Lustre: lnet/lnet/acceptor.c File Reference
lnet/lnet/acceptor.c File Reference
#include <linux/completion.h>
#include <net/sock.h>
#include <lnet/lib-lnet.h>
Defines
#define DEBUG_SUBSYSTEM S_LNET
Functions
int lnet_acceptor_port (void)
static int lnet_accept_magic (__u32 magic, __u32 constant)
module_param (accept, charp, 0444)
MODULE_PARM_DESC (accept,"Accept connections (secure|all|none)")
module_param (accept_port, int, 0444)
MODULE_PARM_DESC (accept_port,"Acceptor's port (same on all nodes)")
module_param (accept_backlog, int, 0444)
MODULE_PARM_DESC (accept_backlog,"Acceptor's listen backlog")
module_param (accept_timeout, int, 0644)
MODULE_PARM_DESC (accept_timeout,"Acceptor's timeout (seconds)")
static int lnet_acceptor_get_tunables (void)
int lnet_acceptor_timeout (void)
void lnet_connect_console_error (int rc, lnet_nid_t peer_nid, __u32 peer_ip, int peer_port)
int lnet_connect (struct socket **sockp, lnet_nid_t peer_nid, __u32 local_ip, __u32 peer_ip, int peer_port)
static int lnet_accept (struct socket *sock, __u32 magic)
static int lnet_acceptor (void *arg)
static int accept2secure (const char *acc, long *sec)
int lnet_acceptor_start (void)
void lnet_acceptor_stop (void)
Variables
static int accept_port = 988
static int accept_backlog = 127
static int accept_timeout = 5
struct {
int pta_shutdown
struct socket * pta_sock
struct completion pta_signal
} lnet_acceptor_state
static char * accept = "secure"
static char * accept_type = NULL
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 37 of file acceptor.c.
Function Documentation
static int accept2secure (const char * acc, long * sec) [inline, static]
Definition at line 446 of file acceptor.c.
References LCONSOLE_ERROR_MSG.
Referenced by lnet_acceptor_start().
static int lnet_accept (struct socket * sock, __u32 magic) [static]
Definition at line 225 of file acceptor.c.
References __swab32s, __swab64s, accept_timeout, CDEBUG, CERROR, D_NET, LASSERT, LCONSOLE_ERROR_MSG, le32_to_cpu, libcfs_nid2str(), lnet_lnd::lnd_accept, lnet_accept_magic(), lnet_net2ni(), lnet_ni_decref(), LNET_NIDNET(), LNET_PROTO_ACCEPTOR_MAGIC, LNET_PROTO_ACCEPTOR_VERSION, LNET_PROTO_MAGIC, LNET_PROTO_TCP_MAGIC, lnet_sock_getaddr(), lnet_sock_read(), lnet_sock_write(), lnet_ni::ni_lnd, lnet_ni::ni_nid, and offsetof.
Referenced by lnet_acceptor().
static int lnet_accept_magic (__u32 magic, __u32 constant) [inline, static]
Definition at line 65 of file acceptor.c.
References __swab32.
Referenced by lnet_accept().
static int lnet_acceptor (void * arg) [static]
Definition at line 350 of file acceptor.c.
References accept_backlog, accept_port, accept_timeout, accept_type, CDEBUG, CERROR, cfs_block_allsigs(), cfs_time_seconds(), CWARN, D_NET, LASSERT, LCONSOLE, LCONSOLE_ERROR_MSG, lnet_accept(), lnet_acceptor_state, lnet_sock_accept(), lnet_sock_getaddr(), lnet_sock_listen(), and lnet_sock_read().
Referenced by lnet_acceptor_start().
static int lnet_acceptor_get_tunables (void) [static]
Definition at line 87 of file acceptor.c.
References accept, and accept_type.
Referenced by lnet_acceptor_start().
int lnet_acceptor_port (void)
Definition at line 59 of file acceptor.c.
References accept_port.
Referenced by ksocknal_launch_packet(), and ksocknal_query().
int lnet_acceptor_start (void)
Definition at line 464 of file acceptor.c.
References accept2secure(), accept_type, CERROR, LASSERT, lnet_acceptor(), lnet_acceptor_get_tunables(), lnet_acceptor_state, and lnet_count_acceptor_nis().
Referenced by lnet_dyn_add_ni(), and LNetNIInit().
void lnet_acceptor_stop (void)
Definition at line 513 of file acceptor.c.
References lnet_acceptor_state.
Referenced by lnet_dyn_del_ni(), LNetNIFini(), and LNetNIInit().
int lnet_acceptor_timeout (void)
Definition at line 97 of file acceptor.c.
References accept_timeout.
Referenced by ksocknal_recv_hello(), ksocknal_send_hello_v1(), and ksocknal_send_hello_v2().
int lnet_connect (struct socket ** sockp, lnet_nid_t peer_nid, __u32 local_ip, __u32 peer_ip, int peer_port)
Definition at line 159 of file acceptor.c.
References accept_timeout, CLASSERT, fatal(), lnet_t::ln_testprotocompat, lnet_connect_console_error(), LNET_LOCK_EX, lnet_net_lock(), lnet_net_unlock(), LNET_PROTO_ACCEPTOR_MAGIC, LNET_PROTO_ACCEPTOR_VERSION, LNET_PROTO_MAGIC, lnet_sock_connect(), lnet_sock_write(), and the_lnet.
Referenced by ksocknal_connect().
void lnet_connect_console_error (int rc, lnet_nid_t peer_nid, __u32 peer_ip, int peer_port)
Definition at line 104 of file acceptor.c.
References CNETERR, LCONSOLE_ERROR_MSG, and libcfs_nid2str().
Referenced by ksocknal_connect(), and lnet_connect().
module_param (accept_timeout , int , 0644)
module_param (accept_backlog , int , 0444)
module_param (accept_port , int , 0444)
module_param (accept , charp , 0444)
MODULE_PARM_DESC (accept_timeout , "Acceptor's timeout (seconds)")
MODULE_PARM_DESC (accept_backlog , "Acceptor's listen backlog")
MODULE_PARM_DESC (accept_port , "Acceptor's port (same on all nodes)")
MODULE_PARM_DESC (accept , "Accept connections (secure|all|none)")
Variable Documentation
char* accept = "secure" [static]
Definition at line 73 of file acceptor.c.
Referenced by lnet_acceptor_get_tunables().
int accept_backlog = 127 [static]
Definition at line 47 of file acceptor.c.
Referenced by lnet_acceptor().
int accept_port = 988 [static]
Definition at line 46 of file acceptor.c.
Referenced by lnet_acceptor(), and lnet_acceptor_port().
int accept_timeout = 5 [static]
Definition at line 48 of file acceptor.c.
Referenced by lnet_accept(), lnet_acceptor(), lnet_acceptor_timeout(), and lnet_connect().
char* accept_type = NULL [static]
Definition at line 84 of file acceptor.c.
Referenced by lnet_acceptor(), lnet_acceptor_get_tunables(), and lnet_acceptor_start().
struct { ... } lnet_acceptor_state [static]
Referenced by lnet_acceptor(), lnet_acceptor_start(), and lnet_acceptor_stop().
int pta_shutdown
Definition at line 51 of file acceptor.c.
struct completion pta_signal
Definition at line 53 of file acceptor.c.
struct socket* pta_sock
Definition at line 52 of file acceptor.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.