Lustre: lnet/lnet/api-ni.c File Reference
lnet/lnet/api-ni.c File Reference
#include <linux/log2.h>
#include <lnet/lib-lnet.h>
Defines
#define DEBUG_SUBSYSTEM S_LNET
#define D_LNI D_CONSOLE
Functions
module_param (ip2nets, charp, 0444)
MODULE_PARM_DESC (ip2nets,"LNET network <- IP table")
module_param (networks, charp, 0444)
MODULE_PARM_DESC (networks,"local networks")
module_param (routes, charp, 0444)
MODULE_PARM_DESC (routes,"routes to non-local networks")
module_param (rnet_htable_size, int, 0444)
MODULE_PARM_DESC (rnet_htable_size,"size of remote network hash table")
static int lnet_ping (lnet_process_id_t id, int timeout_ms, lnet_process_id_t __user *ids, int n_ids)
static char * lnet_get_routes (void)
static char * lnet_get_networks (void)
static void lnet_init_locks (void)
static void lnet_fini_locks (void)
static int lnet_create_remote_nets_table (void)
static void lnet_destroy_remote_nets_table (void)
static void lnet_destroy_locks (void)
static int lnet_create_locks (void)
static void lnet_assert_wire_constants (void)
static lnd_t * lnet_find_lnd_by_type (__u32 type)
void lnet_register_lnd (lnd_t *lnd)
void lnet_unregister_lnd (lnd_t *lnd)
void lnet_counters_get (lnet_counters_t *counters)
void lnet_counters_reset (void)
static __u64 lnet_create_interface_cookie (void)
static char * lnet_res_type2str (int type)
static void lnet_res_container_cleanup (struct lnet_res_container *rec)
static int lnet_res_container_setup (struct lnet_res_container *rec, int cpt, int type)
static void lnet_res_containers_destroy (struct lnet_res_container **recs)
static struct lnet_res_container ** lnet_res_containers_create (int type)
lnet_libhandle_t * lnet_res_lh_lookup (struct lnet_res_container *rec, __u64 cookie)
void lnet_res_lh_initialize (struct lnet_res_container *rec, lnet_libhandle_t *lh)
static int lnet_unprepare (void)
static int lnet_prepare (lnet_pid_t requested_pid)
lnet_ni_t * lnet_net2ni_locked (__u32 net, int cpt)
lnet_ni_t * lnet_net2ni (__u32 net)
static unsigned int lnet_nid_cpt_hash (lnet_nid_t nid, unsigned int number)
int lnet_cpt_of_nid_locked (lnet_nid_t nid)
int lnet_cpt_of_nid (lnet_nid_t nid)
int lnet_islocalnet (__u32 net)
lnet_ni_t * lnet_nid2ni_locked (lnet_nid_t nid, int cpt)
int lnet_islocalnid (lnet_nid_t nid)
int lnet_count_acceptor_nis (void)
static lnet_ping_info_t * lnet_ping_info_create (int num_ni)
static int lnet_get_ni_count (void)
static void lnet_ping_info_free (lnet_ping_info_t *pinfo)
static void lnet_ping_info_destroy (void)
static void lnet_ping_event_handler (lnet_event_t *event)
static int lnet_ping_info_setup (lnet_ping_info_t **ppinfo, lnet_handle_md_t *md_handle, int ni_count, bool set_eq)
static void lnet_ping_md_unlink (lnet_ping_info_t *pinfo, lnet_handle_md_t *md_handle)
static void lnet_ping_info_install_locked (lnet_ping_info_t *ping_info)
static void lnet_ping_target_update (lnet_ping_info_t *pinfo, lnet_handle_md_t md_handle)
static void lnet_ping_target_fini (void)
static int lnet_ni_tq_credits (lnet_ni_t *ni)
static void lnet_ni_unlink_locked (lnet_ni_t *ni)
static void lnet_clear_zombies_nis_locked (void)
static void lnet_shutdown_lndnis (void)
static void lnet_shutdown_lndni (struct lnet_ni *ni)
static int lnet_startup_lndni (struct lnet_ni *ni, struct lnet_ioctl_config_data *conf)
static int lnet_startup_lndnis (struct list_head *nilist)
int lnet_lib_init (void)
Initialize LNet library.
void lnet_lib_exit (void)
Finalize LNet library.
int LNetNIInit (lnet_pid_t requested_pid)
Set LNet PID and start LNet interfaces, routing, and forwarding.
int LNetNIFini ()
Stop LNet interfaces, routing, and forwarding.
static void lnet_fill_ni_info (struct lnet_ni *ni, struct lnet_ioctl_config_data *config)
Grabs the ni data from the ni structure and fills the out parameters.
static int lnet_get_net_config (struct lnet_ioctl_config_data *config)
int lnet_dyn_add_ni (lnet_pid_t requested_pid, struct lnet_ioctl_config_data *conf)
int lnet_dyn_del_ni (__u32 net)
int LNetCtl (unsigned int cmd, void *arg)
LNet ioctl handler.
void LNetDebugPeer (lnet_process_id_t id)
int LNetGetId (unsigned int index, lnet_process_id_t *id)
Retrieve the lnet_process_id_t ID of LNet interface at index.
void LNetSnprintHandle (char *str, int len, lnet_handle_any_t h)
Print a string representation of handle h into buffer str of len bytes.
Variables
lnet_t the_lnet
static char * ip2nets = ""
static char * networks = ""
static char * routes = ""
static int rnet_htable_size = LNET_REMOTE_NETS_HASH_DEFAULT
Define Documentation
#define D_LNI D_CONSOLE
Definition at line 41 of file api-ni.c.
Referenced by lnet_clear_zombies_nis_locked(), and lnet_startup_lndni().
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 37 of file api-ni.c.
Function Documentation
static void lnet_assert_wire_constants (void) [static]
Definition at line 182 of file api-ni.c.
References CLASSERT, LNET_MSG_ACK, LNET_MSG_GET, LNET_MSG_HELLO, LNET_MSG_PUT, LNET_MSG_REPLY, LNET_PROTO_TCP_MAGIC, LNET_PROTO_TCP_VERSION_MAJOR, LNET_PROTO_TCP_VERSION_MINOR, msg, and offsetof.
Referenced by lnet_lib_init().
static void lnet_clear_zombies_nis_locked (void) [static]
Definition at line 1097 of file api-ni.c.
References CDEBUG, cfs_percpt_for_each, cfs_time_seconds(), D_LNI, D_WARNING, LASSERT, libcfs_nid2str(), list_add(), list_del_init(), list_empty(), list_entry, lnet_t::ln_nis_zombie, lnet_lnd::lnd_refcount, lnet_lnd::lnd_shutdown, lnet_lnd::lnd_type, LNET_LOCK_EX, lnet_net_lock(), lnet_net_unlock(), lnet_ni_free(), LOLND, list_head::next, lnet_ni::ni_list, lnet_ni::ni_lnd, lnet_ni::ni_nid, and lnet_ni::ni_refs.
Referenced by lnet_shutdown_lndni(), and lnet_shutdown_lndnis().
int lnet_count_acceptor_nis (void)
Definition at line 820 of file api-ni.c.
References list_entry, list_for_each, lnet_t::ln_nis, lnet_lnd::lnd_accept, lnet_net_lock_current(), lnet_net_unlock(), lnet_ni::ni_list, and lnet_ni::ni_lnd.
Referenced by lnet_acceptor_start(), and lnet_dyn_del_ni().
void lnet_counters_get (lnet_counters_t * counters)
Definition at line 323 of file api-ni.c.
References cfs_percpt_for_each, lnet_counters::drop_count, lnet_counters::drop_length, lnet_counters::errors, lnet_t::ln_counters, LNET_LOCK_EX, lnet_net_lock(), lnet_net_unlock(), lnet_counters::msgs_alloc, lnet_counters::msgs_max, lnet_counters::recv_count, lnet_counters::recv_length, lnet_counters::route_count, lnet_counters::route_length, lnet_counters::send_count, and lnet_counters::send_length.
Referenced by __proc_lnet_stats(), LNetCtl(), and sfw_get_stats().
void lnet_counters_reset (void)
Definition at line 351 of file api-ni.c.
References cfs_percpt_for_each, lnet_t::ln_counters, LNET_LOCK_EX, lnet_net_lock(), and lnet_net_unlock().
Referenced by __proc_lnet_stats().
int lnet_cpt_of_nid (lnet_nid_t nid)
Definition at line 748 of file api-ni.c.
References list_empty(), lnet_t::ln_nis_cpt, LNET_CPT_NUMBER, lnet_cpt_of_nid_locked(), lnet_net_lock_current(), lnet_net_unlock(), and lnet_nid_cpt_hash().
Referenced by brw_client_init(), kiblnd_create_conn(), kiblnd_create_peer(), kiblnd_get_idle_tx(), ksocknal_create_conn(), ksocknal_create_peer(), lnet_create_reply_msg(), lnet_debug_peer(), lnet_match2mt(), lnet_mt_of_match(), lnet_notify(), lnet_parse(), lnet_send(), sfw_run_batch(), and srpc_init_client_rpc().
int lnet_cpt_of_nid_locked (lnet_nid_t nid)
Definition at line 724 of file api-ni.c.
References LASSERT, list_empty(), list_for_each_entry, lnet_t::ln_nis_cpt, LNET_CPT_NUMBER, lnet_nid_cpt_hash(), LNET_NIDNET(), lnet_ni::ni_cptlist, lnet_ni::ni_cpts, lnet_ni::ni_ncpts, and lnet_ni::ni_nid.
Referenced by lnet_cpt_of_nid(), lnet_nid2peer_locked(), lnet_router_checker(), and lnet_send().
static __u64 lnet_create_interface_cookie (void) [static]
Definition at line 364 of file api-ni.c.
References __u64.
Referenced by lnet_prepare().
static int lnet_create_locks (void) [static]
Definition at line 163 of file api-ni.c.
References cfs_percpt_lock_alloc, lnet_t::ln_net_lock, lnet_t::ln_res_lock, lnet_cpt_table, lnet_destroy_locks(), and lnet_init_locks().
Referenced by lnet_lib_init().
static int lnet_create_remote_nets_table (void) [static]
Definition at line 110 of file api-ni.c.
References CERROR, INIT_LIST_HEAD, LASSERT, LIBCFS_ALLOC, lnet_t::ln_remote_nets_hash, lnet_t::ln_remote_nets_hbits, and LNET_REMOTE_NETS_HASH_SIZE.
Referenced by lnet_prepare().
static void lnet_destroy_locks (void) [static]
Definition at line 147 of file api-ni.c.
References cfs_percpt_lock_free(), lnet_t::ln_net_lock, lnet_t::ln_res_lock, and lnet_fini_locks().
Referenced by lnet_create_locks(), and lnet_lib_exit().
static void lnet_destroy_remote_nets_table (void) [static]
Definition at line 130 of file api-ni.c.
References LASSERT, LIBCFS_FREE, list_empty(), lnet_t::ln_remote_nets_hash, and LNET_REMOTE_NETS_HASH_SIZE.
Referenced by lnet_unprepare().
int lnet_dyn_add_ni (lnet_pid_t requested_pid, struct lnet_ioctl_config_data * conf)
Definition at line 1782 of file api-ni.c.
References CERROR, lnet_ioctl_config_data::cfg_config_u, lnet_ioctl_config_data::cfg_net, INIT_LIST_HEAD, list_del_init(), list_empty(), list_entry, lnet_t::ln_api_mutex, lnet_lnd::lnd_accept, lnet_acceptor_start(), lnet_find_net_locked(), lnet_get_ni_count(), LNET_LOCK_EX, lnet_net_lock(), lnet_net_unlock(), lnet_ni_free(), LNET_NIDNET(), lnet_parse_networks(), lnet_ping_info_free(), lnet_ping_info_setup(), lnet_ping_md_unlink(), lnet_ping_target_update(), lnet_shutdown_lndni(), lnet_startup_lndni(), list_head::next, lnet_ni::ni_list, lnet_ni::ni_lnd, and lnet_ni::ni_nid.
Referenced by lnet_dyn_configure().
int lnet_dyn_del_ni (__u32 net)
Definition at line 1860 of file api-ni.c.
References lnet_t::ln_api_mutex, lnet_acceptor_stop(), lnet_count_acceptor_nis(), lnet_get_ni_count(), lnet_net2ni(), LNET_NETTYP(), lnet_ni_decref_locked(), lnet_ping_info_free(), lnet_ping_info_setup(), lnet_ping_md_unlink(), lnet_ping_target_update(), lnet_shutdown_lndni(), and LOLND.
Referenced by lnet_dyn_unconfigure().
static void lnet_fill_ni_info (struct lnet_ni * ni, struct lnet_ioctl_config_data * config) [static]
Grabs the ni data from the ni structure and fills the out parameters.
Parameters:
[in] ni network interface structure
[out] cpt_count the number of cpts the ni is on
[out] nid Network Interface ID
[out] peer_timeout NI peer timeout
[out] peer_tx_crdits NI peer transmit credits
[out] peer_rtr_credits NI peer router credits
[out] max_tx_credits NI max transmit credit
[out] net_config Network configuration
Definition at line 1684 of file api-ni.c.
References ARRAY_SIZE, lnet_ioctl_net_config::cfg_bulk, lnet_ioctl_config_data::cfg_bulk, lnet_ioctl_config_data::cfg_config_u, lnet_ioctl_config_data::cfg_hdr, lnet_ioctl_config_data::cfg_ncpts, lnet_ioctl_config_data::cfg_net, lnet_ioctl_config_data::cfg_nid, CLASSERT, libcfs_ioctl_hdr::ioc_len, LNET_MAX_SHOW_NUM_CPT, lnet_ioctl_net_config::ni_cpts, lnet_ni::ni_cpts, lnet_ioctl_net_config::ni_interfaces, lnet_ni::ni_interfaces, lnet_ni::ni_lnd_tunables, lnet_ni::ni_maxtxcredits, lnet_ni::ni_ncpts, lnet_ni::ni_nid, lnet_ni::ni_peerrtrcredits, lnet_ni::ni_peertimeout, lnet_ni::ni_peertxcredits, lnet_ni::ni_status, and lnet_ioctl_net_config::ni_status.
Referenced by lnet_get_net_config().
static lnd_t* lnet_find_lnd_by_type (__u32 type) [static]
Definition at line 275 of file api-ni.c.
References list_entry, list_for_each, lnet_t::ln_lnds, and lnet_lnd::lnd_type.
Referenced by lnet_register_lnd(), lnet_startup_lndni(), and lnet_unregister_lnd().
static void lnet_fini_locks (void) [static]
Definition at line 105 of file api-ni.c.
Referenced by lnet_destroy_locks().
static int lnet_get_net_config (struct lnet_ioctl_config_data * config) [static]
Definition at line 1753 of file api-ni.c.
References lnet_ioctl_config_data::cfg_bulk, lnet_ioctl_config_data::cfg_count, list_entry, list_for_each, lnet_t::ln_nis, lnet_fill_ni_info(), lnet_net_lock_current(), lnet_net_unlock(), lnet_ni_lock, lnet_ni_unlock, and unlikely.
Referenced by LNetCtl().
static char* lnet_get_networks (void) [static]
Definition at line 72 of file api-ni.c.
References ip2nets, LCONSOLE_ERROR_MSG, lnet_parse_ip2nets(), and networks.
Referenced by LNetNIInit().
static int lnet_get_ni_count (void) [inline, static]
Definition at line 863 of file api-ni.c.
References list_for_each_entry, lnet_t::ln_nis, lnet_net_lock(), lnet_net_unlock(), and lnet_ni::ni_list.
Referenced by lnet_dyn_add_ni(), and lnet_dyn_del_ni().
static char* lnet_get_routes (void) [static]
Definition at line 66 of file api-ni.c.
References routes.
Referenced by LNetNIInit().
static void lnet_init_locks (void) [static]
Definition at line 95 of file api-ni.c.
References lnet_t::ln_api_mutex, lnet_t::ln_eq_wait_lock, lnet_t::ln_eq_waitq, lnet_t::ln_lnd_mutex, and lnet_t::ln_rc_waitq.
Referenced by lnet_create_locks().
int lnet_islocalnet (__u32 net)
Definition at line 768 of file api-ni.c.
References lnet_net2ni_locked(), lnet_net_lock_current(), lnet_net_unlock(), and lnet_ni_decref_locked().
Referenced by lnet_add_route().
int lnet_islocalnid (lnet_nid_t nid)
Definition at line 805 of file api-ni.c.
References lnet_net_lock_current(), lnet_net_unlock(), lnet_ni_decref_locked(), and lnet_nid2ni_locked().
Referenced by lnet_parse(), and lnet_parse_route().
void lnet_lib_exit (void)
Finalize LNet library.
Precondition:
lnet_lib_init() called with success.
All LNet users called LNetNIFini() for matching LNetNIInit() calls.
Definition at line 1490 of file api-ni.c.
References LASSERT, list_empty(), list_entry, lnet_t::ln_lnds, lnet_t::ln_refcount, lnet_destroy_locks(), lnet_unregister_lnd(), and list_head::next.
Referenced by lnet_exit().
int lnet_lib_init (void)
Initialize LNet library.
Automatically called at module loading time. Caller has to call lnet_lib_exit() after a call to lnet_lib_init(), if and only if the latter returned 0. It must be called exactly once.
Return values:
0 on success
-ve on failures.
Definition at line 1431 of file api-ni.c.
References CERROR, cfs_cpt_number(), INIT_LIST_HEAD, LASSERT, lnet_t::ln_cpt_bits, lnet_t::ln_cpt_number, lnet_t::ln_cpt_table, lnet_t::ln_lnds, lnet_t::ln_rc_eqh, lnet_t::ln_rcd_deathrow, lnet_t::ln_rcd_zombie, lnet_t::ln_refcount, lnet_t::ln_remote_nets_hbits, lnet_assert_wire_constants(), LNET_CPT_MAX, lnet_create_locks(), lnet_register_lnd(), LNET_REMOTE_NETS_HASH_DEFAULT, LNET_REMOTE_NETS_HASH_MAX, LNetInvalidateHandle(), rnet_htable_size, and the_lolnd.
Referenced by lnet_init().
lnet_ni_t* lnet_net2ni (__u32 net)
Definition at line 692 of file api-ni.c.
References lnet_net2ni_locked(), lnet_net_lock(), and lnet_net_unlock().
Referenced by kiblnd_passive_connect(), lnet_accept(), lnet_dyn_del_ni(), and LNetCtl().
lnet_ni_t* lnet_net2ni_locked (__u32 net, int cpt)
Definition at line 672 of file api-ni.c.
References LASSERT, list_entry, list_for_each, lnet_t::ln_nis, LNET_LOCK_EX, lnet_ni_addref_locked(), LNET_NIDNET(), and lnet_ni::ni_nid.
Referenced by lnet_islocalnet(), lnet_net2ni(), lnet_nid2peer_locked(), and lnet_send().
static int lnet_ni_tq_credits (lnet_ni_t * ni) [static]
Definition at line 1066 of file api-ni.c.
References credits, LASSERT, max, lnet_ni::ni_maxtxcredits, lnet_ni::ni_ncpts, and lnet_ni::ni_peertxcredits.
Referenced by lnet_startup_lndni().
static void lnet_ni_unlink_locked (lnet_ni_t * ni) [static]
Definition at line 1083 of file api-ni.c.
References LASSERT, list_del_init(), list_empty(), list_move(), lnet_t::ln_nis_zombie, lnet_ni_decref_locked(), lnet_ni::ni_cptlist, and lnet_ni::ni_list.
Referenced by lnet_shutdown_lndni(), and lnet_shutdown_lndnis().
lnet_ni_t* lnet_nid2ni_locked (lnet_nid_t nid, int cpt)
Definition at line 785 of file api-ni.c.
References LASSERT, list_entry, list_for_each, lnet_t::ln_nis, LNET_LOCK_EX, lnet_ni_addref_locked(), and lnet_ni::ni_nid.
Referenced by lnet_islocalnid(), and lnet_send().
static unsigned int lnet_nid_cpt_hash (lnet_nid_t nid, unsigned int number) [static]
Definition at line 705 of file api-ni.c.
References __u64, LASSERT, LNET_CPT_BITS, and LNET_CPT_NUMBER.
Referenced by lnet_cpt_of_nid(), and lnet_cpt_of_nid_locked().
static int lnet_ping (lnet_process_id_t id, int timeout_ms, lnet_process_id_t __user * ids, int n_ids) [static]
Definition at line 2169 of file api-ni.c.
References __swab32, CDEBUG, CERROR, cfs_block_allsigs(), cfs_restore_sigs(), CWARN, D_NET, lnet_md_t::eq_handle, LASSERT, lnet_md_t::length, LIBCFS_ALLOC, LIBCFS_FREE, libcfs_id2str(), LNET_EQ_HANDLER_NONE, LNET_EVENT_REPLY, LNET_MD_TRUNCATE, LNET_NID_ANY, LNET_PID_ANY, LNET_PID_LUSTRE, LNET_PING_FEAT_NI_STATUS, LNET_PROTO_PING_MAGIC, LNET_PROTO_PING_MATCHBITS, LNET_RESERVED_PORTAL, lnet_swap_pinginfo(), LNET_UNLINK, LNetEQAlloc(), LNetEQFree(), LNetEQPoll(), LNetGet(), LNetMDBind(), LNetMDUnlink(), lnet_md_t::max_size, lnet_process_id_t::nid, offsetof, lnet_md_t::options, lnet_process_id_t::pid, lnet_md_t::start, lnet_event_t::status, lnet_md_t::threshold, lnet_event_t::type, lnet_event_t::unlinked, and lnet_md_t::user_ptr.
Referenced by LNetCtl().
static void lnet_ping_event_handler (lnet_event_t * event) [static]
Definition at line 906 of file api-ni.c.
References LNET_PING_FEAT_INVAL, and lnet_event_t::unlinked.
Referenced by lnet_ping_info_setup().
static lnet_ping_info_t* lnet_ping_info_create (int num_ni) [static]
Definition at line 842 of file api-ni.c.
References CERROR, LIBCFS_ALLOC, lnet_t::ln_pid, LNET_PING_FEAT_NI_STATUS, LNET_PROTO_PING_MAGIC, and offsetof.
Referenced by lnet_ping_info_setup().
static void lnet_ping_info_destroy (void) [static]
Definition at line 887 of file api-ni.c.
References list_for_each_entry, lnet_t::ln_nis, lnet_t::ln_ping_info, LNET_LOCK_EX, lnet_net_lock(), lnet_net_unlock(), lnet_ni_lock, lnet_ni_unlock, lnet_ping_info_free(), lnet_ni::ni_list, and lnet_ni::ni_status.
Referenced by lnet_ping_target_fini().
static void lnet_ping_info_free (lnet_ping_info_t * pinfo) [inline, static]
Definition at line 879 of file api-ni.c.
References LIBCFS_FREE, and offsetof.
Referenced by lnet_dyn_add_ni(), lnet_dyn_del_ni(), lnet_ping_info_destroy(), lnet_ping_info_setup(), and lnet_ping_target_update().
static void lnet_ping_info_install_locked (lnet_ping_info_t * ping_info) [static]
Definition at line 998 of file api-ni.c.
References LASSERT, list_for_each_entry, lnet_t::ln_nis, lnet_ni_lock, LNET_NI_STATUS_UP, lnet_ni_unlock, lnet_ni::ni_list, lnet_ni::ni_nid, and lnet_ni::ni_status.
Referenced by lnet_ping_target_update().
static int lnet_ping_info_setup (lnet_ping_info_t ** ppinfo, lnet_handle_md_t * md_handle, int ni_count, bool set_eq) [static]
Definition at line 915 of file api-ni.c.
References CERROR, lnet_md_t::eq_handle, LASSERT, lnet_md_t::length, lnet_t::ln_ping_target_eq, LNET_INS_AFTER, LNET_MD_MANAGE_REMOTE, LNET_MD_OP_GET, LNET_MD_THRESH_INF, LNET_MD_TRUNCATE, LNET_NID_ANY, LNET_PID_ANY, lnet_ping_event_handler(), lnet_ping_info_create(), lnet_ping_info_free(), LNET_PROTO_PING_MATCHBITS, LNET_RESERVED_PORTAL, LNET_RETAIN, LNET_UNLINK, LNetEQAlloc(), LNetEQFree(), LNetMDAttach(), LNetMEAttach(), LNetMEUnlink(), lnet_md_t::max_size, offsetof, lnet_md_t::options, lnet_md_t::start, lnet_md_t::threshold, and lnet_md_t::user_ptr.
Referenced by lnet_dyn_add_ni(), lnet_dyn_del_ni(), and LNetNIInit().
static void lnet_ping_md_unlink (lnet_ping_info_t * pinfo, lnet_handle_md_t * md_handle) [static]
Definition at line 980 of file api-ni.c.
References CDEBUG, cfs_block_allsigs(), cfs_restore_sigs(), cfs_time_seconds(), D_NET, LNET_PING_FEAT_INVAL, LNetInvalidateHandle(), and LNetMDUnlink().
Referenced by lnet_dyn_add_ni(), lnet_dyn_del_ni(), lnet_ping_target_fini(), and lnet_ping_target_update().
static void lnet_ping_target_fini (void) [static]
Definition at line 1052 of file api-ni.c.
References LASSERT, lnet_t::ln_ping_info, lnet_t::ln_ping_target_eq, lnet_t::ln_ping_target_md, lnet_ping_info_destroy(), lnet_ping_md_unlink(), and LNetEQFree().
Referenced by LNetNIFini(), and LNetNIInit().
static void lnet_ping_target_update (lnet_ping_info_t * pinfo, lnet_handle_md_t md_handle) [static]
Definition at line 1023 of file api-ni.c.
References lnet_t::ln_ping_info, lnet_t::ln_ping_target_md, lnet_t::ln_routing, LNET_LOCK_EX, lnet_net_lock(), lnet_net_unlock(), LNET_PING_FEAT_RTE_DISABLED, lnet_ping_info_free(), lnet_ping_info_install_locked(), and lnet_ping_md_unlink().
Referenced by lnet_dyn_add_ni(), lnet_dyn_del_ni(), and LNetNIInit().
static int lnet_prepare (lnet_pid_t requested_pid) [static]
Definition at line 546 of file api-ni.c.
References CERROR, cfs_percpt_alloc(), INIT_LIST_HEAD, LASSERT, lnet_t::ln_counters, lnet_t::ln_delay_rules, lnet_t::ln_drop_rules, lnet_t::ln_eq_container, lnet_t::ln_interface_cookie, lnet_t::ln_md_containers, lnet_t::ln_me_containers, lnet_t::ln_nis, lnet_t::ln_nis_cpt, lnet_t::ln_nis_zombie, lnet_t::ln_pid, lnet_t::ln_refcount, lnet_t::ln_routers, lnet_t::ln_routing, lnet_t::ln_test_peers, LNET_COOKIE_TYPE_EQ, LNET_COOKIE_TYPE_MD, LNET_COOKIE_TYPE_ME, lnet_cpt_table, lnet_create_interface_cookie(), lnet_create_remote_nets_table(), lnet_msg_containers_create(), lnet_peer_tables_create(), LNET_PID_ANY, LNET_PID_USERFLAG, lnet_portals_create(), lnet_res_container_setup(), lnet_res_containers_create(), and lnet_unprepare().
Referenced by LNetNIInit().
void lnet_register_lnd (lnd_t * lnd)
Definition at line 291 of file api-ni.c.
References CDEBUG, D_NET, LASSERT, libcfs_isknown_lnd(), libcfs_lnd2str(), list_add_tail(), lnet_t::ln_lnd_mutex, lnet_t::ln_lnds, lnet_lnd::lnd_list, lnet_lnd::lnd_refcount, lnet_lnd::lnd_type, and lnet_find_lnd_by_type().
Referenced by kgnilnd_init(), ko2iblnd_init(), ksocklnd_init(), and lnet_lib_init().
static void lnet_res_container_cleanup (struct lnet_res_container * rec) [static]
Definition at line 395 of file api-ni.c.
References CERROR, LBUG, LIBCFS_FREE, list_del_init(), list_empty(), list_entry, LNET_COOKIE_TYPE_EQ, LNET_COOKIE_TYPE_MD, lnet_eq_free(), LNET_LH_HASH_SIZE, lnet_md_free(), lnet_res_type2str(), list_head::next, lnet_res_container::rec_active, lnet_res_container::rec_lh_hash, and lnet_res_container::rec_type.
Referenced by lnet_res_container_setup(), lnet_res_containers_destroy(), and lnet_unprepare().
static int lnet_res_container_setup (struct lnet_res_container * rec, int cpt, int type) [static]
Definition at line 436 of file api-ni.c.
References CERROR, INIT_LIST_HEAD, LASSERT, LIBCFS_CPT_ALLOC, LNET_COOKIE_TYPE_BITS, lnet_cpt_table, LNET_LH_HASH_SIZE, lnet_res_container_cleanup(), lnet_res_type2str(), lnet_res_container::rec_active, lnet_res_container::rec_lh_cookie, lnet_res_container::rec_lh_hash, and lnet_res_container::rec_type.
Referenced by lnet_prepare(), and lnet_res_containers_create().
static struct lnet_res_container** lnet_res_containers_create (int type) [static, read]
Definition at line 481 of file api-ni.c.
References CERROR, cfs_percpt_alloc(), cfs_percpt_for_each, lnet_cpt_table, lnet_res_container_setup(), lnet_res_containers_destroy(), and lnet_res_type2str().
Referenced by lnet_prepare().
static void lnet_res_containers_destroy (struct lnet_res_container ** recs) [static]
Definition at line 469 of file api-ni.c.
References cfs_percpt_for_each, cfs_percpt_free(), and lnet_res_container_cleanup().
Referenced by lnet_res_containers_create(), and lnet_unprepare().
void lnet_res_lh_initialize (struct lnet_res_container * rec, lnet_libhandle_t * lh)
Definition at line 529 of file api-ni.c.
References lnet_libhandle::lh_cookie, lnet_libhandle::lh_hash_chain, list_add(), LNET_COOKIE_TYPE_BITS, LNET_CPT_BITS, LNET_LH_HASH_MASK, lnet_res_container::rec_lh_cookie, and lnet_res_container::rec_lh_hash.
Referenced by lnet_md_link(), LNetEQAlloc(), LNetMEAttach(), and LNetMEInsert().
lnet_libhandle_t* lnet_res_lh_lookup (struct lnet_res_container * rec, __u64 cookie)
Definition at line 507 of file api-ni.c.
References head, lnet_libhandle::lh_cookie, list_for_each_entry, LNET_COOKIE_MASK, LNET_COOKIE_TYPE_BITS, LNET_CPT_BITS, LNET_LH_HASH_MASK, lnet_res_container::rec_lh_hash, and lnet_res_container::rec_type.
Referenced by lnet_handle2eq(), lnet_handle2md(), lnet_handle2me(), and lnet_wire_handle2md().
static char* lnet_res_type2str (int type) [static]
Definition at line 380 of file api-ni.c.
References LBUG, LNET_COOKIE_TYPE_EQ, LNET_COOKIE_TYPE_MD, and LNET_COOKIE_TYPE_ME.
Referenced by lnet_res_container_cleanup(), lnet_res_container_setup(), and lnet_res_containers_create().
static void lnet_shutdown_lndni (struct lnet_ni * ni) [static]
Definition at line 1205 of file api-ni.c.
References lnet_t::ln_nportals, lnet_clear_lazy_portal(), lnet_clear_zombies_nis_locked(), LNET_LOCK_EX, lnet_net_lock(), lnet_net_unlock(), lnet_ni_unlink_locked(), and lnet_peer_tables_cleanup().
Referenced by lnet_dyn_add_ni(), lnet_dyn_del_ni(), and lnet_startup_lndni().
static void lnet_shutdown_lndnis (void) [static]
Definition at line 1157 of file api-ni.c.
References LASSERT, list_empty(), list_entry, lnet_t::ln_loni, lnet_t::ln_nis, lnet_t::ln_nis_zombie, lnet_t::ln_nportals, lnet_t::ln_refcount, lnet_t::ln_shutdown, lnet_clear_zombies_nis_locked(), LNET_LOCK_EX, lnet_net_lock(), lnet_net_unlock(), lnet_ni_decref_locked(), lnet_ni_unlink_locked(), lnet_peer_tables_cleanup(), LNetClearLazyPortal(), list_head::next, and lnet_ni::ni_list.
Referenced by lnet_startup_lndnis(), LNetNIFini(), and LNetNIInit().
static int lnet_startup_lndni (struct lnet_ni * ni, struct lnet_ioctl_config_data * conf) [static]
Definition at line 1226 of file api-ni.c.
References CDEBUG, CERROR, lnet_ioctl_config_data::cfg_bulk, lnet_ioctl_config_data::cfg_config_u, lnet_ioctl_config_data::cfg_hdr, lnet_ioctl_config_data::cfg_net, cfs_percpt_for_each, CIBLND, D_LNI, IIBLND, libcfs_ioctl_hdr::ioc_len, LASSERT, LCONSOLE_ERROR_MSG, LIBCFS_ALLOC, libcfs_isknown_lnd(), libcfs_lnd2modname(), libcfs_lnd2str(), libcfs_net2str(), libcfs_nid2str(), list_add_tail(), lnet_t::ln_lnd_mutex, lnet_t::ln_loni, lnet_t::ln_nis, lnet_t::ln_nis_cpt, lnet_lnd::lnd_query, lnet_lnd::lnd_refcount, lnet_lnd::lnd_startup, lnet_lnd::lnd_type, LNET_CPT_NUMBER, lnet_find_lnd_by_type(), LNET_LOCK_EX, lnet_net_lock(), lnet_net_unique(), lnet_net_unlock(), LNET_NETTYP(), lnet_ni_addref(), lnet_ni_addref_locked(), lnet_ni_free(), lnet_ni_tq_credits(), LNET_NIDNET(), lnet_shutdown_lndni(), LOLND, lnet_ni::ni_cptlist, lnet_ni::ni_cpts, lnet_ni::ni_list, lnet_ni::ni_lnd, lnet_ni::ni_lnd_tunables, lnet_ni::ni_maxtxcredits, lnet_ni::ni_nid, lnet_ni::ni_peerrtrcredits, lnet_ni::ni_peertimeout, lnet_ni::ni_peertxcredits, lnet_ni::ni_tx_queues, OPENIBLND, lnet_tx_queue::tq_credits, lnet_tx_queue::tq_credits_max, lnet_tx_queue::tq_credits_min, and VIBLND.
Referenced by lnet_dyn_add_ni(), and lnet_startup_lndnis().
static int lnet_startup_lndnis (struct list_head * nilist) [static]
Definition at line 1397 of file api-ni.c.
References list_del(), list_empty(), list_entry, lnet_shutdown_lndnis(), lnet_startup_lndni(), list_head::next, and lnet_ni::ni_list.
Referenced by LNetNIInit().
static int lnet_unprepare (void) [static]
Definition at line 629 of file api-ni.c.
References cfs_percpt_free(), LASSERT, list_empty(), lnet_t::ln_counters, lnet_t::ln_eq_container, lnet_t::ln_md_containers, lnet_t::ln_me_containers, lnet_t::ln_nis, lnet_t::ln_nis_cpt, lnet_t::ln_nis_zombie, lnet_t::ln_refcount, lnet_t::ln_test_peers, lnet_destroy_remote_nets_table(), lnet_fail_nid(), lnet_msg_containers_destroy(), LNET_NID_ANY, lnet_peer_tables_destroy(), lnet_portals_destroy(), lnet_res_container_cleanup(), lnet_res_containers_destroy(), and lnet_rtrpools_free().
Referenced by lnet_prepare(), LNetNIFini(), and LNetNIInit().
void lnet_unregister_lnd (lnd_t * lnd)
Definition at line 308 of file api-ni.c.
References CDEBUG, D_NET, LASSERT, libcfs_lnd2str(), list_del(), lnet_t::ln_lnd_mutex, lnet_lnd::lnd_list, lnet_lnd::lnd_refcount, lnet_lnd::lnd_type, and lnet_find_lnd_by_type().
Referenced by kgnilnd_exit(), ko2iblnd_exit(), ksocklnd_exit(), and lnet_lib_exit().
module_param (rnet_htable_size , int , 0444)
module_param (routes , charp , 0444)
module_param (networks , charp , 0444)
module_param (ip2nets , charp , 0444)
MODULE_PARM_DESC (rnet_htable_size , "size of remote network hash table")
MODULE_PARM_DESC (routes , "routes to non-local networks")
MODULE_PARM_DESC (networks , "local networks")
MODULE_PARM_DESC (ip2nets)
Variable Documentation
char* ip2nets = "" [static]
Definition at line 46 of file api-ni.c.
Referenced by lnet_get_networks().
char* networks = "" [static]
Definition at line 50 of file api-ni.c.
Referenced by lnet_get_networks(), and lnet_match_networks().
int rnet_htable_size = LNET_REMOTE_NETS_HASH_DEFAULT [static]
Definition at line 58 of file api-ni.c.
Referenced by lnet_lib_init().
char* routes = "" [static]
Definition at line 54 of file api-ni.c.
Referenced by lnet_get_routes().
lnet_t the_lnet
Definition at line 43 of file api-ni.c.
Referenced by __proc_lnet_buffers(), fail_peer(), ksocknal_send_hello(), ksocknal_send_hello_v1(), ksocknal_send_hello_v2(), lnet_add_route(), lnet_add_route_to_rnet(), lnet_build_msg_event(), lnet_check_routes(), lnet_clear_lazy_portal(), lnet_configure(), lnet_connect(), lnet_create_rc_data_locked(), lnet_create_reply_msg(), lnet_del_route(), lnet_delay_rule_add(), lnet_delay_rule_del(), lnet_delay_rule_list(), lnet_delay_rule_match_locked(), lnet_delay_rule_reset(), lnet_destroy_peer_locked(), lnet_drop_message(), lnet_drop_rule_add(), lnet_drop_rule_del(), lnet_drop_rule_list(), lnet_drop_rule_match(), lnet_drop_rule_reset(), lnet_dyn_configure(), lnet_dyn_unconfigure(), lnet_eq_enqueue_event(), lnet_eq_wait_locked(), lnet_fail_nid(), lnet_fault_fini(), lnet_finalize(), lnet_find_net_locked(), lnet_find_peer_locked(), lnet_get_peer_info(), lnet_get_route(), lnet_get_rtr_pool_cfg(), lnet_ioctl(), lnet_md_link(), lnet_msg2bufpool(), lnet_msg_commit(), lnet_msg_containers_create(), lnet_msg_containers_destroy(), lnet_msg_decommit(), lnet_msg_decommit_rx(), lnet_msg_decommit_tx(), lnet_mt_match_head(), lnet_mt_match_md(), lnet_mt_of_attach(), lnet_mt_of_match(), lnet_mt_set_exhausted(), lnet_mt_test_exhausted(), lnet_nid2peer_locked(), lnet_notify(), lnet_parse(), lnet_parse_forward_locked(), lnet_peer_tables_cleanup(), lnet_peer_tables_create(), lnet_peer_tables_destroy(), lnet_ping_router_locked(), lnet_portals_create(), lnet_portals_destroy(), lnet_post_send_locked(), lnet_prep_send(), lnet_prune_rc_data(), lnet_ptl_attach_md(), lnet_ptl_match_md(), lnet_ptl_match_type(), lnet_return_rx_credits_locked(), lnet_router_checker(), lnet_router_checker_active(), lnet_router_checker_start(), lnet_router_checker_stop(), lnet_rtr_addref_locked(), lnet_rtr_decref_locked(), lnet_rtrpools_adjust(), lnet_rtrpools_adjust_helper(), lnet_rtrpools_alloc(), lnet_rtrpools_disable(), lnet_rtrpools_enable(), lnet_rtrpools_free(), lnet_send(), lnet_shuffle_seed(), lnet_unconfigure(), lnet_update_ni_status_locked(), lnet_wait_known_routerstate(), LNetDist(), LNetEQAlloc(), LNetEQFree(), LNetEQPoll(), LNetGet(), LNetMDAttach(), LNetMDBind(), LNetMDUnlink(), LNetMEAttach(), LNetMEInsert(), LNetMEUnlink(), LNetPut(), LNetSetLazyPortal(), proc_lnet_nis(), proc_lnet_peers(), proc_lnet_routers(), and proc_lnet_routes().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.