Lustre: libcfs/include/libcfs/bitmap.h File Reference
libcfs/include/libcfs/bitmap.h File Reference
Data Structures
struct cfs_bitmap
Defines
#define CFS_BITMAP_SIZE(nbits)
#define CFS_FREE_BITMAP(ptr) LIBCFS_FREE(ptr, CFS_BITMAP_SIZE(ptr->size))
#define cfs_foreach_bit(bitmap, pos)
Functions
static struct cfs_bitmap * CFS_ALLOCATE_BITMAP (int size)
static void CFS_RESET_BITMAP (struct cfs_bitmap *bitmap)
static void cfs_bitmap_set (struct cfs_bitmap *bitmap, int nbit)
static void cfs_bitmap_clear (struct cfs_bitmap *bitmap, int nbit)
static int cfs_bitmap_check (struct cfs_bitmap *bitmap, int nbit)
static int cfs_bitmap_test_and_clear (struct cfs_bitmap *bitmap, int nbit)
static int cfs_bitmap_check_empty (struct cfs_bitmap *bitmap)
static void cfs_bitmap_copy (struct cfs_bitmap *new, struct cfs_bitmap *old)
Define Documentation
#define CFS_BITMAP_SIZE (nbits)
Value:
(((nbits / BITS_PER_LONG) + 1) * sizeof(long) + \
        sizeof(struct cfs_bitmap))
Definition at line 44 of file bitmap.h.
Referenced by CFS_ALLOCATE_BITMAP(), cfs_bitmap_copy(), and CFS_RESET_BITMAP().
#define cfs_foreach_bit (bitmap, pos)
Value:
for ((pos) = find_first_bit((bitmap)->data, bitmap->size);      \
             (pos) < (bitmap)->size;                                    \
             (pos) = find_next_bit((bitmap)->data, (bitmap)->size, (pos) + 1))
Definition at line 116 of file bitmap.h.
Referenced by lfsck_assistant_notify_others(), lfsck_layout_assistant_sync_failures(), lfsck_layout_query_all(), lfsck_namespace_assistant_sync_failures(), lfsck_namespace_query_all(), lfsck_query_all(), lfsck_start(), lfsck_start_all(), lfsck_stop_all(), lfsck_tgt_descs_fini(), lod_declare_object_create(), lod_fini_tgt(), lod_pool_remove(), lod_process_config(), lod_putref(), lod_qos_calc_ppo(), lod_recovery_complete(), lod_sub_fini_all_llogs(), lod_sub_init_llog(), lod_sub_init_llogs(), lod_sub_process_config(), lod_sub_recovery_thread(), and lod_sub_stop_recovery_threads().
#define CFS_FREE_BITMAP (ptr) LIBCFS_FREE(ptr, CFS_BITMAP_SIZE(ptr->size))
Definition at line 72 of file bitmap.h.
Referenced by __lfsck_add_target(), lfsck_layout_load_bitmap(), lfsck_layout_master_data_release(), lfsck_namespace_data_release(), lfsck_namespace_load_bitmap(), lfsck_tgt_descs_fini(), lod_fini_tgt(), and ltd_bitmap_resize().
Function Documentation
static struct cfs_bitmap* CFS_ALLOCATE_BITMAP (int size) [static, read]
Definition at line 49 of file bitmap.h.
References CFS_BITMAP_SIZE, LIBCFS_ALLOC, RETURN, and cfs_bitmap::size.
Referenced by __lfsck_add_target(), lfsck_assistant_data_init(), lfsck_layout_load_bitmap(), lfsck_namespace_load_bitmap(), lfsck_tgt_descs_init(), lod_tgt_desc_init(), and ltd_bitmap_resize().
static int cfs_bitmap_check (struct cfs_bitmap * bitmap, int nbit) [inline, static]
Definition at line 87 of file bitmap.h.
References cfs_bitmap::data.
Referenced by __lfsck_add_target(), lfsck_layout_scan_orphan(), lod_add_device(), lod_alloc_ost_list(), lod_alloc_qos(), lod_alloc_rr(), lod_alloc_specific(), lod_del_device(), lod_object_init(), lod_prep_md_striped_create(), lod_qos_calc_rr(), lod_qos_used(), lod_verify_striping(), and validate_lod_and_idx().
static int cfs_bitmap_check_empty (struct cfs_bitmap * bitmap) [inline, static]
Definition at line 100 of file bitmap.h.
References cfs_bitmap::data, and cfs_bitmap::size.
Referenced by lfsck_layout_load_bitmap(), and lfsck_namespace_load_bitmap().
static void cfs_bitmap_clear (struct cfs_bitmap * bitmap, int nbit) [inline, static]
Definition at line 81 of file bitmap.h.
References cfs_bitmap::data.
Referenced by lfsck_del_target(), lfsck_tgt_descs_fini(), lod_add_device(), and lod_putref().
static void cfs_bitmap_copy (struct cfs_bitmap * new, struct cfs_bitmap * old) [inline, static]
Definition at line 106 of file bitmap.h.
References CFS_BITMAP_SIZE, LASSERT, and cfs_bitmap::size.
Referenced by __lfsck_add_target(), and ltd_bitmap_resize().
static void cfs_bitmap_set (struct cfs_bitmap * bitmap, int nbit) [inline, static]
Definition at line 75 of file bitmap.h.
References cfs_bitmap::data.
Referenced by __lfsck_add_target(), lfsck_lad_set_bitmap(), and lod_add_device().
static int cfs_bitmap_test_and_clear (struct cfs_bitmap * bitmap, int nbit) [inline, static]
Definition at line 93 of file bitmap.h.
References cfs_bitmap::data.
static void CFS_RESET_BITMAP (struct cfs_bitmap * bitmap) [inline, static]
Definition at line 62 of file bitmap.h.
References CFS_BITMAP_SIZE, and cfs_bitmap::size.
Referenced by lfsck_layout_load_bitmap(), lfsck_layout_reset(), lfsck_namespace_load_bitmap(), and lfsck_namespace_reset().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.