Lustre: lnet/selftest/brw_test.c File Reference
lnet/selftest/brw_test.c File Reference
#include "selftest.h"
Defines
#define BRW_POISON 0xbeefbeefbeefbeefULL
#define BRW_MAGIC 0xeeb0eeb1eeb2eeb3ULL
#define BRW_MSIZE sizeof(__u64)
Functions
module_param (brw_srv_workitems, int, 0644)
MODULE_PARM_DESC (brw_srv_workitems,"# BRW server workitems")
module_param (brw_inject_errors, int, 0644)
MODULE_PARM_DESC (brw_inject_errors,"# data errors to inject randomly, zero by default")
static void brw_client_fini (sfw_test_instance_t *tsi)
static int brw_client_init (sfw_test_instance_t *tsi)
static int brw_inject_one_error (void)
static void brw_fill_page (struct page *pg, int pattern, __u64 magic)
static int brw_check_page (struct page *pg, int pattern, __u64 magic)
static void brw_fill_bulk (srpc_bulk_t *bk, int pattern, __u64 magic)
static int brw_check_bulk (srpc_bulk_t *bk, int pattern, __u64 magic)
static int brw_client_prep_rpc (sfw_test_unit_t *tsu, lnet_process_id_t dest, srpc_client_rpc_t **rpcpp)
static void brw_client_done_rpc (sfw_test_unit_t *tsu, srpc_client_rpc_t *rpc)
static void brw_server_rpc_done (srpc_server_rpc_t *rpc)
static int brw_bulk_ready (srpc_server_rpc_t *rpc, int status)
static int brw_server_handle (struct srpc_server_rpc *rpc)
void brw_init_test_client (void)
void brw_init_test_service (void)
Variables
static int brw_srv_workitems = SFW_TEST_WI_MAX
static int brw_inject_errors
sfw_test_client_ops_t brw_test_client
srpc_service_t brw_test_service
Define Documentation
#define BRW_MAGIC 0xeeb0eeb1eeb2eeb3ULL
Definition at line 131 of file brw_test.c.
Referenced by brw_bulk_ready(), brw_client_done_rpc(), brw_client_prep_rpc(), brw_fill_page(), and brw_server_handle().
#define BRW_MSIZE sizeof(__u64)
Definition at line 132 of file brw_test.c.
Referenced by brw_check_page(), and brw_fill_page().
#define BRW_POISON 0xbeefbeefbeefbeefULL
Definition at line 130 of file brw_test.c.
Referenced by brw_client_prep_rpc(), and brw_server_handle().
Function Documentation
static int brw_bulk_ready (srpc_server_rpc_t * rpc, int status) [static]
Definition at line 374 of file brw_test.c.
References __swab64s, __u64, brw_check_bulk(), BRW_MAGIC, srpc_msg::brw_reply, srpc_msg::brw_reqst, srpc_buffer::buf_msg, CERROR, LASSERT, libcfs_id2str(), LST_BRW_READ, srpc_msg::msg_body, srpc_msg::msg_magic, srpc_server_rpc::srpc_bulk, SRPC_MSG_MAGIC, srpc_server_rpc::srpc_peer, srpc_server_rpc::srpc_replymsg, and srpc_server_rpc::srpc_reqstbuf.
Referenced by brw_init_test_service().
static int brw_check_bulk (srpc_bulk_t * bk, int pattern, __u64 magic) [static]
Definition at line 230 of file brw_test.c.
References srpc_bulk_t::bk_iovs, srpc_bulk_t::bk_niov, brw_check_page(), CERROR, and lnet_kiov_t::kiov_page.
Referenced by brw_bulk_ready(), and brw_client_done_rpc().
static int brw_check_page (struct page * pg, int pattern, __u64 magic) [static]
Definition at line 178 of file brw_test.c.
References __u64, BRW_MSIZE, CERROR, LASSERT, LBUG, LPX64, LST_BRW_CHECK_FULL, LST_BRW_CHECK_NONE, and LST_BRW_CHECK_SIMPLE.
Referenced by brw_check_bulk().
static void brw_client_done_rpc (sfw_test_unit_t * tsu, srpc_client_rpc_t * rpc) [static]
Definition at line 306 of file brw_test.c.
References __swab32s, __swab64s, __u64, sfw_batch_t::bat_session, brw_check_bulk(), BRW_MAGIC, srpc_msg::brw_reply, srpc_msg::brw_reqst, CDEBUG, CERROR, srpc_client_rpc::crpc_bulk, srpc_client_rpc::crpc_dest, srpc_client_rpc::crpc_replymsg, srpc_client_rpc::crpc_reqstmsg, srpc_client_rpc::crpc_status, D_NET, D_WARNING, LASSERT, libcfs_id2str(), LST_BRW_WRITE, msg, srpc_msg::msg_body, srpc_msg::msg_magic, sfw_session_t::sn_brw_errors, SRPC_MSG_MAGIC, sfw_test_instance::tsi_batch, sfw_test_instance::tsi_stopping, and sfw_test_unit::tsu_instance.
Referenced by brw_init_test_client().
static void brw_client_fini (sfw_test_instance_t * tsi) [static]
Definition at line 52 of file brw_test.c.
References LASSERT, list_for_each_entry, srpc_free_bulk(), sfw_test_instance::tsi_is_client, sfw_test_instance::tsi_units, and sfw_test_unit::tsu_private.
Referenced by brw_client_init(), and brw_init_test_client().
static int brw_client_init (sfw_test_instance_t * tsi) [static]
Definition at line 70 of file brw_test.c.
References sfw_batch_t::bat_session, brw_client_fini(), sfw_test_instance::bulk_v0, sfw_test_instance::bulk_v1, LASSERT, list_for_each_entry, lnet_cpt_of_nid(), LNET_MAX_IOV, LST_BRW_CHECK_FULL, LST_BRW_CHECK_NONE, LST_BRW_CHECK_SIMPLE, LST_BRW_READ, LST_BRW_WRITE, LST_FEAT_BULK_LEN, LST_FEATS_MASK, lnet_process_id_t::nid, sfw_session_t::sn_features, srpc_alloc_bulk(), sfw_test_instance::tsi_batch, sfw_test_instance::tsi_is_client, sfw_test_instance::tsi_u, sfw_test_instance::tsi_units, sfw_test_unit::tsu_dest, and sfw_test_unit::tsu_private.
Referenced by brw_init_test_client().
static int brw_client_prep_rpc (sfw_test_unit_t * tsu, lnet_process_id_t dest, srpc_client_rpc_t ** rpcpp) [static]
Definition at line 248 of file brw_test.c.
References sfw_batch_t::bat_session, brw_fill_bulk(), BRW_MAGIC, BRW_POISON, srpc_msg::brw_reqst, sfw_test_instance::bulk_v0, sfw_test_instance::bulk_v1, srpc_client_rpc::crpc_bulk, srpc_client_rpc::crpc_reqstmsg, LASSERT, LST_BRW_WRITE, LST_FEAT_BULK_LEN, LST_FEATS_MASK, srpc_msg::msg_body, offsetof, sfw_create_test_rpc(), sfw_session_t::sn_features, sfw_test_instance::tsi_batch, sfw_test_instance::tsi_u, sfw_test_unit::tsu_instance, and sfw_test_unit::tsu_private.
Referenced by brw_init_test_client().
static void brw_fill_bulk (srpc_bulk_t * bk, int pattern, __u64 magic) [static]
Definition at line 218 of file brw_test.c.
References srpc_bulk_t::bk_iovs, srpc_bulk_t::bk_niov, brw_fill_page(), and lnet_kiov_t::kiov_page.
Referenced by brw_client_prep_rpc(), and brw_server_handle().
static void brw_fill_page (struct page * pg, int pattern, __u64 magic) [static]
Definition at line 148 of file brw_test.c.
References brw_inject_one_error(), BRW_MAGIC, BRW_MSIZE, LASSERT, LBUG, LST_BRW_CHECK_FULL, LST_BRW_CHECK_NONE, and LST_BRW_CHECK_SIMPLE.
Referenced by brw_fill_bulk().
void brw_init_test_client (void)
Definition at line 484 of file brw_test.c.
References brw_client_done_rpc(), brw_client_fini(), brw_client_init(), brw_client_prep_rpc(), sfw_test_client_ops_t::tso_done_rpc, sfw_test_client_ops_t::tso_fini, sfw_test_client_ops_t::tso_init, and sfw_test_client_ops_t::tso_prep_rpc.
Referenced by sfw_startup().
void brw_init_test_service (void)
Definition at line 493 of file brw_test.c.
References brw_bulk_ready(), brw_server_handle(), brw_srv_workitems, SRPC_SERVICE_BRW, srpc_service::sv_bulk_ready, srpc_service::sv_handler, srpc_service::sv_id, srpc_service::sv_name, and srpc_service::sv_wi_total.
Referenced by sfw_startup().
static int brw_inject_one_error (void) [static]
Definition at line 134 of file brw_test.c.
References brw_inject_errors.
Referenced by brw_fill_page().
static int brw_server_handle (struct srpc_server_rpc * rpc) [static]
Definition at line 410 of file brw_test.c.
References __swab32, __swab32s, __swab64s, brw_fill_bulk(), BRW_MAGIC, BRW_POISON, srpc_msg::brw_reply, srpc_msg::brw_reqst, brw_server_rpc_done(), srpc_buffer::buf_msg, LASSERT, LNET_MAX_IOV, LST_BRW_CHECK_FULL, LST_BRW_CHECK_NONE, LST_BRW_CHECK_SIMPLE, LST_BRW_READ, LST_BRW_WRITE, LST_FEAT_BULK_LEN, LST_FEATS_MASK, srpc_msg::msg_body, srpc_msg::msg_magic, srpc_msg::msg_ses_feats, srpc_msg::msg_type, srpc_service_cd::scd_cpt, srpc_service_cd::scd_svc, sfw_alloc_pages(), srpc_server_rpc::srpc_bulk, srpc_server_rpc::srpc_done, SRPC_MSG_MAGIC, srpc_server_rpc::srpc_replymsg, srpc_server_rpc::srpc_reqstbuf, srpc_server_rpc::srpc_scd, srpc_service2request(), SRPC_SERVICE_BRW, and srpc_service::sv_id.
Referenced by brw_init_test_service().
static void brw_server_rpc_done (srpc_server_rpc_t * rpc) [static]
Definition at line 354 of file brw_test.c.
References srpc_bulk_t::bk_niov, srpc_bulk_t::bk_sink, CDEBUG, CERROR, D_NET, libcfs_id2str(), sfw_free_pages(), srpc_server_rpc::srpc_bulk, srpc_server_rpc::srpc_peer, and srpc_server_rpc::srpc_status.
Referenced by brw_server_handle().
module_param (brw_inject_errors , int , 0644)
module_param (brw_srv_workitems , int , 0644)
MODULE_PARM_DESC (brw_inject_errors , "# data errors to inject randomly, zero by default")
MODULE_PARM_DESC (brw_srv_workitems , "# BRW server workitems")
Variable Documentation
int brw_inject_errors [static]
Definition at line 47 of file brw_test.c.
Referenced by brw_inject_one_error().
int brw_srv_workitems = SFW_TEST_WI_MAX [static]
Definition at line 43 of file brw_test.c.
Referenced by brw_init_test_service().
sfw_test_client_ops_t brw_test_client
Definition at line 483 of file brw_test.c.
Referenced by sfw_startup().
srpc_service_t brw_test_service
Definition at line 490 of file brw_test.c.
Referenced by sfw_startup().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.