Lustre: lustre/utils/gss/cacheio.c File Reference
lustre/utils/gss/cacheio.c File Reference
#include "cacheio.h"
#include <stdio.h>
#include <ctype.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <time.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include "err_util.h"
Defines
#define isodigit(c) (isdigit(c) && c <= '7')
#define READLINE_BUFFER_INCREMENT 2048
Functions
void qword_add (char **bpp, int *lp, char *str)
void qword_addhex (char **bpp, int *lp, char *buf, int blen)
void qword_addint (char **bpp, int *lp, int n)
void qword_adduint (char **bpp, int *lp, unsigned int n)
void qword_addeol (char **bpp, int *lp)
int qword_print (FILE *f, char *str)
int qword_printhex (FILE *f, char *str, int slen)
void qword_printint (FILE *f, int num)
int qword_eol (FILE *f)
int qword_get (char **bpp, char *dest, int bufsize)
int qword_get_int (char **bpp, int *anint)
int readline (int fd, char **buf, int *lenp)
Variables
static char qword_buf [8192]
static char tmp_buf [8192]
Define Documentation
#define isodigit (c) (isdigit(c) && c <= '7')
Definition at line 206 of file cacheio.c.
Referenced by qword_get(), and str_is_id().
#define READLINE_BUFFER_INCREMENT 2048
Definition at line 270 of file cacheio.c.
Referenced by readline().
Function Documentation
void qword_add (char ** bpp, int * lp, char * str)
Definition at line 61 of file cacheio.c.
Referenced by qword_print().
void qword_addeol (char ** bpp, int * lp)
Definition at line 146 of file cacheio.c.
Referenced by send_response().
void qword_addhex (char ** bpp, int * lp, char * buf, int blen)
Definition at line 96 of file cacheio.c.
Referenced by qword_printhex(), rsi_request(), and send_response().
void qword_addint (char ** bpp, int * lp, int n)
Definition at line 124 of file cacheio.c.
Referenced by send_response().
void qword_adduint (char ** bpp, int * lp, unsigned int n)
Definition at line 135 of file cacheio.c.
Referenced by send_response().
int qword_eol (FILE * f)
Definition at line 195 of file cacheio.c.
References printerr.
Referenced by do_svc_downcall().
int qword_get (char ** bpp, char * dest, int bufsize)
Definition at line 207 of file cacheio.c.
References isodigit.
Referenced by handle_nullreq(), qword_get_int(), rsc_parse(), and rsi_parse().
int qword_get_int (char ** bpp, int * anint)
Definition at line 256 of file cacheio.c.
References buf, and qword_get().
int qword_print (FILE * f, char * str)
Definition at line 157 of file cacheio.c.
References printerr, qword_add(), qword_buf, and tmp_buf.
Referenced by do_svc_downcall().
int qword_printhex (FILE * f, char * str, int slen)
Definition at line 173 of file cacheio.c.
References printerr, qword_addhex(), qword_buf, and tmp_buf.
Referenced by do_svc_downcall().
void qword_printint (FILE * f, int num)
Definition at line 189 of file cacheio.c.
References printerr.
Referenced by do_svc_downcall().
int readline (int fd, char ** buf, int * lenp)
Definition at line 272 of file cacheio.c.
References printerr, and READLINE_BUFFER_INCREMENT.
Referenced by handle_nullreq(), Parser_commands(), Parser_getbool(), Parser_getint(), and Parser_getstr().
Variable Documentation
char qword_buf[8192] [static]
Definition at line 155 of file cacheio.c.
Referenced by qword_print(), and qword_printhex().
char tmp_buf[8192] [static]
Definition at line 156 of file cacheio.c.
Referenced by enable_default_ext4_features(), main(), qword_print(), qword_printhex(), and rsc_parse().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.