Lustre: lustre/tests/mpi/cascading_rw.c File Reference
lustre/tests/mpi/cascading_rw.c File Reference
#include <config.h>
#include <mpi.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <asm/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <sys/ioctl.h>
#include <getopt.h>
#include <errno.h>
#include <lustre/lustreapi.h>
#include "lp_utils.h"
#include <ioctl.h>
Functions
void rw_file (char *name, long stride, unsigned int seed)
void cascading_rw (long stride, unsigned int seed)
void usage (char *proc)
int main (int argc, char *argv[])
Variables
int rank = 0
int size = 0
char * testdir = NULL
Function Documentation
void cascading_rw (long stride, unsigned int seed)
Definition at line 273 of file cascading_rw.c.
References begin, end, remove_file(), and rw_file().
Referenced by main().
int main (int argc, char * argv[])
Definition at line 310 of file cascading_rw.c.
References cascading_rw(), debug, lp_gethostname(), optarg, rank, seed, size, testdir, timestamp(), usage, and verbose.
void rw_file (char * name, long stride, unsigned int seed)
Definition at line 65 of file cascading_rw.c.
References buf, dump_diff(), errmsg, FAIL, FILEMODE, filename, fill_stride(), LL_IOC_LOV_SETSTRIPE, LOV_USER_MAGIC, lov_user_md, MAX_FILENAME_LEN, O_LOV_DELAY_CREATE, page_size, rank, remove_file_or_dir(), size, and testdir.
Referenced by cascading_rw().
void usage (char * proc)
Definition at line 287 of file cascading_rw.c.
References rank.
Variable Documentation
int rank = 0
Definition at line 60 of file cascading_rw.c.
int size = 0
Definition at line 61 of file cascading_rw.c.
char* testdir = NULL
Definition at line 63 of file cascading_rw.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.