Lustre: lustre/obdclass/cl_internal.h File Reference
lustre/obdclass/cl_internal.h File Reference
Data Structures
struct cl_thread_counters
Counters used to check correctness of cl_lock interface usage.
struct cl_thread_info
Thread local state internal for generic cl-code.
Defines
#define CLT_PVEC_SIZE (14)
Enumerations
enum clt_nesting_level { CNL_TOP, CNL_SUB, CNL_NR }
Possible levels of the nesting.
Functions
struct cl_thread_info * cl_env_info (const struct lu_env *env)
void cl_page_disown0 (const struct lu_env *env, struct cl_io *io, struct cl_page *pg)
Define Documentation
#define CLT_PVEC_SIZE (14)
Definition at line 43 of file cl_internal.h.
Enumeration Type Documentation
enum clt_nesting_level
Possible levels of the nesting.
Currently this is 2: there are "top" entities (files, extent locks), and "sub" entities (stripes and stripe locks). This is used only for debugging counters right now.
Enumerator:
CNL_TOP
CNL_SUB
CNL_NR
Definition at line 50 of file cl_internal.h.
Function Documentation
struct cl_thread_info* cl_env_info (const struct lu_env * env) [read]
Definition at line 1290 of file cl_object.c.
References cl_key, lu_env::le_ctx, and lu_context_key_get().
Referenced by cl_io_fini(), cl_io_init(), cl_io_is_going(), cl_io_sub_init(), cl_io_submit_sync(), cl_io_unlock(), and cl_lock_request().
void cl_page_disown0 (const struct lu_env * env, struct cl_io * io, struct cl_page * pg)
Definition at line 527 of file cl_page.c.
References cl_page_invariant(), CL_PAGE_INVOID_REVERSE, CL_PAGE_OP, cl_page_owner_clear(), cl_page_state_set(), cl_page::cp_state, CPS_CACHED, CPS_FREEING, CPS_OWNED, ENTRY, EXIT, PINVRNT, and state.
Referenced by cl_page_disown(), cl_page_list_disown(), and cl_page_own0().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.