Lustre: lustre/obdclass/cl_object.c File Reference
lustre/obdclass/cl_object.c File Reference
#include <libcfs/libcfs.h>
#include <obd_class.h>
#include <obd_support.h>
#include <lustre_fid.h>
#include <libcfs/list.h>
#include <libcfs/libcfs_hash.h>
#include <cl_object.h>
#include <lu_object.h>
#include "cl_internal.h"
Data Structures
struct cl_env
Defines
#define DEBUG_SUBSYSTEM S_CLASS
#define CL_ENV_INC(counter)
#define CL_ENV_DEC(counter)
Functions
int cl_object_header_init (struct cl_object_header *h)
Initialize cl_object_header.
void cl_object_header_fini (struct cl_object_header *h)
Finalize cl_object_header.
struct cl_object * cl_object_find (const struct lu_env *env, struct cl_device *cd, const struct lu_fid *fid, const struct cl_object_conf *c)
Returns a cl_object with a given fid.
void cl_object_put (const struct lu_env *env, struct cl_object *o)
Releases a reference on o.
void cl_object_get (struct cl_object *o)
Acquire an additional reference to the object o.
struct cl_object * cl_object_top (struct cl_object *o)
Returns the top-object for a given o.
static spinlock_t * cl_object_attr_guard (struct cl_object *o)
Returns pointer to the lock protecting data-attributes for the given object o.
void cl_object_attr_lock (struct cl_object *o) __acquires(cl_object_attr_guard(o))
Locks data-attributes.
void cl_object_attr_unlock (struct cl_object *o) __releases(cl_object_attr_guard(o))
Releases data-attributes lock, acquired by cl_object_attr_lock().
int cl_object_attr_get (const struct lu_env *env, struct cl_object *obj, struct cl_attr *attr)
Returns data-attributes of an object obj.
int cl_object_attr_update (const struct lu_env *env, struct cl_object *obj, const struct cl_attr *attr, unsigned v)
Updates data-attributes of an object obj.
int cl_object_glimpse (const struct lu_env *env, struct cl_object *obj, struct ost_lvb *lvb)
Notifies layers (bottom-to-top) that glimpse AST was received.
int cl_conf_set (const struct lu_env *env, struct cl_object *obj, const struct cl_object_conf *conf)
Updates a configuration of an object obj.
int cl_object_prune (const struct lu_env *env, struct cl_object *obj)
Prunes caches of pages and locks for this object.
int cl_object_getstripe (const struct lu_env *env, struct cl_object *obj, struct lov_user_md __user *uarg)
Get stripe information of this object.
int cl_object_fiemap (const struct lu_env *env, struct cl_object *obj, struct ll_fiemap_info_key *key, struct fiemap *fiemap, size_t *buflen)
Get fiemap extents from file object.
int cl_object_layout_get (const struct lu_env *env, struct cl_object *obj, struct cl_layout *cl)
loff_t cl_object_maxbytes (struct cl_object *obj)
void cl_object_kill (const struct lu_env *env, struct cl_object *obj)
Helper function removing all object locks, and marking object for deletion.
void cache_stats_init (struct cache_stats *cs, const char *name)
These are not exported so far.
static int cache_stats_print (const struct cache_stats *cs, struct seq_file *m, int h)
static void cl_env_percpu_refill (void)
int cl_site_init (struct cl_site *s, struct cl_device *d)
Initialize client site.
void cl_site_fini (struct cl_site *s)
Finalize client site.
int cl_site_stats_print (const struct cl_site *site, struct seq_file *m)
Outputs client site statistical counters into a buffer.
static DEFINE_SPINLOCK (cl_envs_guard)
static void cl_env_init0 (struct cl_env *cle, void *debug)
static unsigned cl_env_hops_hash (struct cfs_hash *lh, const void *key, unsigned mask)
static void * cl_env_hops_obj (struct hlist_node *hn)
static int cl_env_hops_keycmp (const void *key, struct hlist_node *hn)
static void cl_env_hops_noop (struct cfs_hash *hs, struct hlist_node *hn)
static struct cl_env * cl_env_fetch (void)
static void cl_env_attach (struct cl_env *cle)
static void cl_env_do_detach (struct cl_env *cle)
static int cl_env_store_init (void)
static void cl_env_store_fini (void)
static struct cl_env * cl_env_detach (struct cl_env *cle)
static struct lu_env * cl_env_new (__u32 ctx_tags, __u32 ses_tags, void *debug)
static void cl_env_fini (struct cl_env *cle)
static struct lu_env * cl_env_obtain (void *debug)
static struct cl_env * cl_env_container (struct lu_env *env)
struct lu_env * cl_env_peek (__u16 *refcheck)
struct lu_env * cl_env_get (__u16 *refcheck)
Returns lu_env: if there already is an environment associated with the current thread, it is returned, otherwise, new environment is allocated.
struct lu_env * cl_env_alloc (__u16 *refcheck, __u32 tags)
Forces an allocation of a fresh environment with given tags.
static void cl_env_exit (struct cl_env *cle)
unsigned cl_env_cache_purge (unsigned nr)
Finalizes and frees a given number of cached environments.
void cl_env_put (struct lu_env *env, __u16 *refcheck)
Release an environment.
void * cl_env_reenter (void)
Declares a point of re-entrancy.
void cl_env_reexit (void *cookie)
Exits re-entrancy.
void cl_env_implant (struct lu_env *env, __u16 *refcheck)
Setup user-supplied env as a current environment.
void cl_env_unplant (struct lu_env *env, __u16 *refcheck)
Detach environment installed earlier by cl_env_implant().
struct lu_env * cl_env_nested_get (struct cl_env_nest *nest)
void cl_env_nested_put (struct cl_env_nest *nest, struct lu_env *env)
void cl_attr2lvb (struct ost_lvb *lvb, const struct cl_attr *attr)
Converts struct cl_attr to struct ost_lvb.
void cl_lvb2attr (struct cl_attr *attr, const struct ost_lvb *lvb)
Converts struct ost_lvb to struct cl_attr.
static int cl_env_percpu_init (void)
static void cl_env_percpu_fini (void)
void cl_env_percpu_put (struct lu_env *env)
struct lu_env * cl_env_percpu_get ()
struct cl_device * cl_type_setup (const struct lu_env *env, struct lu_site *site, struct lu_device_type *ldt, struct lu_device *next)
void cl_stack_fini (const struct lu_env *env, struct cl_device *cl)
Finalize device stack by calling lu_stack_fini().
struct cl_thread_info * cl_env_info (const struct lu_env *env)
LU_KEY_INIT_FINI (cl0, struct cl_thread_info)
static void * cl_key_init (const struct lu_context *ctx, struct lu_context_key *key)
static void cl_key_fini (const struct lu_context *ctx, struct lu_context_key *key, void *data)
static void cl_key_exit (const struct lu_context *ctx, struct lu_context_key *key, void *data)
int cl_global_init (void)
Global initialization of cl-data.
void cl_global_fini (void)
Finalization of global cl-data.
Variables
static struct kmem_cache * cl_env_kmem
static struct lock_class_key cl_attr_guard_class
Lock class of cl_object_header::coh_attr_guard.
static struct cache_stats cl_env_stats
static struct list_head cl_envs
The most efficient way is to store cl_env pointer in task specific structures.
static unsigned cl_envs_cached_nr = 0
static unsigned cl_envs_cached_max = 128
static struct cfs_hash * cl_env_hash
static struct cfs_hash_ops cl_env_hops
static struct cl_env cl_env_percpu [NR_CPUS]
static struct lu_context_key cl_key
static struct lu_kmem_descr cl_object_caches []
Define Documentation
#define CL_ENV_DEC (counter)
Definition at line 630 of file cl_object.c.
Referenced by cl_env_fini(), cl_env_percpu_put(), and cl_env_put().
#define CL_ENV_INC (counter)
Definition at line 629 of file cl_object.c.
Referenced by cl_env_init0(), cl_env_new(), and cl_env_peek().
#define DEBUG_SUBSYSTEM S_CLASS
Definition at line 51 of file cl_object.c.
Function Documentation
static int cache_stats_print (const struct cache_stats * cs, struct seq_file * m, int h) [static]
Definition at line 452 of file cl_object.c.
References cache_stats::cs_name, CS_NAMES, CS_NR, and cache_stats::cs_stats.
Referenced by cl_site_stats_print().
static void cl_env_attach (struct cl_env * cle) [inline, static]
Definition at line 702 of file cl_object.c.
References cl_env::ce_node, cl_env::ce_owner, cfs_hash_add_unique(), and LASSERT.
Referenced by cl_env_get(), cl_env_implant(), cl_env_percpu_get(), and cl_env_reexit().
static struct cl_env* cl_env_container (struct lu_env * env) [static, read]
Definition at line 867 of file cl_object.c.
References cl_env::ce_lu.
Referenced by cl_env_alloc(), cl_env_get(), cl_env_implant(), cl_env_percpu_put(), cl_env_put(), and cl_env_unplant().
static struct cl_env* cl_env_detach (struct cl_env * cle) [static, read]
Definition at line 779 of file cl_object.c.
References cl_env::ce_owner, cl_env_do_detach(), and cl_env_fetch().
Referenced by cl_env_percpu_put(), cl_env_put(), cl_env_reenter(), cl_env_reexit(), and cl_env_unplant().
static void cl_env_do_detach (struct cl_env * cle) [inline, static]
Definition at line 715 of file cl_object.c.
References cl_env::ce_node, cl_env::ce_owner, cfs_hash_del(), and LASSERT.
Referenced by cl_env_detach().
static void cl_env_exit (struct cl_env * cle) [static]
Definition at line 948 of file cl_object.c.
References cl_env::ce_lu, cl_env::ce_owner, cl_env::ce_ses, LASSERT, lu_env::le_ctx, and lu_context_exit().
Referenced by cl_env_put().
static struct cl_env* cl_env_fetch (void) [static, read]
Definition at line 693 of file cl_object.c.
References cl_env::ce_magic, cfs_hash_lookup(), cl_env_init0(), ergo, and LASSERT.
Referenced by cl_env_detach(), and cl_env_peek().
static void cl_env_fini (struct cl_env * cle) [static]
Definition at line 825 of file cl_object.c.
References cl_env::ce_lu, cl_env::ce_ses, CL_ENV_DEC, cl_env_kmem, lu_env::le_ctx, lu_context_fini(), and OBD_SLAB_FREE_PTR.
Referenced by cl_env_cache_purge(), cl_env_obtain(), and cl_env_put().
static unsigned cl_env_hops_hash (struct cfs_hash * lh, const void * key, unsigned mask) [static]
Definition at line 652 of file cl_object.c.
References __u64, cfs_hash_u32_hash(), and cfs_hash_u64_hash().
static int cl_env_hops_keycmp (const void * key, struct hlist_node * hn) [static]
Definition at line 670 of file cl_object.c.
References cl_env::ce_owner, cl_env_hops_obj(), and LASSERT.
static void cl_env_hops_noop (struct cfs_hash * hs, struct hlist_node * hn) [static]
Definition at line 678 of file cl_object.c.
References cl_env::ce_magic, cl_env::ce_node, cl_env_init0(), hlist_entry, and LASSERT.
static void* cl_env_hops_obj (struct hlist_node * hn) [static]
Definition at line 662 of file cl_object.c.
References cl_env::ce_magic, cl_env::ce_node, cl_env_init0(), hlist_entry, and LASSERT.
Referenced by cl_env_hops_keycmp().
struct cl_thread_info* cl_env_info (const struct lu_env * env) [read]
Definition at line 1290 of file cl_object.c.
References cl_key, lu_env::le_ctx, and lu_context_key_get().
Referenced by cl_io_fini(), cl_io_init(), cl_io_is_going(), cl_io_sub_init(), cl_io_submit_sync(), cl_io_unlock(), and cl_lock_request().
static void cl_env_init0 (struct cl_env * cle, void * debug) [static]
Definition at line 633 of file cl_object.c.
References cl_env::ce_debug, cl_env::ce_magic, cl_env::ce_owner, cl_env::ce_ref, CL_ENV_INC, and LASSERT.
Referenced by cl_env_fetch(), cl_env_hops_noop(), cl_env_hops_obj(), cl_env_new(), cl_env_obtain(), cl_env_percpu_get(), and cl_env_percpu_init().
static struct lu_env* cl_env_new (__u32 ctx_tags, __u32 ses_tags, void * debug) [static, read]
Definition at line 790 of file cl_object.c.
References cl_env::ce_linkage, cl_env::ce_lu, cl_env::ce_magic, cl_env::ce_ses, CL_ENV_INC, cl_env_init0(), cl_env_kmem, INIT_LIST_HEAD, LCT_CL_THREAD, LCT_SESSION, lu_env::le_ses, lu_context_enter(), lu_context_init(), lu_env_fini(), lu_env_init(), OBD_SLAB_ALLOC_PTR_GFP, and OBD_SLAB_FREE_PTR.
Referenced by cl_env_alloc(), and cl_env_obtain().
static struct lu_env* cl_env_obtain (void * debug) [static, read]
Definition at line 833 of file cl_object.c.
References cl_env::ce_linkage, cl_env::ce_lu, cl_env::ce_ses, cl_env_fini(), cl_env_init0(), cl_env_new(), cl_envs, ENTRY, equi, LASSERT, lu_env::le_ctx, list_del_init(), list_empty(), lu_context_enter(), lu_context_tags_default, lu_env_refill(), lu_session_tags_default, list_head::next, and RETURN.
Referenced by cl_env_get().
static void cl_env_percpu_fini (void) [static]
Definition at line 1188 of file cl_object.c.
References cl_env::ce_lu, cl_env::ce_ses, cl_env_percpu, lu_context_exit(), lu_context_fini(), and lu_env_fini().
Referenced by cl_global_fini().
static int cl_env_percpu_init (void) [static]
Definition at line 1146 of file cl_object.c.
References cl_env::ce_linkage, cl_env::ce_lu, cl_env::ce_magic, cl_env::ce_ses, cl_env_init0(), cl_env_percpu, INIT_LIST_HEAD, LCT_CL_THREAD, LCT_NOREF, LCT_REMEMBER, LCT_SESSION, lu_env::le_ses, lu_context_enter(), lu_context_exit(), lu_context_fini(), lu_context_init(), lu_env_fini(), and lu_env_init().
Referenced by cl_global_init().
static void cl_env_percpu_refill (void) [static]
Definition at line 1201 of file cl_object.c.
References cl_env::ce_lu, cl_env_percpu, and lu_env_refill().
Referenced by cl_site_init().
static void cl_env_store_fini (void) [static]
Definition at line 737 of file cl_object.c.
References cfs_hash_putref().
Referenced by cl_global_fini(), and cl_global_init().
static int cl_env_store_init (void) [static]
Definition at line 726 of file cl_object.c.
References cfs_hash_create(), CFS_HASH_MAX_THETA, CFS_HASH_MIN_THETA, CFS_HASH_RW_BKTLOCK, HASH_CL_ENV_BITS, and HASH_CL_ENV_BKT_BITS.
Referenced by cl_global_init().
void cl_global_fini (void)
Finalization of global cl-data.
Dual to cl_global_init().
Definition at line 1403 of file cl_object.c.
References cl_env_percpu_fini(), cl_env_store_fini(), lu_context_key_degister(), and lu_kmem_fini().
Referenced by obdclass_exit().
int cl_global_init (void)
Global initialization of cl-data.
Create kmem caches, register lu_context_key's, etc.
See also:
cl_global_fini()
Definition at line 1365 of file cl_object.c.
References cl_env_percpu_init(), cl_env_store_fini(), cl_env_store_init(), cl_envs, INIT_LIST_HEAD, lu_context_key_degister(), LU_CONTEXT_KEY_INIT, lu_context_key_register(), lu_kmem_fini(), and lu_kmem_init().
Referenced by obdclass_init().
static void cl_key_exit (const struct lu_context * ctx, struct lu_context_key * key, void * data) [static]
Definition at line 1325 of file cl_object.c.
References ARRAY_SIZE, cl_thread_info::clt_counters, cl_thread_counters::ctc_locks_locked, cl_thread_counters::ctc_nr_held, cl_thread_counters::ctc_nr_locks_acquired, cl_thread_counters::ctc_nr_locks_locked, cl_thread_counters::ctc_nr_used, LASSERT, lu_ref_fini(), and lu_ref_init().
static void cl_key_fini (const struct lu_context * ctx, struct lu_context_key * key, void * data) [static]
Definition at line 1313 of file cl_object.c.
References ARRAY_SIZE, cl_thread_info::clt_counters, cl_thread_counters::ctc_locks_locked, and lu_ref_fini().
static void* cl_key_init (const struct lu_context * ctx, struct lu_context_key * key) [static]
Definition at line 1298 of file cl_object.c.
References ARRAY_SIZE, cl_thread_info::clt_counters, cl_thread_counters::ctc_locks_locked, and lu_ref_init().
static spinlock_t* cl_object_attr_guard (struct cl_object * o) [static]
Returns pointer to the lock protecting data-attributes for the given object o.
Data-attributes are protected by the cl_object_header::coh_attr_guard spin-lock in the top-object.
See also:
cl_attr, cl_object_attr_lock(), cl_object_operations::coo_attr_get().
Definition at line 168 of file cl_object.c.
References cl_object_header(), cl_object_top(), and cl_object_header::coh_attr_guard.
Referenced by cl_object_attr_get(), cl_object_attr_lock(), cl_object_attr_unlock(), and cl_object_attr_update().
static DEFINE_SPINLOCK (cl_envs_guard) [static]
LU_KEY_INIT_FINI (cl0 , struct cl_thread_info)
Variable Documentation
struct lock_class_key cl_attr_guard_class [static]
Lock class of cl_object_header::coh_attr_guard.
Definition at line 67 of file cl_object.c.
Referenced by cl_object_header_init().
struct cfs_hash* cl_env_hash [static]
Definition at line 650 of file cl_object.c.
struct cfs_hash_ops cl_env_hops [static]
Initial value:
 {
        .hs_hash        = cl_env_hops_hash,
        .hs_key         = cl_env_hops_obj,
        .hs_keycmp      = cl_env_hops_keycmp,
        .hs_object      = cl_env_hops_obj,
        .hs_get         = cl_env_hops_noop,
        .hs_put_locked  = cl_env_hops_noop,
}
Definition at line 684 of file cl_object.c.
struct kmem_cache* cl_env_kmem [static]
Definition at line 64 of file cl_object.c.
Referenced by cl_env_fini(), and cl_env_new().
struct cl_env cl_env_percpu[NR_CPUS] [static]
Definition at line 1144 of file cl_object.c.
Referenced by cl_env_percpu_fini(), cl_env_percpu_get(), cl_env_percpu_init(), cl_env_percpu_put(), and cl_env_percpu_refill().
struct cache_stats cl_env_stats [static]
Initial value:
 {
        .cs_name    = "envs",
        .cs_stats = { ATOMIC_INIT(0), }
}
Definition at line 509 of file cl_object.c.
struct list_head cl_envs [static]
The most efficient way is to store cl_env pointer in task specific structures.
On Linux, it wont' be easy to use task_struct->journal_info because Lustre code may call into other fs which has certain assumptions about journal_info. Currently following fields in task_struct are identified can be used for this purpose:
cl_env: for liblustre.
tux_info: ony on RedHat kernel.
...
Note:
As long as we use task_struct to store cl_env, we assume that once called into Lustre, we'll never call into the other part of the kernel which will use those fields in task_struct without explicitly exiting Lustre.
If there's no space in task_struct is available, hash will be used. bz20044, bz22683.
Definition at line 572 of file cl_object.c.
Referenced by cl_env_cache_purge(), cl_env_obtain(), cl_env_put(), and cl_global_init().
unsigned cl_envs_cached_max = 128 [static]
Definition at line 574 of file cl_object.c.
unsigned cl_envs_cached_nr = 0 [static]
Definition at line 573 of file cl_object.c.
static struct lu_context_key cl_key [static, read]
Initial value:
 {
        .lct_tags = LCT_CL_THREAD,
        .lct_init = cl_key_init,
        .lct_fini = cl_key_fini,
        .lct_exit = cl_key_exit
}
Definition at line 1288 of file cl_object.c.
Referenced by cl_env_info().
struct lu_kmem_descr cl_object_caches[] [static]
Initial value:
 {
        {
                .ckd_cache = &cl_env_kmem,
                .ckd_name  = "cl_env_kmem",
                .ckd_size  = sizeof (struct cl_env)
        },
        {
                .ckd_cache = NULL
        }
}
Definition at line 1348 of file cl_object.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.