Lustre: lustre/obdclass/cl_page.c File Reference
lustre/obdclass/cl_page.c File Reference
#include <libcfs/libcfs.h>
#include <obd_class.h>
#include <obd_support.h>
#include <libcfs/list.h>
#include <cl_object.h>
#include "cl_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_CLASS
#define PASSERT(env, page, exp) ((void)sizeof(env), (void)sizeof(page), (void)sizeof !!(exp))
#define PINVRNT(env, page, exp) ((void)sizeof(env), (void)sizeof(page), (void)sizeof !!(exp))
#define CS_PAGE_INC(o, item)
#define CS_PAGE_DEC(o, item)
#define CS_PAGESTATE_INC(o, state)
#define CS_PAGESTATE_DEC(o, state)
#define CL_PAGE_OP(opname) offsetof(struct cl_page_operations, opname)
#define CL_PAGE_INVOKE(_env, _page, _op, _proto,...)
#define CL_PAGE_INVOID(_env, _page, _op, _proto,...)
#define CL_PAGE_INVOID_REVERSE(_env, _page, _op, _proto,...)
Functions
static void cl_page_delete0 (const struct lu_env *env, struct cl_page *pg)
Version of cl_page_delete() that can be called for not fully constructed pages, e.g.
static void cl_page_get_trust (struct cl_page *page)
Internal version of cl_page_get().
static struct cl_page_slice * cl_page_at_trusted (const struct cl_page *page, const struct lu_device_type *dtype)
Returns a slice within a page, corresponding to the given layer in the device stack.
static void cl_page_free (const struct lu_env *env, struct cl_page *page)
static void cl_page_state_set_trust (struct cl_page *page, enum cl_page_state state)
Helper function updating page state.
struct cl_page * cl_page_alloc (const struct lu_env *env, struct cl_object *o, pgoff_t ind, struct page *vmpage, enum cl_page_type type)
struct cl_page * cl_page_find (const struct lu_env *env, struct cl_object *o, pgoff_t idx, struct page *vmpage, enum cl_page_type type)
Returns a cl_page with index idx at the object o, and associated with the VM page vmpage.
static int cl_page_invariant (const struct cl_page *pg)
static void cl_page_state_set0 (const struct lu_env *env, struct cl_page *page, enum cl_page_state state)
static void cl_page_state_set (const struct lu_env *env, struct cl_page *page, enum cl_page_state state)
void cl_page_get (struct cl_page *page)
Acquires an additional reference to a page.
void cl_page_put (const struct lu_env *env, struct cl_page *page)
Releases a reference to a page.
struct cl_page * cl_vmpage_page (struct page *vmpage, struct cl_object *obj)
Returns a cl_page associated with a VM page, and given cl_object.
struct cl_page_slice * cl_page_at (const struct cl_page *page, const struct lu_device_type *dtype)
static int cl_page_invoke (const struct lu_env *env, struct cl_io *io, struct cl_page *page, ptrdiff_t op)
static void cl_page_invoid (const struct lu_env *env, struct cl_io *io, struct cl_page *page, ptrdiff_t op)
static void cl_page_owner_clear (struct cl_page *page)
static void cl_page_owner_set (struct cl_page *page)
void cl_page_disown0 (const struct lu_env *env, struct cl_io *io, struct cl_page *pg)
int cl_page_is_owned (const struct cl_page *pg, const struct cl_io *io)
returns true, iff page is owned by the given io.
static int cl_page_own0 (const struct lu_env *env, struct cl_io *io, struct cl_page *pg, int nonblock)
Try to own a page by IO.
int cl_page_own (const struct lu_env *env, struct cl_io *io, struct cl_page *pg)
Own a page, might be blocked.
int cl_page_own_try (const struct lu_env *env, struct cl_io *io, struct cl_page *pg)
Nonblock version of cl_page_own().
void cl_page_assume (const struct lu_env *env, struct cl_io *io, struct cl_page *pg)
Assume page ownership.
void cl_page_unassume (const struct lu_env *env, struct cl_io *io, struct cl_page *pg)
Releases page ownership without unlocking the page.
void cl_page_disown (const struct lu_env *env, struct cl_io *io, struct cl_page *pg)
Releases page ownership.
void cl_page_discard (const struct lu_env *env, struct cl_io *io, struct cl_page *pg)
Called when page is to be removed from the object, e.g., as a result of truncate.
void cl_page_delete (const struct lu_env *env, struct cl_page *pg)
Called when a decision is made to throw page out of memory.
void cl_page_export (const struct lu_env *env, struct cl_page *pg, int uptodate)
Marks page up-to-date.
int cl_page_is_vmlocked (const struct lu_env *env, const struct cl_page *pg)
Returns true, iff pg is VM locked in a suitable sense by the calling thread.
static enum cl_page_state cl_req_type_state (enum cl_req_type crt)
static void cl_page_io_start (const struct lu_env *env, struct cl_page *pg, enum cl_req_type crt)
int cl_page_prep (const struct lu_env *env, struct cl_io *io, struct cl_page *pg, enum cl_req_type crt)
Prepares page for immediate transfer.
void cl_page_completion (const struct lu_env *env, struct cl_page *pg, enum cl_req_type crt, int ioret)
Notify layers about transfer completion.
int cl_page_make_ready (const struct lu_env *env, struct cl_page *pg, enum cl_req_type crt)
Notify layers that transfer formation engine decided to yank this page from the cache and to make it a part of a transfer.
int cl_page_flush (const struct lu_env *env, struct cl_io *io, struct cl_page *pg)
Called if a pge is being written back by kernel's intention.
void cl_page_clip (const struct lu_env *env, struct cl_page *pg, int from, int to)
Tells transfer engine that only part of a page is to be transmitted.
void cl_page_header_print (const struct lu_env *env, void *cookie, lu_printer_t printer, const struct cl_page *pg)
Prints human readable representation of pg to the f.
void cl_page_print (const struct lu_env *env, void *cookie, lu_printer_t printer, const struct cl_page *pg)
Prints human readable representation of pg to the f.
int cl_page_cancel (const struct lu_env *env, struct cl_page *page)
Cancel a page which is still in a transfer.
loff_t cl_offset (const struct cl_object *obj, pgoff_t idx)
Converts a byte offset within object obj into a page index.
pgoff_t cl_index (const struct cl_object *obj, loff_t offset)
Converts a page index into a byte offset within object obj.
size_t cl_page_size (const struct cl_object *obj)
void cl_page_slice_add (struct cl_page *page, struct cl_page_slice *slice, struct cl_object *obj, pgoff_t index, const struct cl_page_operations *ops)
Adds page slice to the compound page.
struct cl_client_cache * cl_cache_init (unsigned long lru_page_max)
Allocate and initialize cl_cache, called by ll_init_sbi().
void cl_cache_incref (struct cl_client_cache *cache)
Increase cl_cache refcount.
void cl_cache_decref (struct cl_client_cache *cache)
Decrease cl_cache refcount and free the cache if refcount=0.
Define Documentation
#define CL_PAGE_INVOID (_env, _page, _op, _proto, ...)
Value:
do {                                                                    \
        const struct lu_env        *__env  = (_env);                    \
        struct cl_page             *__page = (_page);                   \
        const struct cl_page_slice *__scan;                             \
        ptrdiff_t                   __op   = (_op);                     \
        void                      (*__method)_proto;                    \
                                                                        \
        list_for_each_entry(__scan, &__page->cp_layers, cpl_linkage) {  \
                __method = *(void **)((char *)__scan->cpl_ops +  __op); \
                if (__method != NULL)                                   \
                        (*__method)(__env, __scan, ## __VA_ARGS__);     \
        }                                                               \
} while (0)
Definition at line 452 of file cl_page.c.
Referenced by cl_page_clip(), cl_page_export(), and cl_page_invoid().
#define CL_PAGE_INVOID_REVERSE (_env, _page, _op, _proto, ...)
Value:
do {                                                                    \
        const struct lu_env        *__env  = (_env);                    \
        struct cl_page             *__page = (_page);                   \
        const struct cl_page_slice *__scan;                             \
        ptrdiff_t                   __op   = (_op);                     \
        void                      (*__method)_proto;                    \
                                                                        \
        /* get to the bottom page. */                                   \
        list_for_each_entry_reverse(__scan, &__page->cp_layers,         \
                                    cpl_linkage) {                      \
                __method = *(void **)((char *)__scan->cpl_ops + __op);  \
                if (__method != NULL)                                   \
                        (*__method)(__env, __scan, ## __VA_ARGS__);     \
        }                                                               \
} while (0)
Definition at line 467 of file cl_page.c.
Referenced by cl_page_completion(), cl_page_delete0(), cl_page_disown0(), and cl_page_unassume().
#define CL_PAGE_INVOKE (_env, _page, _op, _proto, ...)
Value:
({                                                                      \
        const struct lu_env        *__env  = (_env);                    \
        struct cl_page             *__page = (_page);                   \
        const struct cl_page_slice *__scan;                             \
        int                         __result;                           \
        ptrdiff_t                   __op   = (_op);                     \
        int                        (*__method)_proto;                   \
                                                                        \
        __result = 0;                                                   \
        list_for_each_entry(__scan, &__page->cp_layers, cpl_linkage) {  \
                __method = *(void **)((char *)__scan->cpl_ops +  __op); \
                if (__method != NULL) {                                 \
                        __result = (*__method)(__env, __scan, ## __VA_ARGS__); \
                        if (__result != 0)                              \
                                break;                                  \
                }                                                       \
        }                                                               \
        if (__result > 0)                                               \
                __result = 0;                                           \
        __result;                                                       \
})
Definition at line 429 of file cl_page.c.
Referenced by cl_page_cancel(), cl_page_invoke(), cl_page_make_ready(), cl_page_own0(), and cl_page_print().
#define CL_PAGE_OP (opname) offsetof(struct cl_page_operations, opname)
Definition at line 427 of file cl_page.c.
Referenced by cl_page_assume(), cl_page_cancel(), cl_page_clip(), cl_page_completion(), cl_page_delete0(), cl_page_discard(), cl_page_disown0(), cl_page_export(), cl_page_flush(), cl_page_make_ready(), cl_page_own0(), cl_page_prep(), cl_page_print(), and cl_page_unassume().
#define CS_PAGE_DEC (o, item)
Definition at line 92 of file cl_page.c.
Referenced by cl_page_free().
#define CS_PAGE_INC (o, item)
Definition at line 91 of file cl_page.c.
Referenced by cl_page_alloc(), and cl_page_find().
#define CS_PAGESTATE_DEC (o, state)
Definition at line 94 of file cl_page.c.
Referenced by cl_page_alloc(), cl_page_free(), and cl_page_state_set0().
#define CS_PAGESTATE_INC (o, state)
Definition at line 93 of file cl_page.c.
Referenced by cl_page_state_set0().
#define DEBUG_SUBSYSTEM S_CLASS
Definition at line 42 of file cl_page.c.
#define PASSERT (env, page, exp) ((void)sizeof(env), (void)sizeof(page), (void)sizeof !!(exp))
Definition at line 63 of file cl_page.c.
Referenced by cl_page_assume(), cl_page_completion(), cl_page_delete0(), cl_page_free(), cl_page_is_vmlocked(), cl_page_make_ready(), cl_page_own0(), cl_page_put(), and cl_page_state_set0().
#define PINVRNT (env, page, exp) ((void)sizeof(env), (void)sizeof(page), (void)sizeof !!(exp))
Definition at line 76 of file cl_page.c.
Referenced by cl_page_assume(), cl_page_clip(), cl_page_delete(), cl_page_discard(), cl_page_disown(), cl_page_disown0(), cl_page_export(), cl_page_flush(), cl_page_invoid(), cl_page_invoke(), cl_page_make_ready(), cl_page_own0(), cl_page_prep(), and cl_page_unassume().
Function Documentation
static struct cl_page_slice* cl_page_at_trusted (const struct cl_page * page, const struct lu_device_type * dtype) [static, read]
Returns a slice within a page, corresponding to the given layer in the device stack.
See also:
cl_lock_at()
Definition at line 120 of file cl_page.c.
References cl_object::co_lu, cl_page::cp_layers, cl_page_slice::cpl_linkage, cl_page_slice::cpl_obj, ENTRY, lu_device::ld_type, list_for_each_entry, lu_object::lo_dev, and RETURN.
Referenced by cl_page_at().
static void cl_page_delete0 (const struct lu_env * env, struct cl_page * pg) [static]
Version of cl_page_delete() that can be called for not fully constructed pages, e.g.
in an error handling cl_page_find()->cl_page_delete0() path. Doesn't check page invariant.
Definition at line 747 of file cl_page.c.
References CL_PAGE_INVOID_REVERSE, CL_PAGE_OP, cl_page_owner_clear(), cl_page_state_set0(), cl_page::cp_state, CPS_FREEING, ENTRY, EXIT, and PASSERT.
Referenced by cl_page_alloc(), and cl_page_delete().
void cl_page_disown0 (const struct lu_env * env, struct cl_io * io, struct cl_page * pg)
Definition at line 527 of file cl_page.c.
References cl_page_invariant(), CL_PAGE_INVOID_REVERSE, CL_PAGE_OP, cl_page_owner_clear(), cl_page_state_set(), cl_page::cp_state, CPS_CACHED, CPS_FREEING, CPS_OWNED, ENTRY, EXIT, PINVRNT, and state.
Referenced by cl_page_disown(), cl_page_list_disown(), and cl_page_own0().
static void cl_page_free (const struct lu_env * env, struct cl_page * page) [static]
Definition at line 133 of file cl_page.c.
References cl_object_header(), cl_object_put(), cl_object::co_lu, cl_object_header::coh_page_bufsize, cl_page::cp_batch, cl_page::cp_layers, cl_page::cp_obj, cl_page::cp_obj_ref, cl_page::cp_owner, cl_page::cp_reference, cl_page::cp_state, cl_page_slice::cpl_linkage, cl_page_slice::cpl_ops, cl_page_operations::cpo_fini, CPS_FREEING, CS_PAGE_DEC, CS_PAGESTATE_DEC, ENTRY, EXIT, list_del_init(), list_empty(), list_entry, lu_object_ref_del_at(), lu_ref_fini(), list_head::next, OBD_FREE, PASSERT, and unlikely.
Referenced by cl_page_alloc(), and cl_page_put().
static void cl_page_get_trust (struct cl_page * page) [static]
Internal version of cl_page_get().
This function can be used to obtain initial reference to previously unreferenced cached object. It can be called only if concurrent page reclamation is somehow prevented, e.g., by keeping a lock on a VM page, associated with page.
Use with care! Not exported.
Definition at line 107 of file cl_page.c.
References cl_page::cp_ref, and LASSERT.
Referenced by cl_page_get(), and cl_vmpage_page().
static int cl_page_invariant (const struct cl_page * pg) [inline, static]
Definition at line 276 of file cl_page.c.
References cl_page_in_use_noref.
Referenced by cl_page_clip(), cl_page_delete(), cl_page_discard(), cl_page_disown0(), cl_page_export(), cl_page_flush(), cl_page_own0(), cl_page_prep(), and cl_page_unassume().
static void cl_page_invoid (const struct lu_env * env, struct cl_io * io, struct cl_page * page, ptrdiff_t op) [static]
Definition at line 496 of file cl_page.c.
References cl_io::ci_obj, cl_object_same(), CL_PAGE_INVOID, cl_page::cp_obj, ENTRY, EXIT, and PINVRNT.
Referenced by cl_page_assume(), and cl_page_discard().
static int cl_page_invoke (const struct lu_env * env, struct cl_io * io, struct cl_page * page, ptrdiff_t op) [static]
Definition at line 484 of file cl_page.c.
References cl_io::ci_obj, cl_object_same(), CL_PAGE_INVOKE, cl_page::cp_obj, ENTRY, PINVRNT, and RETURN.
Referenced by cl_page_flush(), and cl_page_prep().
static void cl_page_io_start (const struct lu_env * env, struct cl_page * pg, enum cl_req_type crt) [static]
Definition at line 847 of file cl_page.c.
References cl_page_owner_clear(), cl_page_state_set(), cl_req_type_state(), ENTRY, and EXIT.
Referenced by cl_page_make_ready(), and cl_page_prep().
static int cl_page_own0 (const struct lu_env * env, struct cl_io * io, struct cl_page * pg, int nonblock) [static]
Try to own a page by IO.
Waits until page is in cl_page_state::CPS_CACHED state, and then switch it into cl_page_state::CPS_OWNED state.
Precondition:
!cl_page_is_owned(pg, io)
Postcondition:
result == 0 iff cl_page_is_owned(pg, io)
Return values:
0 success
-ve failure, e.g., page was destroyed (and landed in cl_page_state::CPS_FREEING instead of cl_page_state::CPS_CACHED). or, page was owned by another thread, or in IO.
See also:
cl_page_disown()
cl_page_operations::cpo_own()
cl_page_own_try()
cl_page_own
Definition at line 584 of file cl_page.c.
References cl_io_top(), cl_page_disown0(), cl_page_invariant(), CL_PAGE_INVOKE, cl_page_is_owned(), CL_PAGE_OP, cl_page_owner_set(), cl_page_state_set(), cl_page::cp_owner, cl_page::cp_state, CPS_FREEING, CPS_OWNED, ENTRY, ergo, PASSERT, PINVRNT, and RETURN.
Referenced by cl_page_own(), and cl_page_own_try().
static void cl_page_owner_clear (struct cl_page * page) [static]
Definition at line 508 of file cl_page.c.
References cl_io::ci_owned_nr, cl_page::cp_owner, ENTRY, EXIT, and LASSERT.
Referenced by cl_page_delete0(), cl_page_disown0(), cl_page_io_start(), and cl_page_unassume().
static void cl_page_owner_set (struct cl_page * page) [static]
Definition at line 519 of file cl_page.c.
References cl_io::ci_owned_nr, cl_page::cp_owner, ENTRY, EXIT, and LASSERT.
Referenced by cl_page_assume(), and cl_page_own0().
static void cl_page_state_set (const struct lu_env * env, struct cl_page * page, enum cl_page_state state) [static]
Definition at line 341 of file cl_page.c.
References cl_page_state_set0().
Referenced by cl_page_assume(), cl_page_completion(), cl_page_disown0(), cl_page_io_start(), cl_page_own0(), and cl_page_unassume().
static void cl_page_state_set0 (const struct lu_env * env, struct cl_page * page, enum cl_page_state state) [static]
Definition at line 281 of file cl_page.c.
References CL_PAGE_HEADER, cl_page_state_set_trust(), cl_page::cp_obj, cl_page::cp_owner, cl_page::cp_state, CPS_CACHED, CPS_FREEING, CPS_NR, CPS_OWNED, CPS_PAGEIN, CPS_PAGEOUT, CS_PAGESTATE_DEC, CS_PAGESTATE_INC, D_TRACE, ENTRY, equi, EXIT, and PASSERT.
Referenced by cl_page_delete0(), and cl_page_state_set().
static void cl_page_state_set_trust (struct cl_page * page, enum cl_page_state state) [inline, static]
Helper function updating page state.
This is the only place in the code where cl_page::cp_state field is mutated.
Definition at line 165 of file cl_page.c.
References cl_page::cp_state.
Referenced by cl_page_alloc(), and cl_page_state_set0().
static enum cl_page_state cl_req_type_state (enum cl_req_type crt) [static]
Definition at line 841 of file cl_page.c.
References CPS_PAGEIN, CPS_PAGEOUT, CRT_WRITE, ENTRY, and RETURN.
Referenced by cl_page_completion(), and cl_page_io_start().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.