Lustre: lustre/include/cl_object.h File Reference
lustre/include/cl_object.h File Reference
#include <libcfs/libcfs.h>
#include <lu_object.h>
#include <linux/atomic.h>
#include <linux/mutex.h>
#include <linux/radix-tree.h>
#include <linux/spinlock.h>
#include <linux/wait.h>
#include <lustre_dlm.h>
Data Structures
struct cl_device
Device in the client stack.
struct cl_attr
"Data attributes" of cl_object.
struct cl_object
Sub-class of lu_object with methods common for objects on the client stacks.
struct cl_object_conf
Description of the client object configuration.
struct cl_layout
struct cl_object_operations
Operations implemented for each cl object layer.
struct cl_object_header
Extended header for client object.
struct cl_page
Fields are protected by the lock on struct page, except for atomics and immutables.
struct cl_page_slice
Per-layer part of cl_page.
struct cl_page_operations
Per-layer page operations.
struct cl_lock_descr
Lock description.
struct cl_lock
Layered client lock.
struct cl_lock_slice
Per-layer part of cl_lock.
struct cl_lock_operations
struct cl_page_list
struct cl_2queue
A 2-queue of pages.
struct cl_io_slice
IO state private for a layer.
struct cl_read_ahead
struct cl_io_operations
Per-layer io operations.
struct cl_io_lock_link
Link between lock and io.
struct cl_lockset
Lock-set represents a collection of locks, that io needs at a time.
struct cl_io_rw_common
struct cl_io
State for io.
struct cl_req_attr
Per-transfer attributes.
struct cache_stats
Stats for a generic cache (similar to inode, lu_object, etc.
struct cl_site
Client-side site.
struct cl_client_cache
Data structure managing a client's cached pages.
struct cl_sync_io
Anchor for synchronous transfer.
struct cl_env_nest
Defines
#define cl_object_for_each(slice, obj)
Helper macro: iterate over all layers of the object obj, assigning every layer top-to-bottom to slice.
#define cl_object_for_each_reverse(slice, obj)
Helper macro: iterate over all layers of the object obj, assigning every layer bottom-to-top to slice.
#define CL_PAGE_EOF ((pgoff_t)~0ull)
#define CL_PAGE_DEBUG(mask, env, page, format,...)
Helper macro, dumping detailed information about page into a log.
#define CL_PAGE_HEADER(mask, env, page, format,...)
Helper macro, dumping shorter information about page into a log.
#define cl_page_in_use(pg) __page_in_use(pg, 1)
Caller itself holds a refcount of cl_page.
#define cl_page_in_use_noref(pg) __page_in_use(pg, 0)
Caller doesn't hold a refcount.
#define DDESCR "%s(%d):[%lu, %lu]:%x"
#define PDESCR(descr)
#define CL_LOCK_DEBUG(mask, env, lock, format,...)
#define CL_LOCK_ASSERT(expr, env, lock)
#define cill_descr cill_lock.cll_descr
#define CS_NAMES { "lookup", "hit", "total", "busy", "create" }
#define CL_IO_SLICE_CLEAN(foo_io, base)
#define cl_page_list_for_each(page, list) list_for_each_entry((page), &(list)->pl_pages, cp_batch)
Iterate over pages in a page list.
#define cl_page_list_for_each_safe(page, temp, list) list_for_each_entry_safe((page), (temp), &(list)->pl_pages, cp_batch)
Iterate over pages in a page list, taking possible removals into account.
Typedefs
typedef void(* cl_commit_cbt)(const struct lu_env *, struct cl_io *, struct cl_page *)
Enumerations
enum cl_attr_valid {
CAT_SIZE = 1 << 0, CAT_KMS = 1 << 1, CAT_MTIME = 1 << 3, CAT_ATIME = 1 << 4,
CAT_CTIME = 1 << 5, CAT_BLOCKS = 1 << 6, CAT_UID = 1 << 7, CAT_GID = 1 << 8
}
Fields in cl_attr that are being set.
enum { OBJECT_CONF_SET = 0, OBJECT_CONF_INVALIDATE = 1, OBJECT_CONF_WAIT = 2 }
enum { CL_LAYOUT_GEN_NONE = (u32)-2, CL_LAYOUT_GEN_EMPTY = (u32)-1 }
enum cl_page_state {
CPS_CACHED, CPS_OWNED, CPS_PAGEOUT, CPS_PAGEIN,
CPS_FREEING, CPS_NR
}
States of cl_page.
enum cl_page_type { CPT_CACHEABLE = 1, CPT_TRANSIENT }
enum cl_lock_mode { CLM_READ, CLM_WRITE, CLM_GROUP, CLM_MAX }
Lock mode.
enum cl_req_type { CRT_READ, CRT_WRITE, CRT_NR }
Requested transfer type.
enum cl_io_type {
CIT_READ, CIT_WRITE, CIT_SETATTR, CIT_DATA_VERSION,
CIT_FAULT, CIT_FSYNC, CIT_MISC, CIT_LADVISE,
CIT_OP_NR
}
IO types.
enum cl_io_state {
CIS_ZERO, CIS_INIT, CIS_IT_STARTED, CIS_LOCKED,
CIS_IO_GOING, CIS_IO_FINISHED, CIS_UNLOCKED, CIS_IT_ENDED,
CIS_FINI
}
States of cl_io state machine.
enum cl_enq_flags {
CEF_NONBLOCK = 0x00000001, CEF_ASYNC = 0x00000002, CEF_DISCARD_DATA = 0x00000004, CEF_MUST = 0x00000008,
CEF_NEVER = 0x00000010, CEF_AGL = 0x00000020, CEF_PEEK = 0x00000040, CEF_LOCK_MATCH = 0x00000080,
CEF_MASK = 0x000000ff
}
Flags to lock enqueue procedure.
enum cl_io_lock_dmd { CILR_MANDATORY = 0, CILR_MAYBE, CILR_NEVER }
Lock requirements(demand) for IO.
enum cl_fsync_mode { CL_FSYNC_NONE = 0, CL_FSYNC_LOCAL = 1, CL_FSYNC_DISCARD = 2, CL_FSYNC_ALL = 3 }
enum cache_stats_item {
CS_lookup = 0, CS_hit, CS_total, CS_busy,
CS_create, CS_NR
}
enum { CLP_GANG_OKAY = 0, CLP_GANG_RESCHED, CLP_GANG_AGAIN, CLP_GANG_ABORT }
Functions
static struct page * cl_page_vmpage (const struct cl_page *page)
static bool __page_in_use (const struct cl_page *page, int refc)
Check if a cl_page is in use.
const char * cl_lock_mode_name (const enum cl_lock_mode mode)
static void cl_read_ahead_release (const struct lu_env *env, struct cl_read_ahead *ra)
void cache_stats_init (struct cache_stats *cs, const char *name)
These are not exported so far.
int cl_site_init (struct cl_site *s, struct cl_device *top)
Initialize client site.
void cl_site_fini (struct cl_site *s)
Finalize client site.
void cl_stack_fini (const struct lu_env *env, struct cl_device *cl)
Finalize device stack by calling lu_stack_fini().
int cl_site_stats_print (const struct cl_site *site, struct seq_file *m)
Output client site statistical counters into a buffer.
struct cl_object * cl_object_top (struct cl_object *o)
Returns the top-object for a given o.
struct cl_object * cl_object_find (const struct lu_env *env, struct cl_device *cd, const struct lu_fid *fid, const struct cl_object_conf *c)
Returns a cl_object with a given fid.
int cl_object_header_init (struct cl_object_header *h)
Initialize cl_object_header.
void cl_object_header_fini (struct cl_object_header *h)
Finalize cl_object_header.
void cl_object_put (const struct lu_env *env, struct cl_object *o)
Releases a reference on o.
void cl_object_get (struct cl_object *o)
Acquire an additional reference to the object o.
void cl_object_attr_lock (struct cl_object *o)
Locks data-attributes.
void cl_object_attr_unlock (struct cl_object *o)
Releases data-attributes lock, acquired by cl_object_attr_lock().
int cl_object_attr_get (const struct lu_env *env, struct cl_object *obj, struct cl_attr *attr)
Returns data-attributes of an object obj.
int cl_object_attr_update (const struct lu_env *env, struct cl_object *obj, const struct cl_attr *attr, unsigned valid)
Updates data-attributes of an object obj.
int cl_object_glimpse (const struct lu_env *env, struct cl_object *obj, struct ost_lvb *lvb)
Notifies layers (bottom-to-top) that glimpse AST was received.
int cl_conf_set (const struct lu_env *env, struct cl_object *obj, const struct cl_object_conf *conf)
Updates a configuration of an object obj.
int cl_object_prune (const struct lu_env *env, struct cl_object *obj)
Prunes caches of pages and locks for this object.
void cl_object_kill (const struct lu_env *env, struct cl_object *obj)
Helper function removing all object locks, and marking object for deletion.
int cl_object_getstripe (const struct lu_env *env, struct cl_object *obj, struct lov_user_md __user *lum)
Get stripe information of this object.
int cl_object_fiemap (const struct lu_env *env, struct cl_object *obj, struct ll_fiemap_info_key *fmkey, struct fiemap *fiemap, size_t *buflen)
Get fiemap extents from file object.
int cl_object_layout_get (const struct lu_env *env, struct cl_object *obj, struct cl_layout *cl)
loff_t cl_object_maxbytes (struct cl_object *obj)
static int cl_object_same (struct cl_object *o0, struct cl_object *o1)
Returns true, iff o0 and o1 are slices of the same object.
static void cl_object_page_init (struct cl_object *clob, int size)
static void * cl_object_page_slice (struct cl_object *clob, struct cl_page *page)
static int cl_object_refc (struct cl_object *clob)
Return refcount of cl_object.
struct cl_page * cl_page_find (const struct lu_env *env, struct cl_object *obj, pgoff_t idx, struct page *vmpage, enum cl_page_type type)
Returns a cl_page with index idx at the object o, and associated with the VM page vmpage.
struct cl_page * cl_page_alloc (const struct lu_env *env, struct cl_object *o, pgoff_t ind, struct page *vmpage, enum cl_page_type type)
void cl_page_get (struct cl_page *page)
Acquires an additional reference to a page.
void cl_page_put (const struct lu_env *env, struct cl_page *page)
Releases a reference to a page.
void cl_page_print (const struct lu_env *env, void *cookie, lu_printer_t printer, const struct cl_page *pg)
Prints human readable representation of pg to the f.
void cl_page_header_print (const struct lu_env *env, void *cookie, lu_printer_t printer, const struct cl_page *pg)
Prints human readable representation of pg to the f.
struct cl_page * cl_vmpage_page (struct page *vmpage, struct cl_object *obj)
Returns a cl_page associated with a VM page, and given cl_object.
struct cl_page * cl_page_top (struct cl_page *page)
struct cl_page_slice * cl_page_at (const struct cl_page *page, const struct lu_device_type *dtype)
struct cl_client_cache * cl_cache_init (unsigned long lru_page_max)
cl_cache functions
void cl_cache_incref (struct cl_client_cache *cache)
Increase cl_cache refcount.
void cl_cache_decref (struct cl_client_cache *cache)
Decrease cl_cache refcount and free the cache if refcount=0.
int cl_lock_request (const struct lu_env *env, struct cl_io *io, struct cl_lock *lock)
Main high-level entry point of cl_lock interface that finds existing or enqueues new lock matching given description.
int cl_lock_init (const struct lu_env *env, struct cl_lock *lock, const struct cl_io *io)
void cl_lock_fini (const struct lu_env *env, struct cl_lock *lock)
struct cl_lock_slice * cl_lock_at (const struct cl_lock *lock, const struct lu_device_type *dtype)
Returns a slice with a lock, corresponding to the given layer in the device stack.
void cl_lock_release (const struct lu_env *env, struct cl_lock *lock)
Releases a hold and a reference on a lock, obtained by cl_lock_hold().
int cl_lock_enqueue (const struct lu_env *env, struct cl_io *io, struct cl_lock *lock, struct cl_sync_io *anchor)
Enqueue a lock.
void cl_lock_cancel (const struct lu_env *env, struct cl_lock *lock)
int cl_io_init (const struct lu_env *env, struct cl_io *io, enum cl_io_type iot, struct cl_object *obj)
Initialize io, by calling cl_io_operations::cio_init() top-to-bottom.
int cl_io_sub_init (const struct lu_env *env, struct cl_io *io, enum cl_io_type iot, struct cl_object *obj)
Initialize sub-io, by calling cl_io_operations::cio_init() top-to-bottom.
int cl_io_rw_init (const struct lu_env *env, struct cl_io *io, enum cl_io_type iot, loff_t pos, size_t count)
Initialize read or write io.
int cl_io_loop (const struct lu_env *env, struct cl_io *io)
Main io loop.
void cl_io_fini (const struct lu_env *env, struct cl_io *io)
Finalize io, by calling cl_io_operations::cio_fini() bottom-to-top.
int cl_io_iter_init (const struct lu_env *env, struct cl_io *io)
Prepares next iteration of io.
void cl_io_iter_fini (const struct lu_env *env, struct cl_io *io)
Finalizes io iteration.
int cl_io_lock (const struct lu_env *env, struct cl_io *io)
Takes locks necessary for the current iteration of io.
void cl_io_unlock (const struct lu_env *env, struct cl_io *io)
Release locks takes by io.
int cl_io_start (const struct lu_env *env, struct cl_io *io)
Starts io by calling cl_io_operations::cio_start() top-to-bottom.
void cl_io_end (const struct lu_env *env, struct cl_io *io)
Wait until current io iteration is finished by calling cl_io_operations::cio_end() bottom-to-top.
int cl_io_lock_add (const struct lu_env *env, struct cl_io *io, struct cl_io_lock_link *link)
Adds a lock to a lockset.
int cl_io_lock_alloc_add (const struct lu_env *env, struct cl_io *io, struct cl_lock_descr *descr)
Allocates new lock link, and uses it to add a lock to a lockset.
int cl_io_submit_rw (const struct lu_env *env, struct cl_io *io, enum cl_req_type iot, struct cl_2queue *queue)
Submits a list of pages for immediate io.
int cl_io_submit_sync (const struct lu_env *env, struct cl_io *io, enum cl_req_type iot, struct cl_2queue *queue, long timeout)
Submit a sync_io and wait for the IO to be finished, or error happens.
int cl_io_commit_async (const struct lu_env *env, struct cl_io *io, struct cl_page_list *queue, int from, int to, cl_commit_cbt cb)
Commit a list of contiguous pages into writeback cache.
int cl_io_read_ahead (const struct lu_env *env, struct cl_io *io, pgoff_t start, struct cl_read_ahead *ra)
Called by read io, to decide the readahead extent.
void cl_io_rw_advance (const struct lu_env *env, struct cl_io *io, size_t nob)
Records that read or write io progressed nob bytes forward.
int cl_io_cancel (const struct lu_env *env, struct cl_io *io, struct cl_page_list *queue)
Cancel an IO which has been submitted by cl_io_submit_rw.
int cl_io_is_going (const struct lu_env *env)
Returns true iff there is an IO ongoing in the given environment.
static int cl_io_is_append (const struct cl_io *io)
True, iff io is an O_APPEND write(2).
static int cl_io_is_sync_write (const struct cl_io *io)
static int cl_io_is_mkwrite (const struct cl_io *io)
static int cl_io_is_trunc (const struct cl_io *io)
True, iff io is a truncate(2).
struct cl_io * cl_io_top (struct cl_io *io)
Returns top-level io.
void cl_io_print (const struct lu_env *env, void *cookie, lu_printer_t printer, const struct cl_io *io)
Prints human readable representation of io to the f.
static struct cl_page * cl_page_list_last (struct cl_page_list *plist)
Last page in the page list.
static struct cl_page * cl_page_list_first (struct cl_page_list *plist)
void cl_page_list_init (struct cl_page_list *plist)
Initializes page list.
void cl_page_list_add (struct cl_page_list *plist, struct cl_page *page)
Adds a page to a page list.
void cl_page_list_move (struct cl_page_list *dst, struct cl_page_list *src, struct cl_page *page)
Moves a page from one page list to another.
void cl_page_list_move_head (struct cl_page_list *dst, struct cl_page_list *src, struct cl_page *page)
Moves a page from one page list to the head of another list.
void cl_page_list_splice (struct cl_page_list *list, struct cl_page_list *head)
splice the cl_page_list, just as list head does
void cl_page_list_del (const struct lu_env *env, struct cl_page_list *plist, struct cl_page *page)
Removes a page from a page list.
void cl_page_list_disown (const struct lu_env *env, struct cl_io *io, struct cl_page_list *plist)
Disowns pages in a queue.
int cl_page_list_own (const struct lu_env *env, struct cl_io *io, struct cl_page_list *plist)
Owns all pages in a queue.
void cl_page_list_assume (const struct lu_env *env, struct cl_io *io, struct cl_page_list *plist)
Assumes all pages in a queue.
void cl_page_list_discard (const struct lu_env *env, struct cl_io *io, struct cl_page_list *plist)
Discards all pages in a queue.
void cl_page_list_fini (const struct lu_env *env, struct cl_page_list *plist)
Releases pages from queue.
void cl_2queue_init (struct cl_2queue *queue)
Initialize dual page queue.
void cl_2queue_add (struct cl_2queue *queue, struct cl_page *page)
Add a page to the incoming page list of 2-queue.
void cl_2queue_disown (const struct lu_env *env, struct cl_io *io, struct cl_2queue *queue)
Disown pages in both lists of a 2-queue.
void cl_2queue_assume (const struct lu_env *env, struct cl_io *io, struct cl_2queue *queue)
Assume to own the pages in cl_2queue.
void cl_2queue_discard (const struct lu_env *env, struct cl_io *io, struct cl_2queue *queue)
Discard (truncate) pages in both lists of a 2-queue.
void cl_2queue_fini (const struct lu_env *env, struct cl_2queue *queue)
Finalize both page lists of a 2-queue.
void cl_2queue_init_page (struct cl_2queue *queue, struct cl_page *page)
Initialize a 2-queue to contain page in its incoming page list.
void cl_req_attr_set (const struct lu_env *env, struct cl_object *obj, struct cl_req_attr *attr)
Fills in attributes that are passed to server together with transfer.
void cl_sync_io_init (struct cl_sync_io *anchor, int nr, void(*end)(const struct lu_env *, struct cl_sync_io *))
Initialize synchronous io wait anchor.
int cl_sync_io_wait (const struct lu_env *env, struct cl_sync_io *anchor, long timeout)
Wait until all IO completes.
void cl_sync_io_note (const struct lu_env *env, struct cl_sync_io *anchor, int ioret)
Indicate that transfer of a single page completed.
void cl_sync_io_end (const struct lu_env *env, struct cl_sync_io *anchor)
struct lu_env * cl_env_peek (__u16 *refcheck)
struct lu_env * cl_env_get (__u16 *refcheck)
Returns lu_env: if there already is an environment associated with the current thread, it is returned, otherwise, new environment is allocated.
struct lu_env * cl_env_alloc (__u16 *refcheck, __u32 tags)
Forces an allocation of a fresh environment with given tags.
struct lu_env * cl_env_nested_get (struct cl_env_nest *nest)
void cl_env_put (struct lu_env *env, __u16 *refcheck)
Release an environment.
void cl_env_nested_put (struct cl_env_nest *nest, struct lu_env *env)
void * cl_env_reenter (void)
Declares a point of re-entrancy.
void cl_env_reexit (void *cookie)
Exits re-entrancy.
void cl_env_implant (struct lu_env *env, __u16 *refcheck)
Setup user-supplied env as a current environment.
void cl_env_unplant (struct lu_env *env, __u16 *refcheck)
Detach environment installed earlier by cl_env_implant().
unsigned cl_env_cache_purge (unsigned nr)
Finalizes and frees a given number of cached environments.
struct lu_env * cl_env_percpu_get (void)
void cl_env_percpu_put (struct lu_env *env)
void cl_attr2lvb (struct ost_lvb *lvb, const struct cl_attr *attr)
Converts struct cl_attr to struct ost_lvb.
void cl_lvb2attr (struct cl_attr *attr, const struct ost_lvb *lvb)
Converts struct ost_lvb to struct cl_attr.
struct cl_device * cl_type_setup (const struct lu_env *env, struct lu_site *site, struct lu_device_type *ldt, struct lu_device *next)
int cl_global_init (void)
Global initialization of cl-data.
void cl_global_fini (void)
Finalization of global cl-data.
helpers
Type conversion and accessory functions.
static struct cl_site * lu2cl_site (const struct lu_site *site)
static struct cl_device * lu2cl_dev (const struct lu_device *d)
static struct lu_device * cl2lu_dev (struct cl_device *d)
static struct cl_object * lu2cl (const struct lu_object *o)
static struct cl_object_conf * lu2cl_conf (const struct lu_object_conf *conf)
static struct cl_object * cl_object_next (const struct cl_object *obj)
static struct cl_object_header * luh2coh (const struct lu_object_header *h)
static struct cl_site * cl_object_site (const struct cl_object *obj)
static struct cl_object_header * cl_object_header (const struct cl_object *obj)
static int cl_device_init (struct cl_device *d, struct lu_device_type *t)
static void cl_device_fini (struct cl_device *d)
void cl_page_slice_add (struct cl_page *page, struct cl_page_slice *slice, struct cl_object *obj, pgoff_t index, const struct cl_page_operations *ops)
Adds page slice to the compound page.
void cl_lock_slice_add (struct cl_lock *lock, struct cl_lock_slice *slice, struct cl_object *obj, const struct cl_lock_operations *ops)
Adds lock slice to the compound lock.
void cl_io_slice_add (struct cl_io *io, struct cl_io_slice *slice, struct cl_object *obj, const struct cl_io_operations *ops)
Adds io slice to the cl_io.
ownership
Functions dealing with the ownership of page by io.
int cl_page_own (const struct lu_env *env, struct cl_io *io, struct cl_page *page)
Own a page, might be blocked.
int cl_page_own_try (const struct lu_env *env, struct cl_io *io, struct cl_page *page)
Nonblock version of cl_page_own().
void cl_page_assume (const struct lu_env *env, struct cl_io *io, struct cl_page *page)
Assume page ownership.
void cl_page_unassume (const struct lu_env *env, struct cl_io *io, struct cl_page *pg)
Releases page ownership without unlocking the page.
void cl_page_disown (const struct lu_env *env, struct cl_io *io, struct cl_page *page)
Releases page ownership.
int cl_page_is_owned (const struct cl_page *pg, const struct cl_io *io)
returns true, iff page is owned by the given io.
transfer
Functions dealing with the preparation of a page for a transfer, and tracking transfer state.
int cl_page_prep (const struct lu_env *env, struct cl_io *io, struct cl_page *pg, enum cl_req_type crt)
Prepares page for immediate transfer.
void cl_page_completion (const struct lu_env *env, struct cl_page *pg, enum cl_req_type crt, int ioret)
Notify layers about transfer completion.
int cl_page_make_ready (const struct lu_env *env, struct cl_page *pg, enum cl_req_type crt)
Notify layers that transfer formation engine decided to yank this page from the cache and to make it a part of a transfer.
int cl_page_cache_add (const struct lu_env *env, struct cl_io *io, struct cl_page *pg, enum cl_req_type crt)
void cl_page_clip (const struct lu_env *env, struct cl_page *pg, int from, int to)
Tells transfer engine that only part of a page is to be transmitted.
int cl_page_cancel (const struct lu_env *env, struct cl_page *page)
Cancel a page which is still in a transfer.
int cl_page_flush (const struct lu_env *env, struct cl_io *io, struct cl_page *pg)
Called if a pge is being written back by kernel's intention.
helper routines
Functions to discard, delete and export a cl_page.
void cl_page_discard (const struct lu_env *env, struct cl_io *io, struct cl_page *pg)
Called when page is to be removed from the object, e.g., as a result of truncate.
void cl_page_delete (const struct lu_env *env, struct cl_page *pg)
Called when a decision is made to throw page out of memory.
int cl_page_is_vmlocked (const struct lu_env *env, const struct cl_page *pg)
Returns true, iff pg is VM locked in a suitable sense by the calling thread.
void cl_page_export (const struct lu_env *env, struct cl_page *pg, int uptodate)
Marks page up-to-date.
loff_t cl_offset (const struct cl_object *obj, pgoff_t idx)
Converts a byte offset within object obj into a page index.
pgoff_t cl_index (const struct cl_object *obj, loff_t offset)
Converts a page index into a byte offset within object obj.
size_t cl_page_size (const struct cl_object *obj)
void cl_lock_print (const struct lu_env *env, void *cookie, lu_printer_t printer, const struct cl_lock *lock)
Prints human readable representation of lock to the f.
void cl_lock_descr_print (const struct lu_env *env, void *cookie, lu_printer_t printer, const struct cl_lock_descr *descr)
Prints human readable representation of a lock description.
Function Documentation
void cl_global_fini (void)
Finalization of global cl-data.
Dual to cl_global_init().
Definition at line 1403 of file cl_object.c.
References cl_env_percpu_fini(), cl_env_store_fini(), lu_context_key_degister(), and lu_kmem_fini().
Referenced by obdclass_exit().
int cl_global_init (void)
Global initialization of cl-data.
Create kmem caches, register lu_context_key's, etc.
See also:
cl_global_fini()
Definition at line 1365 of file cl_object.c.
References cl_env_percpu_init(), cl_env_store_fini(), cl_env_store_init(), cl_envs, INIT_LIST_HEAD, lu_context_key_degister(), LU_CONTEXT_KEY_INIT, lu_context_key_register(), lu_kmem_fini(), and lu_kmem_init().
Referenced by obdclass_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.