Lustre: lustre/obdclass/cl_io.c File Reference
lustre/obdclass/cl_io.c File Reference
#include <linux/sched.h>
#include <obd_class.h>
#include <obd_support.h>
#include <lustre_fid.h>
#include <libcfs/list.h>
#include <cl_object.h>
#include "cl_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_CLASS
#define cl_io_for_each(slice, io) list_for_each_entry((slice), &io->ci_layers, cis_linkage)
#define cl_io_for_each_reverse(slice, io) list_for_each_entry_reverse((slice), &io->ci_layers, cis_linkage)
Functions
static int cl_io_type_is_valid (enum cl_io_type type)
static int cl_io_is_loopable (const struct cl_io *io)
int cl_io_is_going (const struct lu_env *env)
Returns true iff there is an IO ongoing in the given environment.
static int cl_io_invariant (const struct cl_io *io)
cl_io invariant that holds at all times when exported cl_io_*() functions are entered and left.
void cl_io_fini (const struct lu_env *env, struct cl_io *io)
Finalize io, by calling cl_io_operations::cio_fini() bottom-to-top.
static int cl_io_init0 (const struct lu_env *env, struct cl_io *io, enum cl_io_type iot, struct cl_object *obj)
int cl_io_sub_init (const struct lu_env *env, struct cl_io *io, enum cl_io_type iot, struct cl_object *obj)
Initialize sub-io, by calling cl_io_operations::cio_init() top-to-bottom.
int cl_io_init (const struct lu_env *env, struct cl_io *io, enum cl_io_type iot, struct cl_object *obj)
Initialize io, by calling cl_io_operations::cio_init() top-to-bottom.
int cl_io_rw_init (const struct lu_env *env, struct cl_io *io, enum cl_io_type iot, loff_t pos, size_t count)
Initialize read or write io.
static int cl_lock_descr_sort (const struct cl_lock_descr *d0, const struct cl_lock_descr *d1)
static void cl_io_locks_sort (struct cl_io *io)
static void cl_lock_descr_merge (struct cl_lock_descr *d0, const struct cl_lock_descr *d1)
static int cl_lockset_merge (const struct cl_lockset *set, const struct cl_lock_descr *need)
static int cl_lockset_lock (const struct lu_env *env, struct cl_io *io, struct cl_lockset *set)
int cl_io_lock (const struct lu_env *env, struct cl_io *io)
Takes locks necessary for the current iteration of io.
void cl_io_unlock (const struct lu_env *env, struct cl_io *io)
Release locks takes by io.
int cl_io_iter_init (const struct lu_env *env, struct cl_io *io)
Prepares next iteration of io.
void cl_io_iter_fini (const struct lu_env *env, struct cl_io *io)
Finalizes io iteration.
void cl_io_rw_advance (const struct lu_env *env, struct cl_io *io, size_t nob)
Records that read or write io progressed nob bytes forward.
int cl_io_lock_add (const struct lu_env *env, struct cl_io *io, struct cl_io_lock_link *link)
Adds a lock to a lockset.
static void cl_free_io_lock_link (const struct lu_env *env, struct cl_io_lock_link *link)
int cl_io_lock_alloc_add (const struct lu_env *env, struct cl_io *io, struct cl_lock_descr *descr)
Allocates new lock link, and uses it to add a lock to a lockset.
int cl_io_start (const struct lu_env *env, struct cl_io *io)
Starts io by calling cl_io_operations::cio_start() top-to-bottom.
void cl_io_end (const struct lu_env *env, struct cl_io *io)
Wait until current io iteration is finished by calling cl_io_operations::cio_end() bottom-to-top.
int cl_io_read_ahead (const struct lu_env *env, struct cl_io *io, pgoff_t start, struct cl_read_ahead *ra)
Called by read io, to decide the readahead extent.
int cl_io_commit_async (const struct lu_env *env, struct cl_io *io, struct cl_page_list *queue, int from, int to, cl_commit_cbt cb)
Commit a list of contiguous pages into writeback cache.
int cl_io_submit_rw (const struct lu_env *env, struct cl_io *io, enum cl_req_type crt, struct cl_2queue *queue)
Submits a list of pages for immediate io.
int cl_io_submit_sync (const struct lu_env *env, struct cl_io *io, enum cl_req_type iot, struct cl_2queue *queue, long timeout)
Submit a sync_io and wait for the IO to be finished, or error happens.
int cl_io_cancel (const struct lu_env *env, struct cl_io *io, struct cl_page_list *queue)
Cancel an IO which has been submitted by cl_io_submit_rw.
int cl_io_loop (const struct lu_env *env, struct cl_io *io)
Main io loop.
void cl_io_slice_add (struct cl_io *io, struct cl_io_slice *slice, struct cl_object *obj, const struct cl_io_operations *ops)
Adds io slice to the cl_io.
void cl_page_list_init (struct cl_page_list *plist)
Initializes page list.
void cl_page_list_add (struct cl_page_list *plist, struct cl_page *page)
Adds a page to a page list.
void cl_page_list_del (const struct lu_env *env, struct cl_page_list *plist, struct cl_page *page)
Removes a page from a page list.
void cl_page_list_move (struct cl_page_list *dst, struct cl_page_list *src, struct cl_page *page)
Moves a page from one page list to another.
void cl_page_list_move_head (struct cl_page_list *dst, struct cl_page_list *src, struct cl_page *page)
Moves a page from one page list to the head of another list.
void cl_page_list_splice (struct cl_page_list *list, struct cl_page_list *head)
splice the cl_page_list, just as list head does
void cl_page_list_disown (const struct lu_env *env, struct cl_io *io, struct cl_page_list *plist)
Disowns pages in a queue.
void cl_page_list_fini (const struct lu_env *env, struct cl_page_list *plist)
Releases pages from queue.
int cl_page_list_own (const struct lu_env *env, struct cl_io *io, struct cl_page_list *plist)
Owns all pages in a queue.
void cl_page_list_assume (const struct lu_env *env, struct cl_io *io, struct cl_page_list *plist)
Assumes all pages in a queue.
void cl_page_list_discard (const struct lu_env *env, struct cl_io *io, struct cl_page_list *plist)
Discards all pages in a queue.
void cl_2queue_init (struct cl_2queue *queue)
Initialize dual page queue.
void cl_2queue_add (struct cl_2queue *queue, struct cl_page *page)
Add a page to the incoming page list of 2-queue.
void cl_2queue_disown (const struct lu_env *env, struct cl_io *io, struct cl_2queue *queue)
Disown pages in both lists of a 2-queue.
void cl_2queue_discard (const struct lu_env *env, struct cl_io *io, struct cl_2queue *queue)
Discard (truncate) pages in both lists of a 2-queue.
void cl_2queue_assume (const struct lu_env *env, struct cl_io *io, struct cl_2queue *queue)
Assume to own the pages in cl_2queue.
void cl_2queue_fini (const struct lu_env *env, struct cl_2queue *queue)
Finalize both page lists of a 2-queue.
void cl_2queue_init_page (struct cl_2queue *queue, struct cl_page *page)
Initialize a 2-queue to contain page in its incoming page list.
struct cl_io * cl_io_top (struct cl_io *io)
Returns top-level io.
void cl_io_print (const struct lu_env *env, void *cookie, lu_printer_t printer, const struct cl_io *io)
Prints human readable representation of io to the f.
void cl_req_attr_set (const struct lu_env *env, struct cl_object *obj, struct cl_req_attr *attr)
Fills in attributes that are passed to server together with transfer.
void cl_sync_io_end (const struct lu_env *env, struct cl_sync_io *anchor)
void cl_sync_io_init (struct cl_sync_io *anchor, int nr, void(*end)(const struct lu_env *, struct cl_sync_io *))
Initialize synchronous io wait anchor.
int cl_sync_io_wait (const struct lu_env *env, struct cl_sync_io *anchor, long timeout)
Wait until all IO completes.
void cl_sync_io_note (const struct lu_env *env, struct cl_sync_io *anchor, int ioret)
Indicate that transfer of a single page completed.
Define Documentation
#define cl_io_for_each (slice, io) list_for_each_entry((slice), &io->ci_layers, cis_linkage)
Definition at line 58 of file cl_io.c.
Referenced by cl_io_commit_async(), cl_io_iter_init(), cl_io_lock(), cl_io_read_ahead(), cl_io_start(), and cl_io_submit_rw().
#define cl_io_for_each_reverse (slice, io) list_for_each_entry_reverse((slice), &io->ci_layers, cis_linkage)
Definition at line 60 of file cl_io.c.
Referenced by cl_io_end(), cl_io_iter_fini(), cl_io_rw_advance(), and cl_io_unlock().
#define DEBUG_SUBSYSTEM S_CLASS
Definition at line 42 of file cl_io.c.
Function Documentation
static void cl_free_io_lock_link (const struct lu_env * env, struct cl_io_lock_link * link) [static]
Definition at line 532 of file cl_io.c.
References OBD_FREE_PTR.
Referenced by cl_io_lock_alloc_add().
static int cl_io_init0 (const struct lu_env * env, struct cl_io * io, enum cl_io_type iot, struct cl_object * obj) [static]
Definition at line 155 of file cl_io.c.
References cl_io::ci_layers, cl_io::ci_lockset, cl_io::ci_state, cl_io::ci_type, CIS_FINI, CIS_INIT, CIS_ZERO, cl_io_invariant(), cl_io_type_is_valid(), cl_object_for_each, cl_lockset::cls_done, cl_lockset::cls_todo, cl_object::co_ops, cl_object_operations::coo_io_init, ENTRY, INIT_LIST_HEAD, LINVRNT, and RETURN.
Referenced by cl_io_init(), and cl_io_sub_init().
static int cl_io_invariant (const struct cl_io * io) [static]
cl_io invariant that holds at all times when exported cl_io_*() functions are entered and left.
Definition at line 85 of file cl_io.c.
References cl_io::ci_owned_nr, cl_io::ci_parent, cl_io::ci_state, CIS_IO_GOING, CIS_LOCKED, and ergo.
Referenced by cl_io_end(), cl_io_fini(), cl_io_init0(), cl_io_iter_fini(), cl_io_iter_init(), cl_io_lock(), cl_io_read_ahead(), cl_io_rw_advance(), cl_io_start(), and cl_io_unlock().
static int cl_io_is_loopable (const struct cl_io * io) [inline, static]
Definition at line 68 of file cl_io.c.
References cl_io::ci_type, CIT_MISC, and cl_io_type_is_valid().
Referenced by cl_io_end(), cl_io_iter_fini(), cl_io_iter_init(), cl_io_lock(), cl_io_loop(), cl_io_rw_advance(), cl_io_start(), and cl_io_unlock().
static void cl_io_locks_sort (struct cl_io * io) [static]
Definition at line 256 of file cl_io.c.
References cl_io::ci_lockset, cl_io_lock_link::cill_linkage, cl_lock_descr_sort(), cl_lockset::cls_todo, done, ENTRY, EXIT, LBUG, list_for_each_entry_safe, and list_move_tail().
Referenced by cl_io_lock().
static int cl_io_type_is_valid (enum cl_io_type type) [inline, static]
Definition at line 63 of file cl_io.c.
References CIT_OP_NR, and CIT_READ.
Referenced by cl_io_fini(), cl_io_init0(), and cl_io_is_loopable().
static void cl_lock_descr_merge (struct cl_lock_descr * d0, const struct cl_lock_descr * d1) [static]
Definition at line 299 of file cl_io.c.
References cl_lock_descr::cld_end, cl_lock_descr::cld_mode, cl_lock_descr::cld_start, CLM_GROUP, CLM_WRITE, and max.
Referenced by cl_lockset_merge().
static int cl_lock_descr_sort (const struct cl_lock_descr * d0, const struct cl_lock_descr * d1) [static]
Definition at line 246 of file cl_io.c.
References cl_lock_descr::cld_obj, cl_object::co_lu, lu_fid_cmp(), and lu_object_fid().
Referenced by cl_io_locks_sort().
static int cl_lockset_lock (const struct lu_env * env, struct cl_io * io, struct cl_lockset * set) [static]
Definition at line 337 of file cl_io.c.
References cl_io_lock_link::cill_linkage, cl_io_lock_link::cill_lock, cl_lock_request(), ENTRY, list_for_each_entry_safe, list_move(), and RETURN.
Referenced by cl_io_lock().
static int cl_lockset_merge (const struct cl_lockset * set, const struct cl_lock_descr * need) [static]
Definition at line 312 of file cl_io.c.
References CDEBUG, cl_io_lock_link::cill_linkage, cl_lock_descr_merge(), cl_object_same(), cl_lock_descr::cld_obj, D_VFSTRACE, ENTRY, list_for_each_entry, and RETURN.
Referenced by cl_io_lock_add().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.