Lustre: lustre/obdclass/class_obd.c File Reference
lustre/obdclass/class_obd.c File Reference
#include <linux/user_namespace.h>
#include <linux/atomic.h>
#include <obd_support.h>
#include <obd_class.h>
#include <lnet/lnetctl.h>
#include <lustre_debug.h>
#include <lprocfs_status.h>
#include <lustre_ver.h>
#include <libcfs/list.h>
#include <cl_object.h>
#include <lustre_ioctl.h>
#include "llog_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_CLASS
#define OBD_INIT_CHECK
Functions
DEFINE_RWLOCK (obd_dev_lock)
static DEFINE_SPINLOCK (obd_updatemax_lock)
int lustre_get_jobid (char *jobid)
static int class_resolve_dev_name (__u32 len, const char *name)
int class_handle_ioctl (unsigned int cmd, unsigned long arg)
static int obd_init_checks (void)
static int __init obdclass_init (void)
void obd_update_maxusage (void)
static void __exit obdclass_exit (void)
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Class Driver")
MODULE_VERSION (LUSTRE_VERSION_STRING)
MODULE_LICENSE ("GPL")
module_init (obdclass_init)
module_exit (obdclass_exit)
Variables
struct obd_device * obd_devs [MAX_OBD_DEVICES]
struct list_head obd_types
__u64 obd_max_alloc
unsigned int obd_debug_peer_on_timeout
unsigned int obd_dump_on_timeout
unsigned int obd_dump_on_eviction
unsigned long obd_max_dirty_pages
atomic_long_t obd_dirty_pages
unsigned int obd_timeout = OBD_TIMEOUT_DEFAULT
unsigned int ldlm_timeout = LDLM_TIMEOUT_DEFAULT
unsigned int obd_timeout_set
unsigned int ldlm_timeout_set
unsigned int bulk_timeout = 100
unsigned int at_min = 0
unsigned int at_max = 600
unsigned int at_history = 600
int at_early_margin = 5
int at_extra = 30
atomic_long_t obd_dirty_transit_pages
char obd_jobid_var [JOBSTATS_JOBID_VAR_MAX_LEN+1] = JOBSTATS_DISABLE
char obd_jobid_node [LUSTRE_JOBID_SIZE+1]
Define Documentation
#define DEBUG_SUBSYSTEM S_CLASS
Definition at line 37 of file class_obd.c.
#define OBD_INIT_CHECK
Definition at line 422 of file class_obd.c.
Function Documentation
int class_handle_ioctl (unsigned int cmd, unsigned long arg)
Definition at line 212 of file class_obd.c.
References __user, buf, CDEBUG, CERROR, class_devno_max(), class_name2obd(), class_num2obd(), class_process_config(), class_resolve_dev_name(), class_uuid2dev(), D_HA, D_IOCTL, libcfs_debug_ioctl_data::debug, ENTRY, GOTO, obd_ioctl_data::ioc_bulk, obd_ioctl_data::ioc_count, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf4, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen4, obd_ioctl_data::ioc_pbuf1, obd_ioctl_data::ioc_plen1, LASSERT, libcfs_debug, LIBCFS_IOC_DEBUG_MASK, libcfs_subsystem_debug, lustre_cfg_sanity_check(), MAX_OBD_NAME, OBD_ALLOC, obd_device::obd_attached, OBD_DEV_BY_DEVNAME, OBD_DEVICE_MAGIC, OBD_FREE, OBD_GET_VERSION, OBD_IOC_GETDEVICE, OBD_IOC_NAME2DEV, OBD_IOC_NO_TRANSNO, OBD_IOC_PROCESS_CFG, OBD_IOC_UUID2DEV, obd_iocontrol(), obd_ioctl_getdata(), obd_ioctl_popdata(), obd_device::obd_magic, obd_device::obd_minor, obd_device::obd_name, obd_device::obd_no_transno, obd_device::obd_refcount, obd_device::obd_self_export, obd_device::obd_set_up, obd_device::obd_stopping, obd_str2uuid(), obd_device::obd_type, obd_device::obd_uuid, RETURN, status, strnlen, libcfs_debug_ioctl_data::subs, obd_type::typ_name, and obd_uuid::uuid.
Referenced by obd_class_ioctl().
static int class_resolve_dev_name (__u32 len, const char * name) [static]
Definition at line 183 of file class_obd.c.
References CDEBUG, CERROR, class_name2dev(), D_IOCTL, ENTRY, GOTO, and RETURN.
Referenced by class_handle_ioctl().
DEFINE_RWLOCK (obd_dev_lock)
static DEFINE_SPINLOCK (obd_updatemax_lock) [static]
int lustre_get_jobid (char * jobid)
Definition at line 130 of file class_obd.c.
References CDEBUG, cfs_get_environ(), current_comm, D_ERROR, D_INFO, ENTRY, from_kuid(), JOBSTATS_DISABLE, JOBSTATS_NODELOCAL, JOBSTATS_PROCNAME_UID, LCONSOLE_ERROR_MSG, LUSTRE_JOBID_SIZE, obd_jobid_node, obd_jobid_var, RETURN, and unlikely.
Referenced by lustre_msg_set_jobid(), and vvp_io_init().
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Class Driver")
module_exit (obdclass_exit)
module_init (obdclass_init)
MODULE_LICENSE ("GPL")
MODULE_VERSION (LUSTRE_VERSION_STRING)
static int obd_init_checks (void) [static]
Definition at line 424 of file class_obd.c.
References __u64, buf, CDEBUG, CERROR, CWARN, D_INFO, LPD64, LPU64, LPX64, OBD_OBJECT_EOF, and ret.
Referenced by obdclass_init().
void obd_update_maxusage (void)
Definition at line 583 of file class_obd.c.
References __u64, max, obd_max_alloc, and obd_memory_sum.
Referenced by ptlrpc_pinger_main().
static void __exit obdclass_exit (void) [static]
Definition at line 610 of file class_obd.c.
References __u64, CDEBUG, cl_global_fini(), class_exit_uuidlist(), class_handle_cleanup(), class_procfs_clean(), D_ERROR, D_INFO, dt_global_fini(), ENTRY, EXIT, LASSERT, list_empty(), llog_info_fini(), lprocfs_free_stats(), LPU64, lu_global_fini(), lu_ucred_global_fini(), lustre_unregister_fs(), obd_cleanup_caches(), obd_memory_max, obd_memory_sum, obd_psdev, obd_stale_exports, obd_sysctl_clean(), and obd_zombie_impexp_stop().
static int __init obdclass_init (void) [static]
Definition at line 495 of file class_obd.c.
References CERROR, cl_global_init(), class_devno_max(), class_handle_init(), class_init_uuidlist(), class_procfs_init(), dt_global_init(), INIT_LIST_HEAD, LCONSOLE_INFO, llog_info_init(), lprocfs_alloc_stats(), LPROCFS_CNTR_AVGMINMAX, lprocfs_counter_init(), LPROCFS_STATS_FLAG_IRQ_SAFE, LPROCFS_STATS_FLAG_NONE, lu_global_init(), lu_ucred_global_init(), lustre_register_fs(), OBD_DEV_MINOR, obd_init_caches(), obd_init_checks(), obd_max_dirty_pages, OBD_MEMORY_STAT, obd_psdev, obd_stale_export_lock, obd_stale_export_num, obd_stale_exports, OBD_STATS_NUM, obd_types, obd_types_lock, obd_zombie_impexp_init(), and RETURN.
Variable Documentation
int at_early_margin = 5
Definition at line 101 of file class_obd.c.
Referenced by class_set_global(), ptlrpc_at_check_timed(), ptlrpc_at_send_early_reply(), and ptlrpc_at_set_timer().
int at_extra = 30
Definition at line 103 of file class_obd.c.
Referenced by class_set_global(), ptlrpc_at_check_timed(), and ptlrpc_at_send_early_reply().
unsigned int at_history = 600
Definition at line 99 of file class_obd.c.
Referenced by at_measured(), and class_set_global().
unsigned int bulk_timeout = 100
Definition at line 92 of file class_obd.c.
unsigned int ldlm_timeout = LDLM_TIMEOUT_DEFAULT
Definition at line 85 of file class_obd.c.
Referenced by class_process_config(), ldlm_get_rq_timeout(), mdt_init0(), mgs_write_log_sys(), and proc_set_timeout().
unsigned int ldlm_timeout_set
Definition at line 89 of file class_obd.c.
Referenced by class_process_config(), and mgs_write_log_sys().
unsigned int obd_debug_peer_on_timeout
Definition at line 73 of file class_obd.c.
Referenced by ptlrpc_expire_one_request().
struct obd_device* obd_devs[MAX_OBD_DEVICES]
Definition at line 60 of file class_obd.c.
Referenced by class_newdev(), class_num2obd(), and class_release_dev().
atomic_long_t obd_dirty_pages
Definition at line 81 of file class_obd.c.
Referenced by osc_announce_cached(), osc_consume_write_grant(), osc_enter_cache_try(), osc_free_grant(), osc_release_write_grant(), and osc_wake_cache_waiters().
atomic_long_t obd_dirty_transit_pages
Definition at line 106 of file class_obd.c.
Referenced by osc_announce_cached(), osc_enter_cache_try(), and osc_release_write_grant().
unsigned int obd_dump_on_eviction
Definition at line 77 of file class_obd.c.
Referenced by ptlrpc_invalidate_import_thread().
unsigned int obd_dump_on_timeout
Definition at line 75 of file class_obd.c.
Referenced by class_fail_export(), ptlrpc_expire_one_request(), and ptlrpc_set_import_discon().
char obd_jobid_node[LUSTRE_JOBID_SIZE+1]
Definition at line 116 of file class_obd.c.
Referenced by lustre_get_jobid().
char obd_jobid_var[JOBSTATS_JOBID_VAR_MAX_LEN+1] = JOBSTATS_DISABLE
Definition at line 109 of file class_obd.c.
Referenced by class_set_global(), and lustre_get_jobid().
__u64 obd_max_alloc
Definition at line 67 of file class_obd.c.
Referenced by obd_memory_add(), and obd_update_maxusage().
unsigned long obd_max_dirty_pages
Definition at line 79 of file class_obd.c.
Referenced by obdclass_init(), osc_announce_cached(), osc_enter_cache_try(), osc_wake_cache_waiters(), and proc_max_dirty_pages_in_mb().
unsigned int obd_timeout = OBD_TIMEOUT_DEFAULT
Definition at line 83 of file class_obd.c.
Referenced by __ldlm_namespace_free(), class_new_export(), class_process_config(), ldlm_cp_timeout(), ldlm_get_rq_timeout(), ldlm_lock_match(), lfsck_layout_slave_async_interpret(), lov_check_and_wait_active(), mdc_finish_intent_lock(), mdt_getattr_name_lock(), mdt_reint_open(), mgc_process_log(), mgs_write_log_sys(), osc_enter_cache(), osp_precreate_reserve(), osp_statfs_update(), osp_sync(), proc_set_timeout(), prolong_timeout(), ptlrpc_at_set_req_timeout(), ptlrpc_disconnect_import(), ptlrpc_invalidate_import(), ptlrpc_next_reconnect(), ptlrpc_reconnect_import(), ptlrpc_recover_import(), ptlrpc_server_get_timeout(), ptlrpc_server_handle_req_in(), ptlrpc_svcpt_health_check(), ptlrpcd_add_work_req(), qsd_wait_timeout(), tgt_brw_read(), and tgt_brw_write().
unsigned int obd_timeout_set
Definition at line 87 of file class_obd.c.
Referenced by class_process_config(), and mgs_write_log_sys().
struct list_head obd_types
Definition at line 61 of file class_obd.c.
Referenced by class_register_type(), class_search_type(), lfs_check(), and obdclass_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.