Lustre: lustre/ptlrpc/client.c File Reference
lustre/ptlrpc/client.c File Reference
#include <obd_support.h>
#include <obd_class.h>
#include <lustre_lib.h>
#include <lustre_ha.h>
#include <lustre_import.h>
#include <lustre_req_layout.h>
#include "ptlrpc_internal.h"
Data Structures
struct ptlrpc_work_async_args
Functions for operating ptlrpc workers.
Defines
#define DEBUG_SUBSYSTEM S_RPC
Implementation of client-side PortalRPC interfaces.
#define YEAR_2004 (1ULL << 30)
Initialize the XID for the node.
Functions
static int ptlrpc_send_new_req (struct ptlrpc_request *req)
Helper function to send request req over the network for the first time Also adjusts request phase.
static int ptlrpcd_check_work (struct ptlrpc_request *req)
static int ptlrpc_unregister_reply (struct ptlrpc_request *request, int async)
Disengage the client's reply buffer from the network NB does _NOT_ unregister any client-side bulk.
void ptlrpc_init_client (int req_portal, int rep_portal, char *name, struct ptlrpc_client *cl)
Initialize passed in client structure cl.
struct ptlrpc_connection * ptlrpc_uuid_to_connection (struct obd_uuid *uuid)
Return PortalRPC connection for remore uud uuid.
struct ptlrpc_bulk_desc * ptlrpc_new_bulk (unsigned nfrags, unsigned max_brw, enum ptlrpc_bulk_op_type type, unsigned portal, const struct ptlrpc_bulk_frag_ops *ops)
Allocate and initialize new bulk descriptor on the sender.
struct ptlrpc_bulk_desc * ptlrpc_prep_bulk_imp (struct ptlrpc_request *req, unsigned nfrags, unsigned max_brw, unsigned int type, unsigned portal, const struct ptlrpc_bulk_frag_ops *ops)
Prepare bulk descriptor for specified outgoing request req that can fit nfrags * pages.
void __ptlrpc_prep_bulk_page (struct ptlrpc_bulk_desc *desc, struct page *page, int pageoffset, int len, int pin)
int ptlrpc_prep_bulk_frag (struct ptlrpc_bulk_desc *desc, void *frag, int len)
void ptlrpc_free_bulk (struct ptlrpc_bulk_desc *desc)
void ptlrpc_at_set_req_timeout (struct ptlrpc_request *req)
Set server timelimit for this req, i.e.
static void ptlrpc_at_adj_service (struct ptlrpc_request *req, unsigned int serv_est)
int ptlrpc_at_get_net_latency (struct ptlrpc_request *req)
void ptlrpc_at_adj_net_latency (struct ptlrpc_request *req, unsigned int service_time)
static int unpack_reply (struct ptlrpc_request *req)
static int ptlrpc_at_recv_early_reply (struct ptlrpc_request *req) __must_hold(&req->rq_lock)
Handle an early reply message, called with the rq_lock held.
int ptlrpc_request_cache_init (void)
void ptlrpc_request_cache_fini (void)
struct ptlrpc_request * ptlrpc_request_cache_alloc (gfp_t flags)
void ptlrpc_request_cache_free (struct ptlrpc_request *req)
void ptlrpc_free_rq_pool (struct ptlrpc_request_pool *pool)
Wind down request pool pool.
int ptlrpc_add_rqs_to_pool (struct ptlrpc_request_pool *pool, int num_rq)
Allocates, initializes and adds num_rq requests to the pool pool.
struct ptlrpc_request_pool * ptlrpc_init_rq_pool (int num_rq, int msgsize, int(*populate_pool)(struct ptlrpc_request_pool *, int))
Create and initialize new request pool with given attributes: num_rq - initial number of requests to create for the pool msgsize - maximum message size possible for requests in thid pool populate_pool - function to be called when more requests need to be added to the pool Returns pointer to newly created pool or NULL on error.
static struct ptlrpc_request * ptlrpc_prep_req_from_pool (struct ptlrpc_request_pool *pool)
Fetches one request from pool pool.
static void __ptlrpc_free_req_to_pool (struct ptlrpc_request *request)
Returns freed request to pool.
void ptlrpc_add_unreplied (struct ptlrpc_request *req)
void ptlrpc_assign_next_xid_nolock (struct ptlrpc_request *req)
static void ptlrpc_assign_next_xid (struct ptlrpc_request *req)
int ptlrpc_request_bufs_pack (struct ptlrpc_request *request, __u32 version, int opcode, char **bufs, struct ptlrpc_cli_ctx *ctx)
int ptlrpc_request_pack (struct ptlrpc_request *request, __u32 version, int opcode)
Pack request buffers for network transfer, performing necessary encryption steps if necessary.
static struct ptlrpc_request * __ptlrpc_request_alloc (struct obd_import *imp, struct ptlrpc_request_pool *pool)
Helper function to allocate new request on import imp and possibly using existing request from pool pool if provided.
static struct ptlrpc_request * ptlrpc_request_alloc_internal (struct obd_import *imp, struct ptlrpc_request_pool *pool, const struct req_format *format)
Helper function for creating a request.
struct ptlrpc_request * ptlrpc_request_alloc (struct obd_import *imp, const struct req_format *format)
Allocate new request structure for import imp and initialize its buffer structure according to capsule template format.
struct ptlrpc_request * ptlrpc_request_alloc_pool (struct obd_import *imp, struct ptlrpc_request_pool *pool, const struct req_format *format)
Allocate new request structure for import imp from pool pool and initialize its buffer structure according to capsule template format.
void ptlrpc_request_free (struct ptlrpc_request *request)
For requests not from pool, free memory of the request structure.
struct ptlrpc_request * ptlrpc_request_alloc_pack (struct obd_import *imp, const struct req_format *format, __u32 version, int opcode)
Allocate new request for operatione opcode and immediatelly pack it for network transfer.
struct ptlrpc_request_set * ptlrpc_prep_set (void)
Allocate and initialize new request set structure on the current CPT.
struct ptlrpc_request_set * ptlrpc_prep_fcset (int max, set_producer_func func, void *arg)
Allocate and initialize new request set structure with flow control extension.
void ptlrpc_set_destroy (struct ptlrpc_request_set *set)
Wind down and free request set structure previously allocated with ptlrpc_prep_set.
int ptlrpc_set_add_cb (struct ptlrpc_request_set *set, set_interpreter_func fn, void *data)
Add a callback function fn to the set.
void ptlrpc_set_add_req (struct ptlrpc_request_set *set, struct ptlrpc_request *req)
Add a new request to the general purpose request set.
void ptlrpc_set_add_new_req (struct ptlrpcd_ctl *pc, struct ptlrpc_request *req)
Add a request to a request with dedicated server thread and wake the thread to make any necessary processing.
static int ptlrpc_import_delay_req (struct obd_import *imp, struct ptlrpc_request *req, int *status)
Based on the current state of the import, determine if the request can be sent, is an error, or should be delayed.
static bool ptlrpc_console_allow (struct ptlrpc_request *req)
Decide if the error message should be printed to the console or not.
static int ptlrpc_check_status (struct ptlrpc_request *req)
Check request processing status.
static void ptlrpc_save_versions (struct ptlrpc_request *req)
save pre-versions of objects into request for replay.
__u64 ptlrpc_known_replied_xid (struct obd_import *imp)
static int after_reply (struct ptlrpc_request *req)
Callback function called when client receives RPC reply for req.
static int ptlrpc_set_producer (struct ptlrpc_request_set *set)
int ptlrpc_check_set (const struct lu_env *env, struct ptlrpc_request_set *set)
this sends any unsent RPCs in set and returns 1 if all are sent and no more replies are expected.
int ptlrpc_expire_one_request (struct ptlrpc_request *req, int async_unlink)
Time out request req.
int ptlrpc_expired_set (void *data)
Time out all uncompleted requests in request set pointed by data Callback used when waiting on sets with l_wait_event.
void ptlrpc_mark_interrupted (struct ptlrpc_request *req)
Sets rq_intr flag in req under spinlock.
static void ptlrpc_interrupted_set (void *data)
Interrupts (sets interrupted flag) all uncompleted requests in a set data.
int ptlrpc_set_next_timeout (struct ptlrpc_request_set *set)
Get the smallest timeout in the set; this does NOT set a timeout.
int ptlrpc_set_wait (struct ptlrpc_request_set *set)
Send all unset request from the set and then wait untill all requests in the set complete (either get a reply, timeout, get an error or otherwise be interrupted).
static void __ptlrpc_free_req (struct ptlrpc_request *request, int locked)
Helper fuction for request freeing.
static int __ptlrpc_req_finished (struct ptlrpc_request *request, int locked)
Helper function Drops one reference count for request request.
void ptlrpc_req_finished_with_imp_lock (struct ptlrpc_request *request)
Drop one request reference.
void ptlrpc_req_finished (struct ptlrpc_request *request)
Drops one reference count for a request.
__u64 ptlrpc_req_xid (struct ptlrpc_request *request)
Returns xid of a request.
static void ptlrpc_free_request (struct ptlrpc_request *req)
void ptlrpc_request_committed (struct ptlrpc_request *req, int force)
the request is committed and dropped from the replay list of its import
void ptlrpc_free_committed (struct obd_import *imp)
Iterates through replay_list on import and prunes all requests have transno smaller than last_committed for the import and don't have rq_replay set.
void ptlrpc_cleanup_client (struct obd_import *imp)
void ptlrpc_resend_req (struct ptlrpc_request *req)
Schedule previously sent request for resend.
void ptlrpc_restart_req (struct ptlrpc_request *req)
struct ptlrpc_request * ptlrpc_request_addref (struct ptlrpc_request *req)
Grab additional reference on a request req.
void ptlrpc_retain_replayable_request (struct ptlrpc_request *req, struct obd_import *imp)
Add a request to import replay_list.
int ptlrpc_queue_wait (struct ptlrpc_request *req)
Send request and wait until it completes.
static int ptlrpc_replay_interpret (const struct lu_env *env, struct ptlrpc_request *req, void *data, int rc)
Callback used for replayed requests reply processing.
int ptlrpc_replay_req (struct ptlrpc_request *req)
Prepares and queues request for replay.
void ptlrpc_abort_inflight (struct obd_import *imp)
Aborts all in-flight request on import imp sending and delayed lists.
void ptlrpc_abort_set (struct ptlrpc_request_set *set)
Abort all uncompleted requests in request set set.
void ptlrpc_init_xid (void)
__u64 ptlrpc_next_xid (void)
Increase xid and returns resulting new value to the caller.
void ptlrpc_set_bulk_mbits (struct ptlrpc_request *req)
If request has a new allocated XID (new request or EINPROGRESS resend), use this XID as matchbits of bulk, otherwise allocate a new matchbits for request to ensure previous bulk fails and avoid problems with lost replies and therefore several transfers landing into the same buffer from different sending attempts.
__u64 ptlrpc_sample_next_xid (void)
Get a glimpse at what next xid value might have been.
static void ptlrpcd_add_work_req (struct ptlrpc_request *req)
static int work_interpreter (const struct lu_env *env, struct ptlrpc_request *req, void *data, int rc)
void * ptlrpcd_alloc_work (struct obd_import *imp, int(*cb)(const struct lu_env *, void *), void *cbdata)
Create a work for ptlrpc.
void ptlrpcd_destroy_work (void *handler)
int ptlrpcd_queue_work (void *handler)
Variables
struct ptlrpc_bulk_frag_ops ptlrpc_bulk_kiov_pin_ops
struct ptlrpc_bulk_frag_ops ptlrpc_bulk_kiov_nopin_ops
struct ptlrpc_bulk_frag_ops ptlrpc_bulk_kvec_ops
static struct kmem_cache * request_cache
static __u64 ptlrpc_last_xid
static spinlock_t ptlrpc_last_xid_lock
static int worker_format
Define Documentation
#define DEBUG_SUBSYSTEM S_RPC
Implementation of client-side PortalRPC interfaces.
Definition at line 39 of file client.c.
#define YEAR_2004 (1ULL << 30)
Initialize the XID for the node.
This is common among all requests on this node, and only requires the property that it is monotonically increasing. It does not need to be sequential. Since this is also used as the RDMA match bits, it is important that a single client NOT have the same match bits for two different in-flight requests, hence we do NOT want to have an XID per target or similar.
To avoid an unlikely collision between match bits after a client reboot (which would deliver old data into the wrong RDMA buffer) initialize the XID based on the current time, assuming a maximum RPC rate of 1M RPC/s. If the time is clearly incorrect, we instead use a 62-bit random number. In the worst case the random number will overflow 1M RPCs per second in 9133 years, or permutations thereof.
Definition at line 3146 of file client.c.
Referenced by ptlrpc_init_xid().
Function Documentation
static void __ptlrpc_free_req (struct ptlrpc_request * request, int locked) [static]
Helper fuction for request freeing.
Called when request count reached zero and request needs to be freed. Removes request from all sorts of sending/replay lists it might be on, frees network buffers if any are present. If locked is set, that means caller is already holding import imp_lock and so we no longer need to reobtain it (for certain lists manipulations)
Definition at line 2389 of file client.c.
References __ptlrpc_free_req_to_pool(), class_import_put(), D_ERROR, DEBUG_REQ, ENTRY, EXIT, obd_import::imp_lock, LASSERT, LASSERTF, LBUG, list_del_init(), list_empty(), ptlrpc_free_bulk(), ptlrpc_request_cache_free(), req_capsule_fini(), RETURN_EXIT, ptlrpc_request::rq_clrbuf, ptlrpc_request::rq_export, ptlrpc_request::rq_import, ptlrpc_request::rq_list, ptlrpc_request::rq_pill, ptlrpc_request::rq_pool, ptlrpc_request::rq_receiving_reply, ptlrpc_request::rq_refcount, ptlrpc_request::rq_repbuf, ptlrpc_request::rq_replay, ptlrpc_request::rq_replay_list, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_srv_req, sptlrpc_cli_free_repbuf(), sptlrpc_cli_free_reqbuf(), and sptlrpc_req_put_ctx().
Referenced by __ptlrpc_req_finished().
static void __ptlrpc_free_req_to_pool (struct ptlrpc_request * request) [static]
Returns freed request to pool.
Definition at line 647 of file client.c.
References LASSERT, list_add_tail(), list_empty(), ptlrpc_request_pool::prp_lock, ptlrpc_request_pool::prp_req_list, ptlrpc_request::rq_list, ptlrpc_request::rq_pool, and ptlrpc_request::rq_receiving_reply.
Referenced by __ptlrpc_free_req(), and ptlrpc_request_free().
static int __ptlrpc_req_finished (struct ptlrpc_request * request, int locked) [static]
Helper function Drops one reference count for request request.
locked set indicates that caller holds import imp_lock. Frees the request whe reference count reaches zero.
Definition at line 2463 of file client.c.
References __ptlrpc_free_req(), CERROR, D_INFO, DEBUG_REQ, ENTRY, LBUG, RETURN, ptlrpc_request::rq_refcount, and ptlrpc_request::rq_reqmsg.
Referenced by ptlrpc_free_request(), ptlrpc_req_finished(), and ptlrpc_req_finished_with_imp_lock().
static struct ptlrpc_request* __ptlrpc_request_alloc (struct obd_import * imp, struct ptlrpc_request_pool * pool) [static, read]
Helper function to allocate new request on import imp and possibly using existing request from pool pool if provided.
Returns allocated request structure with import field filled or NULL on error.
Definition at line 799 of file client.c.
References CERROR, class_import_get(), obd_import::imp_client, LASSERT, LASSERTF, ptlrpc_cli_req_init(), ptlrpc_prep_req_from_pool(), ptlrpc_request_cache_alloc(), and ptlrpc_request::rq_import.
Referenced by ptlrpc_request_alloc_internal().
static int after_reply (struct ptlrpc_request * req) [static]
Callback function called when client receives RPC reply for req.
Returns 0 on success or error code. The return alue would be assigned to req->rq_status by the caller as request processing status. This function also decides if the request needs to be saved for later replay.
version recovery
Definition at line 1297 of file client.c.
References __u64, CFS_FAIL_TIMEOUT, cfs_fail_val, cfs_time_current_sec(), cfs_timeval_sub(), D_ERROR, D_RPCTRACE, DEBUG_REQ, ENTRY, obd_import::imp_connect_error, obd_import::imp_dlm_fake, obd_import::imp_lock, obd_import::imp_obd, obd_import::imp_peer_committed_transno, obd_import::imp_replay_list, obd_import::imp_replayable, LASSERT, ldlm_cli_update_pool(), likely, list_del_init(), list_empty(), list_entry, lprocfs_counter_add(), LUSTRE_IMP_FULL, lustre_msg_get_flags(), lustre_msg_get_last_committed(), lustre_msg_get_opc(), lustre_msg_get_service_time(), lustre_msg_get_status(), lustre_msg_get_timeout(), lustre_msg_get_transno(), lustre_msg_get_type(), lustre_msg_set_transno(), MSG_REPLAY, now(), OBD_FAIL_PTLRPC_PAUSE_REP, obd_device::obd_no_recov, OBD_PING, obd_device::obd_svc_stats, list_head::prev, PTL_RPC_MSG_ERR, PTL_RPC_MSG_REPLY, ptlrpc_at_adj_net_latency(), ptlrpc_at_adj_service(), ptlrpc_at_set_req_timeout(), ptlrpc_check_status(), ptlrpc_free_committed(), ptlrpc_lprocfs_rpc_sent, ptlrpc_no_resend(), ptlrpc_pinger_commit_expected(), ptlrpc_recoverable_error(), ptlrpc_request_handle_notconn(), PTLRPC_REQWAIT_CNTR, ptlrpc_retain_replayable_request(), ptlrpc_save_versions(), RETURN, ptlrpc_request::rq_import, ptlrpc_request::rq_lock, ptlrpc_request::rq_no_retry_einprogress, ptlrpc_request::rq_nob_received, ptlrpc_request::rq_receiving_reply, ptlrpc_request::rq_repbuf_len, ptlrpc_request::rq_replay, ptlrpc_request::rq_replay_list, ptlrpc_request::rq_replen, ptlrpc_request::rq_reply_truncated, ptlrpc_request::rq_reply_unlinked, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_resend, ptlrpc_request::rq_sent, ptlrpc_request::rq_timeout, ptlrpc_request::rq_transno, sptlrpc_cli_free_repbuf(), sptlrpc_cli_unwrap_reply(), and unpack_reply().
Referenced by ptlrpc_check_set().
void ptlrpc_add_unreplied (struct ptlrpc_request * req)
Definition at line 658 of file client.c.
References obd_import::imp_lock, obd_import::imp_unreplied_list, LASSERT, list_add(), list_empty(), list_entry, list_for_each_prev, ptlrpc_request::rq_import, rq_unreplied_list, and ptlrpc_request::rq_xid.
Referenced by ptlrpc_assign_next_xid_nolock(), ptlrpc_prepare_replay(), and ptlrpc_replay_next().
static void ptlrpc_assign_next_xid (struct ptlrpc_request * req) [inline, static]
Definition at line 687 of file client.c.
References obd_import::imp_lock, ptlrpc_assign_next_xid_nolock(), and ptlrpc_request::rq_import.
Referenced by ptlrpc_request_bufs_pack().
void ptlrpc_assign_next_xid_nolock (struct ptlrpc_request * req)
Definition at line 681 of file client.c.
References ptlrpc_add_unreplied(), ptlrpc_next_xid(), and ptlrpc_request::rq_xid.
Referenced by ptl_send_rpc(), and ptlrpc_assign_next_xid().
void ptlrpc_at_adj_net_latency (struct ptlrpc_request * req, unsigned int service_time)
Definition at line 357 of file client.c.
References at_get(), at_measured(), ptlrpc_connection::c_remote_uuid, CDEBUG, CFS_DURATION_T, cfs_time_current_sec(), cfs_time_sub(), D_ADAPTTO, D_WARNING, imp_at::iat_net_latency, obd_import::imp_at, obd_import::imp_connection, obd_import::imp_obd, LASSERT, lustre_msg_get_flags(), MSG_RESENT, now(), obd_device::obd_name, obd_uuid2str(), ptlrpc_request::rq_import, ptlrpc_request::rq_reqmsg, and ptlrpc_request::rq_sent.
Referenced by after_reply(), ptlrpc_at_recv_early_reply(), and ptlrpc_connect_interpret().
static void ptlrpc_at_adj_service (struct ptlrpc_request * req, unsigned int serv_est) [static]
Definition at line 329 of file client.c.
References at_get(), at_measured(), CDEBUG, D_ADAPTTO, imp_at::iat_service_estimate, obd_import::imp_at, obd_import::imp_obd, import_at_get_index(), LASSERT, obd_device::obd_name, and ptlrpc_request::rq_import.
Referenced by after_reply().
static int ptlrpc_at_recv_early_reply (struct ptlrpc_request * req) [static]
Handle an early reply message, called with the rq_lock held.
If anything goes wrong just ignore it - same as if it never happened
Definition at line 421 of file client.c.
References CFS_DURATION_T, cfs_time_current_sec(), cfs_time_sub(), D_ADAPTTO, DEBUG_REQ, ENTRY, lustre_msg_get_service_time(), lustre_msg_get_timeout(), lustre_msg_set_timeout(), ptlrpc_at_adj_net_latency(), ptlrpc_at_get_net_latency(), RETURN, ptlrpc_request::rq_repmsg, sptlrpc_cli_finish_early_reply(), sptlrpc_cli_unwrap_early_reply(), and unpack_reply().
Referenced by ptlrpc_check_set().
static int ptlrpc_check_status (struct ptlrpc_request * req) [static]
Check request processing status.
Returns the status.
Definition at line 1219 of file client.c.
References ptlrpc_connection::c_peer, D_INFO, DEBUG_REQ, ENTRY, obd_import::imp_connection, obd_import::imp_obd, LCONSOLE_ERROR_MSG, libcfs_nid2str(), ll_opcode2str(), lustre_msg_get_opc(), lustre_msg_get_status(), lustre_msg_get_type(), lnet_process_id_t::nid, obd_device::obd_name, PTL_RPC_MSG_ERR, ptlrpc_console_allow(), RETURN, ptlrpc_request::rq_import, ptlrpc_request::rq_repmsg, and ptlrpc_request::rq_reqmsg.
Referenced by after_reply().
static bool ptlrpc_console_allow (struct ptlrpc_request * req) [static]
Decide if the error message should be printed to the console or not.
Makes its decision based on request type, status, and failure frequency.
Parameters:
[in] req request that failed and may need a console message
Return values:
false if no message should be printed
true if console message should be printed
Definition at line 1187 of file client.c.
References obd_import::imp_conn_cnt, obd_import::imp_remote_handle, LASSERT, lustre_handle_is_used(), lustre_msg_get_opc(), lustre_msg_get_status(), MDS_CONNECT, MGS_CONNECT, OST_CONNECT, ptlrpc_request::rq_import, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_reqmsg, and ptlrpc_request::rq_timedout.
Referenced by ptlrpc_check_status().
int ptlrpc_expire_one_request (struct ptlrpc_request * req, int async_unlink)
Time out request req.
is async_unlink is set, that means do not wait until LNet actually confirms network buffer unlinking. Return 1 if we should give up further retrying attempts or 0 otherwise.
Definition at line 2050 of file client.c.
References ptlrpc_connection::c_peer, CFS_DURATION_T, cfs_time_aftereq(), cfs_time_before(), D_HA, D_RPCTRACE, D_WARNING, DEBUG_REQ, ENTRY, obd_import::imp_connection, obd_import::imp_dlm_fake, obd_import::imp_obd, obd_import::imp_state, obd_import::imp_timeouts, libcfs_debug_dumplog(), LNetDebugPeer(), LUSTRE_IMP_FULL, lustre_msg_get_conn_cnt(), obd_debug_peer_on_timeout, obd_dump_on_timeout, obd_device::obd_no_recov, ptlrpc_fail_import(), ptlrpc_import_state_name(), ptlrpc_no_resend(), ptlrpc_unregister_bulk(), ptlrpc_unregister_reply(), RETURN, ptlrpc_request::rq_ctx_fini, ptlrpc_request::rq_ctx_init, ptlrpc_request::rq_deadline, ptlrpc_request::rq_err, ptlrpc_request::rq_import, ptlrpc_request::rq_lock, ptlrpc_request::rq_net_err, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_sent, ptlrpc_request::rq_status, and ptlrpc_request::rq_timedout.
Referenced by ctx_refresh_timeout(), ptlrpc_check_set(), and ptlrpc_expired_set().
int ptlrpc_expired_set (void * data)
Time out all uncompleted requests in request set pointed by data Callback used when waiting on sets with l_wait_event.
Always returns 1.
Definition at line 2121 of file client.c.
References cfs_time_current_sec(), ENTRY, LASSERT, list_entry, list_for_each, now(), ptlrpc_expire_one_request(), RETURN, ptlrpc_request::rq_deadline, ptlrpc_request::rq_phase, RQ_PHASE_BULK, RQ_PHASE_RPC, ptlrpc_request::rq_resend, rq_set_chain, ptlrpc_request::rq_timedout, ptlrpc_request::rq_wait_ctx, and ptlrpc_request::rq_waiting.
Referenced by ptlrpc_set_wait(), and ptlrpcd().
static void ptlrpc_free_request (struct ptlrpc_request * req) [static]
Definition at line 2585 of file client.c.
References __ptlrpc_req_finished(), list_del_init(), ptlrpc_request::rq_lock, ptlrpc_request::rq_replay, and ptlrpc_request::rq_replay_list.
Referenced by ptlrpc_free_committed(), ptlrpc_replay_interpret(), and ptlrpc_request_committed().
static int ptlrpc_import_delay_req (struct obd_import * imp, struct ptlrpc_request * req, int * status) [static]
Based on the current state of the import, determine if the request can be sent, is an error, or should be delayed.
Returns true if this request should be delayed. If false, and *status is set, then the request can not be sent and *status is the error code. If false and status is 0, then request can be sent.
The imp->imp_lock must be held.
Definition at line 1120 of file client.c.
References D_ERROR, D_HA, D_NET, DEBUG_REQ, ENTRY, obd_import::imp_deactive, obd_import::imp_dlm_fake, obd_import::imp_generation, obd_import::imp_inval_count, obd_import::imp_invalid, obd_import::imp_obd, obd_import::imp_state, LASSERT, LUSTRE_IMP_CLOSED, LUSTRE_IMP_CONNECTING, LUSTRE_IMP_NEW, LUSTRE_IMP_RECOVER, LUSTRE_IMP_REPLAY, LUSTRE_IMP_REPLAY_LOCKS, LUSTRE_IMP_REPLAY_WAIT, lustre_msg_get_opc(), obd_device::obd_no_recov, OBD_PING, ptlrpc_send_limit_expired(), RETURN, ptlrpc_request::rq_allow_replay, ptlrpc_request::rq_ctx_fini, ptlrpc_request::rq_ctx_init, ptlrpc_request::rq_no_delay, and ptlrpc_request::rq_reqmsg.
Referenced by ptlrpc_check_set(), and ptlrpc_send_new_req().
void ptlrpc_init_xid (void)
Definition at line 3147 of file client.c.
References __u64, cfs_get_random_bytes(), cfs_time_current_sec(), CLASSERT, now(), PTLRPC_BULK_OPS_COUNT, PTLRPC_BULK_OPS_MASK, and YEAR_2004.
Referenced by ptlrpc_init().
static void ptlrpc_interrupted_set (void * data) [static]
Interrupts (sets interrupted flag) all uncompleted requests in a set data.
Callback for l_wait_event for interruptible waits.
Definition at line 2180 of file client.c.
References CDEBUG, D_RPCTRACE, LASSERT, list_entry, list_for_each, ptlrpc_mark_interrupted(), ptlrpc_request::rq_allow_intr, ptlrpc_request::rq_intr, ptlrpc_request::rq_phase, RQ_PHASE_RPC, RQ_PHASE_UNREGISTERING, and rq_set_chain.
Referenced by ptlrpc_set_wait().
__u64 ptlrpc_known_replied_xid (struct obd_import * imp)
Definition at line 1272 of file client.c.
References obd_import::imp_known_replied_xid, obd_import::imp_lock, obd_import::imp_unreplied_list, LASSERTF, list_empty(), list_entry, LPU64, list_head::next, rq_unreplied_list, and ptlrpc_request::rq_xid.
Referenced by ptl_send_rpc(), ptlrpc_prepare_replay(), and ptlrpc_send_new_req().
struct ptlrpc_bulk_desc* ptlrpc_new_bulk (unsigned nfrags, unsigned max_brw, enum ptlrpc_bulk_op_type type, unsigned portal, const struct ptlrpc_bulk_frag_ops * ops) [read]
Allocate and initialize new bulk descriptor on the sender.
Returns pointer to the descriptor or NULL on error.
Definition at line 117 of file client.c.
References ptlrpc_bulk_frag_ops::add_iov_frag, ptlrpc_bulk_frag_ops::add_kiov_frag, ptlrpc_bulk_desc::bd_frag_ops, ptlrpc_bulk_desc::bd_iov_count, ptlrpc_bulk_desc::bd_lock, ptlrpc_bulk_desc::bd_max_iov, ptlrpc_bulk_desc::bd_md_count, ptlrpc_bulk_desc::bd_md_max_brw, ptlrpc_bulk_desc::bd_mds, ptlrpc_bulk_desc::bd_portal, ptlrpc_bulk_desc::bd_type, ptlrpc_bulk_desc::bd_waitq, GET_KIOV, GET_KVEC, LASSERT, LNetInvalidateHandle(), OBD_ALLOC_LARGE, OBD_ALLOC_PTR, OBD_FREE_PTR, PTLRPC_BULK_BUF_KIOV, PTLRPC_BULK_OPS_COUNT, ptlrpc_is_bulk_desc_kiov(), and ptlrpc_is_bulk_desc_kvec().
Referenced by ptlrpc_prep_bulk_imp().
static struct ptlrpc_request* ptlrpc_prep_req_from_pool (struct ptlrpc_request_pool * pool) [static, read]
Fetches one request from pool pool.
Definition at line 608 of file client.c.
References LASSERT, list_del_init(), list_empty(), list_entry, lustre_msg, list_head::next, ptlrpc_request_pool::prp_lock, ptlrpc_request_pool::prp_req_list, ptlrpc_request_pool::prp_rq_size, ptlrpc_request::rq_list, ptlrpc_request::rq_pool, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqbuf_len, and unlikely.
Referenced by __ptlrpc_request_alloc().
static int ptlrpc_replay_interpret (const struct lu_env * env, struct ptlrpc_request * req, void * data, int rc) [static]
Callback used for replayed requests reply processing.
In case of successful reply calls registered request replay callback. In case of error restart replay process.
VBR: check version failure
replay was failed due to version mismatch
The transno had better not change over replay.
if replays by version then gap occur on server, no trust to locks
Definition at line 2862 of file client.c.
References CERROR, D_ERROR, D_HA, D_WARNING, DEBUG_REQ, ENTRY, GOTO, obd_import::imp_committed_list, obd_import::imp_connect_flags_orig, obd_import::imp_delayed_list, obd_import::imp_last_replay_transno, obd_import::imp_lock, obd_import::imp_no_lock_replay, obd_import::imp_replay_inflight, obd_import::imp_replay_list, obd_import::imp_sending_list, obd_import::imp_vbr_failed, LASSERT, LASSERTF, list_for_each_entry_safe, LPU64, LPX64, lustre_msg_get_flags(), lustre_msg_get_status(), lustre_msg_get_transno(), lustre_msg_get_type(), lustre_msg_set_status(), MSG_VERSION_REPLAY, OBD_CONNECT_MDS_MDS, ptlrpc_replay_async_args::praa_old_state, ptlrpc_replay_async_args::praa_old_status, PTL_RPC_MSG_ERR, ptlrpc_client_replied(), ptlrpc_client_wake_req(), ptlrpc_connect_import(), ptlrpc_free_request(), ptlrpc_import_recovery_state_machine(), RETURN, ptlrpc_request::rq_err, ptlrpc_request::rq_import, ptlrpc_request::rq_list, ptlrpc_request::rq_lock, ptlrpc_request::rq_replay_list, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_status, and ptlrpc_request::rq_transno.
Referenced by ptlrpc_replay_req().
static struct ptlrpc_request* ptlrpc_request_alloc_internal (struct obd_import * imp, struct ptlrpc_request_pool * pool, const struct req_format * format) [static, read]
Helper function for creating a request.
Calls __ptlrpc_request_alloc to allocate new request sturcture and inits buffer structures according to capsule template format. Returns allocated request structure pointer or NULL on error.
Definition at line 833 of file client.c.
References __ptlrpc_request_alloc(), RCL_CLIENT, req_capsule_init(), req_capsule_set(), and ptlrpc_request::rq_pill.
Referenced by ptlrpc_request_alloc(), and ptlrpc_request_alloc_pool().
struct ptlrpc_request* ptlrpc_request_cache_alloc (gfp_t flags) [read]
Definition at line 492 of file client.c.
References OBD_SLAB_ALLOC_PTR_GFP, and request_cache.
Referenced by __ptlrpc_request_alloc(), ptlrpc_add_rqs_to_pool(), ptlrpc_at_send_early_reply(), ptlrpcd_alloc_work(), request_in_callback(), sptlrpc_cli_unwrap_early_reply(), and sptlrpc_import_check_ctx().
void ptlrpc_request_cache_fini (void)
Definition at line 487 of file client.c.
References request_cache.
Referenced by ptlrpc_exit(), and ptlrpc_init().
void ptlrpc_request_cache_free (struct ptlrpc_request * req)
Definition at line 500 of file client.c.
References OBD_SLAB_FREE_PTR, and request_cache.
Referenced by __ptlrpc_free_req(), ptlrpc_add_rqs_to_pool(), ptlrpc_at_send_early_reply(), ptlrpc_free_rq_pool(), ptlrpc_request_free(), ptlrpc_server_free_request(), sptlrpc_cli_finish_early_reply(), sptlrpc_cli_unwrap_early_reply(), and sptlrpc_import_check_ctx().
int ptlrpc_request_cache_init (void)
Definition at line 479 of file client.c.
References request_cache.
Referenced by ptlrpc_init().
void ptlrpc_resend_req (struct ptlrpc_request * req)
Schedule previously sent request for resend.
For bulk requests we assign new xid (to avoid problems with lost replies and therefore several transfers landing into same buffer from different sending attempts).
Definition at line 2717 of file client.c.
References D_HA, DEBUG_REQ, lustre_msg_set_handle(), ptlrpc_client_replied(), ptlrpc_request::rq_lock, and ptlrpc_request::rq_reqmsg.
Referenced by ptlrpc_resend().
static void ptlrpc_save_versions (struct ptlrpc_request * req) [static]
save pre-versions of objects into request for replay.
Versions are obtained from server reply. used for VBR.
Definition at line 1254 of file client.c.
References __u64, CDEBUG, D_INFO, ENTRY, EXIT, LASSERT, LPX64, lustre_msg, lustre_msg_get_flags(), lustre_msg_get_versions(), lustre_msg_set_versions(), MSG_REPLAY, ptlrpc_request::rq_repmsg, and ptlrpc_request::rq_reqmsg.
Referenced by after_reply().
static int ptlrpc_send_new_req (struct ptlrpc_request * req) [static]
Helper function to send request req over the network for the first time Also adjusts request phase.
Returns 0 on success or error code.
Definition at line 1494 of file client.c.
References __u64, ptlrpc_connection::c_peer, CDEBUG, cfs_time_current_sec(), current_comm, current_pid, D_HA, D_RPCTRACE, DEBUG_REQ, ENTRY, get_free_pages_in_pool(), obd_import::imp_connection, obd_import::imp_delayed_list, obd_import::imp_generation, obd_import::imp_inflight, obd_import::imp_lock, obd_import::imp_obd, obd_import::imp_sending_list, obd_import::imp_state, LASSERT, libcfs_nid2str(), list_add_tail(), list_del_init(), list_empty(), LPU64, lustre_msg_get_opc(), lustre_msg_get_status(), lustre_msg_set_last_xid(), lustre_msg_set_status(), lnet_process_id_t::nid, obd_device::obd_uuid, pool_is_at_full_capacity(), ptl_send_rpc(), ptlrpc_import_delay_req(), ptlrpc_import_state_name(), ptlrpc_known_replied_xid(), ptlrpc_req_is_connect(), ptlrpc_req_is_disconnect(), ptlrpc_rqphase_move(), RETURN, ptlrpc_request::rq_err, ptlrpc_request::rq_generation_set, ptlrpc_request::rq_import, ptlrpc_request::rq_list, ptlrpc_request::rq_lock, ptlrpc_request::rq_net_err, ptlrpc_request::rq_phase, RQ_PHASE_INTERPRET, RQ_PHASE_NEW, RQ_PHASE_RPC, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_sent, ptlrpc_request::rq_status, ptlrpc_request::rq_wait_ctx, ptlrpc_request::rq_waiting, ptlrpc_request::rq_xid, sptlrpc_req_refresh_ctx(), and obd_uuid::uuid.
Referenced by ptlrpc_check_set(), ptlrpc_set_add_req(), and ptlrpc_set_wait().
void ptlrpc_set_add_new_req (struct ptlrpcd_ctl * pc, struct ptlrpc_request * req)
Add a request to a request with dedicated server thread and wake the thread to make any necessary processing.
Currently only used for ptlrpcd.
Definition at line 1079 of file client.c.
References cfs_time_current(), LASSERT, LIOD_STOP, list_add_tail(), ptlrpcd_ctl::pc_flags, ptlrpcd_ctl::pc_npartners, ptlrpcd_ctl::pc_partners, ptlrpcd_ctl::pc_set, and ptlrpc_request_set::set_waitq.
Referenced by ptlrpcd_add_req().
void ptlrpc_set_bulk_mbits (struct ptlrpc_request * req)
If request has a new allocated XID (new request or EINPROGRESS resend), use this XID as matchbits of bulk, otherwise allocate a new matchbits for request to ensure previous bulk fails and avoid problems with lost replies and therefore several transfers landing into the same buffer from different sending attempts.
Definition at line 3196 of file client.c.
References __u64, ptlrpc_bulk_desc::bd_import, ptlrpc_bulk_desc::bd_iov_count, CDEBUG, D_HA, obd_import::imp_connect_data, LASSERT, LNET_MAX_IOV, LPU64, OBD_CONNECT_BULK_MBITS, obd_connect_data::ocd_connect_flags, ptlrpc_next_xid(), ptlrpc_request::rq_mbits, ptlrpc_request::rq_resend, and ptlrpc_request::rq_xid.
Referenced by ptl_send_rpc().
int ptlrpc_set_next_timeout (struct ptlrpc_request_set * set)
Get the smallest timeout in the set; this does NOT set a timeout.
Definition at line 2207 of file client.c.
References cfs_time_current_sec(), ENTRY, list_entry, list_for_each, now(), RETURN, ptlrpc_request::rq_phase, RQ_PHASE_BULK, RQ_PHASE_NEW, RQ_PHASE_RPC, ptlrpc_request::rq_resend, ptlrpc_request::rq_sent, rq_set_chain, ptlrpc_request::rq_timedout, ptlrpc_request::rq_timeout, ptlrpc_request::rq_wait_ctx, ptlrpc_request::rq_waiting, and timeout.
Referenced by ptlrpc_set_wait(), and ptlrpcd().
static int ptlrpc_set_producer (struct ptlrpc_request_set * set) [inline, static]
Definition at line 1612 of file client.c.
References ENTRY, LASSERT, and RETURN.
Referenced by ptlrpc_check_set(), and ptlrpc_set_wait().
static int ptlrpc_unregister_reply (struct ptlrpc_request * request, int async) [static]
Disengage the client's reply buffer from the network NB does _NOT_ unregister any client-side bulk.
IDEMPOTENT, but _not_ safe against concurrent callers. The request owner (i.e. the thread doing the I/O) must call... Returns 0 on success or 1 if unregistering cannot be made.
Definition at line 2512 of file client.c.
References cfs_time_current_sec(), cfs_time_seconds(), D_WARNING, DEBUG_REQ, l_wait_event, LASSERT, LNetMDUnlink(), LONG_UNLINK, LWI_TIMEOUT_INTERVAL, OBD_FAIL_CHECK, OBD_FAIL_PTLRPC_LONG_REPL_UNLINK, ptlrpc_client_recv_or_unlink(), ptlrpc_rqphase_move(), RETURN, ptlrpc_request::rq_next_phase, RQ_PHASE_UNREGISTERING, ptlrpc_request::rq_receiving_reply, ptlrpc_request::rq_reply_unlinked, and ptlrpc_request::rq_req_unlinked.
Referenced by ptlrpc_check_set(), and ptlrpc_expire_one_request().
static void ptlrpcd_add_work_req (struct ptlrpc_request * req) [static]
Definition at line 3270 of file client.c.
References cfs_time_current_sec(), obd_import::imp_generation, obd_timeout, ptlrpc_next_xid(), ptlrpcd_add_req(), ptlrpc_request::rq_deadline, ptlrpc_request::rq_import, ptlrpc_request::rq_next_phase, ptlrpc_request::rq_phase, RQ_PHASE_COMPLETE, RQ_PHASE_INTERPRET, ptlrpc_request::rq_sent, ptlrpc_request::rq_timeout, and ptlrpc_request::rq_xid.
Referenced by ptlrpcd_queue_work(), and work_interpreter().
static int ptlrpcd_check_work (struct ptlrpc_request * req) [static]
Definition at line 3307 of file client.c.
References req_capsule::rc_fmt, and ptlrpc_request::rq_pill.
Referenced by ptlrpc_check_set(), and work_interpreter().
static int unpack_reply (struct ptlrpc_request * req) [static]
Definition at line 397 of file client.c.
References D_ERROR, DEBUG_REQ, lustre_unpack_rep_ptlrpc_body(), MSG_PTLRPC_BODY_OFF, ptlrpc_unpack_rep_msg(), ptlrpc_request::rq_flvr, ptlrpc_request::rq_replen, sptlrpc_flavor::sf_rpc, SPTLRPC_FLVR_POLICY, and SPTLRPC_POLICY_NULL.
Referenced by after_reply(), and ptlrpc_at_recv_early_reply().
static int work_interpreter (const struct lu_env * env, struct ptlrpc_request * req, void * data, int rc) [static]
Definition at line 3285 of file client.c.
References ptlrpc_work_async_args::cb, ptlrpc_work_async_args::cbdata, LASSERT, list_del_init(), ptlrpcd_add_work_req(), ptlrpcd_check_work(), and ptlrpc_request::rq_refcount.
Referenced by ptlrpcd_alloc_work().
Variable Documentation
__u64 ptlrpc_last_xid [static]
Definition at line 3128 of file client.c.
spinlock_t ptlrpc_last_xid_lock [static]
Definition at line 3129 of file client.c.
struct kmem_cache* request_cache [static]
Definition at line 477 of file client.c.
Referenced by ptlrpc_request_cache_alloc(), ptlrpc_request_cache_fini(), ptlrpc_request_cache_free(), and ptlrpc_request_cache_init().
int worker_format [static]
Definition at line 3305 of file client.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.