Lustre: lnet/selftest/conctl.c File Reference
lnet/selftest/conctl.c File Reference
#include <libcfs/libcfs.h>
#include <lnet/lib-lnet.h>
#include <lnet/lnetst.h>
#include "console.h"
Functions
static int lst_session_new_ioctl (lstio_session_new_args_t *args)
static int lst_session_end_ioctl (lstio_session_end_args_t *args)
static int lst_session_info_ioctl (lstio_session_info_args_t *args)
static int lst_debug_ioctl (lstio_debug_args_t *args)
static int lst_group_add_ioctl (lstio_group_add_args_t *args)
static int lst_group_del_ioctl (lstio_group_del_args_t *args)
static int lst_group_update_ioctl (lstio_group_update_args_t *args)
static int lst_nodes_add_ioctl (lstio_group_nodes_args_t *args)
static int lst_group_list_ioctl (lstio_group_list_args_t *args)
static int lst_group_info_ioctl (lstio_group_info_args_t *args)
static int lst_batch_add_ioctl (lstio_batch_add_args_t *args)
static int lst_batch_run_ioctl (lstio_batch_run_args_t *args)
static int lst_batch_stop_ioctl (lstio_batch_stop_args_t *args)
static int lst_batch_query_ioctl (lstio_batch_query_args_t *args)
static int lst_batch_list_ioctl (lstio_batch_list_args_t *args)
static int lst_batch_info_ioctl (lstio_batch_info_args_t *args)
static int lst_stat_query_ioctl (lstio_stat_args_t *args)
static int lst_test_add_ioctl (lstio_test_args_t *args)
int lstcon_ioctl_entry (unsigned int cmd, struct libcfs_ioctl_hdr *hdr)
Function Documentation
static int lst_batch_add_ioctl (lstio_batch_add_args_t * args) [static]
Definition at line 445 of file conctl.c.
References console_session, LIBCFS_ALLOC, LIBCFS_FREE, LST_NAME_SIZE, lstcon_batch_add(), lstio_batch_add_args_t::lstio_bat_key, lstio_batch_add_args_t::lstio_bat_namep, lstio_batch_add_args_t::lstio_bat_nmlen, name, and lstcon_session_t::ses_key.
Referenced by lstcon_ioctl_entry().
static int lst_batch_info_ioctl (lstio_batch_info_args_t * args) [static]
Definition at line 605 of file conctl.c.
References console_session, LIBCFS_ALLOC, LIBCFS_FREE, LST_NAME_SIZE, lstcon_batch_info(), lstio_batch_info_args_t::lstio_bat_dentsp, lstio_batch_info_args_t::lstio_bat_entp, lstio_batch_info_args_t::lstio_bat_idxp, lstio_batch_info_args_t::lstio_bat_key, lstio_batch_info_args_t::lstio_bat_namep, lstio_batch_info_args_t::lstio_bat_ndentp, lstio_batch_info_args_t::lstio_bat_nmlen, lstio_batch_info_args_t::lstio_bat_server, lstio_batch_info_args_t::lstio_bat_testidx, name, and lstcon_session_t::ses_key.
Referenced by lstcon_ioctl_entry().
static int lst_batch_list_ioctl (lstio_batch_list_args_t * args) [static]
Definition at line 588 of file conctl.c.
References console_session, LST_NAME_SIZE, lstcon_batch_list(), lstio_batch_list_args_t::lstio_bat_idx, lstio_batch_list_args_t::lstio_bat_key, lstio_batch_list_args_t::lstio_bat_namep, lstio_batch_list_args_t::lstio_bat_nmlen, and lstcon_session_t::ses_key.
Referenced by lstcon_ioctl_entry().
static int lst_batch_query_ioctl (lstio_batch_query_args_t * args) [static]
Definition at line 547 of file conctl.c.
References console_session, LIBCFS_ALLOC, LIBCFS_FREE, LST_NAME_SIZE, lstcon_test_batch_query(), lstio_batch_query_args_t::lstio_bat_client, lstio_batch_query_args_t::lstio_bat_key, lstio_batch_query_args_t::lstio_bat_namep, lstio_batch_query_args_t::lstio_bat_nmlen, lstio_batch_query_args_t::lstio_bat_resultp, lstio_batch_query_args_t::lstio_bat_testidx, lstio_batch_query_args_t::lstio_bat_timeout, name, and lstcon_session_t::ses_key.
Referenced by lstcon_ioctl_entry().
static int lst_batch_run_ioctl (lstio_batch_run_args_t * args) [static]
Definition at line 478 of file conctl.c.
References console_session, LIBCFS_ALLOC, LIBCFS_FREE, LST_NAME_SIZE, lstcon_batch_run(), lstio_batch_run_args_t::lstio_bat_key, lstio_batch_run_args_t::lstio_bat_namep, lstio_batch_run_args_t::lstio_bat_nmlen, lstio_batch_run_args_t::lstio_bat_resultp, lstio_batch_run_args_t::lstio_bat_timeout, name, and lstcon_session_t::ses_key.
Referenced by lstcon_ioctl_entry().
static int lst_batch_stop_ioctl (lstio_batch_stop_args_t * args) [static]
Definition at line 512 of file conctl.c.
References console_session, LIBCFS_ALLOC, LIBCFS_FREE, LST_NAME_SIZE, lstcon_batch_stop(), lstio_batch_stop_args_t::lstio_bat_force, lstio_batch_stop_args_t::lstio_bat_key, lstio_batch_stop_args_t::lstio_bat_namep, lstio_batch_stop_args_t::lstio_bat_nmlen, lstio_batch_stop_args_t::lstio_bat_resultp, name, and lstcon_session_t::ses_key.
Referenced by lstcon_ioctl_entry().
static int lst_debug_ioctl (lstio_debug_args_t * args) [static]
Definition at line 116 of file conctl.c.
References console_session, LIBCFS_ALLOC, LIBCFS_FREE, LST_NAME_SIZE, LST_OPC_BATCHCLI, LST_OPC_BATCHSRV, LST_OPC_GROUP, LST_OPC_NODES, LST_OPC_SESSION, lstcon_batch_debug(), lstcon_group_debug(), lstcon_nodes_debug(), lstcon_session_debug(), lstio_debug_args_t::lstio_dbg_count, lstio_debug_args_t::lstio_dbg_idsp, lstio_debug_args_t::lstio_dbg_key, lstio_debug_args_t::lstio_dbg_namep, lstio_debug_args_t::lstio_dbg_nmlen, lstio_debug_args_t::lstio_dbg_resultp, lstio_debug_args_t::lstio_dbg_timeout, lstio_debug_args_t::lstio_dbg_type, name, and lstcon_session_t::ses_key.
Referenced by lstcon_ioctl_entry().
static int lst_group_add_ioctl (lstio_group_add_args_t * args) [static]
Definition at line 197 of file conctl.c.
References console_session, LIBCFS_ALLOC, LIBCFS_FREE, LST_NAME_SIZE, lstcon_group_add(), lstio_group_add_args_t::lstio_grp_key, lstio_group_add_args_t::lstio_grp_namep, lstio_group_add_args_t::lstio_grp_nmlen, name, and lstcon_session_t::ses_key.
Referenced by lstcon_ioctl_entry().
static int lst_group_del_ioctl (lstio_group_del_args_t * args) [static]
Definition at line 230 of file conctl.c.
References console_session, LIBCFS_ALLOC, LIBCFS_FREE, LST_NAME_SIZE, lstcon_group_del(), lstio_group_del_args_t::lstio_grp_key, lstio_group_del_args_t::lstio_grp_namep, lstio_group_del_args_t::lstio_grp_nmlen, name, and lstcon_session_t::ses_key.
Referenced by lstcon_ioctl_entry().
static int lst_group_info_ioctl (lstio_group_info_args_t * args) [static]
Definition at line 382 of file conctl.c.
References console_session, LIBCFS_ALLOC, LIBCFS_FREE, LST_NAME_SIZE, lstcon_group_info(), lstio_group_info_args_t::lstio_grp_dentsp, lstio_group_info_args_t::lstio_grp_entp, lstio_group_info_args_t::lstio_grp_idxp, lstio_group_info_args_t::lstio_grp_key, lstio_group_info_args_t::lstio_grp_namep, lstio_group_info_args_t::lstio_grp_ndentp, lstio_group_info_args_t::lstio_grp_nmlen, name, and lstcon_session_t::ses_key.
Referenced by lstcon_ioctl_entry().
static int lst_group_list_ioctl (lstio_group_list_args_t * args) [static]
Definition at line 365 of file conctl.c.
References console_session, LST_NAME_SIZE, lstcon_group_list(), lstio_group_list_args_t::lstio_grp_idx, lstio_group_list_args_t::lstio_grp_key, lstio_group_list_args_t::lstio_grp_namep, lstio_group_list_args_t::lstio_grp_nmlen, and lstcon_session_t::ses_key.
Referenced by lstcon_ioctl_entry().
static int lst_group_update_ioctl (lstio_group_update_args_t * args) [static]
Definition at line 263 of file conctl.c.
References console_session, LIBCFS_ALLOC, LIBCFS_FREE, LST_GROUP_CLEAN, LST_GROUP_REFRESH, LST_GROUP_RMND, LST_NAME_SIZE, lstcon_group_clean(), lstcon_group_refresh(), lstcon_nodes_remove(), lstio_group_update_args_t::lstio_grp_args, lstio_group_update_args_t::lstio_grp_count, lstio_group_update_args_t::lstio_grp_idsp, lstio_group_update_args_t::lstio_grp_key, lstio_group_update_args_t::lstio_grp_namep, lstio_group_update_args_t::lstio_grp_nmlen, lstio_group_update_args_t::lstio_grp_opc, lstio_group_update_args_t::lstio_grp_resultp, name, and lstcon_session_t::ses_key.
Referenced by lstcon_ioctl_entry().
static int lst_nodes_add_ioctl (lstio_group_nodes_args_t * args) [static]
Definition at line 320 of file conctl.c.
References console_session, LIBCFS_ALLOC, LIBCFS_FREE, LST_NAME_SIZE, lstcon_nodes_add(), lstio_group_nodes_args_t::lstio_grp_count, lstio_group_nodes_args_t::lstio_grp_featp, lstio_group_nodes_args_t::lstio_grp_idsp, lstio_group_nodes_args_t::lstio_grp_key, lstio_group_nodes_args_t::lstio_grp_namep, lstio_group_nodes_args_t::lstio_grp_nmlen, lstio_group_nodes_args_t::lstio_grp_resultp, name, and lstcon_session_t::ses_key.
Referenced by lstcon_ioctl_entry().
static int lst_session_end_ioctl (lstio_session_end_args_t * args) [static]
Definition at line 85 of file conctl.c.
References console_session, lstcon_session_end(), lstio_session_end_args_t::lstio_ses_key, and lstcon_session_t::ses_key.
Referenced by lstcon_ioctl_entry().
static int lst_session_info_ioctl (lstio_session_info_args_t * args) [static]
Definition at line 94 of file conctl.c.
References LST_NAME_SIZE, lstcon_session_info(), lstio_session_info_args_t::lstio_ses_featp, lstio_session_info_args_t::lstio_ses_idp, lstio_session_info_args_t::lstio_ses_keyp, lstio_session_info_args_t::lstio_ses_namep, lstio_session_info_args_t::lstio_ses_ndinfo, and lstio_session_info_args_t::lstio_ses_nmlen.
Referenced by lstcon_ioctl_entry().
static int lst_session_new_ioctl (lstio_session_new_args_t * args) [static]
Definition at line 49 of file conctl.c.
References LIBCFS_ALLOC, LIBCFS_FREE, LST_NAME_SIZE, lstcon_session_new(), lstio_session_new_args_t::lstio_ses_feats, lstio_session_new_args_t::lstio_ses_force, lstio_session_new_args_t::lstio_ses_idp, lstio_session_new_args_t::lstio_ses_key, lstio_session_new_args_t::lstio_ses_namep, lstio_session_new_args_t::lstio_ses_nmlen, lstio_session_new_args_t::lstio_ses_timeout, and name.
Referenced by lstcon_ioctl_entry().
static int lst_stat_query_ioctl (lstio_stat_args_t * args) [static]
Definition at line 670 of file conctl.c.
References console_session, LIBCFS_ALLOC, LIBCFS_FREE, LST_NAME_SIZE, lstcon_group_stat(), lstcon_nodes_stat(), lstio_stat_args_t::lstio_sta_count, lstio_stat_args_t::lstio_sta_idsp, lstio_stat_args_t::lstio_sta_key, lstio_stat_args_t::lstio_sta_namep, lstio_stat_args_t::lstio_sta_nmlen, lstio_stat_args_t::lstio_sta_resultp, lstio_stat_args_t::lstio_sta_timeout, name, and lstcon_session_t::ses_key.
Referenced by lstcon_ioctl_entry().
static int lst_test_add_ioctl (lstio_test_args_t * args) [static]
Definition at line 716 of file conctl.c.
References LIBCFS_ALLOC, LIBCFS_FREE, LST_NAME_SIZE, lstcon_test_add(), lstio_test_args_t::lstio_tes_bat_name, lstio_test_args_t::lstio_tes_bat_nmlen, lstio_test_args_t::lstio_tes_concur, lstio_test_args_t::lstio_tes_dgrp_name, lstio_test_args_t::lstio_tes_dgrp_nmlen, lstio_test_args_t::lstio_tes_dist, lstio_test_args_t::lstio_tes_loop, lstio_test_args_t::lstio_tes_param, lstio_test_args_t::lstio_tes_param_len, lstio_test_args_t::lstio_tes_resultp, lstio_test_args_t::lstio_tes_retp, lstio_test_args_t::lstio_tes_sgrp_name, lstio_test_args_t::lstio_tes_sgrp_nmlen, lstio_test_args_t::lstio_tes_span, lstio_test_args_t::lstio_tes_type, and ret.
Referenced by lstcon_ioctl_entry().
int lstcon_ioctl_entry (unsigned int cmd, struct libcfs_ioctl_hdr * hdr)
Definition at line 812 of file conctl.c.
References buf, CDEBUG, cfs_time_current_sec(), console_session, D_NET, libcfs_ioctl_data::ioc_hdr, IOC_LIBCFS_LNETST, libcfs_ioctl_data::ioc_pbuf1, libcfs_ioctl_data::ioc_pbuf2, libcfs_ioctl_data::ioc_plen1, libcfs_ioctl_data::ioc_u32, LIBCFS_ALLOC, LIBCFS_FREE, lst_batch_add_ioctl(), lst_batch_info_ioctl(), lst_batch_list_ioctl(), lst_batch_query_ioctl(), lst_batch_run_ioctl(), lst_batch_stop_ioctl(), lst_debug_ioctl(), lst_group_add_ioctl(), lst_group_del_ioctl(), lst_group_info_ioctl(), lst_group_list_ioctl(), lst_group_update_ioctl(), lst_nodes_add_ioctl(), lst_session_end_ioctl(), lst_session_info_ioctl(), lst_session_new_ioctl(), LST_SESSION_NONE, lst_stat_query_ioctl(), lst_test_add_ioctl(), lstcon_session_end(), LSTIO_BATCH_ADD, LSTIO_BATCH_INFO, LSTIO_BATCH_LIST, LSTIO_BATCH_QUERY, LSTIO_BATCH_START, LSTIO_BATCH_STOP, LSTIO_DEBUG, LSTIO_GROUP_ADD, LSTIO_GROUP_DEL, LSTIO_GROUP_INFO, LSTIO_GROUP_LIST, LSTIO_GROUP_UPDATE, LSTIO_NODES_ADD, LSTIO_SESSION_END, LSTIO_SESSION_INFO, LSTIO_SESSION_NEW, LSTIO_STAT_QUERY, LSTIO_TEST_ADD, lstcon_session_t::ses_expired, lstcon_session_t::ses_laststamp, lstcon_session_t::ses_mutex, lstcon_session_t::ses_shutdown, lstcon_session_t::ses_state, and lstcon_session_t::ses_trans_stat.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.