Lustre: lnet/lnet/config.c File Reference
lnet/lnet/config.c File Reference
#include <lnet/lib-lnet.h>
Data Structures
struct lnet_text_buf
Defines
#define DEBUG_SUBSYSTEM S_LNET
#define LNET_MAX_TEXTBUF_NOB (64<<10)
#define LNET_SINGLE_TEXTBUF_NOB (4<<10)
#define LNET_PRIORITY_SEPARATOR (':')
Functions
static void lnet_syntax (char *name, char *str, int offset, int width)
static int lnet_issep (char c)
int lnet_net_unique (__u32 net, struct list_head *nilist)
void lnet_ni_free (struct lnet_ni *ni)
lnet_ni_t * lnet_ni_alloc (__u32 net, struct cfs_expr_list *el, struct list_head *nilist)
int lnet_parse_networks (struct list_head *nilist, char *networks)
static struct lnet_text_buf * lnet_new_text_buf (int str_len)
static void lnet_free_text_buf (struct lnet_text_buf *ltb)
static void lnet_free_text_bufs (struct list_head *tbs)
void lnet_print_text_bufs (struct list_head *tbs)
static int lnet_str2tbs_sep (struct list_head *tbs, char *str)
static int lnet_expand1tb (struct list_head *list, char *str, char *sep1, char *sep2, char *item, int itemlen)
static int lnet_str2tbs_expand (struct list_head *tbs, char *str)
static int lnet_parse_hops (char *str, unsigned int *hops)
static int lnet_parse_priority (char *str, unsigned int *priority, char **token)
static int lnet_parse_route (char *str, int *im_a_router)
static int lnet_parse_route_tbs (struct list_head *tbs, int *im_a_router)
int lnet_parse_routes (char *routes, int *im_a_router)
static int lnet_match_network_token (char *token, int len, __u32 *ipaddrs, int nip)
static int lnet_match_network_tokens (char *net_entry, __u32 *ipaddrs, int nip)
static __u32 lnet_netspec2net (char *netspec)
static int lnet_splitnets (char *source, struct list_head *nets)
static int lnet_match_networks (char **networksp, char *ip2nets, __u32 *ipaddrs, int nip)
static void lnet_ipaddr_free_enumeration (__u32 *ipaddrs, int nip)
static int lnet_ipaddr_enumerate (__u32 **ipaddrsp)
int lnet_parse_ip2nets (char **networksp, char *ip2nets)
Variables
static int lnet_tbnob = 0
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 37 of file config.c.
#define LNET_MAX_TEXTBUF_NOB (64<<10)
Definition at line 48 of file config.c.
Referenced by lnet_new_text_buf().
#define LNET_PRIORITY_SEPARATOR (':')
Definition at line 632 of file config.c.
Referenced by lnet_parse_priority().
#define LNET_SINGLE_TEXTBUF_NOB (4<<10)
Definition at line 49 of file config.c.
Referenced by lnet_match_network_tokens(), lnet_match_networks(), lnet_new_text_buf(), lnet_parse_networks(), lnet_parse_route(), and lnet_syntax().
Function Documentation
static int lnet_expand1tb (struct list_head * list, char * str, char * sep1, char * sep2, char * item, int itemlen) [static]
Definition at line 517 of file config.c.
References LASSERT, list_add_tail(), lnet_new_text_buf(), lnet_text_buf::ltb_list, and lnet_text_buf::ltb_text.
Referenced by lnet_str2tbs_expand().
static void lnet_free_text_buf (struct lnet_text_buf * ltb) [static]
Definition at line 424 of file config.c.
References LIBCFS_FREE, lnet_tbnob, and lnet_text_buf::ltb_size.
Referenced by lnet_free_text_bufs(), lnet_match_networks(), lnet_parse_route(), and lnet_parse_route_tbs().
static void lnet_free_text_bufs (struct list_head * tbs) [static]
Definition at line 431 of file config.c.
References list_del(), list_empty(), list_entry, lnet_free_text_buf(), lnet_text_buf::ltb_list, and list_head::next.
Referenced by lnet_match_networks(), lnet_parse_route(), lnet_parse_route_tbs(), lnet_str2tbs_expand(), and lnet_str2tbs_sep().
static int lnet_ipaddr_enumerate (__u32 ** ipaddrsp) [static]
Definition at line 1153 of file config.c.
References CERROR, CWARN, LIBCFS_ALLOC, lnet_ipaddr_free_enumeration(), lnet_ipif_enumerate(), lnet_ipif_free_enumeration(), and lnet_ipif_query().
Referenced by lnet_parse_ip2nets().
static void lnet_ipaddr_free_enumeration (__u32 * ipaddrs, int nip) [static]
Definition at line 1147 of file config.c.
References LIBCFS_FREE.
Referenced by lnet_ipaddr_enumerate(), and lnet_parse_ip2nets().
static int lnet_issep (char c) [static]
Definition at line 69 of file config.c.
Referenced by lnet_str2tbs_sep().
static int lnet_match_network_token (char * token, int len, __u32 * ipaddrs, int nip) [static]
Definition at line 852 of file config.c.
References cfs_expr_list_free_list(), cfs_ip_addr_match(), cfs_ip_addr_parse(), and LIST_HEAD_INIT.
Referenced by lnet_match_network_tokens().
static int lnet_match_network_tokens (char * net_entry, __u32 * ipaddrs, int nip) [static]
Definition at line 871 of file config.c.
References LASSERT, lnet_match_network_token(), LNET_SINGLE_TEXTBUF_NOB, and lnet_syntax().
Referenced by lnet_match_networks().
static int lnet_match_networks (char ** networksp, char * ip2nets, __u32 * ipaddrs, int nip) [static]
Definition at line 1027 of file config.c.
References CERROR, INIT_LIST_HEAD, LASSERT, list_add(), list_add_tail(), list_del(), list_empty(), list_entry, list_for_each, list_for_each_safe, lnet_free_text_buf(), lnet_free_text_bufs(), lnet_match_network_tokens(), lnet_netspec2net(), LNET_NID_ANY, LNET_NIDNET(), LNET_SINGLE_TEXTBUF_NOB, lnet_splitnets(), lnet_str2tbs_sep(), lnet_tbnob, lnet_text_buf::ltb_list, lnet_text_buf::ltb_text, networks, list_head::next, and t2.
Referenced by lnet_parse_ip2nets().
int lnet_net_unique (__u32 net, struct list_head * nilist)
Definition at line 82 of file config.c.
References list_entry, list_for_each, LNET_NIDNET(), and lnet_ni::ni_nid.
Referenced by lnet_ni_alloc(), and lnet_startup_lndni().
static __u32 lnet_netspec2net (char * netspec) [static]
Definition at line 928 of file config.c.
References libcfs_str2net().
Referenced by lnet_match_networks(), and lnet_splitnets().
static struct lnet_text_buf* lnet_new_text_buf (int str_len) [static, read]
Definition at line 395 of file config.c.
References CERROR, LIBCFS_ALLOC, LNET_MAX_TEXTBUF_NOB, LNET_SINGLE_TEXTBUF_NOB, lnet_tbnob, lnet_text_buf::ltb_size, lnet_text_buf::ltb_text, and offsetof.
Referenced by lnet_expand1tb(), lnet_parse_route(), lnet_splitnets(), and lnet_str2tbs_sep().
lnet_ni_t* lnet_ni_alloc (__u32 net, struct cfs_expr_list * el, struct list_head * nilist)
Definition at line 123 of file config.c.
References CERROR, cfs_expr_list_values(), cfs_percpt_alloc(), cfs_percpt_for_each, cfs_time_current_sec(), INIT_LIST_HEAD, LASSERT, LCONSOLE_ERROR_MSG, LIBCFS_ALLOC, LIBCFS_FREE, libcfs_net2str(), list_add_tail(), LNET_CPT_NUMBER, lnet_cpt_table, LNET_MKNID(), lnet_net_unique(), lnet_ni_free(), lnet_ni::ni_cptlist, lnet_ni::ni_cpts, lnet_ni::ni_last_alive, lnet_ni::ni_list, lnet_ni::ni_lock, lnet_ni::ni_ncpts, lnet_ni::ni_nid, lnet_ni::ni_refs, lnet_ni::ni_tx_queues, and lnet_tx_queue::tq_delayed.
Referenced by lnet_parse_networks(), and LNetNIInit().
void lnet_ni_free (struct lnet_ni * ni)
Definition at line 98 of file config.c.
References cfs_expr_list_values_free(), cfs_percpt_free(), LIBCFS_FREE, LNET_MAX_INTERFACES, lnet_ni::ni_cpts, lnet_ni::ni_interfaces, lnet_ni::ni_lnd_tunables, lnet_ni::ni_ncpts, lnet_ni::ni_refs, and lnet_ni::ni_tx_queues.
Referenced by lnet_clear_zombies_nis_locked(), lnet_dyn_add_ni(), lnet_ni_alloc(), lnet_parse_networks(), lnet_startup_lndni(), and LNetNIInit().
static int lnet_parse_hops (char * str, unsigned int * hops) [static]
Definition at line 622 of file config.c.
Referenced by lnet_parse_route().
int lnet_parse_ip2nets (char ** networksp, char * ip2nets)
Definition at line 1219 of file config.c.
References LCONSOLE_ERROR_MSG, lnet_ipaddr_enumerate(), lnet_ipaddr_free_enumeration(), and lnet_match_networks().
Referenced by lnet_get_networks().
int lnet_parse_networks (struct list_head * nilist, char * networks)
Definition at line 189 of file config.c.
References CERROR, cfs_expr_list_free(), cfs_expr_list_parse(), cfs_trimwhite(), LCONSOLE_ERROR_MSG, LIBCFS_ALLOC, LIBCFS_FREE, libcfs_net2str(), libcfs_str2net(), list_del(), list_empty(), list_entry, list_for_each, LNET_CPT_NUMBER, LNET_MAX_INTERFACES, LNET_NETTYP(), lnet_ni_alloc(), lnet_ni_free(), LNET_NID_ANY, LNET_NIDNET(), LNET_SINGLE_TEXTBUF_NOB, lnet_syntax(), LOLND, list_head::next, lnet_ni::ni_interfaces, and lnet_ni::ni_list.
Referenced by lnet_dyn_add_ni(), and LNetNIInit().
static int lnet_parse_priority (char * str, unsigned int * priority, char ** token) [static]
Definition at line 635 of file config.c.
References CDEBUG, D_NET, and LNET_PRIORITY_SEPARATOR.
Referenced by lnet_parse_route().
static int lnet_parse_route (char * str, int * im_a_router) [static]
Definition at line 665 of file config.c.
References CERROR, cmd, INIT_LIST_HEAD, LASSERT, libcfs_net2str(), libcfs_nid2str(), libcfs_str2net(), libcfs_str2nid(), list_add_tail(), list_del(), list_empty(), list_entry, list_for_each, lnet_add_route(), lnet_free_text_buf(), lnet_free_text_bufs(), lnet_islocalnid(), LNET_NETTYP(), lnet_new_text_buf(), LNET_NID_ANY, LNET_NIDNET(), lnet_parse_hops(), lnet_parse_priority(), LNET_SINGLE_TEXTBUF_NOB, lnet_str2tbs_expand(), lnet_syntax(), LNET_UNDEFINED_HOPS, LOLND, lnet_text_buf::ltb_list, lnet_text_buf::ltb_text, and list_head::next.
Referenced by lnet_parse_route_tbs().
static int lnet_parse_route_tbs (struct list_head * tbs, int * im_a_router) [static]
Definition at line 811 of file config.c.
References list_del(), list_empty(), list_entry, lnet_free_text_buf(), lnet_free_text_bufs(), lnet_parse_route(), lnet_text_buf::ltb_list, lnet_text_buf::ltb_text, and list_head::next.
Referenced by lnet_parse_routes().
int lnet_parse_routes (char * routes, int * im_a_router)
Definition at line 831 of file config.c.
References CERROR, INIT_LIST_HEAD, LASSERT, lnet_parse_route_tbs(), lnet_str2tbs_sep(), and lnet_tbnob.
Referenced by LNetNIInit().
void lnet_print_text_bufs (struct list_head * tbs)
Definition at line 444 of file config.c.
References CDEBUG, D_WARNING, list_entry, list_for_each, lnet_tbnob, lnet_text_buf::ltb_list, and lnet_text_buf::ltb_text.
static int lnet_splitnets (char * source, struct list_head * nets) [static]
Definition at line 945 of file config.c.
References LASSERT, list_add_tail(), list_empty(), list_entry, list_for_each, lnet_netspec2net(), lnet_new_text_buf(), LNET_NID_ANY, LNET_NIDNET(), lnet_syntax(), lnet_text_buf::ltb_list, lnet_text_buf::ltb_text, list_head::next, and list_head::prev.
Referenced by lnet_match_networks().
static int lnet_str2tbs_expand (struct list_head * tbs, char * str) [static]
Definition at line 542 of file config.c.
References INIT_LIST_HEAD, list_splice(), lnet_expand1tb(), lnet_free_text_bufs(), and list_head::prev.
Referenced by lnet_parse_route().
static int lnet_str2tbs_sep (struct list_head * tbs, char * str) [static]
Definition at line 459 of file config.c.
References INIT_LIST_HEAD, list_add_tail(), list_splice(), lnet_free_text_bufs(), lnet_issep(), lnet_new_text_buf(), lnet_text_buf::ltb_list, lnet_text_buf::ltb_text, and list_head::prev.
Referenced by lnet_match_networks(), and lnet_parse_routes().
static void lnet_syntax (char * name, char * str, int offset, int width) [static]
Definition at line 52 of file config.c.
References LCONSOLE_ERROR_MSG, and LNET_SINGLE_TEXTBUF_NOB.
Referenced by lnet_match_network_tokens(), lnet_parse_networks(), lnet_parse_route(), and lnet_splitnets().
Variable Documentation
int lnet_tbnob = 0 [static]
Definition at line 47 of file config.c.
Referenced by lnet_free_text_buf(), lnet_match_networks(), lnet_new_text_buf(), lnet_parse_routes(), and lnet_print_text_bufs().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.