Lustre: lustre/ptlrpc/connection.c File Reference
lustre/ptlrpc/connection.c File Reference
#include <obd_support.h>
#include <obd_class.h>
#include <lustre_net.h>
#include "ptlrpc_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_RPC
Functions
struct ptlrpc_connection * ptlrpc_connection_get (lnet_process_id_t peer, lnet_nid_t self, struct obd_uuid *uuid)
int ptlrpc_connection_put (struct ptlrpc_connection *conn)
struct ptlrpc_connection * ptlrpc_connection_addref (struct ptlrpc_connection *conn)
int ptlrpc_connection_init (void)
void ptlrpc_connection_fini (void)
static unsigned conn_hashfn (struct cfs_hash *hs, const void *key, unsigned mask)
static int conn_keycmp (const void *key, struct hlist_node *hnode)
static void * conn_key (struct hlist_node *hnode)
static void * conn_object (struct hlist_node *hnode)
static void conn_get (struct cfs_hash *hs, struct hlist_node *hnode)
static void conn_put_locked (struct cfs_hash *hs, struct hlist_node *hnode)
static void conn_exit (struct cfs_hash *hs, struct hlist_node *hnode)
Variables
static struct cfs_hash * conn_hash
static struct cfs_hash_ops conn_hash_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_RPC
Definition at line 37 of file connection.c.
Function Documentation
static void conn_exit (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 219 of file connection.c.
References ptlrpc_connection::c_hash, ptlrpc_connection::c_refcount, hlist_entry, LASSERTF, and OBD_FREE_PTR.
static void conn_get (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 201 of file connection.c.
References ptlrpc_connection::c_hash, ptlrpc_connection::c_refcount, and hlist_entry.
static unsigned conn_hashfn (struct cfs_hash * hs, const void * key, unsigned mask) [static]
Definition at line 167 of file connection.c.
References cfs_hash_djb2_hash().
static void* conn_key (struct hlist_node * hnode) [static]
Definition at line 187 of file connection.c.
References ptlrpc_connection::c_hash, ptlrpc_connection::c_peer, and hlist_entry.
Referenced by conn_keycmp().
static int conn_keycmp (const void * key, struct hlist_node * hnode) [static]
Definition at line 173 of file connection.c.
References ptlrpc_connection::c_hash, ptlrpc_connection::c_peer, conn_key(), hlist_entry, LASSERT, lnet_process_id_t::nid, and lnet_process_id_t::pid.
static void* conn_object (struct hlist_node * hnode) [static]
Definition at line 195 of file connection.c.
References ptlrpc_connection::c_hash, and hlist_entry.
static void conn_put_locked (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 210 of file connection.c.
References ptlrpc_connection::c_hash, ptlrpc_connection::c_refcount, and hlist_entry.
Variable Documentation
struct cfs_hash* conn_hash [static]
Definition at line 44 of file connection.c.
static struct cfs_hash_ops conn_hash_ops [static, read]
Initial value:
 {
        .hs_hash        = conn_hashfn,
        .hs_keycmp      = conn_keycmp,
        .hs_key         = conn_key,
        .hs_object      = conn_object,
        .hs_get         = conn_get,
        .hs_put_locked  = conn_put_locked,
        .hs_exit        = conn_exit,
}
Definition at line 45 of file connection.c.
Referenced by ptlrpc_connection_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.