Lustre: lnet/selftest/conrpc.c File Reference
lnet/selftest/conrpc.c File Reference
#include <libcfs/libcfs.h>
#include <lnet/lib-lnet.h>
#include "timer.h"
#include "conrpc.h"
#include "console.h"
Functions
void lstcon_rpc_stat_reply (lstcon_rpc_trans_t *, srpc_msg_t *, lstcon_node_t *, lstcon_trans_stat_t *)
static void lstcon_rpc_done (srpc_client_rpc_t *rpc)
static int lstcon_rpc_init (lstcon_node_t *nd, int service, unsigned feats, int bulk_npg, int bulk_len, int embedded, lstcon_rpc_t *crpc)
static int lstcon_rpc_prep (lstcon_node_t *nd, int service, unsigned feats, int bulk_npg, int bulk_len, lstcon_rpc_t **crpcpp)
void lstcon_rpc_put (lstcon_rpc_t *crpc)
static void lstcon_rpc_post (lstcon_rpc_t *crpc)
static char * lstcon_rpc_trans_name (int transop)
int lstcon_rpc_trans_prep (struct list_head *translist, int transop, lstcon_rpc_trans_t **transpp)
void lstcon_rpc_trans_addreq (lstcon_rpc_trans_t *trans, lstcon_rpc_t *crpc)
void lstcon_rpc_trans_abort (lstcon_rpc_trans_t *trans, int error)
static int lstcon_rpc_trans_check (lstcon_rpc_trans_t *trans)
int lstcon_rpc_trans_postwait (lstcon_rpc_trans_t *trans, int timeout)
static int lstcon_rpc_get_reply (lstcon_rpc_t *crpc, srpc_msg_t **msgpp)
void lstcon_rpc_trans_stat (lstcon_rpc_trans_t *trans, lstcon_trans_stat_t *stat)
int lstcon_rpc_trans_interpreter (lstcon_rpc_trans_t *trans, struct list_head __user *head_up, lstcon_rpc_readent_func_t readent)
void lstcon_rpc_trans_destroy (lstcon_rpc_trans_t *trans)
int lstcon_sesrpc_prep (lstcon_node_t *nd, int transop, unsigned feats, lstcon_rpc_t **crpc)
int lstcon_dbgrpc_prep (lstcon_node_t *nd, unsigned feats, lstcon_rpc_t **crpc)
int lstcon_batrpc_prep (lstcon_node_t *nd, int transop, unsigned feats, lstcon_tsb_hdr_t *tsb, lstcon_rpc_t **crpc)
int lstcon_statrpc_prep (lstcon_node_t *nd, unsigned feats, lstcon_rpc_t **crpc)
static lnet_process_id_packed_t * lstcon_next_id (int idx, int nkiov, lnet_kiov_t *kiov)
static int lstcon_dstnodes_prep (lstcon_group_t *grp, int idx, int dist, int span, int nkiov, lnet_kiov_t *kiov)
static int lstcon_pingrpc_prep (lst_test_ping_param_t *param, srpc_test_reqst_t *req)
static int lstcon_bulkrpc_v0_prep (lst_test_bulk_param_t *param, srpc_test_reqst_t *req)
static int lstcon_bulkrpc_v1_prep (lst_test_bulk_param_t *param, srpc_test_reqst_t *req)
int lstcon_testrpc_prep (lstcon_node_t *nd, int transop, unsigned feats, lstcon_test_t *test, lstcon_rpc_t **crpc)
static int lstcon_sesnew_stat_reply (lstcon_rpc_trans_t *trans, lstcon_node_t *nd, srpc_msg_t *reply)
int lstcon_rpc_trans_ndlist (struct list_head *ndlist, struct list_head *translist, int transop, void *arg, lstcon_rpc_cond_func_t condition, lstcon_rpc_trans_t **transpp)
static void lstcon_rpc_pinger (void *arg)
int lstcon_rpc_pinger_start (void)
void lstcon_rpc_pinger_stop (void)
void lstcon_rpc_cleanup_wait (void)
int lstcon_rpc_module_init (void)
void lstcon_rpc_module_fini (void)
Function Documentation
int lstcon_batrpc_prep (lstcon_node_t * nd, int transop, unsigned feats, lstcon_tsb_hdr_t * tsb, lstcon_rpc_t ** crpc)
Definition at line 656 of file conrpc.c.
References lstcon_batch_t::bat_arg, console_session, LASSERT, LST_TRANS_TSBRUN, LST_TRANS_TSBSTOP, lstcon_rpc_prep(), lstcon_session_t::ses_id, SRPC_BATCH_OPC_QUERY, SRPC_BATCH_OPC_RUN, SRPC_BATCH_OPC_STOP, SRPC_SERVICE_BATCH, lstcon_tsb_hdr::tsb_id, and lstcon_tsb_hdr::tsb_index.
Referenced by lstcon_rpc_trans_ndlist().
static int lstcon_bulkrpc_v0_prep (lst_test_bulk_param_t * param, srpc_test_reqst_t * req) [static]
Definition at line 787 of file conrpc.c.
References lst_test_bulk_param_t::blk_flags, lst_test_bulk_param_t::blk_opc, and lst_test_bulk_param_t::blk_size.
Referenced by lstcon_testrpc_prep().
static int lstcon_bulkrpc_v1_prep (lst_test_bulk_param_t * param, srpc_test_reqst_t * req) [static]
Definition at line 800 of file conrpc.c.
References lst_test_bulk_param_t::blk_flags, lst_test_bulk_param_t::blk_opc, and lst_test_bulk_param_t::blk_size.
Referenced by lstcon_testrpc_prep().
int lstcon_dbgrpc_prep (lstcon_node_t * nd, unsigned feats, lstcon_rpc_t ** crpc)
Definition at line 638 of file conrpc.c.
References console_session, lstcon_rpc_prep(), lstcon_session_t::ses_id, and SRPC_SERVICE_DEBUG.
Referenced by lstcon_rpc_trans_ndlist().
static int lstcon_dstnodes_prep (lstcon_group_t * grp, int idx, int dist, int span, int nkiov, lnet_kiov_t * kiov) [static]
Definition at line 722 of file conrpc.c.
References end, lstcon_group_t::grp_ndl_list, lstcon_group_t::grp_nnode, LASSERT, list_for_each_entry, lstcon_next_id(), lstcon_node::nd_id, lstcon_ndlink_t::ndl_node, lnet_process_id_t::nid, lnet_process_id_t::pid, and start.
Referenced by lstcon_testrpc_prep().
static lnet_process_id_packed_t* lstcon_next_id (int idx, int nkiov, lnet_kiov_t * kiov) [static]
Definition at line 707 of file conrpc.c.
References LASSERT, and SFW_ID_PER_PAGE.
Referenced by lstcon_dstnodes_prep().
static int lstcon_pingrpc_prep (lst_test_ping_param_t * param, srpc_test_reqst_t * req) [static]
Definition at line 776 of file conrpc.c.
References lst_test_ping_param_t::png_flags, and lst_test_ping_param_t::png_size.
Referenced by lstcon_testrpc_prep().
void lstcon_rpc_cleanup_wait (void)
Definition at line 1330 of file conrpc.c.
References CDEBUG, cfs_time_seconds(), console_session, lstcon_rpc::crp_link, CWARN, D_NET, LASSERT, LIBCFS_FREE, list_add(), list_del(), list_del_init(), list_empty(), list_entry, list_for_each, lst_wait_until, lstcon_rpc_trans_name(), list_head::next, lstcon_session_t::ses_mutex, lstcon_session_t::ses_rpc_counter, lstcon_session_t::ses_rpc_freelist, lstcon_session_t::ses_rpc_lock, lstcon_session_t::ses_shutdown, lstcon_session_t::ses_trans_list, lstcon_rpc_trans::tas_opc, and lstcon_rpc_trans::tas_waitq.
Referenced by lstcon_session_end().
static void lstcon_rpc_done (srpc_client_rpc_t * rpc) [static]
Definition at line 54 of file conrpc.c.
References cfs_time_current(), lstcon_rpc::crp_finished, lstcon_rpc::crp_posted, lstcon_rpc::crp_rpc, lstcon_rpc::crp_stamp, lstcon_rpc::crp_status, lstcon_rpc::crp_trans, srpc_client_rpc::crpc_lock, srpc_client_rpc::crpc_priv, srpc_client_rpc::crpc_status, LASSERT, lstcon_rpc_put(), lstcon_rpc_trans::tas_remaining, and lstcon_rpc_trans::tas_waitq.
Referenced by lstcon_rpc_init().
static int lstcon_rpc_get_reply (lstcon_rpc_t * crpc, srpc_msg_t ** msgpp) [static]
Definition at line 388 of file conrpc.c.
References cfs_time_after(), lstcon_rpc::crp_node, lstcon_rpc::crp_rpc, lstcon_rpc::crp_stamp, lstcon_rpc::crp_status, lstcon_rpc::crp_unpacked, srpc_client_rpc::crpc_replymsg, LASSERT, LNET_NID_ANY, LST_NODE_ACTIVE, LST_NODE_BUSY, LST_NODE_UNKNOWN, lstcon_session_match(), lstcon_node::nd_stamp, lstcon_node::nd_state, and sfw_unpack_message().
Referenced by lstcon_rpc_pinger(), lstcon_rpc_trans_interpreter(), and lstcon_rpc_trans_stat().
static int lstcon_rpc_init (lstcon_node_t * nd, int service, unsigned feats, int bulk_npg, int bulk_len, int embedded, lstcon_rpc_t * crpc) [static]
Definition at line 92 of file conrpc.c.
References console_session, lstcon_rpc::crp_rpc, INIT_LIST_HEAD, lstcon_rpc_done(), lstcon_node::nd_id, lstcon_session_t::ses_rpc_counter, and sfw_create_rpc().
Referenced by lstcon_rpc_pinger(), and lstcon_rpc_prep().
void lstcon_rpc_module_fini (void)
Definition at line 1400 of file conrpc.c.
References console_session, LASSERT, list_empty(), lstcon_session_t::ses_rpc_counter, and lstcon_session_t::ses_rpc_freelist.
Referenced by lstcon_console_fini().
int lstcon_rpc_module_init (void)
Definition at line 1384 of file conrpc.c.
References console_session, INIT_LIST_HEAD, lstcon_rpc_pinger(), lstcon_session_t::ses_ping, lstcon_session_t::ses_ping_timer, lstcon_session_t::ses_rpc_counter, lstcon_session_t::ses_rpc_freelist, lstcon_session_t::ses_rpc_lock, stt_timer_t::stt_data, stt_timer_t::stt_func, and stt_timer_t::stt_list.
Referenced by lstcon_console_init().
static void lstcon_rpc_pinger (void * arg) [static]
Definition at line 1172 of file conrpc.c.
References CDEBUG, CERROR, cfs_duration_sec(), cfs_time_current(), cfs_time_current_sec(), cfs_time_sub(), console_session, lstcon_rpc::crp_finished, lstcon_rpc::crp_link, lstcon_rpc::crp_posted, lstcon_rpc::crp_rpc, lstcon_rpc::crp_trans, srpc_client_rpc::crpc_lock, srpc_client_rpc::crpc_reqstmsg, D_NET, srpc_msg::dbg_reqst, LASSERT, list_del_init(), list_empty(), list_for_each_entry, LST_NODE_ACTIVE, LST_PING_INTERVAL, LST_TRANS_SESEND, lstcon_rpc_get_reply(), lstcon_rpc_init(), lstcon_rpc_post(), lstcon_rpc_put(), lstcon_rpc_trans_addreq(), lstcon_sesrpc_prep(), srpc_msg::msg_body, lstcon_node::nd_ping, lstcon_node::nd_stamp, lstcon_node::nd_state, lstcon_node::nd_timeout, lstcon_ndlink_t::ndl_node, lstcon_session_t::ses_expired, lstcon_session_t::ses_id, lstcon_session_t::ses_laststamp, lstcon_session_t::ses_mutex, lstcon_session_t::ses_ndl_list, lstcon_session_t::ses_ping, lstcon_session_t::ses_shutdown, lstcon_session_t::ses_timeout, SRPC_SERVICE_DEBUG, stt_add_timer(), stt_timer_t::stt_expires, and lstcon_rpc_trans::tas_features.
Referenced by lstcon_rpc_module_init().
int lstcon_rpc_pinger_start (void)
Definition at line 1290 of file conrpc.c.
References CERROR, cfs_time_current_sec(), console_session, LASSERT, list_empty(), LST_PING_INTERVAL, LST_TRANS_SESPING, lstcon_rpc_trans_prep(), lstcon_session_t::ses_ping, lstcon_session_t::ses_ping_timer, lstcon_session_t::ses_rpc_counter, lstcon_session_t::ses_rpc_freelist, stt_add_timer(), and stt_timer_t::stt_expires.
Referenced by lstcon_session_new().
void lstcon_rpc_pinger_stop (void)
Definition at line 1314 of file conrpc.c.
References console_session, LASSERT, lstcon_rpc_trans_abort(), lstcon_rpc_trans_destroy(), lstcon_rpc_trans_stat(), lstcon_trans_stat(), lstcon_session_t::ses_ping, lstcon_session_t::ses_ping_timer, lstcon_session_t::ses_shutdown, and stt_del_timer().
Referenced by lstcon_session_end().
static void lstcon_rpc_post (lstcon_rpc_t * crpc) [static]
Definition at line 186 of file conrpc.c.
References lstcon_rpc::crp_posted, lstcon_rpc::crp_rpc, lstcon_rpc::crp_trans, LASSERT, sfw_post_rpc(), and lstcon_rpc_trans::tas_remaining.
Referenced by lstcon_rpc_pinger(), and lstcon_rpc_trans_postwait().
static int lstcon_rpc_prep (lstcon_node_t * nd, int service, unsigned feats, int bulk_npg, int bulk_len, lstcon_rpc_t ** crpcpp) [static]
Definition at line 117 of file conrpc.c.
References console_session, lstcon_rpc::crp_link, LIBCFS_ALLOC, LIBCFS_FREE, list_del_init(), list_empty(), list_entry, lstcon_rpc_init(), list_head::next, lstcon_session_t::ses_rpc_freelist, and lstcon_session_t::ses_rpc_lock.
Referenced by lstcon_batrpc_prep(), lstcon_dbgrpc_prep(), lstcon_sesrpc_prep(), lstcon_statrpc_prep(), and lstcon_testrpc_prep().
void lstcon_rpc_put (lstcon_rpc_t * crpc)
Definition at line 151 of file conrpc.c.
References srpc_bulk_t::bk_iovs, srpc_bulk_t::bk_niov, console_session, lstcon_rpc::crp_embedded, lstcon_rpc::crp_link, lstcon_rpc::crp_rpc, srpc_client_rpc::crpc_bulk, lnet_kiov_t::kiov_page, LASSERT, list_add(), list_empty(), lstcon_session_t::ses_rpc_counter, lstcon_session_t::ses_rpc_freelist, lstcon_session_t::ses_rpc_lock, and srpc_client_rpc_decref.
Referenced by lstcon_rpc_done(), lstcon_rpc_pinger(), lstcon_rpc_trans_destroy(), and lstcon_testrpc_prep().
void lstcon_rpc_stat_reply (lstcon_rpc_trans_t * trans, srpc_msg_t * msg, lstcon_node_t * nd, lstcon_trans_stat_t * stat)
Definition at line 967 of file conrpc.c.
References srpc_msg::bat_reply, srpc_msg::dbg_reply, LBUG, LST_TRANS_SESEND, LST_TRANS_SESNEW, LST_TRANS_SESPING, LST_TRANS_SESQRY, LST_TRANS_STATQRY, LST_TRANS_TSBCLIADD, LST_TRANS_TSBCLIQRY, LST_TRANS_TSBRUN, LST_TRANS_TSBSRVADD, LST_TRANS_TSBSRVQRY, LST_TRANS_TSBSTOP, lstcon_sesnew_stat_reply(), lstcon_sesop_stat_failure(), lstcon_sesop_stat_success(), lstcon_sesqry_stat_active(), lstcon_sesqry_stat_busy(), lstcon_sesqry_stat_unknown(), lstcon_session_match(), lstcon_statqry_stat_failure(), lstcon_statqry_stat_success(), lstcon_tsbop_stat_failure(), lstcon_tsbop_stat_success(), lstcon_tsbqry_stat_failure(), lstcon_tsbqry_stat_idle(), lstcon_tsbqry_stat_run(), srpc_msg::msg_body, srpc_msg::rmsn_reply, srpc_msg::stat_reply, lstcon_rpc_trans::tas_opc, srpc_msg::tes_reply, and lstcon_trans_stat_t::trs_fwk_errno.
Referenced by lstcon_rpc_trans_stat().
void lstcon_rpc_trans_abort (lstcon_rpc_trans_t * trans, int error)
Definition at line 286 of file conrpc.c.
References cfs_time_after(), cfs_time_current(), lstcon_rpc::crp_node, lstcon_rpc::crp_posted, lstcon_rpc::crp_rpc, lstcon_rpc::crp_stamp, lstcon_rpc::crp_status, srpc_client_rpc::crpc_lock, list_for_each_entry, LST_NODE_DOWN, lstcon_node::nd_stamp, lstcon_node::nd_state, sfw_abort_rpc(), and lstcon_rpc_trans::tas_rpcs_list.
Referenced by lstcon_rpc_pinger_stop(), and lstcon_rpc_trans_postwait().
void lstcon_rpc_trans_addreq (lstcon_rpc_trans_t * trans, lstcon_rpc_t * crpc)
Definition at line 279 of file conrpc.c.
References lstcon_rpc::crp_link, lstcon_rpc::crp_trans, list_add_tail(), and lstcon_rpc_trans::tas_rpcs_list.
Referenced by lstcon_rpc_pinger(), and lstcon_rpc_trans_ndlist().
static int lstcon_rpc_trans_check (lstcon_rpc_trans_t * trans) [static]
Definition at line 327 of file conrpc.c.
References console_session, list_empty(), lstcon_session_t::ses_shutdown, lstcon_rpc_trans::tas_olink, and lstcon_rpc_trans::tas_remaining.
Referenced by lstcon_rpc_trans_postwait().
void lstcon_rpc_trans_destroy (lstcon_rpc_trans_t * trans)
Definition at line 545 of file conrpc.c.
References CDEBUG, lstcon_rpc::crp_finished, lstcon_rpc::crp_link, lstcon_rpc::crp_node, lstcon_rpc::crp_posted, lstcon_rpc::crp_rpc, lstcon_rpc::crp_status, lstcon_rpc::crp_trans, srpc_client_rpc::crpc_lock, D_NET, LASSERT, LIBCFS_FREE, list_del(), list_del_init(), list_empty(), list_for_each_entry_safe, lstcon_rpc_put(), lstcon_rpc_trans_name(), lstcon_rpc_trans::tas_link, lstcon_rpc_trans::tas_olink, lstcon_rpc_trans::tas_opc, lstcon_rpc_trans::tas_remaining, and lstcon_rpc_trans::tas_rpcs_list.
Referenced by lstcon_batch_op(), lstcon_debug_ndlist(), lstcon_group_del(), lstcon_group_nodes_add(), lstcon_group_nodes_remove(), lstcon_group_refresh(), lstcon_ndlist_stat(), lstcon_rpc_pinger_stop(), lstcon_rpc_trans_ndlist(), lstcon_session_end(), lstcon_test_batch_query(), and lstcon_test_nodes_add().
int lstcon_rpc_trans_interpreter (lstcon_rpc_trans_t * trans, struct list_head __user * head_up, lstcon_rpc_readent_func_t readent)
Definition at line 471 of file conrpc.c.
References cfs_duration_usec(), cfs_time_sub(), console_session, lstcon_rpc::crp_node, lstcon_rpc::crp_stamp, error, LASSERT, list_entry, list_for_each_entry, lstcon_rpc_get_reply(), msg, srpc_msg::msg_body, lstcon_node::nd_id, lstcon_node::nd_state, list_head::next, srpc_msg::reply, lstcon_rpc_ent_t::rpe_fwk_errno, lstcon_rpc_ent_t::rpe_peer, lstcon_rpc_ent_t::rpe_rpc_errno, lstcon_rpc_ent_t::rpe_sid, lstcon_rpc_ent_t::rpe_stamp, lstcon_rpc_ent_t::rpe_state, lstcon_session_t::ses_id, lst_sid_t::ses_stamp, lstcon_rpc_trans::tas_opc, and lstcon_rpc_trans::tas_rpcs_list.
Referenced by lstcon_batch_op(), lstcon_debug_ndlist(), lstcon_group_nodes_add(), lstcon_group_nodes_remove(), lstcon_group_refresh(), lstcon_ndlist_stat(), lstcon_test_batch_query(), and lstcon_test_nodes_add().
static char* lstcon_rpc_trans_name (int transop) [static]
Definition at line 199 of file conrpc.c.
References LST_TRANS_SESEND, LST_TRANS_SESNEW, LST_TRANS_SESPING, LST_TRANS_SESQRY, LST_TRANS_STATQRY, LST_TRANS_TSBCLIADD, LST_TRANS_TSBCLIQRY, LST_TRANS_TSBRUN, LST_TRANS_TSBSRVADD, LST_TRANS_TSBSRVQRY, and LST_TRANS_TSBSTOP.
Referenced by lstcon_rpc_cleanup_wait(), lstcon_rpc_trans_destroy(), lstcon_rpc_trans_ndlist(), lstcon_rpc_trans_postwait(), and lstcon_rpc_trans_stat().
int lstcon_rpc_trans_ndlist (struct list_head * ndlist, struct list_head * translist, int transop, void * arg, lstcon_rpc_cond_func_t condition, lstcon_rpc_trans_t ** transpp)
Definition at line 1087 of file conrpc.c.
References CDEBUG, CERROR, D_NET, list_for_each_entry, LST_TRANS_SESEND, LST_TRANS_SESNEW, LST_TRANS_SESPING, LST_TRANS_SESQRY, LST_TRANS_STATQRY, LST_TRANS_TSBCLIADD, LST_TRANS_TSBCLIQRY, LST_TRANS_TSBRUN, LST_TRANS_TSBSRVADD, LST_TRANS_TSBSRVQRY, LST_TRANS_TSBSTOP, lstcon_batrpc_prep(), lstcon_dbgrpc_prep(), lstcon_rpc_trans_addreq(), lstcon_rpc_trans_destroy(), lstcon_rpc_trans_name(), lstcon_rpc_trans_prep(), lstcon_sesrpc_prep(), lstcon_statrpc_prep(), lstcon_testrpc_prep(), lstcon_ndlink_t::ndl_node, and lstcon_rpc_trans::tas_features.
Referenced by lstcon_batch_op(), lstcon_debug_ndlist(), lstcon_group_del(), lstcon_group_nodes_add(), lstcon_group_nodes_remove(), lstcon_group_refresh(), lstcon_ndlist_stat(), lstcon_session_end(), lstcon_test_batch_query(), and lstcon_test_nodes_add().
int lstcon_rpc_trans_postwait (lstcon_rpc_trans_t * trans, int timeout)
Definition at line 337 of file conrpc.c.
References CDEBUG, cfs_time_seconds(), console_session, lstcon_rpc::crp_posted, D_NET, LASSERT, list_empty(), list_for_each_entry, LST_TRANS_MIN_TIMEOUT, lstcon_rpc_post(), lstcon_rpc_trans_abort(), lstcon_rpc_trans_check(), lstcon_rpc_trans_name(), lstcon_rpc_trans_stat(), lstcon_trans_stat(), lstcon_session_t::ses_mutex, lstcon_session_t::ses_shutdown, lstcon_rpc_trans::tas_opc, lstcon_rpc_trans::tas_remaining, lstcon_rpc_trans::tas_rpcs_list, and lstcon_rpc_trans::tas_waitq.
Referenced by lstcon_batch_op(), lstcon_debug_ndlist(), lstcon_group_del(), lstcon_group_nodes_add(), lstcon_group_nodes_remove(), lstcon_group_refresh(), lstcon_ndlist_stat(), lstcon_session_end(), lstcon_test_batch_query(), and lstcon_test_nodes_add().
int lstcon_rpc_trans_prep (struct list_head * translist, int transop, lstcon_rpc_trans_t ** transpp)
Definition at line 238 of file conrpc.c.
References console_session, INIT_LIST_HEAD, LIBCFS_ALLOC, list_add_tail(), list_for_each_entry, LST_TRANS_PRIVATE, lstcon_session_t::ses_features, lstcon_session_t::ses_rpc_lock, lstcon_session_t::ses_trans_list, lstcon_rpc_trans::tas_features, lstcon_rpc_trans::tas_link, lstcon_rpc_trans::tas_olink, lstcon_rpc_trans::tas_opc, lstcon_rpc_trans::tas_remaining, lstcon_rpc_trans::tas_rpcs_list, and lstcon_rpc_trans::tas_waitq.
Referenced by lstcon_rpc_pinger_start(), and lstcon_rpc_trans_ndlist().
void lstcon_rpc_trans_stat (lstcon_rpc_trans_t * trans, lstcon_trans_stat_t * stat)
Definition at line 425 of file conrpc.c.
References CDEBUG, lstcon_rpc::crp_node, lstcon_rpc::crp_stamp, D_NET, error, LASSERT, list_for_each_entry, LST_TRANS_SESNEW, lstcon_rpc_get_reply(), lstcon_rpc_stat_failure(), lstcon_rpc_stat_reply(), lstcon_rpc_stat_success(), lstcon_rpc_stat_total(), lstcon_rpc_trans_name(), lstcon_session_feats_check(), lstcon_rpc_trans::tas_features, lstcon_rpc_trans::tas_opc, lstcon_rpc_trans::tas_rpcs_list, lstcon_trans_stat_t::trs_fwk_errno, and lstcon_trans_stat_t::trs_rpc_errno.
Referenced by lstcon_rpc_pinger_stop(), and lstcon_rpc_trans_postwait().
static int lstcon_sesnew_stat_reply (lstcon_rpc_trans_t * trans, lstcon_node_t * nd, srpc_msg_t * reply) [static]
Definition at line 920 of file conrpc.c.
References CNETERR, console_session, libcfs_nid2str(), LST_FEATS_MASK, srpc_msg::mksn_reply, srpc_msg::msg_body, srpc_msg::msg_ses_feats, lstcon_node::nd_id, lstcon_node::nd_timeout, lnet_process_id_t::nid, lstcon_session_t::ses_rpc_lock, status, lstcon_rpc_trans::tas_feats_updated, and lstcon_rpc_trans::tas_features.
Referenced by lstcon_rpc_stat_reply().
int lstcon_sesrpc_prep (lstcon_node_t * nd, int transop, unsigned feats, lstcon_rpc_t ** crpc)
Definition at line 599 of file conrpc.c.
References console_session, LBUG, LST_TRANS_SESEND, LST_TRANS_SESNEW, lstcon_rpc_prep(), lstcon_session_t::ses_force, lstcon_session_t::ses_id, lstcon_session_t::ses_name, SRPC_SERVICE_MAKE_SESSION, SRPC_SERVICE_REMOVE_SESSION, and strlcpy().
Referenced by lstcon_rpc_pinger(), and lstcon_rpc_trans_ndlist().
int lstcon_statrpc_prep (lstcon_node_t * nd, unsigned feats, lstcon_rpc_t ** crpc)
Definition at line 689 of file conrpc.c.
References console_session, lstcon_rpc_prep(), lstcon_session_t::ses_id, and SRPC_SERVICE_QUERY_STAT.
Referenced by lstcon_rpc_trans_ndlist().
int lstcon_testrpc_prep (lstcon_node_t * nd, int transop, unsigned feats, lstcon_test_t * test, lstcon_rpc_t ** crpc)
Definition at line 813 of file conrpc.c.
References srpc_bulk_t::bk_iovs, srpc_bulk_t::bk_sink, console_session, lstcon_group_t::grp_nnode, lnet_kiov_t::kiov_len, lnet_kiov_t::kiov_offset, lnet_kiov_t::kiov_page, LASSERT, LBUG, LST_FEAT_BULK_LEN, LST_TEST_BULK, LST_TEST_PING, LST_TRANS_TSBCLIADD, LST_TRANS_TSBSRVADD, lstcon_bulkrpc_v0_prep(), lstcon_bulkrpc_v1_prep(), lstcon_dstnodes_prep(), lstcon_pingrpc_prep(), lstcon_rpc_prep(), lstcon_rpc_put(), min_t, lstcon_session_t::ses_id, sfw_id_pages, SRPC_SERVICE_BRW, SRPC_SERVICE_PING, SRPC_SERVICE_TEST, lstcon_test::tes_cliidx, lstcon_test::tes_concur, lstcon_test::tes_dist, lstcon_test::tes_dst_grp, lstcon_test::tes_hdr, lstcon_test::tes_loop, lstcon_test::tes_param, lstcon_test::tes_span, lstcon_test::tes_src_grp, lstcon_test::tes_stop_onerr, lstcon_test::tes_type, and lstcon_tsb_hdr::tsb_id.
Referenced by lstcon_rpc_trans_ndlist().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.