Lustre: lnet/selftest/console.c File Reference
lnet/selftest/console.c File Reference
#include <libcfs/libcfs.h>
#include <lnet/lib-lnet.h>
#include "console.h"
#include "conrpc.h"
Defines
#define LST_NODE_STATE_COUNTER(nd, p)
Functions
static void lstcon_node_get (lstcon_node_t *nd)
static int lstcon_node_find (lnet_process_id_t id, lstcon_node_t **ndpp, int create)
static void lstcon_node_put (lstcon_node_t *nd)
static int lstcon_ndlink_find (struct list_head *hash, lnet_process_id_t id, lstcon_ndlink_t **ndlpp, int create)
static void lstcon_ndlink_release (lstcon_ndlink_t *ndl)
static int lstcon_group_alloc (char *name, lstcon_group_t **grpp)
static void lstcon_group_addref (lstcon_group_t *grp)
static void lstcon_group_ndlink_release (lstcon_group_t *, lstcon_ndlink_t *)
static void lstcon_group_drain (lstcon_group_t *grp, int keep)
static void lstcon_group_decref (lstcon_group_t *grp)
static int lstcon_group_find (const char *name, lstcon_group_t **grpp)
static int lstcon_group_ndlink_find (lstcon_group_t *grp, lnet_process_id_t id, lstcon_ndlink_t **ndlpp, int create)
static void lstcon_group_ndlink_move (lstcon_group_t *old, lstcon_group_t *new, lstcon_ndlink_t *ndl)
static void lstcon_group_move (lstcon_group_t *old, lstcon_group_t *new)
static int lstcon_sesrpc_condition (int transop, lstcon_node_t *nd, void *arg)
static int lstcon_sesrpc_readent (int transop, srpc_msg_t *msg, lstcon_rpc_ent_t __user *ent_up)
static int lstcon_group_nodes_add (lstcon_group_t *grp, int count, lnet_process_id_t __user *ids_up, unsigned *featp, struct list_head __user *result_up)
static int lstcon_group_nodes_remove (lstcon_group_t *grp, int count, lnet_process_id_t __user *ids_up, struct list_head __user *result_up)
int lstcon_group_add (char *name)
int lstcon_nodes_add (char *name, int count, lnet_process_id_t __user *ids_up, unsigned *featp, struct list_head __user *result_up)
int lstcon_group_del (char *name)
int lstcon_group_clean (char *name, int args)
int lstcon_nodes_remove (char *name, int count, lnet_process_id_t __user *ids_up, struct list_head __user *result_up)
int lstcon_group_refresh (char *name, struct list_head __user *result_up)
int lstcon_group_list (int index, int len, char __user *name_up)
static int lstcon_nodes_getent (struct list_head *head, int *index_p, int *count_p, lstcon_node_ent_t __user *dents_up)
int lstcon_group_info (char *name, lstcon_ndlist_ent_t __user *gents_p, int *index_p, int *count_p, lstcon_node_ent_t __user *dents_up)
static int lstcon_batch_find (const char *name, lstcon_batch_t **batpp)
int lstcon_batch_add (char *name)
int lstcon_batch_list (int index, int len, char __user *name_up)
int lstcon_batch_info (char *name, lstcon_test_batch_ent_t __user *ent_up, int server, int testidx, int *index_p, int *ndent_p, lstcon_node_ent_t __user *dents_up)
static int lstcon_batrpc_condition (int transop, lstcon_node_t *nd, void *arg)
static int lstcon_batch_op (lstcon_batch_t *bat, int transop, struct list_head __user *result_up)
int lstcon_batch_run (char *name, int timeout, struct list_head __user *result_up)
int lstcon_batch_stop (char *name, int force, struct list_head __user *result_up)
static void lstcon_batch_destroy (lstcon_batch_t *bat)
static int lstcon_testrpc_condition (int transop, lstcon_node_t *nd, void *arg)
static int lstcon_test_nodes_add (lstcon_test_t *test, struct list_head __user *result_up)
static int lstcon_verify_batch (const char *name, lstcon_batch_t **batch)
static int lstcon_verify_group (const char *name, lstcon_group_t **grp)
int lstcon_test_add (char *batch_name, int type, int loop, int concur, int dist, int span, char *src_name, char *dst_name, void *param, int paramlen, int *retp, struct list_head __user *result_up)
static int lstcon_test_find (lstcon_batch_t *batch, int idx, lstcon_test_t **testpp)
static int lstcon_tsbrpc_readent (int transop, srpc_msg_t *msg, lstcon_rpc_ent_t __user *ent_up)
int lstcon_test_batch_query (char *name, int testidx, int client, int timeout, struct list_head __user *result_up)
static int lstcon_statrpc_readent (int transop, srpc_msg_t *msg, lstcon_rpc_ent_t __user *ent_up)
static int lstcon_ndlist_stat (struct list_head *ndlist, int timeout, struct list_head __user *result_up)
int lstcon_group_stat (char *grp_name, int timeout, struct list_head __user *result_up)
int lstcon_nodes_stat (int count, lnet_process_id_t __user *ids_up, int timeout, struct list_head __user *result_up)
static int lstcon_debug_ndlist (struct list_head *ndlist, struct list_head *translist, int timeout, struct list_head __user *result_up)
int lstcon_session_debug (int timeout, struct list_head __user *result_up)
int lstcon_batch_debug (int timeout, char *name, int client, struct list_head __user *result_up)
int lstcon_group_debug (int timeout, char *name, struct list_head __user *result_up)
int lstcon_nodes_debug (int timeout, int count, lnet_process_id_t __user *ids_up, struct list_head __user *result_up)
int lstcon_session_match (lst_sid_t sid)
static void lstcon_new_session_id (lst_sid_t *sid)
int lstcon_session_new (char *name, int key, unsigned feats, int timeout, int force, lst_sid_t __user *sid_up)
int lstcon_session_info (lst_sid_t __user *sid_up, int __user *key_up, unsigned __user *featp, lstcon_ndlist_ent_t __user *ndinfo_up, char __user *name_up, int len)
int lstcon_session_end ()
int lstcon_session_feats_check (unsigned feats)
static int lstcon_acceptor_handle (srpc_server_rpc_t *rpc)
static void lstcon_init_acceptor_service (void)
int lstcon_ioctl_entry (unsigned int cmd, struct libcfs_ioctl_hdr *hdr)
DECLARE_IOCTL_HANDLER (lstcon_ioctl_handler, lstcon_ioctl_entry)
int lstcon_console_init (void)
int lstcon_console_fini (void)
Variables
lstcon_session_t console_session
static srpc_service_t lstcon_acceptor_service
Define Documentation
#define LST_NODE_STATE_COUNTER (nd, p)
Value:
do {                                                    \
        if ((nd)->nd_state == LST_NODE_ACTIVE)          \
                (p)->nle_nactive ++;                    \
        else if ((nd)->nd_state == LST_NODE_BUSY)       \
                (p)->nle_nbusy ++;                      \
        else if ((nd)->nd_state == LST_NODE_DOWN)       \
                (p)->nle_ndown ++;                      \
        else                                            \
                (p)->nle_nunknown ++;                   \
        (p)->nle_nnode ++;                              \
} while (0)
Definition at line 49 of file console.c.
Referenced by lstcon_batch_info(), lstcon_group_info(), and lstcon_session_info().
Function Documentation
DECLARE_IOCTL_HANDLER (lstcon_ioctl_handler , lstcon_ioctl_entry)
static int lstcon_acceptor_handle (srpc_server_rpc_t * rpc) [static]
Definition at line 1913 of file console.c.
References srpc_buffer::buf_msg, CERROR, lstcon_group_t::grp_link, lstcon_group_t::grp_ref, lstcon_group_t::grp_userland, srpc_msg::join_reply, srpc_msg::join_reqst, list_add_tail(), LNET_NID_ANY, LST_NODE_ACTIVE, lstcon_group_addref(), lstcon_group_alloc(), lstcon_group_decref(), lstcon_group_find(), lstcon_group_ndlink_find(), lstcon_session_feats_check(), lstcon_session_match(), srpc_msg::msg_body, srpc_msg::msg_ses_feats, lstcon_node::nd_state, lstcon_node::nd_timeout, lstcon_ndlink_t::ndl_node, lstcon_session_t::ses_features, lstcon_session_t::ses_grp_list, lstcon_session_t::ses_id, lstcon_session_t::ses_mutex, lstcon_session_t::ses_name, lst_sid_t::ses_nid, lstcon_session_t::ses_timeout, sfw_unpack_message(), srpc_server_rpc::srpc_peer, srpc_server_rpc::srpc_replymsg, srpc_server_rpc::srpc_reqstbuf, and strlcpy().
Referenced by lstcon_init_acceptor_service().
int lstcon_batch_add (char * name)
Definition at line 846 of file console.c.
References lstcon_batch_t::bat_cli_hash, lstcon_batch_t::bat_cli_list, lstcon_batch_t::bat_hdr, lst_bid_t::bat_id, lstcon_batch_t::bat_link, lstcon_batch_t::bat_name, lstcon_batch_t::bat_ntest, lstcon_batch_t::bat_srv_hash, lstcon_batch_t::bat_srv_list, lstcon_batch_t::bat_state, lstcon_batch_t::bat_test_list, lstcon_batch_t::bat_trans_list, CDEBUG, CERROR, D_NET, INIT_LIST_HEAD, LIBCFS_ALLOC, LIBCFS_FREE, list_add_tail(), LST_BATCH_IDLE, LST_NODE_HASHSIZE, lstcon_batch_find(), lstcon_session_t::ses_bat_list, lstcon_session_t::ses_id_cookie, lstcon_tsb_hdr::tsb_id, and lstcon_tsb_hdr::tsb_index.
Referenced by lst_batch_add_ioctl(), and lstcon_session_new().
int lstcon_batch_debug (int timeout, char * name, int client, struct list_head __user * result_up)
Definition at line 1616 of file console.c.
References lstcon_batch_t::bat_cli_list, lstcon_batch_t::bat_srv_list, lstcon_batch_find(), and lstcon_debug_ndlist().
Referenced by lst_debug_ioctl().
static void lstcon_batch_destroy (lstcon_batch_t * bat) [static]
Definition at line 1093 of file console.c.
References lstcon_batch_t::bat_cli_hash, lstcon_batch_t::bat_cli_list, lstcon_batch_t::bat_link, lstcon_batch_t::bat_srv_hash, lstcon_batch_t::bat_srv_list, lstcon_batch_t::bat_test_list, lstcon_batch_t::bat_trans_list, LASSERT, LIBCFS_FREE, list_del(), list_del_init(), list_empty(), list_entry, LST_NODE_HASHSIZE, lstcon_group_decref(), lstcon_ndlink_release(), lstcon_ndlink_t::ndl_link, list_head::next, offsetof, lstcon_test::tes_dst_grp, lstcon_test::tes_link, lstcon_test::tes_paramlen, lstcon_test::tes_src_grp, lstcon_test::tes_trans_list, and test().
Referenced by lstcon_session_end(), and lstcon_session_new().
static int lstcon_batch_find (const char * name, lstcon_batch_t ** batpp) [static]
Definition at line 831 of file console.c.
References lstcon_batch_t::bat_name, list_for_each_entry, LST_NAME_SIZE, and lstcon_session_t::ses_bat_list.
Referenced by lstcon_batch_add(), lstcon_batch_debug(), lstcon_batch_info(), lstcon_batch_run(), lstcon_batch_stop(), lstcon_session_new(), lstcon_test_batch_query(), and lstcon_verify_batch().
int lstcon_batch_info (char * name, lstcon_test_batch_ent_t __user * ent_up, int server, int testidx, int * index_p, int * ndent_p, lstcon_node_ent_t __user * dents_up)
Definition at line 930 of file console.c.
References lstcon_batch_ent_t::bae_ntest, lstcon_batch_ent_t::bae_state, lstcon_batch_t::bat_cli_list, lstcon_batch_t::bat_ntest, lstcon_batch_t::bat_srv_list, lstcon_batch_t::bat_state, lstcon_batch_t::bat_test_list, CDEBUG, D_NET, lstcon_group_t::grp_ndl_list, LIBCFS_ALLOC, LIBCFS_FREE, list_for_each_entry, LST_NODE_STATE_COUNTER, lstcon_batch_find(), lstcon_nodes_getent(), lstcon_ndlink_t::ndl_node, lstcon_test_batch_ent_t::tbe_batch, lstcon_test_batch_ent_t::tbe_cli_nle, lstcon_test_batch_ent_t::tbe_srv_nle, lstcon_test_batch_ent_t::tbe_test, lstcon_test::tes_concur, lstcon_test::tes_dst_grp, lstcon_test::tes_loop, lstcon_test::tes_src_grp, lstcon_test::tes_type, test(), lstcon_test_ent_t::tse_concur, lstcon_test_ent_t::tse_loop, lstcon_test_ent_t::tse_type, and lstcon_test_batch_ent_t::u.
Referenced by lst_batch_info_ioctl().
int lstcon_batch_list (int index, int len, char __user * name_up)
Definition at line 912 of file console.c.
References lstcon_batch_t::bat_name, LASSERT, list_for_each_entry, and lstcon_session_t::ses_bat_list.
Referenced by lst_batch_list_ioctl().
static int lstcon_batch_op (lstcon_batch_t * bat, int transop, struct list_head __user * result_up) [static]
Definition at line 1025 of file console.c.
References lstcon_batch_t::bat_cli_list, lstcon_batch_t::bat_trans_list, CERROR, LST_TRANS_TIMEOUT, lstcon_batrpc_condition(), lstcon_rpc_trans_destroy(), lstcon_rpc_trans_interpreter(), lstcon_rpc_trans_ndlist(), and lstcon_rpc_trans_postwait().
Referenced by lstcon_batch_run(), and lstcon_batch_stop().
int lstcon_batch_run (char * name, int timeout, struct list_head __user * result_up)
Definition at line 1049 of file console.c.
References lstcon_batch_t::bat_arg, lstcon_batch_t::bat_state, CDEBUG, D_NET, LST_BATCH_RUNNING, LST_TRANS_TSBRUN, lstcon_batch_find(), lstcon_batch_op(), lstcon_trans_stat(), and lstcon_tsbop_stat_success().
Referenced by lst_batch_run_ioctl().
int lstcon_batch_stop (char * name, int force, struct list_head __user * result_up)
Definition at line 1071 of file console.c.
References lstcon_batch_t::bat_arg, lstcon_batch_t::bat_state, CDEBUG, D_NET, LST_BATCH_IDLE, LST_TRANS_TSBSTOP, lstcon_batch_find(), lstcon_batch_op(), lstcon_trans_stat(), and lstcon_tsbop_stat_failure().
Referenced by lst_batch_stop_ioctl().
static int lstcon_batrpc_condition (int transop, lstcon_node_t * nd, void * arg) [static]
Definition at line 1003 of file console.c.
References LST_NODE_ACTIVE, LST_TRANS_TSBCLIQRY, LST_TRANS_TSBRUN, LST_TRANS_TSBSRVQRY, LST_TRANS_TSBSTOP, and lstcon_node::nd_state.
Referenced by lstcon_batch_op(), and lstcon_test_batch_query().
int lstcon_console_fini (void)
Definition at line 2082 of file console.c.
References LASSERT, libcfs_deregister_ioctl(), LIBCFS_FREE, list_empty(), LST_GLOBAL_HASHSIZE, LST_NODE_HASHSIZE, LST_SESSION_NONE, lstcon_rpc_module_fini(), lstcon_session_end(), lstcon_session_t::ses_bat_list, lstcon_session_t::ses_grp_list, lstcon_session_t::ses_mutex, lstcon_session_t::ses_ndl_hash, lstcon_session_t::ses_ndl_list, lstcon_session_t::ses_state, lstcon_session_t::ses_trans_list, srpc_remove_service(), srpc_shutdown_service(), and srpc_wait_service_shutdown().
Referenced by lnet_selftest_exit().
int lstcon_console_init (void)
Definition at line 2012 of file console.c.
References cfs_time_current_sec(), INIT_LIST_HEAD, LASSERT, LIBCFS_ALLOC, LIBCFS_FREE, libcfs_register_ioctl(), LST_FEATS_MASK, LST_GLOBAL_HASHSIZE, LST_INVALID_SID, LST_SESSION_NONE, lstcon_init_acceptor_service(), lstcon_rpc_module_init(), lstcon_session_t::ses_bat_list, lstcon_session_t::ses_expired, lstcon_session_t::ses_feats_updated, lstcon_session_t::ses_features, lstcon_session_t::ses_force, lstcon_session_t::ses_grp_list, lstcon_session_t::ses_id, lstcon_session_t::ses_laststamp, lstcon_session_t::ses_mutex, lstcon_session_t::ses_ndl_hash, lstcon_session_t::ses_ndl_list, lstcon_session_t::ses_state, lstcon_session_t::ses_timeout, lstcon_session_t::ses_trans_list, srpc_add_service(), srpc_remove_service(), srpc_service_add_buffers(), srpc_shutdown_service(), srpc_wait_service_shutdown(), and srpc_service::sv_wi_total.
Referenced by lnet_selftest_init().
static int lstcon_debug_ndlist (struct list_head * ndlist, struct list_head * translist, int timeout, struct list_head __user * result_up) [static]
Definition at line 1585 of file console.c.
References CERROR, LST_TRANS_SESQRY, LST_VALIDATE_TIMEOUT, lstcon_rpc_trans_destroy(), lstcon_rpc_trans_interpreter(), lstcon_rpc_trans_ndlist(), lstcon_rpc_trans_postwait(), lstcon_sesrpc_condition(), and lstcon_sesrpc_readent().
Referenced by lstcon_batch_debug(), lstcon_group_debug(), lstcon_nodes_debug(), and lstcon_session_debug().
int lstcon_group_add (char * name)
Definition at line 525 of file console.c.
References CERROR, lstcon_group_t::grp_link, list_add_tail(), lstcon_group_alloc(), lstcon_group_decref(), lstcon_group_find(), and lstcon_session_t::ses_grp_list.
Referenced by lst_group_add_ioctl().
static void lstcon_group_addref (lstcon_group_t * grp) [static]
Definition at line 231 of file console.c.
References lstcon_group_t::grp_ref.
Referenced by lstcon_acceptor_handle(), and lstcon_group_find().
static int lstcon_group_alloc (char * name, lstcon_group_t ** grpp) [static]
Definition at line 198 of file console.c.
References lstcon_group_t::grp_link, lstcon_group_t::grp_name, lstcon_group_t::grp_ndl_hash, lstcon_group_t::grp_ndl_list, lstcon_group_t::grp_ref, lstcon_group_t::grp_trans_list, INIT_LIST_HEAD, LIBCFS_ALLOC, LIBCFS_FREE, LST_NODE_HASHSIZE, and offsetof.
Referenced by lstcon_acceptor_handle(), lstcon_group_add(), lstcon_group_nodes_add(), lstcon_group_nodes_remove(), lstcon_nodes_debug(), and lstcon_nodes_stat().
int lstcon_group_clean (char * name, int args)
Definition at line 621 of file console.c.
References CDEBUG, D_NET, lstcon_group_t::grp_ndl_list, lstcon_group_t::grp_ref, list_empty(), LST_NODE_ACTIVE, LST_NODE_BUSY, LST_NODE_DOWN, LST_NODE_UNKNOWN, lstcon_group_decref(), lstcon_group_drain(), and lstcon_group_find().
Referenced by lst_group_update_ioctl().
int lstcon_group_debug (int timeout, char * name, struct list_head __user * result_up)
Definition at line 1634 of file console.c.
References lstcon_group_t::grp_ndl_list, lstcon_debug_ndlist(), lstcon_group_decref(), and lstcon_group_find().
Referenced by lst_debug_ioctl().
static void lstcon_group_decref (lstcon_group_t * grp) [static]
Definition at line 251 of file console.c.
References lstcon_group_t::grp_link, lstcon_group_t::grp_ndl_hash, lstcon_group_t::grp_ref, LASSERT, LIBCFS_FREE, list_del(), list_empty(), LST_NODE_HASHSIZE, lstcon_group_drain(), and offsetof.
Referenced by lstcon_acceptor_handle(), lstcon_batch_destroy(), lstcon_group_add(), lstcon_group_clean(), lstcon_group_debug(), lstcon_group_del(), lstcon_group_info(), lstcon_group_nodes_add(), lstcon_group_nodes_remove(), lstcon_group_refresh(), lstcon_group_stat(), lstcon_nodes_add(), lstcon_nodes_debug(), lstcon_nodes_remove(), lstcon_nodes_stat(), lstcon_session_end(), and lstcon_test_add().
int lstcon_group_del (char * name)
Definition at line 580 of file console.c.
References CDEBUG, CERROR, D_NET, lstcon_group_t::grp_ndl_list, lstcon_group_t::grp_ref, lstcon_group_t::grp_trans_list, LST_TRANS_SESEND, LST_TRANS_TIMEOUT, lstcon_group_decref(), lstcon_group_find(), lstcon_rpc_trans_destroy(), lstcon_rpc_trans_ndlist(), lstcon_rpc_trans_postwait(), and lstcon_sesrpc_condition().
Referenced by lst_group_del_ioctl().
static void lstcon_group_drain (lstcon_group_t * grp, int keep) [static]
Definition at line 239 of file console.c.
References lstcon_group_t::grp_ndl_list, list_for_each_entry_safe, lstcon_group_ndlink_release(), lstcon_node::nd_state, and lstcon_ndlink_t::ndl_node.
Referenced by lstcon_group_clean(), and lstcon_group_decref().
static int lstcon_group_find (const char * name, lstcon_group_t ** grpp) [static]
Definition at line 271 of file console.c.
References lstcon_group_t::grp_name, list_for_each_entry, LST_NAME_SIZE, lstcon_group_addref(), and lstcon_session_t::ses_grp_list.
Referenced by lstcon_acceptor_handle(), lstcon_group_add(), lstcon_group_clean(), lstcon_group_debug(), lstcon_group_del(), lstcon_group_info(), lstcon_group_refresh(), lstcon_group_stat(), lstcon_nodes_add(), lstcon_nodes_remove(), and lstcon_verify_group().
int lstcon_group_info (char * name, lstcon_ndlist_ent_t __user * gents_p, int * index_p, int * count_p, lstcon_node_ent_t __user * dents_up)
Definition at line 784 of file console.c.
References CDEBUG, CERROR, D_NET, lstcon_group_t::grp_ndl_list, LIBCFS_ALLOC, LIBCFS_FREE, list_for_each_entry, LST_NODE_STATE_COUNTER, lstcon_group_decref(), lstcon_group_find(), lstcon_nodes_getent(), and lstcon_ndlink_t::ndl_node.
Referenced by lst_group_info_ioctl().
int lstcon_group_list (int index, int len, char __user * name_up)
Definition at line 726 of file console.c.
References lstcon_group_t::grp_name, LASSERT, list_for_each_entry, and lstcon_session_t::ses_grp_list.
Referenced by lst_group_list_ioctl().
static void lstcon_group_move (lstcon_group_t * old, lstcon_group_t * new) [static]
Definition at line 333 of file console.c.
References lstcon_group_t::grp_ndl_list, list_empty(), list_entry, lstcon_group_ndlink_move(), and list_head::next.
Referenced by lstcon_group_nodes_add(), and lstcon_group_nodes_remove().
static int lstcon_group_ndlink_find (lstcon_group_t * grp, lnet_process_id_t id, lstcon_ndlink_t ** ndlpp, int create) [static]
Definition at line 288 of file console.c.
References lstcon_group_t::grp_ndl_hash, lstcon_group_t::grp_ndl_list, lstcon_group_t::grp_nnode, list_add_tail(), list_empty(), and lstcon_ndlink_find().
Referenced by lstcon_acceptor_handle(), lstcon_group_nodes_add(), lstcon_group_nodes_remove(), lstcon_nodes_debug(), and lstcon_nodes_stat().
static void lstcon_group_ndlink_move (lstcon_group_t * old, lstcon_group_t * new, lstcon_ndlink_t * ndl) [static]
Definition at line 315 of file console.c.
References lstcon_group_t::grp_nnode, list_add_tail(), list_del(), LNET_NIDADDR(), LST_NODE_HASHSIZE, lstcon_node::nd_id, lstcon_ndlink_t::ndl_hlink, lstcon_ndlink_t::ndl_link, lstcon_ndlink_t::ndl_node, and lnet_process_id_t::nid.
Referenced by lstcon_group_move(), and lstcon_group_nodes_remove().
static void lstcon_group_ndlink_release (lstcon_group_t * grp, lstcon_ndlink_t * ndl) [static]
Definition at line 307 of file console.c.
References lstcon_group_t::grp_nnode, list_del_init(), lstcon_ndlink_release(), and lstcon_ndlink_t::ndl_link.
Referenced by lstcon_group_drain().
static int lstcon_group_nodes_add (lstcon_group_t * grp, int count, lnet_process_id_t __user * ids_up, unsigned * featp, struct list_head __user * result_up) [static]
Definition at line 403 of file console.c.
References CERROR, lstcon_group_t::grp_ndl_list, lstcon_group_t::grp_trans_list, LST_TRANS_SESNEW, LST_TRANS_TIMEOUT, lstcon_group_alloc(), lstcon_group_decref(), lstcon_group_move(), lstcon_group_ndlink_find(), lstcon_rpc_trans_destroy(), lstcon_rpc_trans_interpreter(), lstcon_rpc_trans_ndlist(), lstcon_rpc_trans_postwait(), lstcon_sesrpc_condition(), lstcon_sesrpc_readent(), and lstcon_rpc_trans::tas_features.
Referenced by lstcon_nodes_add().
static int lstcon_group_nodes_remove (lstcon_group_t * grp, int count, lnet_process_id_t __user * ids_up, struct list_head __user * result_up) [static]
Definition at line 470 of file console.c.
References CERROR, error, lstcon_group_t::grp_ndl_list, lstcon_group_t::grp_trans_list, LST_TRANS_SESEND, LST_TRANS_TIMEOUT, lstcon_group_alloc(), lstcon_group_decref(), lstcon_group_move(), lstcon_group_ndlink_find(), lstcon_group_ndlink_move(), lstcon_rpc_trans_destroy(), lstcon_rpc_trans_interpreter(), lstcon_rpc_trans_ndlist(), lstcon_rpc_trans_postwait(), and lstcon_sesrpc_condition().
Referenced by lstcon_nodes_remove().
int lstcon_group_refresh (char * name, struct list_head __user * result_up)
Definition at line 684 of file console.c.
References CDEBUG, D_NET, lstcon_group_t::grp_ndl_list, lstcon_group_t::grp_ref, lstcon_group_t::grp_trans_list, LST_TRANS_SESNEW, LST_TRANS_TIMEOUT, lstcon_group_decref(), lstcon_group_find(), lstcon_rpc_trans_destroy(), lstcon_rpc_trans_interpreter(), lstcon_rpc_trans_ndlist(), lstcon_rpc_trans_postwait(), and lstcon_sesrpc_condition().
Referenced by lst_group_update_ioctl().
int lstcon_group_stat (char * grp_name, int timeout, struct list_head __user * result_up)
Definition at line 1521 of file console.c.
References CDEBUG, D_NET, lstcon_group_t::grp_ndl_list, lstcon_group_decref(), lstcon_group_find(), and lstcon_ndlist_stat().
Referenced by lst_stat_query_ioctl().
static void lstcon_init_acceptor_service (void) [static]
Definition at line 1997 of file console.c.
References lstcon_acceptor_handle(), SFW_FRWK_WI_MAX, SRPC_SERVICE_JOIN, srpc_service::sv_handler, srpc_service::sv_id, srpc_service::sv_name, and srpc_service::sv_wi_total.
Referenced by lstcon_console_init().
int lstcon_ioctl_entry (unsigned int cmd, struct libcfs_ioctl_hdr * hdr)
Definition at line 812 of file conctl.c.
References buf, CDEBUG, cfs_time_current_sec(), console_session, D_NET, libcfs_ioctl_data::ioc_hdr, IOC_LIBCFS_LNETST, libcfs_ioctl_data::ioc_pbuf1, libcfs_ioctl_data::ioc_pbuf2, libcfs_ioctl_data::ioc_plen1, libcfs_ioctl_data::ioc_u32, LIBCFS_ALLOC, LIBCFS_FREE, lst_batch_add_ioctl(), lst_batch_info_ioctl(), lst_batch_list_ioctl(), lst_batch_query_ioctl(), lst_batch_run_ioctl(), lst_batch_stop_ioctl(), lst_debug_ioctl(), lst_group_add_ioctl(), lst_group_del_ioctl(), lst_group_info_ioctl(), lst_group_list_ioctl(), lst_group_update_ioctl(), lst_nodes_add_ioctl(), lst_session_end_ioctl(), lst_session_info_ioctl(), lst_session_new_ioctl(), LST_SESSION_NONE, lst_stat_query_ioctl(), lst_test_add_ioctl(), lstcon_session_end(), LSTIO_BATCH_ADD, LSTIO_BATCH_INFO, LSTIO_BATCH_LIST, LSTIO_BATCH_QUERY, LSTIO_BATCH_START, LSTIO_BATCH_STOP, LSTIO_DEBUG, LSTIO_GROUP_ADD, LSTIO_GROUP_DEL, LSTIO_GROUP_INFO, LSTIO_GROUP_LIST, LSTIO_GROUP_UPDATE, LSTIO_NODES_ADD, LSTIO_SESSION_END, LSTIO_SESSION_INFO, LSTIO_SESSION_NEW, LSTIO_STAT_QUERY, LSTIO_TEST_ADD, lstcon_session_t::ses_expired, lstcon_session_t::ses_laststamp, lstcon_session_t::ses_mutex, lstcon_session_t::ses_shutdown, lstcon_session_t::ses_state, and lstcon_session_t::ses_trans_stat.
static int lstcon_ndlink_find (struct list_head * hash, lnet_process_id_t id, lstcon_ndlink_t ** ndlpp, int create) [static]
Definition at line 141 of file console.c.
References INIT_LIST_HEAD, LIBCFS_ALLOC, list_add_tail(), list_for_each_entry, LNET_NID_ANY, LNET_NIDADDR(), LST_NODE_HASHSIZE, lstcon_node_find(), lstcon_node_put(), lstcon_node::nd_id, lstcon_ndlink_t::ndl_hlink, lstcon_ndlink_t::ndl_link, lstcon_ndlink_t::ndl_node, lnet_process_id_t::nid, and lnet_process_id_t::pid.
Referenced by lstcon_group_ndlink_find(), and lstcon_testrpc_condition().
static void lstcon_ndlink_release (lstcon_ndlink_t * ndl) [static]
Definition at line 186 of file console.c.
References LASSERT, LIBCFS_FREE, list_del(), list_empty(), lstcon_node_put(), lstcon_ndlink_t::ndl_hlink, lstcon_ndlink_t::ndl_link, and lstcon_ndlink_t::ndl_node.
Referenced by lstcon_batch_destroy(), and lstcon_group_ndlink_release().
static int lstcon_ndlist_stat (struct list_head * ndlist, int timeout, struct list_head __user * result_up) [static]
Definition at line 1495 of file console.c.
References CERROR, INIT_LIST_HEAD, LST_TRANS_STATQRY, LST_VALIDATE_TIMEOUT, lstcon_rpc_trans_destroy(), lstcon_rpc_trans_interpreter(), lstcon_rpc_trans_ndlist(), lstcon_rpc_trans_postwait(), and lstcon_statrpc_readent().
Referenced by lstcon_group_stat(), and lstcon_nodes_stat().
static void lstcon_new_session_id (lst_sid_t * sid) [static]
Definition at line 1703 of file console.c.
References cfs_time_current(), LASSERT, LNetGetId(), LST_SESSION_NONE, lst_sid_t::ses_nid, lst_sid_t::ses_stamp, and lstcon_session_t::ses_state.
Referenced by lstcon_session_new().
static int lstcon_node_find (lnet_process_id_t id, lstcon_node_t ** ndpp, int create) [static]
Definition at line 73 of file console.c.
References cfs_time_current(), LASSERT, LIBCFS_ALLOC, list_add_tail(), list_for_each_entry, LNET_NID_ANY, LNET_NIDADDR(), LST_GLOBAL_HASHSIZE, LST_NODE_UNKNOWN, lstcon_node_get(), lstcon_node::nd_id, lstcon_node::nd_ping, lstcon_node::nd_ref, lstcon_node::nd_stamp, lstcon_node::nd_state, lstcon_node::nd_timeout, lstcon_ndlink_t::ndl_hlink, lstcon_ndlink_t::ndl_link, lstcon_ndlink_t::ndl_node, lnet_process_id_t::nid, lnet_process_id_t::pid, lstcon_session_t::ses_ndl_hash, and lstcon_session_t::ses_ndl_list.
Referenced by lstcon_ndlink_find().
static void lstcon_node_get (lstcon_node_t * nd) [static]
Definition at line 65 of file console.c.
References LASSERT, and lstcon_node::nd_ref.
Referenced by lstcon_node_find().
static void lstcon_node_put (lstcon_node_t * nd) [static]
Definition at line 119 of file console.c.
References LASSERT, LIBCFS_FREE, list_del(), list_empty(), lstcon_node::nd_ref, lstcon_ndlink_t::ndl_hlink, and lstcon_ndlink_t::ndl_link.
Referenced by lstcon_ndlink_find(), and lstcon_ndlink_release().
int lstcon_nodes_add (char * name, int count, lnet_process_id_t __user * ids_up, unsigned * featp, struct list_head __user * result_up)
Definition at line 549 of file console.c.
References CDEBUG, D_NET, lstcon_group_t::grp_ref, LASSERT, lstcon_group_decref(), lstcon_group_find(), and lstcon_group_nodes_add().
Referenced by lst_nodes_add_ioctl().
int lstcon_nodes_debug (int timeout, int count, lnet_process_id_t __user * ids_up, struct list_head __user * result_up)
Definition at line 1652 of file console.c.
References CDEBUG, CERROR, D_NET, lstcon_group_t::grp_ndl_list, lstcon_debug_ndlist(), lstcon_group_alloc(), lstcon_group_decref(), and lstcon_group_ndlink_find().
Referenced by lst_debug_ioctl().
static int lstcon_nodes_getent (struct list_head * head, int * index_p, int * count_p, lstcon_node_ent_t __user * dents_up) [static]
Definition at line 744 of file console.c.
References LASSERT, list_for_each_entry, lstcon_node::nd_id, lstcon_node::nd_state, and lstcon_ndlink_t::ndl_node.
Referenced by lstcon_batch_info(), and lstcon_group_info().
int lstcon_nodes_remove (char * name, int count, lnet_process_id_t __user * ids_up, struct list_head __user * result_up)
Definition at line 653 of file console.c.
References CDEBUG, D_NET, lstcon_group_t::grp_ndl_list, lstcon_group_t::grp_ref, list_empty(), lstcon_group_decref(), lstcon_group_find(), and lstcon_group_nodes_remove().
Referenced by lst_group_update_ioctl().
int lstcon_nodes_stat (int count, lnet_process_id_t __user * ids_up, int timeout, struct list_head __user * result_up)
Definition at line 1541 of file console.c.
References CDEBUG, CERROR, D_ERROR, D_NET, lstcon_group_t::grp_ndl_list, libcfs_id2str(), lstcon_group_alloc(), lstcon_group_decref(), lstcon_group_ndlink_find(), and lstcon_ndlist_stat().
Referenced by lst_stat_query_ioctl().
static int lstcon_sesrpc_condition (int transop, lstcon_node_t * nd, void * arg) [static]
Definition at line 345 of file console.c.
References LBUG, LST_NODE_ACTIVE, LST_TRANS_SESEND, LST_TRANS_SESNEW, LST_TRANS_SESQRY, lstcon_node::nd_ref, and lstcon_node::nd_state.
Referenced by lstcon_debug_ndlist(), lstcon_group_del(), lstcon_group_nodes_add(), lstcon_group_nodes_remove(), lstcon_group_refresh(), and lstcon_session_end().
static int lstcon_sesrpc_readent (int transop, srpc_msg_t * msg, lstcon_rpc_ent_t __user * ent_up) [static]
Definition at line 374 of file console.c.
References srpc_msg::dbg_reply, LBUG, LST_NAME_SIZE, LST_TRANS_SESEND, LST_TRANS_SESNEW, LST_TRANS_SESQRY, and srpc_msg::msg_body.
Referenced by lstcon_debug_ndlist(), and lstcon_group_nodes_add().
int lstcon_session_debug (int timeout, struct list_head __user * result_up)
Definition at line 1609 of file console.c.
References lstcon_debug_ndlist(), and lstcon_session_t::ses_ndl_list.
Referenced by lst_debug_ioctl().
int lstcon_session_end (void)
Definition at line 1819 of file console.c.
References CERROR, lstcon_group_t::grp_ref, LASSERT, list_empty(), list_entry, LST_INVALID_SID, LST_SESSION_ACTIVE, LST_SESSION_NONE, LST_TRANS_SESEND, LST_TRANS_TIMEOUT, lstcon_batch_destroy(), lstcon_group_decref(), lstcon_rpc_cleanup_wait(), lstcon_rpc_pinger_stop(), lstcon_rpc_trans_destroy(), lstcon_rpc_trans_ndlist(), lstcon_rpc_trans_postwait(), lstcon_sesrpc_condition(), list_head::next, lstcon_session_t::ses_bat_list, lstcon_session_t::ses_expired, lstcon_session_t::ses_feats_updated, lstcon_session_t::ses_force, lstcon_session_t::ses_grp_list, lstcon_session_t::ses_id, lstcon_session_t::ses_key, lstcon_session_t::ses_ndl_list, lstcon_session_t::ses_shutdown, and lstcon_session_t::ses_state.
Referenced by lst_session_end_ioctl(), lstcon_console_fini(), lstcon_ioctl_entry(), and lstcon_session_new().
int lstcon_session_feats_check (unsigned feats)
Definition at line 1881 of file console.c.
References CERROR, LST_FEATS_MASK, lstcon_session_t::ses_feats_updated, lstcon_session_t::ses_features, and lstcon_session_t::ses_rpc_lock.
Referenced by lstcon_acceptor_handle(), and lstcon_rpc_trans_stat().
int lstcon_session_info (lst_sid_t __user * sid_up, int __user * key_up, unsigned __user * featp, lstcon_ndlist_ent_t __user * ndinfo_up, char __user * name_up, int len)
Definition at line 1784 of file console.c.
References LIBCFS_ALLOC, LIBCFS_FREE, list_for_each_entry, LST_NODE_STATE_COUNTER, LST_SESSION_ACTIVE, lstcon_ndlink_t::ndl_node, lstcon_session_t::ses_features, lstcon_session_t::ses_id, lstcon_session_t::ses_key, lstcon_session_t::ses_name, lstcon_session_t::ses_ndl_list, and lstcon_session_t::ses_state.
Referenced by lst_session_info_ioctl().
int lstcon_session_match (lst_sid_t sid)
Definition at line 1696 of file console.c.
References lstcon_session_t::ses_id, lst_sid_t::ses_nid, and lst_sid_t::ses_stamp.
Referenced by lstcon_acceptor_handle(), lstcon_rpc_get_reply(), and lstcon_rpc_stat_reply().
int lstcon_session_new (char * name, int key, unsigned feats, int timeout, int force, lst_sid_t __user * sid_up)
Definition at line 1715 of file console.c.
References CNETERR, LASSERT, list_empty(), LST_CONSOLE_TIMEOUT, LST_DEFAULT_BATCH, LST_FEATS_MASK, LST_GLOBAL_HASHSIZE, LST_SESSION_ACTIVE, LST_SESSION_NONE, lstcon_batch_add(), lstcon_batch_destroy(), lstcon_batch_find(), lstcon_new_session_id(), lstcon_rpc_pinger_start(), lstcon_session_end(), lstcon_session_t::ses_feats_updated, lstcon_session_t::ses_features, lstcon_session_t::ses_force, lstcon_session_t::ses_id, lstcon_session_t::ses_key, lstcon_session_t::ses_name, lstcon_session_t::ses_ndl_hash, lstcon_session_t::ses_state, lstcon_session_t::ses_timeout, and strlcpy().
Referenced by lst_session_new_ioctl().
static int lstcon_statrpc_readent (int transop, srpc_msg_t * msg, lstcon_rpc_ent_t __user * ent_up) [static]
Definition at line 1469 of file console.c.
References __user, srpc_msg::msg_body, and srpc_msg::stat_reply.
Referenced by lstcon_ndlist_stat().
int lstcon_test_add (char * batch_name, int type, int loop, int concur, int dist, int span, char * src_name, char * dst_name, void * param, int paramlen, int * retp, struct list_head __user * result_up)
Definition at line 1284 of file console.c.
References lstcon_batch_t::bat_hdr, lstcon_batch_t::bat_ntest, lstcon_batch_t::bat_test_list, CDEBUG, CERROR, D_NET, lstcon_group_t::grp_userland, INIT_LIST_HEAD, LIBCFS_ALLOC, LIBCFS_FREE, list_add_tail(), lstcon_group_decref(), lstcon_test_nodes_add(), lstcon_trans_stat(), lstcon_verify_batch(), lstcon_verify_group(), offsetof, lstcon_test::tes_batch, lstcon_test::tes_cliidx, lstcon_test::tes_concur, lstcon_test::tes_dist, lstcon_test::tes_dst_grp, lstcon_test::tes_hdr, lstcon_test::tes_link, lstcon_test::tes_loop, lstcon_test::tes_oneside, lstcon_test::tes_param, lstcon_test::tes_paramlen, lstcon_test::tes_span, lstcon_test::tes_src_grp, lstcon_test::tes_stop_onerr, lstcon_test::tes_trans_list, lstcon_test::tes_type, test(), lstcon_tsb_hdr::tsb_id, and lstcon_tsb_hdr::tsb_index.
Referenced by lst_test_add_ioctl().
int lstcon_test_batch_query (char * name, int testidx, int client, int timeout, struct list_head __user * result_up)
Definition at line 1407 of file console.c.
References lstcon_batch_t::bat_cli_list, lstcon_batch_t::bat_hdr, lstcon_batch_t::bat_state, lstcon_batch_t::bat_trans_list, CDEBUG, CERROR, D_NET, lstcon_group_t::grp_ndl_list, LST_BATCH_IDLE, LST_TRANS_TSBCLIQRY, LST_TRANS_TSBSRVQRY, lstcon_batch_find(), lstcon_batrpc_condition(), lstcon_rpc_stat_failure(), lstcon_rpc_trans_destroy(), lstcon_rpc_trans_interpreter(), lstcon_rpc_trans_ndlist(), lstcon_rpc_trans_postwait(), lstcon_test_find(), lstcon_trans_stat(), lstcon_tsbqry_stat_run(), lstcon_tsbrpc_readent(), lstcon_test::tes_hdr, lstcon_test::tes_src_grp, lstcon_test::tes_trans_list, and test().
Referenced by lst_batch_query_ioctl().
static int lstcon_test_find (lstcon_batch_t * batch, int idx, lstcon_test_t ** testpp) [static]
Definition at line 1375 of file console.c.
References lstcon_batch_t::bat_test_list, list_for_each_entry, lstcon_test::tes_hdr, test(), and lstcon_tsb_hdr::tsb_index.
Referenced by lstcon_test_batch_query().
static int lstcon_test_nodes_add (lstcon_test_t * test, struct list_head __user * result_up) [static]
Definition at line 1190 of file console.c.
References CDEBUG, CERROR, D_NET, lstcon_group_t::grp_ndl_list, LASSERT, LST_TRANS_TIMEOUT, LST_TRANS_TSBCLIADD, LST_TRANS_TSBSRVADD, lstcon_rpc_trans_destroy(), lstcon_rpc_trans_interpreter(), lstcon_rpc_trans_ndlist(), lstcon_rpc_trans_postwait(), lstcon_testrpc_condition(), lstcon_trans_stat(), lstcon_test::tes_cliidx, lstcon_test::tes_dst_grp, lstcon_test::tes_src_grp, and lstcon_test::tes_trans_list.
Referenced by lstcon_test_add().
static int lstcon_testrpc_condition (int transop, lstcon_node_t * nd, void * arg) [static]
Definition at line 1146 of file console.c.
References lstcon_batch_t::bat_cli_hash, lstcon_batch_t::bat_cli_list, lstcon_batch_t::bat_srv_hash, lstcon_batch_t::bat_srv_list, head, LASSERT, list_add_tail(), list_empty(), LNET_NID_ANY, LST_NODE_ACTIVE, LST_TRANS_TSBCLIADD, LST_TRANS_TSBSRVADD, lstcon_ndlink_find(), lstcon_node::nd_id, lstcon_node::nd_state, lstcon_ndlink_t::ndl_link, lnet_process_id_t::nid, lstcon_test::tes_batch, lstcon_test::tes_oneside, and test().
Referenced by lstcon_test_nodes_add().
static int lstcon_tsbrpc_readent (int transop, srpc_msg_t * msg, lstcon_rpc_ent_t __user * ent_up) [static]
Definition at line 1390 of file console.c.
References srpc_msg::bat_reply, LASSERT, LST_TRANS_TSBCLIQRY, LST_TRANS_TSBSRVQRY, and srpc_msg::msg_body.
Referenced by lstcon_test_batch_query().
static int lstcon_verify_batch (const char * name, lstcon_batch_t ** batch) [static]
Definition at line 1242 of file console.c.
References CDEBUG, D_NET, LST_BATCH_IDLE, and lstcon_batch_find().
Referenced by lstcon_test_add().
static int lstcon_verify_group (const char * name, lstcon_group_t ** grp) [static]
Definition at line 1261 of file console.c.
References CDEBUG, D_NET, list_for_each_entry, LST_NODE_ACTIVE, lstcon_group_find(), lstcon_node::nd_state, and lstcon_ndlink_t::ndl_node.
Referenced by lstcon_test_add().
Variable Documentation
lstcon_session_t console_session
Definition at line 62 of file console.c.
Referenced by lst_batch_add_ioctl(), lst_batch_info_ioctl(), lst_batch_list_ioctl(), lst_batch_query_ioctl(), lst_batch_run_ioctl(), lst_batch_stop_ioctl(), lst_debug_ioctl(), lst_group_add_ioctl(), lst_group_del_ioctl(), lst_group_info_ioctl(), lst_group_list_ioctl(), lst_group_update_ioctl(), lst_nodes_add_ioctl(), lst_session_end_ioctl(), lst_stat_query_ioctl(), lstcon_batrpc_prep(), lstcon_dbgrpc_prep(), lstcon_ioctl_entry(), lstcon_rpc_cleanup_wait(), lstcon_rpc_init(), lstcon_rpc_module_fini(), lstcon_rpc_module_init(), lstcon_rpc_pinger(), lstcon_rpc_pinger_start(), lstcon_rpc_pinger_stop(), lstcon_rpc_prep(), lstcon_rpc_put(), lstcon_rpc_trans_check(), lstcon_rpc_trans_interpreter(), lstcon_rpc_trans_postwait(), lstcon_rpc_trans_prep(), lstcon_sesnew_stat_reply(), lstcon_sesrpc_prep(), lstcon_statrpc_prep(), and lstcon_testrpc_prep().
srpc_service_t lstcon_acceptor_service [static]
Definition at line 1996 of file console.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.