Lustre: lnet/selftest/console.h File Reference
lnet/selftest/console.h File Reference
#include <libcfs/libcfs.h>
#include <lnet/lnet.h>
#include <lnet/lib-types.h>
#include <lnet/lnetst.h>
#include "selftest.h"
#include "conrpc.h"
Data Structures
struct lstcon_node
struct lstcon_ndlink_t
struct lstcon_group_t
struct lstcon_tsb_hdr
struct lstcon_batch_t
struct lstcon_test
struct lstcon_session_t
Defines
#define LST_BATCH_IDLE 0xB0
#define LST_BATCH_RUNNING 0xB1
#define LST_GLOBAL_HASHSIZE 503
#define LST_NODE_HASHSIZE 239
#define LST_SESSION_NONE 0x0
#define LST_SESSION_ACTIVE 0x1
#define LST_CONSOLE_TIMEOUT 300
Typedefs
typedef struct lstcon_node lstcon_node_t
typedef struct lstcon_tsb_hdr lstcon_tsb_hdr_t
typedef struct lstcon_test lstcon_test_t
Functions
static lstcon_trans_stat_t * lstcon_trans_stat (void)
static struct list_head * lstcon_id2hash (lnet_process_id_t id, struct list_head *hash)
int lstcon_session_match (lst_sid_t sid)
int lstcon_session_new (char *name, int key, unsigned version, int timeout, int flags, lst_sid_t __user *sid_up)
int lstcon_session_info (lst_sid_t __user *sid_up, int __user *key, unsigned __user *verp, lstcon_ndlist_ent_t __user *entp, char __user *name_up, int len)
int lstcon_session_end (void)
int lstcon_session_debug (int timeout, struct list_head __user *result_up)
int lstcon_session_feats_check (unsigned feats)
int lstcon_batch_debug (int timeout, char *name, int client, struct list_head __user *result_up)
int lstcon_group_debug (int timeout, char *name, struct list_head __user *result_up)
int lstcon_nodes_debug (int timeout, int nnd, lnet_process_id_t __user *nds_up, struct list_head __user *result_up)
int lstcon_group_add (char *name)
int lstcon_group_del (char *name)
int lstcon_group_clean (char *name, int args)
int lstcon_group_refresh (char *name, struct list_head __user *result_up)
int lstcon_nodes_add (char *name, int nnd, lnet_process_id_t __user *nds_up, unsigned *featp, struct list_head __user *result_up)
int lstcon_nodes_remove (char *name, int nnd, lnet_process_id_t __user *nds_up, struct list_head __user *result_up)
int lstcon_group_info (char *name, lstcon_ndlist_ent_t __user *gent_up, int *index_p, int *ndent_p, lstcon_node_ent_t __user *ndents_up)
int lstcon_group_list (int idx, int len, char __user *name_up)
int lstcon_batch_add (char *name)
int lstcon_batch_run (char *name, int timeout, struct list_head __user *result_up)
int lstcon_batch_stop (char *name, int force, struct list_head __user *result_up)
int lstcon_test_batch_query (char *name, int testidx, int client, int timeout, struct list_head __user *result_up)
int lstcon_batch_del (char *name)
int lstcon_batch_list (int idx, int namelen, char __user *name_up)
int lstcon_batch_info (char *name, lstcon_test_batch_ent_t __user *ent_up, int server, int testidx, int *index_p, int *ndent_p, lstcon_node_ent_t __user *dents_up)
int lstcon_group_stat (char *grp_name, int timeout, struct list_head __user *result_up)
int lstcon_nodes_stat (int count, lnet_process_id_t __user *ids_up, int timeout, struct list_head __user *result_up)
int lstcon_test_add (char *batch_name, int type, int loop, int concur, int dist, int span, char *src_name, char *dst_name, void *param, int paramlen, int *retp, struct list_head __user *result_up)
int lstcon_console_init (void)
int lstcon_console_fini (void)
Variables
lstcon_session_t console_session
Define Documentation
#define LST_BATCH_IDLE 0xB0
Definition at line 81 of file console.h.
Referenced by lstcon_batch_add(), lstcon_batch_stop(), lstcon_test_batch_query(), and lstcon_verify_batch().
#define LST_BATCH_RUNNING 0xB1
Definition at line 82 of file console.h.
Referenced by lstcon_batch_run().
#define LST_CONSOLE_TIMEOUT 300
Definition at line 148 of file console.h.
Referenced by lstcon_session_new().
#define LST_GLOBAL_HASHSIZE 503
Definition at line 142 of file console.h.
Referenced by lstcon_console_fini(), lstcon_console_init(), lstcon_node_find(), and lstcon_session_new().
#define LST_NODE_HASHSIZE 239
Definition at line 143 of file console.h.
Referenced by lstcon_batch_add(), lstcon_batch_destroy(), lstcon_console_fini(), lstcon_group_alloc(), lstcon_group_decref(), lstcon_group_ndlink_move(), lstcon_id2hash(), and lstcon_ndlink_find().
#define LST_SESSION_ACTIVE 0x1
Definition at line 146 of file console.h.
Referenced by lstcon_session_end(), lstcon_session_info(), and lstcon_session_new().
#define LST_SESSION_NONE 0x0
Definition at line 145 of file console.h.
Referenced by lstcon_console_fini(), lstcon_console_init(), lstcon_ioctl_entry(), lstcon_new_session_id(), lstcon_session_end(), and lstcon_session_new().
Typedef Documentation
typedef struct lstcon_node lstcon_node_t
typedef struct lstcon_test lstcon_test_t
typedef struct lstcon_tsb_hdr lstcon_tsb_hdr_t
Function Documentation
int lstcon_batch_add (char * name)
Definition at line 846 of file console.c.
References lstcon_batch_t::bat_cli_hash, lstcon_batch_t::bat_cli_list, lstcon_batch_t::bat_hdr, lst_bid_t::bat_id, lstcon_batch_t::bat_link, lstcon_batch_t::bat_name, lstcon_batch_t::bat_ntest, lstcon_batch_t::bat_srv_hash, lstcon_batch_t::bat_srv_list, lstcon_batch_t::bat_state, lstcon_batch_t::bat_test_list, lstcon_batch_t::bat_trans_list, CDEBUG, CERROR, D_NET, INIT_LIST_HEAD, LIBCFS_ALLOC, LIBCFS_FREE, list_add_tail(), LST_BATCH_IDLE, LST_NODE_HASHSIZE, lstcon_batch_find(), lstcon_session_t::ses_bat_list, lstcon_session_t::ses_id_cookie, lstcon_tsb_hdr::tsb_id, and lstcon_tsb_hdr::tsb_index.
Referenced by lst_batch_add_ioctl(), and lstcon_session_new().
int lstcon_batch_debug (int timeout, char * name, int client, struct list_head __user * result_up)
Definition at line 1616 of file console.c.
References lstcon_batch_t::bat_cli_list, lstcon_batch_t::bat_srv_list, lstcon_batch_find(), and lstcon_debug_ndlist().
Referenced by lst_debug_ioctl().
int lstcon_batch_del (char * name)
int lstcon_batch_info (char * name, lstcon_test_batch_ent_t __user * ent_up, int server, int testidx, int * index_p, int * ndent_p, lstcon_node_ent_t __user * dents_up)
Definition at line 930 of file console.c.
References lstcon_batch_ent_t::bae_ntest, lstcon_batch_ent_t::bae_state, lstcon_batch_t::bat_cli_list, lstcon_batch_t::bat_ntest, lstcon_batch_t::bat_srv_list, lstcon_batch_t::bat_state, lstcon_batch_t::bat_test_list, CDEBUG, D_NET, lstcon_group_t::grp_ndl_list, LIBCFS_ALLOC, LIBCFS_FREE, list_for_each_entry, LST_NODE_STATE_COUNTER, lstcon_batch_find(), lstcon_nodes_getent(), lstcon_ndlink_t::ndl_node, lstcon_test_batch_ent_t::tbe_batch, lstcon_test_batch_ent_t::tbe_cli_nle, lstcon_test_batch_ent_t::tbe_srv_nle, lstcon_test_batch_ent_t::tbe_test, lstcon_test::tes_concur, lstcon_test::tes_dst_grp, lstcon_test::tes_loop, lstcon_test::tes_src_grp, lstcon_test::tes_type, test(), lstcon_test_ent_t::tse_concur, lstcon_test_ent_t::tse_loop, lstcon_test_ent_t::tse_type, and lstcon_test_batch_ent_t::u.
Referenced by lst_batch_info_ioctl().
int lstcon_batch_list (int idx, int namelen, char __user * name_up)
Definition at line 912 of file console.c.
References lstcon_batch_t::bat_name, LASSERT, list_for_each_entry, and lstcon_session_t::ses_bat_list.
Referenced by lst_batch_list_ioctl().
int lstcon_batch_run (char * name, int timeout, struct list_head __user * result_up)
Definition at line 1049 of file console.c.
References lstcon_batch_t::bat_arg, lstcon_batch_t::bat_state, CDEBUG, D_NET, LST_BATCH_RUNNING, LST_TRANS_TSBRUN, lstcon_batch_find(), lstcon_batch_op(), lstcon_trans_stat(), and lstcon_tsbop_stat_success().
Referenced by lst_batch_run_ioctl().
int lstcon_batch_stop (char * name, int force, struct list_head __user * result_up)
Definition at line 1071 of file console.c.
References lstcon_batch_t::bat_arg, lstcon_batch_t::bat_state, CDEBUG, D_NET, LST_BATCH_IDLE, LST_TRANS_TSBSTOP, lstcon_batch_find(), lstcon_batch_op(), lstcon_trans_stat(), and lstcon_tsbop_stat_failure().
Referenced by lst_batch_stop_ioctl().
int lstcon_console_fini (void)
Definition at line 2082 of file console.c.
References LASSERT, libcfs_deregister_ioctl(), LIBCFS_FREE, list_empty(), LST_GLOBAL_HASHSIZE, LST_NODE_HASHSIZE, LST_SESSION_NONE, lstcon_rpc_module_fini(), lstcon_session_end(), lstcon_session_t::ses_bat_list, lstcon_session_t::ses_grp_list, lstcon_session_t::ses_mutex, lstcon_session_t::ses_ndl_hash, lstcon_session_t::ses_ndl_list, lstcon_session_t::ses_state, lstcon_session_t::ses_trans_list, srpc_remove_service(), srpc_shutdown_service(), and srpc_wait_service_shutdown().
Referenced by lnet_selftest_exit().
int lstcon_console_init (void)
Definition at line 2012 of file console.c.
References cfs_time_current_sec(), INIT_LIST_HEAD, LASSERT, LIBCFS_ALLOC, LIBCFS_FREE, libcfs_register_ioctl(), LST_FEATS_MASK, LST_GLOBAL_HASHSIZE, LST_INVALID_SID, LST_SESSION_NONE, lstcon_init_acceptor_service(), lstcon_rpc_module_init(), lstcon_session_t::ses_bat_list, lstcon_session_t::ses_expired, lstcon_session_t::ses_feats_updated, lstcon_session_t::ses_features, lstcon_session_t::ses_force, lstcon_session_t::ses_grp_list, lstcon_session_t::ses_id, lstcon_session_t::ses_laststamp, lstcon_session_t::ses_mutex, lstcon_session_t::ses_ndl_hash, lstcon_session_t::ses_ndl_list, lstcon_session_t::ses_state, lstcon_session_t::ses_timeout, lstcon_session_t::ses_trans_list, srpc_add_service(), srpc_remove_service(), srpc_service_add_buffers(), srpc_shutdown_service(), srpc_wait_service_shutdown(), and srpc_service::sv_wi_total.
Referenced by lnet_selftest_init().
int lstcon_group_add (char * name)
Definition at line 525 of file console.c.
References CERROR, lstcon_group_t::grp_link, list_add_tail(), lstcon_group_alloc(), lstcon_group_decref(), lstcon_group_find(), and lstcon_session_t::ses_grp_list.
Referenced by lst_group_add_ioctl().
int lstcon_group_clean (char * name, int args)
Definition at line 621 of file console.c.
References CDEBUG, D_NET, lstcon_group_t::grp_ndl_list, lstcon_group_t::grp_ref, list_empty(), LST_NODE_ACTIVE, LST_NODE_BUSY, LST_NODE_DOWN, LST_NODE_UNKNOWN, lstcon_group_decref(), lstcon_group_drain(), and lstcon_group_find().
Referenced by lst_group_update_ioctl().
int lstcon_group_debug (int timeout, char * name, struct list_head __user * result_up)
Definition at line 1634 of file console.c.
References lstcon_group_t::grp_ndl_list, lstcon_debug_ndlist(), lstcon_group_decref(), and lstcon_group_find().
Referenced by lst_debug_ioctl().
int lstcon_group_del (char * name)
Definition at line 580 of file console.c.
References CDEBUG, CERROR, D_NET, lstcon_group_t::grp_ndl_list, lstcon_group_t::grp_ref, lstcon_group_t::grp_trans_list, LST_TRANS_SESEND, LST_TRANS_TIMEOUT, lstcon_group_decref(), lstcon_group_find(), lstcon_rpc_trans_destroy(), lstcon_rpc_trans_ndlist(), lstcon_rpc_trans_postwait(), and lstcon_sesrpc_condition().
Referenced by lst_group_del_ioctl().
int lstcon_group_info (char * name, lstcon_ndlist_ent_t __user * gent_up, int * index_p, int * ndent_p, lstcon_node_ent_t __user * ndents_up)
Definition at line 784 of file console.c.
References CDEBUG, CERROR, D_NET, lstcon_group_t::grp_ndl_list, LIBCFS_ALLOC, LIBCFS_FREE, list_for_each_entry, LST_NODE_STATE_COUNTER, lstcon_group_decref(), lstcon_group_find(), lstcon_nodes_getent(), and lstcon_ndlink_t::ndl_node.
Referenced by lst_group_info_ioctl().
int lstcon_group_list (int idx, int len, char __user * name_up)
Definition at line 726 of file console.c.
References lstcon_group_t::grp_name, LASSERT, list_for_each_entry, and lstcon_session_t::ses_grp_list.
Referenced by lst_group_list_ioctl().
int lstcon_group_refresh (char * name, struct list_head __user * result_up)
Definition at line 684 of file console.c.
References CDEBUG, D_NET, lstcon_group_t::grp_ndl_list, lstcon_group_t::grp_ref, lstcon_group_t::grp_trans_list, LST_TRANS_SESNEW, LST_TRANS_TIMEOUT, lstcon_group_decref(), lstcon_group_find(), lstcon_rpc_trans_destroy(), lstcon_rpc_trans_interpreter(), lstcon_rpc_trans_ndlist(), lstcon_rpc_trans_postwait(), and lstcon_sesrpc_condition().
Referenced by lst_group_update_ioctl().
int lstcon_group_stat (char * grp_name, int timeout, struct list_head __user * result_up)
Definition at line 1521 of file console.c.
References CDEBUG, D_NET, lstcon_group_t::grp_ndl_list, lstcon_group_decref(), lstcon_group_find(), and lstcon_ndlist_stat().
Referenced by lst_stat_query_ioctl().
static struct list_head* lstcon_id2hash (lnet_process_id_t id, struct list_head * hash) [static, read]
Definition at line 193 of file console.h.
References LNET_NIDADDR(), and LST_NODE_HASHSIZE.
int lstcon_nodes_add (char * name, int nnd, lnet_process_id_t __user * nds_up, unsigned * featp, struct list_head __user * result_up)
Definition at line 549 of file console.c.
References CDEBUG, D_NET, lstcon_group_t::grp_ref, LASSERT, lstcon_group_decref(), lstcon_group_find(), and lstcon_group_nodes_add().
Referenced by lst_nodes_add_ioctl().
int lstcon_nodes_debug (int timeout, int nnd, lnet_process_id_t __user * nds_up, struct list_head __user * result_up)
Definition at line 1652 of file console.c.
References CDEBUG, CERROR, D_NET, lstcon_group_t::grp_ndl_list, lstcon_debug_ndlist(), lstcon_group_alloc(), lstcon_group_decref(), and lstcon_group_ndlink_find().
Referenced by lst_debug_ioctl().
int lstcon_nodes_remove (char * name, int nnd, lnet_process_id_t __user * nds_up, struct list_head __user * result_up)
Definition at line 653 of file console.c.
References CDEBUG, D_NET, lstcon_group_t::grp_ndl_list, lstcon_group_t::grp_ref, list_empty(), lstcon_group_decref(), lstcon_group_find(), and lstcon_group_nodes_remove().
Referenced by lst_group_update_ioctl().
int lstcon_nodes_stat (int count, lnet_process_id_t __user * ids_up, int timeout, struct list_head __user * result_up)
Definition at line 1541 of file console.c.
References CDEBUG, CERROR, D_ERROR, D_NET, lstcon_group_t::grp_ndl_list, libcfs_id2str(), lstcon_group_alloc(), lstcon_group_decref(), lstcon_group_ndlink_find(), and lstcon_ndlist_stat().
Referenced by lst_stat_query_ioctl().
int lstcon_session_debug (int timeout, struct list_head __user * result_up)
Definition at line 1609 of file console.c.
References lstcon_debug_ndlist(), and lstcon_session_t::ses_ndl_list.
Referenced by lst_debug_ioctl().
int lstcon_session_end (void)
Definition at line 1819 of file console.c.
References CERROR, lstcon_group_t::grp_ref, LASSERT, list_empty(), list_entry, LST_INVALID_SID, LST_SESSION_ACTIVE, LST_SESSION_NONE, LST_TRANS_SESEND, LST_TRANS_TIMEOUT, lstcon_batch_destroy(), lstcon_group_decref(), lstcon_rpc_cleanup_wait(), lstcon_rpc_pinger_stop(), lstcon_rpc_trans_destroy(), lstcon_rpc_trans_ndlist(), lstcon_rpc_trans_postwait(), lstcon_sesrpc_condition(), list_head::next, lstcon_session_t::ses_bat_list, lstcon_session_t::ses_expired, lstcon_session_t::ses_feats_updated, lstcon_session_t::ses_force, lstcon_session_t::ses_grp_list, lstcon_session_t::ses_id, lstcon_session_t::ses_key, lstcon_session_t::ses_ndl_list, lstcon_session_t::ses_shutdown, and lstcon_session_t::ses_state.
Referenced by lst_session_end_ioctl(), lstcon_console_fini(), lstcon_ioctl_entry(), and lstcon_session_new().
int lstcon_session_feats_check (unsigned feats)
Definition at line 1881 of file console.c.
References CERROR, LST_FEATS_MASK, lstcon_session_t::ses_feats_updated, lstcon_session_t::ses_features, and lstcon_session_t::ses_rpc_lock.
Referenced by lstcon_acceptor_handle(), and lstcon_rpc_trans_stat().
int lstcon_session_info (lst_sid_t __user * sid_up, int __user * key, unsigned __user * verp, lstcon_ndlist_ent_t __user * entp, char __user * name_up, int len)
Definition at line 1784 of file console.c.
References LIBCFS_ALLOC, LIBCFS_FREE, list_for_each_entry, LST_NODE_STATE_COUNTER, LST_SESSION_ACTIVE, lstcon_ndlink_t::ndl_node, lstcon_session_t::ses_features, lstcon_session_t::ses_id, lstcon_session_t::ses_key, lstcon_session_t::ses_name, lstcon_session_t::ses_ndl_list, and lstcon_session_t::ses_state.
Referenced by lst_session_info_ioctl().
int lstcon_session_match (lst_sid_t sid)
Definition at line 1696 of file console.c.
References lstcon_session_t::ses_id, lst_sid_t::ses_nid, and lst_sid_t::ses_stamp.
Referenced by lstcon_acceptor_handle(), lstcon_rpc_get_reply(), and lstcon_rpc_stat_reply().
int lstcon_session_new (char * name, int key, unsigned version, int timeout, int flags, lst_sid_t __user * sid_up)
Definition at line 1715 of file console.c.
References CNETERR, LASSERT, list_empty(), LST_CONSOLE_TIMEOUT, LST_DEFAULT_BATCH, LST_FEATS_MASK, LST_GLOBAL_HASHSIZE, LST_SESSION_ACTIVE, LST_SESSION_NONE, lstcon_batch_add(), lstcon_batch_destroy(), lstcon_batch_find(), lstcon_new_session_id(), lstcon_rpc_pinger_start(), lstcon_session_end(), lstcon_session_t::ses_feats_updated, lstcon_session_t::ses_features, lstcon_session_t::ses_force, lstcon_session_t::ses_id, lstcon_session_t::ses_key, lstcon_session_t::ses_name, lstcon_session_t::ses_ndl_hash, lstcon_session_t::ses_state, lstcon_session_t::ses_timeout, and strlcpy().
Referenced by lst_session_new_ioctl().
int lstcon_test_add (char * batch_name, int type, int loop, int concur, int dist, int span, char * src_name, char * dst_name, void * param, int paramlen, int * retp, struct list_head __user * result_up)
Definition at line 1284 of file console.c.
References lstcon_batch_t::bat_hdr, lstcon_batch_t::bat_ntest, lstcon_batch_t::bat_test_list, CDEBUG, CERROR, D_NET, lstcon_group_t::grp_userland, INIT_LIST_HEAD, LIBCFS_ALLOC, LIBCFS_FREE, list_add_tail(), lstcon_group_decref(), lstcon_test_nodes_add(), lstcon_trans_stat(), lstcon_verify_batch(), lstcon_verify_group(), offsetof, lstcon_test::tes_batch, lstcon_test::tes_cliidx, lstcon_test::tes_concur, lstcon_test::tes_dist, lstcon_test::tes_dst_grp, lstcon_test::tes_hdr, lstcon_test::tes_link, lstcon_test::tes_loop, lstcon_test::tes_oneside, lstcon_test::tes_param, lstcon_test::tes_paramlen, lstcon_test::tes_span, lstcon_test::tes_src_grp, lstcon_test::tes_stop_onerr, lstcon_test::tes_trans_list, lstcon_test::tes_type, test(), lstcon_tsb_hdr::tsb_id, and lstcon_tsb_hdr::tsb_index.
Referenced by lst_test_add_ioctl().
int lstcon_test_batch_query (char * name, int testidx, int client, int timeout, struct list_head __user * result_up)
Definition at line 1407 of file console.c.
References lstcon_batch_t::bat_cli_list, lstcon_batch_t::bat_hdr, lstcon_batch_t::bat_state, lstcon_batch_t::bat_trans_list, CDEBUG, CERROR, D_NET, lstcon_group_t::grp_ndl_list, LST_BATCH_IDLE, LST_TRANS_TSBCLIQRY, LST_TRANS_TSBSRVQRY, lstcon_batch_find(), lstcon_batrpc_condition(), lstcon_rpc_stat_failure(), lstcon_rpc_trans_destroy(), lstcon_rpc_trans_interpreter(), lstcon_rpc_trans_ndlist(), lstcon_rpc_trans_postwait(), lstcon_test_find(), lstcon_trans_stat(), lstcon_tsbqry_stat_run(), lstcon_tsbrpc_readent(), lstcon_test::tes_hdr, lstcon_test::tes_src_grp, lstcon_test::tes_trans_list, and test().
Referenced by lst_batch_query_ioctl().
static lstcon_trans_stat_t* lstcon_trans_stat (void) [inline, static]
Definition at line 187 of file console.h.
References lstcon_session_t::ses_trans_stat.
Referenced by lstcon_batch_run(), lstcon_batch_stop(), lstcon_rpc_pinger_stop(), lstcon_rpc_trans_postwait(), lstcon_test_add(), lstcon_test_batch_query(), and lstcon_test_nodes_add().
Variable Documentation
lstcon_session_t console_session
Definition at line 62 of file console.c.
Referenced by lst_batch_add_ioctl(), lst_batch_info_ioctl(), lst_batch_list_ioctl(), lst_batch_query_ioctl(), lst_batch_run_ioctl(), lst_batch_stop_ioctl(), lst_debug_ioctl(), lst_group_add_ioctl(), lst_group_del_ioctl(), lst_group_info_ioctl(), lst_group_list_ioctl(), lst_group_update_ioctl(), lst_nodes_add_ioctl(), lst_session_end_ioctl(), lst_stat_query_ioctl(), lstcon_batrpc_prep(), lstcon_dbgrpc_prep(), lstcon_ioctl_entry(), lstcon_rpc_cleanup_wait(), lstcon_rpc_init(), lstcon_rpc_module_fini(), lstcon_rpc_module_init(), lstcon_rpc_pinger(), lstcon_rpc_pinger_start(), lstcon_rpc_pinger_stop(), lstcon_rpc_prep(), lstcon_rpc_put(), lstcon_rpc_trans_check(), lstcon_rpc_trans_interpreter(), lstcon_rpc_trans_postwait(), lstcon_rpc_trans_prep(), lstcon_sesnew_stat_reply(), lstcon_sesrpc_prep(), lstcon_statrpc_prep(), and lstcon_testrpc_prep().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.