Lustre: lustre/utils/gss/context.h File Reference
lustre/utils/gss/context.h File Reference
#include <krb5.h>
Defines
#define MAX_CTX_LEN 4096
#define KRB5_CTX_FLAG_INITIATOR 0x00000001
#define KRB5_CTX_FLAG_CFX 0x00000002
#define KRB5_CTX_FLAG_ACCEPTOR_SUBKEY 0x00000004
Functions
krb5_error_code krb5_derive_key (const void *enc, const krb5_keyblock *inkey, krb5_keyblock *outkey, const krb5_data *in_constant)
int serialize_context_for_kernel (gss_ctx_id_t ctx, gss_buffer_desc *buf, gss_OID mech)
int serialize_spkm3_ctx (gss_ctx_id_t ctx, gss_buffer_desc *buf)
int serialize_krb5_ctx (gss_ctx_id_t ctx, gss_buffer_desc *buf)
Define Documentation
#define KRB5_CTX_FLAG_ACCEPTOR_SUBKEY 0x00000004
Definition at line 42 of file context.h.
#define KRB5_CTX_FLAG_CFX 0x00000002
Definition at line 41 of file context.h.
#define KRB5_CTX_FLAG_INITIATOR 0x00000001
Definition at line 40 of file context.h.
#define MAX_CTX_LEN 4096
Definition at line 37 of file context.h.
Function Documentation
krb5_error_code krb5_derive_key (const void * enc, const krb5_keyblock * inkey, krb5_keyblock * outkey, const krb5_data * in_constant)
int serialize_context_for_kernel (gss_ctx_id_t ctx, gss_buffer_desc * buf, gss_OID mech)
Definition at line 47 of file context.c.
References g_OID_equal, krb5oid, printerr, serialize_krb5_ctx(), serialize_spkm3_ctx(), and spkm3oid.
Referenced by handle_krb5_upcall(), handle_nullreq(), handle_spkm3_upcall(), and lgssc_kr_negotiate().
int serialize_krb5_ctx (gss_ctx_id_t ctx, gss_buffer_desc * buf)
Referenced by serialize_context_for_kernel().
int serialize_spkm3_ctx (gss_ctx_id_t ctx, gss_buffer_desc * buf)
Referenced by serialize_context_for_kernel().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.