Lustre: lustre/utils/gss/context.c File Reference
lustre/utils/gss/context.c File Reference
#include "config.h"
#include <stdio.h>
#include <syslog.h>
#include <string.h>
#include <gssapi/gssapi.h>
#include "gss_util.h"
#include "gss_oids.h"
#include "err_util.h"
#include "context.h"
Functions
int serialize_context_for_kernel (gss_ctx_id_t ctx, gss_buffer_desc *buf, gss_OID mech)
Function Documentation
int serialize_context_for_kernel (gss_ctx_id_t ctx, gss_buffer_desc * buf, gss_OID mech)
Definition at line 47 of file context.c.
References g_OID_equal, krb5oid, printerr, serialize_krb5_ctx(), serialize_spkm3_ctx(), and spkm3oid.
Referenced by handle_krb5_upcall(), handle_nullreq(), handle_spkm3_upcall(), and lgssc_kr_negotiate().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.