Lustre: lustre/utils/create_iam.c File Reference
lustre/utils/create_iam.c File Reference
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <fcntl.h>
#include <string.h>
#include <errno.h>
#include <sys/types.h>
Data Structures
struct iam_lfix_root
struct iam_leaf_head
struct dx_countlimit
struct lvar_leaf_header
struct lvar_root
struct lvar_leaf_entry
Defines
#define STORE_UNALIGNED(val, dst)
Stores val at dst, where the latter is possibly unaligned.
Typedefs
typedef __u32 lvar_hash_t
Enumerations
enum { IAM_LFIX_ROOT_MAGIC = 0xbedabb1edULL, IAM_LVAR_ROOT_MAGIC = 0xb01dface }
enum { IAM_LEAF_HEADER_MAGIC = 0x1976, IAM_LVAR_LEAF_MAGIC = 0x1973 }
enum { LVAR_PAD = 4, LVAR_ROUND = LVAR_PAD - 1 }
enum iam_fmt_t { FMT_LFIX, FMT_LVAR, FMT_LFIX, FMT_LVAR }
Functions
void usage (void)
static void lfix_root (void *buf, int blocksize, int keysize, int ptrsize, int recsize)
static void lfix_leaf (void *buf, int blocksize, int keysize, int ptrsize, int recsize)
static void lvar_root (void *buf, int blocksize, int keysize, int ptrsize, int recsize)
static int lvar_esize (int namelen, int recsize)
static void lvar_leaf (void *buf, int blocksize, int keysize, int ptrsize, int recsize)
int main (int argc, char **argv)
Define Documentation
#define STORE_UNALIGNED (val, dst)
Value:
({                                                      \
        typeof(val) __val = (val);                      \
                                                        \
        CLASSERT(sizeof(val) == sizeof(*(dst)));        \
        memcpy(dst, &__val, sizeof(*(dst)));            \
})
Stores val at dst, where the latter is possibly unaligned.
Uses memcpy(). This macro is needed to avoid dependency of user level tools on the kernel headers.
Definition at line 121 of file create_iam.c.
Typedef Documentation
typedef __u32 lvar_hash_t
Definition at line 89 of file create_iam.c.
Enumeration Type Documentation
anonymous enum
Enumerator:
IAM_LFIX_ROOT_MAGIC
IAM_LVAR_ROOT_MAGIC
Definition at line 61 of file create_iam.c.
anonymous enum
Enumerator:
IAM_LEAF_HEADER_MAGIC
IAM_LVAR_LEAF_MAGIC
Definition at line 74 of file create_iam.c.
anonymous enum
Enumerator:
LVAR_PAD
LVAR_ROUND
Definition at line 111 of file create_iam.c.
enum iam_fmt_t
Enumerator:
FMT_LFIX
FMT_LVAR
FMT_LFIX
FMT_LVAR
Definition at line 258 of file create_iam.c.
Function Documentation
static void lfix_leaf (void * buf, int blocksize, int keysize, int ptrsize, int recsize) [static]
Definition at line 175 of file create_iam.c.
References cpu_to_le16, head, IAM_LEAF_HEADER_MAGIC, and iam_leaf_head::ill_magic.
Referenced by main().
static void lfix_root (void * buf, int blocksize, int keysize, int ptrsize, int recsize) [static]
Definition at line 129 of file create_iam.c.
References dx_countlimit::count, cpu_to_le16, cpu_to_le32, cpu_to_le64, IAM_LFIX_ROOT_MAGIC, iam_lfix_root::ilr_magic, dx_countlimit::limit, and STORE_UNALIGNED.
Referenced by main().
static int lvar_esize (int namelen, int recsize) [static]
Definition at line 239 of file create_iam.c.
References LVAR_ROUND, and offsetof.
Referenced by lvar_leaf().
static void lvar_leaf (void * buf, int blocksize, int keysize, int ptrsize, int recsize) [static]
Definition at line 245 of file create_iam.c.
References cpu_to_le16, head, IAM_LVAR_LEAF_MAGIC, lvar_esize(), and lvar_leaf_header::vlh_magic.
Referenced by main().
static void lvar_root (void * buf, int blocksize, int keysize, int ptrsize, int recsize) [static]
Definition at line 192 of file create_iam.c.
References dx_countlimit::count, cpu_to_le16, cpu_to_le32, cpu_to_le64, IAM_LVAR_ROOT_MAGIC, dx_countlimit::limit, STORE_UNALIGNED, and lvar_root::vr_magic.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 263 of file create_iam.c.
References FMT_LFIX, FMT_LVAR, lfix_leaf(), lfix_root(), lvar_leaf(), lvar_root(), opt, optarg, usage, and verbose.
void usage (void)
Definition at line 55 of file create_iam.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.