Lustre: lustre/tests/createmany.c File Reference
lustre/tests/createmany.c File Reference
#include <stdio.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <time.h>
#include <errno.h>
#include <string.h>
#include <fcntl.h>
#include <unistd.h>
#include <stdlib.h>
#include <getopt.h>
Functions
static void usage (char *prog)
static char * get_file_name (const char *fmt, long n, int has_fmt_spec)
double now (void)
int main (int argc, char **argv)
Function Documentation
static char* get_file_name (const char * fmt, long n, int has_fmt_spec) [static]
Definition at line 55 of file createmany.c.
References filename.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 76 of file createmany.c.
References begin, end, filename, get_file_name(), now(), optarg, optind, start, and usage.
double now (void)
Definition at line 69 of file createmany.c.
Referenced by __osd_attr_init(), after_reply(), at_measured(), ct_copy_data(), delay_rule_match(), delayed_msg_check(), do_stat(), drop_rule_match(), gss_pipe_destroy_msg(), gss_sec_display_kr(), gssd_get_single_krb5_cred(), handler(), jt_dbg_mark_debug_buf(), jt_lst_query_batch(), jt_lst_stat(), kgnilnd_check_conn_timeouts_locked(), kgnilnd_check_fma_rx(), kgnilnd_reaper_dgram_check(), kgnilnd_sendmsg_nolock(), kgnilnd_tx_should_retry(), kiblnd_fmr_pool_unmap(), kiblnd_pool_free_node(), kiblnd_query(), ksocknal_connd_get_route_locked(), ksocknal_find_connectable_route_locked(), ksocknal_query(), lkrb5_check_root_tgt_cc_base(), lnet_eq_wait_locked(), lnet_notify(), lnet_peer_alive_locked(), lnet_ping_router_locked(), lnet_update_ni_status_locked(), lod_qos_calc_ppo(), main(), mdt_coordinator_cb(), ofd_fmd_expire_nolock(), ofd_fmd_find_nolock(), ofd_fmd_get(), osd_oii_insert(), proc_lnet_nis(), proc_lnet_peers(), proc_lnet_routers(), ptlrpc_at_adj_net_latency(), ptlrpc_at_check_timed(), ptlrpc_expired_set(), ptlrpc_inflight_timeout(), ptlrpc_init_xid(), ptlrpc_set_next_timeout(), qmt_dqacq0(), qmt_set(), rvs_sec_install_root_ctx_kr(), show_rate(), sptlrpc_enc_pool_get_pages(), and stt_check_timers().
static void usage (char * prog) [static]
Definition at line 47 of file createmany.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.