Lustre: libcfs/include/libcfs/curproc.h File Reference
libcfs/include/libcfs/curproc.h File Reference
Defines
#define INVALID_UID -1
#define INVALID_GID -1
#define GLOBAL_ROOT_UID 0
#define GLOBAL_ROOT_GID 0
#define CFS_CAP_CHOWN 0
#define CFS_CAP_DAC_OVERRIDE 1
#define CFS_CAP_DAC_READ_SEARCH 2
#define CFS_CAP_FOWNER 3
#define CFS_CAP_FSETID 4
#define CFS_CAP_LINUX_IMMUTABLE 9
#define CFS_CAP_SYS_ADMIN 21
#define CFS_CAP_SYS_BOOT 23
#define CFS_CAP_SYS_RESOURCE 24
#define CFS_CAP_FS_MASK
Typedefs
typedef uid_t kuid_t
typedef gid_t kgid_t
typedef __u32 cfs_cap_t
Functions
static uid_t __kuid_val (kuid_t uid)
static gid_t __kgid_val (kgid_t gid)
static kuid_t make_kuid (struct user_namespace *from, uid_t uid)
static kgid_t make_kgid (struct user_namespace *from, gid_t gid)
static uid_t from_kuid (struct user_namespace *to, kuid_t uid)
static gid_t from_kgid (struct user_namespace *to, kgid_t gid)
static bool uid_eq (kuid_t left, kuid_t right)
static bool uid_valid (kuid_t uid)
static bool gid_valid (kgid_t gid)
int cfs_get_environ (const char *key, char *value, int *val_len)
void cfs_cap_raise (cfs_cap_t cap)
void cfs_cap_lower (cfs_cap_t cap)
int cfs_cap_raised (cfs_cap_t cap)
cfs_cap_t cfs_curproc_cap_pack (void)
void cfs_curproc_cap_unpack (cfs_cap_t cap)
int cfs_capable (cfs_cap_t cap)
Define Documentation
#define CFS_CAP_CHOWN 0
Definition at line 112 of file curproc.h.
Referenced by mdd_fix_attr().
#define CFS_CAP_DAC_OVERRIDE 1
Definition at line 113 of file curproc.h.
Referenced by __mdd_permission_internal(), and mdt_orphan_open().
#define CFS_CAP_DAC_READ_SEARCH 2
Definition at line 114 of file curproc.h.
Referenced by __mdd_permission_internal(), ll_fid2path(), and ll_getparent().
#define CFS_CAP_FOWNER 3
Definition at line 115 of file curproc.h.
Referenced by ll_setattr_raw(), mdd_fix_attr(), mdd_is_sticky(), mdd_open_sanity_check(), mdd_permission(), and mdd_xattr_sanity_check().
#define CFS_CAP_FS_MASK
Value:
((1 << CFS_CAP_CHOWN) |                 \
                         (1 << CFS_CAP_DAC_OVERRIDE) |          \
                         (1 << CFS_CAP_DAC_READ_SEARCH) |       \
                         (1 << CFS_CAP_FOWNER) |                \
                         (1 << CFS_CAP_FSETID ) |               \
                         (1 << CFS_CAP_LINUX_IMMUTABLE) |       \
                         (1 << CFS_CAP_SYS_ADMIN) |             \
                         (1 << CFS_CAP_SYS_BOOT) |              \
                         (1 << CFS_CAP_SYS_RESOURCE))
Definition at line 122 of file curproc.h.
Referenced by hsm_init_ucred(), ll_inode_permission(), new_init_ucred(), and old_init_ucred_common().
#define CFS_CAP_FSETID 4
Definition at line 116 of file curproc.h.
Referenced by mdd_fix_attr().
#define CFS_CAP_LINUX_IMMUTABLE 9
Definition at line 117 of file curproc.h.
Referenced by mdd_fix_attr().
#define CFS_CAP_SYS_ADMIN 21
Definition at line 118 of file curproc.h.
Referenced by echo_client_iocontrol(), hsm_action_permission(), ll_dir_ioctl(), ll_hsm_state_set(), ll_lov_setea(), mdt_hsm_add_actions(), mdt_hsm_is_admin(), mdt_hsm_state_set(), mdt_reint_setxattr(), mdt_reint_unlink(), mdt_remote_permission_check(), obd_class_ioctl(), quotactl_ioctl(), and xattr_type_filter().
#define CFS_CAP_SYS_BOOT 23
Definition at line 119 of file curproc.h.
#define CFS_CAP_SYS_RESOURCE 24
Definition at line 120 of file curproc.h.
Referenced by llog_add(), llog_create(), llog_declare_add(), llog_declare_create(), llog_declare_write_rec(), llog_open(), llog_write_rec(), and osc_page_submit().
#define GLOBAL_ROOT_GID 0
Definition at line 58 of file curproc.h.
#define GLOBAL_ROOT_UID 0
Definition at line 57 of file curproc.h.
Referenced by ll_inode_permission().
#define INVALID_GID -1
Definition at line 55 of file curproc.h.
Referenced by gid_valid(), and ll_i2suppgid().
#define INVALID_UID -1
Definition at line 54 of file curproc.h.
Referenced by uid_valid().
Typedef Documentation
typedef __u32 cfs_cap_t
Definition at line 110 of file curproc.h.
typedef gid_t kgid_t
Definition at line 52 of file curproc.h.
typedef uid_t kuid_t
Definition at line 51 of file curproc.h.
Function Documentation
static gid_t __kgid_val (kgid_t gid) [inline, static]
Definition at line 65 of file curproc.h.
Referenced by ll_i2suppgid(), and ll_inode_permission().
static uid_t __kuid_val (kuid_t uid) [inline, static]
Definition at line 60 of file curproc.h.
Referenced by ll_inode_permission().
void cfs_cap_lower (cfs_cap_t cap)
Definition at line 71 of file linux-curproc.c.
References cfs_cap_unpack.
Referenced by llog_add(), llog_create(), llog_declare_add(), llog_declare_create(), llog_declare_write_rec(), llog_open(), and llog_write_rec().
void cfs_cap_raise (cfs_cap_t cap)
Definition at line 62 of file linux-curproc.c.
References cfs_cap_unpack.
Referenced by llog_add(), llog_create(), llog_declare_add(), llog_declare_create(), llog_declare_write_rec(), llog_open(), and llog_write_rec().
int cfs_cap_raised (cfs_cap_t cap)
Definition at line 80 of file linux-curproc.c.
References cfs_cap_unpack.
Referenced by llog_add(), llog_create(), llog_declare_add(), llog_declare_create(), llog_declare_write_rec(), llog_open(), and llog_write_rec().
int cfs_capable (cfs_cap_t cap)
Definition at line 128 of file linux-curproc.c.
References cfs_cap_unpack.
Referenced by echo_client_iocontrol(), ll_dir_ioctl(), ll_fid2path(), ll_getparent(), ll_hsm_state_set(), ll_lov_setea(), ll_setattr_raw(), obd_class_ioctl(), osc_page_submit(), quotactl_ioctl(), and xattr_type_filter().
cfs_cap_t cfs_curproc_cap_pack (void)
Definition at line 112 of file linux-curproc.c.
References cfs_kernel_cap_pack().
Referenced by __mdc_pack_body(), ll_dir_setdirstripe(), ll_new_node(), ll_prep_md_op_data(), lmv_link(), lmv_rename(), lmv_unlink(), mdc_open_pack(), mdc_setattr_pack_rec(), mdc_xattr_common(), and sptlrpc_pack_user_desc().
void cfs_curproc_cap_unpack (cfs_cap_t cap)
Definition at line 119 of file linux-curproc.c.
References cfs_kernel_cap_unpack().
int cfs_get_environ (const char * key, char * value, int * val_len)
Definition at line 187 of file linux-curproc.c.
References cfs_access_process_vm(), ENTRY, GOTO, LASSERT, min_t, RETURN, and unlikely.
Referenced by lustre_get_jobid().
static gid_t from_kgid (struct user_namespace * to, kgid_t gid) [inline, static]
Definition at line 85 of file curproc.h.
Referenced by __mdc_pack_body(), do_check_remote_perm(), get_my_ctx(), ll_dir_setdirstripe(), ll_i2suppgid(), ll_new_node(), ll_prep_md_op_data(), lmv_link(), lmv_rename(), lmv_unlink(), lustre_groups_search(), lustre_groups_sort(), mdc_open_pack(), mdc_setattr_pack_rec(), mdc_xattr_common(), obdo_from_inode(), sptlrpc_pack_user_desc(), and vvp_attr_get().
static uid_t from_kuid (struct user_namespace * to, kuid_t uid) [inline, static]
Definition at line 80 of file curproc.h.
Referenced by __mdc_pack_body(), do_check_remote_perm(), get_my_ctx(), ll_dir_setdirstripe(), ll_flush_ctx(), ll_new_node(), ll_prep_md_op_data(), lmv_link(), lmv_rename(), lmv_unlink(), lustre_get_jobid(), mdc_open_pack(), mdc_setattr_pack_rec(), mdc_xattr_common(), obdo_from_inode(), sptlrpc_import_flush_my_ctx(), sptlrpc_pack_user_desc(), and vvp_attr_get().
static bool gid_valid (kgid_t gid) [inline, static]
Definition at line 100 of file curproc.h.
References INVALID_GID.
static kgid_t make_kgid (struct user_namespace * from, gid_t gid) [inline, static]
Definition at line 75 of file curproc.h.
Referenced by ll_hsm_import(), ll_inode_permission(), ll_lookup_it(), ll_update_inode(), lustre_groups_sort(), osd_quota_transfer(), quotactl_ioctl(), and vvp_attr_update().
static kuid_t make_kuid (struct user_namespace * from, uid_t uid) [inline, static]
Definition at line 70 of file curproc.h.
Referenced by ll_hsm_import(), ll_inode_permission(), ll_update_inode(), mdt_check_ucred(), mdt_handle_idmap(), new_init_ucred(), osd_quota_transfer(), quotactl_ioctl(), tgt_init_sec_level(), and vvp_attr_update().
static bool uid_eq (kuid_t left, kuid_t right) [inline, static]
Definition at line 90 of file curproc.h.
Referenced by ll_inode_permission(), ll_setattr_raw(), and quotactl_ioctl().
static bool uid_valid (kuid_t uid) [inline, static]
Definition at line 95 of file curproc.h.
References INVALID_UID.
Referenced by mdt_check_ucred(), mdt_handle_idmap(), new_init_ucred(), and tgt_init_sec_level().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.