Lustre: lnet/utils/cyaml/cyaml.h File Reference
lnet/utils/cyaml/cyaml.h File Reference
#include <stdbool.h>
Data Structures
struct cYAML
Typedefs
typedef void(* cYAML_user_data_free_cb)(void *)
typedef bool(* cYAML_walk_cb)(struct cYAML *, void *, void **)
Enumerations
enum cYAML_object_type {
CYAML_TYPE_FALSE = 0, CYAML_TYPE_TRUE, CYAML_TYPE_NULL, CYAML_TYPE_NUMBER,
CYAML_TYPE_STRING, CYAML_TYPE_ARRAY, CYAML_TYPE_OBJECT
}
Functions
struct cYAML * cYAML_build_tree (char *yaml_file, const char *yaml_blk, size_t yaml_blk_size, struct cYAML **err_str)
void cYAML_print_tree (struct cYAML *node)
void cYAML_print_tree2file (FILE *f, struct cYAML *node)
void cYAML_free_tree (struct cYAML *node)
struct cYAML * cYAML_get_object_item (struct cYAML *parent, const char *name)
struct cYAML * cYAML_get_next_seq_item (struct cYAML *seq, struct cYAML **itm)
bool cYAML_is_sequence (struct cYAML *node)
struct cYAML * cYAML_find_object (struct cYAML *root, const char *key)
void cYAML_clean_usr_data (struct cYAML *node, cYAML_user_data_free_cb free_cb)
struct cYAML * cYAML_create_object (struct cYAML *parent, char *key)
struct cYAML * cYAML_create_seq (struct cYAML *parent, char *key)
struct cYAML * cYAML_create_seq_item (struct cYAML *seq)
struct cYAML * cYAML_create_string (struct cYAML *parent, char *key, char *value)
struct cYAML * cYAML_create_number (struct cYAML *parent, char *key, double value)
void cYAML_insert_sibling (struct cYAML *root, struct cYAML *sibling)
void cYAML_insert_child (struct cYAML *parent, struct cYAML *node)
void cYAML_build_error (int rc, int seq_no, char *cmd, char *entity, char *err_str, struct cYAML **root)
Typedef Documentation
typedef void(* cYAML_user_data_free_cb)(void *)
Definition at line 64 of file cyaml.h.
typedef bool(* cYAML_walk_cb)(struct cYAML *, void *, void **)
Definition at line 76 of file cyaml.h.
Enumeration Type Documentation
enum cYAML_object_type
Enumerator:
CYAML_TYPE_FALSE
CYAML_TYPE_TRUE
CYAML_TYPE_NULL
CYAML_TYPE_NUMBER
CYAML_TYPE_STRING
CYAML_TYPE_ARRAY
CYAML_TYPE_OBJECT
Definition at line 32 of file cyaml.h.
Function Documentation
void cYAML_build_error (int rc, int seq_no, char * cmd, char * entity, char * err_str, struct cYAML ** root)
Definition at line 1047 of file cyaml.c.
References cYAML_create_number(), cYAML_create_object(), cYAML_create_seq(), cYAML_create_seq_item(), cYAML_create_string(), cYAML_free_tree(), cYAML_get_object_item(), and CYAML_TYPE_ARRAY.
Referenced by cYAML_build_tree(), jt_set_large(), jt_set_routing(), jt_set_small(), jt_set_tiny(), lustre_lnet_config_buffers(), lustre_lnet_config_net(), lustre_lnet_config_ni_system(), lustre_lnet_config_route(), lustre_lnet_del_net(), lustre_lnet_del_route(), lustre_lnet_enable_routing(), lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), lustre_lnet_show_route(), lustre_lnet_show_routing(), lustre_lnet_show_stats(), lustre_yaml_cb_helper(), and main().
struct cYAML* cYAML_build_tree (char * yaml_file, const char * yaml_blk, size_t yaml_blk_size, struct cYAML ** err_str) [read]
Definition at line 1097 of file cyaml.c.
References cYAML_build_error(), CYAML_ERROR_NONE, cYAML_free_tree(), dispatch_tbl, done, INIT_LIST_HEAD, cYAML_tree_node::ll, cYAML_tree_node::root, and cYAML_tree_node::state.
Referenced by lustre_yaml_cb_helper().
void cYAML_clean_usr_data (struct cYAML * node, cYAML_user_data_free_cb free_cb)
Definition at line 736 of file cyaml.c.
References clean_usr_data(), and cYAML_tree_recursive_walk().
struct cYAML* cYAML_create_number (struct cYAML * parent, char * key, double value) [read]
Definition at line 998 of file cyaml.c.
References cYAML::cy_string, cYAML::cy_type, cYAML::cy_valuedouble, cYAML::cy_valueint, cYAML_insert_child(), and CYAML_TYPE_NUMBER.
Referenced by cYAML_build_error(), lustre_ko2iblnd_show_net(), lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), lustre_lnet_show_route(), lustre_lnet_show_routing(), and lustre_lnet_show_stats().
struct cYAML* cYAML_create_object (struct cYAML * parent, char * key) [read]
Definition at line 978 of file cyaml.c.
References CYAML_TYPE_OBJECT, and insert_item().
Referenced by cYAML_build_error(), lustre_interface_show_net(), lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), lustre_lnet_show_route(), lustre_lnet_show_routing(), and lustre_lnet_show_stats().
struct cYAML* cYAML_create_seq (struct cYAML * parent, char * key) [read]
Definition at line 968 of file cyaml.c.
References CYAML_TYPE_ARRAY, and insert_item().
Referenced by cYAML_build_error(), lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), lustre_lnet_show_route(), and lustre_lnet_show_routing().
struct cYAML* cYAML_create_seq_item (struct cYAML * seq) [read]
Definition at line 973 of file cyaml.c.
References CYAML_TYPE_OBJECT, and insert_item().
Referenced by cYAML_build_error(), lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), lustre_lnet_show_route(), and lustre_lnet_show_routing().
struct cYAML* cYAML_create_string (struct cYAML * parent, char * key, char * value) [read]
Definition at line 983 of file cyaml.c.
References cYAML::cy_string, cYAML::cy_type, cYAML::cy_valuestring, cYAML_insert_child(), and CYAML_TYPE_STRING.
Referenced by cYAML_build_error(), lustre_interface_show_net(), lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), and lustre_lnet_show_route().
struct cYAML* cYAML_find_object (struct cYAML * root, const char * key) [read]
Definition at line 726 of file cyaml.c.
References cYAML_tree_recursive_walk(), and find_obj_iter().
void cYAML_free_tree (struct cYAML * node)
Definition at line 741 of file cyaml.c.
References cYAML_tree_recursive_walk(), and free_node().
Referenced by cYAML_build_error(), cYAML_build_tree(), jt_add_net(), jt_add_route(), jt_config_lnet(), jt_del_net(), jt_del_route(), jt_export(), jt_import(), jt_set_large(), jt_set_routing(), jt_set_small(), jt_set_tiny(), jt_show_net(), jt_show_peer_credits(), jt_show_route(), jt_show_routing(), jt_show_stats(), jt_unconfig_lnet(), lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), lustre_lnet_show_route(), lustre_lnet_show_routing(), lustre_lnet_show_stats(), and lustre_yaml_cb_helper().
struct cYAML* cYAML_get_next_seq_item (struct cYAML * seq, struct cYAML ** itm) [read]
Definition at line 679 of file cyaml.c.
References cYAML::cy_child, cYAML::cy_next, cYAML::cy_type, and CYAML_TYPE_ARRAY.
Referenced by lustre_yaml_cb_helper().
struct cYAML* cYAML_get_object_item (struct cYAML * parent, const char * name) [read]
Definition at line 662 of file cyaml.c.
References cYAML::cy_child, cYAML::cy_next, and cYAML::cy_string.
Referenced by cYAML_build_error(), handle_yaml_config_buffers(), handle_yaml_config_net(), handle_yaml_config_route(), handle_yaml_config_routing(), handle_yaml_del_net(), handle_yaml_del_route(), handle_yaml_del_routing(), handle_yaml_show_credits(), handle_yaml_show_net(), handle_yaml_show_route(), handle_yaml_show_routing(), handle_yaml_show_stats(), lustre_ko2iblnd_parse_net(), lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), lustre_lnet_show_route(), and lustre_lnet_show_routing().
void cYAML_insert_child (struct cYAML * parent, struct cYAML * node)
Definition at line 1014 of file cyaml.c.
References cYAML::cy_child, cYAML::cy_next, and cYAML::cy_prev.
Referenced by cYAML_create_number(), cYAML_create_string(), insert_item(), lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), and lustre_lnet_show_route().
void cYAML_insert_sibling (struct cYAML * root, struct cYAML * sibling)
Definition at line 1034 of file cyaml.c.
References cYAML::cy_next.
Referenced by lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), lustre_lnet_show_route(), lustre_lnet_show_routing(), and lustre_lnet_show_stats().
bool cYAML_is_sequence (struct cYAML * node)
Definition at line 694 of file cyaml.c.
References cYAML::cy_type, and CYAML_TYPE_ARRAY.
Referenced by lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), lustre_lnet_show_route(), and lustre_yaml_cb_helper().
void cYAML_print_tree (struct cYAML * node)
Definition at line 918 of file cyaml.c.
References cYAML_ll_push(), INIT_LIST_HEAD, and print_value().
Referenced by jt_import(), jt_show_net(), jt_show_peer_credits(), jt_show_route(), jt_show_routing(), jt_show_stats(), lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), lustre_lnet_show_route(), lustre_lnet_show_routing(), and lustre_lnet_show_stats().
void cYAML_print_tree2file (FILE * f, struct cYAML * node)
Definition at line 934 of file cyaml.c.
References cYAML_ll_push(), INIT_LIST_HEAD, and print_value().
Referenced by jt_add_net(), jt_add_route(), jt_config_lnet(), jt_del_net(), jt_del_route(), jt_export(), jt_import(), jt_set_large(), jt_set_routing(), jt_set_small(), jt_set_tiny(), jt_show_net(), jt_show_peer_credits(), jt_show_route(), jt_show_routing(), jt_show_stats(), jt_unconfig_lnet(), and main().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.