Lustre: lnet/utils/cyaml/cyaml.c File Reference
lnet/utils/cyaml/cyaml.c File Reference
#include <yaml.h>
#include <stdio.h>
#include <string.h>
#include <math.h>
#include <stdlib.h>
#include <float.h>
#include <limits.h>
#include <ctype.h>
#include "libcfs/list.h"
#include "cyaml.h"
Data Structures
struct cYAML_print_info
struct cYAML_ll
struct cYAML_tree_node
Defines
#define INDENT 4
#define EXTRA_IND 2
Enumerations
enum cYAML_handler_error {
CYAML_ERROR_NONE = 0, CYAML_ERROR_UNEXPECTED_STATE = -1, CYAML_ERROR_NOT_SUPPORTED = -2, CYAML_ERROR_OUT_OF_MEM = -3,
CYAML_ERROR_BAD_VALUE = -4, CYAML_ERROR_PARSE = -5
}
enum cYAML_tree_state {
TREE_STATE_COMPLETE = 0, TREE_STATE_INITED, TREE_STATE_TREE_STARTED, TREE_STATE_BLK_STARTED,
TREE_STATE_KEY, TREE_STATE_KEY_FILLED, TREE_STATE_VALUE, TREE_STATE_SEQ_START
}
Functions
static void print_value (FILE *f, struct list_head *stack)
static enum cYAML_handler_error yaml_parse_error (yaml_token_t *token, struct cYAML_tree_node *tree)
static enum cYAML_handler_error yaml_stream_start (yaml_token_t *token, struct cYAML_tree_node *tree)
static enum cYAML_handler_error yaml_stream_end (yaml_token_t *token, struct cYAML_tree_node *tree)
static enum cYAML_handler_error yaml_not_supported (yaml_token_t *token, struct cYAML_tree_node *tree)
static enum cYAML_handler_error yaml_document_start (yaml_token_t *token, struct cYAML_tree_node *tree)
static enum cYAML_handler_error yaml_document_end (yaml_token_t *token, struct cYAML_tree_node *tree)
static enum cYAML_handler_error yaml_blk_seq_start (yaml_token_t *token, struct cYAML_tree_node *tree)
static enum cYAML_handler_error yaml_blk_mapping_start (yaml_token_t *token, struct cYAML_tree_node *tree)
static enum cYAML_handler_error yaml_block_end (yaml_token_t *token, struct cYAML_tree_node *tree)
static enum cYAML_handler_error yaml_key (yaml_token_t *token, struct cYAML_tree_node *tree)
static enum cYAML_handler_error yaml_value (yaml_token_t *token, struct cYAML_tree_node *tree)
static enum cYAML_handler_error yaml_scalar (yaml_token_t *token, struct cYAML_tree_node *tree)
static enum cYAML_handler_error yaml_entry_token (yaml_token_t *token, struct cYAML_tree_node *tree)
static void cYAML_ll_free (struct list_head *ll)
static int cYAML_ll_push (struct cYAML *obj, const struct cYAML_print_info *print_info, struct list_head *list)
static struct cYAML * cYAML_ll_pop (struct list_head *list, struct cYAML_print_info **print_info)
static int cYAML_ll_count (struct list_head *ll)
static int cYAML_tree_init (struct cYAML_tree_node *tree)
static struct cYAML * create_child (struct cYAML *parent)
static struct cYAML * create_sibling (struct cYAML *sibling)
static bool parse_number (struct cYAML *item, const char *input)
static int assign_type_value (struct cYAML *obj, const char *value)
static bool clean_usr_data (struct cYAML *node, void *usr_data, void **out)
static bool free_node (struct cYAML *node, void *user_data, void **out)
static bool find_obj_iter (struct cYAML *node, void *usr_data, void **out)
struct cYAML * cYAML_get_object_item (struct cYAML *parent, const char *name)
struct cYAML * cYAML_get_next_seq_item (struct cYAML *seq, struct cYAML **itm)
bool cYAML_is_sequence (struct cYAML *node)
void cYAML_tree_recursive_walk (struct cYAML *node, cYAML_walk_cb cb, bool cb_first, void *usr_data, void **out)
struct cYAML * cYAML_find_object (struct cYAML *root, const char *name)
void cYAML_clean_usr_data (struct cYAML *node, cYAML_user_data_free_cb free_cb)
void cYAML_free_tree (struct cYAML *node)
static void print_simple (FILE *f, struct cYAML *node, struct cYAML_print_info *cpi)
static void print_string (FILE *f, struct cYAML *node, struct cYAML_print_info *cpi)
static void print_number (FILE *f, struct cYAML *node, struct cYAML_print_info *cpi)
static void print_object (FILE *f, struct cYAML *node, struct list_head *stack, struct cYAML_print_info *cpi)
static void print_array (FILE *f, struct cYAML *node, struct list_head *stack, struct cYAML_print_info *cpi)
void cYAML_print_tree (struct cYAML *node)
void cYAML_print_tree2file (FILE *f, struct cYAML *node)
static struct cYAML * insert_item (struct cYAML *parent, char *key, enum cYAML_object_type type)
struct cYAML * cYAML_create_seq (struct cYAML *parent, char *key)
struct cYAML * cYAML_create_seq_item (struct cYAML *seq)
struct cYAML * cYAML_create_object (struct cYAML *parent, char *key)
struct cYAML * cYAML_create_string (struct cYAML *parent, char *key, char *value)
struct cYAML * cYAML_create_number (struct cYAML *parent, char *key, double value)
void cYAML_insert_child (struct cYAML *parent, struct cYAML *node)
void cYAML_insert_sibling (struct cYAML *root, struct cYAML *sibling)
void cYAML_build_error (int rc, int seq_no, char *cmd, char *entity, char *err_str, struct cYAML **root)
struct cYAML * cYAML_build_tree (char *yaml_file, const char *yaml_blk, size_t yaml_blk_size, struct cYAML **err_rc)
Variables
enum cYAML_handler_error(* yaml_token_handler)(yaml_token_t *token, struct cYAML_tree_node *)
static yaml_token_handler dispatch_tbl []
Define Documentation
#define EXTRA_IND 2
Definition at line 51 of file cyaml.c.
Referenced by print_array(), and print_object().
#define INDENT 4
Definition at line 50 of file cyaml.c.
Referenced by print_array(), print_number(), print_object(), print_simple(), and print_string().
Enumeration Type Documentation
enum cYAML_handler_error
Enumerator:
CYAML_ERROR_NONE
CYAML_ERROR_UNEXPECTED_STATE
CYAML_ERROR_NOT_SUPPORTED
CYAML_ERROR_OUT_OF_MEM
CYAML_ERROR_BAD_VALUE
CYAML_ERROR_PARSE
Definition at line 77 of file cyaml.c.
enum cYAML_tree_state
Enumerator:
TREE_STATE_COMPLETE
TREE_STATE_INITED
TREE_STATE_TREE_STARTED
TREE_STATE_BLK_STARTED
TREE_STATE_KEY
TREE_STATE_KEY_FILLED
TREE_STATE_VALUE
TREE_STATE_SEQ_START
Definition at line 86 of file cyaml.c.
Function Documentation
static int assign_type_value (struct cYAML * obj, const char * value) [static]
Definition at line 360 of file cyaml.c.
References cYAML::cy_type, cYAML::cy_valueint, cYAML::cy_valuestring, CYAML_TYPE_FALSE, CYAML_TYPE_NULL, CYAML_TYPE_STRING, CYAML_TYPE_TRUE, and parse_number().
Referenced by yaml_scalar().
static bool clean_usr_data (struct cYAML * node, void * usr_data, void ** out) [static]
Definition at line 629 of file cyaml.c.
References cYAML::cy_user_data.
Referenced by cYAML_clean_usr_data().
static struct cYAML* create_child (struct cYAML * parent) [static, read]
Definition at line 264 of file cyaml.c.
References cYAML::cy_child, cYAML::cy_type, and CYAML_TYPE_OBJECT.
Referenced by yaml_blk_mapping_start(), and yaml_entry_token().
static struct cYAML* create_sibling (struct cYAML * sibling) [static, read]
Definition at line 283 of file cyaml.c.
References cYAML::cy_next, cYAML::cy_prev, cYAML::cy_type, and CYAML_TYPE_OBJECT.
Referenced by yaml_entry_token(), and yaml_key().
void cYAML_build_error (int rc, int seq_no, char * cmd, char * entity, char * err_str, struct cYAML ** root)
Definition at line 1047 of file cyaml.c.
References cYAML_create_number(), cYAML_create_object(), cYAML_create_seq(), cYAML_create_seq_item(), cYAML_create_string(), cYAML_free_tree(), cYAML_get_object_item(), and CYAML_TYPE_ARRAY.
Referenced by cYAML_build_tree(), jt_set_large(), jt_set_routing(), jt_set_small(), jt_set_tiny(), lustre_lnet_config_buffers(), lustre_lnet_config_net(), lustre_lnet_config_ni_system(), lustre_lnet_config_route(), lustre_lnet_del_net(), lustre_lnet_del_route(), lustre_lnet_enable_routing(), lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), lustre_lnet_show_route(), lustre_lnet_show_routing(), lustre_lnet_show_stats(), lustre_yaml_cb_helper(), and main().
struct cYAML* cYAML_build_tree (char * yaml_file, const char * yaml_blk, size_t yaml_blk_size, struct cYAML ** err_rc) [read]
Definition at line 1097 of file cyaml.c.
References cYAML_build_error(), CYAML_ERROR_NONE, cYAML_free_tree(), dispatch_tbl, done, INIT_LIST_HEAD, cYAML_tree_node::ll, cYAML_tree_node::root, and cYAML_tree_node::state.
Referenced by lustre_yaml_cb_helper().
void cYAML_clean_usr_data (struct cYAML * node, cYAML_user_data_free_cb free_cb)
Definition at line 736 of file cyaml.c.
References clean_usr_data(), and cYAML_tree_recursive_walk().
struct cYAML* cYAML_create_number (struct cYAML * parent, char * key, double value) [read]
Definition at line 998 of file cyaml.c.
References cYAML::cy_string, cYAML::cy_type, cYAML::cy_valuedouble, cYAML::cy_valueint, cYAML_insert_child(), and CYAML_TYPE_NUMBER.
Referenced by cYAML_build_error(), lustre_ko2iblnd_show_net(), lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), lustre_lnet_show_route(), lustre_lnet_show_routing(), and lustre_lnet_show_stats().
struct cYAML* cYAML_create_object (struct cYAML * parent, char * key) [read]
Definition at line 978 of file cyaml.c.
References CYAML_TYPE_OBJECT, and insert_item().
Referenced by cYAML_build_error(), lustre_interface_show_net(), lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), lustre_lnet_show_route(), lustre_lnet_show_routing(), and lustre_lnet_show_stats().
struct cYAML* cYAML_create_seq (struct cYAML * parent, char * key) [read]
Definition at line 968 of file cyaml.c.
References CYAML_TYPE_ARRAY, and insert_item().
Referenced by cYAML_build_error(), lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), lustre_lnet_show_route(), and lustre_lnet_show_routing().
struct cYAML* cYAML_create_seq_item (struct cYAML * seq) [read]
Definition at line 973 of file cyaml.c.
References CYAML_TYPE_OBJECT, and insert_item().
Referenced by cYAML_build_error(), lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), lustre_lnet_show_route(), and lustre_lnet_show_routing().
struct cYAML* cYAML_create_string (struct cYAML * parent, char * key, char * value) [read]
Definition at line 983 of file cyaml.c.
References cYAML::cy_string, cYAML::cy_type, cYAML::cy_valuestring, cYAML_insert_child(), and CYAML_TYPE_STRING.
Referenced by cYAML_build_error(), lustre_interface_show_net(), lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), and lustre_lnet_show_route().
struct cYAML* cYAML_find_object (struct cYAML * root, const char * name) [read]
Definition at line 726 of file cyaml.c.
References cYAML_tree_recursive_walk(), and find_obj_iter().
void cYAML_free_tree (struct cYAML * node)
Definition at line 741 of file cyaml.c.
References cYAML_tree_recursive_walk(), and free_node().
Referenced by cYAML_build_error(), cYAML_build_tree(), jt_add_net(), jt_add_route(), jt_config_lnet(), jt_del_net(), jt_del_route(), jt_export(), jt_import(), jt_set_large(), jt_set_routing(), jt_set_small(), jt_set_tiny(), jt_show_net(), jt_show_peer_credits(), jt_show_route(), jt_show_routing(), jt_show_stats(), jt_unconfig_lnet(), lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), lustre_lnet_show_route(), lustre_lnet_show_routing(), lustre_lnet_show_stats(), and lustre_yaml_cb_helper().
struct cYAML* cYAML_get_next_seq_item (struct cYAML * seq, struct cYAML ** itm) [read]
Definition at line 679 of file cyaml.c.
References cYAML::cy_child, cYAML::cy_next, cYAML::cy_type, and CYAML_TYPE_ARRAY.
Referenced by lustre_yaml_cb_helper().
struct cYAML* cYAML_get_object_item (struct cYAML * parent, const char * name) [read]
Definition at line 662 of file cyaml.c.
References cYAML::cy_child, cYAML::cy_next, and cYAML::cy_string.
Referenced by cYAML_build_error(), handle_yaml_config_buffers(), handle_yaml_config_net(), handle_yaml_config_route(), handle_yaml_config_routing(), handle_yaml_del_net(), handle_yaml_del_route(), handle_yaml_del_routing(), handle_yaml_show_credits(), handle_yaml_show_net(), handle_yaml_show_route(), handle_yaml_show_routing(), handle_yaml_show_stats(), lustre_ko2iblnd_parse_net(), lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), lustre_lnet_show_route(), and lustre_lnet_show_routing().
void cYAML_insert_child (struct cYAML * parent, struct cYAML * node)
Definition at line 1014 of file cyaml.c.
References cYAML::cy_child, cYAML::cy_next, and cYAML::cy_prev.
Referenced by cYAML_create_number(), cYAML_create_string(), insert_item(), lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), and lustre_lnet_show_route().
void cYAML_insert_sibling (struct cYAML * root, struct cYAML * sibling)
Definition at line 1034 of file cyaml.c.
References cYAML::cy_next.
Referenced by lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), lustre_lnet_show_route(), lustre_lnet_show_routing(), and lustre_lnet_show_stats().
bool cYAML_is_sequence (struct cYAML * node)
Definition at line 694 of file cyaml.c.
References cYAML::cy_type, and CYAML_TYPE_ARRAY.
Referenced by lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), lustre_lnet_show_route(), and lustre_yaml_cb_helper().
static int cYAML_ll_count (struct list_head * ll) [static]
Definition at line 220 of file cyaml.c.
References list_for_each.
Referenced by yaml_block_end().
static void cYAML_ll_free (struct list_head * ll) [static]
Definition at line 163 of file cyaml.c.
References list, list_for_each_entry_safe, and cYAML_ll::print_info.
Referenced by cYAML_tree_init().
static struct cYAML* cYAML_ll_pop (struct list_head * list, struct cYAML_print_info ** print_info) [static, read]
Definition at line 198 of file cyaml.c.
References cYAML_ll::list, list_del(), list_empty(), list_entry, list_head::next, cYAML_ll::obj, and cYAML_ll::print_info.
Referenced by print_value(), and yaml_block_end().
static int cYAML_ll_push (struct cYAML * obj, const struct cYAML_print_info * print_info, struct list_head * list) [static]
Definition at line 173 of file cyaml.c.
References INIT_LIST_HEAD, cYAML_ll::list, list_add(), cYAML_ll::obj, and cYAML_ll::print_info.
Referenced by cYAML_print_tree(), cYAML_print_tree2file(), print_array(), print_object(), yaml_blk_mapping_start(), and yaml_entry_token().
void cYAML_print_tree (struct cYAML * node)
Definition at line 918 of file cyaml.c.
References cYAML_ll_push(), INIT_LIST_HEAD, and print_value().
Referenced by jt_import(), jt_show_net(), jt_show_peer_credits(), jt_show_route(), jt_show_routing(), jt_show_stats(), lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), lustre_lnet_show_route(), lustre_lnet_show_routing(), and lustre_lnet_show_stats().
void cYAML_print_tree2file (FILE * f, struct cYAML * node)
Definition at line 934 of file cyaml.c.
References cYAML_ll_push(), INIT_LIST_HEAD, and print_value().
Referenced by jt_add_net(), jt_add_route(), jt_config_lnet(), jt_del_net(), jt_del_route(), jt_export(), jt_import(), jt_set_large(), jt_set_routing(), jt_set_small(), jt_set_tiny(), jt_show_net(), jt_show_peer_credits(), jt_show_route(), jt_show_routing(), jt_show_stats(), jt_unconfig_lnet(), and main().
static int cYAML_tree_init (struct cYAML_tree_node * tree) [static]
Definition at line 231 of file cyaml.c.
References cYAML_tree_node::cur, cYAML::cy_next, cYAML::cy_type, cYAML_ll_free(), CYAML_TYPE_OBJECT, list_empty(), cYAML_tree_node::ll, cYAML_tree_node::root, cYAML_tree_node::state, and TREE_STATE_COMPLETE.
Referenced by yaml_stream_start().
void cYAML_tree_recursive_walk (struct cYAML * node, cYAML_walk_cb cb, bool cb_first, void * usr_data, void ** out)
Definition at line 699 of file cyaml.c.
References cb(), cYAML::cy_child, and cYAML::cy_next.
Referenced by cYAML_clean_usr_data(), cYAML_find_object(), and cYAML_free_tree().
static bool find_obj_iter (struct cYAML * node, void * usr_data, void ** out) [static]
Definition at line 649 of file cyaml.c.
References cYAML::cy_string, and name.
Referenced by cYAML_find_object().
static bool free_node (struct cYAML * node, void * user_data, void ** out) [static]
Definition at line 641 of file cyaml.c.
Referenced by cYAML_free_tree().
static struct cYAML* insert_item (struct cYAML * parent, char * key, enum cYAML_object_type type) [static, read]
Definition at line 950 of file cyaml.c.
References cYAML::cy_string, cYAML::cy_type, and cYAML_insert_child().
Referenced by cYAML_create_object(), cYAML_create_seq(), and cYAML_create_seq_item().
static bool parse_number (struct cYAML * item, const char * input) [static]
Definition at line 305 of file cyaml.c.
References cYAML::cy_type, cYAML::cy_valuedouble, cYAML::cy_valueint, and CYAML_TYPE_NUMBER.
Referenced by assign_type_value().
static void print_array (FILE * f, struct cYAML * node, struct list_head * stack, struct cYAML_print_info * cpi) [static]
Definition at line 859 of file cyaml.c.
References cYAML_print_info::array_first_elem, cYAML::cy_child, cYAML::cy_next, cYAML::cy_string, cYAML_ll_push(), EXTRA_IND, cYAML_print_info::extra_ind, INDENT, cYAML_print_info::level, and print_value().
Referenced by print_value().
static void print_number (FILE * f, struct cYAML * node, struct cYAML_print_info * cpi) [static]
Definition at line 794 of file cyaml.c.
References cYAML_print_info::array_first_elem, cYAML::cy_string, cYAML::cy_valuedouble, cYAML::cy_valueint, cYAML_print_info::extra_ind, INDENT, and cYAML_print_info::level.
Referenced by print_value().
static void print_object (FILE * f, struct cYAML * node, struct list_head * stack, struct cYAML_print_info * cpi) [static]
Definition at line 829 of file cyaml.c.
References cYAML_print_info::array_first_elem, cYAML::cy_child, cYAML::cy_next, cYAML::cy_string, cYAML_ll_push(), EXTRA_IND, cYAML_print_info::extra_ind, INDENT, cYAML_print_info::level, and print_value().
Referenced by print_value().
static void print_simple (FILE * f, struct cYAML * node, struct cYAML_print_info * cpi) [inline, static]
Definition at line 746 of file cyaml.c.
References cYAML_print_info::array_first_elem, cYAML::cy_string, cYAML::cy_valueint, cYAML_print_info::extra_ind, INDENT, and cYAML_print_info::level.
Referenced by print_value().
static void print_string (FILE * f, struct cYAML * node, struct cYAML_print_info * cpi) [static]
Definition at line 760 of file cyaml.c.
References cYAML_print_info::array_first_elem, cYAML::cy_string, cYAML::cy_valuestring, cYAML_print_info::extra_ind, INDENT, and cYAML_print_info::level.
Referenced by print_value().
static void print_value (FILE * f, struct list_head * stack) [static]
Definition at line 884 of file cyaml.c.
References cYAML::cy_type, cYAML_ll_pop(), CYAML_TYPE_ARRAY, CYAML_TYPE_FALSE, CYAML_TYPE_NULL, CYAML_TYPE_NUMBER, CYAML_TYPE_OBJECT, CYAML_TYPE_STRING, CYAML_TYPE_TRUE, print_array(), print_number(), print_object(), print_simple(), and print_string().
Referenced by cYAML_print_tree(), cYAML_print_tree2file(), print_array(), and print_object().
static enum cYAML_handler_error yaml_blk_mapping_start (yaml_token_t * token, struct cYAML_tree_node * tree) [static]
Definition at line 574 of file cyaml.c.
References create_child(), cYAML_tree_node::cur, CYAML_ERROR_NONE, CYAML_ERROR_OUT_OF_MEM, CYAML_ERROR_UNEXPECTED_STATE, cYAML_ll_push(), cYAML_tree_node::from_blk_map_start, cYAML_tree_node::ll, cYAML_tree_node::state, TREE_STATE_BLK_STARTED, TREE_STATE_INITED, TREE_STATE_SEQ_START, TREE_STATE_TREE_STARTED, and TREE_STATE_VALUE.
static enum cYAML_handler_error yaml_blk_seq_start (yaml_token_t * token, struct cYAML_tree_node * tree) [static]
Definition at line 534 of file cyaml.c.
References cYAML_tree_node::cur, cYAML::cy_type, CYAML_ERROR_NONE, CYAML_ERROR_UNEXPECTED_STATE, CYAML_TYPE_ARRAY, cYAML_tree_node::state, TREE_STATE_SEQ_START, and TREE_STATE_VALUE.
static enum cYAML_handler_error yaml_block_end (yaml_token_t * token, struct cYAML_tree_node * tree) [static]
Definition at line 604 of file cyaml.c.
References cYAML_tree_node::cur, CYAML_ERROR_NONE, CYAML_ERROR_UNEXPECTED_STATE, cYAML_ll_count(), cYAML_ll_pop(), cYAML_tree_node::ll, cYAML_tree_node::state, TREE_STATE_BLK_STARTED, TREE_STATE_COMPLETE, and TREE_STATE_VALUE.
static enum cYAML_handler_error yaml_document_end (yaml_token_t * token, struct cYAML_tree_node * tree) [static]
Definition at line 472 of file cyaml.c.
References CYAML_ERROR_NONE, CYAML_ERROR_UNEXPECTED_STATE, cYAML_tree_node::state, TREE_STATE_COMPLETE, and TREE_STATE_TREE_STARTED.
static enum cYAML_handler_error yaml_document_start (yaml_token_t * token, struct cYAML_tree_node * tree) [static]
Definition at line 461 of file cyaml.c.
References CYAML_ERROR_NONE, CYAML_ERROR_UNEXPECTED_STATE, cYAML_tree_node::state, TREE_STATE_INITED, and TREE_STATE_TREE_STARTED.
static enum cYAML_handler_error yaml_entry_token (yaml_token_t * token, struct cYAML_tree_node * tree) [static]
Definition at line 549 of file cyaml.c.
References create_child(), create_sibling(), cYAML_tree_node::cur, CYAML_ERROR_NONE, CYAML_ERROR_OUT_OF_MEM, CYAML_ERROR_UNEXPECTED_STATE, cYAML_ll_push(), cYAML_tree_node::ll, cYAML_tree_node::state, TREE_STATE_BLK_STARTED, and TREE_STATE_SEQ_START.
static enum cYAML_handler_error yaml_key (yaml_token_t * token, struct cYAML_tree_node * tree) [static]
Definition at line 483 of file cyaml.c.
References create_sibling(), cYAML_tree_node::cur, CYAML_ERROR_NONE, CYAML_ERROR_UNEXPECTED_STATE, cYAML_tree_node::from_blk_map_start, cYAML_tree_node::state, TREE_STATE_BLK_STARTED, TREE_STATE_KEY, and TREE_STATE_VALUE.
static enum cYAML_handler_error yaml_not_supported (yaml_token_t * token, struct cYAML_tree_node * tree) [static]
Definition at line 623 of file cyaml.c.
References CYAML_ERROR_NOT_SUPPORTED.
static enum cYAML_handler_error yaml_parse_error (yaml_token_t * token, struct cYAML_tree_node * tree) [static]
Definition at line 426 of file cyaml.c.
References CYAML_ERROR_PARSE.
static enum cYAML_handler_error yaml_scalar (yaml_token_t * token, struct cYAML_tree_node * tree) [static]
Definition at line 501 of file cyaml.c.
References assign_type_value(), cYAML_tree_node::cur, cYAML::cy_string, CYAML_ERROR_BAD_VALUE, CYAML_ERROR_NONE, CYAML_ERROR_UNEXPECTED_STATE, cYAML_tree_node::state, TREE_STATE_BLK_STARTED, TREE_STATE_KEY, TREE_STATE_KEY_FILLED, and TREE_STATE_VALUE.
static enum cYAML_handler_error yaml_stream_end (yaml_token_t * token, struct cYAML_tree_node * tree) [static]
Definition at line 448 of file cyaml.c.
References CYAML_ERROR_NONE, CYAML_ERROR_UNEXPECTED_STATE, cYAML_tree_node::state, TREE_STATE_COMPLETE, TREE_STATE_INITED, and TREE_STATE_TREE_STARTED.
static enum cYAML_handler_error yaml_stream_start (yaml_token_t * token, struct cYAML_tree_node * tree) [static]
Definition at line 432 of file cyaml.c.
References CYAML_ERROR_NONE, cYAML_tree_init(), cYAML_tree_node::state, and TREE_STATE_INITED.
static enum cYAML_handler_error yaml_value (yaml_token_t * token, struct cYAML_tree_node * tree) [static]
Definition at line 523 of file cyaml.c.
References CYAML_ERROR_NONE, CYAML_ERROR_UNEXPECTED_STATE, cYAML_tree_node::state, TREE_STATE_KEY_FILLED, and TREE_STATE_VALUE.
Variable Documentation
yaml_token_handler dispatch_tbl[] [static]
Initial value:
 {
        [YAML_NO_TOKEN] = yaml_parse_error,
        [YAML_STREAM_START_TOKEN] = yaml_stream_start,
        [YAML_STREAM_END_TOKEN] = yaml_stream_end,
        [YAML_VERSION_DIRECTIVE_TOKEN] = yaml_not_supported,
        [YAML_TAG_DIRECTIVE_TOKEN] = yaml_not_supported,
        [YAML_DOCUMENT_START_TOKEN] = yaml_document_start,
        [YAML_DOCUMENT_END_TOKEN] = yaml_document_end,
        [YAML_BLOCK_SEQUENCE_START_TOKEN] = yaml_blk_seq_start,
        [YAML_BLOCK_MAPPING_START_TOKEN] = yaml_blk_mapping_start,
        [YAML_BLOCK_END_TOKEN] = yaml_block_end,
        [YAML_FLOW_SEQUENCE_START_TOKEN] = yaml_not_supported,
        [YAML_FLOW_SEQUENCE_END_TOKEN] = yaml_not_supported,
        [YAML_FLOW_MAPPING_START_TOKEN] = yaml_not_supported,
        [YAML_FLOW_MAPPING_END_TOKEN] = yaml_not_supported,
        [YAML_BLOCK_ENTRY_TOKEN] = yaml_entry_token,
        [YAML_FLOW_ENTRY_TOKEN] = yaml_not_supported,
        [YAML_KEY_TOKEN] = yaml_key,
        [YAML_VALUE_TOKEN] = yaml_value,
        [YAML_ALIAS_TOKEN] = yaml_not_supported,
        [YAML_ANCHOR_TOKEN] = yaml_not_supported,
        [YAML_TAG_TOKEN] = yaml_not_supported,
        [YAML_SCALAR_TOKEN] = yaml_scalar,
}
Definition at line 138 of file cyaml.c.
Referenced by cYAML_build_tree().
enum cYAML_handler_error(* yaml_token_handler)(yaml_token_t *token, struct cYAML_tree_node *)
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.