Lustre: lustre/llite/dcache.c File Reference
lustre/llite/dcache.c File Reference
#include <linux/fs.h>
#include <linux/sched.h>
#include <linux/quotaops.h>
#include <linux/kernel.h>
#include <obd_support.h>
#include <lustre/lustre_idl.h>
#include <lustre_dlm.h>
#include "llite_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LLITE
Functions
static void free_dentry_data (struct rcu_head *head)
static void ll_release (struct dentry *de)
static int ll_dcompare (struct dentry *parent, struct qstr *d_name, struct qstr *name)
static int ll_ddelete (HAVE_D_DELETE_CONST struct dentry *de)
Called when last reference to a dentry is dropped and dcache wants to know whether or not it should cache it:
return 1 to delete the dentry immediately
return 0 to cache the dentry Should NOT be called with the dcache lock, see fs/dcache.c.
int ll_d_init (struct dentry *de)
void ll_intent_drop_lock (struct lookup_intent *it)
void ll_intent_release (struct lookup_intent *it)
void ll_invalidate_aliases (struct inode *inode)
int ll_revalidate_it_finish (struct ptlrpc_request *request, struct lookup_intent *it, struct dentry *de)
void ll_lookup_finish_locks (struct lookup_intent *it, struct dentry *dentry)
static int ll_revalidate_dentry (struct dentry *dentry, unsigned int lookup_flags)
static int ll_revalidate_nd (struct dentry *dentry, struct nameidata *nd)
Variables
struct dentry_operations ll_d_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_LLITE
Definition at line 42 of file dcache.c.
Function Documentation
static void free_dentry_data (struct rcu_head * head) [static]
Definition at line 50 of file dcache.c.
References ll_dentry_data::lld_rcu_head, and OBD_FREE_PTR.
Referenced by ll_release().
int ll_d_init (struct dentry * de)
Definition at line 169 of file dcache.c.
References __d_lustre_invalidate(), CDEBUG, D_DENTRY, ENTRY, LASSERT, likely, ll_d_count, ll_d_ops, OBD_ALLOC_PTR, OBD_FREE_PTR, and RETURN.
Referenced by ll_splice_alias().
static int ll_dcompare (struct dentry * parent, struct qstr * d_name, struct qstr * name) [static]
Definition at line 96 of file dcache.c.
References CDEBUG, D_DENTRY, d_lustre_invalid(), ENTRY, ll_d_count, and RETURN.
static int ll_ddelete (HAVE_D_DELETE_CONST struct dentry * de) [static]
Called when last reference to a dentry is dropped and dcache wants to know whether or not it should cache it:
return 1 to delete the dentry immediately
return 0 to cache the dentry Should NOT be called with the dcache lock, see fs/dcache.c.
Definition at line 135 of file dcache.c.
References CDEBUG, D_DENTRY, d_lustre_invalid(), ENTRY, LASSERT, list_empty(), ll_d_count, and RETURN.
void ll_intent_drop_lock (struct lookup_intent * it)
Definition at line 204 of file dcache.c.
References CDEBUG, lustre_handle::cookie, D_DLMTRACE, lookup_intent::it_lock_handle, lookup_intent::it_lock_mode, lookup_intent::it_op, lookup_intent::it_remote_lock_handle, lookup_intent::it_remote_lock_mode, ldlm_lock_decref(), and LPX64.
Referenced by ll_intent_file_open(), ll_intent_release(), ll_layout_refresh_locked(), ll_lookup_finish_locks(), ll_statahead_interpret(), and ll_xattr_cache_refill().
void ll_intent_release (struct lookup_intent * it)
Definition at line 230 of file dcache.c.
References CDEBUG, D_INFO, DISP_ENQ_CREATE_REF, DISP_ENQ_OPEN_REF, ENTRY, EXIT, lookup_intent::it_disposition, it_disposition(), lookup_intent::it_request, ll_intent_drop_lock(), and ptlrpc_req_finished().
Referenced by __ll_inode_revalidate(), ll_create_nd(), ll_lease_open(), ll_lookup_it(), ll_lookup_it_finish(), ll_lookup_nd(), ll_lov_setstripe_ea_info(), ll_release(), ll_statahead_interpret(), revalidate_statahead_dentry(), sa_make_ready(), and sa_revalidate().
void ll_invalidate_aliases (struct inode * inode)
Definition at line 248 of file dcache.c.
References CDEBUG, CERROR, D_DENTRY, D_INODE, d_lustre_invalidate(), DECLARE_LL_D_HLIST_NODE_PTR, DFID, ENTRY, EXIT, LASSERT, libcfs_debug_dumpstack, ll_d_hlist_for_each_entry, ll_get_fsname(), ll_inode2fid(), ll_lock_dcache(), ll_unlock_dcache(), lustre_dump_dentry(), PFID, and unlikely.
Referenced by ll_md_blocking_ast().
void ll_lookup_finish_locks (struct lookup_intent * it, struct dentry * dentry)
Definition at line 299 of file dcache.c.
References CDEBUG, D_DLMTRACE, DFID, IT_GETATTR, lookup_intent::it_lock_mode, IT_LOOKUP, lookup_intent::it_op, LASSERT, ll_i2sbi(), ll_inode2fid(), ll_intent_drop_lock(), ll_sb_info::ll_md_exp, ll_set_lock_data(), and PFID.
Referenced by __ll_inode_revalidate(), and ll_lookup_it().
static void ll_release (struct dentry * de) [static]
Definition at line 59 of file dcache.c.
References ENTRY, EXIT, free_dentry_data(), LASSERT, ll_d2d, ll_intent_release(), ll_dentry_data::lld_it, ll_dentry_data::lld_rcu_head, OBD_FREE, and RETURN_EXIT.
static int ll_revalidate_dentry (struct dentry * dentry, unsigned int lookup_flags) [static]
Definition at line 322 of file dcache.c.
References dentry_may_statahead(), dir, ll_statahead(), and LOOKUP_CONTINUE.
Referenced by ll_revalidate_nd().
int ll_revalidate_it_finish (struct ptlrpc_request * request, struct lookup_intent * it, struct dentry * de)
Definition at line 281 of file dcache.c.
References DISP_LOOKUP_NEG, ENTRY, it_disposition(), ll_prep_inode(), and RETURN.
Referenced by __ll_inode_revalidate().
static int ll_revalidate_nd (struct dentry * dentry, struct nameidata * nd) [static]
Definition at line 374 of file dcache.c.
References CDEBUG, D_VFSTRACE, ENTRY, ll_revalidate_dentry(), and RETURN.
Variable Documentation
struct dentry_operations ll_d_ops
Initial value:
 {
        .d_revalidate = ll_revalidate_nd,
        .d_release = ll_release,
        .d_delete  = ll_ddelete,
        .d_compare = ll_dcompare,
}
Definition at line 394 of file dcache.c.
Referenced by client_common_fill_super(), ll_d_init(), and ll_fill_super().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.