Lustre: lustre/llite/dir.c File Reference
lustre/llite/dir.c File Reference
#include <linux/fs.h>
#include <linux/pagemap.h>
#include <linux/mm.h>
#include <linux/version.h>
#include <linux/user_namespace.h>
#include <asm/uaccess.h>
#include <linux/buffer_head.h>
#include <linux/pagevec.h>
#include <lustre/lustre_idl.h>
#include <obd_support.h>
#include <obd_class.h>
#include <lustre_ioctl.h>
#include <lustre_lib.h>
#include <lustre_dlm.h>
#include <lustre_fid.h>
#include <lustre_kernelcomm.h>
#include <lustre_swab.h>
#include "llite_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LLITE
#define ll_putname(filename) OBD_FREE(filename, NAME_MAX + 1);
Functions
struct page * ll_get_dir_page (struct inode *dir, struct md_op_data *op_data, __u64 offset, struct ll_dir_chain *chain)
void ll_release_page (struct inode *inode, struct page *page, bool remove)
static u16 ll_dirent_type_get (struct lu_dirent *ent)
return IF_* type for given lu_dirent entry.
int ll_dir_read (struct inode *inode, __u64 *ppos, struct md_op_data *op_data, void *cookie, filldir_t filldir)
static int ll_readdir (struct file *filp, void *cookie, filldir_t filldir)
static int ll_send_mgc_param (struct obd_export *mgc, char *string)
static int ll_dir_setdirstripe (struct inode *parent, struct lmv_user_md *lump, const char *dirname, umode_t mode)
Create striped directory with specified stripe().
int ll_dir_setstripe (struct inode *inode, struct lov_user_md *lump, int set_default)
int ll_dir_getstripe (struct inode *inode, void **plmm, int *plmm_size, struct ptlrpc_request **request, u64 valid)
This function will be used to get default LOV/LMV/Default LMV will be used to indicate which stripe it will retrieve OBD_MD_MEA LMV stripe EA OBD_MD_DEFAULT_MEA Default LMV stripe EA otherwise Default LOV EA.
int ll_get_mdt_idx_by_fid (struct ll_sb_info *sbi, const struct lu_fid *fid)
int ll_get_mdt_idx (struct inode *inode)
static int ll_ioc_copy_start (struct super_block *sb, struct hsm_copy *copy)
Generic handler to do any pre-copy work.
static int ll_ioc_copy_end (struct super_block *sb, struct hsm_copy *copy)
Generic handler to do any post-copy work.
static int copy_and_ioctl (int cmd, struct obd_export *exp, const void __user *data, size_t size)
static int quotactl_ioctl (struct ll_sb_info *sbi, struct if_quotactl *qctl)
static char * ll_getname (const char __user *filename)
static long ll_dir_ioctl (struct file *file, unsigned int cmd, unsigned long arg)
static loff_t ll_dir_seek (struct file *file, loff_t offset, int origin)
static int ll_dir_open (struct inode *inode, struct file *file)
static int ll_dir_release (struct inode *inode, struct file *file)
Variables
struct file_operations ll_dir_operations
Define Documentation
#define DEBUG_SUBSYSTEM S_LLITE
Definition at line 53 of file dir.c.
#define ll_putname (filename) OBD_FREE(filename, NAME_MAX + 1);
Definition at line 1095 of file dir.c.
Referenced by ll_dir_ioctl().
Function Documentation
static int copy_and_ioctl (int cmd, struct obd_export * exp, const void __user * data, size_t size) [static]
Definition at line 917 of file dir.c.
References OBD_ALLOC, OBD_FREE, and obd_iocontrol().
Referenced by ll_dir_ioctl().
int ll_dir_getstripe (struct inode * inode, void ** plmm, int * plmm_size, struct ptlrpc_request ** request, u64 valid)
This function will be used to get default LOV/LMV/Default LMV will be used to indicate which stripe it will retrieve OBD_MD_MEA LMV stripe EA OBD_MD_DEFAULT_MEA Default LMV stripe EA otherwise Default LOV EA.
Each time, it can only retrieve 1 stripe EA
Definition at line 631 of file dir.c.
References CDEBUG, CERROR, cpu_to_le32, D_INFO, DFID, ENTRY, GOTO, LASSERT, le32_to_cpu, ll_finish_md_op_data(), ll_get_default_mdsize(), ll_i2sbi(), ll_inode2fid(), ll_sb_info::ll_md_exp, ll_prep_md_op_data(), LMV_MAGIC, LMV_MAGIC_V1, LMV_USER_MAGIC, lmv_user_md, LOV_MAGIC, LOV_MAGIC_V1, LOV_MAGIC_V3, lov_mds_md, LUSTRE_OPC_ANY, lustre_swab_lmv_mds_md(), lustre_swab_lmv_user_md, lustre_swab_lov_user_md_v1(), lustre_swab_lov_user_md_v3(), mdt_body::mbo_eadatasize, mdt_body::mbo_valid, md_getattr(), OBD_MD_FLDIREA, OBD_MD_FLEASIZE, md_op_data::op_valid, PFID, req_capsule_server_get(), req_capsule_server_sized_get(), RETURN, RMF_MDT_BODY, RMF_MDT_MD, and ptlrpc_request::rq_pill.
Referenced by ll_dir_ioctl(), ll_getxattr_lov(), and ll_new_node().
static long ll_dir_ioctl (struct file * file, unsigned int cmd, unsigned long arg) [static]
Definition at line 1097 of file dir.c.
References __user, buf, CDEBUG, CERROR, CFS_CAP_SYS_ADMIN, cfs_capable(), copy_and_ioctl(), current_pid, D_INFO, D_VFSTRACE, DFID, ENTRY, EXIT, exp_connect_flags(), ll_file_data::fd_flags, fid_le_to_cpu(), filename, FSFILT_IOC_GETFLAGS, FSFILT_IOC_GETVERSION, FSFILT_IOC_GETVERSION_OLD, FSFILT_IOC_SETFLAGS, GOTO, hsm_progress::hp_cookie, hsm_progress::hp_errval, hsm_progress::hp_extent, hsm_progress::hp_fid, hsm_progress::hp_flags, hsm_progress_kernel::hpk_cookie, hsm_progress_kernel::hpk_data_version, hsm_progress_kernel::hpk_errval, hsm_progress_kernel::hpk_extent, hsm_progress_kernel::hpk_fid, hsm_progress_kernel::hpk_flags, hsm_request::hr_action, hsm_request::hr_itemcount, HUA_RELEASE, hsm_user_item::hui_fid, hur_len(), hsm_user_request::hur_request, hsm_user_request::hur_user_item, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf2, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, IOC_MDC_GETFILEINFO, IOC_MDC_GETFILESTRIPE, IOC_MDC_LOOKUP, IOC_OBD_STATFS, obd_ioctl_data::ioc_type, KEY_TGT_COUNT, LASSERT, ll_dir_getstripe(), ll_dir_setdirstripe(), ll_dir_setstripe(), ll_sb_info::ll_dt_exp, ll_fid2path(), LL_FILE_RMTACL, ll_sb_info::ll_flags, ll_flush_ctx(), ll_get_fid_by_name(), ll_get_fsname(), ll_get_mdt_idx(), ll_get_mdt_idx_by_fid(), ll_get_obd_name(), ll_getname(), ll_getparent(), ll_hsm_release(), ll_i2mdexp(), ll_i2sbi(), ll_inode2fid(), ll_ioc_copy_end(), ll_ioc_copy_start(), LL_IOC_FID2MDTIDX, LL_IOC_FLUSHCTX, LL_IOC_GET_CONNECT_FLAGS, LL_IOC_GET_MDTIDX, LL_IOC_GETOBDCOUNT, LL_IOC_GETPARENT, LL_IOC_HSM_COPY_END, LL_IOC_HSM_COPY_START, LL_IOC_HSM_CT_START, LL_IOC_HSM_PROGRESS, LL_IOC_HSM_REQUEST, LL_IOC_LMV_GETSTRIPE, LL_IOC_LMV_SET_DEFAULT_STRIPE, LL_IOC_LMV_SETSTRIPE, LL_IOC_LOV_GETSTRIPE, LL_IOC_LOV_SETSTRIPE, LL_IOC_LOV_SWAP_LAYOUTS, LL_IOC_MDC_GETINFO, LL_IOC_MIGRATE, LL_IOC_PATH2FID, LL_IOC_REMOVE_ENTRY, LL_IOC_RMTACL, ll_iocontrol(), ll_lov_getstripe_ea_info(), ll_sb_info::ll_md_exp, ll_migrate(), ll_obd_statfs(), ll_putname, ll_sb_info::ll_rct, ll_rmdir_entry(), LL_SBI_RMT_CLIENT, ll_stats_ops_tally(), lov_user_md_v1::lmm_magic, lov_user_md_v3::lmm_objects, LMV_MAGIC_V1, lmv_mds_md_stripe_count_get(), LMV_USER_MAGIC, lmv_user_md, lmv_user_md_size(), lov_mds_md, LOV_USER_MAGIC_V3, lov_user_md, LPROC_LL_IOCTL, LUSTRE_FPRIVATE, mdt_body::mbo_atime, mdt_body::mbo_blocks, mdt_body::mbo_ctime, mdt_body::mbo_gid, mdt_body::mbo_mode, mdt_body::mbo_mtime, mdt_body::mbo_nlink, mdt_body::mbo_rdev, mdt_body::mbo_size, mdt_body::mbo_uid, MDS_MAXREQSIZE, mode, OBD_ALLOC, OBD_ALLOC_LARGE, OBD_ALLOC_PTR, OBD_CONNECT_LVB_TYPE, OBD_FREE, OBD_FREE_LARGE, OBD_FREE_PTR, obd_get_info(), OBD_IOC_CHANGELOG_CLEAR, OBD_IOC_CHANGELOG_SEND, OBD_IOC_FID2PATH, OBD_IOC_GETDTNAME, OBD_IOC_GETMDNAME, OBD_IOC_QUOTACTL, obd_iocontrol(), obd_ioctl_getdata(), OBD_MD_DEFAULT_MEA, OBD_MD_MEA, PFID, ptlrpc_req_finished(), quotactl_ioctl(), req_capsule_server_get(), RETURN, RMF_MDT_BODY, ptlrpc_request::rq_pill, and search_inode_for_lustre().
static int ll_dir_open (struct inode * inode, struct file * file) [static]
Definition at line 1778 of file dir.c.
References ENTRY, ll_file_open(), and RETURN.
int ll_dir_read (struct inode * inode, __u64 * ppos, struct md_op_data * op_data, void * cookie, filldir_t filldir)
Definition at line 214 of file dir.c.
References __u64, cl_fid_build_ino(), done, ENTRY, fid_le_to_cpu(), lu_dirent::lde_fid, lu_dirent::lde_hash, lu_dirent::lde_name, lu_dirent::lde_namelen, LDF_COLLIDE, lu_dirpage::ldp_flags, lu_dirpage::ldp_hash_end, le16_to_cpu, le32_to_cpu, le64_to_cpu, ll_dir_chain_fini(), ll_dir_chain_init(), ll_dirent_type_get(), ll_sb_info::ll_flags, ll_get_dir_page(), ll_i2sbi(), ll_need_32bit_api(), ll_release_page(), LL_SBI_64BIT_HASH, lu_dirent_next(), lu_dirent_start(), MDS_DIR_END_OFF, and RETURN.
Referenced by ll_get_name(), and ll_readdir().
static int ll_dir_release (struct inode * inode, struct file * file) [static]
Definition at line 1784 of file dir.c.
References ENTRY, ll_file_release(), and RETURN.
static loff_t ll_dir_seek (struct file * file, loff_t offset, int origin) [static]
Definition at line 1727 of file dir.c.
References ENTRY, GOTO, ll_file_data::lfd_pos, LL_DIR_END_OFF, LL_DIR_END_OFF_32BIT, ll_sb_info::ll_flags, ll_i2sbi(), ll_need_32bit_api(), LL_SBI_64BIT_HASH, LUSTRE_FPRIVATE, MDS_DIR_END_OFF, and ret.
static int ll_dir_setdirstripe (struct inode * parent, struct lmv_user_md * lump, const char * dirname, umode_t mode) [static]
Create striped directory with specified stripe().
param[in]parent the parent of the directory. param[in]lump the specified stripes. param[in]dirname the name of the directory. param[in]mode the specified mode of the directory.
retval =0 if striped directory is being created successfully. <0 if the creation is failed.
Definition at line 449 of file dir.c.
References CDEBUG, cfs_curproc_cap_pack(), CLI_SET_MEA, cpu_to_le32, D_VFSTRACE, DFID, ENTRY, exp_connect_flags(), exp_connect_umask(), from_kgid(), from_kuid(), GOTO, ll_finish_md_op_data(), ll_i2mdexp(), ll_i2sbi(), ll_init_security(), ll_inode2fid(), ll_sb_info::ll_md_exp, ll_prep_inode(), ll_prep_md_op_data(), LMV_USER_MAGIC, LUSTRE_OPC_MKDIR, lustre_swab_lmv_user_md, md_create(), OBD_CONNECT_DIR_STRIPE, OBD_FAIL_CHECK, OBD_FAIL_LLITE_NO_CHECK_DEAD, md_op_data::op_cli_flags, PFID, ptlrpc_req_finished(), RETURN, and unlikely.
Referenced by ll_dir_ioctl().
int ll_dir_setstripe (struct inode * inode, struct lov_user_md * lump, int set_default)
Definition at line 514 of file dir.c.
References buf, CDEBUG, CERROR, client_obd::cl_mgc_mgsexp, obd_device::cli, cpu_to_le32, D_IOCTL, end, ENTRY, GOTO, le16_to_cpu, le32_to_cpu, ll_finish_md_op_data(), ll_get_fsname(), ll_i2sbi(), ll_sb_info::ll_md_exp, ll_prep_md_op_data(), ll_send_mgc_param(), LMV_USER_MAGIC, lmv_user_md, LOV_USER_MAGIC_V1, LOV_USER_MAGIC_V3, LUSTRE_OPC_ANY, lustre_swab_lmv_user_md, lustre_swab_lov_user_md_v1(), lustre_swab_lov_user_md_v3(), md_setattr(), MGS_PARAM_MAXLEN, MTI_NAME_MAXLEN, OBD_ALLOC, OBD_FREE, ptlrpc_req_finished(), RETURN, and obd_device::u.
Referenced by ll_dir_ioctl(), and ll_setxattr().
static u16 ll_dirent_type_get (struct lu_dirent * ent) [static]
return IF_* type for given lu_dirent entry.
IF_* flag shld be converted to particular OS file type in platform llite module.
Definition at line 191 of file dir.c.
References IFTODT, lu_dirent::lde_attrs, lu_dirent::lde_name, lu_dirent::lde_namelen, le16_to_cpu, le32_to_cpu, luda_type::lt_type, and LUDA_TYPE.
Referenced by ll_dir_read().
struct page* ll_get_dir_page (struct inode * dir, struct md_op_data * op_data, __u64 offset, struct ll_dir_chain * chain) [read]
Definition at line 149 of file dir.c.
References ll_i2mdexp(), ll_md_blocking_ast(), md_callback::md_blocking_ast, and md_read_page().
Referenced by is_first_dirent(), ll_dir_read(), and ll_statahead_thread().
int ll_get_mdt_idx (struct inode * inode)
Definition at line 734 of file dir.c.
References ll_get_mdt_idx_by_fid(), ll_i2sbi(), and ll_inode2fid().
Referenced by ll_dir_ioctl(), and ll_file_ioctl().
int ll_get_mdt_idx_by_fid (struct ll_sb_info * sbi, const struct lu_fid * fid)
Definition at line 709 of file dir.c.
References ENTRY, ll_sb_info::ll_md_exp, md_getattr(), MF_GET_MDT_IDX, OBD_ALLOC_PTR, OBD_FREE_PTR, md_op_data::op_fid1, md_op_data::op_flags, md_op_data::op_mds, and RETURN.
Referenced by ll_dir_ioctl(), ll_get_mdt_idx(), and ll_migrate().
static char* ll_getname (const char __user * filename) [static]
Definition at line 1072 of file dir.c.
References OBD_ALLOC, OBD_FREE, and ret.
Referenced by ll_dir_ioctl().
static int ll_ioc_copy_end (struct super_block * sb, struct hsm_copy * copy) [static]
Generic handler to do any post-copy work.
It will send the last hsm_progress update to coordinator to inform it that copy is finished and whether it was successful or not.
Moreover,
for ARCHIVE request, it will sample the file data version and compare it with the version saved in ll_ioc_copy_start(). If they do not match, copy will be considered as failed.
for RESTORE request, it will sample the file data version and send it to coordinator which is useful if the file was imported as 'released'.
Returns:
0 on success.
Definition at line 829 of file dir.c.
References __u64, CDEBUG, D_HSM, DFID, ENTRY, GOTO, hsm_action_item::hai_action, hsm_action_item::hai_cookie, hsm_action_item::hai_extent, hsm_action_item::hai_fid, hsm_copy::hc_data_version, hsm_copy::hc_errval, hsm_copy::hc_flags, hsm_copy::hc_hai, HP_FLAG_COMPLETED, HP_FLAG_RETRY, hsm_progress_kernel::hpk_cookie, hsm_progress_kernel::hpk_data_version, hsm_progress_kernel::hpk_errval, hsm_progress_kernel::hpk_extent, hsm_progress_kernel::hpk_fid, hsm_progress_kernel::hpk_flags, HSMA_ARCHIVE, HSMA_RESTORE, ll_data_version(), LL_DV_RD_FLUSH, LL_IOC_HSM_PROGRESS, ll_sb_info::ll_md_exp, ll_s2sbi, LPX64, obd_iocontrol(), PFID, RETURN, and search_inode_for_lustre().
Referenced by ll_dir_ioctl().
static int ll_ioc_copy_start (struct super_block * sb, struct hsm_copy * copy) [static]
Generic handler to do any pre-copy work.
It sends a first hsm_progress (with extent length == 0) to coordinator as a first information for it that real work has started.
Moreover, for a ARCHIVE request, it will sample the file data version and store it in copy.
Returns:
0 on success.
Definition at line 750 of file dir.c.
References __u64, CDEBUG, D_HSM, DFID, ENTRY, GOTO, hsm_action_item::hai_action, hsm_action_item::hai_cookie, hsm_action_item::hai_extent, hsm_action_item::hai_fid, hsm_copy::hc_data_version, hsm_copy::hc_hai, HP_FLAG_COMPLETED, HP_FLAG_RETRY, hsm_progress_kernel::hpk_cookie, hsm_progress_kernel::hpk_data_version, hsm_progress_kernel::hpk_errval, hsm_progress_kernel::hpk_extent, hsm_progress_kernel::hpk_fid, hsm_progress_kernel::hpk_flags, HSMA_ARCHIVE, hsm_extent::length, ll_data_version(), LL_DV_RD_FLUSH, LL_IOC_HSM_PROGRESS, ll_sb_info::ll_md_exp, ll_s2sbi, LPX64, obd_iocontrol(), hsm_extent::offset, PFID, RETURN, and search_inode_for_lustre().
Referenced by ll_dir_ioctl().
static int ll_readdir (struct file * filp, void * cookie, filldir_t filldir) [static]
Definition at line 328 of file dir.c.
References __u64, CDEBUG, D_VFSTRACE, DFID, ENTRY, fid_is_zero(), GOTO, LCK_MINMODE, ll_file_data::lfd_pos, LL_DIR_END_OFF, LL_DIR_END_OFF_32BIT, ll_dir_get_parent_fid(), ll_dir_read(), ll_finish_md_op_data(), ll_sb_info::ll_flags, ll_have_md_lock(), ll_i2sbi(), ll_inode2fid(), ll_sb_info::ll_md_brw_pages, ll_need_32bit_api(), ll_prep_md_op_data(), LL_SBI_64BIT_HASH, ll_stats_ops_tally(), LPROC_LL_READDIR, LUSTRE_FPRIVATE, LUSTRE_OPC_ANY, MDS_DIR_END_OFF, MDS_INODELOCK_UPDATE, md_op_data::op_fid3, md_op_data::op_max_pages, md_op_data::op_mea1, PFID, RETURN, and unlikely.
void ll_release_page (struct inode * inode, struct page * page, bool remove)
Definition at line 164 of file dir.c.
References likely, ll_i2info(), and truncate_complete_page().
Referenced by is_first_dirent(), ll_dir_read(), and ll_statahead_thread().
static int ll_send_mgc_param (struct obd_export * mgc, char * string) [static]
Definition at line 419 of file dir.c.
References CERROR, KEY_SET_INFO, mgs_send_param::mgs_param, OBD_ALLOC_PTR, OBD_FREE_PTR, obd_set_info_async(), and strlcpy().
Referenced by ll_dir_setstripe().
static int quotactl_ioctl (struct ll_sb_info * sbi, struct if_quotactl * qctl) [static]
Definition at line 939 of file dir.c.
References CERROR, CFS_CAP_SYS_ADMIN, cfs_capable(), cmd, obd_dqblk::dqb_curinodes, obd_dqblk::dqb_curspace, obd_dqblk::dqb_valid, ENTRY, GOTO, ll_sb_info::ll_dt_exp, ll_sb_info::ll_flags, ll_sb_info::ll_md_exp, LL_SBI_RMT_CLIENT, make_kgid(), make_kuid(), OBD_ALLOC_PTR, OBD_FREE_PTR, OBD_IOC_QUOTACTL, obd_iocontrol(), obd_quotactl(), Q_GETOINFO, Q_GETOQUOTA, obd_quotactl::qc_cmd, if_quotactl::qc_cmd, obd_quotactl::qc_dqblk, QC_GENERAL, obd_quotactl::qc_id, if_quotactl::qc_id, QC_MDTIDX, QC_OSTIDX, obd_quotactl::qc_type, if_quotactl::qc_type, QC_UUID, if_quotactl::qc_valid, QCTL_COPY, QIF_INODES, QIF_SPACE, RETURN, and uid_eq().
Referenced by ll_dir_ioctl().
Variable Documentation
struct file_operations ll_dir_operations
Initial value:
 {
        .llseek         = ll_dir_seek,
        .open           = ll_dir_open,
        .release        = ll_dir_release,
        .read           = generic_read_dir,
        .readdir        = ll_readdir,
        .unlocked_ioctl = ll_dir_ioctl,
        .fsync          = ll_fsync,
}
Definition at line 1790 of file dir.c.
Referenced by ll_iget_anon_dir(), and ll_read_inode2().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.