Lustre: lustre/include/dt_object.h File Reference
lustre/include/dt_object.h File Reference
#include <obd_support.h>
#include <lu_object.h>
#include <libcfs/libcfs.h>
Data Structures
struct dt_device_param
struct dt_txn_commit_cb
struct dt_device_operations
Operations on dt device.
struct dt_index_features
struct dt_allocation_hint
This is a general purpose dt allocation hint.
struct dt_object_format
object format specifier.
struct dt_object_operations
A dt_object provides common operations to create and destroy objects and to manage regular and extended attributes.
struct dt_body_operations
Per-dt-object operations on "file body" - unstructure raw data.
struct dt_index_operations
Per-dt-object operations on object as index.
struct dt_index_operations::dt_it_ops
Iterator interface.
struct dt_device
struct dt_object
struct local_oid_storage
struct thandle
This is the general purpose transaction handle.
struct dt_txn_callback
Transaction call-backs.
struct dt_find_hint
struct dt_insert_rec
struct dt_thread_info
Defines
#define TRANS_COMMIT_CB_MAGIC 0xa0a00a0a
Special per-transaction callback for cases when just commit callback is needed and per-device callback are not convenient to use.
#define MAX_COMMIT_CB_STR_LEN 32
#define DCB_TRANS_STOP 0x1
#define DT_OTABLE_IT_FLAGS_SHIFT 16
#define DT_OTABLE_IT_FLAGS_MASK 0xffff0000
#define DT_MAX_PATH 1024
Typedefs
typedef void(* dt_cb_t)(struct lu_env *env, struct thandle *th, struct dt_txn_commit_cb *cb, int err)
typedef __u64 dt_obj_version_t
typedef int(* dt_entry_func_t)(const struct lu_env *env, const char *name, void *pvt)
Callback function used for parsing path.
typedef int(* dt_index_page_build_t)(const struct lu_env *env, union lu_page *lp, size_t nob, const struct dt_it_ops *iops, struct dt_it *it, __u32 attr, void *arg)
Enumerations
enum mntopt_t { MNTOPT_USERXATTR = 0x00000001, MNTOPT_ACL = 0x00000002 }
enum dt_index_flags {
DT_IND_VARKEY = 1 << 0, DT_IND_VARREC = 1 << 1, DT_IND_UPDATE = 1 << 2, DT_IND_NONUNQ = 1 << 3,
DT_IND_RANGE = 1 << 4
}
enum dt_format_type {
DFT_REGULAR, DFT_DIR, DFT_NODE, DFT_INDEX,
DFT_SYM
}
object type specifier.
enum dt_otable_it_valid { DOIV_ERROR_HANDLE = 0x0001, DOIV_DRYRUN = 0x0002 }
enum dt_otable_it_flags { DOIF_FAILOUT = 0x0001, DOIF_RESET = 0x0002, DOIF_OUTUSED = 0x0004, DOIF_DRYRUN = 0x0008 }
Functions
enum dt_format_type dt_mode_to_dft (__u32 mode)
int dt_device_init (struct dt_device *dev, struct lu_device_type *t)
void dt_device_fini (struct dt_device *dev)
static int lu_device_is_dt (const struct lu_device *d)
static struct dt_device * lu2dt_dev (struct lu_device *l)
static struct lu_device * dt2lu_dev (struct dt_device *d)
static struct dt_object * lu2dt (struct lu_object *l)
int dt_object_init (struct dt_object *obj, struct lu_object_header *h, struct lu_device *d)
void dt_object_fini (struct dt_object *obj)
static int dt_object_exists (const struct dt_object *dt)
static int dt_object_remote (const struct dt_object *dt)
static struct dt_object * lu2dt_obj (struct lu_object *o)
static struct dt_object * dt_object_child (struct dt_object *o)
void dt_txn_callback_add (struct dt_device *dev, struct dt_txn_callback *cb)
void dt_txn_callback_del (struct dt_device *dev, struct dt_txn_callback *cb)
int dt_txn_hook_start (const struct lu_env *env, struct dt_device *dev, struct thandle *txn)
int dt_txn_hook_stop (const struct lu_env *env, struct thandle *txn)
void dt_txn_hook_commit (struct thandle *txn)
int dt_try_as_dir (const struct lu_env *env, struct dt_object *obj)
int dt_path_parser (const struct lu_env *env, char *local, dt_entry_func_t entry_func, void *data)
Abstract function which parses path name.
struct dt_object * dt_store_resolve (const struct lu_env *env, struct dt_device *dt, const char *path, struct lu_fid *fid)
struct dt_object * dt_store_open (const struct lu_env *env, struct dt_device *dt, const char *dirname, const char *filename, struct lu_fid *fid)
Open dt object named filename from dirname directory.
struct dt_object * dt_find_or_create (const struct lu_env *env, struct dt_device *dt, const struct lu_fid *fid, struct dt_object_format *dof, struct lu_attr *attr)
struct dt_object * dt_locate_at (const struct lu_env *env, struct dt_device *dev, const struct lu_fid *fid, struct lu_device *top_dev, const struct lu_object_conf *conf)
static struct dt_object * dt_locate (const struct lu_env *env, struct dt_device *dev, const struct lu_fid *fid)
static struct dt_object * dt_object_locate (struct dt_object *dto, struct dt_device *dt_dev)
int local_oid_storage_init (const struct lu_env *env, struct dt_device *dev, const struct lu_fid *first_fid, struct local_oid_storage **los)
Initialize local OID storage for required sequence.
void local_oid_storage_fini (const struct lu_env *env, struct local_oid_storage *los)
int local_object_fid_generate (const struct lu_env *env, struct local_oid_storage *los, struct lu_fid *fid)
local file fid generation
int local_object_declare_create (const struct lu_env *env, struct local_oid_storage *los, struct dt_object *o, struct lu_attr *attr, struct dt_object_format *dof, struct thandle *th)
int local_object_create (const struct lu_env *env, struct local_oid_storage *los, struct dt_object *o, struct lu_attr *attr, struct dt_object_format *dof, struct thandle *th)
struct dt_object * local_file_find_or_create (const struct lu_env *env, struct local_oid_storage *los, struct dt_object *parent, const char *name, __u32 mode)
struct dt_object * local_file_find_or_create_with_fid (const struct lu_env *env, struct dt_device *dt, const struct lu_fid *fid, struct dt_object *parent, const char *name, __u32 mode)
struct dt_object * local_index_find_or_create (const struct lu_env *env, struct local_oid_storage *los, struct dt_object *parent, const char *name, __u32 mode, const struct dt_index_features *ft)
struct dt_object * local_index_find_or_create_with_fid (const struct lu_env *env, struct dt_device *dt, const struct lu_fid *fid, struct dt_object *parent, const char *name, __u32 mode, const struct dt_index_features *ft)
int local_object_unlink (const struct lu_env *env, struct dt_device *dt, struct dt_object *parent, const char *name)
static int dt_object_lock (const struct lu_env *env, struct dt_object *o, struct lustre_handle *lh, struct ldlm_enqueue_info *einfo, union ldlm_policy_data *policy)
static int dt_object_unlock (const struct lu_env *env, struct dt_object *o, struct ldlm_enqueue_info *einfo, union ldlm_policy_data *policy)
int dt_lookup_dir (const struct lu_env *env, struct dt_object *dir, const char *name, struct lu_fid *fid)
lookup fid for object named name in directory dir.
static int dt_object_sync (const struct lu_env *env, struct dt_object *o, __u64 start, __u64 end)
int dt_declare_version_set (const struct lu_env *env, struct dt_object *o, struct thandle *th)
void dt_version_set (const struct lu_env *env, struct dt_object *o, dt_obj_version_t version, struct thandle *th)
dt_obj_version_t dt_version_get (const struct lu_env *env, struct dt_object *o)
int dt_read (const struct lu_env *env, struct dt_object *dt, struct lu_buf *buf, loff_t *pos)
Generic read helper.
int dt_record_read (const struct lu_env *env, struct dt_object *dt, struct lu_buf *buf, loff_t *pos)
Read structures of fixed size from storage.
int dt_record_write (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, loff_t *pos, struct thandle *th)
int dt_index_walk (const struct lu_env *env, struct dt_object *obj, const struct lu_rdpg *rdpg, dt_index_page_build_t filler, void *arg)
int dt_index_read (const struct lu_env *env, struct dt_device *dev, struct idx_info *ii, const struct lu_rdpg *rdpg)
Walk key/record pairs of an index and copy them into 4KB containers to be transferred over the network.
static struct thandle * dt_trans_create (const struct lu_env *env, struct dt_device *d)
static int dt_trans_start (const struct lu_env *env, struct dt_device *d, struct thandle *th)
static int dt_trans_start_local (const struct lu_env *env, struct dt_device *d, struct thandle *th)
static int dt_trans_stop (const struct lu_env *env, struct dt_device *d, struct thandle *th)
static int dt_trans_cb_add (struct thandle *th, struct dt_txn_commit_cb *dcb)
static int dt_declare_record_write (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, loff_t pos, struct thandle *th)
static int dt_declare_create (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *th)
static int dt_create (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *th)
static int dt_declare_destroy (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
static int dt_destroy (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
static void dt_read_lock (const struct lu_env *env, struct dt_object *dt, unsigned role)
static void dt_write_lock (const struct lu_env *env, struct dt_object *dt, unsigned role)
static void dt_read_unlock (const struct lu_env *env, struct dt_object *dt)
static void dt_write_unlock (const struct lu_env *env, struct dt_object *dt)
static int dt_write_locked (const struct lu_env *env, struct dt_object *dt)
static int dt_declare_attr_get (const struct lu_env *env, struct dt_object *dt)
static int dt_attr_get (const struct lu_env *env, struct dt_object *dt, struct lu_attr *la)
static int dt_declare_attr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_attr *la, struct thandle *th)
static int dt_attr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_attr *la, struct thandle *th)
static int dt_declare_ref_add (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
static int dt_ref_add (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
static int dt_declare_ref_del (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
static int dt_ref_del (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
static int dt_bufs_get (const struct lu_env *env, struct dt_object *d, struct niobuf_remote *rnb, struct niobuf_local *lnb, int rw)
static int dt_bufs_put (const struct lu_env *env, struct dt_object *d, struct niobuf_local *lnb, int n)
static int dt_write_prep (const struct lu_env *env, struct dt_object *d, struct niobuf_local *lnb, int n)
static int dt_declare_write_commit (const struct lu_env *env, struct dt_object *d, struct niobuf_local *lnb, int n, struct thandle *th)
static int dt_write_commit (const struct lu_env *env, struct dt_object *d, struct niobuf_local *lnb, int n, struct thandle *th)
static int dt_read_prep (const struct lu_env *env, struct dt_object *d, struct niobuf_local *lnb, int n)
static int dt_declare_write (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, loff_t pos, struct thandle *th)
static ssize_t dt_write (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, loff_t *pos, struct thandle *th, int rq)
static int dt_declare_punch (const struct lu_env *env, struct dt_object *dt, __u64 start, __u64 end, struct thandle *th)
static int dt_punch (const struct lu_env *env, struct dt_object *dt, __u64 start, __u64 end, struct thandle *th)
static int dt_ladvise (const struct lu_env *env, struct dt_object *dt, __u64 start, __u64 end, int advice)
static int dt_fiemap_get (const struct lu_env *env, struct dt_object *d, struct fiemap *fm)
static int dt_statfs (const struct lu_env *env, struct dt_device *dev, struct obd_statfs *osfs)
static int dt_root_get (const struct lu_env *env, struct dt_device *dev, struct lu_fid *f)
static void dt_conf_get (const struct lu_env *env, const struct dt_device *dev, struct dt_device_param *param)
static int dt_sync (const struct lu_env *env, struct dt_device *dev)
static int dt_ro (const struct lu_env *env, struct dt_device *dev)
static int dt_declare_insert (const struct lu_env *env, struct dt_object *dt, const struct dt_rec *rec, const struct dt_key *key, struct thandle *th)
static int dt_insert (const struct lu_env *env, struct dt_object *dt, const struct dt_rec *rec, const struct dt_key *key, struct thandle *th, int noquota)
static int dt_declare_xattr_del (const struct lu_env *env, struct dt_object *dt, const char *name, struct thandle *th)
static int dt_xattr_del (const struct lu_env *env, struct dt_object *dt, const char *name, struct thandle *th)
static int dt_declare_xattr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, const char *name, int fl, struct thandle *th)
static int dt_xattr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, const char *name, int fl, struct thandle *th)
static int dt_declare_xattr_get (const struct lu_env *env, struct dt_object *dt, struct lu_buf *buf, const char *name)
static int dt_xattr_get (const struct lu_env *env, struct dt_object *dt, struct lu_buf *buf, const char *name)
static int dt_xattr_list (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf)
static int dt_declare_delete (const struct lu_env *env, struct dt_object *dt, const struct dt_key *key, struct thandle *th)
static int dt_delete (const struct lu_env *env, struct dt_object *dt, const struct dt_key *key, struct thandle *th)
static int dt_commit_async (const struct lu_env *env, struct dt_device *dev)
static int dt_lookup (const struct lu_env *env, struct dt_object *dt, struct dt_rec *rec, const struct dt_key *key)
static struct dt_thread_info * dt_info (const struct lu_env *env)
int dt_global_init (void)
void dt_global_fini (void)
Variables
struct dt_index_features dt_directory_features
Features, required from index to support file system directories (mapping names to fids).
struct dt_index_features dt_otable_features
struct dt_index_features dt_lfsck_orphan_features
struct dt_index_features dt_lfsck_features
struct dt_index_features dt_acct_features
struct dt_index_features dt_quota_glb_features
struct dt_index_features dt_quota_slv_features
struct dt_index_features dt_nodemap_features
struct lu_context_key dt_key
Function Documentation
static int dt_attr_get (const struct lu_env * env, struct dt_object * dt, struct lu_attr * la) [inline, static]
Definition at line 2225 of file dt_object.h.
References cfs_fail_err, CFS_FAULT_CHECK, dt_object_operations::do_attr_get, dt_object::do_ops, LASSERT, and OBD_FAIL_DT_ATTR_GET.
Referenced by lfsck_disable_master_lmv(), lfsck_layout_assistant_handler_p1(), lfsck_layout_repair_dangling(), lfsck_layout_repair_multiple_references(), lfsck_layout_repair_owner(), lfsck_layout_repair_unmatched_pair(), lfsck_layout_scan_stripes(), lfsck_layout_slave_conditional_destroy(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_check_for_double_scan(), lfsck_namespace_double_scan_one(), lfsck_namespace_repair_nlink(), lfsck_namespace_replace_cond(), lfsck_orphan_it_next(), llog_osd_get_cat_list(), llog_osd_next_block(), llog_osd_prev_block(), llog_osd_put_cat_list(), llog_osd_read_header(), llog_osd_write_rec(), llog_test_10(), llog_truncate(), lod_attr_get(), lod_declare_init_size(), lod_declare_xattr_set(), lod_xattr_set_lmv(), mdo_attr_get(), ofd_attr_get(), ofd_attr_handle_ugid(), ofd_commitrw_write(), ofd_preprw_read(), ofd_seq_load(), osp_find_or_create_local_file(), out_attr_get(), tgt_reply_data_init(), and tgt_server_data_init().
static int dt_attr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_attr * la, struct thandle * th) [inline, static]
Definition at line 2253 of file dt_object.h.
References cfs_fail_err, CFS_FAULT_CHECK, dt_object_operations::do_attr_set, dt_object::do_ops, LASSERT, and OBD_FAIL_DT_ATTR_SET.
Referenced by lfsck_disable_master_lmv(), lfsck_layout_repair_owner(), lfsck_layout_repair_unmatched_pair(), lfsck_namespace_insert_normal(), lfsck_namespace_insert_orphan(), lfsck_namespace_repair_nlink(), lfsck_namespace_scan_local_lpf_one(), llog_truncate(), lod_sub_object_attr_set(), mdo_attr_set(), ofd_attr_set(), ofd_commitrw_write(), ofd_object_punch(), ofd_write_attr_set(), out_tx_attr_set_exec(), and tgt_truncate_last_rcvd().
static int dt_bufs_get (const struct lu_env * env, struct dt_object * d, struct niobuf_remote * rnb, struct niobuf_local * lnb, int rw) [inline, static]
Definition at line 2318 of file dt_object.h.
References dt_body_operations::dbo_bufs_get, dt_object::do_body_ops, LASSERT, niobuf_remote::rnb_len, and niobuf_remote::rnb_offset.
Referenced by ofd_preprw_read(), and ofd_preprw_write().
static int dt_bufs_put (const struct lu_env * env, struct dt_object * d, struct niobuf_local * lnb, int n) [inline, static]
Definition at line 2329 of file dt_object.h.
References dt_body_operations::dbo_bufs_put, dt_object::do_body_ops, and LASSERT.
Referenced by ofd_commitrw_read(), ofd_commitrw_write(), ofd_preprw_read(), and ofd_preprw_write().
static int dt_commit_async (const struct lu_env * env, struct dt_device * dev) [inline, static]
Definition at line 2645 of file dt_object.h.
References dt_device::dd_ops, dt_device_operations::dt_commit_async, and LASSERT.
Referenced by lod_commit_async(), ofd_commitrw_write(), and osp_precreate_reserve().
static void dt_conf_get (const struct lu_env * env, const struct dt_device * dev, struct dt_device_param * param) [inline, static]
Definition at line 2455 of file dt_object.h.
References dt_device::dd_ops, dt_device_operations::dt_conf_get, and LASSERT.
Referenced by lod_conf_get(), lod_init0(), mdd_init0(), mdd_process_config(), ofd_init0(), and osd_start().
static int dt_create (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof, struct thandle * th) [inline, static]
Definition at line 2120 of file dt_object.h.
References cfs_fail_err, CFS_FAULT_CHECK, dt_object_operations::do_create, dt_object::do_ops, LASSERT, and OBD_FAIL_DT_CREATE.
Referenced by dt_find_or_create(), lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_layout_lastid_create(), lfsck_layout_recreate_parent(), lfsck_layout_repair_dangling(), lfsck_layout_repair_multiple_references(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_repair_dangling(), llog_osd_create(), llog_osd_get_cat_list(), local_object_create(), local_oid_storage_init(), lod_sub_object_create(), mdo_create_obj(), ofd_precreate_objects(), and out_tx_create_exec().
static int dt_declare_attr_get (const struct lu_env * env, struct dt_object * dt) [inline, static]
Definition at line 2212 of file dt_object.h.
References cfs_fail_err, CFS_FAULT_CHECK, dt_object_operations::do_declare_attr_get, dt_object::do_ops, LASSERT, and OBD_FAIL_DT_DECLARE_ATTR_GET.
Referenced by lfsck_layout_scan_stripes().
static int dt_declare_attr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_attr * la, struct thandle * th) [inline, static]
Definition at line 2238 of file dt_object.h.
References cfs_fail_err, CFS_FAULT_CHECK, dt_object_operations::do_declare_attr_set, dt_object::do_ops, LASSERT, and OBD_FAIL_DT_DECLARE_ATTR_SET.
Referenced by lfsck_disable_master_lmv(), lfsck_layout_repair_owner(), lfsck_layout_repair_unmatched_pair(), lfsck_namespace_insert_normal(), lfsck_namespace_insert_orphan(), lfsck_namespace_repair_nlink(), lfsck_namespace_scan_local_lpf_one(), llog_truncate(), lod_sub_object_declare_attr_set(), mdo_declare_attr_set(), ofd_attr_set(), ofd_commitrw_write(), ofd_object_punch(), ofd_write_attr_set(), out_attr_set_add_exec(), and tgt_truncate_last_rcvd().
static int dt_declare_create (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof, struct thandle * th) [inline, static]
Definition at line 2103 of file dt_object.h.
References cfs_fail_err, CFS_FAULT_CHECK, dt_object_operations::do_declare_create, dt_object::do_ops, LASSERT, and OBD_FAIL_DT_DECLARE_CREATE.
Referenced by dt_find_or_create(), lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_layout_lastid_create(), lfsck_layout_recreate_parent(), lfsck_layout_repair_dangling(), lfsck_layout_repair_multiple_references(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_repair_dangling(), llog_osd_declare_create(), llog_osd_get_cat_list(), local_object_declare_create(), local_oid_storage_init(), lod_sub_object_declare_create(), mdo_declare_create_obj(), ofd_precreate_objects(), and out_create_add_exec().
static int dt_declare_delete (const struct lu_env * env, struct dt_object * dt, const struct dt_key * key, struct thandle * th) [inline, static]
Definition at line 2615 of file dt_object.h.
References cfs_fail_err, CFS_FAULT_CHECK, dt_index_operations::dio_declare_delete, dt_object::do_index_ops, LASSERT, and OBD_FAIL_DT_DECLARE_DELETE.
Referenced by fld_declare_index_create(), lfsck_lpf_remove_name_entry(), lfsck_namespace_in_notify(), lfsck_namespace_insert_orphan(), lfsck_namespace_repair_dirent(), lfsck_namespace_repair_unmatched_pairs(), lfsck_namespace_replace_cond(), lfsck_namespace_scan_local_lpf_one(), lfsck_namespace_trace_update(), lfsck_update_name_entry(), llog_osd_declare_destroy(), llog_osd_regular_fid_del_name_entry(), local_object_declare_unlink(), lod_sub_object_declare_delete(), lquota_disk_declare_write(), lquota_disk_write_glb(), mdo_declare_index_delete(), nodemap_idx_delete(), nodemap_idx_update(), orph_declare_index_delete(), and out_index_delete_add_exec().
static int dt_declare_destroy (const struct lu_env * env, struct dt_object * dt, struct thandle * th) [inline, static]
Definition at line 2137 of file dt_object.h.
References cfs_fail_err, CFS_FAULT_CHECK, dt_object_operations::do_declare_destroy, dt_object::do_ops, LASSERT, and OBD_FAIL_DT_DECLARE_DESTROY.
Referenced by lfsck_layout_destroy_orphan(), lfsck_layout_slave_conditional_destroy(), lfsck_namespace_replace_cond(), llog_osd_declare_destroy(), local_object_declare_unlink(), lod_sub_object_declare_destroy(), mdo_declare_destroy(), ofd_object_destroy(), and out_destroy_add_exec().
static int dt_declare_insert (const struct lu_env * env, struct dt_object * dt, const struct dt_rec * rec, const struct dt_key * key, struct thandle * th) [inline, static]
Definition at line 2481 of file dt_object.h.
References cfs_fail_err, CFS_FAULT_CHECK, dt_index_operations::dio_declare_insert, dt_object::do_index_ops, LASSERT, and OBD_FAIL_DT_DECLARE_INSERT.
Referenced by __local_file_create(), fld_declare_index_create(), lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_layout_recreate_parent(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_in_notify(), lfsck_namespace_insert_normal(), lfsck_namespace_insert_orphan(), lfsck_namespace_repair_dangling(), lfsck_namespace_repair_dirent(), lfsck_namespace_repair_unmatched_pairs(), lfsck_namespace_replace_cond(), lfsck_namespace_scan_local_lpf_one(), lfsck_namespace_trace_update(), lfsck_update_name_entry(), llog_osd_declare_create(), llog_osd_regular_fid_add_name_entry(), lod_sub_object_declare_insert(), lquota_disk_declare_write(), lquota_disk_write_glb(), mdo_declare_index_insert(), nodemap_idx_insert(), nodemap_idx_update(), orph_declare_index_insert(), and out_index_insert_add_exec().
static int dt_declare_punch (const struct lu_env * env, struct dt_object * dt, __u64 start, __u64 end, struct thandle * th) [inline, static]
Definition at line 2398 of file dt_object.h.
References dt_body_operations::dbo_declare_punch, dt_object::do_body_ops, and LASSERT.
Referenced by llog_truncate(), lod_sub_object_declare_punch(), ofd_object_punch(), and tgt_truncate_last_rcvd().
static int dt_declare_record_write (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, loff_t pos, struct thandle * th) [inline, static]
Definition at line 2087 of file dt_object.h.
References dt_body_operations::dbo_declare_write, dt_object::do_body_ops, LASSERT, and LASSERTF.
Referenced by distribute_txn_commit_batchid_update(), lfsck_bookmark_store(), lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_layout_lastid_create(), lfsck_layout_lastid_store(), lfsck_layout_store(), llog_osd_declare_write_rec(), llog_osd_put_cat_list(), local_object_declare_create(), local_oid_storage_init(), mdd_declare_migrate_create(), mdd_declare_object_create(), nidtbl_update_version(), ofd_health_check(), ofd_precreate_objects(), ofd_seq_last_oid_write(), osp_declare_object_create(), osp_write_last_oid_seq_files(), osp_write_local_file(), out_write_add_exec(), seq_store_update(), tgt_client_data_update(), tgt_reply_header_write(), tgt_server_data_update(), and tgt_txn_start_cb().
static int dt_declare_ref_add (const struct lu_env * env, struct dt_object * dt, struct thandle * th) [inline, static]
Definition at line 2266 of file dt_object.h.
References cfs_fail_err, CFS_FAULT_CHECK, dt_object_operations::do_declare_ref_add, dt_object::do_ops, LASSERT, and OBD_FAIL_DT_DECLARE_REF_ADD.
Referenced by __local_file_create(), lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_insert_normal(), lfsck_namespace_insert_orphan(), lfsck_namespace_repair_dangling(), lfsck_update_name_entry(), lod_sub_object_declare_ref_add(), mdo_declare_ref_add(), orph_declare_index_insert(), and out_ref_add_add_exec().
static int dt_declare_ref_del (const struct lu_env * env, struct dt_object * dt, struct thandle * th) [inline, static]
Definition at line 2292 of file dt_object.h.
References cfs_fail_err, CFS_FAULT_CHECK, dt_object_operations::do_declare_ref_del, dt_object::do_ops, LASSERT, and OBD_FAIL_DT_DECLARE_REF_DEL.
Referenced by lfsck_layout_destroy_orphan(), lfsck_layout_slave_conditional_destroy(), lfsck_lpf_remove_name_entry(), lfsck_namespace_repair_dirent(), lfsck_namespace_scan_local_lpf_one(), llog_osd_declare_destroy(), local_object_declare_unlink(), lod_sub_object_declare_ref_del(), mdo_declare_ref_del(), ofd_object_destroy(), orph_declare_index_delete(), and out_ref_del_add_exec().
static int dt_declare_write (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, loff_t pos, struct thandle * th) [inline, static]
Definition at line 2377 of file dt_object.h.
References dt_body_operations::dbo_declare_write, dt_object::do_body_ops, and LASSERT.
Referenced by lod_sub_object_declare_write().
static int dt_declare_write_commit (const struct lu_env * env, struct dt_object * d, struct niobuf_local * lnb, int n, struct thandle * th) [inline, static]
Definition at line 2347 of file dt_object.h.
References dt_body_operations::dbo_declare_write_commit, dt_object::do_body_ops, LASSERT, and LASSERTF.
Referenced by ofd_commitrw_write().
static int dt_declare_xattr_del (const struct lu_env * env, struct dt_object * dt, const char * name, struct thandle * th) [inline, static]
Definition at line 2514 of file dt_object.h.
References cfs_fail_err, CFS_FAULT_CHECK, dt_object_operations::do_declare_xattr_del, dt_object::do_ops, LASSERT, and OBD_FAIL_DT_DECLARE_XATTR_DEL.
Referenced by lfsck_declare_namespace_exec_dir(), lfsck_disable_master_lmv(), lfsck_namespace_links_remove(), lod_sub_object_declare_xattr_del(), mdo_declare_xattr_del(), and out_xattr_del_add_exec().
static int dt_declare_xattr_get (const struct lu_env * env, struct dt_object * dt, struct lu_buf * buf, const char * name) [inline, static]
Definition at line 2573 of file dt_object.h.
References cfs_fail_err, CFS_FAULT_CHECK, dt_object_operations::do_declare_xattr_get, dt_object::do_ops, LASSERT, and OBD_FAIL_DT_DECLARE_XATTR_GET.
Referenced by lfsck_layout_scan_stripes().
static int dt_declare_xattr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, const char * name, int fl, struct thandle * th) [inline, static]
Definition at line 2543 of file dt_object.h.
References cfs_fail_err, CFS_FAULT_CHECK, dt_object_operations::do_declare_xattr_set, dt_object::do_ops, LASSERT, and OBD_FAIL_DT_DECLARE_XATTR_SET.
Referenced by __lfsck_layout_update_pfid(), dt_declare_version_set(), lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_declare_namespace_exec_dir(), lfsck_layout_conflict_create(), lfsck_layout_master_exec_oit(), lfsck_layout_recreate_lovea(), lfsck_layout_recreate_parent(), lfsck_layout_repair_dangling(), lfsck_layout_repair_multiple_references(), lfsck_layout_repair_unmatched_pair(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_insert_orphan(), lfsck_namespace_rebuild_linkea(), lfsck_namespace_repair_dangling(), lfsck_namespace_repair_unmatched_pairs(), lfsck_namespace_shrink_linkea(), lfsck_namespace_store(), lfsck_namespace_update_lmv(), lfsck_verify_linkea(), local_object_declare_create(), lod_sub_object_declare_xattr_set(), mdd_create_data(), mdo_declare_xattr_set(), ofd_attr_set(), ofd_object_punch(), ofd_write_attr_set(), and out_xattr_set_add_exec().
static int dt_delete (const struct lu_env * env, struct dt_object * dt, const struct dt_key * key, struct thandle * th) [inline, static]
Definition at line 2630 of file dt_object.h.
References cfs_fail_err, CFS_FAULT_CHECK, dt_index_operations::dio_delete, dt_object::do_index_ops, LASSERT, and OBD_FAIL_DT_DELETE.
Referenced by __mdd_index_delete_only(), fld_index_create(), lfsck_lpf_remove_name_entry(), lfsck_namespace_in_notify(), lfsck_namespace_insert_orphan(), lfsck_namespace_repair_dirent(), lfsck_namespace_repair_unmatched_pairs(), lfsck_namespace_replace_cond(), lfsck_namespace_scan_local_lpf_one(), lfsck_namespace_trace_update(), lfsck_update_name_entry(), llog_osd_destroy(), llog_osd_regular_fid_del_name_entry(), local_object_unlink(), lod_sub_object_delete(), lquota_disk_write(), lquota_disk_write_glb(), mdd_orphan_delete_obj(), nodemap_idx_delete(), nodemap_idx_update(), orph_index_insert(), and out_obj_index_delete().
static int dt_destroy (const struct lu_env * env, struct dt_object * dt, struct thandle * th) [inline, static]
Definition at line 2151 of file dt_object.h.
References cfs_fail_err, CFS_FAULT_CHECK, dt_object_operations::do_destroy, dt_object::do_ops, LASSERT, and OBD_FAIL_DT_DESTROY.
Referenced by __local_file_create(), lfsck_layout_destroy_orphan(), lfsck_layout_slave_conditional_destroy(), lfsck_namespace_replace_cond(), llog_osd_destroy(), local_object_unlink(), lod_sub_object_destroy(), mdo_destroy(), ofd_object_destroy(), and out_obj_destroy().
static int dt_fiemap_get (const struct lu_env * env, struct dt_object * d, struct fiemap * fm) [inline, static]
Definition at line 2426 of file dt_object.h.
References dt_body_operations::dbo_fiemap_get, dt_object::do_body_ops, and LASSERT.
Referenced by ofd_fiemap_get().
void dt_global_fini (void)
Definition at line 453 of file dt_object.c.
References lu_context_key_degister().
Referenced by obdclass_exit().
int dt_global_init (void)
Definition at line 444 of file dt_object.c.
References LU_CONTEXT_KEY_INIT, and lu_context_key_register().
Referenced by obdclass_init().
static struct dt_thread_info* dt_info (const struct lu_env * env) [static, read]
Definition at line 2711 of file dt_object.h.
References dt_key, LASSERT, lu_env::le_ctx, and lu_context_key_get().
Referenced by __local_file_create(), dt_store_resolve(), lastid_compat_check(), llog_osd_dir_get(), local_file_find_or_create(), local_file_find_or_create_with_fid(), local_index_find_or_create(), local_index_find_or_create_with_fid(), local_object_create(), local_object_declare_create(), local_object_unlink(), and local_oid_storage_init().
static int dt_insert (const struct lu_env * env, struct dt_object * dt, const struct dt_rec * rec, const struct dt_key * key, struct thandle * th, int noquota) [inline, static]
Definition at line 2497 of file dt_object.h.
References cfs_fail_err, CFS_FAULT_CHECK, dt_index_operations::dio_insert, dt_object::do_index_ops, LASSERT, and OBD_FAIL_DT_INSERT.
Referenced by __local_file_create(), __mdd_index_insert_only(), fld_index_create(), lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_layout_recreate_parent(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_in_notify(), lfsck_namespace_insert_normal(), lfsck_namespace_insert_orphan(), lfsck_namespace_repair_dangling(), lfsck_namespace_repair_dirent(), lfsck_namespace_repair_unmatched_pairs(), lfsck_namespace_replace_cond(), lfsck_namespace_scan_local_lpf_one(), lfsck_namespace_trace_update(), lfsck_update_name_entry(), llog_osd_create(), llog_osd_regular_fid_add_name_entry(), local_object_unlink(), lod_sub_object_index_insert(), lquota_disk_write(), lquota_disk_write_glb(), mdd_orphan_insert_obj(), nodemap_idx_insert(), nodemap_idx_update(), orph_index_insert(), and out_obj_index_insert().
static int dt_ladvise (const struct lu_env * env, struct dt_object * dt, __u64 start, __u64 end, int advice) [inline, static]
Definition at line 2417 of file dt_object.h.
References dt_body_operations::dbo_ladvise, dt_object::do_body_ops, and LASSERT.
static int dt_lookup (const struct lu_env * env, struct dt_object * dt, struct dt_rec * rec, const struct dt_key * key) [inline, static]
Definition at line 2654 of file dt_object.h.
References cfs_fail_err, CFS_FAULT_CHECK, dt_index_operations::dio_lookup, dt_object::do_index_ops, LASSERT, OBD_FAIL_DT_LOOKUP, and ret.
Referenced by __mdd_lookup(), dt_lookup_dir(), lfsck_allow_regenerate_master_lmv(), lfsck_create_lpf(), lfsck_layout_recreate_parent(), lfsck_namespace_check_exist(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_double_scan_dir(), lfsck_namespace_double_scan_one(), lfsck_namespace_dsd_multiple(), lfsck_namespace_dsd_single(), lfsck_namespace_in_notify(), lfsck_namespace_insert_orphan(), lfsck_namespace_repair_bad_name_hash(), lfsck_namespace_repair_dirent(), lfsck_namespace_repair_nlink(), lfsck_namespace_replace_cond(), lfsck_namespace_scan_local_lpf_one(), lfsck_namespace_shrink_linkea_cond(), lfsck_namespace_trace_update(), lfsck_namespace_verify_stripe_slave(), lfsck_parent_fid(), lfsck_register(), lfsck_verify_lpf(), lfsck_verify_lpf_pairs(), lquota_disk_read(), lquota_disk_write(), lquota_disk_write_glb(), lquotactl_slv(), mdd_migrate_entries(), and out_index_lookup().
static int dt_punch (const struct lu_env * env, struct dt_object * dt, __u64 start, __u64 end, struct thandle * th) [inline, static]
Definition at line 2408 of file dt_object.h.
References dt_body_operations::dbo_punch, dt_object::do_body_ops, and LASSERT.
Referenced by llog_truncate(), lod_sub_object_punch(), ofd_object_punch(), and tgt_truncate_last_rcvd().
static void dt_read_lock (const struct lu_env * env, struct dt_object * dt, unsigned role) [inline, static]
Definition at line 2165 of file dt_object.h.
References dt_object::do_ops, dt_object_operations::do_read_lock, and LASSERT.
Referenced by dt_index_read(), lastid_compat_check(), lfsck_layout_check_parent(), lfsck_layout_lastid_load(), lfsck_layout_lastid_reload(), lfsck_layout_master_check_pairs(), lfsck_layout_master_exec_oit(), lfsck_layout_repair_dangling(), lfsck_layout_repair_owner(), lfsck_layout_slave_conditional_destroy(), lfsck_namespace_double_scan_dir(), lfsck_namespace_double_scan_one(), lfsck_namespace_replace_cond(), lfsck_namespace_shrink_linkea_cond(), lfsck_needs_scan_dir(), lfsck_orphan_it_next(), lfsck_read_stripe_lmv(), lfsck_verify_lpf_pairs(), llog_osd_create(), llog_osd_destroy(), llog_osd_open(), local_oid_storage_init(), lod_object_read_lock(), lquota_disk_read(), mdd_read_lock(), nodemap_load_entries(), out_attr_get(), out_index_lookup(), out_read(), and out_xattr_get().
static int dt_read_prep (const struct lu_env * env, struct dt_object * d, struct niobuf_local * lnb, int n) [inline, static]
Definition at line 2368 of file dt_object.h.
References dt_body_operations::dbo_read_prep, dt_object::do_body_ops, and LASSERT.
Referenced by ofd_preprw_read().
static void dt_read_unlock (const struct lu_env * env, struct dt_object * dt) [inline, static]
Definition at line 2185 of file dt_object.h.
References dt_object::do_ops, dt_object_operations::do_read_unlock, and LASSERT.
Referenced by dt_index_read(), lastid_compat_check(), lfsck_layout_check_parent(), lfsck_layout_lastid_load(), lfsck_layout_lastid_reload(), lfsck_layout_master_check_pairs(), lfsck_layout_master_exec_oit(), lfsck_layout_repair_dangling(), lfsck_layout_repair_owner(), lfsck_layout_slave_conditional_destroy(), lfsck_namespace_double_scan_dir(), lfsck_namespace_double_scan_one(), lfsck_namespace_replace_cond(), lfsck_namespace_shrink_linkea_cond(), lfsck_needs_scan_dir(), lfsck_orphan_it_next(), lfsck_read_stripe_lmv(), lfsck_verify_lpf_pairs(), llog_osd_create(), llog_osd_destroy(), llog_osd_open(), local_oid_storage_init(), lod_object_read_unlock(), lquota_disk_read(), mdd_read_unlock(), nodemap_load_entries(), out_attr_get(), out_index_lookup(), out_read(), and out_xattr_get().
static int dt_ref_add (const struct lu_env * env, struct dt_object * dt, struct thandle * th) [inline, static]
Definition at line 2279 of file dt_object.h.
References cfs_fail_err, CFS_FAULT_CHECK, dt_object::do_ops, dt_object_operations::do_ref_add, LASSERT, and OBD_FAIL_DT_REF_ADD.
Referenced by __local_file_create(), lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_insert_normal(), lfsck_namespace_insert_orphan(), lfsck_namespace_repair_dangling(), lfsck_update_name_entry(), lod_sub_object_ref_add(), mdd_orphan_ref_add(), mdo_ref_add(), and out_obj_ref_add().
static int dt_ref_del (const struct lu_env * env, struct dt_object * dt, struct thandle * th) [inline, static]
Definition at line 2305 of file dt_object.h.
References cfs_fail_err, CFS_FAULT_CHECK, dt_object::do_ops, dt_object_operations::do_ref_del, LASSERT, and OBD_FAIL_DT_REF_DEL.
Referenced by lfsck_layout_destroy_orphan(), lfsck_layout_slave_conditional_destroy(), lfsck_lpf_remove_name_entry(), lfsck_namespace_repair_dirent(), lfsck_namespace_scan_local_lpf_one(), llog_osd_destroy(), local_object_unlink(), lod_sub_object_ref_del(), mdd_orphan_ref_del(), mdo_ref_del(), ofd_object_destroy(), and out_obj_ref_del().
static int dt_ro (const struct lu_env * env, struct dt_device * dev) [inline, static]
Definition at line 2473 of file dt_object.h.
References dt_device::dd_ops, dt_device_operations::dt_ro, and LASSERT.
Referenced by lod_ro(), and ofd_iocontrol().
static int dt_root_get (const struct lu_env * env, struct dt_device * dev, struct lu_fid * f) [inline, static]
Definition at line 2446 of file dt_object.h.
References dt_device::dd_ops, dt_device_operations::dt_root_get, and LASSERT.
Referenced by lastid_compat_check(), lfsck_register(), llog_osd_dir_get(), lod_prepare(), lod_root_get(), lod_xattr_get(), lquota_disk_dir_find_create(), mdd_prepare(), mdt_getattr_internal(), mdt_orphan_open(), mgc_fs_setup(), mgs_fs_setup(), and osd_quota_migration().
static int dt_statfs (const struct lu_env * env, struct dt_device * dev, struct obd_statfs * osfs) [inline, static]
Definition at line 2437 of file dt_object.h.
References dt_device::dd_ops, dt_device_operations::dt_statfs, and LASSERT.
Referenced by lod_prep_md_striped_create(), lod_statfs(), lod_statfs_and_check(), ofd_health_check(), ofd_statfs_internal(), and server_statfs().
static int dt_sync (const struct lu_env * env, struct dt_device * dev) [inline, static]
Definition at line 2465 of file dt_object.h.
References dt_device::dd_ops, dt_device_operations::dt_sync, and LASSERT.
Referenced by lfsck_assistant_engine(), llog_test_10(), lod_sync(), mgs_target_reg(), ofd_fs_cleanup(), ofd_grant_prepare_write(), ofd_iocontrol(), osd_declare_write_commit(), and tgt_sync().
static ssize_t dt_write (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, loff_t * pos, struct thandle * th, int rq) [inline, static]
Definition at line 2388 of file dt_object.h.
References dt_body_operations::dbo_write, dt_object::do_body_ops, and LASSERT.
Referenced by lod_sub_object_write().
static int dt_write_commit (const struct lu_env * env, struct dt_object * d, struct niobuf_local * lnb, int n, struct thandle * th) [inline, static]
Definition at line 2358 of file dt_object.h.
References dt_body_operations::dbo_write_commit, dt_object::do_body_ops, and LASSERT.
Referenced by ofd_commitrw_write().
static void dt_write_lock (const struct lu_env * env, struct dt_object * dt, unsigned role) [inline, static]
Definition at line 2175 of file dt_object.h.
References dt_object::do_ops, dt_object_operations::do_write_lock, and LASSERT.
Referenced by __local_file_create(), dt_find_or_create(), lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_disable_master_lmv(), lfsck_layout_conflict_create(), lfsck_layout_destroy_orphan(), lfsck_layout_lastid_create(), lfsck_layout_lastid_store(), lfsck_layout_master_exec_oit(), lfsck_layout_recreate_lovea(), lfsck_layout_recreate_parent(), lfsck_layout_repair_multiple_references(), lfsck_layout_repair_unmatched_pair(), lfsck_layout_slave_conditional_destroy(), lfsck_layout_slave_repair_pfid(), lfsck_lpf_remove_name_entry(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_insert_normal(), lfsck_namespace_insert_orphan(), lfsck_namespace_links_remove(), lfsck_namespace_rebuild_linkea(), lfsck_namespace_repair_dangling(), lfsck_namespace_repair_dirent(), lfsck_namespace_repair_nlink(), lfsck_namespace_repair_unmatched_pairs(), lfsck_namespace_scan_local_lpf_one(), lfsck_namespace_shrink_linkea(), lfsck_namespace_update_lmv(), lfsck_update_name_entry(), lfsck_verify_linkea(), llog_osd_create(), llog_osd_destroy(), llog_osd_get_cat_list(), llog_osd_regular_fid_add_name_entry(), llog_osd_regular_fid_del_name_entry(), local_object_unlink(), local_oid_storage_init(), lod_cache_parent_lmv_striping(), lod_cache_parent_lov_striping(), lod_load_striping(), lod_object_destroy(), lod_object_write_lock(), lod_xattr_set_lmv(), lquota_disk_write(), lquota_disk_write_glb(), mdd_orphan_write_lock(), mdd_write_lock(), nodemap_idx_delete(), nodemap_idx_insert(), nodemap_idx_update(), ofd_precreate_objects(), out_obj_destroy(), out_obj_index_delete(), out_obj_index_insert(), out_obj_ref_add(), out_obj_ref_del(), out_tx_attr_set_exec(), out_tx_create_exec(), out_tx_write_exec(), out_tx_xattr_del_exec(), and out_tx_xattr_set_exec().
static int dt_write_locked (const struct lu_env * env, struct dt_object * dt) [inline, static]
Definition at line 2203 of file dt_object.h.
References dt_object::do_ops, dt_object_operations::do_write_locked, and LASSERT.
Referenced by lfsck_namespace_assistant_handler_p1(), lod_object_write_locked(), and mdd_write_locked().
static int dt_write_prep (const struct lu_env * env, struct dt_object * d, struct niobuf_local * lnb, int n) [inline, static]
Definition at line 2338 of file dt_object.h.
References dt_body_operations::dbo_write_prep, dt_object::do_body_ops, and LASSERT.
Referenced by ofd_preprw_write().
static void dt_write_unlock (const struct lu_env * env, struct dt_object * dt) [inline, static]
Definition at line 2194 of file dt_object.h.
References dt_object::do_ops, dt_object_operations::do_write_unlock, and LASSERT.
Referenced by __local_file_create(), dt_find_or_create(), lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_disable_master_lmv(), lfsck_layout_conflict_create(), lfsck_layout_destroy_orphan(), lfsck_layout_lastid_create(), lfsck_layout_lastid_store(), lfsck_layout_master_exec_oit(), lfsck_layout_recreate_lovea(), lfsck_layout_recreate_parent(), lfsck_layout_repair_multiple_references(), lfsck_layout_repair_unmatched_pair(), lfsck_layout_slave_conditional_destroy(), lfsck_layout_slave_repair_pfid(), lfsck_lpf_remove_name_entry(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_insert_normal(), lfsck_namespace_insert_orphan(), lfsck_namespace_links_remove(), lfsck_namespace_rebuild_linkea(), lfsck_namespace_repair_dangling(), lfsck_namespace_repair_dirent(), lfsck_namespace_repair_nlink(), lfsck_namespace_repair_unmatched_pairs(), lfsck_namespace_scan_local_lpf_one(), lfsck_namespace_shrink_linkea(), lfsck_namespace_update_lmv(), lfsck_update_name_entry(), lfsck_verify_linkea(), llog_osd_create(), llog_osd_destroy(), llog_osd_get_cat_list(), llog_osd_regular_fid_add_name_entry(), llog_osd_regular_fid_del_name_entry(), local_object_unlink(), local_oid_storage_init(), lod_cache_parent_lmv_striping(), lod_cache_parent_lov_striping(), lod_load_striping(), lod_object_destroy(), lod_object_write_unlock(), lod_xattr_set_lmv(), lquota_disk_write(), lquota_disk_write_glb(), mdd_orphan_write_unlock(), mdd_write_unlock(), nodemap_idx_delete(), nodemap_idx_insert(), nodemap_idx_update(), ofd_precreate_objects(), out_obj_destroy(), out_obj_index_delete(), out_obj_index_insert(), out_obj_ref_add(), out_obj_ref_del(), out_tx_attr_set_exec(), out_tx_create_exec(), out_tx_write_exec(), out_tx_xattr_del_exec(), and out_tx_xattr_set_exec().
static int dt_xattr_del (const struct lu_env * env, struct dt_object * dt, const char * name, struct thandle * th) [inline, static]
Definition at line 2529 of file dt_object.h.
References cfs_fail_err, CFS_FAULT_CHECK, dt_object::do_ops, dt_object_operations::do_xattr_del, LASSERT, and OBD_FAIL_DT_XATTR_DEL.
Referenced by lfsck_disable_master_lmv(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_links_remove(), lod_sub_object_xattr_del(), mdo_xattr_del(), and out_tx_xattr_del_exec().
static int dt_xattr_get (const struct lu_env * env, struct dt_object * dt, struct lu_buf * buf, const char * name) [inline, static]
Definition at line 2588 of file dt_object.h.
References cfs_fail_err, CFS_FAULT_CHECK, dt_object::do_ops, dt_object_operations::do_xattr_get, LASSERT, and OBD_FAIL_DT_XATTR_GET.
Referenced by __lfsck_links_read(), dt_version_get(), fid_is_for_ostobj(), lfsck_layout_assistant_handler_p1(), lfsck_layout_check_parent(), lfsck_layout_get_def_stripesize(), lfsck_layout_get_lovea(), lfsck_layout_recreate_lovea(), lfsck_layout_repair_multiple_references(), lfsck_namespace_load(), lfsck_namespace_load_bitmap(), lfsck_namespace_replace_cond(), lfsck_needs_scan_dir(), lfsck_orphan_it_next(), lfsck_read_stripe_lmv(), lod_get_ea(), lod_object_replace_parent_fid(), lod_xattr_get(), mdo_xattr_get(), ofd_object_ff_load(), and out_xattr_get().
static int dt_xattr_list (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf) [inline, static]
Definition at line 2602 of file dt_object.h.
References cfs_fail_err, CFS_FAULT_CHECK, dt_object::do_ops, dt_object_operations::do_xattr_list, LASSERT, and OBD_FAIL_DT_XATTR_LIST.
Referenced by lod_xattr_list(), and mdo_xattr_list().
static int dt_xattr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, const char * name, int fl, struct thandle * th) [inline, static]
Definition at line 2559 of file dt_object.h.
References cfs_fail_err, CFS_FAULT_CHECK, dt_object::do_ops, dt_object_operations::do_xattr_set, LASSERT, and OBD_FAIL_DT_XATTR_SET.
Referenced by __lfsck_layout_update_pfid(), dt_version_set(), lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_layout_master_exec_oit(), lfsck_layout_recreate_parent(), lfsck_layout_refill_lovea(), lfsck_layout_repair_dangling(), lfsck_layout_repair_multiple_references(), lfsck_layout_repair_unmatched_pair(), lfsck_links_write(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_insert_orphan(), lfsck_namespace_rebuild_linkea(), lfsck_namespace_repair_dangling(), lfsck_namespace_repair_unmatched_pairs(), lfsck_namespace_shrink_linkea(), lfsck_namespace_store(), lfsck_namespace_update_lmv(), lfsck_verify_linkea(), lod_sub_object_xattr_set(), mdd_create_data(), mdo_xattr_set(), ofd_attr_set(), ofd_object_punch(), ofd_write_attr_set(), and out_tx_xattr_set_exec().
Variable Documentation
struct lu_context_key dt_key
Definition at line 58 of file dt_object.c.
Referenced by __local_file_create(), __mdd_index_delete_only(), __mdd_index_insert_only(), __mdd_lookup(), __osd_oi_lookup(), dt_info(), fld_declare_index_create(), fld_index_create(), lfsck_allow_regenerate_master_lmv(), lfsck_create_lpf(), lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_layout_recreate_parent(), lfsck_layout_scan_orphan(), lfsck_lpf_remove_name_entry(), lfsck_namespace_check_exist(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_double_scan_dir(), lfsck_namespace_double_scan_one(), lfsck_namespace_double_scan_one_trace_file(), lfsck_namespace_dsd_multiple(), lfsck_namespace_dsd_single(), lfsck_namespace_in_notify(), lfsck_namespace_insert_normal(), lfsck_namespace_insert_orphan(), lfsck_namespace_repair_bad_name_hash(), lfsck_namespace_repair_dangling(), lfsck_namespace_repair_dirent(), lfsck_namespace_repair_nlink(), lfsck_namespace_repair_unmatched_pairs(), lfsck_namespace_replace_cond(), lfsck_namespace_scan_local_lpf_one(), lfsck_namespace_shrink_linkea_cond(), lfsck_namespace_trace_update(), lfsck_namespace_verify_stripe_slave(), lfsck_orphan_it_key(), lfsck_parent_fid(), lfsck_register(), lfsck_update_name_entry(), lfsck_verify_lpf(), lfsck_verify_lpf_pairs(), llog_osd_create(), llog_osd_declare_create(), llog_osd_declare_destroy(), llog_osd_destroy(), llog_osd_regular_fid_add_name_entry(), llog_osd_regular_fid_del_name_entry(), local_object_declare_unlink(), local_object_unlink(), lod_declare_object_destroy(), lod_dir_declare_create_stripes(), lod_object_destroy(), lod_xattr_set_lmv(), lquota_disk_declare_write(), lquota_disk_for_each_slv(), lquota_disk_read(), lquota_disk_write(), lquota_disk_write_glb(), lquotactl_slv(), mdd_dir_is_empty(), mdd_migrate_entries(), mdd_orphan_insert_obj(), mdo_declare_index_delete(), mdo_declare_index_insert(), nodemap_idx_delete(), nodemap_idx_insert(), nodemap_idx_update(), orph_declare_index_delete(), orph_declare_index_insert(), orph_index_delete(), orph_index_insert(), orph_index_iterate(), orph_key_fill(), orph_key_fill_18(), osd_dir_it_key(), osd_index_iam_delete(), osd_index_iam_insert(), osd_index_iam_lookup(), osd_index_it_key(), osd_index_it_rec(), osd_it_acct_key(), osd_it_acct_load(), osd_it_acct_rec(), osd_it_ea_key(), osd_it_iam_get(), osd_it_iam_key(), osd_oi_delete(), osd_oi_insert(), osd_oi_update(), osp_it_key(), osp_orphan_it_key(), out_index_delete(), out_index_insert(), out_index_lookup(), qsd_reconciliation(), update_recovery_index_delete(), and update_recovery_index_insert().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.