Lustre: lustre/obdecho/echo.c File Reference
lustre/obdecho/echo.c File Reference
#include <obd_support.h>
#include <obd_class.h>
#include <lustre_debug.h>
#include <lustre_dlm.h>
#include <lprocfs_status.h>
#include "echo_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_ECHO
#define ECHO_INIT_OID 0x10000000ULL
#define ECHO_HANDLE_MAGIC 0xabcd0123fedc9876ULL
#define ECHO_PERSISTENT_PAGES (ECHO_PERSISTENT_SIZE >> PAGE_CACHE_SHIFT)
Enumerations
enum { LPROC_ECHO_READ_BYTES = 1, LPROC_ECHO_WRITE_BYTES = 2, LPROC_ECHO_LAST = LPROC_ECHO_WRITE_BYTES +1 }
Functions
static int echo_connect (const struct lu_env *env, struct obd_export **exp, struct obd_device *obd, struct obd_uuid *cluuid, struct obd_connect_data *data, void *localdata)
static int echo_disconnect (struct obd_export *exp)
static int echo_init_export (struct obd_export *exp)
static int echo_destroy_export (struct obd_export *exp)
static u64 echo_next_id (struct obd_device *obddev)
static int echo_create (const struct lu_env *env, struct obd_export *exp, struct obdo *oa)
static int echo_destroy (const struct lu_env *env, struct obd_export *exp, struct obdo *oa)
static int echo_getattr (const struct lu_env *env, struct obd_export *exp, struct obdo *oa)
static int echo_setattr (const struct lu_env *env, struct obd_export *exp, struct obdo *oa)
static void echo_page_debug_setup (struct page *page, int rw, u64 id, __u64 offset, int len)
static int echo_page_debug_check (struct page *page, u64 id, __u64 offset, int len)
static int echo_map_nb_to_lb (struct obdo *oa, struct obd_ioobj *obj, struct niobuf_remote *nb, int *pages, struct niobuf_local *lb, int cmd, int *left)
static int echo_finalize_lb (struct obdo *oa, struct obd_ioobj *obj, struct niobuf_remote *rb, int *pgs, struct niobuf_local *lb, int verify)
static int echo_preprw (const struct lu_env *env, int cmd, struct obd_export *export, struct obdo *oa, int objcount, struct obd_ioobj *obj, struct niobuf_remote *nb, int *pages, struct niobuf_local *res)
static int echo_commitrw (const struct lu_env *env, int cmd, struct obd_export *export, struct obdo *oa, int objcount, struct obd_ioobj *obj, struct niobuf_remote *rb, int niocount, struct niobuf_local *res, int rc)
LPROC_SEQ_FOPS_RO_TYPE (echo, uuid)
static int echo_setup (struct obd_device *obd, struct lustre_cfg *lcfg)
static int echo_cleanup (struct obd_device *obd)
void echo_persistent_pages_fini (void)
int echo_persistent_pages_init (void)
Variables
static struct page * echo_persistent_pages [ECHO_PERSISTENT_PAGES]
static struct lprocfs_vars lprocfs_echo_obd_vars []
struct obd_ops echo_obd_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_ECHO
Definition at line 42 of file echo.c.
#define ECHO_HANDLE_MAGIC 0xabcd0123fedc9876ULL
Definition at line 55 of file echo.c.
#define ECHO_INIT_OID 0x10000000ULL
Definition at line 54 of file echo.c.
Referenced by echo_destroy(), and echo_setup().
#define ECHO_PERSISTENT_PAGES (ECHO_PERSISTENT_SIZE >> PAGE_CACHE_SHIFT)
Definition at line 57 of file echo.c.
Referenced by echo_map_nb_to_lb(), echo_persistent_pages_fini(), and echo_persistent_pages_init().
Enumeration Type Documentation
anonymous enum
Enumerator:
LPROC_ECHO_READ_BYTES
LPROC_ECHO_WRITE_BYTES
LPROC_ECHO_LAST
Definition at line 60 of file echo.c.
Function Documentation
static int echo_cleanup (struct obd_device * obd) [static]
Definition at line 592 of file echo.c.
References CERROR, cfs_time_seconds(), ENTRY, LCK_NL, ldlm_lock_decref(), ldlm_namespace_free(), lprocfs_free_obd_stats(), lprocfs_obd_cleanup(), obd_device::obd_force, obd_device::obd_namespace, RETURN, and obd_device::u.
static int echo_commitrw (const struct lu_env * env, int cmd, struct obd_export * export, struct obdo * oa, int objcount, struct obd_ioobj * obj, struct niobuf_remote * rb, int niocount, struct niobuf_local * res, int rc) [static]
Definition at line 463 of file echo.c.
References CDEBUG, CERROR, D_PAGE, echo_finalize_lb(), ECHO_PERSISTENT_OBJID, ENTRY, obd_export::exp_obd, GOTO, obd_ioobj::ioo_bufcnt, obd_ioobj::ioo_oid, niobuf_local::lnb_page, obdo::o_flags, obdo::o_valid, OBD_BRW_READ, OBD_BRW_RWMASK, OBD_FL_DEBUG_CHECK, OBD_MD_FLFLAGS, ostid_id(), RETURN, and obd_device::u.
static int echo_connect (const struct lu_env * env, struct obd_export ** exp, struct obd_device * obd, struct obd_uuid * cluuid, struct obd_connect_data * data, void * localdata) [static]
Definition at line 66 of file echo.c.
References CERROR, class_conn2export(), class_connect(), ECHO_CONNECT_SUPPORTED, and obd_connect_data::ocd_connect_flags.
static int echo_create (const struct lu_env * env, struct obd_export * exp, struct obdo * oa) [static]
Definition at line 118 of file echo.c.
References CERROR, class_exp2obd(), echo_next_id(), obd_export::exp_handle, portals_handle::h_cookie, LPX64, obdo::o_mode, obdo::o_oi, obdo::o_valid, OBD_MD_FLID, OBD_MD_FLTYPE, ostid_set_id(), and ostid_set_seq_echo().
static int echo_destroy (const struct lu_env * env, struct obd_export * exp, struct obdo * oa) [static]
Definition at line 146 of file echo.c.
References CERROR, class_exp2obd(), DOSTID, ECHO_INIT_OID, ENTRY, obd_export::exp_handle, portals_handle::h_cookie, LPX64, obdo::o_oi, obdo::o_valid, OBD_MD_FLID, ostid_id(), POSTID, RETURN, and obd_device::u.
static int echo_destroy_export (struct obd_export * exp) [static]
Definition at line 97 of file echo.c.
References ENTRY, ldlm_destroy_export(), and RETURN.
static int echo_disconnect (struct obd_export * exp) [static]
Definition at line 85 of file echo.c.
References LASSERT.
static int echo_finalize_lb (struct obdo * oa, struct obd_ioobj * obj, struct niobuf_remote * rb, int * pgs, struct niobuf_local * lb, int verify) [static]
Definition at line 343 of file echo.c.
References CDEBUG, CERROR, D_PAGE, echo_page_debug_check(), end, obd_ioobj::ioo_bufcnt, obd_ioobj::ioo_oid, niobuf_local::lnb_file_offset, niobuf_local::lnb_len, niobuf_local::lnb_page, LPU64, ostid_id(), niobuf_remote::rnb_len, niobuf_remote::rnb_offset, and start.
Referenced by echo_commitrw().
static int echo_getattr (const struct lu_env * env, struct obd_export * exp, struct obdo * oa) [static]
Definition at line 172 of file echo.c.
References CERROR, class_exp2obd(), ENTRY, obd_export::exp_handle, portals_handle::h_cookie, LPX64, obdo::o_oi, obdo::o_valid, OBD_MD_FLID, obdo_cpy_md(), ostid_id(), ostid_set_id(), ostid_set_seq_echo(), RETURN, and obd_device::u.
static int echo_init_export (struct obd_export * exp) [static]
Definition at line 92 of file echo.c.
References ldlm_init_export().
static int echo_map_nb_to_lb (struct obdo * oa, struct obd_ioobj * obj, struct niobuf_remote * nb, int * pages, struct niobuf_local * lb, int cmd, int * left) [static]
Definition at line 275 of file echo.c.
References CDEBUG, CERROR, D_PAGE, DOSTID, echo_page_debug_setup(), ECHO_PERSISTENT_OBJID, echo_persistent_pages, ECHO_PERSISTENT_PAGES, obd_ioobj::ioo_oid, LASSERT, niobuf_local::lnb_file_offset, niobuf_local::lnb_len, niobuf_local::lnb_page, niobuf_local::lnb_rc, LPU64, obdo::o_flags, obdo::o_valid, OBD_BRW_READ, OBD_FL_DEBUG_CHECK, OBD_MD_FLFLAGS, ostid_id(), POSTID, niobuf_remote::rnb_len, and niobuf_remote::rnb_offset.
Referenced by echo_preprw().
static u64 echo_next_id (struct obd_device * obddev) [static]
Definition at line 107 of file echo.c.
References obd_device::u.
Referenced by echo_create().
static int echo_page_debug_check (struct page * page, u64 id, __u64 offset, int len) [static]
Definition at line 247 of file echo.c.
References block_debug_check(), CERROR, and OBD_ECHO_BLOCK_SIZE.
Referenced by echo_finalize_lb().
static void echo_page_debug_setup (struct page * page, int rw, u64 id, __u64 offset, int len) [static]
Definition at line 220 of file echo.c.
References block_debug_setup(), CERROR, OBD_BRW_READ, and OBD_ECHO_BLOCK_SIZE.
Referenced by echo_map_nb_to_lb().
void echo_persistent_pages_fini (void)
Definition at line 633 of file echo.c.
References echo_persistent_pages, and ECHO_PERSISTENT_PAGES.
Referenced by echo_persistent_pages_init(), obdecho_exit(), and obdecho_init().
int echo_persistent_pages_init (void)
Definition at line 644 of file echo.c.
References echo_persistent_pages, ECHO_PERSISTENT_PAGES, and echo_persistent_pages_fini().
Referenced by obdecho_init().
static int echo_preprw (const struct lu_env * env, int cmd, struct obd_export * export, struct obdo * oa, int objcount, struct obd_ioobj * obj, struct niobuf_remote * nb, int * pages, struct niobuf_local * res) [static]
Definition at line 389 of file echo.c.
References CDEBUG, CERROR, D_PAGE, echo_map_nb_to_lb(), ENTRY, obd_export::exp_obd, GOTO, obd_ioobj::ioo_bufcnt, niobuf_local::lnb_page, LPROC_ECHO_READ_BYTES, LPROC_ECHO_WRITE_BYTES, lprocfs_counter_add(), obdo::o_valid, OBD_BRW_READ, OBD_MD_FLBLOCKS, OBD_MD_FLGRANT, obd_device::obd_stats, RETURN, niobuf_remote::rnb_len, and obd_device::u.
static int echo_setattr (const struct lu_env * env, struct obd_export * exp, struct obdo * oa) [static]
Definition at line 197 of file echo.c.
References CERROR, class_exp2obd(), ENTRY, obd_export::exp_handle, portals_handle::h_cookie, LPX64, obdo::o_valid, OBD_MD_FLID, RETURN, and obd_device::u.
static int echo_setup (struct obd_device * obd, struct lustre_cfg * lcfg) [static]
Definition at line 548 of file echo.c.
References __u64, ECHO_INIT_OID, ELDLM_OK, ENTRY, LASSERT, LBUG, LCK_NL, LDLM_CB_REPLY_PORTAL, LDLM_CB_REQUEST_PORTAL, ldlm_cli_enqueue_local(), ldlm_completion_ast(), LDLM_NAMESPACE_MODEST, ldlm_namespace_new(), LDLM_NAMESPACE_SERVER, LDLM_NS_TYPE_OST, LDLM_PLAIN, LPROC_ECHO_LAST, LPROC_ECHO_READ_BYTES, LPROC_ECHO_WRITE_BYTES, lprocfs_alloc_obd_stats(), LPROCFS_CNTR_AVGMINMAX, lprocfs_counter_init(), lprocfs_obd_setup(), LVB_T_NONE, ldlm_res_id::name, obd_device::obd_ldlm_client, obd_device::obd_namespace, obd_device::obd_stats, obd_device::obd_uuid, obd_device::obd_vars, OBT_MAGIC, ptlrpc_init_client(), RETURN, obd_device::u, and obd_uuid::uuid.
LPROC_SEQ_FOPS_RO_TYPE (echo , uuid)
Variable Documentation
struct obd_ops echo_obd_ops
Initial value:
 {
        .o_owner           = THIS_MODULE,
        .o_connect         = echo_connect,
        .o_disconnect      = echo_disconnect,
        .o_init_export     = echo_init_export,
        .o_destroy_export  = echo_destroy_export,
        .o_create          = echo_create,
        .o_destroy         = echo_destroy,
        .o_getattr         = echo_getattr,
        .o_setattr         = echo_setattr,
        .o_preprw          = echo_preprw,
        .o_commitrw        = echo_commitrw,
        .o_setup           = echo_setup,
        .o_cleanup         = echo_cleanup
}
Definition at line 617 of file echo.c.
Referenced by obdecho_init().
struct page* echo_persistent_pages[ECHO_PERSISTENT_PAGES] [static]
Definition at line 58 of file echo.c.
Referenced by echo_map_nb_to_lb(), echo_persistent_pages_fini(), and echo_persistent_pages_init().
struct lprocfs_vars lprocfs_echo_obd_vars[] [static]
Initial value:
 {
        { .name =       "uuid",
          .fops =       &echo_uuid_fops         },
        { NULL }
}
Definition at line 542 of file echo.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.