Lustre: lustre/utils/gss/err_util.h File Reference
lustre/utils/gss/err_util.h File Reference
Functions
void initerr (char *progname, int verbosity, int fg)
void printerr (int priority, char *format,...) __attribute__((__format__(__printf__
void void print_hexl (int pri, unsigned char *cp, int length)
Function Documentation
void initerr (char * progname, int verbosity, int fg)
Definition at line 44 of file err_util.c.
References fg, and verbosity.
Referenced by main().
void void print_hexl (int pri, unsigned char * cp, int length)
Definition at line 98 of file err_util.c.
References printerr.
Referenced by gssd_refresh_lgd(), and handle_nullreq().
void printerr (int priority, char * format, ...)
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.