Lustre: lustre/ptlrpc/errno.c File Reference
lustre/ptlrpc/errno.c File Reference
#include <libcfs/libcfs.h>
#include <lustre/lustre_errno.h>
Functions
unsigned int lustre_errno_hton (unsigned int h)
unsigned int lustre_errno_ntoh (unsigned int n)
Variables
static int lustre_errno_hton_mapping []
static int lustre_errno_ntoh_mapping []
Function Documentation
unsigned int lustre_errno_hton (unsigned int h)
Definition at line 337 of file errno.c.
References ARRAY_SIZE, LUSTRE_EIO, and lustre_errno_hton_mapping.
Referenced by mdc_ioc_hsm_progress(), and ptlrpc_status_hton().
unsigned int lustre_errno_ntoh (unsigned int n)
Definition at line 360 of file errno.c.
References ARRAY_SIZE, and lustre_errno_ntoh_mapping.
Referenced by mdt_hsm_progress(), and ptlrpc_status_ntoh().
Variable Documentation
int lustre_errno_hton_mapping[] [static]
Definition at line 45 of file errno.c.
Referenced by lustre_errno_hton().
int lustre_errno_ntoh_mapping[] [static]
Definition at line 191 of file errno.c.
Referenced by lustre_errno_ntoh().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.