Lustre: lustre/ptlrpc/events.c File Reference
lustre/ptlrpc/events.c File Reference
#include <libcfs/libcfs.h>
#include <linux/kernel.h>
#include <obd_class.h>
#include <lustre_net.h>
#include <lustre_sec.h>
#include "ptlrpc_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_RPC
#define REQS_CPT_BITS(svcpt) ((svcpt)->scp_service->srv_cpt_bits)
#define REQS_SEC_SHIFT 32
#define REQS_USEC_SHIFT 16
#define REQS_SEQ_SHIFT(svcpt) REQS_CPT_BITS(svcpt)
Functions
void request_out_callback (lnet_event_t *ev)
These callbacks are invoked by LNet when something happened to underlying buffer.
void reply_in_callback (lnet_event_t *ev)
void client_bulk_callback (lnet_event_t *ev)
static void ptlrpc_req_add_history (struct ptlrpc_service_part *svcpt, struct ptlrpc_request *req)
void request_in_callback (lnet_event_t *ev)
void reply_out_callback (lnet_event_t *ev)
static void ptlrpc_master_callback (lnet_event_t *ev)
int ptlrpc_uuid_to_peer (struct obd_uuid *uuid, lnet_process_id_t *peer, lnet_nid_t *self)
void ptlrpc_ni_fini (void)
lnet_pid_t ptl_get_pid (void)
int ptlrpc_ni_init (void)
int ptlrpc_init_portals (void)
void ptlrpc_exit_portals (void)
Variables
lnet_handle_eq_t ptlrpc_eq_h
Define Documentation
#define DEBUG_SUBSYSTEM S_RPC
Definition at line 37 of file events.c.
#define REQS_CPT_BITS (svcpt) ((svcpt)->scp_service->srv_cpt_bits)
Definition at line 248 of file events.c.
#define REQS_SEC_SHIFT 32
Definition at line 250 of file events.c.
Referenced by ptlrpc_req_add_history().
#define REQS_SEQ_SHIFT (svcpt) REQS_CPT_BITS(svcpt)
Definition at line 252 of file events.c.
Referenced by ptlrpc_req_add_history().
#define REQS_USEC_SHIFT 16
Definition at line 251 of file events.c.
Referenced by ptlrpc_req_add_history().
Function Documentation
void ptlrpc_exit_portals (void)
Definition at line 632 of file events.c.
References ptlrpc_ni_fini(), and ptlrpcd_decref().
Referenced by ptlrpc_exit(), and ptlrpc_init().
int ptlrpc_init_portals (void)
Definition at line 615 of file events.c.
References CERROR, ptlrpc_ni_fini(), ptlrpc_ni_init(), and ptlrpcd_addref().
Referenced by ptlrpc_init().
static void ptlrpc_master_callback (lnet_event_t * ev) [static]
Definition at line 480 of file events.c.
References ptlrpc_cb_id::cbid_arg, ptlrpc_cb_id::cbid_fn, client_bulk_callback(), LASSERT, lnet_event_t::md, reply_in_callback(), reply_out_callback(), request_in_callback(), request_out_callback(), and lnet_md_t::user_ptr.
Referenced by ptlrpc_ni_init().
void ptlrpc_ni_fini (void)
Definition at line 542 of file events.c.
References cfs_time_seconds(), CWARN, l_wait_event, LBUG, LNetEQFree(), LNetNIFini(), and LWI_TIMEOUT.
Referenced by ptlrpc_exit_portals(), and ptlrpc_init_portals().
int ptlrpc_ni_init (void)
Definition at line 583 of file events.c.
References CDEBUG, CERROR, D_NET, LNetEQAlloc(), LNetNIFini(), LNetNIInit(), ptl_get_pid(), and ptlrpc_master_callback().
Referenced by ptlrpc_init_portals().
static void ptlrpc_req_add_history (struct ptlrpc_service_part * svcpt, struct ptlrpc_request * req) [static]
Definition at line 254 of file events.c.
References __u64, LASSERT, list_add_tail(), REQS_SEC_SHIFT, REQS_SEQ_SHIFT, REQS_USEC_SHIFT, ptlrpc_service_part::scp_cpt, ptlrpc_service_part::scp_hist_reqs, and ptlrpc_service_part::scp_hist_seq.
Referenced by request_in_callback().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.