Lustre: lustre/fid/fid_handler.c File Reference
lustre/fid/fid_handler.c File Reference
#include <libcfs/libcfs.h>
#include <linux/module.h>
#include <obd.h>
#include <obd_class.h>
#include <dt_object.h>
#include <obd_support.h>
#include <lustre_req_layout.h>
#include <lustre_fid.h>
#include "fid_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_FID
Functions
static void seq_server_proc_fini (struct lu_server_seq *seq)
int seq_server_set_cli (const struct lu_env *env, struct lu_server_seq *seq, struct lu_client_seq *cli)
static void range_alloc (struct lu_seq_range *to, struct lu_seq_range *from, __u64 width)
static int __seq_server_alloc_super (struct lu_server_seq *seq, struct lu_seq_range *out, const struct lu_env *env)
On controller node, allocate new super sequence for regular sequence server.
int seq_server_alloc_super (struct lu_server_seq *seq, struct lu_seq_range *out, const struct lu_env *env)
int seq_server_alloc_spec (struct lu_server_seq *seq, struct lu_seq_range *spec, const struct lu_env *env)
static int __seq_set_init (const struct lu_env *env, struct lu_server_seq *seq)
static int range_alloc_set (const struct lu_env *env, struct lu_seq_range *out, struct lu_server_seq *seq)
int seq_server_check_and_alloc_super (const struct lu_env *env, struct lu_server_seq *seq)
Check if the sequence server has sequence avaible.
static int __seq_server_alloc_meta (struct lu_server_seq *seq, struct lu_seq_range *out, const struct lu_env *env)
int seq_server_alloc_meta (struct lu_server_seq *seq, struct lu_seq_range *out, const struct lu_env *env)
static int seq_server_handle (struct lu_site *site, const struct lu_env *env, __u32 opc, struct lu_seq_range *out)
static int seq_handler (struct tgt_session_info *tsi)
LU_KEY_INIT_FINI (seq, struct seq_thread_info)
LU_CONTEXT_KEY_DEFINE (seq, LCT_MD_THREAD|LCT_DT_THREAD)
static int seq_server_proc_init (struct lu_server_seq *seq)
int seq_server_init (const struct lu_env *env, struct lu_server_seq *seq, struct dt_device *dev, const char *prefix, enum lu_mgr_type type, struct seq_server_site *ss)
void seq_server_fini (struct lu_server_seq *seq, const struct lu_env *env)
int seq_site_fini (const struct lu_env *env, struct seq_server_site *ss)
int fid_server_mod_init (void)
void fid_server_mod_exit (void)
Variables
struct tgt_handler seq_handlers []
struct file_operations seq_fld_proc_seq_fops
Define Documentation
#define DEBUG_SUBSYSTEM S_FID
Definition at line 43 of file fid_handler.c.
Referenced by lustre_print_user_md(), mdt_dump_lmm(), and mdt_dump_lmv().
Function Documentation
static int __seq_server_alloc_meta (struct lu_server_seq * seq, struct lu_seq_range * out, const struct lu_env * env) [static]
Definition at line 319 of file fid_handler.c.
References CDEBUG, CERROR, D_INFO, DRANGE, ENTRY, LASSERT, lu_server_seq::lss_name, lu_server_seq::lss_space, lu_seq_range_is_sane(), PRANGE, range_alloc_set(), RETURN, and seq_server_check_and_alloc_super().
Referenced by seq_server_alloc_meta().
static int __seq_server_alloc_super (struct lu_server_seq * seq, struct lu_seq_range * out, const struct lu_env * env) [static]
On controller node, allocate new super sequence for regular sequence server.
As this super sequence controller, this node suppose to maintain fld and update index. out range always has currect mds node number of requester.
Definition at line 113 of file fid_handler.c.
References CERROR, DRANGE, ENTRY, LASSERT, LCONSOLE_INFO, lu_server_seq::lss_name, lu_server_seq::lss_space, lu_server_seq::lss_width, lu_seq_range_is_exhausted(), lu_seq_range_is_sane(), PRANGE, range_alloc(), RETURN, and seq_store_update().
Referenced by seq_server_alloc_super().
static int __seq_set_init (const struct lu_env * env, struct lu_server_seq * seq) [static]
Definition at line 188 of file fid_handler.c.
References lu_server_seq::lss_hiwater_set, lu_server_seq::lss_lowater_set, lu_server_seq::lss_set_width, lu_server_seq::lss_space, range_alloc(), and seq_store_update().
Referenced by range_alloc_set(), and seq_server_check_and_alloc_super().
void fid_server_mod_exit (void)
Definition at line 636 of file fid_handler.c.
References lu_context_key_degister().
Referenced by fid_exit().
int fid_server_mod_init (void)
Definition at line 630 of file fid_handler.c.
References LU_CONTEXT_KEY_INIT, and lu_context_key_register().
Referenced by fid_init().
LU_CONTEXT_KEY_DEFINE (seq , LCT_MD_THREAD| LCT_DT_THREAD)
LU_KEY_INIT_FINI (seq , struct seq_thread_info)
static void range_alloc (struct lu_seq_range * to, struct lu_seq_range * from, __u64 width) [inline, static]
Definition at line 96 of file fid_handler.c.
References lu_seq_range::lsr_end, lu_seq_range::lsr_start, and lu_seq_range_space().
Referenced by __seq_server_alloc_super(), __seq_set_init(), and range_alloc_set().
static int range_alloc_set (const struct lu_env * env, struct lu_seq_range * out, struct lu_server_seq * seq) [static]
Definition at line 217 of file fid_handler.c.
References __seq_set_init(), __u64, DRANGE, LASSERTF, lu_device::ld_obd, lu_site::ls_top_dev, lu_seq_range::lsr_end, lu_seq_range::lsr_start, lu_server_seq::lss_hiwater_set, lu_server_seq::lss_lowater_set, lu_server_seq::lss_need_sync, lu_server_seq::lss_set_width, lu_server_seq::lss_site, lu_server_seq::lss_space, lu_server_seq::lss_width, lu_seq_range_is_exhausted(), lu_seq_range_is_sane(), lu_seq_range_is_zero(), lu_seq_range_space(), max, OBD_FAIL_CHECK, OBD_FAIL_SEQ_ALLOC, obd_device::obd_num_exports, PRANGE, range_alloc(), RETURN, seq_store_update(), and seq_server_site::ss_lu.
Referenced by __seq_server_alloc_meta().
static int seq_handler (struct tgt_session_info * tsi) [static]
Definition at line 400 of file fid_handler.c.
References ENTRY, err_serious(), obd_export::exp_obd, LASSERT, lu_device::ld_site, lu_seq_range::lsr_flags, lu_seq_range::lsr_index, lustre_msg_get_flags(), MSG_REPLAY, obd_device::obd_lu_dev, req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_SEQ_OPC, RMF_SEQ_RANGE, seq_server_handle(), tgt_ses_req(), tgt_session_info::tsi_env, tgt_session_info::tsi_exp, and tgt_session_info::tsi_pill.
int seq_server_alloc_spec (struct lu_server_seq * seq, struct lu_seq_range * spec, const struct lu_env * env)
Definition at line 153 of file fid_handler.c.
References DRANGE, ENTRY, LCONSOLE_INFO, lu_seq_range::lsr_end, lu_seq_range::lsr_flags, lu_seq_range::lsr_start, lu_server_seq::lss_mutex, lu_server_seq::lss_name, lu_server_seq::lss_space, LU_SEQ_RANGE_MDT, LU_SEQ_RANGE_OST, PRANGE, RETURN, and seq_store_update().
static int seq_server_handle (struct lu_site * site, const struct lu_env * env, __u32 opc, struct lu_seq_range * out) [static]
Definition at line 365 of file fid_handler.c.
References CERROR, ENTRY, lu_site2seq(), RETURN, SEQ_ALLOC_META, SEQ_ALLOC_SUPER, seq_server_alloc_meta(), seq_server_alloc_super(), seq_server_site::ss_control_seq, and seq_server_site::ss_server_seq.
Referenced by seq_handler().
static void seq_server_proc_fini (struct lu_server_seq * seq) [static]
Definition at line 488 of file fid_handler.c.
References ENTRY, EXIT, lprocfs_remove(), and lu_server_seq::lss_proc_dir.
Referenced by seq_server_fini(), and seq_server_proc_init().
static int seq_server_proc_init (struct lu_server_seq * seq) [static]
Definition at line 447 of file fid_handler.c.
References CERROR, ENTRY, GOTO, lprocfs_add_vars(), lprocfs_register(), lu_server_seq::lss_name, lu_server_seq::lss_proc_dir, lu_server_seq::lss_type, LUSTRE_SEQ_CONTROLLER, RETURN, seq_fld_proc_seq_fops, seq_server_proc_fini(), and seq_type_proc_dir.
Referenced by seq_server_init().
Variable Documentation
struct file_operations seq_fld_proc_seq_fops
Referenced by seq_server_proc_init().
struct tgt_handler seq_handlers[]
Initial value:
 {
TGT_SEQ_HDL(HABEO_REFERO,       SEQ_QUERY,      seq_handler),
}
Definition at line 434 of file fid_handler.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.