Lustre: lustre/fid/fid_internal.h File Reference
lustre/fid/fid_internal.h File Reference
#include <lustre/lustre_idl.h>
#include <libcfs/libcfs.h>
Functions
int seq_client_alloc_super (struct lu_client_seq *seq, const struct lu_env *env)
Variables
struct proc_dir_entry * seq_type_proc_dir
Function Documentation
int seq_client_alloc_super (struct lu_client_seq * seq, const struct lu_env * env)
Definition at line 148 of file fid_request.c.
References ENTRY, LASSERT, lu_client_seq::lcs_exp, lu_client_seq::lcs_mutex, lu_client_seq::lcs_space, lu_client_seq::lcs_srv, RETURN, SEQ_ALLOC_SUPER, seq_client_rpc(), and seq_server_alloc_super().
Referenced by seq_server_check_and_alloc_super().
Variable Documentation
struct proc_dir_entry* seq_type_proc_dir
Definition at line 569 of file fid_request.c.
Referenced by fid_exit(), fid_init(), seq_client_proc_init(), and seq_server_proc_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.