Lustre: lustre/fid/fid_request.c File Reference
lustre/fid/fid_request.c File Reference
#include <linux/module.h>
#include <libcfs/libcfs.h>
#include <obd.h>
#include <obd_class.h>
#include <obd_support.h>
#include <lustre_fid.h>
#include <lustre_mdc.h>
#include "fid_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_FID
Functions
static int seq_client_rpc (struct lu_client_seq *seq, struct lu_seq_range *output, __u32 opc, const char *opcname)
int seq_client_alloc_super (struct lu_client_seq *seq, const struct lu_env *env)
static int seq_client_alloc_meta (const struct lu_env *env, struct lu_client_seq *seq)
static int seq_client_alloc_seq (const struct lu_env *env, struct lu_client_seq *seq, u64 *seqnr)
static int seq_fid_alloc_prep (struct lu_client_seq *seq, wait_queue_t *link)
static void seq_fid_alloc_fini (struct lu_client_seq *seq)
int seq_client_get_seq (const struct lu_env *env, struct lu_client_seq *seq, u64 *seqnr)
Allocate the whole seq to the caller.
int seq_client_alloc_fid (const struct lu_env *env, struct lu_client_seq *seq, struct lu_fid *fid)
void seq_client_flush (struct lu_client_seq *seq)
static void seq_client_proc_fini (struct lu_client_seq *seq)
static int seq_client_proc_init (struct lu_client_seq *seq)
int seq_client_init (struct lu_client_seq *seq, struct obd_export *exp, enum lu_cli_type type, const char *prefix, struct lu_server_seq *srv)
void seq_client_fini (struct lu_client_seq *seq)
int client_fid_init (struct obd_device *obd, struct obd_export *exp, enum lu_cli_type type)
int client_fid_fini (struct obd_device *obd)
static int __init fid_init (void)
static void __exit fid_exit (void)
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre File IDentifier")
MODULE_VERSION (LUSTRE_VERSION_STRING)
MODULE_LICENSE ("GPL")
module_init (fid_init)
module_exit (fid_exit)
Variables
struct proc_dir_entry * seq_type_proc_dir
Define Documentation
#define DEBUG_SUBSYSTEM S_FID
Definition at line 43 of file fid_request.c.
Function Documentation
static void __exit fid_exit (void) [static]
Definition at line 586 of file fid_request.c.
References fid_server_mod_exit(), lprocfs_remove(), and seq_type_proc_dir.
static int __init fid_init (void) [static]
Definition at line 571 of file fid_request.c.
References fid_server_mod_init(), lprocfs_register(), LUSTRE_SEQ_NAME, proc_lustre_root, and seq_type_proc_dir.
Referenced by obd_fid_init().
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre File IDentifier")
module_exit (fid_exit)
module_init (fid_init)
MODULE_LICENSE ("GPL")
MODULE_VERSION (LUSTRE_VERSION_STRING)
static int seq_client_alloc_meta (const struct lu_env * env, struct lu_client_seq * seq) [static]
Definition at line 180 of file fid_request.c.
References ENTRY, LASSERT, lu_client_seq::lcs_space, lu_client_seq::lcs_srv, RETURN, SEQ_ALLOC_META, seq_client_rpc(), and seq_server_alloc_meta().
Referenced by seq_client_alloc_seq().
static int seq_client_alloc_seq (const struct lu_env * env, struct lu_client_seq * seq, u64 * seqnr) [static]
Definition at line 208 of file fid_request.c.
References CDEBUG, CERROR, D_INFO, DRANGE, ENTRY, LASSERT, lu_client_seq::lcs_name, lu_client_seq::lcs_space, LPX64, lu_seq_range::lsr_start, lu_seq_range_is_exhausted(), lu_seq_range_is_sane(), PRANGE, RETURN, and seq_client_alloc_meta().
Referenced by seq_client_alloc_fid(), and seq_client_get_seq().
int seq_client_alloc_super (struct lu_client_seq * seq, const struct lu_env * env)
Definition at line 148 of file fid_request.c.
References ENTRY, LASSERT, lu_client_seq::lcs_exp, lu_client_seq::lcs_mutex, lu_client_seq::lcs_space, lu_client_seq::lcs_srv, RETURN, SEQ_ALLOC_SUPER, seq_client_rpc(), and seq_server_alloc_super().
Referenced by seq_server_check_and_alloc_super().
static void seq_client_proc_fini (struct lu_client_seq * seq) [static]
Definition at line 422 of file fid_request.c.
References ENTRY, EXIT, lu_client_seq::lcs_proc_dir, and lprocfs_remove().
Referenced by seq_client_fini(), and seq_client_proc_init().
static int seq_client_proc_init (struct lu_client_seq * seq) [static]
Definition at line 435 of file fid_request.c.
References CERROR, ENTRY, GOTO, lu_client_seq::lcs_name, lu_client_seq::lcs_proc_dir, lprocfs_add_vars(), lprocfs_register(), RETURN, seq_client_proc_fini(), and seq_type_proc_dir.
Referenced by seq_client_init().
static int seq_client_rpc (struct lu_client_seq * seq, struct lu_seq_range * output, __u32 opc, const char * opcname) [static]
Definition at line 55 of file fid_request.c.
References CDEBUG_LIMIT, CERROR, class_exp2cliimp(), D_CONSOLE, D_INFO, debug_mask, DRANGE, ENTRY, EXIT, fld_range_set_mdt(), fld_range_set_ost(), GOTO, LASSERT, lu_client_seq::lcs_exp, lu_client_seq::lcs_name, lu_client_seq::lcs_space, lu_client_seq::lcs_type, lu_seq_range::lsr_index, lu_seq_range_init(), lu_seq_range_is_exhausted(), lu_seq_range_is_sane(), LUSTRE_MDS_VERSION, LUSTRE_SEQ_DATA, LUSTRE_SEQ_METADATA, MDC_REPLY_PORTAL, OSC_REPLY_PORTAL, PRANGE, ptlrpc_at_set_req_timeout(), ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc_pack(), ptlrpc_request_set_replen(), req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_SEQ_OPC, RMF_SEQ_RANGE, ptlrpc_request::rq_allow_replay, ptlrpc_request::rq_no_delay, ptlrpc_request::rq_no_resend, ptlrpc_request::rq_pill, RQF_SEQ_QUERY, SEQ_ALLOC_SUPER, SEQ_CONTROLLER_PORTAL, SEQ_DATA_PORTAL, SEQ_METADATA_PORTAL, and SEQ_QUERY.
Referenced by seq_client_alloc_meta(), and seq_client_alloc_super().
static void seq_fid_alloc_fini (struct lu_client_seq * seq) [static]
Definition at line 260 of file fid_request.c.
References LASSERT, lu_client_seq::lcs_mutex, lu_client_seq::lcs_update, and lu_client_seq::lcs_waitq.
Referenced by seq_client_alloc_fid(), and seq_client_get_seq().
static int seq_fid_alloc_prep (struct lu_client_seq * seq, wait_queue_t * link) [static]
Definition at line 240 of file fid_request.c.
References lu_client_seq::lcs_mutex, lu_client_seq::lcs_update, and lu_client_seq::lcs_waitq.
Referenced by seq_client_alloc_fid(), and seq_client_get_seq().
Variable Documentation
struct proc_dir_entry* seq_type_proc_dir
Definition at line 569 of file fid_request.c.
Referenced by fid_exit(), fid_init(), seq_client_proc_init(), and seq_server_proc_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.