Lustre: lustre/fid/fid_store.c File Reference
lustre/fid/fid_store.c File Reference
#include <libcfs/libcfs.h>
#include <dt_object.h>
#include <obd_support.h>
#include <lustre_fid.h>
#include <lustre_fld.h>
#include "fid_internal.h"
Data Structures
struct seq_update_callback
Defines
#define DEBUG_SUBSYSTEM S_FID
Functions
static struct lu_buf * seq_store_buf (struct seq_thread_info *info)
void seq_update_cb (struct lu_env *env, struct thandle *th, struct dt_txn_commit_cb *cb, int err)
int seq_update_cb_add (struct thandle *th, struct lu_server_seq *seq)
int seq_store_update (const struct lu_env *env, struct lu_server_seq *seq, struct lu_seq_range *out, int sync)
int seq_store_read (struct lu_server_seq *seq, const struct lu_env *env)
int seq_store_init (struct lu_server_seq *seq, const struct lu_env *env, struct dt_device *dt)
void seq_store_fini (struct lu_server_seq *seq, const struct lu_env *env)
Define Documentation
#define DEBUG_SUBSYSTEM S_FID
Definition at line 43 of file fid_store.c.
Function Documentation
static struct lu_buf* seq_store_buf (struct seq_thread_info * info) [static, read]
Definition at line 52 of file fid_store.c.
References buf, lu_buf::lb_buf, and lu_buf::lb_len.
Referenced by seq_store_read(), and seq_store_update().
void seq_store_fini (struct lu_server_seq * seq, const struct lu_env * env)
Definition at line 238 of file fid_store.c.
References dt_object::do_lu, ENTRY, EXIT, lu_server_seq::lss_obj, and lu_object_put().
Referenced by seq_server_fini().
int seq_store_init (struct lu_server_seq * seq, const struct lu_env * env, struct dt_device * dt)
Definition at line 200 of file fid_store.c.
References CERROR, DFT_REGULAR, dt_object_format::dof_type, dt_find_or_create(), ENTRY, FID_SEQ_CTL_OID, FID_SEQ_SRV_OID, lu_attr::la_mode, LA_MODE, lu_attr::la_valid, lu_server_seq::lss_name, lu_server_seq::lss_obj, lu_server_seq::lss_type, lu_local_obj_fid(), LUSTRE_SEQ_CTL_NAME, LUSTRE_SEQ_SERVER, LUSTRE_SEQ_SRV_NAME, name, and RETURN.
Referenced by seq_server_init().
int seq_store_read (struct lu_server_seq * seq, const struct lu_env * env)
Definition at line 171 of file fid_store.c.
References CDEBUG, CERROR, D_INFO, DRANGE, dt_read(), ENTRY, LASSERT, lu_env::le_ctx, lu_server_seq::lss_name, lu_server_seq::lss_obj, lu_server_seq::lss_space, lu_context_key_get(), PRANGE, range_le_to_cpu(), RETURN, and seq_store_buf().
Referenced by seq_server_init().
int seq_store_update (const struct lu_env * env, struct lu_server_seq * seq, struct lu_seq_range * out, int sync)
Definition at line 105 of file fid_store.c.
References CERROR, dt_object::do_lu, dt_declare_record_write(), dt_record_write(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), fld_declare_server_create(), fld_server_create(), GOTO, LASSERT, lu_env::le_ctx, lu_object::lo_dev, lu_server_seq::lss_name, lu_server_seq::lss_obj, lu_server_seq::lss_site, lu_server_seq::lss_space, lu2dt_dev(), lu_context_key_get(), range_cpu_to_le(), RETURN, seq_store_buf(), seq_update_cb_add(), seq_server_site::ss_server_fld, and thandle::th_sync.
Referenced by __seq_server_alloc_super(), __seq_set_init(), range_alloc_set(), seq_server_alloc_spec(), and seq_server_init().
void seq_update_cb (struct lu_env * env, struct thandle * th, struct dt_txn_commit_cb * cb, int err)
Definition at line 67 of file fid_store.c.
References LASSERT, lu_server_seq::lss_need_sync, OBD_FREE_PTR, seq_update_callback::suc_cb, and seq_update_callback::suc_seq.
Referenced by seq_update_cb_add().
int seq_update_cb_add (struct thandle * th, struct lu_server_seq * seq)
Definition at line 80 of file fid_store.c.
References dt_txn_commit_cb::dcb_func, dt_txn_commit_cb::dcb_linkage, dt_txn_commit_cb::dcb_name, dt_trans_cb_add(), INIT_LIST_HEAD, lu_server_seq::lss_need_sync, OBD_ALLOC_PTR, OBD_FREE_PTR, seq_update_cb(), strlcpy(), seq_update_callback::suc_cb, and seq_update_callback::suc_seq.
Referenced by seq_store_update().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.