Lustre: lustre/llite/file.c File Reference
lustre/llite/file.c File Reference
#include <lustre_dlm.h>
#include <linux/pagemap.h>
#include <linux/file.h>
#include <linux/sched.h>
#include <linux/user_namespace.h>
#include <lustre/ll_fiemap.h>
#include <lustre_ioctl.h>
#include <lustre_swab.h>
#include "cl_object.h"
#include "llite_internal.h"
#include "vvp_internal.h"
Data Structures
struct ll_swap_stack
struct llioc_ctl_data
struct llioc_data
Defines
#define DEBUG_SUBSYSTEM S_LLITE
Functions
static int ll_put_grouplock (struct inode *inode, struct file *file, unsigned long arg)
static int ll_lease_close (struct obd_client_handle *och, struct inode *inode, bool *lease_broken)
Release lease and close the file.
static enum llioc_iter ll_iocontrol_call (struct inode *inode, struct file *file, unsigned int cmd, unsigned long arg, int *rcp)
static struct ll_file_data * ll_file_data_get (void)
static void ll_file_data_put (struct ll_file_data *fd)
static void ll_prepare_close (struct inode *inode, struct md_op_data *op_data, struct obd_client_handle *och)
Packs all the attributes into for the CLOSE rpc.
static int ll_close_inode_openhandle (struct inode *inode, struct obd_client_handle *och, enum mds_op_bias bias, void *data)
Perform a close, possibly with a bias.
int ll_md_real_close (struct inode *inode, fmode_t fmode)
static int ll_md_close (struct inode *inode, struct file *file)
int ll_file_release (struct inode *inode, struct file *file)
static int ll_intent_file_open (struct file *file, void *lmm, int lmmsize, struct lookup_intent *itp)
static int ll_och_fill (struct obd_export *md_exp, struct lookup_intent *it, struct obd_client_handle *och)
static int ll_local_open (struct file *file, struct lookup_intent *it, struct ll_file_data *fd, struct obd_client_handle *och)
int ll_file_open (struct inode *inode, struct file *file)
static int ll_md_blocking_lease_ast (struct ldlm_lock *lock, struct ldlm_lock_desc *desc, void *data, int flag)
static struct obd_client_handle * ll_lease_open (struct inode *inode, struct file *file, fmode_t fmode, __u64 open_flags)
Acquire a lease and open the file.
static int ll_check_swap_layouts_validity (struct inode *inode1, struct inode *inode2)
Check whether a layout swap can be done between two inodes.
static int ll_swap_layouts_close (struct obd_client_handle *och, struct inode *inode, struct inode *inode2)
int ll_merge_attr (const struct lu_env *env, struct inode *inode)
static bool file_is_noatime (const struct file *file)
static void ll_io_init (struct cl_io *io, const struct file *file, int write)
static ssize_t ll_file_io_generic (const struct lu_env *env, struct vvp_io_args *args, struct file *file, enum cl_io_type iot, loff_t *ppos, size_t count)
static ssize_t ll_file_read_iter (struct kiocb *iocb, struct iov_iter *to)
static ssize_t ll_file_write_iter (struct kiocb *iocb, struct iov_iter *from)
static int ll_file_get_iov_count (const struct iovec *iov, unsigned long *nr_segs, size_t *count)
static ssize_t ll_file_aio_read (struct kiocb *iocb, const struct iovec *iov, unsigned long nr_segs, loff_t pos)
static ssize_t ll_file_read (struct file *file, char __user *buf, size_t count, loff_t *ppos)
static ssize_t ll_file_aio_write (struct kiocb *iocb, const struct iovec *iov, unsigned long nr_segs, loff_t pos)
static ssize_t ll_file_write (struct file *file, const char __user *buf, size_t count, loff_t *ppos)
static ssize_t ll_file_splice_read (struct file *in_file, loff_t *ppos, struct pipe_inode_info *pipe, size_t count, unsigned int flags)
int ll_lov_setstripe_ea_info (struct inode *inode, struct file *file, __u64 flags, struct lov_user_md *lum, int lum_size)
int ll_lov_getstripe_ea_info (struct inode *inode, const char *filename, struct lov_mds_md **lmmp, int *lmm_size, struct ptlrpc_request **request)
static int ll_lov_setea (struct inode *inode, struct file *file, unsigned long arg)
static int ll_file_getstripe (struct inode *inode, struct lov_user_md __user *lum)
static int ll_lov_setstripe (struct inode *inode, struct file *file, unsigned long arg)
static int ll_get_grouplock (struct inode *inode, struct file *file, unsigned long arg)
int ll_release_openhandle (struct dentry *dentry, struct lookup_intent *it)
Close inode open handle.
static int ll_do_fiemap (struct inode *inode, struct fiemap *fiemap, size_t num_bytes)
Get size for inode for which FIEMAP mapping is requested.
int ll_fid2path (struct inode *inode, void __user *arg)
int ll_data_version (struct inode *inode, __u64 *data_version, int flags)
int ll_hsm_release (struct inode *inode)
static int ll_swap_layouts (struct file *file1, struct file *file2, struct lustre_swap_layouts *lsl)
int ll_hsm_state_set (struct inode *inode, struct hsm_state_set *hss)
static int ll_hsm_import (struct inode *inode, struct file *file, struct hsm_user_import *hui)
static long ll_lease_type_from_fmode (fmode_t fmode)
static int ll_file_futimes_3 (struct file *file, const struct ll_futimes_3 *lfu)
static int ll_ladvise (struct inode *inode, struct file *file, __u64 flags, struct lu_ladvise *ladvise)
static long ll_file_ioctl (struct file *file, unsigned int cmd, unsigned long arg)
static loff_t llseek_execute (struct file *file, loff_t offset, loff_t maxsize)
static loff_t generic_file_llseek_size (struct file *file, loff_t offset, int origin, loff_t maxsize, loff_t eof)
static loff_t ll_file_seek (struct file *file, loff_t offset, int origin)
static int ll_flush (struct file *file, fl_owner_t id)
int cl_sync_file_range (struct inode *inode, loff_t start, loff_t end, enum cl_fsync_mode mode, int ignore_layout)
Called to make sure a portion of file has been written out.
int ll_fsync (struct file *file, struct dentry *dentry, int datasync)
static int ll_file_flock (struct file *file, int cmd, struct file_lock *file_lock)
int ll_get_fid_by_name (struct inode *parent, const char *name, int namelen, struct lu_fid *fid, struct inode **inode)
int ll_migrate (struct inode *parent, struct file *file, int mdtidx, const char *name, int namelen)
static int ll_file_noflock (struct file *file, int cmd, struct file_lock *file_lock)
int ll_have_md_lock (struct inode *inode, __u64 *bits, enum ldlm_mode l_req_mode)
test if some locks matching bits and l_req_mode are acquired
bits can be in different locks
if found clear the common lock bits in *bits
the bits not found, are kept in *bits
enum ldlm_mode ll_take_md_lock (struct inode *inode, __u64 bits, struct lustre_handle *lockh, __u64 flags, enum ldlm_mode mode)
static int ll_inode_revalidate_fini (struct inode *inode, int rc)
static int __ll_inode_revalidate (struct dentry *dentry, __u64 ibits)
static int ll_merge_md_attr (struct inode *inode)
static int ll_inode_revalidate (struct dentry *dentry, __u64 ibits)
int ll_getattr (struct vfsmount *mnt, struct dentry *de, struct kstat *stat)
static int ll_fiemap (struct inode *inode, struct fiemap_extent_info *fieinfo, __u64 start, __u64 len)
struct posix_acl * ll_get_acl (struct inode *inode, int type)
static int ll_check_acl (struct inode *inode, int mask)
int ll_inode_permission (struct inode *inode, int mask, struct nameidata *nd)
void * ll_iocontrol_register (llioc_callback_t cb, int count, unsigned int *cmd)
void ll_iocontrol_unregister (void *magic)
int ll_layout_conf (struct inode *inode, const struct cl_object_conf *conf)
static int ll_layout_fetch (struct inode *inode, struct ldlm_lock *lock)
static int ll_layout_lock_set (struct lustre_handle *lockh, enum ldlm_mode mode, struct inode *inode)
Apply the layout to the inode.
static int ll_layout_refresh_locked (struct inode *inode)
int ll_layout_refresh (struct inode *inode, __u32 *gen)
This function checks if there exists a LAYOUT lock on the client side, or enqueues it if it doesn't have one in cache.
int ll_layout_restore (struct inode *inode, loff_t offset, __u64 length)
This function send a restore request to the MDT.
Variables
struct file_operations ll_file_operations
struct file_operations ll_file_operations_flock
struct file_operations ll_file_operations_noflock
struct inode_operations ll_file_inode_operations
static struct llioc_ctl_data llioc
Define Documentation
#define DEBUG_SUBSYSTEM S_LLITE
Definition at line 43 of file file.c.
Function Documentation
static int __ll_inode_revalidate (struct dentry * dentry, __u64 ibits) [static]
Definition at line 3324 of file file.c.
References CDEBUG, d_lustre_invalidate(), D_VFSTRACE, DFID, ENTRY, exp_connect_flags(), GOTO, IT_GETATTR, IT_LOOKUP, lookup_intent::it_op, LASSERT, LCK_MINMODE, ll_finish_md_op_data(), ll_get_default_mdsize(), ll_have_md_lock(), ll_i2mdexp(), ll_i2sbi(), ll_inode2fid(), ll_inode_revalidate_fini(), ll_intent_release(), ll_lock_dcache(), ll_lookup_finish_locks(), ll_md_blocking_ast(), ll_sb_info::ll_md_exp, ll_prep_inode(), ll_prep_md_op_data(), ll_revalidate_it_finish(), ll_unlock_dcache(), LUSTRE_OPC_ANY, md_getattr(), md_intent_lock(), MDS_INODELOCK_LOOKUP, OBD_CONNECT_ATTRFID, OBD_MD_FLEASIZE, OBD_MD_FLGETATTR, OBD_MD_FLMODEASIZE, md_op_data::op_data, md_op_data::op_valid, PFID, ptlrpc_req_finished(), and RETURN.
Referenced by ll_inode_permission(), and ll_inode_revalidate().
int cl_sync_file_range (struct inode * inode, loff_t start, loff_t end, enum cl_fsync_mode mode, int ignore_layout)
Called to make sure a portion of file has been written out.
if is not CL_FSYNC_LOCAL, it will send OST_SYNC RPCs to OST.
Return how many pages have been written.
Definition at line 2787 of file file.c.
References cl_io::ci_fsync, cl_io::ci_ignore_layout, cl_io::ci_obj, cl_io::ci_result, CIT_FSYNC, cl_env_nested_get(), cl_env_nested_put(), CL_FSYNC_ALL, CL_FSYNC_DISCARD, CL_FSYNC_LOCAL, CL_FSYNC_NONE, cl_io_fini(), cl_io_init(), cl_io_loop(), ENTRY, ll_i2info(), ll_inode2fid(), ll_inode_info::lli_clob, RETURN, cl_io::u, and vvp_env_thread_io().
Referenced by ll_delete_inode(), ll_fsync(), ll_writepage(), ll_writepages(), and vvp_prune().
static bool file_is_noatime (const struct file * file) [static]
Definition at line 985 of file file.c.
Referenced by ll_io_init().
static loff_t generic_file_llseek_size (struct file * file, loff_t offset, int origin, loff_t maxsize, loff_t eof) [static]
Definition at line 2680 of file file.c.
References llseek_execute(), SEEK_DATA, and SEEK_HOLE.
static int ll_check_acl (struct inode * inode, int mask) [static]
Definition at line 3568 of file file.c.
References ENTRY, ll_get_acl(), and RETURN.
Referenced by ll_inode_permission().
static int ll_check_swap_layouts_validity (struct inode * inode1, struct inode * inode2) [static]
Check whether a layout swap can be done between two inodes.
Parameters:
[in] inode1 First inode to check
[in] inode2 Second inode to check
Return values:
0 on success, layout swap can be performed between both inodes
negative error code if requirements are not met
Definition at line 844 of file file.c.
Referenced by ll_swap_layouts(), and ll_swap_layouts_close().
static int ll_close_inode_openhandle (struct inode * inode, struct obd_client_handle * och, enum mds_op_bias bias, void * data) [static]
Perform a close, possibly with a bias.
The meaning of "data" depends on the value of "bias".
If bias is MDS_HSM_RELEASE then data is a pointer to the data version. If bias is MDS_CLOSE_LAYOUT_SWAP then data is a pointer to the inode to swap layouts with.
Definition at line 130 of file file.c.
References __u64, ATTR_BLOCKS, CERROR, class_exp2obd(), lustre_handle::cookie, DEAD_HANDLE_MAGIC, DFID, ENTRY, EXIT, obd_export::exp_obd, GOTO, LASSERT, ll_finish_md_op_data(), ll_get_fsname(), ll_i2info(), ll_i2mdexp(), ll_inode2fid(), ll_prepare_close(), ll_inode_info::lli_fid, mdt_body::mbo_valid, md_clear_open_replay_data(), md_close(), MDS_CLOSE_LAYOUT_SWAP, MDS_HSM_RELEASE, OBD_ALLOC_PTR, OBD_FREE_PTR, OBD_MD_CLOSE_INTENT_EXECED, obd_device::obd_name, obd_client_handle::och_fh, obd_client_handle::och_lease_handle, obd_client_handle::och_mod, md_op_data::op_attr, md_op_data::op_bias, md_op_data::op_data, md_op_data::op_data_version, md_op_data::op_fid2, md_op_data::op_lease_handle, PFID, ptlrpc_req_finished(), req_capsule_server_get(), RMF_MDT_BODY, and ptlrpc_request::rq_pill.
Referenced by ll_hsm_release(), ll_lease_close(), ll_lease_open(), ll_md_close(), ll_md_real_close(), ll_release_openhandle(), and ll_swap_layouts_close().
int ll_data_version (struct inode * inode, __u64 * data_version, int flags)
Definition at line 1869 of file file.c.
References cl_io::ci_data_version, cl_io::ci_need_restart, cl_io::ci_obj, cl_io::ci_result, CIT_DATA_VERSION, cl_env_get(), cl_env_put(), cl_io_fini(), cl_io_init(), cl_io_loop(), ENTRY, ll_i2info(), ll_inode_info::lli_clob, RETURN, cl_io::u, unlikely, and vvp_env_thread_io().
Referenced by ll_file_ioctl(), ll_hsm_release(), ll_ioc_copy_end(), ll_ioc_copy_start(), ll_migrate(), and ll_swap_layouts().
static int ll_do_fiemap (struct inode * inode, struct fiemap * fiemap, size_t num_bytes) [static]
Get size for inode for which FIEMAP mapping is requested.
Make the FIEMAP get_info call and returns the result.
Parameters:
fiemap kernel buffer to hold extens
num_bytes kernel buffer size
Definition at line 1760 of file file.c.
References cl_env_get(), cl_env_put(), cl_object_fiemap(), ENTRY, GOTO, KEY_FIEMAP, ll_fiemap_info_key::lfik_fiemap, ll_fiemap_info_key::lfik_name, ll_fiemap_info_key::lfik_oa, ll_glimpse_size(), ll_i2info(), LUSTRE_FIEMAP_FLAGS_COMPAT, obdo::o_size, obdo::o_valid, OBD_MD_FLGROUP, OBD_MD_FLID, OBD_MD_FLSIZE, obdo_from_inode(), obdo_set_parent_fid(), and RETURN.
Referenced by ll_fiemap().
int ll_fid2path (struct inode * inode, void __user * arg)
Definition at line 1811 of file file.c.
References CFS_CAP_DAC_READ_SEARCH, cfs_capable(), ENTRY, getinfo_fid2path::gf_pathlen, getinfo_fid2path::gf_root_fid, getinfo_fid2path::gf_u, GOTO, ll_i2mdexp(), ll_i2sbi(), ll_inode2fid(), LL_SBI_USER_FID2PATH, OBD_ALLOC, OBD_FREE, OBD_IOC_FID2PATH, obd_iocontrol(), and RETURN.
Referenced by ll_dir_ioctl(), and ll_file_ioctl().
static int ll_fiemap (struct inode * inode, struct fiemap_extent_info * fieinfo, __u64 start, __u64 len) [static]
Definition at line 3511 of file file.c.
References GOTO, ll_do_fiemap(), OBD_ALLOC_LARGE, OBD_FREE_LARGE, and RETURN.
static ssize_t ll_file_aio_read (struct kiocb * iocb, const struct iovec * iov, unsigned long nr_segs, loff_t pos) [static]
Definition at line 1245 of file file.c.
References cl_env_get(), cl_env_put(), ENTRY, ll_env_info(), ll_file_get_iov_count(), ll_file_read_iter(), ll_thread_info::lti_local_iov, OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, READ, and RETURN.
Referenced by ll_file_read().
static ssize_t ll_file_aio_write (struct kiocb * iocb, const struct iovec * iov, unsigned long nr_segs, loff_t pos) [static]
Definition at line 1334 of file file.c.
References cl_env_get(), cl_env_put(), ENTRY, ll_env_info(), ll_file_get_iov_count(), ll_file_write_iter(), ll_thread_info::lti_local_iov, OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, RETURN, and WRITE.
Referenced by ll_file_write().
static struct ll_file_data* ll_file_data_get (void) [static, read]
Definition at line 71 of file file.c.
References ll_file_data::fd_write_failed, ll_file_data_slab, and OBD_SLAB_ALLOC_PTR_GFP.
Referenced by ll_file_open().
static void ll_file_data_put (struct ll_file_data * fd) [static]
Definition at line 84 of file file.c.
References ll_file_data_slab, and OBD_SLAB_FREE_PTR.
Referenced by ll_file_open(), ll_file_release(), and ll_md_close().
static int ll_file_flock (struct file * file, int cmd, struct file_lock * file_lock) [static]
Definition at line 2907 of file file.c.
References __u64, CDEBUG, CERROR, D_DLMTRACE, D_INFO, D_VFSTRACE, DFID, ldlm_enqueue_info::ei_mode, ldlm_enqueue_info::ei_type, ldlm_flock::end, ENTRY, ldlm_policy_data::l_flock, LASSERT, LCK_NL, LCK_PR, LCK_PW, LDLM_FL_BLOCK_NOWAIT, LDLM_FL_TEST_LOCK, LDLM_FLOCK, ldlm_flock_completion_ast(), ll_finish_md_op_data(), ll_i2sbi(), ll_inode2fid(), ll_sb_info::ll_md_exp, ll_prep_md_op_data(), ll_stats_ops_tally(), LPROC_LL_FLOCK, LPU64, LPX64, LUSTRE_OPC_ANY, md_enqueue(), md_op_data::op_data, ldlm_flock::owner, PFID, ldlm_flock::pid, RETURN, and ldlm_flock::start.
static int ll_file_futimes_3 (struct file * file, const struct ll_futimes_3 * lfu) [static]
Definition at line 2174 of file file.c.
References ATTR_CTIME_SET, ENTRY, ll_futimes_3::lfu_atime_nsec, ll_futimes_3::lfu_atime_sec, ll_futimes_3::lfu_ctime_nsec, ll_futimes_3::lfu_ctime_sec, ll_futimes_3::lfu_mtime_nsec, ll_futimes_3::lfu_mtime_sec, ll_setattr_raw(), and RETURN.
Referenced by ll_file_ioctl().
static int ll_file_get_iov_count (const struct iovec * iov, unsigned long * nr_segs, size_t * count) [static]
Definition at line 1217 of file file.c.
References unlikely.
Referenced by ll_file_aio_read(), and ll_file_aio_write().
static int ll_file_getstripe (struct inode * inode, struct lov_user_md __user * lum) [static]
Definition at line 1583 of file file.c.
References cl_env_get(), cl_env_put(), cl_object_getstripe(), ENTRY, ll_i2info(), and RETURN.
Referenced by ll_file_ioctl(), and ll_lov_setstripe().
static ssize_t ll_file_io_generic (const struct lu_env * env, struct vvp_io_args * args, struct file * file, enum cl_io_type iot, loff_t * ppos, size_t count) [static]
Definition at line 1036 of file file.c.
References CDEBUG, CERROR, cl_io::ci_need_restart, cl_io::ci_nob, cl_io::ci_result, cl_io::ci_wr, CIT_READ, CIT_WRITE, cl_io_fini(), cl_io_loop(), cl_io_rw_init(), D_VFSTRACE, ENTRY, ll_file_data::fd_flags, ll_file_data::fd_write_failed, GOTO, IO_NORMAL, IO_SPLICE, LBUG, ll_cl_add(), ll_cl_remove(), LL_FILE_GROUP_LOCKED, ll_i2info(), ll_i2sbi(), ll_io_init(), ll_stats_ops_tally(), ll_inode_info::lli_write_tree, LPROC_LL_READ_BYTES, LPROC_LL_WRITE_BYTES, LPU64, LUSTRE_EOF, LUSTRE_FPRIVATE, vvp_io_args::normal, range_lock(), range_lock_init(), range_unlock(), RL_FMT, RL_PARA, vvp_io_args::splice, vvp_io::splice, cl_io::u, vvp_io::u, vvp_io_args::u, vvp_io_args::via_io_subtype, vvp_io::vui_fd, vvp_io::vui_io_subtype, vvp_io::vui_iocb, vvp_io::vui_iter, vvp_io::vui_tot_nrsegs, vvp_env_io(), and vvp_env_thread_io().
Referenced by ll_file_read_iter(), ll_file_splice_read(), and ll_file_write_iter().
static long ll_file_ioctl (struct file * file, unsigned int cmd, unsigned long arg) [static]
Definition at line 2260 of file file.c.
References __user, CDEBUG, CERROR, D_INODE, D_VFSTRACE, DFID, ENTRY, ll_file_data::fd_flags, ll_file_data::fd_lease_och, FMODE_READ, FMODE_WRITE, FSFILT_IOC_GETFLAGS, FSFILT_IOC_GETVERSION, FSFILT_IOC_GETVERSION_OLD, FSFILT_IOC_SETFLAGS, GOTO, ioc_data_version::idv_flags, ioc_data_version::idv_version, IOC_OBD_STATFS, LADVISE_MAGIC, ladvise_hdr::lah_advise, ladvise_hdr::lah_count, LAH_COUNT_MAX, ladvise_hdr::lah_flags, ladvise_hdr::lah_magic, ldlm_handle2lock(), ldlm_is_cancel, LDLM_LOCK_PUT, ll_data_version(), LL_DV_RD_FLUSH, LL_DV_WR_FLUSH, ll_fid2path(), ll_file_futimes_3(), ll_file_getstripe(), LL_FILE_IGNORE_LOCK, ll_finish_md_op_data(), ll_flush_ctx(), ll_get_grouplock(), ll_get_mdt_idx(), ll_get_obd_name(), ll_getparent(), ll_hsm_import(), ll_hsm_state_set(), ll_i2dtexp(), ll_i2info(), ll_i2mdexp(), ll_i2sbi(), ll_inode2fid(), LL_IOC_CLRFLAGS, LL_IOC_DATA_VERSION, LL_IOC_FLUSHCTX, LL_IOC_FUTIMES_3, LL_IOC_GET_LEASE, LL_IOC_GET_MDTIDX, LL_IOC_GETFLAGS, LL_IOC_GETPARENT, LL_IOC_GROUP_LOCK, LL_IOC_GROUP_UNLOCK, LL_IOC_HSM_ACTION, LL_IOC_HSM_IMPORT, LL_IOC_HSM_STATE_GET, LL_IOC_HSM_STATE_SET, LL_IOC_LADVISE, LL_IOC_LOV_GETSTRIPE, LL_IOC_LOV_SETEA, LL_IOC_LOV_SETSTRIPE, LL_IOC_LOV_SWAP_LAYOUTS, LL_IOC_PATH2FID, LL_IOC_SET_LEASE, LL_IOC_SETFLAGS, ll_iocontrol(), ll_iocontrol_call(), ll_ladvise(), ll_lease_close(), ll_lease_open(), LL_LEASE_RDLCK, ll_lease_type_from_fmode(), LL_LEASE_UNLCK, LL_LEASE_WRLCK, ll_lov_setea(), ll_lov_setstripe(), ll_obd_statfs(), ll_prep_md_op_data(), ll_put_grouplock(), ll_stats_ops_tally(), ll_swap_layouts(), ll_swap_layouts_close(), ll_inode_info::lli_och_mutex, LLIOC_STOP, lock_res_and_lock(), lov_user_md, LPROC_LL_IOCTL, LUSTRE_FPRIVATE, LUSTRE_OPC_ANY, OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, OBD_IOC_FID2PATH, OBD_IOC_GETDTNAME, OBD_IOC_GETMDNAME, obd_iocontrol(), obd_client_handle::och_flags, obd_client_handle::och_lease_handle, offsetof, md_op_data::op_data, PFID, RETURN, lustre_swap_layouts::sl_fd, lustre_swap_layouts::sl_flags, SWAP_LAYOUTS_CLOSE, and unlock_res_and_lock().
static int ll_file_noflock (struct file * file, int cmd, struct file_lock * file_lock) [static]
Definition at line 3221 of file file.c.
References ENTRY, and RETURN.
int ll_file_open (struct inode * inode, struct file * file)
Definition at line 491 of file file.c.
References __u64, CDEBUG, cl_lov_delay_create_clear(), D_VFSTRACE, DFID, DISP_ENQ_OPEN_REF, DISP_OPEN_OPEN, ENTRY, ll_file_data::fd_file, FMODE_EXEC, FMODE_READ, FMODE_WRITE, GOTO, it_clear_disposition(), IT_CREAT, it_disposition(), lookup_intent::it_disposition, lookup_intent::it_flags, lookup_intent::it_op, IT_OPEN, it_open_error(), lookup_intent::it_request, lookup_intent::it_status, LASSERT, LASSERTF, ll_authorize_statahead(), ll_deauthorize_statahead(), ll_file_data_get(), ll_file_data_put(), ll_i2info(), ll_i2sbi(), ll_inode2fid(), ll_intent_file_open(), ll_local_open(), ll_release_openhandle(), ll_stats_ops_tally(), ll_inode_info::lli_mds_exec_och, ll_inode_info::lli_mds_read_och, ll_inode_info::lli_mds_write_och, ll_inode_info::lli_och_mutex, ll_inode_info::lli_open_fd_exec_count, ll_inode_info::lli_open_fd_read_count, ll_inode_info::lli_open_fd_write_count, ll_inode_info::lli_opendir_key, LPROC_LL_OPEN, LUSTRE_FPRIVATE, MDS_OPEN_BY_FID, MDS_OPEN_LOCK, MDS_OPEN_OWNEROVERRIDE, OBD_ALLOC, OBD_FREE, PFID, ptlrpc_req_finished(), and RETURN.
Referenced by ll_dir_open().
static ssize_t ll_file_read (struct file * file, char __user * buf, size_t count, loff_t * ppos) [static]
Definition at line 1300 of file file.c.
References cl_env_get(), cl_env_put(), ENTRY, ll_env_info(), ll_file_aio_read(), ll_thread_info::lti_kiocb, and RETURN.
static ssize_t ll_file_read_iter (struct kiocb * iocb, struct iov_iter * to) [static]
Definition at line 1168 of file file.c.
References CIT_READ, cl_env_get(), cl_env_put(), IO_NORMAL, ll_env_args(), ll_file_io_generic(), vvp_io_args::normal, and vvp_io_args::u.
Referenced by ll_file_aio_read().
int ll_file_release (struct inode * inode, struct file * file)
Definition at line 314 of file file.c.
References CDEBUG, CFS_FAIL_TIMEOUT_MS, cfs_fail_val, current_pid, D_VFSTRACE, DFID, ENTRY, ll_file_data::fd_flags, LASSERT, libcfs_debug_dumplog(), ll_deauthorize_statahead(), ll_sb_info::ll_et, ll_file_data_put(), LL_FILE_RMTACL, ll_sb_info::ll_flags, ll_i2info(), ll_i2sbi(), ll_inode2fid(), ll_md_close(), ll_sb_info::ll_rct, LL_SBI_RMT_CLIENT, ll_stats_ops_tally(), ll_inode_info::lli_async_rc, ll_inode_info::lli_clob, ll_inode_info::lli_opendir_key, lov_read_and_clear_async_rc(), LPROC_LL_RELEASE, LUSTRE_FPRIVATE, OBD_FAIL_PTLRPC_DUMP_LOG, PFID, RETURN, and unlikely.
Referenced by ll_dir_release().
static loff_t ll_file_seek (struct file * file, loff_t offset, int origin) [static]
Definition at line 2730 of file file.c.
References CDEBUG, D_VFSTRACE, DFID, ENTRY, ll_file_maxbytes(), ll_generic_file_llseek_size, ll_glimpse_size(), ll_i2sbi(), ll_inode2fid(), ll_stats_ops_tally(), LPROC_LL_LLSEEK, PFID, RETURN, SEEK_DATA, and SEEK_HOLE.
static ssize_t ll_file_splice_read (struct file * in_file, loff_t * ppos, struct pipe_inode_info * pipe, size_t count, unsigned int flags) [static]
Definition at line 1422 of file file.c.
References CIT_READ, cl_env_get(), cl_env_put(), ENTRY, IO_SPLICE, ll_env_args(), ll_file_io_generic(), RETURN, vvp_io_args::splice, and vvp_io_args::u.
static ssize_t ll_file_write (struct file * file, const char __user * buf, size_t count, loff_t * ppos) [static]
Definition at line 1387 of file file.c.
References __user, cl_env_get(), cl_env_put(), ENTRY, ll_env_info(), ll_file_aio_write(), ll_thread_info::lti_kiocb, and RETURN.
static ssize_t ll_file_write_iter (struct kiocb * iocb, struct iov_iter * from) [static]
Definition at line 1192 of file file.c.
References CIT_WRITE, cl_env_get(), cl_env_put(), IO_NORMAL, ll_env_args(), ll_file_io_generic(), vvp_io_args::normal, and vvp_io_args::u.
Referenced by ll_file_aio_write().
static int ll_flush (struct file * file, fl_owner_t id) [static]
Definition at line 2755 of file file.c.
References ll_file_data::fd_write_failed, LASSERT, ll_i2info(), ll_inode_info::lli_async_rc, ll_inode_info::lli_clob, lov_read_and_clear_async_rc(), and LUSTRE_FPRIVATE.
int ll_fsync (struct file * file, struct dentry * dentry, int datasync)
Definition at line 2846 of file file.c.
References CDEBUG, CL_FSYNC_ALL, cl_sync_file_range(), D_VFSTRACE, DFID, ENTRY, ll_file_data::fd_write_failed, ll_i2info(), ll_i2sbi(), ll_inode2fid(), ll_stats_ops_tally(), ll_inode_info::lli_async_rc, ll_inode_info::lli_clob, lov_read_and_clear_async_rc(), LPROC_LL_FSYNC, LUSTRE_FPRIVATE, md_fsync(), PFID, ptlrpc_req_finished(), and RETURN.
struct posix_acl* ll_get_acl (struct inode * inode, int type) [read]
Definition at line 3549 of file file.c.
References ENTRY, ll_i2info(), ll_inode_info::lli_lock, ll_inode_info::lli_posix_acl, and RETURN.
Referenced by ll_check_acl().
int ll_get_fid_by_name (struct inode * parent, const char * name, int namelen, struct lu_fid * fid, struct inode ** inode)
Definition at line 3049 of file file.c.
References ENTRY, GOTO, ll_finish_md_op_data(), ll_i2sbi(), ll_prep_inode(), ll_prep_md_op_data(), LUSTRE_OPC_ANY, mdt_body::mbo_fid1, md_getattr_name(), OBD_MD_FLID, OBD_MD_FLTYPE, md_op_data::op_data, md_op_data::op_valid, ptlrpc_req_finished(), req_capsule_server_get(), RETURN, RMF_MDT_BODY, and ptlrpc_request::rq_pill.
Referenced by ll_dir_ioctl(), and ll_migrate().
static int ll_get_grouplock (struct inode * inode, struct file * file, unsigned long arg) [static]
Definition at line 1629 of file file.c.
References CDEBUG, CERROR, cl_get_grouplock(), cl_put_grouplock(), CWARN, D_INFO, ENTRY, ll_file_data::fd_flags, ll_file_data::fd_grouplock, LASSERT, ll_grouplock::lg_gid, ll_grouplock::lg_lock, LL_FILE_GROUP_LOCKED, ll_file_nolock(), ll_i2info(), ll_inode_info::lli_lock, LUSTRE_FPRIVATE, and RETURN.
Referenced by ll_file_ioctl(), and ll_swap_layouts().
int ll_getattr (struct vfsmount * mnt, struct dentry * de, struct kstat * stat)
Definition at line 3474 of file file.c.
References cl_fid_build_ino(), ll_i2info(), ll_i2sbi(), ll_inode_revalidate(), ll_need_32bit_api(), ll_stats_ops_tally(), ll_inode_info::lli_fid, LPROC_LL_GETATTR, MDS_INODELOCK_LOOKUP, MDS_INODELOCK_UPDATE, OBD_FAIL_GETATTR_DELAY, and OBD_FAIL_TIMEOUT.
int ll_have_md_lock (struct inode * inode, __u64 * bits, enum ldlm_mode l_req_mode)
test if some locks matching bits and l_req_mode are acquired
bits can be in different locks
if found clear the common lock bits in *bits
the bits not found, are kept in *bits
Parameters:
inode [IN]
bits [IN] searched lock bits [IN]
l_req_mode [IN] searched lock mode
Return values:
boolean,true iff all bits are found
Definition at line 3238 of file file.c.
References __u64, ldlm_inodebits::bits, CDEBUG, D_INFO, DFID, ENTRY, ldlm_policy_data::l_inodebits, ldlm_lock::l_policy_data, LCK_CR, LCK_CW, LCK_MINMODE, LCK_PR, LCK_PW, LDLM_FL_BLOCK_GRANTED, LDLM_FL_CBPENDING, LDLM_FL_TEST_LOCK, ldlm_handle2lock(), LDLM_IBITS, LDLM_LOCK_PUT, ldlm_lockname, ll_i2info(), ll_i2mdexp(), ll_inode_info::lli_fid, md_lock_match(), MDS_INODELOCK_MAXSHIFT, mode, PFID, and RETURN.
Referenced by __ll_inode_revalidate(), ll_md_blocking_ast(), and ll_readdir().
static int ll_hsm_import (struct inode * inode, struct file * file, struct hsm_user_import * hui) [static]
Definition at line 2108 of file file.c.
References ENTRY, GOTO, HS_ARCHIVED, HS_EXISTS, HS_RELEASED, hsm_state_set::hss_archive_id, HSS_ARCHIVE_ID, hsm_state_set::hss_setmask, HSS_SETMASK, hsm_state_set::hss_valid, hsm_user_import::hui_archive_id, hsm_user_import::hui_atime, hsm_user_import::hui_atime_ns, hsm_user_import::hui_gid, hsm_user_import::hui_mode, hsm_user_import::hui_mtime, hsm_user_import::hui_mtime_ns, hsm_user_import::hui_size, hsm_user_import::hui_uid, ll_hsm_state_set(), ll_setattr_raw(), make_kgid(), make_kuid(), OBD_ALLOC_PTR, OBD_FREE_PTR, and RETURN.
Referenced by ll_file_ioctl().
int ll_hsm_release (struct inode * inode)
Definition at line 1915 of file file.c.
References __u64, CDEBUG, cl_env_nested_get(), cl_env_nested_put(), D_INODE, DFID, ENTRY, EXIT, FMODE_WRITE, GOTO, ll_close_inode_openhandle(), ll_data_version(), LL_DV_WR_FLUSH, ll_get_fsname(), ll_i2info(), ll_lease_close(), ll_lease_open(), ll_merge_attr(), MDS_HSM_RELEASE, MDS_OPEN_RELEASE, and PFID.
Referenced by ll_dir_ioctl().
int ll_hsm_state_set (struct inode * inode, struct hsm_state_set * hss)
Definition at line 2074 of file file.c.
References CFS_CAP_SYS_ADMIN, cfs_capable(), ENTRY, HSM_FLAGS_MASK, HSM_USER_MASK, hsm_state_set::hss_archive_id, HSS_ARCHIVE_ID, hsm_state_set::hss_clearmask, hsm_state_set::hss_setmask, hsm_state_set::hss_valid, ll_finish_md_op_data(), LL_HSM_MAX_ARCHIVE, ll_i2mdexp(), LL_IOC_HSM_STATE_SET, ll_prep_md_op_data(), LUSTRE_OPC_ANY, obd_iocontrol(), md_op_data::op_data, and RETURN.
Referenced by ll_file_ioctl(), ll_hsm_import(), and ll_setattr_raw().
int ll_inode_permission (struct inode * inode, int mask, struct nameidata * nd)
Definition at line 3601 of file file.c.
References __kgid_val(), __kuid_val(), __ll_inode_revalidate(), CDEBUG, CFS_CAP_FS_MASK, D_OTHER, D_VFSTRACE, DFID, ENTRY, GLOBAL_ROOT_UID, ll_check_acl(), ll_sb_info::ll_flags, ll_generic_permission, ll_i2sbi(), ll_inode2fid(), LL_SBI_NOROOTSQUASH, LL_SBI_RMT_CLIENT, ll_sb_info::ll_squash, ll_stats_ops_tally(), LPROC_LL_INODE_PERM, lustre_check_remote_perm(), make_kgid(), make_kuid(), MDS_INODELOCK_LOOKUP, PFID, RETURN, root_squash_info::rsi_gid, root_squash_info::rsi_uid, uid_eq(), and unlikely.
static int ll_inode_revalidate (struct dentry * dentry, __u64 ibits) [static]
Definition at line 3438 of file file.c.
References __ll_inode_revalidate(), ENTRY, ll_file_test_flag(), ll_glimpse_size(), ll_i2info(), ll_merge_md_attr(), ll_inode_info::lli_atime, ll_inode_info::lli_ctime, ll_inode_info::lli_mtime, LLIF_FILE_RESTORING, LTIME_S, and RETURN.
Referenced by ll_getattr().
static int ll_inode_revalidate_fini (struct inode * inode, int rc) [static]
Definition at line 3297 of file file.c.
References CDEBUG_LIMIT, D_ERROR, D_INFO, DFID, ll_get_fsname(), ll_i2info(), ll_inode2fid(), and PFID.
Referenced by __ll_inode_revalidate().
static int ll_intent_file_open (struct file * file, void * lmm, int lmmsize, struct lookup_intent * itp) [static]
Definition at line 369 of file file.c.
References CDEBUG, D_VFSTRACE, DISP_LOOKUP_NEG, DISP_OPEN_OPEN, ENTRY, exp_connect_flags(), GOTO, it_disposition(), lookup_intent::it_flags, lookup_intent::it_lock_mode, it_open_error(), LASSERT, ll_finish_md_op_data(), ll_i2sbi(), ll_intent_drop_lock(), ll_md_blocking_ast(), ll_sb_info::ll_md_exp, ll_prep_inode(), ll_prep_md_op_data(), ll_release_openhandle(), ll_set_lock_data(), lu_name_is_valid_2(), LUSTRE_OPC_ANY, md_intent_lock(), MDS_OPEN_BY_FID, name, OBD_CONNECT_OPEN_BY_FID, md_op_data::op_data, md_op_data::op_data_size, ptlrpc_req_finished(), and RETURN.
Referenced by ll_file_open(), and ll_lov_setstripe_ea_info().
static void ll_io_init (struct cl_io * io, const struct file * file, int write) [static]
Definition at line 1012 of file file.c.
References cl_io::ci_lockreq, cl_io::ci_no_srvlock, cl_io::ci_noatime, cl_io::ci_obj, cl_io::ci_rw, cl_io::ci_wr, CILR_MANDATORY, CILR_MAYBE, CILR_NEVER, cl_io_rw_common::crw_nonblock, file_is_noatime(), ll_file_nolock(), ll_i2info(), ll_inode_info::lli_clob, and cl_io::u.
Referenced by ll_file_io_generic().
static enum llioc_iter ll_iocontrol_call (struct inode * inode, struct file * file, unsigned int cmd, unsigned long arg, int * rcp) [static]
Definition at line 3845 of file file.c.
References llioc_ctl_data::ioc_head, llioc_ctl_data::ioc_sem, llioc_data::iocd_cb, llioc_data::iocd_cmd, llioc_data::iocd_count, llioc_data::iocd_list, list_for_each_entry, llioc, LLIOC_CONT, LLIOC_STOP, and ret.
Referenced by ll_file_ioctl().
void* ll_iocontrol_register (llioc_callback_t cb, int count, unsigned int * cmd)
Definition at line 3789 of file file.c.
References ENTRY, llioc_ctl_data::ioc_head, llioc_ctl_data::ioc_sem, llioc_data::iocd_cb, llioc_data::iocd_cmd, llioc_data::iocd_count, llioc_data::iocd_list, llioc_data::iocd_size, list_add_tail(), llioc, LLIOC_MAX_CMD, OBD_ALLOC, RETURN, and size.
Referenced by lloop_init().
void ll_iocontrol_unregister (void * magic)
Definition at line 3817 of file file.c.
References CWARN, llioc_ctl_data::ioc_head, llioc_ctl_data::ioc_sem, llioc_data::iocd_list, llioc_data::iocd_size, list_del(), list_for_each_entry, llioc, OBD_FREE, and size.
Referenced by lloop_exit(), and lloop_init().
static int ll_ladvise (struct inode * inode, struct file * file, __u64 flags, struct lu_ladvise * ladvise) [static]
Definition at line 2224 of file file.c.
References cl_io::ci_ladvise, cl_io::ci_obj, cl_io::ci_result, CIT_LADVISE, cl_env_nested_get(), cl_env_nested_put(), cl_io_fini(), cl_io_init(), cl_io_loop(), ENTRY, ll_i2info(), ll_inode2fid(), lu_ladvise::lla_advice, lu_ladvise::lla_end, lu_ladvise::lla_start, ll_inode_info::lli_clob, RETURN, cl_io::u, and vvp_env_thread_io().
Referenced by ll_file_ioctl().
int ll_layout_conf (struct inode * inode, const struct cl_object_conf * conf)
Definition at line 3872 of file file.c.
References CDEBUG, cl_conf_set(), cl_env_nested_get(), cl_env_nested_put(), cl_layout::cl_layout_gen, cl_object_layout_get(), cl_object_conf::coc_lock, cl_object_conf::coc_opc, D_VFSTRACE, DFID, ENTRY, GOTO, LASSERT, ldlm_has_layout(), ldlm_lock_allow_match(), ll_i2info(), ll_layout_version_get(), ll_layout_version_set(), ll_inode_info::lli_clob, ll_inode_info::lli_fid, OBJECT_CONF_SET, PFID, and RETURN.
Referenced by ll_layout_lock_set(), ll_md_blocking_ast(), and ll_prep_inode().
static int ll_layout_fetch (struct inode * inode, struct ldlm_lock * lock) [static]
Definition at line 3925 of file file.c.
References CDEBUG, D_INODE, DFID, ENTRY, EXIT, GOTO, ldlm_lock::l_lvb_data, ldlm_lock::l_lvb_len, ldlm_lock::l_lvb_type, ldlm_is_lvb_ready, ll_get_default_mdsize(), ll_i2sbi(), ll_inode2fid(), ll_sb_info::ll_md_exp, lock_res_and_lock(), LVB_T_LAYOUT, mdt_body::mbo_eadatasize, md_getxattr(), OBD_ALLOC_LARGE, OBD_FREE_LARGE, OBD_MD_FLXATTR, PFID, ptlrpc_req_finished(), req_capsule_server_get(), req_capsule_server_sized_get(), RETURN, RMF_EADATA, RMF_MDT_BODY, ptlrpc_request::rq_pill, unlikely, unlock_res_and_lock(), and XATTR_NAME_LOV.
Referenced by ll_layout_lock_set().
static int ll_layout_lock_set (struct lustre_handle * lockh, enum ldlm_mode mode, struct inode * inode) [static]
Apply the layout to the inode.
Layout lock is held and will be released in this function.
Definition at line 3997 of file file.c.
References CDEBUG, cl_object_conf::coc_inode, cl_object_conf::coc_layout, cl_object_conf::coc_lock, cl_object_conf::coc_opc, lustre_handle::cookie, D_INODE, DFID, ENTRY, EXIT, GOTO, ldlm_lock::l_lvb_data, ldlm_lock::l_lvb_len, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, LDLM_DEBUG, ldlm_handle2lock(), ldlm_has_layout(), ldlm_is_lvb_ready, ldlm_lock_decref(), LDLM_LOCK_PUT, ll_get_fsname(), ll_i2info(), ll_i2sbi(), ll_layout_conf(), ll_layout_fetch(), ll_sb_info::ll_md_exp, ll_inode_info::lli_fid, lock_res_and_lock(), lustre_handle_is_used(), md_set_lock_data(), OBJECT_CONF_SET, OBJECT_CONF_WAIT, PFID, RETURN, cl_object_conf::u, and unlock_res_and_lock().
Referenced by ll_layout_refresh_locked().
int ll_layout_refresh (struct inode * inode, __u32 * gen)
This function checks if there exists a LAYOUT lock on the client side, or enqueues it if it doesn't have one in cache.
This function will not hold layout lock so it may be revoked any time after this function returns. Any operations depend on layout should be redone in that case.
This function should be called before lov_io_init() to get an uptodate layout version, the caller should save the version number and after IO is finished, this function should be called again to verify that layout is not changed during IO time.
Definition at line 4155 of file file.c.
References CL_LAYOUT_GEN_NONE, ENTRY, fid_is_sane(), GOTO, LASSERT, ll_sb_info::ll_flags, ll_i2info(), ll_i2sbi(), ll_inode2fid(), ll_layout_refresh_locked(), ll_layout_version_get(), LL_SBI_LAYOUT_LOCK, ll_inode_info::lli_layout_mutex, and RETURN.
Referenced by ll_lov_setstripe(), vvp_io_fini(), and vvp_io_init().
static int ll_layout_refresh_locked (struct inode * inode) [static]
Definition at line 4076 of file file.c.
References lustre_handle::cookie, DFID, ldlm_enqueue_info::ei_type, ENTRY, IT_LAYOUT, lookup_intent::it_lock_mode, lookup_intent::it_op, lookup_intent::it_request, LCK_CR, LCK_CW, LCK_PR, LCK_PW, ldlm_completion_ast(), LDLM_DEBUG_NOLOCK, LDLM_IBITS, ll_finish_md_op_data(), ll_get_fsname(), ll_i2info(), ll_i2sbi(), ll_intent_drop_lock(), ll_layout_lock_set(), ll_md_blocking_ast(), ll_sb_info::ll_md_exp, ll_prep_md_op_data(), ll_set_lock_data(), ll_take_md_lock(), ll_inode_info::lli_fid, LUSTRE_OPC_ANY, md_enqueue(), MDS_INODELOCK_LAYOUT, mode, md_op_data::op_data, PFID, ptlrpc_req_finished(), and RETURN.
Referenced by ll_layout_refresh().
int ll_layout_restore (struct inode * inode, loff_t offset, __u64 length)
This function send a restore request to the MDT.
Definition at line 4187 of file file.c.
References ENTRY, hsm_request::hr_action, hsm_request::hr_archive_id, hsm_request::hr_flags, hsm_request::hr_itemcount, HUA_RESTORE, hsm_user_item::hui_extent, hsm_user_item::hui_fid, hsm_user_request::hur_request, hsm_user_request::hur_user_item, hsm_extent::length, ll_i2info(), ll_i2sbi(), LL_IOC_HSM_REQUEST, OBD_ALLOC, OBD_FREE, obd_iocontrol(), hsm_extent::offset, and RETURN.
Referenced by vvp_io_fini().
static int ll_lease_close (struct obd_client_handle * och, struct inode * inode, bool * lease_broken) [static]
Release lease and close the file.
It will check if the lease has ever broken.
Definition at line 901 of file file.c.
References CDEBUG, D_INODE, DFID, ENTRY, ldlm_cli_cancel(), ldlm_handle2lock(), ldlm_is_cancel, LDLM_LOCK_PUT, ll_close_inode_openhandle(), ll_i2info(), lock_res_and_lock(), obd_client_handle::och_lease_handle, PFID, RETURN, and unlock_res_and_lock().
Referenced by ll_file_ioctl(), ll_hsm_release(), ll_md_close(), and ll_migrate().
static struct obd_client_handle* ll_lease_open (struct inode * inode, struct file * file, fmode_t fmode, __u64 open_flags) [static, read]
Acquire a lease and open the file.
Definition at line 700 of file file.c.
References __u64, CERROR, lustre_handle::cookie, DFID, DISP_ENQ_OPEN_REF, DISP_LOOKUP_NEG, DISP_OPEN_LEASE, DISP_OPEN_OPEN, ENTRY, ll_file_data::fd_lease_och, ll_file_data::fd_och, FMODE_EXEC, FMODE_READ, FMODE_WRITE, GOTO, it_disposition(), lookup_intent::it_flags, lookup_intent::it_lock_bits, lookup_intent::it_lock_mode, lookup_intent::it_op, IT_OPEN, it_open_error(), LASSERT, LDLM_FL_EXCL, LDLM_FL_NO_LRU, ldlm_lock_decref_and_cancel(), ll_close_inode_openhandle(), ll_finish_md_op_data(), ll_get_fsname(), ll_i2info(), ll_i2sbi(), ll_inode2fid(), ll_intent_release(), ll_md_blocking_lease_ast(), ll_sb_info::ll_md_exp, ll_och_fill(), ll_prep_md_op_data(), ll_set_lock_data(), ll_inode_info::lli_mds_read_och, ll_inode_info::lli_mds_write_och, ll_inode_info::lli_och_mutex, ll_inode_info::lli_open_fd_read_count, ll_inode_info::lli_open_fd_write_count, LPU64, LUSTRE_FPRIVATE, LUSTRE_OPC_ANY, md_intent_lock(), MDS_INODELOCK_OPEN, MDS_OPEN_BY_FID, MDS_OPEN_LEASE, MDS_OPEN_LOCK, OBD_ALLOC_PTR, OBD_FREE_PTR, obd_client_handle::och_fh, obd_client_handle::och_lease_handle, md_op_data::op_data, md_op_data::op_handle, PFID, ptlrpc_req_finished(), and RETURN.
Referenced by ll_file_ioctl(), ll_hsm_release(), and ll_migrate().
static long ll_lease_type_from_fmode (fmode_t fmode) [inline, static]
Definition at line 2168 of file file.c.
References FMODE_READ, FMODE_WRITE, LL_LEASE_RDLCK, and LL_LEASE_WRLCK.
Referenced by ll_file_ioctl().
static int ll_local_open (struct file * file, struct lookup_intent * it, struct ll_file_data * fd, struct obd_client_handle * och) [static]
Definition at line 449 of file file.c.
References ENTRY, ll_file_data::fd_lccs, ll_file_data::fd_lock, ll_file_data::fd_omode, ll_file_data::fd_ras, FMODE_EXEC, FMODE_READ, FMODE_WRITE, INIT_LIST_HEAD, lookup_intent::it_flags, LASSERT, ll_i2sbi(), ll_och_fill(), ll_readahead_init(), LUSTRE_FPRIVATE, and RETURN.
Referenced by ll_file_open().
int ll_lov_getstripe_ea_info (struct inode * inode, const char * filename, struct lov_mds_md ** lmmp, int * lmm_size, struct ptlrpc_request ** request)
Definition at line 1471 of file file.c.
References CDEBUG, cpu_to_le32, D_INFO, GOTO, LASSERT, le16_to_cpu, le32_to_cpu, ll_finish_md_op_data(), ll_get_default_mdsize(), ll_i2sbi(), ll_sb_info::ll_md_exp, ll_prep_md_op_data(), LOV_MAGIC, LOV_MAGIC_V1, LOV_MAGIC_V3, lov_mds_md, LOV_PATTERN_F_RELEASED, LUSTRE_OPC_ANY, lustre_swab_lov_user_md_objects(), lustre_swab_lov_user_md_v1(), lustre_swab_lov_user_md_v3(), mdt_body::mbo_eadatasize, mdt_body::mbo_mode, mdt_body::mbo_valid, md_getattr_name(), OBD_MD_FLDIREA, OBD_MD_FLEASIZE, md_op_data::op_data, md_op_data::op_valid, req_capsule_server_get(), req_capsule_server_sized_get(), RETURN, RMF_MDT_BODY, RMF_MDT_MD, and ptlrpc_request::rq_pill.
Referenced by ll_dir_ioctl().
static int ll_lov_setea (struct inode * inode, struct file * file, unsigned long arg) [static]
Definition at line 1556 of file file.c.
References __u64, __user, CFS_CAP_SYS_ADMIN, cfs_capable(), ENTRY, FMODE_WRITE, GOTO, ll_lov_setstripe_ea_info(), lov_user_md, MDS_OPEN_HAS_OBJS, OBD_ALLOC_LARGE, OBD_FREE_LARGE, and RETURN.
Referenced by ll_file_ioctl().
static int ll_lov_setstripe (struct inode * inode, struct file * file, unsigned long arg) [static]
Definition at line 1600 of file file.c.
References __u64, ENTRY, FMODE_WRITE, ll_copy_user_md(), ll_file_getstripe(), ll_layout_refresh(), ll_lov_setstripe_ea_info(), lov_user_md, OBD_FREE, and RETURN.
Referenced by ll_file_ioctl().
int ll_lov_setstripe_ea_info (struct inode * inode, struct file * file, __u64 flags, struct lov_user_md * lum, int lum_size)
Definition at line 1445 of file file.c.
References cl_lov_delay_create_clear(), ENTRY, GOTO, lookup_intent::it_op, IT_OPEN, ll_inode_size_lock(), ll_inode_size_unlock(), ll_intent_file_open(), ll_intent_release(), ll_release_openhandle(), MDS_OPEN_BY_FID, and RETURN.
Referenced by ll_lov_setea(), ll_lov_setstripe(), and ll_setxattr().
static int ll_md_blocking_lease_ast (struct ldlm_lock * lock, struct ldlm_lock_desc * desc, void * data, int flag) [static]
Definition at line 673 of file file.c.
References CDEBUG, D_INODE, ENTRY, LCF_ASYNC, LDLM_CB_BLOCKING, LDLM_CB_CANCELING, ldlm_cli_cancel(), ldlm_lock2handle(), and RETURN.
Referenced by ll_lease_open().
static int ll_md_close (struct inode * inode, struct file * file) [static]
Definition at line 245 of file file.c.
References __u64, CDEBUG, D_ERROR, D_INODE, DFID, ENTRY, ll_file_data::fd_flags, ll_file_data::fd_grouplock, ll_file_data::fd_lease_och, ll_file_data::fd_och, ll_file_data::fd_omode, FMODE_EXEC, FMODE_WRITE, GOTO, ldlm_policy_data::l_inodebits, LASSERT, LCK_CR, LCK_CW, LCK_PR, LDLM_FL_BLOCK_GRANTED, LDLM_FL_TEST_LOCK, LDLM_IBITS, ll_grouplock::lg_gid, ll_close_inode_openhandle(), ll_file_data_put(), LL_FILE_GROUP_LOCKED, ll_i2info(), ll_i2mdexp(), ll_inode2fid(), ll_lease_close(), ll_md_real_close(), ll_put_grouplock(), ll_inode_info::lli_fid, ll_inode_info::lli_och_mutex, ll_inode_info::lli_open_fd_exec_count, ll_inode_info::lli_open_fd_read_count, ll_inode_info::lli_open_fd_write_count, LUSTRE_FPRIVATE, md_lock_match(), MDS_INODELOCK_OPEN, PFID, RETURN, and unlikely.
Referenced by ll_file_release().
int ll_md_real_close (struct inode * inode, fmode_t fmode)
Definition at line 203 of file file.c.
References __u64, ENTRY, FMODE_EXEC, FMODE_READ, FMODE_WRITE, LASSERT, ll_close_inode_openhandle(), ll_i2info(), ll_inode_info::lli_mds_exec_och, ll_inode_info::lli_mds_read_och, ll_inode_info::lli_mds_write_och, ll_inode_info::lli_och_mutex, ll_inode_info::lli_open_fd_exec_count, ll_inode_info::lli_open_fd_read_count, ll_inode_info::lli_open_fd_write_count, and RETURN.
Referenced by ll_clear_inode(), ll_md_blocking_ast(), and ll_md_close().
int ll_merge_attr (const struct lu_env * env, struct inode * inode)
Definition at line 929 of file file.c.
References cl_attr::cat_atime, cl_attr::cat_blocks, cl_attr::cat_ctime, cl_attr::cat_mtime, cl_attr::cat_size, CDEBUG, cl_object_attr_get(), cl_object_attr_lock(), cl_object_attr_unlock(), D_VFSTRACE, DFID, ENTRY, GOTO, ll_i2info(), ll_inode_size_lock(), ll_inode_size_unlock(), ll_inode_info::lli_atime, ll_inode_info::lli_clob, ll_inode_info::lli_ctime, ll_inode_info::lli_fid, ll_inode_info::lli_mtime, LPU64, LTIME_S, PFID, RETURN, and vvp_env_thread_attr().
Referenced by cl_glimpse_lock(), ll_hsm_release(), vvp_io_write_commit(), and vvp_io_write_start().
static int ll_merge_md_attr (struct inode * inode) [static]
Definition at line 3415 of file file.c.
References cl_attr::cat_atime, cl_attr::cat_blocks, cl_attr::cat_ctime, cl_attr::cat_mtime, cl_attr::cat_nlink, cl_attr::cat_size, LASSERT, ll_i2info(), ll_i2mdexp(), ll_md_blocking_ast(), ll_inode_info::lli_atime, ll_inode_info::lli_ctime, ll_inode_info::lli_mtime, md_merge_attr(), RETURN, and set_nlink().
Referenced by ll_inode_revalidate().
int ll_migrate (struct inode * parent, struct file * file, int mdtidx, const char * name, int namelen)
Definition at line 3083 of file file.c.
References __u64, CDEBUG, CERROR, CLI_MIGRATE, lustre_handle::cookie, D_INFO, D_VFSTRACE, DEAD_HANDLE_MAGIC, DFID, ENTRY, fid_is_sane(), FMODE_WRITE, GOTO, ll_data_version(), LL_DV_WR_FLUSH, ll_finish_md_op_data(), ll_get_fid_by_name(), ll_get_fsname(), ll_get_mdt_idx_by_fid(), ll_i2sbi(), ll_inode2fid(), ll_lease_close(), ll_lease_open(), ll_prep_md_op_data(), ll_update_times(), LUSTRE_OPC_ANY, mdt_body::mbo_valid, md_clear_open_replay_data(), md_rename(), MDS_RENAME_MIGRATE, OBD_FREE_PTR, OBD_MD_CLOSE_INTENT_EXECED, obd_mod_put, obd_client_handle::och_fh, obd_client_handle::och_lease_handle, obd_client_handle::och_mod, md_op_data::op_bias, md_op_data::op_cli_flags, md_op_data::op_data, md_op_data::op_data_version, md_op_data::op_fid3, md_op_data::op_handle, md_op_data::op_lease_handle, md_op_data::op_mds, PFID, ptlrpc_req_finished(), req_capsule_server_get(), RETURN, RMF_MDT_BODY, and ptlrpc_request::rq_pill.
Referenced by ll_dir_ioctl().
static int ll_och_fill (struct obd_export * md_exp, struct lookup_intent * it, struct obd_client_handle * och) [static]
Definition at line 434 of file file.c.
References lustre_handle::cookie, lookup_intent::it_flags, lookup_intent::it_lock_handle, lookup_intent::it_request, mdt_body::mbo_fid1, mdt_body::mbo_handle, md_set_open_replay_data(), OBD_CLIENT_HANDLE_MAGIC, obd_client_handle::och_fh, obd_client_handle::och_fid, obd_client_handle::och_flags, obd_client_handle::och_lease_handle, obd_client_handle::och_magic, req_capsule_server_get(), RMF_MDT_BODY, and ptlrpc_request::rq_pill.
Referenced by ll_lease_open(), ll_local_open(), and ll_release_openhandle().
static void ll_prepare_close (struct inode * inode, struct md_op_data * op_data, struct obd_client_handle * och) [static]
Packs all the attributes into for the CLOSE rpc.
Definition at line 93 of file file.c.
References ATTR_CTIME_SET, ENTRY, EXIT, FMODE_WRITE, ll_file_test_and_clear_flag(), ll_i2info(), ll_prep_md_op_data(), LLIF_DATA_MODIFIED, LUSTRE_OPC_ANY, MDS_DATA_MODIFIED, obd_client_handle::och_fh, obd_client_handle::och_flags, md_op_data::op_attr, md_op_data::op_attr_blocks, md_op_data::op_attr_flags, md_op_data::op_bias, and md_op_data::op_handle.
Referenced by ll_close_inode_openhandle().
static int ll_put_grouplock (struct inode * inode, struct file * file, unsigned long arg) [static]
Definition at line 1676 of file file.c.
References CDEBUG, cl_put_grouplock(), CWARN, D_INFO, ENTRY, ll_file_data::fd_flags, ll_file_data::fd_grouplock, LASSERT, ll_grouplock::lg_gid, ll_grouplock::lg_lock, LL_FILE_GROUP_LOCKED, ll_i2info(), ll_inode_info::lli_lock, LUSTRE_FPRIVATE, and RETURN.
Referenced by ll_file_ioctl(), ll_md_close(), and ll_swap_layouts().
int ll_release_openhandle (struct dentry * dentry, struct lookup_intent * it)
Close inode open handle.
Parameters:
dentry [in] dentry which contains the inode
it [in,out] intent which contains open info and result
Return values:
0 success
<0 failure
Definition at line 1719 of file file.c.
References DISP_ENQ_OPEN_REF, DISP_OPEN_OPEN, ENTRY, GOTO, it_clear_disposition(), it_disposition(), it_open_error(), lookup_intent::it_request, LASSERT, ll_close_inode_openhandle(), ll_i2sbi(), ll_och_fill(), OBD_ALLOC, ptlrpc_req_finished(), and RETURN.
Referenced by ll_file_open(), ll_intent_file_open(), ll_lookup_it(), and ll_lov_setstripe_ea_info().
static int ll_swap_layouts (struct file * file1, struct file * file2, struct lustre_swap_layouts * lsl) [static]
Definition at line 1968 of file file.c.
References __u64, ll_swap_stack::check_dv1, ll_swap_stack::check_dv2, ll_swap_stack::dv1, ll_swap_stack::dv2, GOTO, ll_swap_stack::inode1, ll_swap_stack::inode2, ll_check_swap_layouts_validity(), ll_data_version(), ll_finish_md_op_data(), ll_get_grouplock(), ll_i2mdexp(), ll_inode2fid(), LL_IOC_LOV_SWAP_LAYOUTS, ll_prep_md_op_data(), ll_put_grouplock(), lu_fid_cmp(), LUSTRE_OPC_ANY, mdc_swap_layouts::msl_flags, OBD_ALLOC_PTR, OBD_FREE_PTR, obd_iocontrol(), md_op_data::op_data, RETURN, lustre_swap_layouts::sl_dv1, lustre_swap_layouts::sl_dv2, lustre_swap_layouts::sl_flags, lustre_swap_layouts::sl_gid, swap, SWAP_LAYOUTS_CHECK_DV1, and SWAP_LAYOUTS_CHECK_DV2.
Referenced by ll_file_ioctl().
static int ll_swap_layouts_close (struct obd_client_handle * och, struct inode * inode, struct inode * inode2) [static]
Definition at line 860 of file file.c.
References CDEBUG, D_INODE, DFID, ENTRY, GOTO, ll_check_swap_layouts_validity(), ll_close_inode_openhandle(), ll_get_fsname(), ll_inode2fid(), lu_fid_cmp(), MDS_CLOSE_LAYOUT_SWAP, OBD_FREE_PTR, PFID, and RETURN.
Referenced by ll_file_ioctl().
enum ldlm_mode ll_take_md_lock (struct inode * inode, __u64 bits, struct lustre_handle * lockh, __u64 flags, enum ldlm_mode mode)
Definition at line 3279 of file file.c.
References CDEBUG, D_INFO, DFID, ENTRY, ldlm_policy_data::l_inodebits, LDLM_FL_BLOCK_GRANTED, LDLM_IBITS, ll_i2info(), ll_i2mdexp(), ll_inode_info::lli_fid, md_lock_match(), PFID, and RETURN.
Referenced by ll_layout_refresh_locked(), and ll_xattr_find_get_lock().
static loff_t llseek_execute (struct file * file, loff_t offset, loff_t maxsize) [inline, static]
Definition at line 2665 of file file.c.
References FMODE_UNSIGNED_OFFSET.
Referenced by generic_file_llseek_size().
Variable Documentation
struct inode_operations ll_file_inode_operations
Initial value:
 {
        .setattr        = ll_setattr,
        .getattr        = ll_getattr,
        .permission     = ll_inode_permission,
        .setxattr       = ll_setxattr,
        .getxattr       = ll_getxattr,
        .listxattr      = ll_listxattr,
        .removexattr    = ll_removexattr,
        .fiemap         = ll_fiemap,
}
Definition at line 3757 of file file.c.
Referenced by ll_read_inode2().
struct file_operations ll_file_operations
Initial value:
 {
        .read           = ll_file_read,
        .aio_read       = ll_file_aio_read,
        .write          = ll_file_write,
        .aio_write      = ll_file_aio_write,
        .unlocked_ioctl = ll_file_ioctl,
        .open           = ll_file_open,
        .release        = ll_file_release,
        .mmap           = ll_file_mmap,
        .llseek         = ll_file_seek,
        .splice_read    = ll_file_splice_read,
        .fsync          = ll_fsync,
        .flush          = ll_flush
}
Definition at line 3680 of file file.c.
Referenced by client_common_fill_super().
struct file_operations ll_file_operations_flock
Initial value:
 {
        .read           = ll_file_read,
        .aio_read       = ll_file_aio_read,
        .write          = ll_file_write,
        .aio_write      = ll_file_aio_write,
        .unlocked_ioctl = ll_file_ioctl,
        .open           = ll_file_open,
        .release        = ll_file_release,
        .mmap           = ll_file_mmap,
        .llseek         = ll_file_seek,
        .splice_read    = ll_file_splice_read,
        .fsync          = ll_fsync,
        .flush          = ll_flush,
        .flock          = ll_file_flock,
        .lock           = ll_file_flock
}
Definition at line 3704 of file file.c.
Referenced by client_common_fill_super().
struct file_operations ll_file_operations_noflock
Initial value:
 {
        .read           = ll_file_read,
        .aio_read       = ll_file_aio_read,
        .write          = ll_file_write,
        .aio_write      = ll_file_aio_write,
        .unlocked_ioctl = ll_file_ioctl,
        .open           = ll_file_open,
        .release        = ll_file_release,
        .mmap           = ll_file_mmap,
        .llseek         = ll_file_seek,
        .splice_read    = ll_file_splice_read,
        .fsync          = ll_fsync,
        .flush          = ll_flush,
        .flock          = ll_file_noflock,
        .lock           = ll_file_noflock
}
Definition at line 3731 of file file.c.
Referenced by client_common_fill_super().
struct llioc_ctl_data llioc [static]
Referenced by ll_iocontrol_call(), ll_iocontrol_register(), and ll_iocontrol_unregister().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.