Lustre: lustre/fld/fld_handler.c File Reference
lustre/fld/fld_handler.c File Reference
#include <libcfs/libcfs.h>
#include <linux/module.h>
#include <obd.h>
#include <obd_support.h>
#include <lustre_fid.h>
#include <lustre_fld.h>
#include <lustre_req_layout.h>
#include <lprocfs_status.h>
#include "fld_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_FLD
Functions
LU_KEY_INIT_FINI (fld, struct fld_thread_info)
LU_CONTEXT_KEY_DEFINE (fld, LCT_MD_THREAD|LCT_DT_THREAD|LCT_MG_THREAD)
int fld_server_mod_init (void)
void fld_server_mod_exit (void)
int fld_declare_server_create (const struct lu_env *env, struct lu_server_fld *fld, const struct lu_seq_range *range, struct thandle *th)
int fld_server_create (const struct lu_env *env, struct lu_server_fld *fld, const struct lu_seq_range *range, struct thandle *th)
Insert FLD index entry and update FLD cache.
int fld_name_to_index (const char *name, __u32 *index)
Extract index information from fld name like srv-fsname-MDT0000.
int fld_update_from_controller (const struct lu_env *env, struct lu_server_fld *fld)
Retrieve fldb entry from MDT0 and add to local FLDB and cache.
int fld_local_lookup (const struct lu_env *env, struct lu_server_fld *fld, u64 seq, struct lu_seq_range *range)
Lookup sequece in local cache/fldb.
int fld_server_lookup (const struct lu_env *env, struct lu_server_fld *fld, u64 seq, struct lu_seq_range *range)
Lookup MDT/OST by seq, returns a range for given seq.
static int fld_handle_lookup (struct tgt_session_info *tsi)
All MDT server handle fld lookup operation.
static int fld_handle_read (struct tgt_session_info *tsi)
static int fld_handle_query (struct tgt_session_info *tsi)
int fid_is_local (const struct lu_env *env, struct lu_site *site, const struct lu_fid *fid)
static void fld_server_proc_fini (struct lu_server_fld *fld)
static int fld_server_proc_init (struct lu_server_fld *fld)
int fld_server_init (const struct lu_env *env, struct lu_server_fld *fld, struct dt_device *dt, const char *prefix, int type)
void fld_server_fini (const struct lu_env *env, struct lu_server_fld *fld)
Variables
struct tgt_handler fld_handlers []
Define Documentation
#define DEBUG_SUBSYSTEM S_FLD
Definition at line 45 of file fld_handler.c.
Function Documentation
static int fld_handle_lookup (struct tgt_session_info * tsi) [static]
All MDT server handle fld lookup operation.
But only MDT0 has fld index. if entry is not found in cache we need to forward lookup request to MDT0
Definition at line 286 of file fld_handler.c.
References CDEBUG, D_INFO, DRANGE, ENTRY, err_serious(), obd_export::exp_obd, fld_server_lookup(), lu_device::ld_site, lu_server_fld::lsf_name, lu_seq_range::lsr_start, lu_site2seq(), obd_device::obd_lu_dev, PRANGE, req_capsule_client_get(), req_capsule_server_get(), req_capsule_server_pack(), RETURN, RMF_FLD_MDFLD, seq_server_site::ss_server_fld, tgt_session_info::tsi_env, tgt_session_info::tsi_exp, tgt_session_info::tsi_pill, and unlikely.
Referenced by fld_handle_query().
static int fld_handle_query (struct tgt_session_info * tsi) [static]
Definition at line 350 of file fld_handler.c.
References ENTRY, fld_handle_lookup(), req_capsule_set(), RETURN, RQF_FLD_QUERY, and tgt_session_info::tsi_pill.
static int fld_handle_read (struct tgt_session_info * tsi) [static]
Definition at line 320 of file fld_handler.c.
References ENTRY, err_serious(), obd_export::exp_obd, fld_server_read(), lu_device::ld_site, lu_site2seq(), obd_device::obd_lu_dev, RCL_SERVER, req_capsule_client_get(), req_capsule_server_get(), req_capsule_server_pack(), req_capsule_set(), req_capsule_set_size(), RETURN, RMF_FLD_MDFLD, RMF_GENERIC_DATA, RQF_FLD_READ, tgt_session_info::tsi_env, tgt_session_info::tsi_exp, tgt_session_info::tsi_pill, and unlikely.
int fld_name_to_index (const char * name, __u32 * index)
Extract index information from fld name like srv-fsname-MDT0000.
Definition at line 110 of file fld_handler.c.
References CDEBUG, D_INFO, ENTRY, RETURN, and target_name2index().
Referenced by fld_index_init(), fld_server_lookup(), and fld_update_from_controller().
void fld_server_mod_exit (void)
Definition at line 71 of file fld_handler.c.
References fld_thread_key, and lu_context_key_degister().
Referenced by fld_exit().
int fld_server_mod_init (void)
Definition at line 65 of file fld_handler.c.
References fld_thread_key, LU_CONTEXT_KEY_INIT, and lu_context_key_register().
Referenced by fld_init().
static void fld_server_proc_fini (struct lu_server_fld * fld) [static]
Definition at line 437 of file fld_handler.c.
Referenced by fld_server_fini().
static int fld_server_proc_init (struct lu_server_fld * fld) [static]
Definition at line 432 of file fld_handler.c.
Referenced by fld_server_init().
LU_CONTEXT_KEY_DEFINE (fld , LCT_MD_THREAD|LCT_DT_THREAD| LCT_MG_THREAD)
LU_KEY_INIT_FINI (fld , struct fld_thread_info)
Variable Documentation
struct tgt_handler fld_handlers[]
Initial value:
 {
TGT_FLD_HDL_VAR(0,      FLD_QUERY,      fld_handle_query),
TGT_FLD_HDL_VAR(0,      FLD_READ,       fld_handle_read),
}
Definition at line 504 of file fld_handler.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.