Lustre: lustre/fld/fld_internal.h File Reference
lustre/fld/fld_internal.h File Reference
#include <obd.h>
#include <lustre/lustre_idl.h>
#include <libcfs/libcfs.h>
#include <lustre_fld.h>
Data Structures
struct fld_stats
struct lu_fld_hash
struct fld_cache_entry
struct fld_cache
Typedefs
typedef int(* fld_hash_func_t)(struct lu_client_fld *, __u64)
typedef struct lu_fld_target *(* fld_scan_func_t)(struct lu_client_fld *, __u64)
Enumerations
enum { FLD_SERVER_CACHE_SIZE = (4 * 0x100000), FLD_CLIENT_CACHE_SIZE = (1 * 0x100000) }
enum { FLD_SERVER_CACHE_THRESHOLD = 10, FLD_CLIENT_CACHE_THRESHOLD = 10 }
Functions
int fld_client_rpc (struct obd_export *exp, struct lu_seq_range *range, __u32 fld_op, struct ptlrpc_request **reqp)
struct fld_cache * fld_cache_init (const char *name, int cache_size, int cache_threshold)
create fld cache.
void fld_cache_fini (struct fld_cache *cache)
destroy fld cache.
void fld_cache_flush (struct fld_cache *cache)
kill all fld cache entries.
int fld_cache_insert (struct fld_cache *cache, const struct lu_seq_range *range)
struct fld_cache_entry * fld_cache_entry_create (const struct lu_seq_range *range)
int fld_cache_insert_nolock (struct fld_cache *cache, struct fld_cache_entry *f_new)
Insert FLD entry in FLD cache.
void fld_cache_delete (struct fld_cache *cache, const struct lu_seq_range *range)
Delete FLD entry in FLD cache.
void fld_cache_delete_nolock (struct fld_cache *cache, const struct lu_seq_range *range)
int fld_cache_lookup (struct fld_cache *cache, const u64 seq, struct lu_seq_range *range)
lookup seq sequence for range in fld cache.
struct fld_cache_entry * fld_cache_entry_lookup (struct fld_cache *cache, const struct lu_seq_range *range)
lookup seq sequence for range in fld cache.
void fld_cache_entry_delete (struct fld_cache *cache, struct fld_cache_entry *node)
delete given node from list.
struct fld_cache_entry * fld_cache_entry_lookup_nolock (struct fld_cache *cache, const struct lu_seq_range *range)
static const char * fld_target_name (const struct lu_fld_target *tar)
Variables
struct lu_fld_hash fld_hash []
Typedef Documentation
typedef int(* fld_hash_func_t)(struct lu_client_fld *, __u64)
Definition at line 72 of file fld_internal.h.
typedef struct lu_fld_target*(* fld_scan_func_t)(struct lu_client_fld *, __u64)
Definition at line 75 of file fld_internal.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
FLD_SERVER_CACHE_SIZE
FLD_CLIENT_CACHE_SIZE
Definition at line 128 of file fld_internal.h.
anonymous enum
Enumerator:
FLD_SERVER_CACHE_THRESHOLD
FLD_CLIENT_CACHE_THRESHOLD
Definition at line 136 of file fld_internal.h.
Function Documentation
void fld_cache_delete (struct fld_cache * cache, const struct lu_seq_range * range)
Delete FLD entry in FLD cache.
Definition at line 479 of file fld_cache.c.
References fld_cache::fci_lock, and fld_cache_delete_nolock().
void fld_cache_delete_nolock (struct fld_cache * cache, const struct lu_seq_range * range)
Definition at line 456 of file fld_cache.c.
References fld_cache_entry::fce_range, fld_cache::fci_entries_head, fld_cache_entry_delete(), head, list_for_each_entry_safe, lu_seq_range::lsr_end, lu_seq_range::lsr_flags, and lu_seq_range::lsr_start.
Referenced by fld_cache_delete(), and fld_index_create().
struct fld_cache_entry* fld_cache_entry_create (const struct lu_seq_range * range) [read]
Definition at line 368 of file fld_cache.c.
References fld_cache_entry::fce_range, LASSERT, lu_seq_range_is_sane(), OBD_ALLOC_PTR, and RETURN.
Referenced by fld_cache_insert(), and fld_index_create().
void fld_cache_entry_delete (struct fld_cache * cache, struct fld_cache_entry * node)
delete given node from list.
Definition at line 121 of file fld_cache.c.
References fld_cache_entry::fce_list, fld_cache_entry::fce_lru, fld_cache::fci_cache_count, list_del(), and OBD_FREE_PTR.
Referenced by fld_cache_delete_nolock(), fld_cache_shrink(), and fld_fix_new_list().
struct fld_cache_entry* fld_cache_entry_lookup (struct fld_cache * cache, const struct lu_seq_range * range) [read]
lookup seq sequence for range in fld cache.
Definition at line 512 of file fld_cache.c.
References ENTRY, fld_cache::fci_lock, fld_cache_entry_lookup_nolock(), and RETURN.
struct fld_cache_entry* fld_cache_entry_lookup_nolock (struct fld_cache * cache, const struct lu_seq_range * range) [read]
Definition at line 488 of file fld_cache.c.
References fld_cache_entry::fce_range, fld_cache::fci_entries_head, head, list_for_each_entry, lu_seq_range::lsr_end, lu_seq_range::lsr_flags, lu_seq_range::lsr_start, and RETURN.
Referenced by fld_cache_entry_lookup().
void fld_cache_fini (struct fld_cache * cache)
destroy fld cache.
Definition at line 93 of file fld_cache.c.
References __u64, CDEBUG, D_INFO, ENTRY, EXIT, fld_cache::fci_name, fld_cache::fci_stat, fld_cache_flush(), fld_stats::fst_cache, fld_stats::fst_count, LASSERT, LPU64, OBD_FREE_PTR, and pct.
Referenced by fld_client_fini(), fld_server_fini(), and fld_server_init().
void fld_cache_flush (struct fld_cache * cache)
kill all fld cache entries.
Definition at line 247 of file fld_cache.c.
References ENTRY, EXIT, fld_cache::fci_cache_size, fld_cache::fci_lock, and fld_cache_shrink().
Referenced by fld_cache_fini(), and fld_client_flush().
struct fld_cache* fld_cache_init (const char * name, int cache_size, int cache_threshold) [read]
create fld cache.
Definition at line 56 of file fld_cache.c.
References CDEBUG, D_INFO, ENTRY, fld_cache::fci_cache_count, fld_cache::fci_cache_size, fld_cache::fci_entries_head, fld_cache::fci_lock, fld_cache::fci_lru, fld_cache::fci_name, fld_cache::fci_stat, fld_cache::fci_threshold, INIT_LIST_HEAD, LASSERT, OBD_ALLOC_PTR, RETURN, and strlcpy().
Referenced by fld_client_init(), and fld_server_init().
int fld_cache_insert (struct fld_cache * cache, const struct lu_seq_range * range)
Definition at line 437 of file fld_cache.c.
References fld_cache::fci_lock, fld_cache_entry_create(), fld_cache_insert_nolock(), OBD_FREE_PTR, and RETURN.
Referenced by fld_client_lookup(), fld_index_init(), and fld_server_lookup().
int fld_cache_insert_nolock (struct fld_cache * cache, struct fld_cache_entry * f_new)
Insert FLD entry in FLD cache.
This function handles all cases of merging and breaking up of ranges.
Definition at line 388 of file fld_cache.c.
References CDEBUG, D_INFO, DRANGE, ENTRY, fld_cache_entry::fce_list, fld_cache_entry::fce_range, fld_cache::fci_entries_head, fld_cache::fci_no_shrink, fld_cache_entry_add(), fld_cache_overlap_handle(), fld_cache_shrink(), head, list_for_each_entry_safe, lu_seq_range::lsr_end, lu_seq_range::lsr_flags, lu_seq_range::lsr_start, PRANGE, list_head::prev, and RETURN.
Referenced by fld_cache_insert(), and fld_index_create().
int fld_cache_lookup (struct fld_cache * cache, const u64 seq, struct lu_seq_range * range)
lookup seq sequence for range in fld cache.
Definition at line 528 of file fld_cache.c.
References ENTRY, fld_cache_entry::fce_range, fld_cache::fci_entries_head, fld_cache::fci_lock, fld_cache::fci_stat, fld_stats::fst_cache, fld_stats::fst_count, head, list_for_each_entry, lu_seq_range::lsr_start, lu_seq_range_within(), and RETURN.
Referenced by fid_is_local(), fld_client_lookup(), fld_index_lookup(), and fld_local_lookup().
int fld_client_rpc (struct obd_export * exp, struct lu_seq_range * range, __u32 fld_op, struct ptlrpc_request ** reqp)
Definition at line 358 of file fld_request.c.
References class_exp2cliimp(), obd_device::cli, ENTRY, EXIT, obd_export::exp_obd, FLD_LOOKUP, FLD_QUERY, FLD_READ, FLD_REQUEST_PORTAL, GOTO, obd_import::imp_connect_flags_orig, obd_import::imp_deactive, obd_import::imp_state, LASSERT, LUSTRE_IMP_CLOSED, LUSTRE_MDS_VERSION, MDC_REPLY_PORTAL, OBD_CONNECT_MDS_MDS, obd_get_request_slot(), obd_put_request_slot(), ptlrpc_at_set_req_timeout(), ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc_pack(), ptlrpc_request_set_replen(), RCL_SERVER, req_capsule_client_get(), req_capsule_server_get(), req_capsule_set_size(), RETURN, RMF_FLD_MDFLD, RMF_FLD_OPC, RMF_GENERIC_DATA, ptlrpc_request::rq_allow_replay, ptlrpc_request::rq_no_delay, ptlrpc_request::rq_pill, RQF_FLD_QUERY, RQF_FLD_READ, and obd_device::u.
Referenced by fld_client_lookup(), fld_server_lookup(), and fld_update_from_controller().
static const char* fld_target_name (const struct lu_fld_target * tar) [inline, static]
Definition at line 230 of file fld_internal.h.
References obd_export::exp_obd, lu_fld_target::ft_exp, lu_fld_target::ft_srv, lu_server_fld::lsf_name, and obd_device::obd_name.
Referenced by fld_client_add_target(), and fld_client_lookup().
Variable Documentation
struct lu_fld_hash fld_hash[]
Definition at line 119 of file fld_request.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.