Lustre: lustre/fld/fld_cache.c File Reference
lustre/fld/fld_cache.c File Reference
#include <libcfs/libcfs.h>
#include <linux/module.h>
#include <linux/math64.h>
#include <obd_support.h>
#include <lustre_fld.h>
#include "fld_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_FLD
Functions
struct fld_cache * fld_cache_init (const char *name, int cache_size, int cache_threshold)
create fld cache.
void fld_cache_fini (struct fld_cache *cache)
destroy fld cache.
void fld_cache_entry_delete (struct fld_cache *cache, struct fld_cache_entry *node)
delete given node from list.
static void fld_fix_new_list (struct fld_cache *cache)
fix list by checking new entry with NEXT entry in order.
static void fld_cache_entry_add (struct fld_cache *cache, struct fld_cache_entry *f_new, struct list_head *pos)
add node to fld cache
static int fld_cache_shrink (struct fld_cache *cache)
Check if cache needs to be shrunk.
void fld_cache_flush (struct fld_cache *cache)
kill all fld cache entries.
static void fld_cache_punch_hole (struct fld_cache *cache, struct fld_cache_entry *f_curr, struct fld_cache_entry *f_new)
punch hole in existing range.
static void fld_cache_overlap_handle (struct fld_cache *cache, struct fld_cache_entry *f_curr, struct fld_cache_entry *f_new)
handle range overlap in fld cache.
struct fld_cache_entry * fld_cache_entry_create (const struct lu_seq_range *range)
int fld_cache_insert_nolock (struct fld_cache *cache, struct fld_cache_entry *f_new)
Insert FLD entry in FLD cache.
int fld_cache_insert (struct fld_cache *cache, const struct lu_seq_range *range)
void fld_cache_delete_nolock (struct fld_cache *cache, const struct lu_seq_range *range)
void fld_cache_delete (struct fld_cache *cache, const struct lu_seq_range *range)
Delete FLD entry in FLD cache.
struct fld_cache_entry * fld_cache_entry_lookup_nolock (struct fld_cache *cache, const struct lu_seq_range *range)
struct fld_cache_entry * fld_cache_entry_lookup (struct fld_cache *cache, const struct lu_seq_range *range)
lookup seq sequence for range in fld cache.
int fld_cache_lookup (struct fld_cache *cache, const u64 seq, struct lu_seq_range *range)
lookup seq sequence for range in fld cache.
Define Documentation
#define DEBUG_SUBSYSTEM S_FLD
Definition at line 44 of file fld_cache.c.
Function Documentation
void fld_cache_delete (struct fld_cache * cache, const struct lu_seq_range * range)
Delete FLD entry in FLD cache.
Definition at line 479 of file fld_cache.c.
References fld_cache::fci_lock, and fld_cache_delete_nolock().
void fld_cache_delete_nolock (struct fld_cache * cache, const struct lu_seq_range * range)
Definition at line 456 of file fld_cache.c.
References fld_cache_entry::fce_range, fld_cache::fci_entries_head, fld_cache_entry_delete(), head, list_for_each_entry_safe, lu_seq_range::lsr_end, lu_seq_range::lsr_flags, and lu_seq_range::lsr_start.
Referenced by fld_cache_delete(), and fld_index_create().
static void fld_cache_entry_add (struct fld_cache * cache, struct fld_cache_entry * f_new, struct list_head * pos) [inline, static]
add node to fld cache
Definition at line 200 of file fld_cache.c.
References fld_cache_entry::fce_list, fld_cache_entry::fce_lru, fld_cache::fci_cache_count, fld_cache::fci_lru, fld_fix_new_list(), and list_add().
Referenced by fld_cache_insert_nolock(), fld_cache_overlap_handle(), and fld_cache_punch_hole().
struct fld_cache_entry* fld_cache_entry_create (const struct lu_seq_range * range) [read]
Definition at line 368 of file fld_cache.c.
References fld_cache_entry::fce_range, LASSERT, lu_seq_range_is_sane(), OBD_ALLOC_PTR, and RETURN.
Referenced by fld_cache_insert(), and fld_index_create().
void fld_cache_entry_delete (struct fld_cache * cache, struct fld_cache_entry * node)
delete given node from list.
Definition at line 121 of file fld_cache.c.
References fld_cache_entry::fce_list, fld_cache_entry::fce_lru, fld_cache::fci_cache_count, list_del(), and OBD_FREE_PTR.
Referenced by fld_cache_delete_nolock(), fld_cache_shrink(), and fld_fix_new_list().
struct fld_cache_entry* fld_cache_entry_lookup (struct fld_cache * cache, const struct lu_seq_range * range) [read]
lookup seq sequence for range in fld cache.
Definition at line 512 of file fld_cache.c.
References ENTRY, fld_cache::fci_lock, fld_cache_entry_lookup_nolock(), and RETURN.
struct fld_cache_entry* fld_cache_entry_lookup_nolock (struct fld_cache * cache, const struct lu_seq_range * range) [read]
Definition at line 488 of file fld_cache.c.
References fld_cache_entry::fce_range, fld_cache::fci_entries_head, head, list_for_each_entry, lu_seq_range::lsr_end, lu_seq_range::lsr_flags, lu_seq_range::lsr_start, and RETURN.
Referenced by fld_cache_entry_lookup().
void fld_cache_fini (struct fld_cache * cache)
destroy fld cache.
Definition at line 93 of file fld_cache.c.
References __u64, CDEBUG, D_INFO, ENTRY, EXIT, fld_cache::fci_name, fld_cache::fci_stat, fld_cache_flush(), fld_stats::fst_cache, fld_stats::fst_count, LASSERT, LPU64, OBD_FREE_PTR, and pct.
Referenced by fld_client_fini(), fld_server_fini(), and fld_server_init().
void fld_cache_flush (struct fld_cache * cache)
kill all fld cache entries.
Definition at line 247 of file fld_cache.c.
References ENTRY, EXIT, fld_cache::fci_cache_size, fld_cache::fci_lock, and fld_cache_shrink().
Referenced by fld_cache_fini(), and fld_client_flush().
struct fld_cache* fld_cache_init (const char * name, int cache_size, int cache_threshold) [read]
create fld cache.
Definition at line 56 of file fld_cache.c.
References CDEBUG, D_INFO, ENTRY, fld_cache::fci_cache_count, fld_cache::fci_cache_size, fld_cache::fci_entries_head, fld_cache::fci_lock, fld_cache::fci_lru, fld_cache::fci_name, fld_cache::fci_stat, fld_cache::fci_threshold, INIT_LIST_HEAD, LASSERT, OBD_ALLOC_PTR, RETURN, and strlcpy().
Referenced by fld_client_init(), and fld_server_init().
int fld_cache_insert (struct fld_cache * cache, const struct lu_seq_range * range)
Definition at line 437 of file fld_cache.c.
References fld_cache::fci_lock, fld_cache_entry_create(), fld_cache_insert_nolock(), OBD_FREE_PTR, and RETURN.
Referenced by fld_client_lookup(), fld_index_init(), and fld_server_lookup().
int fld_cache_insert_nolock (struct fld_cache * cache, struct fld_cache_entry * f_new)
Insert FLD entry in FLD cache.
This function handles all cases of merging and breaking up of ranges.
Definition at line 388 of file fld_cache.c.
References CDEBUG, D_INFO, DRANGE, ENTRY, fld_cache_entry::fce_list, fld_cache_entry::fce_range, fld_cache::fci_entries_head, fld_cache::fci_no_shrink, fld_cache_entry_add(), fld_cache_overlap_handle(), fld_cache_shrink(), head, list_for_each_entry_safe, lu_seq_range::lsr_end, lu_seq_range::lsr_flags, lu_seq_range::lsr_start, PRANGE, list_head::prev, and RETURN.
Referenced by fld_cache_insert(), and fld_index_create().
int fld_cache_lookup (struct fld_cache * cache, const u64 seq, struct lu_seq_range * range)
lookup seq sequence for range in fld cache.
Definition at line 528 of file fld_cache.c.
References ENTRY, fld_cache_entry::fce_range, fld_cache::fci_entries_head, fld_cache::fci_lock, fld_cache::fci_stat, fld_stats::fst_cache, fld_stats::fst_count, head, list_for_each_entry, lu_seq_range::lsr_start, lu_seq_range_within(), and RETURN.
Referenced by fid_is_local(), fld_client_lookup(), fld_index_lookup(), and fld_local_lookup().
static void fld_cache_overlap_handle (struct fld_cache * cache, struct fld_cache_entry * f_curr, struct fld_cache_entry * f_new) [static]
handle range overlap in fld cache.
Definition at line 306 of file fld_cache.c.
References CERROR, DRANGE, fld_cache_entry::fce_list, fld_cache_entry::fce_range, fld_cache_entry_add(), fld_cache_punch_hole(), fld_fix_new_list(), LASSERT, lu_seq_range::lsr_end, lu_seq_range::lsr_index, lu_seq_range::lsr_start, max, OBD_FREE_PTR, PRANGE, and list_head::prev.
Referenced by fld_cache_insert_nolock().
static void fld_cache_punch_hole (struct fld_cache * cache, struct fld_cache_entry * f_curr, struct fld_cache_entry * f_new) [static]
punch hole in existing range.
divide this range and add new entry accordingly.
Definition at line 264 of file fld_cache.c.
References ENTRY, EXIT, fld_cache_entry::fce_list, fld_cache_entry::fce_range, fld_cache_entry_add(), lu_seq_range::lsr_end, lu_seq_range::lsr_index, lu_seq_range::lsr_start, OBD_ALLOC_GFP, and OBD_FREE_PTR.
Referenced by fld_cache_overlap_handle().
static int fld_cache_shrink (struct fld_cache * cache) [static]
Check if cache needs to be shrunk.
If so - do it. Remove one entry in list and so on until cache is shrunk enough.
Definition at line 215 of file fld_cache.c.
References CDEBUG, D_INFO, ENTRY, fld_cache::fci_cache_count, fld_cache::fci_cache_size, fld_cache::fci_lru, fld_cache::fci_name, fld_cache::fci_threshold, fld_cache_entry_delete(), LASSERT, list_entry, list_head::prev, and RETURN.
Referenced by fld_cache_flush(), and fld_cache_insert_nolock().
static void fld_fix_new_list (struct fld_cache * cache) [static]
fix list by checking new entry with NEXT entry in order.
Definition at line 133 of file fld_cache.c.
References DRANGE, ENTRY, EXIT, fld_cache_entry::fce_list, fld_cache_entry::fce_range, fld_cache::fci_entries_head, fld_cache_entry_delete(), head, LASSERT, LASSERTF, list_for_each_entry_safe, lu_seq_range::lsr_end, lu_seq_range::lsr_flags, lu_seq_range::lsr_index, lu_seq_range::lsr_start, lu_seq_range_is_sane(), max, and PRANGE.
Referenced by fld_cache_entry_add(), and fld_cache_overlap_handle().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.