Lustre: lustre/fld/fld_request.c File Reference
lustre/fld/fld_request.c File Reference
#include <libcfs/libcfs.h>
#include <linux/module.h>
#include <linux/math64.h>
#include <obd.h>
#include <obd_class.h>
#include <obd_support.h>
#include <lprocfs_status.h>
#include <lustre_req_layout.h>
#include <lustre_fld.h>
#include <lustre_mdc.h>
#include "fld_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_FLD
Functions
static int fld_rrb_hash (struct lu_client_fld *fld, u64 seq)
static struct lu_fld_target * fld_rrb_scan (struct lu_client_fld *fld, u64 seq)
static struct lu_fld_target * fld_client_get_target (struct lu_client_fld *fld, u64 seq)
int fld_client_add_target (struct lu_client_fld *fld, struct lu_fld_target *tar)
int fld_client_del_target (struct lu_client_fld *fld, __u64 idx)
static int fld_client_proc_init (struct lu_client_fld *fld)
void fld_client_proc_fini (struct lu_client_fld *fld)
static int hash_is_sane (int hash)
int fld_client_init (struct lu_client_fld *fld, const char *prefix, int hash)
void fld_client_fini (struct lu_client_fld *fld)
int fld_client_rpc (struct obd_export *exp, struct lu_seq_range *range, __u32 fld_op, struct ptlrpc_request **reqp)
int fld_client_lookup (struct lu_client_fld *fld, u64 seq, u32 *mds, __u32 flags, const struct lu_env *env)
void fld_client_flush (struct lu_client_fld *fld)
static int __init fld_init (void)
static void __exit fld_exit (void)
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre FID Location Database")
MODULE_VERSION (LUSTRE_VERSION_STRING)
MODULE_LICENSE ("GPL")
module_init (fld_init)
module_exit (fld_exit)
Variables
struct lu_fld_hash fld_hash []
struct proc_dir_entry * fld_type_proc_dir
Define Documentation
#define DEBUG_SUBSYSTEM S_FLD
Definition at line 43 of file fld_request.c.
Function Documentation
static struct lu_fld_target* fld_client_get_target (struct lu_client_fld * fld, u64 seq) [static, read]
Definition at line 131 of file fld_request.c.
References CDEBUG, D_INFO, ENTRY, lu_fld_hash::fh_scan_func, lu_fld_target::ft_idx, LASSERT, lu_client_fld::lcf_hash, lu_client_fld::lcf_lock, lu_client_fld::lcf_name, LPU64, LPX64, and RETURN.
Referenced by fld_client_lookup().
static int fld_client_proc_init (struct lu_client_fld * fld) [static]
Definition at line 264 of file fld_request.c.
Referenced by fld_client_init().
int fld_client_rpc (struct obd_export * exp, struct lu_seq_range * range, __u32 fld_op, struct ptlrpc_request ** reqp)
Definition at line 358 of file fld_request.c.
References class_exp2cliimp(), obd_device::cli, ENTRY, EXIT, obd_export::exp_obd, FLD_LOOKUP, FLD_QUERY, FLD_READ, FLD_REQUEST_PORTAL, GOTO, obd_import::imp_connect_flags_orig, obd_import::imp_deactive, obd_import::imp_state, LASSERT, LUSTRE_IMP_CLOSED, LUSTRE_MDS_VERSION, MDC_REPLY_PORTAL, OBD_CONNECT_MDS_MDS, obd_get_request_slot(), obd_put_request_slot(), ptlrpc_at_set_req_timeout(), ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc_pack(), ptlrpc_request_set_replen(), RCL_SERVER, req_capsule_client_get(), req_capsule_server_get(), req_capsule_set_size(), RETURN, RMF_FLD_MDFLD, RMF_FLD_OPC, RMF_GENERIC_DATA, ptlrpc_request::rq_allow_replay, ptlrpc_request::rq_no_delay, ptlrpc_request::rq_pill, RQF_FLD_QUERY, RQF_FLD_READ, and obd_device::u.
Referenced by fld_client_lookup(), fld_server_lookup(), and fld_update_from_controller().
static void __exit fld_exit (void) [static]
Definition at line 555 of file fld_request.c.
References fld_server_mod_exit(), and lprocfs_remove().
static int __init fld_init (void) [static]
Definition at line 540 of file fld_request.c.
References fld_server_mod_init(), lprocfs_register(), LUSTRE_FLD_NAME, and proc_lustre_root.
static int fld_rrb_hash (struct lu_client_fld * fld, u64 seq) [static]
Definition at line 58 of file fld_request.c.
References LASSERT, and lu_client_fld::lcf_count.
Referenced by fld_rrb_scan().
static struct lu_fld_target* fld_rrb_scan (struct lu_client_fld * fld, u64 seq) [static, read]
Definition at line 65 of file fld_request.c.
References CERROR, ENTRY, obd_export::exp_obd, fid_seq_is_norm(), fld_rrb_hash(), lu_fld_target::ft_chain, lu_fld_target::ft_exp, lu_fld_target::ft_idx, lu_fld_target::ft_srv, LBUG, lu_client_fld::lcf_count, lu_client_fld::lcf_name, lu_client_fld::lcf_targets, list_for_each_entry, LPU64, LPX64, lu_server_fld::lsf_name, obd_device::obd_uuid, RETURN, and obd_uuid::uuid.
static int hash_is_sane (int hash) [inline, static]
Definition at line 277 of file fld_request.c.
References ARRAY_SIZE.
Referenced by fld_client_init().
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre FID Location Database")
module_exit (fld_exit)
module_init (fld_init)
MODULE_LICENSE ("GPL")
MODULE_VERSION (LUSTRE_VERSION_STRING)
Variable Documentation
struct lu_fld_hash fld_hash[]
Initial value:
 {
        {
                .fh_name = "RRB",
                .fh_hash_func = fld_rrb_hash,
                .fh_scan_func = fld_rrb_scan
        },
        {
                NULL,
        }
}
Definition at line 119 of file fld_request.c.
struct proc_dir_entry* fld_type_proc_dir
Definition at line 538 of file fld_request.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.