Lustre: lustre/fld/fld_index.c File Reference
lustre/fld/fld_index.c File Reference
#include <libcfs/libcfs.h>
#include <linux/module.h>
#include <obd_support.h>
#include <dt_object.h>
#include <lustre_fid.h>
#include <lustre_fld.h>
#include "fld_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_FLD
Functions
int fld_declare_index_create (const struct lu_env *env, struct lu_server_fld *fld, const struct lu_seq_range *new_range, struct thandle *th)
int fld_index_create (const struct lu_env *env, struct lu_server_fld *fld, const struct lu_seq_range *new_range, struct thandle *th)
insert range in fld store.
int fld_index_lookup (const struct lu_env *env, struct lu_server_fld *fld, u64 seq, struct lu_seq_range *range)
lookup range for a seq passed.
int fld_insert_entry (const struct lu_env *env, struct lu_server_fld *fld, const struct lu_seq_range *range)
insert entry in fld store.
static int fld_insert_special_entries (const struct lu_env *env, struct lu_server_fld *fld)
int fld_index_init (const struct lu_env *env, struct lu_server_fld *fld, struct dt_device *dt, int type)
void fld_index_fini (const struct lu_env *env, struct lu_server_fld *fld)
int fld_server_read (const struct lu_env *env, struct lu_server_fld *fld, struct lu_seq_range *range, void *data, int data_len)
Variables
static const char fld_index_name [] = "fld"
static struct lu_seq_range IGIF_FLD_RANGE
static struct lu_seq_range DOT_LUSTRE_FLD_RANGE
static struct lu_seq_range ROOT_FLD_RANGE
static struct dt_index_features fld_index_features
struct lu_context_key fld_thread_key
Define Documentation
#define DEBUG_SUBSYSTEM S_FLD
Definition at line 42 of file fld_index.c.
Function Documentation
int fld_declare_index_create (const struct lu_env * env, struct lu_server_fld * fld, const struct lu_seq_range * new_range, struct thandle * th)
Definition at line 86 of file fld_index.c.
References CERROR, DRANGE, dt_declare_delete(), dt_declare_insert(), dt_key, ENTRY, fld_index_lookup(), fld_thread_key, GOTO, LASSERT, lu_env::le_ctx, lu_server_fld::lsf_name, lu_server_fld::lsf_obj, lu_seq_range::lsr_end, lu_seq_range::lsr_start, lu_context_key_get(), lu_seq_range_compare_loc(), PRANGE, range_cpu_to_be(), and RETURN.
Referenced by fld_declare_server_create(), and fld_insert_entry().
int fld_index_create (const struct lu_env * env, struct lu_server_fld * fld, const struct lu_seq_range * new_range, struct thandle * th)
insert range in fld store.
Parameters:
range range to be inserted
th transaction for this operation as it could compound transaction.
Return values:
0 success
-ve error
The whole fld index insertion is protected by seq->lss_mutex (see seq_server_alloc_super), i.e. only one thread will access fldb each time, so we do not need worry the fld file and cache will being changed between declare and create. Because the fld entry can only be increamental, so we will only check whether it can be merged from the left.
Caller must hold fld->lsf_lock
Definition at line 160 of file fld_index.c.
References CERROR, DRANGE, dt_delete(), dt_insert(), dt_key, ENTRY, fld_cache::fci_lock, fld_cache_delete_nolock(), fld_cache_entry_create(), fld_cache_insert_nolock(), fld_index_lookup(), fld_thread_key, GOTO, LASSERT, lu_env::le_ctx, lu_server_fld::lsf_cache, lu_server_fld::lsf_lock, lu_server_fld::lsf_name, lu_server_fld::lsf_obj, lu_seq_range::lsr_end, lu_seq_range::lsr_start, lu_context_key_get(), lu_seq_range_compare_loc(), OBD_FREE_PTR, PRANGE, range_cpu_to_be(), and RETURN.
Referenced by fld_insert_entry(), and fld_server_create().
void fld_index_fini (const struct lu_env * env, struct lu_server_fld * fld)
Definition at line 446 of file fld_index.c.
References dt_object::do_lu, ENTRY, EXIT, lu_server_fld::lsf_obj, and lu_object_put().
Referenced by fld_server_fini(), and fld_server_init().
int fld_index_init (const struct lu_env * env, struct lu_server_fld * fld, struct dt_device * dt, int type)
Definition at line 326 of file fld_index.c.
References CERROR, DFT_INDEX, dt_index_operations::dio_it, dt_object::do_index_ops, dt_object_operations::do_index_try, dt_object::do_lu, dt_object::do_ops, dt_object_format::dof_idx, dt_object_format::dof_type, dt_find_or_create(), dt_locate(), dt_object_exists(), ENTRY, fld_cache_insert(), fld_index_name, FLD_INDEX_OID, fld_insert_special_entries(), fld_name_to_index(), fld_thread_key, GOTO, dt_index_operations::dt_it_ops::init, lu_attr::la_mode, LA_MODE, lu_attr::la_valid, LASSERT, lu_env::le_ctx, lu_server_fld::lsf_cache, lu_server_fld::lsf_lock, lu_server_fld::lsf_name, lu_server_fld::lsf_new, lu_server_fld::lsf_obj, lu_context_key_get(), lu_local_obj_fid(), lu_object_put(), LU_SEQ_RANGE_MDT, OBD_ALLOC_PTR, OBD_FREE_PTR, range_be_to_cpu(), RETURN, and dt_object_format::u.
Referenced by fld_server_init().
int fld_index_lookup (const struct lu_env * env, struct lu_server_fld * fld, u64 seq, struct lu_seq_range * range)
lookup range for a seq passed.
note here we only care about the start/end, caller should handle the attached location data (flags, index).
Parameters:
seq seq for lookup.
range result of lookup.
Return values:
0 found, range is the matched range;
-ENOENT not found, range is the left-side range;
-ve other error;
Definition at line 233 of file fld_index.c.
References CDEBUG, D_INFO, DRANGE, ENTRY, fld_cache_lookup(), fld_thread_key, lu_env::le_ctx, LPX64, lu_server_fld::lsf_cache, lu_server_fld::lsf_name, lu_context_key_get(), lu_seq_range_within(), PRANGE, and RETURN.
Referenced by fld_declare_index_create(), and fld_index_create().
static int fld_insert_special_entries (const struct lu_env * env, struct lu_server_fld * fld) [static]
Definition at line 308 of file fld_index.c.
References fld_insert_entry(), and RETURN.
Referenced by fld_index_init().
int fld_server_read (const struct lu_env * env, struct lu_server_fld * fld, struct lu_seq_range * range, void * data, int data_len)
Definition at line 457 of file fld_index.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, ENTRY, fld_thread_key, GOTO, dt_index_operations::dt_it_ops::init, LASSERT, lu_env::le_ctx, lu_server_fld::lsf_obj, lu_seq_range::lsr_end, lu_seq_range::lsr_flags, lu_seq_range::lsr_index, lu_seq_range::lsr_start, lu_seq_range_array::lsra_count, lu_seq_range_array::lsra_lsr, lu_context_key_get(), offsetof, range_array_cpu_to_le(), range_be_to_cpu(), and RETURN.
Referenced by fld_handle_read().
Variable Documentation
struct lu_seq_range DOT_LUSTRE_FLD_RANGE [static]
Initial value:
 {
        .lsr_start = FID_SEQ_DOT_LUSTRE,
        .lsr_end   = FID_SEQ_DOT_LUSTRE + 1,
        .lsr_index = 0,
        .lsr_flags = LU_SEQ_RANGE_MDT
}
Definition at line 61 of file fld_index.c.
struct dt_index_features fld_index_features [static]
Initial value:
 {
        .dif_flags       = DT_IND_UPDATE,
        .dif_keysize_min = sizeof(u64),
        .dif_keysize_max = sizeof(u64),
        .dif_recsize_min = sizeof(struct lu_seq_range),
        .dif_recsize_max = sizeof(struct lu_seq_range),
        .dif_ptrsize     = 4
}
Definition at line 75 of file fld_index.c.
const char fld_index_name[] = "fld" [static]
Definition at line 52 of file fld_index.c.
Referenced by fld_index_init().
struct lu_context_key fld_thread_key
Referenced by fid_is_local(), fld_declare_index_create(), fld_index_create(), fld_index_init(), fld_index_lookup(), fld_local_lookup(), fld_server_mod_exit(), fld_server_mod_init(), fld_server_read(), and fld_update_from_controller().
struct lu_seq_range IGIF_FLD_RANGE [static]
Initial value:
 {
        .lsr_start = FID_SEQ_IGIF,
        .lsr_end   = FID_SEQ_IGIF_MAX + 1,
        .lsr_index = 0,
        .lsr_flags = LU_SEQ_RANGE_MDT
}
Definition at line 54 of file fld_index.c.
struct lu_seq_range ROOT_FLD_RANGE [static]
Initial value:
 {
        .lsr_start = FID_SEQ_ROOT,
        .lsr_end   = FID_SEQ_ROOT + 1,
        .lsr_index = 0,
        .lsr_flags = LU_SEQ_RANGE_MDT
}
Definition at line 68 of file fld_index.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.