Lustre: lustre/tests/flocks_test.c File Reference
lustre/tests/flocks_test.c File Reference
#include <errno.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <pthread.h>
#include <sys/file.h>
#include <sys/wait.h>
#include <stdarg.h>
Data Structures
struct th_data
=============================================================== test number 2
Defines
#define MAX_PATH_LENGTH 4096
#define T5_USAGE
Functions
int t_fcntl (int fd, int cmd,...)
helper functions
int t_unlink (const char *path)
void t1_usage (void)
================================================================= test number 1
int t1 (int argc, char *argv[])
void * t2_thread1 (void *arg)
void * t2_thread2 (void *arg)
int t2 (int argc, char *argv[])
int t3 (int argc, char *argv[])
================================================================= test number 3
int t4 (int argc, char *argv[])
int t5 (int argc, char *argv[])
void usage (void)
============================================================== program entry
int main (int argc, char *argv[])
Define Documentation
#define MAX_PATH_LENGTH 4096
Definition at line 48 of file flocks_test.c.
#define T5_USAGE
Value:
"Usage: ./flocks_test 5 set|get|unlock [read|write] [sleep N] file1\n"\
"       set: F_SETLKW F_WRLCK\n"                                              \
"       get: F_GETLK F_WRLCK  (conflict)\n"                                   \
"       unlock: F_SETLKW F_UNLCK\n"                                           \
"       read|write: lock mode, write by default\n"                            \
"       sleep N: sleep for N secs after fcntl\n"                              \
"       file1: fcntl is called for this file\n"
Definition at line 484 of file flocks_test.c.
Referenced by t5().
Function Documentation
int main (int argc, char * argv[])
Definition at line 576 of file flocks_test.c.
References t1(), t2, t3(), t4(), t5(), and usage.
int t1 (int argc, char * argv[])
Definition at line 134 of file flocks_test.c.
References error, and t1_usage().
Referenced by begin(), end(), and main().
void t1_usage (void)
================================================================= test number 1
normal flock test
Definition at line 129 of file flocks_test.c.
Referenced by t1().
int t2 (int argc, char * argv[])
Definition at line 235 of file flocks_test.c.
References th_data::fd, th_data::lock, MAX_PATH_LENGTH, t2_thread1(), t2_thread2(), t_fcntl(), and t_unlink().
void* t2_thread1 (void * arg)
Definition at line 200 of file flocks_test.c.
References t_fcntl().
Referenced by t2().
void* t2_thread2 (void * arg)
Definition at line 217 of file flocks_test.c.
References t_fcntl().
Referenced by t2().
int t3 (int argc, char * argv[])
================================================================= test number 3
Bug 24040: Two conflicting flocks from same process different fds should fail two conflicting flocks from different processes but same fs should succeed.
Definition at line 291 of file flocks_test.c.
Referenced by main().
int t4 (int argc, char * argv[])
Definition at line 364 of file flocks_test.c.
References child_status(), and t_fcntl().
Referenced by main().
int t5 (int argc, char * argv[])
Definition at line 493 of file flocks_test.c.
References T5_USAGE, and t_fcntl().
Referenced by main().
int t_fcntl (int fd, int cmd, ...)
helper functions
Definition at line 52 of file flocks_test.c.
int t_unlink (const char * path)
Definition at line 114 of file flocks_test.c.
void usage (void)
============================================================== program entry
Definition at line 571 of file flocks_test.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.