Lustre: lustre/tests/flock_deadlock.c File Reference
lustre/tests/flock_deadlock.c File Reference
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/file.h>
#include <unistd.h>
#include <fcntl.h>
#include <string.h>
#include <errno.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <sys/sem.h>
#include <semaphore.h>
#include <sys/mman.h>
#include <sys/stat.h>
Defines
#define LOCK_LEN 100
#define flock_call(fd, num, get, label)
Enumerations
enum { FLOCK_GET = 0, FLOCK_PUT = 1 }
Functions
void catch_alarm ()
int main (int argc, char *argv[])
Variables
struct flock flocks [4]
Define Documentation
#define flock_call (fd, num, get, label)
Value:
flocks[num].l_type = get == FLOCK_GET ? F_WRLCK : F_UNLCK;              \
        printf("%d: %s lock%d [%llu, %llu]\n", pid,                             \
                get == FLOCK_GET ? "taking" : "putting",                        \
                num, (unsigned long long)flocks[num].l_start,                   \
                (unsigned long long)flocks[num].l_start + flocks[num].l_len);   \
        rc = fcntl(fd, F_SETLKW, &flocks[num]);                                 \
        if (rc < 0) {                                                           \
                rc = errno;                                                     \
                fprintf(stderr, "%d: failed to %s lock%d, %s\n",                \
                        pid, get == FLOCK_GET ? "take" : "put",                 \
                        num, strerror(errno));                                  \
                goto label;                                                     \
        } else {                                                                \
                printf("%d: done\n", pid);                                      \
        }
Definition at line 88 of file flock_deadlock.c.
Referenced by main().
#define LOCK_LEN 100
Definition at line 46 of file flock_deadlock.c.
Enumeration Type Documentation
anonymous enum
Enumerator:
FLOCK_GET
FLOCK_PUT
Definition at line 83 of file flock_deadlock.c.
Function Documentation
void catch_alarm ()
Definition at line 105 of file flock_deadlock.c.
Referenced by catch_alarm(), and main().
int main (int argc, char * argv[])
Definition at line 111 of file flock_deadlock.c.
References catch_alarm(), flock_call, FLOCK_GET, FLOCK_PUT, flocks, and status.
Variable Documentation
struct flock flocks[4]
Definition at line 48 of file flock_deadlock.c.
Referenced by main().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.