Lustre: lnet/selftest/framework.c File Reference
lnet/selftest/framework.c File Reference
#include "selftest.h"
Data Structures
struct smoketest_framework
Defines
#define DEBUG_SUBSYSTEM S_LNET
#define sfw_unpack_id(id)
#define sfw_unpack_sid(sid)
#define sfw_unpack_fw_counters(fc)
#define sfw_unpack_rpc_counters(rc)
#define sfw_unpack_lnet_counters(lc)
#define sfw_test_active(t) (atomic_read(&(t)->tsi_nactive) != 0)
#define sfw_batch_active(b) (atomic_read(&(b)->bat_nactive) != 0)
Functions
module_param (session_timeout, int, 0444)
MODULE_PARM_DESC (session_timeout,"test session timeout in seconds (100 by default, 0 == never)")
module_param (rpc_timeout, int, 0644)
MODULE_PARM_DESC (rpc_timeout,"rpc timeout in seconds (64 by default, 0 == never)")
int sfw_stop_batch (sfw_batch_t *tsb, int force)
void sfw_destroy_session (sfw_session_t *sn)
static sfw_test_case_t * sfw_find_test_case (int id)
static int sfw_register_test (srpc_service_t *service, sfw_test_client_ops_t *cliops)
static void sfw_add_session_timer (void)
static int sfw_del_session_timer (void)
static void sfw_deactivate_session (void)
static void sfw_session_expired (void *data)
static void sfw_init_session (sfw_session_t *sn, lst_sid_t sid, unsigned features, const char *name)
static void sfw_server_rpc_done (struct srpc_server_rpc *rpc)
static void sfw_client_rpc_fini (srpc_client_rpc_t *rpc)
static sfw_batch_t * sfw_find_batch (lst_bid_t bid)
static sfw_batch_t * sfw_bid2batch (lst_bid_t bid)
static int sfw_get_stats (srpc_stat_reqst_t *request, srpc_stat_reply_t *reply)
int sfw_make_session (srpc_mksn_reqst_t *request, srpc_mksn_reply_t *reply)
static int sfw_remove_session (srpc_rmsn_reqst_t *request, srpc_rmsn_reply_t *reply)
static int sfw_debug_session (srpc_debug_reqst_t *request, srpc_debug_reply_t *reply)
static void sfw_test_rpc_fini (srpc_client_rpc_t *rpc)
static int sfw_test_buffers (sfw_test_instance_t *tsi)
static int sfw_load_test (struct sfw_test_instance *tsi)
static void sfw_unload_test (struct sfw_test_instance *tsi)
static void sfw_destroy_test_instance (sfw_test_instance_t *tsi)
static void sfw_destroy_batch (sfw_batch_t *tsb)
static void sfw_unpack_addtest_req (srpc_msg_t *msg)
static int sfw_add_test_instance (sfw_batch_t *tsb, srpc_server_rpc_t *rpc)
static void sfw_test_unit_done (sfw_test_unit_t *tsu)
static void sfw_test_rpc_done (srpc_client_rpc_t *rpc)
int sfw_create_test_rpc (sfw_test_unit_t *tsu, lnet_process_id_t peer, unsigned features, int nblk, int blklen, srpc_client_rpc_t **rpcpp)
static int sfw_run_test (swi_workitem_t *wi)
static int sfw_run_batch (sfw_batch_t *tsb)
static int sfw_query_batch (sfw_batch_t *tsb, int testidx, srpc_batch_reply_t *reply)
void sfw_free_pages (srpc_server_rpc_t *rpc)
int sfw_alloc_pages (struct srpc_server_rpc *rpc, int cpt, int npages, int len, int sink)
static int sfw_add_test (srpc_server_rpc_t *rpc)
static int sfw_control_batch (srpc_batch_reqst_t *request, srpc_batch_reply_t *reply)
static int sfw_handle_server_rpc (struct srpc_server_rpc *rpc)
static int sfw_bulk_ready (struct srpc_server_rpc *rpc, int status)
srpc_client_rpc_t * sfw_create_rpc (lnet_process_id_t peer, int service, unsigned features, int nbulkiov, int bulklen, void(*done)(srpc_client_rpc_t *), void *priv)
void sfw_unpack_message (srpc_msg_t *msg)
void sfw_abort_rpc (srpc_client_rpc_t *rpc)
void sfw_post_rpc (srpc_client_rpc_t *rpc)
int sfw_startup (void)
void sfw_shutdown (void)
Variables
lst_sid_t LST_INVALID_SID = {LNET_NID_ANY, -1}
static int session_timeout = 100
static int rpc_timeout = 64
static struct smoketest_framework sfw_data
static srpc_service_t sfw_services []
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 42 of file framework.c.
#define sfw_batch_active (b) (atomic_read(&(b)->bat_nactive) != 0)
Definition at line 104 of file framework.c.
Referenced by sfw_add_test(), sfw_add_test_instance(), sfw_deactivate_session(), sfw_destroy_batch(), sfw_run_batch(), sfw_stop_batch(), and sfw_test_unit_done().
#define sfw_test_active (t) (atomic_read(&(t)->tsi_nactive) != 0)
Definition at line 103 of file framework.c.
Referenced by sfw_create_test_rpc(), sfw_destroy_test_instance(), sfw_run_batch(), sfw_stop_batch(), sfw_test_rpc_done(), and sfw_test_unit_done().
#define sfw_unpack_fw_counters (fc)
Value:
do {                                      \
        __swab32s(&(fc).running_ms);      \
        __swab32s(&(fc).active_batches);  \
        __swab32s(&(fc).zombie_sessions); \
        __swab32s(&(fc).brw_errors);      \
        __swab32s(&(fc).ping_errors);     \
} while (0)
Definition at line 68 of file framework.c.
Referenced by sfw_unpack_message().
#define sfw_unpack_id (id)
Value:
do {                                    \
        __swab64s(&(id).nid);           \
        __swab32s(&(id).pid);           \
} while (0)
Definition at line 56 of file framework.c.
Referenced by sfw_add_test_instance().
#define sfw_unpack_lnet_counters (lc)
Value:
do {                                    \
        __swab32s(&(lc).errors);        \
        __swab32s(&(lc).msgs_max);      \
        __swab32s(&(lc).msgs_alloc);    \
        __swab32s(&(lc).send_count);    \
        __swab32s(&(lc).recv_count);    \
        __swab32s(&(lc).drop_count);    \
        __swab32s(&(lc).route_count);   \
        __swab64s(&(lc).send_length);   \
        __swab64s(&(lc).recv_length);   \
        __swab64s(&(lc).drop_length);   \
        __swab64s(&(lc).route_length);  \
} while (0)
Definition at line 88 of file framework.c.
Referenced by sfw_unpack_message().
#define sfw_unpack_rpc_counters (rc)
Value:
do {                                    \
        __swab32s(&(rc).errors);        \
        __swab32s(&(rc).rpcs_sent);     \
        __swab32s(&(rc).rpcs_rcvd);     \
        __swab32s(&(rc).rpcs_dropped);  \
        __swab32s(&(rc).rpcs_expired);  \
        __swab64s(&(rc).bulk_get);      \
        __swab64s(&(rc).bulk_put);      \
} while (0)
Definition at line 77 of file framework.c.
Referenced by sfw_unpack_message().
#define sfw_unpack_sid (sid)
Value:
do {                                    \
        __swab64s(&(sid).ses_nid);      \
        __swab64s(&(sid).ses_stamp);    \
} while (0)
Definition at line 62 of file framework.c.
Referenced by sfw_unpack_message().
Function Documentation
module_param (rpc_timeout , int , 0644)
module_param (session_timeout , int , 0444)
MODULE_PARM_DESC (rpc_timeout , "rpc timeout in seconds (64 by default, 0 == never)")
MODULE_PARM_DESC (session_timeout , "test session timeout in seconds (100 by default, 0 == never)")
void sfw_abort_rpc (srpc_client_rpc_t * rpc)
Definition at line 1582 of file framework.c.
References srpc_client_rpc::crpc_lock, srpc_client_rpc::crpc_refcount, srpc_client_rpc::crpc_service, LASSERT, srpc_abort_rpc(), and SRPC_FRAMEWORK_SERVICE_MAX_ID.
Referenced by lstcon_rpc_trans_abort().
static void sfw_add_session_timer (void) [static]
Definition at line 168 of file framework.c.
References cfs_time_add(), cfs_time_current_sec(), smoketest_framework::fw_session, smoketest_framework::fw_shuttingdown, LASSERT, sfw_data, sfw_session_t::sn_timeout, sfw_session_t::sn_timer, sfw_session_t::sn_timer_active, stt_add_timer(), and stt_timer_t::stt_expires.
Referenced by sfw_bulk_ready(), and sfw_handle_server_rpc().
static int sfw_add_test (srpc_server_rpc_t * rpc) [static]
Definition at line 1136 of file framework.c.
References srpc_buffer::buf_msg, CDEBUG, CERROR, CFS_CPT_ANY, D_NET, D_WARNING, smoketest_framework::fw_session, libcfs_id2str(), LNET_NID_ANY, LST_FEAT_BULK_LEN, srpc_msg::msg_body, srpc_service_cd::scd_svc, sfw_add_test_instance(), sfw_alloc_pages(), sfw_batch_active, sfw_bid2batch(), sfw_data, sfw_find_test_case(), sfw_id_pages, SFW_MAX_CONCUR, SFW_MAX_NDESTS, sfw_sid_equal, sfw_session_t::sn_features, sfw_session_t::sn_id, srpc_server_rpc::srpc_bulk, SRPC_FRAMEWORK_SERVICE_MAX_ID, srpc_server_rpc::srpc_peer, srpc_server_rpc::srpc_replymsg, srpc_server_rpc::srpc_reqstbuf, srpc_server_rpc::srpc_scd, SRPC_SERVICE_MAX_ID, srpc_service::sv_name, srpc_msg::tes_reply, and srpc_msg::tes_reqst.
Referenced by sfw_bulk_ready(), and sfw_handle_server_rpc().
static int sfw_add_test_instance (sfw_batch_t * tsb, srpc_server_rpc_t * rpc) [static]
Definition at line 747 of file framework.c.
References lst_bid_t::bat_id, sfw_batch_t::bat_id, sfw_batch_t::bat_tests, srpc_bulk_t::bk_iovs, srpc_bulk_t::bk_len, srpc_bulk_t::bk_niov, srpc_buffer::buf_msg, CERROR, error, INIT_LIST_HEAD, lnet_kiov_t::kiov_page, LASSERT, LIBCFS_ALLOC, LIBCFS_FREE, list_add_tail(), LPU64, msg, srpc_msg::msg_body, srpc_msg::msg_magic, lnet_process_id_t::nid, lnet_process_id_t::pid, sfw_batch_active, sfw_destroy_test_instance(), SFW_ID_PER_PAGE, sfw_load_test(), sfw_unpack_addtest_req(), sfw_unpack_id, srpc_server_rpc::srpc_bulk, SRPC_MSG_MAGIC, srpc_server_rpc::srpc_reqstbuf, srpc_msg::tes_reqst, sfw_test_instance::tsi_active_rpcs, sfw_test_instance::tsi_batch, sfw_test_instance::tsi_concur, sfw_test_instance::tsi_free_rpcs, sfw_test_instance::tsi_is_client, sfw_test_instance::tsi_list, sfw_test_instance::tsi_lock, sfw_test_instance::tsi_loop, sfw_test_instance::tsi_nactive, sfw_test_instance::tsi_ops, sfw_test_instance::tsi_service, sfw_test_instance::tsi_stopping, sfw_test_instance::tsi_stoptsu_onerr, sfw_test_instance::tsi_u, sfw_test_instance::tsi_units, sfw_test_client_ops_t::tso_init, sfw_test_unit::tsu_dest, sfw_test_unit::tsu_instance, sfw_test_unit::tsu_list, and sfw_test_unit::tsu_private.
Referenced by sfw_add_test().
int sfw_alloc_pages (struct srpc_server_rpc * rpc, int cpt, int npages, int len, int sink)
Definition at line 1122 of file framework.c.
References LASSERT, LNET_MAX_IOV, srpc_alloc_bulk(), and srpc_server_rpc::srpc_bulk.
Referenced by brw_server_handle(), and sfw_add_test().
static sfw_batch_t* sfw_bid2batch (lst_bid_t bid) [static]
Definition at line 353 of file framework.c.
References sfw_batch_t::bat_error, sfw_batch_t::bat_id, sfw_batch_t::bat_list, sfw_batch_t::bat_nactive, sfw_batch_t::bat_session, sfw_batch_t::bat_tests, smoketest_framework::fw_session, INIT_LIST_HEAD, LASSERT, LIBCFS_ALLOC, list_add_tail(), sfw_data, sfw_find_batch(), and sfw_session_t::sn_batches.
Referenced by sfw_add_test().
static int sfw_bulk_ready (struct srpc_server_rpc * rpc, int status) [static]
Definition at line 1353 of file framework.c.
References srpc_buffer::buf_msg, CERROR, smoketest_framework::fw_active_srpc, smoketest_framework::fw_lock, smoketest_framework::fw_shuttingdown, LASSERT, libcfs_id2str(), srpc_msg::msg_body, srpc_service_cd::scd_svc, sfw_add_session_timer(), sfw_add_test(), sfw_data, sfw_del_session_timer(), srpc_server_rpc::srpc_bulk, srpc_server_rpc::srpc_peer, srpc_server_rpc::srpc_reqstbuf, srpc_server_rpc::srpc_scd, SRPC_SERVICE_TEST, srpc_service::sv_id, srpc_service::sv_name, and srpc_msg::tes_reqst.
Referenced by sfw_startup().
static void sfw_client_rpc_fini (srpc_client_rpc_t * rpc) [static]
Definition at line 315 of file framework.c.
References srpc_bulk_t::bk_niov, CDEBUG, srpc_client_rpc::crpc_aborted, srpc_client_rpc::crpc_bulk, srpc_client_rpc::crpc_dest, srpc_client_rpc::crpc_list, srpc_client_rpc::crpc_refcount, srpc_client_rpc::crpc_service, srpc_client_rpc::crpc_status, srpc_client_rpc::crpc_wi, D_NET, smoketest_framework::fw_lock, smoketest_framework::fw_shuttingdown, smoketest_framework::fw_zombie_rpcs, LASSERT, libcfs_id2str(), list_add(), list_empty(), sfw_data, swi_workitem::swi_state, and swi_state2str().
Referenced by sfw_create_rpc().
static int sfw_control_batch (srpc_batch_reqst_t * request, srpc_batch_reply_t * reply) [static]
Definition at line 1206 of file framework.c.
References smoketest_framework::fw_session, sfw_data, sfw_find_batch(), sfw_query_batch(), sfw_run_batch(), sfw_sid_equal, sfw_stop_batch(), sfw_session_t::sn_id, SRPC_BATCH_OPC_QUERY, SRPC_BATCH_OPC_RUN, and SRPC_BATCH_OPC_STOP.
Referenced by sfw_handle_server_rpc().
srpc_client_rpc_t* sfw_create_rpc (lnet_process_id_t peer, int service, unsigned features, int nbulkiov, int bulklen, void(*)(srpc_client_rpc_t *) done, void * priv)
Definition at line 1401 of file framework.c.
References srpc_client_rpc::crpc_list, srpc_client_rpc::crpc_reqstmsg, done, smoketest_framework::fw_lock, smoketest_framework::fw_shuttingdown, smoketest_framework::fw_zombie_rpcs, LASSERT, list_del(), list_empty(), list_entry, srpc_msg::msg_ses_feats, list_head::next, sfw_client_rpc_fini(), sfw_data, srpc_create_client_rpc(), SRPC_FRAMEWORK_SERVICE_MAX_ID, and srpc_init_client_rpc().
Referenced by lstcon_rpc_init().
int sfw_create_test_rpc (sfw_test_unit_t * tsu, lnet_process_id_t peer, unsigned features, int nblk, int blklen, srpc_client_rpc_t ** rpcpp)
Definition at line 921 of file framework.c.
References srpc_bulk_t::bk_niov, CERROR, srpc_client_rpc::crpc_bulk, srpc_client_rpc::crpc_list, srpc_client_rpc::crpc_reqstmsg, LASSERT, list_del_init(), list_empty(), list_entry, srpc_msg::msg_ses_feats, list_head::next, sfw_test_active, sfw_test_rpc_done(), sfw_test_rpc_fini(), srpc_create_client_rpc(), srpc_init_client_rpc(), sfw_test_instance::tsi_free_rpcs, sfw_test_instance::tsi_lock, sfw_test_instance::tsi_service, and sfw_test_unit::tsu_instance.
Referenced by brw_client_prep_rpc(), and ping_client_prep_rpc().
static void sfw_deactivate_session (void) [static]
Definition at line 207 of file framework.c.
References smoketest_framework::fw_lock, smoketest_framework::fw_nzombies, smoketest_framework::fw_session, smoketest_framework::fw_tests, smoketest_framework::fw_zombie_sessions, LASSERT, list_add(), list_del_init(), list_for_each_entry, sfw_batch_active, sfw_data, sfw_destroy_session(), sfw_stop_batch(), sfw_session_t::sn_batches, sfw_session_t::sn_list, sfw_session_t::sn_timer_active, srpc_abort_service(), and sfw_test_case::tsc_srv_service.
Referenced by sfw_make_session(), sfw_remove_session(), sfw_session_expired(), and sfw_shutdown().
static int sfw_debug_session (srpc_debug_reqst_t * request, srpc_debug_reply_t * reply) [static]
Definition at line 523 of file framework.c.
References smoketest_framework::fw_session, sfw_data, sfw_session_t::sn_id, sfw_session_t::sn_name, sfw_session_t::sn_timeout, and strlcpy().
Referenced by sfw_handle_server_rpc().
static int sfw_del_session_timer (void) [static]
Definition at line 188 of file framework.c.
References smoketest_framework::fw_session, LASSERT, sfw_data, sfw_session_t::sn_timeout, sfw_session_t::sn_timer, sfw_session_t::sn_timer_active, and stt_del_timer().
Referenced by sfw_bulk_ready(), sfw_handle_server_rpc(), and sfw_shutdown().
static void sfw_destroy_batch (sfw_batch_t * tsb) [static]
Definition at line 663 of file framework.c.
References sfw_batch_t::bat_list, sfw_batch_t::bat_tests, LASSERT, LIBCFS_FREE, list_del_init(), list_empty(), list_entry, list_head::next, sfw_batch_active, sfw_destroy_test_instance(), and sfw_test_instance::tsi_list.
Referenced by sfw_destroy_session().
void sfw_destroy_session (sfw_session_t * sn)
Definition at line 682 of file framework.c.
References sfw_batch_t::bat_list, smoketest_framework::fw_nzombies, smoketest_framework::fw_session, LASSERT, LIBCFS_FREE, list_del_init(), list_empty(), list_entry, list_head::next, sfw_data, sfw_destroy_batch(), sfw_session_t::sn_batches, and sfw_session_t::sn_list.
Referenced by sfw_deactivate_session(), and sfw_test_unit_done().
static void sfw_destroy_test_instance (sfw_test_instance_t * tsi) [static]
Definition at line 629 of file framework.c.
References srpc_client_rpc::crpc_list, LASSERT, LIBCFS_FREE, list_del(), list_empty(), list_entry, list_head::next, sfw_test_active, sfw_unload_test(), srpc_client_rpc_size, sfw_test_instance::tsi_active_rpcs, sfw_test_instance::tsi_free_rpcs, sfw_test_instance::tsi_is_client, sfw_test_instance::tsi_ops, sfw_test_instance::tsi_stopping, sfw_test_instance::tsi_units, sfw_test_client_ops_t::tso_fini, and sfw_test_unit::tsu_list.
Referenced by sfw_add_test_instance(), and sfw_destroy_batch().
static sfw_batch_t* sfw_find_batch (lst_bid_t bid) [static]
Definition at line 337 of file framework.c.
References lst_bid_t::bat_id, sfw_batch_t::bat_id, smoketest_framework::fw_session, LASSERT, list_for_each_entry, sfw_data, and sfw_session_t::sn_batches.
Referenced by sfw_bid2batch(), and sfw_control_batch().
static sfw_test_case_t* sfw_find_test_case (int id) [inline, static]
Definition at line 130 of file framework.c.
References smoketest_framework::fw_tests, LASSERT, list_for_each_entry, sfw_data, SRPC_FRAMEWORK_SERVICE_MAX_ID, SRPC_SERVICE_MAX_ID, srpc_service::sv_id, and sfw_test_case::tsc_srv_service.
Referenced by sfw_add_test(), sfw_load_test(), sfw_register_test(), sfw_test_buffers(), and sfw_unload_test().
void sfw_free_pages (srpc_server_rpc_t * rpc)
Definition at line 1115 of file framework.c.
References srpc_server_rpc::srpc_bulk, and srpc_free_bulk().
Referenced by brw_server_rpc_done(), and sfw_server_rpc_done().
static int sfw_get_stats (srpc_stat_reqst_t * request, srpc_stat_reply_t * reply) [static]
Definition at line 379 of file framework.c.
References sfw_batch_t::bat_nactive, cfs_duration_usec(), cfs_time_current(), cfs_time_sub(), smoketest_framework::fw_nzombies, smoketest_framework::fw_session, list_for_each_entry, lnet_counters_get(), LNET_NID_ANY, sfw_data, sfw_sid_equal, sfw_session_t::sn_batches, sfw_session_t::sn_brw_errors, sfw_session_t::sn_id, sfw_session_t::sn_ping_errors, sfw_session_t::sn_started, and srpc_get_counters().
Referenced by sfw_handle_server_rpc().
static int sfw_handle_server_rpc (struct srpc_server_rpc * rpc) [static]
Definition at line 1247 of file framework.c.
References srpc_msg::bat_reply, srpc_msg::bat_reqst, srpc_buffer::buf_msg, CERROR, CNETERR, srpc_msg::dbg_reply, srpc_msg::dbg_reqst, smoketest_framework::fw_active_srpc, smoketest_framework::fw_lock, smoketest_framework::fw_session, smoketest_framework::fw_shuttingdown, LASSERT, LBUG, libcfs_id2str(), LST_FEATS_MASK, srpc_msg::mksn_reply, srpc_msg::mksn_reqst, srpc_msg::msg_body, srpc_msg::msg_ses_feats, srpc_msg::msg_type, srpc_msg::msg_version, srpc_msg::reply, srpc_msg::rmsn_reply, srpc_msg::rmsn_reqst, srpc_service_cd::scd_svc, sfw_add_session_timer(), sfw_add_test(), sfw_control_batch(), sfw_data, sfw_debug_session(), sfw_del_session_timer(), sfw_get_stats(), sfw_make_session(), sfw_remove_session(), sfw_server_rpc_done(), sfw_unpack_message(), sfw_session_t::sn_features, sfw_session_t::sn_id, srpc_server_rpc::srpc_done, SRPC_FRAMEWORK_SERVICE_MAX_ID, SRPC_MSG_VERSION, srpc_server_rpc::srpc_peer, srpc_server_rpc::srpc_replymsg, srpc_server_rpc::srpc_reqstbuf, srpc_server_rpc::srpc_scd, srpc_service2request(), SRPC_SERVICE_BATCH, SRPC_SERVICE_DEBUG, SRPC_SERVICE_MAKE_SESSION, SRPC_SERVICE_QUERY_STAT, SRPC_SERVICE_REMOVE_SESSION, SRPC_SERVICE_TEST, srpc_msg::stat_reply, srpc_msg::stat_reqst, srpc_service::sv_id, and srpc_service::sv_name.
Referenced by sfw_startup().
static void sfw_init_session (sfw_session_t * sn, lst_sid_t sid, unsigned features, const char * name) [inline, static]
Definition at line 271 of file framework.c.
References cfs_time_current(), INIT_LIST_HEAD, session_timeout, sfw_session_expired(), sfw_session_t::sn_batches, sfw_session_t::sn_brw_errors, sfw_session_t::sn_features, sfw_session_t::sn_id, sfw_session_t::sn_list, sfw_session_t::sn_name, sfw_session_t::sn_ping_errors, sfw_session_t::sn_refcount, sfw_session_t::sn_started, sfw_session_t::sn_timeout, sfw_session_t::sn_timer, sfw_session_t::sn_timer_active, strlcpy(), stt_timer_t::stt_data, stt_timer_t::stt_func, and stt_timer_t::stt_list.
Referenced by sfw_make_session().
static int sfw_load_test (struct sfw_test_instance * tsi) [static]
Definition at line 572 of file framework.c.
References CDEBUG, cfs_cpt_number(), CWARN, D_NET, LASSERT, sfw_find_test_case(), sfw_test_buffers(), srpc_serv_is_framework(), srpc_service_add_buffers(), srpc_service_remove_buffers(), srpc_service::sv_name, sfw_test_case::tsc_cli_ops, sfw_test_case::tsc_srv_service, sfw_test_instance::tsi_is_client, sfw_test_instance::tsi_ops, and sfw_test_instance::tsi_service.
Referenced by sfw_add_test_instance().
int sfw_make_session (srpc_mksn_reqst_t * request, srpc_mksn_reply_t * reply)
Definition at line 422 of file framework.c.
References CERROR, smoketest_framework::fw_lock, smoketest_framework::fw_session, LASSERT, LIBCFS_ALLOC, LNET_NID_ANY, LST_FEATS_MASK, msg, srpc_msg::msg_ses_feats, sfw_data, sfw_deactivate_session(), sfw_init_session(), sfw_sid_equal, sfw_session_t::sn_id, sfw_session_t::sn_name, sfw_session_t::sn_refcount, sfw_session_t::sn_timeout, and strlcpy().
Referenced by sfw_handle_server_rpc().
void sfw_post_rpc (srpc_client_rpc_t * rpc)
Definition at line 1594 of file framework.c.
References srpc_client_rpc::crpc_aborted, srpc_client_rpc::crpc_closed, srpc_client_rpc::crpc_list, srpc_client_rpc::crpc_lock, srpc_client_rpc::crpc_timeout, smoketest_framework::fw_shuttingdown, LASSERT, list_empty(), rpc_timeout, sfw_data, and srpc_post_rpc().
Referenced by lstcon_rpc_post().
static int sfw_query_batch (sfw_batch_t * tsb, int testidx, srpc_batch_reply_t * reply) [static]
Definition at line 1091 of file framework.c.
References sfw_batch_t::bat_nactive, sfw_batch_t::bat_tests, list_for_each_entry, and sfw_test_instance::tsi_nactive.
Referenced by sfw_control_batch().
static int sfw_register_test (srpc_service_t * service, sfw_test_client_ops_t * cliops) [static]
Definition at line 146 of file framework.c.
References CERROR, smoketest_framework::fw_tests, LIBCFS_ALLOC, list_add_tail(), sfw_data, sfw_find_test_case(), srpc_service::sv_id, srpc_service::sv_name, sfw_test_case::tsc_cli_ops, sfw_test_case::tsc_list, and sfw_test_case::tsc_srv_service.
Referenced by sfw_startup().
static int sfw_remove_session (srpc_rmsn_reqst_t * request, srpc_rmsn_reply_t * reply) [static]
Definition at line 491 of file framework.c.
References smoketest_framework::fw_lock, smoketest_framework::fw_session, LASSERT, LNET_NID_ANY, sfw_data, sfw_deactivate_session(), sfw_sid_equal, sfw_session_t::sn_id, and sfw_session_t::sn_refcount.
Referenced by sfw_handle_server_rpc().
static int sfw_run_batch (sfw_batch_t * tsb) [static]
Definition at line 1013 of file framework.c.
References lst_bid_t::bat_id, sfw_batch_t::bat_id, sfw_batch_t::bat_nactive, sfw_batch_t::bat_tests, CDEBUG, D_NET, LASSERT, list_for_each_entry, lnet_cpt_of_nid(), LPU64, lst_sched_test, lnet_process_id_t::nid, sfw_batch_active, sfw_run_test(), sfw_test_active, swi_init_workitem(), swi_schedule_workitem(), sfw_test_instance::tsi_is_client, sfw_test_instance::tsi_loop, sfw_test_instance::tsi_nactive, sfw_test_instance::tsi_stopping, sfw_test_instance::tsi_units, sfw_test_unit::tsu_dest, sfw_test_unit::tsu_loop, and sfw_test_unit::tsu_worker.
Referenced by sfw_control_batch().
static int sfw_run_test (swi_workitem_t * wi) [static]
Definition at line 964 of file framework.c.
References srpc_client_rpc::crpc_list, srpc_client_rpc::crpc_lock, srpc_client_rpc::crpc_timeout, LASSERT, list_add(), list_add_tail(), rpc_timeout, sfw_test_unit_done(), srpc_post_rpc(), swi_exit_workitem(), swi_workitem::swi_workitem, sfw_test_instance::tsi_active_rpcs, sfw_test_instance::tsi_free_rpcs, sfw_test_instance::tsi_lock, sfw_test_instance::tsi_ops, sfw_test_instance::tsi_stopping, sfw_test_client_ops_t::tso_prep_rpc, sfw_test_unit::tsu_dest, sfw_test_unit::tsu_instance, sfw_test_unit::tsu_loop, sfw_test_unit::tsu_worker, and cfs_workitem::wi_data.
Referenced by sfw_run_batch().
static void sfw_server_rpc_done (struct srpc_server_rpc * rpc) [static]
Definition at line 297 of file framework.c.
References CDEBUG, D_NET, libcfs_id2str(), srpc_service_cd::scd_svc, sfw_free_pages(), srpc_server_rpc::srpc_bulk, srpc_server_rpc::srpc_peer, srpc_server_rpc::srpc_scd, srpc_server_rpc::srpc_status, srpc_server_rpc::srpc_wi, status, srpc_service::sv_name, swi_workitem::swi_state, and swi_state2str().
Referenced by sfw_handle_server_rpc().
static void sfw_session_expired (void * data) [static]
Definition at line 251 of file framework.c.
References CWARN, smoketest_framework::fw_lock, smoketest_framework::fw_session, LASSERT, libcfs_nid2str(), LPU64, lst_sid_t::ses_nid, lst_sid_t::ses_stamp, sfw_data, sfw_deactivate_session(), sfw_session_t::sn_id, sfw_session_t::sn_name, and sfw_session_t::sn_timer_active.
Referenced by sfw_init_session().
void sfw_shutdown (void)
Definition at line 1748 of file framework.c.
References srpc_client_rpc::crpc_list, smoketest_framework::fw_active_srpc, smoketest_framework::fw_lock, smoketest_framework::fw_nzombies, smoketest_framework::fw_session, smoketest_framework::fw_shuttingdown, smoketest_framework::fw_tests, smoketest_framework::fw_zombie_rpcs, LIBCFS_FREE, list_del(), list_empty(), list_entry, list_for_each_entry, lst_wait_until, list_head::next, sfw_data, sfw_deactivate_session(), sfw_del_session_timer(), srpc_client_rpc_size, srpc_remove_service(), srpc_shutdown_service(), srpc_wait_service_shutdown(), srpc_service::sv_name, sfw_test_case::tsc_list, and sfw_test_case::tsc_srv_service.
Referenced by lnet_selftest_exit(), and sfw_startup().
int sfw_startup (void)
Definition at line 1650 of file framework.c.
References brw_init_test_client(), brw_init_test_service(), brw_test_client, brw_test_service, CERROR, CWARN, error, smoketest_framework::fw_active_srpc, smoketest_framework::fw_lock, smoketest_framework::fw_nzombies, smoketest_framework::fw_session, smoketest_framework::fw_tests, smoketest_framework::fw_zombie_rpcs, smoketest_framework::fw_zombie_sessions, INIT_LIST_HEAD, LASSERT, list_for_each_entry, ping_init_test_client(), ping_init_test_service(), ping_test_client, ping_test_service, rpc_timeout, session_timeout, sfw_bulk_ready(), sfw_data, SFW_FRWK_WI_MAX, sfw_handle_server_rpc(), sfw_register_test(), sfw_shutdown(), srpc_add_service(), srpc_service_add_buffers(), SRPC_SERVICE_TEST, srpc_service::sv_bulk_ready, srpc_service::sv_handler, srpc_service::sv_id, srpc_service::sv_name, srpc_service::sv_wi_total, and sfw_test_case::tsc_srv_service.
Referenced by lnet_selftest_init().
int sfw_stop_batch (sfw_batch_t * tsb, int force)
Definition at line 1049 of file framework.c.
References lst_bid_t::bat_id, sfw_batch_t::bat_id, sfw_batch_t::bat_tests, CDEBUG, srpc_client_rpc::crpc_lock, D_NET, list_for_each_entry, LPU64, sfw_batch_active, sfw_test_active, srpc_abort_rpc(), sfw_test_instance::tsi_active_rpcs, sfw_test_instance::tsi_is_client, sfw_test_instance::tsi_lock, and sfw_test_instance::tsi_stopping.
Referenced by sfw_control_batch(), and sfw_deactivate_session().
static int sfw_test_buffers (sfw_test_instance_t * tsi) [inline, static]
Definition at line 555 of file framework.c.
References LASSERT, max, sfw_find_test_case(), SFW_TEST_WI_EXTRA, SFW_TEST_WI_MIN, srpc_service::sv_ncpts, srpc_service::sv_wi_total, sfw_test_case::tsc_srv_service, sfw_test_instance::tsi_loop, and sfw_test_instance::tsi_service.
Referenced by sfw_load_test(), and sfw_unload_test().
static void sfw_test_rpc_done (srpc_client_rpc_t * rpc) [static]
Definition at line 885 of file framework.c.
References srpc_client_rpc::crpc_list, srpc_client_rpc::crpc_priv, srpc_client_rpc::crpc_status, done, LASSERT, list_del_init(), list_empty(), sfw_test_active, sfw_test_unit_done(), srpc_client_rpc_decref, swi_schedule_workitem(), sfw_test_instance::tsi_lock, sfw_test_instance::tsi_ops, sfw_test_instance::tsi_stopping, sfw_test_instance::tsi_stoptsu_onerr, sfw_test_client_ops_t::tso_done_rpc, sfw_test_unit::tsu_instance, sfw_test_unit::tsu_loop, and sfw_test_unit::tsu_worker.
Referenced by sfw_create_test_rpc().
static void sfw_test_rpc_fini (srpc_client_rpc_t * rpc) [static]
Definition at line 544 of file framework.c.
References srpc_client_rpc::crpc_list, srpc_client_rpc::crpc_priv, LASSERT, list_add(), list_empty(), sfw_test_instance::tsi_free_rpcs, and sfw_test_unit::tsu_instance.
Referenced by sfw_create_test_rpc().
static void sfw_test_unit_done (sfw_test_unit_t * tsu) [static]
Definition at line 842 of file framework.c.
References sfw_batch_t::bat_nactive, sfw_batch_t::bat_session, smoketest_framework::fw_lock, smoketest_framework::fw_session, LASSERT, list_del_init(), list_empty(), list_for_each_entry, sfw_batch_active, sfw_data, sfw_destroy_session(), sfw_test_active, sfw_session_t::sn_batches, sfw_session_t::sn_list, sfw_test_instance::tsi_batch, sfw_test_instance::tsi_lock, sfw_test_instance::tsi_nactive, sfw_test_instance::tsi_stopping, and sfw_test_unit::tsu_instance.
Referenced by sfw_run_test(), and sfw_test_rpc_done().
static void sfw_unload_test (struct sfw_test_instance * tsi) [static]
Definition at line 609 of file framework.c.
References LASSERT, sfw_find_test_case(), sfw_test_buffers(), srpc_service_remove_buffers(), sfw_test_case::tsc_srv_service, sfw_test_instance::tsi_is_client, and sfw_test_instance::tsi_service.
Referenced by sfw_destroy_test_instance().
static void sfw_unpack_addtest_req (srpc_msg_t * msg) [static]
Definition at line 702 of file framework.c.
References __swab16s, __swab32, __swab32s, LASSERT, LBUG, LST_FEAT_BULK_LEN, srpc_msg::msg_body, srpc_msg::msg_magic, srpc_msg::msg_ses_feats, srpc_msg::msg_type, SRPC_MSG_MAGIC, SRPC_MSG_TEST_REQST, SRPC_SERVICE_BRW, SRPC_SERVICE_PING, and srpc_msg::tes_reqst.
Referenced by sfw_add_test_instance().
void sfw_unpack_message (srpc_msg_t * msg)
Definition at line 1438 of file framework.c.
References __swab32, __swab32s, __swab64s, srpc_msg::bat_reply, srpc_msg::bat_reqst, srpc_msg::dbg_reply, srpc_msg::dbg_reqst, srpc_msg::join_reply, srpc_msg::join_reqst, LASSERT, LBUG, srpc_msg::mksn_reply, srpc_msg::mksn_reqst, srpc_msg::msg_body, srpc_msg::msg_magic, srpc_msg::msg_type, srpc_msg::rmsn_reply, srpc_msg::rmsn_reqst, sfw_unpack_fw_counters, sfw_unpack_lnet_counters, sfw_unpack_rpc_counters, sfw_unpack_sid, SRPC_MSG_BATCH_REPLY, SRPC_MSG_BATCH_REQST, SRPC_MSG_DEBUG_REPLY, SRPC_MSG_DEBUG_REQST, SRPC_MSG_JOIN_REPLY, SRPC_MSG_JOIN_REQST, SRPC_MSG_MAGIC, SRPC_MSG_MKSN_REPLY, SRPC_MSG_MKSN_REQST, SRPC_MSG_RMSN_REPLY, SRPC_MSG_RMSN_REQST, SRPC_MSG_STAT_REPLY, SRPC_MSG_STAT_REQST, SRPC_MSG_TEST_REPLY, SRPC_MSG_TEST_REQST, srpc_msg::stat_reply, srpc_msg::stat_reqst, srpc_msg::tes_reply, and srpc_msg::tes_reqst.
Referenced by lstcon_acceptor_handle(), lstcon_rpc_get_reply(), and sfw_handle_server_rpc().
Variable Documentation
lst_sid_t LST_INVALID_SID = {LNET_NID_ANY, -1}
Definition at line 46 of file framework.c.
int rpc_timeout = 64 [static]
Definition at line 52 of file framework.c.
Referenced by sfw_post_rpc(), sfw_run_test(), and sfw_startup().
int session_timeout = 100 [static]
Definition at line 48 of file framework.c.
Referenced by sfw_init_session(), and sfw_startup().
struct smoketest_framework sfw_data [static]
Referenced by sfw_add_session_timer(), sfw_add_test(), sfw_bid2batch(), sfw_bulk_ready(), sfw_client_rpc_fini(), sfw_control_batch(), sfw_create_rpc(), sfw_deactivate_session(), sfw_debug_session(), sfw_del_session_timer(), sfw_destroy_session(), sfw_find_batch(), sfw_find_test_case(), sfw_get_stats(), sfw_handle_server_rpc(), sfw_make_session(), sfw_post_rpc(), sfw_register_test(), sfw_remove_session(), sfw_session_expired(), sfw_shutdown(), sfw_startup(), and sfw_test_unit_done().
srpc_service_t sfw_services[] [static]
Definition at line 1610 of file framework.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.