Lustre: lustre/lvfs/fsfilt-ldiskfs.c File Reference
lustre/lvfs/fsfilt-ldiskfs.c File Reference
#include <linux/init.h>
#include <linux/module.h>
#include <linux/fs.h>
#include <linux/slab.h>
#include <linux/pagemap.h>
#include <ldiskfs/ldiskfs.h>
#include <ldiskfs/ldiskfs_jbd2.h>
#include <linux/version.h>
#include <linux/bitops.h>
#include <linux/quota.h>
#include <libcfs/libcfs.h>
#include <lustre_fsfilt.h>
#include <obd.h>
#include <linux/lustre_compat25.h>
#include <linux/lprocfs_status.h>
#include <ldiskfs/ldiskfs_extents.h>
Data Structures
struct bpointers
Defines
#define DEBUG_SUBSYSTEM S_FILTER
#define fsfilt_ldiskfs_ext_insert_extent(handle, inode, path, newext, flag) ldiskfs_ext_insert_extent(handle, inode, path, newext, flag)
#define ldiskfs_mb_discard_inode_preallocations(inode) ldiskfs_discard_preallocations(inode)
#define LDISKFS_EXTENTS_FL 0x00080000
#define EXT_ASSERT(cond) BUG_ON(!(cond))
#define EXT_GENERATION(inode) (LDISKFS_I(inode)->i_ext_generation)
#define ldiskfs_ext_base inode
#define ldiskfs_ext_base2inode(inode) (inode)
#define EXT_DEPTH(inode) ext_depth(inode)
#define fsfilt_ldiskfs_ext_walk_space(inode, block, num, cb, cbdata) ldiskfs_ext_walk_space(inode, block, num, cb, cbdata);
#define ll_unmap_underlying_metadata(sb, blocknr) unmap_underlying_metadata((sb)->s_bdev, blocknr)
Functions
static long ldiskfs_ext_find_goal (struct inode *inode, struct ldiskfs_ext_path *path, unsigned long block, int *aflags)
static unsigned long new_blocks (handle_t *handle, struct ldiskfs_ext_base *base, struct ldiskfs_ext_path *path, unsigned long block, unsigned long *count, int *err)
static int ldiskfs_ext_new_extent_cb (struct ldiskfs_ext_base *base, struct ldiskfs_ext_path *path, struct ldiskfs_ext_cache *cex, void *cbdata)
int fsfilt_map_nblocks (struct inode *inode, unsigned long block, unsigned long num, unsigned long *blocks, int create)
int fsfilt_ldiskfs_map_ext_inode_pages (struct inode *inode, struct page **page, int pages, unsigned long *blocks, int create)
int fsfilt_ldiskfs_map_bm_inode_pages (struct inode *inode, struct page **page, int pages, unsigned long *blocks, int create)
int fsfilt_ldiskfs_map_inode_pages (struct inode *inode, struct page **page, int pages, unsigned long *blocks, int create, struct mutex *optional_mutex)
static int __init fsfilt_ldiskfs_init (void)
static void __exit fsfilt_ldiskfs_exit (void)
module_init (fsfilt_ldiskfs_init)
module_exit (fsfilt_ldiskfs_exit)
MODULE_AUTHOR ("Sun Microsystems, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre ldiskfs Filesystem Helper v0.1")
MODULE_LICENSE ("GPL")
Variables
static struct fsfilt_operations fsfilt_ldiskfs_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_FILTER
Definition at line 41 of file fsfilt-ldiskfs.c.
#define EXT_ASSERT (cond) BUG_ON(!(cond))
Definition at line 78 of file fsfilt-ldiskfs.c.
Referenced by ldiskfs_ext_new_extent_cb().
#define EXT_DEPTH (inode) ext_depth(inode)
Definition at line 84 of file fsfilt-ldiskfs.c.
#define EXT_GENERATION (inode) (LDISKFS_I(inode)->i_ext_generation)
Definition at line 81 of file fsfilt-ldiskfs.c.
Referenced by ldiskfs_ext_new_extent_cb().
#define fsfilt_ldiskfs_ext_insert_extent (handle, inode, path, newext, flag) ldiskfs_ext_insert_extent(handle, inode, path, newext, flag)
Definition at line 67 of file fsfilt-ldiskfs.c.
Referenced by ldiskfs_ext_new_extent_cb().
#define fsfilt_ldiskfs_ext_walk_space (inode, block, num, cb, cbdata) ldiskfs_ext_walk_space(inode, block, num, cb, cbdata);
Definition at line 85 of file fsfilt-ldiskfs.c.
Referenced by fsfilt_map_nblocks().
#define ldiskfs_ext_base inode
Definition at line 82 of file fsfilt-ldiskfs.c.
Referenced by fsfilt_map_nblocks().
#define ldiskfs_ext_base2inode (inode) (inode)
Definition at line 83 of file fsfilt-ldiskfs.c.
Referenced by ldiskfs_ext_new_extent_cb(), and new_blocks().
#define LDISKFS_EXTENTS_FL 0x00080000
Definition at line 74 of file fsfilt-ldiskfs.c.
Referenced by fsfilt_ldiskfs_map_inode_pages(), osd_declare_write_commit(), osd_extents_enabled(), and osd_ldiskfs_map_inode_pages().
#define ldiskfs_mb_discard_inode_preallocations (inode) ldiskfs_discard_preallocations(inode)
Definition at line 70 of file fsfilt-ldiskfs.c.
Referenced by ldiskfs_ext_new_extent_cb().
#define ll_unmap_underlying_metadata (sb, blocknr) unmap_underlying_metadata((sb)->s_bdev, blocknr)
Definition at line 126 of file fsfilt-ldiskfs.c.
Referenced by ldiskfs_ext_new_extent_cb().
Function Documentation
static void __exit fsfilt_ldiskfs_exit (void) [static]
Definition at line 457 of file fsfilt-ldiskfs.c.
static int __init fsfilt_ldiskfs_init (void) [static]
Definition at line 452 of file fsfilt-ldiskfs.c.
int fsfilt_ldiskfs_map_bm_inode_pages (struct inode * inode, struct page ** page, int pages, unsigned long * blocks, int create)
Definition at line 405 of file fsfilt-ldiskfs.c.
References CERROR.
Referenced by fsfilt_ldiskfs_map_inode_pages().
int fsfilt_ldiskfs_map_ext_inode_pages (struct inode * inode, struct page ** page, int pages, unsigned long * blocks, int create)
Definition at line 356 of file fsfilt-ldiskfs.c.
References CDEBUG, cleanup(), D_OTHER, fsfilt_map_nblocks(), and GOTO.
Referenced by fsfilt_ldiskfs_map_inode_pages().
int fsfilt_ldiskfs_map_inode_pages (struct inode * inode, struct page ** page, int pages, unsigned long * blocks, int create, struct mutex * optional_mutex)
Definition at line 426 of file fsfilt-ldiskfs.c.
References fsfilt_ldiskfs_map_bm_inode_pages(), fsfilt_ldiskfs_map_ext_inode_pages(), and LDISKFS_EXTENTS_FL.
int fsfilt_map_nblocks (struct inode * inode, unsigned long block, unsigned long num, unsigned long * blocks, int create)
Definition at line 333 of file fsfilt-ldiskfs.c.
References bpointers::blocks, CDEBUG, bpointers::create, D_OTHER, fsfilt_ldiskfs_ext_walk_space, bpointers::init_num, ldiskfs_ext_base, ldiskfs_ext_new_extent_cb(), bpointers::num, and bpointers::start.
Referenced by fsfilt_ldiskfs_map_ext_inode_pages().
static long ldiskfs_ext_find_goal (struct inode * inode, struct ldiskfs_ext_path * path, unsigned long block, int * aflags) [static]
Definition at line 96 of file fsfilt-ldiskfs.c.
References le32_to_cpu.
Referenced by new_blocks().
static int ldiskfs_ext_new_extent_cb (struct ldiskfs_ext_base * base, struct ldiskfs_ext_path * path, struct ldiskfs_ext_cache * cex, void * cbdata) [static]
Definition at line 176 of file fsfilt-ldiskfs.c.
References bpointers::blocks, CERROR, cpu_to_le16, cpu_to_le32, bpointers::create, EXT_ASSERT, EXT_GENERATION, fsfilt_ldiskfs_ext_insert_extent, bpointers::init_num, ldiskfs_ext_base2inode, ldiskfs_mb_discard_inode_preallocations, le16_to_cpu, le32_to_cpu, ll_unmap_underlying_metadata, new_blocks(), bpointers::num, and bpointers::start.
Referenced by fsfilt_map_nblocks().
MODULE_AUTHOR ("Sun Microsystems, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre ldiskfs Filesystem Helper v0.1")
module_exit (fsfilt_ldiskfs_exit)
module_init (fsfilt_ldiskfs_init)
MODULE_LICENSE ("GPL")
static unsigned long new_blocks (handle_t * handle, struct ldiskfs_ext_base * base, struct ldiskfs_ext_path * path, unsigned long block, unsigned long * count, int * err) [static]
Definition at line 130 of file fsfilt-ldiskfs.c.
References ldiskfs_ext_base2inode, and ldiskfs_ext_find_goal().
Referenced by ldiskfs_ext_new_extent_cb().
Variable Documentation
struct fsfilt_operations fsfilt_ldiskfs_ops [static]
Initial value:
 {
        .fs_type                = "ldiskfs",
        .fs_owner               = THIS_MODULE,
        .fs_map_inode_pages     = fsfilt_ldiskfs_map_inode_pages,
}
Definition at line 446 of file fsfilt-ldiskfs.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.