Lustre: lustre/tests/fsx.c File Reference
lustre/tests/fsx.c File Reference
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <sys/mman.h>
#include <limits.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <stdarg.h>
#include <errno.h>
Data Structures
struct test_file
struct log_entry
Defines
#define MAP_FILE 0
#define NUMPRINTCOLUMNS 32
#define LOGSIZE 100000
#define OP_READ 1
#define OP_WRITE 2
#define OP_TRUNCATE 3
#define OP_CLOSEOPEN 4
#define OP_MAPREAD 5
#define OP_MAPWRITE 6
#define OP_SKIPPED 7
#define short_at(cp)
Enumerations
enum fd_iteration_policy { FD_SINGLE, FD_ROTATE, FD_RANDOM }
Functions
void vwarnc (int code, const char *fmt, va_list ap)
void warn (const char *fmt,...)
void __attribute__ ((format(printf, 1, 2)))
void prterr (char *prefix)
void log4 (int operation, int arg0, int arg1, int arg2, struct timeval *tv, const struct test_file *tf)
const char * fill_tf_buf (const struct test_file *tf)
void logdump (void)
void save_buffer (char *buffer, off_t bufferlength, int fd)
void report_failure (int status)
void check_buffers (unsigned offset, unsigned size)
struct test_file * get_tf (void)
void assign_fd_policy (char *policy)
int get_fd (void)
static const char * my_basename (const char *path)
void open_test_files (char **argv, int argc)
void close_test_files (void)
void check_size (void)
void check_trunc_hack (void)
void output_line (struct test_file *tf, int op, unsigned offset, unsigned size, struct timeval *tv)
void doread (unsigned offset, unsigned size)
void domapread (unsigned offset, unsigned size)
void gendata (char *original_buf, char *good_buf, unsigned offset, unsigned size)
void dowrite (unsigned offset, unsigned size)
void domapwrite (unsigned offset, unsigned size)
void dotruncate (unsigned size)
void writefileimage ()
void docloseopen (void)
void test (void)
void cleanup (int sig)
void usage (void)
int getnum (char *s, char **e)
int main (int argc, char **argv)
Variables
struct test_file * test_files
int num_test_files
int fd_policy = FD_RANDOM
int fd_last
struct log_entry oplog [LOGSIZE]
int logptr = 0
int logcount = 0
int page_size
int page_mask
char * original_buf
char * good_buf
char * temp_buf
char * fname
char logfile [1024]
char goodfile [1024]
off_t file_size = 0
off_t biggest = 0
char state [256]
unsigned long testcalls = 0
long simulatedopcount = 0
int closeprob = 0
int debug = 0
long debugstart = 0
long maxfilelen = 256 * 1024
int sizechecks = 1
int maxoplen = 64 * 1024
int quiet = 0
long progressinterval = 0
int readbdy = 1
int style = 0
int truncbdy = 1
int writebdy = 1
long monitorstart = -1
long monitorend = -1
int lite = 0
long numops = -1
int randomoplen = 1
int seed = 1
int mapped_writes = 1
int mapped_reads = 1
int fsxgoodfd = 0
FILE * fsxlogf = NULL
int badoff = -1
Define Documentation
#define LOGSIZE 100000
Definition at line 94 of file fsx.c.
Referenced by log4(), and logdump().
#define MAP_FILE 0
Definition at line 51 of file fsx.c.
Referenced by domapread(), and domapwrite().
#define NUMPRINTCOLUMNS 32
Definition at line 62 of file fsx.c.
#define OP_CLOSEOPEN 4
Definition at line 107 of file fsx.c.
Referenced by docloseopen(), and logdump().
#define OP_MAPREAD 5
Definition at line 108 of file fsx.c.
Referenced by domapread(), logdump(), and output_line().
#define OP_MAPWRITE 6
Definition at line 109 of file fsx.c.
Referenced by domapwrite(), logdump(), and output_line().
#define OP_READ 1
Definition at line 104 of file fsx.c.
Referenced by doread(), logdump(), and output_line().
#define OP_SKIPPED 7
Definition at line 110 of file fsx.c.
Referenced by domapread(), domapwrite(), doread(), dowrite(), and logdump().
#define OP_TRUNCATE 3
Definition at line 106 of file fsx.c.
Referenced by dotruncate(), logdump(), and output_line().
#define OP_WRITE 2
Definition at line 105 of file fsx.c.
Referenced by dowrite(), logdump(), and output_line().
#define short_at (cp)
Value:
((unsigned short)((*((unsigned char *)(cp)) << 8) | \
                                        *(((unsigned char *)(cp)) + 1)))
Definition at line 386 of file fsx.c.
Referenced by check_buffers().
Enumeration Type Documentation
enum fd_iteration_policy
Enumerator:
FD_SINGLE
FD_ROTATE
FD_RANDOM
Definition at line 75 of file fsx.c.
Function Documentation
void __attribute__ ((format(printf, 1, 2)))
Definition at line 179 of file fsx.c.
References log_entry::args, and fsxlogf.
void assign_fd_policy (char * policy)
Definition at line 457 of file fsx.c.
References fd_policy, FD_RANDOM, and FD_ROTATE.
Referenced by main().
void check_buffers (unsigned offset, unsigned size)
Definition at line 390 of file fsx.c.
References badoff, good_buf, report_failure(), short_at, and temp_buf.
Referenced by domapread(), and doread().
void check_size (void)
Definition at line 533 of file fsx.c.
References file_size, get_fd(), prterr(), and report_failure().
Referenced by test().
void check_trunc_hack (void)
Definition at line 555 of file fsx.c.
References get_fd(), and prterr().
Referenced by main().
void cleanup (int sig)
Definition at line 1082 of file fsx.c.
References testcalls.
Referenced by __llog_ctxt_put(), echo_device_alloc(), fsfilt_ldiskfs_map_ext_inode_pages(), ldlm_cli_enqueue_fini(), ll_prep_inode(), llog_run_tests(), lmv_revalidate_slaves(), lnet_delay_rule_del(), main(), mdd_rename(), mdd_unlink(), obd_cleanup(), ofd_seq_load(), osd_bufs_get(), osd_ldiskfs_map_ext_inode_pages(), osd_mdt_init(), osd_obj_map_delete(), osd_seq_load(), split_index_node(), test10(), test11(), test12(), test13(), test14(), test40(), tgt_name2lwp_name(), and tgt_truncate_last_rcvd().
void close_test_files (void)
Definition at line 518 of file fsx.c.
References test_file::fd, num_test_files, prterr(), report_failure(), and test_files.
Referenced by main().
void docloseopen (void)
Definition at line 978 of file fsx.c.
References debug, test_file::fd, file_size, get_tf(), log4(), OP_CLOSEOPEN, test_file::path, prterr(), quiet, report_failure(), simulatedopcount, and testcalls.
Referenced by test().
void domapread (unsigned offset, unsigned size)
Definition at line 668 of file fsx.c.
References check_buffers(), debug, test_file::fd, file_size, get_tf(), log4(), MAP_FILE, monitorend, monitorstart, OP_MAPREAD, OP_SKIPPED, output_line(), page_mask, prterr(), quiet, readbdy, report_failure(), simulatedopcount, temp_buf, and testcalls.
Referenced by test().
void domapwrite (unsigned offset, unsigned size)
Definition at line 811 of file fsx.c.
References debug, test_file::fd, file_size, gendata(), get_tf(), good_buf, lite, log4(), MAP_FILE, monitorend, monitorstart, OP_MAPWRITE, OP_SKIPPED, original_buf, output_line(), page_mask, prterr(), quiet, report_failure(), simulatedopcount, testcalls, warn(), and writebdy.
Referenced by test().
void doread (unsigned offset, unsigned size)
Definition at line 612 of file fsx.c.
References check_buffers(), debug, test_file::fd, file_size, get_tf(), log4(), monitorend, monitorstart, OP_READ, OP_SKIPPED, output_line(), prterr(), quiet, readbdy, report_failure(), ret, simulatedopcount, temp_buf, and testcalls.
Referenced by test().
void dotruncate (unsigned size)
Definition at line 911 of file fsx.c.
References biggest, debug, test_file::fd, file_size, get_tf(), good_buf, log4(), OP_TRUNCATE, output_line(), prterr(), quiet, report_failure(), simulatedopcount, testcalls, and truncbdy.
Referenced by test().
void dowrite (unsigned offset, unsigned size)
Definition at line 751 of file fsx.c.
References debug, test_file::fd, file_size, gendata(), get_tf(), good_buf, lite, log4(), monitorend, monitorstart, OP_SKIPPED, OP_WRITE, original_buf, output_line(), prterr(), quiet, report_failure(), ret, simulatedopcount, testcalls, warn(), and writebdy.
Referenced by test().
const char* fill_tf_buf (const struct test_file * tf)
Definition at line 222 of file fsx.c.
References fd_policy, FD_SINGLE, num_test_files, and test_files.
Referenced by logdump(), and output_line().
void gendata (char * original_buf, char * good_buf, unsigned offset, unsigned size)
Definition at line 739 of file fsx.c.
References testcalls.
Referenced by domapwrite(), and dowrite().
int get_fd (void)
Definition at line 470 of file fsx.c.
References test_file::fd, and get_tf().
Referenced by check_size(), check_trunc_hack(), main(), and writefileimage().
struct test_file* get_tf (void) [read]
Definition at line 434 of file fsx.c.
References fd_last, fd_policy, FD_RANDOM, FD_ROTATE, FD_SINGLE, num_test_files, and test_files.
Referenced by docloseopen(), domapread(), domapwrite(), doread(), dotruncate(), dowrite(), and get_fd().
int getnum (char * s, char ** e)
Definition at line 1131 of file fsx.c.
References ret.
Referenced by main().
void log4 (int operation, int arg0, int arg1, int arg2, struct timeval * tv, const struct test_file * tf)
Definition at line 203 of file fsx.c.
References log_entry::args, logcount, logptr, LOGSIZE, log_entry::operation, oplog, log_entry::tf, and log_entry::tv.
Referenced by docloseopen(), domapread(), domapwrite(), doread(), dotruncate(), and dowrite().
void logdump (void)
Definition at line 241 of file fsx.c.
References log_entry::args, badoff, fill_tf_buf(), logcount, logptr, LOGSIZE, OP_CLOSEOPEN, OP_MAPREAD, OP_MAPWRITE, OP_READ, OP_SKIPPED, OP_TRUNCATE, OP_WRITE, and oplog.
Referenced by report_failure().
int main (int argc, char ** argv)
Definition at line 1164 of file fsx.c.
References assign_fd_policy(), check_trunc_hack(), cleanup(), close_test_files(), closeprob, debug, debugstart, test_file::fd, file_size, fname, fsxgoodfd, fsxlogf, get_fd(), getnum(), good_buf, goodfile, lite, logfile, mapped_reads, mapped_writes, maxfilelen, maxoplen, monitorend, monitorstart, my_basename(), numops, open_test_files(), optarg, optind, original_buf, page_mask, page_size, progressinterval, prterr(), quiet, randomoplen, readbdy, ret, seed, simulatedopcount, sizechecks, state, style, temp_buf, test(), truncbdy, usage, warn(), and writebdy.
static const char* my_basename (const char * path) [static]
Definition at line 476 of file fsx.c.
Referenced by main().
void open_test_files (char ** argv, int argc)
Definition at line 484 of file fsx.c.
References test_file::fd, fd_policy, FD_SINGLE, lite, num_test_files, test_file::path, prterr(), quiet, and test_files.
Referenced by main().
void output_line (struct test_file * tf, int op, unsigned offset, unsigned size, struct timeval * tv)
Definition at line 584 of file fsx.c.
References debug, fill_tf_buf(), monitorend, monitorstart, OP_MAPREAD, OP_MAPWRITE, OP_READ, OP_TRUNCATE, OP_WRITE, progressinterval, quiet, and testcalls.
Referenced by domapread(), domapwrite(), doread(), dotruncate(), and dowrite().
void prterr (char * prefix)
Definition at line 196 of file fsx.c.
Referenced by check_size(), check_trunc_hack(), close_test_files(), docloseopen(), domapread(), domapwrite(), doread(), dotruncate(), dowrite(), main(), open_test_files(), save_buffer(), and writefileimage().
void report_failure (int status)
Definition at line 369 of file fsx.c.
References file_size, fname, fsxgoodfd, good_buf, goodfile, logdump(), and save_buffer().
Referenced by check_buffers(), check_size(), close_test_files(), docloseopen(), domapread(), domapwrite(), doread(), dotruncate(), dowrite(), and writefileimage().
void save_buffer (char * buffer, off_t bufferlength, int fd)
Definition at line 326 of file fsx.c.
References lite, prterr(), ret, and warn().
Referenced by report_failure().
void test (void)
Definition at line 1013 of file fsx.c.
References check_size(), closeprob, debug, debugstart, docloseopen(), domapread(), domapwrite(), doread(), dotruncate(), dowrite(), file_size, lite, mapped_reads, mapped_writes, maxfilelen, maxoplen, quiet, randomoplen, simulatedopcount, size, sizechecks, style, testcalls, and writefileimage().
Referenced by jt_lst_add_test(), jt_lst_list_batch(), jt_lst_query_batch(), lstcon_batch_destroy(), lstcon_batch_info(), lstcon_test_add(), lstcon_test_batch_query(), lstcon_test_find(), lstcon_testrpc_condition(), and main().
void usage (void)
Definition at line 1093 of file fsx.c.
void vwarnc (int code, const char * fmt, va_list ap)
Definition at line 154 of file fsx.c.
Referenced by warn().
void warn (const char * fmt, ...)
Definition at line 169 of file fsx.c.
References vwarnc().
Referenced by domapwrite(), dowrite(), ksocknal_create_conn(), main(), and save_buffer().
void writefileimage ()
Definition at line 950 of file fsx.c.
References test_file::fd, file_size, get_fd(), good_buf, lite, prterr(), and report_failure().
Referenced by test().
Variable Documentation
int badoff = -1
Definition at line 150 of file fsx.c.
Referenced by check_buffers(), and logdump().
off_t biggest = 0
Definition at line 123 of file fsx.c.
Referenced by dotruncate().
int closeprob = 0
Definition at line 128 of file fsx.c.
Referenced by main(), and test().
int debug = 0
Definition at line 129 of file fsx.c.
Referenced by docloseopen(), domapread(), domapwrite(), doread(), dotruncate(), dowrite(), lr_debug(), lr_replicate(), main(), output_line(), process_args(), and test().
long debugstart = 0
Definition at line 130 of file fsx.c.
Referenced by main(), and test().
int fd_last
Definition at line 81 of file fsx.c.
Referenced by get_tf().
int fd_policy = FD_RANDOM
Definition at line 80 of file fsx.c.
Referenced by assign_fd_policy(), fill_tf_buf(), get_tf(), and open_test_files().
off_t file_size = 0
Definition at line 122 of file fsx.c.
Referenced by calc_total_bytes(), check_fiemap(), check_size(), dir_read(), dir_write(), docloseopen(), domapread(), domapwrite(), doread(), dotruncate(), dowrite(), llog_pack_buffer(), main(), report_failure(), test(), and writefileimage().
char* fname
Definition at line 118 of file fsx.c.
Referenced by cb_find_init(), cb_getstripe(), do_svc_downcall(), get_lmd_info(), lfs_setstripe(), llapi_file_get_stripe(), main(), mmap_tst7_func(), mmap_tst8(), osd_quota_migration(), and report_failure().
int fsxgoodfd = 0
Definition at line 148 of file fsx.c.
Referenced by main(), and report_failure().
FILE* fsxlogf = NULL
Definition at line 149 of file fsx.c.
Referenced by __attribute__(), and main().
char* good_buf
Definition at line 116 of file fsx.c.
Referenced by check_buffers(), domapwrite(), dotruncate(), dowrite(), main(), report_failure(), and writefileimage().
char goodfile[1024]
Definition at line 120 of file fsx.c.
Referenced by main(), and report_failure().
int lite = 0
Definition at line 142 of file fsx.c.
Referenced by domapwrite(), dowrite(), main(), open_test_files(), save_buffer(), test(), and writefileimage().
int logcount = 0
Definition at line 98 of file fsx.c.
Referenced by log4(), and logdump().
char logfile[1024]
Definition at line 119 of file fsx.c.
Referenced by main().
int logptr = 0
Definition at line 97 of file fsx.c.
Referenced by log4(), and logdump().
int mapped_reads = 1
Definition at line 147 of file fsx.c.
Referenced by main(), and test().
int mapped_writes = 1
Definition at line 146 of file fsx.c.
Referenced by main(), and test().
long maxfilelen = 256 * 1024
Definition at line 131 of file fsx.c.
Referenced by main(), and test().
int maxoplen = 64 * 1024
Definition at line 133 of file fsx.c.
Referenced by main(), and test().
long monitorend = -1
Definition at line 141 of file fsx.c.
Referenced by domapread(), domapwrite(), doread(), dowrite(), main(), and output_line().
long monitorstart = -1
Definition at line 140 of file fsx.c.
Referenced by domapread(), domapwrite(), doread(), dowrite(), main(), and output_line().
int num_test_files
Definition at line 74 of file fsx.c.
Referenced by close_test_files(), fill_tf_buf(), get_tf(), and open_test_files().
long numops = -1
Definition at line 143 of file fsx.c.
Referenced by main().
struct log_entry oplog[LOGSIZE]
Definition at line 96 of file fsx.c.
Referenced by log4(), and logdump().
char* original_buf
Definition at line 115 of file fsx.c.
Referenced by domapwrite(), dowrite(), and main().
int page_mask
Definition at line 113 of file fsx.c.
Referenced by domapread(), domapwrite(), and main().
int page_size
Definition at line 112 of file fsx.c.
Referenced by cl_echo_object_brw(), ll_direct_rw_pages(), llapi_stripe_limit_check(), main(), mmap_initialize(), mmap_tst1(), mmap_tst2(), mmap_tst3(), mmap_tst4(), mmap_tst5(), mmap_tst6(), mmap_tst7_func(), mmap_tst8(), read_param(), remote_tst3(), remote_tst4(), and rw_file().
long progressinterval = 0
Definition at line 135 of file fsx.c.
Referenced by main(), and output_line().
int quiet = 0
Definition at line 134 of file fsx.c.
Referenced by docloseopen(), domapread(), domapwrite(), doread(), dotruncate(), dowrite(), main(), open_test_files(), output_line(), and test().
int randomoplen = 1
Definition at line 144 of file fsx.c.
Referenced by main(), and test().
int readbdy = 1
Definition at line 136 of file fsx.c.
Referenced by domapread(), doread(), and main().
int seed = 1
Definition at line 145 of file fsx.c.
Referenced by __attribute__(), class_handle_init(), lnet_shuffle_seed(), lustre_init(), main(), and process_args().
long simulatedopcount = 0
Definition at line 127 of file fsx.c.
Referenced by docloseopen(), domapread(), domapwrite(), doread(), dotruncate(), dowrite(), main(), and test().
int sizechecks = 1
Definition at line 132 of file fsx.c.
Referenced by main(), and test().
char state[256]
Definition at line 124 of file fsx.c.
Referenced by cl_page_disown0(), jt_ptl_print_peers(), kgnilnd_conn_state2str(), kgnilnd_dgram_state2str(), kgnilnd_smsg_seq_show(), ll_setxattr(), lov_layout_change(), lprocfs_ir_set_state(), main(), and srpc_shutdown().
int style = 0
Definition at line 137 of file fsx.c.
Referenced by main(), and test().
char* temp_buf
Definition at line 117 of file fsx.c.
Referenced by check_buffers(), domapread(), doread(), and main().
struct test_file * test_files
Referenced by close_test_files(), fill_tf_buf(), get_tf(), and open_test_files().
unsigned long testcalls = 0
Definition at line 125 of file fsx.c.
Referenced by cleanup(), docloseopen(), domapread(), domapwrite(), doread(), dotruncate(), dowrite(), gendata(), output_line(), and test().
int truncbdy = 1
Definition at line 138 of file fsx.c.
Referenced by dotruncate(), and main().
int writebdy = 1
Definition at line 139 of file fsx.c.
Referenced by domapwrite(), dowrite(), and main().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.