Lustre: lustre/obdclass/genops.c File Reference
lustre/obdclass/genops.c File Reference
#include <linux/kthread.h>
#include <obd_class.h>
#include <lprocfs_status.h>
#include <lustre_disk.h>
#include <lustre_kernelcomm.h>
Data Structures
struct obd_request_slot_waiter
Defines
#define DEBUG_SUBSYSTEM S_CLASS
#define CLASS_MAX_NAME 1024
#define pct(a, b) (b ? a * 100 / b : 0)
Enumerations
enum { OBD_ZOMBIE_STOP = 0x0001 }
Functions
static void obd_zombie_impexp_notify (void)
notify import/export destroy thread about new zombie.
static void obd_zombie_export_add (struct obd_export *exp)
Add export to the obd_zombe thread and notify it.
static void obd_zombie_import_add (struct obd_import *imp)
Add import to the obd_zombe thread and notify it.
static void print_export_data (struct obd_export *exp, const char *status, int locks)
static struct obd_device * obd_device_alloc (void)
static void obd_device_free (struct obd_device *obd)
struct obd_type * class_search_type (const char *name)
struct obd_type * class_get_type (const char *name)
void class_put_type (struct obd_type *type)
int class_register_type (struct obd_ops *dt_ops, struct md_ops *md_ops, bool enable_proc, struct lprocfs_vars *vars, const char *name, struct lu_device_type *ldt)
int class_unregister_type (const char *name)
struct obd_device * class_newdev (const char *type_name, const char *name)
Create a new obd device.
void class_release_dev (struct obd_device *obd)
int class_name2dev (const char *name)
struct obd_device * class_name2obd (const char *name)
int class_uuid2dev (struct obd_uuid *uuid)
struct obd_device * class_uuid2obd (struct obd_uuid *uuid)
struct obd_device * class_num2obd (int num)
Get obd device from obd_devs[].
int get_devices_count (void)
Get obd devices count.
void class_obd_list (void)
struct obd_device * class_find_client_obd (struct obd_uuid *tgt_uuid, const char *typ_name, struct obd_uuid *grp_uuid)
struct obd_device * class_devices_in_group (struct obd_uuid *grp_uuid, int *next)
int class_notify_sptlrpc_conf (const char *fsname, int namelen)
to notify sptlrpc log for fsname has changed, let every relevant OBD adjust sptlrpc settings accordingly.
void obd_cleanup_caches (void)
int obd_init_caches (void)
struct obd_export * class_conn2export (struct lustre_handle *conn)
struct obd_device * class_exp2obd (struct obd_export *exp)
struct obd_device * class_conn2obd (struct lustre_handle *conn)
struct obd_import * class_exp2cliimp (struct obd_export *exp)
struct obd_import * class_conn2cliimp (struct lustre_handle *conn)
static void class_export_destroy (struct obd_export *exp)
static void export_handle_addref (void *export)
struct obd_export * class_export_get (struct obd_export *exp)
void class_export_put (struct obd_export *exp)
struct obd_export * class_new_export (struct obd_device *obd, struct obd_uuid *cluuid)
void class_unlink_export (struct obd_export *exp)
static void class_import_destroy (struct obd_import *imp)
static void import_handle_addref (void *import)
struct obd_import * class_import_get (struct obd_import *import)
void class_import_put (struct obd_import *imp)
static void init_imp_at (struct imp_at *at)
struct obd_import * class_new_import (struct obd_device *obd)
void class_destroy_import (struct obd_import *import)
int class_connect (struct lustre_handle *conn, struct obd_device *obd, struct obd_uuid *cluuid)
static void class_export_recovery_cleanup (struct obd_export *exp)
int class_disconnect (struct obd_export *export)
int class_connected_export (struct obd_export *exp)
static void class_disconnect_export_list (struct list_head *list, enum obd_option flags)
void class_disconnect_exports (struct obd_device *obd)
void class_disconnect_stale_exports (struct obd_device *obd, int(*test_export)(struct obd_export *))
void class_fail_export (struct obd_export *exp)
char * obd_export_nid2str (struct obd_export *exp)
int obd_export_evict_by_nid (struct obd_device *obd, const char *nid)
int obd_export_evict_by_uuid (struct obd_device *obd, const char *uuid)
void dump_exports (struct obd_device *obd, int locks)
void obd_exports_barrier (struct obd_device *obd)
void obd_zombie_impexp_cull (void)
kill zombie imports and exports
static int obd_zombie_impexp_check (void *arg)
check for work for kill zombie import/export thread.
static int obd_zombie_is_idle (void)
check whether obd_zombie is idle
void obd_zombie_barrier (void)
wait when obd_zombie import/export queues become empty
struct obd_export * obd_stale_export_get (void)
void obd_stale_export_put (struct obd_export *exp)
void obd_stale_export_adjust (struct obd_export *exp)
Adjust the position of the export in the stale list, i.e.
static int obd_zombie_impexp_thread (void *unused)
destroy zombie export/import thread.
int obd_zombie_impexp_init (void)
start destroy zombie import/export thread
void obd_zombie_impexp_stop (void)
stop destroy zombie import/export thread
int kuc_len (int payload_len)
struct kuc_hdr * kuc_ptr (void *p)
void * kuc_alloc (int payload_len, int transport, int type)
void kuc_free (void *p, int payload_len)
static bool obd_request_slot_avail (struct client_obd *cli, struct obd_request_slot_waiter *orsw)
int obd_get_request_slot (struct client_obd *cli)
void obd_put_request_slot (struct client_obd *cli)
__u32 obd_get_max_rpcs_in_flight (struct client_obd *cli)
int obd_set_max_rpcs_in_flight (struct client_obd *cli, __u32 max)
__u16 obd_get_max_mod_rpcs_in_flight (struct client_obd *cli)
int obd_set_max_mod_rpcs_in_flight (struct client_obd *cli, __u16 max)
int obd_mod_rpc_stats_seq_show (struct client_obd *cli, struct seq_file *seq)
static bool obd_mod_rpc_slot_avail_locked (struct client_obd *cli, bool close_req)
static bool obd_mod_rpc_slot_avail (struct client_obd *cli, bool close_req)
__u16 obd_get_mod_rpc_slot (struct client_obd *cli, __u32 opc, struct lookup_intent *it)
void obd_put_mod_rpc_slot (struct client_obd *cli, __u32 opc, struct lookup_intent *it, __u16 tag)
Variables
spinlock_t obd_types_lock
static struct kmem_cache * obd_device_cachep
struct kmem_cache * obdo_cachep
static struct kmem_cache * import_cachep
static struct list_head obd_zombie_imports
static struct list_head obd_zombie_exports
static spinlock_t obd_zombie_impexp_lock
struct list_head obd_stale_exports
spinlock_t obd_stale_export_lock
atomic_t obd_stale_export_num
int(* ptlrpc_put_connection_superhack)(struct ptlrpc_connection *c)
static struct portals_handle_ops export_handle_ops
static struct portals_handle_ops import_handle_ops
static int zombies_count = 0
static struct completion obd_zombie_start
static struct completion obd_zombie_stop
static unsigned long obd_zombie_flags
static wait_queue_head_t obd_zombie_waitq
static pid_t obd_zombie_pid
Define Documentation
#define CLASS_MAX_NAME 1024
Definition at line 165 of file genops.c.
Referenced by class_register_type().
#define DEBUG_SUBSYSTEM S_CLASS
Definition at line 42 of file genops.c.
#define pct (a, b) (b ? a * 100 / b : 0)
Definition at line 2145 of file genops.c.
Enumeration Type Documentation
anonymous enum
Enumerator:
OBD_ZOMBIE_STOP
Definition at line 1665 of file genops.c.
Function Documentation
int class_connect (struct lustre_handle * conn, struct obd_device * obd, struct obd_uuid * cluuid)
Definition at line 1150 of file genops.c.
References CDEBUG, class_export_put(), class_new_export(), lustre_handle::cookie, D_IOCTL, ENTRY, obd_export::exp_handle, portals_handle::h_cookie, LASSERT, LPX64, RETURN, and obd_uuid::uuid.
Referenced by client_connect_import(), echo_client_connect(), echo_connect(), lmv_connect(), lod_obd_connect(), lov_connect(), lwp_obd_connect(), mdd_obd_connect(), mdt_obd_connect(), mgs_obd_connect(), ofd_obd_connect(), osd_obd_connect(), osp_obd_connect(), and qmt_device_obd_connect().
int class_connected_export (struct obd_export * exp)
Definition at line 1260 of file genops.c.
References obd_export::exp_conn_cnt, obd_export::exp_failed, and obd_export::exp_lock.
Referenced by tgt_request_handle().
void class_destroy_import (struct obd_import * import)
Definition at line 1091 of file genops.c.
References class_handle_unhash(), class_import_put(), and LASSERT.
Referenced by client_destroy_import(), and client_obd_setup().
struct obd_device* class_devices_in_group (struct obd_uuid * grp_uuid, int * next) [read]
Definition at line 580 of file genops.c.
References class_devno_max(), class_num2obd(), obd_device::obd_dev_lock, obd_device::obd_uuid, and obd_uuid_equals().
Referenced by ll_put_super().
int class_disconnect (struct obd_export * export)
Definition at line 1220 of file genops.c.
References ptlrpc_connection::c_peer, CDEBUG, cfs_hash_del(), class_export_put(), class_export_recovery_cleanup(), class_unlink_export(), CWARN, D_IOCTL, ENTRY, obd_export::exp_connection, obd_export::exp_disconnected, obd_export::exp_handle, obd_export::exp_lock, obd_export::exp_nid_hash, obd_export::exp_obd, GOTO, portals_handle::h_cookie, hlist_unhashed(), LASSERT, LPX64, lnet_process_id_t::nid, obd_device::obd_nid_hash, and RETURN.
Referenced by client_connect_import(), client_disconnect_export(), echo_client_disconnect(), lmv_check_connect(), lmv_disconnect(), lod_obd_disconnect(), lov_disconnect(), lwp_device_fini(), lwp_obd_connect(), lwp_obd_disconnect(), mdd_obd_disconnect(), mdt_obd_connect(), mgs_obd_connect(), ofd_obd_connect(), osd_obd_disconnect(), osp_obd_disconnect(), and qmt_device_obd_disconnect().
static void class_disconnect_export_list (struct list_head * list, enum obd_option flags) [static]
Definition at line 1273 of file genops.c.
References CDEBUG, CFS_TIME_T, class_export_get(), class_export_put(), D_HA, ENTRY, EXIT, obd_export::exp_client_uuid, obd_export::exp_flags, obd_export::exp_last_request_time, obd_export::exp_lock, obd_export::exp_obd, obd_export::exp_obd_chain, list_del_init(), list_empty(), list_entry, list_head::next, obd_disconnect(), obd_export_nid2str(), obd_device::obd_name, obd_device::obd_uuid, and obd_uuid_equals().
Referenced by class_disconnect_exports(), and class_disconnect_stale_exports().
void class_disconnect_exports (struct obd_device * obd)
Definition at line 1319 of file genops.c.
References CDEBUG, class_disconnect_export_list(), D_HA, ENTRY, EXIT, exp_flags_from_obd(), INIT_LIST_HEAD, list_empty(), list_splice_init(), obd_device::obd_delayed_exports, obd_device::obd_dev_lock, obd_device::obd_exports, and obd_device::obd_minor.
Referenced by class_cleanup(), mgs_device_fini(), and tgt_server_data_init().
void class_disconnect_stale_exports (struct obd_device * obd, int(*)(struct obd_export *) test_export)
Definition at line 1345 of file genops.c.
References ptlrpc_connection::c_peer, CDEBUG, class_disconnect_export_list(), D_HA, ENTRY, EXIT, obd_export::exp_client_uuid, obd_export::exp_connection, obd_export::exp_failed, exp_flags_from_obd(), obd_export::exp_lock, obd_export::exp_obd, obd_export::exp_obd_chain, INIT_LIST_HEAD, LCONSOLE_WARN, libcfs_nid2str(), list_for_each_entry_safe, list_move(), lnet_process_id_t::nid, obd_device::obd_dev_lock, obd_device::obd_exports, obd_device::obd_name, OBD_OPT_ABORT_RECOV, obd_device::obd_uuid, obd_uuid_equals(), print_export_data(), and obd_uuid::uuid.
struct obd_device* class_exp2obd (struct obd_export * exp) [read]
Definition at line 729 of file genops.c.
References obd_export::exp_obd.
Referenced by __lov_del_obd(), cb_statfs_update(), client_disconnect_export(), echo_client_brw_ioctl(), echo_create(), echo_destroy(), echo_getattr(), echo_setattr(), ldlm_completion_ast(), ldlm_flock_completion_ast(), ll_close_inode_openhandle(), ll_get_obd_name(), ll_put_super(), ll_umount_begin(), lmv_disconnect(), lmv_disconnect_mdc(), lmv_fid2path(), lmv_fid_alloc(), lmv_get_info(), lmv_hsm_ct_register(), lmv_iocontrol(), lmv_quotactl(), lmv_set_info_async(), lmv_set_mdc_active(), lmv_statfs(), lod_obd_set_info_async(), lov_disconnect(), lov_disconnect_obd(), lov_get_info(), lov_iocontrol(), lov_set_info_async(), lov_statfs_async(), mdc_cancel_unused(), mdc_close(), mdc_enqueue(), mdc_intent_getattr_async(), mdc_intent_getattr_async_interpret(), mdc_intent_getattr_pack(), mdc_intent_layout_pack(), mdc_intent_open_pack(), mdc_intent_unlink_pack(), mdc_lock_match(), mdc_null_inode(), mdc_statfs(), mdc_unlink(), ofd_statfs(), osc_disconnect(), osc_statfs(), osc_statfs_async(), ping_evictor_wake(), qsd_conn_callback(), tgt_blocking_ast(), tgt_client_data_update(), tgt_client_del(), tgt_handler_find_check(), tgt_init_sec_level(), and tgt_request_handle().
static void class_export_destroy (struct obd_export * exp) [static]
Definition at line 767 of file genops.c.
References CDEBUG, class_decref(), D_IOCTL, ENTRY, EXIT, obd_export::exp_client_uuid, obd_export::exp_connection, obd_export::exp_handle, obd_export::exp_hp_rpcs, obd_export::exp_obd, obd_export::exp_outstanding_replies, obd_export::exp_refcount, obd_export::exp_req_replay_queue, obd_export::exp_uncommitted_replies, LASSERT, LASSERT_ATOMIC_ZERO, list_empty(), obd_destroy_export(), OBD_FREE_RCU, obd_device::obd_name, ptlrpc_put_connection_superhack, and obd_uuid::uuid.
Referenced by obd_zombie_impexp_cull().
struct obd_export* class_export_get (struct obd_export * exp) [read]
Definition at line 803 of file genops.c.
References CDEBUG, D_INFO, and obd_export::exp_refcount.
Referenced by class_disconnect_export_list(), class_fail_export(), do_config_log_add(), export_handle_addref(), fld_client_add_target(), gen_export_get(), ldlm_export_flock_get(), ldlm_flock_deadlock(), ldlm_flock_lookup_cb(), llog_setup(), lmv_connect(), lustre_find_lwp_by_index(), lustre_lwp_connect(), lustre_notify_lwp_list(), mdt_obd_disconnect(), mdt_tgt_connect(), mgs_fsc_attach(), mgs_obd_disconnect(), nid_export_get(), nm_member_add(), ofd_create_hdl(), ofd_obd_disconnect(), osp_obd_connect(), ping_evictor_main(), ptlrpc_request_change_export(), qmt_lvbo_update(), seq_client_init(), target_send_reply(), tgt_connect(), and uuid_export_get().
void class_export_put (struct obd_export * exp)
Definition at line 812 of file genops.c.
References CDEBUG, D_INFO, D_IOCTL, obd_export::exp_client_uuid, obd_export::exp_obd_chain, obd_export::exp_refcount, obd_export::exp_stale_list, LASSERT, LASSERT_ATOMIC_GT_LT, list_empty(), lprocfs_exp_cleanup(), obd_zombie_export_add(), and obd_uuid::uuid.
Referenced by class_conn2obd(), class_connect(), class_disconnect(), class_disconnect_export_list(), class_fail_export(), class_setup(), config_log_put(), distribute_txn_replay_handle(), fld_client_del_target(), fld_client_fini(), gen_export_put_locked(), import_select_connection(), ldlm_export_flock_put(), ldlm_flock_deadlock(), ldlm_lock_destroy_internal(), lfsck_layout_slave_async_interpret(), lfsck_layout_slave_check_pairs(), lfsck_layout_slave_notify_master(), lfsck_layout_slave_query_master(), llog_ctxt_destroy(), lmv_check_connect(), lmv_disconnect(), lustre_disconnect_lwp(), lustre_lwp_connect(), lustre_put_lwp_item(), mdt_hsm_agent_send(), mdt_obd_disconnect(), mgs_fsc_attach(), mgs_fsc_cleanup(), mgs_fsc_cleanup_by_fsdb(), mgs_obd_disconnect(), nid_export_put_locked(), nm_member_del(), nm_member_delete_list(), obd_export_evict_by_nid(), obd_export_evict_by_uuid(), obd_stale_export_put(), ofd_obd_disconnect(), osp_precreate_thread(), ping_evictor_main(), ptlrpc_at_send_early_reply(), ptlrpc_connect_interpret(), ptlrpc_free_bulk(), ptlrpc_handle_rs(), ptlrpc_request_change_export(), ptlrpc_server_drop_request(), qmt_lvbo_update(), seq_client_fini(), tgt_clients_data_init(), tgt_reply_data_init(), and uuid_export_put_locked().
static void class_export_recovery_cleanup (struct obd_export * exp) [static]
Cleanup req replay fields
Cleanup lock replay data
Definition at line 1173 of file genops.c.
References exp_connect_flags(), obd_export::exp_in_recovery, obd_export::exp_lock, obd_export::exp_lock_replay_needed, obd_export::exp_obd, obd_export::exp_req_replay_needed, LASSERT, LASSERT_ATOMIC_POS, OBD_CONNECT_LIGHTWEIGHT, obd_device::obd_connected_clients, obd_device::obd_lock_replay_clients, obd_device::obd_recovering, obd_device::obd_recovery_task_lock, obd_device::obd_req_replay_clients, and obd_device::obd_stale_clients.
Referenced by class_disconnect().
void class_fail_export (struct obd_export * exp)
Definition at line 1395 of file genops.c.
References CDEBUG, CERROR, class_export_get(), class_export_put(), D_HA, obd_export::exp_client_uuid, obd_export::exp_failed, obd_export::exp_lock, libcfs_debug_dumplog(), obd_disconnect(), obd_dump_on_timeout, and obd_uuid::uuid.
Referenced by mdt_export_evict(), obd_export_evict_by_nid(), obd_export_evict_by_uuid(), ping_evictor_main(), and ptlrpc_check_req().
struct obd_device* class_find_client_obd (struct obd_uuid * tgt_uuid, const char * typ_name, struct obd_uuid * grp_uuid) [read]
Definition at line 547 of file genops.c.
References client_obd::cl_target_uuid, class_devno_max(), class_num2obd(), obd_device::cli, obd_device::obd_dev_lock, obd_device::obd_type, obd_device::obd_uuid, obd_uuid_equals(), obd_type::typ_name, and obd_device::u.
Referenced by llog_test_6(), lmv_add_target(), lmv_connect_mdc(), lod_add_device(), lod_del_device(), and lov_add_target().
struct obd_type* class_get_type (const char * name) [read]
Definition at line 121 of file genops.c.
References CDEBUG, class_search_type(), D_INFO, LCONSOLE_ERROR_MSG, LUSTRE_LWP_NAME, LUSTRE_MDS_NAME, LUSTRE_MDT_NAME, LUSTRE_OSP_NAME, obd_ops::o_owner, obd_type::obd_type_lock, obd_type::typ_dt_ops, and obd_type::typ_refcnt.
Referenced by class_newdev().
static void class_import_destroy (struct obd_import * imp) [static]
Definition at line 968 of file genops.c.
References CDEBUG, class_decref(), D_IOCTL, ENTRY, EXIT, obd_import::imp_conn_list, obd_import::imp_connection, obd_import::imp_handle, obd_import::imp_obd, obd_import::imp_refcount, obd_import::imp_sec, LASSERT, LASSERT_ATOMIC_ZERO, list_del_init(), list_empty(), list_entry, list_head::next, OBD_FREE, OBD_FREE_RCU, obd_device::obd_name, obd_import_conn::oic_conn, obd_import_conn::oic_item, and ptlrpc_put_connection_superhack.
Referenced by obd_zombie_impexp_cull().
struct obd_import* class_import_get (struct obd_import * import) [read]
Definition at line 1005 of file genops.c.
References CDEBUG, and D_INFO.
Referenced by __ptlrpc_request_alloc(), client_destroy_import(), gss_do_ctx_init_rpc(), gss_sec_create_common(), import_handle_addref(), llog_initiator_connect(), mdc_statfs(), osc_statfs(), osp_obd_statfs(), plain_create_sec(), ptlrpc_import_recovery_state_machine(), ptlrpc_pinger_add_import(), ptlrpc_prep_bulk_imp(), and ptlrpcd_alloc_work().
void class_import_put (struct obd_import * imp)
Definition at line 1015 of file genops.c.
References CDEBUG, D_INFO, ENTRY, EXIT, obd_import::imp_obd, obd_import::imp_refcount, obd_import::imp_zombie_chain, LASSERT, LASSERT_ATOMIC_GE_LT, LASSERT_ATOMIC_GT_LT, list_empty(), obd_device::obd_name, and obd_zombie_import_add().
Referenced by __ptlrpc_free_req(), class_destroy_import(), client_destroy_import(), client_obd_setup(), gss_do_ctx_init_rpc(), gss_sec_destroy_common(), llog_ctxt_destroy(), llog_initiator_connect(), mdc_statfs(), osc_statfs(), osp_obd_statfs(), plain_destroy_sec(), ptlrpc_free_bulk(), ptlrpc_import_recovery_state_machine(), ptlrpc_invalidate_import_thread(), ptlrpc_pinger_del_import(), and ptlrpc_request_bufs_pack().
int class_name2dev (const char * name)
Definition at line 402 of file genops.c.
References class_devno_max(), class_num2obd(), LASSERT, obd_device::obd_attached, obd_device::obd_dev_lock, obd_dev_lock, OBD_DEVICE_MAGIC, obd_device::obd_magic, and obd_device::obd_name.
Referenced by class_name2obd(), and class_resolve_dev_name().
struct obd_device* class_name2obd (const char * name) [read]
Definition at line 429 of file genops.c.
References class_devno_max(), class_name2dev(), and class_num2obd().
Referenced by class_handle_ioctl(), class_process_config(), client_common_fill_super(), echo_client_setup(), echo_device_alloc(), gss_do_ctx_init_rpc(), llog_test_setup(), lod_connect_to_osd(), lod_init0(), lod_pools_init(), lod_process_config(), lov_device_alloc(), lustre_find_lwp(), lustre_lwp_setup(), lustre_register_lwp_item(), lustre_start_mgc(), lwp_init0(), mdd_connect_to_next(), mdd_init0(), mds_device_alloc(), mdt_connect_to_next(), mdt_init0(), mdt_quota_init(), mdt_stack_init(), mgc_apply_recover_logs(), mgs_connect_to_osd(), mgs_init0(), ofd_connect_to_next(), ofd_init0(), osc_device_alloc(), osd_start(), osp_connect_to_osd(), osp_init0(), qmt_connect_to_osd(), qmt_device_init0(), server_fill_super(), server_put_super(), server_start_targets(), server_stop_mgs(), and server_stop_servers().
struct obd_export* class_new_export (struct obd_device * obd, struct obd_uuid * cluuid) [read]
Definition at line 836 of file genops.c.
References at_init(), cfs_hash_add_unique(), cfs_hash_del(), cfs_hash_getref(), cfs_hash_putref(), cfs_time_current_sec(), class_handle_hash(), class_handle_unhash(), class_incref(), ENTRY, obd_export::exp_bl_list, obd_export::exp_bl_list_lock, obd_export::exp_bl_lock_at, obd_export::exp_cb_count, obd_export::exp_client_uuid, obd_export::exp_conn_cnt, obd_export::exp_flock_hash, obd_export::exp_flvr, obd_export::exp_gen_hash, obd_export::exp_handle, obd_export::exp_hp_rpcs, obd_export::exp_last_request_time, obd_export::exp_lock, obd_export::exp_lock_hash, obd_export::exp_locks_count, obd_export::exp_nid_hash, obd_export::exp_obd, obd_export::exp_obd_chain, obd_export::exp_obd_chain_timed, obd_export::exp_outstanding_replies, obd_export::exp_refcount, obd_export::exp_reg_rpcs, obd_export::exp_replay_count, obd_export::exp_req_replay_queue, obd_export::exp_rpc_count, obd_export::exp_rpc_lock, obd_export::exp_sp_peer, obd_export::exp_stale_list, obd_export::exp_uncommitted_replies, obd_export::exp_uncommitted_replies_lock, obd_export::exp_uuid_hash, GOTO, portals_handle::h_link, hlist_unhashed(), INIT_HLIST_NODE, INIT_LIST_HEAD, LASSERT, LCONSOLE_WARN, list_add(), list_add_tail(), LUSTRE_SP_ANY, OBD_ALLOC_PTR, obd_destroy_export(), obd_device::obd_dev_lock, obd_device::obd_exports, obd_device::obd_exports_timed, OBD_FREE_PTR, obd_init_export(), obd_device::obd_name, obd_device::obd_num_exports, obd_device::obd_stopping, obd_timeout, obd_device::obd_uuid, obd_uuid_equals(), obd_device::obd_uuid_hash, RETURN, sptlrpc_flavor::sf_rpc, SPTLRPC_FLVR_INVALID, and obd_uuid::uuid.
Referenced by class_connect(), class_setup(), and tgt_clients_data_init().
struct obd_import* class_new_import (struct obd_device * obd) [read]
Definition at line 1049 of file genops.c.
References class_handle_hash(), class_incref(), portals_handle::h_link, obd_import::imp_at, obd_import::imp_committed_list, obd_import::imp_conn_list, obd_import::imp_delayed_list, obd_import::imp_handle, obd_import::imp_inflight, obd_import::imp_inval_count, obd_import::imp_known_replied_xid, obd_import::imp_last_success_conn, obd_import::imp_lock, obd_import::imp_msg_magic, obd_import::imp_obd, obd_import::imp_pinger_chain, obd_import::imp_recovery_waitq, obd_import::imp_refcount, obd_import::imp_replay_cursor, obd_import::imp_replay_inflight, obd_import::imp_replay_list, obd_import::imp_sec_mutex, obd_import::imp_sending_list, obd_import::imp_state, obd_import::imp_unregistering, obd_import::imp_unreplied_list, obd_import::imp_zombie_chain, init_imp_at(), INIT_LIST_HEAD, LUSTRE_IMP_NEW, LUSTRE_MSG_MAGIC_V2, and OBD_ALLOC.
Referenced by client_obd_setup().
struct obd_device* class_newdev (const char * type_name, const char * name) [read]
Create a new obd device.
Find an empty slot in obd_devs[], create a new obd device in it.
Parameters:
[in] type_name obd device type string.
[in] name obd device name.
Return values:
NULL if create fails, otherwise return the obd device pointer created.
Definition at line 302 of file genops.c.
References CDEBUG, CERROR, class_devno_max(), class_get_type(), class_num2obd(), class_put_type(), D_IOCTL, ENTRY, GOTO, LASSERT, LASSERTF, MAX_OBD_NAME, obd_device::obd_dev_lock, obd_dev_lock, obd_device_alloc(), obd_device_free(), OBD_DEVICE_MAGIC, obd_devs, obd_device::obd_magic, obd_device::obd_minor, obd_device::obd_name, obd_device::obd_type, and RETURN.
Referenced by class_attach().
int class_notify_sptlrpc_conf (const char * fsname, int namelen)
to notify sptlrpc log for fsname has changed, let every relevant OBD adjust sptlrpc settings accordingly.
Definition at line 614 of file genops.c.
References class_decref(), class_devno_max(), class_incref(), class_num2obd(), KEY_SPTLRPC_CONF, LASSERT, LUSTRE_LWP_NAME, LUSTRE_MDC_NAME, LUSTRE_MDT_NAME, LUSTRE_OSC_NAME, LUSTRE_OSP_NAME, LUSTRE_OST_NAME, obd_device::obd_dev_lock, obd_device::obd_name, obd_device::obd_self_export, obd_set_info_async(), obd_device::obd_set_up, obd_device::obd_stopping, obd_device::obd_type, and obd_type::typ_name.
Referenced by mgc_process_cfg_log().
struct obd_device* class_num2obd (int num) [read]
Get obd device from obd_devs[].
Parameters:
num [in] array index
Return values:
NULL if obd_devs[num] does not contains an obd device otherwise return the obd device there.
Definition at line 475 of file genops.c.
References class_devno_max(), LASSERTF, OBD_DEVICE_MAGIC, obd_devs, obd_device::obd_magic, and obd_device::obd_minor.
Referenced by class_devices_in_group(), class_find_client_obd(), class_handle_ioctl(), class_name2dev(), class_name2obd(), class_newdev(), class_notify_sptlrpc_conf(), class_obd_list(), class_setup(), class_uuid2dev(), class_uuid2obd(), get_devices_count(), and obd_device_list_seq_show().
void class_obd_list (void)
Definition at line 516 of file genops.c.
References class_devno_max(), class_num2obd(), D_CONFIG, LCONSOLE, obd_device::obd_attached, obd_device::obd_dev_lock, obd_device::obd_name, obd_device::obd_refcount, obd_device::obd_set_up, obd_device::obd_stopping, obd_device::obd_type, obd_device::obd_uuid, status, obd_type::typ_name, and obd_uuid::uuid.
void class_put_type (struct obd_type * type)
Definition at line 156 of file genops.c.
References LASSERT, obd_ops::o_owner, obd_type::obd_type_lock, obd_type::typ_dt_ops, and obd_type::typ_refcnt.
Referenced by class_newdev(), class_release_dev(), and lu_stack_fini().
int class_register_type (struct obd_ops * dt_ops, struct md_ops * md_ops, bool enable_proc, struct lprocfs_vars * vars, const char * name, struct lu_device_type * ldt)
Definition at line 167 of file genops.c.
References CDEBUG, CLASS_MAX_NAME, class_search_type(), D_IOCTL, ENTRY, GOTO, LASSERT, list_add(), lprocfs_register(), lu_device_type_init(), OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, obd_type::obd_type_lock, obd_types, obd_types_lock, proc_lustre_root, RETURN, strnlen, obd_type::typ_chain, obd_type::typ_dt_ops, obd_type::typ_lu, obd_type::typ_md_ops, obd_type::typ_name, and obd_type::typ_procroot.
Referenced by llog_test_init(), lmv_init(), lod_init(), lov_init(), mdc_init(), mdd_init(), mds_mod_init(), mdt_init(), mgc_init(), mgs_init(), obdecho_init(), ofd_init(), osc_init(), osd_init(), osp_init(), ost_init(), and qmt_glb_init().
void class_release_dev (struct obd_device * obd)
Definition at line 381 of file genops.c.
References CDEBUG, class_put_type(), D_INFO, LASSERT, LASSERTF, obd_dev_lock, obd_device_free(), OBD_DEVICE_MAGIC, obd_devs, obd_device::obd_magic, obd_device::obd_minor, obd_device::obd_name, obd_device::obd_type, and obd_type::typ_name.
Referenced by class_attach(), and class_decref().
struct obd_type* class_search_type (const char * name) [read]
Definition at line 103 of file genops.c.
References list_entry, list_for_each, obd_types, obd_types_lock, obd_type::typ_chain, and obd_type::typ_name.
Referenced by class_get_type(), class_register_type(), class_unregister_type(), lod_init(), lov_init(), lov_setup(), mdd_procfs_init(), osc_init(), osc_setup(), osp_init(), qmt_device_init0(), and server_stop_servers().
void class_unlink_export (struct obd_export * exp)
Definition at line 932 of file genops.c.
References cfs_hash_del(), cfs_hash_getref(), cfs_hash_putref(), class_handle_unhash(), obd_export::exp_client_uuid, obd_export::exp_gen_hash, obd_export::exp_handle, obd_export::exp_obd, obd_export::exp_obd_chain, obd_export::exp_obd_chain_timed, obd_export::exp_uuid_hash, hlist_unhashed(), LASSERT, lsd_client_data::lcd_generation, list_del_init(), list_move(), obd_device::obd_dev_lock, obd_device::obd_gen_hash, obd_device::obd_num_exports, obd_stale_export_num, obd_stale_export_put(), obd_device::obd_unlinked_exports, obd_device::obd_uuid_hash, and tg_export_data::ted_lcd.
Referenced by class_decref(), class_disconnect(), class_setup(), and tgt_clients_data_init().
int class_unregister_type (const char * name)
Definition at line 246 of file genops.c.
References CERROR, class_search_type(), ENTRY, list_del(), lprocfs_remove(), lu_device_type_fini(), OBD_FREE, OBD_FREE_PTR, obd_types_lock, proc_lustre_root, RETURN, obd_type::typ_chain, obd_type::typ_dt_ops, obd_type::typ_lu, obd_type::typ_md_ops, obd_type::typ_name, obd_type::typ_procroot, obd_type::typ_procsym, and obd_type::typ_refcnt.
Referenced by llog_test_exit(), lmv_exit(), lod_exit(), lov_exit(), mdc_exit(), mdd_exit(), mds_mod_exit(), mdt_exit(), mgc_exit(), mgs_exit(), obdecho_exit(), obdecho_init(), ofd_exit(), osc_exit(), osc_init(), osd_exit(), osp_exit(), osp_init(), ost_exit(), and qmt_glb_fini().
int class_uuid2dev (struct obd_uuid * uuid)
Definition at line 439 of file genops.c.
References class_devno_max(), class_num2obd(), LASSERT, obd_device::obd_dev_lock, OBD_DEVICE_MAGIC, obd_device::obd_magic, obd_device::obd_uuid, and obd_uuid_equals().
Referenced by class_handle_ioctl(), and class_uuid2obd().
struct obd_device* class_uuid2obd (struct obd_uuid * uuid) [read]
Definition at line 458 of file genops.c.
References class_num2obd(), and class_uuid2dev().
Referenced by gss_svc_handle_init().
void dump_exports (struct obd_device * obd, int locks)
Definition at line 1565 of file genops.c.
References obd_export::exp_obd_chain, list_for_each_entry, obd_device::obd_delayed_exports, obd_device::obd_dev_lock, obd_device::obd_exports, obd_device::obd_unlinked_exports, obd_zombie_exports, obd_zombie_impexp_lock, and print_export_data().
Referenced by class_cleanup(), and obd_exports_barrier().
static void export_handle_addref (void * export) [static]
Definition at line 793 of file genops.c.
References class_export_get().
int get_devices_count (void)
Get obd devices count.
Device in any state are counted
Return values:
obd device count
Definition at line 500 of file genops.c.
References class_devno_max(), class_num2obd(), and obd_device::obd_dev_lock.
Referenced by only_mgs_is_running().
static void import_handle_addref (void * import) [static]
Definition at line 995 of file genops.c.
References class_import_get().
static void init_imp_at (struct imp_at * at) [static]
Definition at line 1037 of file genops.c.
References AT_FLG_NOHIST, at_init(), imp_at::iat_net_latency, imp_at::iat_service_estimate, IMP_AT_MAX_PORTALS, and INITIAL_CONNECT_TIMEOUT.
Referenced by class_new_import().
void* kuc_alloc (int payload_len, int transport, int type)
Definition at line 1914 of file genops.c.
References kuc_len(), KUC_MAGIC, kuc_hdr::kuc_magic, kuc_hdr::kuc_msglen, kuc_hdr::kuc_msgtype, kuc_hdr::kuc_transport, and OBD_ALLOC.
Referenced by mdt_hsm_agent_send().
void kuc_free (void * p, int payload_len) [inline]
Definition at line 1933 of file genops.c.
References kuc_len(), kuc_ptr(), and OBD_FREE.
Referenced by mdt_hsm_agent_send().
int kuc_len (int payload_len)
Definition at line 1893 of file genops.c.
Referenced by kuc_alloc(), kuc_free(), and mdt_hsm_agent_send().
struct kuc_hdr* kuc_ptr (void * p) [read]
Definition at line 1903 of file genops.c.
References KUC_MAGIC, kuc_hdr::kuc_magic, and LASSERT.
Referenced by kuc_free(), and mdt_hsm_agent_send().
void obd_cleanup_caches (void)
Definition at line 657 of file genops.c.
References ENTRY, EXIT, import_cachep, obd_device_cachep, and obdo_cachep.
Referenced by obd_init_caches(), and obdclass_exit().
static struct obd_device* obd_device_alloc (void) [static, read]
Definition at line 78 of file genops.c.
References obd_device_cachep, OBD_DEVICE_MAGIC, obd_device::obd_magic, and OBD_SLAB_ALLOC_PTR_GFP.
Referenced by class_newdev().
static void obd_device_free (struct obd_device * obd) [static]
Definition at line 89 of file genops.c.
References CERROR, LASSERT, LASSERTF, LBUG, lu_ref_fini(), obd_device_cachep, OBD_DEVICE_MAGIC, obd_device::obd_force, obd_device::obd_magic, obd_device::obd_namespace, obd_device::obd_reference, and OBD_SLAB_FREE_PTR.
Referenced by class_newdev(), and class_release_dev().
int obd_export_evict_by_nid (struct obd_device * obd, const char * nid)
Definition at line 1442 of file genops.c.
References ptlrpc_connection::c_peer, CDEBUG, cfs_hash_getref(), cfs_hash_lookup(), cfs_hash_putref(), class_export_put(), class_fail_export(), D_HA, obd_export::exp_client_uuid, obd_export::exp_connection, LASSERTF, LCONSOLE_WARN, libcfs_nid2str(), libcfs_str2nid(), lnet_process_id_t::nid, nid_hash(), nid_key(), obd_device::obd_dev_lock, obd_export_nid2str(), obd_device::obd_name, obd_device::obd_nid_hash, obd_device::obd_self_export, obd_device::obd_stopping, and obd_uuid2str().
Referenced by lprocfs_mds_evict_client_seq_write(), mdt_set_info(), and ofd_set_info_hdl().
int obd_export_evict_by_uuid (struct obd_device * obd, const char * uuid)
Definition at line 1490 of file genops.c.
References CERROR, cfs_hash_getref(), cfs_hash_lookup(), cfs_hash_putref(), class_export_put(), class_fail_export(), CWARN, obd_export::exp_client_uuid, obd_device::obd_dev_lock, obd_device::obd_name, obd_device::obd_stopping, obd_str2uuid(), obd_device::obd_uuid, obd_uuid_equals(), obd_device::obd_uuid_hash, obd_uuid::uuid, and uuid_hash().
char* obd_export_nid2str (struct obd_export * exp)
Definition at line 1433 of file genops.c.
References ptlrpc_connection::c_peer, obd_export::exp_connection, libcfs_nid2str(), and lnet_process_id_t::nid.
Referenced by class_disconnect_export_list(), mdt_reconstruct_create(), mdt_reconstruct_open(), mdt_reconstruct_setattr(), mgs_target_reg(), obd_export_evict_by_nid(), ofd_echo_setattr(), ofd_parse_connect_data(), ofd_setattr_hdl(), ping_evictor_main(), print_export_data(), ptlrpc_update_export_timer(), tgt_brw_read(), tgt_brw_write(), tgt_io_data_unpack(), and tgt_validate_obdo().
void obd_exports_barrier (struct obd_device * obd)
Definition at line 1583 of file genops.c.
References cfs_time_seconds(), dump_exports(), LASSERT, LCONSOLE_WARN, list_empty(), obd_device::obd_dev_lock, obd_device::obd_exports, obd_device::obd_name, obd_device::obd_refcount, and obd_device::obd_unlinked_exports.
Referenced by mdt_fini(), mgs_device_fini(), and ofd_fini().
__u16 obd_get_max_mod_rpcs_in_flight (struct client_obd * cli)
Definition at line 2090 of file genops.c.
References client_obd::cl_max_mod_rpcs_in_flight.
__u32 obd_get_max_rpcs_in_flight (struct client_obd * cli)
Definition at line 2032 of file genops.c.
References client_obd::cl_max_rpcs_in_flight.
__u16 obd_get_mod_rpc_slot (struct client_obd * cli, __u32 opc, struct lookup_intent * it)
Definition at line 2229 of file genops.c.
References CDEBUG, client_obd::cl_close_rpcs_in_flight, client_obd::cl_import, client_obd::cl_max_mod_rpcs_in_flight, client_obd::cl_mod_rpcs_hist, client_obd::cl_mod_rpcs_in_flight, client_obd::cl_mod_rpcs_lock, client_obd::cl_mod_rpcs_waitq, client_obd::cl_mod_tag_bitmap, D_RPCTRACE, obd_import::imp_obd, IT_GETATTR, IT_LAYOUT, IT_LOOKUP, lookup_intent::it_op, IT_READDIR, l_wait_event, LASSERT, lprocfs_oh_tally(), LWI_INTR, max, MDS_CLOSE, OBD_MAX_RIF_MAX, obd_mod_rpc_slot_avail(), obd_mod_rpc_slot_avail_locked(), and obd_device::obd_name.
Referenced by mdc_get_mod_rpc_slot().
int obd_get_request_slot (struct client_obd * cli)
Definition at line 1965 of file genops.c.
References client_obd::cl_loi_list_lock, client_obd::cl_loi_read_list, client_obd::cl_max_rpcs_in_flight, client_obd::cl_r_in_flight, l_wait_event, LASSERT, list_add_tail(), list_del(), list_empty(), LWI_INTR, LWI_ON_SIGNAL_NOOP, obd_request_slot_avail(), obd_request_slot_waiter::orsw_entry, obd_request_slot_waiter::orsw_signaled, and obd_request_slot_waiter::orsw_waitq.
Referenced by fld_client_rpc(), mdc_enqueue(), mdc_intent_getattr_async(), mdc_queue_wait(), and osp_send_update_req().
int obd_init_caches (void)
Definition at line 676 of file genops.c.
References ENTRY, GOTO, import_cachep, LASSERT, obd_cleanup_caches(), obd_device_cachep, obdo_cachep, and RETURN.
Referenced by obdclass_init().
static bool obd_mod_rpc_slot_avail (struct client_obd * cli, bool close_req) [inline, static]
Definition at line 2210 of file genops.c.
References client_obd::cl_mod_rpcs_lock, and obd_mod_rpc_slot_avail_locked().
Referenced by obd_get_mod_rpc_slot().
static bool obd_mod_rpc_slot_avail_locked (struct client_obd * cli, bool close_req) [inline, static]
Definition at line 2195 of file genops.c.
References client_obd::cl_close_rpcs_in_flight, client_obd::cl_max_mod_rpcs_in_flight, and client_obd::cl_mod_rpcs_in_flight.
Referenced by obd_get_mod_rpc_slot(), and obd_mod_rpc_slot_avail().
int obd_mod_rpc_stats_seq_show (struct client_obd * cli, struct seq_file * seq)
Definition at line 2146 of file genops.c.
References client_obd::cl_mod_rpcs_hist, client_obd::cl_mod_rpcs_in_flight, client_obd::cl_mod_rpcs_lock, lprocfs_oh_sum(), OBD_HIST_MAX, obd_histogram::oh_buckets, and pct.
void obd_put_mod_rpc_slot (struct client_obd * cli, __u32 opc, struct lookup_intent * it, __u16 tag)
Definition at line 2281 of file genops.c.
References client_obd::cl_close_rpcs_in_flight, client_obd::cl_mod_rpcs_in_flight, client_obd::cl_mod_rpcs_lock, client_obd::cl_mod_rpcs_waitq, client_obd::cl_mod_tag_bitmap, IT_GETATTR, IT_LAYOUT, IT_LOOKUP, lookup_intent::it_op, IT_READDIR, LASSERT, MDS_CLOSE, and OBD_MAX_RIF_MAX.
Referenced by mdc_put_mod_rpc_slot().
void obd_put_request_slot (struct client_obd * cli)
Definition at line 2012 of file genops.c.
References client_obd::cl_loi_list_lock, client_obd::cl_loi_read_list, client_obd::cl_max_rpcs_in_flight, client_obd::cl_r_in_flight, likely, list_del_init(), list_empty(), list_entry, list_head::next, obd_request_slot_waiter::orsw_entry, and obd_request_slot_waiter::orsw_waitq.
Referenced by fld_client_rpc(), mdc_enqueue(), mdc_intent_getattr_async(), mdc_intent_getattr_async_interpret(), mdc_queue_wait(), and osp_update_interpret().
static bool obd_request_slot_avail (struct client_obd * cli, struct obd_request_slot_waiter * orsw) [static]
Definition at line 1946 of file genops.c.
References client_obd::cl_loi_list_lock, list_empty(), and obd_request_slot_waiter::orsw_entry.
Referenced by obd_get_request_slot().
int obd_set_max_mod_rpcs_in_flight (struct client_obd * cli, __u16 max)
Definition at line 2096 of file genops.c.
References CERROR, client_obd::cl_import, client_obd::cl_max_mod_rpcs_in_flight, client_obd::cl_max_rpcs_in_flight, client_obd::cl_mod_rpcs_lock, client_obd::cl_mod_rpcs_waitq, obd_import::imp_connect_data, obd_import::imp_obd, OBD_CONNECT_MULTIMODRPCS, OBD_MAX_RIF_MAX, obd_device::obd_name, obd_connect_data::ocd_connect_flags, and obd_connect_data::ocd_maxmodrpcs.
Referenced by obd_set_max_rpcs_in_flight().
int obd_set_max_rpcs_in_flight (struct client_obd * cli, __u32 max)
Definition at line 2038 of file genops.c.
References CERROR, client_obd::cl_import, client_obd::cl_loi_list_lock, client_obd::cl_loi_read_list, client_obd::cl_max_rpcs_in_flight, client_obd::cl_r_in_flight, obd_import::imp_obd, list_del_init(), list_empty(), list_entry, LUSTRE_MDC_NAME, list_head::next, OBD_MAX_RIF_MAX, obd_device::obd_name, obd_set_max_mod_rpcs_in_flight(), obd_device::obd_type, obd_request_slot_waiter::orsw_entry, obd_request_slot_waiter::orsw_waitq, and obd_type::typ_name.
void obd_stale_export_adjust (struct obd_export * exp)
Adjust the position of the export in the stale list, i.e.
move to the head of the list if is needed.
Definition at line 1812 of file genops.c.
References obd_export::exp_bl_list, obd_export::exp_bl_list_lock, obd_export::exp_stale_list, LASSERT, list_empty(), list_move(), obd_stale_export_lock, and obd_stale_exports.
struct obd_export* obd_stale_export_get (void) [read]
Definition at line 1757 of file genops.c.
References CDEBUG, D_DLMTRACE, ENTRY, obd_export::exp_stale_list, list_del_init(), list_empty(), list_entry, list_head::next, obd_stale_export_lock, obd_stale_export_num, obd_stale_exports, and RETURN.
Referenced by ldlm_bl_get_work().
void obd_stale_export_put (struct obd_export * exp)
Definition at line 1778 of file genops.c.
References CDEBUG, class_export_put(), D_DLMTRACE, ENTRY, EXIT, obd_export::exp_bl_list, obd_export::exp_bl_list_lock, obd_export::exp_lock_hash, obd_export::exp_stale_list, cfs_hash::hs_count, LASSERT, list_add(), list_add_tail(), list_empty(), obd_stale_export_lock, obd_stale_export_num, and obd_stale_exports.
Referenced by class_unlink_export(), ldlm_bl_get_work(), and ldlm_bl_thread_exports().
void obd_zombie_barrier (void)
wait when obd_zombie import/export queues become empty
Definition at line 1745 of file genops.c.
References current_pid, l_wait_event, and obd_zombie_is_idle().
Referenced by lustre_fill_super(), lustre_put_lsi(), mdt_fini(), mgs_device_fini(), ofd_fini(), osc_precleanup(), and server_put_super().
static void obd_zombie_export_add (struct obd_export * exp) [static]
Add export to the obd_zombe thread and notify it.
Definition at line 1687 of file genops.c.
References obd_export::exp_obd, obd_export::exp_obd_chain, LASSERT, list_add(), list_del_init(), list_empty(), obd_device::obd_dev_lock, obd_stale_export_num, obd_zombie_exports, obd_zombie_impexp_lock, and obd_zombie_impexp_notify().
Referenced by class_export_put().
static int obd_zombie_impexp_check (void * arg) [static]
check for work for kill zombie import/export thread.
Definition at line 1672 of file genops.c.
References obd_zombie_impexp_lock, OBD_ZOMBIE_STOP, and RETURN.
Referenced by obd_zombie_impexp_thread().
void obd_zombie_impexp_cull (void)
kill zombie imports and exports
Definition at line 1613 of file genops.c.
References class_export_destroy(), class_import_destroy(), ENTRY, EXIT, obd_export::exp_obd_chain, list_del_init(), list_empty(), list_entry, list_head::next, obd_zombie_exports, obd_zombie_impexp_lock, and obd_zombie_imports.
Referenced by obd_zombie_impexp_thread().
int obd_zombie_impexp_init (void)
start destroy zombie import/export thread
Definition at line 1860 of file genops.c.
References INIT_LIST_HEAD, obd_zombie_exports, obd_zombie_impexp_lock, obd_zombie_impexp_thread(), obd_zombie_imports, obd_zombie_start, obd_zombie_stop, and RETURN.
Referenced by obdclass_init().
static void obd_zombie_impexp_notify (void) [static]
notify import/export destroy thread about new zombie.
Definition at line 1718 of file genops.c.
Referenced by obd_zombie_export_add(), obd_zombie_impexp_stop(), and obd_zombie_import_add().
void obd_zombie_impexp_stop (void)
stop destroy zombie import/export thread
Definition at line 1883 of file genops.c.
References obd_zombie_impexp_notify(), obd_zombie_stop, and OBD_ZOMBIE_STOP.
Referenced by obdclass_exit().
static int obd_zombie_impexp_thread (void * unused) [static]
destroy zombie export/import thread.
Definition at line 1830 of file genops.c.
References current_pid, l_wait_event, obd_zombie_impexp_check(), obd_zombie_impexp_cull(), obd_zombie_start, obd_zombie_stop, OBD_ZOMBIE_STOP, and RETURN.
Referenced by obd_zombie_impexp_init().
static void obd_zombie_import_add (struct obd_import * imp) [static]
Add import to the obd_zombe thread and notify it.
Definition at line 1704 of file genops.c.
References obd_import::imp_sec, obd_import::imp_zombie_chain, LASSERT, list_add(), list_empty(), obd_zombie_impexp_lock, obd_zombie_impexp_notify(), and obd_zombie_imports.
Referenced by class_import_put().
static int obd_zombie_is_idle (void) [static]
check whether obd_zombie is idle
Definition at line 1731 of file genops.c.
References LASSERT, obd_zombie_impexp_lock, and OBD_ZOMBIE_STOP.
Referenced by obd_zombie_barrier().
static void print_export_data (struct obd_export * exp, const char * status, int locks) [static]
Definition at line 1534 of file genops.c.
References CDEBUG, D_HA, obd_export::exp_cb_count, obd_export::exp_client_uuid, obd_export::exp_delayed, obd_export::exp_disconnected, obd_export::exp_failed, obd_export::exp_last_committed, obd_export::exp_lock, obd_export::exp_locks_count, obd_export::exp_obd, obd_export::exp_outstanding_replies, obd_export::exp_refcount, obd_export::exp_rpc_count, list_for_each_entry, LPU64, obd_export_nid2str(), obd_device::obd_name, ptlrpc_reply_state::rs_exp_list, and obd_uuid::uuid.
Referenced by class_disconnect_stale_exports(), and dump_exports().
Variable Documentation
struct portals_handle_ops export_handle_ops [static]
Initial value:
 {
        .hop_addref = export_handle_addref,
        .hop_free   = NULL,
}
Definition at line 798 of file genops.c.
struct kmem_cache* import_cachep [static]
Definition at line 55 of file genops.c.
Referenced by obd_cleanup_caches(), and obd_init_caches().
struct portals_handle_ops import_handle_ops [static]
Initial value:
 {
        .hop_addref = import_handle_addref,
        .hop_free   = NULL,
}
Definition at line 1000 of file genops.c.
struct kmem_cache* obd_device_cachep [static]
Definition at line 52 of file genops.c.
Referenced by obd_cleanup_caches(), obd_device_alloc(), obd_device_free(), and obd_init_caches().
spinlock_t obd_stale_export_lock
Definition at line 68 of file genops.c.
Referenced by obd_stale_export_adjust(), obd_stale_export_get(), obd_stale_export_put(), and obdclass_init().
atomic_t obd_stale_export_num
Definition at line 69 of file genops.c.
Referenced by class_unlink_export(), obd_stale_export_get(), obd_stale_export_put(), obd_zombie_export_add(), and obdclass_init().
struct list_head obd_stale_exports
Definition at line 67 of file genops.c.
Referenced by obd_stale_export_adjust(), obd_stale_export_get(), obd_stale_export_put(), obdclass_exit(), and obdclass_init().
spinlock_t obd_types_lock
Definition at line 50 of file genops.c.
Referenced by class_register_type(), class_search_type(), class_unregister_type(), lu_device_type_fini(), lu_device_type_init(), and obdclass_init().
struct list_head obd_zombie_exports [static]
Definition at line 58 of file genops.c.
Referenced by dump_exports(), obd_zombie_export_add(), obd_zombie_impexp_cull(), and obd_zombie_impexp_init().
unsigned long obd_zombie_flags [static]
Definition at line 1661 of file genops.c.
spinlock_t obd_zombie_impexp_lock [static]
Definition at line 59 of file genops.c.
Referenced by dump_exports(), obd_zombie_export_add(), obd_zombie_impexp_check(), obd_zombie_impexp_cull(), obd_zombie_impexp_init(), obd_zombie_import_add(), and obd_zombie_is_idle().
struct list_head obd_zombie_imports [static]
Definition at line 57 of file genops.c.
Referenced by obd_zombie_impexp_cull(), obd_zombie_impexp_init(), and obd_zombie_import_add().
pid_t obd_zombie_pid [static]
Definition at line 1663 of file genops.c.
struct completion obd_zombie_start [static]
Definition at line 1659 of file genops.c.
Referenced by obd_zombie_impexp_init(), and obd_zombie_impexp_thread().
struct completion obd_zombie_stop [static]
Definition at line 1660 of file genops.c.
Referenced by obd_zombie_impexp_init(), obd_zombie_impexp_stop(), and obd_zombie_impexp_thread().
wait_queue_head_t obd_zombie_waitq [static]
Definition at line 1662 of file genops.c.
struct kmem_cache* obdo_cachep
Definition at line 53 of file genops.c.
Referenced by obd_cleanup_caches(), and obd_init_caches().
int(* ptlrpc_put_connection_superhack)(struct ptlrpc_connection *c)
Referenced by class_export_destroy(), class_import_destroy(), and ptlrpc_init().
int zombies_count = 0 [static]
Definition at line 1608 of file genops.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.