Lustre: lustre/llite/glimpse.c File Reference
lustre/llite/glimpse.c File Reference
#include <libcfs/libcfs.h>
#include <obd_class.h>
#include <obd_support.h>
#include <obd.h>
#include <lustre_dlm.h>
#include <lustre_mdc.h>
#include <linux/pagemap.h>
#include <linux/file.h>
#include "cl_object.h"
#include "llite_internal.h"
#include "vvp_internal.h"
Functions
blkcnt_t dirty_cnt (struct inode *inode)
int cl_glimpse_lock (const struct lu_env *env, struct cl_io *io, struct inode *inode, struct cl_object *clob, int agl)
static int cl_io_get (struct inode *inode, struct lu_env **envout, struct cl_io **ioout, __u16 *refcheck)
int cl_glimpse_size0 (struct inode *inode, int agl)
Variables
static struct cl_lock_descr whole_file
Function Documentation
int cl_glimpse_lock (const struct lu_env * env, struct cl_io * io, struct inode * inode, struct cl_object * clob, int agl)
Definition at line 85 of file glimpse.c.
References CDEBUG, CEF_AGL, CEF_ASYNC, CEF_MUST, cl_lock_release(), cl_lock_request(), cl_lock_descr::cld_enq_flags, cl_lock_descr::cld_mode, cl_lock_descr::cld_obj, cl_lock::cll_descr, CLM_READ, cl_object::co_lu, D_DLMTRACE, DFID, dirty_cnt(), ENTRY, ll_merge_attr(), lu_object_fid(), PFID, RETURN, and vvp_env_lock().
Referenced by cl_glimpse_size0(), and vvp_prep_size().
int cl_glimpse_size0 (struct inode * inode, int agl)
Definition at line 171 of file glimpse.c.
References cl_io::ci_need_restart, cl_io::ci_obj, cl_io::ci_result, cl_io::ci_verify_layout, CIT_MISC, cl_env_put(), cl_glimpse_lock(), cl_io_fini(), cl_io_get(), cl_io_init(), ENTRY, OBD_FAIL_GLIMPSE_DELAY, OBD_FAIL_TIMEOUT, RETURN, and unlikely.
Referenced by cl_agl(), and cl_glimpse_size().
static int cl_io_get (struct inode * inode, struct lu_env ** envout, struct cl_io ** ioout, __u16 * refcheck) [static]
Definition at line 147 of file glimpse.c.
References cl_io::ci_obj, cl_env_get(), ll_i2info(), ll_inode_info::lli_clob, and vvp_env_thread_io().
Referenced by cl_glimpse_size0().
blkcnt_t dirty_cnt (struct inode * inode)
Definition at line 69 of file glimpse.c.
References cl_inode2vvp(), and vvp_object::vob_mmap_cnt.
Referenced by cl_glimpse_lock(), and vvp_object_glimpse().
Variable Documentation
struct cl_lock_descr whole_file [static]
Initial value:
 {
        .cld_start = 0,
        .cld_end   = CL_PAGE_EOF,
        .cld_mode  = CLM_READ
}
Definition at line 57 of file glimpse.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.