Lustre: lnet/klnds/gnilnd/gnilnd.c File Reference
lnet/klnds/gnilnd/gnilnd.c File Reference
#include "gnilnd.h"
Functions
int kgnilnd_thread_start (int(*fn)(void *arg), void *arg, char *name, int id)
int kgnilnd_start_sd_threads (void)
int kgnilnd_close_stale_conns_locked (kgn_peer_t *peer, kgn_conn_t *newconn)
int kgnilnd_conn_isdup_locked (kgn_peer_t *peer, kgn_conn_t *newconn)
int kgnilnd_create_conn (kgn_conn_t **connp, kgn_device_t *dev)
kgn_conn_t * kgnilnd_find_conn_locked (kgn_peer_t *peer)
kgn_conn_t * kgnilnd_find_or_create_conn_locked (kgn_peer_t *peer)
void kgnilnd_destroy_conn_ep (kgn_conn_t *conn)
void kgnilnd_destroy_conn (kgn_conn_t *conn)
void kgnilnd_peer_alive (kgn_peer_t *peer)
void kgnilnd_peer_notify (kgn_peer_t *peer, int error, int alive)
void kgnilnd_close_conn_locked (kgn_conn_t *conn, int error)
void kgnilnd_close_conn (kgn_conn_t *conn, int error)
void kgnilnd_complete_closed_conn (kgn_conn_t *conn)
int kgnilnd_set_conn_params (kgn_dgram_t *dgram)
int kgnilnd_create_peer_safe (kgn_peer_t **peerp, lnet_nid_t nid, kgn_net_t *net, int node_state)
void kgnilnd_destroy_peer (kgn_peer_t *peer)
void kgnilnd_add_purgatory_locked (kgn_conn_t *conn, kgn_peer_t *peer)
void kgnilnd_mark_for_detach_purgatory_all_locked (kgn_peer_t *peer)
void kgnilnd_detach_purgatory_locked (kgn_conn_t *conn, struct list_head *conn_list)
void kgnilnd_release_purgatory_list (struct list_head *conn_list)
void kgnilnd_peer_increase_reconnect_locked (kgn_peer_t *peer)
kgn_peer_t * kgnilnd_find_peer_locked (lnet_nid_t nid)
void kgnilnd_unlink_peer_locked (kgn_peer_t *peer)
int kgnilnd_get_peer_info (int index, kgn_peer_t **found_peer, lnet_nid_t *id, __u32 *nic_addr, int *refcount, int *connecting)
void kgnilnd_add_peer_locked (lnet_nid_t nid, kgn_peer_t *new_stub_peer, kgn_peer_t **peerp)
int kgnilnd_add_peer (kgn_net_t *net, lnet_nid_t nid, kgn_peer_t **peerp)
void kgnilnd_cancel_peer_connect_locked (kgn_peer_t *peer, struct list_head *zombies)
void kgnilnd_del_peer_locked (kgn_peer_t *peer, int error)
int kgnilnd_del_conn_or_peer (kgn_net_t *net, lnet_nid_t nid, int command, int error)
kgn_conn_t * kgnilnd_get_conn_by_idx (int index)
int kgnilnd_get_conn_info (kgn_peer_t *peer, int *device_id, __u64 *peerstamp, int *tx_seq, int *rx_seq, int *fmaq_len, int *nfma, int *nrdma)
int kgnilnd_close_peer_conns_locked (kgn_peer_t *peer, int why)
int kgnilnd_report_node_state (lnet_nid_t nid, int down)
int kgnilnd_ctl (lnet_ni_t *ni, unsigned int cmd, void *arg)
void kgnilnd_query (lnet_ni_t *ni, lnet_nid_t nid, cfs_time_t *when)
int kgnilnd_dev_init (kgn_device_t *dev)
void kgnilnd_dev_fini (kgn_device_t *dev)
int kgnilnd_base_startup (void)
void kgnilnd_base_shutdown (void)
int kgnilnd_startup (lnet_ni_t *ni)
void kgnilnd_shutdown (lnet_ni_t *ni)
static void __exit kgnilnd_exit (void)
static int __init kgnilnd_init (void)
MODULE_AUTHOR ("Cray, Inc. <nic@cray.com>")
MODULE_DESCRIPTION ("Gemini LNet Network Driver")
MODULE_VERSION (KGNILND_BUILD_REV)
MODULE_LICENSE ("GPL")
module_init (kgnilnd_init)
module_exit (kgnilnd_exit)
Variables
lnd_t the_kgnilnd
kgn_data_t kgnilnd_data
Function Documentation
int kgnilnd_add_peer (kgn_net_t * net, lnet_nid_t nid, kgn_peer_t ** peerp)
Definition at line 1393 of file gnilnd.c.
References CDEBUG, D_NET, ENTRY, kgn_data::kgn_net_rw_sem, kgn_data::kgn_peer_conn_lock, kgnilnd_add_peer_locked(), kgnilnd_create_peer_safe(), kgnilnd_get_node_state(), libcfs_nid2str(), LNET_NID_ANY, LNET_NIDADDR(), and RETURN.
Referenced by kgnilnd_ctl(), and kgnilnd_report_node_state().
void kgnilnd_add_peer_locked (lnet_nid_t nid, kgn_peer_t * new_stub_peer, kgn_peer_t ** peerp)
Definition at line 1362 of file gnilnd.c.
References kgn_peer::gnp_list, kgn_peer::gnp_net, kgn_peer::gnp_nid, kgn_data::kgn_peer_version, kgnilnd_find_peer_locked(), kgnilnd_nid2peerlist(), kgnilnd_peer_active(), kgnilnd_peer_decref, LASSERTF, libcfs_nid2str(), and list_add_tail().
Referenced by kgnilnd_add_peer(), kgnilnd_finish_connect(), and kgnilnd_launch_tx().
void kgnilnd_add_purgatory_locked (kgn_conn_t * conn, kgn_peer_t * peer)
Definition at line 1095 of file gnilnd.c.
References CDEBUG, D_NET, ENTRY, EXIT, kgn_conn::gnc_device, kgn_conn::gnc_fma_blk, kgn_conn::gnc_in_purgatory, kgn_conn::gnc_mbox_id, kgn_conn::gnc_mdd_list, kgn_fma_memblock::gnm_mbox_info, kgn_peer::gnp_nid, kgnilnd_count_list(), kgnilnd_peer_active(), kgnilnd_release_mbox(), LASSERTF, libcfs_nid2str(), list_empty(), kgn_mbox_info::mbx_add_purgatory, and kgn_mbox_info::mbx_prev_purg_nid.
Referenced by kgnilnd_close_conn_locked(), and kgnilnd_release_dgram().
void kgnilnd_base_shutdown (void)
Definition at line 2509 of file gnilnd.c.
References CDEBUG, CFS_FAIL_GNI_PAUSE_SHUTDOWN, CFS_FAIL_TIMEOUT, cfs_time_seconds(), D_MALLOC, D_NET, D_WARNING, ENTRY, EXIT, kgn_device::gnd_connd_peers, kgn_device::gnd_dgping_waitq, kgn_device::gnd_dgram_waitq, kgn_device::gnd_dgrams, kgn_device::gnd_ndgrams, GNILND_DEL_PEER, GNILND_INIT_NOTHING, kgn_data::kgn_cksum_map_pages, kgn_data::kgn_cksum_npages, kgn_data::kgn_conns, kgn_data::kgn_devices, kgn_data::kgn_dgram_cache, kgn_data::kgn_init, kgn_data::kgn_mbox_cache, kgn_data::kgn_nconns, kgn_data::kgn_ndevs, kgn_tunables::kgn_net_hash_size, kgn_data::kgn_net_rw_sem, kgn_data::kgn_nets, kgn_data::kgn_npeers, kgn_data::kgn_nthreads, kgn_tunables::kgn_peer_hash_size, kgn_data::kgn_peers, kgn_data::kgn_reaper_lock, kgn_data::kgn_reaper_waitq, kgn_data::kgn_ruhroh_running, kgn_data::kgn_ruhroh_shutdown, kgn_data::kgn_ruhroh_waitq, kgn_data::kgn_rx_cache, kgn_data::kgn_shutdown, kgn_data::kgn_tx_cache, kgn_data::kgn_tx_phys_cache, kgn_data::kgn_wc_kill, kgnilnd_cancel_dgrams(), kgnilnd_cancel_wc_dgrams(), kgnilnd_del_conn_or_peer(), kgnilnd_dev_fini(), kgnilnd_free_phys_fmablk(), kgnilnd_schedule_device(), kgnilnd_tunables, kgnilnd_unmap_fma_blocks(), kgnilnd_wait_for_canceled_dgrams(), kgnilnd_wakeup_rca_thread(), LASSERT, LASSERTF, LIBCFS_FREE, libcfs_kmemory, list_empty(), and LNET_NID_ANY.
Referenced by kgnilnd_base_startup(), and kgnilnd_shutdown().
int kgnilnd_base_startup (void)
Definition at line 2205 of file gnilnd.c.
References __u64, CDEBUG, CERROR, D_MALLOC, ENTRY, kgn_data::free_pages_limit, kgn_device::gnd_canceled_dgrams, kgn_device::gnd_conn_sem, kgn_device::gnd_connd_lock, kgn_device::gnd_connd_peers, kgn_device::gnd_cq_mutex, kgn_device::gnd_dgping_waitq, kgn_device::gnd_dgram_lock, kgn_device::gnd_dgram_waitq, kgn_device::gnd_dgrams, kgn_device::gnd_fma_buffs, kgn_device::gnd_fmablk_lock, kgn_device::gnd_fmablk_mutex, kgn_device::gnd_fmablk_vers, kgn_device::gnd_id, kgn_device::gnd_lock, kgn_device::gnd_map_list, kgn_device::gnd_map_lock, kgn_device::gnd_map_tx, kgn_device::gnd_ndgrams, kgn_device::gnd_neps, kgn_device::gnd_nfmablk, kgn_device::gnd_nwcdgrams, kgn_device::gnd_rdmaq, kgn_device::gnd_rdmaq_lock, kgn_device::gnd_rdmaq_timer, kgn_device::gnd_ready_conns, kgn_device::gnd_waitq, GNILND_INIT_ALL, GNILND_INIT_DATA, GNILND_INIT_NOTHING, GNILND_MAX_MSG_ID, GNILND_MAXDEVS, GOTO, INIT_LIST_HEAD, kgn_data::kgn_cksum_map_pages, kgn_data::kgn_cksum_npages, kgn_data::kgn_conns, kgn_data::kgn_connstamp, kgn_data::kgn_devices, kgn_data::kgn_dgram_cache, kgn_data::kgn_init, kgn_data::kgn_mbox_cache, kgn_data::kgn_ndevs, kgn_tunables::kgn_net_hash_size, kgn_data::kgn_net_rw_sem, kgn_data::kgn_nets, kgn_data::kgn_new_min_timeout, kgn_data::kgn_next_cqid, kgn_data::kgn_npending_conns, kgn_data::kgn_npending_detach, kgn_data::kgn_npending_unlink, kgn_data::kgn_nquiesce, kgn_data::kgn_peer_conn_lock, kgn_tunables::kgn_peer_hash_size, kgn_data::kgn_peers, kgn_data::kgn_peerstamp, kgn_data::kgn_quiesce_mutex, kgn_data::kgn_reaper_lock, kgn_data::kgn_reaper_waitq, kgn_data::kgn_rev_copy_buff, kgn_data::kgn_rev_length, kgn_data::kgn_rev_offset, kgn_data::kgn_ruhroh_waitq, kgn_data::kgn_rx_cache, kgn_tunables::kgn_sched_threads, kgn_tunables::kgn_thread_affinity, kgn_tunables::kgn_timeout, kgn_data::kgn_tx_cache, kgn_data::kgn_tx_phys_cache, kgnilnd_allocate_phys_fmablk(), kgnilnd_base_shutdown(), kgnilnd_check_kgni_version(), kgnilnd_dev_init(), kgnilnd_dgram_mover(), kgnilnd_dgram_waitq(), kgnilnd_reaper(), kgnilnd_ruhroh_thread(), kgnilnd_schedule_device_timer(), kgnilnd_scheduler(), kgnilnd_setup_wildcard_dgram(), kgnilnd_start_rca_thread(), kgnilnd_start_sd_threads(), kgnilnd_thread_start(), kgnilnd_tunables, LASSERT, LASSERTF, LIBCFS_ALLOC, libcfs_kmemory, LNET_MAX_IOV, and RETURN.
Referenced by kgnilnd_startup().
void kgnilnd_cancel_peer_connect_locked (kgn_peer_t * peer, struct list_head * zombies)
Definition at line 1433 of file gnilnd.c.
References kgn_device::gnd_connd_lock, GNILND_PEER_IDLE, GNILND_PEER_NEEDS_DEATH, GNILND_PEER_POSTING, GNILND_TX_ALLOCD, kgn_net::gnn_dev, kgn_peer::gnp_connd_list, kgn_peer::gnp_connecting, kgn_peer::gnp_last_dgram_errno, kgn_peer::gnp_net, kgn_peer::gnp_nid, kgn_peer::gnp_tx_queue, kgnilnd_find_and_cancel_dgram(), kgnilnd_peer_decref, kgnilnd_tx_del_state_locked(), LASSERTF, libcfs_nid2str(), list_add_tail(), list_del_init(), list_empty(), list_for_each_entry_safe, and kgn_tx::tx_list.
Referenced by kgnilnd_check_peer_timeouts_locked(), kgnilnd_del_conn_or_peer(), and kgnilnd_report_node_state().
void kgnilnd_close_conn (kgn_conn_t * conn, int error)
Definition at line 701 of file gnilnd.c.
References kgn_conn::gnc_state, GNILND_CONN_ESTABLISHED, kgn_data::kgn_peer_conn_lock, and kgnilnd_close_conn_locked().
Referenced by kgnilnd_check_fma_rx(), kgnilnd_check_rdma_cq(), kgnilnd_process_fmaq(), kgnilnd_recv(), and kgnilnd_tx_should_retry().
void kgnilnd_close_conn_locked (kgn_conn_t * conn, int error)
Definition at line 620 of file gnilnd.c.
References CDEBUG, CFS_FAIL_CHECK, CFS_FAIL_GNI_RDMA_CQ_ERROR, CNETERR, D_NET, ENTRY, EXIT, kgn_conn::gnc_error, kgn_conn::gnc_hashlist, kgn_conn::gnc_last_rx, kgn_conn::gnc_last_rx_cq, kgn_conn::gnc_list, kgn_conn::gnc_peer, kgn_conn::gnc_peer_error, kgn_conn::gnc_state, GNILND_CONN_CLOSED, GNILND_CONN_CLOSING, GNILND_CONN_ESTABLISHED, GNILND_RCA_NODE_UP, kgn_peer::gnp_dirty_eps, kgn_peer::gnp_down, kgn_peer::gnp_last_errno, kgn_peer::gnp_nid, kgn_data::kgn_conn_version, kgn_data::kgn_in_reset, kgnilnd_add_purgatory_locked(), kgnilnd_admin_addref, kgnilnd_check_purgatory_conn(), kgnilnd_conn_clean_errno(), kgnilnd_conn_decref, kgnilnd_conn_state2str(), kgnilnd_schedule_conn, LASSERT, LASSERTF, libcfs_nid2str(), list_del_init(), list_empty(), and unlikely.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_check_fma_send_cq(), kgnilnd_check_peer_timeouts_locked(), kgnilnd_close_conn(), kgnilnd_close_peer_conns_locked(), kgnilnd_close_stale_conns_locked(), and kgnilnd_report_node_state().
int kgnilnd_close_peer_conns_locked (kgn_peer_t * peer, int why)
Definition at line 1683 of file gnilnd.c.
References kgn_conn::gnc_needs_closing, kgn_conn::gnc_state, GNILND_CONN_ESTABLISHED, kgn_peer::gnp_conns, kgn_data::kgn_npending_conns, kgnilnd_admin_addref, kgnilnd_close_conn_locked(), list_entry, and list_for_each_safe.
Referenced by kgnilnd_del_conn_or_peer(), and kgnilnd_del_peer_locked().
int kgnilnd_close_stale_conns_locked (kgn_peer_t * peer, kgn_conn_t * newconn)
Definition at line 93 of file gnilnd.c.
References CDEBUG, CWARN, D_NET, kgn_conn::gnc_device, kgn_conn::gnc_my_connstamp, kgn_conn::gnc_peer_connstamp, kgn_conn::gnc_peerstamp, kgn_conn::gnc_state, GNILND_CONN_ESTABLISHED, kgn_net::gnn_ni, kgn_peer::gnp_conns, kgn_peer::gnp_net, kgn_peer::gnp_nid, kgnilnd_close_conn_locked(), LASSERTF, libcfs_nid2str(), list_entry, list_for_each_safe, LPU64, LPX64, lnet_ni::ni_nid, and RETURN.
Referenced by kgnilnd_finish_connect(), and kgnilnd_process_nak().
void kgnilnd_complete_closed_conn (kgn_conn_t * conn)
Definition at line 713 of file gnilnd.c.
References CDEBUG, CFS_FAIL_CHECK, CFS_FAIL_GNI_FINISH_PURG, CFS_FAIL_GNI_SCHEDULE_COMPLETE, CFS_RACE, CNETERR, D_NET, D_NETERROR, ENTRY, EXIT, kgn_conn::gnc_device, kgn_conn::gnc_error, kgn_conn::gnc_hashlist, kgn_conn::gnc_in_purgatory, kgn_conn::gnc_list, kgn_conn::gnc_needs_closing, kgn_conn::gnc_nlive_rdma, kgn_conn::gnc_nq_rdma, kgn_conn::gnc_peer, kgn_conn::gnc_peer_error, kgn_conn::gnc_sched_caller, kgn_conn::gnc_sched_line, kgn_conn::gnc_scheduled, kgn_conn::gnc_state, kgn_conn::gnc_tx_ref_table, kgn_device::gnd_lock, kgn_device::gnd_rdmaq_lock, GNIDBG_TX, GNILND_CONN_CLOSED, GNILND_CONN_DONE, GNILND_CONN_PROCESS, GNILND_MAX_MSG_ID, GNILND_MSG_CLOSE, GNILND_RCA_NODE_UP, GNILND_TX_ALLOCD, GNILND_TX_QUIET_ERROR, kgn_peer::gnp_down, kgn_peer::gnp_nid, kgn_peer::gnp_pending_unlink, kgn_tunables::kgn_checksum_dump, kgn_data::kgn_npending_conns, kgn_data::kgn_peer_conn_lock, kgnilnd_admin_decref, kgnilnd_can_unlink_peer_locked(), kgnilnd_conn_decref, kgnilnd_conn_state2str(), kgnilnd_destroy_conn_ep(), kgnilnd_peer_active(), kgnilnd_peer_notify(), kgnilnd_schedule_conn, kgnilnd_tunables, kgnilnd_tx_del_state_locked(), kgnilnd_tx_done(), kgnilnd_unlink_peer_locked(), LASSERT, LASSERTF, libcfs_debug_dumplog(), libcfs_nid2str(), list_add_tail(), list_del_init(), list_empty(), list_for_each_entry_safe, LIST_HEAD(), logmsg, RETURN_EXIT, kgn_tx::tx_list, kgn_tx::tx_msg, and kgn_tx::tx_state.
Referenced by kgnilnd_process_conns(), and kgnilnd_reset_stack().
int kgnilnd_conn_isdup_locked (kgn_peer_t * peer, kgn_conn_t * newconn)
Definition at line 166 of file gnilnd.c.
References CDEBUG, D_NET, ENTRY, kgn_conn::gnc_device, kgn_conn::gnc_my_connstamp, kgn_conn::gnc_peer_connstamp, kgn_conn::gnc_peerstamp, kgn_conn::gnc_state, GNILND_CONN_ESTABLISHED, kgn_net::gnn_ni, kgn_peer::gnp_conns, kgn_peer::gnp_net, kgn_peer::gnp_nid, libcfs_nid2str(), list_entry, list_for_each, LPU64, lnet_ni::ni_nid, and RETURN.
Referenced by kgnilnd_finish_connect().
int kgnilnd_create_conn (kgn_conn_t ** connp, kgn_device_t * dev)
Definition at line 228 of file gnilnd.c.
References CDEBUG, CERROR, CLASSERT, D_NET, kgn_conn::gnc_cqid, kgn_conn::gnc_device, kgn_conn::gnc_ephandle, kgn_conn::gnc_fmaq, kgn_conn::gnc_hashlist, kgn_conn::gnc_list, kgn_conn::gnc_list_lock, kgn_conn::gnc_magic, kgn_conn::gnc_mdd_list, kgn_conn::gnc_my_connstamp, kgn_conn::gnc_next_tx, kgn_conn::gnc_rdma_mutex, kgn_conn::gnc_reaper_noop, kgn_conn::gnc_refcount, kgn_conn::gnc_sched_noop, kgn_conn::gnc_schedlist, kgn_conn::gnc_smsg_mutex, kgn_conn::gnc_timeout, kgn_conn::gnc_tx_in_use, kgn_conn::gnc_tx_lock, kgn_conn::gnc_tx_ref_table, kgn_device::gnd_cq_mutex, kgn_device::gnd_handle, kgn_device::gnd_neps, kgn_device::gnd_snd_fma_cqh, GNI_RC_SUCCESS, GNILND_CONN_MAGIC, GNILND_MAX_CQID, GNILND_MAX_MSG_ID, GNILND_MIN_TIMEOUT, GNILND_MSGID_CLOSE, GOTO, INIT_LIST_HEAD, kgn_data::kgn_connstamp, kgn_data::kgn_nconns, kgn_data::kgn_peer_conn_lock, kgn_tunables::kgn_timeout, kgnilnd_conn_addref, kgnilnd_ep_create(), kgnilnd_get_cqid_locked(), kgnilnd_tunables, kgnilnd_update_reaper_timeout(), kgnilnd_vzalloc(), LASSERT, LIBCFS_ALLOC, LIBCFS_FREE, and MAX.
Referenced by kgnilnd_post_dgram().
int kgnilnd_create_peer_safe (kgn_peer_t ** peerp, lnet_nid_t nid, kgn_net_t * net, int node_state)
Definition at line 972 of file gnilnd.c.
References CDEBUG, D_NET, kgn_net::gnn_shutdown, kgn_peer::gnp_connd_list, kgn_peer::gnp_conns, kgn_peer::gnp_dirty_eps, kgn_peer::gnp_down, kgn_peer::gnp_host_id, kgn_peer::gnp_list, kgn_peer::gnp_net, kgn_peer::gnp_nid, kgn_peer::gnp_refcount, kgn_peer::gnp_tx_queue, INIT_LIST_HEAD, kgn_data::kgn_npeers, kgnilnd_find_net(), kgnilnd_net_addref, kgnilnd_net_decref, kgnilnd_nid_to_nicaddrs(), LASSERT, LASSERTF, LIBCFS_ALLOC, LIBCFS_FREE, libcfs_nid2str(), LNET_NID_ANY, and LNET_NIDADDR().
Referenced by kgnilnd_add_peer(), kgnilnd_finish_connect(), and kgnilnd_launch_tx().
int kgnilnd_ctl (lnet_ni_t * ni, unsigned int cmd, void * arg)
Definition at line 1805 of file gnilnd.c.
References __u64, CERROR, kgn_conn::gnc_device, kgn_conn::gnc_peer, kgn_device::gnd_id, GNILND_CLEAR_PURGATORY, GNILND_DEL_CONN, GNILND_DEL_PEER, kgn_net::gnn_ni, kgn_peer::gnp_nid, libcfs_ioctl_data::ioc_count, libcfs_ioctl_data::ioc_flags, IOC_LIBCFS_ADD_PEER, IOC_LIBCFS_CLOSE_CONNECTION, IOC_LIBCFS_DEL_PEER, IOC_LIBCFS_GET_CONN, IOC_LIBCFS_GET_PEER, IOC_LIBCFS_PUSH_CONNECTION, IOC_LIBCFS_REGISTER_MYNID, libcfs_ioctl_data::ioc_net, libcfs_ioctl_data::ioc_nid, libcfs_ioctl_data::ioc_u32, libcfs_ioctl_data::ioc_u64, kgnilnd_add_peer(), kgnilnd_conn_decref, kgnilnd_del_conn_or_peer(), kgnilnd_get_conn_by_idx(), kgnilnd_get_conn_info(), kgnilnd_get_peer_info(), LASSERT, libcfs_nid2str(), LNET_MKNID(), LNET_NIDADDR(), LNET_NIDNET(), lnet_ni::ni_data, and lnet_ni::ni_nid.
int kgnilnd_del_conn_or_peer (kgn_net_t * net, lnet_nid_t nid, int command, int error)
Definition at line 1507 of file gnilnd.c.
References CDEBUG, CERROR, CFS_FAIL_GNI_RACE_RESET, CFS_RACE, cfs_time_seconds(), D_NET, D_WARNING, GNILND_CLEAR_PURGATORY, GNILND_DEL_CONN, GNILND_DEL_PEER, kgn_peer::gnp_last_errno, kgn_peer::gnp_net, kgn_peer::gnp_nid, kgn_peer::gnp_pending_unlink, kgn_peer::gnp_reconnect_interval, kgn_peer::gnp_reconnect_time, kgn_data::kgn_npending_conns, kgn_data::kgn_npending_detach, kgn_data::kgn_npending_unlink, kgn_data::kgn_peer_conn_lock, kgn_tunables::kgn_peer_hash_size, kgn_data::kgn_peers, kgnilnd_admin_addref, kgnilnd_cancel_peer_connect_locked(), kgnilnd_close_peer_conns_locked(), kgnilnd_del_peer_locked(), kgnilnd_mark_for_detach_purgatory_all_locked(), kgnilnd_nid2peerlist(), kgnilnd_tunables, kgnilnd_txlist_done(), LASSERTF, LBUG, libcfs_nid2str(), list_entry, list_for_each_safe, LIST_HEAD(), LNET_NID_ANY, and LNET_NIDADDR().
Referenced by kgnilnd_base_shutdown(), kgnilnd_ctl(), kgnilnd_reset_stack(), and kgnilnd_shutdown().
void kgnilnd_del_peer_locked (kgn_peer_t * peer, int error)
Definition at line 1479 of file gnilnd.c.
References CFS_FAIL_GNI_FIND_TARGET, CFS_RACE, kgnilnd_can_unlink_peer_locked(), kgnilnd_close_peer_conns_locked(), kgnilnd_peer_active(), kgnilnd_peer_addref, kgnilnd_peer_decref, and kgnilnd_unlink_peer_locked().
Referenced by kgnilnd_del_conn_or_peer().
void kgnilnd_destroy_conn (kgn_conn_t * conn)
Definition at line 443 of file gnilnd.c.
References CDEBUG, D_NET, kgn_conn::gnc_ephandle, kgn_conn::gnc_error, kgn_conn::gnc_fma_blk, kgn_conn::gnc_fmaq, kgn_conn::gnc_hashlist, kgn_conn::gnc_in_purgatory, kgn_conn::gnc_list, kgn_conn::gnc_magic, kgn_conn::gnc_mbox_id, kgn_conn::gnc_mdd_list, kgn_conn::gnc_nlive_fma, kgn_conn::gnc_nlive_rdma, kgn_conn::gnc_peer, kgn_conn::gnc_schedlist, kgn_conn::gnc_scheduled, kgn_conn::gnc_tx_ref_table, GNILND_CONN_MAGIC, GNILND_MAX_MSG_ID, kgn_fma_memblock::gnm_mbox_info, kgn_peer::gnp_nid, kgn_data::kgn_nconns, kgnilnd_count_list(), kgnilnd_peer_decref, kgnilnd_release_mbox(), LASSERTF, LIBCFS_FREE, libcfs_nid2str(), list_empty(), and kgn_mbox_info::mbx_prev_nid.
void kgnilnd_destroy_conn_ep (kgn_conn_t * conn)
Definition at line 407 of file gnilnd.c.
References kgn_conn::gnc_device, kgn_conn::gnc_ephandle, kgn_conn::gnc_peer, kgn_device::gnd_cq_mutex, kgn_device::gnd_neps, GNI_RC_SUCCESS, kgn_peer::gnp_dirty_eps, kgnilnd_admin_decref, kgnilnd_conn_decref, kgnilnd_ep_destroy(), and LASSERTF.
Referenced by kgnilnd_complete_closed_conn(), kgnilnd_process_conns(), and kgnilnd_reset_stack().
void kgnilnd_destroy_peer (kgn_peer_t * peer)
Definition at line 1050 of file gnilnd.c.
References CDEBUG, D_NET, GNILND_PEER_IDLE, GNILND_PEER_KILL, kgn_peer::gnp_connd_list, kgn_peer::gnp_connecting, kgn_peer::gnp_conns, kgn_peer::gnp_dirty_eps, kgn_peer::gnp_net, kgn_peer::gnp_nid, kgn_peer::gnp_refcount, kgn_peer::gnp_tx_queue, kgn_data::kgn_npeers, kgnilnd_net_decref, kgnilnd_peer_active(), LASSERTF, LIBCFS_FREE, libcfs_nid2str(), and list_empty().
void kgnilnd_detach_purgatory_locked (kgn_conn_t * conn, struct list_head * conn_list)
Definition at line 1149 of file gnilnd.c.
References CDEBUG, D_NET, kgn_conn::gnc_fma_blk, kgn_conn::gnc_in_purgatory, kgn_conn::gnc_list, kgn_conn::gnc_mbox_id, kgn_conn::gnc_mdd_list, kgn_conn::gnc_peer, kgn_conn::gnc_state, GNILND_CONN_DONE, kgn_fma_memblock::gnm_mbox_info, kgn_peer::gnp_nid, kgn_peer::gnp_pending_unlink, kgnilnd_can_unlink_peer_locked(), kgnilnd_conn_state2str(), kgnilnd_count_list(), kgnilnd_peer_active(), kgnilnd_unlink_peer_locked(), LASSERTF, libcfs_nid2str(), list_add_tail(), list_del_init(), and kgn_mbox_info::mbx_detach_of_purgatory.
Referenced by kgnilnd_check_peer_timeouts_locked(), and kgnilnd_reset_stack().
void kgnilnd_dev_fini (kgn_device_t * dev)
Definition at line 2115 of file gnilnd.c.
References ENTRY, EXIT, kgn_device::gnd_domain, kgn_device::gnd_err_handle, kgn_device::gnd_map_list, kgn_device::gnd_map_nphys, kgn_device::gnd_map_nvirt, kgn_device::gnd_map_physnop, kgn_device::gnd_map_tx, kgn_device::gnd_map_virtnob, kgn_device::gnd_n_mdd, kgn_device::gnd_n_mdd_held, kgn_device::gnd_nbytes_map, kgn_device::gnd_rcv_fma_cqh, kgn_device::gnd_rdmaq, kgn_device::gnd_ready_conns, kgn_device::gnd_smdd_hold_buf, kgn_device::gnd_snd_fma_cqh, kgn_device::gnd_snd_rdma_cqh, GNI_RC_SUCCESS, kgn_data::kgn_nthreads, kgn_data::kgn_quiesce_trigger, kgn_data::kgn_sock, kgnilnd_cdm_destroy(), kgnilnd_count_list(), kgnilnd_cq_destroy(), kgnilnd_deregister_smdd_buf(), kgnilnd_release_errors(), LASSERT, LASSERTF, list_empty(), and LPU64.
Referenced by kgnilnd_base_shutdown(), kgnilnd_dev_init(), and kgnilnd_reset_stack().
int kgnilnd_dev_init (kgn_device_t * dev)
Definition at line 1996 of file gnilnd.c.
References CDEBUG, CERROR, D_NET, ENTRY, kgn_device::gnd_domain, kgn_device::gnd_err_handle, kgn_device::gnd_handle, kgn_device::gnd_host_id, kgn_device::gnd_id, kgn_device::gnd_nid, kgn_device::gnd_rcv_fma_cqh, kgn_device::gnd_snd_fma_cqh, kgn_device::gnd_snd_rdma_cqh, GNI_ERRMASK_CRITICAL, GNI_ERRMASK_UNKNOWN_TRANSACTION, GNI_RC_SUCCESS, GNILND_INIT_ALL, GOTO, kgn_tunables::kgn_credits, kgn_tunables::kgn_fma_cq_size, kgn_data::kgn_init, kgn_tunables::kgn_pkey, kgn_tunables::kgn_ptag, kgn_data::kgn_sock, kgnilnd_cdm_attach(), kgnilnd_cdm_create(), kgnilnd_cq_create(), kgnilnd_critical_error(), kgnilnd_dev_fini(), kgnilnd_device_callback(), kgnilnd_nicaddr_to_nid(), kgnilnd_quiesce_end_callback(), kgnilnd_register_smdd_buf(), kgnilnd_set_quiesce_callback(), kgnilnd_setup_nic_translation(), kgnilnd_subscribe_errors(), kgnilnd_tunables, and RETURN.
Referenced by kgnilnd_base_startup(), and kgnilnd_reset_stack().
static void __exit kgnilnd_exit (void) [static]
Definition at line 2881 of file gnilnd.c.
References kgnilnd_proc_fini(), kgnilnd_remove_sysctl(), and lnet_unregister_lnd().
kgn_conn_t* kgnilnd_find_conn_locked (kgn_peer_t * peer)
Definition at line 329 of file gnilnd.c.
References kgn_conn::gnc_state, GNILND_CONN_ESTABLISHED, kgn_peer::gnp_conns, kgn_peer::gnp_nid, kgn_data::kgn_in_reset, kgnilnd_conn_state2str(), LASSERTF, libcfs_nid2str(), list_for_each_entry, RETURN, and unlikely.
Referenced by kgnilnd_check_peer_timeouts_locked(), kgnilnd_eager_recv(), kgnilnd_find_or_create_conn_locked(), kgnilnd_get_conn_info(), kgnilnd_launch_tx(), kgnilnd_peer_notify(), kgnilnd_peer_seq_show(), kgnilnd_query(), and kgnilnd_report_node_state().
kgn_conn_t* kgnilnd_find_or_create_conn_locked (kgn_peer_t * peer)
Definition at line 356 of file gnilnd.c.
References CDEBUG, D_NET, D_NETTRACE, kgn_conn::gnc_ephandle, kgn_device::gnd_connd_lock, kgn_device::gnd_connd_peers, GNILND_PEER_CONNECT, GNILND_PEER_IDLE, kgn_net::gnn_dev, kgn_peer::gnp_connd_list, kgn_peer::gnp_connecting, kgn_peer::gnp_conns, kgn_peer::gnp_net, kgn_peer::gnp_nid, kgn_peer::gnp_reconnect_time, kgnilnd_find_conn_locked(), kgnilnd_peer_addref, kgnilnd_schedule_dgram(), libcfs_nid2str(), list_add_tail(), and list_for_each_entry.
Referenced by kgnilnd_launch_tx().
kgn_peer_t* kgnilnd_find_peer_locked (lnet_nid_t nid)
Definition at line 1274 of file gnilnd.c.
References CDEBUG, D_NET, kgn_peer::gnp_connecting, kgn_peer::gnp_nid, kgn_peer::gnp_refcount, kgnilnd_nid2peerlist(), libcfs_nid2str(), list_for_each_entry, and LNET_NIDADDR().
Referenced by kgnilnd_add_peer_locked(), kgnilnd_eager_recv(), kgnilnd_launch_tx(), kgnilnd_probe_and_process_dgram(), kgnilnd_proc_peer_conns_seq_show(), kgnilnd_process_nak(), kgnilnd_query(), kgnilnd_release_dgram(), and kgnilnd_report_node_state().
kgn_conn_t* kgnilnd_get_conn_by_idx (int index)
Definition at line 1614 of file gnilnd.c.
References CDEBUG, D_NET, kgn_conn::gnc_peer, kgn_conn::gnc_refcount, kgn_conn::gnc_state, GNILND_CONN_ESTABLISHED, kgn_peer::gnp_conns, kgn_peer::gnp_nid, kgn_data::kgn_peer_conn_lock, kgn_tunables::kgn_peer_hash_size, kgn_data::kgn_peers, kgnilnd_conn_addref, kgnilnd_tunables, libcfs_nid2str(), list_entry, and list_for_each.
Referenced by kgnilnd_ctl().
int kgnilnd_get_conn_info (kgn_peer_t * peer, int * device_id, __u64 * peerstamp, int * tx_seq, int * rx_seq, int * fmaq_len, int * nfma, int * nrdma)
Definition at line 1653 of file gnilnd.c.
References kgn_conn::gnc_device, kgn_conn::gnc_fmaq, kgn_conn::gnc_nlive_fma, kgn_conn::gnc_nlive_rdma, kgn_conn::gnc_peerstamp, kgn_conn::gnc_rx_seq, kgn_conn::gnc_tx_seq, kgn_device::gnd_host_id, kgn_data::kgn_peer_conn_lock, kgnilnd_count_list(), and kgnilnd_find_conn_locked().
Referenced by kgnilnd_ctl().
int kgnilnd_get_peer_info (int index, kgn_peer_t ** found_peer, lnet_nid_t * id, __u32 * nic_addr, int * refcount, int * connecting)
Definition at line 1320 of file gnilnd.c.
References CDEBUG, D_NET, kgn_peer::gnp_connecting, kgn_peer::gnp_host_id, kgn_peer::gnp_nid, kgn_peer::gnp_refcount, kgn_data::kgn_peer_conn_lock, kgn_tunables::kgn_peer_hash_size, kgn_data::kgn_peers, kgnilnd_tunables, libcfs_nid2str(), list_entry, and list_for_each.
Referenced by kgnilnd_ctl().
static int __init kgnilnd_init (void) [static]
Definition at line 2888 of file gnilnd.c.
References KGNILND_BUILD_REV, kgnilnd_insert_sysctl(), kgnilnd_proc_init(), kgnilnd_tunables_init(), lnet_register_lnd(), and printk.
void kgnilnd_mark_for_detach_purgatory_all_locked (kgn_peer_t * peer)
Definition at line 1136 of file gnilnd.c.
References kgn_conn::gnc_in_purgatory, kgn_conn::gnc_needs_detach, kgn_peer::gnp_conns, kgn_data::kgn_npending_detach, kgnilnd_admin_addref, and list_for_each_entry.
Referenced by kgnilnd_del_conn_or_peer().
void kgnilnd_peer_alive (kgn_peer_t * peer)
Definition at line 506 of file gnilnd.c.
References kgn_peer::gnp_last_alive.
Referenced by kgnilnd_bump_timeouts(), kgnilnd_check_fma_rcv_cq(), kgnilnd_check_fma_rx(), kgnilnd_check_rdma_cq(), kgnilnd_finish_connect(), and kgnilnd_sendmsg_nolock().
void kgnilnd_peer_increase_reconnect_locked (kgn_peer_t * peer)
Definition at line 1247 of file gnilnd.c.
References CDEBUG, cfs_time_seconds(), D_NET, kgn_peer::gnp_nid, kgn_peer::gnp_reconnect_interval, kgn_peer::gnp_reconnect_time, kgn_tunables::kgn_max_reconnect_interval, kgn_tunables::kgn_min_reconnect_interval, kgnilnd_tunables, libcfs_nid2str(), and MIN.
Referenced by kgnilnd_probe_and_process_dgram(), and kgnilnd_start_outbound_dgrams().
void kgnilnd_peer_notify (kgn_peer_t * peer, int error, int alive)
Definition at line 512 of file gnilnd.c.
References CDEBUG, CERROR, cfs_duration_sec(), CFS_FAIL_CHECK, CFS_FAIL_GNI_DONT_NOTIFY, D_NET, D_NETTRACE, GNILND_PEER_IDLE, kgn_net::gnn_ni, kgn_net::gnn_shutdown, kgn_peer::gnp_connecting, kgn_peer::gnp_last_alive, kgn_peer::gnp_nid, kgn_data::kgn_in_reset, kgn_tunables::kgn_net_hash_size, kgn_data::kgn_net_rw_sem, kgn_data::kgn_nets, kgn_data::kgn_peer_conn_lock, kgnilnd_conn_clean_errno(), kgnilnd_find_conn_locked(), kgnilnd_lnd2lnetnid(), kgnilnd_net_addref, kgnilnd_net_decref, kgnilnd_tunables, LIBCFS_ALLOC, LIBCFS_FREE, libcfs_nid2str(), list_for_each_entry, lnet_notify(), and lnet_ni::ni_nid.
Referenced by kgnilnd_bump_timeouts(), kgnilnd_complete_closed_conn(), kgnilnd_probe_and_process_dgram(), kgnilnd_release_purgatory_list(), and kgnilnd_report_node_state().
void kgnilnd_query (lnet_ni_t * ni, lnet_nid_t nid, cfs_time_t * when)
Definition at line 1925 of file gnilnd.c.
References CDEBUG, CFS_FAIL_CHECK, CFS_FAIL_GNI_NOOP_SEND, D_NETTRACE, ENTRY, EXIT, GNILND_MSG_NOOP, kgn_peer::gnp_last_alive, kgn_peer::gnp_last_errno, GOTO, kgn_data::kgn_peer_conn_lock, kgn_data::kgn_quiesce_trigger, kgnilnd_conn_clean_errno(), kgnilnd_find_conn_locked(), kgnilnd_find_peer_locked(), kgnilnd_launch_tx(), kgnilnd_new_tx_msg(), libcfs_nid2str(), LNET_PID_LUSTRE, lnet_ni::ni_data, and lnet_ni::ni_nid.
void kgnilnd_release_purgatory_list (struct list_head * conn_list)
Definition at line 1195 of file gnilnd.c.
References CDEBUG, D_NET, kgn_mdd_purgatory::gmp_list, kgn_mdd_purgatory::gmp_map_key, kgn_conn::gnc_device, kgn_conn::gnc_error, kgn_conn::gnc_in_purgatory, kgn_conn::gnc_list, kgn_conn::gnc_mdd_list, kgn_conn::gnc_needs_detach, kgn_conn::gnc_peer, kgn_device::gnd_handle, kgn_device::gnd_n_mdd_held, kgn_data::kgn_npending_detach, kgnilnd_admin_decref, kgnilnd_conn_decref, kgnilnd_mem_mdd_release(), kgnilnd_peer_notify(), kgnilnd_release_mbox(), LIBCFS_FREE, list_del_init(), list_for_each_entry_safe, LPX64, gni_mem_handle::qword1, and gni_mem_handle::qword2.
Referenced by kgnilnd_reaper_check(), and kgnilnd_reset_stack().
int kgnilnd_report_node_state (lnet_nid_t nid, int down)
Definition at line 1710 of file gnilnd.c.
References CNETERR, GNILND_RCA_NODE_DOWN, GNILND_RCA_NODE_UP, kgn_net::gnn_ni, kgn_peer::gnp_down, kgn_peer::gnp_down_event_time, kgn_peer::gnp_up_event_time, kgn_tunables::kgn_net_hash_size, kgn_data::kgn_net_rw_sem, kgn_data::kgn_nets, kgn_data::kgn_peer_conn_lock, kgnilnd_add_peer(), kgnilnd_cancel_peer_connect_locked(), kgnilnd_close_conn_locked(), kgnilnd_find_conn_locked(), kgnilnd_find_peer_locked(), kgnilnd_peer_notify(), kgnilnd_tunables, kgnilnd_txlist_done(), LCONSOLE_INFO, list_for_each_entry, LIST_HEAD(), LNET_MKNID(), LNET_NIDADDR(), LNET_NIDNET(), and lnet_ni::ni_nid.
int kgnilnd_set_conn_params (kgn_dgram_t * dgram)
Definition at line 869 of file gnilnd.c.
References CDEBUG, CERROR, D_NET, kgn_conn::gnc_cqid, kgn_conn::gnc_device, kgn_conn::gnc_ephandle, kgn_conn::gnc_peer_connstamp, kgn_conn::gnc_peerstamp, kgn_conn::gnc_timeout, kgn_connreq::gncr_connstamp, kgn_connreq::gncr_dstnid, kgn_connreq::gncr_gnparams, kgn_connreq::gncr_peerstamp, kgn_connreq::gncr_srcnid, kgn_connreq::gncr_timeout, kgn_device::gnd_cq_mutex, kgn_dgram::gndg_conn, kgn_dgram::gndg_conn_in, kgn_dgram::gndg_conn_out, GNI_RC_INVALID_PARAM, GNI_RC_SUCCESS, GNILND_TO2KA, kgn_gniparams::gnpr_cqid, kgn_gniparams::gnpr_host_id, kgn_conn::gnpr_smsg_attr, kgn_gniparams::gnpr_smsg_attr, kgnilnd_ep_bind(), kgnilnd_ep_set_eventdata(), kgnilnd_ep_unbind(), kgnilnd_smsg_init(), kgnilnd_update_reaper_timeout(), LASSERTF, LCONSOLE_ERROR, libcfs_nid2str(), LNET_NID_ANY, LPX64, MAX, gni_smsg_attr::mbox_maxcredit, gni_smsg_attr::mbox_offset, gni_smsg_attr::mem_hndl, gni_smsg_attr::msg_buffer, gni_smsg_attr::msg_maxsize, gni_smsg_attr::msg_type, gni_mem_handle::qword1, gni_mem_handle::qword2, kgn_conn::remote_mbox_addr, and unlikely.
Referenced by kgnilnd_unpack_connreq().
void kgnilnd_shutdown (lnet_ni_t * ni)
Definition at line 2780 of file gnilnd.c.
References CDEBUG, CERROR, CFS_FAIL_GNI_SR_DOWN_RACE, CFS_RACE, cfs_time_seconds(), D_MALLOC, D_NET, D_WARNING, ENTRY, EXIT, GNILND_DEL_PEER, GNILND_INIT_ALL, GNILND_IS_QUIESCED, GNILND_QUIESCE_IDLE, kgn_net::gnn_dev, kgn_net::gnn_list, kgn_net::gnn_netnum, kgn_net::gnn_ni, kgn_net::gnn_refcount, kgn_net::gnn_shutdown, GOTO, kgn_data::kgn_init, kgn_tunables::kgn_net_hash_size, kgn_data::kgn_net_rw_sem, kgn_data::kgn_nets, kgn_data::kgn_quiesce_mutex, kgn_data::kgn_quiesce_trigger, kgnilnd_base_shutdown(), kgnilnd_cancel_net_dgrams(), kgnilnd_del_conn_or_peer(), kgnilnd_net_decref, kgnilnd_quiesce_wait(), kgnilnd_tunables, kgnilnd_wait_for_canceled_dgrams(), LASSERT, LASSERTF, LIBCFS_FREE, libcfs_kmemory, list_del_init(), list_empty(), LNET_NID_ANY, and lnet_ni::ni_data.
Referenced by kgnilnd_startup().
int kgnilnd_start_sd_threads (void)
Definition at line 60 of file gnilnd.c.
References CERROR, kgn_data::kgn_nthreads, kgn_tunables::kgn_sched_threads, kgnilnd_scheduler(), and kgnilnd_tunables.
Referenced by kgnilnd_base_startup().
int kgnilnd_startup (lnet_ni_t * ni)
Definition at line 2687 of file gnilnd.c.
References CDEBUG, CERROR, D_NET, ENTRY, kgn_device::gnd_id, kgn_device::gnd_nid, GNILND_INIT_NOTHING, GNILND_MAXDEVS, GNILND_REAPER_NCHECKS, GNILND_TO2KA, kgn_net::gnn_dev, kgn_net::gnn_list, kgn_net::gnn_netnum, kgn_net::gnn_ni, kgn_net::gnn_refcount, GOTO, INIT_LIST_HEAD, kgn_tunables::kgn_credits, kgn_data::kgn_devices, kgn_data::kgn_init, kgn_data::kgn_net_rw_sem, kgn_tunables::kgn_peer_credits, kgn_tunables::kgn_peer_health, kgn_tunables::kgn_peer_timeout, kgn_data::kgn_quiesce_mutex, kgn_tunables::kgn_timeout, kgnilnd_base_startup(), kgnilnd_netnum2netlist(), kgnilnd_shutdown(), kgnilnd_tunables, LASSERTF, LCONSOLE_ERROR, LCONSOLE_INFO, LIBCFS_ALLOC, LIBCFS_FREE, libcfs_nid2str(), list_add_tail(), LNET_MKNID(), LNET_NETNUM(), LNET_NIDNET(), lnet_ni::ni_data, lnet_ni::ni_lnd, lnet_ni::ni_maxtxcredits, lnet_ni::ni_nid, lnet_ni::ni_peertimeout, lnet_ni::ni_peertxcredits, RETURN, and timeout.
int kgnilnd_thread_start (int(*)(void *arg) fn, void * arg, char * name, int id)
Definition at line 46 of file gnilnd.c.
References kgn_data::kgn_nthreads.
Referenced by kgnilnd_base_startup().
void kgnilnd_unlink_peer_locked (kgn_peer_t * peer)
Definition at line 1298 of file gnilnd.c.
References CDEBUG, D_NET, kgn_peer::gnp_conns, kgn_peer::gnp_list, kgn_peer::gnp_nid, kgn_peer::gnp_tx_queue, kgn_data::kgn_npending_unlink, kgn_data::kgn_peer_version, kgnilnd_admin_decref, kgnilnd_peer_active(), kgnilnd_peer_decref, LASSERTF, libcfs_nid2str(), list_del_init(), and list_empty().
Referenced by kgnilnd_complete_closed_conn(), kgnilnd_del_peer_locked(), and kgnilnd_detach_purgatory_locked().
MODULE_AUTHOR (" Cray, Inc.< nic @cray.com >")
MODULE_DESCRIPTION ("Gemini LNet Network Driver")
module_exit (kgnilnd_exit)
module_init (kgnilnd_init)
MODULE_LICENSE ("GPL")
MODULE_VERSION (KGNILND_BUILD_REV)
Variable Documentation
kgn_data_t kgnilnd_data
Definition at line 43 of file gnilnd.c.
Referenced by kgnilnd_alloc_dgram(), kgnilnd_alloc_fmablk(), kgnilnd_alloc_rx(), kgnilnd_alloc_tx(), kgnilnd_bump_timeouts(), kgnilnd_cancel_dgrams(), kgnilnd_cancel_net_dgrams(), kgnilnd_cancel_wc_dgrams(), kgnilnd_check_fma_rcv_cq(), kgnilnd_check_fma_rx(), kgnilnd_check_fma_send_cq(), kgnilnd_check_hw_quiesce(), kgnilnd_check_rdma_cq(), kgnilnd_cksum_kiov(), kgnilnd_conn_seq_seek(), kgnilnd_conn_seq_show(), kgnilnd_conn_seq_start(), kgnilnd_consume_rx(), kgnilnd_critical_error(), kgnilnd_device_callback(), kgnilnd_dgram_mover(), kgnilnd_dgram_poke_with_stick(), kgnilnd_dgram_waitq(), kgnilnd_eager_recv(), kgnilnd_finish_connect(), kgnilnd_free_dgram(), kgnilnd_free_fmablk_locked(), kgnilnd_free_tx(), kgnilnd_hw_in_quiesce(), kgnilnd_launch_tx(), kgnilnd_mdd_seq_start(), kgnilnd_pack_connreq(), kgnilnd_pause_threads(), kgnilnd_peer_seq_seek(), kgnilnd_peer_seq_show(), kgnilnd_peer_seq_start(), kgnilnd_probe_and_process_dgram(), kgnilnd_proc_cksum_test_write(), kgnilnd_proc_peer_conns_seq_show(), kgnilnd_proc_stats_write(), kgnilnd_process_conns(), kgnilnd_process_mapped_tx(), kgnilnd_process_nak(), kgnilnd_process_rdmaq(), kgnilnd_quiesce_end_callback(), kgnilnd_quiesce_wait(), kgnilnd_rdma(), kgnilnd_reaper(), kgnilnd_reaper_check(), kgnilnd_reaper_poke_with_stick(), kgnilnd_recv(), kgnilnd_release_dgram(), kgnilnd_reset_stack(), kgnilnd_ruhroh_thread(), kgnilnd_scheduler(), kgnilnd_send_conn_close(), kgnilnd_sendmsg_trylock(), kgnilnd_setup_immediate_buffer(), kgnilnd_setup_phys_buffer(), kgnilnd_smsg_seq_start(), kgnilnd_start_connect(), kgnilnd_start_outbound_dgrams(), kgnilnd_stats_seq_show(), kgnilnd_unmap_fmablk(), and kgnilnd_update_reaper_timeout().
lnd_t the_kgnilnd
Initial value:
 {
        .lnd_type       = GNIIPLND,
        .lnd_startup    = kgnilnd_startup,
        .lnd_shutdown   = kgnilnd_shutdown,
        .lnd_ctl        = kgnilnd_ctl,
        .lnd_send       = kgnilnd_send,
        .lnd_recv       = kgnilnd_recv,
        .lnd_eager_recv = kgnilnd_eager_recv,
        .lnd_query      = kgnilnd_query,
}
Definition at line 28 of file gnilnd.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.