Lustre: lnet/klnds/gnilnd/gnilnd_conn.c File Reference
lnet/klnds/gnilnd/gnilnd_conn.c File Reference
#include "gnilnd.h"
Functions
void kgnilnd_setup_smsg_attr (gni_smsg_attr_t *smsg_attr)
int kgnilnd_map_fmablk (kgn_device_t *device, kgn_fma_memblock_t *fma_blk)
int kgnilnd_alloc_fmablk (kgn_device_t *device, int use_phys)
void kgnilnd_unmap_fmablk (kgn_device_t *dev, kgn_fma_memblock_t *fma_blk)
void kgnilnd_free_fmablk_locked (kgn_device_t *dev, kgn_fma_memblock_t *fma_blk)
void kgnilnd_find_free_mbox (kgn_conn_t *conn)
int kgnilnd_setup_mbox (kgn_conn_t *conn)
void kgnilnd_release_mbox (kgn_conn_t *conn, int purgatory_hold)
int kgnilnd_count_phys_mbox (kgn_device_t *device)
int kgnilnd_allocate_phys_fmablk (kgn_device_t *device)
int kgnilnd_map_phys_fmablk (kgn_device_t *device)
void kgnilnd_unmap_fma_blocks (kgn_device_t *device)
void kgnilnd_free_phys_fmablk (kgn_device_t *device)
static struct list_head * kgnilnd_nid2dgramlist (kgn_device_t *dev, lnet_nid_t nid)
kgn_dgram_t * kgnilnd_find_dgram_locked (kgn_device_t *dev, lnet_nid_t dst_nid)
int kgnilnd_find_and_cancel_dgram (kgn_device_t *dev, lnet_nid_t dst_nid)
int kgnilnd_pack_connreq (kgn_connreq_t *connreq, kgn_conn_t *conn, lnet_nid_t srcnid, lnet_nid_t dstnid, kgn_connreq_type_t type)
int kgnilnd_unpack_connreq (kgn_dgram_t *dgram)
int kgnilnd_alloc_dgram (kgn_dgram_t **dgramp, kgn_device_t *dev, kgn_dgram_type_t type)
int kgnilnd_process_dgram (kgn_dgram_t *dgram, gni_post_state_t post_state)
void kgnilnd_cancel_dgram_locked (kgn_dgram_t *dgram)
void kgnilnd_cleanup_dgram (kgn_dgram_t *dgram)
void kgnilnd_free_dgram (kgn_device_t *dev, kgn_dgram_t *dgram)
int kgnilnd_post_dgram (kgn_device_t *dev, lnet_nid_t dstnid, kgn_connreq_type_t type, int data_rc)
void kgnilnd_release_dgram (kgn_device_t *dev, kgn_dgram_t *dgram, int shutdown)
int kgnilnd_probe_for_dgram (kgn_device_t *dev, kgn_dgram_t **dgramp)
int kgnilnd_setup_wildcard_dgram (kgn_device_t *dev)
int kgnilnd_cancel_net_dgrams (kgn_net_t *net)
int kgnilnd_cancel_wc_dgrams (kgn_device_t *dev)
int kgnilnd_cancel_dgrams (kgn_device_t *dev)
void kgnilnd_wait_for_canceled_dgrams (kgn_device_t *dev)
int kgnilnd_start_connect (kgn_peer_t *peer)
int kgnilnd_finish_connect (kgn_dgram_t *dgram)
void kgnilnd_send_nak (kgn_device_t *dev, lnet_nid_t dst_nid, int error)
int kgnilnd_process_nak (kgn_dgram_t *dgram)
int kgnilnd_process_connreq (kgn_dgram_t *dgram, int *needs_nak)
int kgnilnd_probe_and_process_dgram (kgn_device_t *dev)
void kgnilnd_reaper_dgram_check (kgn_device_t *dev)
int kgnilnd_dgram_waitq (void *arg)
int kgnilnd_start_outbound_dgrams (kgn_device_t *dev, unsigned long deadline)
int kgnilnd_repost_wc_dgrams (kgn_device_t *dev)
static void kgnilnd_dgram_poke_with_stick (unsigned long arg)
int kgnilnd_dgram_mover (void *arg)
Function Documentation
int kgnilnd_alloc_dgram (kgn_dgram_t ** dgramp, kgn_device_t * dev, kgn_dgram_type_t type)
Definition at line 959 of file gnilnd_conn.c.
References CDEBUG, D_MALLOC, D_NETTRACE, kgn_device::gnd_ndgrams, GNILND_DGRAM_MAGIC, GNILND_DGRAM_USED, INIT_LIST_HEAD, kgn_data::kgn_dgram_cache, kgnilnd_data, and kgnilnd_dgram_type2str().
Referenced by kgnilnd_post_dgram().
int kgnilnd_alloc_fmablk (kgn_device_t * device, int use_phys)
Definition at line 91 of file gnilnd_conn.c.
References CDEBUG, CNETERR, D_MALLOC, kgn_data::free_pages_limit, kgn_device::gnd_fma_buffs, kgn_device::gnd_fmablk_lock, kgn_device::gnd_fmablk_mutex, kgn_device::gnd_fmablk_vers, GNILND_FMABLK_PHYS, GNILND_FMABLK_VIRT, GNILND_MBOX_PAYLOAD, kgn_fma_memblock::gnm_avail_mboxs, kgn_fma_memblock::gnm_bit_array, kgn_fma_memblock::gnm_blk_size, kgn_fma_memblock::gnm_block, kgn_fma_memblock::gnm_bufflist, kgn_fma_memblock::gnm_hndl, kgn_fma_memblock::gnm_mbox_info, kgn_fma_memblock::gnm_mbox_size, kgn_fma_memblock::gnm_next_avail_mbox, kgn_fma_memblock::gnm_num_mboxs, kgn_fma_memblock::gnm_state, GOTO, INIT_LIST_HEAD, kgn_data::kgn_mbox_cache, kgn_tunables::kgn_mbox_per_block, kgnilnd_data, kgnilnd_map_fmablk(), kgnilnd_setup_smsg_attr(), kgnilnd_tunables, kgnilnd_vzalloc(), LASSERTF, LCONSOLE_INFO, LIBCFS_ALLOC, LIBCFS_FREE, list_add_tail(), LPX64, gni_smsg_attr::mbox_maxcredit, gni_smsg_attr::msg_maxsize, gni_mem_handle::qword1, and gni_mem_handle::qword2.
Referenced by kgnilnd_allocate_phys_fmablk(), and kgnilnd_setup_mbox().
int kgnilnd_allocate_phys_fmablk (kgn_device_t * device)
Definition at line 599 of file gnilnd_conn.c.
References CERROR, kgn_tunables::kgn_nphys_mbox, kgnilnd_alloc_fmablk(), kgnilnd_count_phys_mbox(), kgnilnd_tunables, and RETURN.
Referenced by kgnilnd_base_startup().
void kgnilnd_cancel_dgram_locked (kgn_dgram_t * dgram)
Definition at line 1074 of file gnilnd_conn.c.
References __u64, CDEBUG, D_NET, D_NETTRACE, kgn_conn::gnc_device, kgn_conn::gnc_ephandle, kgn_conn::gnc_state, kgn_device::gnd_canceled_dgrams, kgn_dgram::gndg_conn, kgn_dgram::gndg_state, GNI_RC_NO_MATCH, GNI_RC_SUCCESS, GNILND_CONN_ESTABLISHED, GNILND_DGRAM_CANCELED, GNILND_DGRAM_DONE, GNILND_DGRAM_POSTED, GNILND_DGRAM_WC_REQ, kgnilnd_dgram_type2str(), kgnilnd_ep_postdata_cancel_by_id(), kgnilnd_ep_postdata_test_by_id(), kgnilnd_process_dgram(), LASSERTF, libcfs_nid2str(), and RETURN_EXIT.
Referenced by kgnilnd_cancel_dgrams(), kgnilnd_cancel_net_dgrams(), kgnilnd_cancel_wc_dgrams(), kgnilnd_find_and_cancel_dgram(), kgnilnd_reaper_dgram_check(), and kgnilnd_release_dgram().
int kgnilnd_cancel_dgrams (kgn_device_t * dev)
Definition at line 1635 of file gnilnd_conn.c.
References ENTRY, kgn_device::gnd_dgram_lock, kgn_device::gnd_dgrams, kgn_dgram::gndg_type, GNILND_DGRAM_WC_REQ, kgn_tunables::kgn_peer_hash_size, kgn_data::kgn_wc_kill, kgnilnd_cancel_dgram_locked(), kgnilnd_data, kgnilnd_tunables, LASSERTF, list_for_each_entry_safe, and RETURN.
Referenced by kgnilnd_base_shutdown().
int kgnilnd_cancel_net_dgrams (kgn_net_t * net)
Definition at line 1547 of file gnilnd_conn.c.
References ENTRY, kgn_connreq::gncr_dstnid, kgn_device::gnd_dgram_lock, kgn_device::gnd_dgrams, kgn_dgram::gndg_conn_out, kgn_dgram::gndg_type, GNILND_DGRAM_WC_REQ, kgn_net::gnn_dev, kgn_net::gnn_netnum, kgn_net::gnn_shutdown, INIT_LIST_HEAD, kgn_data::kgn_in_reset, kgn_tunables::kgn_peer_hash_size, kgnilnd_cancel_dgram_locked(), kgnilnd_data, kgnilnd_tunables, LASSERTF, list_for_each_entry_safe, LNET_NETNUM(), LNET_NIDNET(), and RETURN.
Referenced by kgnilnd_reset_stack(), and kgnilnd_shutdown().
int kgnilnd_cancel_wc_dgrams (kgn_device_t * dev)
Definition at line 1588 of file gnilnd_conn.c.
References ENTRY, kgn_connreq::gncr_dstnid, kgn_device::gnd_dgram_lock, kgn_dgram::gndg_conn_out, kgn_dgram::gndg_list, kgn_dgram::gndg_state, kgn_dgram::gndg_type, GNILND_DGRAM_DONE, GNILND_DGRAM_WC_REQ, INIT_LIST_HEAD, kgn_data::kgn_in_reset, kgn_data::kgn_wc_kill, kgnilnd_cancel_dgram_locked(), kgnilnd_data, kgnilnd_dgram_type2str(), kgnilnd_find_dgram_locked(), kgnilnd_release_dgram(), LASSERTF, libcfs_nid2str(), list_add_tail(), list_del_init(), list_for_each_entry_safe, LNET_NID_ANY, and RETURN.
Referenced by kgnilnd_base_shutdown(), and kgnilnd_reset_stack().
void kgnilnd_cleanup_dgram (kgn_dgram_t * dgram)
Definition at line 1170 of file gnilnd_conn.c.
References kgn_dgram::gndg_conn, and kgnilnd_conn_decref.
Referenced by kgnilnd_post_dgram(), and kgnilnd_release_dgram().
int kgnilnd_count_phys_mbox (kgn_device_t * device)
Definition at line 582 of file gnilnd_conn.c.
References kgn_device::gnd_fma_buffs, kgn_device::gnd_fmablk_lock, GNILND_FMABLK_PHYS, kgn_fma_memblock::gnm_num_mboxs, kgn_fma_memblock::gnm_state, list_for_each_entry, and RETURN.
Referenced by kgnilnd_allocate_phys_fmablk().
int kgnilnd_dgram_mover (void * arg)
Definition at line 2447 of file gnilnd_conn.c.
References CDEBUG, cfs_block_allsigs(), cfs_duration_sec(), CFS_FAIL_GNI_DGRAM_DEADLINE, CFS_FAIL_GNI_QUIESCE_RACE, CFS_FAIL_GNI_WC_DGRAM_FREE, CFS_FAIL_TIMEOUT, CFS_RACE, cfs_time_seconds(), D_INFO, kgn_device::gnd_dgping_waitq, kgn_device::gnd_dgram_ready, kgn_device::gnd_dgram_waitq, kgn_device::gnd_id, GNILND_DGRAM_IDLE, kgn_tunables::kgn_dgram_timeout, kgn_data::kgn_net_rw_sem, kgn_data::kgn_new_min_timeout, kgn_tunables::kgn_nice, kgn_data::kgn_quiesce_trigger, kgn_data::kgn_shutdown, kgnilnd_data, kgnilnd_dgram_poke_with_stick(), kgnilnd_probe_and_process_dgram(), kgnilnd_reaper_dgram_check(), kgnilnd_repost_wc_dgrams(), KGNILND_SPIN_QUIESCE, kgnilnd_start_outbound_dgrams(), kgnilnd_thread_fini(), kgnilnd_tunables, name, timeout, and unlikely.
Referenced by kgnilnd_base_startup().
static void kgnilnd_dgram_poke_with_stick (unsigned long arg) [static]
Definition at line 2437 of file gnilnd_conn.c.
References kgn_device::gnd_dgram_waitq, kgn_data::kgn_devices, and kgnilnd_data.
Referenced by kgnilnd_dgram_mover().
int kgnilnd_dgram_waitq (void * arg)
Definition at line 2270 of file gnilnd_conn.c.
References __u64, CDEBUG, cfs_block_allsigs(), CFS_FAIL_GNI_PAUSE_DGRAM_COMP, CFS_FAIL_TIMEOUT, D_INFO, kgn_device::gnd_dgping_waitq, kgn_device::gnd_handle, kgn_device::gnd_id, GNI_RC_SUCCESS, kgn_tunables::kgn_nice, kgn_data::kgn_quiesce_trigger, kgn_data::kgn_shutdown, kgnilnd_data, kgnilnd_postdata_probe_wait_by_id(), kgnilnd_schedule_dgram(), KGNILND_SPIN_QUIESCE, kgnilnd_thread_fini(), kgnilnd_tunables, likely, name, and unlikely.
Referenced by kgnilnd_base_startup().
int kgnilnd_find_and_cancel_dgram (kgn_device_t * dev, lnet_nid_t dst_nid)
Definition at line 713 of file gnilnd_conn.c.
References kgn_device::gnd_dgram_lock, kgnilnd_cancel_dgram_locked(), kgnilnd_find_dgram_locked(), and RETURN.
Referenced by kgnilnd_cancel_peer_connect_locked(), kgnilnd_process_nak(), and kgnilnd_start_connect().
kgn_dgram_t* kgnilnd_find_dgram_locked (kgn_device_t * dev, lnet_nid_t dst_nid)
Definition at line 693 of file gnilnd_conn.c.
References CDEBUG, D_NET, kgn_connreq::gncr_dstnid, kgn_dgram::gndg_conn_out, kgn_dgram::gndg_state, GNILND_DGRAM_POSTED, kgnilnd_nid2dgramlist(), libcfs_nid2str(), and list_for_each_entry.
Referenced by kgnilnd_cancel_wc_dgrams(), kgnilnd_find_and_cancel_dgram(), and kgnilnd_post_dgram().
void kgnilnd_find_free_mbox (kgn_conn_t * conn)
Definition at line 362 of file gnilnd_conn.c.
References gni_smsg_attr::buff_size, CDEBUG, D_NET, kgn_conn::gnc_device, kgn_conn::gnc_fma_blk, kgn_conn::gnc_mbox_id, kgn_device::gnd_fma_buffs, kgn_device::gnd_fmablk_lock, GNILND_FMABLK_IDLE, kgn_fma_memblock::gnm_avail_mboxs, kgn_fma_memblock::gnm_bit_array, kgn_fma_memblock::gnm_block, kgn_fma_memblock::gnm_hndl, kgn_fma_memblock::gnm_mbox_info, kgn_fma_memblock::gnm_mbox_size, kgn_fma_memblock::gnm_next_avail_mbox, kgn_fma_memblock::gnm_num_mboxs, kgn_fma_memblock::gnm_state, kgn_conn::gnpr_smsg_attr, kgnilnd_setup_smsg_attr(), LASSERTF, list_for_each_entry, LPX64, gni_smsg_attr::mbox_offset, kgn_mbox_info::mbx_create_conn_memset, kgn_mbox_info::mbx_nallocs, kgn_mbox_info::mbx_nallocs_total, gni_smsg_attr::mem_hndl, gni_smsg_attr::msg_buffer, gni_mem_handle::qword1, and gni_mem_handle::qword2.
Referenced by kgnilnd_setup_mbox().
int kgnilnd_finish_connect (kgn_dgram_t * dgram)
Definition at line 1779 of file gnilnd_conn.c.
References CDEBUG, CERROR, CFS_FAIL_CHECK, CFS_FAIL_GNI_FINISH_PURG, CFS_FAIL_GNI_ONLY_NOOP, cfs_fail_loc, cfs_time_current(), cfs_time_seconds(), CNETERR, D_NET, kgn_conn::gnc_cqid, kgn_conn::gnc_device, kgn_conn::gnc_dgram_type, kgn_conn::gnc_fma_blk, kgn_conn::gnc_hashlist, kgn_conn::gnc_last_rx, kgn_conn::gnc_last_rx_cq, kgn_conn::gnc_last_tx, kgn_conn::gnc_list, kgn_conn::gnc_mbox_id, kgn_conn::gnc_peer, kgn_conn::gnc_state, kgn_conn::gnc_timeout, kgn_connreq::gncr_dstnid, kgn_connreq::gncr_srcnid, kgn_device::gnd_connd_lock, kgn_device::gnd_id, kgn_dgram::gndg_conn, kgn_dgram::gndg_conn_in, kgn_dgram::gndg_conn_out, kgn_dgram::gndg_state, kgn_dgram::gndg_type, GNILND_CONN_ESTABLISHED, GNILND_DGRAM_DONE, GNILND_MSG_NOOP, GNILND_PEER_IDLE, GNILND_RCA_NODE_DOWN, GNILND_RCA_NODE_UP, GNILND_TO2KA, GNILND_TX_ALLOCD, kgn_fma_memblock::gnm_mbox_info, kgn_net::gnn_dev, kgn_net::gnn_ni, kgn_peer::gnp_connd_list, kgn_peer::gnp_connecting, kgn_peer::gnp_conns, kgn_peer::gnp_down, kgn_peer::gnp_net, kgn_peer::gnp_nid, kgn_peer::gnp_pending_unlink, kgn_peer::gnp_reconnect_interval, kgn_peer::gnp_tx_queue, GOTO, kgn_data::kgn_conn_version, kgn_data::kgn_npending_unlink, kgn_data::kgn_peer_conn_lock, kgnilnd_add_peer_locked(), kgnilnd_admin_decref, kgnilnd_close_stale_conns_locked(), kgnilnd_conn_addref, kgnilnd_conn_decref, kgnilnd_conn_isdup_locked(), kgnilnd_cqid2connlist(), kgnilnd_create_peer_safe(), kgnilnd_data, kgnilnd_new_tx_msg(), kgnilnd_peer_addref, kgnilnd_peer_alive(), kgnilnd_peer_decref, kgnilnd_queue_tx(), kgnilnd_schedule_device(), kgnilnd_tx_del_state_locked(), libcfs_nid2str(), list_add_tail(), list_del_init(), list_empty(), list_for_each_entry_safe, LNET_NID_ANY, lnet_notify(), kgn_mbox_info::mbx_release_purg_active_dgram, lnet_ni::ni_nid, and RETURN.
Referenced by kgnilnd_process_connreq().
void kgnilnd_free_dgram (kgn_device_t * dev, kgn_dgram_t * dgram)
Definition at line 1180 of file gnilnd_conn.c.
References CDEBUG, D_MALLOC, D_NETTRACE, kgn_device::gnd_ndgrams, kgn_dgram::gndg_magic, kgn_dgram::gndg_state, GNILND_DGRAM_DONE, GNILND_DGRAM_USED, kgn_data::kgn_dgram_cache, kgnilnd_data, kgnilnd_dgram_state2str(), kgnilnd_dgram_type2str(), and LASSERTF.
Referenced by kgnilnd_post_dgram(), and kgnilnd_release_dgram().
void kgnilnd_free_fmablk_locked (kgn_device_t * dev, kgn_fma_memblock_t * fma_blk)
Definition at line 315 of file gnilnd_conn.c.
References CDEBUG, D_MALLOC, kgn_device::gnd_fmablk_vers, kgn_device::gnd_handle, kgn_device::gnd_n_mdd, kgn_device::gnd_n_mdd_held, GNILND_FMABLK_FREED, GNILND_FMABLK_PHYS, kgn_fma_memblock::gnm_avail_mboxs, kgn_fma_memblock::gnm_bit_array, kgn_fma_memblock::gnm_blk_size, kgn_fma_memblock::gnm_block, kgn_fma_memblock::gnm_bufflist, kgn_fma_memblock::gnm_held_mboxs, kgn_fma_memblock::gnm_hndl, kgn_fma_memblock::gnm_hold_timeout, kgn_fma_memblock::gnm_mbox_info, kgn_fma_memblock::gnm_mbox_size, kgn_fma_memblock::gnm_num_mboxs, kgn_fma_memblock::gnm_state, kgn_data::kgn_in_reset, kgn_data::kgn_mbox_cache, kgnilnd_data, kgnilnd_mem_mdd_release(), LASSERTF, LIBCFS_FREE, and list_del().
Referenced by kgnilnd_free_phys_fmablk(), and kgnilnd_release_mbox().
void kgnilnd_free_phys_fmablk (kgn_device_t * device)
Definition at line 661 of file gnilnd_conn.c.
References kgn_device::gnd_fma_buffs, kgn_device::gnd_fmablk_lock, kgn_device::gnd_fmablk_mutex, GNILND_FMABLK_PHYS, kgn_fma_memblock::gnm_state, kgnilnd_free_fmablk_locked(), and list_for_each_entry_safe.
Referenced by kgnilnd_base_shutdown().
int kgnilnd_map_fmablk (kgn_device_t * device, kgn_fma_memblock_t * fma_blk)
Definition at line 37 of file gnilnd_conn.c.
References __u64, CERROR, cfs_duration_sec(), cfs_time_seconds(), CNETERR, kgn_device::gnd_handle, kgn_device::gnd_n_mdd, kgn_device::gnd_nbytes_map, kgn_device::gnd_nfmablk, kgn_device::gnd_rcv_fma_cqh, GNI_MEM_PHYS_CONT, GNI_MEM_READWRITE, GNI_RC_SUCCESS, GNILND_FMABLK_PHYS, GNILND_REGFAILTO_DISABLE, kgn_fma_memblock::gnm_blk_size, kgn_fma_memblock::gnm_block, kgn_fma_memblock::gnm_hndl, kgn_fma_memblock::gnm_hold_timeout, kgn_fma_memblock::gnm_mbox_size, kgn_fma_memblock::gnm_state, kgn_tunables::kgn_reg_fail_timeout, kgnilnd_mem_register(), kgnilnd_tunables, LASSERTF, LBUG, gni_mem_handle::qword1, and RETURN.
Referenced by kgnilnd_alloc_fmablk(), and kgnilnd_map_phys_fmablk().
int kgnilnd_map_phys_fmablk (kgn_device_t * device)
Definition at line 616 of file gnilnd_conn.c.
References kgn_device::gnd_fma_buffs, kgn_device::gnd_fmablk_lock, kgn_device::gnd_fmablk_mutex, GNILND_FMABLK_PHYS, kgn_fma_memblock::gnm_state, kgnilnd_map_fmablk(), list_for_each_entry, and RETURN.
Referenced by kgnilnd_reset_stack().
static struct list_head* kgnilnd_nid2dgramlist (kgn_device_t * dev, lnet_nid_t nid) [static, read]
Definition at line 683 of file gnilnd_conn.c.
References kgn_device::gnd_dgrams, kgn_tunables::kgn_peer_hash_size, kgnilnd_tunables, and RETURN.
Referenced by kgnilnd_find_dgram_locked(), and kgnilnd_post_dgram().
int kgnilnd_pack_connreq (kgn_connreq_t * connreq, kgn_conn_t * conn, lnet_nid_t srcnid, lnet_nid_t dstnid, kgn_connreq_type_t type)
Definition at line 729 of file gnilnd_conn.c.
References CERROR, CFS_FAIL_CHECK, CFS_FAIL_GNI_CONNREQ_PROTO, CFS_FAIL_GNI_PACK_DSTNID, CFS_FAIL_GNI_PACK_SRCNID, CLASSERT, kgn_conn::gnc_cqid, kgn_conn::gnc_device, kgn_conn::gnc_my_connstamp, kgn_conn::gnc_timeout, kgn_connreq::gncr_connstamp, kgn_connreq::gncr_dstnid, kgn_connreq::gncr_gnparams, kgn_connreq::gncr_magic, kgn_connreq::gncr_peerstamp, kgn_connreq::gncr_srcnid, kgn_connreq::gncr_timeout, kgn_connreq::gncr_type, kgn_connreq::gncr_version, kgn_device::gnd_host_id, GNI_DATAGRAM_MAXSIZE, GNILND_CONNREQ_REQ, GNILND_CONNREQ_VERSION, GNILND_MSG_MAGIC, kgn_gniparams::gnpr_cqid, kgn_gniparams::gnpr_host_id, kgn_conn::gnpr_smsg_attr, kgn_gniparams::gnpr_smsg_attr, kgn_data::kgn_peerstamp, kgnilnd_data, and kgnilnd_setup_mbox().
Referenced by kgnilnd_post_dgram().
int kgnilnd_post_dgram (kgn_device_t * dev, lnet_nid_t dstnid, kgn_connreq_type_t type, int data_rc)
Definition at line 1199 of file gnilnd_conn.c.
References __u64, CDEBUG, CERROR, CFS_FAIL_CHECK, CFS_FAIL_GNI_PACK_DSTNID, CNETERR, D_NETTRACE, ENTRY, kgn_conn::gnc_ephandle, kgn_conn::gnc_state, kgn_connreq::gncr_nakdata, kgn_device::gnd_dgram_lock, kgn_device::gnd_id, kgn_device::gnd_nid, kgn_dgram::gndg_conn, kgn_dgram::gndg_conn_in, kgn_dgram::gndg_conn_out, kgn_dgram::gndg_post_time, kgn_dgram::gndg_type, GNI_RC_ERROR_NOMEM, GNI_RC_SUCCESS, GNILND, GNILND_CONN_CONNECTING, GNILND_CONN_LISTEN, GNILND_CONNREQ_NAK, GNILND_CONNREQ_REQ, GNILND_DGRAM_NAK, GNILND_DGRAM_POSTED, GNILND_DGRAM_REQ, GNILND_DGRAM_WC_REQ, kgn_nak_data::gnnd_errno, GOTO, kgnilnd_alloc_dgram(), kgnilnd_cleanup_dgram(), kgnilnd_connreq_type2str(), kgnilnd_create_conn(), kgnilnd_dgram_type2str(), kgnilnd_ep_bind(), kgnilnd_ep_postdata_w_id(), kgnilnd_find_dgram_locked(), kgnilnd_free_dgram(), kgnilnd_nid2dgramlist(), kgnilnd_nid_to_nicaddrs(), kgnilnd_pack_connreq(), LASSERTF, LBUG, libcfs_nid2str(), list_add_tail(), LNET_MKNET(), LNET_MKNID(), LNET_NID_ANY, LNET_NIDADDR(), LNET_NIDNET(), and RETURN.
Referenced by kgnilnd_release_dgram(), kgnilnd_repost_wc_dgrams(), kgnilnd_send_nak(), kgnilnd_setup_wildcard_dgram(), and kgnilnd_start_connect().
int kgnilnd_probe_and_process_dgram (kgn_device_t * dev)
Definition at line 2111 of file gnilnd_conn.c.
References CDEBUG, CERROR, CFS_FAIL_CHECK, CFS_FAIL_GNI_PAUSE_DGRAM_COMP, D_NET, D_NETTRACE, ENTRY, kgn_connreq::gncr_dstnid, kgn_connreq::gncr_srcnid, kgn_device::gnd_connd_lock, kgn_dgram::gndg_conn_in, kgn_dgram::gndg_conn_out, kgn_dgram::gndg_type, GNILND_DGRAM_NAK, GNILND_DGRAM_REQ, GNILND_DGRAM_WC_REQ, GNILND_PEER_CONNECT, GNILND_PEER_IDLE, kgn_net::gnn_dev, kgn_peer::gnp_connd_list, kgn_peer::gnp_connecting, kgn_peer::gnp_last_dgram_errno, kgn_peer::gnp_net, GOTO, kgn_data::kgn_peer_conn_lock, kgnilnd_data, kgnilnd_dgram_type2str(), kgnilnd_find_peer_locked(), kgnilnd_peer_addref, kgnilnd_peer_decref, kgnilnd_peer_increase_reconnect_locked(), kgnilnd_peer_notify(), kgnilnd_probe_for_dgram(), kgnilnd_process_connreq(), kgnilnd_release_dgram(), kgnilnd_send_nak(), LASSERTF, libcfs_nid2str(), list_del_init(), list_empty(), LNET_NID_ANY, and RETURN.
Referenced by kgnilnd_dgram_mover().
int kgnilnd_probe_for_dgram (kgn_device_t * dev, kgn_dgram_t ** dgramp)
Definition at line 1419 of file gnilnd_conn.c.
References __u64, CDEBUG, CNETERR, D_NET, ENTRY, kgn_conn::gnc_ephandle, kgn_device::gnd_dgram_lock, kgn_device::gnd_handle, kgn_dgram::gndg_conn, kgn_dgram::gndg_list, kgn_dgram::gndg_magic, kgn_dgram::gndg_state, GNI_RC_NO_MATCH, GNI_RC_SUCCESS, GNILND_DGRAM_CANCELED, GNILND_DGRAM_DONE, GNILND_DGRAM_MAGIC, GNILND_DGRAM_POSTED, GNILND_DGRAM_PROCESSING, GOTO, kgnilnd_dgram_state2str(), kgnilnd_dgram_type2str(), kgnilnd_ep_postdata_test_by_id(), kgnilnd_postdata_probe_by_id(), kgnilnd_process_dgram(), kgnilnd_release_dgram(), LASSERTF, libcfs_nid2str(), list_del_init(), list_empty(), LPU64, LPX64, RETURN, and unlikely.
Referenced by kgnilnd_probe_and_process_dgram(), and kgnilnd_wait_for_canceled_dgrams().
int kgnilnd_process_connreq (kgn_dgram_t * dgram, int * needs_nak)
Definition at line 2068 of file gnilnd_conn.c.
References CERROR, kgn_connreq::gncr_srcnid, kgn_connreq::gncr_type, kgn_dgram::gndg_conn_in, GNILND_CONNREQ_NAK, GNILND_CONNREQ_REQ, kgnilnd_connreq_type2str(), kgnilnd_finish_connect(), kgnilnd_process_nak(), kgnilnd_unpack_connreq(), libcfs_nid2str(), and RETURN.
Referenced by kgnilnd_probe_and_process_dgram().
int kgnilnd_process_dgram (kgn_dgram_t * dgram, gni_post_state_t post_state)
Definition at line 991 of file gnilnd_conn.c.
References CDEBUG, CERROR, cfs_duration_sec(), CNETERR, D_NETTRACE, kgn_conn::gnc_device, kgn_connreq::gncr_dstnid, kgn_device::gnd_canceled_dgrams, kgn_dgram::gndg_conn, kgn_dgram::gndg_conn_out, kgn_dgram::gndg_post_time, kgn_dgram::gndg_state, kgn_dgram::gndg_type, GNI_POST_COMPLETED, GNI_POST_PENDING, GNI_POST_TERMINATED, GNI_POST_TIMEOUT, GNILND_DGRAM_CANCELED, GNILND_DGRAM_WC_REQ, GOTO, kgnilnd_dgram_state2str(), kgnilnd_dgram_type2str(), LASSERTF, LBUG, libcfs_nid2str(), LNET_NID_ANY, and RETURN.
Referenced by kgnilnd_cancel_dgram_locked(), and kgnilnd_probe_for_dgram().
int kgnilnd_process_nak (kgn_dgram_t * dgram)
Definition at line 1985 of file gnilnd_conn.c.
References CDEBUG, D_NET, kgn_conn::gnc_device, kgn_conn::gnc_my_connstamp, kgn_conn::gnc_peer_connstamp, kgn_conn::gnc_peerstamp, kgn_connreq::gncr_connstamp, kgn_connreq::gncr_dstnid, kgn_connreq::gncr_nakdata, kgn_connreq::gncr_peerstamp, kgn_connreq::gncr_srcnid, kgn_device::gnd_connd_lock, kgn_dgram::gndg_conn, kgn_dgram::gndg_conn_in, GNILND_PEER_IDLE, kgn_net::gnn_dev, kgn_nak_data::gnnd_errno, kgn_peer::gnp_connd_list, kgn_peer::gnp_connecting, kgn_peer::gnp_conns, kgn_peer::gnp_net, kgn_peer::gnp_nid, kgn_data::kgn_peer_conn_lock, kgnilnd_close_stale_conns_locked(), kgnilnd_data, kgnilnd_find_and_cancel_dgram(), kgnilnd_find_peer_locked(), LCONSOLE_INFO, libcfs_nid2str(), and list_empty().
Referenced by kgnilnd_process_connreq().
void kgnilnd_reaper_dgram_check (kgn_device_t * dev)
Definition at line 2219 of file gnilnd_conn.c.
References CDEBUG, cfs_duration_sec(), cfs_time_seconds(), CNETERR, D_NETTRACE, kgn_connreq::gncr_dstnid, kgn_device::gnd_dgram_lock, kgn_device::gnd_dgrams, kgn_dgram::gndg_conn, kgn_dgram::gndg_conn_out, kgn_dgram::gndg_post_time, kgn_dgram::gndg_state, kgn_dgram::gndg_type, GNILND_DGRAM_POSTED, GNILND_DGRAM_WC_REQ, kgn_tunables::kgn_peer_hash_size, kgn_tunables::kgn_timeout, kgnilnd_cancel_dgram_locked(), kgnilnd_check_hw_quiesce(), kgnilnd_dgram_state2str(), kgnilnd_dgram_type2str(), kgnilnd_tunables, libcfs_nid2str(), list_for_each_entry_safe, now(), and timeout.
Referenced by kgnilnd_dgram_mover().
void kgnilnd_release_dgram (kgn_device_t * dev, kgn_dgram_t * dgram, int shutdown)
Definition at line 1348 of file gnilnd_conn.c.
References CDEBUG, D_NET, kgn_conn::gnc_list, kgn_conn::gnc_peer, kgn_conn::gnc_state, kgn_connreq::gncr_dstnid, kgn_device::gnd_dgram_lock, kgn_device::gnd_nwcdgrams, kgn_dgram::gndg_conn, kgn_dgram::gndg_conn_out, kgn_dgram::gndg_list, kgn_dgram::gndg_state, kgn_dgram::gndg_type, GNILND_CONN_CLOSED, GNILND_CONNREQ_REQ, GNILND_DGRAM_CANCELED, GNILND_DGRAM_DONE, GNILND_DGRAM_WC_REQ, kgn_peer::gnp_conns, kgn_peer::gnp_dirty_eps, kgn_data::kgn_in_reset, kgn_data::kgn_peer_conn_lock, kgn_data::kgn_wc_kill, kgnilnd_add_purgatory_locked(), kgnilnd_admin_addref, kgnilnd_cancel_dgram_locked(), kgnilnd_cleanup_dgram(), kgnilnd_conn_addref, kgnilnd_data, kgnilnd_find_peer_locked(), kgnilnd_free_dgram(), kgnilnd_peer_addref, kgnilnd_post_dgram(), kgnilnd_schedule_conn, LASSERTF, libcfs_nid2str(), list_add_tail(), list_empty(), LNET_NID_ANY, and unlikely.
Referenced by kgnilnd_cancel_wc_dgrams(), kgnilnd_probe_and_process_dgram(), kgnilnd_probe_for_dgram(), and kgnilnd_wait_for_canceled_dgrams().
void kgnilnd_release_mbox (kgn_conn_t * conn, int purgatory_hold)
Definition at line 468 of file gnilnd_conn.c.
References CDEBUG, CERROR, CFS_FAIL_CHECK, CFS_FAIL_GNI_FMABLK_AVAIL, D_NET, kgn_conn::gnc_device, kgn_conn::gnc_ephandle, kgn_conn::gnc_fma_blk, kgn_conn::gnc_mbox_id, kgn_conn::gnc_timeout, kgn_device::gnd_fma_buffs, kgn_device::gnd_fmablk_lock, GNILND_FMABLK_PHYS, GNILND_FMABLK_VIRT, kgn_fma_memblock::gnm_avail_mboxs, kgn_fma_memblock::gnm_bit_array, kgn_fma_memblock::gnm_held_mboxs, kgn_fma_memblock::gnm_hndl, kgn_fma_memblock::gnm_hold_timeout, kgn_fma_memblock::gnm_max_timeout, kgn_fma_memblock::gnm_mbox_info, kgn_fma_memblock::gnm_num_mboxs, kgn_fma_memblock::gnm_state, kgn_conn::gnpr_smsg_attr, kgnilnd_free_fmablk_locked(), kgnilnd_unmap_fmablk(), LASSERTF, list_for_each_entry, LPX64, MAX, kgn_mbox_info::mbx_nallocs, kgn_mbox_info::mbx_release_from_purgatory, gni_smsg_attr::msg_buffer, gni_mem_handle::qword1, and gni_mem_handle::qword2.
Referenced by kgnilnd_add_purgatory_locked(), kgnilnd_destroy_conn(), and kgnilnd_release_purgatory_list().
int kgnilnd_repost_wc_dgrams (kgn_device_t * dev)
Definition at line 2414 of file gnilnd_conn.c.
References CDEBUG, D_NETERROR, ENTRY, kgn_device::gnd_id, kgn_device::gnd_nwcdgrams, GNILND_CONNREQ_REQ, kgnilnd_admin_decref, kgnilnd_post_dgram(), LNET_NID_ANY, and RETURN.
Referenced by kgnilnd_dgram_mover().
void kgnilnd_send_nak (kgn_device_t * dev, lnet_nid_t dst_nid, int error)
Definition at line 1967 of file gnilnd_conn.c.
References CDEBUG, D_NET, ENTRY, EXIT, GNILND_CONNREQ_NAK, kgnilnd_post_dgram(), LASSERTF, libcfs_nid2str(), and LNET_NID_ANY.
Referenced by kgnilnd_probe_and_process_dgram().
int kgnilnd_setup_mbox (kgn_conn_t * conn)
Definition at line 441 of file gnilnd_conn.c.
References CNETERR, kgn_conn::gnc_device, kgn_conn::gnpr_smsg_attr, kgnilnd_alloc_fmablk(), kgnilnd_find_free_mbox(), and gni_smsg_attr::msg_buffer.
Referenced by kgnilnd_pack_connreq().
void kgnilnd_setup_smsg_attr (gni_smsg_attr_t * smsg_attr)
Definition at line 29 of file gnilnd_conn.c.
References GNI_SMSG_TYPE_MBOX_AUTO_RETRANSMIT, GNILND_MAX_MSG_SIZE, kgn_tunables::kgn_mbox_credits, kgnilnd_tunables, gni_smsg_attr::mbox_maxcredit, gni_smsg_attr::msg_maxsize, and gni_smsg_attr::msg_type.
Referenced by kgnilnd_alloc_fmablk(), and kgnilnd_find_free_mbox().
int kgnilnd_setup_wildcard_dgram (kgn_device_t * dev)
Definition at line 1526 of file gnilnd_conn.c.
References CERROR, ENTRY, GNILND_CONNREQ_REQ, GOTO, kgn_tunables::kgn_nwildcard, kgnilnd_post_dgram(), kgnilnd_tunables, LNET_NID_ANY, and RETURN.
Referenced by kgnilnd_base_startup(), and kgnilnd_reset_stack().
int kgnilnd_start_connect (kgn_peer_t * peer)
Definition at line 1710 of file gnilnd_conn.c.
References CDEBUG, CFS_FAIL_CHECK, CFS_FAIL_GNI_GNP_CONNECTING1, CFS_FAIL_GNI_GNP_CONNECTING2, CFS_FAIL_GNI_GNP_CONNECTING3, CFS_FAIL_TIMEOUT, cfs_fail_val, D_NET, GNILND_CONNREQ_REQ, GNILND_PEER_CONNECT, GNILND_PEER_KILL, GNILND_PEER_NEEDS_DEATH, GNILND_PEER_POSTED, GNILND_PEER_POSTING, kgn_net::gnn_dev, kgn_peer::gnp_connecting, kgn_peer::gnp_last_dgram_errno, kgn_peer::gnp_last_dgram_time, kgn_peer::gnp_net, kgn_peer::gnp_nid, GOTO, kgn_data::kgn_peer_conn_lock, kgnilnd_data, kgnilnd_find_and_cancel_dgram(), kgnilnd_peer_active(), kgnilnd_post_dgram(), libcfs_nid2str(), and RETURN.
Referenced by kgnilnd_start_outbound_dgrams().
int kgnilnd_start_outbound_dgrams (kgn_device_t * dev, unsigned long deadline)
Definition at line 2318 of file gnilnd_conn.c.
References CDEBUG, CNETERR, D_NET, kgn_device::gnd_connd_lock, kgn_device::gnd_connd_peers, GNILND_PEER_CONNECT, GNILND_PEER_IDLE, GNILND_PEER_KILL, GNILND_PEER_NEEDS_DEATH, GNILND_PEER_POSTING, kgn_peer::gnp_connd_list, kgn_peer::gnp_connecting, kgn_peer::gnp_nid, kgn_data::kgn_peer_conn_lock, kgnilnd_data, kgnilnd_peer_decref, kgnilnd_peer_increase_reconnect_locked(), kgnilnd_start_connect(), LASSERTF, libcfs_nid2str(), likely, list_add_tail(), list_del_init(), list_empty(), and RETURN.
Referenced by kgnilnd_dgram_mover().
void kgnilnd_unmap_fma_blocks (kgn_device_t * device)
Definition at line 642 of file gnilnd_conn.c.
References kgn_device::gnd_fma_buffs, kgn_device::gnd_fmablk_lock, kgn_device::gnd_fmablk_mutex, kgnilnd_unmap_fmablk(), and list_for_each_entry.
Referenced by kgnilnd_base_shutdown(), and kgnilnd_reset_stack().
void kgnilnd_unmap_fmablk (kgn_device_t * dev, kgn_fma_memblock_t * fma_blk)
Definition at line 258 of file gnilnd_conn.c.
References CDEBUG, D_CONSOLE, D_MALLOC, D_NETERROR, kgn_device::gnd_fmablk_vers, kgn_device::gnd_handle, kgn_device::gnd_n_mdd, kgn_device::gnd_n_mdd_held, kgn_device::gnd_nbytes_map, kgn_device::gnd_nfmablk, GNI_RC_SUCCESS, GNILND_FMABLK_IDLE, GNILND_FMABLK_PHYS, GNILND_TIMEOUT2DEADMAN, kgn_fma_memblock::gnm_avail_mboxs, kgn_fma_memblock::gnm_blk_size, kgn_fma_memblock::gnm_held_mboxs, kgn_fma_memblock::gnm_hndl, kgn_fma_memblock::gnm_hold_timeout, kgn_fma_memblock::gnm_mbox_size, kgn_fma_memblock::gnm_num_mboxs, kgn_fma_memblock::gnm_state, kgn_data::kgn_in_reset, kgn_data::kgn_shutdown, kgnilnd_data, kgnilnd_fmablk_state2str(), kgnilnd_mem_deregister(), LASSERTF, gni_mem_handle::qword1, and gni_mem_handle::qword2.
Referenced by kgnilnd_release_mbox(), and kgnilnd_unmap_fma_blocks().
int kgnilnd_unpack_connreq (kgn_dgram_t * dgram)
Definition at line 796 of file gnilnd_conn.c.
References __swab16s, __swab32, __swab32s, __swab64s, __u64, gni_smsg_attr::buff_size, CERROR, CFS_FAIL_CHECK, CFS_FAIL_GNI_CONNREQ_DROP, kgn_connreq::gncr_cksum, kgn_connreq::gncr_connstamp, kgn_connreq::gncr_dstnid, kgn_connreq::gncr_gnparams, kgn_connreq::gncr_magic, kgn_connreq::gncr_nakdata, kgn_connreq::gncr_peerstamp, kgn_connreq::gncr_srcnid, kgn_connreq::gncr_timeout, kgn_connreq::gncr_type, kgn_connreq::gncr_version, kgn_dgram::gndg_conn_in, kgn_dgram::gndg_conn_out, GNILND_CONNREQ_CLOSE, GNILND_CONNREQ_NAK, GNILND_CONNREQ_REQ, GNILND_CONNREQ_VERSION, GNILND_MIN_TIMEOUT, GNILND_MSG_MAGIC, kgn_net::gnn_ni, kgn_nak_data::gnnd_errno, kgn_gniparams::gnpr_cqid, kgn_gniparams::gnpr_host_id, kgn_gniparams::gnpr_smsg_attr, kgnilnd_dgram_type2str(), kgnilnd_find_net(), kgnilnd_net_decref, kgnilnd_set_conn_params(), LASSERTF, libcfs_nid2str(), LNET_NID_ANY, LNET_NIDADDR(), LPU64, gni_smsg_attr::mbox_maxcredit, gni_smsg_attr::mbox_offset, gni_smsg_attr::mem_hndl, gni_smsg_attr::msg_buffer, gni_smsg_attr::msg_maxsize, gni_smsg_attr::msg_type, lnet_ni::ni_nid, gni_mem_handle::qword1, and gni_mem_handle::qword2.
Referenced by kgnilnd_process_connreq().
void kgnilnd_wait_for_canceled_dgrams (kgn_device_t * dev)
Definition at line 1664 of file gnilnd_conn.c.
References __u64, CDEBUG, D_NET, D_WARNING, kgn_device::gnd_canceled_dgrams, kgn_device::gnd_handle, kgn_device::gnd_id, GNI_RC_SUCCESS, kgnilnd_postdata_probe_wait_by_id(), kgnilnd_probe_for_dgram(), kgnilnd_release_dgram(), and LPX64.
Referenced by kgnilnd_base_shutdown(), kgnilnd_reset_stack(), and kgnilnd_shutdown().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.