Lustre: lnet/klnds/gnilnd/gnilnd.h File Reference
lnet/klnds/gnilnd/gnilnd.h File Reference
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/mm.h>
#include <linux/string.h>
#include <linux/stat.h>
#include <linux/errno.h>
#include <linux/unistd.h>
#include <linux/uio.h>
#include <linux/time.h>
#include <asm/timex.h>
#include <asm/uaccess.h>
#include <asm/io.h>
#include <linux/init.h>
#include <linux/fs.h>
#include <linux/file.h>
#include <linux/list.h>
#include <linux/kmod.h>
#include <linux/sysctl.h>
#include <linux/kthread.h>
#include <linux/nmi.h>
#include <net/sock.h>
#include <linux/in.h>
#include <libcfs/libcfs.h>
#include <lnet/lnet.h>
#include <lnet/lib-lnet.h>
#include <gni_pub.h>
#include "gnilnd_version.h"
#include "gnilnd_hss_ops.h"
#include "gnilnd_api_wrap.h"
Data Structures
struct kgn_gniparams
struct kgn_nak_data
struct kgn_connreq
struct WIRE_ATTR
struct WIRE_ATTR
struct WIRE_ATTR
struct WIRE_ATTR
struct WIRE_ATTR
struct WIRE_ATTR
struct WIRE_ATTR
struct kgn_tunables
struct kgn_mbox_info
struct kgn_fma_memblock
struct kgn_device
struct kgn_net
struct kgn_tx_ev_id
struct kgn_dgram
struct kgn_tx
struct kgn_conn
struct kgn_mdd_purgatory
struct kgn_peer
struct kgn_rx
struct kgn_data
Defines
#define DEBUG_SUBSYSTEM S_LND
#define GNILND_MIN_TIMEOUT 5
#define GNILND_TO2KA(t) (((t)-1)/2)
#define GNILND_MIN_RECONNECT_TO (GNILND_BASE_TIMEOUT/4)
#define GNILND_MAX_RECONNECT_TO GNILND_BASE_TIMEOUT
#define GNILND_HARDWARE_TIMEOUT 15
#define GNILND_MDD_TIMEOUT 15
#define GNILND_SCHED_TIMEOUT 1
#define GNILND_DGRAM_TIMEOUT 2
#define GNILND_FAST_MAPPING_TRY *kgnilnd_tunables.kgn_max_retransmits
#define GNILND_MAP_RETRY_RATE 1
#define GNILND_MAP_TIMEOUT
#define GNILND_REAPER_THREAD_WAKE 1
#define GNILND_REAPER_NCHECKS 4
#define GNILND_MAXDEVS 1
#define GNILND_MBOX_CREDITS 256
#define GNILND_CONN_MAGIC 0xa100f
#define GNILND_CHECKSUM_OFF 0
#define GNILND_CHECKSUM_SMSG_HEADER 1
#define GNILND_CHECKSUM_SMSG 2
#define GNILND_CHECKSUM_SMSG_BTE 3
#define GNILND_FMABLK 1024
#define GNILND_SCHED_NICE -20
#define GNILND_COMPUTE 0
#define GNILND_FAST_RECONNECT 0
#define GNILND_EXTRA_BITS 1
#define GNILND_CQID_NBITS (21 - GNILND_EXTRA_BITS)
#define GNILND_MSGID_TX_NBITS (32 - GNILND_CQID_NBITS)
#define GNILND_MAX_CQID (1 << GNILND_CQID_NBITS)
#define GNILND_MAX_MSG_ID (1 << GNILND_MSGID_TX_NBITS)
#define GNILND_MAX_MSG_SIZE (*kgnilnd_tunables.kgn_max_immediate + sizeof(kgn_msg_t))
#define GNILND_MAX_IMMEDIATE (64<<10)
#define GNILND_PURGATORY_MAX 5
#define GNILND_NOPURG 222
#define GNILND_MBOX_PAYLOAD
#define GNILND_TIMEOUT2DEADMAN ((*kgnilnd_tunables.kgn_mdd_timeout) * 1000 * 60)
#define GNILND_TIMEOUTRX(t) (t + cfs_time_seconds(*kgnilnd_tunables.kgn_hardware_timeout))
#define GNILND_PURG_RELEASE(t) (GNILND_TIMEOUTRX(t) * 3)
#define GNILND_LASTRX(conn)
#define GNILND_REGFAILTO_DISABLE -1
#define GNILND_INIT_NOTHING 0
#define GNILND_INIT_DATA 1
#define GNILND_INIT_ALL 2
#define GNILND_BUF_NONE 0
#define GNILND_BUF_IMMEDIATE 1
#define GNILND_BUF_IMMEDIATE_KIOV 2
#define GNILND_BUF_PHYS_UNMAPPED 3
#define GNILND_BUF_PHYS_MAPPED 4
#define GNILND_BUF_VIRT_UNMAPPED 5
#define GNILND_BUF_VIRT_MAPPED 6
#define GNILND_TX_WAITING_REPLY (1<<1)
#define GNILND_TX_WAITING_COMPLETION (1<<2)
#define GNILND_TX_PENDING_RDMA (1<<3)
#define GNILND_TX_QUIET_ERROR (1<<4)
#define GNILND_TX_FAIL_SMSG (1<<5)
#define GNILND_MSGID_NOOP (GNILND_MAX_CQID + 128)
#define GNILND_MSGID_CLOSE (GNILND_MSGID_NOOP + 1)
#define GNILND_MSG_NONE 0x00
#define GNILND_MSG_NOOP 0x01
#define GNILND_MSG_IMMEDIATE 0x02
#define GNILND_MSG_PUT_REQ 0x03
#define GNILND_MSG_PUT_NAK 0x04
#define GNILND_MSG_PUT_ACK 0x05
#define GNILND_MSG_PUT_DONE 0x06
#define GNILND_MSG_GET_REQ 0x07
#define GNILND_MSG_GET_NAK 0x08
#define GNILND_MSG_GET_DONE 0x09
#define GNILND_MSG_CLOSE 0x0a
#define GNILND_MSG_PUT_REQ_REV 0x0b
#define GNILND_MSG_PUT_DONE_REV 0x0c
#define GNILND_MSG_PUT_NAK_REV 0x0d
#define GNILND_MSG_GET_REQ_REV 0x0e
#define GNILND_MSG_GET_ACK_REV 0x0f
#define GNILND_MSG_GET_DONE_REV 0x10
#define GNILND_MSG_GET_NAK_REV 0x11
#define GNILND_CONN_IDLE 0
#define GNILND_CONN_SCHED 1
#define GNILND_CONN_WANTS_SCHED 2
#define GNILND_CONN_PROCESS 3
#define GNILND_DEV_IDLE 0
#define GNILND_DEV_IRQ 1
#define GNILND_DEV_LOOP 2
#define GNILND_DGRAM_IDLE 0
#define GNILND_DGRAM_SCHED 1
#define GNILND_DGRAM_PROCESS 2
#define GNILND_PEER_IDLE 0
#define GNILND_PEER_CONNECT 1
#define GNILND_PEER_POSTING 2
#define GNILND_PEER_POSTED 3
#define GNILND_PEER_NEEDS_DEATH 4
#define GNILND_PEER_KILL 5
#define GNILND_CLOSE_RX 1
#define GNILND_CLOSE_INJECT1 2
#define GNILND_CLOSE_INJECT2 3
#define GNILND_CLOSE_EARLY 4
#define GNILND_QUIESCE_IDLE 0
#define GNILND_QUIESCE_ADMIN 1
#define GNILND_QUIESCE_RESET 2
#define GNILND_QUIESCE_HW_QUIESCE 3
#define GNILND_PEER_CLEAN 0
#define GNILND_PEER_PERSISTING 1
#define GNILND_DEL_CONN 0
#define GNILND_DEL_PEER 1
#define GNILND_CLEAR_PURGATORY 2
#define GNILND_RCA_NODE_UP 0
#define GNILND_RCA_NODE_DOWN 1
#define GNILND_RCA_NODE_UNKNOWN 2
#define GNILND_REVERSE_NONE 0
#define GNILND_REVERSE_GET 1
#define GNILND_REVERSE_PUT 2
#define GNILND_REVERSE_BOTH (GNILND_REVERSE_GET | GNILND_REVERSE_PUT)
#define GNILND_MSG_MAGIC LNET_PROTO_GNI_MAGIC
#define GNILND_DGRAM_MAGIC 0x0DDBA11
#define GNILND_MSG_VERSION 8
#define GNILND_CONNREQ_VERSION 2
#define kgnilnd_schedule_conn(conn) _kgnilnd_schedule_conn(conn, __func__, __LINE__, 0);
#define kgnilnd_schedule_conn_refheld(conn, refheld) _kgnilnd_schedule_conn(conn, __func__, __LINE__, refheld);
#define kgnilnd_debug_msg(msgdata, mask, cdls, msg, fmt, a...)
#define GNIDBG_MSG(level, msg, fmt, args...)
#define GNIDBG_TOMSG(level, msg, fmt, args...)
#define kgnilnd_debug_conn(msgdata, mask, cdls, conn, fmt, a...)
#define GNIDBG_CONN(level, conn, fmt, args...)
#define kgnilnd_debug_tx(msgdata, mask, cdls, tx, fmt, a...)
#define GNIDBG_TX(level, tx, fmt, args...)
#define GNITX_ASSERTF(tx, cond, fmt, a...)
#define GNILND_IS_QUIESCED
#define KGNILND_SPIN_QUIESCE
#define kgnilnd_admin_addref(atomic)
#define kgnilnd_admin_decref(atomic)
#define kgnilnd_net_addref(net)
#define kgnilnd_net_decref(net)
#define kgnilnd_peer_addref(peer)
#define kgnilnd_peer_decref(peer)
#define kgnilnd_conn_addref(conn)
#define kgnilnd_conn_decref(conn)
#define KGNILND_POISON(ptr, c, s) memset(ptr, c, s)
#define DO_TYPE(x) case x: return #x;
Typedefs
typedef enum kgn_fmablk_state kgn_fmablk_state_t
typedef enum kgn_tx_list_state kgn_tx_list_state_t
typedef enum kgn_conn_state kgn_conn_state_t
typedef enum kgn_connreq_type kgn_connreq_type_t
typedef enum kgn_dgram_state kgn_dgram_state_t
typedef enum kgn_dgram_type kgn_dgram_type_t
typedef struct kgn_gniparams kgn_gniparams_t
typedef struct kgn_nak_data kgn_nak_data_t
typedef struct kgn_connreq kgn_connreq_t
typedef struct kgn_tunables kgn_tunables_t
typedef struct kgn_mbox_info kgn_mbox_info_t
typedef struct kgn_fma_memblock kgn_fma_memblock_t
typedef struct kgn_device kgn_device_t
typedef struct kgn_net kgn_net_t
typedef struct kgn_tx_ev_id kgn_tx_ev_id_t
typedef struct kgn_dgram kgn_dgram_t
typedef struct kgn_tx kgn_tx_t
typedef struct kgn_conn kgn_conn_t
typedef struct kgn_mdd_purgatory kgn_mdd_purgatory_t
typedef struct kgn_peer kgn_peer_t
typedef struct kgn_rx kgn_rx_t
typedef struct kgn_data kgn_data_t
Enumerations
enum kgn_fmablk_state { GNILND_FMABLK_IDLE = 0, GNILND_FMABLK_PHYS, GNILND_FMABLK_VIRT, GNILND_FMABLK_FREED }
enum kgn_tx_list_state {
GNILND_TX_IDLE = 0, GNILND_TX_ALLOCD, GNILND_TX_PEERQ, GNILND_TX_MAPQ,
GNILND_TX_FMAQ, GNILND_TX_LIVE_FMAQ, GNILND_TX_RDMAQ, GNILND_TX_LIVE_RDMAQ,
GNILND_TX_DYING, GNILND_TX_FREED
}
enum kgn_conn_state {
GNILND_CONN_DUMMY = 0, GNILND_CONN_LISTEN, GNILND_CONN_CONNECTING, GNILND_CONN_ESTABLISHED,
GNILND_CONN_CLOSING, GNILND_CONN_CLOSED, GNILND_CONN_DONE, GNILND_CONN_DESTROY_EP
}
enum kgn_connreq_type { GNILND_CONNREQ_REQ = 1, GNILND_CONNREQ_NAK, GNILND_CONNREQ_CLOSE }
enum kgn_dgram_state {
GNILND_DGRAM_USED = 1, GNILND_DGRAM_POSTING, GNILND_DGRAM_POSTED, GNILND_DGRAM_PROCESSING,
GNILND_DGRAM_CANCELED, GNILND_DGRAM_DONE
}
enum kgn_dgram_type { GNILND_DGRAM_REQ = 1, GNILND_DGRAM_WC_REQ, GNILND_DGRAM_NAK, GNILND_DGRAM_CLOSE }
Functions
static lnet_nid_t kgnilnd_lnd2lnetnid (lnet_nid_t ni_nid, lnet_nid_t kgnilnd_nid)
static lnet_nid_t kgnilnd_lnet2lndnid (lnet_nid_t lnet_nid, lnet_nid_t kgnilnd_nid)
void kgnilnd_destroy_peer (kgn_peer_t *peer)
void kgnilnd_destroy_conn (kgn_conn_t *conn)
int _kgnilnd_schedule_conn (kgn_conn_t *conn, const char *caller, int line, int refheld)
static void kgnilnd_thread_fini (void)
static void kgnilnd_gl_mutex_lock (struct mutex *lock)
static void kgnilnd_gl_mutex_unlock (struct mutex *lock)
static void kgnilnd_conn_mutex_lock (struct mutex *lock)
static void kgnilnd_conn_mutex_unlock (struct mutex *lock)
static int __kgnilnd_mutex_trylock (struct mutex *lock)
static int kgnilnd_mutex_trylock (struct mutex *lock)
static int kgnilnd_trylock (struct mutex *cq_lock, struct mutex *c_lock)
static void * kgnilnd_vzalloc (int size)
void _kgnilnd_debug_msg (kgn_msg_t *msg, struct libcfs_debug_msg_data *data, const char *fmt,...)
void _kgnilnd_debug_conn (kgn_conn_t *conn, struct libcfs_debug_msg_data *data, const char *fmt,...)
void _kgnilnd_debug_tx (kgn_tx_t *tx, struct libcfs_debug_msg_data *data, const char *fmt,...)
static struct list_head * kgnilnd_nid2peerlist (lnet_nid_t nid)
static struct list_head * kgnilnd_netnum2netlist (__u16 netnum)
static int kgnilnd_peer_active (kgn_peer_t *peer)
static int kgnilnd_can_unlink_peer_locked (kgn_peer_t *peer)
static int kgnilnd_conn_clean_errno (int errno)
static int kgnilnd_check_purgatory_errno (int errno)
static int kgnilnd_check_purgatory_conn (kgn_conn_t *conn)
static const char * kgnilnd_tx_state2str (kgn_tx_list_state_t state)
static struct list_head * kgnilnd_tx_state2list (kgn_peer_t *peer, kgn_conn_t *conn, kgn_tx_list_state_t to_state)
static void kgnilnd_tx_add_state_locked (kgn_tx_t *tx, kgn_peer_t *peer, kgn_conn_t *conn, kgn_tx_list_state_t state, int add_tail)
static void kgnilnd_tx_del_state_locked (kgn_tx_t *tx, kgn_peer_t *peer, kgn_conn_t *conn, kgn_tx_list_state_t new_state)
static int kgnilnd_tx_mapped (kgn_tx_t *tx)
static struct list_head * kgnilnd_cqid2connlist (__u32 cqid)
static kgn_conn_t * kgnilnd_cqid2conn_locked (__u32 cqid)
static __u32 kgnilnd_get_cqid_locked (void)
static void kgnilnd_validate_tx_ev_id (kgn_tx_ev_id_t *ev_id, kgn_tx_t **txp, kgn_conn_t **connp)
static struct timespec kgnilnd_ts_sub (struct timespec lhs, struct timespec rhs)
static int kgnilnd_count_list (struct list_head *q)
static int kgnilnd_find_net (lnet_nid_t nid, kgn_net_t **netp)
int kgnilnd_dev_init (kgn_device_t *dev)
void kgnilnd_dev_fini (kgn_device_t *dev)
int kgnilnd_startup (lnet_ni_t *ni)
void kgnilnd_shutdown (lnet_ni_t *ni)
int kgnilnd_base_startup (void)
void kgnilnd_base_shutdown (void)
int kgnilnd_allocate_phys_fmablk (kgn_device_t *device)
int kgnilnd_map_phys_fmablk (kgn_device_t *device)
void kgnilnd_unmap_fma_blocks (kgn_device_t *device)
void kgnilnd_free_phys_fmablk (kgn_device_t *device)
int kgnilnd_ctl (lnet_ni_t *ni, unsigned int cmd, void *arg)
void kgnilnd_query (lnet_ni_t *ni, lnet_nid_t nid, cfs_time_t *when)
int kgnilnd_send (lnet_ni_t *ni, void *private, lnet_msg_t *lntmsg)
int kgnilnd_eager_recv (lnet_ni_t *ni, void *private, lnet_msg_t *lntmsg, void **new_private)
int kgnilnd_recv (lnet_ni_t *ni, void *private, lnet_msg_t *lntmsg, int delayed, unsigned int niov, struct kvec *iov, lnet_kiov_t *kiov, unsigned int offset, unsigned int mlen, unsigned int rlen)
__u16 kgnilnd_cksum_kiov (unsigned int nkiov, lnet_kiov_t *kiov, unsigned int offset, unsigned int nob, int dump_blob)
void kgnilnd_add_purgatory_locked (kgn_conn_t *conn, kgn_peer_t *peer)
void kgnilnd_mark_for_detach_purgatory_all_locked (kgn_peer_t *peer)
void kgnilnd_detach_purgatory_locked (kgn_conn_t *conn, struct list_head *conn_list)
void kgnilnd_release_purgatory_list (struct list_head *conn_list)
void kgnilnd_update_reaper_timeout (long timeout)
void kgnilnd_unmap_buffer (kgn_tx_t *tx, int error)
kgn_tx_t * kgnilnd_new_tx_msg (int type, lnet_nid_t source)
void kgnilnd_tx_done (kgn_tx_t *tx, int completion)
void kgnilnd_txlist_done (struct list_head *txlist, int error)
void kgnilnd_unlink_peer_locked (kgn_peer_t *peer)
int kgnilnd_schedule_process_conn (kgn_conn_t *conn, int sched_intent)
void kgnilnd_schedule_dgram (kgn_device_t *dev)
int kgnilnd_create_peer_safe (kgn_peer_t **peerp, lnet_nid_t nid, kgn_net_t *net, int node_state)
void kgnilnd_add_peer_locked (lnet_nid_t nid, kgn_peer_t *new_stub_peer, kgn_peer_t **peerp)
int kgnilnd_add_peer (kgn_net_t *net, lnet_nid_t nid, kgn_peer_t **peerp)
kgn_peer_t * kgnilnd_find_peer_locked (lnet_nid_t nid)
int kgnilnd_del_conn_or_peer (kgn_net_t *net, lnet_nid_t nid, int command, int error)
void kgnilnd_peer_increase_reconnect_locked (kgn_peer_t *peer)
void kgnilnd_queue_reply (kgn_conn_t *conn, kgn_tx_t *tx)
void kgnilnd_queue_tx (kgn_conn_t *conn, kgn_tx_t *tx)
void kgnilnd_launch_tx (kgn_tx_t *tx, kgn_net_t *net, lnet_process_id_t *target)
int kgnilnd_send_mapped_tx (kgn_tx_t *tx, int try_map_if_full)
void kgnilnd_consume_rx (kgn_rx_t *rx)
void kgnilnd_schedule_device (kgn_device_t *dev)
void kgnilnd_device_callback (__u32 devid, __u64 arg)
void kgnilnd_schedule_device_timer (unsigned long arg)
int kgnilnd_reaper (void *arg)
int kgnilnd_scheduler (void *arg)
int kgnilnd_dgram_mover (void *arg)
int kgnilnd_rca (void *arg)
int kgnilnd_thread_start (int(*fn)(void *arg), void *arg, char *name, int id)
int kgnilnd_create_conn (kgn_conn_t **connp, kgn_device_t *dev)
int kgnilnd_conn_isdup_locked (kgn_peer_t *peer, kgn_conn_t *newconn)
kgn_conn_t * kgnilnd_find_conn_locked (kgn_peer_t *peer)
int kgnilnd_get_conn (kgn_conn_t **connp, kgn_peer_t)
kgn_conn_t * kgnilnd_find_or_create_conn_locked (kgn_peer_t *peer)
void kgnilnd_peer_cancel_tx_queue (kgn_peer_t *peer)
void kgnilnd_cancel_peer_connect_locked (kgn_peer_t *peer, struct list_head *zombies)
int kgnilnd_close_stale_conns_locked (kgn_peer_t *peer, kgn_conn_t *newconn)
void kgnilnd_peer_alive (kgn_peer_t *peer)
void kgnilnd_peer_notify (kgn_peer_t *peer, int error, int alive)
void kgnilnd_close_conn_locked (kgn_conn_t *conn, int error)
void kgnilnd_close_conn (kgn_conn_t *conn, int error)
void kgnilnd_complete_closed_conn (kgn_conn_t *conn)
void kgnilnd_destroy_conn_ep (kgn_conn_t *conn)
int kgnilnd_close_peer_conns_locked (kgn_peer_t *peer, int why)
int kgnilnd_report_node_state (lnet_nid_t nid, int down)
void kgnilnd_wakeup_rca_thread (void)
int kgnilnd_start_rca_thread (void)
int kgnilnd_get_node_state (__u32 nid)
int kgnilnd_tunables_init (void)
void kgnilnd_init_msg (kgn_msg_t *msg, int type, lnet_nid_t source)
void kgnilnd_bump_timeouts (__u32 nap_time, char *reason)
void kgnilnd_pause_threads (void)
int kgnilnd_hw_in_quiesce (void)
int kgnilnd_check_hw_quiesce (void)
void kgnilnd_quiesce_wait (char *reason)
void kgnilnd_quiesce_end_callback (gni_nic_handle_t nic_handle, uint64_t msecs)
int kgnilnd_ruhroh_thread (void *arg)
void kgnilnd_reset_stack (void)
void kgnilnd_critical_error (gni_err_handle_t err_handle)
void kgnilnd_insert_sysctl (void)
void kgnilnd_remove_sysctl (void)
void kgnilnd_proc_init (void)
void kgnilnd_proc_fini (void)
void kgnilnd_release_mbox (kgn_conn_t *conn, int purgatory_hold)
int kgnilnd_find_and_cancel_dgram (kgn_device_t *dev, lnet_nid_t dst_nid)
void kgnilnd_cancel_dgram_locked (kgn_dgram_t *dgram)
void kgnilnd_release_dgram (kgn_device_t *dev, kgn_dgram_t *dgram, int shutdown)
int kgnilnd_setup_wildcard_dgram (kgn_device_t *dev)
int kgnilnd_cancel_net_dgrams (kgn_net_t *net)
int kgnilnd_cancel_wc_dgrams (kgn_device_t *dev)
int kgnilnd_cancel_dgrams (kgn_device_t *dev)
void kgnilnd_wait_for_canceled_dgrams (kgn_device_t *dev)
int kgnilnd_dgram_waitq (void *arg)
int kgnilnd_set_conn_params (kgn_dgram_t *dgram)
static const char * kgnilnd_fmablk_state2str (kgn_fmablk_state_t state)
static const char * kgnilnd_msgtype2str (int type)
static const char * kgnilnd_conn_state2str (kgn_conn_t *conn)
static const char * kgnilnd_connreq_type2str (kgn_connreq_t *connreq)
static const char * kgnilnd_dgram_state2str (kgn_dgram_t *dgram)
static const char * kgnilnd_dgram_type2str (kgn_dgram_t *dgram)
static const char * kgnilnd_conn_dgram_type2str (kgn_dgram_type_t type)
static void kgnilnd_check_kgni_version (void)
Variables
kgn_data_t kgnilnd_data
kgn_tunables_t kgnilnd_tunables
uint32_t kgni_driver_version
Define Documentation
#define DEBUG_SUBSYSTEM S_LND
Definition at line 65 of file gnilnd.h.
#define DO_TYPE (x) case x: return #x;
Definition at line 1849 of file gnilnd.h.
Referenced by kgnilnd_conn_dgram_type2str(), kgnilnd_conn_state2str(), kgnilnd_connreq_type2str(), kgnilnd_dgram_state2str(), kgnilnd_dgram_type2str(), kgnilnd_msgtype2str(), and kgnilnd_tx_state2str().
#define GNIDBG_CONN (level, conn, fmt, args...)
Value:
do {                                                                            \
        if ((level) & (D_ERROR | D_WARNING | D_NETERROR)) {                     \
            static struct cfs_debug_limit_state cdls;                           \
            LIBCFS_DEBUG_MSG_DATA_DECL(msgdata, level, &cdls);                  \
            kgnilnd_debug_conn(&msgdata, level, &cdls, conn,                    \
                               "$$ "fmt" ", ## args);                           \
        } else {                                                                \
            LIBCFS_DEBUG_MSG_DATA_DECL(msgdata, level, NULL);                   \
            kgnilnd_debug_conn(&msgdata, level, NULL, conn,                     \
                               "$$ "fmt" ", ## args);                           \
        }                                                                       \
} while (0)
Definition at line 1042 of file gnilnd.h.
Referenced by kgnilnd_check_conn_timeouts_locked(), kgnilnd_check_fma_rx(), and kgnilnd_sendmsg_nolock().
#define GNIDBG_MSG (level, msg, fmt, args...)
Value:
do {                                                                          \
        if ((level) & (D_ERROR | D_WARNING | D_NETERROR)) {                   \
            static struct cfs_debug_limit_state cdls;                         \
            LIBCFS_DEBUG_MSG_DATA_DECL(msgdata, level, &cdls);                \
            kgnilnd_debug_msg(&msgdata, level, &cdls, msg,                    \
                              "$$ "fmt" from %s ", ## args,                   \
                              libcfs_nid2str((msg)->gnm_srcnid));             \
        } else {                                                              \
            LIBCFS_DEBUG_MSG_DATA_DECL(msgdata, level, NULL);                 \
            kgnilnd_debug_msg(&msgdata, level, NULL, msg,                     \
                              "$$ "fmt" from %s ", ## args,                   \
                              libcfs_nid2str((msg)->gnm_srcnid));             \
        }                                                                     \
} while (0)
Definition at line 996 of file gnilnd.h.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_consume_rx(), kgnilnd_eager_recv(), kgnilnd_recv(), and kgnilnd_verify_rdma_cksum().
#define GNIDBG_TOMSG (level, msg, fmt, args...)
Value:
do {                                                                          \
        if ((level) & (D_ERROR | D_WARNING | D_NETERROR)) {                   \
            static struct cfs_debug_limit_state cdls;                         \
            LIBCFS_DEBUG_MSG_DATA_DECL(msgdata, level, &cdls);                \
            kgnilnd_debug_msg(&msgdata, level, &cdls, msg,                    \
                              "$$ "fmt" ", ## args);                          \
        } else {                                                              \
            LIBCFS_DEBUG_MSG_DATA_DECL(msgdata, level, NULL);                 \
            kgnilnd_debug_msg(&msgdata, level, NULL, msg,                     \
                              "$$ "fmt" ", ## args);                          \
        }                                                                     \
} while (0)
Definition at line 1013 of file gnilnd.h.
Referenced by kgnilnd_complete_tx(), kgnilnd_sendmsg_nolock(), kgnilnd_tx_done(), and kgnilnd_tx_should_retry().
#define GNIDBG_TX (level, tx, fmt, args...)
Value:
do {                                                                            \
        if ((level) & (D_ERROR | D_WARNING | D_NETERROR)) {                     \
            static struct cfs_debug_limit_state cdls;                           \
            LIBCFS_DEBUG_MSG_DATA_DECL(msgdata, level, &cdls);                  \
            kgnilnd_debug_tx(&msgdata, level, &cdls, tx,                        \
                              "$$ "fmt" ", ## args);                            \
        } else {                                                                \
            LIBCFS_DEBUG_MSG_DATA_DECL(msgdata, level, NULL);                   \
            kgnilnd_debug_tx(&msgdata, level, NULL, tx,                         \
                              "$$ "fmt" ", ## args);                            \
        }                                                                       \
} while (0)
Definition at line 1071 of file gnilnd.h.
Referenced by kgnilnd_check_fma_send_cq(), kgnilnd_check_rdma_cq(), kgnilnd_complete_closed_conn(), kgnilnd_map_buffer(), kgnilnd_mem_add_map_list(), kgnilnd_mem_del_map_list(), kgnilnd_process_mapped_tx(), kgnilnd_rdma(), kgnilnd_send_mapped_tx(), kgnilnd_sendmsg_nolock(), kgnilnd_set_tx_id(), kgnilnd_setup_immediate_buffer(), kgnilnd_setup_phys_buffer(), kgnilnd_tx_add_state_locked(), kgnilnd_tx_del_state_locked(), kgnilnd_unmap_buffer(), and kgnilnd_validate_tx_ev_id().
#define GNILND_BUF_IMMEDIATE 1
Definition at line 179 of file gnilnd.h.
Referenced by kgnilnd_map_buffer(), kgnilnd_setup_immediate_buffer(), and kgnilnd_unmap_buffer().
#define GNILND_BUF_IMMEDIATE_KIOV 2
Definition at line 180 of file gnilnd.h.
Referenced by kgnilnd_map_buffer(), kgnilnd_setup_immediate_buffer(), and kgnilnd_unmap_buffer().
#define GNILND_BUF_NONE 0
Definition at line 178 of file gnilnd.h.
Referenced by kgnilnd_alloc_tx(), kgnilnd_map_buffer(), kgnilnd_setup_immediate_buffer(), kgnilnd_setup_phys_buffer(), kgnilnd_setup_virt_buffer(), kgnilnd_tx_done(), and kgnilnd_unmap_buffer().
#define GNILND_BUF_PHYS_MAPPED 4
Definition at line 182 of file gnilnd.h.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_map_buffer(), kgnilnd_mem_add_map_list(), kgnilnd_tx_mapped(), and kgnilnd_unmap_buffer().
#define GNILND_BUF_PHYS_UNMAPPED 3
Definition at line 181 of file gnilnd.h.
Referenced by kgnilnd_map_buffer(), kgnilnd_mem_del_map_list(), kgnilnd_setup_phys_buffer(), and kgnilnd_unmap_buffer().
#define GNILND_BUF_VIRT_MAPPED 6
Definition at line 184 of file gnilnd.h.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_map_buffer(), kgnilnd_mem_add_map_list(), kgnilnd_tx_mapped(), and kgnilnd_unmap_buffer().
#define GNILND_BUF_VIRT_UNMAPPED 5
Definition at line 183 of file gnilnd.h.
Referenced by kgnilnd_map_buffer(), kgnilnd_mem_del_map_list(), kgnilnd_setup_virt_buffer(), and kgnilnd_unmap_buffer().
#define GNILND_CHECKSUM_OFF 0
Definition at line 103 of file gnilnd.h.
Referenced by kgnilnd_tunables_init().
#define GNILND_CHECKSUM_SMSG 2
Definition at line 105 of file gnilnd.h.
Referenced by kgnilnd_tunables_init().
#define GNILND_CHECKSUM_SMSG_BTE 3
Definition at line 106 of file gnilnd.h.
Referenced by kgnilnd_tunables_init().
#define GNILND_CHECKSUM_SMSG_HEADER 1
Definition at line 104 of file gnilnd.h.
Referenced by kgnilnd_tunables_init().
#define GNILND_CLEAR_PURGATORY 2
Definition at line 254 of file gnilnd.h.
Referenced by kgnilnd_ctl(), and kgnilnd_del_conn_or_peer().
#define GNILND_CLOSE_EARLY 4
Definition at line 241 of file gnilnd.h.
#define GNILND_CLOSE_INJECT1 2
Definition at line 239 of file gnilnd.h.
Referenced by kgnilnd_check_peer_timeouts_locked().
#define GNILND_CLOSE_INJECT2 3
Definition at line 240 of file gnilnd.h.
Referenced by kgnilnd_send_conn_close().
#define GNILND_CLOSE_RX 1
Definition at line 238 of file gnilnd.h.
Referenced by kgnilnd_check_fma_rx().
#define GNILND_COMPUTE 0
Definition at line 123 of file gnilnd.h.
#define GNILND_CONN_IDLE 0
Definition at line 217 of file gnilnd.h.
Referenced by _kgnilnd_schedule_conn(), kgnilnd_process_conns(), kgnilnd_reset_stack(), and kgnilnd_schedule_process_conn().
#define GNILND_CONN_MAGIC 0xa100f
Definition at line 101 of file gnilnd.h.
Referenced by kgnilnd_create_conn(), and kgnilnd_destroy_conn().
#define GNILND_CONN_PROCESS 3
Definition at line 220 of file gnilnd.h.
Referenced by kgnilnd_complete_closed_conn(), kgnilnd_process_conns(), kgnilnd_reset_stack(), and kgnilnd_schedule_process_conn().
#define GNILND_CONN_SCHED 1
Definition at line 218 of file gnilnd.h.
#define GNILND_CONN_WANTS_SCHED 2
Definition at line 219 of file gnilnd.h.
Referenced by _kgnilnd_schedule_conn(), and kgnilnd_schedule_process_conn().
#define GNILND_CONNREQ_VERSION 2
Definition at line 358 of file gnilnd.h.
Referenced by kgnilnd_pack_connreq(), and kgnilnd_unpack_connreq().
#define GNILND_CQID_NBITS (21 - GNILND_EXTRA_BITS)
Definition at line 130 of file gnilnd.h.
#define GNILND_DEL_CONN 0
Definition at line 252 of file gnilnd.h.
Referenced by kgnilnd_ctl(), kgnilnd_del_conn_or_peer(), and kgnilnd_reset_stack().
#define GNILND_DEL_PEER 1
Definition at line 253 of file gnilnd.h.
Referenced by kgnilnd_base_shutdown(), kgnilnd_ctl(), kgnilnd_del_conn_or_peer(), and kgnilnd_shutdown().
#define GNILND_DEV_IDLE 0
Definition at line 222 of file gnilnd.h.
Referenced by kgnilnd_schedule_device(), and kgnilnd_scheduler().
#define GNILND_DEV_IRQ 1
Definition at line 223 of file gnilnd.h.
Referenced by kgnilnd_schedule_device(), and kgnilnd_scheduler().
#define GNILND_DEV_LOOP 2
Definition at line 224 of file gnilnd.h.
Referenced by kgnilnd_scheduler(), and kgnilnd_sendmsg_trylock().
#define GNILND_DGRAM_IDLE 0
Definition at line 226 of file gnilnd.h.
Referenced by kgnilnd_dgram_mover().
#define GNILND_DGRAM_MAGIC 0x0DDBA11
Definition at line 331 of file gnilnd.h.
Referenced by kgnilnd_alloc_dgram(), and kgnilnd_probe_for_dgram().
#define GNILND_DGRAM_PROCESS 2
Definition at line 228 of file gnilnd.h.
#define GNILND_DGRAM_SCHED 1
Definition at line 227 of file gnilnd.h.
Referenced by kgnilnd_schedule_dgram().
#define GNILND_DGRAM_TIMEOUT 2
Definition at line 83 of file gnilnd.h.
#define GNILND_EXTRA_BITS 1
Definition at line 128 of file gnilnd.h.
#define GNILND_FAST_MAPPING_TRY *kgnilnd_tunables.kgn_max_retransmits
Definition at line 84 of file gnilnd.h.
Referenced by kgnilnd_process_mapped_tx().
#define GNILND_FAST_RECONNECT 0
Definition at line 124 of file gnilnd.h.
#define GNILND_FMABLK 1024
Definition at line 121 of file gnilnd.h.
#define GNILND_HARDWARE_TIMEOUT 15
Definition at line 80 of file gnilnd.h.
#define GNILND_INIT_ALL 2
Definition at line 175 of file gnilnd.h.
Referenced by kgnilnd_base_startup(), kgnilnd_conn_seq_start(), kgnilnd_dev_init(), kgnilnd_mdd_seq_start(), kgnilnd_peer_seq_start(), kgnilnd_proc_cksum_test_write(), kgnilnd_proc_stats_write(), kgnilnd_reset_stack(), kgnilnd_shutdown(), kgnilnd_smsg_seq_start(), and kgnilnd_stats_seq_show().
#define GNILND_INIT_DATA 1
Definition at line 174 of file gnilnd.h.
Referenced by kgnilnd_base_startup().
#define GNILND_INIT_NOTHING 0
Definition at line 173 of file gnilnd.h.
Referenced by kgnilnd_base_shutdown(), kgnilnd_base_startup(), and kgnilnd_startup().
#define GNILND_IS_QUIESCED
Value:
(atomic_read(&kgnilnd_data.kgn_nquiesce) ==                             \
                atomic_read(&kgnilnd_data.kgn_nthreads))
Definition at line 1093 of file gnilnd.h.
Referenced by kgnilnd_bump_timeouts(), kgnilnd_pause_threads(), kgnilnd_quiesce_wait(), and kgnilnd_shutdown().
#define GNILND_LASTRX (conn)
Value:
(time_after(conn->gnc_last_rx, conn->gnc_last_rx_cq) \
                                ? conn->gnc_last_rx : conn->gnc_last_rx_cq)
Definition at line 164 of file gnilnd.h.
Referenced by kgnilnd_check_conn_timeouts_locked(), kgnilnd_check_fma_rx(), and kgnilnd_sendmsg_nolock().
#define GNILND_MAP_RETRY_RATE 1
Definition at line 86 of file gnilnd.h.
Referenced by kgnilnd_process_mapped_tx().
#define GNILND_MAP_TIMEOUT
Value:
(cfs_time_seconds(*kgnilnd_tunables.kgn_timeout * \
         *kgnilnd_tunables.kgn_timeout))
Definition at line 89 of file gnilnd.h.
Referenced by kgnilnd_process_mapped_tx().
#define GNILND_MAX_CQID (1 << GNILND_CQID_NBITS)
Definition at line 132 of file gnilnd.h.
Referenced by kgnilnd_create_conn(), kgnilnd_get_cqid_locked(), and kgnilnd_validate_tx_ev_id().
#define GNILND_MAX_IMMEDIATE (64<<10)
Definition at line 137 of file gnilnd.h.
Referenced by kgnilnd_setup_immediate_buffer(), and kgnilnd_tunables_init().
#define GNILND_MAX_MSG_ID (1 << GNILND_MSGID_TX_NBITS)
Definition at line 133 of file gnilnd.h.
Referenced by kgnilnd_base_startup(), kgnilnd_complete_closed_conn(), kgnilnd_create_conn(), kgnilnd_destroy_conn(), kgnilnd_set_tx_id(), and kgnilnd_validate_tx_ev_id().
#define GNILND_MAX_MSG_SIZE (*kgnilnd_tunables.kgn_max_immediate + sizeof(kgn_msg_t))
Definition at line 134 of file gnilnd.h.
Referenced by kgnilnd_setup_smsg_attr().
#define GNILND_MAX_RECONNECT_TO GNILND_BASE_TIMEOUT
Definition at line 79 of file gnilnd.h.
#define GNILND_MAXDEVS 1
Definition at line 99 of file gnilnd.h.
Referenced by kgnilnd_base_startup(), and kgnilnd_startup().
#define GNILND_MBOX_CREDITS 256
Definition at line 100 of file gnilnd.h.
#define GNILND_MBOX_PAYLOAD
Value:
(GNILND_MAX_MSG_SIZE * \
          ((*kgnilnd_tunables.kgn_concurrent_sends - 2) * 2));
Definition at line 148 of file gnilnd.h.
Referenced by kgnilnd_alloc_fmablk().
#define GNILND_MDD_TIMEOUT 15
Definition at line 81 of file gnilnd.h.
#define GNILND_MIN_RECONNECT_TO (GNILND_BASE_TIMEOUT/4)
Definition at line 78 of file gnilnd.h.
#define GNILND_MIN_TIMEOUT 5
Definition at line 76 of file gnilnd.h.
Referenced by kgnilnd_check_peer_timeouts_locked(), kgnilnd_create_conn(), and kgnilnd_unpack_connreq().
#define GNILND_MSG_CLOSE 0x0a
Definition at line 207 of file gnilnd.h.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_complete_closed_conn(), kgnilnd_msgtype2str(), kgnilnd_process_fmaq(), kgnilnd_send_conn_close(), and kgnilnd_sendmsg_nolock().
#define GNILND_MSG_GET_ACK_REV 0x0f
Definition at line 212 of file gnilnd.h.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_compute_rdma_cksum(), kgnilnd_msgtype2str(), kgnilnd_nak_rdma(), kgnilnd_process_fmaq(), kgnilnd_queue_tx(), kgnilnd_recv(), kgnilnd_send_mapped_tx(), and kgnilnd_verify_rdma_cksum().
#define GNILND_MSG_GET_DONE 0x09
Definition at line 206 of file gnilnd.h.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_check_rdma_cq(), kgnilnd_compute_rdma_cksum(), kgnilnd_msgtype2str(), kgnilnd_nak_rdma(), kgnilnd_process_fmaq(), kgnilnd_rdma(), kgnilnd_send_mapped_tx(), and kgnilnd_setup_rdma().
#define GNILND_MSG_GET_DONE_REV 0x10
Definition at line 213 of file gnilnd.h.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_check_rdma_cq(), kgnilnd_compute_rdma_cksum(), kgnilnd_msgtype2str(), kgnilnd_nak_rdma(), kgnilnd_process_fmaq(), kgnilnd_rdma(), kgnilnd_send_mapped_tx(), and kgnilnd_verify_rdma_cksum().
#define GNILND_MSG_GET_NAK 0x08
Definition at line 205 of file gnilnd.h.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_msgtype2str(), kgnilnd_nak_rdma(), and kgnilnd_process_fmaq().
#define GNILND_MSG_GET_NAK_REV 0x11
Definition at line 214 of file gnilnd.h.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_msgtype2str(), kgnilnd_nak_rdma(), and kgnilnd_process_fmaq().
#define GNILND_MSG_GET_REQ 0x07
Definition at line 204 of file gnilnd.h.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_map_buffer(), kgnilnd_mem_add_map_list(), kgnilnd_mem_del_map_list(), kgnilnd_msgtype2str(), kgnilnd_nak_rdma(), kgnilnd_process_fmaq(), kgnilnd_queue_tx(), kgnilnd_recv(), kgnilnd_send(), kgnilnd_send_mapped_tx(), kgnilnd_setup_rdma(), kgnilnd_tx_done(), and kgnilnd_verify_rdma_cksum().
#define GNILND_MSG_GET_REQ_REV 0x0e
Definition at line 211 of file gnilnd.h.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_msgtype2str(), kgnilnd_nak_rdma(), kgnilnd_process_fmaq(), kgnilnd_process_mapped_tx(), kgnilnd_recv(), kgnilnd_send(), and kgnilnd_send_mapped_tx().
#define GNILND_MSG_IMMEDIATE 0x02
Definition at line 199 of file gnilnd.h.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_msgtype2str(), kgnilnd_process_fmaq(), kgnilnd_queue_tx(), kgnilnd_recv(), kgnilnd_send(), and kgnilnd_sendmsg_nolock().
#define GNILND_MSG_MAGIC LNET_PROTO_GNI_MAGIC
Definition at line 330 of file gnilnd.h.
Referenced by _kgnilnd_match_reply(), kgnilnd_check_fma_rx(), kgnilnd_init_msg(), kgnilnd_pack_connreq(), kgnilnd_unpack_connreq(), and kgnilnd_validate_tx_ev_id().
#define GNILND_MSG_NONE 0x00
Definition at line 197 of file gnilnd.h.
Referenced by kgnilnd_alloc_tx(), kgnilnd_msgtype2str(), and kgnilnd_tx_done().
#define GNILND_MSG_NOOP 0x01
Definition at line 198 of file gnilnd.h.
Referenced by kgnilnd_check_conn_timeouts_locked(), kgnilnd_check_fma_rx(), kgnilnd_check_fma_send_cq(), kgnilnd_finish_connect(), kgnilnd_msgtype2str(), kgnilnd_process_fmaq(), kgnilnd_query(), kgnilnd_queue_tx(), and kgnilnd_sendmsg_nolock().
#define GNILND_MSG_PUT_ACK 0x05
Definition at line 202 of file gnilnd.h.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_map_buffer(), kgnilnd_mem_add_map_list(), kgnilnd_mem_del_map_list(), kgnilnd_msgtype2str(), kgnilnd_nak_rdma(), kgnilnd_process_fmaq(), kgnilnd_queue_tx(), kgnilnd_recv(), kgnilnd_send_mapped_tx(), and kgnilnd_verify_rdma_cksum().
#define GNILND_MSG_PUT_DONE 0x06
Definition at line 203 of file gnilnd.h.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_check_rdma_cq(), kgnilnd_compute_rdma_cksum(), kgnilnd_msgtype2str(), kgnilnd_nak_rdma(), kgnilnd_process_fmaq(), kgnilnd_rdma(), and kgnilnd_send_mapped_tx().
#define GNILND_MSG_PUT_DONE_REV 0x0c
Definition at line 209 of file gnilnd.h.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_check_rdma_cq(), kgnilnd_compute_rdma_cksum(), kgnilnd_msgtype2str(), kgnilnd_nak_rdma(), kgnilnd_process_fmaq(), kgnilnd_rdma(), kgnilnd_send_mapped_tx(), kgnilnd_setup_rdma(), and kgnilnd_verify_rdma_cksum().
#define GNILND_MSG_PUT_NAK 0x04
Definition at line 201 of file gnilnd.h.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_msgtype2str(), kgnilnd_nak_rdma(), and kgnilnd_process_fmaq().
#define GNILND_MSG_PUT_NAK_REV 0x0d
Definition at line 210 of file gnilnd.h.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_msgtype2str(), kgnilnd_nak_rdma(), and kgnilnd_process_fmaq().
#define GNILND_MSG_PUT_REQ 0x03
Definition at line 200 of file gnilnd.h.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_msgtype2str(), kgnilnd_nak_rdma(), kgnilnd_process_fmaq(), kgnilnd_process_mapped_tx(), kgnilnd_recv(), kgnilnd_send(), and kgnilnd_send_mapped_tx().
#define GNILND_MSG_PUT_REQ_REV 0x0b
Definition at line 208 of file gnilnd.h.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_compute_rdma_cksum(), kgnilnd_msgtype2str(), kgnilnd_nak_rdma(), kgnilnd_process_fmaq(), kgnilnd_queue_tx(), kgnilnd_recv(), kgnilnd_send(), kgnilnd_send_mapped_tx(), kgnilnd_setup_rdma(), and kgnilnd_verify_rdma_cksum().
#define GNILND_MSG_VERSION 8
Definition at line 352 of file gnilnd.h.
Referenced by kgnilnd_check_fma_rx(), and kgnilnd_init_msg().
#define GNILND_MSGID_CLOSE (GNILND_MSGID_NOOP + 1)
Definition at line 194 of file gnilnd.h.
Referenced by kgnilnd_create_conn().
#define GNILND_MSGID_NOOP (GNILND_MAX_CQID + 128)
Definition at line 193 of file gnilnd.h.
#define GNILND_MSGID_TX_NBITS (32 - GNILND_CQID_NBITS)
Definition at line 131 of file gnilnd.h.
#define GNILND_NOPURG 222
Definition at line 142 of file gnilnd.h.
Referenced by kgnilnd_check_rdma_cq(), and kgnilnd_unmap_buffer().
#define GNILND_PEER_CLEAN 0
Definition at line 249 of file gnilnd.h.
#define GNILND_PEER_CONNECT 1
Definition at line 231 of file gnilnd.h.
Referenced by kgnilnd_check_peer_timeouts_locked(), kgnilnd_find_or_create_conn_locked(), kgnilnd_probe_and_process_dgram(), kgnilnd_start_connect(), and kgnilnd_start_outbound_dgrams().
#define GNILND_PEER_IDLE 0
Definition at line 230 of file gnilnd.h.
Referenced by kgnilnd_cancel_peer_connect_locked(), kgnilnd_check_peer_timeouts_locked(), kgnilnd_destroy_peer(), kgnilnd_find_or_create_conn_locked(), kgnilnd_finish_connect(), kgnilnd_peer_notify(), kgnilnd_probe_and_process_dgram(), kgnilnd_process_nak(), and kgnilnd_start_outbound_dgrams().
#define GNILND_PEER_KILL 5
Definition at line 235 of file gnilnd.h.
Referenced by kgnilnd_check_peer_timeouts_locked(), kgnilnd_destroy_peer(), kgnilnd_start_connect(), and kgnilnd_start_outbound_dgrams().
#define GNILND_PEER_NEEDS_DEATH 4
Definition at line 234 of file gnilnd.h.
Referenced by kgnilnd_cancel_peer_connect_locked(), kgnilnd_start_connect(), and kgnilnd_start_outbound_dgrams().
#define GNILND_PEER_PERSISTING 1
Definition at line 250 of file gnilnd.h.
#define GNILND_PEER_POSTED 3
Definition at line 233 of file gnilnd.h.
Referenced by kgnilnd_start_connect().
#define GNILND_PEER_POSTING 2
Definition at line 232 of file gnilnd.h.
Referenced by kgnilnd_cancel_peer_connect_locked(), kgnilnd_start_connect(), and kgnilnd_start_outbound_dgrams().
#define GNILND_PURG_RELEASE (t) (GNILND_TIMEOUTRX(t) * 3)
Definition at line 159 of file gnilnd.h.
#define GNILND_PURGATORY_MAX 5
Definition at line 140 of file gnilnd.h.
#define GNILND_QUIESCE_ADMIN 1
Definition at line 245 of file gnilnd.h.
#define GNILND_QUIESCE_HW_QUIESCE 3
Definition at line 247 of file gnilnd.h.
Referenced by kgnilnd_pause_threads(), and kgnilnd_ruhroh_thread().
#define GNILND_QUIESCE_IDLE 0
Definition at line 244 of file gnilnd.h.
Referenced by kgnilnd_reset_stack(), kgnilnd_ruhroh_thread(), and kgnilnd_shutdown().
#define GNILND_QUIESCE_RESET 2
Definition at line 246 of file gnilnd.h.
Referenced by kgnilnd_reset_stack().
#define GNILND_RCA_NODE_DOWN 1
Definition at line 257 of file gnilnd.h.
Referenced by kgnilnd_check_conn_timeouts_locked(), kgnilnd_finish_connect(), kgnilnd_launch_tx(), kgnilnd_peer_seq_show(), and kgnilnd_report_node_state().
#define GNILND_RCA_NODE_UNKNOWN 2
Definition at line 258 of file gnilnd.h.
#define GNILND_RCA_NODE_UP 0
Definition at line 256 of file gnilnd.h.
Referenced by kgnilnd_check_peer_timeouts_locked(), kgnilnd_close_conn_locked(), kgnilnd_complete_closed_conn(), kgnilnd_finish_connect(), kgnilnd_get_node_state(), kgnilnd_launch_tx(), and kgnilnd_report_node_state().
#define GNILND_REAPER_NCHECKS 4
Definition at line 96 of file gnilnd.h.
Referenced by kgnilnd_reaper(), and kgnilnd_startup().
#define GNILND_REAPER_THREAD_WAKE 1
Definition at line 94 of file gnilnd.h.
Referenced by kgnilnd_reaper().
#define GNILND_REGFAILTO_DISABLE -1
Definition at line 168 of file gnilnd.h.
Referenced by kgnilnd_map_fmablk().
#define GNILND_REVERSE_BOTH (GNILND_REVERSE_GET | GNILND_REVERSE_PUT)
Definition at line 264 of file gnilnd.h.
#define GNILND_REVERSE_GET 1
Definition at line 262 of file gnilnd.h.
Referenced by kgnilnd_send().
#define GNILND_REVERSE_NONE 0
Definition at line 261 of file gnilnd.h.
#define GNILND_REVERSE_PUT 2
Definition at line 263 of file gnilnd.h.
Referenced by kgnilnd_send().
#define GNILND_SCHED_NICE -20
Definition at line 122 of file gnilnd.h.
#define GNILND_SCHED_TIMEOUT 1
Definition at line 82 of file gnilnd.h.
#define GNILND_TIMEOUT2DEADMAN ((*kgnilnd_tunables.kgn_mdd_timeout) * 1000 * 60)
Definition at line 153 of file gnilnd.h.
Referenced by kgnilnd_unmap_buffer(), and kgnilnd_unmap_fmablk().
#define GNILND_TIMEOUTRX (t) (t + cfs_time_seconds(*kgnilnd_tunables.kgn_hardware_timeout))
Definition at line 156 of file gnilnd.h.
Referenced by kgnilnd_check_fma_rx(), and kgnilnd_sendmsg_nolock().
#define GNILND_TO2KA (t) (((t)-1)/2)
Definition at line 77 of file gnilnd.h.
Referenced by kgnilnd_check_conn_timeouts_locked(), kgnilnd_finish_connect(), kgnilnd_process_fmaq(), kgnilnd_set_conn_params(), and kgnilnd_startup().
#define GNILND_TX_FAIL_SMSG (1<<5)
Definition at line 190 of file gnilnd.h.
Referenced by kgnilnd_send_mapped_tx(), and kgnilnd_sendmsg_nolock().
#define GNILND_TX_PENDING_RDMA (1<<3)
Definition at line 188 of file gnilnd.h.
Referenced by kgnilnd_check_fma_rx(), and kgnilnd_check_fma_send_cq().
#define GNILND_TX_QUIET_ERROR (1<<4)
Definition at line 189 of file gnilnd.h.
Referenced by kgnilnd_complete_closed_conn(), kgnilnd_tx_done(), and kgnilnd_txlist_done().
#define GNILND_TX_WAITING_COMPLETION (1<<2)
Definition at line 187 of file gnilnd.h.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_check_fma_send_cq(), kgnilnd_complete_tx(), kgnilnd_process_fmaq(), kgnilnd_send_conn_close(), kgnilnd_send_mapped_tx(), and kgnilnd_sendmsg_trylock().
#define GNILND_TX_WAITING_REPLY (1<<1)
Definition at line 186 of file gnilnd.h.
Referenced by _kgnilnd_match_reply(), kgnilnd_check_fma_rx(), kgnilnd_check_fma_send_cq(), kgnilnd_complete_tx(), kgnilnd_process_fmaq(), and kgnilnd_send_mapped_tx().
#define GNITX_ASSERTF (tx, cond, fmt, a...)
Value:
({                                                                              \
        if (unlikely(!(cond))) {                                                \
                GNIDBG_TX(D_EMERG, tx, "ASSERTION(" #cond ") failed:" fmt, a);  \
                LBUG();                                                         \
        }                                                                       \
})
Definition at line 1085 of file gnilnd.h.
Referenced by _kgnilnd_match_reply(), kgnilnd_add_purgatory_tx(), kgnilnd_check_fma_rx(), kgnilnd_check_fma_send_cq(), kgnilnd_check_rdma_cq(), kgnilnd_complete_tx(), kgnilnd_compute_rdma_cksum(), kgnilnd_launch_tx(), kgnilnd_map_buffer(), kgnilnd_mem_add_map_list(), kgnilnd_mem_del_map_list(), kgnilnd_process_fmaq(), kgnilnd_sendmsg_nolock(), kgnilnd_tx_add_state_locked(), kgnilnd_tx_del_state_locked(), kgnilnd_validate_tx_ev_id(), and kgnilnd_verify_rdma_cksum().
#define kgnilnd_admin_addref (atomic)
Value:
do {                                                                            \
        int     val = atomic_inc_return(&atomic);                               \
        LASSERTF(val > 0,  #atomic " refcount %d\n", val);                       \
        CDEBUG(D_NETTRACE, #atomic " refcount %d\n", val);                       \
} while (0)
Definition at line 1115 of file gnilnd.h.
Referenced by kgnilnd_close_conn_locked(), kgnilnd_close_peer_conns_locked(), kgnilnd_del_conn_or_peer(), kgnilnd_mark_for_detach_purgatory_all_locked(), kgnilnd_rdma(), kgnilnd_release_dgram(), and kgnilnd_validate_tx_ev_id().
#define kgnilnd_admin_decref (atomic)
Value:
do {                                                                            \
        int     val = atomic_dec_return(&atomic);                               \
        LASSERTF(val >=0,  #atomic " refcount %d\n", val);                        \
        CDEBUG(D_NETTRACE, #atomic " refcount %d\n", val);                       \
}while (0)
Definition at line 1122 of file gnilnd.h.
Referenced by kgnilnd_check_fma_send_cq(), kgnilnd_check_rdma_cq(), kgnilnd_complete_closed_conn(), kgnilnd_destroy_conn_ep(), kgnilnd_finish_connect(), kgnilnd_release_purgatory_list(), kgnilnd_repost_wc_dgrams(), kgnilnd_unlink_peer_locked(), and kgnilnd_validate_tx_ev_id().
#define kgnilnd_conn_addref (conn)
Value:
do {                                                                    \
        int     val;                                                    \
                                                                        \
        smp_wmb();                                                      \
        val = atomic_inc_return(&conn->gnc_refcount);                   \
        LASSERTF(val > 1 && conn->gnc_magic == GNILND_CONN_MAGIC,       \
                "conn %p refc %d to %s\n",                              \
                conn, val,                                              \
                conn->gnc_peer                                          \
                        ? libcfs_nid2str(conn->gnc_peer->gnp_nid)       \
                        : "<?>");                                       \
        CDEBUG(D_NETTRACE, "conn %p->%s++ (%d)\n", conn,                \
                conn->gnc_peer                                          \
                        ? libcfs_nid2str(conn->gnc_peer->gnp_nid)       \
                        : "<?>",                                        \
                val);                                                   \
} while (0)
Definition at line 1163 of file gnilnd.h.
Referenced by _kgnilnd_schedule_conn(), kgnilnd_conn_seq_show(), kgnilnd_create_conn(), kgnilnd_eager_recv(), kgnilnd_finish_connect(), kgnilnd_get_conn_by_idx(), kgnilnd_release_dgram(), kgnilnd_tx_add_state_locked(), and kgnilnd_validate_tx_ev_id().
#define kgnilnd_conn_decref (conn)
Value:
do {                                                                    \
        int     val;                                                    \
                                                                        \
        smp_wmb();                                                      \
        val = atomic_dec_return(&conn->gnc_refcount);                   \
        LASSERTF(val >= 0, "conn %p refc %d to %s\n",                   \
                conn, val,                                              \
                conn->gnc_peer                                          \
                        ? libcfs_nid2str(conn->gnc_peer->gnp_nid)       \
                        : "<?>");                                       \
        CDEBUG(D_NETTRACE, "conn %p->%s-- (%d)\n", conn,                \
                conn->gnc_peer                                          \
                        ? libcfs_nid2str(conn->gnc_peer->gnp_nid)       \
                        : "<?>",                                        \
                val);                                                   \
        smp_rmb();                                                      \
        if ((val == 1) &&                                               \
            (conn->gnc_ephandle != NULL) &&                             \
            (conn->gnc_state != GNILND_CONN_DESTROY_EP)) {              \
                set_mb(conn->gnc_state, GNILND_CONN_DESTROY_EP);        \
                kgnilnd_schedule_conn(conn);                            \
        } else if (val == 0) {                                          \
                kgnilnd_destroy_conn(conn);                             \
        }                                                               \
} while (0)
Definition at line 1232 of file gnilnd.h.
Referenced by kgnilnd_check_fma_send_cq(), kgnilnd_check_rdma_cq(), kgnilnd_cleanup_dgram(), kgnilnd_close_conn_locked(), kgnilnd_complete_closed_conn(), kgnilnd_conn_seq_show(), kgnilnd_consume_rx(), kgnilnd_ctl(), kgnilnd_destroy_conn_ep(), kgnilnd_eager_recv(), kgnilnd_finish_connect(), kgnilnd_process_conns(), kgnilnd_release_purgatory_list(), kgnilnd_reset_stack(), kgnilnd_tx_del_state_locked(), and kgnilnd_validate_tx_ev_id().
#define kgnilnd_debug_conn (msgdata, mask, cdls, conn, fmt, a...)
Value:
do {                                                                           \
        CFS_CHECK_STACK(msgdata, mask, cdls);                                  \
                                                                               \
        if (((mask) & D_CANTMASK) != 0 ||                                      \
            ((libcfs_debug & (mask)) != 0 &&                                   \
             (libcfs_subsystem_debug & DEBUG_SUBSYSTEM) != 0))                 \
                _kgnilnd_debug_conn((conn), msgdata, fmt, ##a);                \
} while(0)
Definition at line 1031 of file gnilnd.h.
#define kgnilnd_debug_msg (msgdata, mask, cdls, msg, fmt, a...)
Value:
do {                                                                          \
        CFS_CHECK_STACK(msgdata, mask, cdls);                                 \
                                                                              \
        if (((mask) & D_CANTMASK) != 0 ||                                     \
            ((libcfs_debug & (mask)) != 0 &&                                  \
             (libcfs_subsystem_debug & DEBUG_SUBSYSTEM) != 0))                \
                _kgnilnd_debug_msg((msg), msgdata, fmt, ##a);                 \
} while(0)
Definition at line 985 of file gnilnd.h.
#define kgnilnd_debug_tx (msgdata, mask, cdls, tx, fmt, a...)
Value:
do {                                                                           \
        CFS_CHECK_STACK(msgdata, mask, cdls);                                  \
                                                                               \
        if (((mask) & D_CANTMASK) != 0 ||                                      \
            ((libcfs_debug & (mask)) != 0 &&                                   \
             (libcfs_subsystem_debug & DEBUG_SUBSYSTEM) != 0))                 \
                _kgnilnd_debug_tx((tx), msgdata, fmt, ##a);                    \
} while(0)
Definition at line 1060 of file gnilnd.h.
#define kgnilnd_net_addref (net)
Value:
do {                                                                            \
        int     val = atomic_inc_return(&net->gnn_refcount);                    \
        LASSERTF(val > 1, "net %p refcount %d\n", net, val);                    \
        CDEBUG(D_NETTRACE, "net %p->%s++ (%d)\n", net,                          \
                libcfs_nid2str(net->gnn_ni->ni_nid), val);                      \
} while (0)
Definition at line 1129 of file gnilnd.h.
Referenced by kgnilnd_create_peer_safe(), kgnilnd_find_net(), and kgnilnd_peer_notify().
#define kgnilnd_net_decref (net)
Value:
do {                                                                            \
        int     val = atomic_dec_return(&net->gnn_refcount);                    \
        LASSERTF(val >= 0, "net %p refcount %d\n", net, val);                   \
        CDEBUG(D_NETTRACE, "net %p->%s-- (%d)\n", net,                          \
               libcfs_nid2str(net->gnn_ni->ni_nid), val);                       \
} while (0)
Definition at line 1137 of file gnilnd.h.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_create_peer_safe(), kgnilnd_destroy_peer(), kgnilnd_peer_notify(), kgnilnd_shutdown(), and kgnilnd_unpack_connreq().
#define kgnilnd_peer_addref (peer)
Value:
do {                                                                            \
        int     val = atomic_inc_return(&peer->gnp_refcount);                   \
        LASSERTF(val > 1, "peer %p refcount %d\n", peer, val);                  \
        CDEBUG(D_NETTRACE, "peer %p->%s++ (%d)\n", peer,                        \
               libcfs_nid2str(peer->gnp_nid), val);                             \
} while (0)
Definition at line 1145 of file gnilnd.h.
Referenced by kgnilnd_check_peer_timeouts_locked(), kgnilnd_conn_seq_show(), kgnilnd_del_peer_locked(), kgnilnd_find_or_create_conn_locked(), kgnilnd_finish_connect(), kgnilnd_peer_seq_show(), kgnilnd_probe_and_process_dgram(), kgnilnd_release_dgram(), and kgnilnd_tx_add_state_locked().
#define kgnilnd_peer_decref (peer)
Value:
do {                                                                            \
        int     val = atomic_dec_return(&peer->gnp_refcount);                   \
        LASSERTF(val >= 0, "peer %p refcount %d\n", peer, val);                 \
        CDEBUG(D_NETTRACE, "peer %p->%s--(%d)\n", peer,                         \
               libcfs_nid2str(peer->gnp_nid), val);                             \
        if (val == 0)                                                           \
                kgnilnd_destroy_peer(peer);                                     \
} while(0)
Definition at line 1153 of file gnilnd.h.
Referenced by kgnilnd_add_peer_locked(), kgnilnd_cancel_peer_connect_locked(), kgnilnd_conn_seq_show(), kgnilnd_del_peer_locked(), kgnilnd_destroy_conn(), kgnilnd_finish_connect(), kgnilnd_peer_seq_show(), kgnilnd_probe_and_process_dgram(), kgnilnd_start_outbound_dgrams(), kgnilnd_tx_del_state_locked(), and kgnilnd_unlink_peer_locked().
#define KGNILND_POISON (ptr, c, s) memset(ptr, c, s)
Definition at line 1722 of file gnilnd.h.
Referenced by kgnilnd_free_tx().
#define kgnilnd_schedule_conn (conn) _kgnilnd_schedule_conn(conn, __func__, __LINE__, 0);
Definition at line 889 of file gnilnd.h.
Referenced by kgnilnd_bump_timeouts(), kgnilnd_check_fma_rcv_cq(), kgnilnd_check_fma_rx(), kgnilnd_check_fma_send_cq(), kgnilnd_close_conn_locked(), kgnilnd_complete_closed_conn(), kgnilnd_process_conns(), kgnilnd_process_fmaq(), kgnilnd_queue_tx(), kgnilnd_release_dgram(), kgnilnd_send_conn_close(), and kgnilnd_sendmsg_nolock().
#define kgnilnd_schedule_conn_refheld (conn, refheld) _kgnilnd_schedule_conn(conn, __func__, __LINE__, refheld);
Definition at line 892 of file gnilnd.h.
Referenced by kgnilnd_schedule_process_conn().
#define KGNILND_SPIN_QUIESCE
Value:
do {                                                                    \
        /* E.T phone home */                                            \
        atomic_inc(&kgnilnd_data.kgn_nquiesce);                         \
        CDEBUG(D_NET, "Waiting for thread pause to be over...\n");      \
        while (kgnilnd_data.kgn_quiesce_trigger) {                      \
                msleep_interruptible(MSEC_PER_SEC);                     \
        }                                                               \
        /* Mom, my homework is done */                                  \
        CDEBUG(D_NET, "Waking up from thread pause\n");                 \
        atomic_dec(&kgnilnd_data.kgn_nquiesce);                         \
} while(0)
Definition at line 1097 of file gnilnd.h.
Referenced by kgnilnd_dgram_mover(), kgnilnd_dgram_waitq(), kgnilnd_reaper(), and kgnilnd_scheduler().
Typedef Documentation
typedef enum kgn_conn_state kgn_conn_state_t
typedef struct kgn_conn kgn_conn_t
typedef struct kgn_connreq kgn_connreq_t
typedef enum kgn_connreq_type kgn_connreq_type_t
typedef struct kgn_data kgn_data_t
typedef struct kgn_device kgn_device_t
typedef enum kgn_dgram_state kgn_dgram_state_t
typedef struct kgn_dgram kgn_dgram_t
typedef enum kgn_dgram_type kgn_dgram_type_t
typedef struct kgn_fma_memblock kgn_fma_memblock_t
typedef enum kgn_fmablk_state kgn_fmablk_state_t
typedef struct kgn_gniparams kgn_gniparams_t
typedef struct kgn_mbox_info kgn_mbox_info_t
typedef struct kgn_mdd_purgatory kgn_mdd_purgatory_t
typedef struct kgn_nak_data kgn_nak_data_t
typedef struct kgn_net kgn_net_t
typedef struct kgn_peer kgn_peer_t
typedef struct kgn_rx kgn_rx_t
typedef struct kgn_tunables kgn_tunables_t
typedef struct kgn_tx_ev_id kgn_tx_ev_id_t
typedef enum kgn_tx_list_state kgn_tx_list_state_t
typedef struct kgn_tx kgn_tx_t
Enumeration Type Documentation
enum kgn_conn_state
Enumerator:
GNILND_CONN_DUMMY
GNILND_CONN_LISTEN
GNILND_CONN_CONNECTING
GNILND_CONN_ESTABLISHED
GNILND_CONN_CLOSING
GNILND_CONN_CLOSED
GNILND_CONN_DONE
GNILND_CONN_DESTROY_EP
Definition at line 286 of file gnilnd.h.
enum kgn_connreq_type
Enumerator:
GNILND_CONNREQ_REQ
GNILND_CONNREQ_NAK
GNILND_CONNREQ_CLOSE
Definition at line 302 of file gnilnd.h.
enum kgn_dgram_state
Enumerator:
GNILND_DGRAM_USED
GNILND_DGRAM_POSTING
GNILND_DGRAM_POSTED
GNILND_DGRAM_PROCESSING
GNILND_DGRAM_CANCELED
GNILND_DGRAM_DONE
Definition at line 308 of file gnilnd.h.
enum kgn_dgram_type
Enumerator:
GNILND_DGRAM_REQ
GNILND_DGRAM_WC_REQ
GNILND_DGRAM_NAK
GNILND_DGRAM_CLOSE
Definition at line 318 of file gnilnd.h.
enum kgn_fmablk_state
Enumerator:
GNILND_FMABLK_IDLE
GNILND_FMABLK_PHYS
GNILND_FMABLK_VIRT
GNILND_FMABLK_FREED
Definition at line 266 of file gnilnd.h.
enum kgn_tx_list_state
Enumerator:
GNILND_TX_IDLE
GNILND_TX_ALLOCD
GNILND_TX_PEERQ
GNILND_TX_MAPQ
GNILND_TX_FMAQ
GNILND_TX_LIVE_FMAQ
GNILND_TX_RDMAQ
GNILND_TX_LIVE_RDMAQ
GNILND_TX_DYING
GNILND_TX_FREED
Definition at line 273 of file gnilnd.h.
Function Documentation
static int __kgnilnd_mutex_trylock (struct mutex * lock) [inline, static]
Definition at line 938 of file gnilnd.h.
References LASSERT, ret, and timeout.
Referenced by kgnilnd_mutex_trylock(), and kgnilnd_trylock().
void _kgnilnd_debug_conn (kgn_conn_t * conn, struct libcfs_debug_msg_data * data, const char * fmt, ...)
Definition at line 42 of file gnilnd_debug.c.
References cfs_duration_sec(), kgn_conn::gnc_cqid, kgn_conn::gnc_device, kgn_conn::gnc_last_noop_cq, kgn_conn::gnc_last_noop_sent, kgn_conn::gnc_last_noop_want, kgn_conn::gnc_last_rx, kgn_conn::gnc_last_rx_cq, kgn_conn::gnc_last_sched_ask, kgn_conn::gnc_last_sched_do, kgn_conn::gnc_last_tx, kgn_conn::gnc_last_tx_cq, kgn_conn::gnc_peer, kgn_conn::gnc_rx_seq, kgn_conn::gnc_timeout, kgn_conn::gnc_tx_seq, kgn_device::gnd_sched_alive, kgn_peer::gnp_nid, kgnilnd_conn_state2str(), libcfs_debug_vmsg2(), and libcfs_nid2str().
void _kgnilnd_debug_msg (kgn_msg_t * msg, struct libcfs_debug_msg_data * data, const char * fmt, ...)
Definition at line 25 of file gnilnd_debug.c.
References kgnilnd_msgtype2str(), and libcfs_debug_vmsg2().
void _kgnilnd_debug_tx (kgn_tx_t * tx, struct libcfs_debug_msg_data * data, const char * fmt, ...)
Definition at line 73 of file gnilnd_debug.c.
References cfs_duration_sec(), kgn_conn::gnc_peer, kgn_peer::gnp_nid, kgnilnd_msgtype2str(), kgnilnd_tx_state2str(), libcfs_debug_vmsg2(), libcfs_nid2str(), LPX64, kgn_tx::tx_buftype, kgn_tx::tx_conn, kgn_tx::tx_id, kgn_tx::tx_list_p, kgn_tx::tx_list_state, kgn_tx::tx_msg, kgn_tx::tx_qtime, kgn_tx::tx_retrans, kgn_tx::tx_state, kgn_tx_ev_id::txe_cookie, kgn_tx_ev_id::txe_cqid, kgn_tx_ev_id::txe_idx, and kgn_tx_ev_id::txe_smsg_id.
int _kgnilnd_schedule_conn (kgn_conn_t * conn, const char * caller, int line, int refheld)
Definition at line 154 of file gnilnd_cb.c.
References CDEBUG, D_INFO, kgn_conn::gnc_device, kgn_conn::gnc_last_sched_ask, kgn_conn::gnc_sched_caller, kgn_conn::gnc_sched_line, kgn_conn::gnc_schedlist, kgn_conn::gnc_scheduled, kgn_device::gnd_lock, kgn_device::gnd_ready_conns, GNILND_CONN_IDLE, GNILND_CONN_WANTS_SCHED, kgnilnd_conn_addref, kgnilnd_schedule_device(), LASSERTF, list_add_tail(), and list_empty().
int kgnilnd_add_peer (kgn_net_t * net, lnet_nid_t nid, kgn_peer_t ** peerp)
Definition at line 1393 of file gnilnd.c.
References CDEBUG, D_NET, ENTRY, kgn_data::kgn_net_rw_sem, kgn_data::kgn_peer_conn_lock, kgnilnd_add_peer_locked(), kgnilnd_create_peer_safe(), kgnilnd_get_node_state(), libcfs_nid2str(), LNET_NID_ANY, LNET_NIDADDR(), and RETURN.
Referenced by kgnilnd_ctl(), and kgnilnd_report_node_state().
void kgnilnd_add_peer_locked (lnet_nid_t nid, kgn_peer_t * new_stub_peer, kgn_peer_t ** peerp)
Definition at line 1362 of file gnilnd.c.
References kgn_peer::gnp_list, kgn_peer::gnp_net, kgn_peer::gnp_nid, kgn_data::kgn_peer_version, kgnilnd_find_peer_locked(), kgnilnd_nid2peerlist(), kgnilnd_peer_active(), kgnilnd_peer_decref, LASSERTF, libcfs_nid2str(), and list_add_tail().
Referenced by kgnilnd_add_peer(), kgnilnd_finish_connect(), and kgnilnd_launch_tx().
void kgnilnd_add_purgatory_locked (kgn_conn_t * conn, kgn_peer_t * peer)
Definition at line 1095 of file gnilnd.c.
References CDEBUG, D_NET, ENTRY, EXIT, kgn_conn::gnc_device, kgn_conn::gnc_fma_blk, kgn_conn::gnc_in_purgatory, kgn_conn::gnc_mbox_id, kgn_conn::gnc_mdd_list, kgn_fma_memblock::gnm_mbox_info, kgn_peer::gnp_nid, kgnilnd_count_list(), kgnilnd_peer_active(), kgnilnd_release_mbox(), LASSERTF, libcfs_nid2str(), list_empty(), kgn_mbox_info::mbx_add_purgatory, and kgn_mbox_info::mbx_prev_purg_nid.
Referenced by kgnilnd_close_conn_locked(), and kgnilnd_release_dgram().
int kgnilnd_allocate_phys_fmablk (kgn_device_t * device)
Definition at line 599 of file gnilnd_conn.c.
References CERROR, kgn_tunables::kgn_nphys_mbox, kgnilnd_alloc_fmablk(), kgnilnd_count_phys_mbox(), kgnilnd_tunables, and RETURN.
Referenced by kgnilnd_base_startup().
void kgnilnd_base_shutdown (void)
Definition at line 2509 of file gnilnd.c.
References CDEBUG, CFS_FAIL_GNI_PAUSE_SHUTDOWN, CFS_FAIL_TIMEOUT, cfs_time_seconds(), D_MALLOC, D_NET, D_WARNING, ENTRY, EXIT, kgn_device::gnd_connd_peers, kgn_device::gnd_dgping_waitq, kgn_device::gnd_dgram_waitq, kgn_device::gnd_dgrams, kgn_device::gnd_ndgrams, GNILND_DEL_PEER, GNILND_INIT_NOTHING, kgn_data::kgn_cksum_map_pages, kgn_data::kgn_cksum_npages, kgn_data::kgn_conns, kgn_data::kgn_devices, kgn_data::kgn_dgram_cache, kgn_data::kgn_init, kgn_data::kgn_mbox_cache, kgn_data::kgn_nconns, kgn_data::kgn_ndevs, kgn_tunables::kgn_net_hash_size, kgn_data::kgn_net_rw_sem, kgn_data::kgn_nets, kgn_data::kgn_npeers, kgn_data::kgn_nthreads, kgn_tunables::kgn_peer_hash_size, kgn_data::kgn_peers, kgn_data::kgn_reaper_lock, kgn_data::kgn_reaper_waitq, kgn_data::kgn_ruhroh_running, kgn_data::kgn_ruhroh_shutdown, kgn_data::kgn_ruhroh_waitq, kgn_data::kgn_rx_cache, kgn_data::kgn_shutdown, kgn_data::kgn_tx_cache, kgn_data::kgn_tx_phys_cache, kgn_data::kgn_wc_kill, kgnilnd_cancel_dgrams(), kgnilnd_cancel_wc_dgrams(), kgnilnd_del_conn_or_peer(), kgnilnd_dev_fini(), kgnilnd_free_phys_fmablk(), kgnilnd_schedule_device(), kgnilnd_tunables, kgnilnd_unmap_fma_blocks(), kgnilnd_wait_for_canceled_dgrams(), kgnilnd_wakeup_rca_thread(), LASSERT, LASSERTF, LIBCFS_FREE, libcfs_kmemory, list_empty(), and LNET_NID_ANY.
Referenced by kgnilnd_base_startup(), and kgnilnd_shutdown().
int kgnilnd_base_startup (void)
Definition at line 2205 of file gnilnd.c.
References __u64, CDEBUG, CERROR, D_MALLOC, ENTRY, kgn_data::free_pages_limit, kgn_device::gnd_canceled_dgrams, kgn_device::gnd_conn_sem, kgn_device::gnd_connd_lock, kgn_device::gnd_connd_peers, kgn_device::gnd_cq_mutex, kgn_device::gnd_dgping_waitq, kgn_device::gnd_dgram_lock, kgn_device::gnd_dgram_waitq, kgn_device::gnd_dgrams, kgn_device::gnd_fma_buffs, kgn_device::gnd_fmablk_lock, kgn_device::gnd_fmablk_mutex, kgn_device::gnd_fmablk_vers, kgn_device::gnd_id, kgn_device::gnd_lock, kgn_device::gnd_map_list, kgn_device::gnd_map_lock, kgn_device::gnd_map_tx, kgn_device::gnd_ndgrams, kgn_device::gnd_neps, kgn_device::gnd_nfmablk, kgn_device::gnd_nwcdgrams, kgn_device::gnd_rdmaq, kgn_device::gnd_rdmaq_lock, kgn_device::gnd_rdmaq_timer, kgn_device::gnd_ready_conns, kgn_device::gnd_waitq, GNILND_INIT_ALL, GNILND_INIT_DATA, GNILND_INIT_NOTHING, GNILND_MAX_MSG_ID, GNILND_MAXDEVS, GOTO, INIT_LIST_HEAD, kgn_data::kgn_cksum_map_pages, kgn_data::kgn_cksum_npages, kgn_data::kgn_conns, kgn_data::kgn_connstamp, kgn_data::kgn_devices, kgn_data::kgn_dgram_cache, kgn_data::kgn_init, kgn_data::kgn_mbox_cache, kgn_data::kgn_ndevs, kgn_tunables::kgn_net_hash_size, kgn_data::kgn_net_rw_sem, kgn_data::kgn_nets, kgn_data::kgn_new_min_timeout, kgn_data::kgn_next_cqid, kgn_data::kgn_npending_conns, kgn_data::kgn_npending_detach, kgn_data::kgn_npending_unlink, kgn_data::kgn_nquiesce, kgn_data::kgn_peer_conn_lock, kgn_tunables::kgn_peer_hash_size, kgn_data::kgn_peers, kgn_data::kgn_peerstamp, kgn_data::kgn_quiesce_mutex, kgn_data::kgn_reaper_lock, kgn_data::kgn_reaper_waitq, kgn_data::kgn_rev_copy_buff, kgn_data::kgn_rev_length, kgn_data::kgn_rev_offset, kgn_data::kgn_ruhroh_waitq, kgn_data::kgn_rx_cache, kgn_tunables::kgn_sched_threads, kgn_tunables::kgn_thread_affinity, kgn_tunables::kgn_timeout, kgn_data::kgn_tx_cache, kgn_data::kgn_tx_phys_cache, kgnilnd_allocate_phys_fmablk(), kgnilnd_base_shutdown(), kgnilnd_check_kgni_version(), kgnilnd_dev_init(), kgnilnd_dgram_mover(), kgnilnd_dgram_waitq(), kgnilnd_reaper(), kgnilnd_ruhroh_thread(), kgnilnd_schedule_device_timer(), kgnilnd_scheduler(), kgnilnd_setup_wildcard_dgram(), kgnilnd_start_rca_thread(), kgnilnd_start_sd_threads(), kgnilnd_thread_start(), kgnilnd_tunables, LASSERT, LASSERTF, LIBCFS_ALLOC, libcfs_kmemory, LNET_MAX_IOV, and RETURN.
Referenced by kgnilnd_startup().
void kgnilnd_bump_timeouts (__u32 nap_time, char * reason)
Definition at line 30 of file gnilnd_stack.c.
References CDEBUG, cfs_time_seconds(), D_INFO, kgn_conn::gnc_last_rx, kgn_conn::gnc_last_rx_cq, kgn_conn::gnc_last_tx, kgn_conn::gnc_state, kgn_conn::gnc_timeout, kgn_device::gnd_dgrams, kgn_dgram::gndg_post_time, GNILND_CONN_DONE, GNILND_IS_QUIESCED, kgn_peer::gnp_conns, kgn_peer::gnp_reconnect_interval, kgn_peer::gnp_reconnect_time, kgn_peer::gnp_tx_queue, kgn_data::kgn_devices, kgn_data::kgn_ndevs, kgn_data::kgn_nquiesce, kgn_data::kgn_nthreads, kgn_tunables::kgn_peer_hash_size, kgn_data::kgn_peers, kgnilnd_data, kgnilnd_peer_alive(), kgnilnd_peer_notify(), kgnilnd_schedule_conn, kgnilnd_tunables, LASSERTF, list_for_each_entry, timeout, and kgn_tx::tx_qtime.
Referenced by kgnilnd_reset_stack(), and kgnilnd_ruhroh_thread().
static int kgnilnd_can_unlink_peer_locked (kgn_peer_t * peer) [inline, static]
Definition at line 1284 of file gnilnd.h.
References CDEBUG, D_NET, kgn_peer::gnp_conns, kgn_peer::gnp_nid, kgn_peer::gnp_tx_queue, libcfs_nid2str(), list_empty(), and RETURN.
Referenced by kgnilnd_complete_closed_conn(), kgnilnd_del_peer_locked(), and kgnilnd_detach_purgatory_locked().
void kgnilnd_cancel_dgram_locked (kgn_dgram_t * dgram)
Definition at line 1074 of file gnilnd_conn.c.
References __u64, CDEBUG, D_NET, D_NETTRACE, kgn_conn::gnc_device, kgn_conn::gnc_ephandle, kgn_conn::gnc_state, kgn_device::gnd_canceled_dgrams, kgn_dgram::gndg_conn, kgn_dgram::gndg_state, GNI_RC_NO_MATCH, GNI_RC_SUCCESS, GNILND_CONN_ESTABLISHED, GNILND_DGRAM_CANCELED, GNILND_DGRAM_DONE, GNILND_DGRAM_POSTED, GNILND_DGRAM_WC_REQ, kgnilnd_dgram_type2str(), kgnilnd_ep_postdata_cancel_by_id(), kgnilnd_ep_postdata_test_by_id(), kgnilnd_process_dgram(), LASSERTF, libcfs_nid2str(), and RETURN_EXIT.
Referenced by kgnilnd_cancel_dgrams(), kgnilnd_cancel_net_dgrams(), kgnilnd_cancel_wc_dgrams(), kgnilnd_find_and_cancel_dgram(), kgnilnd_reaper_dgram_check(), and kgnilnd_release_dgram().
int kgnilnd_cancel_dgrams (kgn_device_t * dev)
Definition at line 1635 of file gnilnd_conn.c.
References ENTRY, kgn_device::gnd_dgram_lock, kgn_device::gnd_dgrams, kgn_dgram::gndg_type, GNILND_DGRAM_WC_REQ, kgn_tunables::kgn_peer_hash_size, kgn_data::kgn_wc_kill, kgnilnd_cancel_dgram_locked(), kgnilnd_data, kgnilnd_tunables, LASSERTF, list_for_each_entry_safe, and RETURN.
Referenced by kgnilnd_base_shutdown().
int kgnilnd_cancel_net_dgrams (kgn_net_t * net)
Definition at line 1547 of file gnilnd_conn.c.
References ENTRY, kgn_connreq::gncr_dstnid, kgn_device::gnd_dgram_lock, kgn_device::gnd_dgrams, kgn_dgram::gndg_conn_out, kgn_dgram::gndg_type, GNILND_DGRAM_WC_REQ, kgn_net::gnn_dev, kgn_net::gnn_netnum, kgn_net::gnn_shutdown, INIT_LIST_HEAD, kgn_data::kgn_in_reset, kgn_tunables::kgn_peer_hash_size, kgnilnd_cancel_dgram_locked(), kgnilnd_data, kgnilnd_tunables, LASSERTF, list_for_each_entry_safe, LNET_NETNUM(), LNET_NIDNET(), and RETURN.
Referenced by kgnilnd_reset_stack(), and kgnilnd_shutdown().
void kgnilnd_cancel_peer_connect_locked (kgn_peer_t * peer, struct list_head * zombies)
Definition at line 1433 of file gnilnd.c.
References kgn_device::gnd_connd_lock, GNILND_PEER_IDLE, GNILND_PEER_NEEDS_DEATH, GNILND_PEER_POSTING, GNILND_TX_ALLOCD, kgn_net::gnn_dev, kgn_peer::gnp_connd_list, kgn_peer::gnp_connecting, kgn_peer::gnp_last_dgram_errno, kgn_peer::gnp_net, kgn_peer::gnp_nid, kgn_peer::gnp_tx_queue, kgnilnd_find_and_cancel_dgram(), kgnilnd_peer_decref, kgnilnd_tx_del_state_locked(), LASSERTF, libcfs_nid2str(), list_add_tail(), list_del_init(), list_empty(), list_for_each_entry_safe, and kgn_tx::tx_list.
Referenced by kgnilnd_check_peer_timeouts_locked(), kgnilnd_del_conn_or_peer(), and kgnilnd_report_node_state().
int kgnilnd_cancel_wc_dgrams (kgn_device_t * dev)
Definition at line 1588 of file gnilnd_conn.c.
References ENTRY, kgn_connreq::gncr_dstnid, kgn_device::gnd_dgram_lock, kgn_dgram::gndg_conn_out, kgn_dgram::gndg_list, kgn_dgram::gndg_state, kgn_dgram::gndg_type, GNILND_DGRAM_DONE, GNILND_DGRAM_WC_REQ, INIT_LIST_HEAD, kgn_data::kgn_in_reset, kgn_data::kgn_wc_kill, kgnilnd_cancel_dgram_locked(), kgnilnd_data, kgnilnd_dgram_type2str(), kgnilnd_find_dgram_locked(), kgnilnd_release_dgram(), LASSERTF, libcfs_nid2str(), list_add_tail(), list_del_init(), list_for_each_entry_safe, LNET_NID_ANY, and RETURN.
Referenced by kgnilnd_base_shutdown(), and kgnilnd_reset_stack().
int kgnilnd_check_hw_quiesce (void)
Definition at line 512 of file gnilnd_stack.c.
References CDEBUG, D_NET, kgn_data::kgn_ruhroh_shutdown, kgnilnd_data, kgnilnd_hw_in_quiesce(), kgnilnd_pause_threads(), and likely.
Referenced by kgnilnd_reaper_check(), and kgnilnd_reaper_dgram_check().
static void kgnilnd_check_kgni_version (void) [inline, static]
Definition at line 2002 of file gnilnd.h.
References GNI_VERSION_CHECK, GNILND_KGNI_TS_MINOR_VER, kgn_data::kgn_enable_gl_mutex, kgn_tunables::kgn_thread_safe, and LCONSOLE_INFO.
Referenced by kgnilnd_base_startup().
static int kgnilnd_check_purgatory_conn (kgn_conn_t * conn) [inline, static]
Definition at line 1330 of file gnilnd.h.
References CDEBUG, D_NETTRACE, kgn_conn::gnc_close_recvd, kgn_conn::gnc_error, kgn_conn::gnc_peer, kgn_net::gnn_ni, kgn_peer::gnp_net, kgn_peer::gnp_nid, kgnilnd_check_purgatory_errno(), libcfs_nid2str(), likely, lnet_ni::ni_nid, and RETURN.
Referenced by kgnilnd_close_conn_locked(), and kgnilnd_unmap_buffer().
static int kgnilnd_check_purgatory_errno (int errno) [inline, static]
Definition at line 1317 of file gnilnd.h.
References RETURN.
Referenced by kgnilnd_check_purgatory_conn().
__u16 kgnilnd_cksum_kiov (unsigned int nkiov, lnet_kiov_t * kiov, unsigned int offset, unsigned int nob, int dump_blob) [inline]
Definition at line 306 of file gnilnd_cb.c.
References _kgnilnd_cksum, CDEBUG, cksum, CNETERR, D_BUFFS, kgn_data::kgn_cksum_map_pages, kgn_data::kgn_nvmap_cksum, kgn_tunables::kgn_vmap_cksum, kgnilnd_data, kgnilnd_dump_blob(), kgnilnd_tunables, lnet_kiov_t::kiov_len, lnet_kiov_t::kiov_offset, lnet_kiov_t::kiov_page, LASSERT, LASSERTF, and RETURN.
Referenced by _kgnilnd_proc_run_cksum_test(), kgnilnd_compute_rdma_cksum(), and kgnilnd_verify_rdma_cksum().
void kgnilnd_close_conn (kgn_conn_t * conn, int error)
Definition at line 701 of file gnilnd.c.
References kgn_conn::gnc_state, GNILND_CONN_ESTABLISHED, kgn_data::kgn_peer_conn_lock, and kgnilnd_close_conn_locked().
Referenced by kgnilnd_check_fma_rx(), kgnilnd_check_rdma_cq(), kgnilnd_process_fmaq(), kgnilnd_recv(), and kgnilnd_tx_should_retry().
void kgnilnd_close_conn_locked (kgn_conn_t * conn, int error)
Definition at line 620 of file gnilnd.c.
References CDEBUG, CFS_FAIL_CHECK, CFS_FAIL_GNI_RDMA_CQ_ERROR, CNETERR, D_NET, ENTRY, EXIT, kgn_conn::gnc_error, kgn_conn::gnc_hashlist, kgn_conn::gnc_last_rx, kgn_conn::gnc_last_rx_cq, kgn_conn::gnc_list, kgn_conn::gnc_peer, kgn_conn::gnc_peer_error, kgn_conn::gnc_state, GNILND_CONN_CLOSED, GNILND_CONN_CLOSING, GNILND_CONN_ESTABLISHED, GNILND_RCA_NODE_UP, kgn_peer::gnp_dirty_eps, kgn_peer::gnp_down, kgn_peer::gnp_last_errno, kgn_peer::gnp_nid, kgn_data::kgn_conn_version, kgn_data::kgn_in_reset, kgnilnd_add_purgatory_locked(), kgnilnd_admin_addref, kgnilnd_check_purgatory_conn(), kgnilnd_conn_clean_errno(), kgnilnd_conn_decref, kgnilnd_conn_state2str(), kgnilnd_schedule_conn, LASSERT, LASSERTF, libcfs_nid2str(), list_del_init(), list_empty(), and unlikely.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_check_fma_send_cq(), kgnilnd_check_peer_timeouts_locked(), kgnilnd_close_conn(), kgnilnd_close_peer_conns_locked(), kgnilnd_close_stale_conns_locked(), and kgnilnd_report_node_state().
int kgnilnd_close_peer_conns_locked (kgn_peer_t * peer, int why)
Definition at line 1683 of file gnilnd.c.
References kgn_conn::gnc_needs_closing, kgn_conn::gnc_state, GNILND_CONN_ESTABLISHED, kgn_peer::gnp_conns, kgn_data::kgn_npending_conns, kgnilnd_admin_addref, kgnilnd_close_conn_locked(), list_entry, and list_for_each_safe.
Referenced by kgnilnd_del_conn_or_peer(), and kgnilnd_del_peer_locked().
int kgnilnd_close_stale_conns_locked (kgn_peer_t * peer, kgn_conn_t * newconn)
Definition at line 93 of file gnilnd.c.
References CDEBUG, CWARN, D_NET, kgn_conn::gnc_device, kgn_conn::gnc_my_connstamp, kgn_conn::gnc_peer_connstamp, kgn_conn::gnc_peerstamp, kgn_conn::gnc_state, GNILND_CONN_ESTABLISHED, kgn_net::gnn_ni, kgn_peer::gnp_conns, kgn_peer::gnp_net, kgn_peer::gnp_nid, kgnilnd_close_conn_locked(), LASSERTF, libcfs_nid2str(), list_entry, list_for_each_safe, LPU64, LPX64, lnet_ni::ni_nid, and RETURN.
Referenced by kgnilnd_finish_connect(), and kgnilnd_process_nak().
void kgnilnd_complete_closed_conn (kgn_conn_t * conn)
Definition at line 713 of file gnilnd.c.
References CDEBUG, CFS_FAIL_CHECK, CFS_FAIL_GNI_FINISH_PURG, CFS_FAIL_GNI_SCHEDULE_COMPLETE, CFS_RACE, CNETERR, D_NET, D_NETERROR, ENTRY, EXIT, kgn_conn::gnc_device, kgn_conn::gnc_error, kgn_conn::gnc_hashlist, kgn_conn::gnc_in_purgatory, kgn_conn::gnc_list, kgn_conn::gnc_needs_closing, kgn_conn::gnc_nlive_rdma, kgn_conn::gnc_nq_rdma, kgn_conn::gnc_peer, kgn_conn::gnc_peer_error, kgn_conn::gnc_sched_caller, kgn_conn::gnc_sched_line, kgn_conn::gnc_scheduled, kgn_conn::gnc_state, kgn_conn::gnc_tx_ref_table, kgn_device::gnd_lock, kgn_device::gnd_rdmaq_lock, GNIDBG_TX, GNILND_CONN_CLOSED, GNILND_CONN_DONE, GNILND_CONN_PROCESS, GNILND_MAX_MSG_ID, GNILND_MSG_CLOSE, GNILND_RCA_NODE_UP, GNILND_TX_ALLOCD, GNILND_TX_QUIET_ERROR, kgn_peer::gnp_down, kgn_peer::gnp_nid, kgn_peer::gnp_pending_unlink, kgn_tunables::kgn_checksum_dump, kgn_data::kgn_npending_conns, kgn_data::kgn_peer_conn_lock, kgnilnd_admin_decref, kgnilnd_can_unlink_peer_locked(), kgnilnd_conn_decref, kgnilnd_conn_state2str(), kgnilnd_destroy_conn_ep(), kgnilnd_peer_active(), kgnilnd_peer_notify(), kgnilnd_schedule_conn, kgnilnd_tunables, kgnilnd_tx_del_state_locked(), kgnilnd_tx_done(), kgnilnd_unlink_peer_locked(), LASSERT, LASSERTF, libcfs_debug_dumplog(), libcfs_nid2str(), list_add_tail(), list_del_init(), list_empty(), list_for_each_entry_safe, LIST_HEAD(), logmsg, RETURN_EXIT, kgn_tx::tx_list, kgn_tx::tx_msg, and kgn_tx::tx_state.
Referenced by kgnilnd_process_conns(), and kgnilnd_reset_stack().
static int kgnilnd_conn_clean_errno (int errno) [inline, static]
Definition at line 1299 of file gnilnd.h.
References RETURN.
Referenced by kgnilnd_close_conn_locked(), kgnilnd_peer_notify(), kgnilnd_query(), and kgnilnd_tx_done().
static const char* kgnilnd_conn_dgram_type2str (kgn_dgram_type_t type) [inline, static]
Definition at line 1972 of file gnilnd.h.
References DO_TYPE, GNILND_DGRAM_CLOSE, GNILND_DGRAM_NAK, GNILND_DGRAM_REQ, and GNILND_DGRAM_WC_REQ.
Referenced by kgnilnd_proc_peer_conns_seq_show().
int kgnilnd_conn_isdup_locked (kgn_peer_t * peer, kgn_conn_t * newconn)
Definition at line 166 of file gnilnd.c.
References CDEBUG, D_NET, ENTRY, kgn_conn::gnc_device, kgn_conn::gnc_my_connstamp, kgn_conn::gnc_peer_connstamp, kgn_conn::gnc_peerstamp, kgn_conn::gnc_state, GNILND_CONN_ESTABLISHED, kgn_net::gnn_ni, kgn_peer::gnp_conns, kgn_peer::gnp_net, kgn_peer::gnp_nid, libcfs_nid2str(), list_entry, list_for_each, LPU64, lnet_ni::ni_nid, and RETURN.
Referenced by kgnilnd_finish_connect().
static void kgnilnd_conn_mutex_lock (struct mutex * lock) [inline, static]
Definition at line 913 of file gnilnd.h.
References kgn_data::kgn_enable_gl_mutex.
Referenced by kgnilnd_check_fma_send_cq(), kgnilnd_check_rdma_cq(), kgnilnd_rdma(), and kgnilnd_sendmsg().
static void kgnilnd_conn_mutex_unlock (struct mutex * lock) [inline, static]
Definition at line 919 of file gnilnd.h.
References kgn_data::kgn_enable_gl_mutex.
Referenced by kgnilnd_check_fma_send_cq(), kgnilnd_check_rdma_cq(), kgnilnd_rdma(), and kgnilnd_sendmsg_nolock().
static const char* kgnilnd_conn_state2str (kgn_conn_t * conn) [inline, static]
Definition at line 1912 of file gnilnd.h.
References DO_TYPE, kgn_conn::gnc_state, GNILND_CONN_CLOSED, GNILND_CONN_CLOSING, GNILND_CONN_CONNECTING, GNILND_CONN_DESTROY_EP, GNILND_CONN_DONE, GNILND_CONN_DUMMY, GNILND_CONN_ESTABLISHED, GNILND_CONN_LISTEN, and state.
Referenced by _kgnilnd_debug_conn(), kgnilnd_check_conn_timeouts_locked(), kgnilnd_close_conn_locked(), kgnilnd_complete_closed_conn(), kgnilnd_conn_seq_show(), kgnilnd_detach_purgatory_locked(), kgnilnd_find_conn_locked(), kgnilnd_proc_peer_conns_seq_show(), and kgnilnd_process_conns().
static const char* kgnilnd_connreq_type2str (kgn_connreq_t * connreq) [inline, static]
Definition at line 1929 of file gnilnd.h.
References DO_TYPE, kgn_connreq::gncr_type, GNILND_CONNREQ_CLOSE, GNILND_CONNREQ_NAK, and GNILND_CONNREQ_REQ.
Referenced by kgnilnd_post_dgram(), and kgnilnd_process_connreq().
void kgnilnd_consume_rx (kgn_rx_t * rx)
Definition at line 2084 of file gnilnd_cb.c.
References CDEBUG, D_MALLOC, D_NET, GNIDBG_MSG, kgn_rx::grx_conn, kgn_rx::grx_eager, kgn_rx::grx_msg, kgn_tunables::kgn_max_immediate, kgn_data::kgn_neager_allocs, kgn_data::kgn_rx_cache, kgnilnd_conn_decref, kgnilnd_data, kgnilnd_release_msg(), kgnilnd_tunables, LIBCFS_FREE, and unlikely.
Referenced by kgnilnd_check_fma_rx(), and kgnilnd_recv().
static int kgnilnd_count_list (struct list_head * q) [inline, static]
Definition at line 1675 of file gnilnd.h.
References list_for_each.
Referenced by kgnilnd_add_purgatory_locked(), kgnilnd_conn_seq_show(), kgnilnd_destroy_conn(), kgnilnd_detach_purgatory_locked(), kgnilnd_dev_fini(), kgnilnd_get_conn_info(), kgnilnd_peer_seq_show(), and kgnilnd_reset_stack().
static kgn_conn_t* kgnilnd_cqid2conn_locked (__u32 cqid) [inline, static]
Definition at line 1541 of file gnilnd.h.
References kgn_conn::gnc_cqid, kgnilnd_cqid2connlist(), list_entry, and list_for_each.
Referenced by kgnilnd_check_fma_rcv_cq(), kgnilnd_check_fma_send_cq(), kgnilnd_get_cqid_locked(), and kgnilnd_validate_tx_ev_id().
static struct list_head* kgnilnd_cqid2connlist (__u32 cqid) [static, read]
Definition at line 1533 of file gnilnd.h.
References kgn_data::kgn_conns, and kgn_tunables::kgn_peer_hash_size.
Referenced by kgnilnd_cqid2conn_locked(), and kgnilnd_finish_connect().
int kgnilnd_create_conn (kgn_conn_t ** connp, kgn_device_t * dev)
Definition at line 228 of file gnilnd.c.
References CDEBUG, CERROR, CLASSERT, D_NET, kgn_conn::gnc_cqid, kgn_conn::gnc_device, kgn_conn::gnc_ephandle, kgn_conn::gnc_fmaq, kgn_conn::gnc_hashlist, kgn_conn::gnc_list, kgn_conn::gnc_list_lock, kgn_conn::gnc_magic, kgn_conn::gnc_mdd_list, kgn_conn::gnc_my_connstamp, kgn_conn::gnc_next_tx, kgn_conn::gnc_rdma_mutex, kgn_conn::gnc_reaper_noop, kgn_conn::gnc_refcount, kgn_conn::gnc_sched_noop, kgn_conn::gnc_schedlist, kgn_conn::gnc_smsg_mutex, kgn_conn::gnc_timeout, kgn_conn::gnc_tx_in_use, kgn_conn::gnc_tx_lock, kgn_conn::gnc_tx_ref_table, kgn_device::gnd_cq_mutex, kgn_device::gnd_handle, kgn_device::gnd_neps, kgn_device::gnd_snd_fma_cqh, GNI_RC_SUCCESS, GNILND_CONN_MAGIC, GNILND_MAX_CQID, GNILND_MAX_MSG_ID, GNILND_MIN_TIMEOUT, GNILND_MSGID_CLOSE, GOTO, INIT_LIST_HEAD, kgn_data::kgn_connstamp, kgn_data::kgn_nconns, kgn_data::kgn_peer_conn_lock, kgn_tunables::kgn_timeout, kgnilnd_conn_addref, kgnilnd_ep_create(), kgnilnd_get_cqid_locked(), kgnilnd_tunables, kgnilnd_update_reaper_timeout(), kgnilnd_vzalloc(), LASSERT, LIBCFS_ALLOC, LIBCFS_FREE, and MAX.
Referenced by kgnilnd_post_dgram().
int kgnilnd_create_peer_safe (kgn_peer_t ** peerp, lnet_nid_t nid, kgn_net_t * net, int node_state)
Definition at line 972 of file gnilnd.c.
References CDEBUG, D_NET, kgn_net::gnn_shutdown, kgn_peer::gnp_connd_list, kgn_peer::gnp_conns, kgn_peer::gnp_dirty_eps, kgn_peer::gnp_down, kgn_peer::gnp_host_id, kgn_peer::gnp_list, kgn_peer::gnp_net, kgn_peer::gnp_nid, kgn_peer::gnp_refcount, kgn_peer::gnp_tx_queue, INIT_LIST_HEAD, kgn_data::kgn_npeers, kgnilnd_find_net(), kgnilnd_net_addref, kgnilnd_net_decref, kgnilnd_nid_to_nicaddrs(), LASSERT, LASSERTF, LIBCFS_ALLOC, LIBCFS_FREE, libcfs_nid2str(), LNET_NID_ANY, and LNET_NIDADDR().
Referenced by kgnilnd_add_peer(), kgnilnd_finish_connect(), and kgnilnd_launch_tx().
void kgnilnd_critical_error (gni_err_handle_t err_handle)
Referenced by kgnilnd_dev_init().
int kgnilnd_ctl (lnet_ni_t * ni, unsigned int cmd, void * arg)
Definition at line 1805 of file gnilnd.c.
References __u64, CERROR, kgn_conn::gnc_device, kgn_conn::gnc_peer, kgn_device::gnd_id, GNILND_CLEAR_PURGATORY, GNILND_DEL_CONN, GNILND_DEL_PEER, kgn_net::gnn_ni, kgn_peer::gnp_nid, libcfs_ioctl_data::ioc_count, libcfs_ioctl_data::ioc_flags, IOC_LIBCFS_ADD_PEER, IOC_LIBCFS_CLOSE_CONNECTION, IOC_LIBCFS_DEL_PEER, IOC_LIBCFS_GET_CONN, IOC_LIBCFS_GET_PEER, IOC_LIBCFS_PUSH_CONNECTION, IOC_LIBCFS_REGISTER_MYNID, libcfs_ioctl_data::ioc_net, libcfs_ioctl_data::ioc_nid, libcfs_ioctl_data::ioc_u32, libcfs_ioctl_data::ioc_u64, kgnilnd_add_peer(), kgnilnd_conn_decref, kgnilnd_del_conn_or_peer(), kgnilnd_get_conn_by_idx(), kgnilnd_get_conn_info(), kgnilnd_get_peer_info(), LASSERT, libcfs_nid2str(), LNET_MKNID(), LNET_NIDADDR(), LNET_NIDNET(), lnet_ni::ni_data, and lnet_ni::ni_nid.
int kgnilnd_del_conn_or_peer (kgn_net_t * net, lnet_nid_t nid, int command, int error)
Definition at line 1507 of file gnilnd.c.
References CDEBUG, CERROR, CFS_FAIL_GNI_RACE_RESET, CFS_RACE, cfs_time_seconds(), D_NET, D_WARNING, GNILND_CLEAR_PURGATORY, GNILND_DEL_CONN, GNILND_DEL_PEER, kgn_peer::gnp_last_errno, kgn_peer::gnp_net, kgn_peer::gnp_nid, kgn_peer::gnp_pending_unlink, kgn_peer::gnp_reconnect_interval, kgn_peer::gnp_reconnect_time, kgn_data::kgn_npending_conns, kgn_data::kgn_npending_detach, kgn_data::kgn_npending_unlink, kgn_data::kgn_peer_conn_lock, kgn_tunables::kgn_peer_hash_size, kgn_data::kgn_peers, kgnilnd_admin_addref, kgnilnd_cancel_peer_connect_locked(), kgnilnd_close_peer_conns_locked(), kgnilnd_del_peer_locked(), kgnilnd_mark_for_detach_purgatory_all_locked(), kgnilnd_nid2peerlist(), kgnilnd_tunables, kgnilnd_txlist_done(), LASSERTF, LBUG, libcfs_nid2str(), list_entry, list_for_each_safe, LIST_HEAD(), LNET_NID_ANY, and LNET_NIDADDR().
Referenced by kgnilnd_base_shutdown(), kgnilnd_ctl(), kgnilnd_reset_stack(), and kgnilnd_shutdown().
void kgnilnd_destroy_conn (kgn_conn_t * conn)
Definition at line 443 of file gnilnd.c.
References CDEBUG, D_NET, kgn_conn::gnc_ephandle, kgn_conn::gnc_error, kgn_conn::gnc_fma_blk, kgn_conn::gnc_fmaq, kgn_conn::gnc_hashlist, kgn_conn::gnc_in_purgatory, kgn_conn::gnc_list, kgn_conn::gnc_magic, kgn_conn::gnc_mbox_id, kgn_conn::gnc_mdd_list, kgn_conn::gnc_nlive_fma, kgn_conn::gnc_nlive_rdma, kgn_conn::gnc_peer, kgn_conn::gnc_schedlist, kgn_conn::gnc_scheduled, kgn_conn::gnc_tx_ref_table, GNILND_CONN_MAGIC, GNILND_MAX_MSG_ID, kgn_fma_memblock::gnm_mbox_info, kgn_peer::gnp_nid, kgn_data::kgn_nconns, kgnilnd_count_list(), kgnilnd_peer_decref, kgnilnd_release_mbox(), LASSERTF, LIBCFS_FREE, libcfs_nid2str(), list_empty(), and kgn_mbox_info::mbx_prev_nid.
void kgnilnd_destroy_conn_ep (kgn_conn_t * conn)
Definition at line 407 of file gnilnd.c.
References kgn_conn::gnc_device, kgn_conn::gnc_ephandle, kgn_conn::gnc_peer, kgn_device::gnd_cq_mutex, kgn_device::gnd_neps, GNI_RC_SUCCESS, kgn_peer::gnp_dirty_eps, kgnilnd_admin_decref, kgnilnd_conn_decref, kgnilnd_ep_destroy(), and LASSERTF.
Referenced by kgnilnd_complete_closed_conn(), kgnilnd_process_conns(), and kgnilnd_reset_stack().
void kgnilnd_destroy_peer (kgn_peer_t * peer)
Definition at line 1050 of file gnilnd.c.
References CDEBUG, D_NET, GNILND_PEER_IDLE, GNILND_PEER_KILL, kgn_peer::gnp_connd_list, kgn_peer::gnp_connecting, kgn_peer::gnp_conns, kgn_peer::gnp_dirty_eps, kgn_peer::gnp_net, kgn_peer::gnp_nid, kgn_peer::gnp_refcount, kgn_peer::gnp_tx_queue, kgn_data::kgn_npeers, kgnilnd_net_decref, kgnilnd_peer_active(), LASSERTF, LIBCFS_FREE, libcfs_nid2str(), and list_empty().
void kgnilnd_detach_purgatory_locked (kgn_conn_t * conn, struct list_head * conn_list)
Definition at line 1149 of file gnilnd.c.
References CDEBUG, D_NET, kgn_conn::gnc_fma_blk, kgn_conn::gnc_in_purgatory, kgn_conn::gnc_list, kgn_conn::gnc_mbox_id, kgn_conn::gnc_mdd_list, kgn_conn::gnc_peer, kgn_conn::gnc_state, GNILND_CONN_DONE, kgn_fma_memblock::gnm_mbox_info, kgn_peer::gnp_nid, kgn_peer::gnp_pending_unlink, kgnilnd_can_unlink_peer_locked(), kgnilnd_conn_state2str(), kgnilnd_count_list(), kgnilnd_peer_active(), kgnilnd_unlink_peer_locked(), LASSERTF, libcfs_nid2str(), list_add_tail(), list_del_init(), and kgn_mbox_info::mbx_detach_of_purgatory.
Referenced by kgnilnd_check_peer_timeouts_locked(), and kgnilnd_reset_stack().
void kgnilnd_dev_fini (kgn_device_t * dev)
Definition at line 2115 of file gnilnd.c.
References ENTRY, EXIT, kgn_device::gnd_domain, kgn_device::gnd_err_handle, kgn_device::gnd_map_list, kgn_device::gnd_map_nphys, kgn_device::gnd_map_nvirt, kgn_device::gnd_map_physnop, kgn_device::gnd_map_tx, kgn_device::gnd_map_virtnob, kgn_device::gnd_n_mdd, kgn_device::gnd_n_mdd_held, kgn_device::gnd_nbytes_map, kgn_device::gnd_rcv_fma_cqh, kgn_device::gnd_rdmaq, kgn_device::gnd_ready_conns, kgn_device::gnd_smdd_hold_buf, kgn_device::gnd_snd_fma_cqh, kgn_device::gnd_snd_rdma_cqh, GNI_RC_SUCCESS, kgn_data::kgn_nthreads, kgn_data::kgn_quiesce_trigger, kgn_data::kgn_sock, kgnilnd_cdm_destroy(), kgnilnd_count_list(), kgnilnd_cq_destroy(), kgnilnd_deregister_smdd_buf(), kgnilnd_release_errors(), LASSERT, LASSERTF, list_empty(), and LPU64.
Referenced by kgnilnd_base_shutdown(), kgnilnd_dev_init(), and kgnilnd_reset_stack().
int kgnilnd_dev_init (kgn_device_t * dev)
Definition at line 1996 of file gnilnd.c.
References CDEBUG, CERROR, D_NET, ENTRY, kgn_device::gnd_domain, kgn_device::gnd_err_handle, kgn_device::gnd_handle, kgn_device::gnd_host_id, kgn_device::gnd_id, kgn_device::gnd_nid, kgn_device::gnd_rcv_fma_cqh, kgn_device::gnd_snd_fma_cqh, kgn_device::gnd_snd_rdma_cqh, GNI_ERRMASK_CRITICAL, GNI_ERRMASK_UNKNOWN_TRANSACTION, GNI_RC_SUCCESS, GNILND_INIT_ALL, GOTO, kgn_tunables::kgn_credits, kgn_tunables::kgn_fma_cq_size, kgn_data::kgn_init, kgn_tunables::kgn_pkey, kgn_tunables::kgn_ptag, kgn_data::kgn_sock, kgnilnd_cdm_attach(), kgnilnd_cdm_create(), kgnilnd_cq_create(), kgnilnd_critical_error(), kgnilnd_dev_fini(), kgnilnd_device_callback(), kgnilnd_nicaddr_to_nid(), kgnilnd_quiesce_end_callback(), kgnilnd_register_smdd_buf(), kgnilnd_set_quiesce_callback(), kgnilnd_setup_nic_translation(), kgnilnd_subscribe_errors(), kgnilnd_tunables, and RETURN.
Referenced by kgnilnd_base_startup(), and kgnilnd_reset_stack().
void kgnilnd_device_callback (__u32 devid, __u64 arg)
Definition at line 95 of file gnilnd_cb.c.
References kgn_device::gnd_id, kgn_data::kgn_devices, kgn_data::kgn_ndevs, kgnilnd_data, kgnilnd_schedule_device(), and LCONSOLE_EMERG.
Referenced by kgnilnd_dev_init().
int kgnilnd_dgram_mover (void * arg)
Definition at line 2447 of file gnilnd_conn.c.
References CDEBUG, cfs_block_allsigs(), cfs_duration_sec(), CFS_FAIL_GNI_DGRAM_DEADLINE, CFS_FAIL_GNI_QUIESCE_RACE, CFS_FAIL_GNI_WC_DGRAM_FREE, CFS_FAIL_TIMEOUT, CFS_RACE, cfs_time_seconds(), D_INFO, kgn_device::gnd_dgping_waitq, kgn_device::gnd_dgram_ready, kgn_device::gnd_dgram_waitq, kgn_device::gnd_id, GNILND_DGRAM_IDLE, kgn_tunables::kgn_dgram_timeout, kgn_data::kgn_net_rw_sem, kgn_data::kgn_new_min_timeout, kgn_tunables::kgn_nice, kgn_data::kgn_quiesce_trigger, kgn_data::kgn_shutdown, kgnilnd_data, kgnilnd_dgram_poke_with_stick(), kgnilnd_probe_and_process_dgram(), kgnilnd_reaper_dgram_check(), kgnilnd_repost_wc_dgrams(), KGNILND_SPIN_QUIESCE, kgnilnd_start_outbound_dgrams(), kgnilnd_thread_fini(), kgnilnd_tunables, name, timeout, and unlikely.
Referenced by kgnilnd_base_startup().
static const char* kgnilnd_dgram_state2str (kgn_dgram_t * dgram) [inline, static]
Definition at line 1942 of file gnilnd.h.
References DO_TYPE, kgn_dgram::gndg_state, GNILND_DGRAM_CANCELED, GNILND_DGRAM_DONE, GNILND_DGRAM_POSTED, GNILND_DGRAM_POSTING, GNILND_DGRAM_PROCESSING, GNILND_DGRAM_USED, and state.
Referenced by kgnilnd_free_dgram(), kgnilnd_probe_for_dgram(), kgnilnd_process_dgram(), and kgnilnd_reaper_dgram_check().
static const char* kgnilnd_dgram_type2str (kgn_dgram_t * dgram) [inline, static]
Definition at line 1958 of file gnilnd.h.
References DO_TYPE, kgn_dgram::gndg_type, GNILND_DGRAM_CLOSE, GNILND_DGRAM_NAK, GNILND_DGRAM_REQ, and GNILND_DGRAM_WC_REQ.
Referenced by kgnilnd_alloc_dgram(), kgnilnd_cancel_dgram_locked(), kgnilnd_cancel_wc_dgrams(), kgnilnd_free_dgram(), kgnilnd_post_dgram(), kgnilnd_probe_and_process_dgram(), kgnilnd_probe_for_dgram(), kgnilnd_process_dgram(), kgnilnd_reaper_dgram_check(), and kgnilnd_unpack_connreq().
int kgnilnd_dgram_waitq (void * arg)
Definition at line 2270 of file gnilnd_conn.c.
References __u64, CDEBUG, cfs_block_allsigs(), CFS_FAIL_GNI_PAUSE_DGRAM_COMP, CFS_FAIL_TIMEOUT, D_INFO, kgn_device::gnd_dgping_waitq, kgn_device::gnd_handle, kgn_device::gnd_id, GNI_RC_SUCCESS, kgn_tunables::kgn_nice, kgn_data::kgn_quiesce_trigger, kgn_data::kgn_shutdown, kgnilnd_data, kgnilnd_postdata_probe_wait_by_id(), kgnilnd_schedule_dgram(), KGNILND_SPIN_QUIESCE, kgnilnd_thread_fini(), kgnilnd_tunables, likely, name, and unlikely.
Referenced by kgnilnd_base_startup().
int kgnilnd_eager_recv (lnet_ni_t * ni, void * private, lnet_msg_t * lntmsg, void ** new_private)
Definition at line 2342 of file gnilnd_cb.c.
References CERROR, D_ERROR, D_NET, kgn_conn::gnc_peer, kgn_conn::gnc_peer_connstamp, GNIDBG_MSG, kgn_peer::gnp_nid, kgn_rx::grx_conn, kgn_rx::grx_eager, kgn_rx::grx_lntmsg, kgn_rx::grx_msg, kgn_tunables::kgn_eager_credits, kgn_tunables::kgn_max_immediate, kgn_data::kgn_neager_allocs, kgn_data::kgn_peer_conn_lock, kgnilnd_conn_addref, kgnilnd_conn_decref, kgnilnd_data, kgnilnd_find_conn_locked(), kgnilnd_find_peer_locked(), kgnilnd_release_msg(), kgnilnd_tunables, LIBCFS_ALLOC, libcfs_nid2str(), and LPX64.
int kgnilnd_find_and_cancel_dgram (kgn_device_t * dev, lnet_nid_t dst_nid)
Definition at line 713 of file gnilnd_conn.c.
References kgn_device::gnd_dgram_lock, kgnilnd_cancel_dgram_locked(), kgnilnd_find_dgram_locked(), and RETURN.
Referenced by kgnilnd_cancel_peer_connect_locked(), kgnilnd_process_nak(), and kgnilnd_start_connect().
kgn_conn_t* kgnilnd_find_conn_locked (kgn_peer_t * peer)
Definition at line 329 of file gnilnd.c.
References kgn_conn::gnc_state, GNILND_CONN_ESTABLISHED, kgn_peer::gnp_conns, kgn_peer::gnp_nid, kgn_data::kgn_in_reset, kgnilnd_conn_state2str(), LASSERTF, libcfs_nid2str(), list_for_each_entry, RETURN, and unlikely.
Referenced by kgnilnd_check_peer_timeouts_locked(), kgnilnd_eager_recv(), kgnilnd_find_or_create_conn_locked(), kgnilnd_get_conn_info(), kgnilnd_launch_tx(), kgnilnd_peer_notify(), kgnilnd_peer_seq_show(), kgnilnd_query(), and kgnilnd_report_node_state().
static int kgnilnd_find_net (lnet_nid_t nid, kgn_net_t ** netp) [inline, static]
Definition at line 1694 of file gnilnd.h.
References kgn_net::gnn_ni, kgn_net::gnn_shutdown, kgn_data::kgn_net_rw_sem, kgnilnd_net_addref, kgnilnd_netnum2netlist(), list_for_each_entry, LNET_NETNUM(), LNET_NIDNET(), and lnet_ni::ni_nid.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_create_peer_safe(), and kgnilnd_unpack_connreq().
kgn_conn_t* kgnilnd_find_or_create_conn_locked (kgn_peer_t * peer)
Definition at line 356 of file gnilnd.c.
References CDEBUG, D_NET, D_NETTRACE, kgn_conn::gnc_ephandle, kgn_device::gnd_connd_lock, kgn_device::gnd_connd_peers, GNILND_PEER_CONNECT, GNILND_PEER_IDLE, kgn_net::gnn_dev, kgn_peer::gnp_connd_list, kgn_peer::gnp_connecting, kgn_peer::gnp_conns, kgn_peer::gnp_net, kgn_peer::gnp_nid, kgn_peer::gnp_reconnect_time, kgnilnd_find_conn_locked(), kgnilnd_peer_addref, kgnilnd_schedule_dgram(), libcfs_nid2str(), list_add_tail(), and list_for_each_entry.
Referenced by kgnilnd_launch_tx().
kgn_peer_t* kgnilnd_find_peer_locked (lnet_nid_t nid)
Definition at line 1274 of file gnilnd.c.
References CDEBUG, D_NET, kgn_peer::gnp_connecting, kgn_peer::gnp_nid, kgn_peer::gnp_refcount, kgnilnd_nid2peerlist(), libcfs_nid2str(), list_for_each_entry, and LNET_NIDADDR().
Referenced by kgnilnd_add_peer_locked(), kgnilnd_eager_recv(), kgnilnd_launch_tx(), kgnilnd_probe_and_process_dgram(), kgnilnd_proc_peer_conns_seq_show(), kgnilnd_process_nak(), kgnilnd_query(), kgnilnd_release_dgram(), and kgnilnd_report_node_state().
static const char* kgnilnd_fmablk_state2str (kgn_fmablk_state_t state) [inline, static]
Definition at line 1851 of file gnilnd.h.
References GNILND_FMABLK_FREED, GNILND_FMABLK_IDLE, GNILND_FMABLK_PHYS, and GNILND_FMABLK_VIRT.
Referenced by kgnilnd_smsg_seq_show(), and kgnilnd_unmap_fmablk().
void kgnilnd_free_phys_fmablk (kgn_device_t * device)
Definition at line 661 of file gnilnd_conn.c.
References kgn_device::gnd_fma_buffs, kgn_device::gnd_fmablk_lock, kgn_device::gnd_fmablk_mutex, GNILND_FMABLK_PHYS, kgn_fma_memblock::gnm_state, kgnilnd_free_fmablk_locked(), and list_for_each_entry_safe.
Referenced by kgnilnd_base_shutdown().
int kgnilnd_get_conn (kgn_conn_t ** connp, kgn_peer_t)
static __u32 kgnilnd_get_cqid_locked (void) [inline, static]
Definition at line 1559 of file gnilnd.h.
References GNILND_MAX_CQID, kgn_data::kgn_next_cqid, and kgnilnd_cqid2conn_locked().
Referenced by kgnilnd_create_conn().
int kgnilnd_get_node_state (__u32 nid)
Definition at line 811 of file gnilnd_stack.c.
References GNILND_RCA_NODE_UP.
Referenced by kgnilnd_add_peer(), and kgnilnd_launch_tx().
static void kgnilnd_gl_mutex_lock (struct mutex * lock) [inline, static]
Definition at line 901 of file gnilnd.h.
References kgn_data::kgn_enable_gl_mutex.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_rdma(), kgnilnd_release_msg(), and kgnilnd_sendmsg().
static void kgnilnd_gl_mutex_unlock (struct mutex * lock) [inline, static]
Definition at line 907 of file gnilnd.h.
References kgn_data::kgn_enable_gl_mutex.
Referenced by kgnilnd_check_fma_rcv_cq(), kgnilnd_check_fma_rx(), kgnilnd_check_fma_send_cq(), kgnilnd_check_rdma_cq(), kgnilnd_rdma(), kgnilnd_release_msg(), and kgnilnd_sendmsg_nolock().
int kgnilnd_hw_in_quiesce (void)
Definition at line 497 of file gnilnd_stack.c.
References kgn_device::gnd_handle, kgn_data::kgn_devices, kgnilnd_data, kgnilnd_get_quiesce_status(), and LASSERTF.
Referenced by kgnilnd_check_hw_quiesce(), and kgnilnd_ruhroh_thread().
void kgnilnd_init_msg (kgn_msg_t * msg, int type, lnet_nid_t source)
Definition at line 417 of file gnilnd_cb.c.
References GNILND_MSG_MAGIC, and GNILND_MSG_VERSION.
Referenced by kgnilnd_new_tx_msg(), and kgnilnd_rdma().
void kgnilnd_insert_sysctl (void)
Definition at line 314 of file gnilnd_sysctl.c.
Referenced by kgnilnd_init().
void kgnilnd_launch_tx (kgn_tx_t * tx, kgn_net_t * net, lnet_process_id_t * target)
Definition at line 1773 of file gnilnd_cb.c.
References CFS_FAIL_CHECK, CFS_FAIL_GNI_DGRAM_DROP_TX, CFS_FAIL_GNI_FIND_TARGET, CFS_RACE, ENTRY, GNILND_RCA_NODE_DOWN, GNILND_RCA_NODE_UP, GNILND_TX_PEERQ, GNITX_ASSERTF, kgn_peer::gnp_down, GOTO, kgn_data::kgn_net_rw_sem, kgn_data::kgn_peer_conn_lock, kgnilnd_add_peer_locked(), kgnilnd_create_peer_safe(), kgnilnd_data, kgnilnd_find_conn_locked(), kgnilnd_find_or_create_conn_locked(), kgnilnd_find_peer_locked(), kgnilnd_get_node_state(), kgnilnd_queue_tx(), kgnilnd_tx_add_state_locked(), kgnilnd_tx_done(), LNET_NIDADDR(), lnet_process_id_t::nid, RETURN_EXIT, kgn_tx::tx_conn, and kgn_tx::tx_qtime.
Referenced by kgnilnd_query(), and kgnilnd_send().
static lnet_nid_t kgnilnd_lnd2lnetnid (lnet_nid_t ni_nid, lnet_nid_t kgnilnd_nid) [inline, static]
Definition at line 608 of file gnilnd.h.
References LNET_MKNID(), LNET_NIDADDR(), and LNET_NIDNET().
Referenced by kgnilnd_peer_notify().
static lnet_nid_t kgnilnd_lnet2lndnid (lnet_nid_t lnet_nid, lnet_nid_t kgnilnd_nid) [inline, static]
Definition at line 614 of file gnilnd.h.
References LNET_MKNID(), LNET_NIDADDR(), and LNET_NIDNET().
int kgnilnd_map_phys_fmablk (kgn_device_t * device)
Definition at line 616 of file gnilnd_conn.c.
References kgn_device::gnd_fma_buffs, kgn_device::gnd_fmablk_lock, kgn_device::gnd_fmablk_mutex, GNILND_FMABLK_PHYS, kgn_fma_memblock::gnm_state, kgnilnd_map_fmablk(), list_for_each_entry, and RETURN.
Referenced by kgnilnd_reset_stack().
void kgnilnd_mark_for_detach_purgatory_all_locked (kgn_peer_t * peer)
Definition at line 1136 of file gnilnd.c.
References kgn_conn::gnc_in_purgatory, kgn_conn::gnc_needs_detach, kgn_peer::gnp_conns, kgn_data::kgn_npending_detach, kgnilnd_admin_addref, and list_for_each_entry.
Referenced by kgnilnd_del_conn_or_peer().
static const char* kgnilnd_msgtype2str (int type) [inline, static]
Definition at line 1868 of file gnilnd.h.
References DO_TYPE, GNILND_MSG_CLOSE, GNILND_MSG_GET_ACK_REV, GNILND_MSG_GET_DONE, GNILND_MSG_GET_DONE_REV, GNILND_MSG_GET_NAK, GNILND_MSG_GET_NAK_REV, GNILND_MSG_GET_REQ, GNILND_MSG_GET_REQ_REV, GNILND_MSG_IMMEDIATE, GNILND_MSG_NONE, GNILND_MSG_NOOP, GNILND_MSG_PUT_ACK, GNILND_MSG_PUT_DONE, GNILND_MSG_PUT_DONE_REV, GNILND_MSG_PUT_NAK, GNILND_MSG_PUT_NAK_REV, GNILND_MSG_PUT_REQ, and GNILND_MSG_PUT_REQ_REV.
Referenced by _kgnilnd_debug_msg(), _kgnilnd_debug_tx(), kgnilnd_check_fma_rx(), kgnilnd_compute_rdma_cksum(), kgnilnd_nak_rdma(), kgnilnd_new_tx_msg(), kgnilnd_process_fmaq(), kgnilnd_queue_tx(), kgnilnd_rdma(), kgnilnd_setup_rdma(), and kgnilnd_verify_rdma_cksum().
static int kgnilnd_mutex_trylock (struct mutex * lock) [inline, static]
Definition at line 954 of file gnilnd.h.
References __kgnilnd_mutex_trylock(), and kgn_data::kgn_enable_gl_mutex.
Referenced by kgnilnd_check_fma_rcv_cq(), kgnilnd_check_fma_send_cq(), and kgnilnd_check_rdma_cq().
static struct list_head* kgnilnd_netnum2netlist (__u16 netnum) [static, read]
Definition at line 1268 of file gnilnd.h.
References kgn_tunables::kgn_net_hash_size, kgn_data::kgn_nets, and RETURN.
Referenced by kgnilnd_find_net(), and kgnilnd_startup().
kgn_tx_t* kgnilnd_new_tx_msg (int type, lnet_nid_t source)
Definition at line 432 of file gnilnd_cb.c.
References CERROR, kgnilnd_alloc_tx(), kgnilnd_init_msg(), kgnilnd_msgtype2str(), and kgn_tx::tx_msg.
Referenced by kgnilnd_check_conn_timeouts_locked(), kgnilnd_finish_connect(), kgnilnd_nak_rdma(), kgnilnd_process_fmaq(), kgnilnd_query(), kgnilnd_recv(), kgnilnd_send(), kgnilnd_send_conn_close(), and kgnilnd_setup_rdma().
static struct list_head* kgnilnd_nid2peerlist (lnet_nid_t nid) [static, read]
Definition at line 1260 of file gnilnd.h.
References kgn_tunables::kgn_peer_hash_size, kgn_data::kgn_peers, LNET_NIDADDR(), and RETURN.
Referenced by kgnilnd_add_peer_locked(), kgnilnd_del_conn_or_peer(), and kgnilnd_find_peer_locked().
void kgnilnd_pause_threads (void)
Definition at line 471 of file gnilnd_stack.c.
References CDEBUG, D_NET, GNILND_IS_QUIESCED, GNILND_QUIESCE_HW_QUIESCE, kgn_data::kgn_devices, kgn_data::kgn_needs_pause, kgn_data::kgn_quiesce_trigger, kgn_data::kgn_ruhroh_waitq, kgnilnd_data, and LASSERTF.
Referenced by kgnilnd_check_hw_quiesce(), and kgnilnd_quiesce_end_callback().
static int kgnilnd_peer_active (kgn_peer_t * peer) [inline, static]
Definition at line 1276 of file gnilnd.h.
References kgn_peer::gnp_list, and list_empty().
Referenced by kgnilnd_add_peer_locked(), kgnilnd_add_purgatory_locked(), kgnilnd_complete_closed_conn(), kgnilnd_del_peer_locked(), kgnilnd_destroy_peer(), kgnilnd_detach_purgatory_locked(), kgnilnd_start_connect(), and kgnilnd_unlink_peer_locked().
void kgnilnd_peer_alive (kgn_peer_t * peer)
Definition at line 506 of file gnilnd.c.
References kgn_peer::gnp_last_alive.
Referenced by kgnilnd_bump_timeouts(), kgnilnd_check_fma_rcv_cq(), kgnilnd_check_fma_rx(), kgnilnd_check_rdma_cq(), kgnilnd_finish_connect(), and kgnilnd_sendmsg_nolock().
void kgnilnd_peer_cancel_tx_queue (kgn_peer_t * peer)
void kgnilnd_peer_increase_reconnect_locked (kgn_peer_t * peer)
Definition at line 1247 of file gnilnd.c.
References CDEBUG, cfs_time_seconds(), D_NET, kgn_peer::gnp_nid, kgn_peer::gnp_reconnect_interval, kgn_peer::gnp_reconnect_time, kgn_tunables::kgn_max_reconnect_interval, kgn_tunables::kgn_min_reconnect_interval, kgnilnd_tunables, libcfs_nid2str(), and MIN.
Referenced by kgnilnd_probe_and_process_dgram(), and kgnilnd_start_outbound_dgrams().
void kgnilnd_peer_notify (kgn_peer_t * peer, int error, int alive)
Definition at line 512 of file gnilnd.c.
References CDEBUG, CERROR, cfs_duration_sec(), CFS_FAIL_CHECK, CFS_FAIL_GNI_DONT_NOTIFY, D_NET, D_NETTRACE, GNILND_PEER_IDLE, kgn_net::gnn_ni, kgn_net::gnn_shutdown, kgn_peer::gnp_connecting, kgn_peer::gnp_last_alive, kgn_peer::gnp_nid, kgn_data::kgn_in_reset, kgn_tunables::kgn_net_hash_size, kgn_data::kgn_net_rw_sem, kgn_data::kgn_nets, kgn_data::kgn_peer_conn_lock, kgnilnd_conn_clean_errno(), kgnilnd_find_conn_locked(), kgnilnd_lnd2lnetnid(), kgnilnd_net_addref, kgnilnd_net_decref, kgnilnd_tunables, LIBCFS_ALLOC, LIBCFS_FREE, libcfs_nid2str(), list_for_each_entry, lnet_notify(), and lnet_ni::ni_nid.
Referenced by kgnilnd_bump_timeouts(), kgnilnd_complete_closed_conn(), kgnilnd_probe_and_process_dgram(), kgnilnd_release_purgatory_list(), and kgnilnd_report_node_state().
void kgnilnd_proc_fini (void)
Definition at line 1414 of file gnilnd_proc.c.
References GNILND, GNILND_PROC_CKSUM_TEST, GNILND_PROC_CONN, GNILND_PROC_MDD, GNILND_PROC_PEER, GNILND_PROC_PEER_CONNS, GNILND_PROC_SMSG, GNILND_PROC_STATS, kgn_proc_root, and libcfs_lnd2modname().
Referenced by kgnilnd_exit().
void kgnilnd_proc_init (void)
Definition at line 1325 of file gnilnd_proc.c.
References CERROR, ENTRY, GNILND, GNILND_PROC_CKSUM_TEST, GNILND_PROC_CONN, GNILND_PROC_MDD, GNILND_PROC_PEER, GNILND_PROC_PEER_CONNS, GNILND_PROC_SMSG, GNILND_PROC_STATS, GOTO, kgn_cksum_test_fops, kgn_proc_root, kgn_stats_fops, libcfs_lnd2modname(), and RETURN_EXIT.
Referenced by kgnilnd_init().
void kgnilnd_query (lnet_ni_t * ni, lnet_nid_t nid, cfs_time_t * when)
Definition at line 1925 of file gnilnd.c.
References CDEBUG, CFS_FAIL_CHECK, CFS_FAIL_GNI_NOOP_SEND, D_NETTRACE, ENTRY, EXIT, GNILND_MSG_NOOP, kgn_peer::gnp_last_alive, kgn_peer::gnp_last_errno, GOTO, kgn_data::kgn_peer_conn_lock, kgn_data::kgn_quiesce_trigger, kgnilnd_conn_clean_errno(), kgnilnd_find_conn_locked(), kgnilnd_find_peer_locked(), kgnilnd_launch_tx(), kgnilnd_new_tx_msg(), libcfs_nid2str(), LNET_PID_LUSTRE, lnet_ni::ni_data, and lnet_ni::ni_nid.
void kgnilnd_queue_reply (kgn_conn_t * conn, kgn_tx_t * tx)
void kgnilnd_queue_tx (kgn_conn_t * conn, kgn_tx_t * tx)
Definition at line 1714 of file gnilnd_cb.c.
References CDEBUG, CFS_FAIL_CHECK, CFS_FAIL_GNI_ONLY_NOOP, D_NET, kgn_conn::gnc_list_lock, kgn_conn::gnc_peer, GNILND_MSG_GET_ACK_REV, GNILND_MSG_GET_REQ, GNILND_MSG_IMMEDIATE, GNILND_MSG_NOOP, GNILND_MSG_PUT_ACK, GNILND_MSG_PUT_REQ_REV, GNILND_TX_FMAQ, kgn_peer::gnp_nid, kgnilnd_msgtype2str(), kgnilnd_queue_rdma(), kgnilnd_schedule_conn, kgnilnd_sendmsg_trylock(), kgnilnd_set_tx_id(), kgnilnd_tx_add_state_locked(), kgnilnd_tx_done(), libcfs_nid2str(), kgn_tx::tx_buffer, kgn_tx::tx_id, kgn_tx::tx_msg, kgn_tx::tx_nob, kgn_tx::tx_qtime, and kgn_tx_ev_id::txe_idx.
Referenced by kgnilnd_check_conn_timeouts_locked(), kgnilnd_check_rdma_cq(), kgnilnd_finish_connect(), kgnilnd_launch_tx(), kgnilnd_nak_rdma(), and kgnilnd_rdma().
void kgnilnd_quiesce_end_callback (gni_nic_handle_t nic_handle, uint64_t msecs)
Definition at line 530 of file gnilnd_stack.c.
References CDEBUG, D_NET, kgn_data::kgn_bump_info_rdy, kgn_data::kgn_devices, kgn_data::kgn_quiesce_secs, kgn_data::kgn_ruhroh_shutdown, kgnilnd_data, kgnilnd_pause_threads(), LASSERTF, and LPD64.
Referenced by kgnilnd_dev_init().
void kgnilnd_quiesce_wait (char * reason)
Definition at line 100 of file gnilnd_stack.c.
References CDEBUG, cfs_duration_sec(), CFS_FAIL_GNI_QUIESCE_RACE, CFS_RACE, cfs_time_seconds(), D_INFO, kgn_device::gnd_dgping_waitq, kgn_device::gnd_dgram_waitq, kgn_device::gnd_waitq, GNILND_IS_QUIESCED, kgn_data::kgn_devices, kgn_data::kgn_ndevs, kgn_data::kgn_nquiesce, kgn_data::kgn_nthreads, kgn_data::kgn_quiesce_trigger, kgn_data::kgn_reaper_lock, kgn_data::kgn_reaper_waitq, kgn_tunables::kgn_timeout, kgnilnd_data, kgnilnd_schedule_dgram(), kgnilnd_tunables, kgnilnd_wakeup_rca_thread(), LASSERTF, and LCONSOLE_INFO.
Referenced by kgnilnd_reset_stack(), kgnilnd_ruhroh_thread(), and kgnilnd_shutdown().
int kgnilnd_rca (void * arg)
int kgnilnd_reaper (void * arg)
Definition at line 3033 of file gnilnd_cb.c.
References CDEBUG, cfs_block_allsigs(), cfs_duration_sec(), cfs_time_seconds(), D_INFO, D_NET, GNILND_REAPER_NCHECKS, GNILND_REAPER_THREAD_WAKE, kgn_data::kgn_new_min_timeout, kgn_tunables::kgn_nice, kgn_tunables::kgn_peer_hash_size, kgn_data::kgn_quiesce_trigger, kgn_data::kgn_reaper_lock, kgn_data::kgn_reaper_waitq, kgn_data::kgn_shutdown, kgnilnd_data, kgnilnd_reaper_check(), kgnilnd_reaper_poke_with_stick(), KGNILND_SPIN_QUIESCE, kgnilnd_thread_fini(), kgnilnd_tunables, timeout, and unlikely.
Referenced by kgnilnd_base_startup().
int kgnilnd_recv (lnet_ni_t * ni, void * private, lnet_msg_t * lntmsg, int delayed, unsigned int niov, struct kvec * iov, lnet_kiov_t * kiov, unsigned int offset, unsigned int mlen, unsigned int rlen)
Definition at line 2433 of file gnilnd_cb.c.
References __u64, D_BUFFS, D_ERROR, D_NET, D_NETERROR, D_WARNING, ENTRY, kgn_conn::gnc_device, kgn_conn::gnc_error, kgn_conn::gnc_peer, kgn_conn::gnc_state, kgn_device::gnd_lock, GNIDBG_MSG, GNILND_CONN_ESTABLISHED, GNILND_MSG_GET_ACK_REV, GNILND_MSG_GET_REQ, GNILND_MSG_GET_REQ_REV, GNILND_MSG_IMMEDIATE, GNILND_MSG_PUT_ACK, GNILND_MSG_PUT_REQ, GNILND_MSG_PUT_REQ_REV, GNILND_TX_MAPQ, kgn_peer::gnp_nid, GOTO, kgn_rx::grx_conn, kgn_rx::grx_eager, kgn_rx::grx_msg, kgn_tunables::kgn_checksum, kgn_tunables::kgn_checksum_dump, kgn_tunables::kgn_max_immediate, kgn_data::kgn_peer_conn_lock, kgnilnd_cksum(), kgnilnd_close_conn(), kgnilnd_consume_rx(), kgnilnd_data, kgnilnd_dump_blob(), kgnilnd_nak_rdma(), kgnilnd_new_tx_msg(), kgnilnd_schedule_device(), kgnilnd_set_tx_id(), kgnilnd_setup_rdma(), kgnilnd_setup_rdma_buffer(), kgnilnd_tunables, kgnilnd_tx_add_state_locked(), kgnilnd_tx_done(), LASSERT, LASSERTF, LBUG, libcfs_debug_dumplog(), libcfs_nid2str(), lnet_copy_flat2iov(), lnet_copy_flat2kiov(), lnet_finalize(), lnet_ni::ni_nid, RETURN, kgn_tx::tx_buffer, kgn_tx::tx_conn, kgn_tx::tx_id, kgn_tx::tx_lntmsg, kgn_tx::tx_msg, kgn_tx::tx_qtime, and kgn_tx_ev_id::txe_cookie.
void kgnilnd_release_dgram (kgn_device_t * dev, kgn_dgram_t * dgram, int shutdown)
Definition at line 1348 of file gnilnd_conn.c.
References CDEBUG, D_NET, kgn_conn::gnc_list, kgn_conn::gnc_peer, kgn_conn::gnc_state, kgn_connreq::gncr_dstnid, kgn_device::gnd_dgram_lock, kgn_device::gnd_nwcdgrams, kgn_dgram::gndg_conn, kgn_dgram::gndg_conn_out, kgn_dgram::gndg_list, kgn_dgram::gndg_state, kgn_dgram::gndg_type, GNILND_CONN_CLOSED, GNILND_CONNREQ_REQ, GNILND_DGRAM_CANCELED, GNILND_DGRAM_DONE, GNILND_DGRAM_WC_REQ, kgn_peer::gnp_conns, kgn_peer::gnp_dirty_eps, kgn_data::kgn_in_reset, kgn_data::kgn_peer_conn_lock, kgn_data::kgn_wc_kill, kgnilnd_add_purgatory_locked(), kgnilnd_admin_addref, kgnilnd_cancel_dgram_locked(), kgnilnd_cleanup_dgram(), kgnilnd_conn_addref, kgnilnd_data, kgnilnd_find_peer_locked(), kgnilnd_free_dgram(), kgnilnd_peer_addref, kgnilnd_post_dgram(), kgnilnd_schedule_conn, LASSERTF, libcfs_nid2str(), list_add_tail(), list_empty(), LNET_NID_ANY, and unlikely.
Referenced by kgnilnd_cancel_wc_dgrams(), kgnilnd_probe_and_process_dgram(), kgnilnd_probe_for_dgram(), and kgnilnd_wait_for_canceled_dgrams().
void kgnilnd_release_mbox (kgn_conn_t * conn, int purgatory_hold)
Definition at line 468 of file gnilnd_conn.c.
References CDEBUG, CERROR, CFS_FAIL_CHECK, CFS_FAIL_GNI_FMABLK_AVAIL, D_NET, kgn_conn::gnc_device, kgn_conn::gnc_ephandle, kgn_conn::gnc_fma_blk, kgn_conn::gnc_mbox_id, kgn_conn::gnc_timeout, kgn_device::gnd_fma_buffs, kgn_device::gnd_fmablk_lock, GNILND_FMABLK_PHYS, GNILND_FMABLK_VIRT, kgn_fma_memblock::gnm_avail_mboxs, kgn_fma_memblock::gnm_bit_array, kgn_fma_memblock::gnm_held_mboxs, kgn_fma_memblock::gnm_hndl, kgn_fma_memblock::gnm_hold_timeout, kgn_fma_memblock::gnm_max_timeout, kgn_fma_memblock::gnm_mbox_info, kgn_fma_memblock::gnm_num_mboxs, kgn_fma_memblock::gnm_state, kgn_conn::gnpr_smsg_attr, kgnilnd_free_fmablk_locked(), kgnilnd_unmap_fmablk(), LASSERTF, list_for_each_entry, LPX64, MAX, kgn_mbox_info::mbx_nallocs, kgn_mbox_info::mbx_release_from_purgatory, gni_smsg_attr::msg_buffer, gni_mem_handle::qword1, and gni_mem_handle::qword2.
Referenced by kgnilnd_add_purgatory_locked(), kgnilnd_destroy_conn(), and kgnilnd_release_purgatory_list().
void kgnilnd_release_purgatory_list (struct list_head * conn_list)
Definition at line 1195 of file gnilnd.c.
References CDEBUG, D_NET, kgn_mdd_purgatory::gmp_list, kgn_mdd_purgatory::gmp_map_key, kgn_conn::gnc_device, kgn_conn::gnc_error, kgn_conn::gnc_in_purgatory, kgn_conn::gnc_list, kgn_conn::gnc_mdd_list, kgn_conn::gnc_needs_detach, kgn_conn::gnc_peer, kgn_device::gnd_handle, kgn_device::gnd_n_mdd_held, kgn_data::kgn_npending_detach, kgnilnd_admin_decref, kgnilnd_conn_decref, kgnilnd_mem_mdd_release(), kgnilnd_peer_notify(), kgnilnd_release_mbox(), LIBCFS_FREE, list_del_init(), list_for_each_entry_safe, LPX64, gni_mem_handle::qword1, and gni_mem_handle::qword2.
Referenced by kgnilnd_reaper_check(), and kgnilnd_reset_stack().
void kgnilnd_remove_sysctl (void)
Definition at line 315 of file gnilnd_sysctl.c.
Referenced by kgnilnd_exit().
int kgnilnd_report_node_state (lnet_nid_t nid, int down)
Definition at line 1710 of file gnilnd.c.
References CNETERR, GNILND_RCA_NODE_DOWN, GNILND_RCA_NODE_UP, kgn_net::gnn_ni, kgn_peer::gnp_down, kgn_peer::gnp_down_event_time, kgn_peer::gnp_up_event_time, kgn_tunables::kgn_net_hash_size, kgn_data::kgn_net_rw_sem, kgn_data::kgn_nets, kgn_data::kgn_peer_conn_lock, kgnilnd_add_peer(), kgnilnd_cancel_peer_connect_locked(), kgnilnd_close_conn_locked(), kgnilnd_find_conn_locked(), kgnilnd_find_peer_locked(), kgnilnd_peer_notify(), kgnilnd_tunables, kgnilnd_txlist_done(), LCONSOLE_INFO, list_for_each_entry, LIST_HEAD(), LNET_MKNID(), LNET_NIDADDR(), LNET_NIDNET(), and lnet_ni::ni_nid.
void kgnilnd_reset_stack (void)
Definition at line 172 of file gnilnd_stack.c.
References CDEBUG, CERROR, cfs_duration_sec(), CFS_FAIL_GNI_DROP_CLOSING, CFS_FAIL_GNI_DROP_DESTROY_EP, CFS_FAIL_GNI_RACE_RESET, CFS_FAIL_GNI_SR_DOWN_RACE, CFS_FAIL_GNI_WC_DGRAM_FREE, CFS_RACE, D_NET, end, ENTRY, kgn_conn::gnc_close_sent, kgn_conn::gnc_schedlist, kgn_conn::gnc_scheduled, kgn_conn::gnc_state, kgn_device::gnd_neps, kgn_device::gnd_nfmablk, kgn_device::gnd_ready_conns, GNILND_CONN_CLOSED, GNILND_CONN_CLOSING, GNILND_CONN_DESTROY_EP, GNILND_CONN_IDLE, GNILND_CONN_PROCESS, GNILND_DEL_CONN, GNILND_INIT_ALL, GNILND_QUIESCE_IDLE, GNILND_QUIESCE_RESET, kgn_peer::gnp_conns, kgn_data::kgn_devices, kgn_data::kgn_in_reset, kgn_data::kgn_init, kgn_data::kgn_nconns, kgn_data::kgn_ndevs, kgn_tunables::kgn_net_hash_size, kgn_data::kgn_nets, kgn_data::kgn_nresets, kgn_tunables::kgn_peer_hash_size, kgn_data::kgn_peers, kgn_data::kgn_quiesce_trigger, kgnilnd_bump_timeouts(), kgnilnd_cancel_net_dgrams(), kgnilnd_cancel_wc_dgrams(), kgnilnd_complete_closed_conn(), kgnilnd_conn_decref, kgnilnd_count_list(), kgnilnd_data, kgnilnd_del_conn_or_peer(), kgnilnd_destroy_conn_ep(), kgnilnd_detach_purgatory_locked(), kgnilnd_dev_fini(), kgnilnd_dev_init(), kgnilnd_map_phys_fmablk(), kgnilnd_quiesce_wait(), kgnilnd_release_purgatory_list(), kgnilnd_schedule_process_conn(), kgnilnd_setup_wildcard_dgram(), kgnilnd_tunables, kgnilnd_unmap_fma_blocks(), kgnilnd_wait_for_canceled_dgrams(), LASSERTF, LCONSOLE_WARN, list_del_init(), list_empty(), list_for_each_entry, list_for_each_entry_safe, LIST_HEAD(), LNET_NID_ANY, RETURN_EXIT, seconds, and start.
Referenced by kgnilnd_ruhroh_thread().
int kgnilnd_ruhroh_thread (void * arg)
Definition at line 367 of file gnilnd_stack.c.
References CDEBUG, cfs_block_allsigs(), cfs_time_seconds(), D_INFO, D_NET, GNILND_QUIESCE_HW_QUIESCE, GNILND_QUIESCE_IDLE, kgn_data::kgn_bump_info_rdy, kgn_data::kgn_needs_pause, kgn_data::kgn_needs_reset, kgn_tunables::kgn_nice, kgn_data::kgn_quiesce_mutex, kgn_data::kgn_quiesce_secs, kgn_data::kgn_quiesce_trigger, kgn_data::kgn_ruhroh_running, kgn_data::kgn_ruhroh_shutdown, kgn_data::kgn_ruhroh_waitq, kgnilnd_bump_timeouts(), kgnilnd_data, kgnilnd_hw_in_quiesce(), kgnilnd_quiesce_wait(), kgnilnd_reset_stack(), and kgnilnd_tunables.
Referenced by kgnilnd_base_startup().
void kgnilnd_schedule_device (kgn_device_t * dev)
Definition at line 73 of file gnilnd_cb.c.
References kgn_device::gnd_ready, kgn_device::gnd_waitq, GNILND_DEV_IDLE, and GNILND_DEV_IRQ.
Referenced by _kgnilnd_schedule_conn(), kgnilnd_base_shutdown(), kgnilnd_device_callback(), kgnilnd_finish_connect(), kgnilnd_queue_rdma(), kgnilnd_rdma(), kgnilnd_recv(), kgnilnd_schedule_device_timer(), kgnilnd_send_mapped_tx(), and kgnilnd_setup_rdma().
void kgnilnd_schedule_device_timer (unsigned long arg)
Definition at line 87 of file gnilnd_cb.c.
References kgnilnd_schedule_device().
Referenced by kgnilnd_base_startup().
void kgnilnd_schedule_dgram (kgn_device_t * dev)
Definition at line 205 of file gnilnd_cb.c.
References CDEBUG, D_NETTRACE, kgn_device::gnd_dgram_ready, kgn_device::gnd_dgram_waitq, and GNILND_DGRAM_SCHED.
Referenced by kgnilnd_check_peer_timeouts_locked(), kgnilnd_dgram_waitq(), kgnilnd_find_or_create_conn_locked(), and kgnilnd_quiesce_wait().
int kgnilnd_schedule_process_conn (kgn_conn_t * conn, int sched_intent)
Definition at line 127 of file gnilnd_cb.c.
References kgn_conn::gnc_scheduled, GNILND_CONN_IDLE, GNILND_CONN_PROCESS, GNILND_CONN_WANTS_SCHED, kgnilnd_schedule_conn_refheld, and LASSERTF.
Referenced by kgnilnd_process_conns(), and kgnilnd_reset_stack().
int kgnilnd_scheduler (void * arg)
Definition at line 4988 of file gnilnd_cb.c.
References CDEBUG, cfs_block_allsigs(), CFS_FAIL_GNI_SCHED_DEADLINE, CFS_FAIL_TIMEOUT, cfs_time_seconds(), D_INFO, kgn_device::gnd_conn_sem, kgn_device::gnd_n_schedule, kgn_device::gnd_n_yield, kgn_device::gnd_ready, kgn_device::gnd_sched_alive, kgn_device::gnd_waitq, GNILND_DEV_IDLE, GNILND_DEV_IRQ, GNILND_DEV_LOOP, kgn_data::kgn_devices, kgn_data::kgn_last_condresched, kgn_data::kgn_last_scheduled, kgn_tunables::kgn_loops, kgn_data::kgn_ndevs, kgn_data::kgn_quiesce_trigger, kgn_tunables::kgn_sched_nice, kgn_tunables::kgn_sched_timeout, kgn_data::kgn_shutdown, kgnilnd_check_fma_rcv_cq(), kgnilnd_check_fma_send_cq(), kgnilnd_check_rdma_cq(), kgnilnd_data, kgnilnd_hw_hb, kgnilnd_process_conns(), kgnilnd_process_mapped_tx(), kgnilnd_process_rdmaq(), KGNILND_SPIN_QUIESCE, kgnilnd_thread_fini(), kgnilnd_tunables, and unlikely.
Referenced by kgnilnd_base_startup(), and kgnilnd_start_sd_threads().
int kgnilnd_send (lnet_ni_t * ni, void * private, lnet_msg_t * lntmsg)
Definition at line 2109 of file gnilnd_cb.c.
References CDEBUG, CERROR, cfs_memory_pressure_get_and_set(), cfs_memory_pressure_restore(), D_NET, GNILND_MSG_GET_REQ, GNILND_MSG_GET_REQ_REV, GNILND_MSG_IMMEDIATE, GNILND_MSG_PUT_REQ, GNILND_MSG_PUT_REQ_REV, GNILND_REVERSE_GET, GNILND_REVERSE_PUT, lnet_libmd::iov, kgn_tunables::kgn_max_immediate, kgn_tunables::kgn_reverse_rdma, kgnilnd_launch_tx(), kgnilnd_new_tx_msg(), kgnilnd_setup_immediate_buffer(), kgnilnd_setup_rdma_buffer(), kgnilnd_tunables, kgnilnd_tx_done(), lnet_libmd::kiov, LASSERT, LASSERTF, LBUG, libcfs_id2str(), libcfs_nid2str(), lnet_create_reply_msg(), LNET_MAX_IOV, LNET_MD_KIOV, LNET_MSG_ACK, LNET_MSG_GET, LNET_MSG_PUT, LNET_MSG_REPLY, lnet_libmd::md_iov, lnet_libmd::md_length, lnet_libmd::md_niov, lnet_libmd::md_options, lnet_msg::msg_hdr, lnet_msg::msg_iov, lnet_msg::msg_kiov, lnet_msg::msg_len, lnet_msg::msg_md, lnet_msg::msg_niov, lnet_msg::msg_offset, lnet_msg::msg_routing, lnet_msg::msg_target, lnet_msg::msg_target_is_router, lnet_msg::msg_type, lnet_msg::msg_vmflush, lnet_ni::ni_data, lnet_ni::ni_nid, lnet_process_id_t::nid, kgn_tx::tx_lntmsg, and kgn_tx::tx_msg.
int kgnilnd_send_mapped_tx (kgn_tx_t * tx, int try_map_if_full)
Definition at line 3596 of file gnilnd_cb.c.
References __u64, CFS_FAIL_CHECK, CFS_FAIL_GNI_GET_REQ_AGAIN, CFS_FAIL_GNI_PUT_ACK_AGAIN, D_NET, kgn_conn::gnc_device, kgn_conn::gnc_list_lock, kgn_device::gnd_lock, kgn_device::gnd_nq_map, GNIDBG_TX, GNILND_MSG_GET_ACK_REV, GNILND_MSG_GET_DONE, GNILND_MSG_GET_DONE_REV, GNILND_MSG_GET_REQ, GNILND_MSG_GET_REQ_REV, GNILND_MSG_PUT_ACK, GNILND_MSG_PUT_DONE, GNILND_MSG_PUT_DONE_REV, GNILND_MSG_PUT_REQ, GNILND_MSG_PUT_REQ_REV, GNILND_TX_FAIL_SMSG, GNILND_TX_FMAQ, GNILND_TX_MAPQ, GNILND_TX_WAITING_COMPLETION, GNILND_TX_WAITING_REPLY, kgnilnd_compute_rdma_cksum(), kgnilnd_map_buffer(), kgnilnd_rdma(), kgnilnd_schedule_device(), kgnilnd_sendmsg(), kgnilnd_tx_add_state_locked(), LBUG, lnet_msg::msg_len, RETURN, kgn_tx::tx_buffer, kgn_tx::tx_conn, kgn_tx::tx_getinfo, kgn_tx::tx_id, kgn_tx::tx_lntmsg, kgn_tx::tx_map_key, kgn_tx::tx_msg, kgn_tx::tx_nob, kgn_tx::tx_putinfo, kgn_tx::tx_state, kgn_tx_ev_id::txe_cookie, and unlikely.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_check_fma_send_cq(), kgnilnd_process_mapped_tx(), and kgnilnd_process_rdmaq().
int kgnilnd_set_conn_params (kgn_dgram_t * dgram)
Definition at line 869 of file gnilnd.c.
References CDEBUG, CERROR, D_NET, kgn_conn::gnc_cqid, kgn_conn::gnc_device, kgn_conn::gnc_ephandle, kgn_conn::gnc_peer_connstamp, kgn_conn::gnc_peerstamp, kgn_conn::gnc_timeout, kgn_connreq::gncr_connstamp, kgn_connreq::gncr_dstnid, kgn_connreq::gncr_gnparams, kgn_connreq::gncr_peerstamp, kgn_connreq::gncr_srcnid, kgn_connreq::gncr_timeout, kgn_device::gnd_cq_mutex, kgn_dgram::gndg_conn, kgn_dgram::gndg_conn_in, kgn_dgram::gndg_conn_out, GNI_RC_INVALID_PARAM, GNI_RC_SUCCESS, GNILND_TO2KA, kgn_gniparams::gnpr_cqid, kgn_gniparams::gnpr_host_id, kgn_conn::gnpr_smsg_attr, kgn_gniparams::gnpr_smsg_attr, kgnilnd_ep_bind(), kgnilnd_ep_set_eventdata(), kgnilnd_ep_unbind(), kgnilnd_smsg_init(), kgnilnd_update_reaper_timeout(), LASSERTF, LCONSOLE_ERROR, libcfs_nid2str(), LNET_NID_ANY, LPX64, MAX, gni_smsg_attr::mbox_maxcredit, gni_smsg_attr::mbox_offset, gni_smsg_attr::mem_hndl, gni_smsg_attr::msg_buffer, gni_smsg_attr::msg_maxsize, gni_smsg_attr::msg_type, gni_mem_handle::qword1, gni_mem_handle::qword2, kgn_conn::remote_mbox_addr, and unlikely.
Referenced by kgnilnd_unpack_connreq().
int kgnilnd_setup_wildcard_dgram (kgn_device_t * dev)
Definition at line 1526 of file gnilnd_conn.c.
References CERROR, ENTRY, GNILND_CONNREQ_REQ, GOTO, kgn_tunables::kgn_nwildcard, kgnilnd_post_dgram(), kgnilnd_tunables, LNET_NID_ANY, and RETURN.
Referenced by kgnilnd_base_startup(), and kgnilnd_reset_stack().
void kgnilnd_shutdown (lnet_ni_t * ni)
Definition at line 2780 of file gnilnd.c.
References CDEBUG, CERROR, CFS_FAIL_GNI_SR_DOWN_RACE, CFS_RACE, cfs_time_seconds(), D_MALLOC, D_NET, D_WARNING, ENTRY, EXIT, GNILND_DEL_PEER, GNILND_INIT_ALL, GNILND_IS_QUIESCED, GNILND_QUIESCE_IDLE, kgn_net::gnn_dev, kgn_net::gnn_list, kgn_net::gnn_netnum, kgn_net::gnn_ni, kgn_net::gnn_refcount, kgn_net::gnn_shutdown, GOTO, kgn_data::kgn_init, kgn_tunables::kgn_net_hash_size, kgn_data::kgn_net_rw_sem, kgn_data::kgn_nets, kgn_data::kgn_quiesce_mutex, kgn_data::kgn_quiesce_trigger, kgnilnd_base_shutdown(), kgnilnd_cancel_net_dgrams(), kgnilnd_del_conn_or_peer(), kgnilnd_net_decref, kgnilnd_quiesce_wait(), kgnilnd_tunables, kgnilnd_wait_for_canceled_dgrams(), LASSERT, LASSERTF, LIBCFS_FREE, libcfs_kmemory, list_del_init(), list_empty(), LNET_NID_ANY, and lnet_ni::ni_data.
Referenced by kgnilnd_startup().
int kgnilnd_start_rca_thread (void)
Definition at line 800 of file gnilnd_stack.c.
Referenced by kgnilnd_base_startup().
int kgnilnd_startup (lnet_ni_t * ni)
Definition at line 2687 of file gnilnd.c.
References CDEBUG, CERROR, D_NET, ENTRY, kgn_device::gnd_id, kgn_device::gnd_nid, GNILND_INIT_NOTHING, GNILND_MAXDEVS, GNILND_REAPER_NCHECKS, GNILND_TO2KA, kgn_net::gnn_dev, kgn_net::gnn_list, kgn_net::gnn_netnum, kgn_net::gnn_ni, kgn_net::gnn_refcount, GOTO, INIT_LIST_HEAD, kgn_tunables::kgn_credits, kgn_data::kgn_devices, kgn_data::kgn_init, kgn_data::kgn_net_rw_sem, kgn_tunables::kgn_peer_credits, kgn_tunables::kgn_peer_health, kgn_tunables::kgn_peer_timeout, kgn_data::kgn_quiesce_mutex, kgn_tunables::kgn_timeout, kgnilnd_base_startup(), kgnilnd_netnum2netlist(), kgnilnd_shutdown(), kgnilnd_tunables, LASSERTF, LCONSOLE_ERROR, LCONSOLE_INFO, LIBCFS_ALLOC, LIBCFS_FREE, libcfs_nid2str(), list_add_tail(), LNET_MKNID(), LNET_NETNUM(), LNET_NIDNET(), lnet_ni::ni_data, lnet_ni::ni_lnd, lnet_ni::ni_maxtxcredits, lnet_ni::ni_nid, lnet_ni::ni_peertimeout, lnet_ni::ni_peertxcredits, RETURN, and timeout.
static void kgnilnd_thread_fini (void) [inline, static]
Definition at line 896 of file gnilnd.h.
References kgn_data::kgn_nthreads.
Referenced by kgnilnd_dgram_mover(), kgnilnd_dgram_waitq(), kgnilnd_reaper(), and kgnilnd_scheduler().
int kgnilnd_thread_start (int(*)(void *arg) fn, void * arg, char * name, int id)
Definition at line 46 of file gnilnd.c.
References kgn_data::kgn_nthreads.
Referenced by kgnilnd_base_startup().
static int kgnilnd_trylock (struct mutex * cq_lock, struct mutex * c_lock) [inline, static]
Definition at line 962 of file gnilnd.h.
References __kgnilnd_mutex_trylock(), and kgn_data::kgn_enable_gl_mutex.
Referenced by kgnilnd_sendmsg_trylock().
static struct timespec kgnilnd_ts_sub (struct timespec lhs, struct timespec rhs) [static, read]
Definition at line 1652 of file gnilnd.h.
References NSEC_PER_SEC.
Referenced by _kgnilnd_proc_run_cksum_test().
int kgnilnd_tunables_init (void)
Definition at line 250 of file gnilnd_modparams.c.
References CERROR, GNILND_CHECKSUM_OFF, GNILND_CHECKSUM_SMSG, GNILND_CHECKSUM_SMSG_BTE, GNILND_CHECKSUM_SMSG_HEADER, GNILND_MAX_IMMEDIATE, GOTO, kgn_tunables::kgn_checksum, kgn_tunables::kgn_concurrent_sends, kgn_tunables::kgn_max_immediate, kgn_tunables::kgn_mbox_per_block, kgn_tunables::kgn_peer_credits, LCONSOLE_ERROR, and LCONSOLE_INFO.
Referenced by kgnilnd_init().
static void kgnilnd_tx_add_state_locked (kgn_tx_t * tx, kgn_peer_t * peer, kgn_conn_t * conn, kgn_tx_list_state_t state, int add_tail) [inline, static]
Definition at line 1389 of file gnilnd.h.
References CERROR, D_NET, kgn_conn::gnc_device, kgn_conn::gnc_nlive_fma, kgn_conn::gnc_nlive_rdma, kgn_conn::gnc_nq_rdma, kgn_device::gnd_nq_map, GNIDBG_TX, GNILND_TX_ALLOCD, GNILND_TX_DYING, GNILND_TX_FMAQ, GNILND_TX_LIVE_FMAQ, GNILND_TX_LIVE_RDMAQ, GNILND_TX_MAPQ, GNILND_TX_PEERQ, GNILND_TX_RDMAQ, GNITX_ASSERTF, kgnilnd_conn_addref, kgnilnd_peer_addref, kgnilnd_tx_state2list(), kgnilnd_tx_state2str(), LBUG, list, list_add(), list_add_tail(), list_empty(), kgn_tx::tx_list, kgn_tx::tx_list_p, and kgn_tx::tx_list_state.
Referenced by kgnilnd_launch_tx(), kgnilnd_process_mapped_tx(), kgnilnd_process_rdmaq(), kgnilnd_queue_rdma(), kgnilnd_queue_tx(), kgnilnd_rdma(), kgnilnd_recv(), kgnilnd_send_mapped_tx(), kgnilnd_sendmsg_nolock(), and kgnilnd_setup_rdma().
static void kgnilnd_tx_del_state_locked (kgn_tx_t * tx, kgn_peer_t * peer, kgn_conn_t * conn, kgn_tx_list_state_t new_state) [inline, static]
Definition at line 1468 of file gnilnd.h.
References D_NET, kgn_conn::gnc_device, kgn_conn::gnc_nlive_fma, kgn_conn::gnc_nlive_rdma, kgn_conn::gnc_nq_rdma, kgn_device::gnd_nq_map, GNIDBG_TX, GNILND_TX_ALLOCD, GNILND_TX_DYING, GNILND_TX_FMAQ, GNILND_TX_FREED, GNILND_TX_IDLE, GNILND_TX_LIVE_FMAQ, GNILND_TX_LIVE_RDMAQ, GNILND_TX_MAPQ, GNILND_TX_PEERQ, GNILND_TX_RDMAQ, GNITX_ASSERTF, kgnilnd_conn_decref, kgnilnd_peer_decref, kgnilnd_tx_state2str(), list_del_init(), list_empty(), kgn_tx::tx_list, kgn_tx::tx_list_p, and kgn_tx::tx_list_state.
Referenced by kgnilnd_cancel_peer_connect_locked(), kgnilnd_check_fma_rx(), kgnilnd_check_fma_send_cq(), kgnilnd_check_peer_timeouts_locked(), kgnilnd_check_rdma_cq(), kgnilnd_complete_closed_conn(), kgnilnd_complete_tx(), kgnilnd_finish_connect(), kgnilnd_process_fmaq(), kgnilnd_process_mapped_tx(), and kgnilnd_process_rdmaq().
void kgnilnd_tx_done (kgn_tx_t * tx, int completion)
Definition at line 1199 of file gnilnd_cb.c.
References cfs_duration_sec(), D_NETERROR, kgn_conn::gnc_peer, kgn_conn::gnc_tx_bits, kgn_conn::gnc_tx_lock, kgn_conn::gnc_tx_ref_table, GNIDBG_TOMSG, GNILND_BUF_NONE, GNILND_MSG_GET_REQ, GNILND_MSG_NONE, GNILND_TX_QUIET_ERROR, kgn_net::gnn_ni, kgn_peer::gnp_net, kgn_peer::gnp_nid, kgnilnd_conn_clean_errno(), kgnilnd_free_tx(), kgnilnd_tx_state2str(), kgnilnd_unmap_buffer(), LASSERT, LASSERTF, libcfs_nid2str(), lnet_finalize(), kgn_tx::tx_buftype, kgn_tx::tx_conn, kgn_tx::tx_id, kgn_tx::tx_list_state, kgn_tx::tx_lntmsg, kgn_tx::tx_msg, kgn_tx::tx_qtime, kgn_tx::tx_state, kgn_tx_ev_id::txe_idx, and kgn_tx_ev_id::txe_smsg_id.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_check_fma_send_cq(), kgnilnd_check_rdma_cq(), kgnilnd_complete_closed_conn(), kgnilnd_complete_tx(), kgnilnd_launch_tx(), kgnilnd_process_fmaq(), kgnilnd_process_mapped_tx(), kgnilnd_queue_tx(), kgnilnd_rdma(), kgnilnd_recv(), kgnilnd_send(), kgnilnd_send_conn_close(), kgnilnd_setup_rdma(), and kgnilnd_txlist_done().
static int kgnilnd_tx_mapped (kgn_tx_t * tx) [inline, static]
Definition at line 1526 of file gnilnd.h.
References GNILND_BUF_PHYS_MAPPED, GNILND_BUF_VIRT_MAPPED, and kgn_tx::tx_buftype.
Referenced by kgnilnd_rdma().
static struct list_head* kgnilnd_tx_state2list (kgn_peer_t * peer, kgn_conn_t * conn, kgn_tx_list_state_t to_state) [static, read]
Definition at line 1362 of file gnilnd.h.
References CERROR, kgn_conn::gnc_device, kgn_conn::gnc_fmaq, kgn_device::gnd_map_tx, kgn_device::gnd_rdmaq, GNILND_TX_DYING, GNILND_TX_FMAQ, GNILND_TX_LIVE_FMAQ, GNILND_TX_LIVE_RDMAQ, GNILND_TX_MAPQ, GNILND_TX_PEERQ, GNILND_TX_RDMAQ, kgn_peer::gnp_tx_queue, kgnilnd_tx_state2str(), and LBUG.
Referenced by kgnilnd_tx_add_state_locked().
static const char * kgnilnd_tx_state2str (kgn_tx_list_state_t state) [inline, static]
Definition at line 1894 of file gnilnd.h.
References DO_TYPE, GNILND_TX_ALLOCD, GNILND_TX_DYING, GNILND_TX_FMAQ, GNILND_TX_FREED, GNILND_TX_IDLE, GNILND_TX_LIVE_FMAQ, GNILND_TX_LIVE_RDMAQ, GNILND_TX_MAPQ, GNILND_TX_PEERQ, and GNILND_TX_RDMAQ.
Referenced by _kgnilnd_debug_tx(), kgnilnd_complete_tx(), kgnilnd_free_tx(), kgnilnd_tx_add_state_locked(), kgnilnd_tx_del_state_locked(), kgnilnd_tx_done(), and kgnilnd_tx_state2list().
void kgnilnd_txlist_done (struct list_head * txlist, int error)
Definition at line 1276 of file gnilnd_cb.c.
References GNILND_TX_QUIET_ERROR, kgnilnd_tx_done(), list_del_init(), list_empty(), list_for_each_entry_safe, kgn_tx::tx_list, and kgn_tx::tx_state.
Referenced by kgnilnd_del_conn_or_peer(), kgnilnd_reaper_check(), and kgnilnd_report_node_state().
void kgnilnd_unlink_peer_locked (kgn_peer_t * peer)
Definition at line 1298 of file gnilnd.c.
References CDEBUG, D_NET, kgn_peer::gnp_conns, kgn_peer::gnp_list, kgn_peer::gnp_nid, kgn_peer::gnp_tx_queue, kgn_data::kgn_npending_unlink, kgn_data::kgn_peer_version, kgnilnd_admin_decref, kgnilnd_peer_active(), kgnilnd_peer_decref, LASSERTF, libcfs_nid2str(), list_del_init(), and list_empty().
Referenced by kgnilnd_complete_closed_conn(), kgnilnd_del_peer_locked(), and kgnilnd_detach_purgatory_locked().
void kgnilnd_unmap_buffer (kgn_tx_t * tx, int error)
Definition at line 1128 of file gnilnd_cb.c.
References CLASSERT, D_NET, kgn_conn::gnc_device, kgn_conn::gnc_state, kgn_device::gnd_handle, GNI_RC_SUCCESS, GNIDBG_TX, GNILND_BUF_IMMEDIATE, GNILND_BUF_IMMEDIATE_KIOV, GNILND_BUF_NONE, GNILND_BUF_PHYS_MAPPED, GNILND_BUF_PHYS_UNMAPPED, GNILND_BUF_VIRT_MAPPED, GNILND_BUF_VIRT_UNMAPPED, GNILND_CONN_ESTABLISHED, GNILND_NOPURG, GNILND_TIMEOUT2DEADMAN, kgnilnd_add_purgatory_tx(), kgnilnd_check_purgatory_conn(), kgnilnd_mem_del_map_list(), kgnilnd_mem_deregister(), LASSERT, LASSERTF, LBUG, LPX64, gni_mem_handle::qword1, gni_mem_handle::qword2, kgn_tx::tx_buffer, kgn_tx::tx_buffer_copy, kgn_tx::tx_buffer_copy_map_key, kgn_tx::tx_buftype, kgn_tx::tx_conn, kgn_tx::tx_imm_pages, kgn_tx::tx_map_key, and kgn_tx::tx_phys.
Referenced by kgnilnd_rdma(), and kgnilnd_tx_done().
void kgnilnd_unmap_fma_blocks (kgn_device_t * device)
Definition at line 642 of file gnilnd_conn.c.
References kgn_device::gnd_fma_buffs, kgn_device::gnd_fmablk_lock, kgn_device::gnd_fmablk_mutex, kgnilnd_unmap_fmablk(), and list_for_each_entry.
Referenced by kgnilnd_base_shutdown(), and kgnilnd_reset_stack().
void kgnilnd_update_reaper_timeout (long timeout)
Definition at line 3014 of file gnilnd_cb.c.
References kgn_data::kgn_new_min_timeout, kgn_data::kgn_reaper_lock, kgnilnd_data, and LASSERT.
Referenced by kgnilnd_create_conn(), and kgnilnd_set_conn_params().
static void kgnilnd_validate_tx_ev_id (kgn_tx_ev_id_t * ev_id, kgn_tx_t ** txp, kgn_conn_t ** connp) [inline, static]
Definition at line 1579 of file gnilnd.h.
References CDEBUG, CNETERR, D_NET, kgn_conn::gnc_peer, kgn_conn::gnc_tx_in_use, kgn_conn::gnc_tx_lock, kgn_conn::gnc_tx_ref_table, GNIDBG_TX, GNILND_MAX_CQID, GNILND_MAX_MSG_ID, GNILND_MSG_MAGIC, GNITX_ASSERTF, kgn_peer::gnp_nid, kgn_data::kgn_peer_conn_lock, kgnilnd_admin_addref, kgnilnd_admin_decref, kgnilnd_conn_addref, kgnilnd_conn_decref, kgnilnd_cqid2conn_locked(), LASSERTF, libcfs_nid2str(), kgn_tx::tx_conn, kgn_tx::tx_id, kgn_tx::tx_msg, kgn_tx_ev_id::txe_cqid, and kgn_tx_ev_id::txe_idx.
Referenced by kgnilnd_check_fma_send_cq(), and kgnilnd_check_rdma_cq().
static void* kgnilnd_vzalloc (int size) [inline, static]
Definition at line 971 of file gnilnd.h.
References ret.
Referenced by kgnilnd_alloc_fmablk(), and kgnilnd_create_conn().
void kgnilnd_wait_for_canceled_dgrams (kgn_device_t * dev)
Definition at line 1664 of file gnilnd_conn.c.
References __u64, CDEBUG, D_NET, D_WARNING, kgn_device::gnd_canceled_dgrams, kgn_device::gnd_handle, kgn_device::gnd_id, GNI_RC_SUCCESS, kgnilnd_postdata_probe_wait_by_id(), kgnilnd_probe_for_dgram(), kgnilnd_release_dgram(), and LPX64.
Referenced by kgnilnd_base_shutdown(), kgnilnd_reset_stack(), and kgnilnd_shutdown().
void kgnilnd_wakeup_rca_thread (void)
Definition at line 806 of file gnilnd_stack.c.
Referenced by kgnilnd_base_shutdown(), and kgnilnd_quiesce_wait().
Variable Documentation
uint32_t kgni_driver_version
kgn_data_t kgnilnd_data
Definition at line 43 of file gnilnd.c.
kgn_tunables_t kgnilnd_tunables
Definition at line 205 of file gnilnd_modparams.c.
Referenced by kgnilnd_alloc_fmablk(), kgnilnd_allocate_phys_fmablk(), kgnilnd_base_shutdown(), kgnilnd_base_startup(), kgnilnd_bump_timeouts(), kgnilnd_cancel_dgrams(), kgnilnd_cancel_net_dgrams(), kgnilnd_check_fma_rcv_cq(), kgnilnd_check_fma_rx(), kgnilnd_check_peer_timeouts_locked(), kgnilnd_check_rdma_cq(), kgnilnd_cksum_kiov(), kgnilnd_complete_closed_conn(), kgnilnd_complete_tx(), kgnilnd_compute_rdma_cksum(), kgnilnd_conn_seq_seek(), kgnilnd_consume_rx(), kgnilnd_create_conn(), kgnilnd_del_conn_or_peer(), kgnilnd_dev_init(), kgnilnd_dgram_mover(), kgnilnd_dgram_waitq(), kgnilnd_eager_recv(), kgnilnd_get_conn_by_idx(), kgnilnd_get_peer_info(), kgnilnd_map_buffer(), kgnilnd_map_fmablk(), kgnilnd_mem_register(), kgnilnd_nid2dgramlist(), kgnilnd_peer_increase_reconnect_locked(), kgnilnd_peer_notify(), kgnilnd_peer_seq_seek(), kgnilnd_process_rdmaq(), kgnilnd_quiesce_wait(), kgnilnd_rdma(), kgnilnd_reaper(), kgnilnd_reaper_dgram_check(), kgnilnd_recv(), kgnilnd_register_smdd_buf(), kgnilnd_report_node_state(), kgnilnd_reset_stack(), kgnilnd_ruhroh_thread(), kgnilnd_scheduler(), kgnilnd_send(), kgnilnd_sendmsg_nolock(), kgnilnd_setup_immediate_buffer(), kgnilnd_setup_smsg_attr(), kgnilnd_setup_wildcard_dgram(), kgnilnd_shutdown(), kgnilnd_start_sd_threads(), kgnilnd_startup(), kgnilnd_tx_should_retry(), and kgnilnd_verify_rdma_cksum().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.