Lustre: lnet/klnds/gnilnd/gnilnd_proc.c File Reference
lnet/klnds/gnilnd/gnilnd_proc.c File Reference
#include "gnilnd.h"
#include <linux/seq_file.h>
#include <lprocfs_status.h>
Data Structures
struct kgn_mdd_seq_iter_t
struct kgn_smsg_seq_iter_t
struct kgn_conn_seq_iter_t
struct kgn_peer_seq_iter_t
Defines
#define DEBUG_SUBSYSTEM S_LND
#define GNILND_PROC_STATS "stats"
#define GNILND_PROC_MDD "mdd"
#define GNILND_PROC_SMSG "smsg"
#define GNILND_PROC_CONN "conn"
#define GNILND_PROC_PEER_CONNS "peer_conns"
#define GNILND_PROC_PEER "peer"
#define GNILND_PROC_CKSUM_TEST "cksum_test"
#define KGN_DEBUG_PEER_NID_DEFAULT -1
Functions
static int _kgnilnd_proc_run_cksum_test (int caseno, int nloops, int nob)
static ssize_t kgnilnd_proc_cksum_test_write (struct file *file, const char __user *ubuffer, size_t count, loff_t *ppos)
static int kgnilnd_cksum_test_seq_open (struct inode *inode, struct file *file)
static int kgnilnd_stats_seq_show (struct seq_file *sf, void *v)
static ssize_t kgnilnd_proc_stats_write (struct file *file, const char __user *ubuffer, size_t count, loff_t *ppos)
static int kgnilnd_stats_seq_open (struct inode *inode, struct file *file)
int kgnilnd_mdd_seq_seek (kgn_mdd_seq_iter_t *gseq, loff_t off)
static void * kgnilnd_mdd_seq_start (struct seq_file *s, loff_t *pos)
static void kgnilnd_mdd_seq_stop (struct seq_file *s, void *iter)
static void * kgnilnd_mdd_seq_next (struct seq_file *s, void *iter, loff_t *pos)
static int kgnilnd_mdd_seq_show (struct seq_file *s, void *iter)
static int kgnilnd_mdd_seq_open (struct inode *inode, struct file *file)
int kgnilnd_smsg_seq_seek (kgn_smsg_seq_iter_t *gseq, loff_t off)
static void * kgnilnd_smsg_seq_start (struct seq_file *s, loff_t *pos)
static void kgnilnd_smsg_seq_stop (struct seq_file *s, void *iter)
static void * kgnilnd_smsg_seq_next (struct seq_file *s, void *iter, loff_t *pos)
static int kgnilnd_smsg_seq_show (struct seq_file *s, void *iter)
static int kgnilnd_smsg_seq_open (struct inode *inode, struct file *file)
int kgnilnd_conn_seq_seek (kgn_conn_seq_iter_t *gseq, loff_t off)
static void * kgnilnd_conn_seq_start (struct seq_file *s, loff_t *pos)
static void kgnilnd_conn_seq_stop (struct seq_file *s, void *iter)
static void * kgnilnd_conn_seq_next (struct seq_file *s, void *iter, loff_t *pos)
static int kgnilnd_conn_seq_show (struct seq_file *s, void *iter)
static ssize_t kgnilnd_proc_peer_conns_write (struct file *file, const char __user *ubuffer, size_t count, loff_t *ppos)
static int kgnilnd_proc_peer_conns_seq_show (struct seq_file *sf, void *v)
static int kgnilnd_peer_conns_seq_open (struct inode *inode, struct file *file)
static int kgnilnd_conn_seq_open (struct inode *inode, struct file *file)
int kgnilnd_peer_seq_seek (kgn_peer_seq_iter_t *gseq, loff_t off)
static void * kgnilnd_peer_seq_start (struct seq_file *s, loff_t *pos)
static void kgnilnd_peer_seq_stop (struct seq_file *s, void *iter)
static void * kgnilnd_peer_seq_next (struct seq_file *s, void *iter, loff_t *pos)
static int kgnilnd_peer_seq_show (struct seq_file *s, void *iter)
static int kgnilnd_peer_seq_open (struct inode *inode, struct file *file)
void kgnilnd_proc_init (void)
void kgnilnd_proc_fini (void)
Variables
static struct file_operations kgn_cksum_test_fops
static struct file_operations kgn_stats_fops
static struct seq_operations kgn_mdd_sops
static struct file_operations kgn_mdd_fops
static struct seq_operations kgn_smsg_sops
static struct file_operations kgn_smsg_fops
static struct seq_operations kgn_conn_sops
static int kgnilnd_debug_peer_nid = KGN_DEBUG_PEER_NID_DEFAULT
static struct file_operations kgn_peer_conns_fops
static struct file_operations kgn_conn_fops
static struct seq_operations kgn_peer_sops
static struct file_operations kgn_peer_fops
static struct proc_dir_entry * kgn_proc_root
Define Documentation
#define DEBUG_SUBSYSTEM S_LND
Definition at line 26 of file gnilnd_proc.c.
#define GNILND_PROC_CKSUM_TEST "cksum_test"
Definition at line 37 of file gnilnd_proc.c.
Referenced by kgnilnd_proc_fini(), and kgnilnd_proc_init().
#define GNILND_PROC_CONN "conn"
Definition at line 34 of file gnilnd_proc.c.
Referenced by kgnilnd_proc_fini(), and kgnilnd_proc_init().
#define GNILND_PROC_MDD "mdd"
Definition at line 32 of file gnilnd_proc.c.
Referenced by kgnilnd_proc_fini(), and kgnilnd_proc_init().
#define GNILND_PROC_PEER "peer"
Definition at line 36 of file gnilnd_proc.c.
Referenced by kgnilnd_proc_fini(), and kgnilnd_proc_init().
#define GNILND_PROC_PEER_CONNS "peer_conns"
Definition at line 35 of file gnilnd_proc.c.
Referenced by kgnilnd_proc_fini(), and kgnilnd_proc_init().
#define GNILND_PROC_SMSG "smsg"
Definition at line 33 of file gnilnd_proc.c.
Referenced by kgnilnd_proc_fini(), and kgnilnd_proc_init().
#define GNILND_PROC_STATS "stats"
Definition at line 31 of file gnilnd_proc.c.
Referenced by kgnilnd_proc_fini(), and kgnilnd_proc_init().
#define KGN_DEBUG_PEER_NID_DEFAULT -1
Definition at line 945 of file gnilnd_proc.c.
Referenced by kgnilnd_proc_peer_conns_seq_show().
Function Documentation
static int _kgnilnd_proc_run_cksum_test (int caseno, int nloops, int nob) [static]
Definition at line 40 of file gnilnd_proc.c.
References __u64, CDEBUG, CERROR, cksum, D_BUFFS, D_NET, GOTO, kgnilnd_cksum_kiov(), kgnilnd_ts_sub(), lnet_kiov_t::kiov_len, lnet_kiov_t::kiov_offset, lnet_kiov_t::kiov_page, LCONSOLE_INFO, LIBCFS_ALLOC, LIBCFS_FREE, lnet_copy_kiov2kiov(), LNET_MAX_IOV, and LPD64.
Referenced by kgnilnd_proc_cksum_test_write().
static int kgnilnd_cksum_test_seq_open (struct inode * inode, struct file * file) [static]
Definition at line 193 of file gnilnd_proc.c.
static void* kgnilnd_conn_seq_next (struct seq_file * s, void * iter, loff_t * pos) [static]
Definition at line 857 of file gnilnd_proc.c.
References kgnilnd_conn_seq_seek(), LIBCFS_FREE, and list_head::next.
static int kgnilnd_conn_seq_open (struct inode * inode, struct file * file) [static]
Definition at line 1077 of file gnilnd_proc.c.
References kgn_conn_sops.
int kgnilnd_conn_seq_seek (kgn_conn_seq_iter_t * gseq, loff_t off)
Definition at line 754 of file gnilnd_proc.c.
References kgn_conn_seq_iter_t::gconn_conn, kgn_conn_seq_iter_t::gconn_hashidx, kgn_conn_seq_iter_t::gconn_list, kgn_conn_seq_iter_t::gconn_off, kgn_conn_seq_iter_t::gconn_version, kgn_data::kgn_conn_version, kgn_data::kgn_conns, kgn_data::kgn_nconns, kgn_data::kgn_peer_conn_lock, kgn_tunables::kgn_peer_hash_size, kgnilnd_data, kgnilnd_tunables, list, list_entry, and list_for_each.
Referenced by kgnilnd_conn_seq_next(), and kgnilnd_conn_seq_start().
static int kgnilnd_conn_seq_show (struct seq_file * s, void * iter) [static]
Definition at line 873 of file gnilnd_proc.c.
References cfs_duration_sec(), kgn_conn_seq_iter_t::gconn_conn, kgn_conn_seq_iter_t::gconn_list, kgn_conn_seq_iter_t::gconn_version, kgn_conn::gnc_fmaq, kgn_conn::gnc_last_noop_cq, kgn_conn::gnc_last_noop_sent, kgn_conn::gnc_last_noop_want, kgn_conn::gnc_last_rx, kgn_conn::gnc_last_rx_cq, kgn_conn::gnc_last_sched_ask, kgn_conn::gnc_last_sched_do, kgn_conn::gnc_last_tx, kgn_conn::gnc_last_tx_cq, kgn_conn::gnc_nlive_fma, kgn_conn::gnc_nlive_rdma, kgn_conn::gnc_peer, kgn_conn::gnc_reaper_noop, kgn_conn::gnc_refcount, kgn_conn::gnc_rx_seq, kgn_conn::gnc_sched_noop, kgn_conn::gnc_timeout, kgn_conn::gnc_tx_retrans, kgn_conn::gnc_tx_seq, kgn_peer::gnp_nid, kgn_data::kgn_conn_version, kgn_data::kgn_peer_conn_lock, kgnilnd_conn_addref, kgnilnd_conn_decref, kgnilnd_conn_state2str(), kgnilnd_count_list(), kgnilnd_data, kgnilnd_peer_addref, kgnilnd_peer_decref, LASSERT, libcfs_nid2str(), and LPD64.
static void* kgnilnd_conn_seq_start (struct seq_file * s, loff_t * pos) [static]
Definition at line 821 of file gnilnd_proc.c.
References CERROR, kgn_conn_seq_iter_t::gconn_list, GNILND_INIT_ALL, kgn_data::kgn_init, kgnilnd_conn_seq_seek(), kgnilnd_data, LIBCFS_ALLOC, and LIBCFS_FREE.
static void kgnilnd_conn_seq_stop (struct seq_file * s, void * iter) [static]
Definition at line 848 of file gnilnd_proc.c.
References LIBCFS_FREE.
static void* kgnilnd_mdd_seq_next (struct seq_file * s, void * iter, loff_t * pos) [static]
Definition at line 452 of file gnilnd_proc.c.
References kgnilnd_mdd_seq_seek(), and list_head::next.
static int kgnilnd_mdd_seq_open (struct inode * inode, struct file * file) [static]
Definition at line 510 of file gnilnd_proc.c.
References kgn_mdd_sops.
int kgnilnd_mdd_seq_seek (kgn_mdd_seq_iter_t * gseq, loff_t off)
Definition at line 358 of file gnilnd_proc.c.
References kgn_mdd_seq_iter_t::gmdd_dev, kgn_mdd_seq_iter_t::gmdd_off, kgn_mdd_seq_iter_t::gmdd_tx, kgn_device::gnd_map_list, list_entry, list_head::next, and kgn_tx::tx_map_list.
Referenced by kgnilnd_mdd_seq_next(), and kgnilnd_mdd_seq_start().
static int kgnilnd_mdd_seq_show (struct seq_file * s, void * iter) [static]
Definition at line 467 of file gnilnd_proc.c.
References __u64, kgn_mdd_seq_iter_t::gmdd_off, kgn_mdd_seq_iter_t::gmdd_tx, LASSERT, LPX64, gni_mem_handle::qword1, gni_mem_handle::qword2, kgn_tx::tx_buftype, kgn_tx::tx_id, kgn_tx::tx_map_key, kgn_tx::tx_nob, kgn_tx::tx_phys_npages, and kgn_tx_ev_id::txe_smsg_id.
static void* kgnilnd_mdd_seq_start (struct seq_file * s, loff_t * pos) [static]
Definition at line 406 of file gnilnd_proc.c.
References CERROR, kgn_mdd_seq_iter_t::gmdd_dev, kgn_mdd_seq_iter_t::gmdd_tx, kgn_device::gnd_map_lock, GNILND_INIT_ALL, kgn_data::kgn_devices, kgn_data::kgn_init, kgnilnd_data, kgnilnd_mdd_seq_seek(), and LIBCFS_ALLOC.
static void kgnilnd_mdd_seq_stop (struct seq_file * s, void * iter) [static]
Definition at line 441 of file gnilnd_proc.c.
References kgn_mdd_seq_iter_t::gmdd_dev, kgn_device::gnd_map_lock, and LIBCFS_FREE.
static int kgnilnd_peer_conns_seq_open (struct inode * inode, struct file * file) [static]
Definition at line 1061 of file gnilnd_proc.c.
References kgnilnd_proc_peer_conns_seq_show().
static void* kgnilnd_peer_seq_next (struct seq_file * s, void * iter, loff_t * pos) [static]
Definition at line 1211 of file gnilnd_proc.c.
References kgnilnd_peer_seq_seek(), LIBCFS_FREE, and list_head::next.
static int kgnilnd_peer_seq_open (struct inode * inode, struct file * file) [static]
Definition at line 1300 of file gnilnd_proc.c.
References kgn_peer_sops.
int kgnilnd_peer_seq_seek (kgn_peer_seq_iter_t * gseq, loff_t off)
Definition at line 1108 of file gnilnd_proc.c.
References kgn_peer_seq_iter_t::gpeer_hashidx, kgn_peer_seq_iter_t::gpeer_list, kgn_peer_seq_iter_t::gpeer_off, kgn_peer_seq_iter_t::gpeer_peer, kgn_peer_seq_iter_t::gpeer_version, kgn_data::kgn_npeers, kgn_data::kgn_peer_conn_lock, kgn_tunables::kgn_peer_hash_size, kgn_data::kgn_peer_version, kgn_data::kgn_peers, kgnilnd_data, kgnilnd_tunables, list, list_entry, and list_for_each.
Referenced by kgnilnd_peer_seq_next(), and kgnilnd_peer_seq_start().
static int kgnilnd_peer_seq_show (struct seq_file * s, void * iter) [static]
Definition at line 1227 of file gnilnd_proc.c.
References kgn_conn::gnc_in_purgatory, GNILND_RCA_NODE_DOWN, kgn_peer::gnp_connecting, kgn_peer::gnp_conns, kgn_peer::gnp_down, kgn_peer::gnp_host_id, kgn_peer::gnp_last_alive, kgn_peer::gnp_last_dgram_errno, kgn_peer::gnp_last_dgram_time, kgn_peer::gnp_last_errno, kgn_peer::gnp_nid, kgn_peer::gnp_reconnect_interval, kgn_peer::gnp_reconnect_time, kgn_peer::gnp_refcount, kgn_peer::gnp_tx_queue, kgn_peer_seq_iter_t::gpeer_list, kgn_peer_seq_iter_t::gpeer_peer, kgn_peer_seq_iter_t::gpeer_version, kgn_data::kgn_peer_conn_lock, kgn_data::kgn_peer_version, kgnilnd_count_list(), kgnilnd_data, kgnilnd_find_conn_locked(), kgnilnd_peer_addref, kgnilnd_peer_decref, LASSERT, libcfs_nid2str(), and list_for_each_entry.
static void* kgnilnd_peer_seq_start (struct seq_file * s, loff_t * pos) [static]
Definition at line 1175 of file gnilnd_proc.c.
References CERROR, GNILND_INIT_ALL, kgn_peer_seq_iter_t::gpeer_list, kgn_data::kgn_init, kgnilnd_data, kgnilnd_peer_seq_seek(), LIBCFS_ALLOC, and LIBCFS_FREE.
static void kgnilnd_peer_seq_stop (struct seq_file * s, void * iter) [static]
Definition at line 1202 of file gnilnd_proc.c.
References LIBCFS_FREE.
static ssize_t kgnilnd_proc_cksum_test_write (struct file * file, const char __user * ubuffer, size_t count, loff_t * ppos) [static]
Definition at line 161 of file gnilnd_proc.c.
References _kgnilnd_proc_run_cksum_test(), CERROR, ENTRY, GNILND_INIT_ALL, kgn_data::kgn_init, kgnilnd_data, and RETURN.
void kgnilnd_proc_fini (void)
Definition at line 1414 of file gnilnd_proc.c.
References GNILND, GNILND_PROC_CKSUM_TEST, GNILND_PROC_CONN, GNILND_PROC_MDD, GNILND_PROC_PEER, GNILND_PROC_PEER_CONNS, GNILND_PROC_SMSG, GNILND_PROC_STATS, kgn_proc_root, and libcfs_lnd2modname().
Referenced by kgnilnd_exit().
void kgnilnd_proc_init (void)
Definition at line 1325 of file gnilnd_proc.c.
References CERROR, ENTRY, GNILND, GNILND_PROC_CKSUM_TEST, GNILND_PROC_CONN, GNILND_PROC_MDD, GNILND_PROC_PEER, GNILND_PROC_PEER_CONNS, GNILND_PROC_SMSG, GNILND_PROC_STATS, GOTO, kgn_cksum_test_fops, kgn_proc_root, kgn_stats_fops, libcfs_lnd2modname(), and RETURN_EXIT.
Referenced by kgnilnd_init().
static int kgnilnd_proc_peer_conns_seq_show (struct seq_file * sf, void * v) [static]
Definition at line 992 of file gnilnd_proc.c.
References kgn_conn::gnc_close_recvd, kgn_conn::gnc_close_sent, kgn_conn::gnc_dgram_type, kgn_conn::gnc_error, kgn_conn::gnc_first_rx, kgn_conn::gnc_in_purgatory, kgn_conn::gnc_last_rx, kgn_conn::gnc_last_rx_cq, kgn_conn::gnc_last_tx, kgn_conn::gnc_last_tx_cq, kgn_conn::gnc_peer_error, kgn_conn::gnc_rx_seq, kgn_conn::gnc_tx_retrans, kgn_conn::gnc_tx_seq, kgn_peer::gnp_conns, kgn_peer::gnp_nid, KGN_DEBUG_PEER_NID_DEFAULT, kgn_data::kgn_peer_conn_lock, kgnilnd_conn_dgram_type2str(), kgnilnd_conn_state2str(), kgnilnd_data, kgnilnd_debug_peer_nid, kgnilnd_find_peer_locked(), libcfs_nid2str(), list_for_each_entry, and kgn_conn::remote_mbox_addr.
Referenced by kgnilnd_peer_conns_seq_open().
static ssize_t kgnilnd_proc_peer_conns_write (struct file * file, const char __user * ubuffer, size_t count, loff_t * ppos) [static]
Definition at line 949 of file gnilnd_proc.c.
References kgnilnd_debug_peer_nid, and RETURN.
static ssize_t kgnilnd_proc_stats_write (struct file * file, const char __user * ubuffer, size_t count, loff_t * ppos) [static]
Definition at line 300 of file gnilnd_proc.c.
References CERROR, kgn_device::gnd_fast_block, kgn_device::gnd_fast_ok, kgn_device::gnd_fast_try, kgn_device::gnd_mutex_delay, kgn_device::gnd_n_schedule, kgn_device::gnd_n_yield, kgn_device::gnd_rdma_nrx, kgn_device::gnd_rdma_ntx, kgn_device::gnd_rdma_rxbytes, kgn_device::gnd_rdma_txbytes, kgn_device::gnd_rdmaq_nstalls, kgn_device::gnd_short_nrx, kgn_device::gnd_short_ntx, kgn_device::gnd_short_rxbytes, kgn_device::gnd_short_txbytes, GNILND_INIT_ALL, kgn_data::kgn_devices, kgn_data::kgn_init, kgn_data::kgn_nkmap_short, kgn_data::kgn_nvmap_cksum, kgn_data::kgn_nvmap_short, and kgnilnd_data.
static void* kgnilnd_smsg_seq_next (struct seq_file * s, void * iter, loff_t * pos) [static]
Definition at line 641 of file gnilnd_proc.c.
References kgnilnd_smsg_seq_seek(), LIBCFS_FREE, and list_head::next.
static int kgnilnd_smsg_seq_open (struct inode * inode, struct file * file) [static]
Definition at line 723 of file gnilnd_proc.c.
References kgn_smsg_sops.
int kgnilnd_smsg_seq_seek (kgn_smsg_seq_iter_t * gseq, loff_t off)
Definition at line 541 of file gnilnd_proc.c.
References kgn_device::gnd_fma_buffs, kgn_device::gnd_fmablk_lock, kgn_device::gnd_fmablk_vers, kgn_fma_memblock::gnm_bufflist, kgn_smsg_seq_iter_t::gsmsg_dev, kgn_smsg_seq_iter_t::gsmsg_fmablk, kgn_smsg_seq_iter_t::gsmsg_off, kgn_smsg_seq_iter_t::gsmsg_version, list_entry, and list_head::next.
Referenced by kgnilnd_smsg_seq_next(), and kgnilnd_smsg_seq_start().
static int kgnilnd_smsg_seq_show (struct seq_file * s, void * iter) [static]
Definition at line 657 of file gnilnd_proc.c.
References kgn_device::gnd_fmablk_lock, kgn_device::gnd_fmablk_vers, kgn_fma_memblock::gnm_avail_mboxs, kgn_fma_memblock::gnm_blk_size, kgn_fma_memblock::gnm_held_mboxs, kgn_fma_memblock::gnm_hndl, kgn_fma_memblock::gnm_hold_timeout, kgn_fma_memblock::gnm_num_mboxs, kgn_fma_memblock::gnm_state, kgn_smsg_seq_iter_t::gsmsg_dev, kgn_smsg_seq_iter_t::gsmsg_fmablk, kgn_smsg_seq_iter_t::gsmsg_off, kgn_smsg_seq_iter_t::gsmsg_version, kgnilnd_fmablk_state2str(), LASSERT, LPX64, gni_mem_handle::qword1, gni_mem_handle::qword2, and state.
static void* kgnilnd_smsg_seq_start (struct seq_file * s, loff_t * pos) [static]
Definition at line 604 of file gnilnd_proc.c.
References CERROR, GNILND_INIT_ALL, kgn_smsg_seq_iter_t::gsmsg_dev, kgn_smsg_seq_iter_t::gsmsg_fmablk, kgn_data::kgn_devices, kgn_data::kgn_init, kgnilnd_data, kgnilnd_smsg_seq_seek(), LIBCFS_ALLOC, and LIBCFS_FREE.
static void kgnilnd_smsg_seq_stop (struct seq_file * s, void * iter) [static]
Definition at line 632 of file gnilnd_proc.c.
References LIBCFS_FREE.
static int kgnilnd_stats_seq_open (struct inode * inode, struct file * file) [static]
Definition at line 337 of file gnilnd_proc.c.
References kgnilnd_stats_seq_show().
static int kgnilnd_stats_seq_show (struct seq_file * sf, void * v) [static]
Definition at line 208 of file gnilnd_proc.c.
References kgn_device::gnd_fast_block, kgn_device::gnd_fast_ok, kgn_device::gnd_fast_try, kgn_device::gnd_map_nphys, kgn_device::gnd_map_nvirt, kgn_device::gnd_map_physnop, kgn_device::gnd_map_virtnob, kgn_device::gnd_mutex_delay, kgn_device::gnd_n_mdd, kgn_device::gnd_n_mdd_held, kgn_device::gnd_n_schedule, kgn_device::gnd_n_yield, kgn_device::gnd_nbytes_map, kgn_device::gnd_ndgrams, kgn_device::gnd_neps, kgn_device::gnd_nfmablk, kgn_device::gnd_nq_map, kgn_device::gnd_rdma_nrx, kgn_device::gnd_rdma_ntx, kgn_device::gnd_rdma_rxbytes, kgn_device::gnd_rdma_txbytes, kgn_device::gnd_rdmaq_bytes_ok, kgn_device::gnd_rdmaq_bytes_out, kgn_device::gnd_rdmaq_nstalls, kgn_device::gnd_short_nrx, kgn_device::gnd_short_ntx, kgn_device::gnd_short_rxbytes, kgn_device::gnd_short_txbytes, GNILND_INIT_ALL, kgn_data::kgn_devices, kgn_data::kgn_init, kgn_data::kgn_nconns, kgn_data::kgn_neager_allocs, kgn_data::kgn_nkmap_short, kgn_data::kgn_npeers, kgn_data::kgn_ntx, kgn_data::kgn_nvmap_cksum, kgn_data::kgn_nvmap_short, kgn_data::kgn_rev_copy_buff, kgn_data::kgn_rev_length, kgn_data::kgn_rev_offset, kgnilnd_data, and LPU64.
Referenced by kgnilnd_stats_seq_open().
Variable Documentation
struct file_operations kgn_cksum_test_fops [static]
Initial value:
 {
        .owner   = THIS_MODULE,
        .open    = kgnilnd_cksum_test_seq_open,
        .read    = seq_read,
        .write   = kgnilnd_proc_cksum_test_write,
        .llseek  = seq_lseek,
        .release = seq_release,
}
Definition at line 198 of file gnilnd_proc.c.
Referenced by kgnilnd_proc_init().
struct file_operations kgn_conn_fops [static]
Initial value:
 {
        .owner   = THIS_MODULE,
        .open    = kgnilnd_conn_seq_open,
        .read    = seq_read,
        .llseek  = seq_lseek,
        .release = seq_release,
}
Definition at line 1091 of file gnilnd_proc.c.
struct seq_operations kgn_conn_sops [static]
Initial value:
 {
        .start = kgnilnd_conn_seq_start,
        .stop  = kgnilnd_conn_seq_stop,
        .next  = kgnilnd_conn_seq_next,
        .show  = kgnilnd_conn_seq_show,
}
Definition at line 937 of file gnilnd_proc.c.
Referenced by kgnilnd_conn_seq_open().
struct file_operations kgn_mdd_fops [static]
Initial value:
 {
        .owner   = THIS_MODULE,
        .open    = kgnilnd_mdd_seq_open,
        .read    = seq_read,
        .llseek  = seq_lseek,
        .release = seq_release,
}
Definition at line 525 of file gnilnd_proc.c.
struct seq_operations kgn_mdd_sops [static]
Initial value:
 {
        .start = kgnilnd_mdd_seq_start,
        .stop  = kgnilnd_mdd_seq_stop,
        .next  = kgnilnd_mdd_seq_next,
        .show  = kgnilnd_mdd_seq_show,
}
Definition at line 501 of file gnilnd_proc.c.
Referenced by kgnilnd_mdd_seq_open().
struct file_operations kgn_peer_conns_fops [static]
Initial value:
 {
        .owner   = THIS_MODULE,
        .open    = kgnilnd_peer_conns_seq_open,
        .read    = seq_read,
        .write   = kgnilnd_proc_peer_conns_write,
        .llseek  = seq_lseek,
        .release = seq_release,
}
Definition at line 1067 of file gnilnd_proc.c.
struct file_operations kgn_peer_fops [static]
Initial value:
 {
        .owner   = THIS_MODULE,
        .open    = kgnilnd_peer_seq_open,
        .read    = seq_read,
        .llseek  = seq_lseek,
        .release = seq_release,
}
Definition at line 1314 of file gnilnd_proc.c.
struct seq_operations kgn_peer_sops [static]
Initial value:
 {
        .start = kgnilnd_peer_seq_start,
        .stop  = kgnilnd_peer_seq_stop,
        .next  = kgnilnd_peer_seq_next,
        .show  = kgnilnd_peer_seq_show,
}
Definition at line 1292 of file gnilnd_proc.c.
Referenced by kgnilnd_peer_seq_open().
struct proc_dir_entry* kgn_proc_root [static]
Definition at line 1322 of file gnilnd_proc.c.
Referenced by kgnilnd_proc_fini(), and kgnilnd_proc_init().
struct file_operations kgn_smsg_fops [static]
Initial value:
 {
        .owner   = THIS_MODULE,
        .open    = kgnilnd_smsg_seq_open,
        .read    = seq_read,
        .llseek  = seq_lseek,
        .release = seq_release,
}
Definition at line 737 of file gnilnd_proc.c.
struct seq_operations kgn_smsg_sops [static]
Initial value:
 {
        .start = kgnilnd_smsg_seq_start,
        .stop  = kgnilnd_smsg_seq_stop,
        .next  = kgnilnd_smsg_seq_next,
        .show  = kgnilnd_smsg_seq_show,
}
Definition at line 714 of file gnilnd_proc.c.
Referenced by kgnilnd_smsg_seq_open().
struct file_operations kgn_stats_fops [static]
Initial value:
 {
        .owner   = THIS_MODULE,
        .open    = kgnilnd_stats_seq_open,
        .read    = seq_read,
        .write   = kgnilnd_proc_stats_write,
        .llseek  = seq_lseek,
        .release = seq_release,
}
Definition at line 342 of file gnilnd_proc.c.
Referenced by kgnilnd_proc_init().
int kgnilnd_debug_peer_nid = KGN_DEBUG_PEER_NID_DEFAULT [static]
Definition at line 946 of file gnilnd_proc.c.
Referenced by kgnilnd_proc_peer_conns_seq_show(), and kgnilnd_proc_peer_conns_write().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.