Lustre: lnet/klnds/gnilnd/gnilnd_stack.c File Reference
lnet/klnds/gnilnd/gnilnd_stack.c File Reference
#include "gnilnd.h"
Functions
void kgnilnd_bump_timeouts (__u32 nap_time, char *reason)
void kgnilnd_quiesce_wait (char *reason)
void kgnilnd_reset_stack (void)
int kgnilnd_ruhroh_thread (void *arg)
void kgnilnd_pause_threads (void)
int kgnilnd_hw_in_quiesce (void)
int kgnilnd_check_hw_quiesce (void)
void kgnilnd_quiesce_end_callback (gni_nic_handle_t nic_handle, uint64_t msecs)
void kgnilnd_critical_error (struct gni_err *err_handle)
int kgnilnd_start_rca_thread (void)
void kgnilnd_wakeup_rca_thread (void)
int kgnilnd_get_node_state (__u32 nid)
Function Documentation
void kgnilnd_bump_timeouts (__u32 nap_time, char * reason)
Definition at line 30 of file gnilnd_stack.c.
References CDEBUG, cfs_time_seconds(), D_INFO, kgn_conn::gnc_last_rx, kgn_conn::gnc_last_rx_cq, kgn_conn::gnc_last_tx, kgn_conn::gnc_state, kgn_conn::gnc_timeout, kgn_device::gnd_dgrams, kgn_dgram::gndg_post_time, GNILND_CONN_DONE, GNILND_IS_QUIESCED, kgn_peer::gnp_conns, kgn_peer::gnp_reconnect_interval, kgn_peer::gnp_reconnect_time, kgn_peer::gnp_tx_queue, kgn_data::kgn_devices, kgn_data::kgn_ndevs, kgn_data::kgn_nquiesce, kgn_data::kgn_nthreads, kgn_tunables::kgn_peer_hash_size, kgn_data::kgn_peers, kgnilnd_data, kgnilnd_peer_alive(), kgnilnd_peer_notify(), kgnilnd_schedule_conn, kgnilnd_tunables, LASSERTF, list_for_each_entry, timeout, and kgn_tx::tx_qtime.
Referenced by kgnilnd_reset_stack(), and kgnilnd_ruhroh_thread().
int kgnilnd_check_hw_quiesce (void)
Definition at line 512 of file gnilnd_stack.c.
References CDEBUG, D_NET, kgn_data::kgn_ruhroh_shutdown, kgnilnd_data, kgnilnd_hw_in_quiesce(), kgnilnd_pause_threads(), and likely.
Referenced by kgnilnd_reaper_check(), and kgnilnd_reaper_dgram_check().
void kgnilnd_critical_error (struct gni_err * err_handle)
Definition at line 558 of file gnilnd_stack.c.
References CDEBUG, D_NET, kgn_data::kgn_devices, kgn_data::kgn_needs_reset, kgn_data::kgn_ruhroh_shutdown, kgn_data::kgn_ruhroh_waitq, kgnilnd_data, and LASSERTF.
int kgnilnd_get_node_state (__u32 nid)
Definition at line 811 of file gnilnd_stack.c.
References GNILND_RCA_NODE_UP.
Referenced by kgnilnd_add_peer(), and kgnilnd_launch_tx().
int kgnilnd_hw_in_quiesce (void)
Definition at line 497 of file gnilnd_stack.c.
References kgn_device::gnd_handle, kgn_data::kgn_devices, kgnilnd_data, kgnilnd_get_quiesce_status(), and LASSERTF.
Referenced by kgnilnd_check_hw_quiesce(), and kgnilnd_ruhroh_thread().
void kgnilnd_pause_threads (void)
Definition at line 471 of file gnilnd_stack.c.
References CDEBUG, D_NET, GNILND_IS_QUIESCED, GNILND_QUIESCE_HW_QUIESCE, kgn_data::kgn_devices, kgn_data::kgn_needs_pause, kgn_data::kgn_quiesce_trigger, kgn_data::kgn_ruhroh_waitq, kgnilnd_data, and LASSERTF.
Referenced by kgnilnd_check_hw_quiesce(), and kgnilnd_quiesce_end_callback().
void kgnilnd_quiesce_end_callback (gni_nic_handle_t nic_handle, uint64_t msecs)
Definition at line 530 of file gnilnd_stack.c.
References CDEBUG, D_NET, kgn_data::kgn_bump_info_rdy, kgn_data::kgn_devices, kgn_data::kgn_quiesce_secs, kgn_data::kgn_ruhroh_shutdown, kgnilnd_data, kgnilnd_pause_threads(), LASSERTF, and LPD64.
Referenced by kgnilnd_dev_init().
void kgnilnd_quiesce_wait (char * reason)
Definition at line 100 of file gnilnd_stack.c.
References CDEBUG, cfs_duration_sec(), CFS_FAIL_GNI_QUIESCE_RACE, CFS_RACE, cfs_time_seconds(), D_INFO, kgn_device::gnd_dgping_waitq, kgn_device::gnd_dgram_waitq, kgn_device::gnd_waitq, GNILND_IS_QUIESCED, kgn_data::kgn_devices, kgn_data::kgn_ndevs, kgn_data::kgn_nquiesce, kgn_data::kgn_nthreads, kgn_data::kgn_quiesce_trigger, kgn_data::kgn_reaper_lock, kgn_data::kgn_reaper_waitq, kgn_tunables::kgn_timeout, kgnilnd_data, kgnilnd_schedule_dgram(), kgnilnd_tunables, kgnilnd_wakeup_rca_thread(), LASSERTF, and LCONSOLE_INFO.
Referenced by kgnilnd_reset_stack(), kgnilnd_ruhroh_thread(), and kgnilnd_shutdown().
void kgnilnd_reset_stack (void)
Definition at line 172 of file gnilnd_stack.c.
References CDEBUG, CERROR, cfs_duration_sec(), CFS_FAIL_GNI_DROP_CLOSING, CFS_FAIL_GNI_DROP_DESTROY_EP, CFS_FAIL_GNI_RACE_RESET, CFS_FAIL_GNI_SR_DOWN_RACE, CFS_FAIL_GNI_WC_DGRAM_FREE, CFS_RACE, D_NET, end, ENTRY, kgn_conn::gnc_close_sent, kgn_conn::gnc_schedlist, kgn_conn::gnc_scheduled, kgn_conn::gnc_state, kgn_device::gnd_neps, kgn_device::gnd_nfmablk, kgn_device::gnd_ready_conns, GNILND_CONN_CLOSED, GNILND_CONN_CLOSING, GNILND_CONN_DESTROY_EP, GNILND_CONN_IDLE, GNILND_CONN_PROCESS, GNILND_DEL_CONN, GNILND_INIT_ALL, GNILND_QUIESCE_IDLE, GNILND_QUIESCE_RESET, kgn_peer::gnp_conns, kgn_data::kgn_devices, kgn_data::kgn_in_reset, kgn_data::kgn_init, kgn_data::kgn_nconns, kgn_data::kgn_ndevs, kgn_tunables::kgn_net_hash_size, kgn_data::kgn_nets, kgn_data::kgn_nresets, kgn_tunables::kgn_peer_hash_size, kgn_data::kgn_peers, kgn_data::kgn_quiesce_trigger, kgnilnd_bump_timeouts(), kgnilnd_cancel_net_dgrams(), kgnilnd_cancel_wc_dgrams(), kgnilnd_complete_closed_conn(), kgnilnd_conn_decref, kgnilnd_count_list(), kgnilnd_data, kgnilnd_del_conn_or_peer(), kgnilnd_destroy_conn_ep(), kgnilnd_detach_purgatory_locked(), kgnilnd_dev_fini(), kgnilnd_dev_init(), kgnilnd_map_phys_fmablk(), kgnilnd_quiesce_wait(), kgnilnd_release_purgatory_list(), kgnilnd_schedule_process_conn(), kgnilnd_setup_wildcard_dgram(), kgnilnd_tunables, kgnilnd_unmap_fma_blocks(), kgnilnd_wait_for_canceled_dgrams(), LASSERTF, LCONSOLE_WARN, list_del_init(), list_empty(), list_for_each_entry, list_for_each_entry_safe, LIST_HEAD(), LNET_NID_ANY, RETURN_EXIT, seconds, and start.
Referenced by kgnilnd_ruhroh_thread().
int kgnilnd_ruhroh_thread (void * arg)
Definition at line 367 of file gnilnd_stack.c.
References CDEBUG, cfs_block_allsigs(), cfs_time_seconds(), D_INFO, D_NET, GNILND_QUIESCE_HW_QUIESCE, GNILND_QUIESCE_IDLE, kgn_data::kgn_bump_info_rdy, kgn_data::kgn_needs_pause, kgn_data::kgn_needs_reset, kgn_tunables::kgn_nice, kgn_data::kgn_quiesce_mutex, kgn_data::kgn_quiesce_secs, kgn_data::kgn_quiesce_trigger, kgn_data::kgn_ruhroh_running, kgn_data::kgn_ruhroh_shutdown, kgn_data::kgn_ruhroh_waitq, kgnilnd_bump_timeouts(), kgnilnd_data, kgnilnd_hw_in_quiesce(), kgnilnd_quiesce_wait(), kgnilnd_reset_stack(), and kgnilnd_tunables.
Referenced by kgnilnd_base_startup().
int kgnilnd_start_rca_thread (void)
Definition at line 800 of file gnilnd_stack.c.
Referenced by kgnilnd_base_startup().
void kgnilnd_wakeup_rca_thread (void)
Definition at line 806 of file gnilnd_stack.c.
Referenced by kgnilnd_base_shutdown(), and kgnilnd_quiesce_wait().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.