Lustre: lnet/klnds/gnilnd/gnilnd_cb.c File Reference
lnet/klnds/gnilnd/gnilnd_cb.c File Reference
#include <asm/page.h>
#include <linux/nmi.h>
#include "gnilnd.h"
Defines
#define _kgnilnd_cksum(seed, ptr, nob) csum_partial(ptr, nob, seed)
#define kgnilnd_match_reply_either(w, x, y, z) _kgnilnd_match_reply(w, x, y, z)
#define kgnilnd_match_reply(x, y, z) _kgnilnd_match_reply(x, y, GNILND_MSG_NONE, z)
Functions
static void kgnilnd_dump_blob (int level, char *prefix, void *buf, int len)
static void kgnilnd_dump_msg (int mask, kgn_msg_t *msg)
void kgnilnd_schedule_device (kgn_device_t *dev)
void kgnilnd_schedule_device_timer (unsigned long arg)
void kgnilnd_device_callback (__u32 devid, __u64 arg)
int kgnilnd_schedule_process_conn (kgn_conn_t *conn, int sched_intent)
int _kgnilnd_schedule_conn (kgn_conn_t *conn, const char *caller, int line, int refheld)
void kgnilnd_schedule_dgram (kgn_device_t *dev)
void kgnilnd_free_tx (kgn_tx_t *tx)
kgn_tx_t * kgnilnd_alloc_tx (void)
static __u16 kgnilnd_cksum (void *ptr, size_t nob)
__u16 kgnilnd_cksum_kiov (unsigned int nkiov, lnet_kiov_t *kiov, unsigned int offset, unsigned int nob, int dump_blob)
void kgnilnd_init_msg (kgn_msg_t *msg, int type, lnet_nid_t source)
kgn_tx_t * kgnilnd_new_tx_msg (int type, lnet_nid_t source)
static void kgnilnd_nak_rdma (kgn_conn_t *conn, int rx_type, int error, __u64 cookie, lnet_nid_t source)
int kgnilnd_setup_immediate_buffer (kgn_tx_t *tx, unsigned int niov, struct kvec *iov, lnet_kiov_t *kiov, unsigned int offset, unsigned int nob)
int kgnilnd_setup_virt_buffer (kgn_tx_t *tx, unsigned int niov, struct kvec *iov, unsigned int offset, unsigned int nob)
int kgnilnd_setup_phys_buffer (kgn_tx_t *tx, int nkiov, lnet_kiov_t *kiov, unsigned int offset, unsigned int nob)
static int kgnilnd_setup_rdma_buffer (kgn_tx_t *tx, unsigned int niov, struct kvec *iov, lnet_kiov_t *kiov, unsigned int offset, unsigned int nob)
static void kgnilnd_parse_lnet_rdma (lnet_msg_t *lntmsg, unsigned int *niov, unsigned int *offset, unsigned int *nob, lnet_kiov_t **kiov, int put_len)
static void kgnilnd_compute_rdma_cksum (kgn_tx_t *tx, int put_len)
static int kgnilnd_verify_rdma_cksum (kgn_tx_t *tx, __u16 rx_cksum, int put_len)
void kgnilnd_mem_add_map_list (kgn_device_t *dev, kgn_tx_t *tx)
void kgnilnd_mem_del_map_list (kgn_device_t *dev, kgn_tx_t *tx)
int kgnilnd_map_buffer (kgn_tx_t *tx)
void kgnilnd_add_purgatory_tx (kgn_tx_t *tx)
void kgnilnd_unmap_buffer (kgn_tx_t *tx, int error)
void kgnilnd_tx_done (kgn_tx_t *tx, int completion)
void kgnilnd_txlist_done (struct list_head *txlist, int error)
int kgnilnd_set_tx_id (kgn_tx_t *tx, kgn_conn_t *conn)
static int kgnilnd_tx_should_retry (kgn_conn_t *conn, kgn_tx_t *tx)
static int kgnilnd_sendmsg_nolock (kgn_tx_t *tx, void *immediate, unsigned int immediatenob, spinlock_t *state_lock, kgn_tx_list_state_t state)
static int kgnilnd_sendmsg (kgn_tx_t *tx, void *immediate, unsigned int immediatenob, spinlock_t *state_lock, kgn_tx_list_state_t state)
static int kgnilnd_sendmsg_trylock (kgn_tx_t *tx, void *immediate, unsigned int immediatenob, spinlock_t *state_lock, kgn_tx_list_state_t state)
int kgnilnd_auth_rdma_bytes (kgn_device_t *dev, kgn_tx_t *tx)
void kgnilnd_queue_rdma (kgn_conn_t *conn, kgn_tx_t *tx)
void kgnilnd_queue_tx (kgn_conn_t *conn, kgn_tx_t *tx)
void kgnilnd_launch_tx (kgn_tx_t *tx, kgn_net_t *net, lnet_process_id_t *target)
int kgnilnd_rdma (kgn_tx_t *tx, int type, kgn_rdma_desc_t *sink, unsigned int nob, __u64 cookie)
kgn_rx_t * kgnilnd_alloc_rx (void)
void kgnilnd_release_msg (kgn_conn_t *conn)
void kgnilnd_consume_rx (kgn_rx_t *rx)
int kgnilnd_send (lnet_ni_t *ni, void *private, lnet_msg_t *lntmsg)
void kgnilnd_setup_rdma (lnet_ni_t *ni, kgn_rx_t *rx, lnet_msg_t *lntmsg, int mlen)
int kgnilnd_eager_recv (lnet_ni_t *ni, void *private, lnet_msg_t *lntmsg, void **new_private)
int kgnilnd_recv (lnet_ni_t *ni, void *private, lnet_msg_t *lntmsg, int delayed, unsigned int niov, struct kvec *iov, lnet_kiov_t *kiov, unsigned int offset, unsigned int mlen, unsigned int rlen)
int kgnilnd_check_conn_timeouts_locked (kgn_conn_t *conn)
void kgnilnd_check_peer_timeouts_locked (kgn_peer_t *peer, struct list_head *todie, struct list_head *souls)
void kgnilnd_reaper_check (int idx)
void kgnilnd_update_reaper_timeout (long timeout)
static void kgnilnd_reaper_poke_with_stick (unsigned long arg)
int kgnilnd_reaper (void *arg)
int kgnilnd_recv_bte_get (kgn_tx_t *tx)
int kgnilnd_check_rdma_cq (kgn_device_t *dev)
int kgnilnd_check_fma_send_cq (kgn_device_t *dev)
int kgnilnd_check_fma_rcv_cq (kgn_device_t *dev)
int kgnilnd_send_mapped_tx (kgn_tx_t *tx, int try_map_if_full)
void kgnilnd_process_fmaq (kgn_conn_t *conn)
int kgnilnd_process_rdmaq (kgn_device_t *dev)
static void kgnilnd_swab_rdma_desc (kgn_rdma_desc_t *d)
kgn_tx_t * _kgnilnd_match_reply (kgn_conn_t *conn, int type1, int type2, __u64 cookie)
static void kgnilnd_complete_tx (kgn_tx_t *tx, int rc)
static void kgnilnd_finalize_rx_done (kgn_tx_t *tx, kgn_msg_t *msg)
void kgnilnd_check_fma_rx (kgn_conn_t *conn)
static int kgnilnd_check_conn_fail_loc (kgn_device_t *dev, kgn_conn_t *conn, int *intent)
static void kgnilnd_send_conn_close (kgn_conn_t *conn)
int kgnilnd_process_mapped_tx (kgn_device_t *dev)
int kgnilnd_process_conns (kgn_device_t *dev, unsigned long deadline)
int kgnilnd_scheduler (void *arg)
Define Documentation
#define _kgnilnd_cksum (seed, ptr, nob) csum_partial(ptr, nob, seed)
Definition at line 283 of file gnilnd_cb.c.
Referenced by kgnilnd_cksum(), and kgnilnd_cksum_kiov().
#define kgnilnd_match_reply (x, y, z) _kgnilnd_match_reply(x, y, GNILND_MSG_NONE, z)
Definition at line 3978 of file gnilnd_cb.c.
Referenced by kgnilnd_check_fma_rx().
#define kgnilnd_match_reply_either (w, x, y, z) _kgnilnd_match_reply(w, x, y, z)
Definition at line 3977 of file gnilnd_cb.c.
Referenced by kgnilnd_check_fma_rx().
Function Documentation
kgn_tx_t* _kgnilnd_match_reply (kgn_conn_t * conn, int type1, int type2, __u64 cookie)
Definition at line 3981 of file gnilnd_cb.c.
References CWARN, kgn_conn::gnc_peer, kgn_conn::gnc_tx_ref_table, GNILND_MSG_MAGIC, GNILND_TX_WAITING_REPLY, GNITX_ASSERTF, kgn_peer::gnp_nid, LASSERTF, libcfs_nid2str(), LPX64, kgn_tx::tx_id, kgn_tx::tx_msg, kgn_tx::tx_state, kgn_tx_ev_id::txe_cookie, and kgn_tx_ev_id::txe_idx.
int _kgnilnd_schedule_conn (kgn_conn_t * conn, const char * caller, int line, int refheld)
Definition at line 154 of file gnilnd_cb.c.
References CDEBUG, D_INFO, kgn_conn::gnc_device, kgn_conn::gnc_last_sched_ask, kgn_conn::gnc_sched_caller, kgn_conn::gnc_sched_line, kgn_conn::gnc_schedlist, kgn_conn::gnc_scheduled, kgn_device::gnd_lock, kgn_device::gnd_ready_conns, GNILND_CONN_IDLE, GNILND_CONN_WANTS_SCHED, kgnilnd_conn_addref, kgnilnd_schedule_device(), LASSERTF, list_add_tail(), and list_empty().
void kgnilnd_add_purgatory_tx (kgn_tx_t * tx)
Definition at line 1098 of file gnilnd_cb.c.
References kgn_mdd_purgatory::gmp_list, kgn_mdd_purgatory::gmp_map_key, kgn_conn::gnc_device, kgn_conn::gnc_in_purgatory, kgn_conn::gnc_list_lock, kgn_conn::gnc_mdd_list, kgn_conn::gnc_peer, kgn_device::gnd_n_mdd_held, GNITX_ASSERTF, kgn_peer::gnp_nid, LASSERTF, LIBCFS_ALLOC, libcfs_nid2str(), list_add_tail(), kgn_tx::tx_buffer_copy, kgn_tx::tx_buffer_copy_map_key, kgn_tx::tx_conn, and kgn_tx::tx_map_key.
Referenced by kgnilnd_unmap_buffer().
kgn_rx_t* kgnilnd_alloc_rx (void)
Definition at line 2041 of file gnilnd_cb.c.
References CDEBUG, CERROR, D_MALLOC, kgn_data::kgn_rx_cache, and kgnilnd_data.
Referenced by kgnilnd_check_fma_rx().
kgn_tx_t* kgnilnd_alloc_tx (void)
Definition at line 252 of file gnilnd_cb.c.
References CDEBUG, CERROR, CFS_FAIL_CHECK, CFS_FAIL_GNI_ALLOC_TX, D_MALLOC, GNILND_BUF_NONE, GNILND_MSG_NONE, GNILND_TX_ALLOCD, INIT_LIST_HEAD, kgn_data::kgn_ntx, kgn_data::kgn_tx_cache, kgnilnd_data, kgn_tx::tx_buftype, kgn_tx::tx_list, kgn_tx::tx_list_state, kgn_tx::tx_map_list, and kgn_tx::tx_msg.
Referenced by kgnilnd_new_tx_msg().
int kgnilnd_auth_rdma_bytes (kgn_device_t * dev, kgn_tx_t * tx) [inline]
Definition at line 1660 of file gnilnd_cb.c.
References CDEBUG, D_NET, kgn_device::gnd_rdmaq_bytes_ok, kgn_device::gnd_rdmaq_deadline, kgn_device::gnd_rdmaq_nstalls, kgn_device::gnd_rdmaq_timer, and kgn_tx::tx_nob.
Referenced by kgnilnd_process_rdmaq(), and kgnilnd_queue_rdma().
static int kgnilnd_check_conn_fail_loc (kgn_device_t * dev, kgn_conn_t * conn, int * intent) [inline, static]
Definition at line 4574 of file gnilnd_cb.c.
References CFS_FAIL_CHECK, CFS_FAIL_GNI_DROP_CLOSING, CFS_FAIL_GNI_DROP_DESTROY_EP, CFS_FAIL_GNI_FINISH_PURG, CFS_FAIL_GNI_FINISH_PURG2, cfs_fail_loc, CFS_FAIL_TIMEOUT, CFS_RACE, kgn_conn::gnc_state, GNILND_CONN_CLOSED, GNILND_CONN_DESTROY_EP, GOTO, likely, and RETURN.
Referenced by kgnilnd_process_conns().
int kgnilnd_check_conn_timeouts_locked (kgn_conn_t * conn)
Definition at line 2716 of file gnilnd_cb.c.
References CDEBUG, cfs_duration_sec(), CFS_FAIL_CHECK, CFS_FAIL_GNI_NOOP_SEND, cfs_time_seconds(), D_CONSOLE, D_NET, D_NETERROR, kgn_conn::gnc_last_noop_cq, kgn_conn::gnc_last_noop_sent, kgn_conn::gnc_last_noop_want, kgn_conn::gnc_last_rx_cq, kgn_conn::gnc_last_tx, kgn_conn::gnc_peer, kgn_conn::gnc_reaper_noop, kgn_conn::gnc_state, kgn_conn::gnc_timeout, GNIDBG_CONN, GNILND_CONN_ESTABLISHED, GNILND_LASTRX, GNILND_MSG_NOOP, GNILND_RCA_NODE_DOWN, GNILND_TO2KA, kgn_net::gnn_ni, kgn_peer::gnp_down, kgn_peer::gnp_net, kgn_peer::gnp_nid, keepalive, kgnilnd_conn_state2str(), kgnilnd_new_tx_msg(), kgnilnd_queue_tx(), LASSERTF, libcfs_nid2str(), lnet_ni::ni_nid, now(), and timeout.
Referenced by kgnilnd_check_peer_timeouts_locked().
int kgnilnd_check_fma_rcv_cq (kgn_device_t * dev)
Definition at line 3478 of file gnilnd_cb.c.
References __u64, CDEBUG, CFS_FAIL_CHECK, CFS_FAIL_GNI_CQ_GET_EVENT, cfs_fail_val, CNETERR, D_INFO, D_NET, kgn_conn::gnc_device, kgn_conn::gnc_first_rx, kgn_conn::gnc_last_rx_cq, kgn_conn::gnc_peer, kgn_device::gnd_cq_mutex, kgn_device::gnd_id, kgn_device::gnd_rcv_fma_cqh, kgn_device::gnd_sched_alive, GNI_CQ_GET_INST_ID, GNI_CQ_OVERRUN, GNI_RC_ERROR_RESOURCE, GNI_RC_NOT_DONE, GNI_RC_TRANSACTION_ERROR, kgn_peer::gnp_nid, kgn_data::kgn_conns, kgn_data::kgn_peer_conn_lock, kgn_tunables::kgn_peer_hash_size, kgn_data::kgn_quiesce_trigger, kgnilnd_cq_get_event(), kgnilnd_cqid2conn_locked(), kgnilnd_data, kgnilnd_gl_mutex_unlock(), kgnilnd_mutex_trylock(), kgnilnd_peer_alive(), kgnilnd_schedule_conn, kgnilnd_tunables, LASSERTF, libcfs_nid2str(), likely, list_entry, list_for_each, LPU64, LPX64, and unlikely.
Referenced by kgnilnd_scheduler().
void kgnilnd_check_fma_rx (kgn_conn_t * conn)
Definition at line 4089 of file gnilnd_cb.c.
References __swab16s, __swab32, __swab32s, __swab64s, CDEBUG, cfs_duration_sec(), CFS_FAIL_CHECK, CFS_FAIL_GNI_NET_LOOKUP, CFS_FAIL_GNI_RECV_TIMEOUT, cfs_time_seconds(), CNETERR, D_BUFFS, D_CONSOLE, D_INFO, D_NET, D_NETERROR, D_NETTRACE, D_WARNING, ENTRY, EXIT, kgn_conn::gnc_close_recvd, kgn_conn::gnc_device, kgn_conn::gnc_ephandle, kgn_conn::gnc_first_rx, kgn_conn::gnc_last_noop_cq, kgn_conn::gnc_last_noop_sent, kgn_conn::gnc_last_noop_want, kgn_conn::gnc_last_rx, kgn_conn::gnc_last_rx_cq, kgn_conn::gnc_last_sched_ask, kgn_conn::gnc_last_sched_do, kgn_conn::gnc_last_tx, kgn_conn::gnc_last_tx_cq, kgn_conn::gnc_list_lock, kgn_conn::gnc_peer, kgn_conn::gnc_peer_connstamp, kgn_conn::gnc_peer_error, kgn_conn::gnc_rx_seq, kgn_conn::gnc_state, kgn_conn::gnc_timeout, kgn_conn::gnc_tx_seq, kgn_device::gnd_cq_mutex, kgn_device::gnd_mutex_delay, kgn_device::gnd_sched_alive, kgn_device::gnd_short_nrx, kgn_device::gnd_short_rxbytes, GNI_RC_INVALID_STATE, GNI_RC_NOT_DONE, GNI_RC_SUCCESS, GNIDBG_CONN, GNIDBG_MSG, GNILND_BUF_PHYS_MAPPED, GNILND_BUF_VIRT_MAPPED, GNILND_CLOSE_RX, GNILND_CONN_ESTABLISHED, GNILND_LASTRX, GNILND_MSG_CLOSE, GNILND_MSG_GET_ACK_REV, GNILND_MSG_GET_DONE, GNILND_MSG_GET_DONE_REV, GNILND_MSG_GET_NAK, GNILND_MSG_GET_NAK_REV, GNILND_MSG_GET_REQ, GNILND_MSG_GET_REQ_REV, GNILND_MSG_IMMEDIATE, GNILND_MSG_MAGIC, GNILND_MSG_NOOP, GNILND_MSG_PUT_ACK, GNILND_MSG_PUT_DONE, GNILND_MSG_PUT_DONE_REV, GNILND_MSG_PUT_NAK, GNILND_MSG_PUT_NAK_REV, GNILND_MSG_PUT_REQ, GNILND_MSG_PUT_REQ_REV, GNILND_MSG_VERSION, GNILND_TIMEOUTRX, GNILND_TX_ALLOCD, GNILND_TX_PENDING_RDMA, GNILND_TX_WAITING_COMPLETION, GNILND_TX_WAITING_REPLY, GNITX_ASSERTF, kgn_net::gnn_ni, kgn_peer::gnp_nid, GOTO, kgn_rx::grx_conn, kgn_rx::grx_eager, kgn_rx::grx_msg, kgn_rx::grx_received, kgn_tunables::kgn_checksum, kgn_data::kgn_peer_conn_lock, kgnilnd_alloc_rx(), kgnilnd_cksum(), kgnilnd_close_conn(), kgnilnd_close_conn_locked(), kgnilnd_complete_tx(), kgnilnd_consume_rx(), kgnilnd_data, kgnilnd_dump_msg(), kgnilnd_finalize_rx_done(), kgnilnd_find_net(), kgnilnd_gl_mutex_lock(), kgnilnd_gl_mutex_unlock(), kgnilnd_match_reply, kgnilnd_match_reply_either, kgnilnd_msgtype2str(), kgnilnd_net_decref, kgnilnd_peer_alive(), kgnilnd_release_msg(), kgnilnd_schedule_conn, kgnilnd_send_mapped_tx(), kgnilnd_smsg_getnext(), kgnilnd_swab_rdma_desc(), kgnilnd_tunables, kgnilnd_tx_del_state_locked(), kgnilnd_tx_done(), LASSERTF, libcfs_nid2str(), likely, LNET_NIDADDR(), lnet_parse(), lnet_set_reply_msg_len(), LPX64, msg, now(), RETURN_EXIT, timeout, timestamp(), kgn_tx::tx_buftype, kgn_tx::tx_conn, kgn_tx::tx_lntmsg, kgn_tx::tx_msg, kgn_tx::tx_putinfo, and kgn_tx::tx_state.
Referenced by kgnilnd_process_conns().
int kgnilnd_check_fma_send_cq (kgn_device_t * dev)
Definition at line 3321 of file gnilnd_cb.c.
References __u64, CDEBUG, CNETERR, D_INFO, D_NET, kgn_conn::gnc_fmaq, kgn_conn::gnc_last_noop_cq, kgn_conn::gnc_last_tx_cq, kgn_conn::gnc_list_lock, kgn_conn::gnc_peer, kgn_conn::gnc_smsg_mutex, kgn_conn::gnc_tx_in_use, kgn_device::gnd_cq_mutex, kgn_device::gnd_id, kgn_device::gnd_sched_alive, kgn_device::gnd_snd_fma_cqh, GNI_CQ_EVENT_TYPE_SMSG, GNI_CQ_GET_INST_ID, GNI_CQ_GET_MSG_ID, GNI_CQ_GET_TYPE, GNI_CQ_OVERRUN, GNI_RC_NOT_DONE, GNI_RC_TRANSACTION_ERROR, GNIDBG_TX, GNILND_MSG_NOOP, GNILND_TX_ALLOCD, GNILND_TX_LIVE_FMAQ, GNILND_TX_PENDING_RDMA, GNILND_TX_WAITING_COMPLETION, GNILND_TX_WAITING_REPLY, GNITX_ASSERTF, kgn_peer::gnp_nid, kgn_data::kgn_peer_conn_lock, kgn_data::kgn_quiesce_trigger, kgnilnd_admin_decref, kgnilnd_close_conn_locked(), kgnilnd_conn_decref, kgnilnd_conn_mutex_lock(), kgnilnd_conn_mutex_unlock(), kgnilnd_cq_error_str(), kgnilnd_cq_get_event(), kgnilnd_cqid2conn_locked(), kgnilnd_data, kgnilnd_gl_mutex_unlock(), kgnilnd_mutex_trylock(), kgnilnd_schedule_conn, kgnilnd_send_mapped_tx(), kgnilnd_tx_del_state_locked(), kgnilnd_tx_done(), kgnilnd_validate_tx_ev_id(), LASSERTF, libcfs_nid2str(), list_empty(), LPX64, kgn_tx::tx_conn, kgn_tx::tx_list_state, kgn_tx::tx_msg, kgn_tx::tx_rc, kgn_tx::tx_state, kgn_tx_ev_id::txe_smsg_id, and unlikely.
Referenced by kgnilnd_scheduler().
void kgnilnd_check_peer_timeouts_locked (kgn_peer_t * peer, struct list_head * todie, struct list_head * souls)
Definition at line 2793 of file gnilnd_cb.c.
References CDEBUG, cfs_duration_sec(), CFS_FAIL_CHECK, CFS_FAIL_GNI_PURG_REL_DELAY, CFS_FAIL_GNI_RX_CLOSE_CLOSING, cfs_time_seconds(), D_INFO, D_NET, kgn_conn::gnc_close_recvd, kgn_conn::gnc_first_rx, kgn_conn::gnc_in_purgatory, kgn_conn::gnc_last_rx_cq, kgn_conn::gnc_needs_detach, kgn_conn::gnc_peer, kgn_conn::gnc_peer_error, kgn_conn::gnc_state, kgn_device::gnd_connd_lock, kgn_device::gnd_connd_peers, GNILND_CLOSE_INJECT1, GNILND_CONN_DONE, GNILND_MIN_TIMEOUT, GNILND_PEER_CONNECT, GNILND_PEER_IDLE, GNILND_PEER_KILL, GNILND_RCA_NODE_UP, GNILND_TX_ALLOCD, kgn_net::gnn_dev, kgn_peer::gnp_connd_list, kgn_peer::gnp_connecting, kgn_peer::gnp_conns, kgn_peer::gnp_dirty_eps, kgn_peer::gnp_down, kgn_peer::gnp_last_errno, kgn_peer::gnp_net, kgn_peer::gnp_nid, kgn_peer::gnp_reconnect_interval, kgn_peer::gnp_reconnect_time, kgn_peer::gnp_tx_queue, kgn_tunables::kgn_fast_reconn, kgn_tunables::kgn_hardware_timeout, kgn_tunables::kgn_max_purgatory, kgn_tunables::kgn_timeout, kgnilnd_cancel_peer_connect_locked(), kgnilnd_check_conn_timeouts_locked(), kgnilnd_close_conn_locked(), kgnilnd_detach_purgatory_locked(), kgnilnd_find_conn_locked(), kgnilnd_peer_addref, kgnilnd_schedule_dgram(), kgnilnd_tunables, kgnilnd_tx_del_state_locked(), LASSERTF, LCONSOLE_INFO, libcfs_nid2str(), list_add_tail(), list_empty(), list_for_each_entry_safe, MAX, timeout, kgn_tx::tx_list, and kgn_tx::tx_qtime.
Referenced by kgnilnd_reaper_check().
int kgnilnd_check_rdma_cq (kgn_device_t * dev)
Definition at line 3148 of file gnilnd_cb.c.
References __u64, CDEBUG, CFS_FAIL_CHECK, CFS_FAIL_GNI_DELAY_RDMA, CFS_FAIL_GNI_RDMA_CQ_ERROR, D_INFO, D_NET, D_NETERROR, kgn_conn::gnc_list_lock, kgn_conn::gnc_peer, kgn_conn::gnc_rdma_mutex, kgn_conn::gnc_tx_in_use, kgn_device::gnd_cq_mutex, kgn_device::gnd_id, kgn_device::gnd_rdma_ntx, kgn_device::gnd_rdma_txbytes, kgn_device::gnd_sched_alive, kgn_device::gnd_snd_rdma_cqh, GNI_CQ_EVENT_TYPE_POST, GNI_CQ_GET_TYPE, GNI_CQ_OVERRUN, GNI_RC_NOT_DONE, GNI_RC_SUCCESS, GNI_RC_TRANSACTION_ERROR, GNIDBG_TX, GNILND_MSG_GET_DONE, GNILND_MSG_GET_DONE_REV, GNILND_MSG_PUT_DONE, GNILND_MSG_PUT_DONE_REV, GNILND_NOPURG, GNILND_TX_ALLOCD, GNITX_ASSERTF, kgn_tunables::kgn_max_retransmits, kgn_data::kgn_quiesce_trigger, kgnilnd_admin_decref, kgnilnd_close_conn(), kgnilnd_conn_decref, kgnilnd_conn_mutex_lock(), kgnilnd_conn_mutex_unlock(), kgnilnd_cq_error_recoverable(), kgnilnd_cq_error_str(), kgnilnd_cq_get_event(), kgnilnd_data, kgnilnd_get_completed(), kgnilnd_gl_mutex_unlock(), kgnilnd_mutex_trylock(), kgnilnd_nak_rdma(), kgnilnd_peer_alive(), kgnilnd_queue_tx(), kgnilnd_rdma(), kgnilnd_recv_bte_get(), kgnilnd_tunables, kgnilnd_tx_del_state_locked(), kgnilnd_tx_done(), kgnilnd_validate_tx_ev_id(), kgnilnd_verify_rdma_cksum(), LASSERTF, likely, lnet_set_reply_msg_len(), LPX64, lnet_msg::msg_len, gni_post_descriptor::post_id, gni_post_descriptor::status, kgn_tx::tx_buffer_copy, kgn_tx::tx_getinfo, kgn_tx::tx_lntmsg, kgn_tx::tx_msg, kgn_tx::tx_nob, kgn_tx::tx_nob_rdma, kgn_tx::tx_putinfo, kgn_tx::tx_retrans, kgn_tx_ev_id::txe_cookie, and unlikely.
Referenced by kgnilnd_scheduler().
static __u16 kgnilnd_cksum (void * ptr, size_t nob) [inline, static]
Definition at line 289 of file gnilnd_cb.c.
References _kgnilnd_cksum, CDEBUG, and D_INFO.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_compute_rdma_cksum(), kgnilnd_recv(), kgnilnd_sendmsg_nolock(), kgnilnd_setup_immediate_buffer(), and kgnilnd_verify_rdma_cksum().
__u16 kgnilnd_cksum_kiov (unsigned int nkiov, lnet_kiov_t * kiov, unsigned int offset, unsigned int nob, int dump_blob) [inline]
Definition at line 306 of file gnilnd_cb.c.
References _kgnilnd_cksum, CDEBUG, cksum, CNETERR, D_BUFFS, kgn_data::kgn_cksum_map_pages, kgn_data::kgn_nvmap_cksum, kgn_tunables::kgn_vmap_cksum, kgnilnd_data, kgnilnd_dump_blob(), kgnilnd_tunables, lnet_kiov_t::kiov_len, lnet_kiov_t::kiov_offset, lnet_kiov_t::kiov_page, LASSERT, LASSERTF, and RETURN.
Referenced by _kgnilnd_proc_run_cksum_test(), kgnilnd_compute_rdma_cksum(), and kgnilnd_verify_rdma_cksum().
static void kgnilnd_complete_tx (kgn_tx_t * tx, int rc) [inline, static]
Definition at line 4022 of file gnilnd_cb.c.
References __u64, CDEBUG, cfs_duration_sec(), D_NETERROR, kgn_conn::gnc_list_lock, kgn_conn::gnc_peer, GNIDBG_TOMSG, GNILND_TX_ALLOCD, GNILND_TX_WAITING_COMPLETION, GNILND_TX_WAITING_REPLY, GNITX_ASSERTF, kgn_peer::gnp_nid, kgn_tunables::kgn_efault_lbug, kgnilnd_tunables, kgnilnd_tx_del_state_locked(), kgnilnd_tx_done(), kgnilnd_tx_state2str(), LBUG, libcfs_nid2str(), LPX64, gni_mem_handle::qword1, gni_mem_handle::qword2, kgn_tx::tx_buftype, kgn_tx::tx_conn, kgn_tx::tx_id, kgn_tx::tx_list_state, kgn_tx::tx_map_key, kgn_tx::tx_msg, kgn_tx::tx_nob, kgn_tx::tx_phys_npages, kgn_tx::tx_qtime, kgn_tx::tx_rc, kgn_tx::tx_state, kgn_tx_ev_id::txe_idx, and kgn_tx_ev_id::txe_smsg_id.
Referenced by kgnilnd_check_fma_rx(), and kgnilnd_finalize_rx_done().
static void kgnilnd_compute_rdma_cksum (kgn_tx_t * tx, int put_len) [inline, static]
Definition at line 800 of file gnilnd_cb.c.
References CFS_FAIL_CHECK, CFS_FAIL_GNI_SMSG_CKSUM3, D_BUFFS, GNILND_MSG_GET_ACK_REV, GNILND_MSG_GET_DONE, GNILND_MSG_GET_DONE_REV, GNILND_MSG_PUT_DONE, GNILND_MSG_PUT_DONE_REV, GNILND_MSG_PUT_REQ_REV, GNITX_ASSERTF, kgn_tunables::kgn_checksum, kgn_tunables::kgn_checksum_dump, kgnilnd_cksum(), kgnilnd_cksum_kiov(), kgnilnd_dump_blob(), kgnilnd_msgtype2str(), kgnilnd_parse_lnet_rdma(), kgnilnd_tunables, kgn_tx::tx_buffer, kgn_tx::tx_lntmsg, and kgn_tx::tx_msg.
Referenced by kgnilnd_rdma(), and kgnilnd_send_mapped_tx().
void kgnilnd_consume_rx (kgn_rx_t * rx)
Definition at line 2084 of file gnilnd_cb.c.
References CDEBUG, D_MALLOC, D_NET, GNIDBG_MSG, kgn_rx::grx_conn, kgn_rx::grx_eager, kgn_rx::grx_msg, kgn_tunables::kgn_max_immediate, kgn_data::kgn_neager_allocs, kgn_data::kgn_rx_cache, kgnilnd_conn_decref, kgnilnd_data, kgnilnd_release_msg(), kgnilnd_tunables, LIBCFS_FREE, and unlikely.
Referenced by kgnilnd_check_fma_rx(), and kgnilnd_recv().
void kgnilnd_device_callback (__u32 devid, __u64 arg)
Definition at line 95 of file gnilnd_cb.c.
References kgn_device::gnd_id, kgn_data::kgn_devices, kgn_data::kgn_ndevs, kgnilnd_data, kgnilnd_schedule_device(), and LCONSOLE_EMERG.
Referenced by kgnilnd_dev_init().
static void kgnilnd_dump_blob (int level, char * prefix, void * buf, int len) [static]
Definition at line 33 of file gnilnd_cb.c.
References __u64, and CDEBUG.
Referenced by kgnilnd_cksum_kiov(), kgnilnd_compute_rdma_cksum(), kgnilnd_recv(), kgnilnd_setup_immediate_buffer(), and kgnilnd_verify_rdma_cksum().
static void kgnilnd_dump_msg (int mask, kgn_msg_t * msg) [static]
Definition at line 61 of file gnilnd_cb.c.
References CDEBUG.
Referenced by kgnilnd_check_fma_rx().
int kgnilnd_eager_recv (lnet_ni_t * ni, void * private, lnet_msg_t * lntmsg, void ** new_private)
Definition at line 2342 of file gnilnd_cb.c.
References CERROR, D_ERROR, D_NET, kgn_conn::gnc_peer, kgn_conn::gnc_peer_connstamp, GNIDBG_MSG, kgn_peer::gnp_nid, kgn_rx::grx_conn, kgn_rx::grx_eager, kgn_rx::grx_lntmsg, kgn_rx::grx_msg, kgn_tunables::kgn_eager_credits, kgn_tunables::kgn_max_immediate, kgn_data::kgn_neager_allocs, kgn_data::kgn_peer_conn_lock, kgnilnd_conn_addref, kgnilnd_conn_decref, kgnilnd_data, kgnilnd_find_conn_locked(), kgnilnd_find_peer_locked(), kgnilnd_release_msg(), kgnilnd_tunables, LIBCFS_ALLOC, libcfs_nid2str(), and LPX64.
static void kgnilnd_finalize_rx_done (kgn_tx_t * tx, kgn_msg_t * msg) [inline, static]
Definition at line 4073 of file gnilnd_cb.c.
References kgn_conn::gnc_device, kgn_device::gnd_rdma_nrx, kgn_device::gnd_rdma_rxbytes, kgnilnd_complete_tx(), kgnilnd_verify_rdma_cksum(), kgn_tx::tx_conn, and kgn_tx::tx_nob.
Referenced by kgnilnd_check_fma_rx().
void kgnilnd_free_tx (kgn_tx_t * tx)
Definition at line 218 of file gnilnd_cb.c.
References CDEBUG, D_MALLOC, GNILND_TX_ALLOCD, kgn_data::kgn_ntx, kgn_data::kgn_tx_cache, kgn_data::kgn_tx_phys_cache, kgnilnd_data, KGNILND_POISON, kgnilnd_tx_state2str(), LASSERTF, list_empty(), LNET_MAX_IOV, kgn_tx::tx_buffer_copy, kgn_tx::tx_list, kgn_tx::tx_list_p, kgn_tx::tx_list_state, and kgn_tx::tx_phys.
Referenced by kgnilnd_tx_done().
void kgnilnd_init_msg (kgn_msg_t * msg, int type, lnet_nid_t source)
Definition at line 417 of file gnilnd_cb.c.
References GNILND_MSG_MAGIC, and GNILND_MSG_VERSION.
Referenced by kgnilnd_new_tx_msg(), and kgnilnd_rdma().
void kgnilnd_launch_tx (kgn_tx_t * tx, kgn_net_t * net, lnet_process_id_t * target)
Definition at line 1773 of file gnilnd_cb.c.
References CFS_FAIL_CHECK, CFS_FAIL_GNI_DGRAM_DROP_TX, CFS_FAIL_GNI_FIND_TARGET, CFS_RACE, ENTRY, GNILND_RCA_NODE_DOWN, GNILND_RCA_NODE_UP, GNILND_TX_PEERQ, GNITX_ASSERTF, kgn_peer::gnp_down, GOTO, kgn_data::kgn_net_rw_sem, kgn_data::kgn_peer_conn_lock, kgnilnd_add_peer_locked(), kgnilnd_create_peer_safe(), kgnilnd_data, kgnilnd_find_conn_locked(), kgnilnd_find_or_create_conn_locked(), kgnilnd_find_peer_locked(), kgnilnd_get_node_state(), kgnilnd_queue_tx(), kgnilnd_tx_add_state_locked(), kgnilnd_tx_done(), LNET_NIDADDR(), lnet_process_id_t::nid, RETURN_EXIT, kgn_tx::tx_conn, and kgn_tx::tx_qtime.
Referenced by kgnilnd_query(), and kgnilnd_send().
int kgnilnd_map_buffer (kgn_tx_t * tx)
Definition at line 1015 of file gnilnd_cb.c.
References __u64, CFS_FAIL_CHECK, CFS_FAIL_GNI_MAP_TX, D_NET, D_NETTRACE, kgn_conn::gnc_device, kgn_device::gnd_handle, kgn_device::gnd_id, kgn_device::gnd_map_nphys, kgn_device::gnd_map_nvirt, kgn_device::gnd_map_physnop, kgn_device::gnd_map_virtnob, kgn_device::gnd_rdmaq_bytes_out, GNI_MEM_PHYS_SEGMENTS, GNI_MEM_READWRITE, GNI_MEM_RELAXED_PI_ORDERING, GNI_RC_ERROR_RESOURCE, GNI_RC_SUCCESS, GNIDBG_TX, GNILND_BUF_IMMEDIATE, GNILND_BUF_IMMEDIATE_KIOV, GNILND_BUF_NONE, GNILND_BUF_PHYS_MAPPED, GNILND_BUF_PHYS_UNMAPPED, GNILND_BUF_VIRT_MAPPED, GNILND_BUF_VIRT_UNMAPPED, GNILND_MSG_GET_REQ, GNILND_MSG_PUT_ACK, GNITX_ASSERTF, kgn_tunables::kgn_bte_relaxed_ordering, kgnilnd_mem_add_map_list(), kgnilnd_mem_register(), kgnilnd_mem_register_segments(), kgnilnd_tunables, LASSERTF, LBUG, LPU64, RETURN, kgn_tx::tx_buffer, kgn_tx::tx_buftype, kgn_tx::tx_conn, kgn_tx::tx_map_key, kgn_tx::tx_msg, kgn_tx::tx_nob, kgn_tx::tx_phys, kgn_tx::tx_phys_npages, and unlikely.
Referenced by kgnilnd_send_mapped_tx().
void kgnilnd_mem_add_map_list (kgn_device_t * dev, kgn_tx_t * tx)
Definition at line 918 of file gnilnd_cb.c.
References D_EMERG, D_NETTRACE, kgn_device::gnd_map_list, kgn_device::gnd_map_lock, kgn_device::gnd_map_nphys, kgn_device::gnd_map_nvirt, kgn_device::gnd_map_physnop, kgn_device::gnd_map_version, kgn_device::gnd_map_virtnob, kgn_device::gnd_n_mdd, kgn_device::gnd_nbytes_map, kgn_device::gnd_rdmaq_bytes_out, GNIDBG_TX, GNILND_BUF_PHYS_MAPPED, GNILND_BUF_VIRT_MAPPED, GNILND_MSG_GET_REQ, GNILND_MSG_PUT_ACK, GNITX_ASSERTF, LBUG, list_add_tail(), list_empty(), LPD64, kgn_tx::tx_buftype, kgn_tx::tx_map_list, kgn_tx::tx_msg, kgn_tx::tx_nob, kgn_tx::tx_phys_npages, and kgn_tx::tx_retrans.
Referenced by kgnilnd_map_buffer().
void kgnilnd_mem_del_map_list (kgn_device_t * dev, kgn_tx_t * tx)
Definition at line 967 of file gnilnd_cb.c.
References D_EMERG, D_NETTRACE, kgn_device::gnd_map_lock, kgn_device::gnd_map_nphys, kgn_device::gnd_map_nvirt, kgn_device::gnd_map_physnop, kgn_device::gnd_map_version, kgn_device::gnd_map_virtnob, kgn_device::gnd_n_mdd, kgn_device::gnd_nbytes_map, kgn_device::gnd_rdmaq_bytes_out, GNIDBG_TX, GNILND_BUF_PHYS_UNMAPPED, GNILND_BUF_VIRT_UNMAPPED, GNILND_MSG_GET_REQ, GNILND_MSG_PUT_ACK, GNITX_ASSERTF, LASSERTF, LBUG, list_del_init(), list_empty(), LPD64, kgn_tx::tx_buftype, kgn_tx::tx_map_list, kgn_tx::tx_msg, kgn_tx::tx_nob, and kgn_tx::tx_phys_npages.
Referenced by kgnilnd_unmap_buffer().
static void kgnilnd_nak_rdma (kgn_conn_t * conn, int rx_type, int error, __u64 cookie, lnet_nid_t source) [static]
Definition at line 447 of file gnilnd_cb.c.
References CERROR, CNETERR, kgn_conn::gnc_peer, GNILND_MSG_GET_ACK_REV, GNILND_MSG_GET_DONE, GNILND_MSG_GET_DONE_REV, GNILND_MSG_GET_NAK, GNILND_MSG_GET_NAK_REV, GNILND_MSG_GET_REQ, GNILND_MSG_GET_REQ_REV, GNILND_MSG_PUT_ACK, GNILND_MSG_PUT_DONE, GNILND_MSG_PUT_DONE_REV, GNILND_MSG_PUT_NAK, GNILND_MSG_PUT_NAK_REV, GNILND_MSG_PUT_REQ, GNILND_MSG_PUT_REQ_REV, kgn_peer::gnp_nid, kgnilnd_msgtype2str(), kgnilnd_new_tx_msg(), kgnilnd_queue_tx(), LASSERTF, LBUG, libcfs_nid2str(), LPU64, and kgn_tx::tx_msg.
Referenced by kgnilnd_check_rdma_cq(), kgnilnd_process_mapped_tx(), kgnilnd_rdma(), kgnilnd_recv(), and kgnilnd_setup_rdma().
kgn_tx_t* kgnilnd_new_tx_msg (int type, lnet_nid_t source)
Definition at line 432 of file gnilnd_cb.c.
References CERROR, kgnilnd_alloc_tx(), kgnilnd_init_msg(), kgnilnd_msgtype2str(), and kgn_tx::tx_msg.
Referenced by kgnilnd_check_conn_timeouts_locked(), kgnilnd_finish_connect(), kgnilnd_nak_rdma(), kgnilnd_process_fmaq(), kgnilnd_query(), kgnilnd_recv(), kgnilnd_send(), kgnilnd_send_conn_close(), and kgnilnd_setup_rdma().
static void kgnilnd_parse_lnet_rdma (lnet_msg_t * lntmsg, unsigned int * niov, unsigned int * offset, unsigned int * nob, lnet_kiov_t ** kiov, int put_len) [static]
Definition at line 777 of file gnilnd_cb.c.
References lnet_libmd::kiov, LNET_MD_KIOV, LNET_MSG_GET, lnet_libmd::md_iov, lnet_libmd::md_length, lnet_libmd::md_niov, lnet_libmd::md_options, lnet_msg::msg_kiov, lnet_msg::msg_md, lnet_msg::msg_niov, lnet_msg::msg_offset, and lnet_msg::msg_type.
Referenced by kgnilnd_compute_rdma_cksum(), kgnilnd_recv_bte_get(), and kgnilnd_verify_rdma_cksum().
int kgnilnd_process_conns (kgn_device_t * dev, unsigned long deadline)
Definition at line 4870 of file gnilnd_cb.c.
References CDEBUG, D_INFO, kgn_conn::gnc_last_sched_do, kgn_conn::gnc_peer, kgn_conn::gnc_refcount, kgn_conn::gnc_schedlist, kgn_conn::gnc_scheduled, kgn_conn::gnc_state, kgn_conn::gnc_tx_in_use, kgn_device::gnd_conn_sem, kgn_device::gnd_lock, kgn_device::gnd_ready_conns, kgn_device::gnd_sched_alive, GNILND_CONN_CLOSED, GNILND_CONN_CLOSING, GNILND_CONN_DESTROY_EP, GNILND_CONN_IDLE, GNILND_CONN_PROCESS, kgn_peer::gnp_dirty_eps, kgn_data::kgn_quiesce_trigger, kgnilnd_check_conn_fail_loc(), kgnilnd_check_fma_rx(), kgnilnd_complete_closed_conn(), kgnilnd_conn_decref, kgnilnd_conn_state2str(), kgnilnd_data, kgnilnd_destroy_conn_ep(), kgnilnd_process_fmaq(), kgnilnd_schedule_conn, kgnilnd_schedule_process_conn(), kgnilnd_send_conn_close(), LASSERTF, list_del_init(), list_empty(), RETURN, and unlikely.
Referenced by kgnilnd_scheduler().
void kgnilnd_process_fmaq (kgn_conn_t * conn)
Definition at line 3726 of file gnilnd_cb.c.
References CDEBUG, cfs_duration_sec(), CFS_FAIL_CHECK, CFS_FAIL_GNI_NOOP_SEND, cfs_time_seconds(), D_NET, kgn_conn::gnc_close_sent, kgn_conn::gnc_ephandle, kgn_conn::gnc_fmaq, kgn_conn::gnc_last_noop_cq, kgn_conn::gnc_last_noop_sent, kgn_conn::gnc_last_noop_want, kgn_conn::gnc_last_tx, kgn_conn::gnc_list_lock, kgn_conn::gnc_peer, kgn_conn::gnc_sched_noop, kgn_conn::gnc_timeout, GNILND_MSG_CLOSE, GNILND_MSG_GET_ACK_REV, GNILND_MSG_GET_DONE, GNILND_MSG_GET_DONE_REV, GNILND_MSG_GET_NAK, GNILND_MSG_GET_NAK_REV, GNILND_MSG_GET_REQ, GNILND_MSG_GET_REQ_REV, GNILND_MSG_IMMEDIATE, GNILND_MSG_NOOP, GNILND_MSG_PUT_ACK, GNILND_MSG_PUT_DONE, GNILND_MSG_PUT_DONE_REV, GNILND_MSG_PUT_NAK, GNILND_MSG_PUT_NAK_REV, GNILND_MSG_PUT_REQ, GNILND_MSG_PUT_REQ_REV, GNILND_TO2KA, GNILND_TX_ALLOCD, GNILND_TX_FMAQ, GNILND_TX_WAITING_COMPLETION, GNILND_TX_WAITING_REPLY, GNITX_ASSERTF, kgn_net::gnn_ni, kgn_peer::gnp_net, kgn_peer::gnp_nid, keepalive, kgnilnd_close_conn(), kgnilnd_msgtype2str(), kgnilnd_new_tx_msg(), kgnilnd_schedule_conn, kgnilnd_sendmsg(), kgnilnd_set_tx_id(), kgnilnd_tx_del_state_locked(), kgnilnd_tx_done(), LASSERTF, LBUG, libcfs_nid2str(), likely, list_empty(), LPX64, lnet_ni::ni_nid, kgn_tx::tx_buffer, kgn_tx::tx_cred_wait, kgn_tx::tx_id, kgn_tx::tx_msg, kgn_tx::tx_nob, kgn_tx::tx_retrans, kgn_tx::tx_state, kgn_tx_ev_id::txe_cookie, and kgn_tx_ev_id::txe_smsg_id.
Referenced by kgnilnd_process_conns().
int kgnilnd_process_mapped_tx (kgn_device_t * dev)
Definition at line 4704 of file gnilnd_cb.c.
References D_NET, D_NETERROR, ENTRY, kgn_conn::gnc_state, kgn_device::gnd_last_map, kgn_device::gnd_lock, kgn_device::gnd_map_attempt, kgn_device::gnd_map_nphys, kgn_device::gnd_map_nvirt, kgn_device::gnd_map_physnop, kgn_device::gnd_map_timer, kgn_device::gnd_map_tx, kgn_device::gnd_map_version, kgn_device::gnd_map_virtnob, kgn_device::gnd_n_mdd, kgn_device::gnd_n_mdd_held, kgn_device::gnd_nbytes_map, kgn_device::gnd_next_map, kgn_device::gnd_nq_map, kgn_device::gnd_sched_alive, GNIDBG_TX, GNILND_CONN_ESTABLISHED, GNILND_FAST_MAPPING_TRY, GNILND_MAP_RETRY_RATE, GNILND_MAP_TIMEOUT, GNILND_MSG_GET_REQ_REV, GNILND_MSG_PUT_REQ, GNILND_TX_ALLOCD, GNILND_TX_DYING, GNILND_TX_MAPQ, GOTO, kgn_data::kgn_quiesce_trigger, kgnilnd_data, kgnilnd_nak_rdma(), kgnilnd_send_mapped_tx(), kgnilnd_tx_add_state_locked(), kgnilnd_tx_del_state_locked(), kgnilnd_tx_done(), likely, list_empty(), LPU64, RETURN, kgn_tx::tx_conn, kgn_tx::tx_getinfo, kgn_tx::tx_msg, kgn_tx::tx_nob, kgn_tx::tx_phys_npages, kgn_tx::tx_putinfo, and unlikely.
Referenced by kgnilnd_scheduler().
int kgnilnd_process_rdmaq (kgn_device_t * dev)
Definition at line 3869 of file gnilnd_cb.c.
References CDEBUG, CFS_FAIL_CHECK, CFS_FAIL_GNI_DELAY_RDMAQ, cfs_time_seconds(), D_NET, kgn_conn::gnc_state, kgn_device::gnd_rdmaq, kgn_device::gnd_rdmaq_bytes_ok, kgn_device::gnd_rdmaq_bytes_out, kgn_device::gnd_rdmaq_deadline, kgn_device::gnd_rdmaq_lock, kgn_device::gnd_rdmaq_timer, GNILND_CONN_ESTABLISHED, GNILND_TX_ALLOCD, GNILND_TX_DYING, GNILND_TX_RDMAQ, kgn_data::kgn_quiesce_trigger, kgn_tunables::kgn_rdmaq_intervals, kgn_data::kgn_rdmaq_override, kgnilnd_auth_rdma_bytes(), kgnilnd_data, kgnilnd_send_mapped_tx(), kgnilnd_tunables, kgnilnd_tx_add_state_locked(), kgnilnd_tx_del_state_locked(), list_empty(), RETURN, kgn_tx::tx_conn, kgn_tx::tx_qtime, and unlikely.
Referenced by kgnilnd_scheduler().
void kgnilnd_queue_rdma (kgn_conn_t * conn, kgn_tx_t * tx)
Definition at line 1684 of file gnilnd_cb.c.
References kgn_conn::gnc_device, kgn_device::gnd_lock, kgn_device::gnd_rdmaq_lock, GNILND_TX_MAPQ, GNILND_TX_RDMAQ, kgnilnd_auth_rdma_bytes(), kgnilnd_schedule_device(), kgnilnd_tx_add_state_locked(), kgn_tx::tx_conn, and kgn_tx::tx_qtime.
Referenced by kgnilnd_queue_tx().
void kgnilnd_queue_tx (kgn_conn_t * conn, kgn_tx_t * tx)
Definition at line 1714 of file gnilnd_cb.c.
References CDEBUG, CFS_FAIL_CHECK, CFS_FAIL_GNI_ONLY_NOOP, D_NET, kgn_conn::gnc_list_lock, kgn_conn::gnc_peer, GNILND_MSG_GET_ACK_REV, GNILND_MSG_GET_REQ, GNILND_MSG_IMMEDIATE, GNILND_MSG_NOOP, GNILND_MSG_PUT_ACK, GNILND_MSG_PUT_REQ_REV, GNILND_TX_FMAQ, kgn_peer::gnp_nid, kgnilnd_msgtype2str(), kgnilnd_queue_rdma(), kgnilnd_schedule_conn, kgnilnd_sendmsg_trylock(), kgnilnd_set_tx_id(), kgnilnd_tx_add_state_locked(), kgnilnd_tx_done(), libcfs_nid2str(), kgn_tx::tx_buffer, kgn_tx::tx_id, kgn_tx::tx_msg, kgn_tx::tx_nob, kgn_tx::tx_qtime, and kgn_tx_ev_id::txe_idx.
Referenced by kgnilnd_check_conn_timeouts_locked(), kgnilnd_check_rdma_cq(), kgnilnd_finish_connect(), kgnilnd_launch_tx(), kgnilnd_nak_rdma(), and kgnilnd_rdma().
int kgnilnd_rdma (kgn_tx_t * tx, int type, kgn_rdma_desc_t * sink, unsigned int nob, __u64 cookie)
Definition at line 1876 of file gnilnd_cb.c.
References __u64, CERROR, gni_post_descriptor::cq_mode, D_NET, gni_post_descriptor::dlvr_mode, kgn_conn::gnc_close_sent, kgn_conn::gnc_device, kgn_conn::gnc_ephandle, kgn_conn::gnc_list_lock, kgn_conn::gnc_peer, kgn_conn::gnc_rdma_mutex, kgn_device::gnd_cq_mutex, kgn_device::gnd_handle, kgn_device::gnd_lock, kgn_device::gnd_mutex_delay, kgn_device::gnd_snd_rdma_cqh, GNI_CQMODE_GLOBAL_EVENT, GNI_MEM_READWRITE, GNI_POST_RDMA_GET, GNI_POST_RDMA_PUT, GNI_RC_ERROR_RESOURCE, GNI_RC_SUCCESS, GNIDBG_TX, GNILND_MSG_GET_DONE, GNILND_MSG_GET_DONE_REV, GNILND_MSG_PUT_DONE, GNILND_MSG_PUT_DONE_REV, GNILND_TX_LIVE_RDMAQ, GNILND_TX_MAPQ, kgn_tunables::kgn_bte_dlvr_mode, kgn_data::kgn_rev_copy_buff, kgn_data::kgn_rev_length, kgn_data::kgn_rev_offset, kgnilnd_admin_addref, kgnilnd_compute_rdma_cksum(), kgnilnd_conn_mutex_lock(), kgnilnd_conn_mutex_unlock(), kgnilnd_data, kgnilnd_gl_mutex_lock(), kgnilnd_gl_mutex_unlock(), kgnilnd_init_msg(), kgnilnd_mem_register(), kgnilnd_msgtype2str(), kgnilnd_nak_rdma(), kgnilnd_post_rdma(), kgnilnd_queue_tx(), kgnilnd_schedule_device(), kgnilnd_tunables, kgnilnd_tx_add_state_locked(), kgnilnd_tx_done(), kgnilnd_tx_mapped(), kgnilnd_unmap_buffer(), LASSERT, LASSERTF, LBUG, gni_post_descriptor::length, gni_post_descriptor::local_addr, gni_post_descriptor::local_mem_hndl, LPX64, gni_post_descriptor::post_id, gni_post_descriptor::remote_addr, gni_post_descriptor::remote_mem_hndl, gni_post_descriptor::src_cq_hndl, timestamp(), kgn_tx::tx_buffer, kgn_tx::tx_buffer_copy, kgn_tx::tx_buffer_copy_map_key, kgn_tx::tx_conn, kgn_tx::tx_id, kgn_tx::tx_map_key, kgn_tx::tx_msg, kgn_tx::tx_nob, kgn_tx::tx_nob_rdma, kgn_tx::tx_offset, kgn_tx::tx_qtime, kgn_tx::tx_rdma_desc, kgn_tx_ev_id::txe_cookie, and gni_post_descriptor::type.
Referenced by kgnilnd_check_rdma_cq(), and kgnilnd_send_mapped_tx().
int kgnilnd_reaper (void * arg)
Definition at line 3033 of file gnilnd_cb.c.
References CDEBUG, cfs_block_allsigs(), cfs_duration_sec(), cfs_time_seconds(), D_INFO, D_NET, GNILND_REAPER_NCHECKS, GNILND_REAPER_THREAD_WAKE, kgn_data::kgn_new_min_timeout, kgn_tunables::kgn_nice, kgn_tunables::kgn_peer_hash_size, kgn_data::kgn_quiesce_trigger, kgn_data::kgn_reaper_lock, kgn_data::kgn_reaper_waitq, kgn_data::kgn_shutdown, kgnilnd_data, kgnilnd_reaper_check(), kgnilnd_reaper_poke_with_stick(), KGNILND_SPIN_QUIESCE, kgnilnd_thread_fini(), kgnilnd_tunables, timeout, and unlikely.
Referenced by kgnilnd_base_startup().
void kgnilnd_reaper_check (int idx)
Definition at line 2983 of file gnilnd_cb.c.
References INIT_LIST_HEAD, kgn_data::kgn_peer_conn_lock, kgn_data::kgn_peers, kgnilnd_check_hw_quiesce(), kgnilnd_check_peer_timeouts_locked(), kgnilnd_data, kgnilnd_release_purgatory_list(), kgnilnd_txlist_done(), list_entry, and list_for_each_safe.
Referenced by kgnilnd_reaper().
static void kgnilnd_reaper_poke_with_stick (unsigned long arg) [static]
Definition at line 3027 of file gnilnd_cb.c.
References kgn_data::kgn_reaper_waitq, and kgnilnd_data.
Referenced by kgnilnd_reaper().
int kgnilnd_recv (lnet_ni_t * ni, void * private, lnet_msg_t * lntmsg, int delayed, unsigned int niov, struct kvec * iov, lnet_kiov_t * kiov, unsigned int offset, unsigned int mlen, unsigned int rlen)
Definition at line 2433 of file gnilnd_cb.c.
References __u64, D_BUFFS, D_ERROR, D_NET, D_NETERROR, D_WARNING, ENTRY, kgn_conn::gnc_device, kgn_conn::gnc_error, kgn_conn::gnc_peer, kgn_conn::gnc_state, kgn_device::gnd_lock, GNIDBG_MSG, GNILND_CONN_ESTABLISHED, GNILND_MSG_GET_ACK_REV, GNILND_MSG_GET_REQ, GNILND_MSG_GET_REQ_REV, GNILND_MSG_IMMEDIATE, GNILND_MSG_PUT_ACK, GNILND_MSG_PUT_REQ, GNILND_MSG_PUT_REQ_REV, GNILND_TX_MAPQ, kgn_peer::gnp_nid, GOTO, kgn_rx::grx_conn, kgn_rx::grx_eager, kgn_rx::grx_msg, kgn_tunables::kgn_checksum, kgn_tunables::kgn_checksum_dump, kgn_tunables::kgn_max_immediate, kgn_data::kgn_peer_conn_lock, kgnilnd_cksum(), kgnilnd_close_conn(), kgnilnd_consume_rx(), kgnilnd_data, kgnilnd_dump_blob(), kgnilnd_nak_rdma(), kgnilnd_new_tx_msg(), kgnilnd_schedule_device(), kgnilnd_set_tx_id(), kgnilnd_setup_rdma(), kgnilnd_setup_rdma_buffer(), kgnilnd_tunables, kgnilnd_tx_add_state_locked(), kgnilnd_tx_done(), LASSERT, LASSERTF, LBUG, libcfs_debug_dumplog(), libcfs_nid2str(), lnet_copy_flat2iov(), lnet_copy_flat2kiov(), lnet_finalize(), lnet_ni::ni_nid, RETURN, kgn_tx::tx_buffer, kgn_tx::tx_conn, kgn_tx::tx_id, kgn_tx::tx_lntmsg, kgn_tx::tx_msg, kgn_tx::tx_qtime, and kgn_tx_ev_id::txe_cookie.
int kgnilnd_recv_bte_get (kgn_tx_t * tx)
Definition at line 3129 of file gnilnd_cb.c.
References kgnilnd_parse_lnet_rdma(), lnet_copy_flat2kiov(), kgn_tx::tx_buffer, kgn_tx::tx_buffer_copy, kgn_tx::tx_lntmsg, kgn_tx::tx_nob_rdma, and kgn_tx::tx_offset.
Referenced by kgnilnd_check_rdma_cq().
void kgnilnd_release_msg (kgn_conn_t * conn)
Definition at line 2060 of file gnilnd_cb.c.
References CDEBUG, D_NET, kgn_conn::gnc_device, kgn_conn::gnc_ephandle, kgn_device::gnd_cq_mutex, kgn_device::gnd_mutex_delay, GNI_RC_SUCCESS, GNIDBG_SMSG_CREDS, kgnilnd_gl_mutex_lock(), kgnilnd_gl_mutex_unlock(), kgnilnd_smsg_release(), LASSERTF, and timestamp().
Referenced by kgnilnd_check_fma_rx(), kgnilnd_consume_rx(), and kgnilnd_eager_recv().
void kgnilnd_schedule_device (kgn_device_t * dev)
Definition at line 73 of file gnilnd_cb.c.
References kgn_device::gnd_ready, kgn_device::gnd_waitq, GNILND_DEV_IDLE, and GNILND_DEV_IRQ.
Referenced by _kgnilnd_schedule_conn(), kgnilnd_base_shutdown(), kgnilnd_device_callback(), kgnilnd_finish_connect(), kgnilnd_queue_rdma(), kgnilnd_rdma(), kgnilnd_recv(), kgnilnd_schedule_device_timer(), kgnilnd_send_mapped_tx(), and kgnilnd_setup_rdma().
void kgnilnd_schedule_device_timer (unsigned long arg)
Definition at line 87 of file gnilnd_cb.c.
References kgnilnd_schedule_device().
Referenced by kgnilnd_base_startup().
void kgnilnd_schedule_dgram (kgn_device_t * dev)
Definition at line 205 of file gnilnd_cb.c.
References CDEBUG, D_NETTRACE, kgn_device::gnd_dgram_ready, kgn_device::gnd_dgram_waitq, and GNILND_DGRAM_SCHED.
Referenced by kgnilnd_check_peer_timeouts_locked(), kgnilnd_dgram_waitq(), kgnilnd_find_or_create_conn_locked(), and kgnilnd_quiesce_wait().
int kgnilnd_schedule_process_conn (kgn_conn_t * conn, int sched_intent)
Definition at line 127 of file gnilnd_cb.c.
References kgn_conn::gnc_scheduled, GNILND_CONN_IDLE, GNILND_CONN_PROCESS, GNILND_CONN_WANTS_SCHED, kgnilnd_schedule_conn_refheld, and LASSERTF.
Referenced by kgnilnd_process_conns(), and kgnilnd_reset_stack().
int kgnilnd_scheduler (void * arg)
Definition at line 4988 of file gnilnd_cb.c.
References CDEBUG, cfs_block_allsigs(), CFS_FAIL_GNI_SCHED_DEADLINE, CFS_FAIL_TIMEOUT, cfs_time_seconds(), D_INFO, kgn_device::gnd_conn_sem, kgn_device::gnd_n_schedule, kgn_device::gnd_n_yield, kgn_device::gnd_ready, kgn_device::gnd_sched_alive, kgn_device::gnd_waitq, GNILND_DEV_IDLE, GNILND_DEV_IRQ, GNILND_DEV_LOOP, kgn_data::kgn_devices, kgn_data::kgn_last_condresched, kgn_data::kgn_last_scheduled, kgn_tunables::kgn_loops, kgn_data::kgn_ndevs, kgn_data::kgn_quiesce_trigger, kgn_tunables::kgn_sched_nice, kgn_tunables::kgn_sched_timeout, kgn_data::kgn_shutdown, kgnilnd_check_fma_rcv_cq(), kgnilnd_check_fma_send_cq(), kgnilnd_check_rdma_cq(), kgnilnd_data, kgnilnd_hw_hb, kgnilnd_process_conns(), kgnilnd_process_mapped_tx(), kgnilnd_process_rdmaq(), KGNILND_SPIN_QUIESCE, kgnilnd_thread_fini(), kgnilnd_tunables, and unlikely.
Referenced by kgnilnd_base_startup(), and kgnilnd_start_sd_threads().
int kgnilnd_send (lnet_ni_t * ni, void * private, lnet_msg_t * lntmsg)
Definition at line 2109 of file gnilnd_cb.c.
References CDEBUG, CERROR, cfs_memory_pressure_get_and_set(), cfs_memory_pressure_restore(), D_NET, GNILND_MSG_GET_REQ, GNILND_MSG_GET_REQ_REV, GNILND_MSG_IMMEDIATE, GNILND_MSG_PUT_REQ, GNILND_MSG_PUT_REQ_REV, GNILND_REVERSE_GET, GNILND_REVERSE_PUT, lnet_libmd::iov, kgn_tunables::kgn_max_immediate, kgn_tunables::kgn_reverse_rdma, kgnilnd_launch_tx(), kgnilnd_new_tx_msg(), kgnilnd_setup_immediate_buffer(), kgnilnd_setup_rdma_buffer(), kgnilnd_tunables, kgnilnd_tx_done(), lnet_libmd::kiov, LASSERT, LASSERTF, LBUG, libcfs_id2str(), libcfs_nid2str(), lnet_create_reply_msg(), LNET_MAX_IOV, LNET_MD_KIOV, LNET_MSG_ACK, LNET_MSG_GET, LNET_MSG_PUT, LNET_MSG_REPLY, lnet_libmd::md_iov, lnet_libmd::md_length, lnet_libmd::md_niov, lnet_libmd::md_options, lnet_msg::msg_hdr, lnet_msg::msg_iov, lnet_msg::msg_kiov, lnet_msg::msg_len, lnet_msg::msg_md, lnet_msg::msg_niov, lnet_msg::msg_offset, lnet_msg::msg_routing, lnet_msg::msg_target, lnet_msg::msg_target_is_router, lnet_msg::msg_type, lnet_msg::msg_vmflush, lnet_ni::ni_data, lnet_ni::ni_nid, lnet_process_id_t::nid, kgn_tx::tx_lntmsg, and kgn_tx::tx_msg.
static void kgnilnd_send_conn_close (kgn_conn_t * conn) [inline, static]
Definition at line 4632 of file gnilnd_cb.c.
References CDEBUG, CFS_FAIL_CHECK, CFS_FAIL_GNI_CLOSE_SEND, CFS_FAIL_GNI_RX_CLOSE_CLOSED, D_NETTRACE, kgn_conn::gnc_close_recvd, kgn_conn::gnc_close_sent, kgn_conn::gnc_ephandle, kgn_conn::gnc_error, kgn_conn::gnc_peer, kgn_conn::gnc_peer_error, kgn_conn::gnc_state, GNILND_CLOSE_INJECT2, GNILND_CONN_CLOSED, GNILND_MSG_CLOSE, GNILND_TX_FMAQ, GNILND_TX_WAITING_COMPLETION, kgn_net::gnn_ni, kgn_peer::gnp_net, kgn_data::kgn_peer_conn_lock, kgnilnd_data, kgnilnd_new_tx_msg(), kgnilnd_schedule_conn, kgnilnd_sendmsg(), kgnilnd_set_tx_id(), kgnilnd_tx_done(), lnet_ni::ni_nid, kgn_tx::tx_id, kgn_tx::tx_msg, kgn_tx::tx_qtime, kgn_tx::tx_state, and kgn_tx_ev_id::txe_idx.
Referenced by kgnilnd_process_conns().
int kgnilnd_send_mapped_tx (kgn_tx_t * tx, int try_map_if_full)
Definition at line 3596 of file gnilnd_cb.c.
References __u64, CFS_FAIL_CHECK, CFS_FAIL_GNI_GET_REQ_AGAIN, CFS_FAIL_GNI_PUT_ACK_AGAIN, D_NET, kgn_conn::gnc_device, kgn_conn::gnc_list_lock, kgn_device::gnd_lock, kgn_device::gnd_nq_map, GNIDBG_TX, GNILND_MSG_GET_ACK_REV, GNILND_MSG_GET_DONE, GNILND_MSG_GET_DONE_REV, GNILND_MSG_GET_REQ, GNILND_MSG_GET_REQ_REV, GNILND_MSG_PUT_ACK, GNILND_MSG_PUT_DONE, GNILND_MSG_PUT_DONE_REV, GNILND_MSG_PUT_REQ, GNILND_MSG_PUT_REQ_REV, GNILND_TX_FAIL_SMSG, GNILND_TX_FMAQ, GNILND_TX_MAPQ, GNILND_TX_WAITING_COMPLETION, GNILND_TX_WAITING_REPLY, kgnilnd_compute_rdma_cksum(), kgnilnd_map_buffer(), kgnilnd_rdma(), kgnilnd_schedule_device(), kgnilnd_sendmsg(), kgnilnd_tx_add_state_locked(), LBUG, lnet_msg::msg_len, RETURN, kgn_tx::tx_buffer, kgn_tx::tx_conn, kgn_tx::tx_getinfo, kgn_tx::tx_id, kgn_tx::tx_lntmsg, kgn_tx::tx_map_key, kgn_tx::tx_msg, kgn_tx::tx_nob, kgn_tx::tx_putinfo, kgn_tx::tx_state, kgn_tx_ev_id::txe_cookie, and unlikely.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_check_fma_send_cq(), kgnilnd_process_mapped_tx(), and kgnilnd_process_rdmaq().
static int kgnilnd_sendmsg (kgn_tx_t * tx, void * immediate, unsigned int immediatenob, spinlock_t * state_lock, kgn_tx_list_state_t state) [inline, static]
Definition at line 1581 of file gnilnd_cb.c.
References kgn_conn::gnc_device, kgn_conn::gnc_smsg_mutex, kgn_device::gnd_cq_mutex, kgn_device::gnd_mutex_delay, kgnilnd_conn_mutex_lock(), kgnilnd_gl_mutex_lock(), kgnilnd_sendmsg_nolock(), RETURN, timestamp(), and kgn_tx::tx_conn.
Referenced by kgnilnd_process_fmaq(), kgnilnd_send_conn_close(), and kgnilnd_send_mapped_tx().
static int kgnilnd_sendmsg_nolock (kgn_tx_t * tx, void * immediate, unsigned int immediatenob, spinlock_t * state_lock, kgn_tx_list_state_t state) [inline, static]
Definition at line 1417 of file gnilnd_cb.c.
References cfs_duration_sec(), CFS_FAIL_CHECK, CFS_FAIL_GNI_SEND_TIMEOUT, CFS_FAIL_GNI_SMSG_CKSUM1, cfs_fail_val, cfs_time_seconds(), D_CONSOLE, D_NET, D_NETERROR, kgn_conn::gnc_cqid, kgn_conn::gnc_device, kgn_conn::gnc_ephandle, kgn_conn::gnc_last_noop_sent, kgn_conn::gnc_last_tx, kgn_conn::gnc_my_connstamp, kgn_conn::gnc_peer, kgn_conn::gnc_smsg_mutex, kgn_conn::gnc_timeout, kgn_conn::gnc_tx_seq, kgn_device::gnd_cq_mutex, kgn_device::gnd_short_ntx, kgn_device::gnd_short_txbytes, GNI_RC_NOT_DONE, GNI_RC_SUCCESS, GNIDBG_CONN, GNIDBG_SMSG_CREDS, GNIDBG_TOMSG, GNIDBG_TX, GNILND_LASTRX, GNILND_MSG_CLOSE, GNILND_MSG_IMMEDIATE, GNILND_MSG_NOOP, GNILND_TIMEOUTRX, GNILND_TX_FAIL_SMSG, GNILND_TX_LIVE_FMAQ, GNITX_ASSERTF, kgn_peer::gnp_dirty_eps, kgn_peer::gnp_nid, kgn_tunables::kgn_checksum, kgn_tunables::kgn_max_immediate, kgn_tunables::kgn_max_retransmits, kgnilnd_cksum(), kgnilnd_conn_mutex_unlock(), kgnilnd_gl_mutex_unlock(), kgnilnd_peer_alive(), kgnilnd_schedule_conn, kgnilnd_smsg_send(), kgnilnd_tunables, kgnilnd_tx_add_state_locked(), kgnilnd_tx_should_retry(), LASSERTF, libcfs_nid2str(), msg, now(), timeout, kgn_tx::tx_conn, kgn_tx::tx_id, kgn_tx::tx_msg, kgn_tx::tx_retrans, kgn_tx::tx_state, kgn_tx_ev_id::txe_idx, kgn_tx_ev_id::txe_smsg_id, and unlikely.
Referenced by kgnilnd_sendmsg(), and kgnilnd_sendmsg_trylock().
static int kgnilnd_sendmsg_trylock (kgn_tx_t * tx, void * immediate, unsigned int immediatenob, spinlock_t * state_lock, kgn_tx_list_state_t state) [inline, static]
Definition at line 1604 of file gnilnd_cb.c.
References kgn_conn::gnc_device, kgn_conn::gnc_list_lock, kgn_conn::gnc_peer, kgn_conn::gnc_smsg_mutex, kgn_device::gnd_cq_mutex, kgn_device::gnd_fast_block, kgn_device::gnd_fast_ok, kgn_device::gnd_fast_try, kgn_device::gnd_mutex_delay, kgn_device::gnd_ready, GNILND_DEV_LOOP, GNILND_TX_FMAQ, GNILND_TX_WAITING_COMPLETION, kgn_peer::gnp_dirty_eps, kgn_data::kgn_quiesce_trigger, kgnilnd_data, kgnilnd_sendmsg_nolock(), kgnilnd_trylock(), RETURN, timestamp(), kgn_tx::tx_buffer, kgn_tx::tx_conn, kgn_tx::tx_nob, kgn_tx::tx_qtime, kgn_tx::tx_state, and unlikely.
Referenced by kgnilnd_queue_tx().
int kgnilnd_set_tx_id (kgn_tx_t * tx, kgn_conn_t * conn)
Definition at line 1294 of file gnilnd_cb.c.
References D_NET, kgn_conn::gnc_cqid, kgn_conn::gnc_next_tx, kgn_conn::gnc_tx_bits, kgn_conn::gnc_tx_lock, kgn_conn::gnc_tx_ref_table, kgn_conn::gnc_tx_seq, GNIDBG_TX, GNILND_MAX_MSG_ID, LASSERTF, kgn_tx::tx_conn, kgn_tx::tx_id, kgn_tx_ev_id::txe_chips, kgn_tx_ev_id::txe_cqid, and kgn_tx_ev_id::txe_idx.
Referenced by kgnilnd_process_fmaq(), kgnilnd_queue_tx(), kgnilnd_recv(), kgnilnd_send_conn_close(), and kgnilnd_setup_rdma().
int kgnilnd_setup_immediate_buffer (kgn_tx_t * tx, unsigned int niov, struct kvec * iov, lnet_kiov_t * kiov, unsigned int offset, unsigned int nob)
Definition at line 493 of file gnilnd_cb.c.
References CERROR, CFS_FAIL_CHECK, CFS_FAIL_GNI_SMSG_CKSUM2, CNETERR, D_BUFFS, D_NET, GNIDBG_TX, GNILND_BUF_IMMEDIATE, GNILND_BUF_IMMEDIATE_KIOV, GNILND_BUF_NONE, GNILND_MAX_IMMEDIATE, kgn_tunables::kgn_checksum, kgn_tunables::kgn_checksum_dump, kgn_data::kgn_nkmap_short, kgn_data::kgn_nvmap_short, kgnilnd_cksum(), kgnilnd_data, kgnilnd_dump_blob(), kgnilnd_tunables, lnet_kiov_t::kiov_len, lnet_kiov_t::kiov_offset, lnet_kiov_t::kiov_page, LASSERT, LASSERTF, msg, RETURN, kgn_tx::tx_buffer, kgn_tx::tx_buftype, kgn_tx::tx_imm_pages, kgn_tx::tx_msg, kgn_tx::tx_nob, kgn_tx::tx_phys, and unlikely.
Referenced by kgnilnd_send().
int kgnilnd_setup_phys_buffer (kgn_tx_t * tx, int nkiov, lnet_kiov_t * kiov, unsigned int offset, unsigned int nob)
Definition at line 636 of file gnilnd_cb.c.
References gni_mem_segment::address, CDEBUG, CERROR, CFS_FAIL_CHECK, CFS_FAIL_GNI_PHYS_SETUP, D_BUFFS, D_MALLOC, D_NET, error, GNIDBG_TX, GNILND_BUF_NONE, GNILND_BUF_PHYS_UNMAPPED, GOTO, kgn_data::kgn_tx_phys_cache, kgnilnd_data, lnet_kiov_t::kiov_len, lnet_kiov_t::kiov_offset, lnet_kiov_t::kiov_page, LASSERT, LASSERTF, LNET_MAX_IOV, kgn_tx::tx_buffer, kgn_tx::tx_buftype, kgn_tx::tx_nob, kgn_tx::tx_phys, and kgn_tx::tx_phys_npages.
Referenced by kgnilnd_setup_rdma_buffer().
void kgnilnd_setup_rdma (lnet_ni_t * ni, kgn_rx_t * rx, lnet_msg_t * lntmsg, int mlen)
Definition at line 2281 of file gnilnd_cb.c.
References CERROR, kgn_conn::gnc_device, kgn_device::gnd_lock, GNILND_MSG_GET_DONE, GNILND_MSG_GET_REQ, GNILND_MSG_PUT_DONE_REV, GNILND_MSG_PUT_REQ_REV, GNILND_TX_MAPQ, kgn_rx::grx_conn, kgn_rx::grx_msg, kgnilnd_msgtype2str(), kgnilnd_nak_rdma(), kgnilnd_new_tx_msg(), kgnilnd_schedule_device(), kgnilnd_set_tx_id(), kgnilnd_setup_rdma_buffer(), kgnilnd_tx_add_state_locked(), kgnilnd_tx_done(), LBUG, lnet_finalize(), lnet_msg::msg_iov, lnet_msg::msg_kiov, lnet_msg::msg_len, lnet_msg::msg_niov, lnet_msg::msg_offset, lnet_ni::ni_nid, kgn_tx::tx_conn, kgn_tx::tx_getinfo, and kgn_tx::tx_lntmsg.
Referenced by kgnilnd_recv().
static int kgnilnd_setup_rdma_buffer (kgn_tx_t * tx, unsigned int niov, struct kvec * iov, lnet_kiov_t * kiov, unsigned int offset, unsigned int nob) [inline, static]
Definition at line 748 of file gnilnd_cb.c.
References kgnilnd_setup_phys_buffer(), kgnilnd_setup_virt_buffer(), and LASSERTF.
Referenced by kgnilnd_recv(), kgnilnd_send(), and kgnilnd_setup_rdma().
int kgnilnd_setup_virt_buffer (kgn_tx_t * tx, unsigned int niov, struct kvec * iov, unsigned int offset, unsigned int nob)
Definition at line 608 of file gnilnd_cb.c.
References CERROR, GNILND_BUF_NONE, GNILND_BUF_VIRT_UNMAPPED, LASSERT, kgn_tx::tx_buffer, kgn_tx::tx_buftype, and kgn_tx::tx_nob.
Referenced by kgnilnd_setup_rdma_buffer().
static void kgnilnd_swab_rdma_desc (kgn_rdma_desc_t * d) [inline, static]
Definition at line 3969 of file gnilnd_cb.c.
References __swab32s, and __swab64s.
Referenced by kgnilnd_check_fma_rx().
void kgnilnd_tx_done (kgn_tx_t * tx, int completion)
Definition at line 1199 of file gnilnd_cb.c.
References cfs_duration_sec(), D_NETERROR, kgn_conn::gnc_peer, kgn_conn::gnc_tx_bits, kgn_conn::gnc_tx_lock, kgn_conn::gnc_tx_ref_table, GNIDBG_TOMSG, GNILND_BUF_NONE, GNILND_MSG_GET_REQ, GNILND_MSG_NONE, GNILND_TX_QUIET_ERROR, kgn_net::gnn_ni, kgn_peer::gnp_net, kgn_peer::gnp_nid, kgnilnd_conn_clean_errno(), kgnilnd_free_tx(), kgnilnd_tx_state2str(), kgnilnd_unmap_buffer(), LASSERT, LASSERTF, libcfs_nid2str(), lnet_finalize(), kgn_tx::tx_buftype, kgn_tx::tx_conn, kgn_tx::tx_id, kgn_tx::tx_list_state, kgn_tx::tx_lntmsg, kgn_tx::tx_msg, kgn_tx::tx_qtime, kgn_tx::tx_state, kgn_tx_ev_id::txe_idx, and kgn_tx_ev_id::txe_smsg_id.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_check_fma_send_cq(), kgnilnd_check_rdma_cq(), kgnilnd_complete_closed_conn(), kgnilnd_complete_tx(), kgnilnd_launch_tx(), kgnilnd_process_fmaq(), kgnilnd_process_mapped_tx(), kgnilnd_queue_tx(), kgnilnd_rdma(), kgnilnd_recv(), kgnilnd_send(), kgnilnd_send_conn_close(), kgnilnd_setup_rdma(), and kgnilnd_txlist_done().
static int kgnilnd_tx_should_retry (kgn_conn_t * conn, kgn_tx_t * tx) [inline, static]
Definition at line 1347 of file gnilnd_cb.c.
References cfs_duration_sec(), D_ERROR, D_NET, D_NETERROR, kgn_conn::gnc_last_rx, kgn_conn::gnc_last_rx_cq, kgn_conn::gnc_last_tx, kgn_conn::gnc_last_tx_cq, kgn_conn::gnc_peer, kgn_conn::gnc_tx_retrans, GNIDBG_SMSG_CREDS, GNIDBG_TOMSG, kgn_peer::gnp_nid, kgn_tunables::kgn_max_retransmits, kgnilnd_close_conn(), kgnilnd_tunables, libcfs_nid2str(), now(), RETURN, kgn_tx::tx_conn, kgn_tx::tx_cred_wait, kgn_tx::tx_id, kgn_tx::tx_msg, kgn_tx::tx_retrans, and kgn_tx::tx_state.
Referenced by kgnilnd_sendmsg_nolock().
void kgnilnd_txlist_done (struct list_head * txlist, int error)
Definition at line 1276 of file gnilnd_cb.c.
References GNILND_TX_QUIET_ERROR, kgnilnd_tx_done(), list_del_init(), list_empty(), list_for_each_entry_safe, kgn_tx::tx_list, and kgn_tx::tx_state.
Referenced by kgnilnd_del_conn_or_peer(), kgnilnd_reaper_check(), and kgnilnd_report_node_state().
void kgnilnd_unmap_buffer (kgn_tx_t * tx, int error)
Definition at line 1128 of file gnilnd_cb.c.
References CLASSERT, D_NET, kgn_conn::gnc_device, kgn_conn::gnc_state, kgn_device::gnd_handle, GNI_RC_SUCCESS, GNIDBG_TX, GNILND_BUF_IMMEDIATE, GNILND_BUF_IMMEDIATE_KIOV, GNILND_BUF_NONE, GNILND_BUF_PHYS_MAPPED, GNILND_BUF_PHYS_UNMAPPED, GNILND_BUF_VIRT_MAPPED, GNILND_BUF_VIRT_UNMAPPED, GNILND_CONN_ESTABLISHED, GNILND_NOPURG, GNILND_TIMEOUT2DEADMAN, kgnilnd_add_purgatory_tx(), kgnilnd_check_purgatory_conn(), kgnilnd_mem_del_map_list(), kgnilnd_mem_deregister(), LASSERT, LASSERTF, LBUG, LPX64, gni_mem_handle::qword1, gni_mem_handle::qword2, kgn_tx::tx_buffer, kgn_tx::tx_buffer_copy, kgn_tx::tx_buffer_copy_map_key, kgn_tx::tx_buftype, kgn_tx::tx_conn, kgn_tx::tx_imm_pages, kgn_tx::tx_map_key, and kgn_tx::tx_phys.
Referenced by kgnilnd_rdma(), and kgnilnd_tx_done().
void kgnilnd_update_reaper_timeout (long timeout)
Definition at line 3014 of file gnilnd_cb.c.
References kgn_data::kgn_new_min_timeout, kgn_data::kgn_reaper_lock, kgnilnd_data, and LASSERT.
Referenced by kgnilnd_create_conn(), and kgnilnd_set_conn_params().
static int kgnilnd_verify_rdma_cksum (kgn_tx_t * tx, __u16 rx_cksum, int put_len) [inline, static]
Definition at line 850 of file gnilnd_cb.c.
References cksum, D_BUFFS, D_NETERROR, D_WARNING, GNIDBG_MSG, GNILND_MSG_GET_ACK_REV, GNILND_MSG_GET_DONE_REV, GNILND_MSG_GET_REQ, GNILND_MSG_PUT_ACK, GNILND_MSG_PUT_DONE_REV, GNILND_MSG_PUT_REQ_REV, GNITX_ASSERTF, kgn_tunables::kgn_checksum, kgn_tunables::kgn_checksum_dump, kgnilnd_cksum(), kgnilnd_cksum_kiov(), kgnilnd_dump_blob(), kgnilnd_msgtype2str(), kgnilnd_parse_lnet_rdma(), kgnilnd_tunables, libcfs_debug_dumplog(), kgn_tx::tx_buffer, kgn_tx::tx_lntmsg, and kgn_tx::tx_msg.
Referenced by kgnilnd_check_rdma_cq(), and kgnilnd_finalize_rx_done().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.