Lustre: lnet/klnds/gnilnd/gnilnd_debug.c File Reference
lnet/klnds/gnilnd/gnilnd_debug.c File Reference
#include "gnilnd.h"
Functions
void _kgnilnd_debug_msg (kgn_msg_t *msg, struct libcfs_debug_msg_data *msgdata, const char *fmt,...)
void _kgnilnd_debug_conn (kgn_conn_t *conn, struct libcfs_debug_msg_data *msgdata, const char *fmt,...)
void _kgnilnd_debug_tx (kgn_tx_t *tx, struct libcfs_debug_msg_data *msgdata, const char *fmt,...)
void _kgnilnd_api_rc_lbug (const char *rcstr, int rc, struct libcfs_debug_msg_data *msgdata, const char *fmt,...)
Function Documentation
void _kgnilnd_api_rc_lbug (const char * rcstr, int rc, struct libcfs_debug_msg_data * msgdata, const char * fmt, ...)
Definition at line 99 of file gnilnd_debug.c.
References LBUG, and libcfs_debug_vmsg2().
void _kgnilnd_debug_conn (kgn_conn_t * conn, struct libcfs_debug_msg_data * msgdata, const char * fmt, ...)
Definition at line 42 of file gnilnd_debug.c.
References cfs_duration_sec(), kgn_conn::gnc_cqid, kgn_conn::gnc_device, kgn_conn::gnc_last_noop_cq, kgn_conn::gnc_last_noop_sent, kgn_conn::gnc_last_noop_want, kgn_conn::gnc_last_rx, kgn_conn::gnc_last_rx_cq, kgn_conn::gnc_last_sched_ask, kgn_conn::gnc_last_sched_do, kgn_conn::gnc_last_tx, kgn_conn::gnc_last_tx_cq, kgn_conn::gnc_peer, kgn_conn::gnc_rx_seq, kgn_conn::gnc_timeout, kgn_conn::gnc_tx_seq, kgn_device::gnd_sched_alive, kgn_peer::gnp_nid, kgnilnd_conn_state2str(), libcfs_debug_vmsg2(), and libcfs_nid2str().
void _kgnilnd_debug_msg (kgn_msg_t * msg, struct libcfs_debug_msg_data * msgdata, const char * fmt, ...)
Definition at line 25 of file gnilnd_debug.c.
References kgnilnd_msgtype2str(), and libcfs_debug_vmsg2().
void _kgnilnd_debug_tx (kgn_tx_t * tx, struct libcfs_debug_msg_data * msgdata, const char * fmt, ...)
Definition at line 73 of file gnilnd_debug.c.
References cfs_duration_sec(), kgn_conn::gnc_peer, kgn_peer::gnp_nid, kgnilnd_msgtype2str(), kgnilnd_tx_state2str(), libcfs_debug_vmsg2(), libcfs_nid2str(), LPX64, kgn_tx::tx_buftype, kgn_tx::tx_conn, kgn_tx::tx_id, kgn_tx::tx_list_p, kgn_tx::tx_list_state, kgn_tx::tx_msg, kgn_tx::tx_qtime, kgn_tx::tx_retrans, kgn_tx::tx_state, kgn_tx_ev_id::txe_cookie, kgn_tx_ev_id::txe_cqid, kgn_tx_ev_id::txe_idx, and kgn_tx_ev_id::txe_smsg_id.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.