Lustre: log
log
Data Structures
struct plain_handle_data
struct cat_handle_data
struct llog_process_data
struct llog_process_cat_data
struct llog_operations
struct llog_handle
struct llog_ctxt
struct llog_cfg_rec
Defines
#define LOG_NAME_LIMIT(logname, name) snprintf(logname, sizeof(logname), "LOGS/%s", name)
#define LLOG_EEMPTY 4711
#define LLOG_FLAG_NODEAMON 0x0001
#define LLOG_CTXT_FLAG_UNINITIALIZED 0x00000001
#define LLOG_CTXT_FLAG_STOP 0x00000002
#define LLOG_CTXT_FLAG_NORMAL_FID 0x00000004
#define LLOG_PROC_BREAK 0x0001
#define LLOG_DEL_RECORD 0x0002
#define LLOG_DEL_PLAIN 0x0003
Enumerations
enum llog_open_param { LLOG_OPEN_EXISTS = 0x0000, LLOG_OPEN_NEW = 0x0001 }
enum { LLOG_NEXT_IDX = -1, LLOG_HEADER_IDX = 0 }
Functions
int llog_init_handle (const struct lu_env *env, struct llog_handle *handle, int flags, struct obd_uuid *uuid)
int llog_copy_handler (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *rec, void *data)
int llog_process (const struct lu_env *env, struct llog_handle *loghandle, llog_cb_t cb, void *data, void *catdata)
int llog_process_or_fork (const struct lu_env *env, struct llog_handle *loghandle, llog_cb_t cb, void *data, void *catdata, bool fork)
int llog_reverse_process (const struct lu_env *env, struct llog_handle *loghandle, llog_cb_t cb, void *data, void *catdata)
int llog_cancel_rec (const struct lu_env *env, struct llog_handle *loghandle, int index)
int llog_open (const struct lu_env *env, struct llog_ctxt *ctxt, struct llog_handle **lgh, struct llog_logid *logid, char *name, enum llog_open_param open_param)
int llog_close (const struct lu_env *env, struct llog_handle *cathandle)
int llog_is_empty (const struct lu_env *env, struct llog_ctxt *ctxt, char *name)
Helper function to get the llog size in records.
int llog_backup (const struct lu_env *env, struct obd_device *obd, struct llog_ctxt *ctxt, struct llog_ctxt *bak_ctxt, char *name, char *backup)
int llog_read_header (const struct lu_env *env, struct llog_handle *handle, const struct obd_uuid *uuid)
__u64 llog_size (const struct lu_env *env, struct llog_handle *llh)
int llog_cat_close (const struct lu_env *env, struct llog_handle *cathandle)
int llog_cat_add_rec (const struct lu_env *env, struct llog_handle *cathandle, struct llog_rec_hdr *rec, struct llog_cookie *reccookie, struct thandle *th)
int llog_cat_declare_add_rec (const struct lu_env *env, struct llog_handle *cathandle, struct llog_rec_hdr *rec, struct thandle *th)
int llog_cat_add (const struct lu_env *env, struct llog_handle *cathandle, struct llog_rec_hdr *rec, struct llog_cookie *reccookie)
int llog_cat_cancel_records (const struct lu_env *env, struct llog_handle *cathandle, int count, struct llog_cookie *cookies)
int llog_cat_process_or_fork (const struct lu_env *env, struct llog_handle *cat_llh, llog_cb_t cat_cb, llog_cb_t cb, void *data, int startcat, int startidx, bool fork)
int llog_cat_process (const struct lu_env *env, struct llog_handle *cat_llh, llog_cb_t cb, void *data, int startcat, int startidx)
__u64 llog_cat_size (const struct lu_env *env, struct llog_handle *cat_llh)
int llog_cat_reverse_process (const struct lu_env *env, struct llog_handle *cat_llh, llog_cb_t cb, void *data)
int llog_setup (const struct lu_env *env, struct obd_device *obd, struct obd_llog_group *olg, int index, struct obd_device *disk_obd, struct llog_operations *op)
int __llog_ctxt_put (const struct lu_env *env, struct llog_ctxt *ctxt)
int llog_cleanup (const struct lu_env *env, struct llog_ctxt *)
int llog_sync (struct llog_ctxt *ctxt, struct obd_export *exp, int flags)
int llog_cancel (const struct lu_env *env, struct llog_ctxt *ctxt, struct llog_cookie *cookies, int flags)
int llog_ioctl (const struct lu_env *env, struct llog_ctxt *ctxt, int cmd, struct obd_ioctl_data *data)
int llog_catalog_list (const struct lu_env *env, struct dt_device *d, int count, struct obd_ioctl_data *data, const struct lu_fid *fid)
int llog_initiator_connect (struct llog_ctxt *ctxt)
int llog_osd_get_cat_list (const struct lu_env *env, struct dt_device *d, int idx, int count, struct llog_catid *idarray, const struct lu_fid *fid)
Read the special file which contains the list of llog catalogs IDs.
int llog_osd_put_cat_list (const struct lu_env *env, struct dt_device *d, int idx, int count, struct llog_catid *idarray, const struct lu_fid *fid)
Write the special file which contains the list of llog catalogs IDs.
static int llog_obd2ops (struct llog_ctxt *ctxt, struct llog_operations **lop)
static int llog_handle2ops (struct llog_handle *loghandle, struct llog_operations **lop)
static int llog_data_len (int len)
static int llog_get_size (struct llog_handle *loghandle)
static struct llog_ctxt * llog_ctxt_get (struct llog_ctxt *ctxt)
static void llog_ctxt_put (struct llog_ctxt *ctxt)
static void llog_group_init (struct obd_llog_group *olg)
static int llog_group_set_ctxt (struct obd_llog_group *olg, struct llog_ctxt *ctxt, int index)
static struct llog_ctxt * llog_group_get_ctxt (struct obd_llog_group *olg, int index)
static void llog_group_clear_ctxt (struct obd_llog_group *olg, int index)
static struct llog_ctxt * llog_get_context (struct obd_device *obd, int index)
static int llog_group_ctxt_null (struct obd_llog_group *olg, int index)
static int llog_ctxt_null (struct obd_device *obd, int index)
static int llog_next_block (const struct lu_env *env, struct llog_handle *loghandle, int *cur_idx, int next_idx, __u64 *cur_offset, void *buf, int len)
static int llog_prev_block (const struct lu_env *env, struct llog_handle *loghandle, int prev_idx, void *buf, int len)
static int llog_connect (struct llog_ctxt *ctxt, struct llog_logid *logid, struct llog_gen *gen, struct obd_uuid *uuid)
static int llog_is_full (struct llog_handle *llh)
struct llog_cfg_rec * lustre_cfg_rec_new (int cmd, struct lustre_cfg_bufs *bufs)
void lustre_cfg_rec_free (struct llog_cfg_rec *lcr)
int llog_exist (struct llog_handle *loghandle)
new llog API
int llog_declare_create (const struct lu_env *env, struct llog_handle *loghandle, struct thandle *th)
int llog_create (const struct lu_env *env, struct llog_handle *handle, struct thandle *th)
int llog_trans_destroy (const struct lu_env *env, struct llog_handle *handle, struct thandle *th)
int llog_destroy (const struct lu_env *env, struct llog_handle *handle)
int llog_declare_write_rec (const struct lu_env *env, struct llog_handle *handle, struct llog_rec_hdr *rec, int idx, struct thandle *th)
int llog_write_rec (const struct lu_env *env, struct llog_handle *handle, struct llog_rec_hdr *rec, struct llog_cookie *logcookies, int idx, struct thandle *th)
int llog_add (const struct lu_env *env, struct llog_handle *lgh, struct llog_rec_hdr *rec, struct llog_cookie *logcookies, struct thandle *th)
int llog_declare_add (const struct lu_env *env, struct llog_handle *lgh, struct llog_rec_hdr *rec, struct thandle *th)
int lustre_process_log (struct super_block *sb, char *logname, struct config_llog_instance *cfg)
Get a config log from the MGS and process it.
int lustre_end_log (struct super_block *sb, char *logname, struct config_llog_instance *cfg)
int llog_open_create (const struct lu_env *env, struct llog_ctxt *ctxt, struct llog_handle **res, struct llog_logid *logid, char *name)
Helper function to open llog or create it if doesn't exist.
int llog_erase (const struct lu_env *env, struct llog_ctxt *ctxt, struct llog_logid *logid, char *name)
Helper function to delete existent llog.
int llog_write (const struct lu_env *env, struct llog_handle *loghandle, struct llog_rec_hdr *rec, int idx)
Variables
struct llog_operations llog_osd_ops
struct llog_operations llog_common_cat_ops
Define Documentation
#define LLOG_CTXT_FLAG_NORMAL_FID 0x00000004
Definition at line 306 of file lustre_log.h.
Referenced by llog_cat_new_log(), llog_open_create(), llog_osd_close(), llog_osd_create(), llog_osd_declare_create(), llog_osd_declare_destroy(), llog_osd_destroy(), llog_osd_open(), and lod_sub_prep_llog().
#define LLOG_CTXT_FLAG_STOP 0x00000002
Definition at line 302 of file lustre_log.h.
#define LLOG_CTXT_FLAG_UNINITIALIZED 0x00000001
Definition at line 301 of file lustre_log.h.
Referenced by llog_setup().
#define LLOG_DEL_PLAIN 0x0003
Definition at line 330 of file lustre_log.h.
Referenced by llog_cancel_rec(), llog_cat_cancel_records(), llog_cat_process_cb(), llog_cat_reverse_process_cb(), llog_process(), and llog_test_7_sub().
#define LLOG_DEL_RECORD 0x0002
Definition at line 329 of file lustre_log.h.
Referenced by llog_process_thread(), llog_reverse_process(), mdt_coordinator_cb(), test_2_cancel_cb(), and test_7_cancel_cb().
#define LLOG_EEMPTY 4711
Definition at line 61 of file lustre_log.h.
Referenced by llog_cancel_rec_cb(), llog_check_cb(), llog_ioctl(), llog_osd_read_header(), llog_print_cb(), llog_read_header(), llog_test_10(), and llog_test_5().
#define LLOG_FLAG_NODEAMON 0x0001
Definition at line 112 of file lustre_log.h.
#define LLOG_PROC_BREAK 0x0001
Definition at line 328 of file lustre_log.h.
Referenced by changelog_init_cb(), changelog_user_init_cb(), llog_changelog_cancel_cb(), llog_process_thread(), llog_reverse_process(), mdt_agent_record_update_cb(), mdt_hsm_actions_proc_show(), osp_sync_process_queues(), and osp_sync_thread().
#define LOG_NAME_LIMIT (logname, name) snprintf(logname, sizeof(logname), "LOGS/%s", name)
Definition at line 59 of file lustre_log.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
LLOG_NEXT_IDX
LLOG_HEADER_IDX
Definition at line 520 of file lustre_log.h.
enum llog_open_param
Enumerator:
LLOG_OPEN_EXISTS
LLOG_OPEN_NEW
Definition at line 63 of file lustre_log.h.
Function Documentation
int __llog_ctxt_put (const struct lu_env * env, struct llog_ctxt * ctxt)
Definition at line 72 of file llog_obd.c.
References cleanup(), CTXTP, LASSERTF, llog_ctxt_destroy(), llog_ctxt::loc_idx, llog_ctxt::loc_obd, llog_ctxt::loc_olg, llog_ctxt::loc_refcount, obd_device::obd_dev_lock, obd_device::obd_set_up, obd_device::obd_starting, obd_device::obd_stopping, obd_llog_group::olg_ctxts, obd_llog_group::olg_lock, and obd_llog_group::olg_waitq.
Referenced by llog_cleanup(), llog_ctxt_put(), and mgc_process_cfg_log().
int llog_add (const struct lu_env * env, struct llog_handle * lgh, struct llog_rec_hdr * rec, struct llog_cookie * logcookies, struct thandle * th)
Definition at line 918 of file llog.c.
References cfs_cap_lower(), cfs_cap_raise(), cfs_cap_raised(), CFS_CAP_SYS_RESOURCE, ENTRY, llog_handle::lgh_logops, llog_operations::lop_add, and RETURN.
Referenced by mdd_changelog_store(), osp_sync_add_rec(), and sub_updates_write().
int llog_backup (const struct lu_env * env, struct obd_device * obd, struct llog_ctxt * ctxt, struct llog_ctxt * bak_ctxt, char * name, char * backup)
Definition at line 1187 of file llog.c.
References CERROR, ENTRY, GOTO, llog_handle::lgh_obj, llog_close(), llog_copy_handler(), llog_erase(), LLOG_F_IS_PLAIN, llog_init_handle(), llog_open(), llog_open_create(), LLOG_OPEN_EXISTS, llog_process_or_fork(), obd_device::obd_name, and RETURN.
Referenced by mgc_llog_local_copy(), and mgs_replace_nids_log().
int llog_cancel (const struct lu_env * env, struct llog_ctxt * ctxt, struct llog_cookie * cookies, int flags)
Definition at line 237 of file llog_obd.c.
References CERROR, CTXT_CHECK_OP, CTXTP, ENTRY, and RETURN.
Referenced by mdd_changelog_llog_cancel().
int llog_cancel_rec (const struct lu_env * env, struct llog_handle * loghandle, int index)
Definition at line 197 of file llog.c.
References CDEBUG, CERROR, llog_handle::chd, cat_handle_data::chd_current_log, D_RPCTRACE, dt_object::do_lu, DOSTID, dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), ENTRY, ext2_clear_bit, ext2_set_bit, GOTO, LASSERT, llog_cookie::lgc_index, llog_handle::lgh_ctxt, llog_handle::lgh_hdr, llog_handle::lgh_hdr_mutex, llog_handle::lgh_id, llog_handle::lgh_last_idx, llog_handle::lgh_lock, llog_handle::lgh_obj, llog_thread_info::lgi_cookie, llog_logid::lgl_ogen, llog_logid::lgl_oi, llog_log_hdr::llh_count, llog_log_hdr::llh_flags, llog_log_hdr::llh_hdr, llog_declare_destroy(), llog_declare_write_rec(), LLOG_DEL_PLAIN, LLOG_F_ZAP_WHEN_EMPTY, LLOG_HDR_BITMAP, LLOG_HDR_BITMAP_SIZE, LLOG_HEADER_IDX, llog_info(), llog_trans_destroy(), llog_write_rec(), lu_object::lo_dev, llog_ctxt::loc_obd, lu2dt_dev(), obd_device::obd_name, llog_handle::phd, plain_handle_data::phd_cat_handle, POSTID, RETURN, thandle::th_wait_submit, and llog_handle::u.
Referenced by llog_cat_cancel_records(), llog_cat_cleanup(), llog_ioctl(), llog_process_thread(), and llog_reverse_process().
int llog_cat_add (const struct lu_env * env, struct llog_handle * cathandle, struct llog_rec_hdr * rec, struct llog_cookie * reccookie)
Definition at line 631 of file llog_cat.c.
References dt_object::do_lu, dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), GOTO, LASSERT, llog_handle::lgh_ctxt, llog_handle::lgh_obj, llog_cat_add_rec(), llog_cat_declare_add_rec(), lu_object::lo_dev, llog_ctxt::loc_exp, lu2dt_dev(), and RETURN.
Referenced by llog_test_10(), llog_test_4(), llog_test_5(), llog_test_8(), mdd_changelog_user_register(), mdd_changelog_write_header(), mdt_agent_record_add(), and osp_sync_llog_init().
int llog_cat_add_rec (const struct lu_env * env, struct llog_handle * cathandle, struct llog_rec_hdr * rec, struct llog_cookie * reccookie, struct thandle * th)
Definition at line 425 of file llog_cat.c.
References CDEBUG_LIMIT, CERROR, llog_handle::chd, cat_handle_data::chd_current_log, D_ERROR, D_HA, ENTRY, GOTO, LASSERT, llog_handle::lgh_ctxt, llog_handle::lgh_lock, llog_cat_current_log(), llog_cat_new_log(), llog_exist(), llog_is_full(), LLOG_NEXT_IDX, llog_write_rec(), llog_ctxt::loc_chunk_size, llog_ctxt::loc_obd, llog_rec_hdr::lrh_len, obd_device::obd_name, RETURN, and llog_handle::u.
Referenced by llog_cat_add(), mdd_changelog_llog_init(), mdd_init(), and osp_init().
int llog_cat_cancel_records (const struct lu_env * env, struct llog_handle * cathandle, int count, struct llog_cookie * cookies)
Definition at line 673 of file llog_cat.c.
References CERROR, DOSTID, ENTRY, llog_cookie::lgc_index, llog_cookie::lgc_lgl, llog_handle::lgh_ctxt, llog_logid::lgl_oi, llog_cancel_rec(), llog_cat_cleanup(), llog_cat_id2handle(), LLOG_DEL_PLAIN, llog_handle_put(), llog_ctxt::loc_obd, obd_device::obd_name, llog_handle::phd, plain_handle_data::phd_cookie, POSTID, RETURN, and llog_handle::u.
Referenced by distribute_txn_cancel_records(), llog_cancel_rec_cb(), llog_changelog_cancel_cb(), llog_ioctl(), llog_test_4(), mdd_changelog_user_purge_cb(), osp_sync_process_committed(), and osp_sync_process_record().
int llog_cat_close (const struct lu_env * env, struct llog_handle * cathandle)
Definition at line 271 of file llog_cat.c.
References CERROR, llog_handle::chd, cat_handle_data::chd_head, ENTRY, llog_cookie::lgc_index, llog_handle::lgh_ctxt, llog_handle::lgh_hdr, llog_handle::lgh_obj, list_del_init(), list_for_each_entry_safe, llog_log_hdr::llh_count, llog_log_hdr::llh_flags, llog_cat_cleanup(), llog_close(), llog_destroy(), LLOG_F_ZAP_WHEN_EMPTY, llog_ctxt::loc_handle, llog_ctxt::loc_obd, obd_device::obd_name, llog_handle::phd, plain_handle_data::phd_cookie, plain_handle_data::phd_entry, RETURN, and llog_handle::u.
Referenced by llog_ioctl(), llog_origin_close(), llog_test_10(), llog_test_4(), llog_test_5(), llog_test_8(), lod_sub_fini_llog(), lod_sub_prep_llog(), lod_sub_recovery_thread(), mdc_changelog_send_thread(), mdd_changelog_fini(), mdd_changelog_llog_init(), mdd_hsm_actions_llog_fini(), mdd_hsm_actions_llog_init(), osp_sync_llog_fini(), osp_sync_llog_init(), and osp_sync_thread().
int llog_cat_declare_add_rec (const struct lu_env * env, struct llog_handle * cathandle, struct llog_rec_hdr * rec, struct thandle * th)
Definition at line 479 of file llog_cat.c.
References llog_handle::chd, cat_handle_data::chd_current_log, cat_handle_data::chd_head, cat_handle_data::chd_next_log, dt_object_remote(), ENTRY, GOTO, llog_handle::lgh_ctxt, llog_handle::lgh_lock, llog_handle::lgh_obj, llog_handle::lgh_stale, llog_thread_info::lgi_logid, llog_logid_rec::lid_hdr, list_add_tail(), llog_cat_new_log(), llog_cat_update_header(), llog_declare_create(), llog_declare_write_rec(), llog_exist(), llog_info(), llog_open(), LLOG_OPEN_NEW, LLOGH_CAT, LLOGH_LOG, llog_rec_hdr::lrh_len, llog_handle::phd, plain_handle_data::phd_entry, RETURN, and llog_handle::u.
Referenced by llog_cat_add(), mdd_changelog_llog_init(), mdd_init(), and osp_init().
int llog_cat_process (const struct lu_env * env, struct llog_handle * cat_llh, llog_cb_t cb, void * data, int startcat, int startidx)
Definition at line 838 of file llog_cat.c.
References llog_cat_process_cb(), and llog_cat_process_or_fork().
Referenced by cdt_llog_process(), llog_changelog_cancel(), llog_test_10(), llog_test_5(), llog_test_8(), lod_sub_recovery_thread(), mdc_changelog_send_thread(), mdd_changelog_user_purge(), mdd_changelog_users_seq_show(), mdt_hsm_actions_proc_show(), and osp_sync_thread().
int llog_cat_process_or_fork (const struct lu_env * env, struct llog_handle * cat_llh, llog_cb_t cat_cb, llog_cb_t cb, void * data, int startcat, int startidx, bool fork)
Definition at line 796 of file llog_cat.c.
References CWARN, DOSTID, ENTRY, LASSERT, llog_handle::lgh_hdr, llog_handle::lgh_id, llog_handle::lgh_last_idx, llog_logid::lgl_oi, llog_log_hdr::llh_cat_idx, llog_log_hdr::llh_count, llog_log_hdr::llh_flags, LLOG_F_IS_CAT, llog_process_or_fork(), llog_process_cat_data::lpcd_first_idx, llog_process_cat_data::lpcd_last_idx, llog_process_data::lpd_cb, llog_process_data::lpd_data, llog_process_data::lpd_startcat, llog_process_data::lpd_startidx, POSTID, and RETURN.
Referenced by llog_cat_process(), and llog_cat_size().
int llog_cat_reverse_process (const struct lu_env * env, struct llog_handle * cat_llh, llog_cb_t cb, void * data)
Definition at line 958 of file llog_cat.c.
References CWARN, DOSTID, ENTRY, LASSERT, le32_to_cpu, llog_handle::lgh_hdr, llog_handle::lgh_id, llog_handle::lgh_last_idx, llog_logid::lgl_oi, llog_log_hdr::llh_cat_idx, llog_log_hdr::llh_count, llog_log_hdr::llh_flags, llog_cat_reverse_process_cb(), LLOG_F_IS_CAT, llog_reverse_process(), llog_process_cat_data::lpcd_first_idx, llog_process_cat_data::lpcd_last_idx, llog_process_data::lpd_cb, llog_process_data::lpd_data, POSTID, and RETURN.
Referenced by llog_test_5(), and mdd_changelog_llog_init().
__u64 llog_cat_size (const struct lu_env * env, struct llog_handle * cat_llh)
Definition at line 886 of file llog_cat.c.
References __u64, llog_cat_process_or_fork(), llog_cat_size_cb(), llog_size(), and size.
Referenced by mdd_changelog_size_ctxt().
int llog_catalog_list (const struct lu_env * env, struct dt_device * d, int count, struct obd_ioctl_data * data, const struct lu_fid * fid)
Definition at line 432 of file llog_ioctl.c.
References DOSTID, ENTRY, GOTO, obd_ioctl_data::ioc_bulk, obd_ioctl_data::ioc_inllen1, llog_catid::lci_logid, llog_logid::lgl_ogen, llog_logid::lgl_oi, llog_osd_get_cat_list(), OBD_ALLOC_LARGE, OBD_FREE_LARGE, POSTID, RETURN, and size.
Referenced by mdt_iocontrol().
int llog_cleanup (const struct lu_env * env, struct llog_ctxt *)
Definition at line 108 of file llog_obd.c.
References __llog_ctxt_put(), CERROR, ENTRY, l_wait_event, LASSERT, llog_ctxt_put(), llog_group_ctxt_null(), llog_ctxt::loc_idx, llog_ctxt::loc_olg, llog_ctxt::loc_refcount, LWI_INTR, LWI_ON_SIGNAL_NOOP, obd_llog_group::olg_waitq, and RETURN.
Referenced by llog_test_cleanup(), lod_sub_fini_llog(), mdc_llog_finish(), mdd_changelog_fini(), mdd_changelog_llog_init(), mdd_hsm_actions_llog_fini(), mdd_hsm_actions_llog_init(), mgc_llog_fini(), mgc_local_llog_fini(), mgs_device_fini(), mgs_init0(), osp_sync_llog_fini(), osp_sync_llog_init(), and osp_sync_thread().
int llog_close (const struct lu_env * env, struct llog_handle * cathandle)
Definition at line 1120 of file llog.c.
References ENTRY, GOTO, llog_handle2ops(), llog_handle_put(), llog_operations::lop_close, and RETURN.
Referenced by class_config_parse_llog(), llog_backup(), llog_cat_cleanup(), llog_cat_close(), llog_cat_id2handle(), llog_erase(), llog_ioctl(), llog_is_empty(), llog_open_create(), llog_origin_close(), llog_run_tests(), llog_test_1(), llog_test_2(), llog_test_6(), llog_test_7_sub(), llog_test_9_sub(), mgs_get_fsdb_from_llog(), mgs_get_fsdb_srpc_from_llog(), mgs_modify(), mgs_replace_nids_log(), mgs_steal_llog_for_mdt_from_client(), record_end_log(), record_start_log(), sptlrpc_target_local_copy_conf(), and sptlrpc_target_local_read_conf().
static int llog_connect (struct llog_ctxt * ctxt, struct llog_logid * logid, struct llog_gen * gen, struct obd_uuid * uuid) [inline, static]
Definition at line 487 of file lustre_log.h.
References ENTRY, llog_obd2ops(), llog_operations::lop_connect, and RETURN.
int llog_copy_handler (const struct lu_env * env, struct llog_handle * llh, struct llog_rec_hdr * rec, void * data)
Definition at line 1177 of file llog.c.
References LLOG_NEXT_IDX, and llog_write().
Referenced by llog_backup().
int llog_create (const struct lu_env * env, struct llog_handle * handle, struct thandle * th)
Definition at line 840 of file llog.c.
References cfs_cap_lower(), cfs_cap_raise(), cfs_cap_raised(), CFS_CAP_SYS_RESOURCE, ENTRY, llog_handle2ops(), llog_operations::lop_create, and RETURN.
Referenced by llog_cat_new_log(), and llog_open_create().
static struct llog_ctxt* llog_ctxt_get (struct llog_ctxt * ctxt) [static, read]
Definition at line 367 of file lustre_log.h.
References CDEBUG, D_INFO, and llog_ctxt::loc_refcount.
Referenced by llog_group_get_ctxt(), and llog_osd_setup().
static int llog_ctxt_null (struct obd_device * obd, int index) [inline, static]
Definition at line 442 of file lustre_log.h.
References llog_group_ctxt_null(), and obd_device::obd_olg.
Referenced by mdt_llog_ctxt_clone().
static void llog_ctxt_put (struct llog_ctxt * ctxt) [inline, static]
Definition at line 375 of file lustre_log.h.
References __llog_ctxt_put(), CDEBUG, D_INFO, LASSERT_ATOMIC_GT_LT, and llog_ctxt::loc_refcount.
Referenced by cdt_llog_process(), distribute_txn_cancel_records(), llog_cleanup(), llog_origin_handle_destroy(), llog_origin_handle_next_block(), llog_origin_handle_open(), llog_origin_handle_prev_block(), llog_origin_handle_read_header(), llog_osd_setup(), llog_run_tests(), llog_setup(), llog_test_1(), llog_test_10(), llog_test_2(), llog_test_4(), llog_test_5(), llog_test_6(), llog_test_7(), llog_test_8(), llog_test_9(), llog_test_setup(), lod_obd_get_info(), lod_process_config(), lod_sub_prep_llog(), lod_sub_recovery_thread(), mdc_changelog_send_thread(), mdc_llog_init(), mdd_changelog_llog_cancel(), mdd_changelog_llog_init(), mdd_changelog_size_ctxt(), mdd_changelog_store(), mdd_changelog_user_purge(), mdd_changelog_user_register(), mdd_changelog_users_seq_show(), mdd_changelog_write_header(), mdd_declare_changelog_store(), mdd_hsm_actions_llog_init(), mdt_agent_record_add(), mdt_hsm_actions_proc_stop(), mdt_llog_ctxt_unclone(), mgc_llog_init(), mgc_local_llog_init(), mgc_process_cfg_log(), mgs_erase_log(), mgs_get_fsdb_from_llog(), mgs_get_fsdb_srpc_from_llog(), mgs_init0(), mgs_iocontrol(), mgs_log_is_empty(), mgs_modify(), mgs_replace_nids_log(), mgs_steal_llog_for_mdt_from_client(), osp_sync_add_rec(), osp_sync_declare_add(), osp_sync_llog_init(), osp_sync_process_committed(), osp_sync_thread(), record_start_log(), sptlrpc_target_local_copy_conf(), sptlrpc_target_local_read_conf(), sub_declare_updates_write(), and sub_updates_write().
static int llog_data_len (int len) [inline, static]
Definition at line 355 of file lustre_log.h.
References cfs_size_round().
Referenced by lustre_cfg_rec_new(), mdd_changelog_data_store(), mdd_changelog_store(), mdd_changelog_write_header(), mdd_llog_record_calc_size(), and mdt_agent_record_add().
int llog_declare_add (const struct lu_env * env, struct llog_handle * lgh, struct llog_rec_hdr * rec, struct thandle * th)
Definition at line 939 of file llog.c.
References cfs_cap_lower(), cfs_cap_raise(), cfs_cap_raised(), CFS_CAP_SYS_RESOURCE, ENTRY, llog_handle::lgh_logops, llog_operations::lop_declare_add, and RETURN.
Referenced by mdd_declare_changelog_store(), osp_sync_declare_add(), and sub_declare_updates_write().
int llog_declare_create (const struct lu_env * env, struct llog_handle * loghandle, struct thandle * th)
Definition at line 817 of file llog.c.
References cfs_cap_lower(), cfs_cap_raise(), cfs_cap_raised(), CFS_CAP_SYS_RESOURCE, ENTRY, llog_handle2ops(), llog_operations::lop_declare_create, and RETURN.
Referenced by llog_cat_declare_add_rec(), llog_cat_new_log(), and llog_open_create().
int llog_declare_write_rec (const struct lu_env * env, struct llog_handle * handle, struct llog_rec_hdr * rec, int idx, struct thandle * th)
Definition at line 863 of file llog.c.
References cfs_cap_lower(), cfs_cap_raise(), cfs_cap_raised(), CFS_CAP_SYS_RESOURCE, ENTRY, LASSERT, llog_handle2ops(), llog_operations::lop_declare_write_rec, and RETURN.
Referenced by llog_cancel_rec(), llog_cat_declare_add_rec(), llog_cat_new_log(), and llog_write().
int llog_destroy (const struct lu_env * env, struct llog_handle * handle)
Definition at line 149 of file llog.c.
References dt_object::do_lu, dt_object_exists(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), ENTRY, GOTO, llog_handle::lgh_obj, llog_declare_destroy(), llog_handle2ops(), lu_object::lo_dev, llog_operations::lop_destroy, lu2dt_dev(), and RETURN.
Referenced by llog_cat_close(), llog_cat_process_cb(), llog_cat_reverse_process_cb(), llog_erase(), llog_ioctl(), llog_remove_log(), llog_run_tests(), llog_test_2(), and llog_test_7_sub().
int llog_erase (const struct lu_env * env, struct llog_ctxt * ctxt, struct llog_logid * logid, char * name)
Helper function to delete existent llog.
Definition at line 1014 of file llog.c.
References ENTRY, llog_close(), llog_destroy(), LLOG_F_IS_PLAIN, llog_init_handle(), llog_open(), LLOG_OPEN_EXISTS, and RETURN.
Referenced by llog_backup(), llog_origin_handle_destroy(), mgc_llog_local_copy(), mgs_erase_log(), mgs_replace_nids_log(), and sptlrpc_target_local_copy_conf().
int llog_exist (struct llog_handle * loghandle)
new llog API
API functions: llog_open - open llog, may not exist llog_exist - check if llog exists llog_close - close opened llog, pair for open, frees llog_handle llog_declare_create - declare llog creation llog_create - create new llog on disk, need transaction handle llog_declare_write_rec - declaration of llog write llog_write_rec - write llog record on disk, need transaction handle llog_declare_add - declare llog catalog record addition llog_add - add llog record in catalog, need transaction handle
Definition at line 799 of file llog.c.
References ENTRY, llog_handle2ops(), llog_operations::lop_exist, and RETURN.
Referenced by llog_cat_add_rec(), llog_cat_declare_add_rec(), llog_cat_new_log(), llog_cat_update_header(), llog_open_create(), and llog_test_7_sub().
static struct llog_ctxt* llog_get_context (struct obd_device * obd, int index) [static, read]
Definition at line 431 of file lustre_log.h.
References llog_group_get_ctxt(), and obd_device::obd_olg.
Referenced by cdt_llog_process(), distribute_txn_cancel_records(), llog_origin_handle_destroy(), llog_origin_handle_next_block(), llog_origin_handle_open(), llog_origin_handle_prev_block(), llog_origin_handle_read_header(), llog_run_tests(), llog_test_1(), llog_test_10(), llog_test_2(), llog_test_4(), llog_test_5(), llog_test_6(), llog_test_7(), llog_test_8(), llog_test_9(), llog_test_cleanup(), llog_test_setup(), lod_obd_get_info(), lod_process_config(), lod_sub_fini_llog(), lod_sub_prep_llog(), lod_sub_recovery_thread(), mdc_changelog_send_thread(), mdc_llog_finish(), mdd_changelog_fini(), mdd_changelog_llog_cancel(), mdd_changelog_llog_init(), mdd_changelog_size_ctxt(), mdd_changelog_store(), mdd_changelog_user_purge(), mdd_changelog_user_register(), mdd_changelog_users_seq_show(), mdd_changelog_write_header(), mdd_declare_changelog_store(), mdd_hsm_actions_llog_fini(), mdd_hsm_actions_llog_init(), mdt_agent_record_add(), mdt_hsm_actions_proc_start(), mdt_llog_ctxt_unclone(), mgc_llog_fini(), mgc_llog_init(), mgc_local_llog_fini(), mgc_local_llog_init(), mgc_process_cfg_log(), mgs_device_fini(), mgs_erase_log(), mgs_get_fsdb_from_llog(), mgs_get_fsdb_srpc_from_llog(), mgs_init0(), mgs_iocontrol(), mgs_log_is_empty(), mgs_modify(), mgs_replace_nids_log(), mgs_steal_llog_for_mdt_from_client(), osp_sync_add_rec(), osp_sync_declare_add(), osp_sync_llog_fini(), osp_sync_llog_init(), osp_sync_process_committed(), osp_sync_thread(), record_start_log(), sptlrpc_target_local_copy_conf(), sptlrpc_target_local_read_conf(), sub_declare_updates_write(), and sub_updates_write().
static int llog_get_size (struct llog_handle * loghandle) [inline, static]
Definition at line 360 of file lustre_log.h.
References llog_handle::lgh_hdr, and llog_log_hdr::llh_count.
Referenced by llog_is_empty(), mgs_get_fsdb_from_llog(), mgs_get_fsdb_srpc_from_llog(), mgs_modify(), mgs_replace_nids_log(), and sptlrpc_target_local_read_conf().
static void llog_group_clear_ctxt (struct obd_llog_group * olg, int index) [inline, static]
Definition at line 423 of file lustre_log.h.
References LASSERT, LLOG_MAX_CTXTS, obd_llog_group::olg_ctxts, and obd_llog_group::olg_lock.
Referenced by llog_setup().
static int llog_group_ctxt_null (struct obd_llog_group * olg, int index) [inline, static]
Definition at line 437 of file lustre_log.h.
References obd_llog_group::olg_ctxts.
Referenced by llog_cleanup(), and llog_ctxt_null().
static struct llog_ctxt* llog_group_get_ctxt (struct obd_llog_group * olg, int index) [static, read]
Definition at line 407 of file lustre_log.h.
References LASSERT, llog_ctxt_get(), LLOG_MAX_CTXTS, obd_llog_group::olg_ctxts, and obd_llog_group::olg_lock.
Referenced by llog_get_context(), llog_setup(), mdc_llog_init(), and mdd_llog_ctxt_get().
static void llog_group_init (struct obd_llog_group * olg) [inline, static]
Definition at line 385 of file lustre_log.h.
References obd_llog_group::olg_cat_processing, obd_llog_group::olg_lock, and obd_llog_group::olg_waitq.
Referenced by class_attach().
static int llog_group_set_ctxt (struct obd_llog_group * olg, struct llog_ctxt * ctxt, int index) [inline, static]
Definition at line 392 of file lustre_log.h.
References LASSERT, LLOG_MAX_CTXTS, obd_llog_group::olg_ctxts, and obd_llog_group::olg_lock.
Referenced by llog_setup(), and mdt_llog_ctxt_clone().
static int llog_handle2ops (struct llog_handle * loghandle, struct llog_operations ** lop) [inline, static]
Definition at line 345 of file lustre_log.h.
References llog_handle::lgh_logops.
Referenced by llog_close(), llog_create(), llog_declare_create(), llog_declare_destroy(), llog_declare_write_rec(), llog_destroy(), llog_exist(), llog_next_block(), llog_prev_block(), llog_read_header(), llog_trans_destroy(), and llog_write_rec().
int llog_init_handle (const struct lu_env * env, struct llog_handle * handle, int flags, struct obd_uuid * uuid)
Definition at line 345 of file llog.c.
References CERROR, llog_handle::chd, cat_handle_data::chd_head, ENTRY, GOTO, INIT_LIST_HEAD, LASSERT, llog_handle::lgh_ctxt, llog_handle::lgh_hdr, llog_handle::lgh_hdr_size, list_empty(), llog_log_hdr::llh_flags, llog_log_hdr::llh_size, llog_log_hdr::llh_tgtuuid, LLOG_F_EXT_MASK, LLOG_F_IS_CAT, LLOG_F_IS_FIXSIZE, LLOG_F_IS_PLAIN, LLOG_MIN_CHUNK_SIZE, llog_read_header(), llog_ctxt::loc_chunk_size, llog_ctxt::loc_obd, OBD_ALLOC_LARGE, OBD_FREE_LARGE, obd_device::obd_name, obd_uuid_equals(), RETURN, llog_handle::u, unlikely, and obd_uuid::uuid.
Referenced by class_config_parse_llog(), llog_backup(), llog_cat_id2handle(), llog_cat_new_log(), llog_erase(), llog_ioctl(), llog_is_empty(), llog_origin_handle_next_block(), llog_origin_handle_prev_block(), llog_origin_handle_read_header(), llog_test_1(), llog_test_10(), llog_test_2(), llog_test_4(), llog_test_5(), llog_test_6(), llog_test_7_sub(), llog_test_8(), llog_test_9_sub(), lod_sub_prep_llog(), mdc_changelog_send_thread(), mdd_changelog_llog_init(), mdd_hsm_actions_llog_init(), mgs_get_fsdb_from_llog(), mgs_get_fsdb_srpc_from_llog(), mgs_modify(), mgs_replace_nids_log(), mgs_steal_llog_for_mdt_from_client(), osp_sync_llog_init(), record_start_log(), sptlrpc_target_local_copy_conf(), and sptlrpc_target_local_read_conf().
int llog_initiator_connect (struct llog_ctxt * ctxt)
Definition at line 53 of file llog_net.c.
References client_obd::cl_import, class_import_get(), class_import_put(), obd_device::cli, ENTRY, LASSERT, LASSERTF, llog_ctxt::loc_imp, llog_ctxt::loc_mutex, llog_ctxt::loc_obd, RETURN, and obd_device::u.
Referenced by mdc_llog_init(), and mgc_llog_init().
int llog_ioctl (const struct lu_env * env, struct llog_ctxt * ctxt, int cmd, struct obd_ioctl_data * data)
Definition at line 286 of file llog_ioctl.c.
References CERROR, cfs_size_round(), DOSTID, ENTRY, GOTO, obd_ioctl_data::ioc_bulk, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf2, obd_ioctl_data::ioc_inlbuf3, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, LASSERT, llog_cookie::lgc_index, llog_cookie::lgc_lgl, llog_handle::lgh_hdr, llog_handle::lgh_id, llog_handle::lgh_last_idx, llog_logid::lgl_ogen, llog_logid::lgl_oi, llog_log_hdr::llh_count, llog_log_hdr::llh_flags, llog_cancel_rec(), llog_cat_cancel_records(), llog_cat_close(), llog_check_cb(), llog_close(), llog_delete_cb(), llog_destroy(), LLOG_EEMPTY, LLOG_F_IS_CAT, LLOG_F_IS_PLAIN, llog_init_handle(), llog_open(), LLOG_OPEN_EXISTS, llog_print_cb(), llog_process(), llog_remove_log(), llog_ctxt::loc_obd, name, OBD_IOC_LLOG_CANCEL, OBD_IOC_LLOG_CHECK, OBD_IOC_LLOG_INFO, OBD_IOC_LLOG_PRINT, OBD_IOC_LLOG_REMOVE, obd_device::obd_name, POSTID, RETURN, and str2logid().
Referenced by mgs_iocontrol().
int llog_is_empty (const struct lu_env * env, struct llog_ctxt * ctxt, char * name)
Helper function to get the llog size in records.
It is used by MGS mostly to check that config llog exists and contains data.
Parameters:
[in] env execution environment
[in] ctxt llog context
[in] name llog name
Return values:
true if there are records in llog besides a header
false on error or llog without records
Definition at line 1150 of file llog.c.
References GOTO, likely, llog_close(), LLOG_F_IS_PLAIN, llog_get_size(), llog_init_handle(), llog_open(), and LLOG_OPEN_EXISTS.
Referenced by mgc_process_cfg_log(), and mgs_log_is_empty().
static int llog_is_full (struct llog_handle * llh) [inline, static]
Definition at line 506 of file lustre_log.h.
References llog_handle::lgh_hdr, llog_handle::lgh_last_idx, and LLOG_HDR_BITMAP_SIZE.
Referenced by llog_cat_add_rec(), llog_cat_current_log(), and llog_osd_write_rec().
static int llog_next_block (const struct lu_env * env, struct llog_handle * loghandle, int * cur_idx, int next_idx, __u64 * cur_offset, void * buf, int len) [inline, static]
Definition at line 447 of file lustre_log.h.
References ENTRY, llog_handle2ops(), llog_operations::lop_next_block, and RETURN.
Referenced by llog_origin_handle_next_block(), and llog_process_thread().
static int llog_obd2ops (struct llog_ctxt * ctxt, struct llog_operations ** lop) [inline, static]
Definition at line 332 of file lustre_log.h.
References llog_ctxt::loc_logops.
Referenced by llog_connect().
int llog_open (const struct lu_env * env, struct llog_ctxt * ctxt, struct llog_handle ** lgh, struct llog_logid * logid, char * name, enum llog_open_param open_param)
Definition at line 1083 of file llog.c.
References cfs_cap_lower(), cfs_cap_raise(), cfs_cap_raised(), CFS_CAP_SYS_RESOURCE, ENTRY, LASSERT, llog_alloc_handle(), llog_free_handle(), llog_ctxt::loc_logops, llog_operations::lop_open, and RETURN.
Referenced by class_config_parse_llog(), llog_backup(), llog_cat_declare_add_rec(), llog_cat_id2handle(), llog_erase(), llog_ioctl(), llog_is_empty(), llog_open_create(), llog_origin_handle_next_block(), llog_origin_handle_open(), llog_origin_handle_prev_block(), llog_origin_handle_read_header(), llog_test_2(), llog_test_5(), llog_test_6(), llog_test_8(), lod_sub_prep_llog(), mdc_changelog_send_thread(), mgs_get_fsdb_srpc_from_llog(), mgs_modify(), mgs_replace_nids_log(), mgs_steal_llog_for_mdt_from_client(), osp_sync_llog_init(), and sptlrpc_target_local_read_conf().
int llog_open_create (const struct lu_env * env, struct llog_ctxt * ctxt, struct llog_handle ** res, struct llog_logid * logid, char * name)
Helper function to open llog or create it if doesn't exist.
It hides all transaction handling from caller.
Definition at line 963 of file llog.c.
References dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), ENTRY, GOTO, LASSERT, llog_close(), llog_create(), LLOG_CTXT_FLAG_NORMAL_FID, llog_declare_create(), llog_exist(), llog_open(), LLOG_OPEN_NEW, llog_ctxt::loc_flags, lu2dt_dev(), RETURN, thandle::th_sync, and thandle::th_wait_submit.
Referenced by llog_backup(), llog_test_1(), llog_test_10(), llog_test_2(), llog_test_4(), llog_test_7_sub(), llog_test_9_sub(), lod_sub_prep_llog(), mdd_changelog_llog_init(), mdd_hsm_actions_llog_init(), mgs_get_fsdb_from_llog(), mgs_replace_nids_log(), osp_sync_llog_init(), record_start_log(), and sptlrpc_target_local_copy_conf().
int llog_osd_get_cat_list (const struct lu_env * env, struct dt_device * d, int idx, int count, struct llog_catid * idarray, const struct lu_fid * fid)
Read the special file which contains the list of llog catalogs IDs.
This function reads the CATALOGS file which contains the array of llog catalogs IDs. The main purpose of this file is to store OSP llogs indexed by OST/MDT number.
Parameters:
[in] env execution environment
[in] d corresponding storage device
[in] idx position to start from, usually OST/MDT index
[in] count how many catalog IDs to read
[out] idarray the buffer for the data. If it is NULL then function returns just number of catalog IDs in the file.
[in] fid LLOG_CATALOGS_OID for CATALOG object
Return values:
0 on successful read of catalog IDs
negative value on error
positive value which is number of records in the file if idarray is NULL
Definition at line 1913 of file llog_osd.c.
References CDEBUG, CERROR, D_CONFIG, dt_object::do_lu, dt_object_format::dof_type, dt_attr_get(), dt_create(), dt_declare_create(), dt_locate(), dt_mode_to_dft(), dt_object_exists(), dt_record_read(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), ENTRY, EXIT, GOTO, lu_attr::la_mode, LA_MODE, lu_attr::la_size, lu_attr::la_valid, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lu_device::ld_obd, llog_thread_info::lgi_attr, llog_thread_info::lgi_buf, llog_thread_info::lgi_dof, llog_thread_info::lgi_fid, llog_thread_info::lgi_off, llog_info(), lu_object::lo_dev, lu_object_put(), obd_device::obd_name, RETURN, size, thandle::th_sync, and thandle::th_wait_submit.
Referenced by llog_catalog_list(), lod_sub_prep_llog(), and osp_sync_llog_init().
int llog_osd_put_cat_list (const struct lu_env * env, struct dt_device * d, int idx, int count, struct llog_catid * idarray, const struct lu_fid * fid)
Write the special file which contains the list of llog catalogs IDs.
This function writes the CATALOG file which contains the array of llog catalogs IDs. It is used mostly to store OSP llogs indexed by OST/MDT number.
Parameters:
[in] env execution environment
[in] d corresponding storage device
[in] idx position to start from, usually OST/MDT index
[in] count how many catalog IDs to write
[out] idarray the buffer with the data to write.
[in] fid LLOG_CATALOGS_OID for CATALOG object
Return values:
0 on successful write of catalog IDs
negative value on error
Definition at line 2031 of file llog_osd.c.
References CDEBUG, CERROR, D_INODE, dt_object::do_lu, dt_attr_get(), dt_declare_record_write(), dt_locate(), dt_object_exists(), dt_record_write(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), fid_is_update_log(), GOTO, lu_attr::la_mode, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lu_device::ld_obd, llog_thread_info::lgi_attr, llog_thread_info::lgi_buf, llog_thread_info::lgi_fid, llog_thread_info::lgi_off, llog_info(), lu_object::lo_dev, lu_object_put(), obd_device::obd_name, RETURN, size, thandle::th_sync, and thandle::th_wait_submit.
Referenced by lod_sub_prep_llog(), and osp_sync_llog_init().
static int llog_prev_block (const struct lu_env * env, struct llog_handle * loghandle, int prev_idx, void * buf, int len) [inline, static]
Definition at line 468 of file lustre_log.h.
References ENTRY, llog_handle2ops(), llog_operations::lop_prev_block, and RETURN.
Referenced by llog_origin_handle_prev_block(), and llog_reverse_process().
int llog_process (const struct lu_env * env, struct llog_handle * loghandle, llog_cb_t cb, void * data, void * catdata)
Definition at line 687 of file llog.c.
References LLOG_DEL_PLAIN, and llog_process_or_fork().
Referenced by class_config_parse_llog(), llog_check_cb(), llog_ioctl(), llog_test3_process(), llog_test_10(), llog_test_2(), llog_test_5(), llog_test_6(), llog_test_7_sub(), mgs_get_fsdb_from_llog(), mgs_get_fsdb_srpc_from_llog(), mgs_modify(), mgs_replace_nids_log(), and sptlrpc_target_local_read_conf().
int llog_process_or_fork (const struct lu_env * env, struct llog_handle * loghandle, llog_cb_t cb, void * data, void * catdata, bool fork)
Definition at line 640 of file llog.c.
Referenced by llog_backup(), llog_cat_process_cb(), llog_cat_process_or_fork(), llog_process(), and mgs_steal_llog_for_mdt_from_client().
int llog_read_header (const struct lu_env * env, struct llog_handle * handle, const struct obd_uuid * uuid)
Definition at line 299 of file llog.c.
References cfs_time_current_sec(), ENTRY, ext2_set_bit, LASSERT, llog_handle::lgh_ctxt, llog_handle::lgh_hdr, llog_handle::lgh_last_idx, llog_handle::lgh_write_offset, llog_log_hdr::llh_bitmap, llog_log_hdr::llh_bitmap_offset, llog_log_hdr::llh_count, llog_log_hdr::llh_hdr, llog_log_hdr::llh_tail, llog_log_hdr::llh_tgtuuid, llog_log_hdr::llh_timestamp, LLOG_EEMPTY, llog_handle2ops(), LLOG_HDR_BITMAP, LLOG_HDR_MAGIC, LLOG_HDR_TAIL, LLOG_MIN_CHUNK_SIZE, llog_ctxt::loc_chunk_size, llog_operations::lop_read_header, llog_rec_hdr::lrh_index, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, offsetof, and RETURN.
Referenced by llog_cat_update_header(), and llog_init_handle().
int llog_reverse_process (const struct lu_env * env, struct llog_handle * loghandle, llog_cb_t cb, void * data, void * catdata)
Definition at line 696 of file llog.c.
References buf, cb(), CDEBUG, D_RPCTRACE, ENTRY, ext2_test_bit, GOTO, LASSERT, llog_handle::lgh_hdr, llog_log_hdr::llh_hdr, llog_cancel_rec(), LLOG_DEL_RECORD, LLOG_HDR_BITMAP, LLOG_HDR_BITMAP_SIZE, llog_prev_block(), LLOG_PROC_BREAK, LLOG_REC_HDR_NEEDS_SWABBING, llog_process_cat_data::lpcd_first_idx, llog_process_cat_data::lpcd_last_idx, llog_rec_hdr::lrh_index, llog_rec_hdr::lrh_len, llog_rec_tail::lrt_index, llog_rec_tail::lrt_len, lustre_swab_llog_rec(), OBD_ALLOC_LARGE, OBD_FREE_LARGE, and RETURN.
Referenced by llog_cat_reverse_process(), llog_cat_reverse_process_cb(), llog_test_6(), and llog_test_7_sub().
int llog_setup (const struct lu_env * env, struct obd_device * obd, struct obd_llog_group * olg, int index, struct obd_device * disk_obd, struct llog_operations * op)
Definition at line 146 of file llog_obd.c.
References CDEBUG, CERROR, class_export_get(), D_CONFIG, ENTRY, LASSERT, llog_ctxt_destroy(), LLOG_CTXT_FLAG_UNINITIALIZED, llog_ctxt_put(), llog_group_clear_ctxt(), llog_group_get_ctxt(), llog_group_set_ctxt(), LLOG_MAX_CTXTS, LLOG_MIN_CHUNK_SIZE, llog_new_ctxt(), llog_ctxt::loc_chunk_size, llog_ctxt::loc_exp, llog_ctxt::loc_flags, llog_ctxt::loc_idx, llog_ctxt::loc_logops, llog_ctxt::loc_mutex, llog_ctxt::loc_obd, llog_ctxt::loc_olg, llog_operations::lop_setup, OBD_FAIL_CHECK, OBD_FAIL_OBD_LLOG_SETUP, obd_device::obd_name, obd_device::obd_self_export, and RETURN.
Referenced by llog_test_setup(), lod_process_config(), lod_sub_init_llog(), mdc_llog_init(), mdd_changelog_llog_init(), mdd_hsm_actions_llog_init(), mgc_llog_init(), mgc_local_llog_init(), mgs_init0(), and osp_sync_llog_init().
__u64 llog_size (const struct lu_env * env, struct llog_handle * llh)
Definition at line 1252 of file llog.c.
References CERROR, dt_object_operations::do_attr_get, dt_object::do_ops, lu_attr::la_size, llog_handle::lgh_ctxt, llog_handle::lgh_obj, llog_ctxt::loc_obd, and obd_device::obd_name.
Referenced by llog_cat_size(), and llog_cat_size_cb().
int llog_sync (struct llog_ctxt * ctxt, struct obd_export * exp, int flags)
Definition at line 222 of file llog_obd.c.
References CTXTP, ENTRY, and RETURN.
int llog_trans_destroy (const struct lu_env * env, struct llog_handle * handle, struct thandle * th)
Definition at line 127 of file llog.c.
References dt_object_exists(), ENTRY, LASSERT, llog_handle::lgh_obj, llog_handle2ops(), llog_operations::lop_destroy, and RETURN.
Referenced by llog_cancel_rec(), and llog_cat_new_log().
int llog_write (const struct lu_env * env, struct llog_handle * loghandle, struct llog_rec_hdr * rec, int idx)
Definition at line 1046 of file llog.c.
References dt_object::do_lu, dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), ENTRY, GOTO, LASSERT, llog_handle::lgh_ctxt, llog_handle::lgh_lock, llog_handle::lgh_obj, llog_declare_write_rec(), llog_write_rec(), lu_object::lo_dev, lu2dt_dev(), RETURN, and thandle::th_wait_submit.
Referenced by hsm_restore_cb(), llog_copy_handler(), llog_test_2(), llog_test_3(), llog_test_7_sub(), llog_test_9_sub(), mdd_changelog_user_purge_cb(), mdt_agent_record_update_cb(), mdt_cancel_all_cb(), mdt_coordinator_cb(), mgs_modify_handler(), mgs_replace_handler(), mgs_write_log_direct(), record_base(), record_lmv_setup(), record_lov_setup(), record_marker(), sptlrpc_record_rule_set(), and test3_check_n_add_cb().
int llog_write_rec (const struct lu_env * env, struct llog_handle * handle, struct llog_rec_hdr * rec, struct llog_cookie * logcookies, int idx, struct thandle * th)
Definition at line 889 of file llog.c.
References cfs_cap_lower(), cfs_cap_raise(), cfs_cap_raised(), CFS_CAP_SYS_RESOURCE, cfs_size_round(), ENTRY, LASSERT, llog_handle2ops(), llog_operations::lop_write_rec, llog_rec_hdr::lrh_len, and RETURN.
Referenced by llog_cancel_rec(), llog_cat_add_rec(), llog_cat_new_log(), and llog_write().
void lustre_cfg_rec_free (struct llog_cfg_rec * lcr)
Definition at line 1438 of file obd_config.c.
References ENTRY, EXIT, llog_cfg_rec::lcr_hdr, llog_rec_hdr::lrh_len, and OBD_FREE.
Referenced by mgs_srpc_set_param_disk(), mgs_wlp_lcfg(), mgs_write_log_quota(), mgs_write_log_sys(), record_base(), record_lmv_setup(), record_lov_setup(), record_marker(), and sptlrpc_record_rule_set().
struct llog_cfg_rec* lustre_cfg_rec_new (int cmd, struct lustre_cfg_bufs * bufs) [read]
Definition at line 1414 of file obd_config.c.
References ENTRY, lustre_cfg_bufs::lcfg_bufcount, lustre_cfg_bufs::lcfg_buflen, lcr, llog_cfg_rec::lcr_cfg, llog_cfg_rec::lcr_hdr, llog_data_len(), llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, lustre_cfg_init(), lustre_cfg_len(), OBD_ALLOC, OBD_CFG_REC, and RETURN.
Referenced by mgs_srpc_set_param_disk(), mgs_wlp_lcfg(), mgs_write_log_quota(), mgs_write_log_sys(), record_base(), record_lmv_setup(), record_lov_setup(), record_marker(), and sptlrpc_record_rule_set().
int lustre_end_log (struct super_block * sb, char * logname, struct config_llog_instance * cfg)
Definition at line 126 of file obd_mount.c.
References ENTRY, LCFG_LOG_END, lustre_cfg_bufs_reset(), lustre_cfg_bufs_set(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), obd_device::obd_name, obd_process_config(), and RETURN.
Referenced by ll_put_super(), lustre_disconnect_lwp(), and server_put_super().
int lustre_process_log (struct super_block * sb, char * logname, struct config_llog_instance * cfg)
Get a config log from the MGS and process it.
This func is called for both clients and servers. Continue to process new statements appended to the logs (whenever the config lock is revoked) until lustre_end_log is called.
Parameters:
sb The superblock is used by the MGC to write to the local copy of the config log
logname The name of the llog to replicate from the MGS
cfg Since the same mgc may be used to follow multiple config logs (e.g. ost1, ost2, client), the config_llog_instance keeps the state for this log, and is added to the mgc's list of logs to follow.
Definition at line 75 of file obd_mount.c.
References ENTRY, GOTO, LASSERT, LCFG_LOG_START, LCONSOLE_ERROR_MSG, lustre_cfg_bufs_reset(), lustre_cfg_bufs_set(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), OBD_ALLOC_PTR, OBD_FREE_PTR, obd_device::obd_name, obd_process_config(), and RETURN.
Referenced by ll_fill_super(), lustre_start_lwp(), and server_start_targets().
Variable Documentation
struct llog_operations llog_common_cat_ops
Definition at line 1872 of file llog_osd.c.
Referenced by lod_process_config(), and lod_sub_init_llog().
struct llog_operations llog_osd_ops
Definition at line 1854 of file llog_osd.c.
Referenced by llog_test_setup(), mdd_init(), mgc_local_llog_init(), mgs_init0(), and osp_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.