Lustre: Echo Client
Echo Client
Data Structures
struct echo_device
struct echo_object
struct echo_object_conf
struct echo_page
struct echo_lock
struct echo_thread_info
struct echo_session_info
Modules
Helper functions
Page operations
Echo page operations.
Locking
echo lock operations
cl_object operations
operations for cl_object
lu_object operations
operations for echo lu object.
lu_device operations
Operations for echo lu device.
Setup and teardown
Init and fini functions for echo client.
Exported operations
exporting functions to echo client
Functions
static int echo_client_setup (const struct lu_env *env, struct obd_device *obddev, struct lustre_cfg *lcfg)
static int echo_client_cleanup (struct obd_device *obddev)
static int cl_echo_object_put (struct echo_object *eco)
static int cl_echo_object_brw (struct echo_object *eco, int rw, u64 offset, struct page **pages, int npages, int async)
static int echo_create_object (const struct lu_env *env, struct echo_device *ed, struct obdo *oa)
static int echo_get_object (struct echo_object **ecop, struct echo_device *ed, struct obdo *oa)
static void echo_put_object (struct echo_object *eco)
static void echo_client_page_debug_setup (struct page *page, int rw, u64 id, u64 offset, u64 count)
static int echo_client_page_debug_check (struct page *page, u64 id, u64 offset, u64 count)
static int echo_client_kbrw (struct echo_device *ed, int rw, struct obdo *oa, struct echo_object *eco, u64 offset, u64 count, int async)
static int echo_client_prep_commit (const struct lu_env *env, struct obd_export *exp, int rw, struct obdo *oa, struct echo_object *eco, u64 offset, u64 count, u64 batch, int async)
static int echo_client_brw_ioctl (const struct lu_env *env, int rw, struct obd_export *exp, struct obd_ioctl_data *data)
static int echo_client_iocontrol (unsigned int cmd, struct obd_export *exp, int len, void *karg, void __user *uarg)
static int echo_client_connect (const struct lu_env *env, struct obd_export **exp, struct obd_device *src, struct obd_uuid *cluuid, struct obd_connect_data *data, void *localdata)
static int echo_client_disconnect (struct obd_export *exp)
static int __init obdecho_init (void)
static void __exit obdecho_exit (void)
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Echo Client test driver")
MODULE_VERSION (LUSTRE_VERSION_STRING)
MODULE_LICENSE ("GPL")
module_init (obdecho_init)
module_exit (obdecho_exit)
Variables
static struct kmem_cache * echo_lock_kmem
static struct kmem_cache * echo_object_kmem
static struct kmem_cache * echo_thread_kmem
static struct kmem_cache * echo_session_kmem
static struct lu_kmem_descr echo_caches []
static u64 last_object_id
static struct obd_ops echo_client_obd_ops
Function Documentation
static int cl_echo_object_brw (struct echo_object * eco, int rw, u64 offset, struct page ** pages, int npages, int async) [static]
Definition at line 1286 of file echo_client.c.
References cl_2queue::c2_qin, CDEBUG, CEF_NEVER, cl_io::ci_ignore_layout, CIT_MISC, cl_2queue_add(), cl_2queue_discard(), cl_2queue_disown(), cl_2queue_fini(), cl_2queue_init(), cl_echo_cancel0(), cl_echo_enqueue0(), cl_env_get(), cl_env_put(), cl_index(), cl_io_commit_async(), cl_io_fini(), cl_io_init(), cl_io_submit_sync(), cl_page_clip(), cl_page_find(), cl_page_own(), cl_page_put(), cl_page_size(), lustre_handle::cookie, cl_page::cp_state, cl_page::cp_type, CPS_FREEING, CPT_TRANSIENT, CRT_READ, CRT_WRITE, D_INFO, echo_commit_callback(), echo_env_info(), echo_obj2cl(), echo_device::ed_next, ENTRY, echo_object::eo_dev, echo_thread_info::eti_io, echo_thread_info::eti_queue, EXIT, GOTO, LASSERT, LCK_PR, LCK_PW, page_size, READ, and RETURN.
Referenced by echo_client_kbrw().
static int cl_echo_object_put (struct echo_object * eco) [static]
Definition at line 1174 of file echo_client.c.
References cl_env_get(), cl_env_put(), cl_object_put(), cl_object::co_lu, echo_obj2cl(), ENTRY, echo_object::eo_deleted, echo_object::eo_hdr, LASSERT, lu_object::lo_header, lu_object_header::loh_flags, LU_OBJECT_HEARD_BANSHEE, luh2coh(), and RETURN.
Referenced by echo_create_object(), and echo_put_object().
static int echo_client_brw_ioctl (const struct lu_env * env, int rw, struct obd_export * exp, struct obd_ioctl_data * data) [static]
Definition at line 2499 of file echo_client.c.
References class_exp2obd(), echo_client_obd::ec_exp, echo_client_kbrw(), echo_client_prep_commit(), echo_get_object(), echo_put_object(), echo_device::ed_ec, echo_device::ed_next, ENTRY, obd_ioctl_data::ioc_count, obd_ioctl_data::ioc_obdo1, obd_ioctl_data::ioc_offset, obd_ioctl_data::ioc_pbuf1, obd_ioctl_data::ioc_plen1, LASSERT, obdo::o_valid, obd2echo_dev(), OBD_MD_FLGROUP, OBD_MD_FLHANDLE, PTLRPC_MAX_BRW_SIZE, and RETURN.
Referenced by echo_client_iocontrol().
static int echo_client_cleanup (struct obd_device * obddev) [static]
Definition at line 2818 of file echo_client.c.
References CERROR, echo_client_obd::ec_exp, obd_device::echo_client, echo_device::ed_next_ismd, ENTRY, obd_export::exp_refcount, LASSERT, list_empty(), lu_context_tags_clear(), lu_session_tags_clear(), obd2echo_dev(), obd_disconnect(), obd_device::obd_exports, RETURN, and obd_device::u.
Referenced by echo_device_alloc(), and echo_device_free().
static int echo_client_connect (const struct lu_env * env, struct obd_export ** exp, struct obd_device * src, struct obd_uuid * cluuid, struct obd_connect_data * data, void * localdata) [static]
Definition at line 2853 of file echo_client.c.
References class_conn2export(), class_connect(), ENTRY, and RETURN.
static int echo_client_disconnect (struct obd_export * exp) [static]
Definition at line 2870 of file echo_client.c.
References class_disconnect(), ENTRY, and GOTO.
static int echo_client_iocontrol (unsigned int cmd, struct obd_export * exp, int len, void * karg, void __user * uarg) [static]
Definition at line 2557 of file echo_client.c.
References __u64, CERROR, CFS_CAP_SYS_ADMIN, cfs_capable(), cl_env_get(), cl_env_put(), dir, echo_client_obd::ec_exp, echo_client_brw_ioctl(), echo_create_object(), echo_get_object(), echo_put_object(), echo_device::ed_cl_seq, echo_device::ed_ec, ENTRY, echo_object::eo_deleted, EXIT, obd_export::exp_obd, GOTO, obd_ioctl_data::ioc_command, obd_ioctl_data::ioc_count, obd_ioctl_data::ioc_obdo1, obd_ioctl_data::ioc_obdo2, obd_ioctl_data::ioc_pbuf1, obd_ioctl_data::ioc_pbuf2, obd_ioctl_data::ioc_plen1, obd_ioctl_data::ioc_plen2, LCT_DT_THREAD, LCT_NOREF, LCT_SERVER_SESSION, lu_env::le_ses, lu_context_enter(), lu_context_exit(), lu_context_fini(), lu_context_init(), lu_env_fini(), lu_env_init(), lu_env_refill_by_tags(), LUSTRE_METADATA_SEQ_MAX_WIDTH, max_count, obdo::o_oi, obdo::o_valid, obd2echo_dev(), OBD_ALLOC, OBD_ALLOC_PTR, OBD_BRW_READ, OBD_BRW_WRITE, obd_destroy(), OBD_FREE, OBD_FREE_PTR, obd_getattr(), OBD_IOC_BRW_READ, OBD_IOC_BRW_WRITE, OBD_IOC_CREATE, OBD_IOC_DESTROY, OBD_IOC_ECHO_ALLOC_SEQ, OBD_IOC_ECHO_MD, OBD_IOC_GETATTR, OBD_IOC_SETATTR, OBD_MD_FLGROUP, obd_device::obd_name, obd_setattr(), ost_id::oi, ostid_set_seq_echo(), ostid_to_fid(), RETURN, seq_client_get_seq(), tgt_ses_info(), tgt_session_info::tsi_exp, tgt_session_info::tsi_jobid, and unlikely.
static int echo_client_kbrw (struct echo_device * ed, int rw, struct obdo * oa, struct echo_object * eco, u64 offset, u64 count, int async) [static]
Definition at line 2315 of file echo_client.c.
References cl_echo_object_brw(), echo_client_page_debug_check(), echo_client_page_debug_setup(), ECHO_PERSISTENT_OBJID, echo_device::ed_next, ENTRY, LASSERT, obdo::o_flags, obdo::o_oi, obdo::o_valid, OBD_ALLOC, OBD_BRW_ASYNC, OBD_BRW_READ, OBD_BRW_WRITE, OBD_FL_DEBUG_CHECK, OBD_FREE, OBD_MD_FLFLAGS, ostid_id(), and RETURN.
Referenced by echo_client_brw_ioctl().
static int echo_client_page_debug_check (struct page * page, u64 id, u64 offset, u64 count) [static]
Definition at line 2284 of file echo_client.c.
References block_debug_check(), CERROR, LASSERT, LPX64, and OBD_ECHO_BLOCK_SIZE.
Referenced by echo_client_kbrw(), and echo_client_prep_commit().
static void echo_client_page_debug_setup (struct page * page, int rw, u64 id, u64 offset, u64 count) [static]
Definition at line 2255 of file echo_client.c.
References block_debug_setup(), LASSERT, OBD_BRW_WRITE, and OBD_ECHO_BLOCK_SIZE.
Referenced by echo_client_kbrw(), and echo_client_prep_commit().
static int echo_client_prep_commit (const struct lu_env * env, struct obd_export * exp, int rw, struct obdo * oa, struct echo_object * eco, u64 offset, u64 count, u64 batch, int async) [static]
Definition at line 2407 of file echo_client.c.
References echo_client_page_debug_check(), echo_client_page_debug_setup(), ECHO_PERSISTENT_OBJID, ENTRY, GOTO, obd_ioobj::ioo_bufcnt, lu_env::le_ctx, niobuf_local::lnb_file_offset, niobuf_local::lnb_flags, niobuf_local::lnb_len, niobuf_local::lnb_page, lu_context_enter(), lu_context_exit(), obdo::o_flags, obdo::o_oi, obdo::o_valid, OBD_ALLOC, OBD_BRW_ASYNC, OBD_BRW_WRITE, obd_commitrw(), OBD_FL_DEBUG_CHECK, OBD_FREE, OBD_MD_FLFLAGS, obd_preprw(), obdo_to_ioobj(), ostid_id(), ret, RETURN, niobuf_remote::rnb_flags, niobuf_remote::rnb_len, and niobuf_remote::rnb_offset.
Referenced by echo_client_brw_ioctl().
static int echo_client_setup (const struct lu_env * env, struct obd_device * obddev, struct lustre_cfg * lcfg) [static]
Definition at line 2744 of file echo_client.c.
References CERROR, class_name2obd(), DT_MAX_BRW_SIZE, echo_client_obd::ec_exp, echo_client_obd::ec_lock, echo_client_obd::ec_locks, echo_client_obd::ec_objects, echo_client_obd::ec_unique, obd_device::echo_client, ENTRY, obd_export::exp_obd_chain_timed, FID_SEQ_ECHO, INIT_LIST_HEAD, lustre_cfg::lcfg_bufcount, list_del_init(), lu_context_tags_update(), lu_session_tags_update(), LUSTRE_CFG_BUFLEN, lustre_cfg_string(), LUSTRE_MDT_NAME, LUSTRE_VERSION_CODE, OBD_ALLOC, obd_device::obd_attached, obd_connect(), OBD_CONNECT_64BITHASH, OBD_CONNECT_BRW_SIZE, OBD_CONNECT_FID, OBD_CONNECT_FULL20, OBD_CONNECT_GRANT, OBD_CONNECT_LVB_TYPE, OBD_CONNECT_REQPORTAL, OBD_CONNECT_VERSION, obd_device::obd_dev_lock, OBD_FREE, obd_device::obd_set_up, obd_device::obd_type, obd_connect_data::ocd_brw_size, obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_group, obd_connect_data::ocd_version, RETURN, obd_type::typ_name, and obd_device::u.
Referenced by echo_device_alloc().
static int echo_create_object (const struct lu_env * env, struct echo_device * ed, struct obdo * oa) [static]
Definition at line 2174 of file echo_client.c.
References CDEBUG, CERROR, cl_echo_object_find(), cl_echo_object_put(), D_INFO, DOSTID, echo_client_obd::ec_exp, echo_device::ed_ec, ENTRY, EXIT, fid_seq_is_echo(), GOTO, last_object_id, obdo::o_oi, obdo::o_valid, obd_create(), obd_destroy(), OBD_MD_FLGROUP, OBD_MD_FLID, ostid_id(), ostid_seq(), ostid_set_id(), POSTID, and RETURN.
Referenced by echo_client_iocontrol().
static int echo_get_object (struct echo_object ** ecop, struct echo_device * ed, struct obdo * oa) [static]
Definition at line 2221 of file echo_client.c.
References CERROR, cl_echo_object_find(), DOSTID, ENTRY, obdo::o_oi, obdo::o_valid, OBD_MD_FLGROUP, OBD_MD_FLID, ostid_id(), POSTID, and RETURN.
Referenced by echo_client_brw_ioctl(), and echo_client_iocontrol().
static void echo_put_object (struct echo_object * eco) [static]
Definition at line 2245 of file echo_client.c.
References CERROR, cl_echo_object_put(), echo_client_obd::ec_exp, echo_device::ed_ec, echo_object::eo_dev, obd_export::exp_obd, and obd_device::obd_name.
Referenced by echo_client_brw_ioctl(), and echo_client_iocontrol().
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Echo Client test driver")
module_exit (obdecho_exit)
module_init (obdecho_init)
MODULE_LICENSE ("GPL")
MODULE_VERSION (LUSTRE_VERSION_STRING)
static void __exit obdecho_exit (void) [static]
Definition at line 2932 of file echo_client.c.
References class_unregister_type(), echo_persistent_pages_fini(), lu_kmem_fini(), LUSTRE_ECHO_CLIENT_NAME, and LUSTRE_ECHO_NAME.
static int __init obdecho_init (void) [static]
Definition at line 2891 of file echo_client.c.
References class_register_type(), class_unregister_type(), echo_client_obd_ops, echo_device_type, echo_obd_ops, echo_persistent_pages_fini(), echo_persistent_pages_init(), ENTRY, LASSERT, LCONSOLE_INFO, lu_kmem_fini(), lu_kmem_init(), LUSTRE_ECHO_CLIENT_NAME, LUSTRE_ECHO_NAME, OBD_ECHO_BLOCK_SIZE, and RETURN.
Variable Documentation
struct lu_kmem_descr echo_caches[] [static]
Initial value:
 {
        {
                .ckd_cache = &echo_lock_kmem,
                .ckd_name  = "echo_lock_kmem",
                .ckd_size  = sizeof (struct echo_lock)
        },
        {
                .ckd_cache = &echo_object_kmem,
                .ckd_name  = "echo_object_kmem",
                .ckd_size  = sizeof (struct echo_object)
        },
        {
                .ckd_cache = &echo_thread_kmem,
                .ckd_name  = "echo_thread_kmem",
                .ckd_size  = sizeof (struct echo_thread_info)
        },
        {
                .ckd_cache = &echo_session_kmem,
                .ckd_name  = "echo_session_kmem",
                .ckd_size  = sizeof (struct echo_session_info)
        },
        {
                .ckd_cache = NULL
        }
}
Definition at line 252 of file echo_client.c.
struct obd_ops echo_client_obd_ops [static]
Initial value:
 {
        .o_owner       = THIS_MODULE,
        .o_iocontrol   = echo_client_iocontrol,
        .o_connect     = echo_client_connect,
        .o_disconnect  = echo_client_disconnect
}
Definition at line 2884 of file echo_client.c.
Referenced by obdecho_init().
struct kmem_cache* echo_lock_kmem [static]
Definition at line 246 of file echo_client.c.
Referenced by echo_lock_fini(), and echo_lock_init().
struct kmem_cache* echo_object_kmem [static]
Definition at line 247 of file echo_client.c.
Referenced by echo_object_alloc(), and echo_object_free().
struct kmem_cache* echo_session_kmem [static]
Definition at line 249 of file echo_client.c.
Referenced by echo_session_key_fini(), and echo_session_key_init().
struct kmem_cache* echo_thread_kmem [static]
Definition at line 248 of file echo_client.c.
Referenced by echo_thread_key_fini(), and echo_thread_key_init().
u64 last_object_id [static]
Definition at line 1384 of file echo_client.c.
Referenced by echo_create_object().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.