Lustre: dt
dt
Sub-class of lu_object with methods common for "data" objects in OST stack.
Data Structures
struct dt_device_param
struct dt_txn_commit_cb
struct dt_device_operations
Operations on dt device.
struct dt_index_features
struct dt_allocation_hint
This is a general purpose dt allocation hint.
struct dt_object_format
object format specifier.
struct dt_object_operations
A dt_object provides common operations to create and destroy objects and to manage regular and extended attributes.
struct dt_body_operations
Per-dt-object operations on "file body" - unstructure raw data.
struct dt_index_operations
Per-dt-object operations on object as index.
struct dt_device
struct dt_object
struct local_oid_storage
struct thandle
This is the general purpose transaction handle.
struct dt_txn_callback
Transaction call-backs.
Defines
#define TRANS_COMMIT_CB_MAGIC 0xa0a00a0a
Special per-transaction callback for cases when just commit callback is needed and per-device callback are not convenient to use.
#define MAX_COMMIT_CB_STR_LEN 32
#define DCB_TRANS_STOP 0x1
#define DT_OTABLE_IT_FLAGS_SHIFT 16
#define DT_OTABLE_IT_FLAGS_MASK 0xffff0000
#define DT_MAX_PATH 1024
Typedefs
typedef void(* dt_cb_t)(struct lu_env *env, struct thandle *th, struct dt_txn_commit_cb *cb, int err)
typedef __u64 dt_obj_version_t
typedef int(* dt_entry_func_t)(const struct lu_env *env, const char *name, void *pvt)
Callback function used for parsing path.
typedef int(* dt_index_page_build_t)(const struct lu_env *env, union lu_page *lp, size_t nob, const struct dt_it_ops *iops, struct dt_it *it, __u32 attr, void *arg)
Enumerations
enum mntopt_t { MNTOPT_USERXATTR = 0x00000001, MNTOPT_ACL = 0x00000002 }
enum dt_index_flags {
DT_IND_VARKEY = 1 << 0, DT_IND_VARREC = 1 << 1, DT_IND_UPDATE = 1 << 2, DT_IND_NONUNQ = 1 << 3,
DT_IND_RANGE = 1 << 4
}
enum dt_format_type {
DFT_REGULAR, DFT_DIR, DFT_NODE, DFT_INDEX,
DFT_SYM
}
object type specifier.
enum dt_otable_it_valid { DOIV_ERROR_HANDLE = 0x0001, DOIV_DRYRUN = 0x0002 }
enum dt_otable_it_flags { DOIF_FAILOUT = 0x0001, DOIF_RESET = 0x0002, DOIF_OUTUSED = 0x0004, DOIF_DRYRUN = 0x0008 }
Functions
enum dt_format_type dt_mode_to_dft (__u32 mode)
int dt_device_init (struct dt_device *dev, struct lu_device_type *t)
void dt_device_fini (struct dt_device *dev)
static int lu_device_is_dt (const struct lu_device *d)
static struct dt_device * lu2dt_dev (struct lu_device *l)
static struct lu_device * dt2lu_dev (struct dt_device *d)
static struct dt_object * lu2dt (struct lu_object *l)
int dt_object_init (struct dt_object *obj, struct lu_object_header *h, struct lu_device *d)
void dt_object_fini (struct dt_object *obj)
static int dt_object_exists (const struct dt_object *dt)
static int dt_object_remote (const struct dt_object *dt)
static struct dt_object * lu2dt_obj (struct lu_object *o)
static struct dt_object * dt_object_child (struct dt_object *o)
void dt_txn_callback_add (struct dt_device *dev, struct dt_txn_callback *cb)
void dt_txn_callback_del (struct dt_device *dev, struct dt_txn_callback *cb)
int dt_txn_hook_start (const struct lu_env *env, struct dt_device *dev, struct thandle *txn)
int dt_txn_hook_stop (const struct lu_env *env, struct thandle *txn)
void dt_txn_hook_commit (struct thandle *txn)
int dt_try_as_dir (const struct lu_env *env, struct dt_object *obj)
int dt_path_parser (const struct lu_env *env, char *local, dt_entry_func_t entry_func, void *data)
Abstract function which parses path name.
struct dt_object * dt_store_resolve (const struct lu_env *env, struct dt_device *dt, const char *path, struct lu_fid *fid)
struct dt_object * dt_store_open (const struct lu_env *env, struct dt_device *dt, const char *dirname, const char *filename, struct lu_fid *fid)
Open dt object named filename from dirname directory.
struct dt_object * dt_find_or_create (const struct lu_env *env, struct dt_device *dt, const struct lu_fid *fid, struct dt_object_format *dof, struct lu_attr *attr)
struct dt_object * dt_locate_at (const struct lu_env *env, struct dt_device *dev, const struct lu_fid *fid, struct lu_device *top_dev, const struct lu_object_conf *conf)
static struct dt_object * dt_locate (const struct lu_env *env, struct dt_device *dev, const struct lu_fid *fid)
static struct dt_object * dt_object_locate (struct dt_object *dto, struct dt_device *dt_dev)
int local_oid_storage_init (const struct lu_env *env, struct dt_device *dev, const struct lu_fid *first_fid, struct local_oid_storage **los)
Initialize local OID storage for required sequence.
void local_oid_storage_fini (const struct lu_env *env, struct local_oid_storage *los)
int local_object_fid_generate (const struct lu_env *env, struct local_oid_storage *los, struct lu_fid *fid)
local file fid generation
int local_object_declare_create (const struct lu_env *env, struct local_oid_storage *los, struct dt_object *o, struct lu_attr *attr, struct dt_object_format *dof, struct thandle *th)
int local_object_create (const struct lu_env *env, struct local_oid_storage *los, struct dt_object *o, struct lu_attr *attr, struct dt_object_format *dof, struct thandle *th)
struct dt_object * local_file_find_or_create (const struct lu_env *env, struct local_oid_storage *los, struct dt_object *parent, const char *name, __u32 mode)
struct dt_object * local_file_find_or_create_with_fid (const struct lu_env *env, struct dt_device *dt, const struct lu_fid *fid, struct dt_object *parent, const char *name, __u32 mode)
struct dt_object * local_index_find_or_create (const struct lu_env *env, struct local_oid_storage *los, struct dt_object *parent, const char *name, __u32 mode, const struct dt_index_features *ft)
struct dt_object * local_index_find_or_create_with_fid (const struct lu_env *env, struct dt_device *dt, const struct lu_fid *fid, struct dt_object *parent, const char *name, __u32 mode, const struct dt_index_features *ft)
int local_object_unlink (const struct lu_env *env, struct dt_device *dt, struct dt_object *parent, const char *name)
static int dt_object_lock (const struct lu_env *env, struct dt_object *o, struct lustre_handle *lh, struct ldlm_enqueue_info *einfo, union ldlm_policy_data *policy)
static int dt_object_unlock (const struct lu_env *env, struct dt_object *o, struct ldlm_enqueue_info *einfo, union ldlm_policy_data *policy)
int dt_lookup_dir (const struct lu_env *env, struct dt_object *dir, const char *name, struct lu_fid *fid)
lookup fid for object named name in directory dir.
static int dt_object_sync (const struct lu_env *env, struct dt_object *o, __u64 start, __u64 end)
int dt_declare_version_set (const struct lu_env *env, struct dt_object *o, struct thandle *th)
void dt_version_set (const struct lu_env *env, struct dt_object *o, dt_obj_version_t version, struct thandle *th)
dt_obj_version_t dt_version_get (const struct lu_env *env, struct dt_object *o)
int dt_read (const struct lu_env *env, struct dt_object *dt, struct lu_buf *buf, loff_t *pos)
Generic read helper.
int dt_record_read (const struct lu_env *env, struct dt_object *dt, struct lu_buf *buf, loff_t *pos)
Read structures of fixed size from storage.
int dt_record_write (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, loff_t *pos, struct thandle *th)
int dt_index_walk (const struct lu_env *env, struct dt_object *obj, const struct lu_rdpg *rdpg, dt_index_page_build_t filler, void *arg)
int dt_index_read (const struct lu_env *env, struct dt_device *dev, struct idx_info *ii, const struct lu_rdpg *rdpg)
Walk key/record pairs of an index and copy them into 4KB containers to be transferred over the network.
static struct thandle * dt_trans_create (const struct lu_env *env, struct dt_device *d)
static int dt_trans_start (const struct lu_env *env, struct dt_device *d, struct thandle *th)
static int dt_trans_start_local (const struct lu_env *env, struct dt_device *d, struct thandle *th)
static int dt_trans_stop (const struct lu_env *env, struct dt_device *d, struct thandle *th)
static int dt_trans_cb_add (struct thandle *th, struct dt_txn_commit_cb *dcb)
Variables
struct dt_index_features dt_directory_features
Features, required from index to support file system directories (mapping names to fids).
struct dt_index_features dt_otable_features
struct dt_index_features dt_lfsck_orphan_features
struct dt_index_features dt_lfsck_features
struct dt_index_features dt_acct_features
struct dt_index_features dt_quota_glb_features
struct dt_index_features dt_quota_slv_features
struct dt_index_features dt_nodemap_features
Detailed Description
Sub-class of lu_object with methods common for "data" objects in OST stack.
Data objects behave like regular files: you can read/write them, get and set their attributes. Implementation of dt interface is supposed to implement some form of garbage collection, normally reference counting (nlink) based one.
Examples: osd (lustre/osd) is an implementation of dt interface.
Define Documentation
#define DCB_TRANS_STOP 0x1
Definition at line 107 of file dt_object.h.
Referenced by osd_trans_cb_add(), osp_trans_cb_add(), and sub_thandle_register_stop_cb().
#define DT_MAX_PATH 1024
Definition at line 1897 of file dt_object.h.
#define DT_OTABLE_IT_FLAGS_MASK 0xffff0000
Definition at line 1720 of file dt_object.h.
Referenced by osd_otable_it_init().
#define DT_OTABLE_IT_FLAGS_SHIFT 16
Definition at line 1719 of file dt_object.h.
Referenced by lfsck_start(), and osd_otable_it_init().
#define MAX_COMMIT_CB_STR_LEN 32
Definition at line 105 of file dt_object.h.
#define TRANS_COMMIT_CB_MAGIC 0xa0a00a0a
Special per-transaction callback for cases when just commit callback is needed and per-device callback are not convenient to use.
Definition at line 104 of file dt_object.h.
Referenced by dt_trans_cb_add(), osd_trans_cb_add(), osd_trans_commit_cb(), osd_trans_stop_cb(), osp_trans_cb_add(), osp_trans_commit_cb(), and osp_trans_stop_cb().
Typedef Documentation
typedef void(* dt_cb_t)(struct lu_env *env, struct thandle *th, struct dt_txn_commit_cb *cb, int err)
Definition at line 98 of file dt_object.h.
typedef int(* dt_entry_func_t)(const struct lu_env *env, const char *name, void *pvt)
Callback function used for parsing path.
See also:
llo_store_resolve
Definition at line 1893 of file dt_object.h.
typedef int(* dt_index_page_build_t)(const struct lu_env *env, union lu_page *lp, size_t nob, const struct dt_it_ops *iops, struct dt_it *it, __u32 attr, void *arg)
Definition at line 2037 of file dt_object.h.
typedef __u64 dt_obj_version_t
Definition at line 417 of file dt_object.h.
Enumeration Type Documentation
enum dt_format_type
object type specifier.
Enumerator:
DFT_REGULAR
DFT_DIR
DFT_NODE
for mknod
DFT_INDEX
for special index
DFT_SYM
for symbolic link
Definition at line 380 of file dt_object.h.
enum dt_index_flags
Enumerator:
DT_IND_VARKEY
index supports variable sized keys
DT_IND_VARREC
index supports variable sized records
DT_IND_UPDATE
index can be modified
DT_IND_NONUNQ
index supports records with non-unique (duplicate) keys
DT_IND_RANGE
index support fixed-size keys sorted with natural numerical way and is able to return left-side value if no exact value found
Definition at line 327 of file dt_object.h.
enum dt_otable_it_flags
Enumerator:
DOIF_FAILOUT
DOIF_RESET
DOIF_OUTUSED
DOIF_DRYRUN
Definition at line 1697 of file dt_object.h.
enum dt_otable_it_valid
Enumerator:
DOIV_ERROR_HANDLE
DOIV_DRYRUN
Definition at line 1692 of file dt_object.h.
enum mntopt_t
Enumerator:
MNTOPT_USERXATTR
MNTOPT_ACL
Definition at line 72 of file dt_object.h.
Function Documentation
static struct lu_device* dt2lu_dev (struct dt_device * d) [static, read]
Definition at line 1774 of file dt_object.h.
References dt_device::dd_lu_dev.
Referenced by distribute_txn_assign_batchid(), distribute_txn_insert_by_batchid(), lfsck_object_find_by_dev(), lfsck_object_find_by_dev_nowait(), and top_trans_committed_cb().
int dt_declare_version_set (const struct lu_env * env, struct dt_object * o, struct thandle * th)
Definition at line 521 of file dt_object.c.
References dt_declare_xattr_set(), LASSERT, lu_buf::lb_buf, lu_buf::lb_len, and XATTR_NAME_VERSION.
Referenced by lquota_disk_declare_write(), lquota_disk_update_ver(), nodemap_idx_delete(), nodemap_idx_insert(), nodemap_idx_update(), and tgt_txn_start_cb().
void dt_device_fini (struct dt_device * dev)
Definition at line 164 of file dt_object.c.
References dt_device::dd_lu_dev, and lu_device_fini().
Referenced by lod_device_free(), mgs_device_free(), ofd_device_free(), osd_device_alloc(), osd_device_free(), and osp_device_free().
int dt_device_init (struct dt_device * dev, struct lu_device_type * t)
Definition at line 157 of file dt_object.c.
References dt_device::dd_lu_dev, dt_device::dd_txn_callbacks, INIT_LIST_HEAD, and lu_device_init().
Referenced by lod_device_alloc(), mgs_device_alloc(), ofd_device_alloc(), osd_device_alloc(), osp_device_alloc(), and qmt_device_alloc().
struct dt_object* dt_find_or_create (const struct lu_env * env, struct dt_device * dt, const struct lu_fid * fid, struct dt_object_format * dof, struct lu_attr * attr) [read]
Definition at line 388 of file dt_object.c.
References CDEBUG, D_OTHER, DFID, dt_object::do_lu, dt_create(), dt_declare_create(), dt_locate(), dt_object_exists(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), ENTRY, GOTO, LASSERT, lu_object_put(), PFID, and RETURN.
Referenced by distribute_txn_commit_batchid_init(), fld_index_init(), ofd_fs_setup(), ofd_seq_load(), osp_find_or_create_local_file(), seq_store_init(), and tgt_init().
int dt_index_read (const struct lu_env * env, struct dt_device * dev, struct idx_info * ii, const struct lu_rdpg * rdpg)
Walk key/record pairs of an index and copy them into 4KB containers to be transferred over the network.
This is the common handler for OBD_IDX_READ RPC processing.
Parameters:
env - is the environment passed by the caller
dev - is the dt_device storing the index
ii - is the idx_info structure packed by the client in the OBD_IDX_READ request
rdpg - is the lu_rdpg descriptor
Return values:
on success, return sum (in bytes) of all filled containers
appropriate error otherwise.
Definition at line 911 of file dt_object.c.
References dt_index_features::dif_flags, dt_index_features::dif_keysize_max, dt_index_features::dif_recsize_max, dt_object::do_index_ops, dt_object_operations::do_index_try, dt_object::do_lu, dt_object::do_ops, DT_IND_NONUNQ, DT_IND_VARKEY, DT_IND_VARREC, dt_index_feat_select(), dt_index_page_build(), dt_index_walk(), dt_locate(), dt_object_exists(), dt_read_lock(), dt_read_unlock(), dt_version_get(), ENTRY, fid_is_layout_rbtree(), fid_is_norm(), fid_is_quota(), GOTO, idx_info::ii_count, II_END_OFF, idx_info::ii_fid, II_FL_NOHASH, II_FL_NOKEY, II_FL_NONUNQ, II_FL_VARKEY, II_FL_VARREC, idx_info::ii_flags, idx_info::ii_hash_end, idx_info::ii_keysize, idx_info::ii_recsize, idx_info::ii_version, LASSERT, lu_object_attr(), lu_object_put(), LU_PAGE_SIZE, RETURN, and lu_rdpg::rp_count.
Referenced by tgt_obd_idx_read().
int dt_index_walk (const struct lu_env * env, struct dt_object * obj, const struct lu_rdpg * rdpg, dt_index_page_build_t filler, void * arg)
Definition at line 812 of file dt_object.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, ENTRY, GOTO, LASSERT, LU_PAGE_COUNT, LU_PAGE_SIZE, min_t, RETURN, lu_rdpg::rp_attrs, lu_rdpg::rp_count, lu_rdpg::rp_hash, and lu_rdpg::rp_pages.
Referenced by dt_index_read(), and mdd_readpage().
static struct dt_object* dt_locate (const struct lu_env * env, struct dt_device * dev, const struct lu_fid * fid) [static, read]
Definition at line 1926 of file dt_object.h.
References dt_device::dd_lu_dev, dt_locate_at(), lu_device::ld_site, and lu_site::ls_top_dev.
Referenced by acct_obj_lookup(), dt_find_entry(), dt_find_or_create(), dt_index_read(), dt_reg_open(), dt_store_resolve(), fld_index_init(), lfsck_bookmark_setup(), lfsck_layout_get_def_stripesize(), lfsck_layout_lastid_load(), lfsck_layout_setup(), lfsck_namespace_reset(), lfsck_namespace_setup(), lfsck_rbtree_setup(), lfsck_register(), llog_osd_dir_get(), llog_osd_get_cat_list(), llog_osd_get_regular_fid_dir(), llog_osd_put_cat_list(), local_file_find_or_create_with_fid(), local_index_find_or_create_with_fid(), local_object_unlink(), lod_prepare(), lquota_disk_dir_find_create(), lquota_disk_find_create(), lquota_disk_slv_find(), mdd_local_file_create(), orph_index_init(), osd_quota_migration(), out_handle(), qmt_lvbo_init(), quota_obj_lookup(), tgt_blocking_ast(), and update_recovery_exec().
struct dt_object* dt_locate_at (const struct lu_env * env, struct dt_device * dev, const struct lu_fid * fid, struct lu_device * top_dev, const struct lu_object_conf * conf) [read]
Definition at line 236 of file dt_object.c.
References dt_device::dd_lu_dev, LASSERT, list_for_each_entry, lu_object::lo_dev, lu_object::lo_header, lu_object::lo_linkage, lu_object_header::loh_layers, and lu_object_find_at().
Referenced by dt_locate(), llog_osd_open(), lod_parse_dir_striping(), lod_prep_md_striped_create(), lquota_disk_dir_find_create(), ls_locate(), mgc_fs_setup(), mgs_fs_setup(), and nidtbl_read_version().
int dt_lookup_dir (const struct lu_env * env, struct dt_object * dir, const char * name, struct lu_fid * fid)
lookup fid for object named name in directory dir.
Definition at line 224 of file dt_object.c.
References dt_lookup(), and dt_try_as_dir().
Referenced by dt_find_entry(), dt_reg_open(), lastid_compat_check(), llog_osd_open(), local_file_find_or_create(), local_file_find_or_create_with_fid(), local_index_find_or_create(), local_index_find_or_create_with_fid(), local_object_unlink(), lquota_disk_for_each_slv(), lquota_disk_slv_find(), nidtbl_read_version(), and osd_quota_migration().
enum dt_format_type dt_mode_to_dft (__u32 mode)
Definition at line 192 of file dt_object.c.
References DFT_DIR, DFT_NODE, DFT_REGULAR, DFT_SYM, and LBUG.
Referenced by distribute_txn_commit_batchid_init(), lfsck_create_lpf(), lfsck_layout_lastid_create(), lfsck_layout_recreate_parent(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_repair_dangling(), llog_osd_create(), llog_osd_create_new_object(), llog_osd_declare_create(), llog_osd_declare_new_object(), llog_osd_get_cat_list(), local_file_find_or_create(), local_file_find_or_create_with_fid(), local_oid_storage_init(), mdd_declare_object_create_internal(), ofd_fs_setup(), ofd_precreate_objects(), ofd_seq_load(), out_create(), tgt_init(), and update_recovery_create().
static struct dt_object* dt_object_child (struct dt_object * o) [static, read]
Definition at line 1806 of file dt_object.h.
References dt_object::do_lu, and lu_object_next().
Referenced by lod_ah_init(), lod_attr_get(), lod_attr_set(), lod_cache_parent_lmv_striping(), lod_cache_parent_lov_striping(), lod_declare_attr_set(), lod_declare_index_delete(), lod_declare_index_insert(), lod_declare_init_size(), lod_declare_object_create(), lod_declare_object_destroy(), lod_declare_punch(), lod_declare_ref_add(), lod_declare_ref_del(), lod_declare_striped_object(), lod_declare_write(), lod_declare_xattr_del(), lod_declare_xattr_set(), lod_dir_declare_create_stripes(), lod_dir_declare_xattr_set(), lod_generate_and_set_lovea(), lod_get_ea(), lod_index_delete(), lod_index_insert(), lod_index_lookup(), lod_index_try(), lod_it_init(), lod_load_lmv_shards(), lod_load_striping(), lod_load_striping_locked(), lod_object_create(), lod_object_destroy(), lod_object_lock(), lod_object_read_lock(), lod_object_read_unlock(), lod_object_sync(), lod_object_unlock(), lod_object_write_lock(), lod_object_write_locked(), lod_object_write_unlock(), lod_punch(), lod_read(), lod_ref_add(), lod_ref_del(), lod_write(), lod_xattr_del(), lod_xattr_del_internal(), lod_xattr_get(), lod_xattr_list(), lod_xattr_set(), lod_xattr_set_internal(), lod_xattr_set_lmv(), and update_recovery_exec().
static int dt_object_exists (const struct dt_object * dt) [inline, static]
Definition at line 1790 of file dt_object.h.
References dt_object::do_lu, and lu_object_exists.
Referenced by __lfsck_links_read(), __local_file_create(), __osd_object_attr_get(), __osd_xattr_declare_set(), __osd_xattr_del(), __osd_xattr_get(), acct_obj_lookup(), dt_find_or_create(), dt_index_read(), fld_index_init(), lastid_compat_check(), lfsck_assistant_object_load(), lfsck_create_lpf(), lfsck_layout_check_parent(), lfsck_layout_lastid_create(), lfsck_layout_lastid_load(), lfsck_layout_master_check_pairs(), lfsck_layout_master_exec_oit(), lfsck_layout_scan_orphan_one(), lfsck_layout_slave_conditional_destroy(), lfsck_layout_slave_repair_pfid(), lfsck_master_oit_engine(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_double_scan_one(), lfsck_namespace_double_scan_one_trace_file(), lfsck_namespace_dsd_multiple(), lfsck_namespace_dsd_single(), lfsck_namespace_handle_striped_master(), lfsck_namespace_in_notify(), lfsck_namespace_repair_bad_name_hash(), lfsck_namespace_replace_cond(), lfsck_namespace_scan_local_lpf(), lfsck_namespace_scan_local_lpf_one(), lfsck_namespace_verify_stripe_slave(), lfsck_needs_scan_dir(), lfsck_orphan_it_next(), lfsck_prep(), lfsck_verify_lpf(), lfsck_verify_lpf_pairs(), llog_destroy(), llog_osd_create(), llog_osd_declare_create(), llog_osd_destroy(), llog_osd_exist(), llog_osd_get_cat_list(), llog_osd_next_block(), llog_osd_open(), llog_osd_prev_block(), llog_osd_put_cat_list(), llog_trans_destroy(), local_object_create(), local_object_declare_create(), local_oid_storage_init(), lod_ah_init(), lod_attr_set(), lod_declare_attr_set(), lod_declare_striped_object(), lod_declare_xattr_set(), lod_index_try(), lod_load_striping_locked(), lquota_disk_declare_write(), lquota_disk_read(), lquota_disk_write(), osd_attr_get(), osd_attr_set(), osd_bufs_get(), osd_bufs_put(), osd_declare_attr_set(), osd_declare_dir_delete(), osd_declare_index_delete(), osd_declare_object_destroy(), osd_declare_object_ref_del(), osd_declare_write(), osd_declare_write_commit(), osd_declare_xattr_del(), osd_declare_xattr_set(), osd_dir_insert(), osd_index_ea_delete(), osd_index_ea_insert(), osd_index_iam_delete(), osd_index_iam_insert(), osd_index_iam_lookup(), osd_index_insert(), osd_index_try(), osd_it_ea_init(), osd_it_iam_init(), osd_object_create(), osd_object_destroy(), osd_object_ea_create(), osd_object_ref_add(), osd_object_ref_del(), osd_punch(), osd_quota_migration(), osd_read(), osd_read_prep(), osd_write(), osd_write_commit(), osd_write_prep(), osd_xattr_del(), osd_xattr_get(), osd_xattr_list(), osp_declare_attr_set(), out_tx_index_insert_exec(), qmt_lvbo_init(), quota_obj_lookup(), tgt_blocking_ast(), and update_recovery_create().
void dt_object_fini (struct dt_object * obj)
Definition at line 178 of file dt_object.c.
References dt_object::do_lu, and lu_object_fini().
Referenced by ls_object_free(), mgs_object_free(), osd_object_free(), and osp_object_free().
int dt_object_init (struct dt_object * obj, struct lu_object_header * h, struct lu_device * d)
Definition at line 170 of file dt_object.c.
References dt_object::do_lu, and lu_object_init().
Referenced by lod_object_alloc(), ls_object_alloc(), mgs_object_alloc(), osd_object_alloc(), and osp_object_alloc().
static struct dt_object* dt_object_locate (struct dt_object * dto, struct dt_device * dt_dev) [static, read]
Definition at line 1934 of file dt_object.h.
References dt_device::dd_lu_dev, dt_object::do_lu, list_for_each_entry, lu_object::lo_dev, lu_object::lo_header, lu_object::lo_linkage, and lu_object_header::loh_layers.
Referenced by tgt_client_data_write(), tgt_last_rcvd_update(), tgt_reply_data_write(), tgt_reply_header_write(), tgt_server_data_write(), and tgt_txn_start_cb().
static int dt_object_lock (const struct lu_env * env, struct dt_object * o, struct lustre_handle * lh, struct ldlm_enqueue_info * einfo, union ldlm_policy_data * policy) [inline, static]
Definition at line 1990 of file dt_object.h.
References dt_object_operations::do_object_lock, dt_object::do_ops, and LASSERT.
Referenced by __lfsck_ibits_lock(), lod_object_lock(), and mdd_object_lock().
static int dt_object_remote (const struct dt_object * dt) [inline, static]
Definition at line 1795 of file dt_object.h.
References dt_object::do_lu, and lu_object_remote.
Referenced by __lfsck_ibits_lock(), lfsck_layout_check_parent(), lfsck_layout_scan_orphan_one(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_double_scan_dir(), lfsck_namespace_links_remove(), lfsck_namespace_repair_nlink(), lfsck_namespace_repair_unmatched_pairs(), lfsck_namespace_scan_local_lpf_one(), lfsck_namespace_set_lmv_master(), lfsck_namespace_striped_dir_rescan(), lfsck_namespace_update_lmv(), lfsck_prep(), lfsck_verify_lpf(), llog_cat_declare_add_rec(), llog_osd_write_rec(), llog_process_thread(), lod_attr_set(), lod_cache_parent_striping(), lod_declare_attr_set(), lod_declare_object_create(), lod_declare_punch(), lod_declare_striped_object(), lod_object_lock(), lod_object_unlock(), lod_punch(), lod_sub_get_thandle(), lod_xattr_set(), osd_ah_init(), osd_attr_get(), osd_attr_set(), osd_declare_object_ref_del(), osd_declare_xattr_del(), osd_index_declare_ea_delete(), osd_index_declare_ea_insert(), osd_index_ea_delete(), osd_index_ea_insert(), osd_index_iam_delete(), osd_index_iam_insert(), osd_index_iam_lookup(), osd_mkfile(), osd_object_create(), osd_object_ea_create(), osd_object_ref_add(), osd_object_ref_del(), osd_xattr_del(), osd_xattr_get(), and osd_xattr_list().
static int dt_object_sync (const struct lu_env * env, struct dt_object * o, __u64 start, __u64 end) [inline, static]
Definition at line 2015 of file dt_object.h.
References dt_object_operations::do_object_sync, dt_object::do_ops, and LASSERT.
Referenced by lod_object_sync(), mdd_object_sync(), and tgt_sync().
static int dt_object_unlock (const struct lu_env * env, struct dt_object * o, struct ldlm_enqueue_info * einfo, union ldlm_policy_data * policy) [inline, static]
Definition at line 2001 of file dt_object.h.
References dt_object_operations::do_object_unlock, dt_object::do_ops, and LASSERT.
Referenced by mdd_object_unlock().
int dt_path_parser (const struct lu_env * env, char * path, dt_entry_func_t entry_func, void * data)
Abstract function which parses path name.
This function feeds path component to entry_func.
Definition at line 286 of file dt_object.c.
Referenced by dt_store_resolve().
int dt_read (const struct lu_env * env, struct dt_object * dt, struct lu_buf * buf, loff_t * pos)
Generic read helper.
May return an error for partial reads.
Parameters:
env lustre environment
dt object to be read
buf lu_buf to be filled, with buffer pointer and length
pos position to start reading, updated as data is read
Return values:
real size of data read
-ve errno on failure
Definition at line 469 of file dt_object.c.
References dt_body_operations::dbo_read, dt_object::do_body_ops, and LASSERTF.
Referenced by distribute_txn_commit_batchid_init(), lfsck_layout_lastid_load(), lfsck_layout_load(), lfsck_layout_load_bitmap(), llog_osd_next_block(), llog_osd_prev_block(), llog_osd_read_header(), mdd_readlink(), nidtbl_read_version(), out_read(), and seq_store_read().
int dt_record_read (const struct lu_env * env, struct dt_object * dt, struct lu_buf * buf, loff_t * pos)
Read structures of fixed size from storage.
Unlike dt_read(), using dt_record_read() will return an error for partial reads.
Parameters:
env lustre environment
dt object to be read
buf lu_buf to be filled, with buffer pointer and length
pos position to start reading, updated as data is read
Return values:
0 on successfully reading full buffer
-EFAULT on short read
-ve errno on failure
Definition at line 490 of file dt_object.c.
References dt_body_operations::dbo_read, dt_object::do_body_ops, LASSERTF, lu_buf::lb_len, and size.
Referenced by lastid_compat_check(), lfsck_bookmark_load(), lfsck_layout_lastid_reload(), llog_osd_get_cat_list(), local_oid_storage_init(), ofd_seq_load(), osp_init_last_objid(), osp_init_last_seq(), tgt_client_data_read(), tgt_reply_data_read(), tgt_reply_header_read(), and tgt_server_data_read().
int dt_record_write (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, loff_t * pos, struct thandle * th)
Definition at line 504 of file dt_object.c.
References dt_body_operations::dbo_write, dt_object::do_body_ops, LASSERT, LASSERTF, lu_buf::lb_len, and size.
Referenced by distribute_txn_commit_batchid_update(), lfsck_bookmark_store(), lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_layout_lastid_create(), lfsck_layout_lastid_store(), lfsck_layout_store(), llog_osd_pad(), llog_osd_put_cat_list(), llog_osd_write_rec(), local_object_create(), local_oid_storage_init(), nidtbl_update_version(), ofd_health_check(), ofd_precreate_objects(), ofd_seq_last_oid_write(), osp_object_create(), osp_write_last_oid_seq_files(), osp_write_local_file(), out_tx_write_exec(), seq_store_update(), tgt_client_data_write(), tgt_reply_data_write(), tgt_reply_header_write(), and tgt_server_data_write().
struct dt_object* dt_store_open (const struct lu_env * env, struct dt_device * dt, const char * dirname, const char * filename, struct lu_fid * fid) [read]
Open dt object named filename from dirname directory.
Parameters:
dt dt device
fid on success, object fid is stored in *fid
Definition at line 368 of file dt_object.c.
References dir, dt_object::do_lu, dt_reg_open(), dt_store_resolve(), and lu_object_put().
struct dt_object* dt_store_resolve (const struct lu_env * env, struct dt_device * dt, const char * path, struct lu_fid * fid) [read]
Definition at line 312 of file dt_object.c.
References dt_device::dd_ops, dt_find_hint::dfh_dt, dt_find_hint::dfh_fid, dt_find_hint::dfh_o, dt_find_entry(), dt_info(), dt_locate(), dt_path_parser(), dt_device_operations::dt_root_get, dt_thread_info::dti_buf, dt_thread_info::dti_dfh, and strlcpy().
Referenced by dt_store_open().
static int dt_trans_cb_add (struct thandle * th, struct dt_txn_commit_cb * dcb) [inline, static]
Definition at line 2077 of file dt_object.h.
References dt_txn_commit_cb::dcb_magic, dt_device::dd_ops, dt_device_operations::dt_trans_cb_add, LASSERT, thandle::th_dev, and TRANS_COMMIT_CB_MAGIC.
Referenced by distribute_txn_commit_batchid_update(), lod_trans_cb_add(), ofd_grant_commit_cb_add(), ofd_soft_sync_cb_add(), seq_update_cb_add(), sub_thandle_register_commit_cb(), sub_thandle_register_stop_cb(), tgt_last_commit_cb_add(), and tgt_new_client_cb_add().
static struct thandle* dt_trans_create (const struct lu_env * env, struct dt_device * d) [static, read]
Definition at line 2047 of file dt_object.h.
References dt_device::dd_ops, dt_device_operations::dt_trans_create, and LASSERT.
Referenced by __lfsck_layout_update_pfid(), __local_file_create(), distribute_txn_commit_batchid_update(), dt_find_or_create(), fld_insert_entry(), lfsck_bookmark_store(), lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_disable_master_lmv(), lfsck_layout_conflict_create(), lfsck_layout_destroy_orphan(), lfsck_layout_lastid_create(), lfsck_layout_lastid_store(), lfsck_layout_master_exec_oit(), lfsck_layout_recreate_lovea(), lfsck_layout_recreate_parent(), lfsck_layout_repair_dangling(), lfsck_layout_repair_multiple_references(), lfsck_layout_repair_owner(), lfsck_layout_repair_unmatched_pair(), lfsck_layout_slave_conditional_destroy(), lfsck_layout_store(), lfsck_lpf_remove_name_entry(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_insert_normal(), lfsck_namespace_insert_orphan(), lfsck_namespace_links_remove(), lfsck_namespace_rebuild_linkea(), lfsck_namespace_repair_dangling(), lfsck_namespace_repair_dirent(), lfsck_namespace_repair_nlink(), lfsck_namespace_repair_unmatched_pairs(), lfsck_namespace_replace_cond(), lfsck_namespace_scan_local_lpf_one(), lfsck_namespace_shrink_linkea(), lfsck_namespace_store(), lfsck_namespace_trace_update(), lfsck_namespace_update_lmv(), lfsck_update_name_entry(), lfsck_verify_linkea(), llog_cancel_rec(), llog_cat_add(), llog_cat_new_log(), llog_destroy(), llog_open_create(), llog_osd_get_cat_list(), llog_osd_put_cat_list(), llog_truncate(), llog_write(), local_object_unlink(), local_oid_storage_init(), lquota_disk_update_ver(), lquota_disk_write_glb(), mdt_empty_transno(), nidtbl_update_version(), nodemap_idx_delete(), nodemap_idx_insert(), nodemap_idx_update(), ofd_health_check(), ofd_seq_last_oid_write(), ofd_trans_create(), osp_get_storage_thandle(), osp_write_last_oid_seq_files(), osp_write_local_file(), out_tx_start(), qmt_trans_start_with_slv(), qsd_update_index(), seq_store_update(), sub_thandle_trans_create(), tgt_client_data_update(), tgt_reply_header_write(), tgt_server_data_update(), tgt_truncate_last_rcvd(), thandle_get_sub_by_dt(), and top_trans_create().
static int dt_trans_start (const struct lu_env * env, struct dt_device * d, struct thandle * th) [inline, static]
Definition at line 2054 of file dt_object.h.
References dt_device::dd_ops, dt_device_operations::dt_trans_start, and LASSERT.
Referenced by mdt_empty_transno(), ofd_trans_start(), osp_trans_start(), out_trans_start(), tgt_reply_header_write(), tgt_server_data_update(), and top_trans_start().
static int dt_trans_start_local (const struct lu_env * env, struct dt_device * d, struct thandle * th) [inline, static]
Definition at line 2062 of file dt_object.h.
References dt_device::dd_ops, dt_device_operations::dt_trans_start, LASSERT, and thandle::th_local.
Referenced by __lfsck_layout_update_pfid(), __local_file_create(), distribute_txn_commit_batchid_update(), dt_find_or_create(), fld_insert_entry(), lfsck_bookmark_store(), lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_disable_master_lmv(), lfsck_layout_conflict_create(), lfsck_layout_destroy_orphan(), lfsck_layout_lastid_create(), lfsck_layout_lastid_store(), lfsck_layout_master_exec_oit(), lfsck_layout_recreate_lovea(), lfsck_layout_recreate_parent(), lfsck_layout_repair_dangling(), lfsck_layout_repair_multiple_references(), lfsck_layout_repair_owner(), lfsck_layout_repair_unmatched_pair(), lfsck_layout_slave_conditional_destroy(), lfsck_layout_store(), lfsck_lpf_remove_name_entry(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_insert_normal(), lfsck_namespace_insert_orphan(), lfsck_namespace_links_remove(), lfsck_namespace_rebuild_linkea(), lfsck_namespace_repair_dangling(), lfsck_namespace_repair_dirent(), lfsck_namespace_repair_nlink(), lfsck_namespace_repair_unmatched_pairs(), lfsck_namespace_replace_cond(), lfsck_namespace_scan_local_lpf_one(), lfsck_namespace_shrink_linkea(), lfsck_namespace_store(), lfsck_namespace_trace_update(), lfsck_namespace_update_lmv(), lfsck_update_name_entry(), lfsck_verify_linkea(), llog_cancel_rec(), llog_cat_add(), llog_cat_new_log(), llog_destroy(), llog_open_create(), llog_osd_get_cat_list(), llog_osd_put_cat_list(), llog_truncate(), llog_write(), local_object_unlink(), local_oid_storage_init(), lquota_disk_update_ver(), lquota_disk_write_glb(), nidtbl_update_version(), nodemap_idx_delete(), nodemap_idx_insert(), nodemap_idx_update(), ofd_health_check(), ofd_object_destroy(), ofd_precreate_objects(), ofd_seq_last_oid_write(), ofd_write_attr_set(), osp_write_last_oid_seq_files(), osp_write_local_file(), qmt_trans_start_with_slv(), qsd_update_index(), seq_store_update(), tgt_client_data_update(), and tgt_truncate_last_rcvd().
static int dt_trans_stop (const struct lu_env * env, struct dt_device * d, struct thandle * th) [inline, static]
Definition at line 2070 of file dt_object.h.
References dt_device::dd_ops, dt_device_operations::dt_trans_stop, and LASSERT.
Referenced by __lfsck_layout_update_pfid(), __local_file_create(), distribute_txn_commit_batchid_update(), dt_find_or_create(), fld_insert_entry(), lfsck_bookmark_store(), lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_disable_master_lmv(), lfsck_layout_conflict_create(), lfsck_layout_destroy_orphan(), lfsck_layout_lastid_create(), lfsck_layout_lastid_store(), lfsck_layout_master_exec_oit(), lfsck_layout_recreate_lovea(), lfsck_layout_recreate_parent(), lfsck_layout_repair_multiple_references(), lfsck_layout_slave_conditional_destroy(), lfsck_layout_store(), lfsck_layout_trans_stop(), lfsck_lpf_remove_name_entry(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_insert_normal(), lfsck_namespace_insert_orphan(), lfsck_namespace_links_remove(), lfsck_namespace_rebuild_linkea(), lfsck_namespace_repair_dangling(), lfsck_namespace_repair_dirent(), lfsck_namespace_repair_nlink(), lfsck_namespace_repair_unmatched_pairs(), lfsck_namespace_replace_cond(), lfsck_namespace_scan_local_lpf_one(), lfsck_namespace_shrink_linkea(), lfsck_namespace_store(), lfsck_namespace_trace_update(), lfsck_namespace_update_lmv(), lfsck_update_name_entry(), lfsck_verify_linkea(), llog_cancel_rec(), llog_cat_add(), llog_cat_new_log(), llog_destroy(), llog_open_create(), llog_osd_get_cat_list(), llog_osd_put_cat_list(), llog_truncate(), llog_write(), local_object_unlink(), local_oid_storage_init(), lquota_disk_update_ver(), lquota_disk_write_glb(), mdt_empty_transno(), nidtbl_update_version(), nodemap_idx_delete(), nodemap_idx_insert(), nodemap_idx_update(), ofd_health_check(), ofd_seq_last_oid_write(), ofd_trans_stop(), ofd_write_attr_set(), osp_trans_stop(), osp_write_last_oid_seq_files(), osp_write_local_file(), out_trans_stop(), qmt_dqacq0(), qmt_set(), qmt_trans_start_with_slv(), qsd_update_index(), seq_store_update(), tgt_client_data_update(), tgt_reply_header_write(), tgt_server_data_update(), tgt_truncate_last_rcvd(), thandle_get_sub_by_dt(), and top_trans_stop().
int dt_try_as_dir (const struct lu_env * env, struct dt_object * obj)
Definition at line 184 of file dt_object.c.
References dt_object::do_index_ops, dt_object_operations::do_index_try, dt_object::do_ops, and dt_directory_features.
Referenced by __local_file_create(), __mdd_index_delete_only(), __mdd_index_insert_only(), __mdd_lookup(), dt_lookup_dir(), lfsck_allow_regenerate_master_lmv(), lfsck_assistant_object_load(), lfsck_bookmark_setup(), lfsck_create_lpf(), lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_layout_setup(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_double_scan_dir(), lfsck_namespace_double_scan_one(), lfsck_namespace_dsd_multiple(), lfsck_namespace_dsd_single(), lfsck_namespace_insert_normal(), lfsck_namespace_repair_dangling(), lfsck_namespace_repair_dirent(), lfsck_namespace_replace_cond(), lfsck_namespace_reset(), lfsck_namespace_scan_local_lpf(), lfsck_namespace_scan_shard(), lfsck_namespace_setup(), lfsck_namespace_verify_stripe_slave(), lfsck_open_dir(), lfsck_parent_fid(), lfsck_register(), lfsck_verify_lpf(), lfsck_verify_lpf_pairs(), llog_osd_dir_get(), llog_osd_get_regular_fid_dir(), lod_dir_declare_create_stripes(), lod_load_lmv_shards(), lquota_disk_dir_find_create(), mdd_dir_is_empty(), mdd_migrate_entries(), mdd_readpage_sanity_check(), mdo_declare_index_delete(), mdo_declare_index_insert(), mgs_fs_setup(), orph_index_init(), orph_index_insert(), out_index_delete_add_exec(), out_index_insert_add_exec(), out_index_lookup(), out_obj_index_delete(), out_obj_index_insert(), update_recovery_index_delete(), and update_recovery_index_insert().
void dt_txn_callback_add (struct dt_device * dev, struct dt_txn_callback * cb)
Definition at line 67 of file dt_object.c.
References dt_device::dd_txn_callbacks, dt_txn_callback::dtc_linkage, and list_add().
Referenced by mdt_fs_setup(), osp_sync_id_traction_init(), and tgt_init().
void dt_txn_callback_del (struct dt_device * dev, struct dt_txn_callback * cb)
Definition at line 73 of file dt_object.c.
References dt_txn_callback::dtc_linkage, and list_del_init().
Referenced by mdt_fs_cleanup(), osp_sync_id_traction_fini(), tgt_fini(), and tgt_init().
void dt_txn_hook_commit (struct thandle * txn)
Definition at line 139 of file dt_object.c.
References cb(), dt_device::dd_txn_callbacks, dt_txn_callback::dtc_cookie, dt_txn_callback::dtc_linkage, dt_txn_callback::dtc_txn_commit, list_for_each_entry, thandle::th_dev, and thandle::th_local.
Referenced by osd_trans_commit_cb().
int dt_txn_hook_start (const struct lu_env * env, struct dt_device * dev, struct thandle * txn)
Definition at line 79 of file dt_object.c.
References cb(), dt_device::dd_txn_callbacks, dt_txn_callback::dtc_cookie, dt_txn_callback::dtc_linkage, dt_txn_callback::dtc_tag, dt_txn_callback::dtc_txn_start, lu_context::lc_tags, lu_env::le_ctx, list_for_each_entry, thandle::th_local, and thandle::th_top.
Referenced by osd_trans_start().
int dt_txn_hook_stop (const struct lu_env * env, struct thandle * txn)
Definition at line 109 of file dt_object.c.
References cb(), dt_device::dd_txn_callbacks, dt_txn_callback::dtc_cookie, dt_txn_callback::dtc_linkage, dt_txn_callback::dtc_tag, dt_txn_callback::dtc_txn_stop, lu_context::lc_tags, lu_env::le_ctx, list_for_each_entry, thandle::th_dev, thandle::th_local, and thandle::th_top.
Referenced by osd_trans_stop().
dt_obj_version_t dt_version_get (const struct lu_env * env, struct dt_object * o)
Definition at line 553 of file dt_object.c.
References CDEBUG, D_INODE, dt_xattr_get(), LASSERT, lu_buf::lb_buf, lu_buf::lb_len, version, and XATTR_NAME_VERSION.
Referenced by dt_index_read(), lquota_disk_write(), mdt_ioc_version_get(), mdt_obj_version_get(), nodemap_inc_version(), ofd_echo_getattr(), ofd_getattr_hdl(), ofd_ioc_get_obj_version(), ofd_version_get_check(), osd_quota_migration(), qmt_lvbo_fill(), qmt_pool_new_conn(), qmt_pool_prepare(), qsd_qtype_init(), and tgt_sync().
void dt_version_set (const struct lu_env * env, struct dt_object * o, dt_obj_version_t version, struct thandle * th)
Definition at line 535 of file dt_object.c.
References CDEBUG, D_INODE, dt_xattr_set(), LASSERT, lu_buf::lb_buf, lu_buf::lb_len, and XATTR_NAME_VERSION.
Referenced by lquota_disk_update_ver(), lquota_disk_write(), nodemap_inc_version(), tgt_last_rcvd_update(), and tgt_last_rcvd_update_echo().
struct dt_object* local_file_find_or_create (const struct lu_env * env, struct local_oid_storage * los, struct dt_object * parent, const char * name, __u32 mode) [read]
Definition at line 432 of file local_storage.c.
References __local_file_create(), dt_object_format::dof_type, dt2ls_dev(), dt_info(), dt_lookup_dir(), dt_mode_to_dft(), dt_thread_info::dti_attr, dt_thread_info::dti_dof, dt_thread_info::dti_fid, lu_attr::la_mode, LA_MODE, lu_attr::la_valid, LASSERT, local_object_fid_generate(), local_oid_storage::los_dev, and ls_locate().
Referenced by lfsck_bookmark_setup(), lfsck_layout_setup(), lfsck_register(), lquota_disk_dir_find_create(), mdd_local_file_create(), mgc_fs_setup(), mgs_fs_setup(), and nidtbl_update_version().
struct dt_object* local_file_find_or_create_with_fid (const struct lu_env * env, struct dt_device * dt, const struct lu_fid * fid, struct dt_object * parent, const char * name, __u32 mode) [read]
Definition at line 469 of file local_storage.c.
References __local_file_create(), dt_object::do_lu, dt_object_format::dof_type, dt_info(), dt_locate(), dt_lookup_dir(), dt_mode_to_dft(), dt_thread_info::dti_attr, dt_thread_info::dti_dof, dt_thread_info::dti_fid, lu_attr::la_mode, LA_MODE, lu_attr::la_valid, LASSERT, lu_object::lo_header, lu_object_header::loh_fid, ls_device_get(), ls_device_put(), and lu_object_put_nocache().
Referenced by lod_prepare(), and mdd_local_file_create().
struct dt_object* local_index_find_or_create (const struct lu_env * env, struct local_oid_storage * los, struct dt_object * parent, const char * name, __u32 mode, const struct dt_index_features * ft) [read]
Definition at line 519 of file local_storage.c.
References __local_file_create(), DFT_INDEX, dt_object_format::dof_idx, dt_object_format::dof_type, dt2ls_dev(), dt_info(), dt_lookup_dir(), dt_thread_info::dti_attr, dt_thread_info::dti_dof, dt_thread_info::dti_fid, lu_attr::la_mode, LA_MODE, lu_attr::la_valid, LASSERT, local_object_fid_generate(), local_oid_storage::los_dev, ls_locate(), and dt_object_format::u.
Referenced by lfsck_namespace_load_one_trace_file(), lfsck_namespace_setup(), lquota_disk_find_create(), and mgs_fs_setup().
struct dt_object* local_index_find_or_create_with_fid (const struct lu_env * env, struct dt_device * dt, const struct lu_fid * fid, struct dt_object * parent, const char * name, __u32 mode, const struct dt_index_features * ft) [read]
Definition at line 560 of file local_storage.c.
References __local_file_create(), DFT_INDEX, dt_object::do_lu, dt_object_format::dof_idx, dt_object_format::dof_type, dt_info(), dt_locate(), dt_lookup_dir(), dt_thread_info::dti_attr, dt_thread_info::dti_dof, dt_thread_info::dti_fid, lu_attr::la_mode, LA_MODE, lu_attr::la_valid, LASSERT, lu_object::lo_header, lu_object_header::loh_fid, ls_device_get(), ls_device_put(), lu_fid_eq(), lu_object_put_nocache(), and dt_object_format::u.
Referenced by lquota_disk_glb_find_create(), and lquota_disk_slv_find_create().
int local_object_create (const struct lu_env * env, struct local_oid_storage * los, struct dt_object * o, struct lu_attr * attr, struct dt_object_format * dof, struct thandle * th)
Definition at line 251 of file local_storage.c.
References cpu_to_le64, dt_create(), dt_info(), dt_object_exists(), dt_record_write(), dt_thread_info::dti_lb, dt_thread_info::dti_off, ENTRY, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, local_oid_storage::los_id_lock, local_oid_storage::los_last_oid, local_oid_storage::los_obj, and RETURN.
Referenced by __local_file_create(), and llog_osd_create_new_object().
int local_object_declare_create (const struct lu_env * env, struct local_oid_storage * los, struct dt_object * o, struct lu_attr * attr, struct dt_object_format * dof, struct thandle * th)
Definition at line 218 of file local_storage.c.
References dt_declare_create(), dt_declare_record_write(), dt_declare_xattr_set(), dt_info(), dt_object_exists(), dt_thread_info::dti_lb, dt_thread_info::dti_lma, ENTRY, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, local_oid_storage::los_obj, RETURN, and XATTR_NAME_LMA.
Referenced by __local_file_create(), and llog_osd_declare_new_object().
int local_object_fid_generate (const struct lu_env * env, struct local_oid_storage * los, struct lu_fid * fid)
local file fid generation
Definition at line 196 of file local_storage.c.
References lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, LASSERT, local_oid_storage::los_dev, local_oid_storage::los_id_lock, local_oid_storage::los_last_oid, local_oid_storage::los_obj, and local_oid_storage::los_seq.
Referenced by llog_osd_open(), local_file_find_or_create(), and local_index_find_or_create().
int local_object_unlink (const struct lu_env * env, struct dt_device * dt, struct dt_object * parent, const char * name)
Definition at line 630 of file local_storage.c.
References dt_object::do_lu, dt_delete(), dt_destroy(), dt_info(), dt_insert(), dt_key, dt_locate(), dt_lookup_dir(), dt_ref_del(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), dt_thread_info::dti_dt_rec, dt_thread_info::dti_fid, ENTRY, GOTO, lu_object::lo_header, local_object_declare_unlink(), lu_object_header::loh_attr, lu_object_put_nocache(), dt_insert_rec::rec_fid, dt_insert_rec::rec_type, RETURN, stop, and unlikely.
Referenced by lfsck_namespace_load_one_trace_file().
void local_oid_storage_fini (const struct lu_env * env, struct local_oid_storage * los)
Definition at line 936 of file local_storage.c.
References dt_object::do_lu, dt2ls_dev(), LASSERT, list_del(), local_oid_storage::los_dev, local_oid_storage::los_list, local_oid_storage::los_obj, local_oid_storage::los_refcount, ls_device_put(), ls_device::ls_los_mutex, lu_object_put_nocache(), and OBD_FREE_PTR.
Referenced by lfsck_instance_cleanup(), llog_osd_cleanup(), llog_osd_setup(), lquota_disk_dir_find_create(), lquota_disk_find_create(), mdd_device_shutdown(), mdd_prepare(), mgc_fs_cleanup(), mgc_fs_setup(), mgs_fs_cleanup(), and mgs_fs_setup().
int local_oid_storage_init (const struct lu_env * env, struct dt_device * dev, const struct lu_fid * first_fid, struct local_oid_storage ** los)
Initialize local OID storage for required sequence.
That may be needed for services that uses local files and requires dynamic OID allocation for them.
Per each sequence we have an object with 'first_fid' identificator containing the counter for OIDs of locally created files with that sequence.
It is used now by llog subsystem and MGS for NID tables
Function gets first_fid to create counter object. All dynamic fids will be generated with the same sequence and incremented OIDs
Returned local_oid_storage is in-memory representaion of OID storage
Definition at line 803 of file local_storage.c.
References CERROR, cpu_to_le64, dt_object::do_lu, dt_object_format::dof_type, dt_create(), dt_declare_create(), dt_declare_record_write(), dt_info(), dt_los_find(), dt_mode_to_dft(), dt_object_exists(), dt_read_lock(), dt_read_unlock(), dt_record_read(), dt_record_write(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), dt_thread_info::dti_attr, dt_thread_info::dti_dof, dt_thread_info::dti_fid, dt_thread_info::dti_lb, dt_thread_info::dti_off, ENTRY, lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, fid_oid(), GOTO, lu_attr::la_mode, LA_MODE, LA_TYPE, lu_attr::la_valid, lastid_compat_check(), lu_buf::lb_buf, lu_buf::lb_len, lu_device::ld_obd, le64_to_cpu, list_add(), list_del(), lu_object::lo_dev, LPU64, ls_device_get(), ls_device_put(), ls_locate(), ls_device::ls_los_list, ls_device::ls_los_mutex, ls_device::ls_refcount, ls_device::ls_top_dev, lu_object_put_nocache(), LUSTRE_FID_LASTID_OID, OBD_ALLOC_PTR, OBD_FREE_PTR, obd_device::obd_name, OBIF_MAX_OID, and RETURN.
Referenced by lfsck_register(), llog_osd_setup(), lquota_disk_dir_find_create(), lquota_disk_find_create(), mdd_prepare(), mgc_fs_setup(), and mgs_fs_setup().
static struct dt_object* lu2dt (struct lu_object * l) [static, read]
Definition at line 1779 of file dt_object.h.
References dt_object::do_lu, LASSERT, lu_object::lo_dev, and lu_device_is_dt().
Referenced by lfsck_object_find_by_dev(), lfsck_object_find_by_dev_nowait(), lfsck_object_locate(), and mdt_obj2dt().
static struct dt_device* lu2dt_dev (struct lu_device * l) [static, read]
Definition at line 1743 of file dt_object.h.
References dt_device::dd_lu_dev, LASSERT, and lu_device_is_dt().
Referenced by distribute_txn_replay_handle(), fld_insert_entry(), lfsck_orphan_it_init(), llog_cancel_rec(), llog_cat_add(), llog_cat_new_log(), llog_destroy(), llog_open_create(), llog_osd_get_regular_fid_dir(), llog_osd_next_block(), llog_osd_prev_block(), llog_test_10(), llog_test_setup(), llog_truncate(), llog_write(), lod_add_device(), lod_connect_to_osd(), lquota_disk_write_glb(), lu2qmt_dev(), mdd_connect_to_next(), mdt_stack_init(), mgc_process_cfg_log(), mgs_connect_to_osd(), nodemap_idx_delete(), nodemap_idx_insert(), nodemap_idx_update(), ofd_connect_to_next(), ofd_stack_init(), osd_device_fini(), osd_start(), osp_connect_to_osd(), osp_md_object_lock(), qmt_connect_to_osd(), seq_store_update(), thandle_get_sub(), and update_recovery_exec().
static struct dt_object* lu2dt_obj (struct lu_object * o) [static, read]
Definition at line 1800 of file dt_object.h.
References dt_object::do_lu, ergo, LASSERT, lu_object::lo_dev, and lu_device_is_dt().
Referenced by osp_object_init().
static int lu_device_is_dt (const struct lu_device * d) [inline, static]
Definition at line 1738 of file dt_object.h.
References ergo, lu_device::ld_type, lu_device_type::ldt_tags, and LU_DEVICE_DT.
Referenced by lu2dt(), lu2dt_dev(), and lu2dt_obj().
Variable Documentation
struct dt_index_features dt_acct_features
Definition at line 605 of file dt_object.c.
Referenced by acct_obj_lookup(), and osd_index_try().
struct dt_index_features dt_directory_features
Features, required from index to support file system directories (mapping names to fids).
Definition at line 575 of file dt_object.c.
Referenced by dt_index_feat_select(), dt_try_as_dir(), lod_declare_object_destroy(), lod_object_destroy(), lod_striped_it_next(), mdd_declare_object_create_internal(), mdd_migrate_create(), mdt_md_create(), mdt_orphan_open(), mdt_reint_open(), osd_iam_index_probe(), and osd_index_try().
struct dt_index_features dt_lfsck_features
Definition at line 594 of file dt_object.c.
Referenced by lfsck_namespace_load_one_trace_file(), lfsck_namespace_load_sub_trace_files(), and lfsck_namespace_setup().
struct dt_index_features dt_lfsck_orphan_features
Definition at line 583 of file dt_object.c.
Referenced by lfsck_layout_scan_orphan().
struct dt_index_features dt_nodemap_features
Definition at line 640 of file dt_object.c.
Referenced by mgs_fs_setup().
struct dt_index_features dt_otable_features
Definition at line 579 of file dt_object.c.
Referenced by lfsck_register(), and osd_index_try().
struct dt_index_features dt_quota_glb_features
Definition at line 616 of file dt_object.c.
Referenced by lquota_disk_glb_find_create(), and osd_index_try().
struct dt_index_features dt_quota_slv_features
Definition at line 628 of file dt_object.c.
Referenced by lquota_disk_slv_find(), lquota_disk_slv_find_create(), and quota_obj_lookup().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.