Lustre: lu_fid
lu_fid
[lustreidl]
Data Structures
struct hsm_attrs
HSM on-disk attributes stored in a separate xattr.
struct lu_orphan_rec
struct lu_orphan_ent
Defines
#define LL_HSM_MAX_ARCHIVE (sizeof(__u32) * 8)
#define OBIF_OID_MAX_BITS 32
#define OBIF_MAX_OID (1ULL << OBIF_OID_MAX_BITS)
#define OBIF_OID_MASK ((1ULL << OBIF_OID_MAX_BITS) - 1)
#define IDIF_OID_MAX_BITS 48
#define IDIF_MAX_OID (1ULL << IDIF_OID_MAX_BITS)
#define IDIF_OID_MASK ((1ULL << IDIF_OID_MAX_BITS) - 1)
#define __diff_normalize(val0, val1)
Enumerations
enum lma_compat { LMAC_HSM = 0x00000001, LMAC_NOT_IN_OI = 0x00000004, LMAC_FID_ON_OST = 0x00000008 }
Flags for lustre_mdt_attrs::lma_compat and lustre_mdt_attrs::lma_incompat.
enum lma_incompat {
LMAI_RELEASED = 0x00000001, LMAI_AGENT = 0x00000002, LMAI_REMOTE_PARENT = 0x00000004, LMAI_STRIPED = 0x00000008,
LMAI_ORPHAN = 0x00000010, LMA_INCOMPAT_SUPP
}
Masks for all features that should be supported by a Lustre version to access a specific file.
enum { LUSTRE_FID_LASTID_OID = 0UL, LUSTRE_FID_INIT_OID = 1UL }
fid constants
enum fid_seq {
FID_SEQ_OST_MDT0 = 0, FID_SEQ_LLOG = 1, FID_SEQ_ECHO = 2, FID_SEQ_UNUSED_START = 3,
FID_SEQ_UNUSED_END = 9, FID_SEQ_LLOG_NAME = 10, FID_SEQ_RSVD = 11, FID_SEQ_IGIF = 12,
FID_SEQ_IGIF_MAX = 0x0ffffffffULL, FID_SEQ_IDIF = 0x100000000ULL, FID_SEQ_IDIF_MAX = 0x1ffffffffULL, FID_SEQ_START = 0x200000000ULL,
FID_SEQ_LOCAL_FILE = 0x200000001ULL, FID_SEQ_DOT_LUSTRE = 0x200000002ULL, FID_SEQ_LOCAL_NAME = 0x200000003ULL, FID_SEQ_SPECIAL = 0x200000004ULL,
FID_SEQ_QUOTA = 0x200000005ULL, FID_SEQ_QUOTA_GLB = 0x200000006ULL, FID_SEQ_ROOT = 0x200000007ULL, FID_SEQ_LAYOUT_RBTREE = 0x200000008ULL,
FID_SEQ_UPDATE_LOG = 0x200000009ULL, FID_SEQ_UPDATE_LOG_DIR = 0x20000000aULL, FID_SEQ_NORMAL = 0x200000400ULL, FID_SEQ_LOV_DEFAULT = 0xffffffffffffffffULL
}
Note that reserved SEQ numbers below 12 will conflict with ldiskfs inodes in the IGIF namespace, so these reserved SEQ numbers can be used for other purposes and not risk collisions with existing inodes.
enum special_oid { FID_OID_SPECIAL_BFL = 1UL }
OID for FID_SEQ_SPECIAL.
enum dot_lustre_oid { FID_OID_DOT_LUSTRE = 1UL, FID_OID_DOT_LUSTRE_OBF = 2UL, FID_OID_DOT_LUSTRE_LPF = 3UL }
OID for FID_SEQ_DOT_LUSTRE.
enum root_oid { FID_OID_ROOT = 1UL, FID_OID_ECHO_ROOT = 2UL }
OID for FID_SEQ_ROOT.
Functions
void lustre_lma_swab (struct lustre_mdt_attrs *lma)
Swab, if needed, LMA structure which is stored on-disk in little-endian order.
void lustre_lma_init (struct lustre_mdt_attrs *lma, const struct lu_fid *fid, __u32 compat, __u32 incompat)
Initialize new lma.
void lustre_hsm_swab (struct hsm_attrs *attrs)
Swab, if needed, HSM structure which is stored on-disk in little-endian order.
static __u64 fid_seq (const struct lu_fid *fid)
returns fid object sequence
static __u32 fid_oid (const struct lu_fid *fid)
returns fid object id
static __u32 fid_ver (const struct lu_fid *fid)
returns fid object version
static void fid_zero (struct lu_fid *fid)
static __u64 fid_ver_oid (const struct lu_fid *fid)
static bool fid_seq_is_mdt0 (__u64 seq)
static bool fid_seq_is_mdt (__u64 seq)
static bool fid_seq_is_echo (__u64 seq)
static bool fid_is_echo (const struct lu_fid *fid)
static bool fid_seq_is_llog (__u64 seq)
static bool fid_is_llog (const struct lu_fid *fid)
static bool fid_seq_is_rsvd (__u64 seq)
static bool fid_seq_is_special (__u64 seq)
static bool fid_seq_is_local_file (__u64 seq)
static bool fid_seq_is_root (__u64 seq)
static bool fid_seq_is_dot (__u64 seq)
static bool fid_seq_is_default (__u64 seq)
static bool fid_is_mdt0 (const struct lu_fid *fid)
static void lu_root_fid (struct lu_fid *fid)
static void lu_echo_root_fid (struct lu_fid *fid)
static void lu_update_log_fid (struct lu_fid *fid, __u32 index)
static void lu_update_log_dir_fid (struct lu_fid *fid, __u32 index)
static bool fid_seq_is_igif (__u64 seq)
Check if a fid is igif or not.
static bool fid_is_igif (const struct lu_fid *fid)
static bool fid_seq_is_idif (__u64 seq)
Check if a fid is idif or not.
static bool fid_is_idif (const struct lu_fid *fid)
static bool fid_is_local_file (const struct lu_fid *fid)
static bool fid_seq_is_norm (__u64 seq)
static bool fid_is_norm (const struct lu_fid *fid)
static int fid_is_layout_rbtree (const struct lu_fid *fid)
static bool fid_seq_is_update_log (__u64 seq)
static bool fid_is_update_log (const struct lu_fid *fid)
static bool fid_seq_is_update_log_dir (__u64 seq)
static bool fid_is_update_log_dir (const struct lu_fid *fid)
static __u64 fid_idif_seq (__u64 id, __u32 ost_idx)
static __u64 fid_idif_id (__u64 seq, __u32 oid, __u32 ver)
static __u32 idif_ost_idx (__u64 seq)
static __u32 fid_idif_ost_idx (const struct lu_fid *fid)
static __u64 ostid_seq (const struct ost_id *ostid)
static __u64 ostid_id (const struct ost_id *ostid)
static void ostid_set_seq (struct ost_id *oi, __u64 seq)
static void ostid_set_seq_mdt0 (struct ost_id *oi)
static void ostid_set_seq_echo (struct ost_id *oi)
static void ostid_set_seq_llog (struct ost_id *oi)
static void ostid_set_id (struct ost_id *oi, __u64 oid)
Note: we need check oi_seq to decide where to set oi_id, so oi_seq should always be set ahead of oi_id.
static int fid_set_id (struct lu_fid *fid, __u64 oid)
static int ostid_to_fid (struct lu_fid *fid, const struct ost_id *ostid, __u32 ost_idx)
Unpack an OST object id/seq (group) into a FID.
static int fid_to_ostid (const struct lu_fid *fid, struct ost_id *ostid)
static bool fid_is_last_id (const struct lu_fid *fid)
static ino_t lu_igif_ino (const struct lu_fid *fid)
Get inode number from an igif.
static __u32 lu_igif_gen (const struct lu_fid *fid)
Get inode generation from an igif.
static void lu_igif_build (struct lu_fid *fid, __u32 ino, __u32 gen)
Build igif from the inode number/generation.
static void fid_cpu_to_le (struct lu_fid *dst, const struct lu_fid *src)
static void fid_le_to_cpu (struct lu_fid *dst, const struct lu_fid *src)
static void fid_cpu_to_be (struct lu_fid *dst, const struct lu_fid *src)
static void fid_be_to_cpu (struct lu_fid *dst, const struct lu_fid *src)
static bool fid_is_sane (const struct lu_fid *fid)
static bool lu_fid_eq (const struct lu_fid *f0, const struct lu_fid *f1)
static int lu_fid_cmp (const struct lu_fid *f0, const struct lu_fid *f1)
static void ostid_cpu_to_le (const struct ost_id *src_oi, struct ost_id *dst_oi)
static void ostid_le_to_cpu (const struct ost_id *src_oi, struct ost_id *dst_oi)
Define Documentation
#define __diff_normalize (val0, val1)
Value:
({                                                              \
        typeof(val0) __val0 = (val0);                           \
        typeof(val1) __val1 = (val1);                           \
                                                                \
        (__val0 == __val1 ? 0 : __val0 > __val1 ? +1 : -1);     \
})
Definition at line 806 of file lustre_idl.h.
Referenced by lu_fid_cmp().
#define IDIF_MAX_OID (1ULL << IDIF_OID_MAX_BITS)
Definition at line 320 of file lustre_idl.h.
Referenced by fid_set_id(), ofd_create_hdl(), ofd_precreate_objects(), ofd_preprw_write(), osp_fid_end_seq(), osp_precreate_fids(), ostid_set_id(), and ostid_to_fid().
#define IDIF_OID_MASK ((1ULL << IDIF_OID_MAX_BITS) - 1)
Definition at line 321 of file lustre_idl.h.
Referenced by ostid_id().
#define IDIF_OID_MAX_BITS 48
Definition at line 319 of file lustre_idl.h.
#define LL_HSM_MAX_ARCHIVE (sizeof(__u32) * 8)
Definition at line 214 of file lustre_idl.h.
Referenced by ct_parseopts(), ll_hsm_state_set(), llapi_hsm_copytool_register(), and mdt_hsm_state_set().
#define OBIF_MAX_OID (1ULL << OBIF_OID_MAX_BITS)
Definition at line 317 of file lustre_idl.h.
Referenced by fid_set_id(), local_oid_storage_init(), ofd_precreate_objects(), and ostid_set_id().
#define OBIF_OID_MASK ((1ULL << OBIF_OID_MAX_BITS) - 1)
Definition at line 318 of file lustre_idl.h.
#define OBIF_OID_MAX_BITS 32
Definition at line 316 of file lustre_idl.h.
Enumeration Type Documentation
anonymous enum
fid constants
Enumerator:
LUSTRE_FID_LASTID_OID
LASTID file has zero OID.
LUSTRE_FID_INIT_OID
initial fid id value
Definition at line 235 of file lustre_idl.h.
enum dot_lustre_oid
OID for FID_SEQ_DOT_LUSTRE.
Enumerator:
FID_OID_DOT_LUSTRE
FID_OID_DOT_LUSTRE_OBF
FID_OID_DOT_LUSTRE_LPF
Definition at line 330 of file lustre_idl.h.
enum fid_seq
Note that reserved SEQ numbers below 12 will conflict with ldiskfs inodes in the IGIF namespace, so these reserved SEQ numbers can be used for other purposes and not risk collisions with existing inodes.
Different FID Format http://arch.lustre.org/index.php?title=Interoperability_fids_zfs#NEW.0
Enumerator:
FID_SEQ_OST_MDT0
FID_SEQ_LLOG
FID_SEQ_ECHO
FID_SEQ_UNUSED_START
FID_SEQ_UNUSED_END
FID_SEQ_LLOG_NAME
FID_SEQ_RSVD
FID_SEQ_IGIF
FID_SEQ_IGIF_MAX
FID_SEQ_IDIF
FID_SEQ_IDIF_MAX
FID_SEQ_START
FID_SEQ_LOCAL_FILE
FID_SEQ_DOT_LUSTRE
FID_SEQ_LOCAL_NAME
FID_SEQ_SPECIAL
FID_SEQ_QUOTA
FID_SEQ_QUOTA_GLB
FID_SEQ_ROOT
FID_SEQ_LAYOUT_RBTREE
FID_SEQ_UPDATE_LOG
FID_SEQ_UPDATE_LOG_DIR
FID_SEQ_NORMAL
FID_SEQ_LOV_DEFAULT
Definition at line 278 of file lustre_idl.h.
enum lma_compat
Flags for lustre_mdt_attrs::lma_compat and lustre_mdt_attrs::lma_incompat.
Deprecated since HSM and SOM attributes are now stored in separate on-disk xattr.
Enumerator:
LMAC_HSM
LMAC_NOT_IN_OI
LMAC_FID_ON_OST
Definition at line 180 of file lustre_idl.h.
enum lma_incompat
Masks for all features that should be supported by a Lustre version to access a specific file.
This information is stored in lustre_mdt_attrs::lma_incompat.
Enumerator:
LMAI_RELEASED
LMAI_AGENT
LMAI_REMOTE_PARENT
LMAI_STRIPED
LMAI_ORPHAN
LMA_INCOMPAT_SUPP
Definition at line 193 of file lustre_idl.h.
enum root_oid
OID for FID_SEQ_ROOT.
Enumerator:
FID_OID_ROOT
FID_OID_ECHO_ROOT
Definition at line 337 of file lustre_idl.h.
enum special_oid
OID for FID_SEQ_SPECIAL.
Enumerator:
FID_OID_SPECIAL_BFL
Definition at line 324 of file lustre_idl.h.
Function Documentation
static void fid_be_to_cpu (struct lu_fid * dst, const struct lu_fid * src) [inline, static]
Definition at line 786 of file lustre_idl.h.
References be32_to_cpu, be64_to_cpu, f_oid, f_seq, f_ver, fid_oid(), and fid_ver().
Referenced by lfsck_namespace_double_scan_one_trace_file(), linkea_entry_unpack(), mdt_attr_get_pfid(), osd_fid_unpack(), and osd_find_parent_fid().
static void fid_cpu_to_be (struct lu_fid * dst, const struct lu_fid * src) [inline, static]
Definition at line 779 of file lustre_idl.h.
References cpu_to_be32, cpu_to_be64, f_oid, f_seq, f_ver, fid_oid(), and fid_ver().
Referenced by __osd_oi_lookup(), lfsck_namespace_double_scan_one_trace_file(), lfsck_namespace_in_notify(), lfsck_namespace_repair_nlink(), lfsck_namespace_scan_local_lpf_one(), lfsck_namespace_trace_update(), linkea_entry_pack(), osd_attr_set(), osd_dirent_reinsert(), osd_fid_pack(), osd_get_ldiskfs_dirent_param(), osd_oi_delete(), osd_oi_insert(), and osd_oi_update().
static void fid_cpu_to_le (struct lu_fid * dst, const struct lu_fid * src) [inline, static]
Definition at line 765 of file lustre_idl.h.
References cpu_to_le32, cpu_to_le64, f_oid, f_seq, f_ver, fid_oid(), and fid_ver().
Referenced by lfsck_bookmark_cpu_to_le(), lfsck_namespace_cpu_to_le(), lfsck_position_cpu_to_le(), lmv_read_striped_page(), lod_object_replace_parent_fid(), mdd_migrate_create(), osd_it_pack_dirent(), osp_get_lastfid_from_ost(), ostid_cpu_to_le(), out_create_pack(), out_index_insert_pack(), update_records_create_pack(), and update_records_index_insert_pack().
static __u64 fid_idif_id (__u64 seq, __u32 oid, __u32 ver) [inline, static]
Definition at line 514 of file lustre_idl.h.
References __u64.
Referenced by fid_to_ostid(), lfsck_layout_slave_exec_oit(), lu_fid_diff(), osp_fid_diff(), and ostid_id().
static __u32 fid_idif_ost_idx (const struct lu_fid * fid) [inline, static]
Definition at line 525 of file lustre_idl.h.
References idif_ost_idx().
Referenced by fid_set_id(), lfsck_master_oit_engine(), lod_fld_lookup(), osd_check_lma(), osd_obj_update_entry(), osp_fid_diff(), and ostid_set_id().
static __u64 fid_idif_seq (__u64 id, __u32 ost_idx) [inline, static]
Definition at line 508 of file lustre_idl.h.
References FID_SEQ_IDIF.
Referenced by fid_set_id(), lu_last_id_fid(), osp_init_pre_fid(), osp_last_used_init(), ostid_set_id(), and ostid_to_fid().
static bool fid_is_echo (const struct lu_fid * fid) [inline, static]
Definition at line 357 of file lustre_idl.h.
References fid_seq_is_echo().
static bool fid_is_idif (const struct lu_fid * fid) [inline, static]
Definition at line 462 of file lustre_idl.h.
References fid_seq_is_idif().
Referenced by fid_is_internal(), fid_is_on_ost(), fid_is_sane(), fid_set_id(), fid_to_ostid(), lfsck_layout_slave_check_pairs(), lfsck_layout_slave_exec_oit(), lfsck_master_oit_engine(), lfsck_rbtree_update_bitmap(), lod_fld_lookup(), lu_fid_diff(), osd_check_lma(), osd_fid2oi(), osd_fid_lookup(), osd_obj_update_entry(), osd_object_ea_create(), osd_scrub_convert_ff(), osd_scrub_get_fid(), osp_fid_diff(), osp_fid_end_seq(), osp_index_try(), osp_precreate_fids(), osp_precreate_send(), ost_fid_build_resid(), ostid_id(), ostid_seq(), and ostid_set_id().
static bool fid_is_igif (const struct lu_fid * fid) [inline, static]
Definition at line 447 of file lustre_idl.h.
References fid_seq_is_igif().
Referenced by cl_fid_build_gen(), fid_flatten(), fid_flatten32(), fid_is_file(), fid_is_md_operative(), fid_is_on_ost(), fid_is_sane(), lfsck_master_oit_engine(), lfsck_needs_scan_dir(), mdd_layout_swap_allowed(), obf_lookup(), osd_check_lma(), osd_consistency_check(), osd_fid_lookup(), osd_oi_lookup(), and osd_scrub_check_update().
static bool fid_is_last_id (const struct lu_fid * fid) [inline, static]
Definition at line 725 of file lustre_idl.h.
References fid_oid(), FID_SEQ_UPDATE_LOG, and FID_SEQ_UPDATE_LOG_DIR.
Referenced by fid_is_namespace_visible(), fid_is_on_ost(), lfsck_layout_slave_exec_oit(), lfsck_master_oit_engine(), lfsck_rbtree_update_bitmap(), osd_fid2oi(), osd_get_idx_for_ost_obj(), osd_obj_map_recover(), osd_obj_spec_lookup(), osd_object_spec_find(), osd_oi_delete(), osd_oi_insert(), osd_oi_lookup(), osd_oi_update(), osp_index_try(), and osp_it_fetch().
static int fid_is_layout_rbtree (const struct lu_fid * fid) [inline, static]
Definition at line 482 of file lustre_idl.h.
References FID_SEQ_LAYOUT_RBTREE.
Referenced by dt_index_read().
static bool fid_is_llog (const struct lu_fid * fid) [inline, static]
Definition at line 367 of file lustre_idl.h.
References fid_oid(), and fid_seq_is_llog().
Referenced by fid_is_on_ost(), osd_oi_delete(), osd_oi_insert(), osd_oi_lookup(), and osd_oi_update().
static bool fid_is_local_file (const struct lu_fid * fid) [inline, static]
Definition at line 467 of file lustre_idl.h.
References fid_seq_is_local_file().
Referenced by fid_is_on_ost(), and lod_object_start().
static bool fid_is_mdt0 (const struct lu_fid * fid) [inline, static]
Definition at line 404 of file lustre_idl.h.
References fid_seq_is_mdt0().
Referenced by fid_is_md_operative(), and ost_fid_build_resid().
static bool fid_is_norm (const struct lu_fid * fid) [inline, static]
Definition at line 477 of file lustre_idl.h.
References fid_seq_is_norm().
Referenced by dt_index_read(), fid_is_file(), fid_is_md_operative(), lfsck_fid_match_idx(), lfsck_layout_slave_exec_oit(), lfsck_master_oit_engine(), lfsck_namespace_scan_local_lpf(), lfsck_needs_scan_dir(), lfsck_rbtree_update_bitmap(), lfsck_verify_lpf(), llog_osd_regular_fid_add_name_entry(), llog_osd_regular_fid_del_name_entry(), mdd_layout_swap_allowed(), obf_lookup(), osd_consistency_check(), osd_fid_lookup(), osd_object_ref_del(), and osd_scrub_get_fid().
static bool fid_is_sane (const struct lu_fid * fid) [inline, static]
Definition at line 793 of file lustre_idl.h.
References fid_is_idif(), fid_is_igif(), fid_seq_is_rsvd(), FID_SEQ_START, and fid_ver().
Referenced by __lmv_fid_alloc(), cl_file_inode_init(), client_common_fill_super(), hal_is_sane(), lfsck_fid_init(), lfsck_layout_check_parent(), lfsck_layout_scan_orphan_one(), lfsck_master_oit_engine(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_double_scan_dir(), lfsck_namespace_double_scan_one(), lfsck_namespace_double_scan_one_trace_file(), lfsck_namespace_dsd_multiple(), lfsck_namespace_dsd_single(), lfsck_namespace_exec_oit(), lfsck_namespace_repair_bad_name_hash(), lfsck_namespace_replace_cond(), lfsck_namespace_trace_update(), lfsck_namespace_verify_stripe_slave(), lfsck_needs_scan_dir(), lfsck_rbtree_update_bitmap(), lfsck_verify_lpf_pairs(), ll_iget_for_nfs(), ll_layout_refresh(), ll_migrate(), ll_prep_inode(), ll_update_inode(), llapi_fid2path(), lmv_early_cancel(), lmv_fid2path(), lmv_fld_lookup(), lmv_intent_getattr_async(), lmv_intent_lock(), lmv_intent_lookup(), lmv_intent_open(), lmv_intent_remote(), lmv_rename(), lod_fld_lookup(), lod_initialize_objects(), lod_parse_dir_striping(), lod_prep_md_striped_create(), lod_sub_get_thandle(), mdc_create(), mdc_intent_lock(), mdc_intent_open_pack(), mdc_ioc_fid2path(), mdc_link(), mdc_rename(), mdc_set_open_replay_data(), mdc_setattr(), mdc_unlink(), mdc_xattr_common(), mdd_parent_fid(), mdt_body_unpack(), mdt_close_swap_layouts(), mdt_fid2path(), mdt_getattr_name_lock(), mdt_hsm_get_actions(), mdt_hsm_get_running(), mdt_hsm_release(), mdt_hsm_restore_is_running(), mdt_ioc_version_get(), mdt_reint_migrate_internal(), mdt_reint_open(), mdt_rpc_fid2path(), obf_lookup(), ofd_ioc_get_obj_version(), ofd_object_ff_load(), ofd_verify_ff(), orph_index_iterate(), osd_dir_lookup(), osd_dirent_check_repair(), osd_fid_lookup(), osd_get_fid_from_dentry(), osd_index_ea_insert(), osd_ios_uld_fill(), osd_it_ea_rec(), osd_otable_it_rec(), osp_declare_object_create(), osp_get_lastfid_from_ost(), osp_last_used_init(), osp_md_index_lookup(), osp_object_create(), osp_thandle_invalidate_object(), out_create(), out_destroy(), out_handle(), out_index_insert(), tgt_mdt_body_unpack(), and tgt_obd_idx_read().
static bool fid_is_update_log (const struct lu_fid * fid) [inline, static]
Definition at line 492 of file lustre_idl.h.
References fid_seq_is_update_log().
Referenced by llog_osd_put_cat_list(), lod_fld_lookup(), and update_is_committed().
static bool fid_is_update_log_dir (const struct lu_fid * fid) [inline, static]
Definition at line 502 of file lustre_idl.h.
References fid_seq_is_update_log_dir().
Referenced by lod_fld_lookup(), and update_is_committed().
static void fid_le_to_cpu (struct lu_fid * dst, const struct lu_fid * src) [inline, static]
Definition at line 772 of file lustre_idl.h.
References f_oid, f_seq, f_ver, fid_oid(), fid_ver(), le32_to_cpu, and le64_to_cpu.
Referenced by fid_from_lma(), lfsck_bookmark_le_to_cpu(), lfsck_layout_assistant_handler_p1(), lfsck_namespace_le_to_cpu(), lfsck_orphan_it_next(), lfsck_position_le_to_cpu(), lfsck_unpack_ent(), ll_dir_ioctl(), ll_dir_read(), ll_nfs_get_name_filldir(), ll_statahead_thread(), lmv1_le_to_cpu(), lmv_unpack_md_v1(), lod_load_lmv_shards(), lod_object_replace_parent_fid(), lod_parse_dir_striping(), mdd_dir_page_build(), mdd_migrate_entries(), mdt_dump_lmv(), mdt_init_slaves(), mdt_reint_open(), ofd_get_info_hdl(), orph_index_iterate(), ostid_le_to_cpu(), and update_recovery_index_insert().
static __u32 fid_oid (const struct lu_fid * fid) [inline, static]
returns fid object id
Definition at line 249 of file lustre_idl.h.
References f_oid.
Referenced by fid2type(), fid_be_to_cpu(), fid_cpu_to_be(), fid_cpu_to_le(), fid_flatten(), fid_flatten32(), fid_is_acct(), fid_is_dot_lustre(), fid_is_fs_root(), fid_is_last_id(), fid_is_llog(), fid_is_obf(), fid_is_otable_it(), fid_is_root(), fid_le_to_cpu(), fid_to_lmm_oi(), fid_to_ostid(), fid_ver_oid(), ldlm_res_hop_fid_hash(), lfsck_layout_slave_exec_oit(), lfsck_rbtree_new(), lfsck_rbtree_search(), lfsck_rbtree_update_bitmap(), local_oid_storage_init(), lod_fld_lookup(), lu_fid_cmp(), lu_fid_diff(), lu_igif_gen(), lu_obj_hop_hash(), lustre_set_wire_obdo(), mdd_is_root(), obdo_set_parent_fid(), ofd_preprw_write(), orph_key_fill(), orph_key_fill_18(), osd_dirent_check_repair(), osd_fid_lookup(), osd_get_name_n_idx(), osd_quota_fid2dmu(), osp_fid_diff(), osp_fid_end_seq(), osp_get_lastfid_from_ost(), osp_last_used_init(), osp_object_create(), osp_precreate_cleanup_orphans(), osp_statfs(), ostid_id(), seq_client_alloc_fid(), and update_is_committed().
static __u64 fid_seq (const struct lu_fid * fid) [inline, static]
returns fid object sequence
Definition at line 243 of file lustre_idl.h.
References f_seq.
static bool fid_seq_is_default (__u64 seq) [inline, static]
Definition at line 399 of file lustre_idl.h.
References FID_SEQ_LOV_DEFAULT.
Referenced by lustre_swab_ost_id(), ostid_id(), ostid_seq(), ostid_set_seq(), and ostid_to_fid().
static bool fid_seq_is_dot (__u64 seq) [inline, static]
Definition at line 394 of file lustre_idl.h.
References FID_SEQ_DOT_LUSTRE.
Referenced by fid_is_namespace_visible(), fid_seq_in_fldb(), lfsck_namespace_assistant_handler_p1(), and obf_lookup().
static bool fid_seq_is_echo (__u64 seq) [inline, static]
Definition at line 352 of file lustre_idl.h.
References FID_SEQ_ECHO.
Referenced by echo_create_object(), fid_is_echo(), lu_last_id_fid(), lustre_get_wire_obdo(), lustre_set_wire_obdo(), osc_create(), and tgt_validate_obdo().
static bool fid_seq_is_idif (__u64 seq) [inline, static]
Check if a fid is idif or not.
Parameters:
fid the fid to be tested.
Returns:
true if the fid is an idif; otherwise false.
Definition at line 457 of file lustre_idl.h.
References FID_SEQ_IDIF, and FID_SEQ_IDIF_MAX.
Referenced by fid_is_idif(), lu_last_id_fid(), ofd_create_hdl(), ofd_preprw_write(), osd_find_or_add_seq(), osd_fld_lookup(), osd_oid_name(), osd_seq_name(), and tgt_validate_obdo().
static bool fid_seq_is_igif (__u64 seq) [inline, static]
Check if a fid is igif or not.
Parameters:
fid the fid to be tested.
Returns:
true if the fid is an igif; otherwise false.
Definition at line 442 of file lustre_idl.h.
References FID_SEQ_IGIF, and FID_SEQ_IGIF_MAX.
Referenced by fid_is_igif(), fid_is_namespace_visible(), fid_seq_in_fldb(), fid_set_id(), and fid_to_ostid().
static bool fid_seq_is_llog (__u64 seq) [inline, static]
Definition at line 362 of file lustre_idl.h.
References FID_SEQ_LLOG.
Referenced by fid_is_llog().
static bool fid_seq_is_local_file (__u64 seq) [inline, static]
Definition at line 383 of file lustre_idl.h.
References FID_SEQ_LOCAL_FILE, and FID_SEQ_LOCAL_NAME.
Referenced by __osd_object_create(), fid_is_local_file(), and lmv_fld_lookup().
static bool fid_seq_is_mdt (__u64 seq) [inline, static]
Definition at line 347 of file lustre_idl.h.
References FID_SEQ_NORMAL, and FID_SEQ_OST_MDT0.
Referenced by ofd_create_hdl().
static bool fid_seq_is_mdt0 (__u64 seq) [inline, static]
Definition at line 342 of file lustre_idl.h.
References FID_SEQ_OST_MDT0.
Referenced by fid_is_mdt0(), lov_dump_user_lmm_v1v3(), lu_last_id_fid(), lustre_swab_ost_id(), ofd_create_hdl(), ofd_precreate_objects(), ofd_preprw_write(), osd_find_or_add_seq(), osd_ldiskfs_add_entry(), osd_oid_name(), osd_seq_name(), ost_fid_from_resid(), ostid_build_res_name(), ostid_cpu_to_le(), ostid_id(), ostid_le_to_cpu(), ostid_res_name_eq(), ostid_seq(), ostid_set_id(), ostid_set_seq(), ostid_to_fid(), and tgt_validate_obdo().
static bool fid_seq_is_norm (__u64 seq) [inline, static]
Definition at line 472 of file lustre_idl.h.
References FID_SEQ_NORMAL.
Referenced by fid_is_namespace_visible(), fid_is_norm(), fid_seq_in_fldb(), fld_rrb_scan(), lu_last_id_fid(), ofd_create_hdl(), ofd_preprw_write(), and tgt_validate_obdo().
static bool fid_seq_is_root (__u64 seq) [inline, static]
Definition at line 389 of file lustre_idl.h.
References FID_SEQ_ROOT.
Referenced by fid_seq_in_fldb().
static bool fid_seq_is_rsvd (__u64 seq) [inline, static]
Definition at line 373 of file lustre_idl.h.
References FID_SEQ_OST_MDT0, and FID_SEQ_RSVD.
Referenced by fid_is_sane(), lov_dump_user_lmm_v1v3(), osd_find_or_add_seq(), osd_oid_name(), and osd_seq_name().
static bool fid_seq_is_special (__u64 seq) [inline, static]
Definition at line 378 of file lustre_idl.h.
References FID_SEQ_SPECIAL.
static bool fid_seq_is_update_log (__u64 seq) [inline, static]
Definition at line 487 of file lustre_idl.h.
References FID_SEQ_UPDATE_LOG.
Referenced by fid_is_update_log().
static bool fid_seq_is_update_log_dir (__u64 seq) [inline, static]
Definition at line 497 of file lustre_idl.h.
References FID_SEQ_UPDATE_LOG_DIR.
Referenced by fid_is_update_log_dir().
static int fid_set_id (struct lu_fid * fid, __u64 oid) [inline, static]
Definition at line 623 of file lustre_idl.h.
References CERROR, DFID, f_oid, f_seq, f_ver, fid_idif_ost_idx(), fid_idif_seq(), fid_is_idif(), fid_seq_is_igif(), IDIF_MAX_OID, OBIF_MAX_OID, PFID, and unlikely.
Referenced by ofd_destroy_hdl(), ofd_orphans_destroy(), and ofd_precreate_objects().
static int fid_to_ostid (const struct lu_fid * fid, struct ost_id * ostid) [inline, static]
Definition at line 706 of file lustre_idl.h.
References CERROR, DFID, f_seq, fid_idif_id(), fid_is_idif(), fid_oid(), fid_seq_is_igif(), fid_ver(), ost_id::oi_fid, ostid_set_id(), ostid_set_seq_mdt0(), PFID, and unlikely.
Referenced by jt_obd_md_common(), lfsck_layout_master_check_pairs(), lfsck_layout_refill_lovea(), lfsck_layout_repair_multiple_references(), lfsck_master_oit_engine(), lod_attr_set(), lod_generate_and_set_lovea(), ofd_create_hdl(), ofd_destroy_hdl(), osd_check_lma(), osd_get_idx_for_ost_obj(), osd_obj_map_delete(), osd_obj_map_insert(), osd_obj_map_lookup(), osd_obj_map_recover(), osd_obj_map_update(), osd_obj_update_entry(), osd_object_ea_create(), osd_scrub_convert_ff(), osp_fid_end_seq(), osp_object_truncate(), osp_precreate_cleanup_orphans(), osp_precreate_fids(), osp_precreate_send(), osp_sync_add_rec(), osp_sync_inflight_conflict(), osp_sync_new_unlink64_job(), and ost_fid_build_resid().
static __u32 fid_ver (const struct lu_fid * fid) [inline, static]
returns fid object version
Definition at line 255 of file lustre_idl.h.
References f_ver.
Referenced by fid_be_to_cpu(), fid_cpu_to_be(), fid_cpu_to_le(), fid_is_sane(), fid_le_to_cpu(), fid_to_ostid(), fid_ver_oid(), lfsck_layout_slave_exec_oit(), lu_fid_cmp(), obdo_set_parent_fid(), and orph_key_fill().
static __u64 fid_ver_oid (const struct lu_fid * fid) [inline, static]
Definition at line 265 of file lustre_idl.h.
References __u64, fid_oid(), and fid_ver().
Referenced by fid_build_quota_res_name(), fid_build_reg_res_name(), and fid_res_name_eq().
static void fid_zero (struct lu_fid * fid) [inline, static]
Definition at line 260 of file lustre_idl.h.
Referenced by client_common_fill_super(), lfsck_layout_conflict_create(), lfsck_layout_prep(), lfsck_namespace_double_scan_dir(), lfsck_namespace_double_scan_one_trace_file(), lfsck_namespace_dump(), lfsck_namespace_prep(), lfsck_orphan_it_load(), lfsck_orphan_it_next(), lfsck_pos_fill(), lfsck_verify_lpf(), lfsck_verify_lpf_pairs(), ll_encode_fh(), ll_lli_init(), ll_lookup_it(), ll_prep_md_op_data(), lmv_intent_lookup(), lo_ioctl(), lod_add_noop_records(), lu_object_anon(), mdd_changelog_ns_store(), mdd_is_subdir(), mdt_getattr_name_lock(), mdt_lookup_fileset(), mdt_raw_lookup(), mdt_reint_migrate_internal(), mdt_reint_open(), mdt_reint_rename_internal(), mdt_reint_unlink(), ofd_object_ff_load(), orph_index_init(), osd_ea_lookup_rec(), osd_fail_fid_lookup(), osd_fid_lookup(), osd_get_pfid_from_linkea(), osd_ldiskfs_filldir(), osd_oi_delete(), osp_init_pre_fid(), osp_init_precreate(), osp_last_used_init(), and seq_client_flush().
static __u32 idif_ost_idx (__u64 seq) [inline, static]
Definition at line 519 of file lustre_idl.h.
Referenced by fid_idif_ost_idx(), and osd_fld_lookup().
static void lu_echo_root_fid (struct lu_fid * fid) [inline, static]
Definition at line 416 of file lustre_idl.h.
References f_oid, f_seq, f_ver, FID_OID_ECHO_ROOT, and FID_SEQ_ROOT.
static int lu_fid_cmp (const struct lu_fid * f0, const struct lu_fid * f1) [inline, static]
Definition at line 814 of file lustre_idl.h.
References __diff_normalize, fid_oid(), and fid_ver().
Referenced by cl_lock_descr_sort(), ll_swap_layouts(), ll_swap_layouts_close(), mdd_swap_layouts(), mdt_close_swap_layouts(), and mdt_swap_layouts().
static bool lu_fid_eq (const struct lu_fid * f0, const struct lu_fid * f1) [inline, static]
Definition at line 801 of file lustre_idl.h.
Referenced by cdt_find_request_nolock(), hsm_find_compatible_cb(), lfsck_allow_regenerate_master_lmv(), lfsck_layout_check_parent(), lfsck_layout_recreate_lovea(), lfsck_layout_repair_multiple_references(), lfsck_master_oit_engine(), lfsck_namespace_check_exist(), lfsck_namespace_double_scan_dir(), lfsck_namespace_double_scan_one(), lfsck_namespace_dsd_multiple(), lfsck_namespace_dsd_single(), lfsck_namespace_insert_orphan(), lfsck_namespace_repair_dirent(), lfsck_namespace_replace_cond(), lfsck_namespace_shrink_linkea_cond(), lfsck_namespace_verify_stripe_slave(), lfsck_needs_scan_dir(), lfsck_pos_is_eq(), lfsck_record_lmv(), lfsck_verify_lpf(), lfsck_verify_lpf_pairs(), linkea_links_find(), ll_nfs_get_name_filldir(), ll_test_inode(), ll_test_inode_by_fid(), ll_update_inode(), local_index_find_or_create_with_fid(), lod_xattr_get(), lsm_md_eq(), lu_obj_hop_keycmp(), lu_object_find_try(), mdd_is_parent(), mdd_linkea_update_child_internal(), mdd_may_delete(), mdd_rename(), mdd_rename_order(), mdd_update_linkea_internal(), mdt_getattr(), mdt_getattr_internal(), mdt_getattr_name_lock(), mdt_hsm_restore_hdl_find(), mdt_hsm_restore_is_running(), mdt_hsm_update_request_state(), mdt_is_subdir(), mdt_lock_slaves(), mdt_open_by_fid_lock(), mdt_path(), mdt_path_current(), mdt_reint_link(), mdt_reint_migrate_internal(), mdt_reint_rename_internal(), ofd_fmd_find_nolock(), osd_check_lma(), osd_dirent_check_repair(), osd_fid_lookup(), osd_find_parent_fid(), osd_idc_find(), osd_lf_fid2name(), osd_obj_update_entry(), osd_oi_delete(), osd_oi_insert(), osd_oii_lookup(), and sa_instantiate().
static void lu_igif_build (struct lu_fid * fid, __u32 ino, __u32 gen) [inline, static]
Build igif from the inode number/generation.
Definition at line 754 of file lustre_idl.h.
References f_oid, f_seq, and f_ver.
Referenced by logid_to_fid(), osd_dirent_check_repair(), osd_iget_fid(), osd_ios_scan_one(), osd_ldiskfs_add_entry(), osd_oi_open(), osd_ost_init(), osd_scrub_get_fid(), osd_scrub_setup(), and osd_seq_load_locked().
static __u32 lu_igif_gen (const struct lu_fid * fid) [inline, static]
Get inode generation from an igif.
Parameters:
fid an igif to get inode generation from.
Returns:
inode generation for the igif.
Definition at line 746 of file lustre_idl.h.
References fid_oid().
Referenced by cl_fid_build_gen(), and osd_oi_lookup().
static ino_t lu_igif_ino (const struct lu_fid * fid) [inline, static]
Get inode number from an igif.
Parameters:
fid an igif to get inode number from.
Returns:
inode number for the igif.
Definition at line 736 of file lustre_idl.h.
Referenced by fid_flatten(), fid_flatten32(), and osd_oi_lookup().
static void lu_root_fid (struct lu_fid * fid) [inline, static]
Definition at line 409 of file lustre_idl.h.
References f_oid, f_seq, f_ver, FID_OID_ROOT, and FID_SEQ_ROOT.
Referenced by mdd_prepare(), and mdt_rename_lock().
static void lu_update_log_dir_fid (struct lu_fid * fid, __u32 index) [inline, static]
Definition at line 430 of file lustre_idl.h.
References f_oid, f_seq, f_ver, and FID_SEQ_UPDATE_LOG_DIR.
Referenced by llog_osd_get_regular_fid_dir(), and lod_prepare().
static void lu_update_log_fid (struct lu_fid * fid, __u32 index) [inline, static]
Definition at line 423 of file lustre_idl.h.
References f_oid, f_seq, f_ver, and FID_SEQ_UPDATE_LOG.
Referenced by lod_prepare(), and lod_sub_prep_llog().
void lustre_hsm_swab (struct hsm_attrs * attrs)
Swab, if needed, HSM structure which is stored on-disk in little-endian order.
Parameters:
attrs - is a pointer to the HSM structure to be swabbed.
Definition at line 80 of file md_attrs.c.
References __swab32s, __swab64s, hsm_attrs::hsm_arch_id, hsm_attrs::hsm_arch_ver, hsm_attrs::hsm_compat, and hsm_attrs::hsm_flags.
Referenced by lustre_buf2hsm(), and lustre_hsm2buf().
void lustre_lma_init (struct lustre_mdt_attrs * lma, const struct lu_fid * fid, __u32 compat, __u32 incompat)
Initialize new lma.
Only fid is stored.
Parameters:
lma - is the new LMA structure to be initialized
fid - is the FID of the object this LMA belongs to
incompat - features that MDS must understand to access object
Definition at line 44 of file md_attrs.c.
References LASSERT, lustre_mdt_attrs::lma_compat, lustre_mdt_attrs::lma_incompat, lustre_mdt_attrs::lma_self_fid, and offsetof.
Referenced by osd_ea_fid_set(), and osd_init_lma().
void lustre_lma_swab (struct lustre_mdt_attrs * lma)
Swab, if needed, LMA structure which is stored on-disk in little-endian order.
Parameters:
lma - is a pointer to the LMA structure to be swabbed.
Definition at line 64 of file md_attrs.c.
References __swab32s, lustre_mdt_attrs::lma_compat, lustre_mdt_attrs::lma_incompat, lustre_mdt_attrs::lma_self_fid, and lustre_swab_lu_fid.
Referenced by fid_is_for_ostobj(), osd_add_to_remote_parent(), osd_attr_set(), osd_check_lma(), osd_delete_from_remote_parent(), osd_ea_fid_set(), osd_get_fid_by_oid(), osd_get_lma(), osd_init_lma(), osd_xattr_set(), and osd_zfs_otable_it_next().
static void ostid_cpu_to_le (const struct ost_id * src_oi, struct ost_id * dst_oi) [inline, static]
Definition at line 823 of file lustre_idl.h.
References cpu_to_le64, fid_cpu_to_le(), fid_seq_is_mdt0(), ost_id::oi, and ost_id::oi_fid.
Referenced by lfsck_layout_refill_lovea(), lfsck_layout_repair_multiple_references(), lod_attr_set(), lod_generate_and_set_lovea(), and lov_lsm_pack().
static __u64 ostid_id (const struct ost_id * ostid) [inline, static]
Definition at line 546 of file lustre_idl.h.
References fid_idif_id(), fid_is_idif(), fid_oid(), fid_seq_is_default(), fid_seq_is_mdt0(), IDIF_OID_MASK, ost_id::oi, ost_id::oi_fid, and unlikely.
Referenced by cl_echo_object_find(), echo_client_kbrw(), echo_client_prep_commit(), echo_commitrw(), echo_create_object(), echo_destroy(), echo_finalize_lb(), echo_get_object(), echo_getattr(), echo_map_nb_to_lb(), jt_obd_create(), jt_obd_getattr(), jt_obd_test_brw(), llog_cat_id2handle(), llog_origin_handle_destroy(), llog_origin_handle_open(), lov_dump_user_lmm_v1v3(), obdo_print(), ofd_create_hdl(), ofd_destroy_hdl(), ofd_orphans_destroy(), ofd_seq_last_oid(), ofd_seq_last_oid_set(), osc_req_attr_set(), osd_get_idx_for_ost_obj(), osd_obj_map_delete(), osd_obj_map_insert(), osd_obj_map_lookup(), osd_obj_map_recover(), osd_obj_map_update(), osp_fid_end_seq(), osp_precreate_fids(), ostid_build_res_name(), ostid_res_name_eq(), ostid_to_fid(), and tgt_validate_obdo().
static void ostid_le_to_cpu (const struct ost_id * src_oi, struct ost_id * dst_oi) [inline, static]
Definition at line 834 of file lustre_idl.h.
References fid_le_to_cpu(), fid_seq_is_mdt0(), le64_to_cpu, ost_id::oi, and ost_id::oi_fid.
Referenced by lfsck_layout_check_parent(), lfsck_layout_conflict_create(), lfsck_layout_master_check_pairs(), lfsck_layout_recreate_lovea(), lfsck_layout_repair_multiple_references(), lfsck_layout_scan_stripes(), lod_attr_set(), lod_initialize_objects(), lov_dump_lmm_objects(), lsm_unpackmd_common(), and mdt_dump_lmm().
static __u64 ostid_seq (const struct ost_id * ostid) [inline, static]
Definition at line 531 of file lustre_idl.h.
References fid_is_idif(), fid_seq_is_default(), fid_seq_is_mdt0(), FID_SEQ_LOV_DEFAULT, FID_SEQ_OST_MDT0, ost_id::oi, ost_id::oi_fid, and unlikely.
Referenced by cl_echo_object_find(), echo_create_object(), llog_cat_id2handle(), lov_dump_user_lmm_v1v3(), lustre_set_wire_obdo(), obdo_print(), ofd_create_hdl(), ofd_echo_create(), ofd_get_info_hdl(), ofd_orphans_destroy(), ofd_precreate_objects(), ofd_preprw(), ofd_seq_add(), ofd_seq_get(), osc_create(), osc_req_attr_set(), osd_obj_map_delete(), osd_obj_map_insert(), osd_obj_map_lookup(), osd_obj_map_recover(), osd_obj_map_update(), ostid_build_res_name(), ostid_res_name_eq(), ostid_to_fid(), and tgt_validate_obdo().
static void ostid_set_id (struct ost_id * oi, __u64 oid) [inline, static]
Note: we need check oi_seq to decide where to set oi_id, so oi_seq should always be set ahead of oi_id.
Definition at line 594 of file lustre_idl.h.
References CERROR, DOSTID, f_oid, f_seq, f_ver, fid_idif_ost_idx(), fid_idif_seq(), fid_is_idif(), fid_seq_is_mdt0(), IDIF_MAX_OID, OBIF_MAX_OID, ost_id::oi, ost_id::oi_fid, and POSTID.
Referenced by echo_create(), echo_create_object(), echo_getattr(), fid_to_ostid(), jt_obd_create(), jt_obd_destroy(), jt_obd_getattr(), jt_obd_setattr(), jt_obd_test_brw(), jt_obd_test_getattr(), jt_obd_test_setattr(), lfsck_layout_scan_orphan(), lustre_build_llog_lvfs_oid(), ofd_create_hdl(), ofd_echo_create(), ofd_ioc_get_obj_version(), ofd_orphans_destroy(), ofd_seq_last_oid_set(), osc_req_attr_set(), osd_get_idif(), osp_object_create(), osp_precreate_fids(), osp_sync_inflight_conflict(), osp_sync_new_unlink_job(), ost_fid_from_resid(), and str2logid().
static void ostid_set_seq (struct ost_id * oi, __u64 seq) [inline, static]
Definition at line 561 of file lustre_idl.h.
References f_oid, f_seq, f_ver, fid_seq_is_default(), fid_seq_is_mdt0(), LUSTRE_FID_INIT_OID, ost_id::oi, and ost_id::oi_fid.
Referenced by cb_find_init(), cb_getstripe(), lfsck_layout_scan_orphan(), ofd_ioc_get_obj_version(), ofd_seq_load(), osc_req_attr_set(), osd_get_idif(), osp_sync_inflight_conflict(), osp_sync_new_unlink_job(), ost_fid_from_resid(), ostid_set_seq_echo(), ostid_set_seq_llog(), ostid_set_seq_mdt0(), and str2logid().
static void ostid_set_seq_echo (struct ost_id * oi) [inline, static]
Definition at line 580 of file lustre_idl.h.
References FID_SEQ_ECHO, and ostid_set_seq().
Referenced by echo_client_iocontrol(), echo_create(), echo_getattr(), jt_obd_create(), jt_obd_destroy(), jt_obd_getattr(), jt_obd_setattr(), jt_obd_test_brw(), jt_obd_test_getattr(), and jt_obd_test_setattr().
static void ostid_set_seq_llog (struct ost_id * oi) [inline, static]
Definition at line 585 of file lustre_idl.h.
References FID_SEQ_LLOG, and ostid_set_seq().
Referenced by lustre_build_llog_lvfs_oid().
static void ostid_set_seq_mdt0 (struct ost_id * oi) [inline, static]
Definition at line 575 of file lustre_idl.h.
References FID_SEQ_OST_MDT0, and ostid_set_seq().
Referenced by fid_to_ostid(), obdo_to_ioobj(), and tgt_validate_obdo().
static int ostid_to_fid (struct lu_fid * fid, const struct ost_id * ostid, __u32 ost_idx) [inline, static]
Unpack an OST object id/seq (group) into a FID.
This is needed for converting all obdo, lmm, lsm, etc. 64-bit id/seq pairs into proper FIDs. Note that if an id/seq is already in FID/IDIF format it will be passed through unchanged. Only legacy OST objects in "group 0" will be mapped into the IDIF namespace so that they can fit into the struct lu_fid fields without loss. For reference see: http://arch.lustre.org/index.php?title=Interoperability_fids_zfs
Definition at line 659 of file lustre_idl.h.
References __u64, CERROR, DOSTID, f_oid, f_seq, f_ver, fid_idif_seq(), fid_seq_is_default(), fid_seq_is_mdt0(), IDIF_MAX_OID, likely, ost_id::oi_fid, ostid_id(), ostid_seq(), and POSTID.
Referenced by cl_echo_object_find(), echo_client_iocontrol(), lfsck_layout_check_parent(), lfsck_layout_conflict_create(), lfsck_layout_recreate_lovea(), lfsck_layout_repair_multiple_references(), lfsck_layout_scan_orphan(), lfsck_layout_scan_stripes(), lfsck_master_oit_engine(), lod_attr_set(), lod_initialize_objects(), lov_find_subobj(), lov_init_raid0(), ofd_get_info(), ofd_get_info_hdl(), ofd_ioc_get_obj_version(), ofd_ladvise_hdl(), osd_check_lma(), osd_get_idif(), osd_obj_update_entry(), osd_object_ea_create(), osd_scrub_convert_ff(), osp_precreate_cleanup_orphans(), osp_precreate_fids(), osp_precreate_send(), ost_fid_from_resid(), and tgt_validate_obdo().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.