Lustre: Helper functions
Helper functions
[Echo Client]
Functions
static struct echo_device * cl2echo_dev (const struct cl_device *dev)
static struct cl_device * echo_dev2cl (struct echo_device *d)
static struct echo_device * obd2echo_dev (const struct obd_device *obd)
static struct cl_object * echo_obj2cl (struct echo_object *eco)
static struct echo_object * cl2echo_obj (const struct cl_object *o)
static struct echo_page * cl2echo_page (const struct cl_page_slice *s)
static struct echo_lock * cl2echo_lock (const struct cl_lock_slice *s)
static struct cl_lock * echo_lock2cl (const struct echo_lock *ecl)
static struct echo_thread_info * echo_env_info (const struct lu_env *env)
static struct echo_object_conf * cl2echo_conf (const struct cl_object_conf *c)
Variables
static struct lu_context_key echo_thread_key
Function Documentation
static struct echo_object_conf* cl2echo_conf (const struct cl_object_conf * c) [static, read]
Definition at line 184 of file echo_client.c.
References echo_object_conf::eoc_cl.
Referenced by echo_object_init().
static struct echo_device* cl2echo_dev (const struct cl_device * dev) [static, read]
Definition at line 134 of file echo_client.c.
References echo_device::ed_cl.
Referenced by echo_device_fini(), echo_device_free(), echo_object_init(), and obd2echo_dev().
static struct echo_lock* cl2echo_lock (const struct cl_lock_slice * s) [static, read]
Definition at line 164 of file echo_client.c.
References echo_lock::el_cl.
Referenced by cl_echo_enqueue0(), and echo_lock_fini().
static struct echo_object* cl2echo_obj (const struct cl_object * o) [static, read]
Definition at line 154 of file echo_client.c.
References echo_object::eo_cl.
Referenced by cl_echo_object_find(), echo_lock_init(), echo_object_free(), echo_object_init(), echo_object_print(), echo_page_fini(), and echo_page_init().
static struct echo_page* cl2echo_page (const struct cl_page_slice * s) [static, read]
Definition at line 159 of file echo_client.c.
References echo_page::ep_cl.
Referenced by echo_page_disown(), echo_page_is_vmlocked(), echo_page_own(), and echo_page_print().
static struct cl_device* echo_dev2cl (struct echo_device * d) [static, read]
Definition at line 139 of file echo_client.c.
References echo_device::ed_cl.
Referenced by cl_echo_object_find().
static struct echo_thread_info* echo_env_info (const struct lu_env * env) [static, read]
Definition at line 175 of file echo_client.c.
References echo_thread_key, LASSERT, lu_env::le_ctx, and lu_context_key_get().
Referenced by cl_echo_enqueue0(), cl_echo_object_brw(), cl_echo_object_find(), and echo_commit_callback().
static struct cl_lock* echo_lock2cl (const struct echo_lock * ecl) [static, read]
Definition at line 169 of file echo_client.c.
References cl_lock_slice::cls_lock, and echo_lock::el_cl.
Referenced by echo_lock_release().
static struct cl_object* echo_obj2cl (struct echo_object * eco) [static, read]
Definition at line 149 of file echo_client.c.
References echo_object::eo_cl.
Referenced by cl_echo_enqueue0(), cl_echo_object_brw(), cl_echo_object_put(), and echo_object_alloc().
static struct echo_device* obd2echo_dev (const struct obd_device * obd) [static, read]
Definition at line 144 of file echo_client.c.
References cl2echo_dev(), lu2cl_dev(), and obd_device::obd_lu_dev.
Referenced by echo_client_brw_ioctl(), echo_client_cleanup(), and echo_client_iocontrol().
Variable Documentation
static struct lu_context_key echo_thread_key [static, read]
Initial value:
 {
        .lct_tags = LCT_CL_THREAD,
        .lct_init = echo_thread_key_init,
        .lct_fini = echo_thread_key_fini,
        .lct_exit = echo_thread_key_exit
}
Definition at line 174 of file echo_client.c.
Referenced by echo_env_info().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.