Lustre: req_layout
req_layout
Data Structures
struct req_capsule
Defines
#define REQ_MAX_FIELD_NR 9
Enumerations
enum req_location { RCL_CLIENT, RCL_SERVER, RCL_NR }
Functions
void req_capsule_init (struct req_capsule *pill, struct ptlrpc_request *req, enum req_location location)
Initialize a pill.
void req_capsule_fini (struct req_capsule *pill)
void req_capsule_set (struct req_capsule *pill, const struct req_format *fmt)
Set the format (fmt) of a pill; format changes are not allowed here (see req_capsule_extend()).
void req_capsule_client_dump (struct req_capsule *pill)
Dump a request.
void req_capsule_server_dump (struct req_capsule *pill)
Dump a reply.
void req_capsule_init_area (struct req_capsule *pill)
Initializes the expected sizes of each RMF in a pill (rc_area) to -1.
size_t req_capsule_filled_sizes (struct req_capsule *pill, enum req_location loc)
Fills in any parts of the rc_area of a pill that haven't been filled in yet.
int req_capsule_server_pack (struct req_capsule *pill)
Capsule equivalent of lustre_pack_request() and lustre_pack_reply().
void * req_capsule_client_get (struct req_capsule *pill, const struct req_msg_field *field)
Trivial wrapper around __req_capsule_get(), that returns the PTLRPC request buffer corresponding to the given RMF (field) of a pill.
void * req_capsule_client_swab_get (struct req_capsule *pill, const struct req_msg_field *field, void *swabber)
Same as req_capsule_client_get(), but with a swabber argument.
void * req_capsule_client_sized_get (struct req_capsule *pill, const struct req_msg_field *field, __u32 len)
Utility that combines req_capsule_set_size() and req_capsule_client_get().
void * req_capsule_server_get (struct req_capsule *pill, const struct req_msg_field *field)
Trivial wrapper around __req_capsule_get(), that returns the PTLRPC reply buffer corresponding to the given RMF (field) of a pill.
void * req_capsule_server_sized_get (struct req_capsule *pill, const struct req_msg_field *field, __u32 len)
Utility that combines req_capsule_set_size() and req_capsule_server_get().
void * req_capsule_server_swab_get (struct req_capsule *pill, const struct req_msg_field *field, void *swabber)
Same as req_capsule_server_get(), but with a swabber argument.
void * req_capsule_server_sized_swab_get (struct req_capsule *pill, const struct req_msg_field *field, __u32 len, void *swabber)
const void * req_capsule_other_get (struct req_capsule *pill, const struct req_msg_field *field)
Returns the buffer of a pill corresponding to the given field from the request (if the caller is executing on the server-side) or reply (if the caller is executing on the client-side).
void req_capsule_set_size (struct req_capsule *pill, const struct req_msg_field *field, enum req_location loc, __u32 size)
Set the size of the PTLRPC request/reply (loc) buffer for the given field of the given pill.
__u32 req_capsule_get_size (const struct req_capsule *pill, const struct req_msg_field *field, enum req_location loc)
Return the actual PTLRPC buffer length of a request or reply (loc) for the given pill's given field.
__u32 req_capsule_msg_size (struct req_capsule *pill, enum req_location loc)
Wrapper around lustre_msg_size() that returns the PTLRPC size needed for the given pill's request or reply (loc) given the field size recorded in the pill's rc_area.
__u32 req_capsule_fmt_size (__u32 magic, const struct req_format *fmt, enum req_location loc)
While req_capsule_msg_size() computes the size of a PTLRPC request or reply (loc) given a pill's rc_area, this function computes the size of a PTLRPC request or reply given only an RQF (fmt).
void req_capsule_extend (struct req_capsule *pill, const struct req_format *fmt)
Changes the format of an RPC.
int req_capsule_has_field (const struct req_capsule *pill, const struct req_msg_field *field, enum req_location loc)
This function returns a non-zero value if the given field is present in the format (rc_fmt) of pill's PTLRPC request or reply (loc), else it returns 0.
int req_capsule_field_present (const struct req_capsule *pill, const struct req_msg_field *field, enum req_location loc)
Returns a non-zero value if the given field is present in the given pill's PTLRPC request or reply (loc), else it returns 0.
void req_capsule_shrink (struct req_capsule *pill, const struct req_msg_field *field, __u32 newlen, enum req_location loc)
This function shrinks the size of the _buffer_ of the pill's PTLRPC request or reply (loc).
int req_capsule_server_grow (struct req_capsule *pill, const struct req_msg_field *field, __u32 newlen)
int req_layout_init (void)
Initializes the capsule abstraction by computing and setting the rf_idx field of RQFs and the rmf_offset field of RMFs.
void req_layout_fini (void)
Variables
struct req_format RQF_OBD_PING
struct req_format RQF_OBD_SET_INFO
struct req_format RQF_SEC_CTX
struct req_format RQF_OBD_IDX_READ
struct req_format RQF_MGS_TARGET_REG
struct req_format RQF_MGS_SET_INFO
struct req_format RQF_MGS_CONFIG_READ
struct req_format RQF_SEQ_QUERY
struct req_format RQF_FLD_QUERY
struct req_format RQF_FLD_READ
struct req_format RQF_MDS_CONNECT
struct req_format RQF_MDS_DISCONNECT
struct req_format RQF_MDS_STATFS
struct req_format RQF_MDS_GET_ROOT
struct req_format RQF_MDS_SYNC
struct req_format RQF_MDS_GETXATTR
struct req_format RQF_MDS_GETATTR
struct req_format RQF_OUT_UPDATE
struct req_format RQF_MDS_GETATTR_NAME
struct req_format RQF_MDS_CLOSE
struct req_format RQF_MDS_INTENT_CLOSE
struct req_format RQF_MDS_GET_INFO
struct req_format RQF_MDS_READPAGE
struct req_format RQF_MDS_REINT
struct req_format RQF_MDS_REINT_CREATE
struct req_format RQF_MDS_REINT_CREATE_RMT_ACL
struct req_format RQF_MDS_REINT_CREATE_SLAVE
struct req_format RQF_MDS_REINT_CREATE_SYM
struct req_format RQF_MDS_REINT_OPEN
struct req_format RQF_MDS_REINT_UNLINK
struct req_format RQF_MDS_REINT_LINK
struct req_format RQF_MDS_REINT_RENAME
struct req_format RQF_MDS_REINT_SETATTR
struct req_format RQF_MDS_REINT_SETXATTR
struct req_format RQF_MDS_QUOTACTL
struct req_format RQF_QUOTA_DQACQ
struct req_format RQF_MDS_SWAP_LAYOUTS
struct req_format RQF_MDS_REINT_MIGRATE
struct req_format RQF_MDS_HSM_STATE_GET
struct req_format RQF_MDS_HSM_STATE_SET
struct req_format RQF_MDS_HSM_ACTION
struct req_format RQF_MDS_HSM_PROGRESS
struct req_format RQF_MDS_HSM_CT_REGISTER
struct req_format RQF_MDS_HSM_CT_UNREGISTER
struct req_format RQF_MDS_HSM_REQUEST
struct req_format RQF_OST_CONNECT
struct req_format RQF_OST_DISCONNECT
struct req_format RQF_OST_QUOTACTL
struct req_format RQF_OST_GETATTR
struct req_format RQF_OST_SETATTR
struct req_format RQF_OST_CREATE
struct req_format RQF_OST_PUNCH
struct req_format RQF_OST_SYNC
struct req_format RQF_OST_DESTROY
struct req_format RQF_OST_BRW_READ
struct req_format RQF_OST_BRW_WRITE
struct req_format RQF_OST_STATFS
struct req_format RQF_OST_SET_GRANT_INFO
struct req_format RQF_OST_GET_INFO
struct req_format RQF_OST_GET_INFO_LAST_ID
struct req_format RQF_OST_GET_INFO_LAST_FID
struct req_format RQF_OST_SET_INFO_LAST_FID
struct req_format RQF_OST_GET_INFO_FIEMAP
struct req_format RQF_OST_LADVISE
struct req_format RQF_LDLM_ENQUEUE
struct req_format RQF_LDLM_ENQUEUE_LVB
struct req_format RQF_LDLM_CONVERT
struct req_format RQF_LDLM_INTENT
struct req_format RQF_LDLM_INTENT_BASIC
struct req_format RQF_LDLM_INTENT_LAYOUT
struct req_format RQF_LDLM_INTENT_GETATTR
struct req_format RQF_LDLM_INTENT_OPEN
struct req_format RQF_LDLM_INTENT_CREATE
struct req_format RQF_LDLM_INTENT_UNLINK
struct req_format RQF_LDLM_INTENT_GETXATTR
struct req_format RQF_LDLM_INTENT_QUOTA
struct req_format RQF_LDLM_CANCEL
struct req_format RQF_LDLM_CALLBACK
struct req_format RQF_LDLM_CP_CALLBACK
struct req_format RQF_LDLM_BL_CALLBACK
struct req_format RQF_LDLM_GL_CALLBACK
struct req_format RQF_LDLM_GL_DESC_CALLBACK
struct req_format RQF_LOG_CANCEL
struct req_format RQF_LLOG_ORIGIN_HANDLE_CREATE
struct req_format RQF_LLOG_ORIGIN_HANDLE_DESTROY
struct req_format RQF_LLOG_ORIGIN_HANDLE_NEXT_BLOCK
struct req_format RQF_LLOG_ORIGIN_HANDLE_PREV_BLOCK
struct req_format RQF_LLOG_ORIGIN_HANDLE_READ_HEADER
struct req_format RQF_LLOG_ORIGIN_CONNECT
struct req_format RQF_CONNECT
struct req_format RQF_LFSCK_NOTIFY
struct req_format RQF_LFSCK_QUERY
struct req_msg_field RMF_GENERIC_DATA
struct req_msg_field RMF_PTLRPC_BODY
struct req_msg_field RMF_MDT_BODY
struct req_msg_field RMF_MDT_EPOCH
struct req_msg_field RMF_OBD_STATFS
struct req_msg_field RMF_NAME
struct req_msg_field RMF_SYMTGT
struct req_msg_field RMF_TGTUUID
struct req_msg_field RMF_CLUUID
struct req_msg_field RMF_SETINFO_VAL
struct req_msg_field RMF_SETINFO_KEY
struct req_msg_field RMF_GETINFO_VAL
struct req_msg_field RMF_GETINFO_VALLEN
struct req_msg_field RMF_GETINFO_KEY
struct req_msg_field RMF_IDX_INFO
struct req_msg_field RMF_CLOSE_DATA
struct req_msg_field RMF_CONN
struct req_msg_field RMF_CONNECT_DATA
struct req_msg_field RMF_DLM_REQ
struct req_msg_field RMF_DLM_REP
struct req_msg_field RMF_DLM_LVB
struct req_msg_field RMF_DLM_GL_DESC
struct req_msg_field RMF_LDLM_INTENT
struct req_msg_field RMF_LAYOUT_INTENT
struct req_msg_field RMF_MDT_MD
struct req_msg_field RMF_REC_REINT
struct req_msg_field RMF_EADATA
struct req_msg_field RMF_EAVALS
struct req_msg_field RMF_EAVALS_LENS
struct req_msg_field RMF_ACL
struct req_msg_field RMF_LOGCOOKIES
struct req_msg_field RMF_CAPA1
struct req_msg_field RMF_CAPA2
struct req_msg_field RMF_OBD_QUOTACHECK
struct req_msg_field RMF_OBD_QUOTACTL
struct req_msg_field RMF_QUOTA_BODY
struct req_msg_field RMF_STRING
struct req_msg_field RMF_SWAP_LAYOUTS
struct req_msg_field RMF_MDS_HSM_PROGRESS
struct req_msg_field RMF_MDS_HSM_REQUEST
struct req_msg_field RMF_MDS_HSM_USER_ITEM
struct req_msg_field RMF_MDS_HSM_ARCHIVE
struct req_msg_field RMF_HSM_USER_STATE
struct req_msg_field RMF_HSM_STATE_SET
struct req_msg_field RMF_MDS_HSM_CURRENT_ACTION
struct req_msg_field RMF_SEQ_OPC
struct req_msg_field RMF_SEQ_RANGE
struct req_msg_field RMF_FID_SPACE
struct req_msg_field RMF_FLD_OPC
struct req_msg_field RMF_FLD_MDFLD
struct req_msg_field RMF_LLOGD_BODY
struct req_msg_field RMF_LLOG_LOG_HDR
struct req_msg_field RMF_LLOGD_CONN_BODY
struct req_msg_field RMF_MGS_TARGET_INFO
struct req_msg_field RMF_MGS_SEND_PARAM
struct req_msg_field RMF_OST_BODY
struct req_msg_field RMF_OBD_IOOBJ
struct req_msg_field RMF_OBD_ID
struct req_msg_field RMF_FID
struct req_msg_field RMF_NIOBUF_REMOTE
struct req_msg_field RMF_RCS
struct req_msg_field RMF_FIEMAP_KEY
struct req_msg_field RMF_FIEMAP_VAL
struct req_msg_field RMF_OST_ID
struct req_msg_field RMF_MGS_CONFIG_BODY
struct req_msg_field RMF_MGS_CONFIG_RES
struct req_msg_field RMF_U32
struct req_msg_field RMF_OUT_UPDATE
struct req_msg_field RMF_OUT_UPDATE_REPLY
struct req_msg_field RMF_OUT_UPDATE_HEADER
struct req_msg_field RMF_OUT_UPDATE_BUF
struct req_msg_field RMF_LFSCK_REQUEST
struct req_msg_field RMF_LFSCK_REPLY
struct req_msg_field RMF_OST_LADVISE_HDR
struct req_msg_field RMF_OST_LADVISE
Define Documentation
#define REQ_MAX_FIELD_NR 9
Definition at line 64 of file lustre_req_layout.h.
Referenced by __req_capsule_offset(), and req_layout_init().
Enumeration Type Documentation
enum req_location
Enumerator:
RCL_CLIENT
RCL_SERVER
RCL_NR
Definition at line 57 of file lustre_req_layout.h.
Function Documentation
void req_capsule_client_dump (struct req_capsule * pill)
Dump a request.
Definition at line 2098 of file layout.c.
References __req_capsule_dump(), and RCL_CLIENT.
void* req_capsule_client_get (struct req_capsule * pill, const struct req_msg_field * field)
Trivial wrapper around __req_capsule_get(), that returns the PTLRPC request buffer corresponding to the given RMF (field) of a pill.
Definition at line 2117 of file layout.c.
References __req_capsule_get(), and RCL_CLIENT.
Referenced by do_set_info_async(), fld_client_rpc(), fld_handle_lookup(), fld_handle_read(), ldlm_callback_handler(), ldlm_cancel_pack(), ldlm_cli_convert(), ldlm_cli_enqueue(), ldlm_fill_lvb(), ldlm_handle_setinfo(), ldlm_prep_elc_req(), lfsck_async_request(), lfsck_layout_async_notify(), lfsck_layout_async_query(), lfsck_layout_master_conditional_destroy(), lfsck_layout_slave_check_pairs(), lfsck_namespace_notify_lmv_remote(), llog_client_destroy(), llog_client_next_block(), llog_client_open(), llog_client_prev_block(), llog_client_read_header(), llog_origin_handle_destroy(), llog_origin_handle_next_block(), llog_origin_handle_open(), llog_origin_handle_prev_block(), llog_origin_handle_read_header(), mdc_close_pack(), mdc_create_pack(), mdc_finish_enqueue(), mdc_get_info_rpc(), mdc_get_root(), mdc_getattr_name(), mdc_getattr_pack(), mdc_intent_close_pack(), mdc_intent_getattr_pack(), mdc_intent_getxattr_pack(), mdc_intent_layout_pack(), mdc_intent_open_pack(), mdc_intent_unlink_pack(), mdc_ioc_hsm_ct_register(), mdc_ioc_hsm_progress(), mdc_ioc_hsm_request(), mdc_ioc_hsm_state_set(), mdc_ioc_swap_layouts(), mdc_link_pack(), mdc_open_pack(), mdc_pack_body(), mdc_pack_name(), mdc_quotactl(), mdc_readdir_pack(), mdc_rename_pack(), mdc_replay_open(), mdc_set_open_replay_data(), mdc_setattr_pack(), mdc_swap_layouts_pack(), mdc_unlink_pack(), mdc_xattr_common(), mdt_body_unpack(), mdt_close_handle_unpack(), mdt_close_swap_layouts(), mdt_create_unpack(), mdt_dlmreq_unpack(), mdt_get_info(), mdt_get_root(), mdt_getattr(), mdt_getattr_name(), mdt_getattr_name_lock(), mdt_getxattr(), mdt_getxattr_pack_reply(), mdt_hsm_ct_register(), mdt_hsm_progress(), mdt_hsm_release(), mdt_hsm_request(), mdt_hsm_state_set(), mdt_intent_fixup_resent(), mdt_intent_getattr(), mdt_intent_layout(), mdt_intent_policy(), mdt_link_unpack(), mdt_name_unpack(), mdt_open_unpack(), mdt_quotactl(), mdt_reint_migrate_internal(), mdt_reint_opcode(), mdt_rename_unpack(), mdt_set_info(), mdt_setattr_unpack(), mdt_setattr_unpack_rec(), mdt_setxattr_unpack(), mdt_swap_layouts(), mdt_unlink_unpack(), mgc_process_recover_log(), mgc_set_mgs_param(), mgc_target_register(), mgs_config_read(), mgs_get_ir_logs(), mgs_llog_open(), mgs_set_info(), mgs_target_reg(), ofd_destroy_hdl(), ofd_get_info_hdl(), ofd_hp_brw(), ofd_ladvise_hdl(), ofd_quotactl(), ofd_rw_hpreq_check(), ofd_rw_hpreq_lock_match(), ofd_set_info_hdl(), osc_brw_prep_request(), osc_build_rpc(), osc_create(), osc_destroy(), osc_io_data_version_start(), osc_ladvise_base(), osc_object_fiemap(), osc_pack_req_body(), osc_punch_base(), osc_quotactl(), osc_set_info_async(), osc_sync_base(), osp_get_lastfid_from_ost(), osp_it_fetch(), osp_obd_set_info_async(), osp_object_truncate(), osp_precreate_cleanup_orphans(), osp_precreate_send(), osp_prep_inline_update_req(), osp_prep_update_req(), osp_sync_inflight_conflict(), osp_sync_new_job(), osp_sync_new_setattr_job(), osp_sync_new_unlink64_job(), osp_sync_new_unlink_job(), osp_sync_process_committed(), out_handle(), qmt_dqacq(), qmt_intent_policy(), qsd_common_glimpse_ast(), qsd_dqacq_interpret(), qsd_fetch_index(), qsd_intent_interpret(), qsd_intent_lock(), qsd_send_dqacq(), replay_one_lock(), seq_client_rpc(), seq_handler(), tgt_brw_read(), tgt_brw_write(), tgt_handle_lfsck_notify(), tgt_handle_lfsck_query(), tgt_init_sec_level(), tgt_io_data_unpack(), tgt_mdt_body_unpack(), tgt_obd_idx_read(), tgt_ost_body_unpack(), tgt_request_preprocess(), and tgt_warn_on_cksum().
void* req_capsule_client_sized_get (struct req_capsule * pill, const struct req_msg_field * field, __u32 len)
Utility that combines req_capsule_set_size() and req_capsule_client_get().
First the pill's request field's size is set (rc_area) using req_capsule_set_size() with the given len. Then the actual buffer is returned.
Definition at line 2145 of file layout.c.
References __req_capsule_get(), RCL_CLIENT, and req_capsule_set_size().
Referenced by llog_client_open().
void* req_capsule_client_swab_get (struct req_capsule * pill, const struct req_msg_field * field, void * swabber)
Same as req_capsule_client_get(), but with a swabber argument.
Currently unused; will be removed when req_capsule_server_swab_get() is unused too.
Definition at line 2130 of file layout.c.
References __req_capsule_get(), and RCL_CLIENT.
Referenced by ldlm_fill_lvb().
void req_capsule_extend (struct req_capsule * pill, const struct req_format * fmt)
Changes the format of an RPC.
The pill must already have been initialized, which means that it already has a request format. The new format fmt must be an extension of the pill's old format. Specifically: the new format must have as many request and reply fields as the old one, and all fields shared by the old and new format must be at least as large in the new format.
The new format's fields may be of different "type" than the old format, but only for fields that are "opaque" blobs: fields which have a) have no rmf_swabber, b) rmf_flags == 0 or RMF_F_NO_SIZE_CHECK, and c) rmf_size == -1 or rmf_flags == RMF_F_NO_SIZE_CHECK. For example, OBD_SET_INFO has a key field and an opaque value field that gets interpreted according to the key field. When the value, according to the key, contains a structure (or array thereof) to be swabbed, the format should be changed to one where the value field has rmf_size/rmf_flags/rmf_swabber set accordingly.
Definition at line 2339 of file layout.c.
References __req_format_is_sane(), FMT_FIELD, LASSERT, req_format::nr, req_capsule::rc_fmt, RCL_NR, req_format::rf_fields, RMF_F_NO_SIZE_CHECK, req_msg_field::rmf_flags, req_msg_field::rmf_size, and req_msg_field::rmf_swabber.
Referenced by ldlm_callback_handler(), ldlm_cli_enqueue(), mdt_create_unpack(), mdt_intent_close_unpack(), mdt_intent_opc(), mdt_intent_policy(), mdt_reint_opcode(), mdt_rename_unpack(), ofd_get_info_hdl(), ofd_set_info_hdl(), osc_ldlm_glimpse_ast(), qmt_intent_policy(), qsd_common_glimpse_ast(), and replay_one_lock().
int req_capsule_field_present (const struct req_capsule * pill, const struct req_msg_field * field, enum req_location loc)
Returns a non-zero value if the given field is present in the given pill's PTLRPC request or reply (loc), else it returns 0.
Definition at line 2396 of file layout.c.
References __req_capsule_offset(), __req_msg(), LASSERT, lustre_msg_bufcount(), RCL_CLIENT, RCL_SERVER, and req_capsule_has_field().
Referenced by llog_origin_handle_open(), mdt_intent_close_unpack(), mdt_open_unpack(), mdt_reint_migrate_internal(), mdt_setattr_unpack(), mdt_setxattr_unpack(), ofd_destroy_hdl(), req_capsule_server_grow(), and req_capsule_shrink().
size_t req_capsule_filled_sizes (struct req_capsule * pill, enum req_location loc)
Fills in any parts of the rc_area of a pill that haven't been filled in yet.
rc_area is an array of REQ_MAX_FIELD_NR elements, used to store sizes of variable-sized fields. The field sizes come from the declared rmf_size field of a pill's rc_fmt's RMF's.
Definition at line 1833 of file layout.c.
References req_format::d, LASSERT, req_format::nr, req_capsule::rc_area, req_capsule::rc_fmt, RCL_SERVER, req_format::rf_fields, and req_msg_field::rmf_size.
Referenced by ldlm_cli_cancel_req(), ldlm_prep_elc_req(), ptlrpc_request_bufs_pack(), ptlrpc_request_set_replen(), and req_capsule_server_pack().
void req_capsule_fini (struct req_capsule * pill)
Definition at line 1792 of file layout.c.
Referenced by __ptlrpc_free_req(), and tgt_request_handle().
__u32 req_capsule_fmt_size (__u32 magic, const struct req_format * fmt, enum req_location loc)
While req_capsule_msg_size() computes the size of a PTLRPC request or reply (loc) given a pill's rc_area, this function computes the size of a PTLRPC request or reply given only an RQF (fmt).
This function should not be used for formats which contain variable size fields.
Definition at line 2296 of file layout.c.
References cfs_size_round(), req_format::d, lustre_msg_hdr_size(), req_format::nr, req_format::rf_fields, req_msg_field::rmf_size, and size.
Referenced by ldlm_format_handles_avail().
__u32 req_capsule_get_size (const struct req_capsule * pill, const struct req_msg_field * field, enum req_location loc)
Return the actual PTLRPC buffer length of a request or reply (loc) for the given pill's given field.
NB: this function doesn't correspond with req_capsule_set_size(), which actually sets the size in pill.rc_area[loc][offset], but this function returns the message buflen[offset], maybe we should use another name.
Definition at line 2263 of file layout.c.
References __req_capsule_offset(), __req_msg(), LASSERT, lustre_msg_buflen(), RCL_CLIENT, and RCL_SERVER.
Referenced by __req_capsule_dump(), ldlm_cancel_pack(), ldlm_cli_enqueue(), ldlm_cli_enqueue_fini(), ldlm_handle_cp_callback(), ldlm_handle_setinfo(), mdc_finish_enqueue(), mdc_pack_name(), mdt_close(), mdt_close_handle_unpack(), mdt_create_unpack(), mdt_dlmreq_unpack(), mdt_fix_reply(), mdt_get_info(), mdt_get_root(), mdt_getattr_internal(), mdt_hsm_request(), mdt_mfd_open(), mdt_name_unpack(), mdt_open_unpack(), mdt_prep_ma_buf_from_rep(), mdt_set_info(), mdt_setattr_unpack(), mdt_setxattr_unpack(), ofd_get_info_hdl(), ofd_ladvise_hdl(), ofd_set_info_hdl(), out_handle(), ptlrpc_connect_interpret(), req_capsule_server_grow(), tgt_brw_write(), and tgt_io_data_unpack().
int req_capsule_has_field (const struct req_capsule * pill, const struct req_msg_field * field, enum req_location loc)
This function returns a non-zero value if the given field is present in the format (rc_fmt) of pill's PTLRPC request or reply (loc), else it returns 0.
Definition at line 2382 of file layout.c.
References LASSERT, req_capsule::rc_fmt, RCL_CLIENT, RCL_SERVER, req_format::rf_idx, and req_msg_field::rmf_offset.
Referenced by mdc_xattr_common(), mdt_fix_reply(), mdt_intent_close_unpack(), mdt_reint_internal(), mdt_unpack_req_pack_rep(), req_capsule_field_present(), req_capsule_server_grow(), req_capsule_shrink(), tgt_handle_request0(), tgt_ost_body_unpack(), and tgt_request_preprocess().
void req_capsule_init (struct req_capsule * pill, struct ptlrpc_request * req, enum req_location location)
Initialize a pill.
The location indicates whether the caller is executing on the client side (RCL_CLIENT) or server side (RCL_SERVER)..
Definition at line 1762 of file layout.c.
References LASSERT, req_capsule::rc_loc, req_capsule::rc_req, RCL_CLIENT, RCL_SERVER, req_capsule_init_area(), ptlrpc_request::rq_pill, and ptlrpc_request::rq_pill_init.
Referenced by ldlm_callback_handler(), ptlrpc_request_alloc_internal(), tgt_hpreq_handler(), and tgt_request_handle().
void req_capsule_init_area (struct req_capsule * pill)
Initializes the expected sizes of each RMF in a pill (rc_area) to -1.
Actual/expected field sizes are set elsewhere in functions in this file: req_capsule_init(), req_capsule_server_pack(), req_capsule_set_size() and req_capsule_msg_size(). The rc_area information is used by. ptlrpc_request_set_replen().
Definition at line 1745 of file layout.c.
References ARRAY_SIZE, req_capsule::rc_area, RCL_CLIENT, and RCL_SERVER.
Referenced by req_capsule_init().
__u32 req_capsule_msg_size (struct req_capsule * pill, enum req_location loc)
Wrapper around lustre_msg_size() that returns the PTLRPC size needed for the given pill's request or reply (loc) given the field size recorded in the pill's rc_area.
See also req_capsule_set_size().
Definition at line 2281 of file layout.c.
References obd_import::imp_msg_magic, lustre_msg_size(), req_format::nr, req_capsule::rc_area, req_capsule::rc_fmt, req_capsule::rc_req, req_format::rf_fields, and ptlrpc_request::rq_import.
Referenced by ldlm_capsule_handles_avail().
const void* req_capsule_other_get (struct req_capsule * pill, const struct req_msg_field * field)
Returns the buffer of a pill corresponding to the given field from the request (if the caller is executing on the server-side) or reply (if the caller is executing on the client-side).
This function convienient for use is code that could be executed on the client and server alike.
Definition at line 2212 of file layout.c.
References __req_capsule_get(), and req_capsule::rc_loc.
void req_capsule_server_dump (struct req_capsule * pill)
Dump a reply.
Definition at line 2107 of file layout.c.
References __req_capsule_dump(), and RCL_SERVER.
void* req_capsule_server_get (struct req_capsule * pill, const struct req_msg_field * field)
Trivial wrapper around __req_capsule_get(), that returns the PTLRPC reply buffer corresponding to the given RMF (field) of a pill.
Definition at line 2158 of file layout.c.
References __req_capsule_get(), and RCL_SERVER.
Referenced by fld_client_rpc(), fld_handle_lookup(), fld_handle_read(), fld_update_from_controller(), ldlm_cli_convert(), ldlm_cli_enqueue_fini(), ldlm_fill_lvb(), lfsck_async_interpret_common(), lfsck_layout_slave_async_interpret(), ll_close_inode_openhandle(), ll_dir_get_parent_fid(), ll_dir_getstripe(), ll_dir_ioctl(), ll_get_fid_by_name(), ll_getxattr_common(), ll_iocontrol(), ll_layout_fetch(), ll_lookup_it(), ll_lov_getstripe_ea_info(), ll_migrate(), ll_och_fill(), ll_open_cleanup(), ll_readlink_internal(), ll_update_times(), ll_xattr_cache_refill(), llog_client_next_block(), llog_client_open(), llog_client_prev_block(), llog_client_read_header(), llog_origin_handle_next_block(), llog_origin_handle_open(), llog_origin_handle_prev_block(), llog_origin_handle_read_header(), lmv_getattr_name(), lmv_intent_lookup(), lmv_intent_open(), lmv_intent_remote(), lmv_rename(), lmv_revalidate_slaves(), lmv_unlink(), mdc_close(), mdc_enqueue(), mdc_finish_enqueue(), mdc_finish_intent_lock(), mdc_get_info_rpc(), mdc_get_lustre_md(), mdc_get_root(), mdc_getattr_common(), mdc_intent_getattr_async_interpret(), mdc_ioc_hsm_current_action(), mdc_ioc_hsm_state_get(), mdc_quotactl(), mdc_reint(), mdc_replay_open(), mdc_set_open_replay_data(), mdc_statfs(), mdt_client_compatibility(), mdt_close(), mdt_close_swap_layouts(), mdt_finish_open(), mdt_fix_reply(), mdt_get_info(), mdt_get_root(), mdt_getattr(), mdt_getattr_internal(), mdt_getattr_name(), mdt_getxattr(), mdt_getxattr_all(), mdt_handle_last_unlink(), mdt_hsm_action(), mdt_hsm_release(), mdt_hsm_state_get(), mdt_intent_getattr(), mdt_intent_getxattr(), mdt_intent_opc(), mdt_intent_reint(), mdt_md_create(), mdt_mfd_open(), mdt_object_open_unlock(), mdt_open_by_fid(), mdt_prep_ma_buf_from_rep(), mdt_quotactl(), mdt_raw_lookup(), mdt_readpage(), mdt_reconstruct_create(), mdt_reconstruct_open(), mdt_reconstruct_setattr(), mdt_reint_internal(), mdt_reint_migrate_internal(), mdt_reint_open(), mdt_reint_rename_internal(), mdt_reint_setattr(), mdt_reint_unlink(), mdt_statfs(), mdt_sync(), mgc_process_recover_log(), mgc_set_mgs_param(), mgc_target_register(), mgs_get_ir_logs(), mgs_set_info(), mgs_target_reg(), ofd_create_hdl(), ofd_destroy_hdl(), ofd_get_info_hdl(), ofd_getattr_hdl(), ofd_ladvise_hdl(), ofd_punch_hdl(), ofd_quotactl(), ofd_set_info_hdl(), ofd_setattr_hdl(), ofd_statfs_hdl(), ofd_sync_hdl(), osc_brw_fini_request(), osc_create(), osc_data_version_interpret(), osc_enqueue_fini(), osc_getattr(), osc_ladvise_interpret(), osc_ldlm_glimpse_ast(), osc_object_fiemap(), osc_quotactl(), osc_setattr(), osc_setattr_interpret(), osc_shrink_grant_interpret(), osc_statfs(), osc_statfs_interpret(), osc_sync_interpret(), osp_get_lastfid_from_ost(), osp_it_fetch(), osp_obd_statfs(), osp_precreate_cleanup_orphans(), osp_precreate_send(), osp_statfs_interpret(), out_handle(), ptlrpc_connect_interpret(), qmt_dqacq(), qmt_intent_policy(), qsd_common_glimpse_ast(), qsd_dqacq_interpret(), qsd_fetch_index(), qsd_intent_interpret(), replay_lock_interpret(), sa_instantiate(), seq_client_rpc(), seq_handler(), tgt_brw_read(), tgt_brw_write(), tgt_connect(), tgt_handle_lfsck_query(), tgt_init_sec_level(), and tgt_obd_idx_read().
int req_capsule_server_grow (struct req_capsule * pill, const struct req_msg_field * field, __u32 newlen)
Definition at line 2448 of file layout.c.
References __req_capsule_offset(), __req_format_is_sane(), CERROR, cfs_size_round(), LASSERT, lustre_msg_buf(), lustre_packed_msg_size(), ptlrpc_rs_decref(), req_capsule::rc_fmt, req_capsule::rc_req, RCL_SERVER, req_capsule_field_present(), req_capsule_get_size(), req_capsule_has_field(), req_capsule_server_pack(), req_capsule_set_size(), ptlrpc_request::rq_repbuf_len, ptlrpc_request::rq_repmsg, ptlrpc_reply_state::rs_difficult, ptlrpc_reply_state::rs_locks, ptlrpc_reply_state::rs_modes, ptlrpc_reply_state::rs_msg, ptlrpc_reply_state::rs_nlocks, and ptlrpc_reply_state::rs_no_ack.
Referenced by mdt_fix_reply().
int req_capsule_server_pack (struct req_capsule * pill)
Capsule equivalent of lustre_pack_request() and lustre_pack_reply().
This function uses the pill's rc_area as filled in by req_capsule_set_size() or req_capsule_filled_sizes() (the latter is called by this function).
Definition at line 1868 of file layout.c.
References D_ERROR, DEBUG_REQ, LASSERT, lustre_pack_reply(), req_capsule::rc_area, req_capsule::rc_fmt, req_capsule::rc_loc, req_capsule::rc_req, RCL_SERVER, req_capsule_filled_sizes(), and req_format::rf_name.
Referenced by fld_handle_lookup(), fld_handle_read(), llog_origin_handle_close(), llog_origin_handle_destroy(), llog_origin_handle_next_block(), llog_origin_handle_open(), llog_origin_handle_prev_block(), llog_origin_handle_read_header(), mdt_close(), mdt_get_info(), mdt_getattr(), mdt_getxattr_pack_reply(), mdt_intent_layout(), mdt_intent_policy(), mdt_quotactl(), mdt_reint_internal(), mdt_unpack_req_pack_rep(), ofd_get_info_hdl(), ofd_set_info_hdl(), osc_ldlm_glimpse_ast(), out_handle(), qmt_intent_policy(), qsd_common_glimpse_ast(), req_capsule_server_grow(), tgt_brw_write(), tgt_handle_request0(), and tgt_obd_idx_read().
void* req_capsule_server_sized_get (struct req_capsule * pill, const struct req_msg_field * field, __u32 len)
Utility that combines req_capsule_set_size() and req_capsule_server_get().
First the pill's request field's size is set (rc_area) using req_capsule_set_size() with the given len. Then the actual buffer is returned.
Definition at line 2186 of file layout.c.
References __req_capsule_get(), RCL_SERVER, and req_capsule_set_size().
Referenced by check_write_rcs(), ll_dir_getstripe(), ll_getxattr_common(), ll_layout_fetch(), ll_lov_getstripe_ea_info(), ll_xattr_cache_refill(), mdc_finish_enqueue(), mdc_get_lustre_md(), mdc_getattr_common(), osp_attr_get(), osp_md_index_lookup(), osp_md_read(), osp_update_interpret(), osp_xattr_get(), and ptlrpc_connect_interpret().
void* req_capsule_server_sized_swab_get (struct req_capsule * pill, const struct req_msg_field * field, __u32 len, void * swabber)
Definition at line 2195 of file layout.c.
References __req_capsule_get(), RCL_SERVER, and req_capsule_set_size().
Referenced by ldlm_fill_lvb().
void* req_capsule_server_swab_get (struct req_capsule * pill, const struct req_msg_field * field, void * swabber)
Same as req_capsule_server_get(), but with a swabber argument.
Ideally all swabbing should be done pursuant to RMF definitions, with no swabbing done outside this capsule abstraction.
Definition at line 2171 of file layout.c.
References __req_capsule_get(), and RCL_SERVER.
Referenced by ldlm_fill_lvb(), lustre_check_remote_perm(), mdc_finish_enqueue(), mdc_get_lustre_md(), mdc_getattr_common(), ofd_lvbo_update(), and qmt_lvbo_update().
void req_capsule_set (struct req_capsule * pill, const struct req_format * fmt)
Set the format (fmt) of a pill; format changes are not allowed here (see req_capsule_extend()).
Definition at line 1816 of file layout.c.
References __req_format_is_sane(), LASSERT, and req_capsule::rc_fmt.
Referenced by fld_handle_query(), fld_handle_read(), ldlm_callback_handler(), ldlm_handle_setinfo(), out_handle(), ptlrpc_request_alloc_internal(), tgt_obd_idx_read(), tgt_request_handle(), and tgt_request_preprocess().
void req_capsule_set_size (struct req_capsule * pill, const struct req_msg_field * field, enum req_location loc, __u32 size)
Set the size of the PTLRPC request/reply (loc) buffer for the given field of the given pill.
This function must be used when constructing variable sized fields of a request or reply.
Definition at line 2226 of file layout.c.
References __req_capsule_offset(), CERROR, LASSERT, LBUG, req_capsule::rc_area, RCL_CLIENT, RCL_SERVER, RMF_F_NO_SIZE_CHECK, RMF_F_STRUCT_ARRAY, req_msg_field::rmf_flags, req_msg_field::rmf_name, and req_msg_field::rmf_size.
Referenced by do_set_info_async(), fld_client_rpc(), fld_handle_read(), ldlm_cli_cancel_req(), ldlm_cli_enqueue(), ldlm_enqueue_pack(), ldlm_prep_elc_req(), llog_client_next_block(), llog_client_open(), llog_client_prev_block(), llog_origin_handle_next_block(), llog_origin_handle_prev_block(), mdc_close(), mdc_create(), mdc_enqueue_pack(), mdc_finish_enqueue(), mdc_get_info_rpc(), mdc_get_remote_perm(), mdc_get_root(), mdc_getattr(), mdc_getattr_name(), mdc_intent_getattr_pack(), mdc_intent_getxattr_pack(), mdc_intent_layout_pack(), mdc_intent_open_pack(), mdc_intent_unlink_pack(), mdc_ioc_hsm_request(), mdc_link(), mdc_rename(), mdc_setattr(), mdc_unlink(), mdc_xattr_common(), mdt_close(), mdt_get_info(), mdt_getattr(), mdt_getxattr_pack_reply(), mdt_intent_layout(), mdt_intent_policy(), mdt_reint_internal(), mdt_unpack_req_pack_rep(), mgc_enqueue(), ofd_get_info_hdl(), osc_brw_prep_request(), osc_enqueue_base(), osc_ladvise_base(), osc_ldlm_glimpse_ast(), osc_object_fiemap(), osc_set_info_async(), osp_get_lastfid_from_ost(), osp_obd_set_info_async(), osp_prep_inline_update_req(), osp_prep_update_req(), out_handle(), ptlrpc_connect_import(), qmt_intent_policy(), qsd_common_glimpse_ast(), qsd_intent_lock(), replay_one_lock(), req_capsule_client_sized_get(), req_capsule_server_grow(), req_capsule_server_sized_get(), req_capsule_server_sized_swab_get(), tgt_brw_write(), and tgt_handle_request0().
void req_capsule_shrink (struct req_capsule * pill, const struct req_msg_field * field, __u32 newlen, enum req_location loc)
This function shrinks the size of the _buffer_ of the pill's PTLRPC request or reply (loc).
This is not the opposite of req_capsule_extend().
Definition at line 2416 of file layout.c.
References __req_capsule_offset(), __req_format_is_sane(), __req_msg(), LASSERT, LASSERTF, lustre_msg, lustre_msg_buflen(), lustre_shrink_msg(), msg, req_capsule::rc_fmt, req_capsule::rc_req, RCL_CLIENT, req_capsule_field_present(), req_capsule_has_field(), req_format::rf_name, req_msg_field::rmf_name, ptlrpc_request::rq_replen, and ptlrpc_request::rq_reqlen.
Referenced by mdc_finish_enqueue(), mdt_fix_reply(), mdt_getxattr_all(), osc_ldlm_glimpse_ast(), ptlrpc_request_pack(), and qmt_intent_policy().
void req_layout_fini (void)
Definition at line 1732 of file layout.c.
Referenced by ptlrpc_exit(), and ptlrpc_init().
int req_layout_init (void)
Initializes the capsule abstraction by computing and setting the rf_idx field of RQFs and the rmf_offset field of RMFs.
Definition at line 1701 of file layout.c.
References ARRAY_SIZE, req_format::d, LASSERT, req_format::nr, RCL_NR, REQ_MAX_FIELD_NR, req_format::rf_fields, req_format::rf_idx, RMF_F_STRUCT_ARRAY, req_msg_field::rmf_flags, req_msg_field::rmf_offset, and req_msg_field::rmf_size.
Referenced by ptlrpc_init().
Variable Documentation
struct req_msg_field RMF_ACL
Definition at line 1075 of file layout.c.
Referenced by lustre_check_remote_perm(), mdc_finish_enqueue(), mdc_get_lustre_md(), mdc_get_remote_perm(), mdc_getattr(), mdc_getattr_common(), mdc_intent_getattr_pack(), mdc_intent_open_pack(), mdt_finish_open(), mdt_fix_reply(), and mdt_getattr_internal().
struct req_msg_field RMF_CAPA1
Definition at line 1086 of file layout.c.
Referenced by mdt_fix_reply().
struct req_msg_field RMF_CAPA2
Definition at line 1091 of file layout.c.
Referenced by mdt_fix_reply().
struct req_msg_field RMF_CLOSE_DATA
Definition at line 964 of file layout.c.
Referenced by mdc_intent_close_pack(), mdt_close_swap_layouts(), mdt_hsm_release(), mdt_intent_close_unpack(), and mdt_reint_migrate_internal().
struct req_msg_field RMF_CLUUID
Definition at line 991 of file layout.c.
struct req_msg_field RMF_CONN
Definition at line 1022 of file layout.c.
struct req_msg_field RMF_CONNECT_DATA
Definition at line 1026 of file layout.c.
Referenced by ptlrpc_connect_import(), ptlrpc_connect_interpret(), tgt_connect(), and tgt_init_sec_level().
struct req_msg_field RMF_DLM_GL_DESC
Definition at line 1053 of file layout.c.
Referenced by qsd_common_glimpse_ast().
struct req_msg_field RMF_DLM_LVB
Definition at line 1049 of file layout.c.
Referenced by ldlm_cli_enqueue(), ldlm_cli_enqueue_fini(), ldlm_enqueue_pack(), ldlm_fill_lvb(), ldlm_handle_cp_callback(), mdc_enqueue_pack(), mdc_finish_enqueue(), mdc_intent_layout_pack(), mdt_intent_layout(), mdt_intent_policy(), mgc_enqueue(), ofd_lvbo_update(), osc_enqueue_base(), osc_ldlm_glimpse_ast(), qmt_intent_policy(), qmt_lvbo_update(), qsd_common_glimpse_ast(), qsd_intent_lock(), and replay_one_lock().
struct req_msg_field RMF_DLM_REP
Definition at line 1039 of file layout.c.
Referenced by ldlm_cli_convert(), ldlm_cli_enqueue_fini(), mdc_enqueue(), mdc_finish_enqueue(), mdc_intent_getattr_async_interpret(), mdt_intent_getattr(), mdt_intent_getxattr(), mdt_intent_opc(), mdt_intent_reint(), mdt_object_open_unlock(), mdt_reconstruct_open(), mdt_reint_open(), osc_enqueue_fini(), and replay_lock_interpret().
struct req_msg_field RMF_DLM_REQ
Definition at line 1033 of file layout.c.
Referenced by ldlm_callback_handler(), ldlm_cancel_pack(), ldlm_cli_cancel_req(), ldlm_cli_convert(), ldlm_cli_enqueue(), ldlm_prep_elc_req(), mdc_finish_enqueue(), mdt_dlmreq_unpack(), mdt_intent_fixup_resent(), ofd_destroy_hdl(), replay_one_lock(), and tgt_request_preprocess().
struct req_msg_field RMF_EADATA
Definition at line 1068 of file layout.c.
Referenced by ll_getxattr_common(), ll_layout_fetch(), ll_xattr_cache_refill(), llog_client_next_block(), llog_client_prev_block(), llog_origin_handle_next_block(), llog_origin_handle_prev_block(), mdc_create(), mdc_create_pack(), mdc_finish_enqueue(), mdc_intent_getxattr_pack(), mdc_intent_layout_pack(), mdc_intent_open_pack(), mdc_open_pack(), mdc_setattr(), mdc_setattr_pack(), mdc_xattr_common(), mdt_create_unpack(), mdt_getxattr(), mdt_getxattr_all(), mdt_getxattr_pack_reply(), mdt_open_unpack(), mdt_setattr_unpack(), and mdt_setxattr_unpack().
struct req_msg_field RMF_EAVALS
Definition at line 1072 of file layout.c.
Referenced by ll_xattr_cache_refill(), mdc_intent_getxattr_pack(), mdt_getxattr_all(), and mdt_getxattr_pack_reply().
struct req_msg_field RMF_EAVALS_LENS
Definition at line 1126 of file layout.c.
Referenced by ll_xattr_cache_refill(), mdc_intent_getxattr_pack(), mdt_getxattr_all(), and mdt_getxattr_pack_reply().
struct req_msg_field RMF_FID
Definition at line 1136 of file layout.c.
Referenced by ofd_get_info_hdl(), and osp_get_lastfid_from_ost().
struct req_msg_field RMF_FID_SPACE
struct req_msg_field RMF_FIEMAP_KEY
Definition at line 1146 of file layout.c.
Referenced by ofd_get_info_hdl(), and osc_object_fiemap().
struct req_msg_field RMF_FIEMAP_VAL
Definition at line 1151 of file layout.c.
Referenced by ofd_get_info_hdl(), and osc_object_fiemap().
struct req_msg_field RMF_FLD_MDFLD
Definition at line 932 of file layout.c.
Referenced by fld_client_rpc(), fld_handle_lookup(), and fld_handle_read().
struct req_msg_field RMF_FLD_OPC
Definition at line 927 of file layout.c.
Referenced by fld_client_rpc().
struct req_msg_field RMF_GENERIC_DATA
Definition at line 865 of file layout.c.
Referenced by fld_client_rpc(), fld_handle_read(), fld_update_from_controller(), mdc_ioc_hsm_request(), and mdt_hsm_request().
struct req_msg_field RMF_GETINFO_KEY
Definition at line 903 of file layout.c.
Referenced by mdc_get_info_rpc(), mdt_get_info(), ofd_get_info_hdl(), and osp_get_lastfid_from_ost().
struct req_msg_field RMF_GETINFO_VAL
Definition at line 912 of file layout.c.
Referenced by mdc_get_info_rpc(), and mdt_get_info().
struct req_msg_field RMF_GETINFO_VALLEN
Definition at line 907 of file layout.c.
Referenced by mdc_get_info_rpc(), and mdt_get_info().
struct req_msg_field RMF_HSM_STATE_SET
Definition at line 1164 of file layout.c.
Referenced by mdc_ioc_hsm_state_set(), and mdt_hsm_state_set().
struct req_msg_field RMF_HSM_USER_STATE
Definition at line 1159 of file layout.c.
Referenced by mdc_ioc_hsm_state_get(), and mdt_hsm_state_get().
struct req_msg_field RMF_IDX_INFO
Definition at line 1155 of file layout.c.
Referenced by osp_it_fetch(), qsd_fetch_index(), and tgt_obd_idx_read().
struct req_msg_field RMF_LAYOUT_INTENT
Definition at line 1096 of file layout.c.
Referenced by mdc_intent_layout_pack(), and mdt_intent_layout().
struct req_msg_field RMF_LDLM_INTENT
Definition at line 1044 of file layout.c.
Referenced by mdc_intent_getattr_pack(), mdc_intent_getxattr_pack(), mdc_intent_layout_pack(), mdc_intent_open_pack(), mdc_intent_unlink_pack(), mdt_intent_policy(), qmt_intent_policy(), qsd_intent_interpret(), and qsd_intent_lock().
struct req_msg_field RMF_LFSCK_REPLY
Definition at line 1214 of file layout.c.
Referenced by lfsck_async_interpret_common(), lfsck_layout_slave_async_interpret(), and tgt_handle_lfsck_query().
struct req_msg_field RMF_LFSCK_REQUEST
Definition at line 1209 of file layout.c.
Referenced by lfsck_async_request(), lfsck_layout_async_notify(), lfsck_layout_async_query(), lfsck_layout_master_conditional_destroy(), lfsck_layout_slave_check_pairs(), lfsck_namespace_notify_lmv_remote(), tgt_handle_lfsck_notify(), and tgt_handle_lfsck_query().
struct req_msg_field RMF_LLOG_LOG_HDR
Definition at line 1005 of file layout.c.
Referenced by llog_client_read_header(), and llog_origin_handle_read_header().
struct req_msg_field RMF_LLOGD_BODY
Definition at line 1000 of file layout.c.
Referenced by llog_client_destroy(), llog_client_next_block(), llog_client_open(), llog_client_prev_block(), llog_client_read_header(), llog_origin_handle_destroy(), llog_origin_handle_next_block(), llog_origin_handle_open(), llog_origin_handle_prev_block(), and llog_origin_handle_read_header().
struct req_msg_field RMF_LLOGD_CONN_BODY
Definition at line 1010 of file layout.c.
struct req_msg_field RMF_LOGCOOKIES
Definition at line 1081 of file layout.c.
Referenced by mdc_setattr(), mdt_close(), mdt_fix_reply(), mdt_reint_internal(), mdt_unpack_req_pack_rep(), and tgt_handle_request0().
struct req_msg_field RMF_MDS_HSM_ARCHIVE
Definition at line 1185 of file layout.c.
Referenced by mdc_ioc_hsm_ct_register(), and mdt_hsm_ct_register().
struct req_msg_field RMF_MDS_HSM_CURRENT_ACTION
Definition at line 1174 of file layout.c.
Referenced by mdc_ioc_hsm_current_action(), and mdt_hsm_action().
struct req_msg_field RMF_MDS_HSM_PROGRESS
Definition at line 1169 of file layout.c.
Referenced by mdc_ioc_hsm_progress(), and mdt_hsm_progress().
struct req_msg_field RMF_MDS_HSM_REQUEST [read]
Definition at line 301 of file lustre_req_layout.h.
Referenced by mdc_ioc_hsm_request(), and mdt_hsm_request().
struct req_msg_field RMF_MDS_HSM_USER_ITEM
Definition at line 1179 of file layout.c.
Referenced by mdc_ioc_hsm_request(), and mdt_hsm_request().
struct req_msg_field RMF_MDT_BODY
Definition at line 938 of file layout.c.
Referenced by ll_close_inode_openhandle(), ll_dir_get_parent_fid(), ll_dir_getstripe(), ll_dir_ioctl(), ll_get_fid_by_name(), ll_getxattr_common(), ll_iocontrol(), ll_layout_fetch(), ll_lookup_it(), ll_lov_getstripe_ea_info(), ll_migrate(), ll_och_fill(), ll_open_cleanup(), ll_readlink_internal(), ll_update_times(), ll_xattr_cache_refill(), lmv_getattr_name(), lmv_intent_lookup(), lmv_intent_open(), lmv_intent_remote(), lmv_rename(), lmv_revalidate_slaves(), lmv_unlink(), mdc_close(), mdc_finish_enqueue(), mdc_finish_intent_lock(), mdc_get_lustre_md(), mdc_get_root(), mdc_getattr_common(), mdc_getattr_pack(), mdc_pack_body(), mdc_readdir_pack(), mdc_reint(), mdc_replay_open(), mdc_set_open_replay_data(), mdc_swap_layouts_pack(), mdt_body_unpack(), mdt_client_compatibility(), mdt_close(), mdt_close_swap_layouts(), mdt_finish_open(), mdt_fix_reply(), mdt_get_root(), mdt_getattr(), mdt_getattr_internal(), mdt_getattr_name(), mdt_getattr_name_lock(), mdt_getxattr(), mdt_handle_last_unlink(), mdt_hsm_release(), mdt_intent_getattr(), mdt_md_create(), mdt_mfd_open(), mdt_open_by_fid(), mdt_raw_lookup(), mdt_readpage(), mdt_reconstruct_create(), mdt_reconstruct_open(), mdt_reconstruct_setattr(), mdt_reint_internal(), mdt_reint_migrate_internal(), mdt_reint_open(), mdt_reint_rename_internal(), mdt_reint_setattr(), mdt_reint_unlink(), mdt_sync(), mdt_unpack_req_pack_rep(), sa_instantiate(), tgt_mdt_body_unpack(), and tgt_request_preprocess().
struct req_msg_field RMF_MDT_EPOCH
Definition at line 954 of file layout.c.
Referenced by mdc_close_pack(), mdc_rename_pack(), mdc_replay_open(), mdc_setattr(), mdt_close_handle_unpack(), and mdt_reint_migrate_internal().
struct req_msg_field RMF_MDT_MD
Definition at line 1058 of file layout.c.
Referenced by ll_dir_getstripe(), ll_lov_getstripe_ea_info(), ll_readlink_internal(), mdc_close(), mdc_finish_enqueue(), mdc_get_lustre_md(), mdc_getattr(), mdc_getattr_common(), mdc_getattr_name(), mdc_intent_getattr_pack(), mdc_intent_open_pack(), mdc_intent_unlink_pack(), mdc_rename(), mdc_unlink(), mdt_close(), mdt_fix_reply(), mdt_getattr(), mdt_getattr_internal(), mdt_mfd_open(), mdt_prep_ma_buf_from_rep(), mdt_reint_internal(), mdt_unpack_req_pack_rep(), and tgt_handle_request0().
struct req_msg_field RMF_MGS_CONFIG_BODY
Definition at line 882 of file layout.c.
Referenced by mgc_process_recover_log(), mgs_config_read(), and mgs_get_ir_logs().
struct req_msg_field RMF_MGS_CONFIG_RES
Definition at line 888 of file layout.c.
Referenced by mgc_process_recover_log(), and mgs_get_ir_logs().
struct req_msg_field RMF_MGS_SEND_PARAM
Definition at line 876 of file layout.c.
Referenced by mgc_set_mgs_param(), and mgs_set_info().
struct req_msg_field RMF_MGS_TARGET_INFO
Definition at line 870 of file layout.c.
Referenced by mgc_target_register(), and mgs_target_reg().
struct req_msg_field RMF_NAME
Definition at line 978 of file layout.c.
Referenced by llog_client_open(), llog_origin_handle_open(), mdc_create(), mdc_create_pack(), mdc_get_root(), mdc_getattr_name(), mdc_getattr_pack(), mdc_intent_getattr_pack(), mdc_intent_open_pack(), mdc_intent_unlink_pack(), mdc_link(), mdc_link_pack(), mdc_open_pack(), mdc_rename(), mdc_rename_pack(), mdc_unlink(), mdc_unlink_pack(), mdc_xattr_common(), mdt_create_unpack(), mdt_get_root(), mdt_getattr_name_lock(), mdt_getxattr(), mdt_getxattr_pack_reply(), mdt_link_unpack(), mdt_open_unpack(), mdt_rename_unpack(), mdt_setxattr_unpack(), mdt_unlink_unpack(), and mgs_llog_open().
struct req_msg_field RMF_NIOBUF_REMOTE
Definition at line 1115 of file layout.c.
Referenced by ofd_hp_brw(), ofd_rw_hpreq_check(), ofd_rw_hpreq_lock_match(), osc_brw_prep_request(), tgt_brw_read(), tgt_brw_write(), and tgt_io_data_unpack().
struct req_msg_field RMF_OBD_ID
Definition at line 1131 of file layout.c.
Referenced by ofd_get_info_hdl().
struct req_msg_field RMF_OBD_IOOBJ
Definition at line 1110 of file layout.c.
Referenced by ofd_hp_brw(), ofd_rw_hpreq_check(), ofd_rw_hpreq_lock_match(), osc_brw_prep_request(), tgt_brw_read(), tgt_brw_write(), tgt_io_data_unpack(), and tgt_ost_body_unpack().
struct req_msg_field RMF_OBD_QUOTACHECK
struct req_msg_field RMF_OBD_QUOTACTL
Definition at line 943 of file layout.c.
Referenced by mdc_quotactl(), mdt_quotactl(), ofd_quotactl(), and osc_quotactl().
struct req_msg_field RMF_OBD_STATFS
Definition at line 969 of file layout.c.
Referenced by mdc_statfs(), mdt_statfs(), ofd_statfs_hdl(), osc_statfs(), osc_statfs_interpret(), osp_obd_statfs(), and osp_statfs_interpret().
struct req_msg_field RMF_OST_BODY
Definition at line 1105 of file layout.c.
Referenced by ofd_create_hdl(), ofd_destroy_hdl(), ofd_getattr_hdl(), ofd_ladvise_hdl(), ofd_punch_hdl(), ofd_set_info_hdl(), ofd_setattr_hdl(), ofd_sync_hdl(), osc_brw_fini_request(), osc_brw_prep_request(), osc_build_rpc(), osc_create(), osc_data_version_interpret(), osc_destroy(), osc_getattr(), osc_io_data_version_start(), osc_ladvise_base(), osc_ladvise_interpret(), osc_pack_req_body(), osc_punch_base(), osc_set_info_async(), osc_setattr(), osc_setattr_interpret(), osc_shrink_grant_interpret(), osc_sync_base(), osc_sync_interpret(), osp_object_truncate(), osp_precreate_cleanup_orphans(), osp_precreate_send(), osp_sync_inflight_conflict(), osp_sync_new_job(), osp_sync_new_setattr_job(), osp_sync_new_unlink64_job(), osp_sync_new_unlink_job(), osp_sync_process_committed(), tgt_brw_read(), tgt_brw_write(), tgt_ost_body_unpack(), tgt_request_preprocess(), and tgt_warn_on_cksum().
struct req_msg_field RMF_OST_ID
Definition at line 1141 of file layout.c.
struct req_msg_field RMF_OST_LADVISE
Definition at line 1225 of file layout.c.
Referenced by ofd_ladvise_hdl(), and osc_ladvise_base().
struct req_msg_field RMF_OST_LADVISE_HDR
Definition at line 1219 of file layout.c.
Referenced by ofd_ladvise_hdl(), and osc_ladvise_base().
struct req_msg_field RMF_OUT_UPDATE
Definition at line 1195 of file layout.c.
struct req_msg_field RMF_OUT_UPDATE_BUF
Definition at line 1235 of file layout.c.
Referenced by osp_prep_update_req(), and out_handle().
struct req_msg_field RMF_OUT_UPDATE_HEADER
Definition at line 1231 of file layout.c.
Referenced by osp_prep_inline_update_req(), osp_prep_update_req(), and out_handle().
struct req_msg_field RMF_OUT_UPDATE_REPLY
Definition at line 1199 of file layout.c.
Referenced by osp_attr_get(), osp_md_index_lookup(), osp_md_read(), osp_prep_inline_update_req(), osp_prep_update_req(), osp_update_interpret(), osp_xattr_get(), and out_handle().
struct req_msg_field RMF_PTLRPC_BODY
Definition at line 959 of file layout.c.
Referenced by ptlrpc_request_pack().
struct req_msg_field RMF_QUOTA_BODY
Definition at line 949 of file layout.c.
Referenced by qmt_dqacq(), qmt_intent_policy(), qsd_dqacq_interpret(), qsd_intent_interpret(), qsd_intent_lock(), and qsd_send_dqacq().
struct req_msg_field RMF_RCS
Definition at line 1121 of file layout.c.
Referenced by check_write_rcs(), osc_brw_prep_request(), and tgt_brw_write().
struct req_msg_field RMF_REC_REINT
Definition at line 1062 of file layout.c.
Referenced by mdc_close_pack(), mdc_create_pack(), mdc_link_pack(), mdc_open_pack(), mdc_rename_pack(), mdc_set_open_replay_data(), mdc_setattr_pack(), mdc_unlink_pack(), mdc_xattr_common(), mdt_create_unpack(), mdt_link_unpack(), mdt_open_unpack(), mdt_reint_opcode(), mdt_rename_unpack(), mdt_setattr_unpack_rec(), mdt_setxattr_unpack(), and mdt_unlink_unpack().
struct req_msg_field RMF_SEQ_OPC
Definition at line 916 of file layout.c.
Referenced by seq_client_rpc(), and seq_handler().
struct req_msg_field RMF_SEQ_RANGE
Definition at line 921 of file layout.c.
Referenced by seq_client_rpc(), and seq_handler().
struct req_msg_field RMF_SETINFO_KEY
Definition at line 974 of file layout.c.
Referenced by do_set_info_async(), ldlm_handle_setinfo(), mdt_set_info(), ofd_set_info_hdl(), osc_set_info_async(), and osp_obd_set_info_async().
struct req_msg_field RMF_SETINFO_VAL
Definition at line 899 of file layout.c.
Referenced by do_set_info_async(), ldlm_handle_setinfo(), mdt_set_info(), ofd_set_info_hdl(), osc_set_info_async(), and osp_obd_set_info_async().
struct req_msg_field RMF_STRING
Definition at line 996 of file layout.c.
struct req_msg_field RMF_SWAP_LAYOUTS
Definition at line 1204 of file layout.c.
Referenced by mdc_ioc_swap_layouts(), and mdt_swap_layouts().
struct req_msg_field RMF_SYMTGT
Definition at line 982 of file layout.c.
Referenced by mdc_rename(), mdc_rename_pack(), mdt_create_unpack(), and mdt_rename_unpack().
struct req_msg_field RMF_TGTUUID
Definition at line 986 of file layout.c.
struct req_msg_field RMF_U32
Definition at line 894 of file layout.c.
struct req_format RQF_CONNECT
Definition at line 1601 of file layout.c.
Referenced by tgt_request_handle().
struct req_format RQF_FLD_QUERY
Definition at line 1307 of file layout.c.
Referenced by fld_client_rpc(), and fld_handle_query().
struct req_format RQF_FLD_READ
Definition at line 1311 of file layout.c.
Referenced by fld_client_rpc(), and fld_handle_read().
struct req_format RQF_LDLM_BL_CALLBACK
Definition at line 1468 of file layout.c.
Referenced by ldlm_callback_handler().
struct req_format RQF_LDLM_CALLBACK
Definition at line 1460 of file layout.c.
Referenced by ldlm_callback_handler().
struct req_format RQF_LDLM_CANCEL
Definition at line 1456 of file layout.c.
Referenced by ldlm_cli_cancel(), and ldlm_cli_cancel_req().
struct req_format RQF_LDLM_CONVERT
Definition at line 1451 of file layout.c.
Referenced by ldlm_cli_convert().
struct req_format RQF_LDLM_CP_CALLBACK
Definition at line 1464 of file layout.c.
Referenced by ldlm_callback_handler().
struct req_format RQF_LDLM_ENQUEUE
Definition at line 1441 of file layout.c.
Referenced by ldlm_cli_enqueue(), ldlm_enqueue_pack(), mdc_enqueue_pack(), mdt_intent_policy(), mgc_enqueue(), and replay_one_lock().
struct req_format RQF_LDLM_ENQUEUE_LVB
Definition at line 1446 of file layout.c.
Referenced by ldlm_cli_enqueue(), osc_enqueue_base(), and replay_one_lock().
struct req_format RQF_LDLM_GL_CALLBACK
Definition at line 1472 of file layout.c.
Referenced by ldlm_callback_handler(), and osc_ldlm_glimpse_ast().
struct req_format RQF_LDLM_GL_DESC_CALLBACK
Definition at line 1477 of file layout.c.
Referenced by qsd_common_glimpse_ast().
struct req_format RQF_LDLM_INTENT
Definition at line 1487 of file layout.c.
struct req_format RQF_LDLM_INTENT_BASIC
Definition at line 1482 of file layout.c.
Referenced by mdt_intent_policy().
struct req_format RQF_LDLM_INTENT_CREATE
Definition at line 1507 of file layout.c.
Referenced by mdt_intent_reint().
struct req_format RQF_LDLM_INTENT_GETATTR
Definition at line 1497 of file layout.c.
Referenced by mdc_intent_getattr_pack().
struct req_format RQF_LDLM_INTENT_GETXATTR
Definition at line 1517 of file layout.c.
Referenced by mdc_intent_getxattr_pack().
struct req_format RQF_LDLM_INTENT_LAYOUT
Definition at line 1492 of file layout.c.
Referenced by mdc_intent_layout_pack().
struct req_format RQF_LDLM_INTENT_OPEN
Definition at line 1502 of file layout.c.
Referenced by mdc_intent_open_pack(), mdt_intent_reint(), mdt_reconstruct_open(), and mdt_reint_open().
struct req_format RQF_LDLM_INTENT_QUOTA
Definition at line 1331 of file layout.c.
Referenced by qmt_intent_policy(), and qsd_intent_lock().
struct req_format RQF_LDLM_INTENT_UNLINK
Definition at line 1512 of file layout.c.
Referenced by mdc_intent_unlink_pack().
struct req_format RQF_LFSCK_NOTIFY
Definition at line 1680 of file layout.c.
Referenced by lfsck_async_request(), lfsck_layout_async_notify(), lfsck_layout_master_conditional_destroy(), lfsck_layout_slave_check_pairs(), and lfsck_namespace_notify_lmv_remote().
struct req_format RQF_LFSCK_QUERY
Definition at line 1684 of file layout.c.
Referenced by lfsck_async_request(), and lfsck_layout_async_query().
struct req_format RQF_LLOG_ORIGIN_CONNECT
Definition at line 1597 of file layout.c.
struct req_format RQF_LLOG_ORIGIN_HANDLE_CREATE
Definition at line 1572 of file layout.c.
Referenced by ldlm_callback_handler(), and llog_client_open().
struct req_format RQF_LLOG_ORIGIN_HANDLE_DESTROY
Definition at line 1577 of file layout.c.
Referenced by llog_client_destroy().
struct req_format RQF_LLOG_ORIGIN_HANDLE_NEXT_BLOCK
Definition at line 1582 of file layout.c.
Referenced by ldlm_callback_handler(), and llog_client_next_block().
struct req_format RQF_LLOG_ORIGIN_HANDLE_PREV_BLOCK
Definition at line 1587 of file layout.c.
Referenced by llog_client_prev_block().
struct req_format RQF_LLOG_ORIGIN_HANDLE_READ_HEADER
Definition at line 1592 of file layout.c.
Referenced by ldlm_callback_handler(), and llog_client_read_header().
struct req_format RQF_LOG_CANCEL
Definition at line 1315 of file layout.c.
struct req_format RQF_MDS_CLOSE
Definition at line 1523 of file layout.c.
Referenced by mdc_close().
struct req_format RQF_MDS_CONNECT [read]
Definition at line 170 of file lustre_req_layout.h.
Referenced by ptlrpc_connect_import().
struct req_format RQF_MDS_DISCONNECT [read]
Definition at line 171 of file lustre_req_layout.h.
Referenced by ptlrpc_disconnect_import().
struct req_format RQF_MDS_GET_INFO
Definition at line 1431 of file layout.c.
Referenced by mdc_get_info_rpc().
struct req_format RQF_MDS_GET_ROOT
Definition at line 1337 of file layout.c.
Referenced by mdc_get_root().
struct req_format RQF_MDS_GETATTR
Definition at line 1349 of file layout.c.
Referenced by mdc_get_remote_perm(), and mdc_getattr().
struct req_format RQF_MDS_GETATTR_NAME
Definition at line 1358 of file layout.c.
Referenced by mdc_getattr_name().
struct req_format RQF_MDS_GETXATTR
Definition at line 1353 of file layout.c.
Referenced by mdc_getxattr().
struct req_format RQF_MDS_HSM_ACTION
Definition at line 1538 of file layout.c.
Referenced by mdc_ioc_hsm_current_action().
struct req_format RQF_MDS_HSM_CT_REGISTER
Definition at line 1546 of file layout.c.
Referenced by mdc_ioc_hsm_ct_register().
struct req_format RQF_MDS_HSM_CT_UNREGISTER
Definition at line 1550 of file layout.c.
Referenced by mdc_ioc_hsm_ct_unregister().
struct req_format RQF_MDS_HSM_PROGRESS
Definition at line 1542 of file layout.c.
Referenced by mdc_ioc_hsm_progress().
struct req_format RQF_MDS_HSM_REQUEST
Definition at line 1563 of file layout.c.
Referenced by mdc_ioc_hsm_request().
struct req_format RQF_MDS_HSM_STATE_GET
Definition at line 1554 of file layout.c.
Referenced by mdc_ioc_hsm_state_get().
struct req_format RQF_MDS_HSM_STATE_SET
Definition at line 1559 of file layout.c.
Referenced by mdc_ioc_hsm_state_set().
struct req_format RQF_MDS_INTENT_CLOSE
Definition at line 1528 of file layout.c.
Referenced by mdc_close(), and mdt_intent_close_unpack().
struct req_format RQF_MDS_QUOTACTL
Definition at line 1319 of file layout.c.
Referenced by mdc_quotactl().
struct req_format RQF_MDS_READPAGE
Definition at line 1533 of file layout.c.
Referenced by mdc_getpage().
struct req_format RQF_MDS_REINT
Definition at line 1363 of file layout.c.
struct req_format RQF_MDS_REINT_CREATE
Definition at line 1367 of file layout.c.
Referenced by mdt_reint().
struct req_format RQF_MDS_REINT_CREATE_RMT_ACL
Definition at line 1372 of file layout.c.
Referenced by mdc_create(), and mdt_create_unpack().
struct req_format RQF_MDS_REINT_CREATE_SLAVE
Definition at line 1377 of file layout.c.
struct req_format RQF_MDS_REINT_CREATE_SYM
Definition at line 1382 of file layout.c.
Referenced by mdt_create_unpack().
struct req_format RQF_MDS_REINT_LINK
Definition at line 1397 of file layout.c.
Referenced by mdc_link(), and mdt_reint().
struct req_format RQF_MDS_REINT_MIGRATE
Definition at line 1407 of file layout.c.
Referenced by mdc_rename(), and mdt_rename_unpack().
struct req_format RQF_MDS_REINT_OPEN
Definition at line 1387 of file layout.c.
Referenced by mdt_reint().
struct req_format RQF_MDS_REINT_RENAME
Definition at line 1402 of file layout.c.
Referenced by mdc_rename(), and mdt_reint().
struct req_format RQF_MDS_REINT_SETATTR
Definition at line 1412 of file layout.c.
Referenced by mdc_setattr(), and mdt_reint().
struct req_format RQF_MDS_REINT_SETXATTR
Definition at line 1417 of file layout.c.
Referenced by mdc_setxattr(), and mdt_reint().
struct req_format RQF_MDS_REINT_UNLINK
Definition at line 1392 of file layout.c.
Referenced by mdc_unlink(), and mdt_reint().
struct req_format RQF_MDS_STATFS
Definition at line 1341 of file layout.c.
Referenced by mdc_statfs().
struct req_format RQF_MDS_SWAP_LAYOUTS
Definition at line 1567 of file layout.c.
Referenced by mdc_ioc_swap_layouts().
struct req_format RQF_MDS_SYNC
Definition at line 1345 of file layout.c.
Referenced by mdc_fsync().
struct req_format RQF_MGS_CONFIG_READ
Definition at line 1298 of file layout.c.
Referenced by mgc_process_recover_log().
struct req_format RQF_MGS_SET_INFO
Definition at line 1293 of file layout.c.
Referenced by mgc_set_mgs_param().
struct req_format RQF_MGS_TARGET_REG
Definition at line 1288 of file layout.c.
Referenced by mgc_target_register().
struct req_format RQF_OBD_IDX_READ
Definition at line 1279 of file layout.c.
Referenced by osp_it_fetch(), qsd_fetch_index(), and tgt_obd_idx_read().
struct req_format RQF_OBD_PING
Definition at line 1270 of file layout.c.
Referenced by ptlrpc_prep_ping(), and signal_completed_replay().
struct req_format RQF_OBD_SET_INFO
Definition at line 1274 of file layout.c.
Referenced by do_set_info_async(), ldlm_handle_setinfo(), osc_set_info_async(), and osp_obd_set_info_async().
struct req_format RQF_OST_BRW_READ
Definition at line 1638 of file layout.c.
Referenced by osc_brw_prep_request().
struct req_format RQF_OST_BRW_WRITE
Definition at line 1642 of file layout.c.
Referenced by osc_brw_prep_request().
struct req_format RQF_OST_CONNECT
Definition at line 1605 of file layout.c.
struct req_format RQF_OST_CREATE
Definition at line 1622 of file layout.c.
Referenced by osc_create(), osp_precreate_cleanup_orphans(), and osp_precreate_send().
struct req_format RQF_OST_DESTROY
Definition at line 1634 of file layout.c.
Referenced by osc_destroy(), osp_sync_new_unlink64_job(), and osp_sync_new_unlink_job().
struct req_format RQF_OST_DISCONNECT
Definition at line 1610 of file layout.c.
struct req_format RQF_OST_GET_INFO
Definition at line 1655 of file layout.c.
struct req_format RQF_OST_GET_INFO_FIEMAP
Definition at line 1675 of file layout.c.
Referenced by ofd_get_info_hdl(), and osc_object_fiemap().
struct req_format RQF_OST_GET_INFO_LAST_FID
Definition at line 1665 of file layout.c.
Referenced by ofd_get_info_hdl(), and osp_get_lastfid_from_ost().
struct req_format RQF_OST_GET_INFO_LAST_ID
Definition at line 1660 of file layout.c.
Referenced by ofd_get_info_hdl().
struct req_format RQF_OST_GETATTR
Definition at line 1614 of file layout.c.
Referenced by osc_getattr(), and osc_io_data_version_start().
struct req_format RQF_OST_LADVISE
Definition at line 1688 of file layout.c.
Referenced by osc_ladvise_base().
struct req_format RQF_OST_PUNCH
Definition at line 1626 of file layout.c.
Referenced by osc_punch_base(), and osp_object_truncate().
struct req_format RQF_OST_QUOTACTL
Definition at line 1323 of file layout.c.
Referenced by osc_quotactl().
struct req_format RQF_OST_SET_GRANT_INFO
Definition at line 1650 of file layout.c.
Referenced by ofd_set_info_hdl(), and osc_set_info_async().
struct req_format RQF_OST_SET_INFO_LAST_FID
Definition at line 1670 of file layout.c.
struct req_format RQF_OST_SETATTR
Definition at line 1618 of file layout.c.
Referenced by osc_setattr(), osc_setattr_async(), and osp_sync_new_setattr_job().
struct req_format RQF_OST_STATFS
Definition at line 1646 of file layout.c.
Referenced by osc_statfs(), osc_statfs_async(), osp_obd_statfs(), and osp_statfs_update().
struct req_format RQF_OST_SYNC
Definition at line 1630 of file layout.c.
Referenced by osc_sync_base().
struct req_format RQF_OUT_UPDATE
Definition at line 1436 of file layout.c.
Referenced by osp_prep_update_req(), and out_handle().
struct req_format RQF_QUOTA_DQACQ
Definition at line 1327 of file layout.c.
Referenced by qsd_send_dqacq().
struct req_format RQF_SEC_CTX
Definition at line 1284 of file layout.c.
Referenced by gss_do_ctx_fini_rpc(), and gss_do_ctx_init_rpc().
struct req_format RQF_SEQ_QUERY
Definition at line 1303 of file layout.c.
Referenced by seq_client_rpc().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.