Lustre: Setup and teardown
Setup and teardown
[Echo Client]
Init and fini functions for echo client.
Functions
static int echo_site_init (const struct lu_env *env, struct echo_device *ed)
static void echo_site_fini (const struct lu_env *env, struct echo_device *ed)
static void * echo_thread_key_init (const struct lu_context *ctx, struct lu_context_key *key)
static void echo_thread_key_fini (const struct lu_context *ctx, struct lu_context_key *key, void *data)
static void echo_thread_key_exit (const struct lu_context *ctx, struct lu_context_key *key, void *data)
static void * echo_session_key_init (const struct lu_context *ctx, struct lu_context_key *key)
static void echo_session_key_fini (const struct lu_context *ctx, struct lu_context_key *key, void *data)
static void echo_session_key_exit (const struct lu_context *ctx, struct lu_context_key *key, void *data)
LU_TYPE_INIT_FINI (echo,&echo_thread_key,&echo_session_key)
static struct lu_device * echo_device_alloc (const struct lu_env *env, struct lu_device_type *t, struct lustre_cfg *cfg)
static int echo_device_init (const struct lu_env *env, struct lu_device *d, const char *name, struct lu_device *next)
static struct lu_device * echo_device_fini (const struct lu_env *env, struct lu_device *d)
static void echo_lock_release (const struct lu_env *env, struct echo_lock *ecl, int still_used)
static struct lu_device * echo_device_free (const struct lu_env *env, struct lu_device *d)
Variables
static struct lu_context_key echo_session_key
static struct
lu_device_type_operations echo_device_type_ops
static struct lu_device_type echo_device_type
Detailed Description
Init and fini functions for echo client.
Function Documentation
static struct lu_device* echo_device_alloc (const struct lu_env * env, struct lu_device_type * t, struct lustre_cfg * cfg) [static, read]
Definition at line 818 of file echo_client.c.
References cl_device::cd_lu_dev, CERROR, cl_device_fini(), cl_device_init(), class_name2obd(), cleanup(), obd_device::echo_client, echo_client_cleanup(), echo_client_setup(), echo_device_lu_ops, echo_site_fini(), echo_site_init(), echo_device::ed_cl, echo_device::ed_ec, echo_device::ed_next, echo_device::ed_next_ismd, echo_device::ed_site, ENTRY, GOTO, LASSERT, lu_device::ld_ops, lu_device::ld_site, lu_device::ld_type, lu_device_type::ldt_name, lu_device_type::ldt_ops, lu_device_type_operations::ldto_device_init, list_for_each_entry, lu_site::ls_ld_linkage, lu_site::ls_ld_lock, lu2md_dev(), lu_device_is_cl(), lu_site2seq(), lustre_cfg_string(), LUSTRE_MDT_NAME, LUSTRE_OSC_NAME, LUSTRE_OST_NAME, md_device::md_lu_dev, OBD_ALLOC_PTR, OBD_FREE_PTR, obd_device::obd_lu_dev, obd_device::obd_name, obd_device::obd_type, RETURN, obd_type::typ_name, and obd_device::u.
static struct lu_device* echo_device_fini (const struct lu_env * env, struct lu_device * d) [static, read]
Definition at line 997 of file echo_client.c.
References cl2echo_dev(), echo_device::ed_next, echo_device::ed_next_ismd, lu_device::ld_type, lu_device_type::ldt_ops, lu_device_type_operations::ldto_device_fini, and lu2cl_dev().
static struct lu_device* echo_device_free (const struct lu_env * env, struct lu_device * d) [static, read]
Definition at line 1017 of file echo_client.c.
References CDEBUG, CERROR, cfs_time_seconds(), cl2echo_dev(), cl_device_fini(), D_INFO, echo_client_obd::ec_lock, echo_client_obd::ec_locks, echo_client_obd::ec_objects, echo_client_cleanup(), echo_site_fini(), echo_device::ed_cl, echo_device::ed_ec, echo_device::ed_next, echo_device::ed_next_ismd, echo_device::ed_site, echo_object::eo_deleted, LASSERT, lu_device::ld_obd, lu_device::ld_site, lu_device::ld_type, lu_device_type::ldt_ops, lu_device_type_operations::ldto_device_free, list_empty(), list_for_each_entry, lu2cl_dev(), lu_site_purge(), and OBD_FREE_PTR.
static int echo_device_init (const struct lu_env * env, struct lu_device * d, const char * name, struct lu_device * next) [static]
Definition at line 990 of file echo_client.c.
References LBUG.
static void echo_lock_release (const struct lu_env * env, struct echo_lock * ecl, int still_used) [static]
Definition at line 1008 of file echo_client.c.
References cl_lock_release(), and echo_lock2cl().
Referenced by cl_echo_cancel0().
static void echo_session_key_exit (const struct lu_context * ctx, struct lu_context_key * key, void * data) [static]
Definition at line 672 of file echo_client.c.
static void echo_session_key_fini (const struct lu_context * ctx, struct lu_context_key * key, void * data) [static]
Definition at line 665 of file echo_client.c.
References echo_session_kmem, and OBD_SLAB_FREE_PTR.
static void* echo_session_key_init (const struct lu_context * ctx, struct lu_context_key * key) [static]
Definition at line 654 of file echo_client.c.
References echo_session_kmem, and OBD_SLAB_ALLOC_PTR_GFP.
static void echo_site_fini (const struct lu_env * env, struct echo_device * ed) [static]
Definition at line 615 of file echo_client.c.
References echo_device::ed_next_ismd, echo_device::ed_site, and lu_site_fini().
Referenced by echo_device_alloc(), and echo_device_free().
static int echo_site_init (const struct lu_env * env, struct echo_device * ed) [static]
Definition at line 593 of file echo_client.c.
References CERROR, cl_site_fini(), cl_site_init(), cl_site::cs_lu, echo_device::ed_cl, echo_device::ed_site, echo_device::ed_site_myself, and lu_site_init_finish().
Referenced by echo_device_alloc().
static void echo_thread_key_exit (const struct lu_context * ctx, struct lu_context_key * key, void * data) [static]
Definition at line 642 of file echo_client.c.
static void echo_thread_key_fini (const struct lu_context * ctx, struct lu_context_key * key, void * data) [static]
Definition at line 635 of file echo_client.c.
References echo_thread_kmem, and OBD_SLAB_FREE_PTR.
static void* echo_thread_key_init (const struct lu_context * ctx, struct lu_context_key * key) [static]
Definition at line 624 of file echo_client.c.
References echo_thread_kmem, and OBD_SLAB_ALLOC_PTR_GFP.
LU_TYPE_INIT_FINI (echo , & echo_thread_key, & echo_session_key)
Variable Documentation
struct lu_device_type echo_device_type [static]
Initial value:
 {
        .ldt_tags     = LU_DEVICE_CL,
        .ldt_name     = LUSTRE_ECHO_CLIENT_NAME,
        .ldt_ops      = &echo_device_type_ops,
        .ldt_ctx_tags = LCT_CL_THREAD | LCT_MD_THREAD | LCT_DT_THREAD,
}
Definition at line 1092 of file echo_client.c.
Referenced by cl_echo_enqueue0(), and obdecho_init().
struct lu_device_type_operations echo_device_type_ops [static]
Initial value:
 {
        .ldto_init = echo_type_init,
        .ldto_fini = echo_type_fini,
        .ldto_start = echo_type_start,
        .ldto_stop  = echo_type_stop,
        .ldto_device_alloc = echo_device_alloc,
        .ldto_device_free  = echo_device_free,
        .ldto_device_init  = echo_device_init,
        .ldto_device_fini  = echo_device_fini
}
Definition at line 1079 of file echo_client.c.
struct lu_context_key echo_session_key [static]
Initial value:
 {
        .lct_tags = LCT_SESSION,
        .lct_init = echo_session_key_init,
        .lct_fini = echo_session_key_fini,
        .lct_exit = echo_session_key_exit
}
Definition at line 677 of file echo_client.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.