Lustre: Various LDLM pool related functions
Various LDLM pool related functions
[Lustre Distributed Lock Manager]
There are not used outside of ldlm.
Functions
int ldlm_pools_recalc (enum ldlm_side client)
int ldlm_pools_init (void)
void ldlm_pools_fini (void)
int ldlm_pool_init (struct ldlm_pool *pl, struct ldlm_namespace *ns, int idx, enum ldlm_side client)
int ldlm_pool_shrink (struct ldlm_pool *pl, int nr, gfp_t gfp_mask)
void ldlm_pool_fini (struct ldlm_pool *pl)
int ldlm_pool_setup (struct ldlm_pool *pl, int limit)
int ldlm_pool_recalc (struct ldlm_pool *pl)
__u32 ldlm_pool_get_lvf (struct ldlm_pool *pl)
__u64 ldlm_pool_get_slv (struct ldlm_pool *pl)
__u64 ldlm_pool_get_clv (struct ldlm_pool *pl)
__u32 ldlm_pool_get_limit (struct ldlm_pool *pl)
void ldlm_pool_set_slv (struct ldlm_pool *pl, __u64 slv)
void ldlm_pool_set_clv (struct ldlm_pool *pl, __u64 clv)
void ldlm_pool_set_limit (struct ldlm_pool *pl, __u32 limit)
void ldlm_pool_add (struct ldlm_pool *pl, struct ldlm_lock *lock)
void ldlm_pool_del (struct ldlm_pool *pl, struct ldlm_lock *lock)
Detailed Description
There are not used outside of ldlm.
Function Documentation
void ldlm_pool_add (struct ldlm_pool * pl, struct ldlm_lock * lock)
Definition at line 1536 of file ldlm_pool.c.
Referenced by ldlm_grant_lock().
void ldlm_pool_del (struct ldlm_pool * pl, struct ldlm_lock * lock)
Definition at line 1541 of file ldlm_pool.c.
Referenced by ldlm_lock_cancel(), ldlm_lock_convert(), and ldlm_lock_downgrade().
void ldlm_pool_fini (struct ldlm_pool * pl)
Definition at line 1531 of file ldlm_pool.c.
Referenced by ldlm_namespace_free_post().
__u64 ldlm_pool_get_clv (struct ldlm_pool * pl)
Definition at line 1556 of file ldlm_pool.c.
__u32 ldlm_pool_get_limit (struct ldlm_pool * pl)
Definition at line 1566 of file ldlm_pool.c.
__u32 ldlm_pool_get_lvf (struct ldlm_pool * pl)
Definition at line 1576 of file ldlm_pool.c.
Referenced by ldlm_cancel_lrur_policy().
__u64 ldlm_pool_get_slv (struct ldlm_pool * pl)
Definition at line 1546 of file ldlm_pool.c.
Referenced by ldlm_cancel_lrur_policy().
int ldlm_pool_init (struct ldlm_pool * pl, struct ldlm_namespace * ns, int idx, enum ldlm_side client)
Definition at line 1525 of file ldlm_pool.c.
Referenced by ldlm_namespace_new().
int ldlm_pool_recalc (struct ldlm_pool * pl)
Definition at line 1514 of file ldlm_pool.c.
void ldlm_pool_set_clv (struct ldlm_pool * pl, __u64 clv)
Definition at line 1561 of file ldlm_pool.c.
Referenced by ldlm_cancel_lrur_policy().
void ldlm_pool_set_limit (struct ldlm_pool * pl, __u32 limit)
Definition at line 1571 of file ldlm_pool.c.
void ldlm_pool_set_slv (struct ldlm_pool * pl, __u64 slv)
Definition at line 1551 of file ldlm_pool.c.
int ldlm_pool_setup (struct ldlm_pool * pl, int limit)
Definition at line 1509 of file ldlm_pool.c.
int ldlm_pool_shrink (struct ldlm_pool * pl, int nr, gfp_t gfp_mask)
Definition at line 1519 of file ldlm_pool.c.
void ldlm_pools_fini (void)
Definition at line 1586 of file ldlm_pool.c.
Referenced by ldlm_cleanup().
int ldlm_pools_init (void)
Definition at line 1581 of file ldlm_pool.c.
Referenced by ldlm_setup().
int ldlm_pools_recalc (enum ldlm_side client)
Definition at line 1591 of file ldlm_pool.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.