Lustre: lu_device operations
lu_device operations
[Echo Client]
Operations for echo lu device.
Functions
static struct lu_object * echo_object_alloc (const struct lu_env *env, const struct lu_object_header *hdr, struct lu_device *dev)
Variables
static struct lu_device_operations echo_device_lu_ops
Detailed Description
Operations for echo lu device.
Function Documentation
static struct lu_object* echo_object_alloc (const struct lu_env * env, const struct lu_object_header * hdr, struct lu_device * dev) [static, read]
Definition at line 554 of file echo_client.c.
References cfs_size_round(), cl_object_header_init(), cl_object::co_lu, cl_object::co_ops, cl_object_header::coh_lu, cl_object_header::coh_page_bufsize, echo_cl_obj_ops, echo_lu_obj_ops, echo_obj2cl(), echo_object_kmem, ENTRY, echo_object::eo_cl, echo_object::eo_hdr, LASSERT, lu_object::lo_ops, lu_object_add_top(), lu_object_init(), OBD_SLAB_ALLOC_PTR_GFP, and RETURN.
Variable Documentation
struct lu_device_operations echo_device_lu_ops [static]
Initial value:
 {
        .ldo_object_alloc   = echo_object_alloc,
}
Definition at line 581 of file echo_client.c.
Referenced by echo_device_alloc().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.