Lustre: lu
lu
lu_* data-types represent server-side entities shared by data and meta-data stacks.
Data Structures
struct lu_device_operations
Operations common for data and meta-data devices.
struct lu_object_conf
Object configuration, describing particulars of object being created.
struct lu_object_operations
Operations specific for particular lu_object.
struct lu_device
Device: a layer in the server side abstraction stacking.
struct lu_device_type
Type of device.
struct lu_device_type_operations
Operations on a device type.
struct lu_attr
Common object attributes.
struct lu_object
Layer in the layered object.
struct lu_object_header
"Compound" object, consisting of multiple layers.
struct lu_site_bkt_data
struct lu_site
lu_site is a "compartment" within which objects are unique, and LRU discipline is maintained.
struct lu_rdpg
input params, should be filled out by mdt
struct lu_context
lu_context.
struct lu_context_key
Key.
struct lu_env
Environment.
struct lu_name
Common name structure to be passed around for various name related methods.
struct lu_buf
Common buffer structure to be passed around for various xattr_{s,g}et() methods.
struct lu_rdbuf
struct lu_kmem_descr
Defines
#define DNAME "%.*s"
#define PNAME(ln)
#define DLUBUF "(%p %zu)"
#define PLUBUF(buf) (buf)->lb_buf, (buf)->lb_len
Typedefs
typedef int(* lu_printer_t)(const struct lu_env *env, void *cookie, const char *format,...) __attribute__((format(printf
Type of "printer" function used by lu_object_operations::loo_object_print() method.
Enumerations
enum loc_flags_t { LOC_F_NEW = 0x00000001, LOC_F_NOWAIT = 0x00000002 }
For lu_object_conf flags.
enum lu_device_tag { LU_DEVICE_MD = (1 << 0), LU_DEVICE_DT = (1 << 1), LU_DEVICE_CL = (1 << 2) }
Tag bits for device type.
enum la_valid {
LA_ATIME = 1 << 0, LA_MTIME = 1 << 1, LA_CTIME = 1 << 2, LA_SIZE = 1 << 3,
LA_MODE = 1 << 4, LA_UID = 1 << 5, LA_GID = 1 << 6, LA_BLOCKS = 1 << 7,
LA_TYPE = 1 << 8, LA_FLAGS = 1 << 9, LA_NLINK = 1 << 10, LA_RDEV = 1 << 11,
LA_BLKSIZE = 1 << 12, LA_KILL_SUID = 1 << 13, LA_KILL_SGID = 1 << 14
}
Bit-mask of valid attributes.
enum lu_object_header_flags { LU_OBJECT_HEARD_BANSHEE = 0, LU_OBJECT_UNHASHED = 1 }
enum lu_object_header_attr { LOHA_EXISTS = 1 << 0, LOHA_REMOTE = 1 << 1, LOHA_FT_START = 001 << 12, LOHA_FT_END = 017 << 12 }
enum {
LU_SS_CREATED = 0, LU_SS_CACHE_HIT, LU_SS_CACHE_MISS, LU_SS_CACHE_RACE,
LU_SS_CACHE_DEATH_RACE, LU_SS_LRU_PURGED, LU_SS_LRU_LEN, LU_SS_LAST_STAT
}
Functions
static int lu_device_is_md (const struct lu_device *d)
static struct lu_site_bkt_data * lu_site_bkt_from_fid (struct lu_site *site, struct lu_fid *fid)
static struct seq_server_site * lu_site2seq (const struct lu_site *s)
int lu_site_stats_seq_print (const struct lu_site *s, struct seq_file *m)
Output site statistical counters into a buffer.
static bool lu_name_is_valid_2 (const char *name, size_t name_len)
Validate names (path components).
static bool lu_name_is_valid (const struct lu_name *ln)
int lu_global_init (void)
One-time initializers, called at obdclass module initialization, not exported.
void lu_global_fini (void)
Dual to lu_global_init().
int lu_kmem_init (struct lu_kmem_descr *caches)
Helper function to initialize a number of kmem slab caches at once.
void lu_kmem_fini (struct lu_kmem_descr *caches)
Helper function to finalize a number of kmem slab cached at once.
void lu_object_assign_fid (const struct lu_env *env, struct lu_object *o, const struct lu_fid *fid)
Temporary solution to be able to assign fid in ->do_create() till we have fully-functional OST fids.
struct lu_object * lu_object_anon (const struct lu_env *env, struct lu_device *dev, const struct lu_object_conf *conf)
allocates object with 0 (non-assiged) fid XXX: temporary solution to be able to assign fid in ->do_create() till we have fully-functional OST fids
void lu_buf_free (struct lu_buf *buf)
void lu_buf_alloc (struct lu_buf *buf, size_t size)
void lu_buf_realloc (struct lu_buf *buf, size_t size)
int lu_buf_check_and_grow (struct lu_buf *buf, size_t len)
Increase the size of the buf.
struct lu_buf * lu_buf_check_and_alloc (struct lu_buf *buf, size_t len)
static bool lu_device_is_cl (const struct lu_device *d)
static bool lu_object_is_cl (const struct lu_object *o)
Variables
struct lu_buf LU_BUF_NULL
null buffer
__u32 lu_context_tags_default
lu_ctx_tags/lu_ses_tags will be updated if there are new types of obd being added.
__u32 lu_session_tags_default
helpers
Helpers.
enum lu_xattr_flags { LU_XATTR_REPLACE = (1 << 0), LU_XATTR_CREATE = (1 << 1) }
static struct lu_object * lu_object_top (struct lu_object_header *h)
First (topmost) sub-object of given compound object.
static struct lu_object * lu_object_next (const struct lu_object *o)
Next sub-object in the layering.
static struct lu_fid * lu_object_fid (const struct lu_object *o)
Pointer to the fid of this object.
static const struct
lu_device_operations * lu_object_ops (const struct lu_object *o)
return device operations vector for this object
struct lu_object * lu_object_locate (struct lu_object_header *h, const struct lu_device_type *dtype)
Given a compound object, find its slice, corresponding to the device type dtype.
int lu_cdebug_printer (const struct lu_env *env, void *cookie, const char *format,...)
Printer function emitting messages through libcfs_debug_msg().
void lu_object_print (const struct lu_env *env, void *cookie, lu_printer_t printer, const struct lu_object *o)
Print human readable representation of the o to the printer.
void lu_object_header_print (const struct lu_env *env, void *cookie, lu_printer_t printer, const struct lu_object_header *hdr)
Print object header.
int lu_object_invariant (const struct lu_object *o)
Check object consistency.
static int lu_object_assert_exists (const struct lu_object *o)
static int lu_object_assert_not_exists (const struct lu_object *o)
static __u32 lu_object_attr (const struct lu_object *o)
Attr of this object.
static void lu_object_ref_add (struct lu_object *o, const char *scope, const void *source)
static void lu_object_ref_add_at (struct lu_object *o, struct lu_ref_link *link, const char *scope, const void *source)
static void lu_object_ref_del (struct lu_object *o, const char *scope, const void *source)
static void lu_object_ref_del_at (struct lu_object *o, struct lu_ref_link *link, const char *scope, const void *source)
#define LU_OBJECT_DEBUG(mask, env, object, format,...)
Print object description followed by a user-supplied message.
#define LU_OBJECT_HEADER(mask, env, object, format,...)
Print short object description followed by a user-supplied message.
#define lu_object_exists(o) ((o)->lo_header->loh_attr & LOHA_EXISTS)
Check whether object exists, no matter on local or remote storage.
#define lu_object_remote(o) unlikely((o)->lo_header->loh_attr & LOHA_REMOTE)
Check whether object on the remote storage.
lu_context
enum lu_context_state { LCS_INITIALIZED = 1, LCS_ENTERED, LCS_LEFT, LCS_FINALIZED }
For lu_context health-checks.
enum lu_context_tag {
LCT_MD_THREAD = 1 << 0, LCT_DT_THREAD = 1 << 1, LCT_TX_HANDLE = 1 << 2, LCT_CL_THREAD = 1 << 3,
LCT_SESSION = 1 << 4, LCT_OSP_THREAD = 1 << 5, LCT_MG_THREAD = 1 << 6, LCT_LOCAL = 1 << 7,
LCT_SERVER_SESSION = 1 << 8, LCT_HAS_EXIT = 1 << 28, LCT_NOREF = 1 << 29, LCT_QUIESCENT = 1 << 30,
LCT_REMEMBER = 1 << 31, LCT_SHRINKER = LCT_MD_THREAD|LCT_DT_THREAD|LCT_CL_THREAD|LCT_NOREF
}
lu_context_key interface.
int lu_context_key_register (struct lu_context_key *key)
Register new key.
void lu_context_key_degister (struct lu_context_key *key)
Deregister key.
void * lu_context_key_get (const struct lu_context *ctx, const struct lu_context_key *key)
Return value associated with key key in context ctx.
void lu_context_key_quiesce (struct lu_context_key *key)
Destroy key in all remembered contexts.
void lu_context_key_revive (struct lu_context_key *key)
int lu_context_init (struct lu_context *ctx, __u32 tags)
Initialize context data-structure.
void lu_context_fini (struct lu_context *ctx)
Finalize context data-structure.
void lu_context_enter (struct lu_context *ctx)
Called before entering context.
void lu_context_exit (struct lu_context *ctx)
Called after exiting from ctx.
int lu_context_refill (struct lu_context *ctx)
Allocate for context all missing keys that were registered after context creation.
int lu_context_key_register_many (struct lu_context_key *k,...)
Register a number of keys.
void lu_context_key_degister_many (struct lu_context_key *k,...)
De-register a number of keys.
void lu_context_key_revive_many (struct lu_context_key *k,...)
Revive a number of keys.
void lu_context_key_quiesce_many (struct lu_context_key *k,...)
Quiescent a number of keys.
void lu_context_tags_update (__u32 tags)
void lu_context_tags_clear (__u32 tags)
void lu_session_tags_update (__u32 tags)
void lu_session_tags_clear (__u32 tags)
int lu_env_init (struct lu_env *env, __u32 tags)
void lu_env_fini (struct lu_env *env)
int lu_env_refill (struct lu_env *env)
int lu_env_refill_by_tags (struct lu_env *env, __u32 ctags, __u32 stags)
Currently, this API will only be used by echo client.
#define LU_KEY_INIT(mod, type)
#define LU_KEY_FINI(mod, type)
#define LU_KEY_INIT_FINI(mod, type)
#define LU_CONTEXT_KEY_DEFINE(mod, tags)
#define LU_CONTEXT_KEY_INIT(key)
#define LU_KEY_INIT_GENERIC(mod)
#define LU_TYPE_INIT(mod,...)
#define LU_TYPE_FINI(mod,...)
#define LU_TYPE_START(mod,...)
#define LU_TYPE_STOP(mod,...)
#define LU_TYPE_INIT_FINI(mod,...)
ctors
Constructors/destructors.
int lu_site_init (struct lu_site *s, struct lu_device *d)
Initialize site s, with d as the top level device.
void lu_site_fini (struct lu_site *s)
Finalize s and release its resources.
int lu_site_init_finish (struct lu_site *s)
Called when initialization of stack for this site is completed.
void lu_stack_fini (const struct lu_env *env, struct lu_device *top)
Finalize and free devices in the device stack.
void lu_device_get (struct lu_device *d)
Acquire additional reference on device d.
void lu_device_put (struct lu_device *d)
Release reference on device d.
int lu_device_init (struct lu_device *d, struct lu_device_type *t)
Initialize device d of type t.
void lu_device_fini (struct lu_device *d)
Finalize device d.
int lu_object_header_init (struct lu_object_header *h)
Initialize compound object.
void lu_object_header_fini (struct lu_object_header *h)
Finalize compound object.
int lu_object_init (struct lu_object *o, struct lu_object_header *h, struct lu_device *d)
Initialize object o that is part of compound object h and was created by device d.
void lu_object_fini (struct lu_object *o)
Finalize object and release its resources.
void lu_object_add_top (struct lu_object_header *h, struct lu_object *o)
Add object o as first layer of compound object h.
void lu_object_add (struct lu_object *before, struct lu_object *o)
Add object o as a layer of compound object, going after before.
void lu_dev_add_linkage (struct lu_site *s, struct lu_device *d)
void lu_dev_del_linkage (struct lu_site *s, struct lu_device *d)
int lu_device_type_init (struct lu_device_type *ldt)
Helpers to initialize and finalize device types.
void lu_device_type_fini (struct lu_device_type *ldt)
caching
Caching and reference counting.
static void lu_object_get (struct lu_object *o)
Acquire additional reference to the given object.
static int lu_object_is_dying (const struct lu_object_header *h)
Return true of object will not be cached after last reference to it is released.
void lu_object_put (const struct lu_env *env, struct lu_object *o)
Decrease reference counter on object.
void lu_object_put_nocache (const struct lu_env *env, struct lu_object *o)
Put object and don't keep in cache.
void lu_object_unhash (const struct lu_env *env, struct lu_object *o)
Kill the object and take it out of LRU cache.
int lu_site_purge (const struct lu_env *env, struct lu_site *s, int nr)
Free nr objects from the cold end of the site LRU list.
void lu_site_print (const struct lu_env *env, struct lu_site *s, void *cookie, lu_printer_t printer)
Print all objects in s.
struct lu_object * lu_object_find (const struct lu_env *env, struct lu_device *dev, const struct lu_fid *f, const struct lu_object_conf *conf)
Search cache for an object with the fid f.
struct lu_object * lu_object_find_at (const struct lu_env *env, struct lu_device *dev, const struct lu_fid *f, const struct lu_object_conf *conf)
Much like lu_object_find(), but top level device of object is specifically dev rather than top level device of the site.
struct lu_object * lu_object_find_slice (const struct lu_env *env, struct lu_device *dev, const struct lu_fid *f, const struct lu_object_conf *conf)
Find object with given fid, and return its slice belonging to given device.
Detailed Description
lu_* data-types represent server-side entities shared by data and meta-data stacks.
Design goals:
support for layering.
Server side object is split into layers, one per device in the corresponding device stack. Individual layer is represented by struct lu_object. Compound layered object --- by struct lu_object_header. Most interface functions take lu_object as an argument and operate on the whole compound object. This decision was made due to the following reasons:
it's envisaged that lu_object will be used much more often than lu_object_header;
we want lower (non-top) layers to be able to initiate operations on the whole object.
Generic code supports layering more complex than simple stacking, e.g., it is possible that at some layer object "spawns" multiple sub-objects on the lower layer.
fid-based identification.
Compound object is uniquely identified by its fid. Objects are indexed by their fids (hash table is used for index).
caching and life-cycle management.
Object's life-time is controlled by reference counting. When reference count drops to 0, object is returned to cache. Cached objects still retain their identity (i.e., fid), and can be recovered from cache.
Objects are kept in the global LRU list, and lu_site_purge() function can be used to reclaim given number of unused objects from the tail of the LRU.
avoiding recursion.
Generic code tries to replace recursion through layers by iterations where possible. Additionally to the end of reducing stack consumption, data, when practically possible, are allocated through lu_context_key interface rather than on stack.
Define Documentation
#define DLUBUF "(%p %zu)"
Definition at line 1339 of file lu_object.h.
#define DNAME "%.*s"
Definition at line 1325 of file lu_object.h.
Referenced by mdd_update_linkea_internal(), mdt_getattr_name_lock(), mdt_md_create(), mdt_reint_link(), mdt_reint_migrate_internal(), mdt_reint_open(), mdt_reint_rename_internal(), and mdt_reint_unlink().
#define LU_CONTEXT_KEY_DEFINE (mod, tags)
Value:
struct lu_context_key mod##_thread_key = {      \
                .lct_tags = tags,                       \
                .lct_init = mod##_key_init,             \
                .lct_fini = mod##_key_fini              \
        }
Definition at line 1165 of file lu_object.h.
#define LU_CONTEXT_KEY_INIT (key)
Value:
do {                                                    \
        (key)->lct_owner = THIS_MODULE;                 \
} while (0)
Definition at line 1172 of file lu_object.h.
Referenced by cl_global_init(), dt_global_init(), fid_server_mod_init(), fld_server_mod_init(), lu_global_init(), lu_ucred_global_init(), and osd_type_init().
#define LU_KEY_FINI (mod, type)
Value:
static void mod##_key_fini(const struct lu_context *ctx,            \
                                    struct lu_context_key *key, void* data) \
        {                                                                   \
                type *info = data;                                          \
                                                                            \
                OBD_FREE_PTR(info);                                         \
        }                                                                   \
        struct __##mod##__dummy_fini {;}
Definition at line 1151 of file lu_object.h.
#define LU_KEY_INIT (mod, type)
Value:
static void* mod##_key_init(const struct lu_context *ctx, \
                                    struct lu_context_key *key)   \
        {                                                         \
                type *value;                                      \
                                                                  \
                CLASSERT(PAGE_CACHE_SIZE >= sizeof (*value));       \
                                                                  \
                OBD_ALLOC_PTR(value);                             \
                if (value == NULL)                                \
                        value = ERR_PTR(-ENOMEM);                 \
                                                                  \
                return value;                                     \
        }                                                         \
        struct __##mod##__dummy_init {;}
Definition at line 1135 of file lu_object.h.
#define LU_KEY_INIT_FINI (mod, type)
Value:
LU_KEY_INIT(mod,type);        \
        LU_KEY_FINI(mod,type)
Definition at line 1161 of file lu_object.h.
#define LU_KEY_INIT_GENERIC (mod)
Value:
static void mod##_key_init_generic(struct lu_context_key *k, ...) \
        {                                                               \
                struct lu_context_key *key = k;                         \
                va_list args;                                           \
                                                                        \
                va_start(args, k);                                      \
                do {                                                    \
                        LU_CONTEXT_KEY_INIT(key);                       \
                        key = va_arg(args, struct lu_context_key *);    \
                } while (key != NULL);                                  \
                va_end(args);                                           \
        }
Definition at line 1190 of file lu_object.h.
#define LU_OBJECT_DEBUG (mask, env, object, format, ...)
Value:
do {                                                                      \
        if (cfs_cdebug_show(mask, DEBUG_SUBSYSTEM)) {                     \
                LIBCFS_DEBUG_MSG_DATA_DECL(msgdata, mask, NULL);          \
                lu_object_print(env, &msgdata, lu_cdebug_printer, object);\
                CDEBUG(mask, format "\n", ## __VA_ARGS__);                \
        }                                                                 \
} while (0)
Print object description followed by a user-supplied message.
Definition at line 800 of file lu_object.h.
Referenced by lov_init_sub(), mdt_cross_open(), mdt_getattr_name_lock(), mdt_hsm_release(), and osd_object_find().
#define lu_object_exists (o) ((o)->lo_header->loh_attr & LOHA_EXISTS)
Check whether object exists, no matter on local or remote storage.
Note: LOHA_EXISTS will be set once some one created the object, and it does not needs to be committed to storage.
Definition at line 840 of file lu_object.h.
Referenced by dt_object_exists(), lu_object_assert_exists(), lu_object_assert_not_exists(), lu_object_attr(), lu_object_put(), mdd_dot_lustre_setup(), mdd_lpf_setup(), mdd_obf_setup(), mdd_object_exists(), mdd_object_start(), mdt_object_exists(), ofd_object_exists(), orph_index_init(), osd_index_it_init(), osd_it_acct_init(), osd_object_find(), out_attr_get(), out_create(), out_destroy(), out_index_delete(), out_index_lookup(), out_read(), out_ref_del(), out_tx_xattr_del_exec(), out_tx_xattr_set_exec(), out_xattr_get(), and tgt_mdt_body_unpack().
#define LU_OBJECT_HEADER (mask, env, object, format, ...)
Value:
do {                                                                    \
        if (cfs_cdebug_show(mask, DEBUG_SUBSYSTEM)) {                   \
                LIBCFS_DEBUG_MSG_DATA_DECL(msgdata, mask, NULL);        \
                lu_object_header_print(env, &msgdata, lu_cdebug_printer,\
                                       (object)->lo_header);            \
                lu_cdebug_printer(env, &msgdata, "\n");                 \
                CDEBUG(mask, format , ## __VA_ARGS__);                  \
        }                                                               \
} while (0)
Print short object description followed by a user-supplied message.
Definition at line 812 of file lu_object.h.
Referenced by cl_io_rw_init(), cl_object_glimpse(), lov_init_sub(), and vvp_io_read_start().
#define lu_object_remote (o) unlikely((o)->lo_header->loh_attr & LOHA_REMOTE)
Check whether object on the remote storage.
Definition at line 845 of file lu_object.h.
Referenced by dt_object_remote(), mdd_object_remote(), mdt_object_remote(), ofd_ioc_get_obj_version(), tgt_txn_start_cb(), and tgt_txn_stop_cb().
#define LU_TYPE_FINI (mod, ...)
Value:
static void mod##_type_fini(struct lu_device_type *t)           \
        {                                                               \
                lu_context_key_degister_many(__VA_ARGS__, NULL);        \
        }                                                               \
        struct __##mod##_dummy_type_fini {;}
Definition at line 1213 of file lu_object.h.
#define LU_TYPE_INIT (mod, ...)
Value:
LU_KEY_INIT_GENERIC(mod)                                        \
        static int mod##_type_init(struct lu_device_type *t)            \
        {                                                               \
                mod##_key_init_generic(__VA_ARGS__, NULL);              \
                return lu_context_key_register_many(__VA_ARGS__, NULL); \
        }                                                               \
        struct __##mod##_dummy_type_init {;}
Definition at line 1204 of file lu_object.h.
#define LU_TYPE_INIT_FINI (mod, ...)
Value:
LU_TYPE_INIT(mod, __VA_ARGS__);         \
        LU_TYPE_FINI(mod, __VA_ARGS__);         \
        LU_TYPE_START(mod, __VA_ARGS__);        \
        LU_TYPE_STOP(mod, __VA_ARGS__)
Definition at line 1236 of file lu_object.h.
#define LU_TYPE_START (mod, ...)
Value:
static void mod##_type_start(struct lu_device_type *t)  \
        {                                                       \
                lu_context_key_revive_many(__VA_ARGS__, NULL);  \
        }                                                       \
        struct __##mod##_dummy_type_start {;}
Definition at line 1220 of file lu_object.h.
#define LU_TYPE_STOP (mod, ...)
Value:
static void mod##_type_stop(struct lu_device_type *t)   \
        {                                                       \
                lu_context_key_quiesce_many(__VA_ARGS__, NULL); \
        }                                                       \
        struct __##mod##_dummy_type_stop {;}
Definition at line 1227 of file lu_object.h.
#define PLUBUF (buf) (buf)->lb_buf, (buf)->lb_len
Definition at line 1340 of file lu_object.h.
#define PNAME (ln)
Value:
(lu_name_is_valid(ln) ? (ln)->ln_namelen : 0),  \
        (lu_name_is_valid(ln) ? (ln)->ln_name : "")
Definition at line 1326 of file lu_object.h.
Referenced by mdd_update_linkea_internal(), mdt_getattr_name_lock(), mdt_md_create(), mdt_reint_link(), mdt_reint_migrate_internal(), mdt_reint_open(), mdt_reint_rename_internal(), and mdt_reint_unlink().
Typedef Documentation
typedef int(* lu_printer_t)(const struct lu_env *env, void *cookie, const char *format,...) __attribute__((format(printf
Type of "printer" function used by lu_object_operations::loo_object_print() method.
Printer function is needed to provide some flexibility in (semi-)debugging output: possible implementations: printk, CDEBUG, sysfs/seq_file
Definition at line 197 of file lu_object.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
LU_SS_CREATED
LU_SS_CACHE_HIT
LU_SS_CACHE_MISS
LU_SS_CACHE_RACE
LU_SS_CACHE_DEATH_RACE
LU_SS_LRU_PURGED
LU_SS_LRU_LEN
LU_SS_LAST_STAT
Definition at line 586 of file lu_object.h.
enum la_valid
Bit-mask of valid attributes.
Enumerator:
LA_ATIME
LA_MTIME
LA_CTIME
LA_SIZE
LA_MODE
LA_UID
LA_GID
LA_BLOCKS
LA_TYPE
LA_FLAGS
LA_NLINK
LA_RDEV
LA_BLKSIZE
LA_KILL_SUID
LA_KILL_SGID
Definition at line 443 of file lu_object.h.
enum loc_flags_t
For lu_object_conf flags.
Enumerator:
LOC_F_NEW
LOC_F_NOWAIT
Definition at line 168 of file lu_object.h.
enum lu_context_state
For lu_context health-checks.
Enumerator:
LCS_INITIALIZED
LCS_ENTERED
LCS_LEFT
LCS_FINALIZED
Definition at line 919 of file lu_object.h.
enum lu_context_tag
lu_context_key interface.
Similar to pthread_key.
Enumerator:
LCT_MD_THREAD
Thread on md server.
LCT_DT_THREAD
Thread on dt server.
LCT_TX_HANDLE
Context for transaction handle.
LCT_CL_THREAD
Thread on client.
LCT_SESSION
A per-request session on a server, and a per-system-call session on a client.
LCT_OSP_THREAD
A per-request data on OSP device.
LCT_MG_THREAD
MGS device thread.
LCT_LOCAL
Context for local operations.
LCT_SERVER_SESSION
session for server thread
LCT_HAS_EXIT
Set when at least one of keys, having values in this context has non-NULL lu_context_key::lct_exit() method.
This is used to optimize lu_context_exit() call.
LCT_NOREF
Don't add references for modules creating key values in that context.
This is only for contexts used internally by lu_object framework.
LCT_QUIESCENT
Key is being prepared for retiring, don't create new values for it.
LCT_REMEMBER
Context should be remembered.
LCT_SHRINKER
Contexts usable in cache shrinker thread.
Definition at line 991 of file lu_object.h.
enum lu_device_tag
Tag bits for device type.
They are used to distinguish certain groups of device types.
Enumerator:
LU_DEVICE_MD
this is meta-data device
LU_DEVICE_DT
this is data device
LU_DEVICE_CL
data device in the client stack
Definition at line 304 of file lu_object.h.
enum lu_object_header_attr
Enumerator:
LOHA_EXISTS
LOHA_REMOTE
LOHA_FT_START
UNIX file type is stored in S_IFMT bits.
S_IFIFO
LOHA_FT_END
S_IFMT.
Definition at line 500 of file lu_object.h.
enum lu_object_header_flags
Enumerator:
LU_OBJECT_HEARD_BANSHEE
Don't keep this object in cache.
Object will be destroyed as soon as last reference to it is released. This flag cannot be cleared once set.
LU_OBJECT_UNHASHED
Mark this object has already been taken out of cache.
Definition at line 487 of file lu_object.h.
enum lu_xattr_flags
Enumerator:
LU_XATTR_REPLACE
LU_XATTR_CREATE
Definition at line 908 of file lu_object.h.
Function Documentation
void lu_buf_alloc (struct lu_buf * buf, size_t size)
Definition at line 2351 of file lu_object.c.
References LASSERT, lu_buf::lb_buf, lu_buf::lb_len, likely, and OBD_ALLOC_LARGE.
Referenced by lfsck_layout_get_lovea(), lod_load_lmv_shards(), lu_buf_check_and_alloc(), lu_buf_realloc(), mdd_get_lov_ea(), mdd_hsm_archive_exists(), and mdd_swap_layouts().
struct lu_buf* lu_buf_check_and_alloc (struct lu_buf * buf, size_t len) [read]
Definition at line 2369 of file lu_object.c.
References lu_buf::lb_buf, lu_buf::lb_len, lu_buf_alloc(), and lu_buf_realloc().
Referenced by lfsck_links_read(), lfsck_links_read2(), linkea_data_new(), mdd_changelog_data_store(), mdd_changelog_ns_store(), mdd_changelog_write_header(), mdd_declare_changelog_store(), mdd_get_lov_ea(), mdd_linkea_update_child_internal(), mdd_links_read(), mdd_migrate_create(), mdd_migrate_sanity_check(), mdd_migrate_xattrs(), mdd_parent_fid(), mdt_links_read(), mdt_lock_objects_in_linkea(), and mdt_path_current().
int lu_buf_check_and_grow (struct lu_buf * buf, size_t len)
Increase the size of the buf.
preserves old data in buffer old buffer remains unchanged on error
Return values:
0 or -ENOMEM
Definition at line 2387 of file lu_object.c.
References lu_buf::lb_buf, lu_buf::lb_len, OBD_ALLOC_LARGE, and OBD_FREE_LARGE.
Referenced by linkea_add_buf().
void lu_buf_free (struct lu_buf * buf)
Definition at line 2339 of file lu_object.c.
References LASSERT, lu_buf::lb_buf, lu_buf::lb_len, and OBD_FREE_LARGE.
Referenced by lfsck_key_fini(), ll_getparent(), lod_key_fini(), lu_buf_realloc(), mdd_create(), mdd_get_lov_ea(), mdd_hsm_archive_exists(), mdd_key_fini(), mdd_link(), mdd_links_read(), mdd_links_rename(), mdd_swap_layouts(), mdt_links_read(), mdt_thread_info_fini(), osc_key_fini(), and osd_key_fini().
void lu_buf_realloc (struct lu_buf * buf, size_t size)
Definition at line 2362 of file lu_object.c.
References lu_buf_alloc(), and lu_buf_free().
Referenced by __lfsck_links_read(), __osd_init_iobuf(), lfsck_layout_get_lovea(), lfsck_layout_recreate_lovea(), lfsck_layout_recreate_parent(), lu_buf_check_and_alloc(), osc_io_ladvise_start(), and osd_get_pfid_from_linkea().
int lu_cdebug_printer (const struct lu_env * env, void * cookie, const char * format, ...)
Printer function emitting messages through libcfs_debug_msg().
Definition at line 491 of file lu_object.c.
References ARRAY_SIZE, cfs_cdebug_show(), LASSERT, lu_cdebug_data::lck_area, lu_env::le_ctx, libcfs_debug_msg(), lu_context_key_get(), libcfs_debug_msg_data::msg_mask, and libcfs_debug_msg_data::msg_subsys.
Referenced by lovsub_device_free(), lwp_device_free(), mgs_device_fini(), mgs_init0(), ofd_stack_fini(), osd_device_free(), and osp_device_free().
void lu_context_enter (struct lu_context * ctx)
Called before entering context.
Definition at line 1776 of file lu_object.c.
References lu_context::lc_state, LCS_ENTERED, LCS_INITIALIZED, LCS_LEFT, and LINVRNT.
Referenced by cl_env_new(), cl_env_obtain(), cl_env_percpu_init(), distribute_txn_replay_handle(), echo_client_iocontrol(), echo_client_prep_commit(), llog_test_setup(), lu_env_init(), lustre_lwp_connect(), mdt_ctxt_add_dirty_flag(), mdt_hsm_cdt_init(), mdt_ioc_child(), obd_setup(), osd_trans_start(), ptlrpc_main(), ptlrpc_server_handle_req_in(), ptlrpcd(), and server_start_targets().
void lu_context_exit (struct lu_context * ctx)
Called after exiting from ctx.
Definition at line 1786 of file lu_object.c.
References ARRAY_SIZE, LASSERT, lu_context::lc_state, lu_context::lc_tags, lu_context::lc_value, LCS_ENTERED, LCS_LEFT, lu_context_key::lct_exit, LCT_HAS_EXIT, LCT_REMEMBER, and LINVRNT.
Referenced by cl_env_exit(), cl_env_percpu_fini(), cl_env_percpu_init(), distribute_txn_replay_handle(), echo_client_iocontrol(), echo_client_prep_commit(), llog_test_setup(), lu_env_fini(), lustre_lwp_connect(), mdt_ctxt_add_dirty_flag(), mdt_hsm_cdt_fini(), mdt_ioc_child(), obd_setup(), osd_trans_commit_cb(), ptlrpc_main(), ptlrpc_server_drop_request(), ptlrpcd(), and server_start_targets().
void lu_context_fini (struct lu_context * ctx)
Finalize context data-structure.
Destroy key values.
Definition at line 1755 of file lu_object.c.
References keys_fini(), LASSERT, lu_context::lc_remember, lu_context::lc_state, lu_context::lc_tags, LCS_FINALIZED, LCS_INITIALIZED, LCS_LEFT, LCT_REMEMBER, LINVRNT, list_del_init(), and list_empty().
Referenced by cl_env_fini(), cl_env_percpu_fini(), cl_env_percpu_init(), distribute_txn_replay_handle(), echo_client_iocontrol(), llog_test_setup(), lu_context_init(), lu_env_fini(), lustre_lwp_connect(), mdt_ctxt_add_dirty_flag(), mdt_hsm_cdt_fini(), mdt_ioc_child(), obd_setup(), osd_trans_commit_cb(), ptlrpc_main(), ptlrpc_server_drop_request(), ptlrpcd(), ptlrpcd_free(), ptlrpcd_start(), and server_start_targets().
int lu_context_init (struct lu_context * ctx, __u32 tags)
Initialize context data-structure.
Create values for all keys.
Definition at line 1729 of file lu_object.c.
References INIT_LIST_HEAD, keys_init(), lu_context::lc_remember, lu_context::lc_state, lu_context::lc_tags, LCS_INITIALIZED, LCT_REMEMBER, list_add(), lu_context_fini(), and lu_context_remembered.
Referenced by cl_env_new(), cl_env_percpu_init(), distribute_txn_replay_handle(), echo_client_iocontrol(), llog_test_setup(), lu_env_init(), lustre_lwp_connect(), mdt_ctxt_add_dirty_flag(), mdt_hsm_cdt_init(), mdt_ioc_child(), obd_setup(), osd_trans_start(), ptlrpc_main(), ptlrpc_server_handle_req_in(), ptlrpcd(), ptlrpcd_start(), and server_start_targets().
void lu_context_key_degister (struct lu_context_key * key)
Deregister key.
Wait until all transient contexts referencing this key have run lu_context_key::lct_fini() method.
Definition at line 1455 of file lu_object.c.
References ARRAY_SIZE, CDEBUG, D_INFO, key_fini(), LASSERT, LASSERTF, lu_context_key::lct_index, lu_context_key::lct_owner, lu_context_key::lct_reference, lu_context_key::lct_used, lu_env::le_ctx, LINVRNT, lu_context_key_quiesce(), lu_ref_fini(), and lu_shrink_env.
Referenced by cl_global_fini(), cl_global_init(), dt_global_fini(), fid_server_mod_exit(), fld_server_mod_exit(), lfsck_exit(), llog_info_fini(), lquota_exit(), lquota_init(), lu_context_key_degister_many(), lu_context_key_register_many(), lu_global_fini(), lu_ucred_global_fini(), osd_type_fini(), qsd_glb_fini(), tgt_mod_exit(), and update_info_fini().
void lu_context_key_degister_many (struct lu_context_key * k, ...)
De-register a number of keys.
This is a dual to lu_context_key_register_many().
Definition at line 1526 of file lu_object.c.
References lu_context_key_degister().
void* lu_context_key_get (const struct lu_context * ctx, const struct lu_context_key * key)
Return value associated with key key in context ctx.
Definition at line 1574 of file lu_object.c.
References ARRAY_SIZE, LASSERT, lu_context::lc_state, lu_context::lc_value, LCS_ENTERED, lu_context_key::lct_index, and LINVRNT.
Referenced by cl_env_info(), dt_info(), echo_env_info(), fid_is_local(), fld_declare_index_create(), fld_index_create(), fld_index_init(), fld_index_lookup(), fld_local_lookup(), fld_server_read(), fld_update_from_controller(), hsm_cancel_all_actions(), lfsck_env_info(), ll_env_info(), llog_info(), lod_env_info(), lov_env_info(), lov_env_session(), lquota_info(), lu_cdebug_printer(), lu_ucred(), mdd_env_info(), mdt_buf(), mdt_buf_const(), mdt_export_cleanup(), mdt_hsm_cdt_init(), mdt_hsm_cdt_start(), mdt_hsm_cdt_stop(), mdt_init0(), mdt_iocontrol(), mdt_lvbo_fill(), mdt_stack_fini(), mdt_stack_pre_fini(), mdt_th_info(), mdt_txn_stop_cb(), mgs_env_info(), ofd_info(), ofd_punch_hpreq_check(), ofd_punch_hpreq_lock_match(), ofd_rw_hpreq_check(), osc_env_info(), osc_env_session(), osd_oti_get(), osp_env_info(), osp_txn_info(), qmt_info(), qsd_info(), seq_store_read(), seq_store_update(), tgt_ses_info(), tgt_th_info(), update_env_info(), vvp_env_info(), and vvp_env_session().
void lu_context_key_quiesce (struct lu_context_key * key)
Destroy key in all remembered contexts.
This is used to destroy key values in "shared" contexts (like service threads), when a module owning the key is about to be unloaded.
Wait until all lu_context_key::lct_init() methods have completed.
Definition at line 1594 of file lu_object.c.
References CDEBUG, cl_env_cache_purge(), D_INFO, key_fini(), lu_context::lc_remember, lu_context_key::lct_index, lu_context_key::lct_owner, LCT_QUIESCENT, lu_context_key::lct_tags, lu_context_key::lct_used, list_for_each_entry, and lu_context_remembered.
Referenced by lu_context_key_degister(), and lu_context_key_quiesce_many().
void lu_context_key_quiesce_many (struct lu_context_key * k, ...)
Quiescent a number of keys.
Definition at line 1558 of file lu_object.c.
References lu_context_key_quiesce().
int lu_context_key_register (struct lu_context_key * key)
Register new key.
Definition at line 1401 of file lu_object.c.
References ARRAY_SIZE, LASSERT, lu_context_key::lct_fini, lu_context_key::lct_index, lu_context_key::lct_init, lu_context_key::lct_owner, lu_context_key::lct_reference, lu_context_key::lct_tags, lu_context_key::lct_used, and lu_ref_init().
Referenced by cl_global_init(), dt_global_init(), fid_server_mod_init(), fld_server_mod_init(), lfsck_init(), llog_info_init(), lquota_init(), lu_context_key_register_many(), lu_global_init(), lu_ucred_global_init(), osd_type_init(), qsd_glb_init(), and update_info_init().
int lu_context_key_register_many (struct lu_context_key * k, ...)
Register a number of keys.
This has to be called after all keys have been initialized by a call to LU_CONTEXT_KEY_INIT().
Definition at line 1494 of file lu_object.c.
References lu_context_key_degister(), and lu_context_key_register().
Referenced by tgt_mod_init().
void lu_context_key_revive (struct lu_context_key * key)
Definition at line 1633 of file lu_object.c.
References LCT_QUIESCENT, and lu_context_key::lct_tags.
Referenced by lu_context_key_revive_many().
void lu_context_key_revive_many (struct lu_context_key * k, ...)
Revive a number of keys.
Definition at line 1542 of file lu_object.c.
References lu_context_key_revive().
int lu_context_refill (struct lu_context * ctx)
Allocate for context all missing keys that were registered after context creation.
key_set_version is only changed in rare cases when modules are loaded and removed.
Definition at line 1818 of file lu_object.c.
References keys_fill(), lu_context::lc_version, and likely.
Referenced by lu_env_refill(), and lu_site_init_finish().
void lu_context_tags_clear (__u32 tags)
Definition at line 1842 of file lu_object.c.
Referenced by echo_client_cleanup().
void lu_context_tags_update (__u32 tags)
Definition at line 1833 of file lu_object.c.
Referenced by echo_client_setup().
void lu_dev_add_linkage (struct lu_site * s, struct lu_device * d)
Definition at line 1038 of file lu_object.c.
References lu_device::ld_linkage, list_add(), list_empty(), lu_site::ls_ld_linkage, and lu_site::ls_ld_lock.
Referenced by lu_site_init(), mdd_connect_to_next(), and mdt_stack_init().
void lu_dev_del_linkage (struct lu_site * s, struct lu_device * d)
Definition at line 1047 of file lu_object.c.
References lu_device::ld_linkage, list_del_init(), and lu_site::ls_ld_lock.
Referenced by lod_process_config(), mdd_device_fini(), mdd_process_config(), mdt_stack_fini(), osd_process_config(), and osp_process_config().
void lu_device_fini (struct lu_device * d)
Finalize device d.
Definition at line 1218 of file lu_object.c.
References LASSERT, LASSERTF, lu_device::ld_obd, lu_device::ld_ref, lu_device::ld_reference, lu_device::ld_type, lu_device_type::ldt_device_nr, lu_device_type::ldt_ops, lu_device_type_operations::ldto_stop, lu_ref_fini(), and obd_device::obd_lu_dev.
Referenced by cl_device_fini(), dt_device_fini(), ls_device_put(), lwp_device_free(), md_device_fini(), mdt_device_free(), and qmt_device_free().
void lu_device_get (struct lu_device * d)
Acquire additional reference on device d.
Definition at line 1181 of file lu_object.c.
References lu_device::ld_ref.
Referenced by cl_type_setup(), lovsub_device_init(), lu_object_init(), lu_site_init(), osd_start(), osd_trans_start(), qmt_pool_alloc(), qsd_init(), and vvp_device_init().
int lu_device_init (struct lu_device * d, struct lu_device_type * t)
Initialize device d of type t.
Definition at line 1200 of file lu_object.c.
References INIT_LIST_HEAD, lu_device::ld_linkage, lu_device::ld_reference, lu_device::ld_type, lu_device_type::ldt_device_nr, lu_device_type::ldt_ops, lu_device_type_operations::ldto_start, and lu_ref_init().
Referenced by cl_device_init(), dt_device_init(), ls_device_get(), lwp_device_alloc(), md_device_init(), and mdt_init0().
static bool lu_device_is_cl (const struct lu_device * d) [inline, static]
Definition at line 1393 of file lu_object.h.
References lu_device::ld_type, lu_device_type::ldt_tags, and LU_DEVICE_CL.
Referenced by echo_device_alloc(), lu2cl(), lu2cl_dev(), lu_object_is_cl(), and vvp_pgcache_obj().
static int lu_device_is_md (const struct lu_device * d) [inline, static]
Definition at line 399 of file lu_object.h.
References ergo, lu_device::ld_type, lu_device_type::ldt_tags, and LU_DEVICE_MD.
Referenced by lquotactl_slv(), lu2md(), lu2md_dev(), osd_mkreg(), osd_trans_start(), and qsd_prepare().
void lu_device_put (struct lu_device * d)
Release reference on device d.
Definition at line 1190 of file lu_object.c.
References LASSERT, and lu_device::ld_ref.
Referenced by lu_object_fini(), lu_site_fini(), lu_stack_fini(), lustre_put_lsi(), osd_trans_commit_cb(), qmt_pool_free(), and qsd_fini().
void lu_device_type_fini (struct lu_device_type * ldt)
Definition at line 854 of file lu_object.c.
References lu_device_type::ldt_linkage, lu_device_type::ldt_ops, lu_device_type_operations::ldto_fini, list_del_init(), and obd_types_lock.
Referenced by class_unregister_type(), and vvp_global_fini().
int lu_device_type_init (struct lu_device_type * ldt)
Helpers to initialize and finalize device types.
Definition at line 835 of file lu_object.c.
References INIT_LIST_HEAD, lu_device_type::ldt_device_nr, lu_device_type::ldt_linkage, lu_device_type::ldt_ops, lu_device_type_operations::ldto_init, list_add(), lu_device_types, and obd_types_lock.
Referenced by class_register_type(), and vvp_global_init().
void lu_env_fini (struct lu_env * env)
Definition at line 1881 of file lu_object.c.
References lu_env::le_ctx, lu_env::le_ses, lu_context_exit(), and lu_context_fini().
Referenced by __mdd_orphan_cleanup(), arc_prune_func(), cl_env_new(), cl_env_percpu_fini(), cl_env_percpu_init(), distribute_txn_commit_thread(), echo_client_iocontrol(), lfsck_dump(), lfsck_get_speed(), lfsck_get_windows(), lfsck_set_speed(), lfsck_set_windows(), lfsck_thread_args_fini(), llog_process_thread_daemonize(), llog_test_cleanup(), llog_test_setup(), lod_sub_recovery_thread(), lprocfs_release_hsm_actions(), lu_global_fini(), lustre_lwp_connect(), mdd_changelog_size_seq_show(), mdd_changelog_users_seq_show(), mdt_blocking_ast(), mdt_enable_cos(), mdt_export_cleanup(), mdt_hsm_cdt_fini(), mdt_hsm_cdt_init(), mdt_iocontrol(), mdt_lvbo_fill(), mdt_obd_postrecov(), mdt_register_lwp_callback(), mgc_process_cfg_log(), mgs_iocontrol(), nodemap_idx_action(), obd_cleanup(), obd_precleanup(), obd_process_config(), obd_setup(), ofd_health_check(), ofd_inconsistency_verification_main(), ofd_iocontrol(), ofd_lvbo_init(), ofd_lvbo_update(), ofd_obd_disconnect(), ofd_obd_postrecov(), ofd_register_lwp_callback(), osd_scrub_main(), osp_init_pre_fid(), osp_invalidate_request(), osp_precreate_thread(), osp_send_update_thread(), osp_sync_thread(), qmt_lvbo_fill(), qmt_lvbo_free(), qmt_lvbo_init(), qmt_lvbo_update(), qmt_reba_thread(), qsd_id_blocking_ast(), qsd_reint_main(), qsd_upd_thread(), server_start_targets(), tgt_blocking_ast(), and tgt_boot_epoch_update().
int lu_env_init (struct lu_env * env, __u32 tags)
Definition at line 1869 of file lu_object.c.
References lu_env::le_ctx, lu_env::le_ses, likely, lu_context_enter(), and lu_context_init().
Referenced by __mdd_orphan_cleanup(), arc_prune_func(), cl_env_new(), cl_env_percpu_init(), distribute_txn_commit_thread(), echo_client_iocontrol(), lfsck_dump(), lfsck_get_speed(), lfsck_get_windows(), lfsck_set_speed(), lfsck_set_windows(), lfsck_thread_args_init(), llog_process_thread_daemonize(), llog_test_cleanup(), llog_test_setup(), lod_sub_recovery_thread(), lprocfs_open_hsm_actions(), lu_debugging_setup(), lu_global_init(), lustre_lwp_connect(), mdd_changelog_size_seq_show(), mdd_changelog_users_seq_show(), mdt_blocking_ast(), mdt_enable_cos(), mdt_export_cleanup(), mdt_hsm_cdt_init(), mdt_iocontrol(), mdt_lvbo_fill(), mdt_obd_postrecov(), mdt_register_lwp_callback(), mgc_process_cfg_log(), mgs_iocontrol(), nodemap_idx_action(), obd_cleanup(), obd_precleanup(), obd_process_config(), obd_setup(), ofd_health_check(), ofd_inconsistency_verification_main(), ofd_iocontrol(), ofd_lvbo_init(), ofd_lvbo_update(), ofd_obd_disconnect(), ofd_obd_postrecov(), ofd_register_lwp_callback(), osd_scrub_main(), osp_init_pre_fid(), osp_invalidate_request(), osp_precreate_thread(), osp_send_update_thread(), osp_sync_thread(), qmt_lvbo_fill(), qmt_lvbo_free(), qmt_lvbo_init(), qmt_lvbo_update(), qmt_reba_thread(), qsd_id_blocking_ast(), qsd_reint_main(), qsd_upd_thread(), server_start_targets(), tgt_blocking_ast(), and tgt_boot_epoch_update().
int lu_env_refill (struct lu_env * env)
Definition at line 1889 of file lu_object.c.
References lu_env::le_ctx, lu_env::le_ses, and lu_context_refill().
Referenced by cl_env_obtain(), cl_env_percpu_refill(), distribute_txn_replay_handle(), lquota_info(), lu_env_refill_by_tags(), mdd_env_info(), mdt_init0(), mdt_stack_init(), mdt_th_info(), mgs_env_info(), mgs_target_reg(), ofd_info(), ofd_init0(), osd_device_alloc(), osd_device_init0(), osp_env_info(), ptlrpcd_check(), qmt_info(), qsd_info(), and tgt_request_handle().
int lu_env_refill_by_tags (struct lu_env * env, __u32 ctags, __u32 stags)
Currently, this API will only be used by echo client.
Because echo client and normal lustre client will share same cl_env cache. So echo client needs to refresh the env context after it get one from the cache, especially when normal client and echo client co-exist in the same client.
Definition at line 1907 of file lu_object.c.
References lu_context::lc_tags, lu_context::lc_version, lu_env::le_ctx, lu_env::le_ses, and lu_env_refill().
Referenced by echo_client_iocontrol(), and qsd_req_completion().
void lu_global_fini (void)
Dual to lu_global_init().
Definition at line 2181 of file lu_object.c.
References lu_context_key_degister(), lu_env_fini(), lu_ref_global_fini(), lu_shrink_env, and remove_shrinker().
Referenced by obdclass_exit().
int lu_global_init (void)
One-time initializers, called at obdclass module initialization, not exported.
Initialization of global lu_* data.
Definition at line 2134 of file lu_object.c.
References CDEBUG, D_INFO, DEF_SHRINKER_VAR, INIT_LIST_HEAD, LCT_SHRINKER, lu_cache_shrink(), lu_cache_shrink_count(), lu_cache_shrink_scan(), LU_CONTEXT_KEY_INIT, lu_context_key_register(), lu_context_remembered, lu_device_types, lu_env_init(), lu_ref_global_init(), lu_shrink_env, lu_sites, and set_shrinker().
Referenced by obdclass_init().
void lu_kmem_fini (struct lu_kmem_descr * caches)
Helper function to finalize a number of kmem slab cached at once.
Dual to lu_kmem_init().
Definition at line 2275 of file lu_object.c.
References lu_kmem_descr::ckd_cache.
Referenced by cl_global_fini(), cl_global_init(), ll_xattr_fini(), lod_exit(), lod_init(), lov_exit(), lov_init(), lquota_exit(), lquota_init(), lu_kmem_init(), mdd_exit(), mdd_init(), mdt_exit(), mdt_init(), obdecho_exit(), obdecho_init(), ofd_exit(), ofd_init(), osc_exit(), osc_init(), osd_exit(), osd_init(), osp_exit(), osp_init(), qsd_glb_fini(), vvp_global_fini(), and vvp_global_init().
int lu_kmem_init (struct lu_kmem_descr * caches)
Helper function to initialize a number of kmem slab caches at once.
Definition at line 2251 of file lu_object.c.
References lu_kmem_descr::ckd_cache, lu_kmem_descr::ckd_name, lu_kmem_descr::ckd_size, and lu_kmem_fini().
Referenced by cl_global_init(), ll_xattr_init(), lod_init(), lov_init(), lquota_init(), mdd_init(), mdt_init(), obdecho_init(), ofd_init(), osc_init(), osd_init(), osp_init(), qsd_glb_init(), and vvp_global_init().
static bool lu_name_is_valid (const struct lu_name * ln) [inline, static]
Definition at line 1320 of file lu_object.h.
References lu_name::ln_name, lu_name::ln_namelen, and lu_name_is_valid_2().
Referenced by mdd_name_check(), mdt_getattr_name_lock(), mdt_lock_pdo_init(), mdt_name_unpack(), mdt_reint_create(), and mdt_reint_open().
static bool lu_name_is_valid_2 (const char * name, size_t name_len) [inline, static]
Validate names (path components).
To be valid name must be non-empty, '' terminated of length name_len, and not contain '/'. The maximum length of a name (before say -ENAMETOOLONG will be returned) is really controlled by llite and the server. We only check for something insane coming from bad integer handling here.
Definition at line 1310 of file lu_object.h.
Referenced by ll_intent_file_open(), ll_prep_md_op_data(), lu_name_is_valid(), and mdc_pack_name().
void lu_object_add (struct lu_object * before, struct lu_object * o)
Add object o as a layer of compound object, going after before.
This is typically called by the ->ldo_object_alloc() method of before->lo_dev.
Definition at line 1292 of file lu_object.c.
References list_move(), and lu_object::lo_linkage.
Referenced by echo_object_init(), lod_object_init(), lovsub_object_init(), ls_object_init(), mdd_object_init(), mdt_object_init(), mgs_object_init(), ofd_object_init(), and vvp_object_init().
void lu_object_add_top (struct lu_object_header * h, struct lu_object * o)
Add object o as first layer of compound object h.
This is typically called by the ->ldo_object_alloc() method of top-level device.
Definition at line 1280 of file lu_object.c.
References list_move(), lu_object::lo_linkage, and lu_object_header::loh_layers.
Referenced by echo_object_alloc(), lovsub_object_alloc(), ls_object_alloc(), mdt_object_alloc(), mgs_object_alloc(), ofd_object_alloc(), osp_object_alloc(), and vvp_object_alloc().
struct lu_object* lu_object_anon (const struct lu_env * env, struct lu_device * dev, const struct lu_object_conf * conf) [read]
allocates object with 0 (non-assiged) fid XXX: temporary solution to be able to assign fid in ->do_create() till we have fully-functional OST fids
Definition at line 2319 of file lu_object.c.
References fid_zero(), and lu_object_alloc().
Referenced by lfsck_layout_repair_multiple_references(), and lod_qos_declare_object_on().
static int lu_object_assert_exists (const struct lu_object * o) [inline, static]
Definition at line 847 of file lu_object.h.
References lu_object_exists.
Referenced by mdt_getattr(), and mdt_getxattr().
static int lu_object_assert_not_exists (const struct lu_object * o) [inline, static]
Definition at line 852 of file lu_object.h.
References lu_object_exists.
void lu_object_assign_fid (const struct lu_env * env, struct lu_object * o, const struct lu_fid * fid)
Temporary solution to be able to assign fid in ->do_create() till we have fully-functional OST fids.
Definition at line 2290 of file lu_object.c.
References __u64, cfs_hash_bd_add_locked(), cfs_hash_bd_get_and_lock(), cfs_hash_bd_unlock(), fid_is_zero(), htable_lookup(), LASSERT, lu_device::ld_site, lu_object::lo_dev, lu_object::lo_header, lu_object_header::loh_fid, lu_object_header::loh_hash, lu_site::ls_obj_hash, and version.
Referenced by osp_object_assign_fid().
static __u32 lu_object_attr (const struct lu_object * o) [inline, static]
Attr of this object.
Definition at line 860 of file lu_object.h.
References LASSERT, lu_object::lo_header, lu_object_header::loh_attr, and lu_object_exists.
Referenced by dt_index_read(), lfsck_layout_scan_orphan_one(), lfsck_object_type(), lod_load_striping_locked(), mdd_migrate(), mdd_migrate_xattrs(), mdd_object_type(), mdt_attr_get_complex(), mdt_attr_get_eabuf_size(), mdt_close_swap_layouts(), mdt_getattr_internal(), mdt_getattr_name_lock(), mdt_lock_objects_in_linkea(), mdt_lookup_fileset(), mdt_object_local_lock(), mdt_object_open_lock(), mdt_open_by_fid_lock(), mdt_reint_migrate_internal(), and mdt_reint_rename_internal().
static struct lu_fid* lu_object_fid (const struct lu_object * o) [static, read]
Pointer to the fid of this object.
Definition at line 770 of file lu_object.h.
References lu_object::lo_header, and lu_object_header::loh_fid.
Referenced by __local_file_create(), __osd_object_create(), cat_print_cb(), cl_glimpse_lock(), cl_lock_descr_print(), cl_lock_descr_sort(), cl_setattr_ost(), lfsck_dto2fid(), lfsck_layout_assistant_handler_p1(), lfsck_layout_conflict_create(), lfsck_layout_repair_dangling(), lfsck_layout_repair_multiple_references(), lfsck_layout_repair_unmatched_pair(), lfsck_layout_update_pfid(), ll_readahead(), llog_osd_get_regular_fid_dir(), llog_osd_next_block(), llog_osd_prev_block(), llog_osd_read_header(), llog_osd_regular_fid_add_name_entry(), llog_osd_regular_fid_del_name_entry(), llog_osd_write_rec(), llog_test_8(), lod_ah_init(), lod_alloc_specific(), lod_cache_parent_lov_striping(), lod_declare_object_destroy(), lod_dir_declare_create_stripes(), lod_generate_and_set_lovea(), lod_load_lmv_shards(), lod_object_destroy(), lod_object_init(), lod_object_lock(), lod_object_replace_parent_fid(), lod_object_start(), lod_prep_lmv_md(), lod_sub_get_thandle(), lod_sub_object_attr_set(), lod_sub_object_create(), lod_sub_object_declare_attr_set(), lod_sub_object_declare_create(), lod_sub_object_declare_delete(), lod_sub_object_declare_destroy(), lod_sub_object_declare_insert(), lod_sub_object_declare_punch(), lod_sub_object_declare_ref_add(), lod_sub_object_declare_ref_del(), lod_sub_object_declare_write(), lod_sub_object_declare_xattr_del(), lod_sub_object_declare_xattr_set(), lod_sub_object_delete(), lod_sub_object_destroy(), lod_sub_object_index_insert(), lod_sub_object_punch(), lod_sub_object_ref_add(), lod_sub_object_ref_del(), lod_sub_object_write(), lod_sub_object_xattr_del(), lod_sub_object_xattr_set(), lod_xattr_get(), lod_xattr_set_lmv(), lov_conf_set(), lov_io_init_empty(), lov_io_read_ahead(), lov_layout_change(), lov_layout_wait(), lquota_disk_glb_find_create(), lquota_disk_slv_find_create(), lquota_disk_write(), lu_object_find_try(), lu_object_put(), mdd_local_file_create(), mdd_object_fid(), mdo2fid(), mdt_object_fid(), mdt_object_free(), mdt_object_init(), mgs_object_init(), obj2type(), ofd_object_free(), ofd_object_init(), ofd_precreate_objects(), orph_declare_index_insert(), orph_index_insert(), osd_acct_index_lookup(), osd_add_to_remote_parent(), osd_attr_set(), osd_check_lma(), osd_create_local_agent_inode(), osd_declare_object_create(), osd_declare_object_destroy(), osd_delete_from_remote_parent(), osd_dir_it_rec(), osd_dir_lookup(), osd_ea_add_rec(), osd_idc_find_and_init(), osd_index_ea_insert(), osd_index_iam_delete(), osd_index_iam_insert(), osd_index_iam_lookup(), osd_index_try(), osd_it_acct_get(), osd_it_acct_init(), osd_it_acct_next(), osd_it_iam_get(), osd_it_iam_key(), osd_it_iam_rec(), osd_object_create(), osd_object_destroy(), osd_object_ea_create(), osd_object_init(), osd_object_init0(), osd_object_ref_add(), osd_object_ref_del(), osd_write_commit(), osd_xattr_set(), osp_attr_get(), osp_declare_attr_set(), osp_declare_object_create(), osp_index_try(), osp_insert_async_request(), osp_it_fetch(), osp_md_attr_set(), osp_md_index_delete(), osp_md_index_insert(), osp_md_index_lookup(), osp_md_object_create(), osp_md_object_destroy(), osp_md_read(), osp_md_ref_add(), osp_md_ref_del(), osp_md_write(), osp_object_assign_fid(), osp_object_create(), osp_object_truncate(), osp_sync_add(), osp_sync_process_record(), osp_xattr_del(), osp_xattr_get(), osp_xattr_set(), out_create_pack(), out_handle(), out_index_lookup(), out_obj_destroy(), out_obj_index_delete(), out_obj_index_insert(), out_tx_attr_set_exec(), out_tx_attr_set_undo(), out_tx_create_exec(), out_tx_write_exec(), out_tx_xattr_del_exec(), out_tx_xattr_set_exec(), out_xattr_get(), out_xattr_set_add_exec(), qmt_dqacq0(), qmt_pool_new_conn(), qmt_slv_read(), qmt_slv_write(), qmt_trans_start_with_slv(), update_is_committed(), update_records_create_pack(), vvp_io_fini(), vvp_io_init(), vvp_pgcache_show(), vvp_prep_size(), and vvp_prune().
struct lu_object* lu_object_find (const struct lu_env * env, struct lu_device * dev, const struct lu_fid * f, const struct lu_object_conf * conf) [read]
Search cache for an object with the fid f.
If such object is found, return it. Otherwise, create new object, insert it into cache and return it. In any case, additional reference is acquired on the returned object.
Definition at line 643 of file lu_object.c.
References lu_device::ld_site, lu_site::ls_top_dev, and lu_object_find_at().
Referenced by lu_object_find_slice(), mdo_locate(), mdt_object_find(), mdt_object_new(), ofd_object_find(), and tgt_mdt_body_unpack().
struct lu_object* lu_object_find_at (const struct lu_env * env, struct lu_device * dev, const struct lu_fid * f, const struct lu_object_conf * conf) [read]
Much like lu_object_find(), but top level device of object is specifically dev rather than top level device of the site.
This interface allows objects of different "stacking" to be created within the same site.
Definition at line 778 of file lu_object.c.
References lu_device::ld_site, LOC_F_NOWAIT, lu_object_conf::loc_flags, lu_site_bkt_data::lsb_marche_funebre, lu_object_find_try(), and lu_site_bkt_from_fid().
Referenced by dt_locate_at(), lod_initialize_objects(), lov_sub_find(), lu_object_find(), and osd_object_find().
struct lu_object* lu_object_find_slice (const struct lu_env * env, struct lu_device * dev, const struct lu_fid * f, const struct lu_object_conf * conf) [read]
Find object with given fid, and return its slice belonging to given device.
Definition at line 808 of file lu_object.c.
References lu_device::ld_type, lu_object::lo_header, lu_object_find(), lu_object_locate(), lu_object_put(), and unlikely.
Referenced by cl_object_find(), lfsck_object_find_by_dev(), lfsck_object_find_by_dev_nowait(), md_object_find_slice(), and osp_thandle_invalidate_object().
void lu_object_fini (struct lu_object * o)
Finalize object and release its resources.
Definition at line 1259 of file lu_object.c.
References LASSERT, lu_device::ld_reference, list_empty(), lu_object::lo_dev, lu_object::lo_dev_ref, lu_object::lo_linkage, lu_device_put(), and lu_ref_del_at().
Referenced by dt_object_fini(), echo_object_free(), lod_object_free(), lov_object_free(), lovsub_object_free(), mdd_object_free(), mdt_object_free(), ofd_object_free(), osc_object_free(), and vvp_object_free().
static void lu_object_get (struct lu_object * o) [inline, static]
Acquire additional reference to the given object.
This function is used to attain additional reference. To acquire initial reference use lu_object_find().
Definition at line 709 of file lu_object.h.
References LASSERT, lu_object::lo_header, and lu_object_header::loh_ref.
Referenced by cl_object_get(), lfsck_object_get(), lfsck_register(), lfsck_verify_lpf(), lfsck_verify_lpf_pairs(), llog_osd_dir_get(), llog_test_8(), lquota_disk_dir_find_create(), mdd_object_get(), mdt_object_get(), ofd_add_inconsistency_item(), osd_bufs_get(), osd_index_it_init(), osd_it_acct_init(), osd_it_ea_init(), osd_it_iam_init(), osp_update_callback_init(), out_attr_set_add_exec(), out_create_add_exec(), out_destroy_add_exec(), out_index_delete_add_exec(), out_index_insert_add_exec(), out_ref_add_add_exec(), out_ref_del_add_exec(), out_write_add_exec(), out_xattr_del_add_exec(), out_xattr_set_add_exec(), and tsi2mdt_info().
void lu_object_header_fini (struct lu_object_header * h)
Finalize compound object.
Definition at line 1316 of file lu_object.c.
References hlist_unhashed(), LASSERT, list_empty(), lu_object_header::loh_hash, lu_object_header::loh_layers, lu_object_header::loh_lru, lu_object_header::loh_reference, and lu_ref_fini().
Referenced by cl_object_header_fini(), echo_object_free(), lovsub_object_free(), ls_object_free(), mdt_object_free(), mgs_object_free(), ofd_object_free(), osp_object_free(), and vvp_object_free().
int lu_object_header_init (struct lu_object_header * h)
Initialize compound object.
Definition at line 1301 of file lu_object.c.
References INIT_HLIST_NODE, INIT_LIST_HEAD, lu_object_header::loh_hash, lu_object_header::loh_layers, lu_object_header::loh_lru, lu_object_header::loh_ref, lu_object_header::loh_reference, and lu_ref_init().
Referenced by cl_object_header_init(), ls_object_alloc(), mdt_object_alloc(), mgs_object_alloc(), ofd_object_alloc(), and osp_object_alloc().
void lu_object_header_print (const struct lu_env * env, void * cookie, lu_printer_t printer, const struct lu_object_header * hdr)
Print object header.
Definition at line 525 of file lu_object.c.
References DFID, hlist_unhashed(), list_empty(), lu_object_header::loh_flags, LOHA_EXISTS, and PFID.
Referenced by lu_object_print(), and lu_site_obj_print().
int lu_object_init (struct lu_object * o, struct lu_object_header * h, struct lu_device * d)
Initialize object o that is part of compound object h and was created by device d.
Definition at line 1242 of file lu_object.c.
References INIT_LIST_HEAD, lu_device::ld_reference, lu_object::lo_dev, lu_object::lo_dev_ref, lu_object::lo_header, lu_object::lo_linkage, lu_device_get(), and lu_ref_add_at().
Referenced by dt_object_init(), echo_object_alloc(), lov_object_alloc(), lovsub_object_alloc(), mdd_object_alloc(), mdt_object_alloc(), ofd_object_alloc(), osc_object_alloc(), and vvp_object_alloc().
int lu_object_invariant (const struct lu_object * o)
Check object consistency.
Definition at line 573 of file lu_object.c.
References list_for_each_entry, lu_object::lo_header, lu_object::lo_ops, lu_object_header::loh_layers, and lu_object_operations::loo_object_invariant.
static bool lu_object_is_cl (const struct lu_object * o) [inline, static]
Definition at line 1398 of file lu_object.h.
References lu_object::lo_dev, and lu_device_is_cl().
Referenced by lu_object_put().
static int lu_object_is_dying (const struct lu_object_header * h) [inline, static]
Return true of object will not be cached after last reference to it is released.
Definition at line 719 of file lu_object.h.
References lu_object_header::loh_flags, and LU_OBJECT_HEARD_BANSHEE.
Referenced by htable_lookup(), llog_osd_exist(), lu_object_put(), mdt_reint_unlink(), ofd_object_exists(), osd_object_destroy(), osd_object_ref_del(), and vvp_pgcache_obj_get().
struct lu_object* lu_object_locate (struct lu_object_header * h, const struct lu_device_type * dtype) [read]
Given a compound object, find its slice, corresponding to the device type dtype.
Definition at line 1329 of file lu_object.c.
References lu_device::ld_type, list_for_each_entry, lu_object::lo_dev, lu_object::lo_linkage, and lu_object_header::loh_layers.
Referenced by cl_inode2vvp(), lfsck_layout_repair_multiple_references(), lfsck_object_locate(), lod_initialize_objects(), lod_qos_declare_object_on(), lov_init_sub(), lov_read_and_clear_async_rc(), lu_object_find_slice(), mdo_locate(), mdt_obj2dt(), osd_object_find(), and vvp_pgcache_obj().
static struct lu_object* lu_object_next (const struct lu_object * o) [static, read]
Next sub-object in the layering.
Definition at line 762 of file lu_object.h.
References lu_object::lo_linkage, and list_head::next.
Referenced by cl_object_next(), dt_object_child(), lod_object_child(), mdd_object_child(), mdt_object_child(), mgs_object_child(), ofd_object_child(), and osp_object_child().
static const struct lu_device_operations* lu_object_ops (const struct lu_object * o) [static, read]
return device operations vector for this object
Definition at line 779 of file lu_object.h.
References lu_device::ld_ops, and lu_object::lo_dev.
void lu_object_print (const struct lu_env * env, void * cookie, lu_printer_t printer, const struct lu_object * o)
Print human readable representation of the o to the printer.
Definition at line 542 of file lu_object.c.
References lu_device::ld_type, lu_device_type::ldt_name, list_for_each_entry, lu_object::lo_dev, lu_object::lo_header, lu_object::lo_ops, lu_object_header::loh_layers, lu_object_operations::loo_object_print, and lu_object_header_print().
Referenced by lov_print_raid0(), and lu_site_obj_print().
void lu_object_put (const struct lu_env * env, struct lu_object * o)
Decrease reference counter on object.
If last reference is freed, return object to the cache, unless lu_object_is_dying(o) holds. In the latter case, free object immediately.
Definition at line 97 of file lu_object.c.
References CDEBUG, cfs_hash_bd_dec_and_lock(), cfs_hash_bd_del_locked(), cfs_hash_bd_extra_get(), cfs_hash_bd_get(), cfs_hash_bd_unlock(), D_INODE, fid_is_zero(), LASSERT, lu_device::ld_site, list_add_tail(), list_empty(), list_for_each_entry_reverse, lu_object::lo_dev, lu_object::lo_header, lu_object::lo_ops, lu_object_header::loh_fid, lu_object_header::loh_flags, lu_object_header::loh_hash, lu_object_header::loh_layers, lu_object_header::loh_lru, lu_object_header::loh_ref, lu_object_operations::loo_object_release, lprocfs_counter_incr(), lu_site::ls_obj_hash, lu_site::ls_stats, lu_site_bkt_data::lsb_lru, lu_site_bkt_data::lsb_lru_len, lu_site_bkt_data::lsb_marche_funebre, lu_object_exists, lu_object_fid(), lu_object_free(), lu_object_is_cl(), lu_object_is_dying(), LU_OBJECT_UNHASHED, LU_SS_LRU_LEN, hlist_node::next, and hlist_node::pprev.
Referenced by acct_obj_lookup(), cl_object_put(), distribute_txn_commit_batchid_init(), distribute_txn_fini(), distribute_txn_replay_handle(), dt_find_entry(), dt_find_or_create(), dt_index_read(), dt_store_open(), fld_index_fini(), fld_index_init(), lfsck_object_put(), llog_osd_close(), llog_osd_create(), llog_osd_declare_create(), llog_osd_declare_destroy(), llog_osd_destroy(), llog_osd_dir_get(), llog_osd_get_cat_list(), llog_osd_get_regular_fid_dir(), llog_osd_open(), llog_osd_put_cat_list(), llog_osd_regular_fid_add_name_entry(), llog_osd_regular_fid_del_name_entry(), llog_test_8(), lod_alloc_qos(), lod_initialize_objects(), lod_object_free_striping(), lod_prep_md_striped_create(), lod_prepare(), lod_qos_declare_object_on(), lod_qos_prep_create(), lquota_disk_dir_find_create(), lquota_disk_glb_find_create(), lquota_disk_slv_find(), lquota_disk_slv_find_create(), lquotactl_slv(), lu_object_find_slice(), lu_object_put_nocache(), mdd_local_file_create(), mdd_object_put(), mdt_object_put(), mgc_fs_setup(), mgs_fs_cleanup(), mgs_fs_setup(), nidtbl_read_version(), nidtbl_update_version(), nm_config_file_deregister(), ofd_fs_cleanup(), ofd_inconsistency_verification_main(), ofd_inconsistency_verify_one(), ofd_object_put(), ofd_seq_put(), orph_index_fini(), orph_index_init(), osd_bufs_put(), osd_index_it_fini(), osd_it_acct_fini(), osd_it_ea_fini(), osd_it_iam_fini(), osd_object_find(), osd_object_put(), osd_quota_migration(), osp_find_or_create_local_file(), osp_init_last_objid(), osp_init_last_seq(), osp_last_used_fini(), osp_last_used_init(), osp_thandle_invalidate_object(), osp_update_callback_fini(), out_handle(), out_trans_stop(), qmt_device_prepare(), qmt_dqacq0(), qmt_lvbo_free(), qmt_lvbo_init(), qmt_pool_free(), qmt_pool_new_conn(), qsd_fini(), qsd_qtype_fini(), quota_obj_lookup(), seq_store_fini(), tgt_blocking_ast(), tgt_fini(), tgt_init(), tgt_mdt_body_unpack(), tgt_request_handle(), update_recovery_exec(), and vvp_pgcache_obj().
void lu_object_put_nocache (const struct lu_env * env, struct lu_object * o)
Put object and don't keep in cache.
This is temporary solution for multi-site objects when its layering is not constant.
Definition at line 193 of file lu_object.c.
References lu_object::lo_header, lu_object_header::loh_flags, LU_OBJECT_HEARD_BANSHEE, and lu_object_put().
Referenced by __local_file_create(), lastid_compat_check(), lfsck_layout_repair_multiple_references(), lfsck_layout_scan_orphan_one(), llog_osd_close(), local_file_find_or_create_with_fid(), local_index_find_or_create_with_fid(), local_object_unlink(), local_oid_storage_fini(), local_oid_storage_init(), lquota_disk_dir_find_create(), lquota_disk_find_create(), mdd_local_file_create(), mgc_fs_cleanup(), and mgc_fs_setup().
static void lu_object_ref_add (struct lu_object * o, const char * scope, const void * source) [inline, static]
Definition at line 866 of file lu_object.h.
References lu_object::lo_header, lu_object_header::loh_reference, and lu_ref_add().
Referenced by cl_file_inode_init(), lov_init_sub(), and vvp_pgcache_obj().
static void lu_object_ref_add_at (struct lu_object * o, struct lu_ref_link * link, const char * scope, const void * source) [inline, static]
Definition at line 873 of file lu_object.h.
References lu_object::lo_header, lu_object_header::loh_reference, and lu_ref_add_at().
Referenced by cl_page_alloc(), and osc_check_rpcs().
static void lu_object_ref_del (struct lu_object * o, const char * scope, const void * source) [inline, static]
Definition at line 881 of file lu_object.h.
References lu_object::lo_header, lu_object_header::loh_reference, and lu_ref_del().
Referenced by cl_inode_fini(), lov_subobject_kill(), vvp_pgcache_find(), and vvp_pgcache_show().
static void lu_object_ref_del_at (struct lu_object * o, struct lu_ref_link * link, const char * scope, const void * source) [inline, static]
Definition at line 887 of file lu_object.h.
References lu_object::lo_header, lu_object_header::loh_reference, and lu_ref_del_at().
Referenced by cl_page_free(), and osc_check_rpcs().
static struct lu_object* lu_object_top (struct lu_object_header * h) [static, read]
First (topmost) sub-object of given compound object.
Definition at line 753 of file lu_object.h.
References LASSERT, list_empty(), lu_object::lo_linkage, lu_object_header::loh_layers, and list_head::next.
Referenced by cl_object_glimpse(), cl_object_top(), htable_lookup(), lu_site_obj_print(), lu_site_purge(), and vvp_pgcache_obj().
void lu_object_unhash (const struct lu_env * env, struct lu_object * o)
Kill the object and take it out of LRU cache.
Currently used by client code for layout change.
Definition at line 204 of file lu_object.c.
References cfs_hash_bd_del_locked(), cfs_hash_bd_extra_get(), cfs_hash_bd_get_and_lock(), cfs_hash_bd_unlock(), lu_device::ld_site, list_del_init(), list_empty(), lu_object::lo_dev, lu_object::lo_header, lu_object_header::loh_fid, lu_object_header::loh_flags, lu_object_header::loh_hash, lu_object_header::loh_lru, lprocfs_counter_decr(), lu_site::ls_obj_hash, lu_site::ls_stats, lu_site_bkt_data::lsb_lru_len, LU_OBJECT_HEARD_BANSHEE, LU_OBJECT_UNHASHED, and LU_SS_LRU_LEN.
Referenced by lov_init_sub().
void lu_session_tags_clear (__u32 tags)
Definition at line 1860 of file lu_object.c.
Referenced by echo_client_cleanup().
void lu_session_tags_update (__u32 tags)
Definition at line 1851 of file lu_object.c.
Referenced by echo_client_setup().
static struct seq_server_site* lu_site2seq (const struct lu_site * s) [static, read]
Definition at line 661 of file lu_object.h.
References lu_site::ld_seq_site.
Referenced by echo_device_alloc(), fid_is_local(), fld_handle_lookup(), fld_handle_read(), lfsck_dev_site(), lod_declare_object_create(), lod_fld_lookup(), lod_object_init(), lod_prep_md_striped_create(), lod_prepare(), lod_prepare_distribute_txn(), seq_server_handle(), and update_is_committed().
static struct lu_site_bkt_data* lu_site_bkt_from_fid (struct lu_site * site, struct lu_fid * fid) [static, read]
Definition at line 653 of file lu_object.h.
References cfs_hash_bd_extra_get(), cfs_hash_bd_get(), and lu_site::ls_obj_hash.
Referenced by cl_object_put_last(), lov_subobject_kill(), lu_object_find_at(), and lu_object_free().
void lu_site_fini (struct lu_site * s)
Finalize s and release its resources.
Definition at line 1140 of file lu_object.c.
References cfs_hash_putref(), lu_device::ld_reference, lu_device::ld_site, list_del_init(), lprocfs_free_stats(), lu_site::ls_linkage, lu_site::ls_obj_hash, lu_site::ls_stats, lu_site::ls_top_dev, lu_device_put(), and lu_ref_del().
Referenced by cl_site_fini(), echo_site_fini(), osd_device_free(), and osd_device_init0().
int lu_site_init (struct lu_site * s, struct lu_device * d)
Initialize site s, with d as the top level device.
Definition at line 1058 of file lu_object.c.
References CERROR, CFS_HASH_ASSERT_EMPTY, cfs_hash_bd_extra_get(), CFS_HASH_COUNTER, cfs_hash_create(), CFS_HASH_DEPTH, cfs_hash_for_each_bucket, CFS_HASH_NO_ITEMREF, cfs_hash_putref(), CFS_HASH_SPIN_BKTLOCK, ENTRY, INIT_LIST_HEAD, lu_device::ld_reference, lu_device::ld_site, lu_device::ld_type, lu_device_type::ldt_name, lprocfs_alloc_stats(), LPROCFS_CNTR_AVGMINMAX, lprocfs_counter_init(), lu_site::ls_ld_linkage, lu_site::ls_ld_lock, lu_site::ls_linkage, lu_site::ls_obj_hash, lu_site::ls_purge_mutex, lu_site::ls_stats, lu_site::ls_top_dev, lu_site_bkt_data::lsb_lru, lu_site_bkt_data::lsb_marche_funebre, lu_dev_add_linkage(), lu_device_get(), lu_htable_order(), lu_ref_add(), LU_SITE_BITS_MIN, LU_SITE_BKT_BITS, LU_SS_CACHE_DEATH_RACE, LU_SS_CACHE_HIT, LU_SS_CACHE_MISS, LU_SS_CACHE_RACE, LU_SS_CREATED, LU_SS_LAST_STAT, LU_SS_LRU_LEN, LU_SS_LRU_PURGED, name, and RETURN.
Referenced by cl_site_init(), cl_type_setup(), lovsub_device_init(), lu_stack_fini(), osd_device_init0(), osd_mount(), and vvp_device_init().
int lu_site_init_finish (struct lu_site * s)
Called when initialization of stack for this site is completed.
Definition at line 1166 of file lu_object.c.
References lu_env::le_ctx, list_add(), lu_site::ls_linkage, lu_context_refill(), lu_shrink_env, and lu_sites.
Referenced by echo_site_init(), osd_device_init0(), osd_mount(), and vvp_device_alloc().
void lu_site_print (const struct lu_env * env, struct lu_site * s, void * cookie, lu_printer_t printer)
Print all objects in s.
Definition at line 905 of file lu_object.c.
References cfs_hash_for_each(), lu_site::ls_obj_hash, lu_site_print_arg::lsp_env, lu_site_obj_print(), and lu_site_print().
Referenced by lovsub_device_free(), lu_site_print(), lwp_device_free(), mgs_device_fini(), mgs_init0(), ofd_stack_fini(), osd_device_free(), and osp_device_free().
int lu_site_purge (const struct lu_env * env, struct lu_site * s, int nr)
Free nr objects from the cold end of the site LRU list.
Definition at line 352 of file lu_object.c.
References cfs_hash_bd::bd_bucket, cfs_hash_bd_del_locked(), cfs_hash_bd_extra_get(), cfs_hash_bd_get(), cfs_hash_bd_lock(), cfs_hash_bd_unlock(), cfs_hash_for_each_bucket, CFS_HASH_NBKT, INIT_LIST_HEAD, LASSERT, list_del_init(), list_empty(), list_for_each_entry_safe, list_move(), lu_object_header::loh_fid, lu_object_header::loh_hash, lu_object_header::loh_lru, lu_object_header::loh_ref, lprocfs_counter_decr(), lprocfs_counter_incr(), lu_site::ls_obj_hash, lu_site::ls_purge_mutex, lu_site::ls_purge_start, lu_site::ls_stats, lu_site_bkt_data::lsb_lru, lu_site_bkt_data::lsb_lru_len, lu_object_free(), lu_object_top(), LU_SS_LRU_LEN, LU_SS_LRU_PURGED, list_head::next, OBD_FAIL_CHECK, OBD_FAIL_OBD_NO_LRU, RETURN, and start.
Referenced by arc_prune_func(), echo_device_free(), ls_device_put(), lu_cache_shrink_scan(), lu_object_limit(), lu_stack_fini(), mdd_device_shutdown(), mdt_stack_fini(), mgs_device_fini(), mgs_init0(), ofd_stack_fini(), and osd_device_free().
int lu_site_stats_seq_print (const struct lu_site * s, struct seq_file * m)
Output site statistical counters into a buffer.
Suitable for ll_rd_*()-style functions.
Suitable for lprocfs_rd_*()-style functions.
Definition at line 2224 of file lu_object.c.
References CFS_HASH_NHLIST, lu_site::ls_obj_hash, lu_site::ls_stats, ls_stats_read(), lu_site_stats::lss_busy, lu_site_stats::lss_max_search, lu_site_stats::lss_populated, lu_site_stats::lss_total, lu_site_stats_get(), LU_SS_CACHE_DEATH_RACE, LU_SS_CACHE_HIT, LU_SS_CACHE_MISS, LU_SS_CACHE_RACE, LU_SS_CREATED, LU_SS_LRU_LEN, and LU_SS_LRU_PURGED.
Referenced by cl_site_stats_print(), and mdt_site_stats_seq_show().
void lu_stack_fini (const struct lu_env * env, struct lu_device * top)
Finalize and free devices in the device stack.
Finalize device stack by purging object cache, and calling lu_device_type_operations::ldto_device_fini() and lu_device_type_operations::ldto_device_free() on all devices in the stack.
Definition at line 1349 of file lu_object.c.
References class_put_type(), lu_device::ld_reference, lu_device::ld_site, lu_device::ld_type, lu_device_type::ldt_obd_type, lu_device_type::ldt_ops, lu_device_type_operations::ldto_device_fini, lu_device_type_operations::ldto_device_free, lu_device_put(), lu_ref_del(), lu_site_init(), lu_site_purge(), and obd_type::typ_refcnt.
Referenced by cl_stack_fini().
Variable Documentation
struct lu_buf LU_BUF_NULL
null buffer
Definition at line 2333 of file lu_object.c.
Referenced by __lfsck_links_read(), fid_is_for_ostobj(), lfsck_layout_check_parent(), lfsck_layout_get_lovea(), lfsck_layout_recreate_lovea(), lfsck_namespace_replace_cond(), ll_getparent(), lod_get_ea(), mdd_create_data(), mdd_declare_attr_set(), mdd_get_lov_ea(), mdd_migrate_xattrs(), mdt_attr_get_eabuf_size(), mdt_big_xattr_get(), mdt_getxattr_pack_reply(), mdt_lvbo_fill(), mdt_rmtlsetfacl(), mdt_thread_info_init(), and osd_find_parent_fid().
__u32 lu_context_tags_default
lu_ctx_tags/lu_ses_tags will be updated if there are new types of obd being added.
Currently, this is only used on client side, specifically for echo device client, for other stack (like ptlrpc threads), context are predefined when the lu_device type are registered, during the module probe phase.
Definition at line 1830 of file lu_object.c.
Referenced by cl_env_obtain().
__u32 lu_session_tags_default
Definition at line 1831 of file lu_object.c.
Referenced by cl_env_obtain().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.