Lustre: Miscellaneous operations.
Miscellaneous operations.
[LNet]
Miscellaneous operations.
Functions
int LNetSetLazyPortal (int portal)
Turn on the lazy portal attribute.
int LNetClearLazyPortal (int portal)
Turn off the lazy portal attribute.
int LNetCtl (unsigned int cmd, void *arg)
LNet ioctl handler.
void LNetDebugPeer (lnet_process_id_t id)
Detailed Description
Miscellaneous operations.
Function Documentation
int LNetClearLazyPortal (int portal)
Turn off the lazy portal attribute.
Delayed requests on the portal, if any, will be all dropped when this function returns.
Parameters:
portal Index of the portal to disable the lazy attribute on.
Return values:
0 On success.
-EINVAL If portal is not a valid index.
Definition at line 977 of file lib-ptl.c.
References lnet_clear_lazy_portal().
Referenced by lnet_shutdown_lndnis(), ptlrpc_service_unlink_rqbd(), and srpc_shutdown().
int LNetCtl (unsigned int cmd, void * arg)
LNet ioctl handler.
Definition at line 1908 of file api-ni.c.
References __user, lnet_ioctl_config_data::cfg_buffers, lnet_ioctl_config_data::cfg_bulk, lnet_ioctl_config_data::cfg_config_u, lnet_ioctl_config_data::cfg_count, lnet_ioctl_config_data::cfg_hdr, lnet_ioctl_config_data::cfg_net, lnet_ioctl_config_data::cfg_nid, lnet_ioctl_config_data::cfg_route, cfs_time_current(), cfs_time_current_sec(), cfs_time_seconds(), CLASSERT, libcfs_ioctl_data::ioc_count, libcfs_ioctl_data::ioc_flags, libcfs_ioctl_hdr::ioc_len, IOC_LIBCFS_ADD_BUF, IOC_LIBCFS_ADD_ROUTE, IOC_LIBCFS_CONFIG_RTR, IOC_LIBCFS_DEL_ROUTE, IOC_LIBCFS_FAIL_NID, IOC_LIBCFS_GET_BUF, IOC_LIBCFS_GET_LNET_STATS, IOC_LIBCFS_GET_NET, IOC_LIBCFS_GET_NI, IOC_LIBCFS_GET_PEER_INFO, IOC_LIBCFS_GET_ROUTE, IOC_LIBCFS_LNET_DIST, IOC_LIBCFS_LNET_FAULT, IOC_LIBCFS_NOTIFY_ROUTER, IOC_LIBCFS_PING, IOC_LIBCFS_TESTPROTOCOMPAT, libcfs_ioctl_data::ioc_net, libcfs_ioctl_data::ioc_nid, libcfs_ioctl_data::ioc_pbuf1, libcfs_ioctl_data::ioc_plen1, libcfs_ioctl_data::ioc_u32, libcfs_ioctl_data::ioc_u64, LIBCFS_IOC_DATA_MAX, lnet_t::ln_api_mutex, lnet_t::ln_testprotocompat, lnet_lnd::lnd_ctl, lnet_add_route(), lnet_check_routes(), lnet_counters_get(), lnet_del_route(), lnet_fail_nid(), lnet_fault_ctl(), lnet_get_net_config(), lnet_get_peer_info(), lnet_get_route(), lnet_get_rtr_pool_cfg(), LNET_LOCK_EX, lnet_net2ni(), lnet_net_lock(), lnet_net_unlock(), lnet_ni_decref(), lnet_notify(), lnet_ping(), lnet_rtrpools_adjust(), lnet_rtrpools_disable(), lnet_rtrpools_enable(), LNetDist(), LNetGetId(), lnet_ni::ni_lnd, lnet_ioctl_peer::pr_count, lnet_ioctl_peer::pr_hdr, lnet_ioctl_peer::pr_lnd_u, lnet_ioctl_peer::pr_nid, lnet_ioctl_peer::pr_peer_credits, lnet_ioctl_config_data::rtr_priority, lnet_ioctl_lnet_stats::st_cntrs, and lnet_ioctl_lnet_stats::st_hdr.
Referenced by lnet_ioctl().
void LNetDebugPeer (lnet_process_id_t id)
Definition at line 2111 of file api-ni.c.
References lnet_debug_peer().
Referenced by ptlrpc_expire_one_request().
int LNetSetLazyPortal (int portal)
Turn on the lazy portal attribute.
Use with caution!
This portal attribute only affects incoming PUT requests to the portal, and is off by default. By default, if there's no matching MD for an incoming PUT request, it is simply dropped. With the lazy attribute on, such requests are queued indefinitely until either a matching MD is posted to the portal or the lazy attribute is turned off.
It would prevent dropped requests, however it should be regarded as the last line of defense - i.e. users must keep a close watch on active buffers on a lazy portal and once it becomes too low post more buffers as soon as possible. This is because delayed requests usually have detrimental effects on underlying network connections. A few delayed requests often suffice to bring an underlying connection to a complete halt, due to flow control mechanisms.
There's also a DOS attack risk. If users don't post match-all MDs on a lazy portal, a malicious peer can easily stop a service by sending some PUT requests with match bits that won't match any MD. A routed server is especially vulnerable since the connections to its neighbor routers are shared among all clients.
Parameters:
portal Index of the portal to enable the lazy attribute on.
Return values:
0 On success.
-EINVAL If portal is not a valid index.
Definition at line 896 of file lib-ptl.c.
References CDEBUG, D_NET, lnet_t::ln_nportals, lnet_t::ln_portals, LNET_LOCK_EX, LNET_PTL_LAZY, lnet_ptl_lock, lnet_ptl_setopt(), lnet_ptl_unlock, lnet_res_lock(), lnet_res_unlock(), and the_lnet.
Referenced by ptlrpc_register_service(), and srpc_startup().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.