Lustre: Data movement operations
Data movement operations
[LNet]
The LNet API provides two data movement operations: LNetPut() and LNetGet().
Enumerations
enum lnet_ack_req_t { LNET_ACK_REQ, LNET_NOACK_REQ }
Specify whether an acknowledgment should be sent by target when the PUT operation completes (i.e., when the data has been written to a MD of the target process).
Functions
int LNetPut (lnet_nid_t self, lnet_handle_md_t md_in, lnet_ack_req_t ack_req_in, lnet_process_id_t target_in, unsigned int portal_in, __u64 match_bits_in, unsigned int offset_in, __u64 hdr_data_in)
Initiate an asynchronous PUT operation.
int LNetGet (lnet_nid_t self, lnet_handle_md_t md_in, lnet_process_id_t target_in, unsigned int portal_in, __u64 match_bits_in, unsigned int offset_in)
Initiate an asynchronous GET operation.
Detailed Description
The LNet API provides two data movement operations: LNetPut() and LNetGet().
Enumeration Type Documentation
enum lnet_ack_req_t
Specify whether an acknowledgment should be sent by target when the PUT operation completes (i.e., when the data has been written to a MD of the target process).
See also:
lnet_md_t::options for the discussion on LNET_MD_ACK_DISABLE by which acknowledgments can be disabled for a MD.
Enumerator:
LNET_ACK_REQ
Request an acknowledgment.
LNET_NOACK_REQ
Request that no acknowledgment should be generated.
Definition at line 643 of file types.h.
Function Documentation
int LNetGet (lnet_nid_t self, lnet_handle_md_t mdh, lnet_process_id_t target, unsigned int portal, __u64 match_bits, unsigned int offset)
Initiate an asynchronous GET operation.
On the initiator node, an LNET_EVENT_SEND is logged when the GET request is sent, and an LNET_EVENT_REPLY is logged when the data returned from the target node in the REPLY has been written to local MD.
On the target node, an LNET_EVENT_GET is logged when the GET request arrives and is accepted into a MD.
Parameters:
self,target,portal,match_bits,offset See the discussion in LNetPut().
mdh A handle for the MD that describes the memory into which the requested data will be received. The MD must be "free floating" (See LNetMDBind()).
Return values:
0 Success, and only in this case events will be generated and logged to EQ (if it exists) of the MD.
-EIO Simulated failure.
-ENOMEM Memory allocation failure.
-ENOENT Invalid MD object.
Definition at line 2368 of file lib-move.c.
References CDEBUG, CERROR, CNETERR, lnet_handle_any_t::cookie, cpu_to_le32, cpu_to_le64, D_NET, fail_peer(), LASSERT, lnet_libhandle::lh_cookie, libcfs_id2str(), list_empty(), lnet_t::ln_interface_cookie, lnet_t::ln_refcount, lnet_t::ln_test_peers, lnet_build_msg_event(), lnet_cpt_of_cookie(), LNET_EVENT_SEND, lnet_finalize(), lnet_handle2md(), lnet_msg_alloc(), lnet_msg_attach_md(), lnet_msg_free(), LNET_MSG_GET, LNET_NID_ANY, lnet_prep_send(), lnet_res_lock(), lnet_res_unlock(), lnet_send(), LPU64, lnet_libmd::md_length, lnet_libmd::md_lh, lnet_libmd::md_me, lnet_libmd::md_threshold, lnet_me::me_portal, msg, lnet_msg::msg_hdr, lnet_process_id_t::nid, and the_lnet.
Referenced by lnet_ping(), lnet_ping_router_locked(), and srpc_post_active_rdma().
int LNetPut (lnet_nid_t self, lnet_handle_md_t mdh, lnet_ack_req_t ack, lnet_process_id_t target, unsigned int portal, __u64 match_bits, unsigned int offset, __u64 hdr_data)
Initiate an asynchronous PUT operation.
There are several events associated with a PUT: completion of the send on the initiator node (LNET_EVENT_SEND), and when the send completes successfully, the receipt of an acknowledgment (LNET_EVENT_ACK) indicating that the operation was accepted by the target. The event LNET_EVENT_PUT is used at the target node to indicate the completion of incoming data delivery.
The local events will be logged in the EQ associated with the MD pointed to by mdh handle. Using a MD without an associated EQ results in these events being discarded. In this case, the caller must have another mechanism (e.g., a higher level protocol) for determining when it is safe to modify the memory region associated with the MD.
Note that LNet does not guarantee the order of LNET_EVENT_SEND and LNET_EVENT_ACK, though intuitively ACK should happen after SEND.
Parameters:
self Indicates the NID of a local interface through which to send the PUT request. Use LNET_NID_ANY to let LNet choose one by itself.
mdh A handle for the MD that describes the memory to be sent. The MD must be "free floating" (See LNetMDBind()).
ack Controls whether an acknowledgment is requested. Acknowledgments are only sent when they are requested by the initiating process and the target MD enables them.
target A process identifier for the target process.
portal The index in the target's portal table.
match_bits The match bits to use for MD selection at the target process.
offset The offset into the target MD (only used when the target MD has the LNET_MD_MANAGE_REMOTE option set).
hdr_data 64 bits of user data that can be included in the message header. This data is written to an event queue entry at the target if an EQ is present on the matching MD.
Return values:
0 Success, and only in this case events will be generated and logged to EQ (if it exists).
-EIO Simulated failure.
-ENOMEM Memory allocation failure.
-ENOENT Invalid MD object.
See also:
lnet_event_t::hdr_data and lnet_event_kind_t.
Definition at line 2169 of file lib-move.c.
References CDEBUG, CERROR, CNETERR, lnet_handle_any_t::cookie, cpu_to_le32, cpu_to_le64, D_NET, fail_peer(), LASSERT, lnet_libhandle::lh_cookie, libcfs_id2str(), list_empty(), lnet_t::ln_interface_cookie, lnet_t::ln_refcount, lnet_t::ln_test_peers, LNET_ACK_REQ, lnet_build_msg_event(), lnet_cpt_of_cookie(), LNET_EVENT_SEND, lnet_finalize(), lnet_handle2md(), lnet_msg_alloc(), lnet_msg_attach_md(), lnet_msg_free(), LNET_MSG_PUT, LNET_NID_ANY, lnet_prep_send(), lnet_res_lock(), lnet_res_unlock(), lnet_send(), LNET_WIRE_HANDLE_COOKIE_NONE, LPU64, lnet_libmd::md_length, lnet_libmd::md_lh, lnet_libmd::md_me, lnet_libmd::md_threshold, lnet_me::me_portal, memory_pressure_get(), msg, lnet_msg::msg_hdr, lnet_msg::msg_vmflush, lnet_process_id_t::nid, and the_lnet.
Referenced by ptl_send_buf(), and srpc_post_active_rdma().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.