Lustre: param
param
Data Structures
struct cfg_interop_param
Defines
#define PARAM_TIMEOUT "timeout="
#define PARAM_LDLM_TIMEOUT "ldlm_timeout="
#define PARAM_AT_MIN "at_min="
#define PARAM_AT_MAX "at_max="
#define PARAM_AT_EXTRA "at_extra="
#define PARAM_AT_EARLY_MARGIN "at_early_margin="
#define PARAM_AT_HISTORY "at_history="
#define PARAM_JOBID_VAR "jobid_var="
#define PARAM_MGSNODE "mgsnode="
#define PARAM_FAILNODE "failover.node="
#define PARAM_FAILMODE "failover.mode="
#define PARAM_ACTIVE "active="
#define PARAM_NETWORK "network="
#define PARAM_ID_UPCALL "identity_upcall="
#define PARAM_OST "ost."
#define PARAM_OSD "osd."
#define PARAM_OSC "osc."
#define PARAM_MDT "mdt."
#define PARAM_HSM "mdt.hsm."
#define PARAM_MDD "mdd."
#define PARAM_MDC "mdc."
#define PARAM_LLITE "llite."
#define PARAM_LOV "lov."
#define PARAM_LOD "lod."
#define PARAM_OSP "osp."
#define PARAM_SYS "sys."
#define PARAM_SRPC "srpc."
#define PARAM_SRPC_FLVR "srpc.flavor."
#define PARAM_SRPC_UDESC "srpc.udesc.cli2mdt"
#define PARAM_SEC "security."
#define PARAM_QUOTA "quota."
Functions
int class_find_param (char *buf, char *key, char **valp)
struct cfg_interop_param * class_find_old_param (const char *param, struct cfg_interop_param *ptr)
Check whether the proc parameter param is an old parameter or not from the array ptr which contains the mapping from old parameters to new ones.
int class_get_next_param (char **params, char *copy)
Finds a parameter in params and copies it to copy.
int class_match_param (char *buf, const char *key, char **valp)
int class_parse_nid (char *buf, lnet_nid_t *nid, char **endh)
int class_parse_nid_quiet (char *buf, lnet_nid_t *nid, char **endh)
int class_parse_net (char *buf, __u32 *net, char **endh)
int class_match_nid (char *buf, char *key, lnet_nid_t nid)
int class_match_net (char *buf, char *key, __u32 net)
int do_lcfg (char *cfgname, lnet_nid_t nid, int cmd, char *s1, char *s2, char *s3, char *s4)
lustre_cfg_bufs are a holdover from 1.4; we can still set these up from lctl (and do for echo cli/srv.
Define Documentation
#define PARAM_ACTIVE "active="
Definition at line 101 of file lustre_param.h.
Referenced by mgs_write_log_param().
#define PARAM_AT_EARLY_MARGIN "at_early_margin="
Definition at line 95 of file lustre_param.h.
Referenced by class_set_global(), and mgs_write_log_sys().
#define PARAM_AT_EXTRA "at_extra="
Definition at line 94 of file lustre_param.h.
Referenced by class_set_global(), and mgs_write_log_sys().
#define PARAM_AT_HISTORY "at_history="
Definition at line 96 of file lustre_param.h.
Referenced by class_set_global(), and mgs_write_log_sys().
#define PARAM_AT_MAX "at_max="
Definition at line 93 of file lustre_param.h.
Referenced by class_set_global(), and mgs_write_log_sys().
#define PARAM_AT_MIN "at_min="
Definition at line 92 of file lustre_param.h.
Referenced by class_set_global(), and mgs_write_log_sys().
#define PARAM_FAILMODE "failover.mode="
Definition at line 100 of file lustre_param.h.
Referenced by mgs_write_log_mdt0(), mgs_write_log_ost(), and mgs_write_log_param().
#define PARAM_FAILNODE "failover.node="
Definition at line 99 of file lustre_param.h.
Referenced by mgs_check_failover_reg(), mgs_steal_client_llog_handler(), mgs_write_log_failnids(), mgs_write_log_param(), parse_opts(), and server_lsi2mti().
#define PARAM_HSM "mdt.hsm."
Definition at line 110 of file lustre_param.h.
Referenced by mdt_process_config().
#define PARAM_ID_UPCALL "identity_upcall="
Definition at line 103 of file lustre_param.h.
#define PARAM_JOBID_VAR "jobid_var="
Definition at line 97 of file lustre_param.h.
Referenced by class_set_global(), and mgs_write_log_sys().
#define PARAM_LDLM_TIMEOUT "ldlm_timeout="
Definition at line 91 of file lustre_param.h.
Referenced by mgs_write_log_sys().
#define PARAM_LLITE "llite."
Definition at line 113 of file lustre_param.h.
Referenced by class_process_config(), ll_process_config(), mgs_setparam(), and mgs_write_log_param().
#define PARAM_LOD "lod."
Definition at line 115 of file lustre_param.h.
#define PARAM_LOV "lov."
Definition at line 114 of file lustre_param.h.
Referenced by lod_process_config(), lov_process_config_base(), and mgs_write_log_param().
#define PARAM_MDC "mdc."
Definition at line 112 of file lustre_param.h.
Referenced by mdc_process_config(), and mgs_write_log_param().
#define PARAM_MDD "mdd."
Definition at line 111 of file lustre_param.h.
Referenced by mdd_process_config(), and mgs_write_log_param().
#define PARAM_MDT "mdt."
Definition at line 109 of file lustre_param.h.
Referenced by mdt_process_config(), and mgs_write_log_param().
#define PARAM_MGSNODE "mgsnode="
Definition at line 98 of file lustre_param.h.
Referenced by add_mgsnids(), lmd_parse(), lustre_start_mgc(), main(), mgs_write_log_param(), and parse_opts().
#define PARAM_NETWORK "network="
Definition at line 102 of file lustre_param.h.
Referenced by mgs_write_log_param(), parse_opts(), and server_lsi2mti().
#define PARAM_OSC "osc."
Definition at line 108 of file lustre_param.h.
Referenced by mgs_write_log_param(), osc_process_config_base(), and osp_process_config().
#define PARAM_OSD "osd."
Definition at line 107 of file lustre_param.h.
Referenced by mgs_write_log_param(), and osd_process_config().
#define PARAM_OSP "osp."
Definition at line 116 of file lustre_param.h.
Referenced by mgs_write_log_param(), and osp_process_config().
#define PARAM_OST "ost."
Definition at line 106 of file lustre_param.h.
Referenced by match_symlink_param(), mgs_write_log_param(), ofd_process_config(), and osd_process_config().
#define PARAM_QUOTA "quota."
Definition at line 122 of file lustre_param.h.
Referenced by class_process_config(), mgs_write_log_param(), and qsd_process_config().
#define PARAM_SEC "security."
Definition at line 121 of file lustre_param.h.
#define PARAM_SRPC "srpc."
Definition at line 118 of file lustre_param.h.
Referenced by mgs_srpc_set_param_mem(), and mgs_write_log_param().
#define PARAM_SRPC_FLVR "srpc.flavor."
Definition at line 119 of file lustre_param.h.
Referenced by __sptlrpc_process_config(), and mgs_srpc_set_param_mem().
#define PARAM_SRPC_UDESC "srpc.udesc.cli2mdt"
Definition at line 120 of file lustre_param.h.
Referenced by mgs_srpc_set_param_mem(), and mgs_srpc_set_param_udesc_mem().
#define PARAM_SYS "sys."
Definition at line 117 of file lustre_param.h.
Referenced by class_process_config(), and mgs_write_log_param().
#define PARAM_TIMEOUT "timeout="
Definition at line 90 of file lustre_param.h.
Referenced by mgs_write_log_sys().
Function Documentation
struct cfg_interop_param* class_find_old_param (const char * param, struct cfg_interop_param * ptr) [read]
Check whether the proc parameter param is an old parameter or not from the array ptr which contains the mapping from old parameters to new ones.
If it's an old one, then return the pointer to the cfg_interop_param struc- ture which contains both the old and new parameters.
Parameters:
param proc parameter
ptr an array which contains the mapping from old parameters to new ones
Return values:
valid-pointer pointer to the cfg_interop_param structure which contains the old and new parameters
NULL param or ptr is NULL, or param is not an old parameter
Definition at line 95 of file obd_config.c.
References cfg_interop_param::old_param, and RETURN.
Referenced by mdt_process_config(), and ofd_process_config().
int class_find_param (char * buf, char * key, char ** valp)
Definition at line 63 of file obd_config.c.
Referenced by class_match_net(), class_match_nid(), lustre_start_mgc(), mgs_check_failover_reg(), mgs_write_log_failnids(), mgs_write_log_mdt0(), and mgs_write_log_ost().
int class_get_next_param (char ** params, char * copy)
Finds a parameter in params and copies it to copy.
Leading spaces are skipped. Next space or end of string is the parameter terminator with the exception that spaces inside single or double quotes get included into a parameter. The parameter is copied into copy which has to be allocated big enough by a caller, quotes are stripped in the copy and the copy is terminated by 0.
On return params is set to next parameter or to NULL if last parameter is returned.
Return values:
0 if parameter is returned in copy
1 otherwise
-EINVAL if unbalanced quota is found
Definition at line 137 of file obd_config.c.
References CERROR.
Referenced by mgs_write_log_target().
int class_match_net (char * buf, char * key, __u32 net)
Definition at line 313 of file obd_config.c.
References class_find_param(), and class_parse_net().
Referenced by server_lsi2mti().
int class_match_nid (char * buf, char * key, lnet_nid_t nid)
Definition at line 296 of file obd_config.c.
References class_find_param(), and class_parse_nid().
Referenced by server_lsi2mti().
int class_match_param (char * buf, const char * key, char ** valp)
Definition at line 190 of file obd_config.c.
Referenced by class_process_config(), class_process_proc_param(), class_set_global(), match_symlink_param(), mgs_write_log_param(), mgs_write_log_quota(), mgs_write_log_sys(), and qsd_process_config().
int class_parse_net (char * buf, __u32 * net, char ** endh)
Definition at line 287 of file obd_config.c.
References CLASS_PARSE_NET, and class_parse_value().
Referenced by class_match_net().
int class_parse_nid (char * buf, lnet_nid_t * nid, char ** endh)
Definition at line 275 of file obd_config.c.
References CLASS_PARSE_NID, and class_parse_value().
Referenced by class_match_nid(), lustre_start_mgc(), mgs_write_log_failnids(), and process_command().
int class_parse_nid_quiet (char * buf, lnet_nid_t * nid, char ** endh)
Definition at line 281 of file obd_config.c.
References CLASS_PARSE_NID, and class_parse_value().
Referenced by lmd_parse_mgs(), lustre_start_mgc(), and mgs_check_failover_reg().
int do_lcfg (char * cfgname, lnet_nid_t nid, int cmd, char * s1, char * s2, char * s3, char * s4)
lustre_cfg_bufs are a holdover from 1.4; we can still set these up from lctl (and do for echo cli/srv.
Definition at line 158 of file obd_mount.c.
References CDEBUG, class_process_config(), D_TRACE, lustre_cfg::lcfg_nid, lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), and lustre_cfg_new().
Referenced by lustre_start_mgc(), lustre_start_simple(), and lustre_stop_mgc().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.