Lustre: md
md
Sub-class of lu_object with methods common for "meta-data" objects in MDT stack.
Data Structures
struct md_hsm
struct md_attr
struct md_op_spec
Additional parameters for create.
struct md_object_operations
Operations implemented for each md object (both directory and leaf).
struct md_dir_operations
Operations implemented for each directory object.
struct md_device_operations
struct md_device
struct md_object
struct lu_ucred
Defines
#define MAY_RGETFACL (1 << 14)
#define md_cap_t(x) (x)
#define MD_CAP_TO_MASK(x) (1 << (x))
#define md_cap_raised(c, flag) (md_cap_t(c) & MD_CAP_TO_MASK(flag))
Enumerations
enum ma_valid {
MA_INODE = 1 << 0, MA_LOV = 1 << 1, MA_FLAGS = 1 << 2, MA_LMV = 1 << 3,
MA_ACL_DEF = 1 << 4, MA_LOV_DEF = 1 << 5, MA_HSM = 1 << 6, MA_PFID = 1 << 7,
MA_LMV_DEF = 1 << 8
}
metadata attributes
enum mdl_mode_t {
MDL_MINMODE = 0, MDL_EX = 1, MDL_PW = 2, MDL_PR = 4,
MDL_CW = 8, MDL_CR = 16, MDL_NL = 32, MDL_GROUP = 64,
MDL_MAXMODE
}
enum mdl_type_t { MDT_NUL_LOCK = 0, MDT_REG_LOCK = (1 << 0), MDT_PDO_LOCK = (1 << 1) }
enum mdd_object_role {
MOR_SRC_PARENT, MOR_SRC_CHILD, MOR_TGT_PARENT, MOR_TGT_CHILD,
MOR_TGT_ORPHAN
}
Used in MDD/OUT layer for object lock rule.
enum { UCRED_INVALID = -1, UCRED_INIT = 0, UCRED_OLD = 1, UCRED_NEW = 2 }
Functions
static struct md_device * lu2md_dev (const struct lu_device *d)
static struct lu_device * md2lu_dev (struct md_device *d)
static struct md_object * lu2md (const struct lu_object *o)
static int md_device_init (struct md_device *md, struct lu_device_type *t)
static void md_device_fini (struct md_device *md)
static struct md_object * md_object_find_slice (const struct lu_env *env, struct md_device *md, const struct lu_fid *f)
static int mo_permission (const struct lu_env *env, struct md_object *p, struct md_object *c, struct md_attr *at, int mask)
md operations
static int mo_attr_get (const struct lu_env *env, struct md_object *m, struct md_attr *at)
static int mo_readlink (const struct lu_env *env, struct md_object *m, struct lu_buf *buf)
static int mo_changelog (const struct lu_env *env, enum changelog_rec_type type, int flags, struct md_object *m)
static int mo_attr_set (const struct lu_env *env, struct md_object *m, const struct md_attr *at)
static int mo_xattr_get (const struct lu_env *env, struct md_object *m, struct lu_buf *buf, const char *name)
static int mo_xattr_del (const struct lu_env *env, struct md_object *m, const char *name)
static int mo_xattr_set (const struct lu_env *env, struct md_object *m, const struct lu_buf *buf, const char *name, int flags)
static int mo_xattr_list (const struct lu_env *env, struct md_object *m, struct lu_buf *buf)
static int mo_swap_layouts (const struct lu_env *env, struct md_object *o1, struct md_object *o2, __u64 flags)
static int mo_open (const struct lu_env *env, struct md_object *m, int flags)
static int mo_close (const struct lu_env *env, struct md_object *m, struct md_attr *ma, int mode)
static int mo_readpage (const struct lu_env *env, struct md_object *m, const struct lu_rdpg *rdpg)
static int mo_object_sync (const struct lu_env *env, struct md_object *m)
static int mo_object_lock (const struct lu_env *env, struct md_object *m, struct lustre_handle *lh, struct ldlm_enqueue_info *einfo, union ldlm_policy_data *policy)
static int mo_object_unlock (const struct lu_env *env, struct md_object *m, struct ldlm_enqueue_info *einfo, union ldlm_policy_data *policy)
static int mdo_lookup (const struct lu_env *env, struct md_object *p, const struct lu_name *lname, struct lu_fid *f, struct md_op_spec *spec)
static mdl_mode_t mdo_lock_mode (const struct lu_env *env, struct md_object *mo, mdl_mode_t lm)
static int mdo_create (const struct lu_env *env, struct md_object *p, const struct lu_name *lchild_name, struct md_object *c, struct md_op_spec *spc, struct md_attr *at)
static int mdo_create_data (const struct lu_env *env, struct md_object *p, struct md_object *c, const struct md_op_spec *spec, struct md_attr *ma)
static int mdo_rename (const struct lu_env *env, struct md_object *sp, struct md_object *tp, const struct lu_fid *lf, const struct lu_name *lsname, struct md_object *t, const struct lu_name *ltname, struct md_attr *ma)
static int mdo_migrate (const struct lu_env *env, struct md_object *pobj, struct md_object *sobj, const struct lu_name *lname, struct md_object *tobj, struct md_attr *ma)
static int mdo_is_subdir (const struct lu_env *env, struct md_object *mo, const struct lu_fid *fid, struct lu_fid *sfid)
static int mdo_link (const struct lu_env *env, struct md_object *p, struct md_object *s, const struct lu_name *lname, struct md_attr *ma)
static int mdo_unlink (const struct lu_env *env, struct md_object *p, struct md_object *c, const struct lu_name *lname, struct md_attr *ma, int no_name)
int lustre_buf2hsm (void *buf, int rc, struct md_hsm *mh)
void lustre_hsm2buf (void *buf, const struct md_hsm *mh)
struct lu_ucred * lu_ucred (const struct lu_env *env)
Get ucred key if session exists and ucred key is allocated on it.
struct lu_ucred * lu_ucred_check (const struct lu_env *env)
Get ucred key and check if it is properly initialized.
struct lu_ucred * lu_ucred_assert (const struct lu_env *env)
Get ucred key, which must exist and must be properly initialized.
int lu_ucred_global_init (void)
void lu_ucred_global_fini (void)
static int md_capable (struct lu_ucred *uc, cfs_cap_t cap)
Detailed Description
Sub-class of lu_object with methods common for "meta-data" objects in MDT stack.
Meta-data objects implement namespace operations: you can link, unlink them, and treat them as directories.
Examples: mdt, cmm, and mdt are implementations of md interface.
Define Documentation
#define MAY_RGETFACL (1 << 14)
Definition at line 102 of file md_object.h.
Referenced by mdd_permission(), and mdt_getxattr().
#define md_cap_raised (c, flag) (md_cap_t(c) & MD_CAP_TO_MASK(flag))
Definition at line 615 of file md_object.h.
Referenced by md_capable().
#define md_cap_t (x) (x)
Definition at line 611 of file md_object.h.
#define MD_CAP_TO_MASK (x) (1 << (x))
Definition at line 613 of file md_object.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
UCRED_INVALID
UCRED_INIT
UCRED_OLD
UCRED_NEW
Definition at line 576 of file md_object.h.
enum ma_valid
metadata attributes
Enumerator:
MA_INODE
MA_LOV
MA_FLAGS
MA_LMV
MA_ACL_DEF
MA_LOV_DEF
MA_HSM
MA_PFID
MA_LMV_DEF
Definition at line 71 of file md_object.h.
enum mdd_object_role
Used in MDD/OUT layer for object lock rule.
Enumerator:
MOR_SRC_PARENT
MOR_SRC_CHILD
MOR_TGT_PARENT
MOR_TGT_CHILD
MOR_TGT_ORPHAN
Definition at line 563 of file md_object.h.
enum mdl_mode_t
Enumerator:
MDL_MINMODE
MDL_EX
MDL_PW
MDL_PR
MDL_CW
MDL_CR
MDL_NL
MDL_GROUP
MDL_MAXMODE
Definition at line 83 of file md_object.h.
enum mdl_type_t
Enumerator:
MDT_NUL_LOCK
MDT_REG_LOCK
MDT_PDO_LOCK
Definition at line 95 of file md_object.h.
Function Documentation
static struct md_object* lu2md (const struct lu_object * o) [static, read]
Definition at line 303 of file md_object.h.
References LASSERT, lu_object::lo_dev, lu_device_is_md(), and md_object::mo_lu.
Referenced by md_object_find_slice(), mdo_locate(), and mdt_object_child().
static struct md_device* lu2md_dev (const struct lu_device * d) [static, read]
Definition at line 292 of file md_object.h.
References LASSERT, lu_device_is_md(), and md_device::md_lu_dev.
Referenced by echo_device_alloc(), and mdt_stack_init().
struct lu_ucred* lu_ucred (const struct lu_env * env) [read]
Get ucred key if session exists and ucred key is allocated on it.
Return NULL otherwise.
Definition at line 65 of file lu_ucred.c.
References lu_env::le_ses, and lu_context_key_get().
Referenced by __mdd_permission_internal(), lu_ucred_check(), mdd_acl_init(), mdd_changelog_data_store(), mdd_changelog_ns_store(), mdd_llog_record_calc_size(), mdd_open_sanity_check(), mdt_getxattr(), mdt_mfd_open(), mdt_orphan_open(), mdt_reint_setxattr(), and mdt_ucred().
struct lu_ucred* lu_ucred_assert (const struct lu_env * env) [read]
Get ucred key, which must exist and must be properly initialized.
Assert otherwise.
Definition at line 90 of file lu_ucred.c.
References LASSERT, and lu_ucred_check().
Referenced by mdd_check_acl(), mdd_is_sticky(), mdd_object_create(), mdd_permission(), and mdd_xattr_sanity_check().
struct lu_ucred* lu_ucred_check (const struct lu_env * env) [read]
Get ucred key and check if it is properly initialized.
Return NULL otherwise.
Definition at line 77 of file lu_ucred.c.
References lu_ucred(), lu_ucred::uc_valid, UCRED_NEW, and UCRED_OLD.
Referenced by __mdd_index_insert_only(), accmode(), lu_ucred_assert(), mdd_fix_attr(), and mdt_ucred_check().
void lu_ucred_global_fini (void)
Definition at line 104 of file lu_ucred.c.
References lu_context_key_degister().
Referenced by obdclass_exit().
int lu_ucred_global_init (void)
Definition at line 98 of file lu_ucred.c.
References LU_CONTEXT_KEY_INIT, and lu_context_key_register().
Referenced by obdclass_init().
int lustre_buf2hsm (void * buf, int rc, struct md_hsm * mh)
Definition at line 97 of file md_attrs.c.
References ENTRY, hsm_attrs::hsm_arch_id, hsm_attrs::hsm_arch_ver, hsm_attrs::hsm_compat, hsm_attrs::hsm_flags, lustre_hsm_swab(), md_hsm::mh_arch_id, md_hsm::mh_arch_ver, md_hsm::mh_compat, md_hsm::mh_flags, and RETURN.
Referenced by mdd_hsm_archive_exists(), mdd_hsm_update_locked(), and mdt_attr_get_complex().
void lustre_hsm2buf (void * buf, const struct md_hsm * mh)
Definition at line 129 of file md_attrs.c.
References ENTRY, hsm_attrs::hsm_arch_id, hsm_attrs::hsm_arch_ver, hsm_attrs::hsm_compat, hsm_attrs::hsm_flags, lustre_hsm_swab(), md_hsm::mh_arch_id, md_hsm::mh_arch_ver, md_hsm::mh_compat, and md_hsm::mh_flags.
Referenced by mdt_hsm_attr_set(), and mdt_hsm_release().
static struct lu_device* md2lu_dev (struct md_device * d) [static, read]
Definition at line 298 of file md_object.h.
References md_device::md_lu_dev.
Referenced by md_object_find_slice(), mdt_fini(), mdt_init0(), mdt_postrecov(), and mdt_process_config().
static int md_capable (struct lu_ucred * uc, cfs_cap_t cap) [inline, static]
Definition at line 618 of file md_object.h.
References md_cap_raised, and lu_ucred::uc_cap.
Referenced by __mdd_permission_internal(), hsm_action_permission(), mdd_fix_attr(), mdd_is_sticky(), mdd_open_sanity_check(), mdd_permission(), mdd_xattr_sanity_check(), mdt_hsm_add_actions(), mdt_hsm_is_admin(), mdt_hsm_state_set(), mdt_reint_setxattr(), mdt_reint_unlink(), and mdt_remote_permission_check().
static void md_device_fini (struct md_device * md) [inline, static]
Definition at line 314 of file md_object.h.
References lu_device_fini(), and md_device::md_lu_dev.
Referenced by mdd_device_free(), and mds_device_free().
static int md_device_init (struct md_device * md, struct lu_device_type * t) [inline, static]
Definition at line 309 of file md_object.h.
References lu_device_init(), and md_device::md_lu_dev.
Referenced by mdd_device_alloc(), and mds_device_alloc().
static struct md_object* md_object_find_slice (const struct lu_env * env, struct md_device * md, const struct lu_fid * f) [static, read]
Definition at line 319 of file md_object.h.
References lu2md(), lu_object_find_slice(), and md2lu_dev().
Referenced by mdd_object_find().
static int mdo_create (const struct lu_env * env, struct md_object * p, const struct lu_name * lchild_name, struct md_object * c, struct md_op_spec * spc, struct md_attr * at) [inline, static]
Definition at line 485 of file md_object.h.
References LASSERT, md_dir_operations::mdo_create, and md_object::mo_dir_ops.
Referenced by mdt_md_create(), mdt_orphan_open(), and mdt_reint_open().
static int mdo_create_data (const struct lu_env * env, struct md_object * p, struct md_object * c, const struct md_op_spec * spec, struct md_attr * ma) [inline, static]
Definition at line 496 of file md_object.h.
References LASSERT, md_dir_operations::mdo_create_data, and md_object::mo_dir_ops.
Referenced by mdt_create_data().
static int mdo_is_subdir (const struct lu_env * env, struct md_object * mo, const struct lu_fid * fid, struct lu_fid * sfid) [inline, static]
Definition at line 531 of file md_object.h.
References LASSERT, md_dir_operations::mdo_is_subdir, and md_object::mo_dir_ops.
Referenced by mdt_is_subdir().
static int mdo_link (const struct lu_env * env, struct md_object * p, struct md_object * s, const struct lu_name * lname, struct md_attr * ma) [inline, static]
Definition at line 540 of file md_object.h.
References LASSERT, md_dir_operations::mdo_link, and md_object::mo_dir_ops.
Referenced by mdt_reint_link().
static mdl_mode_t mdo_lock_mode (const struct lu_env * env, struct md_object * mo, mdl_mode_t lm) [inline, static]
Definition at line 476 of file md_object.h.
References MDL_MINMODE, md_dir_operations::mdo_lock_mode, and md_object::mo_dir_ops.
Referenced by mdt_lock_pdo_mode().
static int mdo_lookup (const struct lu_env * env, struct md_object * p, const struct lu_name * lname, struct lu_fid * f, struct md_op_spec * spec) [inline, static]
Definition at line 466 of file md_object.h.
References LASSERT, md_dir_operations::mdo_lookup, and md_object::mo_dir_ops.
Referenced by mdt_getattr_name_lock(), mdt_lookup_fileset(), mdt_lookup_version_check(), mdt_raw_lookup(), and mdt_reint_open().
static int mdo_migrate (const struct lu_env * env, struct md_object * pobj, struct md_object * sobj, const struct lu_name * lname, struct md_object * tobj, struct md_attr * ma) [inline, static]
Definition at line 520 of file md_object.h.
References LASSERT, md_dir_operations::mdo_migrate, and md_object::mo_dir_ops.
Referenced by mdt_reint_migrate_internal().
static int mdo_rename (const struct lu_env * env, struct md_object * sp, struct md_object * tp, const struct lu_fid * lf, const struct lu_name * lsname, struct md_object * t, const struct lu_name * ltname, struct md_attr * ma) [inline, static]
Definition at line 506 of file md_object.h.
References LASSERT, md_dir_operations::mdo_rename, and md_object::mo_dir_ops.
Referenced by mdt_reint_rename_internal().
static int mdo_unlink (const struct lu_env * env, struct md_object * p, struct md_object * c, const struct lu_name * lname, struct md_attr * ma, int no_name) [inline, static]
Definition at line 550 of file md_object.h.
References LASSERT, md_dir_operations::mdo_unlink, and md_object::mo_dir_ops.
Referenced by mdt_reint_open(), and mdt_reint_unlink().
static int mo_attr_get (const struct lu_env * env, struct md_object * m, struct md_attr * at) [inline, static]
Definition at line 338 of file md_object.h.
References LASSERT, md_object::mo_ops, and md_object_operations::moo_attr_get.
Referenced by mdt_attr_get_complex(), and mdt_rename_counter_tally().
static int mo_attr_set (const struct lu_env * env, struct md_object * m, const struct md_attr * at) [inline, static]
Definition at line 362 of file md_object.h.
References LASSERT, md_object::mo_ops, and md_object_operations::moo_attr_set.
Referenced by mdt_attr_set(), mdt_hsm_release(), mdt_mfd_close(), and mdt_reint_setxattr().
static int mo_changelog (const struct lu_env * env, enum changelog_rec_type type, int flags, struct md_object * m) [inline, static]
Definition at line 354 of file md_object.h.
References LASSERT, md_object::mo_ops, and md_object_operations::moo_changelog.
Referenced by hsm_cdt_request_completed().
static int mo_close (const struct lu_env * env, struct md_object * m, struct md_attr * ma, int mode) [inline, static]
Definition at line 424 of file md_object.h.
References LASSERT, md_object::mo_ops, and md_object_operations::moo_close.
Referenced by mdt_hsm_release(), and mdt_mfd_close().
static int mo_object_lock (const struct lu_env * env, struct md_object * m, struct lustre_handle * lh, struct ldlm_enqueue_info * einfo, union ldlm_policy_data * policy) [inline, static]
Definition at line 447 of file md_object.h.
References LASSERT, md_object::mo_ops, and md_object_operations::moo_object_lock.
Referenced by mdt_lock_slaves(), and mdt_remote_object_lock().
static int mo_object_sync (const struct lu_env * env, struct md_object * m) [inline, static]
Definition at line 441 of file md_object.h.
References LASSERT, md_object::mo_ops, and md_object_operations::moo_object_sync.
Referenced by mdt_object_sync().
static int mo_object_unlock (const struct lu_env * env, struct md_object * m, struct ldlm_enqueue_info * einfo, union ldlm_policy_data * policy) [inline, static]
Definition at line 457 of file md_object.h.
References LASSERT, md_object::mo_ops, and md_object_operations::moo_object_unlock.
Referenced by mdt_unlock_slaves().
static int mo_open (const struct lu_env * env, struct md_object * m, int flags) [inline, static]
Definition at line 416 of file md_object.h.
References LASSERT, md_object::mo_ops, and md_object_operations::moo_open.
Referenced by mdt_mfd_open(), and mdt_orphan_open().
static int mo_permission (const struct lu_env * env, struct md_object * p, struct md_object * c, struct md_attr * at, int mask) [inline, static]
md operations
Definition at line 328 of file md_object.h.
References LASSERT, md_object::mo_ops, and md_object_operations::moo_permission.
Referenced by mdt_close_swap_layouts(), mdt_cross_open(), mdt_getxattr(), mdt_pack_remote_perm(), and mdt_swap_layouts().
static int mo_readlink (const struct lu_env * env, struct md_object * m, struct lu_buf * buf) [inline, static]
Definition at line 346 of file md_object.h.
References LASSERT, md_object::mo_ops, and md_object_operations::moo_readlink.
Referenced by mdt_getattr_internal().
static int mo_readpage (const struct lu_env * env, struct md_object * m, const struct lu_rdpg * rdpg) [inline, static]
Definition at line 433 of file md_object.h.
References LASSERT, md_object::mo_ops, and md_object_operations::moo_readpage.
Referenced by mdt_readpage().
static int mo_swap_layouts (const struct lu_env * env, struct md_object * o1, struct md_object * o2, __u64 flags) [inline, static]
Definition at line 405 of file md_object.h.
References LASSERT, md_object::mo_ops, and md_object_operations::moo_swap_layouts.
Referenced by hsm_swap_layouts(), mdt_close_swap_layouts(), mdt_hsm_release(), and mdt_swap_layouts().
static int mo_xattr_del (const struct lu_env * env, struct md_object * m, const char * name) [inline, static]
Definition at line 379 of file md_object.h.
References LASSERT, md_object::mo_ops, and md_object_operations::moo_xattr_del.
Referenced by mdt_reint_setxattr().
static int mo_xattr_get (const struct lu_env * env, struct md_object * m, struct lu_buf * buf, const char * name) [inline, static]
Definition at line 370 of file md_object.h.
References LASSERT, md_object::mo_ops, and md_object_operations::moo_xattr_get.
Referenced by mdt_attr_get_complex(), mdt_attr_get_eabuf_size(), mdt_attr_get_pfid(), mdt_big_xattr_get(), mdt_getxattr_one(), mdt_getxattr_pack_reply(), mdt_init_slaves(), mdt_links_read(), mdt_lvbo_fill(), mdt_path_current(), mdt_reint_open(), mdt_rmtlsetfacl(), and mdt_stripe_get().
static int mo_xattr_list (const struct lu_env * env, struct md_object * m, struct lu_buf * buf) [inline, static]
Definition at line 397 of file md_object.h.
References LASSERT, md_object::mo_ops, and md_object_operations::moo_xattr_list.
Referenced by mdt_getxattr(), mdt_getxattr_all(), and mdt_getxattr_pack_reply().
static int mo_xattr_set (const struct lu_env * env, struct md_object * m, const struct lu_buf * buf, const char * name, int flags) [inline, static]
Definition at line 387 of file md_object.h.
References LASSERT, md_object::mo_ops, and md_object_operations::moo_xattr_set.
Referenced by mdt_hsm_attr_set(), mdt_hsm_release(), mdt_reint_setattr(), and mdt_reint_setxattr().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.