Lustre: export
export
[PortalRPC export definitions, PtlRPC import definitions]
Data Structures
struct tg_export_data
Target-specific export data.
struct mdt_export_data
MDT-specific export data.
struct ec_export_data
struct filter_export_data
Filter (oss-side) specific import data.
struct mgs_export_data
struct nid_stat
per-NID statistics structure.
struct obd_export
Export structure.
struct kkuc_ct_data
struct adaptive_timeout
struct ptlrpc_at_array
struct imp_at
struct obd_import_conn
Definition of import connection structure.
struct import_state_hist
struct obd_import
Defintion of PortalRPC import structure.
Defines
#define nidstat_getref(nidstat)
#define nidstat_putref(nidstat)
#define exp_target_data u.eu_target_data
#define exp_mdt_data u.eu_mdt_data
#define exp_filter_data u.eu_filter_data
#define exp_ec_data u.eu_ec_data
#define KKUC_CT_DATA_MAGIC 0x092013cea
#define IMP_STATE_HIST_LEN 16
#define AT_OFF (at_max == 0)
Enumerations
enum obd_option { OBD_OPT_FORCE = 0x0001, OBD_OPT_FAILOVER = 0x0002, OBD_OPT_ABORT_RECOV = 0x0004 }
enum lustre_imp_state {
LUSTRE_IMP_CLOSED = 1, LUSTRE_IMP_NEW = 2, LUSTRE_IMP_DISCON = 3, LUSTRE_IMP_CONNECTING = 4,
LUSTRE_IMP_REPLAY = 5, LUSTRE_IMP_REPLAY_LOCKS = 6, LUSTRE_IMP_REPLAY_WAIT = 7, LUSTRE_IMP_RECOVER = 8,
LUSTRE_IMP_FULL = 9, LUSTRE_IMP_EVICTED = 10
}
Possible import states.
enum obd_import_event {
IMP_EVENT_DISCON = 0x808001, IMP_EVENT_INACTIVE = 0x808002, IMP_EVENT_INVALIDATE = 0x808003, IMP_EVENT_ACTIVE = 0x808004,
IMP_EVENT_OCD = 0x808005, IMP_EVENT_DEACTIVATE = 0x808006, IMP_EVENT_ACTIVATE = 0x808007
}
List of import event types.
Functions
static __u64 * exp_connect_flags_ptr (struct obd_export *exp)
static __u64 exp_connect_flags (struct obd_export *exp)
static int exp_max_brw_size (struct obd_export *exp)
static int exp_connect_multibulk (struct obd_export *exp)
static int exp_expired (struct obd_export *exp, cfs_duration_t age)
static int exp_connect_cancelset (struct obd_export *exp)
static int exp_connect_lru_resize (struct obd_export *exp)
static int exp_connect_rmtclient (struct obd_export *exp)
static int client_is_remote (struct obd_export *exp)
static int exp_connect_vbr (struct obd_export *exp)
static int exp_connect_umask (struct obd_export *exp)
static int imp_connect_lru_resize (struct obd_import *imp)
static int exp_connect_layout (struct obd_export *exp)
static bool exp_connect_lvb_type (struct obd_export *exp)
static bool imp_connect_lvb_type (struct obd_import *imp)
static bool imp_connect_disp_stripe (struct obd_import *imp)
static __u64 exp_connect_ibits (struct obd_export *exp)
struct obd_export * class_conn2export (struct lustre_handle *conn)
struct obd_device * class_conn2obd (struct lustre_handle *conn)
static char * ptlrpc_import_state_name (enum lustre_imp_state state)
Returns test string representation of numeric import state state.
static unsigned int at_est2timeout (unsigned int val)
static unsigned int at_timeout2est (unsigned int val)
static void at_reset_nolock (struct adaptive_timeout *at, int val)
static void at_reset (struct adaptive_timeout *at, int val)
static void at_init (struct adaptive_timeout *at, int val, int flags)
static void at_reinit (struct adaptive_timeout *at, int val, int flags)
static int at_get (struct adaptive_timeout *at)
int at_measured (struct adaptive_timeout *at, unsigned int val)
int import_at_get_index (struct obd_import *imp, int portal)
struct obd_import * class_exp2cliimp (struct obd_export *)
struct obd_import * class_conn2cliimp (struct lustre_handle *)
Variables
unsigned int at_min
unsigned int at_max
enum lustre_at_flags { LATF_SKIP = 0x0, LATF_STATS = 0x1 }
#define D_ADAPTTO D_OTHER
Adaptive Timeout stuff.
#define AT_BINS 4
#define AT_FLG_NOHIST 0x1
#define IMP_AT_MAX_PORTALS 8
Define Documentation
#define AT_BINS 4
Definition at line 60 of file lustre_import.h.
Referenced by at_measured().
#define AT_FLG_NOHIST 0x1
Definition at line 61 of file lustre_import.h.
Referenced by at_measured(), and init_imp_at().
#define AT_OFF (at_max == 0)
Definition at line 379 of file lustre_import.h.
Referenced by ldlm_cp_timeout(), osc_enter_cache(), prolong_timeout(), ptl_send_rpc(), ptlrpc_at_add_timed(), ptlrpc_at_get_net_latency(), ptlrpc_at_send_early_reply(), ptlrpc_at_set_req_timeout(), ptlrpc_disconnect_import(), ptlrpc_server_get_timeout(), ptlrpc_svcpt_health_check(), ptlrpc_update_next_ping(), and signal_completed_replay().
#define D_ADAPTTO D_OTHER
Adaptive Timeout stuff.
Definition at line 59 of file lustre_import.h.
Referenced by ptlrpc_at_adj_net_latency(), ptlrpc_at_adj_service(), ptlrpc_at_check_timed(), ptlrpc_at_recv_early_reply(), ptlrpc_at_send_early_reply(), ptlrpc_at_set_reply(), ptlrpc_server_handle_request(), reply_in_callback(), and sptlrpc_cli_unwrap_early_reply().
#define exp_ec_data u.eu_ec_data
Definition at line 297 of file lustre_export.h.
#define exp_filter_data u.eu_filter_data
Definition at line 296 of file lustre_export.h.
#define exp_mdt_data u.eu_mdt_data
Definition at line 295 of file lustre_export.h.
#define exp_target_data u.eu_target_data
Definition at line 294 of file lustre_export.h.
Referenced by nm_member_delete_list(), nm_member_reclassify_nodemap(), nm_member_revoke_locks(), and nodemap_exports_show().
#define IMP_AT_MAX_PORTALS 8
Definition at line 86 of file lustre_import.h.
Referenced by import_at_get_index(), and init_imp_at().
#define IMP_STATE_HIST_LEN 16
Definition at line 153 of file lustre_import.h.
Referenced by __import_set_state().
#define KKUC_CT_DATA_MAGIC 0x092013cea
Definition at line 423 of file lustre_export.h.
Referenced by lmv_hsm_ct_register(), and mdc_hsm_ct_reregister().
#define nidstat_getref (nidstat)
Value:
do {                                                                           \
        atomic_inc(&(nidstat)->nid_exp_ref_count);                         \
} while(0)
Definition at line 144 of file lustre_export.h.
Referenced by nidstats_get().
#define nidstat_putref (nidstat)
Value:
do {                                                                           \
        atomic_dec(&(nidstat)->nid_exp_ref_count);                         \
        LASSERTF(atomic_read(&(nidstat)->nid_exp_ref_count) >= 0,          \
                 "stat %p nid_exp_ref_count < 0\n", nidstat);                  \
} while(0)
Definition at line 149 of file lustre_export.h.
Referenced by nidstats_put_locked().
Enumeration Type Documentation
enum lustre_at_flags
Enumerator:
LATF_SKIP
LATF_STATS
Definition at line 73 of file lustre_import.h.
enum lustre_imp_state
Possible import states.
Enumerator:
LUSTRE_IMP_CLOSED
LUSTRE_IMP_NEW
LUSTRE_IMP_DISCON
LUSTRE_IMP_CONNECTING
LUSTRE_IMP_REPLAY
LUSTRE_IMP_REPLAY_LOCKS
LUSTRE_IMP_REPLAY_WAIT
LUSTRE_IMP_RECOVER
LUSTRE_IMP_FULL
LUSTRE_IMP_EVICTED
Definition at line 97 of file lustre_import.h.
enum obd_import_event
List of import event types.
Enumerator:
IMP_EVENT_DISCON
IMP_EVENT_INACTIVE
IMP_EVENT_INVALIDATE
IMP_EVENT_ACTIVE
IMP_EVENT_OCD
IMP_EVENT_DEACTIVATE
IMP_EVENT_ACTIVATE
Definition at line 126 of file lustre_import.h.
enum obd_option
Enumerator:
OBD_OPT_FORCE
OBD_OPT_FAILOVER
OBD_OPT_ABORT_RECOV
Definition at line 156 of file lustre_export.h.
Function Documentation
static unsigned int at_est2timeout (unsigned int val) [inline, static]
Definition at line 328 of file lustre_import.h.
Referenced by prolong_timeout(), ptlrpc_at_set_req_timeout(), ptlrpc_service_part_init(), and qmt_dqacq().
static int at_get (struct adaptive_timeout * at) [inline, static]
Definition at line 373 of file lustre_import.h.
References adaptive_timeout::at_current, and at_min.
Referenced by import_select_connection(), ldlm_cp_timeout(), mdt_statfs(), prolong_timeout(), ptlrpc_at_adj_net_latency(), ptlrpc_at_adj_service(), ptlrpc_at_check_timed(), ptlrpc_at_get_net_latency(), ptlrpc_at_send_early_reply(), ptlrpc_at_set_reply(), ptlrpc_at_set_req_timeout(), ptlrpc_disconnect_import(), ptlrpc_server_get_timeout(), ptlrpc_server_handle_request(), ptlrpc_update_next_ping(), and qmt_dqacq().
static void at_init (struct adaptive_timeout * at, int val, int flags) [inline, static]
Definition at line 355 of file lustre_import.h.
References adaptive_timeout::at_flags, adaptive_timeout::at_lock, and at_reset().
Referenced by class_new_export(), init_imp_at(), ldlm_namespace_new(), and ptlrpc_service_part_init().
int at_measured (struct adaptive_timeout * at, unsigned int val)
Definition at line 1665 of file import.c.
References AT_BINS, adaptive_timeout::at_binstart, adaptive_timeout::at_current, adaptive_timeout::at_flags, AT_FLG_NOHIST, adaptive_timeout::at_hist, at_history, adaptive_timeout::at_lock, at_max, at_min, adaptive_timeout::at_worst_ever, adaptive_timeout::at_worst_time, CDEBUG, cfs_time_current_sec(), D_OTHER, LASSERT, max, now(), and unlikely.
Referenced by import_select_connection(), ldlm_completion_tail(), ptlrpc_at_adj_net_latency(), ptlrpc_at_adj_service(), ptlrpc_at_send_early_reply(), and ptlrpc_at_set_reply().
static void at_reinit (struct adaptive_timeout * at, int val, int flags) [inline, static]
Definition at line 362 of file lustre_import.h.
References adaptive_timeout::at_binstart, adaptive_timeout::at_flags, adaptive_timeout::at_hist, adaptive_timeout::at_lock, and at_reset_nolock().
Referenced by ptlrpc_connect_interpret().
static void at_reset (struct adaptive_timeout * at, int val) [inline, static]
Definition at line 348 of file lustre_import.h.
References adaptive_timeout::at_lock, and at_reset_nolock().
Referenced by at_init(), and import_select_connection().
static void at_reset_nolock (struct adaptive_timeout * at, int val) [inline, static]
Definition at line 341 of file lustre_import.h.
References adaptive_timeout::at_current, adaptive_timeout::at_worst_ever, adaptive_timeout::at_worst_time, and cfs_time_current_sec().
Referenced by at_reinit(), and at_reset().
static unsigned int at_timeout2est (unsigned int val) [inline, static]
Definition at line 334 of file lustre_import.h.
References LASSERT, and max.
Referenced by ptlrpc_connect_import().
struct obd_import* class_conn2cliimp (struct lustre_handle *) [read]
Definition at line 758 of file genops.c.
References client_obd::cl_import, class_conn2obd(), obd_device::cli, and obd_device::u.
struct obd_export* class_conn2export (struct lustre_handle * conn) [read]
Definition at line 708 of file genops.c.
Referenced by class_conn2obd(), client_connect_import(), client_import_del_conn(), echo_client_connect(), echo_connect(), import_select_connection(), lmv_connect(), lod_obd_connect(), lov_connect(), lwp_obd_connect(), mdd_obd_connect(), mdt_obd_connect(), mgs_obd_connect(), ofd_obd_connect(), osd_obd_connect(), osp_obd_connect(), ptlrpc_at_send_early_reply(), ptlrpc_connect_interpret(), ptlrpc_server_handle_req_in(), and qmt_device_obd_connect().
struct obd_device* class_conn2obd (struct lustre_handle * conn) [read]
Definition at line 737 of file genops.c.
Referenced by class_conn2cliimp().
struct obd_import* class_exp2cliimp (struct obd_export *) [read]
Definition at line 749 of file genops.c.
References client_obd::cl_import, obd_device::cli, obd_export::exp_obd, and obd_device::u.
Referenced by client_is_remote(), fld_client_rpc(), ldlm_cli_cancel(), ldlm_cli_cancel_req(), ldlm_cli_convert(), ldlm_cli_enqueue(), ldlm_enqueue_pack(), ldlm_lock_match(), lfsck_async_request(), lfsck_layout_async_notify(), lfsck_layout_async_query(), lfsck_layout_master_conditional_destroy(), lfsck_layout_slave_check_pairs(), lfsck_namespace_notify_lmv_remote(), lov_check_and_wait_active(), lov_check_set(), mdc_close(), mdc_create(), mdc_enqueue(), mdc_enqueue_pack(), mdc_fsync(), mdc_get_info(), mdc_get_info_rpc(), mdc_get_remote_perm(), mdc_get_root(), mdc_getattr(), mdc_getattr_name(), mdc_getpage(), mdc_intent_getattr_pack(), mdc_intent_getxattr_pack(), mdc_intent_layout_pack(), mdc_intent_open_pack(), mdc_intent_unlink_pack(), mdc_ioc_hsm_ct_start(), mdc_ioc_hsm_current_action(), mdc_ioc_hsm_progress(), mdc_ioc_hsm_request(), mdc_ioc_hsm_state_get(), mdc_ioc_hsm_state_set(), mdc_ioc_swap_layouts(), mdc_link(), mdc_quotactl(), mdc_rename(), mdc_set_info_async(), mdc_setattr(), mdc_unlink(), mdc_xattr_common(), mgc_enqueue(), mgc_get_info(), mgc_process_log(), mgc_process_recover_log(), mgc_set_info_async(), mgc_set_mgs_param(), mgc_target_register(), osc_create(), osc_destroy(), osc_enqueue_base(), osc_getattr(), osc_io_data_version_start(), osc_ladvise_base(), osc_lock_to_lockless(), osc_object_fiemap(), osc_punch_base(), osc_quotactl(), osc_set_info_async(), osc_setattr(), osc_setattr_async(), osc_sync_base(), qsd_fetch_index(), qsd_intent_lock(), qsd_ready(), qsd_send_dqacq(), and seq_client_rpc().
static int client_is_remote (struct obd_export * exp) [inline, static]
Definition at line 348 of file lustre_export.h.
References class_exp2cliimp(), obd_import::imp_connect_data, OBD_CONNECT_RMT_CLIENT, and obd_connect_data::ocd_connect_flags.
Referenced by mdc_finish_enqueue(), mdc_get_lustre_md(), mdc_get_remote_perm(), mdc_getattr(), mdc_getattr_common(), mdc_intent_getattr_pack(), mdc_intent_open_pack(), and osc_page_submit().
static int exp_connect_cancelset (struct obd_export * exp) [inline, static]
Definition at line 330 of file lustre_export.h.
References exp_connect_flags(), LASSERT, and OBD_CONNECT_CANCELSET.
Referenced by ldlm_cli_cancel(), ldlm_cli_cancel_list(), ldlm_lock_decref_internal(), mdc_rename(), mdc_resource_get_unused(), and osc_resource_get_unused().
static __u64 exp_connect_flags (struct obd_export * exp) [inline, static]
Definition at line 304 of file lustre_export.h.
References exp_connect_flags_ptr().
Referenced by __ll_inode_revalidate(), class_export_recovery_cleanup(), client_common_fill_super(), exp_connect_cancelset(), exp_connect_layout(), exp_connect_lru_resize(), exp_connect_lvb_type(), exp_connect_rmtclient(), exp_connect_umask(), exp_connect_vbr(), exp_max_brw_size(), hsm_action_permission(), ldlm_cli_cancel_req(), ldlm_cli_enqueue_fini(), ldlm_flock_cancel_on_deadlock(), lfsck_layout_master_conditional_destroy(), lfsck_layout_slave_check_pairs(), ll_dir_ioctl(), ll_dir_setdirstripe(), ll_intent_file_open(), lmv_create(), mdc_get_root(), mdt_close_swap_layouts(), mdt_conn_flags(), mdt_counter_incr(), mdt_finish_open(), mdt_getattr_internal(), mdt_getxattr_pack_reply(), mdt_hsm_release(), mdt_intent_opc(), mdt_is_dne_client(), mdt_is_striped_client(), mdt_mfd_open(), mdt_obd_disconnect(), mdt_readpage(), mdt_reint_open(), mdt_reint_setxattr(), mdt_req_get_jobid(), mdt_stripe_get(), mgs_fsc_attach(), ofd_counter_incr(), ofd_destroy_export(), ofd_grant_param_supp(), ofd_orphans_destroy(), ofd_statfs(), only_mgs_is_running(), ptlrpc_connect_interpret(), ptlrpc_connect_set_flags(), tgt_blocking_ast(), tgt_client_add(), tgt_client_del(), tgt_client_new(), tgt_conn_flags(), tgt_is_multimodrpcs_client(), tgt_last_commit_cb_add(), tgt_last_rcvd_update(), tgt_request_handle(), tgt_sendpage(), and tgt_validate_obdo().
static __u64* exp_connect_flags_ptr (struct obd_export * exp) [inline, static]
Definition at line 299 of file lustre_export.h.
References obd_export::exp_connect_data, and obd_connect_data::ocd_connect_flags.
Referenced by exp_connect_flags(), mdc_iocontrol(), mdt_connect_internal(), mdt_set_info(), and tgt_connect().
static __u64 exp_connect_ibits (struct obd_export * exp) [inline, static]
Definition at line 412 of file lustre_export.h.
References obd_export::exp_connect_data, and obd_connect_data::ocd_ibits_known.
Referenced by mdc_lock_match().
static int exp_connect_layout (struct obd_export * exp) [inline, static]
Definition at line 377 of file lustre_export.h.
References exp_connect_flags(), and OBD_CONNECT_LAYOUTLOCK.
Referenced by mdt_client_compatibility(), mdt_getattr_name_lock(), mdt_object_open_lock(), and mdt_swap_layouts().
static int exp_connect_lru_resize (struct obd_export * exp) [inline, static]
Definition at line 336 of file lustre_export.h.
References exp_connect_flags(), LASSERT, and OBD_CONNECT_LRU_RESIZE.
Referenced by target_pack_pool_reply().
static bool exp_connect_lvb_type (struct obd_export * exp) [inline, static]
Definition at line 382 of file lustre_export.h.
References exp_connect_flags(), LASSERT, and OBD_CONNECT_LVB_TYPE.
Referenced by ofd_lvbo_size(), ofd_lvbo_update(), and osc_ldlm_glimpse_ast().
static int exp_connect_multibulk (struct obd_export * exp) [inline, static]
Definition at line 318 of file lustre_export.h.
References exp_max_brw_size(), and ONE_MB_BRW_SIZE.
static int exp_connect_rmtclient (struct obd_export * exp) [inline, static]
Definition at line 342 of file lustre_export.h.
References exp_connect_flags(), LASSERT, and OBD_CONNECT_RMT_CLIENT.
Referenced by allow_client_chgrp(), mdt_body_reverse_idmap(), mdt_check_ucred(), mdt_destroy_export(), mdt_finish_open(), mdt_fix_attr_ucred(), mdt_getattr_internal(), mdt_getxattr(), mdt_getxattr_one(), mdt_handle_idmap(), mdt_init_idmap(), mdt_pack_remote_perm(), mdt_quotactl(), mdt_reint_setxattr(), new_init_ucred(), ofd_preprw_write(), ptlrpc_user_desc_do_idmap(), and tgt_drop_id().
static int exp_connect_umask (struct obd_export * exp) [inline, static]
Definition at line 363 of file lustre_export.h.
References exp_connect_flags(), and OBD_CONNECT_UMASK.
Referenced by ll_dir_setdirstripe(), ll_lookup_it(), ll_mkdir(), and ll_mknod().
static int exp_connect_vbr (struct obd_export * exp) [inline, static]
Definition at line 356 of file lustre_export.h.
References exp_connect_flags(), obd_export::exp_connection, LASSERT, and OBD_CONNECT_VBR.
Referenced by mdt_version_check(), and mdt_version_save().
static int exp_expired (struct obd_export * exp, cfs_duration_t age) [inline, static]
Definition at line 323 of file lustre_export.h.
References cfs_time_add(), cfs_time_before(), cfs_time_current_sec(), obd_export::exp_delayed, obd_export::exp_last_request_time, and LASSERT.
static int exp_max_brw_size (struct obd_export * exp) [inline, static]
Definition at line 309 of file lustre_export.h.
References obd_export::exp_connect_data, exp_connect_flags(), LASSERT, OBD_CONNECT_BRW_SIZE, obd_connect_data::ocd_brw_size, and ONE_MB_BRW_SIZE.
Referenced by exp_connect_multibulk(), mdt_readpage(), ofd_grant_chunk(), and tgt_obd_idx_read().
static bool imp_connect_disp_stripe (struct obd_import * imp) [inline, static]
Definition at line 403 of file lustre_export.h.
References obd_import::imp_connect_data, LASSERT, OBD_CONNECT_DISP_STRIPE, and obd_connect_data::ocd_connect_flags.
Referenced by mdc_free_open().
static int imp_connect_lru_resize (struct obd_import * imp) [inline, static]
Definition at line 368 of file lustre_export.h.
References obd_import::imp_connect_data, LASSERT, OBD_CONNECT_LRU_RESIZE, and obd_connect_data::ocd_connect_flags.
Referenced by ldlm_cli_update_pool().
static bool imp_connect_lvb_type (struct obd_import * imp) [inline, static]
Definition at line 391 of file lustre_export.h.
References obd_import::imp_connect_data, LASSERT, OBD_CONNECT_LVB_TYPE, and obd_connect_data::ocd_connect_flags.
Referenced by mdc_enqueue(), and ofd_lvbo_update().
int import_at_get_index (struct obd_import * imp, int portal)
Definition at line 1742 of file import.c.
References imp_at::iat_portal, obd_import::imp_at, IMP_AT_MAX_PORTALS, obd_import::imp_lock, and LASSERT.
Referenced by ptlrpc_at_adj_service(), ptlrpc_at_set_req_timeout(), and ptlrpc_disconnect_import().
static char* ptlrpc_import_state_name (enum lustre_imp_state state) [inline, static]
Returns test string representation of numeric import state state.
Definition at line 111 of file lustre_import.h.
References LASSERT, and LUSTRE_IMP_EVICTED.
Referenced by import_sec_validate_get(), mgc_set_info_async(), ptlrpc_expire_one_request(), ptlrpc_pinger_force(), ptlrpc_pinger_process_import(), ptlrpc_reconnect_import(), ptlrpc_send_new_req(), and ptlrpc_set_import_discon().
Variable Documentation
unsigned int at_max
Definition at line 97 of file class_obd.c.
Referenced by at_measured(), class_set_global(), osc_enter_cache(), ptlrpc_service_part_init(), ptlrpc_svcpt_health_check(), and qsd_wait_timeout().
unsigned int at_min
Definition at line 95 of file class_obd.c.
Referenced by at_get(), at_measured(), and class_set_global().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.