Lustre: Memory descriptors
Memory descriptors
[LNet]
A memory descriptor contains information about a region of a user's memory (either in kernel or user space) and optionally points to an event queue where information about the operations performed on the memory descriptor are recorded.
Data Structures
struct lnet_md_t
Defines the visible parts of a memory descriptor.
struct lnet_kiov_t
A page-based fragment of a MD.
Defines
#define LNET_MTU_BITS 20
#define LNET_MTU (1 << LNET_MTU_BITS)
#define LNET_MAX_IOV 256
limit on the number of fragments in discontiguous MDs
#define LNET_MD_OP_PUT (1 << 0)
Options for the MD structure.
#define LNET_MD_OP_GET (1 << 1)
See lnet_md_t::options.
#define LNET_MD_MANAGE_REMOTE (1 << 2)
See lnet_md_t::options.
#define LNET_MD_TRUNCATE (1 << 4)
See lnet_md_t::options.
#define LNET_MD_ACK_DISABLE (1 << 5)
See lnet_md_t::options.
#define LNET_MD_IOVEC (1 << 6)
See lnet_md_t::options.
#define LNET_MD_MAX_SIZE (1 << 7)
See lnet_md_t::options.
#define LNET_MD_KIOV (1 << 8)
See lnet_md_t::options.
#define LNET_MD_PHYS 0
#define LNET_MD_THRESH_INF (-1)
Infinite threshold on MD operations.
Typedefs
typedef struct iovec lnet_md_iovec_t
Functions
int LNetMDAttach (lnet_handle_me_t current_in, lnet_md_t md_in, lnet_unlink_t unlink_in, lnet_handle_md_t *handle_out)
Create a memory descriptor and attach it to a ME.
int LNetMDBind (lnet_md_t md_in, lnet_unlink_t unlink_in, lnet_handle_md_t *handle_out)
Create a "free floating" memory descriptor - a MD that is not associated with a ME.
int LNetMDUnlink (lnet_handle_md_t md_in)
Unlink the memory descriptor from any ME it may be linked to and release the internal resources associated with it.
Detailed Description
A memory descriptor contains information about a region of a user's memory (either in kernel or user space) and optionally points to an event queue where information about the operations performed on the memory descriptor are recorded.
Memory descriptor is abbreviated as MD and can be used interchangeably with the memory region it describes.
The LNet API provides two operations to create MDs: LNetMDAttach() and LNetMDBind(); one operation to unlink and release the resources associated with a MD: LNetMDUnlink().
Define Documentation
#define LNET_MAX_IOV 256
limit on the number of fragments in discontiguous MDs
Definition at line 450 of file types.h.
Referenced by _kgnilnd_proc_run_cksum_test(), brw_client_init(), brw_server_handle(), kgnilnd_base_startup(), kgnilnd_free_tx(), kgnilnd_send(), kgnilnd_setup_phys_buffer(), kiblnd_create_tx_pool(), kiblnd_destroy_tx_pool(), kiblnd_send(), ksocknal_lib_kiov_vmap(), ksocknal_recv(), ksocknal_send(), lnet_md_validate(), lst_get_bulk_param(), ptlrpc_fill_bulk_md(), ptlrpc_register_bulk(), ptlrpc_set_bulk_mbits(), sfw_alloc_pages(), srpc_alloc_bulk(), srpc_init_client_rpc(), and srpc_prepare_bulk().
#define LNET_MD_ACK_DISABLE (1 << 5)
See lnet_md_t::options.
Definition at line 464 of file types.h.
Referenced by lnet_recv_put().
#define LNET_MD_IOVEC (1 << 6)
See lnet_md_t::options.
Definition at line 466 of file types.h.
Referenced by lnet_md_alloc(), lnet_md_build(), lnet_md_deconstruct(), lnet_md_validate(), and ptlrpc_fill_bulk_md().
#define LNET_MD_KIOV (1 << 8)
See lnet_md_t::options.
Definition at line 470 of file types.h.
Referenced by kgnilnd_parse_lnet_rdma(), kgnilnd_send(), kiblnd_send(), lnet_md_alloc(), lnet_md_build(), lnet_md_deconstruct(), lnet_md_free(), lnet_md_validate(), lnet_setpayloadbuffer(), ptlrpc_fill_bulk_md(), srpc_do_bulk(), and srpc_prepare_bulk().
#define LNET_MD_MANAGE_REMOTE (1 << 2)
See lnet_md_t::options.
Definition at line 459 of file types.h.
Referenced by lnet_ping_info_setup(), lnet_try_match_md(), ptl_send_rpc(), and reply_in_callback().
#define LNET_MD_MAX_SIZE (1 << 7)
See lnet_md_t::options.
Definition at line 468 of file types.h.
Referenced by lnet_md_build(), lnet_md_exhausted(), lnet_try_match_md(), and ptlrpc_register_rqbd().
#define LNET_MD_OP_GET (1 << 1)
See lnet_md_t::options.
Definition at line 457 of file types.h.
Referenced by lnet_mt_match_md(), lnet_parse_get(), lnet_ping_info_setup(), LNetMDAttach(), LNetMDBind(), ptlrpc_register_bulk(), srpc_do_bulk(), srpc_post_active_rdma(), and srpc_prepare_bulk().
#define LNET_MD_OP_PUT (1 << 0)
Options for the MD structure.
See lnet_md_t::options.
Definition at line 455 of file types.h.
Referenced by lnet_parse_put(), lnet_ptl_attach_md(), lnet_ptl_match_md(), lnet_try_match_md(), LNetMDAttach(), LNetMDBind(), ptl_send_rpc(), ptlrpc_register_bulk(), ptlrpc_register_rqbd(), srpc_do_bulk(), srpc_post_active_rdma(), srpc_post_passive_rqtbuf(), srpc_prepare_bulk(), srpc_prepare_reply(), srpc_send_reply(), and srpc_send_request().
#define LNET_MD_PHYS 0
Definition at line 473 of file types.h.
Referenced by ptlrpc_fill_bulk_md().
#define LNET_MD_THRESH_INF (-1)
Infinite threshold on MD operations.
See lnet_md_t::threshold
Definition at line 476 of file types.h.
Referenced by fail_peer(), jt_ptl_fail_nid(), lnet_create_rc_data_locked(), lnet_msg_attach_md(), lnet_ping_info_setup(), ptl_send_rpc(), and ptlrpc_register_rqbd().
#define LNET_MD_TRUNCATE (1 << 4)
See lnet_md_t::options.
Definition at line 462 of file types.h.
Referenced by lnet_create_rc_data_locked(), lnet_parse_reply(), lnet_ping(), lnet_ping_info_setup(), lnet_try_match_md(), and ptl_send_rpc().
#define LNET_MTU (1 << LNET_MTU_BITS)
Definition at line 447 of file types.h.
Referenced by lnet_msg2bufpool(), and lnet_parse().
#define LNET_MTU_BITS 20
Definition at line 446 of file types.h.
Referenced by osc_brw_prep_request(), and osp_prep_update_req().
Typedef Documentation
typedef struct iovec lnet_md_iovec_t
Definition at line 479 of file types.h.
Function Documentation
int LNetMDAttach (lnet_handle_me_t meh, lnet_md_t umd, lnet_unlink_t unlink, lnet_handle_md_t * handle)
Create a memory descriptor and attach it to a ME.
Parameters:
meh A handle for a ME to associate the new MD with.
umd Provides initial values for the user-visible parts of a MD. Other than its use for initialization, there is no linkage between this structure and the MD maintained by the LNet.
unlink A flag to indicate whether the MD is automatically unlinked when it becomes inactive, either because the operation threshold drops to zero or because the available memory becomes less than umd.max_size. (Note that the check for unlinking a MD only occurs after the completion of a successful operation on the MD.) The value LNET_UNLINK enables auto unlinking; the value LNET_RETAIN disables it.
handle On successful returns, a handle to the newly created MD is saved here. This handle can be used later in LNetMDUnlink().
Return values:
0 On success.
-EINVAL If umd is not valid.
-ENOMEM If new MD cannot be allocated.
-ENOENT Either meh or umd.eq_handle does not point to a valid object. Note that it's OK to supply a NULL umd.eq_handle by calling LNetInvalidateHandle() on it.
-EBUSY If the ME pointed to by meh is already associated with a MD.
Definition at line 263 of file lib-md.c.
References CERROR, lnet_handle_any_t::cookie, lnet_md_t::eq_handle, LASSERT, LIST_HEAD_INIT, lnet_t::ln_refcount, lnet_cpt_of_cookie(), lnet_drop_delayed_msg_list(), lnet_handle2me(), lnet_md2handle(), lnet_md_alloc(), lnet_md_build(), lnet_md_free(), lnet_md_link(), LNET_MD_OP_GET, LNET_MD_OP_PUT, lnet_md_validate(), lnet_ptl_attach_md(), lnet_recv_delayed_msg_list(), lnet_res_lock(), lnet_res_unlock(), lnet_me::me_md, lnet_md_t::options, and the_lnet.
Referenced by lnet_ping_info_setup(), ptl_send_rpc(), ptlrpc_register_bulk(), ptlrpc_register_rqbd(), and srpc_post_passive_rdma().
int LNetMDBind (lnet_md_t umd, lnet_unlink_t unlink, lnet_handle_md_t * handle)
Create a "free floating" memory descriptor - a MD that is not associated with a ME.
Such MDs are usually used in LNetPut() and LNetGet() operations.
Parameters:
umd,unlink See the discussion for LNetMDAttach().
handle On successful returns, a handle to the newly created MD is saved here. This handle can be used later in LNetMDUnlink(), LNetPut(), and LNetGet() operations.
Return values:
0 On success.
-EINVAL If umd is not valid.
-ENOMEM If new MD cannot be allocated.
-ENOENT umd.eq_handle does not point to a valid EQ. Note that it's OK to supply a NULL umd.eq_handle by calling LNetInvalidateHandle() on it.
Definition at line 343 of file lib-md.c.
References CERROR, lnet_md_t::eq_handle, LASSERT, lnet_t::ln_refcount, lnet_md2handle(), lnet_md_alloc(), lnet_md_build(), lnet_md_free(), lnet_md_link(), LNET_MD_OP_GET, LNET_MD_OP_PUT, lnet_md_validate(), lnet_res_lock_current(), lnet_res_unlock(), lnet_md_t::options, and the_lnet.
Referenced by lnet_create_rc_data_locked(), lnet_ping(), ptl_send_buf(), and srpc_post_active_rdma().
int LNetMDUnlink (lnet_handle_md_t mdh)
Unlink the memory descriptor from any ME it may be linked to and release the internal resources associated with it.
As a result, active messages associated with the MD may get aborted.
This function does not free the memory region associated with the MD; i.e., the memory the user allocated for this MD. If the ME associated with this MD is not NULL and was created with auto unlink enabled, the ME is unlinked as well (see LNetMEAttach()).
Explicitly unlinking a MD via this function call has the same behavior as a MD that has been automatically unlinked, except that no LNET_EVENT_UNLINK is generated in the latter case.
An unlinked event can be reported in two ways:
If there's no pending operations on the MD, it's unlinked immediately and an LNET_EVENT_UNLINK event is logged before this function returns.
Otherwise, the MD is only marked for deletion when this function returns, and the unlinked event will be piggybacked on the event of the completion of the last operation by setting the unlinked field of the event. No dedicated LNET_EVENT_UNLINK event is generated.
Note that in both cases the unlinked field of the event is always set; no more event will happen on the MD after such an event is logged.
Parameters:
mdh A handle for the MD to be unlinked.
Return values:
0 On success.
-ENOENT If mdh does not point to a valid MD object.
Definition at line 417 of file lib-md.c.
References lnet_handle_any_t::cookie, LASSERT, lnet_t::ln_refcount, lnet_build_unlink_event(), lnet_cpt_of_cookie(), lnet_eq_enqueue_event(), lnet_handle2md(), LNET_MD_FLAG_ABORTED, lnet_md_unlink(), lnet_res_lock(), lnet_res_unlock(), lnet_libmd::md_eq, lnet_libmd::md_flags, lnet_libmd::md_refcount, and the_lnet.
Referenced by lnet_create_rc_data_locked(), lnet_ping(), lnet_ping_md_unlink(), lnet_prune_rc_data(), mdunlink_iterate_helper(), ptl_send_buf(), ptlrpc_handle_rs(), ptlrpc_service_unlink_rqbd(), ptlrpc_unregister_reply(), srpc_handle_rpc(), srpc_post_active_rdma(), srpc_send_rpc(), srpc_service_post_buffer(), and srpc_shutdown_service().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.