Lustre: sptlrpc
sptlrpc
Data Structures
struct bulk_spec_hash
struct sptlrpc_flavor
Full description of flavors being used on a ptlrpc connection, include both regular RPC and bulk transfer parts.
struct sptlrpc_rule
A rule specifies a flavor to be used by a ptlrpc connection between two Lustre parts.
struct sptlrpc_rule_set
A set of rules in memory.
struct vfs_cred
struct ptlrpc_ctx_ops
struct ptlrpc_cli_ctx
struct ptlrpc_sec_cops
client side policy operation vector.
struct ptlrpc_sec_sops
server side policy operation vector.
struct ptlrpc_sec_policy
struct ptlrpc_sec
The ptlrpc_sec represents the client side ptlrpc security facilities, each obd_import (both regular and reverse import) must associate with a ptlrpc_sec.
struct ptlrpc_svc_ctx
struct ptlrpc_user_desc
struct ptlrpc_bulk_sec_desc
Modules
flavor
RPC flavor is represented by a 32 bits integer.
Defines
#define SPTLRPC_MAX_PAYLOAD (1024)
#define PTLRPC_CTX_NEW_BIT (0)
#define PTLRPC_CTX_UPTODATE_BIT (1)
#define PTLRPC_CTX_DEAD_BIT (2)
#define PTLRPC_CTX_ERROR_BIT (3)
#define PTLRPC_CTX_CACHED_BIT (8)
#define PTLRPC_CTX_ETERNAL_BIT (9)
#define PTLRPC_CTX_NEW (1 << PTLRPC_CTX_NEW_BIT)
#define PTLRPC_CTX_UPTODATE (1 << PTLRPC_CTX_UPTODATE_BIT)
#define PTLRPC_CTX_DEAD (1 << PTLRPC_CTX_DEAD_BIT)
#define PTLRPC_CTX_ERROR (1 << PTLRPC_CTX_ERROR_BIT)
#define PTLRPC_CTX_CACHED (1 << PTLRPC_CTX_CACHED_BIT)
#define PTLRPC_CTX_ETERNAL (1 << PTLRPC_CTX_ETERNAL_BIT)
#define PTLRPC_CTX_STATUS_MASK
#define PTLRPC_SEC_FL_REVERSE 0x0001
#define PTLRPC_SEC_FL_ROOTONLY 0x0002
#define PTLRPC_SEC_FL_UDESC 0x0004
#define PTLRPC_SEC_FL_BULK 0x0008
#define PTLRPC_SEC_FL_PAG 0x0010
#define LUSTRE_MAX_GROUPS (128)
#define CFS_CAP_CHOWN_MASK (1 << CFS_CAP_CHOWN)
#define CFS_CAP_SYS_RESOURCE_MASK (1 << CFS_CAP_SYS_RESOURCE)
Enumerations
enum lustre_sec_part {
LUSTRE_SP_CLI = 0, LUSTRE_SP_MDT, LUSTRE_SP_OST, LUSTRE_SP_MGC,
LUSTRE_SP_MGS, LUSTRE_SP_ANY = 0xFF
}
identify the RPC is generated from what part of Lustre.
enum sptlrpc_bulk_hash_alg {
BULK_HASH_ALG_NULL = 0, BULK_HASH_ALG_ADLER32, BULK_HASH_ALG_CRC32, BULK_HASH_ALG_MD5,
BULK_HASH_ALG_SHA1, BULK_HASH_ALG_SHA256, BULK_HASH_ALG_SHA384, BULK_HASH_ALG_SHA512,
BULK_HASH_ALG_MAX
}
enum { BSD_FL_ERR = 1 }
enum secsvc_accept_res { SECSVC_OK = 0, SECSVC_COMPLETE, SECSVC_DROP }
enum { LUSTRE_SEC_NONE = 0, LUSTRE_SEC_REMOTE = 1, LUSTRE_SEC_SPECIFY = 2, LUSTRE_SEC_ALL = 3 }
Functions
static void flvr_set_svc (__u32 *flvr, __u32 svc)
static void flvr_set_bulk_svc (__u32 *flvr, __u32 svc)
const char * sptlrpc_part2name (enum lustre_sec_part sp)
enum lustre_sec_part sptlrpc_target_sec_part (struct obd_device *obd)
int sptlrpc_parse_flavor (const char *str, struct sptlrpc_flavor *flvr)
int sptlrpc_flavor_has_bulk (struct sptlrpc_flavor *flvr)
static void sptlrpc_rule_set_init (struct sptlrpc_rule_set *set)
void sptlrpc_rule_set_free (struct sptlrpc_rule_set *set)
int sptlrpc_rule_set_expand (struct sptlrpc_rule_set *set)
int sptlrpc_rule_set_merge (struct sptlrpc_rule_set *set, struct sptlrpc_rule *rule)
int sptlrpc_rule_set_choose (struct sptlrpc_rule_set *rset, enum lustre_sec_part from, enum lustre_sec_part to, lnet_nid_t nid, struct sptlrpc_flavor *sf)
given from/to/nid, determine a matching flavor in ruleset.
void sptlrpc_rule_set_dump (struct sptlrpc_rule_set *set)
int sptlrpc_process_config (struct lustre_cfg *lcfg)
void sptlrpc_conf_log_start (const char *logname)
void sptlrpc_conf_log_stop (const char *logname)
void sptlrpc_conf_log_update_begin (const char *logname)
void sptlrpc_conf_log_update_end (const char *logname)
mark a config log has been updated
void sptlrpc_conf_client_adapt (struct obd_device *obd)
called by client devices, notify the sptlrpc config has changed and do import_sec_adapt later.
int sptlrpc_conf_target_get_rules (struct obd_device *obd, struct sptlrpc_rule_set *rset, int initial)
called by target devices, extract sptlrpc rules which applies to this target, to be used for future rpc flavor checking.
void sptlrpc_target_choose_flavor (struct sptlrpc_rule_set *rset, enum lustre_sec_part from, lnet_nid_t nid, struct sptlrpc_flavor *flavor)
called by target devices, determine the expected flavor from certain peer (from, nid).
static int sec_is_reverse (struct ptlrpc_sec *sec)
static int sec_is_rootonly (struct ptlrpc_sec *sec)
const char * sptlrpc_get_hash_name (__u8 hash_alg)
__u8 sptlrpc_get_hash_alg (const char *algname)
static int size_roundup_power2 (int size)
void _sptlrpc_enlarge_msg_inplace (struct lustre_msg *msg, int segment, int newsize)
int sptlrpc_register_policy (struct ptlrpc_sec_policy *policy)
int sptlrpc_unregister_policy (struct ptlrpc_sec_policy *policy)
__u32 sptlrpc_name2flavor_base (const char *name)
const char * sptlrpc_flavor2name_base (__u32 flvr)
char * sptlrpc_flavor2name_bulk (struct sptlrpc_flavor *sf, char *buf, int bufsize)
char * sptlrpc_flavor2name (struct sptlrpc_flavor *sf, char *buf, int bufsize)
char * sptlrpc_secflags2str (__u32 flags, char *buf, int bufsize)
static struct ptlrpc_sec_policy * sptlrpc_policy_get (struct ptlrpc_sec_policy *policy)
static void sptlrpc_policy_put (struct ptlrpc_sec_policy *policy)
static unsigned long cli_ctx_status (struct ptlrpc_cli_ctx *ctx)
static int cli_ctx_is_ready (struct ptlrpc_cli_ctx *ctx)
static int cli_ctx_is_refreshed (struct ptlrpc_cli_ctx *ctx)
static int cli_ctx_is_uptodate (struct ptlrpc_cli_ctx *ctx)
static int cli_ctx_is_error (struct ptlrpc_cli_ctx *ctx)
static int cli_ctx_is_dead (struct ptlrpc_cli_ctx *ctx)
static int cli_ctx_is_eternal (struct ptlrpc_cli_ctx *ctx)
struct ptlrpc_sec * sptlrpc_sec_get (struct ptlrpc_sec *sec)
void sptlrpc_sec_put (struct ptlrpc_sec *sec)
int sptlrpc_get_next_secid (void)
void sptlrpc_sec_destroy (struct ptlrpc_sec *sec)
struct ptlrpc_cli_ctx * sptlrpc_cli_ctx_get (struct ptlrpc_cli_ctx *ctx)
void sptlrpc_cli_ctx_put (struct ptlrpc_cli_ctx *ctx, int sync)
void sptlrpc_cli_ctx_expire (struct ptlrpc_cli_ctx *ctx)
Expire the client context immediately.
void sptlrpc_cli_ctx_wakeup (struct ptlrpc_cli_ctx *ctx)
To wake up the threads who are waiting for this client context.
int sptlrpc_cli_ctx_display (struct ptlrpc_cli_ctx *ctx, char *buf, int bufsize)
int sptlrpc_cli_wrap_request (struct ptlrpc_request *req)
Used by ptlrpc client, to perform the pre-defined security transformation upon the request message of req.
int sptlrpc_cli_unwrap_reply (struct ptlrpc_request *req)
Used by ptlrpc client, to perform security transformation upon the reply message of req.
int sptlrpc_cli_alloc_reqbuf (struct ptlrpc_request *req, int msgsize)
Used by ptlrpc client to allocate request buffer of req.
void sptlrpc_cli_free_reqbuf (struct ptlrpc_request *req)
Used by ptlrpc client to free request buffer of req.
int sptlrpc_cli_alloc_repbuf (struct ptlrpc_request *req, int msgsize)
Used by ptlrpc client to allocate reply buffer of req.
void sptlrpc_cli_free_repbuf (struct ptlrpc_request *req)
Used by ptlrpc client to free reply buffer of req.
int sptlrpc_cli_enlarge_reqbuf (struct ptlrpc_request *req, int segment, int newsize)
Used by ptlrpc client to enlarge the segment of request message pointed by req->rq_reqmsg to size newsize, all previously filled-in data will be preserved after the enlargement.
int sptlrpc_cli_unwrap_early_reply (struct ptlrpc_request *req, struct ptlrpc_request **req_ret)
Used by ptlrpc client, to perform security transformation upon the early reply message of req.
void sptlrpc_cli_finish_early_reply (struct ptlrpc_request *early_req)
Used by ptlrpc client, to release a processed early reply early_req.
void sptlrpc_request_out_callback (struct ptlrpc_request *req)
int sptlrpc_import_sec_adapt (struct obd_import *imp, struct ptlrpc_svc_ctx *ctx, struct sptlrpc_flavor *flvr)
To get an appropriate ptlrpc_sec for the imp, according to the current configuration.
struct ptlrpc_sec * sptlrpc_import_sec_ref (struct obd_import *imp)
void sptlrpc_import_sec_put (struct obd_import *imp)
int sptlrpc_import_check_ctx (struct obd_import *imp)
Given an import imp, check whether current user has a valid context or not.
void sptlrpc_import_flush_root_ctx (struct obd_import *imp)
void sptlrpc_import_flush_my_ctx (struct obd_import *imp)
void sptlrpc_import_flush_all_ctx (struct obd_import *imp)
int sptlrpc_req_get_ctx (struct ptlrpc_request *req)
Given a req, find or allocate an appropriate context for it.
void sptlrpc_req_put_ctx (struct ptlrpc_request *req, int sync)
Drop the context for req.
int sptlrpc_req_refresh_ctx (struct ptlrpc_request *req, long timeout)
To refresh the context of , if it's not up-to-date.
int sptlrpc_req_replace_dead_ctx (struct ptlrpc_request *req)
If current context of req is dead somehow, e.g.
void sptlrpc_req_set_flavor (struct ptlrpc_request *req, int opcode)
Initialize flavor settings for req, according to opcode.
int sptlrpc_parse_rule (char *param, struct sptlrpc_rule *rule)
void sptlrpc_gc_add_sec (struct ptlrpc_sec *sec)
void sptlrpc_gc_del_sec (struct ptlrpc_sec *sec)
void sptlrpc_gc_add_ctx (struct ptlrpc_cli_ctx *ctx)
const char * sec2target_str (struct ptlrpc_sec *sec)
int sptlrpc_lprocfs_cliobd_attach (struct obd_device *dev)
int sptlrpc_svc_unwrap_request (struct ptlrpc_request *req)
Used by ptlrpc server, to perform transformation upon request message of incoming req.
int sptlrpc_svc_alloc_rs (struct ptlrpc_request *req, int msglen)
Used by ptlrpc server, to allocate reply buffer for req.
int sptlrpc_svc_wrap_reply (struct ptlrpc_request *req)
Used by ptlrpc server, to perform transformation upon reply message.
void sptlrpc_svc_free_rs (struct ptlrpc_reply_state *rs)
Used by ptlrpc server, to free reply_state.
void sptlrpc_svc_ctx_addref (struct ptlrpc_request *req)
void sptlrpc_svc_ctx_decref (struct ptlrpc_request *req)
void sptlrpc_svc_ctx_invalidate (struct ptlrpc_request *req)
int sptlrpc_target_export_check (struct obd_export *exp, struct ptlrpc_request *req)
Given an export exp, check whether the flavor of incoming req is allowed by the export exp.
void sptlrpc_target_update_exp_flavor (struct obd_device *obd, struct sptlrpc_rule_set *rset)
int sptlrpc_svc_install_rvs_ctx (struct obd_import *imp, struct ptlrpc_svc_ctx *ctx)
int sptlrpc_cli_install_rvs_ctx (struct obd_import *imp, struct ptlrpc_cli_ctx *ctx)
int sptlrpc_enc_pool_add_user (void)
int sptlrpc_enc_pool_del_user (void)
int sptlrpc_enc_pool_get_pages (struct ptlrpc_bulk_desc *desc)
void sptlrpc_enc_pool_put_pages (struct ptlrpc_bulk_desc *desc)
int get_free_pages_in_pool (void)
int pool_is_at_full_capacity (void)
int sptlrpc_cli_wrap_bulk (struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
Perform transformation upon bulk data pointed by desc.
int sptlrpc_cli_unwrap_bulk_read (struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc, int nob)
This is called after unwrap the reply message.
int sptlrpc_cli_unwrap_bulk_write (struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
This is called after unwrap the reply message.
int sptlrpc_get_bulk_checksum (struct ptlrpc_bulk_desc *desc, __u8 alg, void *buf, int buflen)
int bulk_sec_desc_unpack (struct lustre_msg *msg, int offset, int swabbed)
static int sptlrpc_user_desc_size (int ngroups)
int sptlrpc_current_user_desc_size (void)
int sptlrpc_pack_user_desc (struct lustre_msg *msg, int offset)
int sptlrpc_unpack_user_desc (struct lustre_msg *req, int offset, int swabbed)
Variables
struct proc_dir_entry * sptlrpc_proc_root
Define Documentation
#define CFS_CAP_CHOWN_MASK (1 << CFS_CAP_CHOWN)
Definition at line 1169 of file lustre_sec.h.
Referenced by new_init_ucred().
#define CFS_CAP_SYS_RESOURCE_MASK (1 << CFS_CAP_SYS_RESOURCE)
Definition at line 1170 of file lustre_sec.h.
Referenced by __mdd_index_insert_only(), mdd_object_create(), and new_init_ucred().
#define LUSTRE_MAX_GROUPS (128)
Definition at line 887 of file lustre_sec.h.
Referenced by sptlrpc_current_user_desc_size(), and sptlrpc_unpack_user_desc().
#define PTLRPC_CTX_CACHED (1 << PTLRPC_CTX_CACHED_BIT)
Definition at line 526 of file lustre_sec.h.
Referenced by gss_cli_ctx_flags2str(), null_init_internal(), and plain_sec_install_ctx().
#define PTLRPC_CTX_CACHED_BIT (8)
Definition at line 519 of file lustre_sec.h.
Referenced by ctx_check_death_locked_pf(), ctx_destroy_kr(), ctx_enhash_pf(), ctx_enlist_kr(), ctx_list_destroy_pf(), ctx_unhash_pf(), ctx_unlist_kr(), gss_cli_ctx_die_pf(), gss_sec_release_ctx_pf(), and unbind_key_ctx().
#define PTLRPC_CTX_DEAD (1 << PTLRPC_CTX_DEAD_BIT)
Definition at line 524 of file lustre_sec.h.
Referenced by cli_ctx_is_dead(), gss_cli_ctx_flags2str(), and gss_ctx_refresh_pf().
#define PTLRPC_CTX_DEAD_BIT (2)
Definition at line 517 of file lustre_sec.h.
Referenced by cli_ctx_expire(), flush_spec_ctx_cache_kr(), gss_sec_flush_ctx_cache_pf(), sptlrpc_req_refresh_ctx(), and sptlrpc_req_replace_dead_ctx().
#define PTLRPC_CTX_ERROR (1 << PTLRPC_CTX_ERROR_BIT)
Definition at line 525 of file lustre_sec.h.
Referenced by cli_ctx_is_dead(), cli_ctx_is_error(), gss_cli_ctx_flags2str(), and gss_ctx_refresh_pf().
#define PTLRPC_CTX_ERROR_BIT (3)
Definition at line 518 of file lustre_sec.h.
Referenced by gss_kt_update(), gss_msg_fail_ctx(), gss_pipe_downcall(), and sptlrpc_req_refresh_ctx().
#define PTLRPC_CTX_ETERNAL (1 << PTLRPC_CTX_ETERNAL_BIT)
Definition at line 527 of file lustre_sec.h.
Referenced by cli_ctx_is_eternal(), gss_cli_ctx_flags2str(), and null_init_internal().
#define PTLRPC_CTX_ETERNAL_BIT (9)
Definition at line 520 of file lustre_sec.h.
#define PTLRPC_CTX_NEW (1 << PTLRPC_CTX_NEW_BIT)
Definition at line 522 of file lustre_sec.h.
Referenced by gss_cli_ctx_flags2str(), and gss_cli_ctx_init_common().
#define PTLRPC_CTX_NEW_BIT (0)
Definition at line 515 of file lustre_sec.h.
Referenced by ctx_create_kr(), gss_sec_lookup_ctx_pf(), and sptlrpc_req_refresh_ctx().
#define PTLRPC_CTX_STATUS_MASK
Value:
(PTLRPC_CTX_NEW_BIT    |       \
                                        PTLRPC_CTX_UPTODATE   |       \
                                        PTLRPC_CTX_DEAD       |       \
                                        PTLRPC_CTX_ERROR)
Definition at line 529 of file lustre_sec.h.
Referenced by cli_ctx_status(), and gss_ctx_refresh_pf().
#define PTLRPC_CTX_UPTODATE (1 << PTLRPC_CTX_UPTODATE_BIT)
Definition at line 523 of file lustre_sec.h.
Referenced by cli_ctx_is_ready(), cli_ctx_is_uptodate(), gss_cli_ctx_fini_common(), gss_cli_ctx_flags2str(), gss_ctx_refresh_pf(), null_init_internal(), and plain_sec_install_ctx().
#define PTLRPC_CTX_UPTODATE_BIT (1)
Definition at line 516 of file lustre_sec.h.
Referenced by cli_ctx_expire(), flush_spec_ctx_cache_kr(), gss_cli_ctx_uptodate(), gss_sec_flush_ctx_cache_pf(), gss_sec_release_ctx_pf(), sptlrpc_req_refresh_ctx(), and sptlrpc_req_replace_dead_ctx().
#define PTLRPC_SEC_FL_BULK 0x0008
Definition at line 835 of file lustre_sec.h.
Referenced by flavor_set_flags(), sec_flags2str(), and sptlrpc_secflags2str().
#define PTLRPC_SEC_FL_PAG 0x0010
Definition at line 836 of file lustre_sec.h.
#define PTLRPC_SEC_FL_REVERSE 0x0001
Definition at line 832 of file lustre_sec.h.
Referenced by get_my_ctx(), gss_round_ctx_expiry(), gss_sec_create_pf(), sec_flags2str(), sec_is_reverse(), sptlrpc_import_sec_adapt(), sptlrpc_sec_create(), and sptlrpc_secflags2str().
#define PTLRPC_SEC_FL_ROOTONLY 0x0002
Definition at line 833 of file lustre_sec.h.
Referenced by flavor_set_flags(), get_my_ctx(), gss_sec_create_pf(), sec_flags2str(), sec_is_rootonly(), sptlrpc_import_sec_adapt(), sptlrpc_sec_create(), and sptlrpc_secflags2str().
#define PTLRPC_SEC_FL_UDESC 0x0004
Definition at line 834 of file lustre_sec.h.
Referenced by flavor_set_flags(), sec_flags2str(), sptlrpc_req_set_flavor(), and sptlrpc_secflags2str().
#define SPTLRPC_MAX_PAYLOAD (1024)
Definition at line 388 of file lustre_sec.h.
Referenced by ptlrpc_init_rq_pool(), and ptlrpc_register_service().
Enumeration Type Documentation
anonymous enum
Enumerator:
BSD_FL_ERR
Definition at line 917 of file lustre_sec.h.
anonymous enum
Enumerator:
LUSTRE_SEC_NONE
LUSTRE_SEC_REMOTE
LUSTRE_SEC_SPECIFY
LUSTRE_SEC_ALL
Definition at line 1172 of file lustre_sec.h.
enum lustre_sec_part
identify the RPC is generated from what part of Lustre.
It's encoded into RPC requests and to be checked by ptlrpc service.
Enumerator:
LUSTRE_SP_CLI
LUSTRE_SP_MDT
LUSTRE_SP_OST
LUSTRE_SP_MGC
LUSTRE_SP_MGS
LUSTRE_SP_ANY
Definition at line 315 of file lustre_sec.h.
enum secsvc_accept_res
Enumerator:
SECSVC_OK
SECSVC_COMPLETE
SECSVC_DROP
Definition at line 1101 of file lustre_sec.h.
enum sptlrpc_bulk_hash_alg
Enumerator:
BULK_HASH_ALG_NULL
BULK_HASH_ALG_ADLER32
BULK_HASH_ALG_CRC32
BULK_HASH_ALG_MD5
BULK_HASH_ALG_SHA1
BULK_HASH_ALG_SHA256
BULK_HASH_ALG_SHA384
BULK_HASH_ALG_SHA512
BULK_HASH_ALG_MAX
Definition at line 902 of file lustre_sec.h.
Function Documentation
void _sptlrpc_enlarge_msg_inplace (struct lustre_msg * msg, int segment, int newsize)
Definition at line 1631 of file sec.c.
References LASSERT, lustre_msg_buf(), LUSTRE_MSG_MAGIC_V2, and lustre_msg_size_v2().
Referenced by gss_enlarge_reqbuf_intg(), gss_enlarge_reqbuf_priv(), null_enlarge_reqbuf(), and plain_enlarge_reqbuf().
int bulk_sec_desc_unpack (struct lustre_msg * msg, int offset, int swabbed)
Definition at line 879 of file sec_bulk.c.
References __swab32s, ptlrpc_bulk_sec_desc::bsd_nob, ptlrpc_bulk_sec_desc::bsd_svc, ptlrpc_bulk_sec_desc::bsd_type, ptlrpc_bulk_sec_desc::bsd_version, CERROR, lustre_msg_buf(), size, SPTLRPC_BULK_MAX, SPTLRPC_BULK_SVC_INTG, SPTLRPC_BULK_SVC_NULL, SPTLRPC_BULK_SVC_PRIV, and unlikely.
Referenced by gss_cli_ctx_unseal(), gss_cli_ctx_verify(), gss_svc_unseal_request(), gss_svc_verify_request(), and plain_unpack_bsd().
static int cli_ctx_is_dead (struct ptlrpc_cli_ctx * ctx) [inline, static]
Definition at line 1019 of file lustre_sec.h.
References ptlrpc_cli_ctx::cc_flags, PTLRPC_CTX_DEAD, and PTLRPC_CTX_ERROR.
Referenced by cli_ctx_check_death().
static int cli_ctx_is_error (struct ptlrpc_cli_ctx * ctx) [inline, static]
Definition at line 1013 of file lustre_sec.h.
References ptlrpc_cli_ctx::cc_flags, and PTLRPC_CTX_ERROR.
Referenced by gss_do_ctx_fini_rpc(), and sptlrpc_import_check_ctx().
static int cli_ctx_is_eternal (struct ptlrpc_cli_ctx * ctx) [inline, static]
Definition at line 1025 of file lustre_sec.h.
References ptlrpc_cli_ctx::cc_flags, and PTLRPC_CTX_ETERNAL.
Referenced by sptlrpc_import_check_ctx(), and sptlrpc_req_refresh_ctx().
static int cli_ctx_is_ready (struct ptlrpc_cli_ctx * ctx) [inline, static]
Definition at line 995 of file lustre_sec.h.
References cli_ctx_status(), and PTLRPC_CTX_UPTODATE.
Referenced by gss_cli_ctx_validate_kr(), and gss_cli_ctx_validate_pf().
static int cli_ctx_is_refreshed (struct ptlrpc_cli_ctx * ctx) [inline, static]
Definition at line 1001 of file lustre_sec.h.
References cli_ctx_status().
Referenced by ctx_check_refresh(), gss_kt_update(), and sptlrpc_req_refresh_ctx().
static int cli_ctx_is_uptodate (struct ptlrpc_cli_ctx * ctx) [inline, static]
Definition at line 1007 of file lustre_sec.h.
References ptlrpc_cli_ctx::cc_flags, and PTLRPC_CTX_UPTODATE.
Referenced by gss_do_ctx_fini_rpc().
static unsigned long cli_ctx_status (struct ptlrpc_cli_ctx * ctx) [inline, static]
Definition at line 989 of file lustre_sec.h.
References ptlrpc_cli_ctx::cc_flags, and PTLRPC_CTX_STATUS_MASK.
Referenced by cli_ctx_is_ready(), and cli_ctx_is_refreshed().
static void flvr_set_bulk_svc (__u32 * flvr, __u32 svc) [inline, static]
Definition at line 270 of file lustre_sec.h.
References LASSERT, MAKE_FLVR, SPTLRPC_BULK_SVC_MAX, SPTLRPC_FLVR_BULK_TYPE, SPTLRPC_FLVR_MECH, SPTLRPC_FLVR_POLICY, and SPTLRPC_FLVR_SVC.
Referenced by sptlrpc_parse_flavor().
static void flvr_set_svc (__u32 * flvr, __u32 svc) [inline, static]
Definition at line 260 of file lustre_sec.h.
References LASSERT, MAKE_FLVR, SPTLRPC_FLVR_BULK_SVC, SPTLRPC_FLVR_BULK_TYPE, SPTLRPC_FLVR_MECH, SPTLRPC_FLVR_POLICY, and SPTLRPC_SVC_MAX.
Referenced by sptlrpc_req_set_flavor().
int get_free_pages_in_pool (void)
Definition at line 528 of file sec_bulk.c.
References ptlrpc_enc_page_pool::epp_free_pages, and page_pools.
Referenced by ptlrpc_send_new_req().
int pool_is_at_full_capacity (void)
Definition at line 537 of file sec_bulk.c.
References ptlrpc_enc_page_pool::epp_max_pages, ptlrpc_enc_page_pool::epp_total_pages, and page_pools.
Referenced by ptlrpc_send_new_req().
const char* sec2target_str (struct ptlrpc_sec * sec)
Definition at line 2511 of file sec.c.
References client_obd::cl_target_uuid, obd_device::cli, obd_import::imp_obd, obd_uuid2str(), ptlrpc_sec::ps_import, sec_is_reverse(), and obd_device::u.
Referenced by cli_ctx_expire(), flush_spec_ctx_cache_kr(), gss_cli_ctx_fini_common(), gss_cli_ctx_handle_err_notify(), gss_cli_ctx_init_common(), gss_cli_ctx_uptodate(), gss_ctx_refresh_pf(), gss_do_ctx_fini_rpc(), gss_sec_flush_ctx_cache_pf(), sec_process_ctx_list(), sptlrpc_gc_add_ctx(), and sptlrpc_req_ctx_switch().
static int sec_is_reverse (struct ptlrpc_sec * sec) [inline, static]
Definition at line 868 of file lustre_sec.h.
References ptlrpc_sec::ps_flvr, PTLRPC_SEC_FL_REVERSE, and sptlrpc_flavor::sf_flags.
Referenced by dispose_ctx_list_kr(), flush_user_ctx_cache_kr(), gss_cli_ctx_finalize(), gss_cli_ctx_fini_common(), gss_cli_ctx_handle_err_notify(), gss_cli_ctx_uptodate(), gss_do_ctx_fini_rpc(), gss_sec_create_common(), gss_sec_lookup_ctx_kr(), gss_sec_lookup_ctx_pf(), rvs_sec_install_root_ctx_kr(), sec2target_str(), and sec_lookup_root_ctx_kr().
static int sec_is_rootonly (struct ptlrpc_sec * sec) [inline, static]
Definition at line 873 of file lustre_sec.h.
References ptlrpc_sec::ps_flvr, PTLRPC_SEC_FL_ROOTONLY, and sptlrpc_flavor::sf_flags.
Referenced by flush_user_ctx_cache_kr(), and user_is_root().
static int size_roundup_power2 (int size) [inline, static]
Definition at line 941 of file lustre_sec.h.
Referenced by do_alloc_repbuf(), gss_alloc_reqbuf_intg(), gss_alloc_reqbuf_priv(), gss_enlarge_reqbuf_intg(), gss_enlarge_reqbuf_priv(), lod_ea_store_resize(), mdt_big_xattr_get(), null_alloc_repbuf(), null_alloc_reqbuf(), null_enlarge_reqbuf(), osd_oi_mod_init(), osd_options_init(), plain_alloc_repbuf(), plain_alloc_reqbuf(), plain_enlarge_reqbuf(), and sptlrpc_cli_unwrap_early_reply().
int sptlrpc_cli_alloc_repbuf (struct ptlrpc_request * req, int msgsize)
Used by ptlrpc client to allocate reply buffer of req.
Note:
After this, req->rq_repmsg is still not accessible.
Definition at line 1707 of file sec.c.
References ptlrpc_sec_cops::alloc_repbuf, ptlrpc_cli_ctx::cc_sec, ENTRY, LASSERT, ptlrpc_sec::ps_policy, RETURN, ptlrpc_request::rq_repbuf, and ptlrpc_sec_policy::sp_cops.
Referenced by ptl_send_rpc().
int sptlrpc_cli_alloc_reqbuf (struct ptlrpc_request * req, int msgsize)
Used by ptlrpc client to allocate request buffer of req.
Upon return successfully, req->rq_reqmsg points to a buffer with size msgsize.
Definition at line 1580 of file sec.c.
References ptlrpc_sec_cops::alloc_reqbuf, ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_sec, LASSERT, LASSERT_ATOMIC_POS, ptlrpc_sec::ps_policy, ptlrpc_request::rq_clrbuf, ptlrpc_request::rq_pool, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqmsg, and ptlrpc_sec_policy::sp_cops.
Referenced by lustre_pack_request_v2(), and sptlrpc_req_ctx_switch().
int sptlrpc_cli_ctx_display (struct ptlrpc_cli_ctx * ctx, char * buf, int bufsize)
Definition at line 347 of file sec.c.
References ptlrpc_cli_ctx::cc_ops, ptlrpc_ctx_ops::display, and LASSERT.
void sptlrpc_cli_ctx_expire (struct ptlrpc_cli_ctx * ctx)
Expire the client context immediately.
Precondition:
Caller must hold at least 1 reference on the ctx.
Definition at line 322 of file sec.c.
References ptlrpc_cli_ctx::cc_ops, ptlrpc_ctx_ops::die, and LASSERT.
Referenced by gss_cli_ctx_handle_err_notify(), gss_msg_fail_ctx(), and gss_pipe_downcall().
struct ptlrpc_cli_ctx* sptlrpc_cli_ctx_get (struct ptlrpc_cli_ctx * ctx) [read]
Definition at line 296 of file sec.c.
References ptlrpc_cli_ctx::cc_refcount.
Referenced by gss_ctx_refresh_pf(), gss_kt_update(), ptlrpc_request_bufs_pack(), sptlrpc_cli_unwrap_early_reply(), and sptlrpc_req_replace_dead_ctx().
void sptlrpc_cli_ctx_put (struct ptlrpc_cli_ctx * ctx, int sync)
Definition at line 303 of file sec.c.
References ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_sec, LASSERT, LASSERT_ATOMIC_POS, ptlrpc_sec::ps_policy, ptlrpc_sec_cops::release_ctx, and ptlrpc_sec_policy::sp_cops.
Referenced by gss_kt_update(), gss_release_msg(), plain_create_sec(), plain_flush_ctx_cache(), ptlrpc_request_bufs_pack(), sec_process_ctx_list(), sptlrpc_cli_finish_early_reply(), sptlrpc_cli_unwrap_early_reply(), sptlrpc_import_check_ctx(), sptlrpc_req_put_ctx(), and sptlrpc_req_replace_dead_ctx().
void sptlrpc_cli_ctx_wakeup (struct ptlrpc_cli_ctx * ctx)
To wake up the threads who are waiting for this client context.
Called after some status change happened on ctx.
Definition at line 333 of file sec.c.
References ptlrpc_cli_ctx::cc_lock, ptlrpc_cli_ctx::cc_req_list, list_del_init(), list_for_each_entry_safe, ptlrpc_client_wake_req(), and rq_ctx_chain.
Referenced by cli_ctx_expire(), dispose_ctx_list_kr(), gss_cli_ctx_uptodate(), and gss_release_msg().
int sptlrpc_cli_enlarge_reqbuf (struct ptlrpc_request * req, int segment, int newsize)
Used by ptlrpc client to enlarge the segment of request message pointed by req->rq_reqmsg to size newsize, all previously filled-in data will be preserved after the enlargement.
this must be called after original request buffer being allocated.
Note:
after this be called, rq_reqmsg and rq_reqlen might have been changed, so caller should refresh its local pointers if needed.
Definition at line 1681 of file sec.c.
References ptlrpc_cli_ctx::cc_sec, ptlrpc_sec_cops::enlarge_reqbuf, LASSERT, lustre_msg, msg, ptlrpc_sec::ps_policy, ptlrpc_request::rq_reqmsg, and ptlrpc_sec_policy::sp_cops.
Referenced by mdc_realloc_openmsg().
void sptlrpc_cli_finish_early_reply (struct ptlrpc_request * early_req)
Used by ptlrpc client, to release a processed early reply early_req.
Precondition:
early_req was obtained from calling sptlrpc_cli_unwrap_early_reply().
Definition at line 1221 of file sec.c.
References LASSERT, OBD_FREE_LARGE, ptlrpc_request_cache_free(), ptlrpc_request::rq_repbuf, ptlrpc_request::rq_repbuf_len, ptlrpc_request::rq_repdata, ptlrpc_request::rq_repmsg, and sptlrpc_cli_ctx_put().
Referenced by ptlrpc_at_recv_early_reply().
void sptlrpc_cli_free_repbuf (struct ptlrpc_request * req)
Used by ptlrpc client to free reply buffer of req.
After this req->rq_repmsg is set to NULL and should not be accessed anymore.
Definition at line 1728 of file sec.c.
References ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_sec, ENTRY, EXIT, ptlrpc_sec_cops::free_repbuf, LASSERT, LASSERT_ATOMIC_POS, ptlrpc_sec::ps_policy, ptlrpc_request::rq_repbuf, ptlrpc_request::rq_repbuf_len, ptlrpc_request::rq_repmsg, and ptlrpc_sec_policy::sp_cops.
Referenced by __ptlrpc_free_req(), after_reply(), and sptlrpc_req_ctx_switch().
void sptlrpc_cli_free_reqbuf (struct ptlrpc_request * req)
Used by ptlrpc client to free request buffer of req.
After this req->rq_reqmsg is set to NULL and should not be accessed anymore.
Definition at line 1610 of file sec.c.
References ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_sec, ptlrpc_sec_cops::free_reqbuf, LASSERT, LASSERT_ATOMIC_POS, ptlrpc_sec::ps_policy, ptlrpc_request::rq_clrbuf, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqmsg, and ptlrpc_sec_policy::sp_cops.
Referenced by __ptlrpc_free_req(), and sptlrpc_req_ctx_switch().
int sptlrpc_cli_install_rvs_ctx (struct obd_import * imp, struct ptlrpc_cli_ctx * ctx)
Definition at line 1749 of file sec.c.
References ptlrpc_cli_ctx::cc_sec, ptlrpc_sec_cops::install_rctx, ptlrpc_sec::ps_policy, and ptlrpc_sec_policy::sp_cops.
int sptlrpc_cli_unwrap_bulk_read (struct ptlrpc_request * req, struct ptlrpc_bulk_desc * desc, int nob)
This is called after unwrap the reply message.
return nob of actual plain text size received, or error code.
Definition at line 2286 of file sec.c.
References ptlrpc_bulk_desc::bd_nob_transferred, ptlrpc_cli_ctx::cc_ops, LASSERT, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_pack_bulk, and ptlrpc_ctx_ops::unwrap_bulk.
Referenced by mdc_getpage(), mgc_process_recover_log(), osc_brw_fini_request(), osp_it_fetch(), osp_md_read(), and qsd_fetch_index().
int sptlrpc_cli_unwrap_bulk_write (struct ptlrpc_request * req, struct ptlrpc_bulk_desc * desc)
This is called after unwrap the reply message.
return 0 for success or error code.
Definition at line 2312 of file sec.c.
References ptlrpc_bulk_desc::bd_nob, ptlrpc_bulk_desc::bd_nob_transferred, ptlrpc_cli_ctx::cc_ops, CERROR, LASSERT, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_pack_bulk, and ptlrpc_ctx_ops::unwrap_bulk.
Referenced by osc_brw_fini_request().
int sptlrpc_cli_unwrap_early_reply (struct ptlrpc_request * req, struct ptlrpc_request ** req_ret)
Used by ptlrpc client, to perform security transformation upon the early reply message of req.
We expect the rq_reply_off is 0, and rq_nob_received is the early reply size.
Because the receive buffer might be still posted, the reply data might be changed at any time, no matter we're holding rq_lock or not. For this reason we allocate a separate ptlrpc_request and reply buffer for early reply processing.
Return values:
0 success, req_ret is filled with a duplicated ptlrpc_request. Later the caller must call sptlrpc_cli_finish_early_reply() on the returned *req_ret to release it.
-ev error number, and req_ret will not be set.
Definition at line 1130 of file sec.c.
References CERROR, D_ADAPTTO, DEBUG_REQ, do_cli_unwrap_reply(), ENTRY, GOTO, LASSERT, lustre_msg, OBD_ALLOC_LARGE, OBD_FREE_LARGE, ptlrpc_cli_req_init(), ptlrpc_request_cache_alloc(), ptlrpc_request_cache_free(), RETURN, ptlrpc_request::rq_early, ptlrpc_request::rq_flvr, ptlrpc_request::rq_lock, ptlrpc_request::rq_nob_received, ptlrpc_request::rq_repbuf, ptlrpc_request::rq_repbuf_len, ptlrpc_request::rq_repdata, ptlrpc_request::rq_repdata_len, ptlrpc_request::rq_replied, ptlrpc_request::rq_reply_off, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_reqmsg, size_roundup_power2(), sptlrpc_cli_ctx_get(), and sptlrpc_cli_ctx_put().
Referenced by ptlrpc_at_recv_early_reply().
int sptlrpc_cli_unwrap_reply (struct ptlrpc_request * req)
Used by ptlrpc client, to perform security transformation upon the reply message of req.
After return successfully, req->rq_repmsg points to the reply message in clear text.
Precondition:
the reply buffer should have been un-posted from LNet, so nothing is going to change.
Definition at line 1090 of file sec.c.
References CERROR, do_cli_unwrap_reply(), LASSERT, lustre_msg, lustre_msghdr_get_flags(), MSGHDR_AT_SUPPORT, ptlrpc_request::rq_nob_received, ptlrpc_request::rq_repbuf, ptlrpc_request::rq_repbuf_len, ptlrpc_request::rq_repdata, ptlrpc_request::rq_repdata_len, ptlrpc_request::rq_reply_off, ptlrpc_request::rq_repmsg, and ptlrpc_request::rq_reqmsg.
Referenced by after_reply().
int sptlrpc_cli_wrap_bulk (struct ptlrpc_request * req, struct ptlrpc_bulk_desc * desc)
Perform transformation upon bulk data pointed by desc.
This is called before transforming the request message.
Definition at line 2265 of file sec.c.
References ptlrpc_cli_ctx::cc_ops, LASSERT, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_pack_bulk, and ptlrpc_ctx_ops::wrap_bulk.
Referenced by sptlrpc_cli_wrap_request().
int sptlrpc_cli_wrap_request (struct ptlrpc_request * req)
Used by ptlrpc client, to perform the pre-defined security transformation upon the request message of req.
After this function called, req->rq_reqmsg is still accessible as clear text.
Definition at line 978 of file sec.c.
References ptlrpc_cli_ctx::cc_ops, ptlrpc_cli_ctx::cc_sec, ENTRY, LASSERT, LBUG, RETURN, ptlrpc_request::rq_clrbuf, ptlrpc_request::rq_flvr, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqbuf_len, ptlrpc_request::rq_reqdata_len, ptlrpc_ctx_ops::seal, sptlrpc_flavor::sf_rpc, ptlrpc_ctx_ops::sign, sptlrpc_cli_wrap_bulk(), SPTLRPC_FLVR_SVC, SPTLRPC_SVC_AUTH, SPTLRPC_SVC_INTG, SPTLRPC_SVC_NULL, and SPTLRPC_SVC_PRIV.
Referenced by ptl_send_rpc().
void sptlrpc_conf_client_adapt (struct obd_device * obd)
called by client devices, notify the sptlrpc config has changed and do import_sec_adapt later.
Definition at line 905 of file sec_config.c.
References CDEBUG, cfs_time_current_sec(), client_obd::cl_import, client_obd::cl_sem, client_obd::cl_target_uuid, obd_device::cli, D_SEC, ENTRY, EXIT, obd_import::imp_lock, obd_import::imp_sec, obd_import::imp_sec_expire, LASSERT, LUSTRE_LWP_NAME, LUSTRE_MDC_NAME, LUSTRE_OSC_NAME, LUSTRE_OSP_NAME, obd_device::obd_type, SEC_ADAPT_DELAY, obd_type::typ_name, obd_device::u, and obd_uuid::uuid.
Referenced by lwp_set_info_async(), mdc_set_info_async(), osc_set_info_async(), and osp_obd_set_info_async().
void sptlrpc_conf_log_start (const char * logname)
Definition at line 789 of file sec_config.c.
References logname2fsname(), sptlrpc_conf_get(), and sptlrpc_conf_lock.
Referenced by do_config_log_add().
void sptlrpc_conf_log_stop (const char * logname)
Definition at line 802 of file sec_config.c.
References logname2fsname(), sptlrpc_conf_free(), sptlrpc_conf_get(), and sptlrpc_conf_lock.
Referenced by config_log_put().
void sptlrpc_conf_log_update_begin (const char * logname)
Definition at line 737 of file sec_config.c.
References LASSERT, logname2fsname(), sptlrpc_conf::sc_local, sptlrpc_conf::sc_modified, sptlrpc_conf::sc_updated, sptlrpc_conf_free_rsets(), sptlrpc_conf_get(), and sptlrpc_conf_lock.
Referenced by mgc_process_cfg_log().
void sptlrpc_conf_log_update_end (const char * logname)
mark a config log has been updated
Definition at line 763 of file sec_config.c.
References logname2fsname(), sptlrpc_conf::sc_modified, sptlrpc_conf::sc_updated, sptlrpc_conf_get(), and sptlrpc_conf_lock.
Referenced by mgc_process_cfg_log().
int sptlrpc_conf_target_get_rules (struct obd_device * obd, struct sptlrpc_rule_set * rset, int initial)
called by target devices, extract sptlrpc rules which applies to this target, to be used for future rpc flavor checking.
Definition at line 1148 of file sec_config.c.
References CDEBUG, CERROR, D_SEC, ENTRY, GOTO, LASSERT, LUSTRE_MDT_NAME, LUSTRE_OST_NAME, LUSTRE_SP_ANY, LUSTRE_SP_MDT, LUSTRE_SP_OST, MTI_NAME_MAXLEN, obd_device::obd_name, obd_device::obd_type, obd_device::obd_uuid, RETURN, sptlrpc_conf::sc_local, sptlrpc_conf::sc_modified, sptlrpc_conf::sc_rset, sptlrpc_conf::sc_updated, sptlrpc_conf_tgt::sct_rset, sptlrpc_conf_free_rsets(), sptlrpc_conf_get(), sptlrpc_conf_get_tgt(), sptlrpc_conf_lock, sptlrpc_rule_set_extract(), sptlrpc_target_local_copy_conf(), sptlrpc_target_local_read_conf(), target2fsname(), obd_type::typ_name, and obd_uuid::uuid.
Referenced by tgt_adapt_sptlrpc_conf().
int sptlrpc_current_user_desc_size (void)
Definition at line 2432 of file sec.c.
References current_ngroups, LUSTRE_MAX_GROUPS, and sptlrpc_user_desc_size().
Referenced by gss_alloc_reqbuf_intg(), gss_alloc_reqbuf_priv(), and plain_alloc_reqbuf().
int sptlrpc_enc_pool_add_user (void)
Definition at line 729 of file sec_bulk.c.
References enc_pools_add_pages(), enc_pools_wakeup(), ptlrpc_enc_page_pool::epp_growing, ptlrpc_enc_page_pool::epp_lock, ptlrpc_enc_page_pool::epp_total_pages, page_pools, and PTLRPC_MAX_BRW_PAGES.
Referenced by gss_sec_create_common().
int sptlrpc_enc_pool_del_user (void)
Definition at line 753 of file sec_bulk.c.
Referenced by gss_sec_destroy_common().
int sptlrpc_enc_pool_get_pages (struct ptlrpc_bulk_desc * desc)
Definition at line 546 of file sec_bulk.c.
References BD_GET_ENC_KIOV, ptlrpc_bulk_desc::bd_iov_count, ptlrpc_bulk_desc::bd_type, cfs_time_current(), cfs_time_current_sec(), enc_pools_add_pages(), enc_pools_should_grow(), enc_pools_wakeup(), ptlrpc_enc_page_pool::epp_free_pages, ptlrpc_enc_page_pool::epp_growing, ptlrpc_enc_page_pool::epp_idle_idx, ptlrpc_enc_page_pool::epp_last_access, ptlrpc_enc_page_pool::epp_lock, ptlrpc_enc_page_pool::epp_max_pages, ptlrpc_enc_page_pool::epp_pages_short, ptlrpc_enc_page_pool::epp_pools, ptlrpc_enc_page_pool::epp_st_access, ptlrpc_enc_page_pool::epp_st_lowfree, ptlrpc_enc_page_pool::epp_st_max_wait, ptlrpc_enc_page_pool::epp_st_max_wqlen, ptlrpc_enc_page_pool::epp_st_missings, ptlrpc_enc_page_pool::epp_st_outofmem, ptlrpc_enc_page_pool::epp_total_pages, ptlrpc_enc_page_pool::epp_waitq, ptlrpc_enc_page_pool::epp_waitqlen, GET_ENC_KIOV, IDLE_IDX_MAX, IDLE_IDX_WEIGHT, LASSERT, now(), OBD_ALLOC_LARGE, OBD_FREE_LARGE, page_pools, PAGES_PER_POOL, ptlrpc_is_bulk_desc_kiov(), and unlikely.
Referenced by gss_cli_ctx_wrap_bulk(), gss_prep_bulk(), and gss_svc_wrap_bulk().
void sptlrpc_enc_pool_put_pages (struct ptlrpc_bulk_desc * desc)
Definition at line 678 of file sec_bulk.c.
References BD_GET_ENC_KIOV, ptlrpc_bulk_desc::bd_iov_count, ptlrpc_bulk_desc::bd_type, enc_pools_wakeup(), ptlrpc_enc_page_pool::epp_free_pages, ptlrpc_enc_page_pool::epp_lock, ptlrpc_enc_page_pool::epp_pools, ptlrpc_enc_page_pool::epp_total_pages, GET_ENC_KIOV, LASSERT, OBD_FREE_LARGE, page_pools, PAGES_PER_POOL, and ptlrpc_is_bulk_desc_kiov().
Referenced by ptlrpc_free_bulk().
char* sptlrpc_flavor2name (struct sptlrpc_flavor * sf, char * buf, int bufsize)
Definition at line 226 of file sec.c.
References sptlrpc_flavor::sf_rpc, sptlrpc_flavor2name_base(), sptlrpc_flavor2name_bulk(), SPTLRPC_FLVR_POLICY, and SPTLRPC_POLICY_PLAIN.
Referenced by mgc_set_info_async(), rule2string(), sptlrpc_import_sec_adapt(), and sptlrpc_sec_create().
const char* sptlrpc_flavor2name_base (__u32 flvr)
Definition at line 183 of file sec.c.
References CERROR, SPTLRPC_FLVR_BASE, SPTLRPC_FLVR_GSSNULL, SPTLRPC_FLVR_KRB5A, SPTLRPC_FLVR_KRB5I, SPTLRPC_FLVR_KRB5N, SPTLRPC_FLVR_KRB5P, SPTLRPC_FLVR_NULL, SPTLRPC_FLVR_PLAIN, SPTLRPC_FLVR_SKI, and SPTLRPC_FLVR_SKPI.
Referenced by sptlrpc_flavor2name(), sptlrpc_flavor2name_bulk(), and sptlrpc_info_lprocfs_seq_show().
char* sptlrpc_flavor2name_bulk (struct sptlrpc_flavor * sf, char * buf, int bufsize)
Definition at line 211 of file sec.c.
References sptlrpc_flavor::hash, bulk_spec_hash::hash_alg, sptlrpc_flavor::sf_rpc, sptlrpc_flavor2name_base(), SPTLRPC_FLVR_POLICY, sptlrpc_get_hash_name(), SPTLRPC_POLICY_PLAIN, and sptlrpc_flavor::u_bulk.
Referenced by sptlrpc_flavor2name(), and sptlrpc_info_lprocfs_seq_show().
int sptlrpc_flavor_has_bulk (struct sptlrpc_flavor * flvr)
Definition at line 2524 of file sec.c.
References sptlrpc_flavor::sf_rpc, SPTLRPC_BULK_SVC_INTG, SPTLRPC_BULK_SVC_PRIV, and SPTLRPC_FLVR_BULK_SVC.
Referenced by osc_brw_prep_request(), and sptlrpc_req_set_flavor().
void sptlrpc_gc_add_ctx (struct ptlrpc_cli_ctx * ctx)
Definition at line 105 of file sec_gc.c.
References ptlrpc_cli_ctx::cc_gc_chain, ptlrpc_cli_ctx::cc_sec, ptlrpc_cli_ctx::cc_vcred, CDEBUG, D_SEC, LASSERT, list_add(), list_empty(), sec2target_str(), sec_gc_ctx_list, sec_gc_ctx_list_lock, sec_gc_thread, SVC_SIGNAL, ptlrpc_thread::t_ctl_waitq, thread_add_flags(), and vfs_cred::vc_uid.
Referenced by ctx_release_kr().
void sptlrpc_gc_add_sec (struct ptlrpc_sec * sec)
Definition at line 67 of file sec_gc.c.
References CDEBUG, cfs_time_current_sec(), D_SEC, ptlrpc_sec_cops::gc_ctx, LASSERT, list_add_tail(), list_empty(), ptlrpc_sec::ps_gc_interval, ptlrpc_sec::ps_gc_list, ptlrpc_sec::ps_gc_next, ptlrpc_sec::ps_policy, sec_gc_list, sec_gc_list_lock, ptlrpc_sec_policy::sp_cops, and ptlrpc_sec_policy::sp_name.
Referenced by sptlrpc_sec_create().
void sptlrpc_gc_del_sec (struct ptlrpc_sec * sec)
Definition at line 82 of file sec_gc.c.
References CDEBUG, D_SEC, list_del_init(), list_empty(), ptlrpc_sec::ps_gc_list, ptlrpc_sec::ps_policy, sec_gc_list_lock, sec_gc_mutex, sec_gc_wait_del, and ptlrpc_sec_policy::sp_name.
Referenced by sptlrpc_sec_put().
int sptlrpc_get_bulk_checksum (struct ptlrpc_bulk_desc * desc, __u8 alg, void * buf, int buflen)
Definition at line 923 of file sec_bulk.c.
References BD_GET_KIOV, ptlrpc_bulk_desc::bd_iov_count, ptlrpc_bulk_desc::bd_type, bufsize, BULK_HASH_ALG_MAX, BULK_HASH_ALG_NULL, CERROR, cfs_crypto_hash_digestsize(), CFS_CRYPTO_HASH_DIGESTSIZE_MAX, cfs_crypto_hash_final(), cfs_crypto_hash_init(), cfs_crypto_hash_name(), cfs_crypto_hash_update_page(), LASSERT, LASSERTF, and ptlrpc_is_bulk_desc_kiov().
Referenced by plain_generate_bulk_csum(), and plain_verify_bulk_csum().
__u8 sptlrpc_get_hash_alg (const char * algname)
Definition at line 874 of file sec_bulk.c.
Referenced by sptlrpc_parse_flavor().
const char* sptlrpc_get_hash_name (__u8 hash_alg)
Definition at line 869 of file sec_bulk.c.
References cfs_crypto_hash_name().
Referenced by sptlrpc_flavor2name_bulk().
int sptlrpc_get_next_secid (void)
Definition at line 1241 of file sec.c.
References sptlrpc_sec_id.
Referenced by gss_sec_create_common(), and plain_create_sec().
int sptlrpc_import_check_ctx (struct obd_import * imp)
Given an import imp, check whether current user has a valid context or not.
We may create a new context and try to refresh it, and try repeatedly try in case of non-fatal errors. Return 0 means success.
Definition at line 926 of file sec.c.
References ptlrpc_cli_ctx::cc_ops, cli_ctx_is_error(), cli_ctx_is_eternal(), ENTRY, get_my_ctx(), LASSERT, list_empty(), ptlrpc_sec::ps_flvr, ptlrpc_cli_req_init(), ptlrpc_request_cache_alloc(), ptlrpc_request_cache_free(), RETURN, ptlrpc_request::rq_flvr, ptlrpc_request::rq_import, ptlrpc_request::rq_refcount, sptlrpc_cli_ctx_put(), sptlrpc_import_sec_ref(), sptlrpc_req_refresh_ctx(), sptlrpc_sec_put(), and ptlrpc_ctx_ops::validate.
Referenced by ldlm_lock_match().
void sptlrpc_import_flush_all_ctx (struct obd_import * imp)
Definition at line 1570 of file sec.c.
References import_flush_ctx_common().
Referenced by ptlrpc_invalidate_import().
void sptlrpc_import_flush_my_ctx (struct obd_import * imp)
Definition at line 1563 of file sec.c.
References from_kuid(), and import_flush_ctx_common().
Referenced by mdc_set_info_async(), and osc_set_info_async().
void sptlrpc_import_flush_root_ctx (struct obd_import * imp)
Definition at line 1556 of file sec.c.
References import_flush_ctx_common().
int sptlrpc_import_sec_adapt (struct obd_import * imp, struct ptlrpc_svc_ctx * svc_ctx, struct sptlrpc_flavor * flvr)
To get an appropriate ptlrpc_sec for the imp, according to the current configuration.
Upon called, imp->imp_sec may or may not be NULL.
regular import: svc_ctx should be NULL and flvr is ignored;
reverse import: svc_ctx and flvr are obtained from incoming request.
Definition at line 1438 of file sec.c.
References ptlrpc_connection::c_remote_uuid, ptlrpc_connection::c_self, CDEBUG, CERROR, client_obd::cl_flvr_mgc, client_obd::cl_sp_me, client_obd::cl_sp_to, client_obd::cl_target_uuid, obd_device::cli, D_SEC, ENTRY, flavor_equal(), GOTO, obd_import::imp_connection, obd_import::imp_obd, obd_import::imp_sec_mutex, LNET_NIDNET(), LUSTRE_SP_MGC, obd_device::obd_name, obd_uuid2str(), ptlrpc_sec::ps_flvr, PTLRPC_SEC_FL_REVERSE, PTLRPC_SEC_FL_ROOTONLY, RETURN, sptlrpc_flavor::sf_flags, sptlrpc_flavor::sf_rpc, sptlrpc_conf_choose_flavor(), sptlrpc_flavor2name(), SPTLRPC_FLVR_BASE, SPTLRPC_FLVR_MECH, SPTLRPC_FLVR_NULL, SPTLRPC_FLVR_POLICY, sptlrpc_import_sec_adapt_inplace(), sptlrpc_import_sec_install(), sptlrpc_import_sec_ref(), sptlrpc_sec_create(), sptlrpc_sec_put(), sptlrpc_target_sec_part(), and obd_device::u.
Referenced by import_sec_check_expire(), ptlrpc_connect_import(), and sptlrpc_target_export_check().
void sptlrpc_import_sec_put (struct obd_import * imp)
Definition at line 1530 of file sec.c.
References obd_import::imp_sec, sptlrpc_sec_kill(), and sptlrpc_sec_put().
Referenced by client_destroy_import().
struct ptlrpc_sec* sptlrpc_import_sec_ref (struct obd_import * imp) [read]
Definition at line 1369 of file sec.c.
References obd_import::imp_lock, obd_import::imp_sec, and sptlrpc_sec_get().
Referenced by gss_svc_install_rctx_kr(), gss_svc_install_rctx_pf(), import_flush_ctx_common(), import_sec_validate_get(), sptlrpc_ctxs_lprocfs_seq_show(), sptlrpc_import_check_ctx(), sptlrpc_import_sec_adapt(), and sptlrpc_info_lprocfs_seq_show().
int sptlrpc_lprocfs_cliobd_attach (struct obd_device * dev)
Definition at line 145 of file sec_lproc.c.
References CERROR, LUSTRE_LWP_NAME, LUSTRE_MDC_NAME, LUSTRE_MGC_NAME, LUSTRE_OSC_NAME, LUSTRE_OSP_NAME, obd_device::obd_name, obd_device::obd_type, and obd_type::typ_name.
Referenced by lwp_init0(), mdc_setup(), mgc_setup(), and osc_setup().
__u32 sptlrpc_name2flavor_base (const char * name)
Definition at line 158 of file sec.c.
References SPTLRPC_FLVR_GSSNULL, SPTLRPC_FLVR_INVALID, SPTLRPC_FLVR_KRB5A, SPTLRPC_FLVR_KRB5I, SPTLRPC_FLVR_KRB5N, SPTLRPC_FLVR_KRB5P, SPTLRPC_FLVR_NULL, SPTLRPC_FLVR_PLAIN, SPTLRPC_FLVR_SKI, and SPTLRPC_FLVR_SKPI.
Referenced by sptlrpc_parse_flavor().
int sptlrpc_pack_user_desc (struct lustre_msg * msg, int offset)
Definition at line 2444 of file sec.c.
References cfs_curproc_cap_pack(), current_ngroups, from_kgid(), from_kuid(), lustre_msg_buf(), ptlrpc_user_desc::pud_cap, ptlrpc_user_desc::pud_fsgid, ptlrpc_user_desc::pud_fsuid, ptlrpc_user_desc::pud_gid, ptlrpc_user_desc::pud_groups, ptlrpc_user_desc::pud_ngroups, and ptlrpc_user_desc::pud_uid.
Referenced by gss_alloc_reqbuf_intg(), gss_alloc_reqbuf_priv(), and plain_alloc_reqbuf().
int sptlrpc_parse_flavor (const char * str, struct sptlrpc_flavor * flvr)
Definition at line 99 of file sec_config.c.
References alg, buf, BULK_HASH_ALG_ADLER32, BULK_HASH_ALG_MAX, BULK_HASH_ALG_NULL, CERROR, flvr_set_bulk_svc(), sptlrpc_flavor::hash, bulk_spec_hash::hash_alg, sptlrpc_flavor::sf_flags, sptlrpc_flavor::sf_rpc, SPTLRPC_BULK_SVC_INTG, SPTLRPC_BULK_SVC_NULL, SPTLRPC_FLVR_INVALID, SPTLRPC_FLVR_PLAIN, sptlrpc_get_hash_alg(), sptlrpc_name2flavor_base(), strlcpy(), and sptlrpc_flavor::u_bulk.
Referenced by mgc_set_info_async(), and sptlrpc_parse_rule().
int sptlrpc_parse_rule (char * param, struct sptlrpc_rule * rule)
Definition at line 186 of file sec_config.c.
References CERROR, dir, libcfs_str2net(), LNET_NID_ANY, LNET_NIDNET(), LUSTRE_SP_CLI, LUSTRE_SP_MDT, LUSTRE_SP_OST, RETURN, sptlrpc_parse_flavor(), sptlrpc_rule_init(), sptlrpc_rule::sr_flvr, sptlrpc_rule::sr_from, sptlrpc_rule::sr_netid, and sptlrpc_rule::sr_to.
Referenced by __sptlrpc_process_config(), and mgs_srpc_set_param_mem().
const char* sptlrpc_part2name (enum lustre_sec_part sp)
Definition at line 56 of file sec_config.c.
References LUSTRE_SP_ANY, LUSTRE_SP_CLI, LUSTRE_SP_MDT, LUSTRE_SP_MGC, LUSTRE_SP_MGS, and LUSTRE_SP_OST.
Referenced by rule2string(), sptlrpc_target_update_exp_flavor(), and tgt_connect_check_sptlrpc().
static struct ptlrpc_sec_policy* sptlrpc_policy_get (struct ptlrpc_sec_policy * policy) [static, read]
Definition at line 973 of file lustre_sec.h.
References ptlrpc_sec_policy::sp_owner.
Referenced by gss_svc_accept(), and sptlrpc_sec_create().
static void sptlrpc_policy_put (struct ptlrpc_sec_policy * policy) [inline, static]
Definition at line 980 of file lustre_sec.h.
References ptlrpc_sec_policy::sp_owner.
Referenced by gss_svc_reqctx_free(), null_create_sec(), sec_cop_destroy_sec(), sptlrpc_sec_create(), and sptlrpc_svc_unwrap_request().
int sptlrpc_process_config (struct lustre_cfg * lcfg)
Definition at line 713 of file sec_config.c.
References __sptlrpc_process_config().
Referenced by mgc_process_config().
int sptlrpc_register_policy (struct ptlrpc_sec_policy * policy)
Definition at line 70 of file sec.c.
References CDEBUG, D_SEC, LASSERT, policy_lock, ptlrpc_sec_policy::sp_cops, ptlrpc_sec_policy::sp_name, ptlrpc_sec_policy::sp_policy, ptlrpc_sec_policy::sp_sops, SPTLRPC_POLICY_MAX, and unlikely.
Referenced by gss_init_keyring(), gss_init_pipefs(), sptlrpc_null_init(), and sptlrpc_plain_init().
int sptlrpc_req_get_ctx (struct ptlrpc_request * req)
Given a req, find or allocate an appropriate context for it.
Precondition:
req->rq_cli_ctx == NULL.
Return values:
0 succeed, and req->rq_cli_ctx is set.
-ev error number, and req->rq_cli_ctx == NULL.
Definition at line 425 of file sec.c.
References CERROR, ENTRY, get_my_ctx(), import_sec_validate_get(), LASSERT, RETURN, ptlrpc_request::rq_import, and sptlrpc_sec_put().
Referenced by ptlrpc_request_bufs_pack(), and sptlrpc_req_replace_dead_ctx().
void sptlrpc_req_put_ctx (struct ptlrpc_request * req, int sync)
Drop the context for req.
Precondition:
req->rq_cli_ctx != NULL.
Postcondition:
req->rq_cli_ctx == NULL.
If sync == 0, this function should return quickly without sleep; otherwise it might trigger and wait for the whole process of sending an context-destroying rpc to server.
Definition at line 460 of file sec.c.
References ENTRY, EXIT, LASSERT, list_del_init(), list_empty(), and sptlrpc_cli_ctx_put().
Referenced by __ptlrpc_free_req(), and sptlrpc_req_replace_dead_ctx().
int sptlrpc_req_refresh_ctx (struct ptlrpc_request * req, long timeout)
To refresh the context of , if it's not up-to-date.
Parameters:
timeout
< 0: don't wait
= 0: wait until success or fatal error occur
> 0: timeout value (in seconds)
The status of the context could be subject to be changed by other threads at any time. We allow this race, but once we return with 0, the caller will suppose it's uptodated and keep using it until the owning rpc is done.
Return values:
0 only if the context is uptodated.
-ev error number.
Definition at line 675 of file sec.c.
References ptlrpc_cli_ctx::cc_flags, ptlrpc_cli_ctx::cc_lock, ptlrpc_cli_ctx::cc_ops, ptlrpc_cli_ctx::cc_req_list, CDEBUG, CERROR, cli_ctx_is_eternal(), cli_ctx_is_refreshed(), ctx_check_refresh(), ctx_refresh_interrupt(), ctx_refresh_timeout(), D_SEC, ENTRY, obd_import::imp_deactive, import_sec_validate_get(), l_wait_event, LASSERT, list_add(), list_empty(), lustre_msg_get_flags(), LWI_TIMEOUT_INTR, MSG_RESENT, ptlrpc_sec::ps_flvr, PTLRPC_CTX_DEAD_BIT, PTLRPC_CTX_ERROR_BIT, PTLRPC_CTX_NEW_BIT, PTLRPC_CTX_UPTODATE_BIT, ptlrpc_ctx_ops::refresh, req_off_ctx_list(), RETURN, ptlrpc_request::rq_ctx_fini, ptlrpc_request::rq_ctx_init, ptlrpc_request::rq_err, ptlrpc_request::rq_flvr, ptlrpc_request::rq_import, ptlrpc_request::rq_lock, ptlrpc_request::rq_receiving_reply, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_resend, ptlrpc_request::rq_restart, ptlrpc_request::rq_timedout, sptlrpc_flavor::sf_rpc, sptlrpc_req_replace_dead_ctx(), sptlrpc_sec_put(), unlikely, and ptlrpc_ctx_ops::validate.
Referenced by ptlrpc_check_set(), ptlrpc_send_new_req(), and sptlrpc_import_check_ctx().
int sptlrpc_req_replace_dead_ctx (struct ptlrpc_request * req)
If current context of req is dead somehow, e.g.
we just switched flavor thus marked original contexts dead, we'll find a new context for it. if no switch is needed, req will end up with the same context.
Note:
a request must have a context, to keep other parts of code happy. In any case of failure during the switching, we must restore the old one.
Definition at line 549 of file sec.c.
References ptlrpc_cli_ctx::cc_flags, CDEBUG, D_SEC, ENTRY, LASSERT, PTLRPC_CTX_DEAD_BIT, PTLRPC_CTX_UPTODATE_BIT, RETURN, sptlrpc_cli_ctx_get(), sptlrpc_cli_ctx_put(), sptlrpc_req_ctx_switch(), sptlrpc_req_get_ctx(), sptlrpc_req_put_ctx(), and unlikely.
Referenced by gss_cli_ctx_handle_err_notify(), and sptlrpc_req_refresh_ctx().
void sptlrpc_req_set_flavor (struct ptlrpc_request * req, int opcode)
Initialize flavor settings for req, according to opcode.
Note:
this could be called in two situations:
new request from ptlrpc_pre_req(), with proper
old request which changed ctx in the middle, with == 0
Definition at line 845 of file sec.c.
References flvr_set_svc(), LASSERT, MDS_READPAGE, MDS_WRITEPAGE, MGS_CONFIG_READ, OBD_IDX_READ, OST_READ, OST_WRITE, ptlrpc_sec::ps_flvr, ptlrpc_sec::ps_lock, PTLRPC_SEC_FL_UDESC, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_ctx_fini, ptlrpc_request::rq_ctx_init, ptlrpc_request::rq_flvr, ptlrpc_request::rq_import, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_pack_udesc, SEC_CTX_FINI, SEC_CTX_INIT, sptlrpc_flavor::sf_flags, sptlrpc_flavor::sf_rpc, sptlrpc_flavor_has_bulk(), SPTLRPC_FLVR_NULL, SPTLRPC_SVC_INTG, SPTLRPC_SVC_NULL, and unlikely.
Referenced by ptlrpc_request_bufs_pack(), and sptlrpc_req_ctx_switch().
void sptlrpc_request_out_callback (struct ptlrpc_request * req)
Definition at line 907 of file sec.c.
References LASSERT, OBD_FREE, ptlrpc_request::rq_clrbuf, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pool, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqbuf_len, sptlrpc_flavor::sf_rpc, SPTLRPC_FLVR_SVC, and SPTLRPC_SVC_PRIV.
Referenced by request_out_callback().
int sptlrpc_rule_set_choose (struct sptlrpc_rule_set * rset, enum lustre_sec_part from, enum lustre_sec_part to, lnet_nid_t nid, struct sptlrpc_flavor * sf)
given from/to/nid, determine a matching flavor in ruleset.
return 1 if a match found, otherwise return 0.
Definition at line 404 of file sec_config.c.
References LNET_NID_ANY, LNET_NIDNET(), LUSTRE_SP_ANY, sptlrpc_rule::sr_flvr, sptlrpc_rule::sr_from, sptlrpc_rule::sr_netid, sptlrpc_rule::sr_to, sptlrpc_rule_set::srs_nrule, and sptlrpc_rule_set::srs_rules.
Referenced by sptlrpc_conf_choose_flavor(), and sptlrpc_target_choose_flavor().
void sptlrpc_rule_set_dump (struct sptlrpc_rule_set * set)
Definition at line 436 of file sec_config.c.
References CDEBUG, D_SEC, sptlrpc_flavor::sf_rpc, sptlrpc_rule::sr_flvr, sptlrpc_rule::sr_from, sptlrpc_rule::sr_netid, sptlrpc_rule::sr_to, sptlrpc_rule_set::srs_nrule, and sptlrpc_rule_set::srs_rules.
int sptlrpc_rule_set_expand (struct sptlrpc_rule_set * set)
Definition at line 258 of file sec_config.c.
References LASSERT, OBD_ALLOC, OBD_FREE, sptlrpc_rule_set::srs_nrule, sptlrpc_rule_set::srs_nslot, and sptlrpc_rule_set::srs_rules.
Referenced by sptlrpc_rule_set_merge().
void sptlrpc_rule_set_free (struct sptlrpc_rule_set * set)
Definition at line 242 of file sec_config.c.
References LASSERT, OBD_FREE, sptlrpc_rule_set_init(), sptlrpc_rule_set::srs_nrule, sptlrpc_rule_set::srs_nslot, and sptlrpc_rule_set::srs_rules.
Referenced by mgs_free_fsdb_srpc(), sptlrpc_conf_free_rsets(), tgt_adapt_sptlrpc_conf(), and tgt_fini().
static void sptlrpc_rule_set_init (struct sptlrpc_rule_set * set) [inline, static]
Definition at line 354 of file lustre_sec.h.
Referenced by sptlrpc_conf_get(), sptlrpc_conf_get_tgt(), sptlrpc_rule_set_free(), tgt_adapt_sptlrpc_conf(), and tgt_init().
int sptlrpc_rule_set_merge (struct sptlrpc_rule_set * set, struct sptlrpc_rule * rule)
Definition at line 313 of file sec_config.c.
References CDEBUG, D_CONFIG, LASSERT, rule_match_dir(), rule_match_net(), rule_spec_dir(), rule_spec_net(), sptlrpc_flavor::sf_rpc, SPTLRPC_FLVR_INVALID, sptlrpc_rule_set_expand(), sptlrpc_rule::sr_flvr, sptlrpc_rule_set::srs_nrule, and sptlrpc_rule_set::srs_rules.
Referenced by mgs_srpc_set_param_mem(), sptlrpc_conf_merge_rule(), and sptlrpc_rule_set_extract().
void sptlrpc_sec_destroy (struct ptlrpc_sec * sec)
Definition at line 1276 of file sec.c.
References sec_cop_destroy_sec().
struct ptlrpc_sec* sptlrpc_sec_get (struct ptlrpc_sec * sec) [read]
Definition at line 1293 of file sec.c.
References ptlrpc_sec::ps_refcount.
Referenced by sptlrpc_import_sec_ref().
void sptlrpc_sec_put (struct ptlrpc_sec * sec)
Definition at line 1302 of file sec.c.
References LASSERT_ATOMIC_POS, ptlrpc_sec::ps_refcount, sec_cop_destroy_sec(), and sptlrpc_gc_del_sec().
Referenced by ctx_destroy_kr(), ctx_destroy_pf(), gss_svc_install_rctx_kr(), gss_svc_install_rctx_pf(), import_flush_ctx_common(), import_sec_validate_get(), plain_release_ctx(), sptlrpc_ctxs_lprocfs_seq_show(), sptlrpc_import_check_ctx(), sptlrpc_import_sec_adapt(), sptlrpc_import_sec_install(), sptlrpc_import_sec_put(), sptlrpc_info_lprocfs_seq_show(), sptlrpc_req_get_ctx(), and sptlrpc_req_refresh_ctx().
char* sptlrpc_secflags2str (__u32 flags, char * buf, int bufsize)
Definition at line 247 of file sec.c.
References PTLRPC_SEC_FL_BULK, PTLRPC_SEC_FL_REVERSE, PTLRPC_SEC_FL_ROOTONLY, PTLRPC_SEC_FL_UDESC, and strlcat().
Referenced by sptlrpc_import_sec_adapt_inplace().
int sptlrpc_svc_alloc_rs (struct ptlrpc_request * req, int msglen)
Used by ptlrpc server, to allocate reply buffer for req.
If succeed, req->rq_reply_state is set, and req->rq_reply_state->rs_msg point to a buffer of msglen size.
Definition at line 2130 of file sec.c.
References ptlrpc_sec_sops::alloc_rs, CERROR, ENTRY, LASSERT, lustre_get_emerg_rs(), lustre_put_emerg_rs(), RETURN, ptlrpc_sec_policy::sp_sops, and unlikely.
Referenced by lustre_pack_reply_v2().
void sptlrpc_svc_ctx_addref (struct ptlrpc_request * req)
Definition at line 2221 of file sec.c.
References ptlrpc_svc_ctx::sc_refcount.
Referenced by ptlrpc_at_send_early_reply().
void sptlrpc_svc_ctx_decref (struct ptlrpc_request * req)
Definition at line 2229 of file sec.c.
References ptlrpc_sec_sops::free_ctx, LASSERT_ATOMIC_POS, ptlrpc_svc_ctx::sc_policy, ptlrpc_svc_ctx::sc_refcount, and ptlrpc_sec_policy::sp_sops.
Referenced by ptlrpc_at_send_early_reply(), and ptlrpc_server_free_request().
void sptlrpc_svc_ctx_invalidate (struct ptlrpc_request * req)
Definition at line 2244 of file sec.c.
References ptlrpc_sec_sops::invalidate_ctx, LASSERT_ATOMIC_POS, ptlrpc_svc_ctx::sc_policy, ptlrpc_svc_ctx::sc_refcount, and ptlrpc_sec_policy::sp_sops.
Referenced by mdt_sec_ctx_handle().
void sptlrpc_svc_free_rs (struct ptlrpc_reply_state * rs)
Used by ptlrpc server, to free reply_state.
Definition at line 2201 of file sec.c.
References ENTRY, EXIT, ptlrpc_sec_sops::free_rs, LASSERT, lustre_put_emerg_rs(), ptlrpc_reply_state::rs_prealloc, ptlrpc_reply_state::rs_svc_ctx, ptlrpc_svc_ctx::sc_policy, and ptlrpc_sec_policy::sp_sops.
Referenced by lustre_free_reply_state().
int sptlrpc_svc_install_rvs_ctx (struct obd_import * imp, struct ptlrpc_svc_ctx * ctx)
Definition at line 1759 of file sec.c.
References ptlrpc_sec_sops::install_rctx, ptlrpc_svc_ctx::sc_policy, and ptlrpc_sec_policy::sp_sops.
Referenced by sptlrpc_target_export_check().
int sptlrpc_svc_unwrap_request (struct ptlrpc_request * req)
Used by ptlrpc server, to perform transformation upon request message of incoming req.
This must be the first thing to do with an incoming request in ptlrpc layer.
Return values:
SECSVC_OK success, and req->rq_reqmsg point to request message in clear text, size is req->rq_reqlen; also req->rq_svc_ctx is set.
SECSVC_COMPLETE success, the request has been fully processed, and reply message has been prepared.
SECSVC_DROP failed, this request should be dropped.
Definition at line 2070 of file sec.c.
References __lustre_unpack_msg(), ptlrpc_sec_sops::accept, CERROR, ENTRY, LASSERT, libcfs_id2str(), LPU64, lustre_msg, lustre_set_req_swabbed(), LUSTRE_SP_ANY, msg, MSG_PTLRPC_HEADER_OFF, RETURN, ptlrpc_request::rq_flvr, ptlrpc_request::rq_peer, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_req_swab_mask, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqdata_len, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_xid, SECSVC_DROP, SECSVC_OK, sptlrpc_flavor::sf_rpc, ptlrpc_sec_policy::sp_sops, SPTLRPC_FLVR_POLICY, SPTLRPC_POLICY_NULL, sptlrpc_policy_put(), sptlrpc_svc_check_from(), sptlrpc_wireflavor2policy(), and WIRE_FLVR.
Referenced by ptlrpc_server_handle_req_in().
int sptlrpc_svc_wrap_reply (struct ptlrpc_request * req)
Used by ptlrpc server, to perform transformation upon reply message.
Postcondition:
req->rq_reply_off is set to approriate server-controlled reply offset.
req->rq_repmsg and req->rq_reply_state->rs_msg becomes inaccessible.
Definition at line 2180 of file sec.c.
References ptlrpc_sec_sops::authorize, ENTRY, LASSERT, RETURN, and ptlrpc_sec_policy::sp_sops.
Referenced by ptlrpc_send_reply().
void sptlrpc_target_choose_flavor (struct sptlrpc_rule_set * rset, enum lustre_sec_part from, lnet_nid_t nid, struct sptlrpc_flavor * flavor)
called by target devices, determine the expected flavor from certain peer (from, nid).
Definition at line 890 of file sec_config.c.
References get_default_flavor(), LUSTRE_SP_ANY, and sptlrpc_rule_set_choose().
Referenced by sptlrpc_target_update_exp_flavor(), and tgt_connect_check_sptlrpc().
int sptlrpc_target_export_check (struct obd_export * exp, struct ptlrpc_request * req)
Given an export exp, check whether the flavor of incoming req is allowed by the export exp.
Main logic is about taking care of changing configurations. Return 0 means success.
Definition at line 1797 of file sec.c.
References CDEBUG, CFS_DURATION_T, cfs_time_current_sec(), CWARN, D_SEC, obd_export::exp_flvr, obd_export::exp_flvr_adapt, obd_export::exp_flvr_changed, obd_export::exp_flvr_expire, obd_export::exp_flvr_old, EXP_FLVR_UPDATE_EXPIRE, obd_export::exp_imp_reverse, obd_export::exp_lock, obd_export::exp_obd, flavor_allowed(), LASSERT, likely, obd_device::obd_name, ptlrpc_request::rq_auth_gss, ptlrpc_request::rq_auth_usr_mdt, ptlrpc_request::rq_auth_usr_ost, ptlrpc_request::rq_auth_usr_root, ptlrpc_request::rq_ctx_fini, ptlrpc_request::rq_ctx_init, ptlrpc_request::rq_flvr, sptlrpc_flavor::sf_rpc, sptlrpc_import_sec_adapt(), sptlrpc_svc_install_rvs_ctx(), and unlikely.
Referenced by ptlrpc_server_handle_req_in(), and tgt_connect_check_sptlrpc().
enum lustre_sec_part sptlrpc_target_sec_part (struct obd_device * obd)
Definition at line 77 of file sec_config.c.
References CERROR, LUSTRE_MDT_NAME, LUSTRE_MGS_NAME, LUSTRE_OST_NAME, LUSTRE_SP_ANY, LUSTRE_SP_MDT, LUSTRE_SP_MGS, LUSTRE_SP_OST, obd_device::obd_type, and obd_type::typ_name.
Referenced by sptlrpc_import_sec_adapt().
void sptlrpc_target_update_exp_flavor (struct obd_device * obd, struct sptlrpc_rule_set * rset)
Definition at line 1977 of file sec.c.
References ptlrpc_connection::c_peer, CDEBUG, D_SEC, obd_export::exp_connection, obd_export::exp_flvr, obd_export::exp_flvr_adapt, obd_export::exp_flvr_changed, obd_export::exp_flvr_expire, obd_export::exp_flvr_old, obd_export::exp_lock, obd_export::exp_sp_peer, flavor_equal(), LASSERT, list_for_each_entry, lnet_process_id_t::nid, obd_device::obd_dev_lock, obd_device::obd_exports, sptlrpc_flavor::sf_rpc, sptlrpc_part2name(), and sptlrpc_target_choose_flavor().
Referenced by mgs_srpc_set_param(), and tgt_adapt_sptlrpc_conf().
int sptlrpc_unpack_user_desc (struct lustre_msg * req, int offset, int swabbed)
Definition at line 2468 of file sec.c.
References __swab32s, CERROR, LUSTRE_MAX_GROUPS, lustre_msg_buf(), ptlrpc_user_desc::pud_cap, ptlrpc_user_desc::pud_fsgid, ptlrpc_user_desc::pud_fsuid, ptlrpc_user_desc::pud_gid, ptlrpc_user_desc::pud_groups, ptlrpc_user_desc::pud_ngroups, and ptlrpc_user_desc::pud_uid.
Referenced by gss_svc_handle_destroy(), gss_svc_handle_init(), gss_svc_unseal_request(), gss_svc_verify_request(), and plain_accept().
int sptlrpc_unregister_policy (struct ptlrpc_sec_policy * policy)
Definition at line 94 of file sec.c.
References CDEBUG, CERROR, D_SEC, LASSERT, policy_lock, ptlrpc_sec_policy::sp_name, ptlrpc_sec_policy::sp_policy, SPTLRPC_POLICY_MAX, and unlikely.
Referenced by gss_exit_keyring(), gss_exit_pipefs(), sptlrpc_null_fini(), and sptlrpc_plain_fini().
static int sptlrpc_user_desc_size (int ngroups) [inline, static]
Definition at line 1159 of file lustre_sec.h.
Referenced by sptlrpc_current_user_desc_size().
Variable Documentation
struct proc_dir_entry* sptlrpc_proc_root
Definition at line 57 of file sec_lproc.c.
Referenced by gss_init_lproc(), sptlrpc_lproc_fini(), and sptlrpc_lproc_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.