Lustre: cl_page
cl_page
[clio]
Data Structures
struct cl_page
Fields are protected by the lock on struct page, except for atomics and immutables.
struct cl_page_slice
Per-layer part of cl_page.
struct cl_page_operations
Per-layer page operations.
struct cl_client_cache
Data structure managing a client's cached pages.
Defines
#define CL_PAGE_DEBUG(mask, env, page, format,...)
Helper macro, dumping detailed information about page into a log.
#define CL_PAGE_HEADER(mask, env, page, format,...)
Helper macro, dumping shorter information about page into a log.
#define cl_page_in_use(pg) __page_in_use(pg, 1)
Caller itself holds a refcount of cl_page.
#define cl_page_in_use_noref(pg) __page_in_use(pg, 0)
Caller doesn't hold a refcount.
Enumerations
enum cl_page_state {
CPS_CACHED, CPS_OWNED, CPS_PAGEOUT, CPS_PAGEIN,
CPS_FREEING, CPS_NR
}
States of cl_page.
enum cl_page_type { CPT_CACHEABLE = 1, CPT_TRANSIENT }
enum cl_req_type { CRT_READ, CRT_WRITE, CRT_NR }
Requested transfer type.
enum { CLP_GANG_OKAY = 0, CLP_GANG_RESCHED, CLP_GANG_AGAIN, CLP_GANG_ABORT }
Functions
static struct page * cl_page_vmpage (const struct cl_page *page)
static bool __page_in_use (const struct cl_page *page, int refc)
Check if a cl_page is in use.
struct cl_page * cl_page_find (const struct lu_env *env, struct cl_object *obj, pgoff_t idx, struct page *vmpage, enum cl_page_type type)
Returns a cl_page with index idx at the object o, and associated with the VM page vmpage.
struct cl_page * cl_page_alloc (const struct lu_env *env, struct cl_object *o, pgoff_t ind, struct page *vmpage, enum cl_page_type type)
void cl_page_get (struct cl_page *page)
Acquires an additional reference to a page.
void cl_page_put (const struct lu_env *env, struct cl_page *page)
Releases a reference to a page.
void cl_page_print (const struct lu_env *env, void *cookie, lu_printer_t printer, const struct cl_page *pg)
Prints human readable representation of pg to the f.
void cl_page_header_print (const struct lu_env *env, void *cookie, lu_printer_t printer, const struct cl_page *pg)
Prints human readable representation of pg to the f.
struct cl_page * cl_vmpage_page (struct page *vmpage, struct cl_object *obj)
Returns a cl_page associated with a VM page, and given cl_object.
struct cl_page * cl_page_top (struct cl_page *page)
struct cl_page_slice * cl_page_at (const struct cl_page *page, const struct lu_device_type *dtype)
struct cl_client_cache * cl_cache_init (unsigned long lru_page_max)
cl_cache functions
void cl_cache_incref (struct cl_client_cache *cache)
Increase cl_cache refcount.
void cl_cache_decref (struct cl_client_cache *cache)
Decrease cl_cache refcount and free the cache if refcount=0.
ownership
Functions dealing with the ownership of page by io.
int cl_page_own (const struct lu_env *env, struct cl_io *io, struct cl_page *page)
Own a page, might be blocked.
int cl_page_own_try (const struct lu_env *env, struct cl_io *io, struct cl_page *page)
Nonblock version of cl_page_own().
void cl_page_assume (const struct lu_env *env, struct cl_io *io, struct cl_page *page)
Assume page ownership.
void cl_page_unassume (const struct lu_env *env, struct cl_io *io, struct cl_page *pg)
Releases page ownership without unlocking the page.
void cl_page_disown (const struct lu_env *env, struct cl_io *io, struct cl_page *page)
Releases page ownership.
int cl_page_is_owned (const struct cl_page *pg, const struct cl_io *io)
returns true, iff page is owned by the given io.
transfer
Functions dealing with the preparation of a page for a transfer, and tracking transfer state.
int cl_page_prep (const struct lu_env *env, struct cl_io *io, struct cl_page *pg, enum cl_req_type crt)
Prepares page for immediate transfer.
void cl_page_completion (const struct lu_env *env, struct cl_page *pg, enum cl_req_type crt, int ioret)
Notify layers about transfer completion.
int cl_page_make_ready (const struct lu_env *env, struct cl_page *pg, enum cl_req_type crt)
Notify layers that transfer formation engine decided to yank this page from the cache and to make it a part of a transfer.
int cl_page_cache_add (const struct lu_env *env, struct cl_io *io, struct cl_page *pg, enum cl_req_type crt)
void cl_page_clip (const struct lu_env *env, struct cl_page *pg, int from, int to)
Tells transfer engine that only part of a page is to be transmitted.
int cl_page_cancel (const struct lu_env *env, struct cl_page *page)
Cancel a page which is still in a transfer.
int cl_page_flush (const struct lu_env *env, struct cl_io *io, struct cl_page *pg)
Called if a pge is being written back by kernel's intention.
helper routines
Functions to discard, delete and export a cl_page.
void cl_page_discard (const struct lu_env *env, struct cl_io *io, struct cl_page *pg)
Called when page is to be removed from the object, e.g., as a result of truncate.
void cl_page_delete (const struct lu_env *env, struct cl_page *pg)
Called when a decision is made to throw page out of memory.
int cl_page_is_vmlocked (const struct lu_env *env, const struct cl_page *pg)
Returns true, iff pg is VM locked in a suitable sense by the calling thread.
void cl_page_export (const struct lu_env *env, struct cl_page *pg, int uptodate)
Marks page up-to-date.
loff_t cl_offset (const struct cl_object *obj, pgoff_t idx)
Converts a byte offset within object obj into a page index.
pgoff_t cl_index (const struct cl_object *obj, loff_t offset)
Converts a page index into a byte offset within object obj.
size_t cl_page_size (const struct cl_object *obj)
void cl_lock_print (const struct lu_env *env, void *cookie, lu_printer_t printer, const struct cl_lock *lock)
Prints human readable representation of lock to the f.
void cl_lock_descr_print (const struct lu_env *env, void *cookie, lu_printer_t printer, const struct cl_lock_descr *descr)
Prints human readable representation of a lock description.
Define Documentation
#define CL_PAGE_DEBUG (mask, env, page, format, ...)
Value:
do {                                                                    \
        if (cfs_cdebug_show(mask, DEBUG_SUBSYSTEM)) {                   \
                LIBCFS_DEBUG_MSG_DATA_DECL(msgdata, mask, NULL);        \
                cl_page_print(env, &msgdata, lu_cdebug_printer, page);  \
                CDEBUG(mask, format , ## __VA_ARGS__);                  \
        }                                                               \
} while (0)
Helper macro, dumping detailed information about page into a log.
Definition at line 1005 of file cl_object.h.
Referenced by discard_cb(), ll_write_end(), osc_page_delete(), osc_req_attr_set(), trunc_check_cb(), and vvp_page_make_ready().
#define CL_PAGE_HEADER (mask, env, page, format, ...)
Value:
do {                                                                          \
        if (cfs_cdebug_show(mask, DEBUG_SUBSYSTEM)) {                         \
                LIBCFS_DEBUG_MSG_DATA_DECL(msgdata, mask, NULL);              \
                cl_page_header_print(env, &msgdata, lu_cdebug_printer, page); \
                CDEBUG(mask, format , ## __VA_ARGS__);                        \
        }                                                                     \
} while (0)
Helper macro, dumping shorter information about page into a log.
Definition at line 1017 of file cl_object.h.
Referenced by cl_page_clip(), cl_page_completion(), cl_page_flush(), cl_page_make_ready(), cl_page_prep(), cl_page_put(), cl_page_state_set0(), ll_write_begin(), vvp_page_completion_read(), vvp_page_completion_write(), and vvp_page_make_ready().
#define cl_page_in_use (pg) __page_in_use(pg, 1)
Caller itself holds a refcount of cl_page.
Definition at line 1046 of file cl_object.h.
Referenced by ll_releasepage().
#define cl_page_in_use_noref (pg) __page_in_use(pg, 0)
Caller doesn't hold a refcount.
Definition at line 1050 of file cl_object.h.
Referenced by cl_page_invariant(), and lru_page_busy().
Enumeration Type Documentation
anonymous enum
Enumerator:
CLP_GANG_OKAY
CLP_GANG_RESCHED
CLP_GANG_AGAIN
CLP_GANG_ABORT
Definition at line 2073 of file cl_object.h.
enum cl_page_state
States of cl_page.
cl_page.c assumes particular order here.
The page state machine is rather crude, as it doesn't recognize finer page states like "dirty" or "up to date". This is because such states are not always well defined for the whole stack (see, for example, the implementation of the read-ahead, that hides page up-to-dateness to track cache hits accurately). Such sub-states are maintained by the layers that are interested in them.
Enumerator:
CPS_CACHED
Page is in the cache, un-owned.
Page leaves cached state in the following cases:
[cl_page_state::CPS_OWNED] io comes across the page and owns it;
[cl_page_state::CPS_PAGEOUT] page is dirty, the req-formation engine decides that it wants to include this page into an RPC being constructed, and yanks it from the cache;
[cl_page_state::CPS_FREEING] VM callback is executed to evict the page form the memory;
Invariant:
cl_page::cp_owner == NULL && cl_page::cp_req == NULL
CPS_OWNED
Page is exclusively owned by some cl_io.
Page may end up in this state as a result of
io creating new page and immediately owning it;
[cl_page_state::CPS_CACHED] io finding existing cached page and owning it;
[cl_page_state::CPS_OWNED] io finding existing owned page and waiting for owner to release the page;
Page leaves owned state in the following cases:
[cl_page_state::CPS_CACHED] io decides to leave the page in the cache, doing nothing;
[cl_page_state::CPS_PAGEIN] io starts read transfer for this page;
[cl_page_state::CPS_PAGEOUT] io starts immediate write transfer for this page;
[cl_page_state::CPS_FREEING] io decides to destroy this page (e.g., as part of truncate or extent lock cancellation).
Invariant:
cl_page::cp_owner != NULL && cl_page::cp_req == NULL
CPS_PAGEOUT
Page is being written out, as a part of a transfer.
This state is entered when req-formation logic decided that it wants this page to be sent through the wire _now_. Specifically, it means that once this state is achieved, transfer completion handler (with either success or failure indication) is guaranteed to be executed against this page independently of any locks and any scheduling decisions made by the hosting environment (that effectively means that the page is never put into cl_page_state::CPS_PAGEOUT state "in advance". This property is mentioned, because it is important when reasoning about possible dead-locks in the system). The page can enter this state as a result of
[cl_page_state::CPS_OWNED] an io requesting an immediate write-out of this page, or
[cl_page_state::CPS_CACHED] req-forming engine deciding that it has enough dirty pages cached to issue a "good" transfer.
The page leaves cl_page_state::CPS_PAGEOUT state when the transfer is completed---it is moved into cl_page_state::CPS_CACHED state.
Underlying VM page is locked for the duration of transfer.
Invariant:
: cl_page::cp_owner == NULL && cl_page::cp_req != NULL
CPS_PAGEIN
Page is being read in, as a part of a transfer.
This is quite similar to the cl_page_state::CPS_PAGEOUT state, except that read-in is always "immediate"---there is no such thing a sudden construction of read request from cached, presumably not up to date, pages.
Underlying VM page is locked for the duration of transfer.
Invariant:
: cl_page::cp_owner == NULL && cl_page::cp_req != NULL
CPS_FREEING
Page is being destroyed.
This state is entered when client decides that page has to be deleted from its host object, as, e.g., a part of truncate.
Once this state is reached, there is no way to escape it.
Invariant:
: cl_page::cp_owner == NULL && cl_page::cp_req == NULL
CPS_NR
Definition at line 594 of file cl_object.h.
enum cl_page_type
Enumerator:
CPT_CACHEABLE
Host page, the page is from the host inode which the cl_page belongs to.
CPT_TRANSIENT
Transient page, the transient cl_page is used to bind a cl_page to vmpage which is not belonging to the same object of cl_page.
it is used in DirectIO, lockless IO and liblustre.
Definition at line 694 of file cl_object.h.
enum cl_req_type
Requested transfer type.
Enumerator:
CRT_READ
CRT_WRITE
CRT_NR
Definition at line 786 of file cl_object.h.
Function Documentation
static bool __page_in_use (const struct cl_page * page, int refc) [inline, static]
Check if a cl_page is in use.
Client cache holds a refcount, this refcount will be dropped when the page is taken out of cache, see vvp_page_delete().
Definition at line 1038 of file cl_object.h.
References cp_ref.
void cl_cache_decref (struct cl_client_cache * cache)
Decrease cl_cache refcount and free the cache if refcount=0.
Since llite, lov and osc all hold cl_cache refcount, the free will not cause race. (LU-6173)
Definition at line 1136 of file cl_page.c.
References cl_client_cache::ccc_users, and OBD_FREE.
Referenced by ll_free_sbi(), lov_cleanup(), and osc_cleanup().
void cl_cache_incref (struct cl_client_cache * cache)
Increase cl_cache refcount.
Definition at line 1125 of file cl_page.c.
References cl_client_cache::ccc_users.
Referenced by lov_set_info_async(), and osc_set_info_async().
struct cl_client_cache* cl_cache_init (unsigned long lru_page_max) [read]
cl_cache functions
Definition at line 1097 of file cl_page.c.
References cl_client_cache::ccc_lru, cl_client_cache::ccc_lru_left, cl_client_cache::ccc_lru_lock, cl_client_cache::ccc_lru_max, cl_client_cache::ccc_unstable_check, cl_client_cache::ccc_unstable_nr, cl_client_cache::ccc_unstable_waitq, cl_client_cache::ccc_users, ENTRY, INIT_LIST_HEAD, OBD_ALLOC, and RETURN.
Referenced by ll_init_sbi().
pgoff_t cl_index (const struct cl_object * obj, loff_t offset)
Converts a page index into a byte offset within object obj.
Definition at line 1059 of file cl_page.c.
Referenced by check_and_discard_cb(), cl_echo_enqueue0(), cl_echo_object_brw(), ll_direct_rw_pages(), lov_io_read_ahead(), lov_io_sub_inherit(), lov_lock_sub_init(), lov_page_init_raid0(), osc_dlm_blocking_ast0(), osc_io_fsync_end(), osc_io_fsync_start(), osc_io_read_ahead(), osc_lock_granted(), osc_lock_set_writer(), osc_lock_weight(), osc_trunc_check(), vvp_io_fault_start(), vvp_io_one_lock(), vvp_io_read_start(), and vvp_mmap_locks().
void cl_lock_descr_print (const struct lu_env * env, void * cookie, lu_printer_t printer, const struct cl_lock_descr * descr)
Prints human readable representation of a lock description.
Definition at line 259 of file cl_lock.c.
References cl_lock_descr::cld_obj, cl_object::co_lu, DDESCR, DFID, lu_object_fid(), PDESCR, and PFID.
Referenced by cl_lock_print().
void cl_lock_print (const struct lu_env * env, void * cookie, lu_printer_t printer, const struct cl_lock * lock)
Prints human readable representation of lock to the f.
Definition at line 273 of file cl_lock.c.
References cl_lock_descr_print(), cl_lock::cll_descr, cl_lock::cll_layers, cl_lock_operations::clo_print, cl_lock_slice::cls_linkage, cl_lock_slice::cls_obj, cl_lock_slice::cls_ops, cl_object::co_lu, lu_device::ld_type, lu_device_type::ldt_name, list_for_each_entry, and lu_object::lo_dev.
Referenced by lov_lock_print().
loff_t cl_offset (const struct cl_object * obj, pgoff_t idx)
Converts a byte offset within object obj into a page index.
Definition at line 1050 of file cl_page.c.
Referenced by ll_prepare_partial_page(), ll_writepage(), lov_io_read_ahead(), lov_io_slice_init(), lov_io_sub_inherit(), lov_lock_sub_init(), lov_page_init_raid0(), osc_extent_sanity_check0(), osc_index2policy(), osc_page_init(), osc_page_touch_at(), osc_refresh_count(), osc_trunc_check(), and vvp_io_fault_start().
struct cl_page* cl_page_alloc (const struct lu_env * env, struct cl_object * o, pgoff_t ind, struct page * vmpage, enum cl_page_type type) [read]
Definition at line 172 of file cl_page.c.
References cl_object_get(), cl_object_header(), cl_page_delete0(), cl_page_free(), cl_page_state_set_trust(), cl_object::co_lu, cl_object::co_ops, cl_object_operations::coo_page_init, cp_batch, cp_layers, cp_obj, cp_obj_ref, cp_ref, cp_reference, cp_type, cp_vmpage, CPS_CACHED, CS_PAGE_INC, CS_PAGESTATE_DEC, ENTRY, head, INIT_LIST_HEAD, list_for_each_entry, lu_object::lo_header, lu_object_header::loh_layers, lu_object_ref_add_at(), lu_ref_init(), OBD_ALLOC_GFP, and RETURN.
Referenced by cl_page_find().
void cl_page_assume (const struct lu_env * env, struct cl_io * io, struct cl_page * pg)
Assume page ownership.
Called when page is already locked by the hosting VM.
Precondition:
!cl_page_is_owned(pg, io)
Postcondition:
cl_page_is_owned(pg, io)
See also:
cl_page_operations::cpo_assume()
Definition at line 652 of file cl_page.c.
References cl_io::ci_obj, cl_io_top(), cl_object_same(), cl_page_invoid(), CL_PAGE_OP, cl_page_owner_set(), cl_page_state_set(), cp_obj, cp_owner, CPS_OWNED, ENTRY, EXIT, PASSERT, and PINVRNT.
Referenced by cl_page_list_assume(), ll_read_ahead_page(), ll_readpage(), ll_write_begin(), ll_writepage(), and vvp_io_fault_start().
struct cl_page_slice* cl_page_at (const struct cl_page * page, const struct lu_device_type * dtype) [read]
Definition at line 420 of file cl_page.c.
References cl_page_at_trusted().
Referenced by lov_page_stripe(), and vvp_pgcache_page_show().
int cl_page_cache_add (const struct lu_env * env, struct cl_io * io, struct cl_page * pg, enum cl_req_type crt)
int cl_page_cancel (const struct lu_env * env, struct cl_page * page)
Cancel a page which is still in a transfer.
Definition at line 1040 of file cl_page.c.
References CL_PAGE_INVOKE, and CL_PAGE_OP.
Referenced by cl_io_cancel().
void cl_page_clip (const struct lu_env * env, struct cl_page * pg, int from, int to)
Tells transfer engine that only part of a page is to be transmitted.
See also:
cl_page_operations::cpo_clip()
Definition at line 995 of file cl_page.c.
References CL_PAGE_HEADER, cl_page_invariant(), CL_PAGE_INVOID, CL_PAGE_OP, D_TRACE, and PINVRNT.
Referenced by cl_echo_object_brw(), ll_direct_rw_pages(), osc_io_commit_async(), and vvp_io_commit_sync().
void cl_page_completion (const struct lu_env * env, struct cl_page * pg, enum cl_req_type crt, int ioret)
Notify layers about transfer completion.
Invoked by transfer sub-system (which is a part of osc) to notify layers that a transfer, of which this page is a part of has completed.
Completion call-backs are executed in the bottom-up order, so that uppermost layer (llite), responsible for the VFS/VM interaction runs last and can release locks safely.
Precondition:
pg->cp_state == CPS_PAGEIN || pg->cp_state == CPS_PAGEOUT
Postcondition:
pg->cp_state == CPS_CACHED
See also:
cl_page_operations::cpo_completion()
Definition at line 909 of file cl_page.c.
References CL_PAGE_HEADER, CL_PAGE_INVOID_REVERSE, CL_PAGE_OP, cl_page_state_set(), cl_req_type_state(), cl_sync_io_note(), cp_state, cp_sync_io, CPS_CACHED, CRT_NR, D_TRACE, ENTRY, EXIT, LASSERT, and PASSERT.
Referenced by osc_completion().
void cl_page_delete (const struct lu_env * env, struct cl_page * pg)
Called when a decision is made to throw page out of memory.
Notifies all layers about page destruction by calling cl_page_operations::cpo_delete() method top-to-bottom.
Moves page into cl_page_state::CPS_FREEING state (this is the only place where transition to this state happens).
Eliminates all venues through which new references to the page can be obtained:
removes page from the radix trees,
breaks linkage from VM page to cl_page.
Once page reaches cl_page_state::CPS_FREEING, all remaining references will drain after some time, at which point page will be recycled.
Precondition:
VM page is locked
Postcondition:
pg->cp_state == CPS_FREEING
See also:
cl_page_operations::cpo_delete()
Definition at line 790 of file cl_page.c.
References cl_page_delete0(), cl_page_invariant(), ENTRY, EXIT, and PINVRNT.
Referenced by discard_pagevec(), echo_page_discard(), ll_invalidatepage(), ll_releasepage(), and vvp_transient_page_discard().
void cl_page_discard (const struct lu_env * env, struct cl_io * io, struct cl_page * pg)
Called when page is to be removed from the object, e.g., as a result of truncate.
Calls cl_page_operations::cpo_discard() top-to-bottom.
Precondition:
cl_page_is_owned(pg, io)
See also:
cl_page_operations::cpo_discard()
Definition at line 732 of file cl_page.c.
References cl_page_invariant(), cl_page_invoid(), cl_page_is_owned(), CL_PAGE_OP, and PINVRNT.
Referenced by check_and_discard_cb(), cl_page_list_discard(), discard_cb(), discard_pagevec(), osc_extent_truncate(), vvp_io_fault_start(), and vvp_io_write_commit().
void cl_page_disown (const struct lu_env * env, struct cl_io * io, struct cl_page * pg)
Releases page ownership.
Moves page into cl_page_state::CPS_CACHED.
Precondition:
cl_page_is_owned(pg, io)
Postcondition:
!cl_page_is_owned(pg, io)
See also:
cl_page_own()
cl_page_operations::cpo_disown()
Definition at line 709 of file cl_page.c.
References cl_io_top(), cl_page_disown0(), cl_page_is_owned(), cp_state, CPS_FREEING, ENTRY, EXIT, and PINVRNT.
Referenced by check_and_discard_cb(), discard_cb(), discard_pagevec(), ll_direct_rw_pages(), ll_io_read_page(), ll_write_end(), ll_writepage(), osc_extent_truncate(), osc_lru_shrink(), vvp_io_commit_sync(), vvp_io_fault_start(), vvp_io_write_commit(), and write_commit_callback().
void cl_page_export (const struct lu_env * env, struct cl_page * pg, int uptodate)
Marks page up-to-date.
Call cl_page_operations::cpo_export() through all layers top-to-bottom. The layer responsible for VM interaction has to mark/clear page as up-to-date by the uptodate argument.
See also:
cl_page_operations::cpo_export()
Definition at line 808 of file cl_page.c.
References cl_page_invariant(), CL_PAGE_INVOID, CL_PAGE_OP, and PINVRNT.
Referenced by ll_io_read_page(), lov_page_init_empty(), and vvp_page_completion_read().
struct cl_page* cl_page_find (const struct lu_env * env, struct cl_object * o, pgoff_t idx, struct page * vmpage, enum cl_page_type type) [read]
Returns a cl_page with index idx at the object o, and associated with the VM page vmpage.
This is the main entry point into the cl_page caching interface. First, a cache (implemented as a per-object radix tree) is consulted. If page is found there, it is returned immediately. Otherwise new page is allocated and returned. In any case, additional reference to page is acquired.
See also:
cl_object_find(), cl_lock_find()
Definition at line 231 of file cl_page.c.
References CDEBUG, cl_object_header(), cl_page_alloc(), cl_vmpage_page(), cl_object_header::coh_lu, CPT_CACHEABLE, CPT_TRANSIENT, CS_PAGE_INC, D_PAGE, DFID, ENTRY, KLASSERT, LASSERT, lu_object_header::loh_fid, lookup(), PFID, and RETURN.
Referenced by cl_echo_object_brw(), ll_direct_rw_pages(), ll_read_ahead_page(), ll_readpage(), ll_write_begin(), ll_writepage(), and vvp_io_fault_start().
int cl_page_flush (const struct lu_env * env, struct cl_io * io, struct cl_page * pg)
Called if a pge is being written back by kernel's intention.
Precondition:
cl_page_is_owned(pg, io)
Postcondition:
ergo(result == 0, pg->cp_state == CPS_PAGEOUT)
See also:
cl_page_operations::cpo_flush()
Definition at line 973 of file cl_page.c.
References CL_PAGE_HEADER, cl_page_invariant(), cl_page_invoke(), cl_page_is_owned(), CL_PAGE_OP, D_TRACE, ENTRY, PINVRNT, and RETURN.
Referenced by ll_writepage().
void cl_page_get (struct cl_page * page)
Acquires an additional reference to a page.
This can be called only by caller already possessing a reference to page.
See also:
cl_object_get(), cl_lock_get().
Definition at line 355 of file cl_page.c.
References cl_page_get_trust(), ENTRY, and EXIT.
Referenced by cl_page_list_add(), osc_extent_truncate(), osc_lru_shrink(), and osc_page_transfer_get().
void cl_page_header_print (const struct lu_env * env, void * cookie, lu_printer_t printer, const struct cl_page * pg)
Prints human readable representation of pg to the f.
Definition at line 1011 of file cl_page.c.
References cp_obj.
Referenced by cl_page_print().
int cl_page_is_owned (const struct cl_page * pg, const struct cl_io * io)
returns true, iff page is owned by the given io.
Definition at line 555 of file cl_page.c.
References cl_io::ci_obj, cl_io_top(), cl_object_same(), cp_obj, cp_owner, cp_state, CPS_OWNED, ENTRY, LINVRNT, and RETURN.
Referenced by cl_page_discard(), cl_page_disown(), cl_page_flush(), cl_page_own0(), cl_page_prep(), cl_page_unassume(), discard_pagevec(), ll_page_sync_io(), ll_write_end(), and vvp_io_fault_start().
int cl_page_is_vmlocked (const struct lu_env * env, const struct cl_page * pg)
Returns true, iff pg is VM locked in a suitable sense by the calling thread.
Definition at line 821 of file cl_page.c.
References cp_layers, cl_page_slice::cpl_linkage, cl_page_slice::cpl_ops, cl_page_operations::cpo_is_vmlocked, ENTRY, list_head::next, PASSERT, and RETURN.
Referenced by cl_page_list_del(), and weigh_cb().
int cl_page_make_ready (const struct lu_env * env, struct cl_page * pg, enum cl_req_type crt)
Notify layers that transfer formation engine decided to yank this page from the cache and to make it a part of a transfer.
Precondition:
pg->cp_state == CPS_CACHED
Postcondition:
pg->cp_state == CPS_PAGEIN || pg->cp_state == CPS_PAGEOUT
See also:
cl_page_operations::cpo_make_ready()
Definition at line 943 of file cl_page.c.
References CL_PAGE_HEADER, CL_PAGE_INVOKE, cl_page_io_start(), CL_PAGE_OP, cp_state, CPS_CACHED, CRT_NR, D_TRACE, ENTRY, PASSERT, PINVRNT, and RETURN.
Referenced by osc_make_ready().
int cl_page_own (const struct lu_env * env, struct cl_io * io, struct cl_page * pg)
Own a page, might be blocked.
See also:
cl_page_own0()
Definition at line 623 of file cl_page.c.
References cl_page_own0().
Referenced by check_and_discard_cb(), cl_echo_object_brw(), cl_page_list_own(), discard_cb(), ll_direct_rw_pages(), and osc_extent_truncate().
int cl_page_own_try (const struct lu_env * env, struct cl_io * io, struct cl_page * pg)
Nonblock version of cl_page_own().
See also:
cl_page_own0()
Definition at line 634 of file cl_page.c.
References cl_page_own0().
Referenced by osc_lru_shrink().
int cl_page_prep (const struct lu_env * env, struct cl_io * io, struct cl_page * pg, enum cl_req_type crt)
Prepares page for immediate transfer.
cl_page_operations::cpo_prep() is called top-to-bottom. Every layer either agrees to submit this page (by returning 0), or requests to omit this page (by returning -EALREADY). Layer handling interactions with the VM also has to inform VM that page is under transfer now.
Definition at line 866 of file cl_page.c.
References CL_PAGE_HEADER, cl_page_invariant(), cl_page_invoke(), cl_page_io_start(), cl_page_is_owned(), CL_PAGE_OP, cl_page_vmpage(), cp_type, CPT_CACHEABLE, CRT_NR, CRT_WRITE, D_TRACE, equi, ergo, KLASSERT, and PINVRNT.
Referenced by osc_io_submit().
void cl_page_print (const struct lu_env * env, void * cookie, lu_printer_t printer, const struct cl_page * pg)
Prints human readable representation of pg to the f.
Definition at line 1025 of file cl_page.c.
References cl_page_header_print(), CL_PAGE_INVOKE, and CL_PAGE_OP.
void cl_page_put (const struct lu_env * env, struct cl_page * page)
Releases a reference to a page.
When last reference is released, page is returned to the cache, unless it is in cl_page_state::CPS_FREEING state, in which case it is immediately destroyed.
See also:
cl_object_put(), cl_lock_put().
Definition at line 372 of file cl_page.c.
References cl_page_free(), CL_PAGE_HEADER, cp_batch, cp_owner, cp_ref, cp_state, CPS_FREEING, D_TRACE, ENTRY, EXIT, LASSERT, list_empty(), and PASSERT.
Referenced by cl_echo_object_brw(), cl_page_list_del(), cl_page_list_disown(), discard_pagevec(), ll_direct_rw_pages(), ll_invalidatepage(), ll_read_ahead_page(), ll_readpage(), ll_releasepage(), ll_write_end(), ll_writepage(), osc_completion(), osc_extent_truncate(), osc_page_transfer_put(), vvp_io_commit_sync(), vvp_io_fault_fini(), vvp_io_fault_start(), vvp_io_write_commit(), vvp_pgcache_show(), and write_commit_callback().
size_t cl_page_size (const struct cl_object * obj)
Definition at line 1065 of file cl_page.c.
Referenced by cl_echo_object_brw(), ll_direct_rw_pages(), ll_prepare_partial_page(), lov_page_init_empty(), and vvp_io_fault_start().
struct cl_page* cl_page_top (struct cl_page * page) [read]
void cl_page_unassume (const struct lu_env * env, struct cl_io * io, struct cl_page * pg)
Releases page ownership without unlocking the page.
Moves page into cl_page_state::CPS_CACHED without releasing a lock on the underlying VM page (as VM is supposed to do this itself).
Precondition:
cl_page_is_owned(pg, io)
Postcondition:
!cl_page_is_owned(pg, io)
See also:
cl_page_assume()
Definition at line 680 of file cl_page.c.
References cl_io_top(), cl_page_invariant(), CL_PAGE_INVOID_REVERSE, cl_page_is_owned(), CL_PAGE_OP, cl_page_owner_clear(), cl_page_state_set(), CPS_CACHED, ENTRY, EXIT, and PINVRNT.
Referenced by ll_read_ahead_page(), and ll_write_begin().
static struct page* cl_page_vmpage (const struct cl_page * page) [static, read]
Definition at line 1026 of file cl_object.h.
References cp_vmpage, and LASSERT.
Referenced by cl_page_prep(), discard_cb(), ll_direct_rw_pages(), lru_page_busy(), vvp_io_commit_sync(), and vvp_io_write_commit().
struct cl_page* cl_vmpage_page (struct page * vmpage, struct cl_object * obj) [read]
Returns a cl_page associated with a VM page, and given cl_object.
Definition at line 398 of file cl_page.c.
References cl_page_get_trust(), cp_type, CPT_CACHEABLE, ENTRY, KLASSERT, LASSERT, and RETURN.
Referenced by cl_page_find(), ll_invalidatepage(), ll_releasepage(), and vvp_pgcache_show().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.