Lustre: lu_ref
lu_ref
An interface to track references between objects.
Data Structures
struct lu_ref
struct lu_ref_link
Functions
static void lu_ref_init (struct lu_ref *ref)
static void lu_ref_fini (struct lu_ref *ref)
static void lu_ref_add (struct lu_ref *ref, const char *scope, const void *source)
static void lu_ref_add_atomic (struct lu_ref *ref, const char *scope, const void *source)
static void lu_ref_add_at (struct lu_ref *ref, struct lu_ref_link *link, const char *scope, const void *source)
static void lu_ref_del (struct lu_ref *ref, const char *scope, const void *source)
static void lu_ref_set_at (struct lu_ref *ref, struct lu_ref_link *link, const char *scope, const void *source0, const void *source1)
static void lu_ref_del_at (struct lu_ref *ref, struct lu_ref_link *link, const char *scope, const void *source)
static int lu_ref_global_init (void)
static void lu_ref_global_fini (void)
static void lu_ref_print (const struct lu_ref *ref)
static void lu_ref_print_all (void)
Detailed Description
An interface to track references between objects.
Mostly for debugging.
Suppose there is a reference counted data-structure struct foo. To track who acquired references to instance of struct foo, add lu_ref field to it:
         struct foo {
                 atomic_t      foo_refcount;
                 struct lu_ref foo_reference;
                 ...
         };
foo::foo_reference has to be initialized by calling lu_ref_init(). Typically there will be functions or macros to increment and decrement foo::foo_refcount, let's say they are foo_get(struct foo *foo) and foo_put(struct foo *foo), respectively.
Whenever foo_get() is called to acquire a reference on a foo, lu_ref_add() has to be called to insert into foo::foo_reference a record, describing acquired reference. Dually, lu_ref_del() removes matching record. Typical usages are:
        struct bar *bar;
        // bar owns a reference to foo.
        bar->bar_foo = foo_get(foo);
        lu_ref_add(&foo->foo_reference, "bar", bar);
        ...
        // reference from bar to foo is released.
        lu_ref_del(&foo->foo_reference, "bar", bar);
        foo_put(bar->bar_foo);
        // current thread acquired a temporary reference to foo.
        foo_get(foo);
        lu_ref_add(&foo->reference, __FUNCTION__, current);
        ...
        // temporary reference is released.
        lu_ref_del(&foo->reference, __FUNCTION__, current);
        foo_put(foo);
Et cetera. Often it makes sense to include lu_ref_add() and lu_ref_del() calls into foo_get() and foo_put(). When an instance of struct foo is destroyed, lu_ref_fini() has to be called that checks that no pending references remain. lu_ref_print() can be used to dump a list of pending references, while hunting down a leak.
For objects to which a large number of references can be acquired, lu_ref_del() can become cpu consuming, as it has to scan the list of references. To work around this, remember result of lu_ref_add() (usually in the same place where pointer to struct foo is stored), and use lu_ref_del_at():
        // There is a large number of bar's for a single foo.
        bar->bar_foo     = foo_get(foo);
        bar->bar_foo_ref = lu_ref_add(&foo->foo_reference, "bar", bar);
        ...
        // reference from bar to foo is released.
        lu_ref_del_at(&foo->foo_reference, bar->bar_foo_ref, "bar", bar);
        foo_put(bar->bar_foo);
lu_ref interface degrades gracefully in case of memory shortages.
Function Documentation
static void lu_ref_add (struct lu_ref * ref, const char * scope, const void * source) [inline, static]
Definition at line 204 of file lu_ref.h.
Referenced by __ldlm_handle2lock(), cl_type_setup(), class_attach(), ldlm_lock_change_resource(), ldlm_lock_new(), ldlm_prepare_lru_list(), ll_read_ahead_page(), ll_write_begin(), ll_writepage(), lovsub_device_init(), lu_object_ref_add(), lu_site_init(), osc_extent_find(), osc_extent_put(), osc_extent_truncate(), osc_lock_granted(), qmt_pool_alloc(), qsd_glb_ast_data_get(), qsd_init(), qsd_intent_lock(), qsd_reint_main(), vvp_device_init(), and vvp_io_fault_start().
static void lu_ref_add_at (struct lu_ref * ref, struct lu_ref_link * link, const char * scope, const void * source) [inline, static]
Definition at line 216 of file lu_ref.h.
Referenced by cl_page_list_add(), lu_object_init(), lu_object_ref_add_at(), and osd_trans_start().
static void lu_ref_add_atomic (struct lu_ref * ref, const char * scope, const void * source) [inline, static]
Definition at line 210 of file lu_ref.h.
Referenced by __ldlm_handle2lock(), class_incref(), keys_fill(), ldlm_lock_addref_internal_nolock(), and osc_page_transfer_get().
static void lu_ref_del (struct lu_ref * ref, const char * scope, const void * source) [inline, static]
Definition at line 223 of file lu_ref.h.
Referenced by class_decref(), key_fini(), ldlm_lock_change_resource(), ldlm_lock_decref_internal_nolock(), ldlm_lock_destroy(), ldlm_lock_destroy_nolock(), ldlm_lock_put(), ldlm_prepare_lru_list(), ll_read_ahead_page(), ll_write_end(), ll_writepage(), lu_object_ref_del(), lu_site_fini(), lu_stack_fini(), mdt_intent_lock_replace(), osc_completion(), osc_extent_truncate(), osc_lock_detach(), osc_page_transfer_put(), qmt_pool_free(), qsd_fini(), qsd_glb_ast_data_get(), qsd_glb_blocking_ast(), qsd_glb_glimpse_ast(), qsd_reint_main(), vvp_io_commit_sync(), vvp_io_fault_fini(), vvp_io_write_commit(), and write_commit_callback().
static void lu_ref_del_at (struct lu_ref * ref, struct lu_ref_link * link, const char * scope, const void * source) [inline, static]
Definition at line 234 of file lu_ref.h.
Referenced by cl_page_list_del(), cl_page_list_disown(), lu_object_fini(), lu_object_ref_del_at(), and osd_trans_commit_cb().
static void lu_ref_fini (struct lu_ref * ref) [inline, static]
Definition at line 200 of file lu_ref.h.
Referenced by __ldlm_resource_putref_final(), cl_key_exit(), cl_key_fini(), cl_page_free(), ldlm_lock_put(), ldlm_resource_get(), lu_context_key_degister(), lu_device_fini(), lu_object_header_fini(), obd_device_free(), and qsd_qtype_fini().
static void lu_ref_global_fini (void) [inline, static]
Definition at line 244 of file lu_ref.h.
Referenced by lu_global_fini().
static int lu_ref_global_init (void) [inline, static]
Definition at line 239 of file lu_ref.h.
Referenced by lu_global_init().
static void lu_ref_init (struct lu_ref * ref) [inline, static]
Definition at line 196 of file lu_ref.h.
Referenced by cl_key_exit(), cl_key_init(), cl_page_alloc(), class_attach(), ldlm_lock_new(), ldlm_resource_new(), lu_context_key_register(), lu_device_init(), lu_object_header_init(), and qsd_qtype_init().
static void lu_ref_print (const struct lu_ref * ref) [inline, static]
Definition at line 248 of file lu_ref.h.
Referenced by lu_context_keys_dump().
static void lu_ref_print_all (void) [inline, static]
Definition at line 252 of file lu_ref.h.
static void lu_ref_set_at (struct lu_ref * ref, struct lu_ref_link * link, const char * scope, const void * source0, const void * source1) [inline, static]
Definition at line 228 of file lu_ref.h.
Referenced by cl_page_list_move(), and cl_page_list_move_head().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.