Lustre: lu_object operations
lu_object operations
[Echo Client]
operations for echo lu object.
Functions
static int echo_object_init (const struct lu_env *env, struct lu_object *obj, const struct lu_object_conf *conf)
static void echo_object_free (const struct lu_env *env, struct lu_object *obj)
static int echo_object_print (const struct lu_env *env, void *cookie, lu_printer_t p, const struct lu_object *o)
Variables
static struct lu_object_operations echo_lu_obj_ops
Detailed Description
operations for echo lu object.
Function Documentation
static void echo_object_free (const struct lu_env * env, struct lu_object * obj) [static]
Definition at line 508 of file echo_client.c.
References cl2echo_obj(), echo_client_obd::ec_lock, echo_object_kmem, echo_device::ed_ec, ENTRY, echo_object::eo_dev, echo_object::eo_npages, echo_object::eo_obj_chain, echo_object::eo_oinfo, EXIT, LASSERT, list_del_init(), lu_object::lo_header, lu2cl(), lu_object_fini(), lu_object_header_fini(), OBD_FREE_PTR, and OBD_SLAB_FREE_PTR.
static int echo_object_init (const struct lu_env * env, struct lu_object * obj, const struct lu_object_conf * conf) [static]
Definition at line 463 of file echo_client.c.
References cl2echo_conf(), cl2echo_dev(), cl2echo_obj(), cl_object_page_init(), echo_client_obd::ec_lock, echo_client_obd::ec_objects, echo_device::ed_ec, echo_device::ed_next, echo_device::ed_next_ismd, ENTRY, echo_object::eo_dev, echo_object::eo_npages, echo_object::eo_obj_chain, echo_object::eo_oinfo, echo_object_conf::eoc_oinfo, LASSERT, lu_device::ld_ops, lu_device_operations::ldo_object_alloc, list_add_tail(), lu_object::lo_dev, lu_object::lo_header, lu2cl(), lu2cl_conf(), lu2cl_dev(), lu_object_add(), and RETURN.
static int echo_object_print (const struct lu_env * env, void * cookie, lu_printer_t p, const struct lu_object * o) [static]
Definition at line 530 of file echo_client.c.
References cl2echo_obj(), and lu2cl().
Variable Documentation
struct lu_object_operations echo_lu_obj_ops [static]
Initial value:
 {
        .loo_object_init      = echo_object_init,
        .loo_object_delete    = NULL,
        .loo_object_release   = NULL,
        .loo_object_free      = echo_object_free,
        .loo_object_print     = echo_object_print,
        .loo_object_invariant = NULL
}
Definition at line 538 of file echo_client.c.
Referenced by echo_object_alloc().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.