Lustre: cl_sync_io
cl_sync_io
[clio]
Data Structures
struct cl_sync_io
Anchor for synchronous transfer.
Functions
void cl_sync_io_init (struct cl_sync_io *anchor, int nr, void(*end)(const struct lu_env *, struct cl_sync_io *))
Initialize synchronous io wait anchor.
int cl_sync_io_wait (const struct lu_env *env, struct cl_sync_io *anchor, long timeout)
Wait until all IO completes.
void cl_sync_io_note (const struct lu_env *env, struct cl_sync_io *anchor, int ioret)
Indicate that transfer of a single page completed.
void cl_sync_io_end (const struct lu_env *env, struct cl_sync_io *anchor)
Function Documentation
void cl_sync_io_end (const struct lu_env * env, struct cl_sync_io * anchor)
Definition at line 1190 of file cl_io.c.
References csi_barrier, and csi_waitq.
Referenced by cl_io_submit_sync(), cl_lock_request(), and osc_lock_enqueue_wait().
void cl_sync_io_init (struct cl_sync_io * anchor, int nr, void(*)(const struct lu_env *, struct cl_sync_io *) end)
Initialize synchronous io wait anchor.
Definition at line 1202 of file cl_io.c.
References csi_barrier, csi_end_io, csi_sync_nr, csi_sync_rc, csi_waitq, end, ENTRY, EXIT, and LASSERT.
Referenced by cl_io_submit_sync(), cl_lock_request(), and osc_lock_enqueue_wait().
void cl_sync_io_note (const struct lu_env * env, struct cl_sync_io * anchor, int ioret)
Indicate that transfer of a single page completed.
Definition at line 1258 of file cl_io.c.
References csi_end_io, csi_sync_nr, csi_sync_rc, ENTRY, EXIT, and LASSERT.
Referenced by cl_io_submit_sync(), cl_lock_request(), cl_page_completion(), osc_lock_enqueue(), osc_lock_upcall(), and osc_lock_wake_waiters().
int cl_sync_io_wait (const struct lu_env * env, struct cl_sync_io * anchor, long timeout)
Wait until all IO completes.
Transfer completion routine has to call cl_sync_io_note() for every entity.
Definition at line 1221 of file cl_io.c.
References CERROR, cfs_time_seconds(), csi_barrier, csi_sync_nr, csi_sync_rc, csi_waitq, ENTRY, l_wait_event, LASSERT, LWI_TIMEOUT_INTR, RETURN, and unlikely.
Referenced by cl_io_submit_sync(), cl_lock_request(), and osc_lock_enqueue_wait().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.