Lustre: mds
mds
Data Structures
struct mds_group_info
struct mds_capa_info
Defines
#define MDD_OBD_NAME "mdd_obd"
#define MDD_OBD_UUID "mdd_obd_uuid"
Functions
static int md_should_create (__u64 flags)
Define Documentation
#define MDD_OBD_NAME "mdd_obd"
Definition at line 67 of file lustre_mds.h.
Referenced by mdt_stack_init().
#define MDD_OBD_UUID "mdd_obd_uuid"
Definition at line 68 of file lustre_mds.h.
Function Documentation
static int md_should_create (__u64 flags) [inline, static]
Definition at line 70 of file lustre_mds.h.
References FMODE_WRITE, MDS_OPEN_DELAY_CREATE, and MDS_OPEN_LEASE.
Referenced by mdd_create_data(), mdd_declare_object_create_internal(), mdt_create_data(), mdt_object_open_lock(), and mdt_open_by_fid_lock().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.