Lustre: Page operations
Page operations
[Echo Client]
Echo page operations.
Functions
static int echo_page_own (const struct lu_env *env, const struct cl_page_slice *slice, struct cl_io *io, int nonblock)
static void echo_page_disown (const struct lu_env *env, const struct cl_page_slice *slice, struct cl_io *io)
static void echo_page_discard (const struct lu_env *env, const struct cl_page_slice *slice, struct cl_io *unused)
static int echo_page_is_vmlocked (const struct lu_env *env, const struct cl_page_slice *slice)
static void echo_page_completion (const struct lu_env *env, const struct cl_page_slice *slice, int ioret)
static void echo_page_fini (const struct lu_env *env, struct cl_page_slice *slice)
static int echo_page_prep (const struct lu_env *env, const struct cl_page_slice *slice, struct cl_io *unused)
static int echo_page_print (const struct lu_env *env, const struct cl_page_slice *slice, void *cookie, lu_printer_t printer)
Variables
static struct cl_page_operations echo_page_ops
Detailed Description
Echo page operations.
Function Documentation
static void echo_page_completion (const struct lu_env * env, const struct cl_page_slice * slice, int ioret) [static]
Definition at line 322 of file echo_client.c.
References cl_page::cp_sync_io, cl_page_slice::cpl_page, and LASSERT.
static void echo_page_discard (const struct lu_env * env, const struct cl_page_slice * slice, struct cl_io * unused) [static]
Definition at line 307 of file echo_client.c.
References cl_page_delete(), and cl_page_slice::cpl_page.
static void echo_page_disown (const struct lu_env * env, const struct cl_page_slice * slice, struct cl_io * io) [static]
Definition at line 297 of file echo_client.c.
References cl2echo_page(), ep_lock, and LASSERT.
static void echo_page_fini (const struct lu_env * env, struct cl_page_slice * slice) [static]
Definition at line 329 of file echo_client.c.
References cl2echo_obj(), cl_page::cp_vmpage, cl_page_slice::cpl_obj, cl_page_slice::cpl_page, ENTRY, echo_object::eo_npages, and EXIT.
static int echo_page_is_vmlocked (const struct lu_env * env, const struct cl_page_slice * slice) [static]
Definition at line 314 of file echo_client.c.
References cl2echo_page(), and ep_lock.
static int echo_page_own (const struct lu_env * env, const struct cl_page_slice * slice, struct cl_io * io, int nonblock) [static]
Definition at line 284 of file echo_client.c.
References cl2echo_page(), and ep_lock.
static int echo_page_prep (const struct lu_env * env, const struct cl_page_slice * slice, struct cl_io * unused) [static]
Definition at line 340 of file echo_client.c.
static int echo_page_print (const struct lu_env * env, const struct cl_page_slice * slice, void * cookie, lu_printer_t printer) [static]
Definition at line 347 of file echo_client.c.
References cl2echo_page(), cl_page::cp_vmpage, cl_page_slice::cpl_page, and LUSTRE_ECHO_CLIENT_NAME.
Variable Documentation
struct cl_page_operations echo_page_ops [static]
Initial value:
 {
        .cpo_own           = echo_page_own,
        .cpo_disown        = echo_page_disown,
        .cpo_discard       = echo_page_discard,
        .cpo_fini          = echo_page_fini,
        .cpo_print         = echo_page_print,
        .cpo_is_vmlocked   = echo_page_is_vmlocked,
        .io = {
                [CRT_READ] = {
                        .cpo_prep        = echo_page_prep,
                        .cpo_completion  = echo_page_completion,
                },
                [CRT_WRITE] = {
                        .cpo_prep        = echo_page_prep,
                        .cpo_completion  = echo_page_completion,
                }
        }
}
Definition at line 359 of file echo_client.c.
Referenced by echo_page_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.