Lustre: PortalRPC daemon
PortalRPC daemon
ptlrpcd is a special thread with its own set where other user might add requests when they don't want to wait for their completion.
Data Structures
struct ptlrpcd
Defines
#define DEBUG_SUBSYSTEM S_RPC
Functions
module_param (max_ptlrpcds, int, 0644)
MODULE_PARM_DESC (max_ptlrpcds,"Max ptlrpcd thread count to be started.")
module_param (ptlrpcd_bind_policy, int, 0644)
MODULE_PARM_DESC (ptlrpcd_bind_policy,"Ptlrpcd threads binding mode (obsolete).")
MODULE_PARM_DESC (ptlrpcd_per_cpt_max,"Max ptlrpcd thread count to be started per cpt.")
module_param (ptlrpcd_partner_group_size, int, 0644)
MODULE_PARM_DESC (ptlrpcd_partner_group_size,"Number of ptlrpcd threads in a partner group.")
module_param (ptlrpcd_cpts, charp, 0644)
MODULE_PARM_DESC (ptlrpcd_cpts,"CPU partitions ptlrpcd threads should run in")
void ptlrpcd_wake (struct ptlrpc_request *req)
static struct ptlrpcd_ctl * ptlrpcd_select_pc (struct ptlrpc_request *req)
void ptlrpcd_add_rqset (struct ptlrpc_request_set *set)
Move all request from an existing request set to the ptlrpcd queue.
static int ptlrpcd_steal_rqset (struct ptlrpc_request_set *des, struct ptlrpc_request_set *src)
Return transferred RPCs count.
void ptlrpcd_add_req (struct ptlrpc_request *req)
Requests that are added to the ptlrpcd queue are sent via ptlrpcd_check->ptlrpc_check_set().
static void ptlrpc_reqset_get (struct ptlrpc_request_set *set)
static int ptlrpcd_check (struct lu_env *env, struct ptlrpcd_ctl *pc)
Check if there is more work to do on ptlrpcd set.
static int ptlrpcd (void *arg)
Main ptlrpcd thread.
static void ptlrpcd_ctl_init (struct ptlrpcd_ctl *pc, int index, int cpt)
static int ptlrpcd_partners (struct ptlrpcd *pd, int index)
int ptlrpcd_start (struct ptlrpcd_ctl *pc)
void ptlrpcd_stop (struct ptlrpcd_ctl *pc, int force)
void ptlrpcd_free (struct ptlrpcd_ctl *pc)
static void ptlrpcd_fini (void)
static int ptlrpcd_init (void)
int ptlrpcd_addref (void)
void ptlrpcd_decref (void)
Variables
static int max_ptlrpcds
static int ptlrpcd_bind_policy
static int ptlrpcd_per_cpt_max
static int ptlrpcd_partner_group_size
static char * ptlrpcd_cpts
static int * ptlrpcds_cpt_idx
static int ptlrpcds_num
static struct ptlrpcd ** ptlrpcds
static struct ptlrpcd_ctl ptlrpcd_rcv
struct mutex ptlrpcd_mutex
static int ptlrpcd_users = 0
Detailed Description
ptlrpcd is a special thread with its own set where other user might add requests when they don't want to wait for their completion.
PtlRPCD will take care of sending such requests and then processing their replies and calling completion callbacks as necessary. The callbacks are called directly from ptlrpcd context. It is important to never significantly block (esp. on RPCs!) within such completion handler or a deadlock might occur where ptlrpcd enters some callback that attempts to send another RPC and wait for it to return, during which time ptlrpcd is completely blocked, so e.g. if import fails, recovery cannot progress because connection requests are also sent by ptlrpcd.
Define Documentation
#define DEBUG_SUBSYSTEM S_RPC
Definition at line 56 of file ptlrpcd.c.
Function Documentation
module_param (ptlrpcd_cpts , charp , 0644)
module_param (ptlrpcd_partner_group_size , int , 0644)
module_param (ptlrpcd_bind_policy , int , 0644)
module_param (max_ptlrpcds , int , 0644)
MODULE_PARM_DESC (ptlrpcd_cpts , "CPU partitions ptlrpcd threads should run in")
MODULE_PARM_DESC (ptlrpcd_partner_group_size , "Number of ptlrpcd threads in a partner group.")
MODULE_PARM_DESC (ptlrpcd_per_cpt_max , "Max ptlrpcd thread count to be started per cpt.")
MODULE_PARM_DESC (ptlrpcd_bind_policy , "Ptlrpcd threads binding mode (obsolete).")
MODULE_PARM_DESC (max_ptlrpcds , "Max ptlrpcd thread count to be started.")
static void ptlrpc_reqset_get (struct ptlrpc_request_set * set) [inline, static]
Definition at line 307 of file ptlrpcd.c.
Referenced by ptlrpcd_check().
static int ptlrpcd (void * arg) [static]
Main ptlrpcd thread.
ptlrpc's code paths like to execute in process context, so we have this thread which spins on a set which contains the rpcs and sends them.
Definition at line 427 of file ptlrpcd.c.
References cfs_cpt_bind(), cfs_time_seconds(), CWARN, ENTRY, GOTO, l_wait_event, LCT_CL_THREAD, LCT_DT_THREAD, LCT_MD_THREAD, LCT_NOREF, LCT_REMEMBER, LCT_SESSION, lu_env::le_ctx, lu_env::le_ses, LIOD_FORCE, LIOD_STOP, list_empty(), lu_context_enter(), lu_context_exit(), lu_context_fini(), lu_context_init(), LWI_TIMEOUT, ptlrpcd_ctl::pc_cpt, ptlrpcd_ctl::pc_error, ptlrpcd_ctl::pc_finishing, ptlrpcd_ctl::pc_flags, ptlrpcd_ctl::pc_lock, ptlrpcd_ctl::pc_name, ptlrpcd_ctl::pc_set, ptlrpcd_ctl::pc_starting, ptlrpc_abort_set(), ptlrpc_expired_set(), ptlrpc_prep_set(), ptlrpc_set_next_timeout(), ptlrpc_set_wait(), ptlrpcd_check(), RETURN, and timeout.
void ptlrpcd_add_req (struct ptlrpc_request * req)
Requests that are added to the ptlrpcd queue are sent via ptlrpcd_check->ptlrpc_check_set().
Definition at line 268 of file ptlrpcd.c.
References back_to_sleep(), cfs_time_seconds(), D_INFO, DEBUG_REQ, l_wait_event, LASSERT, LUSTRE_IMP_REPLAY, lustre_msg_set_jobid(), LWI_TIMEOUT, ptlrpcd_ctl::pc_index, ptlrpcd_ctl::pc_name, ptlrpc_set_add_new_req(), ptlrpcd_select_pc(), ptlrpc_request::rq_invalid_rqset, ptlrpc_request::rq_lock, ptlrpc_request::rq_phase, RQ_PHASE_NEW, and ptlrpc_request::rq_reqmsg.
Referenced by ldlm_cli_cancel_req(), mdc_intent_getattr_async(), osc_brw_redo_request(), osc_build_rpc(), osc_destroy(), osc_enqueue_base(), osc_io_data_version_start(), osc_ladvise_base(), osc_punch_base(), osc_set_info_async(), osc_setattr_async(), osc_sync_base(), osp_send_update_req(), osp_statfs_update(), osp_sync_send_new_rpc(), osp_unplug_async_request(), ptlrpc_connect_import(), ptlrpc_ping(), ptlrpc_replay_req(), ptlrpcd_add_work_req(), qsd_intent_lock(), qsd_send_dqacq(), replay_one_lock(), and signal_completed_replay().
void ptlrpcd_add_rqset (struct ptlrpc_request_set * set)
Move all request from an existing request set to the ptlrpcd queue.
All requests from the set must be in phase RQ_PHASE_NEW.
Definition at line 200 of file ptlrpcd.c.
References cfs_time_current(), LASSERT, list_entry, list_for_each_safe, list_splice_init(), ptlrpcd_ctl::pc_npartners, ptlrpcd_ctl::pc_partners, ptlrpcd_ctl::pc_set, ptlrpcd_select_pc(), ptlrpc_request::rq_phase, RQ_PHASE_NEW, rq_set_chain, and ptlrpc_request_set::set_waitq.
int ptlrpcd_addref (void)
Definition at line 955 of file ptlrpcd.c.
References ENTRY, ptlrpcd_init(), ptlrpcd_mutex, ptlrpcd_users, and RETURN.
Referenced by lwp_init0(), mdc_setup(), mgc_setup(), osc_setup(), osp_init0(), and ptlrpc_init_portals().
static int ptlrpcd_check (struct lu_env * env, struct ptlrpcd_ctl * pc) [static]
Check if there is more work to do on ptlrpcd set.
Returns 1 if yes.
Definition at line 316 of file ptlrpcd.c.
References CDEBUG, CERROR, D_RPCTRACE, ENTRY, likely, list_del_init(), list_empty(), list_entry, list_for_each_safe, list_splice_init(), lu_env_refill(), ptlrpcd_ctl::pc_cursor, ptlrpcd_ctl::pc_index, ptlrpcd_ctl::pc_lock, ptlrpcd_ctl::pc_npartners, ptlrpcd_ctl::pc_partners, ptlrpcd_ctl::pc_set, ptlrpc_check_set(), ptlrpc_req_finished(), ptlrpc_reqset_get(), ptlrpc_reqset_put(), ptlrpcd_steal_rqset(), RETURN, ptlrpc_request::rq_phase, RQ_PHASE_COMPLETE, rq_set_chain, and ptlrpc_request_set::set_new_count.
Referenced by ptlrpcd().
static void ptlrpcd_ctl_init (struct ptlrpcd_ctl * pc, int index, int cpt) [static]
Definition at line 526 of file ptlrpcd.c.
References ENTRY, EXIT, ptlrpcd_ctl::pc_cpt, ptlrpcd_ctl::pc_finishing, ptlrpcd_ctl::pc_index, ptlrpcd_ctl::pc_lock, ptlrpcd_ctl::pc_name, and ptlrpcd_ctl::pc_starting.
Referenced by ptlrpcd_init().
void ptlrpcd_decref (void)
Definition at line 971 of file ptlrpcd.c.
References ptlrpcd_fini(), ptlrpcd_mutex, and ptlrpcd_users.
Referenced by lwp_device_fini(), lwp_init0(), mdc_cleanup(), mdc_setup(), mgc_cleanup(), mgc_setup(), osc_cleanup(), osc_setup(), osp_device_fini(), osp_init0(), and ptlrpc_exit_portals().
static void ptlrpcd_fini (void) [static]
Definition at line 701 of file ptlrpcd.c.
References cfs_cpt_number(), ENTRY, EXIT, OBD_FREE, pd_nthreads, ptlrpcd_free(), ptlrpcd_rcv, ptlrpcd_stop(), ptlrpcds_cpt_idx, and ptlrpcds_num.
Referenced by ptlrpcd_decref(), and ptlrpcd_init().
void ptlrpcd_free (struct ptlrpcd_ctl * pc)
Definition at line 666 of file ptlrpcd.c.
References CWARN, ENTRY, EXIT, LASSERT, lu_env::le_ctx, LIOD_FORCE, LIOD_START, LIOD_STOP, lu_context_fini(), OBD_FREE, ptlrpcd_ctl::pc_env, ptlrpcd_ctl::pc_error, ptlrpcd_ctl::pc_finishing, ptlrpcd_ctl::pc_flags, ptlrpcd_ctl::pc_lock, ptlrpcd_ctl::pc_npartners, ptlrpcd_ctl::pc_partners, ptlrpcd_ctl::pc_set, and ptlrpc_set_destroy().
Referenced by ptlrpcd_fini().
static int ptlrpcd_init (void) [static]
Definition at line 735 of file ptlrpcd.c.
References CERROR, CFS_CPT_ANY, cfs_cpt_number(), cfs_cpt_weight(), cfs_expr_list_free(), cfs_expr_list_parse(), cfs_expr_list_values(), cfs_expr_list_values_free(), CWARN, ENTRY, GOTO, LIOD_RECOVERY, max_ptlrpcds, nthreads, OBD_ALLOC, OBD_CPT_ALLOC, offsetof, ptlrpcd_ctl::pc_flags, pd_cpt, pd_cursor, pd_groupsize, pd_index, pd_nthreads, pd_size, pd_threads, ptlrpcd_bind_policy, ptlrpcd_cpts, ptlrpcd_ctl_init(), ptlrpcd_fini(), ptlrpcd_partner_group_size, ptlrpcd_partners(), ptlrpcd_per_cpt_max, ptlrpcd_rcv, ptlrpcd_start(), ptlrpcds_cpt_idx, ptlrpcds_num, RETURN, and size.
Referenced by ptlrpcd_addref().
static int ptlrpcd_partners (struct ptlrpcd * pd, int index) [static]
Definition at line 565 of file ptlrpcd.c.
References ENTRY, GOTO, LASSERT, OBD_CPT_ALLOC, ptlrpcd_ctl::pc_cpt, ptlrpcd_ctl::pc_npartners, ptlrpcd_ctl::pc_partners, pd_groupsize, pd_threads, and RETURN.
Referenced by ptlrpcd_init().
static struct ptlrpcd_ctl* ptlrpcd_select_pc (struct ptlrpc_request * req) [static, read]
Definition at line 171 of file ptlrpcd.c.
References cfs_cpt_current(), LUSTRE_IMP_FULL, pd_cursor, pd_nthreads, pd_threads, ptlrpcd_rcv, and ptlrpcds_cpt_idx.
Referenced by ptlrpcd_add_req(), and ptlrpcd_add_rqset().
int ptlrpcd_start (struct ptlrpcd_ctl * pc)
Definition at line 598 of file ptlrpcd.c.
References CWARN, ENTRY, GOTO, LCT_CL_THREAD, LCT_REMEMBER, lu_env::le_ctx, LIOD_START, lu_context_fini(), lu_context_init(), ptlrpcd_ctl::pc_env, ptlrpcd_ctl::pc_error, ptlrpcd_ctl::pc_flags, ptlrpcd_ctl::pc_lock, ptlrpcd_ctl::pc_name, ptlrpcd_ctl::pc_set, ptlrpcd_ctl::pc_starting, ptlrpc_set_destroy(), and RETURN.
Referenced by ptlrpcd_init().
static int ptlrpcd_steal_rqset (struct ptlrpc_request_set * des, struct ptlrpc_request_set * src) [static]
Return transferred RPCs count.
Definition at line 240 of file ptlrpcd.c.
References likely, list_empty(), list_entry, list_for_each_safe, list_splice_init(), rq_set_chain, ptlrpc_request_set::set_new_count, ptlrpc_request_set::set_new_req_lock, ptlrpc_request_set::set_new_requests, ptlrpc_request_set::set_remaining, and ptlrpc_request_set::set_requests.
Referenced by ptlrpcd_check().
void ptlrpcd_stop (struct ptlrpcd_ctl * pc, int force)
Definition at line 648 of file ptlrpcd.c.
References CWARN, ENTRY, EXIT, LIOD_FORCE, LIOD_START, LIOD_STOP, ptlrpcd_ctl::pc_flags, ptlrpcd_ctl::pc_set, and ptlrpc_request_set::set_waitq.
Referenced by ptlrpcd_fini().
void ptlrpcd_wake (struct ptlrpc_request * req)
Definition at line 161 of file ptlrpcd.c.
References LASSERT.
Variable Documentation
int max_ptlrpcds [static]
Definition at line 87 of file ptlrpcd.c.
Referenced by ptlrpcd_init().
int ptlrpcd_bind_policy [static]
Definition at line 97 of file ptlrpcd.c.
Referenced by ptlrpcd_init().
char* ptlrpcd_cpts [static]
Definition at line 137 of file ptlrpcd.c.
Referenced by ptlrpcd_init().
struct mutex ptlrpcd_mutex
Definition at line 158 of file ptlrpcd.c.
Referenced by ptlrpc_init(), ptlrpcd_addref(), and ptlrpcd_decref().
int ptlrpcd_partner_group_size [static]
Definition at line 116 of file ptlrpcd.c.
Referenced by ptlrpcd_init().
int ptlrpcd_per_cpt_max [static]
Definition at line 106 of file ptlrpcd.c.
Referenced by ptlrpcd_init().
struct ptlrpcd_ctl ptlrpcd_rcv [static]
Definition at line 156 of file ptlrpcd.c.
Referenced by ptlrpcd_fini(), ptlrpcd_init(), and ptlrpcd_select_pc().
int ptlrpcd_users = 0 [static]
Definition at line 159 of file ptlrpcd.c.
Referenced by ptlrpcd_addref(), and ptlrpcd_decref().
struct ptlrpcd** ptlrpcds [static]
Definition at line 147 of file ptlrpcd.c.
int* ptlrpcds_cpt_idx [static]
Definition at line 143 of file ptlrpcd.c.
Referenced by ptlrpcd_fini(), ptlrpcd_init(), and ptlrpcd_select_pc().
int ptlrpcds_num [static]
Definition at line 146 of file ptlrpcd.c.
Referenced by ptlrpcd_fini(), and ptlrpcd_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.