Lustre: mdc
mdc
Data Structures
struct mdc_rpc_lock
Serializes in-flight MDT-modifying RPC requests to preserve idempotency.
Defines
#define MDC_FAKE_RPCL_IT ((void *)0x2c0012bfUL)
Functions
static void mdc_init_rpc_lock (struct mdc_rpc_lock *lck)
static void mdc_get_rpc_lock (struct mdc_rpc_lock *lck, struct lookup_intent *it)
static void mdc_put_rpc_lock (struct mdc_rpc_lock *lck, struct lookup_intent *it)
static void mdc_get_mod_rpc_slot (struct ptlrpc_request *req, struct lookup_intent *it)
static void mdc_put_mod_rpc_slot (struct ptlrpc_request *req, struct lookup_intent *it)
static void mdc_update_max_ea_from_body (struct obd_export *exp, struct mdt_body *body)
Update the maximum possible easize.
int it_open_error (int phase, struct lookup_intent *it)
static bool cl_is_lov_delay_create (unsigned int flags)
static void cl_lov_delay_create_clear (unsigned int *flags)
Define Documentation
#define MDC_FAKE_RPCL_IT ((void *)0x2c0012bfUL)
Definition at line 94 of file lustre_mdc.h.
Referenced by mdc_get_rpc_lock(), and mdc_put_rpc_lock().
Function Documentation
static bool cl_is_lov_delay_create (unsigned int flags) [inline, static]
Definition at line 227 of file lustre_mdc.h.
References O_LOV_DELAY_CREATE_1_8, and O_LOV_DELAY_CREATE_MASK.
Referenced by mds_pack_open_flags().
static void cl_lov_delay_create_clear (unsigned int * flags) [inline, static]
Definition at line 233 of file lustre_mdc.h.
References O_LOV_DELAY_CREATE_1_8, and O_LOV_DELAY_CREATE_MASK.
Referenced by ll_file_open(), and ll_lov_setstripe_ea_info().
int it_open_error (int phase, struct lookup_intent * it)
Definition at line 58 of file mdc_locks.c.
References CERROR, DISP_IT_EXECD, DISP_LOOKUP_EXECD, DISP_OPEN_CREATE, DISP_OPEN_LEASE, DISP_OPEN_OPEN, lookup_intent::it_disposition, it_disposition(), lookup_intent::it_status, and LBUG.
Referenced by ll_create_it(), ll_file_open(), ll_intent_file_open(), ll_lease_open(), ll_release_openhandle(), mdc_finish_enqueue(), and mdc_finish_intent_lock().
static void mdc_get_mod_rpc_slot (struct ptlrpc_request * req, struct lookup_intent * it) [inline, static]
Definition at line 168 of file lustre_mdc.h.
References obd_device::cli, obd_import::imp_obd, lustre_msg_get_opc(), lustre_msg_set_tag(), obd_get_mod_rpc_slot(), ptlrpc_request::rq_import, ptlrpc_request::rq_reqmsg, and obd_device::u.
Referenced by mdc_close(), mdc_enqueue(), mdc_ioc_hsm_progress(), mdc_ioc_hsm_request(), mdc_ioc_hsm_state_set(), mdc_reint(), and mdc_xattr_common().
static void mdc_get_rpc_lock (struct mdc_rpc_lock * lck, struct lookup_intent * it) [inline, static]
Definition at line 102 of file lustre_mdc.h.
References CFS_FAIL_CHECK_QUIET, cfs_time_seconds(), ENTRY, IT_GETATTR, IT_LAYOUT, IT_LOOKUP, lookup_intent::it_op, IT_READDIR, LASSERT, MDC_FAKE_RPCL_IT, OBD_FAIL_MDC_RPCS_SEM, mdc_rpc_lock::rpcl_fakes, mdc_rpc_lock::rpcl_it, mdc_rpc_lock::rpcl_mutex, and unlikely.
Referenced by osp_get_rpc_lock().
static void mdc_init_rpc_lock (struct mdc_rpc_lock * lck) [inline, static]
Definition at line 96 of file lustre_mdc.h.
References mdc_rpc_lock::rpcl_it, and mdc_rpc_lock::rpcl_mutex.
static void mdc_put_mod_rpc_slot (struct ptlrpc_request * req, struct lookup_intent * it) [inline, static]
Definition at line 180 of file lustre_mdc.h.
References obd_device::cli, obd_import::imp_obd, lustre_msg_get_opc(), lustre_msg_get_tag(), obd_put_mod_rpc_slot(), ptlrpc_request::rq_import, ptlrpc_request::rq_reqmsg, and obd_device::u.
Referenced by mdc_close(), mdc_enqueue(), mdc_ioc_hsm_progress(), mdc_ioc_hsm_request(), mdc_ioc_hsm_state_set(), mdc_reint(), and mdc_xattr_common().
static void mdc_put_rpc_lock (struct mdc_rpc_lock * lck, struct lookup_intent * it) [inline, static]
Definition at line 142 of file lustre_mdc.h.
References EXIT, IT_GETATTR, IT_LAYOUT, IT_LOOKUP, lookup_intent::it_op, IT_READDIR, LASSERTF, MDC_FAKE_RPCL_IT, mdc_rpc_lock::rpcl_fakes, mdc_rpc_lock::rpcl_it, and mdc_rpc_lock::rpcl_mutex.
Referenced by osp_put_rpc_lock().
static void mdc_update_max_ea_from_body (struct obd_export * exp, struct mdt_body * body) [inline, static]
Update the maximum possible easize.
This value is learned from ptlrpc replies sent by the MDT. The default easize is initialized to the minimum value but allowed to grow up to a single page in size if required to handle the common case.
See also:
client_obd::cl_default_mds_easize
Parameters:
[in] exp export for MDC device
[in] body body of ptlrpc reply from MDT
Definition at line 207 of file lustre_mdc.h.
References client_obd::cl_default_mds_easize, client_obd::cl_max_mds_easize, obd_device::cli, obd_export::exp_obd, mdt_body::mbo_max_mdsize, mdt_body::mbo_valid, min_t, OBD_MAX_DEFAULT_EA_SIZE, OBD_MD_FLMODEASIZE, and obd_device::u.
Referenced by mdc_finish_enqueue(), and mdc_getattr_common().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.