Lustre: fld
fld
Data Structures
struct lu_fld_target
struct lu_server_fld
struct lu_client_fld
Enumerations
enum { LUSTRE_CLI_FLD_HASH_DHT = 0, LUSTRE_CLI_FLD_HASH_RRB }
Functions
int fld_server_init (const struct lu_env *env, struct lu_server_fld *fld, struct dt_device *dt, const char *prefix, int type)
void fld_server_fini (const struct lu_env *env, struct lu_server_fld *fld)
int fld_declare_server_create (const struct lu_env *env, struct lu_server_fld *fld, const struct lu_seq_range *range, struct thandle *th)
int fld_server_create (const struct lu_env *env, struct lu_server_fld *fld, const struct lu_seq_range *add_range, struct thandle *th)
Insert FLD index entry and update FLD cache.
int fld_insert_entry (const struct lu_env *env, struct lu_server_fld *fld, const struct lu_seq_range *range)
insert entry in fld store.
int fld_server_lookup (const struct lu_env *env, struct lu_server_fld *fld, u64 seq, struct lu_seq_range *range)
Lookup MDT/OST by seq, returns a range for given seq.
int fld_local_lookup (const struct lu_env *env, struct lu_server_fld *fld, u64 seq, struct lu_seq_range *range)
Lookup sequece in local cache/fldb.
int fld_update_from_controller (const struct lu_env *env, struct lu_server_fld *fld)
Retrieve fldb entry from MDT0 and add to local FLDB and cache.
int fld_client_init (struct lu_client_fld *fld, const char *prefix, int hash)
void fld_client_fini (struct lu_client_fld *fld)
void fld_client_flush (struct lu_client_fld *fld)
int fld_client_lookup (struct lu_client_fld *fld, u64 seq, u32 *mds, __u32 flags, const struct lu_env *env)
int fld_client_create (struct lu_client_fld *fld, struct lu_seq_range *range, const struct lu_env *env)
int fld_client_delete (struct lu_client_fld *fld, u64 seq, const struct lu_env *env)
int fld_client_add_target (struct lu_client_fld *fld, struct lu_fld_target *tar)
int fld_client_del_target (struct lu_client_fld *fld, __u64 idx)
void fld_client_proc_fini (struct lu_client_fld *fld)
Enumeration Type Documentation
anonymous enum
Enumerator:
LUSTRE_CLI_FLD_HASH_DHT
LUSTRE_CLI_FLD_HASH_RRB
Definition at line 61 of file lustre_fld.h.
Function Documentation
int fld_client_add_target (struct lu_client_fld * fld, struct lu_fld_target * tar)
Definition at line 155 of file fld_request.c.
References CDEBUG, CERROR, class_export_get(), D_INFO, ENTRY, fld_target_name(), lu_fld_target::ft_chain, lu_fld_target::ft_exp, lu_fld_target::ft_idx, lu_fld_target::ft_srv, LASSERT, lu_client_fld::lcf_count, lu_client_fld::lcf_lock, lu_client_fld::lcf_name, lu_client_fld::lcf_targets, list_add_tail(), list_for_each_entry, LPU64, name, OBD_ALLOC_PTR, OBD_FREE_PTR, and RETURN.
Referenced by lmv_connect_mdc().
int fld_client_create (struct lu_client_fld * fld, struct lu_seq_range * range, const struct lu_env * env)
int fld_client_del_target (struct lu_client_fld * fld, __u64 idx)
Definition at line 201 of file fld_request.c.
References class_export_put(), ENTRY, lu_fld_target::ft_chain, lu_fld_target::ft_exp, lu_fld_target::ft_idx, lu_client_fld::lcf_count, lu_client_fld::lcf_lock, lu_client_fld::lcf_targets, list_del(), list_for_each_entry_safe, OBD_FREE_PTR, and RETURN.
int fld_client_delete (struct lu_client_fld * fld, u64 seq, const struct lu_env * env)
void fld_client_fini (struct lu_client_fld * fld)
Definition at line 333 of file fld_request.c.
References class_export_put(), ENTRY, EXIT, fld_cache_fini(), lu_fld_target::ft_chain, lu_fld_target::ft_exp, lu_client_fld::lcf_cache, lu_client_fld::lcf_count, lu_client_fld::lcf_lock, lu_client_fld::lcf_targets, list_del(), list_for_each_entry_safe, and OBD_FREE_PTR.
Referenced by fld_client_init(), and lmv_cleanup().
void fld_client_flush (struct lu_client_fld * fld)
Definition at line 532 of file fld_request.c.
References fld_cache_flush(), and lu_client_fld::lcf_cache.
Referenced by lmv_notify().
int fld_client_init (struct lu_client_fld * fld, const char * prefix, int hash)
Definition at line 282 of file fld_request.c.
References CDEBUG, CERROR, D_INFO, ENTRY, EXIT, lu_fld_hash::fh_name, fld_cache_init(), FLD_CLIENT_CACHE_SIZE, FLD_CLIENT_CACHE_THRESHOLD, fld_client_fini(), fld_client_proc_init(), GOTO, hash_is_sane(), INIT_LIST_HEAD, LASSERT, lu_client_fld::lcf_cache, lu_client_fld::lcf_count, lu_client_fld::lcf_hash, lu_client_fld::lcf_lock, lu_client_fld::lcf_name, lu_client_fld::lcf_targets, and RETURN.
Referenced by lmv_setup().
int fld_client_lookup (struct lu_client_fld * fld, u64 seq, u32 * mds, __u32 flags, const struct lu_env * env)
Definition at line 465 of file fld_request.c.
References CDEBUG, D_INFO, ENTRY, fld_cache_insert(), fld_cache_lookup(), fld_client_get_target(), fld_client_rpc(), FLD_QUERY, fld_range_set_type(), fld_server_lookup(), fld_target_name(), lu_fld_target::ft_chain, lu_fld_target::ft_exp, lu_fld_target::ft_idx, lu_fld_target::ft_srv, LASSERT, lu_client_fld::lcf_cache, lu_client_fld::lcf_lock, lu_client_fld::lcf_name, lu_client_fld::lcf_targets, list_entry, LPU64, LPX64, lu_seq_range::lsr_index, lu_seq_range::lsr_start, list_head::next, and RETURN.
Referenced by lmv_fld_lookup().
void fld_client_proc_fini (struct lu_client_fld * fld)
Definition at line 269 of file fld_request.c.
Referenced by lmv_precleanup().
int fld_declare_server_create (const struct lu_env * env, struct lu_server_fld * fld, const struct lu_seq_range * range, struct thandle * th)
Definition at line 76 of file fld_handler.c.
References fld_declare_index_create(), and RETURN.
Referenced by seq_store_update().
int fld_insert_entry (const struct lu_env * env, struct lu_server_fld * fld, const struct lu_seq_range * range)
insert entry in fld store.
Parameters:
env relevant lu_env
fld fld store
range range to be inserted
Return values:
0 success
-ve error
Caller must hold fld->lsf_lock
Definition at line 273 of file fld_index.c.
References dt_object::do_lu, dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), ENTRY, fld_declare_index_create(), fld_index_create(), GOTO, LASSERT, lu_object::lo_dev, lu_server_fld::lsf_lock, lu_server_fld::lsf_obj, lu2dt_dev(), and RETURN.
Referenced by fld_insert_special_entries(), fld_update_from_controller(), and seq_server_check_and_alloc_super().
int fld_local_lookup (const struct lu_env * env, struct lu_server_fld * fld, u64 seq, struct lu_seq_range * range)
Lookup sequece in local cache/fldb.
Definition at line 205 of file fld_handler.c.
References CERROR, DRANGE, ENTRY, fld_cache_lookup(), fld_range_is_any(), fld_range_type(), fld_thread_key, LASSERT, lu_env::le_ctx, lu_server_fld::lsf_cache, lu_server_fld::lsf_name, lu_seq_range::lsr_flags, lu_context_key_get(), PRANGE, RETURN, and unlikely.
Referenced by fld_server_lookup(), lfsck_master_oit_engine(), lfsck_namespace_exec_oit(), lfsck_namespace_scan_local_lpf(), lfsck_needs_scan_dir(), and osd_fld_lookup().
int fld_server_create (const struct lu_env * env, struct lu_server_fld * fld, const struct lu_seq_range * range, struct thandle * th)
Insert FLD index entry and update FLD cache.
This function is called from the sequence allocator when a super-sequence is granted to a server.
Definition at line 94 of file fld_handler.c.
References fld_index_create(), lu_server_fld::lsf_lock, and RETURN.
Referenced by seq_store_update().
void fld_server_fini (const struct lu_env * env, struct lu_server_fld * fld)
Definition at line 487 of file fld_handler.c.
References ENTRY, EXIT, fld_cache_fini(), fld_index_fini(), fld_server_proc_fini(), and lu_server_fld::lsf_cache.
Referenced by mdt_fld_fini(), and ofd_fld_fini().
int fld_server_init (const struct lu_env * env, struct lu_server_fld * fld, struct dt_device * dt, const char * prefix, int type)
Definition at line 443 of file fld_handler.c.
References ENTRY, fld_cache_fini(), fld_cache_init(), fld_index_fini(), fld_index_init(), FLD_SERVER_CACHE_SIZE, FLD_SERVER_CACHE_THRESHOLD, fld_server_lookup(), fld_server_proc_init(), GOTO, lu_server_fld::lsf_cache, lu_server_fld::lsf_control_exp, lu_server_fld::lsf_lock, lu_server_fld::lsf_name, lu_server_fld::lsf_seq_lookup, and RETURN.
Referenced by mdt_fld_init(), and ofd_fld_init().
int fld_server_lookup (const struct lu_env * env, struct lu_server_fld * fld, u64 seq, struct lu_seq_range * range)
Lookup MDT/OST by seq, returns a range for given seq.
If that entry is not cached in fld cache, request is sent to super sequence controller node (MDT0). All other MDT[1...N] and client cache fld entries, but this cache is not persistent.
Definition at line 241 of file fld_handler.c.
References CERROR, ENTRY, fld_cache_insert(), fld_client_rpc(), fld_local_lookup(), fld_name_to_index(), FLD_QUERY, LDD_F_SV_TYPE_MDT, likely, LPX64, lu_server_fld::lsf_cache, lu_server_fld::lsf_control_exp, lu_server_fld::lsf_name, lu_seq_range::lsr_start, and RETURN.
Referenced by fid_is_for_ostobj(), fld_client_lookup(), fld_handle_lookup(), fld_server_init(), lfsck_fid_match_idx(), lfsck_find_mdt_idx_by_fid(), lfsck_layout_slave_check_pairs(), lfsck_namespace_set_lmv_master(), lfsck_namespace_striped_dir_rescan(), lod_fld_lookup(), and mdd_fld_lookup().
int fld_update_from_controller (const struct lu_env * env, struct lu_server_fld * fld)
Retrieve fldb entry from MDT0 and add to local FLDB and cache.
Definition at line 128 of file fld_handler.c.
References ENTRY, fld_client_rpc(), fld_insert_entry(), fld_name_to_index(), fld_range_set_mdt(), FLD_READ, fld_thread_key, GOTO, LASSERT, lu_env::le_ctx, lu_server_fld::lsf_control_exp, lu_server_fld::lsf_lock, lu_server_fld::lsf_name, lu_server_fld::lsf_new, lu_seq_range::lsr_flags, lu_seq_range::lsr_index, lu_seq_range_array::lsra_count, lu_seq_range_array::lsra_lsr, lu_context_key_get(), LU_SEQ_RANGE_MDT, ptlrpc_req_finished(), range_array_le_to_cpu(), req_capsule_server_get(), RETURN, RMF_GENERIC_DATA, and ptlrpc_request::rq_pill.
Referenced by mdt_register_lwp_callback(), and ofd_register_lwp_callback().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.