Lustre: cl_env
cl_env
[clio]
lu_env handling for a client.
Data Structures
struct cl_env_nest
Functions
struct lu_env * cl_env_peek (__u16 *refcheck)
struct lu_env * cl_env_get (__u16 *refcheck)
Returns lu_env: if there already is an environment associated with the current thread, it is returned, otherwise, new environment is allocated.
struct lu_env * cl_env_alloc (__u16 *refcheck, __u32 tags)
Forces an allocation of a fresh environment with given tags.
struct lu_env * cl_env_nested_get (struct cl_env_nest *nest)
void cl_env_put (struct lu_env *env, __u16 *refcheck)
Release an environment.
void cl_env_nested_put (struct cl_env_nest *nest, struct lu_env *env)
void * cl_env_reenter (void)
Declares a point of re-entrancy.
void cl_env_reexit (void *cookie)
Exits re-entrancy.
void cl_env_implant (struct lu_env *env, __u16 *refcheck)
Setup user-supplied env as a current environment.
void cl_env_unplant (struct lu_env *env, __u16 *refcheck)
Detach environment installed earlier by cl_env_implant().
unsigned cl_env_cache_purge (unsigned nr)
Finalizes and frees a given number of cached environments.
struct lu_env * cl_env_percpu_get (void)
void cl_env_percpu_put (struct lu_env *env)
Detailed Description
lu_env handling for a client.
lu_env is an environment within which lustre code executes. Its major part is lu_context---a fast memory allocation mechanism that is used to conserve precious kernel stack space. Originally lu_env was designed for a server, where
there is a (mostly) fixed number of threads, and
call chains have no non-lustre portions inserted between lustre code.
On a client both these assumtpion fails, because every user thread can potentially execute lustre code as part of a system call, and lustre calls into VFS or MM that call back into lustre.
To deal with that, cl_env wrapper functions implement the following optimizations:
allocation and destruction of environment is amortized by caching no longer used environments instead of destroying them;
there is a notion of "current" environment, attached to the kernel data structure representing current thread Top-level lustre code allocates an environment and makes it current, then calls into non-lustre code, that in turn calls lustre back. Low-level lustre code thus called can fetch environment created by the top-level code and reuse it, avoiding additional environment allocation. Right now, three interfaces can attach the cl_env to running thread:
cl_env_get
cl_env_implant
cl_env_reexit(cl_env_reenter had to be called priorly)
See also:
lu_env, lu_context, lu_context_key
Function Documentation
struct lu_env* cl_env_alloc (__u16 * refcheck, __u32 tags) [read]
Forces an allocation of a fresh environment with given tags.
See also:
cl_env_get()
Definition at line 931 of file cl_object.c.
References CDEBUG, ce_ref, cl_env_container(), cl_env_new(), cl_env_peek(), D_OTHER, and LASSERT.
Referenced by lov_emerg_alloc(), and lustre_init().
unsigned cl_env_cache_purge (unsigned nr)
Finalizes and frees a given number of cached environments.
This is done to (1) free some memory (not currently hooked into VM), or (2) release references to modules.
Definition at line 960 of file cl_object.c.
References ce_linkage, cl_env_fini(), cl_envs, ENTRY, equi, LASSERT, list_del_init(), list_empty(), list_head::next, and RETURN.
Referenced by ll_put_super(), and lu_context_key_quiesce().
struct lu_env* cl_env_get (__u16 * refcheck) [read]
Returns lu_env: if there already is an environment associated with the current thread, it is returned, otherwise, new environment is allocated.
Allocations are amortized through the global cache of environments.
Parameters:
refcheck pointer to a counter used to detect environment leaks. In the usual case cl_env_get() and cl_env_put() are called in the same lexical scope and pointer to the same integer is passed as refcheck. This is used to detect missed cl_env_put().
See also:
cl_env_put()
Definition at line 906 of file cl_object.c.
References CDEBUG, ce_ref, cl_env_attach(), cl_env_container(), cl_env_obtain(), cl_env_peek(), and D_OTHER.
Referenced by cl_echo_object_brw(), cl_echo_object_find(), cl_echo_object_put(), cl_env_implant(), cl_env_nested_get(), cl_file_inode_init(), cl_get_grouplock(), cl_inode_fini(), cl_io_get(), cl_sb_fini(), cl_sb_init(), cl_setattr_ost(), echo_client_iocontrol(), ll_data_version(), ll_direct_IO(), ll_do_fiemap(), ll_file_aio_read(), ll_file_aio_write(), ll_file_getstripe(), ll_file_read(), ll_file_read_iter(), ll_file_splice_read(), ll_file_write(), ll_file_write_iter(), ll_getxattr_lov(), ll_invalidatepage(), loop_thread(), lov_io_sub_init(), lov_layout_change(), osc_import_event(), vvp_pgcache_next(), vvp_pgcache_show(), and vvp_pgcache_start().
void cl_env_implant (struct lu_env * env, __u16 * refcheck)
Setup user-supplied env as a current environment.
This is to be used to guaranteed that environment exists even when cl_env_get() fails. It is up to user to ensure proper concurrency control.
See also:
cl_env_unplant()
Definition at line 1051 of file cl_object.c.
References CDEBUG, ce_ref, cl_env_attach(), cl_env_container(), cl_env_get(), D_OTHER, and LASSERT.
Referenced by cl_inode_fini(), and cl_put_grouplock().
struct lu_env* cl_env_nested_get (struct cl_env_nest * nest) [read]
Definition at line 1079 of file cl_object.c.
References cl_env_nest::cen_cookie, cl_env_nest::cen_refcheck, cl_env_get(), cl_env_peek(), cl_env_put(), cl_env_reenter(), cl_env_reexit(), cl_io_is_going(), and LASSERT.
Referenced by cl_sync_file_range(), ll_fault_io_init(), ll_hsm_release(), ll_ladvise(), ll_layout_conf(), ll_writepage(), osc_cache_shrink_scan(), osc_extent_truncate(), osc_ldlm_blocking_ast(), osc_ldlm_glimpse_ast(), osc_ldlm_weigh_ast(), osc_lock_flush(), osc_lock_upcall(), osc_lock_upcall_agl(), and osc_lru_reclaim().
void cl_env_nested_put (struct cl_env_nest * nest, struct lu_env * env)
Definition at line 1104 of file cl_object.c.
References cl_env_nest::cen_cookie, cl_env_nest::cen_refcheck, cl_env_put(), and cl_env_reexit().
Referenced by cl_sync_file_range(), ll_fault0(), ll_fault_io_init(), ll_hsm_release(), ll_ladvise(), ll_layout_conf(), ll_page_mkwrite0(), ll_writepage(), osc_cache_shrink_scan(), osc_extent_truncate(), osc_ldlm_blocking_ast(), osc_ldlm_glimpse_ast(), osc_ldlm_weigh_ast(), osc_lock_flush(), osc_lock_upcall(), osc_lock_upcall_agl(), and osc_lru_reclaim().
struct lu_env* cl_env_peek (__u16 * refcheck) [read]
Definition at line 872 of file cl_object.c.
References CDEBUG, ce_lu, ce_magic, ce_ref, cl_env_fetch(), CL_ENV_INC, CLASSERT, D_OTHER, lookup(), and offsetof.
Referenced by cl_env_alloc(), cl_env_get(), and cl_env_nested_get().
struct lu_env* cl_env_percpu_get (void) [read]
Definition at line 1229 of file cl_object.c.
References ce_lu, cl_env_attach(), cl_env_init0(), and cl_env_percpu.
Referenced by ll_releasepage().
void cl_env_percpu_put (struct lu_env * env)
Definition at line 1209 of file cl_object.c.
References ce_debug, ce_ref, cl_env_container(), CL_ENV_DEC, cl_env_detach(), cl_env_percpu, and LASSERT.
Referenced by ll_releasepage().
void cl_env_put (struct lu_env * env, __u16 * refcheck)
Release an environment.
Decrement env reference counter. When counter drops to 0, nothing in this thread is using environment and it is returned to the allocation cache, or freed straight away, if cache is large enough.
Definition at line 989 of file cl_object.c.
References CDEBUG, ce_debug, ce_linkage, ce_ref, cl_env_container(), CL_ENV_DEC, cl_env_detach(), cl_env_exit(), cl_env_fini(), cl_envs, D_OTHER, ergo, LASSERT, lu_context::lc_tags, LCT_CL_THREAD, LCT_HAS_EXIT, LCT_SESSION, lu_env::le_ctx, lu_env::le_ses, and list_add().
Referenced by cl_echo_object_brw(), cl_echo_object_find(), cl_echo_object_put(), cl_env_nested_get(), cl_env_nested_put(), cl_env_unplant(), cl_file_inode_init(), cl_get_grouplock(), cl_glimpse_size0(), cl_inode_fini(), cl_put_grouplock(), cl_sb_fini(), cl_sb_init(), cl_setattr_ost(), echo_client_iocontrol(), ll_data_version(), ll_direct_IO(), ll_do_fiemap(), ll_file_aio_read(), ll_file_aio_write(), ll_file_getstripe(), ll_file_read(), ll_file_read_iter(), ll_file_splice_read(), ll_file_write(), ll_file_write_iter(), ll_getxattr_lov(), ll_invalidatepage(), loop_thread(), lov_emerg_free(), lov_io_sub_fini(), lov_layout_change(), lustre_exit(), lustre_init(), osc_import_event(), vvp_pgcache_next(), vvp_pgcache_show(), and vvp_pgcache_start().
void* cl_env_reenter (void)
Declares a point of re-entrancy.
See also:
cl_env_reexit()
Definition at line 1028 of file cl_object.c.
References cl_env_detach().
Referenced by cl_env_nested_get(), cl_inode_fini(), ll_releasepage(), lov_io_sub_init(), and lov_layout_change().
void cl_env_reexit (void * cookie)
Exits re-entrancy.
Definition at line 1037 of file cl_object.c.
References cl_env_attach(), and cl_env_detach().
Referenced by cl_env_nested_get(), cl_env_nested_put(), cl_inode_fini(), ll_releasepage(), lov_io_sub_init(), and lov_layout_change().
void cl_env_unplant (struct lu_env * env, __u16 * refcheck)
Detach environment installed earlier by cl_env_implant().
Definition at line 1066 of file cl_object.c.
References CDEBUG, ce_ref, cl_env_container(), cl_env_detach(), cl_env_put(), D_OTHER, and LASSERT.
Referenced by cl_get_grouplock(), and cl_inode_fini().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.