Lustre: debug
debug
Defines
#define LL_CDEBUG_PAGE(mask, page, fmt, arg...)
#define ASSERT_MAX_SIZE_MB 60000ULL
#define ASSERT_PAGE_INDEX(index, OP)
#define ASSERT_FILE_OFFSET(offset, OP)
Functions
void dump_lniobuf (struct niobuf_local *lnb)
int dump_req (struct ptlrpc_request *req)
int block_debug_setup (void *addr, int len, __u64 off, __u64 id)
int block_debug_check (char *who, void *addr, int len, __u64 off, __u64 id)
Define Documentation
#define ASSERT_FILE_OFFSET (offset, OP)
Value:
do { if (offset > ASSERT_MAX_SIZE_MB << 20) {                           \
        CERROR("bad file offset %llu > %llu\n", offset,                 \
               ASSERT_MAX_SIZE_MB << 20);                               \
        libcfs_debug = ~0UL;                                            \
        OP;                                                             \
}} while(0)
Definition at line 62 of file lustre_debug.h.
#define ASSERT_MAX_SIZE_MB 60000ULL
Definition at line 53 of file lustre_debug.h.
#define ASSERT_PAGE_INDEX (index, OP)
Value:
do { if (index > ASSERT_MAX_SIZE_MB << (20 - PAGE_CACHE_SHIFT)) {         \
        CERROR("bad page index %lu > %llu\n", index,                    \
               ASSERT_MAX_SIZE_MB << (20 - PAGE_CACHE_SHIFT));            \
        libcfs_debug = ~0UL;                                            \
        OP;                                                             \
}} while(0)
Definition at line 54 of file lustre_debug.h.
#define LL_CDEBUG_PAGE (mask, page, fmt, arg...)
Value:
CDEBUG(mask, "page %p map %p index %lu flags %lx count %u priv %0lx: " \
               fmt, page, page->mapping, page->index, (long)page->flags, \
               page_count(page), page_private(page), ## arg)
Definition at line 48 of file lustre_debug.h.
Referenced by osc_checksum_bulk(), and vvp_io_kernel_fault().
Function Documentation
int block_debug_check (char * who, void * addr, int len, __u64 off, __u64 id)
Definition at line 75 of file debug.c.
References __u64, CDEBUG, D_ERROR, LASSERT, le64_to_cpu, LPDS, LPU64, and LPX64.
Referenced by echo_client_page_debug_check(), echo_page_debug_check(), and main().
int block_debug_setup (void * addr, int len, __u64 off, __u64 id)
Definition at line 58 of file debug.c.
References cpu_to_le64, LASSERT, and LPDS.
Referenced by echo_client_page_debug_setup(), echo_page_debug_setup(), and main().
void dump_lniobuf (struct niobuf_local * lnb)
Definition at line 48 of file debug.c.
References CDEBUG, D_RPCTRACE, niobuf_local::lnb_file_offset, niobuf_local::lnb_len, niobuf_local::lnb_page, niobuf_local::lnb_rc, and LPD64.
int dump_req (struct ptlrpc_request * req)
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.