Lustre: idmap
idmap
Data Structures
struct lustre_idmap_table
Defines
#define CFS_NGROUPS_PER_BLOCK ((int)(PAGE_CACHE_SIZE / sizeof(gid_t)))
#define CFS_GROUP_AT(gi, i) ((gi)->blocks[(i) / CFS_NGROUPS_PER_BLOCK][(i) % CFS_NGROUPS_PER_BLOCK])
#define CFS_IDMAP_NOTFOUND (-1)
#define CFS_IDMAP_HASHSIZE 32
Enumerations
enum { CFS_IC_NOTHING = 0, CFS_IC_ALL = 1, CFS_IC_MAPPED = 2, CFS_IC_UNMAPPED = 3 }
enum lustre_idmap_idx {
RMT_UIDMAP_IDX, LCL_UIDMAP_IDX, RMT_GIDMAP_IDX, LCL_GIDMAP_IDX,
CFS_IDMAP_N_HASHES
}
Functions
void lustre_groups_from_list (struct group_info *ginfo, gid_t *glist)
void lustre_groups_sort (struct group_info *group_info)
int lustre_in_group_p (struct lu_ucred *mu, gid_t grp)
int lustre_idmap_add (struct lustre_idmap_table *t, uid_t ruid, uid_t luid, gid_t rgid, gid_t lgid)
int lustre_idmap_del (struct lustre_idmap_table *t, uid_t ruid, uid_t luid, gid_t rgid, gid_t lgid)
int lustre_idmap_lookup_uid (struct lu_ucred *mu, struct lustre_idmap_table *t, int reverse, uid_t uid)
int lustre_idmap_lookup_gid (struct lu_ucred *mu, struct lustre_idmap_table *t, int reverse, gid_t gid)
struct lustre_idmap_table * lustre_idmap_init (void)
void lustre_idmap_fini (struct lustre_idmap_table *t)
Define Documentation
#define CFS_GROUP_AT (gi, i) ((gi)->blocks[(i) / CFS_NGROUPS_PER_BLOCK][(i) % CFS_NGROUPS_PER_BLOCK])
Definition at line 54 of file lustre_idmap.h.
Referenced by lustre_groups_search(), and lustre_groups_sort().
#define CFS_IDMAP_HASHSIZE 32
Definition at line 66 of file lustre_idmap.h.
Referenced by lustre_idmap_fini(), and lustre_idmap_hashfunc().
#define CFS_IDMAP_NOTFOUND (-1)
Definition at line 64 of file lustre_idmap.h.
Referenced by idmap_lookup_gid(), idmap_lookup_uid(), lustre_idmap_lookup_gid(), lustre_idmap_lookup_uid(), mdt_body_reverse_idmap(), mdt_fix_attr_ucred(), mdt_quotactl(), and ptlrpc_user_desc_do_idmap().
#define CFS_NGROUPS_PER_BLOCK ((int)(PAGE_CACHE_SIZE / sizeof(gid_t)))
Definition at line 52 of file lustre_idmap.h.
Referenced by lustre_groups_from_list().
Enumeration Type Documentation
anonymous enum
Enumerator:
CFS_IC_NOTHING
CFS_IC_ALL
CFS_IC_MAPPED
CFS_IC_UNMAPPED
Definition at line 57 of file lustre_idmap.h.
enum lustre_idmap_idx
Enumerator:
RMT_UIDMAP_IDX
LCL_UIDMAP_IDX
RMT_GIDMAP_IDX
LCL_GIDMAP_IDX
CFS_IDMAP_N_HASHES
Definition at line 68 of file lustre_idmap.h.
Function Documentation
void lustre_groups_from_list (struct group_info * ginfo, gid_t * glist)
Definition at line 92 of file idmap.c.
References CFS_NGROUPS_PER_BLOCK.
Referenced by mdt_identity_parse_downcall(), and new_init_ucred().
void lustre_groups_sort (struct group_info * group_info)
Definition at line 111 of file idmap.c.
References CFS_GROUP_AT, from_kgid(), make_kgid(), and max.
Referenced by mdt_identity_parse_downcall(), and new_init_ucred().
int lustre_idmap_add (struct lustre_idmap_table * t, uid_t ruid, uid_t luid, gid_t rgid, gid_t lgid)
Definition at line 309 of file idmap.c.
References idmap_entry_alloc(), idmap_entry_free(), idmap_search_entry(), LASSERT, LCL_GIDMAP_IDX, LCL_UIDMAP_IDX, lustre_idmap_entry::lie_lcl_gid_hash, lustre_idmap_entry::lie_lcl_uid_hash, lustre_idmap_entry::lie_rmt_gid_hash, lustre_idmap_entry::lie_rmt_uid_hash, list_add_tail(), lustre_idmap_table::lit_idmaps, lustre_idmap_table::lit_lock, lustre_idmap_hashfunc(), RMT_GIDMAP_IDX, and RMT_UIDMAP_IDX.
Referenced by mdt_handle_idmap().
int lustre_idmap_del (struct lustre_idmap_table * t, uid_t ruid, uid_t luid, gid_t rgid, gid_t lgid)
Definition at line 355 of file idmap.c.
References idmap_entry_free(), idmap_search_entry(), LASSERT, and lustre_idmap_table::lit_lock.
Referenced by mdt_handle_idmap().
void lustre_idmap_fini (struct lustre_idmap_table * t)
Definition at line 459 of file idmap.c.
References CFS_IDMAP_HASHSIZE, idmap_entry_free(), LASSERT, lustre_idmap_entry::lie_rmt_uid_hash, list, list_empty(), list_entry, lustre_idmap_table::lit_idmaps, lustre_idmap_table::lit_lock, OBD_FREE_PTR, and RMT_UIDMAP_IDX.
Referenced by mdt_cleanup_idmap().
struct lustre_idmap_table* lustre_idmap_init (void) [read]
Definition at line 441 of file idmap.c.
References ARRAY_SIZE, INIT_LIST_HEAD, lustre_idmap_table::lit_idmaps, lustre_idmap_table::lit_lock, OBD_ALLOC_PTR, and unlikely.
Referenced by mdt_init_idmap().
int lustre_idmap_lookup_gid (struct lu_ucred * mu, struct lustre_idmap_table * t, int reverse, gid_t gid)
Definition at line 409 of file idmap.c.
References CFS_IDMAP_NOTFOUND, idmap_lookup_gid(), LCL_GIDMAP_IDX, lustre_idmap_table::lit_idmaps, lustre_idmap_table::lit_lock, RMT_GIDMAP_IDX, lu_ucred::uc_fsgid, lu_ucred::uc_gid, lu_ucred::uc_o_fsgid, lu_ucred::uc_o_gid, lu_ucred::uc_valid, UCRED_NEW, and UCRED_OLD.
Referenced by mdt_body_reverse_idmap(), mdt_fix_attr_ucred(), mdt_quotactl(), and ptlrpc_user_desc_do_idmap().
int lustre_idmap_lookup_uid (struct lu_ucred * mu, struct lustre_idmap_table * t, int reverse, uid_t uid)
Definition at line 376 of file idmap.c.
References CFS_IDMAP_NOTFOUND, idmap_lookup_uid(), LCL_UIDMAP_IDX, lustre_idmap_table::lit_idmaps, lustre_idmap_table::lit_lock, RMT_UIDMAP_IDX, lu_ucred::uc_fsuid, lu_ucred::uc_o_fsuid, lu_ucred::uc_o_uid, lu_ucred::uc_uid, lu_ucred::uc_valid, UCRED_NEW, and UCRED_OLD.
Referenced by mdt_body_reverse_idmap(), mdt_fix_attr_ucred(), mdt_quotactl(), and ptlrpc_user_desc_do_idmap().
int lustre_in_group_p (struct lu_ucred * mu, gid_t grp)
Definition at line 144 of file idmap.c.
References lustre_get_group_info, lustre_groups_search(), lustre_put_group_info, md_identity::mi_ginfo, lu_ucred::uc_fsgid, lu_ucred::uc_ginfo, lu_ucred::uc_identity, lu_ucred::uc_suppgids, lu_ucred::uc_valid, and UCRED_OLD.
Referenced by __mdd_permission_internal(), hsm_action_permission(), and mdd_fix_attr().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.