Lustre: cl_io
cl_io
[clio]
Data Structures
struct cl_io_slice
IO state private for a layer.
struct cl_read_ahead
struct cl_io_operations
Per-layer io operations.
struct cl_io_lock_link
Link between lock and io.
struct cl_lockset
Lock-set represents a collection of locks, that io needs at a time.
struct cl_io_rw_common
struct cl_io
State for io.
Defines
#define cill_descr cill_lock.cll_descr
#define CL_IO_SLICE_CLEAN(foo_io, base)
Typedefs
typedef void(* cl_commit_cbt)(const struct lu_env *, struct cl_io *, struct cl_page *)
Enumerations
enum cl_io_type {
CIT_READ, CIT_WRITE, CIT_SETATTR, CIT_DATA_VERSION,
CIT_FAULT, CIT_FSYNC, CIT_MISC, CIT_LADVISE,
CIT_OP_NR
}
IO types.
enum cl_io_state {
CIS_ZERO, CIS_INIT, CIS_IT_STARTED, CIS_LOCKED,
CIS_IO_GOING, CIS_IO_FINISHED, CIS_UNLOCKED, CIS_IT_ENDED,
CIS_FINI
}
States of cl_io state machine.
enum cl_io_lock_dmd { CILR_MANDATORY = 0, CILR_MAYBE, CILR_NEVER }
Lock requirements(demand) for IO.
enum cl_fsync_mode { CL_FSYNC_NONE = 0, CL_FSYNC_LOCAL = 1, CL_FSYNC_DISCARD = 2, CL_FSYNC_ALL = 3 }
Functions
static void cl_read_ahead_release (const struct lu_env *env, struct cl_read_ahead *ra)
int cl_io_init (const struct lu_env *env, struct cl_io *io, enum cl_io_type iot, struct cl_object *obj)
Initialize io, by calling cl_io_operations::cio_init() top-to-bottom.
int cl_io_sub_init (const struct lu_env *env, struct cl_io *io, enum cl_io_type iot, struct cl_object *obj)
Initialize sub-io, by calling cl_io_operations::cio_init() top-to-bottom.
int cl_io_rw_init (const struct lu_env *env, struct cl_io *io, enum cl_io_type iot, loff_t pos, size_t count)
Initialize read or write io.
int cl_io_loop (const struct lu_env *env, struct cl_io *io)
Main io loop.
void cl_io_fini (const struct lu_env *env, struct cl_io *io)
Finalize io, by calling cl_io_operations::cio_fini() bottom-to-top.
int cl_io_iter_init (const struct lu_env *env, struct cl_io *io)
Prepares next iteration of io.
void cl_io_iter_fini (const struct lu_env *env, struct cl_io *io)
Finalizes io iteration.
int cl_io_lock (const struct lu_env *env, struct cl_io *io)
Takes locks necessary for the current iteration of io.
void cl_io_unlock (const struct lu_env *env, struct cl_io *io)
Release locks takes by io.
int cl_io_start (const struct lu_env *env, struct cl_io *io)
Starts io by calling cl_io_operations::cio_start() top-to-bottom.
void cl_io_end (const struct lu_env *env, struct cl_io *io)
Wait until current io iteration is finished by calling cl_io_operations::cio_end() bottom-to-top.
int cl_io_lock_add (const struct lu_env *env, struct cl_io *io, struct cl_io_lock_link *link)
Adds a lock to a lockset.
int cl_io_lock_alloc_add (const struct lu_env *env, struct cl_io *io, struct cl_lock_descr *descr)
Allocates new lock link, and uses it to add a lock to a lockset.
int cl_io_submit_rw (const struct lu_env *env, struct cl_io *io, enum cl_req_type iot, struct cl_2queue *queue)
Submits a list of pages for immediate io.
int cl_io_submit_sync (const struct lu_env *env, struct cl_io *io, enum cl_req_type iot, struct cl_2queue *queue, long timeout)
Submit a sync_io and wait for the IO to be finished, or error happens.
int cl_io_commit_async (const struct lu_env *env, struct cl_io *io, struct cl_page_list *queue, int from, int to, cl_commit_cbt cb)
Commit a list of contiguous pages into writeback cache.
int cl_io_read_ahead (const struct lu_env *env, struct cl_io *io, pgoff_t start, struct cl_read_ahead *ra)
Called by read io, to decide the readahead extent.
void cl_io_rw_advance (const struct lu_env *env, struct cl_io *io, size_t nob)
Records that read or write io progressed nob bytes forward.
int cl_io_cancel (const struct lu_env *env, struct cl_io *io, struct cl_page_list *queue)
Cancel an IO which has been submitted by cl_io_submit_rw.
int cl_io_is_going (const struct lu_env *env)
Returns true iff there is an IO ongoing in the given environment.
static int cl_io_is_append (const struct cl_io *io)
True, iff io is an O_APPEND write(2).
static int cl_io_is_sync_write (const struct cl_io *io)
static int cl_io_is_mkwrite (const struct cl_io *io)
static int cl_io_is_trunc (const struct cl_io *io)
True, iff io is a truncate(2).
struct cl_io * cl_io_top (struct cl_io *io)
Returns top-level io.
void cl_io_print (const struct lu_env *env, void *cookie, lu_printer_t printer, const struct cl_io *io)
Prints human readable representation of io to the f.
Define Documentation
#define cill_descr cill_lock.cll_descr
Definition at line 1668 of file cl_object.h.
#define CL_IO_SLICE_CLEAN (foo_io, base)
Value:
do {                                                                    \
        typeof(foo_io) __foo_io = (foo_io);                             \
                                                                        \
        CLASSERT(offsetof(typeof(*__foo_io), base) == 0);               \
        memset(&__foo_io->base + 1, 0,                                  \
               (sizeof *__foo_io) - sizeof __foo_io->base);             \
} while (0)
Definition at line 2314 of file cl_object.h.
Referenced by lov_io_init(), osc_io_init(), and vvp_io_init().
Typedef Documentation
typedef void(* cl_commit_cbt)(const struct lu_env *, struct cl_io *, struct cl_page *)
Definition at line 1451 of file cl_object.h.
Enumeration Type Documentation
enum cl_fsync_mode
Enumerator:
CL_FSYNC_NONE
start writeback, do not wait for them to finish
CL_FSYNC_LOCAL
start writeback and wait for them to finish
CL_FSYNC_DISCARD
discard all of dirty pages in a specific file range
CL_FSYNC_ALL
start writeback and make sure they have reached storage before return.
OST_SYNC RPC must be issued and finished
Definition at line 1719 of file cl_object.h.
enum cl_io_lock_dmd
Lock requirements(demand) for IO.
It should be cl_io_lock_req, but 'req' is always to be thought as 'request' :-)
Enumerator:
CILR_MANDATORY
Always lock data (e.g., O_APPEND).
CILR_MAYBE
Layers are free to decide between local and global locking.
CILR_NEVER
Never lock: there is no cache (e.g., liblustre).
Definition at line 1710 of file cl_object.h.
enum cl_io_state
States of cl_io state machine.
Enumerator:
CIS_ZERO
Not initialized.
CIS_INIT
Initialized.
CIS_IT_STARTED
IO iteration started.
CIS_LOCKED
Locks taken.
CIS_IO_GOING
Actual IO is in progress.
CIS_IO_FINISHED
IO for the current iteration finished.
CIS_UNLOCKED
Locks released.
CIS_IT_ENDED
Iteration completed.
CIS_FINI
cl_io finalized.
Definition at line 1409 of file cl_object.h.
enum cl_io_type
IO types.
Enumerator:
CIT_READ
read system call
CIT_WRITE
write system call
CIT_SETATTR
truncate, utime system calls
CIT_DATA_VERSION
get data version
CIT_FAULT
page fault handling
CIT_FSYNC
fsync system call handling To write out a range of file
CIT_MISC
Miscellaneous io.
This is used for occasional io activity that doesn't fit into other types. Currently this is used for:
cancellation of an extent lock. This io exists as a context to write dirty pages from under the lock being canceled back to the server;
VM induced page write-out. An io context for writing page out for memory cleansing;
glimpse. An io context to acquire glimpse lock.
grouplock. An io context to acquire group lock.
CIT_MISC io is used simply as a context in which locks and pages are manipulated. Such io has no internal "process", that is, cl_io_loop() is never called for it.
CIT_LADVISE
ladvise handling To give advice about access of a file
CIT_OP_NR
Definition at line 1360 of file cl_object.h.
Function Documentation
int cl_io_cancel (const struct lu_env * env, struct cl_io * io, struct cl_page_list * queue)
Cancel an IO which has been submitted by cl_io_submit_rw.
Definition at line 744 of file cl_io.c.
References CERROR, cl_page_cancel(), and cl_page_list_for_each.
int cl_io_commit_async (const struct lu_env * env, struct cl_io * io, struct cl_page_list * queue, int from, int to, cl_commit_cbt cb)
Commit a list of contiguous pages into writeback cache.
Returns:
0 if all pages committed, or errcode if error occurred.
See also:
cl_io_operations::cio_commit_async()
Definition at line 646 of file cl_io.c.
References cl_io_operations::cio_commit_async, cl_io_slice::cis_iop, cl_io_for_each, ENTRY, and RETURN.
Referenced by cl_echo_object_brw(), lov_io_commit_async(), vvp_io_fault_start(), and vvp_io_write_commit().
void cl_io_end (const struct lu_env * env, struct cl_io * io)
Wait until current io iteration is finished by calling cl_io_operations::cio_end() bottom-to-top.
Definition at line 593 of file cl_io.c.
References ci_state, ci_type, cl_io_operations::cio_end, CIS_IO_FINISHED, CIS_IO_GOING, cl_io_slice::cis_iop, cl_io_for_each_reverse, cl_io_invariant(), cl_io_is_loopable(), ENTRY, EXIT, LINVRNT, and cl_io_operations::op.
Referenced by cl_io_loop(), and lov_io_end_wrapper().
void cl_io_fini (const struct lu_env * env, struct cl_io * io)
Finalize io, by calling cl_io_operations::cio_fini() bottom-to-top.
Definition at line 103 of file cl_io.c.
References ci_ignore_layout, ci_layers, ci_need_restart, ci_state, ci_type, ci_verify_layout, cl_io_operations::cio_fini, CIS_FINI, cl_io_slice::cis_io, cl_io_slice::cis_iop, cl_io_slice::cis_linkage, CIT_DATA_VERSION, CIT_FAULT, CIT_FSYNC, CIT_LADVISE, CIT_MISC, CIT_READ, CIT_SETATTR, CIT_WRITE, cl_env_info(), cl_io_invariant(), cl_io_type_is_valid(), cl_thread_info::clt_current_io, ENTRY, ergo, EXIT, LASSERT, LBUG, LINVRNT, list_del_init(), list_empty(), cl_io_operations::op, and list_head::prev.
Referenced by cl_echo_object_brw(), cl_get_grouplock(), cl_glimpse_size0(), cl_put_grouplock(), cl_setattr_ost(), cl_sync_file_range(), do_bio_lustrebacked(), ll_data_version(), ll_fault0(), ll_fault_io_init(), ll_file_io_generic(), ll_ladvise(), ll_page_mkwrite0(), ll_writepage(), lov_io_sub_fini(), osc_extent_truncate(), osc_lock_weight(), and osc_lru_shrink().
int cl_io_init (const struct lu_env * env, struct cl_io * io, enum cl_io_type iot, struct cl_object * obj)
Initialize io, by calling cl_io_operations::cio_init() top-to-bottom.
Caller has to call cl_io_fini() after a call to cl_io_init(), no matter what the latter returned.
Precondition:
obj == cl_object_top(obj)
cl_io_type_is_valid(iot)
Postcondition:
cl_io_type_is_valid(io->ci_type) && io->ci_type == iot
Definition at line 211 of file cl_io.c.
References cl_env_info(), cl_io_init0(), cl_object_top(), cl_thread_info::clt_current_io, and LASSERT.
Referenced by cl_echo_object_brw(), cl_get_grouplock(), cl_glimpse_size0(), cl_io_rw_init(), cl_setattr_ost(), cl_sync_file_range(), do_bio_lustrebacked(), ll_data_version(), ll_fault_io_init(), ll_ladvise(), ll_writepage(), osc_extent_truncate(), osc_lock_weight(), and osc_lru_shrink().
static int cl_io_is_append (const struct cl_io * io) [inline, static]
True, iff io is an O_APPEND write(2).
Definition at line 2285 of file cl_object.h.
References ci_type, ci_wr, CIT_WRITE, and u.
Referenced by lov_io_rw_iter_init(), lov_io_slice_init(), lov_io_sub_inherit(), osc_io_write_iter_init(), osc_lock_set_writer(), and vvp_io_write_start().
int cl_io_is_going (const struct lu_env * env)
Returns true iff there is an IO ongoing in the given environment.
Definition at line 76 of file cl_io.c.
References cl_env_info(), and cl_thread_info::clt_current_io.
Referenced by cl_env_nested_get().
static int cl_io_is_mkwrite (const struct cl_io * io) [inline, static]
Definition at line 2295 of file cl_object.h.
References ci_fault, ci_type, CIT_FAULT, and u.
Referenced by osc_lock_init(), osc_lock_set_writer(), and vvp_io_write_commit().
static int cl_io_is_sync_write (const struct cl_io * io) [inline, static]
Definition at line 2290 of file cl_object.h.
References ci_type, ci_wr, CIT_WRITE, and u.
Referenced by lov_io_sub_inherit(), and osc_io_commit_async().
static int cl_io_is_trunc (const struct cl_io * io) [inline, static]
True, iff io is a truncate(2).
Definition at line 2303 of file cl_object.h.
References ci_setattr, ci_type, CIT_SETATTR, and u.
Referenced by lov_io_init_released(), lov_io_slice_init(), lov_io_sub_inherit(), osc_io_setattr_end(), osc_io_setattr_start(), osc_lock_to_lockless(), vvp_io_init(), vvp_io_setattr_end(), vvp_io_setattr_lock(), and vvp_io_setattr_start().
void cl_io_iter_fini (const struct lu_env * env, struct cl_io * io)
Finalizes io iteration.
Calls cl_io_operations::cio_iter_fini() bottom-to-top.
Definition at line 469 of file cl_io.c.
References ci_state, ci_type, cl_io_operations::cio_iter_fini, cl_io_slice::cis_iop, CIS_IT_ENDED, CIS_UNLOCKED, cl_io_for_each_reverse, cl_io_invariant(), cl_io_is_loopable(), ENTRY, EXIT, LINVRNT, and cl_io_operations::op.
Referenced by cl_io_loop(), lov_io_iter_fini_wrapper(), and lov_io_iter_init().
int cl_io_iter_init (const struct lu_env * env, struct cl_io * io)
Prepares next iteration of io.
Calls cl_io_operations::cio_iter_init() top-to-bottom. This exists to give layers a chance to modify io parameters, e.g., so that lov can restrict io to a single stripe.
Definition at line 439 of file cl_io.c.
References ci_state, ci_type, cl_io_operations::cio_iter_init, CIS_INIT, cl_io_slice::cis_iop, CIS_IT_ENDED, CIS_IT_STARTED, cl_io_for_each, cl_io_invariant(), cl_io_is_loopable(), ENTRY, LINVRNT, cl_io_operations::op, and RETURN.
Referenced by cl_io_loop(), and lov_io_iter_init().
int cl_io_lock (const struct lu_env * env, struct cl_io * io)
Takes locks necessary for the current iteration of io.
Calls cl_io_operations::cio_lock() top-to-bottom to collect locks required by layers for the current iteration. Then sort locks (to avoid dead-locks), and acquire them.
Definition at line 363 of file cl_io.c.
References ci_lockset, ci_state, ci_type, cl_io_operations::cio_lock, cl_io_slice::cis_iop, CIS_IT_STARTED, CIS_LOCKED, cl_io_for_each, cl_io_invariant(), cl_io_is_loopable(), cl_io_locks_sort(), cl_io_unlock(), cl_lockset_lock(), ENTRY, LINVRNT, cl_io_operations::op, and RETURN.
Referenced by cl_io_loop(), and lov_io_lock().
int cl_io_lock_add (const struct lu_env * env, struct cl_io * io, struct cl_io_lock_link * link)
Adds a lock to a lockset.
Definition at line 516 of file cl_io.c.
References ci_lockset, cl_io_lock_link::cill_linkage, cl_lockset_merge(), cl_lockset::cls_todo, ENTRY, list_add(), and RETURN.
Referenced by cl_io_lock_alloc_add(), and vvp_io_one_lock_index().
int cl_io_lock_alloc_add (const struct lu_env * env, struct cl_io * io, struct cl_lock_descr * descr)
Allocates new lock link, and uses it to add a lock to a lockset.
Definition at line 541 of file cl_io.c.
References cl_io_lock_link::cill_fini, cl_free_io_lock_link(), cl_io_lock_add(), ENTRY, OBD_ALLOC_PTR, and RETURN.
Referenced by vvp_mmap_locks().
int cl_io_loop (const struct lu_env * env, struct cl_io * io)
Main io loop.
Pumps io through iterations calling
cl_io_iter_init()
cl_io_lock()
cl_io_start()
cl_io_end()
cl_io_unlock()
cl_io_iter_fini()
repeatedly until there is no more io to do.
Definition at line 779 of file cl_io.c.
References ci_continue, ci_nob, ci_result, cl_io_end(), cl_io_is_loopable(), cl_io_iter_fini(), cl_io_iter_init(), cl_io_lock(), cl_io_rw_advance(), cl_io_start(), cl_io_unlock(), ENTRY, LINVRNT, and RETURN.
Referenced by cl_setattr_ost(), cl_sync_file_range(), ll_data_version(), ll_fault0(), ll_file_io_generic(), ll_ladvise(), and ll_page_mkwrite0().
void cl_io_print (const struct lu_env * env, void * cookie, lu_printer_t printer, const struct cl_io * io)
Prints human readable representation of io to the f.
Definition at line 1164 of file cl_io.c.
int cl_io_read_ahead (const struct lu_env * env, struct cl_io * io, pgoff_t start, struct cl_read_ahead * ra)
Called by read io, to decide the readahead extent.
See also:
cl_io_operations::cio_read_ahead()
Definition at line 617 of file cl_io.c.
References ci_state, ci_type, cl_io_operations::cio_read_ahead, CIS_IO_GOING, cl_io_slice::cis_iop, CIS_LOCKED, CIT_FAULT, CIT_READ, cl_io_for_each, cl_io_invariant(), ENTRY, LINVRNT, and RETURN.
Referenced by ll_read_ahead_pages(), and lov_io_read_ahead().
void cl_io_rw_advance (const struct lu_env * env, struct cl_io * io, size_t nob)
Records that read or write io progressed nob bytes forward.
Definition at line 490 of file cl_io.c.
References ci_rw, ci_type, cl_io_operations::cio_advance, cl_io_slice::cis_iop, CIT_READ, CIT_WRITE, cl_io_for_each_reverse, cl_io_invariant(), cl_io_is_loopable(), cl_io_rw_common::crw_count, cl_io_rw_common::crw_pos, ENTRY, EXIT, LINVRNT, cl_io_operations::op, and u.
Referenced by cl_io_loop().
int cl_io_rw_init (const struct lu_env * env, struct cl_io * io, enum cl_io_type iot, loff_t pos, size_t count)
Initialize read or write io.
Precondition:
iot == CIT_READ || iot == CIT_WRITE
Definition at line 229 of file cl_io.c.
References __u64, ci_obj, ci_rw, ci_wr, CIT_READ, CIT_WRITE, cl_io_init(), cl_object::co_lu, cl_io_rw_common::crw_count, cl_io_rw_common::crw_nonblock, cl_io_rw_common::crw_pos, D_VFSTRACE, ENTRY, LINVRNT, LPU64, LU_OBJECT_HEADER, RETURN, and u.
Referenced by ll_file_io_generic().
int cl_io_start (const struct lu_env * env, struct cl_io * io)
Starts io by calling cl_io_operations::cio_start() top-to-bottom.
Definition at line 565 of file cl_io.c.
References ci_state, ci_type, cl_io_operations::cio_start, CIS_IO_GOING, cl_io_slice::cis_iop, CIS_LOCKED, cl_io_for_each, cl_io_invariant(), cl_io_is_loopable(), ENTRY, LINVRNT, cl_io_operations::op, and RETURN.
Referenced by cl_io_loop(), and lov_io_start().
int cl_io_sub_init (const struct lu_env * env, struct cl_io * io, enum cl_io_type iot, struct cl_object * obj)
Initialize sub-io, by calling cl_io_operations::cio_init() top-to-bottom.
Precondition:
obj != cl_object_top(obj)
Definition at line 189 of file cl_io.c.
References cl_env_info(), cl_io_init0(), cl_object_top(), cl_thread_info::clt_current_io, and LASSERT.
Referenced by lov_io_sub_init().
int cl_io_submit_rw (const struct lu_env * env, struct cl_io * io, enum cl_req_type crt, struct cl_2queue * queue)
Submits a list of pages for immediate io.
After the function gets returned, The submitted pages are moved to queue->c2_qout queue, and queue->c2_qin contain both the pages don't need to be submitted, and the pages are errant to submit.
Returns:
0 if at least one page was submitted, error code otherwise.
See also:
cl_io_operations::cio_submit()
Definition at line 676 of file cl_io.c.
References cl_2queue::c2_qout, cl_io_operations::cio_submit, cl_io_slice::cis_iop, cl_io_for_each, ENTRY, ergo, LASSERT, list_empty(), cl_page_list::pl_pages, and RETURN.
Referenced by cl_io_submit_sync(), ll_io_read_page(), and lov_io_submit().
int cl_io_submit_sync (const struct lu_env * env, struct cl_io * io, enum cl_req_type iot, struct cl_2queue * queue, long timeout)
Submit a sync_io and wait for the IO to be finished, or error happens.
If timeout is zero, it means to wait for the IO unconditionally.
Definition at line 702 of file cl_io.c.
References cl_2queue::c2_qin, cl_2queue::c2_qout, cl_env_info(), cl_io_submit_rw(), cl_page_list_assume(), cl_page_list_for_each, cl_sync_io_end(), cl_sync_io_init(), cl_sync_io_note(), cl_sync_io_wait(), cl_thread_info::clt_anchor, cl_page::cp_sync_io, LASSERT, list_empty(), cl_page_list::pl_nr, and cl_page_list::pl_pages.
Referenced by cl_echo_object_brw(), ll_direct_rw_pages(), ll_page_sync_io(), and vvp_io_commit_sync().
struct cl_io* cl_io_top (struct cl_io * io) [read]
Returns top-level io.
See also:
cl_object_top()
Definition at line 1152 of file cl_io.c.
References ci_parent, ENTRY, and RETURN.
Referenced by cl_page_assume(), cl_page_disown(), cl_page_is_owned(), cl_page_own0(), cl_page_unassume(), and write_commit_callback().
void cl_io_unlock (const struct lu_env * env, struct cl_io * io)
Release locks takes by io.
Definition at line 395 of file cl_io.c.
References ci_lockset, ci_state, ci_type, cl_io_lock_link::cill_fini, cl_io_lock_link::cill_linkage, cl_io_lock_link::cill_lock, cl_io_operations::cio_unlock, cl_io_slice::cis_iop, CIS_UNLOCKED, cl_env_info(), cl_io_for_each_reverse, cl_io_invariant(), cl_io_is_loopable(), cl_lock_release(), CNL_TOP, ENTRY, EXIT, LASSERT, LINVRNT, list_del_init(), list_for_each_entry_safe, and cl_io_operations::op.
Referenced by cl_io_lock(), cl_io_loop(), and lov_io_unlock_wrapper().
static void cl_read_ahead_release (const struct lu_env * env, struct cl_read_ahead * ra) [inline, static]
Definition at line 1468 of file cl_object.h.
References cl_read_ahead::cra_cbdata, and cl_read_ahead::cra_release.
Referenced by ll_read_ahead_pages().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.