Lustre: libiam
libiam
Data Structures
struct iam_uapi_info
Defines
#define DX_FMT_NAME_LEN 16
Enumerations
enum iam_fmt_t { FMT_LFIX, FMT_LVAR, FMT_LFIX, FMT_LVAR }
Functions
int iam_creat (char *filename, enum iam_fmt_t fmt, int blocksize, int keysize, int recsize, int ptrsize)
int iam_open (char *filename, struct iam_uapi_info *ua)
int iam_close (int fd)
int iam_insert (int fd, struct iam_uapi_info *ua, int key_need_convert, char *keybuf, int rec_need_convert, char *recbuf)
int iam_lookup (int fd, struct iam_uapi_info *ua, int key_need_convert, char *key_buf, int *keysize, char *save_key, int rec_need_convert, char *rec_buf, int *recsize, char *save_rec)
int iam_delete (int fd, struct iam_uapi_info *ua, int key_need_convert, char *keybuf, int rec_need_convert, char *recbuf)
int iam_it_start (int fd, struct iam_uapi_info *ua, int key_need_convert, char *key_buf, int *keysize, char *save_key, int rec_need_convert, char *rec_buf, int *recsize, char *save_rec)
int iam_it_next (int fd, struct iam_uapi_info *ua, int key_need_convert, char *key_buf, int *keysize, char *save_key, int rec_need_convert, char *rec_buf, int *recsize, char *save_rec)
int iam_it_stop (int fd, struct iam_uapi_info *ua, int key_need_convert, char *keybuf, int rec_need_convert, char *recbuf)
int iam_polymorph (char *filename, unsigned long mode)
Define Documentation
#define DX_FMT_NAME_LEN 16
Definition at line 56 of file libiam.h.
Enumeration Type Documentation
enum iam_fmt_t
Enumerator:
FMT_LFIX
FMT_LVAR
FMT_LFIX
FMT_LVAR
Definition at line 58 of file libiam.h.
Function Documentation
int iam_close (int fd)
Definition at line 523 of file libiam.c.
int iam_creat (char * filename, enum iam_fmt_t fmt, int blocksize, int keysize, int recsize, int ptrsize)
Definition at line 402 of file libiam.c.
References buf, FMT_LFIX, FMT_LVAR, lfix_leaf(), lfix_root(), lvar_leaf(), and lvar_root().
int iam_delete (int fd, struct iam_uapi_info * ua, int key_need_convert, char * keybuf, int rec_need_convert, char * recbuf)
Definition at line 557 of file libiam.c.
References iam_doop(), and IAM_IOC_DELETE.
Referenced by osd_index_iam_delete(), and osd_oi_iam_delete().
int iam_insert (int fd, struct iam_uapi_info * ua, int key_need_convert, char * keybuf, int rec_need_convert, char * recbuf)
Definition at line 531 of file libiam.c.
References iam_doop(), and IAM_IOC_INSERT.
Referenced by osd_index_iam_insert(), and osd_oi_iam_refresh().
int iam_it_next (int fd, struct iam_uapi_info * ua, int key_need_convert, char * key_buf, int * keysize, char * save_key, int rec_need_convert, char * rec_buf, int * recsize, char * save_rec)
Definition at line 583 of file libiam.c.
References iam_doop(), and IAM_IOC_IT_NEXT.
Referenced by iam_it_collision(), iam_it_get_at(), iam_it_rec_delete(), and osd_it_iam_next().
int iam_it_start (int fd, struct iam_uapi_info * ua, int key_need_convert, char * key_buf, int * keysize, char * save_key, int rec_need_convert, char * rec_buf, int * recsize, char * save_rec)
Definition at line 569 of file libiam.c.
References iam_doop(), and IAM_IOC_IT_START.
int iam_it_stop (int fd, struct iam_uapi_info * ua, int key_need_convert, char * keybuf, int rec_need_convert, char * recbuf)
Definition at line 597 of file libiam.c.
References iam_doop(), and IAM_IOC_IT_STOP.
int iam_lookup (int fd, struct iam_uapi_info * ua, int key_need_convert, char * key_buf, int * keysize, char * save_key, int rec_need_convert, char * rec_buf, int * recsize, char * save_rec)
Definition at line 543 of file libiam.c.
References iam_doop(), and IAM_IOC_LOOKUP.
int iam_open (char * filename, struct iam_uapi_info * ua)
Definition at line 488 of file libiam.c.
References IAM_IOC_GETINFO, and IAM_IOC_INIT.
int iam_polymorph (char * filename, unsigned long mode)
Definition at line 609 of file libiam.c.
References IAM_IOC_POLYMORPH, and ret.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.