Lustre: Binary heap
Binary heap
The binary heap is a scalable data structure created using a binary tree.
Data Structures
struct cfs_binheap_node
Binary heap node.
struct cfs_binheap_ops
Binary heap operations.
struct cfs_binheap
Binary heap object.
Defines
#define CBH_SHIFT 9
#define CBH_SIZE (1 << CBH_SHIFT)
#define CBH_MASK (CBH_SIZE - 1)
#define CBH_NOB (CBH_SIZE * sizeof(struct cfs_binheap_node *))
#define CBH_POISON 0xdeadbeef
#define DEBUG_SUBSYSTEM S_LNET
#define CBH_ALLOC(ptr, h)
#define CBH_FREE(ptr) LIBCFS_FREE(ptr, CBH_NOB)
Enumerations
enum { CBH_FLAG_ATOMIC_GROW = 1 }
Binary heap flags.
Functions
void cfs_binheap_destroy (struct cfs_binheap *h)
Releases all resources associated with a binary heap instance.
struct cfs_binheap * cfs_binheap_create (struct cfs_binheap_ops *ops, unsigned int flags, unsigned count, void *arg, struct cfs_cpt_table *cptab, int cptid)
Creates and initializes a binary heap instance.
struct cfs_binheap_node * cfs_binheap_find (struct cfs_binheap *h, unsigned int idx)
Obtains a pointer to a heap element, given its index into the binary tree.
int cfs_binheap_insert (struct cfs_binheap *h, struct cfs_binheap_node *e)
Sort-inserts a node into the binary heap.
void cfs_binheap_remove (struct cfs_binheap *h, struct cfs_binheap_node *e)
Removes a node from the binary heap.
void cfs_binheap_relocate (struct cfs_binheap *h, struct cfs_binheap_node *e)
Relocate a node in the binary heap.
static int cfs_binheap_size (struct cfs_binheap *h)
static int cfs_binheap_is_empty (struct cfs_binheap *h)
static struct cfs_binheap_node * cfs_binheap_root (struct cfs_binheap *h)
static struct cfs_binheap_node * cfs_binheap_remove_root (struct cfs_binheap *h)
static int cfs_binheap_grow (struct cfs_binheap *h)
Grows the capacity of a binary heap so that it can handle a larger number of struct cfs_binheap_node objects.
static struct cfs_binheap_node ** cfs_binheap_pointer (struct cfs_binheap *h, unsigned int idx)
Obtains a double pointer to a heap element, given its index into the binary tree.
static int cfs_binheap_bubble (struct cfs_binheap *h, struct cfs_binheap_node *e)
Moves a node upwards, towards the root of the binary tree.
static int cfs_binheap_sink (struct cfs_binheap *h, struct cfs_binheap_node *e)
Moves a node downwards, towards the last level of the binary tree.
Detailed Description
The binary heap is a scalable data structure created using a binary tree.
It is capable of maintaining large sets of elements sorted usually by one or more element properties, but really based on anything that can be used as a binary predicate in order to determine the relevant ordering of any two nodes that belong to the set. There is no search operation, rather the intention is for the element of the lowest priority which will always be at the root of the tree (as this is an implementation of a min-heap) to be removed by users for consumption.
Users of the heap should embed a struct cfs_binheap_node object instance on every object of the set that they wish the binary heap instance to handle, and (at a minimum) provide a struct cfs_binheap_ops::hop_compare() implementation which is used by the heap as the binary predicate during its internal sorting operations.
The current implementation enforces no locking scheme, and so assumes the user caters for locking between calls to insert, delete and lookup operations. Since the only consumer for the data structure at this point are NRS policies, and these operate on a per-CPT basis, binary heap instances are tied to a specific CPT.
Define Documentation
#define CBH_ALLOC (ptr, h)
Value:
do {                                                                    \
        if (h->cbh_cptab) {                                             \
                if ((h)->cbh_flags & CBH_FLAG_ATOMIC_GROW)              \
                        LIBCFS_CPT_ALLOC_GFP((ptr), h->cbh_cptab,       \
                                             h->cbh_cptid, CBH_NOB,     \
                                             GFP_ATOMIC);               \
                else                                                    \
                        LIBCFS_CPT_ALLOC((ptr), h->cbh_cptab,           \
                                         h->cbh_cptid, CBH_NOB);        \
        } else {                                                        \
                if ((h)->cbh_flags & CBH_FLAG_ATOMIC_GROW)              \
                        LIBCFS_ALLOC_ATOMIC((ptr), CBH_NOB);            \
                else                                                    \
                        LIBCFS_ALLOC((ptr), CBH_NOB);                   \
        }                                                               \
} while (0)
Definition at line 40 of file heap.c.
Referenced by cfs_binheap_grow().
#define CBH_FREE (ptr) LIBCFS_FREE(ptr, CBH_NOB)
Definition at line 58 of file heap.c.
Referenced by cfs_binheap_destroy(), and cfs_binheap_grow().
#define CBH_MASK (CBH_SIZE - 1)
Definition at line 73 of file libcfs_heap.h.
Referenced by cfs_binheap_grow(), and cfs_binheap_pointer().
#define CBH_NOB (CBH_SIZE * sizeof(struct cfs_binheap_node *))
Definition at line 74 of file libcfs_heap.h.
#define CBH_POISON 0xdeadbeef
Definition at line 76 of file libcfs_heap.h.
Referenced by cfs_binheap_remove().
#define CBH_SHIFT 9
Definition at line 71 of file libcfs_heap.h.
Referenced by cfs_binheap_grow(), and cfs_binheap_pointer().
#define CBH_SIZE (1 << CBH_SHIFT)
Definition at line 72 of file libcfs_heap.h.
Referenced by cfs_binheap_destroy(), cfs_binheap_grow(), and cfs_binheap_pointer().
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 36 of file heap.c.
Enumeration Type Documentation
anonymous enum
Binary heap flags.
Enumerator:
CBH_FLAG_ATOMIC_GROW
Definition at line 81 of file libcfs_heap.h.
Function Documentation
static int cfs_binheap_bubble (struct cfs_binheap * h, struct cfs_binheap_node * e) [static]
Moves a node upwards, towards the root of the binary tree.
Parameters:
[in] h The heap
[in] e The node
Return values:
1 The position of e in the tree was changed at least once
0 The position of e in the tree was not changed
Definition at line 311 of file heap.c.
References cfs_binheap::cbh_ops, cfs_binheap_pointer(), cfs_binheap_node::chn_index, cfs_binheap_ops::hop_compare, and LASSERT.
Referenced by cfs_binheap_insert(), and cfs_binheap_relocate().
struct cfs_binheap * cfs_binheap_create (struct cfs_binheap_ops * ops, unsigned int flags, unsigned count, void * arg, struct cfs_cpt_table * cptab, int cptid) [read]
Creates and initializes a binary heap instance.
Parameters:
[in] ops The operations to be used
[in] flags The heap flags [in] count The initial heap capacity in # of elements
[in] arg An optional private argument
[in] cptab The CPT table this heap instance will operate over
[in] cptid The CPT id of cptab this heap instance will operate over
Return values:
valid-pointer A newly-created and initialized binary heap object
NULL error
Definition at line 167 of file heap.c.
References cfs_binheap::cbh_cptab, cfs_binheap::cbh_cptid, CBH_FLAG_ATOMIC_GROW, cfs_binheap::cbh_flags, cfs_binheap::cbh_hwm, cfs_binheap::cbh_nelements, cfs_binheap::cbh_ops, cfs_binheap::cbh_private, cfs_binheap_destroy(), cfs_binheap_grow(), CFS_CPT_ANY, cfs_binheap_ops::hop_compare, LASSERT, LIBCFS_ALLOC, and LIBCFS_CPT_ALLOC.
void cfs_binheap_destroy (struct cfs_binheap * h)
Releases all resources associated with a binary heap instance.
Deallocates memory for all indirection levels and the binary heap object itself.
Parameters:
[in] h The binary heap object
Definition at line 215 of file heap.c.
References cfs_binheap::cbh_elements1, cfs_binheap::cbh_elements2, cfs_binheap::cbh_elements3, CBH_FREE, cfs_binheap::cbh_hwm, CBH_SIZE, LASSERT, and LIBCFS_FREE.
Referenced by cfs_binheap_create().
struct cfs_binheap_node * cfs_binheap_find (struct cfs_binheap * h, unsigned int idx) [read]
Obtains a pointer to a heap element, given its index into the binary tree.
Parameters:
[in] h The binary heap
[in] idx The requested node's index
Return values:
valid-pointer The requested heap node
NULL Supplied index is out of bounds
Definition at line 292 of file heap.c.
References cfs_binheap::cbh_nelements, and cfs_binheap_pointer().
Referenced by cfs_binheap_remove_root(), and cfs_binheap_root().
static int cfs_binheap_grow (struct cfs_binheap * h) [static]
Grows the capacity of a binary heap so that it can handle a larger number of struct cfs_binheap_node objects.
Parameters:
[in] h The binary heap
Return values:
0 Successfully grew the heap
-ENOMEM OOM error
Definition at line 70 of file heap.c.
References CBH_ALLOC, cfs_binheap::cbh_elements1, cfs_binheap::cbh_elements2, cfs_binheap::cbh_elements3, CBH_FREE, cfs_binheap::cbh_hwm, CBH_MASK, CBH_SHIFT, CBH_SIZE, and LASSERT.
Referenced by cfs_binheap_create(), and cfs_binheap_insert().
int cfs_binheap_insert (struct cfs_binheap * h, struct cfs_binheap_node * e)
Sort-inserts a node into the binary heap.
Parameters:
[in] h The heap
[in] e The node
Return values:
0 Element inserted successfully
!= 0 error
Definition at line 419 of file heap.c.
References cfs_binheap::cbh_hwm, cfs_binheap::cbh_nelements, cfs_binheap::cbh_ops, cfs_binheap_bubble(), cfs_binheap_grow(), cfs_binheap_pointer(), cfs_binheap_node::chn_index, and cfs_binheap_ops::hop_enter.
static int cfs_binheap_is_empty (struct cfs_binheap * h) [inline, static]
Definition at line 180 of file libcfs_heap.h.
References cfs_binheap::cbh_nelements.
static struct cfs_binheap_node** cfs_binheap_pointer (struct cfs_binheap * h, unsigned int idx) [static, read]
Obtains a double pointer to a heap element, given its index into the binary tree.
Parameters:
[in] h The binary heap instance
[in] idx The requested node's index
Return values:
valid-pointer A double pointer to a heap pointer entry
Definition at line 267 of file heap.c.
References cfs_binheap::cbh_elements1, cfs_binheap::cbh_elements2, cfs_binheap::cbh_elements3, CBH_MASK, CBH_SHIFT, and CBH_SIZE.
Referenced by cfs_binheap_bubble(), cfs_binheap_find(), cfs_binheap_insert(), cfs_binheap_remove(), and cfs_binheap_sink().
void cfs_binheap_relocate (struct cfs_binheap * h, struct cfs_binheap_node * e)
Relocate a node in the binary heap.
Should be called whenever a node's values which affects its ranking are changed.
Parameters:
[in] h The heap
[in] e The node
Definition at line 493 of file heap.c.
References cfs_binheap_bubble(), and cfs_binheap_sink().
Referenced by cfs_binheap_remove().
void cfs_binheap_remove (struct cfs_binheap * h, struct cfs_binheap_node * e)
Removes a node from the binary heap.
Parameters:
[in] h The heap
[in] e The node
Definition at line 455 of file heap.c.
References cfs_binheap::cbh_nelements, cfs_binheap::cbh_ops, CBH_POISON, cfs_binheap_pointer(), cfs_binheap_relocate(), cfs_binheap_node::chn_index, cfs_binheap_ops::hop_exit, and LASSERT.
Referenced by cfs_binheap_remove_root().
static struct cfs_binheap_node* cfs_binheap_remove_root (struct cfs_binheap * h) [static, read]
Definition at line 192 of file libcfs_heap.h.
References cfs_binheap_find(), and cfs_binheap_remove().
static struct cfs_binheap_node* cfs_binheap_root (struct cfs_binheap * h) [static, read]
Definition at line 186 of file libcfs_heap.h.
References cfs_binheap_find().
static int cfs_binheap_sink (struct cfs_binheap * h, struct cfs_binheap_node * e) [static]
Moves a node downwards, towards the last level of the binary tree.
Parameters:
[in] h The heap
[in] e The node
Return values:
1 The position of e in the tree was changed at least once
0 The position of e in the tree was not changed
Definition at line 354 of file heap.c.
References cfs_binheap::cbh_nelements, cfs_binheap::cbh_ops, cfs_binheap_pointer(), cfs_binheap_node::chn_index, cfs_binheap_ops::hop_compare, and LASSERT.
Referenced by cfs_binheap_relocate().
static int cfs_binheap_size (struct cfs_binheap * h) [inline, static]
Definition at line 174 of file libcfs_heap.h.
References cfs_binheap::cbh_nelements.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.