Lustre: net
net
[Portal RPC and networking module.]
Data Structures
struct ptlrpc_replay_async_args
struct ptlrpc_connection
Structure to single define portal connection.
struct ptlrpc_client
Client definition for PortalRPC.
union ptlrpc_async_args
struct ptlrpc_request_set
Definition of request set structure.
struct ptlrpc_set_cbdata
Description of a single ptrlrpc_set callback.
struct ptlrpc_cb_id
ptlrpc callback & work item stuff
struct ptlrpc_reply_state
Structure to define reply state on the server Reply state holds various reply message information.
struct ptlrpc_request_pool
Definition of request pool structure.
struct ptlrpc_hpreq_ops
Basic request prioritization operations structure.
struct ptlrpc_cli_req
struct ptlrpc_srv_req
struct ptlrpc_request
Represents remote procedure call.
struct ptlrpc_bulk_page
Structure that defines a single page of a bulk transfer.
struct ptlrpc_bulk_frag_ops
struct ptlrpc_bulk_desc
struct ptlrpc_thread
Definition of server service thread structure.
struct ptlrpc_request_buffer_desc
Request buffer descriptor structure.
struct ptlrpc_service_ops
struct ptlrpc_service
Definition of PortalRPC service.
struct ptlrpc_service_part
Definition of PortalRPC service partition data.
struct ptlrpcd_ctl
Declaration of ptlrpcd control structure.
struct ptlrpc_service_buf_conf
struct ptlrpc_service_thr_conf
struct ptlrpc_service_cpt_conf
struct ptlrpc_service_conf
Modules
Network Request Scheduler
Service compatibility function; the policy is compatible with all services.
Defines
#define PTLRPC_MD_OPTIONS 0
#define PTLRPC_BULK_OPS_BITS 4
log2 max # of bulk operations in one request: 2=4MB/RPC, 5=32MB/RPC, .
#define PTLRPC_BULK_OPS_COUNT (1U << PTLRPC_BULK_OPS_BITS)
#define PTLRPC_BULK_OPS_MASK (~((__u64)PTLRPC_BULK_OPS_COUNT - 1))
PTLRPC_BULK_OPS_MASK is for the convenience of the client only, and should not be used on the server at all.
#define PTLRPC_MAX_BRW_BITS (LNET_MTU_BITS + PTLRPC_BULK_OPS_BITS)
Define maxima for bulk I/O.
#define PTLRPC_MAX_BRW_SIZE (1 << PTLRPC_MAX_BRW_BITS)
#define PTLRPC_MAX_BRW_PAGES (PTLRPC_MAX_BRW_SIZE >> PAGE_CACHE_SHIFT)
#define ONE_MB_BRW_SIZE (1 << LNET_MTU_BITS)
#define MD_MAX_BRW_SIZE (1 << LNET_MTU_BITS)
#define MD_MAX_BRW_PAGES (MD_MAX_BRW_SIZE >> PAGE_CACHE_SHIFT)
#define DT_MAX_BRW_SIZE PTLRPC_MAX_BRW_SIZE
#define DT_MAX_BRW_PAGES (DT_MAX_BRW_SIZE >> PAGE_CACHE_SHIFT)
#define OFD_MAX_BRW_SIZE (1 << LNET_MTU_BITS)
#define PTLRPC_NTHRS_INIT 2
#define LDLM_THR_FACTOR 8
Buffer Constants.
#define LDLM_NTHRS_INIT PTLRPC_NTHRS_INIT
#define LDLM_NTHRS_BASE 24
#define LDLM_NTHRS_MAX (num_online_cpus() == 1 ? 64 : 128)
#define LDLM_BL_THREADS LDLM_NTHRS_AUTO_INIT
#define LDLM_CLIENT_NBUFS 1
#define LDLM_SERVER_NBUFS 64
#define LDLM_BUFSIZE (8 * 1024)
#define LDLM_MAXREQSIZE (5 * 1024)
#define LDLM_MAXREPSIZE (1024)
#define MDS_MAX_THREADS 1024
#define MDS_MAX_OTHR_THREADS 256
#define MDS_THR_FACTOR 8
#define MDS_NTHRS_INIT PTLRPC_NTHRS_INIT
#define MDS_NTHRS_MAX MDS_MAX_THREADS
#define MDS_NTHRS_BASE min(64, MDS_NTHRS_MAX)
#define MDS_RDPG_THR_FACTOR 4
#define MDS_RDPG_NTHRS_INIT PTLRPC_NTHRS_INIT
#define MDS_RDPG_NTHRS_MAX MDS_MAX_OTHR_THREADS
#define MDS_RDPG_NTHRS_BASE min(48, MDS_RDPG_NTHRS_MAX)
#define MDS_SETA_THR_FACTOR 4
#define MDS_SETA_NTHRS_INIT PTLRPC_NTHRS_INIT
#define MDS_SETA_NTHRS_MAX MDS_MAX_OTHR_THREADS
#define MDS_SETA_NTHRS_BASE min(48, MDS_SETA_NTHRS_MAX)
#define MDS_OTHR_NTHRS_INIT PTLRPC_NTHRS_INIT
#define MDS_OTHR_NTHRS_MAX MDS_MAX_OTHR_THREADS
#define MDS_NBUFS 64
#define MDS_MAXREQSIZE (5 * 1024)
Assume file name length = FNAME_MAX = 256 (true for ext3).
#define MDS_MAXREPSIZE (9 * 1024)
#define MDS_LOV_MAXREQSIZE
MDS incoming request with LOV EA 24 = sizeof(struct lov_ost_data), i.e: replay of opencreate.
#define MDS_LOV_MAXREPSIZE MDS_LOV_MAXREQSIZE
MDS outgoing reply with LOV EA.
#define MDS_EA_MAXREQSIZE 66288
This is the size of a maximum REINT_SETXATTR request:.
#define MDS_REG_MAXREQSIZE
These are the maximum request and reply sizes (rounded up to 1 KB boundaries) for the "regular" MDS_REQUEST_PORTAL and MDS_REPLY_PORTAL.
#define MDS_REG_MAXREPSIZE MDS_REG_MAXREQSIZE
#define OUT_MAXREQSIZE (1000 * 1024)
The update request includes all of updates from the create, which might include linkea (4K maxim), together with other updates, we set it to 1000K: lustre_msg + ptlrpc_body + OUT_UPDATE_BUFFER_SIZE_MAX.
#define OUT_MAXREPSIZE MDS_MAXREPSIZE
#define MDS_BUFSIZE
MDS_BUFSIZE = max_reqsize (w/o LOV EA) + max sptlrpc payload size.
#define MDS_REG_BUFSIZE
MDS_REG_BUFSIZE should at least be MDS_REG_MAXREQSIZE + SPTLRPC_MAX_PAYLOAD.
#define OUT_BUFSIZE
OUT_BUFSIZE = max_out_reqsize + max sptlrpc payload (~1K) which is about 10K, for the same reason as MDS_REG_BUFSIZE, we also give some extra bytes to each request buffer to improve buffer utilization rate.
#define FLD_MAXREQSIZE (160)
FLD_MAXREQSIZE == lustre_msg + __u32 padding + ptlrpc_body + opc.
#define FLD_MAXREPSIZE (152)
FLD_MAXREPSIZE == lustre_msg + ptlrpc_body.
#define FLD_BUFSIZE (1 << 12)
#define SEQ_MAXREQSIZE (160)
SEQ_MAXREQSIZE == lustre_msg + __u32 padding + ptlrpc_body + opc + lu_range + __u32 padding.
#define SEQ_MAXREPSIZE (152)
SEQ_MAXREPSIZE == lustre_msg + ptlrpc_body + lu_range.
#define SEQ_BUFSIZE (1 << 12)
#define MGS_NTHRS_INIT (PTLRPC_NTHRS_INIT + 1)
MGS threads must be >= 3, see bug 22458 comment #28.
#define MGS_NTHRS_MAX 32
#define MGS_NBUFS 64
#define MGS_BUFSIZE (8 * 1024)
#define MGS_MAXREQSIZE (7 * 1024)
#define MGS_MAXREPSIZE (9 * 1024)
#define OSS_THR_FACTOR
#define OSS_NTHRS_INIT (PTLRPC_NTHRS_INIT + 1)
#define OSS_NTHRS_BASE 64
#define OSS_CR_THR_FACTOR 1
#define OSS_CR_NTHRS_INIT PTLRPC_NTHRS_INIT
#define OSS_CR_NTHRS_BASE 8
#define OSS_CR_NTHRS_MAX 64
#define _OST_MAXREQSIZE_SUM
OST_IO_MAXREQSIZE ~= lustre_msg + ptlrpc_body + obdo + obd_ioobj + DT_MAX_BRW_PAGES * niobuf_remote.
#define OST_MAXREQSIZE (16 * 1024)
FIEMAP request can be 4K+ for now.
#define OST_IO_MAXREQSIZE
#define OST_MAXREPSIZE (9 * 1024)
#define OST_IO_MAXREPSIZE OST_MAXREPSIZE
#define OST_NBUFS 64
#define OST_BUFSIZE max_t(int, OST_MAXREQSIZE + 1024, 16 * 1024)
OST_BUFSIZE = max_reqsize + max sptlrpc payload size.
#define OST_IO_BUFSIZE max_t(int, OST_IO_MAXREQSIZE + 1024, 64 * 1024)
OST_IO_MAXREQSIZE is 18K, giving extra 46K can increase buffer utilization rate of request buffer, please check comment of MDS_LOV_BUFSIZE for details.
#define ptlrpc_req_async_args(req) ((void *)&req->rq_async_args)
#define PTL_RPC_FL_INTR (1 << 0)
state flags of requests
#define PTL_RPC_FL_TIMEOUT (1 << 7)
#define REQ_MAX_ACK_LOCKS 8
#define RS_MAX_LOCKS 8
Maximum number of locks to fit into reply state.
#define RS_DEBUG 0
#define rq_bulk rq_cli.cr_bulk
client request member alias
#define rq_delay_limit rq_cli.cr_delay_limit
#define rq_queued_time rq_cli.cr_queued_time
#define rq_sent_tv rq_cli.cr_sent_tv
#define rq_real_sent rq_cli.cr_sent_out
#define rq_reply_deadline rq_cli.cr_reply_deadline
#define rq_bulk_deadline rq_cli.cr_bulk_deadline
#define rq_nr_resend rq_cli.cr_resend_nr
#define rq_request_portal rq_cli.cr_req_ptl
#define rq_reply_portal rq_cli.cr_rep_ptl
#define rq_import_generation rq_cli.cr_imp_gen
#define rq_send_state rq_cli.cr_send_state
#define rq_set_chain rq_cli.cr_set_chain
#define rq_ctx_chain rq_cli.cr_ctx_chain
#define rq_set rq_cli.cr_set
#define rq_set_waitq rq_cli.cr_set_waitq
#define rq_cli_ctx rq_cli.cr_cli_ctx
#define rq_req_md_h rq_cli.cr_req_md_h
#define rq_req_cbid rq_cli.cr_req_cbid
#define rq_reply_md_h rq_cli.cr_reply_md_h
#define rq_reply_waitq rq_cli.cr_reply_waitq
#define rq_reply_cbid rq_cli.cr_reply_cbid
#define rq_interpret_reply rq_cli.cr_reply_interp
#define rq_resend_cb rq_cli.cr_resend_cb
#define rq_async_args rq_cli.cr_async_args
#define rq_cb_data rq_cli.cr_cb_data
#define rq_unreplied_list rq_cli.cr_unreplied_list
#define rq_commit_cb rq_cli.cr_commit_cb
#define rq_replay_cb rq_cli.cr_replay_cb
#define rq_svc_thread rq_srv.sr_svc_thread
server request member alias
#define rq_timed_list rq_srv.sr_timed_list
#define rq_exp_list rq_srv.sr_exp_list
#define rq_history_list rq_srv.sr_hist_list
#define rq_history_seq rq_srv.sr_hist_seq
#define rq_at_index rq_srv.sr_at_index
#define rq_auth_uid rq_srv.sr_auth_uid
#define rq_auth_mapped_uid rq_srv.sr_auth_mapped_uid
#define rq_sp_from rq_srv.sr_sp_from
#define rq_session rq_srv.sr_ses
#define rq_nrq rq_srv.sr_nrq
#define rq_arrival_time rq_srv.sr_arrival_time
#define rq_reply_state rq_srv.sr_reply_state
#define rq_svc_ctx rq_srv.sr_svc_ctx
#define rq_user_desc rq_srv.sr_user_desc
#define rq_ops rq_srv.sr_ops
#define rq_rqbd rq_srv.sr_rqbd
#define GET_KIOV(desc) ((desc)->bd_u.bd_kiov.bd_vec)
#define BD_GET_KIOV(desc, i) ((desc)->bd_u.bd_kiov.bd_vec[i])
#define GET_ENC_KIOV(desc) ((desc)->bd_u.bd_kiov.bd_enc_vec)
#define BD_GET_ENC_KIOV(desc, i) ((desc)->bd_u.bd_kiov.bd_enc_vec[i])
#define GET_KVEC(desc) ((desc)->bd_u.bd_kvec.bd_kvec)
#define BD_GET_KVEC(desc, i) ((desc)->bd_u.bd_kvec.bd_kvec[i])
#define GET_ENC_KVEC(desc) ((desc)->bd_u.bd_kvec.bd_enc_kvec)
#define BD_GET_ENC_KVEC(desc, i) ((desc)->bd_u.bd_kvec.bd_enc_kvec[i])
#define PTLRPC_THR_NAME_LEN 32
#define PTLRPC_SVC_HP_RATIO 10
How many high priority requests to serve before serving one normal priority request.
#define ptlrpc_service_for_each_part(part, i, svc)
Typedefs
typedef int(* set_interpreter_func)(struct ptlrpc_request_set *, void *, int)
typedef int(* set_producer_func)(struct ptlrpc_request_set *, void *)
typedef int(* ptlrpc_interpterer_t)(const struct lu_env *env, struct ptlrpc_request *req, void *arg, int rc)
Type of request interpreter call-back.
typedef void(* ptlrpc_resend_cb_t)(struct ptlrpc_request *req, void *arg)
Type of request resend call-back.
typedef int(* svc_handler_t)(struct ptlrpc_request *req)
Enumerations
enum rq_phase {
RQ_PHASE_NEW = 0xebc0de00, RQ_PHASE_RPC = 0xebc0de01, RQ_PHASE_BULK = 0xebc0de02, RQ_PHASE_INTERPRET = 0xebc0de03,
RQ_PHASE_COMPLETE = 0xebc0de04, RQ_PHASE_UNREGISTERING = 0xebc0de05, RQ_PHASE_UNDEFINED = 0xebc0de06
}
RPC stages.
enum ptlrpc_bulk_op_type {
PTLRPC_BULK_OP_ACTIVE = 0x00000001, PTLRPC_BULK_OP_PASSIVE = 0x00000002, PTLRPC_BULK_OP_PUT = 0x00000004, PTLRPC_BULK_OP_GET = 0x00000008,
PTLRPC_BULK_BUF_KVEC = 0x00000010, PTLRPC_BULK_BUF_KIOV = 0x00000020, PTLRPC_BULK_GET_SOURCE = PTLRPC_BULK_OP_PASSIVE | PTLRPC_BULK_OP_GET, PTLRPC_BULK_PUT_SINK = PTLRPC_BULK_OP_PASSIVE | PTLRPC_BULK_OP_PUT,
PTLRPC_BULK_GET_SINK = PTLRPC_BULK_OP_ACTIVE | PTLRPC_BULK_OP_GET, PTLRPC_BULK_PUT_SOURCE = PTLRPC_BULK_OP_ACTIVE | PTLRPC_BULK_OP_PUT
}
enum {
SVC_STOPPED = 1 << 0, SVC_STOPPING = 1 << 1, SVC_STARTING = 1 << 2, SVC_RUNNING = 1 << 3,
SVC_EVENT = 1 << 4, SVC_SIGNAL = 1 << 5
}
enum ptlrpcd_ctl_flags { LIOD_START = 1 << 0, LIOD_STOP = 1 << 1, LIOD_FORCE = 1 << 2, LIOD_RECOVERY = 1 << 3 }
Functions
static int ptlrpc_req_interpret (const struct lu_env *env, struct ptlrpc_request *req, int rc)
Call completion handler for rpc if any, return it's status or original rc if there was no handler defined for this request.
static int lustre_req_swabbed (struct ptlrpc_request *req, size_t index)
Returns 1 if request buffer at offset index was already swabbed.
static int lustre_rep_swabbed (struct ptlrpc_request *req, size_t index)
Returns 1 if request reply buffer at offset index was already swabbed.
static int ptlrpc_req_need_swab (struct ptlrpc_request *req)
Returns 1 if request needs to be swabbed into local cpu byteorder.
static int ptlrpc_rep_need_swab (struct ptlrpc_request *req)
Returns 1 if request reply needs to be swabbed into local cpu byteorder.
static void lustre_set_req_swabbed (struct ptlrpc_request *req, size_t index)
Mark request buffer at offset index that it was already swabbed.
static void lustre_set_rep_swabbed (struct ptlrpc_request *req, size_t index)
Mark request reply buffer at offset index that it was already swabbed.
static const char * ptlrpc_phase2str (enum rq_phase phase)
Convert numerical request phase value phase into text string description.
static const char * ptlrpc_rqphase2str (struct ptlrpc_request *req)
Convert numerical request phase of the request req into text stringi description.
static bool ptlrpc_is_bulk_op_get (enum ptlrpc_bulk_op_type type)
static bool ptlrpc_is_bulk_get_source (enum ptlrpc_bulk_op_type type)
static bool ptlrpc_is_bulk_put_sink (enum ptlrpc_bulk_op_type type)
static bool ptlrpc_is_bulk_get_sink (enum ptlrpc_bulk_op_type type)
static bool ptlrpc_is_bulk_put_source (enum ptlrpc_bulk_op_type type)
static bool ptlrpc_is_bulk_desc_kvec (enum ptlrpc_bulk_op_type type)
static bool ptlrpc_is_bulk_desc_kiov (enum ptlrpc_bulk_op_type type)
static bool ptlrpc_is_bulk_op_active (enum ptlrpc_bulk_op_type type)
static bool ptlrpc_is_bulk_op_passive (enum ptlrpc_bulk_op_type type)
static int thread_is_init (struct ptlrpc_thread *thread)
static int thread_is_stopped (struct ptlrpc_thread *thread)
static int thread_is_stopping (struct ptlrpc_thread *thread)
static int thread_is_starting (struct ptlrpc_thread *thread)
static int thread_is_running (struct ptlrpc_thread *thread)
static int thread_is_event (struct ptlrpc_thread *thread)
static int thread_is_signal (struct ptlrpc_thread *thread)
static void thread_clear_flags (struct ptlrpc_thread *thread, __u32 flags)
static void thread_set_flags (struct ptlrpc_thread *thread, __u32 flags)
static void thread_add_flags (struct ptlrpc_thread *thread, __u32 flags)
static int thread_test_and_clear_flags (struct ptlrpc_thread *thread, __u32 flags)
int ptlrpc_uuid_to_peer (struct obd_uuid *uuid, lnet_process_id_t *peer, lnet_nid_t *self)
struct ptlrpc_connection * ptlrpc_connection_get (lnet_process_id_t peer, lnet_nid_t self, struct obd_uuid *uuid)
int ptlrpc_connection_put (struct ptlrpc_connection *c)
struct ptlrpc_connection * ptlrpc_connection_addref (struct ptlrpc_connection *)
int ptlrpc_connection_init (void)
void ptlrpc_connection_fini (void)
lnet_pid_t ptl_get_pid (void)
static void ptlrpc_rqphase_move (struct ptlrpc_request *req, enum rq_phase new_phase)
Change request phase of req to new_phase.
static int ptlrpc_client_early (struct ptlrpc_request *req)
Returns true if request req got early reply and hard deadline is not met.
static int ptlrpc_client_replied (struct ptlrpc_request *req)
Returns true if we got real reply from server for this request.
static int ptlrpc_client_recv (struct ptlrpc_request *req)
Returns true if request req is in process of receiving server reply.
static int ptlrpc_client_recv_or_unlink (struct ptlrpc_request *req)
static void ptlrpc_client_wake_req (struct ptlrpc_request *req)
static void ptlrpc_rs_addref (struct ptlrpc_reply_state *rs)
static void ptlrpc_rs_decref (struct ptlrpc_reply_state *rs)
static void ptlrpc_req_drop_rs (struct ptlrpc_request *req)
static __u32 lustre_request_magic (struct ptlrpc_request *req)
static int ptlrpc_req_get_repsize (struct ptlrpc_request *req)
static int ptlrpc_send_limit_expired (struct ptlrpc_request *req)
static int ptlrpc_no_resend (struct ptlrpc_request *req)
static int ptlrpc_server_get_timeout (struct ptlrpc_service_part *svcpt)
static struct ptlrpc_service * ptlrpc_req2svc (struct ptlrpc_request *req)
int ptlrpc_pinger_suppress_pings (void)
void ptlrpcd_stop (struct ptlrpcd_ctl *pc, int force)
void ptlrpcd_free (struct ptlrpcd_ctl *pc)
void ptlrpcd_wake (struct ptlrpc_request *req)
void ptlrpcd_add_req (struct ptlrpc_request *req)
Requests that are added to the ptlrpcd queue are sent via ptlrpcd_check->ptlrpc_check_set().
void ptlrpcd_add_rqset (struct ptlrpc_request_set *set)
Move all request from an existing request set to the ptlrpcd queue.
int ptlrpcd_addref (void)
void ptlrpcd_decref (void)
int llog_origin_handle_open (struct ptlrpc_request *req)
int llog_origin_handle_destroy (struct ptlrpc_request *req)
int llog_origin_handle_prev_block (struct ptlrpc_request *req)
int llog_origin_handle_next_block (struct ptlrpc_request *req)
int llog_origin_handle_read_header (struct ptlrpc_request *req)
int llog_origin_handle_close (struct ptlrpc_request *req)
Variables
struct ptlrpc_bulk_frag_ops ptlrpc_bulk_kiov_pin_ops
struct ptlrpc_bulk_frag_ops ptlrpc_bulk_kiov_nopin_ops
struct ptlrpc_bulk_frag_ops ptlrpc_bulk_kvec_ops
lnet_handle_eq_t ptlrpc_eq_h
struct llog_operations llog_client_ops
enum timeout_event { TIMEOUT_GRANT = 1 }
Pinger API (client side only).
typedef int(* timeout_cb_t)(struct timeout_item *, void *)
void _debug_req (struct ptlrpc_request *req, struct libcfs_debug_msg_data *data, const char *fmt,...) __attribute__((format(printf
void request_out_callback (lnet_event_t *ev)
These callbacks are invoked by LNet when something happened to underlying buffer.
void reply_in_callback (lnet_event_t *ev)
void client_bulk_callback (lnet_event_t *ev)
void request_in_callback (lnet_event_t *ev)
void reply_out_callback (lnet_event_t *ev)
int ptlrpc_register_bulk (struct ptlrpc_request *req)
Actual interfacing with LNet to put/get/register/unregister stuff.
int ptlrpc_unregister_bulk (struct ptlrpc_request *req, int async)
Disconnect a bulk desc from the network.
static int ptlrpc_client_bulk_active (struct ptlrpc_request *req)
int ptlrpc_send_reply (struct ptlrpc_request *req, int flags)
Send request reply from request req reply buffer.
int ptlrpc_reply (struct ptlrpc_request *req)
int ptlrpc_send_error (struct ptlrpc_request *req, int difficult)
For request req send an error reply back.
int ptlrpc_error (struct ptlrpc_request *req)
int ptlrpc_at_get_net_latency (struct ptlrpc_request *req)
int ptl_send_rpc (struct ptlrpc_request *request, int noreply)
Send request request.
int ptlrpc_register_rqbd (struct ptlrpc_request_buffer_desc *rqbd)
Register request buffer descriptor for request receiving.
void ptlrpc_request_committed (struct ptlrpc_request *req, int force)
Client-side portals API.
void ptlrpc_init_client (int req_portal, int rep_portal, char *name, struct ptlrpc_client *)
Initialize passed in client structure cl.
void ptlrpc_cleanup_client (struct obd_import *imp)
struct ptlrpc_connection * ptlrpc_uuid_to_connection (struct obd_uuid *uuid)
Return PortalRPC connection for remore uud uuid.
int ptlrpc_queue_wait (struct ptlrpc_request *req)
Send request and wait until it completes.
int ptlrpc_replay_req (struct ptlrpc_request *req)
Prepares and queues request for replay.
void ptlrpc_restart_req (struct ptlrpc_request *req)
void ptlrpc_abort_inflight (struct obd_import *imp)
Aborts all in-flight request on import imp sending and delayed lists.
void ptlrpc_cleanup_imp (struct obd_import *imp)
void ptlrpc_abort_set (struct ptlrpc_request_set *set)
Abort all uncompleted requests in request set set.
struct ptlrpc_request_set * ptlrpc_prep_set (void)
Allocate and initialize new request set structure on the current CPT.
struct ptlrpc_request_set * ptlrpc_prep_fcset (int max, set_producer_func func, void *arg)
Allocate and initialize new request set structure with flow control extension.
int ptlrpc_set_add_cb (struct ptlrpc_request_set *set, set_interpreter_func fn, void *data)
Add a callback function fn to the set.
int ptlrpc_check_set (const struct lu_env *env, struct ptlrpc_request_set *set)
this sends any unsent RPCs in set and returns 1 if all are sent and no more replies are expected.
int ptlrpc_set_wait (struct ptlrpc_request_set *)
Send all unset request from the set and then wait untill all requests in the set complete (either get a reply, timeout, get an error or otherwise be interrupted).
void ptlrpc_mark_interrupted (struct ptlrpc_request *req)
Sets rq_intr flag in req under spinlock.
void ptlrpc_set_destroy (struct ptlrpc_request_set *)
Wind down and free request set structure previously allocated with ptlrpc_prep_set.
void ptlrpc_set_add_req (struct ptlrpc_request_set *, struct ptlrpc_request *)
Add a new request to the general purpose request set.
void ptlrpc_free_rq_pool (struct ptlrpc_request_pool *pool)
Wind down request pool pool.
int ptlrpc_add_rqs_to_pool (struct ptlrpc_request_pool *pool, int num_rq)
Allocates, initializes and adds num_rq requests to the pool pool.
struct ptlrpc_request_pool * ptlrpc_init_rq_pool (int, int, int(*populate_pool)(struct ptlrpc_request_pool *, int))
Create and initialize new request pool with given attributes: num_rq - initial number of requests to create for the pool msgsize - maximum message size possible for requests in thid pool populate_pool - function to be called when more requests need to be added to the pool Returns pointer to newly created pool or NULL on error.
void ptlrpc_at_set_req_timeout (struct ptlrpc_request *req)
Set server timelimit for this req, i.e.
struct ptlrpc_request * ptlrpc_request_alloc (struct obd_import *imp, const struct req_format *format)
Allocate new request structure for import imp and initialize its buffer structure according to capsule template format.
struct ptlrpc_request * ptlrpc_request_alloc_pool (struct obd_import *imp, struct ptlrpc_request_pool *, const struct req_format *format)
Allocate new request structure for import imp from pool pool and initialize its buffer structure according to capsule template format.
void ptlrpc_request_free (struct ptlrpc_request *request)
For requests not from pool, free memory of the request structure.
int ptlrpc_request_pack (struct ptlrpc_request *request, __u32 version, int opcode)
Pack request buffers for network transfer, performing necessary encryption steps if necessary.
struct ptlrpc_request * ptlrpc_request_alloc_pack (struct obd_import *imp, const struct req_format *format, __u32 version, int opcode)
Allocate new request for operatione opcode and immediatelly pack it for network transfer.
int ptlrpc_request_bufs_pack (struct ptlrpc_request *request, __u32 version, int opcode, char **bufs, struct ptlrpc_cli_ctx *ctx)
void ptlrpc_req_finished (struct ptlrpc_request *request)
Drops one reference count for a request.
void ptlrpc_req_finished_with_imp_lock (struct ptlrpc_request *request)
Drop one request reference.
struct ptlrpc_request * ptlrpc_request_addref (struct ptlrpc_request *req)
Grab additional reference on a request req.
struct ptlrpc_bulk_desc * ptlrpc_prep_bulk_imp (struct ptlrpc_request *req, unsigned nfrags, unsigned max_brw, unsigned int type, unsigned portal, const struct ptlrpc_bulk_frag_ops *ops)
Prepare bulk descriptor for specified outgoing request req that can fit nfrags * pages.
int ptlrpc_prep_bulk_frag (struct ptlrpc_bulk_desc *desc, void *frag, int len)
void __ptlrpc_prep_bulk_page (struct ptlrpc_bulk_desc *desc, struct page *page, int pageoffset, int len, int pin)
static void ptlrpc_prep_bulk_page_pin (struct ptlrpc_bulk_desc *desc, struct page *page, int pageoffset, int len)
static void ptlrpc_prep_bulk_page_nopin (struct ptlrpc_bulk_desc *desc, struct page *page, int pageoffset, int len)
void ptlrpc_free_bulk (struct ptlrpc_bulk_desc *bulk)
static void ptlrpc_release_bulk_page_pin (struct ptlrpc_bulk_desc *desc)
static void ptlrpc_release_bulk_noop (struct ptlrpc_bulk_desc *desc)
void ptlrpc_retain_replayable_request (struct ptlrpc_request *req, struct obd_import *imp)
Add a request to import replay_list.
__u64 ptlrpc_next_xid (void)
Increase xid and returns resulting new value to the caller.
__u64 ptlrpc_sample_next_xid (void)
Get a glimpse at what next xid value might have been.
__u64 ptlrpc_req_xid (struct ptlrpc_request *request)
Returns xid of a request.
void * ptlrpcd_alloc_work (struct obd_import *imp, int(*cb)(const struct lu_env *, void *), void *data)
Create a work for ptlrpc.
void ptlrpcd_destroy_work (void *handler)
int ptlrpcd_queue_work (void *handler)
void ptlrpc_save_lock (struct ptlrpc_request *req, struct lustre_handle *lock, int mode, int no_ack)
Server-side services API.
void ptlrpc_commit_replies (struct obd_export *exp)
void ptlrpc_dispatch_difficult_reply (struct ptlrpc_reply_state *rs)
Put reply state into a queue for processing because we received ACK from the client.
void ptlrpc_schedule_difficult_reply (struct ptlrpc_reply_state *rs)
int ptlrpc_hpreq_handler (struct ptlrpc_request *req)
struct ptlrpc_service * ptlrpc_register_service (struct ptlrpc_service_conf *conf, struct proc_dir_entry *proc_entry)
Initialize service on a given portal.
void ptlrpc_stop_all_threads (struct ptlrpc_service *svc)
Stops all threads of a particular service svc.
int ptlrpc_start_threads (struct ptlrpc_service *svc)
int ptlrpc_unregister_service (struct ptlrpc_service *service)
int liblustre_check_services (void *arg)
void ptlrpc_daemonize (char *name)
int ptlrpc_service_health_check (struct ptlrpc_service *)
void ptlrpc_server_drop_request (struct ptlrpc_request *req)
drop a reference count of the request.
void ptlrpc_request_change_export (struct ptlrpc_request *req, struct obd_export *export)
Change request export and move hp request from old export to new.
void ptlrpc_update_export_timer (struct obd_export *exp, long extra_delay)
This function makes sure dead exports are evicted in a timely manner.
int ptlrpc_hr_init (void)
void ptlrpc_hr_fini (void)
int ptlrpc_connect_import (struct obd_import *imp)
Import API.
int ptlrpc_init_import (struct obd_import *imp)
int ptlrpc_disconnect_import (struct obd_import *imp, int noclose)
int ptlrpc_import_recovery_state_machine (struct obd_import *imp)
This is the state machine for client-side recovery on import.
void deuuidify (char *uuid, const char *prefix, char **uuid_start, int *uuid_len)
void ptlrpc_import_enter_resend (struct obd_import *imp)
int ptlrpc_reconnect_import (struct obd_import *imp)
int ptlrpc_buf_need_swab (struct ptlrpc_request *req, const int inout, __u32 index)
ptlrpc msg buffer and swab interface
void ptlrpc_buf_set_swabbed (struct ptlrpc_request *req, const int inout, __u32 index)
int ptlrpc_unpack_rep_msg (struct ptlrpc_request *req, int len)
int ptlrpc_unpack_req_msg (struct ptlrpc_request *req, int len)
int lustre_msg_check_version (struct lustre_msg *msg, __u32 version)
void lustre_init_msg_v2 (struct lustre_msg_v2 *msg, int count, __u32 *lens, char **bufs)
int lustre_pack_request (struct ptlrpc_request *, __u32 magic, int count, __u32 *lens, char **bufs)
int lustre_pack_reply (struct ptlrpc_request *, int count, __u32 *lens, char **bufs)
int lustre_pack_reply_v2 (struct ptlrpc_request *req, int count, __u32 *lens, char **bufs, int flags)
int lustre_pack_reply_flags (struct ptlrpc_request *, int count, __u32 *lens, char **bufs, int flags)
int lustre_shrink_msg (struct lustre_msg *msg, int segment, unsigned int newlen, int move_data)
void lustre_free_reply_state (struct ptlrpc_reply_state *rs)
int __lustre_unpack_msg (struct lustre_msg *m, int len)
__u32 lustre_msg_hdr_size (__u32 magic, __u32 count)
__u32 lustre_msg_size (__u32 magic, int count, __u32 *lengths)
__u32 lustre_msg_size_v2 (int count, __u32 *lengths)
__u32 lustre_packed_msg_size (struct lustre_msg *msg)
__u32 lustre_msg_early_size (void)
void * lustre_msg_buf_v2 (struct lustre_msg_v2 *m, __u32 n, __u32 min_size)
void * lustre_msg_buf (struct lustre_msg *m, __u32 n, __u32 minlen)
__u32 lustre_msg_buflen (struct lustre_msg *m, __u32 n)
lustre_msg_buflen - return the length of buffer n in message m
void lustre_msg_set_buflen (struct lustre_msg *m, __u32 n, __u32 len)
__u32 lustre_msg_bufcount (struct lustre_msg *m)
char * lustre_msg_string (struct lustre_msg *m, __u32 n, __u32 max_len)
__u32 lustre_msghdr_get_flags (struct lustre_msg *msg)
void lustre_msghdr_set_flags (struct lustre_msg *msg, __u32 flags)
__u32 lustre_msg_get_flags (struct lustre_msg *msg)
void lustre_msg_add_flags (struct lustre_msg *msg, __u32 flags)
void lustre_msg_set_flags (struct lustre_msg *msg, __u32 flags)
void lustre_msg_clear_flags (struct lustre_msg *msg, __u32 flags)
__u32 lustre_msg_get_op_flags (struct lustre_msg *msg)
void lustre_msg_add_op_flags (struct lustre_msg *msg, __u32 flags)
struct lustre_handle * lustre_msg_get_handle (struct lustre_msg *msg)
__u32 lustre_msg_get_type (struct lustre_msg *msg)
__u32 lustre_msg_get_version (struct lustre_msg *msg)
void lustre_msg_add_version (struct lustre_msg *msg, __u32 version)
__u32 lustre_msg_get_opc (struct lustre_msg *msg)
__u64 lustre_msg_get_last_xid (struct lustre_msg *msg)
__u16 lustre_msg_get_tag (struct lustre_msg *msg)
__u64 lustre_msg_get_last_committed (struct lustre_msg *msg)
__u64 * lustre_msg_get_versions (struct lustre_msg *msg)
__u64 lustre_msg_get_transno (struct lustre_msg *msg)
__u64 lustre_msg_get_slv (struct lustre_msg *msg)
__u32 lustre_msg_get_limit (struct lustre_msg *msg)
void lustre_msg_set_slv (struct lustre_msg *msg, __u64 slv)
void lustre_msg_set_limit (struct lustre_msg *msg, __u64 limit)
int lustre_msg_get_status (struct lustre_msg *msg)
__u32 lustre_msg_get_conn_cnt (struct lustre_msg *msg)
__u32 lustre_msg_get_magic (struct lustre_msg *msg)
__u32 lustre_msg_get_timeout (struct lustre_msg *msg)
__u32 lustre_msg_get_service_time (struct lustre_msg *msg)
char * lustre_msg_get_jobid (struct lustre_msg *msg)
__u32 lustre_msg_get_cksum (struct lustre_msg *msg)
__u64 lustre_msg_get_mbits (struct lustre_msg *msg)
__u32 lustre_msg_calc_cksum (struct lustre_msg *msg)
void lustre_msg_set_handle (struct lustre_msg *msg, struct lustre_handle *handle)
void lustre_msg_set_type (struct lustre_msg *msg, __u32 type)
void lustre_msg_set_opc (struct lustre_msg *msg, __u32 opc)
void lustre_msg_set_last_xid (struct lustre_msg *msg, __u64 last_xid)
void lustre_msg_set_tag (struct lustre_msg *msg, __u16 tag)
void lustre_msg_set_last_committed (struct lustre_msg *msg, __u64 last_committed)
void lustre_msg_set_versions (struct lustre_msg *msg, __u64 *versions)
void lustre_msg_set_transno (struct lustre_msg *msg, __u64 transno)
void lustre_msg_set_status (struct lustre_msg *msg, __u32 status)
void lustre_msg_set_conn_cnt (struct lustre_msg *msg, __u32 conn_cnt)
void ptlrpc_req_set_repsize (struct ptlrpc_request *req, int count, __u32 *sizes)
void ptlrpc_request_set_replen (struct ptlrpc_request *req)
void lustre_msg_set_timeout (struct lustre_msg *msg, __u32 timeout)
void lustre_msg_set_service_time (struct lustre_msg *msg, __u32 service_time)
void lustre_msg_set_jobid (struct lustre_msg *msg, char *jobid)
void lustre_msg_set_cksum (struct lustre_msg *msg, __u32 cksum)
void lustre_msg_set_mbits (struct lustre_msg *msg, __u64 mbits)
static void lustre_shrink_reply (struct ptlrpc_request *req, int segment, unsigned int newlen, int move_data)
static int ptlrpc_status_hton (int h)
static int ptlrpc_status_ntoh (int n)
int client_obd_setup (struct obd_device *obddev, struct lustre_cfg *lcfg)
Target client logic.
int client_obd_cleanup (struct obd_device *obddev)
int client_connect_import (const struct lu_env *env, struct obd_export **exp, struct obd_device *obd, struct obd_uuid *cluuid, struct obd_connect_data *, void *localdata)
int client_disconnect_export (struct obd_export *exp)
int client_import_add_conn (struct obd_import *imp, struct obd_uuid *uuid, int priority)
int client_import_del_conn (struct obd_import *imp, struct obd_uuid *uuid)
int client_import_find_conn (struct obd_import *imp, lnet_nid_t peer, struct obd_uuid *uuid)
Find conn UUID by peer NID.
int import_set_conn_priority (struct obd_import *imp, struct obd_uuid *uuid)
void client_destroy_import (struct obd_import *imp)
int ptlrpc_pinger_add_import (struct obd_import *imp)
int ptlrpc_pinger_del_import (struct obd_import *imp)
int ptlrpc_add_timeout_client (int time, enum timeout_event event, timeout_cb_t cb, void *data, struct list_head *obd_list)
int ptlrpc_del_timeout_client (struct list_head *obd_list, enum timeout_event event)
struct ptlrpc_request * ptlrpc_prep_ping (struct obd_import *imp)
int ptlrpc_obd_ping (struct obd_device *obd)
void ping_evictor_start (void)
void ping_evictor_stop (void)
void ptlrpc_pinger_ir_up (void)
void ptlrpc_pinger_ir_down (void)
const char * ll_opcode2str (__u32 opcode)
procfs output related functions
static void ptlrpc_lprocfs_register_obd (struct obd_device *obd)
static void ptlrpc_lprocfs_unregister_obd (struct obd_device *obd)
static void ptlrpc_lprocfs_brw (struct ptlrpc_request *req, int bytes)
#define FLAG(field, str) (field ? str : "")
Debugging functions and helpers to print request structure into debug log.
#define DEBUG_REQ_FLAGS(req)
Convert bit flags into a string.
#define REQ_FLAGS_FMT "%s:%s%s%s%s%s%s%s%s%s%s%s%s"
#define debug_req(msgdata, mask, cdls, req, fmt, a...)
Helper that decides if we need to print request accordig to current debug level settings.
#define DEBUG_REQ(level, req, fmt, args...)
This is the debug print function you need to use to print request sturucture content into lustre debug log.
#define PTLRPC_REPLY_MAYBE_DIFFICULT 0x01
#define PTLRPC_REPLY_EARLY 0x02
#define LPRFL_EARLY_REPLY 1
Define Documentation
#define _OST_MAXREQSIZE_SUM
Value:
(sizeof(struct lustre_msg) + \
                             sizeof(struct ptlrpc_body) + \
                             sizeof(struct obdo) + \
                             sizeof(struct obd_ioobj) + \
                             sizeof(struct niobuf_remote) * DT_MAX_BRW_PAGES)
OST_IO_MAXREQSIZE ~= lustre_msg + ptlrpc_body + obdo + obd_ioobj + DT_MAX_BRW_PAGES * niobuf_remote.
single object with 16 pages is 512 bytes
OST_IO_MAXREQSIZE must be at least 1 page of cookies plus some spillover
Must be a multiple of 1024
actual size is about 18K
Definition at line 480 of file lustre_net.h.
#define BD_GET_ENC_KIOV (desc, i) ((desc)->bd_u.bd_kiov.bd_enc_vec[i])
Definition at line 1487 of file lustre_net.h.
Referenced by gss_prep_bulk_kerberos(), krb5_decrypt_bulk(), krb5_encrypt_bulk(), ptlrpc_fill_bulk_md(), sptlrpc_enc_pool_get_pages(), and sptlrpc_enc_pool_put_pages().
#define BD_GET_ENC_KVEC (desc, i) ((desc)->bd_u.bd_kvec.bd_enc_kvec[i])
Definition at line 1491 of file lustre_net.h.
Referenced by ptlrpc_fill_bulk_md().
#define BD_GET_KIOV (desc, i) ((desc)->bd_u.bd_kiov.bd_vec[i])
Definition at line 1485 of file lustre_net.h.
Referenced by __ptlrpc_prep_bulk_page(), corrupt_bulk_data(), gss_cli_ctx_unwrap_bulk(), gss_prep_bulk_kerberos(), krb5_decrypt_bulk(), krb5_encrypt_bulk(), plain_cli_unwrap_bulk(), ptlrpc_fill_bulk_md(), ptlrpc_release_bulk_page_pin(), sptlrpc_get_bulk_checksum(), tgt_checksum_bulk(), and unstable_page_accounting().
#define BD_GET_KVEC (desc, i) ((desc)->bd_u.bd_kvec.bd_kvec[i])
Definition at line 1489 of file lustre_net.h.
Referenced by ptlrpc_fill_bulk_md(), and ptlrpc_prep_bulk_frag().
#define DEBUG_REQ (level, req, fmt, args...)
Value:
do {                                                                          \
        if ((level) & (D_ERROR | D_WARNING)) {                                \
                static struct cfs_debug_limit_state cdls;                     \
                LIBCFS_DEBUG_MSG_DATA_DECL(msgdata, level, &cdls);            \
                debug_req(&msgdata, level, &cdls, req, "@@@ "fmt" ", ## args);\
        } else {                                                              \
                LIBCFS_DEBUG_MSG_DATA_DECL(msgdata, level, NULL);             \
                debug_req(&msgdata, level, NULL, req, "@@@ "fmt" ", ## args); \
        }                                                                     \
} while (0)
This is the debug print function you need to use to print request sturucture content into lustre debug log.
for most callers (level is a constant) this is resolved at compile time
Definition at line 1302 of file lustre_net.h.
Referenced by __ptlrpc_free_req(), __ptlrpc_req_finished(), __req_capsule_dump(), __req_capsule_get(), after_reply(), ldlm_callback_errmsg(), ldlm_cli_update_pool(), ldlm_handle_setinfo(), mdc_clear_replay_flag(), mdc_close(), mdc_finish_enqueue(), mdc_free_open(), mdc_rename(), mdc_replay_open(), mdc_set_open_replay_data(), mdt_check_resent(), mdt_intent_fixup_resent(), mdt_md_create(), mdt_reint_internal(), mdt_reint_link(), mdt_reint_opcode(), mdt_reint_open(), mdt_reint_rename_internal(), mdt_reint_setattr(), mdt_reint_unlink(), mdt_req_from_lrd(), mdt_set_info(), mdt_steal_ack_locks(), mgs_config_read(), mgs_target_reg(), ofd_get_info_hdl(), ofd_rw_hpreq_check(), ofd_set_info_hdl(), osc_brw_fini_request(), osc_brw_redo_request(), osc_build_rpc(), osp_sync_interpret(), osp_sync_process_committed(), out_check_resent(), process_req_last_xid(), ptl_send_rpc(), ptlrpc_abort_inflight(), ptlrpc_at_recv_early_reply(), ptlrpc_at_send_early_reply(), ptlrpc_at_set_reply(), ptlrpc_check_req(), ptlrpc_check_set(), ptlrpc_check_status(), ptlrpc_connect_import(), ptlrpc_connect_interpret(), ptlrpc_expire_one_request(), ptlrpc_first_transno(), ptlrpc_free_committed(), ptlrpc_import_delay_req(), ptlrpc_invalidate_import(), ptlrpc_nrs_hpreq_add_nolock(), ptlrpc_ping(), ptlrpc_replay_interpret(), ptlrpc_replay_req(), ptlrpc_resend_req(), ptlrpc_restart_req(), ptlrpc_retain_replayable_request(), ptlrpc_rqphase_move(), ptlrpc_send_new_req(), ptlrpc_server_check_resend_in_progress(), ptlrpc_server_handle_req_in(), ptlrpc_server_handle_request(), ptlrpc_unregister_bulk(), ptlrpc_unregister_reply(), ptlrpc_wake_delayed(), ptlrpcd_add_req(), reply_in_callback(), req_capsule_server_pack(), request_out_callback(), sptlrpc_cli_unwrap_early_reply(), sptlrpc_svc_check_from(), target_send_reply_msg(), tgt_brw_write(), tgt_filter_recovery_request(), tgt_handle_recovery(), tgt_handle_request0(), tgt_handler_find_check(), tgt_init_sec_level(), tgt_io_data_unpack(), tgt_request_handle(), and unpack_reply().
#define debug_req (msgdata, mask, cdls, req, fmt, a...)
Value:
do {                                                                          \
        CFS_CHECK_STACK(msgdata, mask, cdls);                                 \
                                                                              \
        if (((mask) & D_CANTMASK) != 0 ||                                     \
            ((libcfs_debug & (mask)) != 0 &&                                  \
             (libcfs_subsystem_debug & DEBUG_SUBSYSTEM) != 0))                \
                _debug_req((req), msgdata, fmt, ##a);                         \
} while(0)
Helper that decides if we need to print request accordig to current debug level settings.
Definition at line 1288 of file lustre_net.h.
#define DEBUG_REQ_FLAGS (req)
Value:
ptlrpc_rqphase2str(req),                                                \
        FLAG(req->rq_intr, "I"), FLAG(req->rq_replied, "R"),                    \
        FLAG(req->rq_err, "E"),                                                 \
        FLAG(req->rq_timedout, "X") /* eXpired */, FLAG(req->rq_resend, "S"),   \
        FLAG(req->rq_restart, "T"), FLAG(req->rq_replay, "P"),                  \
        FLAG(req->rq_no_resend, "N"),                                           \
        FLAG(req->rq_waiting, "W"),                                             \
        FLAG(req->rq_wait_ctx, "C"), FLAG(req->rq_hp, "H"),                     \
        FLAG(req->rq_committed, "M")
Convert bit flags into a string.
Definition at line 1267 of file lustre_net.h.
Referenced by _debug_req().
#define DT_MAX_BRW_PAGES (DT_MAX_BRW_SIZE >> PAGE_CACHE_SHIFT)
Definition at line 111 of file lustre_net.h.
Referenced by osc_init_grant().
#define DT_MAX_BRW_SIZE PTLRPC_MAX_BRW_SIZE
Definition at line 110 of file lustre_net.h.
Referenced by client_common_fill_super(), and echo_client_setup().
#define FLAG (field, str) (field ? str : "")
Debugging functions and helpers to print request structure into debug log.
Definition at line 1264 of file lustre_net.h.
#define FLD_BUFSIZE (1 << 12)
Definition at line 414 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service().
#define FLD_MAXREPSIZE (152)
FLD_MAXREPSIZE == lustre_msg + ptlrpc_body.
Definition at line 413 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service().
#define FLD_MAXREQSIZE (160)
FLD_MAXREQSIZE == lustre_msg + __u32 padding + ptlrpc_body + opc.
Definition at line 410 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service().
#define GET_ENC_KIOV (desc) ((desc)->bd_u.bd_kiov.bd_enc_vec)
Definition at line 1486 of file lustre_net.h.
Referenced by gss_prep_bulk_kerberos(), krb5_decrypt_bulk(), krb5_encrypt_bulk(), ptlrpc_fill_bulk_md(), sptlrpc_enc_pool_get_pages(), and sptlrpc_enc_pool_put_pages().
#define GET_ENC_KVEC (desc) ((desc)->bd_u.bd_kvec.bd_enc_kvec)
Definition at line 1490 of file lustre_net.h.
Referenced by ptlrpc_fill_bulk_md().
#define GET_KIOV (desc) ((desc)->bd_u.bd_kiov.bd_vec)
Definition at line 1484 of file lustre_net.h.
Referenced by gss_cli_ctx_unwrap_bulk(), gss_cli_ctx_wrap_bulk(), gss_svc_unwrap_bulk(), gss_svc_wrap_bulk(), gss_unwrap_bulk_kerberos(), gss_wrap_bulk_kerberos(), ptlrpc_free_bulk(), and ptlrpc_new_bulk().
#define GET_KVEC (desc) ((desc)->bd_u.bd_kvec.bd_kvec)
Definition at line 1488 of file lustre_net.h.
Referenced by ptlrpc_free_bulk(), and ptlrpc_new_bulk().
#define LDLM_BL_THREADS LDLM_NTHRS_AUTO_INIT
Definition at line 262 of file lustre_net.h.
#define LDLM_BUFSIZE (8 * 1024)
Definition at line 265 of file lustre_net.h.
Referenced by ldlm_setup().
#define LDLM_CLIENT_NBUFS 1
Definition at line 263 of file lustre_net.h.
Referenced by ldlm_setup().
#define LDLM_MAXREPSIZE (1024)
Definition at line 267 of file lustre_net.h.
Referenced by ldlm_setup().
#define LDLM_MAXREQSIZE (5 * 1024)
Definition at line 266 of file lustre_net.h.
Referenced by ldlm_req_handles_avail(), and ldlm_setup().
#define LDLM_NTHRS_BASE 24
Definition at line 259 of file lustre_net.h.
Referenced by ldlm_setup().
#define LDLM_NTHRS_INIT PTLRPC_NTHRS_INIT
Definition at line 258 of file lustre_net.h.
Referenced by ldlm_setup().
#define LDLM_NTHRS_MAX (num_online_cpus() == 1 ? 64 : 128)
Definition at line 260 of file lustre_net.h.
Referenced by ldlm_setup().
#define LDLM_SERVER_NBUFS 64
Definition at line 264 of file lustre_net.h.
Referenced by ldlm_setup().
#define LDLM_THR_FACTOR 8
Buffer Constants.
Constants determine how memory is used to buffer incoming service requests.
?_NBUFS # buffers to allocate when growing the pool ?_BUFSIZE # bytes in a single request buffer ?_MAXREQSIZE # maximum request service will receive
When fewer than ?_NBUFS/2 buffers are posted for receive, another chunk of ?_NBUFS is added to the pool.
Messages larger than ?_MAXREQSIZE are dropped. Request buffers are considered full when less than ?_MAXREQSIZE is left in them. Thread Constants Constants determine how threads are created for ptlrpc service.
?_NTHRS_INIT # threads to create for each service partition on initializing. If it's non-affinity service and there is only one partition, it's the overall # threads for the service while initializing. ?_NTHRS_BASE # threads should be created at least for each ptlrpc partition to keep the service healthy. It's the low-water mark of threads upper-limit for each partition. ?_THR_FACTOR # threads can be added on threads upper-limit for each CPU core. This factor is only for reference, we might decrease value of factor if number of cores per CPT is above a limit. ?_NTHRS_MAX # overall threads can be created for a service, it's a soft limit because if service is running on machine with hundreds of cores and tens of CPU partitions, we need to guarantee each partition has ?_NTHRS_BASE threads, which means total threads will be ?_NTHRS_BASE * number_of_cpts which can exceed ?_NTHRS_MAX.
Examples
define MDS_NTHRS_INIT 2 define MDS_NTHRS_BASE 64 define MDS_NTHRS_FACTOR 8 define MDS_NTHRS_MAX 1024
Example 1): --------------------------------------------------------------------- Server(A) has 16 cores, user configured it to 4 partitions so each partition has 4 cores, then actual number of service threads on each partition is: MDS_NTHRS_BASE(64) + cores(4) * MDS_NTHRS_FACTOR(8) = 96
Total number of threads for the service is: 96 * partitions(4) = 384
Example 2): --------------------------------------------------------------------- Server(B) has 32 cores, user configured it to 4 partitions so each partition has 8 cores, then actual number of service threads on each partition is: MDS_NTHRS_BASE(64) + cores(8) * MDS_NTHRS_FACTOR(8) = 128
Total number of threads for the service is: 128 * partitions(4) = 512
Example 3): --------------------------------------------------------------------- Server(B) has 96 cores, user configured it to 8 partitions so each partition has 12 cores, then actual number of service threads on each partition is: MDS_NTHRS_BASE(64) + cores(12) * MDS_NTHRS_FACTOR(8) = 160
Total number of threads for the service is: 160 * partitions(8) = 1280
However, it's above the soft limit MDS_NTHRS_MAX, so we choose this number as upper limit of threads number for each partition: MDS_NTHRS_MAX(1024) / partitions(8) = 128
Example 4): --------------------------------------------------------------------- Server(C) have a thousand of cores and user configured it to 32 partitions MDS_NTHRS_BASE(64) * 32 = 2048
which is already above soft limit MDS_NTHRS_MAX(1024), but we still need to guarantee that each partition has at least MDS_NTHRS_BASE(64) threads to keep service healthy, so total number of threads will just be 2048.
NB: we don't suggest to choose server with that many cores because backend filesystem itself, buffer cache, or underlying network stack might have some SMP scalability issues at that large scale.
If user already has a fat machine with hundreds or thousands of cores, there are two choices for configuration: a) create CPU table from subset of all CPUs and run Lustre on top of this subset b) bind service threads on a few partitions, see modparameters of MDS and OSS for details
NB: these calculations (and examples below) are simplified to help understanding, the real implementation is a little more complex, please see ptlrpc_server_nthreads_check() for details.
Definition at line 257 of file lustre_net.h.
Referenced by ldlm_setup().
#define LPRFL_EARLY_REPLY 1
Definition at line 2316 of file lustre_net.h.
Referenced by lustre_pack_reply_v2(), and ptlrpc_at_send_early_reply().
#define MD_MAX_BRW_PAGES (MD_MAX_BRW_SIZE >> PAGE_CACHE_SHIFT)
Definition at line 109 of file lustre_net.h.
#define MD_MAX_BRW_SIZE (1 << LNET_MTU_BITS)
Definition at line 108 of file lustre_net.h.
Referenced by client_common_fill_super(), mdt_connect_internal(), and osp_prep_update_req().
#define MDS_BUFSIZE
Value:
max(MDS_MAXREQSIZE + SPTLRPC_MAX_PAYLOAD, \
                                    8 * 1024)
MDS_BUFSIZE = max_reqsize (w/o LOV EA) + max sptlrpc payload size.
Definition at line 379 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service().
#define MDS_EA_MAXREQSIZE 66288
This is the size of a maximum REINT_SETXATTR request:.
lustre_msg 56 (32 + 4 x 5 + 4) ptlrpc_body 184 mdt_rec_setxattr 136 lustre_capa 120 name 256 (XATTR_NAME_MAX) value 65536 (XATTR_SIZE_MAX)
Definition at line 360 of file lustre_net.h.
#define MDS_LOV_MAXREPSIZE MDS_LOV_MAXREQSIZE
MDS outgoing reply with LOV EA.
NB: max reply size Lustre 2.4+ client can get from old MDS is: LOV_MAX_STRIPE_COUNT * (llog_cookie + lov_ost_data) + extra bytes
but 2.4 or later MDS will never send reply with llog_cookie to any version client. This macro is defined for server side reply buffer size.
Definition at line 348 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service().
#define MDS_LOV_MAXREQSIZE
Value:
max(MDS_MAXREQSIZE, \
                                    362 + LOV_MAX_STRIPE_COUNT * 24)
MDS incoming request with LOV EA 24 = sizeof(struct lov_ost_data), i.e: replay of opencreate.
Definition at line 337 of file lustre_net.h.
#define MDS_MAX_OTHR_THREADS 256
Definition at line 277 of file lustre_net.h.
#define MDS_MAX_THREADS 1024
Definition at line 276 of file lustre_net.h.
#define MDS_MAXREPSIZE (9 * 1024)
Definition at line 331 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service().
#define MDS_MAXREQSIZE (5 * 1024)
Assume file name length = FNAME_MAX = 256 (true for ext3).
path name length = PATH_MAX = 4096 LOV MD size max = EA_MAX = 24 * 2000 (NB: 24 is size of lov_ost_data) LOV LOGCOOKIE size max = 32 * 2000 (NB: 32 is size of llog_cookie) symlink: FNAME_MAX + PATH_MAX <- largest link: FNAME_MAX + PATH_MAX (mds_rec_link < mds_rec_create) rename: FNAME_MAX + FNAME_MAX open: FNAME_MAX + EA_MAX
MDS_MAXREQSIZE ~= 4736 bytes = lustre_msg + ldlm_request + mdt_body + mds_rec_create + FNAME_MAX + PATH_MAX MDS_MAXREPSIZE ~= 8300 bytes = lustre_msg + llog_header
Realistic size is about 512 bytes (20 character name + 128 char symlink), except in the open case where there are a large number of OSTs in a LOV.
Definition at line 330 of file lustre_net.h.
Referenced by ll_dir_ioctl(), and mds_start_ptlrpc_service().
#define MDS_NBUFS 64
Definition at line 309 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service().
#define MDS_NTHRS_BASE min(64, MDS_NTHRS_MAX)
Definition at line 291 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service().
#define MDS_NTHRS_INIT PTLRPC_NTHRS_INIT
Definition at line 289 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service().
#define MDS_NTHRS_MAX MDS_MAX_THREADS
Definition at line 290 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service().
#define MDS_OTHR_NTHRS_INIT PTLRPC_NTHRS_INIT
Definition at line 306 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service().
#define MDS_OTHR_NTHRS_MAX MDS_MAX_OTHR_THREADS
Definition at line 307 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service().
#define MDS_RDPG_NTHRS_BASE min(48, MDS_RDPG_NTHRS_MAX)
Definition at line 297 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service().
#define MDS_RDPG_NTHRS_INIT PTLRPC_NTHRS_INIT
Definition at line 295 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service().
#define MDS_RDPG_NTHRS_MAX MDS_MAX_OTHR_THREADS
Definition at line 296 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service().
#define MDS_RDPG_THR_FACTOR 4
Definition at line 294 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service().
#define MDS_REG_BUFSIZE
Value:
max(MDS_REG_MAXREQSIZE + SPTLRPC_MAX_PAYLOAD, \
                                    160 * 1024)
MDS_REG_BUFSIZE should at least be MDS_REG_MAXREQSIZE + SPTLRPC_MAX_PAYLOAD.
However, we need to allocate a much larger buffer for it because LNet requires each MD(rqbd) has at least MDS_REQ_MAXREQSIZE bytes left to avoid dropping of maximum-sized incoming request. So if MDS_REG_BUFSIZE is only a little larger than MDS_REG_MAXREQSIZE, then it can only fit in one request even there are about MDS_REG_MAX_REQSIZE bytes left in a rqbd, and memory utilization is very low.
In the meanwhile, size of rqbd can't be too large, because rqbd can't be reused until all requests fit in it have been processed and released, which means one long blocked request can prevent the rqbd be reused. Now we set request buffer size to 160 KB, so even each rqbd is unlinked from LNet with unused 65 KB, buffer utilization will be about 59%. Please check LU-2432 for details.
Definition at line 398 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service().
#define MDS_REG_MAXREPSIZE MDS_REG_MAXREQSIZE
Definition at line 368 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service().
#define MDS_REG_MAXREQSIZE
Value:
(((max(MDS_EA_MAXREQSIZE, \
                                       MDS_LOV_MAXREQSIZE) + 1023) >> 10) << 10)
These are the maximum request and reply sizes (rounded up to 1 KB boundaries) for the "regular" MDS_REQUEST_PORTAL and MDS_REPLY_PORTAL.
Definition at line 366 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service().
#define MDS_SETA_NTHRS_BASE min(48, MDS_SETA_NTHRS_MAX)
Definition at line 303 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service().
#define MDS_SETA_NTHRS_INIT PTLRPC_NTHRS_INIT
Definition at line 301 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service().
#define MDS_SETA_NTHRS_MAX MDS_MAX_OTHR_THREADS
Definition at line 302 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service().
#define MDS_SETA_THR_FACTOR 4
Definition at line 300 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service().
#define MDS_THR_FACTOR 8
Definition at line 288 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service().
#define MGS_BUFSIZE (8 * 1024)
Definition at line 430 of file lustre_net.h.
Referenced by mgs_init0().
#define MGS_MAXREPSIZE (9 * 1024)
Definition at line 432 of file lustre_net.h.
Referenced by mgs_init0().
#define MGS_MAXREQSIZE (7 * 1024)
Definition at line 431 of file lustre_net.h.
Referenced by mgs_init0().
#define MGS_NBUFS 64
Definition at line 429 of file lustre_net.h.
Referenced by mgs_init0().
#define MGS_NTHRS_INIT (PTLRPC_NTHRS_INIT + 1)
MGS threads must be >= 3, see bug 22458 comment #28.
Definition at line 426 of file lustre_net.h.
Referenced by mgs_init0().
#define MGS_NTHRS_MAX 32
Definition at line 427 of file lustre_net.h.
Referenced by mgs_init0().
#define OFD_MAX_BRW_SIZE (1 << LNET_MTU_BITS)
Definition at line 112 of file lustre_net.h.
Referenced by osp_it_fetch(), and qsd_reint_index().
#define ONE_MB_BRW_SIZE (1 << LNET_MTU_BITS)
Definition at line 107 of file lustre_net.h.
Referenced by exp_connect_multibulk(), exp_max_brw_size(), and ofd_init0().
#define OSS_CR_NTHRS_BASE 8
Definition at line 467 of file lustre_net.h.
Referenced by ost_setup().
#define OSS_CR_NTHRS_INIT PTLRPC_NTHRS_INIT
Definition at line 466 of file lustre_net.h.
Referenced by ost_setup().
#define OSS_CR_NTHRS_MAX 64
Definition at line 468 of file lustre_net.h.
Referenced by ost_setup().
#define OSS_CR_THR_FACTOR 1
Definition at line 465 of file lustre_net.h.
Referenced by ost_setup().
#define OSS_NTHRS_BASE 64
Definition at line 462 of file lustre_net.h.
Referenced by ost_setup().
#define OSS_NTHRS_INIT (PTLRPC_NTHRS_INIT + 1)
Definition at line 461 of file lustre_net.h.
Referenced by ost_setup().
#define OSS_THR_FACTOR
Value:
min_t(int, 8, \
                                NUM_CACHEPAGES >> (28 - PAGE_CACHE_SHIFT))
Definition at line 459 of file lustre_net.h.
Referenced by ost_setup().
#define OST_BUFSIZE max_t(int, OST_MAXREQSIZE + 1024, 16 * 1024)
OST_BUFSIZE = max_reqsize + max sptlrpc payload size.
Definition at line 497 of file lustre_net.h.
Referenced by ost_setup().
#define OST_IO_BUFSIZE max_t(int, OST_IO_MAXREQSIZE + 1024, 64 * 1024)
OST_IO_MAXREQSIZE is 18K, giving extra 46K can increase buffer utilization rate of request buffer, please check comment of MDS_LOV_BUFSIZE for details.
Definition at line 502 of file lustre_net.h.
Referenced by ost_setup().
#define OST_IO_MAXREPSIZE OST_MAXREPSIZE
Definition at line 493 of file lustre_net.h.
Referenced by ost_setup().
#define OST_IO_MAXREQSIZE
Value:
max_t(int, OST_MAXREQSIZE, \
                                (((_OST_MAXREQSIZE_SUM - 1) | (1024 - 1)) + 1))
Definition at line 489 of file lustre_net.h.
Referenced by osc_init(), and ost_setup().
#define OST_MAXREPSIZE (9 * 1024)
Definition at line 492 of file lustre_net.h.
Referenced by ost_setup().
#define OST_MAXREQSIZE (16 * 1024)
FIEMAP request can be 4K+ for now.
Definition at line 488 of file lustre_net.h.
Referenced by ost_setup().
#define OST_NBUFS 64
Definition at line 495 of file lustre_net.h.
Referenced by ost_setup().
#define OUT_BUFSIZE
Value:
max(OUT_MAXREQSIZE + SPTLRPC_MAX_PAYLOAD, \
                                    24 * 1024)
OUT_BUFSIZE = max_out_reqsize + max sptlrpc payload (~1K) which is about 10K, for the same reason as MDS_REG_BUFSIZE, we also give some extra bytes to each request buffer to improve buffer utilization rate.
Definition at line 406 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service(), and ost_setup().
#define OUT_MAXREPSIZE MDS_MAXREPSIZE
Definition at line 376 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service(), and ost_setup().
#define OUT_MAXREQSIZE (1000 * 1024)
The update request includes all of updates from the create, which might include linkea (4K maxim), together with other updates, we set it to 1000K: lustre_msg + ptlrpc_body + OUT_UPDATE_BUFFER_SIZE_MAX.
Definition at line 375 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service(), ost_setup(), and out_handle().
#define PTL_RPC_FL_INTR (1 << 0)
state flags of requests
Definition at line 540 of file lustre_net.h.
#define PTL_RPC_FL_TIMEOUT (1 << 7)
Definition at line 541 of file lustre_net.h.
#define PTLRPC_BULK_OPS_BITS 4
log2 max # of bulk operations in one request: 2=4MB/RPC, 5=32MB/RPC, .
.. In order for the client and server to properly negotiate the maximum possible transfer size, PTLRPC_BULK_OPS_COUNT must be a power-of-two value. The client is free to limit the actual RPC size for any bulk transfer via cl_max_pages_per_rpc to some non-power-of-two value. NOTE: This is limited to 16 (=64GB RPCs) by IOOBJ_MAX_BRW_BITS.
Definition at line 82 of file lustre_net.h.
#define PTLRPC_BULK_OPS_COUNT (1U << PTLRPC_BULK_OPS_BITS)
Definition at line 86 of file lustre_net.h.
Referenced by out_handle(), ptlrpc_init_xid(), ptlrpc_new_bulk(), ptlrpc_next_xid(), ptlrpc_register_bulk(), and ptlrpc_sample_next_xid().
#define PTLRPC_BULK_OPS_MASK (~((__u64)PTLRPC_BULK_OPS_COUNT - 1))
PTLRPC_BULK_OPS_MASK is for the convenience of the client only, and should not be used on the server at all.
Otherwise, it imposes a protocol limitation on the maximum RPC size that can be used by any RPC sent to that server in the future. Instead, the server should use the negotiated per-client ocd_brw_size to determine the bulk RPC count.
Definition at line 94 of file lustre_net.h.
Referenced by ptlrpc_init_xid(), and ptlrpc_register_bulk().
#define PTLRPC_MAX_BRW_BITS (LNET_MTU_BITS + PTLRPC_BULK_OPS_BITS)
Define maxima for bulk I/O.
A single PTLRPC BRW request is sent via up to PTLRPC_BULK_OPS_COUNT of LNET_MTU sized RDMA transfers. Clients and servers negotiate the currently supported maximum between peers at connect via ocd_brw_size.
Definition at line 103 of file lustre_net.h.
Referenced by ll_update_inode().
#define PTLRPC_MAX_BRW_PAGES (PTLRPC_MAX_BRW_SIZE >> PAGE_CACHE_SHIFT)
Definition at line 105 of file lustre_net.h.
Referenced by __osd_init_iobuf(), client_obd_setup(), enc_pools_add_pages(), enc_pools_shrink_count(), enc_pools_shrink_scan(), ll_ra_count_get(), ll_readahead_init(), ll_write_end(), mdc_read_page_remote(), mgs_get_ir_logs(), ofd_preprw(), ofd_preprw_read(), ofd_preprw_write(), osd_bufs_get_write(), ptlrpc_connect_set_flags(), ptlrpc_fill_bulk_md(), ptlrpc_register_bulk(), sptlrpc_enc_pool_add_user(), tgt_brw_read(), tgt_brw_write(), and tgt_io_data_unpack().
#define PTLRPC_MAX_BRW_SIZE (1 << PTLRPC_MAX_BRW_BITS)
Definition at line 104 of file lustre_net.h.
Referenced by echo_client_brw_ioctl().
#define PTLRPC_MD_OPTIONS 0
Definition at line 73 of file lustre_net.h.
Referenced by ptl_send_buf(), ptl_send_rpc(), ptlrpc_register_bulk(), and ptlrpc_register_rqbd().
#define PTLRPC_NTHRS_INIT 2
Definition at line 128 of file lustre_net.h.
Referenced by ptlrpc_server_allow_high(), ptlrpc_server_allow_normal(), ptlrpc_server_nthreads_check(), and ptlrpc_start_threads().
#define PTLRPC_REPLY_EARLY 0x02
Definition at line 2066 of file lustre_net.h.
Referenced by ptlrpc_at_send_early_reply(), and ptlrpc_at_set_reply().
#define PTLRPC_REPLY_MAYBE_DIFFICULT 0x01
Definition at line 2065 of file lustre_net.h.
Referenced by ptlrpc_send_reply(), and target_send_reply_msg().
#define ptlrpc_req_async_args (req) ((void *)&req->rq_async_args)
Definition at line 505 of file lustre_net.h.
Referenced by lfsck_async_request(), lfsck_layout_async_query(), mdc_intent_getattr_async(), osc_brw_prep_request(), osc_brw_redo_request(), osc_build_rpc(), osc_enqueue_base(), osc_io_data_version_start(), osc_ladvise_base(), osc_punch_base(), osc_set_info_async(), osc_setattr_async(), osc_statfs_async(), osc_sync_base(), osp_send_update_req(), osp_statfs_interpret(), osp_statfs_update(), osp_sync_request_commit_cb(), osp_sync_send_new_rpc(), osp_unplug_async_request(), ptlrpc_connect_import(), ptlrpc_replay_req(), ptlrpcd_alloc_work(), qsd_intent_lock(), qsd_send_dqacq(), and replay_one_lock().
#define ptlrpc_service_for_each_part (part, i, svc)
Value:
for (i = 0;                                                     \
             i < (svc)->srv_ncpts &&                                    \
             (svc)->srv_parts != NULL &&                                \
             ((part) = (svc)->srv_parts[i]) != NULL; i++)
Definition at line 1857 of file lustre_net.h.
Referenced by nrs_policy_unregister_locked(), ptlrpc_nrs_policy_control(), ptlrpc_nrs_policy_register(), ptlrpc_service_del_atimer(), ptlrpc_service_free(), ptlrpc_service_health_check(), ptlrpc_service_nrs_cleanup(), ptlrpc_service_nrs_setup(), ptlrpc_service_purge_all(), ptlrpc_service_unlink_rqbd(), and ptlrpc_stop_all_threads().
#define PTLRPC_SVC_HP_RATIO 10
How many high priority requests to serve before serving one normal priority request.
Definition at line 1661 of file lustre_net.h.
Referenced by ptlrpc_register_service().
#define PTLRPC_THR_NAME_LEN 32
Definition at line 1502 of file lustre_net.h.
Referenced by ptlrpc_start_thread().
#define REQ_FLAGS_FMT "%s:%s%s%s%s%s%s%s%s%s%s%s%s"
Definition at line 1278 of file lustre_net.h.
Referenced by _debug_req().
#define REQ_MAX_ACK_LOCKS 8
Definition at line 543 of file lustre_net.h.
#define rq_arrival_time rq_srv.sr_arrival_time
Definition at line 940 of file lustre_net.h.
#define rq_async_args rq_cli.cr_async_args
Definition at line 873 of file lustre_net.h.
Referenced by osp_sync_inflight_conflict(), and osp_sync_process_committed().
#define rq_at_index rq_srv.sr_at_index
Definition at line 934 of file lustre_net.h.
#define rq_auth_mapped_uid rq_srv.sr_auth_mapped_uid
Definition at line 936 of file lustre_net.h.
#define rq_auth_uid rq_srv.sr_auth_uid
Definition at line 935 of file lustre_net.h.
#define rq_bulk rq_cli.cr_bulk
client request member alias
Definition at line 849 of file lustre_net.h.
#define rq_bulk_deadline rq_cli.cr_bulk_deadline
Definition at line 855 of file lustre_net.h.
#define rq_cb_data rq_cli.cr_cb_data
Definition at line 874 of file lustre_net.h.
#define rq_cli_ctx rq_cli.cr_cli_ctx
Definition at line 865 of file lustre_net.h.
#define rq_commit_cb rq_cli.cr_commit_cb
Definition at line 876 of file lustre_net.h.
#define rq_ctx_chain rq_cli.cr_ctx_chain
Definition at line 862 of file lustre_net.h.
Referenced by sptlrpc_cli_ctx_wakeup().
#define rq_delay_limit rq_cli.cr_delay_limit
Definition at line 850 of file lustre_net.h.
#define rq_exp_list rq_srv.sr_exp_list
Definition at line 931 of file lustre_net.h.
Referenced by ptlrpc_server_check_resend_in_progress().
#define rq_history_list rq_srv.sr_hist_list
Definition at line 932 of file lustre_net.h.
#define rq_history_seq rq_srv.sr_hist_seq
Definition at line 933 of file lustre_net.h.
#define rq_import_generation rq_cli.cr_imp_gen
Definition at line 859 of file lustre_net.h.
#define rq_interpret_reply rq_cli.cr_reply_interp
Definition at line 871 of file lustre_net.h.
#define rq_nr_resend rq_cli.cr_resend_nr
Definition at line 856 of file lustre_net.h.
#define rq_nrq rq_srv.sr_nrq
Definition at line 939 of file lustre_net.h.
Referenced by nrs_fifo_req_get(), nrs_fifo_req_stop(), and ptlrpc_nrs_req_get_nolock0().
#define rq_ops rq_srv.sr_ops
Definition at line 944 of file lustre_net.h.
#define rq_queued_time rq_cli.cr_queued_time
Definition at line 851 of file lustre_net.h.
#define rq_real_sent rq_cli.cr_sent_out
Definition at line 853 of file lustre_net.h.
#define rq_replay_cb rq_cli.cr_replay_cb
Definition at line 877 of file lustre_net.h.
#define rq_reply_cbid rq_cli.cr_reply_cbid
Definition at line 870 of file lustre_net.h.
#define rq_reply_deadline rq_cli.cr_reply_deadline
Definition at line 854 of file lustre_net.h.
#define rq_reply_md_h rq_cli.cr_reply_md_h
Definition at line 868 of file lustre_net.h.
#define rq_reply_portal rq_cli.cr_rep_ptl
Definition at line 858 of file lustre_net.h.
#define rq_reply_state rq_srv.sr_reply_state
Definition at line 941 of file lustre_net.h.
#define rq_reply_waitq rq_cli.cr_reply_waitq
Definition at line 869 of file lustre_net.h.
#define rq_req_cbid rq_cli.cr_req_cbid
Definition at line 867 of file lustre_net.h.
#define rq_req_md_h rq_cli.cr_req_md_h
Definition at line 866 of file lustre_net.h.
#define rq_request_portal rq_cli.cr_req_ptl
Definition at line 857 of file lustre_net.h.
#define rq_resend_cb rq_cli.cr_resend_cb
Definition at line 872 of file lustre_net.h.
#define rq_rqbd rq_srv.sr_rqbd
Definition at line 945 of file lustre_net.h.
#define rq_send_state rq_cli.cr_send_state
Definition at line 860 of file lustre_net.h.
#define rq_sent_tv rq_cli.cr_sent_tv
Definition at line 852 of file lustre_net.h.
#define rq_session rq_srv.sr_ses
Definition at line 938 of file lustre_net.h.
#define rq_set rq_cli.cr_set
Definition at line 863 of file lustre_net.h.
#define rq_set_chain rq_cli.cr_set_chain
Definition at line 861 of file lustre_net.h.
Referenced by ptlrpc_abort_set(), ptlrpc_check_set(), ptlrpc_expired_set(), ptlrpc_interrupted_set(), ptlrpc_set_destroy(), ptlrpc_set_next_timeout(), ptlrpc_set_wait(), ptlrpcd_add_rqset(), ptlrpcd_check(), and ptlrpcd_steal_rqset().
#define rq_set_waitq rq_cli.cr_set_waitq
Definition at line 864 of file lustre_net.h.
#define rq_sp_from rq_srv.sr_sp_from
Definition at line 937 of file lustre_net.h.
#define rq_svc_ctx rq_srv.sr_svc_ctx
Definition at line 942 of file lustre_net.h.
#define rq_svc_thread rq_srv.sr_svc_thread
server request member alias
Definition at line 929 of file lustre_net.h.
#define rq_timed_list rq_srv.sr_timed_list
Definition at line 930 of file lustre_net.h.
Referenced by ptlrpc_at_add_timed(), and ptlrpc_at_check_timed().
#define rq_unreplied_list rq_cli.cr_unreplied_list
Definition at line 875 of file lustre_net.h.
Referenced by ptlrpc_add_unreplied(), and ptlrpc_known_replied_xid().
#define rq_user_desc rq_srv.sr_user_desc
Definition at line 943 of file lustre_net.h.
#define RS_DEBUG 0
Definition at line 640 of file lustre_net.h.
#define RS_MAX_LOCKS 8
Maximum number of locks to fit into reply state.
Definition at line 639 of file lustre_net.h.
Referenced by ptlrpc_save_lock().
#define SEQ_BUFSIZE (1 << 12)
Definition at line 423 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service().
#define SEQ_MAXREPSIZE (152)
SEQ_MAXREPSIZE == lustre_msg + ptlrpc_body + lu_range.
Definition at line 422 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service().
#define SEQ_MAXREQSIZE (160)
SEQ_MAXREQSIZE == lustre_msg + __u32 padding + ptlrpc_body + opc + lu_range + __u32 padding.
Definition at line 419 of file lustre_net.h.
Referenced by mds_start_ptlrpc_service().
Typedef Documentation
typedef int(* ptlrpc_interpterer_t)(const struct lu_env *env, struct ptlrpc_request *req, void *arg, int rc)
Type of request interpreter call-back.
Definition at line 727 of file lustre_net.h.
typedef void(* ptlrpc_resend_cb_t)(struct ptlrpc_request *req, void *arg)
Type of request resend call-back.
Definition at line 731 of file lustre_net.h.
typedef int(* set_interpreter_func)(struct ptlrpc_request_set *, void *, int)
Definition at line 558 of file lustre_net.h.
typedef int(* set_producer_func)(struct ptlrpc_request_set *, void *)
Definition at line 559 of file lustre_net.h.
typedef int(* svc_handler_t)(struct ptlrpc_request *req)
Definition at line 1624 of file lustre_net.h.
typedef int(* timeout_cb_t)(struct timeout_item *, void *)
Definition at line 2623 of file lustre_net.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
SVC_STOPPED
SVC_STOPPING
SVC_STARTING
SVC_RUNNING
SVC_EVENT
SVC_SIGNAL
Definition at line 1493 of file lustre_net.h.
enum ptlrpc_bulk_op_type
Enumerator:
PTLRPC_BULK_OP_ACTIVE
PTLRPC_BULK_OP_PASSIVE
PTLRPC_BULK_OP_PUT
PTLRPC_BULK_OP_GET
PTLRPC_BULK_BUF_KVEC
PTLRPC_BULK_BUF_KIOV
PTLRPC_BULK_GET_SOURCE
PTLRPC_BULK_PUT_SINK
PTLRPC_BULK_GET_SINK
PTLRPC_BULK_PUT_SOURCE
Definition at line 1331 of file lustre_net.h.
enum ptlrpcd_ctl_flags
Enumerator:
LIOD_START
Ptlrpc thread start flag.
LIOD_STOP
Ptlrpc thread stop flag.
LIOD_FORCE
Ptlrpc thread force flag (only stop force so far).
This will cause aborting any inflight rpcs handled by thread if LIOD_STOP is specified.
LIOD_RECOVERY
This is a recovery ptlrpc thread.
Definition at line 1922 of file lustre_net.h.
enum rq_phase
RPC stages.
Enumerator:
RQ_PHASE_NEW
RQ_PHASE_RPC
RQ_PHASE_BULK
RQ_PHASE_INTERPRET
RQ_PHASE_COMPLETE
RQ_PHASE_UNREGISTERING
RQ_PHASE_UNDEFINED
Definition at line 716 of file lustre_net.h.
enum timeout_event
Pinger API (client side only).
Enumerator:
TIMEOUT_GRANT
Definition at line 2619 of file lustre_net.h.
Function Documentation
int __lustre_unpack_msg (struct lustre_msg * m, int len)
Definition at line 574 of file pack_generic.c.
References CERROR, ENTRY, lustre_msg, lustre_unpack_msg_v2(), offsetof, and RETURN.
Referenced by do_cli_unwrap_reply(), gss_cli_ctx_unseal(), gss_svc_unseal_request(), ptlrpc_unpack_rep_msg(), ptlrpc_unpack_req_msg(), and sptlrpc_svc_unwrap_request().
void __ptlrpc_prep_bulk_page (struct ptlrpc_bulk_desc * desc, struct page * page, int pageoffset, int len, int pin)
Definition at line 205 of file client.c.
References BD_GET_KIOV, ptlrpc_bulk_desc::bd_iov_count, ptlrpc_bulk_desc::bd_max_iov, ptlrpc_bulk_desc::bd_nob, ptlrpc_bulk_desc::bd_type, lnet_kiov_t::kiov_len, lnet_kiov_t::kiov_offset, lnet_kiov_t::kiov_page, LASSERT, and ptlrpc_is_bulk_desc_kiov().
Referenced by ptlrpc_prep_bulk_page_nopin(), and ptlrpc_prep_bulk_page_pin().
void _debug_req (struct ptlrpc_request * req, struct libcfs_debug_msg_data * data, const char * fmt, ...)
void client_bulk_callback (lnet_event_t * ev)
Definition at line 181 of file events.c.
References ptlrpc_bulk_desc::bd_failure, ptlrpc_bulk_desc::bd_lock, ptlrpc_bulk_desc::bd_md_count, ptlrpc_bulk_desc::bd_nob_transferred, ptlrpc_bulk_desc::bd_req, ptlrpc_bulk_desc::bd_sender, ptlrpc_bulk_desc::bd_type, ptlrpc_cb_id::cbid_arg, CDEBUG, CFS_FAIL_CHECK_ORSET, CFS_FAIL_ONCE, D_ERROR, D_NET, ENTRY, EXIT, LASSERT, LNET_EVENT_GET, LNET_EVENT_PUT, LNET_EVENT_UNLINK, lnet_event_t::md, lnet_event_t::mlength, OBD_FAIL_PTLRPC_CLIENT_BULK_CB, OBD_FAIL_PTLRPC_CLIENT_BULK_CB2, ptlrpc_client_wake_req(), ptlrpc_is_bulk_get_source(), ptlrpc_is_bulk_put_sink(), ptlrpc_request::rq_lock, ptlrpc_request::rq_net_err, lnet_event_t::sender, lnet_event_t::status, lnet_event_t::type, lnet_event_t::unlinked, and lnet_md_t::user_ptr.
Referenced by ptlrpc_master_callback(), ptlrpc_prep_bulk_imp(), and ptlrpc_register_bulk().
int client_connect_import (const struct lu_env * env, struct obd_export ** exp, struct obd_device * obd, struct obd_uuid * cluuid, struct obd_connect_data * , void * localdata)
Definition at line 527 of file ldlm_lib.c.
References client_obd::cl_conn_count, client_obd::cl_import, client_obd::cl_sem, class_conn2export(), class_connect(), class_disconnect(), obd_device::cli, ENTRY, EXIT, obd_export::exp_connection, GOTO, obd_import::imp_connect_data, obd_import::imp_connect_flags_orig, obd_import::imp_dlm_handle, obd_import::imp_obd, obd_import::imp_state, LASSERT, LASSERTF, LPX64, LUSTRE_IMP_DISCON, LUSTRE_MDC_NAME, OBD_CONNECT_MULTIMODRPCS, obd_device::obd_namespace, obd_device::obd_type, obd_connect_data::ocd_connect_flags, ptlrpc_connect_import(), ptlrpc_init_import(), ptlrpc_pinger_add_import(), obd_type::typ_name, and obd_device::u.
void client_destroy_import (struct obd_import * imp)
Definition at line 220 of file ldlm_lib.c.
References class_destroy_import(), class_import_get(), class_import_put(), and sptlrpc_import_sec_put().
Referenced by obd_cleanup_client_import().
int client_disconnect_export (struct obd_export * exp)
Definition at line 604 of file ldlm_lib.c.
References CDEBUG, CERROR, client_obd::cl_conn_count, client_obd::cl_import, client_obd::cl_sem, class_disconnect(), class_exp2obd(), obd_device::cli, D_INFO, ENTRY, EXIT, obd_export::exp_handle, GOTO, portals_handle::h_cookie, obd_import::imp_deactive, obd_import::imp_lock, LCF_LOCAL, ldlm_cli_cancel_unused(), ldlm_namespace_free_prior(), LPX64, obd_device::obd_force, obd_device::obd_name, obd_device::obd_namespace, ptlrpc_disconnect_import(), ptlrpc_invalidate_import(), ptlrpc_pinger_del_import(), RETURN, and obd_device::u.
Referenced by osc_disconnect().
int client_import_add_conn (struct obd_import * imp, struct obd_uuid * uuid, int priority)
Definition at line 133 of file ldlm_lib.c.
References import_set_conn().
Referenced by client_obd_setup().
int client_import_del_conn (struct obd_import * imp, struct obd_uuid * uuid)
Definition at line 140 of file ldlm_lib.c.
References CDEBUG, CERROR, class_conn2export(), D_HA, ENTRY, obd_export::exp_connection, GOTO, obd_import::imp_conn_current, obd_import::imp_conn_list, obd_import::imp_connection, obd_import::imp_dlm_handle, obd_import::imp_lock, obd_import::imp_obd, obd_import::imp_state, LASSERT, list_del(), list_empty(), list_for_each_entry, LUSTRE_IMP_CLOSED, LUSTRE_IMP_DISCON, OBD_FREE, obd_device::obd_name, obd_uuid_equals(), obd_import_conn::oic_conn, obd_import_conn::oic_item, obd_import_conn::oic_uuid, ptlrpc_connection_put(), RETURN, and obd_uuid::uuid.
int client_import_find_conn (struct obd_import * imp, lnet_nid_t peer, struct obd_uuid * uuid)
Find conn UUID by peer NID.
peer is a server NID. This function is used to find a conn uuid of imp which can reach peer.
Definition at line 199 of file ldlm_lib.c.
References class_check_uuid(), ENTRY, obd_import::imp_conn_list, obd_import::imp_lock, list_for_each_entry, obd_import_conn::oic_item, obd_import_conn::oic_uuid, and RETURN.
Referenced by mgc_apply_recover_logs().
int client_obd_cleanup (struct obd_device * obddev)
Definition at line 504 of file ldlm_lib.c.
References client_obd::cl_import, client_obd::cl_mod_tag_bitmap, obd_device::cli, ENTRY, LASSERT, ldlm_namespace_free_post(), ldlm_put_ref(), obd_cleanup_client_import(), OBD_FREE, OBD_MAX_RIF_MAX, obd_device::obd_namespace, RETURN, and obd_device::u.
Referenced by lwp_device_fini(), lwp_setup(), mdc_cleanup(), mgc_cleanup(), mgc_setup(), osc_cleanup(), osc_setup(), osp_device_fini(), and osp_init0().
int client_obd_setup (struct obd_device * obddev, struct lustre_cfg * lcfg)
Target client logic.
Definition at line 261 of file ldlm_lib.c.
References CDEBUG, CERROR, client_obd::cl_avail_grant, client_obd::cl_cache_waiters, client_obd::cl_checksum, client_obd::cl_chunkbits, client_obd::cl_cksum_type, client_obd::cl_close_rpcs_in_flight, client_obd::cl_conn_count, client_obd::cl_destroy_in_flight, client_obd::cl_destroy_waitq, client_obd::cl_dirty_pages, client_obd::cl_flvr_mgc, client_obd::cl_import, client_obd::cl_loi_hp_ready_list, client_obd::cl_loi_list_lock, client_obd::cl_loi_read_list, client_obd::cl_loi_ready_list, client_obd::cl_loi_write_list, client_obd::cl_lru_busy, client_obd::cl_lru_in_list, client_obd::cl_lru_list, client_obd::cl_lru_list_lock, client_obd::cl_lru_osc, client_obd::cl_lru_shrinkers, client_obd::cl_max_mds_easize, client_obd::cl_max_mod_rpcs_in_flight, client_obd::cl_max_pages_per_rpc, client_obd::cl_max_rpcs_in_flight, client_obd::cl_mgc_mutex, client_obd::cl_mod_rpcs_hist, client_obd::cl_mod_rpcs_in_flight, client_obd::cl_mod_rpcs_lock, client_obd::cl_mod_rpcs_waitq, client_obd::cl_mod_tag_bitmap, client_obd::cl_pending_r_pages, client_obd::cl_pending_w_pages, client_obd::cl_r_in_flight, client_obd::cl_read_offset_hist, client_obd::cl_read_page_hist, client_obd::cl_read_rpc_hist, client_obd::cl_resends, client_obd::cl_sem, client_obd::cl_shrink_list, client_obd::cl_sp_me, client_obd::cl_sp_to, client_obd::cl_supp_cksum_types, client_obd::cl_target_uuid, client_obd::cl_unstable_count, client_obd::cl_w_in_flight, client_obd::cl_write_offset_hist, client_obd::cl_write_page_hist, client_obd::cl_write_rpc_hist, class_destroy_import(), class_import_put(), class_new_import(), obd_device::cli, cli_name(), client_adjust_max_dirty(), client_import_add_conn(), D_HA, ENTRY, GOTO, obd_import::imp_client, obd_import::imp_connect_op, obd_import::imp_deactive, obd_import::imp_lock, INIT_LIST_HEAD, is_lwp_on_mdt(), is_lwp_on_ost(), ldlm_get_ref(), LDLM_NAMESPACE_CLIENT, LDLM_NAMESPACE_GREEDY, ldlm_namespace_new(), LDLM_NS_TYPE_MDC, LDLM_NS_TYPE_MGC, LDLM_NS_TYPE_OSC, LDLM_NS_TYPE_UNKNOWN, ldlm_put_ref(), lustre_cfg_buf(), LUSTRE_CFG_BUFLEN, lustre_cfg_string(), LUSTRE_LWP_NAME, LUSTRE_MDC_NAME, LUSTRE_MGC_NAME, LUSTRE_OSC_NAME, LUSTRE_OSP_NAME, LUSTRE_SP_CLI, LUSTRE_SP_MDT, LUSTRE_SP_MGC, LUSTRE_SP_MGS, LUSTRE_SP_OST, MDC_REPLY_PORTAL, MDS_CONNECT, MDS_REQUEST_PORTAL, MGC_REPLY_PORTAL, MGS_CONNECT, MGS_REQUEST_PORTAL, min_t, name, OBD_ALLOC, OBD_CKSUM_CRC32, OBD_FREE, obd_device::obd_ldlm_client, OBD_MAX_RIF_DEFAULT, OBD_MAX_RIF_MAX, obd_device::obd_name, obd_device::obd_namespace, obd_device::obd_type, obd_histogram::oh_lock, OSC_DEFAULT_RESENDS, osc_on_mdt(), OSC_REPLY_PORTAL, OST_CONNECT, OST_REQUEST_PORTAL, OUT_PORTAL, ptlrpc_init_client(), PTLRPC_MAX_BRW_PAGES, RETURN, sptlrpc_flavor::sf_rpc, SPTLRPC_FLVR_INVALID, obd_type::typ_name, obd_device::u, and obd_uuid::uuid.
Referenced by lwp_setup(), mdc_setup(), mgc_setup(), osc_setup(), and osp_init0().
void deuuidify (char * uuid, const char * prefix, char ** uuid_start, int * uuid_len)
Definition at line 137 of file import.c.
References UUID_STR.
Referenced by import_select_connection(), ptlrpc_import_recovery_state_machine(), and ptlrpc_set_import_discon().
int import_set_conn_priority (struct obd_import * imp, struct obd_uuid * uuid)
Definition at line 128 of file ldlm_lib.c.
References import_set_conn().
Referenced by ptlrpc_recover_import().
int liblustre_check_services (void * arg)
const char* ll_opcode2str (__u32 opcode)
procfs output related functions
Definition at line 163 of file lproc_ptlrpc.c.
References LASSERTF, ll_rpc_opcode_table, LUSTRE_MAX_OPCODES, opcode_offset(), and ll_rpc_opcode::opname.
Referenced by ptlrpc_check_status().
int llog_origin_handle_close (struct ptlrpc_request * req)
Definition at line 332 of file llog_server.c.
References ENTRY, err_serious(), req_capsule_server_pack(), RETURN, and ptlrpc_request::rq_pill.
Referenced by ldlm_callback_handler(), and tgt_llog_close().
int llog_origin_handle_destroy (struct ptlrpc_request * req)
Definition at line 118 of file llog_server.c.
References CDEBUG, CERROR, D_WARNING, ENTRY, err_serious(), obd_export::exp_obd, llogd_body::lgd_ctxt_idx, llogd_body::lgd_llh_flags, llogd_body::lgd_logid, llog_logid::lgl_oi, llog_ctxt_put(), llog_erase(), LLOG_F_IS_PLAIN, llog_get_context(), LLOG_MAX_CTXTS, obd_device::obd_name, ostid_id(), req_capsule_client_get(), req_capsule_server_pack(), RETURN, RMF_LLOGD_BODY, ptlrpc_request::rq_export, and ptlrpc_request::rq_pill.
Referenced by tgt_llog_destroy().
int llog_origin_handle_next_block (struct ptlrpc_request * req)
Definition at line 157 of file llog_server.c.
References CDEBUG, D_WARNING, ENTRY, err_serious(), EXIT, obd_export::exp_obd, GOTO, llogd_body::lgd_ctxt_idx, llogd_body::lgd_cur_offset, llogd_body::lgd_index, llogd_body::lgd_llh_flags, llogd_body::lgd_logid, llogd_body::lgd_saved_index, llog_ctxt_put(), llog_get_context(), llog_init_handle(), LLOG_MAX_CTXTS, LLOG_MIN_CHUNK_SIZE, llog_next_block(), llog_open(), LLOG_OPEN_EXISTS, llog_origin_close(), obd_device::obd_name, RCL_SERVER, req_capsule_client_get(), req_capsule_server_get(), req_capsule_server_pack(), req_capsule_set_size(), RETURN, RMF_EADATA, RMF_LLOGD_BODY, ptlrpc_request::rq_export, and ptlrpc_request::rq_pill.
Referenced by ldlm_callback_handler(), and tgt_llog_next_block().
int llog_origin_handle_open (struct ptlrpc_request * req)
Definition at line 59 of file llog_server.c.
References CDEBUG, D_INFO, D_WARNING, ENTRY, err_serious(), EXIT, obd_export::exp_obd, GOTO, llogd_body::lgd_ctxt_idx, llogd_body::lgd_logid, llog_handle::lgh_id, llog_logid::lgl_oi, llog_ctxt_put(), llog_get_context(), LLOG_MAX_CTXTS, llog_open(), LLOG_OPEN_EXISTS, llog_origin_close(), name, obd_device::obd_name, obd_device::obd_olg, ostid_id(), RCL_CLIENT, req_capsule_client_get(), req_capsule_field_present(), req_capsule_server_get(), req_capsule_server_pack(), RETURN, RMF_LLOGD_BODY, RMF_NAME, ptlrpc_request::rq_export, and ptlrpc_request::rq_pill.
Referenced by ldlm_callback_handler(), and tgt_llog_open().
int llog_origin_handle_prev_block (struct ptlrpc_request * req)
Definition at line 218 of file llog_server.c.
References CDEBUG, D_WARNING, ENTRY, err_serious(), EXIT, obd_export::exp_obd, GOTO, llogd_body::lgd_ctxt_idx, llogd_body::lgd_index, llogd_body::lgd_llh_flags, llogd_body::lgd_logid, llog_ctxt_put(), llog_get_context(), llog_init_handle(), LLOG_MAX_CTXTS, LLOG_MIN_CHUNK_SIZE, llog_open(), LLOG_OPEN_EXISTS, llog_origin_close(), llog_prev_block(), obd_device::obd_name, RCL_SERVER, req_capsule_client_get(), req_capsule_server_get(), req_capsule_server_pack(), req_capsule_set_size(), RETURN, RMF_EADATA, RMF_LLOGD_BODY, ptlrpc_request::rq_export, and ptlrpc_request::rq_pill.
Referenced by tgt_llog_prev_block().
int llog_origin_handle_read_header (struct ptlrpc_request * req)
Definition at line 278 of file llog_server.c.
References CDEBUG, D_WARNING, ENTRY, err_serious(), EXIT, obd_export::exp_obd, GOTO, llogd_body::lgd_ctxt_idx, llogd_body::lgd_llh_flags, llogd_body::lgd_logid, llog_handle::lgh_hdr, llog_log_hdr::llh_flags, llog_ctxt_put(), llog_get_context(), llog_init_handle(), LLOG_MAX_CTXTS, llog_open(), LLOG_OPEN_EXISTS, llog_origin_close(), obd_device::obd_name, req_capsule_client_get(), req_capsule_server_get(), req_capsule_server_pack(), RETURN, RMF_LLOG_LOG_HDR, RMF_LLOGD_BODY, ptlrpc_request::rq_export, and ptlrpc_request::rq_pill.
Referenced by ldlm_callback_handler(), and tgt_llog_read_header().
void lustre_free_reply_state (struct ptlrpc_reply_state * rs)
Definition at line 508 of file pack_generic.c.
References LASSERT, list_empty(), PTLRPC_RS_DEBUG_LRU_DEL, ptlrpc_reply_state::rs_difficult, ptlrpc_reply_state::rs_exp_list, ptlrpc_reply_state::rs_export, ptlrpc_reply_state::rs_handled, ptlrpc_reply_state::rs_nlocks, ptlrpc_reply_state::rs_obd_list, ptlrpc_reply_state::rs_on_net, ptlrpc_reply_state::rs_refcount, ptlrpc_reply_state::rs_scheduled, and sptlrpc_svc_free_rs().
Referenced by ptlrpc_rs_decref().
void lustre_init_msg_v2 (struct lustre_msg_v2 * msg, int count, __u32 * lens, char ** bufs)
Definition at line 192 of file pack_generic.c.
References lustre_msg_v2::lm_bufcount, lustre_msg_v2::lm_buflens, lustre_msg_v2::lm_magic, LOGL, lustre_msg_hdr_size_v2(), and LUSTRE_MSG_MAGIC_V2.
Referenced by gss_alloc_reqbuf_intg(), gss_alloc_reqbuf_priv(), gss_cli_ctx_seal(), gss_svc_alloc_rs(), gss_svc_seal(), lustre_pack_reply_v2(), lustre_pack_request_v2(), plain_alloc_reqbuf(), and plain_alloc_rs().
void lustre_msg_add_flags (struct lustre_msg * msg, __u32 flags)
Definition at line 848 of file pack_generic.c.
References LASSERTF, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by mdc_get_root(), ptl_send_rpc(), ptlrpc_replay_next(), ptlrpc_retain_replayable_request(), and signal_completed_replay().
void lustre_msg_add_op_flags (struct lustre_msg * msg, __u32 flags)
Definition at line 908 of file pack_generic.c.
References LASSERTF, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by mgs_connect(), and ptlrpc_connect_import().
void lustre_msg_add_version (struct lustre_msg * msg, __u32 version)
Definition at line 975 of file pack_generic.c.
References LASSERTF, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by lustre_pack_reply_v2(), lustre_pack_request_v2(), and ptlrpc_request_bufs_pack().
void* lustre_msg_buf (struct lustre_msg * m, __u32 n, __u32 minlen)
Definition at line 436 of file pack_generic.c.
References LASSERTF, lustre_msg_buf_v2(), and LUSTRE_MSG_MAGIC_V2.
Referenced by __req_capsule_get(), _sptlrpc_enlarge_msg_inplace(), bulk_sec_desc_unpack(), ctx_init_pack_request(), ctx_init_parse_reply(), gss_alloc_reqbuf_intg(), gss_alloc_reqbuf_priv(), gss_cli_ctx_seal(), gss_cli_ctx_unseal(), gss_cli_ctx_unwrap_bulk(), gss_cli_ctx_verify(), gss_cli_ctx_wrap_bulk(), gss_do_ctx_fini_rpc(), gss_enlarge_reqbuf_intg(), gss_enlarge_reqbuf_priv(), gss_pack_err_notify(), gss_sign_msg(), gss_svc_alloc_rs(), gss_svc_handle_destroy(), gss_svc_handle_init(), gss_svc_seal(), gss_svc_sign(), gss_svc_unseal_request(), gss_svc_upcall_handle_init(), gss_svc_verify_request(), gss_swab_header(), gss_unseal_msg(), gss_verify_msg(), ofd_intent_policy(), plain_accept(), plain_alloc_reqbuf(), plain_authorize(), plain_cli_unwrap_bulk(), plain_cli_wrap_bulk(), plain_ctx_sign(), plain_ctx_verify(), plain_enlarge_reqbuf(), plain_svc_unwrap_bulk(), plain_svc_wrap_bulk(), plain_unpack_bsd(), req_capsule_server_grow(), sptlrpc_pack_user_desc(), and sptlrpc_unpack_user_desc().
void* lustre_msg_buf_v2 (struct lustre_msg_v2 * m, __u32 n, __u32 min_size)
Definition at line 408 of file pack_generic.c.
References CDEBUG, CERROR, cfs_size_round(), D_INFO, LASSERT, lustre_msg_v2::lm_bufcount, lustre_msg_v2::lm_buflens, lustre_msg_get_opc(), lustre_msg_hdr_size_v2(), MSG_PTLRPC_BODY_OFF, and unlikely.
Referenced by __lustre_swab_buf(), lustre_msg_buf(), lustre_msg_get_jobid(), lustre_msg_ptlrpc_body(), lustre_msg_set_jobid(), lustre_msg_string(), lustre_shrink_msg_v2(), lustre_unpack_ptlrpc_body_v2(), and plain_alloc_rs().
__u32 lustre_msg_bufcount (struct lustre_msg * m)
Definition at line 722 of file pack_generic.c.
References CERROR, and LUSTRE_MSG_MAGIC_V2.
Referenced by __req_capsule_get(), and req_capsule_field_present().
__u32 lustre_msg_buflen (struct lustre_msg * m, __u32 n)
lustre_msg_buflen - return the length of buffer n in message m
Parameters:
m lustre_msg (request or reply) to look at
n message index (base 0)
returns zero for non-existent message indices
Definition at line 688 of file pack_generic.c.
References CERROR, lustre_msg_buflen_v2(), and LUSTRE_MSG_MAGIC_V2.
Referenced by __req_capsule_get(), gss_cli_ctx_seal(), gss_cli_ctx_unwrap_bulk(), gss_cli_ctx_verify(), gss_cli_ctx_wrap_bulk(), gss_svc_alloc_rs(), gss_svc_handle_init(), gss_svc_seal(), gss_svc_sign(), gss_svc_unseal_request(), gss_svc_verify_request(), gss_unseal_msg(), lustre_msg_calc_cksum(), plain_authorize(), plain_ctx_verify(), plain_unpack_bsd(), req_capsule_get_size(), and req_capsule_shrink().
__u32 lustre_msg_calc_cksum (struct lustre_msg * msg)
Definition at line 1298 of file pack_generic.c.
References CERROR, cfs_crypto_hash_digest(), CFS_HASH_ALG_CRC32, LASSERTF, lustre_msg_buflen(), LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), MSG_PTLRPC_BODY_OFF, and ptlrpc_body.
Referenced by null_authorize(), and null_ctx_verify().
int lustre_msg_check_version (struct lustre_msg * msg, __u32 version)
Definition at line 104 of file pack_generic.c.
References CERROR, lustre_msg_check_version_v2(), LUSTRE_MSG_MAGIC_V1, and LUSTRE_MSG_MAGIC_V2.
Referenced by tgt_request_handle().
void lustre_msg_clear_flags (struct lustre_msg * msg, __u32 flags)
Definition at line 877 of file pack_generic.c.
References LASSERTF, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), MSG_GEN_FLAG_MASK, and ptlrpc_body.
Referenced by mdt_intent_fixup_resent(), and ptlrpc_retain_replayable_request().
__u32 lustre_msg_early_size (void)
Definition at line 121 of file pack_generic.c.
References LUSTRE_MSG_MAGIC_V2, lustre_msg_size(), and size.
Referenced by gss_init_at_reply_offset(), null_alloc_repbuf(), null_authorize(), and sptlrpc_plain_init().
__u32 lustre_msg_get_cksum (struct lustre_msg * msg)
Definition at line 1270 of file pack_generic.c.
References CERROR, and LUSTRE_MSG_MAGIC_V2.
Referenced by null_ctx_verify().
__u32 lustre_msg_get_conn_cnt (struct lustre_msg * msg)
Definition at line 1188 of file pack_generic.c.
References CERROR, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by mgs_connect(), ofd_create_hdl(), ptlrpc_check_req(), ptlrpc_expire_one_request(), and ptlrpc_request_handle_notconn().
__u32 lustre_msg_get_flags (struct lustre_msg * msg)
Definition at line 829 of file pack_generic.c.
References CERROR, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by _debug_req(), after_reply(), mdt_check_resent(), mdt_check_resent_lock(), mdt_finish_open(), mdt_getattr_name_lock(), mdt_intent_fixup_resent(), mdt_intent_lock_replace(), mdt_object_open_lock(), mdt_reint_open(), mdt_reint_unlink(), ofd_create_hdl(), out_check_resent(), process_req_last_xid(), ptl_send_rpc(), ptlrpc_at_adj_net_latency(), ptlrpc_at_send_early_reply(), ptlrpc_at_set_reply(), ptlrpc_check_req(), ptlrpc_replay_interpret(), ptlrpc_save_versions(), ptlrpc_server_check_resend_in_progress(), reply_in_callback(), req_is_replay(), seq_handler(), sptlrpc_req_refresh_ctx(), tgt_brw_write(), tgt_handle_recovery(), and tsi2ofd_info().
struct lustre_handle* lustre_msg_get_handle (struct lustre_msg * msg) [read]
Definition at line 923 of file pack_generic.c.
References CERROR, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by ptlrpc_at_send_early_reply(), ptlrpc_connect_interpret(), and ptlrpc_server_handle_req_in().
char* lustre_msg_get_jobid (struct lustre_msg * msg)
Definition at line 1251 of file pack_generic.c.
References CERROR, lustre_msg_buf_v2(), LUSTRE_MSG_MAGIC_V2, MSG_PTLRPC_BODY_OFF, and ptlrpc_body.
Referenced by mdt_counter_incr(), mdt_req_get_jobid(), and tgt_request_handle().
__u64 lustre_msg_get_last_committed (struct lustre_msg * msg)
Definition at line 1044 of file pack_generic.c.
References CERROR, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by after_reply(), mdc_get_root(), osp_request_commit_cb(), and ptlrpc_connect_interpret().
__u64 lustre_msg_get_last_xid (struct lustre_msg * msg)
Definition at line 1008 of file pack_generic.c.
References CERROR, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by process_req_last_xid().
__u32 lustre_msg_get_limit (struct lustre_msg * msg)
Definition at line 1152 of file pack_generic.c.
References CERROR, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by ldlm_cli_update_pool().
__u32 lustre_msg_get_magic (struct lustre_msg * msg)
Definition at line 1206 of file pack_generic.c.
References CERROR, and LUSTRE_MSG_MAGIC_V2.
Referenced by lustre_request_magic(), and ptlrpc_at_set_reply().
__u64 lustre_msg_get_mbits (struct lustre_msg * msg)
Definition at line 1281 of file pack_generic.c.
References CERROR, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
__u32 lustre_msg_get_op_flags (struct lustre_msg * msg)
Definition at line 892 of file pack_generic.c.
References CERROR, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by ptlrpc_connect_interpret().
__u32 lustre_msg_get_opc (struct lustre_msg * msg)
Definition at line 989 of file pack_generic.c.
References CERROR, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by _debug_req(), after_reply(), brw_interpret(), ldlm_callback_handler(), lustre_msg_buf_v2(), lustre_msg_set_jobid(), mdc_get_mod_rpc_slot(), mdc_put_mod_rpc_slot(), mdc_replay_open(), mdt_empty_transno(), mdt_getattr(), mdt_getattr_internal(), mdt_handle_idmap(), mdt_sec_ctx_handle(), mdt_steal_ack_locks(), ofd_rw_hpreq_lock_match(), osc_brw_fini_request(), osc_brw_redo_request(), osc_ldlm_glimpse_ast(), ptlrpc_check_set(), ptlrpc_check_status(), ptlrpc_console_allow(), ptlrpc_hpreq_handler(), ptlrpc_import_delay_req(), ptlrpc_nrs_hpreq_add_nolock(), ptlrpc_req_is_connect(), ptlrpc_req_is_disconnect(), ptlrpc_send_new_req(), ptlrpc_send_reply(), ptlrpc_server_handle_req_in(), ptlrpc_server_handle_request(), qsd_common_glimpse_ast(), req_can_reconstruct(), target_send_reply(), target_send_reply_msg(), tgt_filter_recovery_request(), tgt_handle_recovery(), tgt_handle_request0(), tgt_handler_find_check(), tgt_last_rcvd_update(), tgt_request_handle(), and tgt_request_preprocess().
__u32 lustre_msg_get_service_time (struct lustre_msg * msg)
Definition at line 1234 of file pack_generic.c.
References CERROR, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by after_reply(), ptlrpc_at_recv_early_reply(), and ptlrpc_connect_interpret().
__u64 lustre_msg_get_slv (struct lustre_msg * msg)
Definition at line 1116 of file pack_generic.c.
References CERROR, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by ldlm_cli_update_pool().
int lustre_msg_get_status (struct lustre_msg * msg)
Definition at line 1098 of file pack_generic.c.
References CERROR, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by _debug_req(), after_reply(), mdc_close(), mdt_close(), mdt_reint_internal(), ptlrpc_check_set(), ptlrpc_check_status(), ptlrpc_console_allow(), ptlrpc_replay_interpret(), ptlrpc_replay_req(), ptlrpc_send_new_req(), and ptlrpc_server_handle_request().
__u16 lustre_msg_get_tag (struct lustre_msg * msg)
Definition at line 1026 of file pack_generic.c.
References CERROR, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by mdc_put_mod_rpc_slot(), process_req_last_xid(), and tgt_last_rcvd_update().
__u32 lustre_msg_get_timeout (struct lustre_msg * msg)
Definition at line 1217 of file pack_generic.c.
References CERROR, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by after_reply(), ptlrpc_at_recv_early_reply(), and ptlrpc_server_handle_req_in().
__u64 lustre_msg_get_transno (struct lustre_msg * msg)
Definition at line 1080 of file pack_generic.c.
References CERROR, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by _debug_req(), after_reply(), mdt_empty_transno(), mdt_reconstruct_open(), mdt_thread_info_init(), osc_create(), ptlrpc_check_req(), ptlrpc_replay_interpret(), ptlrpc_server_handle_request(), and tgt_last_rcvd_update().
__u32 lustre_msg_get_type (struct lustre_msg * msg)
Definition at line 940 of file pack_generic.c.
References CERROR, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), PTL_RPC_MSG_ERR, and ptlrpc_body.
Referenced by after_reply(), mdc_close(), ptlrpc_check_status(), ptlrpc_replay_interpret(), and ptlrpc_server_handle_req_in().
__u32 lustre_msg_get_version (struct lustre_msg * msg)
Definition at line 958 of file pack_generic.c.
References CERROR, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by lustre_msg_check_version_v2(), and tgt_request_handle().
__u64* lustre_msg_get_versions (struct lustre_msg * msg)
Definition at line 1062 of file pack_generic.c.
References CERROR, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by mdt_empty_transno(), mdt_version_check(), mdt_version_save(), ptlrpc_save_versions(), tgt_last_rcvd_update(), and tsi2ofd_info().
__u32 lustre_msg_hdr_size (__u32 magic, __u32 count)
Definition at line 66 of file pack_generic.c.
References LASSERTF, lustre_msg_hdr_size_v2(), and LUSTRE_MSG_MAGIC_V2.
Referenced by req_capsule_fmt_size().
void lustre_msg_set_buflen (struct lustre_msg * m, __u32 n, __u32 len)
Definition at line 709 of file pack_generic.c.
References LASSERTF, LUSTRE_MSG_MAGIC_V2, and lustre_msg_set_buflen_v2().
void lustre_msg_set_cksum (struct lustre_msg * msg, __u32 cksum)
Definition at line 1525 of file pack_generic.c.
References LASSERTF, and LUSTRE_MSG_MAGIC_V2.
Referenced by null_authorize().
void lustre_msg_set_conn_cnt (struct lustre_msg * msg, __u32 conn_cnt)
Definition at line 1454 of file pack_generic.c.
References LASSERTF, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by ctx_refresh_timeout(), and ptl_send_rpc().
void lustre_msg_set_flags (struct lustre_msg * msg, __u32 flags)
Definition at line 863 of file pack_generic.c.
References LASSERTF, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by replay_one_lock().
void lustre_msg_set_handle (struct lustre_msg * msg, struct lustre_handle * handle)
Definition at line 1320 of file pack_generic.c.
References LASSERTF, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by ptl_send_rpc(), and ptlrpc_resend_req().
void lustre_msg_set_jobid (struct lustre_msg * msg, char * jobid)
Definition at line 1496 of file pack_generic.c.
References LASSERTF, LDLM_BL_CALLBACK, LDLM_CP_CALLBACK, LDLM_GL_CALLBACK, lustre_get_jobid(), LUSTRE_JOBID_SIZE, lustre_msg_buf_v2(), lustre_msg_get_opc(), LUSTRE_MSG_MAGIC_V2, MSG_PTLRPC_BODY_OFF, and ptlrpc_body.
Referenced by osc_build_rpc(), ptlrpc_set_add_req(), and ptlrpcd_add_req().
void lustre_msg_set_last_committed (struct lustre_msg * msg, __u64 last_committed)
Definition at line 1392 of file pack_generic.c.
References LASSERTF, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
void lustre_msg_set_last_xid (struct lustre_msg * msg, __u64 last_xid)
Definition at line 1362 of file pack_generic.c.
References LASSERTF, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by ptl_send_rpc(), and ptlrpc_send_new_req().
void lustre_msg_set_limit (struct lustre_msg * msg, __u64 limit)
Definition at line 1170 of file pack_generic.c.
References CERROR, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by target_pack_pool_reply().
void lustre_msg_set_mbits (struct lustre_msg * msg, __u64 mbits)
Definition at line 1536 of file pack_generic.c.
References LASSERTF, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by ptl_send_rpc().
void lustre_msg_set_opc (struct lustre_msg * msg, __u32 opc)
Definition at line 1348 of file pack_generic.c.
References LASSERTF, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by ptlrpc_request_bufs_pack(), and ptlrpc_send_reply().
void lustre_msg_set_service_time (struct lustre_msg * msg, __u32 service_time)
Definition at line 1482 of file pack_generic.c.
References LASSERTF, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by ptlrpc_at_set_reply(), ptlrpc_connect_import(), and ptlrpc_replay_req().
void lustre_msg_set_slv (struct lustre_msg * msg, __u64 slv)
Definition at line 1134 of file pack_generic.c.
References CERROR, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by target_pack_pool_reply().
void lustre_msg_set_status (struct lustre_msg * msg, __u32 status)
Definition at line 1439 of file pack_generic.c.
References LASSERTF, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by mdt_reconstruct_open(), mdt_req_from_lrd(), out_check_resent(), ptlrpc_queue_wait(), ptlrpc_replay_interpret(), ptlrpc_send_new_req(), and ptlrpc_send_reply().
void lustre_msg_set_tag (struct lustre_msg * msg, __u16 tag)
Definition at line 1377 of file pack_generic.c.
References LASSERTF, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by mdc_get_mod_rpc_slot().
void lustre_msg_set_timeout (struct lustre_msg * msg, __u32 timeout)
Definition at line 1468 of file pack_generic.c.
References LASSERTF, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by ptlrpc_at_recv_early_reply(), ptlrpc_at_set_reply(), ptlrpc_at_set_req_timeout(), and ptlrpc_connect_import().
void lustre_msg_set_transno (struct lustre_msg * msg, __u64 transno)
Definition at line 1424 of file pack_generic.c.
References LASSERTF, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by after_reply(), mdt_empty_transno(), mdt_finish_open(), mdt_fix_reply(), mdt_reint_open(), mdt_req_from_lrd(), out_check_resent(), and tgt_last_rcvd_update().
void lustre_msg_set_type (struct lustre_msg * msg, __u32 type)
Definition at line 1334 of file pack_generic.c.
References LASSERTF, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by ptl_send_rpc(), and ptlrpc_send_reply().
void lustre_msg_set_versions (struct lustre_msg * msg, __u64 * versions)
Definition at line 1406 of file pack_generic.c.
References LASSERTF, LUSTRE_MSG_MAGIC_V2, lustre_msg_ptlrpc_body(), and ptlrpc_body.
Referenced by mdt_req_from_lrd(), and ptlrpc_save_versions().
__u32 lustre_msg_size (__u32 magic, int count, __u32 * lengths)
Definition at line 158 of file pack_generic.c.
References LASSERT, LASSERTF, LUSTRE_MSG_MAGIC_V2, lustre_msg_size_v2(), MSG_PTLRPC_BODY_OFF, ptlrpc_body, and size.
Referenced by lustre_msg_early_size(), lustre_pack_reply_flags(), ptlrpc_req_set_repsize(), ptlrpc_request_set_replen(), and req_capsule_msg_size().
__u32 lustre_msg_size_v2 (int count, __u32 * lengths)
Definition at line 139 of file pack_generic.c.
References cfs_size_round(), lustre_msg_hdr_size_v2(), and size.
Referenced by _sptlrpc_enlarge_msg_inplace(), get_enlarged_msgsize(), get_enlarged_msgsize2(), gss_alloc_repbuf_intg(), gss_alloc_repbuf_priv(), gss_alloc_reqbuf_intg(), gss_alloc_reqbuf_priv(), gss_cli_ctx_seal(), gss_enlarge_reqbuf_priv(), gss_init_at_reply_offset(), gss_pack_err_notify(), gss_sign_msg(), gss_svc_alloc_rs(), gss_svc_seal(), lustre_msg_size(), lustre_pack_reply_v2(), lustre_pack_request_v2(), lustre_packed_msg_size(), lustre_shrink_msg_v2(), plain_alloc_repbuf(), plain_alloc_reqbuf(), plain_alloc_rs(), plain_authorize(), plain_ctx_sign(), plain_enlarge_reqbuf(), and sptlrpc_plain_init().
char* lustre_msg_string (struct lustre_msg * m, __u32 n, __u32 max_len)
Definition at line 733 of file pack_generic.c.
References CERROR, LASSERTF, lustre_msg_buf_v2(), lustre_msg_buflen_v2(), LUSTRE_MSG_MAGIC_V2, and strnlen.
Referenced by __req_capsule_get().
__u32 lustre_msghdr_get_flags (struct lustre_msg * msg)
Definition at line 805 of file pack_generic.c.
References CERROR, and LUSTRE_MSG_MAGIC_V2.
Referenced by gss_svc_seal(), gss_svc_sign(), null_authorize(), plain_authorize(), ptlrpc_at_add_timed(), ptlrpc_at_send_early_reply(), ptlrpc_at_set_reply(), ptlrpc_server_handle_req_in(), reply_in_callback(), and sptlrpc_cli_unwrap_reply().
void lustre_msghdr_set_flags (struct lustre_msg * msg, __u32 flags)
Definition at line 818 of file pack_generic.c.
References LASSERTF, and LUSTRE_MSG_MAGIC_V2.
Referenced by ptl_send_rpc().
int lustre_pack_reply (struct ptlrpc_request * , int count, __u32 * lens, char ** bufs)
Definition at line 401 of file pack_generic.c.
References lustre_pack_reply_flags().
Referenced by ldlm_callback_reply(), ofd_intent_policy(), osc_ldlm_glimpse_ast(), ptlrpc_send_error(), and req_capsule_server_pack().
int lustre_pack_reply_flags (struct ptlrpc_request * , int count, __u32 * lens, char ** bufs, int flags)
Definition at line 372 of file pack_generic.c.
References CERROR, LASSERT, LASSERTF, LUSTRE_MSG_MAGIC_V2, lustre_msg_size(), lustre_pack_reply_v2(), MSG_PTLRPC_BODY_OFF, ptlrpc_body, and ptlrpc_request::rq_reqmsg.
Referenced by lustre_pack_reply(), and ptlrpc_at_send_early_reply().
int lustre_pack_reply_v2 (struct ptlrpc_request * req, int count, __u32 * lens, char ** bufs, int flags)
Definition at line 329 of file pack_generic.c.
References ptlrpc_cb_id::cbid_arg, ptlrpc_cb_id::cbid_fn, ENTRY, INIT_LIST_HEAD, LASSERT, LPRFL_EARLY_REPLY, lustre_init_msg_v2(), lustre_msg_add_version(), lustre_msg_size_v2(), PTLRPC_MSG_VERSION, PTLRPC_RS_DEBUG_LRU_ADD, reply_out_callback(), RETURN, ptlrpc_request::rq_lock, ptlrpc_request::rq_packed_final, ptlrpc_request::rq_replen, ptlrpc_request::rq_repmsg, ptlrpc_reply_state::rs_cb_id, ptlrpc_reply_state::rs_exp_list, ptlrpc_reply_state::rs_list, ptlrpc_reply_state::rs_lock, ptlrpc_reply_state::rs_msg, ptlrpc_reply_state::rs_obd_list, ptlrpc_reply_state::rs_refcount, ptlrpc_reply_state::rs_svcpt, and sptlrpc_svc_alloc_rs().
Referenced by gss_pack_err_notify(), gss_svc_upcall_handle_init(), and lustre_pack_reply_flags().
int lustre_pack_request (struct ptlrpc_request * , __u32 magic, int count, __u32 * lens, char ** bufs)
Definition at line 234 of file pack_generic.c.
References LASSERT, LASSERTF, LIST_HEAD_INIT, LUSTRE_MSG_MAGIC_V2, lustre_pack_request_v2(), MSG_PTLRPC_BODY_OFF, and ptlrpc_body.
Referenced by ptlrpc_request_bufs_pack().
__u32 lustre_packed_msg_size (struct lustre_msg * msg)
Definition at line 181 of file pack_generic.c.
References CERROR, LUSTRE_MSG_MAGIC_V2, and lustre_msg_size_v2().
Referenced by null_enlarge_reqbuf(), and req_capsule_server_grow().
static int lustre_rep_swabbed (struct ptlrpc_request * req, size_t index) [inline, static]
Returns 1 if request reply buffer at offset index was already swabbed.
Definition at line 1181 of file lustre_net.h.
References LASSERT, and ptlrpc_request::rq_rep_swab_mask.
Referenced by ptlrpc_buf_need_swab(), ptlrpc_rep_need_swab(), and rep_ptlrpc_body_swabbed().
static int lustre_req_swabbed (struct ptlrpc_request * req, size_t index) [inline, static]
Returns 1 if request buffer at offset index was already swabbed.
Definition at line 1172 of file lustre_net.h.
References LASSERT, and ptlrpc_request::rq_req_swab_mask.
Referenced by ptlrpc_buf_need_swab(), ptlrpc_req_need_swab(), and req_ptlrpc_body_swabbed().
static __u32 lustre_request_magic (struct ptlrpc_request * req) [inline, static]
Definition at line 2535 of file lustre_net.h.
References lustre_msg_get_magic(), and ptlrpc_request::rq_reqmsg.
static void lustre_set_rep_swabbed (struct ptlrpc_request * req, size_t index) [inline, static]
Mark request reply buffer at offset index that it was already swabbed.
Definition at line 1217 of file lustre_net.h.
References LASSERT, and ptlrpc_request::rq_rep_swab_mask.
Referenced by do_cli_unwrap_reply(), ptlrpc_buf_set_swabbed(), and ptlrpc_unpack_rep_msg().
static void lustre_set_req_swabbed (struct ptlrpc_request * req, size_t index) [inline, static]
Mark request buffer at offset index that it was already swabbed.
Definition at line 1206 of file lustre_net.h.
References LASSERT, and ptlrpc_request::rq_req_swab_mask.
Referenced by ptlrpc_buf_set_swabbed(), ptlrpc_unpack_req_msg(), and sptlrpc_svc_unwrap_request().
int lustre_shrink_msg (struct lustre_msg * msg, int segment, unsigned int newlen, int move_data)
Definition at line 496 of file pack_generic.c.
References LASSERTF, LUSTRE_MSG_MAGIC_V2, and lustre_shrink_msg_v2().
Referenced by ctx_init_pack_request(), gss_cli_ctx_seal(), gss_sign_msg(), gss_svc_seal(), gss_svc_sign(), gss_svc_upcall_handle_init(), lustre_shrink_reply(), plain_authorize(), ptlrpc_send_reply(), and req_capsule_shrink().
static void lustre_shrink_reply (struct ptlrpc_request * req, int segment, unsigned int newlen, int move_data) [inline, static]
Definition at line 2384 of file lustre_net.h.
References LASSERT, lustre_shrink_msg(), ptlrpc_request::rq_replen, and ptlrpc_request::rq_repmsg.
void ping_evictor_start (void)
Definition at line 686 of file pinger.c.
References CERROR, INIT_LIST_HEAD, pet_list, pet_refcount, pet_waitq, and ping_evictor_main().
Referenced by mdt_init0(), mgs_init0(), and ost_setup().
void ping_evictor_stop (void)
Definition at line 705 of file pinger.c.
References pet_refcount, pet_state, PET_TERMINATE, and pet_waitq.
Referenced by mdt_fini(), mgs_device_fini(), and ost_cleanup().
lnet_pid_t ptl_get_pid (void)
Definition at line 578 of file events.c.
References LNET_PID_LUSTRE.
Referenced by ptlrpc_ni_init().
int ptl_send_rpc (struct ptlrpc_request * request, int noreply)
Send request request.
if noreply is set, don't expect any reply back and don't set up reply buffers. Returns 0 on success or error code.
For enabled AT all request should have AT_SUPPORT in the FULL import state when OBD_CONNECT_AT is set
Definition at line 660 of file niobuf.c.
References __u64, AT_OFF, ptlrpc_connection::c_peer, CDEBUG, CERROR, cfs_memory_pressure_get_and_set(), cfs_memory_pressure_restore(), cfs_time_current_sec(), D_ERROR, D_HA, D_INFO, D_NET, D_RPCTRACE, DEBUG_REQ, ENTRY, lnet_md_t::eq_handle, GOTO, obd_import::imp_conn_cnt, obd_import::imp_connect_data, obd_import::imp_connection, obd_import::imp_inflight, obd_import::imp_known_replied_xid, obd_import::imp_lock, obd_import::imp_msghdr_flags, obd_import::imp_obd, obd_import::imp_remote_handle, obd_import::imp_state, LASSERT, LBUG, lnet_md_t::length, likely, list_empty(), LNET_INS_AFTER, LNET_MD_MANAGE_REMOTE, LNET_MD_OP_PUT, LNET_MD_THRESH_INF, LNET_MD_TRUNCATE, LNET_NOACK_REQ, LNET_RETAIN, LNET_UNLINK, LNetMDAttach(), LNetMEAttach(), LNetMEUnlink(), lprocfs_counter_add(), LPU64, LUSTRE_IMP_FULL, lustre_msg_add_flags(), lustre_msg_get_flags(), lustre_msg_set_conn_cnt(), lustre_msg_set_handle(), lustre_msg_set_last_xid(), lustre_msg_set_mbits(), lustre_msg_set_type(), lustre_msghdr_set_flags(), MSG_REPLAY, MSG_RESENT, MSGHDR_AT_SUPPORT, OBD_CONNECT_AT, obd_device::obd_fail, OBD_FAIL_CHECK, OBD_FAIL_PTLRPC_DELAY_SEND, OBD_FAIL_PTLRPC_DROP_RPC, OBD_FAIL_TIMEOUT, obd_device::obd_name, obd_device::obd_svc_stats, obd_connect_data::ocd_connect_flags, lnet_md_t::options, PTL_RPC_MSG_REQUEST, ptl_send_buf(), ptlrpc_assign_next_xid_nolock(), ptlrpc_at_get_net_latency(), ptlrpc_eq_h, ptlrpc_known_replied_xid(), PTLRPC_MD_OPTIONS, ptlrpc_pinger_sending_on_import(), ptlrpc_register_bulk(), ptlrpc_req_finished(), PTLRPC_REQACTIVE_CNTR, ptlrpc_request_addref(), ptlrpc_set_bulk_mbits(), ptlrpc_unregister_bulk(), RETURN, ptlrpc_request::rq_deadline, ptlrpc_request::rq_err, ptlrpc_request::rq_import, ptlrpc_request::rq_lock, ptlrpc_request::rq_mbits, ptlrpc_request::rq_memalloc, ptlrpc_request::rq_net_err, ptlrpc_request::rq_receiving_reply, ptlrpc_request::rq_repbuf, ptlrpc_request::rq_repbuf_len, ptlrpc_request::rq_repdata, ptlrpc_request::rq_replen, ptlrpc_request::rq_replied, ptlrpc_request::rq_reply_truncated, ptlrpc_request::rq_reply_unlinked, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_req_unlinked, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqdata_len, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_resend, ptlrpc_request::rq_restart, ptlrpc_request::rq_sent, ptlrpc_request::rq_status, ptlrpc_request::rq_timedout, ptlrpc_request::rq_timeout, ptlrpc_request::rq_type, ptlrpc_request::rq_wait_ctx, ptlrpc_request::rq_xid, sptlrpc_cli_alloc_repbuf(), sptlrpc_cli_wrap_request(), lnet_md_t::start, lnet_md_t::threshold, unlikely, and lnet_md_t::user_ptr.
Referenced by gss_do_ctx_fini_rpc(), ptlrpc_check_set(), and ptlrpc_send_new_req().
void ptlrpc_abort_inflight (struct obd_import * imp)
Aborts all in-flight request on import imp sending and delayed lists.
Definition at line 3045 of file client.c.
References D_RPCTRACE, DEBUG_REQ, ENTRY, EXIT, obd_import::imp_delayed_list, obd_import::imp_generation, obd_import::imp_lock, obd_import::imp_replayable, obd_import::imp_sending_list, list_entry, list_for_each_safe, ptlrpc_client_wake_req(), ptlrpc_free_committed(), ptlrpc_request::rq_err, ptlrpc_request::rq_list, ptlrpc_request::rq_lock, and ptlrpc_request::rq_status.
Referenced by ptlrpc_cleanup_imp(), and ptlrpc_deactivate_and_unlock_import().
void ptlrpc_abort_set (struct ptlrpc_request_set * set)
Abort all uncompleted requests in request set set.
Definition at line 3104 of file client.c.
References LASSERT, list_entry, list_for_each_safe, ptlrpc_client_wake_req(), ptlrpc_request::rq_err, ptlrpc_request::rq_lock, ptlrpc_request::rq_phase, RQ_PHASE_RPC, rq_set_chain, and ptlrpc_request::rq_status.
Referenced by ptlrpcd().
int ptlrpc_add_rqs_to_pool (struct ptlrpc_request_pool * pool, int num_rq)
Allocates, initializes and adds num_rq requests to the pool pool.
Definition at line 533 of file client.c.
References LASSERTF, list_add_tail(), list_empty(), lustre_msg, msg, OBD_ALLOC_LARGE, ptlrpc_request_pool::prp_lock, ptlrpc_request_pool::prp_req_list, ptlrpc_request_pool::prp_rq_size, ptlrpc_request_cache_alloc(), ptlrpc_request_cache_free(), ptlrpc_request::rq_list, ptlrpc_request::rq_pool, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqbuf_len, and size.
Referenced by osc_init(), and osc_setup().
int ptlrpc_add_timeout_client (int time, enum timeout_event event, timeout_cb_t cb, void * data, struct list_head * obd_list)
Definition at line 504 of file pinger.c.
References list_add(), pinger_mutex, ptlrpc_pinger_register_timeout(), and timeout_item::ti_obd_list.
Referenced by osc_add_shrink_grant().
int ptlrpc_at_get_net_latency (struct ptlrpc_request * req)
Definition at line 351 of file client.c.
References at_get(), AT_OFF, imp_at::iat_net_latency, obd_import::imp_at, and ptlrpc_request::rq_import.
Referenced by ptl_send_rpc(), ptlrpc_at_recv_early_reply(), and ptlrpc_replay_req().
void ptlrpc_at_set_req_timeout (struct ptlrpc_request * req)
Set server timelimit for this req, i.e.
how long are we willing to wait for reply before timing out this request.
imp_server_timeout means this is reverse import and we send (currently only) ASTs to the client and cannot afford to wait too long for the reply, otherwise the other client (because of which we are sending this request) would timeout waiting for us
Definition at line 293 of file client.c.
References at_est2timeout(), at_get(), AT_OFF, imp_at::iat_service_estimate, obd_import::imp_at, obd_import::imp_server_timeout, import_at_get_index(), LASSERT, lustre_msg_set_timeout(), obd_timeout, ptlrpc_request::rq_import, ptlrpc_request::rq_reqmsg, and ptlrpc_request::rq_timeout.
Referenced by after_reply(), fld_client_rpc(), ldlm_cli_cancel_req(), mdc_close(), mdc_getpage(), mdc_quotactl(), osc_brw_prep_request(), osc_destroy(), osc_ladvise_base(), osc_punch_base(), osc_quotactl(), osc_statfs(), osc_statfs_async(), osp_it_fetch(), osp_obd_statfs(), osp_object_truncate(), osp_statfs_update(), ptlrpc_replay_req(), ptlrpc_request_bufs_pack(), qsd_fetch_index(), and seq_client_rpc().
int ptlrpc_buf_need_swab (struct ptlrpc_request * req, const int inout, __u32 index)
ptlrpc msg buffer and swab interface
Definition at line 86 of file pack_generic.c.
References lustre_rep_swabbed(), lustre_req_swabbed(), ptlrpc_rep_need_swab(), and ptlrpc_req_need_swab().
Referenced by lustre_unpack_ptlrpc_body_v2(), and swabber_dumper_helper().
void ptlrpc_buf_set_swabbed (struct ptlrpc_request * req, const int inout, __u32 index)
Definition at line 77 of file pack_generic.c.
References lustre_set_rep_swabbed(), and lustre_set_req_swabbed().
Referenced by lustre_unpack_ptlrpc_body_v2(), and swabber_dumper_helper().
int ptlrpc_check_set (const struct lu_env * env, struct ptlrpc_request_set * set)
this sends any unsent RPCs in set and returns 1 if all are sent and no more replies are expected.
(it is possible to get less replies than requests sent e.g. due to timed out requests or requests that we had trouble to send out)
NOTE: This function contains a potential schedule point (cond_resched()).
Definition at line 1644 of file client.c.
References after_reply(), ptlrpc_connection::c_peer, CDEBUG, cfs_time_current_sec(), current_comm, D_ERROR, D_HA, D_RPCTRACE, DEBUG_REQ, ENTRY, GOTO, obd_import::imp_connection, obd_import::imp_delayed_list, obd_import::imp_inflight, obd_import::imp_lock, obd_import::imp_obd, obd_import::imp_recovery_waitq, obd_import::imp_sending_list, INIT_LIST_HEAD, LASSERT, LBUG, libcfs_nid2str(), list_add_tail(), list_del_init(), list_empty(), list_entry, list_for_each_safe, list_move_tail(), list_splice(), LPU64, lustre_msg_get_opc(), lustre_msg_get_status(), list_head::next, lnet_process_id_t::nid, OBD_FAIL_CHECK, OBD_FAIL_CHECK_ORSET, OBD_FAIL_ONCE, OBD_FAIL_PTLRPC_LONG_BULK_UNLINK, OBD_FAIL_PTLRPC_LONG_REPL_UNLINK, obd_device::obd_uuid, ptl_send_rpc(), ptlrpc_at_recv_early_reply(), ptlrpc_client_bulk_active(), ptlrpc_client_early(), ptlrpc_client_recv(), ptlrpc_client_recv_or_unlink(), ptlrpc_client_replied(), ptlrpc_expire_one_request(), ptlrpc_import_delay_req(), ptlrpc_no_resend(), ptlrpc_req_finished(), ptlrpc_req_interpret(), ptlrpc_rqphase_move(), ptlrpc_send_new_req(), ptlrpc_set_producer(), ptlrpc_unregister_bulk(), ptlrpc_unregister_reply(), ptlrpcd_check_work(), RETURN, ptlrpc_request::rq_allow_intr, ptlrpc_request::rq_err, ptlrpc_request::rq_import, ptlrpc_request::rq_intr, ptlrpc_request::rq_invalid_rqset, ptlrpc_request::rq_list, ptlrpc_request::rq_lock, ptlrpc_request::rq_net_err, ptlrpc_request::rq_next_phase, ptlrpc_request::rq_no_resend, ptlrpc_request::rq_phase, RQ_PHASE_BULK, RQ_PHASE_COMPLETE, RQ_PHASE_INTERPRET, RQ_PHASE_NEW, RQ_PHASE_RPC, RQ_PHASE_UNDEFINED, RQ_PHASE_UNREGISTERING, ptlrpc_request::rq_receiving_reply, ptlrpc_request::rq_replied, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_resend, ptlrpc_request::rq_sent, rq_set_chain, ptlrpc_request::rq_status, ptlrpc_request::rq_timedout, ptlrpc_request::rq_wait_ctx, ptlrpc_request::rq_waiting, ptlrpc_request::rq_xid, sptlrpc_req_refresh_ctx(), status, unlikely, and obd_uuid::uuid.
Referenced by do_set_info_async(), osc_set_info_async(), osp_obd_set_info_async(), ptlrpc_set_wait(), and ptlrpcd_check().
void ptlrpc_cleanup_client (struct obd_import * imp)
Definition at line 2705 of file client.c.
References ENTRY, and EXIT.
void ptlrpc_cleanup_imp (struct obd_import * imp)
Definition at line 1642 of file import.c.
References ENTRY, EXIT, obd_import::imp_generation, obd_import::imp_lock, IMPORT_SET_STATE_NOLOCK, LUSTRE_IMP_CLOSED, and ptlrpc_abort_inflight().
static int ptlrpc_client_bulk_active (struct ptlrpc_request * req) [inline, static]
Definition at line 2044 of file lustre_net.h.
References ptlrpc_bulk_desc::bd_lock, ptlrpc_bulk_desc::bd_md_count, cfs_time_current_sec(), LASSERT, OBD_FAIL_CHECK, and OBD_FAIL_PTLRPC_LONG_BULK_UNLINK.
Referenced by ptlrpc_check_set(), and ptlrpc_unregister_bulk().
static int ptlrpc_client_early (struct ptlrpc_request * req) [inline, static]
Returns true if request req got early reply and hard deadline is not met.
Definition at line 2454 of file lustre_net.h.
References cfs_time_current_sec(), OBD_FAIL_CHECK, OBD_FAIL_PTLRPC_LONG_REPL_UNLINK, and ptlrpc_request::rq_early.
Referenced by ptlrpc_check_set().
static int ptlrpc_client_recv (struct ptlrpc_request * req) [inline, static]
Returns true if request req is in process of receiving server reply.
Definition at line 2476 of file lustre_net.h.
References cfs_time_current_sec(), OBD_FAIL_CHECK, OBD_FAIL_PTLRPC_LONG_REPL_UNLINK, and ptlrpc_request::rq_receiving_reply.
Referenced by ptlrpc_check_set().
static int ptlrpc_client_recv_or_unlink (struct ptlrpc_request * req) [inline, static]
Definition at line 2485 of file lustre_net.h.
References cfs_time_current_sec(), OBD_FAIL_CHECK, OBD_FAIL_PTLRPC_LONG_REPL_UNLINK, ptlrpc_request::rq_lock, ptlrpc_request::rq_receiving_reply, ptlrpc_request::rq_reply_unlinked, and ptlrpc_request::rq_req_unlinked.
Referenced by ptlrpc_check_set(), and ptlrpc_unregister_reply().
static int ptlrpc_client_replied (struct ptlrpc_request * req) [inline, static]
Returns true if we got real reply from server for this request.
Definition at line 2466 of file lustre_net.h.
References cfs_time_current_sec(), OBD_FAIL_CHECK, OBD_FAIL_PTLRPC_LONG_REPL_UNLINK, and ptlrpc_request::rq_replied.
Referenced by ptlrpc_check_set(), ptlrpc_replay_interpret(), and ptlrpc_resend_req().
static void ptlrpc_client_wake_req (struct ptlrpc_request * req) [inline, static]
Definition at line 2502 of file lustre_net.h.
Referenced by client_bulk_callback(), ptlrpc_abort_inflight(), ptlrpc_abort_set(), ptlrpc_replay_interpret(), ptlrpc_restart_req(), ptlrpc_wake_delayed(), reply_in_callback(), request_out_callback(), and sptlrpc_cli_ctx_wakeup().
void ptlrpc_commit_replies (struct obd_export * exp)
Definition at line 408 of file service.c.
References DECLARE_RS_BATCH, ENTRY, EXIT, obd_export::exp_last_committed, obd_export::exp_uncommitted_replies, obd_export::exp_uncommitted_replies_lock, LASSERT, list_del_init(), list_for_each_entry_safe, rs_batch_add(), rs_batch_fini(), rs_batch_init(), ptlrpc_reply_state::rs_difficult, ptlrpc_reply_state::rs_export, ptlrpc_reply_state::rs_obd_list, and ptlrpc_reply_state::rs_transno.
Referenced by tgt_cb_last_committed().
int ptlrpc_connect_import (struct obd_import * imp)
Import API.
Import API.
This includes all preparations, initializing CONNECT RPC request and passing it to ptlrpcd for actual sending. Returns 0 on success or error code.
Definition at line 648 of file import.c.
References __u64, at_timeout2est(), CERROR, CLASSERT, D_RPCTRACE, DEBUG_REQ, ENTRY, GOTO, obd_import::imp_conn_cnt, obd_import::imp_connect_data, obd_import::imp_connect_flags_orig, obd_import::imp_connect_op, obd_import::imp_connected, obd_import::imp_dlm_handle, obd_import::imp_lock, obd_import::imp_msghdr_flags, obd_import::imp_obd, obd_import::imp_peer_committed_transno, obd_import::imp_remote_handle, obd_import::imp_replayable, obd_import::imp_resend_replay, obd_import::imp_state, import_select_connection(), IMPORT_SET_STATE, IMPORT_SET_STATE_NOLOCK, INITIAL_CONNECT_TIMEOUT, lustre_handle_is_used(), LUSTRE_IMP_CLOSED, LUSTRE_IMP_CONNECTING, LUSTRE_IMP_DISCON, LUSTRE_IMP_FULL, lustre_msg_add_op_flags(), lustre_msg_set_service_time(), lustre_msg_set_timeout(), LUSTRE_OBD_VERSION, LUSTRE_VERSION_CODE, MSG_CONNECT_INITIAL, MSG_CONNECT_TRANSNO, MSGHDR_AT_SUPPORT, MSGHDR_CKSUM_INCOMPAT18, obd2cli_tgt, obd_reconnect(), obd_device::obd_self_export, obd_device::obd_uuid, obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_transno, obd_connect_data::ocd_version, ptlrpc_connect_async_args::pcaa_initial_connect, ptlrpc_connect_async_args::pcaa_peer_committed, ptlrpc_connect_interpret(), ptlrpc_first_transno(), ptlrpc_req_async_args, ptlrpc_request_alloc(), ptlrpc_request_bufs_pack(), ptlrpc_request_free(), ptlrpc_request_set_replen(), ptlrpcd_add_req(), RCL_SERVER, req_capsule_set_size(), RETURN, RMF_CONNECT_DATA, ptlrpc_request::rq_no_delay, ptlrpc_request::rq_no_resend, ptlrpc_request::rq_pill, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_timeout, RQF_MDS_CONNECT, sptlrpc_import_sec_adapt(), and obd_uuid::uuid.
Referenced by client_connect_import(), completed_replay_interpret(), lwp_obd_connect(), osp_obd_connect(), ptlrpc_connect_interpret(), ptlrpc_initiate_recovery(), ptlrpc_recover_import(), ptlrpc_replay_interpret(), ptlrpc_request_handle_notconn(), and replay_lock_interpret().
struct ptlrpc_connection* ptlrpc_connection_addref (struct ptlrpc_connection *) [read]
Definition at line 128 of file connection.c.
References ptlrpc_connection::c_peer, ptlrpc_connection::c_refcount, CDEBUG, D_INFO, ENTRY, libcfs_nid2str(), lnet_process_id_t::nid, and RETURN.
Referenced by import_select_connection(), and ptlrpc_send_reply().
void ptlrpc_connection_fini (void)
Definition at line 157 of file connection.c.
References cfs_hash_putref(), ENTRY, and EXIT.
Referenced by ptlrpc_exit(), and ptlrpc_init().
struct ptlrpc_connection* ptlrpc_connection_get (lnet_process_id_t peer, lnet_nid_t self, struct obd_uuid * uuid) [read]
Definition at line 48 of file connection.c.
References ptlrpc_connection::c_hash, ptlrpc_connection::c_peer, ptlrpc_connection::c_refcount, ptlrpc_connection::c_remote_uuid, ptlrpc_connection::c_self, CDEBUG, cfs_hash_findadd_unique(), cfs_hash_lookup(), D_INFO, ENTRY, EXIT, GOTO, INIT_HLIST_NODE, libcfs_nid2str(), lnet_process_id_t::nid, OBD_ALLOC_PTR, OBD_FREE_PTR, obd_str2uuid(), RETURN, and obd_uuid::uuid.
Referenced by ptlrpc_send_reply(), and ptlrpc_uuid_to_connection().
int ptlrpc_connection_init (void)
Definition at line 140 of file connection.c.
References cfs_hash_create(), CFS_HASH_DEFAULT, CFS_HASH_MAX_THETA, CFS_HASH_MIN_THETA, conn_hash_ops, ENTRY, HASH_CONN_BKT_BITS, HASH_CONN_CUR_BITS, HASH_CONN_MAX_BITS, and RETURN.
Referenced by ptlrpc_init().
int ptlrpc_connection_put (struct ptlrpc_connection * c)
Definition at line 91 of file connection.c.
References ptlrpc_connection::c_peer, ptlrpc_connection::c_refcount, CDEBUG, D_INFO, ENTRY, LASSERT, libcfs_nid2str(), lnet_process_id_t::nid, and RETURN.
Referenced by client_import_del_conn(), import_select_connection(), import_set_conn(), ptlrpc_init(), and ptlrpc_send_reply().
void ptlrpc_daemonize (char * name)
int ptlrpc_del_timeout_client (struct list_head * obd_list, enum timeout_event event)
If there are no obd attached to the timeout event list, remove this timeout event from the pinger
Definition at line 522 of file pinger.c.
References LASSERTF, list_del(), list_del_init(), list_empty(), list_for_each_entry, OBD_FREE_PTR, pinger_mutex, timeout_item::ti_chain, and timeout_item::ti_obd_list.
Referenced by osc_del_shrink_grant().
int ptlrpc_disconnect_import (struct obd_import * imp, int noclose)
Definition at line 1550 of file import.c.
References at_get(), AT_OFF, back_to_sleep(), CERROR, cfs_time_seconds(), cfs_timeout_cap(), ptlrpc_client::cli_request_portal, ENTRY, GOTO, imp_at::iat_service_estimate, obd_import::imp_at, obd_import::imp_client, obd_import::imp_connect_op, obd_import::imp_lock, obd_import::imp_obd, obd_import::imp_recovery_waitq, obd_import::imp_remote_handle, obd_import::imp_server_timeout, obd_import::imp_state, import_at_get_index(), IMPORT_SET_STATE, IMPORT_SET_STATE_NOLOCK, INITIAL_CONNECT_TIMEOUT, l_wait_event, LUSTRE_IMP_CLOSED, LUSTRE_IMP_CONNECTING, LUSTRE_IMP_DISCON, LUSTRE_IMP_FULL, LUSTRE_OBD_VERSION, LWI_ON_SIGNAL_NOOP, LWI_TIMEOUT_INTR, MDS_CONNECT, MDS_DISCONNECT, MGS_CONNECT, MGS_DISCONNECT, min_t, obd2cli_tgt, obd_device::obd_force, obd_device::obd_name, obd_timeout, OST_CONNECT, OST_DISCONNECT, ptlrpc_import_in_recovery(), ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc_pack(), ptlrpc_request_set_replen(), RETURN, ptlrpc_request::rq_no_resend, ptlrpc_request::rq_timeout, RQF_MDS_DISCONNECT, and timeout.
Referenced by client_disconnect_export(), ldlm_namespace_free_prior(), lwp_disconnect(), osp_disconnect(), and ptlrpc_reconnect_import().
void ptlrpc_dispatch_difficult_reply (struct ptlrpc_reply_state * rs)
Put reply state into a queue for processing because we received ACK from the client.
Definition at line 369 of file service.c.
References ENTRY, EXIT, ptlrpc_hr_thread::hrt_lock, ptlrpc_hr_thread::hrt_queue, ptlrpc_hr_thread::hrt_waitq, LASSERT, list_add_tail(), list_empty(), ptlrpc_hr_select(), ptlrpc_reply_state::rs_list, and ptlrpc_reply_state::rs_svcpt.
Referenced by ptlrpc_schedule_difficult_reply(), and target_send_reply().
int ptlrpc_error (struct ptlrpc_request * req)
Definition at line 649 of file niobuf.c.
References ptlrpc_send_error().
Referenced by ldlm_handle_gl_callback(), ptlrpc_check_req(), tgt_handle_recovery(), and tgt_request_handle().
void ptlrpc_free_bulk (struct ptlrpc_bulk_desc * bulk)
Definition at line 257 of file client.c.
References ptlrpc_bulk_desc::bd_export, ptlrpc_bulk_desc::bd_frag_ops, ptlrpc_bulk_desc::bd_import, ptlrpc_bulk_desc::bd_iov_count, ptlrpc_bulk_desc::bd_max_iov, ptlrpc_bulk_desc::bd_md_count, ptlrpc_bulk_desc::bd_type, class_export_put(), class_import_put(), ENTRY, EXIT, GET_KIOV, GET_KVEC, LASSERT, OBD_FREE_LARGE, OBD_FREE_PTR, ptlrpc_is_bulk_desc_kiov(), ptlrpc_bulk_frag_ops::release_frags, and sptlrpc_enc_pool_put_pages().
Referenced by __ptlrpc_free_req(), mgs_get_ir_logs(), out_handle(), tgt_brw_read(), tgt_brw_write(), tgt_send_buffer(), and tgt_sendpage().
void ptlrpc_free_rq_pool (struct ptlrpc_request_pool * pool)
Wind down request pool pool.
Frees all requests from the pool too
Definition at line 509 of file client.c.
References LASSERT, list_del(), list_entry, list_for_each_safe, OBD_FREE, OBD_FREE_LARGE, ptlrpc_request_pool::prp_lock, ptlrpc_request_pool::prp_req_list, ptlrpc_request_pool::prp_rq_size, ptlrpc_request_cache_free(), ptlrpc_request::rq_list, ptlrpc_request::rq_reqbuf, and ptlrpc_request::rq_reqbuf_len.
Referenced by osc_exit().
int ptlrpc_hpreq_handler (struct ptlrpc_request * req)
Definition at line 1620 of file service.c.
References lustre_msg_get_opc(), MDS_CONNECT, OBD_PING, OST_CONNECT, ptlrpc_request::rq_export, and ptlrpc_request::rq_reqmsg.
Referenced by mds_start_ptlrpc_service(), and ost_setup().
void ptlrpc_hr_fini (void)
Definition at line 2943 of file service.c.
References cfs_percpt_for_each, cfs_percpt_free(), ptlrpc_hr_service::hr_partitions, ptlrpc_hr_partition::hrp_nthrs, ptlrpc_hr_partition::hrp_thrs, OBD_FREE, ptlrpc_hr, and ptlrpc_stop_hr_threads().
Referenced by ptlrpc_exit(), ptlrpc_hr_init(), and ptlrpc_init().
int ptlrpc_hr_init (void)
Definition at line 2888 of file service.c.
References cfs_cpt_weight(), cfs_cpu_ht_nsiblings(), cfs_percpt_alloc(), cfs_percpt_for_each, ENTRY, GOTO, ptlrpc_hr_service::hr_cpt_table, ptlrpc_hr_service::hr_partitions, ptlrpc_hr_service::hr_waitq, ptlrpc_hr_partition::hrp_cpt, ptlrpc_hr_partition::hrp_nstarted, ptlrpc_hr_partition::hrp_nstopped, ptlrpc_hr_partition::hrp_nthrs, ptlrpc_hr_partition::hrp_thrs, ptlrpc_hr_thread::hrt_id, ptlrpc_hr_thread::hrt_lock, ptlrpc_hr_thread::hrt_partition, ptlrpc_hr_thread::hrt_queue, ptlrpc_hr_thread::hrt_waitq, INIT_LIST_HEAD, LASSERT, OBD_CPT_ALLOC, ptlrpc_hr, ptlrpc_hr_fini(), ptlrpc_start_hr_threads(), and RETURN.
Referenced by ptlrpc_init().
void ptlrpc_import_enter_resend (struct obd_import * imp)
Definition at line 106 of file import.c.
References IMPORT_SET_STATE, and LUSTRE_IMP_RECOVER.
int ptlrpc_import_recovery_state_machine (struct obd_import * imp)
This is the state machine for client-side recovery on import.
Typicaly we have two possibly paths. If we came to server and it is not in recovery, we just enter IMP_EVICTED state, invalidate our import state and reconnect from scratch. If we came to server that is in recovery, we enter IMP_REPLAY import state. We go through our list of requests to replay and send them to server one by one. After sending all request from the list we change import state to IMP_REPLAY_LOCKS and re-request all the locks we believe we have from server and also all the locks we don't yet have and wait for server to grant us. After that we send a special "replay completed" request and change import state to IMP_REPLAY_WAIT. Upon receiving reply to that "replay completed" RPC we enter IMP_RECOVER state and resend all requests from sending list. After that we promote import to FULL state and send all delayed requests and import is fully operational after that.
Definition at line 1449 of file import.c.
References ptlrpc_connection::c_peer, ptlrpc_connection::c_remote_uuid, CDEBUG, CERROR, class_import_get(), class_import_put(), D_HA, deuuidify(), ENTRY, GOTO, obd_import::imp_connection, obd_import::imp_lock, obd_import::imp_obd, obd_import::imp_recovery_waitq, obd_import::imp_replay_inflight, obd_import::imp_state, obd_import::imp_vbr_failed, IMPORT_SET_STATE, LCONSOLE_ERROR_MSG, LCONSOLE_INFO, ldlm_replay_locks(), libcfs_nid2str(), LUSTRE_IMP_EVICTED, LUSTRE_IMP_FULL, LUSTRE_IMP_RECOVER, LUSTRE_IMP_REPLAY, LUSTRE_IMP_REPLAY_LOCKS, LUSTRE_IMP_REPLAY_WAIT, LUSTRE_MGC_NAME, lnet_process_id_t::nid, obd2cli_tgt, obd_device::obd_name, obd_device::obd_type, obd_uuid2str(), ptlrpc_activate_import(), ptlrpc_invalidate_import_thread(), ptlrpc_replay_next(), ptlrpc_resend(), ptlrpc_wake_delayed(), RETURN, signal_completed_replay(), obd_type::typ_name, and obd_uuid::uuid.
Referenced by completed_replay_interpret(), ptlrpc_connect_interpret(), ptlrpc_invalidate_import_thread(), ptlrpc_replay_interpret(), and replay_lock_interpret().
void ptlrpc_init_client (int req_portal, int rep_portal, char * name, struct ptlrpc_client *)
Initialize passed in client structure cl.
Definition at line 74 of file client.c.
References ptlrpc_client::cli_name, ptlrpc_client::cli_reply_portal, and ptlrpc_client::cli_request_portal.
Referenced by client_obd_setup(), echo_setup(), mdt_init0(), mgs_init0(), and ofd_init0().
int ptlrpc_init_import (struct obd_import * imp)
Definition at line 123 of file import.c.
References obd_import::imp_generation, obd_import::imp_lock, obd_import::imp_state, and LUSTRE_IMP_NEW.
Referenced by client_connect_import(), lwp_obd_connect(), lwp_setup(), and osp_init0().
struct ptlrpc_request_pool* ptlrpc_init_rq_pool (int , int , int(*)(struct ptlrpc_request_pool *, int) populate_pool) [read]
Create and initialize new request pool with given attributes: num_rq - initial number of requests to create for the pool msgsize - maximum message size possible for requests in thid pool populate_pool - function to be called when more requests need to be added to the pool Returns pointer to newly created pool or NULL on error.
Definition at line 581 of file client.c.
References INIT_LIST_HEAD, OBD_ALLOC, ptlrpc_request_pool::prp_lock, ptlrpc_request_pool::prp_populate, ptlrpc_request_pool::prp_req_list, ptlrpc_request_pool::prp_rq_size, and SPTLRPC_MAX_PAYLOAD.
Referenced by osc_init().
static bool ptlrpc_is_bulk_desc_kiov (enum ptlrpc_bulk_op_type type) [inline, static]
Definition at line 1375 of file lustre_net.h.
References PTLRPC_BULK_BUF_KIOV, and PTLRPC_BULK_BUF_KVEC.
Referenced by __ptlrpc_prep_bulk_page(), corrupt_bulk_data(), gss_cli_ctx_unwrap_bulk(), gss_cli_ctx_wrap_bulk(), gss_prep_bulk_kerberos(), gss_svc_unwrap_bulk(), gss_svc_wrap_bulk(), gss_unwrap_bulk_kerberos(), gss_wrap_bulk_kerberos(), krb5_decrypt_bulk(), krb5_encrypt_bulk(), plain_cli_unwrap_bulk(), ptlrpc_fill_bulk_md(), ptlrpc_free_bulk(), ptlrpc_new_bulk(), sptlrpc_enc_pool_get_pages(), sptlrpc_enc_pool_put_pages(), sptlrpc_get_bulk_checksum(), tgt_checksum_bulk(), and unstable_page_accounting().
static bool ptlrpc_is_bulk_desc_kvec (enum ptlrpc_bulk_op_type type) [inline, static]
Definition at line 1369 of file lustre_net.h.
References PTLRPC_BULK_BUF_KIOV, and PTLRPC_BULK_BUF_KVEC.
Referenced by ptlrpc_fill_bulk_md(), ptlrpc_new_bulk(), and ptlrpc_prep_bulk_frag().
static bool ptlrpc_is_bulk_get_sink (enum ptlrpc_bulk_op_type type) [inline, static]
Definition at line 1359 of file lustre_net.h.
References PTLRPC_BULK_GET_SINK.
static bool ptlrpc_is_bulk_get_source (enum ptlrpc_bulk_op_type type) [inline, static]
Definition at line 1349 of file lustre_net.h.
References PTLRPC_BULK_GET_SOURCE.
Referenced by client_bulk_callback().
static bool ptlrpc_is_bulk_op_active (enum ptlrpc_bulk_op_type type) [inline, static]
Definition at line 1381 of file lustre_net.h.
References PTLRPC_BULK_OP_ACTIVE, and PTLRPC_BULK_OP_PASSIVE.
static bool ptlrpc_is_bulk_op_get (enum ptlrpc_bulk_op_type type) [inline, static]
Definition at line 1344 of file lustre_net.h.
References PTLRPC_BULK_OP_GET.
Referenced by ptlrpc_register_bulk().
static bool ptlrpc_is_bulk_op_passive (enum ptlrpc_bulk_op_type type) [inline, static]
Definition at line 1388 of file lustre_net.h.
References PTLRPC_BULK_OP_ACTIVE, and PTLRPC_BULK_OP_PASSIVE.
Referenced by ptlrpc_prep_bulk_imp(), and ptlrpc_register_bulk().
static bool ptlrpc_is_bulk_put_sink (enum ptlrpc_bulk_op_type type) [inline, static]
Definition at line 1354 of file lustre_net.h.
References PTLRPC_BULK_PUT_SINK.
Referenced by client_bulk_callback().
static bool ptlrpc_is_bulk_put_source (enum ptlrpc_bulk_op_type type) [inline, static]
Definition at line 1364 of file lustre_net.h.
References PTLRPC_BULK_PUT_SOURCE.
static void ptlrpc_lprocfs_brw (struct ptlrpc_request * req, int bytes) [inline, static]
Definition at line 2662 of file lustre_net.h.
Referenced by brw_interpret(), tgt_brw_read(), and tgt_brw_write().
static void ptlrpc_lprocfs_register_obd (struct obd_device * obd) [inline, static]
Definition at line 2660 of file lustre_net.h.
Referenced by lwp_init0(), mdc_setup(), and osc_setup().
static void ptlrpc_lprocfs_unregister_obd (struct obd_device * obd) [inline, static]
Definition at line 2661 of file lustre_net.h.
Referenced by lwp_device_fini(), mdc_precleanup(), osc_precleanup(), osp_device_fini(), and osp_init0().
void ptlrpc_mark_interrupted (struct ptlrpc_request * req)
Sets rq_intr flag in req under spinlock.
Definition at line 2168 of file client.c.
References ptlrpc_request::rq_intr, and ptlrpc_request::rq_lock.
Referenced by osc_build_rpc(), and ptlrpc_interrupted_set().
__u64 ptlrpc_next_xid (void)
Increase xid and returns resulting new value to the caller.
Multi-bulk BRW RPCs consume multiple XIDs for each bulk transfer, starting at the returned xid, up to xid + PTLRPC_BULK_OPS_COUNT - 1. The BRW RPC itself uses the last bulk xid needed, so the server can determine the the number of bulk transfers from the RPC XID and a bitmask. The starting xid must align to a power-of-two value.
This is assumed to be true due to the initial ptlrpc_last_xid value also being initialized to a power-of-two value. LU-1431
Definition at line 3177 of file client.c.
References __u64, and PTLRPC_BULK_OPS_COUNT.
Referenced by ptlrpc_assign_next_xid_nolock(), ptlrpc_set_bulk_mbits(), and ptlrpcd_add_work_req().
static int ptlrpc_no_resend (struct ptlrpc_request * req) [inline, static]
Definition at line 2563 of file lustre_net.h.
References ptlrpc_send_limit_expired(), ptlrpc_request::rq_lock, and ptlrpc_request::rq_no_resend.
Referenced by after_reply(), ptlrpc_check_set(), ptlrpc_expire_one_request(), and ptlrpc_resend().
int ptlrpc_obd_ping (struct obd_device * obd)
Definition at line 78 of file pinger.c.
References client_obd::cl_import, obd_device::cli, ENTRY, LUSTRE_IMP_FULL, ptlrpc_prep_ping(), ptlrpc_queue_wait(), ptlrpc_req_finished(), RETURN, and obd_device::u.
Referenced by mdc_iocontrol(), osc_iocontrol(), and osp_iocontrol().
static const char* ptlrpc_phase2str (enum rq_phase phase) [inline, static]
Convert numerical request phase value phase into text string description.
Definition at line 1229 of file lustre_net.h.
References RQ_PHASE_BULK, RQ_PHASE_COMPLETE, RQ_PHASE_INTERPRET, RQ_PHASE_NEW, RQ_PHASE_RPC, and RQ_PHASE_UNREGISTERING.
Referenced by ptlrpc_invalidate_import(), ptlrpc_rqphase2str(), and ptlrpc_rqphase_move().
int ptlrpc_pinger_add_import (struct obd_import * imp)
Definition at line 405 of file pinger.c.
References CDEBUG, class_import_get(), D_HA, ENTRY, obd_import::imp_obd, obd_import::imp_pinger_chain, list_add_tail(), list_empty(), obd2cli_tgt, obd_device::obd_no_recov, obd_device::obd_uuid, pinger_mutex, ptlrpc_pinger_wake_up(), ptlrpc_update_next_ping(), RETURN, and obd_uuid::uuid.
Referenced by client_connect_import(), lwp_obd_connect(), and osp_obd_connect().
int ptlrpc_pinger_del_import (struct obd_import * imp)
Definition at line 428 of file pinger.c.
References CDEBUG, class_import_put(), D_HA, ENTRY, obd_import::imp_obd, obd_import::imp_pinger_chain, list_del_init(), list_empty(), obd2cli_tgt, obd_device::obd_no_recov, obd_device::obd_uuid, pinger_mutex, RETURN, and obd_uuid::uuid.
Referenced by client_disconnect_export(), lwp_disconnect(), and osp_disconnect().
void ptlrpc_pinger_ir_down (void)
Definition at line 180 of file pinger.c.
References CDEBUG, D_HA, and ir_up.
Referenced by mgc_import_event().
void ptlrpc_pinger_ir_up (void)
Definition at line 173 of file pinger.c.
References CDEBUG, D_HA, and ir_up.
Referenced by mgc_import_event().
int ptlrpc_pinger_suppress_pings (void)
Definition at line 58 of file pinger.c.
References suppress_pings.
Referenced by mdt_connect_internal(), and ofd_parse_connect_data().
int ptlrpc_prep_bulk_frag (struct ptlrpc_bulk_desc * desc, void * frag, int len)
Definition at line 233 of file client.c.
References BD_GET_KVEC, ptlrpc_bulk_desc::bd_iov_count, ptlrpc_bulk_desc::bd_max_iov, ptlrpc_bulk_desc::bd_nob, ptlrpc_bulk_desc::bd_type, ENTRY, LASSERT, ptlrpc_is_bulk_desc_kvec(), and RETURN.
struct ptlrpc_bulk_desc* ptlrpc_prep_bulk_imp (struct ptlrpc_request * req, unsigned nfrags, unsigned max_brw, unsigned int type, unsigned portal, const struct ptlrpc_bulk_frag_ops * ops) [read]
Prepare bulk descriptor for specified outgoing request req that can fit nfrags * pages.
type is bulk type. portal is where the bulk to be sent. Used on client-side. Returns pointer to newly allocatrd initialized bulk descriptor or NULL on error.
Definition at line 174 of file client.c.
References ptlrpc_bulk_desc::bd_cbid, ptlrpc_bulk_desc::bd_import, ptlrpc_bulk_desc::bd_import_generation, ptlrpc_bulk_desc::bd_req, ptlrpc_cb_id::cbid_arg, ptlrpc_cb_id::cbid_fn, class_import_get(), client_bulk_callback(), ENTRY, LASSERT, ptlrpc_is_bulk_op_passive(), ptlrpc_new_bulk(), RETURN, and ptlrpc_request::rq_import.
Referenced by mdc_getpage(), mgc_process_recover_log(), osc_brw_prep_request(), osp_it_fetch(), osp_md_read(), osp_prep_update_req(), and qsd_fetch_index().
static void ptlrpc_prep_bulk_page_nopin (struct ptlrpc_bulk_desc * desc, struct page * page, int pageoffset, int len) [inline, static]
Definition at line 2151 of file lustre_net.h.
References __ptlrpc_prep_bulk_page().
static void ptlrpc_prep_bulk_page_pin (struct ptlrpc_bulk_desc * desc, struct page * page, int pageoffset, int len) [inline, static]
Definition at line 2144 of file lustre_net.h.
References __ptlrpc_prep_bulk_page().
struct ptlrpc_request_set* ptlrpc_prep_fcset (int max, set_producer_func func, void * arg) [read]
Allocate and initialize new request set structure with flow control extension.
This extension allows to control the number of requests in-flight for the whole set. A callback function to generate requests must be provided and the request set will keep the number of requests sent over the wire to . Returns a pointer to the newly allocated set structure or NULL on error.
Definition at line 948 of file client.c.
References ptlrpc_prep_set(), and RETURN.
Referenced by ldlm_run_ast_work().
struct ptlrpc_request* ptlrpc_prep_ping (struct obd_import * imp) [read]
Definition at line 65 of file pinger.c.
References LUSTRE_OBD_VERSION, OBD_PING, ptlrpc_request_alloc_pack(), ptlrpc_request_set_replen(), ptlrpc_request::rq_no_delay, ptlrpc_request::rq_no_resend, and RQF_OBD_PING.
Referenced by ptlrpc_obd_ping(), and ptlrpc_ping().
struct ptlrpc_request_set* ptlrpc_prep_set (void) [read]
Allocate and initialize new request set structure on the current CPT.
Returns a pointer to the newly allocated set structure or NULL on error.
Definition at line 913 of file client.c.
References cfs_cpt_current(), ENTRY, INIT_LIST_HEAD, OBD_CPT_ALLOC, and RETURN.
Referenced by lfsck_assistant_notify_others(), lfsck_assistant_query_others(), lfsck_layout_assistant_sync_failures(), lfsck_layout_slave_notify_master(), lfsck_layout_slave_query_master(), lfsck_namespace_assistant_sync_failures(), lfsck_query_all(), lfsck_start_all(), lfsck_stop_all(), lfsck_stop_notify(), lod_obd_set_info_async(), lov_set_info_async(), lov_statfs(), obd_statfs_rqset(), ptlrpc_prep_fcset(), ptlrpc_queue_wait(), and ptlrpcd().
int ptlrpc_queue_wait (struct ptlrpc_request * req)
Send request and wait until it completes.
Returns request processing status.
Definition at line 2829 of file client.c.
References CERROR, current_pid, ENTRY, LASSERT, lustre_msg_set_status(), ptlrpc_prep_set(), ptlrpc_request_addref(), ptlrpc_set_add_req(), ptlrpc_set_destroy(), ptlrpc_set_wait(), RETURN, ptlrpc_request::rq_receiving_reply, and ptlrpc_request::rq_reqmsg.
Referenced by do_set_info_async(), fld_client_rpc(), gss_do_ctx_init_rpc(), ldlm_cli_cancel_req(), ldlm_cli_convert(), ldlm_cli_enqueue(), lfsck_layout_master_conditional_destroy(), lfsck_layout_slave_check_pairs(), lfsck_namespace_notify_lmv_remote(), llog_client_destroy(), llog_client_next_block(), llog_client_open(), llog_client_prev_block(), llog_client_read_header(), mdc_close(), mdc_fsync(), mdc_get_info_rpc(), mdc_get_remote_perm(), mdc_get_root(), mdc_getattr_common(), mdc_getpage(), mdc_ioc_hsm_progress(), mdc_ioc_hsm_request(), mdc_ioc_hsm_state_set(), mdc_ioc_swap_layouts(), mdc_queue_wait(), mdc_quotactl(), mdc_reint(), mdc_statfs(), mdc_xattr_common(), mgc_process_recover_log(), mgc_set_mgs_param(), mgc_target_register(), osc_create(), osc_getattr(), osc_object_fiemap(), osc_quotactl(), osc_setattr(), osc_statfs(), osp_get_lastfid_from_ost(), osp_it_fetch(), osp_md_read(), osp_obd_statfs(), osp_object_truncate(), osp_precreate_cleanup_orphans(), osp_precreate_send(), osp_remote_sync(), osp_send_update_req(), ptlrpc_disconnect_import(), ptlrpc_obd_ping(), qsd_fetch_index(), qsd_intent_lock(), qsd_send_dqacq(), and seq_client_rpc().
int ptlrpc_reconnect_import (struct obd_import * imp)
Definition at line 450 of file import.c.
References CDEBUG, CERROR, cfs_time_seconds(), D_HA, obd_import::imp_inval_count, obd_import::imp_obd, obd_import::imp_recovery_waitq, obd_import::imp_state, l_wait_event, LWI_INTR, LWI_ON_SIGNAL_NOOP, LWI_TIMEOUT, obd2cli_tgt, obd_device::obd_no_recov, obd_timeout, ptlrpc_activate_import(), ptlrpc_disconnect_import(), ptlrpc_import_in_recovery(), ptlrpc_import_state_name(), ptlrpc_invalidate_import(), ptlrpc_pinger_force(), ptlrpc_recover_import(), and ptlrpc_set_import_discon().
Referenced by mgc_set_info_async().
int ptlrpc_register_bulk (struct ptlrpc_request * req)
Actual interfacing with LNet to put/get/register/unregister stuff.
Actual interfacing with LNet to put/get/register/unregister stuff.
Returns 0 on success or error code.
Definition at line 301 of file niobuf.c.
References __u64, ptlrpc_bulk_desc::bd_cbid, ptlrpc_bulk_desc::bd_failure, ptlrpc_bulk_desc::bd_import, ptlrpc_bulk_desc::bd_iov_count, ptlrpc_bulk_desc::bd_last_mbits, ptlrpc_bulk_desc::bd_lock, ptlrpc_bulk_desc::bd_md_count, ptlrpc_bulk_desc::bd_md_max_brw, ptlrpc_bulk_desc::bd_mds, ptlrpc_bulk_desc::bd_nob, ptlrpc_bulk_desc::bd_nob_transferred, ptlrpc_bulk_desc::bd_portal, ptlrpc_bulk_desc::bd_registered, ptlrpc_bulk_desc::bd_req, ptlrpc_bulk_desc::bd_type, ptlrpc_connection::c_peer, ptlrpc_cb_id::cbid_arg, ptlrpc_cb_id::cbid_fn, CDEBUG, CERROR, client_bulk_callback(), CWARN, D_NET, ENTRY, lnet_md_t::eq_handle, obd_import::imp_connection, obd_import::imp_obd, LASSERT, LASSERTF, libcfs_id2str(), LNET_INS_AFTER, LNET_MAX_IOV, LNET_MD_OP_GET, LNET_MD_OP_PUT, LNET_UNLINK, LNetMDAttach(), LNetMEAttach(), LNetMEUnlink(), LPU64, LPX64, LUSTRE_IMP_REPLAY, mdunlink_iterate_helper(), OBD_FAIL_CHECK, OBD_FAIL_PTLRPC_BULK_GET_NET, obd_device::obd_name, lnet_md_t::options, PTLRPC_BULK_OPS_COUNT, PTLRPC_BULK_OPS_MASK, ptlrpc_eq_h, ptlrpc_fill_bulk_md(), ptlrpc_is_bulk_op_get(), ptlrpc_is_bulk_op_passive(), PTLRPC_MAX_BRW_PAGES, PTLRPC_MD_OPTIONS, RETURN, ptlrpc_request::rq_mbits, ptlrpc_request::rq_resend, ptlrpc_request::rq_status, lnet_md_t::threshold, and lnet_md_t::user_ptr.
Referenced by ptl_send_rpc().
int ptlrpc_register_rqbd (struct ptlrpc_request_buffer_desc * rqbd)
Register request buffer descriptor for request receiving.
Definition at line 900 of file niobuf.c.
References CDEBUG, CERROR, D_NET, lnet_md_t::eq_handle, LASSERT, lnet_md_t::length, LNET_INS_AFTER, LNET_INS_LOCAL, LNET_MD_MAX_SIZE, LNET_MD_OP_PUT, LNET_MD_THRESH_INF, LNET_NID_ANY, LNET_PID_ANY, LNET_UNLINK, LNetMDAttach(), LNetMEAttach(), LNetMEUnlink(), lnet_md_t::max_size, OBD_FAIL_CHECK, OBD_FAIL_PTLRPC_RQBD, lnet_md_t::options, ptlrpc_eq_h, PTLRPC_MD_OPTIONS, ptlrpc_request_buffer_desc::rqbd_buffer, ptlrpc_request_buffer_desc::rqbd_cbid, ptlrpc_request_buffer_desc::rqbd_md_h, ptlrpc_request_buffer_desc::rqbd_refcount, ptlrpc_request_buffer_desc::rqbd_svcpt, ptlrpc_service_part::scp_cpt, service, ptlrpc_service::srv_buf_size, ptlrpc_service::srv_max_req_size, ptlrpc_service::srv_req_portal, lnet_md_t::start, lnet_md_t::threshold, and lnet_md_t::user_ptr.
Referenced by ptlrpc_server_post_idle_rqbds().
struct ptlrpc_service* ptlrpc_register_service (struct ptlrpc_service_conf * conf, struct proc_dir_entry * proc_entry) [read]
Initialize service on a given portal.
This includes starting serving threads , allocating and posting rqbds and so on.
Definition at line 690 of file service.c.
References ptlrpc_service_buf_conf::bc_buf_size, ptlrpc_service_buf_conf::bc_nbufs, ptlrpc_service_buf_conf::bc_rep_max_size, ptlrpc_service_buf_conf::bc_rep_portal, ptlrpc_service_buf_conf::bc_req_max_size, ptlrpc_service_buf_conf::bc_req_portal, ptlrpc_service_cpt_conf::cc_cptable, ptlrpc_service_cpt_conf::cc_pattern, CDEBUG, CERROR, CFS_CPT_ANY, cfs_cpt_number(), cfs_expr_list_free(), cfs_expr_list_parse(), cfs_expr_list_values(), D_NET, ENTRY, GOTO, INIT_LIST_HEAD, LASSERT, list_add(), LNetSetLazyPortal(), OBD_ALLOC, OBD_CPT_ALLOC, OBD_FREE, offsetof, ptlrpc_service_conf::psc_buf, ptlrpc_service_conf::psc_cpt, ptlrpc_service_conf::psc_name, ptlrpc_service_conf::psc_ops, ptlrpc_service_conf::psc_thr, ptlrpc_service_conf::psc_watchdog_factor, ptlrpc_all_services, ptlrpc_all_services_mutex, ptlrpc_lprocfs_register_service, ptlrpc_server_nthreads_check(), ptlrpc_service_nrs_setup(), ptlrpc_service_part_init(), ptlrpc_start_threads(), PTLRPC_SVC_HP_RATIO, ptlrpc_unregister_service(), RETURN, service, SPTLRPC_MAX_PAYLOAD, ptlrpc_service::srv_buf_size, ptlrpc_service::srv_cpt_bits, ptlrpc_service::srv_cptable, ptlrpc_service::srv_cpts, ptlrpc_service::srv_ctx_tags, ptlrpc_service::srv_hpreq_ratio, ptlrpc_service::srv_list, ptlrpc_service::srv_lock, ptlrpc_service::srv_max_reply_size, ptlrpc_service::srv_max_req_size, ptlrpc_service::srv_name, ptlrpc_service::srv_nbuf_per_group, ptlrpc_service::srv_ncpts, ptlrpc_service::srv_ops, ptlrpc_service::srv_parts, ptlrpc_service::srv_rep_portal, ptlrpc_service::srv_req_portal, ptlrpc_service::srv_thread_name, ptlrpc_service::srv_watchdog_factor, ptlrpc_service_thr_conf::tc_cpu_affinity, ptlrpc_service_thr_conf::tc_ctx_tags, ptlrpc_service_thr_conf::tc_thr_name, and test_req_buffer_pressure.
Referenced by ldlm_setup(), mds_start_ptlrpc_service(), mgs_init0(), and ost_setup().
static void ptlrpc_release_bulk_noop (struct ptlrpc_bulk_desc * desc) [inline, static]
Definition at line 2168 of file lustre_net.h.
static void ptlrpc_release_bulk_page_pin (struct ptlrpc_bulk_desc * desc) [inline, static]
Definition at line 2160 of file lustre_net.h.
References BD_GET_KIOV, and ptlrpc_bulk_desc::bd_iov_count.
static int ptlrpc_rep_need_swab (struct ptlrpc_request * req) [inline, static]
Returns 1 if request reply needs to be swabbed into local cpu byteorder.
Definition at line 1198 of file lustre_net.h.
References lustre_rep_swabbed(), and MSG_PTLRPC_HEADER_OFF.
Referenced by gss_cli_ctx_unseal(), gss_cli_ctx_verify(), gss_do_ctx_init_rpc(), mdc_get_info_rpc(), mgc_process_recover_log(), osp_it_fetch(), osp_md_index_lookup(), plain_ctx_verify(), ptlrpc_buf_need_swab(), and qsd_fetch_index().
int ptlrpc_replay_req (struct ptlrpc_request * req)
Prepares and queues request for replay.
Adds it to ptlrpcd queue for actual sending. Returns 0 on success.
Definition at line 3006 of file client.c.
References D_HA, DEBUG_REQ, ENTRY, obd_import::imp_replay_inflight, obd_import::imp_state, LASSERT, LUSTRE_IMP_REPLAY, lustre_msg_get_status(), lustre_msg_set_service_time(), ptlrpc_replay_async_args::praa_old_state, ptlrpc_replay_async_args::praa_old_status, ptlrpc_at_get_net_latency(), ptlrpc_at_set_req_timeout(), ptlrpc_replay_interpret(), ptlrpc_req_async_args, ptlrpc_request_addref(), ptlrpcd_add_req(), RETURN, ptlrpc_request::rq_import, ptlrpc_request::rq_next_phase, ptlrpc_request::rq_phase, RQ_PHASE_NEW, RQ_PHASE_UNDEFINED, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_reqmsg, and ptlrpc_request::rq_status.
Referenced by ptlrpc_replay_next().
int ptlrpc_reply (struct ptlrpc_request * req)
Definition at line 614 of file niobuf.c.
References ptlrpc_send_reply(), and ptlrpc_request::rq_no_reply.
Referenced by ldlm_callback_reply(), and ldlm_handle_gl_callback().
static struct ptlrpc_service* ptlrpc_req2svc (struct ptlrpc_request * req) [static, read]
Definition at line 2583 of file lustre_net.h.
References LASSERT.
Referenced by mdt_reint_rec(), ptlrpc_send_reply(), tgt_brw_read(), and tgt_brw_write().
static void ptlrpc_req_drop_rs (struct ptlrpc_request * req) [inline, static]
Definition at line 2526 of file lustre_net.h.
References ptlrpc_rs_decref(), and ptlrpc_request::rq_repmsg.
Referenced by ptlrpc_at_send_early_reply(), ptlrpc_send_reply(), ptlrpc_server_free_request(), tgt_brw_read(), and tgt_brw_write().
void ptlrpc_req_finished (struct ptlrpc_request * request)
Drops one reference count for a request.
Definition at line 2490 of file client.c.
References __ptlrpc_req_finished().
Referenced by __ll_inode_revalidate(), client_common_fill_super(), do_set_info_async(), fld_client_rpc(), fld_update_from_controller(), gss_do_ctx_fini_rpc(), gss_do_ctx_init_rpc(), ldlm_cli_cancel_req(), ldlm_cli_convert(), ldlm_cli_enqueue(), lfsck_layout_master_conditional_destroy(), lfsck_layout_slave_check_pairs(), lfsck_namespace_notify_lmv_remote(), ll_close_inode_openhandle(), ll_create_node(), ll_dir_get_parent_fid(), ll_dir_ioctl(), ll_dir_setdirstripe(), ll_dir_setstripe(), ll_file_open(), ll_follow_link(), ll_fsync(), ll_get_fid_by_name(), ll_getxattr_common(), ll_getxattr_lov(), ll_intent_file_open(), ll_intent_release(), ll_iocontrol(), ll_layout_fetch(), ll_layout_refresh_locked(), ll_lease_open(), ll_link(), ll_lookup_it(), ll_md_setattr(), ll_migrate(), ll_new_node(), ll_open_cleanup(), ll_put_link(), ll_release_openhandle(), ll_rename(), ll_rmdir(), ll_rmdir_entry(), ll_setxattr_common(), ll_unlink(), ll_xattr_cache_refill(), llog_client_destroy(), llog_client_next_block(), llog_client_open(), llog_client_prev_block(), llog_client_read_header(), lmv_getattr_name(), lmv_intent_lookup(), lmv_intent_remote(), lmv_rename(), lmv_revalidate_slaves(), lmv_unlink(), lustre_check_remote_perm(), mdc_create(), mdc_enqueue(), mdc_fsync(), mdc_get_info_rpc(), mdc_get_remote_perm(), mdc_get_root(), mdc_getattr(), mdc_getattr_name(), mdc_getpage(), mdc_intent_getattr_async(), mdc_ioc_hsm_ct_register(), mdc_ioc_hsm_ct_unregister(), mdc_ioc_hsm_current_action(), mdc_ioc_hsm_progress(), mdc_ioc_hsm_request(), mdc_ioc_hsm_state_get(), mdc_ioc_hsm_state_set(), mdc_ioc_swap_layouts(), mdc_quotactl(), mdc_read_page(), mdc_read_page_remote(), mdc_statfs(), mdc_xattr_common(), mgc_enqueue(), mgc_process_recover_log(), mgc_set_mgs_param(), mgc_target_register(), osc_ap_completion(), osc_brw_prep_request(), osc_brw_redo_request(), osc_create(), osc_enqueue_base(), osc_getattr(), osc_object_fiemap(), osc_quotactl(), osc_set_info_async(), osc_setattr(), osc_statfs(), osp_attr_get(), osp_get_lastfid_from_ost(), osp_it_fetch(), osp_md_index_lookup(), osp_md_object_lock(), osp_md_read(), osp_obd_statfs(), osp_object_truncate(), osp_precreate_cleanup_orphans(), osp_precreate_send(), osp_prep_update_req(), osp_remote_sync(), osp_send_update_req(), osp_sync_new_job(), osp_sync_process_committed(), osp_xattr_get(), ptl_send_rpc(), ptlrpc_check_set(), ptlrpc_disconnect_import(), ptlrpc_obd_ping(), ptlrpc_set_destroy(), ptlrpcd_check(), ptlrpcd_destroy_work(), qsd_fetch_index(), qsd_intent_lock(), qsd_send_dqacq(), request_out_callback(), sa_make_ready(), search_inode_for_lustre(), and seq_client_rpc().
void ptlrpc_req_finished_with_imp_lock (struct ptlrpc_request * request)
Drop one request reference.
Must be called with import imp_lock held. When reference count drops to zero, request is freed.
Definition at line 2451 of file client.c.
References __ptlrpc_req_finished(), obd_import::imp_lock, and ptlrpc_request::rq_import.
static int ptlrpc_req_get_repsize (struct ptlrpc_request * req) [inline, static]
Definition at line 2540 of file lustre_net.h.
References LASSERTF, LUSTRE_MSG_MAGIC_V2, and ptlrpc_request::rq_reqmsg.
static int ptlrpc_req_interpret (const struct lu_env * env, struct ptlrpc_request * req, int rc) [inline, static]
Call completion handler for rpc if any, return it's status or original rc if there was no handler defined for this request.
Definition at line 1128 of file lustre_net.h.
References ptlrpc_request::rq_status.
Referenced by ptlrpc_check_set(), and ptlrpc_set_destroy().
static int ptlrpc_req_need_swab (struct ptlrpc_request * req) [inline, static]
Returns 1 if request needs to be swabbed into local cpu byteorder.
Definition at line 1190 of file lustre_net.h.
References lustre_req_swabbed(), and MSG_PTLRPC_HEADER_OFF.
Referenced by _debug_req(), gss_svc_accept(), gss_svc_handle_destroy(), gss_svc_handle_init(), gss_svc_verify_request(), mdt_rpc_fid2path(), mdt_set_info(), osp_get_attr_from_reply(), out_attr_set(), out_create(), out_handle(), out_index_insert(), out_write(), out_xattr_set(), plain_accept(), and ptlrpc_buf_need_swab().
void ptlrpc_req_set_repsize (struct ptlrpc_request * req, int count, __u32 * sizes)
Definition at line 1562 of file pack_generic.c.
References LUSTRE_MSG_MAGIC_V2, lustre_msg_size(), ptlrpc_request::rq_replen, and ptlrpc_request::rq_reqmsg.
__u64 ptlrpc_req_xid (struct ptlrpc_request * request)
Returns xid of a request.
Definition at line 2499 of file client.c.
References ptlrpc_request::rq_xid.
Referenced by osc_ap_completion().
struct ptlrpc_request* ptlrpc_request_addref (struct ptlrpc_request * req) [read]
Grab additional reference on a request req.
Definition at line 2757 of file client.c.
References ENTRY, RETURN, and ptlrpc_request::rq_refcount.
Referenced by ll_statahead_interpret(), mdc_commit_open(), mdc_finish_intent_lock(), osc_brw_redo_request(), osc_build_rpc(), osp_sync_interpret(), osp_sync_request_commit_cb(), ptl_send_rpc(), ptlrpc_queue_wait(), ptlrpc_replay_req(), and ptlrpc_retain_replayable_request().
struct ptlrpc_request* ptlrpc_request_alloc (struct obd_import * imp, const struct req_format * format) [read]
Allocate new request structure for import imp and initialize its buffer structure according to capsule template format.
Definition at line 852 of file client.c.
References ptlrpc_request_alloc_internal().
Referenced by do_set_info_async(), gss_do_ctx_fini_rpc(), ldlm_cli_cancel_req(), ldlm_enqueue_pack(), lfsck_async_request(), lfsck_layout_async_notify(), lfsck_layout_async_query(), lfsck_layout_master_conditional_destroy(), lfsck_layout_slave_check_pairs(), lfsck_namespace_notify_lmv_remote(), llog_client_open(), mdc_close(), mdc_create(), mdc_enqueue_pack(), mdc_fsync(), mdc_get_info_rpc(), mdc_get_remote_perm(), mdc_get_root(), mdc_getattr(), mdc_getattr_name(), mdc_getpage(), mdc_intent_getattr_pack(), mdc_intent_getxattr_pack(), mdc_intent_layout_pack(), mdc_intent_open_pack(), mdc_intent_unlink_pack(), mdc_ioc_hsm_current_action(), mdc_ioc_hsm_request(), mdc_ioc_hsm_state_get(), mdc_ioc_hsm_state_set(), mdc_ioc_swap_layouts(), mdc_link(), mdc_rename(), mdc_setattr(), mdc_unlink(), mdc_xattr_common(), mgc_process_recover_log(), osc_brw_prep_request(), osc_create(), osc_destroy(), osc_enqueue_base(), osc_getattr(), osc_io_data_version_start(), osc_ladvise_base(), osc_object_fiemap(), osc_punch_base(), osc_set_info_async(), osc_setattr(), osc_setattr_async(), osc_statfs(), osc_statfs_async(), osc_sync_base(), osp_get_lastfid_from_ost(), osp_it_fetch(), osp_obd_set_info_async(), osp_obd_statfs(), osp_object_truncate(), osp_precreate_cleanup_orphans(), osp_precreate_send(), osp_prep_update_req(), osp_statfs_update(), osp_sync_new_job(), ptlrpc_connect_import(), ptlrpc_request_alloc_pack(), qsd_fetch_index(), qsd_intent_lock(), and qsd_send_dqacq().
struct ptlrpc_request* ptlrpc_request_alloc_pack (struct obd_import * imp, const struct req_format * format, __u32 version, int opcode) [read]
Allocate new request for operatione opcode and immediatelly pack it for network transfer.
Only used for simple requests like OBD_PING where the only important part of the request is operation itself. Returns allocated request or NULL on error.
Definition at line 891 of file client.c.
References ptlrpc_request_alloc(), ptlrpc_request_free(), and ptlrpc_request_pack().
Referenced by fld_client_rpc(), gss_do_ctx_init_rpc(), ldlm_cli_convert(), ldlm_cli_enqueue(), llog_client_destroy(), llog_client_next_block(), llog_client_prev_block(), llog_client_read_header(), mdc_ioc_hsm_ct_register(), mdc_ioc_hsm_ct_unregister(), mdc_ioc_hsm_progress(), mdc_quotactl(), mdc_statfs(), mgc_enqueue(), mgc_set_mgs_param(), mgc_target_register(), osc_quotactl(), ptlrpc_disconnect_import(), ptlrpc_prep_ping(), replay_one_lock(), seq_client_rpc(), and signal_completed_replay().
struct ptlrpc_request* ptlrpc_request_alloc_pool (struct obd_import * imp, struct ptlrpc_request_pool * , const struct req_format * format) [read]
Allocate new request structure for import imp from pool pool and initialize its buffer structure according to capsule template format.
Definition at line 863 of file client.c.
References ptlrpc_request_alloc_internal().
Referenced by osc_brw_prep_request().
int ptlrpc_request_bufs_pack (struct ptlrpc_request * request, __u32 version, int opcode, char ** bufs, struct ptlrpc_cli_ctx * ctx)
Definition at line 694 of file client.c.
References class_import_put(), ptlrpc_client::cli_reply_portal, ptlrpc_client::cli_request_portal, ENTRY, GOTO, obd_import::imp_client, obd_import::imp_msg_magic, LASSERT, LUSTRE_IMP_FULL, lustre_msg_add_version(), lustre_msg_set_opc(), lustre_pack_request(), PTL_RPC_MSG_REQUEST, ptlrpc_assign_next_xid(), ptlrpc_at_set_req_timeout(), req_capsule::rc_area, RCL_CLIENT, reply_in_callback(), req_capsule_filled_sizes(), request_out_callback(), RETURN, ptlrpc_request::rq_import, ptlrpc_request::rq_next_phase, ptlrpc_request::rq_phase, RQ_PHASE_NEW, RQ_PHASE_UNDEFINED, ptlrpc_request::rq_pill, ptlrpc_request::rq_pool, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_type, sptlrpc_cli_ctx_get(), sptlrpc_cli_ctx_put(), sptlrpc_req_get_ctx(), and sptlrpc_req_set_flavor().
Referenced by gss_do_ctx_fini_rpc(), ptlrpc_connect_import(), and ptlrpc_request_pack().
void ptlrpc_request_change_export (struct ptlrpc_request * req, struct obd_export * export)
Change request export and move hp request from old export to new.
Definition at line 967 of file service.c.
References class_export_get(), class_export_put(), class_export_rpc_dec, class_export_rpc_inc, obd_export::exp_hp_rpcs, obd_export::exp_reg_rpcs, obd_export::exp_rpc_lock, LASSERT, list_add(), list_del_init(), list_empty(), and ptlrpc_request::rq_export.
void ptlrpc_request_committed (struct ptlrpc_request * req, int force)
Client-side portals API.
Everything to send requests, receive replies, request queues, request management, etc.
Definition at line 2601 of file client.c.
References obd_import::imp_lock, obd_import::imp_peer_committed_transno, list_empty(), ptlrpc_free_request(), ptlrpc_request::rq_import, ptlrpc_request::rq_replay_list, and ptlrpc_request::rq_transno.
Referenced by mdc_free_open().
void ptlrpc_request_free (struct ptlrpc_request * request)
For requests not from pool, free memory of the request structure.
For requests obtained from a pool earlier, return request back to pool.
Definition at line 875 of file client.c.
References __ptlrpc_free_req_to_pool(), ptlrpc_request_cache_free(), and ptlrpc_request::rq_pool.
Referenced by do_set_info_async(), ldlm_cli_cancel_req(), ldlm_enqueue_pack(), lfsck_async_request(), lfsck_layout_async_notify(), lfsck_layout_async_query(), lfsck_layout_master_conditional_destroy(), lfsck_layout_slave_check_pairs(), lfsck_namespace_notify_lmv_remote(), llog_client_open(), mdc_close(), mdc_create(), mdc_enqueue_pack(), mdc_fsync(), mdc_get_info_rpc(), mdc_get_remote_perm(), mdc_get_root(), mdc_getattr(), mdc_getattr_name(), mdc_getpage(), mdc_intent_getattr_pack(), mdc_intent_getxattr_pack(), mdc_intent_layout_pack(), mdc_intent_open_pack(), mdc_intent_unlink_pack(), mdc_ioc_hsm_current_action(), mdc_ioc_hsm_request(), mdc_ioc_hsm_state_get(), mdc_ioc_hsm_state_set(), mdc_ioc_swap_layouts(), mdc_link(), mdc_rename(), mdc_setattr(), mdc_unlink(), mdc_xattr_common(), osc_brw_prep_request(), osc_create(), osc_destroy(), osc_enqueue_base(), osc_getattr(), osc_io_data_version_start(), osc_ladvise_base(), osc_object_fiemap(), osc_punch_base(), osc_set_info_async(), osc_setattr(), osc_setattr_async(), osc_statfs(), osc_statfs_async(), osc_sync_base(), osp_get_lastfid_from_ost(), osp_it_fetch(), osp_obd_set_info_async(), osp_obd_statfs(), osp_object_truncate(), osp_precreate_cleanup_orphans(), osp_precreate_send(), osp_statfs_update(), ptlrpc_connect_import(), ptlrpc_request_alloc_pack(), qsd_fetch_index(), qsd_intent_lock(), and qsd_send_dqacq().
int ptlrpc_request_pack (struct ptlrpc_request * request, __u32 version, int opcode)
Pack request buffers for network transfer, performing necessary encryption steps if necessary.
Definition at line 762 of file client.c.
References LDLM_BL_CALLBACK, LDLM_CP_CALLBACK, LDLM_GL_CALLBACK, ptlrpc_request_bufs_pack(), RCL_CLIENT, req_capsule_shrink(), RMF_PTLRPC_BODY, and ptlrpc_request::rq_pill.
Referenced by do_set_info_async(), ldlm_cli_cancel_req(), ldlm_prep_elc_req(), lfsck_async_request(), lfsck_layout_async_notify(), lfsck_layout_async_query(), lfsck_layout_master_conditional_destroy(), lfsck_layout_slave_check_pairs(), lfsck_namespace_notify_lmv_remote(), llog_client_open(), mdc_close(), mdc_fsync(), mdc_get_info_rpc(), mdc_get_remote_perm(), mdc_get_root(), mdc_getattr(), mdc_getattr_name(), mdc_getpage(), mdc_ioc_hsm_current_action(), mdc_ioc_hsm_request(), mdc_ioc_hsm_state_get(), mdc_ioc_hsm_state_set(), mdc_xattr_common(), mgc_process_recover_log(), osc_brw_prep_request(), osc_create(), osc_getattr(), osc_io_data_version_start(), osc_ladvise_base(), osc_object_fiemap(), osc_punch_base(), osc_set_info_async(), osc_setattr(), osc_setattr_async(), osc_statfs(), osc_statfs_async(), osc_sync_base(), osp_get_lastfid_from_ost(), osp_it_fetch(), osp_obd_set_info_async(), osp_obd_statfs(), osp_object_truncate(), osp_precreate_cleanup_orphans(), osp_precreate_send(), osp_prep_inline_update_req(), osp_prep_update_req(), osp_statfs_update(), osp_sync_new_job(), ptlrpc_request_alloc_pack(), qsd_fetch_index(), and qsd_send_dqacq().
void ptlrpc_request_set_replen (struct ptlrpc_request * req)
Definition at line 1551 of file pack_generic.c.
References LUSTRE_MSG_MAGIC_V2, lustre_msg_size(), req_capsule::rc_area, RCL_SERVER, req_capsule_filled_sizes(), ptlrpc_request::rq_pill, ptlrpc_request::rq_replen, and ptlrpc_request::rq_reqmsg.
Referenced by do_set_info_async(), fld_client_rpc(), gss_do_ctx_init_rpc(), ldlm_cli_cancel_req(), ldlm_cli_convert(), ldlm_cli_enqueue(), ldlm_enqueue_pack(), lfsck_async_request(), lfsck_layout_async_notify(), lfsck_layout_async_query(), lfsck_layout_master_conditional_destroy(), lfsck_layout_slave_check_pairs(), lfsck_namespace_notify_lmv_remote(), llog_client_destroy(), llog_client_next_block(), llog_client_open(), llog_client_prev_block(), llog_client_read_header(), mdc_close(), mdc_create(), mdc_enqueue_pack(), mdc_fsync(), mdc_get_info_rpc(), mdc_get_remote_perm(), mdc_get_root(), mdc_getattr(), mdc_getattr_name(), mdc_getpage(), mdc_intent_getattr_pack(), mdc_intent_getxattr_pack(), mdc_intent_layout_pack(), mdc_intent_open_pack(), mdc_intent_unlink_pack(), mdc_ioc_hsm_ct_register(), mdc_ioc_hsm_ct_unregister(), mdc_ioc_hsm_current_action(), mdc_ioc_hsm_progress(), mdc_ioc_hsm_request(), mdc_ioc_hsm_state_get(), mdc_ioc_hsm_state_set(), mdc_ioc_swap_layouts(), mdc_link(), mdc_quotactl(), mdc_rename(), mdc_setattr(), mdc_statfs(), mdc_unlink(), mdc_xattr_common(), mgc_enqueue(), mgc_process_recover_log(), mgc_set_mgs_param(), mgc_target_register(), osc_brw_prep_request(), osc_create(), osc_destroy(), osc_enqueue_base(), osc_getattr(), osc_io_data_version_start(), osc_ladvise_base(), osc_object_fiemap(), osc_punch_base(), osc_quotactl(), osc_set_info_async(), osc_setattr(), osc_setattr_async(), osc_statfs(), osc_statfs_async(), osc_sync_base(), osp_get_lastfid_from_ost(), osp_it_fetch(), osp_obd_set_info_async(), osp_obd_statfs(), osp_object_truncate(), osp_precreate_cleanup_orphans(), osp_precreate_send(), osp_prep_inline_update_req(), osp_prep_update_req(), osp_statfs_update(), osp_sync_new_job(), ptlrpc_connect_import(), ptlrpc_disconnect_import(), ptlrpc_prep_ping(), qsd_fetch_index(), qsd_intent_lock(), qsd_send_dqacq(), replay_one_lock(), seq_client_rpc(), and signal_completed_replay().
void ptlrpc_restart_req (struct ptlrpc_request * req)
Definition at line 2742 of file client.c.
References D_HA, DEBUG_REQ, ptlrpc_client_wake_req(), ptlrpc_request::rq_lock, ptlrpc_request::rq_restart, ptlrpc_request::rq_status, and ptlrpc_request::rq_timedout.
void ptlrpc_retain_replayable_request (struct ptlrpc_request * req, struct obd_import * imp)
Add a request to import replay_list.
Must be called under imp_lock
Definition at line 2769 of file client.c.
References D_EMERG, DEBUG_REQ, obd_import::imp_lock, obd_import::imp_replay_list, obd_import::imp_replayable, LASSERT, LBUG, list_add(), list_empty(), list_entry, list_for_each_prev, lustre_msg_add_flags(), lustre_msg_clear_flags(), MSG_REPLAY, MSG_RESENT, ptlrpc_request_addref(), ptlrpc_request::rq_lock, ptlrpc_request::rq_replay_list, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_resend, ptlrpc_request::rq_transno, and ptlrpc_request::rq_xid.
Referenced by after_reply().
static const char* ptlrpc_rqphase2str (struct ptlrpc_request * req) [inline, static]
Convert numerical request phase of the request req into text stringi description.
Definition at line 1254 of file lustre_net.h.
References ptlrpc_phase2str(), and ptlrpc_request::rq_phase.
Referenced by ptlrpc_rqphase_move().
static void ptlrpc_rqphase_move (struct ptlrpc_request * req, enum rq_phase new_phase) [inline, static]
Change request phase of req to new_phase.
Definition at line 2428 of file lustre_net.h.
References D_INFO, DEBUG_REQ, obd_import::imp_unregistering, ptlrpc_phase2str(), ptlrpc_rqphase2str(), ptlrpc_request::rq_import, ptlrpc_request::rq_next_phase, ptlrpc_request::rq_phase, and RQ_PHASE_UNREGISTERING.
Referenced by ptlrpc_check_set(), ptlrpc_send_new_req(), ptlrpc_server_handle_request(), ptlrpc_unregister_bulk(), and ptlrpc_unregister_reply().
static void ptlrpc_rs_addref (struct ptlrpc_reply_state * rs) [inline, static]
Definition at line 2511 of file lustre_net.h.
References LASSERT, and ptlrpc_reply_state::rs_refcount.
Referenced by ptlrpc_send_reply(), and target_send_reply().
static void ptlrpc_rs_decref (struct ptlrpc_reply_state * rs) [inline, static]
Definition at line 2518 of file lustre_net.h.
References LASSERT, lustre_free_reply_state(), and ptlrpc_reply_state::rs_refcount.
Referenced by ptlrpc_handle_rs(), ptlrpc_req_drop_rs(), reply_out_callback(), and req_capsule_server_grow().
__u64 ptlrpc_sample_next_xid (void)
Get a glimpse at what next xid value might have been.
Returns possible next xid.
Definition at line 3230 of file client.c.
References __u64, and PTLRPC_BULK_OPS_COUNT.
Referenced by osc_process_ar().
void ptlrpc_save_lock (struct ptlrpc_request * req, struct lustre_handle * lock, int mode, int no_ack)
Server-side services API.
Register/unregister service, request state management, service thread management
Server-side services API.
Puts a lock and its mode into reply state assotiated to request reply.
Definition at line 183 of file service.c.
References obd_export::exp_disconnected, LASSERT, ldlm_lock_decref(), ptlrpc_request::rq_export, ptlrpc_reply_state::rs_difficult, ptlrpc_reply_state::rs_locks, RS_MAX_LOCKS, ptlrpc_reply_state::rs_modes, ptlrpc_reply_state::rs_nlocks, and ptlrpc_reply_state::rs_no_ack.
Referenced by mdt_save_lock(), and mdt_steal_ack_locks().
void ptlrpc_schedule_difficult_reply (struct ptlrpc_reply_state * rs)
Definition at line 387 of file service.c.
References ENTRY, EXIT, LASSERT, list_del_init(), ptlrpc_dispatch_difficult_reply(), ptlrpc_reply_state::rs_difficult, ptlrpc_reply_state::rs_list, ptlrpc_reply_state::rs_lock, ptlrpc_reply_state::rs_scheduled, ptlrpc_reply_state::rs_scheduled_ever, and ptlrpc_reply_state::rs_svcpt.
Referenced by mdt_steal_ack_locks(), ptlrpc_service_purge_all(), and reply_out_callback().
int ptlrpc_send_error (struct ptlrpc_request * req, int may_be_difficult)
For request req send an error reply back.
Create empty reply buffers if necessary.
Definition at line 626 of file niobuf.c.
References ENTRY, lustre_pack_reply(), PTL_RPC_MSG_ERR, ptlrpc_send_reply(), RETURN, ptlrpc_request::rq_no_reply, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_status, and ptlrpc_request::rq_type.
Referenced by ptlrpc_error(), and target_send_reply_msg().
static int ptlrpc_send_limit_expired (struct ptlrpc_request * req) [inline, static]
Definition at line 2552 of file lustre_net.h.
References cfs_time_add(), cfs_time_before(), cfs_time_current(), and cfs_time_seconds().
Referenced by ptlrpc_import_delay_req(), and ptlrpc_no_resend().
int ptlrpc_send_reply (struct ptlrpc_request * req, int flags)
Send request reply from request req reply buffer.
flags defines reply types Returns 0 on success or error code
Definition at line 528 of file niobuf.c.
References ptlrpc_cb_id::cbid_arg, ptlrpc_cb_id::cbid_fn, CDEBUG, CERROR, cfs_time_current_sec(), D_HA, obd_export::exp_connection, obd_export::exp_obd, LASSERT, LNET_ACK_REQ, LNET_NOACK_REQ, lustre_msg_get_opc(), lustre_msg_set_opc(), lustre_msg_set_status(), lustre_msg_set_type(), lustre_shrink_msg(), obd_device::obd_fail, obd_device::obd_minor, PTL_RPC_MSG_ERR, PTL_RPC_MSG_REPLY, ptl_send_buf(), ptlrpc_at_set_reply(), ptlrpc_connection_addref(), ptlrpc_connection_get(), ptlrpc_connection_put(), PTLRPC_REPLY_MAYBE_DIFFICULT, ptlrpc_req2svc(), ptlrpc_req_drop_rs(), ptlrpc_rs_addref(), ptlrpc_status_hton(), reply_out_callback(), ptlrpc_request::rq_export, ptlrpc_request::rq_no_reply, ptlrpc_request::rq_peer, ptlrpc_request::rq_replen, ptlrpc_request::rq_reply_off, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_self, ptlrpc_request::rq_sent, ptlrpc_request::rq_status, ptlrpc_request::rq_type, ptlrpc_request::rq_xid, ptlrpc_reply_state::rs_cb_id, ptlrpc_reply_state::rs_difficult, ptlrpc_reply_state::rs_md_h, ptlrpc_reply_state::rs_msg, ptlrpc_reply_state::rs_no_ack, ptlrpc_reply_state::rs_repbuf, ptlrpc_reply_state::rs_repdata_len, sptlrpc_svc_wrap_reply(), target_pack_pool_reply(), and unlikely.
Referenced by ptlrpc_at_send_early_reply(), ptlrpc_reply(), ptlrpc_send_error(), and target_send_reply_msg().
void ptlrpc_server_drop_request (struct ptlrpc_request * req)
drop a reference count of the request.
if it reaches 0, we either put it into history list, or free it immediately.
Definition at line 859 of file service.c.
References class_export_put(), LASSERT, LCS_ENTERED, likely, list_add(), list_add_tail(), list_del(), list_del_init(), list_empty(), list_entry, list_for_each, list_for_each_safe, lu_context_exit(), lu_context_fini(), list_head::next, ptlrpc_at_remove_timed(), ptlrpc_server_free_request(), ptlrpc_request::rq_at_linked, ptlrpc_request::rq_export, ptlrpc_request::rq_list, ptlrpc_request::rq_refcount, ptlrpc_request_buffer_desc::rqbd_list, ptlrpc_request_buffer_desc::rqbd_refcount, ptlrpc_request_buffer_desc::rqbd_req, ptlrpc_request_buffer_desc::rqbd_reqs, ptlrpc_request_buffer_desc::rqbd_svcpt, ptlrpc_service_part::scp_hist_nrqbds, ptlrpc_service_part::scp_hist_rqbds, ptlrpc_service_part::scp_hist_seq_culled, ptlrpc_service_part::scp_rqbd_idle, and ptlrpc_service::srv_hist_nrqbds_cpt_max.
Referenced by ptlrpc_at_check_timed(), and ptlrpc_server_finish_request().
static int ptlrpc_server_get_timeout (struct ptlrpc_service_part * svcpt) [inline, static]
Definition at line 2574 of file lustre_net.h.
References at_get(), AT_OFF, obd_timeout, and ptlrpc_service_part::scp_at_estimate.
Referenced by __attribute__(), and ptlrpc_main().
int ptlrpc_service_health_check (struct ptlrpc_service *)
Definition at line 3227 of file service.c.
References ptlrpc_service_for_each_part, and ptlrpc_svcpt_health_check().
Referenced by mds_health_check(), mgs_health_check(), and ost_health_check().
int ptlrpc_set_add_cb (struct ptlrpc_request_set * set, set_interpreter_func fn, void * data)
Add a callback function fn to the set.
This function would be called when all requests on this set are completed. The function will be passed data argument.
Definition at line 1030 of file client.c.
References list_add_tail(), OBD_ALLOC_PTR, ptlrpc_set_cbdata::psc_data, ptlrpc_set_cbdata::psc_interpret, ptlrpc_set_cbdata::psc_item, and RETURN.
void ptlrpc_set_add_req (struct ptlrpc_request_set * set, struct ptlrpc_request * req)
Add a new request to the general purpose request set.
Assumes request reference from the caller.
Definition at line 1050 of file client.c.
References cfs_time_current(), LASSERT, list_add_tail(), list_empty(), lustre_msg_set_jobid(), ptlrpc_send_new_req(), ptlrpc_request::rq_allow_intr, and ptlrpc_request::rq_reqmsg.
Referenced by do_set_info_async(), lfsck_async_request(), lfsck_layout_async_notify(), lfsck_layout_async_query(), osc_enqueue_base(), osc_ladvise_base(), osc_punch_base(), osc_set_info_async(), osc_setattr_async(), osc_statfs_async(), osc_sync_base(), osp_obd_set_info_async(), and ptlrpc_queue_wait().
void ptlrpc_set_destroy (struct ptlrpc_request_set * set)
Wind down and free request set structure previously allocated with ptlrpc_prep_set.
Ensures that all requests on the set have completed and removes all requests from the request list in a set. If any unsent request happen to be on the list, pretends that they got an error in flight and calls their completion handler.
Definition at line 973 of file client.c.
References ENTRY, EXIT, LASSERT, LASSERTF, list_del_init(), list_entry, list_for_each, list_for_each_safe, list_head::next, ptlrpc_req_finished(), ptlrpc_req_interpret(), ptlrpc_reqset_put(), ptlrpc_request::rq_invalid_rqset, ptlrpc_request::rq_lock, ptlrpc_request::rq_phase, RQ_PHASE_COMPLETE, RQ_PHASE_NEW, and rq_set_chain.
Referenced by ldlm_run_ast_work(), lfsck_assistant_notify_others(), lfsck_assistant_query_others(), lfsck_layout_assistant_sync_failures(), lfsck_layout_slave_notify_master(), lfsck_layout_slave_query_master(), lfsck_namespace_assistant_sync_failures(), lfsck_query_all(), lfsck_start_all(), lfsck_stop_all(), lfsck_stop_notify(), lod_obd_set_info_async(), lov_set_info_async(), lov_statfs(), obd_statfs_rqset(), ptlrpc_queue_wait(), ptlrpcd_free(), and ptlrpcd_start().
int ptlrpc_set_wait (struct ptlrpc_request_set * set)
Send all unset request from the set and then wait untill all requests in the set complete (either get a reply, timeout, get an error or otherwise be interrupted).
Returns 0 on success or error code otherwise.
Definition at line 2260 of file client.c.
References CDEBUG, cfs_block_sigsinv(), cfs_restore_sigs(), cfs_time_seconds(), D_RPCTRACE, ENTRY, l_wait_event, LASSERT, list_del_init(), list_empty(), list_entry, list_for_each, list_for_each_entry_safe, LUSTRE_FATAL_SIGS, l_wait_info::lwi_allow_intr, LWI_TIMEOUT, LWI_TIMEOUT_INTR_ALL, OBD_FREE_PTR, ptlrpc_set_cbdata::psc_data, ptlrpc_set_cbdata::psc_interpret, ptlrpc_set_cbdata::psc_item, ptlrpc_check_set(), ptlrpc_expired_set(), ptlrpc_interrupted_set(), ptlrpc_send_new_req(), ptlrpc_set_next_timeout(), ptlrpc_set_producer(), RETURN, ptlrpc_request::rq_invalid_rqset, ptlrpc_request::rq_lock, ptlrpc_request::rq_phase, RQ_PHASE_COMPLETE, RQ_PHASE_NEW, rq_set_chain, ptlrpc_request::rq_status, and timeout.
Referenced by ldlm_run_ast_work(), lfsck_assistant_notify_others(), lfsck_assistant_query_others(), lfsck_layout_assistant_sync_failures(), lfsck_layout_slave_notify_master(), lfsck_layout_slave_query_master(), lfsck_namespace_assistant_sync_failures(), lfsck_query_all(), lfsck_start_all(), lfsck_stop_all(), lfsck_stop_notify(), lod_obd_set_info_async(), lov_set_info_async(), lov_statfs(), obd_statfs_rqset(), ptlrpc_queue_wait(), and ptlrpcd().
int ptlrpc_start_threads (struct ptlrpc_service * svc)
Definition at line 2751 of file service.c.
References CERROR, ENTRY, LASSERT, PTLRPC_NTHRS_INIT, ptlrpc_start_thread(), ptlrpc_stop_all_threads(), RETURN, ptlrpc_service::srv_ncpts, ptlrpc_service::srv_nthrs_cpt_init, ptlrpc_service::srv_parts, and ptlrpc_service::srv_thread_name.
Referenced by ptlrpc_register_service().
static int ptlrpc_status_hton (int h) [inline, static]
Definition at line 2395 of file lustre_net.h.
References lustre_errno_hton().
Referenced by mdt_intent_opc(), object_update_result_insert(), ofd_intent_policy(), out_read(), ptlrpc_send_reply(), tgt_client_data_write(), and tgt_reply_data_write().
static int ptlrpc_status_ntoh (int n) [inline, static]
Definition at line 2407 of file lustre_net.h.
References lustre_errno_ntoh().
Referenced by lustre_unpack_ptlrpc_body_v2(), mdc_enqueue(), mdc_intent_getattr_async_interpret(), object_update_result_data_get(), osc_enqueue_fini(), tgt_client_data_read(), and tgt_reply_data_write().
void ptlrpc_stop_all_threads (struct ptlrpc_service * svc)
Stops all threads of a particular service svc.
Definition at line 2737 of file service.c.
References ENTRY, EXIT, ptlrpc_service_for_each_part, and ptlrpc_svcpt_stop_threads().
Referenced by ptlrpc_start_threads(), and ptlrpc_unregister_service().
int ptlrpc_unpack_rep_msg (struct ptlrpc_request * req, int len)
Definition at line 611 of file pack_generic.c.
References __lustre_unpack_msg(), lustre_set_rep_swabbed(), MSG_PTLRPC_HEADER_OFF, and ptlrpc_request::rq_repmsg.
Referenced by unpack_reply().
int ptlrpc_unpack_req_msg (struct ptlrpc_request * req, int len)
Definition at line 600 of file pack_generic.c.
References __lustre_unpack_msg(), lustre_set_req_swabbed(), MSG_PTLRPC_HEADER_OFF, and ptlrpc_request::rq_reqmsg.
Referenced by ptlrpc_server_handle_req_in().
int ptlrpc_unregister_bulk (struct ptlrpc_request * req, int async)
Disconnect a bulk desc from the network.
Idempotent. Not thread-safe (i.e. only interlocks with completion callback). Returns 1 on success or 0 if network unregistration failed for whatever reason.
Definition at line 420 of file niobuf.c.
References ptlrpc_bulk_desc::bd_md_max_brw, ptlrpc_bulk_desc::bd_mds, ptlrpc_bulk_desc::bd_req, cfs_time_current_sec(), cfs_time_seconds(), D_WARNING, DEBUG_REQ, ENTRY, l_wait_event, LASSERT, LONG_UNLINK, LWI_TIMEOUT_INTERVAL, mdunlink_iterate_helper(), OBD_FAIL_CHECK, OBD_FAIL_PTLRPC_LONG_BULK_UNLINK, ptlrpc_client_bulk_active(), ptlrpc_rqphase_move(), RETURN, ptlrpc_request::rq_next_phase, and RQ_PHASE_UNREGISTERING.
Referenced by ptl_send_rpc(), ptlrpc_check_set(), and ptlrpc_expire_one_request().
int ptlrpc_unregister_service (struct ptlrpc_service * service)
Definition at line 3160 of file service.c.
References CDEBUG, D_NET, ENTRY, list_del_init(), ptlrpc_all_services_mutex, ptlrpc_lprocfs_unregister_service, ptlrpc_service_del_atimer(), ptlrpc_service_free(), ptlrpc_service_nrs_cleanup(), ptlrpc_service_purge_all(), ptlrpc_service_unlink_rqbd(), ptlrpc_stop_all_threads(), RETURN, ptlrpc_service::srv_is_stopping, ptlrpc_service::srv_list, and ptlrpc_service::srv_name.
Referenced by ldlm_cleanup(), mds_stop_ptlrpc_service(), mgs_device_fini(), ost_cleanup(), ost_setup(), and ptlrpc_register_service().
void ptlrpc_update_export_timer (struct obd_export * exp, long extra_delay)
This function makes sure dead exports are evicted in a timely manner.
This function is only called when some export receives a message (i.e., the network is up.)
Definition at line 1037 of file service.c.
References CDEBUG, cfs_time_current_sec(), CFS_TIME_T, D_HA, ENTRY, EXIT, obd_export::exp_last_request_time, obd_export::exp_obd, obd_export::exp_obd_chain_timed, LASSERT, list_empty(), list_entry, list_move_tail(), list_head::next, obd_device::obd_dev_lock, obd_device::obd_eviction_timer, obd_export_nid2str(), obd_device::obd_exports_timed, obd_device::obd_name, obd_device::obd_recovering, PING_EVICT_TIMEOUT, ping_evictor_wake(), PING_INTERVAL, and RETURN_EXIT.
Referenced by ptlrpc_server_handle_req_in(), and ptlrpc_server_handle_request().
struct ptlrpc_connection* ptlrpc_uuid_to_connection (struct obd_uuid * uuid) [read]
Return PortalRPC connection for remore uud uuid.
Definition at line 86 of file client.c.
References ptlrpc_connection::c_remote_uuid, CDEBUG, CNETERR, D_INFO, ptlrpc_connection_get(), ptlrpc_uuid_to_peer(), and obd_uuid::uuid.
Referenced by import_set_conn().
int ptlrpc_uuid_to_peer (struct obd_uuid * uuid, lnet_process_id_t * peer, lnet_nid_t * self)
Definition at line 500 of file events.c.
References CDEBUG, D_NET, libcfs_id2str(), LNET_MKNET(), LNET_MKNID(), LNET_PID_LUSTRE, LNetDist(), LOLND, lustre_uuid_to_peer(), lnet_process_id_t::nid, order, lnet_process_id_t::pid, and obd_uuid::uuid.
Referenced by ptlrpc_uuid_to_connection().
void ptlrpcd_add_req (struct ptlrpc_request * req)
Requests that are added to the ptlrpcd queue are sent via ptlrpcd_check->ptlrpc_check_set().
Definition at line 268 of file ptlrpcd.c.
References back_to_sleep(), cfs_time_seconds(), D_INFO, DEBUG_REQ, l_wait_event, LASSERT, LUSTRE_IMP_REPLAY, lustre_msg_set_jobid(), LWI_TIMEOUT, ptlrpcd_ctl::pc_index, ptlrpcd_ctl::pc_name, ptlrpc_set_add_new_req(), ptlrpcd_select_pc(), ptlrpc_request::rq_invalid_rqset, ptlrpc_request::rq_lock, ptlrpc_request::rq_phase, RQ_PHASE_NEW, and ptlrpc_request::rq_reqmsg.
Referenced by ldlm_cli_cancel_req(), mdc_intent_getattr_async(), osc_brw_redo_request(), osc_build_rpc(), osc_destroy(), osc_enqueue_base(), osc_io_data_version_start(), osc_ladvise_base(), osc_punch_base(), osc_set_info_async(), osc_setattr_async(), osc_sync_base(), osp_send_update_req(), osp_statfs_update(), osp_sync_send_new_rpc(), osp_unplug_async_request(), ptlrpc_connect_import(), ptlrpc_ping(), ptlrpc_replay_req(), ptlrpcd_add_work_req(), qsd_intent_lock(), qsd_send_dqacq(), replay_one_lock(), and signal_completed_replay().
void ptlrpcd_add_rqset (struct ptlrpc_request_set * set)
Move all request from an existing request set to the ptlrpcd queue.
All requests from the set must be in phase RQ_PHASE_NEW.
Definition at line 200 of file ptlrpcd.c.
References cfs_time_current(), LASSERT, list_entry, list_for_each_safe, list_splice_init(), ptlrpcd_ctl::pc_npartners, ptlrpcd_ctl::pc_partners, ptlrpcd_ctl::pc_set, ptlrpcd_select_pc(), ptlrpc_request::rq_phase, RQ_PHASE_NEW, rq_set_chain, and ptlrpc_request_set::set_waitq.
int ptlrpcd_addref (void)
Definition at line 955 of file ptlrpcd.c.
References ENTRY, ptlrpcd_init(), ptlrpcd_mutex, ptlrpcd_users, and RETURN.
Referenced by lwp_init0(), mdc_setup(), mgc_setup(), osc_setup(), osp_init0(), and ptlrpc_init_portals().
void* ptlrpcd_alloc_work (struct obd_import * imp, int(*)(const struct lu_env *, void *) cb, void * data)
Create a work for ptlrpc.
Definition at line 3315 of file client.c.
References ptlrpc_work_async_args::cb, cb(), ptlrpc_work_async_args::cbdata, CERROR, class_import_get(), CLASSERT, ENTRY, LUSTRE_IMP_FULL, PTL_RPC_MSG_REQUEST, ptlrpc_cli_req_init(), ptlrpc_req_async_args, ptlrpc_request_cache_alloc(), req_capsule::rc_fmt, RETURN, ptlrpc_request::rq_import, ptlrpc_request::rq_no_delay, ptlrpc_request::rq_no_resend, ptlrpc_request::rq_pill, ptlrpc_request::rq_type, and work_interpreter().
Referenced by osc_setup().
void ptlrpcd_decref (void)
Definition at line 971 of file ptlrpcd.c.
References ptlrpcd_fini(), ptlrpcd_mutex, and ptlrpcd_users.
Referenced by lwp_device_fini(), lwp_init0(), mdc_cleanup(), mdc_setup(), mgc_cleanup(), mgc_setup(), osc_cleanup(), osc_setup(), osp_device_fini(), osp_init0(), and ptlrpc_exit_portals().
void ptlrpcd_destroy_work (void * handler)
Definition at line 3353 of file client.c.
References ptlrpc_req_finished().
Referenced by osc_precleanup(), and osc_setup().
void ptlrpcd_free (struct ptlrpcd_ctl * pc)
Definition at line 666 of file ptlrpcd.c.
References CWARN, ENTRY, EXIT, LASSERT, lu_env::le_ctx, LIOD_FORCE, LIOD_START, LIOD_STOP, lu_context_fini(), OBD_FREE, ptlrpcd_ctl::pc_env, ptlrpcd_ctl::pc_error, ptlrpcd_ctl::pc_finishing, ptlrpcd_ctl::pc_flags, ptlrpcd_ctl::pc_lock, ptlrpcd_ctl::pc_npartners, ptlrpcd_ctl::pc_partners, ptlrpcd_ctl::pc_set, and ptlrpc_set_destroy().
Referenced by ptlrpcd_fini().
int ptlrpcd_queue_work (void * handler)
Definition at line 3362 of file client.c.
References LASSERT, ptlrpcd_add_work_req(), and ptlrpc_request::rq_refcount.
Referenced by lru_queue_work(), osc_dec_unstable_pages(), osc_io_unplug0(), osc_lru_add_batch(), osc_lru_del(), osc_lru_reclaim(), and osc_lru_reserve().
void ptlrpcd_stop (struct ptlrpcd_ctl * pc, int force)
Definition at line 648 of file ptlrpcd.c.
References CWARN, ENTRY, EXIT, LIOD_FORCE, LIOD_START, LIOD_STOP, ptlrpcd_ctl::pc_flags, ptlrpcd_ctl::pc_set, and ptlrpc_request_set::set_waitq.
Referenced by ptlrpcd_fini().
void ptlrpcd_wake (struct ptlrpc_request * req)
Definition at line 161 of file ptlrpcd.c.
References LASSERT.
void reply_in_callback (lnet_event_t * ev)
Definition at line 91 of file events.c.
References ptlrpc_cb_id::cbid_arg, CDEBUG, cfs_time_current_sec(), D_ADAPTTO, D_INFO, D_NET, D_RPCTRACE, DEBUG_REQ, ENTRY, EXIT, obd_import::imp_last_reply_time, LASSERT, LNET_EVENT_PUT, LNET_EVENT_UNLINK, LNET_MD_MANAGE_REMOTE, lustre_msg_get_flags(), lustre_msghdr_get_flags(), lnet_event_t::md, lnet_event_t::mlength, MSGHDR_AT_SUPPORT, lnet_event_t::offset, lnet_md_t::options, ptlrpc_client_wake_req(), lnet_event_t::rlength, ptlrpc_request::rq_early, ptlrpc_request::rq_early_count, ptlrpc_request::rq_import, ptlrpc_request::rq_lock, ptlrpc_request::rq_nob_received, ptlrpc_request::rq_receiving_reply, ptlrpc_request::rq_rep_swab_mask, ptlrpc_request::rq_repbuf, ptlrpc_request::rq_repbuf_len, ptlrpc_request::rq_replen, ptlrpc_request::rq_replied, ptlrpc_request::rq_reply_off, ptlrpc_request::rq_reply_truncated, ptlrpc_request::rq_reply_unlinked, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_resend, ptlrpc_request::rq_status, lnet_md_t::start, lnet_event_t::status, lnet_event_t::type, lnet_event_t::unlinked, and lnet_md_t::user_ptr.
Referenced by ptlrpc_master_callback(), and ptlrpc_request_bufs_pack().
void reply_out_callback (lnet_event_t * ev)
Definition at line 390 of file events.c.
References ptlrpc_cb_id::cbid_arg, ENTRY, EXIT, obd_export::exp_obd, LASSERT, LNET_EVENT_ACK, LNET_EVENT_SEND, LNET_EVENT_UNLINK, lnet_event_t::md, obd_device::obd_last_committed, ptlrpc_rs_decref(), ptlrpc_schedule_difficult_reply(), ptlrpc_reply_state::rs_difficult, ptlrpc_reply_state::rs_export, ptlrpc_reply_state::rs_lock, ptlrpc_reply_state::rs_no_ack, ptlrpc_reply_state::rs_on_net, ptlrpc_reply_state::rs_svcpt, ptlrpc_reply_state::rs_transno, lnet_event_t::type, lnet_event_t::unlinked, and lnet_md_t::user_ptr.
Referenced by lustre_pack_reply_v2(), ptlrpc_master_callback(), and ptlrpc_send_reply().
void request_in_callback (lnet_event_t * ev)
Definition at line 291 of file events.c.
References ptlrpc_cb_id::cbid_arg, CDEBUG, CERROR, CWARN, D_ERROR, D_INFO, D_NET, D_RPCTRACE, ENTRY, EXIT, lnet_event_t::initiator, LASSERT, libcfs_id2str(), list_add_tail(), LNET_EVENT_PUT, LNET_EVENT_UNLINK, LPU64, lnet_event_t::match_bits, lnet_event_t::md, lnet_event_t::mlength, lnet_process_id_t::nid, lnet_event_t::offset, ptlrpc_req_add_history(), ptlrpc_request_cache_alloc(), ptlrpc_srv_req_init(), ptlrpc_request::rq_list, ptlrpc_request::rq_peer, ptlrpc_request::rq_phase, RQ_PHASE_NEW, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqdata_len, ptlrpc_request::rq_self, ptlrpc_request::rq_xid, ptlrpc_request_buffer_desc::rqbd_buffer, ptlrpc_request_buffer_desc::rqbd_refcount, ptlrpc_request_buffer_desc::rqbd_req, ptlrpc_request_buffer_desc::rqbd_svcpt, ptlrpc_service_part::scp_nreqs_incoming, ptlrpc_service_part::scp_nrqbds_posted, ptlrpc_service_part::scp_req_incoming, ptlrpc_service_part::scp_waitq, service, ptlrpc_service::srv_buf_size, ptlrpc_service::srv_name, lnet_md_t::start, lnet_event_t::status, lnet_event_t::target, test_req_buffer_pressure, lnet_event_t::type, lnet_event_t::unlinked, and lnet_md_t::user_ptr.
Referenced by ptlrpc_alloc_rqbd(), and ptlrpc_master_callback().
void request_out_callback (lnet_event_t * ev)
These callbacks are invoked by LNet when something happened to underlying buffer.
Definition at line 51 of file events.c.
References ptlrpc_cb_id::cbid_arg, cfs_time_current_sec(), D_NET, DEBUG_REQ, ENTRY, EXIT, LASSERT, LNET_EVENT_SEND, LNET_EVENT_UNLINK, lnet_event_t::md, ptlrpc_client_wake_req(), ptlrpc_req_finished(), ptlrpc_request::rq_lock, ptlrpc_request::rq_net_err, ptlrpc_request::rq_reply_unlinked, ptlrpc_request::rq_req_unlinked, sptlrpc_request_out_callback(), lnet_event_t::status, lnet_event_t::type, lnet_event_t::unlinked, and lnet_md_t::user_ptr.
Referenced by ptlrpc_master_callback(), and ptlrpc_request_bufs_pack().
static void thread_add_flags (struct ptlrpc_thread * thread, __u32 flags) [inline, static]
Definition at line 1582 of file lustre_net.h.
References ptlrpc_thread::t_flags.
Referenced by ptlrpc_main(), ptlrpc_pinger_wake_up(), ptlrpc_start_thread(), ptlrpc_svcpt_stop_threads(), and sptlrpc_gc_add_ctx().
static void thread_clear_flags (struct ptlrpc_thread * thread, __u32 flags) [inline, static]
Definition at line 1572 of file lustre_net.h.
References ptlrpc_thread::t_flags.
Referenced by ptlrpc_main(), and sec_gc_main().
static int thread_is_event (struct ptlrpc_thread * thread) [inline, static]
Definition at line 1562 of file lustre_net.h.
References SVC_EVENT, and ptlrpc_thread::t_flags.
Referenced by ptlrpc_pinger_main().
static int thread_is_init (struct ptlrpc_thread * thread) [inline, static]
Definition at line 1537 of file lustre_net.h.
References ptlrpc_thread::t_flags.
Referenced by do_osd_scrub_stop(), lfsck_instance_cleanup(), lfsck_layout_master_data_release(), lfsck_layout_master_quit(), lfsck_namespace_data_release(), lfsck_namespace_quit(), lfsck_quit_generic(), lfsck_start(), lfsck_stop(), ll_agl_thread(), ll_statahead_thread(), ofd_stop_inconsistency_verification_thread(), ptlrpc_start_pinger(), and ptlrpc_stop_pinger().
static int thread_is_running (struct ptlrpc_thread * thread) [inline, static]
Definition at line 1557 of file lustre_net.h.
References SVC_RUNNING, and ptlrpc_thread::t_flags.
Referenced by do_osd_scrub_start(), lfsck_assistant_engine(), lfsck_checkpoint_generic(), lfsck_control_speed(), lfsck_control_speed_by_self(), lfsck_layout_assistant_handler_p2(), lfsck_layout_lastid_load(), lfsck_layout_scan_orphan(), lfsck_layout_scan_stripes(), lfsck_layout_slave_double_scan(), lfsck_layout_slave_exec_oit(), lfsck_layout_slave_join(), lfsck_master_dir_engine(), lfsck_master_engine(), lfsck_master_oit_engine(), lfsck_namespace_double_scan_one_trace_file(), lfsck_namespace_exec_dir(), lfsck_namespace_rescan_striped_dir(), lfsck_namespace_scan_local_lpf(), lfsck_namespace_scan_shard(), lfsck_post(), lfsck_start(), lfsck_start_assistant(), ll_agl_thread(), ll_deauthorize_statahead(), ll_start_agl(), ll_statahead_thread(), lwp_notify_users(), ofd_inconsistency_verification_main(), ofd_start_inconsistency_verification_thread(), osd_consistency_check(), osd_fid_lookup(), osd_inode_iteration(), osd_oii_insert(), osd_otable_it_next(), osd_otable_it_wakeup(), osd_preload_next(), osd_scrub_dump(), osd_scrub_main(), osd_scrub_next(), osd_scrub_wakeup(), ptlrpc_start_pinger(), ptlrpc_start_thread(), qmt_reba_thread(), qmt_start_reba_thread(), qsd_reint_main(), qsd_start_reint_thread(), qsd_start_upd_thread(), qsd_upd_thread(), sptlrpc_gc_init(), and start_statahead_thread().
static int thread_is_signal (struct ptlrpc_thread * thread) [inline, static]
Definition at line 1567 of file lustre_net.h.
References SVC_SIGNAL, and ptlrpc_thread::t_flags.
Referenced by sec_gc_main().
static int thread_is_starting (struct ptlrpc_thread * thread) [inline, static]
Definition at line 1552 of file lustre_net.h.
References SVC_STARTING, and ptlrpc_thread::t_flags.
Referenced by ptlrpc_main().
static int thread_is_stopped (struct ptlrpc_thread * thread) [inline, static]
Definition at line 1542 of file lustre_net.h.
References SVC_STOPPED, and ptlrpc_thread::t_flags.
Referenced by do_osd_scrub_start(), do_osd_scrub_stop(), lfsck_checkpoint_generic(), lfsck_double_scan_generic(), lfsck_instance_cleanup(), lfsck_layout_master_data_release(), lfsck_layout_master_double_scan(), lfsck_layout_master_quit(), lfsck_layout_scan_stripes(), lfsck_namespace_data_release(), lfsck_namespace_double_scan(), lfsck_namespace_exec_dir(), lfsck_namespace_quit(), lfsck_post_generic(), lfsck_quit_generic(), lfsck_start(), lfsck_start_assistant(), lfsck_stop(), ll_sai_put(), ll_start_agl(), ll_statahead_interpret(), ll_statahead_thread(), lwp_device_fini(), lwp_notify_users(), ofd_start_inconsistency_verification_thread(), ofd_stop_inconsistency_verification_thread(), ptlrpc_start_pinger(), ptlrpc_start_thread(), ptlrpc_stop_pinger(), ptlrpc_svcpt_stop_threads(), qmt_start_reba_thread(), qmt_stop_reba_thread(), qsd_start_reint_thread(), qsd_start_upd_thread(), qsd_stop_reint_thread(), qsd_stop_upd_thread(), sptlrpc_gc_fini(), and start_statahead_thread().
static int thread_is_stopping (struct ptlrpc_thread * thread) [inline, static]
Definition at line 1547 of file lustre_net.h.
References SVC_STOPPING, and ptlrpc_thread::t_flags.
Referenced by do_osd_scrub_start(), ptlrpc_pinger_main(), ptlrpc_start_thread(), ptlrpc_thread_stopping(), and sec_gc_main().
static void thread_set_flags (struct ptlrpc_thread * thread, __u32 flags) [inline, static]
Definition at line 1577 of file lustre_net.h.
References ptlrpc_thread::t_flags.
Referenced by do_osd_scrub_start(), do_osd_scrub_stop(), lfsck_assistant_engine(), lfsck_master_dir_engine(), lfsck_master_engine(), lfsck_master_oit_engine(), lfsck_namespace_scan_shard(), lfsck_start(), lfsck_start_assistant(), lfsck_stop(), ll_agl_thread(), ll_deauthorize_statahead(), ll_start_agl(), ll_statahead_thread(), lwp_notify_main(), lwp_notify_users(), lwp_setup(), ofd_inconsistency_verification_main(), ofd_start_inconsistency_verification_thread(), ofd_stop_inconsistency_verification_thread(), osd_scrub_main(), osd_scrub_next(), osd_scrub_post(), osd_scrub_prep(), ptlrpc_pinger_main(), ptlrpc_stop_pinger(), qmt_device_init0(), qmt_reba_thread(), qmt_start_reba_thread(), qmt_stop_reba_thread(), qsd_init(), qsd_qtype_init(), qsd_reint_main(), qsd_start_reint_thread(), qsd_start_upd_thread(), qsd_stop_reint_thread(), qsd_stop_upd_thread(), qsd_upd_thread(), sec_gc_main(), and sptlrpc_gc_fini().
static int thread_test_and_clear_flags (struct ptlrpc_thread * thread, __u32 flags) [inline, static]
Definition at line 1587 of file lustre_net.h.
References ptlrpc_thread::t_flags.
Referenced by ptlrpc_main(), ptlrpc_pinger_main(), and sec_gc_main().
Variable Documentation
struct llog_operations llog_client_ops
Definition at line 355 of file llog_client.c.
Referenced by mdc_llog_init(), and mgc_llog_init().
struct ptlrpc_bulk_frag_ops ptlrpc_bulk_kiov_nopin_ops
Definition at line 56 of file client.c.
Referenced by tgt_brw_read(), and tgt_brw_write().
struct ptlrpc_bulk_frag_ops ptlrpc_bulk_kiov_pin_ops
Definition at line 50 of file client.c.
Referenced by mdc_getpage(), mgc_process_recover_log(), mgs_get_ir_logs(), osc_brw_prep_request(), osp_it_fetch(), qsd_fetch_index(), and tgt_sendpage().
struct ptlrpc_bulk_frag_ops ptlrpc_bulk_kvec_ops
Definition at line 62 of file client.c.
Referenced by osp_md_read(), osp_prep_update_req(), out_handle(), and tgt_send_buffer().
lnet_handle_eq_t ptlrpc_eq_h
Definition at line 46 of file events.c.
Referenced by ptl_send_buf(), ptl_send_rpc(), ptlrpc_register_bulk(), and ptlrpc_register_rqbd().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.