Lustre: cl_page_list
cl_page_list
[clio]
Page list used to perform collective operations on a group of pages.
Data Structures
struct cl_page_list
struct cl_2queue
A 2-queue of pages.
Defines
#define cl_page_list_for_each(page, list) list_for_each_entry((page), &(list)->pl_pages, cp_batch)
Iterate over pages in a page list.
#define cl_page_list_for_each_safe(page, temp, list) list_for_each_entry_safe((page), (temp), &(list)->pl_pages, cp_batch)
Iterate over pages in a page list, taking possible removals into account.
Functions
static struct cl_page * cl_page_list_last (struct cl_page_list *plist)
Last page in the page list.
static struct cl_page * cl_page_list_first (struct cl_page_list *plist)
void cl_page_list_init (struct cl_page_list *plist)
Initializes page list.
void cl_page_list_add (struct cl_page_list *plist, struct cl_page *page)
Adds a page to a page list.
void cl_page_list_move (struct cl_page_list *dst, struct cl_page_list *src, struct cl_page *page)
Moves a page from one page list to another.
void cl_page_list_move_head (struct cl_page_list *dst, struct cl_page_list *src, struct cl_page *page)
Moves a page from one page list to the head of another list.
void cl_page_list_splice (struct cl_page_list *list, struct cl_page_list *head)
splice the cl_page_list, just as list head does
void cl_page_list_del (const struct lu_env *env, struct cl_page_list *plist, struct cl_page *page)
Removes a page from a page list.
void cl_page_list_disown (const struct lu_env *env, struct cl_io *io, struct cl_page_list *plist)
Disowns pages in a queue.
int cl_page_list_own (const struct lu_env *env, struct cl_io *io, struct cl_page_list *plist)
Owns all pages in a queue.
void cl_page_list_assume (const struct lu_env *env, struct cl_io *io, struct cl_page_list *plist)
Assumes all pages in a queue.
void cl_page_list_discard (const struct lu_env *env, struct cl_io *io, struct cl_page_list *plist)
Discards all pages in a queue.
void cl_page_list_fini (const struct lu_env *env, struct cl_page_list *plist)
Releases pages from queue.
void cl_2queue_init (struct cl_2queue *queue)
Initialize dual page queue.
void cl_2queue_add (struct cl_2queue *queue, struct cl_page *page)
Add a page to the incoming page list of 2-queue.
void cl_2queue_disown (const struct lu_env *env, struct cl_io *io, struct cl_2queue *queue)
Disown pages in both lists of a 2-queue.
void cl_2queue_assume (const struct lu_env *env, struct cl_io *io, struct cl_2queue *queue)
Assume to own the pages in cl_2queue.
void cl_2queue_discard (const struct lu_env *env, struct cl_io *io, struct cl_2queue *queue)
Discard (truncate) pages in both lists of a 2-queue.
void cl_2queue_fini (const struct lu_env *env, struct cl_2queue *queue)
Finalize both page lists of a 2-queue.
void cl_2queue_init_page (struct cl_2queue *queue, struct cl_page *page)
Initialize a 2-queue to contain page in its incoming page list.
Detailed Description
Page list used to perform collective operations on a group of pages.
Pages are added to the list one by one. cl_page_list acquires a reference for every page in it. Page list is used to perform collective operations on pages:
submit pages for an immediate transfer,
own pages on behalf of certain io (waiting for each page in turn),
discard pages.
When list is finalized, it releases references on all pages it still has.
Todo:
XXX concurrency control.
Define Documentation
#define cl_page_list_for_each (page, list) list_for_each_entry((page), &(list)->pl_pages, cp_batch)
Iterate over pages in a page list.
Definition at line 2346 of file cl_object.h.
Referenced by cl_io_cancel(), cl_io_submit_sync(), cl_page_list_assume(), cl_page_list_discard(), and page_list_sanity_check().
#define cl_page_list_for_each_safe (page, temp, list) list_for_each_entry_safe((page), (temp), &(list)->pl_pages, cp_batch)
Iterate over pages in a page list, taking possible removals into account.
Definition at line 2352 of file cl_object.h.
Referenced by cl_page_list_disown(), cl_page_list_fini(), cl_page_list_own(), cl_page_list_splice(), and osc_io_submit().
Function Documentation
void cl_2queue_add (struct cl_2queue * queue, struct cl_page * page)
Add a page to the incoming page list of 2-queue.
Definition at line 1079 of file cl_io.c.
References cl_2queue::c2_qin, cl_page_list_add(), ENTRY, and EXIT.
Referenced by cl_2queue_init_page(), cl_echo_object_brw(), ll_direct_rw_pages(), and ll_io_read_page().
void cl_2queue_assume (const struct lu_env * env, struct cl_io * io, struct cl_2queue * queue)
Assume to own the pages in cl_2queue.
Definition at line 1116 of file cl_io.c.
References cl_2queue::c2_qin, cl_2queue::c2_qout, and cl_page_list_assume().
void cl_2queue_discard (const struct lu_env * env, struct cl_io * io, struct cl_2queue * queue)
Discard (truncate) pages in both lists of a 2-queue.
Definition at line 1103 of file cl_io.c.
References cl_2queue::c2_qin, cl_2queue::c2_qout, cl_page_list_discard(), ENTRY, and EXIT.
Referenced by cl_echo_object_brw(), and ll_direct_rw_pages().
void cl_2queue_disown (const struct lu_env * env, struct cl_io * io, struct cl_2queue * queue)
Disown pages in both lists of a 2-queue.
Definition at line 1090 of file cl_io.c.
References cl_2queue::c2_qin, cl_2queue::c2_qout, cl_page_list_disown(), ENTRY, and EXIT.
Referenced by cl_echo_object_brw(), and ll_direct_rw_pages().
void cl_2queue_fini (const struct lu_env * env, struct cl_2queue * queue)
Finalize both page lists of a 2-queue.
Definition at line 1126 of file cl_io.c.
References cl_2queue::c2_qin, cl_2queue::c2_qout, cl_page_list_fini(), ENTRY, and EXIT.
Referenced by cl_echo_object_brw(), ll_direct_rw_pages(), ll_io_read_page(), ll_page_sync_io(), lov_io_submit(), and vvp_io_commit_sync().
void cl_2queue_init (struct cl_2queue * queue)
Initialize dual page queue.
Definition at line 1067 of file cl_io.c.
References cl_2queue::c2_qin, cl_2queue::c2_qout, cl_page_list_init(), ENTRY, and EXIT.
Referenced by cl_2queue_init_page(), cl_echo_object_brw(), ll_direct_rw_pages(), ll_io_read_page(), lov_io_submit(), and vvp_io_commit_sync().
void cl_2queue_init_page (struct cl_2queue * queue, struct cl_page * page)
Initialize a 2-queue to contain page in its incoming page list.
Definition at line 1138 of file cl_io.c.
References cl_2queue_add(), cl_2queue_init(), ENTRY, and EXIT.
Referenced by ll_page_sync_io().
void cl_page_list_add (struct cl_page_list * plist, struct cl_page * page)
Adds a page to a page list.
Definition at line 866 of file cl_io.c.
References cl_page_get(), cl_page::cp_batch, cl_page::cp_owner, cl_page::cp_queue_ref, cl_page::cp_reference, ENTRY, EXIT, LASSERT, LINVRNT, list_add_tail(), list_empty(), lu_ref_add_at(), pl_nr, pl_owner, and pl_pages.
Referenced by cl_2queue_add(), echo_commit_callback(), ll_read_ahead_page(), ll_write_end(), and vvp_io_fault_start().
void cl_page_list_assume (const struct lu_env * env, struct cl_io * io, struct cl_page_list * plist)
Assumes all pages in a queue.
Definition at line 1038 of file cl_io.c.
References cl_page_assume(), cl_page_list_for_each, LINVRNT, and pl_owner.
Referenced by cl_2queue_assume(), and cl_io_submit_sync().
void cl_page_list_del (const struct lu_env * env, struct cl_page_list * plist, struct cl_page * page)
Removes a page from a page list.
Definition at line 886 of file cl_io.c.
References cl_page_is_vmlocked(), cl_page_put(), cl_page::cp_batch, cl_page::cp_queue_ref, cl_page::cp_reference, ENTRY, EXIT, LASSERT, LINVRNT, list_del_init(), lu_ref_del_at(), pl_nr, and pl_owner.
Referenced by cl_page_list_fini(), cl_page_list_own(), osc_io_commit_async(), osc_io_submit(), vvp_io_commit_sync(), and vvp_io_write_commit().
void cl_page_list_discard (const struct lu_env * env, struct cl_io * io, struct cl_page_list * plist)
Discards all pages in a queue.
Definition at line 1052 of file cl_io.c.
References cl_page_discard(), cl_page_list_for_each, ENTRY, EXIT, LINVRNT, and pl_owner.
Referenced by cl_2queue_discard().
void cl_page_list_disown (const struct lu_env * env, struct cl_io * io, struct cl_page_list * plist)
Disowns pages in a queue.
Definition at line 963 of file cl_io.c.
References cl_page_disown0(), cl_page_list_for_each_safe, cl_page_put(), cl_page::cp_batch, cl_page::cp_queue_ref, cl_page::cp_reference, ENTRY, EXIT, LASSERT, LINVRNT, list_del_init(), lu_ref_del_at(), pl_nr, and pl_owner.
Referenced by cl_2queue_disown(), ll_io_read_page(), and ll_page_sync_io().
void cl_page_list_fini (const struct lu_env * env, struct cl_page_list * plist)
Releases pages from queue.
Definition at line 997 of file cl_io.c.
References cl_page_list_del(), cl_page_list_for_each_safe, ENTRY, EXIT, LASSERT, LINVRNT, pl_nr, and pl_owner.
Referenced by cl_2queue_fini(), lov_io_submit(), vvp_io_fault_start(), and vvp_io_write_commit().
static struct cl_page* cl_page_list_first (struct cl_page_list * plist) [static, read]
Definition at line 2337 of file cl_object.h.
References cl_page::cp_batch, LASSERT, list_entry, list_head::next, pl_nr, and pl_pages.
Referenced by lov_io_commit_async(), lov_io_submit(), osc_io_commit_async(), vvp_io_commit_sync(), and vvp_io_write_commit().
void cl_page_list_init (struct cl_page_list * plist)
Initializes page list.
Definition at line 853 of file cl_io.c.
References ENTRY, EXIT, INIT_LIST_HEAD, pl_nr, pl_owner, and pl_pages.
Referenced by cl_2queue_init(), lov_emerg_alloc(), lov_io_commit_async(), lov_io_submit(), vvp_io_fault_start(), and vvp_io_write_iter_init().
static struct cl_page* cl_page_list_last (struct cl_page_list * plist) [static, read]
Last page in the page list.
Definition at line 2331 of file cl_object.h.
References cl_page::cp_batch, LASSERT, list_entry, pl_nr, pl_pages, and list_head::prev.
Referenced by lov_io_commit_async(), osc_io_commit_async(), and vvp_io_commit_sync().
void cl_page_list_move (struct cl_page_list * dst, struct cl_page_list * src, struct cl_page * page)
Moves a page from one page list to another.
Definition at line 905 of file cl_io.c.
References cl_page::cp_batch, cl_page::cp_queue_ref, cl_page::cp_reference, ENTRY, EXIT, LASSERT, LINVRNT, list_move_tail(), lu_ref_set_at(), pl_nr, pl_owner, and pl_pages.
Referenced by cl_page_list_splice(), lov_io_commit_async(), lov_io_submit(), and osc_io_submit().
void cl_page_list_move_head (struct cl_page_list * dst, struct cl_page_list * src, struct cl_page * page)
Moves a page from one page list to the head of another list.
Definition at line 925 of file cl_io.c.
References cl_page::cp_batch, cl_page::cp_queue_ref, cl_page::cp_reference, ENTRY, EXIT, LASSERT, LINVRNT, list_move(), lu_ref_set_at(), pl_nr, pl_owner, and pl_pages.
Referenced by lov_io_commit_async().
int cl_page_list_own (const struct lu_env * env, struct cl_io * io, struct cl_page_list * plist)
Owns all pages in a queue.
Definition at line 1015 of file cl_io.c.
References cl_page_list_del(), cl_page_list_for_each_safe, cl_page_own(), cl_page::cp_error, ENTRY, LINVRNT, pl_owner, and RETURN.
void cl_page_list_splice (struct cl_page_list * list, struct cl_page_list * head)
splice the cl_page_list, just as list head does
Definition at line 945 of file cl_io.c.
References cl_page_list_for_each_safe, cl_page_list_move(), ENTRY, EXIT, LINVRNT, and pl_owner.
Referenced by lov_io_submit(), and vvp_io_commit_sync().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.