Lustre: cl_object
cl_object
[clio]
Data Structures
struct cl_attr
"Data attributes" of cl_object.
struct cl_object
Sub-class of lu_object with methods common for objects on the client stacks.
struct cl_object_conf
Description of the client object configuration.
struct cl_layout
struct cl_object_operations
Operations implemented for each cl object layer.
struct cl_object_header
Extended header for client object.
Defines
#define cl_object_for_each(slice, obj)
Helper macro: iterate over all layers of the object obj, assigning every layer top-to-bottom to slice.
#define cl_object_for_each_reverse(slice, obj)
Helper macro: iterate over all layers of the object obj, assigning every layer bottom-to-top to slice.
Enumerations
enum cl_attr_valid {
CAT_SIZE = 1 << 0, CAT_KMS = 1 << 1, CAT_MTIME = 1 << 3, CAT_ATIME = 1 << 4,
CAT_CTIME = 1 << 5, CAT_BLOCKS = 1 << 6, CAT_UID = 1 << 7, CAT_GID = 1 << 8
}
Fields in cl_attr that are being set.
enum { OBJECT_CONF_SET = 0, OBJECT_CONF_INVALIDATE = 1, OBJECT_CONF_WAIT = 2 }
enum { CL_LAYOUT_GEN_NONE = (u32)-2, CL_LAYOUT_GEN_EMPTY = (u32)-1 }
Functions
struct cl_object * cl_object_top (struct cl_object *o)
Returns the top-object for a given o.
struct cl_object * cl_object_find (const struct lu_env *env, struct cl_device *cd, const struct lu_fid *fid, const struct cl_object_conf *c)
Returns a cl_object with a given fid.
int cl_object_header_init (struct cl_object_header *h)
Initialize cl_object_header.
void cl_object_header_fini (struct cl_object_header *h)
Finalize cl_object_header.
void cl_object_put (const struct lu_env *env, struct cl_object *o)
Releases a reference on o.
void cl_object_get (struct cl_object *o)
Acquire an additional reference to the object o.
void cl_object_attr_lock (struct cl_object *o)
Locks data-attributes.
void cl_object_attr_unlock (struct cl_object *o)
Releases data-attributes lock, acquired by cl_object_attr_lock().
int cl_object_attr_get (const struct lu_env *env, struct cl_object *obj, struct cl_attr *attr)
Returns data-attributes of an object obj.
int cl_object_attr_update (const struct lu_env *env, struct cl_object *obj, const struct cl_attr *attr, unsigned valid)
Updates data-attributes of an object obj.
int cl_object_glimpse (const struct lu_env *env, struct cl_object *obj, struct ost_lvb *lvb)
Notifies layers (bottom-to-top) that glimpse AST was received.
int cl_conf_set (const struct lu_env *env, struct cl_object *obj, const struct cl_object_conf *conf)
Updates a configuration of an object obj.
int cl_object_prune (const struct lu_env *env, struct cl_object *obj)
Prunes caches of pages and locks for this object.
void cl_object_kill (const struct lu_env *env, struct cl_object *obj)
Helper function removing all object locks, and marking object for deletion.
int cl_object_getstripe (const struct lu_env *env, struct cl_object *obj, struct lov_user_md __user *lum)
Get stripe information of this object.
int cl_object_fiemap (const struct lu_env *env, struct cl_object *obj, struct ll_fiemap_info_key *fmkey, struct fiemap *fiemap, size_t *buflen)
Get fiemap extents from file object.
int cl_object_layout_get (const struct lu_env *env, struct cl_object *obj, struct cl_layout *cl)
loff_t cl_object_maxbytes (struct cl_object *obj)
static int cl_object_same (struct cl_object *o0, struct cl_object *o1)
Returns true, iff o0 and o1 are slices of the same object.
static void cl_object_page_init (struct cl_object *clob, int size)
static void * cl_object_page_slice (struct cl_object *clob, struct cl_page *page)
static int cl_object_refc (struct cl_object *clob)
Return refcount of cl_object.
Define Documentation
#define cl_object_for_each (slice, obj)
Value:
list_for_each_entry((slice),                            \
                            &(obj)->co_lu.lo_header->loh_layers,\
                            co_lu.lo_linkage)
Helper macro: iterate over all layers of the object obj, assigning every layer top-to-bottom to slice.
Definition at line 454 of file cl_object.h.
Referenced by cl_io_init0(), cl_req_attr_set(), and lov_page_slice_fixup().
#define cl_object_for_each_reverse (slice, obj)
Value:
list_for_each_entry_reverse((slice),                            \
                                    &(obj)->co_lu.lo_header->loh_layers,\
                                    co_lu.lo_linkage)
Helper macro: iterate over all layers of the object obj, assigning every layer bottom-to-top to slice.
Definition at line 463 of file cl_object.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
OBJECT_CONF_SET
configure layout, set up a new stripe, must be called while holding layout lock.
OBJECT_CONF_INVALIDATE
invalidate the current stripe configuration due to losing layout lock.
OBJECT_CONF_WAIT
wait for old layout to go away so that new layout can be set up.
Definition at line 267 of file cl_object.h.
anonymous enum
Enumerator:
CL_LAYOUT_GEN_NONE
CL_LAYOUT_GEN_EMPTY
Definition at line 279 of file cl_object.h.
enum cl_attr_valid
Fields in cl_attr that are being set.
Enumerator:
CAT_SIZE
CAT_KMS
CAT_MTIME
CAT_ATIME
CAT_CTIME
CAT_BLOCKS
CAT_UID
CAT_GID
Definition at line 178 of file cl_object.h.
Function Documentation
int cl_conf_set (const struct lu_env * env, struct cl_object * obj, const struct cl_object_conf * conf)
Updates a configuration of an object obj.
Definition at line 298 of file cl_object.c.
References co_lu, co_ops, cl_object_operations::coo_conf_set, ENTRY, list_for_each_entry, lu_object::lo_header, lu_object_header::loh_layers, and RETURN.
Referenced by cl_file_inode_init(), and ll_layout_conf().
int cl_object_attr_get (const struct lu_env * env, struct cl_object * obj, struct cl_attr * attr)
Returns data-attributes of an object obj.
Every layer is asked (by calling cl_object_operations::coo_attr_get()) top-to-bottom to fill in parts of attr that this layer is responsible for.
Definition at line 204 of file cl_object.c.
References cl_object_attr_guard(), co_lu, co_ops, cl_object_operations::coo_attr_get, ENTRY, list_for_each_entry, lu_object::lo_header, lu_object_header::loh_layers, and RETURN.
Referenced by ll_merge_attr(), ll_prepare_partial_page(), ll_readahead(), osc_io_setattr_start(), osc_refresh_count(), and vvp_prep_size().
void cl_object_attr_lock (struct cl_object * o)
Locks data-attributes.
Prevents data-attributes from changing, until lock is released by cl_object_attr_unlock(). This has to be called before calls to cl_object_attr_get(), cl_object_attr_update().
Definition at line 180 of file cl_object.c.
References cl_object_attr_guard().
Referenced by brw_interpret(), ll_merge_attr(), ll_prepare_partial_page(), ll_readahead(), osc_dlm_blocking_ast0(), osc_io_read_start(), osc_io_setattr_start(), osc_io_write_start(), osc_lock_lvb_update(), osc_page_touch_at(), osc_refresh_count(), osc_sync_interpret(), vvp_io_setattr_time(), and vvp_object_size_lock().
void cl_object_attr_unlock (struct cl_object * o)
Releases data-attributes lock, acquired by cl_object_attr_lock().
Definition at line 190 of file cl_object.c.
References cl_object_attr_guard().
Referenced by brw_interpret(), ll_merge_attr(), ll_prepare_partial_page(), ll_readahead(), osc_dlm_blocking_ast0(), osc_io_read_start(), osc_io_setattr_start(), osc_io_write_start(), osc_lock_lvb_update(), osc_page_touch_at(), osc_refresh_count(), osc_sync_interpret(), vvp_io_setattr_time(), and vvp_object_size_unlock().
int cl_object_attr_update (const struct lu_env * env, struct cl_object * obj, const struct cl_attr * attr, unsigned v)
Updates data-attributes of an object obj.
Only attributes, mentioned in a validness bit-mask v are updated. Calls cl_object_operations::coo_upd_attr() on every layer, bottom to top.
Definition at line 236 of file cl_object.c.
References cl_object_attr_guard(), co_lu, co_ops, cl_object_operations::coo_attr_update, ENTRY, list_for_each_entry_reverse, lu_object::lo_header, lu_object_header::loh_layers, and RETURN.
Referenced by brw_interpret(), osc_dlm_blocking_ast0(), osc_io_read_start(), osc_io_setattr_start(), osc_io_write_start(), osc_lock_lvb_update(), osc_page_touch_at(), osc_sync_interpret(), and vvp_io_setattr_time().
int cl_object_fiemap (const struct lu_env * env, struct cl_object * obj, struct ll_fiemap_info_key * key, struct fiemap * fiemap, size_t * buflen)
Get fiemap extents from file object.
Parameters:
env [in] lustre environment
obj [in] file object
key [in] fiemap request argument
fiemap [out] fiemap extents mapping retrived
buflen [in] max buffer length of
Return values:
0 success
< 0 error
Definition at line 376 of file cl_object.c.
References co_lu, co_ops, cl_object_operations::coo_fiemap, ENTRY, list_for_each_entry, lu_object::lo_header, lu_object_header::loh_layers, and RETURN.
Referenced by ll_do_fiemap(), and lov_object_fiemap().
struct cl_object* cl_object_find (const struct lu_env * env, struct cl_device * cd, const struct lu_fid * fid, const struct cl_object_conf * c) [read]
Returns a cl_object with a given fid.
Returns either cached or newly created object. Additional reference on the returned object is acquired.
See also:
lu_object_find(), cl_page_find(), cl_lock_find()
Definition at line 103 of file cl_object.c.
References cl2lu_dev(), cl_object_conf::coc_lu, lu2cl(), and lu_object_find_slice().
Referenced by cl_echo_object_find(), and cl_file_inode_init().
void cl_object_get (struct cl_object * o)
Acquire an additional reference to the object o.
This can only be used to acquire _additional_ reference, i.e., caller already has to possess at least one reference to o before calling this.
See also:
cl_page_get(), cl_lock_get().
Definition at line 134 of file cl_object.c.
References co_lu, and lu_object_get().
Referenced by cl_page_alloc(), osc_check_rpcs(), osc_dlm_blocking_ast0(), osc_extent_alloc(), osc_ldlm_glimpse_ast(), osc_ldlm_resource_invalidate(), osc_lock_enqueue(), and osc_lru_shrink().
int cl_object_getstripe (const struct lu_env * env, struct cl_object * obj, struct lov_user_md __user * lum)
Get stripe information of this object.
Definition at line 345 of file cl_object.c.
References co_lu, co_ops, cl_object_operations::coo_getstripe, ENTRY, list_for_each_entry, lu_object::lo_header, lu_object_header::loh_layers, and RETURN.
Referenced by ll_file_getstripe().
int cl_object_glimpse (const struct lu_env * env, struct cl_object * obj, struct ost_lvb * lvb)
Notifies layers (bottom-to-top) that glimpse AST was received.
Layers have to fill lvb fields with information that will be shipped back to glimpse issuer.
See also:
cl_lock_operations::clo_glimpse()
Definition at line 270 of file cl_object.c.
References co_lu, co_ops, cl_object_operations::coo_glimpse, D_DLMTRACE, ENTRY, list_for_each_entry_reverse, lu_object::lo_header, lu_object_header::loh_layers, LPU64, LU_OBJECT_HEADER, lu_object_top(), ost_lvb::lvb_atime, ost_lvb::lvb_blocks, ost_lvb::lvb_ctime, ost_lvb::lvb_mtime, ost_lvb::lvb_size, and RETURN.
Referenced by lovsub_object_glimpse(), and osc_ldlm_glimpse_ast().
void cl_object_header_fini (struct cl_object_header * h)
Finalize cl_object_header.
Definition at line 90 of file cl_object.c.
References cl_object_header::coh_lu, and lu_object_header_fini().
int cl_object_header_init (struct cl_object_header * h)
Initialize cl_object_header.
Definition at line 72 of file cl_object.c.
References cl_attr_guard_class, cl_object_header::coh_attr_guard, cl_object_header::coh_lu, cl_object_header::coh_page_bufsize, ENTRY, lu_object_header_init(), and RETURN.
Referenced by echo_object_alloc(), lovsub_object_alloc(), and vvp_object_alloc().
void cl_object_kill (const struct lu_env * env, struct cl_object * obj)
Helper function removing all object locks, and marking object for deletion.
All object pages must have been deleted at this point.
This is called by cl_inode_fini() and lov_object_delete() to destroy top- and sub- objects respectively.
Definition at line 435 of file cl_object.c.
References cl_object_header(), cl_object_header::coh_lu, lu_object_header::loh_flags, and LU_OBJECT_HEARD_BANSHEE.
Referenced by cl_inode_fini(), lov_init_sub(), and lov_subobject_kill().
int cl_object_layout_get (const struct lu_env * env, struct cl_object * obj, struct cl_layout * cl)
Definition at line 397 of file cl_object.c.
References co_lu, co_ops, cl_object_operations::coo_layout_get, ENTRY, list_for_each_entry, lu_object::lo_header, lu_object_header::loh_layers, and RETURN.
Referenced by ll_getxattr_lov(), and ll_layout_conf().
loff_t cl_object_maxbytes (struct cl_object * obj)
Definition at line 412 of file cl_object.c.
References co_lu, co_ops, cl_object_operations::coo_maxbytes, ENTRY, list_for_each_entry, lu_object::lo_header, lu_object_header::loh_layers, min_t, and RETURN.
Referenced by ll_file_maxbytes().
static void cl_object_page_init (struct cl_object * clob, int size) [inline, static]
Definition at line 2047 of file cl_object.h.
References cfs_size_round(), cl_object_header(), co_slice_off, and cl_object_header::coh_page_bufsize.
Referenced by echo_object_init(), lov_object_init(), lovsub_object_init(), osc_object_init(), and vvp_object_init0().
static void* cl_object_page_slice (struct cl_object * clob, struct cl_page * page) [inline, static]
Definition at line 2054 of file cl_object.h.
References co_slice_off.
Referenced by echo_page_init(), ll_io_read_page(), ll_prepare_partial_page(), ll_read_ahead_page(), lov_page_init_empty(), lov_page_init_raid0(), lovsub_page_init(), osc_cl_page_osc(), osc_page_init(), page_list_sanity_check(), vvp_io_fault_start(), and vvp_page_init().
int cl_object_prune (const struct lu_env * env, struct cl_object * obj)
Prunes caches of pages and locks for this object.
Definition at line 321 of file cl_object.c.
References co_lu, co_ops, cl_object_operations::coo_prune, ENTRY, list_for_each_entry, lu_object::lo_header, lu_object::lo_linkage, lu_object_header::loh_layers, and RETURN.
Referenced by lov_delete_raid0(), and lov_layout_change().
void cl_object_put (const struct lu_env * env, struct cl_object * o)
Releases a reference on o.
When last reference is released object is returned to the cache, unless lu_object_header_flags::LU_OBJECT_HEARD_BANSHEE bit is set in its header.
See also:
cl_page_put(), cl_lock_put().
Definition at line 120 of file cl_object.c.
References co_lu, and lu_object_put().
Referenced by cl_echo_object_find(), cl_echo_object_put(), cl_object_put_last(), cl_page_free(), lov_init_sub(), lov_object_fiemap(), lov_subobject_kill(), osc_check_rpcs(), osc_dlm_blocking_ast0(), osc_extent_put(), osc_ldlm_glimpse_ast(), osc_ldlm_resource_invalidate(), osc_lock_enqueue(), osc_lock_upcall_agl(), osc_lru_shrink(), vvp_pgcache_find(), and vvp_pgcache_show().
static int cl_object_refc (struct cl_object * clob) [inline, static]
Return refcount of cl_object.
Definition at line 2063 of file cl_object.h.
References co_lu, header, lu_object::lo_header, and lu_object_header::loh_ref.
Referenced by ll_releasepage().
static int cl_object_same (struct cl_object * o0, struct cl_object * o1) [inline, static]
Returns true, iff o0 and o1 are slices of the same object.
Definition at line 2042 of file cl_object.h.
References cl_object_header().
Referenced by cl_lockset_merge(), cl_page_assume(), cl_page_invoid(), cl_page_invoke(), cl_page_is_owned(), lov_sublock_env_get(), and osc_lock_set_writer().
struct cl_object* cl_object_top (struct cl_object * o) [read]
Returns the top-object for a given o.
See also:
cl_io_top()
Definition at line 145 of file cl_object.c.
References CDEBUG, cl_object_header(), cl_object_header::coh_lu, cl_object_header::coh_parent, D_TRACE, lu2cl(), and lu_object_top().
Referenced by cl_io_init(), cl_io_sub_init(), cl_object_attr_guard(), osc_extent_truncate(), and osc_lock_weight().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.