Lustre: Lustre Log Reader
Lustre Log Reader
Interpret llogs used for storing configuration and changelog data.
Defines
#define CANCELLED 0x678
#define PTL_CMD_BASE 100
#define OSD_OI_FID_NR (1UL << 7)
Attempt to display a path to the object (file) containing changelog entries, referred to by this changelog_catalog record.
Functions
static int ext2_test_bit (int nr, const void *addr)
int llog_pack_buffer (int fd, struct llog_log_hdr **llog_buf, struct llog_rec_hdr ***recs, int *recs_number)
void print_llog_header (struct llog_log_hdr *llog_buf)
static void print_records (struct llog_rec_hdr **recs_buf, int rec_number, int is_ext)
void llog_unpack_buffer (int fd, struct llog_log_hdr *llog_buf, struct llog_rec_hdr **recs_buf)
int is_fstype_ext (int fd)
static void print_log_path (struct llog_logid_rec *lid, int is_ext)
int main (int argc, char **argv)
static void print_1_cfg (struct lustre_cfg *lcfg)
static void print_setup_cfg (struct lustre_cfg *lcfg)
void print_lustre_cfg (struct lustre_cfg *lcfg, int *skip)
static void print_hsm_action (struct llog_agent_req_rec *larr)
void print_changelog_rec (struct llog_changelog_rec *rec)
Variables
char * portals_command [17]
Detailed Description
Interpret llogs used for storing configuration and changelog data.
Define Documentation
#define CANCELLED 0x678
Definition at line 86 of file llog_reader.c.
Referenced by llog_pack_buffer(), and print_records().
#define OSD_OI_FID_NR (1UL << 7)
Attempt to display a path to the object (file) containing changelog entries, referred to by this changelog_catalog record.
This path depends on the implementation of the OSD device; zfs-osd and ldiskfs-osd are different.
Assumes that if the file system containing the changelog_catalog is ext{2,3,4}, the backend is ldiskfs-osd; otherwise it is either zfs-osd or at least names objects based on FID and the zfs-osd path (which includes the FID) will be sufficient.
The Object ID stored in the record is also displayed untranslated.
Definition at line 139 of file llog_reader.c.
#define PTL_CMD_BASE 100
Definition at line 88 of file llog_reader.c.
Function Documentation
static int ext2_test_bit (int nr, const void * addr) [inline, static]
Definition at line 65 of file llog_reader.c.
int is_fstype_ext (int fd)
Definition at line 110 of file llog_reader.c.
References llapi_error(), and LLAPI_MSG_ERROR.
Referenced by main().
int llog_pack_buffer (int fd, struct llog_log_hdr ** llog_buf, struct llog_rec_hdr *** recs, int * recs_number)
Definition at line 213 of file llog_reader.c.
References CANCELLED, ext2_test_bit, file_size, le32_to_cpu, llapi_error(), LLAPI_MSG_ERROR, LLOG_HDR_BITMAP, llog_rec_hdr::lrh_id, llog_rec_hdr::lrh_index, llog_rec_hdr::lrh_len, and llog_rec_hdr::lrh_type.
Referenced by main().
void llog_unpack_buffer (int fd, struct llog_log_hdr * llog_buf, struct llog_rec_hdr ** recs_buf)
Definition at line 338 of file llog_reader.c.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 164 of file llog_reader.c.
References is_fstype_ext(), llapi_error(), LLAPI_MSG_ERROR, llog_pack_buffer(), llog_unpack_buffer(), print_llog_header(), and print_records().
static void print_1_cfg (struct lustre_cfg * lcfg) [static]
Definition at line 368 of file llog_reader.c.
References lustre_cfg::lcfg_bufcount, lustre_cfg::lcfg_buflens, lustre_cfg::lcfg_nal, lustre_cfg::lcfg_nid, libcfs_nid2str(), and lustre_cfg_buf().
Referenced by print_lustre_cfg(), and print_setup_cfg().
void print_changelog_rec (struct llog_changelog_rec * rec)
Definition at line 625 of file llog_reader.c.
References changelog_type2str(), llog_changelog_rec::cr, changelog_rec::cr_flags, llog_changelog_rec::cr_hdr, changelog_rec::cr_type, le32_to_cpu, and llog_rec_hdr::lrh_id.
Referenced by print_records().
static void print_hsm_action (struct llog_agent_req_rec * larr) [static]
Definition at line 596 of file llog_reader.c.
References agent_req_status2name(), llog_agent_req_rec::arr_archive_id, llog_agent_req_rec::arr_compound_id, llog_agent_req_rec::arr_flags, llog_agent_req_rec::arr_hai, llog_agent_req_rec::arr_hdr, llog_agent_req_rec::arr_req_change, llog_agent_req_rec::arr_req_create, llog_agent_req_rec::arr_status, buf, DFID, hsm_action_item::hai_action, hsm_action_item::hai_cookie, hai_dump_data_field(), hsm_action_item::hai_extent, hsm_action_item::hai_fid, hsm_action_item::hai_gid, hsm_action_item::hai_len, hsm_copytool_action2name(), hsm_extent::length, llog_rec_hdr::lrh_index, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, hsm_extent::offset, and PFID.
Referenced by print_records().
void print_llog_header (struct llog_log_hdr * llog_buf)
Definition at line 346 of file llog_reader.c.
References le32_to_cpu, le64_to_cpu, llog_log_hdr::llh_count, llog_log_hdr::llh_hdr, llog_log_hdr::llh_tgtuuid, llog_log_hdr::llh_timestamp, and llog_rec_hdr::lrh_len.
Referenced by main().
static void print_log_path (struct llog_logid_rec * lid, int is_ext) [static]
Definition at line 140 of file llog_reader.c.
References DFID_NOBRACE, DOSTID, lu_fid::f_oid, lu_fid::f_seq, llog_logid::lgl_ogen, llog_logid::lgl_oi, llog_logid_rec::lid_id, logid_to_fid(), OSD_OI_FID_NR, PFID, and POSTID.
Referenced by print_records().
void print_lustre_cfg (struct lustre_cfg * lcfg, int * skip)
Definition at line 408 of file llog_reader.c.
References cfg_marker::cm_canceltime, cfg_marker::cm_comment, cfg_marker::cm_createtime, CM_END, CM_EXCLUDE, cfg_marker::cm_flags, CM_SKIP, CM_START, cfg_marker::cm_step, cfg_marker::cm_tgtname, cfg_marker::cm_vers, cmd, LCFG_ADD_CONN, LCFG_ADD_MDC, LCFG_ADD_UUID, LCFG_ATTACH, LCFG_CLEANUP, lustre_cfg::lcfg_command, LCFG_DEL_CONN, LCFG_DEL_MDC, LCFG_DEL_MOUNTOPT, LCFG_DEL_UUID, LCFG_DETACH, LCFG_LOV_ADD_OBD, LCFG_LOV_DEL_OBD, LCFG_MARKER, LCFG_MOUNTOPT, lustre_cfg::lcfg_num, LCFG_PARAM, LCFG_POOL_ADD, LCFG_POOL_DEL, LCFG_POOL_NEW, LCFG_POOL_REM, LCFG_SET_LDLM_TIMEOUT, LCFG_SET_PARAM, LCFG_SET_TIMEOUT, LCFG_SET_UPCALL, LCFG_SETUP, LCFG_SPTLRPC_CONF, le32_to_cpu, lustre_cfg_buf(), OBD_OCD_VERSION_FIX, OBD_OCD_VERSION_MAJOR, OBD_OCD_VERSION_MINOR, OBD_OCD_VERSION_PATCH, print_1_cfg(), and print_setup_cfg().
Referenced by print_records().
static void print_records (struct llog_rec_hdr ** recs_buf, int rec_number, int is_ext) [static]
Definition at line 634 of file llog_reader.c.
References CANCELLED, CHANGELOG_REC, CHANGELOG_USER_REC, HSM_AGENT_REC, le32_to_cpu, LLOG_LOGID_MAGIC, LLOG_PAD_MAGIC, OBD_CFG_REC, print_changelog_rec(), print_hsm_action(), print_log_path(), and print_lustre_cfg().
Referenced by main().
static void print_setup_cfg (struct lustre_cfg * lcfg) [static]
Definition at line 384 of file llog_reader.c.
References lustre_cfg::lcfg_bufcount, lustre_cfg::lcfg_buflens, lov_desc::ld_default_stripe_count, lov_desc::ld_default_stripe_offset, lov_desc::ld_default_stripe_size, lov_desc::ld_pattern, lov_desc::ld_uuid, lustre_cfg_string(), print_1_cfg(), and obd_uuid::uuid.
Referenced by print_lustre_cfg().
Variable Documentation
char* portals_command[17]
Initial value:
{
        "REGISTER_PEER_FD",
        "CLOSE_CONNECTION",
        "REGISTER_MYNID",
        "PUSH_CONNECTION",
        "GET_CONN",
        "DEL_PEER",
        "ADD_PEER",
        "GET_PEER",
        "GET_TXDESC",
        "ADD_ROUTE",
        "DEL_ROUTE",
        "GET_ROUTE",
        "NOTIFY_ROUTER",
        "ADD_INTERFACE",
        "DEL_INTERFACE",
        "GET_INTERFACE",
        ""
}
Definition at line 89 of file llog_reader.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.