Lustre: Lock iterators
Lock iterators
[Lustre Distributed Lock Manager]
LDLM provides for a way to iterate through every lock on a resource or namespace or every resource in a namespace.
Functions
int ldlm_resource_foreach (struct ldlm_resource *res, ldlm_iterator_t iter, void *closure)
void ldlm_namespace_foreach (struct ldlm_namespace *ns, ldlm_iterator_t iter, void *closure)
int ldlm_resource_iterate (struct ldlm_namespace *, const struct ldlm_res_id *, ldlm_iterator_t iter, void *data)
Detailed Description
LDLM provides for a way to iterate through every lock on a resource or namespace or every resource in a namespace.
Function Documentation
void ldlm_namespace_foreach (struct ldlm_namespace * ns, ldlm_iterator_t iter, void * closure)
Definition at line 2115 of file ldlm_request.c.
References cfs_hash_for_each_nolock(), iter_helper_data::iter, ldlm_res_iter_helper(), and ldlm_namespace::ns_rs_hash.
Referenced by ldlm_replay_locks().
int ldlm_resource_foreach (struct ldlm_resource * res, ldlm_iterator_t iter, void * closure)
Definition at line 2056 of file ldlm_request.c.
References ENTRY, GOTO, ldlm_lock::l_res_link, LDLM_ITER_CONTINUE, LDLM_ITER_STOP, list_entry, list_for_each_safe, lock_res(), ldlm_resource::lr_converting, ldlm_resource::lr_granted, ldlm_resource::lr_waiting, list_head::next, RETURN, and unlock_res().
Referenced by ldlm_res_iter_helper(), and ldlm_resource_iterate().
int ldlm_resource_iterate (struct ldlm_namespace * , const struct ldlm_res_id * , ldlm_iterator_t iter, void * data)
Definition at line 2131 of file ldlm_request.c.
References ENTRY, LASSERTF, LDLM_RESOURCE_ADDREF, LDLM_RESOURCE_DELREF, ldlm_resource_foreach(), ldlm_resource_get(), ldlm_resource_putref(), and RETURN.
Referenced by osc_object_prune().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.