Lustre: fid
fid
http://wiki.lustre.org/index.php/Architecture_-_Interoperability_fids_zfs describes the FID namespace and interoperability requirements for FIDs.
Data Structures
struct lu_client_seq
struct lu_server_seq
struct seq_server_site
Defines
#define LUSTRE_SEQ_SRV_NAME "seq_srv"
#define LUSTRE_SEQ_CTL_NAME "seq_ctl"
Enumerations
enum {
LUSTRE_METADATA_SEQ_MAX_WIDTH = 0x0000000000020000ULL, LUSTRE_DATA_SEQ_MAX_WIDTH = 0x00000000FFFFFFFFULL, LUSTRE_SEQ_META_WIDTH = 0x0000000000000001ULL, LUSTRE_SEQ_BATCH_WIDTH = LUSTRE_SEQ_META_WIDTH * 1000,
LUSTRE_SEQ_SUPER_WIDTH = ((1ULL << 30ULL) * LUSTRE_SEQ_META_WIDTH)
}
enum { OSD_OI_FID_OID_BITS = 6, OSD_OI_FID_OID_BITS_MAX = 10 }
enum local_oid {
FLD_INDEX_OID = 3UL, FID_SEQ_CTL_OID = 4UL, FID_SEQ_SRV_OID = 5UL, MDD_ROOT_INDEX_OID = 6UL,
MDD_ORPHAN_OID = 7UL, MDD_LOV_OBJ_OID = 8UL, MDD_CAPA_KEYS_OID = 9UL, LAST_RECV_OID = 11UL,
OSD_FS_ROOT_OID = 13UL, ACCT_USER_OID = 15UL, ACCT_GROUP_OID = 16UL, LFSCK_BOOKMARK_OID = 17UL,
OTABLE_IT_OID = 18UL, OSD_LPF_OID = 19UL, REPLY_DATA_OID = 21UL, OFD_LAST_GROUP_OID = 4117UL,
LLOG_CATALOGS_OID = 4118UL, MGS_CONFIGS_OID = 4119UL, OFD_HEALTH_CHECK_OID = 4120UL, MDD_LOV_OBJ_OSEQ = 4121UL,
LFSCK_NAMESPACE_OID = 4122UL, REMOTE_PARENT_DIR_OID = 4123UL, BATCHID_COMMITTED_OID = 4125UL
}
special OID for local objects
enum lu_cli_type { LUSTRE_SEQ_METADATA = 1, LUSTRE_SEQ_DATA }
enum lu_mgr_type { LUSTRE_SEQ_SERVER, LUSTRE_SEQ_CONTROLLER }
Functions
static void lu_local_obj_fid (struct lu_fid *fid, __u32 oid)
static void lu_local_name_obj_fid (struct lu_fid *fid, __u32 oid)
static int fid_is_root (const struct lu_fid *fid)
static int fid_is_dot_lustre (const struct lu_fid *fid)
static int fid_is_obf (const struct lu_fid *fid)
static int fid_is_otable_it (const struct lu_fid *fid)
static int fid_is_acct (const struct lu_fid *fid)
static int fid_is_quota (const struct lu_fid *fid)
static int fid_is_name_llog (const struct lu_fid *fid)
static int fid_is_namespace_visible (const struct lu_fid *fid)
static int fid_seq_in_fldb (__u64 seq)
static void lu_last_id_fid (struct lu_fid *fid, __u64 seq, __u32 ost_idx)
static bool fid_is_md_operative (const struct lu_fid *fid)
int seq_server_init (const struct lu_env *env, struct lu_server_seq *seq, struct dt_device *dev, const char *prefix, enum lu_mgr_type type, struct seq_server_site *ss)
void seq_server_fini (struct lu_server_seq *seq, const struct lu_env *env)
int seq_server_alloc_super (struct lu_server_seq *seq, struct lu_seq_range *out, const struct lu_env *env)
int seq_server_alloc_meta (struct lu_server_seq *seq, struct lu_seq_range *out, const struct lu_env *env)
int seq_server_set_cli (const struct lu_env *env, struct lu_server_seq *seq, struct lu_client_seq *cli)
int seq_server_check_and_alloc_super (const struct lu_env *env, struct lu_server_seq *seq)
Check if the sequence server has sequence avaible.
int seq_client_init (struct lu_client_seq *seq, struct obd_export *exp, enum lu_cli_type type, const char *prefix, struct lu_server_seq *srv)
void seq_client_fini (struct lu_client_seq *seq)
void seq_client_flush (struct lu_client_seq *seq)
int seq_client_alloc_fid (const struct lu_env *env, struct lu_client_seq *seq, struct lu_fid *fid)
int seq_client_get_seq (const struct lu_env *env, struct lu_client_seq *seq, u64 *seqnr)
Allocate the whole seq to the caller.
int seq_site_fini (const struct lu_env *env, struct seq_server_site *ss)
int fid_is_local (const struct lu_env *env, struct lu_site *site, const struct lu_fid *fid)
int client_fid_init (struct obd_device *obd, struct obd_export *exp, enum lu_cli_type type)
int client_fid_fini (struct obd_device *obd)
static void fid_build_reg_res_name (const struct lu_fid *fid, struct ldlm_res_id *res)
static int fid_res_name_eq (const struct lu_fid *fid, const struct ldlm_res_id *res)
static void fid_extract_from_res_name (struct lu_fid *fid, const struct ldlm_res_id *res)
static void fid_build_quota_res_name (const struct lu_fid *glb_fid, union lquota_id *qid, struct ldlm_res_id *res)
static void fid_extract_from_quota_res (struct lu_fid *glb_fid, union lquota_id *qid, const struct ldlm_res_id *res)
static void fid_build_pdo_res_name (const struct lu_fid *fid, unsigned int hash, struct ldlm_res_id *res)
static void ostid_build_res_name (const struct ost_id *oi, struct ldlm_res_id *name)
Build DLM resource name from object id & seq, which will be removed finally, when we replace ost_id with FID in data stack.
static bool ostid_res_name_eq (const struct ost_id *oi, const struct ldlm_res_id *name)
Return true if the resource is for the object identified by this id & group.
static void ost_fid_build_resid (const struct lu_fid *fid, struct ldlm_res_id *resname)
static void ost_fid_from_resid (struct lu_fid *fid, const struct ldlm_res_id *name, int ost_idx)
static __u64 fid_flatten (const struct lu_fid *fid)
Flatten 128-bit FID values into a 64-bit value for use as an inode number.
static __u32 fid_hash (const struct lu_fid *f, int bits)
static __u32 fid_flatten32 (const struct lu_fid *fid)
map fid to 32 bit value for ino on 32bit systems.
static int lu_fid_diff (const struct lu_fid *fid1, const struct lu_fid *fid2)
static void range_cpu_to_le (struct lu_seq_range *dst, const struct lu_seq_range *src)
static void range_le_to_cpu (struct lu_seq_range *dst, const struct lu_seq_range *src)
static void range_cpu_to_be (struct lu_seq_range *dst, const struct lu_seq_range *src)
static void range_be_to_cpu (struct lu_seq_range *dst, const struct lu_seq_range *src)
static void range_array_cpu_to_le (struct lu_seq_range_array *dst, const struct lu_seq_range_array *src)
static void range_array_le_to_cpu (struct lu_seq_range_array *dst, const struct lu_seq_range_array *src)
Variables
struct lu_seq_range LUSTRE_SEQ_SPACE_RANGE
A cluster-wide range from which fid-sequences are granted to servers and then clients.
struct lu_seq_range LUSTRE_SEQ_ZERO_RANGE
struct lu_fid LUSTRE_BFL_FID
struct lu_fid LU_OBF_FID
Special fid for "fid" special object in .lustre.
struct lu_fid LU_LPF_FID
Special fid for "lost+found" special object in .lustre.
struct lu_fid LU_DOT_LUSTRE_FID
Special fid for ".lustre" directory.
struct lu_fid LU_BACKEND_LPF_FID
"/lost+found" - special FID for ldiskfs backend, invislbe to client.
Detailed Description
http://wiki.lustre.org/index.php/Architecture_-_Interoperability_fids_zfs describes the FID namespace and interoperability requirements for FIDs.
The important parts of that document are included here for reference.
FID File IDentifier generated by client from range allocated by the SEQuence service and stored in struct lu_fid. The FID is composed of three parts: SEQuence, ObjectID, and VERsion. The SEQ component is a filesystem unique 64-bit integer, and only one client is ever assigned any SEQ value. The first 0x400 FID_SEQ_NORMAL [2^33, 2^33 + 0x400] values are reserved for system use. The OID component is a 32-bit value generated by the client on a per-SEQ basis to allow creating many unique FIDs without communication with the server. The VER component is a 32-bit value that distinguishes between different FID instantiations, such as snapshots or separate subtrees within the filesystem. FIDs with the same VER field are considered part of the same namespace.
OLD filesystems are those upgraded from Lustre 1.x that predate FIDs, and MDTs use 32-bit ldiskfs internal inode/generation numbers (IGIFs), while OSTs use 64-bit Lustre object IDs and generation numbers.
NEW filesystems are those formatted since the introduction of FIDs.
IGIF Inode and Generation In FID, a surrogate FID used to globally identify an existing object on OLD formatted MDT file system. This would only be used on MDT0 in a DNE filesystem, because there cannot be more than one MDT in an OLD formatted filesystem. Belongs to sequence in [12, 2^32 - 1] range, where inode number is stored in SEQ, and inode generation is in OID. NOTE: This assumes no more than 2^32-1 inodes exist in the MDT filesystem, which is the maximum possible for an ldiskfs backend. It also assumes that the reserved ext3/ext4/ldiskfs inode numbers [0-11] are never visible to clients, which has always been true.
IDIF object ID In FID, a surrogate FID used to globally identify an existing OST object on OLD formatted OST file system. Belongs to a sequence in [2^32, 2^33 - 1]. Sequence number is calculated as:
1 << 32 | (ost_index << 16) | ((objid >> 32) & 0xffff)
that is, SEQ consists of 16-bit OST index, and higher 16 bits of object ID. The generation of unique SEQ values per OST allows the IDIF FIDs to be identified in the FLD correctly. The OID field is calculated as:
objid & 0xffffffff
that is, it consists of lower 32 bits of object ID. For objects within the IDIF range, object ID extraction will be:
o_id = (fid->f_seq & 0x7fff) << 16 | fid->f_oid; o_seq = 0; // formerly group number
NOTE: This assumes that no more than 2^48-1 objects have ever been created on any OST, and that no more than 65535 OSTs are in use. Both are very reasonable assumptions, i.e. an IDIF can uniquely map all objects assuming a maximum creation rate of 1M objects per second for a maximum of 9 years, or combinations thereof.
OST_MDT0 Surrogate FID used to identify an existing object on OLD formatted OST filesystem. Belongs to the reserved SEQuence 0, and is used prior to the introduction of FID-on-OST, at which point IDIF will be used to identify objects as residing on a specific OST.
LLOG For Lustre Log objects the object sequence 1 is used. This is compatible with both OLD and NEW namespaces, as this SEQ number is in the ext3/ldiskfs reserved inode range and does not conflict with IGIF sequence numbers.
ECHO For testing OST IO performance the object sequence 2 is used. This is compatible with both OLD and NEW namespaces, as this SEQ number is in the ext3/ldiskfs reserved inode range and does not conflict with IGIF sequence numbers.
OST_MDT1 .. OST_MAX For testing with multiple MDTs the object sequence 3 through 9 is used, allowing direct mapping of MDTs 1 through 7 respectively, for a total of 8 MDTs including OST_MDT0. This matches the legacy CMD project "group" mappings. However, this SEQ range is only for testing prior to any production DNE release, as the objects in this range conflict across all OSTs, as the OST index is not part of the FID. For production DNE usage, OST objects created by MDT1+ will use FID_SEQ_NORMAL FIDs.
DLM OST objid to IDIF mapping For compatibility with existing OLD OST network protocol structures, the FID must map onto the o_id and o_seq in a manner that ensures existing objects are identified consistently for IO, as well as onto the LDLM namespace to ensure IDIFs there is only a single resource name for any object in the DLM. The OLD OST object DLM resource mapping is:
resource[] = {o_id, o_seq, 0, 0}; // o_seq == 0 for production releases
The NEW OST object DLM resource mapping is the same for both MDT and OST:
resource[] = {SEQ, OID, VER, HASH};
NOTE: for mapping IDIF values to DLM resource names the o_id may be larger than the 2^33 reserved sequence numbers for IDIF, so it is possible for the o_id numbers to overlap FID SEQ numbers in the resource. However, in all production releases the OLD o_seq field is always zero, and all valid FID OID values are non-zero, so the lock resources will not collide. Even so, the MDT and OST resources are also in different LDLM namespaces.
Define Documentation
#define LUSTRE_SEQ_CTL_NAME "seq_ctl"
Definition at line 757 of file lustre_fid.h.
Referenced by seq_store_init().
#define LUSTRE_SEQ_SRV_NAME "seq_srv"
Definition at line 756 of file lustre_fid.h.
Referenced by seq_store_init().
Enumeration Type Documentation
anonymous enum
Enumerator:
LUSTRE_METADATA_SEQ_MAX_WIDTH
LUSTRE_DATA_SEQ_MAX_WIDTH
LUSTRE_SEQ_META_WIDTH
LUSTRE_SEQ_BATCH_WIDTH
LUSTRE_SEQ_SUPER_WIDTH
Definition at line 173 of file lustre_fid.h.
anonymous enum
Enumerator:
OSD_OI_FID_OID_BITS
2^6 FIDs for OI containers
OSD_OI_FID_OID_BITS_MAX
reserve enough FIDs in case we want more in the future
Definition at line 201 of file lustre_fid.h.
enum local_oid
special OID for local objects
Enumerator:
FLD_INDEX_OID
See also:
fld_mod_init
FID_SEQ_CTL_OID
See also:
fid_mod_init
FID_SEQ_SRV_OID
MDD_ROOT_INDEX_OID
See also:
mdd_mod_init
MDD_ORPHAN_OID
MDD_LOV_OBJ_OID
MDD_CAPA_KEYS_OID
LAST_RECV_OID
See also:
mdt_mod_init
OSD_FS_ROOT_OID
ACCT_USER_OID
ACCT_GROUP_OID
LFSCK_BOOKMARK_OID
OTABLE_IT_OID
OSD_LPF_OID
REPLY_DATA_OID
OFD_LAST_GROUP_OID
LLOG_CATALOGS_OID
MGS_CONFIGS_OID
OFD_HEALTH_CHECK_OID
MDD_LOV_OBJ_OSEQ
LFSCK_NAMESPACE_OID
REMOTE_PARENT_DIR_OID
BATCHID_COMMITTED_OID
Definition at line 209 of file lustre_fid.h.
enum lu_cli_type
Enumerator:
LUSTRE_SEQ_METADATA
LUSTRE_SEQ_DATA
Definition at line 338 of file lustre_fid.h.
enum lu_mgr_type
Enumerator:
LUSTRE_SEQ_SERVER
LUSTRE_SEQ_CONTROLLER
Definition at line 343 of file lustre_fid.h.
Function Documentation
int client_fid_fini (struct obd_device * obd)
Definition at line 554 of file fid_request.c.
References client_obd::cl_seq, obd_device::cli, ENTRY, OBD_FREE_PTR, RETURN, seq_client_fini(), and obd_device::u.
int client_fid_init (struct obd_device * obd, struct obd_export * exp, enum lu_cli_type type)
Definition at line 522 of file fid_request.c.
References client_obd::cl_seq, obd_device::cli, ENTRY, GOTO, MAX_OBD_NAME, OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, obd_device::obd_name, RETURN, seq_client_init(), and obd_device::u.
static void fid_build_pdo_res_name (const struct lu_fid * fid, unsigned int hash, struct ldlm_res_id * res) [inline, static]
Definition at line 597 of file lustre_fid.h.
References fid_build_reg_res_name(), LUSTRE_RES_ID_HSH_OFF, and ldlm_res_id::name.
Referenced by mdt_pdir_hash_lock().
static void fid_build_quota_res_name (const struct lu_fid * glb_fid, union lquota_id * qid, struct ldlm_res_id * res) [inline, static]
Definition at line 574 of file lustre_fid.h.
References fid_build_reg_res_name(), fid_ver_oid(), LUSTRE_RES_ID_QUOTA_SEQ_OFF, LUSTRE_RES_ID_QUOTA_VER_OID_OFF, ldlm_res_id::name, and lquota_id::qid_fid.
Referenced by qmt_id_lock_glimpse(), and qsd_intent_lock().
static void fid_build_reg_res_name (const struct lu_fid * fid, struct ldlm_res_id * res) [inline, static]
Definition at line 541 of file lustre_fid.h.
References fid_ver_oid(), LUSTRE_RES_ID_SEQ_OFF, LUSTRE_RES_ID_VER_OID_OFF, and ldlm_res_id::name.
Referenced by fid_build_pdo_res_name(), fid_build_quota_res_name(), lfsck_ibits_lock(), lfsck_lock(), lod_object_lock(), mdc_cancel_unused(), mdc_enqueue(), mdc_intent_getattr_async(), mdc_lock_match(), mdc_null_inode(), mdc_resource_get_unused(), mdc_revalidate_lock(), mdt_object_local_lock(), mdt_remote_object_lock(), mdt_rename_lock(), ost_fid_build_resid(), ostid_build_res_name(), qmt_glb_lock_notify(), and qsd_intent_lock().
static void fid_extract_from_quota_res (struct lu_fid * glb_fid, union lquota_id * qid, const struct ldlm_res_id * res) [inline, static]
Definition at line 585 of file lustre_fid.h.
References lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, fid_extract_from_res_name(), LUSTRE_RES_ID_QUOTA_SEQ_OFF, LUSTRE_RES_ID_QUOTA_VER_OID_OFF, ldlm_res_id::name, and lquota_id::qid_fid.
Referenced by qmt_lvbo_init().
static void fid_extract_from_res_name (struct lu_fid * fid, const struct ldlm_res_id * res) [inline, static]
Definition at line 562 of file lustre_fid.h.
References lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, fid_res_name_eq(), LASSERT, LUSTRE_RES_ID_SEQ_OFF, LUSTRE_RES_ID_VER_OID_OFF, and ldlm_res_id::name.
Referenced by fid_extract_from_quota_res(), mdt_intent_layout(), mdt_lvbo_fill(), ofd_lvbo_update(), and ost_fid_from_resid().
static __u64 fid_flatten (const struct lu_fid * fid) [inline, static]
Flatten 128-bit FID values into a 64-bit value for use as an inode number.
For non-IGIF FIDs this starts just over 2^32, and continues without conflict until 2^64, at which point we wrap the high 24 bits of the SEQ into the range where there may not be many OID values in use, to minimize the risk of conflict.
Suppose LUSTRE_SEQ_MAX_WIDTH less than (1 << 24) which is currently true, the time between re-used inode numbers is very long - 2^40 SEQ numbers, or about 2^40 client mounts, if clients create less than 2^24 files/mount.
Definition at line 693 of file lustre_fid.h.
References __u64, fid_is_igif(), fid_oid(), lu_igif_ino(), and RETURN.
Referenced by cl_fid_build_gen(), cl_fid_build_ino(), and fid_hash().
static __u32 fid_flatten32 (const struct lu_fid * fid) [inline, static]
map fid to 32 bit value for ino on 32bit systems.
Definition at line 719 of file lustre_fid.h.
References __u64, fid_is_igif(), fid_oid(), FID_SEQ_START, lu_igif_ino(), and RETURN.
Referenced by cl_fid_build_ino(), ldlm_res_hop_fid_hash(), and lu_obj_hop_hash().
static __u32 fid_hash (const struct lu_fid * f, int bits) [inline, static]
Definition at line 710 of file lustre_fid.h.
References fid_flatten().
static int fid_is_acct (const struct lu_fid * fid) [inline, static]
Definition at line 283 of file lustre_fid.h.
References ACCT_GROUP_OID, ACCT_USER_OID, fid_oid(), and FID_SEQ_LOCAL_FILE.
Referenced by fid2type(), osd_acct_obj_lookup(), osd_fid_lookup(), osd_get_name_n_idx(), osd_index_try(), osd_object_create(), osd_object_destroy(), osd_object_ea_create(), osd_object_init0(), osd_oi_lookup(), and osd_quota_fid2dmu().
static int fid_is_dot_lustre (const struct lu_fid * fid) [inline, static]
Definition at line 265 of file lustre_fid.h.
References fid_oid(), FID_OID_DOT_LUSTRE, FID_SEQ_DOT_LUSTRE, and unlikely.
Referenced by mdd_dir_page_build().
int fid_is_local (const struct lu_env * env, struct lu_site * site, const struct lu_fid * fid)
Definition at line 371 of file fld_handler.c.
References ENTRY, fld_cache_lookup(), fld_thread_key, lu_client_fld::lcf_cache, lu_env::le_ctx, lu_seq_range::lsr_index, lu_context_key_get(), lu_site2seq(), seq_server_site::ss_client_fld, and seq_server_site::ss_node_id.
static bool fid_is_md_operative (const struct lu_fid * fid) [inline, static]
Definition at line 331 of file lustre_fid.h.
References fid_is_igif(), fid_is_mdt0(), fid_is_norm(), and fid_is_root().
Referenced by mdt_md_create(), mdt_reint_link(), mdt_reint_migrate_internal(), mdt_reint_open(), mdt_reint_rename_internal(), mdt_reint_rename_or_migrate(), and mdt_reint_unlink().
static int fid_is_name_llog (const struct lu_fid * fid) [inline, static]
Definition at line 296 of file lustre_fid.h.
References FID_SEQ_LLOG_NAME.
Referenced by fid_is_on_ost().
static int fid_is_namespace_visible (const struct lu_fid * fid) [inline, static]
Definition at line 301 of file lustre_fid.h.
References __u64, fid_is_last_id(), fid_is_root(), fid_seq_is_dot(), fid_seq_is_igif(), and fid_seq_is_norm().
Referenced by fid_is_internal(), mdd_create(), mdt_fid2path(), osd_get_ldiskfs_dirent_param(), and osd_scrub_get_fid().
static int fid_is_obf (const struct lu_fid * fid) [inline, static]
Definition at line 271 of file lustre_fid.h.
References fid_oid(), FID_OID_DOT_LUSTRE_OBF, FID_SEQ_DOT_LUSTRE, and unlikely.
Referenced by mdt_obj_version_get().
static int fid_is_otable_it (const struct lu_fid * fid) [inline, static]
Definition at line 277 of file lustre_fid.h.
References fid_oid(), FID_SEQ_LOCAL_FILE, OTABLE_IT_OID, and unlikely.
Referenced by osd_object_init().
static int fid_is_quota (const struct lu_fid * fid) [inline, static]
Definition at line 290 of file lustre_fid.h.
References FID_SEQ_QUOTA, and FID_SEQ_QUOTA_GLB.
Referenced by dt_index_read(), fid_is_on_ost(), osd_index_iam_delete(), osd_index_iam_insert(), osd_index_iam_lookup(), osd_it_iam_get(), osd_it_iam_key(), and osd_it_iam_rec().
static int fid_is_root (const struct lu_fid * fid) [inline, static]
Definition at line 259 of file lustre_fid.h.
References fid_oid(), FID_OID_ROOT, FID_SEQ_ROOT, and unlikely.
Referenced by fid_is_md_operative(), fid_is_namespace_visible(), and obf_lookup().
static int fid_res_name_eq (const struct lu_fid * fid, const struct ldlm_res_id * res) [inline, static]
Definition at line 551 of file lustre_fid.h.
References fid_ver_oid(), LUSTRE_RES_ID_SEQ_OFF, LUSTRE_RES_ID_VER_OID_OFF, and ldlm_res_id::name.
Referenced by fid_extract_from_res_name(), ll_md_blocking_ast(), mdc_finish_intent_lock(), mdt_check_resent_lock(), and mdt_getattr_name_lock().
static int fid_seq_in_fldb (__u64 seq) [inline, static]
Definition at line 312 of file lustre_fid.h.
References fid_seq_is_dot(), fid_seq_is_igif(), fid_seq_is_norm(), and fid_seq_is_root().
Referenced by lfsck_namespace_scan_local_lpf(), lmv_fld_lookup(), lod_fld_lookup(), osd_fld_lookup(), osd_remote_fid(), and update_is_committed().
static int lu_fid_diff (const struct lu_fid * fid1, const struct lu_fid * fid2) [inline, static]
Definition at line 744 of file lustre_fid.h.
References DFID, lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, fid_idif_id(), fid_is_idif(), fid_oid(), LASSERTF, and PFID.
static void lu_last_id_fid (struct lu_fid * fid, __u64 seq, __u32 ost_idx) [inline, static]
Definition at line 318 of file lustre_fid.h.
References lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, fid_idif_seq(), fid_seq_is_echo(), fid_seq_is_idif(), fid_seq_is_mdt0(), fid_seq_is_norm(), LASSERTF, and LPX64.
Referenced by lfsck_layout_lastid_load(), and ofd_seq_load().
static void lu_local_name_obj_fid (struct lu_fid * fid, __u32 oid) [inline, static]
Definition at line 249 of file lustre_fid.h.
References lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, and FID_SEQ_LOCAL_NAME.
Referenced by lquota_disk_dir_find_create(), and lquota_disk_glb_find_create().
static void lu_local_obj_fid (struct lu_fid * fid, __u32 oid) [inline, static]
Definition at line 242 of file lustre_fid.h.
References lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, and FID_SEQ_LOCAL_FILE.
Referenced by acct_obj_lookup(), distribute_txn_commit_batchid_init(), fld_index_init(), mdt_iocontrol(), ofd_fs_setup(), osd_iget_fid(), osd_ldiskfs_add_entry(), osd_mdt_init(), osd_mount(), osd_root_get(), osp_find_or_create_local_file(), osp_sync_llog_init(), seq_store_init(), and tgt_init().
static void ost_fid_build_resid (const struct lu_fid * fid, struct ldlm_res_id * resname) [inline, static]
Definition at line 652 of file lustre_fid.h.
References fid_build_reg_res_name(), fid_is_idif(), fid_is_mdt0(), fid_to_ostid(), ost_id::oi, and ostid_build_res_name().
Referenced by lfsck_layout_slave_conditional_destroy(), ofd_commitrw(), ofd_destroy_by_fid(), ofd_echo_setattr(), ofd_get_info_hdl(), and tgt_ost_body_unpack().
static void ost_fid_from_resid (struct lu_fid * fid, const struct ldlm_res_id * name, int ost_idx) [inline, static]
Definition at line 666 of file lustre_fid.h.
References fid_extract_from_res_name(), fid_seq_is_mdt0(), LUSTRE_RES_ID_SEQ_OFF, LUSTRE_RES_ID_VER_OID_OFF, ldlm_res_id::name, ostid_set_id(), ostid_set_seq(), and ostid_to_fid().
Referenced by ofd_lvbo_init(), ofd_lvbo_update(), and tgt_blocking_ast().
static void ostid_build_res_name (const struct ost_id * oi, struct ldlm_res_id * name) [inline, static]
Build DLM resource name from object id & seq, which will be removed finally, when we replace ost_id with FID in data stack.
Currently, resid from the old client, whose res[0] = object_id, res[1] = object_seq, is just oposite with Metatdata resid, where, res[0] = fid->f_seq, res[1] = fid->f_oid. To unifiy the resid identification, we will reverse the data resid to keep it same with Metadata resid, i.e.
For resid from the old client, res[0] = objid, res[1] = 0, still keep the original order, for compatiblity.
For new resid res will be built from normal FID directly, i.e. res[0] = f_seq, res[1] = f_oid + f_ver.
Definition at line 622 of file lustre_fid.h.
References fid_build_reg_res_name(), fid_seq_is_mdt0(), LUSTRE_RES_ID_SEQ_OFF, LUSTRE_RES_ID_VER_OID_OFF, ldlm_res_id::name, ost_id::oi_fid, ostid_id(), and ostid_seq().
Referenced by osc_dlmlock_at_pgoff(), osc_lock_enqueue(), osc_object_fiemap(), osc_object_prune(), osc_req_attr_set(), osc_resource_get_unused(), and ost_fid_build_resid().
static bool ostid_res_name_eq (const struct ost_id * oi, const struct ldlm_res_id * name) [inline, static]
Return true if the resource is for the object identified by this id & group.
Definition at line 637 of file lustre_fid.h.
References fid_seq_is_mdt0(), LUSTRE_RES_ID_SEQ_OFF, LUSTRE_RES_ID_VER_OID_OFF, ldlm_res_id::name, ostid_id(), and ostid_seq().
Referenced by ofd_rw_hpreq_lock_match().
static void range_array_cpu_to_le (struct lu_seq_range_array * dst, const struct lu_seq_range_array * src) [inline, static]
Definition at line 796 of file lustre_fid.h.
References cpu_to_le32, lu_seq_range_array::lsra_count, lu_seq_range_array::lsra_lsr, and range_cpu_to_le().
Referenced by fld_server_read().
static void range_array_le_to_cpu (struct lu_seq_range_array * dst, const struct lu_seq_range_array * src) [inline, static]
Definition at line 807 of file lustre_fid.h.
References le32_to_cpu, lu_seq_range_array::lsra_count, lu_seq_range_array::lsra_lsr, and range_le_to_cpu().
Referenced by fld_update_from_controller().
static void range_be_to_cpu (struct lu_seq_range * dst, const struct lu_seq_range * src) [inline, static]
Definition at line 788 of file lustre_fid.h.
References be32_to_cpu, be64_to_cpu, lu_seq_range::lsr_end, lu_seq_range::lsr_flags, lu_seq_range::lsr_index, and lu_seq_range::lsr_start.
Referenced by fld_index_init(), and fld_server_read().
static void range_cpu_to_be (struct lu_seq_range * dst, const struct lu_seq_range * src) [inline, static]
Definition at line 779 of file lustre_fid.h.
References cpu_to_be32, cpu_to_be64, lu_seq_range::lsr_end, lu_seq_range::lsr_flags, lu_seq_range::lsr_index, and lu_seq_range::lsr_start.
Referenced by fld_declare_index_create(), and fld_index_create().
static void range_cpu_to_le (struct lu_seq_range * dst, const struct lu_seq_range * src) [inline, static]
Definition at line 761 of file lustre_fid.h.
References cpu_to_le32, cpu_to_le64, lu_seq_range::lsr_end, lu_seq_range::lsr_flags, lu_seq_range::lsr_index, and lu_seq_range::lsr_start.
Referenced by range_array_cpu_to_le(), and seq_store_update().
static void range_le_to_cpu (struct lu_seq_range * dst, const struct lu_seq_range * src) [inline, static]
Definition at line 770 of file lustre_fid.h.
References le32_to_cpu, le64_to_cpu, lu_seq_range::lsr_end, lu_seq_range::lsr_flags, lu_seq_range::lsr_index, and lu_seq_range::lsr_start.
Referenced by range_array_le_to_cpu(), and seq_store_read().
int seq_client_alloc_fid (const struct lu_env * env, struct lu_client_seq * seq, struct lu_fid * fid)
Definition at line 320 of file fid_request.c.
References CDEBUG, CERROR, D_INFO, DFID, ENTRY, lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, fid_is_zero(), fid_oid(), LASSERT, lu_client_seq::lcs_fid, lu_client_seq::lcs_mutex, lu_client_seq::lcs_name, lu_client_seq::lcs_width, LUSTRE_FID_INIT_OID, OBD_FAIL_CHECK, OBD_FAIL_SEQ_EXHAUST, PFID, RETURN, seq_client_alloc_seq(), seq_fid_alloc_fini(), and seq_fid_alloc_prep().
Referenced by lfsck_fid_alloc(), mdc_fid_alloc(), osd_fid_alloc(), and osp_fid_alloc().
void seq_client_fini (struct lu_client_seq * seq)
Definition at line 506 of file fid_request.c.
References class_export_put(), ENTRY, EXIT, lu_client_seq::lcs_exp, lu_client_seq::lcs_srv, and seq_client_proc_fini().
Referenced by client_fid_fini(), lfsck_fid_fini(), ofd_fid_init(), osd_fid_fini(), seq_client_init(), and seq_site_fini().
void seq_client_flush (struct lu_client_seq * seq)
this id shld not be used for seq range allocation. set to -1 for dgb check.
Definition at line 389 of file fid_request.c.
References fid_zero(), LASSERT, lu_client_seq::lcs_fid, lu_client_seq::lcs_mutex, lu_client_seq::lcs_space, lu_client_seq::lcs_update, lu_client_seq::lcs_waitq, lu_seq_range::lsr_index, and lu_seq_range_init().
Referenced by mdc_import_event(), and seq_client_init().
int seq_client_get_seq (const struct lu_env * env, struct lu_client_seq * seq, u64 * seqnr)
Allocate the whole seq to the caller.
Definition at line 271 of file fid_request.c.
References CDEBUG, CERROR, D_INFO, lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, LASSERT, lu_client_seq::lcs_fid, lu_client_seq::lcs_mutex, lu_client_seq::lcs_name, lu_client_seq::lcs_type, LUSTRE_DATA_SEQ_MAX_WIDTH, LUSTRE_METADATA_SEQ_MAX_WIDTH, LUSTRE_SEQ_METADATA, seq_client_alloc_seq(), seq_fid_alloc_fini(), and seq_fid_alloc_prep().
Referenced by echo_client_iocontrol(), osp_init_pre_fid(), and osp_precreate_rollover_new_seq().
int seq_client_init (struct lu_client_seq * seq, struct obd_export * exp, enum lu_cli_type type, const char * prefix, struct lu_server_seq * srv)
Definition at line 468 of file fid_request.c.
References class_export_get(), ENTRY, LASSERT, lu_client_seq::lcs_exp, lu_client_seq::lcs_mutex, lu_client_seq::lcs_name, lu_client_seq::lcs_srv, lu_client_seq::lcs_type, lu_client_seq::lcs_waitq, lu_client_seq::lcs_width, LUSTRE_DATA_SEQ_MAX_WIDTH, LUSTRE_METADATA_SEQ_MAX_WIDTH, LUSTRE_SEQ_METADATA, RETURN, seq_client_fini(), seq_client_flush(), and seq_client_proc_init().
Referenced by client_fid_init(), lfsck_fid_init(), mdt_seq_init_cli(), ofd_fid_init(), and osd_fid_init().
int seq_server_alloc_meta (struct lu_server_seq * seq, struct lu_seq_range * out, const struct lu_env * env)
Definition at line 350 of file fid_handler.c.
References __seq_server_alloc_meta(), ENTRY, lu_server_seq::lss_mutex, and RETURN.
Referenced by osd_fid_init(), seq_client_alloc_meta(), and seq_server_handle().
int seq_server_alloc_super (struct lu_server_seq * seq, struct lu_seq_range * out, const struct lu_env * env)
Definition at line 139 of file fid_handler.c.
References __seq_server_alloc_super(), ENTRY, lu_server_seq::lss_mutex, and RETURN.
Referenced by seq_client_alloc_super(), and seq_server_handle().
int seq_server_check_and_alloc_super (const struct lu_env * env, struct lu_server_seq * seq)
Check if the sequence server has sequence avaible.
Check if the sequence server has sequence avaible, if not, then allocating super sequence from sequence manager (MDT0).
Parameters:
[in] env execution environment
[in] seq server sequence
Return values:
negative errno if allocating new sequence fails
0 if there is enough sequence or allocating new sequence succeeds
Definition at line 275 of file fid_handler.c.
References __seq_set_init(), CDEBUG, CERROR, D_HA, ENTRY, fld_insert_entry(), LASSERT, lu_client_seq::lcs_space, lu_client_seq::lcs_srv, lu_server_fld::lsf_lock, lu_server_seq::lss_cli, lu_server_seq::lss_lowater_set, lu_server_seq::lss_name, lu_server_seq::lss_site, lu_server_seq::lss_space, lu_seq_range_is_exhausted(), lu_seq_range_is_sane(), lu_seq_range_is_zero(), RETURN, seq_client_alloc_super(), and seq_server_site::ss_server_fld.
Referenced by __seq_server_alloc_meta(), and mdt_register_lwp_callback().
void seq_server_fini (struct lu_server_seq * seq, const struct lu_env * env)
Definition at line 591 of file fid_handler.c.
References ENTRY, EXIT, seq_server_proc_fini(), and seq_store_fini().
Referenced by ofd_fid_init(), seq_server_init(), and seq_site_fini().
int seq_server_init (const struct lu_env * env, struct lu_server_seq * seq, struct dt_device * dev, const char * prefix, enum lu_mgr_type type, struct seq_server_site * ss)
Definition at line 501 of file fid_handler.c.
References CERROR, CLASSERT, ENTRY, EXIT, lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, GOTO, LASSERT, LCONSOLE_INFO, lu_seq_range::lsr_index, lu_server_seq::lss_cli, lu_server_seq::lss_hiwater_set, lu_server_seq::lss_lowater_set, lu_server_seq::lss_mutex, lu_server_seq::lss_name, lu_server_seq::lss_set_width, lu_server_seq::lss_site, lu_server_seq::lss_space, lu_server_seq::lss_type, lu_server_seq::lss_width, lu_seq_range_init(), lu_seq_range_is_sane(), lu_seq_range_is_zero(), LUSTRE_SEQ_BATCH_WIDTH, LUSTRE_SEQ_META_WIDTH, LUSTRE_SEQ_SERVER, LUSTRE_SEQ_SPACE_RANGE, LUSTRE_SEQ_SUPER_WIDTH, LUSTRE_SEQ_ZERO_RANGE, seq_server_fini(), seq_server_proc_init(), seq_store_init(), seq_store_read(), seq_store_update(), seq_server_site::ss_lu, and seq_server_site::ss_node_id.
Referenced by mdt_seq_init(), and ofd_fid_init().
int seq_server_set_cli (const struct lu_env * env, struct lu_server_seq * seq, struct lu_client_seq * cli)
Definition at line 58 of file fid_handler.c.
References CDEBUG, D_HA, D_INFO, ENTRY, EXIT, GOTO, lu_client_seq::lcs_name, lu_client_seq::lcs_space, lu_seq_range::lsr_index, lu_server_seq::lss_cli, lu_server_seq::lss_mutex, lu_server_seq::lss_name, lu_server_seq::lss_site, and seq_server_site::ss_node_id.
Referenced by mdt_seq_fini_cli(), mdt_seq_init_cli(), and ofd_fid_init().
int seq_site_fini (const struct lu_env * env, struct seq_server_site * ss)
Definition at line 603 of file fid_handler.c.
References OBD_FREE_PTR, RETURN, seq_client_fini(), seq_server_fini(), seq_server_site::ss_client_seq, seq_server_site::ss_control_seq, and seq_server_site::ss_server_seq.
Referenced by mdt_seq_fini(), and ofd_fid_fini().
Variable Documentation
struct lu_fid LU_BACKEND_LPF_FID
"/lost+found" - special FID for ldiskfs backend, invislbe to client.
Definition at line 102 of file fid_lib.c.
Referenced by lfsck_namespace_scan_local_lpf().
struct lu_fid LU_DOT_LUSTRE_FID
Special fid for ".lustre" directory.
Definition at line 84 of file fid_lib.c.
Referenced by mdd_dot_lustre_setup(), and osd_ios_ROOT_scan().
struct lu_fid LU_LPF_FID
Special fid for "lost+found" special object in .lustre.
Definition at line 96 of file fid_lib.c.
Referenced by lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_verify_lpf(), lfsck_verify_lpf_pairs(), and mdd_lpf_setup().
struct lu_fid LU_OBF_FID
Special fid for "fid" special object in .lustre.
Definition at line 90 of file fid_lib.c.
Referenced by mdd_obf_setup().
struct lu_fid LUSTRE_BFL_FID
Definition at line 78 of file fid_lib.c.
Referenced by mdt_rename_lock().
struct lu_seq_range LUSTRE_SEQ_SPACE_RANGE
A cluster-wide range from which fid-sequences are granted to servers and then clients.
Fid namespace:
 Normal FID:        seq:64 [2^33,2^64-1]      oid:32          ver:32
 IGIF      :        0:32, ino:32              gen:32          0:32
 IDIF      :        0:31, 1:1, ost-index:16,  objd:48         0:32
The first 0x400 sequences of normal FID are reserved for special purpose. FID_SEQ_START + 1 is for local file id generation. FID_SEQ_START + 2 is for .lustre directory and its objects
Definition at line 66 of file fid_lib.c.
Referenced by seq_server_init().
struct lu_seq_range LUSTRE_SEQ_ZERO_RANGE
Definition at line 72 of file fid_lib.c.
Referenced by seq_server_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.