Lustre: Initialization and cleanup
Initialization and cleanup
[LNet]
The LNet must be properly initialized before any LNet calls can be made.
Functions
int LNetNIInit (lnet_pid_t requested_pid)
Set LNet PID and start LNet interfaces, routing, and forwarding.
int LNetNIFini (void)
Stop LNet interfaces, routing, and forwarding.
Detailed Description
The LNet must be properly initialized before any LNet calls can be made.
Function Documentation
int LNetNIFini (void)
Stop LNet interfaces, routing, and forwarding.
Users must call this function once for each successful call to LNetNIInit(). Once the LNetNIFini() operation has been started, the results of pending API operations are undefined.
Returns:
always 0 for current implementation.
Definition at line 1639 of file api-ni.c.
References LASSERT, lnet_t::ln_api_mutex, lnet_t::ln_niinit_self, lnet_t::ln_refcount, lnet_acceptor_stop(), lnet_destroy_routes(), lnet_fault_fini(), lnet_ping_target_fini(), lnet_proc_fini(), lnet_router_checker_stop(), lnet_shutdown_lndnis(), and lnet_unprepare().
Referenced by lnet_ioctl(), lnet_unconfigure(), ptlrpc_ni_fini(), ptlrpc_ni_init(), and srpc_shutdown().
int LNetNIInit (lnet_pid_t requested_pid)
Set LNet PID and start LNet interfaces, routing, and forwarding.
Users must call this function at least once before any other functions. For each successful call there must be a corresponding call to LNetNIFini(). For subsequent calls to LNetNIInit(), requested_pid is ignored.
The PID used by LNet may be different from the one requested. See LNetGetId().
Parameters:
requested_pid PID requested by the caller.
Returns:
>= 0 on success, and < 0 error code on failures.
Definition at line 1516 of file api-ni.c.
References CDEBUG, D_OTHER, INIT_LIST_HEAD, LASSERT, list_del_init(), list_empty(), list_entry, lnet_t::ln_api_mutex, lnet_t::ln_nis_from_mod_params, lnet_t::ln_refcount, lnet_acceptor_start(), lnet_acceptor_stop(), lnet_check_routes(), lnet_destroy_routes(), lnet_fault_init(), lnet_get_networks(), lnet_get_routes(), LNET_MKNET(), lnet_ni_alloc(), lnet_ni_free(), lnet_parse_networks(), lnet_parse_routes(), lnet_ping_info_setup(), lnet_ping_target_fini(), lnet_ping_target_update(), lnet_prepare(), lnet_proc_init(), lnet_router_checker_start(), lnet_rtrpools_alloc(), lnet_shutdown_lndnis(), lnet_startup_lndnis(), lnet_unprepare(), LOLND, list_head::next, and lnet_ni::ni_list.
Referenced by lnet_configure(), lnet_ioctl(), ptlrpc_ni_init(), and srpc_startup().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.