Lustre: LNet addressing and basic types
LNet addressing and basic types
[LNet]
Addressing scheme and basic data types of LNet.
Data Structures
struct WIRE_ATTR
struct lnet_ack
struct lnet_put
struct lnet_get
struct lnet_reply
struct lnet_hello
struct lnet_counters
struct lnet_handle_any_t
Objects maintained by the LNet are accessed through handles.
struct lnet_process_id_t
Global process ID.
Defines
#define LNET_VERSION "0.7.0"
#define LNET_RESERVED_PORTAL 0
Portal reserved for LNet's own use.
#define LNET_NID_ANY ((lnet_nid_t) -1)
wildcard NID that matches any end-point address
#define LNET_PID_ANY ((lnet_pid_t) -1)
wildcard PID that matches any lnet_pid_t
#define LNET_PID_RESERVED 0xf0000000
#define LNET_PID_USERFLAG 0x80000000
#define LNET_PID_LUSTRE 12345
#define LNET_TIME_FOREVER (-1)
#define WIRE_ATTR __attribute__((packed))
#define LNET_PROTO_IB_MAGIC 0x0be91b91
#define LNET_PROTO_GNI_MAGIC 0xb00fbabe
#define LNET_PROTO_TCP_MAGIC 0xeebc0ded
#define LNET_PROTO_ACCEPTOR_MAGIC 0xacce7100
#define LNET_PROTO_PING_MAGIC 0x70696E67
#define LNET_PROTO_MAGIC 0x45726963
#define LNET_PROTO_TCP_VERSION_MAJOR 1
#define LNET_PROTO_TCP_VERSION_MINOR 0
#define LNET_PROTO_ACCEPTOR_VERSION 1
#define LNET_NI_STATUS_UP 0x15aac0de
#define LNET_NI_STATUS_DOWN 0xdeadface
#define LNET_NI_STATUS_INVALID 0x00000000
#define LNET_MAX_INTERFACES 16
#define LNET_WIRE_HANDLE_COOKIE_NONE (-1)
Typedefs
typedef __u64 lnet_nid_t
Address of an end-point in an LNet network.
typedef __u32 lnet_pid_t
ID of a process in a node.
typedef struct lnet_ack lnet_ack_t
typedef struct lnet_put lnet_put_t
typedef struct lnet_get lnet_get_t
typedef struct lnet_reply lnet_reply_t
typedef struct lnet_hello lnet_hello_t
typedef struct lnet_counters lnet_counters_t
typedef lnet_handle_any_t lnet_handle_eq_t
typedef lnet_handle_any_t lnet_handle_md_t
typedef lnet_handle_any_t lnet_handle_me_t
Enumerations
enum lnet_msg_type_t {
LNET_MSG_ACK = 0, LNET_MSG_PUT, LNET_MSG_GET, LNET_MSG_REPLY,
LNET_MSG_HELLO
}
Functions
int LNetGetId (unsigned int index, lnet_process_id_t *id)
Retrieve the lnet_process_id_t ID of LNet interface at index.
int LNetDist (lnet_nid_t nid, lnet_nid_t *srcnid, __u32 *order)
Calculate distance to node at dstnid.
void LNetSnprintHandle (char *str, int str_len, lnet_handle_any_t handle)
Print a string representation of handle h into buffer str of len bytes.
static __u32 LNET_NIDADDR (lnet_nid_t nid)
extract the address part of an lnet_nid_t
static __u32 LNET_NIDNET (lnet_nid_t nid)
static lnet_nid_t LNET_MKNID (__u32 net, __u32 addr)
static __u32 LNET_NETNUM (__u32 net)
static __u32 LNET_NETTYP (__u32 net)
static __u32 LNET_MKNET (__u32 type, __u32 num)
static void LNetInvalidateHandle (lnet_handle_any_t *h)
Invalidate handle h.
static int LNetHandleIsEqual (lnet_handle_any_t h1, lnet_handle_any_t h2)
Compare handles h1 and h2.
static int LNetHandleIsInvalid (lnet_handle_any_t h)
Check whether handle h is invalid.
Detailed Description
Addressing scheme and basic data types of LNet.
The LNet API is memory-oriented, so LNet must be able to address not only end-points but also memory region within a process address space. An lnet_nid_t addresses an end-point. An lnet_pid_t identifies a process in a node. A portal represents an opening in the address space of a process. Match bits is criteria to identify a region of memory inside a portal, and offset specifies an offset within the memory region.
LNet creates a table of portals for each process during initialization. This table has MAX_PORTALS entries and its size can't be dynamically changed. A portal stays empty until the owning process starts to add memory regions to it. A portal is sometimes called an index because it's an entry in the portals table of a process.
See also:
LNetMEAttach
Define Documentation
#define LNET_MAX_INTERFACES 16
Definition at line 249 of file types.h.
Referenced by kiblnd_startup(), ksocknal_add_interface(), ksocknal_create_conn(), ksocknal_create_routes(), ksocknal_enumerate_interfaces(), ksocknal_ip2iface(), ksocknal_local_ipvec(), ksocknal_recv_hello_v1(), ksocknal_recv_hello_v2(), ksocknal_select_ips(), ksocknal_send_hello(), ksocknal_startup(), ksocknal_unlink_peer_locked(), lnet_ni_free(), lnet_parse_networks(), and lustre_lnet_show_net().
#define LNET_NI_STATUS_DOWN 0xdeadface
Definition at line 246 of file types.h.
Referenced by lnet_parse(), lnet_parse_rc_info(), and lnet_update_ni_status_locked().
#define LNET_NI_STATUS_INVALID 0x00000000
Definition at line 247 of file types.h.
Referenced by lnet_create_rc_data_locked().
#define LNET_NI_STATUS_UP 0x15aac0de
Definition at line 245 of file types.h.
Referenced by lnet_parse(), lnet_parse_rc_info(), lnet_ping_info_install_locked(), lustre_lnet_show_net(), and proc_lnet_nis().
#define LNET_NID_ANY ((lnet_nid_t) -1)
wildcard NID that matches any end-point address
Definition at line 72 of file types.h.
Referenced by _debug_req(), clean_path(), convert_hostnames(), fail_peer(), fault_attr_nid_parse(), jt_lcfg_add_uuid(), jt_ptl_add_peer(), jt_ptl_add_route(), jt_ptl_del_peer(), jt_ptl_del_route(), jt_ptl_disconnect(), jt_ptl_mynid(), jt_ptl_network(), jt_ptl_notify_router(), jt_ptl_ping(), jt_ptl_push_connection(), jt_ptl_which_nid(), kgnilnd_add_peer(), kgnilnd_base_shutdown(), kgnilnd_cancel_wc_dgrams(), kgnilnd_create_peer_safe(), kgnilnd_del_conn_or_peer(), kgnilnd_finish_connect(), kgnilnd_post_dgram(), kgnilnd_probe_and_process_dgram(), kgnilnd_process_dgram(), kgnilnd_release_dgram(), kgnilnd_repost_wc_dgrams(), kgnilnd_reset_stack(), kgnilnd_send_nak(), kgnilnd_set_conn_params(), kgnilnd_setup_wildcard_dgram(), kgnilnd_shutdown(), kgnilnd_unpack_connreq(), kiblnd_close_matching_conns(), kiblnd_create_peer(), kiblnd_del_peer(), kiblnd_shutdown(), kiblnd_unpack_msg(), ksocknal_add_peer(), ksocknal_close_matching_conns(), ksocknal_create_conn(), ksocknal_create_peer(), ksocknal_del_peer(), ksocknal_push(), ksocknal_recv_hello(), ksocknal_shutdown(), libcfs_nid2str_r(), libcfs_str2anynid(), libcfs_str2net(), libcfs_str2nid(), lnet_add_route(), lnet_build_msg_event(), lnet_complete_msg_locked(), lnet_create_rc_data_locked(), lnet_del_route(), lnet_destroy_routes(), lnet_fail_nid(), lnet_fault_nid_match(), lnet_match_networks(), lnet_parse_get(), lnet_parse_networks(), lnet_parse_nid(), lnet_parse_rc_info(), lnet_parse_route(), lnet_peer_table_del_rtrs_locked(), lnet_ping(), lnet_ping_info_setup(), lnet_ping_router_locked(), lnet_ptl_match_type(), lnet_send(), lnet_splitnets(), lnet_try_match_md(), lnet_unprepare(), LNetGet(), LNetPut(), lookup_mapping(), lst_alloc_rpcent(), lst_parse_nids(), lst_print_stat(), lst_reset_rpcent(), lstcon_acceptor_handle(), lstcon_ndlink_find(), lstcon_node_find(), lstcon_rpc_get_reply(), lstcon_testrpc_condition(), lustre_lnet_config_route(), lustre_lnet_del_net(), lustre_lnet_del_route(), lustre_lnet_show_net(), lustre_lnet_show_route(), main(), mdt_identity_get_perm(), parse_nid(), parse_perm_line(), ptlrpc_register_rqbd(), read_mapping_db(), rule2string(), rule_spec_net(), sfw_add_test(), sfw_get_stats(), sfw_make_session(), sfw_remove_session(), sptlrpc_parse_rule(), sptlrpc_rule_init(), sptlrpc_rule_set_choose(), srpc_post_passive_rqtbuf(), and srpc_send_request().
#define LNET_PID_ANY ((lnet_pid_t) -1)
wildcard PID that matches any lnet_pid_t
Definition at line 74 of file types.h.
Referenced by jt_ptl_del_peer(), jt_ptl_ping(), ksocknal_add_peer(), ksocknal_close_matching_conns(), ksocknal_create_conn(), ksocknal_create_peer(), ksocknal_ctl(), ksocknal_del_peer(), ksocknal_notify(), ksocknal_push(), ksocknal_shutdown(), libcfs_id2str(), lnet_ioctl(), lnet_parse_nid(), lnet_ping(), lnet_ping_info_setup(), lnet_prepare(), lnet_ptl_match_type(), lnet_try_match_md(), lst_alloc_rpcent(), lst_reset_rpcent(), ptlrpc_register_rqbd(), and srpc_post_passive_rqtbuf().
#define LNET_PID_LUSTRE 12345
Definition at line 78 of file types.h.
Referenced by kgnilnd_query(), ksocknal_ctl(), ksocknal_query(), lnet_configure(), lnet_dyn_configure(), lnet_ping(), lnet_ping_router_locked(), lnet_send(), lst_parse_nids(), ptl_get_pid(), ptlrpc_uuid_to_peer(), and srpc_startup().
#define LNET_PID_RESERVED 0xf0000000
Definition at line 76 of file types.h.
#define LNET_PID_USERFLAG 0x80000000
Definition at line 77 of file types.h.
Referenced by jt_ptl_ping(), ksocknal_launch_packet(), ksocknal_peer_failed(), ksocknal_process_receive(), ksocknal_recv_hello(), libcfs_id2str(), lnet_post_send_locked(), and lnet_prepare().
#define LNET_PROTO_ACCEPTOR_MAGIC 0xacce7100
Definition at line 211 of file types.h.
Referenced by lnet_accept(), and lnet_connect().
#define LNET_PROTO_ACCEPTOR_VERSION 1
Definition at line 229 of file types.h.
Referenced by lnet_accept(), and lnet_connect().
#define LNET_PROTO_GNI_MAGIC 0xb00fbabe
Definition at line 209 of file types.h.
#define LNET_PROTO_IB_MAGIC 0x0be91b91
Definition at line 208 of file types.h.
#define LNET_PROTO_MAGIC 0x45726963
Definition at line 217 of file types.h.
Referenced by kiblnd_passive_connect(), kiblnd_rejected(), ksocknal_parse_proto_version(), ksocknal_recv_hello(), ksocknal_recv_hello_v2(), ksocknal_send_hello_v1(), ksocknal_send_hello_v2(), lnet_accept(), and lnet_connect().
#define LNET_PROTO_PING_MAGIC 0x70696E67
Definition at line 212 of file types.h.
Referenced by lnet_parse_rc_info(), lnet_ping(), and lnet_ping_info_create().
#define LNET_PROTO_TCP_MAGIC 0xeebc0ded
Definition at line 210 of file types.h.
Referenced by ksocknal_parse_proto_version(), ksocknal_recv_hello(), ksocknal_send_hello_v1(), lnet_accept(), lnet_assert_wire_constants(), and main().
#define LNET_PROTO_TCP_VERSION_MAJOR 1
Definition at line 219 of file types.h.
Referenced by lnet_assert_wire_constants(), and main().
#define LNET_PROTO_TCP_VERSION_MINOR 0
Definition at line 220 of file types.h.
Referenced by lnet_assert_wire_constants(), and main().
#define LNET_RESERVED_PORTAL 0
Portal reserved for LNet's own use.
See also:
lustre/include/lustre/lustre_idl.h for Lustre portal assignments.
Definition at line 52 of file types.h.
Referenced by lnet_ping(), lnet_ping_info_setup(), and lnet_ping_router_locked().
#define LNET_TIME_FOREVER (-1)
Definition at line 80 of file types.h.
Referenced by LNetEQWait().
#define LNET_VERSION "0.7.0"
Definition at line 47 of file types.h.
#define LNET_WIRE_HANDLE_COOKIE_NONE (-1)
Definition at line 269 of file types.h.
Referenced by lnet_is_wire_handle_none(), LNetHandleIsInvalid(), LNetInvalidateHandle(), and LNetPut().
#define WIRE_ATTR __attribute__((packed))
Definition at line 115 of file types.h.
Typedef Documentation
typedef struct lnet_ack lnet_ack_t
typedef struct lnet_counters lnet_counters_t
typedef struct lnet_get lnet_get_t
typedef lnet_handle_any_t lnet_handle_eq_t
Definition at line 265 of file types.h.
typedef lnet_handle_any_t lnet_handle_md_t
Definition at line 266 of file types.h.
typedef lnet_handle_any_t lnet_handle_me_t
Definition at line 267 of file types.h.
typedef struct lnet_hello lnet_hello_t
typedef __u64 lnet_nid_t
Address of an end-point in an LNet network.
A node can have multiple end-points and hence multiple addresses. An LNet network can be a simple network (e.g. tcp0) or a network of LNet networks connected by LNet routers. Therefore an end-point address has two parts: network ID, and address within a network.
See also:
LNET_NIDNET, LNET_NIDADDR, and LNET_MKNID.
Definition at line 64 of file types.h.
typedef __u32 lnet_pid_t
ID of a process in a node.
Shortened as PID to distinguish from lnet_process_id_t, the global process ID.
Definition at line 69 of file types.h.
typedef struct lnet_put lnet_put_t
typedef struct lnet_reply lnet_reply_t
Enumeration Type Documentation
enum lnet_msg_type_t
Enumerator:
LNET_MSG_ACK
LNET_MSG_PUT
LNET_MSG_GET
LNET_MSG_REPLY
LNET_MSG_HELLO
Definition at line 132 of file types.h.
Function Documentation
static __u32 LNET_MKNET (__u32 type, __u32 num) [inline, static]
Definition at line 110 of file types.h.
Referenced by class_config_llog_handler(), kgnilnd_post_dgram(), libcfs_str2net_internal(), libcfs_str2nid(), LNetNIInit(), and ptlrpc_uuid_to_peer().
static lnet_nid_t LNET_MKNID (__u32 net, __u32 addr) [inline, static]
Definition at line 95 of file types.h.
References __u64.
Referenced by class_config_llog_handler(), fault_attr_nid_parse(), kgnilnd_ctl(), kgnilnd_lnd2lnetnid(), kgnilnd_lnet2lndnid(), kgnilnd_post_dgram(), kgnilnd_report_node_state(), kgnilnd_startup(), kiblnd_startup(), ksocknal_recv_hello(), ksocknal_startup(), libcfs_str2nid(), lnet_ni_alloc(), and ptlrpc_uuid_to_peer().
static __u32 LNET_NETNUM (__u32 net) [inline, static]
Definition at line 100 of file types.h.
Referenced by cfs_match_nid(), kgnilnd_cancel_net_dgrams(), kgnilnd_find_net(), kgnilnd_startup(), libcfs_net2str_r(), libcfs_nid2str_r(), and lnet_net2rnethash().
static __u32 LNET_NETTYP (__u32 net) [inline, static]
Definition at line 105 of file types.h.
Referenced by cfs_match_nid(), g_net_is_compatible(), jt_ptl_list_nids(), jt_ptl_network(), libcfs_net2str_r(), libcfs_nid2str_r(), ll_compute_rootsquash_state(), lnet_add_route(), lnet_dyn_del_ni(), lnet_net2rnethash(), lnet_ni_send(), lnet_nid2hostname(), lnet_parse_networks(), lnet_parse_rc_info(), lnet_parse_route(), lnet_shuffle_seed(), lnet_startup_lndni(), LNetDist(), lustre_init(), lustre_interface_show_net(), lustre_lnet_config_route(), lustre_lnet_del_route(), lustre_lnet_show_route(), lustre_start_mgc(), server_lsi2mti(), and tgt_connect_check_sptlrpc().
static __u32 LNET_NIDADDR (lnet_nid_t nid) [inline, static]
extract the address part of an lnet_nid_t
Definition at line 85 of file types.h.
Referenced by cfs_match_nid(), fault_attr_nid_parse(), kgnilnd_add_peer(), kgnilnd_check_fma_rx(), kgnilnd_create_peer_safe(), kgnilnd_ctl(), kgnilnd_del_conn_or_peer(), kgnilnd_find_peer_locked(), kgnilnd_launch_tx(), kgnilnd_lnd2lnetnid(), kgnilnd_lnet2lndnid(), kgnilnd_nid2peerlist(), kgnilnd_post_dgram(), kgnilnd_report_node_state(), kgnilnd_unpack_connreq(), kiblnd_connect_peer(), ksocknal_launch_packet(), ksocknal_query(), libcfs_nid2str_r(), lnet_fault_nid_match(), lnet_nid2hostname(), lnet_shuffle_seed(), lstcon_group_ndlink_move(), lstcon_id2hash(), lstcon_ndlink_find(), lstcon_node_find(), lustre_init(), and range_create().
static __u32 LNET_NIDNET (lnet_nid_t nid) [inline, static]
Definition at line 90 of file types.h.
Referenced by cfs_match_nid(), fault_attr_nid_parse(), jt_ptl_del_route(), jt_ptl_list_nids(), jt_ptl_mynid(), jt_ptl_network(), kgnilnd_cancel_net_dgrams(), kgnilnd_ctl(), kgnilnd_find_net(), kgnilnd_lnd2lnetnid(), kgnilnd_lnet2lndnid(), kgnilnd_post_dgram(), kgnilnd_report_node_state(), kgnilnd_startup(), kiblnd_passive_connect(), kiblnd_startup(), ksocknal_recv_hello(), ksocknal_startup(), libcfs_nid2str_r(), libcfs_str2net(), ll_compute_rootsquash_state(), lnet_accept(), lnet_add_route(), lnet_cpt_of_nid_locked(), lnet_del_route(), lnet_destroy_routes(), lnet_dyn_add_ni(), lnet_fault_nid_match(), lnet_find_route_locked(), lnet_match_networks(), lnet_mt_of_match(), lnet_net2ni_locked(), lnet_net_unique(), lnet_ni_send(), lnet_nid2hostname(), lnet_nid2peer_locked(), lnet_notify(), lnet_parse(), lnet_parse_networks(), lnet_parse_rc_info(), lnet_parse_route(), lnet_peer_table_del_rtrs_locked(), lnet_send(), lnet_shuffle_seed(), lnet_splitnets(), lnet_startup_lndni(), LNetDist(), lustre_init(), lustre_interface_show_net(), lustre_lnet_config_route(), lustre_lnet_del_net(), lustre_lnet_del_route(), lustre_lnet_show_net(), lustre_lnet_show_route(), lustre_start_mgc(), range_create(), rule2string(), rule_spec_net(), server_lsi2mti(), sptlrpc_import_sec_adapt(), sptlrpc_parse_rule(), sptlrpc_rule_init(), sptlrpc_rule_set_choose(), and tgt_connect_check_sptlrpc().
int LNetDist (lnet_nid_t dstnid, lnet_nid_t * srcnidp, __u32 * orderp)
Calculate distance to node at dstnid.
Parameters:
dstnid Target NID.
srcnidp If not NULL, NID of the local interface to reach dstnid is saved here.
orderp If not NULL, order of the route to reach dstnid is saved here.
Return values:
0 If dstnid belongs to a local interface, and reserved option local_nid_dist_zero is set, which is the default.
positives Distance to target NID, i.e. number of hops plus one.
-EHOSTUNREACH If dstnid is not reachable.
Definition at line 2460 of file lib-move.c.
References LASSERT, list_empty(), list_entry, list_for_each, list_for_each_entry, lnet_t::ln_nis, lnet_t::ln_refcount, lnet_net2rnethash(), lnet_net_lock_current(), lnet_net_unlock(), LNET_NETTYP(), LNET_NIDNET(), LNET_UNDEFINED_HOPS, local_nid_dist_zero, LOLND, lnet_peer::lp_ni, lnet_route_t::lr_gateway, lnet_route_t::lr_hops, lnet_remotenet_t::lrn_net, lnet_remotenet_t::lrn_routes, lnet_ni::ni_nid, order, and the_lnet.
Referenced by LNetCtl(), and ptlrpc_uuid_to_peer().
int LNetGetId (unsigned int index, lnet_process_id_t * id)
Retrieve the lnet_process_id_t ID of LNet interface at index.
Note that all interfaces share a same PID, as requested by LNetNIInit().
Parameters:
index Index of the interface to look up.
id On successful return, this location will hold the lnet_process_id_t ID of the interface.
Return values:
0 If an interface exists at index.
-ENOENT If no interface has been found.
Definition at line 2129 of file api-ni.c.
References LASSERT, list_entry, list_for_each, lnet_t::ln_nis, lnet_t::ln_pid, lnet_t::ln_refcount, lnet_net_lock_current(), lnet_net_unlock(), and lnet_ni::ni_nid.
Referenced by ll_compute_rootsquash_state(), LNetCtl(), lstcon_new_session_id(), lustre_init(), lustre_start_mgc(), and server_lsi2mti().
static int LNetHandleIsEqual (lnet_handle_any_t h1, lnet_handle_any_t h2) [inline, static]
Compare handles h1 and h2.
Returns:
1 if handles are equal, 0 if otherwise.
Definition at line 284 of file types.h.
References lnet_handle_any_t::cookie.
static int LNetHandleIsInvalid (lnet_handle_any_t h) [inline, static]
Check whether handle h is invalid.
Returns:
1 if handle is invalid, 0 if valid.
Definition at line 294 of file types.h.
References lnet_handle_any_t::cookie, and LNET_WIRE_HANDLE_COOKIE_NONE.
Referenced by lnet_create_rc_data_locked(), lnet_destroy_rc_data(), lnet_md_link(), and lnet_prune_rc_data().
static void LNetInvalidateHandle (lnet_handle_any_t * h) [inline, static]
Invalidate handle h.
Definition at line 274 of file types.h.
References lnet_handle_any_t::cookie, and LNET_WIRE_HANDLE_COOKIE_NONE.
Referenced by lnet_create_rc_data_locked(), lnet_eq2handle(), lnet_lib_init(), lnet_ping_md_unlink(), lnet_router_checker_event(), ptlrpc_new_bulk(), srpc_init_client_rpc(), srpc_init_server_rpc(), srpc_service_post_buffer(), and srpc_startup().
void LNetSnprintHandle (char * str, int str_len, lnet_handle_any_t handle)
Print a string representation of handle h into buffer str of len bytes.
Definition at line 2162 of file api-ni.c.
References lnet_handle_any_t::cookie, and LPX64.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.