Lustre: Lustre Distributed Lock Manager
Lustre Distributed Lock Manager
Lustre DLM is based on VAX DLM.
Data Structures
struct ldlm_pool_ops
Operations on LDLM pools.
struct ldlm_pool
LDLM pool structure to track granted locks.
struct ldlm_valblock_ops
LVB operations.
struct ldlm_ns_bucket
struct ldlm_namespace
LDLM Namespace.
struct ldlm_glimpse_work
Work list for sending GL ASTs to multiple locks.
struct ldlm_interval
Interval node data for each LDLM_EXTENT lock.
struct ldlm_interval_tree
Interval tree for extent locks.
struct ldlm_flock
union ldlm_policy_data
struct ldlm_lock
LDLM lock structure.
struct ldlm_resource
LDLM resource description.
struct ldlm_ast_work
struct ldlm_enqueue_info
Common ldlm_enqueue parameters.
struct ldlm_callback_suite
Modules
Lock iterators
LDLM provides for a way to iterate through every lock on a resource or namespace or every resource in a namespace.
Default AST handlers for local locks
These AST handlers are typically used for server-side local locks and are also used by client-side lock handlers to perform minimum level base processing.
API to operate on locks from actual LDLM users.
These are typically used by client and server (*_local versions) to obtain and release locks.
Various LDLM pool related functions
There are not used outside of ldlm.
Defines
#define OBD_LDLM_DEVICENAME "ldlm"
#define LDLM_DEFAULT_LRU_SIZE (100 * num_online_cpus())
#define LDLM_DEFAULT_MAX_ALIVE (cfs_time_seconds(3900))
#define LDLM_CTIME_AGE_LIMIT (10)
#define LDLM_DEFAULT_PARALLEL_AST_LIMIT 1024
#define LDLM_CB_BLOCKING 1
The blocking callback is overloaded to perform two functions.
#define LDLM_CB_CANCELING 2
#define DLM_OST_NAMESPACE 1
#define DLM_MDS_NAMESPACE 2
#define LDLM_POOLS_THREAD_PERIOD (1)
One second for pools thread check interval.
#define LDLM_POOLS_MODEST_MARGIN_SHIFT (4)
~6% margin for modest pools.
#define LDLM_POOL_SRV_DEF_RECALC_PERIOD (1)
Default recalc period for server side pools in sec.
#define LDLM_POOL_CLI_DEF_RECALC_PERIOD (10)
Default recalc period for client side pools in sec.
#define NS_DEFAULT_MAX_NOLOCK_BYTES 0
Default values for the "max_nolock_size", "contention_time" and "contended_locks" namespace tunables.
#define NS_DEFAULT_CONTENTION_SECONDS 2
#define NS_DEFAULT_CONTENDED_LOCKS 32
#define LDLM_GL_WORK_NOFREE 0x1
The ldlm_glimpse_work is allocated on the stack and should not be freed.
#define to_ldlm_interval(n) container_of(n, struct ldlm_interval, li_node)
#define LUSTRE_TRACKS_LOCK_EXP_REFS (0)
Whether to track references to exports by LDLM locks.
#define LDLM_GID_ANY ((__u64)-1)
LDLM_GID_ANY is used to match any group id in ldlm_lock_match().
#define l_transno l_client_cookie
For uncommitted cross-MDT lock, store transno this lock belongs to.
#define l_slc_link l_rk_ast
For uncommitted cross-MDT lock, which is client lock, share with l_rk_ast which is for server.
#define ei_res_id ei_cb_gl
#define LDLM_DEBUG_NOLOCK(format, a...) CDEBUG(D_DLMTRACE, "### " format "\n" , ##a)
Just a fancy CDEBUG call with log level preset to LDLM_DEBUG.
#define LDLM_DEBUG_LIMIT(mask, lock, fmt, a...) ((void)0)
Support function for lock information printing into debug logs.
#define LDLM_DEBUG(lock, fmt, a...) ((void)0)
#define LDLM_ERROR(lock, fmt, a...) ((void)0)
#define LDLM_ITER_CONTINUE 1
Return values for lock iterators.
#define LDLM_ITER_STOP 2
#define LDLM_LOCK_REF_DEL(lock) lu_ref_del(&lock->l_reference, "handle", current)
#define LDLM_LOCK_PUT(lock)
Release a temporary lock reference obtained by ldlm_handle2lock() or __ldlm_handle2lock().
#define LDLM_LOCK_RELEASE(lock)
Release a lock reference obtained by some other means (see LDLM_LOCK_PUT()).
#define LDLM_LOCK_GET(lock)
#define ldlm_lock_list_put(head, member, count)
#define LDLM_RESOURCE_ADDREF(res)
#define LDLM_RESOURCE_DELREF(res)
Typedefs
typedef int(* ldlm_res_policy)(struct ldlm_namespace *, struct ldlm_lock **, void *req_cookie, enum ldlm_mode mode, __u64 flags, void *data)
typedef int(* ldlm_cancel_cbt)(struct ldlm_lock *lock)
typedef int(* ldlm_blocking_callback)(struct ldlm_lock *lock, struct ldlm_lock_desc *new, void *data, int flag)
Type for blocking callback function of a lock.
typedef int(* ldlm_completion_callback)(struct ldlm_lock *lock, __u64 flags, void *data)
Type for completion callback function of a lock.
typedef int(* ldlm_glimpse_callback)(struct ldlm_lock *lock, void *data)
Type for glimpse callback function of a lock.
typedef int(* ldlm_processing_policy)(struct ldlm_lock *lock, __u64 *flags, int first_enq, enum ldlm_error *err, struct list_head *work_list)
typedef int(* ldlm_iterator_t)(struct ldlm_lock *, void *)
typedef int(* ldlm_res_iterator_t)(struct ldlm_resource *, void *)
Enumerations
enum ldlm_error {
ELDLM_OK = 0, ELDLM_LOCK_MATCHED = 1, ELDLM_LOCK_CHANGED = 300, ELDLM_LOCK_ABORTED = 301,
ELDLM_LOCK_REPLACED = 302, ELDLM_NO_LOCK_DATA = 303, ELDLM_LOCK_WOULDBLOCK = 304, ELDLM_NAMESPACE_EXISTS = 400,
ELDLM_BAD_NAMESPACE = 401
}
LDLM non-error return states.
enum ldlm_side { LDLM_NAMESPACE_SERVER = 0x01, LDLM_NAMESPACE_CLIENT = 0x02 }
LDLM namespace type.
enum ldlm_appetite { LDLM_NAMESPACE_GREEDY = 1 << 0, LDLM_NAMESPACE_MODEST = 1 << 1 }
LDLM pools related, type of lock pool in the namespace.
enum { LDLM_NSS_LOCKS = 0, LDLM_NSS_LAST }
enum ldlm_ns_type {
LDLM_NS_TYPE_UNKNOWN = 0, LDLM_NS_TYPE_MDC, LDLM_NS_TYPE_MDT, LDLM_NS_TYPE_OSC,
LDLM_NS_TYPE_OST, LDLM_NS_TYPE_MGC, LDLM_NS_TYPE_MGT
}
enum ldlm_cancel_flags { LCF_ASYNC = 0x1, LCF_LOCAL = 0x2, LCF_BL_AST = 0x4 }
Cancel flags.
enum lvb_type { LVB_T_NONE = 0, LVB_T_OST = 1, LVB_T_LQUOTA = 2, LVB_T_LAYOUT = 3 }
enum lock_res_type { LRT_NORMAL, LRT_NEW }
"Modes" of acquiring lock_res, necessary to tell lockdep that taking more than one lock_res is dead-lock safe.
Functions
static void lockmode_verify (enum ldlm_mode mode)
static int lockmode_compat (enum ldlm_mode exist_mode, enum ldlm_mode new_mode)
static int ns_is_client (struct ldlm_namespace *ns)
Returns 1 if namespace ns is a client namespace.
static int ns_is_server (struct ldlm_namespace *ns)
Returns 1 if namespace ns is a server namespace.
static int ns_connect_cancelset (struct ldlm_namespace *ns)
Returns 1 if namespace ns supports early lock cancel (ELC).
static int ns_connect_lru_resize (struct ldlm_namespace *ns)
Returns 1 if this namespace supports lru_resize.
static void ns_register_cancel (struct ldlm_namespace *ns, ldlm_cancel_cbt arg)
void ldlm_convert_policy_to_wire (enum ldlm_type type, const union ldlm_policy_data *lpolicy, union ldlm_wire_policy_data *wpolicy)
Converts lock policy from local format to on the wire lock_desc format.
void ldlm_convert_policy_to_local (struct obd_export *exp, enum ldlm_type type, const union ldlm_wire_policy_data *wpolicy, union ldlm_policy_data *lpolicy)
Converts lock policy from on the wire lock_desc format to local format.
static bool ldlm_has_layout (struct ldlm_lock *lock)
static char * ldlm_ns_name (struct ldlm_namespace *ns)
static struct ldlm_namespace * ldlm_res_to_ns (struct ldlm_resource *res)
static struct ldlm_namespace * ldlm_lock_to_ns (struct ldlm_lock *lock)
static char * ldlm_lock_to_ns_name (struct ldlm_lock *lock)
static struct adaptive_timeout * ldlm_lock_to_ns_at (struct ldlm_lock *lock)
static int ldlm_lvbo_init (struct ldlm_resource *res)
static int ldlm_lvbo_size (struct ldlm_lock *lock)
static int ldlm_lvbo_fill (struct ldlm_lock *lock, void *buf, int len)
const char * ldlm_it2str (enum ldlm_intent_flags it)
int ldlm_replay_locks (struct obd_import *imp)
int ldlm_flock_completion_ast (struct ldlm_lock *lock, __u64 flags, void *data)
Flock completion callback function.
__u64 ldlm_extent_shift_kms (struct ldlm_lock *lock, __u64 old_kms)
int ldlm_del_waiting_lock (struct ldlm_lock *lock)
int ldlm_refresh_waiting_lock (struct ldlm_lock *lock, int timeout)
int ldlm_get_ref (void)
void ldlm_put_ref (void)
int ldlm_init_export (struct obd_export *exp)
void ldlm_destroy_export (struct obd_export *exp)
struct ldlm_lock * ldlm_request_lock (struct ptlrpc_request *req)
void ldlm_register_intent (struct ldlm_namespace *ns, ldlm_res_policy arg)
void ldlm_lock2handle (const struct ldlm_lock *lock, struct lustre_handle *lockh)
Fills in handle for LDLM lock lock into supplied lockh Does not take any references.
struct ldlm_lock * __ldlm_handle2lock (const struct lustre_handle *, __u64 flags)
Obtain a lock reference by handle.
void ldlm_cancel_callback (struct ldlm_lock *)
Helper function to call blocking AST for LDLM lock lock in a "cancelling" mode.
int ldlm_lock_remove_from_lru (struct ldlm_lock *)
int ldlm_lock_set_data (const struct lustre_handle *lockh, void *data)
Set opaque data into the lock that only makes sense to upper layer.
static struct ldlm_lock * ldlm_handle2lock (const struct lustre_handle *h)
Obtain a lock reference by its handle.
static struct ldlm_lock * ldlm_handle2lock_long (const struct lustre_handle *h, __u64 flags)
static int ldlm_res_lvbo_update (struct ldlm_resource *res, struct ptlrpc_request *req, int increase)
Update Lock Value Block Operations (LVBO) on a resource taking into account data from request r.
int ldlm_error2errno (enum ldlm_error error)
Rather arbitrary mapping from LDLM error codes to errno values.
enum ldlm_error ldlm_errno2error (int err_no)
Dual to ldlm_error2errno(): maps errno values back to enum ldlm_error.
struct ldlm_lock * ldlm_lock_get (struct ldlm_lock *lock)
Get a reference on a lock.
void ldlm_lock_put (struct ldlm_lock *lock)
Release lock reference.
void ldlm_lock_destroy (struct ldlm_lock *lock)
Destroys a LDLM lock lock.
void ldlm_lock2desc (struct ldlm_lock *lock, struct ldlm_lock_desc *desc)
Fill in "on the wire" representation for given LDLM lock into supplied lock descriptor desc structure.
void ldlm_lock_addref (const struct lustre_handle *lockh, enum ldlm_mode mode)
Add specified reader/writer reference to LDLM lock with handle lockh.
int ldlm_lock_addref_try (const struct lustre_handle *lockh, enum ldlm_mode mode)
Attempts to add reader/writer reference to a lock with handle lockh, and fails if lock is already LDLM_FL_CBPENDING or destroyed.
void ldlm_lock_decref (const struct lustre_handle *lockh, enum ldlm_mode mode)
Decrease reader/writer refcount for LDLM lock with handle lockh.
void ldlm_lock_decref_and_cancel (const struct lustre_handle *lockh, enum ldlm_mode mode)
Decrease reader/writer refcount for LDLM lock with handle lockh and mark it for subsequent cancellation once r/w refcount drops to zero instead of putting into LRU.
void ldlm_lock_fail_match_locked (struct ldlm_lock *lock)
void ldlm_lock_fail_match (struct ldlm_lock *lock)
void ldlm_lock_allow_match (struct ldlm_lock *lock)
Mark lock as "matchable" by OST.
void ldlm_lock_allow_match_locked (struct ldlm_lock *lock)
Mark lock as "matchable" by OST.
enum ldlm_mode ldlm_lock_match (struct ldlm_namespace *ns, __u64 flags, const struct ldlm_res_id *, enum ldlm_type type, union ldlm_policy_data *, enum ldlm_mode mode, struct lustre_handle *, int unref)
Attempt to find a lock with specified properties.
enum ldlm_mode ldlm_revalidate_lock_handle (const struct lustre_handle *lockh, __u64 *bits)
struct ldlm_resource * ldlm_lock_convert (struct ldlm_lock *lock, enum ldlm_mode new_mode, __u32 *flags)
Attempt to convert already granted lock to a different mode.
void ldlm_lock_downgrade (struct ldlm_lock *lock, enum ldlm_mode new_mode)
Downgrade an exclusive lock.
void ldlm_lock_cancel (struct ldlm_lock *lock)
Attempts to cancel LDLM lock lock that has no reader/writer references.
void ldlm_reprocess_all (struct ldlm_resource *res)
Try to grant all waiting locks on a resource.
void ldlm_reprocess_all_ns (struct ldlm_namespace *ns)
Iterate through all resources on a namespace attempting to grant waiting locks.
void ldlm_lock_dump_handle (int level, const struct lustre_handle *lockh)
Print lock with lock handle lockh description into debug log.
void ldlm_unlink_lock_skiplist (struct ldlm_lock *req)
Remove skiplist-enabled LDLM lock req from granted list.
struct ldlm_namespace * ldlm_namespace_new (struct obd_device *obd, char *name, enum ldlm_side client, enum ldlm_appetite apt, enum ldlm_ns_type ns_type)
Create and initialize new empty namespace.
int ldlm_namespace_cleanup (struct ldlm_namespace *ns, __u64 flags)
Cancel and destroy all locks in the namespace.
void ldlm_namespace_free_prior (struct ldlm_namespace *ns, struct obd_import *imp, int force)
Performs various cleanups for passed ns to make it drop refc and be ready for freeing.
void ldlm_namespace_free_post (struct ldlm_namespace *ns)
Performs freeing memory structures related to ns.
void ldlm_namespace_free (struct ldlm_namespace *ns, struct obd_import *imp, int force)
Cleanup the resource, and free namespace.
void ldlm_namespace_register (struct ldlm_namespace *ns, enum ldlm_side client)
Register ns in the list of namespaces.
void ldlm_namespace_unregister (struct ldlm_namespace *ns, enum ldlm_side client)
Unregister ns from the list of namespaces.
void ldlm_namespace_get (struct ldlm_namespace *ns)
void ldlm_namespace_put (struct ldlm_namespace *ns)
int ldlm_proc_setup (void)
static void ldlm_proc_cleanup (void)
struct ldlm_resource * ldlm_resource_get (struct ldlm_namespace *ns, struct ldlm_resource *parent, const struct ldlm_res_id *, enum ldlm_type type, int create)
Return a reference to resource with given name, creating it if necessary.
struct ldlm_resource * ldlm_resource_getref (struct ldlm_resource *res)
int ldlm_resource_putref (struct ldlm_resource *res)
void ldlm_resource_add_lock (struct ldlm_resource *res, struct list_head *head, struct ldlm_lock *lock)
Add a lock into a given resource into specified lock list.
void ldlm_resource_unlink_lock (struct ldlm_lock *lock)
void ldlm_res2desc (struct ldlm_resource *res, struct ldlm_resource_desc *desc)
void ldlm_dump_all_namespaces (enum ldlm_side client, int level)
Print information about all locks in all namespaces on this node to debug log.
void ldlm_namespace_dump (int level, struct ldlm_namespace *)
Print information about all locks in this namespace on this node to debug log.
void ldlm_resource_dump (int level, struct ldlm_resource *)
Print information about all locks in this resource to debug log.
int ldlm_lock_change_resource (struct ldlm_namespace *, struct ldlm_lock *, const struct ldlm_res_id *)
Moves LDLM lock lock to another resource.
int ldlm_expired_completion_wait (void *data)
int intent_disposition (struct ldlm_reply *rep, int flag)
void intent_set_disposition (struct ldlm_reply *rep, int flag)
static void lock_res (struct ldlm_resource *res)
Lock resource.
static void lock_res_nested (struct ldlm_resource *res, enum lock_res_type mode)
Lock resource with a way to instruct lockdep code about nestedness-safe.
static void unlock_res (struct ldlm_resource *res)
Unlock resource.
static void check_res_locked (struct ldlm_resource *res)
Check if resource is already locked, assert if not.
struct ldlm_resource * lock_res_and_lock (struct ldlm_lock *lock)
Lock a lock and its resource.
void unlock_res_and_lock (struct ldlm_lock *lock)
Unlock a lock and its resource previously locked with lock_res_and_lock.
Variables
enum ldlm_mode lck_compat_array []
struct obd_ops ldlm_obd_ops
char * ldlm_lockname []
char * ldlm_typename []
Lock Compatibility Matrix.
A lock has both a type (extent, flock, inode bits, or plain) and a mode.
Lock types are described in their respective implementation files: ldlm_{extent,flock,inodebits,plain}.c.
There are six lock modes along with a compatibility matrix to indicate if two locks are compatible.
EX: Exclusive mode. Before a new file is created, MDS requests EX lock on the parent.
PW: Protective Write (normal write) mode. When a client requests a write lock from an OST, a lock with PW mode will be issued.
PR: Protective Read (normal read) mode. When a client requests a read from an OST, a lock with PR mode will be issued. Also, if the client opens a file for execution, it is granted a lock with PR mode.
CW: Concurrent Write mode. The type of lock that the MDS grants if a client requests a write lock during a file open operation.
CR Concurrent Read mode. When a client performs a path lookup, MDS grants an inodebit lock with the CR mode on the intermediate path component.
NL Null mode.
       NL  CR  CW  PR  PW  EX
  NL    1   1   1   1   1   1
  CR    1   1   1   1   1   0
  CW    1   1   1   0   0   0
  PR    1   1   0   1   0   0
  PW    1   1   0   0   0   0
  EX    1   0   0   0   0   0
#define LCK_COMPAT_EX LCK_NL
#define LCK_COMPAT_PW (LCK_COMPAT_EX | LCK_CR)
#define LCK_COMPAT_PR (LCK_COMPAT_PW | LCK_PR)
#define LCK_COMPAT_CW (LCK_COMPAT_PW | LCK_CW)
#define LCK_COMPAT_CR (LCK_COMPAT_CW | LCK_PR | LCK_PW)
#define LCK_COMPAT_NL (LCK_COMPAT_CR | LCK_EX | LCK_GROUP)
#define LCK_COMPAT_GROUP (LCK_GROUP | LCK_NL)
#define LCK_COMPAT_COS (LCK_COS)
flags
The flags and collections of flags (masks) for
See also:
struct ldlm_lock.
#define LDLM_FL_ALL_FLAGS_MASK 0x00FFFFFFC08F932FULL
l_flags bits marked as "all_flags" bits
#define LDLM_FL_LOCK_CHANGED 0x0000000000000001ULL
extent, mode, or resource changed
#define ldlm_is_lock_changed(_l) LDLM_TEST_FLAG((_l), 1ULL << 0)
#define ldlm_set_lock_changed(_l) LDLM_SET_FLAG((_l), 1ULL << 0)
#define ldlm_clear_lock_changed(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 0)
#define LDLM_FL_BLOCK_GRANTED 0x0000000000000002ULL
Server placed lock on granted list, or a recovering client wants the lock added to the granted list, no questions asked.
#define ldlm_is_block_granted(_l) LDLM_TEST_FLAG((_l), 1ULL << 1)
#define ldlm_set_block_granted(_l) LDLM_SET_FLAG((_l), 1ULL << 1)
#define ldlm_clear_block_granted(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 1)
#define LDLM_FL_BLOCK_CONV 0x0000000000000004ULL
Server placed lock on conv list, or a recovering client wants the lock added to the conv list, no questions asked.
#define ldlm_is_block_conv(_l) LDLM_TEST_FLAG((_l), 1ULL << 2)
#define ldlm_set_block_conv(_l) LDLM_SET_FLAG((_l), 1ULL << 2)
#define ldlm_clear_block_conv(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 2)
#define LDLM_FL_BLOCK_WAIT 0x0000000000000008ULL
Server placed lock on wait list, or a recovering client wants the lock added to the wait list, no questions asked.
#define ldlm_is_block_wait(_l) LDLM_TEST_FLAG((_l), 1ULL << 3)
#define ldlm_set_block_wait(_l) LDLM_SET_FLAG((_l), 1ULL << 3)
#define ldlm_clear_block_wait(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 3)
#define LDLM_FL_AST_SENT 0x0000000000000020ULL
blocking or cancel packet was queued for sending.
#define ldlm_is_ast_sent(_l) LDLM_TEST_FLAG((_l), 1ULL << 5)
#define ldlm_set_ast_sent(_l) LDLM_SET_FLAG((_l), 1ULL << 5)
#define ldlm_clear_ast_sent(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 5)
#define LDLM_FL_REPLAY 0x0000000000000100ULL
Lock is being replayed.
#define ldlm_is_replay(_l) LDLM_TEST_FLAG((_l), 1ULL << 8)
#define ldlm_set_replay(_l) LDLM_SET_FLAG((_l), 1ULL << 8)
#define ldlm_clear_replay(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 8)
#define LDLM_FL_INTENT_ONLY 0x0000000000000200ULL
Don't grant lock, just do intent.
#define ldlm_is_intent_only(_l) LDLM_TEST_FLAG((_l), 1ULL << 9)
#define ldlm_set_intent_only(_l) LDLM_SET_FLAG((_l), 1ULL << 9)
#define ldlm_clear_intent_only(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 9)
#define LDLM_FL_HAS_INTENT 0x0000000000001000ULL
lock request has intent
#define ldlm_is_has_intent(_l) LDLM_TEST_FLAG((_l), 1ULL << 12)
#define ldlm_set_has_intent(_l) LDLM_SET_FLAG((_l), 1ULL << 12)
#define ldlm_clear_has_intent(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 12)
#define LDLM_FL_FLOCK_DEADLOCK 0x0000000000008000ULL
flock deadlock detected
#define ldlm_is_flock_deadlock(_l) LDLM_TEST_FLAG((_l), 1ULL << 15)
#define ldlm_set_flock_deadlock(_l) LDLM_SET_FLAG((_l), 1ULL << 15)
#define ldlm_clear_flock_deadlock(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 15)
#define LDLM_FL_DISCARD_DATA 0x0000000000010000ULL
discard (no writeback) on cancel
#define ldlm_is_discard_data(_l) LDLM_TEST_FLAG((_l), 1ULL << 16)
#define ldlm_set_discard_data(_l) LDLM_SET_FLAG((_l), 1ULL << 16)
#define ldlm_clear_discard_data(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 16)
#define LDLM_FL_NO_TIMEOUT 0x0000000000020000ULL
Blocked by group lock - wait indefinitely.
#define ldlm_is_no_timeout(_l) LDLM_TEST_FLAG((_l), 1ULL << 17)
#define ldlm_set_no_timeout(_l) LDLM_SET_FLAG((_l), 1ULL << 17)
#define ldlm_clear_no_timeout(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 17)
#define LDLM_FL_BLOCK_NOWAIT 0x0000000000040000ULL
Server told not to wait if blocked.
#define ldlm_is_block_nowait(_l) LDLM_TEST_FLAG((_l), 1ULL << 18)
#define ldlm_set_block_nowait(_l) LDLM_SET_FLAG((_l), 1ULL << 18)
#define ldlm_clear_block_nowait(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 18)
#define LDLM_FL_TEST_LOCK 0x0000000000080000ULL
return blocking lock
#define ldlm_is_test_lock(_l) LDLM_TEST_FLAG((_l), 1ULL << 19)
#define ldlm_set_test_lock(_l) LDLM_SET_FLAG((_l), 1ULL << 19)
#define ldlm_clear_test_lock(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 19)
#define LDLM_FL_MATCH_LOCK 0x0000000000100000ULL
match lock only
#define LDLM_FL_CANCEL_ON_BLOCK 0x0000000000800000ULL
Immediatelly cancel such locks when they block some other locks.
#define ldlm_is_cancel_on_block(_l) LDLM_TEST_FLAG((_l), 1ULL << 23)
#define ldlm_set_cancel_on_block(_l) LDLM_SET_FLAG((_l), 1ULL << 23)
#define ldlm_clear_cancel_on_block(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 23)
#define LDLM_FL_COS_INCOMPAT 0x0000000001000000ULL
Flag whether a lock is enqueued from a distributed transaction, and the requesting lock mode is PW/EX, if so, it will check compatibility with COS locks, and different from original COS semantic, transactions from the same client is also treated as lock conflict.
#define ldlm_is_cos_incompat(_l) LDLM_TEST_FLAG((_l), 1ULL << 24)
#define ldlm_set_cos_incompat(_l) LDLM_SET_FLAG((_l), 1ULL << 24)
#define ldlm_clear_cos_incompat(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 24)
#define LDLM_FL_DENY_ON_CONTENTION 0x0000000040000000ULL
measure lock contention and return -EUSERS if locking contention is high
#define ldlm_is_deny_on_contention(_l) LDLM_TEST_FLAG((_l), 1ULL << 30)
#define ldlm_set_deny_on_contention(_l) LDLM_SET_FLAG((_l), 1ULL << 30)
#define ldlm_clear_deny_on_contention(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 30)
#define LDLM_FL_AST_DISCARD_DATA 0x0000000080000000ULL
These are flags that are mapped into the flags and ASTs of blocking locks Add FL_DISCARD to blocking ASTs.
#define ldlm_is_ast_discard_data(_l) LDLM_TEST_FLAG((_l), 1ULL << 31)
#define ldlm_set_ast_discard_data(_l) LDLM_SET_FLAG((_l), 1ULL << 31)
#define ldlm_clear_ast_discard_data(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 31)
#define LDLM_FL_FAIL_LOC 0x0000000100000000ULL
Used for marking lock as a target for -EINTR while cp_ast sleep emulation + race with upcoming bl_ast.
#define ldlm_is_fail_loc(_l) LDLM_TEST_FLAG((_l), 1ULL << 32)
#define ldlm_set_fail_loc(_l) LDLM_SET_FLAG((_l), 1ULL << 32)
#define ldlm_clear_fail_loc(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 32)
#define LDLM_FL_SKIPPED 0x0000000200000000ULL
Used while processing the unused list to know that we have already handled this lock and decided to skip it.
#define ldlm_is_skipped(_l) LDLM_TEST_FLAG((_l), 1ULL << 33)
#define ldlm_set_skipped(_l) LDLM_SET_FLAG((_l), 1ULL << 33)
#define ldlm_clear_skipped(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 33)
#define LDLM_FL_CBPENDING 0x0000000400000000ULL
this lock is being destroyed
#define ldlm_is_cbpending(_l) LDLM_TEST_FLAG((_l), 1ULL << 34)
#define ldlm_set_cbpending(_l) LDLM_SET_FLAG((_l), 1ULL << 34)
#define ldlm_clear_cbpending(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 34)
#define LDLM_FL_WAIT_NOREPROC 0x0000000800000000ULL
not a real flag, not saved in lock
#define ldlm_is_wait_noreproc(_l) LDLM_TEST_FLAG((_l), 1ULL << 35)
#define ldlm_set_wait_noreproc(_l) LDLM_SET_FLAG((_l), 1ULL << 35)
#define ldlm_clear_wait_noreproc(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 35)
#define LDLM_FL_CANCEL 0x0000001000000000ULL
cancellation callback already run
#define ldlm_is_cancel(_l) LDLM_TEST_FLAG((_l), 1ULL << 36)
#define ldlm_set_cancel(_l) LDLM_SET_FLAG((_l), 1ULL << 36)
#define ldlm_clear_cancel(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 36)
#define LDLM_FL_LOCAL_ONLY 0x0000002000000000ULL
whatever it might mean -- never transmitted?
#define ldlm_is_local_only(_l) LDLM_TEST_FLAG((_l), 1ULL << 37)
#define ldlm_set_local_only(_l) LDLM_SET_FLAG((_l), 1ULL << 37)
#define ldlm_clear_local_only(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 37)
#define LDLM_FL_FAILED 0x0000004000000000ULL
don't run the cancel callback under ldlm_cli_cancel_unused
#define ldlm_is_failed(_l) LDLM_TEST_FLAG((_l), 1ULL << 38)
#define ldlm_set_failed(_l) LDLM_SET_FLAG((_l), 1ULL << 38)
#define ldlm_clear_failed(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 38)
#define LDLM_FL_CANCELING 0x0000008000000000ULL
lock cancel has already been sent
#define ldlm_is_canceling(_l) LDLM_TEST_FLAG((_l), 1ULL << 39)
#define ldlm_set_canceling(_l) LDLM_SET_FLAG((_l), 1ULL << 39)
#define ldlm_clear_canceling(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 39)
#define LDLM_FL_LOCAL 0x0000010000000000ULL
local lock (ie, no srv/cli split)
#define ldlm_is_local(_l) LDLM_TEST_FLAG((_l), 1ULL << 40)
#define ldlm_set_local(_l) LDLM_SET_FLAG((_l), 1ULL << 40)
#define ldlm_clear_local(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 40)
#define LDLM_FL_LVB_READY 0x0000020000000000ULL
XXX FIXME: This is being added to b_size as a low-risk fix to the fact that the LVB filling happens _after_ the lock has been granted, so another thread can match it before the LVB has been updated.
#define ldlm_is_lvb_ready(_l) LDLM_TEST_FLAG((_l), 1ULL << 41)
#define ldlm_set_lvb_ready(_l) LDLM_SET_FLAG((_l), 1ULL << 41)
#define ldlm_clear_lvb_ready(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 41)
#define LDLM_FL_KMS_IGNORE 0x0000040000000000ULL
A lock contributes to the known minimum size (KMS) calculation until it has finished the part of its cancelation that performs write back on its dirty pages.
#define ldlm_is_kms_ignore(_l) LDLM_TEST_FLAG((_l), 1ULL << 42)
#define ldlm_set_kms_ignore(_l) LDLM_SET_FLAG((_l), 1ULL << 42)
#define ldlm_clear_kms_ignore(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 42)
#define LDLM_FL_CP_REQD 0x0000080000000000ULL
completion AST to be executed
#define ldlm_is_cp_reqd(_l) LDLM_TEST_FLAG((_l), 1ULL << 43)
#define ldlm_set_cp_reqd(_l) LDLM_SET_FLAG((_l), 1ULL << 43)
#define ldlm_clear_cp_reqd(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 43)
#define LDLM_FL_CLEANED 0x0000100000000000ULL
cleanup_resource has already handled the lock
#define ldlm_is_cleaned(_l) LDLM_TEST_FLAG((_l), 1ULL << 44)
#define ldlm_set_cleaned(_l) LDLM_SET_FLAG((_l), 1ULL << 44)
#define ldlm_clear_cleaned(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 44)
#define LDLM_FL_ATOMIC_CB 0x0000200000000000ULL
optimization hint: LDLM can run blocking callback from current context w/o involving separate thread.
#define ldlm_is_atomic_cb(_l) LDLM_TEST_FLAG((_l), 1ULL << 45)
#define ldlm_set_atomic_cb(_l) LDLM_SET_FLAG((_l), 1ULL << 45)
#define ldlm_clear_atomic_cb(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 45)
#define LDLM_FL_BL_AST 0x0000400000000000ULL
It may happen that a client initiates two operations, e.g.
#define ldlm_is_bl_ast(_l) LDLM_TEST_FLAG((_l), 1ULL << 46)
#define ldlm_set_bl_ast(_l) LDLM_SET_FLAG((_l), 1ULL << 46)
#define ldlm_clear_bl_ast(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 46)
#define LDLM_FL_BL_DONE 0x0000800000000000ULL
Set by ldlm_cancel_callback() when lock cache is dropped to let ldlm_callback_handler() return EINVAL to the server.
#define ldlm_is_bl_done(_l) LDLM_TEST_FLAG((_l), 1ULL << 47)
#define ldlm_set_bl_done(_l) LDLM_SET_FLAG((_l), 1ULL << 47)
#define ldlm_clear_bl_done(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 47)
#define LDLM_FL_NO_LRU 0x0001000000000000ULL
Don't put lock into the LRU list, so that it is not canceled due to aging.
#define ldlm_is_no_lru(_l) LDLM_TEST_FLAG((_l), 1ULL << 48)
#define ldlm_set_no_lru(_l) LDLM_SET_FLAG((_l), 1ULL << 48)
#define ldlm_clear_no_lru(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 48)
#define LDLM_FL_FAIL_NOTIFIED 0x0002000000000000ULL
Set for locks that failed and where the server has been notified.
#define ldlm_is_fail_notified(_l) LDLM_TEST_FLAG((_l), 1ULL << 49)
#define ldlm_set_fail_notified(_l) LDLM_SET_FLAG((_l), 1ULL << 49)
#define ldlm_clear_fail_notified(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 49)
#define LDLM_FL_DESTROYED 0x0004000000000000ULL
Set for locks that were removed from class hash table and will be destroyed when last reference to them is released.
#define ldlm_is_destroyed(_l) LDLM_TEST_FLAG((_l), 1ULL << 50)
#define ldlm_set_destroyed(_l) LDLM_SET_FLAG((_l), 1ULL << 50)
#define ldlm_clear_destroyed(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 50)
#define LDLM_FL_SERVER_LOCK 0x0008000000000000ULL
flag whether this is a server namespace lock
#define ldlm_is_server_lock(_l) LDLM_TEST_FLAG((_l), 1ULL << 51)
#define ldlm_set_server_lock(_l) LDLM_SET_FLAG((_l), 1ULL << 51)
#define ldlm_clear_server_lock(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 51)
#define LDLM_FL_RES_LOCKED 0x0010000000000000ULL
It's set in lock_res_and_lock() and unset in unlock_res_and_lock().
#define ldlm_is_res_locked(_l) LDLM_TEST_FLAG((_l), 1ULL << 52)
#define ldlm_set_res_locked(_l) LDLM_SET_FLAG((_l), 1ULL << 52)
#define ldlm_clear_res_locked(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 52)
#define LDLM_FL_WAITED 0x0020000000000000ULL
It's set once we call ldlm_add_waiting_lock_res_locked() to start the lock-timeout timer and it will never be reset.
#define ldlm_is_waited(_l) LDLM_TEST_FLAG((_l), 1ULL << 53)
#define ldlm_set_waited(_l) LDLM_SET_FLAG((_l), 1ULL << 53)
#define ldlm_clear_waited(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 53)
#define LDLM_FL_NS_SRV 0x0040000000000000ULL
Flag whether this is a server namespace lock.
#define ldlm_is_ns_srv(_l) LDLM_TEST_FLAG((_l), 1ULL << 54)
#define ldlm_set_ns_srv(_l) LDLM_SET_FLAG((_l), 1ULL << 54)
#define ldlm_clear_ns_srv(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 54)
#define LDLM_FL_EXCL 0x0080000000000000ULL
Flag whether this lock can be reused.
#define ldlm_is_excl(_l) LDLM_TEST_FLAG((_l), 1ULL << 55)
#define ldlm_set_excl(_l) LDLM_SET_FLAG((_l), 1ULL << 55)
#define ldlm_clear_excl(_l) LDLM_CLEAR_FLAG((_l), 1ULL << 55)
#define LDLM_FL_RESENT 0x0100000000000000ULL
Flag whether a lock is found on server for re-sent RPC.
#define LDLM_FL_COS_ENABLED 0x0200000000000000ULL
Flag whether Commit-on-Sharing is enabled, if LDLM_FL_COS_INCOMPAT is set this flag may not be set because once the former is set this flag won't be checked, and for cross-MDT lock COS_INCOMPAT is always set but ast handle is in ldlm context which doesn't know whether COS is enabled or not.
#define ldlm_is_cos_enabled(_l) LDLM_TEST_FLAG((_l), 1ULL << 57)
#define ldlm_set_cos_enabled(_l) LDLM_SET_FLAG((_l), 1ULL << 57)
#define LDLM_FL_AST_MASK
l_flags bits marked as "ast" bits
#define LDLM_FL_BLOCKED_MASK
l_flags bits marked as "blocked" bits
#define LDLM_FL_GONE_MASK
l_flags bits marked as "gone" bits
#define LDLM_FL_INHERIT_MASK
l_flags bits marked as "inherit" bits
#define LDLM_FL_SRV_ENQ_MASK
flags returned in parameter on ldlm_lock_enqueue, to be re-constructed on re-send
#define LDLM_TEST_FLAG(_l, _b) (((_l)->l_flags & (_b)) != 0)
test for ldlm_lock flag bit set
#define LDLM_HAVE_MASK(_l, _m) (((_l)->l_flags & LDLM_FL_##_m##_MASK) != 0)
multi-bit test: are any of mask bits set?
#define LDLM_SET_FLAG(_l, _b) ((_l)->l_flags |= (_b))
set a ldlm_lock flag bit
#define LDLM_CLEAR_FLAG(_l, _b) ((_l)->l_flags &= ~(_b))
clear a ldlm_lock flag bit
Detailed Description
Lustre DLM is based on VAX DLM.
Its two main roles are:
To provide locking assuring consistency of data on all Lustre nodes.
To allow clients to cache state protected by a lock by holding the lock until a conflicting lock is requested or it is expired by the LRU.
Define Documentation
#define DLM_MDS_NAMESPACE 2
Definition at line 170 of file lustre_dlm.h.
#define DLM_OST_NAMESPACE 1
Definition at line 169 of file lustre_dlm.h.
#define ei_res_id ei_cb_gl
Definition at line 1109 of file lustre_dlm.h.
#define l_slc_link l_rk_ast
For uncommitted cross-MDT lock, which is client lock, share with l_rk_ast which is for server.
Definition at line 909 of file lustre_dlm.h.
Referenced by tgt_cancel_slc_locks().
#define l_transno l_client_cookie
For uncommitted cross-MDT lock, store transno this lock belongs to.
Definition at line 905 of file lustre_dlm.h.
#define LCK_COMPAT_COS (LCK_COS)
Definition at line 147 of file lustre_dlm.h.
#define LCK_COMPAT_CR (LCK_COMPAT_CW | LCK_PR | LCK_PW)
Definition at line 144 of file lustre_dlm.h.
#define LCK_COMPAT_CW (LCK_COMPAT_PW | LCK_CW)
Definition at line 143 of file lustre_dlm.h.
#define LCK_COMPAT_EX LCK_NL
Definition at line 140 of file lustre_dlm.h.
#define LCK_COMPAT_GROUP (LCK_GROUP | LCK_NL)
Definition at line 146 of file lustre_dlm.h.
#define LCK_COMPAT_NL (LCK_COMPAT_CR | LCK_EX | LCK_GROUP)
Definition at line 145 of file lustre_dlm.h.
#define LCK_COMPAT_PR (LCK_COMPAT_PW | LCK_PR)
Definition at line 142 of file lustre_dlm.h.
#define LCK_COMPAT_PW (LCK_COMPAT_EX | LCK_CR)
Definition at line 141 of file lustre_dlm.h.
#define LDLM_CB_BLOCKING 1
The blocking callback is overloaded to perform two functions.
These flags indicate which operation should be performed.
Definition at line 103 of file lustre_dlm.h.
Referenced by ldlm_handle_bl_callback(), ldlm_work_bl_ast_lock(), ldlm_work_revoke_ast_lock(), ll_md_blocking_ast(), ll_md_blocking_lease_ast(), mdt_remote_blocking_ast(), mgc_blocking_ast(), osc_ldlm_blocking_ast(), qsd_glb_blocking_ast(), and qsd_id_blocking_ast().
#define LDLM_CB_CANCELING 2
Definition at line 104 of file lustre_dlm.h.
Referenced by ldlm_blocking_ast(), ldlm_cancel_callback(), ldlm_flock_blocking_ast(), ll_md_blocking_ast(), ll_md_blocking_lease_ast(), mdt_blocking_ast(), mdt_remote_blocking_ast(), mgc_blocking_ast(), osc_dlm_blocking_ast0(), osc_ldlm_blocking_ast(), qsd_glb_blocking_ast(), qsd_id_blocking_ast(), and tgt_blocking_ast().
#define ldlm_clear_ast_discard_data (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 31)
Definition at line 154 of file lustre_dlm_flags.h.
#define ldlm_clear_ast_sent (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 5)
Definition at line 65 of file lustre_dlm_flags.h.
#define ldlm_clear_atomic_cb (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 45)
Definition at line 261 of file lustre_dlm_flags.h.
#define ldlm_clear_bl_ast (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 46)
Definition at line 273 of file lustre_dlm_flags.h.
#define ldlm_clear_bl_done (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 47)
Definition at line 283 of file lustre_dlm_flags.h.
#define ldlm_clear_block_conv (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 2)
Definition at line 51 of file lustre_dlm_flags.h.
#define ldlm_clear_block_granted (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 1)
Definition at line 43 of file lustre_dlm_flags.h.
#define ldlm_clear_block_nowait (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 18)
Definition at line 111 of file lustre_dlm_flags.h.
#define ldlm_clear_block_wait (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 3)
Definition at line 59 of file lustre_dlm_flags.h.
#define ldlm_clear_cancel (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 36)
Definition at line 188 of file lustre_dlm_flags.h.
#define ldlm_clear_cancel_on_block (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 23)
Definition at line 130 of file lustre_dlm_flags.h.
Referenced by ldlm_prepare_lru_list().
#define ldlm_clear_canceling (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 39)
Definition at line 206 of file lustre_dlm_flags.h.
#define ldlm_clear_cbpending (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 34)
Definition at line 176 of file lustre_dlm_flags.h.
#define ldlm_clear_cleaned (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 44)
Definition at line 253 of file lustre_dlm_flags.h.
Referenced by osc_ldlm_resource_invalidate().
#define ldlm_clear_cos_incompat (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 24)
Definition at line 139 of file lustre_dlm_flags.h.
#define ldlm_clear_cp_reqd (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 43)
Definition at line 247 of file lustre_dlm_flags.h.
Referenced by ldlm_work_cp_ast_lock().
#define ldlm_clear_deny_on_contention (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 30)
Definition at line 146 of file lustre_dlm_flags.h.
#define ldlm_clear_destroyed (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 50)
Definition at line 312 of file lustre_dlm_flags.h.
#define ldlm_clear_discard_data (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 16)
Definition at line 97 of file lustre_dlm_flags.h.
#define ldlm_clear_excl (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 55)
Definition at line 352 of file lustre_dlm_flags.h.
#define ldlm_clear_fail_loc (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 32)
Definition at line 162 of file lustre_dlm_flags.h.
#define ldlm_clear_fail_notified (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 49)
Definition at line 301 of file lustre_dlm_flags.h.
#define ldlm_clear_failed (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 38)
Definition at line 200 of file lustre_dlm_flags.h.
#define LDLM_CLEAR_FLAG (_l, _b) ((_l)->l_flags &= ~(_b))
clear a ldlm_lock flag bit
Definition at line 402 of file lustre_dlm_flags.h.
#define ldlm_clear_flock_deadlock (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 15)
Definition at line 91 of file lustre_dlm_flags.h.
#define ldlm_clear_has_intent (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 12)
Definition at line 85 of file lustre_dlm_flags.h.
#define ldlm_clear_intent_only (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 9)
Definition at line 79 of file lustre_dlm_flags.h.
#define ldlm_clear_kms_ignore (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 42)
Definition at line 241 of file lustre_dlm_flags.h.
#define ldlm_clear_local (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 40)
Definition at line 212 of file lustre_dlm_flags.h.
#define ldlm_clear_local_only (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 37)
Definition at line 194 of file lustre_dlm_flags.h.
#define ldlm_clear_lock_changed (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 0)
Definition at line 35 of file lustre_dlm_flags.h.
#define ldlm_clear_lvb_ready (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 41)
Definition at line 229 of file lustre_dlm_flags.h.
#define ldlm_clear_no_lru (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 48)
Definition at line 292 of file lustre_dlm_flags.h.
#define ldlm_clear_no_timeout (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 17)
Definition at line 103 of file lustre_dlm_flags.h.
#define ldlm_clear_ns_srv (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 54)
Definition at line 346 of file lustre_dlm_flags.h.
#define ldlm_clear_replay (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 8)
Definition at line 73 of file lustre_dlm_flags.h.
#define ldlm_clear_res_locked (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 52)
Definition at line 330 of file lustre_dlm_flags.h.
Referenced by unlock_res_and_lock().
#define ldlm_clear_server_lock (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 51)
Definition at line 318 of file lustre_dlm_flags.h.
#define ldlm_clear_skipped (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 33)
Definition at line 170 of file lustre_dlm_flags.h.
Referenced by ldlm_lock_add_to_lru_nolock().
#define ldlm_clear_test_lock (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 19)
Definition at line 117 of file lustre_dlm_flags.h.
#define ldlm_clear_wait_noreproc (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 35)
Definition at line 182 of file lustre_dlm_flags.h.
#define ldlm_clear_waited (_l) LDLM_CLEAR_FLAG((_l), 1ULL << 53)
Definition at line 340 of file lustre_dlm_flags.h.
#define LDLM_CTIME_AGE_LIMIT (10)
Definition at line 67 of file lustre_dlm.h.
Referenced by ldlm_namespace_new().
#define LDLM_DEBUG (lock, fmt, a...) ((void)0)
Definition at line 1168 of file lustre_dlm.h.
Referenced by cleanup_resource(), failed_lock_cleanup(), ldlm_add_bl_work_item(), ldlm_add_cp_work_item(), ldlm_blocking_ast_nocheck(), ldlm_callback_handler(), ldlm_cancel_callback(), ldlm_cancel_pack(), ldlm_cli_cancel_list_local(), ldlm_cli_cancel_local(), ldlm_cli_convert(), ldlm_cli_convert_local(), ldlm_cli_enqueue(), ldlm_cli_enqueue_fini(), ldlm_cli_enqueue_local(), ldlm_completion_ast(), ldlm_completion_ast_async(), ldlm_completion_tail(), ldlm_flock_completion_ast(), ldlm_flock_destroy(), ldlm_granted_list_add_lock(), ldlm_handle_bl_callback(), ldlm_handle_cp_callback(), ldlm_handle_gl_callback(), ldlm_lock_addref_internal_nolock(), ldlm_lock_decref_and_cancel(), ldlm_lock_decref_internal(), ldlm_lock_decref_internal_nolock(), ldlm_lock_match(), ldlm_lock_put(), ldlm_resource_add_lock(), ldlm_resource_insert_lock_after(), ll_layout_lock_set(), mdc_finish_enqueue(), mdc_finish_intent_lock(), mdt_close_swap_layouts(), mdt_getattr_name_lock(), mdt_hsm_release(), mdt_intent_fixup_resent(), mdt_reint_migrate_internal(), mdt_remote_blocking_ast(), mgc_blocking_ast(), ofd_prolong_one_lock(), osc_lock_lvb_update(), qmt_dqacq(), qsd_glb_blocking_ast(), qsd_id_blocking_ast(), replay_lock_interpret(), and replay_one_lock().
#define LDLM_DEBUG_LIMIT (mask, lock, fmt, a...) ((void)0)
Support function for lock information printing into debug logs.
See also:
LDLM_DEBUG
Definition at line 1167 of file lustre_dlm.h.
Referenced by ldlm_lock_dump_handle(), ldlm_resource_dump(), and ll_inode_from_resource_lock().
#define LDLM_DEBUG_NOLOCK (format, a...) CDEBUG(D_DLMTRACE, "### " format "\n" , ##a)
Just a fancy CDEBUG call with log level preset to LDLM_DEBUG.
For the cases where we do not have actual lock to print along with a debugging message that is ldlm-related
Definition at line 1122 of file lustre_dlm.h.
Referenced by ldlm_cli_cancel(), ldlm_handle_cp_callback(), ldlm_lock_match(), ll_layout_refresh_locked(), mdt_check_resent_lock(), mdt_intent_lock_replace(), and osc_lock_init().
#define LDLM_DEFAULT_LRU_SIZE (100 * num_online_cpus())
Definition at line 65 of file lustre_dlm.h.
Referenced by ldlm_namespace_new().
#define LDLM_DEFAULT_MAX_ALIVE (cfs_time_seconds(3900))
Definition at line 66 of file lustre_dlm.h.
Referenced by ldlm_namespace_new().
#define LDLM_DEFAULT_PARALLEL_AST_LIMIT 1024
Definition at line 68 of file lustre_dlm.h.
Referenced by ldlm_namespace_new().
#define LDLM_ERROR (lock, fmt, a...) ((void)0)
Definition at line 1169 of file lustre_dlm.h.
Referenced by ldlm_cancel_resource_local(), ldlm_cli_cancel_local(), ldlm_cli_enqueue_fini(), ldlm_cli_enqueue_local(), ldlm_expired_completion_wait(), ldlm_fill_lvb(), ldlm_handle_cp_callback(), ldlm_lock_cancel(), ldlm_lock_convert(), ldlm_lock_destroy_internal(), ll_md_blocking_ast(), and search_granted_lock().
#define LDLM_FL_ALL_FLAGS_MASK 0x00FFFFFFC08F932FULL
l_flags bits marked as "all_flags" bits
Definition at line 29 of file lustre_dlm_flags.h.
#define LDLM_FL_AST_DISCARD_DATA 0x0000000080000000ULL
These are flags that are mapped into the flags and ASTs of blocking locks Add FL_DISCARD to blocking ASTs.
Definition at line 151 of file lustre_dlm_flags.h.
Referenced by ldlm_lock_enqueue(), ofd_destroy_by_fid(), ofd_punch_hdl(), and osc_enq2ldlm_flags().
#define LDLM_FL_AST_MASK
Value:
(LDLM_FL_FLOCK_DEADLOCK         |\
                                         LDLM_FL_AST_DISCARD_DATA)
l_flags bits marked as "ast" bits
Definition at line 366 of file lustre_dlm_flags.h.
Referenced by ldlm_callback_handler().
#define LDLM_FL_AST_SENT 0x0000000000000020ULL
blocking or cancel packet was queued for sending.
Definition at line 62 of file lustre_dlm_flags.h.
Referenced by ldlm_cli_enqueue_fini(), ldlm_flock_cancel_on_deadlock(), ldlm_handle_cp_callback(), ofd_prolong_extent_locks(), and ofd_prolong_one_lock().
#define LDLM_FL_ATOMIC_CB 0x0000200000000000ULL
optimization hint: LDLM can run blocking callback from current context w/o involving separate thread.
in order to decrease cs rate
Definition at line 258 of file lustre_dlm_flags.h.
Referenced by __lfsck_ibits_lock(), failed_lock_cleanup(), ldlm_cli_enqueue_local(), lod_object_lock(), mdt_object_local_lock(), mdt_pdir_hash_lock(), mdt_rename_lock(), and mgs_revoke_lock().
#define LDLM_FL_BL_AST 0x0000400000000000ULL
It may happen that a client initiates two operations, e.g.
unlink and mkdir, such that the server sends a blocking AST for conflicting locks to this client for the first operation, whereas the second operation has canceled this lock and is waiting for rpc_lock which is taken by the first operation. LDLM_FL_BL_AST is set by ldlm_callback_handler() in the lock to prevent the Early Lock Cancel (ELC) code from cancelling it.
Definition at line 270 of file lustre_dlm_flags.h.
Referenced by ldlm_cli_cancel_list_local(), ldlm_cli_cancel_local(), ldlm_cli_enqueue_fini(), and ldlm_handle_cp_callback().
#define LDLM_FL_BL_DONE 0x0000800000000000ULL
Set by ldlm_cancel_callback() when lock cache is dropped to let ldlm_callback_handler() return EINVAL to the server.
It is used when ELC RPC is already prepared and is waiting for rpc_lock, too late to send a separate CANCEL RPC.
Definition at line 280 of file lustre_dlm_flags.h.
#define LDLM_FL_BLOCK_CONV 0x0000000000000004ULL
Server placed lock on conv list, or a recovering client wants the lock added to the conv list, no questions asked.
Definition at line 48 of file lustre_dlm_flags.h.
Referenced by ldlm_lock_convert(), ldlm_lock_enqueue(), and replay_one_lock().
#define LDLM_FL_BLOCK_GRANTED 0x0000000000000002ULL
Server placed lock on granted list, or a recovering client wants the lock added to the granted list, no questions asked.
Definition at line 40 of file lustre_dlm_flags.h.
Referenced by ldlm_lock_convert(), ldlm_lock_enqueue(), ldlm_lock_match(), ldlm_process_flock_lock(), ll_have_md_lock(), ll_md_close(), ll_take_md_lock(), mdc_finish_intent_lock(), mdc_revalidate_lock(), osc_dlmlock_at_pgoff(), osc_enqueue_base(), osc_lock_init(), osc_object_fiemap(), and replay_one_lock().
#define LDLM_FL_BLOCK_NOWAIT 0x0000000000040000ULL
Server told not to wait if blocked.
For AGL, OST will not send glimpse callback.
Definition at line 108 of file lustre_dlm_flags.h.
Referenced by ldlm_process_flock_lock(), ll_file_flock(), mdt_object_local_lock(), ofd_intent_policy(), osc_enq2ldlm_flags(), osc_lock_init(), and osp_md_object_lock().
#define LDLM_FL_BLOCK_WAIT 0x0000000000000008ULL
Server placed lock on wait list, or a recovering client wants the lock added to the wait list, no questions asked.
Definition at line 56 of file lustre_dlm_flags.h.
Referenced by ldlm_lock_enqueue(), and replay_one_lock().
#define LDLM_FL_BLOCKED_MASK
Value:
(LDLM_FL_BLOCK_GRANTED          |\
                                         LDLM_FL_BLOCK_CONV             |\
                                         LDLM_FL_BLOCK_WAIT)
l_flags bits marked as "blocked" bits
Definition at line 370 of file lustre_dlm_flags.h.
Referenced by ldlm_completion_ast(), ldlm_completion_ast_async(), ldlm_flock_completion_ast(), ldlm_lock_enqueue(), mdc_finish_enqueue(), and mgs_completion_ast_generic().
#define LDLM_FL_CANCEL 0x0000001000000000ULL
cancellation callback already run
Definition at line 185 of file lustre_dlm_flags.h.
#define LDLM_FL_CANCEL_ON_BLOCK 0x0000000000800000ULL
Immediatelly cancel such locks when they block some other locks.
Send cancel notification to original lock holder, but expect no reply. This is for clients (like liblustre) that cannot be expected to reliably response to blocking AST.
Definition at line 127 of file lustre_dlm_flags.h.
Referenced by ldlm_cli_cancel_local(), and ldlm_flock_cancel_on_deadlock().
#define LDLM_FL_CANCELING 0x0000008000000000ULL
lock cancel has already been sent
Definition at line 203 of file lustre_dlm_flags.h.
Referenced by ldlm_cancel_resource_local(), ldlm_chain_lock_for_replay(), ldlm_cli_cancel_local(), and ldlm_prepare_lru_list().
#define LDLM_FL_CBPENDING 0x0000000400000000ULL
this lock is being destroyed
Definition at line 173 of file lustre_dlm_flags.h.
Referenced by failed_lock_cleanup(), ldlm_cancel_resource_local(), ldlm_cli_enqueue_fini(), ldlm_flock_completion_ast(), ldlm_flock_destroy(), ldlm_handle_cp_callback(), ldlm_prepare_lru_list(), ll_have_md_lock(), lock_matches(), and osc_dlmlock_at_pgoff().
#define LDLM_FL_CLEANED 0x0000100000000000ULL
cleanup_resource has already handled the lock
Definition at line 250 of file lustre_dlm_flags.h.
#define LDLM_FL_COS_ENABLED 0x0200000000000000ULL
Flag whether Commit-on-Sharing is enabled, if LDLM_FL_COS_INCOMPAT is set this flag may not be set because once the former is set this flag won't be checked, and for cross-MDT lock COS_INCOMPAT is always set but ast handle is in ldlm context which doesn't know whether COS is enabled or not.
Definition at line 361 of file lustre_dlm_flags.h.
Referenced by ldlm_lock_enqueue(), and mdt_object_local_lock().
#define LDLM_FL_COS_INCOMPAT 0x0000000001000000ULL
Flag whether a lock is enqueued from a distributed transaction, and the requesting lock mode is PW/EX, if so, it will check compatibility with COS locks, and different from original COS semantic, transactions from the same client is also treated as lock conflict.
Definition at line 136 of file lustre_dlm_flags.h.
Referenced by ldlm_lock_enqueue(), lod_object_lock(), mdt_object_local_lock(), mdt_pdir_hash_lock(), and osp_md_object_lock().
#define LDLM_FL_CP_REQD 0x0000080000000000ULL
completion AST to be executed
Definition at line 244 of file lustre_dlm_flags.h.
#define LDLM_FL_DENY_ON_CONTENTION 0x0000000040000000ULL
measure lock contention and return -EUSERS if locking contention is high
Definition at line 143 of file lustre_dlm_flags.h.
Referenced by osc_lock_init().
#define LDLM_FL_DESTROYED 0x0004000000000000ULL
Set for locks that were removed from class hash table and will be destroyed when last reference to them is released.
Set by ldlm_lock_destroy_internal().
Protected by lock and resource locks.
Definition at line 309 of file lustre_dlm_flags.h.
Referenced by ldlm_lock_match(), and ofd_prolong_one_lock().
#define LDLM_FL_DISCARD_DATA 0x0000000000010000ULL
discard (no writeback) on cancel
Definition at line 94 of file lustre_dlm_flags.h.
Referenced by osc_destroy().
#define LDLM_FL_EXCL 0x0080000000000000ULL
Flag whether this lock can be reused.
Used by exclusive open.
Definition at line 349 of file lustre_dlm_flags.h.
Referenced by ldlm_cli_enqueue(), and ll_lease_open().
#define LDLM_FL_FAIL_LOC 0x0000000100000000ULL
Used for marking lock as a target for -EINTR while cp_ast sleep emulation + race with upcoming bl_ast.
Definition at line 159 of file lustre_dlm_flags.h.
Referenced by cleanup_resource(), and ldlm_flock_completion_ast().
#define LDLM_FL_FAIL_NOTIFIED 0x0002000000000000ULL
Set for locks that failed and where the server has been notified.
Protected by lock and resource locks.
Definition at line 298 of file lustre_dlm_flags.h.
Referenced by ldlm_lock_fail_match_locked(), and ldlm_lock_match().
#define LDLM_FL_FAILED 0x0000004000000000ULL
don't run the cancel callback under ldlm_cli_cancel_unused
Definition at line 197 of file lustre_dlm_flags.h.
Referenced by cleanup_resource(), failed_lock_cleanup(), ldlm_chain_lock_for_replay(), and ldlm_flock_completion_ast().
#define LDLM_FL_FLOCK_DEADLOCK 0x0000000000008000ULL
flock deadlock detected
Definition at line 88 of file lustre_dlm_flags.h.
Referenced by ldlm_flock_cancel_on_deadlock(), and ldlm_flock_completion_ast().
#define LDLM_FL_GONE_MASK
Value:
(LDLM_FL_DESTROYED              |\
                                         LDLM_FL_FAILED)
l_flags bits marked as "gone" bits
Definition at line 375 of file lustre_dlm_flags.h.
#define LDLM_FL_HAS_INTENT 0x0000000000001000ULL
lock request has intent
Definition at line 82 of file lustre_dlm_flags.h.
Referenced by ldlm_lock_enqueue(), mdc_enqueue(), mdc_intent_getattr_async(), mdc_intent_getattr_async_interpret(), osc_enq2ldlm_flags(), osc_enqueue_base(), osc_enqueue_fini(), osc_lock_init(), qsd_intent_interpret(), and qsd_intent_lock().
#define LDLM_FL_INHERIT_MASK
Value:
(LDLM_FL_CANCEL_ON_BLOCK        |\
                                         LDLM_FL_NO_TIMEOUT             |\
                                         LDLM_FL_TEST_LOCK)
l_flags bits marked as "inherit" bits
Definition at line 382 of file lustre_dlm_flags.h.
Referenced by ldlm_cli_enqueue_fini().
#define LDLM_FL_INTENT_ONLY 0x0000000000000200ULL
Don't grant lock, just do intent.
Definition at line 76 of file lustre_dlm_flags.h.
Referenced by ldlm_lock_enqueue(), mdc_finish_enqueue(), and mdt_intent_lock_replace().
#define LDLM_FL_KMS_IGNORE 0x0000040000000000ULL
A lock contributes to the known minimum size (KMS) calculation until it has finished the part of its cancelation that performs write back on its dirty pages.
It can remain on the granted list during this whole time. Threads racing to update the KMS after performing their writeback need to know to exclude each other's locks from the calculation as they walk the granted list.
Definition at line 238 of file lustre_dlm_flags.h.
#define LDLM_FL_LOCAL 0x0000010000000000ULL
local lock (ie, no srv/cli split)
Definition at line 209 of file lustre_dlm_flags.h.
Referenced by mdt_intent_lock_replace().
#define LDLM_FL_LOCAL_ONLY 0x0000002000000000ULL
whatever it might mean -- never transmitted?
Definition at line 191 of file lustre_dlm_flags.h.
Referenced by __ldlm_namespace_free(), cleanup_resource(), failed_lock_cleanup(), ldlm_cli_cancel(), ldlm_cli_cancel_list_local(), ldlm_cli_cancel_local(), ldlm_flock_destroy(), lock_matches(), lwp_import_event(), mdc_import_event(), mdt_object_local_lock(), mdt_pdir_hash_lock(), mdt_rename_lock(), mgc_import_event(), osc_import_event(), and osp_import_event().
#define LDLM_FL_LOCK_CHANGED 0x0000000000000001ULL
extent, mode, or resource changed
Definition at line 32 of file lustre_dlm_flags.h.
Referenced by ldlm_cli_enqueue_fini(), ldlm_lock_enqueue(), and ldlm_process_flock_lock().
#define LDLM_FL_LVB_READY 0x0000020000000000ULL
XXX FIXME: This is being added to b_size as a low-risk fix to the fact that the LVB filling happens _after_ the lock has been granted, so another thread can match it before the LVB has been updated.
As a dirty hack, we set LDLM_FL_LVB_READY only after we've done the LVB poop. this is only needed on LOV/OSC now, where LVB is actually used and callers must set it in input flags.
The proper fix is to do the granting inside of the completion AST, which can be replaced with a LVB-aware wrapping function for OSC locks. That change is pretty high-risk, though, and would need a lot more testing.
Definition at line 226 of file lustre_dlm_flags.h.
Referenced by ldlm_lock_match(), osc_enqueue_base(), osc_enqueue_fini(), osc_lock_cancel(), osc_lock_granted(), osc_lock_upcall(), and osc_object_fiemap().
#define LDLM_FL_MATCH_LOCK 0x0000000000100000ULL
match lock only
Definition at line 120 of file lustre_dlm_flags.h.
Referenced by osc_enq2ldlm_flags(), and osc_enqueue_base().
#define LDLM_FL_NO_LRU 0x0001000000000000ULL
Don't put lock into the LRU list, so that it is not canceled due to aging.
Used by MGC locks, they are cancelled only at unmount or by callback.
Definition at line 289 of file lustre_dlm_flags.h.
Referenced by ldlm_cli_enqueue(), ll_lease_open(), mgc_process_log(), osp_md_object_lock(), and qsd_intent_lock().
#define LDLM_FL_NO_TIMEOUT 0x0000000000020000ULL
Blocked by group lock - wait indefinitely.
Definition at line 100 of file lustre_dlm_flags.h.
Referenced by ldlm_lock_enqueue().
#define LDLM_FL_NS_SRV 0x0040000000000000ULL
Flag whether this is a server namespace lock.
Definition at line 343 of file lustre_dlm_flags.h.
#define LDLM_FL_REPLAY 0x0000000000000100ULL
Lock is being replayed.
This could probably be implied by the fact that one of BLOCK_{GRANTED,CONV,WAIT} is set, but that is pretty dangerous.
Definition at line 70 of file lustre_dlm_flags.h.
Referenced by ldlm_cli_enqueue(), ldlm_cli_enqueue_fini(), ldlm_cli_enqueue_local(), ldlm_lock_enqueue(), and replay_one_lock().
#define LDLM_FL_RES_LOCKED 0x0010000000000000ULL
It's set in lock_res_and_lock() and unset in unlock_res_and_lock().
NB: compared with check_res_locked(), checking this bit is cheaper. Also, spin_is_locked() is deprecated for kernel code; one reason is because it works only for SMP so user needs to add extra macros like LASSERT_SPIN_LOCKED for uniprocessor kernels.
Definition at line 327 of file lustre_dlm_flags.h.
#define LDLM_FL_RESENT 0x0100000000000000ULL
Flag whether a lock is found on server for re-sent RPC.
Definition at line 355 of file lustre_dlm_flags.h.
Referenced by ldlm_lock_enqueue(), mdt_intent_fixup_resent(), mdt_intent_lock_replace(), and ofd_intent_policy().
#define LDLM_FL_SERVER_LOCK 0x0008000000000000ULL
flag whether this is a server namespace lock
Definition at line 315 of file lustre_dlm_flags.h.
#define LDLM_FL_SKIPPED 0x0000000200000000ULL
Used while processing the unused list to know that we have already handled this lock and decided to skip it.
Definition at line 167 of file lustre_dlm_flags.h.
#define LDLM_FL_SRV_ENQ_MASK
Value:
(LDLM_FL_LOCK_CHANGED           |\
                                 LDLM_FL_BLOCKED_MASK           |\
                                 LDLM_FL_NO_TIMEOUT)
flags returned in parameter on ldlm_lock_enqueue, to be re-constructed on re-send
Definition at line 388 of file lustre_dlm_flags.h.
#define LDLM_FL_TEST_LOCK 0x0000000000080000ULL
return blocking lock
Definition at line 114 of file lustre_dlm_flags.h.
Referenced by ldlm_flock_completion_ast(), ldlm_lock_enqueue(), ldlm_lock_match(), ldlm_process_flock_lock(), ll_file_flock(), ll_have_md_lock(), ll_md_close(), lock_matches(), osc_dlmlock_at_pgoff(), osc_enq2ldlm_flags(), osc_enqueue_base(), osc_lock_enqueue(), and osc_match_base().
#define LDLM_FL_WAIT_NOREPROC 0x0000000800000000ULL
not a real flag, not saved in lock
Definition at line 179 of file lustre_dlm_flags.h.
Referenced by ldlm_cli_convert(), ldlm_completion_ast(), ldlm_completion_ast_async(), ldlm_flock_completion_ast(), ldlm_flock_destroy(), ldlm_lock_match(), and ldlm_process_flock_lock().
#define LDLM_FL_WAITED 0x0020000000000000ULL
It's set once we call ldlm_add_waiting_lock_res_locked() to start the lock-timeout timer and it will never be reset.
Protected by lock and resource locks.
Definition at line 337 of file lustre_dlm_flags.h.
#define LDLM_GID_ANY ((__u64)-1)
LDLM_GID_ANY is used to match any group id in ldlm_lock_match().
Definition at line 655 of file lustre_dlm.h.
Referenced by lock_matches(), and osc_dlmlock_at_pgoff().
#define LDLM_GL_WORK_NOFREE 0x1
The ldlm_glimpse_work is allocated on the stack and should not be freed.
Definition at line 588 of file lustre_dlm.h.
Referenced by ldlm_work_gl_ast_lock(), and ofd_intent_policy().
#define LDLM_HAVE_MASK (_l, _m) (((_l)->l_flags & LDLM_FL_##_m##_MASK) != 0)
multi-bit test: are any of mask bits set?
Definition at line 396 of file lustre_dlm_flags.h.
Referenced by ldlm_revalidate_lock_handle(), and lock_matches().
#define ldlm_is_ast_discard_data (_l) LDLM_TEST_FLAG((_l), 1ULL << 31)
Definition at line 152 of file lustre_dlm_flags.h.
Referenced by ldlm_add_bl_work_item().
#define ldlm_is_ast_sent (_l) LDLM_TEST_FLAG((_l), 1ULL << 5)
Definition at line 63 of file lustre_dlm_flags.h.
Referenced by ldlm_add_bl_work_item(), ldlm_flock_cancel_on_deadlock(), ldlm_work_bl_ast_lock(), and qmt_dqacq().
#define ldlm_is_atomic_cb (_l) LDLM_TEST_FLAG((_l), 1ULL << 45)
Definition at line 259 of file lustre_dlm_flags.h.
Referenced by ldlm_lock_decref_internal(), and mdt_remote_blocking_ast().
#define ldlm_is_bl_ast (_l) LDLM_TEST_FLAG((_l), 1ULL << 46)
Definition at line 271 of file lustre_dlm_flags.h.
Referenced by ldlm_cancel_resource_local(), ldlm_cli_cancel_local(), ldlm_lock_decref_internal(), and ldlm_prepare_lru_list().
#define ldlm_is_bl_done (_l) LDLM_TEST_FLAG((_l), 1ULL << 47)
Definition at line 281 of file lustre_dlm_flags.h.
Referenced by is_bl_done(), ldlm_callback_handler(), and ldlm_cancel_callback().
#define ldlm_is_block_conv (_l) LDLM_TEST_FLAG((_l), 1ULL << 2)
Definition at line 49 of file lustre_dlm_flags.h.
#define ldlm_is_block_granted (_l) LDLM_TEST_FLAG((_l), 1ULL << 1)
Definition at line 41 of file lustre_dlm_flags.h.
#define ldlm_is_block_nowait (_l) LDLM_TEST_FLAG((_l), 1ULL << 18)
Definition at line 109 of file lustre_dlm_flags.h.
#define ldlm_is_block_wait (_l) LDLM_TEST_FLAG((_l), 1ULL << 3)
Definition at line 57 of file lustre_dlm_flags.h.
#define ldlm_is_cancel (_l) LDLM_TEST_FLAG((_l), 1ULL << 36)
Definition at line 186 of file lustre_dlm_flags.h.
Referenced by is_granted_or_cancelled(), ldlm_cancel_callback(), ll_file_ioctl(), ll_lease_close(), mdt_close_swap_layouts(), mdt_hsm_release(), and mdt_reint_migrate_internal().
#define ldlm_is_cancel_on_block (_l) LDLM_TEST_FLAG((_l), 1ULL << 23)
Definition at line 128 of file lustre_dlm_flags.h.
Referenced by ldlm_callback_handler(), ldlm_handle_bl_callback(), and replay_one_lock().
#define ldlm_is_canceling (_l) LDLM_TEST_FLAG((_l), 1ULL << 39)
Definition at line 204 of file lustre_dlm_flags.h.
Referenced by ldlm_callback_handler(), ldlm_cancel_resource_local(), ldlm_cli_cancel(), ldlm_prepare_lru_list(), ll_md_blocking_ast(), and replay_one_lock().
#define ldlm_is_cbpending (_l) LDLM_TEST_FLAG((_l), 1ULL << 34)
Definition at line 174 of file lustre_dlm_flags.h.
Referenced by ldlm_lock_addref_try(), ldlm_lock_decref_internal(), ldlm_revalidate_lock_handle(), lock_matches(), tgt_blocking_ast(), tgt_discard_slc_lock(), and tgt_save_slc_lock().
#define ldlm_is_cleaned (_l) LDLM_TEST_FLAG((_l), 1ULL << 44)
Definition at line 251 of file lustre_dlm_flags.h.
Referenced by cleanup_resource().
#define ldlm_is_cos_enabled (_l) LDLM_TEST_FLAG((_l), 1ULL << 57)
Definition at line 362 of file lustre_dlm_flags.h.
#define ldlm_is_cos_incompat (_l) LDLM_TEST_FLAG((_l), 1ULL << 24)
Definition at line 137 of file lustre_dlm_flags.h.
Referenced by mdt_blocking_ast().
#define ldlm_is_cp_reqd (_l) LDLM_TEST_FLAG((_l), 1ULL << 43)
Definition at line 245 of file lustre_dlm_flags.h.
Referenced by is_granted_or_cancelled(), ldlm_add_cp_work_item(), and ldlm_work_cp_ast_lock().
#define ldlm_is_deny_on_contention (_l) LDLM_TEST_FLAG((_l), 1ULL << 30)
Definition at line 144 of file lustre_dlm_flags.h.
#define ldlm_is_destroyed (_l) LDLM_TEST_FLAG((_l), 1ULL << 50)
Definition at line 310 of file lustre_dlm_flags.h.
Referenced by __ldlm_handle2lock(), failed_lock_cleanup(), ldlm_completion_tail(), ldlm_flock_completion_ast(), ldlm_granted_list_add_lock(), ldlm_handle_cp_callback(), ldlm_lock_destroy_internal(), ldlm_lock_put(), ldlm_resource_add_lock(), ldlm_resource_insert_lock_after(), and osc_lock_invariant().
#define ldlm_is_discard_data (_l) LDLM_TEST_FLAG((_l), 1ULL << 16)
Definition at line 95 of file lustre_dlm_flags.h.
Referenced by __ldlm_bl_to_thread(), and osc_dlm_blocking_ast0().
#define ldlm_is_excl (_l) LDLM_TEST_FLAG((_l), 1ULL << 55)
Definition at line 350 of file lustre_dlm_flags.h.
Referenced by lock_matches().
#define ldlm_is_fail_loc (_l) LDLM_TEST_FLAG((_l), 1ULL << 32)
Definition at line 160 of file lustre_dlm_flags.h.
Referenced by ldlm_callback_handler(), and ldlm_lock_decref_internal().
#define ldlm_is_fail_notified (_l) LDLM_TEST_FLAG((_l), 1ULL << 49)
Definition at line 299 of file lustre_dlm_flags.h.
#define ldlm_is_failed (_l) LDLM_TEST_FLAG((_l), 1ULL << 38)
Definition at line 198 of file lustre_dlm_flags.h.
Referenced by failed_lock_cleanup(), is_granted_or_cancelled(), ldlm_callback_handler(), ldlm_completion_tail(), ldlm_flock_completion_ast(), and osc_extent_sanity_check0().
#define ldlm_is_flock_deadlock (_l) LDLM_TEST_FLAG((_l), 1ULL << 15)
Definition at line 89 of file lustre_dlm_flags.h.
Referenced by ldlm_flock_completion_ast(), and ldlm_grant_lock().
#define ldlm_is_has_intent (_l) LDLM_TEST_FLAG((_l), 1ULL << 12)
Definition at line 83 of file lustre_dlm_flags.h.
#define ldlm_is_intent_only (_l) LDLM_TEST_FLAG((_l), 1ULL << 9)
Definition at line 77 of file lustre_dlm_flags.h.
#define ldlm_is_kms_ignore (_l) LDLM_TEST_FLAG((_l), 1ULL << 42)
Definition at line 239 of file lustre_dlm_flags.h.
Referenced by ldlm_extent_shift_kms().
#define ldlm_is_local (_l) LDLM_TEST_FLAG((_l), 1ULL << 40)
Definition at line 210 of file lustre_dlm_flags.h.
Referenced by ldlm_lock_decref_internal(), and lock_matches().
#define ldlm_is_local_only (_l) LDLM_TEST_FLAG((_l), 1ULL << 37)
Definition at line 192 of file lustre_dlm_flags.h.
Referenced by qsd_glb_blocking_ast(), and qsd_id_blocking_ast().
#define ldlm_is_lock_changed (_l) LDLM_TEST_FLAG((_l), 1ULL << 0)
Definition at line 33 of file lustre_dlm_flags.h.
#define ldlm_is_lvb_ready (_l) LDLM_TEST_FLAG((_l), 1ULL << 41)
Definition at line 227 of file lustre_dlm_flags.h.
Referenced by ldlm_lock_match(), ll_layout_fetch(), and ll_layout_lock_set().
#define ldlm_is_no_lru (_l) LDLM_TEST_FLAG((_l), 1ULL << 48)
Definition at line 290 of file lustre_dlm_flags.h.
Referenced by ldlm_lock_decref_internal().
#define ldlm_is_no_timeout (_l) LDLM_TEST_FLAG((_l), 1ULL << 17)
Definition at line 101 of file lustre_dlm_flags.h.
Referenced by ldlm_completion_ast().
#define ldlm_is_ns_srv (_l) LDLM_TEST_FLAG((_l), 1ULL << 54)
Definition at line 344 of file lustre_dlm_flags.h.
Referenced by ldlm_lock_decref_internal(), ldlm_lock_remove_from_lru_check(), ldlm_lock_touch_in_lru(), lock_res_and_lock(), and unlock_res_and_lock().
#define ldlm_is_replay (_l) LDLM_TEST_FLAG((_l), 1ULL << 8)
Definition at line 71 of file lustre_dlm_flags.h.
#define ldlm_is_res_locked (_l) LDLM_TEST_FLAG((_l), 1ULL << 52)
Definition at line 328 of file lustre_dlm_flags.h.
#define ldlm_is_server_lock (_l) LDLM_TEST_FLAG((_l), 1ULL << 51)
Definition at line 316 of file lustre_dlm_flags.h.
#define ldlm_is_skipped (_l) LDLM_TEST_FLAG((_l), 1ULL << 33)
Definition at line 168 of file lustre_dlm_flags.h.
Referenced by ldlm_prepare_lru_list().
#define ldlm_is_test_lock (_l) LDLM_TEST_FLAG((_l), 1ULL << 19)
Definition at line 115 of file lustre_dlm_flags.h.
Referenced by ldlm_flock_completion_ast(), and ldlm_grant_lock().
#define ldlm_is_wait_noreproc (_l) LDLM_TEST_FLAG((_l), 1ULL << 35)
Definition at line 180 of file lustre_dlm_flags.h.
#define ldlm_is_waited (_l) LDLM_TEST_FLAG((_l), 1ULL << 53)
Definition at line 338 of file lustre_dlm_flags.h.
Referenced by ldlm_lock_cancel().
#define LDLM_ITER_CONTINUE 1
Return values for lock iterators.
Also used during deciding of lock grants and cancellations.
Definition at line 1180 of file lustre_dlm.h.
Referenced by ldlm_chain_lock_for_replay(), ldlm_process_flock_lock(), ldlm_reprocess_all(), ldlm_resource_foreach(), ofd_intent_policy(), osc_object_ast_clear(), and reprocess_one_queue().
#define LDLM_ITER_STOP 2
Definition at line 1181 of file lustre_dlm.h.
Referenced by ldlm_bl_thread_blwi(), ldlm_bl_thread_main(), ldlm_lock_convert(), ldlm_process_flock_lock(), ldlm_reprocess_res(), ldlm_res_iter_helper(), and ldlm_resource_foreach().
#define LDLM_LOCK_GET (lock)
Value:
({                                              \
        ldlm_lock_get(lock);                    \
        /*LDLM_DEBUG((lock), "get");*/          \
        lock;                                   \
})
Definition at line 1344 of file lustre_dlm.h.
Referenced by cleanup_resource(), ldlm_add_bl_work_item(), ldlm_add_cp_work_item(), ldlm_cancel_locks_for_export_cb(), ldlm_cancel_resource_local(), ldlm_chain_lock_for_replay(), ldlm_export_cancel_blocked_locks(), ldlm_export_flock_get(), ldlm_export_lock_get(), ldlm_lock_addref_internal_nolock(), ldlm_lock_decref_internal(), ldlm_prepare_lru_list(), lock_handle_addref(), lock_matches(), ofd_intent_cb(), ofd_intent_policy(), osc_extent_find(), and qmt_glimpse_lock().
#define ldlm_lock_list_put (head, member, count)
Value:
({                                                              \
        struct ldlm_lock *_lock, *_next;                        \
        int c = count;                                          \
        list_for_each_entry_safe(_lock, _next, head, member) {  \
                if (c-- == 0)                                   \
                        break;                                  \
                list_del_init(&_lock->member);                  \
                LDLM_LOCK_RELEASE(_lock);                       \
        }                                                       \
        LASSERT(c <= 0);                                        \
})
Definition at line 1351 of file lustre_dlm.h.
Referenced by ldlm_cli_cancel_list(), ldlm_prep_elc_req(), mdc_create(), mdc_intent_open_pack(), mdc_ioc_swap_layouts(), mdc_link(), mdc_rename(), mdc_setattr(), mdc_unlink(), and osc_destroy().
#define LDLM_LOCK_PUT (lock)
Value:
do {                                            \
        LDLM_LOCK_REF_DEL(lock);                \
        /*LDLM_DEBUG((lock), "put");*/          \
        ldlm_lock_put(lock);                    \
} while (0)
Release a temporary lock reference obtained by ldlm_handle2lock() or __ldlm_handle2lock().
Definition at line 1327 of file lustre_dlm.h.
Referenced by __ldlm_handle2lock(), check_and_discard_cb(), ldlm_cli_convert(), ldlm_cli_convert_local(), ldlm_cli_enqueue_fini(), ldlm_lock_addref(), ldlm_lock_addref_try(), ldlm_lock_decref(), ldlm_lock_decref_and_cancel(), ldlm_lock_dump_handle(), ldlm_lock_match(), ldlm_lock_set_data(), ldlm_revalidate_lock_handle(), ll_file_ioctl(), ll_have_md_lock(), ll_layout_lock_set(), ll_lease_close(), ll_prep_inode(), mdc_finish_enqueue(), mdc_finish_intent_lock(), mdc_intent_close_pack(), mdc_set_lock_data(), mdt_check_resent_lock(), mdt_close_swap_layouts(), mdt_getattr_name_lock(), mdt_hsm_release(), mdt_lock_objects_in_linkea(), mdt_reint_migrate_internal(), mdt_save_lock(), ofd_prolong_extent_locks(), osc_enqueue_base(), osc_enqueue_interpret(), osc_extent_put(), osc_handle_ptr(), osc_lock_upcall_agl(), osc_match_base(), osc_read_ahead_release(), osc_req_attr_set(), qmt_dqacq(), qmt_intent_policy(), qsd_id_lock_match(), qsd_intent_lock(), qsd_ready(), replay_lock_interpret(), tgt_cancel_slc_locks(), tgt_discard_slc_lock(), and tgt_save_slc_lock().
#define LDLM_LOCK_REF_DEL (lock) lu_ref_del(&lock->l_reference, "handle", current)
Definition at line 1278 of file lustre_dlm.h.
Referenced by ldlm_handle2lock_long().
#define LDLM_LOCK_RELEASE (lock)
Value:
do {                                            \
        /*LDLM_DEBUG((lock), "put");*/          \
        ldlm_lock_put(lock);                    \
} while (0)
Release a lock reference obtained by some other means (see LDLM_LOCK_PUT()).
Definition at line 1338 of file lustre_dlm.h.
Referenced by cleanup_resource(), ldlm_callback_handler(), ldlm_cancel_locks_for_export_cb(), ldlm_cli_cancel(), ldlm_cli_cancel_list_local(), ldlm_cli_enqueue(), ldlm_cli_enqueue_fini(), ldlm_cli_enqueue_local(), ldlm_export_cancel_blocked_locks(), ldlm_export_flock_put(), ldlm_export_lock_put(), ldlm_handle_bl_callback(), ldlm_handle_cp_callback(), ldlm_handle_gl_callback(), ldlm_lock_create(), ldlm_lock_decref_internal_nolock(), ldlm_lock_destroy(), ldlm_lock_destroy_nolock(), ldlm_lock_enqueue(), ldlm_lock_match(), ldlm_prepare_lru_list(), ldlm_process_flock_lock(), ldlm_replay_locks(), ldlm_work_bl_ast_lock(), ldlm_work_cp_ast_lock(), ldlm_work_gl_ast_lock(), ldlm_work_revoke_ast_lock(), mdt_intent_lock_replace(), ofd_intent_cb(), ofd_intent_policy(), osc_lock_detach(), and qmt_glimpse_lock().
#define LDLM_POOL_CLI_DEF_RECALC_PERIOD (10)
Default recalc period for client side pools in sec.
Definition at line 228 of file lustre_dlm.h.
#define LDLM_POOL_SRV_DEF_RECALC_PERIOD (1)
Default recalc period for server side pools in sec.
Definition at line 225 of file lustre_dlm.h.
#define LDLM_POOLS_MODEST_MARGIN_SHIFT (4)
~6% margin for modest pools.
See ldlm_pool.c for details.
Definition at line 222 of file lustre_dlm.h.
#define LDLM_POOLS_THREAD_PERIOD (1)
One second for pools thread check interval.
Each pool has own period.
Definition at line 219 of file lustre_dlm.h.
#define LDLM_RESOURCE_ADDREF (res)
Value:
do {                                  \
        lu_ref_add_atomic(&(res)->lr_reference, __FUNCTION__, current);  \
} while (0)
Definition at line 1435 of file lustre_dlm.h.
Referenced by ldlm_cli_cancel_unused_resource(), ldlm_lock_match(), ldlm_resource_iterate(), mdc_resource_get_unused(), and osc_resource_get_unused().
#define LDLM_RESOURCE_DELREF (res)
Value:
do {                                  \
        lu_ref_del(&(res)->lr_reference, __FUNCTION__, current);  \
} while (0)
Definition at line 1439 of file lustre_dlm.h.
Referenced by ldlm_cli_cancel_unused_resource(), ldlm_lock_match(), ldlm_resource_iterate(), mdc_resource_get_unused(), and osc_resource_get_unused().
#define ldlm_set_ast_discard_data (_l) LDLM_SET_FLAG((_l), 1ULL << 31)
Definition at line 153 of file lustre_dlm_flags.h.
Referenced by ldlm_lock_enqueue().
#define ldlm_set_ast_sent (_l) LDLM_SET_FLAG((_l), 1ULL << 5)
Definition at line 64 of file lustre_dlm_flags.h.
Referenced by ldlm_add_bl_work_item().
#define ldlm_set_atomic_cb (_l) LDLM_SET_FLAG((_l), 1ULL << 45)
Definition at line 260 of file lustre_dlm_flags.h.
Referenced by ldlm_cli_enqueue_local(), and mdt_lock_objects_in_linkea().
#define ldlm_set_bl_ast (_l) LDLM_SET_FLAG((_l), 1ULL << 46)
Definition at line 272 of file lustre_dlm_flags.h.
Referenced by ldlm_callback_handler().
#define ldlm_set_bl_done (_l) LDLM_SET_FLAG((_l), 1ULL << 47)
Definition at line 282 of file lustre_dlm_flags.h.
Referenced by ldlm_cancel_callback().
#define ldlm_set_block_conv (_l) LDLM_SET_FLAG((_l), 1ULL << 2)
Definition at line 50 of file lustre_dlm_flags.h.
#define ldlm_set_block_granted (_l) LDLM_SET_FLAG((_l), 1ULL << 1)
Definition at line 42 of file lustre_dlm_flags.h.
#define ldlm_set_block_nowait (_l) LDLM_SET_FLAG((_l), 1ULL << 18)
Definition at line 110 of file lustre_dlm_flags.h.
#define ldlm_set_block_wait (_l) LDLM_SET_FLAG((_l), 1ULL << 3)
Definition at line 58 of file lustre_dlm_flags.h.
#define ldlm_set_cancel (_l) LDLM_SET_FLAG((_l), 1ULL << 36)
Definition at line 187 of file lustre_dlm_flags.h.
Referenced by ldlm_cancel_callback(), and ldlm_handle_bl_callback().
#define ldlm_set_cancel_on_block (_l) LDLM_SET_FLAG((_l), 1ULL << 23)
Definition at line 129 of file lustre_dlm_flags.h.
#define ldlm_set_canceling (_l) LDLM_SET_FLAG((_l), 1ULL << 39)
Definition at line 205 of file lustre_dlm_flags.h.
Referenced by ldlm_cli_cancel().
#define ldlm_set_cbpending (_l) LDLM_SET_FLAG((_l), 1ULL << 34)
Definition at line 175 of file lustre_dlm_flags.h.
Referenced by cleanup_resource(), ldlm_blocking_ast_nocheck(), ldlm_cli_cancel_local(), ldlm_flock_interrupted_wait(), ldlm_handle_bl_callback(), ldlm_lock_decref_and_cancel(), ldlm_lock_decref_internal(), and tgt_cancel_slc_locks().
#define ldlm_set_cleaned (_l) LDLM_SET_FLAG((_l), 1ULL << 44)
Definition at line 252 of file lustre_dlm_flags.h.
Referenced by cleanup_resource().
#define ldlm_set_cos_enabled (_l) LDLM_SET_FLAG((_l), 1ULL << 57)
Definition at line 363 of file lustre_dlm_flags.h.
Referenced by ldlm_lock_enqueue().
#define ldlm_set_cos_incompat (_l) LDLM_SET_FLAG((_l), 1ULL << 24)
Definition at line 138 of file lustre_dlm_flags.h.
Referenced by ldlm_lock_enqueue().
#define ldlm_set_cp_reqd (_l) LDLM_SET_FLAG((_l), 1ULL << 43)
Definition at line 246 of file lustre_dlm_flags.h.
Referenced by ldlm_add_cp_work_item().
#define ldlm_set_deny_on_contention (_l) LDLM_SET_FLAG((_l), 1ULL << 30)
Definition at line 145 of file lustre_dlm_flags.h.
#define ldlm_set_destroyed (_l) LDLM_SET_FLAG((_l), 1ULL << 50)
Definition at line 311 of file lustre_dlm_flags.h.
Referenced by ldlm_lock_destroy_internal().
#define ldlm_set_discard_data (_l) LDLM_SET_FLAG((_l), 1ULL << 16)
Definition at line 96 of file lustre_dlm_flags.h.
Referenced by ldlm_add_bl_work_item().
#define ldlm_set_excl (_l) LDLM_SET_FLAG((_l), 1ULL << 55)
Definition at line 351 of file lustre_dlm_flags.h.
#define ldlm_set_fail_loc (_l) LDLM_SET_FLAG((_l), 1ULL << 32)
Definition at line 161 of file lustre_dlm_flags.h.
Referenced by ldlm_completion_ast().
#define ldlm_set_fail_notified (_l) LDLM_SET_FLAG((_l), 1ULL << 49)
Definition at line 300 of file lustre_dlm_flags.h.
#define ldlm_set_failed (_l) LDLM_SET_FLAG((_l), 1ULL << 38)
Definition at line 199 of file lustre_dlm_flags.h.
Referenced by cleanup_resource(), and ldlm_handle_cp_callback().
#define LDLM_SET_FLAG (_l, _b) ((_l)->l_flags |= (_b))
set a ldlm_lock flag bit
Definition at line 399 of file lustre_dlm_flags.h.
#define ldlm_set_flock_deadlock (_l) LDLM_SET_FLAG((_l), 1ULL << 15)
Definition at line 90 of file lustre_dlm_flags.h.
#define ldlm_set_has_intent (_l) LDLM_SET_FLAG((_l), 1ULL << 12)
Definition at line 84 of file lustre_dlm_flags.h.
#define ldlm_set_intent_only (_l) LDLM_SET_FLAG((_l), 1ULL << 9)
Definition at line 78 of file lustre_dlm_flags.h.
#define ldlm_set_kms_ignore (_l) LDLM_SET_FLAG((_l), 1ULL << 42)
Definition at line 240 of file lustre_dlm_flags.h.
Referenced by ldlm_extent_shift_kms().
#define ldlm_set_local (_l) LDLM_SET_FLAG((_l), 1ULL << 40)
Definition at line 211 of file lustre_dlm_flags.h.
Referenced by ldlm_cli_enqueue_local().
#define ldlm_set_local_only (_l) LDLM_SET_FLAG((_l), 1ULL << 37)
Definition at line 193 of file lustre_dlm_flags.h.
Referenced by cleanup_resource().
#define ldlm_set_lock_changed (_l) LDLM_SET_FLAG((_l), 1ULL << 0)
Definition at line 34 of file lustre_dlm_flags.h.
#define ldlm_set_lvb_ready (_l) LDLM_SET_FLAG((_l), 1ULL << 41)
Definition at line 228 of file lustre_dlm_flags.h.
Referenced by ldlm_lock_allow_match_locked().
#define ldlm_set_no_lru (_l) LDLM_SET_FLAG((_l), 1ULL << 48)
Definition at line 291 of file lustre_dlm_flags.h.
#define ldlm_set_no_timeout (_l) LDLM_SET_FLAG((_l), 1ULL << 17)
Definition at line 102 of file lustre_dlm_flags.h.
#define ldlm_set_ns_srv (_l) LDLM_SET_FLAG((_l), 1ULL << 54)
Definition at line 345 of file lustre_dlm_flags.h.
Referenced by ldlm_lock_create().
#define ldlm_set_replay (_l) LDLM_SET_FLAG((_l), 1ULL << 8)
Definition at line 72 of file lustre_dlm_flags.h.
#define ldlm_set_res_locked (_l) LDLM_SET_FLAG((_l), 1ULL << 52)
Definition at line 329 of file lustre_dlm_flags.h.
Referenced by lock_res_and_lock().
#define ldlm_set_server_lock (_l) LDLM_SET_FLAG((_l), 1ULL << 51)
Definition at line 317 of file lustre_dlm_flags.h.
#define ldlm_set_skipped (_l) LDLM_SET_FLAG((_l), 1ULL << 33)
Definition at line 169 of file lustre_dlm_flags.h.
Referenced by ldlm_cancel_no_wait_policy().
#define ldlm_set_test_lock (_l) LDLM_SET_FLAG((_l), 1ULL << 19)
Definition at line 116 of file lustre_dlm_flags.h.
Referenced by ldlm_lock_enqueue().
#define ldlm_set_wait_noreproc (_l) LDLM_SET_FLAG((_l), 1ULL << 35)
Definition at line 181 of file lustre_dlm_flags.h.
#define ldlm_set_waited (_l) LDLM_SET_FLAG((_l), 1ULL << 53)
Definition at line 339 of file lustre_dlm_flags.h.
#define LDLM_TEST_FLAG (_l, _b) (((_l)->l_flags & (_b)) != 0)
test for ldlm_lock flag bit set
Definition at line 393 of file lustre_dlm_flags.h.
#define LUSTRE_TRACKS_LOCK_EXP_REFS (0)
Whether to track references to exports by LDLM locks.
Definition at line 612 of file lustre_dlm.h.
#define NS_DEFAULT_CONTENDED_LOCKS 32
Definition at line 315 of file lustre_dlm.h.
Referenced by ldlm_namespace_new().
#define NS_DEFAULT_CONTENTION_SECONDS 2
Definition at line 314 of file lustre_dlm.h.
Referenced by ldlm_namespace_new().
#define NS_DEFAULT_MAX_NOLOCK_BYTES 0
Default values for the "max_nolock_size", "contention_time" and "contended_locks" namespace tunables.
Definition at line 313 of file lustre_dlm.h.
Referenced by ldlm_namespace_new().
#define OBD_LDLM_DEVICENAME "ldlm"
Definition at line 63 of file lustre_dlm.h.
#define to_ldlm_interval (n) container_of(n, struct ldlm_interval, li_node)
Definition at line 596 of file lustre_dlm.h.
Referenced by itree_overlap_cb(), and ldlm_extent_add_lock().
Typedef Documentation
typedef int(* ldlm_blocking_callback)(struct ldlm_lock *lock, struct ldlm_lock_desc *new, void *data, int flag)
Type for blocking callback function of a lock.
Definition at line 569 of file lustre_dlm.h.
typedef int(* ldlm_cancel_cbt)(struct ldlm_lock *lock)
Definition at line 273 of file lustre_dlm.h.
typedef int(* ldlm_completion_callback)(struct ldlm_lock *lock, __u64 flags, void *data)
Type for completion callback function of a lock.
Definition at line 573 of file lustre_dlm.h.
typedef int(* ldlm_glimpse_callback)(struct ldlm_lock *lock, void *data)
Type for glimpse callback function of a lock.
Definition at line 576 of file lustre_dlm.h.
typedef int(* ldlm_iterator_t)(struct ldlm_lock *, void *)
Definition at line 1183 of file lustre_dlm.h.
typedef int(* ldlm_processing_policy)(struct ldlm_lock *lock, __u64 *flags, int first_enq, enum ldlm_error *err, struct list_head *work_list)
Definition at line 1172 of file lustre_dlm.h.
typedef int(* ldlm_res_iterator_t)(struct ldlm_resource *, void *)
Definition at line 1184 of file lustre_dlm.h.
typedef int(* ldlm_res_policy)(struct ldlm_namespace *, struct ldlm_lock **, void *req_cookie, enum ldlm_mode mode, __u64 flags, void *data)
Definition at line 269 of file lustre_dlm.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
LDLM_NSS_LOCKS
LDLM namespace lock stats.
LDLM_NSS_LAST
Definition at line 332 of file lustre_dlm.h.
enum ldlm_appetite
LDLM pools related, type of lock pool in the namespace.
Greedy means release cached locks aggressively
Enumerator:
LDLM_NAMESPACE_GREEDY
LDLM_NAMESPACE_MODEST
Definition at line 304 of file lustre_dlm.h.
enum ldlm_cancel_flags
Cancel flags.
Enumerator:
LCF_ASYNC
LCF_LOCAL
LCF_BL_AST
Definition at line 615 of file lustre_dlm.h.
enum ldlm_error
LDLM non-error return states.
Enumerator:
ELDLM_OK
ELDLM_LOCK_MATCHED
ELDLM_LOCK_CHANGED
ELDLM_LOCK_ABORTED
ELDLM_LOCK_REPLACED
ELDLM_NO_LOCK_DATA
ELDLM_LOCK_WOULDBLOCK
ELDLM_NAMESPACE_EXISTS
ELDLM_BAD_NAMESPACE
Definition at line 73 of file lustre_dlm.h.
enum ldlm_ns_type
Enumerator:
LDLM_NS_TYPE_UNKNOWN
invalid type
LDLM_NS_TYPE_MDC
MDC namespace.
LDLM_NS_TYPE_MDT
MDT namespace.
LDLM_NS_TYPE_OSC
OSC namespace.
LDLM_NS_TYPE_OST
OST namespace.
LDLM_NS_TYPE_MGC
MGC namespace.
LDLM_NS_TYPE_MGT
MGT namespace.
Definition at line 338 of file lustre_dlm.h.
enum ldlm_side
LDLM namespace type.
The "client" type is actually an indication that this is a narrow local view into complete namespace on the server. Such namespaces cannot make any decisions about lack of conflicts or do any autonomous lock granting without first speaking to a server.
Enumerator:
LDLM_NAMESPACE_SERVER
LDLM_NAMESPACE_CLIENT
Definition at line 94 of file lustre_dlm.h.
enum lock_res_type
"Modes" of acquiring lock_res, necessary to tell lockdep that taking more than one lock_res is dead-lock safe.
Enumerator:
LRT_NORMAL
LRT_NEW
Definition at line 1531 of file lustre_dlm.h.
enum lvb_type
Enumerator:
LVB_T_NONE
LVB_T_OST
LVB_T_LQUOTA
LVB_T_LAYOUT
Definition at line 645 of file lustre_dlm.h.
Function Documentation
struct ldlm_lock* __ldlm_handle2lock (const struct lustre_handle * handle, __u64 flags) [read]
Obtain a lock reference by handle.
if flags: atomically get the lock and set the flags. Return NULL if flag already set
Definition at line 594 of file ldlm_lock.c.
References CDEBUG, class_handle2object(), lustre_handle::cookie, D_INFO, ENTRY, ldlm_lock::l_flags, ldlm_lock::l_reference, ldlm_lock::l_resource, LASSERT, ldlm_is_destroyed, LDLM_LOCK_PUT, lock_res_and_lock(), lu_ref_add(), lu_ref_add_atomic(), RETURN, unlikely, and unlock_res_and_lock().
Referenced by ldlm_handle2lock(), ldlm_handle2lock_long(), ldlm_lock_decref(), and ldlm_lock_decref_and_cancel().
static void check_res_locked (struct ldlm_resource * res) [inline, static]
Check if resource is already locked, assert if not.
Definition at line 1556 of file lustre_dlm.h.
References ldlm_resource::lr_lock.
Referenced by ldlm_add_ast_work_item(), ldlm_cancel_callback(), ldlm_flock_blocking_unlink(), ldlm_grant_lock(), ldlm_granted_list_add_lock(), ldlm_resource_add_lock(), ldlm_resource_insert_lock_after(), ldlm_resource_unlink_lock(), ofd_intent_policy(), and osc_lock_lvb_update().
int intent_disposition (struct ldlm_reply * rep, int flag)
void intent_set_disposition (struct ldlm_reply * rep, int flag)
void ldlm_cancel_callback (struct ldlm_lock *)
Helper function to call blocking AST for LDLM lock lock in a "cancelling" mode.
Definition at line 2205 of file ldlm_lock.c.
References check_res_locked(), is_bl_done(), ldlm_lock::l_ast_data, ldlm_lock::l_blocking_ast, ldlm_lock::l_resource, l_wait_event, ldlm_lock::l_waitq, LDLM_CB_CANCELING, LDLM_DEBUG, ldlm_is_bl_done, ldlm_is_cancel, ldlm_set_bl_done, ldlm_set_cancel, lock_res_and_lock(), and unlock_res_and_lock().
Referenced by ldlm_cli_cancel_local(), and ldlm_lock_cancel().
void ldlm_convert_policy_to_local (struct obd_export * exp, enum ldlm_type type, const union ldlm_wire_policy_data * wpolicy, union ldlm_policy_data * lpolicy)
Converts lock policy from on the wire lock_desc format to local format.
Definition at line 103 of file ldlm_lock.c.
References LDLM_MIN_TYPE, and ldlm_policy_wire_to_local.
Referenced by ldlm_cli_enqueue_fini(), and ldlm_handle_cp_callback().
void ldlm_convert_policy_to_wire (enum ldlm_type type, const union ldlm_policy_data * lpolicy, union ldlm_wire_policy_data * wpolicy)
Converts lock policy from local format to on the wire lock_desc format.
Definition at line 89 of file ldlm_lock.c.
References LDLM_MIN_TYPE, and ldlm_policy_local_to_wire.
Referenced by ldlm_lock2desc().
int ldlm_del_waiting_lock (struct ldlm_lock * lock)
Definition at line 595 of file ldlm_lockd.c.
References RETURN.
Referenced by ldlm_lock_cancel().
void ldlm_destroy_export (struct obd_export * exp)
Definition at line 2913 of file ldlm_lockd.c.
References cfs_hash_putref(), ENTRY, EXIT, obd_export::exp_lock_hash, and ldlm_destroy_flock_export().
Referenced by echo_destroy_export(), ldlm_init_export(), mdt_destroy_export(), mgs_destroy_export(), and ofd_destroy_export().
void ldlm_dump_all_namespaces (enum ldlm_side client, int level)
Print information about all locks in all namespaces on this node to debug log.
Definition at line 1389 of file ldlm_resource.c.
References D_ERROR, ldlm_namespace_dump(), ldlm_namespace_list(), ldlm_namespace_lock(), libcfs_debug, list_entry, list_for_each, and ldlm_namespace::ns_list_chain.
Referenced by ldlm_cleanup().
enum ldlm_error ldlm_errno2error (int err_no)
Dual to ldlm_error2errno(): maps errno values back to enum ldlm_error.
Definition at line 3009 of file ldlm_lib.c.
References ELDLM_BAD_NAMESPACE, ELDLM_LOCK_ABORTED, ELDLM_LOCK_CHANGED, ELDLM_LOCK_REPLACED, ELDLM_NAMESPACE_EXISTS, ELDLM_NO_LOCK_DATA, ELDLM_OK, and error.
int ldlm_error2errno (enum ldlm_error error)
Rather arbitrary mapping from LDLM error codes to errno values.
This should not escape to the user level.
Definition at line 2967 of file ldlm_lib.c.
References CERROR, ELDLM_BAD_NAMESPACE, ELDLM_LOCK_ABORTED, ELDLM_LOCK_CHANGED, ELDLM_LOCK_MATCHED, ELDLM_LOCK_REPLACED, ELDLM_NAMESPACE_EXISTS, ELDLM_NO_LOCK_DATA, and ELDLM_OK.
Referenced by osc_lock_upcall(), and osc_lock_upcall_agl().
int ldlm_expired_completion_wait (void * data)
Definition at line 90 of file ldlm_request.c.
References ptlrpc_connection::c_remote_uuid, CFS_DURATION_T, cfs_time_after(), cfs_time_current(), cfs_time_current_sec(), cfs_time_shift(), cfs_time_sub(), CFS_TIME_T, client_obd::cl_import, obd_device::cli, D_DLMTRACE, ENTRY, obd_export::exp_obd, obd_import::imp_connection, ldlm_lock::l_conn_export, ldlm_lock::l_last_activity, LDLM_ERROR, ldlm_lock_to_ns(), ldlm_namespace_dump(), libcfs_debug_dumplog(), lock_wait_data::lwd_conn_cnt, lock_wait_data::lwd_lock, obd2cli_tgt, ptlrpc_fail_import(), RETURN, obd_device::u, and obd_uuid::uuid.
Referenced by ldlm_completion_ast().
__u64 ldlm_extent_shift_kms (struct ldlm_lock * lock, __u64 old_kms)
Definition at line 802 of file ldlm_extent.c.
References __u64, ldlm_extent::end, ENTRY, ldlm_policy_data::l_extent, ldlm_lock::l_policy_data, ldlm_lock::l_res_link, ldlm_lock::l_resource, LASSERTF, ldlm_is_kms_ignore, ldlm_set_kms_ignore, list_entry, list_for_each, LPU64, ldlm_resource::lr_granted, and RETURN.
Referenced by osc_dlm_blocking_ast0().
int ldlm_flock_completion_ast (struct ldlm_lock * lock, __u64 flags, void * data)
Flock completion callback function.
Parameters:
lock [in,out]: A lock to be handled
flags [in]: flags
*data [in]: ldlm_work_cp_ast_lock() will use ldlm_cb_set_arg
Return values:
0 : success
<0 : failure
Definition at line 662 of file ldlm_flock.c.
References __u64, CDEBUG, client_obd::cl_import, class_exp2obd(), obd_device::cli, D_DLMTRACE, ldlm_flock::end, ENTRY, flock_set_end, flock_set_pid, flock_set_start, flock_set_type, flock_type, ldlm_flock_wait_data::fwd_generation, ldlm_flock_wait_data::fwd_lock, obd_import::imp_generation, obd_import::imp_lock, is_granted_or_cancelled(), ldlm_lock::l_ast_data, ldlm_lock::l_conn_export, ldlm_lock::l_flags, ldlm_policy_data::l_flock, ldlm_lock::l_granted_mode, ldlm_lock::l_policy_data, l_wait_event, ldlm_lock::l_waitq, LASSERT, LCK_PR, LCK_PW, LDLM_DEBUG, LDLM_FL_BLOCKED_MASK, LDLM_FL_CBPENDING, LDLM_FL_FAIL_LOC, LDLM_FL_FAILED, LDLM_FL_FLOCK_DEADLOCK, LDLM_FL_TEST_LOCK, LDLM_FL_WAIT_NOREPROC, ldlm_flock_destroy(), ldlm_flock_interrupted_wait(), ldlm_is_destroyed, ldlm_is_failed, ldlm_is_flock_deadlock, ldlm_is_test_lock, ldlm_process_flock_lock(), ldlm_resource_unlink_lock(), lock_res_and_lock(), LPX64, LWI_TIMEOUT_INTR, mode, OBD_FAIL_LDLM_CP_CB_WAIT, OBD_FAIL_LDLM_CP_CB_WAIT2, OBD_FAIL_LDLM_CP_CB_WAIT3, OBD_FAIL_LDLM_CP_CB_WAIT4, OBD_FAIL_LDLM_CP_CB_WAIT5, OBD_FAIL_PRECHECK, OBD_FAIL_TIMEOUT, ldlm_flock::pid, RETURN, ldlm_flock::start, obd_device::u, and unlock_res_and_lock().
Referenced by ll_file_flock().
int ldlm_get_ref (void)
Definition at line 2783 of file ldlm_lockd.c.
References ENTRY, ldlm_ref_mutex, ldlm_refcount, ldlm_setup(), and RETURN.
Referenced by client_obd_setup(), and ldlm_namespace_new().
static struct ldlm_lock* ldlm_handle2lock (const struct lustre_handle * h) [static, read]
Obtain a lock reference by its handle.
Definition at line 1273 of file lustre_dlm.h.
References __ldlm_handle2lock().
Referenced by ldlm_cli_convert(), ldlm_cli_enqueue_fini(), ldlm_lock_addref(), ldlm_lock_addref_try(), ldlm_lock_dump_handle(), ldlm_lock_match(), ldlm_lock_set_data(), ldlm_revalidate_lock_handle(), ll_file_ioctl(), ll_have_md_lock(), ll_layout_lock_set(), ll_lease_close(), ll_prep_inode(), mdc_finish_enqueue(), mdc_finish_intent_lock(), mdc_intent_close_pack(), mdc_set_lock_data(), mdt_check_resent_lock(), mdt_close_swap_layouts(), mdt_getattr_name_lock(), mdt_hsm_release(), mdt_lock_objects_in_linkea(), mdt_reint_migrate_internal(), mdt_save_lock(), mdt_save_remote_lock(), ofd_prolong_extent_locks(), osc_dlmlock_at_pgoff(), osc_enqueue_base(), osc_enqueue_interpret(), osc_handle_ptr(), osc_lock_upcall_agl(), osc_match_base(), qmt_dqacq(), qmt_intent_policy(), qsd_id_lock_match(), qsd_intent_lock(), qsd_ready(), and replay_lock_interpret().
static struct ldlm_lock* ldlm_handle2lock_long (const struct lustre_handle * h, __u64 flags) [static, read]
Definition at line 1282 of file lustre_dlm.h.
References __ldlm_handle2lock(), and LDLM_LOCK_REF_DEL.
Referenced by ldlm_callback_handler(), ldlm_cli_cancel(), ldlm_cli_enqueue(), mdt_intent_lock_replace(), and osc_lock_granted().
static bool ldlm_has_layout (struct ldlm_lock * lock) [inline, static]
Definition at line 987 of file lustre_dlm.h.
References ldlm_inodebits::bits, ldlm_policy_data::l_inodebits, ldlm_lock::l_policy_data, ldlm_lock::l_resource, LDLM_IBITS, ldlm_resource::lr_type, and MDS_INODELOCK_LAYOUT.
Referenced by ll_layout_conf(), ll_layout_lock_set(), ll_prep_inode(), mdc_finish_enqueue(), mdt_lvbo_fill(), and mdt_lvbo_size().
int ldlm_init_export (struct obd_export * exp)
Definition at line 2884 of file ldlm_lockd.c.
References cfs_hash_create(), CFS_HASH_DEFAULT, CFS_HASH_MAX_THETA, CFS_HASH_MIN_THETA, CFS_HASH_NBLK_CHANGE, CFS_HASH_REHASH_KEY, ENTRY, obd_export::exp_client_uuid, obd_export::exp_lock_hash, GOTO, HASH_EXP_LOCK_BKT_BITS, HASH_EXP_LOCK_CUR_BITS, HASH_EXP_LOCK_MAX_BITS, ldlm_destroy_export(), ldlm_init_flock_export(), obd_uuid2str(), and RETURN.
Referenced by echo_init_export(), mdt_init_export(), mgs_init_export(), and ofd_init_export().
const char* ldlm_it2str (enum ldlm_intent_flags it)
Definition at line 114 of file ldlm_lock.c.
References CERROR, IT_CREAT, IT_GETATTR, IT_GETXATTR, IT_LAYOUT, IT_LOOKUP, IT_OPEN, IT_READDIR, and IT_UNLINK.
Referenced by mdc_finish_enqueue(), mdc_finish_intent_lock(), mdc_intent_getattr_async(), and mdc_intent_lock().
void ldlm_lock2desc (struct ldlm_lock * lock, struct ldlm_lock_desc * desc)
Fill in "on the wire" representation for given LDLM lock into supplied lock descriptor desc structure.
Definition at line 646 of file ldlm_lock.c.
References ldlm_lock::l_granted_mode, ldlm_lock_desc::l_granted_mode, ldlm_lock_desc::l_policy_data, ldlm_lock::l_policy_data, ldlm_lock::l_req_mode, ldlm_lock_desc::l_req_mode, ldlm_lock_desc::l_resource, ldlm_lock::l_resource, ldlm_convert_policy_to_wire(), ldlm_res2desc(), and ldlm_resource::lr_type.
Referenced by ldlm_cli_enqueue(), ldlm_work_bl_ast_lock(), ldlm_work_revoke_ast_lock(), and replay_one_lock().
void ldlm_lock2handle (const struct ldlm_lock * lock, struct lustre_handle * lockh)
Fills in handle for LDLM lock lock into supplied lockh Does not take any references.
Definition at line 582 of file ldlm_lock.c.
References lustre_handle::cookie, portals_handle::h_cookie, and ldlm_lock::l_handle.
Referenced by cleanup_resource(), ldlm_blocking_ast_nocheck(), ldlm_cli_enqueue(), ldlm_cli_enqueue_local(), ldlm_lock_match(), ll_md_blocking_ast(), ll_md_blocking_lease_ast(), mdt_remote_blocking_ast(), mgc_blocking_ast(), mgs_completion_ast_generic(), osc_io_read_ahead(), osc_ldlm_blocking_ast(), osc_read_ahead_release(), qsd_glb_blocking_ast(), qsd_id_blocking_ast(), replay_one_lock(), and tgt_cancel_slc_locks().
void ldlm_lock_addref (const struct lustre_handle * lockh, enum ldlm_mode mode)
Add specified reader/writer reference to LDLM lock with handle lockh.
r/w reference type is determined by mode Calls ldlm_lock_addref_internal.
Definition at line 717 of file ldlm_lock.c.
References lustre_handle::cookie, LASSERTF, ldlm_handle2lock(), ldlm_lock_addref_internal(), LDLM_LOCK_PUT, and LPX64.
Referenced by mdc_finish_enqueue(), osc_enqueue_interpret(), osc_io_read_ahead(), osc_lock_granted(), and osc_object_fiemap().
int ldlm_lock_addref_try (const struct lustre_handle * lockh, enum ldlm_mode mode)
Attempts to add reader/writer reference to a lock with handle lockh, and fails if lock is already LDLM_FL_CBPENDING or destroyed.
Return values:
0 success, lock was addref-ed
-EAGAIN lock is being canceled.
Definition at line 760 of file ldlm_lock.c.
References ldlm_lock::l_readers, ldlm_lock::l_writers, ldlm_handle2lock(), ldlm_is_cbpending, ldlm_lock_addref_internal_nolock(), LDLM_LOCK_PUT, lock_res_and_lock(), and unlock_res_and_lock().
Referenced by qsd_id_lock_match(), and qsd_reint_main().
void ldlm_lock_allow_match (struct ldlm_lock * lock)
Mark lock as "matchable" by OST.
Locks the lock and then
See also:
ldlm_lock_allow_match_locked
Definition at line 1332 of file ldlm_lock.c.
References ldlm_lock_allow_match_locked(), lock_res_and_lock(), and unlock_res_and_lock().
Referenced by ll_layout_conf().
void ldlm_lock_allow_match_locked (struct ldlm_lock * lock)
Mark lock as "matchable" by OST.
Used to prevent certain races in LOV/OSC where the lock is granted, but LVB is not yet valid. Assumes LDLM lock is already locked.
Definition at line 1321 of file ldlm_lock.c.
References ldlm_lock::l_waitq, and ldlm_set_lvb_ready.
Referenced by ldlm_lock_allow_match(), and osc_lock_lvb_update().
void ldlm_lock_cancel (struct ldlm_lock * lock)
Attempts to cancel LDLM lock lock that has no reader/writer references.
Definition at line 2249 of file ldlm_lock.c.
References ENTRY, EXIT, ldlm_lock::l_granted_mode, ldlm_lock::l_readers, ldlm_lock::l_req_mode, ldlm_lock::l_resource, ldlm_lock::l_writers, LASSERT, LBUG, LCK_MINMODE, ldlm_cancel_callback(), ldlm_del_waiting_lock(), LDLM_ERROR, ldlm_is_waited, ldlm_lock_destroy_nolock(), ldlm_pool_del(), ldlm_res_to_ns(), ldlm_resource_unlink_lock(), lock_res_and_lock(), ldlm_namespace::ns_pool, and unlock_res_and_lock().
Referenced by cleanup_resource(), ldlm_cancel_lock_for_export(), ldlm_cli_cancel_list_local(), ldlm_cli_cancel_local(), mdt_close_swap_layouts(), mdt_hsm_release(), mdt_reint_migrate_internal(), and replay_one_lock().
int ldlm_lock_change_resource (struct ldlm_namespace * ns, struct ldlm_lock * lock, const struct ldlm_res_id * new_resid)
Moves LDLM lock lock to another resource.
This is used on client when server returns some other lock than requested (typically as a result of intent operation)
Definition at line 514 of file ldlm_lock.c.
References ENTRY, ldlm_lock::l_lock, ldlm_lock::l_res_link, ldlm_lock::l_resource, LASSERT, ldlm_resource_get(), ldlm_resource_putref(), list_empty(), lock_res(), lock_res_and_lock(), lock_res_nested(), ldlm_resource::lr_name, ldlm_resource::lr_reference, ldlm_resource::lr_type, LRT_NEW, lu_ref_add(), lu_ref_del(), ldlm_res_id::name, ns_is_client(), RETURN, unlock_res(), and unlock_res_and_lock().
Referenced by ldlm_cli_enqueue_fini(), and ldlm_handle_cp_callback().
struct ldlm_resource* ldlm_lock_convert (struct ldlm_lock * lock, enum ldlm_mode new_mode, __u32 * flags) [read]
Attempt to convert already granted lock to a different mode.
While lock conversion is not currently used, future client-side optimizations could take advantage of it to avoid discarding cached pages on a file.
Definition at line 2459 of file ldlm_lock.c.
References __u64, ENTRY, INIT_LIST_HEAD, ldlm_lock::l_completion_ast, ldlm_lock::l_granted_mode, ldlm_lock::l_req_mode, ldlm_lock::l_res_link, ldlm_lock::l_resource, ldlm_lock::l_sl_mode, ldlm_lock::l_sl_policy, LASSERTF, LBUG, LCK_PR, LCK_PW, LDLM_ERROR, LDLM_EXTENT, ldlm_extent_add_lock(), LDLM_FL_BLOCK_CONV, LDLM_FL_BLOCK_GRANTED, ldlm_grant_lock(), ldlm_granted_list_add_lock(), LDLM_IBITS, ldlm_interval_attach(), ldlm_interval_slab, LDLM_ITER_STOP, LDLM_PLAIN, ldlm_pool_del(), ldlm_res_to_ns(), ldlm_resource_add_lock(), ldlm_resource_unlink_lock(), ldlm_interval::li_group, lock_res_and_lock(), ldlm_resource::lr_converting, ldlm_resource::lr_type, sl_insert_point::mode_link, ns_is_client(), ldlm_namespace::ns_pool, OBD_SLAB_ALLOC_PTR_GFP, sl_insert_point::policy_link, list_head::prev, sl_insert_point::res_link, and RETURN.
Referenced by ldlm_cli_convert(), and ldlm_cli_convert_local().
void ldlm_lock_decref (const struct lustre_handle * lockh, enum ldlm_mode mode)
Decrease reader/writer refcount for LDLM lock with handle lockh.
Definition at line 903 of file ldlm_lock.c.
References __ldlm_handle2lock(), lustre_handle::cookie, LASSERTF, ldlm_lock_decref_internal(), LDLM_LOCK_PUT, and LPX64.
Referenced by echo_cleanup(), lfsck_ibits_unlock(), lfsck_layout_slave_conditional_destroy(), ll_intent_drop_lock(), ll_layout_lock_set(), lmv_intent_lock(), lmv_intent_remote(), lmv_revalidate_slaves(), lod_object_unlock_internal(), mdc_enqueue(), mdc_finish_enqueue(), mdc_read_page(), mdt_fid_unlock(), mdt_getattr_name(), mdt_save_remote_lock(), mgc_cancel(), ofd_destroy_by_fid(), osc_enqueue_base(), osc_enqueue_fini(), osc_enqueue_interpret(), osc_io_read_ahead(), osc_lock_detach(), osc_match_base(), osc_object_fiemap(), osc_read_ahead_release(), osp_md_object_unlock(), ptlrpc_handle_rs(), ptlrpc_save_lock(), qsd_reint_main(), qsd_req_completion(), and tgt_extent_unlock().
void ldlm_lock_decref_and_cancel (const struct lustre_handle * lockh, enum ldlm_mode mode)
Decrease reader/writer refcount for LDLM lock with handle lockh and mark it for subsequent cancellation once r/w refcount drops to zero instead of putting into LRU.
Definition at line 918 of file ldlm_lock.c.
References __ldlm_handle2lock(), ENTRY, LASSERT, LDLM_DEBUG, ldlm_lock_decref_internal(), LDLM_LOCK_PUT, ldlm_lockname, ldlm_set_cbpending, lock_res_and_lock(), and unlock_res_and_lock().
Referenced by ll_lease_open(), ll_xattr_cache_refill(), mdc_finish_intent_lock(), mdt_rename_unlock(), mdt_save_remote_lock(), mgs_completion_ast_generic(), and qsd_id_lock_cancel().
void ldlm_lock_destroy (struct ldlm_lock * lock)
Destroys a LDLM lock lock.
Performs necessary locking first.
Definition at line 403 of file ldlm_lock.c.
References ENTRY, EXIT, ldlm_lock::l_reference, ldlm_lock_destroy_internal(), LDLM_LOCK_RELEASE, lock_res_and_lock(), lu_ref_del(), and unlock_res_and_lock().
Referenced by ldlm_lock_create(), and ldlm_lock_enqueue().
void ldlm_lock_downgrade (struct ldlm_lock * lock, enum ldlm_mode new_mode)
Downgrade an exclusive lock.
A fast variant of ldlm_lock_convert for convertion of exclusive locks. The convertion is always successful. Used by Commit on Sharing (COS) code.
Parameters:
lock A lock to convert
new_mode new lock mode
Definition at line 2428 of file ldlm_lock.c.
References ENTRY, EXIT, ldlm_lock::l_granted_mode, ldlm_lock::l_req_mode, ldlm_lock::l_resource, LASSERT, LCK_COS, LCK_EX, LCK_PW, ldlm_grant_lock(), ldlm_lock_to_ns(), ldlm_pool_del(), ldlm_reprocess_all(), ldlm_resource_unlink_lock(), lock_res_and_lock(), and unlock_res_and_lock().
Referenced by mdt_save_lock().
void ldlm_lock_dump_handle (int level, const struct lustre_handle * lockh)
Print lock with lock handle lockh description into debug log.
Used when printing all locks on a resource for debug purposes.
Definition at line 2586 of file ldlm_lock.c.
References D_ERROR, LDLM_DEBUG_LIMIT, ldlm_handle2lock(), LDLM_LOCK_PUT, and libcfs_debug.
Referenced by qsd_id_lock_match().
void ldlm_lock_fail_match (struct ldlm_lock * lock)
Definition at line 1307 of file ldlm_lock.c.
References ldlm_lock_fail_match_locked(), lock_res_and_lock(), and unlock_res_and_lock().
void ldlm_lock_fail_match_locked (struct ldlm_lock * lock)
Definition at line 1298 of file ldlm_lock.c.
References ldlm_lock::l_flags, ldlm_lock::l_waitq, and LDLM_FL_FAIL_NOTIFIED.
Referenced by ldlm_lock_fail_match().
struct ldlm_lock* ldlm_lock_get (struct ldlm_lock * lock) [read]
Get a reference on a lock.
Lock refcounts, during creation:
one special one for allocation, dec'd only once in destroy
one for being a lock that's in-use
one for the addref associated with a new lock
Definition at line 178 of file ldlm_lock.c.
enum ldlm_mode ldlm_lock_match (struct ldlm_namespace * ns, __u64 flags, const struct ldlm_res_id * res_id, enum ldlm_type type, union ldlm_policy_data * policy, enum ldlm_mode mode, struct lustre_handle * lockh, int unref)
Attempt to find a lock with specified properties.
Typically returns a reference to matched lock unless LDLM_FL_TEST_LOCK is set in flags
Can be called in two ways:
If 'ns' is NULL, then lockh describes an existing lock that we want to look for a duplicate of.
Otherwise, all of the fields must be filled in, to match against.
If 'flags' contains LDLM_FL_LOCAL_ONLY, then only match local locks on the server (ie, connh is NULL) If 'flags' contains LDLM_FL_BLOCK_GRANTED, then only locks on the granted list will be considered If 'flags' contains LDLM_FL_CBPENDING, then locks that have been marked to be canceled can still be matched as long as they still have reader or writer refernces If 'flags' contains LDLM_FL_TEST_LOCK, then don't actually reference a lock, just tell us if we would have matched.
Return values:
1 if it finds an already-existing lock that is compatible; in this case, lockh is filled in with a addref()ed lock
We also check security context, and if that fails we simply return 0 (to keep caller code unchanged), the context failure will be discovered by caller sometime later.
Definition at line 1370 of file ldlm_lock.c.
References __u64, cfs_time_seconds(), class_exp2cliimp(), ldlm_extent::end, ENTRY, EXIT, GOTO, ldlm_lock::l_completion_ast, ldlm_lock::l_conn_export, ldlm_policy_data::l_extent, ldlm_lock::l_flags, ldlm_lock::l_req_mode, ldlm_lock::l_resource, l_wait_event, ldlm_lock::l_waitq, LASSERT, LDLM_DEBUG, LDLM_DEBUG_NOLOCK, LDLM_EXTENT, LDLM_FL_BLOCK_GRANTED, LDLM_FL_DESTROYED, LDLM_FL_FAIL_NOTIFIED, LDLM_FL_LVB_READY, LDLM_FL_TEST_LOCK, LDLM_FL_WAIT_NOREPROC, ldlm_handle2lock(), LDLM_IBITS, ldlm_is_lvb_ready, ldlm_lock2handle(), ldlm_lock_decref_internal(), LDLM_LOCK_PUT, LDLM_LOCK_RELEASE, ldlm_lock_to_ns(), LDLM_PLAIN, LDLM_RESOURCE_ADDREF, LDLM_RESOURCE_DELREF, ldlm_resource_get(), ldlm_resource_putref(), lock_match_data::lmd_old, lock_res(), LPU64, ldlm_resource::lr_converting, ldlm_resource::lr_granted, ldlm_resource::lr_name, ldlm_resource::lr_type, ldlm_resource::lr_waiting, LWI_ON_SIGNAL_NOOP, LWI_TIMEOUT_INTR, ldlm_res_id::name, obd_timeout, RETURN, search_itree(), search_queue(), sptlrpc_import_check_ctx(), ldlm_extent::start, and unlock_res().
Referenced by mdc_finish_intent_lock(), mdc_lock_match(), osc_enqueue_base(), osc_match_base(), and osc_object_fiemap().
void ldlm_lock_put (struct ldlm_lock * lock)
Release lock reference.
Also frees the lock if it was last reference.
Definition at line 190 of file ldlm_lock.c.
References class_export_lock_put, ENTRY, EXIT, ldlm_lock::l_exp_list, ldlm_lock::l_export, ldlm_lock::l_handle, ldlm_lock::l_lvb_data, ldlm_lock::l_lvb_len, ldlm_lock::l_pending_chain, ldlm_lock::l_refc, ldlm_lock::l_reference, ldlm_lock::l_res_link, ldlm_lock::l_resource, LASSERT, LDLM_DEBUG, ldlm_interval_detach(), ldlm_interval_free(), ldlm_is_destroyed, LDLM_NSS_LOCKS, ldlm_res_to_ns(), ldlm_resource_putref(), list_empty(), lprocfs_counter_decr(), ldlm_resource::lr_reference, lu_ref_del(), lu_ref_fini(), OBD_FREE_LARGE, and OBD_FREE_RCU.
int ldlm_lock_remove_from_lru (struct ldlm_lock *)
int ldlm_lock_set_data (const struct lustre_handle * lockh, void * data)
Set opaque data into the lock that only makes sense to upper layer.
Definition at line 2293 of file ldlm_lock.c.
References ENTRY, ldlm_lock::l_ast_data, ldlm_handle2lock(), LDLM_LOCK_PUT, and RETURN.
Referenced by mgc_process_log().
static struct ldlm_namespace* ldlm_lock_to_ns (struct ldlm_lock * lock) [static, read]
Definition at line 1006 of file lustre_dlm.h.
References ldlm_lock::l_resource, and ldlm_res_to_ns().
Referenced by ldlm_cli_cancel(), ldlm_cli_cancel_local(), ldlm_cli_convert_local(), ldlm_completion_ast(), ldlm_expired_completion_wait(), ldlm_lock_add_to_lru(), ldlm_lock_add_to_lru_nolock(), ldlm_lock_decref_internal(), ldlm_lock_downgrade(), ldlm_lock_match(), ldlm_lock_remove_from_lru_check(), ldlm_lock_remove_from_lru_nolock(), ldlm_lock_to_ns_name(), ldlm_lock_touch_in_lru(), ldlm_lvbo_fill(), ldlm_lvbo_size(), mdt_blocking_ast(), and mdt_lvbo_fill().
static struct adaptive_timeout* ldlm_lock_to_ns_at (struct ldlm_lock * lock) [static, read]
Definition at line 1018 of file lustre_dlm.h.
References ldlm_lock::l_resource, ldlm_resource::lr_ns_bucket, and ldlm_ns_bucket::nsb_at_estimate.
Referenced by ldlm_completion_tail(), and ldlm_cp_timeout().
static char* ldlm_lock_to_ns_name (struct ldlm_lock * lock) [inline, static]
Definition at line 1012 of file lustre_dlm.h.
References ldlm_lock_to_ns(), and ldlm_ns_name().
Referenced by _ldlm_lock_debug().
static int ldlm_lvbo_fill (struct ldlm_lock * lock, void * buf, int len) [inline, static]
Definition at line 1064 of file lustre_dlm.h.
References CERROR, ldlm_lock::l_resource, LASSERT, ldlm_lock_to_ns(), ldlm_lvbo_init(), ldlm_valblock_ops::lvbo_fill, and ldlm_namespace::ns_lvbo.
Referenced by qmt_intent_policy().
static int ldlm_lvbo_init (struct ldlm_resource * res) [inline, static]
Definition at line 1023 of file lustre_dlm.h.
References CDEBUG, D_DLMTRACE, ldlm_res_to_ns(), ldlm_resource::lr_lvb_data, ldlm_resource::lr_lvb_initialized, ldlm_resource::lr_lvb_len, ldlm_resource::lr_lvb_mutex, ldlm_valblock_ops::lvbo_init, ldlm_namespace::ns_lvbo, and OBD_FREE.
Referenced by ldlm_cli_enqueue_local(), ldlm_lvbo_fill(), and ldlm_res_lvbo_update().
static int ldlm_lvbo_size (struct ldlm_lock * lock) [inline, static]
Definition at line 1054 of file lustre_dlm.h.
References ldlm_lock_to_ns(), ldlm_valblock_ops::lvbo_size, and ldlm_namespace::ns_lvbo.
Referenced by qmt_intent_policy().
int ldlm_namespace_cleanup (struct ldlm_namespace * ns, __u64 flags)
Cancel and destroy all locks in the namespace.
Typically used during evictions when server notified client that it was evicted and all of its state needs to be destroyed. Also used during shutdown.
Definition at line 892 of file ldlm_resource.c.
References CDEBUG, cfs_hash_for_each_nolock(), D_INFO, ELDLM_OK, ldlm_resource_clean(), ldlm_resource_complain(), and ldlm_namespace::ns_rs_hash.
Referenced by __ldlm_namespace_free(), ldlm_namespace_new(), lwp_import_event(), mdc_import_event(), mgc_import_event(), osc_import_event(), and osp_import_event().
void ldlm_namespace_dump (int level, struct ldlm_namespace *)
Print information about all locks in this namespace on this node to debug log.
Definition at line 1425 of file ldlm_resource.c.
References CDEBUG, cfs_hash_for_each_nolock(), cfs_time_before(), cfs_time_current(), cfs_time_shift(), D_ERROR, ldlm_ns_name(), ldlm_res_hash_dump(), libcfs_debug, ldlm_namespace::ns_bref, ns_is_client(), ldlm_namespace::ns_lock, ldlm_namespace::ns_next_dump, and ldlm_namespace::ns_rs_hash.
Referenced by ldlm_dump_all_namespaces(), and ldlm_expired_completion_wait().
void ldlm_namespace_free (struct ldlm_namespace * ns, struct obd_import * imp, int force)
Cleanup the resource, and free namespace.
bug 12864: Deadlock issue: proc1: destroy import class_disconnect_export(grab cl_sem) -> -> ldlm_namespace_free -> -> lprocfs_remove(grab _lprocfs_lock). proc2: read proc info lprocfs_fops_read(grab _lprocfs_lock) -> -> osc_rd_active, etc(grab cl_sem).
So that I have to split the ldlm_namespace_free into two parts - the first part ldlm_namespace_free_prior is used to cleanup the resource which is being used; the 2nd part ldlm_namespace_free_post is used to unregister the lprocfs entries, and then free memory. It will be called w/o cli->cl_sem held.
Definition at line 1052 of file ldlm_resource.c.
References ldlm_namespace_free_post(), and ldlm_namespace_free_prior().
Referenced by echo_cleanup(), mdt_init0(), mgs_init0(), and ofd_init0().
void ldlm_namespace_free_post (struct ldlm_namespace * ns)
Performs freeing memory structures related to ns.
This is only done when ldlm_namespce_free_prior() successfully removed all resources referencing ns and its refc == 0.
Definition at line 1007 of file ldlm_resource.c.
References cfs_hash_putref(), ENTRY, EXIT, LASSERT, ldlm_namespace_proc_unregister, ldlm_namespace_unregister(), ldlm_pool_fini(), ldlm_put_ref(), list_empty(), ldlm_namespace::ns_client, ldlm_namespace::ns_list_chain, ldlm_namespace::ns_pool, ldlm_namespace::ns_rs_hash, and OBD_FREE_PTR.
Referenced by client_obd_cleanup(), ldlm_namespace_free(), mdt_fini(), mgs_device_fini(), and ofd_fini().
void ldlm_namespace_free_prior (struct ldlm_namespace * ns, struct obd_import * imp, int force)
Performs various cleanups for passed ns to make it drop refc and be ready for freeing.
Waits for refc == 0.
The following is done: (0) Unregister ns from its list to make inaccessible for potential users like pools thread and others; (1) Clear all locks in ns.
Definition at line 966 of file ldlm_resource.c.
References __ldlm_namespace_free(), ELDLM_OK, ENTRY, EXIT, LASSERT, ldlm_namespace::ns_lock, ldlm_namespace::ns_stopping, ptlrpc_disconnect_import(), and ptlrpc_invalidate_import().
Referenced by client_disconnect_export(), ldlm_namespace_free(), mdt_fini(), mgs_device_fini(), and ofd_fini().
void ldlm_namespace_get (struct ldlm_namespace * ns)
Definition at line 1061 of file ldlm_resource.c.
References ldlm_namespace::ns_bref.
struct ldlm_namespace* ldlm_namespace_new (struct obd_device * obd, char * name, enum ldlm_side client, enum ldlm_appetite apt, enum ldlm_ns_type ns_type) [read]
Create and initialize new empty namespace.
Definition at line 661 of file ldlm_resource.c.
References at_init(), CERROR, cfs_hash_bd_extra_get(), CFS_HASH_BIGNAME, cfs_hash_create(), CFS_HASH_DEPTH, cfs_hash_for_each_bucket, CFS_HASH_MAX_THETA, CFS_HASH_MIN_THETA, CFS_HASH_NO_ITEMREF, cfs_hash_putref(), CFS_HASH_SPIN_BKTLOCK, ENTRY, GOTO, INIT_LIST_HEAD, LASSERT, LDLM_CTIME_AGE_LIMIT, LDLM_DEFAULT_LRU_SIZE, LDLM_DEFAULT_MAX_ALIVE, LDLM_DEFAULT_PARALLEL_AST_LIMIT, ldlm_enqueue_min, ldlm_get_ref(), ldlm_namespace_cleanup(), ldlm_namespace_nr_read(), ldlm_namespace_proc_register, ldlm_namespace_proc_unregister, ldlm_namespace_register(), LDLM_NS_TYPE_UNKNOWN, ldlm_pool_init(), ldlm_put_ref(), ldlm_namespace::ns_appetite, ldlm_namespace::ns_bref, ldlm_namespace::ns_client, ldlm_namespace::ns_connect_flags, ldlm_namespace::ns_contended_locks, ldlm_namespace::ns_contention_time, ldlm_namespace::ns_ctime_age_limit, NS_DEFAULT_CONTENDED_LOCKS, NS_DEFAULT_CONTENTION_SECONDS, NS_DEFAULT_MAX_NOLOCK_BYTES, ldlm_namespace::ns_list_chain, ldlm_namespace::ns_lock, ldlm_namespace::ns_max_age, ldlm_namespace::ns_max_nolock_size, ldlm_namespace::ns_max_parallel_ast, ldlm_namespace::ns_max_unused, ldlm_namespace::ns_nr_unused, ldlm_namespace::ns_obd, ldlm_namespace::ns_orig_connect_flags, ldlm_namespace::ns_pool, ldlm_namespace::ns_reclaim_start, ldlm_namespace::ns_rs_hash, ldlm_namespace::ns_stopping, ldlm_namespace::ns_timeouts, ldlm_namespace::ns_unused_list, ldlm_namespace::ns_waitq, ldlm_ns_bucket::nsb_at_estimate, ldlm_ns_bucket::nsb_namespace, ldlm_ns_bucket::nsb_reclaim_start, ldlm_ns_hash_def::nsd_all_bits, ldlm_ns_hash_def::nsd_bkt_bits, ldlm_ns_hash_def::nsd_hops, ldlm_ns_hash_def::nsd_type, OBD_ALLOC_PTR, OBD_FREE_PTR, and RETURN.
Referenced by client_obd_setup(), echo_setup(), mdt_init0(), mgs_init0(), and ofd_init0().
void ldlm_namespace_put (struct ldlm_namespace * ns)
Definition at line 1072 of file ldlm_resource.c.
References ldlm_namespace::ns_bref, ldlm_namespace::ns_lock, and ldlm_namespace::ns_waitq.
Referenced by __ldlm_resource_putref_final().
void ldlm_namespace_register (struct ldlm_namespace * ns, enum ldlm_side client)
Register ns in the list of namespaces.
Definition at line 1081 of file ldlm_resource.c.
References LASSERT, ldlm_namespace_inactive_list(), ldlm_namespace_lock(), ldlm_namespace_nr_inc(), list_add(), list_empty(), and ldlm_namespace::ns_list_chain.
Referenced by ldlm_namespace_new().
void ldlm_namespace_unregister (struct ldlm_namespace * ns, enum ldlm_side client)
Unregister ns from the list of namespaces.
Definition at line 1091 of file ldlm_resource.c.
References LASSERT, ldlm_namespace_lock(), ldlm_namespace_nr_dec(), list_del_init(), list_empty(), and ldlm_namespace::ns_list_chain.
Referenced by ldlm_namespace_free_post().
static char* ldlm_ns_name (struct ldlm_namespace * ns) [inline, static]
Definition at line 994 of file lustre_dlm.h.
References cfs_hash::hs_name, and ldlm_namespace::ns_rs_hash.
Referenced by __ldlm_namespace_free(), ldlm_cancel_unused_locks_for_replay(), ldlm_lock_to_ns_name(), ldlm_namespace_dump(), and ldlm_resource_complain().
static void ldlm_proc_cleanup (void) [inline, static]
Definition at line 1414 of file lustre_dlm.h.
Referenced by ldlm_cleanup().
int ldlm_proc_setup (void)
Referenced by ldlm_setup().
void ldlm_put_ref (void)
Definition at line 2798 of file ldlm_lockd.c.
References CERROR, ENTRY, EXIT, ldlm_cleanup(), ldlm_ref_mutex, and ldlm_refcount.
Referenced by client_obd_cleanup(), client_obd_setup(), ldlm_namespace_free_post(), and ldlm_namespace_new().
int ldlm_refresh_waiting_lock (struct ldlm_lock * lock, int timeout)
Definition at line 600 of file ldlm_lockd.c.
References RETURN.
Referenced by ofd_prolong_one_lock(), and qmt_dqacq().
void ldlm_register_intent (struct ldlm_namespace * ns, ldlm_res_policy arg)
Definition at line 159 of file ldlm_lock.c.
References ldlm_namespace::ns_policy.
Referenced by mdt_init0(), and ofd_init0().
int ldlm_replay_locks (struct obd_import * imp)
Definition at line 2338 of file ldlm_request.c.
References ENTRY, obd_import::imp_obd, obd_import::imp_replay_inflight, obd_import::imp_vbr_failed, ldlm_lock::l_pending_chain, LASSERT, ldlm_cancel_unused_locks_before_replay, ldlm_cancel_unused_locks_for_replay(), ldlm_chain_lock_for_replay(), LDLM_LOCK_RELEASE, ldlm_namespace_foreach(), list_del_init(), list_for_each_entry_safe, LIST_HEAD_INIT, obd_device::obd_namespace, replay_one_lock(), and RETURN.
Referenced by ptlrpc_import_recovery_state_machine().
void ldlm_reprocess_all (struct ldlm_resource * res)
Try to grant all waiting locks on a resource.
Calls ldlm_reprocess_queue on converting and waiting queues.
Typically called after some resource locks are cancelled to see if anything could be granted as a result of the cancellation.
Definition at line 2147 of file ldlm_lock.c.
References CERROR, ENTRY, EXIT, INIT_LIST_HEAD, LASSERT, LBUG, LDLM_ITER_CONTINUE, ldlm_res_to_ns(), ldlm_run_ast_work(), LDLM_WORK_CP_AST, list_empty(), lock_res(), ldlm_resource::lr_converting, ldlm_resource::lr_waiting, ns_is_client(), and unlock_res().
Referenced by ldlm_cancel_lock_for_export(), ldlm_cli_cancel_local(), ldlm_cli_convert(), ldlm_cli_convert_local(), ldlm_completion_ast_async(), ldlm_lock_downgrade(), mdt_close_swap_layouts(), mdt_hsm_release(), mdt_reint_migrate_internal(), and reprocess_one_queue().
void ldlm_reprocess_all_ns (struct ldlm_namespace * ns)
Iterate through all resources on a namespace attempting to grant waiting locks.
Definition at line 2128 of file ldlm_lock.c.
References cfs_hash_for_each_nolock(), ENTRY, EXIT, ldlm_reprocess_res(), and ldlm_namespace::ns_rs_hash.
struct ldlm_lock* ldlm_request_lock (struct ptlrpc_request * req) [read]
Referenced by qmt_lvbo_update().
void ldlm_res2desc (struct ldlm_resource * res, struct ldlm_resource_desc * desc)
Definition at line 1379 of file ldlm_resource.c.
References ldlm_resource::lr_name, ldlm_resource_desc::lr_name, ldlm_resource::lr_type, and ldlm_resource_desc::lr_type.
Referenced by ldlm_lock2desc().
static int ldlm_res_lvbo_update (struct ldlm_resource * res, struct ptlrpc_request * req, int increase) [inline, static]
Update Lock Value Block Operations (LVBO) on a resource taking into account data from request r.
Definition at line 1296 of file lustre_dlm.h.
References CERROR, ldlm_lvbo_init(), ldlm_res_to_ns(), ldlm_valblock_ops::lvbo_update, and ldlm_namespace::ns_lvbo.
Referenced by ldlm_cancel_lock_for_export(), ofd_commitrw(), ofd_echo_setattr(), ofd_intent_policy(), ofd_punch_hdl(), and ofd_setattr_hdl().
static struct ldlm_namespace* ldlm_res_to_ns (struct ldlm_resource * res) [static, read]
Definition at line 1000 of file lustre_dlm.h.
References ldlm_resource::lr_ns_bucket, and ldlm_ns_bucket::nsb_namespace.
Referenced by cleanup_resource(), ldlm_cli_hash_cancel_unused(), ldlm_grant_lock(), ldlm_lock_cancel(), ldlm_lock_convert(), ldlm_lock_enqueue(), ldlm_lock_new(), ldlm_lock_put(), ldlm_lock_to_ns(), ldlm_lvbo_init(), ldlm_process_flock_lock(), ldlm_reprocess_all(), ldlm_res_lvbo_update(), ldlm_resource_complain(), ldlm_resource_putref(), mdt_lvbo_free(), mdt_lvbo_init(), mdt_lvbo_size(), mdt_lvbo_update(), ofd_intent_policy(), ofd_lvbo_init(), and ofd_lvbo_update().
void ldlm_resource_add_lock (struct ldlm_resource * res, struct list_head * head, struct ldlm_lock * lock)
Add a lock into a given resource into specified lock list.
Definition at line 1323 of file ldlm_resource.c.
References CDEBUG, check_res_locked(), D_OTHER, ldlm_lock::l_res_link, LASSERT, LDLM_DEBUG, ldlm_is_destroyed, list_add_tail(), and list_empty().
Referenced by ldlm_extent_add_lock(), ldlm_grant_lock(), ldlm_lock_convert(), ldlm_lock_enqueue(), and ldlm_process_flock_lock().
void ldlm_resource_dump (int level, struct ldlm_resource *)
Print information about all locks in this resource to debug log.
Definition at line 1448 of file ldlm_resource.c.
References CDEBUG, CLASSERT, D_CANTMASK, D_ERROR, DLDLMRES, ldlm_lock::l_res_link, LDLM_DEBUG_LIMIT, ldlm_dump_granted_max, libcfs_debug, list_empty(), list_for_each_entry, list_for_each_entry_reverse, ldlm_resource::lr_converting, ldlm_resource::lr_granted, ldlm_resource::lr_refcount, ldlm_resource::lr_waiting, PLDLMRES, and RES_NAME_SIZE.
Referenced by __ldlm_resource_putref_final(), ldlm_granted_list_add_lock(), ldlm_process_flock_lock(), ldlm_res_hash_dump(), ldlm_resource_complain(), ldlm_resource_insert_lock_after(), and osc_req_attr_set().
struct ldlm_resource* ldlm_resource_get (struct ldlm_namespace * ns, struct ldlm_resource * parent, const struct ldlm_res_id * name, enum ldlm_type type, int create) [read]
Return a reference to resource with given name, creating it if necessary.
Args: namespace with ns_lock unlocked Locks: takes and releases NS hash-lock and res->lr_lock Returns: referenced, unlocked ldlm_resource or NULL
Definition at line 1179 of file ldlm_resource.c.
References __u64, cfs_hash_bd_add_locked(), cfs_hash_bd_count_get(), cfs_hash_bd_extra_get(), cfs_hash_bd_get_and_lock(), cfs_hash_bd_lock(), cfs_hash_bd_lookup_locked(), cfs_hash_bd_unlock(), cfs_hash_bd_version_get(), GOTO, hlist_entry, LASSERT, LASSERTF, LCK_MODE_NUM, ldlm_interval_tree_slab, LDLM_MAX_TYPE, LDLM_MIN_TYPE, LDLM_NAMESPACE_CLIENT, ldlm_namespace_get_return(), ldlm_namespace_lock(), ldlm_namespace_move_to_active_locked(), ldlm_resource_new(), ldlm_resource_slab, ldlm_resource::lr_hash, ldlm_resource::lr_itree, ldlm_resource::lr_name, ldlm_resource::lr_ns_bucket, ldlm_resource::lr_reference, ldlm_resource::lr_type, lu_ref_fini(), ldlm_res_id::name, ns_is_client(), ldlm_namespace::ns_rs_hash, OBD_FAIL_LDLM_CREATE_RESOURCE, OBD_FAIL_TIMEOUT, OBD_SLAB_FREE, and version.
Referenced by ldlm_cli_cancel_unused_resource(), ldlm_lock_change_resource(), ldlm_lock_create(), ldlm_lock_match(), ldlm_resource_iterate(), mdc_null_inode(), mdc_resource_get_unused(), ofd_commitrw(), ofd_echo_setattr(), ofd_punch_hdl(), ofd_setattr_hdl(), osc_req_attr_set(), osc_resource_get_unused(), qmt_glb_lock_notify(), and qmt_id_lock_glimpse().
struct ldlm_resource* ldlm_resource_getref (struct ldlm_resource * res) [read]
Definition at line 1257 of file ldlm_resource.c.
References CDEBUG, D_INFO, LASSERT, and ldlm_resource::lr_refcount.
Referenced by ldlm_cancel_lock_for_export(), and ldlm_res_hop_get_locked().
int ldlm_resource_putref (struct ldlm_resource * res)
Definition at line 1295 of file ldlm_resource.c.
References __ldlm_resource_putref_final(), CDEBUG, cfs_hash_bd_dec_and_lock(), cfs_hash_bd_get(), cfs_hash_bd_unlock(), D_INFO, LASSERT_ATOMIC_GT_LT, LCK_MODE_NUM, ldlm_interval_tree_slab, ldlm_res_to_ns(), ldlm_resource_slab, ldlm_resource::lr_itree, ldlm_resource::lr_name, ldlm_resource::lr_refcount, ldlm_valblock_ops::lvbo_free, ldlm_namespace::ns_lvbo, ldlm_namespace::ns_rs_hash, and OBD_SLAB_FREE.
Referenced by ldlm_cancel_lock_for_export(), ldlm_cli_cancel_unused_resource(), ldlm_lock_change_resource(), ldlm_lock_match(), ldlm_lock_put(), ldlm_res_hop_put(), ldlm_resource_iterate(), mdc_null_inode(), mdc_resource_get_unused(), ofd_commitrw(), ofd_echo_setattr(), ofd_punch_hdl(), ofd_setattr_hdl(), osc_resource_get_unused(), qmt_glb_lock_notify(), and qmt_id_lock_glimpse().
void ldlm_resource_unlink_lock (struct ldlm_lock * lock)
Definition at line 1366 of file ldlm_resource.c.
References check_res_locked(), ldlm_lock::l_res_link, ldlm_lock::l_resource, LDLM_EXTENT, ldlm_extent_unlink_lock(), LDLM_IBITS, LDLM_PLAIN, ldlm_unlink_lock_skiplist(), list_del_init(), and ldlm_resource::lr_type.
Referenced by failed_lock_cleanup(), ldlm_flock_cancel_on_deadlock(), ldlm_flock_completion_ast(), ldlm_handle_cp_callback(), ldlm_lock_cancel(), ldlm_lock_convert(), ldlm_lock_downgrade(), ldlm_lock_enqueue(), and ofd_intent_policy().
enum ldlm_mode ldlm_revalidate_lock_handle (const struct lustre_handle * lockh, __u64 * bits)
Definition at line 1504 of file ldlm_lock.c.
References ldlm_inodebits::bits, ENTRY, EXIT, GOTO, ldlm_lock::l_granted_mode, ldlm_policy_data::l_inodebits, ldlm_lock::l_policy_data, ldlm_lock::l_readers, ldlm_lock::l_writers, ldlm_handle2lock(), LDLM_HAVE_MASK, ldlm_is_cbpending, ldlm_lock_addref_internal_nolock(), LDLM_LOCK_PUT, lock_res_and_lock(), mode, and unlock_res_and_lock().
Referenced by mdc_revalidate_lock().
void ldlm_unlink_lock_skiplist (struct ldlm_lock * req)
Remove skiplist-enabled LDLM lock req from granted list.
Definition at line 2236 of file ldlm_lock.c.
References ldlm_lock::l_resource, ldlm_lock::l_sl_mode, ldlm_lock::l_sl_policy, LDLM_IBITS, LDLM_PLAIN, list_del_init(), and ldlm_resource::lr_type.
Referenced by ldlm_resource_unlink_lock().
static void lock_res (struct ldlm_resource * res) [inline, static]
Lock resource.
Definition at line 1537 of file lustre_dlm.h.
References ldlm_resource::lr_lock.
Referenced by cleanup_resource(), ldlm_cancel_resource_local(), ldlm_lock_change_resource(), ldlm_lock_match(), ldlm_reprocess_all(), ldlm_res_hash_dump(), ldlm_resource_complain(), ldlm_resource_foreach(), lock_res_and_lock(), mdc_null_inode(), ofd_intent_policy(), ofd_lvbo_fill(), ofd_lvbo_update(), osc_ldlm_resource_invalidate(), and qmt_glimpse_lock().
struct ldlm_resource* lock_res_and_lock (struct ldlm_lock * lock) [read]
Lock a lock and its resource.
LDLM locking uses resource to serialize access to locks but there is a case when we change resource of lock upon enqueue reply. We rely on lock->l_resource = new_res being an atomic operation.
Definition at line 51 of file l_lock.c.
References ldlm_lock::l_lock, ldlm_lock::l_resource, ldlm_is_ns_srv, ldlm_set_res_locked, and lock_res().
Referenced by __ldlm_handle2lock(), failed_lock_cleanup(), is_bl_done(), is_granted_or_cancelled(), ldlm_blocking_ast(), ldlm_callback_handler(), ldlm_cancel_callback(), ldlm_cancel_no_wait_policy(), ldlm_cli_cancel(), ldlm_cli_cancel_local(), ldlm_cli_enqueue_fini(), ldlm_flock_blocking_ast(), ldlm_flock_completion_ast(), ldlm_flock_interrupted_wait(), ldlm_handle_bl_callback(), ldlm_handle_cp_callback(), ldlm_handle_gl_callback(), ldlm_lock_addref_internal(), ldlm_lock_addref_try(), ldlm_lock_allow_match(), ldlm_lock_cancel(), ldlm_lock_change_resource(), ldlm_lock_convert(), ldlm_lock_decref_and_cancel(), ldlm_lock_decref_internal(), ldlm_lock_destroy(), ldlm_lock_downgrade(), ldlm_lock_enqueue(), ldlm_lock_fail_match(), ldlm_prepare_lru_list(), ldlm_process_flock_lock(), ldlm_revalidate_lock_handle(), ldlm_work_bl_ast_lock(), ldlm_work_cp_ast_lock(), ll_file_ioctl(), ll_inode_from_resource_lock(), ll_layout_fetch(), ll_layout_lock_set(), ll_lease_close(), mdc_finish_enqueue(), mdc_set_lock_data(), mdt_blocking_ast(), mdt_close_swap_layouts(), mdt_hsm_release(), mdt_intent_lock_replace(), mdt_lock_objects_in_linkea(), mdt_reint_migrate_internal(), mgs_completion_ast_generic(), osc_dlm_blocking_ast0(), osc_ldlm_glimpse_ast(), osc_lock_granted(), osc_lock_upcall_agl(), osc_set_lock_data(), qsd_glb_ast_data_get(), qsd_id_ast_data_get(), tgt_cancel_slc_locks(), tgt_discard_slc_lock(), and tgt_save_slc_lock().
static void lock_res_nested (struct ldlm_resource * res, enum lock_res_type mode) [inline, static]
Lock resource with a way to instruct lockdep code about nestedness-safe.
Definition at line 1543 of file lustre_dlm.h.
References ldlm_resource::lr_lock.
Referenced by ldlm_lock_change_resource().
static int lockmode_compat (enum ldlm_mode exist_mode, enum ldlm_mode new_mode) [inline, static]
Definition at line 157 of file lustre_dlm.h.
References lck_compat_array.
Referenced by ldlm_cancel_resource_local(), and ldlm_process_flock_lock().
static void lockmode_verify (enum ldlm_mode mode) [inline, static]
Definition at line 152 of file lustre_dlm.h.
References LASSERT, LCK_MAXMODE, and LCK_MINMODE.
Referenced by ldlm_process_flock_lock().
static int ns_connect_cancelset (struct ldlm_namespace * ns) [inline, static]
Returns 1 if namespace ns supports early lock cancel (ELC).
Definition at line 544 of file lustre_dlm.h.
References LASSERT, ldlm_namespace::ns_connect_flags, and OBD_CONNECT_CANCELSET.
Referenced by ldlm_prep_elc_req(), mdc_resource_get_unused(), and osc_resource_get_unused().
static int ns_connect_lru_resize (struct ldlm_namespace * ns) [inline, static]
Returns 1 if this namespace supports lru_resize.
Definition at line 553 of file lustre_dlm.h.
References LASSERT, ldlm_namespace::ns_connect_flags, and OBD_CONNECT_LRU_RESIZE.
Referenced by ldlm_cancel_lru_policy(), ldlm_cli_cancel(), ldlm_lock_decref_internal(), ldlm_prep_elc_req(), and ldlm_prepare_lru_list().
static int ns_is_client (struct ldlm_namespace * ns) [inline, static]
Returns 1 if namespace ns is a client namespace.
Definition at line 518 of file lustre_dlm.h.
References LASSERT, LDLM_NAMESPACE_CLIENT, LDLM_NAMESPACE_SERVER, and ldlm_namespace::ns_client.
Referenced by cleanup_resource(), ldlm_cli_cancel_local(), ldlm_cli_convert_local(), ldlm_cli_enqueue_local(), ldlm_completion_ast(), ldlm_lock_change_resource(), ldlm_lock_convert(), ldlm_lock_decref_internal(), ldlm_lock_enqueue(), ldlm_namespace_dump(), ldlm_process_flock_lock(), ldlm_reprocess_all(), and ldlm_resource_get().
static int ns_is_server (struct ldlm_namespace * ns) [inline, static]
Returns 1 if namespace ns is a server namespace.
Definition at line 531 of file lustre_dlm.h.
References LASSERT, LDLM_NAMESPACE_CLIENT, LDLM_NAMESPACE_SERVER, and ldlm_namespace::ns_client.
Referenced by ldlm_lock_create().
static void ns_register_cancel (struct ldlm_namespace * ns, ldlm_cancel_cbt arg) [inline, static]
Definition at line 559 of file lustre_dlm.h.
References LASSERT, and ldlm_namespace::ns_cancel.
Referenced by mdc_setup(), osc_setup(), and osp_init0().
static void unlock_res (struct ldlm_resource * res) [inline, static]
Unlock resource.
Definition at line 1550 of file lustre_dlm.h.
References ldlm_resource::lr_lock.
Referenced by cleanup_resource(), ldlm_cancel_resource_local(), ldlm_lock_change_resource(), ldlm_lock_match(), ldlm_reprocess_all(), ldlm_res_hash_dump(), ldlm_resource_complain(), ldlm_resource_foreach(), mdc_null_inode(), ofd_intent_policy(), ofd_lvbo_fill(), ofd_lvbo_update(), osc_ldlm_resource_invalidate(), qmt_glimpse_lock(), and unlock_res_and_lock().
void unlock_res_and_lock (struct ldlm_lock * lock)
Unlock a lock and its resource previously locked with lock_res_and_lock.
Definition at line 67 of file l_lock.c.
References ldlm_lock::l_lock, ldlm_lock::l_resource, ldlm_clear_res_locked, ldlm_is_ns_srv, and unlock_res().
Referenced by __ldlm_handle2lock(), failed_lock_cleanup(), is_bl_done(), is_granted_or_cancelled(), ldlm_blocking_ast(), ldlm_blocking_ast_nocheck(), ldlm_callback_handler(), ldlm_cancel_callback(), ldlm_cancel_no_wait_policy(), ldlm_cli_cancel(), ldlm_cli_cancel_local(), ldlm_cli_enqueue_fini(), ldlm_flock_blocking_ast(), ldlm_flock_completion_ast(), ldlm_flock_interrupted_wait(), ldlm_handle_bl_callback(), ldlm_handle_cp_callback(), ldlm_handle_gl_callback(), ldlm_lock_addref_internal(), ldlm_lock_addref_try(), ldlm_lock_allow_match(), ldlm_lock_cancel(), ldlm_lock_change_resource(), ldlm_lock_decref_and_cancel(), ldlm_lock_decref_internal(), ldlm_lock_destroy(), ldlm_lock_downgrade(), ldlm_lock_fail_match(), ldlm_prepare_lru_list(), ldlm_process_flock_lock(), ldlm_revalidate_lock_handle(), ldlm_work_bl_ast_lock(), ldlm_work_cp_ast_lock(), ll_file_ioctl(), ll_inode_from_resource_lock(), ll_layout_fetch(), ll_layout_lock_set(), ll_lease_close(), mdc_finish_enqueue(), mdc_set_lock_data(), mdt_blocking_ast(), mdt_close_swap_layouts(), mdt_hsm_release(), mdt_intent_lock_replace(), mdt_lock_objects_in_linkea(), mdt_reint_migrate_internal(), mgs_completion_ast_generic(), osc_dlm_blocking_ast0(), osc_ldlm_glimpse_ast(), osc_lock_granted(), osc_lock_upcall_agl(), osc_set_lock_data(), qsd_glb_ast_data_get(), qsd_id_ast_data_get(), tgt_cancel_slc_locks(), tgt_discard_slc_lock(), and tgt_save_slc_lock().
Variable Documentation
enum ldlm_mode lck_compat_array[]
Definition at line 2952 of file ldlm_lib.c.
Referenced by lockmode_compat().
char* ldlm_lockname[]
Definition at line 52 of file ldlm_lock.c.
Referenced by _ldlm_lock_debug(), ldlm_cli_enqueue_fini(), ldlm_lock_addref_internal_nolock(), ldlm_lock_decref_and_cancel(), ldlm_lock_decref_internal_nolock(), and ll_have_md_lock().
struct obd_ops ldlm_obd_ops
char* ldlm_typename[]
Definition at line 65 of file ldlm_lock.c.
Referenced by _ldlm_lock_debug().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.