Lustre: lov
lov
Logical object volume layer.
Data Structures
struct lov_device_emerg
Resources that are used in memory-cleaning path, and whose allocation cannot fail even when memory is tight.
struct lov_device
struct lov_object
lov-specific file state.
struct lov_lock_sub
State lov_lock keeps for each sub-lock.
struct lov_lock
lov-specific lock state.
struct lov_page
struct lovsub_device
struct lovsub_object
struct lov_lock_link
A link between a top-lock and a sub-lock.
struct lovsub_lock
Lock state at lovsub layer.
struct lov_sublock_env
Describe the environment settings for sublocks.
struct lovsub_page
struct lov_thread_info
struct lov_io_sub
State that lov_io maintains for every sub-io.
struct lov_io
IO state private for LOV.
struct lov_session
struct lov_layout_operations
Defines
#define lov_foreach_target(lov, var) for (var = 0; var < lov_targets_nr(lov); ++var)
#define LOV_EMPTY_IMPOSSIBLE ((void *)lov_empty_impossible)
#define LOV_2DISPATCH_NOLOCK(obj, op,...)
Performs a double-dispatch based on the layout type of an object.
#define LOV_2DISPATCH_MAYLOCK(obj, op, lock,...)
#define LOV_2DISPATCH(obj, op,...) LOV_2DISPATCH_MAYLOCK(obj, op, 1, __VA_ARGS__)
Performs a locked double-dispatch based on the layout type of an object.
#define LOV_2DISPATCH_VOID(obj, op,...)
#define FIEMAP_BUFFER_SIZE 4096
#define LUSTRE_LOVSUB_NAME "lovsub"
Enumerations
enum lov_device_flags { LOV_DEV_INITIALIZED = 1 << 0 }
enum lov_layout_type { LLT_EMPTY, LLT_RAID0, LLT_RELEASED, LLT_NR }
Layout type.
Functions
static char * llt2str (enum lov_layout_type llt)
int lov_object_init (const struct lu_env *env, struct lu_object *obj, const struct lu_object_conf *conf)
int lovsub_object_init (const struct lu_env *env, struct lu_object *obj, const struct lu_object_conf *conf)
int lov_lock_init (const struct lu_env *env, struct cl_object *obj, struct cl_lock *lock, const struct cl_io *io)
int lov_io_init (const struct lu_env *env, struct cl_object *obj, struct cl_io *io)
Implements cl_object_operations::clo_io_init() method for lov layer.
int lovsub_lock_init (const struct lu_env *env, struct cl_object *obj, struct cl_lock *lock, const struct cl_io *io)
int lov_lock_init_raid0 (const struct lu_env *env, struct cl_object *obj, struct cl_lock *lock, const struct cl_io *io)
int lov_lock_init_empty (const struct lu_env *env, struct cl_object *obj, struct cl_lock *lock, const struct cl_io *io)
int lov_io_init_raid0 (const struct lu_env *env, struct cl_object *obj, struct cl_io *io)
int lov_io_init_empty (const struct lu_env *env, struct cl_object *obj, struct cl_io *io)
int lov_io_init_released (const struct lu_env *env, struct cl_object *obj, struct cl_io *io)
void lov_lock_unlink (const struct lu_env *env, struct lov_lock_link *link, struct lovsub_lock *sub)
struct lov_io_sub * lov_sub_get (const struct lu_env *env, struct lov_io *lio, int stripe)
void lov_sub_put (struct lov_io_sub *sub)
int lov_sublock_modify (const struct lu_env *env, struct lov_lock *lov, struct lovsub_lock *sublock, const struct cl_lock_descr *d, int idx)
int lov_page_init (const struct lu_env *env, struct cl_object *ob, struct cl_page *page, pgoff_t index)
int lovsub_page_init (const struct lu_env *env, struct cl_object *ob, struct cl_page *page, pgoff_t index)
int lov_page_init_empty (const struct lu_env *env, struct cl_object *obj, struct cl_page *page, pgoff_t index)
int lov_page_init_raid0 (const struct lu_env *env, struct cl_object *obj, struct cl_page *page, pgoff_t index)
struct lu_object * lov_object_alloc (const struct lu_env *env, const struct lu_object_header *hdr, struct lu_device *dev)
struct lu_object * lovsub_object_alloc (const struct lu_env *env, const struct lu_object_header *hdr, struct lu_device *dev)
struct lov_lock_link * lov_lock_link_find (const struct lu_env *env, struct lov_lock *lck, struct lovsub_lock *sub)
struct lov_io_sub * lov_page_subio (const struct lu_env *env, struct lov_io *lio, const struct cl_page_slice *slice)
struct lov_stripe_md * lov_lsm_addref (struct lov_object *lov)
int lov_page_stripe (const struct cl_page *page)
static struct lov_session * lov_env_session (const struct lu_env *env)
static struct lov_io * lov_env_io (const struct lu_env *env)
static int lov_is_object (const struct lu_object *obj)
static int lovsub_is_object (const struct lu_object *obj)
static struct lu_device * lov2lu_dev (struct lov_device *lov)
static struct lov_device * lu2lov_dev (const struct lu_device *d)
static struct cl_device * lovsub2cl_dev (struct lovsub_device *lovsub)
static struct lu_device * lovsub2lu_dev (struct lovsub_device *lovsub)
static struct lovsub_device * lu2lovsub_dev (const struct lu_device *d)
static struct lovsub_device * cl2lovsub_dev (const struct cl_device *d)
static struct lu_object * lov2lu (struct lov_object *lov)
static struct cl_object * lov2cl (struct lov_object *lov)
static struct lov_object * lu2lov (const struct lu_object *obj)
static struct lov_object * cl2lov (const struct cl_object *obj)
static struct lu_object * lovsub2lu (struct lovsub_object *los)
static struct cl_object * lovsub2cl (struct lovsub_object *los)
static struct lovsub_object * cl2lovsub (const struct cl_object *obj)
static struct lovsub_object * lu2lovsub (const struct lu_object *obj)
static struct lovsub_lock * cl2lovsub_lock (const struct cl_lock_slice *slice)
static struct lovsub_lock * cl2sub_lock (const struct cl_lock *lock)
static struct lov_lock * cl2lov_lock (const struct cl_lock_slice *slice)
static struct lov_page * cl2lov_page (const struct cl_page_slice *slice)
static struct lovsub_page * cl2lovsub_page (const struct cl_page_slice *slice)
static struct lov_io * cl2lov_io (const struct lu_env *env, const struct cl_io_slice *ios)
static int lov_targets_nr (const struct lov_device *lov)
static struct lov_thread_info * lov_env_info (const struct lu_env *env)
static struct lov_layout_raid0 * lov_r0 (struct lov_object *lov)
int lov_getstripe (struct lov_object *obj, struct lov_stripe_md *lsm, struct lov_user_md __user *lump)
static void lov_sub_enter (struct lov_io_sub *sub)
static void lov_sub_exit (struct lov_io_sub *sub)
static void lov_io_sub_fini (const struct lu_env *env, struct lov_io *lio, struct lov_io_sub *sub)
static void lov_io_sub_inherit (struct cl_io *io, struct lov_io *lio, int stripe, loff_t start, loff_t end)
static int lov_io_sub_init (const struct lu_env *env, struct lov_io *lio, struct lov_io_sub *sub)
static int lov_io_subio_init (const struct lu_env *env, struct lov_io *lio, struct cl_io *io)
static int lov_io_slice_init (struct lov_io *lio, struct lov_object *obj, struct cl_io *io)
static void lov_io_fini (const struct lu_env *env, const struct cl_io_slice *ios)
static loff_t lov_offset_mod (loff_t val, int delta)
static int lov_io_iter_init (const struct lu_env *env, const struct cl_io_slice *ios)
static int lov_io_rw_iter_init (const struct lu_env *env, const struct cl_io_slice *ios)
static int lov_io_call (const struct lu_env *env, struct lov_io *lio, int(*iofunc)(const struct lu_env *, struct cl_io *))
static int lov_io_lock (const struct lu_env *env, const struct cl_io_slice *ios)
static int lov_io_start (const struct lu_env *env, const struct cl_io_slice *ios)
static int lov_io_end_wrapper (const struct lu_env *env, struct cl_io *io)
static int lov_io_iter_fini_wrapper (const struct lu_env *env, struct cl_io *io)
static int lov_io_unlock_wrapper (const struct lu_env *env, struct cl_io *io)
static void lov_io_end (const struct lu_env *env, const struct cl_io_slice *ios)
static void lov_io_data_version_end (const struct lu_env *env, const struct cl_io_slice *ios)
static void lov_io_iter_fini (const struct lu_env *env, const struct cl_io_slice *ios)
static void lov_io_unlock (const struct lu_env *env, const struct cl_io_slice *ios)
static int lov_io_read_ahead (const struct lu_env *env, const struct cl_io_slice *ios, pgoff_t start, struct cl_read_ahead *ra)
static int lov_io_submit (const struct lu_env *env, const struct cl_io_slice *ios, enum cl_req_type crt, struct cl_2queue *queue)
lov implementation of cl_operations::cio_submit() method.
static int lov_io_commit_async (const struct lu_env *env, const struct cl_io_slice *ios, struct cl_page_list *queue, int from, int to, cl_commit_cbt cb)
static int lov_io_fault_start (const struct lu_env *env, const struct cl_io_slice *ios)
static void lov_io_fsync_end (const struct lu_env *env, const struct cl_io_slice *ios)
static void lov_empty_io_fini (const struct lu_env *env, const struct cl_io_slice *ios)
static int lov_empty_io_submit (const struct lu_env *env, const struct cl_io_slice *ios, enum cl_req_type crt, struct cl_2queue *queue)
static void lov_empty_impossible (const struct lu_env *env, struct cl_io_slice *ios)
static struct lov_sublock_env * lov_sublock_env_get (const struct lu_env *env, const struct cl_lock *parent, struct lov_lock_sub *lls)
static void lov_sublock_env_put (struct lov_sublock_env *subenv)
static int lov_sublock_init (const struct lu_env *env, const struct cl_lock *parent, struct lov_lock_sub *lls)
static struct lov_lock * lov_lock_sub_init (const struct lu_env *env, const struct cl_object *obj, struct cl_lock *lock)
Creates sub-locks for a given lov_lock for the first time.
static void lov_lock_fini (const struct lu_env *env, struct cl_lock_slice *slice)
static int lov_lock_enqueue (const struct lu_env *env, const struct cl_lock_slice *slice, struct cl_io *io, struct cl_sync_io *anchor)
Implementation of cl_lock_operations::clo_enqueue() for lov layer.
static void lov_lock_cancel (const struct lu_env *env, const struct cl_lock_slice *slice)
static int lov_lock_print (const struct lu_env *env, void *cookie, lu_printer_t p, const struct cl_lock_slice *slice)
static void lov_empty_lock_fini (const struct lu_env *env, struct cl_lock_slice *slice)
static int lov_empty_lock_print (const struct lu_env *env, void *cookie, lu_printer_t p, const struct cl_lock_slice *slice)
static int lov_layout_wait (const struct lu_env *env, struct lov_object *lov)
static void lov_lsm_put (struct lov_stripe_md *lsm)
static void lov_install_empty (const struct lu_env *env, struct lov_object *lov, union lov_layout_state *state)
static int lov_init_empty (const struct lu_env *env, struct lov_device *dev, struct lov_object *lov, struct lov_stripe_md *lsm, const struct cl_object_conf *conf, union lov_layout_state *state)
static void lov_install_raid0 (const struct lu_env *env, struct lov_object *lov, union lov_layout_state *state)
static struct cl_object * lov_sub_find (const struct lu_env *env, struct cl_device *dev, const struct lu_fid *fid, const struct cl_object_conf *conf)
static int lov_init_sub (const struct lu_env *env, struct lov_object *lov, struct cl_object *stripe, struct lov_layout_raid0 *r0, int idx)
static int lov_page_slice_fixup (struct lov_object *lov, struct cl_object *stripe)
static int lov_init_raid0 (const struct lu_env *env, struct lov_device *dev, struct lov_object *lov, struct lov_stripe_md *lsm, const struct cl_object_conf *conf, union lov_layout_state *state)
static int lov_init_released (const struct lu_env *env, struct lov_device *dev, struct lov_object *lov, struct lov_stripe_md *lsm, const struct cl_object_conf *conf, union lov_layout_state *state)
static struct cl_object * lov_find_subobj (const struct lu_env *env, struct lov_object *lov, struct lov_stripe_md *lsm, int stripe_idx)
static int lov_delete_empty (const struct lu_env *env, struct lov_object *lov, union lov_layout_state *state)
static void lov_subobject_kill (const struct lu_env *env, struct lov_object *lov, struct lovsub_object *los, int idx)
static int lov_delete_raid0 (const struct lu_env *env, struct lov_object *lov, union lov_layout_state *state)
static void lov_fini_empty (const struct lu_env *env, struct lov_object *lov, union lov_layout_state *state)
static void lov_fini_raid0 (const struct lu_env *env, struct lov_object *lov, union lov_layout_state *state)
static void lov_fini_released (const struct lu_env *env, struct lov_object *lov, union lov_layout_state *state)
static int lov_print_empty (const struct lu_env *env, void *cookie, lu_printer_t p, const struct lu_object *o)
static int lov_print_raid0 (const struct lu_env *env, void *cookie, lu_printer_t p, const struct lu_object *o)
static int lov_print_released (const struct lu_env *env, void *cookie, lu_printer_t p, const struct lu_object *o)
static int lov_attr_get_empty (const struct lu_env *env, struct cl_object *obj, struct cl_attr *attr)
Implements cl_object_operations::coo_attr_get() method for an object without stripes (LLT_EMPTY layout type).
static int lov_attr_get_raid0 (const struct lu_env *env, struct cl_object *obj, struct cl_attr *attr)
static enum lov_layout_type lov_type (struct lov_stripe_md *lsm)
Return lov_layout_type associated with a given lsm.
static void lov_conf_freeze (struct lov_object *lov)
static void lov_conf_thaw (struct lov_object *lov)
static void lov_conf_lock (struct lov_object *lov)
static void lov_conf_unlock (struct lov_object *lov)
static int lov_layout_change (const struct lu_env *unused, struct lov_object *lov, struct lov_stripe_md *lsm, const struct cl_object_conf *conf)
static int lov_conf_set (const struct lu_env *env, struct cl_object *obj, const struct cl_object_conf *conf)
static void lov_object_delete (const struct lu_env *env, struct lu_object *obj)
static void lov_object_free (const struct lu_env *env, struct lu_object *obj)
static int lov_object_print (const struct lu_env *env, void *cookie, lu_printer_t p, const struct lu_object *o)
static int lov_attr_get (const struct lu_env *env, struct cl_object *obj, struct cl_attr *attr)
An implementation of cl_object_operations::clo_attr_get() method for lov layer.
static int lov_attr_update (const struct lu_env *env, struct cl_object *obj, const struct cl_attr *attr, unsigned valid)
static int fiemap_calc_last_stripe (struct lov_stripe_md *lsm, loff_t fm_start, loff_t fm_end, int start_stripe, int *stripe_count)
We calculate on which OST the mapping will end.
static void fiemap_prepare_and_copy_exts (struct fiemap *fiemap, struct fiemap_extent *lcl_fm_ext, int ost_index, unsigned int ext_count, int current_extent)
Set fe_device and copy extents from local buffer into main return buffer.
static loff_t fiemap_calc_fm_end_offset (struct fiemap *fiemap, struct lov_stripe_md *lsm, loff_t fm_start, loff_t fm_end, int *start_stripe)
Non-zero fe_logical indicates that this is a continuation FIEMAP call.
static int lov_object_fiemap (const struct lu_env *env, struct cl_object *obj, struct ll_fiemap_info_key *fmkey, struct fiemap *fiemap, size_t *buflen)
Break down the FIEMAP request and send appropriate calls to individual OSTs.
static int lov_object_getstripe (const struct lu_env *env, struct cl_object *obj, struct lov_user_md __user *lum)
static int lov_object_layout_get (const struct lu_env *env, struct cl_object *obj, struct cl_layout *cl)
static loff_t lov_object_maxbytes (struct cl_object *obj)
int lov_read_and_clear_async_rc (struct cl_object *clob)
static int lov_raid0_page_print (const struct lu_env *env, const struct cl_page_slice *slice, void *cookie, lu_printer_t printer)
static int lov_empty_page_print (const struct lu_env *env, const struct cl_page_slice *slice, void *cookie, lu_printer_t printer)
static int lovsub_device_init (const struct lu_env *env, struct lu_device *d, const char *name, struct lu_device *next)
static struct lu_device * lovsub_device_fini (const struct lu_env *env, struct lu_device *d)
static struct lu_device * lovsub_device_free (const struct lu_env *env, struct lu_device *d)
static struct lu_device * lovsub_device_alloc (const struct lu_env *env, struct lu_device_type *t, struct lustre_cfg *cfg)
static void lovsub_lock_fini (const struct lu_env *env, struct cl_lock_slice *slice)
static void lovsub_object_free (const struct lu_env *env, struct lu_object *obj)
static int lovsub_object_print (const struct lu_env *env, void *cookie, lu_printer_t p, const struct lu_object *obj)
static int lovsub_attr_update (const struct lu_env *env, struct cl_object *obj, const struct cl_attr *attr, unsigned valid)
static int lovsub_object_glimpse (const struct lu_env *env, const struct cl_object *obj, struct ost_lvb *lvb)
static void lovsub_req_attr_set (const struct lu_env *env, struct cl_object *obj, struct cl_req_attr *attr)
Implementation of struct cl_object_operations::coo_req_attr_set() for lovsub layer.
static void lovsub_page_fini (const struct lu_env *env, struct cl_page_slice *slice)
Variables
struct lu_device_type lov_device_type
struct lu_device_type lovsub_device_type
struct lu_context_key lov_key
struct lu_context_key lov_session_key
struct kmem_cache * lov_lock_kmem
struct kmem_cache * lov_object_kmem
struct kmem_cache * lov_thread_kmem
struct kmem_cache * lov_session_kmem
struct kmem_cache * lovsub_lock_kmem
struct kmem_cache * lovsub_object_kmem
struct kmem_cache * lov_lock_link_kmem
static struct cl_io_operations lov_io_ops
static struct cl_io_operations lov_empty_io_ops
An io operation vector for files without stripes.
static struct cl_lock_operations lov_lock_ops
static struct cl_lock_operations lov_empty_lock_ops
static const struct
lov_layout_operations lov_dispatch []
static struct cl_object_operations lov_ops
static struct lu_object_operations lov_lu_obj_ops
static struct cl_page_operations lov_raid0_page_ops
static struct cl_page_operations lov_empty_page_ops
static struct lu_device_operations lovsub_lu_ops
static struct
lu_device_type_operations lovsub_device_type_ops
struct lu_device_type lovsub_device_type
static struct cl_lock_operations lovsub_lock_ops
static struct cl_object_operations lovsub_ops
static struct lu_object_operations lovsub_lu_obj_ops
static struct cl_page_operations lovsub_page_ops
Detailed Description
Logical object volume layer.
This layer implements data striping (raid0).
At the lov layer top-entity (object, page, lock, io) is connected to one or more sub-entities: top-object, representing a file is connected to a set of sub-objects, each representing a stripe, file-level top-lock is connected to a set of per-stripe sub-locks, top-page is connected to a (single) sub-page, and a top-level IO is connected to a set of (potentially concurrent) sub-IO's.
Sub-object, sub-page, and sub-io have well-defined top-object and top-page respectively, while a single sub-lock can be part of multiple top-locks.
Reference counting models are different for different types of entities:
top-object keeps a reference to its sub-objects, and destroys them when it is destroyed.
top-page keeps a reference to its sub-page, and destroys it when it is destroyed.
IO's are not reference counted.
To implement a connection between top and sub entities, lov layer is split into two pieces: lov ("upper half"), and lovsub ("bottom half"), both implementing full set of cl-interfaces. For example, top-object has vvp and lov layers, and it's sub-object has lovsub and osc layers. lovsub layer is used to track child-parent relationship.
Define Documentation
#define FIEMAP_BUFFER_SIZE 4096
Definition at line 1052 of file lov_object.c.
Referenced by lov_object_fiemap().
#define LOV_2DISPATCH (obj, op, ...) LOV_2DISPATCH_MAYLOCK(obj, op, 1, __VA_ARGS__)
Performs a locked double-dispatch based on the layout type of an object.
Definition at line 684 of file lov_object.c.
#define LOV_2DISPATCH_MAYLOCK (obj, op, lock, ...)
Value:
({                                                                      \
        struct lov_object                      *__obj = (obj);          \
        int                                     __lock = !!(lock);      \
        typeof(lov_dispatch[0].op(__VA_ARGS__)) __result;               \
                                                                        \
        if (__lock)                                                     \
                lov_conf_freeze(__obj);                                 \
        __result = LOV_2DISPATCH_NOLOCK(obj, op, __VA_ARGS__);          \
        if (__lock)                                                     \
                lov_conf_thaw(__obj);                                   \
        __result;                                                       \
})
Definition at line 667 of file lov_object.c.
Referenced by lov_io_init().
#define LOV_2DISPATCH_NOLOCK (obj, op, ...)
Value:
({                                                                      \
        struct lov_object                      *__obj = (obj);          \
        enum lov_layout_type                    __llt;                  \
                                                                        \
        __llt = __obj->lo_type;                                         \
        LASSERT(0 <= __llt && __llt < ARRAY_SIZE(lov_dispatch));        \
        lov_dispatch[__llt].op(__VA_ARGS__);                            \
})
Performs a double-dispatch based on the layout type of an object.
Definition at line 633 of file lov_object.c.
Referenced by lov_attr_get(), lov_lock_init(), lov_object_print(), and lov_page_init().
#define LOV_2DISPATCH_VOID (obj, op, ...)
Value:
do {                                                                    \
        struct lov_object                      *__obj = (obj);          \
        enum lov_layout_type                    __llt;                  \
                                                                        \
        lov_conf_freeze(__obj);                                         \
        __llt = __obj->lo_type;                                         \
        LASSERT(0 <= __llt && __llt < ARRAY_SIZE(lov_dispatch));        \
        lov_dispatch[__llt].op(__VA_ARGS__);                            \
        lov_conf_thaw(__obj);                                           \
} while (0)
Definition at line 687 of file lov_object.c.
Referenced by lov_object_delete(), and lov_object_free().
#define LOV_EMPTY_IMPOSSIBLE ((void *)lov_empty_impossible)
Definition at line 991 of file lov_io.c.
#define lov_foreach_target (lov, var) for (var = 0; var < lov_targets_nr(lov); ++var)
Definition at line 553 of file lov_cl_internal.h.
Referenced by lov_device_fini(), and lov_device_init().
#define LUSTRE_LOVSUB_NAME "lovsub"
Definition at line 143 of file lovsub_dev.c.
Enumeration Type Documentation
enum lov_device_flags
Enumerator:
LOV_DEV_INITIALIZED
Definition at line 90 of file lov_cl_internal.h.
enum lov_layout_type
Layout type.
Enumerator:
LLT_EMPTY
LLT_RAID0
empty file without body (mknod + truncate)
LLT_RELEASED
striped file
LLT_NR
file with no objects (data in HSM)
Definition at line 150 of file lov_cl_internal.h.
Function Documentation
static struct lov_object* cl2lov (const struct cl_object * obj) [static, read]
Definition at line 637 of file lov_cl_internal.h.
References cl_object::co_lu, LINVRNT, lov_object::lo_cl, and lov_is_object().
Referenced by lov_attr_get(), lov_attr_get_raid0(), lov_conf_set(), lov_empty_io_fini(), lov_init_sub(), lov_io_fini(), lov_io_init(), lov_io_init_empty(), lov_io_init_raid0(), lov_io_init_released(), lov_lock_init(), lov_lock_sub_init(), lov_object_fiemap(), lov_object_getstripe(), lov_object_layout_get(), lov_object_maxbytes(), lov_page_init(), lov_page_init_raid0(), and lov_page_subio().
static struct lov_io* cl2lov_io (const struct lu_env * env, const struct cl_io_slice * ios) [static, read]
Definition at line 700 of file lov_cl_internal.h.
References LASSERT, lov_io::lis_cl, and lov_env_io().
Referenced by lov_io_commit_async(), lov_io_data_version_end(), lov_io_end(), lov_io_fault_start(), lov_io_fini(), lov_io_fsync_end(), lov_io_iter_fini(), lov_io_iter_init(), lov_io_lock(), lov_io_read_ahead(), lov_io_rw_iter_init(), lov_io_start(), lov_io_submit(), and lov_io_unlock().
static struct lov_lock* cl2lov_lock (const struct cl_lock_slice * slice) [static, read]
Definition at line 681 of file lov_cl_internal.h.
References cl_lock_slice::cls_obj, cl_object::co_lu, LINVRNT, lov_lock::lls_cl, and lov_is_object().
Referenced by lov_empty_lock_fini(), lov_lock_cancel(), lov_lock_enqueue(), lov_lock_fini(), and lov_lock_print().
static struct lov_page* cl2lov_page (const struct cl_page_slice * slice) [static, read]
Definition at line 687 of file lov_cl_internal.h.
References cl_object::co_lu, cl_page_slice::cpl_obj, LINVRNT, lov_is_object(), and lov_page::lps_cl.
Referenced by lov_empty_page_print(), lov_page_stripe(), and lov_raid0_page_print().
static struct lovsub_object* cl2lovsub (const struct cl_object * obj) [static, read]
Definition at line 653 of file lov_cl_internal.h.
References cl_object::co_lu, LINVRNT, lovsub_is_object(), and lovsub_object::lso_cl.
Referenced by lov_init_sub(), lovsub_attr_update(), lovsub_object_glimpse(), and lovsub_req_attr_set().
static struct lovsub_device* cl2lovsub_dev (const struct cl_device * d) [static, read]
Definition at line 615 of file lov_cl_internal.h.
References lovsub_device::acid_cl, cl_device::cd_lu_dev, lu_device::ld_type, LINVRNT, and lovsub_device_type.
Referenced by lov_cl_add_target(), and lov_device_init().
static struct lovsub_lock* cl2lovsub_lock (const struct cl_lock_slice * slice) [static, read]
Definition at line 666 of file lov_cl_internal.h.
References cl_lock_slice::cls_obj, cl_object::co_lu, LINVRNT, lovsub_is_object(), and lovsub_lock::lss_cl.
Referenced by cl2sub_lock(), and lovsub_lock_fini().
static struct lovsub_page* cl2lovsub_page (const struct cl_page_slice * slice) [static, read]
Definition at line 694 of file lov_cl_internal.h.
References cl_object::co_lu, cl_page_slice::cpl_obj, LINVRNT, lovsub_is_object(), and lovsub_page::lsb_cl.
static struct lovsub_lock* cl2sub_lock (const struct cl_lock * lock) [static, read]
Definition at line 672 of file lov_cl_internal.h.
References cl2lovsub_lock(), cl_lock_at(), LASSERT, and lovsub_device_type.
static loff_t fiemap_calc_fm_end_offset (struct fiemap * fiemap, struct lov_stripe_md * lsm, loff_t fm_start, loff_t fm_end, int * start_stripe) [static]
Non-zero fe_logical indicates that this is a continuation FIEMAP call.
The local end offset and the device are sent in the first fm_extent. This function calculates the stripe number from the index. This function returns a stripe_no on which mapping is to be restarted.
This function returns fm_end_offset which is the in-OST offset at which mapping should be restarted. If fm_end_offset=0 is returned then caller will re-calculate proper offset in next stripe. Note that the first extent is passed to lov_get_info via the value field.
Parameters:
fiemap [in] fiemap request header
lsm [in] striping information for the file
fm_start [in] logical start of mapping
fm_end [in] logical end of mapping
start_stripe [out] starting stripe will be returned in this
Definition at line 1071 of file lov_object.c.
References lov_oinfo::loi_ost_idx, lov_oinfo_is_dummy(), lov_stripe_intersects(), lov_stripe_md::lsm_oinfo, and lov_stripe_md::lsm_stripe_count.
Referenced by lov_object_fiemap().
static int fiemap_calc_last_stripe (struct lov_stripe_md * lsm, loff_t fm_start, loff_t fm_end, int start_stripe, int * stripe_count) [static]
We calculate on which OST the mapping will end.
If the length of mapping is greater than (stripe_size * stripe_count) then the last_stripe will will be one just before start_stripe. Else we check if the mapping intersects each OST and find last_stripe. This function returns the last_stripe and also sets the stripe_count over which the mapping is spread
Parameters:
lsm [in] striping information for the file
fm_start [in] logical start of mapping
fm_end [in] logical end of mapping
start_stripe [in] starting stripe of the mapping
stripe_count [out] the number of stripes across which to map is returned
Return values:
last_stripe return the last stripe of the mapping
Definition at line 997 of file lov_object.c.
References lov_stripe_intersects(), lov_stripe_md::lsm_stripe_count, and lov_stripe_md::lsm_stripe_size.
Referenced by lov_object_fiemap().
static void fiemap_prepare_and_copy_exts (struct fiemap * fiemap, struct fiemap_extent * lcl_fm_ext, int ost_index, unsigned int ext_count, int current_extent) [static]
Set fe_device and copy extents from local buffer into main return buffer.
Parameters:
fiemap [out] fiemap to hold all extents
lcl_fm_ext [in] array of fiemap extents get from OSC layer
ost_index [in] OST index to be written into the fm_device field for each extent
ext_count [in] number of extents to be copied
current_extent [in] where to start copying in the extent array
Definition at line 1034 of file lov_object.c.
References fiemap_count_to_size(), and FIEMAP_EXTENT_NET.
Referenced by lov_object_fiemap().
static char* llt2str (enum lov_layout_type llt) [inline, static]
Definition at line 157 of file lov_cl_internal.h.
References LBUG, LLT_EMPTY, LLT_NR, LLT_RAID0, and LLT_RELEASED.
Referenced by lov_layout_change().
static struct cl_object* lov2cl (struct lov_object * lov) [static, read]
Definition at line 626 of file lov_cl_internal.h.
References lov_object::lo_cl.
Referenced by lov_init_sub(), lov_io_read_ahead(), lov_io_sub_init(), and lov_lock_sub_init().
static struct lu_object* lov2lu (struct lov_object * lov) [static, read]
Definition at line 621 of file lov_cl_internal.h.
References cl_object::co_lu, and lov_object::lo_cl.
Referenced by lov_conf_set(), lov_find_subobj(), lov_init_sub(), lov_io_read_ahead(), lov_layout_change(), lov_layout_wait(), and lov_object_alloc().
static struct lu_device* lov2lu_dev (struct lov_device * lov) [static, read]
Definition at line 588 of file lov_cl_internal.h.
References cl_device::cd_lu_dev, and lov_device::ld_cl.
Referenced by lov_device_alloc().
static int lov_attr_get (const struct lu_env * env, struct cl_object * obj, struct cl_attr * attr) [static]
An implementation of cl_object_operations::clo_attr_get() method for lov layer.
For raid0 layout this collects and merges attributes of all sub-objects.
Definition at line 955 of file lov_object.c.
References cl2lov(), and LOV_2DISPATCH_NOLOCK.
static int lov_attr_get_empty (const struct lu_env * env, struct cl_object * obj, struct cl_attr * attr) [static]
Implements cl_object_operations::coo_attr_get() method for an object without stripes (LLT_EMPTY layout type).
The only attributes this layer is authoritative in this case is cl_attr::cat_blocks---it's 0.
Definition at line 520 of file lov_object.c.
References cl_attr::cat_blocks.
static int lov_attr_get_raid0 (const struct lu_env * env, struct cl_object * obj, struct cl_attr * attr) [static]
Definition at line 527 of file lov_object.c.
References __u64, cl_attr::cat_atime, cl_attr::cat_blocks, cl_attr::cat_ctime, cl_attr::cat_kms, cl_attr::cat_mtime, cl_attr::cat_size, cl2lov(), cl_lvb2attr(), ENTRY, lov_object::lo_lsm, lov_env_info(), lov_merge_lvb_kms(), lov_r0(), lov_stripe_lock(), lov_stripe_unlock(), lov_thread_info::lti_lvb, ost_lvb::lvb_atime, ost_lvb::lvb_ctime, ost_lvb::lvb_mtime, and RETURN.
static int lov_attr_update (const struct lu_env * env, struct cl_object * obj, const struct cl_attr * attr, unsigned valid) [static]
Definition at line 963 of file lov_object.c.
static void lov_conf_freeze (struct lov_object * lov) [inline, static]
Definition at line 655 of file lov_object.c.
References lov_object::lo_owner, and lov_object::lo_type_guard.
Referenced by lov_lsm_addref(), and lov_read_and_clear_async_rc().
static void lov_conf_lock (struct lov_object * lov) [static]
Definition at line 699 of file lov_object.c.
References LASSERT, lov_object::lo_owner, and lov_object::lo_type_guard.
Referenced by lov_conf_set().
static int lov_conf_set (const struct lu_env * env, struct cl_object * obj, const struct cl_object_conf * conf) [static]
Definition at line 843 of file lov_object.c.
References CDEBUG, cl2lov(), cl_object_conf::coc_layout, cl_object_conf::coc_opc, D_INODE, DFID, ENTRY, EXIT, GOTO, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lov_object::lo_active_ios, lov_object::lo_layout_invalid, lov_object::lo_lsm, lov2lu(), lov_conf_lock(), lov_conf_unlock(), lov_layout_change(), lov_layout_wait(), lov_lsm_put(), lov_object_dev(), lov_unpackmd(), lov_stripe_md::lsm_layout_gen, lov_stripe_md::lsm_pattern, lu_object_fid(), OBJECT_CONF_INVALIDATE, OBJECT_CONF_SET, OBJECT_CONF_WAIT, PFID, RETURN, and cl_object_conf::u.
static void lov_conf_thaw (struct lov_object * lov) [inline, static]
Definition at line 661 of file lov_object.c.
References lov_object::lo_owner, and lov_object::lo_type_guard.
Referenced by lov_lsm_addref(), and lov_read_and_clear_async_rc().
static void lov_conf_unlock (struct lov_object * lov) [static]
Definition at line 707 of file lov_object.c.
References lov_object::lo_owner, and lov_object::lo_type_guard.
Referenced by lov_conf_set().
static int lov_delete_empty (const struct lu_env * env, struct lov_object * lov, union lov_layout_state * state) [static]
Definition at line 350 of file lov_object.c.
References LASSERT, LLT_EMPTY, LLT_RELEASED, lov_object::lo_type, and lov_layout_wait().
static int lov_delete_raid0 (const struct lu_env * env, struct lov_object * lov, union lov_layout_state * state) [static]
Definition at line 406 of file lov_object.c.
References cl_object_prune(), D_INODE, dump_lsm(), ENTRY, lov_object::lo_lsm, lov_layout_wait(), lov_subobject_kill(), lovsub_object::lso_cl, and RETURN.
static void lov_empty_impossible (const struct lu_env * env, struct cl_io_slice * ios) [static]
Definition at line 985 of file lov_io.c.
References LBUG.
static void lov_empty_io_fini (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 967 of file lov_io.c.
References cl_io_slice::cis_obj, cl2lov(), ENTRY, EXIT, lov_object::lo_active_ios, and lov_object::lo_waitq.
static int lov_empty_io_submit (const struct lu_env * env, const struct cl_io_slice * ios, enum cl_req_type crt, struct cl_2queue * queue) [static]
Definition at line 978 of file lov_io.c.
static void lov_empty_lock_fini (const struct lu_env * env, struct cl_lock_slice * slice) [static]
Definition at line 336 of file lov_lock.c.
References cl2lov_lock(), lov_lock_kmem, and OBD_SLAB_FREE_PTR.
static int lov_empty_lock_print (const struct lu_env * env, void * cookie, lu_printer_t p, const struct cl_lock_slice * slice) [static]
Definition at line 343 of file lov_lock.c.
static int lov_empty_page_print (const struct lu_env * env, const struct cl_page_slice * slice, void * cookie, lu_printer_t printer) [static]
Definition at line 113 of file lov_page.c.
References cl2lov_page(), and LUSTRE_LOV_NAME.
static struct lov_thread_info* lov_env_info (const struct lu_env * env) [static, read]
Definition at line 715 of file lov_cl_internal.h.
References LASSERT, lu_env::le_ctx, lov_key, and lu_context_key_get().
Referenced by lov_attr_get_raid0(), lov_find_subobj(), lov_init_raid0(), lov_io_commit_async(), lov_io_submit(), and lov_subobject_kill().
static struct lov_io* lov_env_io (const struct lu_env * env) [static, read]
Definition at line 573 of file lov_cl_internal.h.
References lov_env_session(), and lov_session::ls_io.
Referenced by cl2lov_io(), lov_io_init(), lov_io_init_empty(), lov_io_init_raid0(), lov_io_init_released(), lov_page_init_raid0(), and lov_sublock_env_get().
static struct lov_session* lov_env_session (const struct lu_env * env) [static, read]
Definition at line 564 of file lov_cl_internal.h.
References LASSERT, lu_env::le_ses, lov_session_key, and lu_context_key_get().
Referenced by lov_env_io(), and lov_sublock_env_get().
static struct cl_object* lov_find_subobj (const struct lu_env * env, struct lov_object * lov, struct lov_stripe_md * lsm, int stripe_idx) [static, read]
Definition at line 320 of file lov_object.c.
References GOTO, lov_device::ld_target, LLT_RAID0, lov_object::lo_type, lov_oinfo::loi_oi, lov_oinfo::loi_ost_idx, lov2lu(), lov_env_info(), lov_sub_find(), lovsub2cl_dev(), lov_stripe_md::lsm_oinfo, lov_thread_info::lti_fid, lu2lov_dev(), and ostid_to_fid().
Referenced by lov_object_fiemap().
static void lov_fini_empty (const struct lu_env * env, struct lov_object * lov, union lov_layout_state * state) [static]
Definition at line 435 of file lov_object.c.
References LASSERT, LLT_EMPTY, LLT_RELEASED, and lov_object::lo_type.
static void lov_fini_raid0 (const struct lu_env * env, struct lov_object * lov, union lov_layout_state * state) [static]
Definition at line 441 of file lov_object.c.
References D_INODE, dump_lsm(), ENTRY, EXIT, lov_object::lo_lsm, lov_free_memmd(), and OBD_FREE_LARGE.
static void lov_fini_released (const struct lu_env * env, struct lov_object * lov, union lov_layout_state * state) [static]
Definition at line 458 of file lov_object.c.
References D_INODE, dump_lsm(), ENTRY, EXIT, lov_object::lo_lsm, and lov_free_memmd().
int lov_getstripe (struct lov_object * obj, struct lov_stripe_md * lsm, struct lov_user_md __user * lump)
Definition at line 324 of file lov_pack.c.
References CERROR, CLASSERT, cpu_to_le32, ENTRY, GOTO, lov_user_md_v3::lmm_layout_gen, lov_user_md_v3::lmm_magic, lov_user_md_v1::lmm_objects, lov_user_md_v3::lmm_objects, lov_mds_md_v3::lmm_stripe_count, lov_user_md_v3::lmm_stripe_count, lov_lsm_pack(), LOV_MAGIC, LOV_MAGIC_V1, LOV_MAGIC_V3, LOV_MAXPOOLNAME, lov_mds_md, lov_mds_md_size(), LOV_USER_MAGIC, LOV_USER_MAGIC_SPECIFIC, LOV_USER_MAGIC_V1, LOV_USER_MAGIC_V3, lov_user_md, lov_user_ost_data, lsm_is_released(), lov_stripe_md::lsm_magic, lov_stripe_md::lsm_stripe_count, lustre_swab_lov_mds_md(), lustre_swab_lov_user_md_objects(), OBD_ALLOC_LARGE, and OBD_FREE_LARGE.
Referenced by lov_object_getstripe().
static int lov_init_empty (const struct lu_env * env, struct lov_device * dev, struct lov_object * lov, struct lov_stripe_md * lsm, const struct cl_object_conf * conf, union lov_layout_state * state) [static]
Definition at line 108 of file lov_object.c.
static int lov_init_raid0 (const struct lu_env * env, struct lov_device * dev, struct lov_object * lov, struct lov_stripe_md * lsm, const struct cl_object_conf * conf, union lov_layout_state * state) [static]
Definition at line 222 of file lov_object.c.
References cl_object_header(), cl_object_conf::coc_inode, cl_object_conf::coc_oinfo, cl_object_header::coh_page_bufsize, D_ERROR, dump_lsm(), ENTRY, ergo, GOTO, LASSERT, LASSERTF, lov_device::ld_target, lov_object::lo_cl, lov_object::lo_layout_invalid, lov_object::lo_lsm, lov_oinfo::loi_oi, lov_oinfo::loi_ost_idx, lov_env_info(), lov_init_sub(), LOV_MAGIC_V1, LOV_MAGIC_V3, lov_oinfo_is_dummy(), lov_page_slice_fixup(), lov_sub_find(), lov_targets_nr(), lovsub2cl_dev(), lsm_addref(), lov_stripe_md::lsm_magic, lov_stripe_md::lsm_oinfo, lov_stripe_md::lsm_stripe_count, lov_thread_info::lti_fid, lov_thread_info::lti_stripe_conf, OBD_ALLOC_LARGE, ostid_to_fid(), RETURN, and cl_object_conf::u.
static int lov_init_released (const struct lu_env * env, struct lov_device * dev, struct lov_object * lov, struct lov_stripe_md * lsm, const struct cl_object_conf * conf, union lov_layout_state * state) [static]
Definition at line 306 of file lov_object.c.
References LASSERT, lov_object::lo_lsm, lsm_addref(), and lsm_is_released().
static int lov_init_sub (const struct lu_env * env, struct lov_object * lov, struct cl_object * stripe, struct lov_layout_raid0 * r0, int idx) [static]
Definition at line 135 of file lov_object.c.
References CDEBUG, cl2lov(), cl2lovsub(), cl_object_header(), cl_object_kill(), cl_object_put(), cl_object::co_lu, cl_object_header::coh_attr_guard, cl_object_header::coh_lu, cl_object_header::coh_nesting, cl_object_header::coh_parent, D_ERROR, D_INODE, DFID, DOSTID, LASSERT, lov_object::lo_layout_invalid, lov_object::lo_lsm, lu_object_header::loh_fid, lov_oinfo::loi_oi, lov_oinfo::loi_ost_gen, lov_oinfo::loi_ost_idx, lov2cl(), lov2lu(), lov_device_type, lov_stripe_md::lsm_oinfo, lu2cl(), LU_OBJECT_DEBUG, LU_OBJECT_HEADER, lu_object_locate(), lu_object_ref_add(), lu_object_unhash(), OBD_FAIL_CHECK, OBD_FAIL_LOV_INIT, PFID, and POSTID.
Referenced by lov_init_raid0().
static void lov_install_empty (const struct lu_env * env, struct lov_object * lov, union lov_layout_state * state) [static]
Definition at line 99 of file lov_object.c.
static void lov_install_raid0 (const struct lu_env * env, struct lov_object * lov, union lov_layout_state * state) [static]
Definition at line 116 of file lov_object.c.
static int lov_io_call (const struct lu_env * env, struct lov_io * lio, int(*)(const struct lu_env *, struct cl_io *) iofunc) [static]
Definition at line 517 of file lov_io.c.
References cl_io::ci_result, cl_io_slice::cis_io, ENTRY, lov_io::lis_active, lov_io::lis_cl, list_for_each_entry, lov_sub_enter(), lov_sub_exit(), RETURN, lov_io_sub::sub_env, lov_io_sub::sub_io, and lov_io_sub::sub_linkage.
Referenced by lov_io_end(), lov_io_iter_fini(), lov_io_lock(), lov_io_start(), and lov_io_unlock().
static int lov_io_commit_async (const struct lu_env * env, const struct cl_io_slice * ios, struct cl_page_list * queue, int from, int to, cl_commit_cbt cb) [static]
Definition at line 774 of file lov_io.c.
References cl2lov_io(), cl_io_commit_async(), cl_page_list_first(), cl_page_list_init(), cl_page_list_last(), cl_page_list_move(), cl_page_list_move_head(), ENTRY, ergo, LASSERT, lov_io::lis_active_subios, lov_io::lis_single_subio, lov_io::lis_single_subio_index, lov_io::lis_subs, lov_env_info(), lov_page_stripe(), lov_sub_get(), lov_sub_put(), lov_thread_info::lti_plist, cl_page_list::pl_nr, RETURN, lov_io_sub::sub_env, and lov_io_sub::sub_io.
static void lov_io_data_version_end (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 586 of file lov_io.c.
References cl_io::ci_data_version, cl_io::ci_result, cl_io_slice::cis_io, cl2lov_io(), ENTRY, EXIT, lov_io::lis_active, lov_io::lis_cl, list_for_each_entry, lov_io_end_wrapper(), lov_io_sub::sub_io, lov_io_sub::sub_linkage, and cl_io::u.
static void lov_io_end (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 577 of file lov_io.c.
References cl2lov_io(), LASSERT, lov_io_call(), and lov_io_end_wrapper().
static int lov_io_end_wrapper (const struct lu_env * env, struct cl_io * io) [static]
Definition at line 550 of file lov_io.c.
References cl_io::ci_state, CIS_IO_FINISHED, CIS_IO_GOING, cl_io_end(), ENTRY, and RETURN.
Referenced by lov_io_data_version_end(), lov_io_end(), and lov_io_fsync_end().
static int lov_io_fault_start (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 849 of file lov_io.c.
References cl_io::ci_fault, cl_io_slice::cis_io, cl2lov_io(), ENTRY, lov_io_start(), lov_page_stripe(), lov_sub_get(), lov_sub_put(), RETURN, lov_io_sub::sub_io, and cl_io::u.
static void lov_io_fini (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 401 of file lov_io.c.
References cl_io_slice::cis_obj, cl2lov(), cl2lov_io(), ENTRY, EXIT, LASSERT, lov_io::lis_nr_subios, lov_io::lis_subs, lov_object::lo_active_ios, lov_object::lo_waitq, lov_io_sub_fini(), and OBD_FREE_LARGE.
static void lov_io_fsync_end (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 865 of file lov_io.c.
References cl_io::ci_fsync, cl_io::ci_result, cl_io_slice::cis_io, cl2lov_io(), ENTRY, lov_io::lis_active, list_for_each_entry, lov_io_end_wrapper(), lov_sub_enter(), lov_sub_exit(), RETURN_EXIT, lov_io_sub::sub_env, lov_io_sub::sub_io, lov_io_sub::sub_linkage, and cl_io::u.
int lov_io_init (const struct lu_env * env, struct cl_object * obj, struct cl_io * io)
Implements cl_object_operations::clo_io_init() method for lov layer.
Dispatches to the appropriate layout io initialization method.
Definition at line 942 of file lov_object.c.
References cl_io::ci_ignore_layout, cl2lov(), CL_IO_SLICE_CLEAN, LOV_2DISPATCH_MAYLOCK, and lov_env_io().
int lov_io_init_empty (const struct lu_env * env, struct cl_object * obj, struct cl_io * io)
Definition at line 1064 of file lov_io.c.
References CERROR, cl_io::ci_result, cl_io::ci_type, CIT_DATA_VERSION, CIT_FAULT, CIT_FSYNC, CIT_LADVISE, CIT_MISC, CIT_READ, CIT_SETATTR, CIT_WRITE, cl2lov(), cl_io_slice_add(), cl_object::co_lu, DFID, ENTRY, LBUG, lov_io::lis_cl, lov_io::lis_object, lov_object::lo_active_ios, lov_env_io(), lu_object_fid(), PFID, and RETURN.
int lov_io_init_raid0 (const struct lu_env * env, struct cl_object * obj, struct cl_io * io)
Definition at line 1042 of file lov_io.c.
References cl_io::ci_result, cl2lov(), cl_io_slice_add(), ENTRY, INIT_LIST_HEAD, lov_io::lis_active, lov_io::lis_cl, lov_object::lo_active_ios, lov_env_io(), lov_io_slice_init(), lov_io_subio_init(), and RETURN.
int lov_io_init_released (const struct lu_env * env, struct cl_object * obj, struct cl_io * io)
Definition at line 1104 of file lov_io.c.
References cl_io::ci_restore_needed, cl_io::ci_result, cl_io::ci_type, CIT_DATA_VERSION, CIT_FAULT, CIT_FSYNC, CIT_LADVISE, CIT_MISC, CIT_READ, CIT_SETATTR, CIT_WRITE, cl2lov(), cl_io_is_trunc(), cl_io_slice_add(), ENTRY, LASSERT, LASSERTF, lov_io::lis_cl, lov_io::lis_object, lov_object::lo_active_ios, lov_object::lo_lsm, lov_env_io(), and RETURN.
static void lov_io_iter_fini (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 606 of file lov_io.c.
References cl2lov_io(), ENTRY, EXIT, LASSERT, lov_io::lis_active, list_del_init(), list_empty(), lov_io_call(), lov_io_iter_fini_wrapper(), and list_head::next.
static int lov_io_iter_fini_wrapper (const struct lu_env * env, struct cl_io * io) [static]
Definition at line 565 of file lov_io.c.
References cl_io_iter_fini(), and RETURN.
Referenced by lov_io_iter_fini().
static int lov_io_iter_init (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 429 of file lov_io.c.
References CDEBUG, cl_io::ci_type, cl_io_slice::cis_io, CIT_FAULT, CIT_READ, CIT_WRITE, cl2lov_io(), cl_io_iter_fini(), cl_io_iter_init(), D_VFSTRACE, end, ENTRY, lov_io::lis_active, lov_io::lis_endpos, lov_io::lis_object, lov_io::lis_pos, lov_io::lis_stripe_count, list_add_tail(), lov_object::lo_lsm, lov_io_sub_inherit(), lov_offset_mod(), lov_r0(), lov_stripe_intersects(), lov_sub_get(), lov_sub_put(), LPU64, RETURN, start, lov_io_sub::sub_env, lov_io_sub::sub_io, lov_io_sub::sub_linkage, and unlikely.
Referenced by lov_io_rw_iter_init().
static int lov_io_lock (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 538 of file lov_io.c.
References cl2lov_io(), cl_io_lock(), ENTRY, lov_io_call(), and RETURN.
static int lov_io_read_ahead (const struct lu_env * env, const struct cl_io_slice * ios, pgoff_t start, struct cl_read_ahead * ra) [static]
Adjust the stripe index by layout of raid0. ra->cra_end is the maximum page index covered by an underlying DLM lock. This function converts cra_end from stripe level to file level, and make sure it's not beyond stripe boundary.
Definition at line 631 of file lov_io.c.
References CDEBUG, cl2lov_io(), cl_index(), cl_io_read_ahead(), cl_offset(), CL_PAGE_EOF, cl_read_ahead::cra_end, D_READA, DFID, ENTRY, lov_io::lis_object, lov_object::lo_lsm, lov2cl(), lov2lu(), lov_r0(), lov_stripe_number(), lov_stripe_offset(), lov_stripe_pgoff(), lov_sub_get(), lov_sub_put(), lovsub2cl(), lov_stripe_md::lsm_stripe_size, lu_object_fid(), min_t, PFID, RETURN, lov_io_sub::sub_env, lov_io_sub::sub_io, and unlikely.
static int lov_io_rw_iter_init (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 480 of file lov_io.c.
References __u64, CDEBUG, cl_io::ci_continue, cl_io::ci_rw, cl_io::ci_type, cl_io_slice::cis_io, CIT_READ, CIT_WRITE, cl2lov_io(), cl_io_is_append(), cl_io_rw_common::crw_count, cl_io_rw_common::crw_pos, D_VFSTRACE, ENTRY, LASSERT, lov_io::lis_endpos, lov_io::lis_io_endpos, lov_io::lis_nr_subios, lov_io::lis_object, lov_io::lis_pos, lov_object::lo_lsm, lov_io_iter_init(), LPU64, lov_stripe_md::lsm_stripe_size, min_t, RETURN, start, and cl_io::u.
static int lov_io_slice_init (struct lov_io * lio, struct lov_object * obj, struct cl_io * io) [static]
Definition at line 326 of file lov_io.c.
References cl_io::ci_fault, cl_io::ci_fsync, cl_io::ci_ladvise, cl_io::ci_obj, cl_io::ci_result, cl_io::ci_rw, cl_io::ci_setattr, cl_io::ci_type, CIT_DATA_VERSION, CIT_FAULT, CIT_FSYNC, CIT_LADVISE, CIT_MISC, CIT_READ, CIT_SETATTR, CIT_WRITE, cl_io_is_append(), cl_io_is_trunc(), cl_offset(), cl_io_rw_common::crw_count, cl_io_rw_common::crw_pos, ENTRY, LASSERT, LBUG, lov_io::lis_endpos, lov_io::lis_io_endpos, lov_io::lis_object, lov_io::lis_pos, lov_io::lis_stripe_count, lov_object::lo_lsm, LOV_PATTERN_F_HOLE, lov_stripe_md::lsm_pattern, lov_stripe_md::lsm_stripe_count, OBD_OBJECT_EOF, RETURN, cl_io::u, and unlikely.
Referenced by lov_io_init_raid0().
static int lov_io_start (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 544 of file lov_io.c.
References cl2lov_io(), cl_io_start(), ENTRY, lov_io_call(), and RETURN.
Referenced by lov_io_fault_start().
static void lov_io_sub_fini (const struct lu_env * env, struct lov_io * lio, struct lov_io_sub * sub) [static]
Definition at line 59 of file lov_io.c.
References cl_env_put(), cl_io_fini(), ENTRY, EXIT, lov_io::lis_active_subios, lov_io::lis_single_subio_index, lov_sub_enter(), lov_sub_exit(), OBD_FREE_PTR, lov_io_sub::sub_borrowed, lov_io_sub::sub_env, lov_io_sub::sub_io, lov_io_sub::sub_io_initialized, lov_io_sub::sub_refcheck, and lov_io_sub::sub_stripe.
Referenced by lov_io_fini(), and lov_io_sub_init().
static void lov_io_sub_inherit (struct cl_io * io, struct lov_io * lio, int stripe, loff_t start, loff_t end) [static]
Definition at line 85 of file lov_io.c.
References cl_io::ci_data_version, cl_io::ci_fault, cl_io::ci_fsync, cl_io::ci_ladvise, cl_io::ci_obj, cl_io::ci_rw, cl_io::ci_setattr, cl_io::ci_type, cl_io::ci_wr, cl_io_slice::cis_io, CIT_DATA_VERSION, CIT_FAULT, CIT_FSYNC, CIT_LADVISE, CIT_READ, CIT_SETATTR, CIT_WRITE, cl_index(), cl_io_is_append(), cl_io_is_sync_write(), cl_io_is_trunc(), cl_offset(), cl_io_rw_common::crw_count, cl_io_rw_common::crw_pos, lov_io::lis_cl, lov_io::lis_object, lov_object::lo_lsm, lov_size_to_stripe(), and cl_io::u.
Referenced by lov_io_iter_init().
static int lov_io_sub_init (const struct lu_env * env, struct lov_io * lio, struct lov_io_sub * sub) [static]
Definition at line 154 of file lov_io.c.
References cl_io::ci_lockreq, cl_io::ci_no_srvlock, cl_io::ci_noatime, cl_io::ci_obj, cl_io::ci_parent, cl_io::ci_result, cl_io::ci_type, cl_io_slice::cis_io, cl_env_get(), cl_env_reenter(), cl_env_reexit(), cl_io_sub_init(), lov_device_emerg::emrg_env, lov_device_emerg::emrg_subio, ENTRY, LASSERT, lov_device::ld_emrg, lov_device::ld_mutex, lov_io::lis_active_subios, lov_io::lis_cl, lov_io::lis_mem_frozen, lov_io::lis_object, lov_io::lis_single_subio, lov_io::lis_single_subio_index, lov_io::lis_stripe_count, lov2cl(), lov_io_sub_fini(), lov_r0(), lov_sub_enter(), lov_sub_exit(), lovsub2cl(), lu2lov_dev(), OBD_ALLOC_PTR, RETURN, lov_io_sub::sub_borrowed, lov_io_sub::sub_env, lov_io_sub::sub_io, lov_io_sub::sub_io_initialized, lov_io_sub::sub_refcheck, lov_io_sub::sub_stripe, and unlikely.
Referenced by lov_sub_get().
static int lov_io_subio_init (const struct lu_env * env, struct lov_io * lio, struct cl_io * io) [static]
Definition at line 299 of file lov_io.c.
References ENTRY, LASSERT, lov_io::lis_active_subios, lov_io::lis_nr_subios, lov_io::lis_object, lov_io::lis_single_subio_index, lov_io::lis_stripe_count, lov_io::lis_subs, lov_object::lo_lsm, lov_stripe_md::lsm_stripe_count, OBD_ALLOC_LARGE, and RETURN.
Referenced by lov_io_init_raid0().
static int lov_io_submit (const struct lu_env * env, const struct cl_io_slice * ios, enum cl_req_type crt, struct cl_2queue * queue) [static]
lov implementation of cl_operations::cio_submit() method.
It takes a list of pages in queue, splits it into per-stripe sub-lists, invokes cl_io_submit() on underlying devices to submit sub-lists, and then splices everything back.
Major complication of this function is a need to handle memory cleansing: cl_io_submit() is called to write out pages as a part of VM memory reclamation, and hence it may not fail due to memory shortages (system dead-locks otherwise). To deal with this, some resources (sub-lists, sub-environment, etc.) are allocated per-device on "startup" (i.e., in a not-memory cleansing context), and in case of memory shortage, these pre-allocated resources are used by lov_io_submit() under lov_device::ld_mutex mutex.
Definition at line 705 of file lov_io.c.
References cl_2queue::c2_qin, cl_2queue::c2_qout, cl2lov_io(), cl_2queue_fini(), cl_2queue_init(), cl_io_submit_rw(), cl_page_list_fini(), cl_page_list_first(), cl_page_list_init(), cl_page_list_move(), cl_page_list_splice(), ENTRY, LASSERT, lov_io::lis_active_subios, lov_io::lis_single_subio, lov_io::lis_single_subio_index, lov_io::lis_subs, lov_env_info(), lov_page_stripe(), lov_sub_get(), lov_sub_put(), lov_thread_info::lti_cl2q, lov_thread_info::lti_plist, cl_page_list::pl_nr, RETURN, lov_io_sub::sub_env, and lov_io_sub::sub_io.
static void lov_io_unlock (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 620 of file lov_io.c.
References cl2lov_io(), ENTRY, EXIT, LASSERT, lov_io_call(), and lov_io_unlock_wrapper().
static int lov_io_unlock_wrapper (const struct lu_env * env, struct cl_io * io) [static]
Definition at line 571 of file lov_io.c.
References cl_io_unlock(), and RETURN.
Referenced by lov_io_unlock().
static int lov_is_object (const struct lu_object * obj) [inline, static]
Definition at line 578 of file lov_cl_internal.h.
References lu_device::ld_type, lu_object::lo_dev, and lov_device_type.
Referenced by cl2lov(), cl2lov_lock(), cl2lov_page(), and lu2lov().
static int lov_layout_change (const struct lu_env * unused, struct lov_object * lov, struct lov_stripe_md * lsm, const struct cl_object_conf * conf) [static]
Definition at line 729 of file lov_object.c.
References ARRAY_SIZE, CDEBUG, cl_env_get(), cl_env_put(), cl_env_reenter(), cl_env_reexit(), cl_object_header(), cl_object_prune(), cl_object_header::coh_page_bufsize, D_INODE, DFID, ENTRY, GOTO, LASSERT, lov_layout_operations::llo_delete, lov_layout_operations::llo_fini, lov_layout_operations::llo_init, lov_layout_operations::llo_install, llt2str(), LLT_EMPTY, lov_object::lo_active_ios, lov_object::lo_cl, lov_object::lo_type, lov2lu(), lov_object_dev(), lov_page_slice_fixup(), lov_type(), lu_object_fid(), PFID, RETURN, state, and lov_object::u.
Referenced by lov_conf_set().
static int lov_layout_wait (const struct lu_env * env, struct lov_object * lov) [static]
Definition at line 713 of file lov_object.c.
References CDEBUG, D_INODE, DFID, ENTRY, l_wait_event, lov_object::lo_active_ios, lov_object::lo_waitq, lov2lu(), lu_object_fid(), PFID, and RETURN.
Referenced by lov_conf_set(), lov_delete_empty(), and lov_delete_raid0().
static void lov_lock_cancel (const struct lu_env * env, const struct cl_lock_slice * slice) [static]
Definition at line 267 of file lov_lock.c.
References cl2lov_lock(), cl_lock_cancel(), CL_LOCK_DEBUG, cl_lock_slice::cls_lock, D_ERROR, ENTRY, lov_lock::lls_nr, lov_lock::lls_sub, lov_sublock_env_get(), lov_sublock_env_put(), lov_sublock_env::lse_env, lov_lock_sub::sub_is_enqueued, and lov_lock_sub::sub_lock.
static int lov_lock_enqueue (const struct lu_env * env, const struct cl_lock_slice * slice, struct cl_io * io, struct cl_sync_io * anchor) [static]
Implementation of cl_lock_operations::clo_enqueue() for lov layer.
This function is rather subtle, as it enqueues top-lock (i.e., advances top-lock state machine from CLS_QUEUING to CLS_ENQUEUED states) by juggling sub-lock state machines in the face of sub-locks sharing (by multiple top-locks), and concurrent sub-lock cancellations.
Definition at line 235 of file lov_lock.c.
References cl2lov_lock(), cl_lock_enqueue(), cl_lock_slice::cls_lock, ENTRY, lov_lock::lls_nr, lov_lock::lls_sub, lov_sublock_env_get(), lov_sublock_env_put(), lov_sublock_env::lse_env, lov_sublock_env::lse_io, RETURN, lov_lock_sub::sub_is_enqueued, and lov_lock_sub::sub_lock.
static void lov_lock_fini (const struct lu_env * env, struct cl_lock_slice * slice) [static]
Definition at line 210 of file lov_lock.c.
References cl2lov_lock(), cl_lock_fini(), ENTRY, EXIT, LASSERT, lov_lock::lls_nr, lov_lock::lls_sub, OBD_FREE_LARGE, offsetof, lov_lock_sub::sub_initialized, lov_lock_sub::sub_is_enqueued, and lov_lock_sub::sub_lock.
int lov_lock_init (const struct lu_env * env, struct cl_object * obj, struct cl_lock * lock, const struct cl_io * io)
Definition at line 972 of file lov_object.c.
References cl2lov(), and LOV_2DISPATCH_NOLOCK.
int lov_lock_init_empty (const struct lu_env * env, struct cl_object * obj, struct cl_lock * lock, const struct cl_io * io)
Definition at line 356 of file lov_lock.c.
References cl_lock_slice_add(), ENTRY, lov_lock::lls_cl, lov_lock_kmem, OBD_SLAB_ALLOC_PTR_GFP, and RETURN.
int lov_lock_init_raid0 (const struct lu_env * env, struct cl_object * obj, struct cl_lock * lock, const struct cl_io * io)
Definition at line 321 of file lov_lock.c.
References cl_lock_slice_add(), ENTRY, lov_lock::lls_cl, lov_lock_sub_init(), and RETURN.
struct lov_lock_link* lov_lock_link_find (const struct lu_env * env, struct lov_lock * lck, struct lovsub_lock * sub) [read]
static int lov_lock_print (const struct lu_env * env, void * cookie, lu_printer_t p, const struct cl_lock_slice * slice) [static]
Definition at line 297 of file lov_lock.c.
References cl2lov_lock(), cl_lock_print(), lov_lock::lls_nr, lov_lock::lls_sub, lov_lock_sub::sub_is_enqueued, and lov_lock_sub::sub_lock.
static struct lov_lock* lov_lock_sub_init (const struct lu_env * env, const struct cl_object * obj, struct cl_lock * lock) [static, read]
Creates sub-locks for a given lov_lock for the first time.
Goes through all sub-objects of top-object, and creates sub-locks on every sub-object intersecting with top-lock extent. This is complicated by the fact that top-lock (that is being created) can be accessed concurrently through already created sub-locks (possibly shared with other top-locks).
Definition at line 126 of file lov_lock.c.
References cl2lov(), cl_index(), cl_lock_fini(), cl_offset(), cl_lock_descr::cld_end, cl_lock_descr::cld_enq_flags, cl_lock_descr::cld_gid, cl_lock_descr::cld_mode, cl_lock_descr::cld_obj, cl_lock_descr::cld_start, cl_lock::cll_descr, end, ENTRY, ergo, LASSERT, likely, lov_lock::lls_nr, lov_lock::lls_sub, lov_object::lo_lsm, lov2cl(), lov_r0(), lov_stripe_intersects(), lov_sublock_init(), lovsub2cl(), OBD_ALLOC_LARGE, OBD_FREE_LARGE, offsetof, RETURN, start, lov_lock_sub::sub_initialized, lov_lock_sub::sub_lock, and lov_lock_sub::sub_stripe.
Referenced by lov_lock_init_raid0().
void lov_lock_unlink (const struct lu_env * env, struct lov_lock_link * link, struct lovsub_lock * sub)
struct lov_stripe_md * lov_lsm_addref (struct lov_object * lov) [read]
Definition at line 1530 of file lov_object.c.
References CDEBUG, D_INODE, lov_object::lo_layout_invalid, lov_object::lo_lsm, lov_conf_freeze(), lov_conf_thaw(), lsm_addref(), and lov_stripe_md::lsm_refc.
Referenced by lov_object_fiemap(), lov_object_getstripe(), lov_object_layout_get(), and lov_object_maxbytes().
static void lov_lsm_put (struct lov_stripe_md * lsm) [static]
Definition at line 87 of file lov_object.c.
References lov_free_memmd().
Referenced by lov_conf_set(), lov_object_fiemap(), lov_object_getstripe(), lov_object_init(), lov_object_layout_get(), and lov_object_maxbytes().
struct lu_object * lov_object_alloc (const struct lu_env * env, const struct lu_object_header * hdr, struct lu_device * dev) [read]
Definition at line 1505 of file lov_object.c.
References cl_object::co_ops, ENTRY, lov_object::lo_cl, lu_object::lo_ops, lov_object::lo_type, lov2lu(), lov_object_kmem, lu_object_init(), OBD_SLAB_ALLOC_PTR_GFP, and RETURN.
static void lov_object_delete (const struct lu_env * env, struct lu_object * obj) [static]
Definition at line 905 of file lov_object.c.
References ENTRY, EXIT, LOV_2DISPATCH_VOID, lu2lov(), and lov_object::u.
static int lov_object_fiemap (const struct lu_env * env, struct cl_object * obj, struct ll_fiemap_info_key * fmkey, struct fiemap * fiemap, size_t * buflen) [static]
Break down the FIEMAP request and send appropriate calls to individual OSTs.
This also handles the restarting of FIEMAP calls in case mapping overflows the available number of extents in single call.
Parameters:
env [in] lustre environment
obj [in] file object
fmkey [in] fiemap request header and other info
fiemap [out] fiemap buffer holding retrived map extents
buflen [in/out] max buffer length of , when iterate each OST, it is used to limit max map needed
Return values:
0 success
< 0 error
If the stripe_count > 1 and the application does not understand DEVICE_ORDER flag, it cannot interpret the extents correctly.
released file, return a minimal FIEMAP if request fits in file-size.
Requested extent count exceeds the fiemap buffer size, shrink our ambition.
Definition at line 1134 of file lov_object.c.
References cl2lov(), cl_object_fiemap(), cl_object_put(), cl_object::co_lu, lov_obd::desc, ENTRY, FIEMAP_BUFFER_SIZE, fiemap_calc_fm_end_offset(), fiemap_calc_last_stripe(), fiemap_count_to_size(), FIEMAP_FLAG_DEVICE_ORDER, fiemap_prepare_and_copy_exts(), fiemap_size_to_count(), GOTO, lov_device::ld_lov, lov_desc::ld_tgt_count, ll_fiemap_info_key::lfik_fiemap, ll_fiemap_info_key::lfik_oa, lu_object::lo_dev, lov_oinfo::loi_ost_idx, lov_find_subobj(), lov_lsm_addref(), lov_lsm_put(), lov_oinfo_is_dummy(), lov_size_to_stripe(), lov_stripe_intersects(), lov_stripe_number(), lov_stripe_size(), lov_obd::lov_tgts, lsm_is_released(), lov_stripe_md::lsm_oinfo, lov_stripe_md::lsm_stripe_count, lov_tgt_desc::ltd_active, lu2lov_dev(), obdo::o_size, OBD_ALLOC_LARGE, OBD_FREE_LARGE, and RETURN.
static void lov_object_free (const struct lu_env * env, struct lu_object * obj) [static]
Definition at line 914 of file lov_object.c.
References ENTRY, EXIT, LOV_2DISPATCH_VOID, lov_object_kmem, lu2lov(), lu_object_fini(), OBD_SLAB_FREE_PTR, and lov_object::u.
static int lov_object_getstripe (const struct lu_env * env, struct cl_object * obj, struct lov_user_md __user * lum) [static]
Definition at line 1424 of file lov_object.c.
References cl2lov(), ENTRY, lov_getstripe(), lov_lsm_addref(), lov_lsm_put(), and RETURN.
int lov_object_init (const struct lu_env * env, struct lu_object * obj, const struct lu_object_conf * conf)
Definition at line 802 of file lov_object.c.
References cl_object_page_init(), cl_object_conf::coc_layout, ENTRY, GOTO, lu_buf::lb_buf, lu_buf::lb_len, lov_device::ld_lov, lov_layout_operations::llo_init, lov_layout_operations::llo_install, LLT_EMPTY, lov_object::lo_active_ios, lov_object::lo_type, lov_object::lo_type_guard, lov_object::lo_waitq, lov_lsm_put(), lov_object_dev(), lov_type(), lov_unpackmd(), lu2cl(), lu2cl_conf(), lu2lov(), RETURN, cl_object_conf::u, and lov_object::u.
static int lov_object_layout_get (const struct lu_env * env, struct cl_object * obj, struct cl_layout * cl) [static]
Definition at line 1441 of file lov_object.c.
References buf, cl2lov(), cl_layout::cl_buf, cl_layout::cl_layout_gen, CL_LAYOUT_GEN_EMPTY, cl_layout::cl_size, ENTRY, lu_buf::lb_buf, lu_buf::lb_len, lov_lsm_addref(), lov_lsm_pack(), lov_lsm_put(), lov_mds_md_size(), lov_stripe_md::lsm_layout_gen, lov_stripe_md::lsm_magic, lov_stripe_md::lsm_stripe_count, and RETURN.
static loff_t lov_object_maxbytes (struct cl_object * obj) [static]
Definition at line 1467 of file lov_object.c.
References cl2lov(), lov_lsm_addref(), lov_lsm_put(), and lov_stripe_md::lsm_maxbytes.
static int lov_object_print (const struct lu_env * env, void * cookie, lu_printer_t p, const struct lu_object * o) [static]
Definition at line 925 of file lov_object.c.
References LOV_2DISPATCH_NOLOCK, and lu2lov().
static loff_t lov_offset_mod (loff_t val, int delta) [static]
Definition at line 422 of file lov_io.c.
References OBD_OBJECT_EOF.
Referenced by lov_io_iter_init().
int lov_page_init (const struct lu_env * env, struct cl_object * ob, struct cl_page * page, pgoff_t index)
Definition at line 931 of file lov_object.c.
References cl2lov(), and LOV_2DISPATCH_NOLOCK.
int lov_page_init_empty (const struct lu_env * env, struct cl_object * obj, struct cl_page * page, pgoff_t index)
Definition at line 126 of file lov_page.c.
References cl_object_page_slice(), cl_page_export(), cl_page_size(), cl_page_slice_add(), cl_page::cp_vmpage, ENTRY, lov_page::lps_cl, and RETURN.
int lov_page_init_raid0 (const struct lu_env * env, struct cl_object * obj, struct cl_page * page, pgoff_t index)
Definition at line 69 of file lov_page.c.
References cl2lov(), cl_index(), cl_object_page_slice(), cl_offset(), cl_page_slice_add(), cl_object::co_lu, cl_object::co_ops, cl_object_operations::coo_page_init, ENTRY, LASSERT, list_for_each_entry, lu_object::lo_header, lov_object::lo_lsm, lu_object_header::loh_layers, lov_env_io(), lov_r0(), lov_stripe_number(), lov_stripe_offset(), lov_sub_get(), lov_sub_put(), lovsub2cl(), lov_page::lps_cl, lov_page::lps_stripe, RETURN, and lov_io_sub::sub_env.
static int lov_page_slice_fixup (struct lov_object * lov, struct cl_object * stripe) [static]
Definition at line 206 of file lov_object.c.
References cfs_size_round(), cl_object_for_each, cl_object_header(), cl_object::co_slice_off, cl_object_header::coh_page_bufsize, and lov_object::lo_cl.
Referenced by lov_init_raid0(), and lov_layout_change().
int lov_page_stripe (const struct cl_page * page)
Definition at line 269 of file lov_io.c.
References cl2lov_page(), cl_page_at(), cl_page_slice::cpl_obj, ENTRY, LASSERT, lov_device_type, and RETURN.
Referenced by lov_io_commit_async(), lov_io_fault_start(), lov_io_submit(), and lov_page_subio().
struct lov_io_sub * lov_page_subio (const struct lu_env * env, struct lov_io * lio, const struct cl_page_slice * slice) [read]
Definition at line 281 of file lov_io.c.
References cl_io_slice::cis_io, cl2lov(), cl_page_slice::cpl_obj, cl_page_slice::cpl_page, ENTRY, LASSERT, lov_io::lis_cl, lov_io::lis_nr_subios, lov_io::lis_object, lov_object::lo_lsm, lov_page_stripe(), lov_sub_get(), and RETURN.
static int lov_print_empty (const struct lu_env * env, void * cookie, lu_printer_t p, const struct lu_object * o) [static]
Definition at line 467 of file lov_object.c.
References lov_object::lo_layout_invalid, and lu2lov().
static int lov_print_raid0 (const struct lu_env * env, void * cookie, lu_printer_t p, const struct lu_object * o) [static]
Definition at line 474 of file lov_object.c.
References lov_object::lo_layout_invalid, lov_object::lo_lsm, lov_r0(), lovsub2lu(), lov_stripe_md::lsm_layout_gen, lov_stripe_md::lsm_magic, lov_stripe_md::lsm_refc, lov_stripe_md::lsm_stripe_count, lu2lov(), and lu_object_print().
static int lov_print_released (const struct lu_env * env, void * cookie, lu_printer_t p, const struct lu_object * o) [static]
Definition at line 499 of file lov_object.c.
References lov_object::lo_layout_invalid, lov_object::lo_lsm, lov_stripe_md::lsm_layout_gen, lov_stripe_md::lsm_magic, lov_stripe_md::lsm_refc, lov_stripe_md::lsm_stripe_count, and lu2lov().
static struct lov_layout_raid0* lov_r0 (struct lov_object * lov) [static, read]
Definition at line 724 of file lov_cl_internal.h.
References LASSERT, LLT_RAID0, lov_object::lo_lsm, lov_object::lo_type, LOV_MAGIC, LOV_MAGIC_V3, lov_stripe_md::lsm_magic, lov_object::lov_layout_state::raid0, and lov_object::u.
Referenced by lov_attr_get_raid0(), lov_io_iter_init(), lov_io_read_ahead(), lov_io_sub_init(), lov_lock_sub_init(), lov_page_init_raid0(), lov_print_raid0(), and lovsub_attr_update().
static int lov_raid0_page_print (const struct lu_env * env, const struct cl_page_slice * slice, void * cookie, lu_printer_t printer) [static]
Definition at line 56 of file lov_page.c.
References cl2lov_page(), and LUSTRE_LOV_NAME.
int lov_read_and_clear_async_rc (struct cl_object * clob)
Definition at line 1545 of file lov_object.c.
References osc_async_rc::ar_rc, cl_object_header(), ENTRY, LASSERT, LBUG, LLT_EMPTY, LLT_RAID0, LLT_RELEASED, lov_object::lo_lsm, lov_object::lo_type, lov_oinfo::loi_ar, lov_conf_freeze(), lov_conf_thaw(), lov_device_type, lov_oinfo_is_dummy(), lov_stripe_md::lsm_oinfo, lov_stripe_md::lsm_stripe_count, lu2lov(), lu_object_locate(), and RETURN.
Referenced by ll_file_release(), ll_flush(), and ll_fsync().
static void lov_sub_enter (struct lov_io_sub * sub) [inline, static]
Definition at line 50 of file lov_io.c.
References lov_io_sub::sub_reenter.
Referenced by lov_io_call(), lov_io_fsync_end(), lov_io_sub_fini(), lov_io_sub_init(), and lov_sub_get().
static void lov_sub_exit (struct lov_io_sub * sub) [inline, static]
Definition at line 54 of file lov_io.c.
References lov_io_sub::sub_reenter.
Referenced by lov_io_call(), lov_io_fsync_end(), lov_io_sub_fini(), lov_io_sub_init(), and lov_sub_put().
static struct cl_object* lov_sub_find (const struct lu_env * env, struct cl_device * dev, const struct lu_fid * fid, const struct cl_object_conf * conf) [static, read]
Definition at line 122 of file lov_object.c.
References cl2lu_dev(), cl_object_conf::coc_lu, ENTRY, ergo, LASSERT, lu_device::ld_type, lu_object::lo_dev, lovsub_device_type, lu2cl(), lu_object_find_at(), and RETURN.
Referenced by lov_find_subobj(), and lov_init_raid0().
struct lov_io_sub * lov_sub_get (const struct lu_env * env, struct lov_io * lio, int stripe) [read]
Definition at line 237 of file lov_io.c.
References ENTRY, LASSERT, lov_io::lis_subs, lov_io_sub_init(), lov_sub_enter(), RETURN, lov_io_sub::sub_io_initialized, and lov_io_sub::sub_stripe.
Referenced by lov_io_commit_async(), lov_io_fault_start(), lov_io_iter_init(), lov_io_read_ahead(), lov_io_submit(), lov_page_init_raid0(), lov_page_subio(), and lov_sublock_env_get().
void lov_sub_put (struct lov_io_sub * sub)
Definition at line 258 of file lov_io.c.
References lov_sub_exit().
Referenced by lov_io_commit_async(), lov_io_fault_start(), lov_io_iter_init(), lov_io_read_ahead(), lov_io_submit(), lov_page_init_raid0(), and lov_sublock_env_put().
static struct lov_sublock_env* lov_sublock_env_get (const struct lu_env * env, const struct cl_lock * parent, struct lov_lock_sub * lls) [static, read]
Definition at line 55 of file lov_lock.c.
References cl_io::ci_obj, cl_io_slice::cis_io, cl_object_same(), cl_lock_descr::cld_obj, cl_lock::cll_descr, lov_io::lis_cl, lov_env_io(), lov_env_session(), lov_sub_get(), lov_session::ls_subenv, lov_sublock_env::lse_env, lov_sublock_env::lse_io, lov_sublock_env::lse_sub, lov_io_sub::sub_env, lov_io_sub::sub_io, and lov_lock_sub::sub_stripe.
Referenced by lov_lock_cancel(), lov_lock_enqueue(), and lov_sublock_init().
static void lov_sublock_env_put (struct lov_sublock_env * subenv) [static]
Definition at line 92 of file lov_lock.c.
References lov_sub_put(), and lov_sublock_env::lse_sub.
Referenced by lov_lock_cancel(), lov_lock_enqueue(), and lov_sublock_init().
static int lov_sublock_init (const struct lu_env * env, const struct cl_lock * parent, struct lov_lock_sub * lls) [static]
Definition at line 98 of file lov_lock.c.
References cl_lock_init(), ENTRY, lov_sublock_env_get(), lov_sublock_env_put(), lov_sublock_env::lse_env, lov_sublock_env::lse_io, RETURN, and lov_lock_sub::sub_lock.
Referenced by lov_lock_sub_init().
int lov_sublock_modify (const struct lu_env * env, struct lov_lock * lov, struct lovsub_lock * sublock, const struct cl_lock_descr * d, int idx)
static void lov_subobject_kill (const struct lu_env * env, struct lov_object * lov, struct lovsub_object * los, int idx) [static]
Definition at line 359 of file lov_object.c.
References cl_object_kill(), cl_object_put(), cl_object::co_lu, LASSERT, lu_device::ld_site, lu_object::lo_dev, lu_object::lo_header, lu_object_header::loh_fid, lov_env_info(), lovsub2cl(), lu_site_bkt_data::lsb_marche_funebre, lov_thread_info::lti_waiter, lu_object_ref_del(), lu_site_bkt_from_fid(), lov_object::lov_layout_state::raid0, and lov_object::u.
Referenced by lov_delete_raid0().
static int lov_targets_nr (const struct lov_device * lov) [inline, static]
Definition at line 710 of file lov_cl_internal.h.
References lov_obd::desc, lov_device::ld_lov, and lov_desc::ld_tgt_count.
Referenced by lov_init_raid0().
static enum lov_layout_type lov_type (struct lov_stripe_md * lsm) [static]
Return lov_layout_type associated with a given lsm.
Definition at line 646 of file lov_object.c.
References LLT_EMPTY, LLT_RAID0, LLT_RELEASED, and lsm_is_released().
Referenced by lov_layout_change(), and lov_object_init().
static struct cl_object* lovsub2cl (struct lovsub_object * los) [static, read]
Definition at line 648 of file lov_cl_internal.h.
References lovsub_object::lso_cl.
Referenced by lov_io_read_ahead(), lov_io_sub_init(), lov_lock_sub_init(), lov_page_init_raid0(), and lov_subobject_kill().
static struct cl_device* lovsub2cl_dev (struct lovsub_device * lovsub) [static, read]
Definition at line 599 of file lov_cl_internal.h.
References lovsub_device::acid_cl.
Referenced by lov_cl_del_target(), lov_device_fini(), lov_find_subobj(), lov_init_raid0(), and lovsub2lu_dev().
static struct lu_object* lovsub2lu (struct lovsub_object * los) [static, read]
Definition at line 643 of file lov_cl_internal.h.
References cl_object::co_lu, and lovsub_object::lso_cl.
Referenced by lov_print_raid0(), and lovsub_object_alloc().
static struct lu_device* lovsub2lu_dev (struct lovsub_device * lovsub) [static, read]
Definition at line 604 of file lov_cl_internal.h.
References cl_device::cd_lu_dev, and lovsub2cl_dev().
Referenced by lovsub_device_alloc().
static int lovsub_attr_update (const struct lu_env * env, struct cl_object * obj, const struct cl_attr * attr, unsigned valid) [static]
Definition at line 108 of file lovsub_object.c.
References cl2lovsub(), ENTRY, lov_r0(), lovsub_object::lso_super, and RETURN.
static struct lu_device* lovsub_device_alloc (const struct lu_env * env, struct lu_device_type * t, struct lustre_cfg * cfg) [static, read]
Definition at line 113 of file lovsub_dev.c.
References lovsub_device::acid_cl, cl_device_init(), lu_device::ld_ops, lovsub2lu_dev(), and OBD_ALLOC_PTR.
static struct lu_device* lovsub_device_fini (const struct lu_env * env, struct lu_device * d) [static, read]
Definition at line 78 of file lovsub_dev.c.
References lovsub_device::acid_next, lovsub_device::acid_super, cl2lu_dev(), ENTRY, lu2lovsub_dev(), and RETURN.
static struct lu_device* lovsub_device_free (const struct lu_env * env, struct lu_device * d) [static, read]
Definition at line 92 of file lovsub_dev.c.
References lovsub_device::acid_next, cl2lu_dev(), cl_device_fini(), D_ERROR, lu_device::ld_ref, lu_device::ld_site, LIBCFS_DEBUG_MSG_DATA_DECL, lu2cl_dev(), lu2lovsub_dev(), lu_cdebug_printer(), lu_site_print(), and OBD_FREE_PTR.
static int lovsub_device_init (const struct lu_env * env, struct lu_device * d, const char * name, struct lu_device * next) [static]
Definition at line 55 of file lovsub_dev.c.
References lovsub_device::acid_next, ENTRY, LASSERT, lu_device::ld_reference, lu_device::ld_site, lu_device::ld_type, lu_device_type::ldt_name, lu_device_type::ldt_ops, lu_device_type_operations::ldto_device_init, lu2cl_dev(), lu2lovsub_dev(), lu_device_get(), lu_ref_add(), lu_site_init(), and RETURN.
static int lovsub_is_object (const struct lu_object * obj) [inline, static]
Definition at line 583 of file lov_cl_internal.h.
References lu_device::ld_type, lu_object::lo_dev, and lovsub_device_type.
Referenced by cl2lovsub(), cl2lovsub_lock(), cl2lovsub_page(), and lu2lovsub().
static void lovsub_lock_fini (const struct lu_env * env, struct cl_lock_slice * slice) [static]
Definition at line 55 of file lovsub_lock.c.
References cl2lovsub_lock(), ENTRY, EXIT, LASSERT, list_empty(), lovsub_lock_kmem, lovsub_lock::lss_parents, and OBD_SLAB_FREE_PTR.
int lovsub_lock_init (const struct lu_env * env, struct cl_object * obj, struct cl_lock * lock, const struct cl_io * io)
Definition at line 71 of file lovsub_lock.c.
References cl_lock_slice_add(), ENTRY, INIT_LIST_HEAD, lovsub_lock_kmem, lovsub_lock::lss_cl, lovsub_lock::lss_parents, OBD_SLAB_ALLOC_PTR_GFP, and RETURN.
struct lu_object * lovsub_object_alloc (const struct lu_env * env, const struct lu_object_header * hdr, struct lu_device * dev) [read]
Definition at line 166 of file lovsub_object.c.
References cl_object_header_init(), cl_object::co_ops, cl_object_header::coh_lu, ENTRY, lu_object::lo_ops, lovsub2lu(), lovsub_object_kmem, lovsub_object::lso_cl, lovsub_object::lso_header, lu_object_add_top(), lu_object_init(), OBD_SLAB_ALLOC_PTR_GFP, and RETURN.
static void lovsub_object_free (const struct lu_env * env, struct lu_object * obj) [static]
Definition at line 77 of file lovsub_object.c.
References cl_object_header::coh_lu, ENTRY, EXIT, LASSERT, LLT_RAID0, lov_object::lov_layout_state::lov_layout_raid0::lo_sub, lov_object::lov_layout_state::lov_layout_raid0::lo_sub_lock, lov_object::lo_type, lovsub_object_kmem, lovsub_object::lso_header, lovsub_object::lso_index, lovsub_object::lso_super, lu2lovsub(), lu_object_fini(), lu_object_header_fini(), OBD_SLAB_FREE_PTR, lov_object::lov_layout_state::raid0, and lov_object::u.
static int lovsub_object_glimpse (const struct lu_env * env, const struct cl_object * obj, struct ost_lvb * lvb) [static]
Definition at line 118 of file lovsub_object.c.
References cl2lovsub(), cl_object_glimpse(), ENTRY, lov_object::lo_cl, lovsub_object::lso_super, and RETURN.
int lovsub_object_init (const struct lu_env * env, struct lu_object * obj, const struct lu_object_conf * conf)
Definition at line 55 of file lovsub_object.c.
References lovsub_device::acid_next, cl_device::cd_lu_dev, cl_object_page_init(), ENTRY, lu_device::ld_ops, lu_device_operations::ldo_object_alloc, lu_object::lo_dev, lu_object::lo_header, lu2cl(), lu2lovsub_dev(), lu_object_add(), and RETURN.
static int lovsub_object_print (const struct lu_env * env, void * cookie, lu_printer_t p, const struct lu_object * obj) [static]
Definition at line 100 of file lovsub_object.c.
References lovsub_object::lso_index, and lu2lovsub().
static void lovsub_page_fini (const struct lu_env * env, struct cl_page_slice * slice) [static]
Definition at line 55 of file lovsub_page.c.
int lovsub_page_init (const struct lu_env * env, struct cl_object * ob, struct cl_page * page, pgoff_t index)
Definition at line 64 of file lovsub_page.c.
References cl_object_page_slice(), cl_page_slice_add(), ENTRY, lovsub_page::lsb_cl, and RETURN.
static void lovsub_req_attr_set (const struct lu_env * env, struct cl_object * obj, struct cl_req_attr * attr) [static]
Implementation of struct cl_object_operations::coo_req_attr_set() for lovsub layer.
Lov and lovsub are responsible only for struct obdo::o_stripe_idx field, which is filled there.
Definition at line 133 of file lovsub_object.c.
References cl2lovsub(), cl_req_attr_set(), cl_req_attr::cra_oa, ENTRY, EXIT, lov_object::lo_cl, lovsub_object::lso_index, lovsub_object::lso_super, and obdo::o_stripe_idx.
static struct lov_object* lu2lov (const struct lu_object * obj) [static, read]
Definition at line 631 of file lov_cl_internal.h.
References cl_object::co_lu, LINVRNT, lov_object::lo_cl, and lov_is_object().
Referenced by lov_object_delete(), lov_object_free(), lov_object_init(), lov_object_print(), lov_print_empty(), lov_print_raid0(), lov_print_released(), and lov_read_and_clear_async_rc().
static struct lov_device* lu2lov_dev (const struct lu_device * d) [static, read]
Definition at line 593 of file lov_cl_internal.h.
References cl_device::cd_lu_dev, lov_device::ld_cl, lu_device::ld_type, LINVRNT, and lov_device_type.
Referenced by lov_cl_add_target(), lov_cl_del_target(), lov_device_fini(), lov_device_free(), lov_device_init(), lov_find_subobj(), lov_io_sub_init(), lov_object_dev(), and lov_object_fiemap().
static struct lovsub_object* lu2lovsub (const struct lu_object * obj) [static, read]
Definition at line 659 of file lov_cl_internal.h.
References cl_object::co_lu, LINVRNT, lovsub_is_object(), and lovsub_object::lso_cl.
Referenced by lovsub_object_free(), and lovsub_object_print().
static struct lovsub_device* lu2lovsub_dev (const struct lu_device * d) [static, read]
Definition at line 609 of file lov_cl_internal.h.
References lovsub_device::acid_cl, cl_device::cd_lu_dev, lu_device::ld_type, LINVRNT, and lovsub_device_type.
Referenced by lovsub_device_fini(), lovsub_device_free(), lovsub_device_init(), and lovsub_object_init().
Variable Documentation
struct lu_device_type lov_device_type
Definition at line 468 of file lov_dev.c.
Referenced by lov_init(), lov_init_sub(), lov_is_object(), lov_page_stripe(), lov_read_and_clear_async_rc(), and lu2lov_dev().
const struct lov_layout_operations lov_dispatch[] [static]
Definition at line 594 of file lov_object.c.
struct cl_io_operations lov_empty_io_ops [static]
An io operation vector for files without stripes.
Definition at line 996 of file lov_io.c.
struct cl_lock_operations lov_empty_lock_ops [static]
Initial value:
 {
        .clo_fini  = lov_empty_lock_fini,
        .clo_print = lov_empty_lock_print
}
Definition at line 351 of file lov_lock.c.
struct cl_page_operations lov_empty_page_ops [static]
Initial value:
 {
        .cpo_print = lov_empty_page_print
}
Definition at line 122 of file lov_page.c.
struct cl_io_operations lov_io_ops [static]
Definition at line 887 of file lov_io.c.
struct lu_context_key lov_key
Definition at line 126 of file lov_dev.c.
Referenced by lov_env_info().
struct kmem_cache* lov_lock_kmem
Definition at line 48 of file lov_dev.c.
Referenced by lov_empty_lock_fini(), and lov_lock_init_empty().
struct kmem_cache* lov_lock_link_kmem
Definition at line 56 of file lov_dev.c.
struct cl_lock_operations lov_lock_ops [static]
Initial value:
 {
        .clo_fini      = lov_lock_fini,
        .clo_enqueue   = lov_lock_enqueue,
        .clo_cancel    = lov_lock_cancel,
        .clo_print     = lov_lock_print
}
Definition at line 314 of file lov_lock.c.
struct lu_object_operations lov_lu_obj_ops [static]
Initial value:
 {
        .loo_object_init      = lov_object_init,
        .loo_object_delete    = lov_object_delete,
        .loo_object_release   = NULL,
        .loo_object_free      = lov_object_free,
        .loo_object_print     = lov_object_print,
        .loo_object_invariant = NULL
}
Definition at line 1496 of file lov_object.c.
struct kmem_cache* lov_object_kmem
Definition at line 49 of file lov_dev.c.
Referenced by lov_object_alloc(), and lov_object_free().
struct cl_object_operations lov_ops [static]
Initial value:
 {
        .coo_page_init    = lov_page_init,
        .coo_lock_init    = lov_lock_init,
        .coo_io_init      = lov_io_init,
        .coo_attr_get     = lov_attr_get,
        .coo_attr_update  = lov_attr_update,
        .coo_conf_set     = lov_conf_set,
        .coo_getstripe    = lov_object_getstripe,
        .coo_layout_get   = lov_object_layout_get,
        .coo_maxbytes     = lov_object_maxbytes,
        .coo_fiemap       = lov_object_fiemap,
}
Definition at line 1483 of file lov_object.c.
struct cl_page_operations lov_raid0_page_ops [static]
Initial value:
 {
        .cpo_print = lov_raid0_page_print
}
Definition at line 65 of file lov_page.c.
struct lu_context_key lov_session_key
Definition at line 150 of file lov_dev.c.
Referenced by lov_env_session().
struct kmem_cache* lov_session_kmem
Definition at line 51 of file lov_dev.c.
Referenced by lov_session_key_fini(), and lov_session_key_init().
struct kmem_cache* lov_thread_kmem
Definition at line 50 of file lov_dev.c.
Referenced by lov_key_fini(), and lov_key_init().
struct lu_device_type lovsub_device_type
Initial value:
 {
        .ldt_tags     = LU_DEVICE_CL,
        .ldt_name     = LUSTRE_LOVSUB_NAME,
        .ldt_ops      = &lovsub_device_type_ops,
        .ldt_ctx_tags = LCT_CL_THREAD
}
Definition at line 145 of file lovsub_dev.c.
Referenced by cl2lovsub_dev(), cl2sub_lock(), lov_cl_add_target(), lov_device_init(), lov_sub_find(), lovsub_is_object(), and lu2lovsub_dev().
struct lu_device_type lovsub_device_type
Definition at line 145 of file lovsub_dev.c.
Referenced by cl2lovsub_dev(), cl2sub_lock(), lov_cl_add_target(), lov_device_init(), lov_sub_find(), lovsub_is_object(), and lu2lovsub_dev().
struct lu_device_type_operations lovsub_device_type_ops [static]
Initial value:
 {
        .ldto_device_alloc = lovsub_device_alloc,
        .ldto_device_free  = lovsub_device_free,
        .ldto_device_init    = lovsub_device_init,
        .ldto_device_fini    = lovsub_device_fini
}
Definition at line 135 of file lovsub_dev.c.
struct kmem_cache* lovsub_lock_kmem
Definition at line 53 of file lov_dev.c.
Referenced by lovsub_lock_fini(), and lovsub_lock_init().
struct cl_lock_operations lovsub_lock_ops [static]
Initial value:
 {
        .clo_fini    = lovsub_lock_fini,
}
Definition at line 67 of file lovsub_lock.c.
struct lu_object_operations lovsub_lu_obj_ops [static]
Initial value:
 {
        .loo_object_init      = lovsub_object_init,
        .loo_object_delete    = NULL,
        .loo_object_release   = NULL,
        .loo_object_free      = lovsub_object_free,
        .loo_object_print     = lovsub_object_print,
        .loo_object_invariant = NULL
}
Definition at line 157 of file lovsub_object.c.
struct lu_device_operations lovsub_lu_ops [static]
Initial value:
 {
        .ldo_object_alloc      = lovsub_object_alloc,
        .ldo_process_config    = NULL,
        .ldo_recovery_complete = NULL
}
Definition at line 107 of file lovsub_dev.c.
struct kmem_cache* lovsub_object_kmem
Definition at line 54 of file lov_dev.c.
Referenced by lovsub_object_alloc(), and lovsub_object_free().
struct cl_object_operations lovsub_ops [static]
Initial value:
 {
        .coo_page_init    = lovsub_page_init,
        .coo_lock_init    = lovsub_lock_init,
        .coo_attr_update  = lovsub_attr_update,
        .coo_glimpse      = lovsub_object_glimpse,
        .coo_req_attr_set = lovsub_req_attr_set
}
Definition at line 149 of file lovsub_object.c.
struct cl_page_operations lovsub_page_ops [static]
Initial value:
 {
        .cpo_fini   = lovsub_page_fini
}
Definition at line 60 of file lovsub_page.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.