Lustre: ucache
ucache
Data Structures
struct md_perm
struct md_identity
struct upcall_cache_entry
struct upcall_cache_ops
struct upcall_cache
Defines
#define UC_CACHE_NEW 0x01
#define UC_CACHE_ACQUIRING 0x02
#define UC_CACHE_INVALID 0x04
#define UC_CACHE_EXPIRED 0x08
#define UC_CACHE_IS_NEW(i) ((i)->ue_flags & UC_CACHE_NEW)
#define UC_CACHE_IS_INVALID(i) ((i)->ue_flags & UC_CACHE_INVALID)
#define UC_CACHE_IS_ACQUIRING(i) ((i)->ue_flags & UC_CACHE_ACQUIRING)
#define UC_CACHE_IS_EXPIRED(i) ((i)->ue_flags & UC_CACHE_EXPIRED)
#define UC_CACHE_IS_VALID(i) ((i)->ue_flags == 0)
#define UC_CACHE_SET_NEW(i) ((i)->ue_flags |= UC_CACHE_NEW)
#define UC_CACHE_SET_INVALID(i) ((i)->ue_flags |= UC_CACHE_INVALID)
#define UC_CACHE_SET_ACQUIRING(i) ((i)->ue_flags |= UC_CACHE_ACQUIRING)
#define UC_CACHE_SET_EXPIRED(i) ((i)->ue_flags |= UC_CACHE_EXPIRED)
#define UC_CACHE_SET_VALID(i) ((i)->ue_flags = 0)
#define UC_CACHE_CLEAR_NEW(i) ((i)->ue_flags &= ~UC_CACHE_NEW)
#define UC_CACHE_CLEAR_ACQUIRING(i) ((i)->ue_flags &= ~UC_CACHE_ACQUIRING)
#define UC_CACHE_CLEAR_INVALID(i) ((i)->ue_flags &= ~UC_CACHE_INVALID)
#define UC_CACHE_CLEAR_EXPIRED(i) ((i)->ue_flags &= ~UC_CACHE_EXPIRED)
#define UC_CACHE_HASH_SIZE (128)
#define UC_CACHE_HASH_INDEX(id) ((id) & (UC_CACHE_HASH_SIZE - 1))
#define UC_CACHE_UPCALL_MAXPATH (1024UL)
Functions
struct upcall_cache_entry * upcall_cache_get_entry (struct upcall_cache *cache, __u64 key, void *args)
void upcall_cache_put_entry (struct upcall_cache *cache, struct upcall_cache_entry *entry)
int upcall_cache_downcall (struct upcall_cache *cache, __u32 err, __u64 key, void *args)
void upcall_cache_flush (struct upcall_cache *cache, int force)
static void upcall_cache_flush_idle (struct upcall_cache *cache)
static void upcall_cache_flush_all (struct upcall_cache *cache)
void upcall_cache_flush_one (struct upcall_cache *cache, __u64 key, void *args)
struct upcall_cache * upcall_cache_init (const char *name, const char *upcall, struct upcall_cache_ops *ops)
void upcall_cache_cleanup (struct upcall_cache *cache)
Define Documentation
#define UC_CACHE_ACQUIRING 0x02
Definition at line 49 of file upcall_cache.h.
#define UC_CACHE_CLEAR_ACQUIRING (i) ((i)->ue_flags &= ~UC_CACHE_ACQUIRING)
Definition at line 66 of file upcall_cache.h.
Referenced by upcall_cache_downcall(), and upcall_cache_get_entry().
#define UC_CACHE_CLEAR_EXPIRED (i) ((i)->ue_flags &= ~UC_CACHE_EXPIRED)
Definition at line 68 of file upcall_cache.h.
#define UC_CACHE_CLEAR_INVALID (i) ((i)->ue_flags &= ~UC_CACHE_INVALID)
Definition at line 67 of file upcall_cache.h.
#define UC_CACHE_CLEAR_NEW (i) ((i)->ue_flags &= ~UC_CACHE_NEW)
Definition at line 65 of file upcall_cache.h.
Referenced by upcall_cache_get_entry().
#define UC_CACHE_EXPIRED 0x08
Definition at line 51 of file upcall_cache.h.
#define UC_CACHE_HASH_INDEX (id) ((id) & (UC_CACHE_HASH_SIZE - 1))
Definition at line 100 of file upcall_cache.h.
Referenced by upcall_cache_downcall(), upcall_cache_flush_one(), and upcall_cache_get_entry().
#define UC_CACHE_HASH_SIZE (128)
Definition at line 99 of file upcall_cache.h.
Referenced by upcall_cache_flush(), and upcall_cache_init().
#define UC_CACHE_INVALID 0x04
Definition at line 50 of file upcall_cache.h.
#define UC_CACHE_IS_ACQUIRING (i) ((i)->ue_flags & UC_CACHE_ACQUIRING)
Definition at line 55 of file upcall_cache.h.
Referenced by check_unlink_entry(), upcall_cache_downcall(), and upcall_cache_get_entry().
#define UC_CACHE_IS_EXPIRED (i) ((i)->ue_flags & UC_CACHE_EXPIRED)
Definition at line 56 of file upcall_cache.h.
Referenced by put_entry(), and upcall_cache_downcall().
#define UC_CACHE_IS_INVALID (i) ((i)->ue_flags & UC_CACHE_INVALID)
Definition at line 54 of file upcall_cache.h.
Referenced by check_unlink_entry(), put_entry(), upcall_cache_downcall(), and upcall_cache_get_entry().
#define UC_CACHE_IS_NEW (i) ((i)->ue_flags & UC_CACHE_NEW)
Definition at line 53 of file upcall_cache.h.
Referenced by upcall_cache_get_entry().
#define UC_CACHE_IS_VALID (i) ((i)->ue_flags == 0)
Definition at line 57 of file upcall_cache.h.
Referenced by check_unlink_entry().
#define UC_CACHE_NEW 0x01
Definition at line 48 of file upcall_cache.h.
#define UC_CACHE_SET_ACQUIRING (i) ((i)->ue_flags |= UC_CACHE_ACQUIRING)
Definition at line 61 of file upcall_cache.h.
Referenced by upcall_cache_get_entry().
#define UC_CACHE_SET_EXPIRED (i) ((i)->ue_flags |= UC_CACHE_EXPIRED)
Definition at line 62 of file upcall_cache.h.
Referenced by check_unlink_entry(), upcall_cache_flush(), and upcall_cache_flush_one().
#define UC_CACHE_SET_INVALID (i) ((i)->ue_flags |= UC_CACHE_INVALID)
Definition at line 60 of file upcall_cache.h.
Referenced by upcall_cache_downcall(), and upcall_cache_get_entry().
#define UC_CACHE_SET_NEW (i) ((i)->ue_flags |= UC_CACHE_NEW)
Definition at line 59 of file upcall_cache.h.
Referenced by alloc_entry().
#define UC_CACHE_SET_VALID (i) ((i)->ue_flags = 0)
Definition at line 63 of file upcall_cache.h.
Referenced by upcall_cache_downcall().
#define UC_CACHE_UPCALL_MAXPATH (1024UL)
Definition at line 101 of file upcall_cache.h.
Referenced by mdt_identity_upcall_seq_write().
Function Documentation
void upcall_cache_cleanup (struct upcall_cache * cache)
Definition at line 445 of file upcall_cache.c.
References LIBCFS_FREE, and upcall_cache_flush_all().
Referenced by mdt_fini(), and mdt_init0().
int upcall_cache_downcall (struct upcall_cache * cache, __u32 err, __u64 key, void * args)
Definition at line 292 of file upcall_cache.c.
References CDEBUG, CERROR, cfs_time_shift(), D_OTHER, D_RPCTRACE, downcall_compare(), ENTRY, get_entry(), GOTO, head, LASSERT, list_del_init(), list_for_each_entry, LPU64, upcall_cache_ops::parse_downcall, put_entry(), RETURN, UC_CACHE_CLEAR_ACQUIRING, UC_CACHE_HASH_INDEX, UC_CACHE_IS_ACQUIRING, UC_CACHE_IS_EXPIRED, UC_CACHE_IS_INVALID, UC_CACHE_SET_INVALID, UC_CACHE_SET_VALID, upcall_cache::uc_entry_expire, upcall_cache::uc_hashtable, upcall_cache::uc_lock, upcall_cache::uc_name, upcall_cache::uc_ops, upcall_cache_entry::ue_expire, upcall_cache_entry::ue_hash, upcall_cache_entry::ue_key, and upcall_cache_entry::ue_waitq.
Referenced by lprocfs_identity_info_seq_write().
void upcall_cache_flush (struct upcall_cache * cache, int force)
Definition at line 364 of file upcall_cache.c.
References ENTRY, EXIT, free_entry(), LASSERT, list_for_each_entry_safe, UC_CACHE_HASH_SIZE, UC_CACHE_SET_EXPIRED, upcall_cache::uc_hashtable, upcall_cache::uc_lock, upcall_cache_entry::ue_hash, and upcall_cache_entry::ue_refcount.
Referenced by upcall_cache_flush_all(), and upcall_cache_flush_idle().
static void upcall_cache_flush_all (struct upcall_cache * cache) [inline, static]
Definition at line 146 of file upcall_cache.h.
References upcall_cache_flush().
Referenced by upcall_cache_cleanup().
static void upcall_cache_flush_idle (struct upcall_cache * cache) [inline, static]
Definition at line 141 of file upcall_cache.h.
References upcall_cache_flush().
Referenced by mdt_flush_identity().
void upcall_cache_flush_one (struct upcall_cache * cache, __u64 key, void * args)
Definition at line 387 of file upcall_cache.c.
References cfs_time_current_sec(), CWARN, ENTRY, free_entry(), head, list_for_each_entry, LPU64, UC_CACHE_HASH_INDEX, UC_CACHE_SET_EXPIRED, upcall_cache::uc_hashtable, upcall_cache::uc_lock, upcall_cache::uc_name, upcall_cache_entry::ue_acquire_expire, upcall_cache_entry::ue_expire, upcall_cache_entry::ue_flags, upcall_cache_entry::ue_hash, upcall_cache_entry::ue_key, upcall_cache_entry::ue_refcount, and upcall_compare().
Referenced by mdt_flush_identity().
struct upcall_cache_entry* upcall_cache_get_entry (struct upcall_cache * cache, __u64 key, void * args) [read]
Definition at line 150 of file upcall_cache.c.
References alloc_entry(), CERROR, cfs_time_seconds(), cfs_time_shift(), check_unlink_entry(), ENTRY, free_entry(), get_entry(), GOTO, head, LASSERT, list_add(), list_for_each_entry_safe, list_move(), LPU64, put_entry(), refresh_entry(), RETURN, upcall_cache::uc_acquire_expire, UC_CACHE_CLEAR_ACQUIRING, UC_CACHE_CLEAR_NEW, UC_CACHE_HASH_INDEX, UC_CACHE_IS_ACQUIRING, UC_CACHE_IS_INVALID, UC_CACHE_IS_NEW, UC_CACHE_SET_ACQUIRING, UC_CACHE_SET_INVALID, upcall_cache::uc_hashtable, upcall_cache::uc_lock, upcall_cache_entry::ue_acquire_expire, upcall_cache_entry::ue_hash, upcall_cache_entry::ue_key, upcall_cache_entry::ue_waitq, unlikely, and upcall_compare().
Referenced by mdt_identity_get().
struct upcall_cache* upcall_cache_init (const char * name, const char * upcall, struct upcall_cache_ops * ops) [read]
Definition at line 419 of file upcall_cache.c.
References ENTRY, INIT_LIST_HEAD, LIBCFS_ALLOC, RETURN, strlcpy(), upcall_cache::uc_acquire_expire, UC_CACHE_HASH_SIZE, upcall_cache::uc_entry_expire, upcall_cache::uc_hashtable, upcall_cache::uc_lock, upcall_cache::uc_name, upcall_cache::uc_ops, upcall_cache::uc_upcall, and upcall_cache::uc_upcall_rwlock.
Referenced by mdt_init0().
void upcall_cache_put_entry (struct upcall_cache * cache, struct upcall_cache_entry * entry)
Definition at line 274 of file upcall_cache.c.
References ENTRY, EXIT, LASSERT, put_entry(), upcall_cache::uc_lock, and upcall_cache_entry::ue_refcount.
Referenced by mdt_identity_put().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.