Lustre: cfg
cfg
Data Structures
struct lustre_cfg_bufs
struct lustre_cfg
Defines
#define LUSTRE_CFG_VERSION 0x1cf60001
#define LUSTRE_CFG_MAX_BUFCOUNT 8
#define LCFG_HDR_SIZE(count) cfs_size_round(offsetof (struct lustre_cfg, lcfg_buflens[(count)]))
#define LCFG_REQUIRED 0x0001000
If the LCFG_REQUIRED bit is set in a configuration command, then the client is required to understand this parameter in order to mount the filesystem.
#define LUSTRE_CFG_BUFLEN(lcfg, idx)
Enumerations
enum lcfg_command_type {
LCFG_ATTACH = 0x00cf001, LCFG_DETACH = 0x00cf002, LCFG_SETUP = 0x00cf003, LCFG_CLEANUP = 0x00cf004,
LCFG_ADD_UUID = 0x00cf005, LCFG_DEL_UUID = 0x00cf006, LCFG_MOUNTOPT = 0x00cf007, LCFG_DEL_MOUNTOPT = 0x00cf008,
LCFG_SET_TIMEOUT = 0x00cf009, LCFG_SET_UPCALL = 0x00cf00a, LCFG_ADD_CONN = 0x00cf00b, LCFG_DEL_CONN = 0x00cf00c,
LCFG_LOV_ADD_OBD = 0x00cf00d, LCFG_LOV_DEL_OBD = 0x00cf00e, LCFG_PARAM = 0x00cf00f, LCFG_MARKER = 0x00cf010,
LCFG_LOG_START = 0x00ce011, LCFG_LOG_END = 0x00ce012, LCFG_LOV_ADD_INA = 0x00ce013, LCFG_ADD_MDC = 0x00cf014,
LCFG_DEL_MDC = 0x00cf015, LCFG_SPTLRPC_CONF = 0x00ce016, LCFG_POOL_NEW = 0x00ce020, LCFG_POOL_ADD = 0x00ce021,
LCFG_POOL_REM = 0x00ce022, LCFG_POOL_DEL = 0x00ce023, LCFG_SET_LDLM_TIMEOUT = 0x00ce030, LCFG_PRE_CLEANUP = 0x00cf031,
LCFG_SET_PARAM = 0x00ce032, LCFG_NODEMAP_ADD = 0x00ce040, LCFG_NODEMAP_DEL = 0x00ce041, LCFG_NODEMAP_ADD_RANGE = 0x00ce042,
LCFG_NODEMAP_DEL_RANGE = 0x00ce043, LCFG_NODEMAP_ADD_UIDMAP = 0x00ce044, LCFG_NODEMAP_DEL_UIDMAP = 0x00ce045, LCFG_NODEMAP_ADD_GIDMAP = 0x00ce046,
LCFG_NODEMAP_DEL_GIDMAP = 0x00ce047, LCFG_NODEMAP_ACTIVATE = 0x00ce048, LCFG_NODEMAP_ADMIN = 0x00ce049, LCFG_NODEMAP_TRUSTED = 0x00ce050,
LCFG_NODEMAP_SQUASH_UID = 0x00ce051, LCFG_NODEMAP_SQUASH_GID = 0x00ce052, LCFG_NODEMAP_ADD_SHKEY = 0x00ce053, LCFG_NODEMAP_DEL_SHKEY = 0x00ce054,
LCFG_NODEMAP_TEST_NID = 0x00ce055, LCFG_NODEMAP_TEST_ID = 0x00ce056
}
enum cfg_record_type { PORTALS_CFG_TYPE = 1, LUSTRE_CFG_TYPE = 123 }
Functions
static void lustre_cfg_bufs_set (struct lustre_cfg_bufs *bufs, __u32 index, void *buf, __u32 buflen)
static void lustre_cfg_bufs_set_string (struct lustre_cfg_bufs *bufs, __u32 index, char *str)
static void lustre_cfg_bufs_reset (struct lustre_cfg_bufs *bufs, char *name)
static void * lustre_cfg_buf (struct lustre_cfg *lcfg, __u32 index)
static void lustre_cfg_bufs_init (struct lustre_cfg_bufs *bufs, struct lustre_cfg *lcfg)
static char * lustre_cfg_string (struct lustre_cfg *lcfg, __u32 index)
static __u32 lustre_cfg_len (__u32 bufcount, __u32 *buflens)
static void lustre_cfg_init (struct lustre_cfg *lcfg, int cmd, struct lustre_cfg_bufs *bufs)
static struct lustre_cfg * lustre_cfg_new (int cmd, struct lustre_cfg_bufs *bufs)
static void lustre_cfg_free (struct lustre_cfg *lcfg)
static int lustre_cfg_sanity_check (void *buf, size_t len)
Define Documentation
#define LCFG_HDR_SIZE (count) cfs_size_round(offsetof (struct lustre_cfg, lcfg_buflens[(count)]))
Definition at line 62 of file lustre_cfg.h.
Referenced by lustre_cfg_buf(), lustre_cfg_init(), lustre_cfg_len(), and lustre_cfg_sanity_check().
#define LCFG_REQUIRED 0x0001000
If the LCFG_REQUIRED bit is set in a configuration command, then the client is required to understand this parameter in order to mount the filesystem.
If it does not understand a REQUIRED command the client mount will fail.
Definition at line 69 of file lustre_cfg.h.
Referenced by class_process_config().
#define LUSTRE_CFG_BUFLEN (lcfg, idx)
Value:
((lcfg)->lcfg_bufcount <= (idx)         \
         ? 0                                    \
         : (lcfg)->lcfg_buflens[(idx)])
Definition at line 146 of file lustre_cfg.h.
Referenced by class_add_conn(), class_attach(), class_cleanup(), class_config_llog_handler(), class_config_yaml_output(), class_del_conn(), class_process_config(), client_lwp_config_process(), client_obd_setup(), echo_client_setup(), lmv_process_config(), lmv_setup(), lod_pools_init(), lov_process_config_base(), lov_setup(), lustre_cfg_rename(), mdt_init0(), mgc_process_config(), and ofd_init0().
#define LUSTRE_CFG_MAX_BUFCOUNT 8
Definition at line 60 of file lustre_cfg.h.
Referenced by jt_lcfg_param(), lustre_cfg_bufs_set(), lustre_cfg_sanity_check(), lustre_swab_lustre_cfg(), and print_lustre_cfg().
#define LUSTRE_CFG_VERSION 0x1cf60001
Definition at line 59 of file lustre_cfg.h.
Referenced by class_config_llog_handler(), client_lwp_config_process(), lod_add_device(), lustre_cfg_init(), lustre_cfg_sanity_check(), and lustre_swab_lustre_cfg().
Enumeration Type Documentation
enum cfg_record_type
Enumerator:
PORTALS_CFG_TYPE
LUSTRE_CFG_TYPE
Definition at line 141 of file lustre_cfg.h.
enum lcfg_command_type
Enumerator:
LCFG_ATTACH
create a new obd instance
LCFG_DETACH
destroy obd instance
LCFG_SETUP
call type-specific setup
LCFG_CLEANUP
call type-specific cleanup
LCFG_ADD_UUID
add a nid to a niduuid
LCFG_DEL_UUID
remove a nid from a niduuid
LCFG_MOUNTOPT
create a profile (mdc, osc)
LCFG_DEL_MOUNTOPT
destroy a profile
LCFG_SET_TIMEOUT
set obd_timeout
LCFG_SET_UPCALL
deprecated
LCFG_ADD_CONN
add a failover niduuid to an obd
LCFG_DEL_CONN
remove a failover niduuid
LCFG_LOV_ADD_OBD
add an osc to a lov
LCFG_LOV_DEL_OBD
remove an osc from a lov
LCFG_PARAM
set a proc parameter
LCFG_MARKER
metadata about next cfg rec
LCFG_LOG_START
mgc only, process a cfg log
LCFG_LOG_END
stop processing updates
LCFG_LOV_ADD_INA
like LOV_ADD_OBD, inactive
LCFG_ADD_MDC
add an mdc to a lmv
LCFG_DEL_MDC
remove an mdc from a lmv
LCFG_SPTLRPC_CONF
security
LCFG_POOL_NEW
create an ost pool name
LCFG_POOL_ADD
add an ost to a pool
LCFG_POOL_REM
remove an ost from a pool
LCFG_POOL_DEL
destroy an ost pool name
LCFG_SET_LDLM_TIMEOUT
set ldlm_timeout
LCFG_PRE_CLEANUP
call type-specific pre cleanup cleanup
LCFG_SET_PARAM
use set_param syntax to set a proc parameters
LCFG_NODEMAP_ADD
create a cluster
LCFG_NODEMAP_DEL
destroy a cluster
LCFG_NODEMAP_ADD_RANGE
add a nid range
LCFG_NODEMAP_DEL_RANGE
delete an nid range
LCFG_NODEMAP_ADD_UIDMAP
add a uidmap
LCFG_NODEMAP_DEL_UIDMAP
delete a uidmap
LCFG_NODEMAP_ADD_GIDMAP
add a gidmap
LCFG_NODEMAP_DEL_GIDMAP
delete a gidmap
LCFG_NODEMAP_ACTIVATE
activate cluster id mapping
LCFG_NODEMAP_ADMIN
allow cluster to use id 0
LCFG_NODEMAP_TRUSTED
trust a clusters ids
LCFG_NODEMAP_SQUASH_UID
default map uid
LCFG_NODEMAP_SQUASH_GID
default map gid
LCFG_NODEMAP_ADD_SHKEY
add shared key to cluster
LCFG_NODEMAP_DEL_SHKEY
delete shared key from cluster
LCFG_NODEMAP_TEST_NID
test for nodemap membership
LCFG_NODEMAP_TEST_ID
test uid/gid mapping
Definition at line 71 of file lustre_cfg.h.
Function Documentation
static void* lustre_cfg_buf (struct lustre_cfg * lcfg, __u32 index) [inline, static]
Definition at line 182 of file lustre_cfg.h.
References cfs_size_round(), LASSERT, lustre_cfg::lcfg_bufcount, lustre_cfg::lcfg_buflens, and LCFG_HDR_SIZE.
Referenced by check_markers(), class_config_llog_handler(), class_config_parse_rec(), class_process_config(), class_process_proc_param(), client_lwp_config_process(), client_obd_setup(), lmv_process_config(), lmv_setup(), lod_pools_init(), lod_process_config(), lov_process_config_base(), lov_setup(), lustre_cfg_bufs_init(), lustre_cfg_string(), mgc_process_config(), mgs_fsdb_handler(), mgs_modify_handler(), mgs_srpc_read_handler(), mgs_steal_client_llog_handler(), print_1_cfg(), and print_lustre_cfg().
static void lustre_cfg_bufs_init (struct lustre_cfg_bufs * bufs, struct lustre_cfg * lcfg) [inline, static]
Definition at line 199 of file lustre_cfg.h.
References lustre_cfg_bufs::lcfg_buf, lustre_cfg::lcfg_bufcount, lustre_cfg_bufs::lcfg_bufcount, lustre_cfg_bufs::lcfg_buflen, lustre_cfg::lcfg_buflens, and lustre_cfg_buf().
Referenced by class_config_llog_handler(), and lustre_cfg_rename().
static void lustre_cfg_bufs_reset (struct lustre_cfg_bufs * bufs, char * name) [inline, static]
Definition at line 175 of file lustre_cfg.h.
References lustre_cfg_bufs_set_string().
Referenced by class_manual_cleanup(), do_add_uuid(), do_lcfg(), jt_lcfg_add_conn(), jt_lcfg_attach(), jt_lcfg_del_conn(), jt_lcfg_del_mount_option(), jt_lcfg_del_uuid(), jt_lcfg_mgsparam(), jt_lcfg_mgsparam2(), jt_lcfg_param(), jt_lcfg_set_timeout(), jt_lcfg_setup(), jt_obd_cleanup(), jt_obd_detach(), lustre_cfg_rename(), lustre_disconnect_lwp(), lustre_end_log(), lustre_lwp_add_conn(), lustre_process_log(), lwp_setup(), mdt_quota_init(), mdt_stack_fini(), mdt_stack_init(), mdt_stack_pre_fini(), mgc_apply_recover_logs(), mgs_set_info(), mgs_srpc_set_param_disk(), mgs_wlp_lcfg(), mgs_write_log_quota(), mgs_write_log_sys(), nodemap_cmd(), ofd_stack_fini(), pool_cmd(), record_base(), record_lmv_setup(), record_lov_setup(), record_marker(), and sptlrpc_record_rule_set().
static void lustre_cfg_bufs_set (struct lustre_cfg_bufs * bufs, __u32 index, void * buf, __u32 buflen) [inline, static]
Definition at line 151 of file lustre_cfg.h.
References lustre_cfg_bufs::lcfg_buf, lustre_cfg_bufs::lcfg_bufcount, lustre_cfg_bufs::lcfg_buflen, and LUSTRE_CFG_MAX_BUFCOUNT.
Referenced by class_config_llog_handler(), lustre_cfg_bufs_set_string(), lustre_end_log(), lustre_process_log(), record_lmv_setup(), record_lov_setup(), and record_marker().
static void lustre_cfg_bufs_set_string (struct lustre_cfg_bufs * bufs, __u32 index, char * str) [inline, static]
Definition at line 168 of file lustre_cfg.h.
References lustre_cfg_bufs_set().
Referenced by class_config_llog_handler(), class_manual_cleanup(), do_add_uuid(), do_lcfg(), jt_lcfg_add_conn(), jt_lcfg_attach(), jt_lcfg_del_conn(), jt_lcfg_del_mount_option(), jt_lcfg_del_uuid(), jt_lcfg_mgsparam(), jt_lcfg_mgsparam2(), jt_lcfg_param(), jt_lcfg_setup(), jt_obd_cleanup(), lustre_cfg_bufs_reset(), lustre_cfg_rename(), lustre_disconnect_lwp(), lustre_end_log(), lustre_lwp_add_conn(), lustre_process_log(), lwp_setup(), mdt_quota_init(), mdt_stack_fini(), mdt_stack_init(), mdt_stack_pre_fini(), mgc_apply_recover_logs(), mgs_set_info(), mgs_srpc_set_param_disk(), mgs_wlp_lcfg(), mgs_write_log_quota(), mgs_write_log_sys(), nodemap_cmd(), ofd_stack_fini(), pool_cmd(), record_base(), and sptlrpc_record_rule_set().
static void lustre_cfg_free (struct lustre_cfg * lcfg) [inline, static]
Definition at line 290 of file lustre_cfg.h.
References lustre_cfg::lcfg_bufcount, lustre_cfg::lcfg_buflens, lustre_cfg_len(), and OBD_FREE.
Referenced by class_config_llog_handler(), class_manual_cleanup(), do_add_uuid(), do_lcfg(), jt_lcfg_add_conn(), jt_lcfg_attach(), jt_lcfg_del_conn(), jt_lcfg_del_mount_option(), jt_lcfg_del_uuid(), jt_lcfg_mgsparam(), jt_lcfg_mgsparam2(), jt_lcfg_param(), jt_lcfg_set_timeout(), jt_lcfg_setup(), jt_obd_cleanup(), jt_obd_detach(), lustre_disconnect_lwp(), lustre_end_log(), lustre_lwp_add_conn(), lustre_process_log(), lwp_setup(), mdt_process_config(), mdt_quota_init(), mdt_stack_fini(), mdt_stack_init(), mdt_stack_pre_fini(), mgc_apply_recover_logs(), mgs_set_info(), nodemap_cmd(), ofd_stack_fini(), and pool_cmd().
static void lustre_cfg_init (struct lustre_cfg * lcfg, int cmd, struct lustre_cfg_bufs * bufs) [inline, static]
Definition at line 256 of file lustre_cfg.h.
References lustre_cfg_bufs::lcfg_buf, lustre_cfg_bufs::lcfg_bufcount, lustre_cfg::lcfg_bufcount, lustre_cfg_bufs::lcfg_buflen, lustre_cfg::lcfg_buflens, lustre_cfg::lcfg_command, LCFG_HDR_SIZE, lustre_cfg::lcfg_version, LOGL, and LUSTRE_CFG_VERSION.
Referenced by lustre_cfg_new(), and lustre_cfg_rec_new().
static __u32 lustre_cfg_len (__u32 bufcount, __u32 * buflens) [inline, static]
Definition at line 243 of file lustre_cfg.h.
References cfs_size_round(), ENTRY, LCFG_HDR_SIZE, and RETURN.
Referenced by lcfg_ioctl(), lcfg_mgs_ioctl(), lustre_cfg_free(), lustre_cfg_new(), lustre_cfg_rec_new(), lustre_cfg_sanity_check(), nodemap_cmd(), and pool_cmd().
static struct lustre_cfg* lustre_cfg_new (int cmd, struct lustre_cfg_bufs * bufs) [static, read]
Definition at line 273 of file lustre_cfg.h.
References lustre_cfg_bufs::lcfg_bufcount, lustre_cfg_bufs::lcfg_buflen, lustre_cfg_init(), lustre_cfg_len(), and OBD_ALLOC.
Referenced by class_config_llog_handler(), class_manual_cleanup(), do_add_uuid(), do_lcfg(), jt_lcfg_add_conn(), jt_lcfg_attach(), jt_lcfg_del_conn(), jt_lcfg_del_mount_option(), jt_lcfg_del_uuid(), jt_lcfg_mgsparam(), jt_lcfg_mgsparam2(), jt_lcfg_param(), jt_lcfg_set_timeout(), jt_lcfg_setup(), jt_obd_cleanup(), jt_obd_detach(), lustre_cfg_rename(), lustre_disconnect_lwp(), lustre_end_log(), lustre_lwp_add_conn(), lustre_process_log(), lwp_setup(), mdt_quota_init(), mdt_stack_fini(), mdt_stack_init(), mdt_stack_pre_fini(), mgc_apply_recover_logs(), mgs_set_info(), nodemap_cmd(), ofd_stack_fini(), and pool_cmd().
static int lustre_cfg_sanity_check (void * buf, size_t len) [inline, static]
Definition at line 299 of file lustre_cfg.h.
References ENTRY, lustre_cfg::lcfg_bufcount, lustre_cfg::lcfg_buflens, LCFG_HDR_SIZE, lustre_cfg::lcfg_version, lustre_cfg_len(), LUSTRE_CFG_MAX_BUFCOUNT, LUSTRE_CFG_VERSION, and RETURN.
Referenced by class_config_llog_handler(), class_config_parse_rec(), class_config_yaml_output(), class_handle_ioctl(), client_lwp_config_process(), local_read_handler(), mgs_fsdb_handler(), mgs_modify_handler(), mgs_replace_handler(), mgs_srpc_read_handler(), and mgs_steal_client_llog_handler().
static char* lustre_cfg_string (struct lustre_cfg * lcfg, __u32 index) [inline, static]
Definition at line 210 of file lustre_cfg.h.
References cfs_size_round(), CWARN, lustre_cfg::lcfg_buflens, and lustre_cfg_buf().
Referenced by __sptlrpc_process_config(), class_add_conn(), class_attach(), class_cleanup(), class_config_llog_handler(), class_config_parse_rec(), class_config_yaml_output(), class_del_conn(), class_process_config(), class_process_proc_param(), class_set_global(), client_lwp_config_process(), client_obd_setup(), echo_client_setup(), echo_device_alloc(), ll_process_config(), llog_test_setup(), lod_connect_to_osd(), lod_init0(), lod_pools_init(), lod_process_config(), lov_device_alloc(), lustre_cfg_rename(), lustre_lwp_add_conn(), lustre_lwp_setup(), lwp_init0(), lwp_process_config(), mdd_init0(), mds_device_alloc(), mdt_init0(), mdt_process_config(), mdt_quota_init(), mdt_stack_init(), mgc_process_config(), mgs_fsdb_handler(), mgs_init0(), mgs_iocontrol_nodemap(), mgs_iocontrol_pool(), mgs_replace_handler(), mgs_setparam(), mgs_srpc_read_handler(), mgs_steal_client_llog_handler(), ofd_init0(), ofd_process_config(), ofd_stack_init(), osc_device_alloc(), osd_device_init0(), osd_mount(), osp_init0(), osp_process_config(), print_lustre_cfg(), print_setup_cfg(), process_command(), process_param2_config(), qmt_connect_to_osd(), qmt_device_init0(), and qsd_process_config().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.