Lustre: Exported operations
Exported operations
[Echo Client]
exporting functions to echo client
Functions
static struct echo_object * cl_echo_object_find (struct echo_device *d, const struct ost_id *oi)
static int cl_echo_enqueue0 (struct lu_env *env, struct echo_object *eco, u64 start, u64 end, int mode, __u64 *cookie, __u32 enqflags)
static int cl_echo_cancel0 (struct lu_env *env, struct echo_device *ed, __u64 cookie)
static void echo_commit_callback (const struct lu_env *env, struct cl_io *io, struct cl_page *page)
Detailed Description
exporting functions to echo client
Function Documentation
static int cl_echo_cancel0 (struct lu_env * env, struct echo_device * ed, __u64 cookie) [static]
Definition at line 1241 of file echo_client.c.
References CDEBUG, D_INFO, echo_client_obd::ec_lock, echo_client_obd::ec_locks, echo_lock_release(), echo_device::ed_ec, echo_lock::el_chain, echo_lock::el_cookie, echo_lock::el_refcount, ENTRY, LASSERT, list_del_init(), list_entry, list_for_each, LPX64, and RETURN.
Referenced by cl_echo_object_brw().
static int cl_echo_enqueue0 (struct lu_env * env, struct echo_object * eco, u64 start, u64 end, int mode, __u64 * cookie, __u32 enqflags) [static]
Definition at line 1197 of file echo_client.c.
References cl_io::ci_obj, cl2echo_lock(), cl_index(), cl_lock_at(), cl_lock_request(), cl_lock_descr::cld_end, cl_lock_descr::cld_enq_flags, cl_lock_descr::cld_mode, cl_lock_descr::cld_obj, cl_lock_descr::cld_start, cl_lock::cll_descr, CLM_READ, CLM_WRITE, echo_client_obd::ec_lock, echo_client_obd::ec_locks, echo_client_obd::ec_unique, echo_device_type, echo_env_info(), echo_obj2cl(), echo_device::ed_ec, echo_lock::el_chain, echo_lock::el_cookie, echo_lock::el_refcount, ENTRY, echo_object::eo_dev, echo_thread_info::eti_io, echo_thread_info::eti_lock, LCK_PW, list_add(), list_empty(), and RETURN.
Referenced by cl_echo_object_brw().
static struct echo_object* cl_echo_object_find (struct echo_device * d, const struct ost_id * oi) [static, read]
Definition at line 1109 of file echo_client.c.
References cl2echo_obj(), cl_env_get(), cl_env_put(), cl_object_find(), cl_object_put(), cl_object_conf::coc_oinfo, DOSTID, echo_dev2cl(), echo_env_info(), echo_device::ed_next, ENTRY, echo_object::eo_deleted, echo_object_conf::eoc_cl, echo_object_conf::eoc_oinfo, echo_thread_info::eti_conf, echo_thread_info::eti_fid, FID_SEQ_ECHO, GOTO, LASSERTF, lov_oinfo::loi_oi, OBD_ALLOC_PTR, OBD_FREE_PTR, ostid_id(), ostid_seq(), ostid_to_fid(), POSTID, RETURN, and cl_object_conf::u.
Referenced by echo_create_object(), and echo_get_object().
static void echo_commit_callback (const struct lu_env * env, struct cl_io * io, struct cl_page * page) [static]
Definition at line 1273 of file echo_client.c.
References cl_2queue::c2_qout, cl_page_list_add(), echo_env_info(), echo_thread_info::eti_io, echo_thread_info::eti_queue, and LASSERT.
Referenced by cl_echo_object_brw().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.