Lustre: osc
osc
Data Structures
struct osc_io
State maintained by osc layer for each IO context.
struct osc_session
State maintained by osc layer for the duration of a system call.
struct osc_thread_info
struct osc_object
struct osc_lock
osc-private state of cl_lock.
struct osc_page
Page state private for osc layer.
struct osc_extent
osc_extent data to manage dirty pages.
struct osc_data_version_args
Defines
#define EXTSTR "[%lu -> %lu/%lu]"
#define EXTPARA(ext) (ext)->oe_start, (ext)->oe_end, (ext)->oe_max_end
#define OSC_EXTENT_DUMP(lvl, extent, fmt,...)
#define EASSERTF(expr, ext, fmt, args...)
#define EASSERT(expr, ext) EASSERTF(expr, ext, "\n")
#define sanity_check_nolock(ext) osc_extent_sanity_check0(ext, __func__, __LINE__)
#define sanity_check(ext)
#define OSC_IO_DEBUG(OSC, STR, args...)
#define OSC_DUMP_GRANT(lvl, cli, fmt, args...)
#define list_to_obj(list, item)
#define OTI_PVEC_SIZE 256
#define OSC_FLAGS (ASYNC_URGENT|ASYNC_READY)
Typedefs
typedef int(* osc_page_gang_cbt)(const struct lu_env *, struct cl_io *, struct osc_page *, void *)
Enumerations
enum osc_lock_state {
OLS_NEW, OLS_ENQUEUED, OLS_UPCALL_RECEIVED, OLS_GRANTED,
OLS_CANCELLED
}
enum osc_extent_state {
OES_INV = 0, OES_ACTIVE = 1, OES_CACHE = 2, OES_LOCKING = 3,
OES_LOCK_DONE = 4, OES_RPC = 5, OES_TRUNC = 6, OES_STATE_MAX
}
Functions
static char * ext_flags (struct osc_extent *ext, char *flags)
static char list_empty_marker (struct list_head *list)
static struct osc_extent * rb_extent (struct rb_node *n)
static struct osc_extent * next_extent (struct osc_extent *ext)
static struct osc_extent * prev_extent (struct osc_extent *ext)
static struct osc_extent * first_extent (struct osc_object *obj)
static int osc_extent_sanity_check0 (struct osc_extent *ext, const char *func, const int line)
static int osc_extent_is_overlapped (struct osc_object *obj, struct osc_extent *ext)
sanity check - to make sure there is no overlapped extent in the tree.
static void osc_extent_state_set (struct osc_extent *ext, int state)
static struct osc_extent * osc_extent_alloc (struct osc_object *obj)
static void osc_extent_free (struct osc_extent *ext)
static struct osc_extent * osc_extent_get (struct osc_extent *ext)
static void osc_extent_put (const struct lu_env *env, struct osc_extent *ext)
static void osc_extent_put_trust (struct osc_extent *ext)
osc_extent_put_trust() is a special version of osc_extent_put() when it's known that the caller is not the last user.
static struct osc_extent * osc_extent_search (struct osc_object *obj, pgoff_t index)
Return the extent which includes pgoff , or return the greatest previous extent in the tree.
static struct osc_extent * osc_extent_lookup (struct osc_object *obj, pgoff_t index)
static void osc_extent_insert (struct osc_object *obj, struct osc_extent *ext)
static void osc_extent_erase (struct osc_extent *ext)
static struct osc_extent * osc_extent_hold (struct osc_extent *ext)
static void __osc_extent_remove (struct osc_extent *ext)
static void osc_extent_remove (struct osc_extent *ext)
static int osc_extent_merge (const struct lu_env *env, struct osc_extent *cur, struct osc_extent *victim)
This function is used to merge extents to get better performance.
int osc_extent_release (const struct lu_env *env, struct osc_extent *ext)
Drop user count of osc_extent, and unplug IO asynchronously.
static int overlapped (struct osc_extent *ex1, struct osc_extent *ex2)
static struct osc_extent * osc_extent_find (const struct lu_env *env, struct osc_object *obj, pgoff_t index, unsigned int *grants)
Find or create an extent which includes , core function to manage extent tree.
int osc_extent_finish (const struct lu_env *env, struct osc_extent *ext, int sent, int rc)
Called when IO is finished to an extent.
static int extent_wait_cb (struct osc_extent *ext, enum osc_extent_state state)
static int osc_extent_wait (const struct lu_env *env, struct osc_extent *ext, enum osc_extent_state state)
Wait for the extent's state to become .
static int osc_extent_truncate (struct osc_extent *ext, pgoff_t trunc_index, bool partial)
Discard pages with index greater than .
static int osc_extent_make_ready (const struct lu_env *env, struct osc_extent *ext)
This function is used to make the extent prepared for transfer.
static int osc_extent_expand (struct osc_extent *ext, pgoff_t index, unsigned int *grants)
Quick and simple version of osc_extent_find().
static void osc_extent_tree_dump0 (int level, struct osc_object *obj, const char *func, int line)
static int osc_is_ready (struct osc_object *osc)
static int osc_make_ready (const struct lu_env *env, struct osc_async_page *oap, int cmd)
static int osc_refresh_count (const struct lu_env *env, struct osc_async_page *oap, int cmd)
static int osc_completion (const struct lu_env *env, struct osc_async_page *oap, int cmd, int rc)
static void osc_consume_write_grant (struct client_obd *cli, struct brw_page *pga)
static void osc_release_write_grant (struct client_obd *cli, struct brw_page *pga)
static int osc_reserve_grant (struct client_obd *cli, unsigned int bytes)
To avoid sleeping with object lock held, it's good for us allocate enough grants before entering into critical section.
static void __osc_unreserve_grant (struct client_obd *cli, unsigned int reserved, unsigned int unused)
static void osc_unreserve_grant (struct client_obd *cli, unsigned int reserved, unsigned int unused)
static void osc_free_grant (struct client_obd *cli, unsigned int nr_pages, unsigned int lost_grant, unsigned int dirty_grant)
Free grant after IO is finished or canceled.
static void osc_exit_cache (struct client_obd *cli, struct osc_async_page *oap)
The companion to osc_enter_cache(), called when is no longer part of the dirty accounting due to error.
static int osc_enter_cache_try (struct client_obd *cli, struct osc_async_page *oap, int bytes, int transient)
Non-blocking version of osc_enter_cache() that consumes grant only when it is available.
static int ocw_granted (struct client_obd *cli, struct osc_cache_waiter *ocw)
static int osc_enter_cache (const struct lu_env *env, struct client_obd *cli, struct osc_async_page *oap, int bytes)
The main entry to reserve dirty page accounting.
void osc_wake_cache_waiters (struct client_obd *cli)
static int osc_max_rpc_in_flight (struct client_obd *cli, struct osc_object *osc)
static int osc_makes_rpc (struct client_obd *cli, struct osc_object *osc, int cmd)
static void osc_update_pending (struct osc_object *obj, int cmd, int delta)
static int osc_makes_hprpc (struct osc_object *obj)
static void on_list (struct list_head *item, struct list_head *list, int should_be_on)
static int __osc_list_maint (struct client_obd *cli, struct osc_object *osc)
static int osc_list_maint (struct client_obd *cli, struct osc_object *osc)
static void osc_process_ar (struct osc_async_rc *ar, __u64 xid, int rc)
static void osc_ap_completion (const struct lu_env *env, struct client_obd *cli, struct osc_async_page *oap, int sent, int rc)
static int try_to_add_extent_for_io (struct client_obd *cli, struct osc_extent *ext, struct list_head *rpclist, unsigned int *pc, unsigned int *max_pages)
Try to add extent to one RPC.
static unsigned int get_write_extents (struct osc_object *obj, struct list_head *rpclist)
In order to prevent multiple ptlrpcd from breaking contiguous extents, get_write_extent() takes all appropriate extents in atomic.
static int osc_send_write_rpc (const struct lu_env *env, struct client_obd *cli, struct osc_object *osc) __must_hold(osc)
static int osc_send_read_rpc (const struct lu_env *env, struct client_obd *cli, struct osc_object *osc) __must_hold(osc)
prepare pages for ASYNC io and put pages in send queue.
static struct osc_object * osc_next_obj (struct client_obd *cli)
static void osc_check_rpcs (const struct lu_env *env, struct client_obd *cli) __must_hold(&cli->cl_loi_list_lock)
static int osc_io_unplug0 (const struct lu_env *env, struct client_obd *cli, struct osc_object *osc, int async)
static int osc_io_unplug_async (const struct lu_env *env, struct client_obd *cli, struct osc_object *osc)
void osc_io_unplug (const struct lu_env *env, struct client_obd *cli, struct osc_object *osc)
int osc_prep_async_page (struct osc_object *osc, struct osc_page *ops, struct page *page, loff_t offset)
int osc_queue_async_io (const struct lu_env *env, struct cl_io *io, struct osc_page *ops)
int osc_teardown_async_page (const struct lu_env *env, struct osc_object *obj, struct osc_page *ops)
int osc_flush_async_page (const struct lu_env *env, struct cl_io *io, struct osc_page *ops)
This is called when a page is picked up by kernel to write out.
int osc_cancel_async_page (const struct lu_env *env, struct osc_page *ops)
this is called when a sync waiter receives an interruption.
int osc_queue_sync_pages (const struct lu_env *env, struct osc_object *obj, struct list_head *list, int cmd, int brw_flags)
int osc_cache_truncate_start (const struct lu_env *env, struct osc_object *obj, __u64 size, struct osc_extent **extp)
Called by osc_io_setattr_start() to freeze and destroy covering extents.
void osc_cache_truncate_end (const struct lu_env *env, struct osc_extent *ext)
Called after osc_io_setattr_end to add oio->oi_trunc back to cache.
int osc_cache_wait_range (const struct lu_env *env, struct osc_object *obj, pgoff_t start, pgoff_t end)
Wait for extents in a specific range to be written out.
int osc_cache_writeback_range (const struct lu_env *env, struct osc_object *obj, pgoff_t start, pgoff_t end, int hp, int discard)
Called to write out a range of osc object.
int osc_page_gang_lookup (const struct lu_env *env, struct cl_io *io, struct osc_object *osc, pgoff_t start, pgoff_t end, osc_page_gang_cbt cb, void *cbdata)
Returns a list of pages by a given [start, end] of obj.
static int check_and_discard_cb (const struct lu_env *env, struct cl_io *io, struct osc_page *ops, void *cbdata)
static int discard_cb (const struct lu_env *env, struct cl_io *io, struct osc_page *ops, void *cbdata)
int osc_lock_discard_pages (const struct lu_env *env, struct osc_object *osc, pgoff_t start, pgoff_t end, enum cl_lock_mode mode)
Discard pages protected by the given lock.
static void osc_object_lock (struct osc_object *obj)
static int osc_object_trylock (struct osc_object *obj)
static void osc_object_unlock (struct osc_object *obj)
static int osc_object_is_locked (struct osc_object *obj)
int osc_lock_init (const struct lu_env *env, struct cl_object *obj, struct cl_lock *lock, const struct cl_io *io)
int osc_io_init (const struct lu_env *env, struct cl_object *obj, struct cl_io *io)
struct lu_object * osc_object_alloc (const struct lu_env *env, const struct lu_object_header *hdr, struct lu_device *dev)
int osc_page_init (const struct lu_env *env, struct cl_object *obj, struct cl_page *page, pgoff_t ind)
void osc_index2policy (union ldlm_policy_data *policy, const struct cl_object *obj, pgoff_t start, pgoff_t end)
int osc_lvb_print (const struct lu_env *env, void *cookie, lu_printer_t p, const struct ost_lvb *lvb)
void osc_lru_add_batch (struct client_obd *cli, struct list_head *list)
void osc_page_submit (const struct lu_env *env, struct osc_page *opg, enum cl_req_type crt, int brw_flags)
Helper function called by osc_io_submit() for every page in an immediate transfer (i.e., transferred synchronously).
int osc_set_async_flags (struct osc_object *obj, struct osc_page *opg, u32 async_flags)
int osc_page_cache_add (const struct lu_env *env, const struct cl_page_slice *slice, struct cl_io *io)
int lru_queue_work (const struct lu_env *env, void *data)
void osc_object_set_contended (struct osc_object *obj)
void osc_object_clear_contended (struct osc_object *obj)
int osc_object_is_contended (struct osc_object *obj)
int osc_lock_is_lockless (const struct osc_lock *olck)
static struct osc_thread_info * osc_env_info (const struct lu_env *env)
static struct osc_session * osc_env_session (const struct lu_env *env)
static struct osc_io * osc_env_io (const struct lu_env *env)
static int osc_is_object (const struct lu_object *obj)
static struct osc_device * lu2osc_dev (const struct lu_device *d)
static struct obd_export * osc_export (const struct osc_object *obj)
static struct client_obd * osc_cli (const struct osc_object *obj)
static struct osc_object * cl2osc (const struct cl_object *obj)
static struct cl_object * osc2cl (const struct osc_object *obj)
static enum ldlm_mode osc_cl_lock2ldlm (enum cl_lock_mode mode)
static enum cl_lock_mode osc_ldlm2cl_lock (enum ldlm_mode mode)
static struct osc_page * cl2osc_page (const struct cl_page_slice *slice)
static struct osc_page * oap2osc (struct osc_async_page *oap)
static pgoff_t osc_index (struct osc_page *opg)
static struct cl_page * oap2cl_page (struct osc_async_page *oap)
static struct osc_page * oap2osc_page (struct osc_async_page *oap)
static struct osc_page * osc_cl_page_osc (struct cl_page *page, struct osc_object *osc)
static struct osc_lock * cl2osc_lock (const struct cl_lock_slice *slice)
static struct osc_lock * osc_lock_at (const struct cl_lock *lock)
static int osc_io_srvlock (struct osc_io *oio)
static struct lu_device * osc2lu_dev (struct osc_device *osc)
static void * osc_key_init (const struct lu_context *ctx, struct lu_context_key *key)
static void osc_key_fini (const struct lu_context *ctx, struct lu_context_key *key, void *data)
static void * osc_session_init (const struct lu_context *ctx, struct lu_context_key *key)
static void osc_session_fini (const struct lu_context *ctx, struct lu_context_key *key, void *data)
LU_TYPE_INIT_FINI (osc,&osc_key,&osc_session_key)
static int osc_cl_process_config (const struct lu_env *env, struct lu_device *d, struct lustre_cfg *cfg)
static int osc_device_init (const struct lu_env *env, struct lu_device *d, const char *name, struct lu_device *next)
static struct lu_device * osc_device_fini (const struct lu_env *env, struct lu_device *d)
static struct lu_device * osc_device_free (const struct lu_env *env, struct lu_device *d)
static struct lu_device * osc_device_alloc (const struct lu_env *env, struct lu_device_type *t, struct lustre_cfg *cfg)
static struct osc_io * cl2osc_io (const struct lu_env *env, const struct cl_io_slice *slice)
static void osc_io_fini (const struct lu_env *env, const struct cl_io_slice *io)
static void osc_read_ahead_release (const struct lu_env *env, void *cbdata)
static int osc_io_read_ahead (const struct lu_env *env, const struct cl_io_slice *ios, pgoff_t start, struct cl_read_ahead *ra)
static int osc_io_submit (const struct lu_env *env, const struct cl_io_slice *ios, enum cl_req_type crt, struct cl_2queue *queue)
An implementation of cl_io_operations::cio_io_submit() method for osc layer.
static void osc_page_touch_at (const struct lu_env *env, struct cl_object *obj, pgoff_t idx, size_t to)
This is called when a page is accessed within file in a way that creates new page, if one were missing (i.e., if there were a hole at that place in the file, or accessed page is beyond the current file size).
static int osc_io_commit_async (const struct lu_env *env, const struct cl_io_slice *ios, struct cl_page_list *qin, int from, int to, cl_commit_cbt cb)
static int osc_io_iter_init (const struct lu_env *env, const struct cl_io_slice *ios)
static int osc_io_write_iter_init (const struct lu_env *env, const struct cl_io_slice *ios)
static void osc_io_iter_fini (const struct lu_env *env, const struct cl_io_slice *ios)
static void osc_io_write_iter_fini (const struct lu_env *env, const struct cl_io_slice *ios)
static int osc_io_fault_start (const struct lu_env *env, const struct cl_io_slice *ios)
static int osc_async_upcall (void *a, int rc)
static int trunc_check_cb (const struct lu_env *env, struct cl_io *io, struct osc_page *ops, void *cbdata)
Checks that there are no pages being written in the extent being truncated.
static void osc_trunc_check (const struct lu_env *env, struct cl_io *io, struct osc_io *oio, __u64 size)
static int osc_io_setattr_start (const struct lu_env *env, const struct cl_io_slice *slice)
static void osc_io_setattr_end (const struct lu_env *env, const struct cl_io_slice *slice)
static int osc_data_version_interpret (const struct lu_env *env, struct ptlrpc_request *req, void *arg, int rc)
static int osc_io_data_version_start (const struct lu_env *env, const struct cl_io_slice *slice)
static void osc_io_data_version_end (const struct lu_env *env, const struct cl_io_slice *slice)
static int osc_io_read_start (const struct lu_env *env, const struct cl_io_slice *slice)
static int osc_io_write_start (const struct lu_env *env, const struct cl_io_slice *slice)
static int osc_fsync_ost (const struct lu_env *env, struct osc_object *obj, struct cl_fsync_io *fio)
static int osc_io_fsync_start (const struct lu_env *env, const struct cl_io_slice *slice)
static void osc_io_fsync_end (const struct lu_env *env, const struct cl_io_slice *slice)
static int osc_io_ladvise_start (const struct lu_env *env, const struct cl_io_slice *slice)
static void osc_io_ladvise_end (const struct lu_env *env, const struct cl_io_slice *slice)
static void osc_io_end (const struct lu_env *env, const struct cl_io_slice *slice)
static void osc_lock_to_lockless (const struct lu_env *env, struct osc_lock *ols, int force)
Determine if the lock should be converted into a lockless lock.
static struct ldlm_lock * osc_handle_ptr (struct lustre_handle *handle)
Returns a weak pointer to the ldlm lock identified by a handle.
static int osc_lock_invariant (struct osc_lock *ols)
Invariant that has to be true all of the time.
static void osc_lock_fini (const struct lu_env *env, struct cl_lock_slice *slice)
static void osc_lock_build_policy (const struct lu_env *env, const struct cl_lock *lock, union ldlm_policy_data *policy)
static __u64 osc_enq2ldlm_flags (__u32 enqflags)
static void osc_lock_lvb_update (const struct lu_env *env, struct osc_object *osc, struct ldlm_lock *dlmlock, struct ost_lvb *lvb)
Updates object attributes from a lock value block (lvb) received together with the DLM lock reply from the server.
static void osc_lock_granted (const struct lu_env *env, struct osc_lock *oscl, struct lustre_handle *lockh, bool lvb_update)
static int osc_lock_upcall (void *cookie, struct lustre_handle *lockh, int errcode)
Lock upcall function that is executed either when a reply to ENQUEUE rpc is received from a server, or after osc_enqueue_base() matched a local DLM lock.
static int osc_lock_upcall_agl (void *cookie, struct lustre_handle *lockh, int errcode)
static int osc_lock_flush (struct osc_object *obj, pgoff_t start, pgoff_t end, enum cl_lock_mode mode, int discard)
static int osc_dlm_blocking_ast0 (const struct lu_env *env, struct ldlm_lock *dlmlock, void *data, int flag)
Helper for osc_dlm_blocking_ast() handling discrepancies between cl_lock and ldlm_lock caches.
static int osc_ldlm_blocking_ast (struct ldlm_lock *dlmlock, struct ldlm_lock_desc *new, void *data, int flag)
Blocking ast invoked by ldlm when dlm lock is either blocking progress of some other lock, or is canceled.
static int osc_ldlm_glimpse_ast (struct ldlm_lock *dlmlock, void *data)
static int weigh_cb (const struct lu_env *env, struct cl_io *io, struct osc_page *ops, void *cbdata)
static unsigned long osc_lock_weight (const struct lu_env *env, struct osc_object *oscobj, struct ldlm_extent *extent)
unsigned long osc_ldlm_weigh_ast (struct ldlm_lock *dlmlock)
Get the weight of dlm lock for early cancellation.
static void osc_lock_build_einfo (const struct lu_env *env, const struct cl_lock *lock, struct osc_object *osc, struct ldlm_enqueue_info *einfo)
static bool osc_lock_compatible (const struct osc_lock *qing, const struct osc_lock *qed)
static void osc_lock_wake_waiters (const struct lu_env *env, struct osc_object *osc, struct osc_lock *oscl)
static int osc_lock_enqueue_wait (const struct lu_env *env, struct osc_object *obj, struct osc_lock *oscl)
static int osc_lock_enqueue (const struct lu_env *env, const struct cl_lock_slice *slice, struct cl_io *unused, struct cl_sync_io *anchor)
Implementation of cl_lock_operations::clo_enqueue() method for osc layer.
static void osc_lock_detach (const struct lu_env *env, struct osc_lock *olck)
Breaks a link between osc_lock and dlm_lock.
static void osc_lock_cancel (const struct lu_env *env, const struct cl_lock_slice *slice)
Implements cl_lock_operations::clo_cancel() method for osc layer.
static int osc_lock_print (const struct lu_env *env, void *cookie, lu_printer_t p, const struct cl_lock_slice *slice)
static void osc_lock_lockless_cancel (const struct lu_env *env, const struct cl_lock_slice *slice)
static void osc_lock_set_writer (const struct lu_env *env, const struct cl_io *io, struct cl_object *obj, struct osc_lock *oscl)
struct ldlm_lock * osc_dlmlock_at_pgoff (const struct lu_env *env, struct osc_object *obj, pgoff_t index, enum osc_dap_flags dap_flags)
Finds an existing lock covering given index and optionally different from a given except lock.
static struct lu_object * osc2lu (struct osc_object *osc)
static struct osc_object * lu2osc (const struct lu_object *obj)
static int osc_object_init (const struct lu_env *env, struct lu_object *obj, const struct lu_object_conf *conf)
static void osc_object_free (const struct lu_env *env, struct lu_object *obj)
static int osc_object_print (const struct lu_env *env, void *cookie, lu_printer_t p, const struct lu_object *obj)
static int osc_attr_get (const struct lu_env *env, struct cl_object *obj, struct cl_attr *attr)
static int osc_attr_update (const struct lu_env *env, struct cl_object *obj, const struct cl_attr *attr, unsigned valid)
static int osc_object_glimpse (const struct lu_env *env, const struct cl_object *obj, struct ost_lvb *lvb)
static int osc_object_ast_clear (struct ldlm_lock *lock, void *data)
static int osc_object_prune (const struct lu_env *env, struct cl_object *obj)
static int osc_object_fiemap (const struct lu_env *env, struct cl_object *obj, struct ll_fiemap_info_key *fmkey, struct fiemap *fiemap, size_t *buflen)
static void osc_req_attr_set (const struct lu_env *env, struct cl_object *obj, struct cl_req_attr *attr)
Implementation of struct cl_object_operations::coo_req_attr_set() for osc layer.
int osc_object_invalidate (const struct lu_env *env, struct osc_object *osc)
static int osc_page_protected (const struct lu_env *env, const struct osc_page *opg, enum cl_lock_mode mode, int unref)
static void osc_page_transfer_get (struct osc_page *opg, const char *label)
static void osc_page_transfer_put (const struct lu_env *env, struct osc_page *opg)
static void osc_page_transfer_add (const struct lu_env *env, struct osc_page *opg, enum cl_req_type crt)
This is called once for every page when it is submitted for a transfer either opportunistic (osc_page_cache_add()), or immediate (osc_page_submit()).
static const char * osc_list (struct list_head *head)
static cfs_time_t osc_submit_duration (struct osc_page *opg)
static int osc_page_print (const struct lu_env *env, const struct cl_page_slice *slice, void *cookie, lu_printer_t printer)
static void osc_page_delete (const struct lu_env *env, const struct cl_page_slice *slice)
static void osc_page_clip (const struct lu_env *env, const struct cl_page_slice *slice, int from, int to)
static int osc_page_cancel (const struct lu_env *env, const struct cl_page_slice *slice)
static int osc_page_flush (const struct lu_env *env, const struct cl_page_slice *slice, struct cl_io *io)
static DECLARE_WAIT_QUEUE_HEAD (osc_lru_waitq)
static int lru_shrink_min (struct client_obd *cli)
LRU pages are freed in batch mode.
static int lru_shrink_max (struct client_obd *cli)
free this number at most otherwise it will take too long time to finsih.
static int osc_cache_too_much (struct client_obd *cli)
Check if we can free LRU slots from this OSC.
static void __osc_lru_del (struct client_obd *cli, struct osc_page *opg)
static void osc_lru_del (struct client_obd *cli, struct osc_page *opg)
Page is being destroyed.
static void osc_lru_use (struct client_obd *cli, struct osc_page *opg)
Delete page from LRUlist for redirty.
static void discard_pagevec (const struct lu_env *env, struct cl_io *io, struct cl_page **pvec, int max_index)
static bool lru_page_busy (struct client_obd *cli, struct cl_page *page)
Check if a cl_page can be released, i.e, it's not being used.
long osc_lru_shrink (const struct lu_env *env, struct client_obd *cli, long target, bool force)
Drop of pages from LRU at most.
static long osc_lru_reclaim (struct client_obd *cli, unsigned long npages)
Reclaim LRU pages by an IO thread.
static int osc_lru_alloc (const struct lu_env *env, struct client_obd *cli, struct osc_page *opg)
osc_lru_alloc() is called to allocate an LRU slot for a cl_page.
unsigned long osc_lru_reserve (struct client_obd *cli, unsigned long npages)
osc_lru_reserve() is called to reserve enough LRU slots for I/O.
void osc_lru_unreserve (struct client_obd *cli, unsigned long npages)
osc_lru_unreserve() is called to unreserve LRU slots.
static void unstable_page_accounting (struct ptlrpc_bulk_desc *desc, int factor)
Atomic operations are expensive.
static void add_unstable_page_accounting (struct ptlrpc_bulk_desc *desc)
static void dec_unstable_page_accounting (struct ptlrpc_bulk_desc *desc)
void osc_dec_unstable_pages (struct ptlrpc_request *req)
Performs "unstable" page accounting.
void osc_inc_unstable_pages (struct ptlrpc_request *req)
"unstable" page accounting.
bool osc_over_unstable_soft_limit (struct client_obd *cli)
Check if it piggybacks SOFT_SYNC flag to OST from this OSC.
unsigned long osc_cache_shrink_count (struct shrinker *sk, struct shrink_control *sc)
Return how many LRU pages in the cache of all OSC devices.
unsigned long osc_cache_shrink_scan (struct shrinker *sk, struct shrink_control *sc)
Scan and try to reclaim sc->nr_to_scan cached LRU pages.
Variables
static const char * oes_strings []
struct kmem_cache * osc_lock_kmem
struct kmem_cache * osc_object_kmem
struct kmem_cache * osc_thread_kmem
struct kmem_cache * osc_session_kmem
struct kmem_cache * osc_extent_kmem
struct lu_device_type osc_device_type
struct lu_context_key osc_key
struct lu_context_key osc_session_key
struct kmem_cache * osc_lock_kmem
struct kmem_cache * osc_object_kmem
struct kmem_cache * osc_thread_kmem
struct kmem_cache * osc_session_kmem
struct kmem_cache * osc_extent_kmem
struct kmem_cache * osc_quota_kmem
struct lu_kmem_descr osc_caches []
struct lu_context_key osc_key
struct lu_context_key osc_session_key
static struct lu_device_operations osc_lu_ops
static struct
lu_device_type_operations osc_device_type_ops
struct lu_device_type osc_device_type
static struct cl_io_operations osc_io_ops
static struct cl_lock_operations osc_lock_ops
static struct cl_lock_operations osc_lock_lockless_ops
static struct cl_object_operations osc_ops
static struct lu_object_operations osc_lu_obj_ops
static struct cl_page_operations osc_page_ops
Check if page
Define Documentation
#define EASSERT (expr, ext) EASSERTF(expr, ext, "\n")
Definition at line 148 of file osc_cache.c.
Referenced by get_write_extents(), osc_extent_find(), osc_extent_make_ready(), osc_send_read_rpc(), and try_to_add_extent_for_io().
#define EASSERTF (expr, ext, fmt, args...)
Value:
do {                            \
        if (!(expr)) {                                                  \
                OSC_EXTENT_DUMP(D_ERROR, (ext), fmt, ##args);           \
                osc_extent_tree_dump(D_ERROR, (ext)->oe_obj);           \
                LASSERT(expr);                                          \
        }                                                               \
} while (0)
Definition at line 139 of file osc_cache.c.
Referenced by osc_extent_expand(), osc_extent_find(), osc_extent_insert(), and osc_extent_truncate().
#define EXTPARA (ext) (ext)->oe_start, (ext)->oe_end, (ext)->oe_max_end
Definition at line 106 of file osc_cache.c.
Referenced by osc_extent_find(), and osc_extent_insert().
#define EXTSTR "[%lu -> %lu/%lu]"
Definition at line 105 of file osc_cache.c.
Referenced by osc_extent_find(), and osc_extent_insert().
#define list_to_obj (list, item)
Value:
({                                            \
        struct list_head *__tmp = (list)->next;                               \
        list_del_init(__tmp);                                         \
        list_entry(__tmp, struct osc_object, oo_##item);                      \
})
Definition at line 2124 of file osc_cache.c.
Referenced by osc_next_obj().
#define OSC_DUMP_GRANT (lvl, cli, fmt, args...)
Value:
do {                    \
        struct client_obd *__tmp = (cli);                               \
        CDEBUG(lvl, "%s: grant { dirty: %ld/%ld dirty_pages: %ld/%lu "  \
               "dropped: %ld avail: %ld, dirty_grant: %ld, "            \
               "reserved: %ld, flight: %d } lru {in list: %ld, "        \
               "left: %ld, waiters: %d }" fmt "\n",                     \
               cli_name(__tmp),                                         \
               __tmp->cl_dirty_pages, __tmp->cl_dirty_max_pages,        \
               atomic_long_read(&obd_dirty_pages), obd_max_dirty_pages, \
               __tmp->cl_lost_grant, __tmp->cl_avail_grant,             \
               __tmp->cl_dirty_grant,                                   \
               __tmp->cl_reserved_grant, __tmp->cl_w_in_flight,         \
               atomic_long_read(&__tmp->cl_lru_in_list),                \
               atomic_long_read(&__tmp->cl_lru_busy),                   \
               atomic_read(&__tmp->cl_lru_shrinkers), ##args);          \
} while (0)
Definition at line 1358 of file osc_cache.c.
Referenced by osc_enter_cache(), and osc_enter_cache_try().
#define OSC_EXTENT_DUMP (lvl, extent, fmt, ...)
Value:
do {                          \
        struct osc_extent *__ext = (extent);                                  \
        char __buf[16];                                                       \
                                                                              \
        CDEBUG(lvl,                                                           \
                "extent %p@{" EXTSTR ", "                                     \
                "[%d|%d|%c|%s|%s|%p], [%d|%d|%c|%c|%p|%u|%p]} " fmt,          \
                /* ----- extent part 0 ----- */                               \
                __ext, EXTPARA(__ext),                                        \
                /* ----- part 1 ----- */                                      \
                atomic_read(&__ext->oe_refc),                         \
                atomic_read(&__ext->oe_users),                        \
                list_empty_marker(&__ext->oe_link),                           \
                oes_strings[__ext->oe_state], ext_flags(__ext, __buf),        \
                __ext->oe_obj,                                                \
                /* ----- part 2 ----- */                                      \
                __ext->oe_grants, __ext->oe_nr_pages,                         \
                list_empty_marker(&__ext->oe_pages),                          \
                waitqueue_active(&__ext->oe_waitq) ? '+' : '-',               \
                __ext->oe_dlmlock, __ext->oe_mppr, __ext->oe_owner,           \
                /* ----- part 4 ----- */                                      \
                ## __VA_ARGS__);                                              \
        if (lvl == D_ERROR && __ext->oe_dlmlock != NULL)                      \
                LDLM_ERROR(__ext->oe_dlmlock, "extent: %p", __ext);           \
        else                                                                  \
                LDLM_DEBUG(__ext->oe_dlmlock, "extent: %p", __ext);           \
} while (0)
Definition at line 110 of file osc_cache.c.
Referenced by __osc_extent_remove(), osc_extent_find(), osc_extent_make_ready(), osc_extent_merge(), osc_extent_sanity_check0(), osc_extent_tree_dump0(), osc_extent_wait(), and try_to_add_extent_for_io().
#define OSC_FLAGS (ASYNC_URGENT|ASYNC_READY)
Definition at line 385 of file osc_cl_internal.h.
#define OSC_IO_DEBUG (OSC, STR, args...)
Value:
CDEBUG(D_CACHE, "obj %p ready %d|%c|%c wr %d|%c|%c rd %d|%c " STR,     \
               (OSC), osc_is_ready(OSC),                                       \
               list_empty_marker(&(OSC)->oo_hp_ready_item),                    \
               list_empty_marker(&(OSC)->oo_ready_item),                       \
               atomic_read(&(OSC)->oo_nr_writes),                              \
               list_empty_marker(&(OSC)->oo_hp_exts),                          \
               list_empty_marker(&(OSC)->oo_urgent_exts),                      \
               atomic_read(&(OSC)->oo_nr_reads),                               \
               list_empty_marker(&(OSC)->oo_reading_exts),                     \
               ##args)
Definition at line 1249 of file osc_cache.c.
Referenced by osc_check_rpcs(), and osc_update_pending().
#define OTI_PVEC_SIZE 256
Definition at line 97 of file osc_cl_internal.h.
Referenced by osc_lru_shrink().
#define sanity_check (ext)
Value:
({                                                   \
        int __res;                                                             \
        osc_object_lock((ext)->oe_obj);                                        \
        __res = sanity_check_nolock(ext);                                      \
        osc_object_unlock((ext)->oe_obj);                                      \
        __res;                                                                 \
})
Definition at line 276 of file osc_cache.c.
Referenced by lustre_dissect_struct_ptlrpc_body(), osc_extent_make_ready(), and osc_extent_truncate().
#define sanity_check_nolock (ext) osc_extent_sanity_check0(ext, __func__, __LINE__)
Definition at line 273 of file osc_cache.c.
Referenced by osc_extent_expand(), osc_extent_find(), and osc_extent_wait().
Typedef Documentation
typedef int(* osc_page_gang_cbt)(const struct lu_env *, struct cl_io *, struct osc_page *, void *)
Definition at line 677 of file osc_cl_internal.h.
Enumeration Type Documentation
enum osc_extent_state
Enumerator:
OES_INV
OES_ACTIVE
extent is just initialized or destroyed
OES_CACHE
process is using this extent
OES_LOCKING
extent is ready for IO
OES_LOCK_DONE
locking page to prepare IO
OES_RPC
locking finished, ready to send
OES_TRUNC
in RPC
OES_STATE_MAX
being truncated
Definition at line 571 of file osc_cl_internal.h.
enum osc_lock_state
Enumerator:
OLS_NEW
OLS_ENQUEUED
OLS_UPCALL_RECEIVED
OLS_GRANTED
OLS_CANCELLED
Definition at line 210 of file osc_cl_internal.h.
Function Documentation
static void __osc_extent_remove (struct osc_extent * ext) [static]
Definition at line 482 of file osc_cache.c.
References D_CACHE, LASSERT, list_del_init(), list_empty(), osc_extent::oe_link, osc_extent::oe_obj, osc_extent::oe_pages, OES_INV, OSC_EXTENT_DUMP, osc_extent_erase(), osc_extent_state_set(), and osc_object_is_locked().
Referenced by osc_extent_merge(), and osc_extent_remove().
static int __osc_list_maint (struct client_obd * cli, struct osc_object * osc) [static]
Definition at line 1788 of file osc_cache.c.
References client_obd::cl_loi_hp_ready_list, client_obd::cl_loi_read_list, client_obd::cl_loi_ready_list, client_obd::cl_loi_write_list, OBD_BRW_READ, OBD_BRW_WRITE, on_list(), osc_object::oo_hp_ready_item, osc_object::oo_nr_reads, osc_object::oo_nr_writes, osc_object::oo_read_item, osc_object::oo_ready_item, osc_object::oo_write_item, osc_is_ready(), osc_makes_hprpc(), and osc_makes_rpc().
Referenced by osc_check_rpcs(), and osc_list_maint().
static void __osc_lru_del (struct client_obd * cli, struct osc_page * opg) [static]
Definition at line 572 of file osc_page.c.
References client_obd::cl_lru_in_list, LASSERT, list_del_init(), and osc_page::ops_lru.
Referenced by osc_lru_del(), osc_lru_shrink(), and osc_lru_use().
static void __osc_unreserve_grant (struct client_obd * cli, unsigned int reserved, unsigned int unused) [static]
Definition at line 1431 of file osc_cache.c.
References client_obd::cl_avail_grant, client_obd::cl_dirty_grant, client_obd::cl_lost_grant, and client_obd::cl_reserved_grant.
Referenced by osc_enter_cache_try(), and osc_unreserve_grant().
static void add_unstable_page_accounting (struct ptlrpc_bulk_desc * desc) [inline, static]
Definition at line 1020 of file osc_page.c.
References unstable_page_accounting().
Referenced by osc_inc_unstable_pages().
static int check_and_discard_cb (const struct lu_env * env, struct cl_io * io, struct osc_page * ops, void * cbdata) [static]
Definition at line 3131 of file osc_cache.c.
References __u64, cl_index(), cl_page_discard(), cl_page_disown(), CL_PAGE_EOF, cl_page_own(), CLP_GANG_OKAY, cl_page::cp_state, cl_page_slice::cpl_page, CPS_FREEING, ldlm_extent::end, ldlm_policy_data::l_extent, ldlm_lock::l_policy_data, LASSERT, LDLM_LOCK_PUT, OBD_OBJECT_EOF, osc_page::ops_cl, osc2cl(), OSC_DAP_FL_TEST_LOCK, osc_dlmlock_at_pgoff(), osc_env_info(), osc_index(), osc_thread_info::oti_fn_index, and osc_thread_info::oti_next_index.
static struct osc_object* cl2osc (const struct cl_object * obj) [static, read]
Definition at line 488 of file osc_cl_internal.h.
References cl_object::co_lu, LINVRNT, osc_object::oo_cl, and osc_is_object().
Referenced by brw_interpret(), osc_attr_get(), osc_attr_update(), osc_dlm_blocking_ast0(), osc_io_commit_async(), osc_io_data_version_start(), osc_io_fsync_end(), osc_io_fsync_start(), osc_io_iter_fini(), osc_io_iter_init(), osc_io_ladvise_start(), osc_io_read_ahead(), osc_io_setattr_start(), osc_io_submit(), osc_io_write_iter_fini(), osc_io_write_iter_init(), osc_lock_cancel(), osc_lock_enqueue(), osc_lock_granted(), osc_lock_init(), osc_lock_lockless_cancel(), osc_lock_to_lockless(), osc_lock_upcall(), osc_object_fiemap(), osc_object_glimpse(), osc_object_prune(), osc_page_delete(), osc_page_init(), osc_page_print(), osc_page_touch_at(), osc_page_transfer_add(), osc_req_attr_set(), and osc_trunc_check().
static struct osc_io* cl2osc_io (const struct lu_env * env, const struct cl_io_slice * slice) [static, read]
Definition at line 58 of file osc_io.c.
References LINVRNT, osc_io::oi_cl, and osc_env_io().
Referenced by osc_io_commit_async(), osc_io_data_version_end(), osc_io_data_version_start(), osc_io_end(), osc_io_fsync_end(), osc_io_ladvise_end(), osc_io_ladvise_start(), osc_io_setattr_end(), osc_io_setattr_start(), and osc_io_submit().
static struct osc_lock* cl2osc_lock (const struct cl_lock_slice * slice) [static, read]
Definition at line 555 of file osc_cl_internal.h.
References cl_lock_slice::cls_obj, cl_object::co_lu, LINVRNT, osc_lock::ols_cl, and osc_is_object().
Referenced by osc_lock_at(), osc_lock_cancel(), osc_lock_enqueue(), osc_lock_fini(), osc_lock_lockless_cancel(), and osc_lock_print().
static struct osc_page* cl2osc_page (const struct cl_page_slice * slice) [static, read]
Definition at line 519 of file osc_cl_internal.h.
References cl_object::co_lu, cl_page_slice::cpl_obj, LINVRNT, osc_page::ops_cl, and osc_is_object().
Referenced by osc_cl_page_osc(), osc_page_cache_add(), osc_page_cancel(), osc_page_clip(), osc_page_delete(), osc_page_flush(), and osc_page_print().
static void dec_unstable_page_accounting (struct ptlrpc_bulk_desc * desc) [inline, static]
Definition at line 1025 of file osc_page.c.
References unstable_page_accounting().
Referenced by osc_dec_unstable_pages().
static DECLARE_WAIT_QUEUE_HEAD (osc_lru_waitq) [static]
static int discard_cb (const struct lu_env * env, struct cl_io * io, struct osc_page * ops, void * cbdata) [static]
Definition at line 3169 of file osc_cache.c.
References CL_PAGE_DEBUG, cl_page_discard(), cl_page_disown(), cl_page_own(), cl_page_vmpage(), CLP_GANG_OKAY, cl_page::cp_state, cl_page::cp_type, cl_page_slice::cpl_page, CPS_FREEING, CPT_CACHEABLE, D_ERROR, ergo, LASSERT, osc_page::ops_cl, osc_env_info(), osc_index(), and osc_thread_info::oti_next_index.
static void discard_pagevec (const struct lu_env * env, struct cl_io * io, struct cl_page ** pvec, int max_index) [static]
Definition at line 624 of file osc_page.c.
References cl_page_delete(), cl_page_discard(), cl_page_disown(), cl_page_is_owned(), cl_page_put(), and LASSERT.
Referenced by osc_lru_shrink().
static char* ext_flags (struct osc_extent * ext, char * flags) [inline, static]
Definition at line 76 of file osc_cache.c.
References buf, osc_extent::oe_fsync_wait, osc_extent::oe_hp, osc_extent::oe_intree, osc_extent::oe_memalloc, osc_extent::oe_rw, osc_extent::oe_srvlock, osc_extent::oe_sync, osc_extent::oe_trunc_pending, and osc_extent::oe_urgent.
static int extent_wait_cb (struct osc_extent * ext, enum osc_extent_state state) [static]
Definition at line 901 of file osc_cache.c.
References osc_extent::oe_obj, osc_extent::oe_state, osc_object_lock(), osc_object_unlock(), and ret.
Referenced by osc_extent_wait().
static struct osc_extent* first_extent (struct osc_object * obj) [static, read]
Definition at line 176 of file osc_cache.c.
References osc_object::oo_root, and rb_extent().
Referenced by get_write_extents(), osc_extent_find(), osc_extent_is_overlapped(), and osc_extent_tree_dump0().
static unsigned int get_write_extents (struct osc_object * obj, struct list_head * rpclist) [static]
In order to prevent multiple ptlrpcd from breaking contiguous extents, get_write_extent() takes all appropriate extents in atomic.
The following policy is used to collect extents for IO: 1. Add as many HP extents as possible; 2. Add the first urgent extent in urgent extent list and take it out of urgent list; 3. Add subsequent extents of this urgent extent; 4. If urgent list is not empty, goto 2; 5. Traverse the extent tree from the 1st extent; 6. Above steps exit if there is no space in this RPC.
Definition at line 1948 of file osc_cache.c.
References client_obd::cl_max_pages_per_rpc, EASSERT, first_extent(), LASSERT, list_empty(), list_entry, list_head::next, next_extent(), osc_extent::oe_intree, osc_extent::oe_link, osc_extent::oe_nr_pages, osc_extent::oe_owner, osc_extent::oe_state, OES_CACHE, osc_object::oo_hp_exts, osc_object::oo_urgent_exts, osc_cli(), osc_object_is_locked(), and try_to_add_extent_for_io().
Referenced by osc_send_write_rpc().
static char list_empty_marker (struct list_head * list) [inline, static]
Definition at line 100 of file osc_cache.c.
References list_empty().
static bool lru_page_busy (struct client_obd * cli, struct cl_page * page) [inline, static]
Check if a cl_page can be released, i.e, it's not being used.
If unstable account is turned on, bulk transfer may hold one refcount for recovery so we need to check vmpage refcount as well; otherwise, even we can destroy cl_page but the corresponding vmpage can't be reused.
Definition at line 649 of file osc_page.c.
References cl_client_cache::ccc_unstable_check, client_obd::cl_cache, cl_page_in_use_noref, and cl_page_vmpage().
Referenced by osc_lru_shrink().
int lru_queue_work (const struct lu_env * env, void * data)
Definition at line 521 of file osc_page.c.
References CDEBUG, client_obd::cl_lru_work, cli_name(), D_CACHE, osc_cache_too_much(), osc_lru_shrink(), ptlrpcd_queue_work(), and RETURN.
Referenced by osc_setup().
static int lru_shrink_max (struct client_obd * cli) [inline, static]
free this number at most otherwise it will take too long time to finsih.
Definition at line 482 of file osc_page.c.
References client_obd::cl_max_pages_per_rpc, and client_obd::cl_max_rpcs_in_flight.
Referenced by osc_cache_too_much().
static int lru_shrink_min (struct client_obd * cli) [inline, static]
LRU pages are freed in batch mode.
OSC should at least free this number of pages to avoid running out of LRU slots.
Definition at line 474 of file osc_page.c.
References client_obd::cl_max_pages_per_rpc.
Referenced by osc_cache_too_much().
static struct osc_object* lu2osc (const struct lu_object * obj) [static, read]
Definition at line 61 of file osc_object.c.
References cl_object::co_lu, LINVRNT, osc_object::oo_cl, and osc_is_object().
Referenced by osc_object_free(), osc_object_init(), and osc_object_print().
static struct osc_device* lu2osc_dev (const struct lu_device * d) [static, read]
Definition at line 472 of file osc_cl_internal.h.
References cl_device::cd_lu_dev, lu_device::ld_type, LINVRNT, osc_device::od_cl, and osc_device_type.
Referenced by osc_completion(), osc_device_free(), osc_export(), osc_io_setattr_end(), osc_lock_to_lockless(), and osc_object_is_contended().
LU_TYPE_INIT_FINI (osc , & osc_key, & osc_session_key)
static struct osc_extent* next_extent (struct osc_extent * ext) [static, read]
Definition at line 158 of file osc_cache.c.
References LASSERT, osc_extent::oe_intree, osc_extent::oe_node, and rb_extent().
Referenced by get_write_extents(), osc_extent_expand(), osc_extent_find(), osc_extent_is_overlapped(), and osc_extent_tree_dump0().
static struct cl_page* oap2cl_page (struct osc_async_page * oap) [static, read]
Definition at line 535 of file osc_cl_internal.h.
References cl_page_slice::cpl_page, oap2osc(), and osc_page::ops_cl.
Referenced by osc_build_rpc(), osc_completion(), osc_extent_truncate(), osc_make_ready(), and try_to_add_extent_for_io().
static struct osc_page* oap2osc (struct osc_async_page * oap) [static, read]
Definition at line 525 of file osc_cl_internal.h.
References osc_page::ops_oap.
Referenced by oap2cl_page(), osc_extent_sanity_check0(), osc_extent_truncate(), and osc_refresh_count().
static struct osc_page* oap2osc_page (struct osc_async_page * oap) [static, read]
Definition at line 540 of file osc_cl_internal.h.
References osc_page::ops_oap.
Referenced by brw_interpret(), osc_completion(), osc_lru_add_batch(), osc_make_ready(), and osc_refresh_count().
static int ocw_granted (struct client_obd * cli, struct osc_cache_waiter * ocw) [static]
Definition at line 1541 of file osc_cache.c.
References client_obd::cl_loi_list_lock, list_empty(), and osc_cache_waiter::ocw_entry.
Referenced by osc_enter_cache().
static void on_list (struct list_head * item, struct list_head * list, int should_be_on) [static]
Definition at line 1777 of file osc_cache.c.
References list_add_tail(), list_del_init(), and list_empty().
Referenced by __osc_list_maint().
static struct cl_object* osc2cl (const struct osc_object * obj) [static, read]
Definition at line 494 of file osc_cl_internal.h.
References osc_object::oo_cl.
Referenced by brw_interpret(), check_and_discard_cb(), osc_build_rpc(), osc_check_rpcs(), osc_dlm_blocking_ast0(), osc_dlmlock_at_pgoff(), osc_extent_alloc(), osc_extent_put(), osc_extent_sanity_check0(), osc_extent_truncate(), osc_io_commit_async(), osc_io_read_ahead(), osc_ldlm_glimpse_ast(), osc_ldlm_resource_invalidate(), osc_lock_enqueue(), osc_lock_lvb_update(), osc_lock_upcall_agl(), osc_object_invalidate(), and osc_sync_interpret().
static struct lu_object* osc2lu (struct osc_object * osc) [static, read]
Definition at line 56 of file osc_object.c.
References cl_object::co_lu, and osc_object::oo_cl.
Referenced by osc_object_alloc().
static struct lu_device* osc2lu_dev (struct osc_device * osc) [static, read]
Definition at line 101 of file osc_dev.c.
References cl_device::cd_lu_dev, and osc_device::od_cl.
Referenced by osc_device_alloc().
static void osc_ap_completion (const struct lu_env * env, struct client_obd * cli, struct osc_async_page * oap, int sent, int rc) [static]
Definition at line 1845 of file osc_cache.c.
References __u64, CERROR, client_obd::cl_ar, client_obd::cl_loi_list_lock, ENTRY, EXIT, lov_oinfo::loi_ar, osc_async_page::oap_async_flags, osc_async_page::oap_cmd, osc_async_page::oap_interrupted, osc_async_page::oap_lock, osc_async_page::oap_obj, osc_async_page::oap_request, OBD_BRW_WRITE, osc_object::oo_oinfo, osc_completion(), osc_process_ar(), ptlrpc_req_finished(), and ptlrpc_req_xid().
static int osc_async_upcall (void * a, int rc) [static]
Definition at line 431 of file osc_io.c.
Referenced by osc_fsync_ost(), osc_io_ladvise_start(), and osc_io_setattr_start().
static int osc_attr_get (const struct lu_env * env, struct cl_object * obj, struct cl_attr * attr) [static]
Definition at line 158 of file osc_object.c.
References cl_attr::cat_kms, cl2osc(), cl_lvb2attr(), lov_oinfo::loi_kms, lov_oinfo::loi_kms_valid, lov_oinfo::loi_lvb, and osc_object::oo_oinfo.
static int osc_attr_update (const struct lu_env * env, struct cl_object * obj, const struct cl_attr * attr, unsigned valid) [static]
Definition at line 168 of file osc_object.c.
References __u64, cl_attr::cat_atime, CAT_ATIME, cl_attr::cat_blocks, CAT_BLOCKS, cl_attr::cat_ctime, CAT_CTIME, cl_attr::cat_kms, CAT_KMS, cl_attr::cat_mtime, CAT_MTIME, cl_attr::cat_size, CAT_SIZE, CDEBUG, cl2osc(), D_CACHE, lov_oinfo::loi_kms, loi_kms_set(), lov_oinfo::loi_lvb, LPU64, ost_lvb::lvb_atime, ost_lvb::lvb_blocks, ost_lvb::lvb_ctime, ost_lvb::lvb_mtime, ost_lvb::lvb_size, and osc_object::oo_oinfo.
unsigned long osc_cache_shrink_count (struct shrinker * sk, struct shrink_control * sc)
Return how many LRU pages in the cache of all OSC devices.
Return values:
return # of cached LRU pages times reclaimation tendency
SHRINK_STOP if it cannot do any scanning in this time
Definition at line 1134 of file osc_page.c.
References client_obd::cl_lru_in_list, client_obd::cl_shrink_list, list_for_each_entry, osc_shrink_list, and osc_shrink_lock.
Referenced by osc_cache_shrink(), and osc_init().
unsigned long osc_cache_shrink_scan (struct shrinker * sk, struct shrink_control * sc)
Scan and try to reclaim sc->nr_to_scan cached LRU pages.
Return values:
number of cached LRU pages reclaimed
SHRINK_STOP if it cannot do any scanning in this time
Linux kernel will loop calling this shrinker scan routine with sc->nr_to_scan = SHRINK_BATCH(128 for now) until kernel got enough memory.
If sc->nr_to_scan is 0, the VM is querying the cache size, we don't need to scan and try to reclaim LRU pages, just return 0 and osc_cache_shrink_count() will report the LRU page number.
Definition at line 1161 of file osc_page.c.
References cl_env_nested_get(), cl_env_nested_put(), client_obd::cl_max_pages_per_rpc, client_obd::cl_shrink_list, shrink_control::gfp_mask, list_empty(), list_entry, list_move_tail(), list_head::next, shrink_control::nr_to_scan, osc_lru_shrink(), osc_shrink_list, osc_shrink_lock, and SHRINK_STOP.
Referenced by osc_cache_shrink(), and osc_init().
static int osc_cache_too_much (struct client_obd * cli) [static]
Check if we can free LRU slots from this OSC.
If there exists LRU waiters, we should free slots aggressively. In this way, slots are freed in a steady step to maintain fairness among OSCs.
Return how many LRU pages should be freed.
Definition at line 494 of file osc_page.c.
References cl_client_cache::ccc_lru_max, cl_client_cache::ccc_users, cfs_time_current_sec(), client_obd::cl_cache, client_obd::cl_lru_in_list, client_obd::cl_lru_last_used, client_obd::cl_lru_left, LASSERT, lru_shrink_max(), and lru_shrink_min().
Referenced by lru_queue_work(), osc_lru_del(), and osc_lru_reclaim().
void osc_cache_truncate_end (const struct lu_env * env, struct osc_extent * ext)
Called after osc_io_setattr_end to add oio->oi_trunc back to cache.
Referenced by osc_io_setattr_end().
int osc_cache_truncate_start (const struct lu_env * env, struct osc_object * obj, __u64 size, struct osc_extent ** extp)
Called by osc_io_setattr_start() to freeze and destroy covering extents.
Referenced by osc_io_setattr_start(), and osc_object_invalidate().
int osc_cache_wait_range (const struct lu_env * env, struct osc_object * obj, pgoff_t start, pgoff_t end)
Wait for extents in a specific range to be written out.
The caller must have called osc_cache_writeback_range() to issue IO otherwise it will take a long time for this function to finish.
Caller must hold inode_mutex , or cancel exclusive dlm lock so that nobody else can dirty this range of file while we're waiting for extents to be written.
Referenced by osc_io_fsync_end(), and osc_io_fsync_start().
int osc_cache_writeback_range (const struct lu_env * env, struct osc_object * obj, pgoff_t start, pgoff_t end, int hp, int discard)
Called to write out a range of osc object.
: should be set this is caused by lock cancel; : is set if dirty pages should be dropped - file will be deleted or truncated, this implies there is no partially discarding extents.
Return how many pages will be issued, or error code if error occurred.
Referenced by osc_io_fsync_start(), and osc_lock_flush().
int osc_cancel_async_page (const struct lu_env * env, struct osc_page * ops)
this is called when a sync waiter receives an interruption.
Its job is to get the caller woken as soon as possible. If its page hasn't been put in an rpc yet it can dequeue immediately. Otherwise it has to mark the rpc as desiring interruption which will forcefully complete the rpc once the rpc has timed out.
Referenced by osc_page_cancel().
static void osc_check_rpcs (const struct lu_env * env, struct client_obd * cli) [static]
Definition at line 2166 of file osc_cache.c.
References __osc_list_maint(), CERROR, client_obd::cl_loi_list_lock, cl_object_get(), cl_object_put(), cl_object::co_lu, ENTRY, lu_object_ref_add_at(), lu_object_ref_del_at(), OBD_BRW_READ, OBD_BRW_WRITE, osc2cl(), OSC_IO_DEBUG, osc_list_maint(), osc_makes_rpc(), osc_max_rpc_in_flight(), osc_next_obj(), osc_object_lock(), osc_object_unlock(), osc_send_read_rpc(), osc_send_write_rpc(), and rpcs_in_flight().
Referenced by osc_io_unplug0().
static enum ldlm_mode osc_cl_lock2ldlm (enum cl_lock_mode mode) [inline, static]
Definition at line 499 of file osc_cl_internal.h.
References CLM_GROUP, CLM_READ, CLM_WRITE, LASSERT, LCK_GROUP, LCK_PR, and LCK_PW.
Referenced by osc_lock_build_einfo().
static struct osc_page* osc_cl_page_osc (struct cl_page * page, struct osc_object * osc) [static, read]
Definition at line 546 of file osc_cl_internal.h.
References cl2osc_page(), cl_object_page_slice(), LASSERT, and osc_object::oo_cl.
Referenced by osc_io_commit_async(), osc_io_submit(), and osc_req_attr_set().
static int osc_cl_process_config (const struct lu_env * env, struct lu_device * d, struct lustre_cfg * cfg) [static]
Definition at line 165 of file osc_dev.c.
References ENTRY, lu_device::ld_obd, osc_process_config_base(), and RETURN.
static struct client_obd* osc_cli (const struct osc_object * obj) [static, read]
Definition at line 483 of file osc_cl_internal.h.
References obd_device::cli, obd_export::exp_obd, osc_export(), and obd_device::u.
Referenced by get_write_extents(), osc_extent_expand(), osc_extent_find(), osc_extent_merge(), osc_extent_tree_dump0(), osc_extent_truncate(), osc_extent_wait(), osc_io_iter_init(), osc_io_read_ahead(), osc_io_submit(), osc_io_write_iter_fini(), osc_io_write_iter_init(), osc_page_delete(), osc_page_init(), osc_page_transfer_add(), and osc_update_pending().
static int osc_completion (const struct lu_env * env, struct osc_async_page * oap, int cmd, int rc) [static]
Definition at line 1309 of file osc_cache.c.
References cl_page_completion(), cl_page_put(), cl_object::co_lu, cl_page::cp_reference, cl_page::cp_state, cl_page_slice::cpl_obj, CPS_PAGEIN, CPS_PAGEOUT, CRT_READ, CRT_WRITE, ENTRY, equi, LASSERT, LASSERTF, lu_object::lo_dev, lu2osc_dev(), lu_ref_del(), oap2cl_page(), oap2osc_page(), OBD_BRW_NOQUOTA, OBD_BRW_READ, OBD_BRW_SRVLOCK, OBD_BRW_WRITE, osc_device::od_stats, osc_page::ops_cl, osc_page::ops_submit_time, osc_page::ops_transfer_pinned, and RETURN.
Referenced by osc_ap_completion().
static void osc_consume_write_grant (struct client_obd * cli, struct brw_page * pga) [static]
Definition at line 1376 of file osc_cache.c.
References CDEBUG, client_obd::cl_dirty_pages, client_obd::cl_loi_list_lock, D_CACHE, brw_page::flag, LASSERT, OBD_BRW_FROM_GRANT, obd_dirty_pages, osc_update_next_shrink(), and brw_page::pg.
Referenced by osc_enter_cache_try().
static int osc_data_version_interpret (const struct lu_env * env, struct ptlrpc_request * req, void * arg, int rc) [static]
Definition at line 619 of file osc_io.c.
References osc_data_version_args::dva_oio, ENTRY, EXIT, GOTO, obd_import::imp_connect_data, lustre_get_wire_obdo(), ost_body::oa, osc_io::oi_cbarg, osc_io::oi_oa, osc_io::osc_async_cbargs::opc_rc, osc_io::osc_async_cbargs::opc_sync, req_capsule_server_get(), RMF_OST_BODY, ptlrpc_request::rq_import, and ptlrpc_request::rq_pill.
Referenced by osc_io_data_version_start().
void osc_dec_unstable_pages (struct ptlrpc_request * req)
Performs "unstable" page accounting.
This function balances the increment operations performed in osc_inc_unstable_pages. It is registered as the RPC request callback, and is executed when the bulk RPC is committed on the server. Thus at this point, the pages involved in the bulk transfer are no longer considered unstable.
If this function is called, the request should have been committed or req:rq_unstable must have been set; it implies that the unstable statistic have been added.
Definition at line 1041 of file osc_page.c.
References ptlrpc_bulk_desc::bd_iov_count, cl_client_cache::ccc_unstable_nr, cl_client_cache::ccc_unstable_waitq, client_obd::cl_cache, client_obd::cl_lru_work, client_obd::cl_unstable_count, obd_device::cli, dec_unstable_page_accounting(), obd_import::imp_obd, LASSERT, ptlrpcd_queue_work(), ptlrpc_request::rq_import, and obd_device::u.
Referenced by brw_commit(), and osc_inc_unstable_pages().
static struct lu_device* osc_device_alloc (const struct lu_env * env, struct lu_device_type * t, struct lustre_cfg * cfg) [static, read]
Definition at line 200 of file osc_dev.c.
References cl_device_init(), class_name2obd(), LASSERT, lu_device::ld_ops, lustre_cfg_string(), OBD_ALLOC_PTR, obd_device::obd_self_export, osc_device::od_cl, osc_device::od_exp, osc2lu_dev(), osc_device_free(), osc_lu_ops, osc_setup(), and RETURN.
static struct lu_device* osc_device_fini (const struct lu_env * env, struct lu_device * d) [static, read]
Definition at line 184 of file osc_dev.c.
static struct lu_device* osc_device_free (const struct lu_env * env, struct lu_device * d) [static, read]
Definition at line 190 of file osc_dev.c.
References cl_device_fini(), lu2cl_dev(), lu2osc_dev(), and OBD_FREE_PTR.
Referenced by osc_device_alloc().
static int osc_device_init (const struct lu_env * env, struct lu_device * d, const char * name, struct lu_device * next) [static]
Definition at line 178 of file osc_dev.c.
References RETURN.
static int osc_dlm_blocking_ast0 (const struct lu_env * env, struct ldlm_lock * dlmlock, void * data, int flag) [static]
Helper for osc_dlm_blocking_ast() handling discrepancies between cl_lock and ldlm_lock caches.
Definition at line 429 of file osc_lock.c.
References __u64, CAT_KMS, cl_attr::cat_kms, cl2osc(), cl_index(), cl_object_attr_lock(), cl_object_attr_unlock(), cl_object_attr_update(), cl_object_get(), cl_object_put(), CLM_READ, CLM_WRITE, ldlm_extent::end, ENTRY, ldlm_lock::l_ast_data, ldlm_policy_data::l_extent, ldlm_lock::l_granted_mode, ldlm_lock::l_policy_data, ldlm_lock::l_req_mode, LASSERT, LCK_GROUP, LCK_PW, LDLM_CB_CANCELING, ldlm_extent_shift_kms(), ldlm_is_discard_data, lock_res_and_lock(), lov_oinfo::loi_kms, mode, osc_object::oo_oinfo, osc2cl(), osc_env_info(), osc_lock_flush(), osc_thread_info::oti_attr, RETURN, ldlm_extent::start, and unlock_res_and_lock().
Referenced by osc_ldlm_blocking_ast().
struct ldlm_lock* osc_dlmlock_at_pgoff (const struct lu_env * env, struct osc_object * obj, pgoff_t index, enum osc_dap_flags dap_flags) [read]
Finds an existing lock covering given index and optionally different from a given except lock.
Definition at line 1210 of file osc_lock.c.
References __u64, ENTRY, ldlm_extent::gid, ldlm_policy_data::l_extent, LCK_GROUP, LCK_PR, LCK_PW, LDLM_EXTENT, LDLM_FL_BLOCK_GRANTED, LDLM_FL_CBPENDING, LDLM_FL_TEST_LOCK, LDLM_GID_ANY, ldlm_handle2lock(), lov_oinfo::loi_oi, mode, osc_object::oo_oinfo, osc2cl(), OSC_DAP_FL_CANCELING, OSC_DAP_FL_TEST_LOCK, osc_env_info(), osc_export(), osc_index2policy(), osc_match_base(), ostid_build_res_name(), osc_thread_info::oti_policy, osc_thread_info::oti_resname, RETURN, and unlikely.
Referenced by check_and_discard_cb(), osc_io_read_ahead(), and osc_req_attr_set().
static __u64 osc_enq2ldlm_flags (__u32 enqflags) [static]
Definition at line 162 of file osc_lock.c.
References __u64, CEF_ASYNC, CEF_DISCARD_DATA, CEF_LOCK_MATCH, CEF_MASK, CEF_NONBLOCK, CEF_PEEK, LASSERT, LDLM_FL_AST_DISCARD_DATA, LDLM_FL_BLOCK_NOWAIT, LDLM_FL_HAS_INTENT, LDLM_FL_MATCH_LOCK, and LDLM_FL_TEST_LOCK.
Referenced by osc_lock_init().
static int osc_enter_cache (const struct lu_env * env, struct client_obd * cli, struct osc_async_page * oap, int bytes) [static]
The main entry to reserve dirty page accounting.
Usually the grant reserved in this function will be freed in bulk in osc_free_grant() unless it fails to add osc cache, in that case, it will be freed in osc_exit_cache().
The process will be put into sleep if it's already run out of grant.
Definition at line 1557 of file osc_cache.c.
References osc_async_rc::ar_force_sync, at_max, AT_OFF, CDEBUG, cfs_time_seconds(), client_obd::cl_ar, client_obd::cl_cache_waiters, client_obd::cl_dirty_max_pages, client_obd::cl_dirty_pages, client_obd::cl_loi_list_lock, client_obd::cl_w_in_flight, cli_name(), D_CACHE, ENTRY, EXIT, GOTO, l_wait_event, LASSERT, list_add_tail(), list_del_init(), list_empty(), lov_oinfo::loi_ar, LWI_ON_SIGNAL_NOOP, LWI_TIMEOUT_INTR, osc_async_page::oap_obj, OBD_FAIL_CHECK, OBD_FAIL_OSC_NO_GRANT, obd_timeout, osc_cache_waiter::ocw_entry, osc_cache_waiter::ocw_grant, ocw_granted(), osc_cache_waiter::ocw_oap, osc_cache_waiter::ocw_rc, osc_cache_waiter::ocw_waitq, osc_object::oo_oinfo, OSC_DUMP_GRANT, osc_enter_cache_try(), osc_extent_tree_dump, osc_io_unplug_async(), and RETURN.
static int osc_enter_cache_try (struct client_obd * cli, struct osc_async_page * oap, int bytes, int transient) [static]
Non-blocking version of osc_enter_cache() that consumes grant only when it is available.
Definition at line 1513 of file osc_cache.c.
References __osc_unreserve_grant(), client_obd::cl_dirty_max_pages, client_obd::cl_dirty_pages, client_obd::cl_dirty_transit, D_CACHE, osc_async_page::oap_brw_page, OBD_BRW_NOCACHE, obd_dirty_pages, obd_dirty_transit_pages, obd_max_dirty_pages, osc_consume_write_grant(), OSC_DUMP_GRANT, and osc_reserve_grant().
Referenced by osc_enter_cache(), and osc_wake_cache_waiters().
static struct osc_thread_info* osc_env_info (const struct lu_env * env) [static, read]
Definition at line 444 of file osc_cl_internal.h.
References LASSERT, lu_env::le_ctx, lu_context_key_get(), and osc_key.
Referenced by brw_interpret(), check_and_discard_cb(), discard_cb(), osc_build_rpc(), osc_dlm_blocking_ast0(), osc_dlmlock_at_pgoff(), osc_extent_truncate(), osc_io_ladvise_start(), osc_io_read_start(), osc_io_setattr_start(), osc_io_write_start(), osc_lock_enqueue(), osc_lock_enqueue_wait(), osc_lock_lvb_update(), osc_lock_weight(), osc_lru_shrink(), osc_object_prune(), osc_page_touch_at(), osc_refresh_count(), osc_req_attr_set(), and osc_sync_interpret().
static struct osc_io* osc_env_io (const struct lu_env * env) [static, read]
Definition at line 462 of file osc_cl_internal.h.
References osc_session::os_io, and osc_env_session().
Referenced by cl2osc_io(), osc_extent_find(), osc_fsync_ost(), osc_io_init(), osc_io_iter_fini(), osc_io_iter_init(), osc_io_write_iter_fini(), osc_io_write_iter_init(), osc_lock_enqueue(), osc_lock_set_writer(), osc_lock_to_lockless(), osc_lru_alloc(), and osc_page_init().
static struct osc_session* osc_env_session (const struct lu_env * env) [static, read]
Definition at line 453 of file osc_cl_internal.h.
References LASSERT, lu_env::le_ses, lu_context_key_get(), and osc_session_key.
Referenced by osc_env_io().
static void osc_exit_cache (struct client_obd * cli, struct osc_async_page * oap) [static]
The companion to osc_enter_cache(), called when is no longer part of the dirty accounting due to error.
Definition at line 1502 of file osc_cache.c.
References client_obd::cl_loi_list_lock, osc_async_page::oap_brw_page, and osc_release_write_grant().
static struct obd_export* osc_export (const struct osc_object * obj) [static, read]
Definition at line 478 of file osc_cl_internal.h.
References cl_object::co_lu, lu_object::lo_dev, lu2osc_dev(), osc_device::od_exp, and osc_object::oo_cl.
Referenced by osc_cli(), osc_dlmlock_at_pgoff(), osc_io_data_version_start(), osc_io_ladvise_start(), osc_io_setattr_start(), osc_lock_enqueue(), osc_lock_to_lockless(), osc_object_fiemap(), osc_object_prune(), osc_page_print(), osc_page_submit(), osc_req_attr_set(), and osc_sync_base().
static struct osc_extent* osc_extent_alloc (struct osc_object * obj) [static, read]
Definition at line 321 of file osc_cache.c.
References cl_object_get(), INIT_LIST_HEAD, OBD_SLAB_ALLOC_PTR_GFP, osc_extent::oe_dlmlock, osc_extent::oe_link, osc_extent::oe_node, osc_extent::oe_obj, osc_extent::oe_pages, osc_extent::oe_refc, osc_extent::oe_state, osc_extent::oe_users, osc_extent::oe_waitq, OES_INV, osc2cl(), and osc_extent_kmem.
Referenced by osc_extent_find().
static void osc_extent_erase (struct osc_extent * ext) [static]
Definition at line 455 of file osc_cache.c.
References LASSERT, osc_extent::oe_intree, osc_extent::oe_node, osc_extent::oe_obj, osc_object::oo_root, osc_extent_put_trust(), and osc_object_is_locked().
Referenced by __osc_extent_remove().
static int osc_extent_expand (struct osc_extent * ext, pgoff_t index, unsigned int * grants) [static]
Quick and simple version of osc_extent_find().
This function is frequently called to expand the extent for the same IO. To expand the extent, the page index must be in the same or next chunk of ext->oe_end.
Definition at line 1161 of file osc_cache.c.
References client_obd::cl_chunkbits, client_obd::cl_max_extent_pages, EASSERTF, ENTRY, EXIT, GOTO, LASSERT, next_extent(), osc_extent::oe_end, osc_extent::oe_grants, osc_extent::oe_max_end, osc_extent::oe_obj, osc_extent::oe_start, osc_cli(), osc_extent_is_overlapped(), osc_object_lock(), osc_object_unlock(), RETURN, and sanity_check_nolock.
static struct osc_extent* osc_extent_find (const struct lu_env * env, struct osc_object * obj, pgoff_t index, unsigned int * grants) [static, read]
Find or create an extent which includes , core function to manage extent tree.
Definition at line 619 of file osc_cache.c.
References client_obd::cl_chunkbits, client_obd::cl_grant_extent_tax, client_obd::cl_max_extent_pages, client_obd::cl_max_pages_per_rpc, cl_lock_descr::cld_end, cl_lock_descr::cld_mode, cl_lock_descr::cld_start, cl_lock::cll_descr, CLM_WRITE, cl_lock_slice::cls_lock, D_CACHE, EASSERT, EASSERTF, ENTRY, EXIT, EXTPARA, EXTSTR, first_extent(), GOTO, ldlm_lock::l_reference, LASSERT, LASSERTF, LDLM_LOCK_GET, lu_ref_add(), min_t, next_extent(), osc_extent::oe_dlmlock, osc_extent::oe_end, osc_extent::oe_fsync_wait, osc_extent::oe_grants, osc_extent::oe_max_end, osc_extent::oe_mppr, osc_extent::oe_start, osc_extent::oe_state, OES_CACHE, OES_INV, osc_io::oi_write_osclock, osc_lock::ols_cl, osc_lock::ols_dlmlock, OLS_GRANTED, osc_lock::ols_hold, osc_lock::ols_state, osc_cli(), osc_env_io(), osc_extent_alloc(), OSC_EXTENT_DUMP, osc_extent_get(), osc_extent_hold(), osc_extent_insert(), osc_extent_is_overlapped(), osc_extent_merge(), osc_extent_put(), osc_extent_search(), osc_extent_tree_dump, osc_extent_wait(), osc_object_lock(), osc_object_unlock(), overlapped(), RETURN, and sanity_check_nolock.
int osc_extent_finish (const struct lu_env * env, struct osc_extent * ext, int sent, int rc)
Called when IO is finished to an extent.
Referenced by brw_interpret(), osc_build_rpc(), and osc_send_write_rpc().
static void osc_extent_free (struct osc_extent * ext) [static]
Definition at line 343 of file osc_cache.c.
References OBD_SLAB_FREE_PTR, and osc_extent_kmem.
Referenced by osc_extent_put().
static struct osc_extent* osc_extent_get (struct osc_extent * ext) [static, read]
Definition at line 348 of file osc_cache.c.
References LASSERT, and osc_extent::oe_refc.
Referenced by osc_extent_find(), osc_extent_hold(), osc_extent_insert(), osc_extent_lookup(), osc_extent_make_ready(), and osc_extent_merge().
static struct osc_extent* osc_extent_hold (struct osc_extent * ext) [static, read]
Definition at line 467 of file osc_cache.c.
References LASSERT, list_del_init(), OBD_BRW_WRITE, osc_extent::oe_link, osc_extent::oe_nr_pages, osc_extent::oe_obj, osc_extent::oe_state, osc_extent::oe_users, OES_ACTIVE, OES_CACHE, osc_extent_get(), osc_extent_state_set(), osc_object_is_locked(), and osc_update_pending().
Referenced by osc_extent_find(), and osc_extent_wait().
static void osc_extent_insert (struct osc_object * obj, struct osc_extent * ext) [static]
Definition at line 428 of file osc_cache.c.
References EASSERTF, EXTPARA, EXTSTR, LASSERT, osc_extent::oe_end, osc_extent::oe_intree, osc_extent::oe_node, osc_extent::oe_obj, osc_extent::oe_start, osc_object::oo_root, osc_extent_get(), osc_object_is_locked(), and rb_extent().
Referenced by osc_extent_find().
static int osc_extent_is_overlapped (struct osc_object * obj, struct osc_extent * ext) [static]
sanity check - to make sure there is no overlapped extent in the tree.
Definition at line 288 of file osc_cache.c.
References extent_debug, first_extent(), LASSERT, next_extent(), osc_extent::oe_end, osc_extent::oe_start, and osc_object_is_locked().
Referenced by osc_extent_expand(), and osc_extent_find().
static struct osc_extent* osc_extent_lookup (struct osc_object * obj, pgoff_t index) [static, read]
Definition at line 416 of file osc_cache.c.
References osc_extent::oe_end, osc_extent::oe_start, osc_extent_get(), and osc_extent_search().
static int osc_extent_make_ready (const struct lu_env * env, struct osc_extent * ext) [static]
This function is used to make the extent prepared for transfer.
A race with flusing page - ll_writepage() has to be handled cautiously.
Definition at line 1080 of file osc_cache.c.
References ASYNC_COUNT_STABLE, ASYNC_READY, D_CACHE, EASSERT, ENTRY, LASSERT, LASSERTF, list_for_each_entry, osc_async_page::oap_async_flags, osc_async_page::oap_lock, osc_async_page::oap_obj_off, osc_async_page::oap_page_off, OBD_BRW_WRITE, osc_extent::oe_nr_pages, osc_extent::oe_obj, osc_extent::oe_owner, osc_extent::oe_pages, osc_extent::oe_state, OES_LOCKING, OES_RPC, OSC_EXTENT_DUMP, osc_extent_get(), osc_extent_state_set(), osc_make_ready(), osc_object_lock(), osc_object_unlock(), osc_refresh_count(), RETURN, and sanity_check.
Referenced by osc_send_write_rpc().
static int osc_extent_merge (const struct lu_env * env, struct osc_extent * cur, struct osc_extent * victim) [static]
This function is used to merge extents to get better performance.
It checks if and are contiguous at block level.
Definition at line 505 of file osc_cache.c.
References __osc_extent_remove(), client_obd::cl_chunkbits, client_obd::cl_grant_extent_tax, client_obd::cl_max_extent_pages, D_CACHE, LASSERT, list_del_init(), list_splice_init(), max, osc_extent::oe_dlmlock, osc_extent::oe_end, osc_extent::oe_fsync_wait, osc_extent::oe_grants, osc_extent::oe_link, osc_extent::oe_max_end, osc_extent::oe_memalloc, osc_extent::oe_nr_pages, osc_extent::oe_obj, osc_extent::oe_pages, osc_extent::oe_start, osc_extent::oe_state, osc_extent::oe_urgent, OES_CACHE, osc_cli(), OSC_EXTENT_DUMP, osc_extent_get(), osc_extent_put(), and osc_object_is_locked().
Referenced by osc_extent_find().
static void osc_extent_put (const struct lu_env * env, struct osc_extent * ext) [static]
Definition at line 355 of file osc_cache.c.
References cl_object_put(), ldlm_lock::l_reference, LASSERT, LDLM_LOCK_PUT, list_empty(), lu_ref_add(), osc_extent::oe_dlmlock, osc_extent::oe_intree, osc_extent::oe_link, osc_extent::oe_obj, osc_extent::oe_refc, osc_extent::oe_state, osc_extent::oe_users, OES_INV, osc2cl(), and osc_extent_free().
Referenced by osc_extent_find(), and osc_extent_merge().
static void osc_extent_put_trust (struct osc_extent * ext) [static]
osc_extent_put_trust() is a special version of osc_extent_put() when it's known that the caller is not the last user.
This is to address the problem of lacking of lu_env ;-).
Definition at line 380 of file osc_cache.c.
References LASSERT, osc_extent::oe_obj, osc_extent::oe_refc, and osc_object_is_locked().
Referenced by osc_extent_erase().
int osc_extent_release (const struct lu_env * env, struct osc_extent * ext)
Drop user count of osc_extent, and unplug IO asynchronously.
Referenced by osc_extent_wait(), osc_io_commit_async(), and osc_io_end().
static void osc_extent_remove (struct osc_extent * ext) [static]
Definition at line 492 of file osc_cache.c.
References __osc_extent_remove(), osc_extent::oe_obj, osc_object_lock(), and osc_object_unlock().
static int osc_extent_sanity_check0 (struct osc_extent * ext, const char * func, const int line) [static]
Definition at line 182 of file osc_cache.c.
References cl_offset(), D_ERROR, ldlm_extent::end, extent_debug, GOTO, ldlm_policy_data::l_extent, ldlm_lock::l_granted_mode, ldlm_lock::l_policy_data, LCK_GROUP, LCK_PW, ldlm_is_failed, list_empty(), list_for_each_entry, oap2osc(), osc_extent::oe_dlmlock, osc_extent::oe_end, osc_extent::oe_fsync_wait, osc_extent::oe_grants, osc_extent::oe_hp, osc_extent::oe_max_end, osc_extent::oe_mppr, osc_extent::oe_nr_pages, osc_extent::oe_obj, osc_extent::oe_pages, osc_extent::oe_refc, osc_extent::oe_start, osc_extent::oe_state, osc_extent::oe_sync, osc_extent::oe_urgent, osc_extent::oe_users, OES_ACTIVE, OES_CACHE, OES_INV, OES_STATE_MAX, osc2cl(), OSC_EXTENT_DUMP, osc_index(), osc_object_is_locked(), and ldlm_extent::start.
static struct osc_extent* osc_extent_search (struct osc_object * obj, pgoff_t index) [static, read]
Return the extent which includes pgoff , or return the greatest previous extent in the tree.
Definition at line 391 of file osc_cache.c.
References LASSERT, osc_extent::oe_end, osc_extent::oe_start, osc_object::oo_root, osc_object_is_locked(), and rb_extent().
Referenced by osc_extent_find(), and osc_extent_lookup().
static void osc_extent_state_set (struct osc_extent * ext, int state) [static]
Definition at line 308 of file osc_cache.c.
References LASSERT, osc_extent::oe_obj, osc_extent::oe_state, osc_extent::oe_waitq, OES_INV, OES_STATE_MAX, and osc_object_is_locked().
Referenced by __osc_extent_remove(), osc_extent_hold(), osc_extent_make_ready(), osc_send_read_rpc(), and osc_send_write_rpc().
static void osc_extent_tree_dump0 (int level, struct osc_object * obj, const char * func, int line) [static]
Definition at line 1213 of file osc_cache.c.
References CDEBUG, first_extent(), list_for_each_entry, next_extent(), osc_extent::oe_link, osc_object::oo_hp_exts, osc_object::oo_reading_exts, osc_object::oo_urgent_exts, osc_cli(), and OSC_EXTENT_DUMP.
static int osc_extent_truncate (struct osc_extent * ext, pgoff_t trunc_index, bool partial) [static]
Discard pages with index greater than .
If is overlapped with , then partial truncate happens.
Definition at line 961 of file osc_cache.c.
References __u64, cl_io::ci_obj, CIT_MISC, client_obd::cl_chunkbits, cl_env_nested_get(), cl_env_nested_put(), cl_io_fini(), cl_io_init(), cl_object_top(), cl_page_discard(), cl_page_disown(), cl_page_get(), cl_page_own(), cl_page_put(), cl_page::cp_reference, cl_page::cp_state, CPS_FREEING, EASSERTF, ENTRY, ergo, GOTO, LASSERT, list_del_init(), list_empty(), list_for_each_entry_safe, lu_ref_add(), lu_ref_del(), oap2cl_page(), oap2osc(), osc_async_page::oap_pending_item, osc_async_page::oap_rpc_item, osc_extent::oe_end, osc_extent::oe_grants, osc_extent::oe_max_end, osc_extent::oe_nr_pages, osc_extent::oe_obj, osc_extent::oe_pages, osc_extent::oe_start, osc_extent::oe_state, osc_extent::oe_urgent, OES_TRUNC, osc2cl(), osc_cli(), osc_env_info(), osc_free_grant(), osc_index(), osc_object_lock(), osc_object_unlock(), osc_thread_info::oti_io, RETURN, and sanity_check.
static int osc_extent_wait (const struct lu_env * env, struct osc_extent * ext, enum osc_extent_state state) [static]
Wait for the extent's state to become .
Definition at line 915 of file osc_cache.c.
References cfs_time_seconds(), cli_name(), D_ERROR, ENTRY, extent_wait_cb(), l_wait_event, LASSERT, LWI_INTR, LWI_ON_SIGNAL_NOOP, LWI_TIMEOUT_INTR, osc_extent::oe_hp, osc_extent::oe_obj, osc_extent::oe_rc, osc_extent::oe_state, osc_extent::oe_urgent, osc_extent::oe_waitq, OES_ACTIVE, OES_CACHE, OES_INV, osc_cli(), OSC_EXTENT_DUMP, osc_extent_hold(), osc_extent_release(), osc_object_lock(), osc_object_unlock(), RETURN, and sanity_check_nolock.
Referenced by osc_extent_find().
int osc_flush_async_page (const struct lu_env * env, struct cl_io * io, struct osc_page * ops)
This is called when a page is picked up by kernel to write out.
We should find out the corresponding extent and add the whole extent into urgent list. The extent may be being truncated or used, handle it carefully.
Referenced by osc_page_flush().
static void osc_free_grant (struct client_obd * cli, unsigned int nr_pages, unsigned int lost_grant, unsigned int dirty_grant) [static]
Free grant after IO is finished or canceled.
is used to remember how many grants we have allocated but not used, we should return these grants to OST. There're two cases where grants can be lost: 1. truncate; 2. blocksize at OST is less than PAGE_CACHE_SIZE and a partial page was written. In this case OST may use less chunks to serve this partial write. OSTs don't actually know the page size on the client side. so clients have to calculate lost grant by the blocksize on the OST. See filter_grant_check() for details.
Definition at line 1472 of file osc_cache.c.
References CDEBUG, client_obd::cl_avail_grant, client_obd::cl_chunkbits, client_obd::cl_dirty_grant, client_obd::cl_dirty_pages, client_obd::cl_grant_extent_tax, client_obd::cl_loi_list_lock, client_obd::cl_lost_grant, D_CACHE, obd_dirty_pages, and osc_wake_cache_waiters().
Referenced by osc_extent_truncate().
static int osc_fsync_ost (const struct lu_env * env, struct osc_object * obj, struct cl_fsync_io * fio) [static]
Definition at line 754 of file osc_io.c.
References ENTRY, lov_oinfo::loi_oi, obdo::o_blocks, obdo::o_oi, obdo::o_size, obdo::o_valid, OBD_MD_FLBLOCKS, OBD_MD_FLGROUP, OBD_MD_FLID, OBD_MD_FLSIZE, obdo_set_parent_fid(), osc_io::oi_cbarg, osc_io::oi_oa, osc_object::oo_oinfo, osc_async_upcall(), osc_env_io(), osc_sync_base(), PTLRPCD_SET, and RETURN.
Referenced by osc_io_fsync_start().
static struct ldlm_lock* osc_handle_ptr (struct lustre_handle * handle) [static, read]
Returns a weak pointer to the ldlm lock identified by a handle.
Returned pointer cannot be dereferenced, as lock is not protected from concurrent reclaim. This function is a helper for osc_lock_invariant().
Definition at line 75 of file osc_lock.c.
References ldlm_handle2lock(), and LDLM_LOCK_PUT.
Referenced by osc_lock_invariant().
void osc_inc_unstable_pages (struct ptlrpc_request * req)
"unstable" page accounting.
See: osc_dec_unstable_pages.
Definition at line 1068 of file osc_page.c.
References add_unstable_page_accounting(), ptlrpc_bulk_desc::bd_iov_count, cl_client_cache::ccc_unstable_check, cl_client_cache::ccc_unstable_nr, client_obd::cl_cache, client_obd::cl_unstable_count, obd_device::cli, obd_import::imp_obd, osc_dec_unstable_pages(), ptlrpc_request::rq_committed, ptlrpc_request::rq_import, ptlrpc_request::rq_lock, ptlrpc_request::rq_unstable, obd_device::u, and unlikely.
Referenced by brw_interpret().
static pgoff_t osc_index (struct osc_page * opg) [inline, static]
Definition at line 530 of file osc_cl_internal.h.
References cl_page_slice::cpl_index, and osc_page::ops_cl.
Referenced by check_and_discard_cb(), discard_cb(), osc_extent_sanity_check0(), osc_extent_truncate(), osc_io_commit_async(), osc_page_delete(), osc_page_print(), osc_refresh_count(), osc_req_attr_set(), trunc_check_cb(), and weigh_cb().
void osc_index2policy (union ldlm_policy_data * policy, const struct cl_object * obj, pgoff_t start, pgoff_t end)
Definition at line 222 of file osc_page.c.
References cl_offset(), ldlm_extent::end, ldlm_policy_data::l_extent, and ldlm_extent::start.
Referenced by osc_dlmlock_at_pgoff(), and osc_lock_build_policy().
static int osc_io_commit_async (const struct lu_env * env, const struct cl_io_slice * ios, struct cl_page_list * qin, int from, int to, cl_commit_cbt cb) [static]
Definition at line 265 of file osc_io.c.
References CDEBUG, cl_io_slice::cis_io, cl_io_slice::cis_obj, cl2osc(), cl2osc_io(), cl_io_is_sync_write(), cl_page_clip(), cl_page_list_del(), cl_page_list_first(), cl_page_list_last(), D_CACHE, D_INFO, ENTRY, LASSERT, list_empty(), osc_async_page::oap_pending_item, osc_async_page::oap_rpc_item, osc_io::oi_active, osc_io::oi_lockless, osc_page::ops_cl, osc_page::ops_oap, osc2cl(), osc_cl_page_osc(), osc_extent_release(), osc_index(), osc_page_cache_add(), osc_page_touch_at(), cl_page_list::pl_nr, and RETURN.
static void osc_io_data_version_end (const struct lu_env * env, const struct cl_io_slice * slice) [static]
Definition at line 697 of file osc_io.c.
References cl_io::ci_data_version, cl_io::ci_result, cl_io_slice::cis_io, cl2osc_io(), ENTRY, EXIT, obdo::o_data_version, obdo::o_valid, OBD_MD_FLDATAVERSION, osc_io::oi_cbarg, osc_io::oi_oa, and cl_io::u.
static int osc_io_data_version_start (const struct lu_env * env, const struct cl_io_slice * slice) [static]
Definition at line 644 of file osc_io.c.
References cl_io::ci_data_version, cl_io_slice::cis_io, cl_io_slice::cis_obj, cl2osc(), cl2osc_io(), class_exp2cliimp(), CLASSERT, osc_data_version_args::dva_oio, ENTRY, obd_import::imp_connect_data, LL_DV_RD_FLUSH, LL_DV_WR_FLUSH, lov_oinfo::loi_oi, LUSTRE_OST_VERSION, lustre_set_wire_obdo(), obdo::o_flags, obdo::o_oi, obdo::o_valid, ost_body::oa, OBD_FL_FLUSH, OBD_FL_SRVLOCK, OBD_MD_FLFLAGS, OBD_MD_FLGROUP, OBD_MD_FLID, osc_io::oi_cbarg, osc_io::oi_oa, osc_object::oo_oinfo, osc_data_version_interpret(), osc_export(), OST_GETATTR, ptlrpc_req_async_args, ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), ptlrpcd_add_req(), req_capsule_client_get(), RETURN, RMF_OST_BODY, ptlrpc_request::rq_import, ptlrpc_request::rq_pill, RQF_OST_GETATTR, and cl_io::u.
static void osc_io_end (const struct lu_env * env, const struct cl_io_slice * slice) [static]
Definition at line 913 of file osc_io.c.
References cl2osc_io(), osc_io::oi_active, and osc_extent_release().
static int osc_io_fault_start (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 409 of file osc_io.c.
References CDEBUG, cl_io::ci_fault, cl_io_slice::cis_io, cl_io_slice::cis_obj, D_INFO, ENTRY, osc_page_touch_at(), RETURN, and cl_io::u.
static void osc_io_fini (const struct lu_env * env, const struct cl_io_slice * io) [static]
Definition at line 72 of file osc_io.c.
static void osc_io_fsync_end (const struct lu_env * env, const struct cl_io_slice * slice) [static]
Definition at line 821 of file osc_io.c.
References cl_io::ci_fsync, cl_io::ci_result, cl_io_slice::cis_io, cl_io_slice::cis_obj, cl2osc(), cl2osc_io(), CL_FSYNC_ALL, CL_FSYNC_LOCAL, cl_index(), end, osc_io::oi_cbarg, osc_cache_wait_range(), start, and cl_io::u.
static int osc_io_fsync_start (const struct lu_env * env, const struct cl_io_slice * slice) [static]
Definition at line 781 of file osc_io.c.
References cl_io::ci_fsync, cl_io_slice::cis_io, cl_io_slice::cis_obj, cl2osc(), CL_FSYNC_ALL, CL_FSYNC_DISCARD, cl_index(), CL_PAGE_EOF, end, ENTRY, OBD_OBJECT_EOF, osc_cache_wait_range(), osc_cache_writeback_range(), osc_fsync_ost(), RETURN, start, and cl_io::u.
int osc_io_init (const struct lu_env * env, struct cl_object * obj, struct cl_io * io)
Definition at line 981 of file osc_io.c.
References cl_io_slice_add(), CL_IO_SLICE_CLEAN, osc_io::oi_cl, and osc_env_io().
static void osc_io_iter_fini (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 379 of file osc_io.c.
References cl_io_slice::cis_obj, cl2osc(), LASSERT, osc_io::oi_is_active, osc_object::oo_io_waitq, osc_object::oo_nr_ios, and osc_env_io().
Referenced by osc_io_write_iter_fini().
static int osc_io_iter_init (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 338 of file osc_io.c.
References cl_io_slice::cis_obj, cl2osc(), client_obd::cl_import, obd_import::imp_invalid, obd_import::imp_lock, likely, osc_io::oi_is_active, osc_object::oo_nr_ios, osc_cli(), and osc_env_io().
Referenced by osc_io_write_iter_init().
static void osc_io_ladvise_end (const struct lu_env * env, const struct cl_io_slice * slice) [static]
Definition at line 897 of file osc_io.c.
References cl_io::ci_ladvise, cl_io::ci_result, cl_io_slice::cis_io, cl2osc_io(), LF_ASYNC, osc_io::oi_cbarg, and cl_io::u.
static int osc_io_ladvise_start (const struct lu_env * env, const struct cl_io_slice * slice) [static]
Definition at line 843 of file osc_io.c.
References cl_io::ci_ladvise, cl_io_slice::cis_io, cl_io_slice::cis_obj, cl2osc(), cl2osc_io(), ENTRY, LADVISE_MAGIC, ladvise_hdr::lah_advise, ladvise_hdr::lah_count, ladvise_hdr::lah_flags, ladvise_hdr::lah_magic, lu_buf::lb_buf, LF_ASYNC, lu_ladvise::lla_advice, lu_ladvise::lla_end, lu_ladvise::lla_start, lov_oinfo::loi_oi, lu_buf_realloc(), obdo::o_oi, obdo::o_valid, OBD_MD_FLID, obdo_set_parent_fid(), offsetof, osc_io::oi_cbarg, osc_io::oi_oa, osc_object::oo_oinfo, osc_async_upcall(), osc_env_info(), osc_export(), osc_ladvise_base(), osc_thread_info::oti_ladvise_buf, PTLRPCD_SET, RETURN, and cl_io::u.
static int osc_io_read_ahead (const struct lu_env * env, const struct cl_io_slice * ios, pgoff_t start, struct cl_read_ahead * ra) [static]
Definition at line 87 of file osc_io.c.
References cl_io_slice::cis_obj, cl2osc(), cl_index(), client_obd::cl_max_pages_per_rpc, cl_read_ahead::cra_cbdata, cl_read_ahead::cra_end, cl_read_ahead::cra_release, cl_read_ahead::cra_rpc_size, ldlm_extent::end, ENTRY, ldlm_lock::l_ast_data, ldlm_policy_data::l_extent, ldlm_lock::l_policy_data, ldlm_lock::l_req_mode, LASSERT, LCK_PR, ldlm_lock2handle(), ldlm_lock_addref(), ldlm_lock_decref(), osc2cl(), osc_cli(), osc_dlmlock_at_pgoff(), osc_read_ahead_release(), and RETURN.
static int osc_io_read_start (const struct lu_env * env, const struct cl_io_slice * slice) [static]
Definition at line 719 of file osc_io.c.
References CAT_ATIME, cl_attr::cat_atime, cl_io::ci_noatime, cl_io_slice::cis_io, cl_io_slice::cis_obj, cl_object_attr_lock(), cl_object_attr_unlock(), cl_object_attr_update(), ENTRY, LTIME_S, osc_env_info(), osc_thread_info::oti_attr, and RETURN.
static void osc_io_setattr_end (const struct lu_env * env, const struct cl_io_slice * slice) [static]
Definition at line 582 of file osc_io.c.
References __u64, cl_io::ci_result, cl_io::ci_setattr, cl_io_slice::cis_io, cl_io_slice::cis_obj, cl2osc_io(), cl_io_is_trunc(), cl_object::co_lu, LASSERT, lu_object::lo_dev, lu2osc_dev(), osc_device::od_stats, osc_io::oi_cbarg, osc_io::oi_lockless, osc_io::oi_trunc, osc_device::osc_stats::os_lockless_truncates, osc_cache_truncate_end(), osc_trunc_check(), size, and cl_io::u.
static int osc_io_setattr_start (const struct lu_env * env, const struct cl_io_slice * slice) [static]
Definition at line 482 of file osc_io.c.
References __u64, ATTR_CTIME_SET, CAT_ATIME, cl_attr::cat_atime, CAT_CTIME, cl_attr::cat_ctime, CAT_KMS, cl_attr::cat_kms, CAT_MTIME, cl_attr::cat_mtime, CAT_SIZE, cl_attr::cat_size, cl_io::ci_setattr, cl_io_slice::cis_io, cl_io_slice::cis_obj, cl2osc(), cl2osc_io(), cl_io_is_trunc(), cl_object_attr_get(), cl_object_attr_lock(), cl_object_attr_unlock(), cl_object_attr_update(), LASSERT, lov_oinfo::loi_oi, ost_lvb::lvb_atime, ost_lvb::lvb_ctime, ost_lvb::lvb_mtime, obdo::o_atime, obdo::o_blocks, obdo::o_ctime, obdo::o_flags, obdo::o_mtime, obdo::o_oi, obdo::o_size, obdo::o_stripe_idx, obdo::o_valid, OBD_FL_SRVLOCK, OBD_MD_FLATIME, OBD_MD_FLBLOCKS, OBD_MD_FLCTIME, OBD_MD_FLFLAGS, OBD_MD_FLGROUP, OBD_MD_FLID, OBD_MD_FLMTIME, OBD_MD_FLSIZE, OBD_OBJECT_EOF, obdo_set_parent_fid(), osc_io::oi_cbarg, osc_io::oi_lockless, osc_io::oi_oa, osc_io::oi_trunc, osc_object::oo_oinfo, osc_async_upcall(), osc_cache_truncate_start(), osc_env_info(), osc_export(), osc_punch_base(), osc_setattr_async(), osc_thread_info::oti_attr, PTLRPCD_SET, size, and cl_io::u.
static int osc_io_srvlock (struct osc_io * oio) [inline, static]
Definition at line 566 of file osc_cl_internal.h.
References cl_io::ci_no_srvlock, cl_io_slice::cis_io, osc_io::oi_cl, and osc_io::oi_lockless.
Referenced by osc_io_submit(), and osc_page_init().
static int osc_io_submit (const struct lu_env * env, const struct cl_io_slice * ios, enum cl_req_type crt, struct cl_2queue * queue) [static]
An implementation of cl_io_operations::cio_io_submit() method for osc layer.
Iterates over pages in the in-queue, prepares each for io by calling cl_page_prep() and then either submits them through osc_io_submit_page() or, if page is already submitted, changes osc flags through osc_set_async_flags().
Definition at line 124 of file osc_io.c.
References ASYNC_COUNT_STABLE, ASYNC_READY, ASYNC_URGENT, cl_2queue::c2_qin, cl_2queue::c2_qout, CDEBUG, cl_io_slice::cis_obj, cl2osc(), cl2osc_io(), client_obd::cl_max_pages_per_rpc, cl_page_list_del(), cl_page_list_for_each_safe, cl_page_list_move(), cl_page_prep(), cmd, cl_page::cp_owner, cl_page::cp_sync_io, CRT_WRITE, D_CACHE, D_INFO, D_READA, LASSERT, list_add_tail(), list_empty(), LIST_HEAD_INIT, osc_async_page::oap_async_flags, osc_async_page::oap_lock, osc_async_page::oap_obj, osc_async_page::oap_pending_item, osc_async_page::oap_rpc_item, OBD_BRW_READ, OBD_BRW_SRVLOCK, OBD_BRW_WRITE, osc_page::ops_oap, osc_cl_page_osc(), osc_cli(), osc_io_srvlock(), osc_page_submit(), osc_queue_sync_pages(), and cl_page_list::pl_nr.
void osc_io_unplug (const struct lu_env * env, struct client_obd * cli, struct osc_object * osc)
Referenced by brw_interpret(), brw_queue_work(), and osc_import_event().
static int osc_io_unplug0 (const struct lu_env * env, struct client_obd * cli, struct osc_object * osc, int async) [static]
Definition at line 2234 of file osc_cache.c.
References CDEBUG, client_obd::cl_loi_list_lock, client_obd::cl_writeback_work, D_CACHE, LASSERT, osc_check_rpcs(), osc_list_maint(), and ptlrpcd_queue_work().
Referenced by osc_io_unplug_async().
static int osc_io_unplug_async (const struct lu_env * env, struct client_obd * cli, struct osc_object * osc) [static]
Definition at line 2254 of file osc_cache.c.
References osc_io_unplug0().
Referenced by osc_enter_cache().
static void osc_io_write_iter_fini (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 394 of file osc_io.c.
References cl_io_slice::cis_obj, cl2osc(), osc_io::oi_lru_reserved, osc_io::oi_write_osclock, osc_cli(), osc_env_io(), osc_io_iter_fini(), and osc_lru_unreserve().
static int osc_io_write_iter_init (const struct lu_env * env, const struct cl_io_slice * ios) [static]
Definition at line 358 of file osc_io.c.
References cl_io::ci_rw, cl_io_slice::cis_io, cl_io_slice::cis_obj, cl2osc(), cl_io_is_append(), cl_io_rw_common::crw_count, cl_io_rw_common::crw_pos, ENTRY, osc_io::oi_lru_reserved, osc_cli(), osc_env_io(), osc_io_iter_init(), osc_lru_reserve(), RETURN, and cl_io::u.
static int osc_io_write_start (const struct lu_env * env, const struct cl_io_slice * slice) [static]
Definition at line 737 of file osc_io.c.
References CAT_CTIME, cl_attr::cat_ctime, CAT_MTIME, cl_attr::cat_mtime, cl_io_slice::cis_obj, cl_object_attr_lock(), cl_object_attr_unlock(), cl_object_attr_update(), ENTRY, LTIME_S, OBD_FAIL_OSC_DELAY_SETTIME, OBD_FAIL_TIMEOUT, osc_env_info(), osc_thread_info::oti_attr, and RETURN.
static int osc_is_object (const struct lu_object * obj) [inline, static]
Definition at line 467 of file osc_cl_internal.h.
References lu_device::ld_type, lu_object::lo_dev, and osc_device_type.
Referenced by cl2osc(), cl2osc_lock(), cl2osc_page(), and lu2osc().
static int osc_is_ready (struct osc_object * osc) [inline, static]
Definition at line 1243 of file osc_cache.c.
References list_empty(), osc_object::oo_hp_ready_item, and osc_object::oo_ready_item.
Referenced by __osc_list_maint().
static void osc_key_fini (const struct lu_context * ctx, struct lu_context_key * key, void * data) [static]
Definition at line 123 of file osc_dev.c.
References lu_buf_free(), OBD_SLAB_FREE_PTR, osc_thread_kmem, and osc_thread_info::oti_ladvise_buf.
static void* osc_key_init (const struct lu_context * ctx, struct lu_context_key * key) [static]
Definition at line 112 of file osc_dev.c.
References OBD_SLAB_ALLOC_PTR_GFP, and osc_thread_kmem.
static enum cl_lock_mode osc_ldlm2cl_lock (enum ldlm_mode mode) [inline, static]
Definition at line 509 of file osc_cl_internal.h.
References CLM_GROUP, CLM_READ, CLM_WRITE, LASSERT, LCK_GROUP, LCK_PR, and LCK_PW.
Referenced by osc_lock_granted().
static int osc_ldlm_blocking_ast (struct ldlm_lock * dlmlock, struct ldlm_lock_desc * new, void * data, int flag) [static]
Blocking ast invoked by ldlm when dlm lock is either blocking progress of some other lock, or is canceled.
This function is installed as a ldlm_lock::l_blocking_ast() for client extent locks.
Control flow is tricky, because ldlm uses the same call-back (ldlm_lock::l_blocking_ast()) for both blocking and cancellation ast's.
Parameters:
dlmlock lock for which ast occurred.
new description of a conflicting lock in case of blocking ast.
data value of dlmlock->l_ast_data
flag LDLM_CB_BLOCKING or LDLM_CB_CANCELING. Used to distinguish cancellation and blocking ast's.
Possible use cases:
ldlm calls dlmlock->l_blocking_ast(..., LDLM_CB_CANCELING) to cancel lock due to lock lru pressure, or explicit user request to purge locks.
ldlm calls dlmlock->l_blocking_ast(..., LDLM_CB_BLOCKING) to notify us that dlmlock conflicts with another lock that some client is enqueuing. Lock is canceled.
cl_lock_cancel() is called. osc_lock_cancel() calls ldlm_cli_cancel() that calls
dlmlock->l_blocking_ast(..., LDLM_CB_CANCELING)
recursively entering osc_ldlm_blocking_ast().
client cancels lock voluntary (e.g., as a part of early cancellation):
cl_lock_cancel()-> osc_lock_cancel()-> ldlm_cli_cancel()-> dlmlock->l_blocking_ast(..., LDLM_CB_CANCELING)
Definition at line 534 of file osc_lock.c.
References cl_env_nested_get(), cl_env_nested_put(), ENTRY, LBUG, LCF_ASYNC, LDLM_CB_BLOCKING, LDLM_CB_CANCELING, ldlm_cli_cancel(), ldlm_lock2handle(), osc_dlm_blocking_ast0(), and RETURN.
Referenced by osc_lock_build_einfo().
static int osc_ldlm_glimpse_ast (struct ldlm_lock * dlmlock, void * data) [static]
Definition at line 582 of file osc_lock.c.
References cl_env_nested_get(), cl_env_nested_put(), cl_object_get(), cl_object_glimpse(), cl_object_put(), ELDLM_NO_LOCK_DATA, ENTRY, exp_connect_lvb_type(), ldlm_lock::l_ast_data, LASSERT, LDLM_GL_CALLBACK, lock_res_and_lock(), lustre_msg_get_opc(), lustre_pack_reply(), osc2cl(), RCL_SERVER, req_capsule_extend(), req_capsule_server_get(), req_capsule_server_pack(), req_capsule_set_size(), req_capsule_shrink(), RETURN, RMF_DLM_LVB, ptlrpc_request::rq_export, ptlrpc_request::rq_pill, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_status, RQF_LDLM_GL_CALLBACK, and unlock_res_and_lock().
Referenced by osc_lock_build_einfo().
unsigned long osc_ldlm_weigh_ast (struct ldlm_lock * dlmlock)
Get the weight of dlm lock for early cancellation.
Definition at line 693 of file osc_lock.c.
References cl_env_nested_get(), cl_env_nested_put(), ENTRY, EXIT, GOTO, ldlm_lock::l_ast_data, ldlm_policy_data::l_extent, ldlm_lock::l_policy_data, ldlm_lock::l_resource, LASSERT, LDLM_EXTENT, list_for_each_entry, ldlm_resource::lr_type, osc_lock::ols_dlmlock, osc_lock::ols_nextlock_oscobj, osc_object::oo_ol_list, osc_object::oo_ol_spin, osc_lock_weight(), and RETURN.
Referenced by osc_cancel_weight().
static const char* osc_list (struct list_head * head) [static]
Definition at line 230 of file osc_page.c.
References list_empty().
Referenced by osc_page_print().
static int osc_list_maint (struct client_obd * cli, struct osc_object * osc) [static]
Definition at line 1810 of file osc_cache.c.
References __osc_list_maint(), and client_obd::cl_loi_list_lock.
Referenced by osc_check_rpcs(), and osc_io_unplug0().
static struct osc_lock* osc_lock_at (const struct cl_lock * lock) [static, read]
Definition at line 561 of file osc_cl_internal.h.
References cl2osc_lock(), cl_lock_at(), and osc_device_type.
static void osc_lock_build_einfo (const struct lu_env * env, const struct cl_lock * lock, struct osc_object * osc, struct ldlm_enqueue_info * einfo) [static]
Definition at line 743 of file osc_lock.c.
References cl_lock_descr::cld_mode, cl_lock::cll_descr, ldlm_enqueue_info::ei_cb_bl, ldlm_enqueue_info::ei_cb_cp, ldlm_enqueue_info::ei_cb_gl, ldlm_enqueue_info::ei_cbdata, ldlm_enqueue_info::ei_mode, ldlm_enqueue_info::ei_type, ldlm_completion_ast(), LDLM_EXTENT, osc_cl_lock2ldlm(), osc_ldlm_blocking_ast(), and osc_ldlm_glimpse_ast().
Referenced by osc_lock_init().
static void osc_lock_build_policy (const struct lu_env * env, const struct cl_lock * lock, union ldlm_policy_data * policy) [static]
Definition at line 152 of file osc_lock.c.
References cl_lock_descr::cld_end, cl_lock_descr::cld_gid, cl_lock_descr::cld_obj, cl_lock_descr::cld_start, cl_lock::cll_descr, ldlm_extent::gid, ldlm_policy_data::l_extent, and osc_index2policy().
Referenced by osc_lock_enqueue().
static void osc_lock_cancel (const struct lu_env * env, const struct cl_lock_slice * slice) [static]
Implements cl_lock_operations::clo_cancel() method for osc layer.
This is called (as part of cl_lock_cancel()) when lock is canceled either voluntary (LRU pressure, early cancellation, umount, etc.) or due to the conflict with some other lock some where in the cluster. This function does the following:
invalidates all pages protected by this lock (after sending dirty ones to the server, as necessary);
decref's underlying ldlm lock;
cancels ldlm lock (ldlm_cli_cancel()).
Definition at line 1066 of file osc_lock.c.
References cl2osc(), cl2osc_lock(), cl_lock_slice::cls_obj, ENTRY, EXIT, LDLM_FL_LVB_READY, LINVRNT, OLS_CANCELLED, osc_lock::ols_flags, osc_lock::ols_state, osc_lock_detach(), osc_lock_invariant(), and osc_lock_wake_waiters().
static bool osc_lock_compatible (const struct osc_lock * qing, const struct osc_lock * qed) [static]
Definition at line 809 of file osc_lock.c.
References cl_lock_descr::cld_end, cl_lock_descr::cld_mode, cl_lock_descr::cld_start, cl_lock::cll_descr, CLM_READ, cl_lock_slice::cls_lock, osc_lock::ols_cl, osc_lock::ols_glimpse, OLS_GRANTED, and osc_lock::ols_state.
Referenced by osc_lock_enqueue_wait().
static void osc_lock_detach (const struct lu_env * env, struct osc_lock * olck) [static]
Breaks a link between osc_lock and dlm_lock.
Definition at line 1025 of file osc_lock.c.
References lustre_handle::cookie, ldlm_enqueue_info::ei_mode, ENTRY, EXIT, ldlm_lock::l_reference, LASSERT, ldlm_lock_decref(), LDLM_LOCK_RELEASE, lu_ref_del(), osc_lock::ols_dlmlock, osc_lock::ols_einfo, osc_lock::ols_handle, osc_lock::ols_has_ref, osc_lock::ols_hold, and RETURN_EXIT.
Referenced by osc_lock_cancel().
int osc_lock_discard_pages (const struct lu_env * env, struct osc_object * osc, pgoff_t start, pgoff_t end, enum cl_lock_mode mode)
Discard pages protected by the given lock.
This function traverses radix tree to find all covering pages and discard them. If a page is being covered by other locks, it should remain in cache.
If error happens on any step, the process continues anyway (the reasoning behind this being that lock cancellation cannot be delayed indefinitely).
Referenced by osc_lock_flush(), and osc_object_invalidate().
static int osc_lock_enqueue (const struct lu_env * env, const struct cl_lock_slice * slice, struct cl_io * unused, struct cl_sync_io * anchor) [static]
Implementation of cl_lock_operations::clo_enqueue() method for osc layer.
This initiates ldlm enqueue:
cancels conflicting locks early (osc_lock_enqueue_wait());
calls osc_enqueue_base() to do actual enqueue.
osc_enqueue_base() is supplied with an upcall function that is executed when lock is received either after a local cached ldlm lock is matched, or when a reply from the server is received.
This function does not wait for the network communication to complete.
DLM lock's ast data must be osc_object; if glimpse or AGL lock, async of osc_enqueue_base() must be true, DLM's enqueue callback set to osc_lock_upcall() with cookie as osc_lock.
Definition at line 925 of file osc_lock.c.
References cl2osc(), cl2osc_lock(), cl_object_get(), cl_object_put(), cl_sync_io_note(), cl_lock_descr::cld_mode, cl_lock::cll_descr, CLM_READ, cl_lock_slice::cls_lock, cl_lock_slice::cls_obj, cl_sync_io::csi_sync_nr, ldlm_enqueue_info::ei_cbdata, ENTRY, equi, ergo, GOTO, LASSERT, LASSERTF, LDLM_FL_TEST_LOCK, lov_oinfo::loi_kms_valid, lov_oinfo::loi_oi, osc_io::oi_lockless, osc_lock::ols_agl, OLS_CANCELLED, osc_lock::ols_dlmlock, osc_lock::ols_einfo, OLS_ENQUEUED, osc_lock::ols_flags, osc_lock::ols_glimpse, OLS_GRANTED, osc_lock::ols_hold, osc_lock::ols_lvb, osc_lock::ols_owner, osc_lock::ols_state, osc_object::oo_oinfo, osc2cl(), osc_enqueue_base(), osc_env_info(), osc_env_io(), osc_export(), osc_lock_build_policy(), osc_lock_enqueue_wait(), osc_lock_is_lockless(), osc_lock_upcall(), osc_lock_upcall_agl(), osc_lock_wake_waiters(), ostid_build_res_name(), osc_thread_info::oti_policy, osc_thread_info::oti_resname, PTLRPCD_SET, and RETURN.
static int osc_lock_enqueue_wait (const struct lu_env * env, struct osc_object * obj, struct osc_lock * oscl) [static]
Definition at line 853 of file osc_lock.c.
References cl_sync_io_end(), cl_sync_io_init(), cl_sync_io_wait(), cl_lock_descr::cld_end, cl_lock_descr::cld_mode, cl_lock_descr::cld_start, cl_lock::cll_descr, CLM_GROUP, cl_lock_slice::cls_lock, ENTRY, list_add_tail(), list_for_each_entry, osc_lock::ols_cl, osc_lock::ols_lock, osc_lock::ols_nextlock_oscobj, osc_lock::ols_owner, osc_lock::ols_wait_entry, osc_lock::ols_waiting_list, osc_object::oo_ol_list, osc_object::oo_ol_spin, osc_env_info(), osc_lock_compatible(), osc_lock_is_lockless(), osc_thread_info::oti_anchor, and RETURN.
Referenced by osc_lock_enqueue().
static void osc_lock_fini (const struct lu_env * env, struct cl_lock_slice * slice) [static]
Definition at line 141 of file osc_lock.c.
References cl2osc_lock(), LASSERT, LINVRNT, OBD_SLAB_FREE_PTR, osc_lock::ols_dlmlock, osc_lock_invariant(), and osc_lock_kmem.
static int osc_lock_flush (struct osc_object * obj, pgoff_t start, pgoff_t end, enum cl_lock_mode mode, int discard) [static]
Definition at line 393 of file osc_lock.c.
References CDEBUG, cl_env_nested_get(), cl_env_nested_put(), CLM_WRITE, D_CACHE, ENTRY, osc_cache_writeback_range(), osc_lock_discard_pages(), and RETURN.
Referenced by osc_dlm_blocking_ast0(), and osc_lock_lockless_cancel().
static void osc_lock_granted (const struct lu_env * env, struct osc_lock * oscl, struct lustre_handle * lockh, bool lvb_update) [static]
Definition at line 243 of file osc_lock.c.
References cl2osc(), cl_index(), cl_lock_descr::cld_end, cl_lock_descr::cld_gid, cl_lock_descr::cld_mode, cl_lock_descr::cld_obj, cl_lock_descr::cld_start, cl_lock::cll_descr, cl_lock_slice::cls_lock, cl_lock_slice::cls_obj, ldlm_enqueue_info::ei_mode, ldlm_extent::end, ldlm_extent::gid, ldlm_policy_data::l_extent, ldlm_lock::l_granted_mode, ldlm_lock::l_policy_data, ldlm_lock::l_reference, ldlm_lock::l_req_mode, LASSERT, LDLM_FL_LVB_READY, ldlm_handle2lock_long(), ldlm_lock_addref(), LINVRNT, lock_res_and_lock(), lu_ref_add(), lustre_handle_copy(), osc_lock::ols_cl, osc_lock::ols_dlmlock, osc_lock::ols_einfo, osc_lock::ols_flags, osc_lock::ols_glimpse, OLS_GRANTED, osc_lock::ols_handle, osc_lock::ols_has_ref, osc_lock::ols_hold, osc_lock::ols_state, osc_ldlm2cl_lock(), osc_lock_invariant(), osc_lock_lvb_update(), ldlm_extent::start, and unlock_res_and_lock().
Referenced by osc_lock_upcall().
int osc_lock_init (const struct lu_env * env, struct cl_object * obj, struct cl_lock * lock, const struct cl_io * io)
Definition at line 1162 of file osc_lock.c.
References CEF_AGL, CEF_DISCARD_DATA, CEF_MUST, CEF_NEVER, cl_io::ci_type, CIT_WRITE, cl2osc(), cl_io_is_mkwrite(), cl_lock_slice_add(), cl_lock_descr::cld_enq_flags, cl_lock::cll_descr, INIT_LIST_HEAD, LDLM_DEBUG_NOLOCK, LDLM_FL_BLOCK_GRANTED, LDLM_FL_BLOCK_NOWAIT, LDLM_FL_DENY_ON_CONTENTION, LDLM_FL_HAS_INTENT, LPX64, OBD_SLAB_ALLOC_PTR_GFP, osc_lock::ols_agl, osc_lock::ols_cl, osc_lock::ols_einfo, osc_lock::ols_flags, osc_lock::ols_glimpse, osc_lock::ols_lock, osc_lock::ols_locklessable, OLS_NEW, osc_lock::ols_nextlock_oscobj, osc_lock::ols_state, osc_lock::ols_wait_entry, osc_lock::ols_waiting_list, osc_enq2ldlm_flags(), osc_lock_build_einfo(), osc_lock_kmem, osc_lock_set_writer(), and osc_lock_to_lockless().
static int osc_lock_invariant (struct osc_lock * ols) [static]
Invariant that has to be true all of the time.
Definition at line 88 of file osc_lock.c.
References lustre_handle::cookie, ergo, portals_handle::h_cookie, ldlm_lock::l_granted_mode, ldlm_lock::l_handle, ldlm_lock::l_req_mode, ldlm_is_destroyed, lustre_handle_is_used(), OLS_CANCELLED, osc_lock::ols_dlmlock, OLS_GRANTED, osc_lock::ols_handle, osc_lock::ols_hold, osc_lock::ols_locklessable, osc_lock::ols_state, osc_handle_ptr(), and osc_lock_is_lockless().
Referenced by osc_lock_cancel(), osc_lock_fini(), and osc_lock_granted().
int osc_lock_is_lockless (const struct osc_lock * olck)
Definition at line 65 of file osc_lock.c.
References cl_lock_slice::cls_ops, osc_lock::ols_cl, and osc_lock_lockless_ops.
Referenced by osc_lock_enqueue(), osc_lock_enqueue_wait(), osc_lock_invariant(), and osc_lock_to_lockless().
static void osc_lock_lockless_cancel (const struct lu_env * env, const struct cl_lock_slice * slice) [static]
Definition at line 1103 of file osc_lock.c.
References CERROR, cl2osc(), cl2osc_lock(), cl_lock_descr::cld_end, cl_lock_descr::cld_mode, cl_lock_descr::cld_start, cl_lock::cll_descr, cl_lock_slice::cls_lock, cl_lock_slice::cls_obj, LASSERT, osc_lock::ols_dlmlock, osc_lock_flush(), and osc_lock_wake_waiters().
static void osc_lock_lvb_update (const struct lu_env * env, struct osc_object * osc, struct ldlm_lock * dlmlock, struct ost_lvb * lvb) [static]
Updates object attributes from a lock value block (lvb) received together with the DLM lock reply from the server.
Copy of osc_update_enqueue() logic.
This can be optimized to not update attributes when lock is a result of a local match.
Called under lock and resource spin-locks.
Definition at line 191 of file osc_lock.c.
References __u64, CAT_ATIME, CAT_BLOCKS, CAT_CTIME, cl_attr::cat_kms, CAT_KMS, CAT_MTIME, CAT_SIZE, check_res_locked(), cl_lvb2attr(), cl_object_attr_lock(), cl_object_attr_unlock(), cl_object_attr_update(), ldlm_extent::end, ENTRY, EXIT, ldlm_policy_data::l_extent, ldlm_lock::l_lvb_data, ldlm_lock::l_policy_data, ldlm_lock::l_resource, LASSERT, LDLM_DEBUG, ldlm_lock_allow_match_locked(), lov_oinfo::loi_kms, LPU64, ost_lvb::lvb_size, osc_object::oo_oinfo, osc2cl(), osc_env_info(), osc_thread_info::oti_attr, and size.
Referenced by osc_lock_granted(), osc_lock_upcall(), and osc_lock_upcall_agl().
static int osc_lock_print (const struct lu_env * env, void * cookie, lu_printer_t p, const struct cl_lock_slice * slice) [static]
Definition at line 1084 of file osc_lock.c.
References cl2osc_lock(), lustre_handle::cookie, LPX64, osc_lock::ols_dlmlock, osc_lock::ols_flags, osc_lock::ols_handle, osc_lock::ols_lvb, osc_lock::ols_owner, osc_lock::ols_state, and osc_lvb_print().
static void osc_lock_set_writer (const struct lu_env * env, const struct cl_io * io, struct cl_object * obj, struct osc_lock * oscl) [static]
Definition at line 1128 of file osc_lock.c.
References cl_io::ci_fault, cl_io::ci_obj, cl_io::ci_rw, cl_io::ci_type, CIT_WRITE, cl_index(), cl_io_is_append(), cl_io_is_mkwrite(), cl_object_same(), CL_PAGE_EOF, cl_lock_descr::cld_end, cl_lock_descr::cld_mode, cl_lock_descr::cld_start, cl_lock::cll_descr, CLM_WRITE, cl_lock_slice::cls_lock, cl_io_rw_common::crw_count, cl_io_rw_common::crw_pos, LASSERT, likely, osc_io::oi_write_osclock, osc_lock::ols_cl, osc_env_io(), and cl_io::u.
Referenced by osc_lock_init().
static void osc_lock_to_lockless (const struct lu_env * env, struct osc_lock * ols, int force) [static]
Determine if the lock should be converted into a lockless lock.
Steps to check:
if the lock has an explicite requirment for a non-lockless lock;
if the io lock request type ci_lockreq;
send the enqueue rpc to ost to make the further decision;
special treat to truncate lockless lock
Additional policy can be implemented here, e.g., never do lockless-io for large extents.
Definition at line 768 of file osc_lock.c.
References cl_io::ci_lockreq, cl_io::ci_type, CILR_MANDATORY, CILR_MAYBE, CILR_NEVER, cl_io_slice::cis_io, CIT_SETATTR, cl2osc(), cl_io_is_trunc(), class_exp2cliimp(), cl_lock_slice::cls_obj, cl_lock_slice::cls_ops, cl_object::co_lu, ergo, obd_import::imp_connect_data, LASSERT, lu_object::lo_dev, lu2osc_dev(), OBD_CONNECT_SRVLOCK, OBD_CONNECT_TRUNCLOCK, obd_connect_data::ocd_connect_flags, osc_device::od_lockless_truncate, osc_io::oi_cl, osc_lock::ols_cl, osc_lock::ols_glimpse, osc_lock::ols_locklessable, OLS_NEW, osc_lock::ols_state, OLS_UPCALL_RECEIVED, osc_env_io(), osc_export(), osc_lock_is_lockless(), osc_lock_lockless_ops, and osc_object_is_contended().
Referenced by osc_lock_init(), and osc_lock_upcall().
static int osc_lock_upcall (void * cookie, struct lustre_handle * lockh, int errcode) [static]
Lock upcall function that is executed either when a reply to ENQUEUE rpc is received from a server, or after osc_enqueue_base() matched a local DLM lock.
Definition at line 302 of file osc_lock.c.
References CERROR, cl2osc(), cl_env_nested_get(), cl_env_nested_put(), cl_sync_io_note(), cl_lock_slice::cls_obj, cl_lock_slice::cls_ops, ELDLM_OK, ENTRY, LASSERT, LBUG, ldlm_error2errno(), LDLM_FL_LVB_READY, OLS_CANCELLED, osc_lock::ols_cl, OLS_ENQUEUED, osc_lock::ols_flags, osc_lock::ols_glimpse, OLS_GRANTED, osc_lock::ols_locklessable, osc_lock::ols_lvb, osc_lock::ols_owner, osc_lock::ols_state, OLS_UPCALL_RECEIVED, osc_lock_granted(), osc_lock_lvb_update(), osc_lock_ops, osc_lock_to_lockless(), osc_object_set_contended(), and RETURN.
Referenced by osc_lock_enqueue().
static int osc_lock_upcall_agl (void * cookie, struct lustre_handle * lockh, int errcode) [static]
Definition at line 357 of file osc_lock.c.
References cl_env_nested_get(), cl_env_nested_put(), cl_object_put(), ELDLM_LOCK_MATCHED, ELDLM_OK, ENTRY, GOTO, ldlm_lock::l_granted_mode, ldlm_lock::l_req_mode, LASSERT, ldlm_error2errno(), ldlm_handle2lock(), LDLM_LOCK_PUT, lock_res_and_lock(), osc2cl(), osc_lock_lvb_update(), RETURN, and unlock_res_and_lock().
Referenced by osc_lock_enqueue().
static void osc_lock_wake_waiters (const struct lu_env * env, struct osc_object * osc, struct osc_lock * oscl) [static]
Definition at line 832 of file osc_lock.c.
References cl_sync_io_note(), list_del_init(), list_empty(), list_entry, list_head::next, osc_lock::ols_lock, osc_lock::ols_nextlock_oscobj, osc_lock::ols_owner, osc_lock::ols_wait_entry, osc_lock::ols_waiting_list, and osc_object::oo_ol_spin.
Referenced by osc_lock_cancel(), osc_lock_enqueue(), and osc_lock_lockless_cancel().
static unsigned long osc_lock_weight (const struct lu_env * env, struct osc_object * oscobj, struct ldlm_extent * extent) [static]
Definition at line 658 of file osc_lock.c.
References cl_io::ci_ignore_layout, cl_io::ci_obj, CIT_MISC, cl_index(), cl_io_fini(), cl_io_init(), cl_object_top(), CLP_GANG_ABORT, CLP_GANG_OKAY, CLP_GANG_RESCHED, ldlm_extent::end, ENTRY, osc_object::oo_cl, osc_env_info(), osc_page_gang_lookup(), osc_thread_info::oti_io, RETURN, ldlm_extent::start, and weigh_cb().
Referenced by osc_ldlm_weigh_ast().
void osc_lru_add_batch (struct client_obd * cli, struct list_head * list)
Definition at line 542 of file osc_page.c.
References cfs_time_current_sec(), client_obd::cl_lru_busy, client_obd::cl_lru_in_list, client_obd::cl_lru_last_used, client_obd::cl_lru_list, client_obd::cl_lru_list_lock, client_obd::cl_lru_work, LASSERT, list_add(), list_empty(), list_for_each_entry, LIST_HEAD_INIT, list_splice_tail(), oap2osc_page(), osc_async_page::oap_pending_item, osc_page::ops_in_lru, osc_page::ops_lru, and ptlrpcd_queue_work().
static int osc_lru_alloc (const struct lu_env * env, struct client_obd * cli, struct osc_page * opg) [static]
osc_lru_alloc() is called to allocate an LRU slot for a cl_page.
Usually the LRU slots are reserved in osc_io_iter_rw_init(). Only in the case that the LRU slots are in extreme shortage, it should have reserved enough slots for an IO.
Definition at line 887 of file osc_page.c.
References client_obd::cl_cache, client_obd::cl_lru_busy, client_obd::cl_lru_left, ENTRY, l_wait_event, LASSERT, LWI_INTR, LWI_ON_SIGNAL_NOOP, osc_io::oi_lru_reserved, osc_page::ops_in_lru, osc_env_io(), osc_lru_reclaim(), and RETURN.
Referenced by osc_page_init().
static void osc_lru_del (struct client_obd * cli, struct osc_page * opg) [static]
Page is being destroyed.
The page may be not in LRU list, if the transfer has never finished(error occurred).
Definition at line 583 of file osc_page.c.
References __osc_lru_del(), CDEBUG, client_obd::cl_lru_busy, client_obd::cl_lru_left, client_obd::cl_lru_list_lock, client_obd::cl_lru_work, cli_name(), D_CACHE, LASSERT, list_empty(), osc_page::ops_in_lru, osc_page::ops_lru, osc_cache_too_much(), and ptlrpcd_queue_work().
Referenced by osc_page_delete().
static long osc_lru_reclaim (struct client_obd * cli, unsigned long npages) [static]
Reclaim LRU pages by an IO thread.
The caller wants to reclaim at least @npages of LRU slots. For performance consideration, it's better to drop LRU pages in batch. Therefore, the actual number is adjusted at least max_pages_per_rpc.
Definition at line 808 of file osc_page.c.
References cl_client_cache::ccc_lru, cl_client_cache::ccc_lru_lock, cl_client_cache::ccc_lru_shrinkers, cl_client_cache::ccc_users, CDEBUG, client_obd::cl_cache, cl_env_nested_get(), cl_env_nested_put(), client_obd::cl_lru_busy, client_obd::cl_lru_in_list, client_obd::cl_lru_osc, client_obd::cl_lru_work, client_obd::cl_max_pages_per_rpc, cli_name(), D_CACHE, ENTRY, GOTO, LASSERT, list_empty(), list_entry, list_move_tail(), list_head::next, osc_cache_too_much(), osc_lru_shrink(), ptlrpcd_queue_work(), and RETURN.
Referenced by osc_lru_alloc(), and osc_lru_reserve().
unsigned long osc_lru_reserve (struct client_obd * cli, unsigned long npages)
osc_lru_reserve() is called to reserve enough LRU slots for I/O.
The benefit of doing this is to reduce contention against atomic counter cl_lru_left by changing it from per-page access to per-IO access.
Definition at line 936 of file osc_page.c.
References CDEBUG, client_obd::cl_lru_left, client_obd::cl_lru_work, client_obd::cl_max_pages_per_rpc, client_obd::cl_max_rpcs_in_flight, cli_name(), D_CACHE, osc_lru_reclaim(), and ptlrpcd_queue_work().
Referenced by osc_io_write_iter_init().
long osc_lru_shrink (const struct lu_env * env, struct client_obd * cli, long target, bool force)
Drop of pages from LRU at most.
Definition at line 667 of file osc_page.c.
References __osc_lru_del(), CDEBUG, cl_io::ci_ignore_layout, cl_io::ci_obj, CIT_MISC, cl_io_fini(), cl_io_init(), client_obd::cl_lru_in_list, client_obd::cl_lru_left, client_obd::cl_lru_list, client_obd::cl_lru_list_lock, client_obd::cl_lru_reclaim, client_obd::cl_lru_shrinkers, cl_object_get(), cl_object_put(), cl_page_disown(), cl_page_get(), cl_page_own_try(), cli_name(), cl_page::cp_obj, cl_page_slice::cpl_page, D_CACHE, discard_pagevec(), ENTRY, LASSERT, list_empty(), list_entry, list_move_tail(), lru_page_busy(), list_head::next, osc_page::ops_cl, osc_page::ops_in_lru, osc_page::ops_lru, osc_env_info(), osc_thread_info::oti_io, osc_thread_info::oti_pvec, OTI_PVEC_SIZE, RETURN, and unlikely.
Referenced by lru_queue_work(), osc_cache_shrink_scan(), osc_lru_reclaim(), and osc_set_info_async().
void osc_lru_unreserve (struct client_obd * cli, unsigned long npages)
osc_lru_unreserve() is called to unreserve LRU slots.
LRU slots reserved by osc_lru_reserve() may have entries left due to several reasons such as page already existing or I/O error. Those reserved slots should be freed by calling this function.
Definition at line 978 of file osc_page.c.
References client_obd::cl_lru_left.
Referenced by osc_io_write_iter_fini().
static void osc_lru_use (struct client_obd * cli, struct osc_page * opg) [static]
Delete page from LRUlist for redirty.
Definition at line 612 of file osc_page.c.
References __osc_lru_del(), client_obd::cl_lru_busy, client_obd::cl_lru_list_lock, list_empty(), osc_page::ops_in_lru, and osc_page::ops_lru.
Referenced by osc_page_transfer_add().
int osc_lvb_print (const struct lu_env * env, void * cookie, lu_printer_t p, const struct ost_lvb * lvb)
Definition at line 131 of file osc_object.c.
References LPU64, ost_lvb::lvb_atime, ost_lvb::lvb_blocks, ost_lvb::lvb_ctime, ost_lvb::lvb_mtime, and ost_lvb::lvb_size.
Referenced by osc_lock_print(), and osc_object_print().
static int osc_make_ready (const struct lu_env * env, struct osc_async_page * oap, int cmd) [static]
Definition at line 1261 of file osc_cache.c.
References cfs_time_current(), cl_page_make_ready(), CRT_WRITE, ENTRY, LASSERT, oap2cl_page(), oap2osc_page(), OBD_BRW_WRITE, osc_page::ops_submit_time, and RETURN.
Referenced by osc_extent_make_ready().
static int osc_makes_hprpc (struct osc_object * obj) [static]
Definition at line 1772 of file osc_cache.c.
References list_empty(), and osc_object::oo_hp_exts.
Referenced by __osc_list_maint().
static int osc_makes_rpc (struct client_obd * cli, struct osc_object * osc, int cmd) [static]
Definition at line 1704 of file osc_cache.c.
References CDEBUG, client_obd::cl_cache_waiters, client_obd::cl_import, client_obd::cl_max_pages_per_rpc, D_CACHE, ENTRY, obd_import::imp_invalid, list_empty(), OBD_BRW_WRITE, osc_object::oo_hp_exts, osc_object::oo_nr_reads, osc_object::oo_nr_writes, osc_object::oo_reading_exts, osc_object::oo_urgent_exts, and RETURN.
Referenced by __osc_list_maint(), and osc_check_rpcs().
static int osc_max_rpc_in_flight (struct client_obd * cli, struct osc_object * osc) [static]
Definition at line 1695 of file osc_cache.c.
References client_obd::cl_max_rpcs_in_flight, list_empty(), osc_object::oo_hp_exts, and rpcs_in_flight().
Referenced by osc_check_rpcs().
static struct osc_object* osc_next_obj (struct client_obd * cli) [static, read]
Definition at line 2132 of file osc_cache.c.
References client_obd::cl_cache_waiters, client_obd::cl_import, client_obd::cl_loi_hp_ready_list, client_obd::cl_loi_read_list, client_obd::cl_loi_ready_list, client_obd::cl_loi_write_list, ENTRY, obd_import::imp_invalid, list_empty(), list_to_obj, and RETURN.
Referenced by osc_check_rpcs().
struct lu_object * osc_object_alloc (const struct lu_env * env, const struct lu_object_header * hdr, struct lu_device * dev) [read]
Definition at line 439 of file osc_object.c.
References cl_object::co_ops, lu_object::lo_ops, lu_object_init(), OBD_SLAB_ALLOC_PTR_GFP, osc_object::oo_cl, osc2lu(), and osc_object_kmem.
static int osc_object_ast_clear (struct ldlm_lock * lock, void * data) [static]
Definition at line 203 of file osc_object.c.
References ENTRY, ldlm_lock::l_ast_data, LDLM_ITER_CONTINUE, and RETURN.
Referenced by osc_object_prune().
void osc_object_clear_contended (struct osc_object * obj)
Definition at line 317 of file osc_object.c.
References osc_object::oo_contended.
Referenced by osc_object_is_contended().
static int osc_object_fiemap (const struct lu_env * env, struct cl_object * obj, struct ll_fiemap_info_key * fmkey, struct fiemap * fiemap, size_t * buflen) [static]
Definition at line 225 of file osc_object.c.
References cl2osc(), class_exp2cliimp(), ldlm_extent::end, ENTRY, obd_export::exp_obd, GOTO, ldlm_policy_data::l_extent, LCK_MINMODE, LCK_PR, LCK_PW, LDLM_EXTENT, LDLM_FL_BLOCK_GRANTED, LDLM_FL_LVB_READY, ldlm_lock_addref(), ldlm_lock_decref(), ldlm_lock_match(), ll_fiemap_info_key::lfik_fiemap, ll_fiemap_info_key::lfik_oa, lov_oinfo::loi_oi, LUSTRE_OST_VERSION, mode, obdo::o_flags, obdo::o_oi, obdo::o_valid, OBD_FL_SRVLOCK, OBD_MD_FLFLAGS, obd_device::obd_namespace, OBD_OBJECT_EOF, osc_object::oo_oinfo, osc_export(), OST_GET_INFO, ostid_build_res_name(), ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), RCL_CLIENT, RCL_SERVER, req_capsule_client_get(), req_capsule_server_get(), req_capsule_set_size(), RETURN, RMF_FIEMAP_KEY, RMF_FIEMAP_VAL, ptlrpc_request::rq_pill, RQF_OST_GET_INFO_FIEMAP, and ldlm_extent::start.
static void osc_object_free (const struct lu_env * env, struct lu_object * obj) [static]
Definition at line 108 of file osc_object.c.
References LASSERT, list_empty(), lu2osc(), lu_object_fini(), OBD_SLAB_FREE_PTR, osc_object::oo_hp_exts, osc_object::oo_hp_ready_item, osc_object::oo_nr_ios, osc_object::oo_nr_reads, osc_object::oo_nr_writes, osc_object::oo_ol_list, osc_object::oo_read_item, osc_object::oo_reading_exts, osc_object::oo_ready_item, osc_object::oo_root, osc_object::oo_rpc_exts, osc_object::oo_urgent_exts, osc_object::oo_write_item, and osc_object_kmem.
static int osc_object_glimpse (const struct lu_env * env, const struct cl_object * obj, struct ost_lvb * lvb) [static]
Definition at line 192 of file osc_object.c.
References cl2osc(), ENTRY, lov_oinfo::loi_kms, lov_oinfo::loi_lvb, ost_lvb::lvb_blocks, ost_lvb::lvb_size, osc_object::oo_oinfo, and RETURN.
static int osc_object_init (const struct lu_env * env, struct lu_object * obj, const struct lu_object_conf * conf) [static]
Definition at line 73 of file osc_object.c.
References cl_object_page_init(), cl_object_conf::coc_oinfo, INIT_LIST_HEAD, lu2cl(), lu2cl_conf(), lu2osc(), osc_object::oo_hp_exts, osc_object::oo_hp_ready_item, osc_object::oo_io_waitq, osc_object::oo_lock, osc_object::oo_nr_ios, osc_object::oo_nr_reads, osc_object::oo_nr_writes, osc_object::oo_oinfo, osc_object::oo_ol_list, osc_object::oo_ol_spin, osc_object::oo_read_item, osc_object::oo_reading_exts, osc_object::oo_ready_item, osc_object::oo_root, osc_object::oo_rpc_exts, osc_object::oo_tree_lock, osc_object::oo_urgent_exts, osc_object::oo_write_item, and cl_object_conf::u.
int osc_object_invalidate (const struct lu_env * env, struct osc_object * osc)
Definition at line 457 of file osc_object.c.
References CDEBUG, CL_PAGE_EOF, CLM_WRITE, D_INODE, ENTRY, l_wait_event, osc_object::oo_io_waitq, osc_object::oo_nr_ios, osc2cl(), osc_cache_truncate_start(), osc_lock_discard_pages(), osc_object_prune(), and RETURN.
Referenced by osc_ldlm_resource_invalidate().
int osc_object_is_contended (struct osc_object * obj)
Definition at line 322 of file osc_object.c.
References cfs_time_add(), cfs_time_after(), cfs_time_current(), cfs_time_seconds(), cl_object::co_lu, lu_object::lo_dev, lu2osc_dev(), OBD_FAIL_CHECK, OBD_FAIL_OSC_OBJECT_CONTENTION, osc_device::od_contention_time, osc_object::oo_cl, osc_object::oo_contended, osc_object::oo_contention_time, and osc_object_clear_contended().
Referenced by osc_lock_to_lockless().
static int osc_object_is_locked (struct osc_object * obj) [inline, static]
Definition at line 193 of file osc_cl_internal.h.
References osc_object::oo_lock.
Referenced by __osc_extent_remove(), get_write_extents(), osc_extent_erase(), osc_extent_hold(), osc_extent_insert(), osc_extent_is_overlapped(), osc_extent_merge(), osc_extent_put_trust(), osc_extent_sanity_check0(), osc_extent_search(), osc_extent_state_set(), osc_send_read_rpc(), and osc_send_write_rpc().
static void osc_object_lock (struct osc_object * obj) [inline, static]
Definition at line 178 of file osc_cl_internal.h.
References osc_object::oo_lock.
Referenced by extent_wait_cb(), osc_check_rpcs(), osc_extent_expand(), osc_extent_find(), osc_extent_make_ready(), osc_extent_remove(), osc_extent_truncate(), osc_extent_wait(), osc_send_read_rpc(), and osc_send_write_rpc().
static int osc_object_print (const struct lu_env * env, void * cookie, lu_printer_t p, const struct lu_object * obj) [static]
Definition at line 140 of file osc_object.c.
References osc_async_rc::ar_force_sync, osc_async_rc::ar_min_xid, osc_async_rc::ar_rc, DOSTID, lov_oinfo::loi_ar, lov_oinfo::loi_kms, lov_oinfo::loi_kms_valid, lov_oinfo::loi_lvb, lov_oinfo::loi_oi, lov_oinfo::loi_ost_gen, lov_oinfo::loi_ost_idx, LPU64, lu2osc(), osc_object::oo_oinfo, osc_lvb_print(), and POSTID.
static int osc_object_prune (const struct lu_env * env, struct cl_object * obj) [static]
Definition at line 212 of file osc_object.c.
References cl2osc(), ldlm_resource_iterate(), lov_oinfo::loi_oi, osc_object::oo_oinfo, osc_env_info(), osc_export(), osc_object_ast_clear(), ostid_build_res_name(), and osc_thread_info::oti_resname.
Referenced by osc_object_invalidate().
void osc_object_set_contended (struct osc_object * obj)
Definition at line 310 of file osc_object.c.
References cfs_time_current(), osc_object::oo_contended, and osc_object::oo_contention_time.
Referenced by osc_lock_upcall().
static int osc_object_trylock (struct osc_object * obj) [inline, static]
Definition at line 183 of file osc_cl_internal.h.
References osc_object::oo_lock.
static void osc_object_unlock (struct osc_object * obj) [inline, static]
Definition at line 188 of file osc_cl_internal.h.
References osc_object::oo_lock.
Referenced by extent_wait_cb(), osc_check_rpcs(), osc_extent_expand(), osc_extent_find(), osc_extent_make_ready(), osc_extent_remove(), osc_extent_truncate(), osc_extent_wait(), osc_send_read_rpc(), and osc_send_write_rpc().
bool osc_over_unstable_soft_limit (struct client_obd * cli)
Check if it piggybacks SOFT_SYNC flag to OST from this OSC.
This function will be called by every BRW RPC so it's critical to make this function fast.
Definition at line 1102 of file osc_page.c.
References cl_client_cache::ccc_lru_max, cl_client_cache::ccc_unstable_check, cl_client_cache::ccc_unstable_nr, CDEBUG, client_obd::cl_cache, client_obd::cl_max_pages_per_rpc, client_obd::cl_max_rpcs_in_flight, client_obd::cl_unstable_count, cli_name(), and D_CACHE.
Referenced by osc_build_rpc().
int osc_page_cache_add (const struct lu_env * env, const struct cl_page_slice * slice, struct cl_io * io)
Definition at line 203 of file osc_page.c.
References cl2osc_page(), CLM_WRITE, CRT_WRITE, ENTRY, LINVRNT, osc_page_protected(), osc_page_transfer_add(), osc_page_transfer_get(), osc_page_transfer_put(), osc_queue_async_io(), and RETURN.
Referenced by osc_io_commit_async().
static int osc_page_cancel (const struct lu_env * env, const struct cl_page_slice * slice) [static]
Definition at line 344 of file osc_page.c.
References cl2osc_page(), CLM_READ, ergo, LASSERT, LINVRNT, osc_page::ops_transfer_pinned, osc_cancel_async_page(), and osc_page_protected().
static void osc_page_clip (const struct lu_env * env, const struct cl_page_slice * slice, int from, int to) [static]
Definition at line 328 of file osc_page.c.
References ASYNC_COUNT_STABLE, cl2osc_page(), CLM_READ, LINVRNT, osc_async_page::oap_async_flags, osc_async_page::oap_lock, osc_page::ops_from, osc_page::ops_oap, osc_page::ops_to, and osc_page_protected().
static void osc_page_delete (const struct lu_env * env, const struct cl_page_slice * slice) [static]
Definition at line 292 of file osc_page.c.
References CDEBUG, cl2osc(), cl2osc_page(), CL_PAGE_DEBUG, CLM_READ, cl_page::cp_type, cl_page_slice::cpl_obj, cl_page_slice::cpl_page, CPT_CACHEABLE, D_ERROR, D_TRACE, ENTRY, ergo, EXIT, LASSERT, LINVRNT, osc_object::oo_npages, osc_object::oo_tree, osc_object::oo_tree_lock, osc_page::ops_cl, osc_page::ops_temp, osc_cli(), osc_index(), osc_lru_del(), osc_page_protected(), osc_page_transfer_put(), and osc_teardown_async_page().
static int osc_page_flush (const struct lu_env * env, const struct cl_page_slice * slice, struct cl_io * io) [static]
Definition at line 361 of file osc_page.c.
References cl2osc_page(), ENTRY, osc_flush_async_page(), and RETURN.
int osc_page_gang_lookup (const struct lu_env * env, struct cl_io * io, struct osc_object * osc, pgoff_t start, pgoff_t end, osc_page_gang_cbt cb, void * cbdata)
Returns a list of pages by a given [start, end] of obj.
Parameters:
resched If not NULL, then we give up before hogging CPU for too long and set *resched = 1, in that case caller should implement a retry logic.
Gang tree lookup (radix_tree_gang_lookup()) optimization is absolutely crucial in the face of [offset, EOF] locks.
Return at least one page in unless there is no covered page.
Referenced by osc_lock_weight(), and osc_trunc_check().
int osc_page_init (const struct lu_env * env, struct cl_object * obj, struct cl_page * page, pgoff_t ind)
Definition at line 380 of file osc_page.c.
References cl2osc(), cl_object_page_slice(), cl_offset(), cl_page_slice_add(), CLM_READ, cl_page::cp_type, cl_page::cp_vmpage, CPT_CACHEABLE, INIT_LIST_HEAD, LASSERT, osc_object::oo_npages, osc_object::oo_tree, osc_object::oo_tree_lock, osc_page::ops_cl, osc_page::ops_from, osc_page::ops_lru, osc_page::ops_srvlock, osc_page::ops_temp, osc_page::ops_to, osc_cli(), osc_env_io(), osc_io_srvlock(), osc_lru_alloc(), osc_page_protected(), and osc_prep_async_page().
static int osc_page_print (const struct lu_env * env, const struct cl_page_slice * slice, void * cookie, lu_printer_t printer) [static]
Definition at line 243 of file osc_page.c.
References cl2osc(), cl2osc_page(), client_obd::cl_avail_grant, client_obd::cl_cache_waiters, client_obd::cl_loi_hp_ready_list, client_obd::cl_loi_read_list, client_obd::cl_loi_ready_list, client_obd::cl_loi_write_list, client_obd::cl_max_rpcs_in_flight, client_obd::cl_r_in_flight, client_obd::cl_w_in_flight, obd_device::cli, cl_page_slice::cpl_obj, obd_export::exp_obd, LPD64, LUSTRE_OSC_NAME, osc_async_page::oap_async_flags, osc_async_page::oap_cli, osc_async_page::oap_cmd, osc_async_page::oap_interrupted, osc_async_page::oap_magic, osc_async_page::oap_obj_off, osc_async_page::oap_page_off, osc_async_page::oap_pending_item, osc_async_page::oap_request, osc_async_page::oap_rpc_item, osc_object::oo_hp_exts, osc_object::oo_hp_ready_item, osc_object::oo_nr_reads, osc_object::oo_nr_writes, osc_object::oo_read_item, osc_object::oo_reading_exts, osc_object::oo_ready_item, osc_object::oo_urgent_exts, osc_object::oo_write_item, osc_page::ops_oap, osc_export(), osc_index(), osc_list(), osc_submit_duration(), and obd_device::u.
static int osc_page_protected (const struct lu_env * env, const struct osc_page * opg, enum cl_lock_mode mode, int unref) [static]
Definition at line 153 of file osc_page.c.
Referenced by osc_page_cache_add(), osc_page_cancel(), osc_page_clip(), osc_page_delete(), osc_page_init(), and osc_page_submit().
void osc_page_submit (const struct lu_env * env, struct osc_page * opg, enum cl_req_type crt, int brw_flags)
Helper function called by osc_io_submit() for every page in an immediate transfer (i.e., transferred synchronously).
Definition at line 427 of file osc_page.c.
References ASYNC_COUNT_STABLE, ASYNC_READY, CFS_CAP_SYS_RESOURCE, cfs_capable(), cfs_time_current(), client_is_remote(), CLM_READ, CLM_WRITE, CRT_WRITE, LASSERT, LASSERTF, LINVRNT, osc_async_page::oap_async_flags, osc_async_page::oap_cmd, OAP_MAGIC, osc_async_page::oap_magic, osc_async_page::oap_obj, osc_async_page::oap_page_off, OBD_BRW_NOQUOTA, OBD_BRW_READ, OBD_BRW_SYNC, OBD_BRW_WRITE, osc_page::ops_from, osc_page::ops_oap, osc_page::ops_submit_time, osc_page::ops_to, osc_export(), osc_page_protected(), osc_page_transfer_add(), and osc_page_transfer_get().
Referenced by osc_io_submit().
static void osc_page_touch_at (const struct lu_env * env, struct cl_object * obj, pgoff_t idx, size_t to) [static]
This is called when a page is accessed within file in a way that creates new page, if one were missing (i.e., if there were a hole at that place in the file, or accessed page is beyond the current file size).
Expand stripe KMS if necessary.
Definition at line 228 of file osc_io.c.
References __u64, CAT_CTIME, cl_attr::cat_ctime, CAT_KMS, cl_attr::cat_kms, CAT_MTIME, cl_attr::cat_mtime, CAT_SIZE, cl_attr::cat_size, CDEBUG, cl2osc(), cl_object_attr_lock(), cl_object_attr_unlock(), cl_object_attr_update(), cl_offset(), D_INODE, lov_oinfo::loi_kms, lov_oinfo::loi_lvb, LPU64, LTIME_S, ost_lvb::lvb_size, osc_object::oo_oinfo, osc_env_info(), and osc_thread_info::oti_attr.
Referenced by osc_io_commit_async(), and osc_io_fault_start().
static void osc_page_transfer_add (const struct lu_env * env, struct osc_page * opg, enum cl_req_type crt) [static]
This is called once for every page when it is submitted for a transfer either opportunistic (osc_page_cache_add()), or immediate (osc_page_submit()).
Definition at line 193 of file osc_page.c.
References cl2osc(), cl_page_slice::cpl_obj, osc_page::ops_cl, osc_cli(), and osc_lru_use().
Referenced by osc_page_cache_add(), and osc_page_submit().
static void osc_page_transfer_get (struct osc_page * opg, const char * label) [static]
Definition at line 166 of file osc_page.c.
References cl_page_get(), cl_page::cp_reference, cl_page_slice::cpl_page, LASSERT, lu_ref_add_atomic(), osc_page::ops_cl, and osc_page::ops_transfer_pinned.
Referenced by osc_page_cache_add(), and osc_page_submit().
static void osc_page_transfer_put (const struct lu_env * env, struct osc_page * opg) [static]
Definition at line 176 of file osc_page.c.
References cl_page_put(), cl_page::cp_reference, cl_page_slice::cpl_page, lu_ref_del(), osc_page::ops_cl, and osc_page::ops_transfer_pinned.
Referenced by osc_page_cache_add(), and osc_page_delete().
int osc_prep_async_page (struct osc_object * osc, struct osc_page * ops, struct page * page, loff_t offset)
Referenced by osc_page_init().
static void osc_process_ar (struct osc_async_rc * ar, __u64 xid, int rc) [static]
Definition at line 1826 of file osc_cache.c.
References osc_async_rc::ar_force_sync, osc_async_rc::ar_min_xid, osc_async_rc::ar_rc, and ptlrpc_sample_next_xid().
Referenced by osc_ap_completion().
int osc_queue_async_io (const struct lu_env * env, struct cl_io * io, struct osc_page * ops)
Referenced by osc_page_cache_add().
int osc_queue_sync_pages (const struct lu_env * env, struct osc_object * obj, struct list_head * list, int cmd, int brw_flags)
Referenced by osc_io_submit().
static void osc_read_ahead_release (const struct lu_env * env, void * cbdata) [static]
Definition at line 76 of file osc_io.c.
References LCK_PR, ldlm_lock2handle(), ldlm_lock_decref(), and LDLM_LOCK_PUT.
Referenced by osc_io_read_ahead().
static int osc_refresh_count (const struct lu_env * env, struct osc_async_page * oap, int cmd) [static]
Definition at line 1277 of file osc_cache.c.
References cl_attr::cat_kms, cl_object_attr_get(), cl_object_attr_lock(), cl_object_attr_unlock(), cl_offset(), cl_page_slice::cpl_obj, LASSERT, oap2osc(), oap2osc_page(), OBD_BRW_READ, osc_page::ops_cl, osc_env_info(), osc_index(), and osc_thread_info::oti_attr.
Referenced by osc_extent_make_ready().
static void osc_release_write_grant (struct client_obd * cli, struct brw_page * pga) [static]
Definition at line 1391 of file osc_cache.c.
References client_obd::cl_dirty_pages, client_obd::cl_dirty_transit, client_obd::cl_loi_list_lock, ENTRY, EXIT, brw_page::flag, OBD_BRW_FROM_GRANT, OBD_BRW_NOCACHE, obd_dirty_pages, and obd_dirty_transit_pages.
Referenced by osc_exit_cache().
static void osc_req_attr_set (const struct lu_env * env, struct cl_object * obj, struct cl_req_attr * attr) [static]
Implementation of struct cl_object_operations::coo_req_attr_set() for osc layer.
osc is responsible for struct obdo::o_id and struct obdo::o_seq fields.
Definition at line 353 of file osc_object.c.
References cl2osc(), CL_PAGE_DEBUG, cl_req_attr::cra_flags, cl_req_attr::cra_oa, cl_req_attr::cra_page, D_ERROR, ldlm_lock::l_remote_handle, LBUG, LDLM_EXTENT, LDLM_LOCK_PUT, ldlm_resource_dump(), ldlm_resource_get(), libcfs_debug_dumpstack, lov_oinfo::loi_lvb, lov_oinfo::loi_oi, ost_lvb::lvb_atime, ost_lvb::lvb_ctime, ost_lvb::lvb_mtime, obdo::o_atime, obdo::o_ctime, obdo::o_handle, obdo::o_mtime, obdo::o_oi, obdo::o_valid, OBD_MD_FLATIME, OBD_MD_FLCTIME, OBD_MD_FLGROUP, OBD_MD_FLHANDLE, OBD_MD_FLID, OBD_MD_FLMTIME, osc_object::oo_oinfo, osc_page::ops_srvlock, osc_cl_page_osc(), OSC_DAP_FL_CANCELING, OSC_DAP_FL_TEST_LOCK, osc_dlmlock_at_pgoff(), osc_env_info(), osc_export(), osc_index(), ostid_build_res_name(), ostid_id(), ostid_seq(), ostid_set_id(), ostid_set_seq(), and osc_thread_info::oti_resname.
static int osc_reserve_grant (struct client_obd * cli, unsigned int bytes) [static]
To avoid sleeping with object lock held, it's good for us allocate enough grants before entering into critical section.
client_obd_list_lock held by caller
Definition at line 1419 of file osc_cache.c.
References client_obd::cl_avail_grant, and client_obd::cl_reserved_grant.
Referenced by osc_enter_cache_try().
static int osc_send_read_rpc (const struct lu_env * env, struct client_obd * cli, struct osc_object * osc) [static]
prepare pages for ASYNC io and put pages in send queue.
Parameters:
cmd OBD_BRW_* macroses
lop pending pages
Returns:
zero if no page added to send queue.
1 if pages successfully added to send queue.
negative on errors.
Definition at line 2086 of file osc_cache.c.
References client_obd::cl_max_pages_per_rpc, EASSERT, ENTRY, LASSERT, list_empty(), list_for_each_entry_safe, LIST_HEAD_INIT, OBD_BRW_READ, osc_extent::oe_nr_pages, osc_extent::oe_state, OES_LOCK_DONE, OES_RPC, osc_build_rpc(), osc_extent_state_set(), osc_object_is_locked(), osc_object_lock(), osc_object_unlock(), osc_update_pending(), RETURN, and try_to_add_extent_for_io().
Referenced by osc_check_rpcs().
static int osc_send_write_rpc (const struct lu_env * env, struct client_obd * cli, struct osc_object * osc) [static]
Definition at line 2012 of file osc_cache.c.
References ENTRY, equi, get_write_extents(), LASSERT, list_del_init(), list_empty(), list_for_each_entry, list_for_each_entry_safe, LIST_HEAD_INIT, OBD_BRW_WRITE, osc_extent::oe_link, osc_extent::oe_srvlock, osc_extent::oe_state, OES_CACHE, OES_LOCK_DONE, OES_LOCKING, OES_RPC, osc_build_rpc(), osc_extent_finish(), osc_extent_make_ready(), osc_extent_state_set(), osc_object_is_locked(), osc_object_lock(), osc_object_unlock(), osc_update_pending(), RETURN, and unlikely.
Referenced by osc_check_rpcs().
static void osc_session_fini (const struct lu_context * ctx, struct lu_context_key * key, void * data) [static]
Definition at line 149 of file osc_dev.c.
References OBD_SLAB_FREE_PTR, and osc_session_kmem.
static void* osc_session_init (const struct lu_context * ctx, struct lu_context_key * key) [static]
Definition at line 138 of file osc_dev.c.
References OBD_SLAB_ALLOC_PTR_GFP, and osc_session_kmem.
int osc_set_async_flags (struct osc_object * obj, struct osc_page * opg, u32 async_flags)
static cfs_time_t osc_submit_duration (struct osc_page * opg) [inline, static]
Definition at line 235 of file osc_page.c.
References cfs_time_current(), and osc_page::ops_submit_time.
Referenced by osc_page_print().
int osc_teardown_async_page (const struct lu_env * env, struct osc_object * obj, struct osc_page * ops)
Referenced by osc_page_delete().
static void osc_trunc_check (const struct lu_env * env, struct cl_io * io, struct osc_io * oio, __u64 size) [static]
Definition at line 463 of file osc_io.c.
References cl_io_slice::cis_obj, cl2osc(), cl_index(), cl_offset(), CL_PAGE_EOF, osc_io::oi_cl, osc_page_gang_lookup(), start, and trunc_check_cb().
Referenced by osc_io_setattr_end().
static void osc_unreserve_grant (struct client_obd * cli, unsigned int reserved, unsigned int unused) [static]
Definition at line 1449 of file osc_cache.c.
References __osc_unreserve_grant(), client_obd::cl_loi_list_lock, and osc_wake_cache_waiters().
static void osc_update_pending (struct osc_object * obj, int cmd, int delta) [static]
Definition at line 1757 of file osc_cache.c.
References client_obd::cl_pending_r_pages, client_obd::cl_pending_w_pages, LASSERT, OBD_BRW_WRITE, osc_object::oo_nr_reads, osc_object::oo_nr_writes, osc_cli(), and OSC_IO_DEBUG.
Referenced by osc_extent_hold(), osc_send_read_rpc(), and osc_send_write_rpc().
void osc_wake_cache_waiters (struct client_obd * cli)
Definition at line 1661 of file osc_cache.c.
References CDEBUG, client_obd::cl_avail_grant, client_obd::cl_cache_waiters, client_obd::cl_dirty_max_pages, client_obd::cl_dirty_pages, D_CACHE, ENTRY, EXIT, list_del_init(), list_entry, list_for_each_safe, obd_dirty_pages, obd_max_dirty_pages, osc_cache_waiter::ocw_entry, osc_cache_waiter::ocw_grant, osc_cache_waiter::ocw_oap, osc_cache_waiter::ocw_rc, osc_cache_waiter::ocw_waitq, and osc_enter_cache_try().
Referenced by brw_interpret(), osc_free_grant(), and osc_unreserve_grant().
static int overlapped (struct osc_extent * ex1, struct osc_extent * ex2) [inline, static]
Definition at line 610 of file osc_cache.c.
References osc_extent::oe_end, and osc_extent::oe_start.
Referenced by osc_extent_find(), and try_to_add_extent_for_io().
static struct osc_extent* prev_extent (struct osc_extent * ext) [static, read]
Definition at line 167 of file osc_cache.c.
References LASSERT, osc_extent::oe_intree, osc_extent::oe_node, and rb_extent().
static struct osc_extent* rb_extent (struct rb_node * n) [static, read]
Definition at line 150 of file osc_cache.c.
References osc_extent::oe_node.
Referenced by first_extent(), next_extent(), osc_extent_insert(), osc_extent_search(), and prev_extent().
static int trunc_check_cb (const struct lu_env * env, struct cl_io * io, struct osc_page * ops, void * cbdata) [static]
Checks that there are no pages being written in the extent being truncated.
Definition at line 443 of file osc_io.c.
References __u64, CDEBUG, CL_PAGE_DEBUG, CLP_GANG_OKAY, cl_page::cp_vmpage, cl_page_slice::cpl_page, D_CACHE, D_ERROR, list_empty(), LPU64, osc_async_page::oap_cmd, osc_async_page::oap_pending_item, OBD_BRW_RWMASK, OBD_BRW_WRITE, osc_page::ops_cl, osc_page::ops_oap, osc_index(), and start.
Referenced by osc_trunc_check().
static int try_to_add_extent_for_io (struct client_obd * cli, struct osc_extent * ext, struct list_head * rpclist, unsigned int * pc, unsigned int * max_pages) [static]
Try to add extent to one RPC.
We need to think about the following things:
# of pages must not be over max_pages_per_rpc
extent must be compatible with previous ones
Definition at line 1885 of file osc_cache.c.
References CDEBUG, D_CACHE, D_ERROR, EASSERT, ENTRY, list_for_each_entry, list_move_tail(), max, oap2cl_page(), osc_async_page::oap_pending_item, osc_extent::oe_grants, osc_extent::oe_link, osc_extent::oe_mppr, osc_extent::oe_no_merge, osc_extent::oe_nr_pages, osc_extent::oe_owner, osc_extent::oe_pages, osc_extent::oe_srvlock, osc_extent::oe_state, OES_CACHE, OES_LOCK_DONE, OSC_EXTENT_DUMP, overlapped(), and RETURN.
Referenced by get_write_extents(), and osc_send_read_rpc().
static void unstable_page_accounting (struct ptlrpc_bulk_desc * desc, int factor) [inline, static]
Atomic operations are expensive.
We accumulate the accounting for the same page zone to get better performance. In practice this can work pretty good because the pages in the same RPC are likely from the same page zone.
Definition at line 990 of file osc_page.c.
References BD_GET_KIOV, ptlrpc_bulk_desc::bd_iov_count, ptlrpc_bulk_desc::bd_type, LASSERT, likely, and ptlrpc_is_bulk_desc_kiov().
Referenced by add_unstable_page_accounting(), and dec_unstable_page_accounting().
static int weigh_cb (const struct lu_env * env, struct cl_io * io, struct osc_page * ops, void * cbdata) [static]
Definition at line 644 of file osc_lock.c.
References cl_page_is_vmlocked(), CLP_GANG_ABORT, CLP_GANG_OKAY, cl_page::cp_vmpage, cl_page_slice::cpl_page, osc_page::ops_cl, and osc_index().
Referenced by osc_lock_weight().
Variable Documentation
const char* oes_strings[] [static]
Initial value:
 {
        "inv", "active", "cache", "locking", "lockdone", "rpc", "trunc", NULL }
Definition at line 107 of file osc_cache.c.
struct lu_kmem_descr osc_caches[]
Definition at line 59 of file osc_dev.c.
Referenced by osc_exit(), and osc_init().
struct lu_device_type osc_device_type
Initial value:
 {
        .ldt_tags     = LU_DEVICE_CL,
        .ldt_name     = LUSTRE_OSC_NAME,
        .ldt_ops      = &osc_device_type_ops,
        .ldt_ctx_tags = LCT_CL_THREAD
}
Definition at line 243 of file osc_dev.c.
Referenced by lu2osc_dev(), osc_init(), osc_is_object(), and osc_lock_at().
struct lu_device_type osc_device_type
Definition at line 243 of file osc_dev.c.
Referenced by lu2osc_dev(), osc_init(), osc_is_object(), and osc_lock_at().
struct lu_device_type_operations osc_device_type_ops [static]
Initial value:
 {
        .ldto_init = osc_type_init,
        .ldto_fini = osc_type_fini,
        .ldto_start = osc_type_start,
        .ldto_stop  = osc_type_stop,
        .ldto_device_alloc = osc_device_alloc,
        .ldto_device_free  = osc_device_free,
        .ldto_device_init    = osc_device_init,
        .ldto_device_fini    = osc_device_fini
}
Definition at line 229 of file osc_dev.c.
struct kmem_cache* osc_extent_kmem
Definition at line 56 of file osc_dev.c.
Referenced by osc_extent_alloc(), and osc_extent_free().
struct kmem_cache* osc_extent_kmem
Definition at line 56 of file osc_dev.c.
Referenced by osc_extent_alloc(), and osc_extent_free().
struct cl_io_operations osc_io_ops [static]
Definition at line 924 of file osc_io.c.
struct lu_context_key osc_key
Initial value:
 {
        .lct_tags = LCT_CL_THREAD,
        .lct_init = osc_key_init,
        .lct_fini = osc_key_fini
}
Definition at line 132 of file osc_dev.c.
Referenced by osc_env_info().
struct lu_context_key osc_key
Definition at line 132 of file osc_dev.c.
Referenced by osc_env_info().
struct kmem_cache* osc_lock_kmem
Definition at line 52 of file osc_dev.c.
Referenced by osc_lock_fini(), and osc_lock_init().
struct kmem_cache* osc_lock_kmem
Definition at line 52 of file osc_dev.c.
Referenced by osc_lock_fini(), and osc_lock_init().
static struct cl_lock_operations osc_lock_lockless_ops [static, read]
Initial value:
 {
        .clo_fini      = osc_lock_fini,
        .clo_enqueue   = osc_lock_enqueue,
        .clo_cancel    = osc_lock_lockless_cancel,
        .clo_print     = osc_lock_print
}
Definition at line 61 of file osc_lock.c.
Referenced by osc_lock_is_lockless(), and osc_lock_to_lockless().
static struct cl_lock_operations osc_lock_ops [static, read]
Initial value:
 {
        .clo_fini    = osc_lock_fini,
        .clo_enqueue = osc_lock_enqueue,
        .clo_cancel  = osc_lock_cancel,
        .clo_print   = osc_lock_print,
}
Definition at line 60 of file osc_lock.c.
Referenced by osc_lock_upcall().
struct lu_object_operations osc_lu_obj_ops [static]
Initial value:
 {
        .loo_object_init      = osc_object_init,
        .loo_object_release   = NULL,
        .loo_object_free      = osc_object_free,
        .loo_object_print     = osc_object_print,
        .loo_object_invariant = NULL
}
Definition at line 431 of file osc_object.c.
struct lu_device_operations osc_lu_ops [static]
Initial value:
 {
        .ldo_object_alloc      = osc_object_alloc,
        .ldo_process_config    = osc_cl_process_config,
        .ldo_recovery_complete = NULL
}
Definition at line 172 of file osc_dev.c.
Referenced by osc_device_alloc().
struct kmem_cache* osc_object_kmem
Definition at line 53 of file osc_dev.c.
Referenced by osc_object_alloc(), and osc_object_free().
struct kmem_cache* osc_object_kmem
Definition at line 53 of file osc_dev.c.
Referenced by osc_object_alloc(), and osc_object_free().
struct cl_object_operations osc_ops [static]
Initial value:
 {
        .coo_page_init    = osc_page_init,
        .coo_lock_init    = osc_lock_init,
        .coo_io_init      = osc_io_init,
        .coo_attr_get     = osc_attr_get,
        .coo_attr_update  = osc_attr_update,
        .coo_glimpse      = osc_object_glimpse,
        .coo_prune        = osc_object_prune,
        .coo_fiemap       = osc_object_fiemap,
        .coo_req_attr_set = osc_req_attr_set
}
Definition at line 419 of file osc_object.c.
struct cl_page_operations osc_page_ops [static]
Initial value:
 {
        .cpo_print         = osc_page_print,
        .cpo_delete        = osc_page_delete,
        .cpo_clip           = osc_page_clip,
        .cpo_cancel         = osc_page_cancel,
        .cpo_flush          = osc_page_flush
}
Definition at line 372 of file osc_page.c.
struct kmem_cache* osc_quota_kmem
Definition at line 57 of file osc_dev.c.
Referenced by oqi_exit(), osc_oqi_alloc(), and osc_quota_setdq().
struct lu_context_key osc_session_key
Initial value:
 {
        .lct_tags = LCT_SESSION,
        .lct_init = osc_session_init,
        .lct_fini = osc_session_fini
}
Definition at line 156 of file osc_dev.c.
Referenced by osc_env_session().
struct lu_context_key osc_session_key
Definition at line 156 of file osc_dev.c.
Referenced by osc_env_session().
struct kmem_cache* osc_session_kmem
Definition at line 55 of file osc_dev.c.
Referenced by osc_session_fini(), and osc_session_init().
struct kmem_cache* osc_session_kmem
Definition at line 55 of file osc_dev.c.
Referenced by osc_session_fini(), and osc_session_init().
struct kmem_cache* osc_thread_kmem
Definition at line 54 of file osc_dev.c.
Referenced by osc_key_fini(), and osc_key_init().
struct kmem_cache* osc_thread_kmem
Definition at line 54 of file osc_dev.c.
Referenced by osc_key_fini(), and osc_key_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.