Lustre: handles
handles
Data Structures
struct portals_handle_ops
struct portals_handle
Functions
void class_handle_hash (struct portals_handle *, struct portals_handle_ops *ops)
void class_handle_unhash (struct portals_handle *)
void class_handle_hash_back (struct portals_handle *)
void * class_handle2object (__u64 cookie, const void *owner)
void class_handle_free_cb (struct rcu_head *rcu)
int class_handle_init (void)
void class_handle_cleanup (void)
Function Documentation
void* class_handle2object (__u64 cookie, const void * owner)
Definition at line 155 of file lustre_handles.c.
References ENTRY, portals_handle::h_cookie, portals_handle::h_in, portals_handle::h_link, portals_handle::h_lock, portals_handle::h_ops, portals_handle::h_owner, handle_hash, HANDLE_HASH_MASK, handle_bucket::head, portals_handle_ops::hop_addref, LASSERT, likely, and RETURN.
Referenced by __ldlm_handle2lock(), class_conn2export(), and mdt_handle2mfd().
void class_handle_cleanup (void)
Definition at line 254 of file lustre_handles.c.
References CERROR, cleanup_all_handles(), handle_hash, HANDLE_HASH_SIZE, LASSERT, and OBD_FREE_LARGE.
Referenced by obdclass_exit().
void class_handle_free_cb (struct rcu_head * rcu)
Definition at line 187 of file lustre_handles.c.
References portals_handle::h_cookie, portals_handle::h_ops, portals_handle::h_rcu, portals_handle::h_size, portals_handle_ops::hop_free, and OBD_FREE.
void class_handle_hash (struct portals_handle * , struct portals_handle_ops * ops)
Definition at line 64 of file lustre_handles.c.
References CDEBUG, CWARN, D_INFO, ENTRY, EXIT, portals_handle::h_cookie, portals_handle::h_in, portals_handle::h_link, portals_handle::h_lock, portals_handle::h_ops, handle_base, handle_base_lock, handle_hash, HANDLE_HASH_MASK, HANDLE_INCR, handle_bucket::head, LASSERT, list_empty(), handle_bucket::lock, LPX64, and unlikely.
Referenced by class_new_export(), class_new_import(), ldlm_lock_new(), and mdt_mfd_new().
void class_handle_hash_back (struct portals_handle *)
Definition at line 139 of file lustre_handles.c.
References ENTRY, EXIT, portals_handle::h_cookie, portals_handle::h_in, portals_handle::h_link, handle_hash, HANDLE_HASH_MASK, handle_bucket::head, and handle_bucket::lock.
int class_handle_init (void)
bug 21430: add randomness to the initial base
Definition at line 202 of file lustre_handles.c.
References cfs_get_random_bytes(), cfs_srand(), handle_base, handle_base_lock, handle_hash, HANDLE_HASH_SIZE, handle_bucket::head, INIT_LIST_HEAD, LASSERT, handle_bucket::lock, OBD_ALLOC_LARGE, and seed.
Referenced by obdclass_init().
void class_handle_unhash (struct portals_handle *)
Definition at line 128 of file lustre_handles.c.
References class_handle_unhash_nolock(), portals_handle::h_cookie, handle_hash, HANDLE_HASH_MASK, and handle_bucket::lock.
Referenced by class_destroy_import(), class_new_export(), class_unlink_export(), ldlm_lock_destroy_internal(), mdt_close_internal(), mdt_export_cleanup(), and mdt_mfd_open().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.