Lustre: Hash List
Hash List
Double linked lists with a single pointer list head.
Data Structures
struct hlist_node
struct hlist_head
Defines
#define HLIST_HEAD_INIT { NULL_P }
#define HLIST_HEAD(name) struct hlist_head name = { NULL_P }
#define INIT_HLIST_HEAD(ptr) ((ptr)->first = NULL_P)
#define INIT_HLIST_NODE(ptr) ((ptr)->next = NULL_P, (ptr)->pprev = NULL_P)
#define hlist_entry(ptr, type, member) container_of(ptr,type,member)
#define hlist_for_each(pos, head)
#define hlist_for_each_safe(pos, n, head)
#define hlist_for_each_entry(tpos, pos, head, member)
Iterate over an hlist of given type.
#define hlist_for_each_entry_continue(tpos, pos, member)
Iterate over an hlist continuing after existing point.
#define hlist_for_each_entry_from(tpos, pos, member)
Iterate over an hlist continuing from an existing point.
#define hlist_for_each_entry_safe(tpos, pos, n, head, member)
Iterate over an hlist of given type safe against removal of list entry.
Functions
static int hlist_unhashed (const struct hlist_node *h)
static int hlist_empty (const struct hlist_head *h)
static void __hlist_del (struct hlist_node *n)
static void hlist_del (struct hlist_node *n)
static void hlist_del_init (struct hlist_node *n)
static void hlist_add_head (struct hlist_node *n, struct hlist_head *h)
static void hlist_add_before (struct hlist_node *n, struct hlist_node *next)
static void hlist_add_after (struct hlist_node *n, struct hlist_node *next)
Detailed Description
Double linked lists with a single pointer list head.
Mostly useful for hash tables where the two pointer list head is too wasteful. You lose the ability to access the tail in O(1).
Define Documentation
#define hlist_entry (ptr, type, member) container_of(ptr,type,member)
Definition at line 382 of file list.h.
Referenced by cl_env_hops_noop(), cl_env_hops_obj(), conn_exit(), conn_get(), conn_key(), conn_keycmp(), conn_object(), conn_put_locked(), gen_export_get(), gen_export_object(), gen_export_put_locked(), gen_kepcmp(), gen_key(), ldlm_export_flock_get(), ldlm_export_flock_key(), ldlm_export_flock_object(), ldlm_export_flock_put(), ldlm_export_lock_get(), ldlm_export_lock_key(), ldlm_export_lock_keycpy(), ldlm_export_lock_object(), ldlm_export_lock_put(), ldlm_res_hop_get_locked(), ldlm_res_hop_key(), ldlm_res_hop_keycmp(), ldlm_res_hop_object(), ldlm_res_hop_put(), ldlm_resource_get(), lqe64_hash_key(), lqe64_hash_keycmp(), lqe_hash_get(), lqe_hash_object(), lqe_hash_put_locked(), lqe_iter_cb(), lu_obj_hop_get(), lu_obj_hop_key(), lu_obj_hop_keycmp(), lu_obj_hop_object(), lu_site_obj_print(), nid_export_get(), nid_export_object(), nid_export_put_locked(), nid_kepcmp(), nid_key(), nidstats_get(), nidstats_key(), nidstats_object(), nidstats_put_locked(), nm_hash_list_cb(), nodemap_cleanup_iter_cb(), nodemap_hs_get(), nodemap_hs_hashobject(), nodemap_hs_key(), nodemap_hs_put_locked(), oqi_exit(), oqi_key(), oqi_keycmp(), oqi_object(), pool_hashkey_keycmp(), pool_hashobject(), pool_hashrefcount_get(), pool_hashrefcount_put_locked(), pool_key(), qpi_hash_get(), qpi_hash_key(), qpi_hash_keycmp(), qpi_hash_object(), qpi_hash_put_locked(), qsd_entry_iter_cb(), uuid_export_get(), uuid_export_object(), uuid_export_put_locked(), uuid_key(), and uuid_keycmp().
#define hlist_for_each (pos, head)
Value:
for (pos = (head)->first; pos && (prefetch(pos->next), 1); \
             pos = pos->next)
Definition at line 384 of file list.h.
Referenced by cfs_hash_bd_lookup_intent(), cfs_hash_for_each_key(), and cfs_hash_hlist_for_each().
#define hlist_for_each_entry (tpos, pos, head, member)
Value:
for (pos = (head)->first;                                            \
             pos && ({ prefetch(pos->next); 1;}) &&                          \
                ({ tpos = hlist_entry(pos, typeof(*tpos), member); 1;}); \
             pos = pos->next)
Iterate over an hlist of given type.
Parameters:
tpos the type * to use as a loop counter.
pos the &struct hlist_node to use as a loop counter.
head the head for your list.
member the name of the hlist_node within the struct.
Definition at line 399 of file list.h.
Referenced by rsc_flush().
#define hlist_for_each_entry_continue (tpos, pos, member)
Value:
for (pos = (pos)->next;                                              \
             pos && ({ prefetch(pos->next); 1;}) &&                          \
                ({ tpos = hlist_entry(pos, typeof(*tpos), member); 1;}); \
             pos = pos->next)
Iterate over an hlist continuing after existing point.
Parameters:
tpos the type * to use as a loop counter.
pos the &struct hlist_node to use as a loop counter.
member the name of the hlist_node within the struct.
Definition at line 411 of file list.h.
#define hlist_for_each_entry_from (tpos, pos, member)
Value:
for (; pos && ({ prefetch(pos->next); 1;}) &&                        \
                ({ tpos = hlist_entry(pos, typeof(*tpos), member); 1;}); \
             pos = pos->next)
Iterate over an hlist continuing from an existing point.
Parameters:
tpos the type * to use as a loop counter.
pos the &struct hlist_node to use as a loop counter.
member the name of the hlist_node within the struct.
Definition at line 423 of file list.h.
#define hlist_for_each_entry_safe (tpos, pos, n, head, member)
Value:
for (pos = (head)->first;                                            \
             pos && ({ n = pos->next; 1; }) &&                               \
                ({ tpos = hlist_entry(pos, typeof(*tpos), member); 1;}); \
             pos = n)
Iterate over an hlist of given type safe against removal of list entry.
Parameters:
tpos the type * to use as a loop counter.
pos the &struct hlist_node to use as a loop counter.
n another &struct hlist_node to use as temporary storage
head the head for your list.
member the name of the hlist_node within the struct.
Definition at line 436 of file list.h.
#define hlist_for_each_safe (pos, n, head)
Value:
for (pos = (head)->first; pos && (n = pos->next, 1); \
             pos = n)
Definition at line 388 of file list.h.
Referenced by cfs_hash_destroy(), cfs_hash_for_each_tight(), and cfs_hash_rehash_bd().
#define HLIST_HEAD (name) struct hlist_head name = { NULL_P }
Definition at line 314 of file list.h.
Referenced by gss_sec_ctx_replace_pf(), gss_sec_flush_ctx_cache_pf(), gss_sec_lookup_ctx_pf(), and null_init_internal().
#define HLIST_HEAD_INIT { NULL_P }
Definition at line 313 of file list.h.
Referenced by flush_spec_ctx_cache_kr(), and gss_sec_gc_ctx_kr().
#define INIT_HLIST_HEAD (ptr) ((ptr)->first = NULL_P)
Definition at line 315 of file list.h.
Referenced by alloc_rmtperm_hash(), cfs_hash_buckets_realloc(), gss_sec_create_kr(), and gss_sec_create_pf().
#define INIT_HLIST_NODE (ptr) ((ptr)->next = NULL_P, (ptr)->pprev = NULL_P)
Definition at line 316 of file list.h.
Referenced by alloc_ll_remote_perm(), class_new_export(), gss_cli_ctx_init_common(), hlist_del_init(), ldlm_lock_new(), lod_pool_new(), lov_pool_new(), lu_object_header_init(), and ptlrpc_connection_get().
Function Documentation
static void __hlist_del (struct hlist_node * n) [inline, static]
Definition at line 328 of file list.h.
References hlist_node::next, and hlist_node::pprev.
Referenced by ctx_unhash_pf(), gss_sec_lookup_ctx_pf(), hlist_del(), and hlist_del_init().
static void hlist_add_after (struct hlist_node * n, struct hlist_node * next) [inline, static]
Definition at line 371 of file list.h.
References hlist_node::next, and hlist_node::pprev.
static void hlist_add_before (struct hlist_node * n, struct hlist_node * next) [inline, static]
Definition at line 362 of file list.h.
References hlist_node::next, and hlist_node::pprev.
static void hlist_add_head (struct hlist_node * n, struct hlist_head * h) [inline, static]
Definition at line 350 of file list.h.
References hlist_head::first, hlist_node::next, and hlist_node::pprev.
Referenced by cfs_hash_dd_hnode_add(), cfs_hash_dh_hnode_add(), cfs_hash_hd_hnode_add(), cfs_hash_hh_hnode_add(), ctx_enhash_pf(), ctx_enlist_kr(), ctx_unhash_pf(), flush_spec_ctx_cache_kr(), gss_sec_gc_ctx_kr(), gss_sec_lookup_ctx_pf(), ll_update_remote_perm(), and null_init_internal().
static void hlist_del (struct hlist_node * n) [inline, static]
Definition at line 337 of file list.h.
References __hlist_del().
Referenced by free_ll_remote_perm().
static void hlist_del_init (struct hlist_node * n) [inline, static]
Definition at line 342 of file list.h.
References __hlist_del(), INIT_HLIST_NODE, and hlist_node::pprev.
Referenced by cfs_hash_dd_hnode_del(), cfs_hash_dh_hnode_del(), cfs_hash_hd_hnode_del(), cfs_hash_hh_hnode_del(), ctx_list_destroy_pf(), ctx_unhash_pf(), ctx_unlist_kr(), dispose_ctx_list_kr(), gss_cli_ctx_die_pf(), and rsc_flush().
static int hlist_empty (const struct hlist_head * h) [inline, static]
Definition at line 323 of file list.h.
References hlist_head::first.
Referenced by ctx_list_destroy_pf(), gss_sec_destroy_kr(), lu_site_stats_get(), and sec_lookup_root_ctx_kr().
static int hlist_unhashed (const struct hlist_node * h) [inline, static]
Definition at line 318 of file list.h.
References hlist_node::pprev.
Referenced by cfs_hash_add(), cfs_hash_del(), cfs_hash_find_or_add(), cfs_hash_rehash_key(), class_disconnect(), class_new_export(), class_unlink_export(), ctx_unhash_pf(), free_ll_remote_perm(), gss_cli_ctx_die_pf(), gss_sec_release_ctx_pf(), ldlm_flock_blocking_link(), ldlm_flock_blocking_unlink(), ldlm_flock_destroy(), ldlm_process_flock_lock(), lod_pool_putref(), lov_pool_putref(), lu_object_header_fini(), lu_object_header_print(), and tgt_client_free().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.