Lustre: cl_object operations
cl_object operations
[Echo Client]
operations for cl_object
Functions
static int echo_page_init (const struct lu_env *env, struct cl_object *obj, struct cl_page *page, pgoff_t index)
static int echo_io_init (const struct lu_env *env, struct cl_object *obj, struct cl_io *io)
static int echo_lock_init (const struct lu_env *env, struct cl_object *obj, struct cl_lock *lock, const struct cl_io *unused)
static int echo_conf_set (const struct lu_env *env, struct cl_object *obj, const struct cl_object_conf *conf)
Variables
static struct cl_object_operations echo_cl_obj_ops
Detailed Description
operations for cl_object
Function Documentation
static int echo_conf_set (const struct lu_env * env, struct cl_object * obj, const struct cl_object_conf * conf) [static]
Definition at line 443 of file echo_client.c.
static int echo_io_init (const struct lu_env * env, struct cl_object * obj, struct cl_io * io) [static]
Definition at line 420 of file echo_client.c.
static int echo_lock_init (const struct lu_env * env, struct cl_object * obj, struct cl_lock * lock, const struct cl_io * unused) [static]
Definition at line 426 of file echo_client.c.
References cl2echo_obj(), cl_lock_slice_add(), echo_lock_kmem, echo_lock_ops, echo_lock::el_chain, echo_lock::el_cl, echo_lock::el_object, echo_lock::el_refcount, ENTRY, INIT_LIST_HEAD, OBD_SLAB_ALLOC_PTR_GFP, and RETURN.
static int echo_page_init (const struct lu_env * env, struct cl_object * obj, struct cl_page * page, pgoff_t index) [static]
Definition at line 406 of file echo_client.c.
References cl2echo_obj(), cl_object_page_slice(), cl_page_slice_add(), cl_page::cp_vmpage, echo_page_ops, ENTRY, echo_object::eo_npages, echo_page::ep_cl, echo_page::ep_lock, and RETURN.
Variable Documentation
struct cl_object_operations echo_cl_obj_ops [static]
Initial value:
 {
        .coo_page_init = echo_page_init,
        .coo_lock_init = echo_lock_init,
        .coo_io_init   = echo_io_init,
        .coo_conf_set  = echo_conf_set
}
Definition at line 449 of file echo_client.c.
Referenced by echo_object_alloc().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.