Lustre: Network Request Scheduler
Network Request Scheduler
[net]
Service compatibility function; the policy is compatible with all services.
Data Structures
struct ptlrpc_nrs_pol_ops
NRS policy operations.
struct ptlrpc_nrs
NRS head.
struct ptlrpc_nrs_pol_conf
struct ptlrpc_nrs_pol_desc
NRS policy registering descriptor.
struct ptlrpc_nrs_pol_info
NRS policy information.
struct ptlrpc_nrs_policy
NRS policy.
struct ptlrpc_nrs_resource
NRS resource.
struct ptlrpc_nrs_request
NRS request.
Defines
#define NRS_POL_NAME_MAX 16
#define NRS_POL_ARG_MAX 16
Typedefs
typedef bool(* nrs_pol_desc_compat_t)(const struct ptlrpc_service *svc, const struct ptlrpc_nrs_pol_desc *desc)
Service compatibility predicate; this determines whether a policy is adequate for handling RPCs of a particular PTLRPC service.
Enumerations
enum ptlrpc_nrs_ctl { PTLRPC_NRS_CTL_INVALID, PTLRPC_NRS_CTL_START, PTLRPC_NRS_CTL_STOP, PTLRPC_NRS_CTL_1ST_POL_SPEC = 0x20 }
NRS control operations.
enum nrs_policy_flags { PTLRPC_NRS_FL_FALLBACK = (1 << 0), PTLRPC_NRS_FL_REG_START = (1 << 1), PTLRPC_NRS_FL_REG_EXTERN = (1 << 2) }
Policy flags.
enum ptlrpc_nrs_queue_type { PTLRPC_NRS_QUEUE_REG = (1 << 0), PTLRPC_NRS_QUEUE_HP = (1 << 1), PTLRPC_NRS_QUEUE_BOTH = (PTLRPC_NRS_QUEUE_REG | PTLRPC_NRS_QUEUE_HP) }
NRS queue type.
enum ptlrpc_nrs_pol_state {
NRS_POL_STATE_INVALID, NRS_POL_STATE_STOPPED, NRS_POL_STATE_STOPPING, NRS_POL_STATE_STARTING,
NRS_POL_STATE_STARTED
}
NRS policy state.
enum { NRS_RES_FALLBACK, NRS_RES_PRIMARY, NRS_RES_MAX }
Functions
int ptlrpc_nrs_policy_register (struct ptlrpc_nrs_pol_conf *conf)
Registers a new policy with NRS core.
int ptlrpc_nrs_policy_unregister (struct ptlrpc_nrs_pol_conf *conf)
Unregisters a previously registered policy with NRS core.
void ptlrpc_nrs_req_hp_move (struct ptlrpc_request *req)
Moves request req from the regular to the high-priority NRS head.
void nrs_policy_get_info_locked (struct ptlrpc_nrs_policy *policy, struct ptlrpc_nrs_pol_info *info)
static bool ptlrpc_nrs_req_can_move (struct ptlrpc_request *req)
static bool nrs_policy_compat_all (const struct ptlrpc_service *svc, const struct ptlrpc_nrs_pol_desc *desc)
static bool nrs_policy_compat_one (const struct ptlrpc_service *svc, const struct ptlrpc_nrs_pol_desc *desc)
Service compatibility function; the policy is compatible with only a specific service which is identified by its human-readable name at ptlrpc_service::srv_name.
Variables
struct ptlrpc_nrs_request ptlrpc_srv_req::sr_nrq
stub for NRS request
Detailed Description
Service compatibility function; the policy is compatible with all services.
Parameters:
[in] svc The service the policy is attempting to register with.
[in] desc The policy descriptor
Return values:
true The policy is compatible with the service
See also:
ptlrpc_nrs_pol_desc::pd_compat()
Define Documentation
#define NRS_POL_ARG_MAX 16
Definition at line 383 of file lustre_nrs.h.
Referenced by nrs_policy_start_locked().
#define NRS_POL_NAME_MAX 16
Definition at line 382 of file lustre_nrs.h.
Referenced by nrs_policy_find_desc_locked(), nrs_policy_find_locked(), ptlrpc_nrs_policy_register(), and ptlrpc_nrs_policy_unregister().
Typedef Documentation
typedef bool(* nrs_pol_desc_compat_t)(const struct ptlrpc_service *svc, const struct ptlrpc_nrs_pol_desc *desc)
Service compatibility predicate; this determines whether a policy is adequate for handling RPCs of a particular PTLRPC service.
XXX:This should give the same result during policy registration and unregistration, and for all partitions of a service; so the result should not depend on temporal service or other properties, that may influence the result.
Definition at line 396 of file lustre_nrs.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
NRS_RES_FALLBACK
NRS_RES_PRIMARY
NRS_RES_MAX
Definition at line 668 of file lustre_nrs.h.
enum nrs_policy_flags
Policy flags.
Enumerator:
PTLRPC_NRS_FL_FALLBACK
Fallback policy, use this flag only on a single supported policy per service.
The flag cannot be used on policies that use PTLRPC_NRS_FL_REG_EXTERN
PTLRPC_NRS_FL_REG_START
Start policy immediately after registering.
PTLRPC_NRS_FL_REG_EXTERN
This is a policy registering from a module different to the one NRS core ships in (currently ptlrpc).
Definition at line 266 of file lustre_nrs.h.
enum ptlrpc_nrs_ctl
NRS control operations.
These are common for all policies.
Enumerator:
PTLRPC_NRS_CTL_INVALID
Not a valid opcode.
PTLRPC_NRS_CTL_START
Activate the policy.
PTLRPC_NRS_CTL_STOP
Reserved for multiple primary policies, which may be a possibility in the future.
PTLRPC_NRS_CTL_1ST_POL_SPEC
Policies can start using opcodes from this value and onwards for their own purposes; the assigned value itself is arbitrary.
Definition at line 48 of file lustre_nrs.h.
enum ptlrpc_nrs_pol_state
NRS policy state.
Policies transition from one state to the other during their lifetime
Enumerator:
NRS_POL_STATE_INVALID
Not a valid policy state.
NRS_POL_STATE_STOPPED
Policies are at this state either at the start of their life, or transition here when the user selects a different policy to act as the primary one.
NRS_POL_STATE_STOPPING
Policy is progress of stopping.
NRS_POL_STATE_STARTING
Policy is in progress of starting.
NRS_POL_STATE_STARTED
A policy is in this state in two cases:
it is the fallback policy, which is always in this state.
it has been activated by the user; i.e. it is the primary policy,
Definition at line 515 of file lustre_nrs.h.
enum ptlrpc_nrs_queue_type
NRS queue type.
Denotes whether an NRS instance is for handling normal or high-priority RPCs, or whether an operation pertains to one or both of the NRS instances in a service.
Enumerator:
PTLRPC_NRS_QUEUE_REG
PTLRPC_NRS_QUEUE_HP
PTLRPC_NRS_QUEUE_BOTH
Definition at line 291 of file lustre_nrs.h.
Function Documentation
static bool nrs_policy_compat_all (const struct ptlrpc_service * svc, const struct ptlrpc_nrs_pol_desc * desc) [inline, static]
Definition at line 1956 of file lustre_net.h.
static bool nrs_policy_compat_one (const struct ptlrpc_service * svc, const struct ptlrpc_nrs_pol_desc * desc) [inline, static]
Service compatibility function; the policy is compatible with only a specific service which is identified by its human-readable name at ptlrpc_service::srv_name.
Parameters:
[in] svc The service the policy is attempting to register with.
[in] desc The policy descriptor
Return values:
false The policy is not compatible with the service
true The policy is compatible with the service
See also:
ptlrpc_nrs_pol_desc::pd_compat()
Definition at line 1975 of file lustre_net.h.
References LASSERT, ptlrpc_nrs_pol_desc::pd_compat_svc_name, and ptlrpc_service::srv_name.
Referenced by ptlrpc_nrs_policy_register().
void nrs_policy_get_info_locked (struct ptlrpc_nrs_policy * policy, struct ptlrpc_nrs_pol_info * info)
int ptlrpc_nrs_policy_register (struct ptlrpc_nrs_pol_conf * conf)
Registers a new policy with NRS core.
The function will only succeed if policy registration with all compatible service partitions (if any) is successful.
N.B. This function should be called either at ptlrpc module initialization time when registering a policy that ships with NRS core, or in a module's init() function for policies registering from other modules.
Parameters:
[in] conf configuration information for the new policy to register
Return values:
-ve error
0 success
External policies are not allowed to start immediately upon registration, as there is a relatively higher chance that their registration might fail. In such a case, some policy instances may already have requests queued wen unregistration needs to happen as part o cleanup; since there is currently no way to drain requests from a policy unless the service is unregistering, we just disallow this.
For policies that are held in the same module as NRS (currently ptlrpc), do not register the policy with all compatible services, as the services will not have started at this point, since we are calling from ptlrpc module initialization code. In such cases each service will register all compatible policies later, via ptlrpc_service_nrs_setup().
Register the new policy on all compatible services
Should not fail at this point
No need to take a reference to other modules here, as we will be calling from the module's init() function.
Should not fail at this point
Definition at line 1165 of file nrs.c.
References CERROR, ENTRY, ergo, GOTO, LASSERT, list_add_tail(), list_for_each_entry, ptlrpc_nrs_pol_conf::nc_compat, ptlrpc_nrs_pol_conf::nc_compat_svc_name, ptlrpc_nrs_pol_conf::nc_flags, ptlrpc_nrs_pol_conf::nc_name, ptlrpc_nrs_pol_conf::nc_ops, ptlrpc_nrs_pol_conf::nc_owner, NRS_POL_NAME_MAX, nrs_policy_compat_one(), nrs_policy_compatible(), nrs_policy_find_desc_locked(), nrs_policy_register(), nrs_policy_unregister_locked(), nrs_svc_has_hp(), nrs_svcpt2nrs(), OBD_ALLOC_PTR, OBD_FREE_PTR, ptlrpc_nrs_pol_ops::op_lprocfs_init, ptlrpc_nrs_pol_desc::pd_compat, ptlrpc_nrs_pol_desc::pd_compat_svc_name, ptlrpc_nrs_pol_desc::pd_flags, ptlrpc_nrs_pol_desc::pd_list, ptlrpc_nrs_pol_desc::pd_name, ptlrpc_nrs_pol_desc::pd_ops, ptlrpc_nrs_pol_desc::pd_owner, ptlrpc_nrs_pol_desc::pd_refs, ptlrpc_all_services, ptlrpc_all_services_mutex, PTLRPC_NRS_FL_FALLBACK, PTLRPC_NRS_FL_REG_EXTERN, PTLRPC_NRS_FL_REG_START, ptlrpc_service_for_each_part, RETURN, ptlrpc_service_part::scp_cpt, ptlrpc_service::srv_is_stopping, strlcpy(), and unlikely.
Referenced by ptlrpc_nrs_init().
int ptlrpc_nrs_policy_unregister (struct ptlrpc_nrs_pol_conf * conf)
Unregisters a previously registered policy with NRS core.
All instances of the policy on all NRS heads of all supported services are removed.
N.B. This function should only be called from a module's exit() function. Although it can be used for policies that ship alongside NRS core, the function is primarily intended for policies that register externally, from other modules.
Parameters:
[in] conf configuration information for the policy to unregister
Return values:
-ve error
0 success
Definition at line 1323 of file nrs.c.
References CDEBUG, CERROR, D_INFO, ENTRY, GOTO, LASSERT, list_del(), ptlrpc_nrs_pol_conf::nc_flags, ptlrpc_nrs_pol_conf::nc_name, NRS_POL_NAME_MAX, nrs_policy_find_desc_locked(), nrs_policy_unregister_locked(), OBD_FREE_PTR, ptlrpc_nrs_pol_desc::pd_list, ptlrpc_all_services_mutex, PTLRPC_NRS_FL_FALLBACK, and RETURN.
static bool ptlrpc_nrs_req_can_move (struct ptlrpc_request * req) [inline, static]
LU-898: Check ptlrpc_nrs_request::nr_enqueued to make sure the request has been enqueued first, and ptlrpc_nrs_request::nr_started to make sure it has not been scheduled yet (analogous to previous (non-NRS) checking of !list_empty(&ptlrpc_request::rq_list).
Definition at line 1155 of file lustre_net.h.
References ptlrpc_nrs_request::nr_enqueued, ptlrpc_nrs_request::nr_started, and ptlrpc_request::rq_hp.
Referenced by ptlrpc_nrs_req_hp_move().
void ptlrpc_nrs_req_hp_move (struct ptlrpc_request * req)
Moves request req from the regular to the high-priority NRS head.
Parameters:
[in] req the request to move
Obtain the high-priority NRS head resources.
Release either the regular NRS head resources if we moved the request, or the high-priority NRS head resources if we took a reference earlier in this function and ptlrpc_nrs_req_can_move() returned false.
Definition at line 1673 of file nrs.c.
References ENTRY, EXIT, ptlrpc_nrs_request::nr_res_ptrs, NRS_RES_MAX, nrs_resource_get_safe(), nrs_resource_put_safe(), nrs_svcpt2nrs(), ptlrpc_nrs_hpreq_add_nolock(), ptlrpc_nrs_req_can_move(), and ptlrpc_nrs_req_del_nolock().
Variable Documentation
struct ptlrpc_nrs_request ptlrpc_srv_req::sr_nrq [read, inherited]
stub for NRS request
Definition at line 910 of file lustre_net.h.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.