Lustre: lustre/ptlrpc/gss/gss_cli_upcall.c File Reference
lustre/ptlrpc/gss/gss_cli_upcall.c File Reference
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/dcache.h>
#include <linux/fs.h>
#include <linux/mutex.h>
#include <obd.h>
#include <obd_class.h>
#include <obd_support.h>
#include <lustre/lustre_idl.h>
#include <lustre_net.h>
#include <lustre_import.h>
#include <lustre_sec.h>
#include "gss_err.h"
#include "gss_internal.h"
#include "gss_api.h"
Data Structures
struct lgssd_ioctl_param
Defines
#define DEBUG_SUBSYSTEM S_SEC
Functions
static int ctx_init_pack_request (struct obd_import *imp, struct ptlrpc_request *req, int lustre_srv, uid_t uid, gid_t gid, long token_size, char __user *token)
static int ctx_init_parse_reply (struct lustre_msg *msg, int swabbed, char __user *outbuf, long outlen)
int gss_do_ctx_init_rpc (char __user *buffer, unsigned long count)
int gss_do_ctx_fini_rpc (struct gss_cli_ctx *gctx)
int __init gss_init_cli_upcall (void)
void gss_exit_cli_upcall (void)
Define Documentation
#define DEBUG_SUBSYSTEM S_SEC
Definition at line 41 of file gss_cli_upcall.c.
Function Documentation
static int ctx_init_pack_request (struct obd_import * imp, struct ptlrpc_request * req, int lustre_srv, uid_t uid, gid_t gid, long token_size, char __user * token) [static]
Definition at line 66 of file gss_cli_upcall.c.
References CERROR, cfs_size_round4(), client_obd::cl_target_uuid, obd_device::cli, cpu_to_le32, rawobj_s::data, gss_header::gh_flags, gss_header::gh_handle, gss_header::gh_proc, gss_header::gh_seq, gss_header::gh_sp, gss_header::gh_svc, gss_header::gh_version, gss_sec::gs_rvs_hdl, obd_import::imp_obd, obd_import::imp_sec, LASSERT, LBUG, rawobj_s::len, netobj_s::len, LUSTRE_GSS_PACK_USER, lustre_msg, lustre_msg_buf(), lustre_shrink_msg(), msg, ptlrpc_sec::ps_part, PTLRPC_GSS_PROC_INIT, PTLRPC_GSS_VERSION, ptlrpc_user_desc::pud_cap, ptlrpc_user_desc::pud_fsgid, ptlrpc_user_desc::pud_fsuid, ptlrpc_user_desc::pud_gid, ptlrpc_user_desc::pud_ngroups, ptlrpc_user_desc::pud_uid, rawobj_serialize(), ptlrpc_request::rq_pack_udesc, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqdata_len, sec2gsec(), size, SPTLRPC_SVC_NULL, obd_device::u, and obd_uuid::uuid.
Referenced by gss_do_ctx_init_rpc().
static int ctx_init_parse_reply (struct lustre_msg * msg, int swabbed, char __user * outbuf, long outlen) [static]
Definition at line 146 of file gss_cli_upcall.c.
References CERROR, cfs_size_round4(), netobj_s::data, gss_rep_header::gh_handle, gss_rep_header::gh_major, gss_rep_header::gh_minor, gss_rep_header::gh_seqwin, gss_rep_header::gh_version, gss_swab_header(), netobj_s::len, lustre_msg_buf(), PTLRPC_GSS_VERSION, and status.
Referenced by gss_do_ctx_init_rpc().
int gss_do_ctx_fini_rpc (struct gss_cli_ctx * gctx)
Definition at line 376 of file gss_cli_upcall.c.
References ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_sec, ptlrpc_cli_ctx::cc_vcred, CDEBUG, cli_ctx_is_error(), cli_ctx_is_uptodate(), CWARN, D_SEC, ENTRY, gss_cli_ctx::gc_base, gss_cli_ctx::gc_handle, gss_cli_ctx::gc_proc, GOTO, gss_handle_to_u64(), LASSERT, LPX64, lustre_msg_buf(), LUSTRE_OBD_VERSION, ptlrpc_sec::ps_import, ptl_send_rpc(), PTLRPC_GSS_PROC_DESTROY, ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_bufs_pack(), ptlrpc_user_desc::pud_cap, ptlrpc_user_desc::pud_fsgid, ptlrpc_user_desc::pud_fsuid, ptlrpc_user_desc::pud_gid, ptlrpc_user_desc::pud_ngroups, ptlrpc_user_desc::pud_uid, RETURN, ptlrpc_request::rq_pack_udesc, ptlrpc_request::rq_phase, RQ_PHASE_RPC, ptlrpc_request::rq_reqbuf, RQF_SEC_CTX, sec2target_str(), SEC_CTX_FINI, sec_is_reverse(), vfs_cred::vc_gid, and vfs_cred::vc_uid.
Referenced by gss_cli_ctx_fini_common().
int gss_do_ctx_init_rpc (char __user * buffer, unsigned long count)
Definition at line 233 of file gss_cli_upcall.c.
References CERROR, client_obd::cl_import, client_obd::cl_sem, class_import_get(), class_import_put(), class_name2obd(), obd_device::cli, ctx_init_pack_request(), ctx_init_parse_reply(), CWARN, lgssd_ioctl_param::gid, GSSD_INTERFACE_VERSION, obd_import::imp_deactive, LASSERT, LUSTRE_LWP_NAME, LUSTRE_MDC_NAME, LUSTRE_MGC_NAME, LUSTRE_OBD_VERSION, LUSTRE_OSC_NAME, LUSTRE_OSP_NAME, lgssd_ioctl_param::lustre_svc, obd_device::obd_dev_lock, obd_device::obd_name, obd_device::obd_set_up, obd_device::obd_stopping, obd_device::obd_type, ptlrpc_queue_wait(), ptlrpc_rep_need_swab(), ptlrpc_req_finished(), ptlrpc_request_alloc_pack(), ptlrpc_request_set_replen(), lgssd_ioctl_param::reply_buf, lgssd_ioctl_param::reply_buf_size, lgssd_ioctl_param::reply_length, RETURN, ptlrpc_request::rq_repdata, RQF_SEC_CTX, SEC_CTX_INIT, lgssd_ioctl_param::secid, lgssd_ioctl_param::send_token, lgssd_ioctl_param::send_token_size, lgssd_ioctl_param::status, obd_type::typ_name, obd_device::u, lgssd_ioctl_param::uid, unlikely, lgssd_ioctl_param::uuid, and lgssd_ioctl_param::version.
Referenced by gss_proc_write_secinit().
void gss_exit_cli_upcall (void)
Definition at line 445 of file gss_cli_upcall.c.
Referenced by sptlrpc_gss_exit(), and sptlrpc_gss_init().
int __init gss_init_cli_upcall (void)
Definition at line 440 of file gss_cli_upcall.c.
Referenced by sptlrpc_gss_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.