Lustre: lustre/ptlrpc/gss/gss_bulk.c File Reference
lustre/ptlrpc/gss/gss_bulk.c File Reference
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/dcache.h>
#include <linux/fs.h>
#include <linux/mutex.h>
#include <linux/crypto.h>
#include <obd.h>
#include <obd_class.h>
#include <obd_support.h>
#include <lustre/lustre_idl.h>
#include <lustre_net.h>
#include <lustre_import.h>
#include <lustre_sec.h>
#include "gss_err.h"
#include "gss_internal.h"
#include "gss_api.h"
Defines
#define DEBUG_SUBSYSTEM S_SEC
Functions
int gss_cli_ctx_wrap_bulk (struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
int gss_cli_ctx_unwrap_bulk (struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
static int gss_prep_bulk (struct ptlrpc_bulk_desc *desc, struct gss_ctx *mechctx)
int gss_cli_prep_bulk (struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
int gss_svc_prep_bulk (struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
int gss_svc_unwrap_bulk (struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
int gss_svc_wrap_bulk (struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
Define Documentation
#define DEBUG_SUBSYSTEM S_SEC
Definition at line 41 of file gss_bulk.c.
Function Documentation
int gss_cli_ctx_unwrap_bulk (struct ptlrpc_cli_ctx * ctx, struct ptlrpc_request * req, struct ptlrpc_bulk_desc * desc)
Definition at line 168 of file gss_bulk.c.
References BD_GET_KIOV, ptlrpc_bulk_desc::bd_iov_count, ptlrpc_bulk_desc::bd_nob, ptlrpc_bulk_desc::bd_nob_transferred, ptlrpc_bulk_desc::bd_type, ptlrpc_bulk_sec_desc::bsd_data, BSD_FL_ERR, ptlrpc_bulk_sec_desc::bsd_flags, ptlrpc_bulk_sec_desc::bsd_nob, ptlrpc_bulk_sec_desc::bsd_svc, ptlrpc_bulk_sec_desc::bsd_type, ptlrpc_bulk_sec_desc::bsd_version, CERROR, rawobj_s::data, ENTRY, gss_cli_ctx::gc_mechctx, GET_KIOV, GSS_S_COMPLETE, LASSERT, LBUG, rawobj_s::len, lgss_unwrap_bulk(), lgss_verify_mic(), lustre_msg, lustre_msg_buf(), lustre_msg_buflen(), ptlrpc_is_bulk_desc_kiov(), RETURN, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_clrbuf, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_repdata, ptlrpc_request::rq_reqbuf, sptlrpc_flavor::sf_rpc, SPTLRPC_BULK_SVC_INTG, SPTLRPC_BULK_SVC_NULL, SPTLRPC_BULK_SVC_PRIV, SPTLRPC_FLVR_SVC, SPTLRPC_SVC_AUTH, SPTLRPC_SVC_INTG, SPTLRPC_SVC_NULL, and SPTLRPC_SVC_PRIV.
int gss_cli_ctx_wrap_bulk (struct ptlrpc_cli_ctx * ctx, struct ptlrpc_request * req, struct ptlrpc_bulk_desc * desc)
Definition at line 62 of file gss_bulk.c.
References ptlrpc_bulk_desc::bd_iov_count, ptlrpc_bulk_desc::bd_nob, ptlrpc_bulk_desc::bd_type, ptlrpc_bulk_sec_desc::bsd_data, ptlrpc_bulk_sec_desc::bsd_flags, ptlrpc_bulk_sec_desc::bsd_nob, ptlrpc_bulk_sec_desc::bsd_svc, ptlrpc_bulk_sec_desc::bsd_type, ptlrpc_bulk_sec_desc::bsd_version, CERROR, CWARN, rawobj_s::data, ENTRY, gss_cli_ctx::gc_mechctx, GET_KIOV, gss_cli_prep_bulk(), GSS_S_COMPLETE, LASSERT, LBUG, rawobj_s::len, lgss_get_mic(), lgss_wrap_bulk(), lustre_msg, lustre_msg_buf(), lustre_msg_buflen(), msg, ptlrpc_is_bulk_desc_kiov(), RETURN, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_clrbuf, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_reqbuf, sptlrpc_flavor::sf_rpc, SPTLRPC_BULK_DEFAULT, SPTLRPC_BULK_SVC_INTG, SPTLRPC_BULK_SVC_NULL, SPTLRPC_BULK_SVC_PRIV, sptlrpc_enc_pool_get_pages(), SPTLRPC_FLVR_BULK_SVC, SPTLRPC_FLVR_SVC, SPTLRPC_SVC_AUTH, SPTLRPC_SVC_INTG, SPTLRPC_SVC_NULL, and SPTLRPC_SVC_PRIV.
int gss_cli_prep_bulk (struct ptlrpc_request * req, struct ptlrpc_bulk_desc * desc)
Definition at line 323 of file gss_bulk.c.
References CERROR, ctx2gctx(), ENTRY, gss_cli_ctx::gc_mechctx, gss_prep_bulk(), LASSERT, RETURN, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pack_bulk, sptlrpc_flavor::sf_rpc, SPTLRPC_BULK_SVC_PRIV, and SPTLRPC_FLVR_BULK_SVC.
Referenced by gss_cli_ctx_wrap_bulk().
static int gss_prep_bulk (struct ptlrpc_bulk_desc * desc, struct gss_ctx * mechctx) [static]
Definition at line 305 of file gss_bulk.c.
References ptlrpc_bulk_desc::bd_iov_count, GSS_S_COMPLETE, lgss_prep_bulk(), and sptlrpc_enc_pool_get_pages().
Referenced by gss_cli_prep_bulk(), and gss_svc_prep_bulk().
int gss_svc_prep_bulk (struct ptlrpc_request * req, struct ptlrpc_bulk_desc * desc)
Definition at line 344 of file gss_bulk.c.
References ptlrpc_bulk_sec_desc::bsd_svc, CERROR, ENTRY, gss_svc_ctx::gsc_mechctx, gss_prep_bulk(), gss_svc_ctx2reqctx(), LASSERT, RETURN, ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_pack_bulk, SPTLRPC_BULK_SVC_PRIV, gss_svc_reqctx::src_ctx, gss_svc_reqctx::src_repbsd, and gss_svc_reqctx::src_reqbsd.
int gss_svc_unwrap_bulk (struct ptlrpc_request * req, struct ptlrpc_bulk_desc * desc)
Definition at line 374 of file gss_bulk.c.
References ptlrpc_bulk_desc::bd_iov_count, ptlrpc_bulk_desc::bd_nob, ptlrpc_bulk_desc::bd_nob_transferred, ptlrpc_bulk_desc::bd_type, ptlrpc_bulk_sec_desc::bsd_data, BSD_FL_ERR, ptlrpc_bulk_sec_desc::bsd_flags, ptlrpc_bulk_sec_desc::bsd_nob, ptlrpc_bulk_sec_desc::bsd_svc, ptlrpc_bulk_sec_desc::bsd_type, ptlrpc_bulk_sec_desc::bsd_version, CERROR, rawobj_s::data, ENTRY, GET_KIOV, gss_svc_ctx::gsc_mechctx, GSS_S_COMPLETE, gss_svc_ctx2reqctx(), LASSERT, rawobj_s::len, lgss_unwrap_bulk(), lgss_verify_mic(), ptlrpc_is_bulk_desc_kiov(), RETURN, ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_pack_bulk, SPTLRPC_BULK_DEFAULT, SPTLRPC_BULK_SVC_INTG, SPTLRPC_BULK_SVC_PRIV, gss_svc_reqctx::src_ctx, gss_svc_reqctx::src_repbsd, gss_svc_reqctx::src_reqbsd, and gss_svc_reqctx::src_reqbsd_size.
int gss_svc_wrap_bulk (struct ptlrpc_request * req, struct ptlrpc_bulk_desc * desc)
Definition at line 451 of file gss_bulk.c.
References ptlrpc_bulk_desc::bd_iov_count, ptlrpc_bulk_desc::bd_nob, ptlrpc_bulk_desc::bd_type, ptlrpc_bulk_sec_desc::bsd_data, BSD_FL_ERR, ptlrpc_bulk_sec_desc::bsd_flags, ptlrpc_bulk_sec_desc::bsd_nob, ptlrpc_bulk_sec_desc::bsd_svc, ptlrpc_bulk_sec_desc::bsd_type, ptlrpc_bulk_sec_desc::bsd_version, CERROR, rawobj_s::data, ENTRY, GET_KIOV, gss_svc_ctx::gsc_mechctx, GSS_S_COMPLETE, gss_svc_ctx2reqctx(), LASSERT, rawobj_s::len, lgss_get_mic(), lgss_wrap_bulk(), ptlrpc_is_bulk_desc_kiov(), RETURN, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_pack_bulk, SPTLRPC_BULK_DEFAULT, SPTLRPC_BULK_SVC_INTG, SPTLRPC_BULK_SVC_PRIV, sptlrpc_enc_pool_get_pages(), gss_svc_reqctx::src_ctx, gss_svc_reqctx::src_repbsd, gss_svc_reqctx::src_repbsd_size, and gss_svc_reqctx::src_reqbsd.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.