Lustre: lustre/ptlrpc/gss/gss_rawobj.c File Reference
lustre/ptlrpc/gss/gss_rawobj.c File Reference
#include <linux/mutex.h>
#include <obd.h>
#include <obd_class.h>
#include <obd_support.h>
#include <lustre_sec.h>
#include "gss_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_SEC
Functions
int rawobj_empty (rawobj_t *obj)
int rawobj_alloc (rawobj_t *obj, char *buf, int len)
void rawobj_free (rawobj_t *obj)
int rawobj_equal (rawobj_t *a, rawobj_t *b)
int rawobj_dup (rawobj_t *dest, rawobj_t *src)
int rawobj_serialize (rawobj_t *obj, __u32 **buf, __u32 *buflen)
static int __rawobj_extract (rawobj_t *obj, __u32 **buf, __u32 *buflen, int alloc, int local)
int rawobj_extract (rawobj_t *obj, __u32 **buf, __u32 *buflen)
int rawobj_extract_alloc (rawobj_t *obj, __u32 **buf, __u32 *buflen)
int rawobj_extract_local (rawobj_t *obj, __u32 **buf, __u32 *buflen)
int rawobj_extract_local_alloc (rawobj_t *obj, __u32 **buf, __u32 *buflen)
int rawobj_from_netobj (rawobj_t *rawobj, netobj_t *netobj)
int rawobj_from_netobj_alloc (rawobj_t *rawobj, netobj_t *netobj)
int buffer_extract_bytes (const void **buf, __u32 *buflen, void *res, __u32 reslen)
Define Documentation
#define DEBUG_SUBSYSTEM S_SEC
Definition at line 41 of file gss_rawobj.c.
Function Documentation
static int __rawobj_extract (rawobj_t * obj, __u32 ** buf, __u32 * buflen, int alloc, int local) [static]
Definition at line 137 of file gss_rawobj.c.
References CERROR, cfs_size_round4(), rawobj_s::data, le32_to_cpu, rawobj_s::len, and OBD_ALLOC_LARGE.
Referenced by rawobj_extract(), rawobj_extract_alloc(), rawobj_extract_local(), and rawobj_extract_local_alloc().
int buffer_extract_bytes (const void ** buf, __u32 * buflen, void * res, __u32 reslen)
Definition at line 230 of file gss_rawobj.c.
References CERROR.
Referenced by gss_kt_update().
int rawobj_alloc (rawobj_t * obj, char * buf, int len)
Definition at line 58 of file gss_rawobj.c.
References rawobj_s::data, LASSERT, rawobj_s::len, OBD_ALLOC_LARGE, and RETURN.
Referenced by gss_svc_upcall_install_rvs_ctx(), rsc_parse(), and rsi_parse().
int rawobj_dup (rawobj_t * dest, rawobj_t * src)
Definition at line 97 of file gss_rawobj.c.
References rawobj_s::data, LASSERT, rawobj_s::len, and OBD_ALLOC_LARGE.
Referenced by gss_copy_reverse_context_kerberos(), gss_copy_rvc_cli_ctx(), gss_pipe_downcall(), gss_svc_searchbyctx(), gss_svc_upcall_dup_handle(), gss_svc_upcall_handle_init(), gss_svc_upcall_install_rvs_ctx(), and keyblock_dup().
int rawobj_empty (rawobj_t * obj)
Definition at line 52 of file gss_rawobj.c.
References rawobj_s::data, equi, LASSERT, and rawobj_s::len.
Referenced by dispose_ctx_list_kr(), and gss_cli_ctx_finalize().
int rawobj_equal (rawobj_t * a, rawobj_t * b)
Definition at line 89 of file gss_rawobj.c.
References rawobj_s::data, LASSERT, and rawobj_s::len.
Referenced by __rsc_match(), and __rsi_match().
int rawobj_extract (rawobj_t * obj, __u32 ** buf, __u32 * buflen)
Definition at line 182 of file gss_rawobj.c.
References __rawobj_extract().
Referenced by gss_svc_handle_init().
int rawobj_extract_alloc (rawobj_t * obj, __u32 ** buf, __u32 * buflen)
Definition at line 187 of file gss_rawobj.c.
References __rawobj_extract().
int rawobj_extract_local (rawobj_t * obj, __u32 ** buf, __u32 * buflen)
Definition at line 192 of file gss_rawobj.c.
References __rawobj_extract().
Referenced by gss_kt_update(), and gss_pipe_downcall().
int rawobj_extract_local_alloc (rawobj_t * obj, __u32 ** buf, __u32 * buflen)
Definition at line 197 of file gss_rawobj.c.
References __rawobj_extract().
Referenced by gss_kt_update().
void rawobj_free (rawobj_t * obj)
Definition at line 76 of file gss_rawobj.c.
References rawobj_s::data, LASSERT, rawobj_s::len, and OBD_FREE_LARGE.
Referenced by delete_context_kerberos(), gss_cli_ctx_finalize(), gss_copy_rvc_cli_ctx(), gss_get_mic_kerberos(), gss_svc_upcall_handle_init(), gss_unwrap_bulk_kerberos(), gss_unwrap_kerberos(), gss_verify_mic_kerberos(), gss_wrap_bulk_kerberos(), gss_wrap_kerberos(), keyblock_free(), rsc_free(), and rsi_free().
int rawobj_from_netobj (rawobj_t * rawobj, netobj_t * netobj)
Definition at line 202 of file gss_rawobj.c.
References netobj_s::data, rawobj_s::data, netobj_s::len, and rawobj_s::len.
Referenced by gss_svc_accept().
int rawobj_from_netobj_alloc (rawobj_t * rawobj, netobj_t * netobj)
Definition at line 209 of file gss_rawobj.c.
References netobj_s::data, rawobj_s::data, netobj_s::len, rawobj_s::len, and OBD_ALLOC_LARGE.
int rawobj_serialize (rawobj_t * obj, __u32 ** buf, __u32 * buflen)
Definition at line 114 of file gss_rawobj.c.
References CERROR, cfs_size_round4(), cpu_to_le32, rawobj_s::data, LASSERT, and rawobj_s::len.
Referenced by ctx_init_pack_request().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.