Lustre: lustre/ptlrpc/gss/gss_keyring.c File Reference
lustre/ptlrpc/gss/gss_keyring.c File Reference
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/dcache.h>
#include <linux/fs.h>
#include <linux/crypto.h>
#include <linux/key.h>
#include <linux/keyctl.h>
#include <linux/key-type.h>
#include <linux/mutex.h>
#include <asm/atomic.h>
#include <obd.h>
#include <obd_class.h>
#include <obd_support.h>
#include <lustre/lustre_idl.h>
#include <lustre_sec.h>
#include <lustre_net.h>
#include <lustre_import.h>
#include "gss_err.h"
#include "gss_internal.h"
#include "gss_api.h"
Defines
#define DEBUG_SUBSYSTEM S_SEC
#define KEYRING_UPCALL_TIMEOUT (obd_timeout + obd_timeout)
#define DUMP_PROCESS_KEYRINGS(tsk)
#define DUMP_KEY(key)
#define key_cred(tsk) ((tsk)->cred)
#define key_tgcred(tsk) key_cred(tsk)
#define RVS_CTX_EXPIRE_NICE (10)
#define HAVE_REVERSE_CTX_NOKEY
Functions
static int sec_install_rctx_kr (struct ptlrpc_sec *sec, struct ptlrpc_svc_ctx *svc_ctx)
static void keyring_upcall_lock (struct gss_sec_keyring *gsec_kr)
static void keyring_upcall_unlock (struct gss_sec_keyring *gsec_kr)
static void key_revoke_locked (struct key *key)
static void ctx_upcall_timeout_kr (unsigned long data)
static void ctx_start_timer_kr (struct ptlrpc_cli_ctx *ctx, long timeout)
static void ctx_clear_timer_kr (struct ptlrpc_cli_ctx *ctx)
static struct ptlrpc_cli_ctx * ctx_create_kr (struct ptlrpc_sec *sec, struct vfs_cred *vcred)
static void ctx_destroy_kr (struct ptlrpc_cli_ctx *ctx)
static void ctx_release_kr (struct ptlrpc_cli_ctx *ctx, int sync)
static void ctx_put_kr (struct ptlrpc_cli_ctx *ctx, int sync)
static void spin_lock_if (spinlock_t *lock, int condition)
static void spin_unlock_if (spinlock_t *lock, int condition)
static void ctx_enlist_kr (struct ptlrpc_cli_ctx *ctx, int is_root, int locked)
static int ctx_unlist_kr (struct ptlrpc_cli_ctx *ctx, int locked)
static void * key_get_payload (struct key *key, unsigned int index)
static int key_set_payload (struct key *key, unsigned int index, struct ptlrpc_cli_ctx *ctx)
static void bind_key_ctx (struct key *key, struct ptlrpc_cli_ctx *ctx)
static void unbind_key_ctx (struct key *key, struct ptlrpc_cli_ctx *ctx)
static void unbind_ctx_kr (struct ptlrpc_cli_ctx *ctx)
static void unbind_key_locked (struct key *key)
static void kill_ctx_kr (struct ptlrpc_cli_ctx *ctx)
static void kill_key_locked (struct key *key)
static void dispose_ctx_list_kr (struct hlist_head *freelist)
static struct ptlrpc_cli_ctx * sec_lookup_root_ctx_kr (struct ptlrpc_sec *sec)
static void rvs_sec_install_root_ctx_kr (struct ptlrpc_sec *sec, struct ptlrpc_cli_ctx *new_ctx, struct key *key)
static void construct_key_desc (void *buf, int bufsize, struct ptlrpc_sec *sec, uid_t uid)
static struct ptlrpc_sec * gss_sec_create_kr (struct obd_import *imp, struct ptlrpc_svc_ctx *svcctx, struct sptlrpc_flavor *sf)
static void gss_sec_destroy_kr (struct ptlrpc_sec *sec)
static int user_is_root (struct ptlrpc_sec *sec, struct vfs_cred *vcred)
static void request_key_unlink (struct key *key)
static struct ptlrpc_cli_ctx * gss_sec_lookup_ctx_kr (struct ptlrpc_sec *sec, struct vfs_cred *vcred, int create, int remove_dead)
static void gss_sec_release_ctx_kr (struct ptlrpc_sec *sec, struct ptlrpc_cli_ctx *ctx, int sync)
static void flush_user_ctx_cache_kr (struct ptlrpc_sec *sec, uid_t uid, int grace, int force)
static void flush_spec_ctx_cache_kr (struct ptlrpc_sec *sec, uid_t uid, int grace, int force)
static int gss_sec_flush_ctx_cache_kr (struct ptlrpc_sec *sec, uid_t uid, int grace, int force)
static void gss_sec_gc_ctx_kr (struct ptlrpc_sec *sec)
static int gss_sec_display_kr (struct ptlrpc_sec *sec, struct seq_file *seq)
static int gss_cli_ctx_refresh_kr (struct ptlrpc_cli_ctx *ctx)
static int gss_cli_ctx_validate_kr (struct ptlrpc_cli_ctx *ctx)
static void gss_cli_ctx_die_kr (struct ptlrpc_cli_ctx *ctx, int grace)
static int gss_svc_accept_kr (struct ptlrpc_request *req)
static int gss_svc_install_rctx_kr (struct obd_import *imp, struct ptlrpc_svc_ctx *svc_ctx)
static int gss_kt_instantiate (struct key *key, const void *data, size_t datalen)
static int gss_kt_update (struct key *key, const void *data, size_t datalen)
static int gss_kt_match (const struct key *key, const void *desc)
static void gss_kt_destroy (struct key *key)
static void gss_kt_describe (const struct key *key, struct seq_file *s)
int __init gss_init_keyring (void)
void __exit gss_exit_keyring (void)
Variables
static struct ptlrpc_sec_policy gss_policy_keyring
static struct ptlrpc_ctx_ops gss_keyring_ctxops
static struct key_type gss_key_type
static struct ptlrpc_sec_cops gss_sec_keyring_cops
static struct ptlrpc_sec_sops gss_sec_keyring_sops
Define Documentation
#define DEBUG_SUBSYSTEM S_SEC
Definition at line 41 of file gss_keyring.c.
#define DUMP_KEY (key)
Value:
{                                                                       \
        CWARN("DUMP KEY: %p(%d) ref %d u%u/g%u desc %s\n",              \
              key, key->serial, atomic_read(&key->usage),               \
              key->uid, key->gid,                                       \
              key->description ? key->description : "n/a"               \
             );                                                         \
}
Definition at line 111 of file gss_keyring.c.
#define DUMP_PROCESS_KEYRINGS (tsk)
Value:
{                                                                       \
        CWARN("DUMP PK: %s[%u,%u/%u](<-%s[%u,%u/%u]): "                 \
              "a %d, t %d, p %d, s %d, u %d, us %d, df %d\n",           \
              tsk->comm, tsk->pid, tsk->uid, tsk->fsuid,                \
              tsk->parent->comm, tsk->parent->pid,                      \
              tsk->parent->uid, tsk->parent->fsuid,                     \
              tsk->request_key_auth ?                                   \
              tsk->request_key_auth->serial : 0,                        \
              key_cred(tsk)->thread_keyring ?                           \
              key_cred(tsk)->thread_keyring->serial : 0,                \
              key_tgcred(tsk)->process_keyring ?                        \
              key_tgcred(tsk)->process_keyring->serial : 0,             \
              key_tgcred(tsk)->session_keyring ?                        \
              key_tgcred(tsk)->session_keyring->serial : 0,             \
              key_cred(tsk)->user->uid_keyring ?                        \
              key_cred(tsk)->user->uid_keyring->serial : 0,             \
              key_cred(tsk)->user->session_keyring ?                    \
              key_cred(tsk)->user->session_keyring->serial : 0,         \
              key_cred(tsk)->jit_keyring                                \
             );                                                         \
}
Definition at line 88 of file gss_keyring.c.
#define HAVE_REVERSE_CTX_NOKEY
Definition at line 1139 of file gss_keyring.c.
#define key_cred (tsk) ((tsk)->cred)
Definition at line 120 of file gss_keyring.c.
Referenced by request_key_unlink().
#define key_tgcred (tsk) key_cred(tsk)
Definition at line 124 of file gss_keyring.c.
Referenced by gss_kt_instantiate(), and request_key_unlink().
#define KEYRING_UPCALL_TIMEOUT (obd_timeout + obd_timeout)
Definition at line 82 of file gss_keyring.c.
Referenced by ctx_create_kr(), and gss_sec_lookup_ctx_kr().
#define RVS_CTX_EXPIRE_NICE (10)
Definition at line 560 of file gss_keyring.c.
Referenced by rvs_sec_install_root_ctx_kr().
Function Documentation
static void bind_key_ctx (struct key * key, struct ptlrpc_cli_ctx * ctx) [static]
Definition at line 391 of file gss_keyring.c.
References ptlrpc_cli_ctx::cc_refcount, ctx2gctx_keyring(), gss_cli_ctx_keyring::gck_key, key_get_payload(), key_set_payload(), and LASSERT.
Referenced by gss_sec_lookup_ctx_kr(), and rvs_sec_install_root_ctx_kr().
static void construct_key_desc (void * buf, int bufsize, struct ptlrpc_sec * sec, uid_t uid) [static]
Definition at line 599 of file gss_keyring.c.
References ptlrpc_sec::ps_id.
Referenced by flush_user_ctx_cache_kr(), and gss_sec_lookup_ctx_kr().
static void ctx_clear_timer_kr (struct ptlrpc_cli_ctx * ctx) [static]
Definition at line 182 of file gss_keyring.c.
References CDEBUG, ctx2gctx_keyring(), D_SEC, gss_cli_ctx_keyring::gck_key, gss_cli_ctx_keyring::gck_timer, and OBD_FREE_PTR.
Referenced by ctx_destroy_kr(), gss_kt_update(), and unbind_key_ctx().
static struct ptlrpc_cli_ctx* ctx_create_kr (struct ptlrpc_sec * sec, struct vfs_cred * vcred) [static, read]
Definition at line 200 of file gss_keyring.c.
References ptlrpc_cli_ctx::cc_expire, ptlrpc_cli_ctx::cc_flags, ptlrpc_cli_ctx::cc_refcount, cfs_time_current_sec(), gss_cli_ctx::gc_base, gss_cli_ctx_keyring::gck_base, gss_cli_ctx_keyring::gck_timer, gss_cli_ctx_init_common(), gss_keyring_ctxops, KEYRING_UPCALL_TIMEOUT, OBD_ALLOC_PTR, OBD_FREE_PTR, and PTLRPC_CTX_NEW_BIT.
Referenced by gss_sec_lookup_ctx_kr(), and sec_install_rctx_kr().
static void ctx_destroy_kr (struct ptlrpc_cli_ctx * ctx) [static]
Definition at line 232 of file gss_keyring.c.
References ptlrpc_cli_ctx::cc_flags, ptlrpc_cli_ctx::cc_sec, CDEBUG, ctx2gctx_keyring(), ctx_clear_timer_kr(), D_SEC, gss_cli_ctx_keyring::gck_key, gss_cli_ctx_keyring::gck_timer, gss_cli_ctx_fini_common(), LASSERT, OBD_FREE_PTR, ptlrpc_sec::ps_nctx, ptlrpc_sec::ps_refcount, PTLRPC_CTX_CACHED_BIT, and sptlrpc_sec_put().
Referenced by ctx_release_kr().
static void ctx_enlist_kr (struct ptlrpc_cli_ctx * ctx, int is_root, int locked) [static]
Definition at line 302 of file gss_keyring.c.
References ptlrpc_cli_ctx::cc_cache, ptlrpc_cli_ctx::cc_flags, ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_sec, gss_sec_keyring::gsk_clist, gss_sec_keyring::gsk_root_ctx, hlist_add_head(), LASSERT, ptlrpc_sec::ps_lock, PTLRPC_CTX_CACHED_BIT, sec2gsec_keyring(), spin_lock_if(), and spin_unlock_if().
Referenced by gss_sec_lookup_ctx_kr(), and rvs_sec_install_root_ctx_kr().
static void ctx_put_kr (struct ptlrpc_cli_ctx * ctx, int sync) [static]
Definition at line 268 of file gss_keyring.c.
References ptlrpc_cli_ctx::cc_refcount, ctx_release_kr(), and LASSERT.
Referenced by dispose_ctx_list_kr(), sec_install_rctx_kr(), and unbind_key_ctx().
static void ctx_release_kr (struct ptlrpc_cli_ctx * ctx, int sync) [static]
Definition at line 258 of file gss_keyring.c.
References ptlrpc_cli_ctx::cc_refcount, ctx_destroy_kr(), and sptlrpc_gc_add_ctx().
Referenced by ctx_put_kr(), and gss_sec_release_ctx_kr().
static void ctx_start_timer_kr (struct ptlrpc_cli_ctx * ctx, long timeout) [static]
Definition at line 159 of file gss_keyring.c.
References CDEBUG, cfs_time_current(), ctx2gctx_keyring(), ctx_upcall_timeout_kr(), D_SEC, gss_cli_ctx_keyring::gck_timer, and LASSERT.
Referenced by gss_sec_lookup_ctx_kr().
static int ctx_unlist_kr (struct ptlrpc_cli_ctx * ctx, int locked) [static]
Definition at line 328 of file gss_keyring.c.
References ptlrpc_cli_ctx::cc_cache, ptlrpc_cli_ctx::cc_flags, ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_sec, gss_sec_keyring::gsk_root_ctx, hlist_del_init(), ptlrpc_sec::ps_lock, PTLRPC_CTX_CACHED_BIT, sec2gsec_keyring(), spin_lock_if(), and spin_unlock_if().
Referenced by flush_spec_ctx_cache_kr(), gss_sec_gc_ctx_kr(), kill_ctx_kr(), and kill_key_locked().
static void ctx_upcall_timeout_kr (unsigned long data) [static]
Definition at line 146 of file gss_keyring.c.
References cli_ctx_expire(), ctx2gctx_keyring(), CWARN, gss_cli_ctx_keyring::gck_key, key_revoke_locked(), and LASSERT.
Referenced by ctx_start_timer_kr().
static void dispose_ctx_list_kr (struct hlist_head * freelist) [static]
Definition at line 483 of file gss_keyring.c.
References ptlrpc_cli_ctx::cc_cache, ptlrpc_cli_ctx::cc_sec, cfs_hlist_for_each_entry_safe, ctx2gctx(), ctx_put_kr(), gss_cli_ctx::gc_base, gss_cli_ctx::gc_seq, gss_cli_ctx::gc_svc_handle, gss_svc_upcall_update_sequence(), hlist_del_init(), hlist_node::next, rawobj_empty(), sec_is_reverse(), sptlrpc_cli_ctx_wakeup(), and unbind_ctx_kr().
Referenced by flush_spec_ctx_cache_kr(), and gss_sec_gc_ctx_kr().
static void flush_spec_ctx_cache_kr (struct ptlrpc_sec * sec, uid_t uid, int grace, int force) [static]
Definition at line 943 of file gss_keyring.c.
References ptlrpc_cli_ctx::cc_cache, ptlrpc_cli_ctx::cc_flags, ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_sec, ptlrpc_cli_ctx::cc_vcred, cfs_hlist_for_each_entry_safe, ctx_unlist_kr(), CWARN, dispose_ctx_list_kr(), ENTRY, EXIT, gss_sec_keyring::gsk_clist, hlist_add_head(), HLIST_HEAD_INIT, LASSERT, hlist_node::next, ptlrpc_sec::ps_lock, PTLRPC_CTX_DEAD_BIT, PTLRPC_CTX_UPTODATE_BIT, sec2gsec_keyring(), sec2target_str(), and vfs_cred::vc_uid.
Referenced by gss_sec_flush_ctx_cache_kr().
static void flush_user_ctx_cache_kr (struct ptlrpc_sec * sec, uid_t uid, int grace, int force) [static]
Definition at line 900 of file gss_keyring.c.
References CDEBUG, construct_key_desc(), D_SEC, gss_key_type, key_revoke_locked(), kill_key_locked(), request_key_unlink(), sec_is_reverse(), and sec_is_rootonly().
Referenced by gss_sec_flush_ctx_cache_kr().
static void gss_cli_ctx_die_kr (struct ptlrpc_cli_ctx * ctx, int grace) [static]
Definition at line 1122 of file gss_keyring.c.
References ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_sec, cli_ctx_expire(), kill_ctx_kr(), and LASSERT.
static int gss_cli_ctx_refresh_kr (struct ptlrpc_cli_ctx * ctx) [static]
Definition at line 1099 of file gss_keyring.c.
static int gss_cli_ctx_validate_kr (struct ptlrpc_cli_ctx * ctx) [static]
Definition at line 1106 of file gss_keyring.c.
References ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_sec, cli_ctx_check_death(), cli_ctx_is_ready(), kill_ctx_kr(), and LASSERT.
void __exit gss_exit_keyring (void)
Definition at line 1586 of file gss_keyring.c.
References sptlrpc_unregister_policy().
Referenced by sptlrpc_gss_exit(), and sptlrpc_gss_init().
int __init gss_init_keyring (void)
Definition at line 1567 of file gss_keyring.c.
References CERROR, and sptlrpc_register_policy().
Referenced by sptlrpc_gss_init().
static void gss_kt_describe (const struct key * key, struct seq_file * s) [static]
Definition at line 1488 of file gss_keyring.c.
static void gss_kt_destroy (struct key * key) [static]
Definition at line 1479 of file gss_keyring.c.
References CDEBUG, D_SEC, ENTRY, EXIT, key_get_payload(), and LASSERT.
static int gss_kt_instantiate (struct key * key, const void * data, size_t datalen) [static]
Definition at line 1279 of file gss_keyring.c.
References CDEBUG, CERROR, D_SEC, ENTRY, key_get_payload(), key_tgcred, LASSERT, RETURN, and unlikely.
static int gss_kt_match (const struct key * key, const void * desc) [static]
Definition at line 1452 of file gss_keyring.c.
static int gss_kt_update (struct key * key, const void * data, size_t datalen) [static]
Definition at line 1333 of file gss_keyring.c.
References buffer_extract_bytes(), ptlrpc_cli_ctx::cc_flags, ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_sec, CDEBUG, CERROR, cli_ctx_expire(), cli_ctx_is_refreshed(), ctx2gctx(), ctx_clear_timer_kr(), CWARN, D_SEC, ENTRY, gss_cli_ctx::gc_handle, gss_cli_ctx::gc_mechctx, gss_cli_ctx::gc_win, gss_sec::gs_mech, gss_cli_ctx_uptodate(), GSS_S_COMPLETE, key_get_payload(), kill_key_locked(), LASSERT, lgss_import_sec_context(), PTLRPC_CTX_ERROR_BIT, RAWOBJ_EMPTY, rawobj_extract_local(), rawobj_extract_local_alloc(), RETURN, sec2gsec(), sptlrpc_cli_ctx_get(), and sptlrpc_cli_ctx_put().
static struct ptlrpc_sec* gss_sec_create_kr (struct obd_import * imp, struct ptlrpc_svc_ctx * svcctx, struct sptlrpc_flavor * sf) [static, read]
Definition at line 611 of file gss_keyring.c.
References ENTRY, gss_sec::gs_base, gss_sec_keyring::gsk_base, gss_sec_keyring::gsk_clist, gss_sec_keyring::gsk_root_ctx, gss_sec_keyring::gsk_root_uc_lock, gss_sec_keyring::gsk_uc_lock, gss_policy_keyring, gss_sec_create_common(), gss_sec_destroy_common(), INIT_HLIST_HEAD, OBD_ALLOC, OBD_FREE, RETURN, and sec_install_rctx_kr().
static void gss_sec_destroy_kr (struct ptlrpc_sec * sec) [static]
Definition at line 647 of file gss_keyring.c.
References CDEBUG, D_SEC, gss_sec_keyring::gsk_clist, gss_sec_keyring::gsk_root_ctx, gss_sec_destroy_common(), hlist_empty(), LASSERT, OBD_FREE, ptlrpc_sec::ps_policy, sec2gsec(), sec2gsec_keyring(), and ptlrpc_sec_policy::sp_name.
static int gss_sec_display_kr (struct ptlrpc_sec * sec, struct seq_file * seq) [static]
Definition at line 1045 of file gss_keyring.c.
References ptlrpc_cli_ctx::cc_expire, ptlrpc_cli_ctx::cc_flags, ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_vcred, cfs_hlist_for_each_entry_safe, cfs_time_current_sec(), ctx2gctx(), ctx2gctx_keyring(), ENTRY, gss_cli_ctx::gc_handle, gss_cli_ctx::gc_mechctx, gss_cli_ctx::gc_seq, gss_cli_ctx::gc_svc_handle, gss_cli_ctx::gc_win, gss_cli_ctx_keyring::gck_key, gss_sec_keyring::gsk_clist, gss_cli_ctx_flags2str(), gss_handle_to_u64(), lgss_display(), LPX64, hlist_node::next, now(), ptlrpc_sec::ps_lock, RETURN, sec2gsec_keyring(), and vfs_cred::vc_uid.
static int gss_sec_flush_ctx_cache_kr (struct ptlrpc_sec * sec, uid_t uid, int grace, int force) [static]
Definition at line 993 of file gss_keyring.c.
References CDEBUG, D_SEC, ENTRY, flush_spec_ctx_cache_kr(), flush_user_ctx_cache_kr(), ptlrpc_sec::ps_nctx, ptlrpc_sec::ps_refcount, and RETURN.
static void gss_sec_gc_ctx_kr (struct ptlrpc_sec * sec) [static]
Definition at line 1012 of file gss_keyring.c.
References ptlrpc_cli_ctx::cc_cache, ptlrpc_cli_ctx::cc_refcount, cfs_hlist_for_each_entry_safe, cli_ctx_check_death(), ctx_unlist_kr(), CWARN, dispose_ctx_list_kr(), ENTRY, EXIT, gss_sec_keyring::gsk_clist, hlist_add_head(), HLIST_HEAD_INIT, LASSERT, hlist_node::next, ptlrpc_sec::ps_lock, and sec2gsec_keyring().
static struct ptlrpc_cli_ctx* gss_sec_lookup_ctx_kr (struct ptlrpc_sec * sec, struct vfs_cred * vcred, int create, int remove_dead) [static, read]
Definition at line 717 of file gss_keyring.c.
References bind_key_ctx(), ptlrpc_connection::c_peer, ptlrpc_connection::c_self, ptlrpc_cli_ctx::cc_refcount, CDEBUG, CERROR, construct_key_desc(), ctx2gctx_keyring(), ctx_create_kr(), ctx_enlist_kr(), ctx_start_timer_kr(), D_SEC, ENTRY, GOTO, gss_sec::gs_rvs_hdl, gss_sec_keyring::gsk_root_uc_lock, gss_get_next_ctx_index(), gss_key_type, obd_import::imp_connection, obd_import::imp_obd, import_to_gss_svc(), key_get_payload(), key_revoke_locked(), keyring_upcall_lock(), KEYRING_UPCALL_TIMEOUT, keyring_upcall_unlock(), LASSERT, LBUG, likely, LPX64, LUSTRE_LWP_NAME, LUSTRE_MDC_NAME, LUSTRE_MGC_NAME, LUSTRE_OSC_NAME, LUSTRE_OSP_NAME, LUSTRE_SP_CLI, LUSTRE_SP_MDT, LUSTRE_SP_MGC, LUSTRE_SP_MGS, LUSTRE_SP_OST, lnet_process_id_t::nid, OBD_ALLOC, OBD_FREE, obd_device::obd_name, obd_device::obd_type, ptlrpc_sec::ps_id, ptlrpc_sec::ps_import, ptlrpc_sec::ps_part, request_key_unlink(), RETURN, sec2gsec(), sec2gsec_keyring(), sec_is_reverse(), sec_lookup_root_ctx_kr(), obd_type::typ_name, user_is_root(), vfs_cred::vc_gid, and vfs_cred::vc_uid.
static void gss_sec_release_ctx_kr (struct ptlrpc_sec * sec, struct ptlrpc_cli_ctx * ctx, int sync) [static]
Definition at line 883 of file gss_keyring.c.
References ptlrpc_cli_ctx::cc_refcount, ctx_release_kr(), LASSERT, and ptlrpc_sec::ps_refcount.
static int gss_svc_accept_kr (struct ptlrpc_request * req) [static]
Definition at line 1247 of file gss_keyring.c.
References gss_policy_keyring, and gss_svc_accept().
static int gss_svc_install_rctx_kr (struct obd_import * imp, struct ptlrpc_svc_ctx * svc_ctx) [static]
Definition at line 1253 of file gss_keyring.c.
References LASSERT, sec_install_rctx_kr(), sptlrpc_import_sec_ref(), and sptlrpc_sec_put().
static void* key_get_payload (struct key * key, unsigned int index) [static]
Definition at line 354 of file gss_keyring.c.
Referenced by bind_key_ctx(), gss_kt_destroy(), gss_kt_instantiate(), gss_kt_update(), gss_sec_lookup_ctx_kr(), kill_key_locked(), unbind_ctx_kr(), unbind_key_ctx(), and unbind_key_locked().
static void key_revoke_locked (struct key * key) [inline, static]
Definition at line 141 of file gss_keyring.c.
Referenced by ctx_upcall_timeout_kr(), flush_user_ctx_cache_kr(), gss_sec_lookup_ctx_kr(), and unbind_key_ctx().
static int key_set_payload (struct key * key, unsigned int index, struct ptlrpc_cli_ctx * ctx) [static]
Definition at line 370 of file gss_keyring.c.
Referenced by bind_key_ctx(), and unbind_key_ctx().
static void keyring_upcall_lock (struct gss_sec_keyring * gsec_kr) [inline, static]
Definition at line 127 of file gss_keyring.c.
References gss_sec_keyring::gsk_uc_lock.
Referenced by gss_sec_lookup_ctx_kr().
static void keyring_upcall_unlock (struct gss_sec_keyring * gsec_kr) [inline, static]
Definition at line 134 of file gss_keyring.c.
References gss_sec_keyring::gsk_uc_lock.
Referenced by gss_sec_lookup_ctx_kr().
static void kill_ctx_kr (struct ptlrpc_cli_ctx * ctx) [static]
Definition at line 462 of file gss_keyring.c.
References ctx_unlist_kr(), and unbind_ctx_kr().
Referenced by gss_cli_ctx_die_kr(), and gss_cli_ctx_validate_kr().
static void kill_key_locked (struct key * key) [static]
Definition at line 472 of file gss_keyring.c.
References ctx_unlist_kr(), key_get_payload(), and unbind_key_locked().
Referenced by flush_user_ctx_cache_kr(), and gss_kt_update().
static void request_key_unlink (struct key * key) [static]
Definition at line 678 of file gss_keyring.c.
References key_cred, key_tgcred, LASSERT, and LBUG.
Referenced by flush_user_ctx_cache_kr(), and gss_sec_lookup_ctx_kr().
static void rvs_sec_install_root_ctx_kr (struct ptlrpc_sec * sec, struct ptlrpc_cli_ctx * new_ctx, struct key * key) [static]
Definition at line 563 of file gss_keyring.c.
References bind_key_ctx(), ptlrpc_cli_ctx::cc_cache, ptlrpc_cli_ctx::cc_early_expire, ptlrpc_cli_ctx::cc_expire, cfs_hlist_for_each_entry, cfs_time_current_sec(), ctx_enlist_kr(), ENTRY, gss_sec_keyring::gsk_clist, gss_sec_keyring::gsk_root_ctx, LASSERT, now(), ptlrpc_sec::ps_lock, RVS_CTX_EXPIRE_NICE, sec2gsec_keyring(), and sec_is_reverse().
Referenced by sec_install_rctx_kr().
static int sec_install_rctx_kr (struct ptlrpc_sec * sec, struct ptlrpc_svc_ctx * svc_ctx) [static]
Definition at line 1144 of file gss_keyring.c.
References CERROR, ctx_create_kr(), ctx_put_kr(), gss_copy_rvc_cli_ctx(), LASSERT, and rvs_sec_install_root_ctx_kr().
Referenced by gss_sec_create_kr(), and gss_svc_install_rctx_kr().
static struct ptlrpc_cli_ctx* sec_lookup_root_ctx_kr (struct ptlrpc_sec * sec) [static, read]
Definition at line 522 of file gss_keyring.c.
References ptlrpc_cli_ctx::cc_cache, ptlrpc_cli_ctx::cc_expire, ptlrpc_cli_ctx::cc_refcount, cfs_hlist_for_each_entry, gss_sec_keyring::gsk_clist, gss_sec_keyring::gsk_root_ctx, hlist_empty(), LASSERT, ptlrpc_sec::ps_lock, sec2gsec_keyring(), sec_is_reverse(), and unlikely.
Referenced by gss_sec_lookup_ctx_kr().
static void spin_lock_if (spinlock_t * lock, int condition) [inline, static]
Definition at line 290 of file gss_keyring.c.
Referenced by ctx_enlist_kr(), and ctx_unlist_kr().
static void spin_unlock_if (spinlock_t * lock, int condition) [inline, static]
Definition at line 296 of file gss_keyring.c.
Referenced by ctx_enlist_kr(), and ctx_unlist_kr().
static void unbind_ctx_kr (struct ptlrpc_cli_ctx * ctx) [static]
Definition at line 432 of file gss_keyring.c.
References ctx2gctx_keyring(), gss_cli_ctx_keyring::gck_key, key_get_payload(), LASSERT, and unbind_key_ctx().
Referenced by dispose_ctx_list_kr(), and kill_ctx_kr().
static void unbind_key_ctx (struct key * key, struct ptlrpc_cli_ctx * ctx) [static]
Definition at line 409 of file gss_keyring.c.
References ptlrpc_cli_ctx::cc_flags, ctx2gctx_keyring(), ctx_clear_timer_kr(), ctx_put_kr(), gss_cli_ctx_keyring::gck_key, key_get_payload(), key_revoke_locked(), key_set_payload(), LASSERT, and PTLRPC_CTX_CACHED_BIT.
Referenced by unbind_ctx_kr(), and unbind_key_locked().
static void unbind_key_locked (struct key * key) [static]
Definition at line 451 of file gss_keyring.c.
References key_get_payload(), and unbind_key_ctx().
Referenced by kill_key_locked().
static int user_is_root (struct ptlrpc_sec * sec, struct vfs_cred * vcred) [inline, static]
Definition at line 662 of file gss_keyring.c.
References sec_is_rootonly(), and vfs_cred::vc_uid.
Referenced by gss_sec_lookup_ctx_kr().
Variable Documentation
static struct key_type gss_key_type [static, read]
Initial value:
{
        .name           = "lgssc",
        .def_datalen    = 0,
        .instantiate    = gss_kt_instantiate,
        .update         = gss_kt_update,
        .match          = gss_kt_match,
        .destroy        = gss_kt_destroy,
        .describe       = gss_kt_describe,
}
Definition at line 68 of file gss_keyring.c.
Referenced by flush_user_ctx_cache_kr(), and gss_sec_lookup_ctx_kr().
static struct ptlrpc_ctx_ops gss_keyring_ctxops [static, read]
Initial value:
 {
        .match                  = gss_cli_ctx_match,
        .refresh                = gss_cli_ctx_refresh_kr,
        .validate               = gss_cli_ctx_validate_kr,
        .die                    = gss_cli_ctx_die_kr,
        .sign                   = gss_cli_ctx_sign,
        .verify                 = gss_cli_ctx_verify,
        .seal                   = gss_cli_ctx_seal,
        .unseal                 = gss_cli_ctx_unseal,
        .wrap_bulk              = gss_cli_ctx_wrap_bulk,
        .unwrap_bulk            = gss_cli_ctx_unwrap_bulk,
}
Definition at line 67 of file gss_keyring.c.
Referenced by ctx_create_kr().
static struct ptlrpc_sec_policy gss_policy_keyring [static, read]
Initial value:
 {
        .sp_owner               = THIS_MODULE,
        .sp_name                = "gss.keyring",
        .sp_policy              = SPTLRPC_POLICY_GSS,
        .sp_cops                = &gss_sec_keyring_cops,
        .sp_sops                = &gss_sec_keyring_sops,
}
Definition at line 66 of file gss_keyring.c.
Referenced by gss_sec_create_kr(), and gss_svc_accept_kr().
struct ptlrpc_sec_cops gss_sec_keyring_cops [static]
Initial value:
 {
        .create_sec             = gss_sec_create_kr,
        .destroy_sec            = gss_sec_destroy_kr,
        .kill_sec               = gss_sec_kill,
        .lookup_ctx             = gss_sec_lookup_ctx_kr,
        .release_ctx            = gss_sec_release_ctx_kr,
        .flush_ctx_cache        = gss_sec_flush_ctx_cache_kr,
        .gc_ctx                 = gss_sec_gc_ctx_kr,
        .install_rctx           = gss_sec_install_rctx,
        .alloc_reqbuf           = gss_alloc_reqbuf,
        .free_reqbuf            = gss_free_reqbuf,
        .alloc_repbuf           = gss_alloc_repbuf,
        .free_repbuf            = gss_free_repbuf,
        .enlarge_reqbuf         = gss_enlarge_reqbuf,
        .display                = gss_sec_display_kr,
}
Definition at line 1528 of file gss_keyring.c.
struct ptlrpc_sec_sops gss_sec_keyring_sops [static]
Initial value:
 {
        .accept                 = gss_svc_accept_kr,
        .invalidate_ctx         = gss_svc_invalidate_ctx,
        .alloc_rs               = gss_svc_alloc_rs,
        .authorize              = gss_svc_authorize,
        .free_rs                = gss_svc_free_rs,
        .free_ctx               = gss_svc_free_ctx,
        .prep_bulk              = gss_svc_prep_bulk,
        .unwrap_bulk            = gss_svc_unwrap_bulk,
        .wrap_bulk              = gss_svc_wrap_bulk,
        .install_rctx           = gss_svc_install_rctx_kr,
}
Definition at line 1545 of file gss_keyring.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.