Lustre: lustre/ptlrpc/gss/gss_internal.h File Reference
lustre/ptlrpc/gss/gss_internal.h File Reference
#include <lustre_sec.h>
Data Structures
struct netobj_s
struct rawobj_s
struct rawobj_buf_s
struct gss_header
struct gss_rep_header
struct gss_err_header
struct gss_wire_ctx
struct gss_svc_seq_data
struct gss_svc_ctx
struct gss_svc_reqctx
struct gss_cli_ctx
struct gss_cli_ctx_keyring
struct gss_sec
struct gss_sec_pipefs
struct gss_sec_keyring
Defines
#define NETOBJ_EMPTY ((netobj_t) { 0 })
#define RAWOBJ_EMPTY ((rawobj_t) { 0, NULL })
#define __TIMEOUT_DELTA (10)
#define GSS_SECINIT_RPC_TIMEOUT
#define GSS_SECFINI_RPC_TIMEOUT (__TIMEOUT_DELTA)
#define GSS_SECSVC_UPCALL_TIMEOUT (GSS_SECINIT_RPC_TIMEOUT)
#define GSS_GC_INTERVAL (60 * 60)
#define GSS_MAX_CIPHER_BLOCK (16)
#define GSSD_INTERFACE_VERSION (1)
#define PTLRPC_GSS_VERSION (1)
#define PTLRPC_GSS_MAX_HANDLE_SIZE (8)
#define PTLRPC_GSS_HEADER_SIZE
#define GSS_SEQ_WIN (2048)
#define GSS_SEQ_WIN_MAIN GSS_SEQ_WIN
#define GSS_SEQ_WIN_BACK (128)
#define GSS_SEQ_REPACK_THRESHOLD
#define HAVE_KEYRING_UPCALL_SERIALIZED 1
#define GSS_CTX_INIT_MAX_LEN (1024)
#define GSS_PRIVBUF_PREFIX_LEN (32)
#define GSS_PRIVBUF_SUFFIX_LEN (32)
Typedefs
typedef struct netobj_s netobj_t
typedef struct rawobj_s rawobj_t
typedef struct rawobj_buf_s rawobj_buf_t
Enumerations
enum ptlrpc_gss_proc {
PTLRPC_GSS_PROC_DATA = 0, PTLRPC_GSS_PROC_INIT = 1, PTLRPC_GSS_PROC_CONTINUE_INIT = 2, PTLRPC_GSS_PROC_DESTROY = 3,
PTLRPC_GSS_PROC_ERR = 4
}
enum ptlrpc_gss_tgt { LUSTRE_GSS_TGT_MGS = 0, LUSTRE_GSS_TGT_MDS = 1, LUSTRE_GSS_TGT_OSS = 2 }
enum ptlrpc_gss_header_flags { LUSTRE_GSS_PACK_BULK = 1, LUSTRE_GSS_PACK_USER = 2 }
Functions
int rawobj_empty (rawobj_t *obj)
int rawobj_alloc (rawobj_t *obj, char *buf, int len)
void rawobj_free (rawobj_t *obj)
int rawobj_equal (rawobj_t *a, rawobj_t *b)
int rawobj_dup (rawobj_t *dest, rawobj_t *src)
int rawobj_serialize (rawobj_t *obj, __u32 **buf, __u32 *buflen)
int rawobj_extract (rawobj_t *obj, __u32 **buf, __u32 *buflen)
int rawobj_extract_alloc (rawobj_t *obj, __u32 **buf, __u32 *buflen)
int rawobj_extract_local (rawobj_t *obj, __u32 **buf, __u32 *buflen)
int rawobj_extract_local_alloc (rawobj_t *obj, __u32 **buf, __u32 *buflen)
int rawobj_from_netobj (rawobj_t *rawobj, netobj_t *netobj)
int rawobj_from_netobj_alloc (rawobj_t *obj, netobj_t *netobj)
int buffer_extract_bytes (const void **buf, __u32 *buflen, void *res, __u32 reslen)
static unsigned long gss_round_ctx_expiry (unsigned long expiry, unsigned long sec_flags)
static __u32 import_to_gss_svc (struct obd_import *imp)
static __u64 gss_handle_to_u64 (rawobj_t *handle)
static struct gss_cli_ctx * ctx2gctx (struct ptlrpc_cli_ctx *ctx)
static struct gss_cli_ctx_keyring * ctx2gctx_keyring (struct ptlrpc_cli_ctx *ctx)
static struct gss_sec * sec2gsec (struct ptlrpc_sec *sec)
static struct gss_sec_pipefs * sec2gsec_pipefs (struct ptlrpc_sec *sec)
static struct gss_sec_keyring * sec2gsec_keyring (struct ptlrpc_sec *sec)
static struct gss_svc_reqctx * gss_svc_ctx2reqctx (struct ptlrpc_svc_ctx *ctx)
static struct gss_svc_ctx * gss_svc_ctx2gssctx (struct ptlrpc_svc_ctx *ctx)
int gss_cli_ctx_match (struct ptlrpc_cli_ctx *ctx, struct vfs_cred *vcred)
int gss_cli_ctx_display (struct ptlrpc_cli_ctx *ctx, char *buf, int bufsize)
int gss_cli_ctx_sign (struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req)
int gss_cli_ctx_verify (struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req)
int gss_cli_ctx_seal (struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req)
int gss_cli_ctx_unseal (struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req)
int gss_sec_install_rctx (struct obd_import *imp, struct ptlrpc_sec *sec, struct ptlrpc_cli_ctx *ctx)
int gss_alloc_reqbuf (struct ptlrpc_sec *sec, struct ptlrpc_request *req, int msgsize)
void gss_free_reqbuf (struct ptlrpc_sec *sec, struct ptlrpc_request *req)
int gss_alloc_repbuf (struct ptlrpc_sec *sec, struct ptlrpc_request *req, int msgsize)
void gss_free_repbuf (struct ptlrpc_sec *sec, struct ptlrpc_request *req)
int gss_enlarge_reqbuf (struct ptlrpc_sec *sec, struct ptlrpc_request *req, int segment, int newsize)
int gss_svc_accept (struct ptlrpc_sec_policy *policy, struct ptlrpc_request *req)
void gss_svc_invalidate_ctx (struct ptlrpc_svc_ctx *svc_ctx)
int gss_svc_alloc_rs (struct ptlrpc_request *req, int msglen)
int gss_svc_authorize (struct ptlrpc_request *req)
void gss_svc_free_rs (struct ptlrpc_reply_state *rs)
void gss_svc_free_ctx (struct ptlrpc_svc_ctx *ctx)
int cli_ctx_expire (struct ptlrpc_cli_ctx *ctx)
int cli_ctx_check_death (struct ptlrpc_cli_ctx *ctx)
int gss_copy_rvc_cli_ctx (struct ptlrpc_cli_ctx *cli_ctx, struct ptlrpc_svc_ctx *svc_ctx)
struct gss_header * gss_swab_header (struct lustre_msg *msg, int segment, int swabbed)
netobj_t * gss_swab_netobj (struct lustre_msg *msg, int segment)
void gss_cli_ctx_uptodate (struct gss_cli_ctx *gctx)
int gss_pack_err_notify (struct ptlrpc_request *req, __u32 major, __u32 minor)
int gss_check_seq_num (struct gss_svc_seq_data *sd, __u32 seq_num, int set)
int gss_sec_create_common (struct gss_sec *gsec, struct ptlrpc_sec_policy *policy, struct obd_import *imp, struct ptlrpc_svc_ctx *ctx, struct sptlrpc_flavor *sf)
void gss_sec_destroy_common (struct gss_sec *gsec)
void gss_sec_kill (struct ptlrpc_sec *sec)
int gss_cli_ctx_init_common (struct ptlrpc_sec *sec, struct ptlrpc_cli_ctx *ctx, struct ptlrpc_ctx_ops *ctxops, struct vfs_cred *vcred)
int gss_cli_ctx_fini_common (struct ptlrpc_sec *sec, struct ptlrpc_cli_ctx *ctx)
void gss_cli_ctx_flags2str (unsigned long flags, char *buf, int bufsize)
static int __init gss_init_keyring (void)
static void __exit gss_exit_keyring (void)
static int __init gss_init_pipefs (void)
static void __exit gss_exit_pipefs (void)
int gss_cli_prep_bulk (struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
int gss_cli_ctx_wrap_bulk (struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
int gss_cli_ctx_unwrap_bulk (struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
int gss_svc_prep_bulk (struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
int gss_svc_unwrap_bulk (struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
int gss_svc_wrap_bulk (struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
int g_token_size (rawobj_t *mech, unsigned int body_size)
void g_make_token_header (rawobj_t *mech, int body_size, unsigned char **buf)
__u32 g_verify_token_header (rawobj_t *mech, int *body_size, unsigned char **buf_in, int toksize)
int gss_do_ctx_init_rpc (char __user *buffer, unsigned long count)
int gss_do_ctx_fini_rpc (struct gss_cli_ctx *gctx)
int __init gss_init_cli_upcall (void)
void gss_exit_cli_upcall (void)
__u64 gss_get_next_ctx_index (void)
int gss_svc_upcall_install_rvs_ctx (struct obd_import *imp, struct gss_sec *gsec, struct gss_cli_ctx *gctx)
int gss_svc_upcall_expire_rvs_ctx (rawobj_t *handle)
int gss_svc_upcall_dup_handle (rawobj_t *handle, struct gss_svc_ctx *ctx)
int gss_svc_upcall_update_sequence (rawobj_t *handle, __u32 seq)
int gss_svc_upcall_handle_init (struct ptlrpc_request *req, struct gss_svc_reqctx *grctx, struct gss_wire_ctx *gw, struct obd_device *target, __u32 lustre_svc, rawobj_t *rvs_hdl, rawobj_t *in_token)
struct gss_svc_ctx * gss_svc_upcall_get_ctx (struct ptlrpc_request *req, struct gss_wire_ctx *gw)
void gss_svc_upcall_put_ctx (struct gss_svc_ctx *ctx)
void gss_svc_upcall_destroy_ctx (struct gss_svc_ctx *ctx)
int __init gss_init_svc_upcall (void)
void gss_exit_svc_upcall (void)
void gss_stat_oos_record_cli (int behind)
void gss_stat_oos_record_svc (int phase, int replay)
int __init gss_init_lproc (void)
void gss_exit_lproc (void)
int __init init_null_module (void)
void cleanup_null_module (void)
int __init init_kerberos_module (void)
void cleanup_kerberos_module (void)
int __init init_sk_module (void)
void cleanup_sk_module (void)
static void __dbg_memdump (char *name, void *ptr, int size)
Define Documentation
#define __TIMEOUT_DELTA (10)
Definition at line 60 of file gss_internal.h.
Referenced by gss_round_ctx_expiry().
#define GSS_CTX_INIT_MAX_LEN (1024)
Definition at line 350 of file gss_internal.h.
Referenced by gss_alloc_repbuf_intg(), and gss_alloc_reqbuf_intg().
#define GSS_GC_INTERVAL (60 * 60)
Definition at line 72 of file gss_internal.h.
Referenced by gss_sec_create_common().
#define GSS_MAX_CIPHER_BLOCK (16)
Definition at line 90 of file gss_internal.h.
Referenced by gss_alloc_repbuf_priv(), gss_alloc_reqbuf_priv(), gss_enlarge_reqbuf_priv(), gss_svc_alloc_rs(), gss_wrap_bulk_kerberos(), and gss_wrap_kerberos().
#define GSS_PRIVBUF_PREFIX_LEN (32)
Definition at line 356 of file gss_internal.h.
#define GSS_PRIVBUF_SUFFIX_LEN (32)
Definition at line 357 of file gss_internal.h.
#define GSS_SECFINI_RPC_TIMEOUT (__TIMEOUT_DELTA)
Definition at line 66 of file gss_internal.h.
#define GSS_SECINIT_RPC_TIMEOUT
Value:
(obd_timeout < __TIMEOUT_DELTA ?                                \
         __TIMEOUT_DELTA : obd_timeout - __TIMEOUT_DELTA)
Definition at line 62 of file gss_internal.h.
#define GSS_SECSVC_UPCALL_TIMEOUT (GSS_SECINIT_RPC_TIMEOUT)
Definition at line 67 of file gss_internal.h.
#define GSS_SEQ_REPACK_THRESHOLD
Value:
(GSS_SEQ_WIN_MAIN / 2 + \
                                         GSS_SEQ_WIN_MAIN / 4)
Definition at line 208 of file gss_internal.h.
Referenced by gss_cli_ctx_seal(), and gss_cli_ctx_sign().
#define GSS_SEQ_WIN (2048)
Definition at line 205 of file gss_internal.h.
Referenced by gss_copy_rvc_cli_ctx(), and gss_svc_upcall_handle_init().
#define GSS_SEQ_WIN_BACK (128)
Definition at line 207 of file gss_internal.h.
Referenced by gss_check_seq_num(), and gss_proc_oos_seq_show().
#define GSS_SEQ_WIN_MAIN GSS_SEQ_WIN
Definition at line 206 of file gss_internal.h.
Referenced by gss_check_seq_num(), and gss_proc_oos_seq_show().
#define GSSD_INTERFACE_VERSION (1)
Definition at line 95 of file gss_internal.h.
Referenced by do_nego_rpc(), do_negotiation(), and gss_do_ctx_init_rpc().
#define HAVE_KEYRING_UPCALL_SERIALIZED 1
Definition at line 299 of file gss_internal.h.
#define NETOBJ_EMPTY ((netobj_t) { 0 })
Definition at line 24 of file gss_internal.h.
#define PTLRPC_GSS_HEADER_SIZE
Value:
(sizeof(struct gss_header) + \
                                         PTLRPC_GSS_MAX_HANDLE_SIZE)
Definition at line 194 of file gss_internal.h.
Referenced by gss_alloc_repbuf_intg(), gss_alloc_repbuf_priv(), gss_alloc_reqbuf_intg(), gss_alloc_reqbuf_priv(), gss_cli_ctx_seal(), gss_enlarge_reqbuf_priv(), gss_init_at_reply_offset(), gss_svc_alloc_rs(), and gss_svc_seal().
#define PTLRPC_GSS_MAX_HANDLE_SIZE (8)
Definition at line 193 of file gss_internal.h.
Referenced by gss_handle_to_u64(), and gss_svc_upcall_handle_init().
#define PTLRPC_GSS_VERSION (1)
Definition at line 97 of file gss_internal.h.
Referenced by ctx_init_pack_request(), ctx_init_parse_reply(), gss_cli_ctx_seal(), gss_cli_ctx_unseal(), gss_pack_err_notify(), gss_sign_msg(), gss_svc_accept(), gss_svc_seal(), and gss_svc_upcall_handle_init().
#define RAWOBJ_EMPTY ((rawobj_t) { 0, NULL })
Definition at line 31 of file gss_internal.h.
Referenced by __rsc_init(), __rsc_update(), __rsi_init(), __rsi_update(), gss_get_mic_kerberos(), gss_kt_update(), gss_unwrap_bulk_kerberos(), gss_unwrap_kerberos(), gss_verify_mic_kerberos(), gss_wrap_bulk_kerberos(), and gss_wrap_kerberos().
Typedef Documentation
typedef struct netobj_s netobj_t
typedef struct rawobj_buf_s rawobj_buf_t
typedef struct rawobj_s rawobj_t
Enumeration Type Documentation
enum ptlrpc_gss_header_flags
Enumerator:
LUSTRE_GSS_PACK_BULK
LUSTRE_GSS_PACK_USER
Definition at line 114 of file gss_internal.h.
enum ptlrpc_gss_proc
Enumerator:
PTLRPC_GSS_PROC_DATA
PTLRPC_GSS_PROC_INIT
PTLRPC_GSS_PROC_CONTINUE_INIT
PTLRPC_GSS_PROC_DESTROY
PTLRPC_GSS_PROC_ERR
Definition at line 100 of file gss_internal.h.
enum ptlrpc_gss_tgt
Enumerator:
LUSTRE_GSS_TGT_MGS
LUSTRE_GSS_TGT_MDS
LUSTRE_GSS_TGT_OSS
Definition at line 108 of file gss_internal.h.
Function Documentation
static void __dbg_memdump (char * name, void * ptr, int size) [inline, static]
Definition at line 523 of file gss_internal.h.
References buf, bufsize, CDEBUG, D_ERROR, LCONSOLE_INFO, OBD_ALLOC, and OBD_FREE.
int buffer_extract_bytes (const void ** buf, __u32 * buflen, void * res, __u32 reslen)
Definition at line 230 of file gss_rawobj.c.
References CERROR.
Referenced by gss_kt_update().
void cleanup_kerberos_module (void)
Definition at line 1972 of file gss_krb5_mech.c.
References lgss_mech_unregister().
Referenced by sptlrpc_gss_exit(), and sptlrpc_gss_init().
void cleanup_null_module (void)
Definition at line 195 of file gss_null_mech.c.
References lgss_mech_unregister().
Referenced by sptlrpc_gss_init().
void cleanup_sk_module (void)
Definition at line 226 of file gss_sk_mech.c.
References lgss_mech_unregister().
Referenced by sptlrpc_gss_init().
int cli_ctx_check_death (struct ptlrpc_cli_ctx * ctx)
Definition at line 351 of file sec_gss.c.
References ptlrpc_cli_ctx::cc_expire, cfs_time_after(), cfs_time_current_sec(), cli_ctx_expire(), cli_ctx_is_dead(), and unlikely.
Referenced by ctx_check_death_pf(), gss_cli_ctx_validate_kr(), and gss_sec_gc_ctx_kr().
int cli_ctx_expire (struct ptlrpc_cli_ctx * ctx)
Definition at line 327 of file sec_gss.c.
References ptlrpc_cli_ctx::cc_early_expire, ptlrpc_cli_ctx::cc_expire, ptlrpc_cli_ctx::cc_flags, ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_sec, ptlrpc_cli_ctx::cc_vcred, cfs_time_current_sec(), cfs_time_sub(), CWARN, LASSERT, PTLRPC_CTX_DEAD_BIT, PTLRPC_CTX_UPTODATE_BIT, sec2target_str(), sptlrpc_cli_ctx_wakeup(), and vfs_cred::vc_uid.
Referenced by cli_ctx_check_death(), ctx_upcall_timeout_kr(), gss_cli_ctx_die_kr(), gss_cli_ctx_die_pf(), gss_kt_update(), and gss_sec_ctx_replace_pf().
static struct gss_cli_ctx* ctx2gctx (struct ptlrpc_cli_ctx * ctx) [static, read]
Definition at line 322 of file gss_internal.h.
References gss_cli_ctx::gc_base.
Referenced by ctx2gctx_keyring(), ctx_destroy_pf(), dispose_ctx_list_kr(), gss_cli_ctx_fini_common(), gss_cli_ctx_handle_err_notify(), gss_cli_ctx_init_common(), gss_cli_ctx_sign(), gss_cli_prep_bulk(), gss_copy_rvc_cli_ctx(), gss_kt_update(), and gss_sec_display_kr().
static struct gss_cli_ctx_keyring* ctx2gctx_keyring (struct ptlrpc_cli_ctx * ctx) [static, read]
Definition at line 328 of file gss_internal.h.
References ctx2gctx(), and gss_cli_ctx_keyring::gck_base.
Referenced by bind_key_ctx(), ctx_clear_timer_kr(), ctx_destroy_kr(), ctx_start_timer_kr(), ctx_upcall_timeout_kr(), gss_sec_display_kr(), gss_sec_lookup_ctx_kr(), unbind_ctx_kr(), and unbind_key_ctx().
void g_make_token_header (rawobj_t * mech, int body_size, unsigned char ** buf)
Definition at line 178 of file gss_generic_token.c.
References rawobj_s::data, der_write_length(), rawobj_s::len, and TWRITE_STR.
int g_token_size (rawobj_t * mech, unsigned int body_size)
Definition at line 167 of file gss_generic_token.c.
References der_length_size(), and rawobj_s::len.
__u32 g_verify_token_header (rawobj_t * mech, int * body_size, unsigned char ** buf_in, int toksize)
Definition at line 195 of file gss_generic_token.c.
References buf, rawobj_s::data, der_read_length(), G_BAD_TOK_HEADER, g_OID_equal, G_WRONG_MECH, rawobj_s::len, and ret.
int gss_alloc_repbuf (struct ptlrpc_sec * sec, struct ptlrpc_request * req, int msgsize)
Definition at line 1573 of file sec_gss.c.
References ENTRY, gss_alloc_repbuf_intg(), gss_alloc_repbuf_priv(), LASSERT, LASSERTF, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pack_bulk, sptlrpc_flavor::sf_rpc, SPTLRPC_FLVR_SVC, SPTLRPC_SVC_AUTH, SPTLRPC_SVC_INTG, SPTLRPC_SVC_NULL, and SPTLRPC_SVC_PRIV.
int gss_alloc_reqbuf (struct ptlrpc_sec * sec, struct ptlrpc_request * req, int msgsize)
Definition at line 1416 of file sec_gss.c.
References gss_alloc_reqbuf_intg(), gss_alloc_reqbuf_priv(), LASSERT, LASSERTF, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pack_bulk, sptlrpc_flavor::sf_rpc, SPTLRPC_FLVR_SVC, SPTLRPC_SVC_AUTH, SPTLRPC_SVC_INTG, SPTLRPC_SVC_NULL, and SPTLRPC_SVC_PRIV.
int gss_check_seq_num (struct gss_svc_seq_data * sd, __u32 seq_num, int set)
Definition at line 536 of file sec_gss.c.
References gss_do_check_seq(), GSS_SEQ_WIN_BACK, GSS_SEQ_WIN_MAIN, gss_stat_oos_record_svc(), gss_svc_seq_data::ssd_lock, gss_svc_seq_data::ssd_max_back, gss_svc_seq_data::ssd_max_main, gss_svc_seq_data::ssd_win_back, gss_svc_seq_data::ssd_win_main, and unlikely.
Referenced by gss_svc_unseal_request(), and gss_svc_verify_request().
int gss_cli_ctx_display (struct ptlrpc_cli_ctx * ctx, char * buf, int bufsize)
int gss_cli_ctx_fini_common (struct ptlrpc_sec * sec, struct ptlrpc_cli_ctx * ctx)
Definition at line 1209 of file sec_gss.c.
References ptlrpc_cli_ctx::cc_flags, ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_sec, ptlrpc_cli_ctx::cc_vcred, ctx2gctx(), CWARN, gss_cli_ctx::gc_mechctx, gss_cli_ctx_finalize(), gss_do_ctx_fini_rpc(), LASSERT, ptlrpc_sec::ps_nctx, ptlrpc_sec::ps_policy, PTLRPC_CTX_UPTODATE, sec2target_str(), sec_is_reverse(), ptlrpc_sec_policy::sp_name, and vfs_cred::vc_uid.
Referenced by ctx_destroy_kr(), and ctx_destroy_pf().
void gss_cli_ctx_flags2str (unsigned long flags, char * buf, int bufsize)
Definition at line 620 of file sec_gss.c.
References PTLRPC_CTX_CACHED, PTLRPC_CTX_DEAD, PTLRPC_CTX_ERROR, PTLRPC_CTX_ETERNAL, PTLRPC_CTX_NEW, PTLRPC_CTX_UPTODATE, and strlcat().
Referenced by gss_sec_display_kr().
int gss_cli_ctx_init_common (struct ptlrpc_sec * sec, struct ptlrpc_cli_ctx * ctx, struct ptlrpc_ctx_ops * ctxops, struct vfs_cred * vcred)
Definition at line 1172 of file sec_gss.c.
References ptlrpc_cli_ctx::cc_cache, ptlrpc_cli_ctx::cc_expire, ptlrpc_cli_ctx::cc_flags, ptlrpc_cli_ctx::cc_gc_chain, ptlrpc_cli_ctx::cc_lock, ptlrpc_cli_ctx::cc_ops, ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_req_list, ptlrpc_cli_ctx::cc_sec, ptlrpc_cli_ctx::cc_vcred, CDEBUG, ctx2gctx(), D_SEC, gss_cli_ctx::gc_seq, gss_cli_ctx::gc_win, INIT_HLIST_NODE, INIT_LIST_HEAD, ptlrpc_sec::ps_nctx, ptlrpc_sec::ps_policy, ptlrpc_sec::ps_refcount, PTLRPC_CTX_NEW, sec2target_str(), ptlrpc_sec_policy::sp_name, and vfs_cred::vc_uid.
Referenced by ctx_create_kr(), and ctx_create_pf().
int gss_cli_ctx_match (struct ptlrpc_cli_ctx * ctx, struct vfs_cred * vcred)
Definition at line 615 of file sec_gss.c.
References ptlrpc_cli_ctx::cc_vcred, and vfs_cred::vc_uid.
int gss_cli_ctx_seal (struct ptlrpc_cli_ctx * ctx, struct ptlrpc_request * req)
Definition at line 881 of file sec_gss.c.
References ptlrpc_cli_ctx::cc_sec, CERROR, CWARN, rawobj_s::data, netobj_s::data, ENTRY, gss_cli_ctx::gc_base, gss_cli_ctx::gc_handle, gss_cli_ctx::gc_mechctx, gss_cli_ctx::gc_proc, gss_cli_ctx::gc_seq, gss_header::gh_flags, gss_header::gh_handle, gss_header::gh_proc, gss_header::gh_seq, gss_header::gh_sp, gss_header::gh_svc, gss_header::gh_version, GOTO, gss_cli_payload(), GSS_S_COMPLETE, GSS_SEQ_REPACK_THRESHOLD, gss_stat_oos_record_cli(), LASSERT, rawobj_s::len, netobj_s::len, lgss_wrap(), LUSTRE_GSS_PACK_BULK, LUSTRE_GSS_PACK_USER, lustre_init_msg_v2(), lustre_msg_buf(), lustre_msg_buflen(), lustre_msg_size_v2(), lustre_shrink_msg(), OBD_ALLOC_LARGE, OBD_FREE_LARGE, ptlrpc_sec::ps_part, PTLRPC_GSS_HEADER_SIZE, PTLRPC_GSS_VERSION, RETURN, ptlrpc_request::rq_clrbuf, ptlrpc_request::rq_clrbuf_len, ptlrpc_request::rq_clrdata_len, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_pack_udesc, ptlrpc_request::rq_pool, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqbuf_len, ptlrpc_request::rq_reqdata_len, ptlrpc_request::rq_reqlen, sptlrpc_flavor::sf_rpc, SPTLRPC_SVC_PRIV, and unlikely.
int gss_cli_ctx_sign (struct ptlrpc_cli_ctx * ctx, struct ptlrpc_request * req)
Definition at line 640 of file sec_gss.c.
References ptlrpc_cli_ctx::cc_sec, ctx2gctx(), CWARN, ENTRY, gss_cli_ctx::gc_handle, gss_cli_ctx::gc_mechctx, gss_cli_ctx::gc_proc, gss_cli_ctx::gc_seq, GSS_SEQ_REPACK_THRESHOLD, gss_sign_msg(), gss_stat_oos_record_cli(), LASSERT, LUSTRE_GSS_PACK_BULK, LUSTRE_GSS_PACK_USER, ptlrpc_sec::ps_part, RETURN, ptlrpc_request::rq_ctx_init, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_pack_udesc, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqdata_len, sptlrpc_flavor::sf_rpc, SPTLRPC_FLVR_SVC, and SPTLRPC_SVC_NULL.
int gss_cli_ctx_unseal (struct ptlrpc_cli_ctx * ctx, struct ptlrpc_request * req)
Definition at line 980 of file sec_gss.c.
References __lustre_unpack_msg(), bulk_sec_desc_unpack(), CERROR, ENTRY, equi, gss_cli_ctx::gc_mechctx, gss_header::gh_flags, gss_header::gh_proc, gss_header::gh_version, gss_cli_ctx_handle_err_notify(), gss_header_swabber(), GSS_S_COMPLETE, gss_swab_header(), gss_unseal_msg(), LASSERT, LUSTRE_GSS_PACK_BULK, lustre_msg, lustre_msg_buf(), PTLRPC_GSS_PROC_DATA, PTLRPC_GSS_PROC_ERR, PTLRPC_GSS_VERSION, ptlrpc_rep_need_swab(), RETURN, ptlrpc_request::rq_ctx_init, ptlrpc_request::rq_early, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_repdata, ptlrpc_request::rq_repdata_len, ptlrpc_request::rq_replen, and ptlrpc_request::rq_repmsg.
int gss_cli_ctx_unwrap_bulk (struct ptlrpc_cli_ctx * ctx, struct ptlrpc_request * req, struct ptlrpc_bulk_desc * desc)
Definition at line 168 of file gss_bulk.c.
References BD_GET_KIOV, ptlrpc_bulk_desc::bd_iov_count, ptlrpc_bulk_desc::bd_nob, ptlrpc_bulk_desc::bd_nob_transferred, ptlrpc_bulk_desc::bd_type, ptlrpc_bulk_sec_desc::bsd_data, BSD_FL_ERR, ptlrpc_bulk_sec_desc::bsd_flags, ptlrpc_bulk_sec_desc::bsd_nob, ptlrpc_bulk_sec_desc::bsd_svc, ptlrpc_bulk_sec_desc::bsd_type, ptlrpc_bulk_sec_desc::bsd_version, CERROR, rawobj_s::data, ENTRY, gss_cli_ctx::gc_mechctx, GET_KIOV, GSS_S_COMPLETE, LASSERT, LBUG, rawobj_s::len, lgss_unwrap_bulk(), lgss_verify_mic(), lustre_msg, lustre_msg_buf(), lustre_msg_buflen(), ptlrpc_is_bulk_desc_kiov(), RETURN, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_clrbuf, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_repdata, ptlrpc_request::rq_reqbuf, sptlrpc_flavor::sf_rpc, SPTLRPC_BULK_SVC_INTG, SPTLRPC_BULK_SVC_NULL, SPTLRPC_BULK_SVC_PRIV, SPTLRPC_FLVR_SVC, SPTLRPC_SVC_AUTH, SPTLRPC_SVC_INTG, SPTLRPC_SVC_NULL, and SPTLRPC_SVC_PRIV.
void gss_cli_ctx_uptodate (struct gss_cli_ctx * gctx)
Definition at line 369 of file sec_gss.c.
References ptlrpc_cli_ctx::cc_expire, ptlrpc_cli_ctx::cc_flags, ptlrpc_cli_ctx::cc_sec, ptlrpc_cli_ctx::cc_vcred, CERROR, cfs_time_current_sec(), CWARN, gss_cli_ctx::gc_base, gss_cli_ctx::gc_handle, gss_cli_ctx::gc_mechctx, gss_handle_to_u64(), gss_round_ctx_expiry(), gss_sec_install_rctx(), lgss_inquire_context(), LPX64, ptlrpc_sec::ps_flvr, ptlrpc_sec::ps_import, PTLRPC_CTX_UPTODATE_BIT, sec2target_str(), sec_is_reverse(), sptlrpc_flavor::sf_flags, sptlrpc_cli_ctx_wakeup(), and vfs_cred::vc_uid.
Referenced by gss_copy_rvc_cli_ctx(), gss_kt_update(), and gss_pipe_downcall().
int gss_cli_ctx_verify (struct ptlrpc_cli_ctx * ctx, struct ptlrpc_request * req)
Definition at line 757 of file sec_gss.c.
References bulk_sec_desc_unpack(), CERROR, cksum, CWARN, ENTRY, equi, gss_cli_ctx::gc_mechctx, gss_header::gh_flags, gss_header::gh_proc, gss_header::gh_seq, gss_header::gh_svc, gss_header::gh_version, gss_cli_ctx_handle_err_notify(), gss_header_swabber(), GSS_S_COMPLETE, gss_swab_header(), gss_verify_msg(), LASSERT, LUSTRE_GSS_PACK_BULK, lustre_msg, lustre_msg_buf(), lustre_msg_buflen(), PTLRPC_GSS_PROC_DATA, PTLRPC_GSS_PROC_ERR, ptlrpc_rep_need_swab(), RETURN, ptlrpc_request::rq_ctx_init, ptlrpc_request::rq_early, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_repdata, ptlrpc_request::rq_replen, ptlrpc_request::rq_repmsg, and SPTLRPC_SVC_NULL.
int gss_cli_ctx_wrap_bulk (struct ptlrpc_cli_ctx * ctx, struct ptlrpc_request * req, struct ptlrpc_bulk_desc * desc)
Definition at line 62 of file gss_bulk.c.
References ptlrpc_bulk_desc::bd_iov_count, ptlrpc_bulk_desc::bd_nob, ptlrpc_bulk_desc::bd_type, ptlrpc_bulk_sec_desc::bsd_data, ptlrpc_bulk_sec_desc::bsd_flags, ptlrpc_bulk_sec_desc::bsd_nob, ptlrpc_bulk_sec_desc::bsd_svc, ptlrpc_bulk_sec_desc::bsd_type, ptlrpc_bulk_sec_desc::bsd_version, CERROR, CWARN, rawobj_s::data, ENTRY, gss_cli_ctx::gc_mechctx, GET_KIOV, gss_cli_prep_bulk(), GSS_S_COMPLETE, LASSERT, LBUG, rawobj_s::len, lgss_get_mic(), lgss_wrap_bulk(), lustre_msg, lustre_msg_buf(), lustre_msg_buflen(), msg, ptlrpc_is_bulk_desc_kiov(), RETURN, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_clrbuf, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_reqbuf, sptlrpc_flavor::sf_rpc, SPTLRPC_BULK_DEFAULT, SPTLRPC_BULK_SVC_INTG, SPTLRPC_BULK_SVC_NULL, SPTLRPC_BULK_SVC_PRIV, sptlrpc_enc_pool_get_pages(), SPTLRPC_FLVR_BULK_SVC, SPTLRPC_FLVR_SVC, SPTLRPC_SVC_AUTH, SPTLRPC_SVC_INTG, SPTLRPC_SVC_NULL, and SPTLRPC_SVC_PRIV.
int gss_cli_prep_bulk (struct ptlrpc_request * req, struct ptlrpc_bulk_desc * desc)
Definition at line 323 of file gss_bulk.c.
References CERROR, ctx2gctx(), ENTRY, gss_cli_ctx::gc_mechctx, gss_prep_bulk(), LASSERT, RETURN, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pack_bulk, sptlrpc_flavor::sf_rpc, SPTLRPC_BULK_SVC_PRIV, and SPTLRPC_FLVR_BULK_SVC.
Referenced by gss_cli_ctx_wrap_bulk().
int gss_copy_rvc_cli_ctx (struct ptlrpc_cli_ctx * cli_ctx, struct ptlrpc_svc_ctx * svc_ctx)
Definition at line 2801 of file sec_gss.c.
References CERROR, ctx2gctx(), gss_cli_ctx::gc_handle, gss_cli_ctx::gc_mechctx, gss_cli_ctx::gc_proc, gss_cli_ctx::gc_seq, gss_cli_ctx::gc_svc_handle, gss_cli_ctx::gc_win, gss_svc_ctx::gsc_mechctx, gss_svc_ctx::gsc_rvs_hdl, gss_svc_ctx::gsc_rvs_seq, gss_cli_ctx_uptodate(), GSS_S_COMPLETE, GSS_SEQ_WIN, gss_svc_ctx2gssctx(), gss_svc_upcall_dup_handle(), LASSERT, lgss_copy_reverse_context(), lgss_delete_sec_context(), PTLRPC_GSS_PROC_DATA, rawobj_dup(), and rawobj_free().
Referenced by gss_install_rvs_cli_ctx_pf(), and sec_install_rctx_kr().
int gss_do_ctx_fini_rpc (struct gss_cli_ctx * gctx)
Definition at line 376 of file gss_cli_upcall.c.
References ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_sec, ptlrpc_cli_ctx::cc_vcred, CDEBUG, cli_ctx_is_error(), cli_ctx_is_uptodate(), CWARN, D_SEC, ENTRY, gss_cli_ctx::gc_base, gss_cli_ctx::gc_handle, gss_cli_ctx::gc_proc, GOTO, gss_handle_to_u64(), LASSERT, LPX64, lustre_msg_buf(), LUSTRE_OBD_VERSION, ptlrpc_sec::ps_import, ptl_send_rpc(), PTLRPC_GSS_PROC_DESTROY, ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_bufs_pack(), ptlrpc_user_desc::pud_cap, ptlrpc_user_desc::pud_fsgid, ptlrpc_user_desc::pud_fsuid, ptlrpc_user_desc::pud_gid, ptlrpc_user_desc::pud_ngroups, ptlrpc_user_desc::pud_uid, RETURN, ptlrpc_request::rq_pack_udesc, ptlrpc_request::rq_phase, RQ_PHASE_RPC, ptlrpc_request::rq_reqbuf, RQF_SEC_CTX, sec2target_str(), SEC_CTX_FINI, sec_is_reverse(), vfs_cred::vc_gid, and vfs_cred::vc_uid.
Referenced by gss_cli_ctx_fini_common().
int gss_do_ctx_init_rpc (char __user * buffer, unsigned long count)
Definition at line 233 of file gss_cli_upcall.c.
References CERROR, client_obd::cl_import, client_obd::cl_sem, class_import_get(), class_import_put(), class_name2obd(), obd_device::cli, ctx_init_pack_request(), ctx_init_parse_reply(), CWARN, lgssd_ioctl_param::gid, GSSD_INTERFACE_VERSION, obd_import::imp_deactive, LASSERT, LUSTRE_LWP_NAME, LUSTRE_MDC_NAME, LUSTRE_MGC_NAME, LUSTRE_OBD_VERSION, LUSTRE_OSC_NAME, LUSTRE_OSP_NAME, lgssd_ioctl_param::lustre_svc, obd_device::obd_dev_lock, obd_device::obd_name, obd_device::obd_set_up, obd_device::obd_stopping, obd_device::obd_type, ptlrpc_queue_wait(), ptlrpc_rep_need_swab(), ptlrpc_req_finished(), ptlrpc_request_alloc_pack(), ptlrpc_request_set_replen(), lgssd_ioctl_param::reply_buf, lgssd_ioctl_param::reply_buf_size, lgssd_ioctl_param::reply_length, RETURN, ptlrpc_request::rq_repdata, RQF_SEC_CTX, SEC_CTX_INIT, lgssd_ioctl_param::secid, lgssd_ioctl_param::send_token, lgssd_ioctl_param::send_token_size, lgssd_ioctl_param::status, obd_type::typ_name, obd_device::u, lgssd_ioctl_param::uid, unlikely, lgssd_ioctl_param::uuid, and lgssd_ioctl_param::version.
Referenced by gss_proc_write_secinit().
int gss_enlarge_reqbuf (struct ptlrpc_sec * sec, struct ptlrpc_request * req, int segment, int newsize)
Definition at line 1838 of file sec_gss.c.
References gss_enlarge_reqbuf_intg(), gss_enlarge_reqbuf_priv(), LASSERT, LASSERTF, ptlrpc_request::rq_ctx_fini, ptlrpc_request::rq_ctx_init, ptlrpc_request::rq_flvr, sptlrpc_flavor::sf_rpc, SPTLRPC_FLVR_SVC, SPTLRPC_SVC_AUTH, SPTLRPC_SVC_INTG, SPTLRPC_SVC_NULL, and SPTLRPC_SVC_PRIV.
void gss_exit_cli_upcall (void)
Definition at line 445 of file gss_cli_upcall.c.
Referenced by sptlrpc_gss_exit(), and sptlrpc_gss_init().
static void __exit gss_exit_keyring (void) [inline, static]
Definition at line 434 of file gss_internal.h.
void gss_exit_lproc (void)
Definition at line 188 of file lproc_gss.c.
References gss_proc_lk, gss_proc_root, and lprocfs_remove().
Referenced by gss_init_lproc(), sptlrpc_gss_exit(), and sptlrpc_gss_init().
static void __exit gss_exit_pipefs (void) [inline, static]
Definition at line 443 of file gss_internal.h.
void gss_exit_svc_upcall (void)
Definition at line 1167 of file gss_svc_upcall.c.
References _cache_unregister_net(), rsc_cache, and rsi_cache.
Referenced by sptlrpc_gss_exit(), and sptlrpc_gss_init().
void gss_free_repbuf (struct ptlrpc_sec * sec, struct ptlrpc_request * req)
Definition at line 1596 of file sec_gss.c.
References OBD_FREE_LARGE, ptlrpc_request::rq_repbuf, ptlrpc_request::rq_repbuf_len, ptlrpc_request::rq_repdata, and ptlrpc_request::rq_repdata_len.
void gss_free_reqbuf (struct ptlrpc_sec * sec, struct ptlrpc_request * req)
Definition at line 1438 of file sec_gss.c.
References ENTRY, EXIT, LASSERT, OBD_FREE_LARGE, ptlrpc_request::rq_clrbuf, ptlrpc_request::rq_clrbuf_len, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pool, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqbuf_len, sptlrpc_flavor::sf_rpc, SPTLRPC_FLVR_SVC, and SPTLRPC_SVC_PRIV.
__u64 gss_get_next_ctx_index (void)
Definition at line 77 of file gss_svc_upcall.c.
References __ctx_index, __ctx_index_lock, and __u64.
Referenced by gss_cli_ctx_refresh_pf(), gss_sec_lookup_ctx_kr(), and rsi_request().
static __u64 gss_handle_to_u64 (rawobj_t * handle) [inline, static]
Definition at line 198 of file gss_internal.h.
References __u64, rawobj_s::data, rawobj_s::len, and PTLRPC_GSS_MAX_HANDLE_SIZE.
Referenced by gss_cli_ctx_handle_err_notify(), gss_cli_ctx_uptodate(), gss_do_ctx_fini_rpc(), gss_sec_display_kr(), gss_svc_handle_data(), gss_svc_handle_destroy(), gss_svc_upcall_get_ctx(), and gss_svc_upcall_handle_init().
int __init gss_init_cli_upcall (void)
Definition at line 440 of file gss_cli_upcall.c.
Referenced by sptlrpc_gss_init().
static int __init gss_init_keyring (void) [inline, static]
Definition at line 433 of file gss_internal.h.
int __init gss_init_lproc (void)
Definition at line 201 of file lproc_gss.c.
References CERROR, GOTO, gss_exit_lproc(), gss_proc_lk, gss_proc_root, gss_stat_oos, lprocfs_register(), and sptlrpc_proc_root.
Referenced by sptlrpc_gss_init().
static int __init gss_init_pipefs (void) [inline, static]
Definition at line 442 of file gss_internal.h.
int __init gss_init_svc_upcall (void)
Definition at line 1124 of file gss_svc_upcall.c.
References __ctx_index, __ctx_index_lock, _cache_register_net(), _cache_unregister_net(), cfs_get_random_bytes(), CWARN, LASSERT, rsc_cache, and rsi_cache.
Referenced by sptlrpc_gss_init().
int gss_pack_err_notify (struct ptlrpc_request * req, __u32 major, __u32 minor)
Definition at line 1955 of file sec_gss.c.
References CDEBUG, CERROR, D_SEC, ENTRY, gss_err_header::gh_flags, gss_err_header::gh_handle, gss_err_header::gh_major, gss_err_header::gh_minor, gss_err_header::gh_proc, gss_err_header::gh_version, gss_svc_ctx2reqctx(), LASSERT, netobj_s::len, libcfs_nid2str(), lustre_msg_buf(), lustre_msg_size_v2(), lustre_pack_reply_v2(), lnet_process_id_t::nid, ptlrpc_body, PTLRPC_GSS_PROC_ERR, PTLRPC_GSS_VERSION, RETURN, ptlrpc_request::rq_peer, ptlrpc_reply_state::rs_repbuf, ptlrpc_reply_state::rs_repdata_len, gss_svc_reqctx::src_err_notify, and gss_svc_reqctx::src_reserve_len.
Referenced by gss_svc_handle_data(), and gss_svc_upcall_handle_init().
static unsigned long gss_round_ctx_expiry (unsigned long expiry, unsigned long sec_flags) [inline, static]
Definition at line 75 of file gss_internal.h.
References __TIMEOUT_DELTA, and PTLRPC_SEC_FL_REVERSE.
Referenced by gss_cli_ctx_uptodate().
int gss_sec_create_common (struct gss_sec * gsec, struct ptlrpc_sec_policy * policy, struct obd_import * imp, struct ptlrpc_svc_ctx * ctx, struct sptlrpc_flavor * sf)
Definition at line 1095 of file sec_gss.c.
References CDEBUG, CERROR, class_import_get(), D_SEC, gss_sec::gs_base, gss_sec::gs_lock, gss_sec::gs_mech, gss_sec::gs_rvs_hdl, GSS_GC_INTERVAL, INIT_LIST_HEAD, LASSERT, lgss_subflavor_to_mech(), ptlrpc_sec::ps_flvr, ptlrpc_sec::ps_gc_interval, ptlrpc_sec::ps_gc_list, ptlrpc_sec::ps_id, ptlrpc_sec::ps_import, ptlrpc_sec::ps_lock, ptlrpc_sec::ps_nctx, ptlrpc_sec::ps_policy, ptlrpc_sec::ps_refcount, sec_is_reverse(), sptlrpc_flavor::sf_rpc, ptlrpc_sec_policy::sp_name, SPTLRPC_BULK_SVC_PRIV, sptlrpc_enc_pool_add_user(), SPTLRPC_FLVR_BASE_SUB, SPTLRPC_FLVR_BULK_SVC, SPTLRPC_FLVR_POLICY, sptlrpc_get_next_secid(), and SPTLRPC_POLICY_GSS.
Referenced by gss_sec_create_kr(), and gss_sec_create_pf().
void gss_sec_destroy_common (struct gss_sec * gsec)
Definition at line 1145 of file sec_gss.c.
References class_import_put(), ENTRY, EXIT, gss_sec::gs_base, gss_sec::gs_mech, LASSERT, lgss_mech_put(), ptlrpc_sec::ps_flvr, ptlrpc_sec::ps_import, ptlrpc_sec::ps_nctx, ptlrpc_sec::ps_refcount, sptlrpc_flavor::sf_rpc, SPTLRPC_BULK_SVC_PRIV, sptlrpc_enc_pool_del_user(), and SPTLRPC_FLVR_BULK_SVC.
Referenced by gss_sec_create_kr(), gss_sec_create_pf(), gss_sec_destroy_kr(), and gss_sec_destroy_pf().
int gss_sec_install_rctx (struct obd_import * imp, struct ptlrpc_sec * sec, struct ptlrpc_cli_ctx * ctx)
Definition at line 1859 of file sec_gss.c.
References gss_cli_ctx::gc_base, and gss_install_rvs_svc_ctx().
Referenced by gss_cli_ctx_uptodate().
void gss_sec_kill (struct ptlrpc_sec * sec)
Definition at line 1167 of file sec_gss.c.
References ptlrpc_sec::ps_dying.
void gss_stat_oos_record_cli (int behind)
Definition at line 77 of file lproc_gss.c.
References gss_stat_oos.
Referenced by gss_cli_ctx_seal(), and gss_cli_ctx_sign().
void gss_stat_oos_record_svc (int phase, int replay)
Definition at line 87 of file lproc_gss.c.
References gss_stat_oos, and LASSERT.
Referenced by gss_check_seq_num().
int gss_svc_accept (struct ptlrpc_sec_policy * policy, struct ptlrpc_request * req)
Definition at line 2366 of file sec_gss.c.
References CERROR, ENTRY, gss_header::gh_flags, gss_header::gh_handle, gss_header::gh_proc, gss_header::gh_seq, gss_header::gh_sp, gss_header::gh_svc, gss_header::gh_version, gss_svc_ctx::gsc_mapped_uid, gss_svc_ctx::gsc_remote, gss_svc_ctx::gsc_uid, gss_svc_ctx::gsc_usr_mds, gss_svc_ctx::gsc_usr_oss, gss_svc_ctx::gsc_usr_root, gss_header_swabber(), gss_svc_handle_data(), gss_svc_handle_destroy(), gss_svc_handle_init(), gss_svc_reqctx_free(), gss_swab_header(), gss_wire_ctx::gw_flags, gss_wire_ctx::gw_handle, gss_wire_ctx::gw_proc, gss_wire_ctx::gw_seq, gss_wire_ctx::gw_svc, LASSERT, OBD_ALLOC_PTR, PTLRPC_GSS_PROC_CONTINUE_INIT, PTLRPC_GSS_PROC_DATA, PTLRPC_GSS_PROC_DESTROY, PTLRPC_GSS_PROC_INIT, PTLRPC_GSS_VERSION, ptlrpc_req_need_swab(), rawobj_from_netobj(), RETURN, ptlrpc_request::rq_auth_gss, ptlrpc_request::rq_auth_remote, ptlrpc_request::rq_auth_usr_mdt, ptlrpc_request::rq_auth_usr_ost, ptlrpc_request::rq_auth_usr_root, ptlrpc_request::rq_reqbuf, ptlrpc_svc_ctx::sc_policy, ptlrpc_svc_ctx::sc_refcount, SECSVC_COMPLETE, SECSVC_DROP, SECSVC_OK, sptlrpc_policy_get(), gss_svc_reqctx::src_base, gss_svc_reqctx::src_ctx, and gss_svc_reqctx::src_wirectx.
Referenced by gss_svc_accept_kr(), and gss_svc_accept_pf().
int gss_svc_alloc_rs (struct ptlrpc_request * req, int msglen)
Definition at line 2517 of file sec_gss.c.
References CERROR, ENTRY, GSS_MAX_CIPHER_BLOCK, gss_svc_bulk_payload(), gss_svc_ctx2reqctx(), gss_svc_payload(), gss_svc_reqctx_addref(), gss_svc_reqctx_is_special(), LASSERT, lustre_init_msg_v2(), lustre_msg, lustre_msg_buf(), lustre_msg_buflen(), lustre_msg_size_v2(), OBD_ALLOC_LARGE, PTLRPC_GSS_HEADER_SIZE, RETURN, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_packed_final, ptlrpc_reply_state::rs_msg, ptlrpc_reply_state::rs_repbuf, ptlrpc_reply_state::rs_repbuf_len, ptlrpc_reply_state::rs_size, ptlrpc_reply_state::rs_svc_ctx, sptlrpc_flavor::sf_rpc, SPTLRPC_FLVR_SVC, SPTLRPC_SVC_INTG, SPTLRPC_SVC_NULL, SPTLRPC_SVC_PRIV, gss_svc_reqctx::src_ctx, gss_svc_reqctx::src_repbsd, gss_svc_reqctx::src_repbsd_size, and gss_svc_reqctx::src_reqbsd.
int gss_svc_authorize (struct ptlrpc_request * req)
Definition at line 2735 of file sec_gss.c.
References CERROR, ENTRY, GOTO, gss_at_reply_off_integ, gss_svc_ctx2reqctx(), gss_svc_reqctx_is_special(), gss_svc_seal(), gss_svc_sign(), gss_wire_ctx::gw_proc, gss_wire_ctx::gw_svc, LASSERT, PTLRPC_GSS_PROC_DATA, PTLRPC_GSS_PROC_DESTROY, RETURN, ptlrpc_request::rq_packed_final, ptlrpc_request::rq_reply_off, ptlrpc_reply_state::rs_repdata_len, SPTLRPC_SVC_AUTH, SPTLRPC_SVC_INTG, SPTLRPC_SVC_NULL, SPTLRPC_SVC_PRIV, gss_svc_reqctx::src_ctx, and gss_svc_reqctx::src_wirectx.
static struct gss_svc_ctx* gss_svc_ctx2gssctx (struct ptlrpc_svc_ctx * ctx) [static, read]
Definition at line 367 of file gss_internal.h.
References gss_svc_ctx2reqctx(), LASSERT, and gss_svc_reqctx::src_ctx.
Referenced by gss_copy_rvc_cli_ctx().
static struct gss_svc_reqctx* gss_svc_ctx2reqctx (struct ptlrpc_svc_ctx * ctx) [static, read]
Definition at line 360 of file gss_internal.h.
References LASSERT, and gss_svc_reqctx::src_base.
Referenced by gss_pack_err_notify(), gss_svc_alloc_rs(), gss_svc_authorize(), gss_svc_ctx2gssctx(), gss_svc_free_ctx(), gss_svc_handle_data(), gss_svc_handle_destroy(), gss_svc_handle_init(), gss_svc_invalidate_ctx(), gss_svc_prep_bulk(), gss_svc_unwrap_bulk(), and gss_svc_wrap_bulk().
void gss_svc_free_ctx (struct ptlrpc_svc_ctx * ctx)
Definition at line 2795 of file sec_gss.c.
References gss_svc_ctx2reqctx(), gss_svc_reqctx_free(), LASSERT, and ptlrpc_svc_ctx::sc_refcount.
void gss_svc_free_rs (struct ptlrpc_reply_state * rs)
Definition at line 2781 of file sec_gss.c.
References gss_svc_reqctx_decref(), LASSERT, OBD_FREE_LARGE, ptlrpc_reply_state::rs_prealloc, ptlrpc_reply_state::rs_size, ptlrpc_reply_state::rs_svc_ctx, and gss_svc_reqctx::src_base.
void gss_svc_invalidate_ctx (struct ptlrpc_svc_ctx * svc_ctx)
Definition at line 2460 of file sec_gss.c.
References CWARN, ENTRY, EXIT, gss_svc_ctx::gsc_uid, gss_svc_ctx2reqctx(), gss_svc_upcall_destroy_ctx(), and gss_svc_reqctx::src_ctx.
int gss_svc_prep_bulk (struct ptlrpc_request * req, struct ptlrpc_bulk_desc * desc)
Definition at line 344 of file gss_bulk.c.
References ptlrpc_bulk_sec_desc::bsd_svc, CERROR, ENTRY, gss_svc_ctx::gsc_mechctx, gss_prep_bulk(), gss_svc_ctx2reqctx(), LASSERT, RETURN, ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_pack_bulk, SPTLRPC_BULK_SVC_PRIV, gss_svc_reqctx::src_ctx, gss_svc_reqctx::src_repbsd, and gss_svc_reqctx::src_reqbsd.
int gss_svc_unwrap_bulk (struct ptlrpc_request * req, struct ptlrpc_bulk_desc * desc)
Definition at line 374 of file gss_bulk.c.
References ptlrpc_bulk_desc::bd_iov_count, ptlrpc_bulk_desc::bd_nob, ptlrpc_bulk_desc::bd_nob_transferred, ptlrpc_bulk_desc::bd_type, ptlrpc_bulk_sec_desc::bsd_data, BSD_FL_ERR, ptlrpc_bulk_sec_desc::bsd_flags, ptlrpc_bulk_sec_desc::bsd_nob, ptlrpc_bulk_sec_desc::bsd_svc, ptlrpc_bulk_sec_desc::bsd_type, ptlrpc_bulk_sec_desc::bsd_version, CERROR, rawobj_s::data, ENTRY, GET_KIOV, gss_svc_ctx::gsc_mechctx, GSS_S_COMPLETE, gss_svc_ctx2reqctx(), LASSERT, rawobj_s::len, lgss_unwrap_bulk(), lgss_verify_mic(), ptlrpc_is_bulk_desc_kiov(), RETURN, ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_pack_bulk, SPTLRPC_BULK_DEFAULT, SPTLRPC_BULK_SVC_INTG, SPTLRPC_BULK_SVC_PRIV, gss_svc_reqctx::src_ctx, gss_svc_reqctx::src_repbsd, gss_svc_reqctx::src_reqbsd, and gss_svc_reqctx::src_reqbsd_size.
void gss_svc_upcall_destroy_ctx (struct gss_svc_ctx * ctx)
Definition at line 1114 of file gss_svc_upcall.c.
References rsc::h.
Referenced by gss_svc_handle_destroy(), and gss_svc_invalidate_ctx().
int gss_svc_upcall_dup_handle (rawobj_t * handle, struct gss_svc_ctx * ctx)
Definition at line 880 of file gss_svc_upcall.c.
References rsc::handle, and rawobj_dup().
Referenced by gss_copy_rvc_cli_ctx().
int gss_svc_upcall_expire_rvs_ctx (rawobj_t * handle)
Definition at line 864 of file gss_svc_upcall.c.
References CDEBUG, cfs_time_current_sec(), COMPAT_RSC_PUT, rsc::ctx, D_SEC, gss_svc_searchbyctx(), rsc::h, and rsc_cache.
Referenced by gss_cli_ctx_finalize().
struct gss_svc_ctx* gss_svc_upcall_get_ctx (struct ptlrpc_request * req, struct gss_wire_ctx * gw) [read]
Definition at line 1091 of file gss_svc_upcall.c.
References rsc::ctx, CWARN, gss_handle_to_u64(), gss_svc_searchbyctx(), gss_wire_ctx::gw_handle, libcfs_nid2str(), LPX64, lnet_process_id_t::nid, and ptlrpc_request::rq_peer.
Referenced by gss_svc_handle_data(), and gss_svc_handle_destroy().
int gss_svc_upcall_handle_init (struct ptlrpc_request * req, struct gss_svc_reqctx * grctx, struct gss_wire_ctx * gw, struct obd_device * target, __u32 lustre_svc, rawobj_t * rvs_hdl, rawobj_t * in_token)
Definition at line 908 of file gss_svc_upcall.c.
References __u64, CDEBUG, CERROR, cfs_size_round4(), COMPAT_RSC_PUT, rsc::ctx, CWARN, D_SEC, rawobj_s::data, netobj_s::data, ENTRY, gss_rep_header::gh_flags, gss_rep_header::gh_handle, gss_rep_header::gh_major, gss_rep_header::gh_minor, gss_rep_header::gh_proc, gss_rep_header::gh_seqwin, gss_rep_header::gh_version, GOTO, gss_svc_ctx::gsc_rvs_hdl, gss_svc_ctx::gsc_uid, gss_handle_to_u64(), gss_pack_err_notify(), GSS_S_FAILURE, GSS_SEQ_WIN, gss_svc_searchbyctx(), GSS_SVC_UPCALL_TIMEOUT, gss_wire_ctx::gw_handle, rsc::h, rsi::h, rsc::handle, LASSERT, netobj_s::len, rawobj_s::len, libcfs_nid2str(), LPX64, lustre_msg_buf(), lustre_pack_reply_v2(), lustre_shrink_msg(), rsi::major_status, rsi::minor_status, lnet_process_id_t::nid, rsi::out_handle, rsi::out_token, ptlrpc_body, PTLRPC_GSS_MAX_HANDLE_SIZE, PTLRPC_GSS_PROC_ERR, PTLRPC_GSS_VERSION, rawobj_dup(), rawobj_free(), RETURN, ptlrpc_request::rq_peer, ptlrpc_reply_state::rs_repbuf, ptlrpc_reply_state::rs_repdata_len, rsc_cache, rsi_cache, rsi_free(), rsi_lookup(), rsi_put(), SECSVC_COMPLETE, SECSVC_DROP, SECSVC_OK, gss_svc_reqctx::src_ctx, gss_svc_reqctx::src_init, gss_svc_reqctx::src_reserve_len, rsc::target, and rsi::waitq.
Referenced by gss_svc_handle_init().
int gss_svc_upcall_install_rvs_ctx (struct obd_import * imp, struct gss_sec * gsec, struct gss_cli_ctx * gctx)
Definition at line 805 of file gss_svc_upcall.c.
References CERROR, rsc::ctx, CWARN, ENTRY, gss_cli_ctx::gc_mechctx, gss_cli_ctx::gc_svc_handle, GOTO, gss_sec::gs_rvs_hdl, gss_svc_ctx::gsc_mechctx, gss_svc_ctx::gsc_usr_mds, gss_svc_ctx::gsc_usr_oss, gss_svc_ctx::gsc_usr_root, GSS_S_COMPLETE, rsc::h, rsc::handle, obd_import::imp_obd, lgss_copy_reverse_context(), lgss_inquire_context(), LPX64, LUSTRE_MDC_NAME, LUSTRE_OSC_NAME, obd2cli_tgt, obd_device::obd_type, rawobj_alloc(), rawobj_dup(), RETURN, rsc_cache, rsc_free(), rsc_lookup(), rsc_update(), rsc::target, and obd_type::typ_name.
Referenced by gss_install_rvs_svc_ctx().
void gss_svc_upcall_put_ctx (struct gss_svc_ctx * ctx)
Definition at line 1107 of file gss_svc_upcall.c.
References COMPAT_RSC_PUT, rsc::h, and rsc_cache.
Referenced by gss_svc_reqctx_free().
int gss_svc_upcall_update_sequence (rawobj_t * handle, __u32 seq)
Definition at line 887 of file gss_svc_upcall.c.
References CDEBUG, COMPAT_RSC_PUT, rsc::ctx, D_SEC, gss_svc_ctx::gsc_rvs_seq, gss_svc_searchbyctx(), rsc::h, and rsc_cache.
Referenced by dispose_ctx_list_kr().
int gss_svc_wrap_bulk (struct ptlrpc_request * req, struct ptlrpc_bulk_desc * desc)
Definition at line 451 of file gss_bulk.c.
References ptlrpc_bulk_desc::bd_iov_count, ptlrpc_bulk_desc::bd_nob, ptlrpc_bulk_desc::bd_type, ptlrpc_bulk_sec_desc::bsd_data, BSD_FL_ERR, ptlrpc_bulk_sec_desc::bsd_flags, ptlrpc_bulk_sec_desc::bsd_nob, ptlrpc_bulk_sec_desc::bsd_svc, ptlrpc_bulk_sec_desc::bsd_type, ptlrpc_bulk_sec_desc::bsd_version, CERROR, rawobj_s::data, ENTRY, GET_KIOV, gss_svc_ctx::gsc_mechctx, GSS_S_COMPLETE, gss_svc_ctx2reqctx(), LASSERT, rawobj_s::len, lgss_get_mic(), lgss_wrap_bulk(), ptlrpc_is_bulk_desc_kiov(), RETURN, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_pack_bulk, SPTLRPC_BULK_DEFAULT, SPTLRPC_BULK_SVC_INTG, SPTLRPC_BULK_SVC_PRIV, sptlrpc_enc_pool_get_pages(), gss_svc_reqctx::src_ctx, gss_svc_reqctx::src_repbsd, gss_svc_reqctx::src_repbsd_size, and gss_svc_reqctx::src_reqbsd.
struct gss_header* gss_swab_header (struct lustre_msg * msg, int segment, int swabbed) [read]
Definition at line 107 of file sec_gss.c.
References CERROR, gss_header::gh_handle, gss_header_swabber(), netobj_s::len, and lustre_msg_buf().
Referenced by ctx_init_parse_reply(), gss_cli_ctx_unseal(), gss_cli_ctx_verify(), and gss_svc_accept().
netobj_t* gss_swab_netobj (struct lustre_msg * msg, int segment)
static __u32 import_to_gss_svc (struct obd_import * imp) [inline, static]
Definition at line 120 of file gss_internal.h.
References obd_import::imp_obd, LUSTRE_GSS_TGT_MDS, LUSTRE_GSS_TGT_MGS, LUSTRE_GSS_TGT_OSS, LUSTRE_LWP_NAME, LUSTRE_MDC_NAME, LUSTRE_MGC_NAME, LUSTRE_OSC_NAME, LUSTRE_OSP_NAME, name, obd_device::obd_type, and obd_type::typ_name.
Referenced by gss_ctx_refresh_pf(), and gss_sec_lookup_ctx_kr().
int __init init_kerberos_module (void)
Definition at line 1960 of file gss_krb5_mech.c.
References CERROR, krb5_seq_lock, lgss_mech_register(), and status.
Referenced by sptlrpc_gss_init().
int __init init_null_module (void)
Definition at line 184 of file gss_null_mech.c.
References CERROR, lgss_mech_register(), and status.
Referenced by sptlrpc_gss_init().
int __init init_sk_module (void)
Definition at line 215 of file gss_sk_mech.c.
References CERROR, lgss_mech_register(), and status.
Referenced by sptlrpc_gss_init().
int rawobj_alloc (rawobj_t * obj, char * buf, int len)
Definition at line 58 of file gss_rawobj.c.
References rawobj_s::data, LASSERT, rawobj_s::len, OBD_ALLOC_LARGE, and RETURN.
Referenced by gss_svc_upcall_install_rvs_ctx(), rsc_parse(), and rsi_parse().
int rawobj_dup (rawobj_t * dest, rawobj_t * src)
Definition at line 97 of file gss_rawobj.c.
References rawobj_s::data, LASSERT, rawobj_s::len, and OBD_ALLOC_LARGE.
Referenced by gss_copy_reverse_context_kerberos(), gss_copy_rvc_cli_ctx(), gss_pipe_downcall(), gss_svc_searchbyctx(), gss_svc_upcall_dup_handle(), gss_svc_upcall_handle_init(), gss_svc_upcall_install_rvs_ctx(), and keyblock_dup().
int rawobj_empty (rawobj_t * obj)
Definition at line 52 of file gss_rawobj.c.
References rawobj_s::data, equi, LASSERT, and rawobj_s::len.
Referenced by dispose_ctx_list_kr(), and gss_cli_ctx_finalize().
int rawobj_equal (rawobj_t * a, rawobj_t * b)
Definition at line 89 of file gss_rawobj.c.
References rawobj_s::data, LASSERT, and rawobj_s::len.
Referenced by __rsc_match(), and __rsi_match().
int rawobj_extract (rawobj_t * obj, __u32 ** buf, __u32 * buflen)
Definition at line 182 of file gss_rawobj.c.
References __rawobj_extract().
Referenced by gss_svc_handle_init().
int rawobj_extract_alloc (rawobj_t * obj, __u32 ** buf, __u32 * buflen)
Definition at line 187 of file gss_rawobj.c.
References __rawobj_extract().
int rawobj_extract_local (rawobj_t * obj, __u32 ** buf, __u32 * buflen)
Definition at line 192 of file gss_rawobj.c.
References __rawobj_extract().
Referenced by gss_kt_update(), and gss_pipe_downcall().
int rawobj_extract_local_alloc (rawobj_t * obj, __u32 ** buf, __u32 * buflen)
Definition at line 197 of file gss_rawobj.c.
References __rawobj_extract().
Referenced by gss_kt_update().
void rawobj_free (rawobj_t * obj)
Definition at line 76 of file gss_rawobj.c.
References rawobj_s::data, LASSERT, rawobj_s::len, and OBD_FREE_LARGE.
Referenced by delete_context_kerberos(), gss_cli_ctx_finalize(), gss_copy_rvc_cli_ctx(), gss_get_mic_kerberos(), gss_svc_upcall_handle_init(), gss_unwrap_bulk_kerberos(), gss_unwrap_kerberos(), gss_verify_mic_kerberos(), gss_wrap_bulk_kerberos(), gss_wrap_kerberos(), keyblock_free(), rsc_free(), and rsi_free().
int rawobj_from_netobj (rawobj_t * rawobj, netobj_t * netobj)
Definition at line 202 of file gss_rawobj.c.
References netobj_s::data, rawobj_s::data, netobj_s::len, and rawobj_s::len.
Referenced by gss_svc_accept().
int rawobj_from_netobj_alloc (rawobj_t * obj, netobj_t * netobj)
Definition at line 209 of file gss_rawobj.c.
References netobj_s::data, rawobj_s::data, netobj_s::len, rawobj_s::len, and OBD_ALLOC_LARGE.
int rawobj_serialize (rawobj_t * obj, __u32 ** buf, __u32 * buflen)
Definition at line 114 of file gss_rawobj.c.
References CERROR, cfs_size_round4(), cpu_to_le32, rawobj_s::data, LASSERT, and rawobj_s::len.
Referenced by ctx_init_pack_request().
static struct gss_sec* sec2gsec (struct ptlrpc_sec * sec) [static, read]
Definition at line 334 of file gss_internal.h.
References gss_sec::gs_base.
Referenced by ctx_init_pack_request(), gss_kt_update(), gss_sec_destroy_kr(), gss_sec_lookup_ctx_kr(), gss_svc_install_rctx_pf(), sec2gsec_keyring(), and sec2gsec_pipefs().
static struct gss_sec_keyring* sec2gsec_keyring (struct ptlrpc_sec * sec) [static, read]
Definition at line 344 of file gss_internal.h.
References gss_sec_keyring::gsk_base, and sec2gsec().
Referenced by ctx_enlist_kr(), ctx_unlist_kr(), flush_spec_ctx_cache_kr(), gss_sec_destroy_kr(), gss_sec_display_kr(), gss_sec_gc_ctx_kr(), gss_sec_lookup_ctx_kr(), rvs_sec_install_root_ctx_kr(), and sec_lookup_root_ctx_kr().
static struct gss_sec_pipefs* sec2gsec_pipefs (struct ptlrpc_sec * sec) [static, read]
Definition at line 339 of file gss_internal.h.
References gss_sec_pipefs::gsp_base, and sec2gsec().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.