Lustre: lustre/ptlrpc/gss/gss_generic_token.c File Reference
lustre/ptlrpc/gss/gss_generic_token.c File Reference
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/mutex.h>
#include <obd.h>
#include <obd_class.h>
#include <obd_support.h>
#include <lustre/lustre_idl.h>
#include <lustre_net.h>
#include <lustre_import.h>
#include <lustre_sec.h>
#include "gss_err.h"
#include "gss_internal.h"
#include "gss_api.h"
#include "gss_krb5.h"
#include "gss_asn1.h"
Defines
#define DEBUG_SUBSYSTEM S_SEC
#define TWRITE_STR(ptr, str, len)
Functions
static int der_length_size (int length)
static void der_write_length (unsigned char **buf, int length)
static int der_read_length (unsigned char **buf, int *bufsize)
int g_token_size (rawobj_t *mech, unsigned int body_size)
void g_make_token_header (rawobj_t *mech, int body_size, unsigned char **buf)
__u32 g_verify_token_header (rawobj_t *mech, int *body_size, unsigned char **buf_in, int toksize)
__u32 g_get_mech_oid (rawobj_t *mech, rawobj_t *in_buf)
Define Documentation
#define DEBUG_SUBSYSTEM S_SEC
Definition at line 44 of file gss_generic_token.c.
#define TWRITE_STR (ptr, str, len)
Value:
memcpy((ptr), (char *) (str), (len)); \
        (ptr) += (len);
Definition at line 66 of file gss_generic_token.c.
Referenced by g_make_token_header().
Function Documentation
static int der_length_size (int length) [static]
Definition at line 95 of file gss_generic_token.c.
Referenced by der_write_length(), and g_token_size().
static int der_read_length (unsigned char ** buf, int * bufsize) [static]
Definition at line 138 of file gss_generic_token.c.
References ret, and SIZEOF_INT.
Referenced by g_get_mech_oid(), and g_verify_token_header().
static void der_write_length (unsigned char ** buf, int length) [static]
Definition at line 115 of file gss_generic_token.c.
References der_length_size().
Referenced by g_make_token_header().
__u32 g_get_mech_oid (rawobj_t * mech, rawobj_t * in_buf)
Definition at line 253 of file gss_generic_token.c.
References buf, rawobj_s::data, der_read_length(), G_BAD_TOK_HEADER, G_BUFFER_ALLOC, rawobj_s::len, OBD_ALLOC_LARGE, and ret.
void g_make_token_header (rawobj_t * mech, int body_size, unsigned char ** buf)
Definition at line 178 of file gss_generic_token.c.
References rawobj_s::data, der_write_length(), rawobj_s::len, and TWRITE_STR.
int g_token_size (rawobj_t * mech, unsigned int body_size)
Definition at line 167 of file gss_generic_token.c.
References der_length_size(), and rawobj_s::len.
__u32 g_verify_token_header (rawobj_t * mech, int * body_size, unsigned char ** buf_in, int toksize)
Definition at line 195 of file gss_generic_token.c.
References buf, rawobj_s::data, der_read_length(), G_BAD_TOK_HEADER, g_OID_equal, G_WRONG_MECH, rawobj_s::len, and ret.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.