Lustre: lustre/ptlrpc/gss/gss_svc_upcall.c File Reference
lustre/ptlrpc/gss/gss_svc_upcall.c File Reference
#include <linux/types.h>
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/hash.h>
#include <linux/mutex.h>
#include <linux/sunrpc/cache.h>
#include <net/sock.h>
#include <obd.h>
#include <obd_class.h>
#include <obd_support.h>
#include <lustre/lustre_idl.h>
#include <lustre_net.h>
#include <lustre_import.h>
#include <lustre_sec.h>
#include "gss_err.h"
#include "gss_internal.h"
#include "gss_api.h"
Data Structures
struct rsi
struct rsc
Defines
#define DEBUG_SUBSYSTEM S_SEC
#define GSS_SVC_UPCALL_TIMEOUT (20)
#define RSI_HASHBITS (6)
#define RSI_HASHMAX (1 << RSI_HASHBITS)
#define RSI_HASHMASK (RSI_HASHMAX - 1)
#define RSC_HASHBITS (10)
#define RSC_HASHMAX (1 << RSC_HASHBITS)
#define RSC_HASHMASK (RSC_HASHMAX - 1)
#define COMPAT_RSC_PUT(item, cd) cache_put((item), (cd))
Typedefs
typedef int rsc_entry_match (struct rsc *rscp, long data)
Functions
__u64 gss_get_next_ctx_index (void)
static unsigned long hash_mem (char *buf, int length, int bits)
static int _cache_register_net (struct cache_detail *cd, struct net *net)
static void _cache_unregister_net (struct cache_detail *cd, struct net *net)
static struct rsi * rsi_update (struct rsi *new, struct rsi *old)
static struct rsi * rsi_lookup (struct rsi *item)
static int rsi_hash (struct rsi *item)
static int __rsi_match (struct rsi *item, struct rsi *tmp)
static void rsi_free (struct rsi *rsi)
static void rsi_request (struct cache_detail *cd, struct cache_head *h, char **bpp, int *blen)
static int rsi_upcall (struct cache_detail *cd, struct cache_head *h)
static void __rsi_init (struct rsi *new, struct rsi *item)
static void __rsi_update (struct rsi *new, struct rsi *item)
static void rsi_put (struct kref *ref)
static int rsi_match (struct cache_head *a, struct cache_head *b)
static void rsi_init (struct cache_head *cnew, struct cache_head *citem)
static void update_rsi (struct cache_head *cnew, struct cache_head *citem)
static struct cache_head * rsi_alloc (void)
static int rsi_parse (struct cache_detail *cd, char *mesg, int mlen)
static struct rsc * rsc_update (struct rsc *new, struct rsc *old)
static struct rsc * rsc_lookup (struct rsc *item)
static void rsc_free (struct rsc *rsci)
static int rsc_hash (struct rsc *rsci)
static int __rsc_match (struct rsc *new, struct rsc *tmp)
static void __rsc_init (struct rsc *new, struct rsc *tmp)
static void __rsc_update (struct rsc *new, struct rsc *tmp)
static void rsc_put (struct kref *ref)
static int rsc_match (struct cache_head *a, struct cache_head *b)
static void rsc_init (struct cache_head *cnew, struct cache_head *ctmp)
static void update_rsc (struct cache_head *cnew, struct cache_head *ctmp)
static struct cache_head * rsc_alloc (void)
static int rsc_parse (struct cache_detail *cd, char *mesg, int mlen)
static void rsc_flush (rsc_entry_match *match, long data)
static int match_uid (struct rsc *rscp, long uid)
static int match_target (struct rsc *rscp, long target)
static void rsc_flush_uid (int uid)
static void rsc_flush_target (struct obd_device *target)
void gss_secsvc_flush (struct obd_device *target)
static struct rsc * gss_svc_searchbyctx (rawobj_t *handle)
int gss_svc_upcall_install_rvs_ctx (struct obd_import *imp, struct gss_sec *gsec, struct gss_cli_ctx *gctx)
int gss_svc_upcall_expire_rvs_ctx (rawobj_t *handle)
int gss_svc_upcall_dup_handle (rawobj_t *handle, struct gss_svc_ctx *ctx)
int gss_svc_upcall_update_sequence (rawobj_t *handle, __u32 seq)
static struct cache_deferred_req * cache_upcall_defer (struct cache_req *req)
int gss_svc_upcall_handle_init (struct ptlrpc_request *req, struct gss_svc_reqctx *grctx, struct gss_wire_ctx *gw, struct obd_device *target, __u32 lustre_svc, rawobj_t *rvs_hdl, rawobj_t *in_token)
struct gss_svc_ctx * gss_svc_upcall_get_ctx (struct ptlrpc_request *req, struct gss_wire_ctx *gw)
void gss_svc_upcall_put_ctx (struct gss_svc_ctx *ctx)
void gss_svc_upcall_destroy_ctx (struct gss_svc_ctx *ctx)
int __init gss_init_svc_upcall (void)
void gss_exit_svc_upcall (void)
Variables
static spinlock_t __ctx_index_lock
static __u64 __ctx_index
static struct cache_head * rsi_table [RSI_HASHMAX]
static struct cache_detail rsi_cache
static struct cache_head * rsc_table [RSC_HASHMAX]
static struct cache_detail rsc_cache
static struct cache_req cache_upcall_chandle = { cache_upcall_defer }
Define Documentation
#define COMPAT_RSC_PUT (item, cd) cache_put((item), (cd))
Definition at line 702 of file gss_svc_upcall.c.
Referenced by gss_svc_upcall_expire_rvs_ctx(), gss_svc_upcall_handle_init(), gss_svc_upcall_put_ctx(), gss_svc_upcall_update_sequence(), and rsc_flush().
#define DEBUG_SUBSYSTEM S_SEC
Definition at line 50 of file gss_svc_upcall.c.
#define GSS_SVC_UPCALL_TIMEOUT (20)
Definition at line 72 of file gss_svc_upcall.c.
Referenced by gss_svc_upcall_handle_init().
#define RSC_HASHBITS (10)
Definition at line 430 of file gss_svc_upcall.c.
Referenced by rsc_hash().
#define RSC_HASHMASK (RSC_HASHMAX - 1)
Definition at line 432 of file gss_svc_upcall.c.
#define RSC_HASHMAX (1 << RSC_HASHBITS)
Definition at line 431 of file gss_svc_upcall.c.
Referenced by rsc_flush().
#define RSI_HASHBITS (6)
Definition at line 138 of file gss_svc_upcall.c.
Referenced by rsi_hash().
#define RSI_HASHMASK (RSI_HASHMAX - 1)
Definition at line 140 of file gss_svc_upcall.c.
#define RSI_HASHMAX (1 << RSI_HASHBITS)
Definition at line 139 of file gss_svc_upcall.c.
Typedef Documentation
typedef int rsc_entry_match(struct rsc *rscp, long data)
Definition at line 708 of file gss_svc_upcall.c.
Function Documentation
static void __rsc_init (struct rsc * new, struct rsc * tmp) [inline, static]
Definition at line 468 of file gss_svc_upcall.c.
References rsc::handle, and RAWOBJ_EMPTY.
Referenced by rsc_init().
static int __rsc_match (struct rsc * new, struct rsc * tmp) [inline, static]
Definition at line 463 of file gss_svc_upcall.c.
References rsc::handle, and rawobj_equal().
Referenced by rsc_match().
static void __rsc_update (struct rsc * new, struct rsc * tmp) [inline, static]
Definition at line 478 of file gss_svc_upcall.c.
References rsc::ctx, gss_svc_ctx::gsc_mechctx, gss_svc_ctx::gsc_rvs_hdl, and RAWOBJ_EMPTY.
Referenced by update_rsc().
static void __rsi_init (struct rsi * new, struct rsi * item) [inline, static]
Definition at line 216 of file gss_svc_upcall.c.
References rsi::in_handle, rsi::in_token, rsi::lustre_svc, rsi::nid, and RAWOBJ_EMPTY.
Referenced by rsi_init().
static int __rsi_match (struct rsi * item, struct rsi * tmp) [inline, static]
Definition at line 169 of file gss_svc_upcall.c.
References rsi::in_handle, rsi::in_token, and rawobj_equal().
Referenced by rsi_match().
static void __rsi_update (struct rsi * new, struct rsi * item) [inline, static]
Definition at line 231 of file gss_svc_upcall.c.
References LASSERT, rsi::major_status, rsi::minor_status, rsi::out_handle, rsi::out_token, and RAWOBJ_EMPTY.
Referenced by update_rsi().
static int _cache_register_net (struct cache_detail * cd, struct net * net) [inline, static]
Definition at line 117 of file gss_svc_upcall.c.
Referenced by gss_init_svc_upcall().
static void _cache_unregister_net (struct cache_detail * cd, struct net * net) [inline, static]
Definition at line 125 of file gss_svc_upcall.c.
Referenced by gss_exit_svc_upcall(), and gss_init_svc_upcall().
static struct cache_deferred_req* cache_upcall_defer (struct cache_req * req) [static, read]
Definition at line 902 of file gss_svc_upcall.c.
void gss_exit_svc_upcall (void)
Definition at line 1167 of file gss_svc_upcall.c.
References _cache_unregister_net(), rsc_cache, and rsi_cache.
Referenced by sptlrpc_gss_exit(), and sptlrpc_gss_init().
__u64 gss_get_next_ctx_index (void)
Definition at line 77 of file gss_svc_upcall.c.
References __ctx_index, __ctx_index_lock, and __u64.
Referenced by gss_cli_ctx_refresh_pf(), gss_sec_lookup_ctx_kr(), and rsi_request().
int __init gss_init_svc_upcall (void)
Definition at line 1124 of file gss_svc_upcall.c.
References __ctx_index, __ctx_index_lock, _cache_register_net(), _cache_unregister_net(), cfs_get_random_bytes(), CWARN, LASSERT, rsc_cache, and rsi_cache.
Referenced by sptlrpc_gss_init().
void gss_secsvc_flush (struct obd_device * target)
Definition at line 782 of file gss_svc_upcall.c.
References rsc_flush_target().
static struct rsc* gss_svc_searchbyctx (rawobj_t * handle) [static, read]
Definition at line 787 of file gss_svc_upcall.c.
References rsc::h, rsc::handle, rawobj_dup(), rsc_cache, rsc_free(), and rsc_lookup().
Referenced by gss_svc_upcall_expire_rvs_ctx(), gss_svc_upcall_get_ctx(), gss_svc_upcall_handle_init(), and gss_svc_upcall_update_sequence().
void gss_svc_upcall_destroy_ctx (struct gss_svc_ctx * ctx)
Definition at line 1114 of file gss_svc_upcall.c.
References rsc::h.
Referenced by gss_svc_handle_destroy(), and gss_svc_invalidate_ctx().
int gss_svc_upcall_dup_handle (rawobj_t * handle, struct gss_svc_ctx * ctx)
Definition at line 880 of file gss_svc_upcall.c.
References rsc::handle, and rawobj_dup().
Referenced by gss_copy_rvc_cli_ctx().
int gss_svc_upcall_expire_rvs_ctx (rawobj_t * handle)
Definition at line 864 of file gss_svc_upcall.c.
References CDEBUG, cfs_time_current_sec(), COMPAT_RSC_PUT, rsc::ctx, D_SEC, gss_svc_searchbyctx(), rsc::h, and rsc_cache.
Referenced by gss_cli_ctx_finalize().
struct gss_svc_ctx* gss_svc_upcall_get_ctx (struct ptlrpc_request * req, struct gss_wire_ctx * gw) [read]
Definition at line 1091 of file gss_svc_upcall.c.
References rsc::ctx, CWARN, gss_handle_to_u64(), gss_svc_searchbyctx(), gss_wire_ctx::gw_handle, libcfs_nid2str(), LPX64, lnet_process_id_t::nid, and ptlrpc_request::rq_peer.
Referenced by gss_svc_handle_data(), and gss_svc_handle_destroy().
int gss_svc_upcall_handle_init (struct ptlrpc_request * req, struct gss_svc_reqctx * grctx, struct gss_wire_ctx * gw, struct obd_device * target, __u32 lustre_svc, rawobj_t * rvs_hdl, rawobj_t * in_token)
Definition at line 908 of file gss_svc_upcall.c.
References __u64, CDEBUG, CERROR, cfs_size_round4(), COMPAT_RSC_PUT, rsc::ctx, CWARN, D_SEC, rawobj_s::data, netobj_s::data, ENTRY, gss_rep_header::gh_flags, gss_rep_header::gh_handle, gss_rep_header::gh_major, gss_rep_header::gh_minor, gss_rep_header::gh_proc, gss_rep_header::gh_seqwin, gss_rep_header::gh_version, GOTO, gss_svc_ctx::gsc_rvs_hdl, gss_svc_ctx::gsc_uid, gss_handle_to_u64(), gss_pack_err_notify(), GSS_S_FAILURE, GSS_SEQ_WIN, gss_svc_searchbyctx(), GSS_SVC_UPCALL_TIMEOUT, gss_wire_ctx::gw_handle, rsc::h, rsi::h, rsc::handle, LASSERT, netobj_s::len, rawobj_s::len, libcfs_nid2str(), LPX64, lustre_msg_buf(), lustre_pack_reply_v2(), lustre_shrink_msg(), rsi::major_status, rsi::minor_status, lnet_process_id_t::nid, rsi::out_handle, rsi::out_token, ptlrpc_body, PTLRPC_GSS_MAX_HANDLE_SIZE, PTLRPC_GSS_PROC_ERR, PTLRPC_GSS_VERSION, rawobj_dup(), rawobj_free(), RETURN, ptlrpc_request::rq_peer, ptlrpc_reply_state::rs_repbuf, ptlrpc_reply_state::rs_repdata_len, rsc_cache, rsi_cache, rsi_free(), rsi_lookup(), rsi_put(), SECSVC_COMPLETE, SECSVC_DROP, SECSVC_OK, gss_svc_reqctx::src_ctx, gss_svc_reqctx::src_init, gss_svc_reqctx::src_reserve_len, rsc::target, and rsi::waitq.
Referenced by gss_svc_handle_init().
int gss_svc_upcall_install_rvs_ctx (struct obd_import * imp, struct gss_sec * gsec, struct gss_cli_ctx * gctx)
Definition at line 805 of file gss_svc_upcall.c.
References CERROR, rsc::ctx, CWARN, ENTRY, gss_cli_ctx::gc_mechctx, gss_cli_ctx::gc_svc_handle, GOTO, gss_sec::gs_rvs_hdl, gss_svc_ctx::gsc_mechctx, gss_svc_ctx::gsc_usr_mds, gss_svc_ctx::gsc_usr_oss, gss_svc_ctx::gsc_usr_root, GSS_S_COMPLETE, rsc::h, rsc::handle, obd_import::imp_obd, lgss_copy_reverse_context(), lgss_inquire_context(), LPX64, LUSTRE_MDC_NAME, LUSTRE_OSC_NAME, obd2cli_tgt, obd_device::obd_type, rawobj_alloc(), rawobj_dup(), RETURN, rsc_cache, rsc_free(), rsc_lookup(), rsc_update(), rsc::target, and obd_type::typ_name.
Referenced by gss_install_rvs_svc_ctx().
void gss_svc_upcall_put_ctx (struct gss_svc_ctx * ctx)
Definition at line 1107 of file gss_svc_upcall.c.
References COMPAT_RSC_PUT, rsc::h, and rsc_cache.
Referenced by gss_svc_reqctx_free().
int gss_svc_upcall_update_sequence (rawobj_t * handle, __u32 seq)
Definition at line 887 of file gss_svc_upcall.c.
References CDEBUG, COMPAT_RSC_PUT, rsc::ctx, D_SEC, gss_svc_ctx::gsc_rvs_seq, gss_svc_searchbyctx(), rsc::h, and rsc_cache.
Referenced by dispose_ctx_list_kr().
static unsigned long hash_mem (char * buf, int length, int bits) [inline, static]
Definition at line 88 of file gss_svc_upcall.c.
Referenced by rsc_hash(), and rsi_hash().
static int match_target (struct rsc * rscp, long target) [static]
Definition at line 764 of file gss_svc_upcall.c.
References rsc::target.
Referenced by rsc_flush_target().
static int match_uid (struct rsc * rscp, long uid) [static]
Definition at line 757 of file gss_svc_upcall.c.
References rsc::ctx, and gss_svc_ctx::gsc_uid.
Referenced by rsc_flush_uid().
static struct cache_head* rsc_alloc (void) [static, read]
Definition at line 525 of file gss_svc_upcall.c.
References rsc::h, and OBD_ALLOC_PTR.
static void rsc_flush (rsc_entry_match * match, long data) [static]
Definition at line 710 of file gss_svc_upcall.c.
References COMPAT_RSC_PUT, ENTRY, EXIT, rsc::h, head, hlist_del_init(), hlist_for_each_entry, rsc_cache, and RSC_HASHMAX.
Referenced by rsc_flush_target(), and rsc_flush_uid().
static void rsc_flush_target (struct obd_device * target) [inline, static]
Definition at line 777 of file gss_svc_upcall.c.
References match_target(), and rsc_flush().
Referenced by gss_secsvc_flush().
static void rsc_flush_uid (int uid) [inline, static]
Definition at line 769 of file gss_svc_upcall.c.
References CWARN, match_uid(), and rsc_flush().
static void rsc_free (struct rsc * rsci) [static]
Definition at line 450 of file gss_svc_upcall.c.
References rsc::ctx, gss_svc_ctx::gsc_mechctx, gss_svc_ctx::gsc_rvs_hdl, rsc::handle, lgss_delete_sec_context(), and rawobj_free().
Referenced by gss_svc_searchbyctx(), gss_svc_upcall_install_rvs_ctx(), rsc_parse(), and rsc_put().
static int rsc_hash (struct rsc * rsci) [inline, static]
Definition at line 457 of file gss_svc_upcall.c.
References rawobj_s::data, rsc::handle, hash_mem(), rawobj_s::len, and RSC_HASHBITS.
Referenced by rsc_lookup(), and rsc_update().
static void rsc_init (struct cache_head * cnew, struct cache_head * ctmp) [static]
Definition at line 509 of file gss_svc_upcall.c.
References __rsc_init(), and rsc::h.
static struct rsc * rsc_lookup (struct rsc * item) [static, read]
Definition at line 678 of file gss_svc_upcall.c.
References rsc::h, rsc_cache, and rsc_hash().
Referenced by gss_svc_searchbyctx(), gss_svc_upcall_install_rvs_ctx(), and rsc_parse().
static int rsc_match (struct cache_head * a, struct cache_head * b) [static]
Definition at line 501 of file gss_svc_upcall.c.
References __rsc_match(), and rsc::h.
static int rsc_parse (struct cache_detail * cd, char * mesg, int mlen) [static]
Definition at line 536 of file gss_svc_upcall.c.
References buf, CERROR, rsc::ctx, rawobj_s::data, gss_svc_ctx::gsc_gid, gss_svc_ctx::gsc_mapped_uid, gss_svc_ctx::gsc_mechctx, gss_svc_ctx::gsc_remote, gss_svc_ctx::gsc_uid, gss_svc_ctx::gsc_usr_mds, gss_svc_ctx::gsc_usr_oss, gss_svc_ctx::gsc_usr_root, rsc::h, rsc::handle, rawobj_s::len, lgss_import_sec_context(), lgss_inquire_context(), lgss_mech_put(), lgss_name_to_mech(), qword_get(), rawobj_alloc(), rsc_cache, rsc_free(), rsc_lookup(), rsc_update(), status, and tmp_buf.
static void rsc_put (struct kref * ref) [static]
Definition at line 488 of file gss_svc_upcall.c.
References rsc::h, LASSERT, OBD_FREE_PTR, and rsc_free().
static struct rsc * rsc_update (struct rsc * new, struct rsc * old) [static, read]
Definition at line 690 of file gss_svc_upcall.c.
References rsc::h, rsc_cache, and rsc_hash().
Referenced by gss_svc_upcall_install_rvs_ctx(), and rsc_parse().
static struct cache_head* rsi_alloc (void) [static, read]
Definition at line 282 of file gss_svc_upcall.c.
References rsi::h, and OBD_ALLOC_PTR.
static void rsi_free (struct rsi * rsi) [static]
Definition at line 175 of file gss_svc_upcall.c.
References rsi::in_handle, rsi::in_token, rsi::out_handle, rsi::out_token, and rawobj_free().
Referenced by gss_svc_upcall_handle_init(), rsi_parse(), and rsi_put().
static int rsi_hash (struct rsi * item) [inline, static]
Definition at line 161 of file gss_svc_upcall.c.
References rawobj_s::data, hash_mem(), rsi::in_handle, rsi::in_token, rawobj_s::len, and RSI_HASHBITS.
Referenced by rsi_lookup(), and rsi_update().
static void rsi_init (struct cache_head * cnew, struct cache_head * citem) [static]
Definition at line 266 of file gss_svc_upcall.c.
References __rsi_init(), and rsi::h.
static struct rsi * rsi_lookup (struct rsi * item) [static, read]
Definition at line 402 of file gss_svc_upcall.c.
References rsi::h, rsi_cache, and rsi_hash().
Referenced by gss_svc_upcall_handle_init(), and rsi_parse().
static int rsi_match (struct cache_head * a, struct cache_head * b) [static]
Definition at line 258 of file gss_svc_upcall.c.
References __rsi_match(), and rsi::h.
static int rsi_parse (struct cache_detail * cd, char * mesg, int mlen) [static]
Definition at line 293 of file gss_svc_upcall.c.
References buf, CERROR, ENTRY, rsi::h, rsi::in_handle, rsi::in_token, rsi::major_status, rsi::minor_status, rsi::out_handle, rsi::out_token, qword_get(), rawobj_alloc(), RETURN, rsi_cache, rsi_free(), rsi_lookup(), rsi_update(), status, and rsi::waitq.
static void rsi_put (struct kref * ref) [static]
Definition at line 245 of file gss_svc_upcall.c.
References rsi::h, LASSERT, OBD_FREE_PTR, and rsi_free().
Referenced by gss_svc_upcall_handle_init().
static void rsi_request (struct cache_detail * cd, struct cache_head * h, char ** bpp, int * blen) [static]
Definition at line 183 of file gss_svc_upcall.c.
References __u64, rawobj_s::data, gss_get_next_ctx_index(), rsi::in_handle, rsi::in_token, rawobj_s::len, rsi::lustre_svc, rsi::nid, and qword_addhex().
static int rsi_upcall (struct cache_detail * cd, struct cache_head * h) [static]
Definition at line 210 of file gss_svc_upcall.c.
static struct rsi * rsi_update (struct rsi * new, struct rsi * old) [static, read]
Definition at line 414 of file gss_svc_upcall.c.
References rsi::h, rsi_cache, and rsi_hash().
Referenced by rsi_parse().
static void update_rsc (struct cache_head * cnew, struct cache_head * ctmp) [static]
Definition at line 517 of file gss_svc_upcall.c.
References __rsc_update(), and rsc::h.
static void update_rsi (struct cache_head * cnew, struct cache_head * citem) [static]
Definition at line 274 of file gss_svc_upcall.c.
References __rsi_update(), and rsi::h.
Variable Documentation
__u64 __ctx_index [static]
Definition at line 75 of file gss_svc_upcall.c.
Referenced by gss_get_next_ctx_index(), and gss_init_svc_upcall().
spinlock_t __ctx_index_lock [static]
Definition at line 74 of file gss_svc_upcall.c.
Referenced by gss_get_next_ctx_index(), and gss_init_svc_upcall().
struct cache_req cache_upcall_chandle = { cache_upcall_defer } [static]
Definition at line 906 of file gss_svc_upcall.c.
static struct cache_detail rsc_cache [static, read]
Initial value:
 {
        .hash_size      = RSC_HASHMAX,
        .hash_table     = rsc_table,
        .name           = "auth.sptlrpc.context",
        .cache_put      = rsc_put,
        .cache_parse    = rsc_parse,
        .match          = rsc_match,
        .init           = rsc_init,
        .update         = update_rsc,
        .alloc          = rsc_alloc,
}
Definition at line 446 of file gss_svc_upcall.c.
Referenced by gss_exit_svc_upcall(), gss_init_svc_upcall(), gss_svc_searchbyctx(), gss_svc_upcall_expire_rvs_ctx(), gss_svc_upcall_handle_init(), gss_svc_upcall_install_rvs_ctx(), gss_svc_upcall_put_ctx(), gss_svc_upcall_update_sequence(), rsc_flush(), rsc_lookup(), rsc_parse(), and rsc_update().
struct cache_head* rsc_table[RSC_HASHMAX] [static]
Definition at line 444 of file gss_svc_upcall.c.
static struct cache_detail rsi_cache [static, read]
Initial value:
 {
        .hash_size      = RSI_HASHMAX,
        .hash_table     = rsi_table,
        .name           = "auth.sptlrpc.init",
        .cache_put      = rsi_put,
        .cache_request  = rsi_request,
        .cache_upcall   = rsi_upcall,
        .cache_parse    = rsi_parse,
        .match          = rsi_match,
        .init           = rsi_init,
        .update         = update_rsi,
        .alloc          = rsi_alloc,
}
Definition at line 157 of file gss_svc_upcall.c.
Referenced by gss_exit_svc_upcall(), gss_init_svc_upcall(), gss_svc_upcall_handle_init(), rsi_lookup(), rsi_parse(), and rsi_update().
struct cache_head* rsi_table[RSI_HASHMAX] [static]
Definition at line 155 of file gss_svc_upcall.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.