Lustre: lustre/ptlrpc/gss/gss_krb5_mech.c File Reference
lustre/ptlrpc/gss/gss_krb5_mech.c File Reference
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/crypto.h>
#include <linux/mutex.h>
#include <obd.h>
#include <obd_class.h>
#include <obd_support.h>
#include <lustre/lustre_idl.h>
#include <lustre_net.h>
#include <lustre_import.h>
#include <lustre_sec.h>
#include "gss_err.h"
#include "gss_internal.h"
#include "gss_api.h"
#include "gss_asn1.h"
#include "gss_krb5.h"
Data Structures
struct krb5_enctype
Defines
#define DEBUG_SUBSYSTEM S_SEC
#define MAX_ENCTYPES sizeof(enctypes)/sizeof(struct krb5_enctype)
#define KRB5_CTX_FLAG_INITIATOR 0x00000001
#define KRB5_CTX_FLAG_CFX 0x00000002
#define KRB5_CTX_FLAG_ACCEPTOR_SUBKEY 0x00000004
Functions
static const char * enctype2str (__u32 enctype)
static int keyblock_init (struct krb5_keyblock *kb, char *alg_name, int alg_mode)
static int krb5_init_keys (struct krb5_ctx *kctx)
static void keyblock_free (struct krb5_keyblock *kb)
static int keyblock_dup (struct krb5_keyblock *new, struct krb5_keyblock *kb)
static int get_bytes (char **ptr, const char *end, void *res, int len)
static int get_rawobj (char **ptr, const char *end, rawobj_t *res)
static int get_keyblock (char **ptr, const char *end, struct krb5_keyblock *kb, __u32 keysize)
static void delete_context_kerberos (struct krb5_ctx *kctx)
static __u32 import_context_rfc1964 (struct krb5_ctx *kctx, char *p, char *end)
static __u32 import_context_rfc4121 (struct krb5_ctx *kctx, char *p, char *end)
static __u32 gss_import_sec_context_kerberos (rawobj_t *inbuf, struct gss_ctx *gctx)
static __u32 gss_copy_reverse_context_kerberos (struct gss_ctx *gctx, struct gss_ctx *gctx_new)
static __u32 gss_inquire_context_kerberos (struct gss_ctx *gctx, unsigned long *endtime)
static void gss_delete_sec_context_kerberos (void *internal_ctx)
static int setup_sgtable (struct sg_table *sgt, struct scatterlist *prealloc_sg, const void *buf, unsigned int buf_len)
static void teardown_sgtable (struct sg_table *sgt)
static __u32 krb5_encrypt (struct crypto_blkcipher *tfm, int decrypt, void *iv, void *in, void *out, int length)
static int krb5_digest_hmac (struct crypto_hash *tfm, rawobj_t *key, struct krb5_header *khdr, int msgcnt, rawobj_t *msgs, int iovcnt, lnet_kiov_t *iovs, rawobj_t *cksum)
static int krb5_digest_norm (struct crypto_hash *tfm, struct krb5_keyblock *kb, struct krb5_header *khdr, int msgcnt, rawobj_t *msgs, int iovcnt, lnet_kiov_t *iovs, rawobj_t *cksum)
static __s32 krb5_make_checksum (__u32 enctype, struct krb5_keyblock *kb, struct krb5_header *khdr, int msgcnt, rawobj_t *msgs, int iovcnt, lnet_kiov_t *iovs, rawobj_t *cksum)
static void fill_krb5_header (struct krb5_ctx *kctx, struct krb5_header *khdr, int privacy)
static __u32 verify_krb5_header (struct krb5_ctx *kctx, struct krb5_header *khdr, int privacy)
static __u32 gss_get_mic_kerberos (struct gss_ctx *gctx, int msgcnt, rawobj_t *msgs, int iovcnt, lnet_kiov_t *iovs, rawobj_t *token)
static __u32 gss_verify_mic_kerberos (struct gss_ctx *gctx, int msgcnt, rawobj_t *msgs, int iovcnt, lnet_kiov_t *iovs, rawobj_t *token)
static int add_padding (rawobj_t *msg, int msg_buflen, int blocksize)
static int krb5_encrypt_rawobjs (struct crypto_blkcipher *tfm, int mode_ecb, int inobj_cnt, rawobj_t *inobjs, rawobj_t *outobj, int enc)
static int krb5_encrypt_bulk (struct crypto_blkcipher *tfm, struct krb5_header *khdr, char *confounder, struct ptlrpc_bulk_desc *desc, rawobj_t *cipher, int adj_nob)
static int krb5_decrypt_bulk (struct crypto_blkcipher *tfm, struct krb5_header *khdr, struct ptlrpc_bulk_desc *desc, rawobj_t *cipher, rawobj_t *plain, int adj_nob)
static __u32 gss_wrap_kerberos (struct gss_ctx *gctx, rawobj_t *gsshdr, rawobj_t *msg, int msg_buflen, rawobj_t *token)
static __u32 gss_prep_bulk_kerberos (struct gss_ctx *gctx, struct ptlrpc_bulk_desc *desc)
static __u32 gss_wrap_bulk_kerberos (struct gss_ctx *gctx, struct ptlrpc_bulk_desc *desc, rawobj_t *token, int adj_nob)
static __u32 gss_unwrap_kerberos (struct gss_ctx *gctx, rawobj_t *gsshdr, rawobj_t *token, rawobj_t *msg)
static __u32 gss_unwrap_bulk_kerberos (struct gss_ctx *gctx, struct ptlrpc_bulk_desc *desc, rawobj_t *token, int adj_nob)
int gss_display_kerberos (struct gss_ctx *ctx, char *buf, int bufsize)
int __init init_kerberos_module (void)
void cleanup_kerberos_module (void)
Variables
static spinlock_t krb5_seq_lock
static struct krb5_enctype enctypes []
static struct gss_api_ops gss_kerberos_ops
static struct subflavor_desc gss_kerberos_sfs []
static struct gss_api_mech gss_kerberos_mech
Define Documentation
#define DEBUG_SUBSYSTEM S_SEC
Definition at line 51 of file gss_krb5_mech.c.
#define KRB5_CTX_FLAG_ACCEPTOR_SUBKEY 0x00000004
Definition at line 353 of file gss_krb5_mech.c.
Referenced by import_context_rfc4121().
#define KRB5_CTX_FLAG_CFX 0x00000002
Definition at line 352 of file gss_krb5_mech.c.
Referenced by import_context_rfc4121().
#define KRB5_CTX_FLAG_INITIATOR 0x00000001
Definition at line 351 of file gss_krb5_mech.c.
Referenced by import_context_rfc4121().
#define MAX_ENCTYPES sizeof(enctypes)/sizeof(struct krb5_enctype)
Definition at line 137 of file gss_krb5_mech.c.
Referenced by enctype2str(), and krb5_init_keys().
Function Documentation
static int add_padding (rawobj_t * msg, int msg_buflen, int blocksize) [static]
Definition at line 956 of file gss_krb5_mech.c.
References CERROR, rawobj_s::data, and rawobj_s::len.
Referenced by gss_wrap_kerberos().
void cleanup_kerberos_module (void)
Definition at line 1972 of file gss_krb5_mech.c.
References lgss_mech_unregister().
Referenced by sptlrpc_gss_exit(), and sptlrpc_gss_init().
static void delete_context_kerberos (struct krb5_ctx * kctx) [static]
Definition at line 267 of file gss_krb5_mech.c.
References krb5_ctx::kc_keyc, krb5_ctx::kc_keye, krb5_ctx::kc_keyi, krb5_ctx::kc_mech_used, keyblock_free(), and rawobj_free().
Referenced by gss_copy_reverse_context_kerberos(), gss_delete_sec_context_kerberos(), and gss_import_sec_context_kerberos().
static const char* enctype2str (__u32 enctype) [static]
Definition at line 139 of file gss_krb5_mech.c.
References krb5_enctype::ke_dispname, and MAX_ENCTYPES.
Referenced by gss_display_kerberos().
static void fill_krb5_header (struct krb5_ctx * kctx, struct krb5_header * khdr, int privacy) [static]
Definition at line 803 of file gss_krb5_mech.c.
References cpu_to_be16, cpu_to_be64, FLAG_SENDER_IS_ACCEPTOR, FLAG_WRAP_CONFIDENTIAL, krb5_ctx::kc_initiate, krb5_ctx::kc_seq_send, KG_TOK_MIC_MSG, KG_TOK_WRAP_MSG, krb5_header::kh_ec, krb5_header::kh_filler, krb5_header::kh_flags, krb5_header::kh_rrc, krb5_header::kh_seq, krb5_header::kh_tok_id, and krb5_seq_lock.
Referenced by gss_get_mic_kerberos(), gss_wrap_bulk_kerberos(), and gss_wrap_kerberos().
static int get_bytes (char ** ptr, const char * end, void * res, int len) [static]
Definition at line 210 of file gss_krb5_mech.c.
Referenced by get_keyblock(), get_rawobj(), gss_import_sec_context_kerberos(), import_context_rfc1964(), and import_context_rfc4121().
static int get_keyblock (char ** ptr, const char * end, struct krb5_keyblock * kb, __u32 keysize) [static]
Definition at line 247 of file gss_krb5_mech.c.
References buf, rawobj_s::data, get_bytes(), krb5_keyblock::kb_key, rawobj_s::len, OBD_ALLOC_LARGE, and OBD_FREE_LARGE.
Referenced by import_context_rfc1964(), and import_context_rfc4121().
static int get_rawobj (char ** ptr, const char * end, rawobj_t * res) [static]
Definition at line 223 of file gss_krb5_mech.c.
References rawobj_s::data, get_bytes(), rawobj_s::len, and OBD_ALLOC_LARGE.
Referenced by import_context_rfc1964().
static __u32 gss_copy_reverse_context_kerberos (struct gss_ctx * gctx, struct gss_ctx * gctx_new) [static]
Definition at line 463 of file gss_krb5_mech.c.
References CDEBUG, D_SEC, delete_context_kerberos(), GSS_S_COMPLETE, GSS_S_FAILURE, gss_ctx::internal_ctx_id, krb5_ctx::kc_cfx, krb5_ctx::kc_enctype, krb5_ctx::kc_endtime, krb5_ctx::kc_have_acceptor_subkey, krb5_ctx::kc_initiate, krb5_ctx::kc_keyc, krb5_ctx::kc_keye, krb5_ctx::kc_keyi, krb5_ctx::kc_mech_used, krb5_ctx::kc_seed, krb5_ctx::kc_seed_init, krb5_ctx::kc_seq_recv, krb5_ctx::kc_seq_send, keyblock_dup(), krb5_init_keys(), OBD_ALLOC_PTR, OBD_FREE_PTR, and rawobj_dup().
static void gss_delete_sec_context_kerberos (void * internal_ctx) [static]
Definition at line 517 of file gss_krb5_mech.c.
References delete_context_kerberos(), and OBD_FREE_PTR.
int gss_display_kerberos (struct gss_ctx * ctx, char * buf, int bufsize)
Definition at line 1893 of file gss_krb5_mech.c.
References enctype2str(), gss_ctx::internal_ctx_id, and krb5_ctx::kc_enctype.
static __u32 gss_get_mic_kerberos (struct gss_ctx * gctx, int msgcnt, rawobj_t * msgs, int iovcnt, lnet_kiov_t * iovs, rawobj_t * token) [static]
Definition at line 872 of file gss_krb5_mech.c.
References cksum, rawobj_s::data, fill_krb5_header(), GSS_S_COMPLETE, GSS_S_FAILURE, gss_ctx::internal_ctx_id, krb5_ctx::kc_enctype, krb5_ctx::kc_keyc, krb5_enctype::ke_hash_size, krb5_make_checksum(), LASSERT, rawobj_s::len, RAWOBJ_EMPTY, and rawobj_free().
static __u32 gss_import_sec_context_kerberos (rawobj_t * inbuf, struct gss_ctx * gctx) [static]
Definition at line 418 of file gss_krb5_mech.c.
References CERROR, rawobj_s::data, delete_context_kerberos(), end, get_bytes(), GSS_S_COMPLETE, GSS_S_FAILURE, import_context_rfc1964(), import_context_rfc4121(), gss_ctx::internal_ctx_id, krb5_ctx::kc_initiate, krb5_init_keys(), rawobj_s::len, OBD_ALLOC_PTR, and OBD_FREE_PTR.
static __u32 gss_inquire_context_kerberos (struct gss_ctx * gctx, unsigned long * endtime) [static]
Definition at line 507 of file gss_krb5_mech.c.
References GSS_S_COMPLETE, gss_ctx::internal_ctx_id, and krb5_ctx::kc_endtime.
static __u32 gss_prep_bulk_kerberos (struct gss_ctx * gctx, struct ptlrpc_bulk_desc * desc) [static]
Definition at line 1486 of file gss_krb5_mech.c.
References BD_GET_ENC_KIOV, BD_GET_KIOV, ptlrpc_bulk_desc::bd_iov_count, ptlrpc_bulk_desc::bd_type, blocksize(), CERROR, GET_ENC_KIOV, GSS_S_COMPLETE, GSS_S_FAILURE, gss_ctx::internal_ctx_id, krb5_keyblock::kb_tfm, krb5_ctx::kc_keye, LASSERT, and ptlrpc_is_bulk_desc_kiov().
static __u32 gss_unwrap_bulk_kerberos (struct gss_ctx * gctx, struct ptlrpc_bulk_desc * desc, rawobj_t * token, int adj_nob) [static]
Definition at line 1801 of file gss_krb5_mech.c.
References ptlrpc_bulk_desc::bd_iov_count, ptlrpc_bulk_desc::bd_type, blocksize(), CERROR, cksum, rawobj_s::data, ENCTYPE_ARCFOUR_HMAC, GET_KIOV, GSS_S_BAD_SIG, GSS_S_COMPLETE, GSS_S_DEFECTIVE_TOKEN, GSS_S_FAILURE, gss_ctx::internal_ctx_id, krb5_keyblock::kb_tfm, krb5_ctx::kc_enctype, krb5_ctx::kc_keye, krb5_ctx::kc_keyi, krb5_enctype::ke_hash_size, krb5_decrypt_bulk(), krb5_make_checksum(), LASSERT, LBUG, rawobj_s::len, ptlrpc_is_bulk_desc_kiov(), RAWOBJ_EMPTY, rawobj_free(), and verify_krb5_header().
static __u32 gss_unwrap_kerberos (struct gss_ctx * gctx, rawobj_t * gsshdr, rawobj_t * token, rawobj_t * msg) [static]
Definition at line 1634 of file gss_krb5_mech.c.
References blocksize(), CERROR, cksum, rawobj_s::data, ENCTYPE_ARCFOUR_HMAC, GOTO, GSS_S_COMPLETE, GSS_S_DEFECTIVE_TOKEN, GSS_S_FAILURE, gss_ctx::internal_ctx_id, krb5_keyblock::kb_tfm, krb5_ctx::kc_enctype, krb5_ctx::kc_keye, krb5_ctx::kc_keyi, krb5_enctype::ke_conf_size, krb5_enctype::ke_hash_size, krb5_encrypt_rawobjs(), krb5_make_checksum(), LASSERT, rawobj_s::len, OBD_ALLOC_LARGE, OBD_FREE_LARGE, RAWOBJ_EMPTY, rawobj_free(), and verify_krb5_header().
static __u32 gss_verify_mic_kerberos (struct gss_ctx * gctx, int msgcnt, rawobj_t * msgs, int iovcnt, lnet_kiov_t * iovs, rawobj_t * token) [static]
Definition at line 905 of file gss_krb5_mech.c.
References CERROR, cksum, rawobj_s::data, GSS_S_BAD_SIG, GSS_S_COMPLETE, GSS_S_DEFECTIVE_TOKEN, GSS_S_FAILURE, gss_ctx::internal_ctx_id, krb5_ctx::kc_enctype, krb5_ctx::kc_keyc, krb5_enctype::ke_hash_size, krb5_make_checksum(), LASSERT, rawobj_s::len, RAWOBJ_EMPTY, rawobj_free(), and verify_krb5_header().
static __u32 gss_wrap_bulk_kerberos (struct gss_ctx * gctx, struct ptlrpc_bulk_desc * desc, rawobj_t * token, int adj_nob) [static]
Definition at line 1522 of file gss_krb5_mech.c.
References ptlrpc_bulk_desc::bd_iov_count, ptlrpc_bulk_desc::bd_type, blocksize(), cfs_get_random_bytes(), cksum, rawobj_s::data, ENCTYPE_ARCFOUR_HMAC, fill_krb5_header(), GET_KIOV, GSS_MAX_CIPHER_BLOCK, GSS_S_COMPLETE, GSS_S_FAILURE, gss_ctx::internal_ctx_id, krb5_keyblock::kb_tfm, krb5_ctx::kc_enctype, krb5_ctx::kc_keye, krb5_ctx::kc_keyi, krb5_enctype::ke_conf_size, krb5_enctype::ke_hash_size, krb5_encrypt_bulk(), krb5_make_checksum(), LASSERT, LBUG, rawobj_s::len, ptlrpc_is_bulk_desc_kiov(), RAWOBJ_EMPTY, and rawobj_free().
static __u32 gss_wrap_kerberos (struct gss_ctx * gctx, rawobj_t * gsshdr, rawobj_t * msg, int msg_buflen, rawobj_t * token) [static]
Definition at line 1344 of file gss_krb5_mech.c.
References add_padding(), blocksize(), CERROR, cfs_get_random_bytes(), cksum, rawobj_s::data, ENCTYPE_ARCFOUR_HMAC, fill_krb5_header(), GOTO, GSS_MAX_CIPHER_BLOCK, GSS_S_COMPLETE, GSS_S_FAILURE, gss_ctx::internal_ctx_id, krb5_keyblock::kb_tfm, krb5_ctx::kc_enctype, krb5_ctx::kc_keye, krb5_ctx::kc_keyi, krb5_enctype::ke_conf_size, krb5_enctype::ke_hash_size, krb5_encrypt_rawobjs(), krb5_make_checksum(), LASSERT, rawobj_s::len, RAWOBJ_EMPTY, and rawobj_free().
static __u32 import_context_rfc1964 (struct krb5_ctx * kctx, char * p, char * end) [static]
Definition at line 277 of file gss_krb5_mech.c.
References CDEBUG, D_SEC, get_bytes(), get_keyblock(), get_rawobj(), GSS_S_FAILURE, krb5_ctx::kc_enctype, krb5_ctx::kc_endtime, krb5_ctx::kc_keyc, krb5_ctx::kc_keye, krb5_ctx::kc_keyi, krb5_ctx::kc_mech_used, krb5_ctx::kc_seed, krb5_ctx::kc_seed_init, krb5_ctx::kc_seq_send, and keyblock_dup().
Referenced by gss_import_sec_context_kerberos().
static __u32 import_context_rfc4121 (struct krb5_ctx * kctx, char * p, char * end) [static]
Definition at line 356 of file gss_krb5_mech.c.
References CDEBUG, CERROR, D_SEC, get_bytes(), get_keyblock(), GSS_S_FAILURE, krb5_ctx::kc_cfx, krb5_ctx::kc_enctype, krb5_ctx::kc_endtime, krb5_ctx::kc_have_acceptor_subkey, krb5_ctx::kc_initiate, krb5_ctx::kc_keyc, krb5_ctx::kc_keye, krb5_ctx::kc_keyi, krb5_ctx::kc_seq_send, KRB5_CTX_FLAG_ACCEPTOR_SUBKEY, KRB5_CTX_FLAG_CFX, and KRB5_CTX_FLAG_INITIATOR.
Referenced by gss_import_sec_context_kerberos().
int __init init_kerberos_module (void)
Definition at line 1960 of file gss_krb5_mech.c.
References CERROR, krb5_seq_lock, lgss_mech_register(), and status.
Referenced by sptlrpc_gss_init().
static int keyblock_dup (struct krb5_keyblock * new, struct krb5_keyblock * kb) [static]
Definition at line 204 of file gss_krb5_mech.c.
References krb5_keyblock::kb_key, and rawobj_dup().
Referenced by gss_copy_reverse_context_kerberos(), and import_context_rfc1964().
static void keyblock_free (struct krb5_keyblock * kb) [static]
Definition at line 196 of file gss_krb5_mech.c.
References krb5_keyblock::kb_key, krb5_keyblock::kb_tfm, and rawobj_free().
Referenced by delete_context_kerberos().
static int keyblock_init (struct krb5_keyblock * kb, char * alg_name, int alg_mode) [static]
Definition at line 148 of file gss_krb5_mech.c.
References CERROR, rawobj_s::data, krb5_keyblock::kb_key, krb5_keyblock::kb_tfm, and rawobj_s::len.
Referenced by krb5_init_keys().
static int krb5_decrypt_bulk (struct crypto_blkcipher * tfm, struct krb5_header * khdr, struct ptlrpc_bulk_desc * desc, rawobj_t * cipher, rawobj_t * plain, int adj_nob) [static]
Definition at line 1174 of file gss_krb5_mech.c.
References BD_GET_ENC_KIOV, BD_GET_KIOV, ptlrpc_bulk_desc::bd_iov_count, ptlrpc_bulk_desc::bd_nob, ptlrpc_bulk_desc::bd_nob_transferred, ptlrpc_bulk_desc::bd_type, blocksize(), CERROR, rawobj_s::data, GET_ENC_KIOV, LASSERT, rawobj_s::len, ptlrpc_is_bulk_desc_kiov(), setup_sgtable(), teardown_sgtable(), and unlikely.
Referenced by gss_unwrap_bulk_kerberos().
static int krb5_digest_hmac (struct crypto_hash * tfm, rawobj_t * key, struct krb5_header * khdr, int msgcnt, rawobj_t * msgs, int iovcnt, lnet_kiov_t * iovs, rawobj_t * cksum) [inline, static]
Definition at line 648 of file gss_krb5_mech.c.
References rawobj_s::data, rawobj_s::len, setup_sgtable(), and teardown_sgtable().
Referenced by krb5_make_checksum().
static int krb5_digest_norm (struct crypto_hash * tfm, struct krb5_keyblock * kb, struct krb5_header * khdr, int msgcnt, rawobj_t * msgs, int iovcnt, lnet_kiov_t * iovs, rawobj_t * cksum) [inline, static]
Definition at line 703 of file gss_krb5_mech.c.
References rawobj_s::data, krb5_keyblock::kb_tfm, krb5_encrypt(), LASSERT, rawobj_s::len, setup_sgtable(), and teardown_sgtable().
Referenced by krb5_make_checksum().
static __u32 krb5_encrypt (struct crypto_blkcipher * tfm, int decrypt, void * iv, void * in, void * out, int length) [static]
Definition at line 597 of file gss_krb5_mech.c.
References CERROR, LASSERT, ret, setup_sgtable(), and teardown_sgtable().
Referenced by krb5_digest_norm().
static int krb5_encrypt_bulk (struct crypto_blkcipher * tfm, struct krb5_header * khdr, char * confounder, struct ptlrpc_bulk_desc * desc, rawobj_t * cipher, int adj_nob) [static]
Definition at line 1054 of file gss_krb5_mech.c.
References BD_GET_ENC_KIOV, BD_GET_KIOV, ptlrpc_bulk_desc::bd_iov_count, ptlrpc_bulk_desc::bd_nob, ptlrpc_bulk_desc::bd_type, blocksize(), CERROR, rawobj_s::data, GET_ENC_KIOV, LASSERT, rawobj_s::len, ptlrpc_is_bulk_desc_kiov(), setup_sgtable(), and teardown_sgtable().
Referenced by gss_wrap_bulk_kerberos().
static int krb5_encrypt_rawobjs (struct crypto_blkcipher * tfm, int mode_ecb, int inobj_cnt, rawobj_t * inobjs, rawobj_t * outobj, int enc) [static]
Definition at line 977 of file gss_krb5_mech.c.
References buf, CERROR, rawobj_s::data, ENTRY, LASSERT, rawobj_s::len, RETURN, setup_sgtable(), and teardown_sgtable().
Referenced by gss_unwrap_kerberos(), and gss_wrap_kerberos().
static int krb5_init_keys (struct krb5_ctx * kctx) [static]
Definition at line 167 of file gss_krb5_mech.c.
References CERROR, ENCTYPE_ARCFOUR_HMAC, krb5_ctx::kc_enctype, krb5_ctx::kc_keyc, krb5_ctx::kc_keye, krb5_ctx::kc_keyi, krb5_enctype::ke_enc_mode, krb5_enctype::ke_enc_name, krb5_enctype::ke_hash_hmac, krb5_enctype::ke_hash_size, keyblock_init(), and MAX_ENCTYPES.
Referenced by gss_copy_reverse_context_kerberos(), and gss_import_sec_context_kerberos().
static __s32 krb5_make_checksum (__u32 enctype, struct krb5_keyblock * kb, struct krb5_header * khdr, int msgcnt, rawobj_t * msgs, int iovcnt, lnet_kiov_t * iovs, rawobj_t * cksum) [static]
Definition at line 765 of file gss_krb5_mech.c.
References CERROR, rawobj_s::data, GSS_S_COMPLETE, GSS_S_FAILURE, krb5_keyblock::kb_key, krb5_enctype::ke_hash_hmac, krb5_enctype::ke_hash_name, krb5_digest_hmac(), krb5_digest_norm(), rawobj_s::len, and OBD_ALLOC_LARGE.
Referenced by gss_get_mic_kerberos(), gss_unwrap_bulk_kerberos(), gss_unwrap_kerberos(), gss_verify_mic_kerberos(), gss_wrap_bulk_kerberos(), and gss_wrap_kerberos().
static int setup_sgtable (struct sg_table * sgt, struct scatterlist * prealloc_sg, const void * buf, unsigned int buf_len) [static]
Definition at line 537 of file gss_krb5_mech.c.
References ret.
Referenced by krb5_decrypt_bulk(), krb5_digest_hmac(), krb5_digest_norm(), krb5_encrypt(), krb5_encrypt_bulk(), and krb5_encrypt_rawobjs().
static void teardown_sgtable (struct sg_table * sgt) [static]
Definition at line 590 of file gss_krb5_mech.c.
Referenced by krb5_decrypt_bulk(), krb5_digest_hmac(), krb5_digest_norm(), krb5_encrypt(), krb5_encrypt_bulk(), and krb5_encrypt_rawobjs().
static __u32 verify_krb5_header (struct krb5_ctx * kctx, struct krb5_header * khdr, int privacy) [static]
Definition at line 829 of file gss_krb5_mech.c.
References be16_to_cpu, CERROR, FLAG_SENDER_IS_ACCEPTOR, FLAG_WRAP_CONFIDENTIAL, GSS_S_BAD_SIG, GSS_S_COMPLETE, GSS_S_DEFECTIVE_TOKEN, krb5_ctx::kc_initiate, KG_TOK_MIC_MSG, KG_TOK_WRAP_MSG, krb5_header::kh_ec, krb5_header::kh_filler, krb5_header::kh_flags, krb5_header::kh_rrc, and krb5_header::kh_tok_id.
Referenced by gss_unwrap_bulk_kerberos(), gss_unwrap_kerberos(), and gss_verify_mic_kerberos().
Variable Documentation
struct krb5_enctype enctypes[] [static]
Definition at line 89 of file gss_krb5_mech.c.
struct gss_api_mech gss_kerberos_mech [static]
Initial value:
 {
        .gm_owner       = NULL,
        .gm_name        = "krb5",
        .gm_oid         = (rawobj_t)
                                {9, "\052\206\110\206\367\022\001\002\002"},
        .gm_ops         = &gss_kerberos_ops,
        .gm_sf_num      = 4,
        .gm_sfs         = gss_kerberos_sfs,
}
Definition at line 1950 of file gss_krb5_mech.c.
struct gss_api_ops gss_kerberos_ops [static]
Initial value:
 {
        .gss_import_sec_context     = gss_import_sec_context_kerberos,
        .gss_copy_reverse_context   = gss_copy_reverse_context_kerberos,
        .gss_inquire_context        = gss_inquire_context_kerberos,
        .gss_get_mic                = gss_get_mic_kerberos,
        .gss_verify_mic             = gss_verify_mic_kerberos,
        .gss_wrap                   = gss_wrap_kerberos,
        .gss_unwrap                 = gss_unwrap_kerberos,
        .gss_prep_bulk              = gss_prep_bulk_kerberos,
        .gss_wrap_bulk              = gss_wrap_bulk_kerberos,
        .gss_unwrap_bulk            = gss_unwrap_bulk_kerberos,
        .gss_delete_sec_context     = gss_delete_sec_context_kerberos,
        .gss_display                = gss_display_kerberos,
}
Definition at line 1905 of file gss_krb5_mech.c.
struct subflavor_desc gss_kerberos_sfs[] [static]
Initial value:
 {
        {
                .sf_subflavor   = SPTLRPC_SUBFLVR_KRB5N,
                .sf_qop         = 0,
                .sf_service     = SPTLRPC_SVC_NULL,
                .sf_name        = "krb5n"
        },
        {
                .sf_subflavor   = SPTLRPC_SUBFLVR_KRB5A,
                .sf_qop         = 0,
                .sf_service     = SPTLRPC_SVC_AUTH,
                .sf_name        = "krb5a"
        },
        {
                .sf_subflavor   = SPTLRPC_SUBFLVR_KRB5I,
                .sf_qop         = 0,
                .sf_service     = SPTLRPC_SVC_INTG,
                .sf_name        = "krb5i"
        },
        {
                .sf_subflavor   = SPTLRPC_SUBFLVR_KRB5P,
                .sf_qop         = 0,
                .sf_service     = SPTLRPC_SVC_PRIV,
                .sf_name        = "krb5p"
        },
}
Definition at line 1920 of file gss_krb5_mech.c.
spinlock_t krb5_seq_lock [static]
Definition at line 72 of file gss_krb5_mech.c.
Referenced by fill_krb5_header(), and init_kerberos_module().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.