Lustre: lustre/utils/gss/gss_util.h File Reference
lustre/utils/gss/gss_util.h File Reference
#include <stdlib.h>
#include "write_bytes.h"
Functions
void pgsserr (char *msg, u_int32_t maj_stat, u_int32_t min_stat, const gss_OID mech)
int gssd_check_mechs (void)
int gssd_get_local_realm (void)
Variables
char * this_realm
gss_cred_id_t gssd_creds
Function Documentation
int gssd_check_mechs (void)
Definition at line 351 of file gss_util.c.
References GSS_S_COMPLETE, and printerr.
Referenced by main().
int gssd_get_local_realm (void)
Definition at line 384 of file gss_util.c.
References printerr, and this_realm.
Referenced by main().
void pgsserr (char * msg, u_int32_t maj_stat, u_int32_t min_stat, const gss_OID mech)
Definition at line 182 of file gss_util.c.
References display_status_2().
Variable Documentation
gss_cred_id_t gssd_creds
char* this_realm
Definition at line 37 of file gss_util.h.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.