Lustre: lustre/ptlrpc/gss/gss_api.h File Reference
lustre/ptlrpc/gss/gss_api.h File Reference
Data Structures
struct gss_ctx
struct subflavor_desc
struct gss_api_mech
struct gss_api_ops
Defines
#define GSS_C_NO_BUFFER ((rawobj_t) 0)
#define GSS_C_NO_CONTEXT ((struct gss_ctx *) 0)
#define GSS_C_NULL_OID ((rawobj_t) 0)
Functions
__u32 lgss_import_sec_context (rawobj_t *input_token, struct gss_api_mech *mech, struct gss_ctx **ctx)
__u32 lgss_copy_reverse_context (struct gss_ctx *ctx, struct gss_ctx **ctx_new)
__u32 lgss_inquire_context (struct gss_ctx *ctx, unsigned long *endtime)
__u32 lgss_get_mic (struct gss_ctx *ctx, int msgcnt, rawobj_t *msgs, int iovcnt, lnet_kiov_t *iovs, rawobj_t *mic_token)
__u32 lgss_verify_mic (struct gss_ctx *ctx, int msgcnt, rawobj_t *msgs, int iovcnt, lnet_kiov_t *iovs, rawobj_t *mic_token)
__u32 lgss_wrap (struct gss_ctx *ctx, rawobj_t *gsshdr, rawobj_t *msg, int msg_buflen, rawobj_t *out_token)
__u32 lgss_unwrap (struct gss_ctx *ctx, rawobj_t *gsshdr, rawobj_t *token, rawobj_t *out_msg)
__u32 lgss_prep_bulk (struct gss_ctx *gctx, struct ptlrpc_bulk_desc *desc)
__u32 lgss_wrap_bulk (struct gss_ctx *gctx, struct ptlrpc_bulk_desc *desc, rawobj_t *token, int adj_nob)
__u32 lgss_unwrap_bulk (struct gss_ctx *gctx, struct ptlrpc_bulk_desc *desc, rawobj_t *token, int adj_nob)
__u32 lgss_delete_sec_context (struct gss_ctx **ctx)
int lgss_display (struct gss_ctx *ctx, char *buf, int bufsize)
int lgss_mech_register (struct gss_api_mech *mech)
void lgss_mech_unregister (struct gss_api_mech *mech)
struct gss_api_mech * lgss_OID_to_mech (rawobj_t *oid)
struct gss_api_mech * lgss_name_to_mech (char *name)
struct gss_api_mech * lgss_subflavor_to_mech (__u32 subflavor)
struct gss_api_mech * lgss_mech_get (struct gss_api_mech *mech)
void lgss_mech_put (struct gss_api_mech *mech)
Define Documentation
#define GSS_C_NO_BUFFER ((rawobj_t) 0)
Definition at line 30 of file gss_api.h.
Referenced by gssd_free_lgd(), gssd_refresh_lgd(), and lgssc_negotiation().
#define GSS_C_NO_CONTEXT ((struct gss_ctx *) 0)
Definition at line 31 of file gss_api.h.
Referenced by gssd_create_lgd(), gssd_free_lgd(), handle_nullreq(), and lgssc_init_nego_data().
#define GSS_C_NULL_OID ((rawobj_t) 0)
Definition at line 32 of file gss_api.h.
Function Documentation
__u32 lgss_copy_reverse_context (struct gss_ctx * ctx, struct gss_ctx ** ctx_new)
Definition at line 163 of file gss_mech_switch.c.
References gss_api_mech::gm_ops, gss_api_ops::gss_copy_reverse_context, GSS_S_COMPLETE, GSS_S_FAILURE, LASSERT, lgss_mech_get(), lgss_mech_put(), gss_ctx::mech_type, OBD_ALLOC_PTR, and OBD_FREE_PTR.
Referenced by gss_copy_rvc_cli_ctx(), and gss_svc_upcall_install_rvs_ctx().
__u32 lgss_delete_sec_context (struct gss_ctx ** ctx)
Definition at line 324 of file gss_mech_switch.c.
References CDEBUG, D_SEC, gss_api_mech::gm_ops, gss_api_ops::gss_delete_sec_context, GSS_S_COMPLETE, GSS_S_NO_CONTEXT, LASSERT, lgss_mech_put(), and OBD_FREE_PTR.
Referenced by gss_cli_ctx_finalize(), gss_copy_rvc_cli_ctx(), and rsc_free().
int lgss_display (struct gss_ctx * ctx, char * buf, int bufsize)
Definition at line 349 of file gss_mech_switch.c.
References gss_api_mech::gm_ops, gss_api_ops::gss_display, LASSERT, and gss_ctx::mech_type.
Referenced by gss_sec_display_kr().
__u32 lgss_get_mic (struct gss_ctx * ctx, int msgcnt, rawobj_t * msgs, int iovcnt, lnet_kiov_t * iovs, rawobj_t * mic_token)
Definition at line 207 of file gss_mech_switch.c.
References gss_api_mech::gm_ops, gss_api_ops::gss_get_mic, LASSERT, and gss_ctx::mech_type.
Referenced by gss_cli_ctx_wrap_bulk(), gss_sign_msg(), and gss_svc_wrap_bulk().
__u32 lgss_import_sec_context (rawobj_t * input_token, struct gss_api_mech * mech, struct gss_ctx ** ctx)
Definition at line 147 of file gss_mech_switch.c.
References gss_api_mech::gm_ops, gss_api_ops::gss_import_sec_context, GSS_S_FAILURE, LASSERT, lgss_mech_get(), and OBD_ALLOC_PTR.
Referenced by gss_kt_update(), gss_pipe_downcall(), and rsc_parse().
__u32 lgss_inquire_context (struct gss_ctx * ctx, unsigned long * endtime)
Definition at line 193 of file gss_mech_switch.c.
References gss_api_mech::gm_ops, gss_api_ops::gss_inquire_context, LASSERT, and gss_ctx::mech_type.
Referenced by gss_cli_ctx_uptodate(), gss_svc_upcall_install_rvs_ctx(), and rsc_parse().
struct gss_api_mech* lgss_mech_get (struct gss_api_mech * mech) [read]
Definition at line 85 of file gss_mech_switch.c.
References gss_api_mech::gm_owner.
Referenced by lgss_copy_reverse_context(), and lgss_import_sec_context().
void lgss_mech_put (struct gss_api_mech * mech)
Definition at line 140 of file gss_mech_switch.c.
References gss_api_mech::gm_owner.
Referenced by gss_sec_destroy_common(), lgss_copy_reverse_context(), lgss_delete_sec_context(), and rsc_parse().
int lgss_mech_register (struct gss_api_mech * mech)
Definition at line 67 of file gss_mech_switch.c.
References CWARN, gss_api_mech::gm_list, gss_api_mech::gm_name, and list_add().
Referenced by init_kerberos_module(), init_null_module(), and init_sk_module().
void lgss_mech_unregister (struct gss_api_mech * mech)
Definition at line 76 of file gss_mech_switch.c.
References CWARN, gss_api_mech::gm_list, gss_api_mech::gm_name, and list_del().
Referenced by cleanup_kerberos_module(), cleanup_null_module(), and cleanup_sk_module().
struct gss_api_mech* lgss_name_to_mech (char * name) [read]
Definition at line 91 of file gss_mech_switch.c.
References gss_api_mech::gm_list, gss_api_mech::gm_name, gss_api_mech::gm_owner, and list_for_each_entry.
Referenced by rsc_parse().
struct gss_api_mech* lgss_OID_to_mech (rawobj_t * oid) [read]
__u32 lgss_prep_bulk (struct gss_ctx * gctx, struct ptlrpc_bulk_desc * desc)
Definition at line 280 of file gss_mech_switch.c.
References gss_api_mech::gm_ops, gss_api_ops::gss_prep_bulk, LASSERT, and gss_ctx::mech_type.
Referenced by gss_prep_bulk().
struct gss_api_mech* lgss_subflavor_to_mech (__u32 subflavor) [read]
Definition at line 121 of file gss_mech_switch.c.
References gss_api_mech::gm_list, gss_api_mech::gm_owner, list_for_each_entry, and mech_supports_subflavor().
Referenced by gss_sec_create_common().
__u32 lgss_unwrap (struct gss_ctx * ctx, rawobj_t * gsshdr, rawobj_t * token, rawobj_t * out_msg)
Definition at line 265 of file gss_mech_switch.c.
References gss_api_mech::gm_ops, gss_api_ops::gss_unwrap, LASSERT, and gss_ctx::mech_type.
Referenced by gss_unseal_msg().
__u32 lgss_unwrap_bulk (struct gss_ctx * gctx, struct ptlrpc_bulk_desc * desc, rawobj_t * token, int adj_nob)
Definition at line 306 of file gss_mech_switch.c.
References gss_api_mech::gm_ops, gss_api_ops::gss_unwrap_bulk, LASSERT, and gss_ctx::mech_type.
Referenced by gss_cli_ctx_unwrap_bulk(), and gss_svc_unwrap_bulk().
__u32 lgss_verify_mic (struct gss_ctx * ctx, int msgcnt, rawobj_t * msgs, int iovcnt, lnet_kiov_t * iovs, rawobj_t * mic_token)
Definition at line 229 of file gss_mech_switch.c.
References gss_api_mech::gm_ops, gss_api_ops::gss_verify_mic, LASSERT, and gss_ctx::mech_type.
Referenced by gss_cli_ctx_unwrap_bulk(), gss_svc_unwrap_bulk(), and gss_verify_msg().
__u32 lgss_wrap (struct gss_ctx * ctx, rawobj_t * gsshdr, rawobj_t * msg, int msg_buflen, rawobj_t * out_token)
Definition at line 250 of file gss_mech_switch.c.
References gss_api_mech::gm_ops, gss_api_ops::gss_wrap, LASSERT, and gss_ctx::mech_type.
Referenced by gss_cli_ctx_seal(), and gss_svc_seal().
__u32 lgss_wrap_bulk (struct gss_ctx * gctx, struct ptlrpc_bulk_desc * desc, rawobj_t * token, int adj_nob)
Definition at line 292 of file gss_mech_switch.c.
References gss_api_mech::gm_ops, gss_api_ops::gss_wrap_bulk, LASSERT, and gss_ctx::mech_type.
Referenced by gss_cli_ctx_wrap_bulk(), and gss_svc_wrap_bulk().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.