Lustre: lustre/utils/gss/gss_util.c File Reference
lustre/utils/gss/gss_util.c File Reference
#include "config.h"
#include <errno.h>
#include <stdio.h>
#include <ctype.h>
#include <string.h>
#include <sys/param.h>
#include <gssapi/gssapi.h>
#include "gss_util.h"
#include "err_util.h"
#include "gssd.h"
#include <stdlib.h>
#include "lsupport.h"
#include "krb5_util.h"
Functions
static void display_status_2 (char *m, u_int32_t major, u_int32_t minor, const gss_OID mech)
void pgsserr (char *msg, u_int32_t maj_stat, u_int32_t min_stat, const gss_OID mech)
static int extract_realm_name (gss_buffer_desc *name, char **realm)
static int gssd_acquire_cred (char *server_name, gss_cred_id_t *cred, char **local_realm, int *valid)
int gssd_prepare_creds (int must_srv_mgs, int must_srv_mds, int must_srv_oss)
gss_cred_id_t gssd_select_svc_cred (int lustre_svc)
int gssd_check_mechs (void)
int gssd_get_local_realm (void)
Variables
gss_cred_id_t gssd_cred_mgs
gss_cred_id_t gssd_cred_mds
gss_cred_id_t gssd_cred_oss
int gssd_cred_mgs_valid = 0
int gssd_cred_mds_valid = 0
int gssd_cred_oss_valid = 0
char * mgs_local_realm = NULL
char * mds_local_realm = NULL
char * oss_local_realm = NULL
gss_OID g_mechOid = GSS_C_NULL_OID
char * this_realm = NULL
Function Documentation
static void display_status_2 (char * m, u_int32_t major, u_int32_t minor, const gss_OID mech) [static]
Definition at line 140 of file gss_util.c.
References GSS_C_GSS_CODE, GSS_C_MECH_CODE, GSS_S_COMPLETE, and printerr.
Referenced by pgsserr().
static int extract_realm_name (gss_buffer_desc * name, char ** realm) [static]
Definition at line 188 of file gss_util.c.
References printerr, and this_realm.
Referenced by gssd_acquire_cred().
static int gssd_acquire_cred (char * server_name, gss_cred_id_t * cred, char ** local_realm, int * valid) [static]
Definition at line 225 of file gss_util.c.
References extract_realm_name(), g_mechOid, GSS_C_ACCEPT, GSS_S_COMPLETE, name, pgsserr, and printerr.
Referenced by gssd_prepare_creds().
int gssd_check_mechs (void)
Definition at line 351 of file gss_util.c.
References GSS_S_COMPLETE, and printerr.
Referenced by main().
int gssd_get_local_realm (void)
Definition at line 384 of file gss_util.c.
References printerr, and this_realm.
Referenced by main().
int gssd_prepare_creds (int must_srv_mgs, int must_srv_mds, int must_srv_oss)
Definition at line 281 of file gss_util.c.
References gssd_acquire_cred(), gssd_cred_mds, gssd_cred_mds_valid, gssd_cred_mgs, gssd_cred_mgs_valid, gssd_cred_oss, gssd_cred_oss_valid, GSSD_SERVICE_MDS, GSSD_SERVICE_MGS, GSSD_SERVICE_OSS, mds_local_realm, mgs_local_realm, oss_local_realm, and printerr.
Referenced by main().
gss_cred_id_t gssd_select_svc_cred (int lustre_svc)
Definition at line 321 of file gss_util.c.
References gssd_cred_mds, gssd_cred_mds_valid, gssd_cred_mgs, gssd_cred_mgs_valid, gssd_cred_oss, gssd_cred_oss_valid, LUSTRE_GSS_SVC_MDS, LUSTRE_GSS_SVC_MGS, LUSTRE_GSS_SVC_OSS, and printerr.
Referenced by handle_nullreq().
void pgsserr (char * msg, u_int32_t maj_stat, u_int32_t min_stat, const gss_OID mech)
Definition at line 182 of file gss_util.c.
References display_status_2().
Variable Documentation
gss_OID g_mechOid = GSS_C_NULL_OID
Definition at line 95 of file gss_util.c.
Referenced by gssd_acquire_cred().
gss_cred_id_t gssd_cred_mds
Definition at line 85 of file gss_util.c.
Referenced by gssd_prepare_creds(), and gssd_select_svc_cred().
int gssd_cred_mds_valid = 0
Definition at line 88 of file gss_util.c.
Referenced by gssd_prepare_creds(), and gssd_select_svc_cred().
gss_cred_id_t gssd_cred_mgs
Definition at line 84 of file gss_util.c.
Referenced by gssd_prepare_creds(), and gssd_select_svc_cred().
int gssd_cred_mgs_valid = 0
Definition at line 87 of file gss_util.c.
Referenced by gssd_prepare_creds(), and gssd_select_svc_cred().
gss_cred_id_t gssd_cred_oss
Definition at line 86 of file gss_util.c.
Referenced by gssd_prepare_creds(), and gssd_select_svc_cred().
int gssd_cred_oss_valid = 0
Definition at line 89 of file gss_util.c.
Referenced by gssd_prepare_creds(), and gssd_select_svc_cred().
char* mds_local_realm = NULL
Definition at line 92 of file gss_util.c.
Referenced by get_ids(), and gssd_prepare_creds().
char* mgs_local_realm = NULL
Definition at line 91 of file gss_util.c.
Referenced by gssd_prepare_creds().
char* oss_local_realm = NULL
Definition at line 93 of file gss_util.c.
Referenced by gssd_prepare_creds().
char* this_realm = NULL
Definition at line 382 of file gss_util.c.
Referenced by extract_realm_name(), gssd_get_local_realm(), and gssd_process_krb5_keytab().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.