Lustre: lustre/ptlrpc/gss/gss_pipefs.c File Reference
lustre/ptlrpc/gss/gss_pipefs.c File Reference
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/dcache.h>
#include <linux/fs.h>
#include <linux/mutex.h>
#include <linux/crypto.h>
#include <asm/atomic.h>
#include <linux/sunrpc/rpc_pipe_fs.h>
#include <obd.h>
#include <obd_class.h>
#include <obd_support.h>
#include <lustre/lustre_idl.h>
#include <lustre_sec.h>
#include <lustre_net.h>
#include <lustre_import.h>
#include "gss_err.h"
#include "gss_internal.h"
#include "gss_api.h"
Data Structures
struct gss_upcall_msg_data
struct gss_upcall_msg
Defines
#define DEBUG_SUBSYSTEM S_SEC
#define GSS_SEC_PIPEFS_CTX_HASH_SIZE (32)
#define LUSTRE_PIPE_ROOT "/lustre"
#define LUSTRE_PIPE_KRB5 LUSTRE_PIPE_ROOT"/krb5"
Enumerations
enum mech_idx_t { MECH_KRB5 = 0, MECH_MAX }
Functions
static int gss_cli_ctx_refresh_pf (struct ptlrpc_cli_ctx *ctx)
static int gss_sec_pipe_upcall_init (struct gss_sec *gsec)
static void gss_sec_pipe_upcall_fini (struct gss_sec *gsec)
static struct ptlrpc_cli_ctx * ctx_create_pf (struct ptlrpc_sec *sec, struct vfs_cred *vcred)
static void ctx_destroy_pf (struct ptlrpc_sec *sec, struct ptlrpc_cli_ctx *ctx)
static void ctx_enhash_pf (struct ptlrpc_cli_ctx *ctx, struct hlist_head *hash)
static void ctx_unhash_pf (struct ptlrpc_cli_ctx *ctx, struct hlist_head *freelist)
static int ctx_check_death_pf (struct ptlrpc_cli_ctx *ctx, struct hlist_head *freelist)
static int ctx_check_death_locked_pf (struct ptlrpc_cli_ctx *ctx, struct hlist_head *freelist)
static int ctx_match_pf (struct ptlrpc_cli_ctx *ctx, struct vfs_cred *vcred)
static void ctx_list_destroy_pf (struct hlist_head *head)
static int gss_cli_ctx_validate_pf (struct ptlrpc_cli_ctx *ctx)
static void gss_cli_ctx_die_pf (struct ptlrpc_cli_ctx *ctx, int grace)
static unsigned int ctx_hash_index (int hashsize, __u64 key)
static void gss_sec_ctx_replace_pf (struct gss_sec *gsec, struct ptlrpc_cli_ctx *new)
static int gss_install_rvs_cli_ctx_pf (struct gss_sec *gsec, struct ptlrpc_svc_ctx *svc_ctx)
static void gss_ctx_cache_gc_pf (struct gss_sec_pipefs *gsec_pf, struct hlist_head *freelist)
static struct ptlrpc_sec * gss_sec_create_pf (struct obd_import *imp, struct ptlrpc_svc_ctx *ctx, struct sptlrpc_flavor *sf)
static void gss_sec_destroy_pf (struct ptlrpc_sec *sec)
static struct ptlrpc_cli_ctx * gss_sec_lookup_ctx_pf (struct ptlrpc_sec *sec, struct vfs_cred *vcred, int create, int remove_dead)
static void gss_sec_release_ctx_pf (struct ptlrpc_sec *sec, struct ptlrpc_cli_ctx *ctx, int sync)
static int gss_sec_flush_ctx_cache_pf (struct ptlrpc_sec *sec, uid_t uid, int grace, int force)
static int gss_svc_accept_pf (struct ptlrpc_request *req)
static int gss_svc_install_rctx_pf (struct obd_import *imp, struct ptlrpc_svc_ctx *ctx)
static __u32 upcall_get_sequence (void)
static __u32 mech_name2idx (const char *name)
static void upcall_list_lock (int idx)
static void upcall_list_unlock (int idx)
static void upcall_msg_enlist (struct gss_upcall_msg *msg)
static void upcall_msg_delist (struct gss_upcall_msg *msg)
static void gss_release_msg (struct gss_upcall_msg *gmsg)
static void gss_unhash_msg_nolock (struct gss_upcall_msg *gmsg)
static void gss_unhash_msg (struct gss_upcall_msg *gmsg)
static void gss_msg_fail_ctx (struct gss_upcall_msg *gmsg)
static struct gss_upcall_msg * gss_find_upcall (__u32 mechidx, __u32 seq)
static int simple_get_bytes (char **buf, __u32 *buflen, void *res, __u32 reslen)
static ssize_t gss_pipe_upcall (struct file *filp, struct rpc_pipe_msg *msg, char *dst, size_t buflen)
static ssize_t gss_pipe_downcall (struct file *filp, const char *src, size_t mlen)
static void gss_pipe_destroy_msg (struct rpc_pipe_msg *msg)
static void gss_pipe_release (struct inode *inode)
static int gss_ctx_refresh_pf (struct ptlrpc_cli_ctx *ctx)
static int __init gss_init_pipefs_upcall (void)
static void __exit gss_exit_pipefs_upcall (void)
int __init gss_init_pipefs (void)
void __exit gss_exit_pipefs (void)
Variables
static struct ptlrpc_sec_policy gss_policy_pipefs
static struct ptlrpc_ctx_ops gss_pipefs_ctxops
static atomic_t upcall_seq = ATOMIC_INIT(0)
static struct dentry * de_pipes [MECH_MAX] = { NULL, }
static struct list_head upcall_lists [MECH_MAX]
static spinlock_t upcall_locks [MECH_MAX]
static struct rpc_pipe_ops gss_upcall_ops
static struct ptlrpc_sec_cops gss_sec_pipefs_cops
static struct ptlrpc_sec_sops gss_sec_pipefs_sops
Define Documentation
#define DEBUG_SUBSYSTEM S_SEC
Definition at line 49 of file gss_pipefs.c.
#define GSS_SEC_PIPEFS_CTX_HASH_SIZE (32)
Referenced by gss_sec_create_pf().
#define LUSTRE_PIPE_KRB5 LUSTRE_PIPE_ROOT"/krb5"
Definition at line 621 of file gss_pipefs.c.
Referenced by gss_exit_pipefs_upcall(), and gss_init_pipefs_upcall().
#define LUSTRE_PIPE_ROOT "/lustre"
Definition at line 620 of file gss_pipefs.c.
Referenced by gss_exit_pipefs_upcall(), and gss_init_pipefs_upcall().
Enumeration Type Documentation
enum mech_idx_t
Enumerator:
MECH_KRB5
MECH_MAX
Definition at line 650 of file gss_pipefs.c.
Function Documentation
static int ctx_check_death_locked_pf (struct ptlrpc_cli_ctx * ctx, struct hlist_head * freelist) [inline, static]
Definition at line 172 of file gss_pipefs.c.
References ptlrpc_cli_ctx::cc_flags, ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_sec, ctx_check_death_pf(), LASSERT, and PTLRPC_CTX_CACHED_BIT.
Referenced by gss_ctx_cache_gc_pf(), and gss_sec_lookup_ctx_pf().
static int ctx_check_death_pf (struct ptlrpc_cli_ctx * ctx, struct hlist_head * freelist) [static]
Definition at line 159 of file gss_pipefs.c.
References cli_ctx_check_death(), and ctx_unhash_pf().
Referenced by ctx_check_death_locked_pf(), and gss_cli_ctx_validate_pf().
static struct ptlrpc_cli_ctx* ctx_create_pf (struct ptlrpc_sec * sec, struct vfs_cred * vcred) [static, read]
Definition at line 92 of file gss_pipefs.c.
References gss_cli_ctx::gc_base, gss_cli_ctx_init_common(), gss_pipefs_ctxops, OBD_ALLOC_PTR, and OBD_FREE_PTR.
Referenced by gss_install_rvs_cli_ctx_pf(), and gss_sec_lookup_ctx_pf().
static void ctx_destroy_pf (struct ptlrpc_sec * sec, struct ptlrpc_cli_ctx * ctx) [static]
Definition at line 113 of file gss_pipefs.c.
References ctx2gctx(), gss_cli_ctx_fini_common(), OBD_FREE_PTR, ptlrpc_sec::ps_nctx, and sptlrpc_sec_put().
Referenced by ctx_list_destroy_pf(), gss_install_rvs_cli_ctx_pf(), and gss_sec_release_ctx_pf().
static void ctx_enhash_pf (struct ptlrpc_cli_ctx * ctx, struct hlist_head * hash) [static]
Definition at line 127 of file gss_pipefs.c.
References ptlrpc_cli_ctx::cc_cache, ptlrpc_cli_ctx::cc_flags, ptlrpc_cli_ctx::cc_refcount, hlist_add_head(), and PTLRPC_CTX_CACHED_BIT.
Referenced by gss_sec_ctx_replace_pf(), and gss_sec_lookup_ctx_pf().
static unsigned int ctx_hash_index (int hashsize, __u64 key) [inline, static]
Definition at line 251 of file gss_pipefs.c.
References __u64.
Referenced by gss_sec_ctx_replace_pf(), and gss_sec_lookup_ctx_pf().
static void ctx_list_destroy_pf (struct hlist_head * head) [static]
Definition at line 193 of file gss_pipefs.c.
References ptlrpc_cli_ctx::cc_cache, ptlrpc_cli_ctx::cc_flags, ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_sec, ctx_destroy_pf(), hlist_head::first, hlist_del_init(), hlist_empty(), LASSERT, and PTLRPC_CTX_CACHED_BIT.
Referenced by gss_sec_ctx_replace_pf(), gss_sec_flush_ctx_cache_pf(), and gss_sec_lookup_ctx_pf().
static int ctx_match_pf (struct ptlrpc_cli_ctx * ctx, struct vfs_cred * vcred) [inline, static]
Definition at line 183 of file gss_pipefs.c.
References ptlrpc_cli_ctx::cc_ops, and ptlrpc_ctx_ops::match.
Referenced by gss_sec_ctx_replace_pf(), and gss_sec_lookup_ctx_pf().
static void ctx_unhash_pf (struct ptlrpc_cli_ctx * ctx, struct hlist_head * freelist) [static]
Definition at line 138 of file gss_pipefs.c.
References __hlist_del(), ptlrpc_cli_ctx::cc_cache, ptlrpc_cli_ctx::cc_flags, ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_sec, hlist_add_head(), hlist_del_init(), hlist_unhashed(), LASSERT, ptlrpc_sec::ps_lock, and PTLRPC_CTX_CACHED_BIT.
Referenced by ctx_check_death_pf(), gss_sec_ctx_replace_pf(), and gss_sec_flush_ctx_cache_pf().
static void gss_cli_ctx_die_pf (struct ptlrpc_cli_ctx * ctx, int grace) [static]
Definition at line 225 of file gss_pipefs.c.
References ptlrpc_cli_ctx::cc_cache, ptlrpc_cli_ctx::cc_flags, ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_sec, cli_ctx_expire(), hlist_del_init(), hlist_unhashed(), LASSERT, LBUG, ptlrpc_sec::ps_lock, and PTLRPC_CTX_CACHED_BIT.
static int gss_cli_ctx_refresh_pf (struct ptlrpc_cli_ctx * ctx) [static]
Definition at line 1118 of file gss_pipefs.c.
References ptlrpc_cli_ctx::cc_sec, ptlrpc_cli_ctx::cc_vcred, gss_sec::gs_base, gss_sec::gs_rvs_hdl, gss_ctx_refresh_pf(), gss_get_next_ctx_index(), and vfs_cred::vc_uid.
Referenced by gss_sec_lookup_ctx_pf().
static int gss_cli_ctx_validate_pf (struct ptlrpc_cli_ctx * ctx) [static]
Definition at line 215 of file gss_pipefs.c.
References cli_ctx_is_ready(), and ctx_check_death_pf().
static void gss_ctx_cache_gc_pf (struct gss_sec_pipefs * gsec_pf, struct hlist_head * freelist) [static]
Definition at line 320 of file gss_pipefs.c.
References CDEBUG, cfs_hlist_for_each_entry_safe, cfs_time_current_sec(), ctx_check_death_locked_pf(), D_SEC, ENTRY, EXIT, gss_sec::gs_base, gss_sec_pipefs::gsp_base, gss_sec_pipefs::gsp_chash, gss_sec_pipefs::gsp_chash_size, hlist_node::next, ptlrpc_sec::ps_gc_interval, ptlrpc_sec::ps_gc_next, ptlrpc_sec::ps_policy, and ptlrpc_sec_policy::sp_name.
Referenced by gss_sec_lookup_ctx_pf().
static int gss_ctx_refresh_pf (struct ptlrpc_cli_ctx * ctx) [static]
Definition at line 1039 of file gss_pipefs.c.
References ptlrpc_connection::c_peer, ptlrpc_cli_ctx::cc_flags, ptlrpc_cli_ctx::cc_sec, ptlrpc_cli_ctx::cc_vcred, CERROR, CWARN, de_pipes, ENTRY, gss_api_mech::gm_name, gss_sec::gs_mech, gss_upcall_msg::gum_base, gss_upcall_msg::gum_data, gss_upcall_msg::gum_gctx, gss_upcall_msg_data::gum_gid, gss_upcall_msg::gum_gsec, gss_upcall_msg::gum_mechidx, gss_upcall_msg_data::gum_nid, gss_upcall_msg_data::gum_obd, gss_upcall_msg::gum_refcount, gss_upcall_msg_data::gum_seq, gss_upcall_msg_data::gum_svc, gss_upcall_msg_data::gum_uid, obd_import::imp_connection, obd_import::imp_obd, import_to_gss_svc(), INIT_LIST_HEAD, LASSERT, mech_name2idx(), lnet_process_id_t::nid, OBD_ALLOC_PTR, OBD_FREE_PTR, obd_device::obd_name, ptlrpc_sec::ps_import, PTLRPC_CTX_DEAD, PTLRPC_CTX_ERROR, PTLRPC_CTX_STATUS_MASK, PTLRPC_CTX_UPTODATE, RETURN, sec2target_str(), sptlrpc_cli_ctx_get(), strlcpy(), upcall_get_sequence(), upcall_msg_delist(), upcall_msg_enlist(), and vfs_cred::vc_uid.
Referenced by gss_cli_ctx_refresh_pf().
void __exit gss_exit_pipefs (void)
Definition at line 1249 of file gss_pipefs.c.
References gss_exit_pipefs_upcall(), and sptlrpc_unregister_policy().
Referenced by sptlrpc_gss_exit().
static void __exit gss_exit_pipefs_upcall (void) [static]
Definition at line 1217 of file gss_pipefs.c.
References de_pipes, LASSERT, list_empty(), LUSTRE_PIPE_KRB5, LUSTRE_PIPE_ROOT, MECH_MAX, and upcall_lists.
Referenced by gss_exit_pipefs(), and gss_init_pipefs().
static struct gss_upcall_msg* gss_find_upcall (__u32 mechidx, __u32 seq) [static, read]
Definition at line 768 of file gss_pipefs.c.
References gss_upcall_msg::gum_data, gss_upcall_msg::gum_list, gss_upcall_msg::gum_mechidx, gss_upcall_msg::gum_refcount, gss_upcall_msg_data::gum_seq, LASSERT, list_for_each_entry, upcall_list_lock(), upcall_list_unlock(), and upcall_lists.
Referenced by gss_pipe_downcall().
int __init gss_init_pipefs (void)
Definition at line 1232 of file gss_pipefs.c.
References gss_exit_pipefs_upcall(), gss_init_pipefs_upcall(), and sptlrpc_register_policy().
Referenced by sptlrpc_gss_init().
static int __init gss_init_pipefs_upcall (void) [static]
Definition at line 1185 of file gss_pipefs.c.
References CERROR, de_pipes, gss_upcall_ops, INIT_LIST_HEAD, LUSTRE_PIPE_KRB5, LUSTRE_PIPE_ROOT, MECH_KRB5, upcall_lists, and upcall_locks.
Referenced by gss_init_pipefs().
static int gss_install_rvs_cli_ctx_pf (struct gss_sec * gsec, struct ptlrpc_svc_ctx * svc_ctx) [static]
Definition at line 294 of file gss_pipefs.c.
References ptlrpc_cli_ctx::cc_sec, ctx_create_pf(), ctx_destroy_pf(), ENTRY, gss_sec::gs_base, gss_copy_rvc_cli_ctx(), gss_sec_ctx_replace_pf(), RETURN, vfs_cred::vc_gid, and vfs_cred::vc_uid.
Referenced by gss_sec_create_pf(), and gss_svc_install_rctx_pf().
static void gss_msg_fail_ctx (struct gss_upcall_msg * gmsg) [static]
Definition at line 756 of file gss_pipefs.c.
References ptlrpc_cli_ctx::cc_flags, ptlrpc_cli_ctx::cc_refcount, gss_cli_ctx::gc_base, gss_upcall_msg::gum_gctx, LASSERT, PTLRPC_CTX_ERROR_BIT, and sptlrpc_cli_ctx_expire().
Referenced by gss_pipe_destroy_msg(), and gss_pipe_release().
static void gss_pipe_destroy_msg (struct rpc_pipe_msg * msg) [static]
Definition at line 948 of file gss_pipefs.c.
References CERROR, cfs_time_after(), cfs_time_current_sec(), CWARN, ENTRY, EXIT, gss_msg_fail_ctx(), gss_release_msg(), gss_unhash_msg(), gss_upcall_msg::gum_data, gss_upcall_msg_data::gum_nid, gss_upcall_msg_data::gum_obd, gss_upcall_msg::gum_refcount, gss_upcall_msg_data::gum_seq, gss_upcall_msg_data::gum_svc, gss_upcall_msg_data::gum_uid, LASSERT, list_empty(), LPX64, and now().
static ssize_t gss_pipe_downcall (struct file * filp, const char * src, size_t mlen) [static]
Definition at line 829 of file gss_pipefs.c.
References buf, ptlrpc_cli_ctx::cc_flags, ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_vcred, CERROR, CWARN, ENTRY, gss_cli_ctx::gc_base, gss_cli_ctx::gc_handle, gss_cli_ctx::gc_mechctx, gss_cli_ctx::gc_win, GOTO, gss_sec::gs_mech, gss_cli_ctx_uptodate(), gss_find_upcall(), gss_release_msg(), GSS_S_COMPLETE, gss_unhash_msg(), gss_upcall_msg::gum_gctx, gss_upcall_msg::gum_gsec, LASSERT, lgss_import_sec_context(), likely, MECH_MAX, OBD_ALLOC, OBD_FREE, PTLRPC_CTX_ERROR_BIT, rawobj_dup(), rawobj_extract_local(), RETURN, simple_get_bytes(), sptlrpc_cli_ctx_expire(), timeout, and vfs_cred::vc_uid.
static void gss_pipe_release (struct inode * inode) [static]
Definition at line 988 of file gss_pipefs.c.
References CERROR, ENTRY, EXIT, gss_msg_fail_ctx(), gss_release_msg(), gss_unhash_msg_nolock(), gss_upcall_msg::gum_base, gss_upcall_msg::gum_data, gss_upcall_msg_data::gum_nid, gss_upcall_msg_data::gum_obd, gss_upcall_msg::gum_refcount, gss_upcall_msg_data::gum_seq, gss_upcall_msg_data::gum_svc, gss_upcall_msg_data::gum_uid, LASSERT, list_empty(), list_entry, LPX64, MECH_MAX, upcall_list_lock(), upcall_list_unlock(), and upcall_lists.
static ssize_t gss_pipe_upcall (struct file * filp, struct rpc_pipe_msg * msg, char * dst, size_t buflen) [static]
Definition at line 807 of file gss_pipefs.c.
References ENTRY, and RETURN.
static void gss_release_msg (struct gss_upcall_msg * gmsg) [static]
Definition at line 706 of file gss_pipefs.c.
References ENTRY, EXIT, gss_cli_ctx::gc_base, gss_upcall_msg::gum_base, gss_upcall_msg::gum_gctx, gss_upcall_msg::gum_list, gss_upcall_msg::gum_refcount, LASSERT, list_empty(), OBD_FREE_PTR, sptlrpc_cli_ctx_put(), and sptlrpc_cli_ctx_wakeup().
Referenced by gss_pipe_destroy_msg(), gss_pipe_downcall(), and gss_pipe_release().
static struct ptlrpc_sec* gss_sec_create_pf (struct obd_import * imp, struct ptlrpc_svc_ctx * ctx, struct sptlrpc_flavor * sf) [static, read]
Definition at line 345 of file gss_pipefs.c.
References ENTRY, gss_sec::gs_base, gss_sec_pipefs::gsp_base, gss_sec_pipefs::gsp_chash, gss_sec_pipefs::gsp_chash_size, gss_install_rvs_cli_ctx_pf(), gss_policy_pipefs, gss_sec_create_common(), gss_sec_destroy_common(), gss_sec_pipe_upcall_init(), GSS_SEC_PIPEFS_CTX_HASH_SIZE, hash_size, INIT_HLIST_HEAD, OBD_ALLOC, OBD_FREE, PTLRPC_SEC_FL_REVERSE, PTLRPC_SEC_FL_ROOTONLY, RETURN, and sptlrpc_flavor::sf_flags.
static void gss_sec_ctx_replace_pf (struct gss_sec * gsec, struct ptlrpc_cli_ctx * new) [static]
Definition at line 257 of file gss_pipefs.c.
References __u64, ptlrpc_cli_ctx::cc_cache, ptlrpc_cli_ctx::cc_vcred, cfs_hlist_for_each_entry_safe, cli_ctx_expire(), ctx_enhash_pf(), ctx_hash_index(), ctx_list_destroy_pf(), ctx_match_pf(), ctx_unhash_pf(), ENTRY, EXIT, gss_sec::gs_base, gss_sec_pipefs::gsp_chash, gss_sec_pipefs::gsp_chash_size, HLIST_HEAD, LASSERT, hlist_node::next, and ptlrpc_sec::ps_lock.
Referenced by gss_install_rvs_cli_ctx_pf().
static void gss_sec_destroy_pf (struct ptlrpc_sec * sec) [static]
Definition at line 394 of file gss_pipefs.c.
References CWARN, gss_sec::gs_base, gss_sec_pipefs::gsp_chash, gss_sec_pipefs::gsp_chash_size, gss_sec_destroy_common(), gss_sec_pipe_upcall_fini(), LASSERT, OBD_FREE, ptlrpc_sec::ps_policy, and ptlrpc_sec_policy::sp_name.
static int gss_sec_flush_ctx_cache_pf (struct ptlrpc_sec * sec, uid_t uid, int grace, int force) [static]
Definition at line 539 of file gss_pipefs.c.
References ptlrpc_cli_ctx::cc_flags, ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_sec, ptlrpc_cli_ctx::cc_vcred, cfs_hlist_for_each_entry_safe, ctx_list_destroy_pf(), ctx_unhash_pf(), CWARN, ENTRY, gss_sec_pipefs::gsp_chash, gss_sec_pipefs::gsp_chash_size, HLIST_HEAD, LASSERT, hlist_node::next, ptlrpc_sec::ps_lock, PTLRPC_CTX_DEAD_BIT, PTLRPC_CTX_UPTODATE_BIT, RETURN, sec2target_str(), and vfs_cred::vc_uid.
static struct ptlrpc_cli_ctx* gss_sec_lookup_ctx_pf (struct ptlrpc_sec * sec, struct vfs_cred * vcred, int create, int remove_dead) [static, read]
Definition at line 416 of file gss_pipefs.c.
References __hlist_del(), __u64, ptlrpc_cli_ctx::cc_cache, ptlrpc_cli_ctx::cc_refcount, cfs_hlist_for_each_entry_safe, cfs_time_after(), cfs_time_current_sec(), ctx_check_death_locked_pf(), ctx_create_pf(), ctx_enhash_pf(), ctx_hash_index(), ctx_list_destroy_pf(), ctx_match_pf(), ENTRY, hlist_head::first, gss_sec_pipefs::gsp_chash, gss_sec_pipefs::gsp_chash_size, gss_cli_ctx_refresh_pf(), gss_ctx_cache_gc_pf(), hlist_add_head(), HLIST_HEAD, LASSERT, hlist_node::next, ptlrpc_sec::ps_gc_next, ptlrpc_sec::ps_lock, PTLRPC_CTX_NEW_BIT, RETURN, sec_is_reverse(), and vfs_cred::vc_uid.
static void gss_sec_pipe_upcall_fini (struct gss_sec * gsec) [static]
Definition at line 83 of file gss_pipefs.c.
Referenced by gss_sec_destroy_pf().
static int gss_sec_pipe_upcall_init (struct gss_sec * gsec) [static]
Definition at line 78 of file gss_pipefs.c.
Referenced by gss_sec_create_pf().
static void gss_sec_release_ctx_pf (struct ptlrpc_sec * sec, struct ptlrpc_cli_ctx * ctx, int sync) [static]
Definition at line 512 of file gss_pipefs.c.
References ptlrpc_cli_ctx::cc_cache, ptlrpc_cli_ctx::cc_flags, ctx_destroy_pf(), hlist_unhashed(), LASSERT, PTLRPC_CTX_CACHED_BIT, and PTLRPC_CTX_UPTODATE_BIT.
static int gss_svc_accept_pf (struct ptlrpc_request * req) [static]
Definition at line 596 of file gss_pipefs.c.
References gss_policy_pipefs, and gss_svc_accept().
static int gss_svc_install_rctx_pf (struct obd_import * imp, struct ptlrpc_svc_ctx * ctx) [static]
Definition at line 602 of file gss_pipefs.c.
References gss_install_rvs_cli_ctx_pf(), LASSERT, sec2gsec(), sptlrpc_import_sec_ref(), and sptlrpc_sec_put().
static void gss_unhash_msg (struct gss_upcall_msg * gmsg) [static]
Definition at line 745 of file gss_pipefs.c.
References gss_unhash_msg_nolock(), gss_upcall_msg::gum_mechidx, LASSERT, MECH_MAX, upcall_list_lock(), and upcall_list_unlock().
Referenced by gss_pipe_destroy_msg(), and gss_pipe_downcall().
static void gss_unhash_msg_nolock (struct gss_upcall_msg * gmsg) [static]
Definition at line 729 of file gss_pipefs.c.
References gss_upcall_msg::gum_list, gss_upcall_msg::gum_mechidx, gss_upcall_msg::gum_refcount, LASSERT, list_del_init(), list_empty(), MECH_MAX, and upcall_locks.
Referenced by gss_pipe_release(), and gss_unhash_msg().
static __u32 mech_name2idx (const char * name) [inline, static]
Definition at line 656 of file gss_pipefs.c.
References LASSERT, and MECH_KRB5.
Referenced by gss_ctx_refresh_pf().
static int simple_get_bytes (char ** buf, __u32 * buflen, void * res, __u32 reslen) [static]
Definition at line 789 of file gss_pipefs.c.
References CERROR.
Referenced by gss_pipe_downcall().
static __u32 upcall_get_sequence (void) [inline, static]
Definition at line 645 of file gss_pipefs.c.
References upcall_seq.
Referenced by gss_ctx_refresh_pf().
static void upcall_list_lock (int idx) [inline, static]
Definition at line 670 of file gss_pipefs.c.
References upcall_locks.
Referenced by gss_find_upcall(), gss_pipe_release(), gss_unhash_msg(), upcall_msg_delist(), and upcall_msg_enlist().
static void upcall_list_unlock (int idx) [inline, static]
Definition at line 676 of file gss_pipefs.c.
References upcall_locks.
Referenced by gss_find_upcall(), gss_pipe_release(), gss_unhash_msg(), upcall_msg_delist(), and upcall_msg_enlist().
static void upcall_msg_delist (struct gss_upcall_msg * msg) [static]
Definition at line 692 of file gss_pipefs.c.
References gss_upcall_msg::gum_list, gss_upcall_msg::gum_mechidx, list_del_init(), upcall_list_lock(), and upcall_list_unlock().
Referenced by gss_ctx_refresh_pf().
static void upcall_msg_enlist (struct gss_upcall_msg * msg) [static]
Definition at line 682 of file gss_pipefs.c.
References gss_upcall_msg::gum_list, gss_upcall_msg::gum_mechidx, list_add(), upcall_list_lock(), upcall_list_unlock(), and upcall_lists.
Referenced by gss_ctx_refresh_pf().
Variable Documentation
struct dentry* de_pipes[MECH_MAX] = { NULL, } [static]
Definition at line 663 of file gss_pipefs.c.
Referenced by gss_ctx_refresh_pf(), gss_exit_pipefs_upcall(), and gss_init_pipefs_upcall().
static struct ptlrpc_ctx_ops gss_pipefs_ctxops [static, read]
Initial value:
 {
        .match                  = gss_cli_ctx_match,
        .refresh                = gss_cli_ctx_refresh_pf,
        .validate               = gss_cli_ctx_validate_pf,
        .die                    = gss_cli_ctx_die_pf,
        .sign                   = gss_cli_ctx_sign,
        .verify                 = gss_cli_ctx_verify,
        .seal                   = gss_cli_ctx_seal,
        .unseal                 = gss_cli_ctx_unseal,
        .wrap_bulk              = gss_cli_ctx_wrap_bulk,
        .unwrap_bulk            = gss_cli_ctx_unwrap_bulk,
}
Definition at line 74 of file gss_pipefs.c.
Referenced by ctx_create_pf().
static struct ptlrpc_sec_policy gss_policy_pipefs [static, read]
Initial value:
 {
        .sp_owner               = THIS_MODULE,
        .sp_name                = "gss.pipefs",
        .sp_policy              = SPTLRPC_POLICY_GSS_PIPEFS,
        .sp_cops                = &gss_sec_pipefs_cops,
        .sp_sops                = &gss_sec_pipefs_sops,
}
Definition at line 73 of file gss_pipefs.c.
Referenced by gss_sec_create_pf(), and gss_svc_accept_pf().
struct ptlrpc_sec_cops gss_sec_pipefs_cops [static]
Initial value:
 {
        .create_sec             = gss_sec_create_pf,
        .destroy_sec            = gss_sec_destroy_pf,
        .kill_sec               = gss_sec_kill,
        .lookup_ctx             = gss_sec_lookup_ctx_pf,
        .release_ctx            = gss_sec_release_ctx_pf,
        .flush_ctx_cache        = gss_sec_flush_ctx_cache_pf,
        .install_rctx           = gss_sec_install_rctx,
        .alloc_reqbuf           = gss_alloc_reqbuf,
        .free_reqbuf            = gss_free_reqbuf,
        .alloc_repbuf           = gss_alloc_repbuf,
        .free_repbuf            = gss_free_repbuf,
        .enlarge_reqbuf         = gss_enlarge_reqbuf,
}
Definition at line 1149 of file gss_pipefs.c.
struct ptlrpc_sec_sops gss_sec_pipefs_sops [static]
Initial value:
 {
        .accept                 = gss_svc_accept_pf,
        .invalidate_ctx         = gss_svc_invalidate_ctx,
        .alloc_rs               = gss_svc_alloc_rs,
        .authorize              = gss_svc_authorize,
        .free_rs                = gss_svc_free_rs,
        .free_ctx               = gss_svc_free_ctx,
        .unwrap_bulk            = gss_svc_unwrap_bulk,
        .wrap_bulk              = gss_svc_wrap_bulk,
        .install_rctx           = gss_svc_install_rctx_pf,
}
Definition at line 1164 of file gss_pipefs.c.
struct rpc_pipe_ops gss_upcall_ops [static]
Initial value:
 {
        .upcall         = gss_pipe_upcall,
        .downcall       = gss_pipe_downcall,
        .destroy_msg    = gss_pipe_destroy_msg,
        .release_pipe   = gss_pipe_release,
}
Definition at line 1027 of file gss_pipefs.c.
Referenced by gss_init_pipefs_upcall().
struct list_head upcall_lists[MECH_MAX] [static]
Definition at line 665 of file gss_pipefs.c.
Referenced by gss_exit_pipefs_upcall(), gss_find_upcall(), gss_init_pipefs_upcall(), gss_pipe_release(), and upcall_msg_enlist().
spinlock_t upcall_locks[MECH_MAX] [static]
Definition at line 667 of file gss_pipefs.c.
Referenced by gss_init_pipefs_upcall(), gss_unhash_msg_nolock(), upcall_list_lock(), and upcall_list_unlock().
atomic_t upcall_seq = ATOMIC_INIT(0) [static]
Definition at line 642 of file gss_pipefs.c.
Referenced by upcall_get_sequence().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.