Lustre: lustre/ptlrpc/gss/gss_sk_mech.c File Reference
lustre/ptlrpc/gss/gss_sk_mech.c File Reference
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/crypto.h>
#include <linux/mutex.h>
#include <obd.h>
#include <obd_class.h>
#include <obd_support.h>
#include "gss_err.h"
#include "gss_internal.h"
#include "gss_api.h"
#include "gss_asn1.h"
Data Structures
struct sk_ctx
Defines
#define DEBUG_SUBSYSTEM S_SEC
Functions
static __u32 gss_import_sec_context_sk (rawobj_t *inbuf, struct gss_ctx *gss_context)
static __u32 gss_copy_reverse_context_sk (struct gss_ctx *gss_context_old, struct gss_ctx *gss_context_new)
static __u32 gss_inquire_context_sk (struct gss_ctx *gss_context, unsigned long *endtime)
static __u32 gss_get_mic_sk (struct gss_ctx *gss_context, int message_count, rawobj_t *messages, int iov_count, lnet_kiov_t *iovs, rawobj_t *token)
static __u32 gss_verify_mic_sk (struct gss_ctx *gss_context, int message_count, rawobj_t *messages, int iov_count, lnet_kiov_t *iovs, rawobj_t *token)
static __u32 gss_wrap_sk (struct gss_ctx *gss_context, rawobj_t *gss_header, rawobj_t *message, int message_buffer_length, rawobj_t *token)
static __u32 gss_unwrap_sk (struct gss_ctx *gss_context, rawobj_t *gss_header, rawobj_t *token, rawobj_t *message)
static __u32 gss_prep_bulk_sk (struct gss_ctx *gss_context, struct ptlrpc_bulk_desc *desc)
static __u32 gss_wrap_bulk_sk (struct gss_ctx *gss_context, struct ptlrpc_bulk_desc *desc, rawobj_t *token, int adj_nob)
static __u32 gss_unwrap_bulk_sk (struct gss_ctx *gss_context, struct ptlrpc_bulk_desc *desc, rawobj_t *token, int adj_nob)
static void gss_delete_sec_context_sk (void *internal_context)
int gss_display_sk (struct gss_ctx *gss_context, char *buf, int bufsize)
int __init init_sk_module (void)
void cleanup_sk_module (void)
Variables
static struct gss_api_ops gss_sk_ops
static struct subflavor_desc gss_sk_sfs []
static struct gss_api_mech gss_sk_mech
Define Documentation
#define DEBUG_SUBSYSTEM S_SEC
Definition at line 30 of file gss_sk_mech.c.
Function Documentation
void cleanup_sk_module (void)
Definition at line 226 of file gss_sk_mech.c.
References lgss_mech_unregister().
Referenced by sptlrpc_gss_init().
static __u32 gss_copy_reverse_context_sk (struct gss_ctx * gss_context_old, struct gss_ctx * gss_context_new) [static]
Definition at line 68 of file gss_sk_mech.c.
References CDEBUG, D_SEC, GSS_S_COMPLETE, GSS_S_FAILURE, gss_ctx::internal_ctx_id, and OBD_ALLOC_PTR.
static void gss_delete_sec_context_sk (void * internal_context) [static]
Definition at line 158 of file gss_sk_mech.c.
References OBD_FREE_PTR.
int gss_display_sk (struct gss_ctx * gss_context, char * buf, int bufsize)
Definition at line 165 of file gss_sk_mech.c.
static __u32 gss_get_mic_sk (struct gss_ctx * gss_context, int message_count, rawobj_t * messages, int iov_count, lnet_kiov_t * iovs, rawobj_t * token) [static]
Definition at line 95 of file gss_sk_mech.c.
References rawobj_s::data, GSS_S_COMPLETE, and rawobj_s::len.
static __u32 gss_import_sec_context_sk (rawobj_t * inbuf, struct gss_ctx * gss_context) [static]
Definition at line 50 of file gss_sk_mech.c.
References CDEBUG, D_SEC, rawobj_s::data, GSS_S_COMPLETE, GSS_S_FAILURE, gss_ctx::internal_ctx_id, and OBD_ALLOC_PTR.
static __u32 gss_inquire_context_sk (struct gss_ctx * gss_context, unsigned long * endtime) [static]
Definition at line 87 of file gss_sk_mech.c.
References GSS_S_COMPLETE.
static __u32 gss_prep_bulk_sk (struct gss_ctx * gss_context, struct ptlrpc_bulk_desc * desc) [static]
Definition at line 135 of file gss_sk_mech.c.
References GSS_S_COMPLETE.
static __u32 gss_unwrap_bulk_sk (struct gss_ctx * gss_context, struct ptlrpc_bulk_desc * desc, rawobj_t * token, int adj_nob) [static]
Definition at line 150 of file gss_sk_mech.c.
References GSS_S_COMPLETE.
static __u32 gss_unwrap_sk (struct gss_ctx * gss_context, rawobj_t * gss_header, rawobj_t * token, rawobj_t * message) [static]
Definition at line 128 of file gss_sk_mech.c.
References GSS_S_COMPLETE.
static __u32 gss_verify_mic_sk (struct gss_ctx * gss_context, int message_count, rawobj_t * messages, int iov_count, lnet_kiov_t * iovs, rawobj_t * token) [static]
Definition at line 109 of file gss_sk_mech.c.
References GSS_S_COMPLETE.
static __u32 gss_wrap_bulk_sk (struct gss_ctx * gss_context, struct ptlrpc_bulk_desc * desc, rawobj_t * token, int adj_nob) [static]
Definition at line 142 of file gss_sk_mech.c.
References GSS_S_COMPLETE.
static __u32 gss_wrap_sk (struct gss_ctx * gss_context, rawobj_t * gss_header, rawobj_t * message, int message_buffer_length, rawobj_t * token) [static]
Definition at line 120 of file gss_sk_mech.c.
References GSS_S_COMPLETE.
int __init init_sk_module (void)
Definition at line 215 of file gss_sk_mech.c.
References CERROR, lgss_mech_register(), and status.
Referenced by sptlrpc_gss_init().
Variable Documentation
struct gss_api_mech gss_sk_mech [static]
Initial value:
 {
        .gm_owner       = NULL,
        .gm_name        = "sk",
        .gm_oid         = (rawobj_t) {
                12,
                "\053\006\001\004\001\311\146\215\126\001\000\001",
        },
        .gm_ops         = &gss_sk_ops,
        .gm_sf_num      = 2,
        .gm_sfs         = gss_sk_sfs,
}
Definition at line 203 of file gss_sk_mech.c.
struct gss_api_ops gss_sk_ops [static]
Initial value:
 {
        .gss_import_sec_context     = gss_import_sec_context_sk,
        .gss_copy_reverse_context   = gss_copy_reverse_context_sk,
        .gss_inquire_context        = gss_inquire_context_sk,
        .gss_get_mic                = gss_get_mic_sk,
        .gss_verify_mic             = gss_verify_mic_sk,
        .gss_wrap                   = gss_wrap_sk,
        .gss_unwrap                 = gss_unwrap_sk,
        .gss_prep_bulk              = gss_prep_bulk_sk,
        .gss_wrap_bulk              = gss_wrap_bulk_sk,
        .gss_unwrap_bulk            = gss_unwrap_bulk_sk,
        .gss_delete_sec_context     = gss_delete_sec_context_sk,
        .gss_display                = gss_display_sk,
}
Definition at line 170 of file gss_sk_mech.c.
struct subflavor_desc gss_sk_sfs[] [static]
Initial value:
 {
        {
                .sf_subflavor   = SPTLRPC_SUBFLVR_SKI,
                .sf_qop         = 0,
                .sf_service     = SPTLRPC_SVC_INTG,
                .sf_name        = "ski"
        },
        {
                .sf_subflavor   = SPTLRPC_SUBFLVR_SKPI,
                .sf_qop         = 0,
                .sf_service     = SPTLRPC_SVC_PRIV,
                .sf_name        = "skpi"
        },
}
Definition at line 185 of file gss_sk_mech.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.