Lustre: lustre/utils/gss/gssd.c File Reference
lustre/utils/gss/gssd.c File Reference
#include "config.h"
#include <sys/types.h>
#include <sys/param.h>
#include <sys/socket.h>
#include <sys/wait.h>
#include <sys/ipc.h>
#include <sys/sem.h>
#include <unistd.h>
#include <err.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>
#include <errno.h>
#include "gssd.h"
#include "err_util.h"
#include "gss_util.h"
#include "krb5_util.h"
#include "lsupport.h"
Functions
static int lgssd_create_mutex (int *semid)
void lgssd_init_mutexs (void)
void lgssd_fini_mutexs (void)
void lgssd_mutex_get (int semid)
void lgssd_mutex_put (int semid)
static void lgssd_cleanup (void)
void sig_die (int signal)
void sig_hup (int signal)
static void usage (char *progname)
int main (int argc, char *argv[])
Variables
char pipefs_dir [PATH_MAX] = GSSD_PIPEFS_DIR
char pipefs_nfsdir [PATH_MAX] = GSSD_PIPEFS_DIR
char keytabfile [PATH_MAX] = GSSD_DEFAULT_KEYTAB_FILE
char ccachedir [PATH_MAX] = GSSD_DEFAULT_CRED_DIR
int use_memcache = 0
int lgssd_mutex_downcall = -1
Function Documentation
static void lgssd_cleanup (void) [static]
Definition at line 135 of file gssd.c.
References gssd_destroy_krb5_machine_creds(), lgssd_fini_mutexs(), and printerr.
Referenced by main(), and sig_die().
static int lgssd_create_mutex (int * semid) [static]
Definition at line 72 of file gssd.c.
References printerr.
Referenced by lgssd_init_mutexs().
void lgssd_fini_mutexs (void)
Definition at line 102 of file gssd.c.
References lgssd_mutex_downcall.
Referenced by lgssd_cleanup().
void lgssd_init_mutexs (void)
Definition at line 94 of file gssd.c.
References lgssd_create_mutex(), lgssd_mutex_downcall, and printerr.
Referenced by main().
void lgssd_mutex_get (int semid)
Definition at line 110 of file gssd.c.
References printerr.
Referenced by do_downcall(), and do_error_downcall().
void lgssd_mutex_put (int semid)
Definition at line 123 of file gssd.c.
References printerr.
Referenced by do_downcall(), and do_error_downcall().
int main (int argc, char * argv[])
Definition at line 179 of file gssd.c.
References ccachedir, fg, gssd_check_mechs(), GSSD_CLI, gssd_get_local_realm(), gssd_init_unique(), gssd_obtain_kernel_krb5_info(), gssd_refresh_krb5_machine_creds(), initerr(), keytabfile, lgssd_cleanup(), lgssd_init_mutexs(), lgssd_run(), opt, optarg, pipefs_dir, printerr, progname, sig_die(), sig_hup(), strlcpy(), usage, use_memcache, and verbosity.
void sig_die (int signal)
Definition at line 155 of file gssd.c.
References lgssd_cleanup(), and printerr.
Referenced by main().
void sig_hup (int signal)
Definition at line 163 of file gssd.c.
References printerr.
Referenced by main().
static void usage (char * progname) [static]
Definition at line 171 of file gssd.c.
Variable Documentation
char ccachedir[PATH_MAX] = GSSD_DEFAULT_CRED_DIR
Definition at line 68 of file gssd.c.
Referenced by gssd_find_existing_krb5_ccache(), gssd_setup_krb5_user_gss_ccache(), and main().
char keytabfile[PATH_MAX] = GSSD_DEFAULT_KEYTAB_FILE
Definition at line 67 of file gssd.c.
Referenced by gssd_refresh_krb5_machine_creds(), and main().
int lgssd_mutex_downcall = -1
Definition at line 70 of file gssd.c.
Referenced by do_downcall(), do_error_downcall(), lgssd_fini_mutexs(), and lgssd_init_mutexs().
char pipefs_dir[PATH_MAX] = GSSD_PIPEFS_DIR
Definition at line 65 of file gssd.c.
Referenced by lgssd_run(), main(), and update_client_list().
char pipefs_nfsdir[PATH_MAX] = GSSD_PIPEFS_DIR
Definition at line 66 of file gssd.c.
int use_memcache = 0
Definition at line 69 of file gssd.c.
Referenced by gssd_get_single_krb5_cred(), and main().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.