Lustre: lustre/utils/gss/gssd_main_loop.c File Reference
lustre/utils/gss/gssd_main_loop.c File Reference
#include <sys/param.h>
#include <sys/socket.h>
#include <sys/poll.h>
#include <netinet/in.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <memory.h>
#include <errno.h>
#include <fcntl.h>
#include <signal.h>
#include <unistd.h>
#include <time.h>
#include <wait.h>
#include "gssd.h"
#include "err_util.h"
Defines
#define POLL_MILLISECS 500
Functions
static void dir_notify_handler (int sig, siginfo_t *si, void *data)
static void scan_poll_results (int ret)
void lgssd_run ()
Variables
struct pollfd * pollarray
int pollsize
static volatile int dir_changed = 1
Define Documentation
#define POLL_MILLISECS 500
Definition at line 58 of file gssd_main_loop.c.
Referenced by lgssd_run().
Function Documentation
static void dir_notify_handler (int sig, siginfo_t * si, void * data) [static]
Definition at line 62 of file gssd_main_loop.c.
References dir_changed.
Referenced by lgssd_run().
void lgssd_run (void)
Definition at line 101 of file gssd_main_loop.c.
References dir_changed, dir_notify_handler(), DNOTIFY_SIGNAL, init_client_list(), pipefs_dir, POLL_MILLISECS, pollarray, pollsize, printerr, ret, scan_poll_results(), and update_client_list().
Referenced by main().
static void scan_poll_results (int ret) [static]
Definition at line 68 of file gssd_main_loop.c.
References dir_changed, handle_krb5_upcall(), handle_spkm3_upcall(), clnt_info::krb5_poll_index, pollarray, and clnt_info::spkm3_poll_index.
Referenced by lgssd_run().
Variable Documentation
volatile int dir_changed = 1 [static]
Definition at line 60 of file gssd_main_loop.c.
Referenced by dir_notify_handler(), lgssd_run(), and scan_poll_results().
struct pollfd* pollarray
Definition at line 102 of file gssd_proc.c.
Referenced by destroy_client(), get_poll_index(), init_client_list(), insert_clnt_poll(), lgssd_run(), and scan_poll_results().
int pollsize
Definition at line 104 of file gssd_proc.c.
Referenced by init_client_list(), and lgssd_run().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.