Lustre: lustre/utils/gss/gssd.h File Reference
lustre/utils/gss/gssd.h File Reference
#include <sys/types.h>
#include <sys/queue.h>
#include <gssapi/gssapi.h>
Data Structures
struct clnt_info
Defines
#define MAX_FILE_NAMELEN 32
#define FD_ALLOC_BLOCK 32
#define GSSD_PIPEFS_DIR "/var/lib/nfs/rpc_pipefs"
#define INFO "info"
#define KRB5 "krb5"
#define DNOTIFY_SIGNAL (SIGRTMIN + 3)
#define GSSD_DEFAULT_CRED_DIR "/tmp"
#define GSSD_DEFAULT_CRED_PREFIX "krb5cc_"
#define GSSD_DEFAULT_MACHINE_CRED_SUFFIX "machine"
#define GSSD_DEFAULT_KEYTAB_FILE "/etc/krb5.keytab"
#define GSSD_SERVICE_MGS "lustre_mgs"
#define GSSD_SERVICE_MDS "lustre_mds"
#define GSSD_SERVICE_OSS "lustre_oss"
#define GSSD_SERVICE_MDS_NAMELEN 10
#define GSSD_SERVICE_OSS_NAMELEN 10
#define LUSTRE_ROOT_NAME "lustre_root"
#define LUSTRE_ROOT_NAMELEN 11
Enumerations
enum { AUTHTYPE_KRB5, AUTHTYPE_SPKM3, AUTHTYPE_LIPKEY }
Functions
TAILQ_HEAD (clnt_list_head, clnt_info) clnt_list
void init_client_list (void)
int update_client_list (void)
void handle_krb5_upcall (struct clnt_info *clp)
void handle_spkm3_upcall (struct clnt_info *clp)
void lgssd_run (void)
void lgssd_init_mutexs (void)
void lgssd_fini_mutexs (void)
void lgssd_mutex_get (int semid)
void lgssd_mutex_put (int semid)
Variables
char pipefs_dir [PATH_MAX]
char keytabfile [PATH_MAX]
char ccachedir [PATH_MAX]
char gethostname_ex [PATH_MAX]
int use_memcache
int lgssd_mutex_downcall
Define Documentation
#define DNOTIFY_SIGNAL (SIGRTMIN + 3)
Definition at line 45 of file gssd.h.
Referenced by lgssd_run(), and process_clnt_dir().
#define FD_ALLOC_BLOCK 32
Definition at line 39 of file gssd.h.
Referenced by get_poll_index(), init_client_list(), and update_client_list().
#define GSSD_DEFAULT_CRED_DIR "/tmp"
Definition at line 47 of file gssd.h.
Referenced by gssd_get_single_krb5_cred().
#define GSSD_DEFAULT_CRED_PREFIX "krb5cc_"
Definition at line 48 of file gssd.h.
Referenced by gssd_get_single_krb5_cred(), gssd_setup_krb5_user_gss_ccache(), and select_krb5_ccache().
#define GSSD_DEFAULT_KEYTAB_FILE "/etc/krb5.keytab"
Definition at line 50 of file gssd.h.
#define GSSD_DEFAULT_MACHINE_CRED_SUFFIX "machine"
Definition at line 49 of file gssd.h.
Referenced by gssd_get_single_krb5_cred().
#define GSSD_PIPEFS_DIR "/var/lib/nfs/rpc_pipefs"
Definition at line 41 of file gssd.h.
#define GSSD_SERVICE_MDS "lustre_mds"
Definition at line 52 of file gssd.h.
Referenced by construct_service_name(), get_ids(), gssd_prepare_creds(), gssd_process_krb5_keytab(), and gssd_refresh_krb5_machine_creds().
#define GSSD_SERVICE_MDS_NAMELEN 10
Definition at line 54 of file gssd.h.
#define GSSD_SERVICE_MGS "lustre_mgs"
Definition at line 51 of file gssd.h.
Referenced by get_ids(), and gssd_prepare_creds().
#define GSSD_SERVICE_OSS "lustre_oss"
Definition at line 53 of file gssd.h.
Referenced by construct_service_name(), get_ids(), and gssd_prepare_creds().
#define GSSD_SERVICE_OSS_NAMELEN 10
Definition at line 55 of file gssd.h.
#define INFO "info"
Definition at line 43 of file gssd.h.
#define KRB5 "krb5"
Definition at line 44 of file gssd.h.
#define LUSTRE_ROOT_NAME "lustre_root"
Definition at line 57 of file gssd.h.
Referenced by get_ids(), gssd_process_krb5_keytab(), and gssd_refresh_krb5_machine_creds().
#define LUSTRE_ROOT_NAMELEN 11
Definition at line 58 of file gssd.h.
#define MAX_FILE_NAMELEN 32
Definition at line 38 of file gssd.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
AUTHTYPE_KRB5
AUTHTYPE_SPKM3
AUTHTYPE_LIPKEY
Definition at line 63 of file gssd.h.
Function Documentation
void handle_krb5_upcall (struct clnt_info * clp)
Definition at line 921 of file gssd_proc.c.
References AUTHTYPE_KRB5, construct_service_name(), do_downcall(), do_error_downcall(), gssd_create_lgd(), gssd_free_krb5_machine_cred_list(), gssd_free_lgd(), gssd_get_krb5_machine_cred_list(), gssd_setup_krb5_machine_gss_ccache(), gssd_setup_krb5_user_gss_ccache(), clnt_info::krb5_fd, krb5oid, lustre_gss_data::lgd_ctx, lustre_gss_data::lgd_gss_err, lustre_gss_data::lgd_rpc_err, LUSTRE_GSS_SVC_MDS, LUSTRE_GSS_SVC_OSS, lgssd_upcall_data::nid, lgssd_upcall_data::obd, printerr, lgssd_upcall_data::seq, serialize_context_for_kernel(), clnt_info::servicename, lgssd_upcall_data::svc, and lgssd_upcall_data::uid.
Referenced by scan_poll_results().
void handle_spkm3_upcall (struct clnt_info * clp)
Definition at line 1070 of file gssd_proc.c.
References AUTHTYPE_SPKM3, do_downcall(), do_error_downcall(), printerr, serialize_context_for_kernel(), clnt_info::spkm3_fd, and spkm3oid.
Referenced by scan_poll_results().
void init_client_list (void)
Definition at line 251 of file gssd_proc.c.
References FD_ALLOC_BLOCK, pollarray, and pollsize.
Referenced by lgssd_run().
void lgssd_fini_mutexs (void)
Definition at line 102 of file gssd.c.
References lgssd_mutex_downcall.
Referenced by lgssd_cleanup().
void lgssd_init_mutexs (void)
Definition at line 94 of file gssd.c.
References lgssd_create_mutex(), lgssd_mutex_downcall, and printerr.
Referenced by main().
void lgssd_mutex_get (int semid)
Definition at line 110 of file gssd.c.
References printerr.
Referenced by do_downcall(), and do_error_downcall().
void lgssd_mutex_put (int semid)
Definition at line 123 of file gssd.c.
References printerr.
Referenced by do_downcall(), and do_error_downcall().
void lgssd_run (void)
Definition at line 101 of file gssd_main_loop.c.
References dir_changed, dir_notify_handler(), DNOTIFY_SIGNAL, init_client_list(), pipefs_dir, POLL_MILLISECS, pollarray, pollsize, printerr, ret, scan_poll_results(), and update_client_list().
Referenced by main().
TAILQ_HEAD (clnt_list_head , clnt_info)
int update_client_list (void)
Definition at line 307 of file gssd_proc.c.
References FD_ALLOC_BLOCK, find_client(), lustre_dir, pipefs_dir, printerr, process_clnt_dir(), and update_old_clients().
Referenced by lgssd_run().
Variable Documentation
char ccachedir[PATH_MAX]
Definition at line 68 of file gssd.c.
Referenced by gssd_find_existing_krb5_ccache(), gssd_setup_krb5_user_gss_ccache(), and main().
char gethostname_ex[PATH_MAX]
Definition at line 166 of file lsupport.c.
Referenced by external_nid2hostname().
char keytabfile[PATH_MAX]
Definition at line 67 of file gssd.c.
Referenced by gssd_refresh_krb5_machine_creds(), and main().
int lgssd_mutex_downcall
Definition at line 70 of file gssd.c.
Referenced by do_downcall(), do_error_downcall(), lgssd_fini_mutexs(), and lgssd_init_mutexs().
char pipefs_dir[PATH_MAX]
Definition at line 65 of file gssd.c.
Referenced by lgssd_run(), main(), and update_client_list().
int use_memcache
Definition at line 69 of file gssd.c.
Referenced by gssd_get_single_krb5_cred(), and main().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.