Lustre: lustre/utils/gss/gssd_proc.c File Reference
lustre/utils/gss/gssd_proc.c File Reference
#include "config.h"
#include <sys/param.h>
#include <sys/stat.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <sys/fsuid.h>
#include <stdio.h>
#include <stdlib.h>
#include <pwd.h>
#include <grp.h>
#include <string.h>
#include <dirent.h>
#include <poll.h>
#include <fcntl.h>
#include <signal.h>
#include <unistd.h>
#include <errno.h>
#include <gssapi/gssapi.h>
#include <libcfs/util/param.h>
#include "gssd.h"
#include "err_util.h"
#include "gss_util.h"
#include "gss_oids.h"
#include "krb5_util.h"
#include "context.h"
#include "lsupport.h"
Data Structures
struct lustre_gss_init_res
struct lustre_gss_data
Functions
static void destroy_client (struct clnt_info *clp)
static struct clnt_info * insert_new_clnt (void)
static int process_clnt_dir_files (struct clnt_info *clp)
static int get_poll_index (int *ind)
static int insert_clnt_poll (struct clnt_info *clp)
static void process_clnt_dir (char *dir)
void init_client_list (void)
static void update_old_clients (struct dirent **namelist, int size)
static int find_client (char *dirname)
int update_client_list (void)
static int do_downcall (int k5_fd, struct lgssd_upcall_data *updata, struct lustre_gss_data *lgd, gss_buffer_desc *context_token)
static int do_error_downcall (int k5_fd, uint32_t seq, int rpc_err, int gss_err)
static int do_negotiation (struct lustre_gss_data *lgd, gss_buffer_desc *gss_token, struct lustre_gss_init_res *gr, int timeout)
static int gssd_refresh_lgd (struct lustre_gss_data *lgd)
static int gssd_create_lgd (struct clnt_info *clp, struct lustre_gss_data *lgd, struct lgssd_upcall_data *updata, int authtype)
static void gssd_free_lgd (struct lustre_gss_data *lgd)
static int construct_service_name (struct clnt_info *clp, struct lgssd_upcall_data *ud)
void handle_krb5_upcall (struct clnt_info *clp)
void handle_spkm3_upcall (struct clnt_info *clp)
Variables
struct pollfd * pollarray
int pollsize
Function Documentation
static int construct_service_name (struct clnt_info * clp, struct lgssd_upcall_data * ud) [static]
Definition at line 889 of file gssd_proc.c.
References GSSD_SERVICE_MDS, GSSD_SERVICE_OSS, lnet_nid2hostname(), LUSTRE_GSS_SVC_MDS, name, lgssd_upcall_data::nid, printerr, clnt_info::servicename, and lgssd_upcall_data::svc.
Referenced by handle_krb5_upcall().
static void destroy_client (struct clnt_info * clp) [static]
Definition at line 107 of file gssd_proc.c.
References clnt_info::dir_fd, clnt_info::dirname, clnt_info::krb5_fd, clnt_info::krb5_poll_index, pollarray, printerr, clnt_info::servicename, clnt_info::spkm3_fd, and clnt_info::spkm3_poll_index.
Referenced by process_clnt_dir(), and update_old_clients().
static int do_downcall (int k5_fd, struct lgssd_upcall_data * updata, struct lustre_gss_data * lgd, gss_buffer_desc * context_token) [static]
Definition at line 370 of file gssd_proc.c.
References buf, end, lustre_gss_data::lgd_rmt_ctx, lustre_gss_data::lgd_seq_win, lgssd_mutex_downcall, lgssd_mutex_get(), lgssd_mutex_put(), printerr, lgssd_upcall_data::seq, timeout, write_buffer(), and WRITE_BYTES.
Referenced by handle_krb5_upcall(), and handle_spkm3_upcall().
static int do_error_downcall (int k5_fd, uint32_t seq, int rpc_err, int gss_err) [static]
Definition at line 408 of file gssd_proc.c.
References buf, end, lgssd_mutex_downcall, lgssd_mutex_get(), lgssd_mutex_put(), printerr, timeout, and WRITE_BYTES.
Referenced by handle_krb5_upcall(), and handle_spkm3_upcall().
static int do_negotiation (struct lustre_gss_data * lgd, gss_buffer_desc * gss_token, struct lustre_gss_init_res * gr, int timeout) [static]
Definition at line 631 of file gssd_proc.c.
References cfs_free_param_data(), cfs_get_param_paths(), lgssd_ioctl_param::gid, lustre_gss_init_res::gr_ctx, lustre_gss_init_res::gr_major, lustre_gss_init_res::gr_minor, lustre_gss_init_res::gr_token, lustre_gss_init_res::gr_win, GSSD_INTERFACE_VERSION, lustre_gss_data::lgd_gss_err, lustre_gss_data::lgd_lustre_svc, lustre_gss_data::lgd_rpc_err, lustre_gss_data::lgd_uid, lustre_gss_data::lgd_uuid, lgssd_ioctl_param::lustre_svc, path, printerr, lgssd_ioctl_param::reply_buf, lgssd_ioctl_param::reply_buf_size, lgssd_ioctl_param::send_token, lgssd_ioctl_param::send_token_size, lgssd_ioctl_param::status, lgssd_ioctl_param::uid, lgssd_ioctl_param::uuid, and lgssd_ioctl_param::version.
Referenced by gssd_refresh_lgd().
static int find_client (char * dirname) [static]
Definition at line 295 of file gssd_proc.c.
References clnt_info::dirname.
Referenced by update_client_list().
static int get_poll_index (int * ind) [static]
Definition at line 165 of file gssd_proc.c.
References FD_ALLOC_BLOCK, pollarray, and printerr.
Referenced by insert_clnt_poll().
static int gssd_create_lgd (struct clnt_info * clp, struct lustre_gss_data * lgd, struct lgssd_upcall_data * updata, int authtype) [static]
Definition at line 817 of file gssd_proc.c.
References AUTHTYPE_KRB5, AUTHTYPE_SPKM3, GSS_C_MUTUAL_FLAG, GSS_C_NO_CONTEXT, GSS_S_COMPLETE, gssd_refresh_lgd(), krb5oid, lustre_gss_data::lgd_cred, lustre_gss_data::lgd_ctx, lustre_gss_data::lgd_established, lustre_gss_data::lgd_lustre_svc, lustre_gss_data::lgd_mech, lustre_gss_data::lgd_name, lustre_gss_data::lgd_req_flags, lustre_gss_data::lgd_rmt_ctx, lustre_gss_data::lgd_seq_win, lustre_gss_data::lgd_uid, lustre_gss_data::lgd_uuid, lgssd_upcall_data::obd, pgsserr, printerr, clnt_info::servicename, spkm3oid, lgssd_upcall_data::svc, and lgssd_upcall_data::uid.
Referenced by handle_krb5_upcall().
static void gssd_free_lgd (struct lustre_gss_data * lgd) [static]
Definition at line 877 of file gssd_proc.c.
References GSS_C_NO_BUFFER, GSS_C_NO_CONTEXT, and lustre_gss_data::lgd_ctx.
Referenced by handle_krb5_upcall().
static int gssd_refresh_lgd (struct lustre_gss_data * lgd) [static]
Definition at line 720 of file gssd_proc.c.
References do_negotiation(), lustre_gss_init_res::gr_ctx, lustre_gss_init_res::gr_major, lustre_gss_init_res::gr_token, lustre_gss_init_res::gr_win, GSS_C_NO_BUFFER, GSS_S_COMPLETE, GSS_S_CONTINUE_NEEDED, lustre_gss_data::lgd_cred, lustre_gss_data::lgd_ctx, lustre_gss_data::lgd_established, lustre_gss_data::lgd_mech, lustre_gss_data::lgd_name, lustre_gss_data::lgd_req_flags, lustre_gss_data::lgd_rmt_ctx, lustre_gss_data::lgd_seq_win, pgsserr, print_hexl(), and printerr.
Referenced by gssd_create_lgd().
void handle_krb5_upcall (struct clnt_info * clp)
Definition at line 921 of file gssd_proc.c.
References AUTHTYPE_KRB5, construct_service_name(), do_downcall(), do_error_downcall(), gssd_create_lgd(), gssd_free_krb5_machine_cred_list(), gssd_free_lgd(), gssd_get_krb5_machine_cred_list(), gssd_setup_krb5_machine_gss_ccache(), gssd_setup_krb5_user_gss_ccache(), clnt_info::krb5_fd, krb5oid, lustre_gss_data::lgd_ctx, lustre_gss_data::lgd_gss_err, lustre_gss_data::lgd_rpc_err, LUSTRE_GSS_SVC_MDS, LUSTRE_GSS_SVC_OSS, lgssd_upcall_data::nid, lgssd_upcall_data::obd, printerr, lgssd_upcall_data::seq, serialize_context_for_kernel(), clnt_info::servicename, lgssd_upcall_data::svc, and lgssd_upcall_data::uid.
Referenced by scan_poll_results().
void handle_spkm3_upcall (struct clnt_info * clp)
Definition at line 1070 of file gssd_proc.c.
References AUTHTYPE_SPKM3, do_downcall(), do_error_downcall(), printerr, serialize_context_for_kernel(), clnt_info::spkm3_fd, and spkm3oid.
Referenced by scan_poll_results().
void init_client_list (void)
Definition at line 251 of file gssd_proc.c.
References FD_ALLOC_BLOCK, pollarray, and pollsize.
Referenced by lgssd_run().
static int insert_clnt_poll (struct clnt_info * clp) [static]
Definition at line 185 of file gssd_proc.c.
References clnt_info::dirname, get_poll_index(), clnt_info::krb5_fd, clnt_info::krb5_poll_index, pollarray, printerr, clnt_info::spkm3_fd, and clnt_info::spkm3_poll_index.
Referenced by process_clnt_dir(), and update_old_clients().
static struct clnt_info* insert_new_clnt (void) [static, read]
Definition at line 125 of file gssd_proc.c.
References clnt_info::dir_fd, clnt_info::krb5_fd, clnt_info::krb5_poll_index, list, printerr, clnt_info::spkm3_fd, and clnt_info::spkm3_poll_index.
Referenced by process_clnt_dir().
static void process_clnt_dir (char * dir) [static]
Definition at line 211 of file gssd_proc.c.
References destroy_client(), clnt_info::dir_fd, clnt_info::dirname, DNOTIFY_SIGNAL, insert_clnt_poll(), insert_new_clnt(), list, printerr, and process_clnt_dir_files().
Referenced by update_client_list().
static int process_clnt_dir_files (struct clnt_info * clp) [static]
Definition at line 146 of file gssd_proc.c.
References clnt_info::dirname, clnt_info::krb5_fd, and clnt_info::spkm3_fd.
Referenced by process_clnt_dir(), and update_old_clients().
int update_client_list (void)
Definition at line 307 of file gssd_proc.c.
References FD_ALLOC_BLOCK, find_client(), lustre_dir, pipefs_dir, printerr, process_clnt_dir(), and update_old_clients().
Referenced by lgssd_run().
static void update_old_clients (struct dirent ** namelist, int size) [static]
Definition at line 265 of file gssd_proc.c.
References destroy_client(), clnt_info::dirname, insert_clnt_poll(), list, printerr, and process_clnt_dir_files().
Referenced by update_client_list().
Variable Documentation
struct pollfd* pollarray
Definition at line 102 of file gssd_proc.c.
Referenced by destroy_client(), get_poll_index(), init_client_list(), insert_clnt_poll(), lgssd_run(), and scan_poll_results().
int pollsize
Definition at line 104 of file gssd_proc.c.
Referenced by init_client_list(), and lgssd_run().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.