Lustre: libcfs/libcfs/hash.c File Reference
libcfs/libcfs/hash.c File Reference
#include <linux/seq_file.h>
#include <libcfs/libcfs.h>
Data Structures
struct cfs_hash_head
Simple hash head without depth tracking new element is always added to head of hlist.
struct cfs_hash_head_dep
Simple hash head with depth tracking new element is always added to head of hlist.
struct cfs_hash_dhead
double links hash head without depth tracking new element is always added to tail of hlist
struct cfs_hash_dhead_dep
double links hash head with depth tracking new element is always added to tail of hlist
struct cfs_hash_cond_arg
Enumerations
enum { CFS_HS_LOOKUP_MASK_FIND = 1 << 0, CFS_HS_LOOKUP_MASK_REF = 1 << 1, CFS_HS_LOOKUP_MASK_ADD = 1 << 2, CFS_HS_LOOKUP_MASK_DEL = 1 << 3 }
enum cfs_hash_lookup_intent {
CFS_HS_LOOKUP_IT_PEEK = CFS_HS_LOOKUP_MASK_FIND, CFS_HS_LOOKUP_IT_FIND, CFS_HS_LOOKUP_IT_ADD, CFS_HS_LOOKUP_IT_FINDADD,
CFS_HS_LOOKUP_IT_FINDDEL
}
Functions
static void cfs_hash_nl_lock (union cfs_hash_lock *lock, int exclusive)
static void cfs_hash_nl_unlock (union cfs_hash_lock *lock, int exclusive)
static void cfs_hash_spin_lock (union cfs_hash_lock *lock, int exclusive) __acquires(&lock->spin)
static void cfs_hash_spin_unlock (union cfs_hash_lock *lock, int exclusive) __releases(&lock->spin)
static void cfs_hash_rw_lock (union cfs_hash_lock *lock, int exclusive) __acquires(&lock->rw)
static void cfs_hash_rw_unlock (union cfs_hash_lock *lock, int exclusive) __releases(&lock->rw)
static void cfs_hash_lock_setup (struct cfs_hash *hs)
static int cfs_hash_hh_hhead_size (struct cfs_hash *hs)
static struct hlist_head * cfs_hash_hh_hhead (struct cfs_hash *hs, struct cfs_hash_bd *bd)
static int cfs_hash_hh_hnode_add (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode)
static int cfs_hash_hh_hnode_del (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode)
static int cfs_hash_hd_hhead_size (struct cfs_hash *hs)
static struct hlist_head * cfs_hash_hd_hhead (struct cfs_hash *hs, struct cfs_hash_bd *bd)
static int cfs_hash_hd_hnode_add (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode)
static int cfs_hash_hd_hnode_del (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode)
static int cfs_hash_dh_hhead_size (struct cfs_hash *hs)
static struct hlist_head * cfs_hash_dh_hhead (struct cfs_hash *hs, struct cfs_hash_bd *bd)
static int cfs_hash_dh_hnode_add (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode)
static int cfs_hash_dh_hnode_del (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnd)
static int cfs_hash_dd_hhead_size (struct cfs_hash *hs)
static struct hlist_head * cfs_hash_dd_hhead (struct cfs_hash *hs, struct cfs_hash_bd *bd)
static int cfs_hash_dd_hnode_add (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode)
static int cfs_hash_dd_hnode_del (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnd)
static void cfs_hash_hlist_setup (struct cfs_hash *hs)
static void cfs_hash_bd_from_key (struct cfs_hash *hs, struct cfs_hash_bucket **bkts, unsigned int bits, const void *key, struct cfs_hash_bd *bd)
void cfs_hash_bd_get (struct cfs_hash *hs, const void *key, struct cfs_hash_bd *bd)
operations on cfs_hash bucket (bd: bucket descriptor), they are normally for hash-table without rehash
static void cfs_hash_bd_dep_record (struct cfs_hash *hs, struct cfs_hash_bd *bd, int dep_cur)
void cfs_hash_bd_add_locked (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode)
void cfs_hash_bd_del_locked (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode)
void cfs_hash_bd_move_locked (struct cfs_hash *hs, struct cfs_hash_bd *bd_old, struct cfs_hash_bd *bd_new, struct hlist_node *hnode)
static struct hlist_node * cfs_hash_bd_lookup_intent (struct cfs_hash *hs, struct cfs_hash_bd *bd, const void *key, struct hlist_node *hnode, enum cfs_hash_lookup_intent intent)
struct hlist_node * cfs_hash_bd_lookup_locked (struct cfs_hash *hs, struct cfs_hash_bd *bd, const void *key)
struct hlist_node * cfs_hash_bd_peek_locked (struct cfs_hash *hs, struct cfs_hash_bd *bd, const void *key)
static void cfs_hash_multi_bd_lock (struct cfs_hash *hs, struct cfs_hash_bd *bds, unsigned n, int excl)
static void cfs_hash_multi_bd_unlock (struct cfs_hash *hs, struct cfs_hash_bd *bds, unsigned n, int excl)
static struct hlist_node * cfs_hash_multi_bd_lookup_locked (struct cfs_hash *hs, struct cfs_hash_bd *bds, unsigned n, const void *key)
static struct hlist_node * cfs_hash_multi_bd_findadd_locked (struct cfs_hash *hs, struct cfs_hash_bd *bds, unsigned n, const void *key, struct hlist_node *hnode, int noref)
static struct hlist_node * cfs_hash_multi_bd_finddel_locked (struct cfs_hash *hs, struct cfs_hash_bd *bds, unsigned n, const void *key, struct hlist_node *hnode)
static void cfs_hash_bd_order (struct cfs_hash_bd *bd1, struct cfs_hash_bd *bd2)
void cfs_hash_dual_bd_get (struct cfs_hash *hs, const void *key, struct cfs_hash_bd *bds)
operations on cfs_hash bucket (bd: bucket descriptor), they are safe for hash-table with rehash
void cfs_hash_dual_bd_lock (struct cfs_hash *hs, struct cfs_hash_bd *bds, int excl)
void cfs_hash_dual_bd_unlock (struct cfs_hash *hs, struct cfs_hash_bd *bds, int excl)
struct hlist_node * cfs_hash_dual_bd_lookup_locked (struct cfs_hash *hs, struct cfs_hash_bd *bds, const void *key)
struct hlist_node * cfs_hash_dual_bd_findadd_locked (struct cfs_hash *hs, struct cfs_hash_bd *bds, const void *key, struct hlist_node *hnode, int noref)
struct hlist_node * cfs_hash_dual_bd_finddel_locked (struct cfs_hash *hs, struct cfs_hash_bd *bds, const void *key, struct hlist_node *hnode)
static void cfs_hash_buckets_free (struct cfs_hash_bucket **buckets, int bkt_size, int prev_size, int size)
static struct cfs_hash_bucket ** cfs_hash_buckets_realloc (struct cfs_hash *hs, struct cfs_hash_bucket **old_bkts, unsigned int old_size, unsigned int new_size)
- Descriptive hash name
Initialize new libcfs hash, where:
- Initial hash table size, in bits - Maximum allowed hash table resize, in bits - Registered hash table operations - CFS_HASH_REHASH enable synamic hash resizing
CFS_HASH_SORT enable chained hash sort
static int cfs_hash_rehash_worker (struct cfs_workitem *wi)
static void cfs_hash_depth_wi_init (struct cfs_hash *hs)
static void cfs_hash_depth_wi_cancel (struct cfs_hash *hs)
struct cfs_hash * cfs_hash_create (char *name, unsigned cur_bits, unsigned max_bits, unsigned bkt_bits, unsigned extra_bytes, unsigned min_theta, unsigned max_theta, struct cfs_hash_ops *ops, unsigned flags)
static void cfs_hash_destroy (struct cfs_hash *hs)
Cleanup libcfs hash .
struct cfs_hash * cfs_hash_getref (struct cfs_hash *hs)
void cfs_hash_putref (struct cfs_hash *hs)
static int cfs_hash_rehash_bits (struct cfs_hash *hs)
static int cfs_hash_rehash_inline (struct cfs_hash *hs)
don't allow inline rehash if:
user wants non-blocking change (add/del) on hash table
too many elements
void cfs_hash_add (struct cfs_hash *hs, const void *key, struct hlist_node *hnode)
Add item to libcfs hash using .
static struct hlist_node * cfs_hash_find_or_add (struct cfs_hash *hs, const void *key, struct hlist_node *hnode, int noref)
int cfs_hash_add_unique (struct cfs_hash *hs, const void *key, struct hlist_node *hnode)
Add item to libcfs hash using .
void * cfs_hash_findadd_unique (struct cfs_hash *hs, const void *key, struct hlist_node *hnode)
Add item to libcfs hash using .
void * cfs_hash_del (struct cfs_hash *hs, const void *key, struct hlist_node *hnode)
Delete item from the libcfs hash using .
void * cfs_hash_del_key (struct cfs_hash *hs, const void *key)
Delete item given in libcfs hash .
void * cfs_hash_lookup (struct cfs_hash *hs, const void *key)
Lookup an item using in the libcfs hash and return it.
static void cfs_hash_for_each_enter (struct cfs_hash *hs)
static void cfs_hash_for_each_exit (struct cfs_hash *hs)
static __u64 cfs_hash_for_each_tight (struct cfs_hash *hs, cfs_hash_for_each_cb_t func, void *data, int remove_safe)
For each item in the libcfs hash call the passed callback and pass to it as an argument each hash item and the private .
static int cfs_hash_cond_del_locked (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode, void *data)
void cfs_hash_cond_del (struct cfs_hash *hs, cfs_hash_cond_opt_cb_t func, void *data)
Delete item from the libcfs hash when return true.
void cfs_hash_for_each (struct cfs_hash *hs, cfs_hash_for_each_cb_t func, void *data)
void cfs_hash_for_each_safe (struct cfs_hash *hs, cfs_hash_for_each_cb_t func, void *data)
static int cfs_hash_peek (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode, void *data)
int cfs_hash_is_empty (struct cfs_hash *hs)
__u64 cfs_hash_size_get (struct cfs_hash *hs)
static int cfs_hash_for_each_relax (struct cfs_hash *hs, cfs_hash_for_each_cb_t func, void *data, int start)
int cfs_hash_for_each_nolock (struct cfs_hash *hs, cfs_hash_for_each_cb_t func, void *data, int start)
int cfs_hash_for_each_empty (struct cfs_hash *hs, cfs_hash_for_each_cb_t func, void *data)
For each hash bucket in the libcfs hash call the passed callback until all the hash buckets are empty.
void cfs_hash_hlist_for_each (struct cfs_hash *hs, unsigned hindex, cfs_hash_for_each_cb_t func, void *data)
void cfs_hash_for_each_key (struct cfs_hash *hs, const void *key, cfs_hash_for_each_cb_t func, void *data)
void cfs_hash_rehash_cancel_locked (struct cfs_hash *hs)
Rehash the libcfs hash to the given .
void cfs_hash_rehash_cancel (struct cfs_hash *hs)
int cfs_hash_rehash (struct cfs_hash *hs, int do_rehash)
static int cfs_hash_rehash_bd (struct cfs_hash *hs, struct cfs_hash_bd *old)
void cfs_hash_rehash_key (struct cfs_hash *hs, const void *old_key, void *new_key, struct hlist_node *hnode)
Rehash the object referenced by in the libcfs hash .
void cfs_hash_debug_header (struct seq_file *m)
static struct cfs_hash_bucket ** cfs_hash_full_bkts (struct cfs_hash *hs)
static unsigned int cfs_hash_full_nbkt (struct cfs_hash *hs)
void cfs_hash_debug_str (struct cfs_hash *hs, struct seq_file *m)
Variables
struct cfs_wi_sched * cfs_sched_rehash
static struct cfs_hash_lock_ops cfs_hash_nl_lops
No lock hash.
static struct cfs_hash_lock_ops cfs_hash_nbl_lops
no bucket lock, one spinlock to protect everything
static struct cfs_hash_lock_ops cfs_hash_bkt_spin_lops
spin bucket lock, rehash is enabled
static struct cfs_hash_lock_ops cfs_hash_bkt_rw_lops
rw bucket lock, rehash is enabled
static struct cfs_hash_lock_ops cfs_hash_nr_bkt_spin_lops
spin bucket lock, rehash is disabled
static struct cfs_hash_lock_ops cfs_hash_nr_bkt_rw_lops
rw bucket lock, rehash is disabled
static struct cfs_hash_hlist_ops cfs_hash_hh_hops
static struct cfs_hash_hlist_ops cfs_hash_hd_hops
static struct cfs_hash_hlist_ops cfs_hash_dh_hops
static struct cfs_hash_hlist_ops cfs_hash_dd_hops
Enumeration Type Documentation
anonymous enum
Enumerator:
CFS_HS_LOOKUP_MASK_FIND
always set, for sanity (avoid ZERO intent)
CFS_HS_LOOKUP_MASK_REF
return entry with a ref
CFS_HS_LOOKUP_MASK_ADD
add entry if not existing
CFS_HS_LOOKUP_MASK_DEL
delete entry, ignore other masks
Definition at line 597 of file hash.c.
enum cfs_hash_lookup_intent
Enumerator:
CFS_HS_LOOKUP_IT_PEEK
return item w/o refcount
CFS_HS_LOOKUP_IT_FIND
return item with refcount
CFS_HS_LOOKUP_IT_ADD
return item w/o refcount if existed, otherwise add
CFS_HS_LOOKUP_IT_FINDADD
return item with refcount if existed, otherwise add
CFS_HS_LOOKUP_IT_FINDDEL
delete if existed
Definition at line 608 of file hash.c.
Function Documentation
void cfs_hash_add (struct cfs_hash * hs, const void * key, struct hlist_node * hnode)
Add item to libcfs hash using .
The registered ops->hs_get function will be called when the item is added.
Definition at line 1204 of file hash.c.
References cfs_hash_bd_add_locked(), cfs_hash_bd_get_and_lock(), cfs_hash_bd_unlock(), cfs_hash_key_validate(), cfs_hash_lock(), cfs_hash_rehash(), cfs_hash_rehash_bits(), cfs_hash_rehash_inline(), cfs_hash_unlock(), hlist_unhashed(), and LASSERT.
Referenced by ldlm_flock_blocking_link(), ldlm_process_flock_lock(), and mdt_intent_lock_replace().
int cfs_hash_add_unique (struct cfs_hash * hs, const void * key, struct hlist_node * hnode)
Add item to libcfs hash using .
The registered ops->hs_get function will be called if the item was added. Returns 0 on success or -EALREADY on key collisions.
Definition at line 1259 of file hash.c.
References cfs_hash_find_or_add().
Referenced by cl_env_attach(), class_new_export(), lod_pool_new(), lov_pool_new(), nodemap_create(), osc_quota_setdq(), qmt_pool_alloc(), and tgt_clients_data_init().
void cfs_hash_bd_add_locked (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode)
Definition at line 529 of file hash.c.
References cfs_hash_bd::bd_bucket, cfs_hash_bd_dep_record(), cfs_hash_get(), cfs_hash_with_counter(), cfs_hash_with_no_itemref(), cfs_hash_hlist_ops::hop_hnode_add, cfs_hash::hs_count, cfs_hash::hs_hops, cfs_hash_bucket::hsb_count, cfs_hash_bucket::hsb_version, and unlikely.
Referenced by cfs_hash_add(), cfs_hash_bd_lookup_intent(), cfs_hash_multi_bd_findadd_locked(), cfs_hash_rehash_key(), ldlm_resource_get(), lu_object_assign_fid(), lu_object_find_try(), and lu_object_new().
void cfs_hash_bd_del_locked (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode)
Definition at line 549 of file hash.c.
References cfs_hash_bd::bd_bucket, cfs_hash_put_locked(), cfs_hash_with_counter(), cfs_hash_with_no_itemref(), cfs_hash_hlist_ops::hop_hnode_del, cfs_hash::hs_count, cfs_hash::hs_hops, cfs_hash_bucket::hsb_count, cfs_hash_bucket::hsb_version, LASSERT, and unlikely.
Referenced by __ldlm_resource_putref_final(), cfs_hash_bd_lookup_intent(), cfs_hash_cond_del_locked(), cfs_hash_del(), cfs_hash_destroy(), lqe_iter_cb(), lu_object_put(), lu_object_unhash(), lu_site_purge(), and nodemap_cleanup_iter_cb().
static void cfs_hash_bd_dep_record (struct cfs_hash * hs, struct cfs_hash_bd * bd, int dep_cur) [inline, static]
Definition at line 506 of file hash.c.
References cfs_hash_bd::bd_bucket, cfs_hash_bd::bd_offset, cfs_wi_schedule(), cfs_hash::hs_cur_bits, cfs_hash_bucket::hsb_depmax, cfs_hash_bucket::hsb_index, likely, and max.
Referenced by cfs_hash_bd_add_locked(), and cfs_hash_bd_move_locked().
static void cfs_hash_bd_from_key (struct cfs_hash * hs, struct cfs_hash_bucket ** bkts, unsigned int bits, const void * key, struct cfs_hash_bd * bd) [static]
Definition at line 479 of file hash.c.
References cfs_hash_bd::bd_bucket, cfs_hash_bd::bd_offset, cfs_hash_id(), cfs_hash::hs_bkt_bits, cfs_hash::hs_cur_bits, cfs_hash::hs_rehash_bits, and LASSERT.
Referenced by cfs_hash_bd_get(), cfs_hash_dual_bd_get(), and cfs_hash_rehash_bd().
void cfs_hash_bd_get (struct cfs_hash * hs, const void * key, struct cfs_hash_bd * bd)
operations on cfs_hash bucket (bd: bucket descriptor), they are normally for hash-table without rehash
Definition at line 491 of file hash.c.
References cfs_hash_bd_from_key(), cfs_hash::hs_buckets, cfs_hash::hs_cur_bits, cfs_hash::hs_rehash_bits, cfs_hash::hs_rehash_buckets, LASSERT, and likely.
Referenced by cfs_hash_bd_get_and_lock(), cfs_hash_multi_bd_findadd_locked(), cfs_hash_rehash_key(), ldlm_resource_putref(), lu_object_put(), lu_site_bkt_from_fid(), and lu_site_purge().
static struct hlist_node* cfs_hash_bd_lookup_intent (struct cfs_hash * hs, struct cfs_hash_bd * bd, const void * key, struct hlist_node * hnode, enum cfs_hash_lookup_intent intent) [static, read]
Definition at line 626 of file hash.c.
References cfs_hash_bd_add_locked(), cfs_hash_bd_del_locked(), cfs_hash_bd_hhead(), cfs_hash_get(), cfs_hash_keycmp(), CFS_HS_LOOKUP_MASK_ADD, CFS_HS_LOOKUP_MASK_DEL, CFS_HS_LOOKUP_MASK_REF, hlist_for_each, and LASSERT.
Referenced by cfs_hash_bd_lookup_locked(), cfs_hash_bd_peek_locked(), cfs_hash_multi_bd_findadd_locked(), cfs_hash_multi_bd_finddel_locked(), and cfs_hash_multi_bd_lookup_locked().
struct hlist_node* cfs_hash_bd_lookup_locked (struct cfs_hash * hs, struct cfs_hash_bd * bd, const void * key) [read]
Definition at line 667 of file hash.c.
References cfs_hash_bd_lookup_intent(), and CFS_HS_LOOKUP_IT_FIND.
Referenced by ldlm_resource_get().
void cfs_hash_bd_move_locked (struct cfs_hash * hs, struct cfs_hash_bd * bd_old, struct cfs_hash_bd * bd_new, struct hlist_node * hnode)
Definition at line 570 of file hash.c.
References cfs_hash_bd::bd_bucket, cfs_hash_bd_compare(), cfs_hash_bd_dep_record(), cfs_hash_hlist_ops::hop_hnode_add, cfs_hash_hlist_ops::hop_hnode_del, cfs_hash::hs_hops, cfs_hash_bucket::hsb_count, cfs_hash_bucket::hsb_version, LASSERT, and unlikely.
Referenced by cfs_hash_rehash_bd(), and cfs_hash_rehash_key().
static void cfs_hash_bd_order (struct cfs_hash_bd * bd1, struct cfs_hash_bd * bd2) [static]
Definition at line 787 of file hash.c.
References cfs_hash_bd::bd_bucket, and cfs_hash_bd_compare().
Referenced by cfs_hash_dual_bd_get(), and cfs_hash_rehash_key().
struct hlist_node* cfs_hash_bd_peek_locked (struct cfs_hash * hs, struct cfs_hash_bd * bd, const void * key) [read]
Definition at line 676 of file hash.c.
References cfs_hash_bd_lookup_intent(), and CFS_HS_LOOKUP_IT_PEEK.
Referenced by htable_lookup().
static void cfs_hash_buckets_free (struct cfs_hash_bucket ** buckets, int bkt_size, int prev_size, int size) [static]
Definition at line 869 of file hash.c.
References LIBCFS_FREE.
Referenced by cfs_hash_buckets_realloc(), cfs_hash_destroy(), and cfs_hash_rehash_worker().
static struct cfs_hash_bucket** cfs_hash_buckets_realloc (struct cfs_hash * hs, struct cfs_hash_bucket ** old_bkts, unsigned int old_size, unsigned int new_size) [static, read]
Definition at line 888 of file hash.c.
References cfs_hash_bd::bd_bucket, cfs_hash_bd_for_each_hlist, cfs_hash_bkt_size(), cfs_hash_buckets_free(), cfs_hash_with_no_bktlock(), cfs_hash_with_no_lock(), cfs_hash_with_rw_bktlock(), cfs_hash_with_spin_bktlock(), cfs_hash_bucket::hsb_depmax, cfs_hash_bucket::hsb_index, cfs_hash_bucket::hsb_version, INIT_HLIST_HEAD, LASSERT, LBUG, and LIBCFS_ALLOC.
Referenced by cfs_hash_create(), and cfs_hash_rehash_worker().
void cfs_hash_cond_del (struct cfs_hash * hs, cfs_hash_cond_opt_cb_t func, void * data)
Delete item from the libcfs hash when return true.
The write lock being hold during loop for each bucket to avoid any object be reference.
Definition at line 1499 of file hash.c.
References cfs_hash_cond_del_locked(), cfs_hash_for_each_tight(), and cfs_hash_cond_arg::func.
static int cfs_hash_cond_del_locked (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode, void * data) [static]
Definition at line 1483 of file hash.c.
References cfs_hash_cond_arg::arg, cfs_hash_bd_del_locked(), cfs_hash_object(), and cfs_hash_cond_arg::func.
Referenced by cfs_hash_cond_del().
struct cfs_hash* cfs_hash_create (char * name, unsigned cur_bits, unsigned max_bits, unsigned bkt_bits, unsigned extra_bytes, unsigned min_theta, unsigned max_theta, struct cfs_hash_ops * ops, unsigned flags) [read]
Definition at line 1003 of file hash.c.
References __cfs_hash_set_theta(), CFS_HASH_BIGNAME, CFS_HASH_BIGNAME_LEN, cfs_hash_buckets_realloc(), CFS_HASH_COUNTER, cfs_hash_depth_wi_init(), cfs_hash_hlist_setup(), cfs_hash_lock_setup(), CFS_HASH_NAME_LEN, CFS_HASH_NBKT, CFS_HASH_NO_LOCK, CFS_HASH_REHASH, CFS_HASH_REHASH_KEY, cfs_hash_rehash_worker(), CFS_HASH_THETA_BITS, cfs_hash_with_rehash(), cfs_wi_init(), CLASSERT, ENTRY, ergo, cfs_hash::hs_bkt_bits, cfs_hash::hs_buckets, cfs_hash::hs_count, cfs_hash::hs_cur_bits, cfs_hash::hs_extra_bytes, cfs_hash::hs_flags, cfs_hash_ops::hs_get, cfs_hash_ops::hs_hash, cfs_hash_ops::hs_key, cfs_hash_ops::hs_keycmp, cfs_hash_ops::hs_keycpy, cfs_hash::hs_max_bits, cfs_hash::hs_min_bits, cfs_hash::hs_name, cfs_hash_ops::hs_object, cfs_hash::hs_ops, cfs_hash_ops::hs_put, cfs_hash_ops::hs_put_locked, cfs_hash::hs_refcount, cfs_hash::hs_rehash_bits, cfs_hash::hs_rehash_wi, LASSERT, LIBCFS_ALLOC, LIBCFS_FREE, offsetof, RETURN, and strlcpy().
Referenced by cl_env_store_init(), class_setup(), ldlm_init_export(), ldlm_init_flock_export(), ldlm_namespace_new(), lod_pools_init(), lov_setup(), lquota_site_alloc(), lu_site_init(), nodemap_init_hash(), osc_quota_setup(), ptlrpc_connection_init(), and qmt_pool_init().
static struct hlist_head* cfs_hash_dd_hhead (struct cfs_hash * hs, struct cfs_hash_bd * bd) [static, read]
Definition at line 398 of file hash.c.
References cfs_hash_bd::bd_bucket, cfs_hash_bd::bd_offset, cfs_hash_dhead_dep::dd_head, head, and cfs_hash_bucket::hsb_head.
Referenced by cfs_hash_dd_hnode_add(), and cfs_hash_dd_hnode_del().
static int cfs_hash_dd_hhead_size (struct cfs_hash * hs) [static]
Definition at line 392 of file hash.c.
static int cfs_hash_dd_hnode_add (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode) [static]
Definition at line 407 of file hash.c.
References cfs_hash_dd_hhead(), cfs_hash_dhead_dep::dd_depth, cfs_hash_dhead_dep::dd_head, cfs_hash_dhead_dep::dd_tail, and hlist_add_head().
static int cfs_hash_dd_hnode_del (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnd) [static]
Definition at line 423 of file hash.c.
References cfs_hash_dd_hhead(), cfs_hash_dhead_dep::dd_depth, cfs_hash_dhead_dep::dd_head, cfs_hash_dhead_dep::dd_tail, hlist_head::first, hlist_del_init(), hlist_node::next, and hlist_node::pprev.
void cfs_hash_debug_header (struct seq_file * m)
Definition at line 2042 of file hash.c.
References CFS_HASH_BIGNAME_LEN.
void cfs_hash_debug_str (struct cfs_hash * hs, struct seq_file * m)
Definition at line 2073 of file hash.c.
References __cfs_hash_theta(), __cfs_hash_theta_frac(), __cfs_hash_theta_int(), cfs_hash_bd::bd_bucket, cfs_hash_bd_lock(), cfs_hash_bd_unlock(), CFS_HASH_BIGNAME_LEN, cfs_hash_full_bkts(), cfs_hash_full_nbkt(), cfs_hash_lock(), cfs_hash_unlock(), cfs_hash::hs_cur_bits, cfs_hash::hs_flags, cfs_hash::hs_max_bits, cfs_hash::hs_max_theta, cfs_hash::hs_min_bits, cfs_hash::hs_min_theta, cfs_hash::hs_name, cfs_hash::hs_rehash_count, cfs_hash_bucket::hsb_count, cfs_hash_bucket::hsb_depmax, and max.
void* cfs_hash_del (struct cfs_hash * hs, const void * key, struct hlist_node * hnode)
Delete item from the libcfs hash using .
The is required to ensure the correct hash bucket is locked since there is no direct linkage from the item to the bucket. The object removed from the hash will be returned and obs->hs_put is called on the removed object.
Definition at line 1291 of file hash.c.
References cfs_hash_bd::bd_bucket, cfs_hash_bd_del_locked(), cfs_hash_dual_bd_finddel_locked(), cfs_hash_dual_bd_get_and_lock(), cfs_hash_dual_bd_unlock(), cfs_hash_lock(), cfs_hash_object(), cfs_hash_rehash(), cfs_hash_rehash_bits(), cfs_hash_rehash_inline(), cfs_hash_unlock(), and hlist_unhashed().
Referenced by cfs_hash_del_key(), cl_env_do_detach(), class_disconnect(), class_new_export(), class_unlink_export(), ldlm_flock_blocking_unlink(), ldlm_lock_destroy_internal(), qmt_pool_fini(), and tgt_client_free().
void* cfs_hash_del_key (struct cfs_hash * hs, const void * key)
Delete item given in libcfs hash .
The first found in the hash will be removed, if the key exists multiple times in the hash this function must be called once per key. The removed object will be returned and ops->hs_put is called on the removed object.
Definition at line 1331 of file hash.c.
References cfs_hash_del().
Referenced by lod_pool_del(), lov_pool_del(), nodemap_del(), and osc_quota_setdq().
static void cfs_hash_depth_wi_cancel (struct cfs_hash * hs) [inline, static]
Definition at line 998 of file hash.c.
Referenced by cfs_hash_destroy().
static void cfs_hash_depth_wi_init (struct cfs_hash * hs) [inline, static]
Definition at line 997 of file hash.c.
Referenced by cfs_hash_create().
static void cfs_hash_destroy (struct cfs_hash * hs) [static]
Cleanup libcfs hash .
prohibit further rehashes, don't need any lock because I'm the only (last) one can change it.
Definition at line 1079 of file hash.c.
References cfs_hash_bd::bd_bucket, cfs_hash_bd::bd_offset, cfs_hash_bd_del_locked(), cfs_hash_bd_for_each_hlist, cfs_hash_bd_lock(), cfs_hash_bd_unlock(), CFS_HASH_BIGNAME_LEN, cfs_hash_bkt_size(), cfs_hash_buckets_free(), cfs_hash_depth_wi_cancel(), cfs_hash_exit(), cfs_hash_for_each_bucket, cfs_hash_is_exiting(), cfs_hash_is_iterating(), CFS_HASH_NAME_LEN, CFS_HASH_NBKT, cfs_hash_rehash_cancel(), cfs_hash_with_assert_empty(), cfs_hash_with_bigname(), cfs_hash_with_rehash(), ENTRY, EXIT, hlist_for_each_safe, cfs_hash::hs_buckets, cfs_hash::hs_count, cfs_hash::hs_exiting, cfs_hash::hs_name, cfs_hash::hs_rehash_buckets, cfs_hash_bucket::hsb_count, cfs_hash_bucket::hsb_index, LASSERT, LASSERTF, LIBCFS_FREE, and offsetof.
Referenced by cfs_hash_putref().
static struct hlist_head* cfs_hash_dh_hhead (struct cfs_hash * hs, struct cfs_hash_bd * bd) [static, read]
Definition at line 341 of file hash.c.
References cfs_hash_bd::bd_bucket, cfs_hash_bd::bd_offset, cfs_hash_dhead::dh_head, head, and cfs_hash_bucket::hsb_head.
Referenced by cfs_hash_dh_hnode_add(), and cfs_hash_dh_hnode_del().
static int cfs_hash_dh_hhead_size (struct cfs_hash * hs) [static]
Definition at line 335 of file hash.c.
static int cfs_hash_dh_hnode_add (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode) [static]
Definition at line 350 of file hash.c.
References cfs_hash_dh_hhead(), cfs_hash_dhead::dh_head, cfs_hash_dhead::dh_tail, and hlist_add_head().
static int cfs_hash_dh_hnode_del (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnd) [static]
Definition at line 366 of file hash.c.
References cfs_hash_dh_hhead(), cfs_hash_dhead::dh_head, cfs_hash_dhead::dh_tail, hlist_head::first, hlist_del_init(), hlist_node::next, and hlist_node::pprev.
struct hlist_node* cfs_hash_dual_bd_findadd_locked (struct cfs_hash * hs, struct cfs_hash_bd * bds, const void * key, struct hlist_node * hnode, int noref) [read]
Definition at line 853 of file hash.c.
References cfs_hash_multi_bd_findadd_locked().
Referenced by cfs_hash_find_or_add().
struct hlist_node* cfs_hash_dual_bd_finddel_locked (struct cfs_hash * hs, struct cfs_hash_bd * bds, const void * key, struct hlist_node * hnode) [read]
Definition at line 862 of file hash.c.
References cfs_hash_multi_bd_finddel_locked().
Referenced by cfs_hash_del(), and cfs_hash_rehash_key().
void cfs_hash_dual_bd_get (struct cfs_hash * hs, const void * key, struct cfs_hash_bd * bds)
operations on cfs_hash bucket (bd: bucket descriptor), they are safe for hash-table with rehash
Definition at line 814 of file hash.c.
References cfs_hash_bd::bd_bucket, cfs_hash_bd_from_key(), cfs_hash_bd_order(), cfs_hash::hs_buckets, cfs_hash::hs_cur_bits, cfs_hash::hs_rehash_bits, cfs_hash::hs_rehash_buckets, LASSERT, and likely.
Referenced by cfs_hash_dual_bd_get_and_lock(), and cfs_hash_rehash_key().
void cfs_hash_dual_bd_lock (struct cfs_hash * hs, struct cfs_hash_bd * bds, int excl)
Definition at line 834 of file hash.c.
References cfs_hash_multi_bd_lock().
Referenced by cfs_hash_dual_bd_get_and_lock().
struct hlist_node* cfs_hash_dual_bd_lookup_locked (struct cfs_hash * hs, struct cfs_hash_bd * bds, const void * key) [read]
Definition at line 846 of file hash.c.
References cfs_hash_multi_bd_lookup_locked().
Referenced by cfs_hash_lookup().
void cfs_hash_dual_bd_unlock (struct cfs_hash * hs, struct cfs_hash_bd * bds, int excl)
Definition at line 840 of file hash.c.
References cfs_hash_multi_bd_unlock().
Referenced by cfs_hash_del(), cfs_hash_find_or_add(), cfs_hash_for_each_key(), and cfs_hash_lookup().
static struct hlist_node* cfs_hash_find_or_add (struct cfs_hash * hs, const void * key, struct hlist_node * hnode, int noref) [static, read]
Definition at line 1227 of file hash.c.
References cfs_hash_dual_bd_findadd_locked(), cfs_hash_dual_bd_get_and_lock(), cfs_hash_dual_bd_unlock(), cfs_hash_key_validate(), cfs_hash_lock(), cfs_hash_rehash(), cfs_hash_rehash_bits(), cfs_hash_rehash_inline(), cfs_hash_unlock(), hlist_unhashed(), and LASSERTF.
Referenced by cfs_hash_add_unique(), and cfs_hash_findadd_unique().
void* cfs_hash_findadd_unique (struct cfs_hash * hs, const void * key, struct hlist_node * hnode)
Add item to libcfs hash using .
If this already exists in the hash then ops->hs_get will be called on the conflicting entry and that entry will be returned to the caller. Otherwise ops->hs_get is called on the item which was added.
Definition at line 1274 of file hash.c.
References cfs_hash_find_or_add(), and cfs_hash_object().
Referenced by lqe_locate(), and ptlrpc_connection_get().
void cfs_hash_for_each (struct cfs_hash * hs, cfs_hash_for_each_cb_t func, void * data)
Definition at line 1511 of file hash.c.
References cfs_hash_for_each_tight().
Referenced by lu_site_print().
int cfs_hash_for_each_empty (struct cfs_hash * hs, cfs_hash_for_each_cb_t func, void * data)
For each hash bucket in the libcfs hash call the passed callback until all the hash buckets are empty.
The passed callback or the previously registered callback hs->hs_put must remove the item from the hash. You may either use the cfs_hash_del() or hlist_del() functions. No rwlocks will be held during the callback it is safe to sleep if needed. This function will not terminate until the hash is empty. Note it is still possible to concurrently add new items in to the hash. It is the callers responsibility to ensure the required locking is in place to prevent concurrent insertions.
Definition at line 1698 of file hash.c.
References CDEBUG, cfs_hash_for_each_enter(), cfs_hash_for_each_exit(), cfs_hash_for_each_relax(), cfs_hash_with_no_lock(), D_INFO, ENTRY, cfs_hash_ops::hs_get, cfs_hash::hs_name, cfs_hash::hs_ops, cfs_hash_ops::hs_put, cfs_hash_ops::hs_put_locked, and RETURN.
Referenced by ldlm_export_cancel_locks().
static void cfs_hash_for_each_enter (struct cfs_hash * hs) [static]
Definition at line 1367 of file hash.c.
References cfs_hash_is_exiting(), cfs_hash_is_rehashing(), cfs_hash_lock(), cfs_hash_rehash_cancel_locked(), cfs_hash_unlock(), cfs_hash_with_rehash(), cfs_hash::hs_iterating, cfs_hash::hs_iterators, and LASSERT.
Referenced by cfs_hash_for_each_empty(), cfs_hash_for_each_nolock(), cfs_hash_for_each_tight(), and cfs_hash_hlist_for_each().
static void cfs_hash_for_each_exit (struct cfs_hash * hs) [static]
Definition at line 1393 of file hash.c.
References cfs_hash_lock(), CFS_HASH_LOOP_HOG, cfs_hash_rehash(), cfs_hash_rehash_bits(), cfs_hash_unlock(), cfs_hash_with_rehash(), cfs_hash::hs_count, cfs_hash::hs_iterating, and cfs_hash::hs_iterators.
Referenced by cfs_hash_for_each_empty(), cfs_hash_for_each_nolock(), cfs_hash_for_each_tight(), and cfs_hash_hlist_for_each().
void cfs_hash_for_each_key (struct cfs_hash * hs, const void * key, cfs_hash_for_each_cb_t func, void * data)
Definition at line 1758 of file hash.c.
References cfs_hash_bd_hhead(), cfs_hash_bucket_validate(), cfs_hash_dual_bd_get_and_lock(), cfs_hash_dual_bd_unlock(), cfs_hash_for_each_bd, cfs_hash_keycmp(), cfs_hash_lock(), cfs_hash_unlock(), and hlist_for_each.
Referenced by ldlm_flock_deadlock(), and lprocfs_mdt_open_files_seq_show().
int cfs_hash_for_each_nolock (struct cfs_hash * hs, cfs_hash_for_each_cb_t func, void * data, int start)
Definition at line 1663 of file hash.c.
References cfs_hash_for_each_enter(), cfs_hash_for_each_exit(), cfs_hash_for_each_relax(), cfs_hash_with_no_itemref(), cfs_hash_with_no_lock(), cfs_hash_with_rehash_key(), ENTRY, cfs_hash_ops::hs_get, cfs_hash::hs_ops, cfs_hash_ops::hs_put, cfs_hash_ops::hs_put_locked, and RETURN.
Referenced by ldlm_cli_cancel_unused(), ldlm_namespace_cleanup(), ldlm_namespace_dump(), ldlm_namespace_foreach(), ldlm_reprocess_all_ns(), and osc_import_event().
static int cfs_hash_for_each_relax (struct cfs_hash * hs, cfs_hash_for_each_cb_t func, void * data, int start) [static]
Definition at line 1569 of file hash.c.
References cfs_hash_bd_for_each_hlist, cfs_hash_bd_lock(), cfs_hash_bd_unlock(), cfs_hash_bd_version_get(), cfs_hash_bucket_validate(), cfs_hash_for_each_bucket, cfs_hash_get(), cfs_hash_is_rehashing(), cfs_hash_lock(), cfs_hash_put(), cfs_hash_put_locked(), cfs_hash_unlock(), cfs_hash_with_no_itemref(), cfs_hash_with_rehash_key(), end, ENTRY, hlist_head::first, cfs_hash::hs_ops, cfs_hash_ops::hs_put_locked, LASSERT, hlist_node::next, and version.
Referenced by cfs_hash_for_each_empty(), and cfs_hash_for_each_nolock().
void cfs_hash_for_each_safe (struct cfs_hash * hs, cfs_hash_for_each_cb_t func, void * data)
Definition at line 1519 of file hash.c.
References cfs_hash_for_each_tight().
Referenced by lqe_cleanup(), nm_member_revoke_all(), nodemap_config_cleanup(), nodemap_config_set_active(), and qsd_pending_updates().
static __u64 cfs_hash_for_each_tight (struct cfs_hash * hs, cfs_hash_for_each_cb_t func, void * data, int remove_safe) [static]
For each item in the libcfs hash call the passed callback and pass to it as an argument each hash item and the private .
a) the function may sleep! b) during the callback: . the bucket lock is held so the callback must never sleep. . if is true, use can remove current item by cfs_hash_bd_del_locked
Definition at line 1424 of file hash.c.
References __u64, cfs_hash_bd::bd_bucket, cfs_hash_bd_for_each_hlist, cfs_hash_bd_lock(), cfs_hash_bd_unlock(), cfs_hash_bucket_validate(), cfs_hash_for_each_bucket, cfs_hash_for_each_enter(), cfs_hash_for_each_exit(), cfs_hash_is_rehashing(), cfs_hash_lock(), CFS_HASH_LOOP_HOG, cfs_hash_unlock(), ENTRY, hlist_for_each_safe, cfs_hash_bucket::hsb_count, LASSERT, and RETURN.
Referenced by cfs_hash_cond_del(), cfs_hash_for_each(), cfs_hash_for_each_safe(), cfs_hash_is_empty(), and cfs_hash_size_get().
static struct cfs_hash_bucket** cfs_hash_full_bkts (struct cfs_hash * hs) [static, read]
Definition at line 2050 of file hash.c.
References cfs_hash::hs_buckets, cfs_hash::hs_cur_bits, cfs_hash::hs_rehash_bits, cfs_hash::hs_rehash_buckets, and LASSERT.
Referenced by cfs_hash_debug_str().
static unsigned int cfs_hash_full_nbkt (struct cfs_hash * hs) [static]
Definition at line 2062 of file hash.c.
References CFS_HASH_NBKT, CFS_HASH_RH_NBKT, cfs_hash::hs_cur_bits, cfs_hash::hs_rehash_bits, cfs_hash::hs_rehash_buckets, and LASSERT.
Referenced by cfs_hash_debug_str().
struct cfs_hash* cfs_hash_getref (struct cfs_hash * hs) [read]
Definition at line 1140 of file hash.c.
References cfs_hash::hs_refcount.
Referenced by class_new_export(), class_unlink_export(), obd_export_evict_by_nid(), obd_export_evict_by_uuid(), tgt_clients_data_init(), tgt_reply_data_init(), and update_recovery_update_ses().
static struct hlist_head* cfs_hash_hd_hhead (struct cfs_hash * hs, struct cfs_hash_bd * bd) [static, read]
Definition at line 293 of file hash.c.
References cfs_hash_bd::bd_bucket, cfs_hash_bd::bd_offset, cfs_hash_head_dep::hd_head, head, and cfs_hash_bucket::hsb_head.
Referenced by cfs_hash_hd_hnode_add(), and cfs_hash_hd_hnode_del().
static int cfs_hash_hd_hhead_size (struct cfs_hash * hs) [static]
Definition at line 287 of file hash.c.
static int cfs_hash_hd_hnode_add (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode) [static]
Definition at line 302 of file hash.c.
References cfs_hash_hd_hhead(), cfs_hash_head_dep::hd_depth, cfs_hash_head_dep::hd_head, and hlist_add_head().
static int cfs_hash_hd_hnode_del (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode) [static]
Definition at line 314 of file hash.c.
References cfs_hash_hd_hhead(), cfs_hash_head_dep::hd_depth, cfs_hash_head_dep::hd_head, and hlist_del_init().
static struct hlist_head* cfs_hash_hh_hhead (struct cfs_hash * hs, struct cfs_hash_bd * bd) [static, read]
Definition at line 253 of file hash.c.
References cfs_hash_bd::bd_bucket, cfs_hash_bd::bd_offset, head, cfs_hash_head::hh_head, and cfs_hash_bucket::hsb_head.
Referenced by cfs_hash_hh_hnode_add().
static int cfs_hash_hh_hhead_size (struct cfs_hash * hs) [static]
Definition at line 247 of file hash.c.
static int cfs_hash_hh_hnode_add (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode) [static]
Definition at line 262 of file hash.c.
References cfs_hash_hh_hhead(), and hlist_add_head().
static int cfs_hash_hh_hnode_del (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode) [static]
Definition at line 270 of file hash.c.
References hlist_del_init().
void cfs_hash_hlist_for_each (struct cfs_hash * hs, unsigned hindex, cfs_hash_for_each_cb_t func, void * data)
Definition at line 1723 of file hash.c.
References cfs_hash_bd_hhead(), cfs_hash_bd_index_set(), cfs_hash_bd_lock(), cfs_hash_bd_unlock(), cfs_hash_for_each_enter(), cfs_hash_for_each_exit(), cfs_hash_lock(), CFS_HASH_NHLIST, cfs_hash_unlock(), and hlist_for_each.
Referenced by vvp_pgcache_obj().
static void cfs_hash_hlist_setup (struct cfs_hash * hs) [static]
Definition at line 467 of file hash.c.
References cfs_hash_with_add_tail(), cfs_hash_with_depth(), and cfs_hash::hs_hops.
Referenced by cfs_hash_create().
int cfs_hash_is_empty (struct cfs_hash * hs)
Definition at line 1535 of file hash.c.
References cfs_hash_for_each_tight(), cfs_hash_peek(), and empty.
Referenced by mgs_device_fini(), mgs_init0(), ofd_stack_fini(), and osd_device_free().
static void cfs_hash_lock_setup (struct cfs_hash * hs) [static]
Definition at line 210 of file hash.c.
References cfs_hash_with_no_bktlock(), cfs_hash_with_no_lock(), cfs_hash_with_rehash(), cfs_hash_with_rw_bktlock(), cfs_hash_with_spin_bktlock(), cfs_hash::hs_lock, cfs_hash::hs_lops, LBUG, cfs_hash_lock::rw, and cfs_hash_lock::spin.
Referenced by cfs_hash_create().
void* cfs_hash_lookup (struct cfs_hash * hs, const void * key)
Lookup an item using in the libcfs hash and return it.
If the is found in the hash hs->hs_get() is called and the matching objects is returned. It is the callers responsibility to call the counterpart ops->hs_put using the cfs_hash_put() macro when when finished with the object. If the was not found in the hash NULL is returned.
Definition at line 1346 of file hash.c.
References cfs_hash_dual_bd_get_and_lock(), cfs_hash_dual_bd_lookup_locked(), cfs_hash_dual_bd_unlock(), cfs_hash_lock(), cfs_hash_object(), and cfs_hash_unlock().
Referenced by cl_env_fetch(), ldlm_flock_lookup_cb(), lod_find_pool(), lod_pool_add(), lod_pool_remove(), lov_pool_add(), lov_pool_remove(), lqe_locate(), lustre_register_lwp_item(), mdt_hsm_agent_send(), nodemap_config_set_active(), nodemap_lookup(), nodemap_process_keyrec(), obd_export_evict_by_nid(), obd_export_evict_by_uuid(), osc_quota_chkdq(), osc_quota_setdq(), ptlrpc_connection_get(), qmt_pool_lookup(), tgt_reply_data_init(), and update_recovery_update_ses().
static struct hlist_node* cfs_hash_multi_bd_findadd_locked (struct cfs_hash * hs, struct cfs_hash_bd * bds, unsigned n, const void * key, struct hlist_node * hnode, int noref) [static, read]
Definition at line 739 of file hash.c.
References cfs_hash_bd_add_locked(), cfs_hash_bd_get(), cfs_hash_bd_lookup_intent(), cfs_hash_for_each_bd, CFS_HS_LOOKUP_IT_PEEK, CFS_HS_LOOKUP_MASK_REF, and LASSERT.
Referenced by cfs_hash_dual_bd_findadd_locked().
static struct hlist_node* cfs_hash_multi_bd_finddel_locked (struct cfs_hash * hs, struct cfs_hash_bd * bds, unsigned n, const void * key, struct hlist_node * hnode) [static, read]
Definition at line 770 of file hash.c.
References cfs_hash_bd_lookup_intent(), cfs_hash_for_each_bd, and CFS_HS_LOOKUP_IT_FINDDEL.
Referenced by cfs_hash_dual_bd_finddel_locked().
static void cfs_hash_multi_bd_lock (struct cfs_hash * hs, struct cfs_hash_bd * bds, unsigned n, int excl) [static]
bds must be ascendantly ordered by bd->bd_bucket->hsb_index. NB: it's possible that several bds point to the same bucket but have different bd::bd_offset, so need take care of deadlock.
Definition at line 685 of file hash.c.
References cfs_hash_bd::bd_bucket, cfs_hash_bd_lock(), cfs_hash_for_each_bd, cfs_hash_bucket::hsb_index, and LASSERT.
Referenced by cfs_hash_dual_bd_lock(), and cfs_hash_rehash_key().
static struct hlist_node* cfs_hash_multi_bd_lookup_locked (struct cfs_hash * hs, struct cfs_hash_bd * bds, unsigned n, const void * key) [static, read]
Definition at line 723 of file hash.c.
References cfs_hash_bd_lookup_intent(), cfs_hash_for_each_bd, and CFS_HS_LOOKUP_IT_FIND.
Referenced by cfs_hash_dual_bd_lookup_locked().
static void cfs_hash_multi_bd_unlock (struct cfs_hash * hs, struct cfs_hash_bd * bds, unsigned n, int excl) [static]
Definition at line 708 of file hash.c.
References cfs_hash_bd::bd_bucket, cfs_hash_bd_unlock(), and cfs_hash_for_each_bd.
Referenced by cfs_hash_dual_bd_unlock(), and cfs_hash_rehash_key().
static void cfs_hash_nl_lock (union cfs_hash_lock * lock, int exclusive) [inline, static]
Definition at line 122 of file hash.c.
static void cfs_hash_nl_unlock (union cfs_hash_lock * lock, int exclusive) [inline, static]
Definition at line 125 of file hash.c.
static int cfs_hash_peek (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode, void * data) [static]
Definition at line 1527 of file hash.c.
Referenced by cfs_hash_is_empty().
void cfs_hash_putref (struct cfs_hash * hs)
Definition at line 1148 of file hash.c.
References cfs_hash_destroy(), and cfs_hash::hs_refcount.
Referenced by cl_env_store_fini(), class_cleanup(), class_new_export(), class_setup(), class_unlink_export(), ldlm_destroy_export(), ldlm_destroy_flock_export(), ldlm_namespace_free_post(), ldlm_namespace_new(), lod_pools_fini(), lod_pools_init(), lov_cleanup(), lquota_site_free(), lu_site_fini(), lu_site_init(), nodemap_config_cleanup(), obd_export_evict_by_nid(), obd_export_evict_by_uuid(), osc_quota_cleanup(), osc_quota_setup(), ptlrpc_connection_fini(), qmt_pool_fini(), tgt_clients_data_init(), tgt_reply_data_init(), and update_recovery_update_ses().
int cfs_hash_rehash (struct cfs_hash * hs, int do_rehash)
Definition at line 1835 of file hash.c.
References cfs_hash_lock(), cfs_hash_rehash_bits(), cfs_hash_rehash_worker(), cfs_hash_unlock(), cfs_hash_with_no_lock(), cfs_hash_with_rehash(), cfs_wi_schedule(), cfs_hash::hs_rehash_bits, cfs_hash::hs_rehash_wi, and LASSERT.
Referenced by cfs_hash_add(), cfs_hash_del(), cfs_hash_find_or_add(), and cfs_hash_for_each_exit().
static int cfs_hash_rehash_bd (struct cfs_hash * hs, struct cfs_hash_bd * old) [static]
Definition at line 1864 of file hash.c.
References cfs_hash_bd_for_each_hlist, cfs_hash_bd_from_key(), cfs_hash_bd_move_locked(), cfs_hash_bucket_validate(), cfs_hash_key(), hlist_for_each_safe, cfs_hash::hs_rehash_bits, cfs_hash::hs_rehash_buckets, and LASSERT.
Referenced by cfs_hash_rehash_worker().
static int cfs_hash_rehash_bits (struct cfs_hash * hs) [inline, static]
Definition at line 1156 of file hash.c.
References __cfs_hash_theta(), cfs_hash_is_exiting(), cfs_hash_is_iterating(), cfs_hash_is_rehashing(), cfs_hash_with_no_lock(), cfs_hash_with_rehash(), cfs_hash_with_shrink(), cfs_hash::hs_cur_bits, cfs_hash::hs_max_bits, cfs_hash::hs_max_theta, cfs_hash::hs_min_bits, cfs_hash::hs_min_theta, and unlikely.
Referenced by cfs_hash_add(), cfs_hash_del(), cfs_hash_find_or_add(), cfs_hash_for_each_exit(), and cfs_hash_rehash().
void cfs_hash_rehash_cancel (struct cfs_hash * hs)
Definition at line 1827 of file hash.c.
References cfs_hash_lock(), cfs_hash_rehash_cancel_locked(), and cfs_hash_unlock().
Referenced by cfs_hash_destroy().
void cfs_hash_rehash_cancel_locked (struct cfs_hash * hs)
Rehash the libcfs hash to the given .
This can be used to grow the hash size when excessive chaining is detected, or to shrink the hash when it is larger than needed. When the CFS_HASH_REHASH flag is set in the libcfs hash may be dynamically rehashed during addition or removal if the hash's theta value exceeds either the hs->hs_min_theta or hs->max_theta values. By default these values are tuned to keep the chained hash depth small, and this approach assumes a reasonably uniform hashing function. The theta thresholds for are tunable via cfs_hash_set_theta().
Definition at line 1799 of file hash.c.
References CDEBUG, cfs_hash_is_rehashing(), cfs_hash_lock(), cfs_hash_unlock(), cfs_hash_with_no_lock(), cfs_hash_with_rehash(), cfs_wi_deschedule(), D_INFO, D_WARNING, cfs_hash::hs_name, cfs_hash::hs_rehash_bits, cfs_hash::hs_rehash_wi, and LASSERT.
Referenced by cfs_hash_for_each_enter(), and cfs_hash_rehash_cancel().
static int cfs_hash_rehash_inline (struct cfs_hash * hs) [inline, static]
don't allow inline rehash if:
user wants non-blocking change (add/del) on hash table
too many elements
Definition at line 1193 of file hash.c.
References CFS_HASH_LOOP_HOG, cfs_hash_with_nblk_change(), and cfs_hash::hs_count.
Referenced by cfs_hash_add(), cfs_hash_del(), and cfs_hash_find_or_add().
void cfs_hash_rehash_key (struct cfs_hash * hs, const void * old_key, void * new_key, struct hlist_node * hnode)
Rehash the object referenced by in the libcfs hash .
The must be provided to locate the objects previous location in the hash, and the will be used to reinsert the object. Use this function instead of a cfs_hash_add() + cfs_hash_del() combo when it is critical that there is no window in time where the object is missing from the hash. When an object is being rehashed the registered cfs_hash_get() and cfs_hash_put() functions will not be called.
Definition at line 2004 of file hash.c.
References cfs_hash_bd::bd_bucket, cfs_hash_bd_add_locked(), cfs_hash_bd_get(), cfs_hash_bd_move_locked(), cfs_hash_bd_order(), cfs_hash_dual_bd_finddel_locked(), cfs_hash_dual_bd_get(), cfs_hash_keycpy(), cfs_hash_lock(), cfs_hash_multi_bd_lock(), cfs_hash_multi_bd_unlock(), cfs_hash_unlock(), hlist_unhashed(), LASSERT, and likely.
Referenced by ldlm_cli_enqueue_fini(), and replay_lock_interpret().
static int cfs_hash_rehash_worker (struct cfs_workitem * wi) [static]
Definition at line 1894 of file hash.c.
References __cfs_hash_theta(), CDEBUG, cfs_hash_bkt_size(), cfs_hash_buckets_free(), cfs_hash_buckets_realloc(), cfs_hash_for_each_bucket, cfs_hash_is_exiting(), cfs_hash_is_iterating(), cfs_hash_is_rehashing(), cfs_hash_lock(), CFS_HASH_LOOP_HOG, CFS_HASH_NBKT, cfs_hash_rehash_bd(), CFS_HASH_RH_NBKT, cfs_hash_unlock(), cfs_hash_with_rehash(), cfs_wi_exit(), D_INFO, cfs_hash::hs_buckets, cfs_hash::hs_cur_bits, cfs_hash::hs_min_theta, cfs_hash::hs_rehash_bits, cfs_hash::hs_rehash_buckets, cfs_hash::hs_rehash_count, cfs_hash::hs_rehash_wi, and LASSERT.
Referenced by cfs_hash_create(), and cfs_hash_rehash().
static void cfs_hash_rw_lock (union cfs_hash_lock * lock, int exclusive) [inline, static]
Definition at line 142 of file hash.c.
static void cfs_hash_rw_unlock (union cfs_hash_lock * lock, int exclusive) [inline, static]
Definition at line 152 of file hash.c.
__u64 cfs_hash_size_get (struct cfs_hash * hs)
Definition at line 1545 of file hash.c.
References cfs_hash_for_each_tight(), cfs_hash_with_counter(), and cfs_hash::hs_count.
Referenced by lu_object_limit().
static void cfs_hash_spin_lock (union cfs_hash_lock * lock, int exclusive) [inline, static]
Definition at line 128 of file hash.c.
static void cfs_hash_spin_unlock (union cfs_hash_lock * lock, int exclusive) [inline, static]
Definition at line 135 of file hash.c.
Variable Documentation
struct cfs_hash_lock_ops cfs_hash_bkt_rw_lops [static]
Initial value:
 {
        .hs_lock        = cfs_hash_rw_lock,
        .hs_unlock      = cfs_hash_rw_unlock,
        .hs_bkt_lock    = cfs_hash_rw_lock,
        .hs_bkt_unlock  = cfs_hash_rw_unlock,
}
rw bucket lock, rehash is enabled
Definition at line 186 of file hash.c.
struct cfs_hash_lock_ops cfs_hash_bkt_spin_lops [static]
Initial value:
 {
        .hs_lock        = cfs_hash_rw_lock,
        .hs_unlock      = cfs_hash_rw_unlock,
        .hs_bkt_lock    = cfs_hash_spin_lock,
        .hs_bkt_unlock  = cfs_hash_spin_unlock,
}
spin bucket lock, rehash is enabled
Definition at line 178 of file hash.c.
struct cfs_hash_hlist_ops cfs_hash_dd_hops [static]
Initial value:
 {
       .hop_hhead      = cfs_hash_dd_hhead,
       .hop_hhead_size = cfs_hash_dd_hhead_size,
       .hop_hnode_add  = cfs_hash_dd_hnode_add,
       .hop_hnode_del  = cfs_hash_dd_hnode_del,
}
Definition at line 459 of file hash.c.
struct cfs_hash_hlist_ops cfs_hash_dh_hops [static]
Initial value:
 {
       .hop_hhead      = cfs_hash_dh_hhead,
       .hop_hhead_size = cfs_hash_dh_hhead_size,
       .hop_hnode_add  = cfs_hash_dh_hnode_add,
       .hop_hnode_del  = cfs_hash_dh_hnode_del,
}
Definition at line 452 of file hash.c.
struct cfs_hash_hlist_ops cfs_hash_hd_hops [static]
Initial value:
 {
       .hop_hhead      = cfs_hash_hd_hhead,
       .hop_hhead_size = cfs_hash_hd_hhead_size,
       .hop_hnode_add  = cfs_hash_hd_hnode_add,
       .hop_hnode_del  = cfs_hash_hd_hnode_del,
}
Definition at line 445 of file hash.c.
struct cfs_hash_hlist_ops cfs_hash_hh_hops [static]
Initial value:
 {
       .hop_hhead      = cfs_hash_hh_hhead,
       .hop_hhead_size = cfs_hash_hh_hhead_size,
       .hop_hnode_add  = cfs_hash_hh_hnode_add,
       .hop_hnode_del  = cfs_hash_hh_hnode_del,
}
Definition at line 438 of file hash.c.
struct cfs_hash_lock_ops cfs_hash_nbl_lops [static]
Initial value:
 {
        .hs_lock        = cfs_hash_spin_lock,
        .hs_unlock      = cfs_hash_spin_unlock,
        .hs_bkt_lock    = cfs_hash_nl_lock,
        .hs_bkt_unlock  = cfs_hash_nl_unlock,
}
no bucket lock, one spinlock to protect everything
Definition at line 170 of file hash.c.
struct cfs_hash_lock_ops cfs_hash_nl_lops [static]
Initial value:
 {
        .hs_lock        = cfs_hash_nl_lock,
        .hs_unlock      = cfs_hash_nl_unlock,
        .hs_bkt_lock    = cfs_hash_nl_lock,
        .hs_bkt_unlock  = cfs_hash_nl_unlock,
}
No lock hash.
Definition at line 162 of file hash.c.
struct cfs_hash_lock_ops cfs_hash_nr_bkt_rw_lops [static]
Initial value:
 {
        .hs_lock        = cfs_hash_nl_lock,
        .hs_unlock      = cfs_hash_nl_unlock,
        .hs_bkt_lock    = cfs_hash_rw_lock,
        .hs_bkt_unlock  = cfs_hash_rw_unlock,
}
rw bucket lock, rehash is disabled
Definition at line 202 of file hash.c.
struct cfs_hash_lock_ops cfs_hash_nr_bkt_spin_lops [static]
Initial value:
 {
        .hs_lock        = cfs_hash_nl_lock,
        .hs_unlock      = cfs_hash_nl_unlock,
        .hs_bkt_lock    = cfs_hash_spin_lock,
        .hs_bkt_unlock  = cfs_hash_spin_unlock,
}
spin bucket lock, rehash is disabled
Definition at line 194 of file hash.c.
struct cfs_wi_sched* cfs_sched_rehash
Definition at line 119 of file hash.c.
Referenced by libcfs_exit(), and libcfs_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.