Lustre: lustre/tests/iam_ut.c File Reference
lustre/tests/iam_ut.c File Reference
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <fcntl.h>
#include <string.h>
#include <errno.h>
#include <assert.h>
#include <sys/types.h>
Data Structures
struct iam_uapi_info
struct iam_uapi_op
struct iam_uapi_it
Enumerations
enum { DX_FMT_NAME_LEN = 16 }
enum iam_ioctl_cmd {
IAM_IOC_INIT = _IOW('i', 1, struct iam_uapi_info), IAM_IOC_GETINFO = _IOR('i', 2, struct iam_uapi_info), IAM_IOC_INSERT = _IOR('i', 3, struct iam_uapi_op), IAM_IOC_LOOKUP = _IOWR('i', 4, struct iam_uapi_op),
IAM_IOC_DELETE = _IOR('i', 5, struct iam_uapi_op), IAM_IOC_IT_START = _IOR('i', 6, struct iam_uapi_it), IAM_IOC_IT_NEXT = _IOW('i', 7, struct iam_uapi_it), IAM_IOC_IT_STOP = _IOR('i', 8, struct iam_uapi_it),
IAM_IOC_POLYMORPH = _IOR('i', 9, unsigned long), IAM_IOC_INIT = _IOW('i', 1, struct iam_uapi_info), IAM_IOC_GETINFO = _IOR('i', 2, struct iam_uapi_info), IAM_IOC_INSERT = _IOR('i', 3, struct iam_uapi_op),
IAM_IOC_LOOKUP = _IOWR('i', 4, struct iam_uapi_op), IAM_IOC_DELETE = _IOR('i', 5, struct iam_uapi_op), IAM_IOC_IT_START = _IOR('i', 6, struct iam_uapi_it), IAM_IOC_IT_NEXT = _IOW('i', 7, struct iam_uapi_it),
IAM_IOC_IT_STOP = _IOR('i', 8, struct iam_uapi_it), IAM_IOC_POLYMORPH = _IOR('i', 9, unsigned long), IAM_IOC_INIT = _IOW('i', 1, struct iam_uapi_info), IAM_IOC_GETINFO = _IOR('i', 2, struct iam_uapi_info),
IAM_IOC_INSERT = _IOR('i', 3, struct iam_uapi_op), IAM_IOC_LOOKUP = _IOWR('i', 4, struct iam_uapi_op), IAM_IOC_DELETE = _IOR('i', 5, struct iam_uapi_op), IAM_IOC_IT_START = _IOR('i', 6, struct iam_uapi_it),
IAM_IOC_IT_NEXT = _IOW('i', 7, struct iam_uapi_it), IAM_IOC_IT_STOP = _IOR('i', 8, struct iam_uapi_it), IAM_IOC_POLYMORPH = _IOR('i', 9, unsigned long)
}
enum op {
OP_TEST, OP_INSERT, OP_LOOKUP, OP_DELETE,
OP_IT_START, OP_IT_NEXT, OP_IT_STOP
}
Functions
static void usage (void)
static int doop (int fd, const void *key, const void *rec, int cmd, const char *name)
static int doit (int fd, const void *key, const void *rec, int cmd, const char *name)
static int insert (int fd, const void *key, const void *rec)
static int lookup (int fd, const void *key, void *rec)
static int delete (int fd, const void *key, void *rec)
static int rec_is_nul_term (int recsize)
static void print_rec (const unsigned char *rec, int nr)
unsigned char hex2dec (unsigned char hex)
unsigned char * packdigit (unsigned char *number)
int main (int argc, char **argv)
Enumeration Type Documentation
anonymous enum
Enumerator:
DX_FMT_NAME_LEN
Definition at line 56 of file iam_ut.c.
enum iam_ioctl_cmd
Enumerator:
IAM_IOC_INIT
IAM_IOC_GETINFO
IAM_IOC_INSERT
IAM_IOC_LOOKUP
IAM_IOC_DELETE
IAM_IOC_IT_START
IAM_IOC_IT_NEXT
IAM_IOC_IT_STOP
IAM_IOC_POLYMORPH
IAM_IOC_INIT
IAM_IOC_GETINFO
IAM_IOC_INSERT
IAM_IOC_LOOKUP
IAM_IOC_DELETE
IAM_IOC_IT_START
IAM_IOC_IT_NEXT
IAM_IOC_IT_STOP
IAM_IOC_POLYMORPH
IAM_IOC_INIT
IAM_IOC_GETINFO
IAM_IOC_INSERT
IAM_IOC_LOOKUP
IAM_IOC_DELETE
IAM_IOC_IT_START
IAM_IOC_IT_NEXT
IAM_IOC_IT_STOP
IAM_IOC_POLYMORPH
Definition at line 81 of file iam_ut.c.
enum op
Enumerator:
OP_TEST
OP_INSERT
OP_LOOKUP
OP_DELETE
OP_IT_START
OP_IT_NEXT
OP_IT_STOP
Definition at line 175 of file iam_ut.c.
Function Documentation
static int delete (int fd, const void * key, void * rec) [static]
Definition at line 147 of file iam_ut.c.
References doop(), and IAM_IOC_DELETE.
static int doit (int fd, const void * key, const void * rec, int cmd, const char * name) [static]
Definition at line 114 of file iam_ut.c.
References assert, iam_uapi_it::iui_op, iam_uapi_it::iui_state, and iam_uapi_op::iul_key.
static int doop (int fd, const void * key, const void * rec, int cmd, const char * name) [static]
Definition at line 99 of file iam_ut.c.
References iam_uapi_op::iul_key.
Referenced by delete(), insert(), lookup(), and main().
unsigned char hex2dec (unsigned char hex)
Definition at line 185 of file iam_ut.c.
Referenced by packdigit().
static int insert (int fd, const void * key, const void * rec) [static]
Definition at line 137 of file iam_ut.c.
References doop(), and IAM_IOC_INSERT.
Referenced by lfsck_rbtree_update_bitmap(), and main().
static int lookup (int fd, const void * key, void * rec) [static]
Definition at line 142 of file iam_ut.c.
References doop(), and IAM_IOC_LOOKUP.
Referenced by cl_env_peek(), cl_page_find(), iam_path_lookup(), main(), and mdd_parent_fid().
int main (int argc, char ** argv)
Definition at line 212 of file iam_ut.c.
References doop(), IAM_IOC_DELETE, IAM_IOC_GETINFO, IAM_IOC_INIT, IAM_IOC_INSERT, IAM_IOC_IT_NEXT, IAM_IOC_IT_START, IAM_IOC_IT_STOP, IAM_IOC_LOOKUP, IAM_IOC_POLYMORPH, insert(), iam_uapi_info::iui_fmt_name, iam_uapi_info::iui_height, iam_uapi_info::iui_keysize, iam_uapi_info::iui_ptrsize, iam_uapi_info::iui_recsize, lookup(), mode, OP_DELETE, OP_INSERT, OP_IT_NEXT, OP_IT_START, OP_IT_STOP, OP_LOOKUP, OP_TEST, opt, optarg, packdigit(), print_rec(), usage, and verbose.
unsigned char* packdigit (unsigned char * number)
Definition at line 199 of file iam_ut.c.
References hex2dec().
Referenced by iam_convert(), and main().
static void print_rec (const unsigned char * rec, int nr) [static]
Definition at line 157 of file iam_ut.c.
References rec_is_nul_term().
Referenced by main().
static int rec_is_nul_term (int recsize) [static]
Definition at line 152 of file iam_ut.c.
Referenced by print_rec().
static void usage (void) [static]
Definition at line 94 of file iam_ut.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.