Lustre: lustre/obdclass/idmap.c File Reference
lustre/obdclass/idmap.c File Reference
#include <linux/user_namespace.h>
#include <lustre_idmap.h>
#include <upcall_cache.h>
#include <md_object.h>
#include <obd_support.h>
Data Structures
struct lustre_idmap_entry
Defines
#define DEBUG_SUBSYSTEM S_SEC
#define lustre_get_group_info(group_info)
#define lustre_put_group_info(group_info)
Functions
static int lustre_groups_search (struct group_info *group_info, gid_t grp)
void lustre_groups_from_list (struct group_info *ginfo, gid_t *glist)
void lustre_groups_sort (struct group_info *group_info)
int lustre_in_group_p (struct lu_ucred *mu, gid_t grp)
static __u32 lustre_idmap_hashfunc (__u32 id)
static struct lustre_idmap_entry * idmap_entry_alloc (uid_t rmt_uid, uid_t lcl_uid, gid_t rmt_gid, gid_t lcl_gid)
static void idmap_entry_free (struct lustre_idmap_entry *e)
static struct lustre_idmap_entry * idmap_search_entry (struct lustre_idmap_table *t, uid_t rmt_uid, uid_t lcl_uid, gid_t rmt_gid, gid_t lcl_gid)
static __u32 idmap_lookup_uid (struct list_head *hash, int reverse, __u32 uid)
static __u32 idmap_lookup_gid (struct list_head *hash, int reverse, __u32 gid)
int lustre_idmap_add (struct lustre_idmap_table *t, uid_t ruid, uid_t luid, gid_t rgid, gid_t lgid)
int lustre_idmap_del (struct lustre_idmap_table *t, uid_t ruid, uid_t luid, gid_t rgid, gid_t lgid)
int lustre_idmap_lookup_uid (struct lu_ucred *mu, struct lustre_idmap_table *t, int reverse, uid_t uid)
int lustre_idmap_lookup_gid (struct lu_ucred *mu, struct lustre_idmap_table *t, int reverse, gid_t gid)
struct lustre_idmap_table * lustre_idmap_init (void)
void lustre_idmap_fini (struct lustre_idmap_table *t)
Define Documentation
#define DEBUG_SUBSYSTEM S_SEC
Definition at line 43 of file idmap.c.
#define lustre_get_group_info (group_info)
Value:
do {            \
        atomic_inc(&(group_info)->usage);               \
} while (0)
Definition at line 54 of file idmap.c.
Referenced by lustre_in_group_p().
#define lustre_put_group_info (group_info)
Value:
do {            \
        if (atomic_dec_and_test(&(group_info)->usage))  \
                groups_free(group_info);                \
} while (0)
Definition at line 58 of file idmap.c.
Referenced by lustre_in_group_p().
Function Documentation
static struct lustre_idmap_entry* idmap_entry_alloc (uid_t rmt_uid, uid_t lcl_uid, gid_t rmt_gid, gid_t lcl_gid) [static, read]
Definition at line 190 of file idmap.c.
References INIT_LIST_HEAD, lustre_idmap_entry::lie_lcl_gid, lustre_idmap_entry::lie_lcl_gid_hash, lustre_idmap_entry::lie_lcl_uid, lustre_idmap_entry::lie_lcl_uid_hash, lustre_idmap_entry::lie_rmt_gid, lustre_idmap_entry::lie_rmt_gid_hash, lustre_idmap_entry::lie_rmt_uid, lustre_idmap_entry::lie_rmt_uid_hash, and OBD_ALLOC_PTR.
Referenced by lustre_idmap_add().
static void idmap_entry_free (struct lustre_idmap_entry * e) [static]
Definition at line 211 of file idmap.c.
References lustre_idmap_entry::lie_lcl_gid_hash, lustre_idmap_entry::lie_lcl_uid_hash, lustre_idmap_entry::lie_rmt_gid_hash, lustre_idmap_entry::lie_rmt_uid_hash, list_del(), and OBD_FREE_PTR.
Referenced by lustre_idmap_add(), lustre_idmap_del(), and lustre_idmap_fini().
static __u32 idmap_lookup_gid (struct list_head * hash, int reverse, __u32 gid) [static]
Definition at line 291 of file idmap.c.
References CFS_IDMAP_NOTFOUND, head, lustre_idmap_entry::lie_lcl_gid, lustre_idmap_entry::lie_lcl_gid_hash, lustre_idmap_entry::lie_rmt_gid, lustre_idmap_entry::lie_rmt_gid_hash, list_for_each_entry, and lustre_idmap_hashfunc().
Referenced by lustre_idmap_lookup_gid().
static __u32 idmap_lookup_uid (struct list_head * hash, int reverse, __u32 uid) [static]
Definition at line 272 of file idmap.c.
References CFS_IDMAP_NOTFOUND, head, lustre_idmap_entry::lie_lcl_uid, lustre_idmap_entry::lie_lcl_uid_hash, lustre_idmap_entry::lie_rmt_uid, lustre_idmap_entry::lie_rmt_uid_hash, list_for_each_entry, and lustre_idmap_hashfunc().
Referenced by lustre_idmap_lookup_uid().
static struct lustre_idmap_entry* idmap_search_entry (struct lustre_idmap_table * t, uid_t rmt_uid, uid_t lcl_uid, gid_t rmt_gid, gid_t lcl_gid) [static, read]
Definition at line 227 of file idmap.c.
References CERROR, head, LBUG, lustre_idmap_entry::lie_lcl_gid, lustre_idmap_entry::lie_lcl_uid, lustre_idmap_entry::lie_rmt_gid, lustre_idmap_entry::lie_rmt_gid_hash, lustre_idmap_entry::lie_rmt_uid, lustre_idmap_entry::lie_rmt_uid_hash, list_for_each_entry, lustre_idmap_table::lit_idmaps, lustre_idmap_hashfunc(), RMT_GIDMAP_IDX, RMT_UIDMAP_IDX, and unlikely.
Referenced by lustre_idmap_add(), and lustre_idmap_del().
static int lustre_groups_search (struct group_info * group_info, gid_t grp) [static]
Definition at line 67 of file idmap.c.
References CFS_GROUP_AT, and from_kgid().
Referenced by lustre_in_group_p().
static __u32 lustre_idmap_hashfunc (__u32 id) [inline, static]
Definition at line 184 of file idmap.c.
References CFS_IDMAP_HASHSIZE.
Referenced by idmap_lookup_gid(), idmap_lookup_uid(), idmap_search_entry(), and lustre_idmap_add().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.