Lustre: lustre/ptlrpc/import.c File Reference
lustre/ptlrpc/import.c File Reference
#include <linux/kthread.h>
#include <obd_support.h>
#include <lustre_ha.h>
#include <lustre_net.h>
#include <lustre_import.h>
#include <lustre_export.h>
#include <obd.h>
#include <obd_cksum.h>
#include <obd_class.h>
#include "ptlrpc_internal.h"
Data Structures
struct ptlrpc_connect_async_args
Defines
#define DEBUG_SUBSYSTEM S_RPC
#define IMPORT_SET_STATE_NOLOCK(imp, state)
#define IMPORT_SET_STATE(imp, state)
#define UUID_STR "_UUID"
Functions
static void __import_set_state (struct obd_import *imp, enum lustre_imp_state state)
Updates import imp current state to provided state value Helper function.
void ptlrpc_import_enter_resend (struct obd_import *imp)
static int ptlrpc_connect_interpret (const struct lu_env *env, struct ptlrpc_request *request, void *data, int rc)
interpret_reply callback for connect RPCs.
int ptlrpc_import_recovery_state_machine (struct obd_import *imp)
This is the state machine for client-side recovery on import.
int ptlrpc_init_import (struct obd_import *imp)
void deuuidify (char *uuid, const char *prefix, char **uuid_start, int *uuid_len)
int ptlrpc_set_import_discon (struct obd_import *imp, __u32 conn_cnt)
Returns true if import was FULL, false if import was already not connected.
static void ptlrpc_deactivate_and_unlock_import (struct obd_import *imp)
void ptlrpc_deactivate_import (struct obd_import *imp)
static unsigned int ptlrpc_inflight_deadline (struct ptlrpc_request *req, time_t now)
static unsigned int ptlrpc_inflight_timeout (struct obd_import *imp)
void ptlrpc_invalidate_import (struct obd_import *imp)
This function will invalidate the import, if necessary, then block for all the RPC completions, and finally notify the obd to invalidate its state (ie cancel locks, clear pending requests, etc).
void ptlrpc_activate_import (struct obd_import *imp)
void ptlrpc_pinger_force (struct obd_import *imp)
void ptlrpc_fail_import (struct obd_import *imp, __u32 conn_cnt)
int ptlrpc_reconnect_import (struct obd_import *imp)
static int import_select_connection (struct obd_import *imp)
Connection on import imp is changed to another one (if more than one is present).
static int ptlrpc_first_transno (struct obd_import *imp, __u64 *transno)
int ptlrpc_connect_import (struct obd_import *imp)
Attempt to (re)connect import imp.
static void ptlrpc_maybe_ping_import_soon (struct obd_import *imp)
static int ptlrpc_busy_reconnect (int rc)
static int ptlrpc_connect_set_flags (struct obd_import *imp, struct obd_connect_data *ocd, __u64 old_connect_flags, struct obd_export *exp, int init_connect)
static void ptlrpc_prepare_replay (struct obd_import *imp)
Add all replay requests back to unreplied list before start replay, so that we can make sure the known replied XID is always increased only even if when replaying requests.
static int completed_replay_interpret (const struct lu_env *env, struct ptlrpc_request *req, void *data, int rc)
interpret callback for "completed replay" RPCs.
static int signal_completed_replay (struct obd_import *imp)
Let server know that we have no requests to replay anymore.
static int ptlrpc_invalidate_import_thread (void *data)
In kernel code all import invalidation happens in its own separate thread, so that whatever application happened to encounter a problem could still be killed or otherwise continue.
int ptlrpc_disconnect_import (struct obd_import *imp, int noclose)
void ptlrpc_cleanup_imp (struct obd_import *imp)
int at_measured (struct adaptive_timeout *at, unsigned int val)
int import_at_get_index (struct obd_import *imp, int portal)
Variables
unsigned int at_min
unsigned int at_max
unsigned int at_history
Define Documentation
#define DEBUG_SUBSYSTEM S_RPC
Definition at line 41 of file import.c.
#define IMPORT_SET_STATE (imp, state)
Value:
do {                                                                    \
        spin_lock(&imp->imp_lock);                                      \
        IMPORT_SET_STATE_NOLOCK(imp, state);                            \
        spin_unlock(&imp->imp_lock);                                    \
} while(0)
Definition at line 99 of file import.c.
Referenced by ptlrpc_connect_import(), ptlrpc_connect_interpret(), ptlrpc_disconnect_import(), ptlrpc_import_enter_resend(), ptlrpc_import_recovery_state_machine(), and ptlrpc_invalidate_import_thread().
#define IMPORT_SET_STATE_NOLOCK (imp, state)
Value:
do {                                                                           \
        if (imp->imp_state != LUSTRE_IMP_CLOSED) {                             \
               CDEBUG(D_HA, "%p %s: changing import state from %s to %s\n",    \
                      imp, obd2cli_tgt(imp->imp_obd),                          \
                      ptlrpc_import_state_name(imp->imp_state),                \
                      ptlrpc_import_state_name(state));                        \
               __import_set_state(imp, state);                                 \
        }                                                                      \
} while(0)
Definition at line 88 of file import.c.
Referenced by ptlrpc_cleanup_imp(), ptlrpc_connect_import(), ptlrpc_disconnect_import(), and ptlrpc_set_import_discon().
#define UUID_STR "_UUID"
Definition at line 136 of file import.c.
Referenced by deuuidify().
Function Documentation
static void __import_set_state (struct obd_import * imp, enum lustre_imp_state state) [static]
Updates import imp current state to provided state value Helper function.
Must be called under imp_lock.
Definition at line 64 of file import.c.
References cfs_time_current_sec(), obd_import::imp_replay_state, obd_import::imp_state, obd_import::imp_state_hist, obd_import::imp_state_hist_idx, IMP_STATE_HIST_LEN, import_state_hist::ish_state, import_state_hist::ish_time, LUSTRE_IMP_CLOSED, LUSTRE_IMP_CONNECTING, LUSTRE_IMP_DISCON, LUSTRE_IMP_NEW, LUSTRE_IMP_REPLAY, LUSTRE_IMP_REPLAY_LOCKS, and LUSTRE_IMP_REPLAY_WAIT.
static int completed_replay_interpret (const struct lu_env * env, struct ptlrpc_request * req, void * data, int rc) [static]
interpret callback for "completed replay" RPCs.
See also:
signal_completed_replay
Definition at line 1338 of file import.c.
References CDEBUG, D_HA, D_WARNING, ENTRY, obd_import::imp_obd, obd_import::imp_replay_inflight, obd_import::imp_vbr_failed, obd_device::obd_name, ptlrpc_connect_import(), ptlrpc_import_recovery_state_machine(), RETURN, ptlrpc_request::rq_import, and ptlrpc_request::rq_status.
Referenced by signal_completed_replay().
static int import_select_connection (struct obd_import * imp) [static]
Connection on import imp is changed to another one (if more than one is present).
We typically chose connection that we have not tried to connect to the longest
Definition at line 503 of file import.c.
References at_get(), at_measured(), at_reset(), ptlrpc_connection::c_peer, CDEBUG, CERROR, cfs_time_before_64(), cfs_time_beforeq_64(), cfs_time_current_64, class_conn2export(), class_export_put(), CONNECTION_SWITCH_INC, CONNECTION_SWITCH_MAX, D_HA, deuuidify(), ENTRY, obd_export::exp_connection, imp_at::iat_net_latency, obd_import::imp_at, obd_import::imp_conn_current, obd_import::imp_conn_list, obd_import::imp_connection, obd_import::imp_dlm_handle, obd_import::imp_force_reconnect, obd_import::imp_last_success_conn, obd_import::imp_lock, obd_import::imp_obd, LASSERT, libcfs_nid2str(), list_empty(), list_for_each_entry, LPU64, list_head::next, lnet_process_id_t::nid, obd2cli_tgt, obd_device::obd_name, obd_import_conn::oic_conn, obd_import_conn::oic_item, obd_import_conn::oic_last_attempt, obd_import_conn::oic_uuid, ptlrpc_connection_addref(), ptlrpc_connection_put(), RETURN, and obd_uuid::uuid.
Referenced by ptlrpc_connect_import().
static int ptlrpc_busy_reconnect (int rc) [static]
Definition at line 790 of file import.c.
Referenced by ptlrpc_connect_interpret().
static int ptlrpc_connect_interpret (const struct lu_env * env, struct ptlrpc_request * request, void * data, int rc) [static]
interpret_reply callback for connect RPCs.
Looks into returned status of connect operation and decides what to do with the import - i.e enter recovery, promote it to full state for normal operations of disconnect it due to an error.
Definition at line 984 of file import.c.
References __u64, at_reinit(), ptlrpc_connection::c_remote_uuid, CDEBUG, CERROR, class_conn2export(), class_export_put(), lustre_handle::cookie, D_HA, D_WARNING, DEBUG_REQ, ENTRY, obd_export::exp_connect_data, exp_connect_flags(), GOTO, imp_at::iat_net_latency, obd_import::imp_at, obd_import::imp_committed_list, obd_import::imp_conn_current, obd_import::imp_connect_data, obd_import::imp_connect_flags_orig, obd_import::imp_connect_tried, obd_import::imp_connected, obd_import::imp_connection, obd_import::imp_dlm_handle, IMP_EVENT_OCD, obd_import::imp_force_reconnect, obd_import::imp_force_verify, obd_import::imp_invalid, obd_import::imp_last_replay_transno, obd_import::imp_lock, obd_import::imp_obd, obd_import::imp_pingable, obd_import::imp_recovery_waitq, obd_import::imp_remote_handle, obd_import::imp_replay_cursor, obd_import::imp_replay_state, obd_import::imp_replayable, obd_import::imp_resend_replay, obd_import::imp_state, IMPORT_SET_STATE, LASSERT, LCONSOLE_ERROR_MSG, LCONSOLE_WARN, LPD64, LPX64, LUSTRE_IMP_CLOSED, LUSTRE_IMP_DISCON, LUSTRE_IMP_EVICTED, LUSTRE_IMP_FULL, LUSTRE_IMP_RECOVER, LUSTRE_IMP_REPLAY, LUSTRE_IMP_REPLAY_LOCKS, lustre_msg_get_handle(), lustre_msg_get_last_committed(), lustre_msg_get_op_flags(), lustre_msg_get_service_time(), LUSTRE_VERSION_CODE, MSG_CONNECT_RECONNECT, MSG_CONNECT_RECOVERING, MSG_CONNECT_REPLAYABLE, obd2cli_tgt, OBD_CONNECT_FID, OBD_CONNECT_LIGHTWEIGHT, OBD_CONNECT_MDS_MDS, OBD_CONNECT_VERSION, obd_device::obd_name, obd_device::obd_no_recov, OBD_OCD_VERSION_FIX, OBD_OCD_VERSION_MAJOR, OBD_OCD_VERSION_MINOR, OBD_OCD_VERSION_PATCH, obd_device::obd_self_export, obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_instance, obd_connect_data::ocd_version, ptlrpc_connect_async_args::pcaa_initial_connect, ptlrpc_connect_async_args::pcaa_peer_committed, ptlrpc_activate_import(), ptlrpc_at_adj_net_latency(), ptlrpc_busy_reconnect(), ptlrpc_connect_import(), ptlrpc_connect_set_flags(), ptlrpc_deactivate_import(), ptlrpc_import_recovery_state_machine(), ptlrpc_maybe_ping_import_soon(), ptlrpc_prepare_replay(), RCL_SERVER, req_capsule_get_size(), req_capsule_server_get(), req_capsule_server_sized_get(), ret, RETURN, RMF_CONNECT_DATA, ptlrpc_request::rq_import, ptlrpc_request::rq_pill, ptlrpc_request::rq_repmsg, unlikely, and obd_uuid::uuid.
Referenced by ptlrpc_connect_import().
static int ptlrpc_connect_set_flags (struct obd_import * imp, struct obd_connect_data * ocd, __u64 old_connect_flags, struct obd_export * exp, int init_connect) [static]
Definition at line 795 of file import.c.
References ptlrpc_connection::c_remote_uuid, CDEBUG, cksum_type_select(), cksum_types_supported_client(), client_obd::cl_checksum, client_obd::cl_cksum_type, client_obd::cl_max_mod_rpcs_in_flight, client_obd::cl_max_pages_per_rpc, client_obd::cl_supp_cksum_types, obd_device::cli, client_adjust_max_dirty(), D_HA, exp_connect_flags(), obd_import::imp_conn_current, obd_import::imp_conn_list, obd_import::imp_connect_flags_orig, obd_import::imp_connect_op, obd_import::imp_connection, obd_import::imp_last_success_conn, obd_import::imp_lock, obd_import::imp_msghdr_flags, obd_import::imp_obd, LASSERT, LCONSOLE_WARN, list_add(), list_del(), LPX64, LUSTRE_MGC_NAME, LUSTRE_VERSION_CODE, MDS_CONNECT, MGS_CONNECT, MSGHDR_AT_SUPPORT, MSGHDR_CKSUM_INCOMPAT18, ldlm_namespace::ns_connect_flags, ldlm_namespace::ns_orig_connect_flags, obd2cli_tgt, OBD_CKSUM_ADLER, OBD_CONNECT_AT, OBD_CONNECT_BRW_SIZE, OBD_CONNECT_CKSUM, OBD_CONNECT_IBITS, OBD_CONNECT_MNE_SWAB, OBD_CONNECT_MULTIMODRPCS, OBD_CONNECT_VERSION, obd_device::obd_name, obd_device::obd_namespace, OBD_OCD_VERSION_FIX, OBD_OCD_VERSION_MAJOR, OBD_OCD_VERSION_MINOR, OBD_OCD_VERSION_PATCH, obd_device::obd_type, obd_connect_data::ocd_brw_size, obd_connect_data::ocd_cksum_types, obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_maxmodrpcs, obd_connect_data::ocd_version, obd_import_conn::oic_item, obd_import_conn::oic_last_attempt, PTLRPC_MAX_BRW_PAGES, obd_type::typ_name, obd_device::u, unlikely, and obd_uuid::uuid.
Referenced by ptlrpc_connect_interpret().
static void ptlrpc_deactivate_and_unlock_import (struct obd_import * imp) [static]
Definition at line 213 of file import.c.
References CDEBUG, D_HA, ENTRY, EXIT, IMP_EVENT_INACTIVE, obd_import::imp_generation, obd_import::imp_invalid, obd_import::imp_lock, obd_import::imp_obd, obd2cli_tgt, and ptlrpc_abort_inflight().
Referenced by ptlrpc_deactivate_import().
static int ptlrpc_first_transno (struct obd_import * imp, __u64 * transno) [static]
Definition at line 612 of file import.c.
References D_ERROR, DEBUG_REQ, obd_import::imp_committed_list, obd_import::imp_replay_list, LBUG, list_empty(), list_entry, list_head::next, and ptlrpc_request::rq_transno.
Referenced by ptlrpc_connect_import().
static unsigned int ptlrpc_inflight_deadline (struct ptlrpc_request * req, time_t now) [static]
Definition at line 241 of file import.c.
References ptlrpc_request::rq_deadline, ptlrpc_request::rq_phase, RQ_PHASE_BULK, RQ_PHASE_NEW, RQ_PHASE_RPC, ptlrpc_request::rq_sent, ptlrpc_request::rq_timedout, and ptlrpc_request::rq_waiting.
Referenced by ptlrpc_inflight_timeout().
static unsigned int ptlrpc_inflight_timeout (struct obd_import * imp) [static]
Definition at line 264 of file import.c.
References cfs_time_current_sec(), obd_import::imp_lock, obd_import::imp_sending_list, list_entry, list_for_each_safe, max, now(), ptlrpc_inflight_deadline(), ptlrpc_request::rq_list, and timeout.
Referenced by ptlrpc_invalidate_import().
static int ptlrpc_invalidate_import_thread (void * data) [static]
In kernel code all import invalidation happens in its own separate thread, so that whatever application happened to encounter a problem could still be killed or otherwise continue.
Definition at line 1403 of file import.c.
References ptlrpc_connection::c_remote_uuid, CDEBUG, CERROR, class_import_put(), D_HA, ENTRY, obd_import::imp_connection, obd_import::imp_obd, IMPORT_SET_STATE, libcfs_debug_dumplog(), LUSTRE_IMP_RECOVER, obd2cli_tgt, obd_dump_on_eviction, obd_device::obd_name, ptlrpc_import_recovery_state_machine(), ptlrpc_invalidate_import(), RETURN, and obd_uuid::uuid.
Referenced by ptlrpc_import_recovery_state_machine().
static void ptlrpc_maybe_ping_import_soon (struct obd_import * imp) [static]
Definition at line 778 of file import.c.
References obd_import::imp_force_verify, obd_import::imp_lock, and ptlrpc_pinger_wake_up().
Referenced by ptlrpc_connect_interpret().
static void ptlrpc_prepare_replay (struct obd_import * imp) [static]
Add all replay requests back to unreplied list before start replay, so that we can make sure the known replied XID is always increased only even if when replaying requests.
Definition at line 952 of file import.c.
References obd_import::imp_committed_list, obd_import::imp_known_replied_xid, obd_import::imp_lock, obd_import::imp_replay_list, obd_import::imp_resend_replay, obd_import::imp_state, list_empty(), list_for_each_entry, LUSTRE_IMP_REPLAY, ptlrpc_add_unreplied(), ptlrpc_known_replied_xid(), and ptlrpc_request::rq_replay_list.
Referenced by ptlrpc_connect_interpret().
int ptlrpc_set_import_discon (struct obd_import * imp, __u32 conn_cnt)
Returns true if import was FULL, false if import was already not connected.
- import to be disconnected - connection count (epoch) of the request that timed out and caused the disconnection. In some cases, multiple inflight requests can fail to a single target (e.g. OST bulk requests) and if one has already caused a reconnection (increasing the import->conn_cnt) the older failure should not also cause a reconnection. If zero it forces a reconnect.
Definition at line 163 of file import.c.
References ptlrpc_connection::c_peer, CDEBUG, ptlrpc_client::cli_name, D_HA, deuuidify(), obd_import::imp_client, obd_import::imp_conn_cnt, obd_import::imp_connection, IMP_EVENT_DISCON, obd_import::imp_lock, obd_import::imp_obd, obd_import::imp_replayable, obd_import::imp_state, IMPORT_SET_STATE_NOLOCK, LCONSOLE_ERROR_MSG, LCONSOLE_WARN, libcfs_debug_dumplog(), libcfs_nid2str(), LUSTRE_IMP_DISCON, LUSTRE_IMP_FULL, lnet_process_id_t::nid, obd2cli_tgt, obd_dump_on_timeout, obd_device::obd_name, and ptlrpc_import_state_name().
Referenced by ptlrpc_fail_import(), ptlrpc_reconnect_import(), ptlrpc_recover_import(), and ptlrpc_request_handle_notconn().
static int signal_completed_replay (struct obd_import * imp) [static]
Let server know that we have no requests to replay anymore.
Achieved by just sending a PING request
Definition at line 1368 of file import.c.
References AT_OFF, completed_replay_interpret(), ENTRY, obd_import::imp_replay_inflight, LASSERT, LUSTRE_IMP_REPLAY_WAIT, lustre_msg_add_flags(), LUSTRE_OBD_VERSION, MSG_LOCK_REPLAY_DONE, MSG_REQ_REPLAY_DONE, OBD_FAIL_CHECK, OBD_FAIL_PTLRPC_FINISH_REPLAY, OBD_PING, ptlrpc_request_alloc_pack(), ptlrpc_request_set_replen(), ptlrpcd_add_req(), RETURN, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_timeout, RQF_OBD_PING, and unlikely.
Referenced by ptlrpc_import_recovery_state_machine().
Variable Documentation
unsigned int at_history
Definition at line 99 of file class_obd.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.