Lustre: lustre/ldlm/interval_tree.c File Reference
lustre/ldlm/interval_tree.c File Reference
#include <libcfs/libcfs.h>
#include <interval_tree.h>
Defines
#define interval_for_each(node, root)
#define interval_for_each_reverse(node, root)
#define interval_swap(a, b)
Enumerations
enum { INTERVAL_RED = 0, INTERVAL_BLACK = 1 }
Functions
static int node_is_left_child (struct interval_node *node)
static int node_is_right_child (struct interval_node *node)
static int node_is_red (struct interval_node *node)
static int node_is_black (struct interval_node *node)
static int extent_compare (struct interval_node_extent *e1, struct interval_node_extent *e2)
static int extent_equal (struct interval_node_extent *e1, struct interval_node_extent *e2)
static int extent_overlapped (struct interval_node_extent *e1, struct interval_node_extent *e2)
static int node_compare (struct interval_node *n1, struct interval_node *n2)
int node_equal (struct interval_node *n1, struct interval_node *n2)
static __u64 max_u64 (__u64 x, __u64 y)
static __u64 min_u64 (__u64 x, __u64 y)
static struct interval_node * interval_first (struct interval_node *node)
static struct interval_node * interval_last (struct interval_node *node)
static struct interval_node * interval_next (struct interval_node *node)
static struct interval_node * interval_prev (struct interval_node *node)
enum interval_iter interval_iterate (struct interval_node *root, interval_callback_t func, void *data)
enum interval_iter interval_iterate_reverse (struct interval_node *root, interval_callback_t func, void *data)
struct interval_node * interval_find (struct interval_node *root, struct interval_node_extent *ex)
static void __rotate_change_maxhigh (struct interval_node *node, struct interval_node *rotate)
static void __rotate_left (struct interval_node *node, struct interval_node **root)
static void __rotate_right (struct interval_node *node, struct interval_node **root)
static void interval_insert_color (struct interval_node *node, struct interval_node **root)
struct interval_node * interval_insert (struct interval_node *node, struct interval_node **root)
static int node_is_black_or_0 (struct interval_node *node)
static void interval_erase_color (struct interval_node *node, struct interval_node *parent, struct interval_node **root)
static void update_maxhigh (struct interval_node *node, __u64 old_maxhigh)
void interval_erase (struct interval_node *node, struct interval_node **root)
static int interval_may_overlap (struct interval_node *node, struct interval_node_extent *ext)
enum interval_iter interval_search (struct interval_node *node, struct interval_node_extent *ext, interval_callback_t func, void *data)
static enum interval_iter interval_overlap_cb (struct interval_node *n, void *args)
int interval_is_overlapped (struct interval_node *root, struct interval_node_extent *ext)
static __u64 interval_expand_low (struct interval_node *root, __u64 low)
static __u64 interval_expand_high (struct interval_node *node, __u64 high)
void interval_expand (struct interval_node *root, struct interval_node_extent *ext, struct interval_node_extent *limiter)
Define Documentation
#define interval_for_each (node, root)
Value:
for (node = interval_first(root); node != NULL;         \
     node = interval_next(node))
Definition at line 130 of file interval_tree.c.
Referenced by interval_iterate(), and sanity_cb().
#define interval_for_each_reverse (node, root)
Value:
for (node = interval_last(root); node != NULL;          \
     node = interval_prev(node))
Definition at line 134 of file interval_tree.c.
Referenced by interval_iterate_reverse().
#define interval_swap (a, b)
Value:
do {                        \
        struct interval_node *c = a; a = b; b = c;      \
} while (0)
Definition at line 318 of file interval_tree.c.
Referenced by interval_insert_color().
Enumeration Type Documentation
anonymous enum
Enumerator:
INTERVAL_RED
INTERVAL_BLACK
Definition at line 50 of file interval_tree.c.
Function Documentation
static void __rotate_change_maxhigh (struct interval_node * node, struct interval_node * rotate) [static]
Definition at line 248 of file interval_tree.c.
References __u64, interval_node::in_left, interval_node::in_max_high, interval_node::in_right, interval_high(), and max_u64().
Referenced by __rotate_left(), and __rotate_right().
static void __rotate_left (struct interval_node * node, struct interval_node ** root) [static]
Definition at line 263 of file interval_tree.c.
References __rotate_change_maxhigh(), interval_node::in_left, interval_node::in_parent, interval_node::in_right, and node_is_left_child().
Referenced by interval_erase_color(), and interval_insert_color().
static void __rotate_right (struct interval_node * node, struct interval_node ** root) [static]
Definition at line 292 of file interval_tree.c.
References __rotate_change_maxhigh(), interval_node::in_left, interval_node::in_parent, interval_node::in_right, and node_is_right_child().
Referenced by interval_erase_color(), and interval_insert_color().
static int extent_compare (struct interval_node_extent * e1, struct interval_node_extent * e2) [inline, static]
Definition at line 77 of file interval_tree.c.
Referenced by interval_find(), and node_compare().
static int extent_equal (struct interval_node_extent * e1, struct interval_node_extent * e2) [inline, static]
Definition at line 97 of file interval_tree.c.
Referenced by node_equal().
static int extent_overlapped (struct interval_node_extent * e1, struct interval_node_extent * e2) [inline, static]
Definition at line 103 of file interval_tree.c.
Referenced by interval_search(), it_test_performance(), it_test_search(), and it_test_search_hole().
void interval_erase (struct interval_node * node, struct interval_node ** root)
Definition at line 523 of file interval_tree.c.
References ENTRY, EXIT, interval_node::in_color, interval_node::in_intree, interval_node::in_left, interval_node::in_max_high, interval_node::in_parent, interval_node::in_right, INTERVAL_BLACK, interval_erase_color(), interval_is_intree(), interval_next(), LASSERT, node_is_left_child(), and update_maxhigh().
Referenced by it_test_helper(), ldlm_extent_unlink_lock(), mdt_cdt_free_request_tree(), range_delete(), and range_unlock().
static void interval_erase_color (struct interval_node * node, struct interval_node * parent, struct interval_node ** root) [static]
Definition at line 425 of file interval_tree.c.
References __rotate_left(), __rotate_right(), ENTRY, EXIT, interval_node::in_color, interval_node::in_left, interval_node::in_parent, interval_node::in_right, INTERVAL_BLACK, INTERVAL_RED, node_is_black_or_0(), and node_is_red().
Referenced by interval_erase().
void interval_expand (struct interval_node * root, struct interval_node_extent * ext, struct interval_node_extent * limiter)
Definition at line 757 of file interval_tree.c.
References interval_expand_high(), interval_expand_low(), interval_is_overlapped(), and LASSERT.
Referenced by it_test_search_hole().
static __u64 interval_expand_high (struct interval_node * node, __u64 high) [inline, static]
Definition at line 737 of file interval_tree.c.
References __u64, interval_node::in_left, interval_node::in_max_high, interval_node::in_right, and interval_low().
Referenced by interval_expand().
static __u64 interval_expand_low (struct interval_node * root, __u64 low) [inline, static]
Definition at line 729 of file interval_tree.c.
Referenced by interval_expand().
struct interval_node* interval_find (struct interval_node * root, struct interval_node_extent * ex) [read]
Definition at line 227 of file interval_tree.c.
References ENTRY, extent_compare(), interval_node::in_extent, interval_node::in_left, interval_node::in_right, and RETURN.
Referenced by it_test_find(), it_test_helper(), and range_find().
static struct interval_node* interval_first (struct interval_node * node) [static, read]
Definition at line 138 of file interval_tree.c.
References ENTRY, interval_node::in_left, and RETURN.
Referenced by interval_next().
struct interval_node* interval_insert (struct interval_node * node, struct interval_node ** root) [read]
Definition at line 383 of file interval_tree.c.
References ENTRY, interval_node::in_color, interval_node::in_intree, interval_node::in_left, interval_node::in_max_high, interval_node::in_parent, interval_node::in_right, interval_high(), interval_insert_color(), interval_is_intree(), INTERVAL_RED, LASSERT, node_compare(), node_equal(), and RETURN.
Referenced by hsm_update_work(), it_test_helper(), it_test_init(), ldlm_extent_add_lock(), range_insert(), range_lock(), and range_unlock().
static void interval_insert_color (struct interval_node * node, struct interval_node ** root) [static]
Definition at line 329 of file interval_tree.c.
References __rotate_left(), __rotate_right(), ENTRY, EXIT, interval_node::in_color, interval_node::in_left, interval_node::in_parent, interval_node::in_right, INTERVAL_BLACK, INTERVAL_RED, interval_swap, node_is_left_child(), and node_is_red().
Referenced by interval_insert().
int interval_is_overlapped (struct interval_node * root, struct interval_node_extent * ext)
Definition at line 691 of file interval_tree.c.
References interval_overlap_cb(), and interval_search().
Referenced by interval_expand(), it_test_search_hole(), and range_insert().
enum interval_iter interval_iterate (struct interval_node * root, interval_callback_t func, void * data)
Definition at line 189 of file interval_tree.c.
References ENTRY, interval_for_each, INTERVAL_ITER_CONT, INTERVAL_ITER_STOP, and RETURN.
Referenced by it_test_iterate(), it_test_sanity(), and mdt_cdt_get_work_done().
enum interval_iter interval_iterate_reverse (struct interval_node * root, interval_callback_t func, void * data)
Definition at line 207 of file interval_tree.c.
References ENTRY, interval_for_each_reverse, INTERVAL_ITER_CONT, INTERVAL_ITER_STOP, and RETURN.
Referenced by it_test_iterate_reverse(), and ofd_intent_policy().
static struct interval_node* interval_last (struct interval_node * node) [static, read]
Definition at line 149 of file interval_tree.c.
References ENTRY, interval_node::in_right, and RETURN.
Referenced by interval_prev().
static int interval_may_overlap (struct interval_node * node, struct interval_node_extent * ext) [inline, static]
Definition at line 597 of file interval_tree.c.
References interval_node::in_max_high, and interval_low().
Referenced by interval_search().
static struct interval_node* interval_next (struct interval_node * node) [static, read]
Definition at line 160 of file interval_tree.c.
References ENTRY, interval_node::in_parent, interval_node::in_right, interval_first(), node_is_right_child(), and RETURN.
Referenced by interval_erase().
static enum interval_iter interval_overlap_cb (struct interval_node * n, void * args) [static]
Definition at line 684 of file interval_tree.c.
References INTERVAL_ITER_STOP.
Referenced by interval_is_overlapped().
static struct interval_node* interval_prev (struct interval_node * node) [static, read]
Definition at line 173 of file interval_tree.c.
References ENTRY, interval_node::in_left, interval_node::in_parent, interval_last(), node_is_left_child(), and RETURN.
enum interval_iter interval_search (struct interval_node * node, struct interval_node_extent * ext, interval_callback_t func, void * data)
Definition at line 625 of file interval_tree.c.
References ENTRY, extent_overlapped(), interval_node::in_extent, interval_node::in_left, interval_node::in_parent, interval_node::in_right, INTERVAL_ITER_CONT, INTERVAL_ITER_STOP, interval_low(), interval_may_overlap(), LASSERT, node_is_left_child(), and RETURN.
Referenced by interval_is_overlapped(), it_test_performance(), it_test_search(), range_lock(), range_search(), range_unlock(), and search_itree().
static __u64 max_u64 (__u64 x, __u64 y) [inline, static]
Definition at line 120 of file interval_tree.c.
Referenced by __rotate_change_maxhigh(), it_test_search_hole(), and update_maxhigh().
static __u64 min_u64 (__u64 x, __u64 y) [inline, static]
Definition at line 125 of file interval_tree.c.
Referenced by it_test_search_hole().
static int node_compare (struct interval_node * n1, struct interval_node * n2) [inline, static]
Definition at line 109 of file interval_tree.c.
References extent_compare(), and interval_node::in_extent.
Referenced by interval_insert(), and sanity_cb().
int node_equal (struct interval_node * n1, struct interval_node * n2)
Definition at line 115 of file interval_tree.c.
References extent_equal(), and interval_node::in_extent.
Referenced by interval_insert().
static int node_is_black (struct interval_node * node) [inline, static]
Definition at line 72 of file interval_tree.c.
References interval_node::in_color, and INTERVAL_BLACK.
Referenced by node_is_black_or_0(), and sanity_cb().
static int node_is_black_or_0 (struct interval_node * node) [inline, static]
Definition at line 420 of file interval_tree.c.
References node_is_black().
Referenced by interval_erase_color().
static int node_is_left_child (struct interval_node * node) [inline, static]
Definition at line 55 of file interval_tree.c.
References interval_node::in_left, interval_node::in_parent, and LASSERT.
Referenced by __rotate_left(), interval_erase(), interval_insert_color(), interval_prev(), and interval_search().
static int node_is_red (struct interval_node * node) [inline, static]
Definition at line 67 of file interval_tree.c.
References interval_node::in_color, and INTERVAL_RED.
Referenced by interval_erase_color(), interval_insert_color(), and sanity_cb().
static int node_is_right_child (struct interval_node * node) [inline, static]
Definition at line 61 of file interval_tree.c.
References interval_node::in_parent, interval_node::in_right, and LASSERT.
Referenced by __rotate_right(), and interval_next().
static void update_maxhigh (struct interval_node * node, __u64 old_maxhigh) [static]
Definition at line 504 of file interval_tree.c.
References __u64, ENTRY, EXIT, interval_node::in_left, interval_node::in_max_high, interval_node::in_parent, interval_node::in_right, interval_high(), and max_u64().
Referenced by interval_erase().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.