Lustre: lustre/include/interval_tree.h File Reference
lustre/include/interval_tree.h File Reference
#include <libcfs/libcfs.h>
Data Structures
struct interval_node
struct interval_node::interval_node_extent
Enumerations
enum interval_iter { INTERVAL_ITER_CONT = 1, INTERVAL_ITER_STOP = 2 }
Functions
static int interval_is_intree (struct interval_node *node)
static __u64 interval_low (struct interval_node *node)
static __u64 interval_high (struct interval_node *node)
static void interval_set (struct interval_node *node, __u64 start, __u64 end)
static void interval_init (struct interval_node *node)
int node_equal (struct interval_node *n1, struct interval_node *n2)
struct interval_node * interval_insert (struct interval_node *node, struct interval_node **root)
void interval_erase (struct interval_node *node, struct interval_node **root)
enum interval_iter interval_search (struct interval_node *root, struct interval_node_extent *ex, interval_callback_t func, void *data)
enum interval_iter interval_iterate (struct interval_node *root, interval_callback_t func, void *data)
enum interval_iter interval_iterate_reverse (struct interval_node *root, interval_callback_t func, void *data)
void interval_expand (struct interval_node *root, struct interval_node_extent *ext, struct interval_node_extent *limiter)
int interval_is_overlapped (struct interval_node *root, struct interval_node_extent *ex)
struct interval_node * interval_find (struct interval_node *root, struct interval_node_extent *ex)
Variables
enum interval_iter(* interval_callback_t)(struct interval_node *node, void *args)
Enumeration Type Documentation
enum interval_iter
Enumerator:
INTERVAL_ITER_CONT
INTERVAL_ITER_STOP
Definition at line 60 of file interval_tree.h.
Function Documentation
void interval_erase (struct interval_node * node, struct interval_node ** root)
Definition at line 523 of file interval_tree.c.
References ENTRY, EXIT, interval_node::in_color, interval_node::in_intree, interval_node::in_left, interval_node::in_max_high, interval_node::in_parent, interval_node::in_right, INTERVAL_BLACK, interval_erase_color(), interval_is_intree(), interval_next(), LASSERT, node_is_left_child(), and update_maxhigh().
Referenced by it_test_helper(), ldlm_extent_unlink_lock(), mdt_cdt_free_request_tree(), range_delete(), and range_unlock().
void interval_expand (struct interval_node * root, struct interval_node_extent * ext, struct interval_node_extent * limiter)
Definition at line 757 of file interval_tree.c.
References interval_expand_high(), interval_expand_low(), interval_is_overlapped(), and LASSERT.
Referenced by it_test_search_hole().
struct interval_node* interval_find (struct interval_node * root, struct interval_node_extent * ex) [read]
Definition at line 227 of file interval_tree.c.
References ENTRY, extent_compare(), interval_node::in_extent, interval_node::in_left, interval_node::in_right, and RETURN.
Referenced by it_test_find(), it_test_helper(), and range_find().
static __u64 interval_high (struct interval_node * node) [inline, static]
Definition at line 75 of file interval_tree.h.
References interval_node::interval_node_extent::end, and interval_node::in_extent.
Referenced by __rotate_change_maxhigh(), interval_insert(), ofd_intent_cb(), and update_maxhigh().
static void interval_init (struct interval_node * node) [inline, static]
Definition at line 89 of file interval_tree.h.
Referenced by range_lock_init().
struct interval_node* interval_insert (struct interval_node * node, struct interval_node ** root) [read]
Definition at line 383 of file interval_tree.c.
References ENTRY, interval_node::in_color, interval_node::in_intree, interval_node::in_left, interval_node::in_max_high, interval_node::in_parent, interval_node::in_right, interval_high(), interval_insert_color(), interval_is_intree(), INTERVAL_RED, LASSERT, node_compare(), node_equal(), and RETURN.
Referenced by hsm_update_work(), it_test_helper(), it_test_init(), ldlm_extent_add_lock(), range_insert(), range_lock(), and range_unlock().
static int interval_is_intree (struct interval_node * node) [inline, static]
Definition at line 65 of file interval_tree.h.
References interval_node::in_intree.
Referenced by interval_erase(), interval_insert(), ldlm_extent_add_lock(), ldlm_extent_unlink_lock(), ldlm_interval_free(), range_delete(), range_destroy(), and range_unlock().
int interval_is_overlapped (struct interval_node * root, struct interval_node_extent * ex)
Definition at line 691 of file interval_tree.c.
References interval_overlap_cb(), and interval_search().
Referenced by interval_expand(), it_test_search_hole(), and range_insert().
enum interval_iter interval_iterate (struct interval_node * root, interval_callback_t func, void * data)
Definition at line 189 of file interval_tree.c.
References ENTRY, interval_for_each, INTERVAL_ITER_CONT, INTERVAL_ITER_STOP, and RETURN.
Referenced by it_test_iterate(), it_test_sanity(), and mdt_cdt_get_work_done().
enum interval_iter interval_iterate_reverse (struct interval_node * root, interval_callback_t func, void * data)
Definition at line 207 of file interval_tree.c.
References ENTRY, interval_for_each_reverse, INTERVAL_ITER_CONT, INTERVAL_ITER_STOP, and RETURN.
Referenced by it_test_iterate_reverse(), and ofd_intent_policy().
static __u64 interval_low (struct interval_node * node) [inline, static]
Definition at line 70 of file interval_tree.h.
References interval_node::in_extent, and interval_node::interval_node_extent::start.
Referenced by interval_expand_high(), interval_may_overlap(), and interval_search().
enum interval_iter interval_search (struct interval_node * root, struct interval_node_extent * ex, interval_callback_t func, void * data)
Definition at line 625 of file interval_tree.c.
References ENTRY, extent_overlapped(), interval_node::in_extent, interval_node::in_left, interval_node::in_parent, interval_node::in_right, INTERVAL_ITER_CONT, INTERVAL_ITER_STOP, interval_low(), interval_may_overlap(), LASSERT, node_is_left_child(), and RETURN.
Referenced by interval_is_overlapped(), it_test_performance(), it_test_search(), range_lock(), range_search(), range_unlock(), and search_itree().
static void interval_set (struct interval_node * node, __u64 start, __u64 end) [inline, static]
Definition at line 80 of file interval_tree.h.
References interval_node::interval_node_extent::end, interval_node::in_extent, interval_node::in_max_high, LASSERT, and interval_node::interval_node_extent::start.
Referenced by hsm_update_work(), it_test_helper(), it_test_init(), ldlm_extent_add_lock(), range_create(), and range_lock_init().
int node_equal (struct interval_node * n1, struct interval_node * n2)
Definition at line 115 of file interval_tree.c.
References extent_equal(), and interval_node::in_extent.
Referenced by interval_insert().
Variable Documentation
enum interval_iter(* interval_callback_t)(struct interval_node *node, void *args)
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.