Lustre: libcfs/include/libcfs/util/ioctl.h File Reference
libcfs/include/libcfs/util/ioctl.h File Reference
#include <stdbool.h>
#include <linux/types.h>
#include <libcfs/libcfs_ioctl.h>
Defines
#define __user
#define LIBCFS_IOC_INIT(data)
#define LIBCFS_IOC_INIT_V2(data, hdr)
Functions
int libcfs_ioctl_pack (struct libcfs_ioctl_data *data, char **pbuf, int max)
void libcfs_ioctl_unpack (struct libcfs_ioctl_data *data, char *pbuf)
int register_ioc_dev (int dev_id, const char *dev_name, int major, int minor)
void unregister_ioc_dev (int dev_id)
int l_ioctl (int dev_id, unsigned int opc, void *buf)
Define Documentation
#define __user
Definition at line 48 of file ioctl.h.
Referenced by cfs_tracefile_dump_all_pages(), class_handle_ioctl(), filp_user_write(), libcfs_psdev_ioctl(), ll_dir_ioctl(), ll_file_ioctl(), ll_file_write(), ll_get_obd_name(), ll_iocontrol(), ll_lov_setea(), lloop_ioctl(), LNetCtl(), lo_ioctl(), lstcon_statrpc_readent(), and tracefiled().
#define LIBCFS_IOC_INIT (data)
Value:
do {                                                            \
        memset(&(data), 0, sizeof(data));                       \
        (data).ioc_hdr.ioc_version = LIBCFS_IOCTL_VERSION;      \
        (data).ioc_hdr.ioc_len = sizeof(data);                  \
} while (0)
Definition at line 52 of file ioctl.h.
Referenced by fault_simul_rule_reset(), jt_ptl_add_interface(), jt_ptl_add_peer(), jt_ptl_del_interface(), jt_ptl_del_peer(), jt_ptl_disconnect(), jt_ptl_fail_nid(), jt_ptl_list_nids(), jt_ptl_mynid(), jt_ptl_network(), jt_ptl_notify_router(), jt_ptl_ping(), jt_ptl_print_connections(), jt_ptl_print_interfaces(), jt_ptl_print_peers(), jt_ptl_push_connection(), jt_ptl_testprotocompat(), jt_ptl_which_nid(), lst_ioctl(), and lustre_lnet_config_ni_system().
#define LIBCFS_IOC_INIT_V2 (data, hdr)
Value:
do {                                                    \
        memset(&(data), 0, sizeof(data));               \
        (data).hdr.ioc_version = LIBCFS_IOCTL_VERSION2; \
        (data).hdr.ioc_len = sizeof(data);              \
} while (0)
Definition at line 59 of file ioctl.h.
Referenced by jt_ptl_add_route(), jt_ptl_del_route(), jt_ptl_print_routes(), lustre_lnet_config_buffers(), lustre_lnet_config_net(), lustre_lnet_config_route(), lustre_lnet_del_net(), lustre_lnet_del_route(), lustre_lnet_enable_routing(), lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), lustre_lnet_show_route(), lustre_lnet_show_routing(), and lustre_lnet_show_stats().
Function Documentation
int l_ioctl (int dev_id, unsigned int opc, void * buf)
Definition at line 102 of file l_ioctl.c.
References open_ioc_dev().
Referenced by fault_simul_rule_add(), fault_simul_rule_del(), fault_simul_rule_list(), fault_simul_rule_reset(), jt_dbg_clear_debug_buf(), jt_dbg_mark_debug_buf(), jt_lfsck_query(), jt_lfsck_start(), jt_lfsck_stop(), jt_llog_cancel(), jt_llog_catlist(), jt_llog_check(), jt_llog_info(), jt_llog_print(), jt_llog_remove(), jt_ptl_add_interface(), jt_ptl_add_peer(), jt_ptl_add_route(), jt_ptl_del_interface(), jt_ptl_del_peer(), jt_ptl_del_route(), jt_ptl_disconnect(), jt_ptl_fail_nid(), jt_ptl_list_nids(), jt_ptl_mynid(), jt_ptl_network(), jt_ptl_notify_router(), jt_ptl_ping(), jt_ptl_print_connections(), jt_ptl_print_interfaces(), jt_ptl_print_peers(), jt_ptl_print_routes(), jt_ptl_push_connection(), jt_ptl_testprotocompat(), jt_ptl_which_nid(), l2_ioctl(), lcfg_ioctl(), lcfg_mgs_ioctl(), lst_ioctl(), lustre_lnet_config_buffers(), lustre_lnet_config_net(), lustre_lnet_config_ni_system(), lustre_lnet_config_route(), lustre_lnet_del_net(), lustre_lnet_del_route(), lustre_lnet_enable_routing(), lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), lustre_lnet_show_route(), lustre_lnet_show_routing(), lustre_lnet_show_stats(), nodemap_cmd(), and pool_cmd().
int libcfs_ioctl_pack (struct libcfs_ioctl_data * data, char ** pbuf, int max)
Definition at line 158 of file l_ioctl.c.
References libcfs_ioctl_data::ioc_bulk, libcfs_ioctl_data::ioc_hdr, libcfs_ioctl_data::ioc_inlbuf1, libcfs_ioctl_data::ioc_inlbuf2, libcfs_ioctl_data::ioc_inllen1, libcfs_ioctl_data::ioc_inllen2, libcfs_ioctl_hdr::ioc_len, libcfs_ioctl_hdr::ioc_version, libcfs_ioctl_packlen(), and LIBCFS_IOCTL_VERSION.
Referenced by fault_simul_rule_add(), fault_simul_rule_del(), fault_simul_rule_list(), jt_dbg_clear_debug_buf(), and jt_dbg_mark_debug_buf().
void libcfs_ioctl_unpack (struct libcfs_ioctl_data * data, char * pbuf)
Definition at line 191 of file l_ioctl.c.
References libcfs_ioctl_data::ioc_bulk, libcfs_ioctl_data::ioc_inlbuf1, libcfs_ioctl_data::ioc_inlbuf2, libcfs_ioctl_data::ioc_inllen1, and libcfs_ioctl_data::ioc_inllen2.
Referenced by fault_simul_rule_del(), and fault_simul_rule_list().
int register_ioc_dev (int dev_id, const char * dev_name, int major, int minor)
Definition at line 117 of file l_ioctl.c.
References ioc_dev::dev_fd, ioc_dev::dev_major, ioc_dev::dev_minor, ioc_dev::dev_name, ioc_dev_list, and unregister_ioc_dev().
Referenced by lustre_lnet_config_lib_init(), obd_initialize(), and ptl_initialize().
void unregister_ioc_dev (int dev_id)
Definition at line 135 of file l_ioctl.c.
References ioc_dev::dev_fd, ioc_dev::dev_name, and ioc_dev_list.
Referenced by register_ioc_dev().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.