Lustre: lustre/tests/it_test.c File Reference
lustre/tests/it_test.c File Reference
#include <inttypes.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <sys/time.h>
#include <linux/types.h>
#include <../ldlm/interval_tree.c>
Data Structures
struct it_node
Defines
#define dprintf(fmt, args...)
#define error(fmt, args...)
#define ALIGN_SIZE 4096
#define ALIGN_MASK (~(ALIGN_SIZE - 1))
#define LOOP_COUNT 1000
Functions
static void it_test_clear (void)
static enum interval_iter cb (struct interval_node *n, void *args)
static int it_test_search (struct interval_node *root)
static int it_test_iterate (struct interval_node *root)
static int it_test_iterate_reverse (struct interval_node *root)
static int it_test_find (struct interval_node *root)
static enum interval_iter sanity_cb (struct interval_node *node, void *args)
static int it_test_sanity (struct interval_node *root)
static int it_test_search_hole (struct interval_node *root)
static enum interval_iter perf_cb (struct interval_node *n, void *args)
static long tv_delta (struct timeval *s, struct timeval *e)
static int it_test_performance (struct interval_node *root, unsigned long len)
static struct interval_node * it_test_helper (struct interval_node *root)
static struct interval_node * it_test_init (int count)
static void it_test_fini (void)
int main (int argc, char *argv[])
Variables
static struct it_node * it_array
static int it_count
static struct list_head header = LIST_HEAD_INIT(header)
static unsigned long max_count = ULONG_MAX & ALIGN_MASK
static int have_wide_lock = 0
static int contended_count = 0
Define Documentation
#define ALIGN_MASK (~(ALIGN_SIZE - 1))
Definition at line 62 of file it_test.c.
Referenced by it_test_helper(), it_test_init(), it_test_performance(), and it_test_search().
#define ALIGN_SIZE 4096
Definition at line 61 of file it_test.c.
Referenced by it_test_init().
#define dprintf (fmt, args...)
Definition at line 54 of file it_test.c.
Referenced by cb(), it_test_find(), it_test_helper(), it_test_iterate(), it_test_iterate_reverse(), it_test_performance(), it_test_search(), it_test_search_hole(), sanity_cb(), and tv_delta().
#define error (fmt, args...)
Value:
do {                        \
        fflush(stdout), fflush(stderr);                 \
        fprintf(stderr, "\nError:" fmt, ##args);        \
        abort();                                        \
} while(0)
Definition at line 55 of file it_test.c.
Referenced by cb(), gss_svc_handle_data(), it_test_find(), it_test_helper(), it_test_init(), it_test_iterate(), it_test_iterate_reverse(), it_test_performance(), it_test_search(), it_test_search_hole(), jt_lst_query_batch(), kgnilnd_setup_phys_buffer(), kiblnd_peer_notify(), ksocknal_find_timed_out_conn(), ldlm_errno2error(), lfs_migrate(), lnet_selftest_init(), load_backfs_module(), loop_set_fd(), lstcon_group_nodes_remove(), lstcon_rpc_trans_interpreter(), lstcon_rpc_trans_stat(), main(), mdd_links_rename(), ofd_grant_sanity_check(), sanity_cb(), sfw_add_test_instance(), sfw_startup(), t1(), and vvp_pgcache_page_show().
#define LOOP_COUNT 1000
Definition at line 358 of file it_test.c.
Referenced by it_test_performance(), and perf_cb().
Function Documentation
static enum interval_iter cb (struct interval_node * n, void * args) [static]
Definition at line 81 of file it_test.c.
References dprintf, interval_node::interval_node_extent::end, error, it_node::hit, interval_node::in_extent, INTERVAL_ITER_CONT, INTERVAL_ITER_STOP, it_node::node, interval_node::interval_node_extent::start, and it_node::valid.
Referenced by cYAML_tree_recursive_walk(), dt_txn_hook_commit(), dt_txn_hook_start(), dt_txn_hook_stop(), it_test_iterate(), it_test_iterate_reverse(), it_test_search(), llapi_target_iterate(), llog_reverse_process(), lustre_yaml_cb_helper(), ptlrpcd_alloc_work(), and qmt_glimpse_lock().
static void it_test_clear (void) [static]
Definition at line 74 of file it_test.c.
References it_array, and it_count.
Referenced by it_test_iterate(), it_test_iterate_reverse(), it_test_sanity(), and it_test_search().
static int it_test_find (struct interval_node * root) [static]
Definition at line 202 of file it_test.c.
References dprintf, error, interval_node::in_extent, interval_find(), it_array, it_count, and it_node::node.
Referenced by main().
static void it_test_fini (void) [static]
Definition at line 503 of file it_test.c.
References it_array, it_count, and max_count.
Referenced by main().
static struct interval_node* it_test_helper (struct interval_node * root) [static, read]
Definition at line 427 of file it_test.c.
References __u64, ALIGN_MASK, dprintf, interval_node::interval_node_extent::end, error, interval_node::in_extent, interval_erase(), interval_find(), interval_insert(), interval_set(), it_array, it_count, it_node::list, list_add(), list_del_init(), max_count, it_node::node, interval_node::interval_node_extent::start, and it_node::valid.
Referenced by main().
static struct interval_node* it_test_init (int count) [static, read]
Definition at line 465 of file it_test.c.
References ALIGN_MASK, ALIGN_SIZE, error, have_wide_lock, it_node::hit, interval_insert(), interval_set(), it_array, it_count, list, it_node::list, list_add_tail(), max_count, it_node::node, and it_node::valid.
Referenced by main().
static int it_test_iterate (struct interval_node * root) [static]
Definition at line 161 of file it_test.c.
References cb(), dprintf, interval_node::interval_node_extent::end, error, interval_node::in_extent, interval_iterate(), it_array, it_count, it_test_clear(), and it_node::node.
Referenced by main().
static int it_test_iterate_reverse (struct interval_node * root) [static]
Definition at line 183 of file it_test.c.
References cb(), dprintf, error, interval_iterate_reverse(), it_array, it_count, and it_test_clear().
Referenced by main().
static int it_test_performance (struct interval_node * root, unsigned long len) [static]
Definition at line 377 of file it_test.c.
References ALIGN_MASK, contended_count, dprintf, error, extent_overlapped(), have_wide_lock, interval_node::in_extent, interval_search(), list, list_for_each_entry, LOOP_COUNT, max_count, it_node::node, perf_cb(), and tv_delta().
Referenced by main().
static int it_test_sanity (struct interval_node * root) [static]
Definition at line 299 of file it_test.c.
References interval_iterate(), it_test_clear(), and sanity_cb().
Referenced by main().
static int it_test_search (struct interval_node * root) [static]
Definition at line 112 of file it_test.c.
References ALIGN_MASK, cb(), dprintf, interval_node::interval_node_extent::end, error, extent_overlapped(), it_node::hit, interval_node::in_extent, interval_search(), it_array, it_count, it_test_clear(), max_count, it_node::node, interval_node::interval_node_extent::start, and it_node::valid.
Referenced by main().
static int it_test_search_hole (struct interval_node * root) [static]
Definition at line 306 of file it_test.c.
References __u64, dprintf, interval_node::interval_node_extent::end, error, extent_overlapped(), interval_node::in_extent, interval_expand(), interval_is_overlapped(), it_array, it_count, max_count, max_u64(), min_u64(), it_node::node, interval_node::interval_node_extent::start, and it_node::valid.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 511 of file it_test.c.
References error, it_test_find(), it_test_fini(), it_test_helper(), it_test_init(), it_test_iterate(), it_test_iterate_reverse(), it_test_performance(), it_test_sanity(), it_test_search(), it_test_search_hole(), and max_count.
static enum interval_iter perf_cb (struct interval_node * n, void * args) [static]
Definition at line 359 of file it_test.c.
References contended_count, INTERVAL_ITER_CONT, and LOOP_COUNT.
Referenced by it_test_performance().
static enum interval_iter sanity_cb (struct interval_node * node, void * args) [static]
Definition at line 225 of file it_test.c.
References __u64, dprintf, interval_node::interval_node_extent::end, error, interval_node::in_extent, interval_node::in_left, interval_node::in_max_high, interval_node::in_parent, interval_node::in_right, interval_for_each, node_compare(), node_is_black(), node_is_red(), and interval_node::interval_node_extent::start.
Referenced by it_test_sanity().
static long tv_delta (struct timeval * s, struct timeval * e) [inline, static]
Definition at line 367 of file it_test.c.
References dprintf.
Referenced by it_test_performance().
Variable Documentation
int contended_count = 0 [static]
Definition at line 357 of file it_test.c.
Referenced by it_test_performance(), and perf_cb().
int have_wide_lock = 0 [static]
Definition at line 72 of file it_test.c.
Referenced by it_test_init(), and it_test_performance().
struct list_head header = LIST_HEAD_INIT(header) [static]
Definition at line 70 of file it_test.c.
Referenced by cl_object_put_last(), cl_object_refc(), and nodemap_map_acl().
struct it_node * it_array [static]
Referenced by it_test_clear(), it_test_find(), it_test_fini(), it_test_helper(), it_test_init(), it_test_iterate(), it_test_iterate_reverse(), it_test_search(), and it_test_search_hole().
int it_count [static]
Definition at line 69 of file it_test.c.
Referenced by it_test_clear(), it_test_find(), it_test_fini(), it_test_helper(), it_test_init(), it_test_iterate(), it_test_iterate_reverse(), it_test_search(), and it_test_search_hole().
unsigned long max_count = ULONG_MAX & ALIGN_MASK [static]
Definition at line 71 of file it_test.c.
Referenced by echo_client_iocontrol(), it_test_fini(), it_test_helper(), it_test_init(), it_test_performance(), it_test_search(), it_test_search_hole(), jt_obd_alloc_fids(), and main().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.