Lustre: lustre/obdclass/kernelcomm.c File Reference
lustre/obdclass/kernelcomm.c File Reference
#include <obd_support.h>
#include <lustre_kernelcomm.h>
Data Structures
struct kkuc_reg
A single group registration has a uid and a file pointer.
Defines
#define DEBUG_SUBSYSTEM S_CLASS
#define D_KUC D_OTHER
Functions
static ssize_t filp_user_write (struct file *filp, const void *buf, size_t count, loff_t *offset)
int libcfs_kkuc_msg_put (struct file *filp, void *payload)
libcfs_kkuc_msg_put - send an message from kernel to userspace
static DECLARE_RWSEM (kg_sem)
int libcfs_kkuc_group_add (struct file *filp, int uid, int group, void *data, size_t data_len)
Add a receiver to a broadcast group.
int libcfs_kkuc_group_rem (int uid, int group)
int libcfs_kkuc_group_put (int group, void *payload)
int libcfs_kkuc_group_foreach (int group, libcfs_kkuc_cb_t cb_func, void *cb_arg)
Calls a callback function for each link of the given kuc group.
Variables
static struct list_head kkuc_groups [KUC_GRP_MAX+1] = {}
Define Documentation
#define D_KUC D_OTHER
Definition at line 38 of file kernelcomm.c.
Referenced by libcfs_kkuc_group_add(), libcfs_kkuc_group_rem(), and libcfs_kkuc_msg_put().
#define DEBUG_SUBSYSTEM S_CLASS
Definition at line 37 of file kernelcomm.c.
Function Documentation
static DECLARE_RWSEM (kg_sem) [static]
static ssize_t filp_user_write (struct file * filp, const void * buf, size_t count, loff_t * offset) [static]
Definition at line 46 of file kernelcomm.c.
References __user, and size.
Referenced by libcfs_kkuc_msg_put().
int libcfs_kkuc_group_add (struct file * filp, int uid, int group, void * data, size_t data_len)
Add a receiver to a broadcast group.
Parameters:
filp pipe to write into
uid identifier for this receiver
group group number
data user data
Definition at line 118 of file kernelcomm.c.
References CDEBUG, D_KUC, D_WARNING, INIT_LIST_HEAD, kkuc_reg::kr_chain, kkuc_reg::kr_data, kkuc_reg::kr_fp, kkuc_reg::kr_uid, KUC_GRP_MAX, and list_add().
Referenced by lmv_hsm_ct_register().
int libcfs_kkuc_group_foreach (int group, libcfs_kkuc_cb_t cb_func, void * cb_arg)
Calls a callback function for each link of the given kuc group.
Parameters:
group the group to call the function on.
cb_func the function to be called.
cb_arg extra argument to be passed to the callback function.
Definition at line 225 of file kernelcomm.c.
References CDEBUG, D_WARNING, ENTRY, kkuc_reg::kr_chain, kkuc_reg::kr_data, kkuc_reg::kr_fp, KUC_GRP_MAX, list_for_each_entry, and RETURN.
Referenced by mdc_kuc_reregister().
int libcfs_kkuc_group_put (int group, void * payload)
Definition at line 189 of file kernelcomm.c.
References ENTRY, kkuc_reg::kr_chain, kkuc_reg::kr_fp, libcfs_kkuc_msg_put(), list_for_each_entry, and RETURN.
Referenced by libcfs_kkuc_group_rem(), and mdc_hsm_copytool_send().
int libcfs_kkuc_group_rem (int uid, int group)
Definition at line 153 of file kernelcomm.c.
References CDEBUG, D_KUC, ENTRY, kkuc_reg::kr_chain, kkuc_reg::kr_fp, kkuc_reg::kr_uid, KUC_MAGIC, kuc_hdr::kuc_magic, KUC_MSG_SHUTDOWN, kuc_hdr::kuc_msglen, kuc_hdr::kuc_msgtype, kuc_hdr::kuc_transport, KUC_TRANSPORT_GENERIC, libcfs_kkuc_group_put(), list_del(), list_for_each_entry_safe, and RETURN.
Referenced by lmv_hsm_ct_unregister(), and mdc_precleanup().
int libcfs_kkuc_msg_put (struct file * filp, void * payload)
libcfs_kkuc_msg_put - send an message from kernel to userspace
Parameters:
fp to send the message to
payload Payload data. First field of payload is always struct kuc_hdr
Definition at line 73 of file kernelcomm.c.
References CDEBUG, CERROR, CWARN, D_KUC, filp_user_write(), KUC_MAGIC, kuc_hdr::kuc_magic, and kuc_hdr::kuc_msglen.
Referenced by changelog_kkuc_cb(), libcfs_kkuc_group_put(), and mdc_changelog_send_thread().
Variable Documentation
struct list_head kkuc_groups[KUC_GRP_MAX+1] = {} [static]
Definition at line 108 of file kernelcomm.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.