Lustre: lnet/klnds/socklnd/socklnd.h File Reference
lnet/klnds/socklnd/socklnd.h File Reference
#include <linux/crc32.h>
#include <linux/errno.h>
#include <linux/if.h>
#include <linux/init.h>
#include <linux/kernel.h>
#include <linux/kthread.h>
#include <linux/kmod.h>
#include <linux/list.h>
#include <linux/mm.h>
#include <linux/module.h>
#include <linux/stat.h>
#include <linux/string.h>
#include <linux/syscalls.h>
#include <linux/sysctl.h>
#include <linux/uio.h>
#include <linux/unistd.h>
#include <net/sock.h>
#include <net/tcp.h>
#include <libcfs/libcfs.h>
#include <lnet/lnet.h>
#include <lnet/lib-lnet.h>
#include <lnet/socklnd.h>
Data Structures
struct ksock_sched_t
struct ksock_sched_info
struct ksock_interface_t
struct ksock_tunables_t
struct ksock_net_t
struct ksock_nal_data_t
struct ksock_tx_t
union ksock_rxiovspace_t
struct ksock_conn
struct ksock_route
struct ksock_peer
struct ksock_connreq
struct ksock_proto
Defines
#define DEBUG_PORTAL_ALLOC
#define DEBUG_SUBSYSTEM S_LND
#define cfs_tcp_sendpage(sk, page, offset, size, flags) tcp_sendpage(sk, page, offset, size, flags)
#define SOCKNAL_NSCHEDS 3
#define SOCKNAL_NSCHEDS_HIGH (SOCKNAL_NSCHEDS << 1)
#define SOCKNAL_PEER_HASH_SIZE 101
#define SOCKNAL_RESCHED 100
#define SOCKNAL_INSANITY_RECONN 5000
#define SOCKNAL_ENOMEM_RETRY CFS_TICK
#define SOCKNAL_SINGLE_FRAG_TX 0
#define SOCKNAL_SINGLE_FRAG_RX 0
#define SOCKNAL_VERSION_DEBUG 0
#define SOCKNAL_RISK_KMAP_DEADLOCK 1
#define KSOCK_CPT_SHIFT 16
#define KSOCK_THREAD_ID(cpt, sid) (((cpt) << KSOCK_CPT_SHIFT) | (sid))
#define KSOCK_THREAD_CPT(id) ((id) >> KSOCK_CPT_SHIFT)
#define KSOCK_THREAD_SID(id) ((id) & ((1UL << KSOCK_CPT_SHIFT) - 1))
#define SOCKNAL_CONND_TIMEOUT 120
connd timeout
#define SOCKNAL_CONND_RESV 1
reserved thread for accepting & creating new connd
#define SOCKNAL_INIT_NOTHING 0
#define SOCKNAL_INIT_DATA 1
#define SOCKNAL_INIT_ALL 2
#define KSOCK_NOOP_TX_SIZE ((int)offsetof(ksock_tx_t, tx_frags.paged.kiov[0]))
#define SOCKNAL_RX_KSM_HEADER 1
#define SOCKNAL_RX_LNET_HEADER 2
#define SOCKNAL_RX_PARSE 3
#define SOCKNAL_RX_PARSE_WAIT 4
#define SOCKNAL_RX_LNET_PAYLOAD 5
#define SOCKNAL_RX_SLOP 6
#define SOCKNAL_KEEPALIVE_PING 1
#define SOCKNAL_MATCH_NO 0
#define SOCKNAL_MATCH_YES 1
#define SOCKNAL_MATCH_MAY 2
#define KSOCK_PROTO_V1_MAJOR LNET_PROTO_TCP_VERSION_MAJOR
#define KSOCK_PROTO_V1_MINOR LNET_PROTO_TCP_VERSION_MINOR
#define KSOCK_PROTO_V1 KSOCK_PROTO_V1_MAJOR
#define CPU_MASK_NONE 0UL
Typedefs
typedef struct ksock_conn ksock_conn_t
typedef struct ksock_route ksock_route_t
typedef struct ksock_peer ksock_peer_t
typedef struct ksock_connreq ksock_connreq_t
typedef struct ksock_proto ksock_proto_t
Functions
static __u32 ksocknal_csum (__u32 crc, unsigned char const *p, size_t len)
static int ksocknal_route_mask (void)
static struct list_head * ksocknal_nid2peerlist (lnet_nid_t nid)
static void ksocknal_conn_addref (ksock_conn_t *conn)
void ksocknal_queue_zombie_conn (ksock_conn_t *conn)
void ksocknal_finalize_zcreq (ksock_conn_t *conn)
static void ksocknal_conn_decref (ksock_conn_t *conn)
static int ksocknal_connsock_addref (ksock_conn_t *conn)
static void ksocknal_connsock_decref (ksock_conn_t *conn)
static void ksocknal_tx_addref (ksock_tx_t *tx)
void ksocknal_tx_prep (ksock_conn_t *, ksock_tx_t *tx)
void ksocknal_tx_done (lnet_ni_t *ni, ksock_tx_t *tx)
static void ksocknal_tx_decref (ksock_tx_t *tx)
static void ksocknal_route_addref (ksock_route_t *route)
void ksocknal_destroy_route (ksock_route_t *route)
static void ksocknal_route_decref (ksock_route_t *route)
static void ksocknal_peer_addref (ksock_peer_t *peer)
void ksocknal_destroy_peer (ksock_peer_t *peer)
static void ksocknal_peer_decref (ksock_peer_t *peer)
int ksocknal_startup (lnet_ni_t *ni)
void ksocknal_shutdown (lnet_ni_t *ni)
int ksocknal_ctl (lnet_ni_t *ni, unsigned int cmd, void *arg)
int ksocknal_send (lnet_ni_t *ni, void *private, lnet_msg_t *lntmsg)
int ksocknal_recv (lnet_ni_t *ni, void *private, lnet_msg_t *lntmsg, int delayed, unsigned int niov, struct kvec *iov, lnet_kiov_t *kiov, unsigned int offset, unsigned int mlen, unsigned int rlen)
int ksocknal_accept (lnet_ni_t *ni, struct socket *sock)
int ksocknal_add_peer (lnet_ni_t *ni, lnet_process_id_t id, __u32 ip, int port)
ksock_peer_t * ksocknal_find_peer_locked (lnet_ni_t *ni, lnet_process_id_t id)
ksock_peer_t * ksocknal_find_peer (lnet_ni_t *ni, lnet_process_id_t id)
void ksocknal_peer_failed (ksock_peer_t *peer)
int ksocknal_create_conn (lnet_ni_t *ni, ksock_route_t *route, struct socket *sock, int type)
void ksocknal_close_conn_locked (ksock_conn_t *conn, int why)
void ksocknal_terminate_conn (ksock_conn_t *conn)
void ksocknal_destroy_conn (ksock_conn_t *conn)
int ksocknal_close_peer_conns_locked (ksock_peer_t *peer, __u32 ipaddr, int why)
int ksocknal_close_conn_and_siblings (ksock_conn_t *conn, int why)
int ksocknal_close_matching_conns (lnet_process_id_t id, __u32 ipaddr)
ksock_conn_t * ksocknal_find_conn_locked (ksock_peer_t *peer, ksock_tx_t *tx, int nonblk)
int ksocknal_launch_packet (lnet_ni_t *ni, ksock_tx_t *tx, lnet_process_id_t id)
ksock_tx_t * ksocknal_alloc_tx (int type, int size)
void ksocknal_free_tx (ksock_tx_t *tx)
ksock_tx_t * ksocknal_alloc_tx_noop (__u64 cookie, int nonblk)
void ksocknal_next_tx_carrier (ksock_conn_t *conn)
void ksocknal_queue_tx_locked (ksock_tx_t *tx, ksock_conn_t *conn)
void ksocknal_txlist_done (lnet_ni_t *ni, struct list_head *txlist, int error)
void ksocknal_notify (lnet_ni_t *ni, lnet_nid_t gw_nid, int alive)
void ksocknal_query (struct lnet_ni *ni, lnet_nid_t nid, cfs_time_t *when)
int ksocknal_thread_start (int(*fn)(void *arg), void *arg, char *name)
void ksocknal_thread_fini (void)
void ksocknal_launch_all_connections_locked (ksock_peer_t *peer)
ksock_route_t * ksocknal_find_connectable_route_locked (ksock_peer_t *peer)
ksock_route_t * ksocknal_find_connecting_route_locked (ksock_peer_t *peer)
int ksocknal_new_packet (ksock_conn_t *conn, int skip)
int ksocknal_scheduler (void *arg)
int ksocknal_connd (void *arg)
int ksocknal_reaper (void *arg)
int ksocknal_send_hello (lnet_ni_t *ni, ksock_conn_t *conn, lnet_nid_t peer_nid, ksock_hello_msg_t *hello)
int ksocknal_recv_hello (lnet_ni_t *ni, ksock_conn_t *conn, ksock_hello_msg_t *hello, lnet_process_id_t *id, __u64 *incarnation)
void ksocknal_read_callback (ksock_conn_t *conn)
void ksocknal_write_callback (ksock_conn_t *conn)
int ksocknal_lib_zc_capable (ksock_conn_t *conn)
void ksocknal_lib_save_callback (struct socket *sock, ksock_conn_t *conn)
void ksocknal_lib_set_callback (struct socket *sock, ksock_conn_t *conn)
void ksocknal_lib_reset_callback (struct socket *sock, ksock_conn_t *conn)
void ksocknal_lib_push_conn (ksock_conn_t *conn)
int ksocknal_lib_get_conn_addrs (ksock_conn_t *conn)
int ksocknal_lib_setup_sock (struct socket *so)
int ksocknal_lib_send_iov (ksock_conn_t *conn, ksock_tx_t *tx)
int ksocknal_lib_send_kiov (ksock_conn_t *conn, ksock_tx_t *tx)
void ksocknal_lib_eager_ack (ksock_conn_t *conn)
int ksocknal_lib_recv_iov (ksock_conn_t *conn)
int ksocknal_lib_recv_kiov (ksock_conn_t *conn)
int ksocknal_lib_get_conn_tunables (ksock_conn_t *conn, int *txmem, int *rxmem, int *nagle)
int ksocknal_tunables_init (void)
void ksocknal_lib_csum_tx (ksock_tx_t *tx)
int ksocknal_lib_memory_pressure (ksock_conn_t *conn)
int ksocknal_lib_bind_thread_to_cpu (int id)
Variables
ksock_nal_data_t ksocknal_data
ksock_tunables_t ksocknal_tunables
ksock_proto_t ksocknal_protocol_v1x
ksock_proto_t ksocknal_protocol_v2x
ksock_proto_t ksocknal_protocol_v3x
Define Documentation
#define cfs_tcp_sendpage (sk, page, offset, size, flags) tcp_sendpage(sk, page, offset, size, flags)
Definition at line 65 of file socklnd.h.
Referenced by ksocknal_lib_send_kiov().
#define CPU_MASK_NONE 0UL
Definition at line 478 of file socklnd.h.
#define DEBUG_PORTAL_ALLOC
Definition at line 31 of file socklnd.h.
#define DEBUG_SUBSYSTEM S_LND
Definition at line 32 of file socklnd.h.
#define KSOCK_CPT_SHIFT 16
Definition at line 120 of file socklnd.h.
#define KSOCK_NOOP_TX_SIZE ((int)offsetof(ksock_tx_t, tx_frags.paged.kiov[0]))
Definition at line 303 of file socklnd.h.
Referenced by ksocknal_alloc_tx(), ksocknal_alloc_tx_noop(), and ksocknal_free_tx().
#define KSOCK_PROTO_V1 KSOCK_PROTO_V1_MAJOR
Definition at line 475 of file socklnd.h.
Referenced by ksocknal_new_packet().
#define KSOCK_PROTO_V1_MAJOR LNET_PROTO_TCP_VERSION_MAJOR
Definition at line 473 of file socklnd.h.
Referenced by ksocknal_parse_proto_version(), and ksocknal_send_hello_v1().
#define KSOCK_PROTO_V1_MINOR LNET_PROTO_TCP_VERSION_MINOR
Definition at line 474 of file socklnd.h.
Referenced by ksocknal_parse_proto_version(), and ksocknal_send_hello_v1().
#define KSOCK_THREAD_CPT (id) ((id) >> KSOCK_CPT_SHIFT)
Definition at line 122 of file socklnd.h.
Referenced by ksocknal_scheduler().
#define KSOCK_THREAD_ID (cpt, sid) (((cpt) << KSOCK_CPT_SHIFT) | (sid))
Definition at line 121 of file socklnd.h.
Referenced by ksocknal_start_schedulers().
#define KSOCK_THREAD_SID (id) ((id) & ((1UL << KSOCK_CPT_SHIFT) - 1))
Definition at line 123 of file socklnd.h.
Referenced by ksocknal_scheduler(), and ksocknal_start_schedulers().
#define SOCKNAL_CONND_RESV 1
reserved thread for accepting & creating new connd
Definition at line 191 of file socklnd.h.
Referenced by ksocknal_base_startup(), ksocknal_connd(), ksocknal_connd_check_start(), and ksocknal_connd_check_stop().
#define SOCKNAL_CONND_TIMEOUT 120
connd timeout
Definition at line 189 of file socklnd.h.
Referenced by ksocknal_connd_check_stop().
#define SOCKNAL_ENOMEM_RETRY CFS_TICK
Definition at line 76 of file socklnd.h.
Referenced by ksocknal_process_transmit(), and ksocknal_reaper().
#define SOCKNAL_INIT_ALL 2
Definition at line 256 of file socklnd.h.
Referenced by ksocknal_base_shutdown(), ksocknal_base_startup(), ksocknal_connd_check_start(), ksocknal_connd_check_stop(), and ksocknal_shutdown().
#define SOCKNAL_INIT_DATA 1
Definition at line 255 of file socklnd.h.
Referenced by ksocknal_base_shutdown(), and ksocknal_base_startup().
#define SOCKNAL_INIT_NOTHING 0
Definition at line 254 of file socklnd.h.
Referenced by ksocknal_base_shutdown(), ksocknal_base_startup(), and ksocknal_startup().
#define SOCKNAL_INSANITY_RECONN 5000
Definition at line 75 of file socklnd.h.
Referenced by ksocknal_connd().
#define SOCKNAL_KEEPALIVE_PING 1
Definition at line 407 of file socklnd.h.
Referenced by ksocknal_check_zc_req(), ksocknal_create_peer(), ksocknal_handle_zcack(), and ksocknal_queue_tx_zcack_v3().
#define SOCKNAL_MATCH_MAY 2
Definition at line 449 of file socklnd.h.
Referenced by ksocknal_find_conn_locked(), ksocknal_match_tx(), and ksocknal_match_tx_v3().
#define SOCKNAL_MATCH_NO 0
Definition at line 447 of file socklnd.h.
Referenced by ksocknal_create_conn(), ksocknal_find_conn_locked(), and ksocknal_match_tx_v3().
#define SOCKNAL_MATCH_YES 1
Definition at line 448 of file socklnd.h.
Referenced by ksocknal_find_conn_locked(), ksocknal_match_tx(), and ksocknal_match_tx_v3().
#define SOCKNAL_NSCHEDS 3
Definition at line 70 of file socklnd.h.
Referenced by ksocknal_base_startup(), and ksocknal_start_schedulers().
#define SOCKNAL_NSCHEDS_HIGH (SOCKNAL_NSCHEDS << 1)
Definition at line 71 of file socklnd.h.
Referenced by ksocknal_start_schedulers().
#define SOCKNAL_PEER_HASH_SIZE 101
Definition at line 73 of file socklnd.h.
Referenced by ksocknal_base_startup().
#define SOCKNAL_RESCHED 100
Definition at line 74 of file socklnd.h.
Referenced by ksocknal_connd(), and ksocknal_scheduler().
#define SOCKNAL_RISK_KMAP_DEADLOCK 1
Definition at line 88 of file socklnd.h.
#define SOCKNAL_RX_KSM_HEADER 1
Definition at line 314 of file socklnd.h.
Referenced by ksocknal_destroy_conn(), ksocknal_new_packet(), and ksocknal_process_receive().
#define SOCKNAL_RX_LNET_HEADER 2
Definition at line 315 of file socklnd.h.
Referenced by ksocknal_destroy_conn(), ksocknal_new_packet(), and ksocknal_process_receive().
#define SOCKNAL_RX_LNET_PAYLOAD 5
Definition at line 318 of file socklnd.h.
Referenced by ksocknal_destroy_conn(), ksocknal_process_receive(), and ksocknal_recv().
#define SOCKNAL_RX_PARSE 3
Definition at line 316 of file socklnd.h.
Referenced by ksocknal_process_receive(), ksocknal_recv(), and ksocknal_scheduler().
#define SOCKNAL_RX_PARSE_WAIT 4
Definition at line 317 of file socklnd.h.
Referenced by ksocknal_recv(), and ksocknal_scheduler().
#define SOCKNAL_RX_SLOP 6
Definition at line 319 of file socklnd.h.
Referenced by ksocknal_destroy_conn(), ksocknal_new_packet(), and ksocknal_process_receive().
#define SOCKNAL_SINGLE_FRAG_RX 0
Definition at line 79 of file socklnd.h.
#define SOCKNAL_SINGLE_FRAG_TX 0
Definition at line 78 of file socklnd.h.
#define SOCKNAL_VERSION_DEBUG 0
Definition at line 81 of file socklnd.h.
Typedef Documentation
typedef struct ksock_conn ksock_conn_t
typedef struct ksock_connreq ksock_connreq_t
typedef struct ksock_peer ksock_peer_t
typedef struct ksock_proto ksock_proto_t
typedef struct ksock_route ksock_route_t
Function Documentation
int ksocknal_accept (lnet_ni_t * ni, struct socket * sock)
Definition at line 973 of file socklnd.c.
References ksock_connreq::ksncr_list, ksock_connreq::ksncr_ni, ksock_connreq::ksncr_sock, ksock_nal_data_t::ksnd_connd_connreqs, ksock_nal_data_t::ksnd_connd_lock, ksock_nal_data_t::ksnd_connd_waitq, LASSERT, LCONSOLE_ERROR_MSG, LIBCFS_ALLOC, list_add_tail(), lnet_ni_addref(), and lnet_sock_getaddr().
Referenced by ksocklnd_init().
int ksocknal_add_peer (lnet_ni_t * ni, lnet_process_id_t id, __u32 ip, int port)
Definition at line 448 of file socklnd.c.
References ksock_nal_data_t::ksnd_global_lock, ksock_peer::ksnp_list, ksock_peer::ksnp_routes, ksock_route::ksnr_ipaddr, ksock_route::ksnr_share_count, ksocknal_add_route_locked(), ksocknal_create_peer(), ksocknal_create_route(), ksocknal_find_peer_locked(), ksocknal_nid2peerlist(), ksocknal_peer_decref(), ksocknal_route_decref(), LASSERT, list_add_tail(), list_entry, list_for_each, LNET_NID_ANY, LNET_PID_ANY, and lnet_ni::ni_data.
Referenced by ksocknal_ctl(), ksocknal_launch_packet(), and ksocknal_query().
ksock_tx_t* ksocknal_alloc_tx (int type, int size)
Definition at line 30 of file socklnd_cb.c.
References ksock_nal_data_t::ksnd_idle_noop_txs, ksock_nal_data_t::ksnd_nactive_txs, ksock_nal_data_t::ksnd_tx_lock, KSOCK_MSG_NOOP, KSOCK_NOOP_TX_SIZE, ksocknal_data, LASSERT, LIBCFS_ALLOC, list_del(), list_empty(), list_entry, ksock_tx_t::tx_desc_size, ksock_tx_t::tx_list, ksock_tx_t::tx_refcount, ksock_tx_t::tx_zc_aborted, ksock_tx_t::tx_zc_capable, and ksock_tx_t::tx_zc_checked.
Referenced by ksocknal_alloc_tx_noop(), and ksocknal_send().
ksock_tx_t* ksocknal_alloc_tx_noop (__u64 cookie, int nonblk)
Definition at line 68 of file socklnd_cb.c.
References CERROR, KSOCK_MSG_NOOP, KSOCK_NOOP_TX_SIZE, ksocknal_alloc_tx(), socklnd_init_msg(), ksock_tx_t::tx_conn, ksock_tx_t::tx_frags, ksock_tx_t::tx_iov, ksock_tx_t::tx_kiov, ksock_tx_t::tx_lnetmsg, ksock_tx_t::tx_msg, ksock_tx_t::tx_niov, ksock_tx_t::tx_nkiov, ksock_tx_t::tx_nonblk, and ksock_tx_t::virt.
Referenced by ksocknal_handle_zcreq(), and ksocknal_send_keepalive_locked().
int ksocknal_close_conn_and_siblings (ksock_conn_t * conn, int why)
Definition at line 1716 of file socklnd.c.
References ksock_conn::ksnc_ipaddr, ksock_conn::ksnc_peer, ksock_nal_data_t::ksnd_global_lock, and ksocknal_close_peer_conns_locked().
Referenced by ksocknal_check_peer_timeouts(), ksocknal_process_receive(), and ksocknal_process_transmit().
void ksocknal_close_conn_locked (ksock_conn_t * conn, int why)
Definition at line 1404 of file socklnd.c.
References ksock_conn::ksnc_closing, ksock_conn::ksnc_list, ksock_conn::ksnc_peer, ksock_conn::ksnc_proto, ksock_conn::ksnc_route, ksock_conn::ksnc_scheduler, ksock_conn::ksnc_tx_queue, ksock_conn::ksnc_type, ksock_nal_data_t::ksnd_deathrow_conns, ksock_nal_data_t::ksnd_reaper_lock, ksock_nal_data_t::ksnd_reaper_waitq, ksock_peer::ksnp_conns, ksock_peer::ksnp_error, ksock_peer::ksnp_proto, ksock_peer::ksnp_routes, ksock_peer::ksnp_tx_queue, ksock_route::ksnr_connected, ksock_route::ksnr_deleted, ksock_route::ksnr_list, ksocknal_protocol_v3x, ksocknal_route_decref(), ksocknal_tx_prep(), ksocknal_unlink_peer_locked(), ksock_sched_t::kss_lock, LASSERT, list_add_tail(), list_del(), list_empty(), list_entry, list_for_each, list_for_each_entry, and list_splice_init().
Referenced by ksocknal_close_peer_conns_locked(), ksocknal_create_conn(), ksocknal_del_peer_locked(), ksocknal_del_route_locked(), and ksocknal_peer_del_interface_locked().
int ksocknal_close_matching_conns (lnet_process_id_t id, __u32 ipaddr)
Definition at line 1732 of file socklnd.c.
References ksock_nal_data_t::ksnd_global_lock, ksock_nal_data_t::ksnd_peer_hash_size, ksock_nal_data_t::ksnd_peers, ksock_peer::ksnp_id, ksocknal_close_peer_conns_locked(), ksocknal_nid2peerlist(), list_entry, list_for_each_safe, LNET_NID_ANY, LNET_PID_ANY, lnet_process_id_t::nid, and lnet_process_id_t::pid.
Referenced by ksocknal_ctl(), and ksocknal_notify().
int ksocknal_close_peer_conns_locked (ksock_peer_t * peer, __u32 ipaddr, int why)
Definition at line 1695 of file socklnd.c.
References ksock_conn::ksnc_ipaddr, ksock_peer::ksnp_conns, ksocknal_close_conn_locked(), list_entry, and list_for_each_safe.
Referenced by ksocknal_close_conn_and_siblings(), ksocknal_close_matching_conns(), and ksocknal_create_conn().
static void ksocknal_conn_addref (ksock_conn_t * conn) [inline, static]
Definition at line 513 of file socklnd.h.
References ksock_conn::ksnc_conn_refcount, and LASSERT.
Referenced by ksocknal_check_peer_timeouts(), ksocknal_create_conn(), ksocknal_find_timed_out_conn(), ksocknal_get_conn_by_idx(), ksocknal_process_receive(), ksocknal_push_peer(), ksocknal_queue_tx_locked(), ksocknal_read_callback(), ksocknal_terminate_conn(), ksocknal_tx_prep(), and ksocknal_write_callback().
static void ksocknal_conn_decref (ksock_conn_t * conn) [inline, static]
Definition at line 523 of file socklnd.h.
References ksock_conn::ksnc_conn_refcount, ksocknal_queue_zombie_conn(), and LASSERT.
Referenced by ksocknal_check_peer_timeouts(), ksocknal_create_conn(), ksocknal_ctl(), ksocknal_process_receive(), ksocknal_push_peer(), ksocknal_reaper(), ksocknal_recv(), ksocknal_scheduler(), and ksocknal_tx_done().
int ksocknal_connd (void * arg)
Definition at line 2134 of file socklnd_cb.c.
References cfs_block_allsigs(), cfs_time_current_sec(), CWARN, ksock_connreq::ksncr_list, ksock_connreq::ksncr_ni, ksock_connreq::ksncr_sock, ksock_nal_data_t::ksnd_connd_connecting, ksock_nal_data_t::ksnd_connd_connreqs, ksock_nal_data_t::ksnd_connd_lock, ksock_nal_data_t::ksnd_connd_running, ksock_nal_data_t::ksnd_connd_starting, ksock_nal_data_t::ksnd_connd_waitq, ksock_nal_data_t::ksnd_shuttingdown, ksock_route::ksnr_connd_list, ksock_route::ksnr_ipaddr, ksocknal_connd_check_start(), ksocknal_connd_check_stop(), ksocknal_connd_get_route_locked(), ksocknal_connect(), ksocknal_create_conn(), ksocknal_data, ksocknal_route_decref(), ksocknal_thread_fini(), LASSERT, LIBCFS_FREE, list_del(), list_empty(), list_entry, lnet_ni_decref(), SOCKLND_CONN_NONE, SOCKNAL_CONND_RESV, SOCKNAL_INSANITY_RECONN, SOCKNAL_RESCHED, and timeout.
Referenced by ksocknal_base_startup(), and ksocknal_connd_check_start().
static int ksocknal_connsock_addref (ksock_conn_t * conn) [inline, static]
Definition at line 531 of file socklnd.h.
References ksock_conn::ksnc_closing, ksock_conn::ksnc_sock_refcount, ksock_nal_data_t::ksnd_global_lock, and LASSERT.
Referenced by ksocknal_create_conn(), ksocknal_lib_get_conn_tunables(), ksocknal_lib_push_conn(), ksocknal_receive(), and ksocknal_transmit().
static void ksocknal_connsock_decref (ksock_conn_t * conn) [inline, static]
Definition at line 547 of file socklnd.h.
References ksock_conn::ksnc_closing, ksock_conn::ksnc_sock, ksock_conn::ksnc_sock_refcount, ksocknal_finalize_zcreq(), and LASSERT.
Referenced by ksocknal_create_conn(), ksocknal_lib_get_conn_tunables(), ksocknal_lib_push_conn(), ksocknal_receive(), ksocknal_terminate_conn(), and ksocknal_transmit().
int ksocknal_create_conn (lnet_ni_t * ni, ksock_route_t * route, struct socket * sock, int type)
Definition at line 1016 of file socklnd.c.
References __u64, CDEBUG, CERROR, cfs_time_current(), cfs_time_shift(), D_NET, INIT_LIST_HEAD, ksock_sched_info::ksi_scheds, ksock_conn::ksnc_closing, ksock_conn::ksnc_conn_refcount, ksock_conn::ksnc_ipaddr, ksock_conn::ksnc_list, ksock_conn::ksnc_myipaddr, ksock_conn::ksnc_peer, ksock_conn::ksnc_port, ksock_conn::ksnc_proto, ksock_conn::ksnc_route, ksock_conn::ksnc_rx_ready, ksock_conn::ksnc_rx_scheduled, ksock_conn::ksnc_scheduler, ksock_conn::ksnc_sock, ksock_conn::ksnc_sock_refcount, ksock_conn::ksnc_tx_bufnob, ksock_conn::ksnc_tx_carrier, ksock_conn::ksnc_tx_deadline, ksock_conn::ksnc_tx_last_post, ksock_conn::ksnc_tx_nob, ksock_conn::ksnc_tx_queue, ksock_conn::ksnc_tx_ready, ksock_conn::ksnc_tx_scheduled, ksock_conn::ksnc_type, ksock_conn::ksnc_zc_capable, ksock_nal_data_t::ksnd_global_lock, ksock_tunables_t::ksnd_timeout, ksock_peer::ksnp_accepting, ksock_peer::ksnp_closing, ksock_peer::ksnp_conns, ksock_peer::ksnp_error, ksock_peer::ksnp_id, ksock_peer::ksnp_incarnation, ksock_peer::ksnp_last_alive, ksock_peer::ksnp_list, ksock_peer::ksnp_ni, ksock_peer::ksnp_proto, ksock_peer::ksnp_routes, ksock_peer::ksnp_send_keepalive, ksock_peer::ksnp_tx_queue, ksock_route::ksnr_deleted, ksock_route::ksnr_ipaddr, ksock_route::ksnr_peer, ksocknal_associate_route_conn_locked(), ksocknal_choose_scheduler_locked(), ksocknal_close_conn_locked(), ksocknal_close_peer_conns_locked(), ksocknal_conn_addref(), ksocknal_conn_decref(), ksocknal_connecting(), ksocknal_connsock_addref(), ksocknal_connsock_decref(), ksocknal_create_peer(), ksocknal_create_routes(), ksocknal_find_peer_locked(), ksocknal_lib_get_conn_addrs(), ksocknal_lib_save_callback(), ksocknal_lib_set_callback(), ksocknal_lib_setup_sock(), ksocknal_lib_zc_capable(), ksocknal_local_ipvec(), ksocknal_new_packet(), ksocknal_nid2peerlist(), ksocknal_peer_addref(), ksocknal_peer_decref(), ksocknal_protocol_v1x, ksocknal_protocol_v2x, ksocknal_protocol_v3x, ksocknal_queue_tx_locked(), ksocknal_read_callback(), ksocknal_recv_hello(), ksocknal_select_ips(), ksocknal_send_hello(), ksocknal_tunables, ksocknal_txlist_done(), ksocknal_unlink_peer_locked(), ksocknal_write_callback(), ksock_sched_t::kss_info, ksock_sched_t::kss_nconns, LASSERT, LBUG, LIBCFS_ALLOC, LIBCFS_FREE, libcfs_id2str(), list_add(), list_add_tail(), list_del(), list_del_init(), list_empty(), list_entry, list_for_each, list_for_each_entry_safe, LIST_HEAD_INIT, lnet_cpt_of_nid(), LNET_MAX_INTERFACES, LNET_NID_ANY, LNET_PID_ANY, lnet_ni::ni_data, lnet_ni::ni_nid, lnet_process_id_t::nid, offsetof, lnet_process_id_t::pid, ksock_proto::pro_match_tx, ksock_proto::pro_version, SOCKLND_CONN_NONE, SOCKNAL_MATCH_NO, ksock_tx_t::tx_list, ksock_tx_t::tx_nonblk, and warn().
Referenced by ksocknal_connd(), and ksocknal_connect().
static __u32 ksocknal_csum (__u32 crc, unsigned char const * p, size_t len) [inline, static]
Definition at line 481 of file socklnd.h.
Referenced by ksocknal_lib_csum_tx(), ksocknal_lib_recv_iov(), and ksocknal_lib_recv_kiov().
int ksocknal_ctl (lnet_ni_t * ni, unsigned int cmd, void * arg)
Definition at line 2094 of file socklnd.c.
References CERROR, libcfs_ioctl_data::ioc_count, libcfs_ioctl_data::ioc_flags, IOC_LIBCFS_ADD_INTERFACE, IOC_LIBCFS_ADD_PEER, IOC_LIBCFS_CLOSE_CONNECTION, IOC_LIBCFS_DEL_INTERFACE, IOC_LIBCFS_DEL_PEER, IOC_LIBCFS_GET_CONN, IOC_LIBCFS_GET_INTERFACE, IOC_LIBCFS_GET_PEER, IOC_LIBCFS_PUSH_CONNECTION, IOC_LIBCFS_REGISTER_MYNID, libcfs_ioctl_data::ioc_nid, libcfs_ioctl_data::ioc_u32, ksock_sched_info::ksi_cpt, ksock_conn::ksnc_ipaddr, ksock_conn::ksnc_myipaddr, ksock_conn::ksnc_peer, ksock_conn::ksnc_port, ksock_conn::ksnc_scheduler, ksock_conn::ksnc_type, ksock_nal_data_t::ksnd_global_lock, ksock_interface_t::ksni_ipaddr, ksock_interface_t::ksni_netmask, ksock_interface_t::ksni_npeers, ksock_interface_t::ksni_nroutes, ksock_net_t::ksnn_interfaces, ksock_net_t::ksnn_ninterfaces, ksock_peer::ksnp_id, ksocknal_add_interface(), ksocknal_add_peer(), ksocknal_close_matching_conns(), ksocknal_conn_decref(), ksocknal_del_interface(), ksocknal_del_peer(), ksocknal_get_conn_by_idx(), ksocknal_get_peer_info(), ksocknal_lib_get_conn_tunables(), ksocknal_push(), ksock_sched_t::kss_info, libcfs_nid2str(), LNET_PID_ANY, LNET_PID_LUSTRE, nagle, lnet_ni::ni_data, lnet_ni::ni_nid, lnet_process_id_t::nid, and lnet_process_id_t::pid.
Referenced by ksocklnd_init().
void ksocknal_destroy_conn (ksock_conn_t * conn)
Definition at line 1630 of file socklnd.c.
References CDEBUG, CERROR, cfs_duration_sec(), cfs_time_current(), cfs_time_seconds(), cfs_time_sub(), D_NET, ksock_conn::ksnc_conn_refcount, ksock_conn::ksnc_cookie, ksock_conn::ksnc_ipaddr, ksock_conn::ksnc_peer, ksock_conn::ksnc_port, ksock_conn::ksnc_proto, ksock_conn::ksnc_route, ksock_conn::ksnc_rx_deadline, ksock_conn::ksnc_rx_nob_left, ksock_conn::ksnc_rx_nob_wanted, ksock_conn::ksnc_rx_scheduled, ksock_conn::ksnc_rx_started, ksock_conn::ksnc_rx_state, ksock_conn::ksnc_sock, ksock_conn::ksnc_sock_refcount, ksock_conn::ksnc_tx_queue, ksock_conn::ksnc_tx_scheduled, ksock_conn::ksnc_type, ksock_tunables_t::ksnd_timeout, ksock_peer::ksnp_id, ksock_peer::ksnp_ni, ksocknal_peer_decref(), ksocknal_tunables, LASSERT, LBUG, LIBCFS_FREE, libcfs_id2str(), list_empty(), lnet_finalize(), ksock_proto::pro_version, SOCKNAL_RX_KSM_HEADER, SOCKNAL_RX_LNET_HEADER, SOCKNAL_RX_LNET_PAYLOAD, and SOCKNAL_RX_SLOP.
Referenced by ksocknal_reaper().
void ksocknal_destroy_peer (ksock_peer_t * peer)
Definition at line 151 of file socklnd.c.
References CDEBUG, D_NET, ksock_net_t::ksnn_lock, ksock_net_t::ksnn_npeers, ksock_peer::ksnp_accepting, ksock_peer::ksnp_conns, ksock_peer::ksnp_id, ksock_peer::ksnp_ni, ksock_peer::ksnp_refcount, ksock_peer::ksnp_routes, ksock_peer::ksnp_tx_queue, ksock_peer::ksnp_zc_req_list, LASSERT, LIBCFS_FREE, libcfs_id2str(), list_empty(), and lnet_ni::ni_data.
Referenced by ksocknal_peer_decref().
void ksocknal_destroy_route (ksock_route_t * route)
Definition at line 92 of file socklnd.c.
References ksock_route::ksnr_peer, ksock_route::ksnr_refcount, ksocknal_peer_decref(), LASSERT, and LIBCFS_FREE.
Referenced by ksocknal_route_decref().
void ksocknal_finalize_zcreq (ksock_conn_t * conn)
Definition at line 1519 of file socklnd.c.
References ksock_conn::ksnc_peer, ksock_conn::ksnc_sock, ksock_peer::ksnp_lock, ksock_peer::ksnp_zc_req_list, ksocknal_tx_decref(), LASSERT, list_add(), list_del(), list_empty(), list_entry, list_for_each_entry_safe, LIST_HEAD_INIT, list_head::next, ksock_tx_t::tx_conn, ksock_tx_t::tx_msg, ksock_tx_t::tx_zc_aborted, and ksock_tx_t::tx_zc_list.
Referenced by ksocknal_connsock_decref().
ksock_conn_t* ksocknal_find_conn_locked (ksock_peer_t * peer, ksock_tx_t * tx, int nonblk)
Definition at line 623 of file socklnd_cb.c.
References cfs_time_after(), cfs_time_current(), ksock_conn::ksnc_closing, ksock_conn::ksnc_proto, ksock_conn::ksnc_sock, ksock_conn::ksnc_tx_last_post, ksock_conn::ksnc_tx_nob, ksock_tunables_t::ksnd_round_robin, ksock_peer::ksnp_conns, ksocknal_tunables, LASSERT, LBUG, list_entry, list_for_each, ksock_proto::pro_match_tx, SOCKNAL_MATCH_MAY, SOCKNAL_MATCH_NO, and SOCKNAL_MATCH_YES.
Referenced by ksocknal_handle_zcreq(), ksocknal_launch_packet(), and ksocknal_send_keepalive_locked().
ksock_route_t* ksocknal_find_connectable_route_locked (ksock_peer_t * peer)
Definition at line 778 of file socklnd_cb.c.
References CDEBUG, cfs_duration_sec(), cfs_time_aftereq(), cfs_time_current(), D_NET, ksock_peer::ksnp_routes, ksock_route::ksnr_connected, ksock_route::ksnr_connecting, ksock_route::ksnr_ipaddr, ksock_route::ksnr_retry_interval, ksock_route::ksnr_scheduled, ksock_route::ksnr_timeout, ksocknal_route_mask(), LASSERT, list_entry, list_for_each, and now().
Referenced by ksocknal_launch_all_connections_locked(), ksocknal_launch_packet(), and ksocknal_query().
ksock_route_t* ksocknal_find_connecting_route_locked (ksock_peer_t * peer)
Definition at line 815 of file socklnd_cb.c.
References ksock_peer::ksnp_routes, ksock_route::ksnr_connecting, ksock_route::ksnr_scheduled, LASSERT, list_entry, and list_for_each.
Referenced by ksocknal_connect(), ksocknal_launch_packet(), and ksocknal_peer_failed().
ksock_peer_t* ksocknal_find_peer (lnet_ni_t * ni, lnet_process_id_t id)
Definition at line 205 of file socklnd.c.
References ksock_nal_data_t::ksnd_global_lock, ksocknal_find_peer_locked(), and ksocknal_peer_addref().
ksock_peer_t* ksocknal_find_peer_locked (lnet_ni_t * ni, lnet_process_id_t id)
Definition at line 177 of file socklnd.c.
References CDEBUG, D_NET, ksock_peer::ksnp_closing, ksock_peer::ksnp_id, ksock_peer::ksnp_ni, ksock_peer::ksnp_refcount, ksocknal_nid2peerlist(), LASSERT, libcfs_id2str(), list_entry, list_for_each, lnet_process_id_t::nid, and lnet_process_id_t::pid.
Referenced by ksocknal_add_peer(), ksocknal_create_conn(), ksocknal_find_peer(), ksocknal_launch_packet(), and ksocknal_query().
void ksocknal_free_tx (ksock_tx_t * tx)
Definition at line 94 of file socklnd_cb.c.
References ksock_nal_data_t::ksnd_idle_noop_txs, ksock_nal_data_t::ksnd_nactive_txs, ksock_nal_data_t::ksnd_tx_lock, KSOCK_NOOP_TX_SIZE, ksocknal_data, LIBCFS_FREE, list_add(), ksock_tx_t::tx_desc_size, ksock_tx_t::tx_list, and ksock_tx_t::tx_lnetmsg.
Referenced by ksocknal_handle_zcreq(), ksocknal_send(), ksocknal_send_keepalive_locked(), and ksocknal_tx_done().
void ksocknal_launch_all_connections_locked (ksock_peer_t * peer)
Definition at line 607 of file socklnd_cb.c.
References ksocknal_find_connectable_route_locked(), and ksocknal_launch_connection_locked().
Referenced by ksocknal_launch_packet(), and ksocknal_query().
int ksocknal_launch_packet (lnet_ni_t * ni, ksock_tx_t * tx, lnet_process_id_t id)
Definition at line 833 of file socklnd_cb.c.
References CERROR, cfs_time_shift(), CNETERR, ksock_nal_data_t::ksnd_global_lock, ksock_tunables_t::ksnd_timeout, ksock_peer::ksnp_accepting, ksock_peer::ksnp_tx_queue, ksocknal_add_peer(), ksocknal_data, ksocknal_find_conn_locked(), ksocknal_find_connectable_route_locked(), ksocknal_find_connecting_route_locked(), ksocknal_find_peer_locked(), ksocknal_launch_all_connections_locked(), ksocknal_queue_tx_locked(), ksocknal_tunables, LASSERT, libcfs_id2str(), list_add_tail(), lnet_acceptor_port(), LNET_NIDADDR(), LNET_PID_USERFLAG, ksock_tx_t::tx_conn, ksock_tx_t::tx_deadline, ksock_tx_t::tx_list, and ksock_tx_t::tx_nonblk.
Referenced by ksocknal_handle_zcreq(), ksocknal_send(), and ksocknal_send_keepalive_locked().
int ksocknal_lib_bind_thread_to_cpu (int id)
void ksocknal_lib_csum_tx (ksock_tx_t * tx)
Definition at line 387 of file socklnd_lib.c.
References lnet_kiov_t::kiov_len, lnet_kiov_t::kiov_offset, lnet_kiov_t::kiov_page, ksock_conn::ksnc_proto, ksock_tunables_t::ksnd_inject_csum_error, ksocknal_csum(), ksocknal_protocol_v2x, ksocknal_tunables, LASSERT, ksock_tx_t::tx_conn, ksock_tx_t::tx_iov, ksock_tx_t::tx_kiov, ksock_tx_t::tx_msg, ksock_tx_t::tx_niov, and ksock_tx_t::tx_nkiov.
Referenced by ksocknal_lib_send_iov().
void ksocknal_lib_eager_ack (ksock_conn_t * conn)
Definition at line 188 of file socklnd_lib.c.
References ksock_conn::ksnc_sock, and opt.
Referenced by ksocknal_new_packet().
int ksocknal_lib_get_conn_addrs (ksock_conn_t * conn)
Definition at line 40 of file socklnd_lib.c.
References CERROR, ksock_conn::ksnc_closing, ksock_conn::ksnc_ipaddr, ksock_conn::ksnc_myipaddr, ksock_conn::ksnc_port, ksock_conn::ksnc_sock, LASSERT, and lnet_sock_getaddr().
Referenced by ksocknal_create_conn().
int ksocknal_lib_get_conn_tunables (ksock_conn_t * conn, int * txmem, int * rxmem, int * nagle)
Definition at line 426 of file socklnd_lib.c.
References ksock_conn::ksnc_closing, ksock_conn::ksnc_sock, ksocknal_connsock_addref(), ksocknal_connsock_decref(), LASSERT, and lnet_sock_getbuf().
Referenced by ksocknal_ctl().
int ksocknal_lib_memory_pressure (ksock_conn_t * conn)
Definition at line 732 of file socklnd_lib.c.
References ksock_conn::ksnc_scheduler, ksock_conn::ksnc_sock, ksock_conn::ksnc_tx_ready, and ksock_sched_t::kss_lock.
Referenced by ksocknal_transmit().
void ksocknal_lib_push_conn (ksock_conn_t * conn)
Definition at line 587 of file socklnd_lib.c.
References ksock_conn::ksnc_sock, ksocknal_connsock_addref(), ksocknal_connsock_decref(), and LASSERT.
Referenced by ksocknal_push_peer().
int ksocknal_lib_recv_iov (ksock_conn_t * conn)
Definition at line 203 of file socklnd_lib.c.
References ksock_conn::ksnc_msg, ksock_conn::ksnc_proto, ksock_conn::ksnc_rx_csum, ksock_conn::ksnc_rx_iov, ksock_conn::ksnc_rx_niov, ksock_conn::ksnc_scheduler, ksock_conn::ksnc_sock, ksocknal_csum(), ksocknal_protocol_v2x, ksock_sched_t::kss_scratch_iov, and LASSERT.
Referenced by ksocknal_recv_iov().
int ksocknal_lib_recv_kiov (ksock_conn_t * conn)
Definition at line 308 of file socklnd_lib.c.
References lnet_kiov_t::kiov_len, lnet_kiov_t::kiov_offset, ksock_conn::ksnc_msg, ksock_conn::ksnc_rx_csum, ksock_conn::ksnc_rx_kiov, ksock_conn::ksnc_rx_nkiov, ksock_conn::ksnc_scheduler, ksock_conn::ksnc_sock, ksocknal_csum(), ksocknal_lib_kiov_vmap(), ksocknal_lib_kiov_vunmap(), ksock_sched_t::kss_rx_scratch_pgs, ksock_sched_t::kss_scratch_iov, and LASSERT.
Referenced by ksocknal_recv_kiov().
void ksocknal_lib_reset_callback (struct socket * sock, ksock_conn_t * conn)
Definition at line 715 of file socklnd_lib.c.
References ksock_conn::ksnc_saved_data_ready, and ksock_conn::ksnc_saved_write_space.
Referenced by ksocknal_terminate_conn().
void ksocknal_lib_save_callback (struct socket * sock, ksock_conn_t * conn)
Definition at line 699 of file socklnd_lib.c.
References ksock_conn::ksnc_saved_data_ready, and ksock_conn::ksnc_saved_write_space.
Referenced by ksocknal_create_conn().
int ksocknal_lib_send_iov (ksock_conn_t * conn, ksock_tx_t * tx)
Definition at line 78 of file socklnd_lib.c.
References ksock_conn::ksnc_proto, ksock_conn::ksnc_scheduler, ksock_conn::ksnc_sock, ksock_conn::ksnc_tx_queue, ksock_tunables_t::ksnd_enable_csum, ksocknal_lib_csum_tx(), ksocknal_protocol_v2x, ksocknal_tunables, ksock_sched_t::kss_scratch_iov, list_empty(), ksock_tx_t::tx_iov, ksock_tx_t::tx_msg, ksock_tx_t::tx_niov, ksock_tx_t::tx_nob, and ksock_tx_t::tx_resid.
Referenced by ksocknal_send_iov().
int ksocknal_lib_send_kiov (ksock_conn_t * conn, ksock_tx_t * tx)
Definition at line 120 of file socklnd_lib.c.
References CDEBUG, cfs_tcp_sendpage, D_NET, lnet_kiov_t::kiov_len, lnet_kiov_t::kiov_offset, lnet_kiov_t::kiov_page, ksock_conn::ksnc_scheduler, ksock_conn::ksnc_sock, ksock_conn::ksnc_tx_queue, ksock_sched_t::kss_scratch_iov, LASSERT, list_empty(), ksock_tx_t::tx_kiov, ksock_tx_t::tx_lnetmsg, ksock_tx_t::tx_msg, and ksock_tx_t::tx_nkiov.
Referenced by ksocknal_send_kiov().
void ksocknal_lib_set_callback (struct socket * sock, ksock_conn_t * conn)
Definition at line 706 of file socklnd_lib.c.
References ksocknal_data_ready(), and ksocknal_write_space().
Referenced by ksocknal_create_conn().
int ksocknal_lib_setup_sock (struct socket * so)
Definition at line 457 of file socklnd_lib.c.
References CERROR, ksock_tunables_t::ksnd_keepalive_count, ksock_tunables_t::ksnd_keepalive_idle, ksock_tunables_t::ksnd_keepalive_intvl, ksock_tunables_t::ksnd_nagle, ksock_tunables_t::ksnd_rx_buffer_size, ksock_tunables_t::ksnd_tx_buffer_size, ksocknal_tunables, and lnet_sock_setbuf().
Referenced by ksocknal_create_conn().
int ksocknal_lib_zc_capable (ksock_conn_t * conn)
Definition at line 65 of file socklnd_lib.c.
References ksock_conn::ksnc_proto, ksock_conn::ksnc_sock, and ksocknal_protocol_v1x.
Referenced by ksocknal_create_conn().
int ksocknal_new_packet (ksock_conn_t * conn, int skip)
Definition at line 1028 of file socklnd_cb.c.
References ksock_conn::ksnc_msg, ksock_conn::ksnc_proto, ksock_conn::ksnc_rx_csum, ksock_conn::ksnc_rx_iov, ksock_conn::ksnc_rx_iov_space, ksock_conn::ksnc_rx_kiov, ksock_conn::ksnc_rx_niov, ksock_conn::ksnc_rx_nkiov, ksock_conn::ksnc_rx_nob_left, ksock_conn::ksnc_rx_nob_wanted, ksock_conn::ksnc_rx_started, ksock_conn::ksnc_rx_state, ksock_conn::ksnc_type, ksock_tunables_t::ksnd_eager_ack, KSOCK_PROTO_V1, KSOCK_PROTO_V2, KSOCK_PROTO_V3, ksocknal_lib_eager_ack(), ksocknal_tunables, LASSERT, LBUG, MIN, offsetof, ksock_proto::pro_version, SOCKNAL_RX_KSM_HEADER, SOCKNAL_RX_LNET_HEADER, and SOCKNAL_RX_SLOP.
Referenced by ksocknal_create_conn(), and ksocknal_process_receive().
void ksocknal_next_tx_carrier (ksock_conn_t * conn)
Definition at line 53 of file socklnd_proto.c.
References ksock_conn::ksnc_tx_carrier, ksock_conn::ksnc_tx_queue, LASSERT, list_empty(), list_entry, list_head::next, ksock_tx_t::tx_list, and ksock_tx_t::tx_msg.
Referenced by ksocknal_queue_tx_msg_v2(), ksocknal_queue_tx_zcack_v2(), ksocknal_queue_tx_zcack_v3(), and ksocknal_scheduler().
static struct list_head* ksocknal_nid2peerlist (lnet_nid_t nid) [static, read]
Definition at line 505 of file socklnd.h.
References ksock_nal_data_t::ksnd_peer_hash_size, and ksock_nal_data_t::ksnd_peers.
Referenced by ksocknal_add_peer(), ksocknal_close_matching_conns(), ksocknal_create_conn(), ksocknal_del_peer(), ksocknal_find_peer_locked(), and ksocknal_push().
void ksocknal_notify (lnet_ni_t * ni, lnet_nid_t gw_nid, int alive)
Definition at line 1774 of file socklnd.c.
References CDEBUG, D_NET, ksocknal_close_matching_conns(), libcfs_nid2str(), and LNET_PID_ANY.
Referenced by ksocklnd_init().
static void ksocknal_peer_addref (ksock_peer_t * peer) [inline, static]
Definition at line 594 of file socklnd.h.
References ksock_peer::ksnp_refcount, and LASSERT.
Referenced by ksocknal_add_route_locked(), ksocknal_check_peer_timeouts(), ksocknal_create_conn(), ksocknal_del_peer(), ksocknal_del_peer_locked(), ksocknal_find_peer(), and ksocknal_push().
static void ksocknal_peer_decref (ksock_peer_t * peer) [inline, static]
Definition at line 603 of file socklnd.h.
References ksock_peer::ksnp_refcount, ksocknal_destroy_peer(), and LASSERT.
Referenced by ksocknal_add_peer(), ksocknal_check_peer_timeouts(), ksocknal_create_conn(), ksocknal_del_peer(), ksocknal_del_peer_locked(), ksocknal_destroy_conn(), ksocknal_destroy_route(), ksocknal_push(), and ksocknal_unlink_peer_locked().
void ksocknal_peer_failed (ksock_peer_t * peer)
Definition at line 1492 of file socklnd.c.
References ksock_nal_data_t::ksnd_global_lock, ksock_peer::ksnp_accepting, ksock_peer::ksnp_conns, ksock_peer::ksnp_id, ksock_peer::ksnp_last_alive, ksock_peer::ksnp_ni, ksocknal_find_connecting_route_locked(), list_empty(), lnet_notify(), LNET_PID_USERFLAG, lnet_process_id_t::nid, and lnet_process_id_t::pid.
Referenced by ksocknal_connect(), and ksocknal_terminate_conn().
void ksocknal_query (struct lnet_ni * ni, lnet_nid_t nid, cfs_time_t * when)
Definition at line 1797 of file socklnd.c.
References CDEBUG, cfs_duration_sec(), cfs_time_current(), cfs_time_shift(), D_NET, ksock_conn::ksnc_sock, ksock_conn::ksnc_tx_bufnob, ksock_conn::ksnc_tx_deadline, ksock_nal_data_t::ksnd_global_lock, ksock_tunables_t::ksnd_timeout, ksock_peer::ksnp_conns, ksock_peer::ksnp_last_alive, ksocknal_add_peer(), ksocknal_find_connectable_route_locked(), ksocknal_find_peer_locked(), ksocknal_launch_all_connections_locked(), ksocknal_tunables, libcfs_nid2str(), list_entry, list_for_each, lnet_acceptor_port(), LNET_NIDADDR(), LNET_PID_LUSTRE, and now().
Referenced by ksocklnd_init().
void ksocknal_queue_tx_locked (ksock_tx_t * tx, ksock_conn_t * conn)
Definition at line 690 of file socklnd_cb.c.
References CDEBUG, cfs_time_current(), cfs_time_shift(), D_NET, ksock_conn::ksnc_closing, ksock_conn::ksnc_ipaddr, ksock_conn::ksnc_peer, ksock_conn::ksnc_port, ksock_conn::ksnc_proto, ksock_conn::ksnc_scheduler, ksock_conn::ksnc_sock, ksock_conn::ksnc_tx_bufnob, ksock_conn::ksnc_tx_deadline, ksock_conn::ksnc_tx_list, ksock_conn::ksnc_tx_nob, ksock_conn::ksnc_tx_queue, ksock_conn::ksnc_tx_ready, ksock_conn::ksnc_tx_scheduled, ksock_tunables_t::ksnd_timeout, ksock_peer::ksnp_id, ksock_peer::ksnp_last_alive, KSOCK_MSG_NOOP, ksocknal_conn_addref(), ksocknal_tunables, ksocknal_tx_prep(), ksock_sched_t::kss_lock, ksock_sched_t::kss_tx_conns, ksock_sched_t::kss_waitq, ksock_sched_t::kss_zombie_noop_txs, LASSERT, libcfs_id2str(), list_add_tail(), list_empty(), lnet_iov_nob(), lnet_kiov_nob(), msg, lnet_msg::msg_hdr, ksock_proto::pro_queue_tx_msg, ksock_proto::pro_queue_tx_zcack, ksock_tx_t::tx_iov, ksock_tx_t::tx_kiov, ksock_tx_t::tx_list, ksock_tx_t::tx_lnetmsg, ksock_tx_t::tx_msg, ksock_tx_t::tx_niov, ksock_tx_t::tx_nkiov, ksock_tx_t::tx_nob, and ksock_tx_t::tx_resid.
Referenced by ksocknal_create_conn(), and ksocknal_launch_packet().
void ksocknal_queue_zombie_conn (ksock_conn_t * conn)
Definition at line 1616 of file socklnd.c.
References ksock_conn::ksnc_conn_refcount, ksock_conn::ksnc_list, ksock_nal_data_t::ksnd_reaper_lock, ksock_nal_data_t::ksnd_reaper_waitq, ksock_nal_data_t::ksnd_zombie_conns, LASSERT, and list_add_tail().
Referenced by ksocknal_conn_decref().
void ksocknal_read_callback (ksock_conn_t * conn)
Definition at line 1559 of file socklnd_cb.c.
Referenced by ksocknal_create_conn(), and ksocknal_data_ready().
int ksocknal_reaper (void * arg)
Definition at line 2519 of file socklnd_cb.c.
References cfs_block_allsigs(), cfs_time_add(), cfs_time_current(), cfs_time_seconds(), cfs_time_sub(), INIT_LIST_HEAD, ksock_conn::ksnc_list, ksock_conn::ksnc_scheduler, ksock_conn::ksnc_tx_list, ksock_conn::ksnc_tx_ready, ksock_conn::ksnc_tx_scheduled, ksock_nal_data_t::ksnd_deathrow_conns, ksock_nal_data_t::ksnd_enomem_conns, ksock_nal_data_t::ksnd_peer_hash_size, ksock_nal_data_t::ksnd_reaper_lock, ksock_nal_data_t::ksnd_reaper_waitq, ksock_nal_data_t::ksnd_reaper_waketime, ksock_nal_data_t::ksnd_shuttingdown, ksock_tunables_t::ksnd_timeout, ksock_nal_data_t::ksnd_zombie_conns, ksocknal_check_peer_timeouts(), ksocknal_conn_decref(), ksocknal_data, ksocknal_destroy_conn(), ksocknal_terminate_conn(), ksocknal_thread_fini(), ksocknal_tunables, ksock_sched_t::kss_lock, ksock_sched_t::kss_tx_conns, ksock_sched_t::kss_waitq, LASSERT, list_add(), list_add_tail(), list_del(), list_del_init(), list_empty(), list_entry, list_head::next, SOCKNAL_ENOMEM_RETRY, and timeout.
Referenced by ksocknal_base_startup().
int ksocknal_recv (lnet_ni_t * ni, void * private, lnet_msg_t * lntmsg, int delayed, unsigned int niov, struct kvec * iov, lnet_kiov_t * kiov, unsigned int offset, unsigned int mlen, unsigned int rlen)
Definition at line 1316 of file socklnd_cb.c.
References ksock_rxiovspace_t::iov, ksock_rxiovspace_t::kiov, ksock_conn::ksnc_cookie, ksock_conn::ksnc_rx_iov, ksock_conn::ksnc_rx_iov_space, ksock_conn::ksnc_rx_kiov, ksock_conn::ksnc_rx_list, ksock_conn::ksnc_rx_niov, ksock_conn::ksnc_rx_nkiov, ksock_conn::ksnc_rx_nob_left, ksock_conn::ksnc_rx_nob_wanted, ksock_conn::ksnc_rx_ready, ksock_conn::ksnc_rx_scheduled, ksock_conn::ksnc_rx_state, ksock_conn::ksnc_scheduler, ksocknal_conn_decref(), ksock_sched_t::kss_lock, ksock_sched_t::kss_rx_conns, ksock_sched_t::kss_waitq, LASSERT, list_add_tail(), lnet_extract_iov(), lnet_extract_kiov(), lnet_iov_nob(), lnet_kiov_nob(), LNET_MAX_IOV, SOCKNAL_RX_LNET_PAYLOAD, SOCKNAL_RX_PARSE, and SOCKNAL_RX_PARSE_WAIT.
Referenced by ksocklnd_init().
int ksocknal_recv_hello (lnet_ni_t * ni, ksock_conn_t * conn, ksock_hello_msg_t * hello, lnet_process_id_t * id, __u64 * incarnation)
Definition at line 1696 of file socklnd_cb.c.
References __swab32, CERROR, ksock_conn::ksnc_ipaddr, ksock_conn::ksnc_port, ksock_conn::ksnc_proto, ksock_conn::ksnc_sock, ksock_conn::ksnc_type, ksock_tunables_t::ksnd_timeout, ksocknal_invert_type(), ksocknal_parse_proto_version(), ksocknal_protocol_v1x, ksocknal_protocol_v2x, ksocknal_protocol_v3x, ksocknal_send_hello(), ksocknal_tunables, LASSERT, LCONSOLE_ERROR_MSG, le32_to_cpu, libcfs_id2str(), lnet_acceptor_timeout(), LNET_MKNID(), LNET_NID_ANY, LNET_NIDNET(), LNET_PID_USERFLAG, LNET_PROTO_MAGIC, LNET_PROTO_TCP_MAGIC, lnet_sock_read(), lnet_ni::ni_nid, lnet_process_id_t::nid, lnet_process_id_t::pid, ksock_proto::pro_recv_hello, ksock_proto::pro_version, SOCKLND_CONN_NONE, and timeout.
Referenced by ksocknal_create_conn().
static void ksocknal_route_addref (ksock_route_t * route) [inline, static]
Definition at line 577 of file socklnd.h.
References ksock_route::ksnr_refcount, and LASSERT.
Referenced by ksocknal_associate_route_conn_locked(), and ksocknal_launch_connection_locked().
static void ksocknal_route_decref (ksock_route_t * route) [inline, static]
Definition at line 586 of file socklnd.h.
References ksock_route::ksnr_refcount, ksocknal_destroy_route(), and LASSERT.
Referenced by ksocknal_add_peer(), ksocknal_close_conn_locked(), ksocknal_connd(), ksocknal_create_routes(), and ksocknal_del_route_locked().
static int ksocknal_route_mask (void) [inline, static]
Definition at line 494 of file socklnd.h.
References ksock_tunables_t::ksnd_typed_conns, SOCKLND_CONN_ANY, SOCKLND_CONN_BULK_IN, SOCKLND_CONN_BULK_OUT, and SOCKLND_CONN_CONTROL.
Referenced by ksocknal_connect(), ksocknal_find_connectable_route_locked(), and ksocknal_launch_connection_locked().
int ksocknal_scheduler (void * arg)
Definition at line 1388 of file socklnd_cb.c.
References CERROR, cfs_block_allsigs(), cfs_cpt_bind(), ksock_sched_info::ksi_cpt, ksock_sched_info::ksi_scheds, ksock_conn::ksnc_rx_list, ksock_conn::ksnc_rx_ready, ksock_conn::ksnc_rx_scheduled, ksock_conn::ksnc_rx_state, ksock_conn::ksnc_tx_carrier, ksock_conn::ksnc_tx_list, ksock_conn::ksnc_tx_queue, ksock_conn::ksnc_tx_ready, ksock_conn::ksnc_tx_scheduled, ksock_nal_data_t::ksnd_sched_info, ksock_nal_data_t::ksnd_shuttingdown, KSOCK_THREAD_CPT, KSOCK_THREAD_SID, ksocknal_conn_decref(), ksocknal_data, ksocknal_next_tx_carrier(), ksocknal_process_receive(), ksocknal_process_transmit(), ksocknal_sched_cansleep(), ksocknal_thread_fini(), ksocknal_tx_decref(), ksocknal_txlist_done(), ksock_sched_t::kss_lock, ksock_sched_t::kss_rx_conns, ksock_sched_t::kss_tx_conns, ksock_sched_t::kss_waitq, ksock_sched_t::kss_zombie_noop_txs, LASSERT, list_add(), list_add_tail(), list_del(), list_del_init(), list_empty(), list_entry, LIST_HEAD_INIT, lnet_cpt_table, list_head::next, SOCKNAL_RESCHED, SOCKNAL_RX_PARSE, SOCKNAL_RX_PARSE_WAIT, and ksock_tx_t::tx_list.
Referenced by ksocknal_start_schedulers().
int ksocknal_send (lnet_ni_t * ni, void * private, lnet_msg_t * lntmsg)
Definition at line 924 of file socklnd_cb.c.
References CDEBUG, CERROR, cfs_memory_pressure_get_and_set(), cfs_memory_pressure_restore(), D_NET, ksock_tunables_t::ksnd_zc_min_payload, KSOCK_MSG_LNET, ksocknal_alloc_tx(), ksocknal_free_tx(), ksocknal_launch_packet(), ksocknal_tunables, LASSERT, libcfs_id2str(), lnet_extract_iov(), lnet_extract_kiov(), LNET_MAX_IOV, lnet_msg::msg_iov, lnet_msg::msg_kiov, lnet_msg::msg_len, lnet_msg::msg_niov, lnet_msg::msg_offset, lnet_msg::msg_target, lnet_msg::msg_type, lnet_msg::msg_vmflush, offsetof, ksock_tx_t::paged, socklnd_init_msg(), ksock_tx_t::tx_conn, ksock_tx_t::tx_frags, ksock_tx_t::tx_iov, ksock_tx_t::tx_kiov, ksock_tx_t::tx_lnetmsg, ksock_tx_t::tx_msg, ksock_tx_t::tx_niov, ksock_tx_t::tx_nkiov, ksock_tx_t::tx_zc_capable, and ksock_tx_t::virt.
Referenced by ksocklnd_init().
int ksocknal_send_hello (lnet_ni_t * ni, ksock_conn_t * conn, lnet_nid_t peer_nid, ksock_hello_msg_t * hello)
Definition at line 1657 of file socklnd_cb.c.
References ksock_conn::ksnc_proto, ksock_conn::ksnc_type, ksock_net_t::ksnn_incarnation, LASSERT, lnet_t::ln_pid, LNET_MAX_INTERFACES, lnet_ni::ni_data, lnet_ni::ni_nid, ksock_proto::pro_send_hello, and the_lnet.
Referenced by ksocknal_create_conn(), and ksocknal_recv_hello().
void ksocknal_shutdown (lnet_ni_t * ni)
Definition at line 2558 of file socklnd.c.
References CDEBUG, cfs_time_seconds(), D_NET, D_WARNING, ksock_nal_data_t::ksnd_init, ksock_nal_data_t::ksnd_nnets, ksock_interface_t::ksni_npeers, ksock_interface_t::ksni_nroutes, ksock_net_t::ksnn_interfaces, ksock_net_t::ksnn_list, ksock_net_t::ksnn_lock, ksock_net_t::ksnn_ninterfaces, ksock_net_t::ksnn_npeers, ksock_net_t::ksnn_shutdown, ksocknal_base_shutdown(), ksocknal_debug_peerhash(), ksocknal_del_peer(), LASSERT, LIBCFS_FREE, list_del(), LNET_NID_ANY, LNET_PID_ANY, lnet_ni::ni_data, lnet_process_id_t::nid, lnet_process_id_t::pid, and SOCKNAL_INIT_ALL.
Referenced by ksocklnd_init().
int ksocknal_startup (lnet_ni_t * ni)
Definition at line 2781 of file socklnd.c.
References CERROR, ksock_tunables_t::ksnd_credits, ksock_nal_data_t::ksnd_init, ksock_nal_data_t::ksnd_nets, ksock_nal_data_t::ksnd_nnets, ksock_tunables_t::ksnd_peerrtrcredits, ksock_tunables_t::ksnd_peertimeout, ksock_tunables_t::ksnd_peertxcredits, ksock_interface_t::ksni_ipaddr, ksock_interface_t::ksni_name, ksock_interface_t::ksni_netmask, ksock_net_t::ksnn_incarnation, ksock_net_t::ksnn_interfaces, ksock_net_t::ksnn_list, ksock_net_t::ksnn_lock, ksock_net_t::ksnn_ninterfaces, ksocknal_base_shutdown(), ksocknal_base_startup(), ksocknal_enumerate_interfaces(), ksocknal_net_start_threads(), ksocknal_new_incarnation(), ksocknal_tunables, LASSERT, LIBCFS_ALLOC, LIBCFS_FREE, list_add(), lnet_ipif_query(), LNET_MAX_INTERFACES, LNET_MKNID(), LNET_NIDNET(), lnet_ni::ni_cpts, lnet_ni::ni_data, lnet_ni::ni_interfaces, lnet_ni::ni_lnd, lnet_ni::ni_maxtxcredits, lnet_ni::ni_ncpts, lnet_ni::ni_nid, lnet_ni::ni_peerrtrcredits, lnet_ni::ni_peertimeout, lnet_ni::ni_peertxcredits, SOCKNAL_INIT_NOTHING, and strlcpy().
Referenced by ksocklnd_init().
void ksocknal_terminate_conn (ksock_conn_t * conn)
Definition at line 1555 of file socklnd.c.
References ksock_conn::ksnc_closing, ksock_conn::ksnc_peer, ksock_conn::ksnc_scheduler, ksock_conn::ksnc_sock, ksock_conn::ksnc_tx_list, ksock_conn::ksnc_tx_queue, ksock_conn::ksnc_tx_ready, ksock_conn::ksnc_tx_scheduled, ksock_nal_data_t::ksnd_global_lock, ksock_peer::ksnp_conns, ksock_peer::ksnp_error, ksocknal_conn_addref(), ksocknal_connsock_decref(), ksocknal_lib_reset_callback(), ksocknal_peer_failed(), ksock_sched_t::kss_lock, ksock_sched_t::kss_nconns, ksock_sched_t::kss_tx_conns, ksock_sched_t::kss_waitq, LASSERT, list_add_tail(), and list_empty().
Referenced by ksocknal_reaper().
void ksocknal_thread_fini (void)
Definition at line 1020 of file socklnd_cb.c.
References ksock_nal_data_t::ksnd_global_lock, ksock_nal_data_t::ksnd_nthreads, and ksocknal_data.
Referenced by ksocknal_connd(), ksocknal_reaper(), and ksocknal_scheduler().
int ksocknal_thread_start (int(*)(void *arg) fn, void * arg, char * name)
Definition at line 1006 of file socklnd_cb.c.
References ksock_nal_data_t::ksnd_global_lock, ksock_nal_data_t::ksnd_nthreads, and ksocknal_data.
Referenced by ksocknal_base_startup(), ksocknal_connd_check_start(), and ksocknal_start_schedulers().
int ksocknal_tunables_init (void)
Definition at line 160 of file socklnd_modparams.c.
References credits, CWARN, eager_ack, enable_csum, inject_csum_error, keepalive, keepalive_count, keepalive_idle, keepalive_intvl, ksock_tunables_t::ksnd_credits, ksock_tunables_t::ksnd_eager_ack, ksock_tunables_t::ksnd_enable_csum, ksock_tunables_t::ksnd_inject_csum_error, ksock_tunables_t::ksnd_keepalive, ksock_tunables_t::ksnd_keepalive_count, ksock_tunables_t::ksnd_keepalive_idle, ksock_tunables_t::ksnd_keepalive_intvl, ksock_tunables_t::ksnd_max_reconnectms, ksock_tunables_t::ksnd_min_bulk, ksock_tunables_t::ksnd_min_reconnectms, ksock_tunables_t::ksnd_nagle, ksock_tunables_t::ksnd_nconnds, ksock_tunables_t::ksnd_nconnds_max, ksock_tunables_t::ksnd_nonblk_zcack, ksock_tunables_t::ksnd_nscheds, ksock_tunables_t::ksnd_peerrtrcredits, ksock_tunables_t::ksnd_peertimeout, ksock_tunables_t::ksnd_peertxcredits, ksock_tunables_t::ksnd_round_robin, ksock_tunables_t::ksnd_rx_buffer_size, ksock_tunables_t::ksnd_timeout, ksock_tunables_t::ksnd_tx_buffer_size, ksock_tunables_t::ksnd_typed_conns, ksock_tunables_t::ksnd_zc_min_payload, ksock_tunables_t::ksnd_zc_recv, ksock_tunables_t::ksnd_zc_recv_min_nfrags, max_reconnectms, min_bulk, min_reconnectms, nagle, nconnds, nconnds_max, nonblk_zcack, nscheds, peer_buffer_credits, peer_credits, peer_timeout, round_robin, rx_buffer_size, sock_timeout, tx_buffer_size, typed_conns, zc_min_payload, zc_recv, and zc_recv_min_nfrags.
Referenced by ksocklnd_init().
static void ksocknal_tx_addref (ksock_tx_t * tx) [inline, static]
Definition at line 559 of file socklnd.h.
References LASSERT, and ksock_tx_t::tx_refcount.
Referenced by ksocknal_check_zc_req().
static void ksocknal_tx_decref (ksock_tx_t * tx) [inline, static]
Definition at line 569 of file socklnd.h.
References ksocknal_tx_done(), LASSERT, and ksock_tx_t::tx_refcount.
Referenced by ksocknal_finalize_zcreq(), ksocknal_handle_zcack(), ksocknal_scheduler(), and ksocknal_uncheck_zc_req().
void ksocknal_tx_done (lnet_ni_t * ni, ksock_tx_t * tx)
Definition at line 390 of file socklnd_cb.c.
References ENTRY, EXIT, ksock_conn::ksnc_peer, ksock_peer::ksnp_ni, ksocknal_conn_decref(), ksocknal_free_tx(), LASSERT, lnet_finalize(), ksock_tx_t::tx_conn, ksock_tx_t::tx_lnetmsg, ksock_tx_t::tx_resid, and ksock_tx_t::tx_zc_aborted.
Referenced by ksocknal_tx_decref(), and ksocknal_txlist_done().
void ksocknal_tx_prep (ksock_conn_t * , ksock_tx_t * tx)
Definition at line 680 of file socklnd_cb.c.
References ksock_conn::ksnc_proto, ksock_conn::ksnc_tx_nob, ksocknal_conn_addref(), ksock_proto::pro_pack, ksock_tx_t::tx_conn, and ksock_tx_t::tx_nob.
Referenced by ksocknal_close_conn_locked(), and ksocknal_queue_tx_locked().
void ksocknal_txlist_done (lnet_ni_t * ni, struct list_head * txlist, int error)
Definition at line 412 of file socklnd_cb.c.
References CNETERR, ksocknal_tx_done(), LASSERT, le32_to_cpu, le64_to_cpu, libcfs_nid2str(), list_del(), list_empty(), list_entry, lnet_msg::msg_hdr, list_head::next, ksock_tx_t::tx_list, ksock_tx_t::tx_lnetmsg, and ksock_tx_t::tx_refcount.
Referenced by ksocknal_connect(), ksocknal_create_conn(), ksocknal_del_peer(), ksocknal_flush_stale_txs(), and ksocknal_scheduler().
void ksocknal_write_callback (ksock_conn_t * conn)
Definition at line 1588 of file socklnd_cb.c.
Referenced by ksocknal_create_conn(), and ksocknal_write_space().
Variable Documentation
ksock_nal_data_t ksocknal_data
Definition at line 47 of file socklnd.c.
Referenced by ksocknal_alloc_tx(), ksocknal_check_peer_timeouts(), ksocknal_connd(), ksocknal_connd_check_start(), ksocknal_connd_check_stop(), ksocknal_connd_get_route_locked(), ksocknal_connect(), ksocknal_data_ready(), ksocknal_flush_stale_txs(), ksocknal_free_tx(), ksocknal_handle_zcreq(), ksocknal_launch_connection_locked(), ksocknal_launch_packet(), ksocknal_process_transmit(), ksocknal_reaper(), ksocknal_receive(), ksocknal_sched_cansleep(), ksocknal_scheduler(), ksocknal_send_keepalive_locked(), ksocknal_thread_fini(), ksocknal_thread_start(), ksocknal_transmit(), and ksocknal_write_space().
ksock_proto_t ksocknal_protocol_v1x
Definition at line 758 of file socklnd_proto.c.
Referenced by ksocknal_check_zc_req(), ksocknal_create_conn(), ksocknal_lib_zc_capable(), ksocknal_match_tx(), ksocknal_parse_proto_version(), ksocknal_process_receive(), and ksocknal_recv_hello().
ksock_proto_t ksocknal_protocol_v2x
Definition at line 772 of file socklnd_proto.c.
Referenced by ksocknal_create_conn(), ksocknal_lib_csum_tx(), ksocknal_lib_recv_iov(), ksocknal_lib_send_iov(), ksocknal_parse_proto_version(), and ksocknal_recv_hello().
ksock_proto_t ksocknal_protocol_v3x
Definition at line 786 of file socklnd_proto.c.
Referenced by ksocknal_close_conn_locked(), ksocknal_connect(), ksocknal_create_conn(), ksocknal_handle_zcack(), ksocknal_parse_proto_version(), ksocknal_recv_hello(), and ksocknal_send_keepalive_locked().
ksock_tunables_t ksocknal_tunables
Definition at line 158 of file socklnd_modparams.c.
Referenced by ksocknal_base_startup(), ksocknal_check_zc_req(), ksocknal_connd_check_start(), ksocknal_connd_check_stop(), ksocknal_connect(), ksocknal_create_conn(), ksocknal_destroy_conn(), ksocknal_find_conn_locked(), ksocknal_launch_packet(), ksocknal_lib_csum_tx(), ksocknal_lib_kiov_vmap(), ksocknal_lib_send_iov(), ksocknal_lib_setup_sock(), ksocknal_match_tx(), ksocknal_match_tx_v3(), ksocknal_new_packet(), ksocknal_parse_proto_version(), ksocknal_process_receive(), ksocknal_query(), ksocknal_queue_tx_locked(), ksocknal_reaper(), ksocknal_recv_hello(), ksocknal_recv_iov(), ksocknal_recv_kiov(), ksocknal_send(), ksocknal_send_keepalive_locked(), ksocknal_start_schedulers(), ksocknal_startup(), and ksocknal_transmit().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.