Lustre: lustre/utils/gss/krb5_util.c File Reference
lustre/utils/gss/krb5_util.c File Reference
#include "config.h"
#include <sys/param.h>
#include <rpc/rpc.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/utsname.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <fcntl.h>
#include <errno.h>
#include <time.h>
#include <gssapi/gssapi.h>
#include <krb5.h>
#include "gssd.h"
#include "err_util.h"
#include "gss_util.h"
#include "gss_oids.h"
#include "krb5_util.h"
Defines
#define KEYTAB_ENTRY_MATCH(kte, name)
#define KRB5_FREE_UNPARSED_NAME(ctx, name) free(pname);
#define KRB5_STRDUP(str) strdup(str)
#define KRB5_STRCMP(str, name) strcmp((str), (name))
#define KRB5_STRCASECMP(str, name) strcmp((str), (name))
Functions
static int select_krb5_ccache (const struct dirent *d)
static int gssd_find_existing_krb5_ccache (uid_t uid, struct dirent **d)
static int gssd_get_single_krb5_cred (krb5_context context, krb5_keytab kt, struct gssd_k5_kt_princ *ple)
static int gssd_process_krb5_keytab (krb5_context context, krb5_keytab kt, char *kt_name)
static struct gssd_k5_kt_princ * gssd_get_realm_ple (void *r)
static void gssd_free_ple (krb5_context kctx, struct gssd_k5_kt_princ *ple)
static int gssd_remove_ple (krb5_context kctx, struct gssd_k5_kt_princ *ple)
static struct gssd_k5_kt_princ * gssd_create_ple (krb5_context kctx, krb5_principal principal)
static void gssd_set_krb5_ccache_name (char *ccname)
static int parse_enctypes (char *enctypes)
void gssd_setup_krb5_user_gss_ccache (uid_t uid, char *servername)
void gssd_setup_krb5_machine_gss_ccache (char *ccname)
int gssd_refresh_krb5_machine_creds (void)
int gssd_get_krb5_machine_cred_list (char ***list)
void gssd_free_krb5_machine_cred_list (char **list)
void gssd_destroy_krb5_machine_creds (void)
Variables
struct gssd_k5_kt_princ * gssd_k5_kt_princ_list = NULL
int num_krb5_enctypes = 0
krb5_enctype * krb5_enctypes = NULL
unsigned long machine_cred_expire_advance = 300
Define Documentation
#define KEYTAB_ENTRY_MATCH (kte, name)
Value:
(\
         strlen((kte).principal->name.name_string.val[0]) ==                   \
         (sizeof(name)-1) &&                                                   \
         strncmp(kte.principal->name.name_string.val[0], (name),               \
                 sizeof(name)-1) == 0                                          \
        )
Definition at line 177 of file krb5_util.c.
Referenced by gssd_process_krb5_keytab().
#define KRB5_FREE_UNPARSED_NAME (ctx, name) free(pname);
Definition at line 184 of file krb5_util.c.
Referenced by gssd_get_single_krb5_cred(), and gssd_process_krb5_keytab().
#define KRB5_STRCASECMP (str, name) strcmp((str), (name))
Definition at line 190 of file krb5_util.c.
Referenced by gssd_process_krb5_keytab().
#define KRB5_STRCMP (str, name) strcmp((str), (name))
Definition at line 188 of file krb5_util.c.
Referenced by gssd_get_realm_ple().
#define KRB5_STRDUP (str) strdup(str)
Definition at line 186 of file krb5_util.c.
Referenced by gssd_create_ple().
Function Documentation
static struct gssd_k5_kt_princ* gssd_create_ple (krb5_context kctx, krb5_principal principal) [static, read]
Definition at line 472 of file krb5_util.c.
References gssd_free_ple(), KRB5_STRDUP, gssd_k5_kt_princ::princ, printerr, and gssd_k5_kt_princ::realm.
Referenced by gssd_process_krb5_keytab().
void gssd_destroy_krb5_machine_creds (void)
Definition at line 969 of file krb5_util.c.
References gssd_k5_kt_princ::ccname, gssd_k5_kt_princ::next, and printerr.
Referenced by lgssd_cleanup().
static int gssd_find_existing_krb5_ccache (uid_t uid, struct dirent ** d) [static]
Definition at line 229 of file krb5_util.c.
References ccachedir, printerr, and select_krb5_ccache().
Referenced by gssd_setup_krb5_user_gss_ccache().
void gssd_free_krb5_machine_cred_list (char ** list)
Definition at line 953 of file krb5_util.c.
Referenced by handle_krb5_upcall().
static void gssd_free_ple (krb5_context kctx, struct gssd_k5_kt_princ * ple) [static]
Definition at line 444 of file krb5_util.c.
References gssd_k5_kt_princ::ccname, gssd_k5_kt_princ::princ, and gssd_k5_kt_princ::realm.
Referenced by gssd_create_ple(), and gssd_remove_ple().
int gssd_get_krb5_machine_cred_list (char *** list)
Definition at line 893 of file krb5_util.c.
References gssd_k5_kt_princ::ccname, gssd_refresh_krb5_machine_creds(), and gssd_k5_kt_princ::next.
Referenced by handle_krb5_upcall().
static struct gssd_k5_kt_princ* gssd_get_realm_ple (void * r) [static, read]
Definition at line 428 of file krb5_util.c.
References KRB5_STRCMP, gssd_k5_kt_princ::next, and gssd_k5_kt_princ::realm.
Referenced by gssd_process_krb5_keytab().
static int gssd_get_single_krb5_cred (krb5_context context, krb5_keytab kt, struct gssd_k5_kt_princ * ple) [static]
Definition at line 327 of file krb5_util.c.
References gssd_k5_kt_princ::ccname, gssd_k5_kt_princ::endtime, GSSD_DEFAULT_CRED_DIR, GSSD_DEFAULT_CRED_PREFIX, GSSD_DEFAULT_MACHINE_CRED_SUFFIX, KRB5_FREE_UNPARSED_NAME, machine_cred_expire_advance, now(), gssd_k5_kt_princ::princ, printerr, gssd_k5_kt_princ::realm, and use_memcache.
Referenced by gssd_refresh_krb5_machine_creds().
static int gssd_process_krb5_keytab (krb5_context context, krb5_keytab kt, char * kt_name) [static]
Definition at line 517 of file krb5_util.c.
References gssd_k5_kt_princ::fl_mds, gssd_k5_kt_princ::fl_root, gssd_create_ple(), gssd_get_realm_ple(), gssd_remove_ple(), GSSD_SERVICE_MDS, KEYTAB_ENTRY_MATCH, KRB5_FREE_UNPARSED_NAME, KRB5_STRCASECMP, LUSTRE_ROOT_NAME, gssd_k5_kt_princ::next, gssd_k5_kt_princ::princ, printerr, and this_realm.
Referenced by gssd_refresh_krb5_machine_creds().
int gssd_refresh_krb5_machine_creds (void)
Definition at line 807 of file krb5_util.c.
References gssd_get_single_krb5_cred(), gssd_process_krb5_keytab(), GSSD_SERVICE_MDS, keytabfile, LUSTRE_ROOT_NAME, gssd_k5_kt_princ::next, and printerr.
Referenced by gssd_get_krb5_machine_cred_list(), and main().
static int gssd_remove_ple (krb5_context kctx, struct gssd_k5_kt_princ * ple) [static]
Definition at line 455 of file krb5_util.c.
References gssd_free_ple(), and gssd_k5_kt_princ::next.
Referenced by gssd_process_krb5_keytab().
static void gssd_set_krb5_ccache_name (char * ccname) [static]
Definition at line 669 of file krb5_util.c.
References GSS_S_COMPLETE, and printerr.
Referenced by gssd_setup_krb5_machine_gss_ccache(), and gssd_setup_krb5_user_gss_ccache().
void gssd_setup_krb5_machine_gss_ccache (char * ccname)
Definition at line 787 of file krb5_util.c.
References gssd_set_krb5_ccache_name(), and printerr.
Referenced by handle_krb5_upcall().
void gssd_setup_krb5_user_gss_ccache (uid_t uid, char * servername)
Definition at line 758 of file krb5_util.c.
References buf, ccachedir, GSSD_DEFAULT_CRED_PREFIX, gssd_find_existing_krb5_ccache(), gssd_set_krb5_ccache_name(), and printerr.
Referenced by handle_krb5_upcall().
static int parse_enctypes (char * enctypes) [static]
Definition at line 699 of file krb5_util.c.
References num_krb5_enctypes.
static int select_krb5_ccache (const struct dirent * d) [static]
Definition at line 204 of file krb5_util.c.
References GSSD_DEFAULT_CRED_PREFIX.
Referenced by gssd_find_existing_krb5_ccache().
Variable Documentation
struct gssd_k5_kt_princ* gssd_k5_kt_princ_list = NULL
Definition at line 130 of file krb5_util.c.
krb5_enctype* krb5_enctypes = NULL
Definition at line 134 of file krb5_util.c.
unsigned long machine_cred_expire_advance = 300
Definition at line 137 of file krb5_util.c.
Referenced by gssd_get_single_krb5_cred().
int num_krb5_enctypes = 0
Definition at line 133 of file krb5_util.c.
Referenced by parse_enctypes().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.