Lustre: lustre/utils/gss/krb5_util.h File Reference
lustre/utils/gss/krb5_util.h File Reference
#include <krb5.h>
Data Structures
struct gssd_k5_kt_princ
Functions
void gssd_setup_krb5_user_gss_ccache (uid_t uid, char *servername)
int gssd_get_krb5_machine_cred_list (char ***list)
int gssd_refresh_krb5_machine_creds (void)
void gssd_free_krb5_machine_cred_list (char **list)
void gssd_setup_krb5_machine_gss_ccache (char *servername)
void gssd_destroy_krb5_machine_creds (void)
void gssd_obtain_kernel_krb5_info (void)
Function Documentation
void gssd_destroy_krb5_machine_creds (void)
Definition at line 969 of file krb5_util.c.
References gssd_k5_kt_princ::ccname, gssd_k5_kt_princ::next, and printerr.
Referenced by lgssd_cleanup().
void gssd_free_krb5_machine_cred_list (char ** list)
Definition at line 953 of file krb5_util.c.
Referenced by handle_krb5_upcall().
int gssd_get_krb5_machine_cred_list (char *** list)
Definition at line 893 of file krb5_util.c.
References gssd_k5_kt_princ::ccname, gssd_refresh_krb5_machine_creds(), and gssd_k5_kt_princ::next.
Referenced by handle_krb5_upcall().
void gssd_obtain_kernel_krb5_info (void)
Referenced by main().
int gssd_refresh_krb5_machine_creds (void)
Definition at line 807 of file krb5_util.c.
References gssd_get_single_krb5_cred(), gssd_process_krb5_keytab(), GSSD_SERVICE_MDS, keytabfile, LUSTRE_ROOT_NAME, gssd_k5_kt_princ::next, and printerr.
Referenced by gssd_get_krb5_machine_cred_list(), and main().
void gssd_setup_krb5_machine_gss_ccache (char * servername)
Definition at line 787 of file krb5_util.c.
References gssd_set_krb5_ccache_name(), and printerr.
Referenced by handle_krb5_upcall().
void gssd_setup_krb5_user_gss_ccache (uid_t uid, char * servername)
Definition at line 758 of file krb5_util.c.
References buf, ccachedir, GSSD_DEFAULT_CRED_PREFIX, gssd_find_existing_krb5_ccache(), gssd_set_krb5_ccache_name(), and printerr.
Referenced by handle_krb5_upcall().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.