Lustre: lustre/utils/l_getidentity.c File Reference
lustre/utils/l_getidentity.c File Reference
#include <stdbool.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdio.h>
#include <unistd.h>
#include <errno.h>
#include <string.h>
#include <fcntl.h>
#include <pwd.h>
#include <grp.h>
#include <stdarg.h>
#include <stddef.h>
#include <libgen.h>
#include <syslog.h>
#include <libcfs/util/param.h>
#include <lnet/nidstr.h>
#include <lustre/lustre_user.h>
#include <lustre/lustre_idl.h>
Data Structures
struct perm_type_t
Defines
#define PERM_PATHNAME "/etc/lustre/perm.conf"
Functions
static void usage (void)
static int compare_u32 (const void *v1, const void *v2)
static void errlog (const char *fmt,...)
int get_groups_local (struct identity_downcall_data *data, unsigned int maxgroups)
static int comment_line (char *line)
static int match_uid (uid_t uid, const char *str)
int parse_perm (__u32 *perm, __u32 *noperm, char *str)
static int parse_perm_line (struct identity_downcall_data *data, char *line, size_t size)
int get_perms (struct identity_downcall_data *data)
static void show_result (struct identity_downcall_data *data)
int main (int argc, char **argv)
Variables
static char * progname
static perm_type_t perm_types []
static perm_type_t noperm_types []
Define Documentation
#define PERM_PATHNAME "/etc/lustre/perm.conf"
Definition at line 58 of file l_getidentity.c.
Referenced by get_perms().
Function Documentation
static int comment_line (char * line) [inline, static]
Definition at line 172 of file l_getidentity.c.
Referenced by get_perms().
static int compare_u32 (const void * v1, const void * v2) [static]
Definition at line 86 of file l_getidentity.c.
Referenced by get_groups_local().
static void errlog (const char * fmt, ...) [static]
Definition at line 91 of file l_getidentity.c.
References progname.
Referenced by get_groups_local(), get_perms(), main(), parse_perm_line(), and show_result().
int get_groups_local (struct identity_downcall_data * data, unsigned int maxgroups)
Definition at line 104 of file l_getidentity.c.
References compare_u32(), errlog(), identity_downcall_data::idd_err, identity_downcall_data::idd_gid, identity_downcall_data::idd_groups, identity_downcall_data::idd_ngroups, identity_downcall_data::idd_uid, and strlcpy().
Referenced by main().
int get_perms (struct identity_downcall_data * data)
Definition at line 362 of file l_getidentity.c.
References comment_line(), errlog(), identity_downcall_data::idd_err, parse_perm_line(), and PERM_PATHNAME.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 422 of file l_getidentity.c.
References cfs_free_param_data(), cfs_get_param_paths(), end, errlog(), get_groups_local(), get_perms(), identity_downcall_data::idd_groups, identity_downcall_data::idd_magic, identity_downcall_data::idd_ngroups, identity_downcall_data::idd_uid, IDENTITY_DOWNCALL_MAGIC, NGROUPS_MAX, offsetof, path, progname, show_result(), size, and usage.
static int match_uid (uid_t uid, const char * str) [inline, static]
Definition at line 183 of file l_getidentity.c.
References end.
Referenced by parse_perm_line().
int parse_perm (__u32 * perm, __u32 * noperm, char * str)
Definition at line 220 of file l_getidentity.c.
References perm_type_t::bit, end, perm_type_t::name, name, and start.
Referenced by parse_perm_line().
static int parse_perm_line (struct identity_downcall_data * data, char * line, size_t size) [static]
Definition at line 269 of file l_getidentity.c.
References errlog(), identity_downcall_data::idd_nperms, identity_downcall_data::idd_perms, identity_downcall_data::idd_uid, libcfs_str2nid(), LNET_NID_ANY, match_uid(), N_PERMS_MAX, parse_perm(), perm_downcall_data::pdd_nid, and perm_downcall_data::pdd_perm.
Referenced by get_perms().
static void show_result (struct identity_downcall_data * data) [static]
Definition at line 395 of file l_getidentity.c.
References errlog(), identity_downcall_data::idd_err, identity_downcall_data::idd_gid, identity_downcall_data::idd_groups, identity_downcall_data::idd_ngroups, identity_downcall_data::idd_nperms, identity_downcall_data::idd_perms, identity_downcall_data::idd_uid, perm_downcall_data::pdd_nid, and perm_downcall_data::pdd_perm.
Referenced by main().
static void usage (void) [static]
Definition at line 77 of file l_getidentity.c.
References progname.
Variable Documentation
perm_type_t noperm_types[] [static]
Initial value:
 {
        { "nosetuid", CFS_SETUID_PERM },
        { "nosetgid", CFS_SETGID_PERM },
        { "nosetgrp", CFS_SETGRP_PERM },
        { "normtacl", CFS_RMTACL_PERM },
        { "normtown", CFS_RMTOWN_PERM },
        { 0 }
}
Definition at line 211 of file l_getidentity.c.
perm_type_t perm_types[] [static]
Initial value:
 {
        { "setuid", CFS_SETUID_PERM },
        { "setgid", CFS_SETGID_PERM },
        { "setgrp", CFS_SETGRP_PERM },
        { "rmtacl", CFS_RMTACL_PERM },
        { "rmtown", CFS_RMTOWN_PERM },
        { 0 }
}
Definition at line 202 of file l_getidentity.c.
char* progname [static]
Definition at line 75 of file l_getidentity.c.
Referenced by add_param(), badopt(), calc_total_bytes(), check_lease(), check_mountfsoptions(), convert_hostnames(), dir_read(), dir_write(), display_usage(), errlog(), fatal(), file_create(), file_in_dev(), get_device_size(), in_mntlist(), is_block(), is_e2fsprogs_feature_supp(), is_feature_enabled(), ldiskfs_enable_quota(), ldiskfs_make_lustre(), ldiskfs_read_ldd(), ldiskfs_write_ldd(), lfs_migrate(), loop_format(), loop_setup(), main(), migrate_block(), migrate_copy_data(), migrate_nonblock(), open_dev(), open_file(), parse_ldd(), parse_opts(), read_chunks(), set_blockdev_scheduler(), set_blockdev_tunables(), sizeof_dev(), update_mtab_entry(), usage(), verify_chunk(), write_chunks(), and write_retry().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.