Lustre: lustre/ptlrpc/layout.c File Reference
lustre/ptlrpc/layout.c File Reference
#include <linux/module.h>
#include <lustre/lustre_idl.h>
#include <llog_swab.h>
#include <lustre_debug.h>
#include <lustre_swab.h>
#include <lustre_ver.h>
#include <obd.h>
#include <obd_support.h>
#include <lustre_req_layout.h>
#include <lustre_acl.h>
Data Structures
struct req_msg_field
struct req_format
Defines
#define DEBUG_SUBSYSTEM S_RPC
#define DEFINE_MSGF(name, flags, size, swabber, dumper)
#define DEFINE_REQ_FMT(name, client, client_nr, server, server_nr)
#define DEFINE_REQ_FMT0(name, client, server) DEFINE_REQ_FMT(name, client, ARRAY_SIZE(client), server, ARRAY_SIZE(server))
#define FMT_FIELD(fmt, i, j) (fmt)->rf_fields[(i)].d[(j)]
Enumerations
enum rmf_flags { RMF_F_STRING = 1 << 0, RMF_F_NO_SIZE_CHECK = 1 << 1, RMF_F_STRUCT_ARRAY = 1 << 2 }
Functions
int req_layout_init (void)
Initializes the capsule abstraction by computing and setting the rf_idx field of RQFs and the rmf_offset field of RMFs.
void req_layout_fini (void)
void req_capsule_init_area (struct req_capsule *pill)
Initializes the expected sizes of each RMF in a pill (rc_area) to -1.
void req_capsule_init (struct req_capsule *pill, struct ptlrpc_request *req, enum req_location location)
Initialize a pill.
void req_capsule_fini (struct req_capsule *pill)
static int __req_format_is_sane (const struct req_format *fmt)
static struct lustre_msg * __req_msg (const struct req_capsule *pill, enum req_location loc)
void req_capsule_set (struct req_capsule *pill, const struct req_format *fmt)
Set the format (fmt) of a pill; format changes are not allowed here (see req_capsule_extend()).
size_t req_capsule_filled_sizes (struct req_capsule *pill, enum req_location loc)
Fills in any parts of the rc_area of a pill that haven't been filled in yet.
int req_capsule_server_pack (struct req_capsule *pill)
Capsule equivalent of lustre_pack_request() and lustre_pack_reply().
static __u32 __req_capsule_offset (const struct req_capsule *pill, const struct req_msg_field *field, enum req_location loc)
Returns the PTLRPC request or reply (loc) buffer offset of a pill corresponding to the given RMF (field).
static void swabber_dumper_helper (struct req_capsule *pill, const struct req_msg_field *field, enum req_location loc, int offset, void *value, int len, int dump, void(*swabber)(void *))
Helper for __req_capsule_get(); swabs value / array of values and/or dumps them if desired.
static void * __req_capsule_get (struct req_capsule *pill, const struct req_msg_field *field, enum req_location loc, void(*swabber)(void *), int dump)
Returns the pointer to a PTLRPC request or reply (loc) buffer of a pill corresponding to the given RMF (field).
void __req_capsule_dump (struct req_capsule *pill, enum req_location loc)
Dump a request and/or reply.
void req_capsule_client_dump (struct req_capsule *pill)
Dump a request.
void req_capsule_server_dump (struct req_capsule *pill)
Dump a reply.
void * req_capsule_client_get (struct req_capsule *pill, const struct req_msg_field *field)
Trivial wrapper around __req_capsule_get(), that returns the PTLRPC request buffer corresponding to the given RMF (field) of a pill.
void * req_capsule_client_swab_get (struct req_capsule *pill, const struct req_msg_field *field, void *swabber)
Same as req_capsule_client_get(), but with a swabber argument.
void * req_capsule_client_sized_get (struct req_capsule *pill, const struct req_msg_field *field, __u32 len)
Utility that combines req_capsule_set_size() and req_capsule_client_get().
void * req_capsule_server_get (struct req_capsule *pill, const struct req_msg_field *field)
Trivial wrapper around __req_capsule_get(), that returns the PTLRPC reply buffer corresponding to the given RMF (field) of a pill.
void * req_capsule_server_swab_get (struct req_capsule *pill, const struct req_msg_field *field, void *swabber)
Same as req_capsule_server_get(), but with a swabber argument.
void * req_capsule_server_sized_get (struct req_capsule *pill, const struct req_msg_field *field, __u32 len)
Utility that combines req_capsule_set_size() and req_capsule_server_get().
void * req_capsule_server_sized_swab_get (struct req_capsule *pill, const struct req_msg_field *field, __u32 len, void *swabber)
const void * req_capsule_other_get (struct req_capsule *pill, const struct req_msg_field *field)
Returns the buffer of a pill corresponding to the given field from the request (if the caller is executing on the server-side) or reply (if the caller is executing on the client-side).
void req_capsule_set_size (struct req_capsule *pill, const struct req_msg_field *field, enum req_location loc, __u32 size)
Set the size of the PTLRPC request/reply (loc) buffer for the given field of the given pill.
__u32 req_capsule_get_size (const struct req_capsule *pill, const struct req_msg_field *field, enum req_location loc)
Return the actual PTLRPC buffer length of a request or reply (loc) for the given pill's given field.
__u32 req_capsule_msg_size (struct req_capsule *pill, enum req_location loc)
Wrapper around lustre_msg_size() that returns the PTLRPC size needed for the given pill's request or reply (loc) given the field size recorded in the pill's rc_area.
__u32 req_capsule_fmt_size (__u32 magic, const struct req_format *fmt, enum req_location loc)
While req_capsule_msg_size() computes the size of a PTLRPC request or reply (loc) given a pill's rc_area, this function computes the size of a PTLRPC request or reply given only an RQF (fmt).
void req_capsule_extend (struct req_capsule *pill, const struct req_format *fmt)
Changes the format of an RPC.
int req_capsule_has_field (const struct req_capsule *pill, const struct req_msg_field *field, enum req_location loc)
This function returns a non-zero value if the given field is present in the format (rc_fmt) of pill's PTLRPC request or reply (loc), else it returns 0.
int req_capsule_field_present (const struct req_capsule *pill, const struct req_msg_field *field, enum req_location loc)
Returns a non-zero value if the given field is present in the given pill's PTLRPC request or reply (loc), else it returns 0.
void req_capsule_shrink (struct req_capsule *pill, const struct req_msg_field *field, __u32 newlen, enum req_location loc)
This function shrinks the size of the _buffer_ of the pill's PTLRPC request or reply (loc).
int req_capsule_server_grow (struct req_capsule *pill, const struct req_msg_field *field, __u32 newlen)
Variables
static struct req_msg_field * empty []
static struct req_msg_field * mgs_target_info_only []
static struct req_msg_field * mgs_set_info []
static struct req_msg_field * mgs_config_read_client []
static struct req_msg_field * mgs_config_read_server []
static struct req_msg_field * log_cancel_client []
static struct req_msg_field * mdt_body_only []
static struct req_msg_field * mdt_body_capa []
static struct req_msg_field * quotactl_only []
static struct req_msg_field * quota_body_only []
static struct req_msg_field * ldlm_intent_quota_client []
static struct req_msg_field * ldlm_intent_quota_server []
static struct req_msg_field * mdt_close_client []
static struct req_msg_field * mdt_intent_close_client []
static struct req_msg_field * obd_statfs_server []
static struct req_msg_field * seq_query_client []
static struct req_msg_field * seq_query_server []
static struct req_msg_field * fld_query_client []
static struct req_msg_field * fld_query_server []
static struct req_msg_field * fld_read_client []
static struct req_msg_field * fld_read_server []
static struct req_msg_field * mds_getattr_name_client []
static struct req_msg_field * mds_reint_client []
static struct req_msg_field * mds_reint_create_client []
static struct req_msg_field * mds_reint_create_slave_client []
static struct req_msg_field * mds_reint_create_rmt_acl_client []
static struct req_msg_field * mds_reint_create_sym_client []
static struct req_msg_field * mds_reint_open_client []
static struct req_msg_field * mds_reint_open_server []
static struct req_msg_field * mds_reint_unlink_client []
static struct req_msg_field * mds_reint_link_client []
static struct req_msg_field * mds_reint_rename_client []
static struct req_msg_field * mds_reint_migrate_client []
static struct req_msg_field * mds_last_unlink_server []
static struct req_msg_field * mds_reint_setattr_client []
static struct req_msg_field * mds_reint_setxattr_client []
static struct req_msg_field * mdt_swap_layouts []
static struct req_msg_field * obd_connect_client []
static struct req_msg_field * obd_connect_server []
static struct req_msg_field * obd_set_info_client []
static struct req_msg_field * ost_grant_shrink_client []
static struct req_msg_field * mds_getinfo_client []
static struct req_msg_field * mds_getinfo_server []
static struct req_msg_field * ldlm_enqueue_client []
static struct req_msg_field * ldlm_enqueue_server []
static struct req_msg_field * ldlm_enqueue_lvb_server []
static struct req_msg_field * ldlm_cp_callback_client []
static struct req_msg_field * ldlm_gl_callback_desc_client []
static struct req_msg_field * ldlm_gl_callback_server []
static struct req_msg_field * ldlm_intent_basic_client []
static struct req_msg_field * ldlm_intent_client []
static struct req_msg_field * ldlm_intent_server []
static struct req_msg_field * ldlm_intent_layout_client []
static struct req_msg_field * ldlm_intent_open_server []
static struct req_msg_field * ldlm_intent_getattr_client []
static struct req_msg_field * ldlm_intent_getattr_server []
static struct req_msg_field * ldlm_intent_create_client []
static struct req_msg_field * ldlm_intent_open_client []
static struct req_msg_field * ldlm_intent_unlink_client []
static struct req_msg_field * ldlm_intent_getxattr_client []
static struct req_msg_field * ldlm_intent_getxattr_server []
static struct req_msg_field * mds_get_root_client []
static struct req_msg_field * mds_getxattr_client []
static struct req_msg_field * mds_getxattr_server []
static struct req_msg_field * mds_getattr_server []
static struct req_msg_field * mds_setattr_server []
static struct req_msg_field * mds_update_client []
static struct req_msg_field * mds_update_server []
static struct req_msg_field * llog_origin_handle_create_client []
static struct req_msg_field * llogd_body_only []
static struct req_msg_field * llog_log_hdr_only []
static struct req_msg_field * llogd_conn_body_only []
static struct req_msg_field * llog_origin_handle_next_block_server []
static struct req_msg_field * obd_idx_read_client []
static struct req_msg_field * obd_idx_read_server []
static struct req_msg_field * ost_body_only []
static struct req_msg_field * ost_body_capa []
static struct req_msg_field * ost_destroy_client []
static struct req_msg_field * ost_brw_client []
static struct req_msg_field * ost_brw_read_server []
static struct req_msg_field * ost_brw_write_server []
static struct req_msg_field * ost_get_info_generic_server []
static struct req_msg_field * ost_get_info_generic_client []
static struct req_msg_field * ost_get_last_id_server []
static struct req_msg_field * ost_get_last_fid_client []
static struct req_msg_field * ost_get_last_fid_server []
static struct req_msg_field * ost_get_fiemap_client []
static struct req_msg_field * ost_ladvise []
static struct req_msg_field * ost_get_fiemap_server []
static struct req_msg_field * mdt_hsm_progress []
static struct req_msg_field * mdt_hsm_ct_register []
static struct req_msg_field * mdt_hsm_ct_unregister []
static struct req_msg_field * mdt_hsm_action_server []
static struct req_msg_field * mdt_hsm_state_get_server []
static struct req_msg_field * mdt_hsm_state_set []
static struct req_msg_field * mdt_hsm_request []
static struct req_msg_field * obd_lfsck_request []
static struct req_msg_field * obd_lfsck_reply []
static struct req_format * req_formats []
struct req_msg_field RMF_GENERIC_DATA
struct req_msg_field RMF_MGS_TARGET_INFO
struct req_msg_field RMF_MGS_SEND_PARAM
struct req_msg_field RMF_MGS_CONFIG_BODY
struct req_msg_field RMF_MGS_CONFIG_RES
struct req_msg_field RMF_U32
struct req_msg_field RMF_SETINFO_VAL
struct req_msg_field RMF_GETINFO_KEY
struct req_msg_field RMF_GETINFO_VALLEN
struct req_msg_field RMF_GETINFO_VAL
struct req_msg_field RMF_SEQ_OPC
struct req_msg_field RMF_SEQ_RANGE
struct req_msg_field RMF_FLD_OPC
struct req_msg_field RMF_FLD_MDFLD
struct req_msg_field RMF_MDT_BODY
struct req_msg_field RMF_OBD_QUOTACTL
struct req_msg_field RMF_QUOTA_BODY
struct req_msg_field RMF_MDT_EPOCH
struct req_msg_field RMF_PTLRPC_BODY
struct req_msg_field RMF_CLOSE_DATA
struct req_msg_field RMF_OBD_STATFS
struct req_msg_field RMF_SETINFO_KEY
struct req_msg_field RMF_NAME
struct req_msg_field RMF_SYMTGT
struct req_msg_field RMF_TGTUUID
struct req_msg_field RMF_CLUUID
struct req_msg_field RMF_STRING
struct req_msg_field RMF_LLOGD_BODY
struct req_msg_field RMF_LLOG_LOG_HDR
struct req_msg_field RMF_LLOGD_CONN_BODY
struct req_msg_field RMF_CONN
struct req_msg_field RMF_CONNECT_DATA
struct req_msg_field RMF_DLM_REQ
struct req_msg_field RMF_DLM_REP
struct req_msg_field RMF_LDLM_INTENT
struct req_msg_field RMF_DLM_LVB
struct req_msg_field RMF_DLM_GL_DESC
struct req_msg_field RMF_MDT_MD
struct req_msg_field RMF_REC_REINT
struct req_msg_field RMF_EADATA
struct req_msg_field RMF_EAVALS = DEFINE_MSGF("eavals", 0, -1, NULL, NULL)
struct req_msg_field RMF_ACL
struct req_msg_field RMF_LOGCOOKIES
struct req_msg_field RMF_CAPA1
struct req_msg_field RMF_CAPA2
struct req_msg_field RMF_LAYOUT_INTENT
struct req_msg_field RMF_OST_BODY
struct req_msg_field RMF_OBD_IOOBJ
struct req_msg_field RMF_NIOBUF_REMOTE
struct req_msg_field RMF_RCS
struct req_msg_field RMF_EAVALS_LENS
struct req_msg_field RMF_OBD_ID
struct req_msg_field RMF_FID
struct req_msg_field RMF_OST_ID
struct req_msg_field RMF_FIEMAP_KEY
struct req_msg_field RMF_FIEMAP_VAL
struct req_msg_field RMF_IDX_INFO
struct req_msg_field RMF_HSM_USER_STATE
struct req_msg_field RMF_HSM_STATE_SET
struct req_msg_field RMF_MDS_HSM_PROGRESS
struct req_msg_field RMF_MDS_HSM_CURRENT_ACTION
struct req_msg_field RMF_MDS_HSM_USER_ITEM
struct req_msg_field RMF_MDS_HSM_ARCHIVE
struct req_msg_field RMF_MDS_HSM_REQUEST
struct req_msg_field RMF_OUT_UPDATE
struct req_msg_field RMF_OUT_UPDATE_REPLY
struct req_msg_field RMF_SWAP_LAYOUTS
struct req_msg_field RMF_LFSCK_REQUEST
struct req_msg_field RMF_LFSCK_REPLY
struct req_msg_field RMF_OST_LADVISE_HDR
struct req_msg_field RMF_OST_LADVISE
struct req_msg_field RMF_OUT_UPDATE_HEADER
struct req_msg_field RMF_OUT_UPDATE_BUF
struct req_format RQF_OBD_PING
struct req_format RQF_OBD_SET_INFO
struct req_format RQF_OBD_IDX_READ
struct req_format RQF_SEC_CTX
struct req_format RQF_MGS_TARGET_REG
struct req_format RQF_MGS_SET_INFO
struct req_format RQF_MGS_CONFIG_READ
struct req_format RQF_SEQ_QUERY
struct req_format RQF_FLD_QUERY
struct req_format RQF_FLD_READ
struct req_format RQF_LOG_CANCEL
struct req_format RQF_MDS_QUOTACTL
struct req_format RQF_OST_QUOTACTL
struct req_format RQF_QUOTA_DQACQ
struct req_format RQF_LDLM_INTENT_QUOTA
struct req_format RQF_MDS_GET_ROOT
struct req_format RQF_MDS_STATFS
struct req_format RQF_MDS_SYNC
struct req_format RQF_MDS_GETATTR
struct req_format RQF_MDS_GETXATTR
struct req_format RQF_MDS_GETATTR_NAME
struct req_format RQF_MDS_REINT
struct req_format RQF_MDS_REINT_CREATE
struct req_format RQF_MDS_REINT_CREATE_RMT_ACL
struct req_format RQF_MDS_REINT_CREATE_SLAVE
struct req_format RQF_MDS_REINT_CREATE_SYM
struct req_format RQF_MDS_REINT_OPEN
struct req_format RQF_MDS_REINT_UNLINK
struct req_format RQF_MDS_REINT_LINK
struct req_format RQF_MDS_REINT_RENAME
struct req_format RQF_MDS_REINT_MIGRATE
struct req_format RQF_MDS_REINT_SETATTR
struct req_format RQF_MDS_REINT_SETXATTR
struct req_format RQF_MDS_CONNECT
struct req_format RQF_MDS_DISCONNECT
struct req_format RQF_MDS_GET_INFO
struct req_format RQF_OUT_UPDATE
struct req_format RQF_LDLM_ENQUEUE
struct req_format RQF_LDLM_ENQUEUE_LVB
struct req_format RQF_LDLM_CONVERT
struct req_format RQF_LDLM_CANCEL
struct req_format RQF_LDLM_CALLBACK
struct req_format RQF_LDLM_CP_CALLBACK
struct req_format RQF_LDLM_BL_CALLBACK
struct req_format RQF_LDLM_GL_CALLBACK
struct req_format RQF_LDLM_GL_DESC_CALLBACK
struct req_format RQF_LDLM_INTENT_BASIC
struct req_format RQF_LDLM_INTENT
struct req_format RQF_LDLM_INTENT_LAYOUT
struct req_format RQF_LDLM_INTENT_GETATTR
struct req_format RQF_LDLM_INTENT_OPEN
struct req_format RQF_LDLM_INTENT_CREATE
struct req_format RQF_LDLM_INTENT_UNLINK
struct req_format RQF_LDLM_INTENT_GETXATTR
struct req_format RQF_MDS_CLOSE
struct req_format RQF_MDS_INTENT_CLOSE
struct req_format RQF_MDS_READPAGE
struct req_format RQF_MDS_HSM_ACTION
struct req_format RQF_MDS_HSM_PROGRESS
struct req_format RQF_MDS_HSM_CT_REGISTER
struct req_format RQF_MDS_HSM_CT_UNREGISTER
struct req_format RQF_MDS_HSM_STATE_GET
struct req_format RQF_MDS_HSM_STATE_SET
struct req_format RQF_MDS_HSM_REQUEST
struct req_format RQF_MDS_SWAP_LAYOUTS
struct req_format RQF_LLOG_ORIGIN_HANDLE_CREATE
struct req_format RQF_LLOG_ORIGIN_HANDLE_DESTROY
struct req_format RQF_LLOG_ORIGIN_HANDLE_NEXT_BLOCK
struct req_format RQF_LLOG_ORIGIN_HANDLE_PREV_BLOCK
struct req_format RQF_LLOG_ORIGIN_HANDLE_READ_HEADER
struct req_format RQF_LLOG_ORIGIN_CONNECT
struct req_format RQF_CONNECT
struct req_format RQF_OST_CONNECT
struct req_format RQF_OST_DISCONNECT
struct req_format RQF_OST_GETATTR
struct req_format RQF_OST_SETATTR
struct req_format RQF_OST_CREATE
struct req_format RQF_OST_PUNCH
struct req_format RQF_OST_SYNC
struct req_format RQF_OST_DESTROY
struct req_format RQF_OST_BRW_READ
struct req_format RQF_OST_BRW_WRITE
struct req_format RQF_OST_STATFS
struct req_format RQF_OST_SET_GRANT_INFO
struct req_format RQF_OST_GET_INFO
struct req_format RQF_OST_GET_INFO_LAST_ID
struct req_format RQF_OST_GET_INFO_LAST_FID
struct req_format RQF_OST_SET_INFO_LAST_FID
struct req_format RQF_OST_GET_INFO_FIEMAP
struct req_format RQF_LFSCK_NOTIFY
struct req_format RQF_LFSCK_QUERY
struct req_format RQF_OST_LADVISE
Define Documentation
#define DEBUG_SUBSYSTEM S_RPC
Definition at line 51 of file layout.c.
#define DEFINE_MSGF (name, flags, size, swabber, dumper)
Value:
{       \
        .rmf_name    = (name),                                  \
        .rmf_flags   = (flags),                                 \
        .rmf_size    = (size),                                  \
        .rmf_swabber = (void (*)(void*))(swabber),              \
        .rmf_dumper  = (void (*)(void*))(dumper)                \
}
Definition at line 857 of file layout.c.
#define DEFINE_REQ_FMT (name, client, client_nr, server, server_nr)
Value:
{    \
        .rf_name   = name,                                              \
        .rf_fields = {                                                  \
                [RCL_CLIENT] = {                                        \
                        .nr = client_nr,                                \
                        .d  = client                                    \
                },                                                      \
                [RCL_SERVER] = {                                        \
                        .nr = server_nr,                                \
                        .d  = server                                    \
                }                                                       \
        }                                                               \
}
Definition at line 1253 of file layout.c.
#define DEFINE_REQ_FMT0 (name, client, server) DEFINE_REQ_FMT(name, client, ARRAY_SIZE(client), server, ARRAY_SIZE(server))
Definition at line 1267 of file layout.c.
#define FMT_FIELD (fmt, i, j) (fmt)->rf_fields[(i)].d[(j)]
Definition at line 1695 of file layout.c.
Referenced by __req_capsule_dump(), and req_capsule_extend().
Enumeration Type Documentation
enum rmf_flags
Enumerator:
RMF_F_STRING
The field is a string, must be NUL-terminated.
RMF_F_NO_SIZE_CHECK
The field's buffer size need not match the declared rmf_size.
RMF_F_STRUCT_ARRAY
The field's buffer size must be a whole multiple of the declared rmf_size and the rmf_swabber function must work on the declared rmf_size worth of bytes.
Definition at line 835 of file layout.c.
Function Documentation
void __req_capsule_dump (struct req_capsule * pill, enum req_location loc)
Dump a request and/or reply.
Definition at line 2067 of file layout.c.
References __req_capsule_get(), CDEBUG, D_RPCTRACE, DEBUG_REQ, FMT_FIELD, req_format::nr, req_capsule::rc_fmt, req_capsule::rc_req, req_capsule_get_size(), req_format::rf_fields, req_msg_field::rmf_dumper, and req_msg_field::rmf_name.
Referenced by req_capsule_client_dump(), and req_capsule_server_dump().
static void* __req_capsule_get (struct req_capsule * pill, const struct req_msg_field * field, enum req_location loc, void(*)(void *) swabber, int dump) [static]
Returns the pointer to a PTLRPC request or reply (loc) buffer of a pill corresponding to the given RMF (field).
The buffer will be swabbed using the given swabber. If swabber == NULL then the rmf_swabber from the RMF will be used. Soon there will be no calls to __req_capsule_get() with a non-NULL swabber; swabber will then be removed. Fields with the RMF_F_STRUCT_ARRAY flag set will have each element of the array swabbed.
Definition at line 1995 of file layout.c.
References __req_capsule_offset(), __req_format_is_sane(), __req_msg(), CERROR, D_ERROR, DEBUG_REQ, LASSERT, lustre_msg, lustre_msg_buf(), lustre_msg_bufcount(), lustre_msg_buflen(), lustre_msg_string(), msg, req_capsule::rc_area, req_capsule::rc_fmt, req_capsule::rc_req, RCL_CLIENT, RCL_NR, RCL_SERVER, req_format::rf_name, RMF_F_NO_SIZE_CHECK, RMF_F_STRING, RMF_F_STRUCT_ARRAY, req_msg_field::rmf_flags, req_msg_field::rmf_name, req_msg_field::rmf_size, and swabber_dumper_helper().
Referenced by __req_capsule_dump(), req_capsule_client_get(), req_capsule_client_sized_get(), req_capsule_client_swab_get(), req_capsule_other_get(), req_capsule_server_get(), req_capsule_server_sized_get(), req_capsule_server_sized_swab_get(), and req_capsule_server_swab_get().
static __u32 __req_capsule_offset (const struct req_capsule * pill, const struct req_msg_field * field, enum req_location loc) [static]
Returns the PTLRPC request or reply (loc) buffer offset of a pill corresponding to the given RMF (field).
Definition at line 1894 of file layout.c.
References LASSERT, LASSERTF, req_capsule::rc_fmt, REQ_MAX_FIELD_NR, req_format::rf_idx, req_format::rf_name, req_msg_field::rmf_name, and req_msg_field::rmf_offset.
Referenced by __req_capsule_get(), req_capsule_field_present(), req_capsule_get_size(), req_capsule_server_grow(), req_capsule_set_size(), and req_capsule_shrink().
static int __req_format_is_sane (const struct req_format * fmt) [static]
Definition at line 1797 of file layout.c.
References ARRAY_SIZE, and req_format::rf_idx.
Referenced by __req_capsule_get(), req_capsule_extend(), req_capsule_server_grow(), req_capsule_set(), and req_capsule_shrink().
static struct lustre_msg* __req_msg (const struct req_capsule * pill, enum req_location loc) [static, read]
Definition at line 1803 of file layout.c.
References req_capsule::rc_req, RCL_CLIENT, ptlrpc_request::rq_repmsg, and ptlrpc_request::rq_reqmsg.
Referenced by __req_capsule_get(), req_capsule_field_present(), req_capsule_get_size(), and req_capsule_shrink().
static void swabber_dumper_helper (struct req_capsule * pill, const struct req_msg_field * field, enum req_location loc, int offset, void * value, int len, int dump, void(*)(void *) swabber) [static]
Helper for __req_capsule_get(); swabs value / array of values and/or dumps them if desired.
Definition at line 1916 of file layout.c.
References CDEBUG, D_RPCTRACE, LASSERT, ptlrpc_buf_need_swab(), ptlrpc_buf_set_swabbed(), req_capsule::rc_req, RCL_CLIENT, req_msg_field::rmf_dumper, RMF_F_STRUCT_ARRAY, req_msg_field::rmf_flags, req_msg_field::rmf_name, req_msg_field::rmf_size, and req_msg_field::rmf_swabber.
Referenced by __req_capsule_get().
Variable Documentation
struct req_msg_field* empty[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY
}
Definition at line 74 of file layout.c.
Referenced by cfs_hash_is_empty(), and lfsck_assistant_req_empty().
struct req_msg_field* fld_query_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_FLD_OPC,
        &RMF_FLD_MDFLD
}
Definition at line 169 of file layout.c.
struct req_msg_field* fld_query_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_FLD_MDFLD
}
Definition at line 175 of file layout.c.
struct req_msg_field* fld_read_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_FLD_MDFLD
}
Definition at line 180 of file layout.c.
struct req_msg_field* fld_read_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_GENERIC_DATA
}
Definition at line 185 of file layout.c.
struct req_msg_field* ldlm_cp_callback_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_DLM_REQ,
        &RMF_DLM_LVB
}
Definition at line 382 of file layout.c.
struct req_msg_field* ldlm_enqueue_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_DLM_REQ
}
Definition at line 366 of file layout.c.
struct req_msg_field* ldlm_enqueue_lvb_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_DLM_REP,
        &RMF_DLM_LVB
}
Definition at line 376 of file layout.c.
struct req_msg_field* ldlm_enqueue_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_DLM_REP
}
Definition at line 371 of file layout.c.
struct req_msg_field* ldlm_gl_callback_desc_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_DLM_REQ,
        &RMF_DLM_GL_DESC
}
Definition at line 388 of file layout.c.
struct req_msg_field* ldlm_gl_callback_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_DLM_LVB
}
Definition at line 394 of file layout.c.
struct req_msg_field* ldlm_intent_basic_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_DLM_REQ,
        &RMF_LDLM_INTENT,
}
Definition at line 399 of file layout.c.
struct req_msg_field* ldlm_intent_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_DLM_REQ,
        &RMF_LDLM_INTENT,
        &RMF_REC_REINT
}
Definition at line 405 of file layout.c.
struct req_msg_field* ldlm_intent_create_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_DLM_REQ,
        &RMF_LDLM_INTENT,
        &RMF_REC_REINT,
        &RMF_CAPA1,
        &RMF_NAME,
        &RMF_EADATA
}
Definition at line 455 of file layout.c.
struct req_msg_field* ldlm_intent_getattr_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_DLM_REQ,
        &RMF_LDLM_INTENT,
        &RMF_MDT_BODY,
        &RMF_CAPA1,
        &RMF_NAME
}
Definition at line 437 of file layout.c.
struct req_msg_field* ldlm_intent_getattr_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_DLM_REP,
        &RMF_MDT_BODY,
        &RMF_MDT_MD,
        &RMF_ACL,
        &RMF_CAPA1
}
Definition at line 446 of file layout.c.
struct req_msg_field* ldlm_intent_getxattr_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_DLM_REQ,
        &RMF_LDLM_INTENT,
        &RMF_MDT_BODY,
        &RMF_CAPA1,
}
Definition at line 485 of file layout.c.
struct req_msg_field* ldlm_intent_getxattr_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_DLM_REP,
        &RMF_MDT_BODY,
        &RMF_MDT_MD,
        &RMF_ACL,
        &RMF_EADATA,
        &RMF_EAVALS,
        &RMF_EAVALS_LENS
}
Definition at line 493 of file layout.c.
struct req_msg_field* ldlm_intent_layout_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_DLM_REQ,
        &RMF_LDLM_INTENT,
        &RMF_LAYOUT_INTENT,
        &RMF_EADATA
}
Definition at line 420 of file layout.c.
struct req_msg_field* ldlm_intent_open_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_DLM_REQ,
        &RMF_LDLM_INTENT,
        &RMF_REC_REINT,
        &RMF_CAPA1,
        &RMF_CAPA2,
        &RMF_NAME,
        &RMF_EADATA
}
Definition at line 465 of file layout.c.
struct req_msg_field* ldlm_intent_open_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_DLM_REP,
        &RMF_MDT_BODY,
        &RMF_MDT_MD,
        &RMF_ACL,
        &RMF_CAPA1,
        &RMF_CAPA2
}
Definition at line 427 of file layout.c.
struct req_msg_field* ldlm_intent_quota_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_DLM_REQ,
        &RMF_LDLM_INTENT,
        &RMF_QUOTA_BODY
}
Definition at line 124 of file layout.c.
struct req_msg_field* ldlm_intent_quota_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_DLM_REP,
        &RMF_DLM_LVB,
        &RMF_QUOTA_BODY
}
Definition at line 131 of file layout.c.
struct req_msg_field* ldlm_intent_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_DLM_REP,
        &RMF_MDT_BODY,
        &RMF_MDT_MD,
        &RMF_ACL
}
Definition at line 412 of file layout.c.
struct req_msg_field* ldlm_intent_unlink_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_DLM_REQ,
        &RMF_LDLM_INTENT,
        &RMF_REC_REINT,
        &RMF_CAPA1,
        &RMF_NAME
}
Definition at line 476 of file layout.c.
struct req_msg_field* llog_log_hdr_only[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_LLOG_LOG_HDR
}
Definition at line 564 of file layout.c.
struct req_msg_field* llog_origin_handle_create_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_LLOGD_BODY,
        &RMF_NAME
}
Definition at line 553 of file layout.c.
struct req_msg_field* llog_origin_handle_next_block_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_LLOGD_BODY,
        &RMF_EADATA
}
Definition at line 574 of file layout.c.
struct req_msg_field* llogd_body_only[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_LLOGD_BODY
}
Definition at line 559 of file layout.c.
struct req_msg_field* llogd_conn_body_only[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_LLOGD_CONN_BODY
}
Definition at line 569 of file layout.c.
struct req_msg_field* log_cancel_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_LOGCOOKIES
}
Definition at line 98 of file layout.c.
struct req_msg_field* mds_get_root_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_MDT_BODY,
        &RMF_NAME
}
Definition at line 504 of file layout.c.
struct req_msg_field* mds_getattr_name_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_MDT_BODY,
        &RMF_CAPA1,
        &RMF_NAME
}
Definition at line 190 of file layout.c.
struct req_msg_field* mds_getattr_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_MDT_BODY,
        &RMF_MDT_MD,
        &RMF_ACL,
        &RMF_CAPA1,
        &RMF_CAPA2
}
Definition at line 524 of file layout.c.
struct req_msg_field* mds_getinfo_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_GETINFO_KEY,
        &RMF_GETINFO_VALLEN
}
Definition at line 355 of file layout.c.
struct req_msg_field* mds_getinfo_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_GETINFO_VAL,
}
Definition at line 361 of file layout.c.
struct req_msg_field* mds_getxattr_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_MDT_BODY,
        &RMF_CAPA1,
        &RMF_NAME,
        &RMF_EADATA
}
Definition at line 510 of file layout.c.
struct req_msg_field* mds_getxattr_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_MDT_BODY,
        &RMF_EADATA
}
Definition at line 518 of file layout.c.
struct req_msg_field* mds_last_unlink_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_MDT_BODY,
        &RMF_MDT_MD,
        &RMF_LOGCOOKIES,
        &RMF_CAPA1,
        &RMF_CAPA2
}
Definition at line 293 of file layout.c.
struct req_msg_field* mds_reint_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_REC_REINT
}
Definition at line 197 of file layout.c.
struct req_msg_field* mds_reint_create_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_REC_REINT,
        &RMF_CAPA1,
        &RMF_NAME
}
Definition at line 202 of file layout.c.
struct req_msg_field* mds_reint_create_rmt_acl_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_REC_REINT,
        &RMF_CAPA1,
        &RMF_NAME,
        &RMF_EADATA,
        &RMF_DLM_REQ
}
Definition at line 218 of file layout.c.
struct req_msg_field* mds_reint_create_slave_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_REC_REINT,
        &RMF_CAPA1,
        &RMF_NAME,
        &RMF_EADATA,
        &RMF_DLM_REQ
}
Definition at line 209 of file layout.c.
struct req_msg_field* mds_reint_create_sym_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_REC_REINT,
        &RMF_CAPA1,
        &RMF_NAME,
        &RMF_SYMTGT,
        &RMF_DLM_REQ
}
Definition at line 227 of file layout.c.
struct req_msg_field* mds_reint_link_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_REC_REINT,
        &RMF_CAPA1,
        &RMF_CAPA2,
        &RMF_NAME,
        &RMF_DLM_REQ
}
Definition at line 262 of file layout.c.
struct req_msg_field* mds_reint_migrate_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_REC_REINT,
        &RMF_CAPA1,
        &RMF_CAPA2,
        &RMF_NAME,
        &RMF_SYMTGT,
        &RMF_DLM_REQ,
        &RMF_MDT_EPOCH,
        &RMF_CLOSE_DATA
}
Definition at line 281 of file layout.c.
struct req_msg_field* mds_reint_open_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_REC_REINT,
        &RMF_CAPA1,
        &RMF_CAPA2,
        &RMF_NAME,
        &RMF_EADATA
}
Definition at line 236 of file layout.c.
struct req_msg_field* mds_reint_open_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_MDT_BODY,
        &RMF_MDT_MD,
        &RMF_ACL,
        &RMF_CAPA1,
        &RMF_CAPA2
}
Definition at line 245 of file layout.c.
struct req_msg_field* mds_reint_rename_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_REC_REINT,
        &RMF_CAPA1,
        &RMF_CAPA2,
        &RMF_NAME,
        &RMF_SYMTGT,
        &RMF_DLM_REQ
}
Definition at line 271 of file layout.c.
struct req_msg_field* mds_reint_setattr_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_REC_REINT,
        &RMF_CAPA1,
        &RMF_MDT_EPOCH,
        &RMF_EADATA,
        &RMF_LOGCOOKIES,
        &RMF_DLM_REQ
}
Definition at line 302 of file layout.c.
struct req_msg_field* mds_reint_setxattr_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_REC_REINT,
        &RMF_CAPA1,
        &RMF_NAME,
        &RMF_EADATA,
        &RMF_DLM_REQ
}
Definition at line 312 of file layout.c.
struct req_msg_field* mds_reint_unlink_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_REC_REINT,
        &RMF_CAPA1,
        &RMF_NAME,
        &RMF_DLM_REQ
}
Definition at line 254 of file layout.c.
struct req_msg_field* mds_setattr_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_MDT_BODY,
        &RMF_MDT_MD,
        &RMF_ACL,
        &RMF_CAPA1,
        &RMF_CAPA2
}
Definition at line 533 of file layout.c.
struct req_msg_field* mds_update_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_OUT_UPDATE_HEADER,
        &RMF_OUT_UPDATE_BUF,
}
Definition at line 542 of file layout.c.
struct req_msg_field* mds_update_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_OUT_UPDATE_REPLY,
}
Definition at line 548 of file layout.c.
struct req_msg_field* mdt_body_capa[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_MDT_BODY,
        &RMF_CAPA1
}
Definition at line 108 of file layout.c.
struct req_msg_field* mdt_body_only[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_MDT_BODY
}
Definition at line 103 of file layout.c.
struct req_msg_field* mdt_close_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_MDT_EPOCH,
        &RMF_REC_REINT,
        &RMF_CAPA1
}
Definition at line 138 of file layout.c.
struct req_msg_field* mdt_hsm_action_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_MDT_BODY,
        &RMF_MDS_HSM_CURRENT_ACTION,
}
Definition at line 689 of file layout.c.
struct req_msg_field* mdt_hsm_ct_register[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_MDT_BODY,
        &RMF_MDS_HSM_ARCHIVE,
}
Definition at line 678 of file layout.c.
struct req_msg_field* mdt_hsm_ct_unregister[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_MDT_BODY,
}
Definition at line 684 of file layout.c.
struct req_msg_field* mdt_hsm_progress[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_MDT_BODY,
        &RMF_MDS_HSM_PROGRESS,
}
Definition at line 672 of file layout.c.
struct req_msg_field* mdt_hsm_request[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_MDT_BODY,
        &RMF_MDS_HSM_REQUEST,
        &RMF_MDS_HSM_USER_ITEM,
        &RMF_GENERIC_DATA,
}
Definition at line 708 of file layout.c.
struct req_msg_field* mdt_hsm_state_get_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_MDT_BODY,
        &RMF_HSM_USER_STATE,
}
Definition at line 695 of file layout.c.
struct req_msg_field* mdt_hsm_state_set[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_MDT_BODY,
        &RMF_CAPA1,
        &RMF_HSM_STATE_SET,
}
Definition at line 701 of file layout.c.
struct req_msg_field* mdt_intent_close_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_MDT_EPOCH,
        &RMF_REC_REINT,
        &RMF_CAPA1,
        &RMF_CLOSE_DATA
}
Definition at line 145 of file layout.c.
struct req_msg_field* mdt_swap_layouts[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_MDT_BODY,
        &RMF_SWAP_LAYOUTS,
        &RMF_CAPA1,
        &RMF_CAPA2,
        &RMF_DLM_REQ
}
Definition at line 321 of file layout.c.
struct req_msg_field* mgs_config_read_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_MGS_CONFIG_BODY
}
Definition at line 88 of file layout.c.
struct req_msg_field* mgs_config_read_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_MGS_CONFIG_RES
}
Definition at line 93 of file layout.c.
struct req_msg_field* mgs_set_info[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_MGS_SEND_PARAM
}
Definition at line 83 of file layout.c.
struct req_msg_field* mgs_target_info_only[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_MGS_TARGET_INFO
}
Definition at line 78 of file layout.c.
struct req_msg_field* obd_connect_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_TGTUUID,
        &RMF_CLUUID,
        &RMF_CONN,
        &RMF_CONNECT_DATA
}
Definition at line 330 of file layout.c.
struct req_msg_field* obd_connect_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_CONNECT_DATA
}
Definition at line 338 of file layout.c.
struct req_msg_field* obd_idx_read_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_IDX_INFO
}
Definition at line 580 of file layout.c.
struct req_msg_field* obd_idx_read_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_IDX_INFO
}
Definition at line 585 of file layout.c.
struct req_msg_field* obd_lfsck_reply[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_LFSCK_REPLY,
}
Definition at line 721 of file layout.c.
struct req_msg_field* obd_lfsck_request[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_LFSCK_REQUEST,
}
Definition at line 716 of file layout.c.
struct req_msg_field* obd_set_info_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_SETINFO_KEY,
        &RMF_SETINFO_VAL
}
Definition at line 343 of file layout.c.
struct req_msg_field* obd_statfs_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_OBD_STATFS
}
Definition at line 153 of file layout.c.
struct req_msg_field* ost_body_capa[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_OST_BODY,
        &RMF_CAPA1
}
Definition at line 595 of file layout.c.
struct req_msg_field* ost_body_only[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_OST_BODY
}
Definition at line 590 of file layout.c.
struct req_msg_field* ost_brw_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_OST_BODY,
        &RMF_OBD_IOOBJ,
        &RMF_NIOBUF_REMOTE,
        &RMF_CAPA1
}
Definition at line 609 of file layout.c.
struct req_msg_field* ost_brw_read_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_OST_BODY
}
Definition at line 617 of file layout.c.
struct req_msg_field* ost_brw_write_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_OST_BODY,
        &RMF_RCS
}
Definition at line 622 of file layout.c.
struct req_msg_field* ost_destroy_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_OST_BODY,
        &RMF_DLM_REQ,
        &RMF_CAPA1
}
Definition at line 601 of file layout.c.
struct req_msg_field* ost_get_fiemap_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_FIEMAP_KEY,
        &RMF_FIEMAP_VAL
}
Definition at line 654 of file layout.c.
struct req_msg_field* ost_get_fiemap_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_FIEMAP_VAL
}
Definition at line 667 of file layout.c.
struct req_msg_field* ost_get_info_generic_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_GETINFO_KEY
}
Definition at line 633 of file layout.c.
struct req_msg_field* ost_get_info_generic_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_GENERIC_DATA,
}
Definition at line 628 of file layout.c.
struct req_msg_field* ost_get_last_fid_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_GETINFO_KEY,
        &RMF_FID,
}
Definition at line 643 of file layout.c.
struct req_msg_field* ost_get_last_fid_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_FID,
}
Definition at line 649 of file layout.c.
struct req_msg_field* ost_get_last_id_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_OBD_ID
}
Definition at line 638 of file layout.c.
struct req_msg_field* ost_grant_shrink_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_SETINFO_KEY,
        &RMF_OST_BODY
}
Definition at line 349 of file layout.c.
struct req_msg_field* ost_ladvise[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_OST_BODY,
        &RMF_OST_LADVISE_HDR,
        &RMF_OST_LADVISE,
}
Definition at line 660 of file layout.c.
struct req_msg_field* quota_body_only[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_QUOTA_BODY
}
Definition at line 119 of file layout.c.
struct req_msg_field* quotactl_only[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_OBD_QUOTACTL
}
Definition at line 114 of file layout.c.
struct req_format* req_formats[] [static]
Definition at line 726 of file layout.c.
Referenced by print_layouts().
struct req_msg_field* seq_query_client[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_SEQ_OPC,
        &RMF_SEQ_RANGE
}
Definition at line 158 of file layout.c.
struct req_msg_field* seq_query_server[] [static]
Initial value:
 {
        &RMF_PTLRPC_BODY,
        &RMF_SEQ_RANGE
}
Definition at line 164 of file layout.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.