Lustre: lustre/llite/lcommon_misc.c File Reference
lustre/llite/lcommon_misc.c File Reference
#include <obd_class.h>
#include <obd_support.h>
#include <obd.h>
#include <cl_object.h>
#include "llite_internal.h"
Defines
#define GROUPLOCK_SCOPE "grouplock"
Functions
static int cl_init_ea_size (struct obd_export *md_exp, struct obd_export *dt_exp)
int cl_ocd_update (struct obd_device *host, struct obd_device *watched, enum obd_notify_event ev, void *owner, void *data)
This function is used as an upcall-callback hooked by liblustre and llite clients into obd_notify() listeners chain to handle notifications about change of import connect_flags.
int cl_get_grouplock (struct cl_object *obj, unsigned long gid, int nonblock, struct ll_grouplock *lg)
void cl_put_grouplock (struct ll_grouplock *lg)
Define Documentation
#define GROUPLOCK_SCOPE "grouplock"
Definition at line 122 of file lcommon_misc.c.
Function Documentation
int cl_get_grouplock (struct cl_object * obj, unsigned long gid, int nonblock, struct ll_grouplock * lg)
Definition at line 124 of file lcommon_misc.c.
References CEF_MUST, CEF_NONBLOCK, cl_io::ci_ignore_layout, cl_io::ci_obj, CIT_MISC, cl_env_get(), cl_env_put(), cl_env_unplant(), cl_io_fini(), cl_io_init(), cl_lock_request(), CL_PAGE_EOF, cl_lock_descr::cld_end, cl_lock_descr::cld_enq_flags, cl_lock_descr::cld_gid, cl_lock_descr::cld_mode, cl_lock_descr::cld_obj, cl_lock_descr::cld_start, cl_lock::cll_descr, CLM_GROUP, LASSERT, ll_grouplock::lg_env, ll_grouplock::lg_gid, ll_grouplock::lg_io, ll_grouplock::lg_lock, vvp_env_lock(), and vvp_env_thread_io().
Referenced by ll_get_grouplock().
static int cl_init_ea_size (struct obd_export * md_exp, struct obd_export * dt_exp) [static]
Definition at line 51 of file lcommon_misc.c.
References CDEBUG, D_HA, ENTRY, KEY_DEFAULT_EASIZE, KEY_MAX_EASIZE, md_init_ea_size(), obd_get_info(), and RETURN.
Referenced by cl_ocd_update().
int cl_ocd_update (struct obd_device * host, struct obd_device * watched, enum obd_notify_event ev, void * owner, void * data)
This function is used as an upcall-callback hooked by liblustre and llite clients into obd_notify() listeners chain to handle notifications about change of import connect_flags.
See llu_fsswop_mount() and lustre_common_fill_super().
Definition at line 86 of file lcommon_misc.c.
References __u64, CDEBUG, CERROR, client_obd::cl_import, cl_init_ea_size(), obd_device::cli, D_SUPER, ENTRY, obd_import::imp_connect_data, lustre_client_ocd::lco_dt_exp, lustre_client_ocd::lco_flags, lustre_client_ocd::lco_lock, lustre_client_ocd::lco_md_exp, LPX64, LUSTRE_OSC_NAME, obd_device::obd_name, obd_device::obd_set_up, obd_device::obd_stopping, obd_device::obd_type, obd_connect_data::ocd_connect_flags, RETURN, obd_type::typ_name, and obd_device::u.
Referenced by client_common_fill_super().
void cl_put_grouplock (struct ll_grouplock * lg)
Definition at line 181 of file lcommon_misc.c.
References cl_env_implant(), cl_env_put(), cl_io_fini(), cl_lock_release(), LASSERT, ll_grouplock::lg_env, ll_grouplock::lg_gid, ll_grouplock::lg_io, and ll_grouplock::lg_lock.
Referenced by ll_get_grouplock(), and ll_put_grouplock().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.