Lustre: lustre/llite/lcommon_cl.c File Reference
lustre/llite/lcommon_cl.c File Reference
#include <libcfs/libcfs.h>
#include <linux/fs.h>
#include <linux/sched.h>
#include <linux/mm.h>
#include <linux/quotaops.h>
#include <linux/highmem.h>
#include <linux/pagemap.h>
#include <linux/rbtree.h>
#include <obd.h>
#include <obd_support.h>
#include <lustre_fid.h>
#include <lustre_dlm.h>
#include <lustre_ver.h>
#include <lustre_mdc.h>
#include <cl_object.h>
#include "llite_internal.h"
#include "vvp_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LLITE
Functions
static DEFINE_MUTEX (cl_inode_fini_guard)
A mutex serializing calls to slp_inode_fini() under extreme memory pressure, when environments cannot be allocated.
int cl_setattr_ost (struct cl_object *obj, const struct iattr *attr, unsigned int attr_flags)
int cl_file_inode_init (struct inode *inode, struct lustre_md *md)
Initialize or update CLIO structures for regular files when new meta-data arrives from the server.
static void cl_object_put_last (struct lu_env *env, struct cl_object *obj)
Wait for others drop their references of the object at first, then we drop the last one, which will lead to the object be destroyed immediately.
void cl_inode_fini (struct inode *inode)
__u64 cl_fid_build_ino (const struct lu_fid *fid, int api32)
build inode number from passed
__u32 cl_fid_build_gen (const struct lu_fid *fid)
build inode generation from passed .
Variables
struct lu_env * cl_inode_fini_env
An `emergency' environment used by cl_inode_fini() when cl_env_get() fails.
__u16 cl_inode_fini_refcheck
Define Documentation
#define DEBUG_SUBSYSTEM S_LLITE
Definition at line 39 of file lcommon_cl.c.
Function Documentation
__u32 cl_fid_build_gen (const struct lu_fid * fid)
build inode generation from passed .
If our FID overflows the 32-bit inode number then return a non-zero generation to distinguish them.
Definition at line 280 of file lcommon_cl.c.
References ENTRY, fid_flatten(), fid_is_igif(), lu_igif_gen(), and RETURN.
Referenced by ll_update_inode().
__u64 cl_fid_build_ino (const struct lu_fid * fid, int api32)
build inode number from passed
Definition at line 269 of file lcommon_cl.c.
References fid_flatten(), fid_flatten32(), and RETURN.
Referenced by client_common_fill_super(), ll_dir_read(), ll_getattr(), ll_iget_anon_dir(), ll_md_blocking_ast(), ll_prep_inode(), ll_update_inode(), and search_inode_for_lustre().
int cl_file_inode_init (struct inode * inode, struct lustre_md * md)
Initialize or update CLIO structures for regular files when new meta-data arrives from the server.
Parameters:
inode regular file inode
md new file metadata from MDS
allocates cl_object if necessary,
updated layout, if object was already here.
Definition at line 131 of file lcommon_cl.c.
References lustre_md::body, CERROR, cl_conf_set(), cl_env_get(), cl_env_put(), cl_object_find(), cl_object::co_lu, cl_object_conf::coc_inode, cl_object_conf::coc_lu, DFID, fid_is_sane(), LASSERT, lustre_md::layout, ll_i2info(), ll_i2sbi(), ll_sb_info::ll_site, ll_inode_info::lli_clob, ll_inode_info::lli_fid, LOC_F_NEW, lu_object_conf::loc_flags, lu_site::ls_top_dev, lu2cl_dev(), lu_object_ref_add(), mdt_body::mbo_valid, OBD_MD_FLID, and PFID.
Referenced by ll_iget(), and ll_update_inode().
void cl_inode_fini (struct inode * inode)
Definition at line 226 of file lcommon_cl.c.
References cl_env_get(), cl_env_implant(), cl_env_put(), cl_env_reenter(), cl_env_reexit(), cl_env_unplant(), cl_object_kill(), cl_object_put_last(), cl_object::co_lu, LASSERT, ll_i2info(), ll_inode_info::lli_clob, and lu_object_ref_del().
Referenced by ll_clear_inode().
static void cl_object_put_last (struct lu_env * env, struct cl_object * obj) [static]
Wait for others drop their references of the object at first, then we drop the last one, which will lead to the object be destroyed immediately.
Must be called after cl_object_kill() against this object.
The reason we want to do this is: destroying top object will wait for sub objects being destroyed first, so we can't let bottom layer (e.g. from ASTs) to initiate top object destroying which may deadlock. See bz22520.
Definition at line 198 of file lcommon_cl.c.
References cl_object_put(), cl_object::co_lu, header, lu_device::ld_site, lu_object::lo_dev, lu_object::lo_header, lu_object_header::loh_fid, lu_object_header::loh_ref, lu_site_bkt_data::lsb_marche_funebre, lu_site_bkt_from_fid(), and unlikely.
Referenced by cl_inode_fini().
int cl_setattr_ost (struct cl_object * obj, const struct iattr * attr, unsigned int attr_flags)
Definition at line 75 of file lcommon_cl.c.
References cl_io::ci_need_restart, cl_io::ci_obj, cl_io::ci_result, cl_io::ci_setattr, cl_io::ci_verify_layout, CIT_SETATTR, cl_env_get(), cl_env_put(), cl_io_fini(), cl_io_init(), cl_io_loop(), cl_object::co_lu, ENTRY, LTIME_S, lu_object_fid(), LUSTRE_FPRIVATE, RETURN, cl_io::u, unlikely, vvp_io::vui_fd, vvp_env_io(), and vvp_env_thread_io().
Referenced by ll_iocontrol(), and ll_setattr_raw().
static DEFINE_MUTEX (cl_inode_fini_guard) [static]
A mutex serializing calls to slp_inode_fini() under extreme memory pressure, when environments cannot be allocated.
Referenced by enc_pools_add_pages(), and sptlrpc_wireflavor2policy().
Variable Documentation
struct lu_env* cl_inode_fini_env
An `emergency' environment used by cl_inode_fini() when cl_env_get() fails.
Access to this environment is serialized by cl_inode_fini_guard mutex.
Definition at line 66 of file lcommon_cl.c.
Referenced by lustre_exit(), and lustre_init().
__u16 cl_inode_fini_refcheck
Definition at line 67 of file lcommon_cl.c.
Referenced by lustre_exit(), and lustre_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.