Lustre: lustre/utils/lctl.c File Reference
lustre/utils/lctl.c File Reference
#include <errno.h>
#include <limits.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <libcfs/util/parser.h>
#include <lnet/lnetctl.h>
#include "obdctl.h"
#include <lustre/lustre_idl.h>
Functions
static int jt_noop (int argc, char **argv)
static int jt_opt_ignore_errors (int argc, char **argv)
int lctl_main (int argc, char **argv)
int main (int argc, char **argv)
Variables
command_t cmdlist []
Function Documentation
static int jt_noop (int argc, char ** argv) [static]
Definition at line 53 of file lctl.c.
static int jt_opt_ignore_errors (int argc, char ** argv) [static]
Definition at line 57 of file lctl.c.
References Parser_ignore_errors().
int lctl_main (int argc, char ** argv)
Definition at line 487 of file lctl.c.
References dbg_initialize(), obd_finalize(), obd_initialize(), Parser_commands(), Parser_execarg(), Parser_init(), and ptl_initialize().
Referenced by main().
int main (int argc, char ** argv)
Definition at line 512 of file lctl.c.
References lctl_main().
Variable Documentation
command_t cmdlist[]
Definition at line 62 of file lctl.c.
Referenced by lloop_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.