Lustre: lustre/ldlm/ldlm_lib.c File Reference
lustre/ldlm/ldlm_lib.c File Reference
#include <linux/kthread.h>
#include <libcfs/libcfs.h>
#include <obd.h>
#include <obd_class.h>
#include <lustre_dlm.h>
#include <lustre_net.h>
#include <lustre_sec.h>
#include "ldlm_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LDLM
This file deals with various client/target related logic including recovery.
Functions
static int import_set_conn (struct obd_import *imp, struct obd_uuid *uuid, int priority, int create)
int import_set_conn_priority (struct obd_import *imp, struct obd_uuid *uuid)
int client_import_add_conn (struct obd_import *imp, struct obd_uuid *uuid, int priority)
int client_import_del_conn (struct obd_import *imp, struct obd_uuid *uuid)
int client_import_find_conn (struct obd_import *imp, lnet_nid_t peer, struct obd_uuid *uuid)
Find conn UUID by peer NID.
void client_destroy_import (struct obd_import *imp)
static int osc_on_mdt (char *obdname)
Check whether or not the OSC is on MDT.
int client_obd_setup (struct obd_device *obddev, struct lustre_cfg *lcfg)
Target client logic.
int client_obd_cleanup (struct obd_device *obddev)
int client_connect_import (const struct lu_env *env, struct obd_export **exp, struct obd_device *obd, struct obd_uuid *cluuid, struct obd_connect_data *data, void *localdata)
int client_disconnect_export (struct obd_export *exp)
int target_pack_pool_reply (struct ptlrpc_request *req)
Packs current SLV and Limit into req.
static int target_send_reply_msg (struct ptlrpc_request *req, int rc, int fail_id)
void target_send_reply (struct ptlrpc_request *req, int rc, int fail_id)
int ldlm_error2errno (enum ldlm_error error)
Rather arbitrary mapping from LDLM error codes to errno values.
enum ldlm_error ldlm_errno2error (int err_no)
Dual to ldlm_error2errno(): maps errno values back to enum ldlm_error.
Variables
enum ldlm_mode lck_compat_array []
Define Documentation
#define DEBUG_SUBSYSTEM S_LDLM
This file deals with various client/target related logic including recovery.
TODO: This code more logically belongs in the ptlrpc module than in ldlm and should be moved.
Definition at line 44 of file ldlm_lib.c.
Function Documentation
static int import_set_conn (struct obd_import * imp, struct obd_uuid * uuid, int priority, int create) [static]
Definition at line 58 of file ldlm_lib.c.
References CDEBUG, D_HA, ENTRY, GOTO, obd_import::imp_conn_list, obd_import::imp_lock, obd_import::imp_obd, list_add(), list_add_tail(), list_del(), list_for_each_entry, OBD_ALLOC, OBD_FREE, obd_device::obd_name, obd_uuid_equals(), obd_import_conn::oic_conn, obd_import_conn::oic_item, obd_import_conn::oic_last_attempt, obd_import_conn::oic_uuid, ptlrpc_connection_put(), ptlrpc_uuid_to_connection(), RETURN, and obd_uuid::uuid.
Referenced by client_import_add_conn(), and import_set_conn_priority().
static int osc_on_mdt (char * obdname) [static]
Check whether or not the OSC is on MDT.
In the config log, osc on MDT setup 0:{fsname}-OSTxxxx-osc[-MDTxxxx] 1:lustre-OST0000_UUID 2:NID osc on client setup 0:{fsname}-OSTxxxx-osc 1:lustre-OST0000_UUID 2:NID
Definition at line 240 of file ldlm_lib.c.
Referenced by client_obd_setup().
static int target_send_reply_msg (struct ptlrpc_request * req, int rc, int fail_id) [static]
Definition at line 2835 of file ldlm_lib.c.
References D_ERROR, D_NET, DEBUG_REQ, lustre_msg_get_opc(), MDS_REINT, OBD_FAIL_CHECK, OBD_FAIL_CHECK_ORSET, OBD_FAIL_MDS_REINT_MULTI_NET_REP, OBD_FAIL_ONCE, PTLRPC_REPLY_MAYBE_DIFFICULT, ptlrpc_send_error(), ptlrpc_send_reply(), ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_status, and unlikely.
Referenced by target_send_reply().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.