Lustre: lustre/ldlm/ldlm_request.c File Reference
lustre/ldlm/ldlm_request.c File Reference
#include <lustre_dlm.h>
#include <obd_class.h>
#include <obd.h>
#include "ldlm_internal.h"
Data Structures
struct lock_wait_data
struct ldlm_async_args
struct ldlm_cli_cancel_arg
struct iter_helper_data
Defines
#define DEBUG_SUBSYSTEM S_LDLM
This file contains Asynchronous System Trap (AST) handlers and related LDLM request-processing routines.
Functions
module_param (ldlm_enqueue_min, uint, 0644)
MODULE_PARM_DESC (ldlm_enqueue_min,"lock enqueue timeout minimum")
static void interrupted_completion_wait (void *data)
int ldlm_expired_completion_wait (void *data)
static unsigned int ldlm_cp_timeout (struct ldlm_lock *lock)
Calculate the Completion timeout (covering enqueue, BL AST, data flush, lock cancel, and their replies).
static int ldlm_completion_tail (struct ldlm_lock *lock, void *data)
Helper function for ldlm_completion_ast(), updating timings when lock is actually granted.
int ldlm_completion_ast_async (struct ldlm_lock *lock, __u64 flags, void *data)
Implementation of ->l_completion_ast() for a client, that doesn't wait until lock is granted.
int ldlm_completion_ast (struct ldlm_lock *lock, __u64 flags, void *data)
Generic LDLM "completion" AST.
int ldlm_blocking_ast_nocheck (struct ldlm_lock *lock)
A helper to build a blocking AST function.
int ldlm_blocking_ast (struct ldlm_lock *lock, struct ldlm_lock_desc *desc, void *data, int flag)
Server blocking AST.
int ldlm_glimpse_ast (struct ldlm_lock *lock, void *reqp)
Implements ldlm_lock::l_glimpse_ast for extent locks acquired on the server.
int ldlm_cli_enqueue_local (struct ldlm_namespace *ns, const struct ldlm_res_id *res_id, enum ldlm_type type, union ldlm_policy_data *policy, enum ldlm_mode mode, __u64 *flags, ldlm_blocking_callback blocking, ldlm_completion_callback completion, ldlm_glimpse_callback glimpse, void *data, __u32 lvb_len, enum lvb_type lvb_type, const __u64 *client_cookie, struct lustre_handle *lockh)
Enqueue a local lock (typically on a server).
static void failed_lock_cleanup (struct ldlm_namespace *ns, struct ldlm_lock *lock, int mode)
int ldlm_cli_enqueue_fini (struct obd_export *exp, struct ptlrpc_request *req, enum ldlm_type type, __u8 with_policy, enum ldlm_mode mode, __u64 *flags, void *lvb, __u32 lvb_len, const struct lustre_handle *lockh, int rc)
Finishing portion of client lock enqueue code.
static int ldlm_req_handles_avail (int req_size, int off)
Estimate number of lock handles that would fit into request of given size.
static int ldlm_capsule_handles_avail (struct req_capsule *pill, enum req_location loc, int off)
static int ldlm_format_handles_avail (struct obd_import *imp, const struct req_format *fmt, enum req_location loc, int off)
int ldlm_prep_elc_req (struct obd_export *exp, struct ptlrpc_request *req, int version, int opc, int canceloff, struct list_head *cancels, int count)
Cancel LRU locks and pack them into the enqueue request.
int ldlm_prep_enqueue_req (struct obd_export *exp, struct ptlrpc_request *req, struct list_head *cancels, int count)
struct ptlrpc_request * ldlm_enqueue_pack (struct obd_export *exp, int lvb_len)
int ldlm_cli_enqueue (struct obd_export *exp, struct ptlrpc_request **reqp, struct ldlm_enqueue_info *einfo, const struct ldlm_res_id *res_id, union ldlm_policy_data const *policy, __u64 *flags, void *lvb, __u32 lvb_len, enum lvb_type lvb_type, struct lustre_handle *lockh, int async)
Client-side lock enqueue.
static int ldlm_cli_convert_local (struct ldlm_lock *lock, int new_mode, __u32 *flags)
int ldlm_cli_convert (const struct lustre_handle *lockh, int new_mode, __u32 *flags)
static __u64 ldlm_cli_cancel_local (struct ldlm_lock *lock)
Cancel locks locally.
static void ldlm_cancel_pack (struct ptlrpc_request *req, struct list_head *head, int count)
Pack count locks in head into ldlm_request buffer of request req.
int ldlm_cli_cancel_req (struct obd_export *exp, struct list_head *cancels, int count, enum ldlm_cancel_flags flags)
Prepare and send a batched cancel RPC.
static struct ldlm_pool * ldlm_imp2pl (struct obd_import *imp)
int ldlm_cli_update_pool (struct ptlrpc_request *req)
Update client's OBD pool related fields with new SLV and Limit from req.
int ldlm_cli_cancel (const struct lustre_handle *lockh, enum ldlm_cancel_flags cancel_flags)
Client side lock cancel.
int ldlm_cli_cancel_list_local (struct list_head *cancels, int count, enum ldlm_cancel_flags cancel_flags)
Locally cancel up to count locks in list cancels.
static enum ldlm_policy_res ldlm_cancel_no_wait_policy (struct ldlm_namespace *ns, struct ldlm_lock *lock, int unused, int added, int count)
Cancel as many locks as possible w/o sending any RPCs (e.g.
static enum ldlm_policy_res ldlm_cancel_lrur_policy (struct ldlm_namespace *ns, struct ldlm_lock *lock, int unused, int added, int count)
Callback function for LRU-resize policy.
static enum ldlm_policy_res ldlm_cancel_lrur_no_wait_policy (struct ldlm_namespace *ns, struct ldlm_lock *lock, int unused, int added, int count)
static enum ldlm_policy_res ldlm_cancel_passed_policy (struct ldlm_namespace *ns, struct ldlm_lock *lock, int unused, int added, int count)
Callback function for proc used policy.
static enum ldlm_policy_res ldlm_cancel_aged_policy (struct ldlm_namespace *ns, struct ldlm_lock *lock, int unused, int added, int count)
Callback function for aged policy.
static enum ldlm_policy_res ldlm_cancel_default_policy (struct ldlm_namespace *ns, struct ldlm_lock *lock, int unused, int added, int count)
Callback function for default policy.
static ldlm_cancel_lru_policy_t ldlm_cancel_lru_policy (struct ldlm_namespace *ns, enum ldlm_lru_flags lru_flags)
static int ldlm_prepare_lru_list (struct ldlm_namespace *ns, struct list_head *cancels, int count, int max, enum ldlm_lru_flags lru_flags)
Free space in LRU for count new locks, redundant unused locks are canceled locally;
also cancel locally unused aged locks;
do not cancel more than max locks;
GET the found locks and add them into the cancels list.
int ldlm_cancel_lru_local (struct ldlm_namespace *ns, struct list_head *cancels, int count, int max, enum ldlm_cancel_flags cancel_flags, enum ldlm_lru_flags lru_flags)
int ldlm_cancel_lru (struct ldlm_namespace *ns, int nr, enum ldlm_cancel_flags cancel_flags, enum ldlm_lru_flags lru_flags)
Cancel at least nr locks from given namespace LRU.
int ldlm_cancel_resource_local (struct ldlm_resource *res, struct list_head *cancels, union ldlm_policy_data *policy, enum ldlm_mode mode, __u64 lock_flags, enum ldlm_cancel_flags cancel_flags, void *opaque)
Find and cancel locally unused locks found on resource, matched to the given policy, mode.
int ldlm_cli_cancel_list (struct list_head *cancels, int count, struct ptlrpc_request *req, enum ldlm_cancel_flags flags)
Cancel client-side locks from a list and send/prepare cancel RPCs to the server.
int ldlm_cli_cancel_unused_resource (struct ldlm_namespace *ns, const struct ldlm_res_id *res_id, union ldlm_policy_data *policy, enum ldlm_mode mode, enum ldlm_cancel_flags flags, void *opaque)
Cancel all locks on a resource that have 0 readers/writers.
static int ldlm_cli_hash_cancel_unused (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode, void *arg)
int ldlm_cli_cancel_unused (struct ldlm_namespace *ns, const struct ldlm_res_id *res_id, enum ldlm_cancel_flags flags, void *opaque)
Cancel all locks on a namespace (or a specific resource, if given) that have 0 readers/writers.
int ldlm_resource_foreach (struct ldlm_resource *res, ldlm_iterator_t iter, void *closure)
static int ldlm_iter_helper (struct ldlm_lock *lock, void *closure)
static int ldlm_res_iter_helper (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode, void *arg)
void ldlm_namespace_foreach (struct ldlm_namespace *ns, ldlm_iterator_t iter, void *closure)
int ldlm_resource_iterate (struct ldlm_namespace *ns, const struct ldlm_res_id *res_id, ldlm_iterator_t iter, void *data)
static int ldlm_chain_lock_for_replay (struct ldlm_lock *lock, void *closure)
static int replay_lock_interpret (const struct lu_env *env, struct ptlrpc_request *req, struct ldlm_async_args *aa, int rc)
static int replay_one_lock (struct obd_import *imp, struct ldlm_lock *lock)
static void ldlm_cancel_unused_locks_for_replay (struct ldlm_namespace *ns)
Cancel as many unused locks as possible before replay.
int ldlm_replay_locks (struct obd_import *imp)
Variables
unsigned int ldlm_enqueue_min = OBD_TIMEOUT_DEFAULT
unsigned int ldlm_cancel_unused_locks_before_replay = 1
enum ldlm_policy_res(* ldlm_cancel_lru_policy_t)(struct ldlm_namespace *ns, struct ldlm_lock *lock, int unused, int added, int count)
Define Documentation
#define DEBUG_SUBSYSTEM S_LDLM
This file contains Asynchronous System Trap (AST) handlers and related LDLM request-processing routines.
An AST is a callback issued on a lock when its state is changed. There are several different types of ASTs (callbacks) registered for each lock:
completion AST: when a lock is enqueued by some process, but cannot be granted immediately due to other conflicting locks on the same resource, the completion AST is sent to notify the caller when the lock is eventually granted
blocking AST: when a lock is granted to some process, if another process enqueues a conflicting (blocking) lock on a resource, a blocking AST is sent to notify the holder(s) of the lock(s) of the conflicting lock request. The lock holder(s) must release their lock(s) on that resource in a timely manner or be evicted by the server.
glimpse AST: this is used when a process wants information about a lock (i.e. the lock value block (LVB)) but does not necessarily require holding the lock. If the resource is locked, the lock holder(s) are sent glimpse ASTs and the LVB is returned to the caller, and lock holder(s) may CANCEL their lock(s) if they are idle. If the resource is not locked, the server may grant the lock.
Definition at line 62 of file ldlm_request.c.
Function Documentation
static void failed_lock_cleanup (struct ldlm_namespace * ns, struct ldlm_lock * lock, int mode) [static]
Definition at line 491 of file ldlm_request.c.
References ldlm_lock::l_flags, ldlm_lock::l_granted_mode, ldlm_lock::l_req_mode, ldlm_lock::l_resource, LDLM_DEBUG, LDLM_FL_ATOMIC_CB, LDLM_FL_CBPENDING, LDLM_FL_FAILED, LDLM_FL_LOCAL_ONLY, LDLM_FLOCK, ldlm_is_destroyed, ldlm_is_failed, ldlm_lock_decref_internal(), ldlm_lock_decref_internal_nolock(), ldlm_lock_destroy_nolock(), ldlm_resource_unlink_lock(), lock_res_and_lock(), ldlm_resource::lr_type, and unlock_res_and_lock().
Referenced by ldlm_cli_enqueue(), and ldlm_cli_enqueue_fini().
static void interrupted_completion_wait (void * data) [static]
Definition at line 77 of file ldlm_request.c.
Referenced by ldlm_completion_ast().
static enum ldlm_policy_res ldlm_cancel_aged_policy (struct ldlm_namespace * ns, struct ldlm_lock * lock, int unused, int added, int count) [static]
Callback function for aged policy.
Makes decision whether to keep lock in LRU for current LRU size unused, added in current scan added and number of locks to be preferably canceled count.
Return values:
LDLM_POLICY_KEEP_LOCK keep lock in LRU in stop scanning
LDLM_POLICY_CANCEL_LOCK cancel lock from LRU
Definition at line 1574 of file ldlm_request.c.
References cfs_time_add(), cfs_time_before(), cfs_time_current(), ldlm_lock::l_last_used, LDLM_POLICY_CANCEL_LOCK, LDLM_POLICY_KEEP_LOCK, and ldlm_namespace::ns_max_age.
Referenced by ldlm_cancel_lru_policy().
static enum ldlm_policy_res ldlm_cancel_default_policy (struct ldlm_namespace * ns, struct ldlm_lock * lock, int unused, int added, int count) [static]
Callback function for default policy.
Makes decision whether to keep lock in LRU for current LRU size unused, added in current scan added and number of locks to be preferably canceled count.
Return values:
LDLM_POLICY_KEEP_LOCK keep lock in LRU in stop scanning
LDLM_POLICY_CANCEL_LOCK cancel lock from LRU
Definition at line 1597 of file ldlm_request.c.
References LDLM_POLICY_CANCEL_LOCK, and LDLM_POLICY_KEEP_LOCK.
Referenced by ldlm_cancel_lru_policy().
int ldlm_cancel_lru (struct ldlm_namespace * ns, int nr, enum ldlm_cancel_flags cancel_flags, enum ldlm_lru_flags lru_flags)
Cancel at least nr locks from given namespace LRU.
When called with LCF_ASYNC the blocking callback will be handled in a thread and this function will return after the thread has been asked to call the callback. When called with LCF_ASYNC the blocking callback will be performed in this function.
Definition at line 1831 of file ldlm_request.c.
References ENTRY, ldlm_bl_to_thread_list(), ldlm_prepare_lru_list(), LIST_HEAD_INIT, and RETURN.
Referenced by ldlm_lock_decref_internal().
int ldlm_cancel_lru_local (struct ldlm_namespace * ns, struct list_head * cancels, int count, int max, enum ldlm_cancel_flags cancel_flags, enum ldlm_lru_flags lru_flags)
Definition at line 1809 of file ldlm_request.c.
References ldlm_cli_cancel_list_local(), and ldlm_prepare_lru_list().
Referenced by ldlm_cancel_unused_locks_for_replay(), ldlm_cli_cancel(), and ldlm_prep_elc_req().
static ldlm_cancel_lru_policy_t ldlm_cancel_lru_policy (struct ldlm_namespace * ns, enum ldlm_lru_flags lru_flags) [static]
Definition at line 1613 of file ldlm_request.c.
References ldlm_cancel_aged_policy(), ldlm_cancel_default_policy(), ldlm_cancel_lrur_no_wait_policy(), ldlm_cancel_lrur_policy(), ldlm_cancel_no_wait_policy(), ldlm_cancel_passed_policy(), LDLM_LRU_FLAG_AGED, LDLM_LRU_FLAG_LRUR, LDLM_LRU_FLAG_LRUR_NO_WAIT, LDLM_LRU_FLAG_NO_WAIT, LDLM_LRU_FLAG_PASSED, LDLM_LRU_FLAG_SHRINK, and ns_connect_lru_resize().
Referenced by ldlm_prepare_lru_list().
static enum ldlm_policy_res ldlm_cancel_lrur_no_wait_policy (struct ldlm_namespace * ns, struct ldlm_lock * lock, int unused, int added, int count) [static]
Definition at line 1531 of file ldlm_request.c.
References ldlm_cancel_lrur_policy(), ldlm_cancel_no_wait_policy(), and LDLM_POLICY_KEEP_LOCK.
Referenced by ldlm_cancel_lru_policy().
static enum ldlm_policy_res ldlm_cancel_lrur_policy (struct ldlm_namespace * ns, struct ldlm_lock * lock, int unused, int added, int count) [static]
Callback function for LRU-resize policy.
Decides whether to keep lock in LRU for current LRU size unused, added in current scan added and number of locks to be preferably canceled count.
Return values:
LDLM_POLICY_KEEP_LOCK keep lock in LRU in stop scanning
LDLM_POLICY_CANCEL_LOCK cancel lock from LRU
Definition at line 1492 of file ldlm_request.c.
References __u64, cfs_duration_sec(), cfs_time_add(), cfs_time_after(), cfs_time_current(), cfs_time_sub(), ldlm_lock::l_last_used, LDLM_POLICY_CANCEL_LOCK, LDLM_POLICY_KEEP_LOCK, ldlm_pool_get_lvf(), ldlm_pool_get_slv(), ldlm_pool_set_clv(), ldlm_namespace::ns_max_age, and ldlm_namespace::ns_pool.
Referenced by ldlm_cancel_lru_policy(), and ldlm_cancel_lrur_no_wait_policy().
static enum ldlm_policy_res ldlm_cancel_no_wait_policy (struct ldlm_namespace * ns, struct ldlm_lock * lock, int unused, int added, int count) [static]
Cancel as many locks as possible w/o sending any RPCs (e.g.
to write back dirty data, to close a file, ...) or waiting for any RPCs in-flight (e.g. readahead requests, ...)
Definition at line 1458 of file ldlm_request.c.
References ldlm_lock::l_resource, LDLM_EXTENT, LDLM_IBITS, LDLM_POLICY_CANCEL_LOCK, LDLM_POLICY_SKIP_LOCK, ldlm_set_skipped, lock_res_and_lock(), ldlm_resource::lr_type, ldlm_namespace::ns_cancel, RETURN, and unlock_res_and_lock().
Referenced by ldlm_cancel_lru_policy(), and ldlm_cancel_lrur_no_wait_policy().
static void ldlm_cancel_pack (struct ptlrpc_request * req, struct list_head * head, int count) [static]
Pack count locks in head into ldlm_request buffer of request req.
Definition at line 1148 of file ldlm_request.c.
References CDEBUG, D_DLMTRACE, ENTRY, EXIT, ldlm_lock::l_conn_export, ldlm_lock::l_remote_handle, LASSERT, LDLM_DEBUG, LDLM_LOCKREQ_HANDLES, list_for_each_entry, ldlm_request::lock_count, ldlm_request::lock_handle, max, packed, RCL_CLIENT, req_capsule_client_get(), req_capsule_get_size(), RMF_DLM_REQ, and ptlrpc_request::rq_pill.
Referenced by ldlm_cli_cancel_list(), and ldlm_cli_cancel_req().
static enum ldlm_policy_res ldlm_cancel_passed_policy (struct ldlm_namespace * ns, struct ldlm_lock * lock, int unused, int added, int count) [static]
Callback function for proc used policy.
Makes decision whether to keep lock in LRU for current LRU size unused, added in current scan added and number of locks to be preferably canceled count.
Return values:
LDLM_POLICY_KEEP_LOCK keep lock in LRU in stop scanning
LDLM_POLICY_CANCEL_LOCK cancel lock from LRU
Definition at line 1554 of file ldlm_request.c.
References LDLM_POLICY_CANCEL_LOCK, and LDLM_POLICY_KEEP_LOCK.
Referenced by ldlm_cancel_lru_policy().
static void ldlm_cancel_unused_locks_for_replay (struct ldlm_namespace * ns) [static]
Cancel as many unused locks as possible before replay.
since we are in recovery, we can't wait for any outstanding RPCs to send any RPC to the server.
Called only in recovery before replaying locks. there is no need to replay locks that are unused. since the clients may hold thousands of cached unused locks, dropping the unused locks can greatly reduce the load on the servers at recovery time.
Definition at line 2319 of file ldlm_request.c.
References CDEBUG, D_DLMTRACE, LCF_LOCAL, ldlm_cancel_lru_local(), LDLM_LRU_FLAG_NO_WAIT, ldlm_ns_name(), LIST_HEAD_INIT, and ldlm_namespace::ns_nr_unused.
Referenced by ldlm_replay_locks().
static int ldlm_capsule_handles_avail (struct req_capsule * pill, enum req_location loc, int off) [inline, static]
Definition at line 738 of file ldlm_request.c.
References ldlm_req_handles_avail(), req_capsule_msg_size(), and size.
Referenced by ldlm_prep_elc_req().
static int ldlm_chain_lock_for_replay (struct ldlm_lock * lock, void * closure) [static]
Definition at line 2155 of file ldlm_request.c.
References ldlm_lock::l_flags, ldlm_lock::l_pending_chain, LASSERTF, LDLM_FL_CANCELING, LDLM_FL_FAILED, LDLM_ITER_CONTINUE, LDLM_LOCK_GET, list, list_add(), list_empty(), list_head::next, and list_head::prev.
Referenced by ldlm_replay_locks().
static __u64 ldlm_cli_cancel_local (struct ldlm_lock * lock) [static]
Cancel locks locally.
Returns:
Return values:
LDLM_FL_LOCAL_ONLY if there is no need for a CANCEL RPC to the server
LDLM_FL_CANCELING otherwise;
LDLM_FL_BL_AST if there is a need for a separate CANCEL RPC.
Definition at line 1107 of file ldlm_request.c.
References __u64, CDEBUG, D_DLMTRACE, ENTRY, ldlm_lock::l_conn_export, ldlm_lock::l_flags, ldlm_lock::l_resource, LBUG, ldlm_cancel_callback(), LDLM_DEBUG, LDLM_ERROR, LDLM_FL_BL_AST, LDLM_FL_CANCEL_ON_BLOCK, LDLM_FL_CANCELING, LDLM_FL_LOCAL_ONLY, ldlm_is_bl_ast, ldlm_lock_cancel(), ldlm_lock_to_ns(), ldlm_reprocess_all(), ldlm_set_cbpending, lock_res_and_lock(), ns_is_client(), RETURN, and unlock_res_and_lock().
Referenced by ldlm_cli_cancel(), and ldlm_cli_cancel_list_local().
static int ldlm_cli_convert_local (struct ldlm_lock * lock, int new_mode, __u32 * flags) [static]
Definition at line 1001 of file ldlm_request.c.
References CERROR, ENTRY, LBUG, LDLM_DEBUG, ldlm_lock_convert(), LDLM_LOCK_PUT, ldlm_lock_to_ns(), ldlm_reprocess_all(), LUSTRE_EDEADLK, ns_is_client(), and RETURN.
Referenced by ldlm_cli_convert().
static int ldlm_cli_hash_cancel_unused (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode, void * arg) [static]
Definition at line 2010 of file ldlm_request.c.
References cfs_hash_object(), ldlm_cli_cancel_arg::lc_flags, ldlm_cli_cancel_arg::lc_opaque, LCK_MINMODE, ldlm_cli_cancel_unused_resource(), ldlm_res_to_ns(), and ldlm_resource::lr_name.
Referenced by ldlm_cli_cancel_unused().
static int ldlm_completion_tail (struct ldlm_lock * lock, void * data) [static]
Helper function for ldlm_completion_ast(), updating timings when lock is actually granted.
Definition at line 160 of file ldlm_request.c.
References at_measured(), CFS_DURATION_T, cfs_time_current_sec(), cfs_time_sub(), ldlm_lock::l_last_activity, LDLM_DEBUG, ldlm_is_destroyed, ldlm_is_failed, and ldlm_lock_to_ns_at().
Referenced by ldlm_completion_ast(), and ldlm_completion_ast_async().
static unsigned int ldlm_cp_timeout (struct ldlm_lock * lock) [static]
Calculate the Completion timeout (covering enqueue, BL AST, data flush, lock cancel, and their replies).
Used for lock completion timeout on the client side.
Parameters:
[in] lock lock which is waiting the completion callback
Return values:
timeout in seconds to wait for the server reply
Definition at line 142 of file ldlm_request.c.
References at_get(), AT_OFF, ldlm_enqueue_min, ldlm_lock_to_ns_at(), max, obd_timeout, and timeout.
Referenced by ldlm_completion_ast().
static int ldlm_format_handles_avail (struct obd_import * imp, const struct req_format * fmt, enum req_location loc, int off) [inline, static]
Definition at line 746 of file ldlm_request.c.
References obd_import::imp_msg_magic, ldlm_req_handles_avail(), req_capsule_fmt_size(), and size.
Referenced by ldlm_cli_cancel(), and ldlm_cli_cancel_req().
static struct ldlm_pool* ldlm_imp2pl (struct obd_import * imp) [static, read]
Definition at line 1285 of file ldlm_request.c.
References obd_import::imp_obd, LASSERT, ldlm_namespace::ns_pool, and obd_device::obd_namespace.
static int ldlm_iter_helper (struct ldlm_lock * lock, void * closure) [static]
Definition at line 2099 of file ldlm_request.c.
References iter_helper_data::closure, and iter_helper_data::iter.
Referenced by ldlm_res_iter_helper().
static int ldlm_prepare_lru_list (struct ldlm_namespace * ns, struct list_head * cancels, int count, int max, enum ldlm_lru_flags lru_flags) [static]
Free space in LRU for count new locks, redundant unused locks are canceled locally;
also cancel locally unused aged locks;
do not cancel more than max locks;
GET the found locks and add them into the cancels list.
A client lock can be added to the l_bl_ast list only when it is marked LDLM_FL_CANCELING. Otherwise, somebody is already doing CANCEL. There are the following use cases: ldlm_cancel_resource_local(), ldlm_cancel_lru_local() and ldlm_cli_cancel(), which check and set this flag properly. As any attempt to cancel a lock rely on this flag, l_bl_ast list is accessed later without any special locking.
Calling policies for enabled LRU resize: ---------------------------------------- flags & LDLM_LRU_FLAG_LRUR - use LRU resize policy (SLV from server) to cancel not more than count locks;
flags & LDLM_LRU_FLAG_PASSED - cancel count number of old locks (located at the beginning of LRU list);
flags & LDLM_LRU_FLAG_SHRINK - cancel not more than count locks according to memory pressre policy function;
flags & LDLM_LRU_FLAG_AGED - cancel count locks according to "aged policy"
flags & LDLM_LRU_FLAG_NO_WAIT - cancel as many unused locks as possible (typically before replaying locks) w/o sending any RPCs or waiting for any outstanding RPC to complete.
Definition at line 1669 of file ldlm_request.c.
References cfs_time_current(), ENTRY, ldlm_lock::l_bl_ast, ldlm_lock::l_flags, ldlm_lock::l_last_used, ldlm_lock::l_lru, ldlm_lock::l_readers, ldlm_lock::l_reference, ldlm_lock::l_writers, LASSERT, ldlm_cancel_lru_policy(), ldlm_cancel_lru_policy_t, ldlm_clear_cancel_on_block, LDLM_FL_CANCELING, LDLM_FL_CBPENDING, ldlm_is_bl_ast, ldlm_is_canceling, ldlm_is_skipped, LDLM_LOCK_GET, LDLM_LOCK_RELEASE, ldlm_lock_remove_from_lru_check(), ldlm_lock_remove_from_lru_nolock(), LDLM_LRU_FLAG_LRUR_NO_WAIT, LDLM_LRU_FLAG_NO_WAIT, LDLM_POLICY_KEEP_LOCK, LDLM_POLICY_SKIP_LOCK, list_add(), list_empty(), list_for_each_entry_safe, lock_res_and_lock(), lu_ref_add(), lu_ref_del(), ns_connect_lru_resize(), ldlm_namespace::ns_lock, ldlm_namespace::ns_max_unused, ldlm_namespace::ns_nr_unused, ldlm_namespace::ns_unused_list, RETURN, and unlock_res_and_lock().
Referenced by ldlm_cancel_lru(), and ldlm_cancel_lru_local().
static int ldlm_req_handles_avail (int req_size, int off) [inline, static]
Estimate number of lock handles that would fit into request of given size.
PAGE_SIZE-512 is to allow TCP/IP and LNET headers to fit into a single page on the send/receive side. XXX: 512 should be changed to more adequate value.
Definition at line 724 of file ldlm_request.c.
References LDLM_LOCKREQ_HANDLES, LDLM_MAXREQSIZE, likely, and min_t.
Referenced by ldlm_capsule_handles_avail(), and ldlm_format_handles_avail().
static int ldlm_res_iter_helper (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode, void * arg) [static]
Definition at line 2105 of file ldlm_request.c.
References cfs_hash_object(), ldlm_iter_helper(), LDLM_ITER_STOP, and ldlm_resource_foreach().
Referenced by ldlm_namespace_foreach().
module_param (ldlm_enqueue_min , uint , 0644)
MODULE_PARM_DESC (ldlm_enqueue_min , "lock enqueue timeout minimum")
static int replay_lock_interpret (const struct lu_env * env, struct ptlrpc_request * req, struct ldlm_async_args * aa, int rc) [static]
Definition at line 2175 of file ldlm_request.c.
References CERROR, cfs_hash_rehash_key(), lustre_handle::cookie, ELDLM_OK, ENTRY, obd_export::exp_client_uuid, obd_export::exp_lock_hash, GOTO, obd_import::imp_replay_inflight, ldlm_lock::l_exp_hash, ldlm_lock::l_remote_handle, LDLM_DEBUG, ldlm_handle2lock(), LDLM_LOCK_PUT, libcfs_id2str(), ldlm_reply::lock_handle, ldlm_async_args::lock_handle, LPX64, ptlrpc_connect_import(), ptlrpc_import_recovery_state_machine(), req_capsule_server_get(), RETURN, RMF_DLM_REP, ptlrpc_request::rq_export, ptlrpc_request::rq_import, ptlrpc_request::rq_peer, ptlrpc_request::rq_pill, and obd_uuid::uuid.
Referenced by replay_one_lock().
static int replay_one_lock (struct obd_import * imp, struct ldlm_lock * lock) [static]
Definition at line 2226 of file ldlm_request.c.
References CLASSERT, ENTRY, obd_import::imp_replay_inflight, ldlm_lock::l_granted_mode, ldlm_lock::l_lvb_len, ldlm_lock::l_req_mode, ldlm_lock::l_res_link, LDLM_DEBUG, LDLM_ENQUEUE, LDLM_FL_BLOCK_CONV, LDLM_FL_BLOCK_GRANTED, LDLM_FL_BLOCK_WAIT, LDLM_FL_REPLAY, ldlm_flags_to_wire, ldlm_is_cancel_on_block, ldlm_is_canceling, ldlm_lock2desc(), ldlm_lock2handle(), ldlm_lock_cancel(), list_empty(), ldlm_request::lock_desc, ldlm_request::lock_flags, ldlm_async_args::lock_handle, ldlm_request::lock_handle, LUSTRE_DLM_VERSION, LUSTRE_IMP_REPLAY_LOCKS, lustre_msg_set_flags(), MSG_REQ_REPLAY_DONE, ptlrpc_req_async_args, ptlrpc_request_alloc_pack(), ptlrpc_request_set_replen(), ptlrpcd_add_req(), RCL_SERVER, replay_lock_interpret(), req_capsule_client_get(), req_capsule_extend(), req_capsule_set_size(), RETURN, RMF_DLM_LVB, RMF_DLM_REQ, ptlrpc_request::rq_import, ptlrpc_request::rq_pill, ptlrpc_request::rq_reqmsg, RQF_LDLM_ENQUEUE, and RQF_LDLM_ENQUEUE_LVB.
Referenced by ldlm_replay_locks().
Variable Documentation
enum ldlm_policy_res(* ldlm_cancel_lru_policy_t)(struct ldlm_namespace *ns, struct ldlm_lock *lock, int unused, int added, int count)
Referenced by ldlm_prepare_lru_list().
unsigned int ldlm_cancel_unused_locks_before_replay = 1
Definition at line 75 of file ldlm_request.c.
Referenced by ldlm_replay_locks().
unsigned int ldlm_enqueue_min = OBD_TIMEOUT_DEFAULT
Definition at line 70 of file ldlm_request.c.
Referenced by ldlm_cp_timeout(), and ldlm_namespace_new().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.