Lustre: lustre/ldlm/ldlm_internal.h File Reference
lustre/ldlm/ldlm_internal.h File Reference
Data Structures
struct ldlm_cb_set_arg
struct ldlm_state
Defines
#define MAX_STRING_SIZE 128
#define ldlm_lock_remove_from_lru(lock) ldlm_lock_remove_from_lru_check(lock, 0)
#define LDLM_POOL_PROC_READER_SEQ_SHOW(var, type)
#define LDLM_POOL_PROC_WRITER(var, type)
Typedefs
typedef void(* ldlm_policy_wire_to_local_t)(const union ldlm_wire_policy_data *, union ldlm_policy_data *)
typedef void(* ldlm_policy_local_to_wire_t)(const union ldlm_policy_data *, union ldlm_wire_policy_data *)
Enumerations
enum ldlm_lru_flags {
LDLM_LRU_FLAG_AGED = 0x01, LDLM_LRU_FLAG_PASSED = 0x02, LDLM_LRU_FLAG_SHRINK = 0x04, LDLM_LRU_FLAG_LRUR = 0x08,
LDLM_LRU_FLAG_NO_WAIT = 0x10, LDLM_LRU_FLAG_LRUR_NO_WAIT = 0x20
}
enum ldlm_desc_ast_t { LDLM_WORK_BL_AST, LDLM_WORK_CP_AST, LDLM_WORK_REVOKE_AST, LDLM_WORK_GL_AST }
enum ldlm_policy_res { LDLM_POLICY_CANCEL_LOCK, LDLM_POLICY_KEEP_LOCK, LDLM_POLICY_SKIP_LOCK }
Functions
static int ldlm_namespace_nr_read (enum ldlm_side client)
static void ldlm_namespace_nr_inc (enum ldlm_side client)
static void ldlm_namespace_nr_dec (enum ldlm_side client)
static struct list_head * ldlm_namespace_list (enum ldlm_side client)
static struct list_head * ldlm_namespace_inactive_list (enum ldlm_side client)
static struct mutex * ldlm_namespace_lock (enum ldlm_side client)
static int ldlm_ns_empty (struct ldlm_namespace *ns)
void ldlm_namespace_move_to_active_locked (struct ldlm_namespace *, enum ldlm_side)
Should be called with ldlm_namespace_lock(client) taken.
void ldlm_namespace_move_to_inactive_locked (struct ldlm_namespace *, enum ldlm_side)
Should be called with ldlm_namespace_lock(client) taken.
struct ldlm_namespace * ldlm_namespace_first_locked (enum ldlm_side)
Should be called with ldlm_namespace_lock(client) taken.
int ldlm_cancel_lru (struct ldlm_namespace *ns, int nr, enum ldlm_cancel_flags cancel_flags, enum ldlm_lru_flags lru_flags)
Cancel at least nr locks from given namespace LRU.
int ldlm_cancel_lru_local (struct ldlm_namespace *ns, struct list_head *cancels, int count, int max, enum ldlm_cancel_flags cancel_flags, enum ldlm_lru_flags lru_flags)
void ldlm_resource_insert_lock_after (struct ldlm_lock *original, struct ldlm_lock *new)
Insert a lock into resource after specified lock.
void ldlm_grant_lock (struct ldlm_lock *lock, struct list_head *work_list)
Perform lock granting bookkeeping.
int ldlm_fill_lvb (struct ldlm_lock *lock, struct req_capsule *pill, enum req_location loc, void *data, int size)
The caller must guarantee that the buffer is large enough.
struct ldlm_lock * ldlm_lock_create (struct ldlm_namespace *ns, const struct ldlm_res_id *, enum ldlm_type type, enum ldlm_mode mode, const struct ldlm_callback_suite *cbs, void *data, __u32 lvb_len, enum lvb_type lvb_type)
Create and fill in new LDLM lock with specified properties.
enum ldlm_error ldlm_lock_enqueue (struct ldlm_namespace *, struct ldlm_lock **, void *cookie, __u64 *flags)
Enqueue (request) a lock.
void ldlm_lock_addref_internal (struct ldlm_lock *, enum ldlm_mode mode)
Add specified reader/writer reference to LDLM lock lock.
void ldlm_lock_addref_internal_nolock (struct ldlm_lock *, enum ldlm_mode mode)
Helper function.
void ldlm_lock_decref_internal (struct ldlm_lock *, enum ldlm_mode mode)
Removes reader/writer reference for LDLM lock lock.
void ldlm_lock_decref_internal_nolock (struct ldlm_lock *, enum ldlm_mode mode)
Removes reader/writer reference for LDLM lock lock.
void ldlm_add_ast_work_item (struct ldlm_lock *lock, struct ldlm_lock *new, struct list_head *work_list)
Aggregator function to add AST work items into a list.
int ldlm_run_ast_work (struct ldlm_namespace *ns, struct list_head *rpc_list, ldlm_desc_ast_t ast_type)
Process list of locks in need of ASTs being sent.
int ldlm_work_gl_ast_lock (struct ptlrpc_request_set *rqset, void *opaq)
Process a call to glimpse AST callback for a lock in ast_work list.
int ldlm_lock_remove_from_lru_check (struct ldlm_lock *lock, cfs_time_t last_use)
Removes LDLM lock lock from LRU.
int ldlm_lock_remove_from_lru_nolock (struct ldlm_lock *lock)
Removes LDLM lock lock from LRU.
void ldlm_lock_add_to_lru_nolock (struct ldlm_lock *lock)
Adds LDLM lock lock to namespace LRU.
void ldlm_lock_add_to_lru (struct ldlm_lock *lock)
Adds LDLM lock lock to namespace LRU.
void ldlm_lock_touch_in_lru (struct ldlm_lock *lock)
Moves LDLM lock lock that is already in namespace LRU to the tail of the LRU.
void ldlm_lock_destroy_nolock (struct ldlm_lock *lock)
Destroys a LDLM lock lock that is already locked.
int ldlm_export_cancel_blocked_locks (struct obd_export *exp)
Cancel all blocked locks for given export.
int ldlm_export_cancel_locks (struct obd_export *exp)
Cancel all locks for given export.
int ldlm_bl_to_thread_lock (struct ldlm_namespace *ns, struct ldlm_lock_desc *ld, struct ldlm_lock *lock)
int ldlm_bl_to_thread_list (struct ldlm_namespace *ns, struct ldlm_lock_desc *ld, struct list_head *cancels, int count, enum ldlm_cancel_flags cancel_flags)
int ldlm_bl_thread_wakeup (void)
void ldlm_handle_bl_callback (struct ldlm_namespace *ns, struct ldlm_lock_desc *ld, struct ldlm_lock *lock)
Callback handler for receiving incoming blocking ASTs.
void ldlm_extent_add_lock (struct ldlm_resource *res, struct ldlm_lock *lock)
Add newly granted lock into interval tree for the resource.
void ldlm_extent_unlink_lock (struct ldlm_lock *lock)
Remove cancelled lock from resource interval tree.
int ldlm_process_flock_lock (struct ldlm_lock *req, __u64 *flags, int first_enq, enum ldlm_error *err, struct list_head *work_list)
Process a granting attempt for flock lock.
int ldlm_init_flock_export (struct obd_export *exp)
void ldlm_destroy_flock_export (struct obd_export *exp)
void l_check_ns_lock (struct ldlm_namespace *ns)
void l_check_no_ns_lock (struct ldlm_namespace *ns)
void ldlm_interval_attach (struct ldlm_interval *n, struct ldlm_lock *l)
struct ldlm_interval * ldlm_interval_detach (struct ldlm_lock *l)
struct ldlm_interval * ldlm_interval_alloc (struct ldlm_lock *lock)
void ldlm_interval_free (struct ldlm_interval *node)
static struct ldlm_extent * ldlm_interval_extent (struct ldlm_interval *node)
int ldlm_init (void)
void ldlm_exit (void)
static void ldlm_add_var (struct lprocfs_vars *vars, struct proc_dir_entry *proc_dir, const char *name, void *data, const struct file_operations *ops)
static int is_granted_or_cancelled (struct ldlm_lock *lock)
void ldlm_plain_policy_wire_to_local (const union ldlm_wire_policy_data *wpolicy, union ldlm_policy_data *lpolicy)
void ldlm_plain_policy_local_to_wire (const union ldlm_policy_data *lpolicy, union ldlm_wire_policy_data *wpolicy)
void ldlm_ibits_policy_wire_to_local (const union ldlm_wire_policy_data *wpolicy, union ldlm_policy_data *lpolicy)
void ldlm_ibits_policy_local_to_wire (const union ldlm_policy_data *lpolicy, union ldlm_wire_policy_data *wpolicy)
void ldlm_extent_policy_wire_to_local (const union ldlm_wire_policy_data *wpolicy, union ldlm_policy_data *lpolicy)
void ldlm_extent_policy_local_to_wire (const union ldlm_policy_data *lpolicy, union ldlm_wire_policy_data *wpolicy)
void ldlm_flock_policy_wire_to_local (const union ldlm_wire_policy_data *wpolicy, union ldlm_policy_data *lpolicy)
void ldlm_flock_policy_local_to_wire (const union ldlm_policy_data *lpolicy, union ldlm_wire_policy_data *wpolicy)
int ldlm_reclaim_setup (void)
void ldlm_reclaim_cleanup (void)
void ldlm_reclaim_add (struct ldlm_lock *lock)
void ldlm_reclaim_del (struct ldlm_lock *lock)
bool ldlm_reclaim_full (void)
Variables
int ldlm_srv_namespace_nr
int ldlm_cli_namespace_nr
struct mutex ldlm_srv_namespace_lock
struct list_head ldlm_srv_namespace_list
struct mutex ldlm_cli_namespace_lock
struct list_head ldlm_cli_active_namespace_list
struct list_head ldlm_cli_inactive_namespace_list
unsigned int ldlm_cancel_unused_locks_before_replay
unsigned int ldlm_enqueue_min
struct kmem_cache * ldlm_resource_slab
struct kmem_cache * ldlm_lock_slab
struct kmem_cache * ldlm_interval_tree_slab
struct proc_dir_entry * ldlm_svc_proc_dir
struct kmem_cache * ldlm_interval_slab
Define Documentation
#define ldlm_lock_remove_from_lru (lock) ldlm_lock_remove_from_lru_check(lock, 0)
Definition at line 171 of file ldlm_internal.h.
Referenced by ldlm_callback_handler(), ldlm_handle_cp_callback(), ldlm_lock_addref_internal_nolock(), ldlm_lock_decref_internal(), and ldlm_lock_destroy_internal().
#define LDLM_POOL_PROC_READER_SEQ_SHOW (var, type)
Value:
static int lprocfs_##var##_seq_show(struct seq_file *m, void *v)\
        {                                                               \
                struct ldlm_pool *pl = m->private;                      \
                type tmp;                                               \
                                                                        \
                spin_lock(&pl->pl_lock);                                \
                tmp = pl->pl_##var;                                     \
                spin_unlock(&pl->pl_lock);                              \
                                                                        \
                return lprocfs_uint_seq_show(m, &tmp);                  \
        }                                                               \
        struct __##var##__dummy_read {;}
Definition at line 262 of file ldlm_internal.h.
#define LDLM_POOL_PROC_WRITER (var, type)
Value:
static int lprocfs_wr_##var(struct file *file,                  \
                             const char __user *buffer,                 \
                             unsigned long count, void *data)           \
        {                                                               \
                struct ldlm_pool *pl = data;                            \
                type tmp;                                               \
                int rc;                                                 \
                                                                        \
                rc = lprocfs_wr_uint(file, buffer, count, &tmp);        \
                if (rc < 0) {                                           \
                        CERROR("Can't parse user input, rc = %d\n", rc);\
                        return rc;                                      \
                }                                                       \
                                                                        \
                spin_lock(&pl->pl_lock);                                \
                pl->pl_##var = tmp;                                     \
                spin_unlock(&pl->pl_lock);                              \
                                                                        \
                return rc;                                              \
        }                                                               \
        struct __##var##__dummy_write {;}
Definition at line 276 of file ldlm_internal.h.
#define MAX_STRING_SIZE 128
Definition at line 37 of file ldlm_internal.h.
Referenced by jt_obd_list(), ldlm_add_var(), llapi_target_iterate(), and print_obd_line().
Typedef Documentation
typedef void(* ldlm_policy_local_to_wire_t)(const union ldlm_policy_data *, union ldlm_wire_policy_data *)
Definition at line 326 of file ldlm_internal.h.
typedef void(* ldlm_policy_wire_to_local_t)(const union ldlm_wire_policy_data *, union ldlm_policy_data *)
Definition at line 324 of file ldlm_internal.h.
Enumeration Type Documentation
enum ldlm_desc_ast_t
Enumerator:
LDLM_WORK_BL_AST
LDLM_WORK_CP_AST
LDLM_WORK_REVOKE_AST
LDLM_WORK_GL_AST
Definition at line 139 of file ldlm_internal.h.
enum ldlm_lru_flags
Enumerator:
LDLM_LRU_FLAG_AGED
LDLM_LRU_FLAG_PASSED
LDLM_LRU_FLAG_SHRINK
LDLM_LRU_FLAG_LRUR
LDLM_LRU_FLAG_NO_WAIT
LDLM_LRU_FLAG_LRUR_NO_WAIT
Definition at line 103 of file ldlm_internal.h.
enum ldlm_policy_res
Enumerator:
LDLM_POLICY_CANCEL_LOCK
LDLM_POLICY_KEEP_LOCK
LDLM_POLICY_SKIP_LOCK
Definition at line 256 of file ldlm_internal.h.
Function Documentation
static int is_granted_or_cancelled (struct ldlm_lock * lock) [inline, static]
Definition at line 309 of file ldlm_internal.h.
References ldlm_lock::l_granted_mode, ldlm_lock::l_req_mode, ldlm_is_cancel, ldlm_is_cp_reqd, ldlm_is_failed, lock_res_and_lock(), ret, and unlock_res_and_lock().
Referenced by ldlm_completion_ast(), and ldlm_flock_completion_ast().
void l_check_no_ns_lock (struct ldlm_namespace * ns)
void l_check_ns_lock (struct ldlm_namespace * ns)
void ldlm_add_ast_work_item (struct ldlm_lock * lock, struct ldlm_lock * new, struct list_head * work_list)
Aggregator function to add AST work items into a list.
Determines what sort of an AST work needs to be done and calls the proper adding function. Must be called with lr_lock held.
Definition at line 700 of file ldlm_lock.c.
References check_res_locked(), ENTRY, EXIT, ldlm_lock::l_resource, ldlm_add_bl_work_item(), and ldlm_add_cp_work_item().
Referenced by ldlm_flock_cancel_on_deadlock(), ldlm_grant_lock(), and ldlm_process_flock_lock().
static void ldlm_add_var (struct lprocfs_vars * vars, struct proc_dir_entry * proc_dir, const char * name, void * data, const struct file_operations * ops) [inline, static]
Definition at line 300 of file ldlm_internal.h.
References lprocfs_vars::data, lprocfs_vars::fops, lprocfs_add_vars(), MAX_STRING_SIZE, and lprocfs_vars::name.
int ldlm_bl_thread_wakeup (void)
Definition at line 2088 of file ldlm_lockd.c.
References ldlm_bl_pool::blp_waitq, and ldlm_state::ldlm_bl_pool.
int ldlm_bl_to_thread_list (struct ldlm_namespace * ns, struct ldlm_lock_desc * ld, struct list_head * cancels, int count, enum ldlm_cancel_flags cancel_flags)
Definition at line 2081 of file ldlm_lockd.c.
References ldlm_bl_to_thread().
Referenced by ldlm_cancel_lru().
int ldlm_bl_to_thread_lock (struct ldlm_namespace * ns, struct ldlm_lock_desc * ld, struct ldlm_lock * lock)
Definition at line 2075 of file ldlm_lockd.c.
References LCF_ASYNC, and ldlm_bl_to_thread().
Referenced by ldlm_callback_handler(), ldlm_handle_gl_callback(), and ldlm_lock_decref_internal().
int ldlm_cancel_lru (struct ldlm_namespace * ns, int nr, enum ldlm_cancel_flags cancel_flags, enum ldlm_lru_flags lru_flags)
Cancel at least nr locks from given namespace LRU.
When called with LCF_ASYNC the blocking callback will be handled in a thread and this function will return after the thread has been asked to call the callback. When called with LCF_ASYNC the blocking callback will be performed in this function.
Definition at line 1831 of file ldlm_request.c.
References ENTRY, ldlm_bl_to_thread_list(), ldlm_prepare_lru_list(), LIST_HEAD_INIT, and RETURN.
Referenced by ldlm_lock_decref_internal().
int ldlm_cancel_lru_local (struct ldlm_namespace * ns, struct list_head * cancels, int count, int max, enum ldlm_cancel_flags cancel_flags, enum ldlm_lru_flags lru_flags)
Definition at line 1809 of file ldlm_request.c.
References ldlm_cli_cancel_list_local(), and ldlm_prepare_lru_list().
Referenced by ldlm_cancel_unused_locks_for_replay(), ldlm_cli_cancel(), and ldlm_prep_elc_req().
void ldlm_destroy_flock_export (struct obd_export * exp)
Definition at line 955 of file ldlm_flock.c.
References cfs_hash_putref(), ENTRY, EXIT, and obd_export::exp_flock_hash.
Referenced by ldlm_destroy_export().
void ldlm_exit (void)
Definition at line 3203 of file ldlm_lockd.c.
References CERROR, ldlm_interval_slab, ldlm_interval_tree_slab, ldlm_lock_slab, ldlm_refcount, and ldlm_resource_slab.
Referenced by ptlrpc_exit(), and ptlrpc_init().
int ldlm_export_cancel_blocked_locks (struct obd_export * exp)
Cancel all blocked locks for given export.
Typically called on client disconnection/eviction
Definition at line 2361 of file ldlm_lock.c.
References CDEBUG, D_DLMTRACE, export_cl_data::ecl_exp, export_cl_data::ecl_loop, obd_export::exp_bl_list, obd_export::exp_bl_list_lock, obd_export::exp_lock_hash, cfs_hash::hs_count, ldlm_lock::l_exp_list, ldlm_cancel_lock_for_export(), LDLM_LOCK_GET, LDLM_LOCK_RELEASE, list_del_init(), list_empty(), list_entry, and list_head::next.
Referenced by ldlm_bl_thread_exports().
int ldlm_export_cancel_locks (struct obd_export * exp)
Cancel all locks for given export.
Typically called after client disconnection/eviction
Definition at line 2401 of file ldlm_lock.c.
References CDEBUG, cfs_hash_for_each_empty(), D_DLMTRACE, export_cl_data::ecl_exp, export_cl_data::ecl_loop, obd_export::exp_lock_hash, cfs_hash::hs_count, and ldlm_cancel_locks_for_export_cb().
Referenced by ldlm_bl_thread_exports().
void ldlm_extent_add_lock (struct ldlm_resource * res, struct ldlm_lock * lock)
Add newly granted lock into interval tree for the resource.
Definition at line 898 of file ldlm_extent.c.
References ldlm_extent::end, interval_insert(), interval_is_intree(), interval_set(), ldlm_policy_data::l_extent, ldlm_lock::l_granted_mode, ldlm_lock::l_policy_data, ldlm_lock::l_req_mode, ldlm_lock::l_tree_node, LASSERT, ldlm_interval_attach(), ldlm_interval_detach(), ldlm_interval_free(), ldlm_mode_to_index(), ldlm_resource_add_lock(), ldlm_interval::li_node, ldlm_interval_tree::lit_mode, ldlm_interval_tree::lit_root, ldlm_interval_tree::lit_size, ldlm_resource::lr_granted, ldlm_resource::lr_itree, ldlm_extent::start, and to_ldlm_interval.
Referenced by ldlm_grant_lock(), and ldlm_lock_convert().
void ldlm_extent_policy_local_to_wire (const union ldlm_policy_data * lpolicy, union ldlm_wire_policy_data * wpolicy)
Definition at line 969 of file ldlm_extent.c.
References ldlm_extent::end, ldlm_extent::gid, ldlm_policy_data::l_extent, ldlm_wire_policy_data::l_extent, and ldlm_extent::start.
void ldlm_extent_policy_wire_to_local (const union ldlm_wire_policy_data * wpolicy, union ldlm_policy_data * lpolicy)
Definition at line 960 of file ldlm_extent.c.
References ldlm_extent::end, ldlm_extent::gid, ldlm_wire_policy_data::l_extent, ldlm_policy_data::l_extent, and ldlm_extent::start.
void ldlm_extent_unlink_lock (struct ldlm_lock * lock)
Remove cancelled lock from resource interval tree.
Definition at line 936 of file ldlm_extent.c.
References interval_erase(), interval_is_intree(), ldlm_lock::l_granted_mode, ldlm_lock::l_resource, ldlm_lock::l_tree_node, LASSERT, ldlm_interval_detach(), ldlm_interval_free(), ldlm_mode_to_index(), ldlm_interval::li_node, ldlm_interval_tree::lit_root, ldlm_interval_tree::lit_size, and ldlm_resource::lr_itree.
Referenced by ldlm_resource_unlink_lock().
int ldlm_fill_lvb (struct ldlm_lock * lock, struct req_capsule * pill, enum req_location loc, void * data, int size)
The caller must guarantee that the buffer is large enough.
Definition at line 1539 of file ldlm_lock.c.
References ENTRY, ldlm_lock::l_lvb_type, LASSERT, LDLM_ERROR, libcfs_debug_dumpstack, lustre_swab_lquota_lvb(), lustre_swab_ost_lvb, lustre_swab_ost_lvb_v1, ost_lvb::lvb_atime_ns, ost_lvb::lvb_ctime_ns, ost_lvb::lvb_mtime_ns, LVB_T_LAYOUT, LVB_T_LQUOTA, LVB_T_OST, RCL_CLIENT, req_capsule_client_get(), req_capsule_client_swab_get(), req_capsule_server_get(), req_capsule_server_sized_swab_get(), req_capsule_server_swab_get(), RETURN, RMF_DLM_LVB, and unlikely.
Referenced by ldlm_cli_enqueue_fini(), and ldlm_handle_cp_callback().
void ldlm_flock_policy_local_to_wire (const union ldlm_policy_data * lpolicy, union ldlm_wire_policy_data * wpolicy)
Definition at line 853 of file ldlm_flock.c.
References ldlm_flock::end, ldlm_policy_data::l_flock, ldlm_wire_policy_data::l_flock, ldlm_flock_wire::lfw_end, ldlm_flock_wire::lfw_owner, ldlm_flock_wire::lfw_pid, ldlm_flock_wire::lfw_start, ldlm_flock::owner, ldlm_flock::pid, and ldlm_flock::start.
void ldlm_flock_policy_wire_to_local (const union ldlm_wire_policy_data * wpolicy, union ldlm_policy_data * lpolicy)
Definition at line 843 of file ldlm_flock.c.
References ldlm_flock::end, ldlm_wire_policy_data::l_flock, ldlm_policy_data::l_flock, ldlm_flock_wire::lfw_end, ldlm_flock_wire::lfw_owner, ldlm_flock_wire::lfw_pid, ldlm_flock_wire::lfw_start, ldlm_flock::owner, ldlm_flock::pid, and ldlm_flock::start.
void ldlm_grant_lock (struct ldlm_lock * lock, struct list_head * work_list)
Perform lock granting bookkeeping.
Includes putting the lock into granted list and updating lock mode. NOTE: called by
ldlm_lock_enqueue
ldlm_reprocess_queue
ldlm_lock_convert
must be called with lr_lock held
Definition at line 1101 of file ldlm_lock.c.
References check_res_locked(), ENTRY, EXIT, ldlm_lock::l_completion_ast, ldlm_lock::l_granted_mode, ldlm_lock::l_req_mode, ldlm_lock::l_resource, LCK_NL, ldlm_add_ast_work_item(), LDLM_EXTENT, ldlm_extent_add_lock(), ldlm_grant_lock_with_skiplist(), LDLM_IBITS, ldlm_is_flock_deadlock, ldlm_is_test_lock, LDLM_PLAIN, ldlm_pool_add(), ldlm_res_to_ns(), ldlm_resource_add_lock(), ldlm_resource::lr_granted, ldlm_resource::lr_type, and RETURN_EXIT.
Referenced by ldlm_handle_cp_callback(), ldlm_lock_convert(), ldlm_lock_downgrade(), and ldlm_lock_enqueue().
void ldlm_handle_bl_callback (struct ldlm_namespace * ns, struct ldlm_lock_desc * ld, struct ldlm_lock * lock)
Callback handler for receiving incoming blocking ASTs.
This can only happen on client side.
Definition at line 1758 of file ldlm_lockd.c.
References CDEBUG, D_DLMTRACE, ENTRY, EXIT, ldlm_lock::l_ast_data, ldlm_lock::l_blocking_ast, ldlm_lock::l_readers, ldlm_lock::l_writers, LDLM_CB_BLOCKING, LDLM_DEBUG, ldlm_is_cancel_on_block, LDLM_LOCK_RELEASE, ldlm_set_cancel, ldlm_set_cbpending, lock_res_and_lock(), and unlock_res_and_lock().
Referenced by ldlm_bl_thread_blwi(), ldlm_callback_handler(), ldlm_handle_gl_callback(), and ldlm_lock_decref_internal().
void ldlm_ibits_policy_local_to_wire (const union ldlm_policy_data * lpolicy, union ldlm_wire_policy_data * wpolicy)
Definition at line 259 of file ldlm_inodebits.c.
References ldlm_inodebits::bits, ldlm_policy_data::l_inodebits, and ldlm_wire_policy_data::l_inodebits.
void ldlm_ibits_policy_wire_to_local (const union ldlm_wire_policy_data * wpolicy, union ldlm_policy_data * lpolicy)
Definition at line 252 of file ldlm_inodebits.c.
References ldlm_inodebits::bits, ldlm_wire_policy_data::l_inodebits, and ldlm_policy_data::l_inodebits.
int ldlm_init (void)
Definition at line 3154 of file ldlm_lockd.c.
References INIT_LIST_HEAD, LCK_MODE_NUM, ldlm_cli_active_namespace_list, ldlm_cli_inactive_namespace_list, ldlm_interval_slab, ldlm_interval_tree_slab, ldlm_lock_slab, LDLM_NAMESPACE_CLIENT, ldlm_namespace_lock(), LDLM_NAMESPACE_SERVER, ldlm_ref_mutex, ldlm_resource_slab, ldlm_srv_namespace_list, and SLAB_DESTROY_BY_RCU.
Referenced by ptlrpc_init().
int ldlm_init_flock_export (struct obd_export * exp)
Definition at line 936 of file ldlm_flock.c.
References cfs_hash_create(), CFS_HASH_DEFAULT, CFS_HASH_MAX_THETA, CFS_HASH_MIN_THETA, CFS_HASH_NBLK_CHANGE, obd_export::exp_client_uuid, obd_export::exp_flock_hash, obd_export::exp_obd, HASH_EXP_LOCK_BKT_BITS, HASH_EXP_LOCK_CUR_BITS, HASH_EXP_LOCK_MAX_BITS, LUSTRE_MDT_NAME, obd_device::obd_type, obd_uuid2str(), RETURN, and obd_type::typ_name.
Referenced by ldlm_init_export().
struct ldlm_interval* ldlm_interval_alloc (struct ldlm_lock * lock) [read]
Definition at line 836 of file ldlm_extent.c.
References ENTRY, INIT_LIST_HEAD, ldlm_lock::l_resource, LASSERT, LDLM_EXTENT, ldlm_interval_attach(), ldlm_interval::li_group, ldlm_resource::lr_type, OBD_SLAB_ALLOC_PTR_GFP, and RETURN.
Referenced by ldlm_lock_create().
void ldlm_interval_attach (struct ldlm_interval * n, struct ldlm_lock * l)
Definition at line 861 of file ldlm_extent.c.
References ldlm_lock::l_resource, ldlm_lock::l_sl_policy, ldlm_lock::l_tree_node, LASSERT, LDLM_EXTENT, ldlm_interval::li_group, list_add_tail(), and ldlm_resource::lr_type.
Referenced by ldlm_extent_add_lock(), ldlm_interval_alloc(), ldlm_lock_convert(), and ldlm_lock_enqueue().
struct ldlm_interval* ldlm_interval_detach (struct ldlm_lock * l) [read]
Definition at line 871 of file ldlm_extent.c.
References ldlm_lock::l_sl_policy, ldlm_lock::l_tree_node, LASSERT, ldlm_interval::li_group, list_del_init(), and list_empty().
Referenced by ldlm_extent_add_lock(), ldlm_extent_unlink_lock(), and ldlm_lock_put().
static struct ldlm_extent* ldlm_interval_extent (struct ldlm_interval * node) [static, read]
Definition at line 243 of file ldlm_internal.h.
References ldlm_policy_data::l_extent, ldlm_lock::l_policy_data, ldlm_lock::l_sl_policy, LASSERT, ldlm_interval::li_group, list_empty(), list_entry, and list_head::next.
void ldlm_interval_free (struct ldlm_interval * node)
Definition at line 851 of file ldlm_extent.c.
References interval_is_intree(), LASSERT, ldlm_interval::li_group, ldlm_interval::li_node, list_empty(), and OBD_SLAB_FREE.
Referenced by ldlm_extent_add_lock(), ldlm_extent_unlink_lock(), and ldlm_lock_put().
void ldlm_lock_add_to_lru (struct ldlm_lock * lock)
Adds LDLM lock lock to namespace LRU.
Obtains necessary LRU locks first.
Definition at line 298 of file ldlm_lock.c.
References ENTRY, EXIT, ldlm_lock_add_to_lru_nolock(), ldlm_lock_to_ns(), and ldlm_namespace::ns_lock.
Referenced by ldlm_lock_decref_internal().
void ldlm_lock_add_to_lru_nolock (struct ldlm_lock * lock)
Adds LDLM lock lock to namespace LRU.
Assumes LRU is already locked.
Definition at line 281 of file ldlm_lock.c.
References cfs_time_current(), ldlm_lock::l_last_used, ldlm_lock::l_lru, ldlm_lock::l_resource, LASSERT, ldlm_clear_skipped, LDLM_FLOCK, ldlm_lock_to_ns(), list_add_tail(), list_empty(), ldlm_resource::lr_type, ldlm_namespace::ns_nr_unused, and ldlm_namespace::ns_unused_list.
Referenced by ldlm_lock_add_to_lru(), and ldlm_lock_touch_in_lru().
void ldlm_lock_addref_internal (struct ldlm_lock * lock, enum ldlm_mode mode)
Add specified reader/writer reference to LDLM lock lock.
Locks LDLM lock and calls ldlm_lock_addref_internal_nolock to do the work. Only called for local locks.
Definition at line 786 of file ldlm_lock.c.
References ldlm_lock_addref_internal_nolock(), lock_res_and_lock(), and unlock_res_and_lock().
Referenced by ldlm_cli_enqueue(), and ldlm_lock_addref().
void ldlm_lock_addref_internal_nolock (struct ldlm_lock * lock, enum ldlm_mode mode)
Helper function.
Add specified reader/writer reference to LDLM lock lock. r/w reference type is determined by mode Removes lock from LRU if it is there. Assumes the LDLM lock is already locked.
Definition at line 735 of file ldlm_lock.c.
References ldlm_lock::l_readers, ldlm_lock::l_reference, ldlm_lock::l_writers, LCK_COS, LCK_CR, LCK_CW, LCK_EX, LCK_GROUP, LCK_NL, LCK_PR, LCK_PW, LDLM_DEBUG, LDLM_LOCK_GET, ldlm_lock_remove_from_lru, ldlm_lockname, and lu_ref_add_atomic().
Referenced by ldlm_cli_enqueue_local(), ldlm_lock_addref_internal(), ldlm_lock_addref_try(), ldlm_process_flock_lock(), ldlm_revalidate_lock_handle(), and lock_matches().
struct ldlm_lock* ldlm_lock_create (struct ldlm_namespace * ns, const struct ldlm_res_id * res_id, enum ldlm_type type, enum ldlm_mode mode, const struct ldlm_callback_suite * cbs, void * data, __u32 lvb_len, enum lvb_type lvb_type) [read]
Create and fill in new LDLM lock with specified properties.
Returns a referenced lock
Definition at line 1641 of file ldlm_lock.c.
References current_pid, ENTRY, GOTO, ldlm_lock::l_ast_data, ldlm_lock::l_blocking_ast, ldlm_lock::l_completion_ast, ldlm_lock::l_glimpse_ast, ldlm_lock::l_lvb_data, ldlm_lock::l_lvb_len, ldlm_lock::l_lvb_type, ldlm_lock::l_pid, ldlm_lock::l_req_mode, ldlm_lock::l_tree_node, ldlm_callback_suite::lcs_blocking, ldlm_callback_suite::lcs_completion, ldlm_callback_suite::lcs_glimpse, LDLM_EXTENT, ldlm_interval_alloc(), ldlm_lock_destroy(), ldlm_lock_new(), LDLM_LOCK_RELEASE, ldlm_resource_get(), ldlm_set_ns_srv, ns_is_server(), OBD_ALLOC_LARGE, OBD_FAIL_CHECK, OBD_FAIL_LDLM_NEW_LOCK, and RETURN.
Referenced by ldlm_cli_enqueue(), ldlm_cli_enqueue_local(), and ldlm_process_flock_lock().
void ldlm_lock_decref_internal (struct ldlm_lock * lock, enum ldlm_mode mode)
Removes reader/writer reference for LDLM lock lock.
Locks LDLM lock first. If the lock is determined to be client lock on a client and r/w refcount drops to zero and the lock is not blocked, the lock is added to LRU lock on the namespace. For blocked LDLM locks if r/w count drops to zero, blocking_ast is called.
Definition at line 827 of file ldlm_lock.c.
References CERROR, ENTRY, EXIT, exp_connect_cancelset(), ldlm_lock::l_conn_export, ldlm_lock::l_export, ldlm_lock::l_readers, ldlm_lock::l_req_mode, ldlm_lock::l_writers, LCF_ASYNC, LCK_GROUP, ldlm_bl_to_thread_lock(), ldlm_cancel_lru(), LDLM_DEBUG, ldlm_handle_bl_callback(), ldlm_is_atomic_cb, ldlm_is_bl_ast, ldlm_is_cbpending, ldlm_is_fail_loc, ldlm_is_local, ldlm_is_no_lru, ldlm_is_ns_srv, ldlm_lock_add_to_lru(), ldlm_lock_decref_internal_nolock(), LDLM_LOCK_GET, ldlm_lock_remove_from_lru, ldlm_lock_to_ns(), ldlm_set_cbpending, lock_res_and_lock(), ns_connect_lru_resize(), ns_is_client(), OBD_FAIL_LDLM_CP_BL_RACE, OBD_RACE, and unlock_res_and_lock().
Referenced by failed_lock_cleanup(), ldlm_lock_decref(), ldlm_lock_decref_and_cancel(), and ldlm_lock_match().
void ldlm_lock_decref_internal_nolock (struct ldlm_lock * lock, enum ldlm_mode mode)
Removes reader/writer reference for LDLM lock lock.
Assumes LDLM lock is already locked. only called in ldlm_flock_destroy and for local locks. Does NOT add lock to LRU if no r/w references left to accomodate flock locks that cannot be placed in LRU.
Definition at line 800 of file ldlm_lock.c.
References ldlm_lock::l_readers, ldlm_lock::l_reference, ldlm_lock::l_writers, LASSERT, LCK_COS, LCK_CR, LCK_CW, LCK_EX, LCK_GROUP, LCK_NL, LCK_PR, LCK_PW, LDLM_DEBUG, LDLM_LOCK_RELEASE, ldlm_lockname, and lu_ref_del().
Referenced by failed_lock_cleanup(), ldlm_flock_destroy(), and ldlm_lock_decref_internal().
void ldlm_lock_destroy_nolock (struct ldlm_lock * lock)
Destroys a LDLM lock lock that is already locked.
Definition at line 422 of file ldlm_lock.c.
References ENTRY, EXIT, ldlm_lock::l_reference, ldlm_lock_destroy_internal(), LDLM_LOCK_RELEASE, and lu_ref_del().
Referenced by failed_lock_cleanup(), ldlm_flock_destroy(), ldlm_lock_cancel(), ldlm_lock_enqueue(), and ldlm_process_flock_lock().
enum ldlm_error ldlm_lock_enqueue (struct ldlm_namespace * ns, struct ldlm_lock ** lockp, void * cookie, __u64 * flags)
Enqueue (request) a lock.
Does not block. As a result of enqueue the lock would be put into granted or waiting list.
If namespace has intent policy sent and the lock has LDLM_FL_HAS_INTENT flag set, skip all the enqueueing and delegate lock processing to intent policy function.
Definition at line 1708 of file ldlm_lock.c.
References ELDLM_LOCK_REPLACED, ELDLM_OK, ENTRY, GOTO, INIT_LIST_HEAD, ldlm_lock::l_flags, ldlm_lock::l_granted_mode, ldlm_lock::l_req_mode, ldlm_lock::l_resource, ldlm_lock::l_tree_node, LASSERT, LDLM_EXTENT, LDLM_FL_AST_DISCARD_DATA, LDLM_FL_BLOCK_CONV, LDLM_FL_BLOCK_GRANTED, LDLM_FL_BLOCK_WAIT, LDLM_FL_BLOCKED_MASK, LDLM_FL_COS_ENABLED, LDLM_FL_COS_INCOMPAT, LDLM_FL_HAS_INTENT, LDLM_FL_INTENT_ONLY, LDLM_FL_LOCK_CHANGED, LDLM_FL_NO_TIMEOUT, LDLM_FL_REPLAY, LDLM_FL_RESENT, LDLM_FL_TEST_LOCK, ldlm_grant_lock(), ldlm_interval_attach(), ldlm_interval_slab, ldlm_lock_destroy(), ldlm_lock_destroy_nolock(), LDLM_LOCK_RELEASE, ldlm_res_to_ns(), ldlm_resource_add_lock(), ldlm_resource_unlink_lock(), ldlm_set_ast_discard_data, ldlm_set_cos_enabled, ldlm_set_cos_incompat, ldlm_set_test_lock, ldlm_interval::li_group, lock_res_and_lock(), ldlm_resource::lr_converting, ldlm_resource::lr_type, ldlm_resource::lr_waiting, ns_is_client(), ldlm_namespace::ns_policy, OBD_SLAB_ALLOC_PTR_GFP, and RETURN.
Referenced by ldlm_cli_enqueue_fini(), and ldlm_cli_enqueue_local().
int ldlm_lock_remove_from_lru_check (struct ldlm_lock * lock, cfs_time_t last_use)
Removes LDLM lock lock from LRU.
Obtains the LRU lock first.
If last_use is non-zero, it will remove the lock from LRU only if it matches lock's l_last_used.
Return values:
0 if last_use is set, the lock is not in LRU list or last_use doesn't match lock's l_last_used; otherwise, the lock hasn't been in the LRU list.
1 the lock was in LRU list and removed.
Definition at line 259 of file ldlm_lock.c.
References ENTRY, ldlm_lock::l_last_used, ldlm_lock::l_lru, LASSERT, ldlm_is_ns_srv, ldlm_lock_remove_from_lru_nolock(), ldlm_lock_to_ns(), list_empty(), ldlm_namespace::ns_lock, and RETURN.
Referenced by ldlm_prepare_lru_list().
int ldlm_lock_remove_from_lru_nolock (struct ldlm_lock * lock)
Removes LDLM lock lock from LRU.
Assumes LRU is already locked.
Definition at line 233 of file ldlm_lock.c.
References ldlm_lock::l_lru, ldlm_lock::l_resource, LASSERT, LDLM_FLOCK, ldlm_lock_to_ns(), list_del_init(), list_empty(), ldlm_resource::lr_type, and ldlm_namespace::ns_nr_unused.
Referenced by ldlm_lock_remove_from_lru_check(), ldlm_lock_touch_in_lru(), and ldlm_prepare_lru_list().
void ldlm_lock_touch_in_lru (struct ldlm_lock * lock)
Moves LDLM lock lock that is already in namespace LRU to the tail of the LRU.
Performs necessary LRU locking
Definition at line 313 of file ldlm_lock.c.
References ENTRY, EXIT, ldlm_lock::l_lru, LASSERT, ldlm_is_ns_srv, ldlm_lock_add_to_lru_nolock(), ldlm_lock_remove_from_lru_nolock(), ldlm_lock_to_ns(), list_empty(), and ldlm_namespace::ns_lock.
Referenced by lock_matches().
struct ldlm_namespace* ldlm_namespace_first_locked (enum ldlm_side client) [read]
Should be called with ldlm_namespace_lock(client) taken.
Definition at line 1123 of file ldlm_resource.c.
References LASSERT, ldlm_namespace_list(), ldlm_namespace_lock(), list_empty(), and ldlm_namespace::ns_list_chain.
static struct list_head* ldlm_namespace_inactive_list (enum ldlm_side client) [static, read]
Definition at line 77 of file ldlm_internal.h.
References ldlm_cli_inactive_namespace_list, LDLM_NAMESPACE_SERVER, and ldlm_srv_namespace_list.
Referenced by ldlm_namespace_move_to_inactive_locked(), and ldlm_namespace_register().
static struct list_head* ldlm_namespace_list (enum ldlm_side client) [static, read]
Definition at line 70 of file ldlm_internal.h.
References ldlm_cli_active_namespace_list, LDLM_NAMESPACE_SERVER, and ldlm_srv_namespace_list.
Referenced by ldlm_cleanup(), ldlm_dump_all_namespaces(), ldlm_namespace_first_locked(), and ldlm_namespace_move_to_active_locked().
static struct mutex* ldlm_namespace_lock (enum ldlm_side client) [static, read]
Definition at line 83 of file ldlm_internal.h.
References ldlm_cli_namespace_lock, LDLM_NAMESPACE_SERVER, and ldlm_srv_namespace_lock.
Referenced by ldlm_dump_all_namespaces(), ldlm_init(), ldlm_namespace_first_locked(), ldlm_namespace_move_to_active_locked(), ldlm_namespace_move_to_inactive_locked(), ldlm_namespace_register(), ldlm_namespace_unregister(), and ldlm_resource_get().
void ldlm_namespace_move_to_active_locked (struct ldlm_namespace * ns, enum ldlm_side client)
Should be called with ldlm_namespace_lock(client) taken.
Definition at line 1104 of file ldlm_resource.c.
References LASSERT, ldlm_namespace_list(), ldlm_namespace_lock(), list_empty(), list_move_tail(), and ldlm_namespace::ns_list_chain.
Referenced by ldlm_resource_get().
void ldlm_namespace_move_to_inactive_locked (struct ldlm_namespace * ns, enum ldlm_side client)
Should be called with ldlm_namespace_lock(client) taken.
Definition at line 1113 of file ldlm_resource.c.
References LASSERT, ldlm_namespace_inactive_list(), ldlm_namespace_lock(), list_empty(), list_move_tail(), and ldlm_namespace::ns_list_chain.
static void ldlm_namespace_nr_dec (enum ldlm_side client) [inline, static]
Definition at line 62 of file ldlm_internal.h.
References ldlm_cli_namespace_nr, LDLM_NAMESPACE_SERVER, and ldlm_srv_namespace_nr.
Referenced by ldlm_namespace_unregister().
static void ldlm_namespace_nr_inc (enum ldlm_side client) [inline, static]
Definition at line 54 of file ldlm_internal.h.
References ldlm_cli_namespace_nr, LDLM_NAMESPACE_SERVER, and ldlm_srv_namespace_nr.
Referenced by ldlm_namespace_register().
static int ldlm_namespace_nr_read (enum ldlm_side client) [inline, static]
Definition at line 48 of file ldlm_internal.h.
References ldlm_cli_namespace_nr, LDLM_NAMESPACE_SERVER, and ldlm_srv_namespace_nr.
Referenced by ldlm_namespace_new().
static int ldlm_ns_empty (struct ldlm_namespace * ns) [inline, static]
Definition at line 90 of file ldlm_internal.h.
References ldlm_namespace::ns_bref.
void ldlm_plain_policy_local_to_wire (const union ldlm_policy_data * lpolicy, union ldlm_wire_policy_data * wpolicy)
Definition at line 198 of file ldlm_plain.c.
void ldlm_plain_policy_wire_to_local (const union ldlm_wire_policy_data * wpolicy, union ldlm_policy_data * lpolicy)
Definition at line 192 of file ldlm_plain.c.
int ldlm_process_flock_lock (struct ldlm_lock * req, __u64 * flags, int first_enq, enum ldlm_error * err, struct list_head * work_list)
Process a granting attempt for flock lock.
Must be called under ns lock held.
This function looks for any conflicts for lock in the granted or waiting queues. The lock is granted if no conflicts are found in either queue.
It is also responsible for splitting a lock if a portion of the lock is released.
If first_enq is 0 (ie, called from ldlm_reprocess_queue):
blocking ASTs have already been sent
If first_enq is 1 (ie, called from ldlm_lock_enqueue):
blocking ASTs have not been sent yet, so list of conflicting locks would be collected and ASTs sent.
Definition at line 289 of file ldlm_flock.c.
References CDEBUG, CERROR, cfs_hash_add(), class_export_lock_get, D_DLMTRACE, D_INFO, ELDLM_OK, ldlm_flock::end, ENTRY, obd_export::exp_lock_hash, GOTO, hlist_unhashed(), INIT_LIST_HEAD, ldlm_lock::l_blocking_ast, ldlm_lock::l_completion_ast, ldlm_lock::l_conn_export, ldlm_lock::l_exp_hash, ldlm_lock::l_export, ldlm_policy_data::l_flock, ldlm_lock::l_granted_mode, ldlm_lock::l_policy_data, ldlm_lock::l_remote_handle, ldlm_lock::l_req_mode, ldlm_lock::l_res_link, ldlm_lock::l_resource, LASSERT, LBUG, LCK_NL, ldlm_add_ast_work_item(), LDLM_FL_BLOCK_GRANTED, LDLM_FL_BLOCK_NOWAIT, LDLM_FL_LOCK_CHANGED, LDLM_FL_TEST_LOCK, LDLM_FL_WAIT_NOREPROC, LDLM_FLOCK, ldlm_flock_blocking_ast(), ldlm_flock_blocking_link(), ldlm_flock_blocking_unlink(), ldlm_flock_cancel_on_deadlock(), ldlm_flock_deadlock(), ldlm_flock_destroy(), ldlm_flocks_overlap(), LDLM_ITER_CONTINUE, LDLM_ITER_STOP, ldlm_lock_addref_internal_nolock(), ldlm_lock_create(), ldlm_lock_destroy_nolock(), LDLM_LOCK_RELEASE, ldlm_res_to_ns(), ldlm_resource_add_lock(), ldlm_resource_dump(), ldlm_run_ast_work(), ldlm_same_flock_owner(), LDLM_WORK_CP_AST, list_del_init(), list_entry, list_for_each, list_for_remaining_safe, lock_res_and_lock(), lockmode_compat(), lockmode_verify(), LPU64, LPX64, ldlm_resource::lr_granted, ldlm_resource::lr_name, ldlm_resource::lr_waiting, LVB_T_NONE, mode, ns_is_client(), OBD_OBJECT_EOF, ldlm_flock::owner, ldlm_flock::pid, RETURN, ldlm_flock::start, and unlock_res_and_lock().
Referenced by ldlm_flock_completion_ast().
void ldlm_reclaim_add (struct ldlm_lock * lock)
Definition at line 392 of file ldlm_reclaim.c.
void ldlm_reclaim_cleanup (void)
Definition at line 405 of file ldlm_reclaim.c.
Referenced by ldlm_cleanup().
void ldlm_reclaim_del (struct ldlm_lock * lock)
Definition at line 396 of file ldlm_reclaim.c.
bool ldlm_reclaim_full (void)
Definition at line 387 of file ldlm_reclaim.c.
int ldlm_reclaim_setup (void)
Definition at line 400 of file ldlm_reclaim.c.
Referenced by ldlm_setup().
void ldlm_resource_insert_lock_after (struct ldlm_lock * original, struct ldlm_lock * new)
Insert a lock into resource after specified lock.
Obtain resource description from the lock we are inserting after.
Definition at line 1345 of file ldlm_resource.c.
References CDEBUG, check_res_locked(), D_INFO, D_OTHER, ldlm_lock::l_res_link, ldlm_lock::l_resource, LASSERT, LDLM_DEBUG, ldlm_is_destroyed, ldlm_resource_dump(), list_add(), and list_empty().
int ldlm_run_ast_work (struct ldlm_namespace * ns, struct list_head * rpc_list, ldlm_desc_ast_t ast_type)
Process list of locks in need of ASTs being sent.
Used on server to send multiple ASTs together instead of sending one by one.
Definition at line 2050 of file ldlm_lock.c.
References GOTO, LBUG, LDLM_BL_CALLBACK, LDLM_CP_CALLBACK, LDLM_GL_CALLBACK, LDLM_WORK_BL_AST, ldlm_work_bl_ast_lock(), LDLM_WORK_CP_AST, ldlm_work_cp_ast_lock(), LDLM_WORK_GL_AST, ldlm_work_gl_ast_lock(), LDLM_WORK_REVOKE_AST, ldlm_work_revoke_ast_lock(), ldlm_cb_set_arg::list, list_empty(), ldlm_namespace::ns_max_parallel_ast, OBD_ALLOC_PTR, OBD_FREE_PTR, ptlrpc_prep_fcset(), ptlrpc_set_destroy(), ptlrpc_set_wait(), ldlm_cb_set_arg::restart, RETURN, ldlm_cb_set_arg::set, and ldlm_cb_set_arg::type.
Referenced by ldlm_handle_cp_callback(), ldlm_process_flock_lock(), and ldlm_reprocess_all().
int ldlm_work_gl_ast_lock (struct ptlrpc_request_set * rqset, void * opaq)
Process a call to glimpse AST callback for a lock in ast_work list.
Definition at line 2012 of file ldlm_lock.c.
References ENTRY, ldlm_glimpse_work::gl_desc, ldlm_cb_set_arg::gl_desc, ldlm_glimpse_work::gl_flags, ldlm_glimpse_work::gl_list, ldlm_glimpse_work::gl_lock, ldlm_lock::l_glimpse_ast, LDLM_GL_WORK_NOFREE, LDLM_LOCK_RELEASE, ldlm_cb_set_arg::list, list_del_init(), list_empty(), list_entry, list_head::next, OBD_FREE_PTR, and RETURN.
Referenced by ldlm_run_ast_work().
Variable Documentation
unsigned int ldlm_cancel_unused_locks_before_replay
Definition at line 75 of file ldlm_request.c.
Referenced by ldlm_replay_locks().
struct list_head ldlm_cli_active_namespace_list
Definition at line 61 of file ldlm_resource.c.
Referenced by ldlm_init(), and ldlm_namespace_list().
struct list_head ldlm_cli_inactive_namespace_list
Definition at line 63 of file ldlm_resource.c.
Referenced by ldlm_init(), and ldlm_namespace_inactive_list().
struct mutex ldlm_cli_namespace_lock
Definition at line 57 of file ldlm_resource.c.
Referenced by ldlm_namespace_lock().
int ldlm_cli_namespace_nr
Definition at line 52 of file ldlm_resource.c.
Referenced by ldlm_namespace_nr_dec(), ldlm_namespace_nr_inc(), and ldlm_namespace_nr_read().
unsigned int ldlm_enqueue_min
Definition at line 70 of file ldlm_request.c.
Referenced by ldlm_cp_timeout(), and ldlm_namespace_new().
struct kmem_cache* ldlm_interval_slab
Definition at line 835 of file ldlm_extent.c.
Referenced by ldlm_exit(), ldlm_init(), ldlm_lock_convert(), and ldlm_lock_enqueue().
struct kmem_cache* ldlm_interval_tree_slab
Definition at line 49 of file ldlm_resource.c.
Referenced by ldlm_exit(), ldlm_init(), ldlm_resource_get(), ldlm_resource_new(), and ldlm_resource_putref().
struct kmem_cache* ldlm_lock_slab
Definition at line 48 of file ldlm_resource.c.
Referenced by ldlm_exit(), ldlm_init(), ldlm_lock_new(), and lock_handle_free().
struct kmem_cache* ldlm_resource_slab
Definition at line 48 of file ldlm_resource.c.
Referenced by ldlm_exit(), ldlm_init(), ldlm_resource_get(), ldlm_resource_new(), and ldlm_resource_putref().
struct list_head ldlm_srv_namespace_list
Definition at line 55 of file ldlm_resource.c.
Referenced by ldlm_init(), ldlm_namespace_inactive_list(), and ldlm_namespace_list().
struct mutex ldlm_srv_namespace_lock
Definition at line 54 of file ldlm_resource.c.
Referenced by ldlm_namespace_lock().
int ldlm_srv_namespace_nr
Definition at line 51 of file ldlm_resource.c.
Referenced by ldlm_namespace_nr_dec(), ldlm_namespace_nr_inc(), and ldlm_namespace_nr_read().
struct proc_dir_entry* ldlm_svc_proc_dir
Definition at line 67 of file ldlm_resource.c.
Referenced by ldlm_setup().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.