Lustre: lustre/ldlm/ldlm_lockd.c File Reference
lustre/ldlm/ldlm_lockd.c File Reference
#include <linux/kthread.h>
#include <libcfs/libcfs.h>
#include <lustre_dlm.h>
#include <obd_class.h>
#include <libcfs/list.h>
#include "ldlm_internal.h"
Data Structures
struct ldlm_cb_async_args
struct ldlm_bl_pool
struct ldlm_bl_work_item
struct ldlm_bl_thread_data
Defines
#define DEBUG_SUBSYSTEM S_LDLM
#define ELT_STOPPED 0
#define ELT_READY 1
#define ELT_TERMINATE 2
Functions
module_param (ldlm_num_threads, int, 0444)
MODULE_PARM_DESC (ldlm_num_threads,"number of DLM service threads to start")
module_param (ldlm_cpts, charp, 0444)
MODULE_PARM_DESC (ldlm_cpts,"CPU partitions ldlm threads should run on")
static cfs_time_t round_timeout (cfs_time_t timeout)
static unsigned int ldlm_get_rq_timeout (void)
int ldlm_del_waiting_lock (struct ldlm_lock *lock)
int ldlm_refresh_waiting_lock (struct ldlm_lock *lock, int timeout)
void ldlm_handle_bl_callback (struct ldlm_namespace *ns, struct ldlm_lock_desc *ld, struct ldlm_lock *lock)
Callback handler for receiving incoming blocking ASTs.
static void ldlm_handle_cp_callback (struct ptlrpc_request *req, struct ldlm_namespace *ns, struct ldlm_request *dlm_req, struct ldlm_lock *lock)
Callback handler for receiving incoming completion ASTs.
static void ldlm_handle_gl_callback (struct ptlrpc_request *req, struct ldlm_namespace *ns, struct ldlm_request *dlm_req, struct ldlm_lock *lock)
Callback handler for receiving incoming glimpse ASTs.
static int ldlm_callback_reply (struct ptlrpc_request *req, int rc)
static int __ldlm_bl_to_thread (struct ldlm_bl_work_item *blwi, enum ldlm_cancel_flags cancel_flags)
static void init_blwi (struct ldlm_bl_work_item *blwi, struct ldlm_namespace *ns, struct ldlm_lock_desc *ld, struct list_head *cancels, int count, struct ldlm_lock *lock, enum ldlm_cancel_flags cancel_flags)
static int ldlm_bl_to_thread (struct ldlm_namespace *ns, struct ldlm_lock_desc *ld, struct ldlm_lock *lock, struct list_head *cancels, int count, enum ldlm_cancel_flags cancel_flags)
Queues a list of locks cancels containing count locks for later processing by a blocking thread.
int ldlm_bl_to_thread_lock (struct ldlm_namespace *ns, struct ldlm_lock_desc *ld, struct ldlm_lock *lock)
int ldlm_bl_to_thread_list (struct ldlm_namespace *ns, struct ldlm_lock_desc *ld, struct list_head *cancels, int count, enum ldlm_cancel_flags cancel_flags)
int ldlm_bl_thread_wakeup (void)
static int ldlm_handle_setinfo (struct ptlrpc_request *req)
static void ldlm_callback_errmsg (struct ptlrpc_request *req, const char *msg, int rc, const struct lustre_handle *handle)
static int ldlm_callback_handler (struct ptlrpc_request *req)
static int ldlm_bl_get_work (struct ldlm_bl_pool *blp, struct ldlm_bl_work_item **p_blwi, struct obd_export **p_exp)
static int ldlm_bl_thread_main (void *arg)
Main blocking requests processing thread.
static int ldlm_bl_thread_start (struct ldlm_bl_pool *blp, bool check_busy)
static int ldlm_bl_thread_need_create (struct ldlm_bl_pool *blp, struct ldlm_bl_work_item *blwi)
static int ldlm_bl_thread_blwi (struct ldlm_bl_pool *blp, struct ldlm_bl_work_item *blwi)
static int ldlm_bl_thread_exports (struct ldlm_bl_pool *blp, struct obd_export *exp)
Cancel stale locks on export.
static int ldlm_setup (void)
static int ldlm_cleanup (void)
int ldlm_get_ref (void)
void ldlm_put_ref (void)
static unsigned ldlm_export_lock_hash (struct cfs_hash *hs, const void *key, unsigned mask)
static void * ldlm_export_lock_key (struct hlist_node *hnode)
static void ldlm_export_lock_keycpy (struct hlist_node *hnode, void *key)
static int ldlm_export_lock_keycmp (const void *key, struct hlist_node *hnode)
static void * ldlm_export_lock_object (struct hlist_node *hnode)
static void ldlm_export_lock_get (struct cfs_hash *hs, struct hlist_node *hnode)
static void ldlm_export_lock_put (struct cfs_hash *hs, struct hlist_node *hnode)
int ldlm_init_export (struct obd_export *exp)
void ldlm_destroy_export (struct obd_export *exp)
int ldlm_init (void)
void ldlm_exit (void)
Variables
static int ldlm_num_threads
static char * ldlm_cpts
static struct mutex ldlm_ref_mutex
static int ldlm_refcount
static struct ldlm_state * ldlm_state
static struct cfs_hash_ops ldlm_export_lock_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_LDLM
Definition at line 42 of file ldlm_lockd.c.
#define ELT_READY 1
Definition at line 86 of file ldlm_lockd.c.
Referenced by ldlm_setup().
#define ELT_STOPPED 0
Definition at line 85 of file ldlm_lockd.c.
Referenced by ldlm_cleanup(), and ldlm_setup().
#define ELT_TERMINATE 2
Definition at line 87 of file ldlm_lockd.c.
Referenced by ldlm_cleanup().
Function Documentation
static int __ldlm_bl_to_thread (struct ldlm_bl_work_item * blwi, enum ldlm_cancel_flags cancel_flags) [static]
Definition at line 1980 of file ldlm_lockd.c.
References ldlm_bl_pool::blp_list, ldlm_bl_pool::blp_lock, ldlm_bl_pool::blp_prio_list, ldlm_bl_pool::blp_waitq, ldlm_bl_work_item::blwi_comp, ldlm_bl_work_item::blwi_entry, ldlm_bl_work_item::blwi_lock, ENTRY, LCF_ASYNC, ldlm_state::ldlm_bl_pool, ldlm_is_discard_data, list_add_tail(), and RETURN.
Referenced by ldlm_bl_to_thread().
static void init_blwi (struct ldlm_bl_work_item * blwi, struct ldlm_namespace * ns, struct ldlm_lock_desc * ld, struct list_head * cancels, int count, struct ldlm_lock * lock, enum ldlm_cancel_flags cancel_flags) [inline, static]
Definition at line 2007 of file ldlm_lockd.c.
References ldlm_bl_work_item::blwi_comp, ldlm_bl_work_item::blwi_count, ldlm_bl_work_item::blwi_flags, ldlm_bl_work_item::blwi_head, ldlm_bl_work_item::blwi_ld, ldlm_bl_work_item::blwi_lock, ldlm_bl_work_item::blwi_mem_pressure, ldlm_bl_work_item::blwi_ns, INIT_LIST_HEAD, list_add(), list_del_init(), and memory_pressure_get().
Referenced by ldlm_bl_to_thread().
static int ldlm_bl_get_work (struct ldlm_bl_pool * blp, struct ldlm_bl_work_item ** p_blwi, struct obd_export ** p_exp) [static]
Definition at line 2554 of file ldlm_lockd.c.
References ldlm_bl_pool::blp_list, ldlm_bl_pool::blp_lock, ldlm_bl_pool::blp_num_threads, ldlm_bl_pool::blp_prio_list, ldlm_bl_work_item::blwi_entry, list_del(), list_empty(), list_entry, list_head::next, obd_stale_export_get(), and obd_stale_export_put().
Referenced by ldlm_bl_thread_main().
static int ldlm_bl_thread_blwi (struct ldlm_bl_pool * blp, struct ldlm_bl_work_item * blwi) [static]
Definition at line 2662 of file ldlm_lockd.c.
References ldlm_bl_work_item::blwi_comp, ldlm_bl_work_item::blwi_count, ldlm_bl_work_item::blwi_flags, ldlm_bl_work_item::blwi_head, ldlm_bl_work_item::blwi_ld, ldlm_bl_work_item::blwi_lock, ldlm_bl_work_item::blwi_mem_pressure, ldlm_bl_work_item::blwi_ns, ENTRY, LCF_ASYNC, LCF_BL_AST, ldlm_cli_cancel_list(), ldlm_cli_cancel_list_local(), ldlm_handle_bl_callback(), LDLM_ITER_STOP, memory_pressure_clr(), memory_pressure_set(), OBD_FAIL_LDLM_PAUSE_CANCEL2, OBD_FAIL_TIMEOUT, OBD_FREE, and RETURN.
Referenced by ldlm_bl_thread_main().
static int ldlm_bl_thread_exports (struct ldlm_bl_pool * blp, struct obd_export * exp) [static]
Cancel stale locks on export.
Cancel blocked locks first. If the given export has blocked locks, the next in the list may have them too, thus cancel not blocked locks only if the current export has no blocked locks.
Definition at line 2708 of file ldlm_lockd.c.
References ENTRY, ldlm_export_cancel_blocked_locks(), ldlm_export_cancel_locks(), OBD_FAIL_LDLM_BL_EVICT, OBD_FAIL_TIMEOUT, obd_stale_export_put(), and RETURN.
Referenced by ldlm_bl_thread_main().
static int ldlm_bl_thread_main (void * arg) [static]
Main blocking requests processing thread.
Callers put locks into its queue by calling ldlm_bl_to_thread. This thread in the end ends up doing actual call to ->l_blocking_ast for queued locks.
Definition at line 2733 of file ldlm_lockd.c.
References ldlm_bl_pool::blp_busy_threads, ldlm_bl_pool::blp_comp, ldlm_bl_pool::blp_num_threads, ldlm_bl_pool::blp_waitq, ldlm_bl_thread_data::bltd_blp, ldlm_bl_thread_data::bltd_comp, ENTRY, l_wait_event_exclusive, ldlm_bl_get_work(), ldlm_bl_thread_blwi(), ldlm_bl_thread_exports(), ldlm_bl_thread_need_create(), ldlm_bl_thread_start(), LDLM_ITER_STOP, and RETURN.
Referenced by ldlm_bl_thread_start().
static int ldlm_bl_thread_need_create (struct ldlm_bl_pool * blp, struct ldlm_bl_work_item * blwi) [static]
Definition at line 2645 of file ldlm_lockd.c.
References ldlm_bl_pool::blp_busy_threads, ldlm_bl_pool::blp_max_threads, ldlm_bl_pool::blp_num_threads, ldlm_bl_work_item::blwi_mem_pressure, and ldlm_bl_work_item::blwi_ns.
Referenced by ldlm_bl_thread_main().
static int ldlm_bl_thread_start (struct ldlm_bl_pool * blp, bool check_busy) [static]
Definition at line 2611 of file ldlm_lockd.c.
References ldlm_bl_pool::blp_busy_threads, ldlm_bl_pool::blp_max_threads, ldlm_bl_pool::blp_num_threads, ldlm_bl_thread_data::bltd_blp, ldlm_bl_thread_data::bltd_comp, ldlm_bl_thread_data::bltd_num, CERROR, LASSERTF, and ldlm_bl_thread_main().
Referenced by ldlm_bl_thread_main(), and ldlm_setup().
int ldlm_bl_thread_wakeup (void)
Definition at line 2088 of file ldlm_lockd.c.
References ldlm_bl_pool::blp_waitq, and ldlm_state::ldlm_bl_pool.
static int ldlm_bl_to_thread (struct ldlm_namespace * ns, struct ldlm_lock_desc * ld, struct ldlm_lock * lock, struct list_head * cancels, int count, enum ldlm_cancel_flags cancel_flags) [static]
Queues a list of locks cancels containing count locks for later processing by a blocking thread.
If count is zero, then the lock referenced as lock is queued instead.
The blocking thread would then call ->l_blocking_ast callback in the lock. If list addition fails an error is returned and caller is supposed to call ->l_blocking_ast itself.
Definition at line 2042 of file ldlm_lockd.c.
References __ldlm_bl_to_thread(), ENTRY, init_blwi(), LCF_ASYNC, OBD_ALLOC, and RETURN.
Referenced by ldlm_bl_to_thread_list(), and ldlm_bl_to_thread_lock().
int ldlm_bl_to_thread_list (struct ldlm_namespace * ns, struct ldlm_lock_desc * ld, struct list_head * cancels, int count, enum ldlm_cancel_flags cancel_flags)
Definition at line 2081 of file ldlm_lockd.c.
References ldlm_bl_to_thread().
Referenced by ldlm_cancel_lru().
int ldlm_bl_to_thread_lock (struct ldlm_namespace * ns, struct ldlm_lock_desc * ld, struct ldlm_lock * lock)
Definition at line 2075 of file ldlm_lockd.c.
References LCF_ASYNC, and ldlm_bl_to_thread().
Referenced by ldlm_callback_handler(), ldlm_handle_gl_callback(), and ldlm_lock_decref_internal().
static void ldlm_callback_errmsg (struct ptlrpc_request * req, const char * msg, int rc, const struct lustre_handle * handle) [inline, static]
Definition at line 2138 of file ldlm_lockd.c.
References lustre_handle::cookie, CWARN, D_DLMTRACE, D_WARNING, DEBUG_REQ, libcfs_id2str(), LPX64, ptlrpc_request::rq_no_reply, and ptlrpc_request::rq_peer.
Referenced by ldlm_callback_handler().
static int ldlm_callback_handler (struct ptlrpc_request * req) [static]
Definition at line 2153 of file ldlm_lockd.c.
References CDEBUG, CERROR, cfs_fail_err, lustre_handle::cookie, D_DLMTRACE, D_INODE, ENTRY, obd_export::exp_obd, ldlm_lock::l_flags, LASSERT, LBUG, LDLM_BL_CALLBACK, ldlm_bl_to_thread_lock(), ldlm_callback_errmsg(), ldlm_callback_reply(), ldlm_cli_cancel(), LDLM_CP_CALLBACK, LDLM_DEBUG, LDLM_FL_AST_MASK, ldlm_flags_from_wire, LDLM_GL_CALLBACK, ldlm_handle2lock_long(), ldlm_handle_bl_callback(), ldlm_handle_cp_callback(), ldlm_handle_gl_callback(), ldlm_handle_setinfo(), ldlm_is_bl_done, ldlm_is_cancel_on_block, ldlm_is_canceling, ldlm_is_fail_loc, ldlm_is_failed, LDLM_LOCK_RELEASE, ldlm_lock_remove_from_lru, ldlm_set_bl_ast, LDLM_SET_INFO, llog_origin_handle_close(), LLOG_ORIGIN_HANDLE_CLOSE, LLOG_ORIGIN_HANDLE_CREATE, llog_origin_handle_next_block(), LLOG_ORIGIN_HANDLE_NEXT_BLOCK, llog_origin_handle_open(), llog_origin_handle_read_header(), LLOG_ORIGIN_HANDLE_READ_HEADER, ldlm_request::lock_desc, ldlm_request::lock_flags, ldlm_request::lock_handle, lock_res_and_lock(), LPX64, lustre_msg_get_opc(), OBD_FAIL_CHECK, OBD_FAIL_LDLM_BL_CALLBACK_NET, OBD_FAIL_LDLM_CANCEL_BL_CB_RACE, OBD_FAIL_LDLM_CP_BL_RACE, OBD_FAIL_LDLM_CP_CALLBACK_NET, OBD_FAIL_LDLM_GL_CALLBACK_NET, OBD_FAIL_OBD_LOGD_NET, obd_device::obd_namespace, OBD_RACE, RCL_SERVER, req_capsule_client_get(), req_capsule_extend(), req_capsule_init(), req_capsule_set(), RETURN, RMF_DLM_REQ, ptlrpc_request::rq_export, ptlrpc_request::rq_no_reply, ptlrpc_request::rq_pill, ptlrpc_request::rq_reqmsg, RQF_LDLM_BL_CALLBACK, RQF_LDLM_CALLBACK, RQF_LDLM_CP_CALLBACK, RQF_LDLM_GL_CALLBACK, RQF_LLOG_ORIGIN_HANDLE_CREATE, RQF_LLOG_ORIGIN_HANDLE_NEXT_BLOCK, RQF_LLOG_ORIGIN_HANDLE_READ_HEADER, SEC_CTX_FINI, and unlock_res_and_lock().
Referenced by ldlm_setup().
static int ldlm_callback_reply (struct ptlrpc_request * req, int rc) [static]
Definition at line 1966 of file ldlm_lockd.c.
References lustre_pack_reply(), ptlrpc_reply(), ptlrpc_request::rq_no_reply, ptlrpc_request::rq_packed_final, and ptlrpc_request::rq_status.
Referenced by ldlm_callback_handler().
static int ldlm_cleanup (void) [static]
Definition at line 3096 of file ldlm_lockd.c.
References ldlm_bl_pool::blp_comp, ldlm_bl_pool::blp_list, ldlm_bl_pool::blp_lock, ldlm_bl_pool::blp_num_threads, ldlm_bl_pool::blp_waitq, ldlm_bl_work_item::blwi_entry, ldlm_bl_work_item::blwi_ns, CERROR, D_DLMTRACE, ELT_STOPPED, ELT_TERMINATE, ENTRY, ldlm_state::ldlm_bl_pool, ldlm_state::ldlm_cancel_service, ldlm_state::ldlm_cb_service, ldlm_dump_all_namespaces(), LDLM_NAMESPACE_CLIENT, ldlm_namespace_list(), LDLM_NAMESPACE_SERVER, ldlm_pools_fini(), ldlm_proc_cleanup(), ldlm_reclaim_cleanup(), list_add_tail(), list_empty(), OBD_FREE, ptlrpc_unregister_service(), and RETURN.
Referenced by ldlm_put_ref(), and ldlm_setup().
void ldlm_exit (void)
Definition at line 3203 of file ldlm_lockd.c.
References CERROR, ldlm_interval_slab, ldlm_interval_tree_slab, ldlm_lock_slab, ldlm_refcount, and ldlm_resource_slab.
Referenced by ptlrpc_exit(), and ptlrpc_init().
static void ldlm_export_lock_get (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 2856 of file ldlm_lockd.c.
References hlist_entry, ldlm_lock::l_exp_hash, and LDLM_LOCK_GET.
static unsigned ldlm_export_lock_hash (struct cfs_hash * hs, const void * key, unsigned mask) [static]
Definition at line 2820 of file ldlm_lockd.c.
References cfs_hash_u64_hash().
static void* ldlm_export_lock_key (struct hlist_node * hnode) [static]
Definition at line 2826 of file ldlm_lockd.c.
References hlist_entry, ldlm_lock::l_exp_hash, and ldlm_lock::l_remote_handle.
Referenced by ldlm_export_lock_keycmp().
static int ldlm_export_lock_keycmp (const void * key, struct hlist_node * hnode) [static]
Definition at line 2844 of file ldlm_lockd.c.
References ldlm_export_lock_key(), and lustre_handle_equal().
static void ldlm_export_lock_keycpy (struct hlist_node * hnode, void * key) [static]
Definition at line 2835 of file ldlm_lockd.c.
References hlist_entry, ldlm_lock::l_exp_hash, and ldlm_lock::l_remote_handle.
static void* ldlm_export_lock_object (struct hlist_node * hnode) [static]
Definition at line 2850 of file ldlm_lockd.c.
References hlist_entry.
static void ldlm_export_lock_put (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 2865 of file ldlm_lockd.c.
References hlist_entry, ldlm_lock::l_exp_hash, and LDLM_LOCK_RELEASE.
static unsigned int ldlm_get_rq_timeout (void) [inline, static]
Definition at line 77 of file ldlm_lockd.c.
References ldlm_timeout, obd_timeout, and timeout.
void ldlm_handle_bl_callback (struct ldlm_namespace * ns, struct ldlm_lock_desc * ld, struct ldlm_lock * lock)
Callback handler for receiving incoming blocking ASTs.
This can only happen on client side.
Definition at line 1758 of file ldlm_lockd.c.
References CDEBUG, D_DLMTRACE, ENTRY, EXIT, ldlm_lock::l_ast_data, ldlm_lock::l_blocking_ast, ldlm_lock::l_readers, ldlm_lock::l_writers, LDLM_CB_BLOCKING, LDLM_DEBUG, ldlm_is_cancel_on_block, LDLM_LOCK_RELEASE, ldlm_set_cancel, ldlm_set_cbpending, lock_res_and_lock(), and unlock_res_and_lock().
Referenced by ldlm_bl_thread_blwi(), ldlm_callback_handler(), ldlm_handle_gl_callback(), and ldlm_lock_decref_internal().
static void ldlm_handle_cp_callback (struct ptlrpc_request * req, struct ldlm_namespace * ns, struct ldlm_request * dlm_req, struct ldlm_lock * lock) [static]
Callback handler for receiving incoming completion ASTs.
This only can happen on client side.
Definition at line 1796 of file ldlm_lockd.c.
References CERROR, cfs_time_seconds(), ENTRY, GOTO, INIT_LIST_HEAD, ldlm_lock::l_flags, ldlm_lock_desc::l_granted_mode, ldlm_lock::l_granted_mode, ldlm_lock::l_lvb_data, ldlm_lock::l_lvb_len, ldlm_lock::l_policy_data, ldlm_lock_desc::l_policy_data, ldlm_lock::l_req_mode, ldlm_lock_desc::l_resource, ldlm_lock::l_resource, ldlm_lock::l_waitq, LASSERT, ldlm_convert_policy_to_local(), LDLM_DEBUG, LDLM_DEBUG_NOLOCK, LDLM_ERROR, ldlm_fill_lvb(), LDLM_FL_AST_SENT, LDLM_FL_BL_AST, LDLM_FL_CBPENDING, ldlm_grant_lock(), ldlm_is_destroyed, ldlm_lock_change_resource(), LDLM_LOCK_RELEASE, ldlm_lock_remove_from_lru, LDLM_PLAIN, ldlm_resource_unlink_lock(), ldlm_run_ast_work(), ldlm_set_failed, LDLM_WORK_CP_AST, ldlm_request::lock_desc, ldlm_request::lock_flags, lock_res_and_lock(), ldlm_resource::lr_name, ldlm_resource_desc::lr_name, ldlm_resource_desc::lr_type, ldlm_resource::lr_type, OBD_FAIL_CHECK, OBD_FAIL_LDLM_CANCEL_BL_CB_RACE, OBD_FAIL_OSC_CP_ENQ_RACE, OBD_FAIL_TIMEOUT, RCL_CLIENT, req_capsule_get_size(), RMF_DLM_LVB, ptlrpc_request::rq_export, ptlrpc_request::rq_pill, unlikely, and unlock_res_and_lock().
Referenced by ldlm_callback_handler().
static void ldlm_handle_gl_callback (struct ptlrpc_request * req, struct ldlm_namespace * ns, struct ldlm_request * dlm_req, struct ldlm_lock * lock) [static]
Callback handler for receiving incoming glimpse ASTs.
This only can happen on client side. After handling the glimpse AST we also consider dropping the lock here if it is unused locally for a long time.
Definition at line 1928 of file ldlm_lockd.c.
References cfs_time_add(), cfs_time_after(), cfs_time_current(), cfs_time_seconds(), ENTRY, EXIT, ldlm_lock::l_glimpse_ast, ldlm_lock::l_granted_mode, ldlm_lock::l_last_used, ldlm_lock::l_readers, ldlm_lock::l_writers, LCK_PW, ldlm_bl_to_thread_lock(), LDLM_DEBUG, ldlm_handle_bl_callback(), LDLM_LOCK_RELEASE, lock_res_and_lock(), ptlrpc_error(), ptlrpc_reply(), ptlrpc_request::rq_repmsg, ptlrpc_request::rq_status, and unlock_res_and_lock().
Referenced by ldlm_callback_handler().
static int ldlm_handle_setinfo (struct ptlrpc_request * req) [static]
Definition at line 2095 of file ldlm_lockd.c.
References D_HSM, D_IOCTL, D_WARNING, DEBUG_REQ, ENTRY, obd_export::exp_obd, KEY_HSM_COPYTOOL_SEND, KEY_IS, obd_device::obd_name, obd_set_info_async(), RCL_CLIENT, req_capsule_client_get(), req_capsule_get_size(), req_capsule_set(), RETURN, RMF_SETINFO_KEY, RMF_SETINFO_VAL, ptlrpc_request::rq_export, ptlrpc_request::rq_pill, and RQF_OBD_SET_INFO.
Referenced by ldlm_callback_handler().
int ldlm_init (void)
Definition at line 3154 of file ldlm_lockd.c.
References INIT_LIST_HEAD, LCK_MODE_NUM, ldlm_cli_active_namespace_list, ldlm_cli_inactive_namespace_list, ldlm_interval_slab, ldlm_interval_tree_slab, ldlm_lock_slab, LDLM_NAMESPACE_CLIENT, ldlm_namespace_lock(), LDLM_NAMESPACE_SERVER, ldlm_ref_mutex, ldlm_resource_slab, ldlm_srv_namespace_list, and SLAB_DESTROY_BY_RCU.
Referenced by ptlrpc_init().
static int ldlm_setup (void) [static]
Definition at line 2924 of file ldlm_lockd.c.
References ldlm_bl_pool::blp_busy_threads, ldlm_bl_pool::blp_list, ldlm_bl_pool::blp_lock, ldlm_bl_pool::blp_max_threads, ldlm_bl_pool::blp_min_threads, ldlm_bl_pool::blp_num_threads, ldlm_bl_pool::blp_prio_list, ldlm_bl_pool::blp_waitq, CERROR, cfs_timer_init(), ELT_READY, ELT_STOPPED, ENTRY, GOTO, INIT_LIST_HEAD, LCT_CL_THREAD, LCT_DT_THREAD, LCT_MD_THREAD, ldlm_state::ldlm_bl_pool, ldlm_bl_thread_start(), LDLM_BUFSIZE, ldlm_callback_handler(), LDLM_CANCEL_REPLY_PORTAL, LDLM_CANCEL_REQUEST_PORTAL, ldlm_state::ldlm_cancel_service, LDLM_CB_REPLY_PORTAL, LDLM_CB_REQUEST_PORTAL, ldlm_state::ldlm_cb_service, ldlm_cleanup(), LDLM_CLIENT_NBUFS, ldlm_cpts, LDLM_MAXREPSIZE, LDLM_MAXREQSIZE, LDLM_NTHRS_BASE, LDLM_NTHRS_INIT, LDLM_NTHRS_MAX, ldlm_num_threads, ldlm_pools_init(), ldlm_proc_setup(), ldlm_reclaim_setup(), LDLM_SERVER_NBUFS, ldlm_svc_proc_dir, LDLM_THR_FACTOR, min_t, OBD_ALLOC, ptlrpc_service_conf::psc_name, ptlrpc_register_service(), and RETURN.
Referenced by ldlm_get_ref().
module_param (ldlm_cpts , charp , 0444)
module_param (ldlm_num_threads , int , 0444)
MODULE_PARM_DESC (ldlm_cpts , "CPU partitions ldlm threads should run on")
MODULE_PARM_DESC (ldlm_num_threads , "number of DLM service threads to start")
static cfs_time_t round_timeout (cfs_time_t timeout) [inline, static]
Definition at line 71 of file ldlm_lockd.c.
References cfs_duration_sec(), cfs_time_seconds(), and cfs_time_sub().
Variable Documentation
char* ldlm_cpts [static]
Definition at line 55 of file ldlm_lockd.c.
Referenced by ldlm_setup().
struct cfs_hash_ops ldlm_export_lock_ops [static]
Initial value:
 {
        .hs_hash        = ldlm_export_lock_hash,
        .hs_key         = ldlm_export_lock_key,
        .hs_keycmp      = ldlm_export_lock_keycmp,
        .hs_keycpy      = ldlm_export_lock_keycpy,
        .hs_object      = ldlm_export_lock_object,
        .hs_get         = ldlm_export_lock_get,
        .hs_put         = ldlm_export_lock_put,
        .hs_put_locked  = ldlm_export_lock_put,
}
Definition at line 2873 of file ldlm_lockd.c.
int ldlm_num_threads [static]
Definition at line 51 of file ldlm_lockd.c.
Referenced by ldlm_setup().
struct mutex ldlm_ref_mutex [static]
Definition at line 59 of file ldlm_lockd.c.
Referenced by ldlm_get_ref(), ldlm_init(), and ldlm_put_ref().
int ldlm_refcount [static]
Definition at line 60 of file ldlm_lockd.c.
Referenced by ldlm_exit(), ldlm_get_ref(), and ldlm_put_ref().
struct ldlm_state* ldlm_state [static]
Definition at line 69 of file ldlm_lockd.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.