Lustre: lustre/ldlm/ldlm_flock.c File Reference
lustre/ldlm/ldlm_flock.c File Reference
#include <lustre_dlm.h>
#include <obd_support.h>
#include <obd_class.h>
#include <lustre_lib.h>
#include <libcfs/list.h>
#include "ldlm_internal.h"
Data Structures
struct ldlm_flock_lookup_cb_data
POSIX locks deadlock detection code.
struct ldlm_flock_wait_data
Defines
#define DEBUG_SUBSYSTEM S_LDLM
This file implements POSIX lock type for Lustre.
#define list_for_remaining_safe(pos, n, head) for (n = pos->next; pos != (head); pos = n, n = pos->next)
list_for_remaining_safe - iterate over the remaining entries in a list and safeguard against removal of a list entry.
Functions
int ldlm_flock_blocking_ast (struct ldlm_lock *lock, struct ldlm_lock_desc *desc, void *data, int flag)
static int ldlm_same_flock_owner (struct ldlm_lock *lock, struct ldlm_lock *new)
static int ldlm_flocks_overlap (struct ldlm_lock *lock, struct ldlm_lock *new)
static void ldlm_flock_blocking_link (struct ldlm_lock *req, struct ldlm_lock *lock)
static void ldlm_flock_blocking_unlink (struct ldlm_lock *req)
static void ldlm_flock_destroy (struct ldlm_lock *lock, enum ldlm_mode mode, __u64 flags)
static int ldlm_flock_lookup_cb (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode, void *data)
static int ldlm_flock_deadlock (struct ldlm_lock *req, struct ldlm_lock *bl_lock)
static void ldlm_flock_cancel_on_deadlock (struct ldlm_lock *lock, struct list_head *work_list)
int ldlm_process_flock_lock (struct ldlm_lock *req, __u64 *flags, int first_enq, enum ldlm_error *err, struct list_head *work_list)
Process a granting attempt for flock lock.
static void ldlm_flock_interrupted_wait (void *data)
int ldlm_flock_completion_ast (struct ldlm_lock *lock, __u64 flags, void *data)
Flock completion callback function.
void ldlm_flock_policy_wire_to_local (const union ldlm_wire_policy_data *wpolicy, union ldlm_policy_data *lpolicy)
void ldlm_flock_policy_local_to_wire (const union ldlm_policy_data *lpolicy, union ldlm_wire_policy_data *wpolicy)
static unsigned ldlm_export_flock_hash (struct cfs_hash *hs, const void *key, unsigned mask)
static void * ldlm_export_flock_key (struct hlist_node *hnode)
static int ldlm_export_flock_keycmp (const void *key, struct hlist_node *hnode)
static void * ldlm_export_flock_object (struct hlist_node *hnode)
static void ldlm_export_flock_get (struct cfs_hash *hs, struct hlist_node *hnode)
static void ldlm_export_flock_put (struct cfs_hash *hs, struct hlist_node *hnode)
int ldlm_init_flock_export (struct obd_export *exp)
void ldlm_destroy_flock_export (struct obd_export *exp)
Variables
static struct cfs_hash_ops ldlm_export_flock_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_LDLM
This file implements POSIX lock type for Lustre.
Its policy properties are start and end of extent and PID.
These locks are only done through MDS due to POSIX semantics requiring e.g. that locks could be only partially released and as such split into two parts, and also that two adjacent locks from the same process may be merged into a single wider lock.
Lock modes are mapped like this: PR and PW for READ and WRITE locks NL to request a releasing of a portion of the lock
These flock locks never timeout.
Definition at line 57 of file ldlm_flock.c.
#define list_for_remaining_safe (pos, n, head) for (n = pos->next; pos != (head); pos = n, n = pos->next)
list_for_remaining_safe - iterate over the remaining entries in a list and safeguard against removal of a list entry.
Parameters:
pos the &struct list_head to use as a loop counter. pos MUST have been initialized prior to using it in this macro.
n another &struct list_head to use as temporary storage
head the head for your list.
Definition at line 78 of file ldlm_flock.c.
Referenced by ldlm_process_flock_lock().
Function Documentation
void ldlm_destroy_flock_export (struct obd_export * exp)
Definition at line 955 of file ldlm_flock.c.
References cfs_hash_putref(), ENTRY, EXIT, and obd_export::exp_flock_hash.
Referenced by ldlm_destroy_export().
static void ldlm_export_flock_get (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 894 of file ldlm_flock.c.
References ldlm_flock::blocking_export, ldlm_flock::blocking_refs, class_export_get(), hlist_entry, ldlm_policy_data::l_flock, ldlm_lock::l_policy_data, LASSERT, and LDLM_LOCK_GET.
static unsigned ldlm_export_flock_hash (struct cfs_hash * hs, const void * key, unsigned mask) [static]
Definition at line 867 of file ldlm_flock.c.
References __u64, and cfs_hash_u64_hash().
static void* ldlm_export_flock_key (struct hlist_node * hnode) [static]
Definition at line 873 of file ldlm_flock.c.
References hlist_entry, ldlm_lock::l_exp_flock_hash, ldlm_policy_data::l_flock, ldlm_lock::l_policy_data, and ldlm_flock::owner.
Referenced by ldlm_export_flock_keycmp().
static int ldlm_export_flock_keycmp (const void * key, struct hlist_node * hnode) [static]
Definition at line 882 of file ldlm_flock.c.
References __u64, and ldlm_export_flock_key().
static void* ldlm_export_flock_object (struct hlist_node * hnode) [static]
Definition at line 888 of file ldlm_flock.c.
References hlist_entry, and ldlm_lock::l_exp_flock_hash.
static void ldlm_export_flock_put (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 909 of file ldlm_flock.c.
References ldlm_flock::blocking_export, ldlm_flock::blocking_owner, ldlm_flock::blocking_refs, class_export_put(), hlist_entry, ldlm_policy_data::l_flock, ldlm_lock::l_policy_data, LASSERT, and LDLM_LOCK_RELEASE.
int ldlm_flock_blocking_ast (struct ldlm_lock * lock, struct ldlm_lock_desc * desc, void * data, int flag)
Definition at line 828 of file ldlm_flock.c.
References ENTRY, LASSERT, LDLM_CB_CANCELING, ldlm_flock_blocking_unlink(), lock_res_and_lock(), RETURN, and unlock_res_and_lock().
Referenced by ldlm_process_flock_lock().
static void ldlm_flock_blocking_link (struct ldlm_lock * req, struct ldlm_lock * lock) [inline, static]
Definition at line 98 of file ldlm_flock.c.
References ldlm_flock::blocking_export, ldlm_flock::blocking_owner, ldlm_flock::blocking_refs, cfs_hash_add(), obd_export::exp_flock_hash, hlist_unhashed(), ldlm_lock::l_exp_flock_hash, ldlm_lock::l_export, ldlm_policy_data::l_flock, ldlm_lock::l_policy_data, LASSERT, and ldlm_flock::owner.
Referenced by ldlm_process_flock_lock().
static void ldlm_flock_blocking_unlink (struct ldlm_lock * req) [inline, static]
Definition at line 118 of file ldlm_flock.c.
References cfs_hash_del(), check_res_locked(), obd_export::exp_flock_hash, hlist_unhashed(), ldlm_lock::l_exp_flock_hash, ldlm_lock::l_export, ldlm_policy_data::l_flock, ldlm_lock::l_policy_data, ldlm_lock::l_resource, and ldlm_flock::owner.
Referenced by ldlm_flock_blocking_ast(), ldlm_flock_cancel_on_deadlock(), ldlm_flock_interrupted_wait(), and ldlm_process_flock_lock().
static void ldlm_flock_cancel_on_deadlock (struct ldlm_lock * lock, struct list_head * work_list) [static]
Definition at line 250 of file ldlm_flock.c.
References CDEBUG, CERROR, D_INFO, exp_connect_flags(), ldlm_lock::l_completion_ast, ldlm_lock::l_export, ldlm_lock::l_flags, LASSERT, ldlm_add_ast_work_item(), LDLM_FL_AST_SENT, LDLM_FL_CANCEL_ON_BLOCK, LDLM_FL_FLOCK_DEADLOCK, ldlm_flock_blocking_unlink(), ldlm_is_ast_sent, ldlm_resource_unlink_lock(), and OBD_CONNECT_FLOCK_DEAD.
Referenced by ldlm_process_flock_lock().
static int ldlm_flock_deadlock (struct ldlm_lock * req, struct ldlm_lock * bl_lock) [static]
Definition at line 192 of file ldlm_flock.c.
References __u64, ldlm_flock_lookup_cb_data::bl_owner, ldlm_flock::blocking_export, ldlm_flock::blocking_owner, ptlrpc_connection::c_peer, cfs_hash_for_each_key(), cfs_hash_put(), class_export_get(), class_export_put(), ldlm_flock_lookup_cb_data::exp, obd_export::exp_connection, obd_export::exp_failed, obd_export::exp_flock_hash, obd_export::exp_obd, ldlm_lock::l_exp_flock_hash, ldlm_lock::l_export, ldlm_policy_data::l_flock, ldlm_lock::l_policy_data, LASSERT, ldlm_flock_lookup_cb(), ldlm_flock_lookup_cb_data::lock, lnet_process_id_t::nid, obd_device::obd_nid_hash, and ldlm_flock::owner.
Referenced by ldlm_process_flock_lock().
static void ldlm_flock_destroy (struct ldlm_lock * lock, enum ldlm_mode mode, __u64 flags) [inline, static]
Definition at line 133 of file ldlm_flock.c.
References ENTRY, EXIT, hlist_unhashed(), ldlm_lock::l_exp_flock_hash, ldlm_lock::l_flags, ldlm_lock::l_res_link, LASSERT, LDLM_DEBUG, LDLM_FL_CBPENDING, LDLM_FL_LOCAL_ONLY, LDLM_FL_WAIT_NOREPROC, ldlm_lock_decref_internal_nolock(), ldlm_lock_destroy_nolock(), list_del_init(), and LPX64.
Referenced by ldlm_flock_completion_ast(), and ldlm_process_flock_lock().
static void ldlm_flock_interrupted_wait (void * data) [static]
Definition at line 633 of file ldlm_flock.c.
References ENTRY, EXIT, ldlm_flock_blocking_unlink(), ldlm_set_cbpending, lock_res_and_lock(), and unlock_res_and_lock().
Referenced by ldlm_flock_completion_ast().
static int ldlm_flock_lookup_cb (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode, void * data) [static]
Definition at line 173 of file ldlm_flock.c.
References ldlm_flock_lookup_cb_data::bl_owner, cfs_hash_lookup(), cfs_hash_object(), class_export_get(), ldlm_flock_lookup_cb_data::exp, obd_export::exp_flock_hash, and ldlm_flock_lookup_cb_data::lock.
Referenced by ldlm_flock_deadlock().
void ldlm_flock_policy_local_to_wire (const union ldlm_policy_data * lpolicy, union ldlm_wire_policy_data * wpolicy)
Definition at line 853 of file ldlm_flock.c.
References ldlm_flock::end, ldlm_policy_data::l_flock, ldlm_wire_policy_data::l_flock, ldlm_flock_wire::lfw_end, ldlm_flock_wire::lfw_owner, ldlm_flock_wire::lfw_pid, ldlm_flock_wire::lfw_start, ldlm_flock::owner, ldlm_flock::pid, and ldlm_flock::start.
void ldlm_flock_policy_wire_to_local (const union ldlm_wire_policy_data * wpolicy, union ldlm_policy_data * lpolicy)
Definition at line 843 of file ldlm_flock.c.
References ldlm_flock::end, ldlm_wire_policy_data::l_flock, ldlm_policy_data::l_flock, ldlm_flock_wire::lfw_end, ldlm_flock_wire::lfw_owner, ldlm_flock_wire::lfw_pid, ldlm_flock_wire::lfw_start, ldlm_flock::owner, ldlm_flock::pid, and ldlm_flock::start.
static int ldlm_flocks_overlap (struct ldlm_lock * lock, struct ldlm_lock * new) [inline, static]
Definition at line 90 of file ldlm_flock.c.
References ldlm_flock::end, ldlm_policy_data::l_flock, ldlm_lock::l_policy_data, and ldlm_flock::start.
Referenced by ldlm_process_flock_lock().
int ldlm_init_flock_export (struct obd_export * exp)
Definition at line 936 of file ldlm_flock.c.
References cfs_hash_create(), CFS_HASH_DEFAULT, CFS_HASH_MAX_THETA, CFS_HASH_MIN_THETA, CFS_HASH_NBLK_CHANGE, obd_export::exp_client_uuid, obd_export::exp_flock_hash, obd_export::exp_obd, HASH_EXP_LOCK_BKT_BITS, HASH_EXP_LOCK_CUR_BITS, HASH_EXP_LOCK_MAX_BITS, LUSTRE_MDT_NAME, obd_device::obd_type, obd_uuid2str(), RETURN, and obd_type::typ_name.
Referenced by ldlm_init_export().
int ldlm_process_flock_lock (struct ldlm_lock * req, __u64 * flags, int first_enq, enum ldlm_error * err, struct list_head * work_list)
Process a granting attempt for flock lock.
Must be called under ns lock held.
This function looks for any conflicts for lock in the granted or waiting queues. The lock is granted if no conflicts are found in either queue.
It is also responsible for splitting a lock if a portion of the lock is released.
If first_enq is 0 (ie, called from ldlm_reprocess_queue):
blocking ASTs have already been sent
If first_enq is 1 (ie, called from ldlm_lock_enqueue):
blocking ASTs have not been sent yet, so list of conflicting locks would be collected and ASTs sent.
Definition at line 289 of file ldlm_flock.c.
References CDEBUG, CERROR, cfs_hash_add(), class_export_lock_get, D_DLMTRACE, D_INFO, ELDLM_OK, ldlm_flock::end, ENTRY, obd_export::exp_lock_hash, GOTO, hlist_unhashed(), INIT_LIST_HEAD, ldlm_lock::l_blocking_ast, ldlm_lock::l_completion_ast, ldlm_lock::l_conn_export, ldlm_lock::l_exp_hash, ldlm_lock::l_export, ldlm_policy_data::l_flock, ldlm_lock::l_granted_mode, ldlm_lock::l_policy_data, ldlm_lock::l_remote_handle, ldlm_lock::l_req_mode, ldlm_lock::l_res_link, ldlm_lock::l_resource, LASSERT, LBUG, LCK_NL, ldlm_add_ast_work_item(), LDLM_FL_BLOCK_GRANTED, LDLM_FL_BLOCK_NOWAIT, LDLM_FL_LOCK_CHANGED, LDLM_FL_TEST_LOCK, LDLM_FL_WAIT_NOREPROC, LDLM_FLOCK, ldlm_flock_blocking_ast(), ldlm_flock_blocking_link(), ldlm_flock_blocking_unlink(), ldlm_flock_cancel_on_deadlock(), ldlm_flock_deadlock(), ldlm_flock_destroy(), ldlm_flocks_overlap(), LDLM_ITER_CONTINUE, LDLM_ITER_STOP, ldlm_lock_addref_internal_nolock(), ldlm_lock_create(), ldlm_lock_destroy_nolock(), LDLM_LOCK_RELEASE, ldlm_res_to_ns(), ldlm_resource_add_lock(), ldlm_resource_dump(), ldlm_run_ast_work(), ldlm_same_flock_owner(), LDLM_WORK_CP_AST, list_del_init(), list_entry, list_for_each, list_for_remaining_safe, lock_res_and_lock(), lockmode_compat(), lockmode_verify(), LPU64, LPX64, ldlm_resource::lr_granted, ldlm_resource::lr_name, ldlm_resource::lr_waiting, LVB_T_NONE, mode, ns_is_client(), OBD_OBJECT_EOF, ldlm_flock::owner, ldlm_flock::pid, RETURN, ldlm_flock::start, and unlock_res_and_lock().
Referenced by ldlm_flock_completion_ast().
static int ldlm_same_flock_owner (struct ldlm_lock * lock, struct ldlm_lock * new) [inline, static]
Definition at line 82 of file ldlm_flock.c.
References ldlm_lock::l_export, ldlm_policy_data::l_flock, ldlm_lock::l_policy_data, and ldlm_flock::owner.
Referenced by ldlm_process_flock_lock().
Variable Documentation
struct cfs_hash_ops ldlm_export_flock_ops [static]
Initial value:
 {
        .hs_hash        = ldlm_export_flock_hash,
        .hs_key         = ldlm_export_flock_key,
        .hs_keycmp      = ldlm_export_flock_keycmp,
        .hs_object      = ldlm_export_flock_object,
        .hs_get         = ldlm_export_flock_get,
        .hs_put         = ldlm_export_flock_put,
        .hs_put_locked  = ldlm_export_flock_put,
}
Definition at line 926 of file ldlm_flock.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.