Lustre: lustre/ldlm/ldlm_extent.c File Reference
lustre/ldlm/ldlm_extent.c File Reference
#include <libcfs/libcfs.h>
#include <lustre_dlm.h>
#include <obd_support.h>
#include <obd.h>
#include <obd_class.h>
#include <lustre_lib.h>
#include "ldlm_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LDLM
This file contains implementation of EXTENT lock type.
Functions
__u64 ldlm_extent_shift_kms (struct ldlm_lock *lock, __u64 old_kms)
struct ldlm_interval * ldlm_interval_alloc (struct ldlm_lock *lock)
void ldlm_interval_free (struct ldlm_interval *node)
void ldlm_interval_attach (struct ldlm_interval *n, struct ldlm_lock *l)
struct ldlm_interval * ldlm_interval_detach (struct ldlm_lock *l)
static int ldlm_mode_to_index (enum ldlm_mode mode)
void ldlm_extent_add_lock (struct ldlm_resource *res, struct ldlm_lock *lock)
Add newly granted lock into interval tree for the resource.
void ldlm_extent_unlink_lock (struct ldlm_lock *lock)
Remove cancelled lock from resource interval tree.
void ldlm_extent_policy_wire_to_local (const union ldlm_wire_policy_data *wpolicy, union ldlm_policy_data *lpolicy)
void ldlm_extent_policy_local_to_wire (const union ldlm_policy_data *lpolicy, union ldlm_wire_policy_data *wpolicy)
Variables
struct kmem_cache * ldlm_interval_slab
Define Documentation
#define DEBUG_SUBSYSTEM S_LDLM
This file contains implementation of EXTENT lock type.
EXTENT lock type is for locking a contiguous range of values, represented by 64-bit starting and ending offsets (inclusive). There are several extent lock modes, some of which may be mutually incompatible. Extent locks are considered incompatible if their modes are incompatible and their extents intersect. See the lock mode compatibility matrix in lustre_dlm.h.
Definition at line 52 of file ldlm_extent.c.
Function Documentation
void ldlm_extent_add_lock (struct ldlm_resource * res, struct ldlm_lock * lock)
Add newly granted lock into interval tree for the resource.
Definition at line 898 of file ldlm_extent.c.
References ldlm_extent::end, interval_insert(), interval_is_intree(), interval_set(), ldlm_policy_data::l_extent, ldlm_lock::l_granted_mode, ldlm_lock::l_policy_data, ldlm_lock::l_req_mode, ldlm_lock::l_tree_node, LASSERT, ldlm_interval_attach(), ldlm_interval_detach(), ldlm_interval_free(), ldlm_mode_to_index(), ldlm_resource_add_lock(), ldlm_interval::li_node, ldlm_interval_tree::lit_mode, ldlm_interval_tree::lit_root, ldlm_interval_tree::lit_size, ldlm_resource::lr_granted, ldlm_resource::lr_itree, ldlm_extent::start, and to_ldlm_interval.
Referenced by ldlm_grant_lock(), and ldlm_lock_convert().
void ldlm_extent_policy_local_to_wire (const union ldlm_policy_data * lpolicy, union ldlm_wire_policy_data * wpolicy)
Definition at line 969 of file ldlm_extent.c.
References ldlm_extent::end, ldlm_extent::gid, ldlm_policy_data::l_extent, ldlm_wire_policy_data::l_extent, and ldlm_extent::start.
void ldlm_extent_policy_wire_to_local (const union ldlm_wire_policy_data * wpolicy, union ldlm_policy_data * lpolicy)
Definition at line 960 of file ldlm_extent.c.
References ldlm_extent::end, ldlm_extent::gid, ldlm_wire_policy_data::l_extent, ldlm_policy_data::l_extent, and ldlm_extent::start.
void ldlm_extent_unlink_lock (struct ldlm_lock * lock)
Remove cancelled lock from resource interval tree.
Definition at line 936 of file ldlm_extent.c.
References interval_erase(), interval_is_intree(), ldlm_lock::l_granted_mode, ldlm_lock::l_resource, ldlm_lock::l_tree_node, LASSERT, ldlm_interval_detach(), ldlm_interval_free(), ldlm_mode_to_index(), ldlm_interval::li_node, ldlm_interval_tree::lit_root, ldlm_interval_tree::lit_size, and ldlm_resource::lr_itree.
Referenced by ldlm_resource_unlink_lock().
struct ldlm_interval* ldlm_interval_alloc (struct ldlm_lock * lock) [read]
Definition at line 836 of file ldlm_extent.c.
References ENTRY, INIT_LIST_HEAD, ldlm_lock::l_resource, LASSERT, LDLM_EXTENT, ldlm_interval_attach(), ldlm_interval::li_group, ldlm_resource::lr_type, OBD_SLAB_ALLOC_PTR_GFP, and RETURN.
Referenced by ldlm_lock_create().
void ldlm_interval_attach (struct ldlm_interval * n, struct ldlm_lock * l)
Definition at line 861 of file ldlm_extent.c.
References ldlm_lock::l_resource, ldlm_lock::l_sl_policy, ldlm_lock::l_tree_node, LASSERT, LDLM_EXTENT, ldlm_interval::li_group, list_add_tail(), and ldlm_resource::lr_type.
Referenced by ldlm_extent_add_lock(), ldlm_interval_alloc(), ldlm_lock_convert(), and ldlm_lock_enqueue().
struct ldlm_interval* ldlm_interval_detach (struct ldlm_lock * l) [read]
Definition at line 871 of file ldlm_extent.c.
References ldlm_lock::l_sl_policy, ldlm_lock::l_tree_node, LASSERT, ldlm_interval::li_group, list_del_init(), and list_empty().
Referenced by ldlm_extent_add_lock(), ldlm_extent_unlink_lock(), and ldlm_lock_put().
void ldlm_interval_free (struct ldlm_interval * node)
Definition at line 851 of file ldlm_extent.c.
References interval_is_intree(), LASSERT, ldlm_interval::li_group, ldlm_interval::li_node, list_empty(), and OBD_SLAB_FREE.
Referenced by ldlm_extent_add_lock(), ldlm_extent_unlink_lock(), and ldlm_lock_put().
static int ldlm_mode_to_index (enum ldlm_mode mode) [inline, static]
Definition at line 885 of file ldlm_extent.c.
References LASSERT.
Referenced by ldlm_extent_add_lock(), and ldlm_extent_unlink_lock().
Variable Documentation
struct kmem_cache* ldlm_interval_slab
Definition at line 835 of file ldlm_extent.c.
Referenced by ldlm_exit(), ldlm_init(), ldlm_lock_convert(), and ldlm_lock_enqueue().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.