Lustre: lustre/ldlm/ldlm_lock.c File Reference
lustre/ldlm/ldlm_lock.c File Reference
#include <libcfs/libcfs.h>
#include <lustre_swab.h>
#include <obd_class.h>
#include "ldlm_internal.h"
Data Structures
struct sl_insert_point
struct lock_match_data
Describe the overlap between two locks.
struct export_cl_data
Defines
#define DEBUG_SUBSYSTEM S_LDLM
Functions
void ldlm_convert_policy_to_wire (enum ldlm_type type, const union ldlm_policy_data *lpolicy, union ldlm_wire_policy_data *wpolicy)
Converts lock policy from local format to on the wire lock_desc format.
void ldlm_convert_policy_to_local (struct obd_export *exp, enum ldlm_type type, const union ldlm_wire_policy_data *wpolicy, union ldlm_policy_data *lpolicy)
Converts lock policy from on the wire lock_desc format to local format.
const char * ldlm_it2str (enum ldlm_intent_flags it)
void ldlm_register_intent (struct ldlm_namespace *ns, ldlm_res_policy arg)
struct ldlm_lock * ldlm_lock_get (struct ldlm_lock *lock)
Get a reference on a lock.
void ldlm_lock_put (struct ldlm_lock *lock)
Release lock reference.
int ldlm_lock_remove_from_lru_nolock (struct ldlm_lock *lock)
Removes LDLM lock lock from LRU.
int ldlm_lock_remove_from_lru_check (struct ldlm_lock *lock, cfs_time_t last_use)
Removes LDLM lock lock from LRU.
void ldlm_lock_add_to_lru_nolock (struct ldlm_lock *lock)
Adds LDLM lock lock to namespace LRU.
void ldlm_lock_add_to_lru (struct ldlm_lock *lock)
Adds LDLM lock lock to namespace LRU.
void ldlm_lock_touch_in_lru (struct ldlm_lock *lock)
Moves LDLM lock lock that is already in namespace LRU to the tail of the LRU.
static int ldlm_lock_destroy_internal (struct ldlm_lock *lock)
Helper to destroy a locked lock.
void ldlm_lock_destroy (struct ldlm_lock *lock)
Destroys a LDLM lock lock.
void ldlm_lock_destroy_nolock (struct ldlm_lock *lock)
Destroys a LDLM lock lock that is already locked.
static void lock_handle_addref (void *lock)
static void lock_handle_free (void *lock, int size)
static struct ldlm_lock * ldlm_lock_new (struct ldlm_resource *resource)
Allocate and initialize new lock structure.
int ldlm_lock_change_resource (struct ldlm_namespace *ns, struct ldlm_lock *lock, const struct ldlm_res_id *new_resid)
Moves LDLM lock lock to another resource.
void ldlm_lock2handle (const struct ldlm_lock *lock, struct lustre_handle *lockh)
Fills in handle for LDLM lock lock into supplied lockh Does not take any references.
struct ldlm_lock * __ldlm_handle2lock (const struct lustre_handle *handle, __u64 flags)
Obtain a lock reference by handle.
void ldlm_lock2desc (struct ldlm_lock *lock, struct ldlm_lock_desc *desc)
Fill in "on the wire" representation for given LDLM lock into supplied lock descriptor desc structure.
static void ldlm_add_bl_work_item (struct ldlm_lock *lock, struct ldlm_lock *new, struct list_head *work_list)
Add a lock to list of conflicting locks to send AST to.
static void ldlm_add_cp_work_item (struct ldlm_lock *lock, struct list_head *work_list)
Add a lock to list of just granted locks to send completion AST to.
void ldlm_add_ast_work_item (struct ldlm_lock *lock, struct ldlm_lock *new, struct list_head *work_list)
Aggregator function to add AST work items into a list.
void ldlm_lock_addref (const struct lustre_handle *lockh, enum ldlm_mode mode)
Add specified reader/writer reference to LDLM lock with handle lockh.
void ldlm_lock_addref_internal_nolock (struct ldlm_lock *lock, enum ldlm_mode mode)
Helper function.
int ldlm_lock_addref_try (const struct lustre_handle *lockh, enum ldlm_mode mode)
Attempts to add reader/writer reference to a lock with handle lockh, and fails if lock is already LDLM_FL_CBPENDING or destroyed.
void ldlm_lock_addref_internal (struct ldlm_lock *lock, enum ldlm_mode mode)
Add specified reader/writer reference to LDLM lock lock.
void ldlm_lock_decref_internal_nolock (struct ldlm_lock *lock, enum ldlm_mode mode)
Removes reader/writer reference for LDLM lock lock.
void ldlm_lock_decref_internal (struct ldlm_lock *lock, enum ldlm_mode mode)
Removes reader/writer reference for LDLM lock lock.
void ldlm_lock_decref (const struct lustre_handle *lockh, enum ldlm_mode mode)
Decrease reader/writer refcount for LDLM lock with handle lockh.
void ldlm_lock_decref_and_cancel (const struct lustre_handle *lockh, enum ldlm_mode mode)
Decrease reader/writer refcount for LDLM lock with handle lockh and mark it for subsequent cancellation once r/w refcount drops to zero instead of putting into LRU.
static void search_granted_lock (struct list_head *queue, struct ldlm_lock *req, struct sl_insert_point *prev)
Finds a position to insert the new lock into granted lock list.
static void ldlm_granted_list_add_lock (struct ldlm_lock *lock, struct sl_insert_point *prev)
Add a lock into resource granted list after a position described by prev.
static void ldlm_grant_lock_with_skiplist (struct ldlm_lock *lock)
Add a lock to granted list on a resource maintaining skiplist correctness.
void ldlm_grant_lock (struct ldlm_lock *lock, struct list_head *work_list)
Perform lock granting bookkeeping.
static int lock_matches (struct ldlm_lock *lock, struct lock_match_data *data)
Check if the given meets the criteria for a match.
static unsigned int itree_overlap_cb (struct interval_node *in, void *args)
static struct ldlm_lock * search_itree (struct ldlm_resource *res, struct lock_match_data *data)
Search for a lock with given parameters in interval trees.
static struct ldlm_lock * search_queue (struct list_head *queue, struct lock_match_data *data)
Search for a lock with given properties in a queue.
void ldlm_lock_fail_match_locked (struct ldlm_lock *lock)
void ldlm_lock_fail_match (struct ldlm_lock *lock)
void ldlm_lock_allow_match_locked (struct ldlm_lock *lock)
Mark lock as "matchable" by OST.
void ldlm_lock_allow_match (struct ldlm_lock *lock)
Mark lock as "matchable" by OST.
enum ldlm_mode ldlm_lock_match (struct ldlm_namespace *ns, __u64 flags, const struct ldlm_res_id *res_id, enum ldlm_type type, union ldlm_policy_data *policy, enum ldlm_mode mode, struct lustre_handle *lockh, int unref)
Attempt to find a lock with specified properties.
enum ldlm_mode ldlm_revalidate_lock_handle (const struct lustre_handle *lockh, __u64 *bits)
int ldlm_fill_lvb (struct ldlm_lock *lock, struct req_capsule *pill, enum req_location loc, void *data, int size)
The caller must guarantee that the buffer is large enough.
struct ldlm_lock * ldlm_lock_create (struct ldlm_namespace *ns, const struct ldlm_res_id *res_id, enum ldlm_type type, enum ldlm_mode mode, const struct ldlm_callback_suite *cbs, void *data, __u32 lvb_len, enum lvb_type lvb_type)
Create and fill in new LDLM lock with specified properties.
enum ldlm_error ldlm_lock_enqueue (struct ldlm_namespace *ns, struct ldlm_lock **lockp, void *cookie, __u64 *flags)
Enqueue (request) a lock.
static int ldlm_work_bl_ast_lock (struct ptlrpc_request_set *rqset, void *opaq)
Process a call to blocking AST callback for a lock in ast_work list.
static int ldlm_work_cp_ast_lock (struct ptlrpc_request_set *rqset, void *opaq)
Process a call to completion AST callback for a lock in ast_work list.
static int ldlm_work_revoke_ast_lock (struct ptlrpc_request_set *rqset, void *opaq)
Process a call to revocation AST callback for a lock in ast_work list.
int ldlm_work_gl_ast_lock (struct ptlrpc_request_set *rqset, void *opaq)
Process a call to glimpse AST callback for a lock in ast_work list.
int ldlm_run_ast_work (struct ldlm_namespace *ns, struct list_head *rpc_list, ldlm_desc_ast_t ast_type)
Process list of locks in need of ASTs being sent.
static int reprocess_one_queue (struct ldlm_resource *res, void *closure)
static int ldlm_reprocess_res (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode, void *arg)
void ldlm_reprocess_all_ns (struct ldlm_namespace *ns)
Iterate through all resources on a namespace attempting to grant waiting locks.
void ldlm_reprocess_all (struct ldlm_resource *res)
Try to grant all waiting locks on a resource.
static bool is_bl_done (struct ldlm_lock *lock)
void ldlm_cancel_callback (struct ldlm_lock *lock)
Helper function to call blocking AST for LDLM lock lock in a "cancelling" mode.
void ldlm_unlink_lock_skiplist (struct ldlm_lock *req)
Remove skiplist-enabled LDLM lock req from granted list.
void ldlm_lock_cancel (struct ldlm_lock *lock)
Attempts to cancel LDLM lock lock that has no reader/writer references.
int ldlm_lock_set_data (const struct lustre_handle *lockh, void *data)
Set opaque data into the lock that only makes sense to upper layer.
static void ldlm_cancel_lock_for_export (struct obd_export *exp, struct ldlm_lock *lock, struct export_cl_data *ecl)
static int ldlm_cancel_locks_for_export_cb (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode, void *data)
Iterator function for ldlm_export_cancel_locks.
int ldlm_export_cancel_blocked_locks (struct obd_export *exp)
Cancel all blocked locks for given export.
int ldlm_export_cancel_locks (struct obd_export *exp)
Cancel all locks for given export.
void ldlm_lock_downgrade (struct ldlm_lock *lock, enum ldlm_mode new_mode)
Downgrade an exclusive lock.
struct ldlm_resource * ldlm_lock_convert (struct ldlm_lock *lock, enum ldlm_mode new_mode, __u32 *flags)
Attempt to convert already granted lock to a different mode.
void ldlm_lock_dump_handle (int level, const struct lustre_handle *lockh)
Print lock with lock handle lockh description into debug log.
void _ldlm_lock_debug (struct ldlm_lock *lock, struct libcfs_debug_msg_data *msgdata, const char *fmt,...)
Print lock information with custom message into debug log.
Variables
char * ldlm_lockname []
char * ldlm_typename []
static ldlm_policy_wire_to_local_t ldlm_policy_wire_to_local []
static ldlm_policy_local_to_wire_t ldlm_policy_local_to_wire []
struct kmem_cache * ldlm_lock_slab
static struct portals_handle_ops lock_handle_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_LDLM
Definition at line 42 of file ldlm_lock.c.
Function Documentation
void _ldlm_lock_debug (struct ldlm_lock * lock, struct libcfs_debug_msg_data * msgdata, const char * fmt, ...)
Print lock information with custom message into debug log.
Helper function.
Definition at line 2607 of file ldlm_lock.c.
References ldlm_inodebits::bits, ptlrpc_connection::c_peer, client_obd::cl_import, obd_device::cli, lustre_handle::cookie, DLDLMRES, ldlm_flock::end, ldlm_extent::end, obd_export::exp_connection, obd_export::exp_obd, obd_export::exp_refcount, portals_handle::h_cookie, obd_import::imp_connection, ldlm_lock::l_callback_timeout, ldlm_lock::l_export, ldlm_policy_data::l_extent, ldlm_lock::l_flags, ldlm_policy_data::l_flock, ldlm_lock::l_granted_mode, ldlm_lock::l_handle, ldlm_policy_data::l_inodebits, ldlm_lock::l_lvb_type, ldlm_lock::l_pid, ldlm_lock::l_policy_data, ldlm_lock::l_readers, ldlm_lock::l_refc, ldlm_lock::l_remote_handle, ldlm_lock::l_req_extent, ldlm_lock::l_req_mode, ldlm_lock::l_resource, ldlm_lock::l_writers, LDLM_EXTENT, LDLM_FLOCK, LDLM_IBITS, ldlm_lock_to_ns_name(), ldlm_lockname, ldlm_typename, libcfs_debug_vmsg2(), libcfs_nid2str(), LPU64, LPX64, ldlm_resource::lr_refcount, ldlm_resource::lr_type, lnet_process_id_t::nid, ldlm_flock::pid, PLDLMRES, ldlm_flock::start, ldlm_extent::start, and obd_device::u.
static bool is_bl_done (struct ldlm_lock * lock) [static]
Definition at line 2188 of file ldlm_lock.c.
References ldlm_is_bl_done, lock_res_and_lock(), and unlock_res_and_lock().
Referenced by ldlm_cancel_callback().
static unsigned int itree_overlap_cb (struct interval_node * in, void * args) [static]
Definition at line 1228 of file ldlm_lock.c.
References INTERVAL_ITER_CONT, INTERVAL_ITER_STOP, ldlm_lock::l_sl_policy, ldlm_interval::li_group, list_for_each_entry, lock_matches(), and to_ldlm_interval.
Referenced by search_itree().
void ldlm_add_ast_work_item (struct ldlm_lock * lock, struct ldlm_lock * new, struct list_head * work_list)
Aggregator function to add AST work items into a list.
Determines what sort of an AST work needs to be done and calls the proper adding function. Must be called with lr_lock held.
Definition at line 700 of file ldlm_lock.c.
References check_res_locked(), ENTRY, EXIT, ldlm_lock::l_resource, ldlm_add_bl_work_item(), and ldlm_add_cp_work_item().
Referenced by ldlm_flock_cancel_on_deadlock(), ldlm_grant_lock(), and ldlm_process_flock_lock().
static void ldlm_add_bl_work_item (struct ldlm_lock * lock, struct ldlm_lock * new, struct list_head * work_list) [static]
Add a lock to list of conflicting locks to send AST to.
Only add if we have not sent a blocking AST to the lock yet.
Definition at line 661 of file ldlm_lock.c.
References ldlm_lock::l_bl_ast, ldlm_lock::l_blocking_lock, LASSERT, LDLM_DEBUG, ldlm_is_ast_discard_data, ldlm_is_ast_sent, LDLM_LOCK_GET, ldlm_set_ast_sent, ldlm_set_discard_data, list_add(), and list_empty().
Referenced by ldlm_add_ast_work_item().
static void ldlm_add_cp_work_item (struct ldlm_lock * lock, struct list_head * work_list) [static]
Add a lock to list of just granted locks to send completion AST to.
Definition at line 682 of file ldlm_lock.c.
References ldlm_lock::l_cp_ast, LASSERT, LDLM_DEBUG, ldlm_is_cp_reqd, LDLM_LOCK_GET, ldlm_set_cp_reqd, list_add(), and list_empty().
Referenced by ldlm_add_ast_work_item().
static void ldlm_cancel_lock_for_export (struct obd_export * exp, struct ldlm_lock * lock, struct export_cl_data * ecl) [static]
Definition at line 2315 of file ldlm_lock.c.
References CDEBUG, D_INFO, export_cl_data::ecl_loop, obd_export::exp_obd, ldlm_lock::l_resource, ldlm_lock_cancel(), ldlm_reprocess_all(), ldlm_res_lvbo_update(), ldlm_resource_getref(), ldlm_resource_putref(), and obd_device::obd_stopping.
Referenced by ldlm_cancel_locks_for_export_cb(), and ldlm_export_cancel_blocked_locks().
static int ldlm_cancel_locks_for_export_cb (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode, void * data) [static]
Iterator function for ldlm_export_cancel_locks.
Cancels passed locks.
Definition at line 2341 of file ldlm_lock.c.
References cfs_hash_object(), export_cl_data::ecl_exp, ldlm_cancel_lock_for_export(), LDLM_LOCK_GET, and LDLM_LOCK_RELEASE.
Referenced by ldlm_export_cancel_locks().
int ldlm_export_cancel_blocked_locks (struct obd_export * exp)
Cancel all blocked locks for given export.
Typically called on client disconnection/eviction
Definition at line 2361 of file ldlm_lock.c.
References CDEBUG, D_DLMTRACE, export_cl_data::ecl_exp, export_cl_data::ecl_loop, obd_export::exp_bl_list, obd_export::exp_bl_list_lock, obd_export::exp_lock_hash, cfs_hash::hs_count, ldlm_lock::l_exp_list, ldlm_cancel_lock_for_export(), LDLM_LOCK_GET, LDLM_LOCK_RELEASE, list_del_init(), list_empty(), list_entry, and list_head::next.
Referenced by ldlm_bl_thread_exports().
int ldlm_export_cancel_locks (struct obd_export * exp)
Cancel all locks for given export.
Typically called after client disconnection/eviction
Definition at line 2401 of file ldlm_lock.c.
References CDEBUG, cfs_hash_for_each_empty(), D_DLMTRACE, export_cl_data::ecl_exp, export_cl_data::ecl_loop, obd_export::exp_lock_hash, cfs_hash::hs_count, and ldlm_cancel_locks_for_export_cb().
Referenced by ldlm_bl_thread_exports().
int ldlm_fill_lvb (struct ldlm_lock * lock, struct req_capsule * pill, enum req_location loc, void * data, int size)
The caller must guarantee that the buffer is large enough.
Definition at line 1539 of file ldlm_lock.c.
References ENTRY, ldlm_lock::l_lvb_type, LASSERT, LDLM_ERROR, libcfs_debug_dumpstack, lustre_swab_lquota_lvb(), lustre_swab_ost_lvb, lustre_swab_ost_lvb_v1, ost_lvb::lvb_atime_ns, ost_lvb::lvb_ctime_ns, ost_lvb::lvb_mtime_ns, LVB_T_LAYOUT, LVB_T_LQUOTA, LVB_T_OST, RCL_CLIENT, req_capsule_client_get(), req_capsule_client_swab_get(), req_capsule_server_get(), req_capsule_server_sized_swab_get(), req_capsule_server_swab_get(), RETURN, RMF_DLM_LVB, and unlikely.
Referenced by ldlm_cli_enqueue_fini(), and ldlm_handle_cp_callback().
void ldlm_grant_lock (struct ldlm_lock * lock, struct list_head * work_list)
Perform lock granting bookkeeping.
Includes putting the lock into granted list and updating lock mode. NOTE: called by
ldlm_lock_enqueue
ldlm_reprocess_queue
ldlm_lock_convert
must be called with lr_lock held
Definition at line 1101 of file ldlm_lock.c.
References check_res_locked(), ENTRY, EXIT, ldlm_lock::l_completion_ast, ldlm_lock::l_granted_mode, ldlm_lock::l_req_mode, ldlm_lock::l_resource, LCK_NL, ldlm_add_ast_work_item(), LDLM_EXTENT, ldlm_extent_add_lock(), ldlm_grant_lock_with_skiplist(), LDLM_IBITS, ldlm_is_flock_deadlock, ldlm_is_test_lock, LDLM_PLAIN, ldlm_pool_add(), ldlm_res_to_ns(), ldlm_resource_add_lock(), ldlm_resource::lr_granted, ldlm_resource::lr_type, and RETURN_EXIT.
Referenced by ldlm_handle_cp_callback(), ldlm_lock_convert(), ldlm_lock_downgrade(), and ldlm_lock_enqueue().
static void ldlm_grant_lock_with_skiplist (struct ldlm_lock * lock) [static]
Add a lock to granted list on a resource maintaining skiplist correctness.
Definition at line 1078 of file ldlm_lock.c.
References ENTRY, EXIT, ldlm_lock::l_granted_mode, ldlm_lock::l_req_mode, ldlm_lock::l_resource, LASSERT, ldlm_granted_list_add_lock(), ldlm_resource::lr_granted, and search_granted_lock().
Referenced by ldlm_grant_lock().
static void ldlm_granted_list_add_lock (struct ldlm_lock * lock, struct sl_insert_point * prev) [static]
Add a lock into resource granted list after a position described by prev.
Definition at line 1040 of file ldlm_lock.c.
References CDEBUG, check_res_locked(), D_INFO, D_OTHER, ENTRY, EXIT, ldlm_lock::l_res_link, ldlm_lock::l_resource, ldlm_lock::l_sl_mode, ldlm_lock::l_sl_policy, LASSERT, LDLM_DEBUG, ldlm_is_destroyed, ldlm_resource_dump(), list_add(), list_empty(), sl_insert_point::mode_link, sl_insert_point::policy_link, and sl_insert_point::res_link.
Referenced by ldlm_grant_lock_with_skiplist(), and ldlm_lock_convert().
void ldlm_lock_add_to_lru (struct ldlm_lock * lock)
Adds LDLM lock lock to namespace LRU.
Obtains necessary LRU locks first.
Definition at line 298 of file ldlm_lock.c.
References ENTRY, EXIT, ldlm_lock_add_to_lru_nolock(), ldlm_lock_to_ns(), and ldlm_namespace::ns_lock.
Referenced by ldlm_lock_decref_internal().
void ldlm_lock_add_to_lru_nolock (struct ldlm_lock * lock)
Adds LDLM lock lock to namespace LRU.
Assumes LRU is already locked.
Definition at line 281 of file ldlm_lock.c.
References cfs_time_current(), ldlm_lock::l_last_used, ldlm_lock::l_lru, ldlm_lock::l_resource, LASSERT, ldlm_clear_skipped, LDLM_FLOCK, ldlm_lock_to_ns(), list_add_tail(), list_empty(), ldlm_resource::lr_type, ldlm_namespace::ns_nr_unused, and ldlm_namespace::ns_unused_list.
Referenced by ldlm_lock_add_to_lru(), and ldlm_lock_touch_in_lru().
void ldlm_lock_addref_internal (struct ldlm_lock * lock, enum ldlm_mode mode)
Add specified reader/writer reference to LDLM lock lock.
Locks LDLM lock and calls ldlm_lock_addref_internal_nolock to do the work. Only called for local locks.
Definition at line 786 of file ldlm_lock.c.
References ldlm_lock_addref_internal_nolock(), lock_res_and_lock(), and unlock_res_and_lock().
Referenced by ldlm_cli_enqueue(), and ldlm_lock_addref().
void ldlm_lock_addref_internal_nolock (struct ldlm_lock * lock, enum ldlm_mode mode)
Helper function.
Add specified reader/writer reference to LDLM lock lock. r/w reference type is determined by mode Removes lock from LRU if it is there. Assumes the LDLM lock is already locked.
Definition at line 735 of file ldlm_lock.c.
References ldlm_lock::l_readers, ldlm_lock::l_reference, ldlm_lock::l_writers, LCK_COS, LCK_CR, LCK_CW, LCK_EX, LCK_GROUP, LCK_NL, LCK_PR, LCK_PW, LDLM_DEBUG, LDLM_LOCK_GET, ldlm_lock_remove_from_lru, ldlm_lockname, and lu_ref_add_atomic().
Referenced by ldlm_cli_enqueue_local(), ldlm_lock_addref_internal(), ldlm_lock_addref_try(), ldlm_process_flock_lock(), ldlm_revalidate_lock_handle(), and lock_matches().
struct ldlm_lock* ldlm_lock_create (struct ldlm_namespace * ns, const struct ldlm_res_id * res_id, enum ldlm_type type, enum ldlm_mode mode, const struct ldlm_callback_suite * cbs, void * data, __u32 lvb_len, enum lvb_type lvb_type) [read]
Create and fill in new LDLM lock with specified properties.
Returns a referenced lock
Definition at line 1641 of file ldlm_lock.c.
References current_pid, ENTRY, GOTO, ldlm_lock::l_ast_data, ldlm_lock::l_blocking_ast, ldlm_lock::l_completion_ast, ldlm_lock::l_glimpse_ast, ldlm_lock::l_lvb_data, ldlm_lock::l_lvb_len, ldlm_lock::l_lvb_type, ldlm_lock::l_pid, ldlm_lock::l_req_mode, ldlm_lock::l_tree_node, ldlm_callback_suite::lcs_blocking, ldlm_callback_suite::lcs_completion, ldlm_callback_suite::lcs_glimpse, LDLM_EXTENT, ldlm_interval_alloc(), ldlm_lock_destroy(), ldlm_lock_new(), LDLM_LOCK_RELEASE, ldlm_resource_get(), ldlm_set_ns_srv, ns_is_server(), OBD_ALLOC_LARGE, OBD_FAIL_CHECK, OBD_FAIL_LDLM_NEW_LOCK, and RETURN.
Referenced by ldlm_cli_enqueue(), ldlm_cli_enqueue_local(), and ldlm_process_flock_lock().
void ldlm_lock_decref_internal (struct ldlm_lock * lock, enum ldlm_mode mode)
Removes reader/writer reference for LDLM lock lock.
Locks LDLM lock first. If the lock is determined to be client lock on a client and r/w refcount drops to zero and the lock is not blocked, the lock is added to LRU lock on the namespace. For blocked LDLM locks if r/w count drops to zero, blocking_ast is called.
Definition at line 827 of file ldlm_lock.c.
References CERROR, ENTRY, EXIT, exp_connect_cancelset(), ldlm_lock::l_conn_export, ldlm_lock::l_export, ldlm_lock::l_readers, ldlm_lock::l_req_mode, ldlm_lock::l_writers, LCF_ASYNC, LCK_GROUP, ldlm_bl_to_thread_lock(), ldlm_cancel_lru(), LDLM_DEBUG, ldlm_handle_bl_callback(), ldlm_is_atomic_cb, ldlm_is_bl_ast, ldlm_is_cbpending, ldlm_is_fail_loc, ldlm_is_local, ldlm_is_no_lru, ldlm_is_ns_srv, ldlm_lock_add_to_lru(), ldlm_lock_decref_internal_nolock(), LDLM_LOCK_GET, ldlm_lock_remove_from_lru, ldlm_lock_to_ns(), ldlm_set_cbpending, lock_res_and_lock(), ns_connect_lru_resize(), ns_is_client(), OBD_FAIL_LDLM_CP_BL_RACE, OBD_RACE, and unlock_res_and_lock().
Referenced by failed_lock_cleanup(), ldlm_lock_decref(), ldlm_lock_decref_and_cancel(), and ldlm_lock_match().
void ldlm_lock_decref_internal_nolock (struct ldlm_lock * lock, enum ldlm_mode mode)
Removes reader/writer reference for LDLM lock lock.
Assumes LDLM lock is already locked. only called in ldlm_flock_destroy and for local locks. Does NOT add lock to LRU if no r/w references left to accomodate flock locks that cannot be placed in LRU.
Definition at line 800 of file ldlm_lock.c.
References ldlm_lock::l_readers, ldlm_lock::l_reference, ldlm_lock::l_writers, LASSERT, LCK_COS, LCK_CR, LCK_CW, LCK_EX, LCK_GROUP, LCK_NL, LCK_PR, LCK_PW, LDLM_DEBUG, LDLM_LOCK_RELEASE, ldlm_lockname, and lu_ref_del().
Referenced by failed_lock_cleanup(), ldlm_flock_destroy(), and ldlm_lock_decref_internal().
static int ldlm_lock_destroy_internal (struct ldlm_lock * lock) [static]
Helper to destroy a locked lock.
Used by ldlm_lock_destroy and ldlm_lock_destroy_nolock Must be called with l_lock and lr_lock held.
Does not actually free the lock data, but rather marks the lock as destroyed by setting l_destroyed field in the lock to 1. Destroys a handle->lock association too, so that the lock can no longer be found and removes the lock from LRU list. Actual lock freeing occurs when last lock reference goes away.
Original comment (of some historical value): This used to have a 'strict' flag, which recovery would use to mark an in-use lock as needing-to-die. Lest I am ever tempted to put it back, I shall explain why it's gone: with the new hash table scheme, once you call ldlm_lock_destroy, you can never drop your final references on this lock. Because it's not in the hash table anymore. -phil
Definition at line 352 of file ldlm_lock.c.
References cfs_hash_del(), class_export_put(), class_handle_unhash(), ENTRY, EXIT, obd_export::exp_lock_hash, ldlm_lock::l_completion_ast, ldlm_lock::l_exp_hash, ldlm_lock::l_export, ldlm_lock::l_handle, ldlm_lock::l_lru, ldlm_lock::l_readers, ldlm_lock::l_remote_handle, ldlm_lock::l_res_link, ldlm_lock::l_writers, LASSERT, LBUG, LDLM_ERROR, ldlm_is_destroyed, ldlm_lock_remove_from_lru, ldlm_set_destroyed, and list_empty().
Referenced by ldlm_lock_destroy(), and ldlm_lock_destroy_nolock().
void ldlm_lock_destroy_nolock (struct ldlm_lock * lock)
Destroys a LDLM lock lock that is already locked.
Definition at line 422 of file ldlm_lock.c.
References ENTRY, EXIT, ldlm_lock::l_reference, ldlm_lock_destroy_internal(), LDLM_LOCK_RELEASE, and lu_ref_del().
Referenced by failed_lock_cleanup(), ldlm_flock_destroy(), ldlm_lock_cancel(), ldlm_lock_enqueue(), and ldlm_process_flock_lock().
enum ldlm_error ldlm_lock_enqueue (struct ldlm_namespace * ns, struct ldlm_lock ** lockp, void * cookie, __u64 * flags)
Enqueue (request) a lock.
Does not block. As a result of enqueue the lock would be put into granted or waiting list.
If namespace has intent policy sent and the lock has LDLM_FL_HAS_INTENT flag set, skip all the enqueueing and delegate lock processing to intent policy function.
Definition at line 1708 of file ldlm_lock.c.
References ELDLM_LOCK_REPLACED, ELDLM_OK, ENTRY, GOTO, INIT_LIST_HEAD, ldlm_lock::l_flags, ldlm_lock::l_granted_mode, ldlm_lock::l_req_mode, ldlm_lock::l_resource, ldlm_lock::l_tree_node, LASSERT, LDLM_EXTENT, LDLM_FL_AST_DISCARD_DATA, LDLM_FL_BLOCK_CONV, LDLM_FL_BLOCK_GRANTED, LDLM_FL_BLOCK_WAIT, LDLM_FL_BLOCKED_MASK, LDLM_FL_COS_ENABLED, LDLM_FL_COS_INCOMPAT, LDLM_FL_HAS_INTENT, LDLM_FL_INTENT_ONLY, LDLM_FL_LOCK_CHANGED, LDLM_FL_NO_TIMEOUT, LDLM_FL_REPLAY, LDLM_FL_RESENT, LDLM_FL_TEST_LOCK, ldlm_grant_lock(), ldlm_interval_attach(), ldlm_interval_slab, ldlm_lock_destroy(), ldlm_lock_destroy_nolock(), LDLM_LOCK_RELEASE, ldlm_res_to_ns(), ldlm_resource_add_lock(), ldlm_resource_unlink_lock(), ldlm_set_ast_discard_data, ldlm_set_cos_enabled, ldlm_set_cos_incompat, ldlm_set_test_lock, ldlm_interval::li_group, lock_res_and_lock(), ldlm_resource::lr_converting, ldlm_resource::lr_type, ldlm_resource::lr_waiting, ns_is_client(), ldlm_namespace::ns_policy, OBD_SLAB_ALLOC_PTR_GFP, and RETURN.
Referenced by ldlm_cli_enqueue_fini(), and ldlm_cli_enqueue_local().
static struct ldlm_lock* ldlm_lock_new (struct ldlm_resource * resource) [static, read]
Allocate and initialize new lock structure.
usage: pass in a resource on which you have done ldlm_resource_get new lock will take over the refcount. returns: lock with refcount 2 - one for current caller and one for remote
Definition at line 460 of file ldlm_lock.c.
References class_handle_hash(), ENTRY, portals_handle::h_link, INIT_HLIST_NODE, INIT_LIST_HEAD, ldlm_lock::l_bl_ast, ldlm_lock::l_blocking_lock, ldlm_lock::l_callback_timeout, ldlm_lock::l_cp_ast, ldlm_lock::l_exp_flock_hash, ldlm_lock::l_exp_hash, ldlm_lock::l_exp_list, ldlm_lock::l_handle, ldlm_lock::l_lock, ldlm_lock::l_lru, ldlm_lock::l_pending_chain, ldlm_lock::l_refc, ldlm_lock::l_reference, ldlm_lock::l_res_link, ldlm_lock::l_resource, ldlm_lock::l_rk_ast, ldlm_lock::l_sl_mode, ldlm_lock::l_sl_policy, ldlm_lock::l_waitq, LBUG, ldlm_lock_slab, LDLM_NSS_LOCKS, ldlm_res_to_ns(), lprocfs_counter_incr(), ldlm_resource::lr_reference, lu_ref_add(), lu_ref_init(), OBD_SLAB_ALLOC_PTR_GFP, and RETURN.
Referenced by ldlm_lock_create().
int ldlm_lock_remove_from_lru_check (struct ldlm_lock * lock, cfs_time_t last_use)
Removes LDLM lock lock from LRU.
Obtains the LRU lock first.
If last_use is non-zero, it will remove the lock from LRU only if it matches lock's l_last_used.
Return values:
0 if last_use is set, the lock is not in LRU list or last_use doesn't match lock's l_last_used; otherwise, the lock hasn't been in the LRU list.
1 the lock was in LRU list and removed.
Definition at line 259 of file ldlm_lock.c.
References ENTRY, ldlm_lock::l_last_used, ldlm_lock::l_lru, LASSERT, ldlm_is_ns_srv, ldlm_lock_remove_from_lru_nolock(), ldlm_lock_to_ns(), list_empty(), ldlm_namespace::ns_lock, and RETURN.
Referenced by ldlm_prepare_lru_list().
int ldlm_lock_remove_from_lru_nolock (struct ldlm_lock * lock)
Removes LDLM lock lock from LRU.
Assumes LRU is already locked.
Definition at line 233 of file ldlm_lock.c.
References ldlm_lock::l_lru, ldlm_lock::l_resource, LASSERT, LDLM_FLOCK, ldlm_lock_to_ns(), list_del_init(), list_empty(), ldlm_resource::lr_type, and ldlm_namespace::ns_nr_unused.
Referenced by ldlm_lock_remove_from_lru_check(), ldlm_lock_touch_in_lru(), and ldlm_prepare_lru_list().
void ldlm_lock_touch_in_lru (struct ldlm_lock * lock)
Moves LDLM lock lock that is already in namespace LRU to the tail of the LRU.
Performs necessary LRU locking
Definition at line 313 of file ldlm_lock.c.
References ENTRY, EXIT, ldlm_lock::l_lru, LASSERT, ldlm_is_ns_srv, ldlm_lock_add_to_lru_nolock(), ldlm_lock_remove_from_lru_nolock(), ldlm_lock_to_ns(), list_empty(), and ldlm_namespace::ns_lock.
Referenced by lock_matches().
static int ldlm_reprocess_res (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode, void * arg) [static]
Definition at line 2113 of file ldlm_lock.c.
References cfs_hash_object(), LDLM_ITER_STOP, and reprocess_one_queue().
Referenced by ldlm_reprocess_all_ns().
int ldlm_run_ast_work (struct ldlm_namespace * ns, struct list_head * rpc_list, ldlm_desc_ast_t ast_type)
Process list of locks in need of ASTs being sent.
Used on server to send multiple ASTs together instead of sending one by one.
Definition at line 2050 of file ldlm_lock.c.
References GOTO, LBUG, LDLM_BL_CALLBACK, LDLM_CP_CALLBACK, LDLM_GL_CALLBACK, LDLM_WORK_BL_AST, ldlm_work_bl_ast_lock(), LDLM_WORK_CP_AST, ldlm_work_cp_ast_lock(), LDLM_WORK_GL_AST, ldlm_work_gl_ast_lock(), LDLM_WORK_REVOKE_AST, ldlm_work_revoke_ast_lock(), ldlm_cb_set_arg::list, list_empty(), ldlm_namespace::ns_max_parallel_ast, OBD_ALLOC_PTR, OBD_FREE_PTR, ptlrpc_prep_fcset(), ptlrpc_set_destroy(), ptlrpc_set_wait(), ldlm_cb_set_arg::restart, RETURN, ldlm_cb_set_arg::set, and ldlm_cb_set_arg::type.
Referenced by ldlm_handle_cp_callback(), ldlm_process_flock_lock(), and ldlm_reprocess_all().
static int ldlm_work_bl_ast_lock (struct ptlrpc_request_set * rqset, void * opaq) [static]
Process a call to blocking AST callback for a lock in ast_work list.
Definition at line 1902 of file ldlm_lock.c.
References ENTRY, ldlm_lock::l_bl_ast, ldlm_lock::l_bl_ast_run, ldlm_lock::l_blocking_ast, ldlm_lock::l_blocking_lock, LASSERT, LDLM_CB_BLOCKING, ldlm_is_ast_sent, ldlm_lock2desc(), LDLM_LOCK_RELEASE, ldlm_cb_set_arg::list, list_del_init(), list_empty(), list_entry, lock_res_and_lock(), list_head::next, RETURN, and unlock_res_and_lock().
Referenced by ldlm_run_ast_work().
static int ldlm_work_cp_ast_lock (struct ptlrpc_request_set * rqset, void * opaq) [static]
Process a call to completion AST callback for a lock in ast_work list.
Definition at line 1939 of file ldlm_lock.c.
References ENTRY, ldlm_lock::l_completion_ast, ldlm_lock::l_cp_ast, LASSERT, ldlm_clear_cp_reqd, ldlm_is_cp_reqd, LDLM_LOCK_RELEASE, ldlm_cb_set_arg::list, list_del_init(), list_empty(), list_entry, lock_res_and_lock(), list_head::next, RETURN, and unlock_res_and_lock().
Referenced by ldlm_run_ast_work().
int ldlm_work_gl_ast_lock (struct ptlrpc_request_set * rqset, void * opaq)
Process a call to glimpse AST callback for a lock in ast_work list.
Definition at line 2012 of file ldlm_lock.c.
References ENTRY, ldlm_glimpse_work::gl_desc, ldlm_cb_set_arg::gl_desc, ldlm_glimpse_work::gl_flags, ldlm_glimpse_work::gl_list, ldlm_glimpse_work::gl_lock, ldlm_lock::l_glimpse_ast, LDLM_GL_WORK_NOFREE, LDLM_LOCK_RELEASE, ldlm_cb_set_arg::list, list_del_init(), list_empty(), list_entry, list_head::next, OBD_FREE_PTR, and RETURN.
Referenced by ldlm_run_ast_work().
static int ldlm_work_revoke_ast_lock (struct ptlrpc_request_set * rqset, void * opaq) [static]
Process a call to revocation AST callback for a lock in ast_work list.
Definition at line 1984 of file ldlm_lock.c.
References ENTRY, ldlm_lock::l_blocking_ast, ldlm_lock_desc::l_granted_mode, ldlm_lock_desc::l_req_mode, ldlm_lock::l_rk_ast, LCK_EX, LDLM_CB_BLOCKING, ldlm_lock2desc(), LDLM_LOCK_RELEASE, ldlm_cb_set_arg::list, list_del_init(), list_empty(), list_entry, list_head::next, and RETURN.
Referenced by ldlm_run_ast_work().
static void lock_handle_addref (void * lock) [static]
Definition at line 436 of file ldlm_lock.c.
References LDLM_LOCK_GET.
static void lock_handle_free (void * lock, int size) [static]
Definition at line 441 of file ldlm_lock.c.
References LASSERT, ldlm_lock_slab, and OBD_SLAB_FREE.
static int lock_matches (struct ldlm_lock * lock, struct lock_match_data * data) [static]
Check if the given meets the criteria for a match.
A reference on the lock is taken if matched.
Parameters:
lock test-against this lock
data parameters
Definition at line 1154 of file ldlm_lock.c.
References ldlm_inodebits::bits, ldlm_extent::end, equi, ldlm_extent::gid, INTERVAL_ITER_CONT, INTERVAL_ITER_STOP, ldlm_policy_data::l_extent, ldlm_policy_data::l_inodebits, ldlm_lock::l_policy_data, ldlm_lock::l_readers, ldlm_lock::l_req_mode, ldlm_lock::l_resource, ldlm_lock::l_writers, LCK_GROUP, LDLM_EXTENT, LDLM_FL_CBPENDING, LDLM_FL_LOCAL_ONLY, LDLM_FL_TEST_LOCK, LDLM_GID_ANY, LDLM_HAVE_MASK, LDLM_IBITS, ldlm_is_cbpending, ldlm_is_excl, ldlm_is_local, ldlm_lock_addref_internal_nolock(), LDLM_LOCK_GET, ldlm_lock_touch_in_lru(), lock_match_data::lmd_flags, lock_match_data::lmd_lock, lock_match_data::lmd_old, lock_match_data::lmd_policy, lock_match_data::lmd_unref, ldlm_resource::lr_type, ldlm_extent::start, and unlikely.
Referenced by itree_overlap_cb(), and search_queue().
static int reprocess_one_queue (struct ldlm_resource * res, void * closure) [static]
Definition at line 2107 of file ldlm_lock.c.
References LDLM_ITER_CONTINUE, and ldlm_reprocess_all().
Referenced by ldlm_reprocess_res().
static void search_granted_lock (struct list_head * queue, struct ldlm_lock * req, struct sl_insert_point * prev) [static]
Finds a position to insert the new lock into granted lock list.
Used for locks eligible for skiplist optimization.
Parameters: queue [input]: the granted list where search acts on; req [input]: the lock whose position to be located; prev [output]: positions within 3 lists to insert to Return Value: filled NOTE: called by
ldlm_grant_lock_with_skiplist
Definition at line 955 of file ldlm_lock.c.
References ldlm_inodebits::bits, ENTRY, EXIT, ldlm_policy_data::l_inodebits, ldlm_lock::l_policy_data, ldlm_lock::l_req_mode, ldlm_lock::l_res_link, ldlm_lock::l_resource, ldlm_lock::l_sl_mode, ldlm_lock::l_sl_policy, LBUG, LDLM_ERROR, LDLM_IBITS, LDLM_PLAIN, list_entry, list_for_each, ldlm_resource::lr_type, sl_insert_point::mode_link, list_head::next, sl_insert_point::policy_link, list_head::prev, and sl_insert_point::res_link.
Referenced by ldlm_grant_lock_with_skiplist().
static struct ldlm_lock* search_itree (struct ldlm_resource * res, struct lock_match_data * data) [static, read]
Search for a lock with given parameters in interval trees.
Parameters:
res search for a lock in this resource
data parameters
Return values:
a referenced lock or NULL.
Definition at line 1251 of file ldlm_lock.c.
References ldlm_extent::end, interval_search(), itree_overlap_cb(), ldlm_policy_data::l_extent, LCK_MODE_NUM, ldlm_interval_tree::lit_mode, ldlm_interval_tree::lit_root, lock_match_data::lmd_lock, lock_match_data::lmd_policy, ldlm_resource::lr_itree, and ldlm_extent::start.
Referenced by ldlm_lock_match().
static struct ldlm_lock* search_queue (struct list_head * queue, struct lock_match_data * data) [static, read]
Search for a lock with given properties in a queue.
Parameters:
queue search for a lock in this queue
data parameters
Return values:
a referenced lock or NULL.
Definition at line 1284 of file ldlm_lock.c.
References INTERVAL_ITER_STOP, ldlm_lock::l_res_link, list_for_each_entry, lock_match_data::lmd_lock, and lock_matches().
Referenced by ldlm_lock_match().
Variable Documentation
struct kmem_cache* ldlm_lock_slab
Definition at line 48 of file ldlm_resource.c.
ldlm_policy_local_to_wire_t ldlm_policy_local_to_wire[] [static]
Initial value:
 {
        [LDLM_PLAIN - LDLM_MIN_TYPE]  = ldlm_plain_policy_local_to_wire,
        [LDLM_EXTENT - LDLM_MIN_TYPE] = ldlm_extent_policy_local_to_wire,
        [LDLM_FLOCK - LDLM_MIN_TYPE]  = ldlm_flock_policy_local_to_wire,
        [LDLM_IBITS - LDLM_MIN_TYPE]  = ldlm_ibits_policy_local_to_wire,
}
Definition at line 79 of file ldlm_lock.c.
Referenced by ldlm_convert_policy_to_wire().
ldlm_policy_wire_to_local_t ldlm_policy_wire_to_local[] [static]
Initial value:
 {
        [LDLM_PLAIN - LDLM_MIN_TYPE]  = ldlm_plain_policy_wire_to_local,
        [LDLM_EXTENT - LDLM_MIN_TYPE] = ldlm_extent_policy_wire_to_local,
        [LDLM_FLOCK - LDLM_MIN_TYPE]  = ldlm_flock_policy_wire_to_local,
        [LDLM_IBITS - LDLM_MIN_TYPE]  = ldlm_ibits_policy_wire_to_local,
}
Definition at line 72 of file ldlm_lock.c.
Referenced by ldlm_convert_policy_to_local().
struct portals_handle_ops lock_handle_ops [static]
Initial value:
 {
        .hop_addref = lock_handle_addref,
        .hop_free   = lock_handle_free,
}
Definition at line 447 of file ldlm_lock.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.