Lustre: lustre/ldlm/ldlm_resource.c File Reference
lustre/ldlm/ldlm_resource.c File Reference
#include <lustre_dlm.h>
#include <lustre_fid.h>
#include <obd_class.h>
#include "ldlm_internal.h"
Data Structures
struct ldlm_ns_hash_def
Defines
#define DEBUG_SUBSYSTEM S_LDLM
#define ldlm_namespace_proc_unregister(ns) ({;})
#define ldlm_namespace_proc_register(ns) ({0;})
Typedefs
typedef struct ldlm_ns_hash_def ldlm_ns_hash_def_t
Functions
static unsigned ldlm_res_hop_hash (struct cfs_hash *hs, const void *key, unsigned mask)
static unsigned ldlm_res_hop_fid_hash (struct cfs_hash *hs, const void *key, unsigned mask)
static void * ldlm_res_hop_key (struct hlist_node *hnode)
static int ldlm_res_hop_keycmp (const void *key, struct hlist_node *hnode)
static void * ldlm_res_hop_object (struct hlist_node *hnode)
static void ldlm_res_hop_get_locked (struct cfs_hash *hs, struct hlist_node *hnode)
static void ldlm_res_hop_put (struct cfs_hash *hs, struct hlist_node *hnode)
struct ldlm_namespace * ldlm_namespace_new (struct obd_device *obd, char *name, enum ldlm_side client, enum ldlm_appetite apt, enum ldlm_ns_type ns_type)
Create and initialize new empty namespace.
struct ldlm_lock * ldlm_lock_get (struct ldlm_lock *lock)
Get a reference on a lock.
static void cleanup_resource (struct ldlm_resource *res, struct list_head *q, __u64 flags)
Cancel and destroy all locks on a resource.
static int ldlm_resource_clean (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode, void *arg)
static int ldlm_resource_complain (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode, void *arg)
int ldlm_namespace_cleanup (struct ldlm_namespace *ns, __u64 flags)
Cancel and destroy all locks in the namespace.
static int __ldlm_namespace_free (struct ldlm_namespace *ns, int force)
Attempts to free namespace.
void ldlm_namespace_free_prior (struct ldlm_namespace *ns, struct obd_import *imp, int force)
Performs various cleanups for passed ns to make it drop refc and be ready for freeing.
void ldlm_namespace_free_post (struct ldlm_namespace *ns)
Performs freeing memory structures related to ns.
void ldlm_namespace_free (struct ldlm_namespace *ns, struct obd_import *imp, int force)
Cleanup the resource, and free namespace.
void ldlm_namespace_get (struct ldlm_namespace *ns)
static int ldlm_namespace_get_return (struct ldlm_namespace *ns)
void ldlm_namespace_put (struct ldlm_namespace *ns)
void ldlm_namespace_register (struct ldlm_namespace *ns, enum ldlm_side client)
Register ns in the list of namespaces.
void ldlm_namespace_unregister (struct ldlm_namespace *ns, enum ldlm_side client)
Unregister ns from the list of namespaces.
void ldlm_namespace_move_to_active_locked (struct ldlm_namespace *ns, enum ldlm_side client)
Should be called with ldlm_namespace_lock(client) taken.
void ldlm_namespace_move_to_inactive_locked (struct ldlm_namespace *ns, enum ldlm_side client)
Should be called with ldlm_namespace_lock(client) taken.
struct ldlm_namespace * ldlm_namespace_first_locked (enum ldlm_side client)
Should be called with ldlm_namespace_lock(client) taken.
static struct ldlm_resource * ldlm_resource_new (enum ldlm_type ldlm_type)
Create and initialize new resource.
struct ldlm_resource * ldlm_resource_get (struct ldlm_namespace *ns, struct ldlm_resource *parent, const struct ldlm_res_id *name, enum ldlm_type type, int create)
Return a reference to resource with given name, creating it if necessary.
struct ldlm_resource * ldlm_resource_getref (struct ldlm_resource *res)
static void __ldlm_resource_putref_final (struct cfs_hash_bd *bd, struct ldlm_resource *res)
int ldlm_resource_putref (struct ldlm_resource *res)
void ldlm_resource_add_lock (struct ldlm_resource *res, struct list_head *head, struct ldlm_lock *lock)
Add a lock into a given resource into specified lock list.
void ldlm_resource_insert_lock_after (struct ldlm_lock *original, struct ldlm_lock *new)
Insert a lock into resource after specified lock.
void ldlm_resource_unlink_lock (struct ldlm_lock *lock)
void ldlm_res2desc (struct ldlm_resource *res, struct ldlm_resource_desc *desc)
void ldlm_dump_all_namespaces (enum ldlm_side client, int level)
Print information about all locks in all namespaces on this node to debug log.
static int ldlm_res_hash_dump (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode, void *arg)
void ldlm_namespace_dump (int level, struct ldlm_namespace *ns)
Print information about all locks in this namespace on this node to debug log.
void ldlm_resource_dump (int level, struct ldlm_resource *res)
Print information about all locks in this resource to debug log.
Variables
struct kmem_cache * ldlm_resource_slab
struct kmem_cache * ldlm_lock_slab
struct kmem_cache * ldlm_interval_tree_slab
int ldlm_srv_namespace_nr = 0
int ldlm_cli_namespace_nr = 0
struct mutex ldlm_srv_namespace_lock
struct list_head ldlm_srv_namespace_list
struct mutex ldlm_cli_namespace_lock
struct list_head ldlm_cli_active_namespace_list
struct list_head ldlm_cli_inactive_namespace_list
static struct proc_dir_entry * ldlm_type_proc_dir
static struct proc_dir_entry * ldlm_ns_proc_dir
struct proc_dir_entry * ldlm_svc_proc_dir
static unsigned int ldlm_dump_granted_max = 256
static struct cfs_hash_ops ldlm_ns_hash_ops
static struct cfs_hash_ops ldlm_ns_fid_hash_ops
static struct ldlm_ns_hash_def ldlm_ns_hash_defs []
Define Documentation
#define DEBUG_SUBSYSTEM S_LDLM
Definition at line 42 of file ldlm_resource.c.
#define ldlm_namespace_proc_register (ns) ({0;})
Definition at line 500 of file ldlm_resource.c.
Referenced by ldlm_namespace_new().
#define ldlm_namespace_proc_unregister (ns) ({;})
Definition at line 499 of file ldlm_resource.c.
Referenced by ldlm_namespace_free_post(), and ldlm_namespace_new().
Typedef Documentation
typedef struct ldlm_ns_hash_def ldlm_ns_hash_def_t
Function Documentation
static int __ldlm_namespace_free (struct ldlm_namespace * ns, int force) [static]
Attempts to free namespace.
Only used when namespace goes away, like during an unmount.
Definition at line 912 of file ldlm_resource.c.
References CDEBUG, D_DLMTRACE, ELDLM_NAMESPACE_EXISTS, ELDLM_OK, ENTRY, GOTO, l_wait_event, LCONSOLE_ERROR, LDLM_FL_LOCAL_ONLY, ldlm_namespace_cleanup(), ldlm_ns_name(), LWI_INTR, LWI_ON_SIGNAL_NOOP, LWI_TIMEOUT, ldlm_namespace::ns_bref, ldlm_namespace::ns_waitq, obd_timeout, and RETURN.
Referenced by ldlm_namespace_free_prior().
static void __ldlm_resource_putref_final (struct cfs_hash_bd * bd, struct ldlm_resource * res) [static]
Definition at line 1267 of file ldlm_resource.c.
References cfs_hash_bd_count_get(), cfs_hash_bd_del_locked(), D_ERROR, LBUG, ldlm_namespace_put(), ldlm_resource_dump(), list_empty(), ldlm_resource::lr_converting, ldlm_resource::lr_granted, ldlm_resource::lr_hash, ldlm_resource::lr_ns_bucket, ldlm_resource::lr_reference, ldlm_resource::lr_waiting, lu_ref_fini(), ldlm_namespace::ns_rs_hash, and ldlm_ns_bucket::nsb_namespace.
Referenced by ldlm_resource_putref().
static void cleanup_resource (struct ldlm_resource * res, struct list_head * q, __u64 flags) [static]
Cancel and destroy all locks on a resource.
If flags contains FL_LOCAL_ONLY, don't try to tell the server, just clean up. This is currently only used for recovery, and we make certain assumptions as a result--notably, that we shouldn't cancel locks with refs.
Definition at line 779 of file ldlm_resource.c.
References CERROR, cfs_time_seconds(), ldlm_lock::l_completion_ast, ldlm_lock::l_flags, ldlm_lock::l_readers, ldlm_lock::l_res_link, ldlm_lock::l_writers, LCF_LOCAL, ldlm_cli_cancel(), LDLM_DEBUG, LDLM_FL_FAIL_LOC, LDLM_FL_FAILED, LDLM_FL_LOCAL_ONLY, ldlm_is_cleaned, ldlm_lock2handle(), ldlm_lock_cancel(), LDLM_LOCK_GET, LDLM_LOCK_RELEASE, ldlm_res_to_ns(), ldlm_set_cbpending, ldlm_set_cleaned, ldlm_set_failed, ldlm_set_local_only, list_entry, list_for_each, lock_res(), ns_is_client(), and unlock_res().
Referenced by ldlm_resource_clean().
struct ldlm_namespace* ldlm_namespace_first_locked (enum ldlm_side client) [read]
Should be called with ldlm_namespace_lock(client) taken.
Definition at line 1123 of file ldlm_resource.c.
References LASSERT, ldlm_namespace_list(), ldlm_namespace_lock(), list_empty(), and ldlm_namespace::ns_list_chain.
static int ldlm_namespace_get_return (struct ldlm_namespace * ns) [static]
Definition at line 1067 of file ldlm_resource.c.
References ldlm_namespace::ns_bref.
Referenced by ldlm_resource_get().
void ldlm_namespace_move_to_active_locked (struct ldlm_namespace * ns, enum ldlm_side client)
Should be called with ldlm_namespace_lock(client) taken.
Definition at line 1104 of file ldlm_resource.c.
References LASSERT, ldlm_namespace_list(), ldlm_namespace_lock(), list_empty(), list_move_tail(), and ldlm_namespace::ns_list_chain.
Referenced by ldlm_resource_get().
void ldlm_namespace_move_to_inactive_locked (struct ldlm_namespace * ns, enum ldlm_side client)
Should be called with ldlm_namespace_lock(client) taken.
Definition at line 1113 of file ldlm_resource.c.
References LASSERT, ldlm_namespace_inactive_list(), ldlm_namespace_lock(), list_empty(), list_move_tail(), and ldlm_namespace::ns_list_chain.
static int ldlm_res_hash_dump (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode, void * arg) [static]
Definition at line 1408 of file ldlm_resource.c.
References cfs_hash_object(), ldlm_resource_dump(), lock_res(), and unlock_res().
Referenced by ldlm_namespace_dump().
static unsigned ldlm_res_hop_fid_hash (struct cfs_hash * hs, const void * key, unsigned mask) [static]
Definition at line 516 of file ldlm_resource.c.
References CFS_HASH_NBKT, lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, fid_flatten32(), fid_oid(), cfs_hash::hs_bkt_bits, ldlm_res_hop_hash(), LUSTRE_RES_ID_HSH_OFF, LUSTRE_RES_ID_SEQ_OFF, LUSTRE_RES_ID_VER_OID_OFF, and ldlm_res_id::name.
static void ldlm_res_hop_get_locked (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 569 of file ldlm_resource.c.
References hlist_entry, ldlm_resource_getref(), and ldlm_resource::lr_hash.
static unsigned ldlm_res_hop_hash (struct cfs_hash * hs, const void * key, unsigned mask) [static]
Definition at line 504 of file ldlm_resource.c.
References ldlm_res_id::name, and RES_NAME_SIZE.
Referenced by ldlm_res_hop_fid_hash().
static void* ldlm_res_hop_key (struct hlist_node * hnode) [static]
Definition at line 546 of file ldlm_resource.c.
References hlist_entry, ldlm_resource::lr_hash, and ldlm_resource::lr_name.
static int ldlm_res_hop_keycmp (const void * key, struct hlist_node * hnode) [static]
Definition at line 554 of file ldlm_resource.c.
References hlist_entry, ldlm_res_eq(), ldlm_resource::lr_hash, and ldlm_resource::lr_name.
static void* ldlm_res_hop_object (struct hlist_node * hnode) [static]
Definition at line 563 of file ldlm_resource.c.
References hlist_entry, and ldlm_resource::lr_hash.
static void ldlm_res_hop_put (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 577 of file ldlm_resource.c.
References hlist_entry, ldlm_resource_putref(), and ldlm_resource::lr_hash.
static int ldlm_resource_clean (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode, void * arg) [static]
Definition at line 856 of file ldlm_resource.c.
References __u64, cfs_hash_object(), cleanup_resource(), ldlm_resource::lr_converting, ldlm_resource::lr_granted, and ldlm_resource::lr_waiting.
Referenced by ldlm_namespace_cleanup().
static int ldlm_resource_complain (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode, void * arg) [static]
Definition at line 869 of file ldlm_resource.c.
References CERROR, cfs_hash_object(), D_ERROR, DLDLMRES, ldlm_ns_name(), ldlm_res_to_ns(), ldlm_resource_dump(), lock_res(), ldlm_resource::lr_refcount, PLDLMRES, and unlock_res().
Referenced by ldlm_namespace_cleanup().
void ldlm_resource_insert_lock_after (struct ldlm_lock * original, struct ldlm_lock * new)
Insert a lock into resource after specified lock.
Obtain resource description from the lock we are inserting after.
Definition at line 1345 of file ldlm_resource.c.
References CDEBUG, check_res_locked(), D_INFO, D_OTHER, ldlm_lock::l_res_link, ldlm_lock::l_resource, LASSERT, LDLM_DEBUG, ldlm_is_destroyed, ldlm_resource_dump(), list_add(), and list_empty().
static struct ldlm_resource* ldlm_resource_new (enum ldlm_type ldlm_type) [static, read]
Create and initialize new resource.
Definition at line 1132 of file ldlm_resource.c.
References INIT_LIST_HEAD, LCK_MODE_NUM, LDLM_EXTENT, ldlm_interval_tree_slab, ldlm_resource_slab, ldlm_interval_tree::lit_mode, ldlm_interval_tree::lit_root, ldlm_interval_tree::lit_size, ldlm_resource::lr_converting, ldlm_resource::lr_granted, ldlm_resource::lr_itree, ldlm_resource::lr_lock, ldlm_resource::lr_lvb_initialized, ldlm_resource::lr_lvb_mutex, ldlm_resource::lr_refcount, ldlm_resource::lr_reference, ldlm_resource::lr_waiting, lu_ref_init(), OBD_SLAB_ALLOC, OBD_SLAB_ALLOC_PTR_GFP, and OBD_SLAB_FREE_PTR.
Referenced by ldlm_resource_get().
Variable Documentation
struct list_head ldlm_cli_active_namespace_list
Definition at line 61 of file ldlm_resource.c.
Referenced by ldlm_init(), and ldlm_namespace_list().
struct list_head ldlm_cli_inactive_namespace_list
Definition at line 63 of file ldlm_resource.c.
Referenced by ldlm_init(), and ldlm_namespace_inactive_list().
struct mutex ldlm_cli_namespace_lock
Definition at line 57 of file ldlm_resource.c.
Referenced by ldlm_namespace_lock().
int ldlm_cli_namespace_nr = 0
Definition at line 52 of file ldlm_resource.c.
Referenced by ldlm_namespace_nr_dec(), ldlm_namespace_nr_inc(), and ldlm_namespace_nr_read().
unsigned int ldlm_dump_granted_max = 256 [static]
Definition at line 71 of file ldlm_resource.c.
Referenced by ldlm_resource_dump().
struct kmem_cache* ldlm_interval_tree_slab
Definition at line 49 of file ldlm_resource.c.
Referenced by ldlm_exit(), ldlm_init(), ldlm_resource_get(), ldlm_resource_new(), and ldlm_resource_putref().
struct kmem_cache * ldlm_lock_slab
Definition at line 48 of file ldlm_resource.c.
Referenced by ldlm_exit(), ldlm_init(), ldlm_lock_new(), and lock_handle_free().
struct cfs_hash_ops ldlm_ns_fid_hash_ops [static]
Initial value:
 {
        .hs_hash        = ldlm_res_hop_fid_hash,
        .hs_key         = ldlm_res_hop_key,
        .hs_keycmp      = ldlm_res_hop_keycmp,
        .hs_keycpy      = NULL,
        .hs_object      = ldlm_res_hop_object,
        .hs_get         = ldlm_res_hop_get_locked,
        .hs_put         = ldlm_res_hop_put
}
Definition at line 595 of file ldlm_resource.c.
struct ldlm_ns_hash_def ldlm_ns_hash_defs[] [static]
Definition at line 615 of file ldlm_resource.c.
struct cfs_hash_ops ldlm_ns_hash_ops [static]
Initial value:
 {
        .hs_hash        = ldlm_res_hop_hash,
        .hs_key         = ldlm_res_hop_key,
        .hs_keycmp      = ldlm_res_hop_keycmp,
        .hs_keycpy      = NULL,
        .hs_object      = ldlm_res_hop_object,
        .hs_get         = ldlm_res_hop_get_locked,
        .hs_put         = ldlm_res_hop_put
}
Definition at line 585 of file ldlm_resource.c.
struct proc_dir_entry* ldlm_ns_proc_dir [static]
Definition at line 66 of file ldlm_resource.c.
struct kmem_cache* ldlm_resource_slab
Definition at line 48 of file ldlm_resource.c.
Referenced by ldlm_exit(), ldlm_init(), ldlm_resource_get(), ldlm_resource_new(), and ldlm_resource_putref().
struct list_head ldlm_srv_namespace_list
Definition at line 55 of file ldlm_resource.c.
Referenced by ldlm_init(), ldlm_namespace_inactive_list(), and ldlm_namespace_list().
struct mutex ldlm_srv_namespace_lock
Definition at line 54 of file ldlm_resource.c.
Referenced by ldlm_namespace_lock().
int ldlm_srv_namespace_nr = 0
Definition at line 51 of file ldlm_resource.c.
Referenced by ldlm_namespace_nr_dec(), ldlm_namespace_nr_inc(), and ldlm_namespace_nr_read().
struct proc_dir_entry* ldlm_svc_proc_dir
Definition at line 67 of file ldlm_resource.c.
Referenced by ldlm_setup().
struct proc_dir_entry* ldlm_type_proc_dir [static]
Definition at line 65 of file ldlm_resource.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.