Lustre: lustre/utils/lfs.c File Reference
lustre/utils/lfs.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <getopt.h>
#include <string.h>
#include <mntent.h>
#include <unistd.h>
#include <errno.h>
#include <err.h>
#include <pwd.h>
#include <grp.h>
#include <sys/ioctl.h>
#include <sys/quota.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <dirent.h>
#include <time.h>
#include <ctype.h>
#include <libcfs/util/ioctl.h>
#include <libcfs/util/parser.h>
#include <lustre/lustreapi.h>
#include <lustre_ver.h>
#include <lustre_param.h>
Data Structures
struct ll_stat_type
Defines
#define SSM_CMD_COMMON(cmd)
#define SSM_HELP_COMMON
#define SETSTRIPE_USAGE
#define MIGRATE_USAGE
#define MIGRATION_NONBLOCK 1
#define USER 0
#define GROUP 1
#define FIND_POOL_OPT 3
#define COOK(value)
#define UUF "%-20s"
#define CSF "%11s"
#define CDF "%11llu"
#define HDF "%8.1f%c"
#define RSF "%4s"
#define RDF "%3d%%"
#define LFS_HSM_SET 0
#define LFS_HSM_CLEAR 1
Functions
static int lfs_setstripe (int argc, char **argv)
static int lfs_find (int argc, char **argv)
static int lfs_getstripe (int argc, char **argv)
static int lfs_getdirstripe (int argc, char **argv)
static int lfs_setdirstripe (int argc, char **argv)
static int lfs_rmentry (int argc, char **argv)
static int lfs_osts (int argc, char **argv)
static int lfs_mdts (int argc, char **argv)
static int lfs_df (int argc, char **argv)
static int lfs_getname (int argc, char **argv)
static int lfs_check (int argc, char **argv)
static int lfs_flushctx (int argc, char **argv)
static int lfs_join (int argc, char **argv)
static int lfs_lsetfacl (int argc, char **argv)
static int lfs_lgetfacl (int argc, char **argv)
static int lfs_rsetfacl (int argc, char **argv)
static int lfs_rgetfacl (int argc, char **argv)
static int lfs_cp (int argc, char **argv)
static int lfs_ls (int argc, char **argv)
static int lfs_poollist (int argc, char **argv)
static int lfs_changelog (int argc, char **argv)
static int lfs_changelog_clear (int argc, char **argv)
static int lfs_fid2path (int argc, char **argv)
static int lfs_path2fid (int argc, char **argv)
static int lfs_data_version (int argc, char **argv)
static int lfs_hsm_state (int argc, char **argv)
static int lfs_hsm_set (int argc, char **argv)
static int lfs_hsm_clear (int argc, char **argv)
static int lfs_hsm_action (int argc, char **argv)
static int lfs_hsm_archive (int argc, char **argv)
static int lfs_hsm_restore (int argc, char **argv)
static int lfs_hsm_release (int argc, char **argv)
static int lfs_hsm_remove (int argc, char **argv)
static int lfs_hsm_cancel (int argc, char **argv)
static int lfs_swap_layouts (int argc, char **argv)
static int lfs_mv (int argc, char **argv)
static int lfs_ladvise (int argc, char **argv)
static int check_lease (int fd, bool *lease_broken, bool group_locked, const char *path)
Internal helper for migrate_copy_data().
static int migrate_copy_data (int fd_src, int fd_dst, size_t buf_size, bool group_locked, const char *fname)
static int migrate_copy_timestamps (int fdv, const struct stat *st)
static int migrate_block (int fd, int fdv, const struct stat *st, size_t buf_size, const char *name)
static int migrate_nonblock (int fd, int fdv, const struct stat *st, size_t buf_size, const char *name)
static int lfs_migrate (char *name, __u64 migration_flags, struct llapi_stripe_param *param)
static int parse_targets (__u32 *osts, int size, int offset, char *arg)
Parse a string containing an OST index list into an array of integers.
static int set_time (time_t *time, time_t *set, char *str)
static int name2id (unsigned int *id, char *name, int type)
static int id2name (char **name, unsigned int id, int type)
static int name2layout (__u32 *layout, char *name)
static int lfs_getstripe_internal (int argc, char **argv, struct find_param *param)
static int lfs_tgts (int argc, char **argv)
static int showdf (char *mntdir, struct obd_statfs *stat, char *uuid, int ishow, int cooked, char *type, int index, int rc)
static int mntdf (char *mntdir, char *fsname, char *pool, int ishow, int cooked, int lazy)
static int flushctx_ioctl (char *mp)
static int lfs_hsm_change_flags (int argc, char **argv, int mode)
Generic function to set or clear HSM flags.
static int lfs_hsm_prepare_file (const char *file, struct lu_fid *fid, dev_t *last_dev)
Check file state and return its fid, to be used by lfs_hsm_request().
static int fill_hur_item (struct hsm_user_request *hur, unsigned int idx, const char *mntpath, const char *fname, dev_t *last_dev)
static int lfs_hsm_request (int argc, char **argv, int action)
static enum lu_ladvise_type lfs_get_ladvice (const char *string)
int main (int argc, char **argv)
Variables
static const char * progname
static bool file_lease_supported = true
command_t cmdlist []
static const char *const ladvise_names [] = LU_LADVISE_NAMES
Define Documentation
#define CDF "%11llu"
Definition at line 2203 of file lfs.c.
Referenced by showdf().
#define COOK (value)
Value:
({                                                                      \
        int radix = 0;                                                  \
        while (value > 1024) {                                          \
                value /= 1024;                                          \
                radix++;                                                \
        }                                                               \
        radix;                                                          \
})
Definition at line 2192 of file lfs.c.
Referenced by showdf().
#define CSF "%11s"
Definition at line 2202 of file lfs.c.
Referenced by mntdf(), and showdf().
#define FIND_POOL_OPT 3
Definition at line 1344 of file lfs.c.
Referenced by lfs_find().
#define GROUP 1
Definition at line 1269 of file lfs.c.
Referenced by lfs_find().
#define HDF "%8.1f%c"
Definition at line 2204 of file lfs.c.
Referenced by showdf().
#define LFS_HSM_CLEAR 1
Definition at line 3773 of file lfs.c.
Referenced by lfs_hsm_clear().
#define LFS_HSM_SET 0
Definition at line 3772 of file lfs.c.
Referenced by lfs_hsm_change_flags(), and lfs_hsm_set().
#define MIGRATE_USAGE
Value:
SSM_CMD_COMMON("migrate  ")                                     \
        "                 [--block|-b]\n"                               \
        "                 [--non-block|-n]\n"                           \
        "                 <filename>\n"                                 \
        SSM_HELP_COMMON                                                 \
        "\n"                                                            \
        "\tblock:        Block file access during data migration (default)\n" \
        "\tnon-block:    Abort migrations if concurrent access is detected\n" \
Definition at line 149 of file lfs.c.
#define MIGRATION_NONBLOCK 1
Definition at line 403 of file lfs.c.
Referenced by lfs_migrate(), and lfs_setstripe().
#define RDF "%3d%%"
Definition at line 2206 of file lfs.c.
Referenced by showdf().
#define RSF "%4s"
Definition at line 2205 of file lfs.c.
Referenced by mntdf(), and showdf().
#define SETSTRIPE_USAGE
Value:
SSM_CMD_COMMON("setstripe")                             \
        "                 <directory|filename>\n"               \
        SSM_HELP_COMMON
Definition at line 144 of file lfs.c.
#define SSM_CMD_COMMON (cmd)
Value:
"usage: "cmd" [--stripe-count|-c <stripe_count>]\n"             \
        "                 [--stripe-index|-i <start_ost_idx>]\n"        \
        "                 [--stripe-size|-S <stripe_size>]\n"           \
        "                 [--pool|-p <pool_name>]\n"                    \
        "                 [--ost-list|-o <ost_indices>]\n"
Definition at line 122 of file lfs.c.
#define SSM_HELP_COMMON
Value:
"\tstripe_size:  Number of bytes on each OST (0 filesystem default)\n" \
        "\t              Can be specified with k, m or g (in KB, MB and GB\n" \
        "\t              respectively)\n"                               \
        "\tstart_ost_idx: OST index of first stripe (-1 default)\n"     \
        "\tstripe_count: Number of OSTs to stripe over (0 default, -1 all)\n" \
        "\tpool_name:    Name of OST pool to use (default none)\n"      \
        "\tost_indices:  List of OST indices, can be repeated multiple times\n"\
        "\t              Indices be specified in a format of:\n"        \
        "\t                -o <ost_1>,<ost_i>-<ost_j>,<ost_n>\n"        \
        "\t              Or:\n"                                         \
        "\t                -o <ost_1> -o <ost_i>-<ost_j> -o <ost_n>\n"  \
        "\t              If --pool is set with --ost-list, then the OSTs\n" \
        "\t              must be the members of the pool."
Definition at line 129 of file lfs.c.
#define USER 0
Definition at line 1268 of file lfs.c.
Referenced by id2name(), lfs_find(), and name2id().
#define UUF "%-20s"
Definition at line 2201 of file lfs.c.
Referenced by mntdf(), and showdf().
Function Documentation
static int check_lease (int fd, bool * lease_broken, bool group_locked, const char * path) [static]
Internal helper for migrate_copy_data().
Check lease and report error if need be.
Parameters:
[in] fd File descriptor on which to check the lease.
[out] lease_broken Set to true if the lease was broken.
[in] group_locked Whether a group lock was taken or not.
[in] path Name of the file being processed, for error reporting
Return values:
0 Migration can keep on going.
-errno Error occurred, abort migration.
Definition at line 418 of file lfs.c.
References file_lease_supported, llapi_lease_check(), and progname.
Referenced by migrate_copy_data().
static int fill_hur_item (struct hsm_user_request * hur, unsigned int idx, const char * mntpath, const char * fname, dev_t * last_dev) [static]
Definition at line 3977 of file lfs.c.
References hsm_request::hr_itemcount, hsm_user_item::hui_extent, hsm_user_item::hui_fid, hsm_user_request::hur_request, hsm_user_request::hur_user_item, hsm_extent::length, lfs_hsm_prepare_file(), RFID, and SFID.
Referenced by lfs_hsm_request().
static int flushctx_ioctl (char * mp) [static]
Definition at line 3289 of file lfs.c.
References LL_IOC_FLUSHCTX.
Referenced by lfs_flushctx().
static int id2name (char ** name, unsigned int id, int type) [static]
Definition at line 1298 of file lfs.c.
References USER.
static int lfs_changelog (int argc, char ** argv) [static]
Definition at line 3391 of file lfs.c.
References CHANGELOG_FLAG_BLOCK, CHANGELOG_FLAG_FOLLOW, CHANGELOG_FLAG_JOBID, changelog_rec_jobid(), changelog_rec_name(), changelog_rec_rename(), changelog_rec_sname(), changelog_rec_snamelen(), changelog_type2str(), CLF_FLAGMASK, CLF_JOBID, CLF_RENAME, CMD_HELP, changelog_rec::cr_flags, changelog_rec::cr_index, changelog_ext_jobid::cr_jobid, changelog_rec::cr_namelen, changelog_rec::cr_pfid, changelog_ext_rename::cr_sfid, changelog_ext_rename::cr_spfid, changelog_rec::cr_tfid, changelog_rec::cr_time, changelog_rec::cr_type, DFID, fid_is_zero(), llapi_changelog_fini(), llapi_changelog_free(), llapi_changelog_recv(), llapi_changelog_start(), optind, and PFID.
static int lfs_changelog_clear (int argc, char ** argv) [static]
Definition at line 3497 of file lfs.c.
References CMD_HELP, and llapi_changelog_clear().
static int lfs_check (int argc, char ** argv) [static]
Definition at line 2487 of file lfs.c.
References CMD_HELP, llapi_search_mounts(), llapi_target_check(), and obd_types.
static int lfs_cp (int argc, char ** argv) [static]
Definition at line 3381 of file lfs.c.
References llapi_cp().
static int lfs_data_version (int argc, char ** argv) [static]
Definition at line 3679 of file lfs.c.
References __u64, CMD_HELP, LL_DV_RD_FLUSH, LL_DV_WR_FLUSH, llapi_get_data_version(), optind, and path.
static int lfs_df (int argc, char ** argv) [static]
Definition at line 2395 of file lfs.c.
References CMD_HELP, llapi_search_mounts(), mntdf(), optarg, optind, and path.
static int lfs_fid2path (int argc, char ** argv) [static]
Definition at line 3514 of file lfs.c.
References CMD_HELP, llapi_fid2path(), optarg, optind, and path.
static int lfs_find (int argc, char ** argv) [static]
Definition at line 1345 of file lfs.c.
References buf, CMD_HELP, FIND_POOL_OPT, find_param::fp_asign, find_param::fp_atime, find_param::fp_check_gid, find_param::fp_check_layout, find_param::fp_check_pool, find_param::fp_check_size, find_param::fp_check_stripe_count, find_param::fp_check_stripe_size, find_param::fp_check_uid, find_param::fp_csign, find_param::fp_ctime, find_param::fp_exclude_atime, find_param::fp_exclude_ctime, find_param::fp_exclude_gid, find_param::fp_exclude_layout, find_param::fp_exclude_mdt, find_param::fp_exclude_mtime, find_param::fp_exclude_obd, find_param::fp_exclude_pattern, find_param::fp_exclude_pool, find_param::fp_exclude_size, find_param::fp_exclude_stripe_count, find_param::fp_exclude_stripe_size, find_param::fp_exclude_type, find_param::fp_exclude_uid, find_param::fp_gid, find_param::fp_layout, find_param::fp_max_depth, find_param::fp_mdt_uuid, find_param::fp_msign, find_param::fp_mtime, find_param::fp_num_alloc_mdts, find_param::fp_num_alloc_obds, find_param::fp_num_mdts, find_param::fp_num_obds, find_param::fp_obd_uuid, find_param::fp_pattern, find_param::fp_poolname, find_param::fp_size, find_param::fp_size_sign, find_param::fp_size_units, find_param::fp_stripe_count, find_param::fp_stripe_count_sign, find_param::fp_stripe_size, find_param::fp_stripe_size_sign, find_param::fp_stripe_size_units, find_param::fp_type, find_param::fp_uid, find_param::fp_zero_end, GROUP, llapi_find(), llapi_parse_size(), LOV_MAXPOOLNAME, name2id(), name2layout(), optarg, optind, ret, set_time(), USER, and obd_uuid::uuid.
static int lfs_flushctx (int argc, char ** argv) [static]
Definition at line 3309 of file lfs.c.
References CMD_HELP, flushctx_ioctl(), llapi_search_mounts(), and optind.
static enum lu_ladvise_type lfs_get_ladvice (const char * string) [static]
Definition at line 4233 of file lfs.c.
References ARRAY_SIZE, and LU_LADVISE_INVALID.
Referenced by lfs_ladvise().
static int lfs_getdirstripe (int argc, char ** argv) [static]
Definition at line 1938 of file lfs.c.
References find_param::fp_get_lmv, and lfs_getstripe_internal().
static int lfs_getname (int argc, char ** argv) [static]
Definition at line 2448 of file lfs.c.
References buf, CMD_HELP, llapi_getname(), llapi_search_mounts(), optind, and path.
static int lfs_getstripe (int argc, char ** argv) [static]
Definition at line 1931 of file lfs.c.
References lfs_getstripe_internal().
static int lfs_getstripe_internal (int argc, char ** argv, struct find_param * param) [static]
Definition at line 1722 of file lfs.c.
References CMD_HELP, find_param::fp_get_default_lmv, find_param::fp_max_depth, find_param::fp_obd_uuid, find_param::fp_quiet, find_param::fp_raw, find_param::fp_recursive, find_param::fp_verbose, llapi_getstripe(), optarg, optind, VERBOSE_ALL, VERBOSE_COUNT, VERBOSE_DETAIL, VERBOSE_GENERATION, VERBOSE_LAYOUT, VERBOSE_MDTINDEX, VERBOSE_OBJID, VERBOSE_OFFSET, VERBOSE_POOL, and VERBOSE_SIZE.
Referenced by lfs_getdirstripe(), and lfs_getstripe().
static int lfs_hsm_action (int argc, char ** argv) [static]
Definition at line 3855 of file lfs.c.
References CMD_HELP, hsm_current_action::hca_action, hsm_current_action::hca_location, hsm_current_action::hca_state, HPS_RUNNING, hsm_progress_state2name(), hsm_user_action2name(), HUA_ARCHIVE, HUA_NONE, HUA_RESTORE, hsm_extent::length, llapi_hsm_current_action(), LUSTRE_EOF, hsm_extent::offset, and path.
static int lfs_hsm_archive (int argc, char ** argv) [static]
Definition at line 4196 of file lfs.c.
References HUA_ARCHIVE, and lfs_hsm_request().
static int lfs_hsm_cancel (int argc, char ** argv) [static]
Definition at line 4216 of file lfs.c.
References HUA_CANCEL, and lfs_hsm_request().
static int lfs_hsm_change_flags (int argc, char ** argv, int mode) [static]
Generic function to set or clear HSM flags.
Used by hsm_set and hsm_clear.
if LFS_HSM_SET, set the flags, if LFS_HSM_CLEAR, clear the flags.
Definition at line 3781 of file lfs.c.
References __u64, CMD_HELP, HS_ARCHIVED, HS_DIRTY, HS_EXISTS, HS_LOST, HS_NOARCHIVE, HS_NORELEASE, LFS_HSM_SET, llapi_hsm_state_set(), optind, and path.
Referenced by lfs_hsm_clear(), and lfs_hsm_set().
static int lfs_hsm_clear (int argc, char ** argv) [static]
Definition at line 3913 of file lfs.c.
References lfs_hsm_change_flags(), and LFS_HSM_CLEAR.
static int lfs_hsm_prepare_file (const char * file, struct lu_fid * fid, dev_t * last_dev) [static]
Check file state and return its fid, to be used by lfs_hsm_request().
Parameters:
[in] file Path to file to check
[in,out] fid Pointer to allocated lu_fid struct.
[in,out] last_dev Pointer to last device id used.
Returns:
0 on success.
Definition at line 3927 of file lfs.c.
References CMD_HELP, and llapi_path2fid().
Referenced by fill_hur_item().
static int lfs_hsm_release (int argc, char ** argv) [static]
Definition at line 4206 of file lfs.c.
References HUA_RELEASE, and lfs_hsm_request().
static int lfs_hsm_remove (int argc, char ** argv) [static]
Definition at line 4211 of file lfs.c.
References HUA_REMOVE, and lfs_hsm_request().
static int lfs_hsm_request (int argc, char ** argv, int action) [static]
Definition at line 4007 of file lfs.c.
References CMD_HELP, fill_hur_item(), hsm_request::hr_action, hsm_request::hr_archive_id, hsm_request::hr_data_len, hsm_request::hr_flags, hsm_request::hr_itemcount, HUA_ARCHIVE, HUA_REMOVE, hur_data(), hur_len(), hsm_user_request::hur_request, llapi_hsm_request(), llapi_hsm_user_request_alloc(), optarg, optind, and size.
Referenced by lfs_hsm_archive(), lfs_hsm_cancel(), lfs_hsm_release(), lfs_hsm_remove(), and lfs_hsm_restore().
static int lfs_hsm_restore (int argc, char ** argv) [static]
Definition at line 4201 of file lfs.c.
References HUA_RESTORE, and lfs_hsm_request().
static int lfs_hsm_set (int argc, char ** argv) [static]
Definition at line 3908 of file lfs.c.
References lfs_hsm_change_flags(), and LFS_HSM_SET.
static int lfs_hsm_state (int argc, char ** argv) [static]
Definition at line 3724 of file lfs.c.
References CMD_HELP, HS_ARCHIVED, HS_DIRTY, HS_EXISTS, HS_LOST, HS_NOARCHIVE, HS_NORELEASE, HS_RELEASED, hsm_user_state::hus_archive_id, hsm_user_state::hus_states, llapi_hsm_state_get(), and path.
static int lfs_join (int argc, char ** argv) [static]
Definition at line 2531 of file lfs.c.
static int lfs_ladvise (int argc, char ** argv) [static]
Definition at line 4248 of file lfs.c.
References ARRAY_SIZE, CMD_HELP, end, LF_ASYNC, lfs_get_ladvice(), lu_ladvise::lla_advice, lu_ladvise::lla_end, lu_ladvise::lla_padding, lu_ladvise::lla_start, llapi_ladvise(), llapi_parse_size(), LU_LADVISE_INVALID, LUSTRE_EOF, optarg, optind, path, and start.
static int lfs_lgetfacl (int argc, char ** argv) [static]
Definition at line 3363 of file lfs.c.
References llapi_lgetfacl().
static int lfs_ls (int argc, char ** argv) [static]
Definition at line 3386 of file lfs.c.
References llapi_ls().
static int lfs_lsetfacl (int argc, char ** argv) [static]
Definition at line 3357 of file lfs.c.
References llapi_lsetfacl().
static int lfs_mdts (int argc, char ** argv) [static]
Definition at line 2187 of file lfs.c.
References lfs_tgts().
static int lfs_migrate (char * name, __u64 migration_flags, struct llapi_stripe_param * param) [static]
Definition at line 645 of file lfs.c.
References error, file_lease_supported, LL_LEASE_RDLCK, llapi_file_fget_mdtidx(), llapi_file_get_stripe(), llapi_file_open_param(), llapi_lease_get(), llapi_lease_put(), LOV_MAX_STRIPE_COUNT, LOV_USER_MAGIC_V3, lov_user_md, lov_user_md_size(), LUSTRE_VOLATILE_HDR, LUSTRE_VOLATILE_HDR_LEN, migrate_block(), migrate_nonblock(), MIGRATION_NONBLOCK, and progname.
Referenced by lfs_setstripe().
static int lfs_mv (int argc, char ** argv) [static]
Definition at line 2126 of file lfs.c.
References CMD_HELP, end, find_param::fp_max_depth, find_param::fp_mdt_index, find_param::fp_migrate, find_param::fp_verbose, llapi_migrate_mdt(), optarg, optind, and VERBOSE_DETAIL.
static int lfs_osts (int argc, char ** argv) [static]
Definition at line 2182 of file lfs.c.
References lfs_tgts().
static int lfs_path2fid (int argc, char ** argv) [static]
Definition at line 3604 of file lfs.c.
References CMD_HELP, DFID, llapi_path2fid(), llapi_path2parent(), optind, path, and PFID.
static int lfs_poollist (int argc, char ** argv) [static]
Definition at line 1235 of file lfs.c.
References CMD_HELP, and llapi_poollist().
static int lfs_rgetfacl (int argc, char ** argv) [static]
Definition at line 3375 of file lfs.c.
References llapi_rgetfacl().
static int lfs_rmentry (int argc, char ** argv) [static]
Definition at line 2100 of file lfs.c.
References CMD_HELP, and llapi_direntry_remove().
static int lfs_rsetfacl (int argc, char ** argv) [static]
Definition at line 3369 of file lfs.c.
References llapi_rsetfacl().
static int lfs_setdirstripe (int argc, char ** argv) [static]
Definition at line 1947 of file lfs.c.
References CMD_HELP, end, llapi_dir_create_pool(), llapi_dir_set_default_lmv_stripe(), LMV_HASH_NAME_ALL_CHARS, LMV_HASH_NAME_FNV_1A_64, LMV_HASH_TYPE_ALL_CHARS, LMV_HASH_TYPE_FNV_1A_64, mode, optarg, and optind.
static int lfs_setstripe (int argc, char ** argv) [static]
Definition at line 906 of file lfs.c.
References __u64, CMD_HELP, end, fname, find_param::fp_max_depth, find_param::fp_mdt_index, find_param::fp_migrate, find_param::fp_verbose, lfs_migrate(), llapi_file_open_param(), llapi_migrate_mdt(), llapi_parse_size(), LOV_MAX_STRIPE_COUNT, LOV_MAXPOOLNAME, llapi_stripe_param::lsp_is_specific, llapi_stripe_param::lsp_osts, llapi_stripe_param::lsp_pool, llapi_stripe_param::lsp_stripe_count, llapi_stripe_param::lsp_stripe_offset, llapi_stripe_param::lsp_stripe_pattern, llapi_stripe_param::lsp_stripe_size, lustre_is_poolname_valid(), MIGRATION_NONBLOCK, offsetof, optarg, optind, parse_targets(), and VERBOSE_DETAIL.
static int lfs_swap_layouts (int argc, char ** argv) [static]
Definition at line 4221 of file lfs.c.
References CMD_HELP, llapi_swap_layouts(), SWAP_LAYOUTS_KEEP_ATIME, and SWAP_LAYOUTS_KEEP_MTIME.
static int lfs_tgts (int argc, char ** argv) [static]
Definition at line 1893 of file lfs.c.
References CMD_HELP, find_param::fp_get_lmv, llapi_ostlist(), llapi_search_mounts(), and path.
Referenced by lfs_mdts(), and lfs_osts().
int main (int argc, char ** argv)
Definition at line 4403 of file lfs.c.
References liblustreapi_initialized, Parser_commands(), Parser_execarg(), Parser_init(), and progname.
static int migrate_block (int fd, int fdv, const struct stat * st, size_t buf_size, const char * name) [static]
Definition at line 518 of file lfs.c.
References __u64, LL_DV_RD_FLUSH, llapi_fswap_layouts_grouplock(), llapi_get_data_version(), llapi_group_lock(), llapi_group_unlock(), migrate_copy_data(), migrate_copy_timestamps(), progname, and SWAP_LAYOUTS_CHECK_DV1.
Referenced by lfs_migrate().
static int migrate_copy_data (int fd_src, int fd_dst, size_t buf_size, bool group_locked, const char * fname) [static]
Definition at line 443 of file lfs.c.
References buf, check_lease(), and progname.
Referenced by migrate_block(), and migrate_nonblock().
static int migrate_copy_timestamps (int fdv, const struct stat * st) [static]
Definition at line 508 of file lfs.c.
Referenced by migrate_block(), and migrate_nonblock().
static int migrate_nonblock (int fd, int fdv, const struct stat * st, size_t buf_size, const char * name) [static]
Definition at line 589 of file lfs.c.
References __u64, LL_DV_RD_FLUSH, llapi_fswap_layouts(), llapi_get_data_version(), migrate_copy_data(), migrate_copy_timestamps(), progname, and SWAP_LAYOUTS_CLOSE.
Referenced by lfs_migrate().
static int mntdf (char * mntdir, char * fsname, char * pool, int ishow, int cooked, int lazy) [static]
Definition at line 2297 of file lfs.c.
References __u64, CSF, LL_STATFS_LMV, LL_STATFS_LOV, LL_STATFS_NODELAY, llapi_obd_statfs(), llapi_search_ost(), obd_uuid2str(), obd_statfs::os_bavail, obd_statfs::os_bfree, obd_statfs::os_blocks, obd_statfs::os_bsize, obd_statfs::os_ffree, obd_statfs::os_files, poolname, RSF, showdf(), ll_stat_type::st_name, ll_stat_type::st_op, UUF, and obd_uuid::uuid.
Referenced by lfs_df().
static int name2id (unsigned int * id, char * name, int type) [static]
Definition at line 1271 of file lfs.c.
References USER.
Referenced by lfs_find().
static int name2layout (__u32 * layout, char * name) [static]
Definition at line 1325 of file lfs.c.
References LOV_PATTERN_F_RELEASED, and LOV_PATTERN_RAID0.
Referenced by lfs_find().
static int parse_targets (__u32 * osts, int size, int offset, char * arg) [static]
Parse a string containing an OST index list into an array of integers.
The input string contains a comma delimited list of individual indices and ranges, for example "1,2-4,7". Add the indices into the osts array and remove duplicates.
Parameters:
[out] osts array to store indices in
[in] size size of osts array
[in] offset starting index in osts
[in] arg string containing OST index list
Return values:
positive number of indices in osts
-EINVAL unable to parse arg
Definition at line 836 of file lfs.c.
Referenced by lfs_setstripe().
static int set_time (time_t * time, time_t * set, char * str) [static]
Definition at line 1243 of file lfs.c.
Referenced by lfs_find().
static int showdf (char * mntdir, struct obd_statfs * stat, char * uuid, int ishow, int cooked, char * type, int index, int rc) [static]
Definition at line 2208 of file lfs.c.
References __u64, CDF, COOK, CSF, HDF, obd_statfs::os_bavail, obd_statfs::os_bfree, obd_statfs::os_blocks, obd_statfs::os_bsize, obd_statfs::os_ffree, obd_statfs::os_files, RDF, RSF, and UUF.
Referenced by mntdf().
Variable Documentation
command_t cmdlist[]
Definition at line 163 of file lfs.c.
bool file_lease_supported = true [static]
Definition at line 160 of file lfs.c.
Referenced by check_lease(), and lfs_migrate().
const char* const ladvise_names[] = LU_LADVISE_NAMES [static]
Definition at line 4231 of file lfs.c.
const char* progname [static]
Definition at line 159 of file lfs.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.