Lustre: lustre/lfsck/lfsck_namespace.c File Reference
lustre/lfsck/lfsck_namespace.c File Reference
#include <lustre/lustre_idl.h>
#include <lu_object.h>
#include <dt_object.h>
#include <md_object.h>
#include <lustre_fid.h>
#include <lustre_lib.h>
#include <lustre_net.h>
#include <lustre/lustre_user.h>
#include "lfsck_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LFSCK
#define LFSCK_NAMESPACE_MAGIC_V1 0xA0629D03
#define LFSCK_NAMESPACE_MAGIC_V2 0xA0621A0B
#define LFSCK_NAMESPACE_MAGIC LFSCK_NAMESPACE_MAGIC_V2
Enumerations
enum lfsck_nameentry_check { LFSCK_NAMEENTRY_DEAD = 1, LFSCK_NAMEENTRY_REMOVED = 2, LFSCK_NAMEENTRY_RECREATED = 3 }
Functions
static struct lfsck_namespace_req * lfsck_namespace_assistant_req_init (struct lfsck_instance *lfsck, struct lfsck_assistant_object *lso, struct lu_dirent *ent, __u16 type)
static void lfsck_namespace_assistant_req_fini (const struct lu_env *env, struct lfsck_assistant_req *lar)
static void lfsck_namespace_le_to_cpu (struct lfsck_namespace *dst, struct lfsck_namespace *src)
static void lfsck_namespace_cpu_to_le (struct lfsck_namespace *dst, struct lfsck_namespace *src)
static void lfsck_namespace_record_failure (const struct lu_env *env, struct lfsck_instance *lfsck, struct lfsck_namespace *ns)
static int lfsck_namespace_load_bitmap (const struct lu_env *env, struct lfsck_component *com)
Load the MDT bitmap from the lfsck_namespace trace file.
static int lfsck_namespace_load (const struct lu_env *env, struct lfsck_component *com)
Load namespace LFSCK statistics information from the trace file.
static int lfsck_namespace_store (const struct lu_env *env, struct lfsck_component *com)
static struct dt_object * lfsck_namespace_load_one_trace_file (const struct lu_env *env, struct lfsck_component *com, struct dt_object *parent, const char *name, bool reset)
static int lfsck_namespace_load_sub_trace_files (const struct lu_env *env, struct lfsck_component *com, bool reset)
static int lfsck_namespace_init (const struct lu_env *env, struct lfsck_component *com)
int lfsck_namespace_trace_update (const struct lu_env *env, struct lfsck_component *com, const struct lu_fid *fid, const __u8 flags, bool add)
Update the namespace LFSCK trace file for the given .
int lfsck_namespace_check_exist (const struct lu_env *env, struct dt_object *dir, struct dt_object *obj, const char *name)
static int lfsck_declare_namespace_exec_dir (const struct lu_env *env, struct dt_object *obj, struct thandle *handle)
int __lfsck_links_read (const struct lu_env *env, struct dt_object *obj, struct linkea_data *ldata)
static int lfsck_namespace_links_remove (const struct lu_env *env, struct lfsck_component *com, struct dt_object *obj)
Remove linkEA for the given object.
static int lfsck_links_write (const struct lu_env *env, struct dt_object *obj, struct linkea_data *ldata, struct thandle *handle)
static void lfsck_namespace_unpack_linkea_entry (struct linkea_data *ldata, struct lu_name *cname, struct lu_fid *pfid, char *buf)
static int lfsck_namespace_filter_linkea_entry (struct linkea_data *ldata, struct lu_name *cname, struct lu_fid *pfid, bool remove)
static int lfsck_namespace_insert_orphan (const struct lu_env *env, struct lfsck_component *com, struct dt_object *orphan, const char *infix, const char *type, int *count)
Insert orphan into .lustre/lost+found/MDTxxxx/ locally.
static int lfsck_namespace_insert_normal (const struct lu_env *env, struct lfsck_component *com, struct dt_object *parent, struct dt_object *child, const char *name)
Add the specified name entry back to namespace.
static int lfsck_namespace_create_orphan_dir (const struct lu_env *env, struct lfsck_component *com, struct dt_object *orphan, struct lmv_mds_md_v1 *lmv)
Create the specified orphan directory.
static int lfsck_namespace_shrink_linkea (const struct lu_env *env, struct lfsck_component *com, struct dt_object *obj, struct linkea_data *ldata, struct lu_name *cname, struct lu_fid *pfid, bool next)
Remove the specified entry from the linkEA.
static int lfsck_namespace_shrink_linkea_cond (const struct lu_env *env, struct lfsck_component *com, struct dt_object *parent, struct dt_object *child, struct linkea_data *ldata, struct lu_name *cname, struct lu_fid *pfid)
Conditionally remove the specified entry from the linkEA.
static int lfsck_namespace_replace_cond (const struct lu_env *env, struct lfsck_component *com, struct dt_object *parent, struct dt_object *child, const struct lu_fid *cfid, const struct lu_name *cname)
Conditionally replace name entry in the parent.
int lfsck_namespace_rebuild_linkea (const struct lu_env *env, struct lfsck_component *com, struct dt_object *obj, struct linkea_data *ldata)
Overwrite the linkEA for the object with the given ldata.
int lfsck_namespace_repair_dirent (const struct lu_env *env, struct lfsck_component *com, struct dt_object *parent, struct dt_object *child, const char *name, const char *name2, __u16 type, bool update, bool dec)
Repair invalid name entry.
static int lfsck_namespace_repair_unmatched_pairs (const struct lu_env *env, struct lfsck_component *com, struct dt_object *obj, const struct lu_fid *pfid, struct lu_name *cname)
Update the ".." name entry for the given object.
static int lfsck_namespace_dsd_orphan (const struct lu_env *env, struct lfsck_component *com, struct dt_object *obj, const struct lu_fid *pfid, struct lustre_handle *lh, enum lfsck_namespace_inconsistency_type *type)
Handle orphan during Double Scan Directory.
static int lfsck_namespace_dsd_single (const struct lu_env *env, struct lfsck_component *com, struct dt_object *child, const struct lu_fid *pfid, struct linkea_data *ldata, struct lustre_handle *lh, enum lfsck_namespace_inconsistency_type *type, bool *retry)
Double Scan Directory object for single linkEA entry case.
static int lfsck_namespace_dsd_multiple (const struct lu_env *env, struct lfsck_component *com, struct dt_object *child, const struct lu_fid *pfid, struct linkea_data *ldata, struct lustre_handle *lh, enum lfsck_namespace_inconsistency_type *type, bool lpf)
Double Scan Directory object for multiple linkEA entries case.
static int lfsck_namespace_repair_nlink (const struct lu_env *env, struct lfsck_component *com, struct dt_object *obj, struct lu_attr *la)
Repair the object's nlink attribute.
static int lfsck_namespace_double_scan_dir (const struct lu_env *env, struct lfsck_component *com, struct dt_object *child, __u8 flags)
Double scan the directory object for namespace LFSCK.
static int lfsck_namespace_double_scan_one (const struct lu_env *env, struct lfsck_component *com, struct dt_object *child, __u8 flags)
Double scan the MDT-object for namespace LFSCK.
static void lfsck_namespace_dump_statistics (struct seq_file *m, struct lfsck_namespace *ns, __u64 checked_phase1, __u64 checked_phase2, __u32 time_phase1, __u32 time_phase2)
static void lfsck_namespace_release_lmv (const struct lu_env *env, struct lfsck_component *com)
static int lfsck_namespace_check_for_double_scan (const struct lu_env *env, struct lfsck_component *com, struct dt_object *obj)
static int lfsck_namespace_reset (const struct lu_env *env, struct lfsck_component *com, bool init)
static void lfsck_namespace_fail (const struct lu_env *env, struct lfsck_component *com, bool new_checked)
static void lfsck_namespace_close_dir (const struct lu_env *env, struct lfsck_component *com)
static int lfsck_namespace_open_dir (const struct lu_env *env, struct lfsck_component *com)
static int lfsck_namespace_checkpoint (const struct lu_env *env, struct lfsck_component *com, bool init)
static int lfsck_namespace_prep (const struct lu_env *env, struct lfsck_component *com, struct lfsck_start_param *lsp)
static int lfsck_namespace_exec_oit (const struct lu_env *env, struct lfsck_component *com, struct dt_object *obj)
static int lfsck_namespace_exec_dir (const struct lu_env *env, struct lfsck_component *com, struct lfsck_assistant_object *lso, struct lu_dirent *ent, __u16 type)
static int lfsck_namespace_post (const struct lu_env *env, struct lfsck_component *com, int result, bool init)
static void lfsck_namespace_dump (const struct lu_env *env, struct lfsck_component *com, struct seq_file *m)
static int lfsck_namespace_double_scan (const struct lu_env *env, struct lfsck_component *com)
static void lfsck_namespace_data_release (const struct lu_env *env, struct lfsck_component *com)
static void lfsck_namespace_quit (const struct lu_env *env, struct lfsck_component *com)
static int lfsck_namespace_in_notify (const struct lu_env *env, struct lfsck_component *com, struct lfsck_request *lr, struct thandle *th)
static void lfsck_namespace_repaired (struct lfsck_namespace *ns, __u64 *count)
static int lfsck_namespace_query_all (const struct lu_env *env, struct lfsck_component *com, __u32 *mdts_count, __u64 *repaired)
static int lfsck_namespace_query (const struct lu_env *env, struct lfsck_component *com, struct lfsck_request *req, struct lfsck_reply *rep, struct lfsck_query *que, int idx)
int lfsck_namespace_repair_dangling (const struct lu_env *env, struct lfsck_component *com, struct dt_object *parent, struct dt_object *child, struct lfsck_namespace_req *lnr)
Repair dangling name entry.
static int lfsck_namespace_assistant_handler_p1 (const struct lu_env *env, struct lfsck_component *com, struct lfsck_assistant_req *lar)
static int lfsck_namespace_scan_local_lpf_one (const struct lu_env *env, struct lfsck_component *com, struct dt_object *parent, struct lu_dirent *ent)
Handle one orphan under the backend /lost+found directory.
static void lfsck_namespace_scan_local_lpf (const struct lu_env *env, struct lfsck_component *com)
Handle orphans under the backend /lost+found directory.
static int lfsck_namespace_rescan_striped_dir (const struct lu_env *env, struct lfsck_component *com, struct lfsck_lmv_unit *llu)
Rescan the striped directory after the master LMV EA reset.
static int lfsck_namespace_double_scan_one_trace_file (const struct lu_env *env, struct lfsck_component *com, struct dt_object *obj, bool first)
static int lfsck_namespace_assistant_handler_p2 (const struct lu_env *env, struct lfsck_component *com)
static void lfsck_namespace_assistant_fill_pos (const struct lu_env *env, struct lfsck_component *com, struct lfsck_position *pos)
static int lfsck_namespace_double_scan_result (const struct lu_env *env, struct lfsck_component *com, int rc)
static int lfsck_namespace_assistant_sync_failures_interpret (const struct lu_env *env, struct ptlrpc_request *req, void *args, int rc)
static void lfsck_namespace_assistant_sync_failures (const struct lu_env *env, struct lfsck_component *com, struct lfsck_request *lr)
Notify remote LFSCK instances about former failures.
int lfsck_verify_linkea (const struct lu_env *env, struct dt_object *obj, const struct lu_name *cname, const struct lu_fid *pfid)
Verify the specified linkEA entry for the given directory object.
int lfsck_links_get_first (const struct lu_env *env, struct dt_object *obj, char *name, struct lu_fid *pfid)
Get the name and parent directory's FID from the first linkEA entry.
int lfsck_update_name_entry (const struct lu_env *env, struct lfsck_instance *lfsck, struct dt_object *dir, const char *name, const struct lu_fid *fid, __u32 type)
Update the object's name entry with the given FID.
int lfsck_namespace_setup (const struct lu_env *env, struct lfsck_instance *lfsck)
Variables
static struct lfsck_operations lfsck_namespace_ops
struct lfsck_assistant_operations lfsck_namespace_assistant_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_LFSCK
Definition at line 31 of file lfsck_namespace.c.
#define LFSCK_NAMESPACE_MAGIC LFSCK_NAMESPACE_MAGIC_V2
Definition at line 52 of file lfsck_namespace.c.
Referenced by lfsck_namespace_init(), lfsck_namespace_load(), and lfsck_namespace_reset().
#define LFSCK_NAMESPACE_MAGIC_V1 0xA0629D03
Definition at line 44 of file lfsck_namespace.c.
#define LFSCK_NAMESPACE_MAGIC_V2 0xA0621A0B
Definition at line 45 of file lfsck_namespace.c.
Enumeration Type Documentation
enum lfsck_nameentry_check
Enumerator:
LFSCK_NAMEENTRY_DEAD
LFSCK_NAMEENTRY_REMOVED
LFSCK_NAMEENTRY_RECREATED
Definition at line 54 of file lfsck_namespace.c.
Function Documentation
int __lfsck_links_read (const struct lu_env * env, struct dt_object * obj, struct linkea_data * ldata)
Definition at line 671 of file lfsck_namespace.c.
References dt_object_exists(), dt_xattr_get(), lu_buf::lb_buf, linkea_data::ld_buf, linkea_init(), LU_BUF_NULL, lu_buf_realloc(), and XATTR_NAME_LINK.
Referenced by lfsck_links_read(), and lfsck_links_read2().
static int lfsck_declare_namespace_exec_dir (const struct lu_env * env, struct dt_object * obj, struct thandle * handle) [static]
Definition at line 653 of file lfsck_namespace.c.
References DEFAULT_LINKEA_SIZE, dt_declare_xattr_del(), dt_declare_xattr_set(), lfsck_buf_get_const(), and XATTR_NAME_LINK.
Referenced by lfsck_namespace_assistant_handler_p1().
int lfsck_links_get_first (const struct lu_env * env, struct dt_object * obj, char * name, struct lu_fid * pfid)
Get the name and parent directory's FID from the first linkEA entry.
Parameters:
[in] env pointer to the thread context
[in] obj pointer to the object which get linkEA from
[out] name pointer to the buffer to hold the name in the first linkEA entry
[out] pfid pointer to the buffer to hold the parent directory's FID in the first linkEA entry
Return values:
0 for success
negative error number on failure
Definition at line 6404 of file lfsck_namespace.c.
References linkea_data::ld_lee, linkea_data::ld_reclen, lfsck_env_info(), lfsck_links_read(), linkea_entry_unpack(), linkea_first_entry(), lu_name::ln_name, lu_name::ln_namelen, and lfsck_thread_info::lti_name.
Referenced by lfsck_namespace_verify_stripe_slave(), and lfsck_verify_lpf_pairs().
static int lfsck_links_write (const struct lu_env * env, struct dt_object * obj, struct linkea_data * ldata, struct thandle * handle) [static]
Definition at line 769 of file lfsck_namespace.c.
References buf, dt_xattr_set(), lu_buf::lb_buf, linkea_data::ld_buf, linkea_data::ld_leh, link_ea_header::leh_len, lfsck_buf_get_const(), and XATTR_NAME_LINK.
Referenced by lfsck_namespace_assistant_handler_p1().
static void lfsck_namespace_assistant_fill_pos (const struct lu_env * env, struct lfsck_component * com, struct lfsck_position * pos) [static]
Definition at line 6153 of file lfsck_namespace.c.
References lfsck_assistant_data::lad_req_list, lfsck_assistant_req::lar_list, lfsck_assistant_req::lar_parent, lfsck_component::lc_data, list_empty(), list_entry, lfsck_namespace_req::lnr_dir_cookie, lfsck_namespace_req::lnr_lar, lfsck_position::lp_dir_cookie, lfsck_position::lp_dir_parent, lfsck_position::lp_oit_cookie, lfsck_assistant_object::lso_fid, lfsck_assistant_object::lso_oit_cookie, and list_head::next.
static int lfsck_namespace_assistant_handler_p1 (const struct lu_env * env, struct lfsck_component * com, struct lfsck_assistant_req * lar) [static]
Definition at line 5012 of file lfsck_namespace.c.
References CDEBUG, D_LFSCK, DFID, dir, dotdot, dt_attr_get(), dt_object_exists(), dt_object_remote(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_locked(), dt_write_unlock(), dt_xattr_del(), ENTRY, fid_is_sane(), fid_is_zero(), fid_seq_is_dot(), GOTO, lu_attr::la_nlink, lfsck_assistant_data::lad_advance_lock, lfsck_assistant_req::lar_parent, LASSERT, lfsck_bookmark::lb_param, LBUG, lfsck_component::lc_data, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_sem, LCK_EX, linkea_data::ld_leh, link_ea_header::leh_reccount, LF_INCOMPLETE, LF_INCONSISTENT, LF_UPGRADE, lfsck_assistant_object_load(), lfsck_declare_namespace_exec_dir(), lfsck_dev_idx(), lfsck_env_info(), lfsck_find_mdt_idx_by_fid(), lfsck_ibits_lock(), lfsck_ibits_unlock(), lfsck_is_valid_slave_name_entry(), lfsck_lad_set_bitmap(), lfsck_lfsck2name(), lfsck_links_read(), lfsck_links_write(), lfsck_ltd2tgt(), lfsck_name_get_const(), lfsck_namespace_check_exist(), lfsck_namespace_handle_striped_master(), lfsck_namespace_record_failure(), lfsck_namespace_repair_bad_name_hash(), lfsck_namespace_repair_dangling(), lfsck_namespace_repair_dirent(), lfsck_namespace_striped_dir_rescan(), lfsck_namespace_trace_update(), lfsck_object_find_by_dev(), lfsck_object_put(), lfsck_object_type(), lfsck_pos_fill(), lfsck_pos_is_zero(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_bottom, lfsck_instance::li_mdt_descs, linkea_add_buf(), linkea_data_new(), linkea_links_find(), lfsck_lmv::ll_lmv_master, lfsck_namespace::ln_bad_type_repaired, lfsck_namespace::ln_dangling_repaired, lfsck_namespace::ln_dirent_repaired, lfsck_namespace::ln_flags, lfsck_namespace::ln_items_repaired, lfsck_namespace::ln_linkea_repaired, lfsck_namespace::ln_mul_linked_checked, lfsck_namespace::ln_name_hash_repaired, lfsck_namespace::ln_pos_first_inconsistent, LNIT_BAD_DIRENT, LNIT_BAD_TYPE, LNIT_DANGLING, LNIT_NONE, lfsck_namespace_req::lnr_attr, lfsck_namespace_req::lnr_dir_cookie, lfsck_namespace_req::lnr_fid, lfsck_namespace_req::lnr_lar, lfsck_namespace_req::lnr_lmv, lfsck_namespace_req::lnr_name, lfsck_namespace_req::lnr_namelen, lfsck_namespace_req::lnr_type, LNTF_CHECK_PARENT, LNTF_SKIP_NLINK, LPF_DRYRUN, LPF_FAILOUT, lfsck_assistant_object::lso_dead, lfsck_assistant_object::lso_fid, lfsck_tgt_desc::ltd_tgt, lfsck_thread_info::lti_la, LUDA_REPAIR, LUDA_UPGRADE, lustre_handle_is_used(), MDS_DIR_END_OFF, MDS_INODELOCK_UPDATE, MDS_INODELOCK_XATTR, name_is_dot_or_dotdot(), PFID, RETURN, stop, unlikely, and XATTR_NAME_LINK.
Referenced by lfsck_namespace_rescan_striped_dir().
static int lfsck_namespace_assistant_handler_p2 (const struct lu_env * env, struct lfsck_component * com) [static]
Definition at line 6106 of file lfsck_namespace.c.
References CDEBUG, cfs_time_current(), cfs_time_seconds(), D_LFSCK, ENTRY, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_new_checked, lfsck_component::lc_new_scanned, lfsck_component::lc_sub_trace_objs, lfsck_component::lc_time_last_checkpoint, lfsck_component::lc_time_next_checkpoint, LFSCK_CHECKPOINT_INTERVAL, lfsck_lfsck2name(), lfsck_namespace_double_scan_one_trace_file(), lfsck_namespace_rescan_striped_dir(), lfsck_namespace_scan_local_lpf(), LFSCK_STF_COUNT, lfsck_sub_trace_file_fid2idx(), lfsck_instance::li_list_lmv, lfsck_instance::li_lock, list_del_init(), list_empty(), list_entry, lfsck_lmv_unit::llu_link, lfsck_namespace::ln_fid_latest_scanned_phase2, lfsck_sub_trace_obj::lsto_obj, list_head::next, and RETURN.
static void lfsck_namespace_assistant_req_fini (const struct lu_env * env, struct lfsck_assistant_req * lar) [static]
Definition at line 87 of file lfsck_namespace.c.
References lfsck_assistant_req::lar_parent, lfsck_assistant_object_put(), lfsck_lmv_put(), lfsck_namespace_req::lnr_lar, lfsck_namespace_req::lnr_lmv, lfsck_namespace_req::lnr_size, and OBD_FREE.
Referenced by lfsck_namespace_close_dir(), lfsck_namespace_exec_dir(), and lfsck_namespace_rescan_striped_dir().
static struct lfsck_namespace_req* lfsck_namespace_assistant_req_init (struct lfsck_instance * lfsck, struct lfsck_assistant_object * lso, struct lu_dirent * ent, __u16 type) [static, read]
Definition at line 61 of file lfsck_namespace.c.
References INIT_LIST_HEAD, lfsck_assistant_req::lar_list, lfsck_assistant_req::lar_parent, lu_dirent::lde_attrs, lu_dirent::lde_fid, lu_dirent::lde_hash, lu_dirent::lde_name, lu_dirent::lde_namelen, lfsck_assistant_object_get(), lfsck_lmv_get(), lfsck_instance::li_lmv, lfsck_namespace_req::lnr_attr, lfsck_namespace_req::lnr_dir_cookie, lfsck_namespace_req::lnr_fid, lfsck_namespace_req::lnr_lar, lfsck_namespace_req::lnr_lmv, lfsck_namespace_req::lnr_name, lfsck_namespace_req::lnr_namelen, lfsck_namespace_req::lnr_size, lfsck_namespace_req::lnr_type, OBD_ALLOC, and size.
Referenced by lfsck_namespace_exec_dir(), and lfsck_namespace_rescan_striped_dir().
static void lfsck_namespace_assistant_sync_failures (const struct lu_env * env, struct lfsck_component * com, struct lfsck_request * lr) [static]
Notify remote LFSCK instances about former failures.
The local LFSCK instance has recorded which MDTs have ever failed to respond some LFSCK verification requests (maybe because of network issues or the MDT itself trouble). During the respond gap the MDT may missed some name entries verification, then the MDT cannot know whether related MDT-objects have been referenced by related name entries or not, then in the second-stage scanning, these MDT-objects will be regarded as orphan, if the MDT-object contains bad linkEA for back reference, then it will misguide the LFSCK to generate wrong name entry for repairing the orphan.
To avoid above trouble, when layout LFSCK finishes the first-stage scanning, it will scan the bitmap for the ever failed MDTs, and notify them that they have ever missed some name entries verification and should skip the handling for orphan MDT-objects.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] lr pointer to the lfsck request
Definition at line 6245 of file lfsck_namespace.c.
References CDEBUG, cfs_foreach_bit, D_LFSCK, ENTRY, EXIT, GOTO, lfsck_assistant_data::lad_bitmap, lfsck_assistant_data::lad_incomplete, lfsck_assistant_data::lad_touch_gen, lfsck_async_interpret_args::laia_ltd, LASSERT, lfsck_component::lc_data, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, LF_INCOMPLETE, lfsck_async_request(), lfsck_env_info(), lfsck_lfsck2name(), lfsck_ltd2tgt(), lfsck_namespace_assistant_sync_failures_interpret(), LFSCK_NOTIFY, lfsck_instance::li_mdt_descs, lfsck_namespace::ln_flags, lfsck_request::lr_flags2, lfsck_tgt_desc::ltd_exp, lfsck_tgt_desc::ltd_index, lfsck_tgt_descs::ltd_rw_sem, lfsck_thread_info::lti_laia2, ptlrpc_prep_set(), ptlrpc_set_destroy(), ptlrpc_set_wait(), and RETURN_EXIT.
static int lfsck_namespace_assistant_sync_failures_interpret (const struct lu_env * env, struct ptlrpc_request * req, void * args, int rc) [static]
Definition at line 6210 of file lfsck_namespace.c.
References lfsck_async_interpret_args::laia_ltd, and lfsck_tgt_desc::ltd_synced_failures.
Referenced by lfsck_namespace_assistant_sync_failures().
int lfsck_namespace_check_exist (const struct lu_env * env, struct dt_object * dir, struct dt_object * obj, const char * name)
Definition at line 628 of file lfsck_namespace.c.
References dt_key, dt_lookup(), ENTRY, lfsck_dto2fid(), lfsck_env_info(), lfsck_is_dead_obj(), LFSCK_NAMEENTRY_DEAD, LFSCK_NAMEENTRY_RECREATED, LFSCK_NAMEENTRY_REMOVED, lfsck_thread_info::lti_fid, lu_fid_eq(), RETURN, and unlikely.
Referenced by lfsck_namespace_assistant_handler_p1(), lfsck_namespace_handle_striped_master(), and lfsck_namespace_repair_dangling().
static int lfsck_namespace_check_for_double_scan (const struct lu_env * env, struct lfsck_component * com, struct dt_object * obj) [static]
Definition at line 3670 of file lfsck_namespace.c.
References dt_attr_get(), lu_attr::la_ctime, lu_attr::la_nlink, lfsck_dto2fid(), lfsck_env_info(), lfsck_namespace_trace_update(), lfsck_object_type(), LNTF_CHECK_LINKEA, lfsck_thread_info::lti_la, and unlikely.
Referenced by lfsck_namespace_exec_oit().
static int lfsck_namespace_checkpoint (const struct lu_env * env, struct lfsck_component * com, bool init) [static]
Definition at line 3866 of file lfsck_namespace.c.
References CDEBUG, cfs_duration_sec(), cfs_time_current(), cfs_time_current_sec(), D_LFSCK, DFID, HALF_SEC, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_new_checked, lfsck_component::lc_sem, lfsck_checkpoint_generic(), lfsck_lfsck2name(), lfsck_namespace_store(), lfsck_instance::li_pos_checkpoint, lfsck_instance::li_pos_current, lfsck_instance::li_time_last_checkpoint, lfsck_namespace::ln_items_checked, lfsck_namespace::ln_pos_last_checkpoint, lfsck_namespace::ln_pos_latest_start, lfsck_namespace::ln_run_time_phase1, lfsck_namespace::ln_status, lfsck_namespace::ln_time_last_checkpoint, lfsck_position::lp_dir_cookie, lfsck_position::lp_dir_parent, lfsck_position::lp_oit_cookie, LPU64, LPX64, and PFID.
static void lfsck_namespace_close_dir (const struct lu_env * env, struct lfsck_component * com) [static]
Definition at line 3774 of file lfsck_namespace.c.
References ENTRY, EXIT, INIT_LIST_HEAD, lfsck_assistant_data::lad_assistant_status, lfsck_assistant_data::lad_lock, lfsck_assistant_data::lad_prefetched, lfsck_assistant_data::lad_req_list, lfsck_assistant_data::lad_thread, lfsck_assistant_req::lar_list, lfsck_assistant_req::lar_parent, lfsck_component::lc_data, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_assistant_object_init(), lfsck_dto2fid(), lfsck_lmv_get(), lfsck_namespace_assistant_req_fini(), LFSCK_TMPBUF_LEN, lfsck_instance::li_lmv, lfsck_instance::li_obj_dir, lfsck_instance::li_pos_current, list_add_tail(), lfsck_namespace::ln_striped_dirs_skipped, lfsck_namespace_req::lnr_dir_cookie, lfsck_namespace_req::lnr_fid, lfsck_namespace_req::lnr_lar, lfsck_namespace_req::lnr_lmv, lfsck_namespace_req::lnr_size, lfsck_position::lp_oit_cookie, MDS_DIR_END_OFF, OBD_ALLOC, OBD_FREE, RETURN_EXIT, size, and ptlrpc_thread::t_ctl_waitq.
static void lfsck_namespace_cpu_to_le (struct lfsck_namespace * dst, struct lfsck_namespace * src) [static]
Definition at line 169 of file lfsck_namespace.c.
References cpu_to_le32, cpu_to_le64, fid_cpu_to_le(), lfsck_position_cpu_to_le(), lfsck_namespace::ln_bad_type_repaired, lfsck_namespace::ln_bitmap_size, lfsck_namespace::ln_dangling_repaired, lfsck_namespace::ln_dirent_repaired, lfsck_namespace::ln_dirs_checked, lfsck_namespace::ln_fid_latest_scanned_phase2, lfsck_namespace::ln_flags, lfsck_namespace::ln_items_checked, lfsck_namespace::ln_items_failed, lfsck_namespace::ln_items_repaired, lfsck_namespace::ln_linkea_repaired, lfsck_namespace::ln_local_lpf_failed, lfsck_namespace::ln_local_lpf_moved, lfsck_namespace::ln_local_lpf_scanned, lfsck_namespace::ln_local_lpf_skipped, lfsck_namespace::ln_lost_dirent_repaired, lfsck_namespace::ln_magic, lfsck_namespace::ln_mul_linked_checked, lfsck_namespace::ln_mul_linked_repaired, lfsck_namespace::ln_mul_ref_repaired, lfsck_namespace::ln_name_hash_repaired, lfsck_namespace::ln_objs_checked_phase2, lfsck_namespace::ln_objs_failed_phase2, lfsck_namespace::ln_objs_nlink_repaired, lfsck_namespace::ln_objs_repaired_phase2, lfsck_namespace::ln_pos_first_inconsistent, lfsck_namespace::ln_pos_last_checkpoint, lfsck_namespace::ln_pos_latest_start, lfsck_namespace::ln_run_time_phase1, lfsck_namespace::ln_run_time_phase2, lfsck_namespace::ln_status, lfsck_namespace::ln_striped_dirs_disabled, lfsck_namespace::ln_striped_dirs_failed, lfsck_namespace::ln_striped_dirs_repaired, lfsck_namespace::ln_striped_dirs_scanned, lfsck_namespace::ln_striped_dirs_skipped, lfsck_namespace::ln_striped_shards_failed, lfsck_namespace::ln_striped_shards_repaired, lfsck_namespace::ln_striped_shards_scanned, lfsck_namespace::ln_striped_shards_skipped, lfsck_namespace::ln_success_count, lfsck_namespace::ln_time_last_checkpoint, lfsck_namespace::ln_time_last_complete, lfsck_namespace::ln_time_latest_start, lfsck_namespace::ln_unknown_inconsistency, and lfsck_namespace::ln_unmatched_pairs_repaired.
Referenced by lfsck_namespace_store().
static int lfsck_namespace_create_orphan_dir (const struct lu_env * env, struct lfsck_component * com, struct dt_object * orphan, struct lmv_mds_md_v1 * lmv) [static]
Create the specified orphan directory.
For the case that the parent MDT-object stored in some MDT-object's linkEA entry is lost, the LFSCK will re-create the parent object as an orphan and insert it into .lustre/lost+found/MDTxxxx/ directory with the name ${FID}-P-${conflict_version}.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] orphan pointer to the orphan MDT-object to be created
[in] lmv pointer to master LMV EA that will be set to the orphan
Return values:
positive number for repaired cases
negative error number on failure
Definition at line 1226 of file lfsck_namespace.c.
References CDEBUG, D_LFSCK, DFID, dt_object_operations::do_ah_init, dt_object::do_ops, dt_object_format::dof_type, dot, dotdot, dt_create(), dt_declare_create(), dt_declare_insert(), dt_declare_ref_add(), dt_declare_xattr_set(), dt_insert(), dt_key, dt_lookup(), dt_mode_to_dft(), dt_object_exists(), dt_object_remote(), dt_ref_add(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_try_as_dir(), dt_write_lock(), dt_write_unlock(), dt_xattr_set(), ENTRY, GOTO, LA_ATIME, LA_CTIME, LA_GID, LA_MODE, lu_attr::la_mode, LA_MTIME, LA_TYPE, LA_UID, lu_attr::la_valid, LASSERT, lu_buf::lb_buf, lfsck_bookmark::lb_param, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, LCK_PW, linkea_data::ld_buf, linkea_data::ld_leh, link_ea_header::leh_len, LF_INCONSISTENT, lfsck_buf_init(), lfsck_dev_idx(), lfsck_dto2fid(), lfsck_env_info(), lfsck_find_dev_by_fid(), lfsck_find_mdt_idx_by_fid(), lfsck_lfsck2name(), lfsck_lmv_header_cpu_to_le(), lfsck_lock(), lfsck_obj2dev(), lfsck_object_find_bottom(), lfsck_object_put(), lfsck_unlock(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_lpf_obj, lfsck_instance::li_lpf_root_obj, linkea_add_buf(), linkea_data_new(), LMV_MAGIC, lmv_mds_md_v1::lmv_magic, lmv_mds_md_v1::lmv_master_mdt_index, lfsck_namespace::ln_flags, lu_name::ln_name, lu_name::ln_namelen, LPF_DRYRUN, lfsck_thread_info::lti_dof, lfsck_thread_info::lti_dt_rec, lfsck_thread_info::lti_hint, lfsck_thread_info::lti_la, lfsck_thread_info::lti_linkea_buf2, lfsck_thread_info::lti_llh, lfsck_thread_info::lti_lmv2, lfsck_thread_info::lti_name2, MDS_INODELOCK_UPDATE, name, PFID, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, stop, thandle::th_sync, unlikely, XATTR_NAME_LINK, and XATTR_NAME_LMV.
Referenced by lfsck_namespace_double_scan_one(), and lfsck_namespace_dsd_single().
static void lfsck_namespace_data_release (const struct lu_env * env, struct lfsck_component * com) [static]
Definition at line 4406 of file lfsck_namespace.c.
References CFS_FREE_BITMAP, lfsck_assistant_data::lad_bitmap, lfsck_assistant_data::lad_mdt_list, lfsck_assistant_data::lad_mdt_phase1_list, lfsck_assistant_data::lad_mdt_phase2_list, lfsck_assistant_data::lad_req_list, lfsck_assistant_data::lad_thread, LASSERT, lfsck_component::lc_data, lfsck_component::lc_lfsck, lfsck_namespace_release_lmv(), lfsck_instance::li_mdt_descs, likely, list_del_init(), list_empty(), list_for_each_entry_safe, lfsck_tgt_descs::ltd_lock, lfsck_tgt_desc::ltd_namespace_list, lfsck_tgt_desc::ltd_namespace_phase_list, OBD_FREE_PTR, thread_is_init(), and thread_is_stopped().
static int lfsck_namespace_double_scan (const struct lu_env * env, struct lfsck_component * com) [static]
Definition at line 4380 of file lfsck_namespace.c.
References lfsck_assistant_data::lad_mdt_phase1_list, lfsck_assistant_data::lad_mdt_phase2_list, lfsck_assistant_data::lad_req_list, lfsck_assistant_data::lad_thread, LASSERT, lfsck_component::lc_data, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_double_scan_generic(), lfsck_instance::li_mdt_descs, list_del_init(), list_empty(), list_for_each_entry_safe, lfsck_namespace::ln_status, lfsck_tgt_descs::ltd_lock, lfsck_tgt_desc::ltd_namespace_phase_list, and thread_is_stopped().
static int lfsck_namespace_double_scan_dir (const struct lu_env * env, struct lfsck_component * com, struct dt_object * child, __u8 flags) [static]
Double scan the directory object for namespace LFSCK.
This function will verify the <parent, child> pairs in the namespace tree: the parent references the child via some name entry that should be in the child's linkEA entry, the child should back references the parent via its ".." name entry.
The LFSCK will scan every linkEA entry in turn until find out the first matched pairs. If found, then all other linkEA entries will be dropped. If all the linkEA entries cannot match the ".." name entry, then there are serveral possible cases:
1) If there is only one linkEA entry, then trust it as long as the PFID in the linkEA entry is valid.
2) If there are multiple linkEA entries, then try to find the linkEA that matches the ".." name entry. If found, then all other entries are invalid; otherwise, it is quite possible that the ".." name entry is corrupted. Under such case, the LFSCK will rebuild the ".." name entry according to the first valid linkEA entry (both the parent and the name entry should exist).
3) If the directory object has no (valid) linkEA entry, then the directory object will be handled as pure orphan and inserted in the .lustre/lost+found/MDTxxxx/ with the name: ${self_FID}-${PFID}-D-${conflict_version}
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] child pointer to the directory object to be handled
[in] flags to indicate the specical checking on the
Return values:
positive number for repaired cases
0 if nothing to be repaired
negative error number on failure
Definition at line 2990 of file lfsck_namespace.c.
References CDEBUG, D_LFSCK, DFID, dotdot, dt_key, dt_lookup(), dt_object_remote(), dt_read_lock(), dt_read_unlock(), dt_try_as_dir(), ENTRY, fid_is_sane(), fid_is_zero(), fid_zero(), GOTO, LASSERT, lfsck_bookmark::lb_param, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, LCK_EX, linkea_data::ld_leh, link_ea_header::leh_reccount, LF_INCOMPLETE, lfsck_dto2fid(), lfsck_env_info(), lfsck_ibits_lock(), lfsck_ibits_unlock(), lfsck_is_dead_obj(), lfsck_lfsck2name(), lfsck_links_read(), lfsck_namespace_dsd_multiple(), lfsck_namespace_dsd_orphan(), lfsck_namespace_dsd_single(), lfsck_namespace_insert_orphan(), lfsck_namespace_links_remove(), lfsck_namespace_scan_shard(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_lpf_obj, linkea_first_entry(), lfsck_namespace::ln_flags, lfsck_namespace::ln_linkea_repaired, lfsck_namespace::ln_mul_ref_repaired, lfsck_namespace::ln_striped_shards_scanned, lfsck_namespace::ln_striped_shards_skipped, lfsck_namespace::ln_unknown_inconsistency, lfsck_namespace::ln_unmatched_pairs_repaired, LNIT_BAD_LINKEA, LNIT_MUL_REF, LNIT_UNMATCHED_PAIRS, LNTF_CHECK_LINKEA, LNTF_CHECK_PARENT, LNTF_RECHECK_NAME_HASH, LNTF_UNCERTAIN_LMV, LPF_ALL_TGT, lfsck_thread_info::lti_fid2, lfsck_thread_info::lti_tmpbuf, lu_fid_eq(), lustre_handle_is_used(), MDS_INODELOCK_UPDATE, MDS_INODELOCK_XATTR, PFID, RETURN, and unlikely.
Referenced by lfsck_namespace_double_scan_one().
static int lfsck_namespace_double_scan_one (const struct lu_env * env, struct lfsck_component * com, struct dt_object * child, __u8 flags) [static]
Double scan the MDT-object for namespace LFSCK.
If the MDT-object contains invalid or repeated linkEA entries, then drop those entries from the linkEA; if the linkEA becomes empty or the object has no linkEA, then it is an orphan and will be added into the directory .lustre/lost+found/MDTxxxx/; if the remote parent is lost, then recreate the remote parent; if the name entry corresponding to some linkEA entry is lost, then add the name entry back to the namespace.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] child pointer to the dt_object to be handled
[in] flags some hints to indicate how the should be handled
Return values:
positive number for repaired cases
0 if nothing to be repaired
negative error number on failure
Definition at line 3220 of file lfsck_namespace.c.
References dt_attr_get(), dt_key, dt_lookup(), dt_object_exists(), dt_read_lock(), dt_read_unlock(), dt_try_as_dir(), ENTRY, fid_is_sane(), GOTO, lu_attr::la_nlink, LASSERT, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, linkea_data::ld_lee, linkea_data::ld_leh, link_ea_header::leh_reccount, LF_INCOMPLETE, lfsck_dto2fid(), lfsck_env_info(), lfsck_is_dead_obj(), lfsck_links_read(), lfsck_namespace_check_name(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_double_scan_dir(), lfsck_namespace_filter_linkea_entry(), lfsck_namespace_insert_normal(), lfsck_namespace_insert_orphan(), lfsck_namespace_repair_nlink(), lfsck_namespace_replace_cond(), lfsck_namespace_shrink_linkea(), lfsck_namespace_shrink_linkea_cond(), lfsck_namespace_unpack_linkea_entry(), lfsck_object_find_bottom(), lfsck_object_put(), lfsck_object_type(), linkea_first_entry(), linkea_next_entry(), lfsck_namespace::ln_flags, lfsck_namespace::ln_mul_linked_repaired, lfsck_namespace::ln_mul_ref_repaired, lu_name::ln_name, lfsck_namespace::ln_objs_nlink_repaired, lfsck_thread_info::lti_fid, lfsck_thread_info::lti_fid2, lfsck_thread_info::lti_key, lfsck_thread_info::lti_la, lfsck_thread_info::lti_name, lu_fid_eq(), RETURN, and unlikely.
Referenced by lfsck_namespace_double_scan_one_trace_file().
static int lfsck_namespace_double_scan_one_trace_file (const struct lu_env * env, struct lfsck_component * com, struct dt_object * obj, bool first) [static]
Definition at line 5977 of file lfsck_namespace.c.
References cfs_duration_sec(), CFS_FAIL_TIMEOUT, cfs_fail_val, cfs_time_beforeq(), cfs_time_current(), cfs_time_current_sec(), cfs_time_seconds(), dt_index_operations::dio_it, dt_object::do_index_ops, dt_key, dt_object_exists(), ENTRY, fid_be_to_cpu(), fid_cpu_to_be(), fid_is_sane(), fid_zero(), GOTO, HALF_SEC, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_new_checked, lfsck_component::lc_new_scanned, lfsck_component::lc_sem, lfsck_component::lc_time_last_checkpoint, lfsck_component::lc_time_next_checkpoint, LFSCK_CHECKPOINT_INTERVAL, lfsck_control_speed_by_self(), lfsck_namespace_double_scan_one(), lfsck_namespace_store(), lfsck_object_find_bottom(), lfsck_object_put(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_thread, lfsck_namespace::ln_fid_latest_scanned_phase2, lfsck_namespace::ln_objs_checked_phase2, lfsck_namespace::ln_objs_failed_phase2, lfsck_namespace::ln_objs_repaired_phase2, lfsck_namespace::ln_run_time_phase2, lfsck_namespace::ln_time_last_checkpoint, LPF_FAILOUT, OBD_FAIL_LFSCK_DELAY3, RETURN, thread, thread_is_running(), and unlikely.
Referenced by lfsck_namespace_assistant_handler_p2().
static int lfsck_namespace_double_scan_result (const struct lu_env * env, struct lfsck_component * com, int rc) [static]
Definition at line 6171 of file lfsck_namespace.c.
References cfs_duration_sec(), cfs_time_current(), cfs_time_current_sec(), HALF_SEC, lfsck_bookmark::lb_param, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_new_checked, lfsck_component::lc_sem, lfsck_component::lc_time_last_checkpoint, LF_INCOMPLETE, LF_INCONSISTENT, LF_SCANNED_ONCE, lfsck_namespace_store(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_status, lfsck_namespace::ln_flags, lfsck_namespace::ln_objs_checked_phase2, lfsck_namespace::ln_run_time_phase2, lfsck_namespace::ln_status, lfsck_namespace::ln_success_count, lfsck_namespace::ln_time_last_checkpoint, lfsck_namespace::ln_time_last_complete, LPF_DRYRUN, LS_COMPLETED, LS_FAILED, LS_PARTIAL, and LS_STOPPED.
static int lfsck_namespace_dsd_multiple (const struct lu_env * env, struct lfsck_component * com, struct dt_object * child, const struct lu_fid * pfid, struct linkea_data * ldata, struct lustre_handle * lh, enum lfsck_namespace_inconsistency_type * type, bool lpf) [static]
Double Scan Directory object for multiple linkEA entries case.
The given has multiple linkEA entries. There is at most one linkEA entry will be valid, all the others will be removed. Firstly, the function will try to find out the linkEA entry for which the name entry exists under the given parent (). If there is no linkEA entry that matches the given ".." name entry, then tries to find out the first linkEA entry that both the parent and the name entry exist to rebuild a new ".." name entry.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] child pointer to the directory to be double scanned
[in] pfid the FID corresponding to the ".." entry
[in] ldata pointer to the linkEA data for the given
[in,out] lh ldlm lock handler for the given
[out] type to tell the caller what the inconsistency is
[in] lpf true if the ".." entry is under lost+found/MDTxxxx/
Return values:
positive number for repaired cases
0 if nothing to be repaired
negative error number on failure
Definition at line 2604 of file lfsck_namespace.c.
References dt_key, dt_lookup(), dt_object_exists(), dt_try_as_dir(), ENTRY, fid_is_sane(), fid_is_zero(), lfsck_bookmark::lb_param, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, LCK_EX, linkea_data::ld_lee, linkea_data::ld_leh, link_ea_header::leh_reccount, lfsck_dto2fid(), lfsck_env_info(), lfsck_ibits_unlock(), lfsck_namespace_dsd_orphan(), lfsck_namespace_dsd_single(), lfsck_namespace_filter_linkea_entry(), lfsck_namespace_rebuild_linkea(), lfsck_namespace_repair_dirent(), lfsck_namespace_repair_unmatched_pairs(), lfsck_namespace_replace_cond(), lfsck_namespace_unpack_linkea_entry(), lfsck_object_find_bottom(), lfsck_object_put(), lfsck_instance::li_bookmark_ram, linkea_add_buf(), linkea_data_new(), linkea_del_buf(), linkea_first_entry(), linkea_next_entry(), lfsck_namespace::ln_dirent_repaired, lu_name::ln_name, LNIT_UNMATCHED_PAIRS, LPF_FAILOUT, lfsck_thread_info::lti_big_buf, lfsck_thread_info::lti_fid3, lfsck_thread_info::lti_key, lfsck_thread_info::lti_name, lu_fid_eq(), RETURN, and unlikely.
Referenced by lfsck_namespace_double_scan_dir().
static int lfsck_namespace_dsd_orphan (const struct lu_env * env, struct lfsck_component * com, struct dt_object * obj, const struct lu_fid * pfid, struct lustre_handle * lh, enum lfsck_namespace_inconsistency_type * type) [static]
Handle orphan during Double Scan Directory.
Remove the 's current (invalid) linkEA entries, and insert it in the directory .lustre/lost+found/MDTxxxx/ with the name: ${FID}-${PFID}-D-${conflict_version}
The caller should take the ldlm lock before the calling.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] obj pointer to the orphan object to be handled
[in] pfid the new fid for the object's ".." name entry
[in,out] lh ldlm lock handler for the given
[out] type to tell the caller what the inconsistency is
Return values:
positive number for repaired cases
0 if nothing to be repaired
negative error number on failure
Definition at line 2263 of file lfsck_namespace.c.
References DFID, ENTRY, lfsck_component::lc_file_ram, LCK_EX, LF_INCOMPLETE, lfsck_env_info(), lfsck_ibits_unlock(), lfsck_namespace_insert_orphan(), lfsck_namespace_links_remove(), lfsck_namespace::ln_flags, LNIT_MUL_REF, lfsck_thread_info::lti_tmpbuf, PFID, and RETURN.
Referenced by lfsck_namespace_double_scan_dir(), lfsck_namespace_dsd_multiple(), and lfsck_namespace_dsd_single().
static int lfsck_namespace_dsd_single (const struct lu_env * env, struct lfsck_component * com, struct dt_object * child, const struct lu_fid * pfid, struct linkea_data * ldata, struct lustre_handle * lh, enum lfsck_namespace_inconsistency_type * type, bool * retry) [static]
Double Scan Directory object for single linkEA entry case.
The given has unique linkEA entry. If the linkEA entry is valid, then check whether the name is in the namespace or not, if not, add the missing name entry back to namespace. If the linkEA entry is invalid, then remove it and insert the in the .lustre/lost+found/MDTxxxx/ as an orphan.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] child pointer to the directory to be double scanned
[in] pfid the FID corresponding to the ".." entry
[in] ldata pointer to the linkEA data for the given
[in,out] lh ldlm lock handler for the given
[out] type to tell the caller what the inconsistency is
[in] retry if found inconsistency, but the caller does not hold ldlm lock on the , then set as true
Return values:
positive number for repaired cases
0 if nothing to be repaired
negative error number on failure
Definition at line 2328 of file lfsck_namespace.c.
References DFID, dt_key, dt_lookup(), dt_object_exists(), dt_try_as_dir(), ENTRY, fid_is_sane(), fid_is_zero(), GOTO, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, LCK_EX, LF_INCOMPLETE, lfsck_dto2fid(), lfsck_env_info(), lfsck_ibits_unlock(), lfsck_namespace_check_name(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_dsd_orphan(), lfsck_namespace_insert_normal(), lfsck_namespace_insert_orphan(), lfsck_namespace_repair_unmatched_pairs(), lfsck_namespace_replace_cond(), lfsck_namespace_shrink_linkea(), lfsck_namespace_shrink_linkea_cond(), lfsck_namespace_unpack_linkea_entry(), lfsck_object_find_bottom(), lfsck_object_put(), lfsck_read_stripe_lmv(), lfsck_shard_name_to_index(), lmv_mds_md_v1::lmv_magic, LMV_MAGIC_STRIPE, lfsck_namespace::ln_flags, lu_name::ln_name, lu_name::ln_namelen, LNIT_UNMATCHED_PAIRS, lfsck_thread_info::lti_key, lfsck_thread_info::lti_lmv, lfsck_thread_info::lti_name, lfsck_thread_info::lti_tmpbuf, lu_fid_eq(), lustre_handle_is_used(), PFID, and unlikely.
Referenced by lfsck_namespace_double_scan_dir(), and lfsck_namespace_dsd_multiple().
static void lfsck_namespace_dump (const struct lu_env * env, struct lfsck_component * com, struct seq_file * m) [static]
Definition at line 4209 of file lfsck_namespace.c.
References __u64, cfs_duration_sec(), cfs_time_current(), DFID, dt_index_operations::dio_it, dt_object::do_index_ops, fid_zero(), HALF_SEC, LASSERT, lfsck_bookmark::lb_param, lfsck_bookmark::lb_version, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_new_checked, lfsck_component::lc_sem, lfsck_component::lc_time_last_checkpoint, lfsck_bits_dump(), lfsck_dto2fid(), lfsck_flags_names, lfsck_namespace_dump_statistics(), lfsck_param_names, lfsck_pos_dump(), lfsck_status2name(), lfsck_time_dump(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_cookie_dir, lfsck_instance::li_current_oit_processed, lfsck_instance::li_di_dir, lfsck_instance::li_di_oit, lfsck_instance::li_lock, lfsck_instance::li_obj_dir, lfsck_instance::li_obj_oit, lfsck_instance::li_time_last_checkpoint, lfsck_namespace::ln_fid_latest_scanned_phase2, lfsck_namespace::ln_flags, lfsck_namespace::ln_items_checked, lfsck_namespace::ln_magic, lfsck_namespace::ln_objs_checked_phase2, lfsck_namespace::ln_pos_first_inconsistent, lfsck_namespace::ln_pos_last_checkpoint, lfsck_namespace::ln_pos_latest_start, lfsck_namespace::ln_run_time_phase1, lfsck_namespace::ln_run_time_phase2, lfsck_namespace::ln_status, lfsck_namespace::ln_time_last_checkpoint, lfsck_namespace::ln_time_last_complete, lfsck_namespace::ln_time_latest_start, lfsck_position::lp_dir_cookie, lfsck_position::lp_dir_parent, lfsck_position::lp_oit_cookie, LPU64, LS_SCANNING_PHASE1, LS_SCANNING_PHASE2, MDS_DIR_END_OFF, and PFID.
static void lfsck_namespace_dump_statistics (struct seq_file * m, struct lfsck_namespace * ns, __u64 checked_phase1, __u64 checked_phase2, __u32 time_phase1, __u32 time_phase2) [static]
Definition at line 3568 of file lfsck_namespace.c.
References lfsck_namespace::ln_bad_type_repaired, lfsck_namespace::ln_dangling_repaired, lfsck_namespace::ln_dirent_repaired, lfsck_namespace::ln_dirs_checked, lfsck_namespace::ln_items_failed, lfsck_namespace::ln_items_repaired, lfsck_namespace::ln_linkea_repaired, lfsck_namespace::ln_local_lpf_failed, lfsck_namespace::ln_local_lpf_moved, lfsck_namespace::ln_local_lpf_scanned, lfsck_namespace::ln_local_lpf_skipped, lfsck_namespace::ln_lost_dirent_repaired, lfsck_namespace::ln_mul_linked_checked, lfsck_namespace::ln_mul_linked_repaired, lfsck_namespace::ln_mul_ref_repaired, lfsck_namespace::ln_name_hash_repaired, lfsck_namespace::ln_objs_failed_phase2, lfsck_namespace::ln_objs_nlink_repaired, lfsck_namespace::ln_objs_repaired_phase2, lfsck_namespace::ln_striped_dirs_disabled, lfsck_namespace::ln_striped_dirs_failed, lfsck_namespace::ln_striped_dirs_repaired, lfsck_namespace::ln_striped_dirs_scanned, lfsck_namespace::ln_striped_dirs_skipped, lfsck_namespace::ln_striped_shards_failed, lfsck_namespace::ln_striped_shards_repaired, lfsck_namespace::ln_striped_shards_scanned, lfsck_namespace::ln_striped_shards_skipped, lfsck_namespace::ln_success_count, lfsck_namespace::ln_unknown_inconsistency, lfsck_namespace::ln_unmatched_pairs_repaired, and LPU64.
Referenced by lfsck_namespace_dump().
static int lfsck_namespace_exec_dir (const struct lu_env * env, struct lfsck_component * com, struct lfsck_assistant_object * lso, struct lu_dirent * ent, __u16 type) [static]
Definition at line 4094 of file lfsck_namespace.c.
References l_wait_event, lfsck_assistant_data::lad_assistant_status, lfsck_assistant_data::lad_lock, lfsck_assistant_data::lad_prefetched, lfsck_assistant_data::lad_req_list, lfsck_assistant_data::lad_thread, lfsck_assistant_req::lar_list, lfsck_bookmark::lb_async_windows, lfsck_component::lc_data, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_new_checked, lfsck_component::lc_sem, lfsck_is_dead_obj(), lfsck_namespace_assistant_req_fini(), lfsck_namespace_assistant_req_init(), lfsck_namespace_record_failure(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_obj_dir, lfsck_instance::li_thread, list_add_tail(), lfsck_namespace_req::lnr_lar, ptlrpc_thread::t_ctl_waitq, thread_is_running(), thread_is_stopped(), and unlikely.
static int lfsck_namespace_exec_oit (const struct lu_env * env, struct lfsck_component * com, struct dt_object * obj) [static]
Definition at line 4005 of file lfsck_namespace.c.
References ENTRY, fid_is_sane(), fld_local_lookup(), fld_range_set_mdt(), GOTO, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_sem, LCK_EX, linkea_data::ld_lee, linkea_data::ld_leh, linkea_data::ld_reclen, link_ea_header::leh_reccount, lfsck_dev_idx(), lfsck_dev_site(), lfsck_dto2fid(), lfsck_env_info(), lfsck_ibits_lock(), lfsck_ibits_unlock(), lfsck_links_read(), lfsck_namespace_check_for_double_scan(), lfsck_namespace_links_remove(), lfsck_namespace_record_failure(), lfsck_namespace_trace_update(), lfsck_object_type(), linkea_entry_unpack(), linkea_first_entry(), lfsck_namespace::ln_dirs_checked, LNTF_CHECK_LINKEA, LNTF_CHECK_PARENT, lu_seq_range::lsr_index, lfsck_thread_info::lti_fid2, lfsck_thread_info::lti_name, lfsck_thread_info::lti_range, MDS_INODELOCK_UPDATE, MDS_INODELOCK_XATTR, and seq_server_site::ss_server_fld.
static void lfsck_namespace_fail (const struct lu_env * env, struct lfsck_component * com, bool new_checked) [static]
Definition at line 3762 of file lfsck_namespace.c.
References lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_new_checked, lfsck_component::lc_sem, and lfsck_namespace_record_failure().
static int lfsck_namespace_filter_linkea_entry (struct linkea_data * ldata, struct lu_name * cname, struct lu_fid * pfid, bool remove) [static]
Definition at line 791 of file lfsck_namespace.c.
References linkea_data::ld_lee, linkea_data::ld_reclen, link_ea_entry::lee_reclen, linkea_del_buf(), linkea_next_entry(), and unlikely.
Referenced by lfsck_namespace_double_scan_one(), lfsck_namespace_dsd_multiple(), and lfsck_namespace_shrink_linkea().
static int lfsck_namespace_in_notify (const struct lu_env * env, struct lfsck_component * com, struct lfsck_request * lr, struct thandle * th) [static]
Definition at line 4473 of file lfsck_namespace.c.
References CDEBUG, D_LFSCK, DFID, dt_declare_delete(), dt_declare_insert(), dt_delete(), dt_insert(), dt_key, dt_lookup(), dt_object_exists(), ENTRY, fid_cpu_to_be(), GOTO, lfsck_assistant_data::lad_mdt_list, lfsck_assistant_data::lad_mdt_phase2_list, lfsck_assistant_data::lad_thread, LASSERT, lfsck_bookmark::lb_param, lfsck_component::lc_data, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_sub_trace_objs, LE_PEER_EXIT, LE_PHASE1_DONE, LE_PHASE2_DONE, LE_SET_LMV_MASTER, LE_SET_LMV_SLAVE, LE_SKIP_NLINK, LE_SKIP_NLINK_DECLARE, LEF_RECHECK_NAME_HASH, LF_INCOMPLETE, lfsck_env_info(), lfsck_lfsck2name(), lfsck_ltd2tgt(), lfsck_namespace_notify_lmv_master_local(), lfsck_namespace_trace_update(), lfsck_object_find_bottom(), lfsck_object_put(), lfsck_phase2_next_ready(), lfsck_stop(), lfsck_sub_trace_file_fid2idx(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_bottom, lfsck_instance::li_mdt_descs, likely, list_add_tail(), list_del_init(), list_empty(), lfsck_namespace::ln_flags, lfsck_namespace::ln_striped_shards_repaired, LNTF_RECHECK_NAME_HASH, LNTF_SKIP_NLINK, LPF_BROADCAST, LPF_FAILOUT, lfsck_request::lr_event, lfsck_request::lr_fid, lfsck_request::lr_flags, lfsck_request::lr_flags2, lfsck_request::lr_index, lfsck_request::lr_param, lfsck_request::lr_status, lfsck_stop::ls_flags, lfsck_stop::ls_status, lfsck_sub_trace_obj::lsto_mutex, lfsck_sub_trace_obj::lsto_obj, lfsck_tgt_desc::ltd_index, lfsck_tgt_descs::ltd_lock, lfsck_tgt_desc::ltd_namespace_done, lfsck_tgt_desc::ltd_namespace_list, lfsck_tgt_desc::ltd_namespace_phase_list, lfsck_thread_info::lti_fid3, lfsck_thread_info::lti_stop, PFID, RETURN, stop, and ptlrpc_thread::t_ctl_waitq.
static int lfsck_namespace_init (const struct lu_env * env, struct lfsck_component * com) [static]
Definition at line 495 of file lfsck_namespace.c.
References lfsck_component::lc_file_ram, lfsck_component::lc_sem, lfsck_namespace_load_sub_trace_files(), LFSCK_NAMESPACE_MAGIC, lfsck_namespace_store(), lfsck_namespace::ln_magic, lfsck_namespace::ln_status, and LS_INIT.
Referenced by lfsck_namespace_setup().
static int lfsck_namespace_insert_normal (const struct lu_env * env, struct lfsck_component * com, struct dt_object * parent, struct dt_object * child, const char * name) [static]
Add the specified name entry back to namespace.
If there is a linkEA entry that back references a name entry under some parent directory, but such parent directory does not have the claimed name entry. On the other hand, the linkEA entries count is not larger than the MDT-object's hard link count. Under such case, it is quite possible that the name entry is lost. Then the LFSCK should add the name entry back to the namespace.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] parent pointer to the directory under which the name entry will be inserted into
[in] child pointer to the object referenced by the name entry that to be inserted into the parent
[in] name the name for the child in the parent directory
Return values:
positive number for repaired cases
0 if nothing to be repaired
negative error number on failure
Definition at line 1092 of file lfsck_namespace.c.
References CDEBUG, cfs_time_current_sec(), D_LFSCK, DFID, dt_attr_set(), dt_declare_attr_set(), dt_declare_insert(), dt_declare_ref_add(), dt_insert(), dt_key, dt_ref_add(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_try_as_dir(), dt_write_lock(), dt_write_unlock(), ENTRY, GOTO, LA_CTIME, lu_attr::la_ctime, lu_attr::la_valid, lfsck_bookmark::lb_param, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, LCK_PW, LF_INCONSISTENT, lfsck_dto2fid(), lfsck_env_info(), lfsck_lfsck2name(), lfsck_lock(), lfsck_object_locate(), lfsck_object_type(), lfsck_unlock(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_next, lfsck_namespace::ln_flags, lfsck_namespace::ln_lost_dirent_repaired, LPF_DRYRUN, lfsck_thread_info::lti_dt_rec, lfsck_thread_info::lti_la, lfsck_thread_info::lti_llh, MDS_INODELOCK_UPDATE, PFID, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, stop, and unlikely.
Referenced by lfsck_namespace_double_scan_one(), and lfsck_namespace_dsd_single().
static int lfsck_namespace_insert_orphan (const struct lu_env * env, struct lfsck_component * com, struct dt_object * orphan, const char * infix, const char * type, int * count) [static]
Insert orphan into .lustre/lost+found/MDTxxxx/ locally.
Add the specified orphan MDT-object to the .lustre/lost+found/MDTxxxx/ with the given type to generate the name, the detailed rules for name have been described as following.
The function also generates the linkEA corresponding to the name entry under the .lustre/lost+found/MDTxxxx/ for the orphan MDT-object.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] orphan pointer to the orphan MDT-object
[in] infix additional information for the orphan name, such as the FID for original
[in] type the type for describing why the orphan MDT-object is created. The rules are as following:
type "D": The MDT-object is a directory, it may knows its parent but because there is no valid linkEA, the LFSCK cannot know where to put it back to the namespace. type "O": The MDT-object has no linkEA, and there is no name entry that references the MDT-object.
type "S": The orphan MDT-object is a shard of a striped directory
See also:
lfsck_layout_recreate_parent() for more types.
The orphan name will be like: ${FID}-${infix}-${type}-${conflict_version}
Parameters:
[out] count if some others inserted some linkEA entries by race, then return the linkEA entries count.
Return values:
positive number for repaired cases
0 if needs to repair nothing
negative error number on failure
Definition at line 861 of file lfsck_namespace.c.
References CDEBUG, cfs_time_current_sec(), D_LFSCK, DFID, dotdot, dt_attr_set(), dt_declare_attr_set(), dt_declare_delete(), dt_declare_insert(), dt_declare_ref_add(), dt_declare_xattr_set(), dt_delete(), dt_insert(), dt_key, dt_lookup(), dt_ref_add(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), dt_xattr_set(), ENTRY, GOTO, LA_CTIME, lu_attr::la_ctime, lu_attr::la_valid, lu_buf::lb_buf, lfsck_bookmark::lb_param, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, LCK_EX, LCK_PW, linkea_data::ld_buf, linkea_data::ld_leh, link_ea_header::leh_len, link_ea_header::leh_reccount, LF_INCONSISTENT, lfsck_buf_init(), lfsck_dto2fid(), lfsck_env_info(), lfsck_ibits_lock(), lfsck_ibits_unlock(), lfsck_lfsck2name(), lfsck_links_read(), lfsck_lock(), lfsck_obj2dev(), lfsck_object_type(), lfsck_unlock(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_lpf_obj, likely, linkea_add_buf(), linkea_data_new(), lfsck_namespace::ln_flags, lu_name::ln_name, lu_name::ln_namelen, LPF_DRYRUN, lfsck_thread_info::lti_dt_rec, lfsck_thread_info::lti_key, lfsck_thread_info::lti_la2, lfsck_thread_info::lti_linkea_buf2, lfsck_thread_info::lti_llh, lfsck_thread_info::lti_name, lu_fid_eq(), MDS_INODELOCK_LOOKUP, MDS_INODELOCK_UPDATE, MDS_INODELOCK_XATTR, PFID, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, stop, unlikely, and XATTR_NAME_LINK.
Referenced by lfsck_namespace_double_scan_dir(), lfsck_namespace_double_scan_one(), lfsck_namespace_dsd_orphan(), and lfsck_namespace_dsd_single().
static void lfsck_namespace_le_to_cpu (struct lfsck_namespace * dst, struct lfsck_namespace * src) [static]
Definition at line 100 of file lfsck_namespace.c.
References fid_le_to_cpu(), le32_to_cpu, le64_to_cpu, lfsck_position_le_to_cpu(), lfsck_namespace::ln_bad_type_repaired, lfsck_namespace::ln_bitmap_size, lfsck_namespace::ln_dangling_repaired, lfsck_namespace::ln_dirent_repaired, lfsck_namespace::ln_dirs_checked, lfsck_namespace::ln_fid_latest_scanned_phase2, lfsck_namespace::ln_flags, lfsck_namespace::ln_items_checked, lfsck_namespace::ln_items_failed, lfsck_namespace::ln_items_repaired, lfsck_namespace::ln_linkea_repaired, lfsck_namespace::ln_local_lpf_failed, lfsck_namespace::ln_local_lpf_moved, lfsck_namespace::ln_local_lpf_scanned, lfsck_namespace::ln_local_lpf_skipped, lfsck_namespace::ln_lost_dirent_repaired, lfsck_namespace::ln_magic, lfsck_namespace::ln_mul_linked_checked, lfsck_namespace::ln_mul_linked_repaired, lfsck_namespace::ln_mul_ref_repaired, lfsck_namespace::ln_name_hash_repaired, lfsck_namespace::ln_objs_checked_phase2, lfsck_namespace::ln_objs_failed_phase2, lfsck_namespace::ln_objs_nlink_repaired, lfsck_namespace::ln_objs_repaired_phase2, lfsck_namespace::ln_pos_first_inconsistent, lfsck_namespace::ln_pos_last_checkpoint, lfsck_namespace::ln_pos_latest_start, lfsck_namespace::ln_run_time_phase1, lfsck_namespace::ln_run_time_phase2, lfsck_namespace::ln_status, lfsck_namespace::ln_striped_dirs_disabled, lfsck_namespace::ln_striped_dirs_failed, lfsck_namespace::ln_striped_dirs_repaired, lfsck_namespace::ln_striped_dirs_scanned, lfsck_namespace::ln_striped_dirs_skipped, lfsck_namespace::ln_striped_shards_failed, lfsck_namespace::ln_striped_shards_repaired, lfsck_namespace::ln_striped_shards_scanned, lfsck_namespace::ln_striped_shards_skipped, lfsck_namespace::ln_success_count, lfsck_namespace::ln_time_last_checkpoint, lfsck_namespace::ln_time_last_complete, lfsck_namespace::ln_time_latest_start, lfsck_namespace::ln_unknown_inconsistency, and lfsck_namespace::ln_unmatched_pairs_repaired.
Referenced by lfsck_namespace_load().
static int lfsck_namespace_links_remove (const struct lu_env * env, struct lfsck_component * com, struct dt_object * obj) [static]
Remove linkEA for the given object.
The caller should take the ldlm lock before the calling.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] obj pointer to the dt_object to be handled
Return values:
0 for repaired cases
negative error number on failure
Definition at line 714 of file lfsck_namespace.c.
References CDEBUG, D_LFSCK, DFID, dt_declare_xattr_del(), dt_object_remote(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), dt_xattr_del(), ENTRY, GOTO, LASSERT, lfsck_bookmark::lb_param, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, LF_INCONSISTENT, lfsck_dto2fid(), lfsck_is_dead_obj(), lfsck_lfsck2name(), lfsck_obj2dev(), lfsck_instance::li_bookmark_ram, lfsck_namespace::ln_flags, LPF_DRYRUN, PFID, stop, unlikely, and XATTR_NAME_LINK.
Referenced by lfsck_namespace_double_scan_dir(), lfsck_namespace_dsd_orphan(), and lfsck_namespace_exec_oit().
static int lfsck_namespace_load (const struct lu_env * env, struct lfsck_component * com) [static]
Load namespace LFSCK statistics information from the trace file.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
Return values:
0 for success
negative error number on failure
Definition at line 336 of file lfsck_namespace.c.
References CDEBUG, D_LFSCK, dt_xattr_get(), lfsck_component::lc_file_disk, lfsck_component::lc_file_ram, lfsck_component::lc_file_size, lfsck_component::lc_lfsck, lfsck_component::lc_obj, lfsck_buf_get(), lfsck_lfsck2name(), lfsck_namespace_le_to_cpu(), LFSCK_NAMESPACE_MAGIC, lfsck_namespace::ln_magic, and XATTR_NAME_LFSCK_NAMESPACE.
Referenced by lfsck_namespace_setup().
static int lfsck_namespace_load_bitmap (const struct lu_env * env, struct lfsck_component * com) [static]
Load the MDT bitmap from the lfsck_namespace trace file.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
Return values:
0 for success
negative error number on failure or data corruption
Definition at line 268 of file lfsck_namespace.c.
References CFS_ALLOCATE_BITMAP(), cfs_bitmap_check_empty(), CFS_FREE_BITMAP, CFS_RESET_BITMAP(), cfs_bitmap::data, dt_xattr_get(), ENTRY, lfsck_assistant_data::lad_bitmap, lfsck_assistant_data::lad_incomplete, lfsck_component::lc_data, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_obj, lfsck_buf_get(), lfsck_instance::li_mdt_descs, lfsck_namespace::ln_bitmap_size, lfsck_tgt_descs::ltd_tgts_bitmap, RETURN, cfs_bitmap::size, size, unlikely, and XATTR_NAME_LFSCK_BITMAP.
Referenced by lfsck_namespace_prep().
static struct dt_object* lfsck_namespace_load_one_trace_file (const struct lu_env * env, struct lfsck_component * com, struct dt_object * parent, const char * name, bool reset) [static, read]
Definition at line 438 of file lfsck_namespace.c.
References dt_lfsck_features, lfsck_component::lc_lfsck, lfsck_instance::li_bottom, lfsck_instance::li_los, local_index_find_or_create(), and local_object_unlink().
Referenced by lfsck_namespace_load_sub_trace_files(), and lfsck_namespace_reset().
static int lfsck_namespace_load_sub_trace_files (const struct lu_env * env, struct lfsck_component * com, bool reset) [static]
Definition at line 460 of file lfsck_namespace.c.
References dt_object_operations::do_index_try, dt_object::do_ops, dt_lfsck_features, lfsck_component::lc_lfsck, lfsck_component::lc_sub_trace_objs, lfsck_env_info(), LFSCK_NAMESPACE, lfsck_namespace_load_one_trace_file(), lfsck_object_put(), LFSCK_STF_COUNT, lfsck_instance::li_lfsck_dir, lfsck_sub_trace_obj::lsto_obj, lfsck_thread_info::lti_key, and name.
Referenced by lfsck_namespace_init(), lfsck_namespace_reset(), and lfsck_namespace_setup().
static int lfsck_namespace_open_dir (const struct lu_env * env, struct lfsck_component * com) [static]
Definition at line 3837 of file lfsck_namespace.c.
References ENTRY, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, LF_INCONSISTENT, lfsck_dev_idx(), lfsck_namespace_verify_stripe_slave(), lfsck_instance::li_lmv, lfsck_instance::li_obj_dir, lfsck_lmv::ll_lmv, lfsck_lmv::ll_lmv_master, lfsck_lmv::ll_lmv_updated, lmv_mds_md_v1::lmv_master_mdt_index, lfsck_namespace::ln_flags, and RETURN.
static int lfsck_namespace_post (const struct lu_env * env, struct lfsck_component * com, int result, bool init) [static]
Definition at line 4152 of file lfsck_namespace.c.
References CDEBUG, cfs_duration_sec(), cfs_time_current(), cfs_time_current_sec(), D_LFSCK, ENTRY, HALF_SEC, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_link, lfsck_component::lc_link_dir, lfsck_component::lc_new_checked, lfsck_component::lc_sem, LF_SCANNED_ONCE, LF_UPGRADE, lfsck_lfsck2name(), lfsck_namespace_release_lmv(), lfsck_namespace_store(), lfsck_post_generic(), lfsck_instance::li_list_double_scan, lfsck_instance::li_list_idle, lfsck_instance::li_lock, lfsck_instance::li_pos_checkpoint, lfsck_instance::li_status, lfsck_instance::li_time_last_checkpoint, list_del_init(), list_move_tail(), lfsck_namespace::ln_flags, lfsck_namespace::ln_items_checked, lfsck_namespace::ln_pos_last_checkpoint, lfsck_namespace::ln_run_time_phase1, lfsck_namespace::ln_status, lfsck_namespace::ln_time_last_checkpoint, LS_FAILED, LS_PAUSED, LS_SCANNING_PHASE2, LS_STOPPED, and RETURN.
static int lfsck_namespace_prep (const struct lu_env * env, struct lfsck_component * com, struct lfsck_start_param * lsp) [static]
Definition at line 3904 of file lfsck_namespace.c.
References CDEBUG, cfs_time_current_sec(), D_LFSCK, DFID, fid_zero(), lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_link, lfsck_component::lc_link_dir, lfsck_component::lc_pos_start, lfsck_component::lc_sem, LF_SCANNED_ONCE, lfsck_lfsck2name(), lfsck_namespace_load_bitmap(), lfsck_namespace_reset(), lfsck_pos_is_zero(), lfsck_pos_set_zero(), lfsck_set_param(), lfsck_start_assistant(), lfsck_instance::li_drop_dryrun, lfsck_instance::li_list_dir, lfsck_instance::li_list_double_scan, lfsck_instance::li_lock, list_add_tail(), list_del_init(), list_empty(), list_move_tail(), lfsck_namespace::ln_bad_type_repaired, lfsck_namespace::ln_dangling_repaired, lfsck_namespace::ln_dirent_repaired, lfsck_namespace::ln_dirs_checked, lfsck_namespace::ln_fid_latest_scanned_phase2, lfsck_namespace::ln_flags, lfsck_namespace::ln_items_checked, lfsck_namespace::ln_items_failed, lfsck_namespace::ln_items_repaired, lfsck_namespace::ln_linkea_repaired, lfsck_namespace::ln_lost_dirent_repaired, lfsck_namespace::ln_mul_linked_checked, lfsck_namespace::ln_mul_linked_repaired, lfsck_namespace::ln_mul_ref_repaired, lfsck_namespace::ln_name_hash_repaired, lfsck_namespace::ln_objs_checked_phase2, lfsck_namespace::ln_objs_failed_phase2, lfsck_namespace::ln_objs_nlink_repaired, lfsck_namespace::ln_objs_repaired_phase2, lfsck_namespace::ln_pos_first_inconsistent, lfsck_namespace::ln_pos_last_checkpoint, lfsck_namespace::ln_run_time_phase1, lfsck_namespace::ln_run_time_phase2, lfsck_namespace::ln_status, lfsck_namespace::ln_striped_dirs_disabled, lfsck_namespace::ln_striped_dirs_failed, lfsck_namespace::ln_striped_dirs_repaired, lfsck_namespace::ln_striped_dirs_scanned, lfsck_namespace::ln_striped_dirs_skipped, lfsck_namespace::ln_striped_shards_failed, lfsck_namespace::ln_striped_shards_repaired, lfsck_namespace::ln_striped_shards_scanned, lfsck_namespace::ln_striped_shards_skipped, lfsck_namespace::ln_time_latest_start, lfsck_namespace::ln_unknown_inconsistency, lfsck_namespace::ln_unmatched_pairs_repaired, lfsck_position::lp_dir_cookie, lfsck_position::lp_dir_parent, lfsck_position::lp_oit_cookie, LPU64, LPX64, LS_COMPLETED, LS_SCANNING_PHASE1, LS_SCANNING_PHASE2, lfsck_start_param::lsp_start, and PFID.
static int lfsck_namespace_query (const struct lu_env * env, struct lfsck_component * com, struct lfsck_request * req, struct lfsck_reply * rep, struct lfsck_query * que, int idx) [static]
Definition at line 4720 of file lfsck_namespace.c.
References LASSERT, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_sem, LEF_QUERY_ALL, lfsck_namespace_query_all(), lfsck_namespace_repaired(), lfsck_instance::li_master, lfsck_namespace::ln_status, lfsck_request::lr_flags, lfsck_reply::lr_repaired, lfsck_reply::lr_status, lfsck_query::lu_mdts_count, and lfsck_query::lu_repaired.
static int lfsck_namespace_query_all (const struct lu_env * env, struct lfsck_component * com, __u32 * mdts_count, __u64 * repaired) [static]
Definition at line 4687 of file lfsck_namespace.c.
References cfs_foreach_bit, ENTRY, LASSERT, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_sem, lfsck_ltd2tgt(), lfsck_namespace_repaired(), lfsck_query_all(), lfsck_instance::li_mdt_descs, lfsck_namespace::ln_status, lfsck_tgt_desc::ltd_namespace_repaired, lfsck_tgt_desc::ltd_namespace_status, lfsck_tgt_descs::ltd_rw_sem, lfsck_tgt_descs::ltd_tgts_bitmap, and RETURN.
Referenced by lfsck_namespace_query().
static void lfsck_namespace_quit (const struct lu_env * env, struct lfsck_component * com) [static]
Definition at line 4443 of file lfsck_namespace.c.
References lfsck_assistant_data::lad_mdt_phase1_list, lfsck_assistant_data::lad_mdt_phase2_list, lfsck_assistant_data::lad_req_list, lfsck_assistant_data::lad_thread, LASSERT, lfsck_component::lc_data, lfsck_component::lc_lfsck, lfsck_namespace_release_lmv(), lfsck_quit_generic(), lfsck_instance::li_mdt_descs, list_del_init(), list_empty(), list_for_each_entry_safe, lfsck_tgt_descs::ltd_lock, lfsck_tgt_desc::ltd_namespace_phase_list, thread_is_init(), and thread_is_stopped().
int lfsck_namespace_rebuild_linkea (const struct lu_env * env, struct lfsck_component * com, struct dt_object * obj, struct linkea_data * ldata)
Overwrite the linkEA for the object with the given ldata.
The caller should take the ldlm lock before the calling.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] obj pointer to the dt_object to be handled
[in] ldata pointer to the new linkEA data
Return values:
positive number for repaired cases
0 if nothing to be repaired
negative error number on failure
Definition at line 1910 of file lfsck_namespace.c.
References CDEBUG, D_LFSCK, DFID, dt_declare_xattr_set(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), dt_xattr_set(), ENTRY, GOTO, lu_buf::lb_buf, lfsck_bookmark::lb_param, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, linkea_data::ld_buf, linkea_data::ld_leh, link_ea_header::leh_len, LF_INCONSISTENT, lfsck_buf_init(), lfsck_dto2fid(), lfsck_is_dead_obj(), lfsck_lfsck2name(), lfsck_obj2dev(), lfsck_instance::li_bookmark_ram, lfsck_namespace::ln_flags, LPF_DRYRUN, PFID, stop, unlikely, and XATTR_NAME_LINK.
Referenced by lfsck_namespace_dsd_multiple(), and lfsck_namespace_striped_dir_rescan().
static void lfsck_namespace_record_failure (const struct lu_env * env, struct lfsck_instance * lfsck, struct lfsck_namespace * ns) [static]
Definition at line 238 of file lfsck_namespace.c.
References CDEBUG, D_LFSCK, DFID, lfsck_lfsck2name(), lfsck_pos_fill(), lfsck_pos_is_eq(), lfsck_pos_is_zero(), lfsck_namespace::ln_items_failed, lfsck_namespace::ln_pos_first_inconsistent, lfsck_position::lp_dir_cookie, lfsck_position::lp_dir_parent, lfsck_position::lp_oit_cookie, LPU64, LPX64, and PFID.
Referenced by lfsck_namespace_assistant_handler_p1(), lfsck_namespace_exec_dir(), lfsck_namespace_exec_oit(), and lfsck_namespace_fail().
static void lfsck_namespace_release_lmv (const struct lu_env * env, struct lfsck_component * com) [static]
Definition at line 3647 of file lfsck_namespace.c.
References LASSERTF, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_lmv_put(), lfsck_instance::li_list_lmv, list_empty(), list_entry, lfsck_lmv::ll_ref, lfsck_lmv_unit::llu_lmv, lfsck_namespace::ln_striped_dirs_skipped, and list_head::next.
Referenced by lfsck_namespace_data_release(), lfsck_namespace_post(), and lfsck_namespace_quit().
int lfsck_namespace_repair_dangling (const struct lu_env * env, struct lfsck_component * com, struct dt_object * parent, struct dt_object * child, struct lfsck_namespace_req * lnr)
Repair dangling name entry.
For the name entry with dangling reference, we need to repare the inconsistency according to the LFSCK sponsor's requirement:
1) Keep the inconsistency there and report the inconsistency case, then give the chance to the application to find related issues, and the users can make the decision about how to handle it with more human knownledge. (by default)
2) Re-create the missing MDT-object with the FID information.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] parent pointer to the dir object that contains the dangling name entry
[in] child pointer to the object corresponding to the dangling name entry
[in] lnr pointer to the namespace request that contains the name's name, parent object, parent's LMV, and ect.
Return values:
positive number if no need to repair
zero for repaired successfully
negative error number on failure
Definition at line 4790 of file lfsck_namespace.c.
References CDEBUG, D_LFSCK, DFID, dt_object_operations::do_ah_init, dt_object::do_ops, dt_object_format::dof_type, dot, dotdot, dt_create(), dt_declare_create(), dt_declare_insert(), dt_declare_ref_add(), dt_declare_xattr_set(), dt_insert(), dt_key, dt_mode_to_dft(), dt_ref_add(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_try_as_dir(), dt_write_lock(), dt_write_unlock(), dt_xattr_set(), ENTRY, GOTO, LA_ATIME, LA_CTIME, LA_GID, LA_MODE, lu_attr::la_mode, LA_MTIME, LA_TYPE, LA_UID, lu_attr::la_valid, lu_buf::lb_buf, lfsck_bookmark::lb_param, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, LCK_PR, linkea_data::ld_buf, linkea_data::ld_leh, link_ea_header::leh_len, LF_INCONSISTENT, lfsck_buf_init(), lfsck_dto2fid(), lfsck_env_info(), lfsck_lfsck2name(), lfsck_lmv_header_cpu_to_le(), lfsck_lock(), lfsck_name_get_const(), lfsck_namespace_check_exist(), lfsck_object_locate(), lfsck_shard_name_to_index(), lfsck_unlock(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_next, linkea_add_buf(), linkea_data_new(), lfsck_lmv::ll_lmv, lfsck_lmv::ll_lmv_master, lmv_mds_md_v1::lmv_magic, LMV_MAGIC_STRIPE, lmv_mds_md_v1::lmv_master_mdt_index, lfsck_namespace::ln_flags, lu_name::ln_name, lfsck_namespace_req::lnr_lmv, lfsck_namespace_req::lnr_name, lfsck_namespace_req::lnr_namelen, lfsck_namespace_req::lnr_type, LPF_CREATE_MDTOBJ, LPF_DRYRUN, lfsck_thread_info::lti_dof, lfsck_thread_info::lti_dt_rec, lfsck_thread_info::lti_hint, lfsck_thread_info::lti_la, lfsck_thread_info::lti_linkea_buf2, lfsck_thread_info::lti_llh, lfsck_thread_info::lti_lmv2, MDS_INODELOCK_UPDATE, PFID, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, stop, unlikely, XATTR_NAME_LINK, and XATTR_NAME_LMV.
Referenced by lfsck_namespace_assistant_handler_p1(), and lfsck_namespace_striped_dir_rescan().
int lfsck_namespace_repair_dirent (const struct lu_env * env, struct lfsck_component * com, struct dt_object * parent, struct dt_object * child, const char * name, const char * name2, __u16 type, bool update, bool dec)
Repair invalid name entry.
If the name entry contains invalid information, such as bad file type or (and) corrupted object FID, then either remove the name entry or udpate the name entry with the given (right) information.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] parent pointer to the parent directory
[in] child pointer to the object referenced by the name entry
[in] name the old name of the child under the parent directory
[in] name2 the new name of the child under the parent directory
[in] type the type claimed by the name entry
[in] update update the name entry if true; otherwise, remove it
[in] dec decrease the parent nlink count if true
Return values:
positive number for repaired successfully
0 if nothing to be repaired
negative error number on failure
Definition at line 1990 of file lfsck_namespace.c.
References CDEBUG, D_LFSCK, DFID, dt_declare_delete(), dt_declare_insert(), dt_declare_ref_del(), dt_delete(), dt_insert(), dt_key, dt_lookup(), dt_ref_del(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_try_as_dir(), dt_write_lock(), dt_write_unlock(), ENTRY, GOTO, lfsck_bookmark::lb_param, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, LCK_PW, LF_INCONSISTENT, lfsck_dto2fid(), lfsck_env_info(), lfsck_ibits_lock(), lfsck_ibits_unlock(), lfsck_lfsck2name(), lfsck_lock(), lfsck_namespace_trace_update(), lfsck_object_locate(), lfsck_object_type(), lfsck_unlock(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_next, lfsck_namespace::ln_flags, LNTF_CHECK_LINKEA, LPF_DRYRUN, lfsck_thread_info::lti_dt_rec, lfsck_thread_info::lti_llh, lu_fid_eq(), MDS_INODELOCK_UPDATE, PFID, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, stop, and unlikely.
Referenced by lfsck_namespace_assistant_handler_p1(), lfsck_namespace_dsd_multiple(), lfsck_namespace_handle_striped_master(), lfsck_namespace_striped_dir_rescan(), and lfsck_remove_dirent().
static int lfsck_namespace_repair_nlink (const struct lu_env * env, struct lfsck_component * com, struct dt_object * obj, struct lu_attr * la) [static]
Repair the object's nlink attribute.
If all the known name entries have been verified, then the object's hard link attribute should match the object's linkEA entries count unless the object's has too much hard link to be recorded in the linkEA. Such cases should have been marked in the LFSCK trace file. Otherwise, trust the linkEA to update the object's nlink attribute.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] obj pointer to the dt_object to be handled
[in,out] la pointer to buffer to object's attribute before and after the repairing
Return values:
positive number for repaired cases
0 if nothing to be repaired
negative error number on failure
Definition at line 2853 of file lfsck_namespace.c.
References CDEBUG, D_LFSCK, DFID, dt_attr_get(), dt_attr_set(), dt_declare_attr_set(), dt_key, dt_lookup(), dt_object_remote(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), ENTRY, fid_cpu_to_be(), GOTO, LA_NLINK, lu_attr::la_nlink, lu_attr::la_valid, LASSERT, lfsck_bookmark::lb_param, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_sub_trace_objs, LCK_PW, linkea_data::ld_leh, link_ea_header::leh_reccount, LF_INCOMPLETE, LF_INCONSISTENT, lfsck_dto2fid(), lfsck_env_info(), lfsck_ibits_lock(), lfsck_ibits_unlock(), lfsck_lfsck2name(), lfsck_links_read2(), lfsck_obj2dev(), lfsck_object_type(), lfsck_sub_trace_file_fid2idx(), lfsck_instance::li_bookmark_ram, lfsck_namespace::ln_flags, LNTF_SKIP_NLINK, LPF_DRYRUN, lfsck_sub_trace_obj::lsto_obj, lfsck_thread_info::lti_fid3, MDS_INODELOCK_UPDATE, PFID, stop, and unlikely.
Referenced by lfsck_namespace_double_scan_one().
static int lfsck_namespace_repair_unmatched_pairs (const struct lu_env * env, struct lfsck_component * com, struct dt_object * obj, const struct lu_fid * pfid, struct lu_name * cname) [static]
Update the ".." name entry for the given object.
The object's ".." is corrupted, this function will update the ".." name entry with the given pfid, and the linkEA with the given ldata.
The caller should take the ldlm lock before the calling.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] obj pointer to the dt_object to be handled
[in] pfid the new fid for the object's ".." name entry
[in] cname the name for the in the parent directory
Return values:
positive number for repaired cases
0 if nothing to be repaired
negative error number on failure
Definition at line 2147 of file lfsck_namespace.c.
References CDEBUG, D_LFSCK, DFID, dotdot, dt_declare_delete(), dt_declare_insert(), dt_declare_xattr_set(), dt_delete(), dt_insert(), dt_key, dt_object_remote(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), dt_xattr_set(), ENTRY, GOTO, LASSERT, lu_buf::lb_buf, lfsck_bookmark::lb_param, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, linkea_data::ld_buf, linkea_data::ld_leh, link_ea_header::leh_len, LF_INCONSISTENT, lfsck_buf_init(), lfsck_dto2fid(), lfsck_env_info(), lfsck_is_dead_obj(), lfsck_lfsck2name(), lfsck_obj2dev(), lfsck_object_type(), lfsck_instance::li_bookmark_ram, linkea_add_buf(), linkea_data_new(), lfsck_namespace::ln_flags, LPF_DRYRUN, lfsck_thread_info::lti_big_buf, lfsck_thread_info::lti_dt_rec, PFID, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, stop, unlikely, and XATTR_NAME_LINK.
Referenced by lfsck_namespace_dsd_multiple(), and lfsck_namespace_dsd_single().
static void lfsck_namespace_repaired (struct lfsck_namespace * ns, __u64 * count) [static]
Definition at line 4669 of file lfsck_namespace.c.
References lfsck_namespace::ln_bad_type_repaired, lfsck_namespace::ln_dangling_repaired, lfsck_namespace::ln_dirent_repaired, lfsck_namespace::ln_linkea_repaired, lfsck_namespace::ln_local_lpf_moved, lfsck_namespace::ln_lost_dirent_repaired, lfsck_namespace::ln_mul_linked_repaired, lfsck_namespace::ln_mul_ref_repaired, lfsck_namespace::ln_name_hash_repaired, lfsck_namespace::ln_objs_nlink_repaired, lfsck_namespace::ln_striped_dirs_disabled, lfsck_namespace::ln_striped_dirs_repaired, lfsck_namespace::ln_striped_shards_repaired, and lfsck_namespace::ln_unmatched_pairs_repaired.
Referenced by lfsck_namespace_query(), and lfsck_namespace_query_all().
static int lfsck_namespace_replace_cond (const struct lu_env * env, struct lfsck_component * com, struct dt_object * parent, struct dt_object * child, const struct lu_fid * cfid, const struct lu_name * cname) [static]
Conditionally replace name entry in the parent.
As required, the LFSCK may re-create the lost MDT-object for dangling name entry, but such repairing may be wrong because of bad FID in the name entry. As the LFSCK processing, the real MDT-object may be found, then the LFSCK should check whether the former re-created MDT-object has been modified or not, if not, then destroy it and update the name entry in the parent to reference the real MDT-object.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] parent pointer to the parent directory
[in] child pointer to the MDT-object that may be the real MDT-object corresponding to the name entry in parent
[in] cfid the current FID in the name entry
[in] cname contains the name of the child in the parent directory
Return values:
positive number for repaired cases
0 if nothing to be repaired
negative error number on failure
Definition at line 1711 of file lfsck_namespace.c.
References CDEBUG, D_LFSCK, DFID, dt_attr_get(), dt_declare_delete(), dt_declare_destroy(), dt_declare_insert(), dt_delete(), dt_destroy(), dt_insert(), dt_key, dt_lookup(), dt_object_exists(), dt_read_lock(), dt_read_unlock(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_try_as_dir(), dt_xattr_get(), ENTRY, fid_is_sane(), GOTO, lu_attr::la_ctime, lu_attr::la_mode, lfsck_bookmark::lb_param, lfsck_component::lc_lfsck, LCK_EX, LCK_PW, lfsck_dto2fid(), lfsck_env_info(), lfsck_ibits_lock(), lfsck_ibits_unlock(), lfsck_is_dead_obj(), lfsck_lfsck2name(), lfsck_links_read2(), lfsck_lock(), lfsck_object_find_by_dev(), lfsck_object_locate(), lfsck_object_put(), lfsck_unlock(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_next, linkea_links_find(), lu_name::ln_name, LPF_DRYRUN, lfsck_thread_info::lti_dt_rec, lfsck_thread_info::lti_la, lfsck_thread_info::lti_llh, LU_BUF_NULL, lu_fid_eq(), MDS_INODELOCK_UPDATE, MDS_INODELOCK_XATTR, name, PFID, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, stop, unlikely, and XATTR_NAME_LOV.
Referenced by lfsck_namespace_double_scan_one(), lfsck_namespace_dsd_multiple(), and lfsck_namespace_dsd_single().
static int lfsck_namespace_rescan_striped_dir (const struct lu_env * env, struct lfsck_component * com, struct lfsck_lmv_unit * llu) [static]
Rescan the striped directory after the master LMV EA reset.
Sometimes, the master LMV EA of the striped directory maybe lost, so when the namespace LFSCK engine scan the striped directory for the first time, it will be regarded as a normal directory. As the LFSCK processing, some other LFSCK instance on other MDT will find the shard of this striped dir, and find that the master MDT-object of the striped directory lost its LMV EA, then such remote LFSCK instance will regenerate the master LMV EA and notify the LFSCK instance on this MDT to rescan the striped directory.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] llu the lfsck_lmv_unit that contains the striped directory to be rescanned.
Return values:
positive number for success
0 for LFSCK stopped/paused
negative error number on failure
Definition at line 5869 of file lfsck_namespace.c.
References dt_index_operations::dio_it, dir, dt_object::do_index_ops, ENTRY, GOTO, lfsck_assistant_data::lad_lock, lfsck_assistant_data::lad_req_list, LASSERT, lfsck_component::lc_data, lfsck_component::lc_lfsck, lfsck_assistant_object_init(), lfsck_assistant_object_put(), lfsck_close_dir(), lfsck_dto2fid(), lfsck_env_info(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_assistant_req_fini(), lfsck_namespace_assistant_req_init(), lfsck_object_get(), lfsck_open_dir(), lfsck_unpack_ent(), lfsck_instance::li_args_dir, lfsck_instance::li_bookmark_ram, lfsck_instance::li_cookie_dir, lfsck_instance::li_di_dir, lfsck_instance::li_lmv, lfsck_instance::li_obj_dir, lfsck_instance::li_pos_current, lfsck_instance::li_thread, list_del_init(), list_empty(), list_entry, lfsck_lmv_unit::llu_lmv, lfsck_lmv_unit::llu_obj, lfsck_position::lp_oit_cookie, LPF_FAILOUT, lfsck_thread_info::lti_key, name_is_dot_or_dotdot(), list_head::next, dt_index_operations::dt_it_ops::rec, RETURN, thread, thread_is_running(), and unlikely.
Referenced by lfsck_namespace_assistant_handler_p2().
static int lfsck_namespace_reset (const struct lu_env * env, struct lfsck_component * com, bool init) [static]
Definition at line 3699 of file lfsck_namespace.c.
References __u64, CDEBUG, CFS_RESET_BITMAP(), D_LFSCK, dt_locate(), dt_try_as_dir(), ENTRY, GOTO, lfsck_assistant_data::lad_bitmap, lfsck_assistant_data::lad_incomplete, lfsck_component::lc_data, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_obj, lfsck_component::lc_sem, lfsck_lfsck2name(), LFSCK_NAMESPACE, lfsck_namespace_load_one_trace_file(), lfsck_namespace_load_sub_trace_files(), LFSCK_NAMESPACE_MAGIC, lfsck_namespace_store(), lfsck_object_put(), lfsck_instance::li_bottom, lfsck_instance::li_local_root_fid, lfsck_namespace::ln_magic, lfsck_namespace::ln_status, lfsck_namespace::ln_success_count, lfsck_namespace::ln_time_last_complete, LS_INIT, and unlikely.
Referenced by lfsck_namespace_prep(), and lfsck_namespace_setup().
static void lfsck_namespace_scan_local_lpf (const struct lu_env * env, struct lfsck_component * com) [static]
Handle orphans under the backend /lost+found directory.
Some backend checker, such as e2fsck for ldiskfs may find some orphans and put them under the backend /lost+found directory that is invisible to client. The LFSCK will scan such directory, for the original client visible orphans, add their fids into the namespace LFSCK trace file, then the subsenquent namespace LFSCK second-stage scanning can handle them as other objects to be double scanned: either move back to normal namespace, or to the global visible orphan directory: /ROOT/.lustre/lost+found/MDTxxxx/
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
Definition at line 5699 of file lfsck_namespace.c.
References __u64, CDEBUG, CERROR, CFS_FAIL_TIMEOUT, cfs_fail_val, D_LFSCK, DFID, dt_object_exists(), dt_try_as_dir(), ENTRY, EXIT, fid_is_norm(), fid_seq_in_fldb(), fld_local_lookup(), fld_range_set_mdt(), GOTO, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_new_scanned, lfsck_component::lc_sem, lfsck_control_speed_by_self(), lfsck_dev_idx(), lfsck_dev_site(), lfsck_env_info(), lfsck_lfsck2name(), lfsck_namespace_scan_local_lpf_one(), lfsck_object_find_by_dev(), lfsck_object_put(), lfsck_unpack_ent(), LPF_FAILOUT, lfsck_thread_info::lti_key, lfsck_thread_info::lti_range, LU_BACKEND_LPF_FID, LUDA_64BITHASH, LUDA_TYPE, name_is_dot_or_dotdot(), OBD_FAIL_LFSCK_DELAY3, PFID, RETURN_EXIT, thread, thread_is_running(), and unlikely.
Referenced by lfsck_namespace_assistant_handler_p2().
static int lfsck_namespace_scan_local_lpf_one (const struct lu_env * env, struct lfsck_component * com, struct dt_object * parent, struct lu_dirent * ent) [static]
Handle one orphan under the backend /lost+found directory.
Insert the orphan FID into the namespace LFSCK trace file for further processing (via the subsequent namespace LFSCK second-stage scanning). At the same time, remove the orphan name entry from backend /lost+found directory. There is an interval between the orphan name entry removed from the backend /lost+found directory and the orphan FID in the LFSCK trace file handled. In such interval, the LFSCK can be reset, then all the FIDs recorded in the namespace LFSCK trace file will be dropped. To guarantee that the orphans can be found when LFSCK run next time without e2fsck again, when remove the orphan name entry, the LFSCK will set the orphan's ctime attribute as 1. Since normal applications cannot change the object's ctime attribute as 1. Then when LFSCK run next time, it can record the object (that ctime is 1) in the namespace LFSCK trace file during the first-stage scanning.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] parent pointer to the object for the backend /lost+found
[in] ent pointer to the name entry for the target under the backend /lost+found
Return values:
positive for repaired
0 if needs to repair nothing
negative error number on failure
Definition at line 5560 of file lfsck_namespace.c.
References dt_attr_set(), dt_declare_attr_set(), dt_declare_delete(), dt_declare_insert(), dt_declare_ref_del(), dt_delete(), dt_insert(), dt_key, dt_lookup(), dt_object_exists(), dt_object_remote(), dt_ref_del(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), ENTRY, fid_cpu_to_be(), GOTO, LA_CTIME, lu_attr::la_ctime, lu_attr::la_valid, LASSERT, lfsck_component::lc_lfsck, lfsck_component::lc_sub_trace_objs, lu_dirent::lde_fid, lu_dirent::lde_name, lfsck_env_info(), lfsck_object_find_by_dev(), lfsck_object_put(), lfsck_object_type(), lfsck_sub_trace_file_fid2idx(), lfsck_instance::li_bottom, LNTF_CHECK_ORPHAN, lfsck_sub_trace_obj::lsto_obj, lfsck_thread_info::lti_fid, lfsck_thread_info::lti_la, RETURN, and stop.
Referenced by lfsck_namespace_scan_local_lpf().
int lfsck_namespace_setup (const struct lu_env * env, struct lfsck_instance * lfsck)
Definition at line 6514 of file lfsck_namespace.c.
References CERROR, dt_lfsck_features, dt_locate(), dt_try_as_dir(), ENTRY, GOTO, INIT_LIST_HEAD, LASSERT, lfsck_component::lc_data, lfsck_component::lc_file_disk, lfsck_component::lc_file_ram, lfsck_component::lc_file_size, lfsck_component::lc_lfsck, lfsck_component::lc_link, lfsck_component::lc_link_dir, lfsck_component::lc_obj, lfsck_component::lc_ops, lfsck_component::lc_ref, lfsck_component::lc_sem, lfsck_component::lc_sub_trace_objs, lfsck_component::lc_type, lfsck_assistant_data_init(), lfsck_component_cleanup(), lfsck_lfsck2name(), LFSCK_NAMESPACE, lfsck_namespace_init(), lfsck_namespace_load(), lfsck_namespace_load_sub_trace_files(), lfsck_namespace_reset(), lfsck_object_put(), LFSCK_STF_COUNT, LFSCK_TYPE_NAMESPACE, lfsck_instance::li_bottom, lfsck_instance::li_list_dir, lfsck_instance::li_list_idle, lfsck_instance::li_list_scan, lfsck_instance::li_local_root_fid, lfsck_instance::li_lock, lfsck_instance::li_los, lfsck_instance::li_master, list_add_tail(), lfsck_namespace::ln_status, local_index_find_or_create(), LS_COMPLETED, LS_CRASHED, LS_FAILED, LS_INIT, LS_PAUSED, LS_SCANNING_PHASE1, LS_SCANNING_PHASE2, LS_STOPPED, lfsck_sub_trace_obj::lsto_mutex, OBD_ALLOC, OBD_ALLOC_PTR, RETURN, and unlikely.
Referenced by lfsck_register().
static int lfsck_namespace_shrink_linkea (const struct lu_env * env, struct lfsck_component * com, struct dt_object * obj, struct linkea_data * ldata, struct lu_name * cname, struct lu_fid * pfid, bool next) [static]
Remove the specified entry from the linkEA.
Locate the linkEA entry with the given and , then remove this entry or the other entries those are repeated with this entry.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] obj pointer to the dt_object to be handled
[in,out] pointer to the buffer that holds the linkEA
[in] cname the name for the child in the parent directory
[in] pfid the parent directory's FID for the linkEA
[in] next if true, then remove the first found linkEA entry, and move the ldata->ld_lee to next entry
Return values:
positive number for repaired cases
0 if nothing to be repaired
negative error number on failure
Definition at line 1498 of file lfsck_namespace.c.
References CDEBUG, D_LFSCK, DFID, dt_declare_xattr_set(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), dt_xattr_set(), ENTRY, GOTO, lu_buf::lb_buf, lu_buf::lb_len, lfsck_bookmark::lb_param, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, LCK_EX, linkea_data::ld_buf, linkea_data::ld_leh, link_ea_header::leh_len, LF_INCONSISTENT, lfsck_buf_init(), lfsck_dto2fid(), lfsck_ibits_lock(), lfsck_ibits_unlock(), lfsck_is_dead_obj(), lfsck_lfsck2name(), lfsck_links_read2(), lfsck_namespace_filter_linkea_entry(), lfsck_obj2dev(), lfsck_instance::li_bookmark_ram, linkea_del_buf(), linkea_links_find(), lfsck_namespace::ln_flags, lu_name::ln_name, lu_name::ln_namelen, LPF_DRYRUN, MDS_INODELOCK_UPDATE, MDS_INODELOCK_XATTR, PFID, stop, unlikely, and XATTR_NAME_LINK.
Referenced by lfsck_namespace_double_scan_one(), lfsck_namespace_dsd_single(), and lfsck_namespace_shrink_linkea_cond().
static int lfsck_namespace_shrink_linkea_cond (const struct lu_env * env, struct lfsck_component * com, struct dt_object * parent, struct dt_object * child, struct linkea_data * ldata, struct lu_name * cname, struct lu_fid * pfid) [static]
Conditionally remove the specified entry from the linkEA.
Take the parent lock firstly, then check whether the specified name entry exists or not: if yes, do nothing; otherwise, call lfsck_namespace_shrink_linkea() to remove the linkea entry.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] parent pointer to the parent directory
[in] child pointer to the child object that holds the linkEA
[in,out] pointer to the buffer that holds the linkEA
[in] cname the name for the child in the parent directory
[in] pfid the parent directory's FID for the linkEA
Return values:
positive number for repaired cases
0 if nothing to be repaired
negative error number on failure
Definition at line 1624 of file lfsck_namespace.c.
References dt_key, dt_lookup(), dt_read_lock(), dt_read_unlock(), ENTRY, lfsck_component::lc_lfsck, LCK_PR, lfsck_dto2fid(), lfsck_env_info(), lfsck_is_dead_obj(), lfsck_lock(), lfsck_namespace_shrink_linkea(), lfsck_unlock(), linkea_next_entry(), lu_name::ln_name, lfsck_thread_info::lti_fid3, lfsck_thread_info::lti_llh, lu_fid_eq(), MDS_INODELOCK_UPDATE, RETURN, and unlikely.
Referenced by lfsck_namespace_double_scan_one(), and lfsck_namespace_dsd_single().
static int lfsck_namespace_store (const struct lu_env * env, struct lfsck_component * com) [static]
Definition at line 369 of file lfsck_namespace.c.
References CDEBUG, D_LFSCK, cfs_bitmap::data, dt_declare_xattr_set(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_xattr_set(), ENTRY, GOTO, lfsck_assistant_data::lad_bitmap, LASSERT, LASSERTF, lfsck_component::lc_data, lfsck_component::lc_file_disk, lfsck_component::lc_file_ram, lfsck_component::lc_file_size, lfsck_component::lc_lfsck, lfsck_component::lc_obj, lfsck_buf_get(), lfsck_lfsck2name(), lfsck_namespace_cpu_to_le(), lfsck_obj2dev(), lfsck_namespace::ln_bitmap_size, cfs_bitmap::size, XATTR_NAME_LFSCK_BITMAP, and XATTR_NAME_LFSCK_NAMESPACE.
Referenced by lfsck_namespace_checkpoint(), lfsck_namespace_double_scan_one_trace_file(), lfsck_namespace_double_scan_result(), lfsck_namespace_init(), lfsck_namespace_post(), and lfsck_namespace_reset().
int lfsck_namespace_trace_update (const struct lu_env * env, struct lfsck_component * com, const struct lu_fid * fid, const __u8 flags, bool add)
Update the namespace LFSCK trace file for the given .
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] fid the fid which flags to be updated in the lfsck trace file
[in] add true if add new flags, otherwise remove flags
Return values:
0 for success or nothing to be done
negative error number on failure
Definition at line 525 of file lfsck_namespace.c.
References CDEBUG, D_LFSCK, DFID, dt_declare_delete(), dt_declare_insert(), dt_delete(), dt_insert(), dt_key, dt_lookup(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), ENTRY, fid_cpu_to_be(), fid_is_sane(), GOTO, LASSERT, lfsck_component::lc_lfsck, lfsck_component::lc_sub_trace_objs, lfsck_env_info(), lfsck_lfsck2name(), lfsck_obj2dev(), lfsck_sub_trace_file_fid2idx(), lfsck_sub_trace_obj::lsto_mutex, lfsck_sub_trace_obj::lsto_obj, lfsck_thread_info::lti_fid3, PFID, RETURN, and unlikely.
Referenced by lfsck_namespace_assistant_handler_p1(), lfsck_namespace_check_for_double_scan(), lfsck_namespace_exec_oit(), lfsck_namespace_handle_striped_master(), lfsck_namespace_in_notify(), lfsck_namespace_repair_dirent(), lfsck_namespace_striped_dir_rescan(), lfsck_namespace_verify_stripe_slave(), and lfsck_record_lmv().
static void lfsck_namespace_unpack_linkea_entry (struct linkea_data * ldata, struct lu_name * cname, struct lu_fid * pfid, char * buf) [static]
Definition at line 779 of file lfsck_namespace.c.
References linkea_data::ld_lee, linkea_data::ld_reclen, linkea_entry_unpack(), lu_name::ln_name, and lu_name::ln_namelen.
Referenced by lfsck_namespace_double_scan_one(), lfsck_namespace_dsd_multiple(), and lfsck_namespace_dsd_single().
int lfsck_update_name_entry (const struct lu_env * env, struct lfsck_instance * lfsck, struct dt_object * dir, const char * name, const struct lu_fid * fid, __u32 type)
Update the object's name entry with the given FID.
Parameters:
[in] env pointer to the thread context
[in] lfsck pointer to the lfsck instance
[in] dir pointer to the directory that holds the name entry
[in] name the name for the entry to be updated
[in] fid the new FID for the name entry referenced
[in] type the type for the name entry to be updated
Return values:
0 for success
negative error number on failure
Definition at line 6441 of file lfsck_namespace.c.
References CDEBUG, D_LFSCK, DFID, dt_declare_delete(), dt_declare_insert(), dt_declare_ref_add(), dt_delete(), dt_insert(), dt_key, dt_ref_add(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), ENTRY, GOTO, LCK_PW, lfsck_dto2fid(), lfsck_env_info(), lfsck_lfsck2name(), lfsck_lock(), lfsck_obj2dev(), lfsck_unlock(), lfsck_thread_info::lti_dt_rec, lfsck_thread_info::lti_llh, MDS_INODELOCK_UPDATE, PFID, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, RETURN, and stop.
Referenced by lfsck_update_lpf_entry(), and lfsck_verify_lpf_pairs().
int lfsck_verify_linkea (const struct lu_env * env, struct dt_object * obj, const struct lu_name * cname, const struct lu_fid * pfid)
Verify the specified linkEA entry for the given directory object.
If the object has no such linkEA entry or it has more other linkEA entries, then re-generate the linkEA with the given information.
Parameters:
[in] env pointer to the thread context
[in] obj pointer to the dt_object to be handled
[in] cname the name for the child in the parent directory
[in] pfid the parent directory's FID for the linkEA
Return values:
0 for success
negative error number on failure
Definition at line 6325 of file lfsck_namespace.c.
References dt_declare_xattr_set(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), dt_xattr_set(), ENTRY, GOTO, LASSERT, lu_buf::lb_buf, linkea_data::ld_buf, linkea_data::ld_leh, link_ea_header::leh_len, link_ea_header::leh_reccount, lfsck_buf_init(), lfsck_env_info(), lfsck_links_read(), lfsck_obj2dev(), lfsck_object_type(), linkea_add_buf(), linkea_data_new(), linkea_links_find(), LU_XATTR_CREATE, LU_XATTR_REPLACE, RETURN, stop, and XATTR_NAME_LINK.
Referenced by lfsck_register(), lfsck_verify_lpf(), and lfsck_verify_lpf_pairs().
Variable Documentation
struct lfsck_assistant_operations lfsck_namespace_assistant_ops
Initial value:
 {
        .la_handler_p1          = lfsck_namespace_assistant_handler_p1,
        .la_handler_p2          = lfsck_namespace_assistant_handler_p2,
        .la_fill_pos            = lfsck_namespace_assistant_fill_pos,
        .la_double_scan_result  = lfsck_namespace_double_scan_result,
        .la_req_fini            = lfsck_namespace_assistant_req_fini,
        .la_sync_failures       = lfsck_namespace_assistant_sync_failures,
}
Definition at line 6303 of file lfsck_namespace.c.
struct lfsck_operations lfsck_namespace_ops [static]
Initial value:
 {
        .lfsck_reset            = lfsck_namespace_reset,
        .lfsck_fail             = lfsck_namespace_fail,
        .lfsck_close_dir        = lfsck_namespace_close_dir,
        .lfsck_open_dir         = lfsck_namespace_open_dir,
        .lfsck_checkpoint       = lfsck_namespace_checkpoint,
        .lfsck_prep             = lfsck_namespace_prep,
        .lfsck_exec_oit         = lfsck_namespace_exec_oit,
        .lfsck_exec_dir         = lfsck_namespace_exec_dir,
        .lfsck_post             = lfsck_namespace_post,
        .lfsck_dump             = lfsck_namespace_dump,
        .lfsck_double_scan      = lfsck_namespace_double_scan,
        .lfsck_data_release     = lfsck_namespace_data_release,
        .lfsck_quit             = lfsck_namespace_quit,
        .lfsck_in_notify        = lfsck_namespace_in_notify,
        .lfsck_query            = lfsck_namespace_query,
}
Definition at line 4746 of file lfsck_namespace.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.