Lustre: lustre/lfsck/lfsck_internal.h File Reference
lustre/lfsck/lfsck_internal.h File Reference
#include <lustre/lustre_lfsck_user.h>
#include <lustre/lustre_user.h>
#include <lustre/lustre_idl.h>
#include <lustre_lfsck.h>
#include <obd.h>
#include <lu_object.h>
#include <dt_object.h>
#include <md_object.h>
#include <lustre_net.h>
#include <lustre_dlm.h>
#include <lustre_fid.h>
#include <lustre_linkea.h>
Data Structures
struct lfsck_position
struct lfsck_bookmark
struct lfsck_namespace
struct lfsck_layout
struct lfsck_assistant_object
struct lfsck_operations
struct lfsck_tgt_desc
struct lfsck_tgt_desc_idx
struct lfsck_tgt_descs
struct lfsck_sub_trace_obj
struct lfsck_component
struct lfsck_slave_lmv_rec
struct lfsck_lmv
struct lfsck_lmv_unit
struct lfsck_rec_lmv_save
struct lfsck_instance
struct lfsck_async_interpret_args
struct lfsck_thread_args
struct lfsck_assistant_req
struct lfsck_namespace_req
struct lfsck_layout_req
struct lfsck_assistant_operations
struct lfsck_assistant_data
struct lfsck_lock_handle
struct lfsck_thread_info
Defines
#define HALF_SEC msecs_to_jiffies(MSEC_PER_SEC >> 1)
#define LFSCK_CHECKPOINT_INTERVAL 60
#define TGT_PTRS 256
#define TGT_PTRS_PER_BLOCK 256
#define LFSCK_STF_BITS 4
#define LFSCK_STF_COUNT (1 << LFSCK_STF_BITS)
#define LFSCK_LMV_MAX_STRIPES LMV_MAX_STRIPE_COUNT
#define LFSCK_LMV_DEF_STRIPES 4
#define LFSCK_REC_LMV_MAX_DEPTH 3
#define LFSCK_TMPBUF_LEN 64
Enumerations
enum lfsck_flags {
LF_SCANNED_ONCE = 0x00000001ULL, LF_INCONSISTENT = 0x00000002ULL, LF_UPGRADE = 0x00000004ULL, LF_INCOMPLETE = 0x00000008ULL,
LF_CRASHED_LASTID = 0x00000010ULL
}
enum lfsck_namespace_trace_flags {
LNTF_CHECK_LINKEA = 0x01, LNTF_CHECK_PARENT = 0x02, LNTF_SKIP_NLINK = 0x04, LNTF_CHECK_ORPHAN = 0x08,
LNTF_UNCERTAIN_LMV = 0x10, LNTF_RECHECK_NAME_HASH = 0x20, LNTF_ALL = 0xff
}
enum lfsck_namespace_inconsistency_type {
LNIT_NONE = 0, LNIT_BAD_LINKEA = 1, LNIT_UNMATCHED_PAIRS = 2, LNIT_DANGLING = 3,
LNIT_MUL_REF = 4, LNIT_BAD_TYPE = 5, LNIT_BAD_DIRENT = 6
}
enum lfsck_layout_inconsistency_type {
LLIT_NONE = 0, LLIT_DANGLING = 1, LLIT_UNMATCHED_PAIR = 2, LLIT_MULTIPLE_REFERENCED = 3,
LLIT_ORPHAN = 4, LLIT_INCONSISTENT_OWNER = 5, LLIT_OTHERS = 6, LLIT_MAX = LLIT_OTHERS
}
enum lfsck_slave_lmv_flags {
LSLF_NONE = 0, LSLF_BAD_INDEX2 = 1, LSLF_NO_LMVEA = 2, LSLF_DANGLING = 3,
LSLF_BAD_INDEX1 = 4
}
Functions
static struct lfsck_tgt_desc * lfsck_ltd2tgt (struct lfsck_tgt_descs *ltd, __u32 index)
static void lfsck_assign_tgt (struct lfsck_tgt_descs *ltd, struct lfsck_tgt_desc *tgt, __u32 index)
int lfsck_fid_alloc (const struct lu_env *env, struct lfsck_instance *lfsck, struct lu_fid *fid, bool locked)
int lfsck_ibits_lock (const struct lu_env *env, struct lfsck_instance *lfsck, struct dt_object *obj, struct lustre_handle *lh, __u64 bits, enum ldlm_mode mode)
Request the specified ibits lock for the given object.
void lfsck_ibits_unlock (struct lustre_handle *lh, enum ldlm_mode mode)
Release the the specified ibits lock.
int lfsck_lock (const struct lu_env *env, struct lfsck_instance *lfsck, struct dt_object *obj, const char *name, struct lfsck_lock_handle *llh, __u64 bits, enum ldlm_mode mode)
Request compound ibits locks for the given <obj, name> pairs.
void lfsck_unlock (struct lfsck_lock_handle *llh)
Release the the compound ibits locks.
int lfsck_find_mdt_idx_by_fid (const struct lu_env *env, struct lfsck_instance *lfsck, const struct lu_fid *fid)
int lfsck_verify_lpf (const struct lu_env *env, struct lfsck_instance *lfsck)
Verify the /ROOT/.lustre/lost+found/ directory.
struct lfsck_instance * lfsck_instance_find (struct dt_device *key, bool ref, bool unlink)
struct lfsck_component * lfsck_component_find (struct lfsck_instance *lfsck, __u16 type)
void lfsck_component_cleanup (const struct lu_env *env, struct lfsck_component *com)
void lfsck_instance_cleanup (const struct lu_env *env, struct lfsck_instance *lfsck)
void lfsck_bits_dump (struct seq_file *m, int bits, const char *names[], const char *prefix)
void lfsck_time_dump (struct seq_file *m, __u64 time, const char *name)
void lfsck_pos_dump (struct seq_file *m, struct lfsck_position *pos, const char *prefix)
void lfsck_pos_fill (const struct lu_env *env, struct lfsck_instance *lfsck, struct lfsck_position *pos, bool init)
bool __lfsck_set_speed (struct lfsck_instance *lfsck, __u32 limit)
void lfsck_control_speed (struct lfsck_instance *lfsck)
void lfsck_control_speed_by_self (struct lfsck_component *com)
void lfsck_thread_args_fini (struct lfsck_thread_args *lta)
struct lfsck_assistant_data * lfsck_assistant_data_init (struct lfsck_assistant_operations *lao, const char *name)
struct lfsck_assistant_object * lfsck_assistant_object_init (const struct lu_env *env, const struct lu_fid *fid, const struct lu_attr *attr, __u64 cookie, bool is_dir)
struct dt_object * lfsck_assistant_object_load (const struct lu_env *env, struct lfsck_instance *lfsck, struct lfsck_assistant_object *lso)
int lfsck_async_interpret_common (const struct lu_env *env, struct ptlrpc_request *req, void *args, int rc)
Generic LFSCK asynchronous communication interpretor function.
int lfsck_async_request (const struct lu_env *env, struct obd_export *exp, struct lfsck_request *lr, struct ptlrpc_request_set *set, ptlrpc_interpterer_t interpterer, void *args, int request)
int lfsck_query_all (const struct lu_env *env, struct lfsck_component *com)
int lfsck_start_assistant (const struct lu_env *env, struct lfsck_component *com, struct lfsck_start_param *lsp)
int lfsck_checkpoint_generic (const struct lu_env *env, struct lfsck_component *com)
void lfsck_post_generic (const struct lu_env *env, struct lfsck_component *com, int *result)
int lfsck_double_scan_generic (const struct lu_env *env, struct lfsck_component *com, int status)
void lfsck_quit_generic (const struct lu_env *env, struct lfsck_component *com)
int lfsck_unpack_ent (struct lu_dirent *ent, __u64 *cookie, __u16 *type)
void lfsck_close_dir (const struct lu_env *env, struct lfsck_instance *lfsck, int result)
int lfsck_open_dir (const struct lu_env *env, struct lfsck_instance *lfsck, __u64 cookie)
int lfsck_master_engine (void *args)
int lfsck_assistant_engine (void *args)
The LFSCK assistant thread is triggered by the LFSCK main engine.
void lfsck_bookmark_cpu_to_le (struct lfsck_bookmark *des, struct lfsck_bookmark *src)
int lfsck_bookmark_store (const struct lu_env *env, struct lfsck_instance *lfsck)
int lfsck_bookmark_setup (const struct lu_env *env, struct lfsck_instance *lfsck)
int lfsck_set_param (const struct lu_env *env, struct lfsck_instance *lfsck, struct lfsck_start *start, bool reset)
int lfsck_namespace_trace_update (const struct lu_env *env, struct lfsck_component *com, const struct lu_fid *fid, const __u8 flags, bool add)
Update the namespace LFSCK trace file for the given .
int lfsck_namespace_check_exist (const struct lu_env *env, struct dt_object *dir, struct dt_object *obj, const char *name)
int __lfsck_links_read (const struct lu_env *env, struct dt_object *obj, struct linkea_data *ldata)
int lfsck_namespace_rebuild_linkea (const struct lu_env *env, struct lfsck_component *com, struct dt_object *obj, struct linkea_data *ldata)
Overwrite the linkEA for the object with the given ldata.
int lfsck_namespace_repair_dangling (const struct lu_env *env, struct lfsck_component *com, struct dt_object *parent, struct dt_object *child, struct lfsck_namespace_req *lnr)
Repair dangling name entry.
int lfsck_namespace_repair_dirent (const struct lu_env *env, struct lfsck_component *com, struct dt_object *parent, struct dt_object *child, const char *name, const char *name2, __u16 type, bool update, bool dec)
Repair invalid name entry.
int lfsck_verify_linkea (const struct lu_env *env, struct dt_object *obj, const struct lu_name *cname, const struct lu_fid *pfid)
Verify the specified linkEA entry for the given directory object.
int lfsck_links_get_first (const struct lu_env *env, struct dt_object *obj, char *name, struct lu_fid *pfid)
Get the name and parent directory's FID from the first linkEA entry.
int lfsck_update_name_entry (const struct lu_env *env, struct lfsck_instance *lfsck, struct dt_object *dir, const char *name, const struct lu_fid *fid, __u32 type)
Update the object's name entry with the given FID.
int lfsck_namespace_setup (const struct lu_env *env, struct lfsck_instance *lfsck)
void lfsck_lmv_put (const struct lu_env *env, struct lfsck_lmv *llmv)
int lfsck_read_stripe_lmv (const struct lu_env *env, struct dt_object *obj, struct lmv_mds_md_v1 *lmv)
int lfsck_shard_name_to_index (const struct lu_env *env, const char *name, int namelen, __u16 type, const struct lu_fid *fid)
Parse the shard's index from the given shard name.
bool lfsck_is_valid_slave_name_entry (const struct lu_env *env, struct lfsck_lmv *llmv, const char *name, int namelen)
int lfsck_namespace_check_name (const struct lu_env *env, struct dt_object *parent, struct dt_object *child, const struct lu_name *cname)
Check whether the given name is a valid entry under the .
int lfsck_namespace_update_lmv (const struct lu_env *env, struct lfsck_component *com, struct dt_object *obj, struct lmv_mds_md_v1 *lmv, bool locked)
Update the object's LMV EA with the given .
int lfsck_namespace_verify_stripe_slave (const struct lu_env *env, struct lfsck_component *com, struct dt_object *obj, struct lfsck_lmv *llmv)
Verify the slave object's (of striped directory) LMV EA.
int lfsck_namespace_scan_shard (const struct lu_env *env, struct lfsck_component *com, struct dt_object *child)
Scan the shard of a striped directory for name hash verification.
int lfsck_namespace_notify_lmv_master_local (const struct lu_env *env, struct lfsck_component *com, struct dt_object *obj)
Generate request for local LFSCK instance to rescan the striped directory.
int lfsck_namespace_repair_bad_name_hash (const struct lu_env *env, struct lfsck_component *com, struct dt_object *shard, struct lfsck_lmv *llmv, const char *name)
Repair the bad name hash.
int lfsck_namespace_striped_dir_rescan (const struct lu_env *env, struct lfsck_component *com, struct lfsck_namespace_req *lnr)
Double scan the striped directory or the shard.
int lfsck_namespace_handle_striped_master (const struct lu_env *env, struct lfsck_component *com, struct lfsck_namespace_req *lnr)
Verify the shard's name entry under the striped directory.
int lfsck_layout_setup (const struct lu_env *env, struct lfsck_instance *lfsck)
static bool name_is_dot_or_dotdot (const char *name, int namelen)
static struct dt_device * lfsck_obj2dev (struct dt_object *obj)
static struct lfsck_thread_info * lfsck_env_info (const struct lu_env *env)
static struct lu_name * lfsck_name_get_const (const struct lu_env *env, const void *area, ssize_t len)
static void lfsck_buf_init (struct lu_buf *buf, void *area, ssize_t len)
static struct lu_buf * lfsck_buf_get (const struct lu_env *env, void *area, ssize_t len)
static struct lu_buf * lfsck_buf_get_const (const struct lu_env *env, const void *area, ssize_t len)
static char * lfsck_lfsck2name (struct lfsck_instance *lfsck)
static struct lu_fid * lfsck_dto2fid (const struct dt_object *obj)
static void lfsck_pos_set_zero (struct lfsck_position *pos)
static int lfsck_pos_is_zero (const struct lfsck_position *pos)
static int lfsck_pos_is_eq (const struct lfsck_position *pos1, const struct lfsck_position *pos2)
static void lfsck_position_le_to_cpu (struct lfsck_position *des, struct lfsck_position *src)
static void lfsck_position_cpu_to_le (struct lfsck_position *des, struct lfsck_position *src)
static umode_t lfsck_object_type (const struct dt_object *obj)
static int lfsck_is_dead_obj (const struct dt_object *obj)
static struct dt_object * lfsck_object_get (struct dt_object *obj)
static void lfsck_object_put (const struct lu_env *env, struct dt_object *obj)
static struct seq_server_site * lfsck_dev_site (struct lfsck_instance *lfsck)
static u32 lfsck_dev_idx (struct lfsck_instance *lfsck)
static struct dt_object * lfsck_object_find_by_dev_nowait (const struct lu_env *env, struct dt_device *dev, const struct lu_fid *fid)
static struct dt_object * lfsck_object_find_by_dev (const struct lu_env *env, struct dt_device *dev, const struct lu_fid *fid)
static struct dt_device * lfsck_find_dev_by_fid (const struct lu_env *env, struct lfsck_instance *lfsck, const struct lu_fid *fid)
static struct dt_object * lfsck_object_find_bottom (const struct lu_env *env, struct lfsck_instance *lfsck, const struct lu_fid *fid)
static struct dt_object * lfsck_object_find_bottom_nowait (const struct lu_env *env, struct lfsck_instance *lfsck, const struct lu_fid *fid)
static struct dt_object * lfsck_object_locate (struct dt_device *dev, struct dt_object *obj)
static struct lfsck_tgt_desc * lfsck_tgt_get (struct lfsck_tgt_descs *ltds, __u32 index)
static void lfsck_tgt_put (struct lfsck_tgt_desc *ltd)
static struct lfsck_component * lfsck_component_get (struct lfsck_component *com)
static void lfsck_component_put (const struct lu_env *env, struct lfsck_component *com)
static struct lfsck_instance * lfsck_instance_get (struct lfsck_instance *lfsck)
static void lfsck_instance_put (const struct lu_env *env, struct lfsck_instance *lfsck)
static bool lfsck_phase2_next_ready (struct lfsck_assistant_data *lad)
static void lfsck_lad_set_bitmap (const struct lu_env *env, struct lfsck_component *com, __u32 index)
static int lfsck_links_read (const struct lu_env *env, struct dt_object *obj, struct linkea_data *ldata)
static int lfsck_links_read2 (const struct lu_env *env, struct dt_object *obj, struct linkea_data *ldata)
static struct lfsck_lmv * lfsck_lmv_get (struct lfsck_lmv *llmv)
static int lfsck_sub_trace_file_fid2idx (const struct lu_fid *fid)
static void lfsck_lmv_header_le_to_cpu (struct lmv_mds_md_v1 *dst, const struct lmv_mds_md_v1 *src)
static void lfsck_lmv_header_cpu_to_le (struct lmv_mds_md_v1 *dst, const struct lmv_mds_md_v1 *src)
static struct
lfsck_assistant_object * lfsck_assistant_object_get (struct lfsck_assistant_object *lso)
static void lfsck_assistant_object_put (const struct lu_env *env, struct lfsck_assistant_object *lso)
Variables
const char dot []
const char dotdot []
const char * lfsck_flags_names []
const char * lfsck_param_names []
struct lu_context_key lfsck_thread_key
Define Documentation
#define HALF_SEC msecs_to_jiffies(MSEC_PER_SEC >> 1)
Definition at line 50 of file lfsck_internal.h.
Referenced by lfsck_layout_double_scan_result(), lfsck_layout_dump(), lfsck_layout_master_checkpoint(), lfsck_layout_master_post(), lfsck_layout_slave_checkpoint(), lfsck_layout_slave_post(), lfsck_namespace_checkpoint(), lfsck_namespace_double_scan_one_trace_file(), lfsck_namespace_double_scan_result(), lfsck_namespace_dump(), lfsck_namespace_post(), osd_scrub_checkpoint(), osd_scrub_dump(), and osd_scrub_post().
#define LFSCK_CHECKPOINT_INTERVAL 60
Definition at line 51 of file lfsck_internal.h.
Referenced by lfsck_assistant_engine(), lfsck_checkpoint(), lfsck_layout_slave_double_scan(), lfsck_namespace_assistant_handler_p2(), lfsck_namespace_double_scan_one_trace_file(), lfsck_post(), and lfsck_prep().
#define LFSCK_LMV_DEF_STRIPES 4
Definition at line 565 of file lfsck_internal.h.
Referenced by lfsck_load_stripe_lmv(), and lfsck_namespace_notify_lmv_master_local().
#define LFSCK_LMV_MAX_STRIPES LMV_MAX_STRIPE_COUNT
Definition at line 564 of file lfsck_internal.h.
Referenced by lfsck_is_valid_slave_lmv(), lfsck_load_stripe_lmv(), lfsck_namespace_notify_lmv_master_local(), lfsck_namespace_striped_dir_rescan(), lfsck_record_lmv(), lfsck_replace_lmv(), and lfsck_shard_name_to_index().
#define LFSCK_REC_LMV_MAX_DEPTH 3
Definition at line 631 of file lfsck_internal.h.
Referenced by lfsck_record_lmv().
#define LFSCK_STF_BITS 4
Definition at line 518 of file lfsck_internal.h.
#define LFSCK_STF_COUNT (1 << LFSCK_STF_BITS)
Definition at line 520 of file lfsck_internal.h.
Referenced by lfsck_component_put(), lfsck_namespace_assistant_handler_p2(), lfsck_namespace_load_sub_trace_files(), lfsck_namespace_setup(), and lfsck_sub_trace_file_fid2idx().
#define LFSCK_TMPBUF_LEN 64
Definition at line 845 of file lfsck_internal.h.
Referenced by lfsck_namespace_close_dir().
#define TGT_PTRS 256
Definition at line 443 of file lfsck_internal.h.
Referenced by lfsck_ltd2tgt(), lfsck_tgt_descs_fini(), and lod_fini_tgt().
#define TGT_PTRS_PER_BLOCK 256
Definition at line 444 of file lfsck_internal.h.
Referenced by __lfsck_add_target(), lfsck_assign_tgt(), lfsck_ltd2tgt(), and lod_add_device().
Enumeration Type Documentation
enum lfsck_flags
Enumerator:
LF_SCANNED_ONCE
LF_INCONSISTENT
LF_UPGRADE
LF_INCOMPLETE
LF_CRASHED_LASTID
Definition at line 53 of file lfsck_internal.h.
enum lfsck_layout_inconsistency_type
Enumerator:
LLIT_NONE
LLIT_DANGLING
LLIT_UNMATCHED_PAIR
LLIT_MULTIPLE_REFERENCED
LLIT_ORPHAN
LLIT_INCONSISTENT_OWNER
LLIT_OTHERS
LLIT_MAX
Definition at line 282 of file lfsck_internal.h.
enum lfsck_namespace_inconsistency_type
Enumerator:
LNIT_NONE
LNIT_BAD_LINKEA
LNIT_UNMATCHED_PAIRS
LNIT_DANGLING
LNIT_MUL_REF
LNIT_BAD_TYPE
LNIT_BAD_DIRENT
Definition at line 121 of file lfsck_internal.h.
enum lfsck_namespace_trace_flags
Enumerator:
LNTF_CHECK_LINKEA
LNTF_CHECK_PARENT
LNTF_SKIP_NLINK
LNTF_CHECK_ORPHAN
LNTF_UNCERTAIN_LMV
LNTF_RECHECK_NAME_HASH
LNTF_ALL
Definition at line 111 of file lfsck_internal.h.
enum lfsck_slave_lmv_flags
Enumerator:
LSLF_NONE
LSLF_BAD_INDEX2
LSLF_NO_LMVEA
LSLF_DANGLING
LSLF_BAD_INDEX1
Definition at line 569 of file lfsck_internal.h.
Function Documentation
int __lfsck_links_read (const struct lu_env * env, struct dt_object * obj, struct linkea_data * ldata)
Definition at line 671 of file lfsck_namespace.c.
References dt_object_exists(), dt_xattr_get(), lu_buf::lb_buf, linkea_data::ld_buf, linkea_init(), LU_BUF_NULL, lu_buf_realloc(), and XATTR_NAME_LINK.
Referenced by lfsck_links_read(), and lfsck_links_read2().
bool __lfsck_set_speed (struct lfsck_instance * lfsck, __u32 limit)
Definition at line 1830 of file lfsck_lib.c.
References lfsck_bookmark::lb_speed_limit, LFSCK_SPEED_NO_LIMIT, lfsck_instance::li_bookmark_ram, lfsck_instance::li_sleep_jif, and lfsck_instance::li_sleep_rate.
Referenced by lfsck_set_param(), lfsck_set_speed(), and lfsck_start().
static void lfsck_assign_tgt (struct lfsck_tgt_descs * ltd, struct lfsck_tgt_desc * tgt, __u32 index) [inline, static]
Definition at line 508 of file lfsck_internal.h.
References lfsck_tgt_desc_idx::ldi_tgts, likely, lfsck_tgt_descs::ltd_tgts_idx, and TGT_PTRS_PER_BLOCK.
Referenced by __lfsck_add_target(), lfsck_del_target(), and lfsck_tgt_descs_fini().
struct lfsck_assistant_data* lfsck_assistant_data_init (struct lfsck_assistant_operations * lao, const char * name) [read]
Definition at line 1929 of file lfsck_lib.c.
References CFS_ALLOCATE_BITMAP(), INIT_LIST_HEAD, lfsck_assistant_data::lad_bitmap, lfsck_assistant_data::lad_lock, lfsck_assistant_data::lad_mdt_list, lfsck_assistant_data::lad_mdt_phase1_list, lfsck_assistant_data::lad_mdt_phase2_list, lfsck_assistant_data::lad_name, lfsck_assistant_data::lad_ops, lfsck_assistant_data::lad_ost_list, lfsck_assistant_data::lad_ost_phase1_list, lfsck_assistant_data::lad_ost_phase2_list, lfsck_assistant_data::lad_req_list, lfsck_assistant_data::lad_thread, OBD_ALLOC_PTR, OBD_FREE_PTR, and ptlrpc_thread::t_ctl_waitq.
Referenced by lfsck_layout_setup(), and lfsck_namespace_setup().
int lfsck_assistant_engine (void * args)
The LFSCK assistant thread is triggered by the LFSCK main engine.
They co-work together as an asynchronous pipeline: the LFSCK main engine scans the system and pre-fetches the objects, attributes, or name entries, etc, and pushes them into the pipeline as input requests for the LFSCK assistant thread; on the other end of the pipeline, the LFSCK assistant thread performs the real check and repair for every request from the main engine.
Generally, the assistant engine may be blocked when check/repair something, so the LFSCK main engine will run some faster. On the other hand, the LFSCK main engine will drive multiple assistant threads in parallel, means for each LFSCK component on the master (such as layout LFSCK, namespace LFSCK), there is an independent LFSCK assistant thread. So under such 1:N multiple asynchronous pipelines mode, the whole LFSCK performance will be much better than check/repair everything by the LFSCK main engine itself.
Definition at line 1543 of file lfsck_engine.c.
References CDEBUG, cfs_time_current(), cfs_time_seconds(), D_LFSCK, dt_sync(), ENTRY, GOTO, l_wait_event, lfsck_assistant_operations::la_double_scan_result, lfsck_assistant_operations::la_fill_pos, lfsck_assistant_operations::la_handler_p1, lfsck_assistant_operations::la_handler_p2, lfsck_assistant_operations::la_req_fini, lfsck_assistant_data::lad_assistant_status, lfsck_assistant_data::lad_exit, lfsck_assistant_data::lad_in_double_scan, lfsck_assistant_data::lad_lock, lfsck_assistant_data::lad_name, lfsck_assistant_data::lad_ops, lfsck_assistant_data::lad_post_result, lfsck_assistant_data::lad_prefetched, lfsck_assistant_data::lad_req_list, lfsck_assistant_data::lad_task, lfsck_assistant_data::lad_thread, lfsck_assistant_data::lad_to_double_scan, lfsck_assistant_data::lad_to_post, lfsck_assistant_req::lar_list, LASSERT, LASSERTF, lfsck_bookmark::lb_async_windows, lfsck_component::lc_data, lfsck_component::lc_new_checked, lfsck_component::lc_new_scanned, lfsck_component::lc_pos_start, lfsck_component::lc_time_last_checkpoint, lfsck_component::lc_time_next_checkpoint, LE_PEER_EXIT, LE_PHASE1_DONE, LE_PHASE2_DONE, LE_START, LE_STOP, lfsck_assistant_notify_others(), lfsck_assistant_query_others(), lfsck_assistant_req_empty(), LFSCK_CHECKPOINT_INTERVAL, lfsck_env_info(), lfsck_lfsck2name(), lfsck_phase2_next_ready(), lfsck_thread_args_fini(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_double_scan_count, lfsck_instance::li_flags, lfsck_instance::li_next, lfsck_instance::li_pos_checkpoint, lfsck_instance::li_status, lfsck_instance::li_thread, list_del_init(), list_empty(), list_entry, lfsck_position::lp_oit_cookie, LPF_ALL_TGT, LPF_FAILOUT, LPF_RESET, lfsck_request::lr_event, lfsck_request::lr_param, lfsck_request::lr_status, LS_CO_FAILED, LS_CO_PAUSED, LS_CO_STOPPED, LS_FAILED, LS_PAUSED, LS_STOPPED, lfsck_thread_args::lta_com, lfsck_thread_args::lta_env, lfsck_thread_args::lta_lfsck, lfsck_thread_info::lti_lr, LWI_TIMEOUT_INTERVAL, list_head::next, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_NO_DOUBLESCAN, SVC_RUNNING, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, thread_is_running(), thread_set_flags(), and unlikely.
Referenced by lfsck_start_assistant().
static struct lfsck_assistant_object* lfsck_assistant_object_get (struct lfsck_assistant_object * lso) [static, read]
Definition at line 1479 of file lfsck_internal.h.
References lfsck_assistant_object::lso_ref.
Referenced by lfsck_layout_assistant_req_init(), and lfsck_namespace_assistant_req_init().
struct lfsck_assistant_object* lfsck_assistant_object_init (const struct lu_env * env, const struct lu_fid * fid, const struct lu_attr * attr, __u64 cookie, bool is_dir) [read]
Definition at line 1959 of file lfsck_lib.c.
References lfsck_assistant_object::lso_attr, lfsck_assistant_object::lso_fid, lfsck_assistant_object::lso_is_dir, lfsck_assistant_object::lso_oit_cookie, lfsck_assistant_object::lso_ref, and OBD_ALLOC_PTR.
Referenced by lfsck_layout_scan_stripes(), lfsck_master_dir_engine(), lfsck_namespace_close_dir(), and lfsck_namespace_rescan_striped_dir().
struct dt_object* lfsck_assistant_object_load (const struct lu_env * env, struct lfsck_instance * lfsck, struct lfsck_assistant_object * lso) [read]
Definition at line 1982 of file lfsck_lib.c.
References dt_object_exists(), dt_try_as_dir(), lfsck_is_dead_obj(), lfsck_object_find_bottom(), lfsck_object_put(), lfsck_assistant_object::lso_dead, lfsck_assistant_object::lso_fid, lfsck_assistant_object::lso_is_dir, and unlikely.
Referenced by lfsck_layout_assistant_handler_p1(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_handle_striped_master(), and lfsck_namespace_striped_dir_rescan().
static void lfsck_assistant_object_put (const struct lu_env * env, struct lfsck_assistant_object * lso) [inline, static]
Definition at line 1487 of file lfsck_internal.h.
References lfsck_assistant_object::lso_ref, and OBD_FREE_PTR.
Referenced by lfsck_layout_assistant_req_fini(), lfsck_layout_scan_stripes(), lfsck_namespace_assistant_req_fini(), and lfsck_namespace_rescan_striped_dir().
int lfsck_async_interpret_common (const struct lu_env * env, struct ptlrpc_request * req, void * args, int rc)
Generic LFSCK asynchronous communication interpretor function.
The LFSCK RPC reply for both the event notification and status querying will be handled here.
Parameters:
[in] env pointer to the thread context
[in] req pointer to the LFSCK request
[in] args pointer to the lfsck_async_interpret_args
[in] rc the result for handling the LFSCK request
Return values:
0 for success
negative error number on failure
Definition at line 2021 of file lfsck_lib.c.
References CDEBUG, D_LFSCK, lfsck_assistant_data::lad_mdt_list, lfsck_assistant_data::lad_mdt_phase1_list, lfsck_assistant_data::lad_mdt_phase2_list, lfsck_assistant_data::lad_name, lfsck_assistant_data::lad_ost_list, lfsck_assistant_data::lad_ost_phase1_list, lfsck_assistant_data::lad_ost_phase2_list, lfsck_async_interpret_args::laia_com, lfsck_async_interpret_args::laia_lr, lfsck_async_interpret_args::laia_ltd, lfsck_async_interpret_args::laia_ltds, lfsck_async_interpret_args::laia_shared, LASSERT, lfsck_component::lc_data, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_type, LE_PEER_EXIT, LE_PHASE1_DONE, LE_PHASE2_DONE, LE_QUERY, LE_START, LE_STOP, LEF_QUERY_ALL, LEF_TO_OST, LF_INCOMPLETE, lfsck_component_put(), lfsck_lad_set_bitmap(), lfsck_lfsck2name(), lfsck_reset_ltd_status(), lfsck_tgt_put(), LFSCK_TYPE_LAYOUT, lfsck_instance::li_master, list, list_add_tail(), list_del_init(), list_empty(), lfsck_layout::ll_flags, lfsck_namespace::ln_flags, lfsck_request::lr_event, lfsck_request::lr_flags, lfsck_reply::lr_repaired, lfsck_reply::lr_status, LS_SCANNING_PHASE1, LS_SCANNING_PHASE2, lfsck_tgt_desc::ltd_dead, lfsck_tgt_desc::ltd_index, lfsck_tgt_desc::ltd_layout_done, lfsck_tgt_desc::ltd_layout_list, lfsck_tgt_desc::ltd_layout_phase_list, lfsck_tgt_desc::ltd_layout_repaired, lfsck_tgt_desc::ltd_layout_status, lfsck_tgt_descs::ltd_lock, lfsck_tgt_desc::ltd_namespace_done, lfsck_tgt_desc::ltd_namespace_list, lfsck_tgt_desc::ltd_namespace_phase_list, lfsck_tgt_desc::ltd_namespace_repaired, lfsck_tgt_desc::ltd_namespace_status, req_capsule_server_get(), RMF_LFSCK_REPLY, and ptlrpc_request::rq_pill.
Referenced by lfsck_assistant_notify_others(), lfsck_assistant_query_others(), lfsck_interpret(), lfsck_query_all(), and lfsck_stop_notify().
int lfsck_async_request (const struct lu_env * env, struct obd_export * exp, struct lfsck_request * lr, struct ptlrpc_request_set * set, ptlrpc_interpterer_t interpterer, void * args, int request)
Definition at line 2369 of file lfsck_lib.c.
References CDEBUG, class_exp2cliimp(), D_LFSCK, obd_export::exp_obd, lfsck_async_interpret_args::laia_com, lfsck_component_get(), LFSCK_NOTIFY, LFSCK_QUERY, LUSTRE_OBD_VERSION, obd_device::obd_name, ptlrpc_req_async_args, ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), ptlrpc_set_add_req(), req_capsule_client_get(), RMF_LFSCK_REQUEST, ptlrpc_request::rq_allow_intr, ptlrpc_request::rq_pill, RQF_LFSCK_NOTIFY, and RQF_LFSCK_QUERY.
Referenced by lfsck_assistant_notify_others(), lfsck_assistant_query_others(), lfsck_layout_assistant_sync_failures(), lfsck_namespace_assistant_sync_failures(), lfsck_query_all(), lfsck_start_all(), lfsck_stop_all(), and lfsck_stop_notify().
void lfsck_bits_dump (struct seq_file * m, int bits, const char * names[], const char * prefix)
Definition at line 1741 of file lfsck_lib.c.
Referenced by lfsck_layout_dump(), and lfsck_namespace_dump().
void lfsck_bookmark_cpu_to_le (struct lfsck_bookmark * des, struct lfsck_bookmark * src)
Definition at line 54 of file lfsck_bookmark.c.
References cpu_to_le16, cpu_to_le32, fid_cpu_to_le(), lfsck_bookmark::lb_async_windows, lfsck_bookmark::lb_last_fid, lfsck_bookmark::lb_lpf_fid, lfsck_bookmark::lb_magic, lfsck_bookmark::lb_param, lfsck_bookmark::lb_speed_limit, and lfsck_bookmark::lb_version.
Referenced by lfsck_bookmark_store(), lfsck_create_lpf_local(), and lfsck_create_lpf_remote().
int lfsck_bookmark_setup (const struct lu_env * env, struct lfsck_instance * lfsck)
Definition at line 158 of file lfsck_bookmark.c.
References dt_locate(), dt_try_as_dir(), ENTRY, lfsck_bookmark::lb_async_windows, LFSCK_ASYNC_WIN_DEFAULT, LFSCK_BOOKMARK, lfsck_bookmark_init(), lfsck_bookmark_load(), lfsck_bookmark_store(), lfsck_object_put(), lfsck_instance::li_bookmark_obj, lfsck_instance::li_bookmark_ram, lfsck_instance::li_bottom, lfsck_instance::li_local_root_fid, lfsck_instance::li_los, lfsck_instance::li_mutex, local_file_find_or_create(), RETURN, and unlikely.
Referenced by lfsck_register().
int lfsck_bookmark_store (const struct lu_env * env, struct lfsck_instance * lfsck)
Definition at line 99 of file lfsck_bookmark.c.
References CDEBUG, D_LFSCK, dt_declare_record_write(), dt_record_write(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), ENTRY, GOTO, lfsck_bookmark_cpu_to_le(), lfsck_buf_get(), lfsck_lfsck2name(), lfsck_obj2dev(), lfsck_instance::li_bookmark_disk, lfsck_instance::li_bookmark_obj, and lfsck_instance::li_bookmark_ram.
Referenced by lfsck_bookmark_init(), lfsck_bookmark_setup(), lfsck_create_lpf(), lfsck_fid_alloc(), lfsck_set_param(), lfsck_set_speed(), lfsck_set_windows(), lfsck_start(), lfsck_update_lpf_entry(), lfsck_verify_lpf(), and lfsck_verify_lpf_pairs().
static struct lu_buf* lfsck_buf_get (const struct lu_env * env, void * area, ssize_t len) [static, read]
Definition at line 1112 of file lfsck_internal.h.
References buf, lu_buf::lb_buf, lu_buf::lb_len, lfsck_env_info(), and lfsck_thread_info::lti_buf.
Referenced by fid_is_for_ostobj(), lfsck_bookmark_load(), lfsck_bookmark_store(), lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_layout_get_def_stripesize(), lfsck_layout_lastid_create(), lfsck_layout_lastid_load(), lfsck_layout_lastid_reload(), lfsck_layout_lastid_store(), lfsck_layout_load(), lfsck_layout_load_bitmap(), lfsck_layout_repair_dangling(), lfsck_layout_repair_unmatched_pair(), lfsck_layout_store(), lfsck_namespace_load(), lfsck_namespace_load_bitmap(), lfsck_namespace_store(), lfsck_needs_scan_dir(), lfsck_orphan_it_next(), and lfsck_read_stripe_lmv().
static struct lu_buf* lfsck_buf_get_const (const struct lu_env * env, const void * area, ssize_t len) [static, read]
Definition at line 1123 of file lfsck_internal.h.
References buf, lu_buf::lb_buf, lu_buf::lb_len, lfsck_env_info(), and lfsck_thread_info::lti_buf.
Referenced by lfsck_declare_namespace_exec_dir(), and lfsck_links_write().
static void lfsck_buf_init (struct lu_buf * buf, void * area, ssize_t len) [inline, static]
Definition at line 1105 of file lfsck_internal.h.
References lu_buf::lb_buf, and lu_buf::lb_len.
Referenced by __lfsck_layout_update_pfid(), lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_layout_assistant_handler_p1(), lfsck_layout_master_exec_oit(), lfsck_layout_recreate_parent(), lfsck_layout_refill_lovea(), lfsck_layout_repair_multiple_references(), lfsck_layout_scan_stripes(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_insert_orphan(), lfsck_namespace_rebuild_linkea(), lfsck_namespace_repair_dangling(), lfsck_namespace_repair_unmatched_pairs(), lfsck_namespace_shrink_linkea(), lfsck_namespace_update_lmv(), and lfsck_verify_linkea().
int lfsck_checkpoint_generic (const struct lu_env * env, struct lfsck_component * com)
Definition at line 2531 of file lfsck_lib.c.
References l_wait_event, lfsck_assistant_data::lad_req_list, lfsck_assistant_data::lad_thread, lfsck_component::lc_data, lfsck_component::lc_lfsck, LFSCK_CHECKPOINT_SKIP, lfsck_instance::li_thread, list_empty(), ptlrpc_thread::t_ctl_waitq, thread_is_running(), and thread_is_stopped().
Referenced by lfsck_layout_master_checkpoint(), and lfsck_namespace_checkpoint().
void lfsck_close_dir (const struct lu_env * env, struct lfsck_instance * lfsck, int result)
Definition at line 297 of file lfsck_engine.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, ENTRY, EXIT, LASSERT, lfsck_component::lc_link_dir, lfsck_component::lc_ops, lfsck_operations::lfsck_close_dir, lfsck_di_dir_put(), lfsck_lmv_put(), lfsck_object_put(), lfsck_instance::li_di_dir, lfsck_instance::li_list_dir, lfsck_instance::li_lmv, lfsck_instance::li_obj_dir, list_for_each_entry, and lfsck_lmv::ll_exit_value.
Referenced by lfsck_exec_oit(), lfsck_master_engine(), lfsck_namespace_rescan_striped_dir(), lfsck_open_dir(), lfsck_post(), and lfsck_prep().
void lfsck_component_cleanup (const struct lu_env * env, struct lfsck_component * com)
Definition at line 318 of file lfsck_lib.c.
References lfsck_component::lc_link, lfsck_component::lc_link_dir, lfsck_component_put(), list_del_init(), and list_empty().
Referenced by lfsck_instance_cleanup(), lfsck_layout_setup(), and lfsck_namespace_setup().
struct lfsck_component* lfsck_component_find (struct lfsck_instance * lfsck, __u16 type) [read]
Definition at line 295 of file lfsck_lib.c.
References __lfsck_component_find(), lfsck_component_get(), lfsck_instance::li_list_double_scan, lfsck_instance::li_list_idle, lfsck_instance::li_list_scan, and lfsck_instance::li_lock.
Referenced by lfsck_dump(), lfsck_in_notify(), lfsck_orphan_it_init(), and lfsck_query().
static struct lfsck_component* lfsck_component_get (struct lfsck_component * com) [static, read]
Definition at line 1345 of file lfsck_internal.h.
References lfsck_component::lc_ref.
Referenced by lfsck_async_request(), lfsck_component_find(), lfsck_layout_async_query(), lfsck_stop_notify(), and lfsck_thread_args_init().
static void lfsck_component_put (const struct lu_env * env, struct lfsck_component * com) [inline, static]
Definition at line 1352 of file lfsck_internal.h.
References LASSERT, lfsck_component::lc_data, lfsck_component::lc_file_disk, lfsck_component::lc_file_ram, lfsck_component::lc_file_size, lfsck_component::lc_obj, lfsck_component::lc_ops, lfsck_component::lc_ref, lfsck_component::lc_sub_trace_objs, lfsck_operations::lfsck_data_release, lfsck_object_put(), LFSCK_STF_COUNT, lfsck_sub_trace_obj::lsto_obj, OBD_FREE, and OBD_FREE_PTR.
Referenced by lfsck_async_interpret_common(), lfsck_component_cleanup(), lfsck_dump(), lfsck_in_notify(), lfsck_layout_slave_async_interpret(), lfsck_orphan_it_fini(), lfsck_orphan_it_init(), lfsck_query(), lfsck_stop_notify(), and lfsck_thread_args_fini().
void lfsck_control_speed (struct lfsck_instance * lfsck)
Definition at line 1857 of file lfsck_lib.c.
References l_wait_event, lfsck_instance::li_new_scanned, lfsck_instance::li_sleep_jif, lfsck_instance::li_sleep_rate, lfsck_instance::li_thread, LWI_ON_SIGNAL_NOOP, LWI_TIMEOUT_INTR, ptlrpc_thread::t_ctl_waitq, thread, and thread_is_running().
Referenced by lfsck_master_dir_engine(), lfsck_master_oit_engine(), and lfsck_namespace_scan_shard().
void lfsck_control_speed_by_self (struct lfsck_component * com)
Definition at line 1874 of file lfsck_lib.c.
References l_wait_event, lfsck_component::lc_lfsck, lfsck_component::lc_new_scanned, lfsck_instance::li_sleep_jif, lfsck_instance::li_sleep_rate, lfsck_instance::li_thread, LWI_ON_SIGNAL_NOOP, LWI_TIMEOUT_INTR, ptlrpc_thread::t_ctl_waitq, thread, and thread_is_running().
Referenced by lfsck_layout_scan_orphan(), lfsck_namespace_double_scan_one_trace_file(), and lfsck_namespace_scan_local_lpf().
static u32 lfsck_dev_idx (struct lfsck_instance * lfsck) [inline, static]
Definition at line 1231 of file lfsck_internal.h.
References lfsck_dev_site(), and seq_server_site::ss_node_id.
Referenced by lfsck_assistant_notify_others(), lfsck_create_lpf(), lfsck_find_dev_by_fid(), lfsck_layout_lastid_load(), lfsck_layout_slave_exec_oit(), lfsck_layout_slave_notify_master(), lfsck_master_oit_engine(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_exec_oit(), lfsck_namespace_handle_striped_master(), lfsck_namespace_notify_lmv_remote(), lfsck_namespace_open_dir(), lfsck_namespace_repair_bad_name_hash(), lfsck_namespace_scan_local_lpf(), lfsck_needs_scan_dir(), lfsck_rbtree_setup(), lfsck_register(), lfsck_start_all(), lfsck_stop_all(), lfsck_stop_notify(), and lfsck_verify_lpf().
static struct seq_server_site* lfsck_dev_site (struct lfsck_instance * lfsck) [static, read]
Definition at line 1226 of file lfsck_internal.h.
References dt_device::dd_lu_dev, lu_device::ld_site, lfsck_instance::li_bottom, and lu_site2seq().
Referenced by fid_is_for_ostobj(), lfsck_dev_idx(), lfsck_fid_init(), lfsck_fid_match_idx(), lfsck_find_mdt_idx_by_fid(), lfsck_layout_slave_check_pairs(), lfsck_master_oit_engine(), lfsck_namespace_exec_oit(), lfsck_namespace_scan_local_lpf(), lfsck_namespace_set_lmv_master(), lfsck_namespace_striped_dir_rescan(), and lfsck_needs_scan_dir().
int lfsck_double_scan_generic (const struct lu_env * env, struct lfsck_component * com, int status)
Definition at line 2580 of file lfsck_lib.c.
References CDEBUG, D_LFSCK, l_wait_event, lfsck_assistant_data::lad_assistant_status, lfsck_assistant_data::lad_exit, lfsck_assistant_data::lad_in_double_scan, lfsck_assistant_data::lad_name, lfsck_assistant_data::lad_thread, lfsck_assistant_data::lad_to_double_scan, lfsck_component::lc_data, lfsck_component::lc_lfsck, lfsck_lfsck2name(), lfsck_instance::li_thread, LS_SCANNING_PHASE2, ptlrpc_thread::t_ctl_waitq, and thread_is_stopped().
Referenced by lfsck_layout_master_double_scan(), and lfsck_namespace_double_scan().
static struct lu_fid* lfsck_dto2fid (const struct dt_object * obj) [static, read]
Definition at line 1138 of file lfsck_internal.h.
References dt_object::do_lu, and lu_object_fid().
Referenced by lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_disable_master_lmv(), lfsck_ibits_lock(), lfsck_layout_conflict_create(), lfsck_layout_destroy_orphan(), lfsck_layout_extend_lovea(), lfsck_layout_lastid_create(), lfsck_layout_master_exec_oit(), lfsck_layout_recreate_lovea(), lfsck_layout_recreate_parent(), lfsck_layout_repair_dangling(), lfsck_layout_repair_multiple_references(), lfsck_layout_repair_owner(), lfsck_layout_repair_unmatched_pair(), lfsck_layout_scan_stripes(), lfsck_layout_slave_exec_oit(), lfsck_lock(), lfsck_lpf_remove_name_entry(), lfsck_master_dir_engine(), lfsck_namespace_check_exist(), lfsck_namespace_check_for_double_scan(), lfsck_namespace_check_name(), lfsck_namespace_close_dir(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_double_scan_dir(), lfsck_namespace_double_scan_one(), lfsck_namespace_dsd_multiple(), lfsck_namespace_dsd_single(), lfsck_namespace_dump(), lfsck_namespace_exec_oit(), lfsck_namespace_insert_normal(), lfsck_namespace_insert_orphan(), lfsck_namespace_links_remove(), lfsck_namespace_notify_lmv_remote(), lfsck_namespace_rebuild_linkea(), lfsck_namespace_repair_bad_name_hash(), lfsck_namespace_repair_dangling(), lfsck_namespace_repair_dirent(), lfsck_namespace_repair_nlink(), lfsck_namespace_repair_unmatched_pairs(), lfsck_namespace_replace_cond(), lfsck_namespace_rescan_striped_dir(), lfsck_namespace_set_lmv_master(), lfsck_namespace_shrink_linkea(), lfsck_namespace_shrink_linkea_cond(), lfsck_namespace_striped_dir_rescan(), lfsck_namespace_update_lmv(), lfsck_namespace_verify_stripe_slave(), lfsck_needs_scan_dir(), lfsck_pos_fill(), lfsck_record_lmv(), lfsck_update_lpf_entry(), lfsck_update_name_entry(), lfsck_verify_lpf(), and lfsck_verify_lpf_pairs().
static struct lfsck_thread_info* lfsck_env_info (const struct lu_env * env) [static, read]
Definition at line 1084 of file lfsck_internal.h.
References LASSERT, lu_env::le_ctx, lfsck_thread_key, and lu_context_key_get().
Referenced by __lfsck_ibits_lock(), __lfsck_layout_update_pfid(), fid_is_for_ostobj(), lfsck_allow_regenerate_master_lmv(), lfsck_assistant_engine(), lfsck_assistant_notify_others(), lfsck_assistant_query_others(), lfsck_buf_get(), lfsck_buf_get_const(), lfsck_create_lpf(), lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_disable_master_lmv(), lfsck_fid_match_idx(), lfsck_find_mdt_idx_by_fid(), lfsck_ibits_lock(), lfsck_in_notify(), lfsck_layout_assistant_handler_p1(), lfsck_layout_assistant_sync_failures(), lfsck_layout_check_parent(), lfsck_layout_conflict_create(), lfsck_layout_get_def_stripesize(), lfsck_layout_lastid_create(), lfsck_layout_lastid_load(), lfsck_layout_master_check_pairs(), lfsck_layout_master_conditional_destroy(), lfsck_layout_master_exec_oit(), lfsck_layout_master_in_notify(), lfsck_layout_recreate_lovea(), lfsck_layout_recreate_parent(), lfsck_layout_refill_lovea(), lfsck_layout_repair_dangling(), lfsck_layout_repair_multiple_references(), lfsck_layout_repair_owner(), lfsck_layout_repair_unmatched_pair(), lfsck_layout_scan_orphan(), lfsck_layout_scan_stripes(), lfsck_layout_slave_check_pairs(), lfsck_layout_slave_conditional_destroy(), lfsck_layout_slave_in_notify(), lfsck_layout_slave_notify_master(), lfsck_layout_slave_query_master(), lfsck_links_get_first(), lfsck_links_read(), lfsck_links_read2(), lfsck_load_stripe_lmv(), lfsck_lock(), lfsck_lpf_remove_name_entry(), lfsck_master_dir_engine(), lfsck_master_oit_engine(), lfsck_name_get_const(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_assistant_sync_failures(), lfsck_namespace_check_exist(), lfsck_namespace_check_for_double_scan(), lfsck_namespace_check_name(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_double_scan_dir(), lfsck_namespace_double_scan_one(), lfsck_namespace_dsd_multiple(), lfsck_namespace_dsd_orphan(), lfsck_namespace_dsd_single(), lfsck_namespace_exec_oit(), lfsck_namespace_handle_striped_master(), lfsck_namespace_in_notify(), lfsck_namespace_insert_normal(), lfsck_namespace_insert_orphan(), lfsck_namespace_load_sub_trace_files(), lfsck_namespace_notify_lmv_master_local(), lfsck_namespace_notify_lmv_remote(), lfsck_namespace_repair_bad_name_hash(), lfsck_namespace_repair_dangling(), lfsck_namespace_repair_dirent(), lfsck_namespace_repair_nlink(), lfsck_namespace_repair_unmatched_pairs(), lfsck_namespace_replace_cond(), lfsck_namespace_rescan_striped_dir(), lfsck_namespace_scan_local_lpf(), lfsck_namespace_scan_local_lpf_one(), lfsck_namespace_scan_shard(), lfsck_namespace_set_lmv_master(), lfsck_namespace_shrink_linkea_cond(), lfsck_namespace_striped_dir_rescan(), lfsck_namespace_trace_update(), lfsck_namespace_update_lmv(), lfsck_namespace_verify_stripe_slave(), lfsck_needs_scan_dir(), lfsck_object_find_by_dev_nowait(), lfsck_orphan_it_next(), lfsck_query_all(), lfsck_rbtree_setup(), lfsck_register(), lfsck_remove_dirent(), lfsck_scan_lpf_bad_entries(), lfsck_shard_name_to_index(), lfsck_start_all(), lfsck_stop_all(), lfsck_stop_notify(), lfsck_update_name_entry(), lfsck_verify_linkea(), lfsck_verify_lpf(), and lfsck_verify_lpf_pairs().
int lfsck_fid_alloc (const struct lu_env * env, struct lfsck_instance * lfsck, struct lu_fid * fid, bool locked)
Definition at line 329 of file lfsck_lib.c.
References ENTRY, lfsck_bookmark::lb_last_fid, lfsck_bookmark_store(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_mutex, lfsck_instance::li_seq, RETURN, and seq_client_alloc_fid().
Referenced by lfsck_create_lpf(), and lfsck_layout_recreate_parent().
static struct dt_device* lfsck_find_dev_by_fid (const struct lu_env * env, struct lfsck_instance * lfsck, const struct lu_fid * fid) [static, read]
Definition at line 1254 of file lfsck_internal.h.
References lfsck_dev_idx(), lfsck_find_mdt_idx_by_fid(), lfsck_ltd2tgt(), lfsck_instance::li_bottom, lfsck_instance::li_master, lfsck_instance::li_mdt_descs, lfsck_tgt_desc::ltd_tgt, and unlikely.
Referenced by lfsck_namespace_create_orphan_dir(), lfsck_object_find_bottom(), and lfsck_object_find_bottom_nowait().
int lfsck_find_mdt_idx_by_fid (const struct lu_env * env, struct lfsck_instance * lfsck, const struct lu_fid * fid)
Definition at line 526 of file lfsck_lib.c.
References fld_range_set_mdt(), fld_server_lookup(), lfsck_dev_site(), lfsck_env_info(), lu_seq_range::lsr_index, lfsck_thread_info::lti_range, and seq_server_site::ss_server_fld.
Referenced by lfsck_find_dev_by_fid(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_create_orphan_dir(), and lfsck_namespace_handle_striped_master().
int lfsck_ibits_lock (const struct lu_env * env, struct lfsck_instance * lfsck, struct dt_object * obj, struct lustre_handle * lh, __u64 bits, enum ldlm_mode mode)
Request the specified ibits lock for the given object.
Before the LFSCK modifying on the namespace visible object, it needs to acquire related ibits ldlm lock.
Parameters:
[in] env pointer to the thread context
[in] lfsck pointer to the lfsck instance
[in] obj pointer to the dt_object to be locked
[out] lh pointer to the lock handle
[in] bits the bits for the ldlm lock to be acquired
[in] mode the mode for the ldlm lock to be acquired
Return values:
0 for success
negative error number on failure
Definition at line 415 of file lfsck_lib.c.
References __lfsck_ibits_lock(), fid_build_reg_res_name(), LASSERT, lfsck_dto2fid(), lfsck_env_info(), lfsck_thread_info::lti_resid, and lustre_handle_is_used().
Referenced by lfsck_layout_check_parent(), lfsck_layout_conflict_create(), lfsck_layout_master_exec_oit(), lfsck_layout_recreate_lovea(), lfsck_layout_repair_dangling(), lfsck_layout_repair_multiple_references(), lfsck_layout_repair_unmatched_pair(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_double_scan_dir(), lfsck_namespace_exec_oit(), lfsck_namespace_insert_orphan(), lfsck_namespace_repair_dirent(), lfsck_namespace_repair_nlink(), lfsck_namespace_replace_cond(), lfsck_namespace_set_lmv_master(), lfsck_namespace_shrink_linkea(), lfsck_namespace_striped_dir_rescan(), lfsck_namespace_update_lmv(), lfsck_remove_lmv(), and lfsck_verify_lpf_pairs().
void lfsck_ibits_unlock (struct lustre_handle * lh, enum ldlm_mode mode)
Release the the specified ibits lock.
If the lock has been acquired before, release it and cleanup the handle. Otherwise, do nothing.
Parameters:
[in] lh pointer to the lock handle
[in] mode the mode for the ldlm lock to be released
Definition at line 436 of file lfsck_lib.c.
References ldlm_lock_decref(), and lustre_handle_is_used().
Referenced by lfsck_layout_check_parent(), lfsck_layout_conflict_create(), lfsck_layout_master_exec_oit(), lfsck_layout_recreate_lovea(), lfsck_layout_repair_dangling(), lfsck_layout_repair_multiple_references(), lfsck_layout_repair_unmatched_pair(), lfsck_lock(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_double_scan_dir(), lfsck_namespace_dsd_multiple(), lfsck_namespace_dsd_orphan(), lfsck_namespace_dsd_single(), lfsck_namespace_exec_oit(), lfsck_namespace_insert_orphan(), lfsck_namespace_repair_dirent(), lfsck_namespace_repair_nlink(), lfsck_namespace_replace_cond(), lfsck_namespace_set_lmv_master(), lfsck_namespace_shrink_linkea(), lfsck_namespace_striped_dir_rescan(), lfsck_namespace_update_lmv(), lfsck_remove_lmv(), lfsck_unlock(), and lfsck_verify_lpf_pairs().
void lfsck_instance_cleanup (const struct lu_env * env, struct lfsck_instance * lfsck)
Definition at line 1613 of file lfsck_lib.c.
References ENTRY, LASSERT, LASSERTF, lfsck_component_cleanup(), lfsck_fid_fini(), lfsck_lmv_put(), lfsck_object_put(), lfsck_tgt_descs_fini(), lfsck_instance::li_bookmark_obj, lfsck_instance::li_lfsck_dir, lfsck_instance::li_link, lfsck_instance::li_list_dir, lfsck_instance::li_list_double_scan, lfsck_instance::li_list_idle, lfsck_instance::li_list_lmv, lfsck_instance::li_list_scan, lfsck_instance::li_lmv, lfsck_instance::li_los, lfsck_instance::li_lpf_obj, lfsck_instance::li_lpf_root_obj, lfsck_instance::li_mdt_descs, lfsck_instance::li_obj_dir, lfsck_instance::li_obj_oit, lfsck_instance::li_ost_descs, lfsck_instance::li_thread, list_empty(), list_for_each_entry_safe, lfsck_lmv::ll_ref, lfsck_lmv_unit::llu_lmv, local_oid_storage_fini(), OBD_FREE_PTR, thread, thread_is_init(), and thread_is_stopped().
Referenced by lfsck_instance_put(), and lfsck_register().
struct lfsck_instance* lfsck_instance_find (struct dt_device * key, bool ref, bool unlink) [read]
Definition at line 1712 of file lfsck_lib.c.
References __lfsck_instance_find().
Referenced by lfsck_degister(), lfsck_dump(), lfsck_get_speed(), lfsck_get_windows(), lfsck_in_notify(), lfsck_orphan_it_init(), lfsck_query(), lfsck_register(), lfsck_register_namespace(), lfsck_set_speed(), lfsck_set_windows(), lfsck_start(), and lfsck_stop().
static struct lfsck_instance* lfsck_instance_get (struct lfsck_instance * lfsck) [static, read]
Definition at line 1382 of file lfsck_internal.h.
References lfsck_instance::li_ref.
Referenced by __lfsck_instance_find(), and lfsck_thread_args_init().
static void lfsck_instance_put (const struct lu_env * env, struct lfsck_instance * lfsck) [inline, static]
Definition at line 1389 of file lfsck_internal.h.
References lfsck_instance_cleanup(), and lfsck_instance::li_ref.
Referenced by lfsck_add_target(), lfsck_degister(), lfsck_del_target(), lfsck_dump(), lfsck_get_speed(), lfsck_get_windows(), lfsck_in_notify(), lfsck_orphan_it_init(), lfsck_query(), lfsck_register_namespace(), lfsck_set_speed(), lfsck_set_windows(), lfsck_start(), lfsck_stop(), and lfsck_thread_args_fini().
static int lfsck_is_dead_obj (const struct dt_object * obj) [inline, static]
Definition at line 1206 of file lfsck_internal.h.
References dt_object::do_lu, lu_object::lo_header, lu_object_header::loh_flags, and LU_OBJECT_HEARD_BANSHEE.
Referenced by lfsck_assistant_object_load(), lfsck_disable_master_lmv(), lfsck_layout_check_parent(), lfsck_layout_master_check_pairs(), lfsck_layout_master_exec_oit(), lfsck_layout_repair_dangling(), lfsck_layout_repair_multiple_references(), lfsck_layout_repair_owner(), lfsck_layout_repair_unmatched_pair(), lfsck_layout_scan_stripes(), lfsck_layout_slave_conditional_destroy(), lfsck_layout_slave_repair_pfid(), lfsck_namespace_check_exist(), lfsck_namespace_double_scan_dir(), lfsck_namespace_double_scan_one(), lfsck_namespace_exec_dir(), lfsck_namespace_handle_striped_master(), lfsck_namespace_links_remove(), lfsck_namespace_rebuild_linkea(), lfsck_namespace_repair_unmatched_pairs(), lfsck_namespace_replace_cond(), lfsck_namespace_shrink_linkea(), lfsck_namespace_shrink_linkea_cond(), lfsck_namespace_striped_dir_rescan(), lfsck_namespace_update_lmv(), lfsck_needs_scan_dir(), and lfsck_orphan_it_next().
bool lfsck_is_valid_slave_name_entry (const struct lu_env * env, struct lfsck_lmv * llmv, const char * name, int namelen)
Definition at line 910 of file lfsck_striped_dir.c.
References lfsck_lmv::ll_lmv, lfsck_lmv::ll_lmv_slave, lfsck_lmv::ll_lmv_verified, lmv_mds_md_v1::lmv_hash_type, lmv_mds_md_v1::lmv_master_mdt_index, lmv_name_to_stripe_index(), lmv_mds_md_v1::lmv_stripe_count, and unlikely.
Referenced by lfsck_namespace_assistant_handler_p1(), and lfsck_namespace_scan_shard().
static void lfsck_lad_set_bitmap (const struct lu_env * env, struct lfsck_component * com, __u32 index) [inline, static]
Definition at line 1403 of file lfsck_internal.h.
References cfs_bitmap_set(), lfsck_assistant_data::lad_bitmap, lfsck_assistant_data::lad_incomplete, LASSERT, lfsck_component::lc_data, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_type, LF_INCOMPLETE, LFSCK_TYPE_NAMESPACE, lfsck_instance::li_master, likely, lfsck_namespace::ln_flags, and cfs_bitmap::size.
Referenced by lfsck_assistant_notify_others(), lfsck_async_interpret_common(), lfsck_layout_assistant_handler_p1(), lfsck_layout_master_in_notify(), lfsck_layout_scan_orphan(), lfsck_layout_scan_stripes(), lfsck_namespace_assistant_handler_p1(), and lfsck_namespace_handle_striped_master().
int lfsck_layout_setup (const struct lu_env * env, struct lfsck_instance * lfsck)
Definition at line 5556 of file lfsck_layout.c.
References CERROR, dt_locate(), dt_try_as_dir(), ENTRY, GOTO, INIT_LIST_HEAD, LASSERT, lfsck_component::lc_data, lfsck_component::lc_file_disk, lfsck_component::lc_file_ram, lfsck_component::lc_file_size, lfsck_component::lc_lfsck, lfsck_component::lc_link, lfsck_component::lc_link_dir, lfsck_component::lc_obj, lfsck_component::lc_ops, lfsck_component::lc_ref, lfsck_component::lc_sem, lfsck_component::lc_type, LE_LASTID_REBUILDING, LF_CRASHED_LASTID, LF_INCOMPLETE, lfsck_assistant_data_init(), lfsck_component_cleanup(), LFSCK_LAYOUT, lfsck_layout_init(), lfsck_layout_load(), lfsck_layout_reset(), lfsck_lfsck2name(), lfsck_object_put(), LFSCK_TYPE_LAYOUT, lfsck_instance::li_bottom, lfsck_instance::li_list_idle, lfsck_instance::li_list_scan, lfsck_instance::li_local_root_fid, lfsck_instance::li_lock, lfsck_instance::li_los, lfsck_instance::li_master, lfsck_instance::li_out_notify, lfsck_instance::li_out_notify_data, list_add_tail(), lfsck_layout::ll_flags, lfsck_layout::ll_status, lfsck_layout_slave_data::llsd_lock, lfsck_layout_slave_data::llsd_master_list, lfsck_layout_slave_data::llsd_rb_lock, lfsck_layout_slave_data::llsd_rb_root, lfsck_layout_slave_data::llsd_seq_list, local_file_find_or_create(), LS_CO_FAILED, LS_CO_PAUSED, LS_CO_STOPPED, LS_COMPLETED, LS_CRASHED, LS_FAILED, LS_INIT, LS_PARTIAL, LS_PAUSED, LS_SCANNING_PHASE1, LS_SCANNING_PHASE2, LS_STOPPED, OBD_ALLOC, OBD_ALLOC_PTR, RETURN, and unlikely.
Referenced by lfsck_register().
static char* lfsck_lfsck2name (struct lfsck_instance * lfsck) [inline, static]
Definition at line 1133 of file lfsck_internal.h.
References dt_device::dd_lu_dev, lu_device::ld_obd, lfsck_instance::li_bottom, and obd_device::obd_name.
Referenced by __lfsck_add_target(), lfsck_assistant_engine(), lfsck_assistant_notify_others(), lfsck_assistant_query_others(), lfsck_async_interpret_common(), lfsck_bookmark_load(), lfsck_bookmark_store(), lfsck_create_lpf_remote(), lfsck_disable_master_lmv(), lfsck_double_scan_generic(), lfsck_fid_init(), lfsck_layout_assistant_handler_p1(), lfsck_layout_assistant_handler_p2(), lfsck_layout_assistant_sync_failures(), lfsck_layout_check_parent(), lfsck_layout_conflict_create(), lfsck_layout_extend_lovea(), lfsck_layout_lastid_create(), lfsck_layout_lastid_load(), lfsck_layout_lastid_reload(), lfsck_layout_lastid_store(), lfsck_layout_load(), lfsck_layout_master_checkpoint(), lfsck_layout_master_exec_oit(), lfsck_layout_master_in_notify(), lfsck_layout_master_post(), lfsck_layout_master_prep(), lfsck_layout_prep(), lfsck_layout_record_failure(), lfsck_layout_recreate_lovea(), lfsck_layout_recreate_parent(), lfsck_layout_repair_dangling(), lfsck_layout_repair_multiple_references(), lfsck_layout_repair_owner(), lfsck_layout_repair_unmatched_pair(), lfsck_layout_reset(), lfsck_layout_scan_orphan(), lfsck_layout_scan_stripes(), lfsck_layout_setup(), lfsck_layout_slave_async_interpret(), lfsck_layout_slave_checkpoint(), lfsck_layout_slave_conditional_destroy(), lfsck_layout_slave_double_scan(), lfsck_layout_slave_exec_oit(), lfsck_layout_slave_in_notify(), lfsck_layout_slave_notify_master(), lfsck_layout_slave_post(), lfsck_layout_slave_prep(), lfsck_layout_slave_query_master(), lfsck_layout_slave_repair_pfid(), lfsck_layout_store(), lfsck_lock(), lfsck_lpf_remove_name_entry(), lfsck_master_dir_engine(), lfsck_master_engine(), lfsck_master_oit_engine(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_assistant_handler_p2(), lfsck_namespace_assistant_sync_failures(), lfsck_namespace_checkpoint(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_double_scan_dir(), lfsck_namespace_handle_striped_master(), lfsck_namespace_in_notify(), lfsck_namespace_insert_normal(), lfsck_namespace_insert_orphan(), lfsck_namespace_links_remove(), lfsck_namespace_load(), lfsck_namespace_notify_lmv_remote(), lfsck_namespace_post(), lfsck_namespace_prep(), lfsck_namespace_rebuild_linkea(), lfsck_namespace_record_failure(), lfsck_namespace_repair_bad_name_hash(), lfsck_namespace_repair_dangling(), lfsck_namespace_repair_dirent(), lfsck_namespace_repair_nlink(), lfsck_namespace_repair_unmatched_pairs(), lfsck_namespace_replace_cond(), lfsck_namespace_reset(), lfsck_namespace_scan_local_lpf(), lfsck_namespace_set_lmv_master(), lfsck_namespace_setup(), lfsck_namespace_shrink_linkea(), lfsck_namespace_store(), lfsck_namespace_striped_dir_rescan(), lfsck_namespace_trace_update(), lfsck_namespace_update_lmv(), lfsck_orphan_it_fini(), lfsck_orphan_it_init(), lfsck_orphan_it_load(), lfsck_orphan_it_next(), lfsck_post(), lfsck_post_generic(), lfsck_query_all(), lfsck_rbtree_cleanup(), lfsck_rbtree_setup(), lfsck_rbtree_update_bitmap(), lfsck_record_lmv(), lfsck_set_windows(), lfsck_start(), lfsck_start_all(), lfsck_start_assistant(), lfsck_stop(), lfsck_stop_all(), lfsck_stop_notify(), lfsck_update_lpf_entry(), lfsck_update_name_entry(), lfsck_verify_lpf(), and lfsck_verify_lpf_pairs().
int lfsck_links_get_first (const struct lu_env * env, struct dt_object * obj, char * name, struct lu_fid * pfid)
Get the name and parent directory's FID from the first linkEA entry.
Parameters:
[in] env pointer to the thread context
[in] obj pointer to the object which get linkEA from
[out] name pointer to the buffer to hold the name in the first linkEA entry
[out] pfid pointer to the buffer to hold the parent directory's FID in the first linkEA entry
Return values:
0 for success
negative error number on failure
Definition at line 6404 of file lfsck_namespace.c.
References linkea_data::ld_lee, linkea_data::ld_reclen, lfsck_env_info(), lfsck_links_read(), linkea_entry_unpack(), linkea_first_entry(), lu_name::ln_name, lu_name::ln_namelen, and lfsck_thread_info::lti_name.
Referenced by lfsck_namespace_verify_stripe_slave(), and lfsck_verify_lpf_pairs().
static int lfsck_links_read (const struct lu_env * env, struct dt_object * obj, struct linkea_data * ldata) [inline, static]
Definition at line 1423 of file lfsck_internal.h.
References __lfsck_links_read(), linkea_data::ld_buf, lfsck_env_info(), and lu_buf_check_and_alloc().
Referenced by lfsck_links_get_first(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_double_scan_dir(), lfsck_namespace_double_scan_one(), lfsck_namespace_exec_oit(), lfsck_namespace_insert_orphan(), lfsck_namespace_striped_dir_rescan(), and lfsck_verify_linkea().
static int lfsck_links_read2 (const struct lu_env * env, struct dt_object * obj, struct linkea_data * ldata) [inline, static]
Definition at line 1434 of file lfsck_internal.h.
References __lfsck_links_read(), linkea_data::ld_buf, lfsck_env_info(), and lu_buf_check_and_alloc().
Referenced by lfsck_namespace_repair_nlink(), lfsck_namespace_replace_cond(), and lfsck_namespace_shrink_linkea().
static struct lfsck_lmv* lfsck_lmv_get (struct lfsck_lmv * llmv) [static, read]
Definition at line 1445 of file lfsck_internal.h.
References lfsck_lmv::ll_ref.
Referenced by lfsck_namespace_assistant_req_init(), and lfsck_namespace_close_dir().
static void lfsck_lmv_header_cpu_to_le (struct lmv_mds_md_v1 * dst, const struct lmv_mds_md_v1 * src) [inline, static]
Definition at line 1468 of file lfsck_internal.h.
References cpu_to_le32, lmv_mds_md_v1::lmv_hash_type, lmv_mds_md_v1::lmv_layout_version, lmv_mds_md_v1::lmv_magic, lmv_mds_md_v1::lmv_master_mdt_index, and lmv_mds_md_v1::lmv_stripe_count.
Referenced by lfsck_namespace_create_orphan_dir(), lfsck_namespace_repair_dangling(), and lfsck_namespace_update_lmv().
static void lfsck_lmv_header_le_to_cpu (struct lmv_mds_md_v1 * dst, const struct lmv_mds_md_v1 * src) [inline, static]
Definition at line 1458 of file lfsck_internal.h.
References le32_to_cpu, lmv_mds_md_v1::lmv_hash_type, lmv_mds_md_v1::lmv_layout_version, lmv_mds_md_v1::lmv_magic, lmv_mds_md_v1::lmv_master_mdt_index, and lmv_mds_md_v1::lmv_stripe_count.
Referenced by lfsck_read_stripe_lmv().
void lfsck_lmv_put (const struct lu_env * env, struct lfsck_lmv * llmv)
Definition at line 155 of file lfsck_striped_dir.c.
References LASSERT, lfsck_object_put(), lfsck_instance::li_lock, list_del(), list_entry, lfsck_lmv::ll_inline, lfsck_lmv::ll_lslr, lfsck_lmv::ll_ref, lfsck_lmv::ll_stripes_allocated, lfsck_lmv_unit::llu_lfsck, lfsck_lmv_unit::llu_link, lfsck_lmv_unit::llu_obj, OBD_FREE_LARGE, and OBD_FREE_PTR.
Referenced by lfsck_close_dir(), lfsck_instance_cleanup(), lfsck_namespace_assistant_req_fini(), lfsck_namespace_notify_lmv_master_local(), lfsck_namespace_release_lmv(), and lfsck_namespace_scan_shard().
int lfsck_lock (const struct lu_env * env, struct lfsck_instance * lfsck, struct dt_object * obj, const char * name, struct lfsck_lock_handle * llh, __u64 bits, enum ldlm_mode mode)
Request compound ibits locks for the given <obj, name> pairs.
Before the LFSCK modifying on the namespace visible object, it needs to acquire related ibits ldlm lock. Usually, we can use lfsck_ibits_lock for the lock purpose. But the simple lfsck_ibits_lock for directory-based modificationis (such as insert name entry to the directory) may be too coarse-grained and not efficient.
The lfsck_lock() will request compound ibits locks on the specified <obj, name> pairs: the PDO (Parallel Directory Operations) ibits (UPDATE) lock on the directory object, and the regular ibits lock on the name hash.
Parameters:
[in] env pointer to the thread context
[in] lfsck pointer to the lfsck instance
[in] obj pointer to the dt_object to be locked
[in] name used for building the PDO lock resource
[out] llh pointer to the lfsck_lock_handle
[in] bits the bits for the ldlm lock to be acquired
[in] mode the mode for the ldlm lock to be acquired
Return values:
0 for success
negative error number on failure
Definition at line 468 of file lfsck_lib.c.
References __lfsck_ibits_lock(), CDEBUG, D_LFSCK, DFID, fid_build_reg_res_name(), LASSERT, LBUG, LCK_CR, LCK_CW, LCK_EX, LCK_PR, LCK_PW, lfsck_dto2fid(), lfsck_env_info(), lfsck_ibits_unlock(), lfsck_lfsck2name(), lfsck_object_type(), lfsck_lock_handle::llh_pdo_lh, lfsck_lock_handle::llh_pdo_mode, lfsck_lock_handle::llh_reg_lh, lfsck_lock_handle::llh_reg_mode, lfsck_thread_info::lti_resid, lustre_handle_is_used(), LUSTRE_RES_ID_HSH_OFF, MDS_INODELOCK_UPDATE, ldlm_res_id::name, and PFID.
Referenced by lfsck_create_lpf(), lfsck_layout_recreate_parent(), lfsck_lpf_remove_name_entry(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_insert_normal(), lfsck_namespace_insert_orphan(), lfsck_namespace_repair_dangling(), lfsck_namespace_repair_dirent(), lfsck_namespace_replace_cond(), lfsck_namespace_shrink_linkea_cond(), and lfsck_update_name_entry().
static struct lfsck_tgt_desc* lfsck_ltd2tgt (struct lfsck_tgt_descs * ltd, __u32 index) [static, read]
Definition at line 494 of file lfsck_internal.h.
References CDEBUG, D_LFSCK, lfsck_tgt_desc_idx::ldi_tgts, likely, lfsck_tgt_descs::ltd_tgts_idx, TGT_PTRS, TGT_PTRS_PER_BLOCK, and unlikely.
Referenced by lfsck_assistant_notify_others(), lfsck_del_target(), lfsck_find_dev_by_fid(), lfsck_layout_assistant_sync_failures(), lfsck_layout_master_in_notify(), lfsck_layout_query_all(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_assistant_sync_failures(), lfsck_namespace_handle_striped_master(), lfsck_namespace_in_notify(), lfsck_namespace_query_all(), lfsck_start(), lfsck_tgt_descs_fini(), and lfsck_tgt_get().
int lfsck_master_engine (void * args)
Definition at line 996 of file lfsck_engine.c.
References CDEBUG, current_pid, D_LFSCK, DFID, dt_index_operations::dio_it, dt_object::do_index_ops, ENTRY, GOTO, l_wait_event, lfsck_close_dir(), lfsck_di_oit_put(), lfsck_double_scan(), lfsck_lfsck2name(), lfsck_master_oit_engine(), lfsck_pos_fill(), lfsck_post(), lfsck_prep(), lfsck_quit(), lfsck_thread_args_fini(), lfsck_verify_lpf(), lfsck_instance::li_args_dir, lfsck_instance::li_args_oit, lfsck_instance::li_di_oit, lfsck_instance::li_list_double_scan, lfsck_instance::li_list_scan, lfsck_instance::li_lock, lfsck_instance::li_master, lfsck_instance::li_obj_oit, lfsck_instance::li_pos_checkpoint, lfsck_instance::li_start_unplug, lfsck_instance::li_thread, list_empty(), lfsck_position::lp_dir_cookie, lfsck_position::lp_dir_parent, lfsck_position::lp_oit_cookie, LPU64, LPX64, lfsck_thread_args::lta_env, lfsck_thread_args::lta_lfsck, lfsck_thread_args::lta_lsp, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_CRASH, PFID, SVC_RUNNING, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, thread, thread_is_running(), and thread_set_flags().
Referenced by lfsck_start().
static struct lu_name* lfsck_name_get_const (const struct lu_env * env, const void * area, ssize_t len) [static, read]
Definition at line 1094 of file lfsck_internal.h.
References lfsck_env_info(), lu_name::ln_name, lu_name::ln_namelen, and lfsck_thread_info::lti_name_const.
Referenced by lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_layout_recreate_parent(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_repair_dangling(), lfsck_namespace_striped_dir_rescan(), lfsck_register(), lfsck_verify_lpf(), and lfsck_verify_lpf_pairs().
int lfsck_namespace_check_exist (const struct lu_env * env, struct dt_object * dir, struct dt_object * obj, const char * name)
Definition at line 628 of file lfsck_namespace.c.
References dt_key, dt_lookup(), ENTRY, lfsck_dto2fid(), lfsck_env_info(), lfsck_is_dead_obj(), LFSCK_NAMEENTRY_DEAD, LFSCK_NAMEENTRY_RECREATED, LFSCK_NAMEENTRY_REMOVED, lfsck_thread_info::lti_fid, lu_fid_eq(), RETURN, and unlikely.
Referenced by lfsck_namespace_assistant_handler_p1(), lfsck_namespace_handle_striped_master(), and lfsck_namespace_repair_dangling().
int lfsck_namespace_check_name (const struct lu_env * env, struct dt_object * parent, struct dt_object * child, const struct lu_name * cname)
Check whether the given name is a valid entry under the .
If the is a striped directory then the should one shard of the striped directory, its name should be $FID:$index.
If the is a shard of a striped directory, then the name hash should match the MDT, otherwise it is invalid.
Parameters:
[in] env pointer to the thread context
[in] parent the parent directory
[in] child the child object to be checked
[in] cname the name for the in the parent directory
Return values:
positive number for invalid name entry
0 if the name is valid or uncertain
negative error number on failure
Definition at line 948 of file lfsck_striped_dir.c.
References lfsck_dto2fid(), lfsck_env_info(), lfsck_is_valid_slave_lmv(), lfsck_object_type(), lfsck_read_stripe_lmv(), lfsck_shard_name_to_index(), lmv_mds_md_v1::lmv_hash_type, lmv_mds_md_v1::lmv_magic, LMV_MAGIC_STRIPE, lmv_mds_md_v1::lmv_master_mdt_index, lmv_name_to_stripe_index(), lmv_mds_md_v1::lmv_stripe_count, lu_name::ln_name, lu_name::ln_namelen, lfsck_thread_info::lti_lmv, RETURN, and unlikely.
Referenced by lfsck_namespace_double_scan_one(), and lfsck_namespace_dsd_single().
int lfsck_namespace_handle_striped_master (const struct lu_env * env, struct lfsck_component * com, struct lfsck_namespace_req * lnr)
Verify the shard's name entry under the striped directory.
Before all shards of the striped directory scanned, the LFSCK cannot know whether the master LMV EA is valid or not, and also cannot know how to repair an invalid shard exactly. For example, the stripe index stored in the shard's name does not match the stripe index stored in the slave LMV EA, then the LFSCK cannot know which one is correct. If the LFSCK just assumed one is correct, and fixed the other, then as the LFSCK processing, it may find that the former reparation is wrong and have to roll back. Unfortunately, if some applications saw the changes and made further modification based on such changes, then the roll back is almost impossible.
To avoid above trouble, the LFSCK will scan the master object of the striped directory twice, that is NOT the same as normal two-stages scanning, the double scanning the striped directory will happen both during the first-stage scanning:
1) When the striped directory is opened for scanning, the LFSCK will iterate each shard in turn, and records its slave LMV EA in the lfsck_lmv::ll_lslr. In this step, if the 'shard' (may be fake shard) name does not match the shard naming rule, for example, it does not contains the shard's FID, or not contains index, then we can remove the bad name entry directly. But if the name is valid, but the shard has no slave LMV EA or the slave LMV EA does not match its name, then we just record related information in the lfsck_lmv::ll_lslr in RAM.
2) When all the known shards have been scanned, then the engine will generate a dummy request (via lfsck_namespace_close_dir) to tell the assistant thread that all the known shards have been scanned. Since the assistant has got the global knowledge about the index conflict, stripe count, hash type, and so on. Then the assistant thread will scan the lfsck_lmv::ll_lslr, and for every shard in the record, check and repair inconsistency.
Generally, the stripe directory has only several shards, and there will NOT be a lof of striped directory. So double scanning striped directory will not much affect the LFSCK performance.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] lnr pointer to the namespace request that contains the shard's name, parent object, parent's LMV, and ect.
Return values:
zero for success
negative error number on failure
Definition at line 2248 of file lfsck_striped_dir.c.
References CDEBUG, D_LFSCK, DFID, dir, dotdot, dt_object_exists(), ENTRY, GOTO, lfsck_assistant_req::lar_parent, lfsck_bookmark::lb_param, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_assistant_object_load(), lfsck_dev_idx(), lfsck_env_info(), lfsck_find_mdt_idx_by_fid(), lfsck_is_dead_obj(), lfsck_lad_set_bitmap(), lfsck_lfsck2name(), lfsck_ltd2tgt(), lfsck_namespace_check_exist(), lfsck_namespace_repair_dirent(), lfsck_namespace_trace_update(), lfsck_object_find_by_dev_nowait(), lfsck_object_put(), lfsck_object_type(), lfsck_read_stripe_lmv(), lfsck_record_lmv(), lfsck_shard_name_to_index(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_bottom, lfsck_instance::li_mdt_descs, lfsck_lmv::ll_failed, lfsck_lmv::ll_ignore, LMV_MAGIC, lmv_mds_md_v1::lmv_magic, lmv_mds_md_v1::lmv_master_mdt_index, lfsck_namespace::ln_bad_type_repaired, lfsck_namespace::ln_dirent_repaired, lfsck_namespace::ln_items_repaired, LNIT_BAD_DIRENT, LNIT_BAD_TYPE, LNIT_NONE, lfsck_namespace_req::lnr_fid, lfsck_namespace_req::lnr_lar, lfsck_namespace_req::lnr_lmv, lfsck_namespace_req::lnr_name, lfsck_namespace_req::lnr_namelen, lfsck_namespace_req::lnr_type, LNTF_CHECK_PARENT, LPF_FAILOUT, LSLF_BAD_INDEX1, LSLF_DANGLING, LSLF_NO_LMVEA, LSLF_NONE, lfsck_assistant_object::lso_fid, lfsck_tgt_desc::ltd_tgt, lfsck_thread_info::lti_lmv, PFID, RETURN, and unlikely.
Referenced by lfsck_namespace_assistant_handler_p1().
int lfsck_namespace_notify_lmv_master_local (const struct lu_env * env, struct lfsck_component * com, struct dt_object * obj)
Generate request for local LFSCK instance to rescan the striped directory.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] obj pointer to the striped directory to be rescanned
Return values:
positive number if nothing to be done
zero for success
negative error number on failure
Definition at line 1264 of file lfsck_striped_dir.c.
References ENTRY, INIT_LIST_HEAD, lfsck_bookmark::lb_param, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_sem, lfsck_env_info(), LFSCK_LMV_DEF_STRIPES, LFSCK_LMV_MAX_STRIPES, lfsck_lmv_put(), lfsck_object_get(), lfsck_read_stripe_lmv(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_list_lmv, lfsck_instance::li_lock, list_add_tail(), lfsck_lmv::ll_hash_type, lfsck_lmv::ll_inline, lfsck_lmv::ll_lmv, lfsck_lmv::ll_lmv_master, lfsck_lmv::ll_lslr, lfsck_lmv::ll_ref, lfsck_lmv::ll_stripes_allocated, lfsck_lmv_unit::llu_lfsck, lfsck_lmv_unit::llu_link, lfsck_lmv_unit::llu_lmv, lfsck_lmv_unit::llu_obj, LMV_HASH_TYPE_UNKNOWN, lmv_mds_md_v1::lmv_stripe_count, lfsck_namespace::ln_status, lfsck_namespace::ln_striped_dirs_repaired, lfsck_namespace::ln_striped_dirs_skipped, LPF_DRYRUN, LS_SCANNING_PHASE1, LS_SCANNING_PHASE2, lfsck_thread_info::lti_lmv4, OBD_ALLOC_LARGE, OBD_ALLOC_PTR, OBD_FREE_PTR, RETURN, and unlikely.
Referenced by lfsck_namespace_in_notify(), and lfsck_namespace_set_lmv_master().
int lfsck_namespace_rebuild_linkea (const struct lu_env * env, struct lfsck_component * com, struct dt_object * obj, struct linkea_data * ldata)
Overwrite the linkEA for the object with the given ldata.
The caller should take the ldlm lock before the calling.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] obj pointer to the dt_object to be handled
[in] ldata pointer to the new linkEA data
Return values:
positive number for repaired cases
0 if nothing to be repaired
negative error number on failure
Definition at line 1910 of file lfsck_namespace.c.
References CDEBUG, D_LFSCK, DFID, dt_declare_xattr_set(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), dt_xattr_set(), ENTRY, GOTO, lu_buf::lb_buf, lfsck_bookmark::lb_param, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, linkea_data::ld_buf, linkea_data::ld_leh, link_ea_header::leh_len, LF_INCONSISTENT, lfsck_buf_init(), lfsck_dto2fid(), lfsck_is_dead_obj(), lfsck_lfsck2name(), lfsck_obj2dev(), lfsck_instance::li_bookmark_ram, lfsck_namespace::ln_flags, LPF_DRYRUN, PFID, stop, unlikely, and XATTR_NAME_LINK.
Referenced by lfsck_namespace_dsd_multiple(), and lfsck_namespace_striped_dir_rescan().
int lfsck_namespace_repair_bad_name_hash (const struct lu_env * env, struct lfsck_component * com, struct dt_object * shard, struct lfsck_lmv * llmv, const char * name)
Repair the bad name hash.
If the name hash of some name entry under the striped directory does not match the shard of the striped directory, then the LFSCK will repair the inconsistency. Ideally, the LFSCK should migrate the name entry from the current MDT to the right MDT (another one), but before the async commit finished, the LFSCK will change the striped directory's hash type as LMV_HASH_TYPE_UNKNOWN and mark the lmv flags as LMV_HASH_FLAG_BAD_TYPE.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] shard pointer to the shard of the striped directory that contains the bad name entry
[in] llmv pointer to lfsck LMV EA structure
[in] name the name of the bad name hash
Return values:
positive number if nothing to be done
zero for success
negative error number on failure
Definition at line 1473 of file lfsck_striped_dir.c.
References CDEBUG, D_LFSCK, DFID, dotdot, dt_key, dt_lookup(), dt_object_exists(), ENTRY, fid_is_sane(), GOTO, lfsck_component::lc_lfsck, LEF_SET_LMV_HASH, lfsck_dev_idx(), lfsck_dto2fid(), lfsck_env_info(), lfsck_lfsck2name(), lfsck_namespace_set_lmv_master(), lfsck_object_find_bottom(), lfsck_object_put(), lfsck_lmv::ll_lmv, LMV_HASH_FLAG_BAD_TYPE, lmv_mds_md_v1::lmv_hash_type, LMV_HASH_TYPE_UNKNOWN, lmv_mds_md_v1::lmv_master_mdt_index, lfsck_thread_info::lti_fid3, lfsck_thread_info::lti_lmv2, PFID, and unlikely.
Referenced by lfsck_namespace_assistant_handler_p1(), and lfsck_namespace_scan_shard().
int lfsck_namespace_repair_dangling (const struct lu_env * env, struct lfsck_component * com, struct dt_object * parent, struct dt_object * child, struct lfsck_namespace_req * lnr)
Repair dangling name entry.
For the name entry with dangling reference, we need to repare the inconsistency according to the LFSCK sponsor's requirement:
1) Keep the inconsistency there and report the inconsistency case, then give the chance to the application to find related issues, and the users can make the decision about how to handle it with more human knownledge. (by default)
2) Re-create the missing MDT-object with the FID information.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] parent pointer to the dir object that contains the dangling name entry
[in] child pointer to the object corresponding to the dangling name entry
[in] lnr pointer to the namespace request that contains the name's name, parent object, parent's LMV, and ect.
Return values:
positive number if no need to repair
zero for repaired successfully
negative error number on failure
Definition at line 4790 of file lfsck_namespace.c.
References CDEBUG, D_LFSCK, DFID, dt_object_operations::do_ah_init, dt_object::do_ops, dt_object_format::dof_type, dot, dotdot, dt_create(), dt_declare_create(), dt_declare_insert(), dt_declare_ref_add(), dt_declare_xattr_set(), dt_insert(), dt_key, dt_mode_to_dft(), dt_ref_add(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_try_as_dir(), dt_write_lock(), dt_write_unlock(), dt_xattr_set(), ENTRY, GOTO, LA_ATIME, LA_CTIME, LA_GID, LA_MODE, lu_attr::la_mode, LA_MTIME, LA_TYPE, LA_UID, lu_attr::la_valid, lu_buf::lb_buf, lfsck_bookmark::lb_param, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, LCK_PR, linkea_data::ld_buf, linkea_data::ld_leh, link_ea_header::leh_len, LF_INCONSISTENT, lfsck_buf_init(), lfsck_dto2fid(), lfsck_env_info(), lfsck_lfsck2name(), lfsck_lmv_header_cpu_to_le(), lfsck_lock(), lfsck_name_get_const(), lfsck_namespace_check_exist(), lfsck_object_locate(), lfsck_shard_name_to_index(), lfsck_unlock(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_next, linkea_add_buf(), linkea_data_new(), lfsck_lmv::ll_lmv, lfsck_lmv::ll_lmv_master, lmv_mds_md_v1::lmv_magic, LMV_MAGIC_STRIPE, lmv_mds_md_v1::lmv_master_mdt_index, lfsck_namespace::ln_flags, lu_name::ln_name, lfsck_namespace_req::lnr_lmv, lfsck_namespace_req::lnr_name, lfsck_namespace_req::lnr_namelen, lfsck_namespace_req::lnr_type, LPF_CREATE_MDTOBJ, LPF_DRYRUN, lfsck_thread_info::lti_dof, lfsck_thread_info::lti_dt_rec, lfsck_thread_info::lti_hint, lfsck_thread_info::lti_la, lfsck_thread_info::lti_linkea_buf2, lfsck_thread_info::lti_llh, lfsck_thread_info::lti_lmv2, MDS_INODELOCK_UPDATE, PFID, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, stop, unlikely, XATTR_NAME_LINK, and XATTR_NAME_LMV.
Referenced by lfsck_namespace_assistant_handler_p1(), and lfsck_namespace_striped_dir_rescan().
int lfsck_namespace_repair_dirent (const struct lu_env * env, struct lfsck_component * com, struct dt_object * parent, struct dt_object * child, const char * name, const char * name2, __u16 type, bool update, bool dec)
Repair invalid name entry.
If the name entry contains invalid information, such as bad file type or (and) corrupted object FID, then either remove the name entry or udpate the name entry with the given (right) information.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] parent pointer to the parent directory
[in] child pointer to the object referenced by the name entry
[in] name the old name of the child under the parent directory
[in] name2 the new name of the child under the parent directory
[in] type the type claimed by the name entry
[in] update update the name entry if true; otherwise, remove it
[in] dec decrease the parent nlink count if true
Return values:
positive number for repaired successfully
0 if nothing to be repaired
negative error number on failure
Definition at line 1990 of file lfsck_namespace.c.
References CDEBUG, D_LFSCK, DFID, dt_declare_delete(), dt_declare_insert(), dt_declare_ref_del(), dt_delete(), dt_insert(), dt_key, dt_lookup(), dt_ref_del(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_try_as_dir(), dt_write_lock(), dt_write_unlock(), ENTRY, GOTO, lfsck_bookmark::lb_param, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, LCK_PW, LF_INCONSISTENT, lfsck_dto2fid(), lfsck_env_info(), lfsck_ibits_lock(), lfsck_ibits_unlock(), lfsck_lfsck2name(), lfsck_lock(), lfsck_namespace_trace_update(), lfsck_object_locate(), lfsck_object_type(), lfsck_unlock(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_next, lfsck_namespace::ln_flags, LNTF_CHECK_LINKEA, LPF_DRYRUN, lfsck_thread_info::lti_dt_rec, lfsck_thread_info::lti_llh, lu_fid_eq(), MDS_INODELOCK_UPDATE, PFID, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, stop, and unlikely.
Referenced by lfsck_namespace_assistant_handler_p1(), lfsck_namespace_dsd_multiple(), lfsck_namespace_handle_striped_master(), lfsck_namespace_striped_dir_rescan(), and lfsck_remove_dirent().
int lfsck_namespace_scan_shard (const struct lu_env * env, struct lfsck_component * com, struct dt_object * child)
Scan the shard of a striped directory for name hash verification.
During the first-stage scanning, if the LFSCK cannot make sure whether the shard of a stripe directory contains valid slave LMV EA or not, then it will skip the name hash verification for this shard temporarily, and record the shard's FID in the LFSCK tracing file. As the LFSCK processing, the slave LMV EA may has been verified/fixed by LFSCK instance on master. Then in the second-stage scanning, the shard will be re-scanned, and for every name entry under the shard, the name hash will be verified, and for unmatched name entry, the LFSCK will try to fix it.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] child pointer to the directory object to be handled
Return values:
positive number for scanning successfully
zero for the scanning is paused
negative error number on failure
Definition at line 1545 of file lfsck_striped_dir.c.
References __u64, CFS_FAIL_TIMEOUT, cfs_fail_val, dt_index_operations::dio_it, dt_object::do_index_ops, dt_try_as_dir(), ENTRY, GOTO, dt_index_operations::dt_it_ops::init, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, LF_INCONSISTENT, lfsck_control_speed(), lfsck_env_info(), lfsck_is_valid_slave_name_entry(), lfsck_lmv_put(), lfsck_namespace_repair_bad_name_hash(), lfsck_read_stripe_lmv(), lfsck_unpack_ent(), lfsck_instance::li_args_dir, lfsck_instance::li_bookmark_ram, lfsck_instance::li_lock, lfsck_instance::li_thread, lmv_mds_md_v1::lmv_magic, LMV_MAGIC_STRIPE, lfsck_namespace::ln_flags, lfsck_namespace::ln_name_hash_repaired, LPF_FAILOUT, lfsck_thread_info::lti_key, lfsck_thread_info::lti_lmv, LUDA_VERIFY, LUDA_VERIFY_DRYRUN, name_is_dot_or_dotdot(), OBD_ALLOC_PTR, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_DELAY3, OBD_FAIL_LFSCK_FATAL2, RETURN, SVC_STOPPING, thread, thread_is_running(), thread_set_flags(), and unlikely.
Referenced by lfsck_namespace_double_scan_dir().
int lfsck_namespace_setup (const struct lu_env * env, struct lfsck_instance * lfsck)
Definition at line 6514 of file lfsck_namespace.c.
References CERROR, dt_lfsck_features, dt_locate(), dt_try_as_dir(), ENTRY, GOTO, INIT_LIST_HEAD, LASSERT, lfsck_component::lc_data, lfsck_component::lc_file_disk, lfsck_component::lc_file_ram, lfsck_component::lc_file_size, lfsck_component::lc_lfsck, lfsck_component::lc_link, lfsck_component::lc_link_dir, lfsck_component::lc_obj, lfsck_component::lc_ops, lfsck_component::lc_ref, lfsck_component::lc_sem, lfsck_component::lc_sub_trace_objs, lfsck_component::lc_type, lfsck_assistant_data_init(), lfsck_component_cleanup(), lfsck_lfsck2name(), LFSCK_NAMESPACE, lfsck_namespace_init(), lfsck_namespace_load(), lfsck_namespace_load_sub_trace_files(), lfsck_namespace_reset(), lfsck_object_put(), LFSCK_STF_COUNT, LFSCK_TYPE_NAMESPACE, lfsck_instance::li_bottom, lfsck_instance::li_list_dir, lfsck_instance::li_list_idle, lfsck_instance::li_list_scan, lfsck_instance::li_local_root_fid, lfsck_instance::li_lock, lfsck_instance::li_los, lfsck_instance::li_master, list_add_tail(), lfsck_namespace::ln_status, local_index_find_or_create(), LS_COMPLETED, LS_CRASHED, LS_FAILED, LS_INIT, LS_PAUSED, LS_SCANNING_PHASE1, LS_SCANNING_PHASE2, LS_STOPPED, lfsck_sub_trace_obj::lsto_mutex, OBD_ALLOC, OBD_ALLOC_PTR, RETURN, and unlikely.
Referenced by lfsck_register().
int lfsck_namespace_striped_dir_rescan (const struct lu_env * env, struct lfsck_component * com, struct lfsck_namespace_req * lnr)
Double scan the striped directory or the shard.
All the shards' under the given striped directory or its shard have been scanned, the LFSCK has got the global knownledge about the LMV EA consistency.
If the target is one shard of a striped directory, then only needs to update related tracing file.
If the target is the master MDT-object of a striped directory, then the LFSCK will make the decision about whether the master LMV EA is invalid or not, and repair it if inconsistenct; for every shard of the striped directory, whether the slave LMV EA is invalid or not, and repair it if inconsistent.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] lnr pointer to the namespace request that contains the striped directory or the shard
Return values:
zero for success
negative error number on failure
Definition at line 1817 of file lfsck_striped_dir.c.
References CDEBUG, D_LFSCK, DFID, dir, dt_object_remote(), ENTRY, fid_is_zero(), fld_range_set_mdt(), fld_server_lookup(), GOTO, lfsck_assistant_req::lar_parent, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, LCK_EX, linkea_data::ld_leh, LE_SET_LMV_SLAVE, LEF_RECHECK_NAME_HASH, link_ea_header::leh_reccount, lfsck_assistant_object_load(), lfsck_dev_site(), lfsck_dto2fid(), lfsck_env_info(), lfsck_ibits_lock(), lfsck_ibits_unlock(), lfsck_is_dead_obj(), lfsck_lfsck2name(), lfsck_links_read(), LFSCK_LMV_MAX_STRIPES, lfsck_name_get_const(), lfsck_namespace_notify_lmv_remote(), lfsck_namespace_rebuild_linkea(), lfsck_namespace_repair_dangling(), lfsck_namespace_repair_dirent(), lfsck_namespace_trace_update(), lfsck_namespace_update_lmv(), lfsck_object_find_bottom_nowait(), lfsck_object_put(), linkea_add_buf(), linkea_data_new(), linkea_links_find(), lfsck_lmv::ll_exit_value, lfsck_lmv::ll_failed, lfsck_lmv::ll_hash_type, lfsck_lmv::ll_ignore, lfsck_lmv::ll_inline, lfsck_lmv::ll_lmv, lfsck_lmv::ll_lmv_slave, lfsck_lmv::ll_lmv_updated, lfsck_lmv::ll_lmv_verified, lfsck_lmv::ll_lslr, lfsck_lmv::ll_max_filled_off, lfsck_lmv::ll_max_stripe_count, LMV_HASH_FLAG_BAD_TYPE, lmv_mds_md_v1::lmv_hash_type, LMV_HASH_TYPE_MASK, LMV_HASH_TYPE_UNKNOWN, lmv_is_known_hash_type(), lmv_mds_md_v1::lmv_layout_version, lmv_mds_md_v1::lmv_magic, LMV_MAGIC_STRIPE, lmv_mds_md_v1::lmv_master_mdt_index, lmv_mds_md_v1::lmv_stripe_count, lfsck_namespace::ln_dangling_repaired, lfsck_namespace::ln_dirent_repaired, lfsck_namespace::ln_linkea_repaired, lfsck_namespace::ln_striped_dirs_failed, lfsck_namespace::ln_striped_dirs_repaired, lfsck_namespace::ln_striped_dirs_scanned, lfsck_namespace::ln_striped_shards_failed, lfsck_namespace::ln_striped_shards_repaired, lfsck_namespace::ln_striped_shards_scanned, lfsck_namespace_req::lnr_fid, lfsck_namespace_req::lnr_lar, lfsck_namespace_req::lnr_lmv, lfsck_namespace_req::lnr_name, lfsck_namespace_req::lnr_type, LNTF_RECHECK_NAME_HASH, LNTF_UNCERTAIN_LMV, LSLF_BAD_INDEX1, LSLF_BAD_INDEX2, LSLF_DANGLING, LSLF_NO_LMVEA, LSLF_NONE, lfsck_slave_lmv_rec::lslr_fid, lfsck_slave_lmv_rec::lslr_flags, lfsck_slave_lmv_rec::lslr_hash_type, lfsck_slave_lmv_rec::lslr_index, lfsck_slave_lmv_rec::lslr_stripe_count, lfsck_assistant_object::lso_fid, lu_seq_range::lsr_index, lfsck_thread_info::lti_big_buf, lfsck_thread_info::lti_lmv2, lfsck_thread_info::lti_range, lfsck_thread_info::lti_tmpbuf, lfsck_thread_info::lti_tmpbuf2, max, MDS_INODELOCK_UPDATE, MDS_INODELOCK_XATTR, PFID, RETURN, and seq_server_site::ss_server_fld.
Referenced by lfsck_namespace_assistant_handler_p1().
int lfsck_namespace_trace_update (const struct lu_env * env, struct lfsck_component * com, const struct lu_fid * fid, const __u8 flags, bool add)
Update the namespace LFSCK trace file for the given .
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] fid the fid which flags to be updated in the lfsck trace file
[in] add true if add new flags, otherwise remove flags
Return values:
0 for success or nothing to be done
negative error number on failure
Definition at line 525 of file lfsck_namespace.c.
References CDEBUG, D_LFSCK, DFID, dt_declare_delete(), dt_declare_insert(), dt_delete(), dt_insert(), dt_key, dt_lookup(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), ENTRY, fid_cpu_to_be(), fid_is_sane(), GOTO, LASSERT, lfsck_component::lc_lfsck, lfsck_component::lc_sub_trace_objs, lfsck_env_info(), lfsck_lfsck2name(), lfsck_obj2dev(), lfsck_sub_trace_file_fid2idx(), lfsck_sub_trace_obj::lsto_mutex, lfsck_sub_trace_obj::lsto_obj, lfsck_thread_info::lti_fid3, PFID, RETURN, and unlikely.
Referenced by lfsck_namespace_assistant_handler_p1(), lfsck_namespace_check_for_double_scan(), lfsck_namespace_exec_oit(), lfsck_namespace_handle_striped_master(), lfsck_namespace_in_notify(), lfsck_namespace_repair_dirent(), lfsck_namespace_striped_dir_rescan(), lfsck_namespace_verify_stripe_slave(), and lfsck_record_lmv().
int lfsck_namespace_update_lmv (const struct lu_env * env, struct lfsck_component * com, struct dt_object * obj, struct lmv_mds_md_v1 * lmv, bool locked)
Update the object's LMV EA with the given .
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] obj pointer to the object which LMV EA will be updated
[in] lmv pointer to buffer holding the new LMV EA
[in] locked whether the caller has held ldlm lock on the or not
Return values:
positive number for nothing to be done
zero if updated successfully
negative error number on failure
Definition at line 993 of file lfsck_striped_dir.c.
References buf, CDEBUG, D_LFSCK, DFID, dt_declare_xattr_set(), dt_object_remote(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), dt_xattr_set(), ENTRY, GOTO, LASSERT, lfsck_bookmark::lb_param, lfsck_component::lc_lfsck, LCK_EX, lfsck_buf_init(), lfsck_dto2fid(), lfsck_env_info(), lfsck_ibits_lock(), lfsck_ibits_unlock(), lfsck_is_dead_obj(), lfsck_lfsck2name(), lfsck_lmv_header_cpu_to_le(), lfsck_obj2dev(), lfsck_instance::li_bookmark_ram, LMV_MAGIC, lmv_mds_md_v1::lmv_magic, LPF_DRYRUN, lfsck_thread_info::lti_buf, lfsck_thread_info::lti_lmv4, MDS_INODELOCK_UPDATE, MDS_INODELOCK_XATTR, PFID, stop, thandle::th_sync, unlikely, and XATTR_NAME_LMV.
Referenced by lfsck_namespace_set_lmv_master(), and lfsck_namespace_striped_dir_rescan().
int lfsck_namespace_verify_stripe_slave (const struct lu_env * env, struct lfsck_component * com, struct dt_object * obj, struct lfsck_lmv * llmv)
Verify the slave object's (of striped directory) LMV EA.
For the slave object of a striped directory, before traversing the shard the LFSCK will verify whether its slave LMV EA matches its parent's master LMV EA or not.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] obj pointer to the object which LMV EA will be checked
[in] llmv pointer to buffer holding the slave LMV EA
Return values:
positive number if nothing to be done
zero for success
negative error number on failure
Definition at line 1672 of file lfsck_striped_dir.c.
References DFID, dotdot, dt_key, dt_lookup(), dt_object_exists(), dt_try_as_dir(), ENTRY, fid_is_sane(), GOTO, lfsck_component::lc_lfsck, LEF_SET_LMV_ALL, lfsck_dto2fid(), lfsck_env_info(), lfsck_is_valid_slave_lmv(), lfsck_links_get_first(), lfsck_namespace_set_lmv_master(), lfsck_namespace_trace_update(), lfsck_object_find_bottom(), lfsck_object_put(), lfsck_read_stripe_lmv(), lfsck_lmv::ll_lmv, lfsck_lmv::ll_lmv_verified, LMV_HASH_FLAG_BAD_TYPE, lmv_mds_md_v1::lmv_hash_type, LMV_HASH_TYPE_MASK, LMV_HASH_TYPE_UNKNOWN, LMV_MAGIC, lmv_mds_md_v1::lmv_magic, lmv_mds_md_v1::lmv_master_mdt_index, lmv_mds_md_v1::lmv_stripe_count, LNTF_UNCERTAIN_LMV, lfsck_thread_info::lti_fid3, lfsck_thread_info::lti_key, lfsck_thread_info::lti_lmv, lfsck_thread_info::lti_tmpbuf2, lu_fid_eq(), name, PFID, and unlikely.
Referenced by lfsck_namespace_open_dir().
static struct dt_device* lfsck_obj2dev (struct dt_object * obj) [static, read]
Definition at line 1078 of file lfsck_internal.h.
References dt_device::dd_lu_dev, dt_object::do_lu, and lu_object::lo_dev.
Referenced by __lfsck_layout_update_pfid(), lfsck_bookmark_store(), lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_disable_master_lmv(), lfsck_layout_conflict_create(), lfsck_layout_destroy_orphan(), lfsck_layout_lastid_create(), lfsck_layout_master_exec_oit(), lfsck_layout_recreate_lovea(), lfsck_layout_repair_dangling(), lfsck_layout_repair_multiple_references(), lfsck_layout_repair_owner(), lfsck_layout_repair_unmatched_pair(), lfsck_layout_store(), lfsck_lpf_remove_name_entry(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_insert_orphan(), lfsck_namespace_links_remove(), lfsck_namespace_rebuild_linkea(), lfsck_namespace_repair_nlink(), lfsck_namespace_repair_unmatched_pairs(), lfsck_namespace_shrink_linkea(), lfsck_namespace_store(), lfsck_namespace_trace_update(), lfsck_namespace_update_lmv(), lfsck_object_locate(), lfsck_update_name_entry(), and lfsck_verify_linkea().
static struct dt_object* lfsck_object_find_bottom (const struct lu_env * env, struct lfsck_instance * lfsck, const struct lu_fid * fid) [static, read]
Definition at line 1283 of file lfsck_internal.h.
References lfsck_find_dev_by_fid(), and lfsck_object_find_by_dev().
Referenced by lfsck_assistant_object_load(), lfsck_create_lpf(), lfsck_layout_check_parent(), lfsck_layout_master_check_pairs(), lfsck_layout_slave_repair_pfid(), lfsck_master_oit_engine(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_double_scan_one(), lfsck_namespace_double_scan_one_trace_file(), lfsck_namespace_dsd_multiple(), lfsck_namespace_dsd_single(), lfsck_namespace_in_notify(), lfsck_namespace_repair_bad_name_hash(), lfsck_namespace_verify_stripe_slave(), lfsck_needs_scan_dir(), lfsck_orphan_it_next(), lfsck_prep(), lfsck_remove_dirent(), lfsck_verify_lpf(), and lfsck_verify_lpf_pairs().
static struct dt_object* lfsck_object_find_bottom_nowait (const struct lu_env * env, struct lfsck_instance * lfsck, const struct lu_fid * fid) [static, read]
Definition at line 1296 of file lfsck_internal.h.
References lfsck_find_dev_by_fid(), and lfsck_object_find_by_dev_nowait().
Referenced by lfsck_namespace_striped_dir_rescan().
static struct dt_object* lfsck_object_find_by_dev (const struct lu_env * env, struct dt_device * dev, const struct lu_fid * fid) [static, read]
Definition at line 1247 of file lfsck_internal.h.
References dt2lu_dev(), lu2dt(), and lu_object_find_slice().
Referenced by lfsck_layout_recreate_parent(), lfsck_layout_scan_orphan(), lfsck_layout_scan_orphan_one(), lfsck_layout_slave_conditional_destroy(), lfsck_layout_update_pfid(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_replace_cond(), lfsck_namespace_scan_local_lpf(), lfsck_namespace_scan_local_lpf_one(), lfsck_object_find_bottom(), and lfsck_verify_lpf().
static struct dt_object* lfsck_object_find_by_dev_nowait (const struct lu_env * env, struct dt_device * dev, const struct lu_fid * fid) [static, read]
Definition at line 1237 of file lfsck_internal.h.
References dt2lu_dev(), lfsck_env_info(), LOC_F_NOWAIT, lu_object_conf::loc_flags, lfsck_thread_info::lti_conf, lu2dt(), and lu_object_find_slice().
Referenced by lfsck_layout_scan_stripes(), lfsck_namespace_handle_striped_master(), and lfsck_object_find_bottom_nowait().
static struct dt_object* lfsck_object_get (struct dt_object * obj) [static, read]
Definition at line 1213 of file lfsck_internal.h.
References dt_object::do_lu, and lu_object_get().
Referenced by lfsck_load_stripe_lmv(), lfsck_master_oit_engine(), lfsck_namespace_notify_lmv_master_local(), lfsck_namespace_rescan_striped_dir(), and lfsck_post().
static struct dt_object* lfsck_object_locate (struct dt_device * dev, struct dt_object * obj) [static, read]
Definition at line 1310 of file lfsck_internal.h.
References dt_device::dd_lu_dev, dt_object::do_lu, lu_device::ld_type, lfsck_obj2dev(), lu_object::lo_header, lu2dt(), lu_object_locate(), and unlikely.
Referenced by lfsck_layout_repair_multiple_references(), lfsck_namespace_insert_normal(), lfsck_namespace_repair_dangling(), lfsck_namespace_repair_dirent(), and lfsck_namespace_replace_cond().
static void lfsck_object_put (const struct lu_env * env, struct dt_object * obj) [inline, static]
Definition at line 1219 of file lfsck_internal.h.
References dt_object::do_lu, and lu_object_put().
Referenced by lfsck_assistant_object_load(), lfsck_bookmark_setup(), lfsck_close_dir(), lfsck_component_put(), lfsck_create_lpf(), lfsck_instance_cleanup(), lfsck_layout_assistant_handler_p1(), lfsck_layout_assistant_req_fini(), lfsck_layout_check_parent(), lfsck_layout_get_def_stripesize(), lfsck_layout_lastid_load(), lfsck_layout_master_check_pairs(), lfsck_layout_recreate_parent(), lfsck_layout_repair_multiple_references(), lfsck_layout_scan_orphan(), lfsck_layout_scan_orphan_one(), lfsck_layout_scan_stripes(), lfsck_layout_setup(), lfsck_layout_slave_conditional_destroy(), lfsck_layout_slave_quit(), lfsck_layout_slave_repair_pfid(), lfsck_layout_update_pfid(), lfsck_lmv_put(), lfsck_master_oit_engine(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_double_scan_one(), lfsck_namespace_double_scan_one_trace_file(), lfsck_namespace_dsd_multiple(), lfsck_namespace_dsd_single(), lfsck_namespace_handle_striped_master(), lfsck_namespace_in_notify(), lfsck_namespace_load_sub_trace_files(), lfsck_namespace_repair_bad_name_hash(), lfsck_namespace_replace_cond(), lfsck_namespace_reset(), lfsck_namespace_scan_local_lpf(), lfsck_namespace_scan_local_lpf_one(), lfsck_namespace_setup(), lfsck_namespace_striped_dir_rescan(), lfsck_namespace_verify_stripe_slave(), lfsck_needs_scan_dir(), lfsck_orphan_it_next(), lfsck_prep(), lfsck_rbtree_cleanup(), lfsck_register(), lfsck_remove_dirent(), lfsck_verify_lpf(), and lfsck_verify_lpf_pairs().
static umode_t lfsck_object_type (const struct dt_object * obj) [inline, static]
Definition at line 1201 of file lfsck_internal.h.
References dt_object::do_lu, and lu_object_attr().
Referenced by lfsck_layout_check_parent(), lfsck_layout_master_check_pairs(), lfsck_layout_master_exec_oit(), lfsck_lock(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_check_for_double_scan(), lfsck_namespace_check_name(), lfsck_namespace_double_scan_one(), lfsck_namespace_exec_oit(), lfsck_namespace_handle_striped_master(), lfsck_namespace_insert_normal(), lfsck_namespace_insert_orphan(), lfsck_namespace_repair_dirent(), lfsck_namespace_repair_nlink(), lfsck_namespace_repair_unmatched_pairs(), lfsck_namespace_scan_local_lpf_one(), lfsck_needs_scan_dir(), lfsck_parent_fid(), lfsck_prep(), lfsck_verify_linkea(), and lfsck_verify_lpf().
int lfsck_open_dir (const struct lu_env * env, struct lfsck_instance * lfsck, __u64 cookie)
Definition at line 337 of file lfsck_engine.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, dt_try_as_dir(), ENTRY, GOTO, dt_index_operations::dt_it_ops::init, LASSERT, lfsck_component::lc_ops, lfsck_close_dir(), lfsck_operations::lfsck_open_dir, lfsck_instance::li_args_dir, lfsck_instance::li_cookie_dir, lfsck_instance::li_di_dir, lfsck_instance::li_list_dir, lfsck_instance::li_lock, lfsck_instance::li_obj_dir, list_for_each_entry, and unlikely.
Referenced by lfsck_exec_oit(), lfsck_master_oit_engine(), lfsck_namespace_rescan_striped_dir(), lfsck_post(), and lfsck_prep().
static bool lfsck_phase2_next_ready (struct lfsck_assistant_data * lad) [inline, static]
Definition at line 1396 of file lfsck_internal.h.
References lfsck_assistant_data::lad_mdt_phase1_list, lfsck_assistant_data::lad_ost_phase1_list, lfsck_assistant_data::lad_ost_phase2_list, and list_empty().
Referenced by lfsck_assistant_engine(), lfsck_layout_master_in_notify(), and lfsck_namespace_in_notify().
void lfsck_pos_dump (struct seq_file * m, struct lfsck_position * pos, const char * prefix)
Definition at line 1779 of file lfsck_lib.c.
References DFID, fid_is_zero(), lfsck_position::lp_dir_cookie, lfsck_position::lp_dir_parent, lfsck_position::lp_oit_cookie, LPU64, LPX64, and PFID.
Referenced by lfsck_namespace_dump().
void lfsck_pos_fill (const struct lu_env * env, struct lfsck_instance * lfsck, struct lfsck_position * pos, bool init)
Definition at line 1796 of file lfsck_lib.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, fid_zero(), LASSERT, lfsck_dto2fid(), lfsck_instance::li_current_oit_processed, lfsck_instance::li_di_dir, lfsck_instance::li_di_oit, lfsck_instance::li_obj_dir, lfsck_instance::li_obj_oit, lfsck_position::lp_dir_cookie, lfsck_position::lp_dir_parent, lfsck_position::lp_oit_cookie, MDS_DIR_END_OFF, dt_index_operations::dt_it_ops::store, and unlikely.
Referenced by lfsck_checkpoint(), lfsck_master_engine(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_record_failure(), lfsck_post(), and lfsck_prep().
static int lfsck_pos_is_eq (const struct lfsck_position * pos1, const struct lfsck_position * pos2) [inline, static]
Definition at line 1153 of file lfsck_internal.h.
References fid_is_zero(), LASSERT, lfsck_position::lp_dir_cookie, lfsck_position::lp_dir_parent, lfsck_position::lp_oit_cookie, and lu_fid_eq().
Referenced by lfsck_namespace_record_failure(), and lfsck_prep().
static int lfsck_pos_is_zero (const struct lfsck_position * pos) [inline, static]
Definition at line 1148 of file lfsck_internal.h.
References fid_is_zero(), lfsck_position::lp_dir_parent, and lfsck_position::lp_oit_cookie.
Referenced by lfsck_namespace_assistant_handler_p1(), lfsck_namespace_prep(), lfsck_namespace_record_failure(), and lfsck_prep().
static void lfsck_pos_set_zero (struct lfsck_position * pos) [inline, static]
Definition at line 1143 of file lfsck_internal.h.
Referenced by lfsck_namespace_prep().
static void lfsck_position_cpu_to_le (struct lfsck_position * des, struct lfsck_position * src) [inline, static]
Definition at line 1193 of file lfsck_internal.h.
References cpu_to_le64, fid_cpu_to_le(), lfsck_position::lp_dir_cookie, lfsck_position::lp_dir_parent, and lfsck_position::lp_oit_cookie.
Referenced by lfsck_namespace_cpu_to_le().
static void lfsck_position_le_to_cpu (struct lfsck_position * des, struct lfsck_position * src) [inline, static]
Definition at line 1185 of file lfsck_internal.h.
References fid_le_to_cpu(), le64_to_cpu, lfsck_position::lp_dir_cookie, lfsck_position::lp_dir_parent, and lfsck_position::lp_oit_cookie.
Referenced by lfsck_namespace_le_to_cpu().
void lfsck_post_generic (const struct lu_env * env, struct lfsck_component * com, int * result)
Definition at line 2551 of file lfsck_lib.c.
References CDEBUG, D_LFSCK, l_wait_event, lfsck_assistant_data::lad_assistant_status, lfsck_assistant_data::lad_exit, lfsck_assistant_data::lad_name, lfsck_assistant_data::lad_post_result, lfsck_assistant_data::lad_req_list, lfsck_assistant_data::lad_thread, lfsck_assistant_data::lad_to_post, lfsck_component::lc_data, lfsck_component::lc_lfsck, lfsck_lfsck2name(), lfsck_instance::li_thread, list_empty(), ptlrpc_thread::t_ctl_waitq, and thread_is_stopped().
Referenced by lfsck_layout_master_post(), and lfsck_namespace_post().
int lfsck_query_all (const struct lu_env * env, struct lfsck_component * com)
Definition at line 2420 of file lfsck_lib.c.
References CDEBUG, cfs_foreach_bit, D_LFSCK, ENTRY, lfsck_assistant_data::lad_name, lfsck_async_interpret_args::laia_com, lfsck_async_interpret_args::laia_lr, lfsck_async_interpret_args::laia_ltd, lfsck_async_interpret_args::laia_ltds, LASSERT, lfsck_component::lc_data, lfsck_component::lc_lfsck, lfsck_component::lc_type, LE_QUERY, LEF_QUERY_ALL, LEF_TO_OST, lfsck_async_interpret_common(), lfsck_async_request(), lfsck_env_info(), lfsck_lfsck2name(), LFSCK_QUERY, lfsck_reset_ltd_status(), lfsck_tgt_get(), lfsck_tgt_put(), LFSCK_TYPE_LAYOUT, lfsck_instance::li_mdt_descs, lfsck_instance::li_ost_descs, lfsck_request::lr_active, lfsck_request::lr_event, lfsck_request::lr_flags, lfsck_tgt_desc::ltd_exp, lfsck_tgt_desc::ltd_index, lfsck_tgt_descs::ltd_rw_sem, lfsck_tgt_descs::ltd_tgts_bitmap, lfsck_thread_info::lti_laia, lfsck_thread_info::lti_lr, ptlrpc_prep_set(), ptlrpc_set_destroy(), ptlrpc_set_wait(), and RETURN.
Referenced by lfsck_layout_query_all(), and lfsck_namespace_query_all().
void lfsck_quit_generic (const struct lu_env * env, struct lfsck_component * com)
Definition at line 2613 of file lfsck_lib.c.
References l_wait_event, lfsck_assistant_data::lad_exit, lfsck_assistant_data::lad_thread, lfsck_component::lc_data, lfsck_component::lc_lfsck, lfsck_instance::li_thread, ptlrpc_thread::t_ctl_waitq, thread_is_init(), and thread_is_stopped().
Referenced by lfsck_layout_master_quit(), and lfsck_namespace_quit().
int lfsck_read_stripe_lmv (const struct lu_env * env, struct dt_object * obj, struct lmv_mds_md_v1 * lmv)
Definition at line 841 of file lfsck_striped_dir.c.
References dt_read_lock(), dt_read_unlock(), dt_xattr_get(), lfsck_buf_get(), lfsck_lmv_header_le_to_cpu(), LMV_HASH_FLAG_MIGRATION, lmv_mds_md_v1::lmv_hash_type, LMV_MAGIC, lmv_mds_md_v1::lmv_magic, LMV_MAGIC_STRIPE, and XATTR_NAME_LMV.
Referenced by lfsck_load_stripe_lmv(), lfsck_namespace_check_name(), lfsck_namespace_dsd_single(), lfsck_namespace_handle_striped_master(), lfsck_namespace_notify_lmv_master_local(), lfsck_namespace_scan_shard(), lfsck_namespace_set_lmv_master(), and lfsck_namespace_verify_stripe_slave().
int lfsck_set_param (const struct lu_env * env, struct lfsck_instance * lfsck, struct lfsck_start * start, bool reset)
Definition at line 203 of file lfsck_bookmark.c.
References __lfsck_set_speed(), LASSERT, lfsck_bookmark::lb_async_windows, lfsck_bookmark::lb_param, LFSCK_ASYNC_WIN_DEFAULT, LFSCK_ASYNC_WIN_MAX, lfsck_bookmark_store(), LFSCK_SPEED_NO_LIMIT, lfsck_instance::li_bookmark_ram, lfsck_instance::li_drop_dryrun, LPF_ALL_TGT, LPF_CREATE_MDTOBJ, LPF_CREATE_OSTOBJ, LPF_DRYRUN, LPF_FAILOUT, LPF_OST_ORPHAN, lfsck_start::ls_async_windows, lfsck_start::ls_flags, lfsck_start::ls_speed_limit, lfsck_start::ls_valid, LSV_ASYNC_WINDOWS, LSV_CREATE_MDTOBJ, LSV_CREATE_OSTOBJ, LSV_DRYRUN, LSV_ERROR_HANDLE, and LSV_SPEED_LIMIT.
Referenced by lfsck_layout_master_prep(), lfsck_layout_prep(), lfsck_namespace_prep(), and lfsck_start().
int lfsck_shard_name_to_index (const struct lu_env * env, const char * name, int namelen, __u16 type, const struct lu_fid * fid)
Parse the shard's index from the given shard name.
The valid shard name/type should be: 1) The type must be S_IFDIR 2) The name should be $FID:$index 3) the index should within valid range.
Parameters:
[in] env pointer to the thread context
[in] name the shard name
[in] namelen the name length
[in] type the entry's type
[in] fid the entry's FID
Return values:
zero or positive number for the index from the name
negative error number on failure
Definition at line 880 of file lfsck_striped_dir.c.
References DFID, LASSERT, lfsck_env_info(), LFSCK_LMV_MAX_STRIPES, lfsck_thread_info::lti_tmpbuf2, and PFID.
Referenced by lfsck_allow_regenerate_master_lmv(), lfsck_namespace_check_name(), lfsck_namespace_dsd_single(), lfsck_namespace_handle_striped_master(), and lfsck_namespace_repair_dangling().
int lfsck_start_assistant (const struct lu_env * env, struct lfsck_component * com, struct lfsck_start_param * lsp)
Definition at line 2484 of file lfsck_lib.c.
References CERROR, ENTRY, l_wait_event, lfsck_assistant_data::lad_advance_lock, lfsck_assistant_data::lad_assistant_status, lfsck_assistant_data::lad_exit, lfsck_assistant_data::lad_in_double_scan, lfsck_assistant_data::lad_name, lfsck_assistant_data::lad_post_result, lfsck_assistant_data::lad_thread, lfsck_assistant_data::lad_to_double_scan, lfsck_assistant_data::lad_to_post, lfsck_component::lc_data, lfsck_component::lc_lfsck, lfsck_assistant_engine(), lfsck_lfsck2name(), lfsck_thread_args_fini(), lfsck_thread_args_init(), lfsck_instance::li_thread, RETURN, ptlrpc_thread::t_ctl_waitq, thread_is_running(), thread_is_stopped(), thread_set_flags(), and unlikely.
Referenced by lfsck_layout_master_prep(), and lfsck_namespace_prep().
static int lfsck_sub_trace_file_fid2idx (const struct lu_fid * fid) [inline, static]
Definition at line 1453 of file lfsck_internal.h.
References lu_fid::f_oid, and LFSCK_STF_COUNT.
Referenced by lfsck_namespace_assistant_handler_p2(), lfsck_namespace_in_notify(), lfsck_namespace_repair_nlink(), lfsck_namespace_scan_local_lpf_one(), and lfsck_namespace_trace_update().
static struct lfsck_tgt_desc* lfsck_tgt_get (struct lfsck_tgt_descs * ltds, __u32 index) [static, read]
Definition at line 1326 of file lfsck_internal.h.
References lfsck_ltd2tgt(), and lfsck_tgt_desc::ltd_ref.
Referenced by lfsck_assistant_notify_others(), lfsck_layout_master_conditional_destroy(), lfsck_layout_scan_stripes(), lfsck_namespace_notify_lmv_remote(), lfsck_query_all(), lfsck_start_all(), lfsck_stop_all(), and lfsck_verify_lpf().
static void lfsck_tgt_put (struct lfsck_tgt_desc * ltd) [inline, static]
Definition at line 1338 of file lfsck_internal.h.
References lfsck_tgt_desc::ltd_ref, and OBD_FREE_PTR.
Referenced by lfsck_add_target(), lfsck_assistant_notify_others(), lfsck_assistant_query_others(), lfsck_async_interpret(), lfsck_async_interpret_common(), lfsck_del_target(), lfsck_exit(), lfsck_layout_master_conditional_destroy(), lfsck_layout_scan_stripes(), lfsck_namespace_notify_lmv_remote(), lfsck_query_all(), lfsck_start_all(), lfsck_stop_all(), lfsck_stop_notify(), lfsck_tgt_descs_fini(), and lfsck_verify_lpf().
void lfsck_thread_args_fini (struct lfsck_thread_args * lta)
Definition at line 1919 of file lfsck_lib.c.
References lfsck_component_put(), lfsck_instance_put(), lfsck_thread_args::lta_com, lfsck_thread_args::lta_env, lfsck_thread_args::lta_lfsck, lu_env_fini(), and OBD_FREE_PTR.
Referenced by lfsck_assistant_engine(), lfsck_master_engine(), lfsck_start(), and lfsck_start_assistant().
void lfsck_time_dump (struct seq_file * m, __u64 time, const char * name)
Definition at line 1767 of file lfsck_lib.c.
References cfs_time_current_sec(), and LPU64.
Referenced by lfsck_layout_dump(), and lfsck_namespace_dump().
void lfsck_unlock (struct lfsck_lock_handle * llh)
Release the the compound ibits locks.
Parameters:
[in] llh pointer to the lfsck_lock_handle to be released
Definition at line 520 of file lfsck_lib.c.
References lfsck_ibits_unlock(), lfsck_lock_handle::llh_pdo_lh, lfsck_lock_handle::llh_pdo_mode, lfsck_lock_handle::llh_reg_lh, and lfsck_lock_handle::llh_reg_mode.
Referenced by lfsck_create_lpf(), lfsck_layout_recreate_parent(), lfsck_lpf_remove_name_entry(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_insert_normal(), lfsck_namespace_insert_orphan(), lfsck_namespace_repair_dangling(), lfsck_namespace_repair_dirent(), lfsck_namespace_replace_cond(), lfsck_namespace_shrink_linkea_cond(), and lfsck_update_name_entry().
int lfsck_unpack_ent (struct lu_dirent * ent, __u64 * cookie, __u16 * type)
Definition at line 42 of file lfsck_engine.c.
References fid_le_to_cpu(), lu_dirent::lde_attrs, lu_dirent::lde_fid, lu_dirent::lde_hash, lu_dirent::lde_name, lu_dirent::lde_namelen, lu_dirent::lde_reclen, le16_to_cpu, le32_to_cpu, le64_to_cpu, luda_type::lt_type, LUDA_TYPE, and unlikely.
Referenced by lfsck_allow_regenerate_master_lmv(), lfsck_master_dir_engine(), lfsck_namespace_rescan_striped_dir(), lfsck_namespace_scan_local_lpf(), and lfsck_namespace_scan_shard().
int lfsck_update_name_entry (const struct lu_env * env, struct lfsck_instance * lfsck, struct dt_object * dir, const char * name, const struct lu_fid * fid, __u32 type)
Update the object's name entry with the given FID.
Parameters:
[in] env pointer to the thread context
[in] lfsck pointer to the lfsck instance
[in] dir pointer to the directory that holds the name entry
[in] name the name for the entry to be updated
[in] fid the new FID for the name entry referenced
[in] type the type for the name entry to be updated
Return values:
0 for success
negative error number on failure
Definition at line 6441 of file lfsck_namespace.c.
References CDEBUG, D_LFSCK, DFID, dt_declare_delete(), dt_declare_insert(), dt_declare_ref_add(), dt_delete(), dt_insert(), dt_key, dt_ref_add(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), ENTRY, GOTO, LCK_PW, lfsck_dto2fid(), lfsck_env_info(), lfsck_lfsck2name(), lfsck_lock(), lfsck_obj2dev(), lfsck_unlock(), lfsck_thread_info::lti_dt_rec, lfsck_thread_info::lti_llh, MDS_INODELOCK_UPDATE, PFID, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, RETURN, and stop.
Referenced by lfsck_update_lpf_entry(), and lfsck_verify_lpf_pairs().
int lfsck_verify_linkea (const struct lu_env * env, struct dt_object * obj, const struct lu_name * cname, const struct lu_fid * pfid)
Verify the specified linkEA entry for the given directory object.
If the object has no such linkEA entry or it has more other linkEA entries, then re-generate the linkEA with the given information.
Parameters:
[in] env pointer to the thread context
[in] obj pointer to the dt_object to be handled
[in] cname the name for the child in the parent directory
[in] pfid the parent directory's FID for the linkEA
Return values:
0 for success
negative error number on failure
Definition at line 6325 of file lfsck_namespace.c.
References dt_declare_xattr_set(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), dt_xattr_set(), ENTRY, GOTO, LASSERT, lu_buf::lb_buf, linkea_data::ld_buf, linkea_data::ld_leh, link_ea_header::leh_len, link_ea_header::leh_reccount, lfsck_buf_init(), lfsck_env_info(), lfsck_links_read(), lfsck_obj2dev(), lfsck_object_type(), linkea_add_buf(), linkea_data_new(), linkea_links_find(), LU_XATTR_CREATE, LU_XATTR_REPLACE, RETURN, stop, and XATTR_NAME_LINK.
Referenced by lfsck_register(), lfsck_verify_lpf(), and lfsck_verify_lpf_pairs().
int lfsck_verify_lpf (const struct lu_env * env, struct lfsck_instance * lfsck)
Verify the /ROOT/.lustre/lost+found/ directory.
/ROOT/.lustre/lost+found/ is a special directory to hold the objects that the LFSCK does not exactly know how to handle, such as orphans. So before the LFSCK scanning the system, the consistency of such directory needs to be verified firstly to allow the users to use it during the LFSCK.
Parameters:
[in] env pointer to the thread context
[in] lfsck pointer to the lfsck instance
Return values:
positive number for uncertain inconsistency
0 for success
negative error number on failure
Definition at line 1371 of file lfsck_lib.c.
References CDEBUG, D_LFSCK, DFID, dt_object::do_lu, dt_key, dt_lookup(), dt_object_exists(), dt_object_remote(), dt_try_as_dir(), ENTRY, fid_is_norm(), fid_is_zero(), fid_zero(), GOTO, LASSERT, lfsck_bookmark::lb_lpf_fid, lfsck_bookmark_store(), lfsck_create_lpf(), lfsck_dev_idx(), lfsck_dto2fid(), lfsck_env_info(), lfsck_lfsck2name(), lfsck_lpf_remove_name_entry(), lfsck_name_get_const(), lfsck_object_find_bottom(), lfsck_object_find_by_dev(), lfsck_object_put(), lfsck_object_type(), lfsck_scan_lpf_bad_entries(), lfsck_tgt_get(), lfsck_tgt_put(), lfsck_verify_linkea(), lfsck_verify_lpf_pairs(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_bottom, lfsck_instance::li_lpf_obj, lfsck_instance::li_lpf_root_obj, lfsck_instance::li_master, lfsck_instance::li_mdt_descs, likely, lfsck_tgt_desc::ltd_tgt, lfsck_thread_info::lti_fid, lfsck_thread_info::lti_fid2, lu_fid_eq(), LU_LPF_FID, lu_object_get(), LVLT_BY_BOOKMARK, LVLT_BY_NAMEENTRY, name, PFID, RETURN, and unlikely.
Referenced by lfsck_master_engine().
static bool name_is_dot_or_dotdot (const char * name, int namelen) [inline, static]
Definition at line 1072 of file lfsck_internal.h.
Referenced by lfsck_allow_regenerate_master_lmv(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_rescan_striped_dir(), lfsck_namespace_scan_local_lpf(), lfsck_namespace_scan_shard(), and lfsck_scan_lpf_bad_entries().
Variable Documentation
const char dot[]
Definition at line 542 of file lfsck_lib.c.
Referenced by lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_repair_dangling(), lod_dir_declare_create_stripes(), lod_xattr_set_lmv(), mdd_declare_object_initialize(), and mdd_object_initialize().
const char dotdot[]
Definition at line 543 of file lfsck_lib.c.
Referenced by lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_double_scan_dir(), lfsck_namespace_handle_striped_master(), lfsck_namespace_insert_orphan(), lfsck_namespace_repair_bad_name_hash(), lfsck_namespace_repair_dangling(), lfsck_namespace_repair_unmatched_pairs(), lfsck_namespace_verify_stripe_slave(), lfsck_verify_lpf_pairs(), ll_dir_get_parent_fid(), lod_dir_declare_create_stripes(), lod_xattr_set_lmv(), mdd_declare_object_initialize(), mdd_declare_rename(), mdd_migrate_entries(), mdd_object_initialize(), mdd_rename(), orph_declare_index_insert(), and orph_index_insert().
const char* lfsck_flags_names[]
Definition at line 71 of file lfsck_lib.c.
Referenced by lfsck_layout_dump(), and lfsck_namespace_dump().
const char* lfsck_param_names[]
Definition at line 80 of file lfsck_lib.c.
Referenced by lfsck_layout_dump(), and lfsck_namespace_dump().
struct lu_context_key lfsck_thread_key
Referenced by lfsck_env_info(), lfsck_exit(), and lfsck_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.