Lustre: lustre/lfsck/lfsck_striped_dir.c File Reference
lustre/lfsck/lfsck_striped_dir.c File Reference
#include <lustre/lustre_idl.h>
#include <lu_object.h>
#include <dt_object.h>
#include <md_object.h>
#include <lustre_fid.h>
#include <lustre_lib.h>
#include <lustre_net.h>
#include <lustre_lmv.h>
#include <lustre/lustre_user.h>
#include "lfsck_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LFSCK
Functions
void lfsck_lmv_put (const struct lu_env *env, struct lfsck_lmv *llmv)
static int lfsck_disable_master_lmv (const struct lu_env *env, struct lfsck_component *com, struct dt_object *obj, bool del_lmv)
Mark the specified directory as read-only by set LUSTRE_IMMUTABLE_FL.
static bool lfsck_is_valid_slave_lmv (struct lmv_mds_md_v1 *lmv)
static int lfsck_remove_lmv (const struct lu_env *env, struct lfsck_component *com, struct dt_object *obj, struct lfsck_namespace_req *lnr)
Remove the striped directory's master LMV EA and mark it as read-only.
static int lfsck_remove_dirent (const struct lu_env *env, struct lfsck_component *com, struct dt_object *dir, const struct lu_fid *fid, __u32 index)
Remove the name entry from the striped directory's master MDT-object.
static int lfsck_replace_lmv (const struct lu_env *env, struct lfsck_component *com, struct dt_object *dir, struct lfsck_slave_lmv_rec *lslr, struct lfsck_namespace_req *lnr, struct lmv_mds_md_v1 *lmv, __u32 index, __u32 flags)
Remove old shard's name entry and refill the slot with new shard.
static int lfsck_record_lmv (const struct lu_env *env, struct lfsck_component *com, struct dt_object *dir, struct lfsck_namespace_req *lnr, struct lmv_mds_md_v1 *lmv, __u32 shard_idx, __u32 flags, __u32 flags2, __u32 *depth)
Record the slave LMV EA in the lfsck_lmv::ll_lslr.
int lfsck_read_stripe_lmv (const struct lu_env *env, struct dt_object *obj, struct lmv_mds_md_v1 *lmv)
int lfsck_shard_name_to_index (const struct lu_env *env, const char *name, int namelen, __u16 type, const struct lu_fid *fid)
Parse the shard's index from the given shard name.
bool lfsck_is_valid_slave_name_entry (const struct lu_env *env, struct lfsck_lmv *llmv, const char *name, int namelen)
int lfsck_namespace_check_name (const struct lu_env *env, struct dt_object *parent, struct dt_object *child, const struct lu_name *cname)
Check whether the given name is a valid entry under the .
int lfsck_namespace_update_lmv (const struct lu_env *env, struct lfsck_component *com, struct dt_object *obj, struct lmv_mds_md_v1 *lmv, bool locked)
Update the object's LMV EA with the given .
static int lfsck_allow_regenerate_master_lmv (const struct lu_env *env, struct lfsck_component *com, struct dt_object *obj, const struct lu_fid *cfid, __u32 cidx)
Check whether allow to re-genereate the lost master LMV EA.
static int lfsck_namespace_notify_lmv_remote (const struct lu_env *env, struct lfsck_component *com, struct dt_object *obj, __u32 event, __u32 flags, __u32 index)
Notify remote LFSCK instance that the object's LMV EA has been updated.
int lfsck_namespace_notify_lmv_master_local (const struct lu_env *env, struct lfsck_component *com, struct dt_object *obj)
Generate request for local LFSCK instance to rescan the striped directory.
static int lfsck_namespace_set_lmv_master (const struct lu_env *env, struct lfsck_component *com, struct dt_object *obj, struct lmv_mds_md_v1 *lmv, const struct lu_fid *cfid, __u32 cidx, __u32 flags)
Set master LMV EA for the specified striped directory.
int lfsck_namespace_repair_bad_name_hash (const struct lu_env *env, struct lfsck_component *com, struct dt_object *shard, struct lfsck_lmv *llmv, const char *name)
Repair the bad name hash.
int lfsck_namespace_scan_shard (const struct lu_env *env, struct lfsck_component *com, struct dt_object *child)
Scan the shard of a striped directory for name hash verification.
int lfsck_namespace_verify_stripe_slave (const struct lu_env *env, struct lfsck_component *com, struct dt_object *obj, struct lfsck_lmv *llmv)
Verify the slave object's (of striped directory) LMV EA.
int lfsck_namespace_striped_dir_rescan (const struct lu_env *env, struct lfsck_component *com, struct lfsck_namespace_req *lnr)
Double scan the striped directory or the shard.
int lfsck_namespace_handle_striped_master (const struct lu_env *env, struct lfsck_component *com, struct lfsck_namespace_req *lnr)
Verify the shard's name entry under the striped directory.
Define Documentation
#define DEBUG_SUBSYSTEM S_LFSCK
Definition at line 141 of file lfsck_striped_dir.c.
Function Documentation
static int lfsck_allow_regenerate_master_lmv (const struct lu_env * env, struct lfsck_component * com, struct dt_object * obj, const struct lu_fid * cfid, __u32 cidx) [static]
Check whether allow to re-genereate the lost master LMV EA.
If the master MDT-object of the striped directory lost its master LMV EA, then before the LFSCK repaired the striped directory, some ones may have created some objects (that are not normal shards of the striped directory) under the master MDT-object. If such case happend, then the LFSCK cannot re-generate the lost master LMV EA to keep those objects to be visible to client.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] obj pointer to the master MDT-object to be checked
[in] cfid the shard's FID used for verification
[in] cidx the shard's index used for verification
Return values:
positive number if not allow to re-generate LMV EA
zero if allow to re-generate LMV EA
negative error number on failure
Definition at line 1089 of file lfsck_striped_dir.c.
References __u64, DFID, dt_index_operations::dio_it, dt_object::do_index_ops, dt_key, dt_lookup(), dt_try_as_dir(), ENTRY, GOTO, dt_index_operations::dt_it_ops::init, lfsck_component::lc_lfsck, lfsck_env_info(), lfsck_shard_name_to_index(), lfsck_unpack_ent(), lfsck_instance::li_args_dir, lfsck_thread_info::lti_fid3, lfsck_thread_info::lti_key, lfsck_thread_info::lti_tmpbuf, lu_fid_eq(), LUDA_VERIFY, LUDA_VERIFY_DRYRUN, name_is_dot_or_dotdot(), PFID, RETURN, and unlikely.
Referenced by lfsck_namespace_set_lmv_master().
static int lfsck_disable_master_lmv (const struct lu_env * env, struct lfsck_component * com, struct dt_object * obj, bool del_lmv) [static]
Mark the specified directory as read-only by set LUSTRE_IMMUTABLE_FL.
The caller has taken the ldlm lock on the already.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] obj pointer to the object to be handled
[in] del_lmv true if need to drop the LMV EA
Return values:
positive number if nothing to be done
zero for success
negative error number on failure
Definition at line 202 of file lfsck_striped_dir.c.
References CDEBUG, D_LFSCK, DFID, dt_attr_get(), dt_attr_set(), dt_declare_attr_set(), dt_declare_xattr_del(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), dt_xattr_del(), ENTRY, GOTO, lu_attr::la_flags, LA_FLAGS, lu_attr::la_valid, lfsck_bookmark::lb_param, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, LF_INCONSISTENT, lfsck_dto2fid(), lfsck_env_info(), lfsck_is_dead_obj(), lfsck_lfsck2name(), lfsck_obj2dev(), lfsck_instance::li_bookmark_ram, lfsck_namespace::ln_flags, lfsck_namespace::ln_striped_dirs_disabled, LPF_DRYRUN, lfsck_thread_info::lti_la, LUSTRE_IMMUTABLE_FL, PFID, stop, unlikely, and XATTR_NAME_LMV.
Referenced by lfsck_namespace_set_lmv_master(), and lfsck_remove_lmv().
static bool lfsck_is_valid_slave_lmv (struct lmv_mds_md_v1 * lmv) [inline, static]
Definition at line 277 of file lfsck_striped_dir.c.
References LFSCK_LMV_MAX_STRIPES, lmv_mds_md_v1::lmv_hash_type, lmv_is_known_hash_type(), lmv_mds_md_v1::lmv_master_mdt_index, and lmv_mds_md_v1::lmv_stripe_count.
Referenced by lfsck_namespace_check_name(), and lfsck_namespace_verify_stripe_slave().
bool lfsck_is_valid_slave_name_entry (const struct lu_env * env, struct lfsck_lmv * llmv, const char * name, int namelen)
Definition at line 910 of file lfsck_striped_dir.c.
References lfsck_lmv::ll_lmv, lfsck_lmv::ll_lmv_slave, lfsck_lmv::ll_lmv_verified, lmv_mds_md_v1::lmv_hash_type, lmv_mds_md_v1::lmv_master_mdt_index, lmv_name_to_stripe_index(), lmv_mds_md_v1::lmv_stripe_count, and unlikely.
Referenced by lfsck_namespace_assistant_handler_p1(), and lfsck_namespace_scan_shard().
void lfsck_lmv_put (const struct lu_env * env, struct lfsck_lmv * llmv)
Definition at line 155 of file lfsck_striped_dir.c.
References LASSERT, lfsck_object_put(), lfsck_instance::li_lock, list_del(), list_entry, lfsck_lmv::ll_inline, lfsck_lmv::ll_lslr, lfsck_lmv::ll_ref, lfsck_lmv::ll_stripes_allocated, lfsck_lmv_unit::llu_lfsck, lfsck_lmv_unit::llu_link, lfsck_lmv_unit::llu_obj, OBD_FREE_LARGE, and OBD_FREE_PTR.
Referenced by lfsck_close_dir(), lfsck_instance_cleanup(), lfsck_namespace_assistant_req_fini(), lfsck_namespace_notify_lmv_master_local(), lfsck_namespace_release_lmv(), and lfsck_namespace_scan_shard().
int lfsck_namespace_check_name (const struct lu_env * env, struct dt_object * parent, struct dt_object * child, const struct lu_name * cname)
Check whether the given name is a valid entry under the .
If the is a striped directory then the should one shard of the striped directory, its name should be $FID:$index.
If the is a shard of a striped directory, then the name hash should match the MDT, otherwise it is invalid.
Parameters:
[in] env pointer to the thread context
[in] parent the parent directory
[in] child the child object to be checked
[in] cname the name for the in the parent directory
Return values:
positive number for invalid name entry
0 if the name is valid or uncertain
negative error number on failure
Definition at line 948 of file lfsck_striped_dir.c.
References lfsck_dto2fid(), lfsck_env_info(), lfsck_is_valid_slave_lmv(), lfsck_object_type(), lfsck_read_stripe_lmv(), lfsck_shard_name_to_index(), lmv_mds_md_v1::lmv_hash_type, lmv_mds_md_v1::lmv_magic, LMV_MAGIC_STRIPE, lmv_mds_md_v1::lmv_master_mdt_index, lmv_name_to_stripe_index(), lmv_mds_md_v1::lmv_stripe_count, lu_name::ln_name, lu_name::ln_namelen, lfsck_thread_info::lti_lmv, RETURN, and unlikely.
Referenced by lfsck_namespace_double_scan_one(), and lfsck_namespace_dsd_single().
int lfsck_namespace_handle_striped_master (const struct lu_env * env, struct lfsck_component * com, struct lfsck_namespace_req * lnr)
Verify the shard's name entry under the striped directory.
Before all shards of the striped directory scanned, the LFSCK cannot know whether the master LMV EA is valid or not, and also cannot know how to repair an invalid shard exactly. For example, the stripe index stored in the shard's name does not match the stripe index stored in the slave LMV EA, then the LFSCK cannot know which one is correct. If the LFSCK just assumed one is correct, and fixed the other, then as the LFSCK processing, it may find that the former reparation is wrong and have to roll back. Unfortunately, if some applications saw the changes and made further modification based on such changes, then the roll back is almost impossible.
To avoid above trouble, the LFSCK will scan the master object of the striped directory twice, that is NOT the same as normal two-stages scanning, the double scanning the striped directory will happen both during the first-stage scanning:
1) When the striped directory is opened for scanning, the LFSCK will iterate each shard in turn, and records its slave LMV EA in the lfsck_lmv::ll_lslr. In this step, if the 'shard' (may be fake shard) name does not match the shard naming rule, for example, it does not contains the shard's FID, or not contains index, then we can remove the bad name entry directly. But if the name is valid, but the shard has no slave LMV EA or the slave LMV EA does not match its name, then we just record related information in the lfsck_lmv::ll_lslr in RAM.
2) When all the known shards have been scanned, then the engine will generate a dummy request (via lfsck_namespace_close_dir) to tell the assistant thread that all the known shards have been scanned. Since the assistant has got the global knowledge about the index conflict, stripe count, hash type, and so on. Then the assistant thread will scan the lfsck_lmv::ll_lslr, and for every shard in the record, check and repair inconsistency.
Generally, the stripe directory has only several shards, and there will NOT be a lof of striped directory. So double scanning striped directory will not much affect the LFSCK performance.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] lnr pointer to the namespace request that contains the shard's name, parent object, parent's LMV, and ect.
Return values:
zero for success
negative error number on failure
Definition at line 2248 of file lfsck_striped_dir.c.
References CDEBUG, D_LFSCK, DFID, dir, dotdot, dt_object_exists(), ENTRY, GOTO, lfsck_assistant_req::lar_parent, lfsck_bookmark::lb_param, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_assistant_object_load(), lfsck_dev_idx(), lfsck_env_info(), lfsck_find_mdt_idx_by_fid(), lfsck_is_dead_obj(), lfsck_lad_set_bitmap(), lfsck_lfsck2name(), lfsck_ltd2tgt(), lfsck_namespace_check_exist(), lfsck_namespace_repair_dirent(), lfsck_namespace_trace_update(), lfsck_object_find_by_dev_nowait(), lfsck_object_put(), lfsck_object_type(), lfsck_read_stripe_lmv(), lfsck_record_lmv(), lfsck_shard_name_to_index(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_bottom, lfsck_instance::li_mdt_descs, lfsck_lmv::ll_failed, lfsck_lmv::ll_ignore, LMV_MAGIC, lmv_mds_md_v1::lmv_magic, lmv_mds_md_v1::lmv_master_mdt_index, lfsck_namespace::ln_bad_type_repaired, lfsck_namespace::ln_dirent_repaired, lfsck_namespace::ln_items_repaired, LNIT_BAD_DIRENT, LNIT_BAD_TYPE, LNIT_NONE, lfsck_namespace_req::lnr_fid, lfsck_namespace_req::lnr_lar, lfsck_namespace_req::lnr_lmv, lfsck_namespace_req::lnr_name, lfsck_namespace_req::lnr_namelen, lfsck_namespace_req::lnr_type, LNTF_CHECK_PARENT, LPF_FAILOUT, LSLF_BAD_INDEX1, LSLF_DANGLING, LSLF_NO_LMVEA, LSLF_NONE, lfsck_assistant_object::lso_fid, lfsck_tgt_desc::ltd_tgt, lfsck_thread_info::lti_lmv, PFID, RETURN, and unlikely.
Referenced by lfsck_namespace_assistant_handler_p1().
int lfsck_namespace_notify_lmv_master_local (const struct lu_env * env, struct lfsck_component * com, struct dt_object * obj)
Generate request for local LFSCK instance to rescan the striped directory.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] obj pointer to the striped directory to be rescanned
Return values:
positive number if nothing to be done
zero for success
negative error number on failure
Definition at line 1264 of file lfsck_striped_dir.c.
References ENTRY, INIT_LIST_HEAD, lfsck_bookmark::lb_param, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_sem, lfsck_env_info(), LFSCK_LMV_DEF_STRIPES, LFSCK_LMV_MAX_STRIPES, lfsck_lmv_put(), lfsck_object_get(), lfsck_read_stripe_lmv(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_list_lmv, lfsck_instance::li_lock, list_add_tail(), lfsck_lmv::ll_hash_type, lfsck_lmv::ll_inline, lfsck_lmv::ll_lmv, lfsck_lmv::ll_lmv_master, lfsck_lmv::ll_lslr, lfsck_lmv::ll_ref, lfsck_lmv::ll_stripes_allocated, lfsck_lmv_unit::llu_lfsck, lfsck_lmv_unit::llu_link, lfsck_lmv_unit::llu_lmv, lfsck_lmv_unit::llu_obj, LMV_HASH_TYPE_UNKNOWN, lmv_mds_md_v1::lmv_stripe_count, lfsck_namespace::ln_status, lfsck_namespace::ln_striped_dirs_repaired, lfsck_namespace::ln_striped_dirs_skipped, LPF_DRYRUN, LS_SCANNING_PHASE1, LS_SCANNING_PHASE2, lfsck_thread_info::lti_lmv4, OBD_ALLOC_LARGE, OBD_ALLOC_PTR, OBD_FREE_PTR, RETURN, and unlikely.
Referenced by lfsck_namespace_in_notify(), and lfsck_namespace_set_lmv_master().
static int lfsck_namespace_notify_lmv_remote (const struct lu_env * env, struct lfsck_component * com, struct dt_object * obj, __u32 event, __u32 flags, __u32 index) [static]
Notify remote LFSCK instance that the object's LMV EA has been updated.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] obj pointer to the object on which the LMV EA will be set
[in] event indicate either master or slave LMV EA has been updated
[in] flags indicate which element(s) in the LMV EA has been updated
[in] index the MDT index on which the LFSCK instance to be notified
Return values:
positive number if nothing to be done
zero for success
negative error number on failure
Definition at line 1197 of file lfsck_striped_dir.c.
References CDEBUG, class_exp2cliimp(), D_LFSCK, DFID, ENTRY, GOTO, lfsck_component::lc_lfsck, lfsck_dev_idx(), lfsck_dto2fid(), lfsck_env_info(), lfsck_lfsck2name(), LFSCK_NOTIFY, lfsck_tgt_get(), lfsck_tgt_put(), LFSCK_TYPE_NAMESPACE, lfsck_instance::li_mdt_descs, lfsck_request::lr_active, lfsck_request::lr_event, lfsck_request::lr_fid, lfsck_request::lr_flags, lfsck_request::lr_index, lfsck_tgt_desc::ltd_exp, lfsck_thread_info::lti_lr, LUSTRE_OBD_VERSION, PFID, ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), req_capsule_client_get(), RMF_LFSCK_REQUEST, ptlrpc_request::rq_pill, and RQF_LFSCK_NOTIFY.
Referenced by lfsck_namespace_set_lmv_master(), and lfsck_namespace_striped_dir_rescan().
int lfsck_namespace_repair_bad_name_hash (const struct lu_env * env, struct lfsck_component * com, struct dt_object * shard, struct lfsck_lmv * llmv, const char * name)
Repair the bad name hash.
If the name hash of some name entry under the striped directory does not match the shard of the striped directory, then the LFSCK will repair the inconsistency. Ideally, the LFSCK should migrate the name entry from the current MDT to the right MDT (another one), but before the async commit finished, the LFSCK will change the striped directory's hash type as LMV_HASH_TYPE_UNKNOWN and mark the lmv flags as LMV_HASH_FLAG_BAD_TYPE.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] shard pointer to the shard of the striped directory that contains the bad name entry
[in] llmv pointer to lfsck LMV EA structure
[in] name the name of the bad name hash
Return values:
positive number if nothing to be done
zero for success
negative error number on failure
Definition at line 1473 of file lfsck_striped_dir.c.
References CDEBUG, D_LFSCK, DFID, dotdot, dt_key, dt_lookup(), dt_object_exists(), ENTRY, fid_is_sane(), GOTO, lfsck_component::lc_lfsck, LEF_SET_LMV_HASH, lfsck_dev_idx(), lfsck_dto2fid(), lfsck_env_info(), lfsck_lfsck2name(), lfsck_namespace_set_lmv_master(), lfsck_object_find_bottom(), lfsck_object_put(), lfsck_lmv::ll_lmv, LMV_HASH_FLAG_BAD_TYPE, lmv_mds_md_v1::lmv_hash_type, LMV_HASH_TYPE_UNKNOWN, lmv_mds_md_v1::lmv_master_mdt_index, lfsck_thread_info::lti_fid3, lfsck_thread_info::lti_lmv2, PFID, and unlikely.
Referenced by lfsck_namespace_assistant_handler_p1(), and lfsck_namespace_scan_shard().
int lfsck_namespace_scan_shard (const struct lu_env * env, struct lfsck_component * com, struct dt_object * child)
Scan the shard of a striped directory for name hash verification.
During the first-stage scanning, if the LFSCK cannot make sure whether the shard of a stripe directory contains valid slave LMV EA or not, then it will skip the name hash verification for this shard temporarily, and record the shard's FID in the LFSCK tracing file. As the LFSCK processing, the slave LMV EA may has been verified/fixed by LFSCK instance on master. Then in the second-stage scanning, the shard will be re-scanned, and for every name entry under the shard, the name hash will be verified, and for unmatched name entry, the LFSCK will try to fix it.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] child pointer to the directory object to be handled
Return values:
positive number for scanning successfully
zero for the scanning is paused
negative error number on failure
Definition at line 1545 of file lfsck_striped_dir.c.
References __u64, CFS_FAIL_TIMEOUT, cfs_fail_val, dt_index_operations::dio_it, dt_object::do_index_ops, dt_try_as_dir(), ENTRY, GOTO, dt_index_operations::dt_it_ops::init, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, LF_INCONSISTENT, lfsck_control_speed(), lfsck_env_info(), lfsck_is_valid_slave_name_entry(), lfsck_lmv_put(), lfsck_namespace_repair_bad_name_hash(), lfsck_read_stripe_lmv(), lfsck_unpack_ent(), lfsck_instance::li_args_dir, lfsck_instance::li_bookmark_ram, lfsck_instance::li_lock, lfsck_instance::li_thread, lmv_mds_md_v1::lmv_magic, LMV_MAGIC_STRIPE, lfsck_namespace::ln_flags, lfsck_namespace::ln_name_hash_repaired, LPF_FAILOUT, lfsck_thread_info::lti_key, lfsck_thread_info::lti_lmv, LUDA_VERIFY, LUDA_VERIFY_DRYRUN, name_is_dot_or_dotdot(), OBD_ALLOC_PTR, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_DELAY3, OBD_FAIL_LFSCK_FATAL2, RETURN, SVC_STOPPING, thread, thread_is_running(), thread_set_flags(), and unlikely.
Referenced by lfsck_namespace_double_scan_dir().
static int lfsck_namespace_set_lmv_master (const struct lu_env * env, struct lfsck_component * com, struct dt_object * obj, struct lmv_mds_md_v1 * lmv, const struct lu_fid * cfid, __u32 cidx, __u32 flags) [static]
Set master LMV EA for the specified striped directory.
First, if the master MDT-object of a striped directory lost its LMV EA, then there may be some users have created some files under the master MDT-object directly. Under such case, the LFSCK cannot re-generate LMV EA for the master MDT-object, because we should keep the existing files to be visible to client. Then the LFSCK will mark the striped directory as read-only and keep it there to be handled by administrator manually.
If nobody has created files under the master MDT-object of the striped directory, then we will set the master LMV EA and generate a new rescan (the striped directory) request that will be handled later by the LFSCK instance on the MDT later.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] obj pointer to the object on which the LMV EA will be set
[in] lmv pointer to the buffer holding the new LMV EA
[in] cfid the shard's FID used for verification
[in] cidx the shard's index used for verification
[in] flags to indicate which element(s) in the LMV EA will be set
Return values:
positive number if nothing to be done
zero for success
negative error number on failure
Definition at line 1359 of file lfsck_striped_dir.c.
References CDEBUG, D_LFSCK, DFID, dt_object_remote(), ENTRY, fld_range_set_mdt(), fld_server_lookup(), GOTO, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, LCK_EX, LE_SET_LMV_MASTER, LEF_SET_LMV_ALL, LEF_SET_LMV_HASH, LF_INCONSISTENT, lfsck_allow_regenerate_master_lmv(), lfsck_dev_site(), lfsck_disable_master_lmv(), lfsck_dto2fid(), lfsck_env_info(), lfsck_ibits_lock(), lfsck_ibits_unlock(), lfsck_lfsck2name(), lfsck_namespace_notify_lmv_master_local(), lfsck_namespace_notify_lmv_remote(), lfsck_namespace_update_lmv(), lfsck_read_stripe_lmv(), LMV_HASH_FLAG_LOST_LMV, lmv_mds_md_v1::lmv_hash_type, LMV_MAGIC, lmv_mds_md_v1::lmv_magic, lmv_mds_md_v1::lmv_master_mdt_index, lfsck_namespace::ln_flags, lu_seq_range::lsr_index, lfsck_thread_info::lti_lmv3, lfsck_thread_info::lti_range, MDS_INODELOCK_UPDATE, MDS_INODELOCK_XATTR, PFID, and seq_server_site::ss_server_fld.
Referenced by lfsck_namespace_repair_bad_name_hash(), and lfsck_namespace_verify_stripe_slave().
int lfsck_namespace_striped_dir_rescan (const struct lu_env * env, struct lfsck_component * com, struct lfsck_namespace_req * lnr)
Double scan the striped directory or the shard.
All the shards' under the given striped directory or its shard have been scanned, the LFSCK has got the global knownledge about the LMV EA consistency.
If the target is one shard of a striped directory, then only needs to update related tracing file.
If the target is the master MDT-object of a striped directory, then the LFSCK will make the decision about whether the master LMV EA is invalid or not, and repair it if inconsistenct; for every shard of the striped directory, whether the slave LMV EA is invalid or not, and repair it if inconsistent.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] lnr pointer to the namespace request that contains the striped directory or the shard
Return values:
zero for success
negative error number on failure
Definition at line 1817 of file lfsck_striped_dir.c.
References CDEBUG, D_LFSCK, DFID, dir, dt_object_remote(), ENTRY, fid_is_zero(), fld_range_set_mdt(), fld_server_lookup(), GOTO, lfsck_assistant_req::lar_parent, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, LCK_EX, linkea_data::ld_leh, LE_SET_LMV_SLAVE, LEF_RECHECK_NAME_HASH, link_ea_header::leh_reccount, lfsck_assistant_object_load(), lfsck_dev_site(), lfsck_dto2fid(), lfsck_env_info(), lfsck_ibits_lock(), lfsck_ibits_unlock(), lfsck_is_dead_obj(), lfsck_lfsck2name(), lfsck_links_read(), LFSCK_LMV_MAX_STRIPES, lfsck_name_get_const(), lfsck_namespace_notify_lmv_remote(), lfsck_namespace_rebuild_linkea(), lfsck_namespace_repair_dangling(), lfsck_namespace_repair_dirent(), lfsck_namespace_trace_update(), lfsck_namespace_update_lmv(), lfsck_object_find_bottom_nowait(), lfsck_object_put(), linkea_add_buf(), linkea_data_new(), linkea_links_find(), lfsck_lmv::ll_exit_value, lfsck_lmv::ll_failed, lfsck_lmv::ll_hash_type, lfsck_lmv::ll_ignore, lfsck_lmv::ll_inline, lfsck_lmv::ll_lmv, lfsck_lmv::ll_lmv_slave, lfsck_lmv::ll_lmv_updated, lfsck_lmv::ll_lmv_verified, lfsck_lmv::ll_lslr, lfsck_lmv::ll_max_filled_off, lfsck_lmv::ll_max_stripe_count, LMV_HASH_FLAG_BAD_TYPE, lmv_mds_md_v1::lmv_hash_type, LMV_HASH_TYPE_MASK, LMV_HASH_TYPE_UNKNOWN, lmv_is_known_hash_type(), lmv_mds_md_v1::lmv_layout_version, lmv_mds_md_v1::lmv_magic, LMV_MAGIC_STRIPE, lmv_mds_md_v1::lmv_master_mdt_index, lmv_mds_md_v1::lmv_stripe_count, lfsck_namespace::ln_dangling_repaired, lfsck_namespace::ln_dirent_repaired, lfsck_namespace::ln_linkea_repaired, lfsck_namespace::ln_striped_dirs_failed, lfsck_namespace::ln_striped_dirs_repaired, lfsck_namespace::ln_striped_dirs_scanned, lfsck_namespace::ln_striped_shards_failed, lfsck_namespace::ln_striped_shards_repaired, lfsck_namespace::ln_striped_shards_scanned, lfsck_namespace_req::lnr_fid, lfsck_namespace_req::lnr_lar, lfsck_namespace_req::lnr_lmv, lfsck_namespace_req::lnr_name, lfsck_namespace_req::lnr_type, LNTF_RECHECK_NAME_HASH, LNTF_UNCERTAIN_LMV, LSLF_BAD_INDEX1, LSLF_BAD_INDEX2, LSLF_DANGLING, LSLF_NO_LMVEA, LSLF_NONE, lfsck_slave_lmv_rec::lslr_fid, lfsck_slave_lmv_rec::lslr_flags, lfsck_slave_lmv_rec::lslr_hash_type, lfsck_slave_lmv_rec::lslr_index, lfsck_slave_lmv_rec::lslr_stripe_count, lfsck_assistant_object::lso_fid, lu_seq_range::lsr_index, lfsck_thread_info::lti_big_buf, lfsck_thread_info::lti_lmv2, lfsck_thread_info::lti_range, lfsck_thread_info::lti_tmpbuf, lfsck_thread_info::lti_tmpbuf2, max, MDS_INODELOCK_UPDATE, MDS_INODELOCK_XATTR, PFID, RETURN, and seq_server_site::ss_server_fld.
Referenced by lfsck_namespace_assistant_handler_p1().
int lfsck_namespace_update_lmv (const struct lu_env * env, struct lfsck_component * com, struct dt_object * obj, struct lmv_mds_md_v1 * lmv, bool locked)
Update the object's LMV EA with the given .
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] obj pointer to the object which LMV EA will be updated
[in] lmv pointer to buffer holding the new LMV EA
[in] locked whether the caller has held ldlm lock on the or not
Return values:
positive number for nothing to be done
zero if updated successfully
negative error number on failure
Definition at line 993 of file lfsck_striped_dir.c.
References buf, CDEBUG, D_LFSCK, DFID, dt_declare_xattr_set(), dt_object_remote(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), dt_xattr_set(), ENTRY, GOTO, LASSERT, lfsck_bookmark::lb_param, lfsck_component::lc_lfsck, LCK_EX, lfsck_buf_init(), lfsck_dto2fid(), lfsck_env_info(), lfsck_ibits_lock(), lfsck_ibits_unlock(), lfsck_is_dead_obj(), lfsck_lfsck2name(), lfsck_lmv_header_cpu_to_le(), lfsck_obj2dev(), lfsck_instance::li_bookmark_ram, LMV_MAGIC, lmv_mds_md_v1::lmv_magic, LPF_DRYRUN, lfsck_thread_info::lti_buf, lfsck_thread_info::lti_lmv4, MDS_INODELOCK_UPDATE, MDS_INODELOCK_XATTR, PFID, stop, thandle::th_sync, unlikely, and XATTR_NAME_LMV.
Referenced by lfsck_namespace_set_lmv_master(), and lfsck_namespace_striped_dir_rescan().
int lfsck_namespace_verify_stripe_slave (const struct lu_env * env, struct lfsck_component * com, struct dt_object * obj, struct lfsck_lmv * llmv)
Verify the slave object's (of striped directory) LMV EA.
For the slave object of a striped directory, before traversing the shard the LFSCK will verify whether its slave LMV EA matches its parent's master LMV EA or not.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] obj pointer to the object which LMV EA will be checked
[in] llmv pointer to buffer holding the slave LMV EA
Return values:
positive number if nothing to be done
zero for success
negative error number on failure
Definition at line 1672 of file lfsck_striped_dir.c.
References DFID, dotdot, dt_key, dt_lookup(), dt_object_exists(), dt_try_as_dir(), ENTRY, fid_is_sane(), GOTO, lfsck_component::lc_lfsck, LEF_SET_LMV_ALL, lfsck_dto2fid(), lfsck_env_info(), lfsck_is_valid_slave_lmv(), lfsck_links_get_first(), lfsck_namespace_set_lmv_master(), lfsck_namespace_trace_update(), lfsck_object_find_bottom(), lfsck_object_put(), lfsck_read_stripe_lmv(), lfsck_lmv::ll_lmv, lfsck_lmv::ll_lmv_verified, LMV_HASH_FLAG_BAD_TYPE, lmv_mds_md_v1::lmv_hash_type, LMV_HASH_TYPE_MASK, LMV_HASH_TYPE_UNKNOWN, LMV_MAGIC, lmv_mds_md_v1::lmv_magic, lmv_mds_md_v1::lmv_master_mdt_index, lmv_mds_md_v1::lmv_stripe_count, LNTF_UNCERTAIN_LMV, lfsck_thread_info::lti_fid3, lfsck_thread_info::lti_key, lfsck_thread_info::lti_lmv, lfsck_thread_info::lti_tmpbuf2, lu_fid_eq(), name, PFID, and unlikely.
Referenced by lfsck_namespace_open_dir().
int lfsck_read_stripe_lmv (const struct lu_env * env, struct dt_object * obj, struct lmv_mds_md_v1 * lmv)
Definition at line 841 of file lfsck_striped_dir.c.
References dt_read_lock(), dt_read_unlock(), dt_xattr_get(), lfsck_buf_get(), lfsck_lmv_header_le_to_cpu(), LMV_HASH_FLAG_MIGRATION, lmv_mds_md_v1::lmv_hash_type, LMV_MAGIC, lmv_mds_md_v1::lmv_magic, LMV_MAGIC_STRIPE, and XATTR_NAME_LMV.
Referenced by lfsck_load_stripe_lmv(), lfsck_namespace_check_name(), lfsck_namespace_dsd_single(), lfsck_namespace_handle_striped_master(), lfsck_namespace_notify_lmv_master_local(), lfsck_namespace_scan_shard(), lfsck_namespace_set_lmv_master(), and lfsck_namespace_verify_stripe_slave().
static int lfsck_record_lmv (const struct lu_env * env, struct lfsck_component * com, struct dt_object * dir, struct lfsck_namespace_req * lnr, struct lmv_mds_md_v1 * lmv, __u32 shard_idx, __u32 flags, __u32 flags2, __u32 * depth) [static]
Record the slave LMV EA in the lfsck_lmv::ll_lslr.
If the lfsck_lmv::ll_lslr slot corresponding to the given is free, then fill the slot with the given // directly (maybe need to extend the lfsck_lmv::ll_lslr buffer).
If the lfsck_lmv::ll_lslr slot corresponding to the given is taken by other shard, then the LFSCK will try to resolve the conflict by checking the two conflict shards' flags, and try other possible slot (if one of them claims another possible).
1) If one of the two conflict shards can be recorded in another slot, then it is OK, go ahead. Otherwise,
2) If one of them is dangling name entry, then remove (one of) the dangling name entry (and replace related slot if needed). Otherwise,
3) If one of them has no slave LMV EA, then check whether the master LMV EA has ever been lost and re-generated (LMV_HASH_FLAG_LOST_LMV in the master LMV EA).
3.1) If yes, then it is possible that such object is not a real shard of the striped directory, instead, it was created by someone after the master LMV EA lost with the name that matches the shard naming rule. Then the LFSCK will remove the master LMV EA and mark the striped directory as read-only to allow those non-shard files to be visible to client.
3.2) If no, then remove (one of) the object what has no slave LMV EA.
4) If all above efforts cannot work, then the LFSCK cannot know how to recover the striped directory. To make the administrator can see the conflicts, the LFSCK will remove the master LMV EA and mark the striped directory as read-only.
This function may be called recursively, to prevent overflow, we define LFSCK_REC_LMV_MAX_DEPTH to restrict the recursive call depth.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] dir pointer to the striped directory to be handled
[in] lnr contain the shard's FID to fill the slot, it also records the known max filled index and the known max stripe count
[in] lmv pointer to the slave LMV EA to be recorded
[in] shard_idx the shard's index used for locating the slot, it can be the index stored in the shard's name, it also can be the index stored in the slave LMV EA (for recursive case)
[in] flags the shard's flags to be recorded in the slot to indicate the shard status, such as whether has slave LMV EA, whether dangling name entry, whether the name entry and slave LMV EA unmatched, and ect
[in] flags2 when be called recursively, the tells the former conflict shard's flags in the slot.
[in,out] depth To prevent to be called recurisively too deep, we define the max depth can be called recursively (LFSCK_REC_LMV_MAX_DEPTH)
Return values:
zero for success
-ERANGE for invalid
-EEXIST for the required lslr slot has been occupied by other shard
other negative error number on failure
Definition at line 485 of file lfsck_striped_dir.c.
References CDEBUG, D_LFSCK, DFID, ENTRY, fid_is_zero(), GOTO, LASSERTF, lfsck_component::lc_lfsck, lfsck_dto2fid(), lfsck_lfsck2name(), LFSCK_LMV_MAX_STRIPES, lfsck_namespace_trace_update(), LFSCK_REC_LMV_MAX_DEPTH, lfsck_remove_dirent(), lfsck_remove_lmv(), lfsck_replace_lmv(), lfsck_instance::li_rec_lmv_save, lfsck_lmv::ll_failed, lfsck_lmv::ll_hash_type, lfsck_lmv::ll_lmv, lfsck_lmv::ll_lslr, lfsck_lmv::ll_max_filled_off, lfsck_lmv::ll_max_stripe_count, lfsck_lmv::ll_stripes_allocated, lfsck_lmv::ll_stripes_filled, LMV_HASH_FLAG_LOST_LMV, lmv_mds_md_v1::lmv_hash_type, LMV_HASH_TYPE_UNKNOWN, lmv_is_known_hash_type(), lmv_mds_md_v1::lmv_master_mdt_index, lmv_mds_md_v1::lmv_stripe_count, lfsck_namespace_req::lnr_fid, lfsck_namespace_req::lnr_lmv, LNTF_CHECK_PARENT, lfsck_rec_lmv_save::lrls_fid, lfsck_rec_lmv_save::lrls_lmv, LSLF_BAD_INDEX1, LSLF_BAD_INDEX2, LSLF_DANGLING, LSLF_NO_LMVEA, LSLF_NONE, lfsck_slave_lmv_rec::lslr_fid, lfsck_slave_lmv_rec::lslr_flags, lfsck_slave_lmv_rec::lslr_hash_type, lfsck_slave_lmv_rec::lslr_index, lfsck_slave_lmv_rec::lslr_stripe_count, lu_fid_eq(), OBD_ALLOC_LARGE, OBD_FREE_LARGE, PFID, RETURN, and unlikely.
Referenced by lfsck_namespace_handle_striped_master().
static int lfsck_remove_dirent (const struct lu_env * env, struct lfsck_component * com, struct dt_object * dir, const struct lu_fid * fid, __u32 index) [static]
Remove the name entry from the striped directory's master MDT-object.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] dir pointer to the striped directory
[in] fid the shard's FID which name entry will be removed
[in] index the shard's index which name entry will be removed
Return values:
positive number for repaired successfully
0 if nothing to be repaired
negative error number on failure
Definition at line 334 of file lfsck_striped_dir.c.
References DFID, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_env_info(), lfsck_namespace_repair_dirent(), lfsck_object_find_bottom(), lfsck_object_put(), lfsck_namespace::ln_dirent_repaired, lfsck_thread_info::lti_tmpbuf2, and PFID.
Referenced by lfsck_record_lmv(), and lfsck_replace_lmv().
static int lfsck_remove_lmv (const struct lu_env * env, struct lfsck_component * com, struct dt_object * obj, struct lfsck_namespace_req * lnr) [static]
Remove the striped directory's master LMV EA and mark it as read-only.
Take ldlm lock on the striped directory before calling the lfsck_disable_master_lmv().
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] obj pointer to the striped directory to be handled
[in] lnr pointer to the namespace request that contains the striped directory to be handled and other information
Return values:
positive number if nothing to be done
zero for success
negative error number on failure
Definition at line 301 of file lfsck_striped_dir.c.
References lfsck_component::lc_lfsck, LCK_EX, lfsck_disable_master_lmv(), lfsck_ibits_lock(), lfsck_ibits_unlock(), lfsck_lmv::ll_ignore, lfsck_namespace_req::lnr_lmv, MDS_INODELOCK_UPDATE, and MDS_INODELOCK_XATTR.
Referenced by lfsck_record_lmv().
static int lfsck_replace_lmv (const struct lu_env * env, struct lfsck_component * com, struct dt_object * dir, struct lfsck_slave_lmv_rec * lslr, struct lfsck_namespace_req * lnr, struct lmv_mds_md_v1 * lmv, __u32 index, __u32 flags) [static]
Remove old shard's name entry and refill the slot with new shard.
Some old shard held the specified slot, but it is an invalid shard. This function will remove the bad shard's name entry, and refill the slot with the new shard.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] dir pointer to the striped directory to be handled
[in] lslr pointer to lfsck_disable_master_lmv slot which content will be replaced by the given information
[in] lnr contain the shard's FID to be used to fill the slot, it also records the known max filled index and the known max stripe count
[in] lmv contain the slave LMV EA to be used to fill the slot
[in] index the old shard's index in the striped directory
[in] flags the new shard's flags in the slot
Return values:
zero for success
negative error number on failure
Definition at line 385 of file lfsck_striped_dir.c.
References LFSCK_LMV_MAX_STRIPES, lfsck_remove_dirent(), lfsck_lmv::ll_hash_type, lfsck_lmv::ll_max_stripe_count, lmv_mds_md_v1::lmv_hash_type, LMV_HASH_TYPE_UNKNOWN, lmv_is_known_hash_type(), lmv_mds_md_v1::lmv_master_mdt_index, lmv_mds_md_v1::lmv_stripe_count, lfsck_namespace_req::lnr_fid, lfsck_namespace_req::lnr_lmv, LSLF_NONE, lfsck_slave_lmv_rec::lslr_fid, lfsck_slave_lmv_rec::lslr_flags, lfsck_slave_lmv_rec::lslr_hash_type, lfsck_slave_lmv_rec::lslr_index, and lfsck_slave_lmv_rec::lslr_stripe_count.
Referenced by lfsck_record_lmv().
int lfsck_shard_name_to_index (const struct lu_env * env, const char * name, int namelen, __u16 type, const struct lu_fid * fid)
Parse the shard's index from the given shard name.
The valid shard name/type should be: 1) The type must be S_IFDIR 2) The name should be $FID:$index 3) the index should within valid range.
Parameters:
[in] env pointer to the thread context
[in] name the shard name
[in] namelen the name length
[in] type the entry's type
[in] fid the entry's FID
Return values:
zero or positive number for the index from the name
negative error number on failure
Definition at line 880 of file lfsck_striped_dir.c.
References DFID, LASSERT, lfsck_env_info(), LFSCK_LMV_MAX_STRIPES, lfsck_thread_info::lti_tmpbuf2, and PFID.
Referenced by lfsck_allow_regenerate_master_lmv(), lfsck_namespace_check_name(), lfsck_namespace_dsd_single(), lfsck_namespace_handle_striped_master(), and lfsck_namespace_repair_dangling().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.