Lustre: lustre/lfsck/lfsck_layout.c File Reference
lustre/lfsck/lfsck_layout.c File Reference
#include <linux/bitops.h>
#include <linux/rbtree.h>
#include <lustre/lustre_idl.h>
#include <lu_object.h>
#include <dt_object.h>
#include <lustre_fid.h>
#include <lustre_lib.h>
#include <lustre_net.h>
#include <lustre/lustre_user.h>
#include <md_object.h>
#include <obd_class.h>
#include "lfsck_internal.h"
Data Structures
struct lfsck_layout_seq
struct lfsck_layout_slave_target
struct lfsck_layout_slave_data
struct lfsck_layout_slave_async_args
struct lfsck_rbtree_node
struct lfsck_orphan_it
Defines
#define DEBUG_SUBSYSTEM S_LFSCK
#define LFSCK_LAYOUT_MAGIC_V1 0xB173AE14
#define LFSCK_LAYOUT_MAGIC_V2 0xB1734D76
#define LFSCK_LAYOUT_MAGIC LFSCK_LAYOUT_MAGIC_V2
#define LFSCK_RBTREE_BITMAP_SIZE PAGE_CACHE_SIZE
#define LFSCK_RBTREE_BITMAP_WIDTH (LFSCK_RBTREE_BITMAP_SIZE << 3)
#define LFSCK_RBTREE_BITMAP_MASK (LFSCK_RBTREE_BITMAP_WIDTH - 1)
Functions
static void lfsck_layout_llst_put (struct lfsck_layout_slave_target *llst)
static int lfsck_layout_llst_add (struct lfsck_layout_slave_data *llsd, __u32 index)
static void lfsck_layout_llst_del (struct lfsck_layout_slave_data *llsd, struct lfsck_layout_slave_target *llst)
static struct
lfsck_layout_slave_target * lfsck_layout_llst_find_and_del (struct lfsck_layout_slave_data *llsd, __u32 index, bool unlink)
static struct lfsck_layout_req * lfsck_layout_assistant_req_init (struct lfsck_assistant_object *lso, struct dt_object *child, __u32 ost_idx, __u32 lov_idx)
static void lfsck_layout_assistant_req_fini (const struct lu_env *env, struct lfsck_assistant_req *lar)
static int lfsck_layout_assistant_sync_failures_interpret (const struct lu_env *env, struct ptlrpc_request *req, void *args, int rc)
static void lfsck_layout_assistant_sync_failures (const struct lu_env *env, struct lfsck_component *com, struct lfsck_request *lr)
Notify remote LFSCK instances about former failures.
static int lfsck_layout_get_lovea (const struct lu_env *env, struct dt_object *obj, struct lu_buf *buf)
static int lfsck_layout_verify_header (struct lov_mds_md_v1 *lmm)
static int lfsck_rbtree_cmp (struct lfsck_rbtree_node *lrn, __u64 seq, __u32 oid)
static struct lfsck_rbtree_node * lfsck_rbtree_search (struct lfsck_layout_slave_data *llsd, const struct lu_fid *fid, bool *exact)
static struct lfsck_rbtree_node * lfsck_rbtree_new (const struct lu_env *env, const struct lu_fid *fid)
static void lfsck_rbtree_free (struct lfsck_rbtree_node *lrn)
static struct lfsck_rbtree_node * lfsck_rbtree_insert (struct lfsck_layout_slave_data *llsd, struct lfsck_rbtree_node *lrn)
static int lfsck_rbtree_setup (const struct lu_env *env, struct lfsck_component *com)
static void lfsck_rbtree_cleanup (const struct lu_env *env, struct lfsck_component *com)
static void lfsck_rbtree_update_bitmap (const struct lu_env *env, struct lfsck_component *com, const struct lu_fid *fid, bool accessed)
static void lfsck_layout_le_to_cpu (struct lfsck_layout *des, const struct lfsck_layout *src)
static void lfsck_layout_cpu_to_le (struct lfsck_layout *des, const struct lfsck_layout *src)
static int lfsck_layout_load_bitmap (const struct lu_env *env, struct lfsck_component *com)
Load the OST bitmap from the lfsck_layout trace file.
static int lfsck_layout_load (const struct lu_env *env, struct lfsck_component *com)
Load the layout LFSCK trace file from disk.
static int lfsck_layout_store (const struct lu_env *env, struct lfsck_component *com)
Store the layout LFSCK trace file on disk.
static int lfsck_layout_init (const struct lu_env *env, struct lfsck_component *com)
static int fid_is_for_ostobj (const struct lu_env *env, struct lfsck_instance *lfsck, struct dt_object *obj, const struct lu_fid *fid)
static struct lfsck_layout_seq * lfsck_layout_seq_lookup (struct lfsck_layout_slave_data *llsd, __u64 seq)
static void lfsck_layout_seq_insert (struct lfsck_layout_slave_data *llsd, struct lfsck_layout_seq *lls)
static int lfsck_layout_lastid_create (const struct lu_env *env, struct lfsck_instance *lfsck, struct dt_object *obj)
static int lfsck_layout_lastid_reload (const struct lu_env *env, struct lfsck_component *com, struct lfsck_layout_seq *lls)
static int lfsck_layout_lastid_store (const struct lu_env *env, struct lfsck_component *com)
static int lfsck_layout_lastid_load (const struct lu_env *env, struct lfsck_component *com, struct lfsck_layout_seq *lls)
static void lfsck_layout_record_failure (const struct lu_env *env, struct lfsck_instance *lfsck, struct lfsck_layout *lo)
static int lfsck_layout_double_scan_result (const struct lu_env *env, struct lfsck_component *com, int rc)
static int lfsck_layout_trans_stop (const struct lu_env *env, struct dt_device *dev, struct thandle *handle, int result)
static int lfsck_layout_get_def_stripesize (const struct lu_env *env, struct lfsck_instance *lfsck, __u32 *size)
Get the system default stripe size.
static int lfsck_layout_refill_lovea (const struct lu_env *env, struct thandle *handle, struct dt_object *parent, struct lu_fid *cfid, struct lu_buf *buf, struct lov_ost_data_v1 *slot, int fl, __u32 ost_idx)
static int lfsck_layout_extend_lovea (const struct lu_env *env, struct lfsck_instance *lfsck, struct thandle *handle, struct dt_object *parent, struct lu_fid *cfid, struct lu_buf *buf, int fl, __u32 ost_idx, __u32 ea_off, bool reset)
static int __lfsck_layout_update_pfid (const struct lu_env *env, struct dt_object *child, const struct lu_fid *pfid, __u32 offset)
static int lfsck_layout_update_pfid (const struct lu_env *env, struct lfsck_component *com, struct dt_object *parent, struct lu_fid *cfid, struct dt_device *cdev, __u32 ea_off)
static int lfsck_layout_recreate_parent (const struct lu_env *env, struct lfsck_component *com, struct lfsck_tgt_desc *ltd, struct lu_orphan_rec *rec, struct lu_fid *cfid, const char *infix, const char *type, __u32 ea_off)
This function will create the MDT-object with the given (partial) LOV EA.
static int lfsck_layout_master_conditional_destroy (const struct lu_env *env, struct lfsck_component *com, const struct lu_fid *fid, __u32 index)
static int lfsck_layout_slave_conditional_destroy (const struct lu_env *env, struct lfsck_component *com, struct lfsck_request *lr)
static int lfsck_layout_conflict_create (const struct lu_env *env, struct lfsck_component *com, struct lfsck_tgt_desc *ltd, struct lu_orphan_rec *rec, struct dt_object *parent, struct lu_fid *cfid, struct lu_buf *ea_buf, struct lov_ost_data_v1 *slot, __u32 ea_off)
Some OST-object has occupied the specified layout EA slot.
static int lfsck_layout_recreate_lovea (const struct lu_env *env, struct lfsck_component *com, struct lfsck_tgt_desc *ltd, struct lu_orphan_rec *rec, struct dt_object *parent, struct lu_fid *cfid, __u32 ost_idx, __u32 ea_off)
static int lfsck_layout_scan_orphan_one (const struct lu_env *env, struct lfsck_component *com, struct lfsck_tgt_desc *ltd, struct lu_orphan_rec *rec, struct lu_fid *cfid)
static int lfsck_layout_scan_orphan (const struct lu_env *env, struct lfsck_component *com, struct lfsck_tgt_desc *ltd)
static int lfsck_layout_repair_dangling (const struct lu_env *env, struct lfsck_component *com, struct dt_object *parent, struct lfsck_layout_req *llr, struct lu_attr *la)
static int lfsck_layout_repair_unmatched_pair (const struct lu_env *env, struct lfsck_component *com, struct dt_object *parent, struct lfsck_layout_req *llr, struct lu_attr *la)
static int lfsck_layout_repair_multiple_references (const struct lu_env *env, struct lfsck_component *com, struct dt_object *parent, struct lfsck_layout_req *llr, struct lu_attr *la, struct lu_buf *buf)
static int lfsck_layout_repair_owner (const struct lu_env *env, struct lfsck_component *com, struct dt_object *parent, struct lfsck_layout_req *llr, struct lu_attr *pla, const struct lu_attr *cla)
static int lfsck_layout_check_parent (const struct lu_env *env, struct lfsck_component *com, struct lfsck_assistant_object *lso, const struct lu_fid *pfid, const struct lu_fid *cfid, const struct lu_attr *cla, struct lfsck_layout_req *llr, struct lu_buf *lov_ea, __u32 idx)
static int lfsck_layout_assistant_handler_p1 (const struct lu_env *env, struct lfsck_component *com, struct lfsck_assistant_req *lar)
static int lfsck_layout_assistant_handler_p2 (const struct lu_env *env, struct lfsck_component *com)
static int lfsck_layout_slave_async_interpret (const struct lu_env *env, struct ptlrpc_request *req, void *args, int rc)
static int lfsck_layout_async_query (const struct lu_env *env, struct lfsck_component *com, struct obd_export *exp, struct lfsck_layout_slave_target *llst, struct lfsck_request *lr, struct ptlrpc_request_set *set)
static int lfsck_layout_async_notify (const struct lu_env *env, struct obd_export *exp, struct lfsck_request *lr, struct ptlrpc_request_set *set)
static int lfsck_layout_slave_query_master (const struct lu_env *env, struct lfsck_component *com)
static void lfsck_layout_slave_notify_master (const struct lu_env *env, struct lfsck_component *com, enum lfsck_events event, int result)
static int lfsck_layout_master_check_pairs (const struct lu_env *env, struct lfsck_component *com, struct lu_fid *cfid, struct lu_fid *pfid)
static int lfsck_layout_slave_check_pairs (const struct lu_env *env, struct lfsck_component *com, struct lu_fid *cfid, struct lu_fid *pfid)
static int lfsck_layout_slave_repair_pfid (const struct lu_env *env, struct lfsck_component *com, struct lfsck_request *lr)
static void lfsck_layout_slave_quit (const struct lu_env *env, struct lfsck_component *com)
static int lfsck_layout_reset (const struct lu_env *env, struct lfsck_component *com, bool init)
static void lfsck_layout_fail (const struct lu_env *env, struct lfsck_component *com, bool new_checked)
static int lfsck_layout_master_checkpoint (const struct lu_env *env, struct lfsck_component *com, bool init)
static int lfsck_layout_slave_checkpoint (const struct lu_env *env, struct lfsck_component *com, bool init)
static int lfsck_layout_prep (const struct lu_env *env, struct lfsck_component *com, struct lfsck_start *start)
static int lfsck_layout_slave_prep (const struct lu_env *env, struct lfsck_component *com, struct lfsck_start_param *lsp)
static int lfsck_layout_master_prep (const struct lu_env *env, struct lfsck_component *com, struct lfsck_start_param *lsp)
static int lfsck_layout_scan_stripes (const struct lu_env *env, struct lfsck_component *com, struct dt_object *parent, struct lov_mds_md_v1 *lmm)
static int lfsck_layout_master_exec_oit (const struct lu_env *env, struct lfsck_component *com, struct dt_object *obj)
static int lfsck_layout_slave_exec_oit (const struct lu_env *env, struct lfsck_component *com, struct dt_object *obj)
static int lfsck_layout_exec_dir (const struct lu_env *env, struct lfsck_component *com, struct lfsck_assistant_object *lso, struct lu_dirent *ent, __u16 type)
static int lfsck_layout_master_post (const struct lu_env *env, struct lfsck_component *com, int result, bool init)
static int lfsck_layout_slave_post (const struct lu_env *env, struct lfsck_component *com, int result, bool init)
static void lfsck_layout_dump (const struct lu_env *env, struct lfsck_component *com, struct seq_file *m)
static int lfsck_layout_master_double_scan (const struct lu_env *env, struct lfsck_component *com)
static int lfsck_layout_slave_double_scan (const struct lu_env *env, struct lfsck_component *com)
static void lfsck_layout_master_data_release (const struct lu_env *env, struct lfsck_component *com)
static void lfsck_layout_slave_data_release (const struct lu_env *env, struct lfsck_component *com)
static void lfsck_layout_master_quit (const struct lu_env *env, struct lfsck_component *com)
static int lfsck_layout_master_in_notify (const struct lu_env *env, struct lfsck_component *com, struct lfsck_request *lr, struct thandle *th)
static int lfsck_layout_slave_in_notify (const struct lu_env *env, struct lfsck_component *com, struct lfsck_request *lr, struct thandle *th)
static void lfsck_layout_repaired (struct lfsck_layout *lo, __u64 *count)
static int lfsck_layout_query_all (const struct lu_env *env, struct lfsck_component *com, __u32 *mdts_count, __u32 *osts_count, __u64 *repaired)
static int lfsck_layout_query (const struct lu_env *env, struct lfsck_component *com, struct lfsck_request *req, struct lfsck_reply *rep, struct lfsck_query *que, int idx)
static int lfsck_layout_slave_join (const struct lu_env *env, struct lfsck_component *com, struct lfsck_start_param *lsp)
static void lfsck_layout_assistant_fill_pos (const struct lu_env *env, struct lfsck_component *com, struct lfsck_position *pos)
int lfsck_layout_setup (const struct lu_env *env, struct lfsck_instance *lfsck)
static int lfsck_fid_match_idx (const struct lu_env *env, struct lfsck_instance *lfsck, const struct lu_fid *fid, int idx)
static void lfsck_layout_destroy_orphan (const struct lu_env *env, struct dt_object *obj)
static int lfsck_orphan_index_lookup (const struct lu_env *env, struct dt_object *dt, struct dt_rec *rec, const struct dt_key *key)
static int lfsck_orphan_index_declare_insert (const struct lu_env *env, struct dt_object *dt, const struct dt_rec *rec, const struct dt_key *key, struct thandle *handle)
static int lfsck_orphan_index_insert (const struct lu_env *env, struct dt_object *dt, const struct dt_rec *rec, const struct dt_key *key, struct thandle *handle, int ignore_quota)
static int lfsck_orphan_index_declare_delete (const struct lu_env *env, struct dt_object *dt, const struct dt_key *key, struct thandle *handle)
static int lfsck_orphan_index_delete (const struct lu_env *env, struct dt_object *dt, const struct dt_key *key, struct thandle *handle)
static struct dt_it * lfsck_orphan_it_init (const struct lu_env *env, struct dt_object *dt, __u32 attr)
static void lfsck_orphan_it_fini (const struct lu_env *env, struct dt_it *di)
static int lfsck_orphan_it_next (const struct lu_env *env, struct dt_it *di)
static int lfsck_orphan_it_get (const struct lu_env *env, struct dt_it *di, const struct dt_key *key)
static void lfsck_orphan_it_put (const struct lu_env *env, struct dt_it *di)
static struct dt_key * lfsck_orphan_it_key (const struct lu_env *env, const struct dt_it *di)
static int lfsck_orphan_it_key_size (const struct lu_env *env, const struct dt_it *di)
static int lfsck_orphan_it_rec (const struct lu_env *env, const struct dt_it *di, struct dt_rec *rec, __u32 attr)
static __u64 lfsck_orphan_it_store (const struct lu_env *env, const struct dt_it *di)
static int lfsck_orphan_it_load (const struct lu_env *env, const struct dt_it *di, __u64 hash)
static int lfsck_orphan_it_key_rec (const struct lu_env *env, const struct dt_it *di, void *key_rec)
Variables
struct dt_index_operations lfsck_orphan_index_ops
static struct lfsck_operations lfsck_layout_master_ops
static struct lfsck_operations lfsck_layout_slave_ops
struct lfsck_assistant_operations lfsck_layout_assistant_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_LFSCK
Definition at line 34 of file lfsck_layout.c.
#define LFSCK_LAYOUT_MAGIC LFSCK_LAYOUT_MAGIC_V2
Definition at line 54 of file lfsck_layout.c.
Referenced by lfsck_layout_init(), lfsck_layout_load(), and lfsck_layout_reset().
#define LFSCK_LAYOUT_MAGIC_V1 0xB173AE14
Definition at line 51 of file lfsck_layout.c.
#define LFSCK_LAYOUT_MAGIC_V2 0xB1734D76
Definition at line 52 of file lfsck_layout.c.
#define LFSCK_RBTREE_BITMAP_MASK (LFSCK_RBTREE_BITMAP_WIDTH - 1)
Definition at line 402 of file lfsck_layout.c.
Referenced by lfsck_rbtree_new(), and lfsck_rbtree_update_bitmap().
#define LFSCK_RBTREE_BITMAP_SIZE PAGE_CACHE_SIZE
Definition at line 400 of file lfsck_layout.c.
Referenced by lfsck_rbtree_free(), and lfsck_rbtree_new().
#define LFSCK_RBTREE_BITMAP_WIDTH (LFSCK_RBTREE_BITMAP_SIZE << 3)
Definition at line 401 of file lfsck_layout.c.
Referenced by lfsck_orphan_it_next(), and lfsck_rbtree_cmp().
Function Documentation
static int __lfsck_layout_update_pfid (const struct lu_env * env, struct dt_object * child, const struct lu_fid * pfid, __u32 offset) [static]
Definition at line 1576 of file lfsck_layout.c.
References cpu_to_le32, cpu_to_le64, dt_declare_xattr_set(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_xattr_set(), lu_fid::f_oid, lu_fid::f_seq, filter_fid::ff_parent, GOTO, lfsck_buf_init(), lfsck_env_info(), lfsck_obj2dev(), lfsck_thread_info::lti_new_pfid, RETURN, stop, and XATTR_NAME_FID.
Referenced by lfsck_layout_recreate_parent(), lfsck_layout_slave_repair_pfid(), and lfsck_layout_update_pfid().
static int fid_is_for_ostobj (const struct lu_env * env, struct lfsck_instance * lfsck, struct dt_object * obj, const struct lu_fid * fid) [static]
Definition at line 973 of file lfsck_layout.c.
References dt_xattr_get(), fld_range_is_ost(), fld_range_set_any(), fld_server_lookup(), lfsck_buf_get(), lfsck_dev_site(), lfsck_env_info(), lustre_mdt_attrs::lma_compat, LMAC_FID_ON_OST, lfsck_thread_info::lti_lma, lfsck_thread_info::lti_range, LU_BUF_NULL, lustre_lma_swab(), seq_server_site::ss_server_fld, XATTR_NAME_FID, and XATTR_NAME_LMA.
Referenced by lfsck_layout_slave_exec_oit().
static int lfsck_fid_match_idx (const struct lu_env * env, struct lfsck_instance * lfsck, const struct lu_fid * fid, int idx) [static]
Definition at line 5696 of file lfsck_layout.c.
References fid_is_norm(), fld_range_is_mdt(), fld_range_set_any(), fld_server_lookup(), LASSERT, lfsck_dev_site(), lfsck_env_info(), lu_seq_range::lsr_index, lfsck_thread_info::lti_range, seq_server_site::ss_server_fld, and unlikely.
Referenced by lfsck_orphan_it_next().
static void lfsck_layout_assistant_fill_pos (const struct lu_env * env, struct lfsck_component * com, struct lfsck_position * pos) [static]
Definition at line 5531 of file lfsck_layout.c.
References lfsck_assistant_data::lad_req_list, lfsck_assistant_req::lar_list, lfsck_assistant_req::lar_parent, lfsck_component::lc_data, list_empty(), list_entry, llr, lfsck_layout_req::llr_lar, lfsck_position::lp_oit_cookie, lfsck_assistant_object::lso_oit_cookie, and list_head::next.
static int lfsck_layout_assistant_handler_p1 (const struct lu_env * env, struct lfsck_component * com, struct lfsck_assistant_req * lar) [static]
Definition at line 3225 of file lfsck_layout.c.
References CDEBUG, CFS_FAIL_TIMEOUT, cfs_fail_val, D_LFSCK, dt_index_operations::dio_it, dt_object::do_index_ops, dt_object::do_lu, dt_attr_get(), dt_xattr_get(), ENTRY, lu_fid::f_ver, filter_fid_old::ff_parent, fid_le_to_cpu(), GOTO, lu_attr::la_gid, lu_attr::la_uid, lfsck_assistant_data::lad_exit, lfsck_assistant_req::lar_parent, LASSERTF, lfsck_bookmark::lb_param, lfsck_component::lc_data, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_sem, lfsck_assistant_object_load(), lfsck_buf_init(), lfsck_env_info(), lfsck_lad_set_bitmap(), lfsck_layout_check_parent(), lfsck_layout_record_failure(), lfsck_layout_repair_dangling(), lfsck_layout_repair_multiple_references(), lfsck_layout_repair_owner(), lfsck_layout_repair_unmatched_pair(), lfsck_lfsck2name(), lfsck_object_put(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_di_oit, lfsck_instance::li_obj_oit, lfsck_layout::ll_objs_repaired, lfsck_layout::ll_objs_skipped, lfsck_layout::ll_pos_first_inconsistent, LLIT_DANGLING, LLIT_INCONSISTENT_OWNER, LLIT_MAX, LLIT_MULTIPLE_REFERENCED, LLIT_NONE, LLIT_UNMATCHED_PAIR, llr, lfsck_layout_req::llr_child, lfsck_layout_req::llr_lar, lfsck_layout_req::llr_ost_idx, LPF_DRYRUN, lfsck_assistant_object::lso_attr, lfsck_assistant_object::lso_dead, lfsck_thread_info::lti_fid, lfsck_thread_info::lti_la, lfsck_thread_info::lti_old_pfid, lu_object_fid(), OBD_FAIL_LFSCK_ASSISTANT_DIRECT, RETURN, dt_index_operations::dt_it_ops::store, unlikely, and XATTR_NAME_FID.
static int lfsck_layout_assistant_handler_p2 (const struct lu_env * env, struct lfsck_component * com) [static]
Definition at line 3390 of file lfsck_layout.c.
References CDEBUG, D_LFSCK, ENTRY, lfsck_assistant_data::lad_exit, lfsck_assistant_data::lad_ost_phase1_list, lfsck_assistant_data::lad_ost_phase2_list, lfsck_bookmark::lb_param, lfsck_component::lc_data, lfsck_component::lc_lfsck, lfsck_layout_scan_orphan(), lfsck_lfsck2name(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_ost_descs, lfsck_instance::li_thread, list_del_init(), list_empty(), list_entry, LPF_ALL_TGT, LPF_FAILOUT, lfsck_tgt_desc::ltd_layout_phase_list, lfsck_tgt_descs::ltd_lock, list_head::next, RETURN, thread_is_running(), and unlikely.
static void lfsck_layout_assistant_req_fini (const struct lu_env * env, struct lfsck_assistant_req * lar) [static]
Definition at line 202 of file lfsck_layout.c.
References lfsck_assistant_req::lar_parent, lfsck_assistant_object_put(), lfsck_object_put(), llr, lfsck_layout_req::llr_child, lfsck_layout_req::llr_lar, and OBD_FREE_PTR.
Referenced by lfsck_layout_scan_stripes().
static struct lfsck_layout_req* lfsck_layout_assistant_req_init (struct lfsck_assistant_object * lso, struct dt_object * child, __u32 ost_idx, __u32 lov_idx) [static, read]
Definition at line 183 of file lfsck_layout.c.
References INIT_LIST_HEAD, lfsck_assistant_req::lar_list, lfsck_assistant_req::lar_parent, lfsck_assistant_object_get(), llr, lfsck_layout_req::llr_child, lfsck_layout_req::llr_lar, lfsck_layout_req::llr_lov_idx, lfsck_layout_req::llr_ost_idx, and OBD_ALLOC_PTR.
Referenced by lfsck_layout_scan_stripes().
static void lfsck_layout_assistant_sync_failures (const struct lu_env * env, struct lfsck_component * com, struct lfsck_request * lr) [static]
Notify remote LFSCK instances about former failures.
The local LFSCK instance has recorded which OSTs have ever failed to respond some LFSCK verification requests (maybe because of network issues or the OST itself trouble). During the respond gap, the OST may missed some OST-objects verification, then the OST cannot know whether related OST-objects have been referenced by related MDT-objects or not, then in the second-stage scanning, these OST-objects will be regarded as orphan, if the OST-object contains bad parent FID for back reference, then it will misguide the LFSCK to make wrong fixing for the fake orphan.
To avoid above trouble, when layout LFSCK finishes the first-stage scanning, it will scan the bitmap for the ever failed OSTs, and notify them that they have ever missed some OST-object verification and should skip the handling for orphan OST-objects on all MDTs that are in the layout LFSCK.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] lr pointer to the lfsck request
Definition at line 250 of file lfsck_layout.c.
References CDEBUG, cfs_foreach_bit, D_LFSCK, ENTRY, GOTO, lfsck_assistant_data::lad_bitmap, lfsck_assistant_data::lad_incomplete, lfsck_assistant_data::lad_name, lfsck_async_interpret_args::laia_count, lfsck_async_interpret_args::laia_ltd, LASSERT, lfsck_component::lc_data, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, LF_INCOMPLETE, lfsck_async_request(), lfsck_env_info(), lfsck_layout_assistant_sync_failures_interpret(), lfsck_lfsck2name(), lfsck_ltd2tgt(), LFSCK_NOTIFY, lfsck_instance::li_ost_descs, lfsck_layout::ll_flags, lfsck_request::lr_flags2, lfsck_tgt_desc::ltd_exp, lfsck_tgt_desc::ltd_index, lfsck_tgt_descs::ltd_rw_sem, lfsck_thread_info::lti_laia2, ptlrpc_prep_set(), ptlrpc_set_destroy(), ptlrpc_set_wait(), and RETURN_EXIT.
static int lfsck_layout_assistant_sync_failures_interpret (const struct lu_env * env, struct ptlrpc_request * req, void * args, int rc) [static]
Definition at line 214 of file lfsck_layout.c.
References lfsck_async_interpret_args::laia_count, lfsck_async_interpret_args::laia_ltd, and lfsck_tgt_desc::ltd_synced_failures.
Referenced by lfsck_layout_assistant_sync_failures().
static int lfsck_layout_async_notify (const struct lu_env * env, struct obd_export * exp, struct lfsck_request * lr, struct ptlrpc_request_set * set) [static]
Definition at line 3525 of file lfsck_layout.c.
References class_exp2cliimp(), ENTRY, LFSCK_NOTIFY, LUSTRE_OBD_VERSION, ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), ptlrpc_set_add_req(), req_capsule_client_get(), RETURN, RMF_LFSCK_REQUEST, ptlrpc_request::rq_allow_intr, ptlrpc_request::rq_pill, and RQF_LFSCK_NOTIFY.
Referenced by lfsck_layout_slave_notify_master().
static int lfsck_layout_async_query (const struct lu_env * env, struct lfsck_component * com, struct obd_export * exp, struct lfsck_layout_slave_target * llst, struct lfsck_request * lr, struct ptlrpc_request_set * set) [static]
Definition at line 3487 of file lfsck_layout.c.
References class_exp2cliimp(), ENTRY, lfsck_component_get(), lfsck_layout_slave_async_interpret(), LFSCK_QUERY, lfsck_layout_slave_async_args::llsaa_com, lfsck_layout_slave_async_args::llsaa_exp, lfsck_layout_slave_async_args::llsaa_llst, LUSTRE_OBD_VERSION, ptlrpc_req_async_args, ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), ptlrpc_set_add_req(), req_capsule_client_get(), RETURN, RMF_LFSCK_REQUEST, ptlrpc_request::rq_allow_intr, ptlrpc_request::rq_pill, and RQF_LFSCK_QUERY.
Referenced by lfsck_layout_slave_query_master().
static int lfsck_layout_check_parent (const struct lu_env * env, struct lfsck_component * com, struct lfsck_assistant_object * lso, const struct lu_fid * pfid, const struct lu_fid * cfid, const struct lu_attr * cla, struct lfsck_layout_req * llr, struct lu_buf * lov_ea, __u32 idx) [static]
Definition at line 3085 of file lfsck_layout.c.
References buf, CDEBUG, D_LFSCK, DFID, dt_object_exists(), dt_object_remote(), dt_read_lock(), dt_read_unlock(), dt_xattr_get(), ENTRY, fid_is_sane(), GOTO, lov_ost_data_v1::l_ost_idx, lov_ost_data_v1::l_ost_oi, LASSERT, lu_buf::lb_buf, lfsck_component::lc_lfsck, LCK_EX, le16_to_cpu, le32_to_cpu, lfsck_env_info(), lfsck_ibits_lock(), lfsck_ibits_unlock(), lfsck_is_dead_obj(), lfsck_layout_get_lovea(), lfsck_lfsck2name(), lfsck_object_find_bottom(), lfsck_object_put(), lfsck_object_type(), likely, LLIT_MULTIPLE_REFERENCED, LLIT_UNMATCHED_PAIR, lfsck_layout_req::llr_lov_idx, lov_mds_md_v1::lmm_magic, lov_mds_md_v1::lmm_objects, lov_mds_md_v1::lmm_stripe_count, LOV_MAGIC_V1, LOV_MAGIC_V3, lovea_slot_is_dummy(), lfsck_assistant_object::lso_fid, lfsck_thread_info::lti_big_buf, lfsck_thread_info::lti_fid2, lfsck_thread_info::lti_oi, LU_BUF_NULL, lu_fid_eq(), lustre_handle_is_used(), MDS_INODELOCK_LAYOUT, MDS_INODELOCK_UPDATE, MDS_INODELOCK_XATTR, ost_id::oi, ostid_le_to_cpu(), ostid_to_fid(), PFID, RETURN, unlikely, and XATTR_NAME_DUMMY.
Referenced by lfsck_layout_assistant_handler_p1().
static int lfsck_layout_conflict_create (const struct lu_env * env, struct lfsck_component * com, struct lfsck_tgt_desc * ltd, struct lu_orphan_rec * rec, struct dt_object * parent, struct lu_fid * cfid, struct lu_buf * ea_buf, struct lov_ost_data_v1 * slot, __u32 ea_off) [static]
Some OST-object has occupied the specified layout EA slot.
Such OST-object may be generated by the LFSCK when repair dangling referenced MDT-object, which can be indicated by attr::la_ctime == 0 but without S_ISUID in la_mode. If it is true and such OST-object has not been modified yet, we will replace it with the orphan OST-object; otherwise the LFSCK will create new MDT-object to reference the orphan.
Return values:
+1,: repaired
0,: did nothing
-ve,: on error
Definition at line 2071 of file lfsck_layout.c.
References CDEBUG, cpu_to_le16, D_LFSCK, DFID, dt_object::do_lu, dt_declare_xattr_set(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), ENTRY, fid_zero(), GOTO, lov_ost_data_v1::l_ost_idx, lov_ost_data_v1::l_ost_oi, lu_buf::lb_buf, lfsck_component::lc_lfsck, LCK_EX, le16_to_cpu, le32_to_cpu, lfsck_dto2fid(), lfsck_env_info(), lfsck_ibits_lock(), lfsck_ibits_unlock(), lfsck_layout_master_conditional_destroy(), lfsck_layout_recreate_parent(), lfsck_layout_refill_lovea(), lfsck_lfsck2name(), lfsck_obj2dev(), lov_mds_md_v1::lmm_layout_gen, lu_orphan_rec::lor_fid, lfsck_tgt_desc::ltd_index, lfsck_thread_info::lti_fid2, lfsck_thread_info::lti_oi, lfsck_thread_info::lti_tmpbuf, lu_object_fid(), LU_XATTR_REPLACE, MDS_INODELOCK_LAYOUT, MDS_INODELOCK_XATTR, ost_id::oi, ostid_le_to_cpu(), ostid_to_fid(), PFID, RETURN, stop, and XATTR_NAME_LOV.
Referenced by lfsck_layout_recreate_lovea().
static void lfsck_layout_cpu_to_le (struct lfsck_layout * des, const struct lfsck_layout * src) [static]
Definition at line 721 of file lfsck_layout.c.
References cpu_to_le32, cpu_to_le64, lfsck_layout::ll_bitmap_size, lfsck_layout::ll_flags, lfsck_layout::ll_magic, lfsck_layout::ll_objs_checked_phase1, lfsck_layout::ll_objs_checked_phase2, lfsck_layout::ll_objs_failed_phase1, lfsck_layout::ll_objs_failed_phase2, lfsck_layout::ll_objs_repaired, lfsck_layout::ll_objs_skipped, lfsck_layout::ll_pos_first_inconsistent, lfsck_layout::ll_pos_last_checkpoint, lfsck_layout::ll_pos_latest_start, lfsck_layout::ll_run_time_phase1, lfsck_layout::ll_run_time_phase2, lfsck_layout::ll_status, lfsck_layout::ll_success_count, lfsck_layout::ll_time_last_checkpoint, lfsck_layout::ll_time_last_complete, lfsck_layout::ll_time_latest_start, and LLIT_MAX.
Referenced by lfsck_layout_store().
static void lfsck_layout_destroy_orphan (const struct lu_env * env, struct dt_object * obj) [static]
Definition at line 5734 of file lfsck_layout.c.
References CDEBUG, D_LFSCK, DFID, dt_declare_destroy(), dt_declare_ref_del(), dt_destroy(), dt_ref_del(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), ENTRY, GOTO, lfsck_dto2fid(), lfsck_obj2dev(), PFID, RETURN_EXIT, and stop.
Referenced by lfsck_orphan_it_next().
static int lfsck_layout_double_scan_result (const struct lu_env * env, struct lfsck_component * com, int rc) [static]
Definition at line 1332 of file lfsck_layout.c.
References cfs_duration_sec(), cfs_time_current(), cfs_time_current_sec(), HALF_SEC, lfsck_assistant_data::lad_incomplete, lfsck_bookmark::lb_param, lfsck_component::lc_data, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_new_checked, lfsck_component::lc_sem, lfsck_component::lc_time_last_checkpoint, LF_INCOMPLETE, LF_INCONSISTENT, LF_SCANNED_ONCE, lfsck_layout_store(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_master, lfsck_instance::li_status, lfsck_layout::ll_flags, lfsck_layout::ll_objs_checked_phase2, lfsck_layout::ll_run_time_phase2, lfsck_layout::ll_status, lfsck_layout::ll_success_count, lfsck_layout::ll_time_last_checkpoint, lfsck_layout::ll_time_last_complete, LPF_DRYRUN, LS_COMPLETED, LS_FAILED, LS_PARTIAL, and LS_STOPPED.
Referenced by lfsck_layout_slave_double_scan().
static void lfsck_layout_dump (const struct lu_env * env, struct lfsck_component * com, struct seq_file * m) [static]
Definition at line 4750 of file lfsck_layout.c.
References __u64, cfs_duration_sec(), cfs_time_current(), DFID, dt_index_operations::dio_it, dt_object::do_index_ops, HALF_SEC, LASSERT, lfsck_bookmark::lb_param, lfsck_bookmark::lb_version, lfsck_component::lc_fid_latest_scanned_phase2, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_new_checked, lfsck_component::lc_sem, lfsck_component::lc_time_last_checkpoint, lfsck_bits_dump(), lfsck_flags_names, lfsck_param_names, lfsck_status2name(), lfsck_time_dump(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_current_oit_processed, lfsck_instance::li_di_oit, lfsck_instance::li_obj_oit, lfsck_instance::li_time_last_checkpoint, lfsck_layout::ll_flags, lfsck_layout::ll_magic, lfsck_layout::ll_objs_checked_phase1, lfsck_layout::ll_objs_checked_phase2, lfsck_layout::ll_objs_failed_phase1, lfsck_layout::ll_objs_failed_phase2, lfsck_layout::ll_objs_repaired, lfsck_layout::ll_objs_skipped, lfsck_layout::ll_pos_first_inconsistent, lfsck_layout::ll_pos_last_checkpoint, lfsck_layout::ll_pos_latest_start, lfsck_layout::ll_run_time_phase1, lfsck_layout::ll_run_time_phase2, lfsck_layout::ll_status, lfsck_layout::ll_success_count, lfsck_layout::ll_time_last_checkpoint, lfsck_layout::ll_time_last_complete, lfsck_layout::ll_time_latest_start, LLIT_DANGLING, LLIT_INCONSISTENT_OWNER, LLIT_MULTIPLE_REFERENCED, LLIT_ORPHAN, LLIT_OTHERS, LLIT_UNMATCHED_PAIR, LPU64, LS_SCANNING_PHASE1, LS_SCANNING_PHASE2, PFID, and dt_index_operations::dt_it_ops::store.
static int lfsck_layout_exec_dir (const struct lu_env * env, struct lfsck_component * com, struct lfsck_assistant_object * lso, struct lu_dirent * ent, __u16 type) [static]
Definition at line 4617 of file lfsck_layout.c.
static int lfsck_layout_extend_lovea (const struct lu_env * env, struct lfsck_instance * lfsck, struct thandle * handle, struct dt_object * parent, struct lu_fid * cfid, struct lu_buf * buf, int fl, __u32 ost_idx, __u32 ea_off, bool reset) [static]
Return values:
+1,: repaired
0,: did nothing
-ve,: on error
Definition at line 1497 of file lfsck_layout.c.
References CDEBUG, cpu_to_le16, cpu_to_le32, D_LFSCK, DFID, ENTRY, fid_to_lmm_oi(), LASSERT, lu_buf::lb_buf, lu_buf::lb_len, le16_to_cpu, le32_to_cpu, lfsck_dto2fid(), lfsck_layout_get_def_stripesize(), lfsck_layout_refill_lovea(), lfsck_lfsck2name(), lov_mds_md_v1::lmm_layout_gen, lov_mds_md_v1::lmm_magic, lov_mds_md_v3::lmm_objects, lov_mds_md_v1::lmm_objects, lov_mds_md_v1::lmm_oi, lmm_oi_cpu_to_le(), lov_mds_md_v1::lmm_pattern, lov_mds_md_v1::lmm_stripe_count, lov_mds_md_v1::lmm_stripe_size, LOV_MAGIC_V1, lov_mds_md_size(), LOV_PATTERN_F_HOLE, LOV_PATTERN_RAID0, LU_XATTR_CREATE, PFID, and RETURN.
Referenced by lfsck_layout_recreate_lovea(), and lfsck_layout_recreate_parent().
static void lfsck_layout_fail (const struct lu_env * env, struct lfsck_component * com, bool new_checked) [static]
Definition at line 3932 of file lfsck_layout.c.
References lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_new_checked, lfsck_component::lc_sem, and lfsck_layout_record_failure().
static int lfsck_layout_get_def_stripesize (const struct lu_env * env, struct lfsck_instance * lfsck, __u32 * size) [static]
Get the system default stripe size.
Parameters:
[in] env pointer to the thread context
[in] lfsck pointer to the lfsck instance
[out] size pointer to the default stripe size
Return values:
0 for success
negative error number on failure
Definition at line 1407 of file lfsck_layout.c.
References dt_locate(), dt_xattr_get(), lfsck_buf_get(), lfsck_env_info(), lfsck_object_put(), lfsck_instance::li_local_root_fid, lfsck_instance::li_next, lov_user_md, lfsck_thread_info::lti_lum, unlikely, and XATTR_NAME_LOV.
Referenced by lfsck_layout_extend_lovea().
static int lfsck_layout_get_lovea (const struct lu_env * env, struct dt_object * obj, struct lu_buf * buf) [static]
Definition at line 323 of file lfsck_layout.c.
References dt_xattr_get(), lu_buf::lb_buf, lu_buf_alloc(), LU_BUF_NULL, lu_buf_realloc(), unlikely, and XATTR_NAME_LOV.
Referenced by lfsck_layout_check_parent(), lfsck_layout_master_check_pairs(), and lfsck_layout_master_exec_oit().
static int lfsck_layout_init (const struct lu_env * env, struct lfsck_component * com) [static]
Definition at line 957 of file lfsck_layout.c.
References lfsck_component::lc_file_ram, lfsck_component::lc_file_size, lfsck_component::lc_sem, LFSCK_LAYOUT_MAGIC, lfsck_layout_store(), lfsck_layout::ll_magic, lfsck_layout::ll_status, and LS_INIT.
Referenced by lfsck_layout_setup().
static int lfsck_layout_lastid_create (const struct lu_env * env, struct lfsck_instance * lfsck, struct dt_object * obj) [static]
Definition at line 1038 of file lfsck_layout.c.
References __u64, CDEBUG, D_LFSCK, dt_object_format::dof_type, dt_create(), dt_declare_create(), dt_declare_record_write(), dt_mode_to_dft(), dt_object_exists(), dt_record_write(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), ENTRY, GOTO, LA_GID, LA_MODE, lu_attr::la_mode, LA_UID, lu_attr::la_valid, lfsck_bookmark::lb_param, lfsck_buf_get(), lfsck_dto2fid(), lfsck_env_info(), lfsck_lfsck2name(), lfsck_obj2dev(), lfsck_instance::li_bookmark_ram, likely, LPF_DRYRUN, LPX64, lfsck_thread_info::lti_dof, lfsck_thread_info::lti_la, and stop.
Referenced by lfsck_layout_lastid_load().
static int lfsck_layout_lastid_load (const struct lu_env * env, struct lfsck_component * com, struct lfsck_layout_seq * lls) [static]
Definition at line 1222 of file lfsck_layout.c.
References __u64, CDEBUG, cfs_fail_val, cfs_time_seconds(), D_LFSCK, dt_locate(), dt_object_exists(), dt_read(), dt_read_lock(), dt_read_unlock(), ENTRY, GOTO, l_wait_event, LASSERT, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_sem, le64_to_cpu, LE_LASTID_REBUILDING, LF_CRASHED_LASTID, lfsck_buf_get(), lfsck_dev_idx(), lfsck_env_info(), lfsck_layout_lastid_create(), lfsck_lfsck2name(), lfsck_object_put(), lfsck_instance::li_bottom, lfsck_instance::li_out_notify, lfsck_instance::li_out_notify_data, lfsck_instance::li_thread, likely, lfsck_layout::ll_flags, lfsck_layout_seq::lls_lastid, lfsck_layout_seq::lls_lastid_obj, lfsck_layout_seq::lls_seq, LPX64, lfsck_thread_info::lti_fid, lu_last_id_fid(), l_wait_info::lwi_timeout, LWI_TIMEOUT, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_DELAY4, RETURN, ptlrpc_thread::t_ctl_waitq, thread, and thread_is_running().
Referenced by lfsck_layout_slave_exec_oit().
static int lfsck_layout_lastid_reload (const struct lu_env * env, struct lfsck_component * com, struct lfsck_layout_seq * lls) [static]
Definition at line 1105 of file lfsck_layout.c.
References __u64, CDEBUG, D_LFSCK, dt_read_lock(), dt_read_unlock(), dt_record_read(), LASSERT, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, le64_to_cpu, LE_LASTID_REBUILDING, LF_CRASHED_LASTID, lfsck_buf_get(), lfsck_lfsck2name(), lfsck_instance::li_out_notify, lfsck_instance::li_out_notify_data, lfsck_layout::ll_flags, lfsck_layout_seq::lls_dirty, lfsck_layout_seq::lls_lastid, lfsck_layout_seq::lls_lastid_known, lfsck_layout_seq::lls_lastid_obj, lfsck_layout_seq::lls_seq, LPU64, LPX64, and unlikely.
Referenced by lfsck_layout_slave_exec_oit().
static int lfsck_layout_lastid_store (const struct lu_env * env, struct lfsck_component * com) [static]
Definition at line 1149 of file lfsck_layout.c.
References __u64, CDEBUG, cpu_to_le64, D_LFSCK, dt_declare_record_write(), dt_record_write(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), lfsck_bookmark::lb_param, lfsck_component::lc_data, lfsck_component::lc_lfsck, lfsck_buf_get(), lfsck_lfsck2name(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_bottom, list_for_each_entry, lfsck_layout_seq::lls_dirty, lfsck_layout_seq::lls_lastid, lfsck_layout_seq::lls_lastid_obj, lfsck_layout_seq::lls_seq, lfsck_layout_slave_data::llsd_seq_list, LPF_DRYRUN, LPU64, LPX64, and stop.
Referenced by lfsck_layout_slave_post().
static void lfsck_layout_le_to_cpu (struct lfsck_layout * des, const struct lfsck_layout * src) [static]
Definition at line 691 of file lfsck_layout.c.
References le32_to_cpu, le64_to_cpu, lfsck_layout::ll_bitmap_size, lfsck_layout::ll_flags, lfsck_layout::ll_magic, lfsck_layout::ll_objs_checked_phase1, lfsck_layout::ll_objs_checked_phase2, lfsck_layout::ll_objs_failed_phase1, lfsck_layout::ll_objs_failed_phase2, lfsck_layout::ll_objs_repaired, lfsck_layout::ll_objs_skipped, lfsck_layout::ll_pos_first_inconsistent, lfsck_layout::ll_pos_last_checkpoint, lfsck_layout::ll_pos_latest_start, lfsck_layout::ll_run_time_phase1, lfsck_layout::ll_run_time_phase2, lfsck_layout::ll_status, lfsck_layout::ll_success_count, lfsck_layout::ll_time_last_checkpoint, lfsck_layout::ll_time_last_complete, lfsck_layout::ll_time_latest_start, and LLIT_MAX.
Referenced by lfsck_layout_load().
static int lfsck_layout_llst_add (struct lfsck_layout_slave_data * llsd, __u32 index) [inline, static]
Definition at line 110 of file lfsck_layout.c.
References INIT_LIST_HEAD, list_add_tail(), list_for_each_entry, lfsck_layout_slave_data::llsd_lock, lfsck_layout_slave_data::llsd_master_list, lfsck_layout_slave_target::llst_gen, lfsck_layout_slave_target::llst_index, lfsck_layout_slave_target::llst_list, lfsck_layout_slave_target::llst_ref, OBD_ALLOC_PTR, and OBD_FREE_PTR.
Referenced by lfsck_layout_slave_join(), and lfsck_layout_slave_prep().
static void lfsck_layout_llst_del (struct lfsck_layout_slave_data * llsd, struct lfsck_layout_slave_target * llst) [inline, static]
Definition at line 143 of file lfsck_layout.c.
References lfsck_layout_llst_put(), list_del_init(), list_empty(), lfsck_layout_slave_data::llsd_lock, and lfsck_layout_slave_target::llst_list.
Referenced by lfsck_layout_slave_async_interpret(), lfsck_layout_slave_notify_master(), and lfsck_layout_slave_query_master().
static struct lfsck_layout_slave_target* lfsck_layout_llst_find_and_del (struct lfsck_layout_slave_data * llsd, __u32 index, bool unlink) [static, read]
Definition at line 160 of file lfsck_layout.c.
References list_del_init(), list_for_each_entry, lfsck_layout_slave_data::llsd_lock, lfsck_layout_slave_data::llsd_master_list, lfsck_layout_slave_target::llst_index, lfsck_layout_slave_target::llst_list, and lfsck_layout_slave_target::llst_ref.
Referenced by lfsck_layout_slave_in_notify(), lfsck_layout_slave_join(), and lfsck_orphan_it_init().
static void lfsck_layout_llst_put (struct lfsck_layout_slave_target * llst) [inline, static]
Definition at line 100 of file lfsck_layout.c.
References LASSERT, list_empty(), lfsck_layout_slave_target::llst_list, lfsck_layout_slave_target::llst_ref, and OBD_FREE_PTR.
Referenced by lfsck_layout_llst_del(), lfsck_layout_slave_async_interpret(), lfsck_layout_slave_in_notify(), lfsck_layout_slave_join(), lfsck_layout_slave_notify_master(), lfsck_layout_slave_query_master(), lfsck_layout_slave_quit(), and lfsck_orphan_it_fini().
static int lfsck_layout_load (const struct lu_env * env, struct lfsck_component * com) [static]
Load the layout LFSCK trace file from disk.
The layout LFSCK trace file records the layout LFSCK status information and other statistics, such as how many objects have been scanned, and how many objects have been repaired, and etc. It also contains the bitmap for failed OSTs during the layout LFSCK. All these information will be loaded from disk to RAM when the layout LFSCK component setup.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
Return values:
positive number for file data corruption, the caller should reset the layout LFSCK trace file
0 for success
negative error number on failure
Definition at line 835 of file lfsck_layout.c.
References CDEBUG, D_LFSCK, dt_read(), lfsck_component::lc_file_disk, lfsck_component::lc_file_ram, lfsck_component::lc_file_size, lfsck_component::lc_lfsck, lfsck_component::lc_obj, lfsck_buf_get(), lfsck_layout_le_to_cpu(), LFSCK_LAYOUT_MAGIC, lfsck_lfsck2name(), lfsck_layout::ll_magic, and size.
Referenced by lfsck_layout_setup().
static int lfsck_layout_load_bitmap (const struct lu_env * env, struct lfsck_component * com) [static]
Load the OST bitmap from the lfsck_layout trace file.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
Return values:
0 for success
negative error number on failure or data corruption
Definition at line 760 of file lfsck_layout.c.
References CFS_ALLOCATE_BITMAP(), cfs_bitmap_check_empty(), CFS_FREE_BITMAP, CFS_RESET_BITMAP(), cfs_bitmap::data, dt_read(), ENTRY, lfsck_assistant_data::lad_bitmap, lfsck_assistant_data::lad_incomplete, lfsck_component::lc_data, lfsck_component::lc_file_ram, lfsck_component::lc_file_size, lfsck_component::lc_lfsck, lfsck_component::lc_obj, lfsck_buf_get(), lfsck_instance::li_ost_descs, lfsck_layout::ll_bitmap_size, lfsck_tgt_descs::ltd_tgts_bitmap, RETURN, cfs_bitmap::size, size, and unlikely.
Referenced by lfsck_layout_master_prep().
static int lfsck_layout_master_check_pairs (const struct lu_env * env, struct lfsck_component * com, struct lu_fid * cfid, struct lu_fid * pfid) [static]
Definition at line 3704 of file lfsck_layout.c.
References buf, dt_object_exists(), dt_read_lock(), dt_read_unlock(), ENTRY, lu_fid::f_ver, fid_to_ostid(), GOTO, lov_ost_data_v1::l_ost_oi, LASSERT, lu_buf::lb_buf, lfsck_component::lc_lfsck, le16_to_cpu, le32_to_cpu, lfsck_env_info(), lfsck_is_dead_obj(), lfsck_layout_get_lovea(), lfsck_layout_verify_header(), lfsck_object_find_bottom(), lfsck_object_put(), lfsck_object_type(), lov_mds_md_v1::lmm_magic, lov_mds_md_v1::lmm_objects, lov_mds_md_v1::lmm_stripe_count, LOV_MAGIC_V1, LOV_MAGIC_V3, lfsck_thread_info::lti_big_buf, lfsck_thread_info::lti_oi, ost_id::oi, ostid_le_to_cpu(), RETURN, and unlikely.
Referenced by lfsck_layout_master_in_notify().
static int lfsck_layout_master_checkpoint (const struct lu_env * env, struct lfsck_component * com, bool init) [static]
Definition at line 3944 of file lfsck_layout.c.
References CDEBUG, cfs_duration_sec(), cfs_time_current(), cfs_time_current_sec(), D_LFSCK, HALF_SEC, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_new_checked, lfsck_component::lc_sem, lfsck_checkpoint_generic(), lfsck_layout_store(), lfsck_lfsck2name(), lfsck_instance::li_pos_checkpoint, lfsck_instance::li_pos_current, lfsck_instance::li_time_last_checkpoint, lfsck_layout::ll_objs_checked_phase1, lfsck_layout::ll_pos_last_checkpoint, lfsck_layout::ll_pos_latest_start, lfsck_layout::ll_run_time_phase1, lfsck_layout::ll_status, lfsck_layout::ll_time_last_checkpoint, lfsck_position::lp_oit_cookie, and LPU64.
static int lfsck_layout_master_conditional_destroy (const struct lu_env * env, struct lfsck_component * com, const struct lu_fid * fid, __u32 index) [static]
Definition at line 1900 of file lfsck_layout.c.
References class_exp2cliimp(), ENTRY, exp_connect_flags(), GOTO, lfsck_component::lc_lfsck, LE_CONDITIONAL_DESTROY, lfsck_env_info(), LFSCK_NOTIFY, lfsck_tgt_get(), lfsck_tgt_put(), LFSCK_TYPE_LAYOUT, lfsck_instance::li_ost_descs, lfsck_request::lr_active, lfsck_request::lr_event, lfsck_request::lr_fid, lfsck_tgt_desc::ltd_exp, lfsck_thread_info::lti_lr, LUSTRE_OBD_VERSION, OBD_CONNECT_LFSCK, ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), req_capsule_client_get(), RETURN, RMF_LFSCK_REQUEST, ptlrpc_request::rq_pill, RQF_LFSCK_NOTIFY, and unlikely.
Referenced by lfsck_layout_conflict_create().
static void lfsck_layout_master_data_release (const struct lu_env * env, struct lfsck_component * com) [static]
Definition at line 5023 of file lfsck_layout.c.
References CFS_FREE_BITMAP, lfsck_assistant_data::lad_bitmap, lfsck_assistant_data::lad_mdt_list, lfsck_assistant_data::lad_mdt_phase1_list, lfsck_assistant_data::lad_mdt_phase2_list, lfsck_assistant_data::lad_ost_list, lfsck_assistant_data::lad_ost_phase1_list, lfsck_assistant_data::lad_ost_phase2_list, lfsck_assistant_data::lad_req_list, lfsck_assistant_data::lad_thread, LASSERT, lfsck_component::lc_data, lfsck_component::lc_lfsck, lfsck_instance::li_mdt_descs, lfsck_instance::li_ost_descs, likely, list_del_init(), list_empty(), list_for_each_entry_safe, lfsck_tgt_desc::ltd_layout_list, lfsck_tgt_desc::ltd_layout_phase_list, lfsck_tgt_descs::ltd_lock, OBD_FREE_PTR, thread_is_init(), and thread_is_stopped().
static int lfsck_layout_master_double_scan (const struct lu_env * env, struct lfsck_component * com) [static]
Definition at line 4912 of file lfsck_layout.c.
References lfsck_assistant_data::lad_mdt_phase1_list, lfsck_assistant_data::lad_mdt_phase2_list, lfsck_assistant_data::lad_ost_phase1_list, lfsck_assistant_data::lad_ost_phase2_list, lfsck_assistant_data::lad_req_list, lfsck_assistant_data::lad_thread, LASSERT, lfsck_component::lc_data, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_double_scan_generic(), lfsck_instance::li_mdt_descs, lfsck_instance::li_ost_descs, list_del_init(), list_empty(), list_for_each_entry_safe, lfsck_layout::ll_status, lfsck_tgt_desc::ltd_layout_phase_list, lfsck_tgt_descs::ltd_lock, and thread_is_stopped().
static int lfsck_layout_master_exec_oit (const struct lu_env * env, struct lfsck_component * com, struct dt_object * obj) [static]
Definition at line 4370 of file lfsck_layout.c.
References buf, CDEBUG, D_LFSCK, DFID, dt_declare_xattr_set(), dt_object_exists(), dt_read_lock(), dt_read_unlock(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), dt_xattr_set(), ENTRY, fid_to_lmm_oi(), GOTO, lfsck_assistant_data::lad_assistant_status, lu_buf::lb_buf, lfsck_bookmark::lb_param, lfsck_component::lc_data, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_new_checked, lfsck_component::lc_sem, LCK_EX, lfsck_buf_init(), lfsck_dto2fid(), lfsck_env_info(), lfsck_ibits_lock(), lfsck_ibits_unlock(), lfsck_is_dead_obj(), lfsck_layout_get_lovea(), lfsck_layout_record_failure(), lfsck_layout_scan_stripes(), lfsck_layout_verify_header(), lfsck_lfsck2name(), lfsck_obj2dev(), lfsck_object_type(), lfsck_instance::li_bookmark_ram, lfsck_layout::ll_objs_repaired, LLIT_OTHERS, lov_mds_md_v1::lmm_oi, lmm_oi_cpu_to_le(), LPF_DRYRUN, lfsck_thread_info::lti_big_buf, lfsck_thread_info::lti_oi, LU_XATTR_REPLACE, lustre_handle_is_used(), MDS_INODELOCK_LAYOUT, MDS_INODELOCK_XATTR, ost_id::oi, PFID, size, and XATTR_NAME_LOV.
static int lfsck_layout_master_in_notify (const struct lu_env * env, struct lfsck_component * com, struct lfsck_request * lr, struct thandle * th) [static]
Definition at line 5162 of file lfsck_layout.c.
References CDEBUG, D_LFSCK, ENTRY, lfsck_assistant_data::lad_mdt_list, lfsck_assistant_data::lad_mdt_phase2_list, lfsck_assistant_data::lad_ost_list, lfsck_assistant_data::lad_ost_phase2_list, lfsck_assistant_data::lad_thread, lfsck_bookmark::lb_param, lfsck_component::lc_data, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, LE_PAIRS_VERIFY, LE_PEER_EXIT, LE_PHASE1_DONE, LE_PHASE2_DONE, LEF_FROM_OST, LF_INCOMPLETE, lfsck_env_info(), lfsck_lad_set_bitmap(), lfsck_layout_master_check_pairs(), lfsck_lfsck2name(), lfsck_ltd2tgt(), lfsck_phase2_next_ready(), lfsck_stop(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_bottom, lfsck_instance::li_mdt_descs, lfsck_instance::li_ost_descs, list_add_tail(), list_del_init(), list_empty(), lfsck_layout::ll_flags, LPF_BROADCAST, LPF_FAILOUT, lfsck_request::lr_event, lfsck_request::lr_fid, lfsck_request::lr_fid2, lfsck_request::lr_flags, lfsck_request::lr_flags2, lfsck_request::lr_index, lfsck_request::lr_param, lfsck_request::lr_status, lfsck_stop::ls_flags, lfsck_stop::ls_status, lfsck_tgt_desc::ltd_index, lfsck_tgt_desc::ltd_layout_done, lfsck_tgt_desc::ltd_layout_list, lfsck_tgt_desc::ltd_layout_phase_list, lfsck_tgt_descs::ltd_lock, lfsck_thread_info::lti_stop, RETURN, stop, and ptlrpc_thread::t_ctl_waitq.
static int lfsck_layout_master_post (const struct lu_env * env, struct lfsck_component * com, int result, bool init) [static]
Definition at line 4625 of file lfsck_layout.c.
References CDEBUG, cfs_duration_sec(), cfs_time_current(), cfs_time_current_sec(), D_LFSCK, ENTRY, HALF_SEC, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_link, lfsck_component::lc_new_checked, lfsck_component::lc_sem, LF_INCOMPLETE, LF_SCANNED_ONCE, LF_UPGRADE, lfsck_layout_store(), lfsck_lfsck2name(), lfsck_post_generic(), lfsck_instance::li_list_double_scan, lfsck_instance::li_list_idle, lfsck_instance::li_lock, lfsck_instance::li_pos_checkpoint, lfsck_instance::li_status, lfsck_instance::li_time_last_checkpoint, list_move_tail(), lfsck_layout::ll_flags, lfsck_layout::ll_objs_checked_phase1, lfsck_layout::ll_pos_last_checkpoint, lfsck_layout::ll_run_time_phase1, lfsck_layout::ll_status, lfsck_layout::ll_time_last_checkpoint, lfsck_position::lp_oit_cookie, LS_FAILED, LS_PARTIAL, LS_PAUSED, LS_SCANNING_PHASE2, LS_STOPPED, and RETURN.
static int lfsck_layout_master_prep (const struct lu_env * env, struct lfsck_component * com, struct lfsck_start_param * lsp) [static]
Definition at line 4124 of file lfsck_layout.c.
References CDEBUG, D_LFSCK, ENTRY, GOTO, lfsck_component::lc_lfsck, lfsck_component::lc_pos_start, lfsck_layout_load_bitmap(), lfsck_layout_prep(), lfsck_layout_reset(), lfsck_lfsck2name(), lfsck_set_param(), lfsck_start_assistant(), lfsck_position::lp_oit_cookie, LPU64, lfsck_start_param::lsp_start, and RETURN.
static void lfsck_layout_master_quit (const struct lu_env * env, struct lfsck_component * com) [static]
Definition at line 5087 of file lfsck_layout.c.
References lfsck_assistant_data::lad_mdt_phase1_list, lfsck_assistant_data::lad_mdt_phase2_list, lfsck_assistant_data::lad_ost_phase1_list, lfsck_assistant_data::lad_ost_phase2_list, lfsck_assistant_data::lad_req_list, lfsck_assistant_data::lad_thread, LASSERT, lfsck_component::lc_data, lfsck_component::lc_lfsck, lfsck_quit_generic(), lfsck_instance::li_mdt_descs, lfsck_instance::li_ost_descs, list_del_init(), list_empty(), list_for_each_entry_safe, lfsck_tgt_desc::ltd_layout_phase_list, lfsck_tgt_descs::ltd_lock, thread_is_init(), and thread_is_stopped().
static int lfsck_layout_prep (const struct lu_env * env, struct lfsck_component * com, struct lfsck_start * start) [static]
Definition at line 4015 of file lfsck_layout.c.
References CDEBUG, cfs_time_current_sec(), D_LFSCK, fid_zero(), lfsck_component::lc_fid_latest_scanned_phase2, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_link, lfsck_component::lc_pos_start, lfsck_component::lc_sem, LF_SCANNED_ONCE, lfsck_layout_reset(), lfsck_lfsck2name(), lfsck_set_param(), lfsck_instance::li_drop_dryrun, lfsck_instance::li_list_double_scan, lfsck_instance::li_lock, list_move_tail(), lfsck_layout::ll_flags, lfsck_layout::ll_objs_checked_phase1, lfsck_layout::ll_objs_checked_phase2, lfsck_layout::ll_objs_failed_phase1, lfsck_layout::ll_objs_failed_phase2, lfsck_layout::ll_objs_repaired, lfsck_layout::ll_pos_first_inconsistent, lfsck_layout::ll_pos_last_checkpoint, lfsck_layout::ll_run_time_phase1, lfsck_layout::ll_run_time_phase2, lfsck_layout::ll_status, lfsck_layout::ll_time_latest_start, LLIT_MAX, lfsck_position::lp_dir_cookie, lfsck_position::lp_dir_parent, lfsck_position::lp_oit_cookie, LPF_OST_ORPHAN, LS_COMPLETED, lfsck_start::ls_flags, LS_PARTIAL, LS_SCANNING_PHASE1, and LS_SCANNING_PHASE2.
Referenced by lfsck_layout_master_prep(), and lfsck_layout_slave_prep().
static int lfsck_layout_query (const struct lu_env * env, struct lfsck_component * com, struct lfsck_request * req, struct lfsck_reply * rep, struct lfsck_query * que, int idx) [static]
Definition at line 5431 of file lfsck_layout.c.
References LASSERT, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_sem, LEF_QUERY_ALL, lfsck_layout_query_all(), lfsck_layout_repaired(), lfsck_instance::li_master, lfsck_layout::ll_status, lfsck_request::lr_flags, lfsck_reply::lr_repaired, lfsck_reply::lr_status, lfsck_query::lu_mdts_count, lfsck_query::lu_osts_count, and lfsck_query::lu_repaired.
static int lfsck_layout_query_all (const struct lu_env * env, struct lfsck_component * com, __u32 * mdts_count, __u32 * osts_count, __u64 * repaired) [static]
Definition at line 5385 of file lfsck_layout.c.
References cfs_foreach_bit, ENTRY, LASSERT, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_sem, lfsck_layout_repaired(), lfsck_ltd2tgt(), lfsck_query_all(), lfsck_instance::li_mdt_descs, lfsck_instance::li_ost_descs, lfsck_layout::ll_status, lfsck_tgt_desc::ltd_layout_repaired, lfsck_tgt_desc::ltd_layout_status, lfsck_tgt_descs::ltd_rw_sem, lfsck_tgt_descs::ltd_tgts_bitmap, and RETURN.
Referenced by lfsck_layout_query().
static void lfsck_layout_record_failure (const struct lu_env * env, struct lfsck_instance * lfsck, struct lfsck_layout * lo) [static]
Definition at line 1312 of file lfsck_layout.c.
References __u64, CDEBUG, D_LFSCK, dt_index_operations::dio_it, dt_object::do_index_ops, lfsck_lfsck2name(), lfsck_instance::li_di_oit, lfsck_instance::li_obj_oit, lfsck_layout::ll_objs_failed_phase1, lfsck_layout::ll_pos_first_inconsistent, LPU64, and dt_index_operations::dt_it_ops::store.
Referenced by lfsck_layout_assistant_handler_p1(), lfsck_layout_fail(), lfsck_layout_master_exec_oit(), and lfsck_layout_scan_stripes().
static int lfsck_layout_recreate_lovea (const struct lu_env * env, struct lfsck_component * com, struct lfsck_tgt_desc * ltd, struct lu_orphan_rec * rec, struct dt_object * parent, struct lu_fid * cfid, __u32 ost_idx, __u32 ea_off) [static]
Return values:
+1,: repaired
0,: did nothing
-ve,: on error
Definition at line 2169 of file lfsck_layout.c.
References buf, CDEBUG, cpu_to_le16, D_LFSCK, DFID, dt_declare_xattr_set(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), dt_xattr_get(), ENTRY, GOTO, lov_ost_data_v1::l_ost_idx, lov_ost_data_v1::l_ost_oi, LASSERT, LASSERTF, lu_buf::lb_buf, lu_buf::lb_len, lfsck_bookmark::lb_param, lfsck_component::lc_lfsck, LCK_EX, le16_to_cpu, le32_to_cpu, lfsck_dto2fid(), lfsck_env_info(), lfsck_ibits_lock(), lfsck_ibits_unlock(), lfsck_layout_conflict_create(), lfsck_layout_extend_lovea(), lfsck_layout_refill_lovea(), lfsck_layout_update_pfid(), lfsck_layout_verify_header(), lfsck_lfsck2name(), lfsck_obj2dev(), lfsck_instance::li_bookmark_ram, lov_mds_md_v1::lmm_layout_gen, lov_mds_md_v1::lmm_magic, lov_mds_md_v1::lmm_objects, lov_mds_md_v1::lmm_stripe_count, LOV_MAGIC_V1, LOV_MAGIC_V3, lov_mds_md_size(), lovea_slot_is_dummy(), LPF_DRYRUN, lfsck_tgt_desc::ltd_index, lfsck_tgt_desc::ltd_tgt, lfsck_thread_info::lti_big_buf, lfsck_thread_info::lti_fid2, lfsck_thread_info::lti_oi, LU_BUF_NULL, lu_buf_realloc(), lu_fid_eq(), LU_XATTR_CREATE, LU_XATTR_REPLACE, MDS_INODELOCK_LAYOUT, MDS_INODELOCK_XATTR, ost_id::oi, ostid_le_to_cpu(), ostid_to_fid(), PFID, RETURN, stop, unlikely, and XATTR_NAME_LOV.
Referenced by lfsck_layout_scan_orphan_one().
static int lfsck_layout_recreate_parent (const struct lu_env * env, struct lfsck_component * com, struct lfsck_tgt_desc * ltd, struct lu_orphan_rec * rec, struct lu_fid * cfid, const char * infix, const char * type, __u32 ea_off) [static]
This function will create the MDT-object with the given (partial) LOV EA.
Under some data corruption cases, the MDT-object of the file may be lost, but its OST-objects, or some of them are there. The layout LFSCK needs to re-create the MDT-object with the orphan OST-object(s) information.
On the other hand, the LFSCK may has created some OST-object for repairing dangling LOV EA reference, but as the LFSCK processing, it may find that the old OST-object is there and should replace the former new created OST object. Unfortunately, some others have modified such newly created object. To keep the data (both new and old), the LFSCK will create MDT-object with new FID to reference the original OST-object.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] ltd pointer to target device descriptor
[in] rec pointer to the record for the orphan OST-object
[in] cfid pointer to FID for the orphan OST-object
[in] infix additional information, such as the FID for original MDT-object and the stripe offset in the LOV EA
[in] type the type for describing why the orphan MDT-object is created. The rules are as following:
type "C": Multiple OST-objects claim the same MDT-object and the same slot in the layout EA. Then the LFSCK will create new MDT-object(s) to hold the conflict OST-object(s).
type "N": The orphan OST-object does not know which one was the real parent MDT-object, so the LFSCK uses new FID for its parent MDT-object.
type "R": The orphan OST-object knows its parent MDT-object FID, but does not know the position (the file name) in the layout.
type "D": The MDT-object is a directory, it may knows its parent but because there is no valid linkEA, the LFSCK cannot know where to put it back to the namespace. type "O": The MDT-object has no linkEA, and there is no name entry that references the MDT-object.
type "P": The orphan object to be created was a parent directory of some MDT-object which linkEA shows that the object is missing.
The orphan name will be like: ${FID}-${infix}-${type}-${conflict_version}
Parameters:
[in] ea_off the stripe offset in the LOV EA
Return values:
positive on repaired something
0 if needs to repair nothing
negative error number on failure
Definition at line 1697 of file lfsck_layout.c.
References __lfsck_layout_update_pfid(), CDEBUG, D_LFSCK, DFID, dt_object_format::dof_type, dt_create(), dt_declare_create(), dt_declare_insert(), dt_declare_xattr_set(), dt_insert(), dt_key, dt_lookup(), dt_mode_to_dft(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), dt_xattr_set(), ENTRY, fid_is_zero(), GOTO, LA_GID, lu_attr::la_gid, LA_MODE, lu_attr::la_mode, LA_UID, lu_attr::la_uid, lu_attr::la_valid, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lfsck_component::lc_lfsck, LCK_PW, linkea_data::ld_buf, linkea_data::ld_leh, link_ea_header::leh_len, lfsck_buf_init(), lfsck_dto2fid(), lfsck_env_info(), lfsck_fid_alloc(), lfsck_layout_extend_lovea(), lfsck_lfsck2name(), lfsck_lock(), lfsck_name_get_const(), lfsck_object_find_by_dev(), lfsck_object_put(), lfsck_unlock(), lfsck_instance::li_bottom, lfsck_instance::li_lpf_obj, linkea_add_buf(), linkea_data_new(), lu_orphan_rec::lor_fid, lu_orphan_rec::lor_gid, lu_orphan_rec::lor_uid, LOV_MAGIC_V1, lov_mds_md_size(), lfsck_tgt_desc::ltd_index, lfsck_tgt_desc::ltd_tgt, lfsck_thread_info::lti_big_buf, lfsck_thread_info::lti_dof, lfsck_thread_info::lti_dt_rec, lfsck_thread_info::lti_fid3, lfsck_thread_info::lti_key, lfsck_thread_info::lti_la2, lfsck_thread_info::lti_llh, lu_buf_realloc(), LU_XATTR_REPLACE, MDS_INODELOCK_UPDATE, name, PFID, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, size, stop, unlikely, XATTR_NAME_LINK, and XATTR_NAME_LOV.
Referenced by lfsck_layout_conflict_create(), and lfsck_layout_scan_orphan_one().
static int lfsck_layout_refill_lovea (const struct lu_env * env, struct thandle * handle, struct dt_object * parent, struct lu_fid * cfid, struct lu_buf * buf, struct lov_ost_data_v1 * slot, int fl, __u32 ost_idx) [static]
Return values:
+1,: repaired
0,: did nothing
-ve,: on error
Definition at line 1441 of file lfsck_layout.c.
References cpu_to_le32, dt_xattr_set(), ENTRY, fid_to_ostid(), lov_ost_data_v1::l_ost_gen, lov_ost_data_v1::l_ost_idx, lov_ost_data_v1::l_ost_oi, lu_buf::lb_buf, le16_to_cpu, le32_to_cpu, lfsck_buf_init(), lfsck_env_info(), lov_mds_md_v1::lmm_magic, lov_mds_md_v1::lmm_objects, lov_mds_md_v1::lmm_pattern, lov_mds_md_v1::lmm_stripe_count, LOV_MAGIC_V1, lov_mds_md_size(), LOV_PATTERN_F_HOLE, lovea_slot_is_dummy(), lfsck_thread_info::lti_oi, ost_id::oi, ostid_cpu_to_le(), RETURN, and XATTR_NAME_LOV.
Referenced by lfsck_layout_conflict_create(), lfsck_layout_extend_lovea(), and lfsck_layout_recreate_lovea().
static int lfsck_layout_repair_dangling (const struct lu_env * env, struct lfsck_component * com, struct dt_object * parent, struct lfsck_layout_req * llr, struct lu_attr * la) [static]
Definition at line 2625 of file lfsck_layout.c.
References buf, CDEBUG, cpu_to_le32, cpu_to_le64, D_LFSCK, DFID, dt_object::do_lu, dt_attr_get(), dt_create(), dt_declare_create(), dt_declare_xattr_set(), dt_read_lock(), dt_read_unlock(), dt_trans_create(), dt_trans_start_local(), dt_xattr_set(), ENTRY, lu_fid::f_oid, lu_fid::f_seq, filter_fid::ff_parent, GOTO, LA_ATIME, lu_attr::la_atime, LA_CTIME, lu_attr::la_ctime, lu_attr::la_gid, LA_GID, LA_MODE, lu_attr::la_mode, LA_MTIME, lu_attr::la_mtime, LA_TYPE, lu_attr::la_uid, LA_UID, lu_attr::la_valid, lfsck_bookmark::lb_param, lfsck_component::lc_lfsck, LCK_EX, lfsck_buf_get(), lfsck_dto2fid(), lfsck_env_info(), lfsck_ibits_lock(), lfsck_ibits_unlock(), lfsck_is_dead_obj(), lfsck_layout_trans_stop(), lfsck_lfsck2name(), lfsck_obj2dev(), lfsck_instance::li_bookmark_ram, lfsck_layout_req::llr_child, lfsck_layout_req::llr_lov_idx, lfsck_layout_req::llr_ost_idx, LPF_CREATE_OSTOBJ, lfsck_thread_info::lti_dof, lfsck_thread_info::lti_new_pfid, lu_object_fid(), LU_XATTR_CREATE, MDS_INODELOCK_LAYOUT, MDS_INODELOCK_XATTR, PFID, stop, unlikely, and XATTR_NAME_FID.
Referenced by lfsck_layout_assistant_handler_p1().
static int lfsck_layout_repair_multiple_references (const struct lu_env * env, struct lfsck_component * com, struct dt_object * parent, struct lfsck_layout_req * llr, struct lu_attr * la, struct lu_buf * buf) [static]
Definition at line 2829 of file lfsck_layout.c.
References CDEBUG, cpu_to_le16, cpu_to_le32, D_LFSCK, dt_device::dd_lu_dev, DFID, dt_object::do_lu, dt_attr_get(), dt_create(), dt_declare_create(), dt_declare_xattr_set(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), dt_xattr_get(), dt_xattr_set(), ENTRY, fid_to_ostid(), GOTO, lov_ost_data_v1::l_ost_gen, lov_ost_data_v1::l_ost_idx, lov_ost_data_v1::l_ost_oi, lu_attr::la_gid, LA_GID, lu_attr::la_uid, LA_UID, lu_attr::la_valid, LASSERT, lu_buf::lb_buf, lfsck_component::lc_lfsck, LCK_EX, lu_device::ld_type, le16_to_cpu, le32_to_cpu, lfsck_buf_init(), lfsck_dto2fid(), lfsck_env_info(), lfsck_ibits_lock(), lfsck_ibits_unlock(), lfsck_is_dead_obj(), lfsck_lfsck2name(), lfsck_obj2dev(), lfsck_object_locate(), lfsck_object_put(), lfsck_instance::li_next, lfsck_layout_req::llr_child, lfsck_layout_req::llr_lov_idx, lfsck_layout_req::llr_ost_idx, lov_mds_md_v1::lmm_layout_gen, lov_mds_md_v1::lmm_magic, lov_mds_md_v1::lmm_objects, lov_mds_md_v1::lmm_stripe_count, lu_object::lo_header, LOV_MAGIC_V1, LOV_MAGIC_V3, lov_mds_md_size(), lfsck_thread_info::lti_dof, lfsck_thread_info::lti_hint, lfsck_thread_info::lti_oi, lu_fid_eq(), lu_object_anon(), lu_object_fid(), lu_object_locate(), lu_object_put_nocache(), LU_XATTR_REPLACE, MDS_INODELOCK_LAYOUT, MDS_INODELOCK_XATTR, ost_id::oi, ostid_cpu_to_le(), ostid_le_to_cpu(), ostid_to_fid(), PFID, stop, unlikely, and XATTR_NAME_LOV.
Referenced by lfsck_layout_assistant_handler_p1().
static int lfsck_layout_repair_owner (const struct lu_env * env, struct lfsck_component * com, struct dt_object * parent, struct lfsck_layout_req * llr, struct lu_attr * pla, const struct lu_attr * cla) [static]
Definition at line 3014 of file lfsck_layout.c.
References CDEBUG, D_LFSCK, DFID, dt_attr_get(), dt_attr_set(), dt_declare_attr_set(), dt_read_lock(), dt_read_unlock(), dt_trans_create(), dt_trans_start_local(), ENTRY, GOTO, LA_GID, lu_attr::la_gid, LA_UID, lu_attr::la_uid, lu_attr::la_valid, lfsck_component::lc_lfsck, lfsck_dto2fid(), lfsck_env_info(), lfsck_is_dead_obj(), lfsck_layout_trans_stop(), lfsck_lfsck2name(), lfsck_obj2dev(), lfsck_layout_req::llr_child, lfsck_layout_req::llr_lov_idx, lfsck_layout_req::llr_ost_idx, lfsck_thread_info::lti_la2, PFID, stop, and unlikely.
Referenced by lfsck_layout_assistant_handler_p1().
static int lfsck_layout_repair_unmatched_pair (const struct lu_env * env, struct lfsck_component * com, struct dt_object * parent, struct lfsck_layout_req * llr, struct lu_attr * la) [static]
Definition at line 2732 of file lfsck_layout.c.
References buf, CDEBUG, cpu_to_le32, cpu_to_le64, D_LFSCK, DFID, dt_object::do_lu, dt_attr_get(), dt_attr_set(), dt_declare_attr_set(), dt_declare_xattr_set(), dt_trans_create(), dt_trans_start_local(), dt_write_lock(), dt_write_unlock(), dt_xattr_set(), ENTRY, lu_fid::f_oid, lu_fid::f_seq, filter_fid::ff_parent, GOTO, lu_attr::la_gid, LA_GID, lu_attr::la_uid, LA_UID, lu_attr::la_valid, lfsck_component::lc_lfsck, LCK_EX, lfsck_buf_get(), lfsck_dto2fid(), lfsck_env_info(), lfsck_ibits_lock(), lfsck_ibits_unlock(), lfsck_is_dead_obj(), lfsck_layout_trans_stop(), lfsck_lfsck2name(), lfsck_obj2dev(), lfsck_layout_req::llr_child, lfsck_layout_req::llr_lov_idx, lfsck_layout_req::llr_ost_idx, lfsck_thread_info::lti_new_pfid, lu_object_fid(), MDS_INODELOCK_LAYOUT, MDS_INODELOCK_XATTR, PFID, stop, unlikely, and XATTR_NAME_FID.
Referenced by lfsck_layout_assistant_handler_p1().
static void lfsck_layout_repaired (struct lfsck_layout * lo, __u64 * count) [static]
Definition at line 5377 of file lfsck_layout.c.
References lfsck_layout::ll_objs_repaired, and LLIT_MAX.
Referenced by lfsck_layout_query(), and lfsck_layout_query_all().
static int lfsck_layout_reset (const struct lu_env * env, struct lfsck_component * com, bool init) [static]
Definition at line 3895 of file lfsck_layout.c.
References __u64, CDEBUG, CFS_RESET_BITMAP(), D_LFSCK, lfsck_assistant_data::lad_bitmap, lfsck_assistant_data::lad_incomplete, lfsck_component::lc_data, lfsck_component::lc_file_ram, lfsck_component::lc_file_size, lfsck_component::lc_lfsck, lfsck_component::lc_sem, LFSCK_LAYOUT_MAGIC, lfsck_layout_store(), lfsck_lfsck2name(), lfsck_instance::li_master, lfsck_layout::ll_magic, lfsck_layout::ll_status, lfsck_layout::ll_success_count, lfsck_layout::ll_time_last_complete, and LS_INIT.
Referenced by lfsck_layout_master_prep(), lfsck_layout_prep(), and lfsck_layout_setup().
static int lfsck_layout_scan_orphan (const struct lu_env * env, struct lfsck_component * com, struct lfsck_tgt_desc * ltd) [static]
Definition at line 2511 of file lfsck_layout.c.
References CDEBUG, cfs_bitmap_check(), CFS_FAIL_TIMEOUT, cfs_fail_val, D_LFSCK, dt_index_operations::dio_it, dt_object::do_index_ops, dt_object_operations::do_index_try, dt_object::do_ops, dt_key, dt_lfsck_orphan_features, ENTRY, FID_SEQ_IDIF, GOTO, dt_index_operations::dt_it_ops::init, lfsck_assistant_data::lad_bitmap, lfsck_bookmark::lb_param, lfsck_component::lc_data, lfsck_component::lc_fid_latest_scanned_phase2, lfsck_component::lc_lfsck, lfsck_control_speed_by_self(), lfsck_env_info(), lfsck_lad_set_bitmap(), lfsck_layout_scan_orphan_one(), lfsck_lfsck2name(), lfsck_object_find_by_dev(), lfsck_object_put(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_thread, LPF_FAILOUT, lfsck_tgt_desc::ltd_index, lfsck_tgt_desc::ltd_tgt, lfsck_thread_info::lti_fid, lfsck_thread_info::lti_oi, lfsck_thread_info::lti_rec, OBD_FAIL_LFSCK_DELAY3, ost_id::oi, ostid_set_id(), ostid_set_seq(), ostid_to_fid(), RETURN, thread_is_running(), and unlikely.
Referenced by lfsck_layout_assistant_handler_p2().
static int lfsck_layout_scan_orphan_one (const struct lu_env * env, struct lfsck_component * com, struct lfsck_tgt_desc * ltd, struct lu_orphan_rec * rec, struct lu_fid * cfid) [static]
Definition at line 2441 of file lfsck_layout.c.
References dt_object::do_lu, dt_object_exists(), dt_object_remote(), ENTRY, lu_fid::f_ver, fid_is_sane(), fid_is_zero(), GOTO, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_new_checked, lfsck_component::lc_new_scanned, lfsck_component::lc_sem, lfsck_layout_recreate_lovea(), lfsck_layout_recreate_parent(), lfsck_object_find_by_dev(), lfsck_object_put(), lfsck_instance::li_bottom, lfsck_layout::ll_objs_failed_phase2, lfsck_layout::ll_objs_repaired, LLIT_ORPHAN, lu_orphan_rec::lor_fid, lfsck_tgt_desc::ltd_index, lu_object_attr(), lu_object_put_nocache(), and unlikely.
Referenced by lfsck_layout_scan_orphan().
static int lfsck_layout_scan_stripes (const struct lu_env * env, struct lfsck_component * com, struct dt_object * parent, struct lov_mds_md_v1 * lmm) [static]
Definition at line 4159 of file lfsck_layout.c.
References CDEBUG, D_LFSCK, DFID, DOSTID, dt_attr_get(), dt_declare_attr_get(), dt_declare_xattr_get(), ENTRY, GOTO, lov_ost_data_v1::l_ost_idx, lov_ost_data_v1::l_ost_oi, l_wait_event, lfsck_assistant_data::lad_assistant_status, lfsck_assistant_data::lad_lock, lfsck_assistant_data::lad_prefetched, lfsck_assistant_data::lad_req_list, lfsck_assistant_data::lad_thread, lfsck_assistant_req::lar_list, LASSERT, lfsck_bookmark::lb_async_windows, lfsck_component::lc_data, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_new_checked, lfsck_component::lc_sem, le16_to_cpu, le32_to_cpu, lfsck_assistant_object_init(), lfsck_assistant_object_put(), lfsck_buf_init(), lfsck_dto2fid(), lfsck_env_info(), lfsck_is_dead_obj(), lfsck_lad_set_bitmap(), lfsck_layout_assistant_req_fini(), lfsck_layout_assistant_req_init(), lfsck_layout_record_failure(), lfsck_lfsck2name(), lfsck_object_find_by_dev_nowait(), lfsck_object_put(), lfsck_tgt_get(), lfsck_tgt_put(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_ost_descs, lfsck_instance::li_pos_current, lfsck_instance::li_thread, likely, list_add_tail(), llr, lfsck_layout_req::llr_lar, lov_mds_md_v1::lmm_magic, lov_mds_md_v1::lmm_objects, lov_mds_md_v1::lmm_stripe_count, LOV_MAGIC_V1, LOV_MAGIC_V3, lovea_slot_is_dummy(), lfsck_position::lp_oit_cookie, LPF_FAILOUT, lfsck_tgt_desc::ltd_tgt, lfsck_thread_info::lti_fid, lfsck_thread_info::lti_la, lfsck_thread_info::lti_oi, lfsck_thread_info::lti_old_pfid, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_ASSISTANT_DIRECT, ost_id::oi, ostid_le_to_cpu(), ostid_to_fid(), PFID, POSTID, RETURN, ptlrpc_thread::t_ctl_waitq, thread_is_running(), thread_is_stopped(), unlikely, and XATTR_NAME_FID.
Referenced by lfsck_layout_master_exec_oit().
static void lfsck_layout_seq_insert (struct lfsck_layout_slave_data * llsd, struct lfsck_layout_seq * lls) [static]
Definition at line 1022 of file lfsck_layout.c.
References list_add_tail(), list_for_each_entry, lfsck_layout_seq::lls_list, lfsck_layout_seq::lls_seq, and lfsck_layout_slave_data::llsd_seq_list.
Referenced by lfsck_layout_slave_exec_oit().
static struct lfsck_layout_seq* lfsck_layout_seq_lookup (struct lfsck_layout_slave_data * llsd, __u64 seq) [static, read]
Definition at line 1006 of file lfsck_layout.c.
References list_for_each_entry, lfsck_layout_seq::lls_list, lfsck_layout_seq::lls_seq, and lfsck_layout_slave_data::llsd_seq_list.
Referenced by lfsck_layout_slave_exec_oit().
int lfsck_layout_setup (const struct lu_env * env, struct lfsck_instance * lfsck)
Definition at line 5556 of file lfsck_layout.c.
References CERROR, dt_locate(), dt_try_as_dir(), ENTRY, GOTO, INIT_LIST_HEAD, LASSERT, lfsck_component::lc_data, lfsck_component::lc_file_disk, lfsck_component::lc_file_ram, lfsck_component::lc_file_size, lfsck_component::lc_lfsck, lfsck_component::lc_link, lfsck_component::lc_link_dir, lfsck_component::lc_obj, lfsck_component::lc_ops, lfsck_component::lc_ref, lfsck_component::lc_sem, lfsck_component::lc_type, LE_LASTID_REBUILDING, LF_CRASHED_LASTID, LF_INCOMPLETE, lfsck_assistant_data_init(), lfsck_component_cleanup(), LFSCK_LAYOUT, lfsck_layout_init(), lfsck_layout_load(), lfsck_layout_reset(), lfsck_lfsck2name(), lfsck_object_put(), LFSCK_TYPE_LAYOUT, lfsck_instance::li_bottom, lfsck_instance::li_list_idle, lfsck_instance::li_list_scan, lfsck_instance::li_local_root_fid, lfsck_instance::li_lock, lfsck_instance::li_los, lfsck_instance::li_master, lfsck_instance::li_out_notify, lfsck_instance::li_out_notify_data, list_add_tail(), lfsck_layout::ll_flags, lfsck_layout::ll_status, lfsck_layout_slave_data::llsd_lock, lfsck_layout_slave_data::llsd_master_list, lfsck_layout_slave_data::llsd_rb_lock, lfsck_layout_slave_data::llsd_rb_root, lfsck_layout_slave_data::llsd_seq_list, local_file_find_or_create(), LS_CO_FAILED, LS_CO_PAUSED, LS_CO_STOPPED, LS_COMPLETED, LS_CRASHED, LS_FAILED, LS_INIT, LS_PARTIAL, LS_PAUSED, LS_SCANNING_PHASE1, LS_SCANNING_PHASE2, LS_STOPPED, OBD_ALLOC, OBD_ALLOC_PTR, RETURN, and unlikely.
Referenced by lfsck_register().
static int lfsck_layout_slave_async_interpret (const struct lu_env * env, struct ptlrpc_request * req, void * args, int rc) [static]
Definition at line 3436 of file lfsck_layout.c.
References CDEBUG, class_export_put(), D_LFSCK, done, lfsck_component::lc_data, lfsck_component::lc_lfsck, lfsck_component_put(), lfsck_layout_llst_del(), lfsck_layout_llst_put(), lfsck_lfsck2name(), lfsck_layout_slave_async_args::llsaa_com, lfsck_layout_slave_async_args::llsaa_exp, lfsck_layout_slave_async_args::llsaa_llst, lfsck_layout_slave_target::llst_failures, lfsck_layout_slave_target::llst_index, lfsck_reply::lr_status, LS_SCANNING_PHASE1, LS_SCANNING_PHASE2, obd_timeout, req_capsule_server_get(), RMF_LFSCK_REPLY, and ptlrpc_request::rq_pill.
Referenced by lfsck_layout_async_query().
static int lfsck_layout_slave_check_pairs (const struct lu_env * env, struct lfsck_component * com, struct lu_fid * cfid, struct lu_fid * pfid) [static]
Definition at line 3789 of file lfsck_layout.c.
References class_exp2cliimp(), class_export_put(), ENTRY, exp_connect_flags(), fid_is_idif(), fld_range_is_mdt(), fld_range_set_any(), fld_server_lookup(), GOTO, lfsck_component::lc_lfsck, LE_PAIRS_VERIFY, lfsck_dev_site(), lfsck_env_info(), LFSCK_NOTIFY, LFSCK_TYPE_LAYOUT, lfsck_instance::li_obd, lfsck_request::lr_active, lfsck_request::lr_event, lfsck_request::lr_fid, lfsck_request::lr_fid2, lu_seq_range::lsr_index, lfsck_thread_info::lti_range, lustre_find_lwp_by_index(), LUSTRE_OBD_VERSION, OBD_CONNECT_LFSCK, obd_device::obd_name, ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), req_capsule_client_get(), RETURN, RMF_LFSCK_REQUEST, ptlrpc_request::rq_pill, RQF_LFSCK_NOTIFY, seq_server_site::ss_server_fld, and unlikely.
Referenced by lfsck_layout_slave_in_notify().
static int lfsck_layout_slave_checkpoint (const struct lu_env * env, struct lfsck_component * com, bool init) [static]
Definition at line 3981 of file lfsck_layout.c.
References CDEBUG, cfs_duration_sec(), cfs_time_current(), cfs_time_current_sec(), D_LFSCK, HALF_SEC, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_new_checked, lfsck_component::lc_sem, lfsck_layout_store(), lfsck_lfsck2name(), lfsck_instance::li_pos_checkpoint, lfsck_instance::li_pos_current, lfsck_instance::li_time_last_checkpoint, lfsck_layout::ll_objs_checked_phase1, lfsck_layout::ll_pos_last_checkpoint, lfsck_layout::ll_pos_latest_start, lfsck_layout::ll_run_time_phase1, lfsck_layout::ll_status, lfsck_layout::ll_time_last_checkpoint, lfsck_position::lp_oit_cookie, and LPU64.
static int lfsck_layout_slave_conditional_destroy (const struct lu_env * env, struct lfsck_component * com, struct lfsck_request * lr) [static]
Definition at line 1954 of file lfsck_layout.c.
References __u64, CDEBUG, D_LFSCK, DFID, dt_attr_get(), dt_declare_destroy(), dt_declare_ref_del(), dt_destroy(), dt_object_exists(), dt_read_lock(), dt_read_unlock(), dt_ref_del(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), ELDLM_OK, ldlm_extent::end, ENTRY, GOTO, ldlm_policy_data::l_extent, lu_attr::la_ctime, lu_attr::la_mode, LASSERT, lfsck_component::lc_lfsck, LCK_EX, ldlm_blocking_ast(), ldlm_cli_enqueue_local(), ldlm_completion_ast(), LDLM_EXTENT, ldlm_lock_decref(), lfsck_env_info(), lfsck_is_dead_obj(), lfsck_lfsck2name(), lfsck_object_find_by_dev(), lfsck_object_put(), lfsck_instance::li_bottom, lfsck_instance::li_namespace, likely, lfsck_request::lr_fid, lfsck_thread_info::lti_la, lfsck_thread_info::lti_policy, lfsck_thread_info::lti_resid, LVB_T_NONE, OBD_OBJECT_EOF, ost_fid_build_resid(), PFID, RETURN, and stop.
Referenced by lfsck_layout_slave_in_notify().
static void lfsck_layout_slave_data_release (const struct lu_env * env, struct lfsck_component * com) [static]
Definition at line 5077 of file lfsck_layout.c.
References lfsck_component::lc_data, lfsck_layout_slave_quit(), and OBD_FREE_PTR.
static int lfsck_layout_slave_double_scan (const struct lu_env * env, struct lfsck_component * com) [static]
Definition at line 4950 of file lfsck_layout.c.
References CDEBUG, cfs_time_current(), cfs_time_seconds(), D_LFSCK, done, ENTRY, GOTO, l_wait_event, lfsck_component::lc_data, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_new_checked, lfsck_component::lc_new_scanned, lfsck_component::lc_time_last_checkpoint, lfsck_component::lc_time_next_checkpoint, LE_PHASE2_DONE, LF_INCOMPLETE, LFSCK_CHECKPOINT_INTERVAL, lfsck_layout_double_scan_result(), lfsck_layout_slave_notify_master(), lfsck_layout_slave_query_master(), lfsck_layout_slave_quit(), lfsck_lfsck2name(), lfsck_instance::li_double_scan_count, lfsck_instance::li_thread, list_empty(), lfsck_layout::ll_flags, lfsck_layout::ll_status, lfsck_layout_slave_data::llsd_master_list, LWI_TIMEOUT, ptlrpc_thread::t_ctl_waitq, thread, thread_is_running(), and unlikely.
static int lfsck_layout_slave_exec_oit (const struct lu_env * env, struct lfsck_component * com, struct dt_object * obj) [static]
Definition at line 4504 of file lfsck_layout.c.
References __u64, CDEBUG, cfs_fail_val, cfs_time_seconds(), D_LFSCK, ENTRY, fid_idif_id(), fid_is_for_ostobj(), fid_is_idif(), fid_is_last_id(), fid_is_norm(), fid_oid(), fid_ver(), GOTO, INIT_LIST_HEAD, l_wait_event, LASSERT, lfsck_component::lc_data, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_new_checked, lfsck_component::lc_sem, LE_LASTID_REBUILDING, LF_CRASHED_LASTID, lfsck_dev_idx(), lfsck_dto2fid(), lfsck_layout_lastid_load(), lfsck_layout_lastid_reload(), lfsck_layout_seq_insert(), lfsck_layout_seq_lookup(), lfsck_lfsck2name(), lfsck_rbtree_update_bitmap(), lfsck_instance::li_out_notify, lfsck_instance::li_out_notify_data, lfsck_instance::li_thread, lfsck_layout::ll_flags, lfsck_layout::ll_objs_failed_phase1, lfsck_layout_seq::lls_dirty, lfsck_layout_seq::lls_lastid, lfsck_layout_seq::lls_lastid_known, lfsck_layout_seq::lls_list, lfsck_layout_seq::lls_seq, LPU64, LPX64, LWI_TIMEOUT, OBD_ALLOC_PTR, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_DELAY5, OBD_FREE_PTR, ptlrpc_thread::t_ctl_waitq, thread, thread_is_running(), and unlikely.
static int lfsck_layout_slave_in_notify (const struct lu_env * env, struct lfsck_component * com, struct lfsck_request * lr, struct thandle * th) [static]
Definition at line 5276 of file lfsck_layout.c.
References CDEBUG, D_LFSCK, ENTRY, lfsck_bookmark::lb_param, lfsck_component::lc_data, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, LE_CONDITIONAL_DESTROY, LE_FID_ACCESSED, LE_PAIRS_VERIFY, LE_PEER_EXIT, LE_PHASE1_DONE, LE_PHASE2_DONE, LF_INCOMPLETE, lfsck_env_info(), lfsck_layout_llst_find_and_del(), lfsck_layout_llst_put(), lfsck_layout_slave_check_pairs(), lfsck_layout_slave_conditional_destroy(), lfsck_layout_slave_repair_pfid(), lfsck_lfsck2name(), lfsck_rbtree_update_bitmap(), lfsck_stop(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_bottom, lfsck_instance::li_thread, list_empty(), lfsck_layout::ll_flags, lfsck_layout_slave_data::llsd_master_list, LPF_BROADCAST, LPF_FAILOUT, LPVS_INCONSISTENT, LPVS_INCONSISTENT_TOFIX, LPVS_INIT, lfsck_request::lr_event, lfsck_request::lr_fid, lfsck_request::lr_fid2, lfsck_request::lr_fid3, lfsck_request::lr_flags2, lfsck_request::lr_index, lfsck_request::lr_param, lfsck_request::lr_status, LS_CO_STOPPED, lfsck_stop::ls_flags, lfsck_stop::ls_status, LS_STOPPED, lfsck_thread_info::lti_stop, RETURN, stop, and ptlrpc_thread::t_ctl_waitq.
static int lfsck_layout_slave_join (const struct lu_env * env, struct lfsck_component * com, struct lfsck_start_param * lsp) [static]
Definition at line 5459 of file lfsck_layout.c.
References ENTRY, lfsck_component::lc_data, lfsck_component::lc_lfsck, lfsck_layout_llst_add(), lfsck_layout_llst_find_and_del(), lfsck_layout_llst_put(), lfsck_instance::li_lock, lfsck_instance::li_thread, lfsck_layout_slave_data::llsd_rbtree_valid, LPF_OST_ORPHAN, lfsck_start::ls_flags, lfsck_start_param::lsp_index, lfsck_start_param::lsp_index_valid, lfsck_start_param::lsp_start, RETURN, start, and thread_is_running().
static void lfsck_layout_slave_notify_master (const struct lu_env * env, struct lfsck_component * com, enum lfsck_events event, int result) [static]
Definition at line 3628 of file lfsck_layout.c.
References CDEBUG, class_export_put(), D_LFSCK, ENTRY, obd_export::exp_obd, lfsck_component::lc_data, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, LEF_FROM_OST, lfsck_dev_idx(), lfsck_env_info(), lfsck_layout_async_notify(), lfsck_layout_llst_del(), lfsck_layout_llst_put(), lfsck_lfsck2name(), LFSCK_TYPE_LAYOUT, lfsck_instance::li_obd, list_empty(), list_entry, list_move_tail(), lfsck_layout::ll_flags, lfsck_layout_slave_data::llsd_lock, lfsck_layout_slave_data::llsd_master_list, lfsck_layout_slave_data::llsd_touch_gen, lfsck_layout_slave_target::llst_gen, lfsck_layout_slave_target::llst_index, lfsck_layout_slave_target::llst_list, lfsck_layout_slave_target::llst_ref, lfsck_request::lr_active, lfsck_request::lr_event, lfsck_request::lr_flags, lfsck_request::lr_flags2, lfsck_request::lr_index, lfsck_request::lr_status, lfsck_thread_info::lti_lr, lustre_find_lwp_by_index(), list_head::next, obd_device::obd_name, ptlrpc_prep_set(), ptlrpc_set_destroy(), ptlrpc_set_wait(), and RETURN_EXIT.
Referenced by lfsck_layout_slave_double_scan(), and lfsck_layout_slave_post().
static int lfsck_layout_slave_post (const struct lu_env * env, struct lfsck_component * com, int result, bool init) [static]
Definition at line 4680 of file lfsck_layout.c.
References CDEBUG, cfs_duration_sec(), cfs_time_current(), cfs_time_current_sec(), D_LFSCK, done, HALF_SEC, LASSERT, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_link, lfsck_component::lc_new_checked, lfsck_component::lc_sem, LE_LASTID_REBUILT, LE_PHASE1_DONE, LF_CRASHED_LASTID, LF_SCANNED_ONCE, LF_UPGRADE, lfsck_layout_lastid_store(), lfsck_layout_slave_notify_master(), lfsck_layout_store(), lfsck_lfsck2name(), lfsck_instance::li_list_double_scan, lfsck_instance::li_list_idle, lfsck_instance::li_lock, lfsck_instance::li_out_notify, lfsck_instance::li_out_notify_data, lfsck_instance::li_pos_checkpoint, lfsck_instance::li_status, lfsck_instance::li_time_last_checkpoint, list_move_tail(), lfsck_layout::ll_flags, lfsck_layout::ll_objs_checked_phase1, lfsck_layout::ll_pos_last_checkpoint, lfsck_layout::ll_run_time_phase1, lfsck_layout::ll_status, lfsck_layout::ll_time_last_checkpoint, lfsck_position::lp_oit_cookie, LS_FAILED, LS_PAUSED, LS_SCANNING_PHASE2, and LS_STOPPED.
static int lfsck_layout_slave_prep (const struct lu_env * env, struct lfsck_component * com, struct lfsck_start_param * lsp) [static]
Definition at line 4083 of file lfsck_layout.c.
References CDEBUG, D_LFSCK, LASSERT, lfsck_component::lc_data, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_pos_start, LE_LASTID_REBUILDING, LF_CRASHED_LASTID, lfsck_layout_llst_add(), lfsck_layout_prep(), lfsck_lfsck2name(), lfsck_rbtree_setup(), lfsck_instance::li_out_notify, lfsck_instance::li_out_notify_data, list_empty(), lfsck_layout::ll_flags, lfsck_layout_slave_data::llsd_master_list, lfsck_layout_slave_data::llsd_rb_lock, lfsck_layout_slave_data::llsd_rbtree_valid, lfsck_position::lp_oit_cookie, LPF_OST_ORPHAN, LPU64, lfsck_start::ls_flags, lfsck_start_param::lsp_index, lfsck_start_param::lsp_index_valid, lfsck_start_param::lsp_start, and start.
static int lfsck_layout_slave_query_master (const struct lu_env * env, struct lfsck_component * com) [static]
Definition at line 3555 of file lfsck_layout.c.
References CDEBUG, class_export_put(), D_LFSCK, ENTRY, obd_export::exp_obd, GOTO, lfsck_component::lc_data, lfsck_component::lc_lfsck, LE_QUERY, lfsck_env_info(), lfsck_layout_async_query(), lfsck_layout_llst_del(), lfsck_layout_llst_put(), lfsck_lfsck2name(), LFSCK_TYPE_LAYOUT, lfsck_instance::li_obd, list_empty(), list_entry, list_move_tail(), lfsck_layout_slave_data::llsd_lock, lfsck_layout_slave_data::llsd_master_list, lfsck_layout_slave_data::llsd_touch_gen, lfsck_layout_slave_target::llst_gen, lfsck_layout_slave_target::llst_index, lfsck_layout_slave_target::llst_list, lfsck_layout_slave_target::llst_ref, lfsck_request::lr_active, lfsck_request::lr_event, lfsck_thread_info::lti_lr, lustre_find_lwp_by_index(), list_head::next, obd_device::obd_name, ptlrpc_prep_set(), ptlrpc_set_destroy(), and ptlrpc_set_wait().
Referenced by lfsck_layout_slave_double_scan().
static void lfsck_layout_slave_quit (const struct lu_env * env, struct lfsck_component * com) [static]
Definition at line 5129 of file lfsck_layout.c.
References LASSERT, lfsck_component::lc_data, lfsck_component::lc_sem, lfsck_layout_llst_put(), lfsck_object_put(), lfsck_rbtree_cleanup(), list_del_init(), list_empty(), list_entry, list_for_each_entry_safe, lfsck_layout_seq::lls_lastid_obj, lfsck_layout_seq::lls_list, lfsck_layout_slave_data::llsd_lock, lfsck_layout_slave_data::llsd_master_list, lfsck_layout_slave_data::llsd_seq_list, lfsck_layout_slave_target::llst_list, list_head::next, and OBD_FREE_PTR.
Referenced by lfsck_layout_slave_data_release(), and lfsck_layout_slave_double_scan().
static int lfsck_layout_slave_repair_pfid (const struct lu_env * env, struct lfsck_component * com, struct lfsck_request * lr) [static]
Definition at line 3856 of file lfsck_layout.c.
References __lfsck_layout_update_pfid(), CDEBUG, D_LFSCK, DFID, dt_object_exists(), dt_write_lock(), dt_write_unlock(), ENTRY, lu_fid::f_ver, GOTO, lfsck_component::lc_lfsck, lfsck_is_dead_obj(), lfsck_lfsck2name(), lfsck_object_find_bottom(), lfsck_object_put(), lfsck_request::lr_fid, lfsck_request::lr_fid2, PFID, and unlikely.
Referenced by lfsck_layout_slave_in_notify().
static int lfsck_layout_store (const struct lu_env * env, struct lfsck_component * com) [static]
Store the layout LFSCK trace file on disk.
The layout LFSCK trace file records the layout LFSCK status information and other statistics, such as how many objects have been scanned, and how many objects have been repaired, and etc. It also contains the bitmap for failed OSTs during the layout LFSCK. All these information will be synced from RAM to disk periodically.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
Return values:
0 for success
negative error number on failure
Definition at line 883 of file lfsck_layout.c.
References CDEBUG, D_LFSCK, cfs_bitmap::data, dt_declare_record_write(), dt_record_write(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), ENTRY, GOTO, lfsck_assistant_data::lad_bitmap, LASSERT, LASSERTF, lfsck_component::lc_data, lfsck_component::lc_file_disk, lfsck_component::lc_file_ram, lfsck_component::lc_file_size, lfsck_component::lc_lfsck, lfsck_component::lc_obj, lfsck_buf_get(), lfsck_layout_cpu_to_le(), lfsck_lfsck2name(), lfsck_obj2dev(), lfsck_instance::li_master, lfsck_layout::ll_bitmap_size, cfs_bitmap::size, and size.
Referenced by lfsck_layout_double_scan_result(), lfsck_layout_init(), lfsck_layout_master_checkpoint(), lfsck_layout_master_post(), lfsck_layout_reset(), lfsck_layout_slave_checkpoint(), and lfsck_layout_slave_post().
static int lfsck_layout_trans_stop (const struct lu_env * env, struct dt_device * dev, struct thandle * handle, int result) [static]
Definition at line 1379 of file lfsck_layout.c.
References dt_trans_stop(), and thandle::th_result.
Referenced by lfsck_layout_repair_dangling(), lfsck_layout_repair_owner(), and lfsck_layout_repair_unmatched_pair().
static int lfsck_layout_update_pfid (const struct lu_env * env, struct lfsck_component * com, struct dt_object * parent, struct lu_fid * cfid, struct dt_device * cdev, __u32 ea_off) [static]
Return values:
+1,: repaired
0,: did nothing
-ve,: on error
Definition at line 1621 of file lfsck_layout.c.
References __lfsck_layout_update_pfid(), dt_object::do_lu, ENTRY, lfsck_object_find_by_dev(), lfsck_object_put(), lu_object_fid(), and RETURN.
Referenced by lfsck_layout_recreate_lovea().
static int lfsck_layout_verify_header (struct lov_mds_md_v1 * lmm) [static]
Definition at line 359 of file lfsck_layout.c.
References CDEBUG, D_LFSCK, DOSTID, le32_to_cpu, lov_mds_md_v1::lmm_magic, lov_mds_md_v1::lmm_oi, lmm_oi_le_to_cpu(), lov_mds_md_v1::lmm_pattern, LOV_MAGIC_MAGIC, LOV_MAGIC_MASK, LOV_MAGIC_V1, LOV_MAGIC_V3, lov_pattern, LOV_PATTERN_RAID0, and POSTID.
Referenced by lfsck_layout_master_check_pairs(), lfsck_layout_master_exec_oit(), and lfsck_layout_recreate_lovea().
static int lfsck_orphan_index_declare_delete (const struct lu_env * env, struct dt_object * dt, const struct dt_key * key, struct thandle * handle) [static]
Definition at line 5802 of file lfsck_layout.c.
static int lfsck_orphan_index_declare_insert (const struct lu_env * env, struct dt_object * dt, const struct dt_rec * rec, const struct dt_key * key, struct thandle * handle) [static]
Definition at line 5783 of file lfsck_layout.c.
static int lfsck_orphan_index_delete (const struct lu_env * env, struct dt_object * dt, const struct dt_key * key, struct thandle * handle) [static]
Definition at line 5810 of file lfsck_layout.c.
static int lfsck_orphan_index_insert (const struct lu_env * env, struct dt_object * dt, const struct dt_rec * rec, const struct dt_key * key, struct thandle * handle, int ignore_quota) [static]
Definition at line 5792 of file lfsck_layout.c.
static int lfsck_orphan_index_lookup (const struct lu_env * env, struct dt_object * dt, struct dt_rec * rec, const struct dt_key * key) [static]
Definition at line 5775 of file lfsck_layout.c.
static void lfsck_orphan_it_fini (const struct lu_env * env, struct dt_it * di) [static]
Definition at line 5908 of file lfsck_layout.c.
References CDEBUG, D_LFSCK, LASSERT, lfsck_component::lc_data, lfsck_component::lc_lfsck, lfsck_component_put(), lfsck_layout_llst_put(), lfsck_lfsck2name(), lfsck_layout_slave_data::llsd_rb_lock, lfsck_layout_slave_target::llst_fid, lfsck_layout_slave_target::llst_hash, lfsck_orphan_it::loi_com, lfsck_orphan_it::loi_hash, lfsck_orphan_it::loi_key, lfsck_orphan_it::loi_llst, and OBD_FREE_PTR.
static int lfsck_orphan_it_get (const struct lu_env * env, struct dt_it * di, const struct dt_key * key) [static]
Return values:
+1,: locate to the exactly position
0,: cannot locate to the exactly position, call next() to move to a valid position.
-ve,: on error
Definition at line 6145 of file lfsck_layout.c.
References lfsck_orphan_it_next(), and lfsck_orphan_it::loi_key.
static struct dt_it* lfsck_orphan_it_init (const struct lu_env * env, struct dt_object * dt, __u32 attr) [static, read]
Definition at line 5818 of file lfsck_layout.c.
References CDEBUG, D_LFSCK, dt_device::dd_record_fid_accessed, dt_object::do_lu, ENTRY, GOTO, lfsck_component::lc_data, lfsck_component::lc_file_ram, LF_INCOMPLETE, lfsck_component_find(), lfsck_component_put(), lfsck_instance_find(), lfsck_instance_put(), lfsck_layout_llst_find_and_del(), lfsck_lfsck2name(), lfsck_rbtree_free(), LFSCK_TYPE_LAYOUT, lfsck_layout::ll_flags, lfsck_layout_slave_data::llsd_rb_lock, lfsck_layout_slave_data::llsd_rb_root, lfsck_layout_slave_data::llsd_rbtree_valid, lu_object::lo_dev, lfsck_orphan_it::loi_com, lfsck_orphan_it::loi_llst, lfsck_rbtree_node::lrn_accessed_count, lfsck_rbtree_node::lrn_known_count, lfsck_rbtree_node::lrn_node, lu2dt_dev(), OBD_ALLOC_PTR, OBD_FREE_PTR, RETURN, and unlikely.
static struct dt_key* lfsck_orphan_it_key (const struct lu_env * env, const struct dt_it * di) [static, read]
Definition at line 6168 of file lfsck_layout.c.
References dt_key, and lfsck_orphan_it::loi_key.
static int lfsck_orphan_it_key_rec (const struct lu_env * env, const struct dt_it * di, void * key_rec) [static]
Definition at line 6240 of file lfsck_layout.c.
static int lfsck_orphan_it_key_size (const struct lu_env * env, const struct dt_it * di) [static]
Definition at line 6176 of file lfsck_layout.c.
static int lfsck_orphan_it_load (const struct lu_env * env, const struct dt_it * di, __u64 hash) [static]
Return values:
+1,: locate to the exactly position
0,: cannot locate to the exactly position, call next() to move to a valid position.
-ve,: on error
Definition at line 6208 of file lfsck_layout.c.
References CDEBUG, D_LFSCK, fid_zero(), LASSERT, lfsck_component::lc_lfsck, lfsck_lfsck2name(), lfsck_orphan_it_next(), lfsck_layout_slave_target::llst_fid, lfsck_layout_slave_target::llst_hash, lfsck_orphan_it::loi_com, lfsck_orphan_it::loi_hash, lfsck_orphan_it::loi_key, lfsck_orphan_it::loi_llst, and LPU64.
static int lfsck_orphan_it_next (const struct lu_env * env, struct dt_it * di) [static]
Return values:
+1,: the iteration finished
0,: on success, not finished
-ve,: on error
Definition at line 5939 of file lfsck_layout.c.
References CDEBUG, D_LFSCK, DFID, dt_attr_get(), dt_object_exists(), dt_read_lock(), dt_read_unlock(), dt_xattr_get(), ENTRY, lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, filter_fid_old::ff_parent, fid_le_to_cpu(), fid_zero(), GOTO, lu_attr::la_ctime, lu_attr::la_gid, lu_attr::la_mode, lu_attr::la_uid, lfsck_component::lc_data, lfsck_component::lc_lfsck, lfsck_buf_get(), lfsck_env_info(), lfsck_fid_match_idx(), lfsck_is_dead_obj(), lfsck_layout_destroy_orphan(), lfsck_lfsck2name(), lfsck_object_find_bottom(), lfsck_object_put(), LFSCK_RBTREE_BITMAP_WIDTH, lfsck_rbtree_search(), lfsck_layout_slave_target::llst_index, lfsck_orphan_it::loi_com, lfsck_orphan_it::loi_hash, lfsck_orphan_it::loi_key, lfsck_orphan_it::loi_llst, lfsck_orphan_it::loi_lrn, lfsck_orphan_it::loi_over, lfsck_orphan_it::loi_rec, lu_orphan_rec::lor_fid, lu_orphan_rec::lor_gid, lu_orphan_rec::lor_uid, lfsck_rbtree_node::lrn_accessed_bitmap, lfsck_rbtree_node::lrn_accessed_count, lfsck_rbtree_node::lrn_first_oid, lfsck_rbtree_node::lrn_known_bitmap, lfsck_rbtree_node::lrn_known_count, lfsck_rbtree_node::lrn_node, lfsck_rbtree_node::lrn_seq, lfsck_thread_info::lti_la, lfsck_thread_info::lti_old_pfid, PFID, RETURN, unlikely, and XATTR_NAME_FID.
Referenced by lfsck_orphan_it_get(), and lfsck_orphan_it_load().
static void lfsck_orphan_it_put (const struct lu_env * env, struct dt_it * di) [static]
Definition at line 6163 of file lfsck_layout.c.
static int lfsck_orphan_it_rec (const struct lu_env * env, const struct dt_it * di, struct dt_rec * rec, __u32 attr) [static]
Definition at line 6182 of file lfsck_layout.c.
References lfsck_orphan_it::loi_rec.
static __u64 lfsck_orphan_it_store (const struct lu_env * env, const struct dt_it * di) [static]
Definition at line 6194 of file lfsck_layout.c.
References lfsck_orphan_it::loi_hash.
static void lfsck_rbtree_cleanup (const struct lu_env * env, struct lfsck_component * com) [static]
Definition at line 585 of file lfsck_layout.c.
References CDEBUG, D_LFSCK, dt_device::dd_record_fid_accessed, lfsck_component::lc_data, lfsck_component::lc_lfsck, lfsck_lfsck2name(), lfsck_object_put(), lfsck_rbtree_free(), lfsck_instance::li_bottom, lfsck_layout_slave_data::llsd_rb_lock, lfsck_layout_slave_data::llsd_rb_obj, lfsck_layout_slave_data::llsd_rb_root, lfsck_layout_slave_data::llsd_rbtree_valid, and lfsck_rbtree_node::lrn_node.
Referenced by lfsck_layout_slave_quit(), and lfsck_rbtree_update_bitmap().
static int lfsck_rbtree_cmp (struct lfsck_rbtree_node * lrn, __u64 seq, __u32 oid) [inline, static]
Definition at line 414 of file lfsck_layout.c.
References LFSCK_RBTREE_BITMAP_WIDTH, lfsck_rbtree_node::lrn_first_oid, and lfsck_rbtree_node::lrn_seq.
Referenced by lfsck_rbtree_insert(), and lfsck_rbtree_search().
static void lfsck_rbtree_free (struct lfsck_rbtree_node * lrn) [static]
Definition at line 514 of file lfsck_layout.c.
References LFSCK_RBTREE_BITMAP_SIZE, lfsck_rbtree_node::lrn_accessed_bitmap, lfsck_rbtree_node::lrn_known_bitmap, OBD_FREE, and OBD_FREE_PTR.
Referenced by lfsck_orphan_it_init(), lfsck_rbtree_cleanup(), and lfsck_rbtree_update_bitmap().
static struct lfsck_rbtree_node* lfsck_rbtree_insert (struct lfsck_layout_slave_data * llsd, struct lfsck_rbtree_node * lrn) [static, read]
Definition at line 523 of file lfsck_layout.c.
References lfsck_rbtree_cmp(), lfsck_layout_slave_data::llsd_rb_root, lfsck_rbtree_node::lrn_first_oid, lfsck_rbtree_node::lrn_node, and lfsck_rbtree_node::lrn_seq.
Referenced by lfsck_rbtree_update_bitmap().
static struct lfsck_rbtree_node* lfsck_rbtree_new (const struct lu_env * env, const struct lu_fid * fid) [static, read]
Definition at line 481 of file lfsck_layout.c.
References fid_oid(), LFSCK_RBTREE_BITMAP_MASK, LFSCK_RBTREE_BITMAP_SIZE, lfsck_rbtree_node::lrn_accessed_bitmap, lfsck_rbtree_node::lrn_accessed_count, lfsck_rbtree_node::lrn_first_oid, lfsck_rbtree_node::lrn_known_bitmap, lfsck_rbtree_node::lrn_known_count, lfsck_rbtree_node::lrn_node, lfsck_rbtree_node::lrn_seq, OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, and OBD_FREE_PTR.
Referenced by lfsck_rbtree_update_bitmap().
static struct lfsck_rbtree_node* lfsck_rbtree_search (struct lfsck_layout_slave_data * llsd, const struct lu_fid * fid, bool * exact) [static, read]
Definition at line 434 of file lfsck_layout.c.
References fid_oid(), lfsck_rbtree_cmp(), lfsck_layout_slave_data::llsd_rb_root, and lfsck_rbtree_node::lrn_node.
Referenced by lfsck_orphan_it_next(), and lfsck_rbtree_update_bitmap().
static int lfsck_rbtree_setup (const struct lu_env * env, struct lfsck_component * com) [static]
Definition at line 551 of file lfsck_layout.c.
References CDEBUG, D_LFSCK, dt_device::dd_record_fid_accessed, dt_object::do_index_ops, dt_object::do_lu, dt_locate(), lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, FID_SEQ_LAYOUT_RBTREE, lfsck_component::lc_data, lfsck_component::lc_lfsck, lfsck_dev_idx(), lfsck_env_info(), lfsck_lfsck2name(), lfsck_orphan_index_ops, lfsck_instance::li_bottom, lfsck_layout_slave_data::llsd_rb_obj, lfsck_layout_slave_data::llsd_rbtree_valid, lu_object::lo_header, lu_object_header::loh_attr, LOHA_EXISTS, lfsck_thread_info::lti_fid, and RETURN.
Referenced by lfsck_layout_slave_prep().
static void lfsck_rbtree_update_bitmap (const struct lu_env * env, struct lfsck_component * com, const struct lu_fid * fid, bool accessed) [static]
Definition at line 617 of file lfsck_layout.c.
References CDEBUG, D_LFSCK, ENTRY, fid_is_idif(), fid_is_last_id(), fid_is_norm(), fid_is_sane(), fid_oid(), GOTO, insert(), LASSERT, lfsck_component::lc_data, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, LF_INCOMPLETE, lfsck_lfsck2name(), LFSCK_RBTREE_BITMAP_MASK, lfsck_rbtree_cleanup(), lfsck_rbtree_free(), lfsck_rbtree_insert(), lfsck_rbtree_new(), lfsck_rbtree_search(), lfsck_layout::ll_flags, lfsck_layout_slave_data::llsd_rb_lock, lfsck_layout_slave_data::llsd_rbtree_valid, lfsck_rbtree_node::lrn_accessed_bitmap, lfsck_rbtree_node::lrn_accessed_count, lfsck_rbtree_node::lrn_known_bitmap, lfsck_rbtree_node::lrn_known_count, RETURN_EXIT, and unlikely.
Referenced by lfsck_layout_slave_exec_oit(), and lfsck_layout_slave_in_notify().
Variable Documentation
struct lfsck_assistant_operations lfsck_layout_assistant_ops
Initial value:
 {
        .la_handler_p1          = lfsck_layout_assistant_handler_p1,
        .la_handler_p2          = lfsck_layout_assistant_handler_p2,
        .la_fill_pos            = lfsck_layout_assistant_fill_pos,
        .la_double_scan_result  = lfsck_layout_double_scan_result,
        .la_req_fini            = lfsck_layout_assistant_req_fini,
        .la_sync_failures       = lfsck_layout_assistant_sync_failures,
}
Definition at line 5547 of file lfsck_layout.c.
struct lfsck_operations lfsck_layout_master_ops [static]
Initial value:
 {
        .lfsck_reset            = lfsck_layout_reset,
        .lfsck_fail             = lfsck_layout_fail,
        .lfsck_checkpoint       = lfsck_layout_master_checkpoint,
        .lfsck_prep             = lfsck_layout_master_prep,
        .lfsck_exec_oit         = lfsck_layout_master_exec_oit,
        .lfsck_exec_dir         = lfsck_layout_exec_dir,
        .lfsck_post             = lfsck_layout_master_post,
        .lfsck_dump             = lfsck_layout_dump,
        .lfsck_double_scan      = lfsck_layout_master_double_scan,
        .lfsck_data_release     = lfsck_layout_master_data_release,
        .lfsck_quit             = lfsck_layout_master_quit,
        .lfsck_in_notify        = lfsck_layout_master_in_notify,
        .lfsck_query            = lfsck_layout_query,
}
Definition at line 5498 of file lfsck_layout.c.
struct lfsck_operations lfsck_layout_slave_ops [static]
Initial value:
 {
        .lfsck_reset            = lfsck_layout_reset,
        .lfsck_fail             = lfsck_layout_fail,
        .lfsck_checkpoint       = lfsck_layout_slave_checkpoint,
        .lfsck_prep             = lfsck_layout_slave_prep,
        .lfsck_exec_oit         = lfsck_layout_slave_exec_oit,
        .lfsck_exec_dir         = lfsck_layout_exec_dir,
        .lfsck_post             = lfsck_layout_slave_post,
        .lfsck_dump             = lfsck_layout_dump,
        .lfsck_double_scan      = lfsck_layout_slave_double_scan,
        .lfsck_data_release     = lfsck_layout_slave_data_release,
        .lfsck_quit             = lfsck_layout_slave_quit,
        .lfsck_in_notify        = lfsck_layout_slave_in_notify,
        .lfsck_query            = lfsck_layout_query,
        .lfsck_join             = lfsck_layout_slave_join,
}
Definition at line 5514 of file lfsck_layout.c.
struct dt_index_operations lfsck_orphan_index_ops [read]
Initial value:
 {
        .dio_lookup             = lfsck_orphan_index_lookup,
        .dio_declare_insert     = lfsck_orphan_index_declare_insert,
        .dio_insert             = lfsck_orphan_index_insert,
        .dio_declare_delete     = lfsck_orphan_index_declare_delete,
        .dio_delete             = lfsck_orphan_index_delete,
        .dio_it = {
                .init           = lfsck_orphan_it_init,
                .fini           = lfsck_orphan_it_fini,
                .get            = lfsck_orphan_it_get,
                .put            = lfsck_orphan_it_put,
                .next           = lfsck_orphan_it_next,
                .key            = lfsck_orphan_it_key,
                .key_size       = lfsck_orphan_it_key_size,
                .rec            = lfsck_orphan_it_rec,
                .store          = lfsck_orphan_it_store,
                .load           = lfsck_orphan_it_load,
                .key_rec        = lfsck_orphan_it_key_rec,
        }
}
Definition at line 6247 of file lfsck_layout.c.
Referenced by lfsck_rbtree_setup().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.