Lustre: lustre/lfsck/lfsck_engine.c File Reference
lustre/lfsck/lfsck_engine.c File Reference
#include <lu_object.h>
#include <dt_object.h>
#include <lustre_net.h>
#include <lustre_fid.h>
#include <obd_support.h>
#include <lustre_lib.h>
#include "lfsck_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LFSCK
Functions
int lfsck_unpack_ent (struct lu_dirent *ent, __u64 *cookie, __u16 *type)
static void lfsck_di_oit_put (const struct lu_env *env, struct lfsck_instance *lfsck)
static void lfsck_di_dir_put (const struct lu_env *env, struct lfsck_instance *lfsck)
static int lfsck_parent_fid (const struct lu_env *env, struct dt_object *obj, struct lu_fid *fid)
static int lfsck_needs_scan_dir (const struct lu_env *env, struct lfsck_instance *lfsck, struct dt_object *obj)
Check whether needs to scan the directory or not.
static int lfsck_load_stripe_lmv (const struct lu_env *env, struct lfsck_instance *lfsck, struct dt_object *obj)
static void lfsck_fail (const struct lu_env *env, struct lfsck_instance *lfsck, bool new_checked)
void lfsck_close_dir (const struct lu_env *env, struct lfsck_instance *lfsck, int result)
int lfsck_open_dir (const struct lu_env *env, struct lfsck_instance *lfsck, __u64 cookie)
static int lfsck_checkpoint (const struct lu_env *env, struct lfsck_instance *lfsck)
static int lfsck_prep (const struct lu_env *env, struct lfsck_instance *lfsck, struct lfsck_start_param *lsp)
static int lfsck_exec_oit (const struct lu_env *env, struct lfsck_instance *lfsck, struct dt_object *obj)
static int lfsck_exec_dir (const struct lu_env *env, struct lfsck_instance *lfsck, struct lfsck_assistant_object *lso, struct lu_dirent *ent, __u16 type)
static int lfsck_master_dir_engine (const struct lu_env *env, struct lfsck_instance *lfsck)
static int lfsck_post (const struct lu_env *env, struct lfsck_instance *lfsck, int result)
static int lfsck_double_scan (const struct lu_env *env, struct lfsck_instance *lfsck)
static void lfsck_quit (const struct lu_env *env, struct lfsck_instance *lfsck)
static int lfsck_master_oit_engine (const struct lu_env *env, struct lfsck_instance *lfsck)
Object-table based iteration engine.
int lfsck_master_engine (void *args)
static bool lfsck_assistant_req_empty (struct lfsck_assistant_data *lad)
static int lfsck_assistant_query_others (const struct lu_env *env, struct lfsck_component *com)
Query the LFSCK status from the instatnces on remote servers.
static int lfsck_assistant_notify_others (const struct lu_env *env, struct lfsck_component *com, struct lfsck_request *lr)
Notify the LFSCK event to the instances on remote servers.
int lfsck_assistant_engine (void *args)
The LFSCK assistant thread is triggered by the LFSCK main engine.
Define Documentation
#define DEBUG_SUBSYSTEM S_LFSCK
Definition at line 31 of file lfsck_engine.c.
Function Documentation
int lfsck_assistant_engine (void * args)
The LFSCK assistant thread is triggered by the LFSCK main engine.
They co-work together as an asynchronous pipeline: the LFSCK main engine scans the system and pre-fetches the objects, attributes, or name entries, etc, and pushes them into the pipeline as input requests for the LFSCK assistant thread; on the other end of the pipeline, the LFSCK assistant thread performs the real check and repair for every request from the main engine.
Generally, the assistant engine may be blocked when check/repair something, so the LFSCK main engine will run some faster. On the other hand, the LFSCK main engine will drive multiple assistant threads in parallel, means for each LFSCK component on the master (such as layout LFSCK, namespace LFSCK), there is an independent LFSCK assistant thread. So under such 1:N multiple asynchronous pipelines mode, the whole LFSCK performance will be much better than check/repair everything by the LFSCK main engine itself.
Definition at line 1543 of file lfsck_engine.c.
References CDEBUG, cfs_time_current(), cfs_time_seconds(), D_LFSCK, dt_sync(), ENTRY, GOTO, l_wait_event, lfsck_assistant_operations::la_double_scan_result, lfsck_assistant_operations::la_fill_pos, lfsck_assistant_operations::la_handler_p1, lfsck_assistant_operations::la_handler_p2, lfsck_assistant_operations::la_req_fini, lfsck_assistant_data::lad_assistant_status, lfsck_assistant_data::lad_exit, lfsck_assistant_data::lad_in_double_scan, lfsck_assistant_data::lad_lock, lfsck_assistant_data::lad_name, lfsck_assistant_data::lad_ops, lfsck_assistant_data::lad_post_result, lfsck_assistant_data::lad_prefetched, lfsck_assistant_data::lad_req_list, lfsck_assistant_data::lad_task, lfsck_assistant_data::lad_thread, lfsck_assistant_data::lad_to_double_scan, lfsck_assistant_data::lad_to_post, lfsck_assistant_req::lar_list, LASSERT, LASSERTF, lfsck_bookmark::lb_async_windows, lfsck_component::lc_data, lfsck_component::lc_new_checked, lfsck_component::lc_new_scanned, lfsck_component::lc_pos_start, lfsck_component::lc_time_last_checkpoint, lfsck_component::lc_time_next_checkpoint, LE_PEER_EXIT, LE_PHASE1_DONE, LE_PHASE2_DONE, LE_START, LE_STOP, lfsck_assistant_notify_others(), lfsck_assistant_query_others(), lfsck_assistant_req_empty(), LFSCK_CHECKPOINT_INTERVAL, lfsck_env_info(), lfsck_lfsck2name(), lfsck_phase2_next_ready(), lfsck_thread_args_fini(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_double_scan_count, lfsck_instance::li_flags, lfsck_instance::li_next, lfsck_instance::li_pos_checkpoint, lfsck_instance::li_status, lfsck_instance::li_thread, list_del_init(), list_empty(), list_entry, lfsck_position::lp_oit_cookie, LPF_ALL_TGT, LPF_FAILOUT, LPF_RESET, lfsck_request::lr_event, lfsck_request::lr_param, lfsck_request::lr_status, LS_CO_FAILED, LS_CO_PAUSED, LS_CO_STOPPED, LS_FAILED, LS_PAUSED, LS_STOPPED, lfsck_thread_args::lta_com, lfsck_thread_args::lta_env, lfsck_thread_args::lta_lfsck, lfsck_thread_info::lti_lr, LWI_TIMEOUT_INTERVAL, list_head::next, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_NO_DOUBLESCAN, SVC_RUNNING, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, thread_is_running(), thread_set_flags(), and unlikely.
Referenced by lfsck_start_assistant().
static int lfsck_assistant_notify_others (const struct lu_env * env, struct lfsck_component * com, struct lfsck_request * lr) [static]
Notify the LFSCK event to the instances on remote servers.
The LFSCK assistant thread notifies the LFSCK instances on other servers (MDT/OST) about some events, such as start new scanning, stop the scanning, this LFSCK instance will exit, and so on.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
[in] lr pointer to the LFSCK event request
Return values:
0 for success
negative error number on failure
Definition at line 1248 of file lfsck_engine.c.
References CDEBUG, cfs_foreach_bit, D_LFSCK, ENTRY, lfsck_assistant_operations::la_sync_failures, lfsck_assistant_data::lad_mdt_list, lfsck_assistant_data::lad_mdt_phase1_list, lfsck_assistant_data::lad_name, lfsck_assistant_data::lad_ops, lfsck_assistant_data::lad_ost_list, lfsck_assistant_data::lad_touch_gen, lfsck_async_interpret_args::laia_com, lfsck_async_interpret_args::laia_lr, lfsck_async_interpret_args::laia_ltd, lfsck_async_interpret_args::laia_ltds, LASSERT, lfsck_bookmark::lb_async_windows, lfsck_bookmark::lb_param, lfsck_bookmark::lb_speed_limit, lfsck_bookmark::lb_version, lfsck_component::lc_data, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_type, LE_PEER_EXIT, LE_PHASE1_DONE, LE_PHASE2_DONE, LE_START, LE_STOP, LEF_TO_OST, LF_INCOMPLETE, lfsck_async_interpret_common(), lfsck_async_request(), lfsck_dev_idx(), lfsck_env_info(), lfsck_lad_set_bitmap(), lfsck_lfsck2name(), lfsck_ltd2tgt(), LFSCK_NOTIFY, lfsck_tgt_get(), lfsck_tgt_put(), LFSCK_TYPE_LAYOUT, lfsck_instance::li_bookmark_ram, lfsck_instance::li_mdt_descs, lfsck_instance::li_ost_descs, list, list_add_tail(), list_del_init(), list_empty(), list_entry, list_for_each_entry_safe, list_move_tail(), lfsck_namespace::ln_flags, LPF_ALL_TGT, lfsck_request::lr_active, lfsck_request::lr_async_windows, lfsck_request::lr_event, lfsck_request::lr_flags, lfsck_request::lr_flags2, lfsck_request::lr_index, lfsck_request::lr_param, lfsck_request::lr_speed, lfsck_request::lr_valid, lfsck_request::lr_version, LSV_DRYRUN, LSV_ERROR_HANDLE, LSV_SPEED_LIMIT, lfsck_tgt_desc::ltd_exp, lfsck_tgt_desc::ltd_index, lfsck_tgt_desc::ltd_layout_gen, lfsck_tgt_desc::ltd_layout_list, lfsck_tgt_desc::ltd_layout_phase_list, lfsck_tgt_descs::ltd_lock, lfsck_tgt_desc::ltd_namespace_gen, lfsck_tgt_desc::ltd_namespace_list, lfsck_tgt_desc::ltd_namespace_phase_list, lfsck_tgt_desc::ltd_ref, lfsck_tgt_descs::ltd_rw_sem, lfsck_tgt_desc::ltd_synced_failures, lfsck_tgt_descs::ltd_tgts_bitmap, lfsck_thread_info::lti_laia, list_head::next, ptlrpc_prep_set(), ptlrpc_set_destroy(), ptlrpc_set_wait(), and RETURN.
Referenced by lfsck_assistant_engine().
static int lfsck_assistant_query_others (const struct lu_env * env, struct lfsck_component * com) [static]
Query the LFSCK status from the instatnces on remote servers.
The LFSCK assistant thread queries the LFSCK instances on other servers (MDT/OST) about their status, such as whether they have finished the phase1/phase2 scanning or not, and so on.
Parameters:
[in] env pointer to the thread context
[in] com pointer to the lfsck component
Return values:
0 for success
negative error number on failure
Definition at line 1131 of file lfsck_engine.c.
References CDEBUG, D_LFSCK, ENTRY, lfsck_assistant_data::lad_mdt_phase1_list, lfsck_assistant_data::lad_name, lfsck_assistant_data::lad_ost_phase1_list, lfsck_assistant_data::lad_touch_gen, lfsck_async_interpret_args::laia_com, lfsck_async_interpret_args::laia_lr, lfsck_async_interpret_args::laia_ltd, lfsck_async_interpret_args::laia_ltds, lfsck_component::lc_data, lfsck_component::lc_lfsck, lfsck_component::lc_type, LE_QUERY, LEF_TO_OST, lfsck_async_interpret_common(), lfsck_async_request(), lfsck_env_info(), lfsck_lfsck2name(), LFSCK_QUERY, lfsck_tgt_put(), LFSCK_TYPE_LAYOUT, lfsck_instance::li_mdt_descs, lfsck_instance::li_ost_descs, list_empty(), list_entry, list_move_tail(), lfsck_request::lr_active, lfsck_request::lr_event, lfsck_request::lr_flags, lfsck_tgt_desc::ltd_exp, lfsck_tgt_desc::ltd_index, lfsck_tgt_desc::ltd_layout_gen, lfsck_tgt_desc::ltd_layout_phase_list, lfsck_tgt_descs::ltd_lock, lfsck_tgt_desc::ltd_namespace_gen, lfsck_tgt_desc::ltd_namespace_phase_list, lfsck_tgt_desc::ltd_ref, lfsck_thread_info::lti_laia, lfsck_thread_info::lti_lr, list_head::next, ptlrpc_prep_set(), ptlrpc_set_destroy(), ptlrpc_set_wait(), and RETURN.
Referenced by lfsck_assistant_engine().
static bool lfsck_assistant_req_empty (struct lfsck_assistant_data * lad) [inline, static]
Definition at line 1106 of file lfsck_engine.c.
References empty, lfsck_assistant_data::lad_lock, lfsck_assistant_data::lad_req_list, and list_empty().
Referenced by lfsck_assistant_engine().
static int lfsck_checkpoint (const struct lu_env * env, struct lfsck_instance * lfsck) [static]
Definition at line 389 of file lfsck_engine.c.
References cfs_time_beforeq(), cfs_time_current(), cfs_time_seconds(), lfsck_component::lc_link, lfsck_component::lc_ops, lfsck_operations::lfsck_checkpoint, LFSCK_CHECKPOINT_INTERVAL, lfsck_pos_fill(), lfsck_instance::li_list_scan, lfsck_instance::li_pos_checkpoint, lfsck_instance::li_time_last_checkpoint, lfsck_instance::li_time_next_checkpoint, likely, and list_for_each_entry.
Referenced by lfsck_master_dir_engine(), and lfsck_master_oit_engine().
void lfsck_close_dir (const struct lu_env * env, struct lfsck_instance * lfsck, int result)
Definition at line 297 of file lfsck_engine.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, ENTRY, EXIT, LASSERT, lfsck_component::lc_link_dir, lfsck_component::lc_ops, lfsck_operations::lfsck_close_dir, lfsck_di_dir_put(), lfsck_lmv_put(), lfsck_object_put(), lfsck_instance::li_di_dir, lfsck_instance::li_list_dir, lfsck_instance::li_lmv, lfsck_instance::li_obj_dir, list_for_each_entry, and lfsck_lmv::ll_exit_value.
Referenced by lfsck_exec_oit(), lfsck_master_engine(), lfsck_namespace_rescan_striped_dir(), lfsck_open_dir(), lfsck_post(), and lfsck_prep().
static void lfsck_di_dir_put (const struct lu_env * env, struct lfsck_instance * lfsck) [static]
Definition at line 82 of file lfsck_engine.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, lfsck_instance::li_cookie_dir, lfsck_instance::li_di_dir, lfsck_instance::li_lock, and lfsck_instance::li_obj_dir.
Referenced by lfsck_close_dir().
static void lfsck_di_oit_put (const struct lu_env * env, struct lfsck_instance * lfsck) [static]
Definition at line 69 of file lfsck_engine.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, lfsck_instance::li_di_oit, lfsck_instance::li_lock, and lfsck_instance::li_obj_oit.
Referenced by lfsck_master_engine().
static int lfsck_double_scan (const struct lu_env * env, struct lfsck_instance * lfsck) [static]
Definition at line 617 of file lfsck_engine.c.
References l_wait_event, lfsck_component::lc_link, lfsck_component::lc_ops, lfsck_operations::lfsck_double_scan, lfsck_instance::li_double_scan_count, lfsck_instance::li_list_double_scan, lfsck_instance::li_list_idle, lfsck_instance::li_lock, lfsck_instance::li_status, lfsck_instance::li_thread, list_for_each_entry, list_for_each_entry_safe, list_move_tail(), LS_CO_PAUSED, LS_PAUSED, and ptlrpc_thread::t_ctl_waitq.
Referenced by lfsck_master_engine().
static int lfsck_exec_dir (const struct lu_env * env, struct lfsck_instance * lfsck, struct lfsck_assistant_object * lso, struct lu_dirent * ent, __u16 type) [static]
Definition at line 551 of file lfsck_engine.c.
References lfsck_component::lc_link, lfsck_component::lc_ops, lfsck_operations::lfsck_exec_dir, lfsck_instance::li_list_scan, and list_for_each_entry.
Referenced by lfsck_master_dir_engine().
static int lfsck_exec_oit (const struct lu_env * env, struct lfsck_instance * lfsck, struct dt_object * obj) [static]
Definition at line 516 of file lfsck_engine.c.
References ENTRY, GOTO, LASSERT, lfsck_component::lc_link, lfsck_component::lc_ops, lfsck_close_dir(), lfsck_operations::lfsck_exec_oit, lfsck_fail(), lfsck_load_stripe_lmv(), lfsck_needs_scan_dir(), lfsck_open_dir(), lfsck_instance::li_list_scan, lfsck_instance::li_obj_dir, list_for_each_entry, and RETURN.
Referenced by lfsck_master_oit_engine().
static void lfsck_fail (const struct lu_env * env, struct lfsck_instance * lfsck, bool new_checked) [static]
Definition at line 287 of file lfsck_engine.c.
References lfsck_component::lc_link, lfsck_component::lc_ops, lfsck_operations::lfsck_fail, lfsck_instance::li_list_scan, and list_for_each_entry.
Referenced by lfsck_exec_oit(), lfsck_master_dir_engine(), and lfsck_master_oit_engine().
static int lfsck_load_stripe_lmv (const struct lu_env * env, struct lfsck_instance * lfsck, struct dt_object * obj) [static]
Definition at line 225 of file lfsck_engine.c.
References ENTRY, LASSERT, lfsck_env_info(), LFSCK_LMV_DEF_STRIPES, LFSCK_LMV_MAX_STRIPES, lfsck_object_get(), lfsck_read_stripe_lmv(), lfsck_instance::li_lmv, lfsck_instance::li_obj_dir, lfsck_lmv::ll_hash_type, lfsck_lmv::ll_lmv, lfsck_lmv::ll_lmv_master, lfsck_lmv::ll_lmv_slave, lfsck_lmv::ll_lslr, lfsck_lmv::ll_ref, lfsck_lmv::ll_stripes_allocated, LMV_HASH_TYPE_UNKNOWN, LMV_MAGIC, lmv_mds_md_v1::lmv_magic, lmv_mds_md_v1::lmv_stripe_count, lfsck_thread_info::lti_lmv, OBD_ALLOC_LARGE, OBD_ALLOC_PTR, OBD_FREE_PTR, RETURN, and stripes.
Referenced by lfsck_exec_oit(), and lfsck_prep().
static int lfsck_master_dir_engine (const struct lu_env * env, struct lfsck_instance * lfsck) [static]
Definition at line 678 of file lfsck_engine.c.
References CDEBUG, CFS_FAIL_TIMEOUT, cfs_fail_val, D_LFSCK, DFID, dt_index_operations::dio_it, dir, dt_object::do_index_ops, ENTRY, GOTO, lfsck_assistant_object_init(), lfsck_checkpoint(), lfsck_control_speed(), lfsck_dto2fid(), lfsck_env_info(), lfsck_exec_dir(), lfsck_fail(), lfsck_lfsck2name(), lfsck_unpack_ent(), lfsck_instance::li_args_dir, lfsck_instance::li_bookmark_ram, lfsck_instance::li_cookie_dir, lfsck_instance::li_di_dir, lfsck_instance::li_lock, lfsck_instance::li_new_scanned, lfsck_instance::li_obj_dir, lfsck_instance::li_pos_current, lfsck_instance::li_thread, lfsck_position::lp_oit_cookie, LPF_FAILOUT, LPX64, lfsck_thread_info::lti_key, LUDA_IGNORE, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_DELAY2, OBD_FAIL_LFSCK_FATAL2, PFID, RETURN, SVC_STOPPING, thread, thread_is_running(), thread_set_flags(), and unlikely.
Referenced by lfsck_master_oit_engine(), and lfsck_post().
int lfsck_master_engine (void * args)
Definition at line 996 of file lfsck_engine.c.
References CDEBUG, current_pid, D_LFSCK, DFID, dt_index_operations::dio_it, dt_object::do_index_ops, ENTRY, GOTO, l_wait_event, lfsck_close_dir(), lfsck_di_oit_put(), lfsck_double_scan(), lfsck_lfsck2name(), lfsck_master_oit_engine(), lfsck_pos_fill(), lfsck_post(), lfsck_prep(), lfsck_quit(), lfsck_thread_args_fini(), lfsck_verify_lpf(), lfsck_instance::li_args_dir, lfsck_instance::li_args_oit, lfsck_instance::li_di_oit, lfsck_instance::li_list_double_scan, lfsck_instance::li_list_scan, lfsck_instance::li_lock, lfsck_instance::li_master, lfsck_instance::li_obj_oit, lfsck_instance::li_pos_checkpoint, lfsck_instance::li_start_unplug, lfsck_instance::li_thread, list_empty(), lfsck_position::lp_dir_cookie, lfsck_position::lp_dir_parent, lfsck_position::lp_oit_cookie, LPU64, LPX64, lfsck_thread_args::lta_env, lfsck_thread_args::lta_lfsck, lfsck_thread_args::lta_lsp, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_CRASH, PFID, SVC_RUNNING, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, thread, thread_is_running(), and thread_set_flags().
Referenced by lfsck_start().
static int lfsck_master_oit_engine (const struct lu_env * env, struct lfsck_instance * lfsck) [static]
Object-table based iteration engine.
Object-table based iteration is the basic linear engine to scan all the objects on current device in turn. For each object, it calls all the registered LFSCK component(s)' API to perform related consistency verification.
It flushes related LFSCK trace files to disk via making checkpoint periodically. Then if the server crashed or the LFSCK is paused, the LFSCK can resume from the latest checkpoint.
It also controls the whole LFSCK speed via lfsck_control_speed() to avoid the server to become overload.
Parameters:
[in] env pointer to the thread context
[in] lfsck pointer to the lfsck instance
Return values:
positive number if all objects have been scanned
0 if the iteration is stopped or paused
negative error number on failure
Definition at line 811 of file lfsck_engine.c.
References CDEBUG, CFS_FAIL_TIMEOUT, cfs_fail_val, D_LFSCK, DFID, dt_index_operations::dio_it, dt_object::do_index_ops, dt_object_exists(), ENTRY, fid_idif_ost_idx(), fid_is_idif(), fid_is_igif(), fid_is_last_id(), fid_is_norm(), fid_is_sane(), fid_to_ostid(), fld_local_lookup(), fld_range_set_mdt(), fld_range_set_ost(), LASSERT, lfsck_bookmark::lb_param, lfsck_checkpoint(), lfsck_control_speed(), lfsck_dev_idx(), lfsck_dev_site(), lfsck_env_info(), lfsck_exec_oit(), lfsck_fail(), lfsck_lfsck2name(), lfsck_master_dir_engine(), lfsck_object_find_bottom(), lfsck_object_get(), lfsck_object_put(), lfsck_open_dir(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_current_oit_processed, lfsck_instance::li_di_dir, lfsck_instance::li_di_oit, lfsck_instance::li_global_root_fid, lfsck_instance::li_list_lmv, lfsck_instance::li_lmv, lfsck_instance::li_lock, lfsck_instance::li_master, lfsck_instance::li_new_scanned, lfsck_instance::li_obj_dir, lfsck_instance::li_obj_oit, lfsck_instance::li_oit_over, lfsck_instance::li_pos_current, lfsck_instance::li_thread, likely, list_del_init(), list_empty(), list_entry, lfsck_lmv_unit::llu_link, lfsck_lmv_unit::llu_lmv, lfsck_lmv_unit::llu_obj, lfsck_position::lp_oit_cookie, LPF_FAILOUT, LPU64, lu_seq_range::lsr_index, lfsck_thread_info::lti_fid, lfsck_thread_info::lti_oi, lfsck_thread_info::lti_range, lu_fid_eq(), list_head::next, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_CRASH, OBD_FAIL_LFSCK_DELAY1, OBD_FAIL_LFSCK_FATAL1, ost_id::oi, ostid_to_fid(), PFID, RETURN, seq_server_site::ss_server_fld, SVC_STOPPING, thread, thread_is_running(), thread_set_flags(), and unlikely.
Referenced by lfsck_master_engine().
static int lfsck_needs_scan_dir (const struct lu_env * env, struct lfsck_instance * lfsck, struct dt_object * obj) [static]
Check whether needs to scan the directory or not.
1) If we are not doing namespace LFSCK, or the given is not directory, then needs not to scan the . Otherwise, 2) Global /ROOT needs to be scanned, backend root needs not to be scanned. 3) If the is neither IGIF nor normal FID (including .lustre and its sub-directories that have been scanned when the LFSCK engine start), then needs not to be scanned. 4) If it is a remote object, then scanning the object will be done on the MDT on which the object really resides. 5) If the local object has normal FID, then needs to be scanned. Otherwise, 6) If the object has linkEA, then needs to be scanned. Otherwise, 7) If none of the previous conditions are true, we need to check the parent directories whether this subdirectory is in a tree that should be scanned. Set the parent as current , repeat 2)-7).
Parameters:
[in] env pointer to the thread context
[in] lfsck pointer to the lfsck instance
[in] obj pointer to the object to be checked
Return values:
positive number if the directory needs to be scanned
0 if the directory needs NOT to be scanned
negative error number on failure
Definition at line 132 of file lfsck_engine.c.
References dt_object_exists(), dt_read_lock(), dt_read_unlock(), dt_xattr_get(), fid_is_igif(), fid_is_norm(), fid_is_sane(), fld_local_lookup(), fld_range_set_mdt(), GOTO, LASSERT, lfsck_buf_get(), lfsck_dev_idx(), lfsck_dev_site(), lfsck_dto2fid(), lfsck_env_info(), lfsck_is_dead_obj(), lfsck_object_find_bottom(), lfsck_object_put(), lfsck_object_type(), lfsck_parent_fid(), lfsck_instance::li_global_root_fid, lfsck_instance::li_list_dir, lfsck_instance::li_local_root_fid, list_empty(), lu_seq_range::lsr_index, lfsck_thread_info::lti_fid, lfsck_thread_info::lti_range, lu_fid_eq(), MOR_TGT_CHILD, seq_server_site::ss_server_fld, unlikely, and XATTR_NAME_LINK.
Referenced by lfsck_exec_oit().
int lfsck_open_dir (const struct lu_env * env, struct lfsck_instance * lfsck, __u64 cookie)
Definition at line 337 of file lfsck_engine.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, dt_try_as_dir(), ENTRY, GOTO, dt_index_operations::dt_it_ops::init, LASSERT, lfsck_component::lc_ops, lfsck_close_dir(), lfsck_operations::lfsck_open_dir, lfsck_instance::li_args_dir, lfsck_instance::li_cookie_dir, lfsck_instance::li_di_dir, lfsck_instance::li_list_dir, lfsck_instance::li_lock, lfsck_instance::li_obj_dir, list_for_each_entry, and unlikely.
Referenced by lfsck_exec_oit(), lfsck_master_oit_engine(), lfsck_namespace_rescan_striped_dir(), lfsck_post(), and lfsck_prep().
static int lfsck_parent_fid (const struct lu_env * env, struct dt_object * obj, struct lu_fid * fid) [static]
Definition at line 96 of file lfsck_engine.c.
References dt_key, dt_lookup(), dt_try_as_dir(), lfsck_object_type(), and unlikely.
Referenced by lfsck_needs_scan_dir().
static int lfsck_post (const struct lu_env * env, struct lfsck_instance * lfsck, int result) [static]
Definition at line 570 of file lfsck_engine.c.
References CDEBUG, cfs_time_current(), cfs_time_seconds(), D_LFSCK, lfsck_component::lc_ops, lfsck_component::lc_type, LFSCK_CHECKPOINT_INTERVAL, lfsck_close_dir(), lfsck_lfsck2name(), lfsck_master_dir_engine(), lfsck_object_get(), lfsck_open_dir(), lfsck_pos_fill(), lfsck_operations::lfsck_post, lfsck_instance::li_list_lmv, lfsck_instance::li_list_scan, lfsck_instance::li_lmv, lfsck_instance::li_lock, lfsck_instance::li_obj_dir, lfsck_instance::li_pos_checkpoint, lfsck_instance::li_thread, lfsck_instance::li_time_last_checkpoint, lfsck_instance::li_time_next_checkpoint, list_del_init(), list_empty(), list_entry, list_for_each_entry_safe, lfsck_lmv_unit::llu_link, lfsck_lmv_unit::llu_lmv, lfsck_lmv_unit::llu_obj, list_head::next, and thread_is_running().
Referenced by lfsck_master_engine().
static int lfsck_prep (const struct lu_env * env, struct lfsck_instance * lfsck, struct lfsck_start_param * lsp) [static]
Definition at line 413 of file lfsck_engine.c.
References cfs_time_current(), cfs_time_seconds(), dt_index_operations::dio_it, dt_object::do_index_ops, dt_object_exists(), dt_object_remote(), ENTRY, fid_is_zero(), GOTO, LASSERT, lfsck_component::lc_new_checked, lfsck_component::lc_ops, lfsck_component::lc_pos_start, lfsck_operations::lfsck_checkpoint, LFSCK_CHECKPOINT_INTERVAL, lfsck_close_dir(), lfsck_load_stripe_lmv(), lfsck_object_find_bottom(), lfsck_object_put(), lfsck_object_type(), lfsck_open_dir(), lfsck_pos_fill(), lfsck_pos_is_eq(), lfsck_pos_is_zero(), lfsck_operations::lfsck_post, lfsck_operations::lfsck_prep, lfsck_instance::li_current_oit_processed, lfsck_instance::li_di_dir, lfsck_instance::li_di_oit, lfsck_instance::li_list_scan, lfsck_instance::li_lmv, lfsck_instance::li_master, lfsck_instance::li_obj_dir, lfsck_instance::li_obj_oit, lfsck_instance::li_oit_over, lfsck_instance::li_pos_checkpoint, lfsck_instance::li_pos_current, lfsck_instance::li_time_last_checkpoint, lfsck_instance::li_time_next_checkpoint, list_for_each_entry, list_for_each_entry_safe, lfsck_lmv::ll_lmv_master, lfsck_position::lp_dir_cookie, lfsck_position::lp_dir_parent, lfsck_position::lp_oit_cookie, RETURN, and unlikely.
Referenced by lfsck_master_engine().
static void lfsck_quit (const struct lu_env * env, struct lfsck_instance * lfsck) [static]
Definition at line 649 of file lfsck_engine.c.
References lfsck_component::lc_link, lfsck_component::lc_link_dir, lfsck_component::lc_ops, lfsck_operations::lfsck_quit, lfsck_instance::li_list_double_scan, lfsck_instance::li_list_idle, lfsck_instance::li_list_scan, lfsck_instance::li_lock, list_del_init(), list_for_each_entry_safe, and list_move_tail().
Referenced by lfsck_master_engine().
int lfsck_unpack_ent (struct lu_dirent * ent, __u64 * cookie, __u16 * type)
Definition at line 42 of file lfsck_engine.c.
References fid_le_to_cpu(), lu_dirent::lde_attrs, lu_dirent::lde_fid, lu_dirent::lde_hash, lu_dirent::lde_name, lu_dirent::lde_namelen, lu_dirent::lde_reclen, le16_to_cpu, le32_to_cpu, le64_to_cpu, luda_type::lt_type, LUDA_TYPE, and unlikely.
Referenced by lfsck_allow_regenerate_master_lmv(), lfsck_master_dir_engine(), lfsck_namespace_rescan_striped_dir(), lfsck_namespace_scan_local_lpf(), and lfsck_namespace_scan_shard().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.