Lustre: lustre/lfsck/lfsck_bookmark.c File Reference
lustre/lfsck/lfsck_bookmark.c File Reference
#include <lu_object.h>
#include <dt_object.h>
#include <lustre_fid.h>
#include <lustre/lustre_user.h>
#include "lfsck_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LFSCK
#define LFSCK_BOOKMARK_MAGIC 0x20130C1D
Functions
static void lfsck_bookmark_le_to_cpu (struct lfsck_bookmark *des, struct lfsck_bookmark *src)
void lfsck_bookmark_cpu_to_le (struct lfsck_bookmark *des, struct lfsck_bookmark *src)
static int lfsck_bookmark_load (const struct lu_env *env, struct lfsck_instance *lfsck)
int lfsck_bookmark_store (const struct lu_env *env, struct lfsck_instance *lfsck)
static int lfsck_bookmark_init (const struct lu_env *env, struct lfsck_instance *lfsck)
int lfsck_bookmark_setup (const struct lu_env *env, struct lfsck_instance *lfsck)
int lfsck_set_param (const struct lu_env *env, struct lfsck_instance *lfsck, struct lfsck_start *start, bool reset)
Define Documentation
#define DEBUG_SUBSYSTEM S_LFSCK
Definition at line 31 of file lfsck_bookmark.c.
#define LFSCK_BOOKMARK_MAGIC 0x20130C1D
Definition at line 40 of file lfsck_bookmark.c.
Referenced by lfsck_bookmark_init(), and lfsck_bookmark_load().
Function Documentation
void lfsck_bookmark_cpu_to_le (struct lfsck_bookmark * des, struct lfsck_bookmark * src)
Definition at line 54 of file lfsck_bookmark.c.
References cpu_to_le16, cpu_to_le32, fid_cpu_to_le(), lfsck_bookmark::lb_async_windows, lfsck_bookmark::lb_last_fid, lfsck_bookmark::lb_lpf_fid, lfsck_bookmark::lb_magic, lfsck_bookmark::lb_param, lfsck_bookmark::lb_speed_limit, and lfsck_bookmark::lb_version.
Referenced by lfsck_bookmark_store(), lfsck_create_lpf_local(), and lfsck_create_lpf_remote().
static int lfsck_bookmark_init (const struct lu_env * env, struct lfsck_instance * lfsck) [static]
Definition at line 142 of file lfsck_bookmark.c.
References lfsck_bookmark::lb_async_windows, lfsck_bookmark::lb_magic, lfsck_bookmark::lb_version, LFSCK_ASYNC_WIN_DEFAULT, LFSCK_BOOKMARK_MAGIC, lfsck_bookmark_store(), LFSCK_VERSION_V2, lfsck_instance::li_bookmark_ram, and lfsck_instance::li_mutex.
Referenced by lfsck_bookmark_setup().
static void lfsck_bookmark_le_to_cpu (struct lfsck_bookmark * des, struct lfsck_bookmark * src) [static]
Definition at line 42 of file lfsck_bookmark.c.
References fid_le_to_cpu(), lfsck_bookmark::lb_async_windows, lfsck_bookmark::lb_last_fid, lfsck_bookmark::lb_lpf_fid, lfsck_bookmark::lb_magic, lfsck_bookmark::lb_param, lfsck_bookmark::lb_speed_limit, lfsck_bookmark::lb_version, le16_to_cpu, and le32_to_cpu.
Referenced by lfsck_bookmark_load().
static int lfsck_bookmark_load (const struct lu_env * env, struct lfsck_instance * lfsck) [static]
Definition at line 66 of file lfsck_bookmark.c.
References CDEBUG, D_LFSCK, dt_record_read(), lfsck_bookmark::lb_magic, lfsck_bookmark_le_to_cpu(), LFSCK_BOOKMARK_MAGIC, lfsck_buf_get(), lfsck_lfsck2name(), lfsck_instance::li_bookmark_disk, lfsck_instance::li_bookmark_obj, and lfsck_instance::li_bookmark_ram.
Referenced by lfsck_bookmark_setup().
int lfsck_bookmark_setup (const struct lu_env * env, struct lfsck_instance * lfsck)
Definition at line 158 of file lfsck_bookmark.c.
References dt_locate(), dt_try_as_dir(), ENTRY, lfsck_bookmark::lb_async_windows, LFSCK_ASYNC_WIN_DEFAULT, LFSCK_BOOKMARK, lfsck_bookmark_init(), lfsck_bookmark_load(), lfsck_bookmark_store(), lfsck_object_put(), lfsck_instance::li_bookmark_obj, lfsck_instance::li_bookmark_ram, lfsck_instance::li_bottom, lfsck_instance::li_local_root_fid, lfsck_instance::li_los, lfsck_instance::li_mutex, local_file_find_or_create(), RETURN, and unlikely.
Referenced by lfsck_register().
int lfsck_bookmark_store (const struct lu_env * env, struct lfsck_instance * lfsck)
Definition at line 99 of file lfsck_bookmark.c.
References CDEBUG, D_LFSCK, dt_declare_record_write(), dt_record_write(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), ENTRY, GOTO, lfsck_bookmark_cpu_to_le(), lfsck_buf_get(), lfsck_lfsck2name(), lfsck_obj2dev(), lfsck_instance::li_bookmark_disk, lfsck_instance::li_bookmark_obj, and lfsck_instance::li_bookmark_ram.
Referenced by lfsck_bookmark_init(), lfsck_bookmark_setup(), lfsck_create_lpf(), lfsck_fid_alloc(), lfsck_set_param(), lfsck_set_speed(), lfsck_set_windows(), lfsck_start(), lfsck_update_lpf_entry(), lfsck_verify_lpf(), and lfsck_verify_lpf_pairs().
int lfsck_set_param (const struct lu_env * env, struct lfsck_instance * lfsck, struct lfsck_start * start, bool reset)
Definition at line 203 of file lfsck_bookmark.c.
References __lfsck_set_speed(), LASSERT, lfsck_bookmark::lb_async_windows, lfsck_bookmark::lb_param, LFSCK_ASYNC_WIN_DEFAULT, LFSCK_ASYNC_WIN_MAX, lfsck_bookmark_store(), LFSCK_SPEED_NO_LIMIT, lfsck_instance::li_bookmark_ram, lfsck_instance::li_drop_dryrun, LPF_ALL_TGT, LPF_CREATE_MDTOBJ, LPF_CREATE_OSTOBJ, LPF_DRYRUN, LPF_FAILOUT, LPF_OST_ORPHAN, lfsck_start::ls_async_windows, lfsck_start::ls_flags, lfsck_start::ls_speed_limit, lfsck_start::ls_valid, LSV_ASYNC_WINDOWS, LSV_CREATE_MDTOBJ, LSV_CREATE_OSTOBJ, LSV_DRYRUN, LSV_ERROR_HANDLE, and LSV_SPEED_LIMIT.
Referenced by lfsck_layout_master_prep(), lfsck_layout_prep(), lfsck_namespace_prep(), and lfsck_start().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.