Lustre: lustre/lfsck/lfsck_lib.c File Reference
lustre/lfsck/lfsck_lib.c File Reference
#include <linux/kthread.h>
#include <linux/sched.h>
#include <libcfs/list.h>
#include <lu_object.h>
#include <dt_object.h>
#include <md_object.h>
#include <lustre_fld.h>
#include <lustre_lib.h>
#include <lustre_net.h>
#include <lustre_lfsck.h>
#include <lustre/lustre_lfsck_user.h>
#include "lfsck_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LFSCK
#define LFSCK_CHECKPOINT_SKIP 1
Enumerations
enum lfsck_verify_lpf_types { LVLT_BY_BOOKMARK = 0, LVLT_BY_NAMEENTRY = 1 }
Functions
LU_KEY_INIT (lfsck, struct lfsck_thread_info)
static void lfsck_key_fini (const struct lu_context *ctx, struct lu_context_key *key, void *data)
LU_CONTEXT_KEY_DEFINE (lfsck, LCT_MD_THREAD|LCT_DT_THREAD)
LU_KEY_INIT_GENERIC (lfsck)
static DEFINE_SPINLOCK (lfsck_instance_lock)
static void lfsck_reset_ltd_status (struct lfsck_tgt_desc *ltd, enum lfsck_type type)
static int lfsck_tgt_descs_init (struct lfsck_tgt_descs *ltds)
static void lfsck_tgt_descs_fini (struct lfsck_tgt_descs *ltds)
static int __lfsck_add_target (const struct lu_env *env, struct lfsck_instance *lfsck, struct lfsck_tgt_desc *ltd, bool for_ost, bool locked)
static int lfsck_add_target_from_orphan (const struct lu_env *env, struct lfsck_instance *lfsck)
static struct lfsck_component * __lfsck_component_find (struct lfsck_instance *lfsck, __u16 type, struct list_head *list)
struct lfsck_component * lfsck_component_find (struct lfsck_instance *lfsck, __u16 type)
void lfsck_component_cleanup (const struct lu_env *env, struct lfsck_component *com)
int lfsck_fid_alloc (const struct lu_env *env, struct lfsck_instance *lfsck, struct lu_fid *fid, bool locked)
static int __lfsck_ibits_lock (const struct lu_env *env, struct lfsck_instance *lfsck, struct dt_object *obj, struct ldlm_res_id *resid, struct lustre_handle *lh, __u64 bits, enum ldlm_mode mode)
int lfsck_ibits_lock (const struct lu_env *env, struct lfsck_instance *lfsck, struct dt_object *obj, struct lustre_handle *lh, __u64 bits, enum ldlm_mode mode)
Request the specified ibits lock for the given object.
void lfsck_ibits_unlock (struct lustre_handle *lh, enum ldlm_mode mode)
Release the the specified ibits lock.
int lfsck_lock (const struct lu_env *env, struct lfsck_instance *lfsck, struct dt_object *obj, const char *name, struct lfsck_lock_handle *llh, __u64 bits, enum ldlm_mode mode)
Request compound ibits locks for the given <obj, name> pairs.
void lfsck_unlock (struct lfsck_lock_handle *llh)
Release the the compound ibits locks.
int lfsck_find_mdt_idx_by_fid (const struct lu_env *env, struct lfsck_instance *lfsck, const struct lu_fid *fid)
static int lfsck_lpf_remove_name_entry (const struct lu_env *env, struct lfsck_instance *lfsck, const char *name)
Remove the name entry from the .lustre/lost+found directory.
static int lfsck_create_lpf_local (const struct lu_env *env, struct lfsck_instance *lfsck, struct dt_object *child, struct lu_attr *la, struct dt_object_format *dof, const char *name)
static int lfsck_create_lpf_remote (const struct lu_env *env, struct lfsck_instance *lfsck, struct dt_object *child, struct lu_attr *la, struct dt_object_format *dof, const char *name)
static int lfsck_create_lpf (const struct lu_env *env, struct lfsck_instance *lfsck)
Create the MDTxxxx directory under /ROOT/.lustre/lost+found/.
static int lfsck_scan_lpf_bad_entries (const struct lu_env *env, struct lfsck_instance *lfsck)
Scan .lustre/lost+found for bad name entries and remove them.
static int lfsck_update_lpf_entry (const struct lu_env *env, struct lfsck_instance *lfsck, struct dt_object *parent, struct dt_object *child, const char *name, enum lfsck_verify_lpf_types type)
static int lfsck_verify_lpf_pairs (const struct lu_env *env, struct lfsck_instance *lfsck, struct dt_object *child, const char *name, struct lu_fid *fid, enum lfsck_verify_lpf_types type)
Check whether the back references the .
int lfsck_verify_lpf (const struct lu_env *env, struct lfsck_instance *lfsck)
Verify the /ROOT/.lustre/lost+found/ directory.
static int lfsck_fid_init (struct lfsck_instance *lfsck)
static void lfsck_fid_fini (struct lfsck_instance *lfsck)
void lfsck_instance_cleanup (const struct lu_env *env, struct lfsck_instance *lfsck)
static struct lfsck_instance * __lfsck_instance_find (struct dt_device *key, bool ref, bool unlink)
struct lfsck_instance * lfsck_instance_find (struct dt_device *key, bool ref, bool unlink)
static int lfsck_instance_add (struct lfsck_instance *lfsck)
void lfsck_bits_dump (struct seq_file *m, int bits, const char *names[], const char *prefix)
void lfsck_time_dump (struct seq_file *m, __u64 time, const char *name)
void lfsck_pos_dump (struct seq_file *m, struct lfsck_position *pos, const char *prefix)
void lfsck_pos_fill (const struct lu_env *env, struct lfsck_instance *lfsck, struct lfsck_position *pos, bool init)
bool __lfsck_set_speed (struct lfsck_instance *lfsck, __u32 limit)
void lfsck_control_speed (struct lfsck_instance *lfsck)
void lfsck_control_speed_by_self (struct lfsck_component *com)
static struct lfsck_thread_args * lfsck_thread_args_init (struct lfsck_instance *lfsck, struct lfsck_component *com, struct lfsck_start_param *lsp)
void lfsck_thread_args_fini (struct lfsck_thread_args *lta)
struct lfsck_assistant_data * lfsck_assistant_data_init (struct lfsck_assistant_operations *lao, const char *name)
struct lfsck_assistant_object * lfsck_assistant_object_init (const struct lu_env *env, const struct lu_fid *fid, const struct lu_attr *attr, __u64 cookie, bool is_dir)
struct dt_object * lfsck_assistant_object_load (const struct lu_env *env, struct lfsck_instance *lfsck, struct lfsck_assistant_object *lso)
int lfsck_async_interpret_common (const struct lu_env *env, struct ptlrpc_request *req, void *args, int rc)
Generic LFSCK asynchronous communication interpretor function.
static void lfsck_interpret (const struct lu_env *env, struct lfsck_instance *lfsck, struct ptlrpc_request *req, void *args, int result)
static int lfsck_stop_notify (const struct lu_env *env, struct lfsck_instance *lfsck, struct lfsck_tgt_descs *ltds, struct lfsck_tgt_desc *ltd, __u16 type)
static int lfsck_async_interpret (const struct lu_env *env, struct ptlrpc_request *req, void *args, int rc)
int lfsck_async_request (const struct lu_env *env, struct obd_export *exp, struct lfsck_request *lr, struct ptlrpc_request_set *set, ptlrpc_interpterer_t interpreter, void *args, int request)
int lfsck_query_all (const struct lu_env *env, struct lfsck_component *com)
int lfsck_start_assistant (const struct lu_env *env, struct lfsck_component *com, struct lfsck_start_param *lsp)
int lfsck_checkpoint_generic (const struct lu_env *env, struct lfsck_component *com)
void lfsck_post_generic (const struct lu_env *env, struct lfsck_component *com, int *result)
int lfsck_double_scan_generic (const struct lu_env *env, struct lfsck_component *com, int status)
void lfsck_quit_generic (const struct lu_env *env, struct lfsck_component *com)
int lfsck_get_speed (struct seq_file *m, struct dt_device *key)
int lfsck_set_speed (struct dt_device *key, __u32 val)
int lfsck_get_windows (struct seq_file *m, struct dt_device *key)
int lfsck_set_windows (struct dt_device *key, int val)
int lfsck_dump (struct seq_file *m, struct dt_device *key, enum lfsck_type type)
static int lfsck_stop_all (const struct lu_env *env, struct lfsck_instance *lfsck, struct lfsck_stop *stop)
static int lfsck_start_all (const struct lu_env *env, struct lfsck_instance *lfsck, struct lfsck_start *start)
int lfsck_start (const struct lu_env *env, struct dt_device *key, struct lfsck_start_param *lsp)
int lfsck_stop (const struct lu_env *env, struct dt_device *key, struct lfsck_stop *stop)
int lfsck_in_notify (const struct lu_env *env, struct dt_device *key, struct lfsck_request *lr, struct thandle *th)
int lfsck_query (const struct lu_env *env, struct dt_device *key, struct lfsck_request *req, struct lfsck_reply *rep, struct lfsck_query *que)
int lfsck_register_namespace (const struct lu_env *env, struct dt_device *key, struct ldlm_namespace *ns)
int lfsck_register (const struct lu_env *env, struct dt_device *key, struct dt_device *next, struct obd_device *obd, lfsck_out_notify notify, void *notify_data, bool master)
void lfsck_degister (const struct lu_env *env, struct dt_device *key)
int lfsck_add_target (const struct lu_env *env, struct dt_device *key, struct dt_device *tgt, struct obd_export *exp, __u32 index, bool for_ost)
void lfsck_del_target (const struct lu_env *env, struct dt_device *key, struct dt_device *tgt, __u32 index, bool for_ost)
static int __init lfsck_init (void)
static void __exit lfsck_exit (void)
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre File System Checker")
MODULE_VERSION (LUSTRE_VERSION_STRING)
MODULE_LICENSE ("GPL")
module_init (lfsck_init)
module_exit (lfsck_exit)
Variables
static struct list_head lfsck_instance_list
static struct list_head lfsck_ost_orphan_list
static struct list_head lfsck_mdt_orphan_list
const char * lfsck_flags_names []
const char * lfsck_param_names []
const char dot [] = "."
const char dotdot [] = ".."
static const char dotlustre [] = ".lustre"
static const char lostfound [] = "lost+found"
Define Documentation
#define DEBUG_SUBSYSTEM S_LFSCK
Definition at line 31 of file lfsck_lib.c.
#define LFSCK_CHECKPOINT_SKIP 1
Definition at line 47 of file lfsck_lib.c.
Referenced by lfsck_checkpoint_generic().
Enumeration Type Documentation
enum lfsck_verify_lpf_types
Enumerator:
LVLT_BY_BOOKMARK
LVLT_BY_NAMEENTRY
Definition at line 92 of file lfsck_lib.c.
Function Documentation
static int __lfsck_add_target (const struct lu_env * env, struct lfsck_instance * lfsck, struct lfsck_tgt_desc * ltd, bool for_ost, bool locked) [static]
Definition at line 171 of file lfsck_lib.c.
References CERROR, CFS_ALLOCATE_BITMAP(), cfs_bitmap_check(), cfs_bitmap_copy(), cfs_bitmap_set(), CFS_FREE_BITMAP, dt_device::dd_lu_dev, ENTRY, GOTO, LASSERT, lu_device::ld_obd, lfsck_assign_tgt(), lfsck_lfsck2name(), lfsck_instance::li_mdt_descs, lfsck_instance::li_ost_descs, lfsck_tgt_desc::ltd_index, lfsck_tgt_descs::ltd_rw_sem, lfsck_tgt_desc::ltd_tgt, lfsck_tgt_descs::ltd_tgtnr, lfsck_tgt_descs::ltd_tgts_bitmap, lfsck_tgt_descs::ltd_tgts_idx, max, OBD_ALLOC_PTR, obd_device::obd_name, cfs_bitmap::size, and TGT_PTRS_PER_BLOCK.
Referenced by lfsck_add_target(), and lfsck_add_target_from_orphan().
static struct lfsck_component* __lfsck_component_find (struct lfsck_instance * lfsck, __u16 type, struct list_head * list) [static, read]
Definition at line 282 of file lfsck_lib.c.
References lfsck_component::lc_link, lfsck_component::lc_type, and list_for_each_entry.
Referenced by lfsck_component_find(), lfsck_start(), and lfsck_stop_notify().
static int __lfsck_ibits_lock (const struct lu_env * env, struct lfsck_instance * lfsck, struct dt_object * obj, struct ldlm_res_id * resid, struct lustre_handle * lh, __u64 bits, enum ldlm_mode mode) [static]
Definition at line 355 of file lfsck_lib.c.
References __u64, ldlm_inodebits::bits, dt_object_lock(), dt_object_remote(), ldlm_enqueue_info::ei_cb_bl, ldlm_enqueue_info::ei_cb_cp, ldlm_enqueue_info::ei_mode, ldlm_enqueue_info::ei_type, ELDLM_OK, ldlm_policy_data::l_inodebits, LASSERT, ldlm_blocking_ast(), ldlm_cli_enqueue_local(), ldlm_completion_ast(), LDLM_FL_ATOMIC_CB, LDLM_IBITS, lfsck_env_info(), lfsck_instance::li_namespace, lfsck_thread_info::lti_einfo, lfsck_thread_info::lti_policy, and LVB_T_NONE.
Referenced by lfsck_ibits_lock(), and lfsck_lock().
static struct lfsck_instance* __lfsck_instance_find (struct dt_device * key, bool ref, bool unlink) [static, read]
Definition at line 1694 of file lfsck_lib.c.
References lfsck_instance_get(), lfsck_instance_list, lfsck_instance::li_bottom, lfsck_instance::li_link, list_del_init(), and list_for_each_entry.
Referenced by lfsck_add_target(), lfsck_del_target(), and lfsck_instance_find().
bool __lfsck_set_speed (struct lfsck_instance * lfsck, __u32 limit)
Definition at line 1830 of file lfsck_lib.c.
References lfsck_bookmark::lb_speed_limit, LFSCK_SPEED_NO_LIMIT, lfsck_instance::li_bookmark_ram, lfsck_instance::li_sleep_jif, and lfsck_instance::li_sleep_rate.
Referenced by lfsck_set_param(), lfsck_set_speed(), and lfsck_start().
static DEFINE_SPINLOCK (lfsck_instance_lock) [static]
int lfsck_add_target (const struct lu_env * env, struct dt_device * key, struct dt_device * tgt, struct obd_export * exp, __u32 index, bool for_ost)
Definition at line 3661 of file lfsck_lib.c.
References __lfsck_add_target(), __lfsck_instance_find(), ENTRY, INIT_LIST_HEAD, lfsck_instance_put(), lfsck_mdt_orphan_list, lfsck_ost_orphan_list, lfsck_tgt_put(), list_add_tail(), lfsck_tgt_desc::ltd_exp, lfsck_tgt_desc::ltd_index, lfsck_tgt_desc::ltd_key, lfsck_tgt_desc::ltd_layout_list, lfsck_tgt_desc::ltd_layout_phase_list, lfsck_tgt_desc::ltd_namespace_list, lfsck_tgt_desc::ltd_namespace_phase_list, lfsck_tgt_desc::ltd_orphan_list, lfsck_tgt_desc::ltd_ref, lfsck_tgt_desc::ltd_tgt, OBD_ALLOC_PTR, and RETURN.
Referenced by lod_add_device().
static int lfsck_add_target_from_orphan (const struct lu_env * env, struct lfsck_instance * lfsck) [static]
Definition at line 236 of file lfsck_lib.c.
References __lfsck_add_target(), head, lfsck_mdt_orphan_list, lfsck_ost_orphan_list, lfsck_instance::li_bottom, lfsck_instance::li_mdt_descs, lfsck_instance::li_ost_descs, list_del_init(), list_empty(), list_entry, list_for_each_entry_safe, list_move_tail(), lfsck_tgt_desc::ltd_key, lfsck_tgt_descs::ltd_orphan, lfsck_tgt_desc::ltd_orphan_list, lfsck_tgt_descs::ltd_rw_sem, and list_head::next.
Referenced by lfsck_register().
struct lfsck_assistant_data* lfsck_assistant_data_init (struct lfsck_assistant_operations * lao, const char * name) [read]
Definition at line 1929 of file lfsck_lib.c.
References CFS_ALLOCATE_BITMAP(), INIT_LIST_HEAD, lfsck_assistant_data::lad_bitmap, lfsck_assistant_data::lad_lock, lfsck_assistant_data::lad_mdt_list, lfsck_assistant_data::lad_mdt_phase1_list, lfsck_assistant_data::lad_mdt_phase2_list, lfsck_assistant_data::lad_name, lfsck_assistant_data::lad_ops, lfsck_assistant_data::lad_ost_list, lfsck_assistant_data::lad_ost_phase1_list, lfsck_assistant_data::lad_ost_phase2_list, lfsck_assistant_data::lad_req_list, lfsck_assistant_data::lad_thread, OBD_ALLOC_PTR, OBD_FREE_PTR, and ptlrpc_thread::t_ctl_waitq.
Referenced by lfsck_layout_setup(), and lfsck_namespace_setup().
struct lfsck_assistant_object* lfsck_assistant_object_init (const struct lu_env * env, const struct lu_fid * fid, const struct lu_attr * attr, __u64 cookie, bool is_dir) [read]
Definition at line 1959 of file lfsck_lib.c.
References lfsck_assistant_object::lso_attr, lfsck_assistant_object::lso_fid, lfsck_assistant_object::lso_is_dir, lfsck_assistant_object::lso_oit_cookie, lfsck_assistant_object::lso_ref, and OBD_ALLOC_PTR.
Referenced by lfsck_layout_scan_stripes(), lfsck_master_dir_engine(), lfsck_namespace_close_dir(), and lfsck_namespace_rescan_striped_dir().
struct dt_object* lfsck_assistant_object_load (const struct lu_env * env, struct lfsck_instance * lfsck, struct lfsck_assistant_object * lso) [read]
Definition at line 1982 of file lfsck_lib.c.
References dt_object_exists(), dt_try_as_dir(), lfsck_is_dead_obj(), lfsck_object_find_bottom(), lfsck_object_put(), lfsck_assistant_object::lso_dead, lfsck_assistant_object::lso_fid, lfsck_assistant_object::lso_is_dir, and unlikely.
Referenced by lfsck_layout_assistant_handler_p1(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_handle_striped_master(), and lfsck_namespace_striped_dir_rescan().
static int lfsck_async_interpret (const struct lu_env * env, struct ptlrpc_request * req, void * args, int rc) [static]
Definition at line 2352 of file lfsck_lib.c.
References lfsck_async_interpret_args::laia_ltd, lfsck_async_interpret_args::laia_ltds, lfsck_async_interpret_args::laia_result, lfsck_interpret(), lfsck_tgt_put(), and lfsck_instance::li_mdt_descs.
Referenced by lfsck_start_all(), and lfsck_stop_all().
int lfsck_async_interpret_common (const struct lu_env * env, struct ptlrpc_request * req, void * args, int rc)
Generic LFSCK asynchronous communication interpretor function.
The LFSCK RPC reply for both the event notification and status querying will be handled here.
Parameters:
[in] env pointer to the thread context
[in] req pointer to the LFSCK request
[in] args pointer to the lfsck_async_interpret_args
[in] rc the result for handling the LFSCK request
Return values:
0 for success
negative error number on failure
Definition at line 2021 of file lfsck_lib.c.
References CDEBUG, D_LFSCK, lfsck_assistant_data::lad_mdt_list, lfsck_assistant_data::lad_mdt_phase1_list, lfsck_assistant_data::lad_mdt_phase2_list, lfsck_assistant_data::lad_name, lfsck_assistant_data::lad_ost_list, lfsck_assistant_data::lad_ost_phase1_list, lfsck_assistant_data::lad_ost_phase2_list, lfsck_async_interpret_args::laia_com, lfsck_async_interpret_args::laia_lr, lfsck_async_interpret_args::laia_ltd, lfsck_async_interpret_args::laia_ltds, lfsck_async_interpret_args::laia_shared, LASSERT, lfsck_component::lc_data, lfsck_component::lc_file_ram, lfsck_component::lc_lfsck, lfsck_component::lc_type, LE_PEER_EXIT, LE_PHASE1_DONE, LE_PHASE2_DONE, LE_QUERY, LE_START, LE_STOP, LEF_QUERY_ALL, LEF_TO_OST, LF_INCOMPLETE, lfsck_component_put(), lfsck_lad_set_bitmap(), lfsck_lfsck2name(), lfsck_reset_ltd_status(), lfsck_tgt_put(), LFSCK_TYPE_LAYOUT, lfsck_instance::li_master, list, list_add_tail(), list_del_init(), list_empty(), lfsck_layout::ll_flags, lfsck_namespace::ln_flags, lfsck_request::lr_event, lfsck_request::lr_flags, lfsck_reply::lr_repaired, lfsck_reply::lr_status, LS_SCANNING_PHASE1, LS_SCANNING_PHASE2, lfsck_tgt_desc::ltd_dead, lfsck_tgt_desc::ltd_index, lfsck_tgt_desc::ltd_layout_done, lfsck_tgt_desc::ltd_layout_list, lfsck_tgt_desc::ltd_layout_phase_list, lfsck_tgt_desc::ltd_layout_repaired, lfsck_tgt_desc::ltd_layout_status, lfsck_tgt_descs::ltd_lock, lfsck_tgt_desc::ltd_namespace_done, lfsck_tgt_desc::ltd_namespace_list, lfsck_tgt_desc::ltd_namespace_phase_list, lfsck_tgt_desc::ltd_namespace_repaired, lfsck_tgt_desc::ltd_namespace_status, req_capsule_server_get(), RMF_LFSCK_REPLY, and ptlrpc_request::rq_pill.
Referenced by lfsck_assistant_notify_others(), lfsck_assistant_query_others(), lfsck_interpret(), lfsck_query_all(), and lfsck_stop_notify().
int lfsck_async_request (const struct lu_env * env, struct obd_export * exp, struct lfsck_request * lr, struct ptlrpc_request_set * set, ptlrpc_interpterer_t interpreter, void * args, int request)
Definition at line 2369 of file lfsck_lib.c.
References CDEBUG, class_exp2cliimp(), D_LFSCK, obd_export::exp_obd, lfsck_async_interpret_args::laia_com, lfsck_component_get(), LFSCK_NOTIFY, LFSCK_QUERY, LUSTRE_OBD_VERSION, obd_device::obd_name, ptlrpc_req_async_args, ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), ptlrpc_set_add_req(), req_capsule_client_get(), RMF_LFSCK_REQUEST, ptlrpc_request::rq_allow_intr, ptlrpc_request::rq_pill, RQF_LFSCK_NOTIFY, and RQF_LFSCK_QUERY.
Referenced by lfsck_assistant_notify_others(), lfsck_assistant_query_others(), lfsck_layout_assistant_sync_failures(), lfsck_namespace_assistant_sync_failures(), lfsck_query_all(), lfsck_start_all(), lfsck_stop_all(), and lfsck_stop_notify().
void lfsck_bits_dump (struct seq_file * m, int bits, const char * names[], const char * prefix)
Definition at line 1741 of file lfsck_lib.c.
Referenced by lfsck_layout_dump(), and lfsck_namespace_dump().
int lfsck_checkpoint_generic (const struct lu_env * env, struct lfsck_component * com)
Definition at line 2531 of file lfsck_lib.c.
References l_wait_event, lfsck_assistant_data::lad_req_list, lfsck_assistant_data::lad_thread, lfsck_component::lc_data, lfsck_component::lc_lfsck, LFSCK_CHECKPOINT_SKIP, lfsck_instance::li_thread, list_empty(), ptlrpc_thread::t_ctl_waitq, thread_is_running(), and thread_is_stopped().
Referenced by lfsck_layout_master_checkpoint(), and lfsck_namespace_checkpoint().
void lfsck_component_cleanup (const struct lu_env * env, struct lfsck_component * com)
Definition at line 318 of file lfsck_lib.c.
References lfsck_component::lc_link, lfsck_component::lc_link_dir, lfsck_component_put(), list_del_init(), and list_empty().
Referenced by lfsck_instance_cleanup(), lfsck_layout_setup(), and lfsck_namespace_setup().
struct lfsck_component* lfsck_component_find (struct lfsck_instance * lfsck, __u16 type) [read]
Definition at line 295 of file lfsck_lib.c.
References __lfsck_component_find(), lfsck_component_get(), lfsck_instance::li_list_double_scan, lfsck_instance::li_list_idle, lfsck_instance::li_list_scan, and lfsck_instance::li_lock.
Referenced by lfsck_dump(), lfsck_in_notify(), lfsck_orphan_it_init(), and lfsck_query().
void lfsck_control_speed (struct lfsck_instance * lfsck)
Definition at line 1857 of file lfsck_lib.c.
References l_wait_event, lfsck_instance::li_new_scanned, lfsck_instance::li_sleep_jif, lfsck_instance::li_sleep_rate, lfsck_instance::li_thread, LWI_ON_SIGNAL_NOOP, LWI_TIMEOUT_INTR, ptlrpc_thread::t_ctl_waitq, thread, and thread_is_running().
Referenced by lfsck_master_dir_engine(), lfsck_master_oit_engine(), and lfsck_namespace_scan_shard().
void lfsck_control_speed_by_self (struct lfsck_component * com)
Definition at line 1874 of file lfsck_lib.c.
References l_wait_event, lfsck_component::lc_lfsck, lfsck_component::lc_new_scanned, lfsck_instance::li_sleep_jif, lfsck_instance::li_sleep_rate, lfsck_instance::li_thread, LWI_ON_SIGNAL_NOOP, LWI_TIMEOUT_INTR, ptlrpc_thread::t_ctl_waitq, thread, and thread_is_running().
Referenced by lfsck_layout_scan_orphan(), lfsck_namespace_double_scan_one_trace_file(), and lfsck_namespace_scan_local_lpf().
static int lfsck_create_lpf (const struct lu_env * env, struct lfsck_instance * lfsck) [static]
Create the MDTxxxx directory under /ROOT/.lustre/lost+found/.
The /ROOT/.lustre/lost+found/MDTxxxx/ directory is used for holding orphans and other uncertain inconsistent objects found during the LFSCK. Such directory will be created by the LFSCK engine on the local MDT before the LFSCK scanning.
Parameters:
[in] env pointer to the thread context
[in] lfsck pointer to the lfsck instance
Return values:
0 for success
negative error number on failure
Definition at line 989 of file lfsck_lib.c.
References cfs_time_current_sec(), dt_object_format::dof_type, dt_key, dt_lookup(), dt_mode_to_dft(), dt_object_exists(), dt_try_as_dir(), ENTRY, fid_is_zero(), GOTO, LA_ATIME, lu_attr::la_atime, LA_CTIME, lu_attr::la_ctime, LA_GID, LA_MODE, lu_attr::la_mode, LA_MTIME, lu_attr::la_mtime, LA_UID, lu_attr::la_valid, LASSERT, lfsck_bookmark::lb_lpf_fid, LCK_PW, lfsck_bookmark_store(), lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_dev_idx(), lfsck_env_info(), lfsck_fid_alloc(), lfsck_lock(), lfsck_object_find_bottom(), lfsck_object_put(), lfsck_unlock(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_lpf_obj, lfsck_instance::li_lpf_root_obj, lfsck_instance::li_master, lfsck_thread_info::lti_dof, lfsck_thread_info::lti_fid2, lfsck_thread_info::lti_la, lfsck_thread_info::lti_llh, MDS_INODELOCK_UPDATE, name, RETURN, and unlikely.
Referenced by lfsck_verify_lpf().
static int lfsck_create_lpf_local (const struct lu_env * env, struct lfsck_instance * lfsck, struct dt_object * child, struct lu_attr * la, struct dt_object_format * dof, const char * name) [static]
Definition at line 615 of file lfsck_lib.c.
References dot, dotdot, dt_create(), dt_declare_create(), dt_declare_insert(), dt_declare_record_write(), dt_declare_ref_add(), dt_declare_xattr_set(), dt_insert(), dt_key, dt_record_write(), dt_ref_add(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_try_as_dir(), dt_write_lock(), dt_write_unlock(), dt_xattr_set(), ENTRY, GOTO, lu_buf::lb_buf, lfsck_bookmark::lb_lpf_fid, linkea_data::ld_buf, linkea_data::ld_leh, link_ea_header::leh_len, lfsck_bookmark_cpu_to_le(), lfsck_buf_get(), lfsck_buf_init(), lfsck_dto2fid(), lfsck_env_info(), lfsck_name_get_const(), lfsck_obj2dev(), lfsck_instance::li_bookmark_disk, lfsck_instance::li_bookmark_obj, lfsck_instance::li_bookmark_ram, lfsck_instance::li_lpf_root_obj, linkea_add_buf(), linkea_data_new(), lfsck_thread_info::lti_dt_rec, LU_LPF_FID, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, RETURN, stop, and XATTR_NAME_LINK.
Referenced by lfsck_create_lpf().
static int lfsck_create_lpf_remote (const struct lu_env * env, struct lfsck_instance * lfsck, struct dt_object * child, struct lu_attr * la, struct dt_object_format * dof, const char * name) [static]
Definition at line 774 of file lfsck_lib.c.
References CDEBUG, D_LFSCK, DFID, dot, dotdot, dt_create(), dt_declare_create(), dt_declare_insert(), dt_declare_record_write(), dt_declare_ref_add(), dt_declare_xattr_set(), dt_insert(), dt_key, dt_record_write(), dt_ref_add(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_try_as_dir(), dt_write_lock(), dt_write_unlock(), dt_xattr_set(), ENTRY, GOTO, lu_buf::lb_buf, lfsck_bookmark::lb_lpf_fid, linkea_data::ld_buf, linkea_data::ld_leh, link_ea_header::leh_len, lfsck_bookmark_cpu_to_le(), lfsck_buf_get(), lfsck_buf_init(), lfsck_dto2fid(), lfsck_env_info(), lfsck_lfsck2name(), lfsck_name_get_const(), lfsck_obj2dev(), lfsck_instance::li_bookmark_disk, lfsck_instance::li_bookmark_obj, lfsck_instance::li_bookmark_ram, lfsck_instance::li_lpf_root_obj, linkea_add_buf(), linkea_data_new(), lfsck_thread_info::lti_dt_rec, LU_LPF_FID, PFID, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, RETURN, stop, thandle::th_sync, and XATTR_NAME_LINK.
Referenced by lfsck_create_lpf().
void lfsck_degister (const struct lu_env * env, struct dt_device * key)
Definition at line 3651 of file lfsck_lib.c.
References lfsck_instance_find(), and lfsck_instance_put().
Referenced by mdd_device_shutdown(), and ofd_fini().
void lfsck_del_target (const struct lu_env * env, struct dt_device * key, struct dt_device * tgt, __u32 index, bool for_ost)
Definition at line 3710 of file lfsck_lib.c.
References __lfsck_instance_find(), cfs_bitmap_clear(), head, LASSERT, lfsck_assign_tgt(), lfsck_instance_put(), lfsck_ltd2tgt(), lfsck_mdt_orphan_list, lfsck_ost_orphan_list, lfsck_stop_notify(), lfsck_tgt_put(), LFSCK_TYPE_LAYOUT, LFSCK_TYPE_NAMESPACE, lfsck_instance::li_mdt_descs, lfsck_instance::li_ost_descs, list_del_init(), list_for_each_entry, lfsck_tgt_desc::ltd_dead, lfsck_tgt_descs::ltd_lock, lfsck_tgt_descs::ltd_orphan, lfsck_tgt_desc::ltd_orphan_list, lfsck_tgt_descs::ltd_rw_sem, lfsck_tgt_desc::ltd_tgt, lfsck_tgt_descs::ltd_tgtnr, lfsck_tgt_descs::ltd_tgts_bitmap, cfs_bitmap::size, and unlikely.
Referenced by __lod_del_device().
int lfsck_double_scan_generic (const struct lu_env * env, struct lfsck_component * com, int status)
Definition at line 2580 of file lfsck_lib.c.
References CDEBUG, D_LFSCK, l_wait_event, lfsck_assistant_data::lad_assistant_status, lfsck_assistant_data::lad_exit, lfsck_assistant_data::lad_in_double_scan, lfsck_assistant_data::lad_name, lfsck_assistant_data::lad_thread, lfsck_assistant_data::lad_to_double_scan, lfsck_component::lc_data, lfsck_component::lc_lfsck, lfsck_lfsck2name(), lfsck_instance::li_thread, LS_SCANNING_PHASE2, ptlrpc_thread::t_ctl_waitq, and thread_is_stopped().
Referenced by lfsck_layout_master_double_scan(), and lfsck_namespace_double_scan().
int lfsck_dump (struct seq_file * m, struct dt_device * key, enum lfsck_type type)
Definition at line 2745 of file lfsck_lib.c.
References ENTRY, lfsck_component::lc_ops, LCT_DT_THREAD, LCT_MD_THREAD, lfsck_component_find(), lfsck_component_put(), lfsck_operations::lfsck_dump, lfsck_instance_find(), lfsck_instance_put(), likely, lu_env_fini(), lu_env_init(), and RETURN.
Referenced by mdd_lfsck_layout_seq_show(), and mdd_lfsck_namespace_seq_show().
static void __exit lfsck_exit (void) [static]
Definition at line 3807 of file lfsck_lib.c.
References LASSERT, lfsck_instance_list, lfsck_mdt_orphan_list, lfsck_ost_orphan_list, lfsck_tgt_put(), lfsck_thread_key, list_del_init(), list_empty(), list_for_each_entry_safe, lfsck_tgt_desc::ltd_orphan_list, and lu_context_key_degister().
int lfsck_fid_alloc (const struct lu_env * env, struct lfsck_instance * lfsck, struct lu_fid * fid, bool locked)
Definition at line 329 of file lfsck_lib.c.
References ENTRY, lfsck_bookmark::lb_last_fid, lfsck_bookmark_store(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_mutex, lfsck_instance::li_seq, RETURN, and seq_client_alloc_fid().
Referenced by lfsck_create_lpf(), and lfsck_layout_recreate_parent().
static void lfsck_fid_fini (struct lfsck_instance * lfsck) [static]
Definition at line 1604 of file lfsck_lib.c.
References lfsck_instance::li_seq, OBD_FREE_PTR, and seq_client_fini().
Referenced by lfsck_instance_cleanup().
static int lfsck_fid_init (struct lfsck_instance * lfsck) [static]
Definition at line 1566 of file lfsck_lib.c.
References ENTRY, fid_is_sane(), GOTO, lfsck_bookmark::lb_last_fid, lu_client_seq::lcs_fid, lfsck_dev_site(), lfsck_lfsck2name(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_seq, LUSTRE_SEQ_METADATA, MAX_OBD_NAME, OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, RETURN, seq_client_init(), seq_server_site::ss_server_seq, and unlikely.
Referenced by lfsck_register().
int lfsck_find_mdt_idx_by_fid (const struct lu_env * env, struct lfsck_instance * lfsck, const struct lu_fid * fid)
Definition at line 526 of file lfsck_lib.c.
References fld_range_set_mdt(), fld_server_lookup(), lfsck_dev_site(), lfsck_env_info(), lu_seq_range::lsr_index, lfsck_thread_info::lti_range, and seq_server_site::ss_server_fld.
Referenced by lfsck_find_dev_by_fid(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_create_orphan_dir(), and lfsck_namespace_handle_striped_master().
int lfsck_get_speed (struct seq_file * m, struct dt_device * key)
Definition at line 2631 of file lfsck_lib.c.
References ENTRY, lfsck_bookmark::lb_speed_limit, LCT_DT_THREAD, LCT_MD_THREAD, lfsck_instance_find(), lfsck_instance_put(), lfsck_instance::li_bookmark_ram, likely, lu_env_fini(), lu_env_init(), and RETURN.
Referenced by mdd_lfsck_speed_limit_seq_show().
int lfsck_get_windows (struct seq_file * m, struct dt_device * key)
Definition at line 2684 of file lfsck_lib.c.
References ENTRY, lfsck_bookmark::lb_async_windows, LCT_DT_THREAD, LCT_MD_THREAD, lfsck_instance_find(), lfsck_instance_put(), lfsck_instance::li_bookmark_ram, likely, lu_env_fini(), lu_env_init(), and RETURN.
Referenced by mdd_lfsck_async_windows_seq_show().
int lfsck_ibits_lock (const struct lu_env * env, struct lfsck_instance * lfsck, struct dt_object * obj, struct lustre_handle * lh, __u64 bits, enum ldlm_mode mode)
Request the specified ibits lock for the given object.
Before the LFSCK modifying on the namespace visible object, it needs to acquire related ibits ldlm lock.
Parameters:
[in] env pointer to the thread context
[in] lfsck pointer to the lfsck instance
[in] obj pointer to the dt_object to be locked
[out] lh pointer to the lock handle
[in] bits the bits for the ldlm lock to be acquired
[in] mode the mode for the ldlm lock to be acquired
Return values:
0 for success
negative error number on failure
Definition at line 415 of file lfsck_lib.c.
References __lfsck_ibits_lock(), fid_build_reg_res_name(), LASSERT, lfsck_dto2fid(), lfsck_env_info(), lfsck_thread_info::lti_resid, and lustre_handle_is_used().
Referenced by lfsck_layout_check_parent(), lfsck_layout_conflict_create(), lfsck_layout_master_exec_oit(), lfsck_layout_recreate_lovea(), lfsck_layout_repair_dangling(), lfsck_layout_repair_multiple_references(), lfsck_layout_repair_unmatched_pair(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_double_scan_dir(), lfsck_namespace_exec_oit(), lfsck_namespace_insert_orphan(), lfsck_namespace_repair_dirent(), lfsck_namespace_repair_nlink(), lfsck_namespace_replace_cond(), lfsck_namespace_set_lmv_master(), lfsck_namespace_shrink_linkea(), lfsck_namespace_striped_dir_rescan(), lfsck_namespace_update_lmv(), lfsck_remove_lmv(), and lfsck_verify_lpf_pairs().
void lfsck_ibits_unlock (struct lustre_handle * lh, enum ldlm_mode mode)
Release the the specified ibits lock.
If the lock has been acquired before, release it and cleanup the handle. Otherwise, do nothing.
Parameters:
[in] lh pointer to the lock handle
[in] mode the mode for the ldlm lock to be released
Definition at line 436 of file lfsck_lib.c.
References ldlm_lock_decref(), and lustre_handle_is_used().
Referenced by lfsck_layout_check_parent(), lfsck_layout_conflict_create(), lfsck_layout_master_exec_oit(), lfsck_layout_recreate_lovea(), lfsck_layout_repair_dangling(), lfsck_layout_repair_multiple_references(), lfsck_layout_repair_unmatched_pair(), lfsck_lock(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_double_scan_dir(), lfsck_namespace_dsd_multiple(), lfsck_namespace_dsd_orphan(), lfsck_namespace_dsd_single(), lfsck_namespace_exec_oit(), lfsck_namespace_insert_orphan(), lfsck_namespace_repair_dirent(), lfsck_namespace_repair_nlink(), lfsck_namespace_replace_cond(), lfsck_namespace_set_lmv_master(), lfsck_namespace_shrink_linkea(), lfsck_namespace_striped_dir_rescan(), lfsck_namespace_update_lmv(), lfsck_remove_lmv(), lfsck_unlock(), and lfsck_verify_lpf_pairs().
int lfsck_in_notify (const struct lu_env * env, struct dt_device * key, struct lfsck_request * lr, struct thandle * th)
Definition at line 3296 of file lfsck_lib.c.
References ENTRY, lfsck_component::lc_ops, LE_CONDITIONAL_DESTROY, LE_FID_ACCESSED, LE_PAIRS_VERIFY, LE_PEER_EXIT, LE_PHASE1_DONE, LE_PHASE2_DONE, LE_SET_LMV_MASTER, LE_SET_LMV_SLAVE, LE_SKIP_NLINK, LE_SKIP_NLINK_DECLARE, LE_START, LE_STOP, lfsck_component_find(), lfsck_component_put(), lfsck_env_info(), lfsck_operations::lfsck_in_notify, lfsck_instance_find(), lfsck_instance_put(), lfsck_start(), lfsck_stop(), likely, LPF_BROADCAST, lfsck_request::lr_active, lfsck_request::lr_async_windows, lfsck_request::lr_event, lfsck_request::lr_index, lfsck_request::lr_param, lfsck_request::lr_speed, lfsck_request::lr_status, lfsck_request::lr_valid, lfsck_request::lr_version, lfsck_start::ls_active, lfsck_start::ls_async_windows, lfsck_stop::ls_flags, lfsck_start::ls_flags, lfsck_start::ls_speed_limit, lfsck_stop::ls_status, lfsck_start::ls_valid, lfsck_start::ls_version, lfsck_start_param::lsp_index, lfsck_start_param::lsp_index_valid, lfsck_start_param::lsp_start, lfsck_thread_info::lti_start, lfsck_thread_info::lti_stop, RETURN, start, stop, and unlikely.
Referenced by lfsck_init(), mdd_declare_links_add(), mdd_links_write(), ofd_inconsistency_verify_one(), and ofd_precreate_objects().
static int __init lfsck_init (void) [static]
Definition at line 3790 of file lfsck_lib.c.
References INIT_LIST_HEAD, lfsck_in_notify(), lfsck_instance_list, lfsck_mdt_orphan_list, lfsck_ost_orphan_list, lfsck_thread_key, lu_context_key_register(), tgt_register_lfsck_in_notify(), and tgt_register_lfsck_query().
static int lfsck_instance_add (struct lfsck_instance * lfsck) [inline, static]
Definition at line 1724 of file lfsck_lib.c.
References lfsck_instance_list, lfsck_instance::li_bottom, lfsck_instance::li_link, list_add_tail(), and list_for_each_entry.
Referenced by lfsck_register().
void lfsck_instance_cleanup (const struct lu_env * env, struct lfsck_instance * lfsck)
Definition at line 1613 of file lfsck_lib.c.
References ENTRY, LASSERT, LASSERTF, lfsck_component_cleanup(), lfsck_fid_fini(), lfsck_lmv_put(), lfsck_object_put(), lfsck_tgt_descs_fini(), lfsck_instance::li_bookmark_obj, lfsck_instance::li_lfsck_dir, lfsck_instance::li_link, lfsck_instance::li_list_dir, lfsck_instance::li_list_double_scan, lfsck_instance::li_list_idle, lfsck_instance::li_list_lmv, lfsck_instance::li_list_scan, lfsck_instance::li_lmv, lfsck_instance::li_los, lfsck_instance::li_lpf_obj, lfsck_instance::li_lpf_root_obj, lfsck_instance::li_mdt_descs, lfsck_instance::li_obj_dir, lfsck_instance::li_obj_oit, lfsck_instance::li_ost_descs, lfsck_instance::li_thread, list_empty(), list_for_each_entry_safe, lfsck_lmv::ll_ref, lfsck_lmv_unit::llu_lmv, local_oid_storage_fini(), OBD_FREE_PTR, thread, thread_is_init(), and thread_is_stopped().
Referenced by lfsck_instance_put(), and lfsck_register().
struct lfsck_instance* lfsck_instance_find (struct dt_device * key, bool ref, bool unlink) [read]
Definition at line 1712 of file lfsck_lib.c.
References __lfsck_instance_find().
Referenced by lfsck_degister(), lfsck_dump(), lfsck_get_speed(), lfsck_get_windows(), lfsck_in_notify(), lfsck_orphan_it_init(), lfsck_query(), lfsck_register(), lfsck_register_namespace(), lfsck_set_speed(), lfsck_set_windows(), lfsck_start(), and lfsck_stop().
static void lfsck_interpret (const struct lu_env * env, struct lfsck_instance * lfsck, struct ptlrpc_request * req, void * args, int result) [static]
Definition at line 2236 of file lfsck_lib.c.
References lfsck_async_interpret_args::laia_com, lfsck_async_interpret_args::laia_shared, LASSERT, lfsck_component::lc_link, lfsck_async_interpret_common(), lfsck_instance::li_list_double_scan, lfsck_instance::li_list_scan, lfsck_instance::li_lock, and list_for_each_entry.
Referenced by lfsck_async_interpret(), lfsck_start_all(), and lfsck_stop_all().
static void lfsck_key_fini (const struct lu_context * ctx, struct lu_context_key * key, void * data) [static]
Definition at line 52 of file lfsck_lib.c.
References lfsck_thread_info::lti_big_buf, lfsck_thread_info::lti_linkea_buf, lfsck_thread_info::lti_linkea_buf2, lu_buf_free(), and OBD_FREE_PTR.
int lfsck_lock (const struct lu_env * env, struct lfsck_instance * lfsck, struct dt_object * obj, const char * name, struct lfsck_lock_handle * llh, __u64 bits, enum ldlm_mode mode)
Request compound ibits locks for the given <obj, name> pairs.
Before the LFSCK modifying on the namespace visible object, it needs to acquire related ibits ldlm lock. Usually, we can use lfsck_ibits_lock for the lock purpose. But the simple lfsck_ibits_lock for directory-based modificationis (such as insert name entry to the directory) may be too coarse-grained and not efficient.
The lfsck_lock() will request compound ibits locks on the specified <obj, name> pairs: the PDO (Parallel Directory Operations) ibits (UPDATE) lock on the directory object, and the regular ibits lock on the name hash.
Parameters:
[in] env pointer to the thread context
[in] lfsck pointer to the lfsck instance
[in] obj pointer to the dt_object to be locked
[in] name used for building the PDO lock resource
[out] llh pointer to the lfsck_lock_handle
[in] bits the bits for the ldlm lock to be acquired
[in] mode the mode for the ldlm lock to be acquired
Return values:
0 for success
negative error number on failure
Definition at line 468 of file lfsck_lib.c.
References __lfsck_ibits_lock(), CDEBUG, D_LFSCK, DFID, fid_build_reg_res_name(), LASSERT, LBUG, LCK_CR, LCK_CW, LCK_EX, LCK_PR, LCK_PW, lfsck_dto2fid(), lfsck_env_info(), lfsck_ibits_unlock(), lfsck_lfsck2name(), lfsck_object_type(), lfsck_lock_handle::llh_pdo_lh, lfsck_lock_handle::llh_pdo_mode, lfsck_lock_handle::llh_reg_lh, lfsck_lock_handle::llh_reg_mode, lfsck_thread_info::lti_resid, lustre_handle_is_used(), LUSTRE_RES_ID_HSH_OFF, MDS_INODELOCK_UPDATE, ldlm_res_id::name, and PFID.
Referenced by lfsck_create_lpf(), lfsck_layout_recreate_parent(), lfsck_lpf_remove_name_entry(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_insert_normal(), lfsck_namespace_insert_orphan(), lfsck_namespace_repair_dangling(), lfsck_namespace_repair_dirent(), lfsck_namespace_replace_cond(), lfsck_namespace_shrink_linkea_cond(), and lfsck_update_name_entry().
static int lfsck_lpf_remove_name_entry (const struct lu_env * env, struct lfsck_instance * lfsck, const char * name) [static]
Remove the name entry from the .lustre/lost+found directory.
No need to care about the object referenced by the name entry, either the name entry is invalid or redundant, or the referenced object has been processed or will be handled by others.
Parameters:
[in] env pointer to the thread context
[in] lfsck pointer to the lfsck instance
[in] name the name for the name entry to be removed
Return values:
0 for success
negative error number on failure
Definition at line 561 of file lfsck_lib.c.
References CDEBUG, D_LFSCK, DFID, dt_declare_delete(), dt_declare_ref_del(), dt_delete(), dt_key, dt_ref_del(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), ENTRY, GOTO, LCK_PW, lfsck_dto2fid(), lfsck_env_info(), lfsck_lfsck2name(), lfsck_lock(), lfsck_obj2dev(), lfsck_unlock(), lfsck_instance::li_lpf_root_obj, lfsck_thread_info::lti_llh, MDS_INODELOCK_UPDATE, PFID, RETURN, and stop.
Referenced by lfsck_scan_lpf_bad_entries(), lfsck_verify_lpf(), and lfsck_verify_lpf_pairs().
void lfsck_pos_dump (struct seq_file * m, struct lfsck_position * pos, const char * prefix)
Definition at line 1779 of file lfsck_lib.c.
References DFID, fid_is_zero(), lfsck_position::lp_dir_cookie, lfsck_position::lp_dir_parent, lfsck_position::lp_oit_cookie, LPU64, LPX64, and PFID.
Referenced by lfsck_namespace_dump().
void lfsck_pos_fill (const struct lu_env * env, struct lfsck_instance * lfsck, struct lfsck_position * pos, bool init)
Definition at line 1796 of file lfsck_lib.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, fid_zero(), LASSERT, lfsck_dto2fid(), lfsck_instance::li_current_oit_processed, lfsck_instance::li_di_dir, lfsck_instance::li_di_oit, lfsck_instance::li_obj_dir, lfsck_instance::li_obj_oit, lfsck_position::lp_dir_cookie, lfsck_position::lp_dir_parent, lfsck_position::lp_oit_cookie, MDS_DIR_END_OFF, dt_index_operations::dt_it_ops::store, and unlikely.
Referenced by lfsck_checkpoint(), lfsck_master_engine(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_record_failure(), lfsck_post(), and lfsck_prep().
void lfsck_post_generic (const struct lu_env * env, struct lfsck_component * com, int * result)
Definition at line 2551 of file lfsck_lib.c.
References CDEBUG, D_LFSCK, l_wait_event, lfsck_assistant_data::lad_assistant_status, lfsck_assistant_data::lad_exit, lfsck_assistant_data::lad_name, lfsck_assistant_data::lad_post_result, lfsck_assistant_data::lad_req_list, lfsck_assistant_data::lad_thread, lfsck_assistant_data::lad_to_post, lfsck_component::lc_data, lfsck_component::lc_lfsck, lfsck_lfsck2name(), lfsck_instance::li_thread, list_empty(), ptlrpc_thread::t_ctl_waitq, and thread_is_stopped().
Referenced by lfsck_layout_master_post(), and lfsck_namespace_post().
int lfsck_query (const struct lu_env * env, struct dt_device * key, struct lfsck_request * req, struct lfsck_reply * rep, struct lfsck_query * que)
Definition at line 3364 of file lfsck_lib.c.
References cfs_time_seconds(), ENTRY, GOTO, l_wait_event, lfsck_component::lc_ops, lfsck_component_find(), lfsck_component_put(), lfsck_instance_find(), lfsck_instance_put(), lfsck_operations::lfsck_query, LFSCK_TYPE_BITS, LFSCK_TYPE_SCRUB, LFSCK_TYPES_ALL, LFSCK_TYPES_SUPPORTED, lfsck_instance::li_thread, likely, LPF_WAIT, lfsck_request::lr_active, LS_MAX, LS_SCANNING_PHASE1, LS_SCANNING_PHASE2, lfsck_query::lu_flags, lfsck_query::lu_mdts_count, lfsck_query::lu_osts_count, lfsck_query::lu_repaired, lfsck_query::lu_types, LWI_ON_SIGNAL_NOOP, LWI_TIMEOUT_INTR, RETURN, ptlrpc_thread::t_ctl_waitq, and unlikely.
Referenced by mdd_iocontrol().
int lfsck_query_all (const struct lu_env * env, struct lfsck_component * com)
Definition at line 2420 of file lfsck_lib.c.
References CDEBUG, cfs_foreach_bit, D_LFSCK, ENTRY, lfsck_assistant_data::lad_name, lfsck_async_interpret_args::laia_com, lfsck_async_interpret_args::laia_lr, lfsck_async_interpret_args::laia_ltd, lfsck_async_interpret_args::laia_ltds, LASSERT, lfsck_component::lc_data, lfsck_component::lc_lfsck, lfsck_component::lc_type, LE_QUERY, LEF_QUERY_ALL, LEF_TO_OST, lfsck_async_interpret_common(), lfsck_async_request(), lfsck_env_info(), lfsck_lfsck2name(), LFSCK_QUERY, lfsck_reset_ltd_status(), lfsck_tgt_get(), lfsck_tgt_put(), LFSCK_TYPE_LAYOUT, lfsck_instance::li_mdt_descs, lfsck_instance::li_ost_descs, lfsck_request::lr_active, lfsck_request::lr_event, lfsck_request::lr_flags, lfsck_tgt_desc::ltd_exp, lfsck_tgt_desc::ltd_index, lfsck_tgt_descs::ltd_rw_sem, lfsck_tgt_descs::ltd_tgts_bitmap, lfsck_thread_info::lti_laia, lfsck_thread_info::lti_lr, ptlrpc_prep_set(), ptlrpc_set_destroy(), ptlrpc_set_wait(), and RETURN.
Referenced by lfsck_layout_query_all(), and lfsck_namespace_query_all().
void lfsck_quit_generic (const struct lu_env * env, struct lfsck_component * com)
Definition at line 2613 of file lfsck_lib.c.
References l_wait_event, lfsck_assistant_data::lad_exit, lfsck_assistant_data::lad_thread, lfsck_component::lc_data, lfsck_component::lc_lfsck, lfsck_instance::li_thread, ptlrpc_thread::t_ctl_waitq, thread_is_init(), and thread_is_stopped().
Referenced by lfsck_layout_master_quit(), and lfsck_namespace_quit().
int lfsck_register (const struct lu_env * env, struct dt_device * key, struct dt_device * next, struct obd_device * obd, lfsck_out_notify notify, void * notify_data, bool master)
Definition at line 3474 of file lfsck_lib.c.
References dt_object_operations::do_index_try, dt_object::do_lu, dt_object::do_ops, dotlustre, dt_key, dt_locate(), dt_lookup(), dt_otable_features, dt_root_get(), dt_try_as_dir(), ENTRY, lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, FID_SEQ_LOCAL_FILE, FID_SEQ_LOCAL_NAME, GOTO, INIT_LIST_HEAD, lfsck_add_target_from_orphan(), lfsck_bookmark_setup(), lfsck_dev_idx(), LFSCK_DIR, lfsck_env_info(), lfsck_fid_init(), lfsck_instance_add(), lfsck_instance_cleanup(), lfsck_instance_find(), lfsck_layout_setup(), lfsck_name_get_const(), lfsck_namespace_setup(), lfsck_object_put(), lfsck_tgt_descs_init(), lfsck_verify_linkea(), lfsck_instance::li_bottom, lfsck_instance::li_double_scan_count, lfsck_instance::li_global_root_fid, lfsck_instance::li_lfsck_dir, lfsck_instance::li_link, lfsck_instance::li_list_dir, lfsck_instance::li_list_double_scan, lfsck_instance::li_list_idle, lfsck_instance::li_list_lmv, lfsck_instance::li_list_scan, lfsck_instance::li_local_root_fid, lfsck_instance::li_lock, lfsck_instance::li_los, lfsck_instance::li_master, lfsck_instance::li_mdt_descs, lfsck_instance::li_mutex, lfsck_instance::li_next, lfsck_instance::li_obd, lfsck_instance::li_obj_oit, lfsck_instance::li_ost_descs, lfsck_instance::li_out_notify, lfsck_instance::li_out_notify_data, lfsck_instance::li_ref, lfsck_instance::li_thread, local_file_find_or_create(), local_oid_storage_init(), lostfound, lfsck_thread_info::lti_fid, lfsck_thread_info::lti_fid2, lu_object_get(), OBD_ALLOC_PTR, OTABLE_IT_OID, RETURN, ptlrpc_thread::t_ctl_waitq, and unlikely.
Referenced by mdd_prepare(), and ofd_prepare().
int lfsck_register_namespace (const struct lu_env * env, struct dt_device * key, struct ldlm_namespace * ns)
Definition at line 3457 of file lfsck_lib.c.
References lfsck_instance_find(), lfsck_instance_put(), lfsck_instance::li_namespace, and likely.
Referenced by mdt_prepare(), and ofd_prepare().
static void lfsck_reset_ltd_status (struct lfsck_tgt_desc * ltd, enum lfsck_type type) [inline, static]
Definition at line 98 of file lfsck_lib.c.
References LFSCK_TYPE_LAYOUT, LS_MAX, lfsck_tgt_desc::ltd_layout_repaired, lfsck_tgt_desc::ltd_layout_status, lfsck_tgt_desc::ltd_namespace_repaired, and lfsck_tgt_desc::ltd_namespace_status.
Referenced by lfsck_async_interpret_common(), lfsck_query_all(), and lfsck_start().
static int lfsck_scan_lpf_bad_entries (const struct lu_env * env, struct lfsck_instance * lfsck) [static]
Scan .lustre/lost+found for bad name entries and remove them.
The valid name entry should be "MDTxxxx", the "xxxx" is the MDT device index in the system. Any other formatted name is invalid and should be removed.
Parameters:
[in] env pointer to the thread context
[in] lfsck pointer to the lfsck instance
Return values:
0 for success
negative error number on failure
Definition at line 1088 of file lfsck_lib.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, ENTRY, le16_to_cpu, lfsck_env_info(), lfsck_lpf_remove_name_entry(), lfsck_instance::li_lpf_root_obj, lfsck_thread_info::lti_key, LUDA_64BITHASH, name_is_dot_or_dotdot(), and RETURN.
Referenced by lfsck_verify_lpf().
int lfsck_set_speed (struct dt_device * key, __u32 val)
Definition at line 2656 of file lfsck_lib.c.
References __lfsck_set_speed(), ENTRY, LCT_DT_THREAD, LCT_MD_THREAD, lfsck_bookmark_store(), lfsck_instance_find(), lfsck_instance_put(), lfsck_instance::li_mutex, likely, lu_env_fini(), lu_env_init(), and RETURN.
Referenced by mdd_lfsck_speed_limit_seq_write().
int lfsck_set_windows (struct dt_device * key, int val)
Definition at line 2709 of file lfsck_lib.c.
References CWARN, ENTRY, lfsck_bookmark::lb_async_windows, LCT_DT_THREAD, LCT_MD_THREAD, LFSCK_ASYNC_WIN_MAX, lfsck_bookmark_store(), lfsck_instance_find(), lfsck_instance_put(), lfsck_lfsck2name(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_mutex, likely, lu_env_fini(), lu_env_init(), and RETURN.
Referenced by mdd_lfsck_async_windows_seq_write().
int lfsck_start (const struct lu_env * env, struct dt_device * key, struct lfsck_start_param * lsp)
Definition at line 2937 of file lfsck_lib.c.
References __lfsck_component_find(), __lfsck_set_speed(), CERROR, cfs_foreach_bit, DOIF_DRYRUN, DOIF_FAILOUT, DOIF_OUTUSED, DOIF_RESET, DOIV_DRYRUN, DOIV_ERROR_HANDLE, DT_OTABLE_IT_FLAGS_SHIFT, ENTRY, GOTO, l_wait_event, LASSERT, lfsck_bookmark::lb_param, lfsck_bookmark::lb_speed_limit, lfsck_bookmark::lb_version, lfsck_component::lc_link, lfsck_component::lc_ops, lfsck_component::lc_type, lfsck_bookmark_store(), lfsck_instance_find(), lfsck_instance_put(), lfsck_operations::lfsck_join, lfsck_lfsck2name(), lfsck_ltd2tgt(), lfsck_master_engine(), lfsck_operations::lfsck_post, lfsck_operations::lfsck_reset, lfsck_reset_ltd_status(), lfsck_set_param(), lfsck_start_all(), lfsck_thread_args_fini(), lfsck_thread_args_init(), LFSCK_TYPE_LAYOUT, LFSCK_TYPE_NAMESPACE, LFSCK_TYPES_ALL, LFSCK_TYPES_SUPPORTED, lfsck_instance::li_args_dir, lfsck_instance::li_args_oit, lfsck_instance::li_bookmark_ram, lfsck_instance::li_drop_dryrun, lfsck_instance::li_flags, lfsck_instance::li_list_double_scan, lfsck_instance::li_list_idle, lfsck_instance::li_list_scan, lfsck_instance::li_lock, lfsck_instance::li_master, lfsck_instance::li_mdt_descs, lfsck_instance::li_mutex, lfsck_instance::li_namespace, lfsck_instance::li_new_scanned, lfsck_instance::li_oit_over, lfsck_instance::li_ost_descs, lfsck_instance::li_start_unplug, lfsck_instance::li_status, lfsck_instance::li_thread, list_del_init(), list_empty(), list_for_each_entry, list_for_each_entry_safe, list_move_tail(), LPF_BROADCAST, LPF_DRYRUN, LPF_FAILOUT, LPF_RESET, lfsck_start::ls_active, LS_FAILED, lfsck_start::ls_flags, lfsck_start::ls_speed_limit, lfsck_start::ls_valid, lfsck_start::ls_version, lfsck_start_param::lsp_start, LSV_DRYRUN, LSV_ERROR_HANDLE, LSV_SPEED_LIMIT, lfsck_tgt_desc::ltd_layout_done, lfsck_tgt_desc::ltd_layout_list, lfsck_tgt_desc::ltd_layout_phase_list, lfsck_tgt_desc::ltd_namespace_done, lfsck_tgt_desc::ltd_namespace_list, lfsck_tgt_desc::ltd_namespace_phase_list, lfsck_tgt_descs::ltd_rw_sem, lfsck_tgt_desc::ltd_synced_failures, lfsck_tgt_descs::ltd_tgts_bitmap, LUDA_64BITHASH, LUDA_TYPE, LUDA_VERIFY, LUDA_VERIFY_DRYRUN, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_NO_AUTO, RETURN, start, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, thread, thread_is_init(), thread_is_running(), thread_is_stopped(), thread_set_flags(), and unlikely.
Referenced by lfsck_in_notify(), mdd_iocontrol(), ofd_iocontrol(), and ofd_postrecov().
static int lfsck_start_all (const struct lu_env * env, struct lfsck_instance * lfsck, struct lfsck_start * start) [static]
Definition at line 2848 of file lfsck_lib.c.
References CERROR, cfs_foreach_bit, ENTRY, lfsck_async_interpret_args::laia_lr, lfsck_async_interpret_args::laia_ltd, lfsck_async_interpret_args::laia_ltds, lfsck_async_interpret_args::laia_result, lfsck_async_interpret_args::laia_shared, LASSERT, lfsck_bookmark::lb_async_windows, lfsck_bookmark::lb_speed_limit, lfsck_bookmark::lb_version, LE_START, lfsck_async_interpret(), lfsck_async_request(), lfsck_dev_idx(), lfsck_env_info(), lfsck_interpret(), lfsck_lfsck2name(), LFSCK_NOTIFY, lfsck_stop_all(), lfsck_tgt_get(), lfsck_tgt_put(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_mdt_descs, LPF_ALL_TGT, LPF_BROADCAST, lfsck_request::lr_active, lfsck_request::lr_async_windows, lfsck_request::lr_event, lfsck_request::lr_index, lfsck_request::lr_param, lfsck_request::lr_speed, lfsck_request::lr_valid, lfsck_request::lr_version, lfsck_start::ls_active, LS_FAILED, lfsck_stop::ls_flags, lfsck_start::ls_flags, lfsck_stop::ls_status, LSV_ASYNC_WINDOWS, LSV_CREATE_MDTOBJ, LSV_CREATE_OSTOBJ, LSV_DRYRUN, LSV_ERROR_HANDLE, LSV_SPEED_LIMIT, lfsck_tgt_desc::ltd_exp, lfsck_tgt_desc::ltd_layout_done, lfsck_tgt_desc::ltd_namespace_done, lfsck_tgt_descs::ltd_rw_sem, lfsck_tgt_desc::ltd_synced_failures, lfsck_tgt_descs::ltd_tgts_bitmap, lfsck_thread_info::lti_laia, lfsck_thread_info::lti_lr, lfsck_thread_info::lti_stop, ptlrpc_prep_set(), ptlrpc_set_destroy(), ptlrpc_set_wait(), RETURN, stop, and unlikely.
Referenced by lfsck_start().
int lfsck_start_assistant (const struct lu_env * env, struct lfsck_component * com, struct lfsck_start_param * lsp)
Definition at line 2484 of file lfsck_lib.c.
References CERROR, ENTRY, l_wait_event, lfsck_assistant_data::lad_advance_lock, lfsck_assistant_data::lad_assistant_status, lfsck_assistant_data::lad_exit, lfsck_assistant_data::lad_in_double_scan, lfsck_assistant_data::lad_name, lfsck_assistant_data::lad_post_result, lfsck_assistant_data::lad_thread, lfsck_assistant_data::lad_to_double_scan, lfsck_assistant_data::lad_to_post, lfsck_component::lc_data, lfsck_component::lc_lfsck, lfsck_assistant_engine(), lfsck_lfsck2name(), lfsck_thread_args_fini(), lfsck_thread_args_init(), lfsck_instance::li_thread, RETURN, ptlrpc_thread::t_ctl_waitq, thread_is_running(), thread_is_stopped(), thread_set_flags(), and unlikely.
Referenced by lfsck_layout_master_prep(), and lfsck_namespace_prep().
int lfsck_stop (const struct lu_env * env, struct dt_device * key, struct lfsck_stop * stop)
Definition at line 3213 of file lfsck_lib.c.
References CERROR, ENTRY, GOTO, l_wait_event, lfsck_assistant_data::lad_lock, lfsck_assistant_data::lad_task, lfsck_component::lc_data, lfsck_instance_find(), lfsck_instance_put(), lfsck_lfsck2name(), lfsck_stop_all(), lfsck_instance::li_flags, lfsck_instance::li_list_double_scan, lfsck_instance::li_list_scan, lfsck_instance::li_lock, lfsck_instance::li_master, lfsck_instance::li_mutex, lfsck_instance::li_status, lfsck_instance::li_thread, list_for_each_entry, LPF_BROADCAST, lfsck_stop::ls_flags, lfsck_stop::ls_status, LS_STOPPED, RETURN, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, thread, thread_is_init(), thread_is_stopped(), thread_set_flags(), and unlikely.
Referenced by lfsck_in_notify(), lfsck_layout_master_in_notify(), lfsck_layout_slave_in_notify(), lfsck_namespace_in_notify(), mdd_iocontrol(), ofd_fini(), and ofd_iocontrol().
static int lfsck_stop_all (const struct lu_env * env, struct lfsck_instance * lfsck, struct lfsck_stop * stop) [static]
Definition at line 2778 of file lfsck_lib.c.
References CERROR, cfs_foreach_bit, ENTRY, lfsck_async_interpret_args::laia_lr, lfsck_async_interpret_args::laia_ltd, lfsck_async_interpret_args::laia_ltds, lfsck_async_interpret_args::laia_result, lfsck_async_interpret_args::laia_shared, LASSERT, lfsck_bookmark::lb_version, LE_STOP, lfsck_async_interpret(), lfsck_async_request(), lfsck_dev_idx(), lfsck_env_info(), lfsck_interpret(), lfsck_lfsck2name(), LFSCK_NOTIFY, lfsck_tgt_get(), lfsck_tgt_put(), LFSCK_TYPES_ALL, lfsck_instance::li_bookmark_ram, lfsck_instance::li_mdt_descs, LPF_BROADCAST, lfsck_request::lr_active, lfsck_request::lr_event, lfsck_request::lr_index, lfsck_request::lr_param, lfsck_request::lr_status, lfsck_request::lr_version, lfsck_stop::ls_flags, lfsck_stop::ls_status, lfsck_tgt_desc::ltd_exp, lfsck_tgt_descs::ltd_rw_sem, lfsck_tgt_descs::ltd_tgts_bitmap, lfsck_thread_info::lti_laia, lfsck_thread_info::lti_lr, ptlrpc_prep_set(), ptlrpc_set_destroy(), ptlrpc_set_wait(), RETURN, and unlikely.
Referenced by lfsck_start_all(), and lfsck_stop().
static int lfsck_stop_notify (const struct lu_env * env, struct lfsck_instance * lfsck, struct lfsck_tgt_descs * ltds, struct lfsck_tgt_desc * ltd, __u16 type) [static]
Definition at line 2259 of file lfsck_lib.c.
References __lfsck_component_find(), CDEBUG, D_LFSCK, ENTRY, lfsck_assistant_data::lad_name, lfsck_async_interpret_args::laia_com, lfsck_async_interpret_args::laia_lr, lfsck_async_interpret_args::laia_ltd, lfsck_async_interpret_args::laia_ltds, LASSERT, lfsck_component::lc_data, LE_PEER_EXIT, LEF_TO_OST, lfsck_async_interpret_common(), lfsck_async_request(), lfsck_component_get(), lfsck_component_put(), lfsck_dev_idx(), lfsck_env_info(), lfsck_lfsck2name(), LFSCK_NOTIFY, lfsck_tgt_put(), LFSCK_TYPE_LAYOUT, lfsck_instance::li_list_double_scan, lfsck_instance::li_list_scan, lfsck_instance::li_lock, lfsck_instance::li_master, lfsck_instance::li_ost_descs, list, list_del_init(), list_empty(), lfsck_request::lr_active, lfsck_request::lr_event, lfsck_request::lr_flags, lfsck_request::lr_index, lfsck_request::lr_status, LS_CO_PAUSED, lfsck_tgt_desc::ltd_exp, lfsck_tgt_desc::ltd_index, lfsck_tgt_desc::ltd_layout_list, lfsck_tgt_desc::ltd_layout_phase_list, lfsck_tgt_descs::ltd_lock, lfsck_tgt_desc::ltd_namespace_list, lfsck_tgt_desc::ltd_namespace_phase_list, lfsck_tgt_desc::ltd_ref, lfsck_thread_info::lti_laia, lfsck_thread_info::lti_lr, ptlrpc_prep_set(), ptlrpc_set_destroy(), ptlrpc_set_wait(), and RETURN.
Referenced by lfsck_del_target().
static void lfsck_tgt_descs_fini (struct lfsck_tgt_descs * ltds) [static]
Definition at line 121 of file lfsck_lib.c.
References cfs_bitmap_clear(), cfs_foreach_bit, CFS_FREE_BITMAP, LASSERT, LASSERTF, lfsck_assign_tgt(), lfsck_ltd2tgt(), lfsck_tgt_put(), likely, list_del_init(), list_empty(), list_for_each_entry_safe, lfsck_tgt_desc::ltd_layout_list, lfsck_tgt_desc::ltd_layout_phase_list, lfsck_tgt_desc::ltd_namespace_list, lfsck_tgt_desc::ltd_namespace_phase_list, lfsck_tgt_descs::ltd_orphan, lfsck_tgt_desc::ltd_orphan_list, lfsck_tgt_descs::ltd_rw_sem, lfsck_tgt_descs::ltd_tgtnr, lfsck_tgt_descs::ltd_tgts_bitmap, lfsck_tgt_descs::ltd_tgts_idx, OBD_FREE_PTR, TGT_PTRS, and unlikely.
Referenced by lfsck_instance_cleanup().
static int lfsck_tgt_descs_init (struct lfsck_tgt_descs * ltds) [static]
Definition at line 109 of file lfsck_lib.c.
References CFS_ALLOCATE_BITMAP(), INIT_LIST_HEAD, lfsck_tgt_descs::ltd_lock, lfsck_tgt_descs::ltd_orphan, lfsck_tgt_descs::ltd_rw_sem, and lfsck_tgt_descs::ltd_tgts_bitmap.
Referenced by lfsck_register().
void lfsck_thread_args_fini (struct lfsck_thread_args * lta)
Definition at line 1919 of file lfsck_lib.c.
References lfsck_component_put(), lfsck_instance_put(), lfsck_thread_args::lta_com, lfsck_thread_args::lta_env, lfsck_thread_args::lta_lfsck, lu_env_fini(), and OBD_FREE_PTR.
Referenced by lfsck_assistant_engine(), lfsck_master_engine(), lfsck_start(), and lfsck_start_assistant().
static struct lfsck_thread_args* lfsck_thread_args_init (struct lfsck_instance * lfsck, struct lfsck_component * com, struct lfsck_start_param * lsp) [static, read]
Definition at line 1893 of file lfsck_lib.c.
References LCT_DT_THREAD, LCT_MD_THREAD, lfsck_component_get(), lfsck_instance_get(), lfsck_thread_args::lta_com, lfsck_thread_args::lta_env, lfsck_thread_args::lta_lfsck, lfsck_thread_args::lta_lsp, lu_env_init(), OBD_ALLOC_PTR, and OBD_FREE_PTR.
Referenced by lfsck_start(), and lfsck_start_assistant().
void lfsck_time_dump (struct seq_file * m, __u64 time, const char * name)
Definition at line 1767 of file lfsck_lib.c.
References cfs_time_current_sec(), and LPU64.
Referenced by lfsck_layout_dump(), and lfsck_namespace_dump().
void lfsck_unlock (struct lfsck_lock_handle * llh)
Release the the compound ibits locks.
Parameters:
[in] llh pointer to the lfsck_lock_handle to be released
Definition at line 520 of file lfsck_lib.c.
References lfsck_ibits_unlock(), lfsck_lock_handle::llh_pdo_lh, lfsck_lock_handle::llh_pdo_mode, lfsck_lock_handle::llh_reg_lh, and lfsck_lock_handle::llh_reg_mode.
Referenced by lfsck_create_lpf(), lfsck_layout_recreate_parent(), lfsck_lpf_remove_name_entry(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_insert_normal(), lfsck_namespace_insert_orphan(), lfsck_namespace_repair_dangling(), lfsck_namespace_repair_dirent(), lfsck_namespace_replace_cond(), lfsck_namespace_shrink_linkea_cond(), and lfsck_update_name_entry().
static int lfsck_update_lpf_entry (const struct lu_env * env, struct lfsck_instance * lfsck, struct dt_object * parent, struct dt_object * child, const char * name, enum lfsck_verify_lpf_types type) [static]
Definition at line 1149 of file lfsck_lib.c.
References CDEBUG, D_LFSCK, DFID, lfsck_bookmark::lb_lpf_fid, lfsck_bookmark_store(), lfsck_dto2fid(), lfsck_lfsck2name(), lfsck_update_name_entry(), lfsck_instance::li_bookmark_ram, LVLT_BY_BOOKMARK, and PFID.
Referenced by lfsck_verify_lpf_pairs().
int lfsck_verify_lpf (const struct lu_env * env, struct lfsck_instance * lfsck)
Verify the /ROOT/.lustre/lost+found/ directory.
/ROOT/.lustre/lost+found/ is a special directory to hold the objects that the LFSCK does not exactly know how to handle, such as orphans. So before the LFSCK scanning the system, the consistency of such directory needs to be verified firstly to allow the users to use it during the LFSCK.
Parameters:
[in] env pointer to the thread context
[in] lfsck pointer to the lfsck instance
Return values:
positive number for uncertain inconsistency
0 for success
negative error number on failure
Definition at line 1371 of file lfsck_lib.c.
References CDEBUG, D_LFSCK, DFID, dt_object::do_lu, dt_key, dt_lookup(), dt_object_exists(), dt_object_remote(), dt_try_as_dir(), ENTRY, fid_is_norm(), fid_is_zero(), fid_zero(), GOTO, LASSERT, lfsck_bookmark::lb_lpf_fid, lfsck_bookmark_store(), lfsck_create_lpf(), lfsck_dev_idx(), lfsck_dto2fid(), lfsck_env_info(), lfsck_lfsck2name(), lfsck_lpf_remove_name_entry(), lfsck_name_get_const(), lfsck_object_find_bottom(), lfsck_object_find_by_dev(), lfsck_object_put(), lfsck_object_type(), lfsck_scan_lpf_bad_entries(), lfsck_tgt_get(), lfsck_tgt_put(), lfsck_verify_linkea(), lfsck_verify_lpf_pairs(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_bottom, lfsck_instance::li_lpf_obj, lfsck_instance::li_lpf_root_obj, lfsck_instance::li_master, lfsck_instance::li_mdt_descs, likely, lfsck_tgt_desc::ltd_tgt, lfsck_thread_info::lti_fid, lfsck_thread_info::lti_fid2, lu_fid_eq(), LU_LPF_FID, lu_object_get(), LVLT_BY_BOOKMARK, LVLT_BY_NAMEENTRY, name, PFID, RETURN, and unlikely.
Referenced by lfsck_master_engine().
static int lfsck_verify_lpf_pairs (const struct lu_env * env, struct lfsck_instance * lfsck, struct dt_object * child, const char * name, struct lu_fid * fid, enum lfsck_verify_lpf_types type) [static]
Check whether the back references the .
Two cases: 1) The child's FID is stored in the bookmark file. If the child back references the parent (LU_LPF_FID object) via its ".." entry, then insert the name (MDTxxxx) to the .lustre/lost+found; otherwise, if the child back references another parent2, then: 1.1) If the parent2 recognizes the child, then update the bookmark file; 1.2) Otherwise, the LFSCK cannot know whether there will be parent3 that references the child. So keep them there. As the LFSCK processing, the parent3 may be found, then when the LFSCK run next time, the inconsistency can be repaired.
2) The child's FID is stored in the .lustre/lost+found/ sub-directory name entry (MDTxxxx). If the child back references the parent (LU_LPF_FID obj) via its ".." entry, then update the bookmark file, otherwise, if the child back references another parent2, then: 2.1) If the parent2 recognizes the child, then remove the sub-directory from .lustre/lost+found/; 2.2) Otherwise, if the parent2 does not recognizes the child, trust the sub-directory name entry and update the child; 2.3) Otherwise, if we do not know whether the parent2 recognizes the child or not, then keep them there.
Parameters:
[in] env pointer to the thread context
[in] lfsck pointer to the lfsck instance
[in] child pointer to the lost+found sub-directory object
[in] name the name for lost+found sub-directory object
[out] fid pointer to the buffer to hold the FID of the object (called it as parent2) that is referenced via the child's dotdot entry; it also can be the FID that is referenced by the name entry under the parent2.
[in] type to indicate where the child's FID is stored in
Return values:
positive number for uncertain inconsistency
0 for success
negative error number on failure
Definition at line 1213 of file lfsck_lib.c.
References CDEBUG, D_LFSCK, DFID, dt_object::do_lu, dotdot, dt_key, dt_lookup(), dt_object_exists(), dt_read_lock(), dt_read_unlock(), dt_try_as_dir(), ENTRY, fid_is_sane(), fid_zero(), GOTO, lfsck_bookmark::lb_lpf_fid, LCK_PR, lfsck_bookmark_store(), lfsck_dto2fid(), lfsck_env_info(), lfsck_ibits_lock(), lfsck_ibits_unlock(), lfsck_lfsck2name(), lfsck_links_get_first(), lfsck_lpf_remove_name_entry(), lfsck_name_get_const(), lfsck_object_find_bottom(), lfsck_object_put(), lfsck_update_lpf_entry(), lfsck_update_name_entry(), lfsck_verify_linkea(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_lpf_obj, lfsck_instance::li_lpf_root_obj, lfsck_thread_info::lti_fid3, lfsck_thread_info::lti_key, lu_fid_eq(), LU_LPF_FID, lu_object_get(), LVLT_BY_BOOKMARK, MDS_INODELOCK_UPDATE, and PFID.
Referenced by lfsck_verify_lpf().
LU_CONTEXT_KEY_DEFINE (lfsck , LCT_MD_THREAD| LCT_DT_THREAD)
LU_KEY_INIT (lfsck , struct lfsck_thread_info)
LU_KEY_INIT_GENERIC (lfsck)
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre File System Checker")
module_exit (lfsck_exit)
module_init (lfsck_init)
MODULE_LICENSE ("GPL")
MODULE_VERSION (LUSTRE_VERSION_STRING)
Variable Documentation
const char dot[] = "."
Definition at line 542 of file lfsck_lib.c.
Referenced by lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_repair_dangling(), lod_dir_declare_create_stripes(), lod_xattr_set_lmv(), mdd_declare_object_initialize(), and mdd_object_initialize().
const char dotdot[] = ".."
Definition at line 543 of file lfsck_lib.c.
Referenced by lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_double_scan_dir(), lfsck_namespace_handle_striped_master(), lfsck_namespace_insert_orphan(), lfsck_namespace_repair_bad_name_hash(), lfsck_namespace_repair_dangling(), lfsck_namespace_repair_unmatched_pairs(), lfsck_namespace_verify_stripe_slave(), lfsck_verify_lpf_pairs(), ll_dir_get_parent_fid(), lod_dir_declare_create_stripes(), lod_xattr_set_lmv(), mdd_declare_object_initialize(), mdd_declare_rename(), mdd_migrate_entries(), mdd_object_initialize(), mdd_rename(), orph_declare_index_insert(), and orph_index_insert().
const char dotlustre[] = ".lustre" [static]
Definition at line 544 of file lfsck_lib.c.
Referenced by lfsck_register().
const char* lfsck_flags_names[]
Initial value:
 {
        "scanned-once",
        "inconsistent",
        "upgrade",
        "incomplete",
        "crashed_lastid",
        NULL
}
Definition at line 71 of file lfsck_lib.c.
Referenced by lfsck_layout_dump(), and lfsck_namespace_dump().
struct list_head lfsck_instance_list [static]
Definition at line 66 of file lfsck_lib.c.
Referenced by __lfsck_instance_find(), lfsck_exit(), lfsck_init(), and lfsck_instance_add().
struct list_head lfsck_mdt_orphan_list [static]
Definition at line 68 of file lfsck_lib.c.
Referenced by lfsck_add_target(), lfsck_add_target_from_orphan(), lfsck_del_target(), lfsck_exit(), and lfsck_init().
struct list_head lfsck_ost_orphan_list [static]
Definition at line 67 of file lfsck_lib.c.
Referenced by lfsck_add_target(), lfsck_add_target_from_orphan(), lfsck_del_target(), lfsck_exit(), and lfsck_init().
const char* lfsck_param_names[]
Initial value:
 {
        NULL,
        "failout",
        "dryrun",
        "all_targets",
        "broadcast",
        "orphan",
        "create_ostobj",
        "create_mdtobj",
        NULL
}
Definition at line 80 of file lfsck_lib.c.
Referenced by lfsck_layout_dump(), and lfsck_namespace_dump().
const char lostfound[] = "lost+found" [static]
Definition at line 545 of file lfsck_lib.c.
Referenced by lfsck_register().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.