Lustre: lustre/utils/gss/lgss_keyring.c File Reference
lustre/utils/gss/lgss_keyring.c File Reference
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <fcntl.h>
#include <inttypes.h>
#include <string.h>
#include <errno.h>
#include <pwd.h>
#include <keyutils.h>
#include <gssapi/gssapi.h>
#include <libcfs/util/param.h>
#include "lsupport.h"
#include "lgss_utils.h"
#include "write_bytes.h"
#include "context.h"
Data Structures
struct lgss_nego_data
struct lgss_init_res
struct keyring_upcall_param
Functions
int do_nego_rpc (struct lgss_nego_data *lnd, gss_buffer_desc *gss_token, struct lgss_init_res *gr)
static int lgssc_negotiation (struct lgss_nego_data *lnd)
static int lgssc_init_nego_data (struct lgss_nego_data *lnd, struct keyring_upcall_param *kup, lgss_mech_t mech)
void lgssc_fini_nego_data (struct lgss_nego_data *lnd)
static int error_kernel_key (key_serial_t keyid, int rpc_error, int gss_error)
static int update_kernel_key (key_serial_t keyid, struct lgss_nego_data *lnd, gss_buffer_desc *ctx_token)
static int lgssc_kr_negotiate (key_serial_t keyid, struct lgss_cred *cred, struct keyring_upcall_param *kup)
static int parse_callout_info (const char *coinfo, struct keyring_upcall_param *uparam)
static void set_log_level ()
int main (int argc, char *argv[])
Variables
static char * g_service = NULL
Function Documentation
int do_nego_rpc (struct lgss_nego_data * lnd, gss_buffer_desc * gss_token, struct lgss_init_res * gr)
Definition at line 121 of file lgss_keyring.c.
References cfs_free_param_data(), cfs_get_param_paths(), lgssd_ioctl_param::gid, lgss_init_res::gr_ctx, lgss_init_res::gr_major, lgss_init_res::gr_minor, lgss_init_res::gr_token, lgss_init_res::gr_win, GSSD_INTERFACE_VERSION, LL_DEBUG, LL_ERR, LL_TRACE, lgss_nego_data::lnd_lsvc, lgss_nego_data::lnd_secid, lgss_nego_data::lnd_uid, lgss_nego_data::lnd_uuid, logmsg, lgssd_ioctl_param::lustre_svc, path, lgssd_ioctl_param::reply_buf, lgssd_ioctl_param::reply_buf_size, ret, lgssd_ioctl_param::secid, lgssd_ioctl_param::send_token, lgssd_ioctl_param::send_token_size, lgssd_ioctl_param::status, lgssd_ioctl_param::uid, lgssd_ioctl_param::uuid, and lgssd_ioctl_param::version.
Referenced by lgssc_negotiation().
static int error_kernel_key (key_serial_t keyid, int rpc_error, int gss_error) [static]
Definition at line 391 of file lgss_keyring.c.
References buf, end, LL_ERR, LL_INFO, LL_TRACE, LL_WARN, logmsg, and WRITE_BYTES.
Referenced by lgssc_kr_negotiate().
void lgssc_fini_nego_data (struct lgss_nego_data * lnd)
Definition at line 371 of file lgss_keyring.c.
References GSS_S_COMPLETE, LL_ERR, lgss_nego_data::lnd_cred, lgss_nego_data::lnd_mech, lgss_nego_data::lnd_svc_name, and logmsg_gss.
Referenced by lgssc_kr_negotiate().
static int lgssc_init_nego_data (struct lgss_nego_data * lnd, struct keyring_upcall_param * kup, lgss_mech_t mech) [static]
Definition at line 323 of file lgss_keyring.c.
References g_service, GSS_C_MUTUAL_FLAG, GSS_C_NO_CONTEXT, GSS_S_COMPLETE, krb5oid, keyring_upcall_param::kup_secid, keyring_upcall_param::kup_svc, keyring_upcall_param::kup_tgt, keyring_upcall_param::kup_uid, LGSS_MECH_KRB5, LL_ERR, lgss_nego_data::lnd_cred, lgss_nego_data::lnd_ctx, lgss_nego_data::lnd_established, lgss_nego_data::lnd_gss_err, lgss_nego_data::lnd_lsvc, lgss_nego_data::lnd_mech, lgss_nego_data::lnd_req_flags, lgss_nego_data::lnd_rmt_ctx, lgss_nego_data::lnd_rpc_err, lgss_nego_data::lnd_secid, lgss_nego_data::lnd_seq_win, lgss_nego_data::lnd_svc_name, lgss_nego_data::lnd_uid, lgss_nego_data::lnd_uuid, logmsg, and logmsg_gss.
Referenced by lgssc_kr_negotiate().
static int lgssc_kr_negotiate (key_serial_t keyid, struct lgss_cred * cred, struct keyring_upcall_param * kup) [static]
Definition at line 480 of file lgss_keyring.c.
References error_kernel_key(), g_service, keyring_upcall_param::kup_fsgid, keyring_upcall_param::kup_fsuid, keyring_upcall_param::kup_gid, keyring_upcall_param::kup_nid, keyring_upcall_param::kup_svc, keyring_upcall_param::kup_uid, lgss_cred::lc_mech, lgss_cred::lc_tgt_nid, lgss_cred::lc_tgt_svc, lgss_cred::lc_uid, lgss_get_service_str(), lgss_release_cred(), lgss_using_cred(), lgssc_fini_nego_data(), lgssc_init_nego_data(), lgssc_negotiation(), LL_ERR, LL_INFO, LL_TRACE, lgss_mech_type::lmt_mech_n, lgss_nego_data::lnd_ctx, lgss_nego_data::lnd_gss_err, lgss_nego_data::lnd_mech, lgss_nego_data::lnd_rpc_err, logmsg, serialize_context_for_kernel(), and update_kernel_key().
Referenced by main().
static int lgssc_negotiation (struct lgss_nego_data * lnd) [static]
Definition at line 218 of file lgss_keyring.c.
References do_nego_rpc(), lgss_init_res::gr_ctx, lgss_init_res::gr_major, lgss_init_res::gr_token, lgss_init_res::gr_win, GSS_C_NO_BUFFER, GSS_S_COMPLETE, GSS_S_CONTINUE_NEEDED, LL_DEBUG, LL_ERR, LL_TRACE, lgss_nego_data::lnd_cred, lgss_nego_data::lnd_ctx, lgss_nego_data::lnd_established, lgss_nego_data::lnd_gss_err, lgss_nego_data::lnd_mech, lgss_nego_data::lnd_req_flags, lgss_nego_data::lnd_rmt_ctx, lgss_nego_data::lnd_rpc_err, lgss_nego_data::lnd_seq_win, lgss_nego_data::lnd_svc_name, logmsg, and logmsg_gss.
Referenced by lgssc_kr_negotiate().
int main (int argc, char * argv[])
Definition at line 648 of file lgss_keyring.c.
References keyring_upcall_param::kup_fsgid, keyring_upcall_param::kup_fsuid, keyring_upcall_param::kup_is_mdt, keyring_upcall_param::kup_is_ost, keyring_upcall_param::kup_is_root, keyring_upcall_param::kup_mech, keyring_upcall_param::kup_nid, keyring_upcall_param::kup_selfnid, keyring_upcall_param::kup_svc, keyring_upcall_param::kup_uid, lgss_cred::lc_root_flags, lgss_cred::lc_self_nid, lgss_cred::lc_tgt_nid, lgss_cred::lc_tgt_svc, lgss_cred::lc_uid, lgss_create_cred(), lgss_mech_initialize(), lgss_name2mech(), lgss_prepare_cred(), LGSS_ROOT_CRED_MDT, LGSS_ROOT_CRED_OST, LGSS_ROOT_CRED_ROOT, lgssc_kr_negotiate(), LL_ERR, LL_INFO, LL_TRACE, lgss_mech_type::lmt_name, logmsg, parse_callout_info(), and set_log_level().
static int parse_callout_info (const char * coinfo, struct keyring_upcall_param * uparam) [static]
Definition at line 557 of file lgss_keyring.c.
References buf, keyring_upcall_param::kup_gid, keyring_upcall_param::kup_is_mdt, keyring_upcall_param::kup_is_ost, keyring_upcall_param::kup_is_root, keyring_upcall_param::kup_mech, keyring_upcall_param::kup_nid, keyring_upcall_param::kup_secid, keyring_upcall_param::kup_selfnid, keyring_upcall_param::kup_svc, keyring_upcall_param::kup_tgt, keyring_upcall_param::kup_uid, LL_DEBUG, LL_ERR, LL_TRACE, logmsg, and strlcpy().
Referenced by main().
static void set_log_level () [static]
Definition at line 617 of file lgss_keyring.c.
References cfs_free_param_data(), cfs_get_param_paths(), lgss_set_loglevel(), LL_MAX, and path.
Referenced by main().
static int update_kernel_key (key_serial_t keyid, struct lgss_nego_data * lnd, gss_buffer_desc * ctx_token) [static]
Definition at line 425 of file lgss_keyring.c.
References buf, end, LL_DEBUG, LL_ERR, LL_TRACE, lgss_nego_data::lnd_rmt_ctx, lgss_nego_data::lnd_seq_win, logmsg, write_buffer(), and WRITE_BYTES.
Referenced by lgssc_kr_negotiate().
Variable Documentation
char* g_service = NULL [static]
Definition at line 64 of file lgss_keyring.c.
Referenced by lgssc_init_nego_data(), and lgssc_kr_negotiate().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.