Lustre: lustre/utils/gss/lgss_krb5_utils.c File Reference
lustre/utils/gss/lgss_krb5_utils.c File Reference
#include "config.h"
#include <sys/param.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/utsname.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <unistd.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <fcntl.h>
#include <errno.h>
#include <time.h>
#include <gssapi/gssapi.h>
#include <krb5.h>
#include "lsupport.h"
#include "lgss_utils.h"
#include "lgss_krb5_utils.h"
Data Structures
struct lgss_krb5_cred
Defines
#define krb5_err_msg(code) error_message(code)
Functions
static void lgss_krb5_mutex_lock (void)
static void lgss_krb5_mutex_unlock (void)
static int lgss_krb5_set_ccache_name (const char *ccname)
static int lgss_krb5_get_local_realm (void)
static int princ_is_local_realm (krb5_context ctx, krb5_principal princ)
static int svc_princ_verify_host (krb5_context ctx, krb5_principal princ, uint64_t self_nid, loglevel_t loglevel)
static int lkrb5_cc_check_tgt_princ (krb5_context ctx, krb5_ccache ccache, krb5_principal princ, unsigned int flag, uint64_t self_nid)
static void get_root_tgt_ccname (char *ccname, int size, unsigned int flag)
compose the TGT cc name, according to the root flags.
static int lkrb5_check_root_tgt_cc_base (krb5_context ctx, krb5_ccache ccache, char *ccname, unsigned int flag, uint64_t self_nid)
static int lkrb5_check_root_tgt_cc (krb5_context ctx, krb5_ccache ccache, unsigned int root_flags, uint64_t self_nid)
find out whether current TGT cache is valid or not
static int lkrb5_get_root_tgt_keytab (krb5_context ctx, krb5_ccache ccache, krb5_keytab kt, krb5_principal princ, const char *ccname)
static int lkrb5_refresh_root_tgt_cc (krb5_context ctx, krb5_ccache ccache, unsigned int root_flags, uint64_t self_nid)
static int lkrb5_prepare_root_cred (struct lgss_cred *cred)
static int lkrb5_prepare_user_cred (struct lgss_cred *cred)
static int lgss_krb5_prepare_cred (struct lgss_cred *cred)
static void lgss_krb5_release_cred (struct lgss_cred *cred)
Variables
const char * krb5_cc_type_mem = "MEMORY:"
const char * krb5_cc_type_file = "FILE:"
const char * krb5_cred_root_suffix = "lustre_root"
const char * krb5_cred_mds_suffix = "lustre_mds"
const char * krb5_cred_oss_suffix = "lustre_oss"
char * krb5_this_realm = NULL
char * krb5_keytab_file = "/etc/krb5.keytab"
char * krb5_cc_type = "FILE:"
char * krb5_cc_dir = "/tmp"
char * krb5_cred_prefix = "krb5cc_"
struct lgss_mech_type lgss_mech_krb5
Define Documentation
#define krb5_err_msg (code) error_message(code)
Definition at line 156 of file lgss_krb5_utils.c.
Referenced by lgss_krb5_get_local_realm(), lkrb5_check_root_tgt_cc_base(), lkrb5_get_root_tgt_keytab(), lkrb5_prepare_root_cred(), and lkrb5_refresh_root_tgt_cc().
Function Documentation
static void get_root_tgt_ccname (char * ccname, int size, unsigned int flag) [static]
compose the TGT cc name, according to the root flags.
Definition at line 374 of file lgss_krb5_utils.c.
References krb5_cc_dir, krb5_cc_type, krb5_cred_mds_suffix, krb5_cred_oss_suffix, krb5_cred_prefix, krb5_cred_root_suffix, krb5_this_realm, lassert, LGSS_ROOT_CRED_MDT, LGSS_ROOT_CRED_OST, and LGSS_ROOT_CRED_ROOT.
Referenced by lkrb5_check_root_tgt_cc(), and lkrb5_refresh_root_tgt_cc().
static int lgss_krb5_get_local_realm (void) [static]
Definition at line 203 of file lgss_krb5_utils.c.
References krb5_err_msg, krb5_this_realm, LL_DEBUG, LL_ERR, and logmsg.
Referenced by lgss_krb5_prepare_cred().
static void lgss_krb5_mutex_lock (void) [static]
Definition at line 135 of file lgss_krb5_utils.c.
References LGSS_MUTEX_KRB5, lgss_mutex_lock(), LL_ERR, and logmsg.
Referenced by lkrb5_prepare_root_cred().
static void lgss_krb5_mutex_unlock (void) [static]
Definition at line 143 of file lgss_krb5_utils.c.
References LGSS_MUTEX_KRB5, lgss_mutex_unlock(), LL_WARN, and logmsg.
Referenced by lkrb5_prepare_root_cred().
static int lgss_krb5_prepare_cred (struct lgss_cred * cred) [static]
Definition at line 845 of file lgss_krb5_utils.c.
References lgss_krb5_cred::kc_ccname, lgss_krb5_cred::kc_remove, lgss_cred::lc_mech_cred, lgss_cred::lc_root_flags, lgss_krb5_get_local_realm(), lkrb5_prepare_root_cred(), lkrb5_prepare_user_cred(), LL_ERR, and logmsg.
static void lgss_krb5_release_cred (struct lgss_cred * cred) [static]
Definition at line 873 of file lgss_krb5_utils.c.
References lgss_cred::lc_mech_cred.
static int lgss_krb5_set_ccache_name (const char * ccname) [static]
Definition at line 176 of file lgss_krb5_utils.c.
References GSS_S_COMPLETE, LL_DEBUG, LL_ERR, and logmsg.
Referenced by lkrb5_prepare_root_cred(), and lkrb5_prepare_user_cred().
static int lkrb5_cc_check_tgt_princ (krb5_context ctx, krb5_ccache ccache, krb5_principal princ, unsigned int flag, uint64_t self_nid) [static]
Definition at line 291 of file lgss_krb5_utils.c.
References krb5_this_realm, lassert, LGSS_ROOT_CRED_MDT, LGSS_ROOT_CRED_OST, LGSS_ROOT_CRED_ROOT, LGSS_SVC_MDS_STR, LGSS_SVC_OSS_STR, LGSS_USR_ROOT_STR, LL_DEBUG, LL_TRACE, LL_WARN, logmsg, princ_is_local_realm(), and svc_princ_verify_host().
Referenced by lkrb5_check_root_tgt_cc_base().
static int lkrb5_check_root_tgt_cc (krb5_context ctx, krb5_ccache ccache, unsigned int root_flags, uint64_t self_nid) [static]
find out whether current TGT cache is valid or not
Definition at line 522 of file lgss_krb5_utils.c.
References get_root_tgt_ccname(), krb5_cc_type, LGSS_ROOT_CRED_NR, lkrb5_check_root_tgt_cc_base(), LL_DEBUG, LL_TRACE, and logmsg.
Referenced by lkrb5_prepare_root_cred().
static int lkrb5_check_root_tgt_cc_base (krb5_context ctx, krb5_ccache ccache, char * ccname, unsigned int flag, uint64_t self_nid) [static]
Definition at line 398 of file lgss_krb5_utils.c.
References krb5_err_msg, krb5_this_realm, lkrb5_cc_check_tgt_princ(), LL_DEBUG, LL_ERR, logmsg, and now().
Referenced by lkrb5_check_root_tgt_cc().
static int lkrb5_get_root_tgt_keytab (krb5_context ctx, krb5_ccache ccache, krb5_keytab kt, krb5_principal princ, const char * ccname) [static]
Definition at line 562 of file lgss_krb5_utils.c.
References krb5_err_msg, LL_DEBUG, LL_ERR, LL_INFO, and logmsg.
Referenced by lkrb5_refresh_root_tgt_cc().
static int lkrb5_prepare_root_cred (struct lgss_cred * cred) [static]
Definition at line 759 of file lgss_krb5_utils.c.
References lgss_krb5_cred::kc_ccname, krb5_cc_type_mem, krb5_err_msg, krb5_this_realm, lassert, lgss_cred::lc_mech_cred, lgss_cred::lc_root_flags, lgss_cred::lc_self_nid, lgss_krb5_mutex_lock(), lgss_krb5_mutex_unlock(), lgss_krb5_set_ccache_name(), lkrb5_check_root_tgt_cc(), lkrb5_refresh_root_tgt_cc(), LL_DEBUG, LL_ERR, LL_TRACE, and logmsg.
Referenced by lgss_krb5_prepare_cred().
static int lkrb5_prepare_user_cred (struct lgss_cred * cred) [static]
Definition at line 818 of file lgss_krb5_utils.c.
References lgss_krb5_cred::kc_ccname, krb5_cc_dir, krb5_cc_type, krb5_cred_prefix, krb5_this_realm, lassert, lgss_cred::lc_mech_cred, lgss_cred::lc_uid, lgss_krb5_set_ccache_name(), LL_DEBUG, LL_ERR, and logmsg.
Referenced by lgss_krb5_prepare_cred().
static int lkrb5_refresh_root_tgt_cc (krb5_context ctx, krb5_ccache ccache, unsigned int root_flags, uint64_t self_nid) [static]
Definition at line 653 of file lgss_krb5_utils.c.
References get_root_tgt_ccname(), krb5_err_msg, krb5_keytab_file, lassert, LGSS_ROOT_CRED_MDT, LGSS_ROOT_CRED_OST, LGSS_ROOT_CRED_ROOT, LGSS_SVC_MDS_STR, LGSS_SVC_OSS_STR, LGSS_USR_ROOT_STR, lkrb5_get_root_tgt_keytab(), LL_ERR, LL_TRACE, logmsg, princ_is_local_realm(), and svc_princ_verify_host().
Referenced by lkrb5_prepare_root_cred().
static int princ_is_local_realm (krb5_context ctx, krb5_principal princ) [static]
Definition at line 232 of file lgss_krb5_utils.c.
References krb5_this_realm.
Referenced by lkrb5_cc_check_tgt_princ(), and lkrb5_refresh_root_tgt_cc().
static int svc_princ_verify_host (krb5_context ctx, krb5_principal princ, uint64_t self_nid, loglevel_t loglevel) [static]
Definition at line 239 of file lgss_krb5_utils.c.
References lnet_nid2hostname(), and logmsg.
Referenced by lkrb5_cc_check_tgt_princ(), and lkrb5_refresh_root_tgt_cc().
Variable Documentation
char* krb5_cc_dir = "/tmp"
Definition at line 167 of file lgss_krb5_utils.c.
Referenced by get_root_tgt_ccname(), and lkrb5_prepare_user_cred().
char* krb5_cc_type = "FILE:"
Definition at line 166 of file lgss_krb5_utils.c.
Referenced by get_root_tgt_ccname(), lkrb5_check_root_tgt_cc(), and lkrb5_prepare_user_cred().
const char* krb5_cc_type_file = "FILE:"
Definition at line 159 of file lgss_krb5_utils.c.
const char* krb5_cc_type_mem = "MEMORY:"
Definition at line 158 of file lgss_krb5_utils.c.
Referenced by lkrb5_prepare_root_cred().
const char* krb5_cred_mds_suffix = "lustre_mds"
Definition at line 161 of file lgss_krb5_utils.c.
Referenced by get_root_tgt_ccname().
const char* krb5_cred_oss_suffix = "lustre_oss"
Definition at line 162 of file lgss_krb5_utils.c.
Referenced by get_root_tgt_ccname().
char* krb5_cred_prefix = "krb5cc_"
Definition at line 168 of file lgss_krb5_utils.c.
Referenced by get_root_tgt_ccname(), and lkrb5_prepare_user_cred().
const char* krb5_cred_root_suffix = "lustre_root"
Definition at line 160 of file lgss_krb5_utils.c.
Referenced by get_root_tgt_ccname().
char* krb5_keytab_file = "/etc/krb5.keytab"
Definition at line 165 of file lgss_krb5_utils.c.
Referenced by lkrb5_refresh_root_tgt_cc().
char* krb5_this_realm = NULL
Definition at line 164 of file lgss_krb5_utils.c.
Referenced by get_root_tgt_ccname(), lgss_krb5_get_local_realm(), lkrb5_cc_check_tgt_princ(), lkrb5_check_root_tgt_cc_base(), lkrb5_prepare_root_cred(), lkrb5_prepare_user_cred(), and princ_is_local_realm().
struct lgss_mech_type lgss_mech_krb5
Initial value:
{
        .lmt_name               = "krb5",
        .lmt_mech_n             = LGSS_MECH_KRB5,
        .lmt_prepare_cred       = lgss_krb5_prepare_cred,
        .lmt_release_cred       = lgss_krb5_release_cred,
}
Definition at line 883 of file lgss_krb5_utils.c.
Referenced by lgss_name2mech().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.