Lustre: lustre/utils/gss/lgss_utils.c File Reference
lustre/utils/gss/lgss_utils.c File Reference
#include "config.h"
#include <sys/types.h>
#include <sys/time.h>
#include <sys/stat.h>
#include <sys/ipc.h>
#include <sys/sem.h>
#include <errno.h>
#include <stdio.h>
#include <ctype.h>
#include <signal.h>
#include <string.h>
#include <fcntl.h>
#include <stdarg.h>
#include <syslog.h>
#include <gssapi/gssapi.h>
#include <stdlib.h>
#include "lsupport.h"
#include "lgss_utils.h"
#include "lgss_krb5_utils.h"
Data Structures
struct lgss_mutex_s
Functions
static int lgss_mutex_get (struct lgss_mutex_s *mutex)
int lgss_mutex_lock (lgss_mutex_id_t mid)
int lgss_mutex_unlock (lgss_mutex_id_t mid)
void lgss_set_loglevel (loglevel_t level)
void __logmsg (loglevel_t level, const char *func, const char *format,...)
void __logmsg_gss (loglevel_t level, const char *func, const gss_OID mech, uint32_t major, uint32_t minor, const char *format,...)
struct lgss_mech_type * lgss_name2mech (const char *mech_name)
int lgss_mech_initialize (struct lgss_mech_type *mech)
void lgss_mech_finalize (struct lgss_mech_type *mech)
struct lgss_cred * lgss_create_cred (struct lgss_mech_type *mech)
void lgss_destroy_cred (struct lgss_cred *cred)
int lgss_prepare_cred (struct lgss_cred *cred)
void lgss_release_cred (struct lgss_cred *cred)
int lgss_using_cred (struct lgss_cred *cred)
int lgss_get_service_str (char **string, uint32_t lsvc, uint64_t tgt_nid)
Variables
const char * lgss_svc_str [LGSS_SVC_MAX]
static struct lgss_mutex_s lgss_mutexes [LGSS_MUTEX_MAX]
gss_OID_desc krb5oid
gss_OID_desc spkm3oid
loglevel_t g_log_level = LL_WARN
static const char * log_prefix []
Function Documentation
void __logmsg (loglevel_t level, const char * func, const char * format, ...)
Definition at line 253 of file lgss_utils.c.
References buf, LOG_INFO, and log_prefix.
void __logmsg_gss (loglevel_t level, const char * func, const gss_OID mech, uint32_t major, uint32_t minor, const char * format, ...)
Definition at line 269 of file lgss_utils.c.
References buf, GSS_C_GSS_CODE, GSS_C_MECH_CODE, GSS_S_COMPLETE, LOG_INFO, and log_prefix.
struct lgss_cred* lgss_create_cred (struct lgss_mech_type * mech) [read]
Definition at line 349 of file lgss_utils.c.
References lgss_cred::lc_mech, LL_TRACE, lgss_mech_type::lmt_name, and logmsg.
Referenced by main().
void lgss_destroy_cred (struct lgss_cred * cred)
Definition at line 363 of file lgss_utils.c.
References lassert, lgss_cred::lc_mech, lgss_cred::lc_mech_cred, LL_TRACE, lgss_mech_type::lmt_name, and logmsg.
int lgss_get_service_str (char ** string, uint32_t lsvc, uint64_t tgt_nid)
Definition at line 419 of file lgss_utils.c.
References lassert, LGSS_SVC_MAX, lgss_svc_str, LL_DEBUG, LL_ERR, lnet_nid2hostname(), and logmsg.
Referenced by lgssc_kr_negotiate().
void lgss_mech_finalize (struct lgss_mech_type * mech)
Definition at line 342 of file lgss_utils.c.
References LL_TRACE, lgss_mech_type::lmt_fini, lgss_mech_type::lmt_name, and logmsg.
int lgss_mech_initialize (struct lgss_mech_type * mech)
Definition at line 334 of file lgss_utils.c.
References LL_TRACE, lgss_mech_type::lmt_init, lgss_mech_type::lmt_name, and logmsg.
Referenced by main().
static int lgss_mutex_get (struct lgss_mutex_s * mutex) [static]
Definition at line 122 of file lgss_utils.c.
References LL_DEBUG, LL_ERR, LL_TRACE, LL_WARN, logmsg, lgss_mutex_s::sem_id, lgss_mutex_s::sem_key, and lgss_mutex_s::sem_name.
Referenced by lgss_mutex_lock().
int lgss_mutex_lock (lgss_mutex_id_t mid)
Definition at line 164 of file lgss_utils.c.
References lassert, lgss_mutex_get(), LGSS_MUTEX_MAX, lgss_mutexes, LL_DEBUG, LL_ERR, LL_TRACE, logmsg, sem, lgss_mutex_s::sem_id, lgss_mutex_s::sem_key, and lgss_mutex_s::sem_name.
Referenced by lgss_krb5_mutex_lock().
int lgss_mutex_unlock (lgss_mutex_id_t mid)
Definition at line 196 of file lgss_utils.c.
References lassert, LGSS_MUTEX_MAX, lgss_mutexes, LL_DEBUG, LL_ERR, LL_TRACE, logmsg, sem, lgss_mutex_s::sem_id, lgss_mutex_s::sem_key, and lgss_mutex_s::sem_name.
Referenced by lgss_krb5_mutex_unlock().
struct lgss_mech_type* lgss_name2mech (const char * mech_name) [read]
Definition at line 327 of file lgss_utils.c.
References lgss_mech_krb5.
Referenced by main().
int lgss_prepare_cred (struct lgss_cred * cred)
Definition at line 373 of file lgss_utils.c.
References lassert, lgss_cred::lc_mech, LL_TRACE, lgss_mech_type::lmt_name, lgss_mech_type::lmt_prepare_cred, and logmsg.
Referenced by main().
void lgss_release_cred (struct lgss_cred * cred)
Definition at line 386 of file lgss_utils.c.
References lassert, lgss_cred::lc_mech, lgss_cred::lc_mech_cred, LL_TRACE, lgss_mech_type::lmt_name, lgss_mech_type::lmt_release_cred, and logmsg.
Referenced by lgssc_kr_negotiate().
void lgss_set_loglevel (loglevel_t level)
Definition at line 247 of file lgss_utils.c.
References g_log_level, lassert, and LL_MAX.
Referenced by set_log_level().
int lgss_using_cred (struct lgss_cred * cred)
Definition at line 402 of file lgss_utils.c.
References lassert, lgss_cred::lc_mech, LL_TRACE, lgss_mech_type::lmt_name, lgss_mech_type::lmt_using_cred, and logmsg.
Referenced by lgssc_kr_negotiate().
Variable Documentation
loglevel_t g_log_level = LL_WARN
Definition at line 237 of file lgss_utils.c.
Referenced by lgss_set_loglevel().
gss_OID_desc krb5oid
Initial value:
        {9, "\052\206\110\206\367\022\001\002\002"}
Definition at line 227 of file lgss_utils.c.
struct lgss_mutex_s lgss_mutexes[LGSS_MUTEX_MAX] [static]
Referenced by lgss_mutex_lock(), and lgss_mutex_unlock().
const char* lgss_svc_str[LGSS_SVC_MAX]
Initial value:
 {
        [LGSS_SVC_MGS] = LGSS_SVC_MGS_STR,
        [LGSS_SVC_MDS] = LGSS_SVC_MDS_STR,
        [LGSS_SVC_OSS] = LGSS_SVC_OSS_STR,
}
Definition at line 104 of file lgss_utils.c.
Referenced by lgss_get_service_str().
const char* log_prefix[] [static]
Initial value:
 {
        [LL_ERR]        = "ERROR",
        [LL_WARN]       = "WARNING",
        [LL_INFO]       = "INFO",
        [LL_DEBUG]      = "DEBUG",
        [LL_TRACE]      = "TRACE",
}
Definition at line 239 of file lgss_utils.c.
Referenced by __logmsg(), and __logmsg_gss().
gss_OID_desc spkm3oid
Initial value:
        {7, "\053\006\001\005\005\001\003"}
Definition at line 230 of file lgss_utils.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.