Lustre: lustre/utils/lhsmtool_posix.c File Reference
lustre/utils/lhsmtool_posix.c File Reference
#include <ctype.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <dirent.h>
#include <errno.h>
#include <getopt.h>
#include <pthread.h>
#include <time.h>
#include <unistd.h>
#include <utime.h>
#include <signal.h>
#include <sys/time.h>
#include <sys/xattr.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <lustre/lustre_idl.h>
#include <lustre/lustreapi.h>
Data Structures
struct options
struct ct_th_data
Defines
#define REPORT_INTERVAL_DEFAULT 30
#define DIR_PERM S_IRWXU
#define FILE_PERM (S_IRUSR | S_IWUSR)
#define ONE_MB 0x100000
#define NSEC_PER_SEC 1000000000UL
#define CT_ERROR(_rc, _format,...)
#define CT_DEBUG(_format,...)
#define CT_WARN(_format,...)
#define CT_TRACE(_format,...)
Enumerations
enum ct_action { CA_IMPORT = 1, CA_REBIND, CA_MAXSEQ }
Functions
static double ct_now (void)
static void usage (const char *name, int rc)
static int ct_parseopts (int argc, char *const *argv)
static int ct_mkdir_p (const char *path)
static int ct_save_stripe (int src_fd, const char *src, const char *dst)
static int ct_load_stripe (const char *src, void *lovea, size_t *lovea_size)
static int ct_restore_stripe (const char *src, const char *dst, int dst_fd, const void *lovea, size_t lovea_size)
static int ct_copy_data (struct hsm_copyaction_private *hcp, const char *src, const char *dst, int src_fd, int dst_fd, const struct hsm_action_item *hai, long hal_flags)
static int ct_copy_attr (const char *src, const char *dst, int src_fd, int dst_fd)
static int ct_copy_xattr (const char *src, const char *dst, int src_fd, int dst_fd, bool is_restore)
static int ct_path_lustre (char *buf, int sz, const char *mnt, const lustre_fid *fid)
static int ct_path_archive (char *buf, int sz, const char *archive_dir, const lustre_fid *fid)
static bool ct_is_retryable (int err)
static int ct_begin_restore (struct hsm_copyaction_private **phcp, const struct hsm_action_item *hai, int mdt_index, int open_flags)
static int ct_begin (struct hsm_copyaction_private **phcp, const struct hsm_action_item *hai)
static int ct_fini (struct hsm_copyaction_private **phcp, const struct hsm_action_item *hai, int hp_flags, int ct_rc)
static int ct_archive (const struct hsm_action_item *hai, const long hal_flags)
static int ct_restore (const struct hsm_action_item *hai, const long hal_flags)
static int ct_remove (const struct hsm_action_item *hai, const long hal_flags)
static int ct_process_item (struct hsm_action_item *hai, const long hal_flags)
static void * ct_thread (void *data)
static int ct_process_item_async (const struct hsm_action_item *hai, long hal_flags)
static int ct_import_one (const char *src, const char *dst)
static char * path_concat (const char *dirname, const char *basename)
static int ct_import_fid (const lustre_fid *import_fid)
static int ct_import_recurse (const char *relpath)
static int ct_rebind_one (const lustre_fid *old_fid, const lustre_fid *new_fid)
static bool fid_is_file (lustre_fid *fid)
static bool should_ignore_line (const char *line)
static int ct_rebind_list (const char *list)
static int ct_rebind (void)
static int ct_dir_level_max (const char *dirpath, __u16 *sub_seqmax)
static int ct_max_sequence (void)
static void handler (int signal)
static int ct_run (void)
static int ct_setup (void)
static int ct_cleanup (void)
int main (int argc, char **argv)
Variables
struct options opt
static int arc_fd = -1
static int err_major
static int err_minor
static char cmd_name [PATH_MAX]
static char fs_name [MAX_OBD_NAME+1]
static struct
hsm_copytool_private * ctdata
Define Documentation
#define CT_DEBUG (_format, ...)
Value:
llapi_error(LLAPI_MSG_DEBUG | LLAPI_MSG_NO_ERRNO, 0,            \
                    "%f %s[%ld]: "_format,                              \
                    ct_now(), cmd_name, syscall(SYS_gettid), ## __VA_ARGS__)
Definition at line 143 of file lhsmtool_posix.c.
#define CT_ERROR (_rc, _format, ...)
Value:
llapi_error(LLAPI_MSG_ERROR, _rc,                               \
                    "%f %s[%ld]: "_format,                              \
                    ct_now(), cmd_name, syscall(SYS_gettid), ## __VA_ARGS__)
Definition at line 138 of file lhsmtool_posix.c.
Referenced by ct_archive(), ct_begin_restore(), ct_cleanup(), ct_copy_attr(), ct_copy_data(), ct_copy_xattr(), ct_dir_level_max(), ct_fini(), ct_import_fid(), ct_import_one(), ct_import_recurse(), ct_load_stripe(), ct_mkdir_p(), ct_parseopts(), ct_process_item(), ct_process_item_async(), ct_rebind(), ct_rebind_list(), ct_rebind_one(), ct_remove(), ct_restore(), ct_restore_stripe(), ct_run(), ct_save_stripe(), ct_setup(), and llapi_hsm_log_ct_progress().
#define CT_TRACE (_format, ...)
Value:
llapi_error(LLAPI_MSG_INFO | LLAPI_MSG_NO_ERRNO, 0,             \
                    "%f %s[%ld]: "_format,                              \
                    ct_now(), cmd_name, syscall(SYS_gettid), ## __VA_ARGS__)
Definition at line 153 of file lhsmtool_posix.c.
Referenced by ct_archive(), ct_copy_data(), ct_copy_xattr(), ct_dir_level_max(), ct_fini(), ct_import_fid(), ct_import_one(), ct_load_stripe(), ct_parseopts(), ct_process_item(), ct_rebind_list(), ct_rebind_one(), ct_remove(), ct_restore(), ct_run(), ct_save_stripe(), and main().
#define CT_WARN (_format, ...)
Value:
llapi_error(LLAPI_MSG_WARN | LLAPI_MSG_NO_ERRNO, 0,             \
                    "%f %s[%ld]: "_format,                              \
                    ct_now(), cmd_name, syscall(SYS_gettid), ## __VA_ARGS__)
Definition at line 148 of file lhsmtool_posix.c.
Referenced by ct_restore(), ct_run(), and main().
#define DIR_PERM S_IRWXU
Definition at line 66 of file lhsmtool_posix.c.
Referenced by ct_mkdir_p().
#define FILE_PERM (S_IRUSR | S_IWUSR)
Definition at line 68 of file lhsmtool_posix.c.
Referenced by ct_archive(), and ct_save_stripe().
#define NSEC_PER_SEC 1000000000UL
Definition at line 73 of file lhsmtool_posix.c.
Referenced by __cfs_fs_time_flat(), cfs_duration_nsec(), ct_copy_data(), and kgnilnd_ts_sub().
#define ONE_MB 0x100000
Definition at line 70 of file lhsmtool_posix.c.
#define REPORT_INTERVAL_DEFAULT 30
Definition at line 64 of file lhsmtool_posix.c.
Enumeration Type Documentation
enum ct_action
Enumerator:
CA_IMPORT
CA_REBIND
CA_MAXSEQ
Definition at line 76 of file lhsmtool_posix.c.
Function Documentation
static int ct_archive (const struct hsm_action_item * hai, const long hal_flags) [static]
Definition at line 874 of file lhsmtool_posix.c.
References buf, ct_begin(), ct_copy_attr(), ct_copy_data(), ct_copy_xattr(), CT_ERROR, ct_fini(), ct_is_retryable(), ct_mkdir_p(), ct_path_archive(), ct_path_lustre(), ct_save_stripe(), CT_TRACE, DFID, err_major, err_minor, FILE_PERM, hsm_action_item::hai_dfid, hsm_action_item::hai_extent, hsm_action_item::hai_fid, HP_FLAG_RETRY, hsm_extent::length, llapi_fid2path(), llapi_hsm_action_get_fd(), options::o_copy_attrs, options::o_copy_xattrs, options::o_dry_run, options::o_hsm_root, options::o_mnt, options::o_shadow_tree, PFID, and strlcat().
Referenced by ct_process_item().
static int ct_begin (struct hsm_copyaction_private ** phcp, const struct hsm_action_item * hai) [static]
Definition at line 828 of file lhsmtool_posix.c.
References ct_begin_restore().
Referenced by ct_archive(), and ct_remove().
static int ct_begin_restore (struct hsm_copyaction_private ** phcp, const struct hsm_action_item * hai, int mdt_index, int open_flags) [static]
Definition at line 811 of file lhsmtool_posix.c.
References CT_ERROR, ct_path_lustre(), hsm_action_item::hai_fid, llapi_hsm_action_begin(), and options::o_mnt.
Referenced by ct_begin(), and ct_restore().
static int ct_cleanup (void) [static]
Definition at line 1928 of file lhsmtool_posix.c.
References arc_fd, CT_ERROR, and options::o_mnt_fd.
Referenced by main().
static int ct_copy_attr (const char * src, const char * dst, int src_fd, int dst_fd) [static]
Definition at line 716 of file lhsmtool_posix.c.
References CT_ERROR.
Referenced by ct_archive().
static int ct_copy_data (struct hsm_copyaction_private * hcp, const char * src, const char * dst, int src_fd, int dst_fd, const struct hsm_action_item * hai, long hal_flags) [static]
Definition at line 517 of file lhsmtool_posix.c.
References __u64, buf, CT_ERROR, ct_now(), CT_TRACE, err_major, hsm_action_item::hai_action, hsm_action_item::hai_extent, HSMA_RESTORE, hsm_extent::length, llapi_hsm_action_progress(), now(), NSEC_PER_SEC, options::o_bandwidth, options::o_chunk_size, options::o_report_int, and hsm_extent::offset.
Referenced by ct_archive(), and ct_restore().
static int ct_copy_xattr (const char * src, const char * dst, int src_fd, int dst_fd, bool is_restore) [static]
Definition at line 744 of file lhsmtool_posix.c.
References CT_ERROR, CT_TRACE, list, name, and XATTR_TRUSTED_PREFIX.
Referenced by ct_archive().
static int ct_dir_level_max (const char * dirpath, __u16 * sub_seqmax) [static]
Definition at line 1703 of file lhsmtool_posix.c.
References CT_ERROR, CT_TRACE, dir, and options::o_hsm_root.
Referenced by ct_max_sequence().
static int ct_fini (struct hsm_copyaction_private ** phcp, const struct hsm_action_item * hai, int hp_flags, int ct_rc) [static]
Definition at line 836 of file lhsmtool_posix.c.
References CT_ERROR, ct_path_lustre(), CT_TRACE, DFID, hsm_action_item::hai_cookie, hsm_action_item::hai_extent, hsm_action_item::hai_fid, llapi_hsm_action_begin(), llapi_hsm_action_end(), options::o_mnt, and PFID.
Referenced by ct_archive(), ct_process_item(), ct_remove(), and ct_restore().
static int ct_import_fid (const lustre_fid * import_fid) [static]
Definition at line 1446 of file lhsmtool_posix.c.
References CT_ERROR, ct_import_one(), ct_path_archive(), ct_path_lustre(), CT_TRACE, DFID, options::o_dst, options::o_hsm_root, options::o_mnt, and PFID.
Referenced by ct_import_recurse().
static int ct_import_one (const char * src, const char * dst) [static]
Definition at line 1385 of file lhsmtool_posix.c.
References CT_ERROR, ct_mkdir_p(), ct_path_archive(), CT_TRACE, err_major, llapi_hsm_import(), options::o_archive_cnt, options::o_archive_id, options::o_dry_run, and options::o_hsm_root.
Referenced by ct_import_fid(), and ct_import_recurse().
static int ct_import_recurse (const char * relpath) [static]
Definition at line 1467 of file lhsmtool_posix.c.
References CT_ERROR, ct_import_fid(), ct_import_one(), ct_mkdir_p(), dir, err_major, options::o_abort_on_error, options::o_dst, options::o_hsm_root, path_concat(), RFID, and SFID.
Referenced by main().
static bool ct_is_retryable (int err) [static]
Definition at line 806 of file lhsmtool_posix.c.
Referenced by ct_archive(), and ct_restore().
static int ct_load_stripe (const char * src, void * lovea, size_t * lovea_size) [static]
Definition at line 473 of file lhsmtool_posix.c.
References CT_ERROR, and CT_TRACE.
Referenced by ct_restore().
static int ct_max_sequence (void) [static]
Definition at line 1744 of file lhsmtool_posix.c.
References __u64, ct_dir_level_max(), options::o_hsm_root, path, and strlcpy().
Referenced by main().
static int ct_mkdir_p (const char * path) [static]
Definition at line 382 of file lhsmtool_posix.c.
References CT_ERROR, and DIR_PERM.
Referenced by ct_archive(), ct_import_one(), ct_import_recurse(), and ct_rebind_one().
static double ct_now (void) [inline, static]
Definition at line 129 of file lhsmtool_posix.c.
Referenced by ct_copy_data().
static int ct_parseopts (int argc, char *const * argv) [static]
Definition at line 210 of file lhsmtool_posix.c.
References CA_IMPORT, CA_MAXSEQ, CA_REBIND, CT_ERROR, CT_TRACE, LL_HSM_MAX_ARCHIVE, llapi_parse_size(), options::o_abort_on_error, options::o_action, options::o_archive_cnt, options::o_archive_id, options::o_bandwidth, options::o_chunk_size, options::o_copy_attrs, options::o_copy_xattrs, options::o_daemonize, options::o_dry_run, options::o_dst, options::o_event_fifo, options::o_hsm_root, options::o_mnt, options::o_mnt_fd, options::o_report_int, options::o_shadow_tree, options::o_src, options::o_verbose, ONE_MB, optarg, optind, and usage.
Referenced by main().
static int ct_path_archive (char * buf, int sz, const char * archive_dir, const lustre_fid * fid) [static]
Definition at line 792 of file lhsmtool_posix.c.
References DFID_NOBRACE, and PFID.
Referenced by ct_archive(), ct_import_fid(), ct_import_one(), ct_rebind_one(), ct_remove(), and ct_restore().
static int ct_path_lustre (char * buf, int sz, const char * mnt, const lustre_fid * fid) [static]
Definition at line 785 of file lhsmtool_posix.c.
References DFID_NOBRACE, dot_lustre_name, and PFID.
Referenced by ct_archive(), ct_begin_restore(), ct_fini(), and ct_import_fid().
static int ct_process_item (struct hsm_action_item * hai, const long hal_flags) [static]
Definition at line 1273 of file lhsmtool_posix.c.
References ct_archive(), CT_ERROR, ct_fini(), ct_remove(), ct_restore(), CT_TRACE, DFID, err_minor, hsm_action_item::hai_action, hsm_action_item::hai_cookie, hsm_action_item::hai_fid, hsm_action_item::hai_len, hsm_copytool_action2name(), HSMA_ARCHIVE, HSMA_CANCEL, HSMA_REMOVE, HSMA_RESTORE, llapi_fid2path(), LLAPI_MSG_INFO, options::o_dry_run, options::o_mnt, options::o_verbose, path, and PFID.
Referenced by ct_thread().
static int ct_process_item_async (const struct hsm_action_item * hai, long hal_flags) [static]
Definition at line 1344 of file lhsmtool_posix.c.
References CT_ERROR, ct_thread(), ct_th_data::hai, hsm_action_item::hai_len, ct_th_data::hal_flags, options::o_mnt, and thread.
Referenced by ct_run().
static int ct_rebind (void) [static]
Definition at line 1670 of file lhsmtool_posix.c.
References CT_ERROR, ct_rebind_list(), ct_rebind_one(), fid_is_file(), options::o_dst, options::o_src, RFID, and SFID.
Referenced by main().
static int ct_rebind_list (const char * list) [static]
Definition at line 1615 of file lhsmtool_posix.c.
References CT_ERROR, ct_rebind_one(), CT_TRACE, err_major, fid_is_file(), RFID, SFID, and should_ignore_line().
Referenced by ct_rebind().
static int ct_rebind_one (const lustre_fid * old_fid, const lustre_fid * new_fid) [static]
Definition at line 1566 of file lhsmtool_posix.c.
References CT_ERROR, ct_mkdir_p(), ct_path_archive(), CT_TRACE, DFID, options::o_dry_run, options::o_hsm_root, PFID, and strlcat().
Referenced by ct_rebind(), and ct_rebind_list().
static int ct_remove (const struct hsm_action_item * hai, const long hal_flags) [static]
Definition at line 1231 of file lhsmtool_posix.c.
References ct_begin(), CT_ERROR, ct_fini(), ct_path_archive(), CT_TRACE, err_minor, hsm_action_item::hai_fid, options::o_dry_run, options::o_hsm_root, and strlcat().
Referenced by ct_process_item().
static int ct_restore (const struct hsm_action_item * hai, const long hal_flags) [static]
Definition at line 1114 of file lhsmtool_posix.c.
References ct_begin_restore(), ct_copy_data(), CT_ERROR, ct_fini(), ct_is_retryable(), ct_load_stripe(), ct_path_archive(), ct_restore_stripe(), CT_TRACE, CT_WARN, DFID, err_major, hsm_action_item::hai_fid, HP_FLAG_RETRY, llapi_get_mdt_index_by_fid(), llapi_hsm_action_get_dfid(), llapi_hsm_action_get_fd(), options::o_dry_run, options::o_hsm_root, O_LOV_DELAY_CREATE, options::o_mnt_fd, and PFID.
Referenced by ct_process_item().
static int ct_restore_stripe (const char * src, const char * dst, int dst_fd, const void * lovea, size_t lovea_size) [static]
Definition at line 502 of file lhsmtool_posix.c.
References CT_ERROR, and XATTR_LUSTRE_LOV.
Referenced by ct_restore().
static int ct_run (void) [static]
Definition at line 1791 of file lhsmtool_posix.c.
References CT_ERROR, ct_process_item_async(), CT_TRACE, CT_WARN, err_major, fs_name, hai_first(), hai_next(), hsm_action_list::hal_archive_id, hsm_action_list::hal_count, hsm_action_list::hal_flags, hsm_action_list::hal_fsname, handler(), llapi_error_callback_set(), llapi_hsm_copytool_recv(), llapi_hsm_copytool_register(), llapi_hsm_copytool_unregister(), llapi_hsm_log_error(), llapi_hsm_register_event_fifo(), llapi_hsm_unregister_event_fifo(), options::o_abort_on_error, options::o_archive_cnt, options::o_archive_id, options::o_daemonize, options::o_event_fifo, and options::o_mnt.
Referenced by main().
static int ct_save_stripe (int src_fd, const char * src, const char * dst) [static]
Definition at line 413 of file lhsmtool_posix.c.
References CT_ERROR, CT_TRACE, FILE_PERM, LOV_USER_MAGIC_V1, LOV_USER_MAGIC_V3, lov_user_md, and XATTR_LUSTRE_LOV.
Referenced by ct_archive().
static int ct_setup (void) [static]
Definition at line 1896 of file lhsmtool_posix.c.
References arc_fd, CT_ERROR, fs_name, llapi_msg_set_level(), llapi_search_fsname(), options::o_hsm_root, options::o_mnt, options::o_mnt_fd, and options::o_verbose.
Referenced by main().
static void* ct_thread (void * data) [static]
Definition at line 1332 of file lhsmtool_posix.c.
References ct_process_item(), ct_th_data::hai, and ct_th_data::hal_flags.
Referenced by ct_process_item_async().
static bool fid_is_file (lustre_fid * fid) [static]
Definition at line 1594 of file lhsmtool_posix.c.
References fid_is_igif(), and fid_is_norm().
Referenced by ct_rebind(), and ct_rebind_list().
static void handler (int signal) [static]
Definition at line 1775 of file lhsmtool_posix.c.
References llapi_hsm_copytool_unregister(), llapi_hsm_unregister_event_fifo(), and options::o_event_fifo.
int main (int argc, char ** argv)
Definition at line 1953 of file lhsmtool_posix.c.
References CA_IMPORT, CA_MAXSEQ, CA_REBIND, cmd_name, ct_cleanup(), ct_import_recurse(), ct_max_sequence(), ct_parseopts(), ct_rebind(), ct_run(), ct_setup(), CT_TRACE, CT_WARN, err_major, err_minor, options::o_action, options::o_src, and strlcpy().
static char* path_concat (const char * dirname, const char * basename) [static]
Definition at line 1434 of file lhsmtool_posix.c.
Referenced by ct_import_recurse().
static bool should_ignore_line (const char * line) [static]
Definition at line 1599 of file lhsmtool_posix.c.
Referenced by ct_rebind_list().
static void usage (const char * name, int rc) [static]
Definition at line 158 of file lhsmtool_posix.c.
References cmd_name.
Variable Documentation
int arc_fd = -1 [static]
Definition at line 119 of file lhsmtool_posix.c.
Referenced by ct_cleanup(), and ct_setup().
char cmd_name[PATH_MAX] [static]
Definition at line 124 of file lhsmtool_posix.c.
Referenced by main(), and usage().
struct hsm_copytool_private* ctdata [static]
Definition at line 127 of file lhsmtool_posix.c.
Referenced by helper_archiving(), test1(), test3(), test5(), test6(), and test7().
int err_major [static]
Definition at line 121 of file lhsmtool_posix.c.
Referenced by ct_archive(), ct_copy_data(), ct_import_one(), ct_import_recurse(), ct_rebind_list(), ct_restore(), ct_run(), and main().
int err_minor [static]
Definition at line 122 of file lhsmtool_posix.c.
Referenced by ct_archive(), ct_process_item(), ct_remove(), and main().
char fs_name[MAX_OBD_NAME+1] [static]
Definition at line 125 of file lhsmtool_posix.c.
Referenced by ct_run(), and ct_setup().
struct options opt
Initial value:
 {
        .o_copy_attrs = 1,
        .o_shadow_tree = 1,
        .o_verbose = LLAPI_MSG_INFO,
        .o_copy_xattrs = 1,
        .o_report_int = REPORT_INTERVAL_DEFAULT,
        .o_chunk_size = ONE_MB,
}
Definition at line 105 of file lhsmtool_posix.c.
Referenced by handle_help(), iam_convert(), jt_add_net(), jt_add_route(), jt_config_lnet(), jt_del_net(), jt_del_route(), jt_export(), jt_import(), jt_lfsck_query(), jt_lfsck_start(), jt_lfsck_stop(), jt_show_net(), jt_show_route(), ksocknal_lib_eager_ack(), main(), parse_one_option(), parse_options(), parse_opts(), process_args(), srpc_do_bulk(), and srpc_prepare_bulk().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.