Lustre: lnet/lnet/lib-msg.c File Reference
lnet/lnet/lib-msg.c File Reference
#include <lnet/lib-lnet.h>
Defines
#define DEBUG_SUBSYSTEM S_LNET
Functions
void lnet_build_unlink_event (lnet_libmd_t *md, lnet_event_t *ev)
void lnet_build_msg_event (lnet_msg_t *msg, lnet_event_kind_t ev_type)
void lnet_msg_commit (lnet_msg_t *msg, int cpt)
static void lnet_msg_decommit_tx (lnet_msg_t *msg, int status)
static void lnet_msg_decommit_rx (lnet_msg_t *msg, int status)
void lnet_msg_decommit (lnet_msg_t *msg, int cpt, int status)
void lnet_msg_attach_md (lnet_msg_t *msg, lnet_libmd_t *md, unsigned int offset, unsigned int mlen)
void lnet_msg_detach_md (lnet_msg_t *msg, int status)
static int lnet_complete_msg_locked (lnet_msg_t *msg, int cpt)
void lnet_finalize (lnet_ni_t *ni, lnet_msg_t *msg, int status)
void lnet_msg_container_cleanup (struct lnet_msg_container *container)
int lnet_msg_container_setup (struct lnet_msg_container *container, int cpt)
void lnet_msg_containers_destroy (void)
int lnet_msg_containers_create (void)
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 41 of file lib-msg.c.
Function Documentation
void lnet_build_msg_event (lnet_msg_t * msg, lnet_event_kind_t ev_type)
Definition at line 64 of file lib-msg.c.
References lnet_event_t::hdr_data, lnet_event_t::initiator, LASSERT, LBUG, le32_to_cpu, le64_to_cpu, lnet_t::ln_pid, LNET_EVENT_ACK, LNET_EVENT_GET, LNET_EVENT_PUT, LNET_EVENT_REPLY, LNET_EVENT_SEND, LNET_MSG_GET, LNET_MSG_PUT, LNET_NID_ANY, lnet_event_t::match_bits, lnet_event_t::mlength, lnet_msg::msg_ev, lnet_msg::msg_from, lnet_msg::msg_hdr, lnet_msg::msg_offset, lnet_msg::msg_routing, lnet_msg::msg_type, lnet_msg::msg_wanted, lnet_process_id_t::nid, lnet_event_t::offset, lnet_process_id_t::pid, lnet_event_t::pt_index, lnet_event_t::rlength, lnet_event_t::sender, lnet_event_t::target, the_lnet, and lnet_event_t::type.
Referenced by lnet_create_reply_msg(), lnet_parse_ack(), lnet_parse_get(), lnet_parse_reply(), lnet_recv_put(), LNetGet(), and LNetPut().
void lnet_build_unlink_event (lnet_libmd_t * md, lnet_event_t * ev)
Definition at line 46 of file lib-msg.c.
References ENTRY, EXIT, LNET_EVENT_UNLINK, lnet_md2handle(), lnet_md_deconstruct(), lnet_event_t::md, lnet_event_t::md_handle, lnet_event_t::status, lnet_event_t::type, and lnet_event_t::unlinked.
Referenced by LNetMDUnlink(), and LNetMEUnlink().
static int lnet_complete_msg_locked (lnet_msg_t * msg, int cpt) [static]
Definition at line 362 of file lib-msg.c.
References cpu_to_le32, lnet_event_t::initiator, LASSERT, LNET_EVENT_PUT, LNET_MSG_ACK, lnet_msg_decommit(), lnet_msg_free(), lnet_net_lock(), lnet_net_unlock(), LNET_NID_ANY, lnet_prep_send(), lnet_send(), lnet_event_t::match_bits, lnet_event_t::mlength, lnet_msg::msg_ack, lnet_msg::msg_ev, lnet_msg::msg_hdr, lnet_msg::msg_onactivelist, lnet_msg::msg_receiving, lnet_msg::msg_routing, lnet_msg::msg_sending, lnet_process_id_t::nid, lnet_event_t::status, status, lnet_event_t::target, and lnet_event_t::type.
Referenced by lnet_finalize().
void lnet_finalize (lnet_ni_t * ni, lnet_msg_t * msg, int status)
Definition at line 438 of file lib-msg.c.
References CDEBUG, D_WARNING, LASSERT, lnet_libhandle::lh_cookie, libcfs_id2str(), libcfs_nid2str(), list_add_tail(), list_del(), list_empty(), list_entry, lnet_t::ln_delay_rules, lnet_t::ln_msg_containers, lnet_complete_msg_locked(), lnet_cpt_of_cookie(), lnet_delay_rule_check(), lnet_msg_detach_md(), lnet_msg_free(), lnet_msgtyp2str(), lnet_net_lock(), lnet_net_unlock(), lnet_res_lock(), lnet_res_unlock(), lnet_peer::lp_nid, lnet_libmd::md_lh, lnet_msg_container::msc_finalizers, lnet_msg_container::msc_finalizing, lnet_msg_container::msc_nfinalizers, lnet_msg::msg_ack, lnet_msg::msg_ev, lnet_msg::msg_list, lnet_msg::msg_md, lnet_msg::msg_onactivelist, lnet_msg::msg_peerrtrcredit, lnet_msg::msg_peertxcredit, lnet_msg::msg_receiving, lnet_msg::msg_routing, lnet_msg::msg_rtrcredit, lnet_msg::msg_rx_committed, lnet_msg::msg_rx_cpt, lnet_msg::msg_rxpeer, lnet_msg::msg_sending, lnet_msg::msg_target, lnet_msg::msg_target_is_router, lnet_msg::msg_tx_committed, lnet_msg::msg_tx_cpt, lnet_msg::msg_txcredit, lnet_msg::msg_txpeer, lnet_msg::msg_type, list_head::next, lnet_event_t::status, the_lnet, and unlikely.
Referenced by delayed_msg_process(), kgnilnd_recv(), kgnilnd_setup_rdma(), kgnilnd_tx_done(), kiblnd_recv(), kiblnd_reply(), kiblnd_tx_done(), ksocknal_destroy_conn(), ksocknal_process_receive(), ksocknal_tx_done(), lnet_drop_delayed_msg_list(), lnet_drop_routed_msgs_locked(), lnet_ni_recv(), lnet_ni_send(), lnet_parse(), lnet_parse_get(), lnet_post_send_locked(), LNetGet(), LNetPut(), and lolnd_recv().
void lnet_msg_attach_md (lnet_msg_t * msg, lnet_libmd_t * md, unsigned int offset, unsigned int mlen)
Definition at line 311 of file lib-msg.c.
References LASSERT, lnet_md2handle(), lnet_md_deconstruct(), LNET_MD_THRESH_INF, lnet_event_t::md, lnet_event_t::md_handle, lnet_libmd::md_refcount, lnet_libmd::md_threshold, lnet_msg::msg_ev, lnet_msg::msg_md, lnet_msg::msg_offset, lnet_msg::msg_receiving, lnet_msg::msg_routing, and lnet_msg::msg_wanted.
Referenced by lnet_create_reply_msg(), lnet_parse_ack(), lnet_parse_reply(), lnet_try_match_md(), LNetGet(), and LNetPut().
void lnet_msg_commit (lnet_msg_t * msg, int cpt)
Definition at line 140 of file lib-msg.c.
References LASSERT, list_add(), lnet_t::ln_counters, lnet_t::ln_msg_containers, lnet_msg_container::msc_active, lnet_msg::msg_activelist, lnet_msg::msg_onactivelist, lnet_msg::msg_receiving, lnet_msg::msg_rx_committed, lnet_msg::msg_rx_cpt, lnet_msg::msg_sending, lnet_msg::msg_tx_committed, lnet_msg::msg_tx_cpt, lnet_counters::msgs_alloc, lnet_counters::msgs_max, and the_lnet.
Referenced by lnet_create_reply_msg(), lnet_parse(), and lnet_send().
void lnet_msg_container_cleanup (struct lnet_msg_container * container)
Definition at line 544 of file lib-msg.c.
References CERROR, LASSERT, LIBCFS_FREE, list_del(), list_empty(), list_entry, lnet_msg_free(), lnet_msg_container::msc_active, lnet_msg_container::msc_finalizers, lnet_msg_container::msc_init, lnet_msg_container::msc_nfinalizers, msg, lnet_msg::msg_activelist, lnet_msg::msg_onactivelist, and list_head::next.
Referenced by lnet_msg_container_setup(), and lnet_msg_containers_destroy().
int lnet_msg_container_setup (struct lnet_msg_container * container, int cpt)
Definition at line 575 of file lib-msg.c.
References CERROR, cfs_cpt_weight(), INIT_LIST_HEAD, LIBCFS_CPT_ALLOC, lnet_cpt_table, lnet_msg_container_cleanup(), lnet_msg_container::msc_active, lnet_msg_container::msc_finalizers, lnet_msg_container::msc_finalizing, lnet_msg_container::msc_init, and lnet_msg_container::msc_nfinalizers.
Referenced by lnet_msg_containers_create().
int lnet_msg_containers_create (void)
Definition at line 618 of file lib-msg.c.
References CERROR, cfs_percpt_alloc(), cfs_percpt_for_each, lnet_t::ln_msg_containers, lnet_cpt_table, lnet_msg_container_setup(), lnet_msg_containers_destroy(), and the_lnet.
Referenced by lnet_prepare().
void lnet_msg_containers_destroy (void)
Definition at line 602 of file lib-msg.c.
References cfs_percpt_for_each, cfs_percpt_free(), lnet_t::ln_msg_containers, lnet_msg_container_cleanup(), and the_lnet.
Referenced by lnet_msg_containers_create(), and lnet_unprepare().
void lnet_msg_decommit (lnet_msg_t * msg, int cpt, int status)
Definition at line 277 of file lib-msg.c.
References LASSERT, list_del(), lnet_t::ln_counters, lnet_msg_decommit_rx(), lnet_msg_decommit_tx(), lnet_net_lock(), lnet_net_unlock(), lnet_msg::msg_activelist, lnet_msg::msg_onactivelist, lnet_msg::msg_rx_committed, lnet_msg::msg_rx_cpt, lnet_msg::msg_tx_committed, lnet_msg::msg_tx_cpt, lnet_counters::msgs_alloc, and the_lnet.
Referenced by lnet_complete_msg_locked().
static void lnet_msg_decommit_rx (lnet_msg_t * msg, int status) [static]
Definition at line 223 of file lib-msg.c.
References LASSERT, lnet_t::ln_counters, LNET_EVENT_ACK, LNET_EVENT_GET, LNET_EVENT_PUT, LNET_EVENT_REPLY, LNET_MSG_ACK, LNET_MSG_GET, LNET_MSG_PUT, LNET_MSG_REPLY, lnet_return_rx_credits_locked(), lnet_msg::msg_ev, lnet_msg::msg_routing, lnet_msg::msg_rx_committed, lnet_msg::msg_rx_cpt, lnet_msg::msg_tx_committed, lnet_msg::msg_type, lnet_msg::msg_wanted, lnet_counters::recv_count, lnet_counters::recv_length, lnet_counters::send_length, the_lnet, and lnet_event_t::type.
Referenced by lnet_msg_decommit().
static void lnet_msg_decommit_tx (lnet_msg_t * msg, int status) [static]
Definition at line 173 of file lib-msg.c.
References LASSERT, lnet_t::ln_counters, LNET_EVENT_GET, LNET_EVENT_PUT, LNET_EVENT_SEND, LNET_MSG_ACK, LNET_MSG_GET, LNET_MSG_PUT, LNET_MSG_REPLY, lnet_return_tx_credits_locked(), lnet_msg::msg_ev, lnet_msg::msg_len, lnet_msg::msg_routing, lnet_msg::msg_rx_committed, lnet_msg::msg_tx_committed, lnet_msg::msg_tx_cpt, lnet_msg::msg_type, lnet_counters::route_count, lnet_counters::route_length, lnet_counters::send_count, lnet_counters::send_length, the_lnet, and lnet_event_t::type.
Referenced by lnet_msg_decommit().
void lnet_msg_detach_md (lnet_msg_t * msg, int status)
Definition at line 339 of file lib-msg.c.
References LASSERT, lnet_eq_enqueue_event(), lnet_md_unlink(), lnet_md_unlinkable(), lnet_libmd::md_eq, lnet_libmd::md_refcount, lnet_msg::msg_ev, lnet_msg::msg_md, lnet_event_t::status, and lnet_event_t::unlinked.
Referenced by lnet_finalize().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.