Lustre: lnet/lnet/lib-eq.c File Reference
lnet/lnet/lib-eq.c File Reference
#include <lnet/lib-lnet.h>
Defines
#define DEBUG_SUBSYSTEM S_LNET
Functions
int LNetEQAlloc (unsigned int count, lnet_eq_handler_t callback, lnet_handle_eq_t *handle)
Create an event queue that has room for count number of events.
int LNetEQFree (lnet_handle_eq_t eqh)
Release the resources associated with an event queue if it's idle; otherwise do nothing and it's up to the user to try again.
void lnet_eq_enqueue_event (lnet_eq_t *eq, lnet_event_t *ev)
static int lnet_eq_dequeue_event (lnet_eq_t *eq, lnet_event_t *ev)
int LNetEQGet (lnet_handle_eq_t eventq, lnet_event_t *event)
A nonblocking function that can be used to get the next event in an EQ.
int LNetEQWait (lnet_handle_eq_t eventq, lnet_event_t *event)
Block the calling process until there is an event in the EQ.
static int lnet_eq_wait_locked (int *timeout_ms) __must_hold(&the_lnet.ln_eq_wait_lock)
int LNetEQPoll (lnet_handle_eq_t *eventqs, int neq, int timeout_ms, lnet_event_t *event, int *which)
Block the calling process until there's an event from a set of EQs or timeout happens.
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 41 of file lib-eq.c.
Function Documentation
static int lnet_eq_dequeue_event (lnet_eq_t * eq, lnet_event_t * ev) [static]
Definition at line 241 of file lib-eq.c.
References CDEBUG, D_INFO, D_NET, ENTRY, lnet_eq::eq_deq_seq, lnet_eq::eq_events, lnet_eq::eq_size, LNET_SEQ_GT, RETURN, and lnet_event_t::sequence.
Referenced by LNetEQPoll().
void lnet_eq_enqueue_event (lnet_eq_t * eq, lnet_event_t * ev)
Definition at line 212 of file lib-eq.c.
References lnet_eq::eq_callback, lnet_eq::eq_enq_seq, lnet_eq::eq_events, lnet_eq::eq_size, LASSERT, lnet_t::ln_eq_waitq, LNET_EQ_HANDLER_NONE, lnet_eq_wait_lock, lnet_eq_wait_unlock, lnet_event_t::sequence, and the_lnet.
Referenced by lnet_msg_detach_md(), LNetMDUnlink(), and LNetMEUnlink().
static int lnet_eq_wait_locked (int * timeout_ms) [static]
Definition at line 326 of file lib-eq.c.
References cfs_duration_usec(), cfs_time_current(), cfs_time_seconds(), cfs_time_sub(), lnet_t::ln_eq_waitq, lnet_eq_wait_lock, lnet_eq_wait_unlock, now(), and the_lnet.
Referenced by LNetEQPoll().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.