Lustre: lnet/lnet/lib-md.c File Reference
lnet/lnet/lib-md.c File Reference
#include <lnet/lib-lnet.h>
Defines
#define DEBUG_SUBSYSTEM S_LNET
Functions
void lnet_md_unlink (lnet_libmd_t *md)
static int lnet_md_build (lnet_libmd_t *lmd, lnet_md_t *umd, int unlink)
static int lnet_md_link (lnet_libmd_t *md, lnet_handle_eq_t eq_handle, int cpt)
void lnet_md_deconstruct (lnet_libmd_t *lmd, lnet_md_t *umd)
static int lnet_md_validate (lnet_md_t *umd)
int LNetMDAttach (lnet_handle_me_t meh, lnet_md_t umd, lnet_unlink_t unlink, lnet_handle_md_t *handle)
Create a memory descriptor and attach it to a ME.
int LNetMDBind (lnet_md_t umd, lnet_unlink_t unlink, lnet_handle_md_t *handle)
Create a "free floating" memory descriptor - a MD that is not associated with a ME.
int LNetMDUnlink (lnet_handle_md_t mdh)
Unlink the memory descriptor from any ME it may be linked to and release the internal resources associated with it.
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 41 of file lib-md.c.
Function Documentation
static int lnet_md_build (lnet_libmd_t * lmd, lnet_md_t * umd, int unlink) [static]
Definition at line 88 of file lib-md.c.
References lnet_libmd::iov, lnet_libmd::kiov, lnet_kiov_t::kiov_len, lnet_kiov_t::kiov_offset, lnet_md_t::length, LNET_MD_FLAG_AUTO_UNLINK, LNET_MD_IOVEC, LNET_MD_KIOV, LNET_MD_MAX_SIZE, LNET_UNLINK, lnet_md_t::max_size, lnet_libmd::md_eq, lnet_libmd::md_flags, lnet_libmd::md_iov, lnet_libmd::md_length, lnet_libmd::md_max_size, lnet_libmd::md_me, lnet_libmd::md_niov, lnet_libmd::md_offset, lnet_libmd::md_options, lnet_libmd::md_refcount, lnet_libmd::md_start, lnet_libmd::md_threshold, lnet_libmd::md_user_ptr, lnet_md_t::options, lnet_md_t::start, lnet_md_t::threshold, and lnet_md_t::user_ptr.
Referenced by LNetMDAttach(), and LNetMDBind().
void lnet_md_deconstruct (lnet_libmd_t * lmd, lnet_md_t * umd)
Definition at line 201 of file lib-md.c.
References lnet_md_t::eq_handle, lnet_md_t::length, lnet_eq2handle(), LNET_MD_IOVEC, LNET_MD_KIOV, lnet_md_t::max_size, lnet_libmd::md_eq, lnet_libmd::md_length, lnet_libmd::md_max_size, lnet_libmd::md_niov, lnet_libmd::md_options, lnet_libmd::md_start, lnet_libmd::md_threshold, lnet_libmd::md_user_ptr, lnet_md_t::options, lnet_md_t::start, lnet_md_t::threshold, and lnet_md_t::user_ptr.
Referenced by lnet_build_unlink_event(), and lnet_msg_attach_md().
static int lnet_md_link (lnet_libmd_t * md, lnet_handle_eq_t eq_handle, int cpt) [static]
Definition at line 166 of file lib-md.c.
References lnet_eq::eq_refs, LASSERT, list_add(), list_empty(), lnet_t::ln_md_containers, lnet_handle2eq(), lnet_res_lh_initialize(), LNetHandleIsInvalid(), lnet_libmd::md_eq, lnet_libmd::md_lh, lnet_libmd::md_list, lnet_res_container::rec_active, and the_lnet.
Referenced by LNetMDAttach(), and LNetMDBind().
void lnet_md_unlink (lnet_libmd_t * md)
Definition at line 47 of file lib-md.c.
References CDEBUG, D_NET, lnet_eq::eq_refs, LASSERT, lnet_libhandle::lh_cookie, list_del_init(), list_empty(), lnet_cpt_of_cookie(), LNET_MD_FLAG_ZOMBIE, lnet_md_free(), lnet_me_unlink(), lnet_ptl_detach_md(), lnet_res_lh_invalidate(), LNET_UNLINK, lnet_libmd::md_eq, lnet_libmd::md_flags, lnet_libmd::md_lh, lnet_libmd::md_list, lnet_libmd::md_me, lnet_libmd::md_refcount, and lnet_me::me_unlink.
Referenced by lnet_me_unlink(), lnet_msg_detach_md(), lnet_try_match_md(), and LNetMDUnlink().
static int lnet_md_validate (lnet_md_t * umd) [static]
Definition at line 219 of file lib-md.c.
References CERROR, lnet_md_t::length, LNET_MAX_IOV, LNET_MD_IOVEC, LNET_MD_KIOV, lnet_md_t::options, and lnet_md_t::start.
Referenced by LNetMDAttach(), and LNetMDBind().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.