Lustre: lnet/lnet/lib-socket.c File Reference
lnet/lnet/lib-socket.c File Reference
#include <linux/if.h>
#include <linux/in.h>
#include <linux/net.h>
#include <linux/file.h>
#include <linux/pagemap.h>
#include <linux/syscalls.h>
#include <net/sock.h>
#include <libcfs/libcfs.h>
#include <lnet/lib-lnet.h>
Defines
#define DEBUG_SUBSYSTEM S_LNET
Functions
static int kernel_sock_unlocked_ioctl (struct file *filp, int cmd, unsigned long arg)
static int lnet_sock_ioctl (int cmd, unsigned long arg)
int lnet_ipif_query (char *name, int *up, __u32 *ip, __u32 *mask)
void lnet_ipif_free_enumeration (char **names, int n)
int lnet_ipif_enumerate (char ***namesp)
int lnet_sock_write (struct socket *sock, void *buffer, int nob, int timeout)
int lnet_sock_read (struct socket *sock, void *buffer, int nob, int timeout)
static int lnet_sock_create (struct socket **sockp, int *fatal, __u32 local_ip, int local_port)
int lnet_sock_setbuf (struct socket *sock, int txbufsize, int rxbufsize)
int lnet_sock_getaddr (struct socket *sock, bool remote, __u32 *ip, int *port)
int lnet_sock_getbuf (struct socket *sock, int *txbufsize, int *rxbufsize)
int lnet_sock_listen (struct socket **sockp, __u32 local_ip, int local_port, int backlog)
static wait_queue_head_t * sk_sleep (struct sock *sk)
int lnet_sock_accept (struct socket **newsockp, struct socket *sock)
int lnet_sock_connect (struct socket **sockp, int *fatal, __u32 local_ip, int local_port, __u32 peer_ip, int peer_port)
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 36 of file lib-socket.c.
Function Documentation
static int kernel_sock_unlocked_ioctl (struct file * filp, int cmd, unsigned long arg) [static]
Definition at line 54 of file lib-socket.c.
Referenced by lnet_sock_ioctl().
int lnet_ipif_enumerate (char *** namesp)
Definition at line 192 of file lib-socket.c.
References CERROR, CWARN, LASSERT, LIBCFS_ALLOC, LIBCFS_FREE, lnet_ipif_free_enumeration(), lnet_sock_ioctl(), and strnlen.
Referenced by ksocknal_enumerate_interfaces(), and lnet_ipaddr_enumerate().
void lnet_ipif_free_enumeration (char ** names, int n)
Definition at line 178 of file lib-socket.c.
References LASSERT, and LIBCFS_FREE.
Referenced by ksocknal_enumerate_interfaces(), lnet_ipaddr_enumerate(), and lnet_ipif_enumerate().
int lnet_ipif_query (char * name, int * up, __u32 * ip, __u32 * mask)
Definition at line 111 of file lib-socket.c.
References CDEBUG, CERROR, CLASSERT, D_NET, lnet_sock_ioctl(), and strnlen.
Referenced by kiblnd_create_dev(), ksocknal_enumerate_interfaces(), ksocknal_startup(), and lnet_ipaddr_enumerate().
int lnet_sock_accept (struct socket ** newsockp, struct socket * sock)
Definition at line 568 of file lib-socket.c.
References CERROR, and sk_sleep().
Referenced by lnet_acceptor().
int lnet_sock_connect (struct socket ** sockp, int * fatal, __u32 local_ip, int local_port, __u32 peer_ip, int peer_port)
Definition at line 607 of file lib-socket.c.
References CDEBUG_LIMIT, D_NET, D_NETERROR, and lnet_sock_create().
Referenced by lnet_connect().
static int lnet_sock_create (struct socket ** sockp, int * fatal, __u32 local_ip, int local_port) [static]
Definition at line 412 of file lib-socket.c.
References CDEBUG, CERROR, and D_NET.
Referenced by lnet_sock_connect(), and lnet_sock_listen().
int lnet_sock_getaddr (struct socket * sock, bool remote, __u32 * ip, int * port)
Definition at line 497 of file lib-socket.c.
References CERROR.
Referenced by ksocknal_accept(), ksocknal_lib_get_conn_addrs(), lnet_accept(), and lnet_acceptor().
int lnet_sock_getbuf (struct socket * sock, int * txbufsize, int * rxbufsize)
Definition at line 524 of file lib-socket.c.
Referenced by ksocknal_lib_get_conn_tunables().
static int lnet_sock_ioctl (int cmd, unsigned long arg) [static]
Definition at line 67 of file lib-socket.c.
References CERROR, and kernel_sock_unlocked_ioctl().
Referenced by lnet_ipif_enumerate(), and lnet_ipif_query().
int lnet_sock_listen (struct socket ** sockp, __u32 local_ip, int local_port, int backlog)
Definition at line 537 of file lib-socket.c.
References CERROR, fatal(), and lnet_sock_create().
Referenced by lnet_acceptor().
int lnet_sock_read (struct socket * sock, void * buffer, int nob, int timeout)
Definition at line 354 of file lib-socket.c.
References CERROR, and LASSERT.
Referenced by ksocknal_recv_hello(), ksocknal_recv_hello_v1(), ksocknal_recv_hello_v2(), lnet_accept(), and lnet_acceptor().
int lnet_sock_setbuf (struct socket * sock, int txbufsize, int rxbufsize)
Definition at line 466 of file lib-socket.c.
References CERROR.
Referenced by ksocknal_lib_setup_sock().
int lnet_sock_write (struct socket * sock, void * buffer, int nob, int timeout)
Definition at line 287 of file lib-socket.c.
References CERROR, LASSERT, and lnet_sock_write().
Referenced by ksocknal_send_hello_v1(), ksocknal_send_hello_v2(), lnet_accept(), lnet_connect(), and lnet_sock_write().
static wait_queue_head_t* sk_sleep (struct sock * sk) [inline, static]
Definition at line 561 of file lib-socket.c.
Referenced by lnet_sock_accept().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.