Lustre: lnet/lnet/lib-ptl.c File Reference
lnet/lnet/lib-ptl.c File Reference
#include <lnet/lib-lnet.h>
Defines
#define DEBUG_SUBSYSTEM S_LNET
Functions
module_param (portal_rotor, int, 0644)
MODULE_PARM_DESC (portal_rotor,"redirect PUTs to different cpu-partitions")
static int lnet_ptl_match_type (unsigned int index, lnet_process_id_t match_id, __u64 mbits, __u64 ignore_bits)
static void lnet_ptl_enable_mt (struct lnet_portal *ptl, int cpt)
static void lnet_ptl_disable_mt (struct lnet_portal *ptl, int cpt)
static int lnet_try_match_md (lnet_libmd_t *md, struct lnet_match_info *info, struct lnet_msg *msg)
static struct lnet_match_table * lnet_match2mt (struct lnet_portal *ptl, lnet_process_id_t id, __u64 mbits)
struct lnet_match_table * lnet_mt_of_attach (unsigned int index, lnet_process_id_t id, __u64 mbits, __u64 ignore_bits, lnet_ins_pos_t pos)
static struct lnet_match_table * lnet_mt_of_match (struct lnet_match_info *info, struct lnet_msg *msg)
static int lnet_mt_test_exhausted (struct lnet_match_table *mtable, int pos)
static void lnet_mt_set_exhausted (struct lnet_match_table *mtable, int pos, int exhausted)
struct list_head * lnet_mt_match_head (struct lnet_match_table *mtable, lnet_process_id_t id, __u64 mbits)
int lnet_mt_match_md (struct lnet_match_table *mtable, struct lnet_match_info *info, struct lnet_msg *msg)
static int lnet_ptl_match_early (struct lnet_portal *ptl, struct lnet_msg *msg)
static int lnet_ptl_match_delay (struct lnet_portal *ptl, struct lnet_match_info *info, struct lnet_msg *msg)
int lnet_ptl_match_md (struct lnet_match_info *info, struct lnet_msg *msg)
void lnet_ptl_detach_md (lnet_me_t *me, lnet_libmd_t *md)
void lnet_ptl_attach_md (lnet_me_t *me, lnet_libmd_t *md, struct list_head *matches, struct list_head *drops)
static void lnet_ptl_cleanup (struct lnet_portal *ptl)
static int lnet_ptl_setup (struct lnet_portal *ptl, int index)
void lnet_portals_destroy (void)
int lnet_portals_create (void)
int LNetSetLazyPortal (int portal)
Turn on the lazy portal attribute.
int lnet_clear_lazy_portal (struct lnet_ni *ni, int portal, char *reason)
int LNetClearLazyPortal (int portal)
Turn off the lazy portal attribute.
Variables
int portal_rotor = LNET_PTL_ROTOR_HASH_RT
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 37 of file lib-ptl.c.
Function Documentation
int lnet_clear_lazy_portal (struct lnet_ni * ni, int portal, char * reason)
Definition at line 919 of file lib-ptl.c.
References CDEBUG, CWARN, D_NET, list_for_each_entry_safe, LIST_HEAD_INIT, list_move(), list_splice_init(), lnet_t::ln_nportals, lnet_t::ln_portals, lnet_t::ln_shutdown, lnet_drop_delayed_msg_list(), LNET_LOCK_EX, lnet_ptl_is_lazy(), LNET_PTL_LAZY, lnet_ptl_lock, lnet_ptl_unlock, lnet_ptl_unsetopt(), lnet_res_lock(), lnet_res_unlock(), lnet_peer::lp_ni, msg, lnet_msg::msg_list, lnet_msg::msg_rxpeer, lnet_portal::ptl_msg_delayed, and the_lnet.
Referenced by lnet_shutdown_lndni(), and LNetClearLazyPortal().
static struct lnet_match_table* lnet_match2mt (struct lnet_portal * ptl, lnet_process_id_t id, __u64 mbits) [static, read]
Definition at line 218 of file lib-ptl.c.
References LNET_CPT_NUMBER, lnet_cpt_of_nid(), lnet_ptl_is_unique(), and lnet_portal::ptl_mtables.
Referenced by lnet_mt_of_attach(), and lnet_mt_of_match().
struct list_head* lnet_mt_match_head (struct lnet_match_table * mtable, lnet_process_id_t id, __u64 mbits) [read]
Definition at line 358 of file lib-ptl.c.
References LASSERT, lnet_t::ln_portals, LNET_MT_HASH_BITS, LNET_MT_HASH_MASK, lnet_ptl_is_unique(), lnet_ptl_is_wildcard(), lnet_match_table::mt_mhash, lnet_match_table::mt_portal, and the_lnet.
Referenced by lnet_mt_match_md(), and LNetMEAttach().
int lnet_mt_match_md (struct lnet_match_table * mtable, struct lnet_match_info * info, struct lnet_msg * msg)
Definition at line 375 of file lib-ptl.c.
References head, LASSERT, list_empty(), list_for_each_entry_safe, lnet_t::ln_portals, LNET_MATCHMD_DROP, LNET_MATCHMD_EXHAUSTED, LNET_MATCHMD_FINISH, LNET_MATCHMD_NONE, LNET_MD_OP_GET, LNET_MT_HASH_IGNORE, lnet_mt_match_head(), lnet_mt_set_exhausted(), lnet_mt_test_exhausted(), lnet_ptl_is_lazy(), lnet_ptl_is_wildcard(), lnet_try_match_md(), lnet_libmd::md_me, lnet_me::me_md, lnet_match_info::mi_id, lnet_match_info::mi_mbits, lnet_match_info::mi_opc, lnet_match_info::mi_portal, lnet_match_table::mt_mhash, lnet_match_table::mt_portal, and the_lnet.
Referenced by lnet_ptl_match_delay(), and lnet_ptl_match_md().
struct lnet_match_table* lnet_mt_of_attach (unsigned int index, lnet_process_id_t id, __u64 mbits, __u64 ignore_bits, lnet_ins_pos_t pos) [read]
Definition at line 229 of file lib-ptl.c.
References LASSERT, lnet_t::ln_nportals, lnet_t::ln_portals, lnet_cpt_current, LNET_CPT_NUMBER, LNET_INS_AFTER, LNET_INS_BEFORE, LNET_INS_LOCAL, lnet_match2mt(), lnet_ptl_match_type(), lnet_portal::ptl_index, lnet_portal::ptl_mtables, and the_lnet.
Referenced by LNetMEAttach().
static struct lnet_match_table* lnet_mt_of_match (struct lnet_match_info * info, struct lnet_msg * msg) [static, read]
Definition at line 263 of file lib-ptl.c.
References LASSERT, lnet_t::ln_nportals, lnet_t::ln_portals, lnet_cpt_current, LNET_CPT_NUMBER, lnet_cpt_of_nid(), lnet_match2mt(), LNET_NIDNET(), lnet_ptl_is_unique(), lnet_ptl_is_wildcard(), LNET_PTL_ROTOR_HASH_RT, LNET_PTL_ROTOR_OFF, LNET_PTL_ROTOR_ON, lnet_match_info::mi_id, lnet_match_info::mi_mbits, lnet_match_info::mi_portal, lnet_msg::msg_hdr, lnet_match_table::mt_enabled, portal_rotor, lnet_portal::ptl_mt_maps, lnet_portal::ptl_mt_nmaps, lnet_portal::ptl_mtables, lnet_portal::ptl_rotor, and the_lnet.
Referenced by lnet_ptl_match_md().
static void lnet_mt_set_exhausted (struct lnet_match_table * mtable, int pos, int exhausted) [static]
Definition at line 340 of file lib-ptl.c.
References __u64, LASSERT, lnet_t::ln_portals, LNET_MT_BITS_U64, LNET_MT_HASH_IGNORE, lnet_ptl_is_wildcard(), lnet_match_table::mt_exhausted, lnet_match_table::mt_portal, and the_lnet.
Referenced by lnet_mt_match_md(), and lnet_ptl_attach_md().
static int lnet_mt_test_exhausted (struct lnet_match_table * mtable, int pos) [static]
Definition at line 315 of file lib-ptl.c.
References __u64, LASSERT, lnet_t::ln_portals, LNET_MT_BITS_U64, LNET_MT_EXHAUSTED_BMAP, LNET_MT_HASH_IGNORE, lnet_ptl_is_wildcard(), lnet_match_table::mt_exhausted, lnet_match_table::mt_portal, and the_lnet.
Referenced by lnet_mt_match_md(), and lnet_ptl_attach_md().
int lnet_portals_create (void)
Definition at line 843 of file lib-ptl.c.
References CERROR, cfs_array_alloc(), lnet_t::ln_nportals, lnet_t::ln_portals, LNET_CPT_NUMBER, lnet_portals_destroy(), lnet_ptl_setup(), MAX_PORTALS, offsetof, size, and the_lnet.
Referenced by lnet_prepare().
void lnet_portals_destroy (void)
Definition at line 828 of file lib-ptl.c.
References cfs_array_free(), lnet_t::ln_nportals, lnet_t::ln_portals, lnet_ptl_cleanup(), and the_lnet.
Referenced by lnet_portals_create(), and lnet_unprepare().
void lnet_ptl_attach_md (lnet_me_t * me, lnet_libmd_t * md, struct list_head * matches, struct list_head * drops)
Definition at line 650 of file lib-ptl.c.
References CDEBUG, D_NET, head, LASSERT, lnet_libhandle::lh_cookie, libcfs_id2str(), list_add_tail(), list_del_init(), list_empty(), list_for_each_entry_safe, lnet_t::ln_portals, lnet_cpt_of_cookie(), LNET_MATCHMD_EXHAUSTED, LNET_MATCHMD_FINISH, LNET_MATCHMD_NONE, LNET_MATCHMD_OK, LNET_MD_OP_PUT, lnet_mt_set_exhausted(), lnet_mt_test_exhausted(), lnet_ptl_enable_mt(), lnet_ptl_is_wildcard(), lnet_ptl_lock, lnet_ptl_unlock, lnet_try_match_md(), LPU64, lnet_libmd::md_lh, lnet_libmd::md_me, lnet_libmd::md_refcount, lnet_me::me_md, lnet_me::me_portal, lnet_me::me_pos, lnet_match_info::mi_id, lnet_match_info::mi_mbits, lnet_match_info::mi_opc, lnet_match_info::mi_portal, lnet_match_info::mi_rlength, lnet_match_info::mi_roffset, msg, lnet_msg::msg_hdr, lnet_msg::msg_list, lnet_msg::msg_rx_delayed, lnet_match_table::mt_enabled, lnet_process_id_t::nid, lnet_process_id_t::pid, lnet_portal::ptl_msg_delayed, lnet_portal::ptl_msg_stealing, lnet_portal::ptl_mtables, and the_lnet.
Referenced by LNetMDAttach().
static void lnet_ptl_cleanup (struct lnet_portal * ptl) [static]
Definition at line 744 of file lib-ptl.c.
References CERROR, cfs_percpt_for_each, cfs_percpt_free(), LASSERT, LIBCFS_FREE, list_del(), list_empty(), list_entry, lnet_me_free(), LNET_MT_HASH_SIZE, lnet_me::me_list, lnet_match_table::mt_mhash, list_head::next, lnet_portal::ptl_msg_delayed, lnet_portal::ptl_msg_stealing, and lnet_portal::ptl_mtables.
Referenced by lnet_portals_destroy(), and lnet_ptl_setup().
void lnet_ptl_detach_md (lnet_me_t * me, lnet_libmd_t * md)
Definition at line 640 of file lib-ptl.c.
References LASSERT, lnet_libmd::md_me, and lnet_me::me_md.
Referenced by lnet_md_unlink(), and lnet_me_unlink().
static void lnet_ptl_disable_mt (struct lnet_portal * ptl, int cpt) [static]
Definition at line 114 of file lib-ptl.c.
References LASSERT, LNET_CPT_NUMBER, lnet_ptl_is_wildcard(), lnet_match_table::mt_enabled, lnet_portal::ptl_mt_maps, lnet_portal::ptl_mt_nmaps, and lnet_portal::ptl_mtables.
Referenced by lnet_ptl_match_delay(), and lnet_ptl_match_md().
static void lnet_ptl_enable_mt (struct lnet_portal * ptl, int cpt) [static]
Definition at line 89 of file lib-ptl.c.
References LASSERT, lnet_ptl_is_wildcard(), lnet_match_table::mt_enabled, lnet_portal::ptl_mt_maps, lnet_portal::ptl_mt_nmaps, and lnet_portal::ptl_mtables.
Referenced by lnet_ptl_attach_md().
static int lnet_ptl_match_delay (struct lnet_portal * ptl, struct lnet_match_info * info, struct lnet_msg * msg) [static]
Definition at line 463 of file lib-ptl.c.
References LASSERT, list_add_tail(), list_del_init(), list_empty(), LNET_CPT_NUMBER, LNET_MATCHMD_DROP, LNET_MATCHMD_EXHAUSTED, LNET_MATCHMD_FINISH, LNET_MATCHMD_NONE, LNET_MATCHMD_OK, lnet_mt_match_md(), lnet_ptl_disable_mt(), lnet_ptl_is_lazy(), lnet_ptl_is_wildcard(), lnet_ptl_lock, lnet_ptl_unlock, lnet_res_lock(), lnet_res_unlock(), lnet_msg::msg_list, lnet_msg::msg_md, lnet_msg::msg_rx_delayed, lnet_match_table::mt_enabled, lnet_portal::ptl_msg_delayed, lnet_portal::ptl_msg_stealing, lnet_portal::ptl_mt_maps, lnet_portal::ptl_mt_nmaps, and lnet_portal::ptl_mtables.
Referenced by lnet_ptl_match_md().
static int lnet_ptl_match_early (struct lnet_portal * ptl, struct lnet_msg * msg) [static]
Definition at line 431 of file lib-ptl.c.
References likely, list_add_tail(), LNET_MATCHMD_DROP, LNET_MATCHMD_NONE, lnet_ptl_is_lazy(), lnet_ptl_is_unique(), lnet_ptl_is_wildcard(), lnet_ptl_lock, lnet_ptl_unlock, lnet_msg::msg_list, lnet_msg::msg_rx_delayed, lnet_msg::msg_rx_ready_delay, and lnet_portal::ptl_msg_delayed.
Referenced by lnet_ptl_match_md().
int lnet_ptl_match_md (struct lnet_match_info * info, struct lnet_msg * msg)
Definition at line 563 of file lib-ptl.c.
References CDEBUG, CERROR, D_NET, LASSERT, libcfs_id2str(), list_add_tail(), lnet_t::ln_nportals, lnet_t::ln_portals, lnet_t::ln_shutdown, LNET_CPT_NUMBER, LNET_MATCHMD_DROP, LNET_MATCHMD_EXHAUSTED, LNET_MATCHMD_FINISH, LNET_MATCHMD_NONE, LNET_MD_OP_PUT, lnet_mt_match_md(), lnet_mt_of_match(), lnet_ptl_disable_mt(), lnet_ptl_is_lazy(), lnet_ptl_is_unique(), lnet_ptl_lock, lnet_ptl_match_delay(), lnet_ptl_match_early(), lnet_ptl_unlock, lnet_res_lock(), lnet_res_unlock(), LPX64, lnet_match_info::mi_id, lnet_match_info::mi_mbits, lnet_match_info::mi_opc, lnet_match_info::mi_portal, lnet_match_info::mi_rlength, lnet_match_info::mi_roffset, lnet_msg::msg_list, lnet_msg::msg_rx_delayed, lnet_msg::msg_rx_ready_delay, lnet_match_table::mt_cpt, lnet_match_table::mt_enabled, lnet_portal::ptl_msg_delayed, and the_lnet.
Referenced by lnet_parse_get(), and lnet_parse_put().
static int lnet_ptl_match_type (unsigned int index, lnet_process_id_t match_id, __u64 mbits, __u64 ignore_bits) [static]
Definition at line 47 of file lib-ptl.c.
References LASSERT, likely, lnet_t::ln_portals, LNET_NID_ANY, LNET_PID_ANY, lnet_ptl_is_unique(), lnet_ptl_is_wildcard(), lnet_ptl_lock, LNET_PTL_MATCH_UNIQUE, LNET_PTL_MATCH_WILDCARD, lnet_ptl_setopt(), lnet_ptl_unlock, lnet_process_id_t::nid, lnet_process_id_t::pid, the_lnet, and unlikely.
Referenced by lnet_mt_of_attach().
static int lnet_ptl_setup (struct lnet_portal * ptl, int index) [static]
Definition at line 782 of file lib-ptl.c.
References CERROR, cfs_percpt_alloc(), cfs_percpt_for_each, INIT_LIST_HEAD, LIBCFS_CPT_ALLOC, lnet_cpt_table, LNET_MT_EXHAUSTED_BMAP, LNET_MT_HASH_SIZE, lnet_ptl_cleanup(), lnet_match_table::mt_cpt, lnet_match_table::mt_exhausted, lnet_match_table::mt_mhash, lnet_match_table::mt_portal, lnet_portal::ptl_index, lnet_portal::ptl_lock, lnet_portal::ptl_msg_delayed, lnet_portal::ptl_msg_stealing, and lnet_portal::ptl_mtables.
Referenced by lnet_portals_create().
static int lnet_try_match_md (lnet_libmd_t * md, struct lnet_match_info * info, struct lnet_msg * msg) [static]
Definition at line 139 of file lib-ptl.c.
References CDEBUG, CERROR, D_NET, LASSERT, lnet_libhandle::lh_cookie, libcfs_id2str(), LNET_MATCHMD_DROP, LNET_MATCHMD_EXHAUSTED, LNET_MATCHMD_NONE, LNET_MATCHMD_OK, lnet_md_exhausted(), LNET_MD_FLAG_AUTO_UNLINK, LNET_MD_MANAGE_REMOTE, LNET_MD_MAX_SIZE, LNET_MD_OP_PUT, LNET_MD_TRUNCATE, lnet_md_unlink(), lnet_msg_attach_md(), LNET_NID_ANY, LNET_PID_ANY, LPU64, LPX64, lnet_libmd::md_flags, lnet_libmd::md_length, lnet_libmd::md_lh, lnet_libmd::md_max_size, lnet_libmd::md_me, lnet_libmd::md_niov, lnet_libmd::md_offset, lnet_libmd::md_options, lnet_me::me_ignore_bits, lnet_me::me_match_bits, lnet_me::me_match_id, lnet_match_info::mi_id, lnet_match_info::mi_mbits, lnet_match_info::mi_opc, lnet_match_info::mi_portal, lnet_match_info::mi_rlength, lnet_match_info::mi_roffset, lnet_process_id_t::nid, and lnet_process_id_t::pid.
Referenced by lnet_mt_match_md(), and lnet_ptl_attach_md().
module_param (portal_rotor , int , 0644)
MODULE_PARM_DESC (portal_rotor , "redirect PUTs to different cpu-partitions")
Variable Documentation
int portal_rotor = LNET_PTL_ROTOR_HASH_RT
Definition at line 42 of file lib-ptl.c.
Referenced by __proc_lnet_portal_rotor(), and lnet_mt_of_match().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.