Lustre: lnet/include/lnet/lib-lnet.h File Reference
lnet/include/lnet/lib-lnet.h File Reference
#include <libcfs/libcfs.h>
#include <lnet/api.h>
#include <lnet/lnet.h>
#include <lnet/lib-types.h>
Data Structures
struct libcfs_ioctl_handler
Defines
#define LNET_CPT_MAX_BITS 8
#define LNET_CPT_MAX (1 << LNET_CPT_MAX_BITS)
#define LNET_CPT_NUMBER (the_lnet.ln_cpt_number)
#define LNET_CPT_BITS (the_lnet.ln_cpt_bits)
#define LNET_CPT_MASK ((1ULL << LNET_CPT_BITS) - 1)
#define LNET_LOCK_EX CFS_PERCPT_LOCK_EX
exclusive lock
#define lnet_cpt_table() (the_lnet.ln_cpt_table)
#define lnet_cpt_current() cfs_cpt_current(the_lnet.ln_cpt_table, 1)
#define LNET_LOCK() lnet_net_lock(LNET_LOCK_EX)
#define LNET_UNLOCK() lnet_net_unlock(LNET_LOCK_EX)
#define lnet_ptl_lock(ptl) spin_lock(&(ptl)->ptl_lock)
#define lnet_ptl_unlock(ptl) spin_unlock(&(ptl)->ptl_lock)
#define lnet_eq_wait_lock() spin_lock(&the_lnet.ln_eq_wait_lock)
#define lnet_eq_wait_unlock() spin_unlock(&the_lnet.ln_eq_wait_lock)
#define lnet_ni_lock(ni) spin_lock(&(ni)->ni_lock)
#define lnet_ni_unlock(ni) spin_unlock(&(ni)->ni_lock)
#define MAX_PORTALS 64
#define DECLARE_IOCTL_HANDLER(ident, func)
Functions
static int lnet_is_route_alive (lnet_route_t *route)
static int lnet_is_wire_handle_none (lnet_handle_wire_t *wh)
static int lnet_md_exhausted (lnet_libmd_t *md)
static int lnet_md_unlinkable (lnet_libmd_t *md)
static int lnet_cpt_of_cookie (__u64 cookie)
static void lnet_res_lock (int cpt)
static void lnet_res_unlock (int cpt)
static int lnet_res_lock_current (void)
static void lnet_net_lock (int cpt)
static void lnet_net_unlock (int cpt)
static int lnet_net_lock_current (void)
static lnet_eq_t * lnet_eq_alloc (void)
static void lnet_eq_free (lnet_eq_t *eq)
static lnet_libmd_t * lnet_md_alloc (lnet_md_t *umd)
static void lnet_md_free (lnet_libmd_t *md)
static lnet_me_t * lnet_me_alloc (void)
static void lnet_me_free (lnet_me_t *me)
static lnet_msg_t * lnet_msg_alloc (void)
static void lnet_msg_free (lnet_msg_t *msg)
lnet_libhandle_t * lnet_res_lh_lookup (struct lnet_res_container *rec, __u64 cookie)
void lnet_res_lh_initialize (struct lnet_res_container *rec, lnet_libhandle_t *lh)
static void lnet_res_lh_invalidate (lnet_libhandle_t *lh)
static void lnet_eq2handle (lnet_handle_eq_t *handle, lnet_eq_t *eq)
static lnet_eq_t * lnet_handle2eq (lnet_handle_eq_t *handle)
static void lnet_md2handle (lnet_handle_md_t *handle, lnet_libmd_t *md)
static lnet_libmd_t * lnet_handle2md (lnet_handle_md_t *handle)
static lnet_libmd_t * lnet_wire_handle2md (lnet_handle_wire_t *wh)
static void lnet_me2handle (lnet_handle_me_t *handle, lnet_me_t *me)
static lnet_me_t * lnet_handle2me (lnet_handle_me_t *handle)
static void lnet_peer_addref_locked (lnet_peer_t *lp)
void lnet_destroy_peer_locked (lnet_peer_t *lp)
static void lnet_peer_decref_locked (lnet_peer_t *lp)
static int lnet_isrouter (lnet_peer_t *lp)
static void lnet_ni_addref_locked (lnet_ni_t *ni, int cpt)
static void lnet_ni_addref (lnet_ni_t *ni)
static void lnet_ni_decref_locked (lnet_ni_t *ni, int cpt)
static void lnet_ni_decref (lnet_ni_t *ni)
void lnet_ni_free (lnet_ni_t *ni)
lnet_ni_t * lnet_ni_alloc (__u32 net, struct cfs_expr_list *el, struct list_head *nilist)
static int lnet_nid2peerhash (lnet_nid_t nid)
static struct list_head * lnet_net2rnethash (__u32 net)
int lnet_cpt_of_nid_locked (lnet_nid_t nid)
int lnet_cpt_of_nid (lnet_nid_t nid)
lnet_ni_t * lnet_nid2ni_locked (lnet_nid_t nid, int cpt)
lnet_ni_t * lnet_net2ni_locked (__u32 net, int cpt)
lnet_ni_t * lnet_net2ni (__u32 net)
int lnet_lib_init (void)
Initialize LNet library.
void lnet_lib_exit (void)
Finalize LNet library.
int lnet_notify (lnet_ni_t *ni, lnet_nid_t peer, int alive, cfs_time_t when)
void lnet_notify_locked (lnet_peer_t *lp, int notifylnd, int alive, cfs_time_t when)
int lnet_add_route (__u32 net, __u32 hops, lnet_nid_t gateway_nid, unsigned int priority)
int lnet_check_routes (void)
int lnet_del_route (__u32 net, lnet_nid_t gw_nid)
void lnet_destroy_routes (void)
int lnet_get_route (int idx, __u32 *net, __u32 *hops, lnet_nid_t *gateway, __u32 *alive, __u32 *priority)
int lnet_get_rtr_pool_cfg (int idx, struct lnet_ioctl_pool_cfg *pool_cfg)
int libcfs_register_ioctl (struct libcfs_ioctl_handler *hand)
int libcfs_deregister_ioctl (struct libcfs_ioctl_handler *hand)
int libcfs_ioctl_getdata (struct libcfs_ioctl_hdr **hdr_pp, struct libcfs_ioctl_hdr __user *uparam)
void lnet_proc_init (void)
void lnet_proc_fini (void)
int lnet_rtrpools_alloc (int im_a_router)
void lnet_destroy_rtrbuf (lnet_rtrbuf_t *rb, int npages)
int lnet_rtrpools_adjust (int tiny, int small, int large)
int lnet_rtrpools_enable (void)
void lnet_rtrpools_disable (void)
void lnet_rtrpools_free (int keep_pools)
lnet_remotenet_t * lnet_find_net_locked (__u32 net)
int lnet_dyn_add_ni (lnet_pid_t requested_pid, struct lnet_ioctl_config_data *conf)
int lnet_dyn_del_ni (__u32 net)
int lnet_clear_lazy_portal (struct lnet_ni *ni, int portal, char *reason)
int lnet_islocalnid (lnet_nid_t nid)
int lnet_islocalnet (__u32 net)
void lnet_msg_attach_md (lnet_msg_t *msg, lnet_libmd_t *md, unsigned int offset, unsigned int mlen)
void lnet_msg_detach_md (lnet_msg_t *msg, int status)
void lnet_build_unlink_event (lnet_libmd_t *md, lnet_event_t *ev)
void lnet_build_msg_event (lnet_msg_t *msg, lnet_event_kind_t ev_type)
void lnet_msg_commit (lnet_msg_t *msg, int cpt)
void lnet_msg_decommit (lnet_msg_t *msg, int cpt, int status)
void lnet_eq_enqueue_event (lnet_eq_t *eq, lnet_event_t *ev)
void lnet_prep_send (lnet_msg_t *msg, int type, lnet_process_id_t target, unsigned int offset, unsigned int len)
int lnet_send (lnet_nid_t nid, lnet_msg_t *msg, lnet_nid_t rtr_nid)
void lnet_return_tx_credits_locked (lnet_msg_t *msg)
void lnet_return_rx_credits_locked (lnet_msg_t *msg)
void lnet_schedule_blocked_locked (lnet_rtrbufpool_t *rbp)
void lnet_drop_routed_msgs_locked (struct list_head *list, int cpt)
static int lnet_ptl_is_lazy (lnet_portal_t *ptl)
static int lnet_ptl_is_unique (lnet_portal_t *ptl)
static int lnet_ptl_is_wildcard (lnet_portal_t *ptl)
static void lnet_ptl_setopt (lnet_portal_t *ptl, int opt)
static void lnet_ptl_unsetopt (lnet_portal_t *ptl, int opt)
struct list_head * lnet_mt_match_head (struct lnet_match_table *mtable, lnet_process_id_t id, __u64 mbits)
struct lnet_match_table * lnet_mt_of_attach (unsigned int index, lnet_process_id_t id, __u64 mbits, __u64 ignore_bits, lnet_ins_pos_t pos)
int lnet_mt_match_md (struct lnet_match_table *mtable, struct lnet_match_info *info, struct lnet_msg *msg)
void lnet_ptl_attach_md (lnet_me_t *me, lnet_libmd_t *md, struct list_head *matches, struct list_head *drops)
void lnet_ptl_detach_md (lnet_me_t *me, lnet_libmd_t *md)
int lnet_ptl_match_md (struct lnet_match_info *info, struct lnet_msg *msg)
int lnet_portals_create (void)
void lnet_portals_destroy (void)
int lnet_parse (lnet_ni_t *ni, lnet_hdr_t *hdr, lnet_nid_t fromnid, void *private, int rdma_req)
int lnet_parse_local (lnet_ni_t *ni, lnet_msg_t *msg)
int lnet_parse_forward_locked (lnet_ni_t *ni, lnet_msg_t *msg)
void lnet_recv (lnet_ni_t *ni, void *private, lnet_msg_t *msg, int delayed, unsigned int offset, unsigned int mlen, unsigned int rlen)
void lnet_ni_recv (lnet_ni_t *ni, void *private, lnet_msg_t *msg, int delayed, unsigned int offset, unsigned int mlen, unsigned int rlen)
lnet_msg_t * lnet_create_reply_msg (lnet_ni_t *ni, lnet_msg_t *get_msg)
void lnet_set_reply_msg_len (lnet_ni_t *ni, lnet_msg_t *msg, unsigned int len)
void lnet_finalize (lnet_ni_t *ni, lnet_msg_t *msg, int rc)
void lnet_drop_message (lnet_ni_t *ni, int cpt, void *private, unsigned int nob)
void lnet_drop_delayed_msg_list (struct list_head *head, char *reason)
void lnet_recv_delayed_msg_list (struct list_head *head)
int lnet_msg_container_setup (struct lnet_msg_container *container, int cpt)
void lnet_msg_container_cleanup (struct lnet_msg_container *container)
void lnet_msg_containers_destroy (void)
int lnet_msg_containers_create (void)
char * lnet_msgtyp2str (int type)
void lnet_print_hdr (lnet_hdr_t *hdr)
int lnet_fail_nid (lnet_nid_t nid, unsigned int threshold)
int lnet_fault_ctl (int cmd, struct libcfs_ioctl_data *data)
int lnet_fault_init (void)
void lnet_fault_fini (void)
bool lnet_drop_rule_match (lnet_hdr_t *hdr)
Check if message from src to dst can match any existed drop rule.
int lnet_delay_rule_add (struct lnet_fault_attr *attr)
Add a new delay rule to LNet There is no check for duplicated delay rule, all rules will be checked for incoming message.
int lnet_delay_rule_del (lnet_nid_t src, lnet_nid_t dst, bool shutdown)
Remove matched Delay Rules from lnet, if shutdown is true or both src and dst are zero, all rules will be removed, otherwise only matched rules will be removed.
int lnet_delay_rule_list (int pos, struct lnet_fault_attr *attr, struct lnet_fault_stat *stat)
List Delay Rule at position of pos.
void lnet_delay_rule_reset (void)
reset counters for all Delay Rules
void lnet_delay_rule_check (void)
Process delayed messages for scheduled rules This function can either be called by delay_rule_daemon, or by lnet_finalise.
bool lnet_delay_rule_match_locked (lnet_hdr_t *hdr, struct lnet_msg *msg)
check if msg can match any Delay Rule, receiving of this message will be delayed if there is a match.
void lnet_counters_get (lnet_counters_t *counters)
void lnet_counters_reset (void)
unsigned int lnet_iov_nob (unsigned int niov, struct kvec *iov)
int lnet_extract_iov (int dst_niov, struct kvec *dst, int src_niov, struct kvec *src, unsigned int offset, unsigned int len)
unsigned int lnet_kiov_nob (unsigned int niov, lnet_kiov_t *iov)
int lnet_extract_kiov (int dst_niov, lnet_kiov_t *dst, int src_niov, lnet_kiov_t *src, unsigned int offset, unsigned int len)
void lnet_copy_iov2iov (unsigned int ndiov, struct kvec *diov, unsigned int doffset, unsigned int nsiov, struct kvec *siov, unsigned int soffset, unsigned int nob)
void lnet_copy_kiov2iov (unsigned int niov, struct kvec *iov, unsigned int iovoffset, unsigned int nkiov, lnet_kiov_t *kiov, unsigned int kiovoffset, unsigned int nob)
void lnet_copy_iov2kiov (unsigned int nkiov, lnet_kiov_t *kiov, unsigned int kiovoffset, unsigned int niov, struct kvec *iov, unsigned int iovoffset, unsigned int nob)
void lnet_copy_kiov2kiov (unsigned int ndkiov, lnet_kiov_t *dkiov, unsigned int doffset, unsigned int nskiov, lnet_kiov_t *skiov, unsigned int soffset, unsigned int nob)
static void lnet_copy_iov2flat (int dlen, void *dest, unsigned int doffset, unsigned int nsiov, struct kvec *siov, unsigned int soffset, unsigned int nob)
static void lnet_copy_kiov2flat (int dlen, void *dest, unsigned int doffset, unsigned int nsiov, lnet_kiov_t *skiov, unsigned int soffset, unsigned int nob)
static void lnet_copy_flat2iov (unsigned int ndiov, struct kvec *diov, unsigned int doffset, int slen, void *src, unsigned int soffset, unsigned int nob)
static void lnet_copy_flat2kiov (unsigned int ndiov, lnet_kiov_t *dkiov, unsigned int doffset, int slen, void *src, unsigned int soffset, unsigned int nob)
void lnet_me_unlink (lnet_me_t *me)
void lnet_md_unlink (lnet_libmd_t *md)
void lnet_md_deconstruct (lnet_libmd_t *lmd, lnet_md_t *umd)
void lnet_register_lnd (lnd_t *lnd)
void lnet_unregister_lnd (lnd_t *lnd)
int lnet_connect (struct socket **sockp, lnet_nid_t peer_nid, __u32 local_ip, __u32 peer_ip, int peer_port)
void lnet_connect_console_error (int rc, lnet_nid_t peer_nid, __u32 peer_ip, int port)
int lnet_count_acceptor_nis (void)
int lnet_acceptor_timeout (void)
int lnet_acceptor_port (void)
int lnet_acceptor_start (void)
void lnet_acceptor_stop (void)
int lnet_ipif_query (char *name, int *up, __u32 *ip, __u32 *mask)
int lnet_ipif_enumerate (char ***names)
void lnet_ipif_free_enumeration (char **names, int n)
int lnet_sock_setbuf (struct socket *socket, int txbufsize, int rxbufsize)
int lnet_sock_getbuf (struct socket *socket, int *txbufsize, int *rxbufsize)
int lnet_sock_getaddr (struct socket *socket, bool remote, __u32 *ip, int *port)
int lnet_sock_write (struct socket *sock, void *buffer, int nob, int timeout)
int lnet_sock_read (struct socket *sock, void *buffer, int nob, int timeout)
int lnet_sock_listen (struct socket **sockp, __u32 ip, int port, int backlog)
int lnet_sock_accept (struct socket **newsockp, struct socket *sock)
int lnet_sock_connect (struct socket **sockp, int *fatal, __u32 local_ip, int local_port, __u32 peer_ip, int peer_port)
int lnet_peers_start_down (void)
int lnet_peer_buffer_credits (lnet_ni_t *ni)
int lnet_router_checker_start (void)
void lnet_router_checker_stop (void)
void lnet_router_ni_update_locked (lnet_peer_t *gw, __u32 net)
void lnet_swap_pinginfo (lnet_ping_info_t *info)
int lnet_parse_ip2nets (char **networksp, char *ip2nets)
int lnet_parse_routes (char *route_str, int *im_a_router)
int lnet_parse_networks (struct list_head *nilist, char *networks)
int lnet_net_unique (__u32 net, struct list_head *nilist)
int lnet_nid2peer_locked (lnet_peer_t **lpp, lnet_nid_t nid, int cpt)
lnet_peer_t * lnet_find_peer_locked (struct lnet_peer_table *ptable, lnet_nid_t nid)
void lnet_peer_tables_cleanup (lnet_ni_t *ni)
void lnet_peer_tables_destroy (void)
int lnet_peer_tables_create (void)
void lnet_debug_peer (lnet_nid_t nid)
int lnet_get_peer_info (__u32 peer_index, __u64 *nid, char alivness[LNET_MAX_STR_LEN], __u32 *cpt_iter, __u32 *refcount, __u32 *ni_peer_tx_credits, __u32 *peer_tx_credits, __u32 *peer_rtr_credits, __u32 *peer_min_rtr_credtis, __u32 *peer_tx_qnob)
static void lnet_peer_set_alive (lnet_peer_t *lp)
Variables
lnet_t the_lnet
lnd_t the_lolnd
int avoid_asym_router_failure
int portal_rotor
Define Documentation
#define DECLARE_IOCTL_HANDLER (ident, func)
Value:
static struct libcfs_ioctl_handler ident = {            \
                /* .item = */ LIST_HEAD_INIT(ident.item),       \
                /* .handle_ioctl = */ func                      \
        }
Definition at line 479 of file lib-lnet.h.
#define LNET_CPT_BITS (the_lnet.ln_cpt_bits)
Definition at line 71 of file lib-lnet.h.
Referenced by lnet_nid_cpt_hash(), lnet_res_lh_initialize(), and lnet_res_lh_lookup().
#define lnet_cpt_current () cfs_cpt_current(the_lnet.ln_cpt_table, 1)
Definition at line 119 of file lib-lnet.h.
Referenced by lnet_mt_of_attach(), lnet_mt_of_match(), lnet_net_lock_current(), and lnet_res_lock_current().
#define LNET_CPT_MASK ((1ULL << LNET_CPT_BITS) - 1)
Definition at line 72 of file lib-lnet.h.
Referenced by lnet_cpt_of_cookie().
#define LNET_CPT_MAX (1 << LNET_CPT_MAX_BITS)
Definition at line 68 of file lib-lnet.h.
Referenced by lnet_lib_init().
#define LNET_CPT_MAX_BITS 8
Definition at line 64 of file lib-lnet.h.
#define LNET_CPT_NUMBER (the_lnet.ln_cpt_number)
Definition at line 70 of file lib-lnet.h.
Referenced by __proc_lnet_buffers(), lnet_cpt_of_cookie(), lnet_cpt_of_nid(), lnet_cpt_of_nid_locked(), lnet_match2mt(), lnet_mt_of_attach(), lnet_mt_of_match(), lnet_ni_addref_locked(), lnet_ni_alloc(), lnet_ni_decref_locked(), lnet_nid_cpt_hash(), lnet_nrb_large_calculate(), lnet_nrb_small_calculate(), lnet_nrb_tiny_calculate(), lnet_parse_networks(), lnet_portals_create(), lnet_ptl_disable_mt(), lnet_ptl_match_delay(), lnet_ptl_match_md(), lnet_startup_lndni(), proc_lnet_nis(), and proc_lnet_peers().
#define lnet_cpt_table () (the_lnet.ln_cpt_table)
Definition at line 118 of file lib-lnet.h.
Referenced by kiblnd_alloc_freg_pool(), kiblnd_alloc_pages(), kiblnd_base_startup(), kiblnd_create_conn(), kiblnd_create_fmr_pool(), kiblnd_create_peer(), kiblnd_create_tx_pool(), kiblnd_dev_failover(), kiblnd_get_completion_vector(), kiblnd_net_fini_pools(), kiblnd_net_init_pools(), kiblnd_scheduler(), kiblnd_start_schedulers(), ksocknal_base_startup(), ksocknal_create_peer(), ksocknal_net_start_threads(), ksocknal_scheduler(), ksocknal_start_schedulers(), lnet_create_locks(), lnet_msg_container_setup(), lnet_msg_containers_create(), lnet_new_rtrbuf(), lnet_ni_alloc(), lnet_nid2peer_locked(), lnet_peer_tables_create(), lnet_prepare(), lnet_ptl_setup(), lnet_res_container_setup(), lnet_res_containers_create(), lnet_rtrpools_alloc(), lnet_selftest_exit(), lnet_selftest_init(), LNetEQAlloc(), srpc_alloc_bulk(), and srpc_service_init().
#define lnet_eq_wait_lock () spin_lock(&the_lnet.ln_eq_wait_lock)
Definition at line 178 of file lib-lnet.h.
Referenced by lnet_eq_enqueue_event(), lnet_eq_wait_locked(), LNetEQAlloc(), LNetEQFree(), and LNetEQPoll().
#define lnet_eq_wait_unlock () spin_unlock(&the_lnet.ln_eq_wait_lock)
Definition at line 179 of file lib-lnet.h.
Referenced by lnet_eq_enqueue_event(), lnet_eq_wait_locked(), LNetEQAlloc(), LNetEQFree(), and LNetEQPoll().
#define LNET_LOCK () lnet_net_lock(LNET_LOCK_EX)
Definition at line 173 of file lib-lnet.h.
Referenced by ksocknal_send_hello_v1(), and ksocknal_send_hello_v2().
#define LNET_LOCK_EX CFS_PERCPT_LOCK_EX
exclusive lock
Definition at line 75 of file lib-lnet.h.
Referenced by __proc_lnet_buffers(), lnet_add_route(), lnet_clear_lazy_portal(), lnet_clear_zombies_nis_locked(), lnet_connect(), lnet_counters_get(), lnet_counters_reset(), lnet_del_route(), lnet_delay_rule_add(), lnet_delay_rule_del(), lnet_drop_rule_add(), lnet_drop_rule_del(), lnet_dyn_add_ni(), lnet_get_rtr_pool_cfg(), lnet_net2ni_locked(), lnet_nid2ni_locked(), lnet_nid2peer_locked(), lnet_ping_info_destroy(), lnet_ping_target_update(), lnet_prune_rc_data(), lnet_rtrpools_alloc(), lnet_rtrpools_disable(), lnet_rtrpools_enable(), lnet_shutdown_lndni(), lnet_shutdown_lndnis(), lnet_startup_lndni(), LNetCtl(), LNetEQAlloc(), LNetEQFree(), and LNetSetLazyPortal().
#define lnet_ni_lock (ni) spin_lock(&(ni)->ni_lock)
Definition at line 180 of file lib-lnet.h.
Referenced by lnet_get_net_config(), lnet_parse(), lnet_ping_info_destroy(), lnet_ping_info_install_locked(), lnet_update_ni_status_locked(), and proc_lnet_nis().
#define lnet_ni_unlock (ni) spin_unlock(&(ni)->ni_lock)
Definition at line 181 of file lib-lnet.h.
Referenced by lnet_get_net_config(), lnet_parse(), lnet_ping_info_destroy(), lnet_ping_info_install_locked(), lnet_update_ni_status_locked(), and proc_lnet_nis().
#define lnet_ptl_lock (ptl) spin_lock(&(ptl)->ptl_lock)
Definition at line 176 of file lib-lnet.h.
Referenced by lnet_clear_lazy_portal(), lnet_ptl_attach_md(), lnet_ptl_match_delay(), lnet_ptl_match_early(), lnet_ptl_match_md(), lnet_ptl_match_type(), and LNetSetLazyPortal().
#define lnet_ptl_unlock (ptl) spin_unlock(&(ptl)->ptl_lock)
Definition at line 177 of file lib-lnet.h.
Referenced by lnet_clear_lazy_portal(), lnet_ptl_attach_md(), lnet_ptl_match_delay(), lnet_ptl_match_early(), lnet_ptl_match_md(), lnet_ptl_match_type(), and LNetSetLazyPortal().
#define LNET_UNLOCK () lnet_net_unlock(LNET_LOCK_EX)
Definition at line 174 of file lib-lnet.h.
Referenced by ksocknal_send_hello_v1(), and ksocknal_send_hello_v2().
#define MAX_PORTALS 64
Definition at line 183 of file lib-lnet.h.
Referenced by lnet_portals_create().
Function Documentation
int libcfs_deregister_ioctl (struct libcfs_ioctl_handler * hand)
Definition at line 84 of file module.c.
References libcfs_ioctl_handler::item, list_del_init(), and list_empty().
Referenced by lnet_exit(), and lstcon_console_fini().
int libcfs_ioctl_getdata (struct libcfs_ioctl_hdr ** hdr_pp, struct libcfs_ioctl_hdr __user * uparam)
Definition at line 111 of file linux-module.c.
References CERROR, ENTRY, GOTO, libcfs_ioctl_hdr::ioc_len, libcfs_ioctl_hdr::ioc_version, LIBCFS_ALLOC, LIBCFS_FREE, LIBCFS_IOC_DATA_MAX, LIBCFS_IOCTL_VERSION, LIBCFS_IOCTL_VERSION2, and RETURN.
Referenced by libcfs_ioctl().
int libcfs_register_ioctl (struct libcfs_ioctl_handler * hand)
Definition at line 69 of file module.c.
References libcfs_ioctl_handler::item, list_add_tail(), and list_empty().
Referenced by lnet_init(), and lstcon_console_init().
int lnet_acceptor_port (void)
Definition at line 59 of file acceptor.c.
References accept_port.
Referenced by ksocknal_launch_packet(), and ksocknal_query().
int lnet_acceptor_start (void)
Definition at line 464 of file acceptor.c.
References accept2secure(), accept_type, CERROR, LASSERT, lnet_acceptor(), lnet_acceptor_get_tunables(), lnet_acceptor_state, and lnet_count_acceptor_nis().
Referenced by lnet_dyn_add_ni(), and LNetNIInit().
void lnet_acceptor_stop (void)
Definition at line 513 of file acceptor.c.
References lnet_acceptor_state.
Referenced by lnet_dyn_del_ni(), LNetNIFini(), and LNetNIInit().
int lnet_acceptor_timeout (void)
Definition at line 97 of file acceptor.c.
References accept_timeout.
Referenced by ksocknal_recv_hello(), ksocknal_send_hello_v1(), and ksocknal_send_hello_v2().
int lnet_add_route (__u32 net, __u32 hops, lnet_nid_t gateway_nid, unsigned int priority)
Definition at line 296 of file router.c.
References CDEBUG, CERROR, D_NET, INIT_LIST_HEAD, LASSERT, LIBCFS_ALLOC, LIBCFS_FREE, libcfs_net2str(), libcfs_nid2str(), list_add_tail(), list_entry, list_for_each, lnet_t::ln_rc_waitq, lnet_t::ln_shutdown, lnet_lnd::lnd_notify, lnet_add_route_to_rnet(), lnet_find_net_locked(), lnet_islocalnet(), LNET_LOCK_EX, lnet_net2rnethash(), lnet_net_lock(), lnet_net_unlock(), LNET_NETTYP(), lnet_nid2peer_locked(), LNET_NID_ANY, LNET_NIDNET(), lnet_peer_addref_locked(), lnet_peer_decref_locked(), LNET_UNDEFINED_HOPS, LOLND, lnet_peer::lp_ni, lnet_peer::lp_nid, lnet_route_t::lr_gateway, lnet_route_t::lr_hops, lnet_route_t::lr_net, lnet_route_t::lr_priority, lnet_remotenet_t::lrn_list, lnet_remotenet_t::lrn_net, lnet_remotenet_t::lrn_routes, lnet_ni::ni_lnd, and the_lnet.
Referenced by lnet_parse_route(), and LNetCtl().
void lnet_build_msg_event (lnet_msg_t * msg, lnet_event_kind_t ev_type)
Definition at line 64 of file lib-msg.c.
References lnet_event_t::hdr_data, lnet_event_t::initiator, LASSERT, LBUG, le32_to_cpu, le64_to_cpu, lnet_t::ln_pid, LNET_EVENT_ACK, LNET_EVENT_GET, LNET_EVENT_PUT, LNET_EVENT_REPLY, LNET_EVENT_SEND, LNET_MSG_GET, LNET_MSG_PUT, LNET_NID_ANY, lnet_event_t::match_bits, lnet_event_t::mlength, lnet_msg::msg_ev, lnet_msg::msg_from, lnet_msg::msg_hdr, lnet_msg::msg_offset, lnet_msg::msg_routing, lnet_msg::msg_type, lnet_msg::msg_wanted, lnet_process_id_t::nid, lnet_event_t::offset, lnet_process_id_t::pid, lnet_event_t::pt_index, lnet_event_t::rlength, lnet_event_t::sender, lnet_event_t::target, the_lnet, and lnet_event_t::type.
Referenced by lnet_create_reply_msg(), lnet_parse_ack(), lnet_parse_get(), lnet_parse_reply(), lnet_recv_put(), LNetGet(), and LNetPut().
void lnet_build_unlink_event (lnet_libmd_t * md, lnet_event_t * ev)
Definition at line 46 of file lib-msg.c.
References ENTRY, EXIT, LNET_EVENT_UNLINK, lnet_md2handle(), lnet_md_deconstruct(), lnet_event_t::md, lnet_event_t::md_handle, lnet_event_t::status, lnet_event_t::type, and lnet_event_t::unlinked.
Referenced by LNetMDUnlink(), and LNetMEUnlink().
int lnet_check_routes (void)
Definition at line 415 of file router.c.
References CERROR, libcfs_net2str(), libcfs_nid2str(), list_entry, list_for_each, lnet_t::ln_remote_nets_hash, lnet_net_lock_current(), lnet_net_unlock(), LNET_REMOTE_NETS_HASH_SIZE, lnet_peer::lp_ni, lnet_peer::lp_nid, lnet_route_t::lr_gateway, lnet_remotenet_t::lrn_net, lnet_remotenet_t::lrn_routes, and the_lnet.
Referenced by LNetCtl(), and LNetNIInit().
int lnet_clear_lazy_portal (struct lnet_ni * ni, int portal, char * reason)
Definition at line 919 of file lib-ptl.c.
References CDEBUG, CWARN, D_NET, list_for_each_entry_safe, LIST_HEAD_INIT, list_move(), list_splice_init(), lnet_t::ln_nportals, lnet_t::ln_portals, lnet_t::ln_shutdown, lnet_drop_delayed_msg_list(), LNET_LOCK_EX, lnet_ptl_is_lazy(), LNET_PTL_LAZY, lnet_ptl_lock, lnet_ptl_unlock, lnet_ptl_unsetopt(), lnet_res_lock(), lnet_res_unlock(), lnet_peer::lp_ni, msg, lnet_msg::msg_list, lnet_msg::msg_rxpeer, lnet_portal::ptl_msg_delayed, and the_lnet.
Referenced by lnet_shutdown_lndni(), and LNetClearLazyPortal().
int lnet_connect (struct socket ** sockp, lnet_nid_t peer_nid, __u32 local_ip, __u32 peer_ip, int peer_port)
Definition at line 159 of file acceptor.c.
References accept_timeout, CLASSERT, fatal(), lnet_t::ln_testprotocompat, lnet_connect_console_error(), LNET_LOCK_EX, lnet_net_lock(), lnet_net_unlock(), LNET_PROTO_ACCEPTOR_MAGIC, LNET_PROTO_ACCEPTOR_VERSION, LNET_PROTO_MAGIC, lnet_sock_connect(), lnet_sock_write(), and the_lnet.
Referenced by ksocknal_connect().
void lnet_connect_console_error (int rc, lnet_nid_t peer_nid, __u32 peer_ip, int port)
Definition at line 104 of file acceptor.c.
References CNETERR, LCONSOLE_ERROR_MSG, and libcfs_nid2str().
Referenced by ksocknal_connect(), and lnet_connect().
static void lnet_copy_flat2iov (unsigned int ndiov, struct kvec * diov, unsigned int doffset, int slen, void * src, unsigned int soffset, unsigned int nob) [inline, static]
Definition at line 678 of file lib-lnet.h.
References lnet_copy_iov2iov().
Referenced by kgnilnd_recv(), and kiblnd_recv().
static void lnet_copy_flat2kiov (unsigned int ndiov, lnet_kiov_t * dkiov, unsigned int doffset, int slen, void * src, unsigned int soffset, unsigned int nob) [inline, static]
Definition at line 688 of file lib-lnet.h.
References lnet_copy_iov2kiov().
Referenced by kgnilnd_recv(), kgnilnd_recv_bte_get(), and kiblnd_recv().
static void lnet_copy_iov2flat (int dlen, void * dest, unsigned int doffset, unsigned int nsiov, struct kvec * siov, unsigned int soffset, unsigned int nob) [inline, static]
Definition at line 656 of file lib-lnet.h.
References lnet_copy_iov2iov().
Referenced by kiblnd_send().
void lnet_copy_iov2iov (unsigned int ndiov, struct kvec * diov, unsigned int doffset, unsigned int nsiov, struct kvec * siov, unsigned int soffset, unsigned int nob)
Definition at line 172 of file lib-move.c.
References LASSERT, and MIN.
Referenced by lnet_copy_flat2iov(), lnet_copy_iov2flat(), and lolnd_recv().
void lnet_copy_iov2kiov (unsigned int nkiov, lnet_kiov_t * kiov, unsigned int kiovoffset, unsigned int niov, struct kvec * iov, unsigned int iovoffset, unsigned int nob)
Definition at line 444 of file lib-move.c.
References lnet_kiov_t::kiov_len, lnet_kiov_t::kiov_offset, lnet_kiov_t::kiov_page, LASSERT, and MIN.
Referenced by lnet_copy_flat2kiov(), and lolnd_recv().
static void lnet_copy_kiov2flat (int dlen, void * dest, unsigned int doffset, unsigned int nsiov, lnet_kiov_t * skiov, unsigned int soffset, unsigned int nob) [inline, static]
Definition at line 667 of file lib-lnet.h.
References lnet_copy_kiov2iov().
Referenced by kiblnd_send().
void lnet_copy_kiov2iov (unsigned int niov, struct kvec * iov, unsigned int iovoffset, unsigned int nkiov, lnet_kiov_t * kiov, unsigned int kiovoffset, unsigned int nob)
Definition at line 374 of file lib-move.c.
References lnet_kiov_t::kiov_len, lnet_kiov_t::kiov_offset, lnet_kiov_t::kiov_page, LASSERT, and MIN.
Referenced by lnet_copy_kiov2flat(), and lolnd_recv().
void lnet_copy_kiov2kiov (unsigned int ndkiov, lnet_kiov_t * dkiov, unsigned int doffset, unsigned int nskiov, lnet_kiov_t * skiov, unsigned int soffset, unsigned int nob)
Definition at line 292 of file lib-move.c.
References lnet_kiov_t::kiov_len, lnet_kiov_t::kiov_offset, lnet_kiov_t::kiov_page, LASSERT, and MIN.
Referenced by _kgnilnd_proc_run_cksum_test(), and lolnd_recv().
int lnet_count_acceptor_nis (void)
Definition at line 820 of file api-ni.c.
References list_entry, list_for_each, lnet_t::ln_nis, lnet_lnd::lnd_accept, lnet_net_lock_current(), lnet_net_unlock(), lnet_ni::ni_list, and lnet_ni::ni_lnd.
Referenced by lnet_acceptor_start(), and lnet_dyn_del_ni().
void lnet_counters_get (lnet_counters_t * counters)
Definition at line 323 of file api-ni.c.
References cfs_percpt_for_each, lnet_counters::drop_count, lnet_counters::drop_length, lnet_counters::errors, lnet_t::ln_counters, LNET_LOCK_EX, lnet_net_lock(), lnet_net_unlock(), lnet_counters::msgs_alloc, lnet_counters::msgs_max, lnet_counters::recv_count, lnet_counters::recv_length, lnet_counters::route_count, lnet_counters::route_length, lnet_counters::send_count, and lnet_counters::send_length.
Referenced by __proc_lnet_stats(), LNetCtl(), and sfw_get_stats().
void lnet_counters_reset (void)
Definition at line 351 of file api-ni.c.
References cfs_percpt_for_each, lnet_t::ln_counters, LNET_LOCK_EX, lnet_net_lock(), and lnet_net_unlock().
Referenced by __proc_lnet_stats().
static int lnet_cpt_of_cookie (__u64 cookie) [inline, static]
Definition at line 122 of file lib-lnet.h.
References LNET_COOKIE_TYPE_BITS, LNET_CPT_MASK, and LNET_CPT_NUMBER.
Referenced by lnet_create_reply_msg(), lnet_finalize(), lnet_handle2md(), lnet_handle2me(), lnet_md_unlink(), lnet_parse_ack(), lnet_parse_reply(), lnet_ptl_attach_md(), lnet_wire_handle2md(), LNetGet(), LNetMDAttach(), LNetMDUnlink(), LNetMEInsert(), LNetMEUnlink(), and LNetPut().
int lnet_cpt_of_nid (lnet_nid_t nid)
Definition at line 748 of file api-ni.c.
References list_empty(), lnet_t::ln_nis_cpt, LNET_CPT_NUMBER, lnet_cpt_of_nid_locked(), lnet_net_lock_current(), lnet_net_unlock(), and lnet_nid_cpt_hash().
Referenced by brw_client_init(), kiblnd_create_conn(), kiblnd_create_peer(), kiblnd_get_idle_tx(), ksocknal_create_conn(), ksocknal_create_peer(), lnet_create_reply_msg(), lnet_debug_peer(), lnet_match2mt(), lnet_mt_of_match(), lnet_notify(), lnet_parse(), lnet_send(), sfw_run_batch(), and srpc_init_client_rpc().
int lnet_cpt_of_nid_locked (lnet_nid_t nid)
Definition at line 724 of file api-ni.c.
References LASSERT, list_empty(), list_for_each_entry, lnet_t::ln_nis_cpt, LNET_CPT_NUMBER, lnet_nid_cpt_hash(), LNET_NIDNET(), lnet_ni::ni_cptlist, lnet_ni::ni_cpts, lnet_ni::ni_ncpts, and lnet_ni::ni_nid.
Referenced by lnet_cpt_of_nid(), lnet_nid2peer_locked(), lnet_router_checker(), and lnet_send().
lnet_msg_t* lnet_create_reply_msg (lnet_ni_t * ni, lnet_msg_t * get_msg)
Definition at line 2254 of file lib-move.c.
References CDEBUG, CERROR, D_NET, lnet_counters::drop_count, lnet_counters::drop_length, LASSERT, lnet_libhandle::lh_cookie, libcfs_id2str(), libcfs_nid2str(), lnet_t::ln_counters, lnet_build_msg_event(), lnet_cpt_of_cookie(), lnet_cpt_of_nid(), LNET_EVENT_REPLY, lnet_msg_alloc(), lnet_msg_attach_md(), lnet_msg_commit(), lnet_msg_free(), LNET_MSG_GET, lnet_net_lock(), lnet_net_unlock(), lnet_res_lock(), lnet_res_unlock(), lnet_libmd::md_length, lnet_libmd::md_lh, lnet_libmd::md_offset, lnet_libmd::md_refcount, lnet_libmd::md_threshold, msg, lnet_msg::msg_from, lnet_msg::msg_hdr, lnet_msg::msg_md, lnet_msg::msg_receiving, lnet_msg::msg_routing, lnet_msg::msg_target, lnet_msg::msg_target_is_router, lnet_msg::msg_type, lnet_ni::ni_nid, lnet_process_id_t::nid, and the_lnet.
Referenced by kgnilnd_send(), and kiblnd_send().
void lnet_debug_peer (lnet_nid_t nid)
Definition at line 362 of file peer.c.
References CDEBUG, D_WARNING, libcfs_nid2str(), lnet_cpt_of_nid(), lnet_isrouter(), lnet_net_lock(), lnet_net_unlock(), lnet_nid2peer_locked(), lnet_peer_aliveness_enabled, lnet_peer_decref_locked(), lnet_peer::lp_alive, lnet_peer::lp_minrtrcredits, lnet_peer::lp_mintxcredits, lnet_peer::lp_ni, lnet_peer::lp_nid, lnet_peer::lp_refcount, lnet_peer::lp_rtrcredits, lnet_peer::lp_txcredits, lnet_peer::lp_txqnob, and lnet_ni::ni_peertxcredits.
Referenced by LNetDebugPeer().
int lnet_del_route (__u32 net, lnet_nid_t gw_nid)
Definition at line 472 of file router.c.
References CDEBUG, D_NET, LIBCFS_FREE, libcfs_net2str(), libcfs_nid2str(), list_del(), list_empty(), list_entry, list_for_each, lnet_t::ln_remote_nets_hash, lnet_t::ln_remote_nets_version, LNET_LOCK_EX, lnet_net2rnethash(), lnet_net_lock(), lnet_net_unlock(), LNET_NID_ANY, LNET_NIDNET(), lnet_peer_decref_locked(), LNET_REMOTE_NETS_HASH_SIZE, lnet_rtr_decref_locked(), lnet_peer::lp_nid, lnet_route_t::lr_gateway, lnet_route_t::lr_gwlist, lnet_route_t::lr_list, lnet_remotenet_t::lrn_list, lnet_remotenet_t::lrn_net, lnet_remotenet_t::lrn_routes, and the_lnet.
Referenced by lnet_destroy_routes(), lnet_peer_table_del_rtrs_locked(), and LNetCtl().
int lnet_delay_rule_add (struct lnet_fault_attr * attr)
Add a new delay rule to LNet There is no check for duplicated delay rule, all rules will be checked for incoming message.
Definition at line 730 of file net_fault.c.
References CDEBUG, CFS_ALLOC_PTR, CFS_FREE_PTR, cfs_rand(), cfs_time_shift(), D_NET, delay_daemon_data::dd_ctl_waitq, delay_daemon_data::dd_mutex, delay_daemon_data::dd_running, lnet_fault_attr::delay, delay_dd, delay_timer_cb(), lnet_delay_rule::dl_attr, lnet_delay_rule::dl_delay_at, lnet_delay_rule::dl_delay_time, lnet_delay_rule::dl_link, lnet_delay_rule::dl_lock, lnet_delay_rule::dl_msg_list, lnet_delay_rule::dl_msg_send, lnet_delay_rule::dl_refcount, lnet_delay_rule::dl_sched_link, lnet_delay_rule::dl_time_base, lnet_delay_rule::dl_timer, ENTRY, lnet_fault_attr::fa_src, GOTO, INIT_LIST_HEAD, libcfs_nid2str(), list_add(), lnet_t::ln_delay_rules, lnet_delay_rule_daemon(), lnet_fault_attr_validate(), LNET_LOCK_EX, lnet_net_lock(), lnet_net_unlock(), RETURN, the_lnet, and lnet_fault_attr::u.
Referenced by lnet_fault_ctl().
void lnet_delay_rule_check (void)
Process delayed messages for scheduled rules This function can either be called by delay_rule_daemon, or by lnet_finalise.
Definition at line 659 of file net_fault.c.
References delay_daemon_data::dd_lock, delay_daemon_data::dd_sched_rules, delay_dd, delay_rule_decref(), delayed_msg_check(), delayed_msg_process(), lnet_delay_rule::dl_sched_link, INIT_LIST_HEAD, list_del_init(), list_empty(), list_entry, and list_head::next.
Referenced by lnet_delay_rule_daemon(), and lnet_finalize().
int lnet_delay_rule_del (lnet_nid_t src, lnet_nid_t dst, bool shutdown)
Remove matched Delay Rules from lnet, if shutdown is true or both src and dst are zero, all rules will be removed, otherwise only matched rules will be removed.
If src is zero, then all rules have dst as destination will be remove If dst is zero, then all rules have src as source will be removed
When a delay rule is removed, all delayed messages of this rule will be processed immediately.
Definition at line 823 of file net_fault.c.
References CDEBUG, cleanup(), D_NET, delay_daemon_data::dd_ctl_waitq, delay_daemon_data::dd_mutex, delay_daemon_data::dd_running, delay_daemon_data::dd_stopped, delay_daemon_data::dd_waitq, lnet_fault_attr::delay, delay_dd, delay_rule_decref(), delayed_msg_check(), delayed_msg_process(), lnet_delay_rule::dl_attr, lnet_delay_rule::dl_link, lnet_delay_rule::dl_timer, ENTRY, lnet_fault_attr::fa_dst, lnet_fault_attr::fa_src, INIT_LIST_HEAD, LASSERT, libcfs_nid2str(), list_del_init(), list_empty(), list_for_each_entry_safe, list_move(), lnet_t::ln_delay_rules, LNET_LOCK_EX, lnet_net_lock(), lnet_net_unlock(), RETURN, the_lnet, and lnet_fault_attr::u.
Referenced by lnet_fault_ctl(), and lnet_fault_fini().
int lnet_delay_rule_list (int pos, struct lnet_fault_attr * attr, struct lnet_fault_stat * stat)
List Delay Rule at position of pos.
Definition at line 892 of file net_fault.c.
References lnet_delay_rule::dl_attr, lnet_delay_rule::dl_link, lnet_delay_rule::dl_lock, lnet_delay_rule::dl_stat, ENTRY, list_for_each_entry, lnet_t::ln_delay_rules, lnet_net_lock_current(), lnet_net_unlock(), RETURN, and the_lnet.
Referenced by lnet_fault_ctl().
bool lnet_delay_rule_match_locked (lnet_hdr_t * hdr, struct lnet_msg * msg)
check if msg can match any Delay Rule, receiving of this message will be delayed if there is a match.
Definition at line 547 of file net_fault.c.
References delay_rule_match(), lnet_delay_rule::dl_link, le32_to_cpu, le64_to_cpu, list_for_each_entry, lnet_t::ln_delay_rules, LNET_MSG_GET, LNET_MSG_PUT, and the_lnet.
Referenced by lnet_parse().
void lnet_delay_rule_reset (void)
reset counters for all Delay Rules
Definition at line 922 of file net_fault.c.
References cfs_rand(), cfs_time_shift(), lnet_fault_attr::delay, lnet_delay_rule::dl_attr, lnet_delay_rule::dl_delay_at, lnet_delay_rule::dl_delay_time, lnet_delay_rule::dl_link, lnet_delay_rule::dl_lock, lnet_delay_rule::dl_stat, lnet_delay_rule::dl_time_base, ENTRY, EXIT, lnet_fault_attr::la_interval, list_for_each_entry, lnet_t::ln_delay_rules, lnet_net_lock_current(), lnet_net_unlock(), the_lnet, and lnet_fault_attr::u.
Referenced by lnet_fault_ctl().
void lnet_destroy_peer_locked (lnet_peer_t * lp)
Definition at line 217 of file peer.c.
References LASSERT, list_add(), list_empty(), lnet_t::ln_peer_tables, lnet_ni_decref_locked(), lnet_peer::lp_cpt, lnet_peer::lp_hashlist, lnet_peer::lp_ni, lnet_peer::lp_refcount, lnet_peer::lp_rtr_refcount, lnet_peer::lp_txq, lnet_peer::lp_txqnob, lnet_peer_table::pt_deathrow, lnet_peer_table::pt_number, lnet_peer_table::pt_zombies, and the_lnet.
Referenced by lnet_peer_decref_locked().
void lnet_destroy_routes (void)
Definition at line 547 of file router.c.
References lnet_del_route(), LNET_NID_ANY, and LNET_NIDNET().
Referenced by LNetNIFini(), and LNetNIInit().
void lnet_destroy_rtrbuf (lnet_rtrbuf_t * rb, int npages)
Definition at line 1299 of file router.c.
References lnet_kiov_t::kiov_page, LIBCFS_FREE, offsetof, and lnet_rtrbuf_t::rb_kiov.
Referenced by lnet_return_rx_credits_locked(), lnet_rtrpool_adjust_bufs(), and lnet_rtrpool_free_bufs().
void lnet_drop_delayed_msg_list (struct list_head * head, char * reason)
Definition at line 2051 of file lib-move.c.
References CWARN, LASSERT, libcfs_id2str(), list_del(), list_empty(), list_entry, lnet_drop_message(), lnet_finalize(), LNET_MSG_PUT, lnet_peer::lp_cpt, lnet_peer::lp_ni, LPU64, msg, lnet_msg::msg_hdr, lnet_msg::msg_len, lnet_msg::msg_list, lnet_msg::msg_md, lnet_msg::msg_private, lnet_msg::msg_rx_delayed, lnet_msg::msg_rxpeer, and list_head::next.
Referenced by lnet_clear_lazy_portal(), and LNetMDAttach().
void lnet_drop_message (lnet_ni_t * ni, int cpt, void * private, unsigned int nob)
Definition at line 1409 of file lib-move.c.
References lnet_counters::drop_count, lnet_counters::drop_length, lnet_t::ln_counters, lnet_net_lock(), lnet_net_unlock(), lnet_ni_recv(), and the_lnet.
Referenced by delayed_msg_process(), lnet_drop_delayed_msg_list(), and lnet_parse().
void lnet_drop_routed_msgs_locked (struct list_head * list, int cpt)
Definition at line 1039 of file lib-move.c.
References INIT_LIST_HEAD, list_del_init(), list_for_each_entry_safe, list_splice_init(), lnet_finalize(), lnet_net_lock(), lnet_net_unlock(), lnet_ni_recv(), lnet_peer::lp_ni, msg, lnet_msg::msg_hdr, lnet_msg::msg_list, lnet_msg::msg_private, and lnet_msg::msg_rxpeer.
Referenced by lnet_return_rx_credits_locked(), and lnet_rtrpool_free_bufs().
bool lnet_drop_rule_match (lnet_hdr_t * hdr)
Check if message from src to dst can match any existed drop rule.
Definition at line 363 of file net_fault.c.
References lnet_drop_rule::dr_link, drop_rule_match(), le32_to_cpu, le64_to_cpu, list_for_each_entry, lnet_t::ln_drop_rules, LNET_MSG_GET, LNET_MSG_PUT, lnet_net_lock_current(), lnet_net_unlock(), and the_lnet.
Referenced by lnet_parse().
int lnet_dyn_add_ni (lnet_pid_t requested_pid, struct lnet_ioctl_config_data * conf)
Definition at line 1782 of file api-ni.c.
References CERROR, lnet_ioctl_config_data::cfg_config_u, lnet_ioctl_config_data::cfg_net, INIT_LIST_HEAD, list_del_init(), list_empty(), list_entry, lnet_t::ln_api_mutex, lnet_lnd::lnd_accept, lnet_acceptor_start(), lnet_find_net_locked(), lnet_get_ni_count(), LNET_LOCK_EX, lnet_net_lock(), lnet_net_unlock(), lnet_ni_free(), LNET_NIDNET(), lnet_parse_networks(), lnet_ping_info_free(), lnet_ping_info_setup(), lnet_ping_md_unlink(), lnet_ping_target_update(), lnet_shutdown_lndni(), lnet_startup_lndni(), list_head::next, lnet_ni::ni_list, lnet_ni::ni_lnd, and lnet_ni::ni_nid.
Referenced by lnet_dyn_configure().
int lnet_dyn_del_ni (__u32 net)
Definition at line 1860 of file api-ni.c.
References lnet_t::ln_api_mutex, lnet_acceptor_stop(), lnet_count_acceptor_nis(), lnet_get_ni_count(), lnet_net2ni(), LNET_NETTYP(), lnet_ni_decref_locked(), lnet_ping_info_free(), lnet_ping_info_setup(), lnet_ping_md_unlink(), lnet_ping_target_update(), lnet_shutdown_lndni(), and LOLND.
Referenced by lnet_dyn_unconfigure().
static void lnet_eq2handle (lnet_handle_eq_t * handle, lnet_eq_t * eq) [inline, static]
Definition at line 287 of file lib-lnet.h.
References lnet_handle_any_t::cookie, lnet_eq::eq_lh, lnet_libhandle::lh_cookie, and LNetInvalidateHandle().
Referenced by lnet_md_deconstruct(), and LNetEQAlloc().
static lnet_eq_t* lnet_eq_alloc (void) [inline, static]
Definition at line 186 of file lib-lnet.h.
References LIBCFS_ALLOC.
Referenced by LNetEQAlloc().
void lnet_eq_enqueue_event (lnet_eq_t * eq, lnet_event_t * ev)
Definition at line 212 of file lib-eq.c.
References lnet_eq::eq_callback, lnet_eq::eq_enq_seq, lnet_eq::eq_events, lnet_eq::eq_size, LASSERT, lnet_t::ln_eq_waitq, LNET_EQ_HANDLER_NONE, lnet_eq_wait_lock, lnet_eq_wait_unlock, lnet_event_t::sequence, and the_lnet.
Referenced by lnet_msg_detach_md(), LNetMDUnlink(), and LNetMEUnlink().
static void lnet_eq_free (lnet_eq_t * eq) [inline, static]
Definition at line 195 of file lib-lnet.h.
References LIBCFS_FREE.
Referenced by lnet_res_container_cleanup(), LNetEQAlloc(), and LNetEQFree().
int lnet_extract_iov (int dst_niov, struct kvec * dst, int src_niov, struct kvec * src, unsigned int offset, unsigned int len)
Definition at line 231 of file lib-move.c.
References LASSERT.
Referenced by ksocknal_recv(), and ksocknal_send().
int lnet_extract_kiov (int dst_niov, lnet_kiov_t * dst, int src_niov, lnet_kiov_t * src, unsigned int offset, unsigned int len)
Definition at line 513 of file lib-move.c.
References lnet_kiov_t::kiov_len, lnet_kiov_t::kiov_offset, lnet_kiov_t::kiov_page, and LASSERT.
Referenced by ksocknal_recv(), and ksocknal_send().
int lnet_fail_nid (lnet_nid_t nid, unsigned int threshold)
Definition at line 50 of file lib-move.c.
References INIT_LIST_HEAD, LIBCFS_ALLOC, LIBCFS_FREE, list_add(), list_add_tail(), list_del(), list_empty(), list_entry, list_for_each_safe, lnet_t::ln_test_peers, lnet_net_lock(), lnet_net_unlock(), LNET_NID_ANY, list_head::next, the_lnet, lnet_test_peer_t::tp_list, lnet_test_peer_t::tp_nid, and lnet_test_peer_t::tp_threshold.
Referenced by lnet_unprepare(), and LNetCtl().
int lnet_fault_ctl (int cmd, struct libcfs_ioctl_data * data)
Definition at line 952 of file net_fault.c.
References lnet_fault_attr::fa_dst, lnet_fault_attr::fa_src, libcfs_ioctl_data::ioc_count, libcfs_ioctl_data::ioc_inlbuf1, libcfs_ioctl_data::ioc_inlbuf2, LNET_CTL_DELAY_ADD, LNET_CTL_DELAY_DEL, LNET_CTL_DELAY_LIST, LNET_CTL_DELAY_RESET, LNET_CTL_DROP_ADD, LNET_CTL_DROP_DEL, LNET_CTL_DROP_LIST, LNET_CTL_DROP_RESET, lnet_delay_rule_add(), lnet_delay_rule_del(), lnet_delay_rule_list(), lnet_delay_rule_reset(), lnet_drop_rule_add(), lnet_drop_rule_del(), lnet_drop_rule_list(), and lnet_drop_rule_reset().
Referenced by LNetCtl().
void lnet_fault_fini (void)
Definition at line 1033 of file net_fault.c.
References delay_daemon_data::dd_sched_rules, delay_dd, LASSERT, list_empty(), lnet_t::ln_delay_rules, lnet_t::ln_drop_rules, lnet_delay_rule_del(), lnet_drop_rule_del(), and the_lnet.
Referenced by LNetNIFini().
int lnet_fault_init (void)
Definition at line 1016 of file net_fault.c.
References CLASSERT, delay_daemon_data::dd_ctl_waitq, delay_daemon_data::dd_lock, delay_daemon_data::dd_mutex, delay_daemon_data::dd_sched_rules, delay_daemon_data::dd_waitq, delay_dd, INIT_LIST_HEAD, LNET_ACK_BIT, LNET_GET_BIT, LNET_MSG_ACK, LNET_MSG_GET, LNET_MSG_PUT, LNET_MSG_REPLY, LNET_PUT_BIT, and LNET_REPLY_BIT.
Referenced by LNetNIInit().
void lnet_finalize (lnet_ni_t * ni, lnet_msg_t * msg, int rc)
Definition at line 438 of file lib-msg.c.
References CDEBUG, D_WARNING, LASSERT, lnet_libhandle::lh_cookie, libcfs_id2str(), libcfs_nid2str(), list_add_tail(), list_del(), list_empty(), list_entry, lnet_t::ln_delay_rules, lnet_t::ln_msg_containers, lnet_complete_msg_locked(), lnet_cpt_of_cookie(), lnet_delay_rule_check(), lnet_msg_detach_md(), lnet_msg_free(), lnet_msgtyp2str(), lnet_net_lock(), lnet_net_unlock(), lnet_res_lock(), lnet_res_unlock(), lnet_peer::lp_nid, lnet_libmd::md_lh, lnet_msg_container::msc_finalizers, lnet_msg_container::msc_finalizing, lnet_msg_container::msc_nfinalizers, lnet_msg::msg_ack, lnet_msg::msg_ev, lnet_msg::msg_list, lnet_msg::msg_md, lnet_msg::msg_onactivelist, lnet_msg::msg_peerrtrcredit, lnet_msg::msg_peertxcredit, lnet_msg::msg_receiving, lnet_msg::msg_routing, lnet_msg::msg_rtrcredit, lnet_msg::msg_rx_committed, lnet_msg::msg_rx_cpt, lnet_msg::msg_rxpeer, lnet_msg::msg_sending, lnet_msg::msg_target, lnet_msg::msg_target_is_router, lnet_msg::msg_tx_committed, lnet_msg::msg_tx_cpt, lnet_msg::msg_txcredit, lnet_msg::msg_txpeer, lnet_msg::msg_type, list_head::next, lnet_event_t::status, the_lnet, and unlikely.
Referenced by delayed_msg_process(), kgnilnd_recv(), kgnilnd_setup_rdma(), kgnilnd_tx_done(), kiblnd_recv(), kiblnd_reply(), kiblnd_tx_done(), ksocknal_destroy_conn(), ksocknal_process_receive(), ksocknal_tx_done(), lnet_drop_delayed_msg_list(), lnet_drop_routed_msgs_locked(), lnet_ni_recv(), lnet_ni_send(), lnet_parse(), lnet_parse_get(), lnet_post_send_locked(), LNetGet(), LNetPut(), and lolnd_recv().
lnet_remotenet_t* lnet_find_net_locked (__u32 net)
Definition at line 219 of file router.c.
References LASSERT, list_entry, list_for_each, lnet_t::ln_shutdown, lnet_net2rnethash(), lnet_remotenet_t::lrn_net, and the_lnet.
Referenced by lnet_add_route(), lnet_dyn_add_ni(), and lnet_find_route_locked().
lnet_peer_t* lnet_find_peer_locked (struct lnet_peer_table * ptable, lnet_nid_t nid)
Definition at line 240 of file peer.c.
References LASSERT, list_for_each_entry, lnet_t::ln_shutdown, lnet_nid2peerhash(), lnet_peer_addref_locked(), lnet_peer::lp_nid, lnet_peer_table::pt_hash, and the_lnet.
Referenced by lnet_nid2peer_locked(), and lnet_notify().
int lnet_get_peer_info (__u32 peer_index, __u64 * nid, char alivness[LNET_MAX_STR_LEN], __u32 * cpt_iter, __u32 * refcount, __u32 * ni_peer_tx_credits, __u32 * peer_tx_credits, __u32 * peer_rtr_credits, __u32 * peer_min_rtr_credtis, __u32 * peer_tx_qnob)
Definition at line 393 of file peer.c.
References cfs_percpt_number(), list_for_each_entry, lnet_t::ln_peer_tables, lnet_isrouter(), lnet_net_lock(), lnet_net_unlock(), lnet_peer_aliveness_enabled, LNET_PEER_HASH_SIZE, lnet_peer::lp_alive, lnet_peer::lp_mintxcredits, lnet_peer::lp_ni, lnet_peer::lp_nid, lnet_peer::lp_refcount, lnet_peer::lp_rtrcredits, lnet_peer::lp_txcredits, lnet_peer::lp_txqnob, lnet_ni::ni_peertxcredits, lnet_peer_table::pt_hash, and the_lnet.
Referenced by LNetCtl().
int lnet_get_route (int idx, __u32 * net, __u32 * hops, lnet_nid_t * gateway, __u32 * alive, __u32 * priority)
Definition at line 589 of file router.c.
References list_entry, list_for_each, lnet_t::ln_remote_nets_hash, lnet_is_route_alive(), lnet_net_lock_current(), lnet_net_unlock(), LNET_REMOTE_NETS_HASH_SIZE, lnet_peer::lp_nid, lnet_route_t::lr_gateway, lnet_route_t::lr_hops, lnet_route_t::lr_priority, lnet_remotenet_t::lrn_net, lnet_remotenet_t::lrn_routes, and the_lnet.
Referenced by LNetCtl().
int lnet_get_rtr_pool_cfg (int idx, struct lnet_ioctl_pool_cfg * pool_cfg)
Definition at line 552 of file router.c.
References cfs_percpt_for_each, lnet_t::ln_routing, lnet_t::ln_rtrpools, LNET_LOCK_EX, lnet_net_lock(), lnet_net_unlock(), LNET_NRBPOOLS, lnet_ioctl_pool_cfg::pl_credits, lnet_ioctl_pool_cfg::pl_mincredits, lnet_ioctl_pool_cfg::pl_nbuffers, lnet_ioctl_pool_cfg::pl_npages, lnet_ioctl_pool_cfg::pl_pools, lnet_ioctl_pool_cfg::pl_routing, lnet_rtrbufpool_t::rbp_credits, lnet_rtrbufpool_t::rbp_mincredits, lnet_rtrbufpool_t::rbp_nbuffers, lnet_rtrbufpool_t::rbp_npages, and the_lnet.
Referenced by LNetCtl().
static lnet_eq_t* lnet_handle2eq (lnet_handle_eq_t * handle) [inline, static]
Definition at line 298 of file lib-lnet.h.
References lnet_handle_any_t::cookie, lh_entry, lnet_t::ln_eq_container, and lnet_res_lh_lookup().
Referenced by lnet_md_link(), LNetEQFree(), and LNetEQPoll().
static lnet_libmd_t* lnet_handle2md (lnet_handle_md_t * handle) [inline, static]
Definition at line 317 of file lib-lnet.h.
References lnet_handle_any_t::cookie, lh_entry, lnet_t::ln_md_containers, lnet_cpt_of_cookie(), and lnet_res_lh_lookup().
Referenced by LNetGet(), LNetMDUnlink(), and LNetPut().
static lnet_me_t* lnet_handle2me (lnet_handle_me_t * handle) [inline, static]
Definition at line 358 of file lib-lnet.h.
References lnet_handle_any_t::cookie, lh_entry, lnet_t::ln_me_containers, lnet_cpt_of_cookie(), and lnet_res_lh_lookup().
Referenced by LNetMDAttach(), LNetMEInsert(), and LNetMEUnlink().
unsigned int lnet_iov_nob (unsigned int niov, struct kvec * iov)
Definition at line 159 of file lib-move.c.
References LASSERT.
Referenced by ksocknal_queue_tx_locked(), and ksocknal_recv().
int lnet_ipif_enumerate (char *** names)
Definition at line 192 of file lib-socket.c.
References CERROR, CWARN, LASSERT, LIBCFS_ALLOC, LIBCFS_FREE, lnet_ipif_free_enumeration(), lnet_sock_ioctl(), and strnlen.
Referenced by ksocknal_enumerate_interfaces(), and lnet_ipaddr_enumerate().
void lnet_ipif_free_enumeration (char ** names, int n)
Definition at line 178 of file lib-socket.c.
References LASSERT, and LIBCFS_FREE.
Referenced by ksocknal_enumerate_interfaces(), lnet_ipaddr_enumerate(), and lnet_ipif_enumerate().
int lnet_ipif_query (char * name, int * up, __u32 * ip, __u32 * mask)
Definition at line 111 of file lib-socket.c.
References CDEBUG, CERROR, CLASSERT, D_NET, lnet_sock_ioctl(), and strnlen.
Referenced by kiblnd_create_dev(), ksocknal_enumerate_interfaces(), ksocknal_startup(), and lnet_ipaddr_enumerate().
static int lnet_is_route_alive (lnet_route_t * route) [inline, static]
Definition at line 77 of file lib-lnet.h.
References LNET_PING_FEAT_NI_STATUS, lnet_peer::lp_alive, lnet_peer::lp_ping_feats, lnet_route_t::lr_downis, and lnet_route_t::lr_gateway.
Referenced by lnet_find_route_locked(), lnet_get_route(), and proc_lnet_routes().
static int lnet_is_wire_handle_none (lnet_handle_wire_t * wh) [inline, static]
Definition at line 88 of file lib-lnet.h.
References LNET_WIRE_HANDLE_COOKIE_NONE.
Referenced by lnet_recv_put().
int lnet_islocalnet (__u32 net)
Definition at line 768 of file api-ni.c.
References lnet_net2ni_locked(), lnet_net_lock_current(), lnet_net_unlock(), and lnet_ni_decref_locked().
Referenced by lnet_add_route().
int lnet_islocalnid (lnet_nid_t nid)
Definition at line 805 of file api-ni.c.
References lnet_net_lock_current(), lnet_net_unlock(), lnet_ni_decref_locked(), and lnet_nid2ni_locked().
Referenced by lnet_parse(), and lnet_parse_route().
static int lnet_isrouter (lnet_peer_t * lp) [inline, static]
Definition at line 392 of file lib-lnet.h.
References lnet_peer::lp_rtr_refcount.
Referenced by lnet_create_rc_data_locked(), lnet_debug_peer(), lnet_get_peer_info(), lnet_parse(), lnet_peer_is_alive(), lnet_ping_router_locked(), lnet_router_checker_event(), and proc_lnet_peers().
unsigned int lnet_kiov_nob (unsigned int niov, lnet_kiov_t * iov)
Definition at line 279 of file lib-move.c.
References LASSERT.
Referenced by ksocknal_queue_tx_locked(), and ksocknal_recv().
void lnet_lib_exit (void)
Finalize LNet library.
Precondition:
lnet_lib_init() called with success.
All LNet users called LNetNIFini() for matching LNetNIInit() calls.
Definition at line 1490 of file api-ni.c.
References LASSERT, list_empty(), list_entry, lnet_t::ln_lnds, lnet_t::ln_refcount, lnet_destroy_locks(), lnet_unregister_lnd(), and list_head::next.
Referenced by lnet_exit().
int lnet_lib_init (void)
Initialize LNet library.
Automatically called at module loading time. Caller has to call lnet_lib_exit() after a call to lnet_lib_init(), if and only if the latter returned 0. It must be called exactly once.
Return values:
0 on success
-ve on failures.
Definition at line 1431 of file api-ni.c.
References CERROR, cfs_cpt_number(), INIT_LIST_HEAD, LASSERT, lnet_t::ln_cpt_bits, lnet_t::ln_cpt_number, lnet_t::ln_cpt_table, lnet_t::ln_lnds, lnet_t::ln_rc_eqh, lnet_t::ln_rcd_deathrow, lnet_t::ln_rcd_zombie, lnet_t::ln_refcount, lnet_t::ln_remote_nets_hbits, lnet_assert_wire_constants(), LNET_CPT_MAX, lnet_create_locks(), lnet_register_lnd(), LNET_REMOTE_NETS_HASH_DEFAULT, LNET_REMOTE_NETS_HASH_MAX, LNetInvalidateHandle(), rnet_htable_size, and the_lolnd.
Referenced by lnet_init().
static void lnet_md2handle (lnet_handle_md_t * handle, lnet_libmd_t * md) [inline, static]
Definition at line 311 of file lib-lnet.h.
References lnet_handle_any_t::cookie, lnet_libhandle::lh_cookie, and lnet_libmd::md_lh.
Referenced by lnet_build_unlink_event(), lnet_msg_attach_md(), LNetMDAttach(), and LNetMDBind().
static lnet_libmd_t* lnet_md_alloc (lnet_md_t * umd) [inline, static]
Definition at line 201 of file lib-lnet.h.
References INIT_LIST_HEAD, lnet_md_t::length, LIBCFS_ALLOC, LNET_MD_IOVEC, LNET_MD_KIOV, lnet_libmd::md_list, lnet_libmd::md_niov, lnet_libmd::md_options, offsetof, lnet_md_t::options, and size.
Referenced by LNetMDAttach(), and LNetMDBind().
void lnet_md_deconstruct (lnet_libmd_t * lmd, lnet_md_t * umd)
Definition at line 201 of file lib-md.c.
References lnet_md_t::eq_handle, lnet_md_t::length, lnet_eq2handle(), LNET_MD_IOVEC, LNET_MD_KIOV, lnet_md_t::max_size, lnet_libmd::md_eq, lnet_libmd::md_length, lnet_libmd::md_max_size, lnet_libmd::md_niov, lnet_libmd::md_options, lnet_libmd::md_start, lnet_libmd::md_threshold, lnet_libmd::md_user_ptr, lnet_md_t::options, lnet_md_t::start, lnet_md_t::threshold, and lnet_md_t::user_ptr.
Referenced by lnet_build_unlink_event(), and lnet_msg_attach_md().
static int lnet_md_exhausted (lnet_libmd_t * md) [inline, static]
Definition at line 94 of file lib-lnet.h.
References LNET_MD_MAX_SIZE, lnet_libmd::md_length, lnet_libmd::md_max_size, lnet_libmd::md_offset, lnet_libmd::md_options, and lnet_libmd::md_threshold.
Referenced by lnet_md_unlinkable(), and lnet_try_match_md().
static void lnet_md_free (lnet_libmd_t * md) [inline, static]
Definition at line 229 of file lib-lnet.h.
References LIBCFS_FREE, LNET_MD_KIOV, lnet_libmd::md_niov, lnet_libmd::md_options, offsetof, and size.
Referenced by lnet_md_unlink(), lnet_res_container_cleanup(), LNetMDAttach(), and LNetMDBind().
void lnet_md_unlink (lnet_libmd_t * md)
Definition at line 47 of file lib-md.c.
References CDEBUG, D_NET, lnet_eq::eq_refs, LASSERT, lnet_libhandle::lh_cookie, list_del_init(), list_empty(), lnet_cpt_of_cookie(), LNET_MD_FLAG_ZOMBIE, lnet_md_free(), lnet_me_unlink(), lnet_ptl_detach_md(), lnet_res_lh_invalidate(), LNET_UNLINK, lnet_libmd::md_eq, lnet_libmd::md_flags, lnet_libmd::md_lh, lnet_libmd::md_list, lnet_libmd::md_me, lnet_libmd::md_refcount, and lnet_me::me_unlink.
Referenced by lnet_me_unlink(), lnet_msg_detach_md(), lnet_try_match_md(), and LNetMDUnlink().
static int lnet_md_unlinkable (lnet_libmd_t * md) [inline, static]
Definition at line 101 of file lib-lnet.h.
References lnet_md_exhausted(), LNET_MD_FLAG_AUTO_UNLINK, LNET_MD_FLAG_ZOMBIE, lnet_libmd::md_flags, and lnet_libmd::md_refcount.
Referenced by lnet_msg_detach_md().
static void lnet_me2handle (lnet_handle_me_t * handle, lnet_me_t * me) [inline, static]
Definition at line 352 of file lib-lnet.h.
References lnet_handle_any_t::cookie, lnet_libhandle::lh_cookie, and lnet_me::me_lh.
Referenced by LNetMEAttach(), and LNetMEInsert().
static lnet_me_t* lnet_me_alloc (void) [inline, static]
Definition at line 242 of file lib-lnet.h.
References LIBCFS_ALLOC.
Referenced by LNetMEAttach(), and LNetMEInsert().
static void lnet_me_free (lnet_me_t * me) [inline, static]
Definition at line 251 of file lib-lnet.h.
References LIBCFS_FREE.
Referenced by lnet_me_unlink(), lnet_ptl_cleanup(), and LNetMEInsert().
void lnet_me_unlink (lnet_me_t * me)
Definition at line 263 of file lib-me.c.
References list_del(), lnet_md_unlink(), lnet_me_free(), lnet_ptl_detach_md(), lnet_res_lh_invalidate(), lnet_me::me_lh, lnet_me::me_list, and lnet_me::me_md.
Referenced by lnet_md_unlink(), and LNetMEUnlink().
static lnet_msg_t* lnet_msg_alloc (void) [inline, static]
Definition at line 257 of file lib-lnet.h.
References LIBCFS_ALLOC, and msg.
Referenced by lnet_create_reply_msg(), lnet_parse(), LNetGet(), and LNetPut().
void lnet_msg_attach_md (lnet_msg_t * msg, lnet_libmd_t * md, unsigned int offset, unsigned int mlen)
Definition at line 311 of file lib-msg.c.
References LASSERT, lnet_md2handle(), lnet_md_deconstruct(), LNET_MD_THRESH_INF, lnet_event_t::md, lnet_event_t::md_handle, lnet_libmd::md_refcount, lnet_libmd::md_threshold, lnet_msg::msg_ev, lnet_msg::msg_md, lnet_msg::msg_offset, lnet_msg::msg_receiving, lnet_msg::msg_routing, and lnet_msg::msg_wanted.
Referenced by lnet_create_reply_msg(), lnet_parse_ack(), lnet_parse_reply(), lnet_try_match_md(), LNetGet(), and LNetPut().
void lnet_msg_commit (lnet_msg_t * msg, int cpt)
Definition at line 140 of file lib-msg.c.
References LASSERT, list_add(), lnet_t::ln_counters, lnet_t::ln_msg_containers, lnet_msg_container::msc_active, lnet_msg::msg_activelist, lnet_msg::msg_onactivelist, lnet_msg::msg_receiving, lnet_msg::msg_rx_committed, lnet_msg::msg_rx_cpt, lnet_msg::msg_sending, lnet_msg::msg_tx_committed, lnet_msg::msg_tx_cpt, lnet_counters::msgs_alloc, lnet_counters::msgs_max, and the_lnet.
Referenced by lnet_create_reply_msg(), lnet_parse(), and lnet_send().
void lnet_msg_container_cleanup (struct lnet_msg_container * container)
Definition at line 544 of file lib-msg.c.
References CERROR, LASSERT, LIBCFS_FREE, list_del(), list_empty(), list_entry, lnet_msg_free(), lnet_msg_container::msc_active, lnet_msg_container::msc_finalizers, lnet_msg_container::msc_init, lnet_msg_container::msc_nfinalizers, msg, lnet_msg::msg_activelist, lnet_msg::msg_onactivelist, and list_head::next.
Referenced by lnet_msg_container_setup(), and lnet_msg_containers_destroy().
int lnet_msg_container_setup (struct lnet_msg_container * container, int cpt)
Definition at line 575 of file lib-msg.c.
References CERROR, cfs_cpt_weight(), INIT_LIST_HEAD, LIBCFS_CPT_ALLOC, lnet_cpt_table, lnet_msg_container_cleanup(), lnet_msg_container::msc_active, lnet_msg_container::msc_finalizers, lnet_msg_container::msc_finalizing, lnet_msg_container::msc_init, and lnet_msg_container::msc_nfinalizers.
Referenced by lnet_msg_containers_create().
int lnet_msg_containers_create (void)
Definition at line 618 of file lib-msg.c.
References CERROR, cfs_percpt_alloc(), cfs_percpt_for_each, lnet_t::ln_msg_containers, lnet_cpt_table, lnet_msg_container_setup(), lnet_msg_containers_destroy(), and the_lnet.
Referenced by lnet_prepare().
void lnet_msg_containers_destroy (void)
Definition at line 602 of file lib-msg.c.
References cfs_percpt_for_each, cfs_percpt_free(), lnet_t::ln_msg_containers, lnet_msg_container_cleanup(), and the_lnet.
Referenced by lnet_msg_containers_create(), and lnet_unprepare().
void lnet_msg_decommit (lnet_msg_t * msg, int cpt, int status)
Definition at line 277 of file lib-msg.c.
References LASSERT, list_del(), lnet_t::ln_counters, lnet_msg_decommit_rx(), lnet_msg_decommit_tx(), lnet_net_lock(), lnet_net_unlock(), lnet_msg::msg_activelist, lnet_msg::msg_onactivelist, lnet_msg::msg_rx_committed, lnet_msg::msg_rx_cpt, lnet_msg::msg_tx_committed, lnet_msg::msg_tx_cpt, lnet_counters::msgs_alloc, and the_lnet.
Referenced by lnet_complete_msg_locked().
void lnet_msg_detach_md (lnet_msg_t * msg, int status)
Definition at line 339 of file lib-msg.c.
References LASSERT, lnet_eq_enqueue_event(), lnet_md_unlink(), lnet_md_unlinkable(), lnet_libmd::md_eq, lnet_libmd::md_refcount, lnet_msg::msg_ev, lnet_msg::msg_md, lnet_event_t::status, and lnet_event_t::unlinked.
Referenced by lnet_finalize().
static void lnet_msg_free (lnet_msg_t * msg) [inline, static]
Definition at line 268 of file lib-lnet.h.
References LASSERT, LIBCFS_FREE, and lnet_msg::msg_onactivelist.
Referenced by lnet_complete_msg_locked(), lnet_create_reply_msg(), lnet_finalize(), lnet_msg_container_cleanup(), lnet_parse(), LNetGet(), and LNetPut().
char* lnet_msgtyp2str (int type)
Definition at line 1734 of file lib-move.c.
References LNET_MSG_ACK, LNET_MSG_GET, LNET_MSG_HELLO, LNET_MSG_PUT, and LNET_MSG_REPLY.
Referenced by lnet_finalize(), lnet_parse(), lnet_print_hdr(), and lnet_send().
struct list_head* lnet_mt_match_head (struct lnet_match_table * mtable, lnet_process_id_t id, __u64 mbits) [read]
Definition at line 358 of file lib-ptl.c.
References LASSERT, lnet_t::ln_portals, LNET_MT_HASH_BITS, LNET_MT_HASH_MASK, lnet_ptl_is_unique(), lnet_ptl_is_wildcard(), lnet_match_table::mt_mhash, lnet_match_table::mt_portal, and the_lnet.
Referenced by lnet_mt_match_md(), and LNetMEAttach().
int lnet_mt_match_md (struct lnet_match_table * mtable, struct lnet_match_info * info, struct lnet_msg * msg)
Definition at line 375 of file lib-ptl.c.
References head, LASSERT, list_empty(), list_for_each_entry_safe, lnet_t::ln_portals, LNET_MATCHMD_DROP, LNET_MATCHMD_EXHAUSTED, LNET_MATCHMD_FINISH, LNET_MATCHMD_NONE, LNET_MD_OP_GET, LNET_MT_HASH_IGNORE, lnet_mt_match_head(), lnet_mt_set_exhausted(), lnet_mt_test_exhausted(), lnet_ptl_is_lazy(), lnet_ptl_is_wildcard(), lnet_try_match_md(), lnet_libmd::md_me, lnet_me::me_md, lnet_match_info::mi_id, lnet_match_info::mi_mbits, lnet_match_info::mi_opc, lnet_match_info::mi_portal, lnet_match_table::mt_mhash, lnet_match_table::mt_portal, and the_lnet.
Referenced by lnet_ptl_match_delay(), and lnet_ptl_match_md().
struct lnet_match_table* lnet_mt_of_attach (unsigned int index, lnet_process_id_t id, __u64 mbits, __u64 ignore_bits, lnet_ins_pos_t pos) [read]
Definition at line 229 of file lib-ptl.c.
References LASSERT, lnet_t::ln_nportals, lnet_t::ln_portals, lnet_cpt_current, LNET_CPT_NUMBER, LNET_INS_AFTER, LNET_INS_BEFORE, LNET_INS_LOCAL, lnet_match2mt(), lnet_ptl_match_type(), lnet_portal::ptl_index, lnet_portal::ptl_mtables, and the_lnet.
Referenced by LNetMEAttach().
lnet_ni_t* lnet_net2ni (__u32 net)
Definition at line 692 of file api-ni.c.
References lnet_net2ni_locked(), lnet_net_lock(), and lnet_net_unlock().
Referenced by kiblnd_passive_connect(), lnet_accept(), lnet_dyn_del_ni(), and LNetCtl().
lnet_ni_t* lnet_net2ni_locked (__u32 net, int cpt)
Definition at line 672 of file api-ni.c.
References LASSERT, list_entry, list_for_each, lnet_t::ln_nis, LNET_LOCK_EX, lnet_ni_addref_locked(), LNET_NIDNET(), and lnet_ni::ni_nid.
Referenced by lnet_islocalnet(), lnet_net2ni(), lnet_nid2peer_locked(), and lnet_send().
static struct list_head* lnet_net2rnethash (__u32 net) [static, read]
Definition at line 442 of file lib-lnet.h.
References lnet_t::ln_remote_nets_hash, lnet_t::ln_remote_nets_hbits, LNET_NETNUM(), and LNET_NETTYP().
Referenced by lnet_add_route(), lnet_del_route(), lnet_find_net_locked(), and LNetDist().
static void lnet_net_lock (int cpt) [inline, static]
Definition at line 153 of file lib-lnet.h.
References cfs_percpt_lock(), and lnet_t::ln_net_lock.
Referenced by __proc_lnet_buffers(), delayed_msg_process(), fail_peer(), lnet_add_route(), lnet_clear_zombies_nis_locked(), lnet_complete_msg_locked(), lnet_connect(), lnet_counters_get(), lnet_counters_reset(), lnet_create_rc_data_locked(), lnet_create_reply_msg(), lnet_debug_peer(), lnet_del_route(), lnet_delay_rule_add(), lnet_delay_rule_del(), lnet_destroy_rc_data(), lnet_drop_message(), lnet_drop_routed_msgs_locked(), lnet_drop_rule_add(), lnet_drop_rule_del(), lnet_dyn_add_ni(), lnet_fail_nid(), lnet_finalize(), lnet_get_ni_count(), lnet_get_peer_info(), lnet_get_rtr_pool_cfg(), lnet_msg_decommit(), lnet_net2ni(), lnet_net_lock_current(), lnet_ni_addref(), lnet_ni_decref(), lnet_ni_notify_locked(), lnet_ni_query_locked(), lnet_nid2peer_locked(), lnet_notify(), lnet_parse(), lnet_parse_forward_locked(), lnet_peer_table_deathrow_wait_locked(), lnet_peer_table_del_rtrs_locked(), lnet_peer_tables_cleanup(), lnet_ping_info_destroy(), lnet_ping_router_locked(), lnet_ping_target_update(), lnet_post_routed_recv_locked(), lnet_post_send_locked(), lnet_prune_rc_data(), lnet_router_checker(), lnet_router_checker_event(), lnet_rtrpool_adjust_bufs(), lnet_rtrpool_free_bufs(), lnet_rtrpools_alloc(), lnet_rtrpools_disable(), lnet_rtrpools_enable(), lnet_send(), lnet_shutdown_lndni(), lnet_shutdown_lndnis(), lnet_startup_lndni(), LNetCtl(), proc_lnet_nis(), proc_lnet_peers(), proc_lnet_routers(), and proc_lnet_routes().
static int lnet_net_lock_current (void) [inline, static]
Definition at line 165 of file lib-lnet.h.
References lnet_cpt_current, and lnet_net_lock().
Referenced by lnet_check_routes(), lnet_count_acceptor_nis(), lnet_cpt_of_nid(), lnet_delay_rule_list(), lnet_delay_rule_reset(), lnet_drop_rule_list(), lnet_drop_rule_match(), lnet_drop_rule_reset(), lnet_get_net_config(), lnet_get_route(), lnet_islocalnet(), lnet_islocalnid(), lnet_router_checker(), lnet_wait_known_routerstate(), LNetDist(), and LNetGetId().
int lnet_net_unique (__u32 net, struct list_head * nilist)
Definition at line 82 of file config.c.
References list_entry, list_for_each, LNET_NIDNET(), and lnet_ni::ni_nid.
Referenced by lnet_ni_alloc(), and lnet_startup_lndni().
static void lnet_net_unlock (int cpt) [inline, static]
Definition at line 159 of file lib-lnet.h.
References cfs_percpt_unlock(), and lnet_t::ln_net_lock.
Referenced by __proc_lnet_buffers(), delayed_msg_process(), fail_peer(), lnet_add_route(), lnet_check_routes(), lnet_clear_zombies_nis_locked(), lnet_complete_msg_locked(), lnet_connect(), lnet_count_acceptor_nis(), lnet_counters_get(), lnet_counters_reset(), lnet_cpt_of_nid(), lnet_create_rc_data_locked(), lnet_create_reply_msg(), lnet_debug_peer(), lnet_del_route(), lnet_delay_rule_add(), lnet_delay_rule_del(), lnet_delay_rule_list(), lnet_delay_rule_reset(), lnet_destroy_rc_data(), lnet_drop_message(), lnet_drop_routed_msgs_locked(), lnet_drop_rule_add(), lnet_drop_rule_del(), lnet_drop_rule_list(), lnet_drop_rule_match(), lnet_drop_rule_reset(), lnet_dyn_add_ni(), lnet_fail_nid(), lnet_finalize(), lnet_get_net_config(), lnet_get_ni_count(), lnet_get_peer_info(), lnet_get_route(), lnet_get_rtr_pool_cfg(), lnet_islocalnet(), lnet_islocalnid(), lnet_msg_decommit(), lnet_net2ni(), lnet_ni_addref(), lnet_ni_decref(), lnet_ni_notify_locked(), lnet_ni_query_locked(), lnet_nid2peer_locked(), lnet_notify(), lnet_parse(), lnet_parse_forward_locked(), lnet_peer_table_deathrow_wait_locked(), lnet_peer_table_del_rtrs_locked(), lnet_peer_tables_cleanup(), lnet_ping_info_destroy(), lnet_ping_router_locked(), lnet_ping_target_update(), lnet_post_routed_recv_locked(), lnet_post_send_locked(), lnet_prune_rc_data(), lnet_router_checker(), lnet_router_checker_event(), lnet_rtrpool_adjust_bufs(), lnet_rtrpool_free_bufs(), lnet_rtrpools_alloc(), lnet_rtrpools_disable(), lnet_rtrpools_enable(), lnet_send(), lnet_shutdown_lndni(), lnet_shutdown_lndnis(), lnet_startup_lndni(), lnet_wait_known_routerstate(), LNetCtl(), LNetDist(), LNetGetId(), proc_lnet_nis(), proc_lnet_peers(), proc_lnet_routers(), and proc_lnet_routes().
static void lnet_ni_addref (lnet_ni_t * ni) [inline, static]
Definition at line 407 of file lib-lnet.h.
References lnet_net_lock(), lnet_net_unlock(), and lnet_ni_addref_locked().
Referenced by ksocknal_accept(), and lnet_startup_lndni().
static void lnet_ni_addref_locked (lnet_ni_t * ni, int cpt) [inline, static]
Definition at line 398 of file lib-lnet.h.
References LASSERT, LNET_CPT_NUMBER, and lnet_ni::ni_refs.
Referenced by lnet_net2ni_locked(), lnet_ni_addref(), lnet_nid2ni_locked(), and lnet_startup_lndni().
lnet_ni_t* lnet_ni_alloc (__u32 net, struct cfs_expr_list * el, struct list_head * nilist)
Definition at line 123 of file config.c.
References CERROR, cfs_expr_list_values(), cfs_percpt_alloc(), cfs_percpt_for_each, cfs_time_current_sec(), INIT_LIST_HEAD, LASSERT, LCONSOLE_ERROR_MSG, LIBCFS_ALLOC, LIBCFS_FREE, libcfs_net2str(), list_add_tail(), LNET_CPT_NUMBER, lnet_cpt_table, LNET_MKNID(), lnet_net_unique(), lnet_ni_free(), lnet_ni::ni_cptlist, lnet_ni::ni_cpts, lnet_ni::ni_last_alive, lnet_ni::ni_list, lnet_ni::ni_lock, lnet_ni::ni_ncpts, lnet_ni::ni_nid, lnet_ni::ni_refs, lnet_ni::ni_tx_queues, and lnet_tx_queue::tq_delayed.
Referenced by lnet_parse_networks(), and LNetNIInit().
static void lnet_ni_decref (lnet_ni_t * ni) [inline, static]
Definition at line 424 of file lib-lnet.h.
References lnet_net_lock(), lnet_net_unlock(), and lnet_ni_decref_locked().
Referenced by kiblnd_passive_connect(), ksocknal_connd(), lnet_accept(), and LNetCtl().
static void lnet_ni_decref_locked (lnet_ni_t * ni, int cpt) [inline, static]
Definition at line 415 of file lib-lnet.h.
References LASSERT, LNET_CPT_NUMBER, and lnet_ni::ni_refs.
Referenced by lnet_destroy_peer_locked(), lnet_dyn_del_ni(), lnet_islocalnet(), lnet_islocalnid(), lnet_ni_decref(), lnet_ni_unlink_locked(), lnet_send(), and lnet_shutdown_lndnis().
void lnet_ni_free (lnet_ni_t * ni)
Definition at line 98 of file config.c.
References cfs_expr_list_values_free(), cfs_percpt_free(), LIBCFS_FREE, LNET_MAX_INTERFACES, lnet_ni::ni_cpts, lnet_ni::ni_interfaces, lnet_ni::ni_lnd_tunables, lnet_ni::ni_ncpts, lnet_ni::ni_refs, and lnet_ni::ni_tx_queues.
Referenced by lnet_clear_zombies_nis_locked(), lnet_dyn_add_ni(), lnet_ni_alloc(), lnet_parse_networks(), lnet_startup_lndni(), and LNetNIInit().
void lnet_ni_recv (lnet_ni_t * ni, void * private, lnet_msg_t * msg, int delayed, unsigned int offset, unsigned int mlen, unsigned int rlen)
Definition at line 563 of file lib-move.c.
References LASSERT, lnet_lnd::lnd_recv, lnet_finalize(), lnet_msg::msg_iov, lnet_msg::msg_kiov, lnet_msg::msg_len, lnet_msg::msg_niov, lnet_msg::msg_offset, lnet_msg::msg_receiving, lnet_msg::msg_sending, lnet_msg::msg_wanted, and lnet_ni::ni_lnd.
Referenced by delayed_msg_process(), lnet_drop_message(), lnet_drop_routed_msgs_locked(), lnet_parse(), lnet_parse_ack(), lnet_parse_get(), lnet_parse_reply(), lnet_post_routed_recv_locked(), and lnet_recv_put().
lnet_ni_t* lnet_nid2ni_locked (lnet_nid_t nid, int cpt)
Definition at line 785 of file api-ni.c.
References LASSERT, list_entry, list_for_each, lnet_t::ln_nis, LNET_LOCK_EX, lnet_ni_addref_locked(), and lnet_ni::ni_nid.
Referenced by lnet_islocalnid(), and lnet_send().
int lnet_nid2peer_locked (lnet_peer_t ** lpp, lnet_nid_t nid, int cpt)
Definition at line 259 of file peer.c.
References cfs_time_current(), INIT_LIST_HEAD, LIBCFS_CPT_ALLOC, list_add(), list_add_tail(), list_del(), list_empty(), list_entry, lnet_t::ln_peer_tables, lnet_t::ln_shutdown, lnet_cpt_of_nid_locked(), lnet_cpt_table, lnet_find_peer_locked(), LNET_LOCK_EX, lnet_net2ni_locked(), lnet_net_lock(), lnet_net_unlock(), lnet_nid2peerhash(), LNET_NIDNET(), lnet_peer_buffer_credits(), lnet_peers_start_down(), LNET_PING_FEAT_INVAL, lnet_peer::lp_alive, lnet_peer::lp_alive_count, lnet_peer::lp_cpt, lnet_peer::lp_hashlist, lnet_peer::lp_last_alive, lnet_peer::lp_last_query, lnet_peer::lp_minrtrcredits, lnet_peer::lp_mintxcredits, lnet_peer::lp_ni, lnet_peer::lp_nid, lnet_peer::lp_notify, lnet_peer::lp_notifying, lnet_peer::lp_notifylnd, lnet_peer::lp_ping_feats, lnet_peer::lp_ping_timestamp, lnet_peer::lp_refcount, lnet_peer::lp_routes, lnet_peer::lp_rtr_refcount, lnet_peer::lp_rtrcredits, lnet_peer::lp_rtrq, lnet_peer::lp_timestamp, lnet_peer::lp_txcredits, lnet_peer::lp_txq, list_head::next, lnet_ni::ni_peertxcredits, lnet_peer_table::pt_deathrow, lnet_peer_table::pt_hash, lnet_peer_table::pt_number, lnet_peer_table::pt_version, and the_lnet.
Referenced by lnet_add_route(), lnet_debug_peer(), lnet_parse(), and lnet_send().
static int lnet_nid2peerhash (lnet_nid_t nid) [inline, static]
Definition at line 436 of file lib-lnet.h.
References LNET_PEER_HASH_BITS.
Referenced by lnet_find_peer_locked(), and lnet_nid2peer_locked().
int lnet_notify (lnet_ni_t * ni, lnet_nid_t peer, int alive, cfs_time_t when)
Definition at line 1721 of file router.c.
References auto_down, CDEBUG, cfs_duration_sec(), cfs_time_after(), cfs_time_current(), cfs_time_sub(), CWARN, D_NET, LASSERT, libcfs_nid2str(), lnet_t::ln_peer_tables, lnet_t::ln_shutdown, lnet_cpt_of_nid(), lnet_find_peer_locked(), lnet_net_lock(), lnet_net_unlock(), lnet_ni_notify_locked(), LNET_NIDNET(), lnet_notify_locked(), lnet_peer_decref_locked(), lnet_peer::lp_last_alive, lnet_ni::ni_nid, now(), and the_lnet.
Referenced by kgnilnd_finish_connect(), kgnilnd_peer_notify(), kiblnd_peer_notify(), ksocknal_peer_failed(), and LNetCtl().
void lnet_notify_locked (lnet_peer_t * lp, int notifylnd, int alive, cfs_time_t when)
Definition at line 101 of file router.c.
References CDEBUG, cfs_time_before(), D_NET, libcfs_nid2str(), LNET_PING_FEAT_INVAL, lnet_peer::lp_alive, lnet_peer::lp_alive_count, lnet_peer::lp_nid, lnet_peer::lp_notify, lnet_peer::lp_notifylnd, lnet_peer::lp_ping_deadline, lnet_peer::lp_ping_feats, and lnet_peer::lp_timestamp.
Referenced by lnet_notify(), lnet_peer_alive_locked(), lnet_peer_is_alive(), lnet_peer_set_alive(), lnet_ping_router_locked(), and lnet_router_checker_event().
int lnet_parse (lnet_ni_t * ni, lnet_hdr_t * hdr, lnet_nid_t fromnid, void * private, int rdma_req)
Definition at line 1815 of file lib-move.c.
References avoid_asym_router_failure, CDEBUG, CERROR, cfs_time_current_sec(), D_NET, fail_peer(), LASSERT, le32_to_cpu, le64_to_cpu, libcfs_nid2str(), list_empty(), lnet_t::ln_delay_rules, lnet_t::ln_drop_rules, lnet_t::ln_routing, lnet_t::ln_test_peers, lnet_cpt_of_nid(), LNET_CREDIT_OK, lnet_delay_rule_match_locked(), lnet_drop_message(), lnet_drop_rule_match(), lnet_finalize(), lnet_islocalnid(), lnet_isrouter(), LNET_MAX_PAYLOAD, LNET_MSG_ACK, lnet_msg_alloc(), lnet_msg_commit(), lnet_msg_free(), LNET_MSG_GET, LNET_MSG_PUT, LNET_MSG_REPLY, lnet_msgtyp2str(), LNET_MTU, lnet_net_lock(), lnet_net_unlock(), lnet_ni_lock, lnet_ni_recv(), LNET_NI_STATUS_DOWN, LNET_NI_STATUS_UP, lnet_ni_unlock, lnet_nid2peer_locked(), LNET_NIDNET(), lnet_parse_forward_locked(), lnet_parse_local(), lnet_peer_set_alive(), lnet_router_ni_update_locked(), msg, lnet_msg::msg_from, lnet_msg::msg_hdr, lnet_msg::msg_len, lnet_msg::msg_md, lnet_msg::msg_offset, lnet_msg::msg_private, lnet_msg::msg_rdma_get, lnet_msg::msg_receiving, lnet_msg::msg_routing, lnet_msg::msg_rxpeer, lnet_msg::msg_target, lnet_msg::msg_type, lnet_msg::msg_wanted, lnet_ni::ni_last_alive, lnet_ni::ni_nid, lnet_ni::ni_status, lnet_process_id_t::nid, lnet_process_id_t::pid, the_lnet, and unlikely.
Referenced by kgnilnd_check_fma_rx(), kiblnd_handle_rx(), ksocknal_process_receive(), and lolnd_send().
int lnet_parse_forward_locked (lnet_ni_t * ni, lnet_msg_t * msg)
Return values:
LNET_CREDIT_OK If msg is forwarded
LNET_CREDIT_WAIT If msg is blocked because w/o buffer
-ve error code
Definition at line 1683 of file lib-move.c.
References lnet_t::ln_routing, lnet_lnd::lnd_eager_recv, lnet_msg2bufpool(), lnet_net_lock(), lnet_net_unlock(), lnet_ni_eager_recv(), lnet_post_routed_recv_locked(), lnet_peer::lp_rtrcredits, lnet_msg::msg_rx_cpt, lnet_msg::msg_rx_ready_delay, lnet_msg::msg_rxpeer, lnet_ni::ni_lnd, and the_lnet.
Referenced by delayed_msg_process(), and lnet_parse().
int lnet_parse_ip2nets (char ** networksp, char * ip2nets)
Definition at line 1219 of file config.c.
References LCONSOLE_ERROR_MSG, lnet_ipaddr_enumerate(), lnet_ipaddr_free_enumeration(), and lnet_match_networks().
Referenced by lnet_get_networks().
int lnet_parse_local (lnet_ni_t * ni, lnet_msg_t * msg)
Definition at line 1707 of file lib-move.c.
References LASSERT, LNET_MSG_ACK, LNET_MSG_GET, LNET_MSG_PUT, LNET_MSG_REPLY, lnet_parse_ack(), lnet_parse_get(), lnet_parse_put(), lnet_parse_reply(), lnet_msg::msg_rdma_get, and lnet_msg::msg_type.
Referenced by delayed_msg_process(), and lnet_parse().
int lnet_parse_networks (struct list_head * nilist, char * networks)
Definition at line 189 of file config.c.
References CERROR, cfs_expr_list_free(), cfs_expr_list_parse(), cfs_trimwhite(), LCONSOLE_ERROR_MSG, LIBCFS_ALLOC, LIBCFS_FREE, libcfs_net2str(), libcfs_str2net(), list_del(), list_empty(), list_entry, list_for_each, LNET_CPT_NUMBER, LNET_MAX_INTERFACES, LNET_NETTYP(), lnet_ni_alloc(), lnet_ni_free(), LNET_NID_ANY, LNET_NIDNET(), LNET_SINGLE_TEXTBUF_NOB, lnet_syntax(), LOLND, list_head::next, lnet_ni::ni_interfaces, and lnet_ni::ni_list.
Referenced by lnet_dyn_add_ni(), and LNetNIInit().
int lnet_parse_routes (char * route_str, int * im_a_router)
Definition at line 831 of file config.c.
References CERROR, INIT_LIST_HEAD, LASSERT, lnet_parse_route_tbs(), lnet_str2tbs_sep(), and lnet_tbnob.
Referenced by LNetNIInit().
static void lnet_peer_addref_locked (lnet_peer_t * lp) [inline, static]
Definition at line 374 of file lib-lnet.h.
References LASSERT, and lnet_peer::lp_refcount.
Referenced by lnet_add_route(), lnet_create_rc_data_locked(), lnet_find_peer_locked(), lnet_ping_router_locked(), lnet_rtr_addref_locked(), and lnet_send().
int lnet_peer_buffer_credits (lnet_ni_t * ni)
Definition at line 58 of file router.c.
References lnet_ni::ni_peerrtrcredits, lnet_ni::ni_peertxcredits, and peer_buffer_credits.
Referenced by lnet_nid2peer_locked().
static void lnet_peer_decref_locked (lnet_peer_t * lp) [inline, static]
Definition at line 383 of file lib-lnet.h.
References LASSERT, lnet_destroy_peer_locked(), and lnet_peer::lp_refcount.
Referenced by lnet_add_route(), lnet_debug_peer(), lnet_del_route(), lnet_destroy_rc_data(), lnet_notify(), lnet_peer_table_cleanup_locked(), lnet_ping_router_locked(), lnet_return_rx_credits_locked(), lnet_return_tx_credits_locked(), and lnet_rtr_decref_locked().
static void lnet_peer_set_alive (lnet_peer_t * lp) [inline, static]
Definition at line 758 of file lib-lnet.h.
References cfs_time_current(), lnet_notify_locked(), lnet_peer::lp_alive, lnet_peer::lp_last_alive, and lnet_peer::lp_last_query.
Referenced by lnet_parse().
void lnet_peer_tables_cleanup (lnet_ni_t * ni)
Definition at line 175 of file peer.c.
References cfs_percpt_for_each, INIT_LIST_HEAD, LASSERT, LIBCFS_FREE, list_del(), list_empty(), list_entry, list_splice_init(), lnet_t::ln_peer_tables, lnet_t::ln_shutdown, lnet_net_lock(), lnet_net_unlock(), lnet_peer_table_cleanup_locked(), lnet_peer_table_deathrow_wait_locked(), lnet_peer_table_del_rtrs_locked(), lnet_peer::lp_hashlist, list_head::next, lnet_peer_table::pt_deathrow, and the_lnet.
Referenced by lnet_shutdown_lndni(), and lnet_shutdown_lndnis().
int lnet_peer_tables_create (void)
Definition at line 45 of file peer.c.
References CERROR, cfs_percpt_alloc(), cfs_percpt_for_each, INIT_LIST_HEAD, LIBCFS_CPT_ALLOC, lnet_t::ln_peer_tables, lnet_cpt_table, LNET_PEER_HASH_SIZE, lnet_peer_tables_destroy(), lnet_peer_table::pt_deathrow, lnet_peer_table::pt_hash, and the_lnet.
Referenced by lnet_prepare().
void lnet_peer_tables_destroy (void)
Definition at line 79 of file peer.c.
References cfs_percpt_for_each, cfs_percpt_free(), LASSERT, LIBCFS_FREE, list_empty(), lnet_t::ln_peer_tables, LNET_PEER_HASH_SIZE, lnet_peer_table::pt_deathrow, lnet_peer_table::pt_hash, and the_lnet.
Referenced by lnet_peer_tables_create(), and lnet_unprepare().
int lnet_peers_start_down (void)
Definition at line 95 of file router.c.
References check_routers_before_use.
Referenced by lnet_nid2peer_locked().
int lnet_portals_create (void)
Definition at line 843 of file lib-ptl.c.
References CERROR, cfs_array_alloc(), lnet_t::ln_nportals, lnet_t::ln_portals, LNET_CPT_NUMBER, lnet_portals_destroy(), lnet_ptl_setup(), MAX_PORTALS, offsetof, size, and the_lnet.
Referenced by lnet_prepare().
void lnet_portals_destroy (void)
Definition at line 828 of file lib-ptl.c.
References cfs_array_free(), lnet_t::ln_nportals, lnet_t::ln_portals, lnet_ptl_cleanup(), and the_lnet.
Referenced by lnet_portals_create(), and lnet_unprepare().
void lnet_prep_send (lnet_msg_t * msg, int type, lnet_process_id_t target, unsigned int offset, unsigned int len)
Definition at line 620 of file lib-move.c.
References cpu_to_le32, cpu_to_le64, lnet_t::ln_pid, lnet_setpayloadbuffer(), lnet_msg::msg_hdr, lnet_msg::msg_len, lnet_msg::msg_offset, lnet_msg::msg_target, lnet_msg::msg_type, lnet_process_id_t::nid, lnet_process_id_t::pid, and the_lnet.
Referenced by lnet_complete_msg_locked(), lnet_parse_get(), LNetGet(), and LNetPut().
void lnet_print_hdr (lnet_hdr_t * hdr)
Definition at line 1753 of file lib-move.c.
References CWARN, libcfs_id2str(), LNET_MSG_ACK, LNET_MSG_GET, LNET_MSG_PUT, LNET_MSG_REPLY, lnet_msgtyp2str(), LPU64, LPX64, lnet_process_id_t::nid, and lnet_process_id_t::pid.
void lnet_proc_fini (void)
Definition at line 932 of file router_proc.c.
References lnet_table_header.
Referenced by LNetNIFini().
void lnet_proc_init (void)
Definition at line 923 of file router_proc.c.
References lnet_table_header, and top_table.
Referenced by LNetNIInit().
void lnet_ptl_attach_md (lnet_me_t * me, lnet_libmd_t * md, struct list_head * matches, struct list_head * drops)
Definition at line 650 of file lib-ptl.c.
References CDEBUG, D_NET, head, LASSERT, lnet_libhandle::lh_cookie, libcfs_id2str(), list_add_tail(), list_del_init(), list_empty(), list_for_each_entry_safe, lnet_t::ln_portals, lnet_cpt_of_cookie(), LNET_MATCHMD_EXHAUSTED, LNET_MATCHMD_FINISH, LNET_MATCHMD_NONE, LNET_MATCHMD_OK, LNET_MD_OP_PUT, lnet_mt_set_exhausted(), lnet_mt_test_exhausted(), lnet_ptl_enable_mt(), lnet_ptl_is_wildcard(), lnet_ptl_lock, lnet_ptl_unlock, lnet_try_match_md(), LPU64, lnet_libmd::md_lh, lnet_libmd::md_me, lnet_libmd::md_refcount, lnet_me::me_md, lnet_me::me_portal, lnet_me::me_pos, lnet_match_info::mi_id, lnet_match_info::mi_mbits, lnet_match_info::mi_opc, lnet_match_info::mi_portal, lnet_match_info::mi_rlength, lnet_match_info::mi_roffset, msg, lnet_msg::msg_hdr, lnet_msg::msg_list, lnet_msg::msg_rx_delayed, lnet_match_table::mt_enabled, lnet_process_id_t::nid, lnet_process_id_t::pid, lnet_portal::ptl_msg_delayed, lnet_portal::ptl_msg_stealing, lnet_portal::ptl_mtables, and the_lnet.
Referenced by LNetMDAttach().
void lnet_ptl_detach_md (lnet_me_t * me, lnet_libmd_t * md)
Definition at line 640 of file lib-ptl.c.
References LASSERT, lnet_libmd::md_me, and lnet_me::me_md.
Referenced by lnet_md_unlink(), and lnet_me_unlink().
static int lnet_ptl_is_lazy (lnet_portal_t * ptl) [inline, static]
Definition at line 527 of file lib-lnet.h.
References LNET_PTL_LAZY, and lnet_portal::ptl_options.
Referenced by lnet_clear_lazy_portal(), lnet_mt_match_md(), lnet_ptl_match_delay(), lnet_ptl_match_early(), and lnet_ptl_match_md().
static int lnet_ptl_is_unique (lnet_portal_t * ptl) [inline, static]
Definition at line 533 of file lib-lnet.h.
References LNET_PTL_MATCH_UNIQUE, and lnet_portal::ptl_options.
Referenced by lnet_match2mt(), lnet_mt_match_head(), lnet_mt_of_match(), lnet_ptl_match_early(), lnet_ptl_match_md(), lnet_ptl_match_type(), and LNetMEInsert().
static int lnet_ptl_is_wildcard (lnet_portal_t * ptl) [inline, static]
Definition at line 539 of file lib-lnet.h.
References LNET_PTL_MATCH_WILDCARD, and lnet_portal::ptl_options.
Referenced by lnet_mt_match_head(), lnet_mt_match_md(), lnet_mt_of_match(), lnet_mt_set_exhausted(), lnet_mt_test_exhausted(), lnet_ptl_attach_md(), lnet_ptl_disable_mt(), lnet_ptl_enable_mt(), lnet_ptl_match_delay(), lnet_ptl_match_early(), and lnet_ptl_match_type().
int lnet_ptl_match_md (struct lnet_match_info * info, struct lnet_msg * msg)
Definition at line 563 of file lib-ptl.c.
References CDEBUG, CERROR, D_NET, LASSERT, libcfs_id2str(), list_add_tail(), lnet_t::ln_nportals, lnet_t::ln_portals, lnet_t::ln_shutdown, LNET_CPT_NUMBER, LNET_MATCHMD_DROP, LNET_MATCHMD_EXHAUSTED, LNET_MATCHMD_FINISH, LNET_MATCHMD_NONE, LNET_MD_OP_PUT, lnet_mt_match_md(), lnet_mt_of_match(), lnet_ptl_disable_mt(), lnet_ptl_is_lazy(), lnet_ptl_is_unique(), lnet_ptl_lock, lnet_ptl_match_delay(), lnet_ptl_match_early(), lnet_ptl_unlock, lnet_res_lock(), lnet_res_unlock(), LPX64, lnet_match_info::mi_id, lnet_match_info::mi_mbits, lnet_match_info::mi_opc, lnet_match_info::mi_portal, lnet_match_info::mi_rlength, lnet_match_info::mi_roffset, lnet_msg::msg_list, lnet_msg::msg_rx_delayed, lnet_msg::msg_rx_ready_delay, lnet_match_table::mt_cpt, lnet_match_table::mt_enabled, lnet_portal::ptl_msg_delayed, and the_lnet.
Referenced by lnet_parse_get(), and lnet_parse_put().
static void lnet_ptl_setopt (lnet_portal_t * ptl, int opt) [inline, static]
Definition at line 545 of file lib-lnet.h.
References lnet_portal::ptl_options.
Referenced by lnet_ptl_match_type(), and LNetSetLazyPortal().
static void lnet_ptl_unsetopt (lnet_portal_t * ptl, int opt) [inline, static]
Definition at line 551 of file lib-lnet.h.
References lnet_portal::ptl_options.
Referenced by lnet_clear_lazy_portal().
void lnet_recv (lnet_ni_t * ni, void * private, lnet_msg_t * msg, int delayed, unsigned int offset, unsigned int mlen, unsigned int rlen)
void lnet_recv_delayed_msg_list (struct list_head * head)
Definition at line 2093 of file lib-move.c.
References CDEBUG, D_NET, LASSERT, libcfs_id2str(), list_del(), list_empty(), list_entry, LNET_MSG_PUT, lnet_recv_put(), lnet_peer::lp_ni, LPU64, msg, lnet_msg::msg_hdr, lnet_msg::msg_list, lnet_msg::msg_md, lnet_msg::msg_rx_delayed, lnet_msg::msg_rxpeer, and list_head::next.
Referenced by LNetMDAttach().
void lnet_register_lnd (lnd_t * lnd)
Definition at line 291 of file api-ni.c.
References CDEBUG, D_NET, LASSERT, libcfs_isknown_lnd(), libcfs_lnd2str(), list_add_tail(), lnet_t::ln_lnd_mutex, lnet_t::ln_lnds, lnet_lnd::lnd_list, lnet_lnd::lnd_refcount, lnet_lnd::lnd_type, and lnet_find_lnd_by_type().
Referenced by kgnilnd_init(), ko2iblnd_init(), ksocklnd_init(), and lnet_lib_init().
void lnet_res_lh_initialize (struct lnet_res_container * rec, lnet_libhandle_t * lh)
Definition at line 529 of file api-ni.c.
References lnet_libhandle::lh_cookie, lnet_libhandle::lh_hash_chain, list_add(), LNET_COOKIE_TYPE_BITS, LNET_CPT_BITS, LNET_LH_HASH_MASK, lnet_res_container::rec_lh_cookie, and lnet_res_container::rec_lh_hash.
Referenced by lnet_md_link(), LNetEQAlloc(), LNetMEAttach(), and LNetMEInsert().
static void lnet_res_lh_invalidate (lnet_libhandle_t * lh) [inline, static]
Definition at line 279 of file lib-lnet.h.
References lnet_libhandle::lh_hash_chain, and list_del().
Referenced by lnet_md_unlink(), lnet_me_unlink(), and LNetEQFree().
lnet_libhandle_t* lnet_res_lh_lookup (struct lnet_res_container * rec, __u64 cookie)
Definition at line 507 of file api-ni.c.
References head, lnet_libhandle::lh_cookie, list_for_each_entry, LNET_COOKIE_MASK, LNET_COOKIE_TYPE_BITS, LNET_CPT_BITS, LNET_LH_HASH_MASK, lnet_res_container::rec_lh_hash, and lnet_res_container::rec_type.
Referenced by lnet_handle2eq(), lnet_handle2md(), lnet_handle2me(), and lnet_wire_handle2md().
static void lnet_res_lock (int cpt) [inline, static]
Definition at line 132 of file lib-lnet.h.
References cfs_percpt_lock(), and lnet_t::ln_res_lock.
Referenced by __proc_lnet_portal_rotor(), lnet_clear_lazy_portal(), lnet_create_reply_msg(), lnet_finalize(), lnet_parse_ack(), lnet_parse_reply(), lnet_ptl_match_delay(), lnet_ptl_match_md(), lnet_res_lock_current(), LNetEQAlloc(), LNetEQFree(), LNetGet(), LNetMDAttach(), LNetMDUnlink(), LNetMEAttach(), LNetMEInsert(), LNetMEUnlink(), LNetPut(), and LNetSetLazyPortal().
static int lnet_res_lock_current (void) [inline, static]
Definition at line 144 of file lib-lnet.h.
References lnet_cpt_current, and lnet_res_lock().
Referenced by LNetMDBind().
static void lnet_res_unlock (int cpt) [inline, static]
Definition at line 138 of file lib-lnet.h.
References cfs_percpt_unlock(), and lnet_t::ln_res_lock.
Referenced by __proc_lnet_portal_rotor(), lnet_clear_lazy_portal(), lnet_create_reply_msg(), lnet_finalize(), lnet_parse_ack(), lnet_parse_reply(), lnet_ptl_match_delay(), lnet_ptl_match_md(), LNetEQAlloc(), LNetEQFree(), LNetGet(), LNetMDAttach(), LNetMDBind(), LNetMDUnlink(), LNetMEAttach(), LNetMEInsert(), LNetMEUnlink(), LNetPut(), and LNetSetLazyPortal().
void lnet_return_rx_credits_locked (lnet_msg_t * msg)
Definition at line 1062 of file lib-move.c.
References LASSERT, list_add(), list_del(), list_empty(), list_entry, lnet_t::ln_routing, lnet_destroy_rtrbuf(), lnet_drop_routed_msgs_locked(), lnet_msg2bufpool(), lnet_peer_decref_locked(), lnet_post_routed_recv_locked(), lnet_schedule_blocked_locked(), lnet_peer::lp_rtrcredits, lnet_peer::lp_rtrq, lnet_msg::msg_kiov, lnet_msg::msg_list, lnet_msg::msg_peerrtrcredit, lnet_msg::msg_rtrcredit, lnet_msg::msg_rx_cpt, lnet_msg::msg_rxpeer, list_head::next, lnet_rtrbuf_t::rb_list, lnet_rtrbuf_t::rb_pool, lnet_rtrbufpool_t::rbp_bufs, lnet_rtrbufpool_t::rbp_credits, lnet_rtrbufpool_t::rbp_nbuffers, lnet_rtrbufpool_t::rbp_npages, lnet_rtrbufpool_t::rbp_req_nbuffers, the_lnet, and unlikely.
Referenced by lnet_msg_decommit_rx().
void lnet_return_tx_credits_locked (lnet_msg_t * msg)
Definition at line 967 of file lib-move.c.
References LASSERT, list_del(), list_empty(), list_entry, lnet_peer_decref_locked(), lnet_post_send_locked(), lnet_peer::lp_ni, lnet_peer::lp_txcredits, lnet_peer::lp_txq, lnet_peer::lp_txqnob, lnet_msg::msg_len, lnet_msg::msg_list, lnet_msg::msg_peertxcredit, lnet_msg::msg_tx_cpt, lnet_msg::msg_tx_delayed, lnet_msg::msg_txcredit, lnet_msg::msg_txpeer, list_head::next, lnet_ni::ni_tx_queues, lnet_tx_queue::tq_credits, and lnet_tx_queue::tq_delayed.
Referenced by lnet_msg_decommit_tx().
int lnet_router_checker_start (void)
Definition at line 1054 of file router.c.
References CERROR, check_routers_before_use, dead_router_check_interval, LASSERT, LCONSOLE_ERROR_MSG, lnet_t::ln_rc_eqh, lnet_t::ln_rc_signal, lnet_t::ln_rc_state, LNET_RC_STATE_RUNNING, LNET_RC_STATE_SHUTDOWN, lnet_router_checker(), lnet_router_checker_event(), lnet_wait_known_routerstate(), LNetEQAlloc(), LNetEQFree(), and the_lnet.
Referenced by LNetNIInit().
void lnet_router_checker_stop (void)
Definition at line 1102 of file router.c.
References LASSERT, lnet_t::ln_rc_eqh, lnet_t::ln_rc_signal, lnet_t::ln_rc_state, lnet_t::ln_rc_waitq, LNET_RC_STATE_RUNNING, LNET_RC_STATE_SHUTDOWN, LNET_RC_STATE_STOPPING, LNetEQFree(), and the_lnet.
Referenced by LNetNIFini().
void lnet_router_ni_update_locked (lnet_peer_t * gw, __u32 net)
Definition at line 823 of file router.c.
References list_for_each_entry, LNET_PING_FEAT_NI_STATUS, lnet_peer::lp_ping_feats, lnet_peer::lp_routes, lnet_route_t::lr_downis, and lnet_route_t::lr_net.
Referenced by lnet_parse().
int lnet_rtrpools_adjust (int tiny, int small, int large)
Definition at line 1662 of file router.c.
References lnet_t::ln_routing, lnet_rtrpools_adjust_helper(), and the_lnet.
Referenced by LNetCtl().
int lnet_rtrpools_alloc (int im_a_router)
Definition at line 1540 of file router.c.
References cfs_percpt_alloc(), cfs_percpt_for_each, forwarding, LCONSOLE_ERROR_MSG, lnet_t::ln_routing, lnet_t::ln_rtrpools, lnet_cpt_table, LNET_LARGE_BUF_IDX, LNET_LOCK_EX, lnet_net_lock(), lnet_net_unlock(), lnet_nrb_large_calculate(), LNET_NRB_LARGE_PAGES, lnet_nrb_small_calculate(), LNET_NRB_SMALL_PAGES, lnet_nrb_tiny_calculate(), LNET_NRBPOOLS, lnet_rtrpool_adjust_bufs(), lnet_rtrpool_init(), lnet_rtrpools_free(), LNET_SMALL_BUF_IDX, LNET_TINY_BUF_IDX, and the_lnet.
Referenced by lnet_rtrpools_enable(), and LNetNIInit().
void lnet_rtrpools_disable (void)
Definition at line 1704 of file router.c.
References large_router_buffers, lnet_t::ln_ping_info, lnet_t::ln_routing, LNET_LOCK_EX, lnet_net_lock(), lnet_net_unlock(), LNET_PING_FEAT_RTE_DISABLED, lnet_rtrpools_free(), small_router_buffers, the_lnet, and tiny_router_buffers.
Referenced by LNetCtl().
int lnet_rtrpools_enable (void)
Definition at line 1675 of file router.c.
References lnet_t::ln_ping_info, lnet_t::ln_routing, lnet_t::ln_rtrpools, LNET_LOCK_EX, lnet_net_lock(), lnet_net_unlock(), LNET_PING_FEAT_RTE_DISABLED, lnet_rtrpools_adjust_helper(), lnet_rtrpools_alloc(), and the_lnet.
Referenced by LNetCtl().
void lnet_rtrpools_free (int keep_pools)
Definition at line 1462 of file router.c.
References cfs_percpt_for_each, cfs_percpt_free(), lnet_t::ln_rtrpools, LNET_LARGE_BUF_IDX, lnet_rtrpool_free_bufs(), LNET_SMALL_BUF_IDX, LNET_TINY_BUF_IDX, and the_lnet.
Referenced by lnet_rtrpools_alloc(), lnet_rtrpools_disable(), and lnet_unprepare().
void lnet_schedule_blocked_locked (lnet_rtrbufpool_t * rbp)
Definition at line 1025 of file lib-move.c.
References list_del(), list_empty(), list_entry, lnet_post_routed_recv_locked(), msg, lnet_msg::msg_list, list_head::next, and lnet_rtrbufpool_t::rbp_msgs.
Referenced by lnet_return_rx_credits_locked(), and lnet_rtrpool_adjust_bufs().
int lnet_send (lnet_nid_t nid, lnet_msg_t * msg, lnet_nid_t rtr_nid)
Definition at line 1237 of file lib-move.c.
References CDEBUG, cpu_to_le64, D_NET, LASSERT, LCONSOLE_WARN, libcfs_id2str(), libcfs_nid2str(), lnet_t::ln_loni, lnet_t::ln_shutdown, lnet_cpt_of_nid(), lnet_cpt_of_nid_locked(), LNET_CREDIT_OK, lnet_find_route_locked(), lnet_msg_commit(), lnet_msgtyp2str(), lnet_net2ni_locked(), lnet_net_lock(), lnet_net_unlock(), lnet_ni_decref_locked(), lnet_ni_send(), lnet_nid2ni_locked(), lnet_nid2peer_locked(), LNET_NID_ANY, LNET_NIDNET(), lnet_peer_addref_locked(), LNET_PID_LUSTRE, lnet_post_send_locked(), lnet_peer::lp_ni, lnet_peer::lp_nid, lnet_msg::msg_hdr, lnet_msg::msg_len, lnet_msg::msg_peertxcredit, lnet_msg::msg_receiving, lnet_msg::msg_routing, lnet_msg::msg_sending, lnet_msg::msg_target, lnet_msg::msg_target_is_router, lnet_msg::msg_tx_committed, lnet_msg::msg_txcredit, lnet_msg::msg_txpeer, lnet_msg::msg_type, lnet_ni::ni_nid, lnet_process_id_t::nid, lnet_process_id_t::pid, and the_lnet.
Referenced by lnet_complete_msg_locked(), lnet_parse_get(), LNetGet(), and LNetPut().
void lnet_set_reply_msg_len (lnet_ni_t * ni, lnet_msg_t * msg, unsigned int len)
Definition at line 2331 of file lib-move.c.
References LASSERT, LNET_EVENT_REPLY, LNET_MSG_GET, lnet_event_t::mlength, lnet_msg::msg_ev, lnet_msg::msg_type, and lnet_event_t::type.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_check_rdma_cq(), and kiblnd_handle_completion().
int lnet_sock_accept (struct socket ** newsockp, struct socket * sock)
Definition at line 568 of file lib-socket.c.
References CERROR, and sk_sleep().
Referenced by lnet_acceptor().
int lnet_sock_connect (struct socket ** sockp, int * fatal, __u32 local_ip, int local_port, __u32 peer_ip, int peer_port)
Definition at line 607 of file lib-socket.c.
References CDEBUG_LIMIT, D_NET, D_NETERROR, and lnet_sock_create().
Referenced by lnet_connect().
int lnet_sock_getaddr (struct socket * socket, bool remote, __u32 * ip, int * port)
Definition at line 497 of file lib-socket.c.
References CERROR.
Referenced by ksocknal_accept(), ksocknal_lib_get_conn_addrs(), lnet_accept(), and lnet_acceptor().
int lnet_sock_getbuf (struct socket * socket, int * txbufsize, int * rxbufsize)
Definition at line 524 of file lib-socket.c.
Referenced by ksocknal_lib_get_conn_tunables().
int lnet_sock_listen (struct socket ** sockp, __u32 ip, int port, int backlog)
Definition at line 537 of file lib-socket.c.
References CERROR, fatal(), and lnet_sock_create().
Referenced by lnet_acceptor().
int lnet_sock_read (struct socket * sock, void * buffer, int nob, int timeout)
Definition at line 354 of file lib-socket.c.
References CERROR, and LASSERT.
Referenced by ksocknal_recv_hello(), ksocknal_recv_hello_v1(), ksocknal_recv_hello_v2(), lnet_accept(), and lnet_acceptor().
int lnet_sock_setbuf (struct socket * socket, int txbufsize, int rxbufsize)
Definition at line 466 of file lib-socket.c.
References CERROR.
Referenced by ksocknal_lib_setup_sock().
int lnet_sock_write (struct socket * sock, void * buffer, int nob, int timeout)
Definition at line 287 of file lib-socket.c.
References CERROR, LASSERT, and lnet_sock_write().
Referenced by ksocknal_send_hello_v1(), ksocknal_send_hello_v2(), lnet_accept(), lnet_connect(), and lnet_sock_write().
void lnet_swap_pinginfo (lnet_ping_info_t * info)
Definition at line 629 of file router.c.
References __swab32s, __swab64s, and LNET_MAX_RTR_NIS.
Referenced by lnet_parse_rc_info(), and lnet_ping().
void lnet_unregister_lnd (lnd_t * lnd)
Definition at line 308 of file api-ni.c.
References CDEBUG, D_NET, LASSERT, libcfs_lnd2str(), list_del(), lnet_t::ln_lnd_mutex, lnet_lnd::lnd_list, lnet_lnd::lnd_refcount, lnet_lnd::lnd_type, and lnet_find_lnd_by_type().
Referenced by kgnilnd_exit(), ko2iblnd_exit(), ksocklnd_exit(), and lnet_lib_exit().
static lnet_libmd_t* lnet_wire_handle2md (lnet_handle_wire_t * wh) [inline, static]
Definition at line 333 of file lib-lnet.h.
References lh_entry, lnet_t::ln_interface_cookie, lnet_t::ln_md_containers, lnet_cpt_of_cookie(), and lnet_res_lh_lookup().
Referenced by lnet_parse_ack(), and lnet_parse_reply().
Variable Documentation
int avoid_asym_router_failure
Definition at line 78 of file router.c.
Referenced by lnet_parse(), and lnet_router_checker_event().
int portal_rotor
Definition at line 42 of file lib-ptl.c.
Referenced by __proc_lnet_portal_rotor(), and lnet_mt_of_match().
lnet_t the_lnet
Definition at line 43 of file api-ni.c.
Referenced by __proc_lnet_buffers(), fail_peer(), ksocknal_send_hello(), ksocknal_send_hello_v1(), ksocknal_send_hello_v2(), lnet_add_route(), lnet_add_route_to_rnet(), lnet_build_msg_event(), lnet_check_routes(), lnet_clear_lazy_portal(), lnet_configure(), lnet_connect(), lnet_create_rc_data_locked(), lnet_create_reply_msg(), lnet_del_route(), lnet_delay_rule_add(), lnet_delay_rule_del(), lnet_delay_rule_list(), lnet_delay_rule_match_locked(), lnet_delay_rule_reset(), lnet_destroy_peer_locked(), lnet_drop_message(), lnet_drop_rule_add(), lnet_drop_rule_del(), lnet_drop_rule_list(), lnet_drop_rule_match(), lnet_drop_rule_reset(), lnet_dyn_configure(), lnet_dyn_unconfigure(), lnet_eq_enqueue_event(), lnet_eq_wait_locked(), lnet_fail_nid(), lnet_fault_fini(), lnet_finalize(), lnet_find_net_locked(), lnet_find_peer_locked(), lnet_get_peer_info(), lnet_get_route(), lnet_get_rtr_pool_cfg(), lnet_ioctl(), lnet_md_link(), lnet_msg2bufpool(), lnet_msg_commit(), lnet_msg_containers_create(), lnet_msg_containers_destroy(), lnet_msg_decommit(), lnet_msg_decommit_rx(), lnet_msg_decommit_tx(), lnet_mt_match_head(), lnet_mt_match_md(), lnet_mt_of_attach(), lnet_mt_of_match(), lnet_mt_set_exhausted(), lnet_mt_test_exhausted(), lnet_nid2peer_locked(), lnet_notify(), lnet_parse(), lnet_parse_forward_locked(), lnet_peer_tables_cleanup(), lnet_peer_tables_create(), lnet_peer_tables_destroy(), lnet_ping_router_locked(), lnet_portals_create(), lnet_portals_destroy(), lnet_post_send_locked(), lnet_prep_send(), lnet_prune_rc_data(), lnet_ptl_attach_md(), lnet_ptl_match_md(), lnet_ptl_match_type(), lnet_return_rx_credits_locked(), lnet_router_checker(), lnet_router_checker_active(), lnet_router_checker_start(), lnet_router_checker_stop(), lnet_rtr_addref_locked(), lnet_rtr_decref_locked(), lnet_rtrpools_adjust(), lnet_rtrpools_adjust_helper(), lnet_rtrpools_alloc(), lnet_rtrpools_disable(), lnet_rtrpools_enable(), lnet_rtrpools_free(), lnet_send(), lnet_shuffle_seed(), lnet_unconfigure(), lnet_update_ni_status_locked(), lnet_wait_known_routerstate(), LNetDist(), LNetEQAlloc(), LNetEQFree(), LNetEQPoll(), LNetGet(), LNetMDAttach(), LNetMDBind(), LNetMDUnlink(), LNetMEAttach(), LNetMEInsert(), LNetMEUnlink(), LNetPut(), LNetSetLazyPortal(), proc_lnet_nis(), proc_lnet_peers(), proc_lnet_routers(), and proc_lnet_routes().
lnd_t the_lolnd
Definition at line 108 of file lo.c.
Referenced by lnet_lib_init(), and lolnd_startup().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.