Lustre: lnet/lnet/lib-move.c File Reference
lnet/lnet/lib-move.c File Reference
#include <lnet/lib-lnet.h>
Defines
#define DEBUG_SUBSYSTEM S_LNET
Functions
module_param (local_nid_dist_zero, int, 0444)
MODULE_PARM_DESC (local_nid_dist_zero,"Reserved")
int lnet_fail_nid (lnet_nid_t nid, unsigned int threshold)
static int fail_peer (lnet_nid_t nid, int outgoing)
unsigned int lnet_iov_nob (unsigned int niov, struct kvec *iov)
void lnet_copy_iov2iov (unsigned int ndiov, struct kvec *diov, unsigned int doffset, unsigned int nsiov, struct kvec *siov, unsigned int soffset, unsigned int nob)
int lnet_extract_iov (int dst_niov, struct kvec *dst, int src_niov, struct kvec *src, unsigned int offset, unsigned int len)
unsigned int lnet_kiov_nob (unsigned int niov, lnet_kiov_t *kiov)
void lnet_copy_kiov2kiov (unsigned int ndiov, lnet_kiov_t *diov, unsigned int doffset, unsigned int nsiov, lnet_kiov_t *siov, unsigned int soffset, unsigned int nob)
void lnet_copy_kiov2iov (unsigned int niov, struct kvec *iov, unsigned int iovoffset, unsigned int nkiov, lnet_kiov_t *kiov, unsigned int kiovoffset, unsigned int nob)
void lnet_copy_iov2kiov (unsigned int nkiov, lnet_kiov_t *kiov, unsigned int kiovoffset, unsigned int niov, struct kvec *iov, unsigned int iovoffset, unsigned int nob)
int lnet_extract_kiov (int dst_niov, lnet_kiov_t *dst, int src_niov, lnet_kiov_t *src, unsigned int offset, unsigned int len)
void lnet_ni_recv (lnet_ni_t *ni, void *private, lnet_msg_t *msg, int delayed, unsigned int offset, unsigned int mlen, unsigned int rlen)
static void lnet_setpayloadbuffer (lnet_msg_t *msg)
void lnet_prep_send (lnet_msg_t *msg, int type, lnet_process_id_t target, unsigned int offset, unsigned int len)
static void lnet_ni_send (lnet_ni_t *ni, lnet_msg_t *msg)
static int lnet_ni_eager_recv (lnet_ni_t *ni, lnet_msg_t *msg)
static void lnet_ni_query_locked (lnet_ni_t *ni, lnet_peer_t *lp)
static int lnet_peer_is_alive (lnet_peer_t *lp, cfs_time_t now)
static int lnet_peer_alive_locked (lnet_peer_t *lp)
static int lnet_post_send_locked (lnet_msg_t *msg, int do_send)
static lnet_rtrbufpool_t * lnet_msg2bufpool (lnet_msg_t *msg)
static int lnet_post_routed_recv_locked (lnet_msg_t *msg, int do_recv)
void lnet_return_tx_credits_locked (lnet_msg_t *msg)
void lnet_schedule_blocked_locked (lnet_rtrbufpool_t *rbp)
void lnet_drop_routed_msgs_locked (struct list_head *list, int cpt)
void lnet_return_rx_credits_locked (lnet_msg_t *msg)
static int lnet_compare_routes (lnet_route_t *r1, lnet_route_t *r2)
static lnet_peer_t * lnet_find_route_locked (lnet_ni_t *ni, lnet_nid_t target, lnet_nid_t rtr_nid)
int lnet_send (lnet_nid_t src_nid, lnet_msg_t *msg, lnet_nid_t rtr_nid)
void lnet_drop_message (lnet_ni_t *ni, int cpt, void *private, unsigned int nob)
static void lnet_recv_put (lnet_ni_t *ni, lnet_msg_t *msg)
static int lnet_parse_put (lnet_ni_t *ni, lnet_msg_t *msg)
static int lnet_parse_get (lnet_ni_t *ni, lnet_msg_t *msg, int rdma_get)
static int lnet_parse_reply (lnet_ni_t *ni, lnet_msg_t *msg)
static int lnet_parse_ack (lnet_ni_t *ni, lnet_msg_t *msg)
int lnet_parse_forward_locked (lnet_ni_t *ni, lnet_msg_t *msg)
int lnet_parse_local (lnet_ni_t *ni, lnet_msg_t *msg)
char * lnet_msgtyp2str (int type)
void lnet_print_hdr (lnet_hdr_t *hdr)
int lnet_parse (lnet_ni_t *ni, lnet_hdr_t *hdr, lnet_nid_t from_nid, void *private, int rdma_req)
void lnet_drop_delayed_msg_list (struct list_head *head, char *reason)
void lnet_recv_delayed_msg_list (struct list_head *head)
int LNetPut (lnet_nid_t self, lnet_handle_md_t mdh, lnet_ack_req_t ack, lnet_process_id_t target, unsigned int portal, __u64 match_bits, unsigned int offset, __u64 hdr_data)
Initiate an asynchronous PUT operation.
lnet_msg_t * lnet_create_reply_msg (lnet_ni_t *ni, lnet_msg_t *getmsg)
void lnet_set_reply_msg_len (lnet_ni_t *ni, lnet_msg_t *reply, unsigned int len)
int LNetGet (lnet_nid_t self, lnet_handle_md_t mdh, lnet_process_id_t target, unsigned int portal, __u64 match_bits, unsigned int offset)
Initiate an asynchronous GET operation.
int LNetDist (lnet_nid_t dstnid, lnet_nid_t *srcnidp, __u32 *orderp)
Calculate distance to node at dstnid.
Variables
static int local_nid_dist_zero = 1
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 41 of file lib-move.c.
Function Documentation
static int fail_peer (lnet_nid_t nid, int outgoing) [static]
Definition at line 101 of file lib-move.c.
References INIT_LIST_HEAD, LIBCFS_FREE, list_add(), list_del(), list_empty(), list_entry, list_for_each_safe, lnet_t::ln_test_peers, LNET_MD_THRESH_INF, lnet_net_lock(), lnet_net_unlock(), LNET_NID_ANY, list_head::next, the_lnet, lnet_test_peer_t::tp_list, lnet_test_peer_t::tp_nid, and lnet_test_peer_t::tp_threshold.
Referenced by lnet_parse(), LNetGet(), and LNetPut().
static int lnet_compare_routes (lnet_route_t * r1, lnet_route_t * r2) [static]
Definition at line 1141 of file lib-move.c.
References LNET_UNDEFINED_HOPS, lnet_peer::lp_txcredits, lnet_peer::lp_txqnob, lnet_route_t::lr_gateway, lnet_route_t::lr_hops, lnet_route_t::lr_priority, and lnet_route_t::lr_seq.
Referenced by lnet_find_route_locked().
void lnet_copy_iov2iov (unsigned int ndiov, struct kvec * diov, unsigned int doffset, unsigned int nsiov, struct kvec * siov, unsigned int soffset, unsigned int nob)
Definition at line 172 of file lib-move.c.
References LASSERT, and MIN.
Referenced by lnet_copy_flat2iov(), lnet_copy_iov2flat(), and lolnd_recv().
void lnet_copy_iov2kiov (unsigned int nkiov, lnet_kiov_t * kiov, unsigned int kiovoffset, unsigned int niov, struct kvec * iov, unsigned int iovoffset, unsigned int nob)
Definition at line 444 of file lib-move.c.
References lnet_kiov_t::kiov_len, lnet_kiov_t::kiov_offset, lnet_kiov_t::kiov_page, LASSERT, and MIN.
Referenced by lnet_copy_flat2kiov(), and lolnd_recv().
void lnet_copy_kiov2iov (unsigned int niov, struct kvec * iov, unsigned int iovoffset, unsigned int nkiov, lnet_kiov_t * kiov, unsigned int kiovoffset, unsigned int nob)
Definition at line 374 of file lib-move.c.
References lnet_kiov_t::kiov_len, lnet_kiov_t::kiov_offset, lnet_kiov_t::kiov_page, LASSERT, and MIN.
Referenced by lnet_copy_kiov2flat(), and lolnd_recv().
void lnet_copy_kiov2kiov (unsigned int ndiov, lnet_kiov_t * diov, unsigned int doffset, unsigned int nsiov, lnet_kiov_t * siov, unsigned int soffset, unsigned int nob)
Definition at line 292 of file lib-move.c.
References lnet_kiov_t::kiov_len, lnet_kiov_t::kiov_offset, lnet_kiov_t::kiov_page, LASSERT, and MIN.
Referenced by _kgnilnd_proc_run_cksum_test(), and lolnd_recv().
lnet_msg_t* lnet_create_reply_msg (lnet_ni_t * ni, lnet_msg_t * getmsg)
Definition at line 2254 of file lib-move.c.
References CDEBUG, CERROR, D_NET, lnet_counters::drop_count, lnet_counters::drop_length, LASSERT, lnet_libhandle::lh_cookie, libcfs_id2str(), libcfs_nid2str(), lnet_t::ln_counters, lnet_build_msg_event(), lnet_cpt_of_cookie(), lnet_cpt_of_nid(), LNET_EVENT_REPLY, lnet_msg_alloc(), lnet_msg_attach_md(), lnet_msg_commit(), lnet_msg_free(), LNET_MSG_GET, lnet_net_lock(), lnet_net_unlock(), lnet_res_lock(), lnet_res_unlock(), lnet_libmd::md_length, lnet_libmd::md_lh, lnet_libmd::md_offset, lnet_libmd::md_refcount, lnet_libmd::md_threshold, msg, lnet_msg::msg_from, lnet_msg::msg_hdr, lnet_msg::msg_md, lnet_msg::msg_receiving, lnet_msg::msg_routing, lnet_msg::msg_target, lnet_msg::msg_target_is_router, lnet_msg::msg_type, lnet_ni::ni_nid, lnet_process_id_t::nid, and the_lnet.
Referenced by kgnilnd_send(), and kiblnd_send().
void lnet_drop_delayed_msg_list (struct list_head * head, char * reason)
Definition at line 2051 of file lib-move.c.
References CWARN, LASSERT, libcfs_id2str(), list_del(), list_empty(), list_entry, lnet_drop_message(), lnet_finalize(), LNET_MSG_PUT, lnet_peer::lp_cpt, lnet_peer::lp_ni, LPU64, msg, lnet_msg::msg_hdr, lnet_msg::msg_len, lnet_msg::msg_list, lnet_msg::msg_md, lnet_msg::msg_private, lnet_msg::msg_rx_delayed, lnet_msg::msg_rxpeer, and list_head::next.
Referenced by lnet_clear_lazy_portal(), and LNetMDAttach().
void lnet_drop_message (lnet_ni_t * ni, int cpt, void * private, unsigned int nob)
Definition at line 1409 of file lib-move.c.
References lnet_counters::drop_count, lnet_counters::drop_length, lnet_t::ln_counters, lnet_net_lock(), lnet_net_unlock(), lnet_ni_recv(), and the_lnet.
Referenced by delayed_msg_process(), lnet_drop_delayed_msg_list(), and lnet_parse().
void lnet_drop_routed_msgs_locked (struct list_head * list, int cpt)
Definition at line 1039 of file lib-move.c.
References INIT_LIST_HEAD, list_del_init(), list_for_each_entry_safe, list_splice_init(), lnet_finalize(), lnet_net_lock(), lnet_net_unlock(), lnet_ni_recv(), lnet_peer::lp_ni, msg, lnet_msg::msg_hdr, lnet_msg::msg_list, lnet_msg::msg_private, and lnet_msg::msg_rxpeer.
Referenced by lnet_return_rx_credits_locked(), and lnet_rtrpool_free_bufs().
int lnet_extract_iov (int dst_niov, struct kvec * dst, int src_niov, struct kvec * src, unsigned int offset, unsigned int len)
Definition at line 231 of file lib-move.c.
References LASSERT.
Referenced by ksocknal_recv(), and ksocknal_send().
int lnet_extract_kiov (int dst_niov, lnet_kiov_t * dst, int src_niov, lnet_kiov_t * src, unsigned int offset, unsigned int len)
Definition at line 513 of file lib-move.c.
References lnet_kiov_t::kiov_len, lnet_kiov_t::kiov_offset, lnet_kiov_t::kiov_page, and LASSERT.
Referenced by ksocknal_recv(), and ksocknal_send().
int lnet_fail_nid (lnet_nid_t nid, unsigned int threshold)
Definition at line 50 of file lib-move.c.
References INIT_LIST_HEAD, LIBCFS_ALLOC, LIBCFS_FREE, list_add(), list_add_tail(), list_del(), list_empty(), list_entry, list_for_each_safe, lnet_t::ln_test_peers, lnet_net_lock(), lnet_net_unlock(), LNET_NID_ANY, list_head::next, the_lnet, lnet_test_peer_t::tp_list, lnet_test_peer_t::tp_nid, and lnet_test_peer_t::tp_threshold.
Referenced by lnet_unprepare(), and LNetCtl().
static lnet_peer_t* lnet_find_route_locked (lnet_ni_t * ni, lnet_nid_t target, lnet_nid_t rtr_nid) [static]
Definition at line 1179 of file lib-move.c.
References list_for_each_entry, lnet_compare_routes(), lnet_find_net_locked(), lnet_is_route_alive(), LNET_NIDNET(), lnet_peer::lp_ni, lnet_peer::lp_nid, lnet_route_t::lr_gateway, lnet_route_t::lr_seq, and lnet_remotenet_t::lrn_routes.
Referenced by lnet_send().
unsigned int lnet_iov_nob (unsigned int niov, struct kvec * iov)
Definition at line 159 of file lib-move.c.
References LASSERT.
Referenced by ksocknal_queue_tx_locked(), and ksocknal_recv().
unsigned int lnet_kiov_nob (unsigned int niov, lnet_kiov_t * kiov)
Definition at line 279 of file lib-move.c.
References LASSERT.
Referenced by ksocknal_queue_tx_locked(), and ksocknal_recv().
static lnet_rtrbufpool_t* lnet_msg2bufpool (lnet_msg_t * msg) [static]
Definition at line 873 of file lib-move.c.
References LASSERT, lnet_t::ln_rtrpools, LNET_MTU, LNET_NRBPOOLS, lnet_msg::msg_len, lnet_msg::msg_rx_committed, lnet_msg::msg_rx_cpt, lnet_rtrbufpool_t::rbp_npages, and the_lnet.
Referenced by lnet_parse_forward_locked(), lnet_post_routed_recv_locked(), and lnet_return_rx_credits_locked().
char* lnet_msgtyp2str (int type)
Definition at line 1734 of file lib-move.c.
References LNET_MSG_ACK, LNET_MSG_GET, LNET_MSG_HELLO, LNET_MSG_PUT, and LNET_MSG_REPLY.
Referenced by lnet_finalize(), lnet_parse(), lnet_print_hdr(), and lnet_send().
static int lnet_ni_eager_recv (lnet_ni_t * ni, lnet_msg_t * msg) [static]
Definition at line 656 of file lib-move.c.
References CERROR, LASSERT, libcfs_id2str(), libcfs_nid2str(), lnet_lnd::lnd_eager_recv, lnet_peer::lp_nid, lnet_msg::msg_private, lnet_msg::msg_receiving, lnet_msg::msg_rx_ready_delay, lnet_msg::msg_rxpeer, lnet_msg::msg_sending, lnet_msg::msg_target, and lnet_ni::ni_lnd.
Referenced by lnet_parse_forward_locked(), and lnet_parse_put().
static void lnet_ni_query_locked (lnet_ni_t * ni, lnet_peer_t * lp) [static]
Definition at line 681 of file lib-move.c.
References cfs_time_current(), LASSERT, lnet_lnd::lnd_query, lnet_net_lock(), lnet_net_unlock(), lnet_peer_aliveness_enabled, lnet_peer::lp_cpt, lnet_peer::lp_last_alive, lnet_peer::lp_last_query, lnet_peer::lp_nid, and lnet_ni::ni_lnd.
Referenced by lnet_peer_alive_locked().
void lnet_ni_recv (lnet_ni_t * ni, void * private, lnet_msg_t * msg, int delayed, unsigned int offset, unsigned int mlen, unsigned int rlen)
Definition at line 563 of file lib-move.c.
References LASSERT, lnet_lnd::lnd_recv, lnet_finalize(), lnet_msg::msg_iov, lnet_msg::msg_kiov, lnet_msg::msg_len, lnet_msg::msg_niov, lnet_msg::msg_offset, lnet_msg::msg_receiving, lnet_msg::msg_sending, lnet_msg::msg_wanted, and lnet_ni::ni_lnd.
Referenced by delayed_msg_process(), lnet_drop_message(), lnet_drop_routed_msgs_locked(), lnet_parse(), lnet_parse_ack(), lnet_parse_get(), lnet_parse_reply(), lnet_post_routed_recv_locked(), and lnet_recv_put().
static void lnet_ni_send (lnet_ni_t * ni, lnet_msg_t * msg) [static]
Definition at line 641 of file lib-move.c.
References LASSERT, lnet_lnd::lnd_send, lnet_finalize(), LNET_NETTYP(), LNET_NIDNET(), LOLND, lnet_msg::msg_peertxcredit, lnet_msg::msg_private, lnet_msg::msg_txcredit, lnet_ni::ni_lnd, and lnet_ni::ni_nid.
Referenced by lnet_post_send_locked(), and lnet_send().
int lnet_parse (lnet_ni_t * ni, lnet_hdr_t * hdr, lnet_nid_t from_nid, void * private, int rdma_req)
Definition at line 1815 of file lib-move.c.
References avoid_asym_router_failure, CDEBUG, CERROR, cfs_time_current_sec(), D_NET, fail_peer(), LASSERT, le32_to_cpu, le64_to_cpu, libcfs_nid2str(), list_empty(), lnet_t::ln_delay_rules, lnet_t::ln_drop_rules, lnet_t::ln_routing, lnet_t::ln_test_peers, lnet_cpt_of_nid(), LNET_CREDIT_OK, lnet_delay_rule_match_locked(), lnet_drop_message(), lnet_drop_rule_match(), lnet_finalize(), lnet_islocalnid(), lnet_isrouter(), LNET_MAX_PAYLOAD, LNET_MSG_ACK, lnet_msg_alloc(), lnet_msg_commit(), lnet_msg_free(), LNET_MSG_GET, LNET_MSG_PUT, LNET_MSG_REPLY, lnet_msgtyp2str(), LNET_MTU, lnet_net_lock(), lnet_net_unlock(), lnet_ni_lock, lnet_ni_recv(), LNET_NI_STATUS_DOWN, LNET_NI_STATUS_UP, lnet_ni_unlock, lnet_nid2peer_locked(), LNET_NIDNET(), lnet_parse_forward_locked(), lnet_parse_local(), lnet_peer_set_alive(), lnet_router_ni_update_locked(), msg, lnet_msg::msg_from, lnet_msg::msg_hdr, lnet_msg::msg_len, lnet_msg::msg_md, lnet_msg::msg_offset, lnet_msg::msg_private, lnet_msg::msg_rdma_get, lnet_msg::msg_receiving, lnet_msg::msg_routing, lnet_msg::msg_rxpeer, lnet_msg::msg_target, lnet_msg::msg_type, lnet_msg::msg_wanted, lnet_ni::ni_last_alive, lnet_ni::ni_nid, lnet_ni::ni_status, lnet_process_id_t::nid, lnet_process_id_t::pid, the_lnet, and unlikely.
Referenced by kgnilnd_check_fma_rx(), kiblnd_handle_rx(), ksocknal_process_receive(), and lolnd_send().
static int lnet_parse_ack (lnet_ni_t * ni, lnet_msg_t * msg) [static]
Definition at line 1628 of file lib-move.c.
References CDEBUG, CERROR, D_NET, le32_to_cpu, le64_to_cpu, libcfs_id2str(), libcfs_nid2str(), lnet_build_msg_event(), lnet_cpt_of_cookie(), LNET_EVENT_ACK, lnet_msg_attach_md(), lnet_ni_recv(), lnet_res_lock(), lnet_res_unlock(), lnet_wire_handle2md(), LPX64, lnet_libmd::md_me, lnet_libmd::md_threshold, lnet_me::me_portal, lnet_msg::msg_hdr, lnet_msg::msg_len, lnet_msg::msg_private, lnet_ni::ni_nid, lnet_process_id_t::nid, and lnet_process_id_t::pid.
Referenced by lnet_parse_local().
int lnet_parse_forward_locked (lnet_ni_t * ni, lnet_msg_t * msg)
Return values:
LNET_CREDIT_OK If msg is forwarded
LNET_CREDIT_WAIT If msg is blocked because w/o buffer
-ve error code
Definition at line 1683 of file lib-move.c.
References lnet_t::ln_routing, lnet_lnd::lnd_eager_recv, lnet_msg2bufpool(), lnet_net_lock(), lnet_net_unlock(), lnet_ni_eager_recv(), lnet_post_routed_recv_locked(), lnet_peer::lp_rtrcredits, lnet_msg::msg_rx_cpt, lnet_msg::msg_rx_ready_delay, lnet_msg::msg_rxpeer, lnet_ni::ni_lnd, and the_lnet.
Referenced by delayed_msg_process(), and lnet_parse().
static int lnet_parse_get (lnet_ni_t * ni, lnet_msg_t * msg, int rdma_get) [static]
Definition at line 1496 of file lib-move.c.
References CERROR, CNETERR, LASSERT, le32_to_cpu, le64_to_cpu, libcfs_id2str(), libcfs_nid2str(), lnet_build_msg_event(), LNET_EVENT_GET, lnet_finalize(), LNET_MATCHMD_DROP, LNET_MATCHMD_OK, LNET_MD_OP_GET, LNET_MSG_REPLY, lnet_ni_recv(), LNET_NID_ANY, lnet_prep_send(), lnet_ptl_match_md(), lnet_send(), LPU64, lnet_match_info::mi_id, lnet_match_info::mi_mbits, lnet_match_info::mi_opc, lnet_match_info::mi_portal, lnet_match_info::mi_rlength, lnet_match_info::mi_roffset, lnet_msg::msg_hdr, lnet_msg::msg_len, lnet_msg::msg_offset, lnet_msg::msg_private, lnet_msg::msg_receiving, lnet_msg::msg_wanted, lnet_ni::ni_nid, lnet_process_id_t::nid, and lnet_process_id_t::pid.
Referenced by lnet_parse_local().
int lnet_parse_local (lnet_ni_t * ni, lnet_msg_t * msg)
Definition at line 1707 of file lib-move.c.
References LASSERT, LNET_MSG_ACK, LNET_MSG_GET, LNET_MSG_PUT, LNET_MSG_REPLY, lnet_parse_ack(), lnet_parse_get(), lnet_parse_put(), lnet_parse_reply(), lnet_msg::msg_rdma_get, and lnet_msg::msg_type.
Referenced by delayed_msg_process(), and lnet_parse().
static int lnet_parse_put (lnet_ni_t * ni, lnet_msg_t * msg) [static]
Definition at line 1439 of file lib-move.c.
References CNETERR, LBUG, le32_to_cpu, le64_to_cpu, libcfs_id2str(), lnet_lnd::lnd_eager_recv, LNET_MATCHMD_DROP, LNET_MATCHMD_NONE, LNET_MATCHMD_OK, LNET_MD_OP_PUT, lnet_ni_eager_recv(), lnet_ptl_match_md(), lnet_recv_put(), LPU64, lnet_match_info::mi_id, lnet_match_info::mi_mbits, lnet_match_info::mi_opc, lnet_match_info::mi_portal, lnet_match_info::mi_rlength, lnet_match_info::mi_roffset, lnet_msg::msg_hdr, lnet_msg::msg_rx_ready_delay, lnet_ni::ni_lnd, lnet_process_id_t::nid, and lnet_process_id_t::pid.
Referenced by lnet_parse_local().
static int lnet_parse_reply (lnet_ni_t * ni, lnet_msg_t * msg) [static]
Definition at line 1561 of file lib-move.c.
References CDEBUG, CERROR, CNETERR, D_NET, LASSERT, libcfs_id2str(), libcfs_nid2str(), lnet_build_msg_event(), lnet_cpt_of_cookie(), LNET_EVENT_REPLY, LNET_MD_TRUNCATE, lnet_msg_attach_md(), lnet_ni_recv(), lnet_res_lock(), lnet_res_unlock(), lnet_setpayloadbuffer(), lnet_wire_handle2md(), LPX64, lnet_libmd::md_length, lnet_libmd::md_me, lnet_libmd::md_offset, lnet_libmd::md_options, lnet_libmd::md_threshold, lnet_me::me_portal, MIN, lnet_msg::msg_hdr, lnet_msg::msg_private, lnet_ni::ni_nid, lnet_process_id_t::nid, and lnet_process_id_t::pid.
Referenced by lnet_parse_local().
static int lnet_peer_alive_locked (lnet_peer_t * lp) [static]
Definition at line 733 of file lib-move.c.
References cfs_time_add(), cfs_time_before(), cfs_time_current(), cfs_time_seconds(), CWARN, libcfs_nid2str(), lnet_ni_query_locked(), lnet_notify_locked(), lnet_peer_aliveness_enabled, lnet_peer_is_alive(), lnet_peer::lp_alive, lnet_peer::lp_last_alive, lnet_peer::lp_last_query, lnet_peer::lp_ni, lnet_peer::lp_nid, lnet_ni::ni_peertimeout, and now().
Referenced by lnet_post_send_locked().
static int lnet_peer_is_alive (lnet_peer_t * lp, cfs_time_t now) [inline, static]
Definition at line 700 of file lib-move.c.
References cfs_time_add(), cfs_time_after(), cfs_time_aftereq(), cfs_time_seconds(), LASSERT, lnet_isrouter(), lnet_notify_locked(), lnet_peer_aliveness_enabled, lnet_peer::lp_alive, lnet_peer::lp_alive_count, lnet_peer::lp_last_alive, lnet_peer::lp_ni, lnet_peer::lp_timestamp, and lnet_ni::ni_peertimeout.
Referenced by lnet_peer_alive_locked().
static int lnet_post_routed_recv_locked (lnet_msg_t * msg, int do_recv) [static]
Definition at line 893 of file lib-move.c.
References LASSERT, list_add_tail(), list_del(), list_empty(), list_entry, LNET_CREDIT_OK, LNET_CREDIT_WAIT, lnet_msg2bufpool(), lnet_net_lock(), lnet_net_unlock(), lnet_ni_recv(), lnet_peer::lp_minrtrcredits, lnet_peer::lp_ni, lnet_peer::lp_rtrcredits, lnet_peer::lp_rtrq, lnet_msg::msg_iov, lnet_msg::msg_kiov, lnet_msg::msg_len, lnet_msg::msg_list, lnet_msg::msg_niov, lnet_msg::msg_peerrtrcredit, lnet_msg::msg_private, lnet_msg::msg_receiving, lnet_msg::msg_routing, lnet_msg::msg_rtrcredit, lnet_msg::msg_rx_cpt, lnet_msg::msg_rx_delayed, lnet_msg::msg_rx_ready_delay, lnet_msg::msg_rxpeer, lnet_msg::msg_sending, list_head::next, lnet_rtrbuf_t::rb_kiov, lnet_rtrbuf_t::rb_list, lnet_rtrbufpool_t::rbp_bufs, lnet_rtrbufpool_t::rbp_credits, lnet_rtrbufpool_t::rbp_mincredits, lnet_rtrbufpool_t::rbp_msgs, and lnet_rtrbufpool_t::rbp_npages.
Referenced by lnet_parse_forward_locked(), lnet_return_rx_credits_locked(), and lnet_schedule_blocked_locked().
static int lnet_post_send_locked (lnet_msg_t * msg, int do_send) [static]
Parameters:
msg The message to be sent.
do_send True if lnet_ni_send() should be called in this function. lnet_send() is going to lnet_net_unlock immediately after this, so it sets do_send FALSE and I don't do the unlock/send/lock bit.
Return values:
LNET_CREDIT_OK If msg sent or OK to send.
LNET_CREDIT_WAIT If msg blocked for credit.
-EHOSTUNREACH If the next hop of the message appears dead.
-ECANCELED If the MD of the message has been unlinked.
Definition at line 786 of file lib-move.c.
References CNETERR, lnet_counters::drop_count, lnet_counters::drop_length, LASSERT, libcfs_id2str(), list_add_tail(), list_empty(), lnet_t::ln_counters, LNET_CREDIT_OK, LNET_CREDIT_WAIT, lnet_finalize(), LNET_MD_FLAG_ABORTED, lnet_net_lock(), lnet_net_unlock(), lnet_ni_send(), lnet_peer_alive_locked(), LNET_PID_USERFLAG, lnet_peer::lp_mintxcredits, lnet_peer::lp_ni, lnet_peer::lp_txcredits, lnet_peer::lp_txq, lnet_peer::lp_txqnob, lnet_libmd::md_flags, lnet_msg::msg_len, lnet_msg::msg_list, lnet_msg::msg_md, lnet_msg::msg_peertxcredit, lnet_msg::msg_receiving, lnet_msg::msg_target, lnet_msg::msg_tx_committed, lnet_msg::msg_tx_cpt, lnet_msg::msg_tx_delayed, lnet_msg::msg_txcredit, lnet_msg::msg_txpeer, lnet_ni::ni_tx_queues, lnet_process_id_t::pid, the_lnet, lnet_tx_queue::tq_credits, lnet_tx_queue::tq_credits_min, and lnet_tx_queue::tq_delayed.
Referenced by lnet_return_tx_credits_locked(), and lnet_send().
void lnet_prep_send (lnet_msg_t * msg, int type, lnet_process_id_t target, unsigned int offset, unsigned int len)
Definition at line 620 of file lib-move.c.
References cpu_to_le32, cpu_to_le64, lnet_t::ln_pid, lnet_setpayloadbuffer(), lnet_msg::msg_hdr, lnet_msg::msg_len, lnet_msg::msg_offset, lnet_msg::msg_target, lnet_msg::msg_type, lnet_process_id_t::nid, lnet_process_id_t::pid, and the_lnet.
Referenced by lnet_complete_msg_locked(), lnet_parse_get(), LNetGet(), and LNetPut().
void lnet_print_hdr (lnet_hdr_t * hdr)
Definition at line 1753 of file lib-move.c.
References CWARN, libcfs_id2str(), LNET_MSG_ACK, LNET_MSG_GET, LNET_MSG_PUT, LNET_MSG_REPLY, lnet_msgtyp2str(), LPU64, LPX64, lnet_process_id_t::nid, and lnet_process_id_t::pid.
void lnet_recv_delayed_msg_list (struct list_head * head)
Definition at line 2093 of file lib-move.c.
References CDEBUG, D_NET, LASSERT, libcfs_id2str(), list_del(), list_empty(), list_entry, LNET_MSG_PUT, lnet_recv_put(), lnet_peer::lp_ni, LPU64, msg, lnet_msg::msg_hdr, lnet_msg::msg_list, lnet_msg::msg_md, lnet_msg::msg_rx_delayed, lnet_msg::msg_rxpeer, and list_head::next.
Referenced by LNetMDAttach().
static void lnet_recv_put (lnet_ni_t * ni, lnet_msg_t * msg) [static]
Definition at line 1420 of file lib-move.c.
References lnet_build_msg_event(), LNET_EVENT_PUT, lnet_is_wire_handle_none(), LNET_MD_ACK_DISABLE, lnet_ni_recv(), lnet_setpayloadbuffer(), lnet_libmd::md_options, lnet_msg::msg_ack, lnet_msg::msg_hdr, lnet_msg::msg_md, lnet_msg::msg_offset, lnet_msg::msg_private, lnet_msg::msg_rx_delayed, and lnet_msg::msg_wanted.
Referenced by lnet_parse_put(), and lnet_recv_delayed_msg_list().
void lnet_return_rx_credits_locked (lnet_msg_t * msg)
Definition at line 1062 of file lib-move.c.
References LASSERT, list_add(), list_del(), list_empty(), list_entry, lnet_t::ln_routing, lnet_destroy_rtrbuf(), lnet_drop_routed_msgs_locked(), lnet_msg2bufpool(), lnet_peer_decref_locked(), lnet_post_routed_recv_locked(), lnet_schedule_blocked_locked(), lnet_peer::lp_rtrcredits, lnet_peer::lp_rtrq, lnet_msg::msg_kiov, lnet_msg::msg_list, lnet_msg::msg_peerrtrcredit, lnet_msg::msg_rtrcredit, lnet_msg::msg_rx_cpt, lnet_msg::msg_rxpeer, list_head::next, lnet_rtrbuf_t::rb_list, lnet_rtrbuf_t::rb_pool, lnet_rtrbufpool_t::rbp_bufs, lnet_rtrbufpool_t::rbp_credits, lnet_rtrbufpool_t::rbp_nbuffers, lnet_rtrbufpool_t::rbp_npages, lnet_rtrbufpool_t::rbp_req_nbuffers, the_lnet, and unlikely.
Referenced by lnet_msg_decommit_rx().
void lnet_return_tx_credits_locked (lnet_msg_t * msg)
Definition at line 967 of file lib-move.c.
References LASSERT, list_del(), list_empty(), list_entry, lnet_peer_decref_locked(), lnet_post_send_locked(), lnet_peer::lp_ni, lnet_peer::lp_txcredits, lnet_peer::lp_txq, lnet_peer::lp_txqnob, lnet_msg::msg_len, lnet_msg::msg_list, lnet_msg::msg_peertxcredit, lnet_msg::msg_tx_cpt, lnet_msg::msg_tx_delayed, lnet_msg::msg_txcredit, lnet_msg::msg_txpeer, list_head::next, lnet_ni::ni_tx_queues, lnet_tx_queue::tq_credits, and lnet_tx_queue::tq_delayed.
Referenced by lnet_msg_decommit_tx().
void lnet_schedule_blocked_locked (lnet_rtrbufpool_t * rbp)
Definition at line 1025 of file lib-move.c.
References list_del(), list_empty(), list_entry, lnet_post_routed_recv_locked(), msg, lnet_msg::msg_list, list_head::next, and lnet_rtrbufpool_t::rbp_msgs.
Referenced by lnet_return_rx_credits_locked(), and lnet_rtrpool_adjust_bufs().
int lnet_send (lnet_nid_t src_nid, lnet_msg_t * msg, lnet_nid_t rtr_nid)
Definition at line 1237 of file lib-move.c.
References CDEBUG, cpu_to_le64, D_NET, LASSERT, LCONSOLE_WARN, libcfs_id2str(), libcfs_nid2str(), lnet_t::ln_loni, lnet_t::ln_shutdown, lnet_cpt_of_nid(), lnet_cpt_of_nid_locked(), LNET_CREDIT_OK, lnet_find_route_locked(), lnet_msg_commit(), lnet_msgtyp2str(), lnet_net2ni_locked(), lnet_net_lock(), lnet_net_unlock(), lnet_ni_decref_locked(), lnet_ni_send(), lnet_nid2ni_locked(), lnet_nid2peer_locked(), LNET_NID_ANY, LNET_NIDNET(), lnet_peer_addref_locked(), LNET_PID_LUSTRE, lnet_post_send_locked(), lnet_peer::lp_ni, lnet_peer::lp_nid, lnet_msg::msg_hdr, lnet_msg::msg_len, lnet_msg::msg_peertxcredit, lnet_msg::msg_receiving, lnet_msg::msg_routing, lnet_msg::msg_sending, lnet_msg::msg_target, lnet_msg::msg_target_is_router, lnet_msg::msg_tx_committed, lnet_msg::msg_txcredit, lnet_msg::msg_txpeer, lnet_msg::msg_type, lnet_ni::ni_nid, lnet_process_id_t::nid, lnet_process_id_t::pid, and the_lnet.
Referenced by lnet_complete_msg_locked(), lnet_parse_get(), LNetGet(), and LNetPut().
void lnet_set_reply_msg_len (lnet_ni_t * ni, lnet_msg_t * reply, unsigned int len)
Definition at line 2331 of file lib-move.c.
References LASSERT, LNET_EVENT_REPLY, LNET_MSG_GET, lnet_event_t::mlength, lnet_msg::msg_ev, lnet_msg::msg_type, and lnet_event_t::type.
Referenced by kgnilnd_check_fma_rx(), kgnilnd_check_rdma_cq(), and kiblnd_handle_completion().
static void lnet_setpayloadbuffer (lnet_msg_t * msg) [static]
Definition at line 601 of file lib-move.c.
References lnet_libmd::iov, lnet_libmd::kiov, LASSERT, LNET_MD_KIOV, lnet_libmd::md_iov, lnet_libmd::md_niov, lnet_libmd::md_options, lnet_msg::msg_iov, lnet_msg::msg_kiov, lnet_msg::msg_len, lnet_msg::msg_md, lnet_msg::msg_niov, and lnet_msg::msg_routing.
Referenced by lnet_parse_reply(), lnet_prep_send(), and lnet_recv_put().
module_param (local_nid_dist_zero , int , 0444)
MODULE_PARM_DESC (local_nid_dist_zero , "Reserved")
Variable Documentation
int local_nid_dist_zero = 1 [static]
Definition at line 45 of file lib-move.c.
Referenced by LNetDist().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.