Lustre: lnet/lnet/lib-me.c File Reference
lnet/lnet/lib-me.c File Reference
#include <lnet/lib-lnet.h>
Defines
#define DEBUG_SUBSYSTEM S_LNET
Functions
int LNetMEAttach (unsigned int portal, lnet_process_id_t match_id, __u64 match_bits, __u64 ignore_bits, lnet_unlink_t unlink, lnet_ins_pos_t pos, lnet_handle_me_t *handle)
Create and attach a match entry to the match list of portal.
int LNetMEInsert (lnet_handle_me_t current_meh, lnet_process_id_t match_id, __u64 match_bits, __u64 ignore_bits, lnet_unlink_t unlink, lnet_ins_pos_t pos, lnet_handle_me_t *handle)
Create and a match entry and insert it before or after the ME pointed to by current_meh.
int LNetMEUnlink (lnet_handle_me_t meh)
Unlink a match entry from its match list.
void lnet_me_unlink (lnet_me_t *me)
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 41 of file lib-me.c.
Function Documentation
void lnet_me_unlink (lnet_me_t * me)
Definition at line 263 of file lib-me.c.
References list_del(), lnet_md_unlink(), lnet_me_free(), lnet_ptl_detach_md(), lnet_res_lh_invalidate(), lnet_me::me_lh, lnet_me::me_list, and lnet_me::me_md.
Referenced by lnet_md_unlink(), and LNetMEUnlink().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.