Lustre: libcfs/libcfs/util/nidstrings.c File Reference
libcfs/libcfs/util/nidstrings.c File Reference
#include <assert.h>
#include <errno.h>
#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <lnet/types.h>
#include <lnet/nidstr.h>
Data Structures
struct nidrange
Nid range list syntax.
struct addrrange
Structure to represent <addrrange> token of the syntax.
Defines
#define DEBUG_SUBSYSTEM S_LNET
#define MAX_NUMERIC_VALUE 0xffffffff
#define IPSTRING_LENGTH 16
Functions
char * libcfs_next_nidstring (void)
static int libcfs_lo_str2addr (const char *str, int nob, __u32 *addr)
static void libcfs_ip_addr2str (__u32 addr, char *str, size_t size)
static int libcfs_ip_str2addr (const char *str, int nob, __u32 *addr)
int cfs_ip_addr_parse (char *str, int len, struct list_head *list)
static int libcfs_ip_addr_range_print (char *buffer, int count, struct list_head *list)
int cfs_ip_addr_match (__u32 addr, struct list_head *list)
Matches address (addr) against address set encoded in list.
static void libcfs_decnum_addr2str (__u32 addr, char *str, size_t size)
static void libcfs_hexnum_addr2str (__u32 addr, char *str, size_t size)
static int libcfs_num_str2addr (const char *str, int nob, __u32 *addr)
static int libcfs_num_parse (char *str, int len, struct list_head *list)
Nf_parse_addrlist method for networks using numeric addresses.
static int libcfs_num_addr_range_print (char *buffer, int count, struct list_head *list)
static int libcfs_num_match (__u32 addr, struct list_head *numaddr)
static bool cfs_ip_is_contiguous (struct list_head *nidlist)
Determines whether an expression list in an ip nidrange contains exactly one contiguous address range.
static void cfs_ip_min_max (struct list_head *nidlist, __u32 *min_nid, __u32 *max_nid)
Takes an nidlist and determines the minimum and maximum ip addresses.
static bool cfs_num_is_contiguous (struct list_head *nidlist)
Determines whether an expression list in an num nidrange contains exactly one contiguous address range.
static void cfs_num_min_max (struct list_head *nidlist, __u32 *min_nid, __u32 *max_nid)
Determines the min and max NID values for num LNDs.
static struct netstrfns * libcfs_lnd2netstrfns (__u32 lnd)
static struct netstrfns * libcfs_namenum2netstrfns (const char *name)
static struct netstrfns * libcfs_name2netstrfns (const char *name)
int libcfs_isknown_lnd (__u32 lnd)
char * libcfs_lnd2modname (__u32 lnd)
int libcfs_str2lnd (const char *str)
char * libcfs_lnd2str_r (__u32 lnd, char *buf, size_t buf_size)
char * libcfs_net2str_r (__u32 net, char *buf, size_t buf_size)
char * libcfs_nid2str_r (lnet_nid_t nid, char *buf, size_t buf_size)
static struct netstrfns * libcfs_str2net_internal (const char *str, __u32 *net)
__u32 libcfs_str2net (const char *str)
lnet_nid_t libcfs_str2nid (const char *str)
char * libcfs_id2str (lnet_process_id_t id)
int libcfs_str2anynid (lnet_nid_t *nidp, const char *str)
static int parse_addrange (const struct cfs_lstr *src, struct nidrange *nidrange)
Parses <addrrange> token on the syntax.
static struct nidrange * add_nidrange (const struct cfs_lstr *src, struct list_head *nidlist)
Finds or creates struct nidrange.
static int parse_nidrange (struct cfs_lstr *src, struct list_head *nidlist)
Parses <nidrange> token of the syntax.
static void free_addrranges (struct list_head *list)
Frees addrrange structures of list.
void cfs_free_nidlist (struct list_head *list)
Frees nidrange strutures of list.
int cfs_parse_nidlist (char *str, int len, struct list_head *nidlist)
Parses nid range list.
int cfs_match_nid (lnet_nid_t nid, struct list_head *nidlist)
Matches a nid (nid) against the compiled list of nidranges (nidlist).
static int cfs_print_network (char *buffer, int count, struct nidrange *nr)
Print the network part of the nidrange nr into the specified buffer.
static int cfs_print_addrranges (char *buffer, int count, struct list_head *addrranges, struct nidrange *nr)
Print a list of addrrange (addrranges) into the specified buffer.
int cfs_print_nidlist (char *buffer, int count, struct list_head *nidlist)
Print a list of nidranges (nidlist) into the specified buffer.
static void cfs_ip_ar_min_max (struct addrrange *ar, __u32 *min_nid, __u32 *max_nid)
Determines minimum and maximum addresses for a single numeric address range.
static void cfs_num_ar_min_max (struct addrrange *ar, __u32 *min_nid, __u32 *max_nid)
Determines minimum and maximum addresses for a single numeric address range.
bool cfs_nidrange_is_contiguous (struct list_head *nidlist)
Determines whether an expression list in an nidrange contains exactly one contiguous address range.
void cfs_nidrange_find_min_max (struct list_head *nidlist, char *min_nid, char *max_nid, size_t nidstr_length)
Takes a linked list of nidrange expressions, determines the minimum and maximum nid and creates appropriate nid structures.
Variables
static char libcfs_nidstrings [LNET_NIDSTR_COUNT][LNET_NIDSTR_SIZE]
static int libcfs_nidstring_idx
static struct netstrfns libcfs_netstrfns []
static const size_t libcfs_nnetstrfns
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 41 of file nidstrings.c.
#define IPSTRING_LENGTH 16
Definition at line 60 of file nidstrings.c.
#define MAX_NUMERIC_VALUE 0xffffffff
Definition at line 58 of file nidstrings.c.
Function Documentation
static struct nidrange* add_nidrange (const struct cfs_lstr * src, struct list_head * nidlist) [static, read]
Finds or creates struct nidrange.
Checks if src is a valid network name, looks for corresponding nidrange on the ist of nidranges (nidlist), creates new struct nidrange if it is not found.
Return values:
pointer to struct nidrange matching network specified via src
NULL if src does not match any network
Definition at line 804 of file nidstrings.c.
References cfs_str2num_check(), INIT_LIST_HEAD, libcfs_namenum2netstrfns(), list_add_tail(), list_for_each_entry, LNET_NIDSTR_SIZE, cfs_lstr::ls_len, cfs_lstr::ls_str, MAX_NUMERIC_VALUE, netstrfns::nf_name, nidrange::nr_addrranges, nidrange::nr_all, nidrange::nr_link, nidrange::nr_netnum, and nidrange::nr_netstrfns.
Referenced by parse_nidrange().
void cfs_free_nidlist (struct list_head * list)
Frees nidrange strutures of list.
For each struct nidrange structure found on list it frees addrrange list attached to it and frees the nidrange itself.
Return values:
none
Definition at line 917 of file nidstrings.c.
References free_addrranges(), list_del(), list_entry, list_for_each_safe, list_head::next, nidrange::nr_addrranges, and nidrange::nr_link.
Referenced by cfs_parse_nidlist(), ll_free_sbi(), lmd_parse_nidlist(), mdt_fini(), and parse_nids().
int cfs_ip_addr_match (__u32 addr, struct list_head * list)
Matches address (addr) against address set encoded in list.
Return values:
1 if addr matches
0 otherwise
Definition at line 218 of file nidstrings.c.
References cfs_expr_list_match(), cfs_expr_list::el_link, and list_for_each_entry_reverse.
Referenced by lnet_match_network_token().
int cfs_ip_addr_parse (char * str, int len, struct list_head * list)
Definition at line 159 of file nidstrings.c.
References cfs_expr_list_free_list(), cfs_expr_list_parse(), cfs_gettok(), cfs_expr_list::el_link, list_add_tail(), cfs_lstr::ls_len, and cfs_lstr::ls_str.
Referenced by lnet_match_network_token().
static void cfs_ip_ar_min_max (struct addrrange * ar, __u32 * min_nid, __u32 * max_nid) [static]
Determines minimum and maximum addresses for a single numeric address range.
Parameters:
ar
min_nid
max_nid
Definition at line 1077 of file nidstrings.c.
References addrrange::ar_numaddr_ranges, cfs_expr_list::el_exprs, list_for_each_entry, cfs_range_expr::re_hi, cfs_range_expr::re_link, and cfs_range_expr::re_lo.
Referenced by cfs_ip_is_contiguous(), and cfs_ip_min_max().
static bool cfs_ip_is_contiguous (struct list_head * nidlist) [static]
Determines whether an expression list in an ip nidrange contains exactly one contiguous address range.
Parameters:
*nidlist
Return values:
true if contiguous
false if not contiguous
Definition at line 1231 of file nidstrings.c.
References addrrange::ar_numaddr_ranges, cfs_ip_ar_min_max(), cfs_expr_list::el_exprs, list_for_each_entry, nidrange::nr_addrranges, cfs_range_expr::re_hi, cfs_range_expr::re_link, cfs_range_expr::re_lo, and cfs_range_expr::re_stride.
static void cfs_ip_min_max (struct list_head * nidlist, __u32 * min_nid, __u32 * max_nid) [static]
Takes an nidlist and determines the minimum and maximum ip addresses.
Parameters:
*nidlist
*min_nid
*max_nid
Definition at line 1352 of file nidstrings.c.
References addrrange::ar_link, cfs_ip_ar_min_max(), list_for_each_entry, and nidrange::nr_addrranges.
int cfs_match_nid (lnet_nid_t nid, struct list_head * nidlist)
Matches a nid (nid) against the compiled list of nidranges (nidlist).
See also:
cfs_parse_nidlist()
Return values:
1 on match
0 otherwises
Definition at line 976 of file nidstrings.c.
References addrrange::ar_link, addrrange::ar_numaddr_ranges, list_for_each_entry, LNET_NETNUM(), LNET_NETTYP(), LNET_NIDADDR(), LNET_NIDNET(), netstrfns::nf_match_addr, netstrfns::nf_type, nidrange::nr_addrranges, nidrange::nr_all, nidrange::nr_netnum, and nidrange::nr_netstrfns.
Referenced by ll_compute_rootsquash_state(), and match_nosquash_list().
void cfs_nidrange_find_min_max (struct list_head * nidlist, char * min_nid, char * max_nid, size_t nidstr_length)
Takes a linked list of nidrange expressions, determines the minimum and maximum nid and creates appropriate nid structures.
Parameters:
*nidlist
*min_nid
*max_nid
Definition at line 1284 of file nidstrings.c.
References IPSTRING_LENGTH, list_for_each_entry, netstrfns::nf_addr2str, netstrfns::nf_min_max, netstrfns::nf_name, nidrange::nr_netnum, and nidrange::nr_netstrfns.
Referenced by jt_nodemap_add_range(), jt_nodemap_del_range(), and parse_nids().
bool cfs_nidrange_is_contiguous (struct list_head * nidlist)
Determines whether an expression list in an nidrange contains exactly one contiguous address range.
Calls the correct netstrfns for the LND
Parameters:
*nidlist
Return values:
true if contiguous
false if not contiguous
Definition at line 1148 of file nidstrings.c.
References list_for_each_entry, netstrfns::nf_is_contiguous, netstrfns::nf_name, nidrange::nr_netnum, and nidrange::nr_netstrfns.
Referenced by jt_nodemap_add_range(), jt_nodemap_del_range(), and parse_nids().
static void cfs_num_ar_min_max (struct addrrange * ar, __u32 * min_nid, __u32 * max_nid) [static]
Determines minimum and maximum addresses for a single numeric address range.
Parameters:
ar
min_nid
max_nid
Definition at line 1116 of file nidstrings.c.
References addrrange::ar_numaddr_ranges, cfs_expr_list::el_exprs, list_for_each_entry, cfs_range_expr::re_hi, cfs_range_expr::re_link, and cfs_range_expr::re_lo.
Referenced by cfs_num_is_contiguous(), and cfs_num_min_max().
static bool cfs_num_is_contiguous (struct list_head * nidlist) [static]
Determines whether an expression list in an num nidrange contains exactly one contiguous address range.
Parameters:
*nidlist
Return values:
true if contiguous
false if not contiguous
Definition at line 1185 of file nidstrings.c.
References addrrange::ar_numaddr_ranges, cfs_num_ar_min_max(), cfs_expr_list::el_exprs, list_for_each_entry, nidrange::nr_addrranges, cfs_range_expr::re_hi, cfs_range_expr::re_link, and cfs_range_expr::re_stride.
static void cfs_num_min_max (struct list_head * nidlist, __u32 * min_nid, __u32 * max_nid) [static]
Determines the min and max NID values for num LNDs.
Parameters:
*nidlist
*min_nid
*max_nid
Definition at line 1320 of file nidstrings.c.
References addrrange::ar_link, cfs_num_ar_min_max(), list_for_each_entry, and nidrange::nr_addrranges.
int cfs_parse_nidlist (char * str, int len, struct list_head * nidlist)
Parses nid range list.
Parses with rigorous syntax and overflow checking str into <nidrange> [ ' ' <nidrange> ], compiles str into set of structures and links that structure to nidlist. The resulting list can be used to match a NID againts set of NIDS defined by str.
See also:
cfs_match_nid
Return values:
1 on success
0 otherwise
Definition at line 944 of file nidstrings.c.
References cfs_free_nidlist(), cfs_gettok(), INIT_LIST_HEAD, cfs_lstr::ls_len, cfs_lstr::ls_str, and parse_nidrange().
Referenced by jt_nodemap_add_range(), jt_nodemap_del_range(), lmd_parse_nidlist(), and parse_nids().
static int cfs_print_addrranges (char * buffer, int count, struct list_head * addrranges, struct nidrange * nr) [static]
Print a list of addrrange (addrranges) into the specified buffer.
At max count characters can be printed into buffer.
Return values:
number of characters written
Definition at line 1021 of file nidstrings.c.
References addrrange::ar_numaddr_ranges, cfs_print_network(), list_for_each_entry, netstrfns::nf_print_addrlist, and nidrange::nr_netstrfns.
Referenced by cfs_print_nidlist().
static int cfs_print_network (char * buffer, int count, struct nidrange * nr) [static]
Print the network part of the nidrange nr into the specified buffer.
Return values:
number of characters written
Definition at line 1002 of file nidstrings.c.
References netstrfns::nf_name, nidrange::nr_netnum, and nidrange::nr_netstrfns.
Referenced by cfs_print_addrranges(), and cfs_print_nidlist().
int cfs_print_nidlist (char * buffer, int count, struct list_head * nidlist)
Print a list of nidranges (nidlist) into the specified buffer.
At max count characters can be printed into buffer. Nidranges are separated by a space character.
Return values:
number of characters written
Definition at line 1045 of file nidstrings.c.
References assert, cfs_print_addrranges(), cfs_print_network(), list_empty(), list_for_each_entry, nidrange::nr_addrranges, nidrange::nr_all, and nidrange::nr_link.
Referenced by mdt_nosquash_nids_seq_show().
static void free_addrranges (struct list_head * list) [static]
Frees addrrange structures of list.
For each struct addrrange structure found on list it frees cfs_expr_list list attached to it and frees the addrrange itself.
Return values:
none
Definition at line 895 of file nidstrings.c.
References addrrange::ar_link, addrrange::ar_numaddr_ranges, cfs_expr_list_free_list(), list_del(), list_empty(), list_entry, and list_head::next.
Referenced by cfs_free_nidlist().
static void libcfs_decnum_addr2str (__u32 addr, char * str, size_t size) [static]
Definition at line 234 of file nidstrings.c.
static void libcfs_hexnum_addr2str (__u32 addr, char * str, size_t size) [static]
Definition at line 240 of file nidstrings.c.
char* libcfs_id2str (lnet_process_id_t id)
Definition at line 669 of file nidstrings.c.
References libcfs_next_nidstring(), libcfs_nid2str(), LNET_NIDSTR_SIZE, LNET_PID_ANY, and LNET_PID_USERFLAG.
Referenced by brw_bulk_ready(), brw_client_done_rpc(), brw_server_rpc_done(), jt_lst_list_group(), jt_lst_ping(), jt_lst_show_error(), jt_ptl_ping(), jt_ptl_print_connections(), jt_ptl_print_peers(), kgnilnd_send(), kiblnd_send(), ksocknal_add_route_locked(), ksocknal_associate_route_conn_locked(), ksocknal_create_conn(), ksocknal_debug_peerhash(), ksocknal_destroy_conn(), ksocknal_destroy_peer(), ksocknal_find_peer_locked(), ksocknal_find_timed_out_conn(), ksocknal_launch_packet(), ksocknal_process_receive(), ksocknal_process_transmit(), ksocknal_queue_tx_locked(), ksocknal_queue_tx_zcack_v3(), ksocknal_recv_hello(), ksocknal_send(), ldlm_callback_errmsg(), lnet_create_reply_msg(), lnet_drop_delayed_msg_list(), lnet_finalize(), lnet_ni_eager_recv(), lnet_parse_ack(), lnet_parse_get(), lnet_parse_put(), lnet_parse_reply(), lnet_ping(), lnet_ping_router_locked(), lnet_post_send_locked(), lnet_print_hdr(), lnet_ptl_attach_md(), lnet_ptl_match_md(), lnet_recv_delayed_msg_list(), lnet_send(), lnet_try_match_md(), LNetGet(), LNetPut(), lst_list_tsb_nodes(), lst_print_transerr(), lst_print_tsb_verbose(), lstcon_nodes_stat(), nrs_fifo_req_get(), nrs_fifo_req_stop(), ping_client_done_rpc(), ping_server_handle(), ptl_send_buf(), ptlrpc_register_bulk(), ptlrpc_server_handle_req_in(), ptlrpc_server_handle_request(), ptlrpc_uuid_to_peer(), replay_lock_interpret(), request_in_callback(), sfw_add_test(), sfw_bulk_ready(), sfw_client_rpc_fini(), sfw_handle_server_rpc(), sfw_server_rpc_done(), sptlrpc_svc_unwrap_request(), srpc_abort_rpc(), srpc_client_rpc_done(), srpc_client_rpc_expired(), srpc_finish_service(), srpc_handle_rpc(), srpc_lnet_ev_handler(), srpc_post_active_rdma(), srpc_post_passive_rdma(), srpc_post_rpc(), srpc_send_rpc(), srpc_server_rpc_done(), tgt_brw_read(), tgt_brw_write(), tgt_request_handle(), and tgt_warn_on_cksum().
static void libcfs_ip_addr2str (__u32 addr, char * str, size_t size) [static]
Definition at line 98 of file nidstrings.c.
static int libcfs_ip_addr_range_print (char * buffer, int count, struct list_head * list) [static]
Definition at line 197 of file nidstrings.c.
References assert, cfs_expr_list_print(), cfs_expr_list::el_link, and list_for_each_entry.
static int libcfs_ip_str2addr (const char * str, int nob, __u32 * addr) [static]
Definition at line 112 of file nidstrings.c.
int libcfs_isknown_lnd (__u32 lnd)
Definition at line 506 of file nidstrings.c.
References libcfs_lnd2netstrfns().
Referenced by lnet_register_lnd(), and lnet_startup_lndni().
char* libcfs_lnd2modname (__u32 lnd)
Definition at line 512 of file nidstrings.c.
References libcfs_lnd2netstrfns(), and netstrfns::nf_modname.
Referenced by kgnilnd_proc_fini(), kgnilnd_proc_init(), and lnet_startup_lndni().
static struct netstrfns* libcfs_lnd2netstrfns (__u32 lnd) [static, read]
Definition at line 468 of file nidstrings.c.
References libcfs_nnetstrfns, and netstrfns::nf_type.
Referenced by libcfs_isknown_lnd(), libcfs_lnd2modname(), libcfs_lnd2str_r(), libcfs_net2str_r(), libcfs_nid2str_r(), and libcfs_str2nid().
char* libcfs_lnd2str_r (__u32 lnd, char * buf, size_t buf_size)
Definition at line 531 of file nidstrings.c.
References libcfs_lnd2netstrfns(), and netstrfns::nf_name.
Referenced by libcfs_lnd2str().
static int libcfs_lo_str2addr (const char * str, int nob, __u32 * addr) [static]
Definition at line 91 of file nidstrings.c.
static struct netstrfns* libcfs_name2netstrfns (const char * name) [static, read]
Definition at line 494 of file nidstrings.c.
References libcfs_nnetstrfns, and netstrfns::nf_name.
Referenced by libcfs_str2lnd().
static struct netstrfns* libcfs_namenum2netstrfns (const char * name) [static, read]
Definition at line 480 of file nidstrings.c.
References libcfs_nnetstrfns, and netstrfns::nf_name.
Referenced by add_nidrange().
char* libcfs_net2str_r (__u32 net, char * buf, size_t buf_size)
Definition at line 545 of file nidstrings.c.
References libcfs_lnd2netstrfns(), LNET_NETNUM(), LNET_NETTYP(), and netstrfns::nf_name.
Referenced by libcfs_net2str(), and rule2string().
char* libcfs_next_nidstring (void)
Definition at line 78 of file nidstrings.c.
References libcfs_nidstring_idx, and libcfs_nidstrings.
Referenced by libcfs_id2str(), libcfs_lnd2str(), libcfs_net2str(), and libcfs_nid2str().
char* libcfs_nid2str_r (lnet_nid_t nid, char * buf, size_t buf_size)
Definition at line 563 of file nidstrings.c.
References libcfs_lnd2netstrfns(), LNET_NETNUM(), LNET_NETTYP(), LNET_NID_ANY, LNET_NIDADDR(), LNET_NIDNET(), netstrfns::nf_addr2str, and netstrfns::nf_name.
Referenced by class_config_parse_rec(), class_config_yaml_output(), libcfs_nid2str(), lustre_start_mgc(), mgs_steal_client_llog_handler(), mgs_write_log_failnids(), mgs_write_log_mdc_to_lmv(), mgs_write_log_osc_to_lov(), mgs_write_log_osp_to_mdt(), nodemap_exports_show(), and nodemap_ranges_show().
static int libcfs_num_addr_range_print (char * buffer, int count, struct list_head * list) [static]
Definition at line 287 of file nidstrings.c.
References assert, cfs_expr_list_print(), cfs_expr_list::el_link, and list_for_each_entry.
static int libcfs_num_match (__u32 addr, struct list_head * numaddr) [static]
Definition at line 306 of file nidstrings.c.
References assert, cfs_expr_list_match(), cfs_expr_list::el_link, list_empty(), list_entry, and list_head::next.
static int libcfs_num_parse (char * str, int len, struct list_head * list) [static]
Nf_parse_addrlist method for networks using numeric addresses.
Examples of such networks are gm and elan.
Return values:
0 if str parsed to numeric address
errno otherwise
Definition at line 274 of file nidstrings.c.
References cfs_expr_list_parse(), cfs_expr_list::el_link, list_add_tail(), and MAX_NUMERIC_VALUE.
static int libcfs_num_str2addr (const char * str, int nob, __u32 * addr) [static]
Definition at line 246 of file nidstrings.c.
int libcfs_str2anynid (lnet_nid_t * nidp, const char * str)
Definition at line 686 of file nidstrings.c.
References libcfs_str2nid(), and LNET_NID_ANY.
Referenced by fault_attr_nid_parse(), jt_ptl_del_peer(), jt_ptl_del_route(), jt_ptl_disconnect(), jt_ptl_fail_nid(), and jt_ptl_push_connection().
int libcfs_str2lnd (const char * str)
Definition at line 520 of file nidstrings.c.
References libcfs_name2netstrfns(), and netstrfns::nf_type.
__u32 libcfs_str2net (const char * str)
Definition at line 633 of file nidstrings.c.
References libcfs_str2net_internal(), LNET_NID_ANY, and LNET_NIDNET().
Referenced by fault_attr_nid_parse(), jt_ptl_network(), lnet_netspec2net(), lnet_parse_networks(), lnet_parse_route(), lustre_lnet_config_route(), lustre_lnet_del_net(), lustre_lnet_del_route(), lustre_lnet_show_net(), lustre_lnet_show_route(), parse_net(), and sptlrpc_parse_rule().
static struct netstrfns* libcfs_str2net_internal (const char * str, __u32 * net) [static, read]
Definition at line 597 of file nidstrings.c.
References libcfs_nnetstrfns, LNET_MKNET(), LOLND, netstrfns::nf_name, and netstrfns::nf_type.
Referenced by libcfs_str2net(), and libcfs_str2nid().
lnet_nid_t libcfs_str2nid (const char * str)
Definition at line 644 of file nidstrings.c.
References assert, libcfs_lnd2netstrfns(), libcfs_str2net_internal(), LNET_MKNET(), LNET_MKNID(), LNET_NID_ANY, netstrfns::nf_str2addr, and SOCKLND.
Referenced by clean_path(), convert_hostnames(), jt_lcfg_add_uuid(), jt_ptl_add_peer(), jt_ptl_add_route(), jt_ptl_mynid(), jt_ptl_notify_router(), jt_ptl_ping(), jt_ptl_which_nid(), libcfs_str2anynid(), lnet_parse_nid(), lnet_parse_route(), lst_parse_nids(), lustre_lnet_config_route(), lustre_lnet_del_route(), lustre_lnet_show_route(), main(), mgs_iocontrol_nodemap(), nodemap_parse_range(), obd_export_evict_by_nid(), parse_nid(), parse_perm_line(), and read_mapping_db().
static int parse_addrange (const struct cfs_lstr * src, struct nidrange * nidrange) [static]
Parses <addrrange> token on the syntax.
Allocates struct addrrange and links to nidrange via (nidrange::nr_addrranges)
Return values:
0 if src parses to '*' | <ipaddr_range> | <cfs_expr_list>
-errno otherwise
Definition at line 773 of file nidstrings.c.
References addrrange::ar_link, addrrange::ar_numaddr_ranges, INIT_LIST_HEAD, list_add_tail(), cfs_lstr::ls_len, cfs_lstr::ls_str, netstrfns::nf_parse_addrlist, nidrange::nr_addrranges, nidrange::nr_all, and nidrange::nr_netstrfns.
Referenced by parse_nidrange().
static int parse_nidrange (struct cfs_lstr * src, struct list_head * nidlist) [static]
Parses <nidrange> token of the syntax.
Return values:
1 if src parses to <addrrange> '@' <net>
0 otherwise
Definition at line 858 of file nidstrings.c.
References add_nidrange(), cfs_gettok(), cfs_lstr::ls_len, cfs_lstr::ls_str, and parse_addrange().
Referenced by cfs_parse_nidlist().
Variable Documentation
struct netstrfns libcfs_netstrfns[] [static]
Definition at line 321 of file nidstrings.c.
int libcfs_nidstring_idx [static]
Definition at line 75 of file nidstrings.c.
Referenced by libcfs_next_nidstring().
char libcfs_nidstrings[LNET_NIDSTR_COUNT][LNET_NIDSTR_SIZE] [static]
Definition at line 74 of file nidstrings.c.
Referenced by libcfs_next_nidstring().
const size_t libcfs_nnetstrfns [static]
Initial value:
        sizeof(libcfs_netstrfns)/sizeof(libcfs_netstrfns[0])
Definition at line 464 of file nidstrings.c.
Referenced by libcfs_lnd2netstrfns(), libcfs_name2netstrfns(), libcfs_namenum2netstrfns(), and libcfs_str2net_internal().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.