Lustre: libcfs/libcfs/libcfs_cpu.c File Reference
libcfs/libcfs/libcfs_cpu.c File Reference
#include <libcfs/libcfs.h>
Defines
#define DEBUG_SUBSYSTEM S_LNET
#define CFS_CPU_VERSION_MAGIC 0xbabecafe
Functions
struct cfs_cpt_table * cfs_cpt_table_alloc (unsigned int ncpt)
create a cfs_cpt_table with ncpt number of partitions
void cfs_cpt_table_free (struct cfs_cpt_table *cptab)
destroy a CPU partition table
int cfs_cpt_table_print (struct cfs_cpt_table *cptab, char *buf, int len)
print string information of cpt-table
int cfs_cpt_number (struct cfs_cpt_table *cptab)
return total number of CPU partitions in cptab
int cfs_cpt_weight (struct cfs_cpt_table *cptab, int cpt)
return number of HW cores or hypter-threadings in a CPU partition cpt
int cfs_cpt_online (struct cfs_cpt_table *cptab, int cpt)
is there any online CPU in CPU partition cpt
nodemask_t * cfs_cpt_nodemask (struct cfs_cpt_table *cptab, int cpt)
return nodemask of CPU partition cpt
int cfs_cpt_set_cpu (struct cfs_cpt_table *cptab, int cpt, int cpu)
add cpu to CPU partion of cptab, return 1 for success, otherwise 0 is returned
void cfs_cpt_unset_cpu (struct cfs_cpt_table *cptab, int cpt, int cpu)
remove cpu from CPU partition cpt of cptab
int cfs_cpt_set_cpumask (struct cfs_cpt_table *cptab, int cpt, cpumask_t *mask)
add all cpus in mask to CPU partition cpt return 1 if successfully set all CPUs, otherwise return 0
void cfs_cpt_unset_cpumask (struct cfs_cpt_table *cptab, int cpt, cpumask_t *mask)
remove all cpus in mask from CPU partition cpt
int cfs_cpt_set_node (struct cfs_cpt_table *cptab, int cpt, int node)
add all cpus in NUMA node node to CPU partition cpt return 1 if successfully set all CPUs, otherwise return 0
void cfs_cpt_unset_node (struct cfs_cpt_table *cptab, int cpt, int node)
remove all cpus in NUMA node node from CPU partition cpt
int cfs_cpt_set_nodemask (struct cfs_cpt_table *cptab, int cpt, nodemask_t *mask)
add all cpus in node mask mask to CPU partition cpt return 1 if successfully set all CPUs, otherwise return 0
void cfs_cpt_unset_nodemask (struct cfs_cpt_table *cptab, int cpt, nodemask_t *mask)
remove all cpus in node mask mask from CPU partition cpt
void cfs_cpt_clear (struct cfs_cpt_table *cptab, int cpt)
unset all cpus for CPU partition cpt
int cfs_cpt_spread_node (struct cfs_cpt_table *cptab, int cpt)
convert partition id cpt to numa node id, if there are more than one nodes in this partition, it might return a different node id each time.
int cfs_cpu_ht_nsiblings (int cpu)
return number of HTs in the same core of cpu
int cfs_cpt_current (struct cfs_cpt_table *cptab, int remap)
shadow current HW processor ID to CPU-partition ID of cptab
int cfs_cpt_of_cpu (struct cfs_cpt_table *cptab, int cpu)
shadow HW processor ID CPU to CPU-partition ID by cptab
int cfs_cpt_bind (struct cfs_cpt_table *cptab, int cpt)
bind current thread on a CPU-partition cpt of cptab
void cfs_cpu_fini (void)
int cfs_cpu_init (void)
Variables
struct cfs_cpt_table *cfs_cpt_table __read_mostly = NULL
Global CPU partition table.
Define Documentation
#define CFS_CPU_VERSION_MAGIC 0xbabecafe
Definition at line 46 of file libcfs_cpu.c.
Referenced by cfs_cpt_table_alloc(), and cfs_cpt_table_free().
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 36 of file libcfs_cpu.c.
Function Documentation
int cfs_cpt_bind (struct cfs_cpt_table * cptab, int cpt)
bind current thread on a CPU-partition cpt of cptab
Definition at line 207 of file libcfs_cpu.c.
Referenced by cfs_wi_scheduler(), kiblnd_scheduler(), ksocknal_scheduler(), ptlrpc_hr_main(), ptlrpc_main(), and ptlrpcd().
void cfs_cpt_clear (struct cfs_cpt_table * cptab, int cpt)
unset all cpus for CPU partition cpt
Definition at line 173 of file libcfs_cpu.c.
int cfs_cpt_current (struct cfs_cpt_table * cptab, int remap)
shadow current HW processor ID to CPU-partition ID of cptab
Definition at line 193 of file libcfs_cpu.c.
Referenced by ptlrpc_prep_set(), and ptlrpcd_select_pc().
nodemask_t* cfs_cpt_nodemask (struct cfs_cpt_table * cptab, int cpt)
return nodemask of CPU partition cpt
Definition at line 114 of file libcfs_cpu.c.
References cfs_cpt_table::ctb_nodemask.
Referenced by ost_setup().
int cfs_cpt_number (struct cfs_cpt_table * cptab)
return total number of CPU partitions in cptab
Definition at line 93 of file libcfs_cpu.c.
Referenced by cfs_percpt_alloc(), cfs_percpt_lock(), cfs_percpt_unlock(), cfs_wi_sched_create(), ksocknal_net_start_threads(), lnet_lib_init(), lnet_selftest_exit(), lnet_selftest_init(), ost_setup(), ptlrpc_hr_select(), ptlrpc_register_service(), ptlrpcd_fini(), ptlrpcd_init(), sfw_load_test(), and srpc_service_init().
int cfs_cpt_of_cpu (struct cfs_cpt_table * cptab, int cpu)
shadow HW processor ID CPU to CPU-partition ID by cptab
Definition at line 200 of file libcfs_cpu.c.
int cfs_cpt_online (struct cfs_cpt_table * cptab, int cpt)
is there any online CPU in CPU partition cpt
Definition at line 107 of file libcfs_cpu.c.
int cfs_cpt_set_cpu (struct cfs_cpt_table * cptab, int cpt, int cpu)
add cpu to CPU partion of cptab, return 1 for success, otherwise 0 is returned
Definition at line 121 of file libcfs_cpu.c.
int cfs_cpt_set_cpumask (struct cfs_cpt_table * cptab, int cpt, cpumask_t * mask)
add all cpus in mask to CPU partition cpt return 1 if successfully set all CPUs, otherwise return 0
Definition at line 134 of file libcfs_cpu.c.
int cfs_cpt_set_node (struct cfs_cpt_table * cptab, int cpt, int node)
add all cpus in NUMA node node to CPU partition cpt return 1 if successfully set all CPUs, otherwise return 0
Definition at line 147 of file libcfs_cpu.c.
Referenced by ost_setup().
int cfs_cpt_set_nodemask (struct cfs_cpt_table * cptab, int cpt, nodemask_t * mask)
add all cpus in node mask mask to CPU partition cpt return 1 if successfully set all CPUs, otherwise return 0
Definition at line 160 of file libcfs_cpu.c.
int cfs_cpt_spread_node (struct cfs_cpt_table * cptab, int cpt)
convert partition id cpt to numa node id, if there are more than one nodes in this partition, it might return a different node id each time.
Definition at line 179 of file libcfs_cpu.c.
Referenced by cfs_cpt_malloc(), cfs_cpt_vzalloc(), cfs_mem_cache_cpt_alloc(), and cfs_page_cpt_alloc().
struct cfs_cpt_table* cfs_cpt_table_alloc (unsigned int ncpt) [read]
create a cfs_cpt_table with ncpt number of partitions
Definition at line 49 of file libcfs_cpu.c.
References CERROR, CFS_CPU_VERSION_MAGIC, cfs_cpt_table::ctb_nodemask, cfs_cpt_table::ctb_nparts, cfs_cpt_table::ctb_version, and LIBCFS_ALLOC.
Referenced by cfs_cpu_init(), and ost_setup().
void cfs_cpt_table_free (struct cfs_cpt_table * cptab)
destroy a CPU partition table
Definition at line 70 of file libcfs_cpu.c.
References CFS_CPU_VERSION_MAGIC, cfs_cpt_table::ctb_version, LASSERT, and LIBCFS_FREE.
Referenced by cfs_cpu_fini(), ost_cleanup(), and ost_setup().
int cfs_cpt_table_print (struct cfs_cpt_table * cptab, char * buf, int len)
print string information of cpt-table
Definition at line 79 of file libcfs_cpu.c.
Referenced by __proc_cpt_table().
void cfs_cpt_unset_cpu (struct cfs_cpt_table * cptab, int cpt, int cpu)
remove cpu from CPU partition cpt of cptab
Definition at line 128 of file libcfs_cpu.c.
void cfs_cpt_unset_cpumask (struct cfs_cpt_table * cptab, int cpt, cpumask_t * mask)
remove all cpus in mask from CPU partition cpt
Definition at line 141 of file libcfs_cpu.c.
void cfs_cpt_unset_node (struct cfs_cpt_table * cptab, int cpt, int node)
remove all cpus in NUMA node node from CPU partition cpt
Definition at line 154 of file libcfs_cpu.c.
void cfs_cpt_unset_nodemask (struct cfs_cpt_table * cptab, int cpt, nodemask_t * mask)
remove all cpus in node mask mask from CPU partition cpt
Definition at line 167 of file libcfs_cpu.c.
int cfs_cpt_weight (struct cfs_cpt_table * cptab, int cpt)
return number of HW cores or hypter-threadings in a CPU partition cpt
Definition at line 100 of file libcfs_cpu.c.
Referenced by kiblnd_base_startup(), kiblnd_start_schedulers(), ksocknal_base_startup(), ksocknal_start_schedulers(), libcfs_init(), lnet_msg_container_setup(), lnet_selftest_init(), ptlrpc_hr_init(), ptlrpc_server_nthreads_check(), and ptlrpcd_init().
void cfs_cpu_fini (void)
Definition at line 214 of file libcfs_cpu.c.
References cfs_cpt_table_free().
Referenced by libcfs_exit(), and libcfs_init().
int cfs_cpu_ht_nsiblings (int cpu)
return number of HTs in the same core of cpu
Definition at line 186 of file libcfs_cpu.c.
Referenced by ptlrpc_hr_init(), and ptlrpc_server_nthreads_check().
int cfs_cpu_init (void)
Definition at line 223 of file libcfs_cpu.c.
References cfs_cpt_table_alloc().
Referenced by libcfs_init().
Variable Documentation
struct cfs_cpt_table* cfs_cpt_table __read_mostly = NULL
Global CPU partition table.
Definition at line 41 of file libcfs_cpu.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.