Lustre: libcfs/libcfs/debug.c File Reference
libcfs/libcfs/debug.c File Reference
#include <linux/kthread.h>
#include <libcfs/libcfs.h>
#include "tracefile.h"
Defines
#define DEBUG_SUBSYSTEM S_LNET
#define DEBUG_SUBSYSTEM S_UNDEFINED
#define DEBUG_SUBSYSTEM S_LNET
Functions
module_param (libcfs_subsystem_debug, int, 0644)
MODULE_PARM_DESC (libcfs_subsystem_debug,"Lustre kernel debug subsystem mask")
module_param (libcfs_debug, int, 0644)
MODULE_PARM_DESC (libcfs_debug,"Lustre kernel debug mask")
module_param (libcfs_debug_mb, uint, 0644)
MODULE_PARM_DESC (libcfs_debug_mb,"Total debug buffer size.")
module_param (libcfs_printk, uint, 0644)
MODULE_PARM_DESC (libcfs_printk,"Lustre kernel debug console mask")
module_param (libcfs_console_ratelimit, uint, 0644)
MODULE_PARM_DESC (libcfs_console_ratelimit,"Lustre kernel debug console ratelimit (0 to disable)")
module_param (libcfs_console_max_delay, uint, 0644)
MODULE_PARM_DESC (libcfs_console_max_delay,"Lustre kernel debug console max delay (jiffies)")
module_param (libcfs_console_min_delay, uint, 0644)
MODULE_PARM_DESC (libcfs_console_min_delay,"Lustre kernel debug console min delay (jiffies)")
module_param (libcfs_console_backoff, uint, 0644)
MODULE_PARM_DESC (libcfs_console_backoff,"Lustre kernel debug console backoff factor")
module_param (libcfs_panic_on_lbug, uint, 0644)
MODULE_PARM_DESC (libcfs_panic_on_lbug,"Lustre kernel panic on LBUG")
module_param (libcfs_debug_file_path, charp, 0644)
MODULE_PARM_DESC (libcfs_debug_file_path,"Path for dumping debug logs, set 'NONE' to prevent log dumping")
static const char * libcfs_debug_subsys2str (int subsys)
static const char * libcfs_debug_dbg2str (int debug)
int libcfs_debug_mask2str (char *str, int size, int mask, int is_subsys)
int libcfs_debug_str2mask (int *mask, const char *str, int is_subsys)
void libcfs_debug_dumplog_internal (void *arg)
Dump Lustre log to debug_file_path by calling tracefile_dump_all_pages().
static int libcfs_debug_dumplog_thread (void *arg)
void libcfs_debug_dumplog (void)
int libcfs_debug_init (unsigned long bufsize)
int libcfs_debug_cleanup (void)
int libcfs_debug_clear_buffer (void)
int libcfs_debug_mark_buffer (const char *text)
long libcfs_log_return (struct libcfs_debug_msg_data *msgdata, long rc)
void libcfs_log_goto (struct libcfs_debug_msg_data *msgdata, const char *label, long_ptr_t rc)
Variables
static char debug_file_name [1024]
unsigned int libcfs_subsystem_debug = ~0
unsigned int libcfs_debug
static unsigned int libcfs_debug_mb
unsigned int libcfs_printk = D_CANTMASK
unsigned int libcfs_console_ratelimit = 1
unsigned int libcfs_console_max_delay
unsigned int libcfs_console_min_delay
unsigned int libcfs_console_backoff = CDEBUG_DEFAULT_BACKOFF
unsigned int libcfs_debug_binary = 1
unsigned int libcfs_stack = 3 * THREAD_SIZE / 4
unsigned int libcfs_catastrophe
unsigned int libcfs_watchdog_ratelimit = 300
unsigned int libcfs_panic_on_lbug = 1
atomic_t libcfs_kmemory = ATOMIC_INIT(0)
static wait_queue_head_t debug_ctlwq
char libcfs_debug_file_path_arr [PATH_MAX] = LIBCFS_DEBUG_FILE_PATH_DEFAULT
static char * libcfs_debug_file_path
int libcfs_panic_in_progress
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 341 of file debug.c.
#define DEBUG_SUBSYSTEM S_UNDEFINED
Definition at line 341 of file debug.c.
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 341 of file debug.c.
Function Documentation
int libcfs_debug_cleanup (void)
Definition at line 315 of file debug.c.
References cfs_tracefile_exit(), and libcfs_unregister_panic_notifier().
Referenced by libcfs_exit(), and libcfs_init().
int libcfs_debug_clear_buffer (void)
Definition at line 322 of file debug.c.
References cfs_trace_flush_pages().
Referenced by libcfs_ioctl().
static const char* libcfs_debug_dbg2str (int debug) [static]
Definition at line 128 of file debug.c.
References ARRAY_SIZE, libcfs_debug_masks, and LIBCFS_DEBUG_MASKS_NAMES.
Referenced by libcfs_debug_mask2str(), and libcfs_debug_str2mask().
void libcfs_debug_dumplog (void)
Definition at line 251 of file debug.c.
References current_pid, debug_ctlwq, ENTRY, libcfs_debug_dumplog_thread(), and printk.
Referenced by class_fail_export(), kgnilnd_complete_closed_conn(), kgnilnd_recv(), kgnilnd_verify_rdma_cksum(), lbug_with_loc(), ldlm_expired_completion_wait(), ll_file_release(), ptlrpc_expire_one_request(), ptlrpc_invalidate_import_thread(), ptlrpc_server_handle_request(), and ptlrpc_set_import_discon().
void libcfs_debug_dumplog_internal (void * arg)
Dump Lustre log to debug_file_path by calling tracefile_dump_all_pages().
Definition at line 219 of file debug.c.
References cfs_time_current_sec(), cfs_tracefile_dump_all_pages(), debug_file_name, libcfs_debug_file_path_arr, libcfs_run_debug_log_upcall(), LPLD, and printk.
Referenced by libcfs_debug_dumplog_thread(), and panic_notifier().
static int libcfs_debug_dumplog_thread (void * arg) [static]
Definition at line 244 of file debug.c.
References debug_ctlwq, and libcfs_debug_dumplog_internal().
Referenced by libcfs_debug_dumplog().
int libcfs_debug_init (unsigned long bufsize)
Definition at line 279 of file debug.c.
References CDEBUG_DEFAULT_MAX_DELAY, CDEBUG_DEFAULT_MIN_DELAY, cfs_trace_max_debug_mb(), cfs_tracefile_init(), debug_ctlwq, libcfs_console_max_delay, libcfs_console_min_delay, libcfs_debug_file_path, libcfs_debug_file_path_arr, libcfs_debug_mb, libcfs_register_panic_notifier(), max, strlcpy(), and TCD_MAX_PAGES.
Referenced by libcfs_init().
int libcfs_debug_mark_buffer (const char * text)
Definition at line 332 of file debug.c.
References CDEBUG, D_TRACE, D_WARNING, and LCONSOLE.
Referenced by libcfs_ioctl().
int libcfs_debug_mask2str (char * str, int size, int mask, int is_subsys)
Definition at line 139 of file debug.c.
References bit, libcfs_debug_dbg2str(), and libcfs_debug_subsys2str().
Referenced by __proc_dobitmasks().
int libcfs_debug_str2mask (int * mask, const char * str, int is_subsys)
Definition at line 185 of file debug.c.
References bit, cfs_str2mask(), CWARN, D_CANTMASK, libcfs_debug_dbg2str(), and libcfs_debug_subsys2str().
Referenced by __proc_dobitmasks().
static const char* libcfs_debug_subsys2str (int subsys) [static]
Definition at line 116 of file debug.c.
References ARRAY_SIZE, LIBCFS_DEBUG_SUBSYS_NAMES, and libcfs_debug_subsystems.
Referenced by libcfs_debug_mask2str(), and libcfs_debug_str2mask().
void libcfs_log_goto (struct libcfs_debug_msg_data * msgdata, const char * label, long_ptr_t rc)
Definition at line 351 of file debug.c.
References libcfs_debug_msg(), LPLD, LPLU, and LPLX.
long libcfs_log_return (struct libcfs_debug_msg_data * msgdata, long rc)
Definition at line 343 of file debug.c.
References libcfs_debug_msg().
module_param (libcfs_debug_file_path , charp , 0644)
module_param (libcfs_panic_on_lbug , uint , 0644)
module_param (libcfs_console_backoff , uint , 0644)
module_param (libcfs_console_min_delay , uint , 0644)
module_param (libcfs_console_max_delay , uint , 0644)
module_param (libcfs_console_ratelimit , uint , 0644)
module_param (libcfs_printk , uint , 0644)
module_param (libcfs_debug_mb , uint , 0644)
module_param (libcfs_debug , int , 0644)
module_param (libcfs_subsystem_debug , int , 0644)
MODULE_PARM_DESC (libcfs_debug_file_path , "Path for dumping debug logs, set 'NONE'to prevent log dumping")
MODULE_PARM_DESC (libcfs_panic_on_lbug , "Lustre kernel panic on LBUG")
MODULE_PARM_DESC (libcfs_console_backoff , "Lustre kernel debug console backoff factor")
MODULE_PARM_DESC (libcfs_console_min_delay , "Lustre kernel debug console min delay (jiffies)")
MODULE_PARM_DESC (libcfs_console_max_delay , "Lustre kernel debug console max delay (jiffies)")
MODULE_PARM_DESC (libcfs_console_ratelimit , "Lustre kernel debug console ratelimit (0 to disable)")
MODULE_PARM_DESC (libcfs_printk , "Lustre kernel debug console mask")
MODULE_PARM_DESC (libcfs_debug_mb , "Total debug buffer size.")
MODULE_PARM_DESC (libcfs_debug , "Lustre kernel debug mask")
MODULE_PARM_DESC (libcfs_subsystem_debug , "Lustre kernel debug subsystem mask")
Variable Documentation
wait_queue_head_t debug_ctlwq [static]
Definition at line 102 of file debug.c.
Referenced by libcfs_debug_dumplog(), libcfs_debug_dumplog_thread(), and libcfs_debug_init().
char debug_file_name[1024] [static]
Definition at line 48 of file debug.c.
Referenced by libcfs_debug_dumplog_internal().
unsigned int libcfs_catastrophe
Definition at line 90 of file debug.c.
Referenced by cfs_trace_assertion_failed(), and lbug_with_loc().
unsigned int libcfs_console_backoff = CDEBUG_DEFAULT_BACKOFF
Definition at line 81 of file debug.c.
Referenced by libcfs_debug_vmsg2(), and proc_console_backoff().
unsigned int libcfs_console_max_delay
Definition at line 73 of file debug.c.
Referenced by libcfs_debug_init(), libcfs_debug_vmsg2(), proc_console_max_delay_cs(), and proc_console_min_delay_cs().
unsigned int libcfs_console_min_delay
Definition at line 77 of file debug.c.
Referenced by libcfs_debug_init(), libcfs_debug_vmsg2(), proc_console_max_delay_cs(), and proc_console_min_delay_cs().
unsigned int libcfs_console_ratelimit = 1
Definition at line 69 of file debug.c.
Referenced by libcfs_debug_vmsg2().
unsigned int libcfs_debug
Initial value:
 (D_CANTMASK |
                             D_NETERROR | D_HA | D_CONFIG | D_IOCTL | D_LFSCK)
Definition at line 55 of file debug.c.
unsigned int libcfs_debug_binary = 1
Definition at line 85 of file debug.c.
Referenced by libcfs_debug_vmsg2().
char* libcfs_debug_file_path [static]
Definition at line 107 of file debug.c.
Referenced by libcfs_debug_init().
char libcfs_debug_file_path_arr[PATH_MAX] = LIBCFS_DEBUG_FILE_PATH_DEFAULT
Definition at line 104 of file debug.c.
Referenced by libcfs_debug_dumplog_internal(), and libcfs_debug_init().
unsigned int libcfs_debug_mb [static]
Definition at line 61 of file debug.c.
Referenced by libcfs_debug_init().
atomic_t libcfs_kmemory = ATOMIC_INIT(0)
Definition at line 99 of file debug.c.
Referenced by kgnilnd_base_shutdown(), kgnilnd_base_startup(), kgnilnd_shutdown(), kiblnd_base_shutdown(), kiblnd_shutdown(), ksocknal_base_shutdown(), ksocknal_process_transmit(), and libcfs_exit().
int libcfs_panic_in_progress
Definition at line 112 of file debug.c.
Referenced by cfs_trace_assertion_failed(), collect_pages(), panic_notifier(), and put_pages_back().
unsigned int libcfs_panic_on_lbug = 1
Definition at line 95 of file debug.c.
Referenced by lbug_with_loc().
unsigned int libcfs_printk = D_CANTMASK
Definition at line 65 of file debug.c.
unsigned int libcfs_stack = 3 * THREAD_SIZE / 4
Definition at line 87 of file debug.c.
unsigned int libcfs_subsystem_debug = ~0
Definition at line 50 of file debug.c.
Referenced by __proc_dobitmasks(), and class_handle_ioctl().
unsigned int libcfs_watchdog_ratelimit = 300
Definition at line 93 of file debug.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.