Lustre: libcfs/libcfs/module.c File Reference
libcfs/libcfs/module.c File Reference
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/mm.h>
#include <linux/string.h>
#include <linux/stat.h>
#include <linux/errno.h>
#include <linux/unistd.h>
#include <net/sock.h>
#include <linux/uio.h>
#include <linux/uaccess.h>
#include <linux/fs.h>
#include <linux/file.h>
#include <linux/list.h>
#include <linux/sysctl.h>
#include <linux/proc_fs.h>
#include <asm/div64.h>
#include <libcfs/libcfs.h>
#include <libcfs/libcfs_crypto.h>
#include <lnet/lib-lnet.h>
#include "tracefile.h"
Defines
#define DEBUG_SUBSYSTEM S_LNET
Functions
static DECLARE_RWSEM (ioctl_list_sem)
static LIST_HEAD (ioctl_list)
int libcfs_register_ioctl (struct libcfs_ioctl_handler *hand)
int libcfs_deregister_ioctl (struct libcfs_ioctl_handler *hand)
int libcfs_ioctl (unsigned long cmd, void __user *uparam)
int lprocfs_call_handler (void *data, int write, loff_t *ppos, void __user *buffer, size_t *lenp, int(*handler)(void *data, int write, loff_t pos, void __user *buffer, int len))
static int __proc_dobitmasks (void *data, int write, loff_t pos, void __user *buffer, int nob)
static int proc_dobitmasks (struct ctl_table *table, int write, void __user *buffer, size_t *lenp, loff_t *ppos)
static int __proc_dump_kernel (void *data, int write, loff_t pos, void __user *buffer, int nob)
static int proc_dump_kernel (struct ctl_table *table, int write, void __user *buffer, size_t *lenp, loff_t *ppos)
static int __proc_daemon_file (void *data, int write, loff_t pos, void __user *buffer, int nob)
static int proc_daemon_file (struct ctl_table *table, int write, void __user *buffer, size_t *lenp, loff_t *ppos)
static int __proc_debug_mb (void *data, int write, loff_t pos, void __user *buffer, int nob)
static int proc_debug_mb (struct ctl_table *table, int write, void __user *buffer, size_t *lenp, loff_t *ppos)
static int proc_console_max_delay_cs (struct ctl_table *table, int write, void __user *buffer, size_t *lenp, loff_t *ppos)
static int proc_console_min_delay_cs (struct ctl_table *table, int write, void __user *buffer, size_t *lenp, loff_t *ppos)
static int proc_console_backoff (struct ctl_table *table, int write, void __user *buffer, size_t *lenp, loff_t *ppos)
static int libcfs_force_lbug (struct ctl_table *table, int write, void __user *buffer, size_t *lenp, loff_t *ppos)
static int proc_fail_loc (struct ctl_table *table, int write, void __user *buffer, size_t *lenp, loff_t *ppos)
static int __proc_cpt_table (void *data, int write, loff_t pos, void __user *buffer, int nob)
static int proc_cpt_table (struct ctl_table *table, int write, void __user *buffer, size_t *lenp, loff_t *ppos)
static int insert_proc (void)
static void remove_proc (void)
static int __init libcfs_init (void)
static void __exit libcfs_exit (void)
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre helper library")
MODULE_VERSION (LIBCFS_VERSION)
MODULE_LICENSE ("GPL")
module_init (libcfs_init)
module_exit (libcfs_exit)
Variables
static int min_watchdog_ratelimit
static int max_watchdog_ratelimit = (24*60*60)
static struct ctl_table lnet_table []
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 55 of file module.c.
Function Documentation
static int __proc_cpt_table (void * data, int write, loff_t pos, void __user * buffer, int nob) [static]
Definition at line 421 of file module.c.
References buf, cfs_cpt_table_print(), cfs_trace_copyout_string(), LASSERT, LIBCFS_ALLOC, and LIBCFS_FREE.
Referenced by proc_cpt_table().
static int __proc_daemon_file (void * data, int write, loff_t pos, void __user * buffer, int nob) [static]
Definition at line 253 of file module.c.
References cfs_trace_copyout_string(), cfs_trace_daemon_command_usrstr(), and cfs_tracefile.
Referenced by proc_daemon_file().
static int __proc_debug_mb (void * data, int write, loff_t pos, void __user * buffer, int nob) [static]
Definition at line 277 of file module.c.
References cfs_trace_copyout_string(), cfs_trace_get_debug_mb(), and cfs_trace_set_debug_mb_usrstr().
Referenced by proc_debug_mb().
static int __proc_dobitmasks (void * data, int write, loff_t pos, void __user * buffer, int nob) [static]
Definition at line 184 of file module.c.
References cfs_trace_allocate_string_buffer(), cfs_trace_copyin_string(), cfs_trace_copyout_string(), D_EMERG, libcfs_debug_mask2str(), libcfs_debug_str2mask(), libcfs_printk, and libcfs_subsystem_debug.
Referenced by proc_dobitmasks().
static int __proc_dump_kernel (void * data, int write, loff_t pos, void __user * buffer, int nob) [static]
Definition at line 236 of file module.c.
References cfs_trace_dump_debug_buffer_usrstr().
Referenced by proc_dump_kernel().
static DECLARE_RWSEM (ioctl_list_sem) [static]
static int insert_proc (void) [static]
Definition at line 663 of file module.c.
References lnet_table_header.
Referenced by libcfs_init().
int libcfs_deregister_ioctl (struct libcfs_ioctl_handler * hand)
Definition at line 84 of file module.c.
References libcfs_ioctl_handler::item, list_del_init(), and list_empty().
Referenced by lnet_exit(), and lstcon_console_fini().
static void __exit libcfs_exit (void) [static]
Definition at line 745 of file module.c.
References CDEBUG, CERROR, cfs_cpu_fini(), cfs_crypto_unregister(), cfs_sched_rehash, cfs_wi_sched_destroy(), cfs_wi_shutdown(), D_MALLOC, libcfs_debug_cleanup(), libcfs_dev, libcfs_kmemory, printk, and remove_proc().
static int libcfs_force_lbug (struct ctl_table * table, int write, void __user * buffer, size_t * lenp, loff_t * ppos) [static]
Definition at line 400 of file module.c.
References LBUG.
static int __init libcfs_init (void) [static]
Definition at line 682 of file module.c.
References CDEBUG, CERROR, CFS_CPT_ANY, cfs_cpt_weight(), cfs_cpu_fini(), cfs_cpu_init(), cfs_crypto_register(), cfs_crypto_unregister(), cfs_sched_rehash, cfs_wi_sched_create(), cfs_wi_shutdown(), cfs_wi_startup(), D_OTHER, insert_proc(), libcfs_debug_cleanup(), libcfs_debug_init(), libcfs_dev, and printk.
int libcfs_ioctl (unsigned long cmd, void __user * uparam)
Definition at line 99 of file module.c.
References CDEBUG, CDEBUG_LIMIT, D_ERROR, D_IOCTL, ENTRY, GOTO, libcfs_ioctl_handler::handle_ioctl, libcfs_ioctl_data::ioc_inlbuf1, libcfs_ioctl_data::ioc_inllen1, libcfs_ioctl_hdr::ioc_len, IOC_LIBCFS_CLEAR_DEBUG, IOC_LIBCFS_MARK_DEBUG, libcfs_ioctl_hdr::ioc_version, libcfs_ioctl_handler::item, libcfs_debug_clear_buffer(), libcfs_debug_mark_buffer(), LIBCFS_FREE, libcfs_ioctl_data_adjust(), libcfs_ioctl_getdata(), LIBCFS_IOCTL_VERSION, list_for_each_entry, and RETURN.
Referenced by libcfs_psdev_ioctl().
int libcfs_register_ioctl (struct libcfs_ioctl_handler * hand)
Definition at line 69 of file module.c.
References libcfs_ioctl_handler::item, list_add_tail(), and list_empty().
Referenced by lnet_init(), and lstcon_console_init().
static LIST_HEAD (ioctl_list) [static]
int lprocfs_call_handler (void * data, int write, loff_t * ppos, void __user * buffer, size_t * lenp, int(*)(void *data, int write, loff_t pos, void __user *buffer, int len) handler)
Definition at line 164 of file module.c.
References handler().
Referenced by proc_cpt_table(), proc_daemon_file(), proc_debug_mb(), proc_dobitmasks(), proc_dump_kernel(), proc_lnet_buffers(), proc_lnet_portal_rotor(), and proc_lnet_stats().
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre helper library")
module_exit (libcfs_exit)
module_init (libcfs_init)
MODULE_LICENSE ("GPL")
MODULE_VERSION (LIBCFS_VERSION)
static int proc_console_backoff (struct ctl_table * table, int write, void __user * buffer, size_t * lenp, loff_t * ppos) [static]
Definition at line 370 of file module.c.
References libcfs_console_backoff.
static int proc_console_max_delay_cs (struct ctl_table * table, int write, void __user * buffer, size_t * lenp, loff_t * ppos) [static]
Definition at line 304 of file module.c.
References cfs_duration_sec(), cfs_time_seconds(), libcfs_console_max_delay, and libcfs_console_min_delay.
static int proc_console_min_delay_cs (struct ctl_table * table, int write, void __user * buffer, size_t * lenp, loff_t * ppos) [static]
Definition at line 337 of file module.c.
References cfs_duration_sec(), cfs_time_seconds(), libcfs_console_max_delay, and libcfs_console_min_delay.
static int proc_cpt_table (struct ctl_table * table, int write, void __user * buffer, size_t * lenp, loff_t * ppos) [static]
Definition at line 463 of file module.c.
References __proc_cpt_table(), and lprocfs_call_handler().
static int proc_daemon_file (struct ctl_table * table, int write, void __user * buffer, size_t * lenp, loff_t * ppos) [static]
Definition at line 270 of file module.c.
References __proc_daemon_file(), and lprocfs_call_handler().
static int proc_debug_mb (struct ctl_table * table, int write, void __user * buffer, size_t * lenp, loff_t * ppos) [static]
Definition at line 296 of file module.c.
References __proc_debug_mb(), and lprocfs_call_handler().
static int proc_dobitmasks (struct ctl_table * table, int write, void __user * buffer, size_t * lenp, loff_t * ppos) [static]
Definition at line 226 of file module.c.
References __proc_dobitmasks(), and lprocfs_call_handler().
static int proc_dump_kernel (struct ctl_table * table, int write, void __user * buffer, size_t * lenp, loff_t * ppos) [static]
Definition at line 246 of file module.c.
References __proc_dump_kernel(), and lprocfs_call_handler().
static int proc_fail_loc (struct ctl_table * table, int write, void __user * buffer, size_t * lenp, loff_t * ppos) [static]
Definition at line 409 of file module.c.
References cfs_fail_loc, and cfs_race_waitq.
static void remove_proc (void) [static]
Definition at line 672 of file module.c.
References lnet_table_header.
Referenced by libcfs_exit().
Variable Documentation
struct ctl_table lnet_table[] [static]
Definition at line 470 of file module.c.
int max_watchdog_ratelimit = (24*60*60) [static]
Definition at line 234 of file module.c.
int min_watchdog_ratelimit [static]
Definition at line 233 of file module.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.