Lustre: libcfs/include/libcfs/libcfs_hash.h File Reference
libcfs/include/libcfs/libcfs_hash.h File Reference
#include <linux/hash.h>
Data Structures
union cfs_hash_lock
struct cfs_hash_bucket
cfs_hash_bucket is a container of:
lock, counter .
struct cfs_hash_bd
cfs_hash bucket descriptor, it's normally in stack of caller
struct cfs_hash
cfs_hash is a hash-table implementation for general purpose, it can support:
struct cfs_hash_lock_ops
struct cfs_hash_hlist_ops
struct cfs_hash_ops
Defines
#define CFS_GOLDEN_RATIO_PRIME_32 0x9e370001UL
#define CFS_GOLDEN_RATIO_PRIME_64 0x9e37fffffffc0001ULL
#define CFS_HASH_DEBUG_NONE 0
disable debug
#define CFS_HASH_DEBUG_1 1
record hash depth and output to console when it's too deep, computing overhead is low but consume more memory
#define CFS_HASH_DEBUG_2 2
expensive, check key validation
#define CFS_HASH_DEBUG_LEVEL CFS_HASH_DEBUG_NONE
#define CFS_HASH_NAME_LEN 16
default name length
#define CFS_HASH_BIGNAME_LEN 64
bigname for param tree
#define CFS_HASH_BKT_BITS 3
default bits of bucket
#define CFS_HASH_BITS_MAX 30
max bits of bucket
#define CFS_HASH_BITS_MIN CFS_HASH_BKT_BITS
#define CFS_HASH_DEFAULT
most used attributes
#define CFS_HASH_NBKT(hs) (1U << ((hs)->hs_cur_bits - (hs)->hs_bkt_bits))
total number of buckets in
#define CFS_HASH_RH_NBKT(hs) (1U << ((hs)->hs_rehash_bits - (hs)->hs_bkt_bits))
total number of buckets in while rehashing
#define CFS_HASH_BKT_NHLIST(hs) (1U << (hs)->hs_bkt_bits)
number of hlist for in bucket
#define CFS_HASH_NHLIST(hs) (1U << (hs)->hs_cur_bits)
total number of hlist in
#define CFS_HASH_RH_NHLIST(hs) (1U << (hs)->hs_rehash_bits)
total number of hlist in while rehashing
#define CFS_HASH_LOOP_HOG 1024
#define CFS_HASH_THETA_BITS 10
#define CFS_HASH_MIN_THETA (1U << (CFS_HASH_THETA_BITS - 1))
#define CFS_HASH_MAX_THETA (1U << (CFS_HASH_THETA_BITS + 1))
#define cfs_hash_for_each_bd(bds, n, i) for (i = 0; i < n && (bds)[i].bd_bucket != NULL; i++)
iterate over all buckets in (array of struct cfs_hash_bd)
#define cfs_hash_for_each_bucket(hs, bd, pos)
iterate over all buckets of
#define cfs_hash_bd_for_each_hlist(hs, bd, hlist)
iterate over all hlist of bucket
Typedefs
typedef int(* cfs_hash_for_each_cb_t)(struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *node, void *data)
typedef int(* cfs_hash_cond_opt_cb_t)(void *obj, void *data)
Enumerations
enum cfs_hash_tag {
CFS_HASH_NO_LOCK = 1 << 0, CFS_HASH_NO_BKTLOCK = 1 << 1, CFS_HASH_RW_BKTLOCK = 1 << 2, CFS_HASH_SPIN_BKTLOCK = 1 << 3,
CFS_HASH_ADD_TAIL = 1 << 4, CFS_HASH_NO_ITEMREF = 1 << 5, CFS_HASH_BIGNAME = 1 << 6, CFS_HASH_COUNTER = 1 << 7,
CFS_HASH_REHASH_KEY = 1 << 8, CFS_HASH_REHASH = 1 << 9, CFS_HASH_SHRINK = 1 << 10, CFS_HASH_ASSERT_EMPTY = 1 << 11,
CFS_HASH_DEPTH = 1 << 12, CFS_HASH_NBLK_CHANGE = 1 << 13
}
common hash attributes.
Functions
static int cfs_hash_with_no_lock (struct cfs_hash *hs)
static int cfs_hash_with_no_bktlock (struct cfs_hash *hs)
static int cfs_hash_with_rw_bktlock (struct cfs_hash *hs)
static int cfs_hash_with_spin_bktlock (struct cfs_hash *hs)
static int cfs_hash_with_add_tail (struct cfs_hash *hs)
static int cfs_hash_with_no_itemref (struct cfs_hash *hs)
static int cfs_hash_with_bigname (struct cfs_hash *hs)
static int cfs_hash_with_counter (struct cfs_hash *hs)
static int cfs_hash_with_rehash (struct cfs_hash *hs)
static int cfs_hash_with_rehash_key (struct cfs_hash *hs)
static int cfs_hash_with_shrink (struct cfs_hash *hs)
static int cfs_hash_with_assert_empty (struct cfs_hash *hs)
static int cfs_hash_with_depth (struct cfs_hash *hs)
static int cfs_hash_with_nblk_change (struct cfs_hash *hs)
static int cfs_hash_is_exiting (struct cfs_hash *hs)
static int cfs_hash_is_rehashing (struct cfs_hash *hs)
static int cfs_hash_is_iterating (struct cfs_hash *hs)
static int cfs_hash_bkt_size (struct cfs_hash *hs)
static unsigned cfs_hash_id (struct cfs_hash *hs, const void *key, unsigned mask)
static void * cfs_hash_key (struct cfs_hash *hs, struct hlist_node *hnode)
static void cfs_hash_keycpy (struct cfs_hash *hs, struct hlist_node *hnode, void *key)
static int cfs_hash_keycmp (struct cfs_hash *hs, const void *key, struct hlist_node *hnode)
Returns 1 on a match,.
static void * cfs_hash_object (struct cfs_hash *hs, struct hlist_node *hnode)
static void cfs_hash_get (struct cfs_hash *hs, struct hlist_node *hnode)
static void cfs_hash_put_locked (struct cfs_hash *hs, struct hlist_node *hnode)
static void cfs_hash_put (struct cfs_hash *hs, struct hlist_node *hnode)
static void cfs_hash_exit (struct cfs_hash *hs, struct hlist_node *hnode)
static void cfs_hash_lock (struct cfs_hash *hs, int excl)
static void cfs_hash_unlock (struct cfs_hash *hs, int excl)
static int cfs_hash_dec_and_lock (struct cfs_hash *hs, atomic_t *condition)
static void cfs_hash_bd_lock (struct cfs_hash *hs, struct cfs_hash_bd *bd, int excl)
static void cfs_hash_bd_unlock (struct cfs_hash *hs, struct cfs_hash_bd *bd, int excl)
void cfs_hash_bd_get (struct cfs_hash *hs, const void *key, struct cfs_hash_bd *bd)
operations on cfs_hash bucket (bd: bucket descriptor), they are normally for hash-table without rehash
static void cfs_hash_bd_get_and_lock (struct cfs_hash *hs, const void *key, struct cfs_hash_bd *bd, int excl)
static unsigned cfs_hash_bd_index_get (struct cfs_hash *hs, struct cfs_hash_bd *bd)
static void cfs_hash_bd_index_set (struct cfs_hash *hs, unsigned index, struct cfs_hash_bd *bd)
static void * cfs_hash_bd_extra_get (struct cfs_hash *hs, struct cfs_hash_bd *bd)
static __u32 cfs_hash_bd_version_get (struct cfs_hash_bd *bd)
static __u32 cfs_hash_bd_count_get (struct cfs_hash_bd *bd)
static int cfs_hash_bd_depmax_get (struct cfs_hash_bd *bd)
static int cfs_hash_bd_compare (struct cfs_hash_bd *bd1, struct cfs_hash_bd *bd2)
void cfs_hash_bd_add_locked (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode)
void cfs_hash_bd_del_locked (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode)
void cfs_hash_bd_move_locked (struct cfs_hash *hs, struct cfs_hash_bd *bd_old, struct cfs_hash_bd *bd_new, struct hlist_node *hnode)
static int cfs_hash_bd_dec_and_lock (struct cfs_hash *hs, struct cfs_hash_bd *bd, atomic_t *condition)
static struct hlist_head * cfs_hash_bd_hhead (struct cfs_hash *hs, struct cfs_hash_bd *bd)
struct hlist_node * cfs_hash_bd_lookup_locked (struct cfs_hash *hs, struct cfs_hash_bd *bd, const void *key)
struct hlist_node * cfs_hash_bd_peek_locked (struct cfs_hash *hs, struct cfs_hash_bd *bd, const void *key)
struct hlist_node * cfs_hash_bd_findadd_locked (struct cfs_hash *hs, struct cfs_hash_bd *bd, const void *key, struct hlist_node *hnode, int insist_add)
struct hlist_node * cfs_hash_bd_finddel_locked (struct cfs_hash *hs, struct cfs_hash_bd *bd, const void *key, struct hlist_node *hnode)
void cfs_hash_dual_bd_get (struct cfs_hash *hs, const void *key, struct cfs_hash_bd *bds)
operations on cfs_hash bucket (bd: bucket descriptor), they are safe for hash-table with rehash
void cfs_hash_dual_bd_lock (struct cfs_hash *hs, struct cfs_hash_bd *bds, int excl)
void cfs_hash_dual_bd_unlock (struct cfs_hash *hs, struct cfs_hash_bd *bds, int excl)
static void cfs_hash_dual_bd_get_and_lock (struct cfs_hash *hs, const void *key, struct cfs_hash_bd *bds, int excl)
struct hlist_node * cfs_hash_dual_bd_lookup_locked (struct cfs_hash *hs, struct cfs_hash_bd *bds, const void *key)
struct hlist_node * cfs_hash_dual_bd_findadd_locked (struct cfs_hash *hs, struct cfs_hash_bd *bds, const void *key, struct hlist_node *hnode, int insist_add)
struct hlist_node * cfs_hash_dual_bd_finddel_locked (struct cfs_hash *hs, struct cfs_hash_bd *bds, const void *key, struct hlist_node *hnode)
struct cfs_hash * cfs_hash_create (char *name, unsigned cur_bits, unsigned max_bits, unsigned bkt_bits, unsigned extra_bytes, unsigned min_theta, unsigned max_theta, struct cfs_hash_ops *ops, unsigned flags)
struct cfs_hash * cfs_hash_getref (struct cfs_hash *hs)
void cfs_hash_putref (struct cfs_hash *hs)
void cfs_hash_add (struct cfs_hash *hs, const void *key, struct hlist_node *hnode)
Add item to libcfs hash using .
int cfs_hash_add_unique (struct cfs_hash *hs, const void *key, struct hlist_node *hnode)
Add item to libcfs hash using .
void * cfs_hash_findadd_unique (struct cfs_hash *hs, const void *key, struct hlist_node *hnode)
Add item to libcfs hash using .
void * cfs_hash_del (struct cfs_hash *hs, const void *key, struct hlist_node *hnode)
Delete item from the libcfs hash using .
void * cfs_hash_del_key (struct cfs_hash *hs, const void *key)
Delete item given in libcfs hash .
void * cfs_hash_lookup (struct cfs_hash *hs, const void *key)
Lookup an item using in the libcfs hash and return it.
void cfs_hash_for_each (struct cfs_hash *hs, cfs_hash_for_each_cb_t, void *data)
void cfs_hash_for_each_safe (struct cfs_hash *hs, cfs_hash_for_each_cb_t, void *data)
int cfs_hash_for_each_nolock (struct cfs_hash *hs, cfs_hash_for_each_cb_t, void *data, int start)
int cfs_hash_for_each_empty (struct cfs_hash *hs, cfs_hash_for_each_cb_t, void *data)
For each hash bucket in the libcfs hash call the passed callback until all the hash buckets are empty.
void cfs_hash_for_each_key (struct cfs_hash *hs, const void *key, cfs_hash_for_each_cb_t, void *data)
void cfs_hash_cond_del (struct cfs_hash *hs, cfs_hash_cond_opt_cb_t, void *data)
Delete item from the libcfs hash when return true.
void cfs_hash_hlist_for_each (struct cfs_hash *hs, unsigned hindex, cfs_hash_for_each_cb_t, void *data)
int cfs_hash_is_empty (struct cfs_hash *hs)
__u64 cfs_hash_size_get (struct cfs_hash *hs)
void cfs_hash_rehash_cancel_locked (struct cfs_hash *hs)
Rehash the libcfs hash to the given .
void cfs_hash_rehash_cancel (struct cfs_hash *hs)
int cfs_hash_rehash (struct cfs_hash *hs, int do_rehash)
void cfs_hash_rehash_key (struct cfs_hash *hs, const void *old_key, void *new_key, struct hlist_node *hnode)
Rehash the object referenced by in the libcfs hash .
static void cfs_hash_key_validate (struct cfs_hash *hs, const void *key, struct hlist_node *hnode)
static void cfs_hash_bucket_validate (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode)
static int __cfs_hash_theta_int (int theta)
static int __cfs_hash_theta_frac (int theta)
static int __cfs_hash_theta (struct cfs_hash *hs)
static void __cfs_hash_set_theta (struct cfs_hash *hs, int min, int max)
void cfs_hash_debug_header (struct seq_file *m)
void cfs_hash_debug_str (struct cfs_hash *hs, struct seq_file *m)
static unsigned cfs_hash_djb2_hash (const void *key, size_t size, unsigned mask)
static unsigned cfs_hash_u32_hash (const __u32 key, unsigned mask)
static unsigned cfs_hash_u64_hash (const __u64 key, unsigned mask)
Define Documentation
#define CFS_GOLDEN_RATIO_PRIME_32 0x9e370001UL
Definition at line 58 of file libcfs_hash.h.
Referenced by cfs_hash_u32_hash().
#define CFS_GOLDEN_RATIO_PRIME_64 0x9e37fffffffc0001ULL
Definition at line 60 of file libcfs_hash.h.
Referenced by cfs_hash_u64_hash().
#define cfs_hash_bd_for_each_hlist (hs, bd, hlist)
Value:
for ((bd)->bd_offset = 0;                               \
             (bd)->bd_offset < CFS_HASH_BKT_NHLIST(hs) &&       \
             (hlist = cfs_hash_bd_hhead(hs, bd)) != NULL;       \
             (bd)->bd_offset++)
iterate over all hlist of bucket
Definition at line 854 of file libcfs_hash.h.
Referenced by cfs_hash_buckets_realloc(), cfs_hash_destroy(), cfs_hash_for_each_relax(), cfs_hash_for_each_tight(), cfs_hash_rehash_bd(), and lu_site_stats_get().
#define CFS_HASH_BIGNAME_LEN 64
bigname for param tree
Definition at line 112 of file libcfs_hash.h.
Referenced by cfs_hash_create(), cfs_hash_debug_header(), cfs_hash_debug_str(), and cfs_hash_destroy().
#define CFS_HASH_BITS_MAX 30
max bits of bucket
Definition at line 115 of file libcfs_hash.h.
#define CFS_HASH_BITS_MIN CFS_HASH_BKT_BITS
Definition at line 116 of file libcfs_hash.h.
#define CFS_HASH_BKT_BITS 3
default bits of bucket
Definition at line 114 of file libcfs_hash.h.
#define CFS_HASH_BKT_NHLIST (hs) (1U << (hs)->hs_bkt_bits)
number of hlist for in bucket
Definition at line 328 of file libcfs_hash.h.
Referenced by cfs_hash_bd_index_set(), and cfs_hash_bkt_size().
#define CFS_HASH_DEBUG_1 1
record hash depth and output to console when it's too deep, computing overhead is low but consume more memory
Definition at line 66 of file libcfs_hash.h.
#define CFS_HASH_DEBUG_2 2
expensive, check key validation
Definition at line 68 of file libcfs_hash.h.
#define CFS_HASH_DEBUG_LEVEL CFS_HASH_DEBUG_NONE
Definition at line 70 of file libcfs_hash.h.
#define CFS_HASH_DEBUG_NONE 0
disable debug
Definition at line 63 of file libcfs_hash.h.
#define CFS_HASH_DEFAULT
Value:
(CFS_HASH_RW_BKTLOCK | \
                                CFS_HASH_COUNTER | CFS_HASH_REHASH)
most used attributes
Definition at line 165 of file libcfs_hash.h.
Referenced by class_setup(), ldlm_init_export(), ldlm_init_flock_export(), lod_pools_init(), lov_setup(), lquota_site_alloc(), nodemap_init_hash(), osc_quota_setup(), ptlrpc_connection_init(), and qmt_pool_init().
#define cfs_hash_for_each_bd (bds, n, i) for (i = 0; i < n && (bds)[i].bd_bucket != NULL; i++)
iterate over all buckets in (array of struct cfs_hash_bd)
Definition at line 844 of file libcfs_hash.h.
Referenced by cfs_hash_for_each_key(), cfs_hash_multi_bd_findadd_locked(), cfs_hash_multi_bd_finddel_locked(), cfs_hash_multi_bd_lock(), cfs_hash_multi_bd_lookup_locked(), and cfs_hash_multi_bd_unlock().
#define cfs_hash_for_each_bucket (hs, bd, pos)
Value:
for (pos = 0;                                           \
             pos < CFS_HASH_NBKT(hs) &&                         \
             ((bd)->bd_bucket = (hs)->hs_buckets[pos]) != NULL; pos++)
iterate over all buckets of
Definition at line 848 of file libcfs_hash.h.
Referenced by cfs_hash_destroy(), cfs_hash_for_each_relax(), cfs_hash_for_each_tight(), cfs_hash_rehash_worker(), ldlm_namespace_new(), lu_site_init(), lu_site_purge(), and lu_site_stats_get().
#define CFS_HASH_LOOP_HOG 1024
Definition at line 699 of file libcfs_hash.h.
Referenced by cfs_hash_for_each_exit(), cfs_hash_for_each_tight(), cfs_hash_rehash_inline(), and cfs_hash_rehash_worker().
#define CFS_HASH_MAX_THETA (1U << (CFS_HASH_THETA_BITS + 1))
Definition at line 775 of file libcfs_hash.h.
Referenced by cl_env_store_init(), class_setup(), ldlm_init_export(), ldlm_init_flock_export(), ldlm_namespace_new(), lod_pools_init(), lov_setup(), lquota_site_alloc(), nodemap_init_hash(), osc_quota_setup(), ptlrpc_connection_init(), and qmt_pool_init().
#define CFS_HASH_MIN_THETA (1U << (CFS_HASH_THETA_BITS - 1))
Definition at line 774 of file libcfs_hash.h.
Referenced by cl_env_store_init(), class_setup(), ldlm_init_export(), ldlm_init_flock_export(), ldlm_namespace_new(), lod_pools_init(), lov_setup(), lquota_site_alloc(), nodemap_init_hash(), osc_quota_setup(), ptlrpc_connection_init(), and qmt_pool_init().
#define CFS_HASH_NAME_LEN 16
default name length
Definition at line 111 of file libcfs_hash.h.
Referenced by cfs_hash_create(), and cfs_hash_destroy().
#define CFS_HASH_NBKT (hs) (1U << ((hs)->hs_cur_bits - (hs)->hs_bkt_bits))
total number of buckets in
Definition at line 320 of file libcfs_hash.h.
Referenced by cfs_hash_create(), cfs_hash_destroy(), cfs_hash_full_nbkt(), cfs_hash_rehash_worker(), ldlm_res_hop_fid_hash(), lu_obj_hop_hash(), and lu_site_purge().
#define CFS_HASH_NHLIST (hs) (1U << (hs)->hs_cur_bits)
total number of hlist in
Definition at line 331 of file libcfs_hash.h.
Referenced by cfs_hash_hlist_for_each(), lu_site_stats_seq_print(), and vvp_pgcache_find().
#define CFS_HASH_RH_NBKT (hs) (1U << ((hs)->hs_rehash_bits - (hs)->hs_bkt_bits))
total number of buckets in while rehashing
Definition at line 324 of file libcfs_hash.h.
Referenced by cfs_hash_full_nbkt(), and cfs_hash_rehash_worker().
#define CFS_HASH_RH_NHLIST (hs) (1U << (hs)->hs_rehash_bits)
total number of hlist in while rehashing
Definition at line 334 of file libcfs_hash.h.
#define CFS_HASH_THETA_BITS 10
Definition at line 773 of file libcfs_hash.h.
Referenced by __cfs_hash_theta(), __cfs_hash_theta_frac(), __cfs_hash_theta_int(), and cfs_hash_create().
Typedef Documentation
typedef int(* cfs_hash_cond_opt_cb_t)(void *obj, void *data)
Definition at line 720 of file libcfs_hash.h.
typedef int(* cfs_hash_for_each_cb_t)(struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *node, void *data)
Definition at line 701 of file libcfs_hash.h.
Enumeration Type Documentation
enum cfs_hash_tag
common hash attributes.
Enumerator:
CFS_HASH_NO_LOCK
don't need any lock, caller will protect operations with it's own lock.
With this flag: . CFS_HASH_NO_BKTLOCK, CFS_HASH_RW_BKTLOCK, CFS_HASH_SPIN_BKTLOCK will be ignored. . Some functions will be disabled with this flag, i.e: cfs_hash_for_each_empty, cfs_hash_rehash
CFS_HASH_NO_BKTLOCK
no bucket lock, use one spinlock to protect the whole hash
CFS_HASH_RW_BKTLOCK
rwlock to protect bucket
CFS_HASH_SPIN_BKTLOCK
spinlock to protect bucket
CFS_HASH_ADD_TAIL
always add new item to tail
CFS_HASH_NO_ITEMREF
hash-table doesn't have refcount on item
CFS_HASH_BIGNAME
big name for param-tree
CFS_HASH_COUNTER
track global count
CFS_HASH_REHASH_KEY
rehash item by new key
CFS_HASH_REHASH
Enable dynamic hash resizing.
CFS_HASH_SHRINK
can shrink hash-size
CFS_HASH_ASSERT_EMPTY
assert hash is empty on exit
CFS_HASH_DEPTH
record hlist depth
CFS_HASH_NBLK_CHANGE
rehash is always scheduled in a different thread, so current change on hash table is non-blocking
Definition at line 121 of file libcfs_hash.h.
Function Documentation
static void __cfs_hash_set_theta (struct cfs_hash * hs, int min, int max) [inline, static]
Definition at line 797 of file libcfs_hash.h.
References cfs_hash::hs_max_theta, cfs_hash::hs_min_theta, and LASSERT.
Referenced by cfs_hash_create().
static int __cfs_hash_theta (struct cfs_hash * hs) [inline, static]
Definition at line 790 of file libcfs_hash.h.
References CFS_HASH_THETA_BITS, cfs_hash::hs_count, and cfs_hash::hs_cur_bits.
Referenced by cfs_hash_debug_str(), cfs_hash_rehash_bits(), and cfs_hash_rehash_worker().
static int __cfs_hash_theta_frac (int theta) [inline, static]
Definition at line 784 of file libcfs_hash.h.
References __cfs_hash_theta_int(), and CFS_HASH_THETA_BITS.
Referenced by cfs_hash_debug_str().
static int __cfs_hash_theta_int (int theta) [inline, static]
Definition at line 778 of file libcfs_hash.h.
References CFS_HASH_THETA_BITS.
Referenced by __cfs_hash_theta_frac(), and cfs_hash_debug_str().
void cfs_hash_add (struct cfs_hash * hs, const void * key, struct hlist_node * hnode)
Add item to libcfs hash using .
The registered ops->hs_get function will be called when the item is added.
Definition at line 1204 of file hash.c.
References cfs_hash_bd_add_locked(), cfs_hash_bd_get_and_lock(), cfs_hash_bd_unlock(), cfs_hash_key_validate(), cfs_hash_lock(), cfs_hash_rehash(), cfs_hash_rehash_bits(), cfs_hash_rehash_inline(), cfs_hash_unlock(), hlist_unhashed(), and LASSERT.
Referenced by ldlm_flock_blocking_link(), ldlm_process_flock_lock(), and mdt_intent_lock_replace().
int cfs_hash_add_unique (struct cfs_hash * hs, const void * key, struct hlist_node * hnode)
Add item to libcfs hash using .
The registered ops->hs_get function will be called if the item was added. Returns 0 on success or -EALREADY on key collisions.
Definition at line 1259 of file hash.c.
References cfs_hash_find_or_add().
Referenced by cl_env_attach(), class_new_export(), lod_pool_new(), lov_pool_new(), nodemap_create(), osc_quota_setdq(), qmt_pool_alloc(), and tgt_clients_data_init().
void cfs_hash_bd_add_locked (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode)
Definition at line 529 of file hash.c.
References cfs_hash_bd::bd_bucket, cfs_hash_bd_dep_record(), cfs_hash_get(), cfs_hash_with_counter(), cfs_hash_with_no_itemref(), cfs_hash_hlist_ops::hop_hnode_add, cfs_hash::hs_count, cfs_hash::hs_hops, cfs_hash_bucket::hsb_count, cfs_hash_bucket::hsb_version, and unlikely.
Referenced by cfs_hash_add(), cfs_hash_bd_lookup_intent(), cfs_hash_multi_bd_findadd_locked(), cfs_hash_rehash_key(), ldlm_resource_get(), lu_object_assign_fid(), lu_object_find_try(), and lu_object_new().
static int cfs_hash_bd_compare (struct cfs_hash_bd * bd1, struct cfs_hash_bd * bd2) [inline, static]
Definition at line 598 of file libcfs_hash.h.
References cfs_hash_bd::bd_bucket, cfs_hash_bd::bd_offset, and cfs_hash_bucket::hsb_index.
Referenced by cfs_hash_bd_move_locked(), and cfs_hash_bd_order().
static __u32 cfs_hash_bd_count_get (struct cfs_hash_bd * bd) [inline, static]
Definition at line 585 of file libcfs_hash.h.
References cfs_hash_bd::bd_bucket, and cfs_hash_bucket::hsb_count.
Referenced by __ldlm_resource_putref_final(), ldlm_resource_get(), and lu_site_stats_get().
static int cfs_hash_bd_dec_and_lock (struct cfs_hash * hs, struct cfs_hash_bd * bd, atomic_t * condition) [inline, static]
Definition at line 618 of file libcfs_hash.h.
References cfs_hash_bd::bd_bucket, cfs_hash_with_spin_bktlock(), cfs_hash_bucket::hsb_lock, LASSERT, and cfs_hash_lock::spin.
Referenced by ldlm_resource_putref(), and lu_object_put().
void cfs_hash_bd_del_locked (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode)
Definition at line 549 of file hash.c.
References cfs_hash_bd::bd_bucket, cfs_hash_put_locked(), cfs_hash_with_counter(), cfs_hash_with_no_itemref(), cfs_hash_hlist_ops::hop_hnode_del, cfs_hash::hs_count, cfs_hash::hs_hops, cfs_hash_bucket::hsb_count, cfs_hash_bucket::hsb_version, LASSERT, and unlikely.
Referenced by __ldlm_resource_putref_final(), cfs_hash_bd_lookup_intent(), cfs_hash_cond_del_locked(), cfs_hash_del(), cfs_hash_destroy(), lqe_iter_cb(), lu_object_put(), lu_object_unhash(), lu_site_purge(), and nodemap_cleanup_iter_cb().
static int cfs_hash_bd_depmax_get (struct cfs_hash_bd * bd) [inline, static]
Definition at line 592 of file libcfs_hash.h.
References cfs_hash_bd::bd_bucket, and cfs_hash_bucket::hsb_depmax.
Referenced by lu_site_stats_get().
static void* cfs_hash_bd_extra_get (struct cfs_hash * hs, struct cfs_hash_bd * bd) [inline, static]
Definition at line 571 of file libcfs_hash.h.
References cfs_hash_bd::bd_bucket, cfs_hash_bkt_size(), and cfs_hash::hs_extra_bytes.
Referenced by htable_lookup(), ldlm_namespace_new(), ldlm_resource_get(), lu_object_put(), lu_object_unhash(), lu_site_bkt_from_fid(), lu_site_init(), lu_site_purge(), and lu_site_stats_get().
struct hlist_node* cfs_hash_bd_findadd_locked (struct cfs_hash * hs, struct cfs_hash_bd * bd, const void * key, struct hlist_node * hnode, int insist_add) [read]
struct hlist_node* cfs_hash_bd_finddel_locked (struct cfs_hash * hs, struct cfs_hash_bd * bd, const void * key, struct hlist_node * hnode) [read]
void cfs_hash_bd_get (struct cfs_hash * hs, const void * key, struct cfs_hash_bd * bd)
operations on cfs_hash bucket (bd: bucket descriptor), they are normally for hash-table without rehash
Definition at line 491 of file hash.c.
References cfs_hash_bd_from_key(), cfs_hash::hs_buckets, cfs_hash::hs_cur_bits, cfs_hash::hs_rehash_bits, cfs_hash::hs_rehash_buckets, LASSERT, and likely.
Referenced by cfs_hash_bd_get_and_lock(), cfs_hash_multi_bd_findadd_locked(), cfs_hash_rehash_key(), ldlm_resource_putref(), lu_object_put(), lu_site_bkt_from_fid(), and lu_site_purge().
static void cfs_hash_bd_get_and_lock (struct cfs_hash * hs, const void * key, struct cfs_hash_bd * bd, int excl) [inline, static]
Definition at line 549 of file libcfs_hash.h.
References cfs_hash_bd_get(), and cfs_hash_bd_lock().
Referenced by cfs_hash_add(), ldlm_resource_get(), lu_object_assign_fid(), lu_object_find_try(), lu_object_new(), and lu_object_unhash().
static struct hlist_head* cfs_hash_bd_hhead (struct cfs_hash * hs, struct cfs_hash_bd * bd) [static, read]
Definition at line 626 of file libcfs_hash.h.
References cfs_hash_hlist_ops::hop_hhead, and cfs_hash::hs_hops.
Referenced by cfs_hash_bd_lookup_intent(), cfs_hash_for_each_key(), and cfs_hash_hlist_for_each().
static unsigned cfs_hash_bd_index_get (struct cfs_hash * hs, struct cfs_hash_bd * bd) [inline, static]
Definition at line 557 of file libcfs_hash.h.
References cfs_hash_bd::bd_bucket, cfs_hash_bd::bd_offset, cfs_hash::hs_bkt_bits, and cfs_hash_bucket::hsb_index.
static void cfs_hash_bd_index_set (struct cfs_hash * hs, unsigned index, struct cfs_hash_bd * bd) [inline, static]
Definition at line 563 of file libcfs_hash.h.
References cfs_hash_bd::bd_bucket, cfs_hash_bd::bd_offset, CFS_HASH_BKT_NHLIST, cfs_hash::hs_bkt_bits, and cfs_hash::hs_buckets.
Referenced by cfs_hash_hlist_for_each().
static void cfs_hash_bd_lock (struct cfs_hash * hs, struct cfs_hash_bd * bd, int excl) [inline, static]
Definition at line 529 of file libcfs_hash.h.
References cfs_hash_bd::bd_bucket, cfs_hash_lock_ops::hs_bkt_lock, cfs_hash::hs_lops, and cfs_hash_bucket::hsb_lock.
Referenced by cfs_hash_bd_get_and_lock(), cfs_hash_debug_str(), cfs_hash_destroy(), cfs_hash_for_each_relax(), cfs_hash_for_each_tight(), cfs_hash_hlist_for_each(), cfs_hash_multi_bd_lock(), ldlm_resource_get(), lu_object_find_try(), lu_site_purge(), and lu_site_stats_get().
struct hlist_node* cfs_hash_bd_lookup_locked (struct cfs_hash * hs, struct cfs_hash_bd * bd, const void * key) [read]
Definition at line 667 of file hash.c.
References cfs_hash_bd_lookup_intent(), and CFS_HS_LOOKUP_IT_FIND.
Referenced by ldlm_resource_get().
void cfs_hash_bd_move_locked (struct cfs_hash * hs, struct cfs_hash_bd * bd_old, struct cfs_hash_bd * bd_new, struct hlist_node * hnode)
Definition at line 570 of file hash.c.
References cfs_hash_bd::bd_bucket, cfs_hash_bd_compare(), cfs_hash_bd_dep_record(), cfs_hash_hlist_ops::hop_hnode_add, cfs_hash_hlist_ops::hop_hnode_del, cfs_hash::hs_hops, cfs_hash_bucket::hsb_count, cfs_hash_bucket::hsb_version, LASSERT, and unlikely.
Referenced by cfs_hash_rehash_bd(), and cfs_hash_rehash_key().
struct hlist_node* cfs_hash_bd_peek_locked (struct cfs_hash * hs, struct cfs_hash_bd * bd, const void * key) [read]
Definition at line 676 of file hash.c.
References cfs_hash_bd_lookup_intent(), and CFS_HS_LOOKUP_IT_PEEK.
Referenced by htable_lookup().
static void cfs_hash_bd_unlock (struct cfs_hash * hs, struct cfs_hash_bd * bd, int excl) [inline, static]
Definition at line 535 of file libcfs_hash.h.
References cfs_hash_bd::bd_bucket, cfs_hash_lock_ops::hs_bkt_unlock, cfs_hash::hs_lops, and cfs_hash_bucket::hsb_lock.
Referenced by cfs_hash_add(), cfs_hash_debug_str(), cfs_hash_destroy(), cfs_hash_for_each_relax(), cfs_hash_for_each_tight(), cfs_hash_hlist_for_each(), cfs_hash_multi_bd_unlock(), ldlm_resource_get(), ldlm_resource_putref(), lu_object_assign_fid(), lu_object_find_try(), lu_object_new(), lu_object_put(), lu_object_unhash(), lu_site_purge(), and lu_site_stats_get().
static __u32 cfs_hash_bd_version_get (struct cfs_hash_bd * bd) [inline, static]
Definition at line 578 of file libcfs_hash.h.
References cfs_hash_bd::bd_bucket, and cfs_hash_bucket::hsb_version.
Referenced by cfs_hash_for_each_relax(), htable_lookup(), and ldlm_resource_get().
static int cfs_hash_bkt_size (struct cfs_hash * hs) [inline, static]
Definition at line 446 of file libcfs_hash.h.
References CFS_HASH_BKT_NHLIST, cfs_hash_hlist_ops::hop_hhead_size, cfs_hash::hs_extra_bytes, cfs_hash::hs_hops, and offsetof.
Referenced by cfs_hash_bd_extra_get(), cfs_hash_buckets_realloc(), cfs_hash_destroy(), and cfs_hash_rehash_worker().
static void cfs_hash_bucket_validate (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode) [inline, static]
Definition at line 768 of file libcfs_hash.h.
Referenced by cfs_hash_for_each_key(), cfs_hash_for_each_relax(), cfs_hash_for_each_tight(), and cfs_hash_rehash_bd().
void cfs_hash_cond_del (struct cfs_hash * hs, cfs_hash_cond_opt_cb_t func, void * data)
Delete item from the libcfs hash when return true.
The write lock being hold during loop for each bucket to avoid any object be reference.
Definition at line 1499 of file hash.c.
References cfs_hash_cond_del_locked(), cfs_hash_for_each_tight(), and cfs_hash_cond_arg::func.
struct cfs_hash* cfs_hash_create (char * name, unsigned cur_bits, unsigned max_bits, unsigned bkt_bits, unsigned extra_bytes, unsigned min_theta, unsigned max_theta, struct cfs_hash_ops * ops, unsigned flags) [read]
Definition at line 1003 of file hash.c.
References __cfs_hash_set_theta(), CFS_HASH_BIGNAME, CFS_HASH_BIGNAME_LEN, cfs_hash_buckets_realloc(), CFS_HASH_COUNTER, cfs_hash_depth_wi_init(), cfs_hash_hlist_setup(), cfs_hash_lock_setup(), CFS_HASH_NAME_LEN, CFS_HASH_NBKT, CFS_HASH_NO_LOCK, CFS_HASH_REHASH, CFS_HASH_REHASH_KEY, cfs_hash_rehash_worker(), CFS_HASH_THETA_BITS, cfs_hash_with_rehash(), cfs_wi_init(), CLASSERT, ENTRY, ergo, cfs_hash::hs_bkt_bits, cfs_hash::hs_buckets, cfs_hash::hs_count, cfs_hash::hs_cur_bits, cfs_hash::hs_extra_bytes, cfs_hash::hs_flags, cfs_hash_ops::hs_get, cfs_hash_ops::hs_hash, cfs_hash_ops::hs_key, cfs_hash_ops::hs_keycmp, cfs_hash_ops::hs_keycpy, cfs_hash::hs_max_bits, cfs_hash::hs_min_bits, cfs_hash::hs_name, cfs_hash_ops::hs_object, cfs_hash::hs_ops, cfs_hash_ops::hs_put, cfs_hash_ops::hs_put_locked, cfs_hash::hs_refcount, cfs_hash::hs_rehash_bits, cfs_hash::hs_rehash_wi, LASSERT, LIBCFS_ALLOC, LIBCFS_FREE, offsetof, RETURN, and strlcpy().
Referenced by cl_env_store_init(), class_setup(), ldlm_init_export(), ldlm_init_flock_export(), ldlm_namespace_new(), lod_pools_init(), lov_setup(), lquota_site_alloc(), lu_site_init(), nodemap_init_hash(), osc_quota_setup(), ptlrpc_connection_init(), and qmt_pool_init().
void cfs_hash_debug_header (struct seq_file * m)
Definition at line 2042 of file hash.c.
References CFS_HASH_BIGNAME_LEN.
void cfs_hash_debug_str (struct cfs_hash * hs, struct seq_file * m)
Definition at line 2073 of file hash.c.
References __cfs_hash_theta(), __cfs_hash_theta_frac(), __cfs_hash_theta_int(), cfs_hash_bd::bd_bucket, cfs_hash_bd_lock(), cfs_hash_bd_unlock(), CFS_HASH_BIGNAME_LEN, cfs_hash_full_bkts(), cfs_hash_full_nbkt(), cfs_hash_lock(), cfs_hash_unlock(), cfs_hash::hs_cur_bits, cfs_hash::hs_flags, cfs_hash::hs_max_bits, cfs_hash::hs_max_theta, cfs_hash::hs_min_bits, cfs_hash::hs_min_theta, cfs_hash::hs_name, cfs_hash::hs_rehash_count, cfs_hash_bucket::hsb_count, cfs_hash_bucket::hsb_depmax, and max.
static int cfs_hash_dec_and_lock (struct cfs_hash * hs, atomic_t * condition) [inline, static]
Definition at line 522 of file libcfs_hash.h.
References cfs_hash_with_no_bktlock(), cfs_hash::hs_lock, LASSERT, and cfs_hash_lock::spin.
void* cfs_hash_del (struct cfs_hash * hs, const void * key, struct hlist_node * hnode)
Delete item from the libcfs hash using .
The is required to ensure the correct hash bucket is locked since there is no direct linkage from the item to the bucket. The object removed from the hash will be returned and obs->hs_put is called on the removed object.
Definition at line 1291 of file hash.c.
References cfs_hash_bd::bd_bucket, cfs_hash_bd_del_locked(), cfs_hash_dual_bd_finddel_locked(), cfs_hash_dual_bd_get_and_lock(), cfs_hash_dual_bd_unlock(), cfs_hash_lock(), cfs_hash_object(), cfs_hash_rehash(), cfs_hash_rehash_bits(), cfs_hash_rehash_inline(), cfs_hash_unlock(), and hlist_unhashed().
Referenced by cfs_hash_del_key(), cl_env_do_detach(), class_disconnect(), class_new_export(), class_unlink_export(), ldlm_flock_blocking_unlink(), ldlm_lock_destroy_internal(), qmt_pool_fini(), and tgt_client_free().
void* cfs_hash_del_key (struct cfs_hash * hs, const void * key)
Delete item given in libcfs hash .
The first found in the hash will be removed, if the key exists multiple times in the hash this function must be called once per key. The removed object will be returned and ops->hs_put is called on the removed object.
Definition at line 1331 of file hash.c.
References cfs_hash_del().
Referenced by lod_pool_del(), lov_pool_del(), nodemap_del(), and osc_quota_setdq().
static unsigned cfs_hash_djb2_hash (const void * key, size_t size, unsigned mask) [inline, static]
Definition at line 813 of file libcfs_hash.h.
References LASSERT.
Referenced by conn_hashfn(), gen_hash(), nid_hash(), nodemap_hashfn(), pool_hashfn(), and uuid_hash().
struct hlist_node* cfs_hash_dual_bd_findadd_locked (struct cfs_hash * hs, struct cfs_hash_bd * bds, const void * key, struct hlist_node * hnode, int insist_add) [read]
Definition at line 853 of file hash.c.
References cfs_hash_multi_bd_findadd_locked().
Referenced by cfs_hash_find_or_add().
struct hlist_node* cfs_hash_dual_bd_finddel_locked (struct cfs_hash * hs, struct cfs_hash_bd * bds, const void * key, struct hlist_node * hnode) [read]
Definition at line 862 of file hash.c.
References cfs_hash_multi_bd_finddel_locked().
Referenced by cfs_hash_del(), and cfs_hash_rehash_key().
void cfs_hash_dual_bd_get (struct cfs_hash * hs, const void * key, struct cfs_hash_bd * bds)
operations on cfs_hash bucket (bd: bucket descriptor), they are safe for hash-table with rehash
Definition at line 814 of file hash.c.
References cfs_hash_bd::bd_bucket, cfs_hash_bd_from_key(), cfs_hash_bd_order(), cfs_hash::hs_buckets, cfs_hash::hs_cur_bits, cfs_hash::hs_rehash_bits, cfs_hash::hs_rehash_buckets, LASSERT, and likely.
Referenced by cfs_hash_dual_bd_get_and_lock(), and cfs_hash_rehash_key().
static void cfs_hash_dual_bd_get_and_lock (struct cfs_hash * hs, const void * key, struct cfs_hash_bd * bds, int excl) [inline, static]
Definition at line 657 of file libcfs_hash.h.
References cfs_hash_dual_bd_get(), and cfs_hash_dual_bd_lock().
Referenced by cfs_hash_del(), cfs_hash_find_or_add(), cfs_hash_for_each_key(), and cfs_hash_lookup().
void cfs_hash_dual_bd_lock (struct cfs_hash * hs, struct cfs_hash_bd * bds, int excl)
Definition at line 834 of file hash.c.
References cfs_hash_multi_bd_lock().
Referenced by cfs_hash_dual_bd_get_and_lock().
struct hlist_node* cfs_hash_dual_bd_lookup_locked (struct cfs_hash * hs, struct cfs_hash_bd * bds, const void * key) [read]
Definition at line 846 of file hash.c.
References cfs_hash_multi_bd_lookup_locked().
Referenced by cfs_hash_lookup().
void cfs_hash_dual_bd_unlock (struct cfs_hash * hs, struct cfs_hash_bd * bds, int excl)
Definition at line 840 of file hash.c.
References cfs_hash_multi_bd_unlock().
Referenced by cfs_hash_del(), cfs_hash_find_or_add(), cfs_hash_for_each_key(), and cfs_hash_lookup().
static void cfs_hash_exit (struct cfs_hash * hs, struct hlist_node * hnode) [inline, static]
Definition at line 506 of file libcfs_hash.h.
References cfs_hash_ops::hs_exit, and cfs_hash::hs_ops.
Referenced by cfs_hash_destroy().
void* cfs_hash_findadd_unique (struct cfs_hash * hs, const void * key, struct hlist_node * hnode)
Add item to libcfs hash using .
If this already exists in the hash then ops->hs_get will be called on the conflicting entry and that entry will be returned to the caller. Otherwise ops->hs_get is called on the item which was added.
Definition at line 1274 of file hash.c.
References cfs_hash_find_or_add(), and cfs_hash_object().
Referenced by lqe_locate(), and ptlrpc_connection_get().
void cfs_hash_for_each (struct cfs_hash * hs, cfs_hash_for_each_cb_t , void * data)
Definition at line 1511 of file hash.c.
References cfs_hash_for_each_tight().
Referenced by lu_site_print().
int cfs_hash_for_each_empty (struct cfs_hash * hs, cfs_hash_for_each_cb_t func, void * data)
For each hash bucket in the libcfs hash call the passed callback until all the hash buckets are empty.
The passed callback or the previously registered callback hs->hs_put must remove the item from the hash. You may either use the cfs_hash_del() or hlist_del() functions. No rwlocks will be held during the callback it is safe to sleep if needed. This function will not terminate until the hash is empty. Note it is still possible to concurrently add new items in to the hash. It is the callers responsibility to ensure the required locking is in place to prevent concurrent insertions.
Definition at line 1698 of file hash.c.
References CDEBUG, cfs_hash_for_each_enter(), cfs_hash_for_each_exit(), cfs_hash_for_each_relax(), cfs_hash_with_no_lock(), D_INFO, ENTRY, cfs_hash_ops::hs_get, cfs_hash::hs_name, cfs_hash::hs_ops, cfs_hash_ops::hs_put, cfs_hash_ops::hs_put_locked, and RETURN.
Referenced by ldlm_export_cancel_locks().
void cfs_hash_for_each_key (struct cfs_hash * hs, const void * key, cfs_hash_for_each_cb_t , void * data)
Definition at line 1758 of file hash.c.
References cfs_hash_bd_hhead(), cfs_hash_bucket_validate(), cfs_hash_dual_bd_get_and_lock(), cfs_hash_dual_bd_unlock(), cfs_hash_for_each_bd, cfs_hash_keycmp(), cfs_hash_lock(), cfs_hash_unlock(), and hlist_for_each.
Referenced by ldlm_flock_deadlock(), and lprocfs_mdt_open_files_seq_show().
int cfs_hash_for_each_nolock (struct cfs_hash * hs, cfs_hash_for_each_cb_t , void * data, int start)
Definition at line 1663 of file hash.c.
References cfs_hash_for_each_enter(), cfs_hash_for_each_exit(), cfs_hash_for_each_relax(), cfs_hash_with_no_itemref(), cfs_hash_with_no_lock(), cfs_hash_with_rehash_key(), ENTRY, cfs_hash_ops::hs_get, cfs_hash::hs_ops, cfs_hash_ops::hs_put, cfs_hash_ops::hs_put_locked, and RETURN.
Referenced by ldlm_cli_cancel_unused(), ldlm_namespace_cleanup(), ldlm_namespace_dump(), ldlm_namespace_foreach(), ldlm_reprocess_all_ns(), and osc_import_event().
void cfs_hash_for_each_safe (struct cfs_hash * hs, cfs_hash_for_each_cb_t , void * data)
Definition at line 1519 of file hash.c.
References cfs_hash_for_each_tight().
Referenced by lqe_cleanup(), nm_member_revoke_all(), nodemap_config_cleanup(), nodemap_config_set_active(), and qsd_pending_updates().
static void cfs_hash_get (struct cfs_hash * hs, struct hlist_node * hnode) [inline, static]
Definition at line 488 of file libcfs_hash.h.
References cfs_hash_ops::hs_get, and cfs_hash::hs_ops.
Referenced by cfs_hash_bd_add_locked(), cfs_hash_bd_lookup_intent(), cfs_hash_for_each_relax(), htable_lookup(), and vvp_pgcache_obj_get().
struct cfs_hash* cfs_hash_getref (struct cfs_hash * hs) [read]
Definition at line 1140 of file hash.c.
References cfs_hash::hs_refcount.
Referenced by class_new_export(), class_unlink_export(), obd_export_evict_by_nid(), obd_export_evict_by_uuid(), tgt_clients_data_init(), tgt_reply_data_init(), and update_recovery_update_ses().
void cfs_hash_hlist_for_each (struct cfs_hash * hs, unsigned hindex, cfs_hash_for_each_cb_t , void * data)
Definition at line 1723 of file hash.c.
References cfs_hash_bd_hhead(), cfs_hash_bd_index_set(), cfs_hash_bd_lock(), cfs_hash_bd_unlock(), cfs_hash_for_each_enter(), cfs_hash_for_each_exit(), cfs_hash_lock(), CFS_HASH_NHLIST, cfs_hash_unlock(), and hlist_for_each.
Referenced by vvp_pgcache_obj().
static unsigned cfs_hash_id (struct cfs_hash * hs, const void * key, unsigned mask) [inline, static]
Definition at line 454 of file libcfs_hash.h.
References cfs_hash_ops::hs_hash, and cfs_hash::hs_ops.
Referenced by cfs_hash_bd_from_key().
int cfs_hash_is_empty (struct cfs_hash * hs)
Definition at line 1535 of file hash.c.
References cfs_hash_for_each_tight(), cfs_hash_peek(), and empty.
Referenced by mgs_device_fini(), mgs_init0(), ofd_stack_fini(), and osd_device_free().
static int cfs_hash_is_exiting (struct cfs_hash * hs) [inline, static]
Definition at line 428 of file libcfs_hash.h.
References cfs_hash::hs_exiting.
Referenced by cfs_hash_destroy(), cfs_hash_for_each_enter(), cfs_hash_rehash_bits(), and cfs_hash_rehash_worker().
static int cfs_hash_is_iterating (struct cfs_hash * hs) [inline, static]
Definition at line 440 of file libcfs_hash.h.
References cfs_hash::hs_iterating, and cfs_hash::hs_iterators.
Referenced by cfs_hash_destroy(), cfs_hash_rehash_bits(), and cfs_hash_rehash_worker().
static int cfs_hash_is_rehashing (struct cfs_hash * hs) [inline, static]
Definition at line 434 of file libcfs_hash.h.
References cfs_hash::hs_rehash_bits.
Referenced by cfs_hash_for_each_enter(), cfs_hash_for_each_relax(), cfs_hash_for_each_tight(), cfs_hash_rehash_bits(), cfs_hash_rehash_cancel_locked(), and cfs_hash_rehash_worker().
static void* cfs_hash_key (struct cfs_hash * hs, struct hlist_node * hnode) [inline, static]
Definition at line 460 of file libcfs_hash.h.
References cfs_hash_ops::hs_key, and cfs_hash::hs_ops.
Referenced by cfs_hash_rehash_bd().
static void cfs_hash_key_validate (struct cfs_hash * hs, const void * key, struct hlist_node * hnode) [inline, static]
Definition at line 764 of file libcfs_hash.h.
Referenced by cfs_hash_add(), and cfs_hash_find_or_add().
static int cfs_hash_keycmp (struct cfs_hash * hs, const void * key, struct hlist_node * hnode) [inline, static]
Returns 1 on a match,.
Definition at line 476 of file libcfs_hash.h.
References cfs_hash_ops::hs_keycmp, and cfs_hash::hs_ops.
Referenced by cfs_hash_bd_lookup_intent(), and cfs_hash_for_each_key().
static void cfs_hash_keycpy (struct cfs_hash * hs, struct hlist_node * hnode, void * key) [inline, static]
Definition at line 466 of file libcfs_hash.h.
References cfs_hash_ops::hs_keycpy, and cfs_hash::hs_ops.
Referenced by cfs_hash_rehash_key().
static void cfs_hash_lock (struct cfs_hash * hs, int excl) [inline, static]
Definition at line 512 of file libcfs_hash.h.
References cfs_hash::hs_lock, cfs_hash_lock_ops::hs_lock, and cfs_hash::hs_lops.
Referenced by cfs_hash_add(), cfs_hash_debug_str(), cfs_hash_del(), cfs_hash_find_or_add(), cfs_hash_for_each_enter(), cfs_hash_for_each_exit(), cfs_hash_for_each_key(), cfs_hash_for_each_relax(), cfs_hash_for_each_tight(), cfs_hash_hlist_for_each(), cfs_hash_lookup(), cfs_hash_rehash(), cfs_hash_rehash_cancel(), cfs_hash_rehash_cancel_locked(), cfs_hash_rehash_key(), and cfs_hash_rehash_worker().
void* cfs_hash_lookup (struct cfs_hash * hs, const void * key)
Lookup an item using in the libcfs hash and return it.
If the is found in the hash hs->hs_get() is called and the matching objects is returned. It is the callers responsibility to call the counterpart ops->hs_put using the cfs_hash_put() macro when when finished with the object. If the was not found in the hash NULL is returned.
Definition at line 1346 of file hash.c.
References cfs_hash_dual_bd_get_and_lock(), cfs_hash_dual_bd_lookup_locked(), cfs_hash_dual_bd_unlock(), cfs_hash_lock(), cfs_hash_object(), and cfs_hash_unlock().
Referenced by cl_env_fetch(), ldlm_flock_lookup_cb(), lod_find_pool(), lod_pool_add(), lod_pool_remove(), lov_pool_add(), lov_pool_remove(), lqe_locate(), lustre_register_lwp_item(), mdt_hsm_agent_send(), nodemap_config_set_active(), nodemap_lookup(), nodemap_process_keyrec(), obd_export_evict_by_nid(), obd_export_evict_by_uuid(), osc_quota_chkdq(), osc_quota_setdq(), ptlrpc_connection_get(), qmt_pool_lookup(), tgt_reply_data_init(), and update_recovery_update_ses().
static void* cfs_hash_object (struct cfs_hash * hs, struct hlist_node * hnode) [inline, static]
Definition at line 482 of file libcfs_hash.h.
References cfs_hash_ops::hs_object, and cfs_hash::hs_ops.
Referenced by cfs_hash_cond_del_locked(), cfs_hash_del(), cfs_hash_findadd_unique(), cfs_hash_lookup(), ldlm_cancel_locks_for_export_cb(), ldlm_cli_hash_cancel_unused(), ldlm_flock_lookup_cb(), ldlm_reprocess_res(), ldlm_res_hash_dump(), ldlm_res_iter_helper(), ldlm_resource_clean(), ldlm_resource_complain(), lprocfs_mdt_print_open_files(), osc_ldlm_resource_invalidate(), and vvp_pgcache_obj_get().
static void cfs_hash_put (struct cfs_hash * hs, struct hlist_node * hnode) [inline, static]
Definition at line 500 of file libcfs_hash.h.
References cfs_hash::hs_ops, and cfs_hash_ops::hs_put.
Referenced by cfs_hash_for_each_relax(), and ldlm_flock_deadlock().
static void cfs_hash_put_locked (struct cfs_hash * hs, struct hlist_node * hnode) [inline, static]
Definition at line 494 of file libcfs_hash.h.
References cfs_hash::hs_ops, and cfs_hash_ops::hs_put_locked.
Referenced by cfs_hash_bd_del_locked(), and cfs_hash_for_each_relax().
void cfs_hash_putref (struct cfs_hash * hs)
Definition at line 1148 of file hash.c.
References cfs_hash_destroy(), and cfs_hash::hs_refcount.
Referenced by cl_env_store_fini(), class_cleanup(), class_new_export(), class_setup(), class_unlink_export(), ldlm_destroy_export(), ldlm_destroy_flock_export(), ldlm_namespace_free_post(), ldlm_namespace_new(), lod_pools_fini(), lod_pools_init(), lov_cleanup(), lquota_site_free(), lu_site_fini(), lu_site_init(), nodemap_config_cleanup(), obd_export_evict_by_nid(), obd_export_evict_by_uuid(), osc_quota_cleanup(), osc_quota_setup(), ptlrpc_connection_fini(), qmt_pool_fini(), tgt_clients_data_init(), tgt_reply_data_init(), and update_recovery_update_ses().
int cfs_hash_rehash (struct cfs_hash * hs, int do_rehash)
Definition at line 1835 of file hash.c.
References cfs_hash_lock(), cfs_hash_rehash_bits(), cfs_hash_rehash_worker(), cfs_hash_unlock(), cfs_hash_with_no_lock(), cfs_hash_with_rehash(), cfs_wi_schedule(), cfs_hash::hs_rehash_bits, cfs_hash::hs_rehash_wi, and LASSERT.
Referenced by cfs_hash_add(), cfs_hash_del(), cfs_hash_find_or_add(), and cfs_hash_for_each_exit().
void cfs_hash_rehash_cancel (struct cfs_hash * hs)
Definition at line 1827 of file hash.c.
References cfs_hash_lock(), cfs_hash_rehash_cancel_locked(), and cfs_hash_unlock().
Referenced by cfs_hash_destroy().
void cfs_hash_rehash_cancel_locked (struct cfs_hash * hs)
Rehash the libcfs hash to the given .
This can be used to grow the hash size when excessive chaining is detected, or to shrink the hash when it is larger than needed. When the CFS_HASH_REHASH flag is set in the libcfs hash may be dynamically rehashed during addition or removal if the hash's theta value exceeds either the hs->hs_min_theta or hs->max_theta values. By default these values are tuned to keep the chained hash depth small, and this approach assumes a reasonably uniform hashing function. The theta thresholds for are tunable via cfs_hash_set_theta().
Definition at line 1799 of file hash.c.
References CDEBUG, cfs_hash_is_rehashing(), cfs_hash_lock(), cfs_hash_unlock(), cfs_hash_with_no_lock(), cfs_hash_with_rehash(), cfs_wi_deschedule(), D_INFO, D_WARNING, cfs_hash::hs_name, cfs_hash::hs_rehash_bits, cfs_hash::hs_rehash_wi, and LASSERT.
Referenced by cfs_hash_for_each_enter(), and cfs_hash_rehash_cancel().
void cfs_hash_rehash_key (struct cfs_hash * hs, const void * old_key, void * new_key, struct hlist_node * hnode)
Rehash the object referenced by in the libcfs hash .
The must be provided to locate the objects previous location in the hash, and the will be used to reinsert the object. Use this function instead of a cfs_hash_add() + cfs_hash_del() combo when it is critical that there is no window in time where the object is missing from the hash. When an object is being rehashed the registered cfs_hash_get() and cfs_hash_put() functions will not be called.
Definition at line 2004 of file hash.c.
References cfs_hash_bd::bd_bucket, cfs_hash_bd_add_locked(), cfs_hash_bd_get(), cfs_hash_bd_move_locked(), cfs_hash_bd_order(), cfs_hash_dual_bd_finddel_locked(), cfs_hash_dual_bd_get(), cfs_hash_keycpy(), cfs_hash_lock(), cfs_hash_multi_bd_lock(), cfs_hash_multi_bd_unlock(), cfs_hash_unlock(), hlist_unhashed(), LASSERT, and likely.
Referenced by ldlm_cli_enqueue_fini(), and replay_lock_interpret().
__u64 cfs_hash_size_get (struct cfs_hash * hs)
Definition at line 1545 of file hash.c.
References cfs_hash_for_each_tight(), cfs_hash_with_counter(), and cfs_hash::hs_count.
Referenced by lu_object_limit().
static unsigned cfs_hash_u32_hash (const __u32 key, unsigned mask) [inline, static]
Definition at line 829 of file libcfs_hash.h.
References CFS_GOLDEN_RATIO_PRIME_32.
Referenced by cl_env_hops_hash(), oqi_hashfn(), and qpi_hash_hash().
static unsigned cfs_hash_u64_hash (const __u64 key, unsigned mask) [inline, static]
Definition at line 838 of file libcfs_hash.h.
References CFS_GOLDEN_RATIO_PRIME_64.
Referenced by cl_env_hops_hash(), ldlm_export_flock_hash(), ldlm_export_lock_hash(), and lqe64_hash_hash().
static void cfs_hash_unlock (struct cfs_hash * hs, int excl) [inline, static]
Definition at line 517 of file libcfs_hash.h.
References cfs_hash::hs_lock, cfs_hash::hs_lops, and cfs_hash_lock_ops::hs_unlock.
Referenced by cfs_hash_add(), cfs_hash_debug_str(), cfs_hash_del(), cfs_hash_find_or_add(), cfs_hash_for_each_enter(), cfs_hash_for_each_exit(), cfs_hash_for_each_key(), cfs_hash_for_each_relax(), cfs_hash_for_each_tight(), cfs_hash_hlist_for_each(), cfs_hash_lookup(), cfs_hash_rehash(), cfs_hash_rehash_cancel(), cfs_hash_rehash_cancel_locked(), cfs_hash_rehash_key(), and cfs_hash_rehash_worker().
static int cfs_hash_with_add_tail (struct cfs_hash * hs) [inline, static]
Definition at line 365 of file libcfs_hash.h.
References CFS_HASH_ADD_TAIL, and cfs_hash::hs_flags.
Referenced by cfs_hash_hlist_setup().
static int cfs_hash_with_assert_empty (struct cfs_hash * hs) [inline, static]
Definition at line 410 of file libcfs_hash.h.
References CFS_HASH_ASSERT_EMPTY, and cfs_hash::hs_flags.
Referenced by cfs_hash_destroy().
static int cfs_hash_with_bigname (struct cfs_hash * hs) [inline, static]
Definition at line 380 of file libcfs_hash.h.
References CFS_HASH_BIGNAME, and cfs_hash::hs_flags.
Referenced by cfs_hash_destroy().
static int cfs_hash_with_counter (struct cfs_hash * hs) [inline, static]
Definition at line 386 of file libcfs_hash.h.
References CFS_HASH_COUNTER, and cfs_hash::hs_flags.
Referenced by cfs_hash_bd_add_locked(), cfs_hash_bd_del_locked(), and cfs_hash_size_get().
static int cfs_hash_with_depth (struct cfs_hash * hs) [inline, static]
Definition at line 416 of file libcfs_hash.h.
References CFS_HASH_DEPTH, and cfs_hash::hs_flags.
Referenced by cfs_hash_hlist_setup().
static int cfs_hash_with_nblk_change (struct cfs_hash * hs) [inline, static]
Definition at line 422 of file libcfs_hash.h.
References CFS_HASH_NBLK_CHANGE, and cfs_hash::hs_flags.
Referenced by cfs_hash_rehash_inline().
static int cfs_hash_with_no_bktlock (struct cfs_hash * hs) [inline, static]
Definition at line 344 of file libcfs_hash.h.
References CFS_HASH_NO_BKTLOCK, and cfs_hash::hs_flags.
Referenced by cfs_hash_buckets_realloc(), cfs_hash_dec_and_lock(), and cfs_hash_lock_setup().
static int cfs_hash_with_no_itemref (struct cfs_hash * hs) [inline, static]
Definition at line 371 of file libcfs_hash.h.
References CFS_HASH_NO_ITEMREF, and cfs_hash::hs_flags.
Referenced by cfs_hash_bd_add_locked(), cfs_hash_bd_del_locked(), cfs_hash_for_each_nolock(), and cfs_hash_for_each_relax().
static int cfs_hash_with_no_lock (struct cfs_hash * hs) [inline, static]
Definition at line 337 of file libcfs_hash.h.
References CFS_HASH_NO_LOCK, and cfs_hash::hs_flags.
Referenced by cfs_hash_buckets_realloc(), cfs_hash_for_each_empty(), cfs_hash_for_each_nolock(), cfs_hash_lock_setup(), cfs_hash_rehash(), cfs_hash_rehash_bits(), and cfs_hash_rehash_cancel_locked().
static int cfs_hash_with_rehash (struct cfs_hash * hs) [inline, static]
Definition at line 392 of file libcfs_hash.h.
References CFS_HASH_REHASH, and cfs_hash::hs_flags.
Referenced by cfs_hash_create(), cfs_hash_destroy(), cfs_hash_for_each_enter(), cfs_hash_for_each_exit(), cfs_hash_lock_setup(), cfs_hash_rehash(), cfs_hash_rehash_bits(), cfs_hash_rehash_cancel_locked(), and cfs_hash_rehash_worker().
static int cfs_hash_with_rehash_key (struct cfs_hash * hs) [inline, static]
Definition at line 398 of file libcfs_hash.h.
References CFS_HASH_REHASH_KEY, and cfs_hash::hs_flags.
Referenced by cfs_hash_for_each_nolock(), and cfs_hash_for_each_relax().
static int cfs_hash_with_rw_bktlock (struct cfs_hash * hs) [inline, static]
Definition at line 351 of file libcfs_hash.h.
References CFS_HASH_RW_BKTLOCK, and cfs_hash::hs_flags.
Referenced by cfs_hash_buckets_realloc(), and cfs_hash_lock_setup().
static int cfs_hash_with_shrink (struct cfs_hash * hs) [inline, static]
Definition at line 404 of file libcfs_hash.h.
References CFS_HASH_SHRINK, and cfs_hash::hs_flags.
Referenced by cfs_hash_rehash_bits().
static int cfs_hash_with_spin_bktlock (struct cfs_hash * hs) [inline, static]
Definition at line 358 of file libcfs_hash.h.
References CFS_HASH_SPIN_BKTLOCK, and cfs_hash::hs_flags.
Referenced by cfs_hash_bd_dec_and_lock(), cfs_hash_buckets_realloc(), and cfs_hash_lock_setup().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.