Lustre: libcfs/include/libcfs/libcfs_prim.h File Reference
libcfs/include/libcfs/libcfs_prim.h File Reference
#include <linux/sched.h>
Defines
#define NUM_CACHEPAGES totalram_pages
Typedefs
typedef void(cfs_timer_func_t)(ulong_ptr_t)
Functions
void cfs_init_timer (struct timer_list *t)
void cfs_timer_init (struct timer_list *t, cfs_timer_func_t *func, void *arg)
void cfs_timer_arm (struct timer_list *t, cfs_time_t deadline)
void cfs_timer_disarm (struct timer_list *t)
int cfs_timer_is_armed (struct timer_list *t)
cfs_time_t cfs_timer_deadline (struct timer_list *t)
static unsigned int memory_pressure_get (void)
static void memory_pressure_set (void)
static void memory_pressure_clr (void)
static int cfs_memory_pressure_get_and_set (void)
static void cfs_memory_pressure_restore (int old)
Define Documentation
#define NUM_CACHEPAGES totalram_pages
Definition at line 65 of file libcfs_prim.h.
Typedef Documentation
typedef void(cfs_timer_func_t)(ulong_ptr_t)
Definition at line 48 of file libcfs_prim.h.
Function Documentation
void cfs_init_timer (struct timer_list * t)
Definition at line 49 of file linux-prim.c.
Referenced by class_attach().
static int cfs_memory_pressure_get_and_set (void) [inline, static]
Definition at line 83 of file libcfs_prim.h.
References memory_pressure_get(), and memory_pressure_set().
Referenced by kgnilnd_send(), ksocknal_send(), osc_build_rpc(), and ptl_send_rpc().
static void cfs_memory_pressure_restore (int old) [inline, static]
Definition at line 92 of file libcfs_prim.h.
References memory_pressure_clr(), and memory_pressure_set().
Referenced by kgnilnd_send(), ksocknal_send(), osc_build_rpc(), and ptl_send_rpc().
void cfs_timer_arm (struct timer_list * t, cfs_time_t deadline)
Definition at line 63 of file linux-prim.c.
Referenced by osp_statfs_interpret(), and ptlrpc_at_set_timer().
cfs_time_t cfs_timer_deadline (struct timer_list * t)
Definition at line 81 of file linux-prim.c.
void cfs_timer_disarm (struct timer_list * t)
Definition at line 69 of file linux-prim.c.
Referenced by osp_precreate_fini(), osp_statfs_need_now(), osp_statfs_update(), ptlrpc_at_set_timer(), ptlrpc_service_del_atimer(), and ptlrpc_service_free().
void cfs_timer_init (struct timer_list * t, cfs_timer_func_t * func, void * arg)
Definition at line 55 of file linux-prim.c.
Referenced by ldlm_setup(), osp_init_precreate(), and ptlrpc_service_part_init().
int cfs_timer_is_armed (struct timer_list * t)
Definition at line 75 of file linux-prim.c.
static void memory_pressure_clr (void) [inline, static]
Definition at line 78 of file libcfs_prim.h.
Referenced by cfs_memory_pressure_restore(), ldlm_bl_thread_blwi(), and tgt_brw_write().
static unsigned int memory_pressure_get (void) [inline, static]
Definition at line 68 of file libcfs_prim.h.
Referenced by cfs_memory_pressure_get_and_set(), cfs_tage_alloc(), cfs_trace_get_tage_try(), init_blwi(), and LNetPut().
static void memory_pressure_set (void) [inline, static]
Definition at line 73 of file libcfs_prim.h.
Referenced by cfs_memory_pressure_get_and_set(), cfs_memory_pressure_restore(), ldlm_bl_thread_blwi(), and tgt_brw_write().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.