Lustre: libcfs/libcfs/libcfs_string.c File Reference
libcfs/libcfs/libcfs_string.c File Reference
#include <libcfs/libcfs.h>
Functions
char * cfs_strrstr (const char *haystack, const char *needle)
int cfs_str2mask (const char *str, const char *(*bit2str)(int bit), int *oldmask, int minmask, int allmask)
char * cfs_firststr (char *str, size_t size)
char * cfs_trimwhite (char *str)
int cfs_gettok (struct cfs_lstr *next, char delim, struct cfs_lstr *res)
Extracts tokens from strings.
int cfs_str2num_check (char *str, int nob, unsigned *num, unsigned min, unsigned max)
Converts string to integer.
static int cfs_range_expr_parse (struct cfs_lstr *src, unsigned min, unsigned max, int bracketed, struct cfs_range_expr **expr)
Parses <range_expr> token of the syntax.
static int cfs_range_expr_print (char *buffer, int count, struct cfs_range_expr *expr, bool bracketed)
Print the range expression re into specified buffer.
int cfs_expr_list_print (char *buffer, int count, struct cfs_expr_list *expr_list)
Print a list of range expressions (expr_list) into specified buffer.
int cfs_expr_list_match (__u32 value, struct cfs_expr_list *expr_list)
Matches value (value) against ranges expression list expr_list.
int cfs_expr_list_values (struct cfs_expr_list *expr_list, int max, __u32 **valpp)
Convert express list (expr_list) to an array of all matched values.
void cfs_expr_list_free (struct cfs_expr_list *expr_list)
Frees cfs_range_expr structures of expr_list.
int cfs_expr_list_parse (char *str, int len, unsigned min, unsigned max, struct cfs_expr_list **elpp)
Parses <cfs_expr_list> token of the syntax.
void cfs_expr_list_free_list (struct list_head *list)
Frees cfs_expr_list structures of list.
Function Documentation
void cfs_expr_list_free (struct cfs_expr_list * expr_list)
Frees cfs_range_expr structures of expr_list.
Return values:
none
Definition at line 493 of file libcfs_string.c.
References cfs_expr_list::el_exprs, LIBCFS_FREE, list_del(), list_empty(), list_entry, list_head::next, and cfs_range_expr::re_link.
Referenced by cfs_expr_list_free_list(), cfs_expr_list_parse(), lnet_parse_networks(), ptlrpc_register_service(), and ptlrpcd_init().
void cfs_expr_list_free_list (struct list_head * list)
Frees cfs_expr_list structures of list.
For each struct cfs_expr_list structure found on list it frees range_expr list attached to it and frees the cfs_expr_list itself.
Return values:
none
Definition at line 579 of file libcfs_string.c.
References cfs_expr_list_free(), cfs_expr_list::el_link, list_del(), list_empty(), list_entry, and list_head::next.
int cfs_expr_list_match (__u32 value, struct cfs_expr_list * expr_list)
Matches value (value) against ranges expression list expr_list.
Return values:
1 if value matches
0 otherwise
Definition at line 425 of file libcfs_string.c.
References cfs_expr_list::el_exprs, list_for_each_entry, cfs_range_expr::re_hi, cfs_range_expr::re_link, cfs_range_expr::re_lo, and cfs_range_expr::re_stride.
int cfs_expr_list_parse (char * str, int len, unsigned min, unsigned max, struct cfs_expr_list ** elpp)
Parses <cfs_expr_list> token of the syntax.
Return values:
0 if str parses to <number> | <expr_list>
-errno otherwise
Definition at line 515 of file libcfs_string.c.
References cfs_expr_list_free(), cfs_gettok(), cfs_range_expr_parse(), cfs_expr_list::el_exprs, INIT_LIST_HEAD, LIBCFS_ALLOC, list_add_tail(), cfs_lstr::ls_len, cfs_lstr::ls_str, and cfs_range_expr::re_link.
int cfs_expr_list_print (char * buffer, int count, struct cfs_expr_list * expr_list)
Print a list of range expressions (expr_list) into specified buffer.
If the list contains several expressions, separate them with comma and surround the list with brackets.
Return values:
number of characters written
Definition at line 389 of file libcfs_string.c.
References cfs_range_expr_print(), cfs_expr_list::el_exprs, list_for_each_entry, and cfs_range_expr::re_link.
int cfs_expr_list_values (struct cfs_expr_list * expr_list, int max, __u32 ** valpp)
Convert express list (expr_list) to an array of all matched values.
Return values:
N N is total number of all matched values
0 if expression list is empty
< 0 for failure
Definition at line 447 of file libcfs_string.c.
References CERROR, cfs_expr_list::el_exprs, LIBCFS_ALLOC, list_for_each_entry, cfs_range_expr::re_hi, cfs_range_expr::re_link, cfs_range_expr::re_lo, and cfs_range_expr::re_stride.
Referenced by lnet_ni_alloc(), ptlrpc_register_service(), and ptlrpcd_init().
char* cfs_firststr (char * str, size_t size)
Definition at line 143 of file libcfs_string.c.
References end.
Referenced by lprocfs_mds_evict_client_seq_write().
int cfs_gettok (struct cfs_lstr * next, char delim, struct cfs_lstr * res)
Extracts tokens from strings.
Looks for delim in string next, sets res to point to substring before the delimiter, sets next right after the found delimiter.
Return values:
1 if res points to a string of non-whitespace characters
0 otherwise
Definition at line 201 of file libcfs_string.c.
References end, cfs_lstr::ls_len, and cfs_lstr::ls_str.
static int cfs_range_expr_parse (struct cfs_lstr * src, unsigned min, unsigned max, int bracketed, struct cfs_range_expr ** expr) [static]
Parses <range_expr> token of the syntax.
If bracketed is false, src should only have a single token which can be <number> or \*
Return values:
pointer to allocated range_expr and initialized range_expr::re_lo, range_expr::re_hi and range_expr:re_stride if `* src parses to <number> | <number> '-' <number> | <number> '-' <number> '/' <number>
0 will be returned if it can be parsed, otherwise -EINVAL or -ENOMEM will be returned.
Definition at line 288 of file libcfs_string.c.
References cfs_gettok(), cfs_str2num_check(), LIBCFS_ALLOC, LIBCFS_FREE, cfs_lstr::ls_len, cfs_lstr::ls_str, cfs_range_expr::re_hi, cfs_range_expr::re_lo, and cfs_range_expr::re_stride.
Referenced by cfs_expr_list_parse().
static int cfs_range_expr_print (char * buffer, int count, struct cfs_range_expr * expr, bool bracketed) [static]
Print the range expression re into specified buffer.
If bracketed is true, expression does not need additional brackets.
Return values:
number of characters written
Definition at line 359 of file libcfs_string.c.
References cfs_range_expr::re_hi, cfs_range_expr::re_lo, and cfs_range_expr::re_stride.
Referenced by cfs_expr_list_print().
int cfs_str2mask (const char * str, const char *(*)(int bit) bit2str, int * oldmask, int minmask, int allmask)
Definition at line 73 of file libcfs_string.c.
References CWARN, and ENTRY.
Referenced by libcfs_debug_str2mask(), and mdd_changelog_mask_seq_write().
int cfs_str2num_check (char * str, int nob, unsigned * num, unsigned min, unsigned max)
Converts string to integer.
Accepts decimal and hexadecimal number recordings.
Return values:
1 if first nob chars of str convert to decimal or hexadecimal integer in the range [min, max]
0 otherwise
Definition at line 256 of file libcfs_string.c.
char* cfs_strrstr (const char * haystack, const char * needle)
Definition at line 45 of file libcfs_string.c.
References unlikely.
Referenced by lwp_setup().
char* cfs_trimwhite (char * str)
Definition at line 171 of file libcfs_string.c.
References end.
Referenced by __proc_lnet_portal_rotor(), and lnet_parse_networks().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.