Lustre: libcfs/include/libcfs/libcfs_workitem.h File Reference
libcfs/include/libcfs/libcfs_workitem.h File Reference
Data Structures
struct cfs_workitem
Defines
#define CFS_WI_RESCHED 128
# workitem scheduler loops before reschedule
Typedefs
typedef int(* cfs_wi_action_t)(struct cfs_workitem *)
Functions
void cfs_wi_sched_destroy (struct cfs_wi_sched *)
int cfs_wi_sched_create (char *name, struct cfs_cpt_table *cptab, int cpt, int nthrs, struct cfs_wi_sched **)
static void cfs_wi_init (struct cfs_workitem *wi, void *data, cfs_wi_action_t action)
void cfs_wi_schedule (struct cfs_wi_sched *sched, struct cfs_workitem *wi)
int cfs_wi_deschedule (struct cfs_wi_sched *sched, struct cfs_workitem *wi)
cancel schedule request of workitem wi
void cfs_wi_exit (struct cfs_wi_sched *sched, struct cfs_workitem *wi)
int cfs_wi_startup (void)
void cfs_wi_shutdown (void)
Define Documentation
#define CFS_WI_RESCHED 128
# workitem scheduler loops before reschedule
Definition at line 109 of file libcfs_workitem.h.
Referenced by cfs_wi_scheduler().
Typedef Documentation
typedef int(* cfs_wi_action_t)(struct cfs_workitem *)
Definition at line 75 of file libcfs_workitem.h.
Function Documentation
int cfs_wi_deschedule (struct cfs_wi_sched * sched, struct cfs_workitem * wi)
cancel schedule request of workitem wi
Definition at line 142 of file workitem.c.
References LASSERT, list_del_init(), list_empty(), cfs_workitem::wi_list, cfs_workitem::wi_running, cfs_workitem::wi_scheduled, cfs_wi_sched::ws_lock, cfs_wi_sched::ws_nscheduled, and cfs_wi_sched::ws_stopping.
Referenced by cfs_hash_rehash_cancel_locked(), and swi_deschedule_workitem().
void cfs_wi_exit (struct cfs_wi_sched * sched, struct cfs_workitem * wi)
Definition at line 112 of file workitem.c.
References LASSERT, list_del_init(), list_empty(), cfs_workitem::wi_list, cfs_workitem::wi_running, cfs_workitem::wi_scheduled, cfs_wi_sched::ws_lock, cfs_wi_sched::ws_nscheduled, and cfs_wi_sched::ws_stopping.
Referenced by cfs_hash_rehash_worker(), and swi_exit_workitem().
static void cfs_wi_init (struct cfs_workitem * wi, void * data, cfs_wi_action_t action) [inline, static]
Definition at line 91 of file libcfs_workitem.h.
References INIT_LIST_HEAD, cfs_workitem::wi_action, cfs_workitem::wi_data, cfs_workitem::wi_list, cfs_workitem::wi_running, and cfs_workitem::wi_scheduled.
Referenced by cfs_hash_create(), and swi_init_workitem().
int cfs_wi_sched_create (char * name, struct cfs_cpt_table * cptab, int cpt, int nthrs, struct cfs_wi_sched **)
Definition at line 343 of file workitem.c.
References CERROR, CFS_CPT_ANY, cfs_cpt_number(), cfs_wi_data, cfs_wi_sched_destroy(), cfs_wi_scheduler(), INIT_LIST_HEAD, LASSERT, LIBCFS_ALLOC, LIBCFS_FREE, list_add(), strlcpy(), cfs_workitem_data::wi_glock, cfs_workitem_data::wi_init, cfs_workitem_data::wi_scheds, cfs_workitem_data::wi_stopping, cfs_wi_sched::ws_cpt, cfs_wi_sched::ws_cptab, cfs_wi_sched::ws_list, cfs_wi_sched::ws_lock, cfs_wi_sched::ws_name, cfs_wi_sched::ws_nthreads, cfs_wi_sched::ws_rerunq, cfs_wi_sched::ws_runq, cfs_wi_sched::ws_starting, and cfs_wi_sched::ws_waitq.
Referenced by libcfs_init(), and lnet_selftest_init().
void cfs_wi_sched_destroy (struct cfs_wi_sched *)
Definition at line 295 of file workitem.c.
References CDEBUG, cfs_time_seconds(), cfs_wi_data, D_INFO, D_NET, D_WARNING, LASSERT, LIBCFS_FREE, list_del(), list_empty(), cfs_workitem_data::wi_glock, cfs_workitem_data::wi_init, cfs_workitem_data::wi_stopping, cfs_wi_sched::ws_list, cfs_wi_sched::ws_name, cfs_wi_sched::ws_nscheduled, cfs_wi_sched::ws_nthreads, cfs_wi_sched::ws_stopping, and cfs_wi_sched::ws_waitq.
Referenced by cfs_wi_sched_create(), libcfs_exit(), and lnet_selftest_exit().
void cfs_wi_schedule (struct cfs_wi_sched * sched, struct cfs_workitem * wi)
Definition at line 183 of file workitem.c.
References LASSERT, list_add(), list_add_tail(), list_empty(), cfs_workitem::wi_list, cfs_workitem::wi_running, cfs_workitem::wi_scheduled, cfs_wi_sched::ws_lock, cfs_wi_sched::ws_nscheduled, cfs_wi_sched::ws_rerunq, cfs_wi_sched::ws_runq, cfs_wi_sched::ws_stopping, and cfs_wi_sched::ws_waitq.
Referenced by cfs_hash_bd_dep_record(), cfs_hash_rehash(), and swi_schedule_workitem().
void cfs_wi_shutdown (void)
Definition at line 438 of file workitem.c.
References cfs_time_seconds(), cfs_wi_data, LIBCFS_FREE, list_del(), list_empty(), list_entry, list_for_each_entry, list_head::next, cfs_workitem_data::wi_glock, cfs_workitem_data::wi_init, cfs_workitem_data::wi_scheds, cfs_workitem_data::wi_stopping, cfs_wi_sched::ws_list, cfs_wi_sched::ws_nthreads, cfs_wi_sched::ws_stopping, and cfs_wi_sched::ws_waitq.
Referenced by libcfs_exit(), and libcfs_init().
int cfs_wi_startup (void)
Definition at line 426 of file workitem.c.
References cfs_wi_data, INIT_LIST_HEAD, cfs_workitem_data::wi_glock, cfs_workitem_data::wi_init, and cfs_workitem_data::wi_scheds.
Referenced by libcfs_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.