Lustre: libcfs/libcfs/libcfs_lock.c File Reference
libcfs/libcfs/libcfs_lock.c File Reference
#include <libcfs/libcfs.h>
Defines
#define DEBUG_SUBSYSTEM S_LNET
Functions
void cfs_percpt_lock_free (struct cfs_percpt_lock *pcl)
destroy cpu-partition lock, see libcfs_private.h for more detail
struct cfs_percpt_lock * cfs_percpt_lock_create (struct cfs_cpt_table *cptab, struct lock_class_key *keys)
create cpu-partition lock, see libcfs_private.h for more detail.
void cfs_percpt_lock (struct cfs_percpt_lock *pcl, int index) __acquires(pcl->pcl_locks)
lock a CPU partition
void cfs_percpt_unlock (struct cfs_percpt_lock *pcl, int index) __releases(pcl->pcl_locks)
unlock a CPU partition
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 33 of file libcfs_lock.c.
Function Documentation
void cfs_percpt_lock (struct cfs_percpt_lock * pcl, int index)
lock a CPU partition
index != CFS_PERCPT_LOCK_EX hold private lock indexed by index
index == CFS_PERCPT_LOCK_EX exclusively lock and nobody can take private lock
Definition at line 101 of file libcfs_lock.c.
References cfs_cpt_number(), CFS_PERCPT_LOCK_EX, LASSERT, and likely.
Referenced by lnet_net_lock(), and lnet_res_lock().
struct cfs_percpt_lock* cfs_percpt_lock_create (struct cfs_cpt_table * cptab, struct lock_class_key * keys) [read]
create cpu-partition lock, see libcfs_private.h for more detail.
cpu-partition lock is designed for large-scale SMP system, so we need to reduce cacheline conflict as possible as we can, that's the reason we always allocate cacheline-aligned memory block.
Definition at line 57 of file libcfs_lock.c.
References cfs_percpt_alloc(), cfs_percpt_for_each, CWARN, LIBCFS_ALLOC, LIBCFS_FREE, cfs_percpt_lock::pcl_cptab, and cfs_percpt_lock::pcl_locks.
void cfs_percpt_lock_free (struct cfs_percpt_lock * pcl)
destroy cpu-partition lock, see libcfs_private.h for more detail
Definition at line 39 of file libcfs_lock.c.
References cfs_percpt_free(), LASSERT, LIBCFS_FREE, cfs_percpt_lock::pcl_locked, and cfs_percpt_lock::pcl_locks.
Referenced by lnet_destroy_locks().
void cfs_percpt_unlock (struct cfs_percpt_lock * pcl, int index)
unlock a CPU partition
Definition at line 136 of file libcfs_lock.c.
References cfs_cpt_number(), CFS_PERCPT_LOCK_EX, LASSERT, and likely.
Referenced by lnet_net_unlock(), and lnet_res_unlock().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.