Lustre: libcfs/include/libcfs/libcfs_crypto.h File Reference
libcfs/include/libcfs/libcfs_crypto.h File Reference
Data Structures
struct cfs_crypto_hash_type
Defines
#define CFS_CRYPTO_HASH_DIGESTSIZE_MAX 64
Enumerations
enum cfs_crypto_hash_alg {
CFS_HASH_ALG_NULL = 0, CFS_HASH_ALG_ADLER32, CFS_HASH_ALG_CRC32, CFS_HASH_ALG_MD5,
CFS_HASH_ALG_SHA1, CFS_HASH_ALG_SHA256, CFS_HASH_ALG_SHA384, CFS_HASH_ALG_SHA512,
CFS_HASH_ALG_CRC32C, CFS_HASH_ALG_MAX, CFS_HASH_ALG_UNKNOWN = 0xff
}
Functions
static struct
cfs_crypto_hash_type * cfs_crypto_hash_type (enum cfs_crypto_hash_alg hash_alg)
Return hash algorithm information for the specified algorithm identifier.
static const char * cfs_crypto_hash_name (enum cfs_crypto_hash_alg hash_alg)
Return hash name for hash algorithm identifier.
static unsigned int cfs_crypto_hash_digestsize (enum cfs_crypto_hash_alg hash_alg)
Return digest size for hash algorithm type.
static unsigned char cfs_crypto_hash_alg (const char *algname)
Find hash algorithm ID for the specified algorithm name.
int cfs_crypto_hash_digest (enum cfs_crypto_hash_alg hash_alg, const void *buf, unsigned int buf_len, unsigned char *key, unsigned int key_len, unsigned char *hash, unsigned int *hash_len)
Calculate hash digest for the passed buffer.
struct cfs_crypto_hash_desc * cfs_crypto_hash_init (enum cfs_crypto_hash_alg hash_alg, unsigned char *key, unsigned int key_len)
Allocate and initialize desriptor for hash algorithm.
int cfs_crypto_hash_update_page (struct cfs_crypto_hash_desc *desc, struct page *page, unsigned int offset, unsigned int len)
Update hash digest computed on data within the given page.
int cfs_crypto_hash_update (struct cfs_crypto_hash_desc *desc, const void *buf, unsigned int buf_len)
Update hash digest computed on the specified data.
int cfs_crypto_hash_final (struct cfs_crypto_hash_desc *desc, unsigned char *hash, unsigned int *hash_len)
Finish hash calculation, copy hash digest to buffer, clean up hash descriptor.
int cfs_crypto_register (void)
Register available hash functions.
void cfs_crypto_unregister (void)
Unregister previously registered hash functions.
int cfs_crypto_hash_speed (enum cfs_crypto_hash_alg hash_alg)
hash speed in Mbytes per second for valid hash algorithm
Variables
static struct cfs_crypto_hash_type hash_types []
Define Documentation
#define CFS_CRYPTO_HASH_DIGESTSIZE_MAX 64
Definition at line 69 of file libcfs_crypto.h.
Referenced by cfs_crypto_performance_test(), and sptlrpc_get_bulk_checksum().
Enumeration Type Documentation
enum cfs_crypto_hash_alg
Enumerator:
CFS_HASH_ALG_NULL
CFS_HASH_ALG_ADLER32
CFS_HASH_ALG_CRC32
CFS_HASH_ALG_MD5
CFS_HASH_ALG_SHA1
CFS_HASH_ALG_SHA256
CFS_HASH_ALG_SHA384
CFS_HASH_ALG_SHA512
CFS_HASH_ALG_CRC32C
CFS_HASH_ALG_MAX
CFS_HASH_ALG_UNKNOWN
Definition at line 41 of file libcfs_crypto.h.
Function Documentation
static unsigned char cfs_crypto_hash_alg (const char * algname) [inline, static]
Find hash algorithm ID for the specified algorithm name.
Return values:
hash algorithm ID for valid ID (CFS_HASH_ALG_*)
CFS_HASH_ALG_UNKNOWN for unknown algorithm name
Definition at line 138 of file libcfs_crypto.h.
References CFS_HASH_ALG_MAX, CFS_HASH_ALG_UNKNOWN, and cfs_crypto_hash_type::cht_name.
int cfs_crypto_hash_digest (enum cfs_crypto_hash_alg hash_alg, const void * buf, unsigned int buf_len, unsigned char * key, unsigned int key_len, unsigned char * hash, unsigned int * hash_len)
Calculate hash digest for the passed buffer.
This should be used when computing the hash on a single contiguous buffer. It combines the hash initialization, computation, and cleanup.
Parameters:
[in] hash_alg id of hash algorithm (CFS_HASH_ALG_*)
[in] buf data buffer on which to compute hash
[in] buf_len length of buf in bytes
[in] key initial value/state for algorithm, if key = NULL use default initial value
[in] key_len length of key in bytes
[out] hash pointer to computed hash value, if hash = NULL then hash_len is to digest size in bytes, retval -ENOSPC
[in,out] hash_len size of hash buffer
Return values:
-EINVAL buf, buf_len, hash_len, hash_alg invalid
-ENOENT hash_alg is unsupported
-ENOSPC hash is NULL, or hash_len less than digest size
0 for success
negative errno for other errors from lower layers.
Definition at line 152 of file linux-crypto.c.
References cfs_crypto_hash_alloc(), and cfs_crypto_hash_type::cht_size.
Referenced by lustre_msg_calc_cksum(), plain_authorize(), and plain_ctx_verify().
static unsigned int cfs_crypto_hash_digestsize (enum cfs_crypto_hash_alg hash_alg) [inline, static]
Return digest size for hash algorithm type.
Parameters:
[in] hash_alg hash alrgorithm id (CFS_HASH_ALG_*)
Return values:
hash algorithm digest size in bytes
0 if hash algorithm type is unknown
Definition at line 121 of file libcfs_crypto.h.
References cfs_crypto_hash_type(), and cfs_crypto_hash_type::cht_size.
Referenced by sptlrpc_get_bulk_checksum().
int cfs_crypto_hash_final (struct cfs_crypto_hash_desc * hdesc, unsigned char * hash, unsigned int * hash_len)
Finish hash calculation, copy hash digest to buffer, clean up hash descriptor.
Parameters:
[in] hdesc hash descriptor
[out] hash pointer to hash buffer to store hash digest
[in,out] hash_len pointer to hash buffer size, if hash == NULL or hash_len == NULL only free hdesc instead of computing the hash
Return values:
0 for success
-EOVERFLOW if hash_len is too small for the hash digest
negative errno for other errors from lower layers
Definition at line 280 of file linux-crypto.c.
References size.
Referenced by cfs_crypto_performance_test(), osc_checksum_bulk(), sptlrpc_get_bulk_checksum(), and tgt_checksum_bulk().
struct cfs_crypto_hash_desc* cfs_crypto_hash_init (enum cfs_crypto_hash_alg hash_alg, unsigned char * key, unsigned int key_len) [read]
Allocate and initialize desriptor for hash algorithm.
This should be used to initialize a hash descriptor for multiple calls to a single hash function when computing the hash across multiple separate buffers or pages using cfs_crypto_hash_update{,_page}().
The hash descriptor should be freed with cfs_crypto_hash_final().
Parameters:
[in] hash_alg algorithm id (CFS_HASH_ALG_*)
[in] key initial value/state for algorithm, if key = NULL use default initial value
[in] key_len length of key in bytes
Return values:
pointer to descriptor of hash instance
ERR_PTR(errno) in case of error
Definition at line 204 of file linux-crypto.c.
References cfs_crypto_hash_alloc().
Referenced by cfs_crypto_performance_test(), osc_checksum_bulk(), sptlrpc_get_bulk_checksum(), and tgt_checksum_bulk().
static const char* cfs_crypto_hash_name (enum cfs_crypto_hash_alg hash_alg) [inline, static]
Return hash name for hash algorithm identifier.
Parameters:
[in] hash_alg hash alrgorithm id (CFS_HASH_ALG_*)
Return values:
string name of known hash algorithm
unknown if hash algorithm is unknown
Definition at line 101 of file libcfs_crypto.h.
References cfs_crypto_hash_type(), and cfs_crypto_hash_type::cht_name.
Referenced by cfs_crypto_performance_test(), osc_checksum_bulk(), sptlrpc_get_bulk_checksum(), sptlrpc_get_hash_name(), and tgt_checksum_bulk().
int cfs_crypto_hash_speed (enum cfs_crypto_hash_alg hash_alg)
hash speed in Mbytes per second for valid hash algorithm
Return the performance of the specified hash_alg that was previously computed using cfs_crypto_performance_test().
Parameters:
[in] hash_alg hash algorithm id (CFS_HASH_ALG_*)
Return values:
positive speed of the hash function in MB/s
-ENOENT if hash_alg is unsupported
negative errno if hash_alg speed is unavailable
Definition at line 393 of file linux-crypto.c.
References cfs_crypto_hash_speeds, and CFS_HASH_ALG_MAX.
Referenced by cksum_type_pack(), cksum_types_supported_client(), and cksum_types_supported_server().
static struct cfs_crypto_hash_type* cfs_crypto_hash_type (enum cfs_crypto_hash_alg hash_alg) [static, read]
Return hash algorithm information for the specified algorithm identifier.
Hash information includes algorithm name, initial seed, hash size.
Return values:
cfs_crypto_hash_type for valid ID (CFS_HASH_ALG_*)
NULL for unknown algorithm identifier
Definition at line 80 of file libcfs_crypto.h.
References CFS_HASH_ALG_MAX, and cfs_crypto_hash_type::cht_name.
Referenced by cfs_crypto_hash_alloc(), cfs_crypto_hash_digestsize(), and cfs_crypto_hash_name().
int cfs_crypto_hash_update (struct cfs_crypto_hash_desc * hdesc, const void * buf, unsigned int buf_len)
Update hash digest computed on the specified data.
Parameters:
[in] hdesc hash state descriptor
[in] buf data buffer on which to compute the hash
[in] buf_len length of on which to compute hash
Return values:
0 for success
negative errno on failure
Definition at line 254 of file linux-crypto.c.
int cfs_crypto_hash_update_page (struct cfs_crypto_hash_desc * hdesc, struct page * page, unsigned int offset, unsigned int len)
Update hash digest computed on data within the given page.
Parameters:
[in] hdesc hash state descriptor
[in] page data page on which to compute the hash
[in] offset offset within page at which to start hash
[in] len length of data on which to compute hash
Return values:
0 for success
negative errno on failure
Definition at line 229 of file linux-crypto.c.
Referenced by cfs_crypto_performance_test(), osc_checksum_bulk(), sptlrpc_get_bulk_checksum(), and tgt_checksum_bulk().
int cfs_crypto_register (void)
Register available hash functions.
Return values:
0
Definition at line 449 of file linux-crypto.c.
References adler32, cfs_crypto_adler32_register(), cfs_crypto_crc32_pclmul_register(), cfs_crypto_crc32_register(), cfs_crypto_crc32c_pclmul_register(), and cfs_crypto_test_hashes().
Referenced by libcfs_init().
void cfs_crypto_unregister (void)
Unregister previously registered hash functions.
Definition at line 476 of file linux-crypto.c.
References adler32, cfs_crypto_adler32_unregister(), cfs_crypto_crc32_pclmul_unregister(), cfs_crypto_crc32_unregister(), and cfs_crypto_crc32c_pclmul_unregister().
Referenced by libcfs_exit(), and libcfs_init().
Variable Documentation
struct cfs_crypto_hash_type hash_types[] [static]
Initial value:
 {
        [CFS_HASH_ALG_NULL]     = { "null",      0,      0 },
        [CFS_HASH_ALG_ADLER32]  = { "adler32",   1,      4 },
        [CFS_HASH_ALG_CRC32]    = { "crc32",    ~0,      4 },
        [CFS_HASH_ALG_CRC32C]   = { "crc32c",   ~0,      4 },
        [CFS_HASH_ALG_MD5]      = { "md5",       0,     16 },
        [CFS_HASH_ALG_SHA1]     = { "sha1",      0,     20 },
        [CFS_HASH_ALG_SHA256]   = { "sha256",    0,     32 },
        [CFS_HASH_ALG_SHA384]   = { "sha384",    0,     48 },
        [CFS_HASH_ALG_SHA512]   = { "sha512",    0,     64 },
        [CFS_HASH_ALG_MAX]      = { NULL,        0,     64 },
}
Definition at line 55 of file libcfs_crypto.h.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.