Lustre: libcfs/libcfs/linux/linux-module.c File Reference
libcfs/libcfs/linux/linux-module.c File Reference
#include <libcfs/libcfs.h>
Defines
#define DEBUG_SUBSYSTEM S_LNET
#define LNET_MINOR 240
Functions
static size_t libcfs_ioctl_packlen (struct libcfs_ioctl_data *data)
static bool libcfs_ioctl_is_invalid (struct libcfs_ioctl_data *data)
int libcfs_ioctl_data_adjust (struct libcfs_ioctl_data *data)
int libcfs_ioctl_getdata (struct libcfs_ioctl_hdr **hdr_pp, struct libcfs_ioctl_hdr __user *uhdr)
static long libcfs_psdev_ioctl (struct file *file, unsigned int cmd, unsigned long arg)
Variables
static struct file_operations libcfs_fops
struct miscdevice libcfs_dev
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 37 of file linux-module.c.
#define LNET_MINOR 240
Definition at line 41 of file linux-module.c.
Function Documentation
int libcfs_ioctl_data_adjust (struct libcfs_ioctl_data * data)
Definition at line 92 of file linux-module.c.
References CERROR, cfs_size_round(), ENTRY, libcfs_ioctl_data::ioc_bulk, libcfs_ioctl_data::ioc_inlbuf1, libcfs_ioctl_data::ioc_inlbuf2, libcfs_ioctl_data::ioc_inllen1, libcfs_ioctl_data::ioc_inllen2, libcfs_ioctl_is_invalid(), and RETURN.
Referenced by libcfs_ioctl().
int libcfs_ioctl_getdata (struct libcfs_ioctl_hdr ** hdr_pp, struct libcfs_ioctl_hdr __user * uhdr)
Definition at line 111 of file linux-module.c.
References CERROR, ENTRY, GOTO, libcfs_ioctl_hdr::ioc_len, libcfs_ioctl_hdr::ioc_version, LIBCFS_ALLOC, LIBCFS_FREE, LIBCFS_IOC_DATA_MAX, LIBCFS_IOCTL_VERSION, LIBCFS_IOCTL_VERSION2, and RETURN.
Referenced by libcfs_ioctl().
static bool libcfs_ioctl_is_invalid (struct libcfs_ioctl_data * data) [static]
Definition at line 52 of file linux-module.c.
References libcfs_ioctl_data::ioc_bulk, libcfs_ioctl_data::ioc_hdr, libcfs_ioctl_data::ioc_inlbuf1, libcfs_ioctl_data::ioc_inlbuf2, libcfs_ioctl_data::ioc_inllen1, libcfs_ioctl_data::ioc_inllen2, libcfs_ioctl_hdr::ioc_len, libcfs_ioctl_data::ioc_pbuf1, libcfs_ioctl_data::ioc_pbuf2, libcfs_ioctl_data::ioc_plen1, libcfs_ioctl_data::ioc_plen2, and libcfs_ioctl_packlen().
Referenced by libcfs_ioctl_data_adjust().
static size_t libcfs_ioctl_packlen (struct libcfs_ioctl_data * data) [inline, static]
Definition at line 43 of file linux-module.c.
References libcfs_ioctl_data::ioc_inllen1, and libcfs_ioctl_data::ioc_inllen2.
Referenced by libcfs_ioctl_is_invalid().
static long libcfs_psdev_ioctl (struct file * file, unsigned int cmd, unsigned long arg) [static]
Definition at line 153 of file linux-module.c.
References __user, CDEBUG, D_IOCTL, IOC_LIBCFS_MAX_NR, IOC_LIBCFS_MIN_NR, IOC_LIBCFS_TYPE, and libcfs_ioctl().
Variable Documentation
struct miscdevice libcfs_dev
Initial value:
 {
        LNET_MINOR,
        "lnet",
        &libcfs_fops
}
Definition at line 174 of file linux-module.c.
Referenced by libcfs_exit(), and libcfs_init().
struct file_operations libcfs_fops [static]
Initial value:
 {
        .owner          = THIS_MODULE,
        .unlocked_ioctl = libcfs_psdev_ioctl,
}
Definition at line 169 of file linux-module.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.