Lustre: libcfs/libcfs/libcfs_mem.c File Reference
libcfs/libcfs/libcfs_mem.c File Reference
#include <libcfs/libcfs.h>
Data Structures
struct cfs_var_array
Defines
#define DEBUG_SUBSYSTEM S_LNET
Functions
void cfs_percpt_free (void *vars)
void * cfs_percpt_alloc (struct cfs_cpt_table *cptab, unsigned int size)
int cfs_percpt_number (void *vars)
void cfs_array_free (void *vars)
void * cfs_array_alloc (int count, unsigned int size)
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 34 of file libcfs_mem.c.
Function Documentation
void* cfs_array_alloc (int count, unsigned int size)
Definition at line 149 of file libcfs_mem.c.
References cfs_array_free(), LIBCFS_ALLOC, offsetof, cfs_var_array::va_count, cfs_var_array::va_ptrs, and cfs_var_array::va_size.
Referenced by lnet_portals_create().
void cfs_array_free (void * vars)
Definition at line 125 of file libcfs_mem.c.
References LIBCFS_FREE, offsetof, cfs_var_array::va_count, cfs_var_array::va_ptrs, and cfs_var_array::va_size.
Referenced by cfs_array_alloc(), and lnet_portals_destroy().
void* cfs_percpt_alloc (struct cfs_cpt_table * cptab, unsigned int size)
Definition at line 78 of file libcfs_mem.c.
References cfs_cpt_number(), cfs_percpt_free(), LIBCFS_ALLOC, LIBCFS_CPT_ALLOC, offsetof, cfs_var_array::va_count, cfs_var_array::va_cptab, cfs_var_array::va_ptrs, and cfs_var_array::va_size.
Referenced by cfs_percpt_lock_create(), kiblnd_base_startup(), kiblnd_net_init_pools(), ksocknal_base_startup(), lnet_msg_containers_create(), lnet_ni_alloc(), lnet_peer_tables_create(), lnet_prepare(), lnet_ptl_setup(), lnet_res_containers_create(), lnet_rtrpools_alloc(), LNetEQAlloc(), ptlrpc_hr_init(), and srpc_service_init().
void cfs_percpt_free (void * vars)
Definition at line 49 of file libcfs_mem.c.
References LIBCFS_FREE, offsetof, cfs_var_array::va_count, cfs_var_array::va_ptrs, and cfs_var_array::va_size.
Referenced by cfs_percpt_alloc(), cfs_percpt_lock_free(), kiblnd_base_shutdown(), kiblnd_net_fini_pools(), ksocknal_free_buffers(), lnet_msg_containers_destroy(), lnet_ni_free(), lnet_peer_tables_destroy(), lnet_ptl_cleanup(), lnet_res_containers_destroy(), lnet_rtrpools_free(), lnet_unprepare(), LNetEQAlloc(), LNetEQFree(), ptlrpc_hr_fini(), and srpc_service_fini().
int cfs_percpt_number (void * vars)
Definition at line 111 of file libcfs_mem.c.
References cfs_var_array::va_count, and cfs_var_array::va_ptrs.
Referenced by lnet_get_peer_info().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.