Lustre: libcfs/include/libcfs/libcfs_cpu.h File Reference
libcfs/include/libcfs/libcfs_cpu.h File Reference
Data Structures
struct cfs_cpt_table
struct cfs_percpt_lock
Defines
#define CFS_CPT_ANY (-1)
#define cfs_percpt_for_each(var, i, vars)
#define cfs_percpt_lock_num(pcl) cfs_cpt_number(pcl->pcl_cptab)
#define CFS_PERCPT_LOCK_KEYS 256
#define cfs_percpt_lock_alloc(cptab)
#define cfs_cpt_for_each(i, cptab) for (i = 0; i < cfs_cpt_number(cptab); i++)
iterate over all CPU partitions in cptab
Enumerations
enum { CFS_PERCPT_LOCK_EX = -1 }
Functions
void cfs_cpt_table_free (struct cfs_cpt_table *cptab)
destroy a CPU partition table
struct cfs_cpt_table * cfs_cpt_table_alloc (unsigned int ncpt)
create a cfs_cpt_table with ncpt number of partitions
int cfs_cpt_table_print (struct cfs_cpt_table *cptab, char *buf, int len)
print string information of cpt-table
int cfs_cpt_number (struct cfs_cpt_table *cptab)
return total number of CPU partitions in cptab
int cfs_cpt_weight (struct cfs_cpt_table *cptab, int cpt)
return number of HW cores or hypter-threadings in a CPU partition cpt
int cfs_cpt_online (struct cfs_cpt_table *cptab, int cpt)
is there any online CPU in CPU partition cpt
cpumask_t * cfs_cpt_cpumask (struct cfs_cpt_table *cptab, int cpt)
return cpumask of CPU partition cpt
nodemask_t * cfs_cpt_nodemask (struct cfs_cpt_table *cptab, int cpt)
return nodemask of CPU partition cpt
int cfs_cpt_current (struct cfs_cpt_table *cptab, int remap)
shadow current HW processor ID to CPU-partition ID of cptab
int cfs_cpt_of_cpu (struct cfs_cpt_table *cptab, int cpu)
shadow HW processor ID CPU to CPU-partition ID by cptab
int cfs_cpt_bind (struct cfs_cpt_table *cptab, int cpt)
bind current thread on a CPU-partition cpt of cptab
int cfs_cpt_set_cpu (struct cfs_cpt_table *cptab, int cpt, int cpu)
add cpu to CPU partion of cptab, return 1 for success, otherwise 0 is returned
void cfs_cpt_unset_cpu (struct cfs_cpt_table *cptab, int cpt, int cpu)
remove cpu from CPU partition cpt of cptab
int cfs_cpt_set_cpumask (struct cfs_cpt_table *cptab, int cpt, cpumask_t *mask)
add all cpus in mask to CPU partition cpt return 1 if successfully set all CPUs, otherwise return 0
void cfs_cpt_unset_cpumask (struct cfs_cpt_table *cptab, int cpt, cpumask_t *mask)
remove all cpus in mask from CPU partition cpt
int cfs_cpt_set_node (struct cfs_cpt_table *cptab, int cpt, int node)
add all cpus in NUMA node node to CPU partition cpt return 1 if successfully set all CPUs, otherwise return 0
void cfs_cpt_unset_node (struct cfs_cpt_table *cptab, int cpt, int node)
remove all cpus in NUMA node node from CPU partition cpt
int cfs_cpt_set_nodemask (struct cfs_cpt_table *cptab, int cpt, nodemask_t *mask)
add all cpus in node mask mask to CPU partition cpt return 1 if successfully set all CPUs, otherwise return 0
void cfs_cpt_unset_nodemask (struct cfs_cpt_table *cptab, int cpt, nodemask_t *mask)
remove all cpus in node mask mask from CPU partition cpt
void cfs_cpt_clear (struct cfs_cpt_table *cptab, int cpt)
unset all cpus for CPU partition cpt
int cfs_cpt_spread_node (struct cfs_cpt_table *cptab, int cpt)
convert partition id cpt to numa node id, if there are more than one nodes in this partition, it might return a different node id each time.
int cfs_cpu_ht_nsiblings (int cpu)
return number of HTs in the same core of cpu
void * cfs_percpt_alloc (struct cfs_cpt_table *cptab, unsigned int size)
void cfs_percpt_free (void *vars)
int cfs_percpt_number (void *vars)
struct cfs_percpt_lock * cfs_percpt_lock_create (struct cfs_cpt_table *cptab, struct lock_class_key *keys)
create cpu-partition lock, see libcfs_private.h for more detail.
void cfs_percpt_lock_free (struct cfs_percpt_lock *pcl)
destroy cpu-partition lock, see libcfs_private.h for more detail
void cfs_percpt_lock (struct cfs_percpt_lock *pcl, int index)
lock a CPU partition
void cfs_percpt_unlock (struct cfs_percpt_lock *pcl, int index)
unlock a CPU partition
static void * cfs_cpt_malloc (struct cfs_cpt_table *cptab, int cpt, size_t nr_bytes, gfp_t flags)
allocate nr_bytes of physical memory from a contiguous region with the properties of flags which are bound to the partition id cpt.
static void * cfs_cpt_vzalloc (struct cfs_cpt_table *cptab, int cpt, size_t nr_bytes)
allocate nr_bytes of virtually contiguous memory that is bound to the partition id cpt.
static struct page * cfs_page_cpt_alloc (struct cfs_cpt_table *cptab, int cpt, gfp_t flags)
allocate a single page of memory with the properties of flags were that page is bound to the partition id cpt.
static void * cfs_mem_cache_cpt_alloc (struct kmem_cache *cachep, struct cfs_cpt_table *cptab, int cpt, gfp_t flags)
allocate a chunck of memory from a memory pool that is bound to the partition id cpt with the properites of flags.
int cfs_cpu_init (void)
void cfs_cpu_fini (void)
Variables
struct cfs_cpt_table * cfs_cpt_table
Define Documentation
#define CFS_CPT_ANY (-1)
Definition at line 95 of file libcfs_cpu.h.
Referenced by cfs_binheap_create(), cfs_wi_sched_create(), libcfs_init(), lnet_selftest_init(), ost_setup(), ptlrpc_register_service(), ptlrpc_server_nthreads_check(), ptlrpcd_init(), and sfw_add_test().
#define cfs_cpt_for_each (i, cptab) for (i = 0; i < cfs_cpt_number(cptab); i++)
iterate over all CPU partitions in cptab
Definition at line 335 of file libcfs_cpu.h.
Referenced by kiblnd_dev_failover(), and kiblnd_net_fini_pools().
#define cfs_percpt_for_each (var, i, vars)
Value:
for (i = 0; i < cfs_percpt_number(vars) &&      \
                ((var) = (vars)[i]) != NULL; i++)
Definition at line 213 of file libcfs_cpu.h.
Referenced by __proc_lnet_buffers(), cfs_percpt_lock_create(), kiblnd_base_shutdown(), kiblnd_base_startup(), ksocknal_base_shutdown(), ksocknal_base_startup(), ksocknal_free_buffers(), lnet_clear_zombies_nis_locked(), lnet_counters_get(), lnet_counters_reset(), lnet_get_rtr_pool_cfg(), lnet_msg_containers_create(), lnet_msg_containers_destroy(), lnet_ni_alloc(), lnet_peer_tables_cleanup(), lnet_peer_tables_create(), lnet_peer_tables_destroy(), lnet_ptl_cleanup(), lnet_ptl_setup(), lnet_res_containers_create(), lnet_res_containers_destroy(), lnet_rtrpools_adjust_helper(), lnet_rtrpools_alloc(), lnet_rtrpools_free(), lnet_startup_lndni(), LNetEQFree(), proc_lnet_nis(), ptlrpc_hr_fini(), ptlrpc_hr_init(), ptlrpc_start_hr_threads(), ptlrpc_stop_hr_threads(), srpc_abort_service(), srpc_finish_service(), srpc_service_add_buffers(), srpc_service_fini(), srpc_service_init(), srpc_service_remove_buffers(), and srpc_shutdown_service().
#define cfs_percpt_lock_alloc (cptab)
Value:
({                                                                      \
        static struct lock_class_key  ___keys[CFS_PERCPT_LOCK_KEYS];    \
        struct cfs_percpt_lock       *___lk;                            \
                                                                        \
        if (cfs_cpt_number(cptab) > CFS_PERCPT_LOCK_KEYS)               \
                ___lk = cfs_percpt_lock_create(cptab, NULL);            \
        else                                                            \
                ___lk = cfs_percpt_lock_create(cptab, ___keys);         \
        ___lk;                                                          \
})
Definition at line 266 of file libcfs_cpu.h.
Referenced by lnet_create_locks().
#define CFS_PERCPT_LOCK_KEYS 256
Definition at line 263 of file libcfs_cpu.h.
#define cfs_percpt_lock_num (pcl) cfs_cpt_number(pcl->pcl_cptab)
Definition at line 247 of file libcfs_cpu.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
CFS_PERCPT_LOCK_EX
Definition at line 233 of file libcfs_cpu.h.
Function Documentation
int cfs_cpt_bind (struct cfs_cpt_table * cptab, int cpt)
bind current thread on a CPU-partition cpt of cptab
Definition at line 207 of file libcfs_cpu.c.
Referenced by cfs_wi_scheduler(), kiblnd_scheduler(), ksocknal_scheduler(), ptlrpc_hr_main(), ptlrpc_main(), and ptlrpcd().
void cfs_cpt_clear (struct cfs_cpt_table * cptab, int cpt)
unset all cpus for CPU partition cpt
Definition at line 173 of file libcfs_cpu.c.
cpumask_t* cfs_cpt_cpumask (struct cfs_cpt_table * cptab, int cpt)
return cpumask of CPU partition cpt
Referenced by kiblnd_get_completion_vector().
int cfs_cpt_current (struct cfs_cpt_table * cptab, int remap)
shadow current HW processor ID to CPU-partition ID of cptab
Definition at line 193 of file libcfs_cpu.c.
Referenced by ptlrpc_prep_set(), and ptlrpcd_select_pc().
static void* cfs_cpt_malloc (struct cfs_cpt_table * cptab, int cpt, size_t nr_bytes, gfp_t flags) [inline, static]
allocate nr_bytes of physical memory from a contiguous region with the properties of flags which are bound to the partition id cpt.
This function should only be used for the case when only a few pages of memory are need.
Definition at line 285 of file libcfs_cpu.h.
References cfs_cpt_spread_node().
nodemask_t* cfs_cpt_nodemask (struct cfs_cpt_table * cptab, int cpt)
return nodemask of CPU partition cpt
Definition at line 114 of file libcfs_cpu.c.
References cfs_cpt_table::ctb_nodemask.
Referenced by ost_setup().
int cfs_cpt_number (struct cfs_cpt_table * cptab)
return total number of CPU partitions in cptab
Definition at line 93 of file libcfs_cpu.c.
Referenced by cfs_percpt_alloc(), cfs_percpt_lock(), cfs_percpt_unlock(), cfs_wi_sched_create(), ksocknal_net_start_threads(), lnet_lib_init(), lnet_selftest_exit(), lnet_selftest_init(), ost_setup(), ptlrpc_hr_select(), ptlrpc_register_service(), ptlrpcd_fini(), ptlrpcd_init(), sfw_load_test(), and srpc_service_init().
int cfs_cpt_of_cpu (struct cfs_cpt_table * cptab, int cpu)
shadow HW processor ID CPU to CPU-partition ID by cptab
Definition at line 200 of file libcfs_cpu.c.
int cfs_cpt_online (struct cfs_cpt_table * cptab, int cpt)
is there any online CPU in CPU partition cpt
Definition at line 107 of file libcfs_cpu.c.
int cfs_cpt_set_cpu (struct cfs_cpt_table * cptab, int cpt, int cpu)
add cpu to CPU partion of cptab, return 1 for success, otherwise 0 is returned
Definition at line 121 of file libcfs_cpu.c.
int cfs_cpt_set_cpumask (struct cfs_cpt_table * cptab, int cpt, cpumask_t * mask)
add all cpus in mask to CPU partition cpt return 1 if successfully set all CPUs, otherwise return 0
Definition at line 134 of file libcfs_cpu.c.
int cfs_cpt_set_node (struct cfs_cpt_table * cptab, int cpt, int node)
add all cpus in NUMA node node to CPU partition cpt return 1 if successfully set all CPUs, otherwise return 0
Definition at line 147 of file libcfs_cpu.c.
Referenced by ost_setup().
int cfs_cpt_set_nodemask (struct cfs_cpt_table * cptab, int cpt, nodemask_t * mask)
add all cpus in node mask mask to CPU partition cpt return 1 if successfully set all CPUs, otherwise return 0
Definition at line 160 of file libcfs_cpu.c.
int cfs_cpt_spread_node (struct cfs_cpt_table * cptab, int cpt)
convert partition id cpt to numa node id, if there are more than one nodes in this partition, it might return a different node id each time.
Definition at line 179 of file libcfs_cpu.c.
Referenced by cfs_cpt_malloc(), cfs_cpt_vzalloc(), cfs_mem_cache_cpt_alloc(), and cfs_page_cpt_alloc().
struct cfs_cpt_table* cfs_cpt_table_alloc (unsigned int ncpt) [read]
create a cfs_cpt_table with ncpt number of partitions
Definition at line 49 of file libcfs_cpu.c.
References CERROR, CFS_CPU_VERSION_MAGIC, cfs_cpt_table::ctb_nodemask, cfs_cpt_table::ctb_nparts, cfs_cpt_table::ctb_version, and LIBCFS_ALLOC.
Referenced by cfs_cpu_init(), and ost_setup().
void cfs_cpt_table_free (struct cfs_cpt_table * cptab)
destroy a CPU partition table
Definition at line 70 of file libcfs_cpu.c.
References CFS_CPU_VERSION_MAGIC, cfs_cpt_table::ctb_version, LASSERT, and LIBCFS_FREE.
Referenced by cfs_cpu_fini(), ost_cleanup(), and ost_setup().
int cfs_cpt_table_print (struct cfs_cpt_table * cptab, char * buf, int len)
print string information of cpt-table
Definition at line 79 of file libcfs_cpu.c.
Referenced by __proc_cpt_table().
void cfs_cpt_unset_cpu (struct cfs_cpt_table * cptab, int cpt, int cpu)
remove cpu from CPU partition cpt of cptab
Definition at line 128 of file libcfs_cpu.c.
void cfs_cpt_unset_cpumask (struct cfs_cpt_table * cptab, int cpt, cpumask_t * mask)
remove all cpus in mask from CPU partition cpt
Definition at line 141 of file libcfs_cpu.c.
void cfs_cpt_unset_node (struct cfs_cpt_table * cptab, int cpt, int node)
remove all cpus in NUMA node node from CPU partition cpt
Definition at line 154 of file libcfs_cpu.c.
void cfs_cpt_unset_nodemask (struct cfs_cpt_table * cptab, int cpt, nodemask_t * mask)
remove all cpus in node mask mask from CPU partition cpt
Definition at line 167 of file libcfs_cpu.c.
static void* cfs_cpt_vzalloc (struct cfs_cpt_table * cptab, int cpt, size_t nr_bytes) [inline, static]
allocate nr_bytes of virtually contiguous memory that is bound to the partition id cpt.
Definition at line 297 of file libcfs_cpu.h.
References cfs_cpt_spread_node().
int cfs_cpt_weight (struct cfs_cpt_table * cptab, int cpt)
return number of HW cores or hypter-threadings in a CPU partition cpt
Definition at line 100 of file libcfs_cpu.c.
Referenced by kiblnd_base_startup(), kiblnd_start_schedulers(), ksocknal_base_startup(), ksocknal_start_schedulers(), libcfs_init(), lnet_msg_container_setup(), lnet_selftest_init(), ptlrpc_hr_init(), ptlrpc_server_nthreads_check(), and ptlrpcd_init().
void cfs_cpu_fini (void)
Definition at line 214 of file libcfs_cpu.c.
References cfs_cpt_table_free().
Referenced by libcfs_exit(), and libcfs_init().
int cfs_cpu_ht_nsiblings (int cpu)
return number of HTs in the same core of cpu
Definition at line 186 of file libcfs_cpu.c.
Referenced by ptlrpc_hr_init(), and ptlrpc_server_nthreads_check().
int cfs_cpu_init (void)
Definition at line 223 of file libcfs_cpu.c.
References cfs_cpt_table_alloc().
Referenced by libcfs_init().
static void* cfs_mem_cache_cpt_alloc (struct kmem_cache * cachep, struct cfs_cpt_table * cptab, int cpt, gfp_t flags) [inline, static]
allocate a chunck of memory from a memory pool that is bound to the partition id cpt with the properites of flags.
Definition at line 325 of file libcfs_cpu.h.
References cfs_cpt_spread_node().
static struct page* cfs_page_cpt_alloc (struct cfs_cpt_table * cptab, int cpt, gfp_t flags) [static, read]
allocate a single page of memory with the properties of flags were that page is bound to the partition id cpt.
Definition at line 315 of file libcfs_cpu.h.
References cfs_cpt_spread_node().
Referenced by kiblnd_alloc_pages(), lnet_new_rtrbuf(), and srpc_alloc_bulk().
void* cfs_percpt_alloc (struct cfs_cpt_table * cptab, unsigned int size)
Definition at line 78 of file libcfs_mem.c.
References cfs_cpt_number(), cfs_percpt_free(), LIBCFS_ALLOC, LIBCFS_CPT_ALLOC, offsetof, cfs_var_array::va_count, cfs_var_array::va_cptab, cfs_var_array::va_ptrs, and cfs_var_array::va_size.
Referenced by cfs_percpt_lock_create(), kiblnd_base_startup(), kiblnd_net_init_pools(), ksocknal_base_startup(), lnet_msg_containers_create(), lnet_ni_alloc(), lnet_peer_tables_create(), lnet_prepare(), lnet_ptl_setup(), lnet_res_containers_create(), lnet_rtrpools_alloc(), LNetEQAlloc(), ptlrpc_hr_init(), and srpc_service_init().
void cfs_percpt_free (void * vars)
Definition at line 49 of file libcfs_mem.c.
References LIBCFS_FREE, offsetof, cfs_var_array::va_count, cfs_var_array::va_ptrs, and cfs_var_array::va_size.
Referenced by cfs_percpt_alloc(), cfs_percpt_lock_free(), kiblnd_base_shutdown(), kiblnd_net_fini_pools(), ksocknal_free_buffers(), lnet_msg_containers_destroy(), lnet_ni_free(), lnet_peer_tables_destroy(), lnet_ptl_cleanup(), lnet_res_containers_destroy(), lnet_rtrpools_free(), lnet_unprepare(), LNetEQAlloc(), LNetEQFree(), ptlrpc_hr_fini(), and srpc_service_fini().
void cfs_percpt_lock (struct cfs_percpt_lock * pcl, int index)
lock a CPU partition
index != CFS_PERCPT_LOCK_EX hold private lock indexed by index
index == CFS_PERCPT_LOCK_EX exclusively lock and nobody can take private lock
Definition at line 101 of file libcfs_lock.c.
References cfs_cpt_number(), CFS_PERCPT_LOCK_EX, LASSERT, and likely.
Referenced by lnet_net_lock(), and lnet_res_lock().
struct cfs_percpt_lock* cfs_percpt_lock_create (struct cfs_cpt_table * cptab, struct lock_class_key * keys) [read]
create cpu-partition lock, see libcfs_private.h for more detail.
cpu-partition lock is designed for large-scale SMP system, so we need to reduce cacheline conflict as possible as we can, that's the reason we always allocate cacheline-aligned memory block.
Definition at line 57 of file libcfs_lock.c.
References cfs_percpt_alloc(), cfs_percpt_for_each, CWARN, LIBCFS_ALLOC, LIBCFS_FREE, cfs_percpt_lock::pcl_cptab, and cfs_percpt_lock::pcl_locks.
void cfs_percpt_lock_free (struct cfs_percpt_lock * pcl)
destroy cpu-partition lock, see libcfs_private.h for more detail
Definition at line 39 of file libcfs_lock.c.
References cfs_percpt_free(), LASSERT, LIBCFS_FREE, cfs_percpt_lock::pcl_locked, and cfs_percpt_lock::pcl_locks.
Referenced by lnet_destroy_locks().
int cfs_percpt_number (void * vars)
Definition at line 111 of file libcfs_mem.c.
References cfs_var_array::va_count, and cfs_var_array::va_ptrs.
Referenced by lnet_get_peer_info().
void cfs_percpt_unlock (struct cfs_percpt_lock * pcl, int index)
unlock a CPU partition
Definition at line 136 of file libcfs_lock.c.
References cfs_cpt_number(), CFS_PERCPT_LOCK_EX, LASSERT, and likely.
Referenced by lnet_net_unlock(), and lnet_res_unlock().
Variable Documentation
struct cfs_cpt_table* cfs_cpt_table
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.