Lustre: libcfs/include/libcfs/libcfs_time.h File Reference
libcfs/include/libcfs/libcfs_time.h File Reference
Defines
#define CFS_RATELIMIT(seconds)
#define CFS_TICK 1
Functions
static cfs_time_t cfs_time_add (cfs_time_t t, cfs_duration_t d)
static cfs_duration_t cfs_time_sub (cfs_time_t t1, cfs_time_t t2)
static int cfs_time_after (cfs_time_t t1, cfs_time_t t2)
static int cfs_time_aftereq (cfs_time_t t1, cfs_time_t t2)
static cfs_time_t cfs_time_shift (int seconds)
static long cfs_timeval_sub (struct timeval *large, struct timeval *small, struct timeval *result)
static void cfs_fs_timeval (struct timeval *tv)
static cfs_duration_t cfs_timeout_cap (cfs_duration_t timeout)
Define Documentation
#define CFS_RATELIMIT (seconds)
Value:
({                                                              \
        /*                                                      \
         * XXX nikita: non-portable initializer                 \
         */                                                     \
        static time_t __next_message = 0;                       \
        int result;                                             \
                                                                \
        if (cfs_time_after(cfs_time_current(), __next_message)) \
                result = 1;                                     \
        else {                                                  \
                __next_message = cfs_time_shift(seconds);       \
                result = 0;                                     \
        }                                                       \
        result;                                                 \
})
Definition at line 85 of file libcfs_time.h.
#define CFS_TICK 1
Definition at line 111 of file libcfs_time.h.
Referenced by cfs_timeout_cap(), osc_should_shrink_grant(), and ptlrpc_pinger_process_import().
Function Documentation
static void cfs_fs_timeval (struct timeval * tv) [inline, static]
Definition at line 103 of file libcfs_time.h.
References cfs_fs_time_current(), and cfs_fs_time_usec().
Referenced by ping_client_done_rpc(), and ping_client_prep_rpc().
static cfs_time_t cfs_time_add (cfs_time_t t, cfs_duration_t d) [inline, static]
Definition at line 46 of file libcfs_time.h.
Referenced by cfs_time_shift(), exp_expired(), ksocknal_connect(), ksocknal_process_transmit(), ksocknal_reaper(), ksocknal_send_keepalive_locked(), ldlm_cancel_aged_policy(), ldlm_cancel_lrur_policy(), ldlm_handle_gl_callback(), lnet_peer_alive_locked(), lnet_peer_is_alive(), lnet_ping_router_locked(), ofd_fmd_find_nolock(), ofd_fmd_get(), osc_object_is_contended(), pinger_check_timeout(), ptlrpc_pinger_main(), ptlrpc_send_limit_expired(), sfw_add_session_timer(), and srpc_add_client_rpc_timer().
static int cfs_time_after (cfs_time_t t1, cfs_time_t t2) [inline, static]
Definition at line 56 of file libcfs_time.h.
References cfs_time_before().
Referenced by cli_ctx_check_death(), delay_rule_match(), drop_rule_match(), gss_pipe_destroy_msg(), gss_sec_lookup_ctx_pf(), kiblnd_send_keepalive(), ksocknal_find_conn_locked(), ldlm_cancel_lrur_policy(), ldlm_expired_completion_wait(), ldlm_handle_gl_callback(), libcfs_debug_vmsg2(), lnet_notify(), lnet_peer_is_alive(), lnet_ping_router_locked(), lstcon_rpc_get_reply(), lstcon_rpc_trans_abort(), ofd_create_hdl(), osc_object_is_contended(), ptlrpc_pinger_main(), sec_do_gc(), stt_add_timer(), and stt_expire_list().
static int cfs_time_aftereq (cfs_time_t t1, cfs_time_t t2) [inline, static]
Definition at line 61 of file libcfs_time.h.
References cfs_time_beforeq().
Referenced by delay_rule_match(), drop_rule_match(), kiblnd_check_txs_locked(), kiblnd_fmr_pool_is_idle(), kiblnd_pool_is_idle(), ksocknal_check_peer_timeouts(), ksocknal_connd_get_route_locked(), ksocknal_connect(), ksocknal_find_connectable_route_locked(), ksocknal_find_timed_out_conn(), ksocknal_flush_stale_txs(), ksocknal_process_transmit(), lnet_peer_is_alive(), osc_should_shrink_grant(), osp_precreate_reserve(), ptlrpc_expire_one_request(), ptlrpc_pinger_process_import(), stt_add_timer(), and stt_check_timers().
static cfs_time_t cfs_time_shift (int seconds) [inline, static]
Definition at line 67 of file libcfs_time.h.
References cfs_time_add(), cfs_time_current(), and cfs_time_seconds().
Referenced by delay_rule_match(), kiblnd_create_fmr_pool(), kiblnd_failover_thread(), kiblnd_fmr_pool_map(), kiblnd_init_pool(), kiblnd_pool_alloc_node(), ksocknal_check_zc_req(), ksocknal_create_conn(), ksocknal_launch_packet(), ksocknal_query(), ksocknal_queue_tx_locked(), ksocknal_recv_iov(), ksocknal_recv_kiov(), ksocknal_send_keepalive_locked(), ksocknal_transmit(), ldlm_expired_completion_wait(), ldlm_namespace_dump(), ll_agl_trigger(), lnet_delay_rule_add(), lnet_delay_rule_reset(), lnet_drop_rule_add(), lnet_drop_rule_reset(), lnet_ping_router_locked(), ofd_create_hdl(), osc_update_next_shrink(), osp_init_precreate(), osp_precreate_reserve(), osp_statfs_interpret(), osp_statfs_need_now(), osp_statfs_update(), osp_sync(), ptlrpc_at_set_timer(), ptlrpc_next_reconnect(), ptlrpc_update_next_ping(), upcall_cache_downcall(), and upcall_cache_get_entry().
static cfs_duration_t cfs_time_sub (cfs_time_t t1, cfs_time_t t2) [inline, static]
Definition at line 51 of file libcfs_time.h.
Referenced by cli_ctx_expire(), ksocknal_destroy_conn(), ksocknal_reaper(), ldlm_cancel_lrur_policy(), ldlm_completion_tail(), ldlm_expired_completion_wait(), lnet_eq_wait_locked(), lnet_notify(), lstcon_rpc_pinger(), lstcon_rpc_trans_interpreter(), mgs_ir_notify_complete(), pinger_check_timeout(), proc_lnet_peers(), proc_lnet_routers(), ptlrpc_at_adj_net_latency(), ptlrpc_at_check_timed(), ptlrpc_at_recv_early_reply(), ptlrpc_server_handle_req_in(), ptlrpc_server_handle_request(), round_timeout(), sfw_get_stats(), and stt_check_timers().
static cfs_duration_t cfs_timeout_cap (cfs_duration_t timeout) [inline, static]
Definition at line 117 of file libcfs_time.h.
References CFS_TICK.
Referenced by ptlrpc_disconnect_import(), and ptlrpc_invalidate_import().
static long cfs_timeval_sub (struct timeval * large, struct timeval * small, struct timeval * result) [inline, static]
Definition at line 72 of file libcfs_time.h.
References ONE_MILLION.
Referenced by after_reply(), mdt_identity_do_upcall(), osd_read_prep(), osd_write_prep(), process_param2_config(), ptlrpc_server_handle_request(), and ptlrpc_svcpt_health_check().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.