Lustre: lustre/utils/libiam.c File Reference
lustre/utils/libiam.c File Reference
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <fcntl.h>
#include <string.h>
#include <errno.h>
#include <assert.h>
#include <sys/ioctl.h>
#include <sys/types.h>
#include <libcfs/byteorder.h>
#include <lustre/libiam.h>
Data Structures
struct iam_lfix_root
struct iam_leaf_head
struct dx_countlimit
struct lvar_leaf_header
struct lvar_root
struct lvar_leaf_entry
struct iam_uapi_op
struct iam_uapi_it
Defines
#define STORE_UNALIGNED(val, dst)
Stores val at dst, where the latter is possibly unaligned.
Typedefs
typedef __u32 lvar_hash_t
Enumerations
enum { IAM_LFIX_ROOT_MAGIC = 0xbedabb1edULL, IAM_LVAR_ROOT_MAGIC = 0xb01dface }
enum { IAM_LEAF_HEADER_MAGIC = 0x1976, IAM_LVAR_LEAF_MAGIC = 0x1973 }
enum { LVAR_PAD = 4, LVAR_ROUND = LVAR_PAD - 1 }
enum iam_ioctl_cmd {
IAM_IOC_INIT = _IOW('i', 1, struct iam_uapi_info), IAM_IOC_GETINFO = _IOR('i', 2, struct iam_uapi_info), IAM_IOC_INSERT = _IOR('i', 3, struct iam_uapi_op), IAM_IOC_LOOKUP = _IOWR('i', 4, struct iam_uapi_op),
IAM_IOC_DELETE = _IOR('i', 5, struct iam_uapi_op), IAM_IOC_IT_START = _IOR('i', 6, struct iam_uapi_it), IAM_IOC_IT_NEXT = _IOW('i', 7, struct iam_uapi_it), IAM_IOC_IT_STOP = _IOR('i', 8, struct iam_uapi_it),
IAM_IOC_POLYMORPH = _IOR('i', 9, unsigned long), IAM_IOC_INIT = _IOW('i', 1, struct iam_uapi_info), IAM_IOC_GETINFO = _IOR('i', 2, struct iam_uapi_info), IAM_IOC_INSERT = _IOR('i', 3, struct iam_uapi_op),
IAM_IOC_LOOKUP = _IOWR('i', 4, struct iam_uapi_op), IAM_IOC_DELETE = _IOR('i', 5, struct iam_uapi_op), IAM_IOC_IT_START = _IOR('i', 6, struct iam_uapi_it), IAM_IOC_IT_NEXT = _IOW('i', 7, struct iam_uapi_it),
IAM_IOC_IT_STOP = _IOR('i', 8, struct iam_uapi_it), IAM_IOC_POLYMORPH = _IOR('i', 9, unsigned long), IAM_IOC_INIT = _IOW('i', 1, struct iam_uapi_info), IAM_IOC_GETINFO = _IOR('i', 2, struct iam_uapi_info),
IAM_IOC_INSERT = _IOR('i', 3, struct iam_uapi_op), IAM_IOC_LOOKUP = _IOWR('i', 4, struct iam_uapi_op), IAM_IOC_DELETE = _IOR('i', 5, struct iam_uapi_op), IAM_IOC_IT_START = _IOR('i', 6, struct iam_uapi_it),
IAM_IOC_IT_NEXT = _IOW('i', 7, struct iam_uapi_it), IAM_IOC_IT_STOP = _IOR('i', 8, struct iam_uapi_it), IAM_IOC_POLYMORPH = _IOR('i', 9, unsigned long)
}
Functions
static int root_limit (int rootgap, int blocksize, int size)
static int lfix_root_limit (int blocksize, int size)
static void lfix_root (void *buf, int blocksize, int keysize, int ptrsize, int recsize)
static void lfix_leaf (void *buf, int blocksize, int keysize, int ptrsize, int recsize)
static int lvar_root_limit (int blocksize, int size)
static void lvar_root (void *buf, int blocksize, int keysize, int ptrsize, int recsize)
static int lvar_esize (int namelen, int recsize)
static void lvar_leaf (void *buf, int blocksize, int keysize, int ptrsize, int recsize)
static unsigned char hex2dec (unsigned char hex)
static unsigned char * packdigit (unsigned char *number)
static char * iam_convert (int size, int need_convert, char *source)
static int iam_doop (int fd, struct iam_uapi_info *ua, int cmd, int key_need_convert, char *key_buf, int *keysize, char *save_key, int rec_need_convert, char *rec_buf, int *recsize, char *save_rec)
int iam_creat (char *filename, enum iam_fmt_t fmt, int blocksize, int keysize, int recsize, int ptrsize)
int iam_open (char *filename, struct iam_uapi_info *ua)
int iam_close (int fd)
int iam_insert (int fd, struct iam_uapi_info *ua, int key_need_convert, char *key_buf, int rec_need_convert, char *rec_buf)
int iam_lookup (int fd, struct iam_uapi_info *ua, int key_need_convert, char *key_buf, int *keysize, char *save_key, int rec_need_convert, char *rec_buf, int *recsize, char *save_rec)
int iam_delete (int fd, struct iam_uapi_info *ua, int key_need_convert, char *key_buf, int rec_need_convert, char *rec_buf)
int iam_it_start (int fd, struct iam_uapi_info *ua, int key_need_convert, char *key_buf, int *keysize, char *save_key, int rec_need_convert, char *rec_buf, int *recsize, char *save_rec)
int iam_it_next (int fd, struct iam_uapi_info *ua, int key_need_convert, char *key_buf, int *keysize, char *save_key, int rec_need_convert, char *rec_buf, int *recsize, char *save_rec)
int iam_it_stop (int fd, struct iam_uapi_info *ua, int key_need_convert, char *key_buf, int rec_need_convert, char *rec_buf)
int iam_polymorph (char *filename, unsigned long mode)
Define Documentation
#define STORE_UNALIGNED (val, dst)
Value:
({                                              \
        typeof(*(dst)) __val = (val);           \
                                                \
        memcpy(dst, &__val, sizeof *(dst));     \
})
Stores val at dst, where the latter is possibly unaligned.
Uses memcpy(). This macro is needed to avoid dependency of user level tools on the kernel headers.
Definition at line 119 of file libiam.c.
Typedef Documentation
typedef __u32 lvar_hash_t
Definition at line 59 of file libiam.c.
Enumeration Type Documentation
anonymous enum
Enumerator:
IAM_LFIX_ROOT_MAGIC
IAM_LVAR_ROOT_MAGIC
Definition at line 61 of file libiam.c.
anonymous enum
Enumerator:
IAM_LEAF_HEADER_MAGIC
IAM_LVAR_LEAF_MAGIC
Definition at line 74 of file libiam.c.
anonymous enum
Enumerator:
LVAR_PAD
LVAR_ROUND
Definition at line 109 of file libiam.c.
enum iam_ioctl_cmd
Enumerator:
IAM_IOC_INIT
IAM_IOC_GETINFO
IAM_IOC_INSERT
IAM_IOC_LOOKUP
IAM_IOC_DELETE
IAM_IOC_IT_START
IAM_IOC_IT_NEXT
IAM_IOC_IT_STOP
IAM_IOC_POLYMORPH
IAM_IOC_INIT
IAM_IOC_GETINFO
IAM_IOC_INSERT
IAM_IOC_LOOKUP
IAM_IOC_DELETE
IAM_IOC_IT_START
IAM_IOC_IT_NEXT
IAM_IOC_IT_STOP
IAM_IOC_POLYMORPH
IAM_IOC_INIT
IAM_IOC_GETINFO
IAM_IOC_INSERT
IAM_IOC_LOOKUP
IAM_IOC_DELETE
IAM_IOC_IT_START
IAM_IOC_IT_NEXT
IAM_IOC_IT_STOP
IAM_IOC_POLYMORPH
Definition at line 291 of file libiam.c.
Function Documentation
static unsigned char hex2dec (unsigned char hex) [static]
Definition at line 303 of file libiam.c.
static char* iam_convert (int size, int need_convert, char * source) [static]
Definition at line 328 of file libiam.c.
References opt, packdigit(), and strlcpy().
Referenced by iam_doop().
static int iam_doop (int fd, struct iam_uapi_info * ua, int cmd, int key_need_convert, char * key_buf, int * keysize, char * save_key, int rec_need_convert, char * rec_buf, int * recsize, char * save_rec) [static]
Definition at line 356 of file libiam.c.
References iam_convert(), iam_uapi_info::iui_keysize, iam_uapi_info::iui_recsize, iam_uapi_op::iul_key, iam_uapi_op::iul_rec, and ret.
Referenced by iam_delete(), iam_insert(), iam_it_next(), iam_it_start(), iam_it_stop(), and iam_lookup().
static void lfix_leaf (void * buf, int blocksize, int keysize, int ptrsize, int recsize) [static]
Definition at line 189 of file libiam.c.
References cpu_to_le16, head, IAM_LEAF_HEADER_MAGIC, and iam_leaf_head::ill_magic.
Referenced by iam_creat().
static void lfix_root (void * buf, int blocksize, int keysize, int ptrsize, int recsize) [static]
Definition at line 143 of file libiam.c.
References dx_countlimit::count, cpu_to_le16, cpu_to_le32, cpu_to_le64, IAM_LFIX_ROOT_MAGIC, iam_lfix_root::ilr_magic, lfix_root_limit(), dx_countlimit::limit, and STORE_UNALIGNED.
Referenced by iam_creat().
static int lfix_root_limit (int blocksize, int size) [static]
Definition at line 138 of file libiam.c.
References root_limit().
Referenced by lfix_root().
static int lvar_esize (int namelen, int recsize) [static]
Definition at line 258 of file libiam.c.
References LVAR_ROUND, and offsetof.
Referenced by lvar_leaf().
static void lvar_leaf (void * buf, int blocksize, int keysize, int ptrsize, int recsize) [static]
Definition at line 264 of file libiam.c.
References cpu_to_le16, head, IAM_LVAR_LEAF_MAGIC, lvar_esize(), offsetof, and lvar_leaf_header::vlh_magic.
Referenced by iam_creat().
static void lvar_root (void * buf, int blocksize, int keysize, int ptrsize, int recsize) [static]
Definition at line 211 of file libiam.c.
References dx_countlimit::count, cpu_to_le16, cpu_to_le32, cpu_to_le64, IAM_LVAR_ROOT_MAGIC, dx_countlimit::limit, lvar_root_limit(), STORE_UNALIGNED, and lvar_root::vr_magic.
Referenced by iam_creat().
static int lvar_root_limit (int blocksize, int size) [static]
Definition at line 206 of file libiam.c.
References root_limit().
Referenced by lvar_root().
static unsigned char* packdigit (unsigned char * number) [static]
Definition at line 315 of file libiam.c.
References hex2dec().
static int root_limit (int rootgap, int blocksize, int size) [static]
Definition at line 126 of file libiam.c.
Referenced by lfix_root_limit(), and lvar_root_limit().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.