Lustre: lnet/utils/lnetconfig/liblnetconfig.c File Reference
lnet/utils/lnetconfig/liblnetconfig.c File Reference
#include <errno.h>
#include <limits.h>
#include <netdb.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <libcfs/util/ioctl.h>
#include <lnet/lnetctl.h>
#include <lnet/socklnd.h>
#include "liblnd.h"
#include "liblnetconfig.h"
#include "cyaml.h"
Data Structures
struct lookup_cmd_hdlr_tbl
Defines
#define CONFIG_CMD "configure"
#define UNCONFIG_CMD "unconfigure"
#define ADD_CMD "add"
#define DEL_CMD "del"
#define SHOW_CMD "show"
Typedefs
typedef int(* cmd_handler_t)(struct cYAML *tree, struct cYAML **show_rc, struct cYAML **err_rc)
Functions
int lustre_lnet_config_lib_init (void)
int lustre_lnet_config_ni_system (bool up, bool load_ni_from_mod, int seq_no, struct cYAML **err_rc)
int lustre_lnet_config_route (char *nw, char *gw, int hops, int prio, int seq_no, struct cYAML **err_rc)
int lustre_lnet_del_route (char *nw, char *gw, int seq_no, struct cYAML **err_rc)
int lustre_lnet_show_route (char *nw, char *gw, int hops, int prio, int detail, int seq_no, struct cYAML **show_rc, struct cYAML **err_rc)
int lustre_lnet_config_net (char *net, char *intf, char *ip2net, int peer_to, int peer_cr, int peer_buf_cr, int credits, char *smp, int seq_no, struct lnet_ioctl_config_lnd_tunables *lnd_tunables, struct cYAML **err_rc)
int lustre_lnet_del_net (char *nw, int seq_no, struct cYAML **err_rc)
int lustre_lnet_show_net (char *nw, int detail, int seq_no, struct cYAML **show_rc, struct cYAML **err_rc)
int lustre_lnet_enable_routing (int enable, int seq_no, struct cYAML **err_rc)
int lustre_lnet_config_buffers (int tiny, int small, int large, int seq_no, struct cYAML **err_rc)
int lustre_lnet_show_routing (int seq_no, struct cYAML **show_rc, struct cYAML **err_rc)
int lustre_lnet_show_peer_credits (int seq_no, struct cYAML **show_rc, struct cYAML **err_rc)
int lustre_lnet_show_stats (int seq_no, struct cYAML **show_rc, struct cYAML **err_rc)
static int handle_yaml_config_route (struct cYAML *tree, struct cYAML **show_rc, struct cYAML **err_rc)
static int handle_yaml_config_net (struct cYAML *tree, struct cYAML **show_rc, struct cYAML **err_rc)
static int handle_yaml_config_buffers (struct cYAML *tree, struct cYAML **show_rc, struct cYAML **err_rc)
static int handle_yaml_config_routing (struct cYAML *tree, struct cYAML **show_rc, struct cYAML **err_rc)
static int handle_yaml_del_route (struct cYAML *tree, struct cYAML **show_rc, struct cYAML **err_rc)
static int handle_yaml_del_net (struct cYAML *tree, struct cYAML **show_rc, struct cYAML **err_rc)
static int handle_yaml_del_routing (struct cYAML *tree, struct cYAML **show_rc, struct cYAML **err_rc)
static int handle_yaml_show_route (struct cYAML *tree, struct cYAML **show_rc, struct cYAML **err_rc)
static int handle_yaml_show_net (struct cYAML *tree, struct cYAML **show_rc, struct cYAML **err_rc)
static int handle_yaml_show_routing (struct cYAML *tree, struct cYAML **show_rc, struct cYAML **err_rc)
static int handle_yaml_show_credits (struct cYAML *tree, struct cYAML **show_rc, struct cYAML **err_rc)
static int handle_yaml_show_stats (struct cYAML *tree, struct cYAML **show_rc, struct cYAML **err_rc)
static cmd_handler_t lookup_fn (char *key, struct lookup_cmd_hdlr_tbl *tbl)
static int lustre_yaml_cb_helper (char *f, struct lookup_cmd_hdlr_tbl *table, struct cYAML **show_rc, struct cYAML **err_rc)
int lustre_yaml_config (char *f, struct cYAML **err_rc)
int lustre_yaml_del (char *f, struct cYAML **err_rc)
int lustre_yaml_show (char *f, struct cYAML **show_rc, struct cYAML **err_rc)
Variables
static struct lookup_cmd_hdlr_tbl lookup_config_tbl []
static struct lookup_cmd_hdlr_tbl lookup_del_tbl []
static struct lookup_cmd_hdlr_tbl lookup_show_tbl []
Define Documentation
#define ADD_CMD "add"
Definition at line 52 of file liblnetconfig.c.
Referenced by lustre_lnet_config_buffers(), lustre_lnet_config_net(), lustre_lnet_config_route(), and lustre_lnet_enable_routing().
#define CONFIG_CMD "configure"
Definition at line 50 of file liblnetconfig.c.
Referenced by lustre_lnet_config_ni_system().
#define DEL_CMD "del"
Definition at line 53 of file liblnetconfig.c.
Referenced by lustre_lnet_del_net(), lustre_lnet_del_route(), and lustre_lnet_enable_routing().
#define SHOW_CMD "show"
Definition at line 54 of file liblnetconfig.c.
Referenced by lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), lustre_lnet_show_route(), lustre_lnet_show_routing(), and lustre_lnet_show_stats().
#define UNCONFIG_CMD "unconfigure"
Definition at line 51 of file liblnetconfig.c.
Referenced by lustre_lnet_config_ni_system().
Typedef Documentation
typedef int(* cmd_handler_t)(struct cYAML *tree, struct cYAML **show_rc, struct cYAML **err_rc)
Definition at line 1253 of file liblnetconfig.c.
Function Documentation
static int handle_yaml_config_buffers (struct cYAML * tree, struct cYAML ** show_rc, struct cYAML ** err_rc) [static]
Definition at line 1351 of file liblnetconfig.c.
References cYAML::cy_valueint, cYAML_get_object_item(), and lustre_lnet_config_buffers().
static int handle_yaml_config_net (struct cYAML * tree, struct cYAML ** show_rc, struct cYAML ** err_rc) [static]
Definition at line 1276 of file liblnetconfig.c.
References credits, cYAML::cy_child, cYAML::cy_valueint, cYAML::cy_valuestring, cYAML_get_object_item(), LNET_MAX_STR_LEN, lustre_interface_parse(), lustre_lnet_config_net(), and size.
static int handle_yaml_config_route (struct cYAML * tree, struct cYAML ** show_rc, struct cYAML ** err_rc) [static]
Definition at line 1257 of file liblnetconfig.c.
References cYAML::cy_valueint, cYAML::cy_valuestring, cYAML_get_object_item(), and lustre_lnet_config_route().
static int handle_yaml_config_routing (struct cYAML * tree, struct cYAML ** show_rc, struct cYAML ** err_rc) [static]
Definition at line 1372 of file liblnetconfig.c.
References cYAML::cy_valueint, cYAML_get_object_item(), LUSTRE_CFG_RC_NO_ERR, and lustre_lnet_enable_routing().
static int handle_yaml_del_net (struct cYAML * tree, struct cYAML ** show_rc, struct cYAML ** err_rc) [static]
Definition at line 1409 of file liblnetconfig.c.
References cYAML::cy_valueint, cYAML::cy_valuestring, cYAML_get_object_item(), and lustre_lnet_del_net().
static int handle_yaml_del_route (struct cYAML * tree, struct cYAML ** show_rc, struct cYAML ** err_rc) [static]
Definition at line 1392 of file liblnetconfig.c.
References cYAML::cy_valueint, cYAML::cy_valuestring, cYAML_get_object_item(), and lustre_lnet_del_route().
static int handle_yaml_del_routing (struct cYAML * tree, struct cYAML ** show_rc, struct cYAML ** err_rc) [static]
Definition at line 1422 of file liblnetconfig.c.
References cYAML::cy_valueint, cYAML_get_object_item(), and lustre_lnet_enable_routing().
static int handle_yaml_show_credits (struct cYAML * tree, struct cYAML ** show_rc, struct cYAML ** err_rc) [static]
Definition at line 1488 of file liblnetconfig.c.
References cYAML::cy_valueint, cYAML_get_object_item(), and lustre_lnet_show_peer_credits().
static int handle_yaml_show_net (struct cYAML * tree, struct cYAML ** show_rc, struct cYAML ** err_rc) [static]
Definition at line 1461 of file liblnetconfig.c.
References cYAML::cy_valueint, cYAML::cy_valuestring, cYAML_get_object_item(), and lustre_lnet_show_net().
static int handle_yaml_show_route (struct cYAML * tree, struct cYAML ** show_rc, struct cYAML ** err_rc) [static]
Definition at line 1434 of file liblnetconfig.c.
References cYAML::cy_valueint, cYAML::cy_valuestring, cYAML_get_object_item(), and lustre_lnet_show_route().
static int handle_yaml_show_routing (struct cYAML * tree, struct cYAML ** show_rc, struct cYAML ** err_rc) [static]
Definition at line 1477 of file liblnetconfig.c.
References cYAML::cy_valueint, cYAML_get_object_item(), and lustre_lnet_show_routing().
static int handle_yaml_show_stats (struct cYAML * tree, struct cYAML ** show_rc, struct cYAML ** err_rc) [static]
Definition at line 1500 of file liblnetconfig.c.
References cYAML::cy_valueint, cYAML_get_object_item(), and lustre_lnet_show_stats().
static cmd_handler_t lookup_fn (char * key, struct lookup_cmd_hdlr_tbl * tbl) [static]
Definition at line 1541 of file liblnetconfig.c.
References lookup_cmd_hdlr_tbl::cb, name, and lookup_cmd_hdlr_tbl::name.
Referenced by lustre_yaml_cb_helper().
int lustre_lnet_config_buffers (int tiny, int small, int large, int seq_no, struct cYAML ** err_rc)
Definition at line 814 of file liblnetconfig.c.
References ADD_CMD, lnet_ioctl_config_data::cfg_buffers, lnet_ioctl_config_data::cfg_config_u, lnet_ioctl_config_data::cfg_hdr, cYAML_build_error(), IOC_LIBCFS_ADD_BUF, l_ioctl(), LIBCFS_IOC_INIT_V2, LNET_DEV_ID, LNET_MAX_STR_LEN, LUSTRE_CFG_RC_NO_ERR, and LUSTRE_CFG_RC_OUT_OF_RANGE_PARAM.
Referenced by handle_yaml_config_buffers(), jt_set_large(), jt_set_small(), and jt_set_tiny().
int lustre_lnet_config_lib_init (void)
Definition at line 56 of file liblnetconfig.c.
References LNET_DEV_ID, LNET_DEV_MAJOR, LNET_DEV_MINOR, LNET_DEV_PATH, and register_ioc_dev().
Referenced by main().
int lustre_lnet_config_net (char * net, char * intf, char * ip2net, int peer_to, int peer_cr, int peer_buf_cr, int credits, char * smp, int seq_no, struct lnet_ioctl_config_lnd_tunables * lnd_tunables, struct cYAML ** err_rc)
Definition at line 443 of file liblnetconfig.c.
References ADD_CMD, buf, lnet_ioctl_config_data::cfg_bulk, lnet_ioctl_config_data::cfg_config_u, lnet_ioctl_config_data::cfg_hdr, lnet_ioctl_config_data::cfg_net, cYAML_build_error(), libcfs_ioctl_hdr::ioc_len, IOC_LIBCFS_ADD_NET, l_ioctl(), LIBCFS_IOC_INIT_V2, LNET_DEV_ID, LNET_MAX_STR_LEN, LUSTRE_CFG_RC_MISSING_PARAM, LUSTRE_CFG_RC_NO_ERR, and LUSTRE_CFG_RC_OUT_OF_RANGE_PARAM.
Referenced by handle_yaml_config_net(), and jt_add_net().
int lustre_lnet_config_ni_system (bool up, bool load_ni_from_mod, int seq_no, struct cYAML ** err_rc)
Definition at line 62 of file liblnetconfig.c.
References CONFIG_CMD, cYAML_build_error(), libcfs_ioctl_data::ioc_flags, IOC_LIBCFS_CONFIGURE, IOC_LIBCFS_UNCONFIGURE, l_ioctl(), LIBCFS_IOC_INIT, LNET_DEV_ID, LNET_MAX_STR_LEN, and UNCONFIG_CMD.
Referenced by jt_config_lnet(), and jt_unconfig_lnet().
int lustre_lnet_config_route (char * nw, char * gw, int hops, int prio, int seq_no, struct cYAML ** err_rc)
Definition at line 95 of file liblnetconfig.c.
References ADD_CMD, lnet_ioctl_config_data::cfg_config_u, lnet_ioctl_config_data::cfg_hdr, lnet_ioctl_config_data::cfg_net, lnet_ioctl_config_data::cfg_nid, lnet_ioctl_config_data::cfg_route, CIBLND, cYAML_build_error(), IIBLND, IOC_LIBCFS_ADD_ROUTE, l_ioctl(), LIBCFS_IOC_INIT_V2, libcfs_lnd2str(), libcfs_str2net(), libcfs_str2nid(), LNET_DEV_ID, LNET_MAX_STR_LEN, LNET_NETTYP(), LNET_NID_ANY, LNET_NIDNET(), LNET_UNDEFINED_HOPS, LUSTRE_CFG_RC_BAD_PARAM, LUSTRE_CFG_RC_MISSING_PARAM, LUSTRE_CFG_RC_NO_ERR, LUSTRE_CFG_RC_OUT_OF_RANGE_PARAM, OPENIBLND, and VIBLND.
Referenced by handle_yaml_config_route(), and jt_add_route().
int lustre_lnet_del_net (char * nw, int seq_no, struct cYAML ** err_rc)
Definition at line 533 of file liblnetconfig.c.
References lnet_ioctl_config_data::cfg_hdr, lnet_ioctl_config_data::cfg_net, cYAML_build_error(), DEL_CMD, IOC_LIBCFS_DEL_NET, l_ioctl(), LIBCFS_IOC_INIT_V2, libcfs_str2net(), LNET_DEV_ID, LNET_MAX_STR_LEN, LNET_NID_ANY, LNET_NIDNET(), LUSTRE_CFG_RC_BAD_PARAM, LUSTRE_CFG_RC_MISSING_PARAM, and LUSTRE_CFG_RC_NO_ERR.
Referenced by handle_yaml_del_net(), and jt_del_net().
int lustre_lnet_del_route (char * nw, char * gw, int seq_no, struct cYAML ** err_rc)
Definition at line 189 of file liblnetconfig.c.
References lnet_ioctl_config_data::cfg_hdr, lnet_ioctl_config_data::cfg_net, lnet_ioctl_config_data::cfg_nid, CIBLND, cYAML_build_error(), DEL_CMD, IIBLND, IOC_LIBCFS_DEL_ROUTE, l_ioctl(), LIBCFS_IOC_INIT_V2, libcfs_lnd2str(), libcfs_str2net(), libcfs_str2nid(), LNET_DEV_ID, LNET_MAX_STR_LEN, LNET_NETTYP(), LNET_NID_ANY, LNET_NIDNET(), LUSTRE_CFG_RC_BAD_PARAM, LUSTRE_CFG_RC_MISSING_PARAM, LUSTRE_CFG_RC_NO_ERR, OPENIBLND, and VIBLND.
Referenced by handle_yaml_del_route(), and jt_del_route().
int lustre_lnet_enable_routing (int enable, int seq_no, struct cYAML ** err_rc)
Definition at line 785 of file liblnetconfig.c.
References ADD_CMD, lnet_ioctl_config_data::cfg_buffers, lnet_ioctl_config_data::cfg_config_u, lnet_ioctl_config_data::cfg_hdr, cYAML_build_error(), DEL_CMD, IOC_LIBCFS_CONFIG_RTR, l_ioctl(), LIBCFS_IOC_INIT_V2, LNET_DEV_ID, LNET_MAX_STR_LEN, and LUSTRE_CFG_RC_NO_ERR.
Referenced by handle_yaml_config_routing(), handle_yaml_del_routing(), and jt_set_routing().
int lustre_lnet_show_net (char * nw, int detail, int seq_no, struct cYAML ** show_rc, struct cYAML ** err_rc)
Definition at line 577 of file liblnetconfig.c.
References buf, lnet_ioctl_config_data::cfg_bulk, lnet_ioctl_config_data::cfg_config_u, lnet_ioctl_config_data::cfg_count, lnet_ioctl_config_data::cfg_hdr, lnet_ioctl_config_data::cfg_ncpts, lnet_ioctl_config_data::cfg_net, lnet_ioctl_config_data::cfg_nid, cYAML_build_error(), cYAML_create_number(), cYAML_create_object(), cYAML_create_seq(), cYAML_create_seq_item(), cYAML_create_string(), cYAML_free_tree(), cYAML_get_object_item(), cYAML_insert_child(), cYAML_insert_sibling(), cYAML_is_sequence(), cYAML_print_tree(), libcfs_ioctl_hdr::ioc_len, IOC_LIBCFS_GET_NET, l_ioctl(), LIBCFS_IOC_INIT_V2, libcfs_net2str(), libcfs_nid2str(), libcfs_str2net(), LNET_DEV_ID, LNET_MAX_INTERFACES, LNET_MAX_SHOW_NUM_CPT, LNET_MAX_STR_LEN, LNET_NI_STATUS_UP, LNET_NID_ANY, LNET_NIDNET(), LUSTRE_CFG_RC_BAD_PARAM, LUSTRE_CFG_RC_NO_ERR, LUSTRE_CFG_RC_OUT_OF_MEM, lustre_interface_show_net(), lnet_ioctl_net_config::ni_cpts, lnet_ioctl_net_config::ni_interfaces, lnet_ioctl_net_config::ni_status, and SHOW_CMD.
Referenced by handle_yaml_show_net(), jt_export(), and jt_show_net().
int lustre_lnet_show_peer_credits (int seq_no, struct cYAML ** show_rc, struct cYAML ** err_rc)
Definition at line 1005 of file liblnetconfig.c.
References cYAML_build_error(), cYAML_create_number(), cYAML_create_object(), cYAML_create_seq(), cYAML_create_seq_item(), cYAML_create_string(), cYAML_free_tree(), cYAML_get_object_item(), cYAML_insert_child(), cYAML_insert_sibling(), cYAML_is_sequence(), cYAML_print_tree(), IOC_LIBCFS_GET_PEER_INFO, l_ioctl(), LIBCFS_IOC_INIT_V2, libcfs_nid2str(), LNET_DEV_ID, LNET_MAX_STR_LEN, LUSTRE_CFG_RC_NO_ERR, LUSTRE_CFG_RC_OUT_OF_MEM, lnet_ioctl_peer::pr_count, lnet_ioctl_peer::pr_lnd_u, lnet_ioctl_peer::pr_nid, lnet_ioctl_peer::pr_peer_credits, and SHOW_CMD.
Referenced by handle_yaml_show_credits(), and jt_show_peer_credits().
int lustre_lnet_show_route (char * nw, char * gw, int hops, int prio, int detail, int seq_no, struct cYAML ** show_rc, struct cYAML ** err_rc)
Definition at line 258 of file liblnetconfig.c.
References lnet_ioctl_config_data::cfg_config_u, lnet_ioctl_config_data::cfg_count, lnet_ioctl_config_data::cfg_net, lnet_ioctl_config_data::cfg_nid, lnet_ioctl_config_data::cfg_route, CIBLND, cYAML_build_error(), cYAML_create_number(), cYAML_create_object(), cYAML_create_seq(), cYAML_create_seq_item(), cYAML_create_string(), cYAML_free_tree(), cYAML_get_object_item(), cYAML_insert_child(), cYAML_insert_sibling(), cYAML_is_sequence(), cYAML_print_tree(), IIBLND, IOC_LIBCFS_GET_ROUTE, l_ioctl(), LIBCFS_IOC_INIT_V2, libcfs_lnd2str(), libcfs_net2str(), libcfs_nid2str(), libcfs_str2net(), libcfs_str2nid(), LNET_DEV_ID, LNET_MAX_STR_LEN, LNET_NETTYP(), LNET_NID_ANY, LNET_NIDNET(), LUSTRE_CFG_RC_BAD_PARAM, LUSTRE_CFG_RC_NO_ERR, LUSTRE_CFG_RC_OUT_OF_MEM, LUSTRE_CFG_RC_OUT_OF_RANGE_PARAM, OPENIBLND, lnet_ioctl_config_data::rtr_priority, SHOW_CMD, and VIBLND.
Referenced by handle_yaml_show_route(), jt_export(), and jt_show_route().
int lustre_lnet_show_routing (int seq_no, struct cYAML ** show_rc, struct cYAML ** err_rc)
Definition at line 852 of file liblnetconfig.c.
References buf, lnet_ioctl_config_data::cfg_bulk, lnet_ioctl_config_data::cfg_count, lnet_ioctl_config_data::cfg_hdr, cYAML::cy_child, cYAML_build_error(), cYAML_create_number(), cYAML_create_object(), cYAML_create_seq(), cYAML_create_seq_item(), cYAML_free_tree(), cYAML_get_object_item(), cYAML_insert_sibling(), cYAML_print_tree(), libcfs_ioctl_hdr::ioc_len, IOC_LIBCFS_GET_BUF, l_ioctl(), LIBCFS_IOC_INIT_V2, LNET_DEV_ID, LNET_MAX_STR_LEN, LNET_NRBPOOLS, LUSTRE_CFG_RC_NO_ERR, LUSTRE_CFG_RC_OUT_OF_MEM, lnet_ioctl_pool_cfg::pl_credits, lnet_ioctl_pool_cfg::pl_mincredits, lnet_ioctl_pool_cfg::pl_nbuffers, lnet_ioctl_pool_cfg::pl_npages, lnet_ioctl_pool_cfg::pl_pools, lnet_ioctl_pool_cfg::pl_routing, and SHOW_CMD.
Referenced by handle_yaml_show_routing(), jt_export(), and jt_show_routing().
int lustre_lnet_show_stats (int seq_no, struct cYAML ** show_rc, struct cYAML ** err_rc)
Definition at line 1157 of file liblnetconfig.c.
References cYAML::cy_child, cYAML_build_error(), cYAML_create_number(), cYAML_create_object(), cYAML_free_tree(), cYAML_insert_sibling(), cYAML_print_tree(), lnet_counters::drop_count, lnet_counters::drop_length, lnet_counters::errors, IOC_LIBCFS_GET_LNET_STATS, l_ioctl(), LIBCFS_IOC_INIT_V2, LNET_DEV_ID, LNET_MAX_STR_LEN, LUSTRE_CFG_RC_NO_ERR, LUSTRE_CFG_RC_OUT_OF_MEM, lnet_counters::msgs_alloc, lnet_counters::msgs_max, lnet_counters::recv_count, lnet_counters::recv_length, lnet_counters::route_count, lnet_counters::route_length, lnet_counters::send_count, lnet_counters::send_length, SHOW_CMD, and lnet_ioctl_lnet_stats::st_cntrs.
Referenced by handle_yaml_show_stats(), and jt_show_stats().
static int lustre_yaml_cb_helper (char * f, struct lookup_cmd_hdlr_tbl * table, struct cYAML ** show_rc, struct cYAML ** err_rc) [static]
Definition at line 1556 of file liblnetconfig.c.
References cb(), cYAML::cy_child, cYAML::cy_next, cYAML_build_error(), cYAML_build_tree(), cYAML_free_tree(), cYAML_get_next_seq_item(), cYAML_is_sequence(), head, LNET_MAX_STR_LEN, lookup_fn(), LUSTRE_CFG_RC_BAD_PARAM, and LUSTRE_CFG_RC_NO_ERR.
Referenced by lustre_yaml_config(), lustre_yaml_del(), and lustre_yaml_show().
int lustre_yaml_config (char * f, struct cYAML ** err_rc)
Definition at line 1602 of file liblnetconfig.c.
References lustre_yaml_cb_helper().
Referenced by jt_import().
int lustre_yaml_del (char * f, struct cYAML ** err_rc)
Definition at line 1608 of file liblnetconfig.c.
References lustre_yaml_cb_helper().
Referenced by jt_import().
int lustre_yaml_show (char * f, struct cYAML ** show_rc, struct cYAML ** err_rc)
Definition at line 1614 of file liblnetconfig.c.
References lustre_yaml_cb_helper().
Referenced by jt_import().
Variable Documentation
struct lookup_cmd_hdlr_tbl lookup_config_tbl[] [static]
Initial value:
 {
        {"route", handle_yaml_config_route},
        {"net", handle_yaml_config_net},
        {"routing", handle_yaml_config_routing},
        {"buffers", handle_yaml_config_buffers},
        {NULL, NULL}
}
Definition at line 1516 of file liblnetconfig.c.
struct lookup_cmd_hdlr_tbl lookup_del_tbl[] [static]
Initial value:
 {
        {"route", handle_yaml_del_route},
        {"net", handle_yaml_del_net},
        {"routing", handle_yaml_del_routing},
        {NULL, NULL}
}
Definition at line 1524 of file liblnetconfig.c.
struct lookup_cmd_hdlr_tbl lookup_show_tbl[] [static]
Initial value:
 {
        {"route", handle_yaml_show_route},
        {"net", handle_yaml_show_net},
        {"buffers", handle_yaml_show_routing},
        {"routing", handle_yaml_show_routing},
        {"credits", handle_yaml_show_credits},
        {"statistics", handle_yaml_show_stats},
        {NULL, NULL}
}
Definition at line 1531 of file liblnetconfig.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.