Lustre: lnet/utils/lnetconfig/liblnetconfig.h File Reference
lnet/utils/lnetconfig/liblnetconfig.h File Reference
#include <lnet/lnet.h>
Defines
#define LUSTRE_CFG_RC_NO_ERR 0
#define LUSTRE_CFG_RC_BAD_PARAM -1
#define LUSTRE_CFG_RC_MISSING_PARAM -2
#define LUSTRE_CFG_RC_OUT_OF_RANGE_PARAM -3
#define LUSTRE_CFG_RC_OUT_OF_MEM -4
#define LUSTRE_CFG_RC_GENERIC_ERR -5
Functions
int lustre_lnet_config_lib_init ()
int lustre_lnet_config_ni_system (bool up, bool load_ni_from_mod, int seq_no, struct cYAML **err_rc)
int lustre_lnet_config_route (char *nw, char *gw, int hops, int prio, int seq_no, struct cYAML **err_rc)
int lustre_lnet_del_route (char *nw, char *gw, int seq_no, struct cYAML **err_rc)
int lustre_lnet_show_route (char *nw, char *gw, int hops, int prio, int detail, int seq_no, struct cYAML **show_rc, struct cYAML **err_rc)
int lustre_lnet_config_net (char *net, char *intf, char *ip2net, int peer_to, int peer_cr, int peer_buf_cr, int credits, char *smp, int seq_no, struct lnet_ioctl_config_lnd_tunables *lnd_tunables, struct cYAML **err_rc)
int lustre_lnet_del_net (char *nw, int seq_no, struct cYAML **err_rc)
int lustre_lnet_show_net (char *nw, int detail, int seq_no, struct cYAML **show_rc, struct cYAML **err_rc)
int lustre_lnet_enable_routing (int enable, int seq_no, struct cYAML **err_rc)
int lustre_lnet_config_buffers (int tiny, int small, int large, int seq_no, struct cYAML **err_rc)
int lustre_lnet_show_routing (int seq_no, struct cYAML **show_rc, struct cYAML **err_rc)
int lustre_lnet_show_peer_credits (int seq_no, struct cYAML **show_rc, struct cYAML **err_rc)
int lustre_lnet_show_stats (int seq_no, struct cYAML **show_rc, struct cYAML **err_rc)
int lustre_yaml_config (char *f, struct cYAML **err_rc)
int lustre_yaml_del (char *f, struct cYAML **err_rc)
int lustre_yaml_show (char *f, struct cYAML **show_rc, struct cYAML **err_rc)
Define Documentation
#define LUSTRE_CFG_RC_BAD_PARAM -1
Definition at line 33 of file liblnetconfig.h.
Referenced by lustre_lnet_config_route(), lustre_lnet_del_net(), lustre_lnet_del_route(), lustre_lnet_show_net(), lustre_lnet_show_route(), and lustre_yaml_cb_helper().
#define LUSTRE_CFG_RC_GENERIC_ERR -5
Definition at line 37 of file liblnetconfig.h.
#define LUSTRE_CFG_RC_MISSING_PARAM -2
Definition at line 34 of file liblnetconfig.h.
Referenced by lustre_lnet_config_net(), lustre_lnet_config_route(), lustre_lnet_del_net(), and lustre_lnet_del_route().
#define LUSTRE_CFG_RC_NO_ERR 0
Definition at line 32 of file liblnetconfig.h.
Referenced by handle_yaml_config_routing(), jt_add_net(), jt_add_route(), jt_config_lnet(), jt_del_net(), jt_del_route(), jt_export(), jt_import(), jt_set_large(), jt_set_routing(), jt_set_small(), jt_set_tiny(), jt_show_net(), jt_show_peer_credits(), jt_show_route(), jt_show_routing(), jt_show_stats(), jt_unconfig_lnet(), lustre_lnet_config_buffers(), lustre_lnet_config_net(), lustre_lnet_config_route(), lustre_lnet_del_net(), lustre_lnet_del_route(), lustre_lnet_enable_routing(), lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), lustre_lnet_show_route(), lustre_lnet_show_routing(), lustre_lnet_show_stats(), and lustre_yaml_cb_helper().
#define LUSTRE_CFG_RC_OUT_OF_MEM -4
Definition at line 36 of file liblnetconfig.h.
Referenced by lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), lustre_lnet_show_route(), lustre_lnet_show_routing(), and lustre_lnet_show_stats().
#define LUSTRE_CFG_RC_OUT_OF_RANGE_PARAM -3
Definition at line 35 of file liblnetconfig.h.
Referenced by lustre_lnet_config_buffers(), lustre_lnet_config_net(), lustre_lnet_config_route(), and lustre_lnet_show_route().
Function Documentation
int lustre_lnet_config_buffers (int tiny, int small, int large, int seq_no, struct cYAML ** err_rc)
Definition at line 814 of file liblnetconfig.c.
References ADD_CMD, lnet_ioctl_config_data::cfg_buffers, lnet_ioctl_config_data::cfg_config_u, lnet_ioctl_config_data::cfg_hdr, cYAML_build_error(), IOC_LIBCFS_ADD_BUF, l_ioctl(), LIBCFS_IOC_INIT_V2, LNET_DEV_ID, LNET_MAX_STR_LEN, LUSTRE_CFG_RC_NO_ERR, and LUSTRE_CFG_RC_OUT_OF_RANGE_PARAM.
Referenced by handle_yaml_config_buffers(), jt_set_large(), jt_set_small(), and jt_set_tiny().
int lustre_lnet_config_lib_init ()
Definition at line 56 of file liblnetconfig.c.
References LNET_DEV_ID, LNET_DEV_MAJOR, LNET_DEV_MINOR, LNET_DEV_PATH, and register_ioc_dev().
Referenced by main().
int lustre_lnet_config_net (char * net, char * intf, char * ip2net, int peer_to, int peer_cr, int peer_buf_cr, int credits, char * smp, int seq_no, struct lnet_ioctl_config_lnd_tunables * lnd_tunables, struct cYAML ** err_rc)
Definition at line 443 of file liblnetconfig.c.
References ADD_CMD, buf, lnet_ioctl_config_data::cfg_bulk, lnet_ioctl_config_data::cfg_config_u, lnet_ioctl_config_data::cfg_hdr, lnet_ioctl_config_data::cfg_net, cYAML_build_error(), libcfs_ioctl_hdr::ioc_len, IOC_LIBCFS_ADD_NET, l_ioctl(), LIBCFS_IOC_INIT_V2, LNET_DEV_ID, LNET_MAX_STR_LEN, LUSTRE_CFG_RC_MISSING_PARAM, LUSTRE_CFG_RC_NO_ERR, and LUSTRE_CFG_RC_OUT_OF_RANGE_PARAM.
Referenced by handle_yaml_config_net(), and jt_add_net().
int lustre_lnet_config_ni_system (bool up, bool load_ni_from_mod, int seq_no, struct cYAML ** err_rc)
Definition at line 62 of file liblnetconfig.c.
References CONFIG_CMD, cYAML_build_error(), libcfs_ioctl_data::ioc_flags, IOC_LIBCFS_CONFIGURE, IOC_LIBCFS_UNCONFIGURE, l_ioctl(), LIBCFS_IOC_INIT, LNET_DEV_ID, LNET_MAX_STR_LEN, and UNCONFIG_CMD.
Referenced by jt_config_lnet(), and jt_unconfig_lnet().
int lustre_lnet_config_route (char * nw, char * gw, int hops, int prio, int seq_no, struct cYAML ** err_rc)
Definition at line 95 of file liblnetconfig.c.
References ADD_CMD, lnet_ioctl_config_data::cfg_config_u, lnet_ioctl_config_data::cfg_hdr, lnet_ioctl_config_data::cfg_net, lnet_ioctl_config_data::cfg_nid, lnet_ioctl_config_data::cfg_route, CIBLND, cYAML_build_error(), IIBLND, IOC_LIBCFS_ADD_ROUTE, l_ioctl(), LIBCFS_IOC_INIT_V2, libcfs_lnd2str(), libcfs_str2net(), libcfs_str2nid(), LNET_DEV_ID, LNET_MAX_STR_LEN, LNET_NETTYP(), LNET_NID_ANY, LNET_NIDNET(), LNET_UNDEFINED_HOPS, LUSTRE_CFG_RC_BAD_PARAM, LUSTRE_CFG_RC_MISSING_PARAM, LUSTRE_CFG_RC_NO_ERR, LUSTRE_CFG_RC_OUT_OF_RANGE_PARAM, OPENIBLND, and VIBLND.
Referenced by handle_yaml_config_route(), and jt_add_route().
int lustre_lnet_del_net (char * nw, int seq_no, struct cYAML ** err_rc)
Definition at line 533 of file liblnetconfig.c.
References lnet_ioctl_config_data::cfg_hdr, lnet_ioctl_config_data::cfg_net, cYAML_build_error(), DEL_CMD, IOC_LIBCFS_DEL_NET, l_ioctl(), LIBCFS_IOC_INIT_V2, libcfs_str2net(), LNET_DEV_ID, LNET_MAX_STR_LEN, LNET_NID_ANY, LNET_NIDNET(), LUSTRE_CFG_RC_BAD_PARAM, LUSTRE_CFG_RC_MISSING_PARAM, and LUSTRE_CFG_RC_NO_ERR.
Referenced by handle_yaml_del_net(), and jt_del_net().
int lustre_lnet_del_route (char * nw, char * gw, int seq_no, struct cYAML ** err_rc)
Definition at line 189 of file liblnetconfig.c.
References lnet_ioctl_config_data::cfg_hdr, lnet_ioctl_config_data::cfg_net, lnet_ioctl_config_data::cfg_nid, CIBLND, cYAML_build_error(), DEL_CMD, IIBLND, IOC_LIBCFS_DEL_ROUTE, l_ioctl(), LIBCFS_IOC_INIT_V2, libcfs_lnd2str(), libcfs_str2net(), libcfs_str2nid(), LNET_DEV_ID, LNET_MAX_STR_LEN, LNET_NETTYP(), LNET_NID_ANY, LNET_NIDNET(), LUSTRE_CFG_RC_BAD_PARAM, LUSTRE_CFG_RC_MISSING_PARAM, LUSTRE_CFG_RC_NO_ERR, OPENIBLND, and VIBLND.
Referenced by handle_yaml_del_route(), and jt_del_route().
int lustre_lnet_enable_routing (int enable, int seq_no, struct cYAML ** err_rc)
Definition at line 785 of file liblnetconfig.c.
References ADD_CMD, lnet_ioctl_config_data::cfg_buffers, lnet_ioctl_config_data::cfg_config_u, lnet_ioctl_config_data::cfg_hdr, cYAML_build_error(), DEL_CMD, IOC_LIBCFS_CONFIG_RTR, l_ioctl(), LIBCFS_IOC_INIT_V2, LNET_DEV_ID, LNET_MAX_STR_LEN, and LUSTRE_CFG_RC_NO_ERR.
Referenced by handle_yaml_config_routing(), handle_yaml_del_routing(), and jt_set_routing().
int lustre_lnet_show_net (char * nw, int detail, int seq_no, struct cYAML ** show_rc, struct cYAML ** err_rc)
Definition at line 577 of file liblnetconfig.c.
References buf, lnet_ioctl_config_data::cfg_bulk, lnet_ioctl_config_data::cfg_config_u, lnet_ioctl_config_data::cfg_count, lnet_ioctl_config_data::cfg_hdr, lnet_ioctl_config_data::cfg_ncpts, lnet_ioctl_config_data::cfg_net, lnet_ioctl_config_data::cfg_nid, cYAML_build_error(), cYAML_create_number(), cYAML_create_object(), cYAML_create_seq(), cYAML_create_seq_item(), cYAML_create_string(), cYAML_free_tree(), cYAML_get_object_item(), cYAML_insert_child(), cYAML_insert_sibling(), cYAML_is_sequence(), cYAML_print_tree(), libcfs_ioctl_hdr::ioc_len, IOC_LIBCFS_GET_NET, l_ioctl(), LIBCFS_IOC_INIT_V2, libcfs_net2str(), libcfs_nid2str(), libcfs_str2net(), LNET_DEV_ID, LNET_MAX_INTERFACES, LNET_MAX_SHOW_NUM_CPT, LNET_MAX_STR_LEN, LNET_NI_STATUS_UP, LNET_NID_ANY, LNET_NIDNET(), LUSTRE_CFG_RC_BAD_PARAM, LUSTRE_CFG_RC_NO_ERR, LUSTRE_CFG_RC_OUT_OF_MEM, lustre_interface_show_net(), lnet_ioctl_net_config::ni_cpts, lnet_ioctl_net_config::ni_interfaces, lnet_ioctl_net_config::ni_status, and SHOW_CMD.
Referenced by handle_yaml_show_net(), jt_export(), and jt_show_net().
int lustre_lnet_show_peer_credits (int seq_no, struct cYAML ** show_rc, struct cYAML ** err_rc)
Definition at line 1005 of file liblnetconfig.c.
References cYAML_build_error(), cYAML_create_number(), cYAML_create_object(), cYAML_create_seq(), cYAML_create_seq_item(), cYAML_create_string(), cYAML_free_tree(), cYAML_get_object_item(), cYAML_insert_child(), cYAML_insert_sibling(), cYAML_is_sequence(), cYAML_print_tree(), IOC_LIBCFS_GET_PEER_INFO, l_ioctl(), LIBCFS_IOC_INIT_V2, libcfs_nid2str(), LNET_DEV_ID, LNET_MAX_STR_LEN, LUSTRE_CFG_RC_NO_ERR, LUSTRE_CFG_RC_OUT_OF_MEM, lnet_ioctl_peer::pr_count, lnet_ioctl_peer::pr_lnd_u, lnet_ioctl_peer::pr_nid, lnet_ioctl_peer::pr_peer_credits, and SHOW_CMD.
Referenced by handle_yaml_show_credits(), and jt_show_peer_credits().
int lustre_lnet_show_route (char * nw, char * gw, int hops, int prio, int detail, int seq_no, struct cYAML ** show_rc, struct cYAML ** err_rc)
Definition at line 258 of file liblnetconfig.c.
References lnet_ioctl_config_data::cfg_config_u, lnet_ioctl_config_data::cfg_count, lnet_ioctl_config_data::cfg_net, lnet_ioctl_config_data::cfg_nid, lnet_ioctl_config_data::cfg_route, CIBLND, cYAML_build_error(), cYAML_create_number(), cYAML_create_object(), cYAML_create_seq(), cYAML_create_seq_item(), cYAML_create_string(), cYAML_free_tree(), cYAML_get_object_item(), cYAML_insert_child(), cYAML_insert_sibling(), cYAML_is_sequence(), cYAML_print_tree(), IIBLND, IOC_LIBCFS_GET_ROUTE, l_ioctl(), LIBCFS_IOC_INIT_V2, libcfs_lnd2str(), libcfs_net2str(), libcfs_nid2str(), libcfs_str2net(), libcfs_str2nid(), LNET_DEV_ID, LNET_MAX_STR_LEN, LNET_NETTYP(), LNET_NID_ANY, LNET_NIDNET(), LUSTRE_CFG_RC_BAD_PARAM, LUSTRE_CFG_RC_NO_ERR, LUSTRE_CFG_RC_OUT_OF_MEM, LUSTRE_CFG_RC_OUT_OF_RANGE_PARAM, OPENIBLND, lnet_ioctl_config_data::rtr_priority, SHOW_CMD, and VIBLND.
Referenced by handle_yaml_show_route(), jt_export(), and jt_show_route().
int lustre_lnet_show_routing (int seq_no, struct cYAML ** show_rc, struct cYAML ** err_rc)
Definition at line 852 of file liblnetconfig.c.
References buf, lnet_ioctl_config_data::cfg_bulk, lnet_ioctl_config_data::cfg_count, lnet_ioctl_config_data::cfg_hdr, cYAML::cy_child, cYAML_build_error(), cYAML_create_number(), cYAML_create_object(), cYAML_create_seq(), cYAML_create_seq_item(), cYAML_free_tree(), cYAML_get_object_item(), cYAML_insert_sibling(), cYAML_print_tree(), libcfs_ioctl_hdr::ioc_len, IOC_LIBCFS_GET_BUF, l_ioctl(), LIBCFS_IOC_INIT_V2, LNET_DEV_ID, LNET_MAX_STR_LEN, LNET_NRBPOOLS, LUSTRE_CFG_RC_NO_ERR, LUSTRE_CFG_RC_OUT_OF_MEM, lnet_ioctl_pool_cfg::pl_credits, lnet_ioctl_pool_cfg::pl_mincredits, lnet_ioctl_pool_cfg::pl_nbuffers, lnet_ioctl_pool_cfg::pl_npages, lnet_ioctl_pool_cfg::pl_pools, lnet_ioctl_pool_cfg::pl_routing, and SHOW_CMD.
Referenced by handle_yaml_show_routing(), jt_export(), and jt_show_routing().
int lustre_lnet_show_stats (int seq_no, struct cYAML ** show_rc, struct cYAML ** err_rc)
Definition at line 1157 of file liblnetconfig.c.
References cYAML::cy_child, cYAML_build_error(), cYAML_create_number(), cYAML_create_object(), cYAML_free_tree(), cYAML_insert_sibling(), cYAML_print_tree(), lnet_counters::drop_count, lnet_counters::drop_length, lnet_counters::errors, IOC_LIBCFS_GET_LNET_STATS, l_ioctl(), LIBCFS_IOC_INIT_V2, LNET_DEV_ID, LNET_MAX_STR_LEN, LUSTRE_CFG_RC_NO_ERR, LUSTRE_CFG_RC_OUT_OF_MEM, lnet_counters::msgs_alloc, lnet_counters::msgs_max, lnet_counters::recv_count, lnet_counters::recv_length, lnet_counters::route_count, lnet_counters::route_length, lnet_counters::send_count, lnet_counters::send_length, SHOW_CMD, and lnet_ioctl_lnet_stats::st_cntrs.
Referenced by handle_yaml_show_stats(), and jt_show_stats().
int lustre_yaml_config (char * f, struct cYAML ** err_rc)
Definition at line 1602 of file liblnetconfig.c.
References lustre_yaml_cb_helper().
Referenced by jt_import().
int lustre_yaml_del (char * f, struct cYAML ** err_rc)
Definition at line 1608 of file liblnetconfig.c.
References lustre_yaml_cb_helper().
Referenced by jt_import().
int lustre_yaml_show (char * f, struct cYAML ** show_rc, struct cYAML ** err_rc)
Definition at line 1614 of file liblnetconfig.c.
References lustre_yaml_cb_helper().
Referenced by jt_import().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.