Lustre: lnet/utils/lnetconfig/liblnd.h File Reference
lnet/utils/lnetconfig/liblnd.h File Reference
#include <lnet/lib-dlc.h>
#include "cyaml.h"
Functions
int lustre_interface_show_net (struct cYAML *interfaces, unsigned int index, bool detail, struct lnet_ioctl_config_data *data, struct lnet_ioctl_net_config *net_config)
void lustre_interface_parse (struct cYAML *lndparams, const char *dev_name, struct lnet_ioctl_config_lnd_tunables *lnd_cfg)
Function Documentation
void lustre_interface_parse (struct cYAML * lndparams, const char * dev_name, struct lnet_ioctl_config_lnd_tunables * lnd_cfg)
Definition at line 132 of file liblnetconfig_lnd.c.
References lustre_ko2iblnd_parse_net().
Referenced by handle_yaml_config_net().
int lustre_interface_show_net (struct cYAML * interfaces, unsigned int index, bool detail, struct lnet_ioctl_config_data * data, struct lnet_ioctl_net_config * net_config)
Definition at line 67 of file liblnetconfig_lnd.c.
References lnet_ioctl_net_config::cfg_bulk, lnet_ioctl_config_data::cfg_config_u, lnet_ioctl_config_data::cfg_net, lnet_ioctl_config_data::cfg_nid, cYAML_create_object(), cYAML_create_string(), LNET_NETTYP(), LNET_NIDNET(), lustre_ko2iblnd_show_net(), lnet_ioctl_net_config::ni_interfaces, and O2IBLND.
Referenced by lustre_lnet_show_net().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.