Lustre: lustre/utils/liblustreapi_kernelconn.c File Reference
lustre/utils/liblustreapi_kernelconn.c File Reference
#include <unistd.h>
#include <fcntl.h>
#include <string.h>
#include <errno.h>
#include <lustre/lustreapi.h>
#include "lustreapi_internal.h"
Defines
#define lhsz sizeof(*kuch)
Functions
int libcfs_ukuc_start (struct lustre_kernelcomm *link, int group, int rfd_flags)
Start the userspace side of a KUC pipe.
int libcfs_ukuc_stop (struct lustre_kernelcomm *link)
int libcfs_ukuc_get_rfd (struct lustre_kernelcomm *link)
Returns the file descriptor for the read side of the pipe, to be used with poll/select.
int libcfs_ukuc_msg_get (struct lustre_kernelcomm *link, char *buf, int maxsize, int transport)
Read a message from the link.
Define Documentation
#define lhsz sizeof(*kuch)
Definition at line 98 of file liblustreapi_kernelconn.c.
Referenced by libcfs_ukuc_msg_get().
Function Documentation
int libcfs_ukuc_get_rfd (struct lustre_kernelcomm * link)
Returns the file descriptor for the read side of the pipe, to be used with poll/select.
Parameters:
link Private descriptor for pipe/socket.
Definition at line 93 of file liblustreapi_kernelconn.c.
References lustre_kernelcomm::lk_rfd.
Referenced by llapi_hsm_copytool_get_fd().
int libcfs_ukuc_msg_get (struct lustre_kernelcomm * link, char * buf, int maxsize, int transport)
Read a message from the link.
Allocates memory, returns handle
Parameters:
link Private descriptor for pipe/socket.
buf Buffer to read into, must include size for kuc_hdr
maxsize Maximum message size allowed
transport Only listen to messages on this transport (and the generic transport)
Definition at line 109 of file liblustreapi_kernelconn.c.
References KUC_MAGIC, kuc_hdr::kuc_magic, kuc_hdr::kuc_msglen, kuc_hdr::kuc_transport, KUC_TRANSPORT_GENERIC, lhsz, lustre_kernelcomm::lk_rfd, llapi_err_noerrno, and LLAPI_MSG_ERROR.
Referenced by llapi_changelog_recv(), and llapi_hsm_copytool_recv().
int libcfs_ukuc_start (struct lustre_kernelcomm * link, int group, int rfd_flags)
Start the userspace side of a KUC pipe.
Parameters:
link Private descriptor for pipe/socket.
groups KUC broadcast group to listen to (can be null for unicast to this pid)
rfd_flags flags for read side of pipe (e.g. O_NONBLOCK)
Definition at line 52 of file liblustreapi_kernelconn.c.
References lustre_kernelcomm::lk_group, LK_NOFD, lustre_kernelcomm::lk_rfd, lustre_kernelcomm::lk_uid, and lustre_kernelcomm::lk_wfd.
Referenced by llapi_changelog_start(), and llapi_hsm_copytool_register().
int libcfs_ukuc_stop (struct lustre_kernelcomm * link)
Definition at line 78 of file liblustreapi_kernelconn.c.
References LK_NOFD, lustre_kernelcomm::lk_rfd, and lustre_kernelcomm::lk_wfd.
Referenced by llapi_changelog_fini(), llapi_hsm_copytool_register(), and llapi_hsm_copytool_unregister().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.