Lustre: lustre/utils/liblustreapi_param.c File Reference
lustre/utils/liblustreapi_param.c File Reference
#include <errno.h>
#include <stdint.h>
#include <libcfs/util/param.h>
#include <lustre/lustre_user.h>
#include <lustre/lustreapi.h>
#include "lustreapi_internal.h"
Functions
int get_lustre_param_path (const char *obd_type, const char *filter, enum param_filter type, const char *param_name, glob_t *param)
return the parameter's path for a specific device type or mountpoint
int get_lustre_param_value (const char *obd_type, const char *filter, enum param_filter type, const char *param_name, char *value, size_t val_len)
return a parameter of a single line value for a specific device type or mountpoint
Function Documentation
int get_lustre_param_path (const char * obd_type, const char * filter, enum param_filter type, const char * param_name, glob_t * param)
return the parameter's path for a specific device type or mountpoint
Parameters:
param the results returned to the caller
obd_type Lustre OBD device type
filter filter combined with the type agrument allow the
type caller to limit the scope of the search for the parameter's path. Typical options are search by Lustre filesystem name or by the path to a file or directory in the filesystem.
param_name parameter name to fetch
Using filter and the type argument we can limit the scope of the search to either the parameter belonging to a specific lustre filesystem (if it exists) or using a given file or directory path located on a mounted Lustre filesystem. The last case it can do is a special search based on exactly what the user passed instead of scanning file paths or specific file systems.
If "obd_type" matches a Lustre device then the first matching device (as with "lctl dl", constrained by
Parameters:
filter and
type) will be used to provide the return value, otherwise the first such device found will be used.
Return 0 for success, with the results stored in
Parameters:
param. Return -ve value for error.
Definition at line 63 of file liblustreapi_param.c.
References cfs_get_param_paths(), FILTER_BY_FS_NAME, FILTER_BY_PATH, llapi_error(), LLAPI_MSG_ERROR, and llapi_search_fsname().
Referenced by get_lustre_param_value(), llapi_get_target_uuids(), llapi_search_ost(), poolpath(), and setup_obd_uuid().
int get_lustre_param_value (const char * obd_type, const char * filter, enum param_filter type, const char * param_name, char * value, size_t val_len)
return a parameter of a single line value for a specific device type or mountpoint
Parameters:
obd_type Lustre OBD device type
filter filter combined with the type agruments allow the
type caller to limit the scope of the search for the parameter's path. Typical options are search by Lustre filesystem name or by the path to a file or directory in the filesystem.
param_name parameter name to fetch
value return buffer for parameter value string
val_len size of buffer for return value
Using filter and the type argument we can limit the scope of the search to either the parameter belonging to a specific lustre filesystem (if it exists) or using a given file or directory path located on a mounted Lustre filesystem. The last case it can do is a special search based on exactly what the user passed instead of scanning file paths or specific file systems.
If "obd_type" matches a Lustre device then the first matching device (as with "lctl dl", constrained by
Parameters:
filter and
type) will be used to provide the return value, otherwise the first such device found will be used.
Return 0 for success, with a NUL-terminated string in
Parameters:
value. Return negative errno value for error.
Definition at line 146 of file liblustreapi_param.c.
References cfs_free_param_data(), get_lustre_param_path(), llapi_error(), and LLAPI_MSG_ERROR.
Referenced by get_mds_md_size(), get_param_lmv(), get_param_lov(), llapi_poollist(), and sattr_get_defaults().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.