Lustre: lustre/utils/liblustreapi_hsm.c File Reference
lustre/utils/liblustreapi_hsm.c File Reference
#include <fcntl.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <stddef.h>
#include <sys/ioctl.h>
#include <unistd.h>
#include <malloc.h>
#include <errno.h>
#include <dirent.h>
#include <stdarg.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/types.h>
#include <time.h>
#include <utime.h>
#include <sys/syscall.h>
#include <fnmatch.h>
#include <signal.h>
#include <lnet/lnetctl.h>
#include <lustre/lustre_idl.h>
#include <lustre/lustreapi.h>
#include "lustreapi_internal.h"
Data Structures
struct hsm_copytool_private
struct hsm_copyaction_private
Defines
#define OPEN_BY_FID_PATH dot_lustre_name"/fid"
#define CT_PRIV_MAGIC 0xC0BE2001
#define CP_PRIV_MAGIC 0x19880429
Enumerations
enum ct_progress_type {
CT_START = 0, CT_RUNNING = 50, CT_FINISH = 100, CT_CANCEL = 150,
CT_ERROR = 175
}
enum ct_event {
CT_REGISTER = 1, CT_UNREGISTER = 2, CT_ARCHIVE_START = HSMA_ARCHIVE, CT_ARCHIVE_RUNNING = HSMA_ARCHIVE + CT_RUNNING,
CT_ARCHIVE_FINISH = HSMA_ARCHIVE + CT_FINISH, CT_ARCHIVE_CANCEL = HSMA_ARCHIVE + CT_CANCEL, CT_ARCHIVE_ERROR = HSMA_ARCHIVE + CT_ERROR, CT_RESTORE_START = HSMA_RESTORE,
CT_RESTORE_RUNNING = HSMA_RESTORE + CT_RUNNING, CT_RESTORE_FINISH = HSMA_RESTORE + CT_FINISH, CT_RESTORE_CANCEL = HSMA_RESTORE + CT_CANCEL, CT_RESTORE_ERROR = HSMA_RESTORE + CT_ERROR,
CT_REMOVE_START = HSMA_REMOVE, CT_REMOVE_RUNNING = HSMA_REMOVE + CT_RUNNING, CT_REMOVE_FINISH = HSMA_REMOVE + CT_FINISH, CT_REMOVE_CANCEL = HSMA_REMOVE + CT_CANCEL,
CT_REMOVE_ERROR = HSMA_REMOVE + CT_ERROR, CT_EVENT_MAX
}
Functions
static const char * llapi_hsm_ct_ev2str (int type)
static int llapi_hsm_write_json_event (struct llapi_json_item_list **event)
Writes a JSON event to the monitor FIFO.
static int llapi_hsm_log_ct_registration (struct hsm_copytool_private **priv, __u32 event_type)
Hook for llapi_hsm_copytool_register and llapi_hsm_copytool_unregister to generate JSON events suitable for consumption by a copytool monitoring process.
static int llapi_hsm_log_ct_progress (struct hsm_copyaction_private **phcp, const struct hsm_action_item *hai, __u32 progress_type, __u64 total, __u64 current)
Given a copytool progress update, construct a JSON event suitable for consumption by a copytool monitoring process.
int llapi_hsm_register_event_fifo (const char *path)
Given a path to a FIFO, create a filehandle for nonblocking writes to it.
int llapi_hsm_unregister_event_fifo (const char *path)
Given a path to a FIFO, close its filehandle and delete the FIFO.
void llapi_hsm_log_error (enum llapi_message_level level, int _rc, const char *fmt, va_list args)
Custom logging callback to be used when a monitoring FIFO has been registered.
int llapi_hsm_copytool_register (struct hsm_copytool_private **priv, const char *mnt, int archive_count, int *archives, int rfd_flags)
Register a copytool.
int llapi_hsm_copytool_unregister (struct hsm_copytool_private **priv)
Deregister a copytool Note: under Linux, until llapi_hsm_copytool_unregister is called (or the program is killed), the libcfs module will be referenced and unremovable, even after Lustre services stop.
int llapi_hsm_copytool_get_fd (struct hsm_copytool_private *ct)
Returns a file descriptor to poll/select on.
int llapi_hsm_copytool_recv (struct hsm_copytool_private *ct, struct hsm_action_list **halh, int *msgsize)
Wait for the next hsm_action_list.
static int fid_parent (const char *mnt, const lustre_fid *fid, char *parent, size_t parent_len)
Get parent path from mount point and fid.
static int ct_open_by_fid (const struct hsm_copytool_private *ct, const struct lu_fid *fid, int open_flags)
static int ct_md_getattr (const struct hsm_copytool_private *ct, const struct lu_fid *fid, lstat_t *st)
Get metadata attributes of file by FID.
static int create_restore_volatile (struct hsm_copyaction_private *hcp, int mdt_index, int open_flags)
Create the destination volatile file for a restore operation.
int llapi_hsm_action_begin (struct hsm_copyaction_private **phcp, const struct hsm_copytool_private *ct, const struct hsm_action_item *hai, int restore_mdt_index, int restore_open_flags, bool is_error)
Start processing an HSM action.
int llapi_hsm_action_end (struct hsm_copyaction_private **phcp, const struct hsm_extent *he, int hp_flags, int errval)
Terminate an HSM action processing.
int llapi_hsm_action_progress (struct hsm_copyaction_private *hcp, const struct hsm_extent *he, __u64 total, int hp_flags)
Notify a progress in processing an HSM action.
int llapi_hsm_action_get_dfid (const struct hsm_copyaction_private *hcp, lustre_fid *fid)
Get the fid of object to be used for copying data.
int llapi_hsm_action_get_fd (const struct hsm_copyaction_private *hcp)
Get a file descriptor to be used for copying data.
int llapi_hsm_import (const char *dst, int archive, const struct stat *st, unsigned long long stripe_size, int stripe_offset, int stripe_count, int stripe_pattern, char *pool_name, lustre_fid *newfid)
Import an existing hsm-archived file into Lustre.
int llapi_hsm_state_get_fd (int fd, struct hsm_user_state *hus)
Return the current HSM states and HSM requests related to file pointed by path.
int llapi_hsm_state_get (const char *path, struct hsm_user_state *hus)
Return the current HSM states and HSM requests related to file pointed by path.
int llapi_hsm_state_set_fd (int fd, __u64 setmask, __u64 clearmask, __u32 archive_id)
Set HSM states of file pointed by fd.
int llapi_hsm_state_set (const char *path, __u64 setmask, __u64 clearmask, __u32 archive_id)
Set HSM states of file pointed by path.
int llapi_hsm_current_action (const char *path, struct hsm_current_action *hca)
Return the current HSM request related to file pointed by path.
struct hsm_user_request * llapi_hsm_user_request_alloc (int itemcount, int data_len)
Allocate a hsm_user_request with the specified carateristics.
int llapi_hsm_request (const char *path, const struct hsm_user_request *request)
Send a HSM request to Lustre, described in.
Variables
static int llapi_hsm_event_fd = -1
static bool created_hsm_event_fifo
Define Documentation
#define CP_PRIV_MAGIC 0x19880429
Definition at line 79 of file liblustreapi_hsm.c.
Referenced by llapi_hsm_action_begin(), llapi_hsm_action_end(), llapi_hsm_action_get_dfid(), llapi_hsm_action_get_fd(), and llapi_hsm_action_progress().
#define CT_PRIV_MAGIC 0xC0BE2001
Definition at line 68 of file liblustreapi_hsm.c.
Referenced by llapi_hsm_copytool_get_fd(), llapi_hsm_copytool_recv(), llapi_hsm_copytool_register(), llapi_hsm_copytool_unregister(), and llapi_hsm_log_ct_registration().
#define OPEN_BY_FID_PATH dot_lustre_name"/fid"
Definition at line 65 of file liblustreapi_hsm.c.
Referenced by llapi_hsm_copytool_register().
Enumeration Type Documentation
enum ct_event
Enumerator:
CT_REGISTER
CT_UNREGISTER
CT_ARCHIVE_START
CT_ARCHIVE_RUNNING
CT_ARCHIVE_FINISH
CT_ARCHIVE_CANCEL
CT_ARCHIVE_ERROR
CT_RESTORE_START
CT_RESTORE_RUNNING
CT_RESTORE_FINISH
CT_RESTORE_CANCEL
CT_RESTORE_ERROR
CT_REMOVE_START
CT_REMOVE_RUNNING
CT_REMOVE_FINISH
CT_REMOVE_CANCEL
CT_REMOVE_ERROR
CT_EVENT_MAX
Definition at line 96 of file liblustreapi_hsm.c.
enum ct_progress_type
Enumerator:
CT_START
CT_RUNNING
CT_FINISH
CT_CANCEL
CT_ERROR
Definition at line 88 of file liblustreapi_hsm.c.
Function Documentation
static int create_restore_volatile (struct hsm_copyaction_private * hcp, int mdt_index, int open_flags) [static]
Create the destination volatile file for a restore operation.
Parameters:
hcp Private copyaction handle.
mdt_index MDT index where to create the volatile file.
flags Volatile file creation flags.
Returns:
0 on success.
Definition at line 1037 of file liblustreapi_hsm.c.
References hsm_copyaction_private::copy, hsm_copyaction_private::ct_priv, hsm_copyaction_private::data_fd, DFID, fid_parent(), hsm_action_item::hai_dfid, hsm_action_item::hai_fid, hsm_copy::hc_hai, llapi_create_volatile_idx(), llapi_error(), llapi_fd2fid(), LLAPI_MSG_ERROR, hsm_copytool_private::mnt, PFID, and hsm_copyaction_private::stat.
Referenced by llapi_hsm_action_begin().
static int ct_md_getattr (const struct hsm_copytool_private * ct, const struct lu_fid * fid, lstat_t * st) [static]
Get metadata attributes of file by FID.
Use the IOC_MDC_GETFILEINFO ioctl (to send a MDS_GETATTR_NAME RPC) to get the attributes of the file identified by fid. This returns only the attributes stored on the MDT and avoids taking layout locks or accessing OST objects. It also bypasses the inode cache. Attributes are returned in st.
Definition at line 991 of file liblustreapi_hsm.c.
References DFID, DFID_NOBRACE, FID_NOBRACE_LEN, IOC_MDC_GETFILEINFO, llapi_error(), LLAPI_MSG_ERROR, LOV_MAX_STRIPE_COUNT, LOV_USER_MAGIC_V3, lov_user_md_size(), hsm_copytool_private::mnt, hsm_copytool_private::open_by_fid_fd, and PFID.
Referenced by llapi_hsm_action_begin().
static int ct_open_by_fid (const struct hsm_copytool_private * ct, const struct lu_fid * fid, int open_flags) [static]
Definition at line 970 of file liblustreapi_hsm.c.
References DFID_NOBRACE, FID_NOBRACE_LEN, hsm_copytool_private::open_by_fid_fd, and PFID.
Referenced by llapi_hsm_action_get_fd().
static int fid_parent (const char * mnt, const lustre_fid * fid, char * parent, size_t parent_len) [static]
Get parent path from mount point and fid.
Parameters:
mnt Filesystem root path.
fid Object FID.
parent Destination buffer.
parent_len Destination buffer size.
Returns:
0 on success.
Definition at line 936 of file liblustreapi_hsm.c.
References DFID_NOBRACE, FID_NOBRACE_LEN, llapi_fid2path(), and PFID.
Referenced by create_restore_volatile().
static const char* llapi_hsm_ct_ev2str (int type) [inline, static]
Definition at line 121 of file liblustreapi_hsm.c.
References CT_ARCHIVE_CANCEL, CT_ARCHIVE_ERROR, CT_ARCHIVE_FINISH, CT_ARCHIVE_RUNNING, CT_ARCHIVE_START, CT_REGISTER, CT_REMOVE_CANCEL, CT_REMOVE_ERROR, CT_REMOVE_FINISH, CT_REMOVE_RUNNING, CT_REMOVE_START, CT_RESTORE_CANCEL, CT_RESTORE_ERROR, CT_RESTORE_FINISH, CT_RESTORE_RUNNING, CT_RESTORE_START, CT_UNREGISTER, llapi_err_noerrno, and LLAPI_MSG_ERROR.
Referenced by llapi_hsm_log_ct_progress(), and llapi_hsm_log_ct_registration().
static int llapi_hsm_log_ct_progress (struct hsm_copyaction_private ** phcp, const struct hsm_action_item * hai, __u32 progress_type, __u64 total, __u64 current) [static]
Given a copytool progress update, construct a JSON event suitable for consumption by a copytool monitoring process.
Examples of various events generated here and written by llapi_hsm_write_json_event:
Copytool registration and deregistration: {"event_time": "2014-02-26 14:58:01 -0500", "event_type": "REGISTER", "archive": 0, "mount_point": "/mnt/lustre", "uuid": "80379a60-1f8a-743f-daf2-307cde793ec2"} {"event_time": "2014-02-26 14:58:01 -0500", "event_type": "UNREGISTER", "archive": 0, "mount_point": "/mnt/lustre", "uuid": "80379a60-1f8a-743f-daf2-307cde793ec2"}
An archive action, start to completion: {"event_time": "2014-02-26 14:50:13 -0500", "event_type": "ARCHIVE_START", "total_bytes": 0, "lustre_path": "d71.sanity-hsm/f71.sanity-hsm", "source_fid": "0x2000013a1:0x2:0x0", "data_fid": "0x2000013a1:0x2:0x0"} {"event_time": "2014-02-26 14:50:18 -0500", "event_type": "ARCHIVE_RUNNING", "current_bytes": 5242880, "total_bytes": 39000000, "lustre_path": "d71.sanity-hsm/f71.sanity-hsm", "source_fid": "0x2000013a1:0x2:0x0", "data_fid": "0x2000013a1:0x2:0x0"} {"event_time": "2014-02-26 14:50:50 -0500", "event_type": "ARCHIVE_FINISH", "source_fid": "0x2000013a1:0x2:0x0", "data_fid": "0x2000013a1:0x2:0x0"}
A log message: {"event_time": "2014-02-26 14:50:13 -0500", "event_type": "LOGGED_MESSAGE", "level": "INFO", "message": "lhsmtool_posix[42]: copytool fs=lustre archive#=2 item_count=1"}
Parameters:
hcp Opaque action handle returned by llapi_hsm_action_start.
hai The hsm_action_item describing the request.
progress_type The ct_progress_type describing the update.
total The total expected bytes for the request.
current The current copied byte count for the request.
Return values:
0 on success.
-errno on error.
Definition at line 352 of file liblustreapi_hsm.c.
References hsm_copyaction_private::copy, CT_CANCEL, CT_ERROR, CT_FINISH, hsm_copyaction_private::ct_priv, CT_RUNNING, DFID_NOBRACE, FID_NOBRACE_LEN, hsm_action_item::hai_action, hsm_action_item::hai_dfid, hsm_action_item::hai_fid, hsm_copy::hc_errval, llapi_error(), llapi_fid2path(), llapi_hsm_ct_ev2str(), llapi_hsm_event_fd, llapi_hsm_write_json_event(), llapi_json_add_item(), LLAPI_JSON_BIGNUM, llapi_json_destroy_list(), llapi_json_init_list(), LLAPI_JSON_INTEGER, LLAPI_JSON_STRING, LLAPI_MSG_ERROR, lustre_path, hsm_copytool_private::mnt, and PFID.
Referenced by llapi_hsm_action_begin(), llapi_hsm_action_end(), and llapi_hsm_action_progress().
static int llapi_hsm_log_ct_registration (struct hsm_copytool_private ** priv, __u32 event_type) [static]
Hook for llapi_hsm_copytool_register and llapi_hsm_copytool_unregister to generate JSON events suitable for consumption by a copytool monitoring process.
Parameters:
priv Opaque private control structure.
event_type The type of event (register or unregister).
Return values:
0 on success.
-errno on error.
Definition at line 243 of file liblustreapi_hsm.c.
References hsm_copytool_private::archives, CT_PRIV_MAGIC, CT_REGISTER, CT_UNREGISTER, llapi_chomp_string(), llapi_error(), llapi_get_agent_uuid(), llapi_hsm_ct_ev2str(), llapi_hsm_event_fd, llapi_hsm_write_json_event(), llapi_json_add_item(), llapi_json_destroy_list(), llapi_json_init_list(), LLAPI_JSON_INTEGER, LLAPI_JSON_STRING, LLAPI_MSG_ERROR, hsm_copytool_private::magic, hsm_copytool_private::mnt, and UUID_MAX.
Referenced by llapi_hsm_copytool_register(), and llapi_hsm_copytool_unregister().
static int llapi_hsm_write_json_event (struct llapi_json_item_list ** event) [static]
Writes a JSON event to the monitor FIFO.
Noop if no FIFO has been registered.
Parameters:
event A list of llapi_json_items comprising a single JSON-formatted event.
Return values:
0 on success.
-errno on error.
Definition at line 175 of file liblustreapi_hsm.c.
References llapi_error(), llapi_hsm_event_fd, llapi_json_add_item(), LLAPI_JSON_STRING, llapi_json_write_list(), and LLAPI_MSG_ERROR.
Referenced by llapi_hsm_log_ct_progress(), llapi_hsm_log_ct_registration(), and llapi_hsm_log_error().
Variable Documentation
bool created_hsm_event_fifo [static]
Definition at line 119 of file liblustreapi_hsm.c.
Referenced by llapi_hsm_register_event_fifo(), and llapi_hsm_unregister_event_fifo().
int llapi_hsm_event_fd = -1 [static]
Definition at line 118 of file liblustreapi_hsm.c.
Referenced by llapi_hsm_log_ct_progress(), llapi_hsm_log_ct_registration(), llapi_hsm_log_error(), llapi_hsm_register_event_fifo(), llapi_hsm_unregister_event_fifo(), and llapi_hsm_write_json_event().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.