Lustre: lustre/utils/liblustreapi.c File Reference
lustre/utils/liblustreapi.c File Reference
#include <mntent.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <stddef.h>
#include <sys/ioctl.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <dirent.h>
#include <stdarg.h>
#include <sys/stat.h>
#include <sys/statfs.h>
#include <sys/syscall.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/xattr.h>
#include <time.h>
#include <fnmatch.h>
#include <libgen.h>
#include <poll.h>
#include <libcfs/util/param.h>
#include <lnet/lnetctl.h>
#include <lustre/lustreapi.h>
#include <lustre_ioctl.h>
#include "lustreapi_internal.h"
#include <pwd.h>
#include <grp.h>
#include <sys/wait.h>
#include <ctype.h>
Data Structures
struct rmtacl_name_t
struct changelog_private
Defines
#define OBD_NOT_FOUND (-1)
#define MAX_STRING_SIZE 128
#define RMTACL_OPTNAME(name) name, sizeof(name) - 1
#define CHANGELOG_PRIV_MAGIC 0xCA8E1080
#define DEFAULT_RECORD_FMT (CLF_VERSION | CLF_RENAME)
Convert all records to a same format according to the caller's wishes.
Typedefs
typedef int(semantic_func_t)(char *path, DIR *parent, DIR **d, void *data, struct dirent64 *de)
Enumerations
enum tgt_type { LOV_TYPE = 1, LMV_TYPE }
Functions
void llapi_msg_set_level (int level)
int llapi_msg_get_level (void)
static void error_callback_default (enum llapi_message_level level, int err, const char *fmt, va_list ap)
static void info_callback_default (enum llapi_message_level level, int err, const char *fmt, va_list ap)
void llapi_error (enum llapi_message_level level, int err, const char *fmt,...)
void llapi_printf (enum llapi_message_level level, const char *fmt,...)
llapi_log_callback_t llapi_error_callback_set (llapi_log_callback_t cb)
Set a custom error logging function.
llapi_log_callback_t llapi_info_callback_set (llapi_log_callback_t cb)
Set a custom info logging function.
int llapi_parse_size (const char *optarg, unsigned long long *size, unsigned long long *size_units, int bytes_spec)
size_units is to be initialized (or zeroed) by caller.
int llapi_stripe_limit_check (unsigned long long stripe_size, int stripe_offset, int stripe_count, int stripe_pattern)
int llapi_chomp_string (char *buf)
static int get_param_lov (const char *path, const char *param, char *buf, size_t buf_size)
static int get_param_lmv (const char *path, const char *param, char *buf, size_t buf_size)
static int get_mds_md_size (const char *path)
int llapi_get_agent_uuid (char *path, char *buf, size_t bufsize)
int llapi_search_ost (char *fsname, char *poolname, char *ostname)
int llapi_file_open_param (const char *name, int flags, mode_t mode, const struct llapi_stripe_param *param)
Open a Lustre file.
int llapi_file_open_pool (const char *name, int flags, int mode, unsigned long long stripe_size, int stripe_offset, int stripe_count, int stripe_pattern, char *pool_name)
int llapi_file_open (const char *name, int flags, int mode, unsigned long long stripe_size, int stripe_offset, int stripe_count, int stripe_pattern)
int llapi_file_create (const char *name, unsigned long long stripe_size, int stripe_offset, int stripe_count, int stripe_pattern)
int llapi_file_create_pool (const char *name, unsigned long long stripe_size, int stripe_offset, int stripe_count, int stripe_pattern, char *pool_name)
int llapi_dir_set_default_lmv_stripe (const char *name, int stripe_offset, int stripe_count, int stripe_pattern, const char *pool_name)
int llapi_dir_create_pool (const char *name, int mode, int stripe_offset, int stripe_count, int stripe_pattern, const char *pool_name)
int llapi_direntry_remove (char *dname)
int get_root_path (int want, char *fsname, int *outfd, char *path, int index)
int llapi_search_mounts (const char *pathname, int index, char *mntdir, char *fsname)
int llapi_search_fsname (const char *pathname, char *fsname)
int llapi_search_rootpath (char *pathname, const char *fsname)
int llapi_getname (const char *path, char *buf, size_t size)
int llapi_get_poolmembers (const char *poolname, char **members, int list_size, char *buffer, int buffer_size)
Get the list of pool members.
int llapi_get_poollist (const char *name, char **poollist, int list_size, char *buffer, int buffer_size)
Get the list of pools in a filesystem.
int llapi_poollist (const char *name)
static int common_param_init (struct find_param *param, char *path)
static void find_param_fini (struct find_param *param)
static int cb_common_fini (char *path, DIR *parent, DIR **dirp, void *data, struct dirent64 *de)
static DIR * opendir_parent (const char *path)
static int cb_get_dirstripe (char *path, DIR *d, struct find_param *param)
static int get_lmd_info (char *path, DIR *parent, DIR *dir, struct lov_user_mds_data *lmd, int lumlen)
static int llapi_semantic_traverse (char *path, int size, DIR *parent, semantic_func_t sem_init, semantic_func_t sem_fini, void *data, struct dirent64 *de)
static int param_callback (char *path, semantic_func_t sem_init, semantic_func_t sem_fini, struct find_param *param)
int llapi_file_fget_lov_uuid (int fd, struct obd_uuid *lov_name)
int llapi_file_fget_lmv_uuid (int fd, struct obd_uuid *lov_name)
int llapi_file_get_lov_uuid (const char *path, struct obd_uuid *lov_uuid)
int llapi_file_get_lmv_uuid (const char *path, struct obd_uuid *lov_uuid)
static int llapi_get_target_uuids (int fd, struct obd_uuid *uuidp, int *ost_count, enum tgt_type type)
int llapi_lov_get_uuids (int fd, struct obd_uuid *uuidp, int *ost_count)
int llapi_get_obd_count (char *mnt, int *count, int is_mdt)
int llapi_uuid_match (char *real_uuid, char *search_uuid)
static int setup_obd_uuid (DIR *dir, char *dname, struct find_param *param)
static int setup_indexes (DIR *dir, char *path, struct obd_uuid *obduuids, int num_obds, int **obdindexes, int *obdindex, enum tgt_type type)
static int setup_target_indexes (DIR *dir, char *path, struct find_param *param)
int llapi_ostlist (char *path, struct find_param *param)
static int sattr_get_defaults (const char *const fsname, unsigned int *scount, unsigned int *ssize, unsigned int *soffset)
static int sattr_cache_get_defaults (const char *const fsname, const char *const pathname, unsigned int *scount, unsigned int *ssize, unsigned int *soffset)
static void lov_dump_user_lmm_header (struct lov_user_md *lum, char *path, struct lov_user_ost_data_v1 *objects, int is_dir, int verbose, int depth, int raw, char *pool_name)
void lov_dump_user_lmm_v1v3 (struct lov_user_md *lum, char *pool_name, struct lov_user_ost_data_v1 *objects, char *path, int is_dir, int obdindex, int depth, int header, int raw)
void lmv_dump_user_lmm (struct lmv_user_md *lum, char *pool_name, char *path, int obdindex, int depth, int verbose)
void llapi_lov_dump_user_lmm (struct find_param *param, char *path, int is_dir)
int llapi_file_get_stripe (const char *path, struct lov_user_md *lum)
int llapi_file_lookup (int dirfd, const char *name)
static int find_value_cmp (unsigned long long file, unsigned long long limit, int sign, int negopt, unsigned long long margin, int mds)
static int find_time_check (lstat_t *st, struct find_param *param, int mds)
static int check_obd_match (struct find_param *param)
Check whether the stripes matches the indexes user provided 1 : matched 0 : Unmatched.
static int check_mdt_match (struct find_param *param)
static int print_failed_tgt (struct find_param *param, char *path, int type)
Check whether the obd is active or not, if it is not active, just print the object affected by this failed target.
static int cb_find_init (char *path, DIR *parent, DIR **dirp, void *data, struct dirent64 *de)
static int cb_migrate_mdt_init (char *path, DIR *parent, DIR **dirp, void *param_data, struct dirent64 *de)
int llapi_migrate_mdt (char *path, struct find_param *param)
int llapi_mv (char *path, struct find_param *param)
int llapi_find (char *path, struct find_param *param)
int llapi_file_fget_mdtidx (int fd, int *mdtidx)
static int cb_get_mdt_index (char *path, DIR *parent, DIR **dirp, void *data, struct dirent64 *de)
static int cb_getstripe (char *path, DIR *parent, DIR **dirp, void *data, struct dirent64 *de)
int llapi_getstripe (char *path, struct find_param *param)
int llapi_obd_statfs (char *path, __u32 type, __u32 index, struct obd_statfs *stat_buf, struct obd_uuid *uuid_buf)
int llapi_ping (char *obd_type, char *obd_name)
int llapi_target_iterate (int type_num, char **obd_type, void *args, llapi_cb_t cb)
static void do_target_check (char *obd_type_name, char *obd_name, char *obd_uuid, void *args)
int llapi_target_check (int type_num, char **obd_type, char *dir)
int llapi_is_lustre_mnttype (const char *type)
int llapi_is_lustre_mnt (struct mntent *mnt)
int llapi_quotactl (char *mnt, struct if_quotactl *qctl)
static int rmtacl_notify (int ops)
static char * next_token (char *p, int div)
static int rmtacl_name2id (char *name, int is_user)
static int isodigit (int c)
static int str_is_id (char *str)
static int rgetfacl_output (char *str)
static int child_status (int status)
static int do_rmtacl (int argc, char *argv[], int ops, int(output_func)(char *))
int llapi_lsetfacl (int argc, char *argv[])
int llapi_lgetfacl (int argc, char *argv[])
int llapi_rsetfacl (int argc, char *argv[])
int llapi_rgetfacl (int argc, char *argv[])
int llapi_cp (int argc, char *argv[])
int llapi_ls (int argc, char *argv[])
static int get_mdtname (char *name, char *format, char *buf)
int root_ioctl (const char *mdtname, int opc, void *data, int *mdtidxp, int want_error)
ioctl on filsystem root, with mdtindex sent as data
static int changelog_ioctl (const char *mdtname, int opc, int id, long long recno, int flags)
int llapi_changelog_start (void **priv, enum changelog_send_flag flags, const char *device, long long startrec)
Start reading from a changelog.
int llapi_changelog_fini (void **priv)
Finish reading from a changelog.
int llapi_changelog_recv (void *priv, struct changelog_rec **rech)
int llapi_changelog_free (struct changelog_rec **rech)
Release the changelog record when done with it.
int llapi_changelog_clear (const char *mdtname, const char *idstr, long long endrec)
int llapi_fid2path (const char *device, const char *fidstr, char *buf, int buflen, long long *recno, int *linkno)
static int fid_from_lma (const char *path, const int fd, lustre_fid *fid)
int llapi_get_mdt_index_by_fid (int fd, const lustre_fid *fid, int *mdt_index)
int llapi_fd2fid (const int fd, lustre_fid *fid)
int llapi_path2fid (const char *path, lustre_fid *fid)
int llapi_fd2parent (int fd, unsigned int linkno, lustre_fid *parent_fid, char *name, size_t name_size)
int llapi_path2parent (const char *path, unsigned int linkno, lustre_fid *parent_fid, char *name, size_t name_size)
int llapi_get_connect_flags (const char *mnt, __u64 *flags)
int llapi_get_version (char *buffer, int buffer_size, char **version)
int llapi_get_data_version (int fd, __u64 *data_version, __u64 flags)
Get a 64-bit value representing the version of file data pointed by fd.
int llapi_create_volatile_idx (char *directory, int idx, int open_flags)
int llapi_fswap_layouts_grouplock (int fd1, int fd2, __u64 dv1, __u64 dv2, int gid, __u64 flags)
Swap the layouts between 2 file descriptors the 2 files must be open for writing first fd received the ioctl, second fd is passed as arg this is assymetric but avoid use of root path for ioctl.
int llapi_fswap_layouts (int fd1, int fd2, __u64 dv1, __u64 dv2, __u64 flags)
int llapi_swap_layouts (const char *path1, const char *path2, __u64 dv1, __u64 dv2, __u64 flags)
Swap the layouts between 2 files the 2 files are open in write.
int llapi_open_by_fid (const char *lustre_dir, const lustre_fid *fid, int flags)
Attempt to open a file with Lustre file identifier fid and return an open file descriptor.
int llapi_group_lock (int fd, int gid)
Take group lock.
int llapi_group_unlock (int fd, int gid)
Put group lock.
Variables
static int llapi_msg_level = LLAPI_MSG_MAX
static llapi_log_callback_t llapi_error_callback = error_callback_default
static llapi_log_callback_t llapi_info_callback = info_callback_default
static rmtacl_name_t rmtacl_namelist []
Define Documentation
#define CHANGELOG_PRIV_MAGIC 0xCA8E1080
Definition at line 3924 of file liblustreapi.c.
Referenced by llapi_changelog_fini(), llapi_changelog_recv(), and llapi_changelog_start().
#define DEFAULT_RECORD_FMT (CLF_VERSION | CLF_RENAME)
Convert all records to a same format according to the caller's wishes.
Default is CLF_VERSION | CLF_RENAME. Add CLF_JOBID if explicitely requested.
Parameters:
rec The record to remap. It is expected to be big enough to properly handle the final format.
Returns:
1 if anything changed. 0 otherwise. Read the next changelog entry
Parameters:
priv Opaque private control structure
rech Changelog record handle; record will be allocated here
Returns:
0 valid message received; rec is set <0 error code 1 EOF
Definition at line 4017 of file liblustreapi.c.
Referenced by llapi_changelog_recv().
#define MAX_STRING_SIZE 128
Definition at line 3381 of file liblustreapi.c.
#define OBD_NOT_FOUND (-1)
Definition at line 1315 of file liblustreapi.c.
Referenced by cb_find_init(), check_mdt_match(), check_obd_match(), common_param_init(), lmv_dump_user_lmm(), lov_dump_user_lmm_v1v3(), setup_indexes(), and setup_obd_uuid().
#define RMTACL_OPTNAME (name) name, sizeof(name) - 1
Definition at line 3653 of file liblustreapi.c.
Typedef Documentation
typedef int(semantic_func_t)(char *path, DIR *parent, DIR **d, void *data, struct dirent64 *de)
Definition at line 1312 of file liblustreapi.c.
Enumeration Type Documentation
enum tgt_type
Enumerator:
LOV_TYPE
LMV_TYPE
Definition at line 1676 of file liblustreapi.c.
Function Documentation
static int cb_common_fini (char * path, DIR * parent, DIR ** dirp, void * data, struct dirent64 * de) [static]
Definition at line 1365 of file liblustreapi.c.
References find_param::fp_depth.
Referenced by llapi_find(), llapi_getstripe(), and llapi_migrate_mdt().
static int cb_find_init (char * path, DIR * parent, DIR ** dirp, void * data, struct dirent64 * de) [static]
Definition at line 2690 of file liblustreapi.c.
References check_mdt_match(), check_obd_match(), dir, DTTOIF, FID_SEQ_LOV_DEFAULT, find_time_check(), find_value_cmp(), fname, find_param::fp_atime, find_param::fp_check_gid, find_param::fp_check_layout, find_param::fp_check_pool, find_param::fp_check_size, find_param::fp_check_stripe_count, find_param::fp_check_stripe_size, find_param::fp_check_uid, find_param::fp_ctime, find_param::fp_depth, find_param::fp_dev, find_param::fp_exclude_gid, find_param::fp_exclude_layout, find_param::fp_exclude_pattern, find_param::fp_exclude_pool, find_param::fp_exclude_size, find_param::fp_exclude_stripe_count, find_param::fp_exclude_stripe_size, find_param::fp_exclude_type, find_param::fp_exclude_uid, find_param::fp_file_mdt_index, find_param::fp_gid, find_param::fp_got_uuids, find_param::fp_layout, find_param::fp_lmd, find_param::fp_lum_size, find_param::fp_max_depth, find_param::fp_mdt_index, find_param::fp_mdt_uuid, find_param::fp_mtime, find_param::fp_obd_index, find_param::fp_obd_uuid, find_param::fp_obds_printed, find_param::fp_pattern, find_param::fp_poolname, find_param::fp_raw, find_param::fp_size, find_param::fp_size_sign, find_param::fp_size_units, find_param::fp_stripe_count, find_param::fp_stripe_count_sign, find_param::fp_stripe_size, find_param::fp_stripe_size_sign, find_param::fp_stripe_size_units, find_param::fp_type, find_param::fp_uid, find_param::fp_zero_end, get_lmd_info(), LASSERT, LL_STATFS_LMV, LL_STATFS_LOV, llapi_error(), llapi_file_fget_mdtidx(), LLAPI_MSG_ERROR, LLAPI_MSG_NORMAL, llapi_printf(), lov_user_md_v3::lmm_pool_name, LOV_MAXPOOLNAME, LOV_USER_MAGIC_V1, LOV_USER_MAGIC_V3, lov_user_md, OBD_NOT_FOUND, ostid_set_seq(), print_failed_tgt(), ret, and setup_target_indexes().
Referenced by llapi_find().
static int cb_get_dirstripe (char * path, DIR * d, struct find_param * param) [static]
Definition at line 1392 of file liblustreapi.c.
References find_param::fp_get_default_lmv, find_param::fp_lmv_md, find_param::fp_lmv_stripe_count, LL_IOC_LMV_GETSTRIPE, llapi_error(), LLAPI_MSG_ERROR, LMV_MAGIC_V1, LMV_USER_MAGIC, lmv_user_md_size(), and ret.
Referenced by cb_getstripe().
static int cb_get_mdt_index (char * path, DIR * parent, DIR ** dirp, void * data, struct dirent64 * de) [static]
Definition at line 3148 of file liblustreapi.c.
References find_param::fp_depth, find_param::fp_max_depth, find_param::fp_obd_uuid, find_param::fp_quiet, find_param::fp_verbose, LASSERT, llapi_error(), llapi_file_fget_mdtidx(), LLAPI_MSG_ERROR, LLAPI_MSG_NORMAL, LLAPI_MSG_WARN, llapi_printf(), ret, and VERBOSE_DETAIL.
Referenced by llapi_getstripe().
static int cb_getstripe (char * path, DIR * parent, DIR ** dirp, void * data, struct dirent64 * de) [static]
Definition at line 3211 of file liblustreapi.c.
References cb_get_dirstripe(), FID_SEQ_LOV_DEFAULT, fname, find_param::fp_depth, find_param::fp_get_default_lmv, find_param::fp_get_lmv, find_param::fp_lmd, find_param::fp_lmv_md, find_param::fp_lum_size, find_param::fp_max_depth, find_param::fp_mdt_uuid, find_param::fp_obd_uuid, find_param::fp_quiet, find_param::fp_raw, find_param::fp_verbose, IOC_MDC_GETFILESTRIPE, LASSERT, LL_IOC_LOV_GETSTRIPE, llapi_error(), llapi_file_fget_mdtidx(), llapi_lov_dump_user_lmm(), LLAPI_MSG_ERROR, LLAPI_MSG_NORMAL, LLAPI_MSG_WARN, llapi_printf(), LMV_MAGIC_V1, LMV_USER_MAGIC, lmv_user_md, LOV_USER_MAGIC_V1, lov_user_md, ostid_set_seq(), ret, setup_obd_uuid(), strlcpy(), and VERBOSE_MDTINDEX.
Referenced by llapi_getstripe().
static int cb_migrate_mdt_init (char * path, DIR * parent, DIR ** dirp, void * param_data, struct dirent64 * de) [static]
Definition at line 3023 of file liblustreapi.c.
References filename, find_param::fp_mdt_index, find_param::fp_verbose, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf2, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, LASSERT, LL_IOC_MIGRATE, llapi_error(), LLAPI_MSG_ERROR, obd_ioctl_pack(), OBD_MAX_IOCTL_BUFFER, opendir_parent(), rawbuf, ret, and VERBOSE_DETAIL.
Referenced by llapi_migrate_mdt().
static int changelog_ioctl (const char * mdtname, int opc, int id, long long recno, int flags) [static]
Definition at line 3910 of file liblustreapi.c.
References ioc_changelog::icc_flags, ioc_changelog::icc_id, ioc_changelog::icc_mdtindex, ioc_changelog::icc_recno, root_ioctl(), and WANT_ERROR.
Referenced by llapi_changelog_clear(), and llapi_changelog_start().
static int check_mdt_match (struct find_param * param) [static]
Definition at line 2643 of file liblustreapi.c.
References find_param::fp_exclude_mdt, find_param::fp_file_mdt_index, find_param::fp_mdt_index, find_param::fp_mdt_indexes, find_param::fp_mdt_uuid, find_param::fp_num_mdts, and OBD_NOT_FOUND.
Referenced by cb_find_init().
static int check_obd_match (struct find_param * param) [static]
Check whether the stripes matches the indexes user provided 1 : matched 0 : Unmatched.
Definition at line 2596 of file liblustreapi.c.
References find_param::fp_exclude_obd, find_param::fp_lmd, find_param::fp_num_obds, find_param::fp_obd_index, find_param::fp_obd_indexes, find_param::fp_obd_uuid, lov_user_ost_data_v1::l_ost_idx, llapi_err_noerrno, LLAPI_MSG_ERROR, lov_user_md_v3::lmm_objects, LOV_USER_MAGIC_V1, LOV_USER_MAGIC_V3, and OBD_NOT_FOUND.
Referenced by cb_find_init().
static int child_status (int status) [static]
Definition at line 3714 of file liblustreapi.c.
Referenced by do_rmtacl(), and t4().
static int common_param_init (struct find_param * param, char * path) [static]
Definition at line 1317 of file liblustreapi.c.
References find_param::fp_got_uuids, find_param::fp_lmd, find_param::fp_lmv_md, find_param::fp_lmv_stripe_count, find_param::fp_lum_size, find_param::fp_mdt_index, find_param::fp_migrate, find_param::fp_obd_index, find_param::fp_obd_indexes, get_mds_md_size(), llapi_error(), LLAPI_MSG_ERROR, LMV_MAGIC_V1, lmv_user_md_size(), and OBD_NOT_FOUND.
Referenced by param_callback().
static int do_rmtacl (int argc, char * argv[], int ops, int(output_func)(char *)) [static]
Definition at line 3719 of file liblustreapi.c.
References buf, child_status(), llapi_error(), LLAPI_MSG_ERROR, rmtacl_notify(), and status.
Referenced by llapi_lgetfacl(), llapi_lsetfacl(), llapi_rgetfacl(), and llapi_rsetfacl().
static void do_target_check (char * obd_type_name, char * obd_name, char * obd_uuid, void * args) [static]
Definition at line 3467 of file liblustreapi.c.
References llapi_error(), LLAPI_MSG_ERROR, LLAPI_MSG_NORMAL, llapi_ping(), and llapi_printf().
Referenced by llapi_target_check().
static void error_callback_default (enum llapi_message_level level, int err, const char * fmt, va_list ap) [static]
Definition at line 100 of file liblustreapi.c.
References LLAPI_MSG_NO_ERRNO.
Referenced by llapi_error_callback_set().
static int fid_from_lma (const char * path, const int fd, lustre_fid * fid) [static]
Definition at line 4161 of file liblustreapi.c.
References buf, fid_le_to_cpu(), lustre_mdt_attrs::lma_self_fid, and XATTR_NAME_LMA.
Referenced by llapi_fd2fid(), and llapi_path2fid().
static void find_param_fini (struct find_param * param) [static]
Definition at line 1353 of file liblustreapi.c.
References find_param::fp_lmd, find_param::fp_lmv_md, and find_param::fp_obd_indexes.
Referenced by param_callback().
static int find_time_check (lstat_t * st, struct find_param * param, int mds) [static]
Definition at line 2547 of file liblustreapi.c.
References find_value_cmp(), find_param::fp_asign, find_param::fp_atime, find_param::fp_csign, find_param::fp_ctime, find_param::fp_exclude_atime, find_param::fp_exclude_ctime, find_param::fp_exclude_mtime, find_param::fp_msign, and find_param::fp_mtime.
Referenced by cb_find_init().
static int find_value_cmp (unsigned long long file, unsigned long long limit, int sign, int negopt, unsigned long long margin, int mds) [static]
Definition at line 2515 of file liblustreapi.c.
References ret.
Referenced by cb_find_init(), and find_time_check().
static int get_lmd_info (char * path, DIR * parent, DIR * dir, struct lov_user_mds_data * lmd, int lumlen) [static]
Definition at line 1428 of file liblustreapi.c.
References fname, IOC_MDC_GETFILEINFO, LL_IOC_MDC_GETINFO, llapi_error(), LLAPI_MSG_ERROR, LLAPI_MSG_WARN, ret, and strlcpy().
Referenced by cb_find_init(), and llapi_semantic_traverse().
static int get_mds_md_size (const char * path) [static]
Definition at line 353 of file liblustreapi.c.
References buf, FILTER_BY_EXACT, get_lustre_param_value(), llapi_getname(), LOV_MAX_STRIPE_COUNT, LOV_USER_MAGIC_V3, and lov_user_md_size().
Referenced by common_param_init().
static int get_mdtname (char * name, char * format, char * buf) [static]
Definition at line 3838 of file liblustreapi.c.
References llapi_err_noerrno, and LLAPI_MSG_ERROR.
Referenced by root_ioctl().
static int get_param_lmv (const char * path, const char * param, char * buf, size_t buf_size) [static]
Definition at line 339 of file liblustreapi.c.
References FILTER_BY_EXACT, get_lustre_param_value(), llapi_file_get_lmv_uuid(), and obd_uuid::uuid.
Referenced by llapi_get_agent_uuid(), and setup_indexes().
static int get_param_lov (const char * path, const char * param, char * buf, size_t buf_size) [static]
Definition at line 322 of file liblustreapi.c.
References FILTER_BY_EXACT, get_lustre_param_value(), llapi_file_get_lov_uuid(), and obd_uuid::uuid.
Referenced by setup_indexes().
int get_root_path (int want, char * fsname, int * outfd, char * path, int index)
Definition at line 848 of file liblustreapi.c.
References buf, llapi_err_noerrno, llapi_error(), llapi_is_lustre_mnt(), LLAPI_MSG_ERROR, PROC_MOUNTS, WANT_ERROR, WANT_FD, WANT_FSNAME, WANT_INDEX, and WANT_PATH.
Referenced by llapi_hsm_request(), llapi_search_fsname(), llapi_search_mounts(), llapi_search_rootpath(), and root_ioctl().
static void info_callback_default (enum llapi_message_level level, int err, const char * fmt, va_list ap) [static]
Definition at line 110 of file liblustreapi.c.
Referenced by llapi_info_callback_set().
static int isodigit (int c) [static]
Definition at line 3613 of file liblustreapi.c.
void llapi_error (enum llapi_message_level level, int err, const char * fmt, ...)
Definition at line 121 of file liblustreapi.c.
References llapi_error_callback, llapi_msg_level, and LLAPI_MSG_MASK.
int llapi_file_fget_lmv_uuid (int fd, struct obd_uuid * lov_name)
Definition at line 1632 of file liblustreapi.c.
References llapi_error(), LLAPI_MSG_ERROR, and OBD_IOC_GETMDNAME.
Referenced by llapi_file_get_lmv_uuid(), llapi_get_target_uuids(), and setup_obd_uuid().
static int llapi_get_target_uuids (int fd, struct obd_uuid * uuidp, int * ost_count, enum tgt_type type) [static]
Definition at line 1687 of file liblustreapi.c.
References buf, cfs_free_param_data(), FILTER_BY_EXACT, get_lustre_param_path(), llapi_error(), llapi_file_fget_lmv_uuid(), llapi_file_fget_lov_uuid(), LLAPI_MSG_ERROR, LOV_TYPE, uuid, and obd_uuid::uuid.
Referenced by llapi_lov_get_uuids(), and setup_indexes().
void llapi_lov_dump_user_lmm (struct find_param * param, char * path, int is_dir)
Definition at line 2371 of file liblustreapi.c.
References find_param::fp_get_default_lmv, find_param::fp_get_lmv, find_param::fp_lmd, find_param::fp_lmv_md, find_param::fp_max_depth, find_param::fp_obd_index, find_param::fp_raw, find_param::fp_verbose, LLAPI_MSG_NORMAL, llapi_printf(), lov_user_md_v3::lmm_objects, lov_user_md_v3::lmm_pool_name, lmv_dump_user_lmm(), LMV_MAGIC_V1, LMV_USER_MAGIC, lmv_user_md, lov_dump_user_lmm_v1v3(), LOV_MAXPOOLNAME, LOV_USER_MAGIC_V1, LOV_USER_MAGIC_V3, and strlcpy().
Referenced by cb_getstripe().
void llapi_printf (enum llapi_message_level level, const char * fmt, ...)
Definition at line 136 of file liblustreapi.c.
References llapi_info_callback, llapi_msg_level, and LLAPI_MSG_MASK.
static int llapi_semantic_traverse (char * path, int size, DIR * parent, semantic_func_t sem_init, semantic_func_t sem_fini, void * data, struct dirent64 * de) [static]
Definition at line 1486 of file liblustreapi.c.
References dot_lustre_name, find_param::fp_lmd, find_param::fp_lum_size, get_lmd_info(), IFTODT, llapi_err_noerrno, llapi_error(), LLAPI_MSG_ERROR, opendir_parent(), and ret.
Referenced by param_callback().
int llapi_stripe_limit_check (unsigned long long stripe_size, int stripe_offset, int stripe_count, int stripe_pattern)
Definition at line 257 of file liblustreapi.c.
References llapi_err_noerrno, llapi_error(), LLAPI_MSG_ERROR, LLAPI_MSG_WARN, llapi_stripe_count_is_valid(), llapi_stripe_index_is_valid(), llapi_stripe_size_is_aligned(), llapi_stripe_size_is_too_big(), LOV_MIN_STRIPE_SIZE, and page_size.
Referenced by llapi_file_open_param().
void lmv_dump_user_lmm (struct lmv_user_md * lum, char * pool_name, char * path, int obdindex, int depth, int verbose)
Definition at line 2278 of file liblustreapi.c.
References DFID, LLAPI_MSG_NORMAL, llapi_printf(), LMV_USER_MAGIC, lmv_user_mds_data::lum_fid, lmv_user_mds_data::lum_mds, OBD_NOT_FOUND, PFID, VERBOSE_COUNT, VERBOSE_OBJID, VERBOSE_OFFSET, and VERBOSE_POOL.
Referenced by llapi_lov_dump_user_lmm().
static void lov_dump_user_lmm_header (struct lov_user_md * lum, char * path, struct lov_user_ost_data_v1 * objects, int is_dir, int verbose, int depth, int raw, char * pool_name) [static]
Definition at line 2105 of file liblustreapi.c.
References FID_SEQ_LOV_DEFAULT, llapi_error(), LLAPI_MSG_ERROR, LLAPI_MSG_NORMAL, llapi_printf(), lmm_oi_id(), lmm_oi_seq(), lmm_oi_set_seq(), sattr_cache_get_defaults(), VERBOSE_COUNT, VERBOSE_DETAIL, VERBOSE_GENERATION, VERBOSE_LAYOUT, VERBOSE_OBJID, VERBOSE_OFFSET, VERBOSE_POOL, and VERBOSE_SIZE.
Referenced by lov_dump_user_lmm_v1v3().
void lov_dump_user_lmm_v1v3 (struct lov_user_md * lum, char * pool_name, struct lov_user_ost_data_v1 * objects, char * path, int is_dir, int obdindex, int depth, int header, int raw)
Definition at line 2231 of file liblustreapi.c.
References fid_seq_is_mdt0(), fid_seq_is_rsvd(), lov_user_ost_data_v1::l_ost_idx, LLAPI_MSG_NORMAL, llapi_printf(), lov_dump_user_lmm_header(), LOV_PATTERN_F_RELEASED, OBD_NOT_FOUND, ostid_id(), ostid_seq(), and VERBOSE_OBJID.
Referenced by llapi_lov_dump_user_lmm().
static char* next_token (char * p, int div) [static]
Definition at line 3577 of file liblustreapi.c.
Referenced by rgetfacl_output().
static DIR* opendir_parent (const char * path) [static]
Definition at line 1375 of file liblustreapi.c.
Referenced by cb_migrate_mdt_init(), and llapi_semantic_traverse().
static int param_callback (char * path, semantic_func_t sem_init, semantic_func_t sem_fini, struct find_param * param) [static]
Definition at line 1590 of file liblustreapi.c.
References buf, common_param_init(), find_param_fini(), find_param::fp_depth, llapi_error(), LLAPI_MSG_ERROR, llapi_semantic_traverse(), ret, and strlcpy().
Referenced by llapi_find(), llapi_getstripe(), and llapi_migrate_mdt().
static int print_failed_tgt (struct find_param * param, char * path, int type) [static]
Check whether the obd is active or not, if it is not active, just print the object affected by this failed target.
Definition at line 2667 of file liblustreapi.c.
References find_param::fp_obd_index, find_param::fp_obd_uuid, LASSERT, LL_STATFS_LMV, LL_STATFS_LOV, LLAPI_MSG_NORMAL, llapi_obd_statfs(), llapi_printf(), ret, and obd_uuid::uuid.
Referenced by cb_find_init().
static int rgetfacl_output (char * str) [static]
Definition at line 3666 of file liblustreapi.c.
References end, INVALID_ID, rmtacl_name_t::is_user, rmtacl_name_t::length, rmtacl_name_t::name, next_token(), rmtacl_name_t::next_token, NOBODY_GID, NOBODY_UID, rmtacl_name2id(), start, and str_is_id().
Referenced by llapi_rgetfacl().
static int rmtacl_name2id (char * name, int is_user) [static]
Definition at line 3592 of file liblustreapi.c.
References INVALID_ID.
Referenced by rgetfacl_output().
static int rmtacl_notify (int ops) [static]
Definition at line 3529 of file liblustreapi.c.
References LL_IOC_RMTACL, llapi_error(), llapi_is_lustre_mnt(), and LLAPI_MSG_ERROR.
Referenced by do_rmtacl(), llapi_cp(), and llapi_ls().
int root_ioctl (const char * mdtname, int opc, void * data, int * mdtidxp, int want_error)
ioctl on filsystem root, with mdtindex sent as data
Parameters:
mdtname path, fsname, or mdtname (lutre-MDT0004)
mdtidxp pointer to integer within data to be filled in with the mdt index (0 if no mdt is specified). NULL won't be filled.
Definition at line 3867 of file liblustreapi.c.
References get_mdtname(), get_root_path(), llapi_err_noerrno, LLAPI_MSG_ERROR, and WANT_FD.
Referenced by changelog_ioctl(), and llapi_fid2path().
static int sattr_cache_get_defaults (const char *const fsname, const char *const pathname, unsigned int * scount, unsigned int * ssize, unsigned int * soffset) [static]
Definition at line 2052 of file liblustreapi.c.
References llapi_search_fsname(), sattr_get_defaults(), and strlcpy().
Referenced by lov_dump_user_lmm_header().
static int sattr_get_defaults (const char *const fsname, unsigned int * scount, unsigned int * ssize, unsigned int * soffset) [static]
Definition at line 2011 of file liblustreapi.c.
References FILTER_BY_FS_NAME, and get_lustre_param_value().
Referenced by sattr_cache_get_defaults().
static int setup_indexes (DIR * dir, char * path, struct obd_uuid * obduuids, int num_obds, int ** obdindexes, int * obdindex, enum tgt_type type) [static]
Definition at line 1877 of file liblustreapi.c.
References buf, end, get_param_lmv(), get_param_lov(), llapi_err_noerrno, llapi_error(), llapi_get_target_uuids(), LLAPI_MSG_ERROR, llapi_uuid_match(), LOV_TYPE, OBD_NOT_FOUND, ret, and uuid.
Referenced by setup_target_indexes().
static int setup_obd_uuid (DIR * dir, char * dname, struct find_param * param) [static]
Definition at line 1790 of file liblustreapi.c.
References buf, cfs_free_param_data(), FILTER_BY_EXACT, find_param::fp_get_lmv, find_param::fp_got_uuids, find_param::fp_obd_index, find_param::fp_obd_uuid, find_param::fp_obds_printed, find_param::fp_quiet, get_lustre_param_path(), llapi_err_noerrno, llapi_error(), llapi_file_fget_lmv_uuid(), llapi_file_fget_lov_uuid(), LLAPI_MSG_ERROR, LLAPI_MSG_NORMAL, llapi_printf(), llapi_uuid_match(), OBD_NOT_FOUND, and obd_uuid::uuid.
Referenced by cb_getstripe(), and llapi_ostlist().
static int setup_target_indexes (DIR * dir, char * path, struct find_param * param) [static]
Definition at line 1964 of file liblustreapi.c.
References find_param::fp_got_uuids, find_param::fp_mdt_index, find_param::fp_mdt_indexes, find_param::fp_mdt_uuid, find_param::fp_num_mdts, find_param::fp_num_obds, find_param::fp_obd_index, find_param::fp_obd_indexes, find_param::fp_obd_uuid, LMV_TYPE, LOV_TYPE, ret, and setup_indexes().
Referenced by cb_find_init().
static int str_is_id (char * str) [static]
Definition at line 3624 of file liblustreapi.c.
References isodigit.
Referenced by rgetfacl_output().
Variable Documentation
llapi_log_callback_t llapi_error_callback = error_callback_default [static]
Definition at line 116 of file liblustreapi.c.
Referenced by llapi_error(), and llapi_error_callback_set().
llapi_log_callback_t llapi_info_callback = info_callback_default [static]
Definition at line 117 of file liblustreapi.c.
Referenced by llapi_info_callback_set(), and llapi_printf().
int llapi_msg_level = LLAPI_MSG_MAX [static]
Definition at line 82 of file liblustreapi.c.
Referenced by llapi_error(), llapi_msg_get_level(), llapi_msg_set_level(), and llapi_printf().
rmtacl_name_t rmtacl_namelist[] [static]
Initial value:
 {
        { RMTACL_OPTNAME("user:"),            1,      0 },
        { RMTACL_OPTNAME("group:"),           0,      0 },
        { RMTACL_OPTNAME("default:user:"),    1,      0 },
        { RMTACL_OPTNAME("default:group:"),   0,      0 },
        { RMTACL_OPTNAME("user"),             1,      1 },
        { RMTACL_OPTNAME("group"),            0,      1 },
        { 0 }
}
Definition at line 3655 of file liblustreapi.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.