Lustre: lustre/utils/liblustreapi_layout.c File Reference
lustre/utils/liblustreapi_layout.c File Reference
#include <stdio.h>
#include <fcntl.h>
#include <stdlib.h>
#include <unistd.h>
#include <errno.h>
#include <limits.h>
#include <sys/xattr.h>
#include <lustre/lustreapi.h>
#include <lustre/lustre_idl.h>
#include "lustreapi_internal.h"
Data Structures
struct llapi_layout
An Opaque data type abstracting the layout of a Lustre file.
Functions
static void llapi_layout_swab_lov_user_md (struct lov_user_md *lum, int object_count)
Byte-swap the fields of struct lov_user_md.
static struct llapi_layout * __llapi_layout_alloc (unsigned int num_stripes)
Allocate storage for a llapi_layout with num_stripes stripes.
static struct llapi_layout * llapi_layout_from_lum (const struct lov_user_md *lum, size_t object_count)
Copy the data from a lov_user_md to a newly allocated llapi_layout.
static struct lov_user_md * llapi_layout_to_lum (const struct llapi_layout *layout)
Copy the data from a llapi_layout to a newly allocated lov_user_md.
static void get_parent_dir (const char *path, char *buf, size_t size)
Get the parent directory of a path.
static void inherit_layout_attributes (const struct llapi_layout *src, struct llapi_layout *dest)
Substitute unspecified attribute values in dest with values from src.
static bool is_fully_specified (const struct llapi_layout *layout)
Test if all attributes of layout are specified.
struct llapi_layout * llapi_layout_alloc (void)
Allocate and initialize a new layout.
static bool llapi_layout_lum_truncated (struct lov_user_md *lum, size_t lum_size)
Check if the given lum_size is large enough to hold the required fields in lum.
static int llapi_layout_objects_in_lum (struct lov_user_md *lum, size_t lum_size)
Compute the number of elements in the lmm_objects array of lum with size lum_size.
struct llapi_layout * llapi_layout_get_by_fd (int fd, uint32_t flags)
Get the striping layout for the file referenced by file descriptor fd.
static struct llapi_layout * llapi_layout_expected (const char *path)
Get the expected striping layout for a file at path.
struct llapi_layout * llapi_layout_get_by_path (const char *path, uint32_t flags)
Get the striping layout for the file at path.
struct llapi_layout * llapi_layout_get_by_fid (const char *lustre_dir, const lustre_fid *fid, uint32_t flags)
Get the layout for the file with FID fidstr in filesystem lustre_dir.
void llapi_layout_free (struct llapi_layout *layout)
* Free memory allocated for layout.
int llapi_layout_stripe_count_get (const struct llapi_layout *layout, uint64_t *count)
Get the stripe count of layout.
static bool llapi_layout_stripe_count_is_valid (int64_t stripe_count)
static bool llapi_layout_stripe_size_is_valid (uint64_t stripe_size)
static bool llapi_layout_stripe_index_is_valid (int64_t stripe_index)
int llapi_layout_stripe_count_set (struct llapi_layout *layout, uint64_t count)
Set the stripe count of layout.
int llapi_layout_stripe_size_get (const struct llapi_layout *layout, uint64_t *size)
Get the stripe size of layout.
int llapi_layout_stripe_size_set (struct llapi_layout *layout, uint64_t size)
Set the stripe size of layout.
int llapi_layout_pattern_get (const struct llapi_layout *layout, uint64_t *pattern)
Get the RAID pattern of layout.
int llapi_layout_pattern_set (struct llapi_layout *layout, uint64_t pattern)
Set the RAID pattern of layout.
int llapi_layout_ost_index_set (struct llapi_layout *layout, int stripe_number, uint64_t ost_index)
Set the OST index of stripe number stripe_number to ost_index.
int llapi_layout_ost_index_get (const struct llapi_layout *layout, uint64_t stripe_number, uint64_t *index)
Get the OST index associated with stripe stripe_number.
int llapi_layout_pool_name_get (const struct llapi_layout *layout, char *dest, size_t n)
Get the pool name of layout layout.
int llapi_layout_pool_name_set (struct llapi_layout *layout, const char *pool_name)
Set the name of the pool of layout layout.
int llapi_layout_file_open (const char *path, int open_flags, mode_t mode, const struct llapi_layout *layout)
Open and possibly create a file with a given layout.
int llapi_layout_file_create (const char *path, int open_flags, int mode, const struct llapi_layout *layout)
Create a file with a given layout.
Function Documentation
static struct llapi_layout* __llapi_layout_alloc (unsigned int num_stripes) [static, read]
Allocate storage for a llapi_layout with num_stripes stripes.
Parameters:
[in] num_stripes number of stripes in new layout
Return values:
valid pointer if allocation succeeds
NULL if allocation fails
Definition at line 98 of file liblustreapi_layout.c.
References llapi_layout::llot_objects, LOV_MAX_STRIPE_COUNT, and size.
Referenced by llapi_layout_alloc(), and llapi_layout_from_lum().
static void get_parent_dir (const char * path, char * buf, size_t size) [static]
Get the parent directory of a path.
Parameters:
[in] path path to get parent of
[out] buf buffer in which to store parent path
[in] size size in bytes of buffer buf
Definition at line 250 of file liblustreapi_layout.c.
Referenced by llapi_layout_expected().
static void inherit_layout_attributes (const struct llapi_layout * src, struct llapi_layout * dest) [static]
Substitute unspecified attribute values in dest with values from src.
Parameters:
[in] src layout to inherit values from
[in] dest layout to receive inherited values
Definition at line 270 of file liblustreapi_layout.c.
References LLAPI_LAYOUT_DEFAULT, llapi_layout::llot_pattern, llapi_layout::llot_stripe_count, and llapi_layout::llot_stripe_size.
Referenced by llapi_layout_expected().
static bool is_fully_specified (const struct llapi_layout * layout) [static]
Test if all attributes of layout are specified.
Parameters:
[in] layout the layout to check
Return values:
true all attributes are specified
false at least one attribute is unspecified
Definition at line 291 of file liblustreapi_layout.c.
References LLAPI_LAYOUT_DEFAULT, llapi_layout::llot_pattern, llapi_layout::llot_stripe_count, and llapi_layout::llot_stripe_size.
Referenced by llapi_layout_expected().
struct llapi_layout* llapi_layout_alloc (void) [read]
Allocate and initialize a new layout.
Allocate a new layout.
Return values:
valid llapi_layout pointer on success
NULL if memory allocation fails
Definition at line 304 of file liblustreapi_layout.c.
References __llapi_layout_alloc(), LLAPI_LAYOUT_DEFAULT, LLAPI_LAYOUT_MAGIC, llapi_layout::llot_magic, llapi_layout::llot_objects_are_valid, llapi_layout::llot_pattern, llapi_layout::llot_pool_name, llapi_layout::llot_stripe_count, llapi_layout::llot_stripe_offset, and llapi_layout::llot_stripe_size.
Referenced by llapi_layout_expected(), llapi_layout_get_by_fd(), test0(), test10(), test11(), test12(), test13(), test14(), test15(), test16(), test17(), test18(), test19(), test20(), test21(), and test9().
static struct llapi_layout* llapi_layout_expected (const char * path) [static, read]
Get the expected striping layout for a file at path.
Substitute expected inherited attribute values for unspecified attributes. Unspecified attributes may belong to directories and never-written-to files, and indicate that default values will be assigned when files are created or first written to. A default value is inherited from the parent directory if the attribute is specified there, otherwise it is inherited from the filesystem root. Unspecified attributes normally have the value LLAPI_LAYOUT_DEFAULT.
The complete path need not refer to an existing file or directory, but some leading portion of it must reside within a lustre filesystem. A use case for this interface would be to obtain the literal striping values that would be assigned to a new file in a given directory.
Parameters:
[in] path path for which to get the expected layout
Return values:
valid llapi_layout pointer on success
NULL if an error occurs
Definition at line 482 of file liblustreapi_layout.c.
References get_parent_dir(), inherit_layout_attributes(), is_fully_specified(), llapi_layout_alloc(), llapi_layout_free(), llapi_layout_get_by_fd(), llapi_layout_get_by_path(), and llapi_search_mounts().
Referenced by llapi_layout_get_by_path().
int llapi_layout_file_create (const char * path, int open_flags, int mode, const struct llapi_layout * layout)
Create a file with a given layout.
Create a new file at path with the specified layout and mode.
Force O_CREAT and O_EXCL flags on so caller is assured that file was created with the given layout on successful function return.
Parameters:
[in] path name of the file to open
[in] open_flags open() flags
[in] mode permissions to create new file with
[in] layout layout to create new file with
Return values:
non-negative file descriptor on successful open
-1 if an error occurred
Definition at line 1002 of file liblustreapi_layout.c.
References llapi_layout_file_open().
Referenced by test0(), test13(), test14(), test15(), test16(), test17(), test18(), test20(), test21(), and test22().
int llapi_layout_file_open (const char * path, int open_flags, mode_t mode, const struct llapi_layout * layout)
Open and possibly create a file with a given layout.
Open an existing file at path, or create it with the specified layout and mode.
If layout is NULL this function acts as a simple wrapper for open(). By convention, ENOTTY is returned in errno if path refers to a non-Lustre file.
Parameters:
[in] path name of the file to open
[in] open_flags open() flags
[in] mode permissions to create new file with
[in] layout layout to create new file with
Return values:
non-negative file descriptor on successful open
-1 if an error occurred
Definition at line 938 of file liblustreapi_layout.c.
References LLAPI_LAYOUT_MAGIC, llapi_layout_to_lum(), llapi_layout::llot_magic, lov_user_md, lov_user_md_size(), O_LOV_DELAY_CREATE, and XATTR_LUSTRE_LOV.
Referenced by llapi_layout_file_create(), and test15().
void llapi_layout_free (struct llapi_layout * layout)
* Free memory allocated for layout.
Free memory allocated for layout.
Definition at line 625 of file liblustreapi_layout.c.
Referenced by llapi_layout_expected(), test0(), test1(), test10(), test11(), test12(), test13(), test14(), test15(), test16(), test17(), test18(), test19(), test2(), test20(), test21(), test24(), test25(), test26(), test27(), test28(), test3(), test4(), test8(), and test9().
static struct llapi_layout* llapi_layout_from_lum (const struct lov_user_md * lum, size_t object_count) [static, read]
Copy the data from a lov_user_md to a newly allocated llapi_layout.
The caller is responsible for freeing the returned pointer.
Parameters:
[in] lum LOV user metadata structure to copy data from
Return values:
valid llapi_layout pointer on success
NULL if memory allocation fails
Definition at line 123 of file liblustreapi_layout.c.
References __llapi_layout_alloc(), LLAPI_LAYOUT_DEFAULT, LLAPI_LAYOUT_MAGIC, LLAPI_LAYOUT_RAID0, LLAPI_LAYOUT_WIDE, lov_user_md_v1::lmm_objects, lov_user_md_v3::lmm_objects, lov_user_md_v3::lmm_pool_name, LOV_PATTERN_RAID0, and LOV_USER_MAGIC_V1.
Referenced by llapi_layout_get_by_fd().
struct llapi_layout* llapi_layout_get_by_fd (int fd, uint32_t flags) [read]
Get the striping layout for the file referenced by file descriptor fd.
Return a pointer to a newly-allocated opaque data type containing the layout for the file referenced by open file descriptor fd.
If the filesystem does not support the "lustre." xattr namespace, the file must be on a non-Lustre filesystem, so set errno to ENOTTY per convention. If the file has no "lustre.lov" data, the file will inherit default values, so return a default layout.
If the kernel gives us back less than the expected amount of data, we fail with errno set to EINTR.
Parameters:
[in] fd open file descriptor
[in] flags open file descriptor
Return values:
valid llapi_layout pointer on success
NULL if an error occurs
Definition at line 398 of file liblustreapi_layout.c.
References __swab16, __swab32, llapi_layout_alloc(), llapi_layout_from_lum(), llapi_layout_lum_truncated(), llapi_layout_objects_in_lum(), llapi_layout_swab_lov_user_md(), LOV_MAGIC_V1, LOV_MAGIC_V3, lov_user_md, and XATTR_LUSTRE_LOV.
Referenced by llapi_layout_expected(), llapi_layout_get_by_fid(), llapi_layout_get_by_path(), test2(), and test6().
struct llapi_layout* llapi_layout_get_by_fid (const char * lustre_dir, const lustre_fid * fid, uint32_t flags) [read]
Get the layout for the file with FID fidstr in filesystem lustre_dir.
Return a pointer to a newly-allocated opaque data type containing the layout for the file associated with Lustre file identifier string fidstr.
Parameters:
[in] lustre_dir path within Lustre filesystem containing fid
[in] fid Lustre identifier of file to get layout for
Return values:
valid llapi_layout pointer on success
NULL if an error occurs
Definition at line 597 of file liblustreapi_layout.c.
References llapi_layout_get_by_fd(), llapi_msg_get_level(), LLAPI_MSG_OFF, llapi_msg_set_level(), and llapi_open_by_fid().
Referenced by test3().
struct llapi_layout* llapi_layout_get_by_path (const char * path, uint32_t flags) [read]
Get the striping layout for the file at path.
Return a pointer to a newly-allocated opaque data structure containing the layout for the file at path.
If flags contains LAYOUT_GET_EXPECTED, substitute expected inherited attribute values for unspecified attributes. See llapi_layout_expected().
Parameters:
[in] path path for which to get the layout
[in] flags flags to control how layout is retrieved
Return values:
valid llapi_layout pointer on success
NULL if an error occurs
Definition at line 567 of file liblustreapi_layout.c.
References LAYOUT_GET_EXPECTED, llapi_layout_expected(), and llapi_layout_get_by_fd().
Referenced by llapi_layout_expected(), test1(), test13(), test15(), test16(), test17(), test18(), test20(), test23(), test24(), test25(), test26(), test27(), test28(), test4(), test5(), test7(), and test8().
static bool llapi_layout_lum_truncated (struct lov_user_md * lum, size_t lum_size) [static]
Check if the given lum_size is large enough to hold the required fields in lum.
Parameters:
[in] lum the struct lov_user_md to check
[in] lum_size the number of bytes in lum
Return values:
true the lum_size is too small
false the lum_size is large enough
Definition at line 334 of file liblustreapi_layout.c.
References __swab32, LOV_MAGIC_V1, LOV_MAGIC_V3, and lov_user_md_size().
Referenced by llapi_layout_get_by_fd().
static int llapi_layout_objects_in_lum (struct lov_user_md * lum, size_t lum_size) [static]
Compute the number of elements in the lmm_objects array of lum with size lum_size.
Parameters:
[in] lum the struct lov_user_md to check
[in] lum_size the number of bytes in lum
Return values:
number of elements in array lum->lmm_objects
Definition at line 359 of file liblustreapi_layout.c.
References __swab32, LOV_MAGIC_V1, LOV_MAGIC_V3, and lov_user_md_size().
Referenced by llapi_layout_get_by_fd().
int llapi_layout_ost_index_get (const struct llapi_layout * layout, uint64_t stripe_number, uint64_t * index)
Get the OST index associated with stripe stripe_number.
Store the index of the OST where stripe number stripe_number is stored in index.
Stripes are indexed starting from zero.
Parameters:
[in] layout layout to get index from
[in] stripe_number stripe number to get index for
[out] index integer to store index in
Return values:
0 on success
-1 if arguments are invalid
Definition at line 844 of file liblustreapi_layout.c.
References lov_user_ost_data_v1::l_ost_idx, LLAPI_LAYOUT_DEFAULT, LLAPI_LAYOUT_MAGIC, llapi_layout::llot_magic, llapi_layout::llot_objects, llapi_layout::llot_objects_are_valid, and llapi_layout::llot_stripe_count.
Referenced by __test1_helper(), test13(), and test4().
int llapi_layout_ost_index_set (struct llapi_layout * layout, int stripe_number, uint64_t ost_index)
Set the OST index of stripe number stripe_number to ost_index.
Set the OST index associated with stripe number stripe_number to ost_index.
The index may only be set for stripe number 0 for now.
Parameters:
[in] layout layout to set OST index in
[in] stripe_number stripe number to set index for
[in] ost_index the index to set
Return values:
0 on success
-1 if arguments are invalid or an unsupported stripe number was specified
Definition at line 813 of file liblustreapi_layout.c.
References LLAPI_LAYOUT_MAGIC, llapi_layout_stripe_index_is_valid(), llapi_layout::llot_magic, and llapi_layout::llot_stripe_offset.
Referenced by test0(), and test13().
int llapi_layout_pattern_get (const struct llapi_layout * layout, uint64_t * pattern)
Get the RAID pattern of layout.
Store the stripe pattern of layout in pattern.
Parameters:
[in] layout layout to get pattern from
[out] pattern integer to store pattern in
Return values:
0 on success
-1 if arguments are invalid
Definition at line 758 of file liblustreapi_layout.c.
References LLAPI_LAYOUT_MAGIC, llapi_layout::llot_magic, and llapi_layout::llot_pattern.
Referenced by test24(), test25(), test26(), test27(), and test8().
int llapi_layout_pattern_set (struct llapi_layout * layout, uint64_t pattern)
Set the RAID pattern of layout.
Set the stripe pattern of layout to pattern.
Parameters:
[in] layout layout to set pattern in
[in] pattern value to be set
Return values:
0 on success
-1 if arguments are invalid or RAID pattern is unsupported
Definition at line 782 of file liblustreapi_layout.c.
References LLAPI_LAYOUT_DEFAULT, LLAPI_LAYOUT_MAGIC, LLAPI_LAYOUT_RAID0, llapi_layout::llot_magic, and llapi_layout::llot_pattern.
Referenced by test9().
int llapi_layout_pool_name_get (const struct llapi_layout * layout, char * dest, size_t n)
Get the pool name of layout layout.
Store up to pool_name_len characters of the name of the pool of OSTs associated with layout into the buffer pointed to by pool_name.
Parameters:
[in] layout layout to get pool name from
[out] dest buffer to store pool name in
[in] n size in bytes of buffer dest
Return values:
0 on success
-1 if arguments are invalid
Definition at line 873 of file liblustreapi_layout.c.
References LLAPI_LAYOUT_MAGIC, llapi_layout::llot_magic, and llapi_layout::llot_pool_name.
Referenced by __test1_helper(), test0(), test12(), test18(), test19(), and test4().
int llapi_layout_pool_name_set (struct llapi_layout * layout, const char * pool_name)
Set the name of the pool of layout layout.
Set the name of the pool of OSTs from which file objects will be allocated to pool_name.
Parameters:
[in] layout layout to set pool name in
[in] pool_name pool name to set
Return values:
0 on success
-1 if arguments are invalid or pool name is too long
Definition at line 896 of file liblustreapi_layout.c.
References LLAPI_LAYOUT_MAGIC, llapi_layout::llot_magic, llapi_layout::llot_pool_name, and LOV_MAXPOOLNAME.
Referenced by test0(), test12(), test18(), and test19().
int llapi_layout_stripe_count_get (const struct llapi_layout * layout, uint64_t * count)
Get the stripe count of layout.
Flags to modify how layouts are retrieved.
Parameters:
[in] layout layout to get stripe count from
[out] count integer to store stripe count in
Return values:
0 on success
-1 if arguments are invalid
Definition at line 639 of file liblustreapi_layout.c.
References LLAPI_LAYOUT_MAGIC, llapi_layout::llot_magic, and llapi_layout::llot_stripe_count.
Referenced by __test1_helper(), test0(), test10(), test15(), test16(), test17(), test20(), test24(), test25(), test26(), test27(), test28(), test4(), and test8().
static bool llapi_layout_stripe_count_is_valid (int64_t stripe_count) [static]
Definition at line 657 of file liblustreapi_layout.c.
References LLAPI_LAYOUT_DEFAULT, LLAPI_LAYOUT_WIDE, and llapi_stripe_count_is_valid().
Referenced by llapi_layout_stripe_count_set().
int llapi_layout_stripe_count_set (struct llapi_layout * layout, uint64_t count)
Set the stripe count of layout.
Set the stripe count of layout to count.
Parameters:
[in] layout layout to set stripe count in
[in] count value to be set
Return values:
0 on success
-1 if arguments are invalid
Definition at line 689 of file liblustreapi_layout.c.
References LLAPI_LAYOUT_MAGIC, llapi_layout_stripe_count_is_valid(), llapi_layout::llot_magic, and llapi_layout::llot_stripe_count.
Referenced by test0(), test10(), test13(), test15(), test17(), and test20().
static bool llapi_layout_stripe_index_is_valid (int64_t stripe_index) [static]
Definition at line 673 of file liblustreapi_layout.c.
References LLAPI_LAYOUT_DEFAULT, and llapi_stripe_index_is_valid().
Referenced by llapi_layout_ost_index_set().
int llapi_layout_stripe_size_get (const struct llapi_layout * layout, uint64_t * size)
Get the stripe size of layout.
Store the stripe size of layout in size.
Parameters:
[in] layout layout to get stripe size from
[out] size integer to store stripe size in
Return values:
0 on success
-1 if arguments are invalid
Definition at line 712 of file liblustreapi_layout.c.
References LLAPI_LAYOUT_MAGIC, llapi_layout::llot_magic, and llapi_layout::llot_stripe_size.
Referenced by __test1_helper(), test0(), test11(), test16(), test20(), test24(), test25(), test26(), test27(), test4(), and test8().
static bool llapi_layout_stripe_size_is_valid (uint64_t stripe_size) [static]
Definition at line 665 of file liblustreapi_layout.c.
References LLAPI_LAYOUT_DEFAULT, llapi_stripe_size_is_aligned(), and llapi_stripe_size_is_too_big().
Referenced by llapi_layout_stripe_size_set().
int llapi_layout_stripe_size_set (struct llapi_layout * layout, uint64_t size)
Set the stripe size of layout.
Set the stripe size of layout to stripe_size.
Parameters:
[in] layout layout to set stripe size in
[in] size value to be set
Return values:
0 on success
-1 if arguments are invalid
Definition at line 735 of file liblustreapi_layout.c.
References LLAPI_LAYOUT_MAGIC, llapi_layout_stripe_size_is_valid(), llapi_layout::llot_magic, and llapi_layout::llot_stripe_size.
Referenced by test0(), test11(), and test20().
static void llapi_layout_swab_lov_user_md (struct lov_user_md * lum, int object_count) [static]
Byte-swap the fields of struct lov_user_md.
XXX Rather than duplicating swabbing code here, we should eventually refactor the needed functions in lustre/ptlrpc/pack_generic.c into a library that can be shared between kernel and user code.
Definition at line 69 of file liblustreapi_layout.c.
References __swab16s, __swab32s, lov_user_md_v3::lmm_objects, LOV_MAGIC_V1, and lov_user_ost_data.
Referenced by llapi_layout_get_by_fd().
static struct lov_user_md* llapi_layout_to_lum (const struct llapi_layout * layout) [static, read]
Copy the data from a llapi_layout to a newly allocated lov_user_md.
The caller is responsible for freeing the returned pointer.
The current version of this API doesn't support specifying the OST index of arbitrary stripes, only stripe 0 via lmm_stripe_offset. There is therefore no need to copy the lmm_objects array.
Parameters:
[in] layout the layout to copy from
Return values:
valid lov_user_md pointer on success
NULL if memory allocation fails
Definition at line 189 of file liblustreapi_layout.c.
References LLAPI_LAYOUT_DEFAULT, LLAPI_LAYOUT_RAID0, LLAPI_LAYOUT_WIDE, llapi_layout::llot_pattern, llapi_layout::llot_pool_name, llapi_layout::llot_stripe_count, llapi_layout::llot_stripe_offset, llapi_layout::llot_stripe_size, lov_user_md_v3::lmm_pool_name, LOV_USER_MAGIC_V1, LOV_USER_MAGIC_V3, lov_user_md, and lov_user_md_size().
Referenced by llapi_layout_file_open().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.