Lustre: lustre/obdclass/linkea.c File Reference
lustre/obdclass/linkea.c File Reference
#include <lustre/lustre_idl.h>
#include <obd.h>
#include <lustre_linkea.h>
Functions
int linkea_data_new (struct linkea_data *ldata, struct lu_buf *buf)
int linkea_init (struct linkea_data *ldata)
int linkea_entry_pack (struct link_ea_entry *lee, const struct lu_name *lname, const struct lu_fid *pfid)
Pack a link_ea_entry.
void linkea_entry_unpack (const struct link_ea_entry *lee, int *reclen, struct lu_name *lname, struct lu_fid *pfid)
int linkea_add_buf (struct linkea_data *ldata, const struct lu_name *lname, const struct lu_fid *pfid)
Add a record to the end of link ea buf.
void linkea_del_buf (struct linkea_data *ldata, const struct lu_name *lname)
Del the current record from the link ea buf.
int linkea_links_find (struct linkea_data *ldata, const struct lu_name *lname, const struct lu_fid *pfid)
Check if such a link exists in linkEA.
Function Documentation
int linkea_add_buf (struct linkea_data * ldata, const struct lu_name * lname, const struct lu_fid * pfid)
Add a record to the end of link ea buf.
Definition at line 113 of file linkea.c.
References CDEBUG, D_INODE, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, linkea_data::ld_buf, linkea_data::ld_lee, linkea_data::ld_leh, linkea_data::ld_reclen, link_ea_header::leh_len, link_ea_header::leh_reccount, linkea_entry_pack(), lu_name::ln_name, lu_name::ln_namelen, and lu_buf_check_and_grow().
Referenced by __mdd_links_add(), lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_layout_recreate_parent(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_dsd_multiple(), lfsck_namespace_insert_orphan(), lfsck_namespace_repair_dangling(), lfsck_namespace_repair_unmatched_pairs(), lfsck_namespace_striped_dir_rescan(), lfsck_verify_linkea(), lod_dir_declare_create_stripes(), lod_xattr_set_lmv(), and mdd_migrate_update_name().
int linkea_data_new (struct linkea_data * ldata, struct lu_buf * buf)
Definition at line 34 of file linkea.c.
References lu_buf::lb_buf, linkea_data::ld_buf, linkea_data::ld_leh, link_ea_header::leh_len, link_ea_header::leh_magic, link_ea_header::leh_reccount, LINK_EA_MAGIC, and lu_buf_check_and_alloc().
Referenced by __mdd_links_add(), lfsck_create_lpf_local(), lfsck_create_lpf_remote(), lfsck_layout_recreate_parent(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_dsd_multiple(), lfsck_namespace_insert_orphan(), lfsck_namespace_repair_dangling(), lfsck_namespace_repair_unmatched_pairs(), lfsck_namespace_striped_dir_rescan(), lfsck_verify_linkea(), ll_getparent(), lod_dir_declare_create_stripes(), and lod_xattr_set_lmv().
void linkea_del_buf (struct linkea_data * ldata, const struct lu_name * lname)
Del the current record from the link ea buf.
Definition at line 142 of file linkea.c.
References CDEBUG, D_INODE, LASSERT, linkea_data::ld_lee, linkea_data::ld_leh, linkea_data::ld_reclen, link_ea_header::leh_len, link_ea_header::leh_reccount, lu_name::ln_name, and lu_name::ln_namelen.
Referenced by __mdd_links_del(), lfsck_namespace_dsd_multiple(), lfsck_namespace_filter_linkea_entry(), lfsck_namespace_shrink_linkea(), and mdd_update_linkea_internal().
int linkea_entry_pack (struct link_ea_entry * lee, const struct lu_name * lname, const struct lu_fid * pfid)
Pack a link_ea_entry.
All elements are stored as chars to avoid alignment issues. Numbers are always big-endian
Return values:
record length
Definition at line 75 of file linkea.c.
References lu_fid::f_oid, lu_fid::f_ver, fid_cpu_to_be(), link_ea_entry::lee_name, link_ea_entry::lee_parent_fid, link_ea_entry::lee_reclen, lu_name::ln_name, lu_name::ln_namelen, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_LINKEA_CRASH, and OBD_FAIL_LFSCK_MUL_REF.
Referenced by linkea_add_buf(), and mdd_linkea_update_child_internal().
void linkea_entry_unpack (const struct link_ea_entry * lee, int * reclen, struct lu_name * lname, struct lu_fid * pfid)
Definition at line 97 of file linkea.c.
References fid_be_to_cpu(), link_ea_entry::lee_name, link_ea_entry::lee_parent_fid, link_ea_entry::lee_reclen, lu_name::ln_name, and lu_name::ln_namelen.
Referenced by lfsck_links_get_first(), lfsck_namespace_exec_oit(), lfsck_namespace_unpack_linkea_entry(), linkea_links_find(), ll_linkea_decode(), mdd_linkea_update_child_internal(), mdd_migrate_sanity_check(), mdd_parent_fid(), mdd_update_linkea_internal(), mdt_lock_objects_in_linkea(), mdt_path_current(), and osd_get_pfid_from_linkea().
int linkea_init (struct linkea_data * ldata)
Definition at line 47 of file linkea.c.
References __swab32, __swab64, LASSERT, lu_buf::lb_buf, linkea_data::ld_buf, linkea_data::ld_leh, link_ea_header::leh_len, link_ea_header::leh_magic, link_ea_header::leh_reccount, and LINK_EA_MAGIC.
Referenced by __lfsck_links_read(), ll_linkea_decode(), mdd_links_read(), mdt_links_read(), and osd_get_pfid_from_linkea().
int linkea_links_find (struct linkea_data * ldata, const struct lu_name * lname, const struct lu_fid * pfid)
Check if such a link exists in linkEA.
Parameters:
ldata link data the search to be done on
lname name in the parent's directory entry pointing to this object
pfid parent fid the link to be found for
Return values:
0 success
-ENOENT link does not exist
-ve on error
Definition at line 171 of file linkea.c.
References CDEBUG, D_INODE, LASSERT, linkea_data::ld_lee, linkea_data::ld_leh, linkea_data::ld_reclen, link_ea_header::leh_reccount, linkea_entry_unpack(), lu_name::ln_name, lu_name::ln_namelen, and lu_fid_eq().
Referenced by __mdd_links_add(), __mdd_links_del(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_replace_cond(), lfsck_namespace_shrink_linkea(), lfsck_namespace_striped_dir_rescan(), and lfsck_verify_linkea().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.