Lustre: lustre/obdclass/linux/linux-obdo.c File Reference
lustre/obdclass/linux/linux-obdo.c File Reference
#include <linux/fs.h>
#include <linux/module.h>
#include <linux/pagemap.h>
#include <lustre/lustre_idl.h>
#include <obd_class.h>
Defines
#define DEBUG_SUBSYSTEM S_CLASS
Functions
void obdo_from_la (struct obdo *dst, const struct lu_attr *la, u64 valid)
void la_from_obdo (struct lu_attr *dst, const struct obdo *obdo, u64 valid)
Define Documentation
#define DEBUG_SUBSYSTEM S_CLASS
Definition at line 43 of file linux-obdo.c.
Function Documentation
void la_from_obdo (struct lu_attr * dst, const struct obdo * obdo, u64 valid)
Definition at line 103 of file linux-obdo.c.
References LA_ATIME, lu_attr::la_atime, LA_BLOCKS, lu_attr::la_blocks, LA_CTIME, lu_attr::la_ctime, LA_FLAGS, lu_attr::la_flags, LA_GID, lu_attr::la_gid, LA_MODE, lu_attr::la_mode, LA_MTIME, lu_attr::la_mtime, LA_SIZE, lu_attr::la_size, LA_TYPE, LA_UID, lu_attr::la_uid, lu_attr::la_valid, obdo::o_atime, obdo::o_blocks, obdo::o_ctime, obdo::o_flags, obdo::o_gid, obdo::o_mode, obdo::o_mtime, obdo::o_size, obdo::o_uid, obdo::o_valid, OBD_MD_FLATIME, OBD_MD_FLBLOCKS, OBD_MD_FLCTIME, OBD_MD_FLFLAGS, OBD_MD_FLGID, OBD_MD_FLMODE, OBD_MD_FLMTIME, OBD_MD_FLSIZE, OBD_MD_FLTYPE, and OBD_MD_FLUID.
Referenced by ofd_commitrw(), ofd_echo_setattr(), ofd_preprw(), ofd_punch_hdl(), ofd_setattr_hdl(), osp_get_attr_from_reply(), out_attr_set(), out_create(), update_recovery_attr_set(), and update_recovery_create().
void obdo_from_la (struct obdo * dst, const struct lu_attr * la, u64 valid)
Definition at line 52 of file linux-obdo.c.
References lu_attr::la_atime, LA_ATIME, lu_attr::la_blocks, LA_BLOCKS, lu_attr::la_ctime, LA_CTIME, lu_attr::la_flags, LA_FLAGS, lu_attr::la_gid, LA_GID, LA_MODE, lu_attr::la_mode, lu_attr::la_mtime, LA_MTIME, lu_attr::la_size, LA_SIZE, LA_TYPE, lu_attr::la_uid, LA_UID, obdo::o_atime, obdo::o_blocks, obdo::o_ctime, obdo::o_flags, obdo::o_gid, obdo::o_mode, obdo::o_mtime, obdo::o_size, obdo::o_uid, obdo::o_valid, OBD_MD_FLATIME, OBD_MD_FLBLOCKS, OBD_MD_FLCTIME, OBD_MD_FLFLAGS, OBD_MD_FLGID, OBD_MD_FLMODE, OBD_MD_FLMTIME, OBD_MD_FLSIZE, OBD_MD_FLTYPE, and OBD_MD_FLUID.
Referenced by ofd_commitrw(), ofd_echo_getattr(), ofd_getattr_hdl(), ofd_preprw(), ofd_setattr_hdl(), ofd_sync_hdl(), out_attr_get(), out_attr_set_pack(), out_create_pack(), update_records_attr_set_pack(), and update_records_create_pack().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.