Lustre: libcfs/libcfs/linux/linux-crypto-crc32pclmul.c File Reference
libcfs/libcfs/linux/linux-crypto-crc32pclmul.c File Reference
#include <linux/crc32.h>
#include <crypto/internal/hash.h>
#include <asm/cpufeature.h>
#include <asm/i387.h>
#include <libcfs/libcfs.h>
Defines
#define CHKSUM_BLOCK_SIZE 1
#define CHKSUM_DIGEST_SIZE 4
#define PCLMUL_MIN_LEN 64L
#define SCALE_F 16L
#define SCALE_F_MASK (SCALE_F - 1)
#define X86_FEATURE_PCLMULQDQ (4*32+1)
Functions
u32 crc32_pclmul_le_16 (unsigned char const *buffer, size_t len, u32 crc32)
static u32 __attribute__ ((pure))
static int crc32_pclmul_cra_init (struct crypto_tfm *tfm)
static int crc32_pclmul_setkey (struct crypto_shash *hash, const u8 *key, unsigned int keylen)
static int crc32_pclmul_init (struct shash_desc *desc)
static int crc32_pclmul_update (struct shash_desc *desc, const u8 *data, unsigned int len)
static int __crc32_pclmul_finup (u32 *crcp, const u8 *data, unsigned int len, u8 *out)
static int crc32_pclmul_finup (struct shash_desc *desc, const u8 *data, unsigned int len, u8 *out)
static int crc32_pclmul_final (struct shash_desc *desc, u8 *out)
static int crc32_pclmul_digest (struct shash_desc *desc, const u8 *data, unsigned int len, u8 *out)
int cfs_crypto_crc32_pclmul_register (void)
Functions for start/stop shash crc32 pclmulqdq.
void cfs_crypto_crc32_pclmul_unregister (void)
Variables
static struct shash_alg alg
Define Documentation
#define CHKSUM_BLOCK_SIZE 1
Definition at line 38 of file linux-crypto-crc32pclmul.c.
#define CHKSUM_DIGEST_SIZE 4
Definition at line 39 of file linux-crypto-crc32pclmul.c.
#define PCLMUL_MIN_LEN 64L
Definition at line 41 of file linux-crypto-crc32pclmul.c.
Referenced by __attribute__().
#define SCALE_F 16L
Definition at line 43 of file linux-crypto-crc32pclmul.c.
Referenced by __attribute__().
#define SCALE_F_MASK (SCALE_F - 1)
Definition at line 44 of file linux-crypto-crc32pclmul.c.
Referenced by __attribute__().
#define X86_FEATURE_PCLMULQDQ (4*32+1)
Definition at line 176 of file linux-crypto-crc32pclmul.c.
Referenced by cfs_crypto_crc32_pclmul_register().
Function Documentation
static u32 __attribute__ ((pure)) [static]
Definition at line 48 of file linux-crypto-crc32pclmul.c.
References crc32_pclmul_le_16(), PCLMUL_MIN_LEN, SCALE_F, and SCALE_F_MASK.
static int __crc32_pclmul_finup (u32 * crcp, const u8 * data, unsigned int len, u8 * out) [static]
Definition at line 127 of file linux-crypto-crc32pclmul.c.
References cpu_to_le32.
Referenced by crc32_pclmul_digest(), and crc32_pclmul_finup().
int cfs_crypto_crc32_pclmul_register (void)
Functions for start/stop shash crc32 pclmulqdq.
Definition at line 179 of file linux-crypto-crc32pclmul.c.
References CDEBUG, D_INFO, and X86_FEATURE_PCLMULQDQ.
Referenced by cfs_crypto_register().
void cfs_crypto_crc32_pclmul_unregister (void)
Definition at line 189 of file linux-crypto-crc32pclmul.c.
Referenced by cfs_crypto_unregister().
static int crc32_pclmul_cra_init (struct crypto_tfm * tfm) [static]
Definition at line 80 of file linux-crypto-crc32pclmul.c.
static int crc32_pclmul_digest (struct shash_desc * desc, const u8 * data, unsigned int len, u8 * out) [static]
Definition at line 148 of file linux-crypto-crc32pclmul.c.
References __crc32_pclmul_finup().
static int crc32_pclmul_final (struct shash_desc * desc, u8 * out) [static]
Definition at line 140 of file linux-crypto-crc32pclmul.c.
static int crc32_pclmul_finup (struct shash_desc * desc, const u8 * data, unsigned int len, u8 * out) [static]
Definition at line 134 of file linux-crypto-crc32pclmul.c.
References __crc32_pclmul_finup().
static int crc32_pclmul_init (struct shash_desc * desc) [static]
Definition at line 107 of file linux-crypto-crc32pclmul.c.
u32 crc32_pclmul_le_16 (unsigned char const * buffer, size_t len, u32 crc32)
Referenced by __attribute__().
static int crc32_pclmul_setkey (struct crypto_shash * hash, const u8 * key, unsigned int keylen) [static]
Definition at line 94 of file linux-crypto-crc32pclmul.c.
static int crc32_pclmul_update (struct shash_desc * desc, const u8 * data, unsigned int len) [static]
Definition at line 117 of file linux-crypto-crc32pclmul.c.
Variable Documentation
struct shash_alg alg [static]
Initial value:
 {
        .setkey         = crc32_pclmul_setkey,
        .init           = crc32_pclmul_init,
        .update         = crc32_pclmul_update,
        .final          = crc32_pclmul_final,
        .finup          = crc32_pclmul_finup,
        .digest         = crc32_pclmul_digest,
        .descsize       = sizeof(u32),
        .digestsize     = CHKSUM_DIGEST_SIZE,
        .base           = {
                        .cra_name               = "crc32",
                        .cra_driver_name        = "crc32-pclmul",
                        .cra_priority           = 200,
                        .cra_blocksize          = CHKSUM_BLOCK_SIZE,
                        .cra_ctxsize            = sizeof(u32),
                        .cra_module             = THIS_MODULE,
                        .cra_init               = crc32_pclmul_cra_init,
        }
}
Definition at line 155 of file linux-crypto-crc32pclmul.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.