Lustre: libcfs/include/libcfs/linux/linux-misc.h File Reference
libcfs/include/libcfs/linux/linux-misc.h File Reference
Defines
#define INIT_CTL_NAME
#define INIT_STRATEGY
Functions
static int kstrtoul (const char *s, unsigned int base, unsigned long *res)
Define Documentation
#define INIT_CTL_NAME
Definition at line 44 of file linux-misc.h.
#define INIT_STRATEGY
Definition at line 45 of file linux-misc.h.
Function Documentation
static int kstrtoul (const char * s, unsigned int base, unsigned long * res) [inline, static]
Definition at line 49 of file linux-misc.h.
References end.
Referenced by mgs_iocontrol_nodemap(), nodemap_active_seq_write(), nodemap_parse_idmap(), nodemap_proc_read_flag(), nodemap_squash_gid_seq_write(), and nodemap_squash_uid_seq_write().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.