Lustre: libcfs/libcfs/linux/linux-curproc.c File Reference
libcfs/libcfs/linux/linux-curproc.c File Reference
#include <linux/sched.h>
#include <linux/fs_struct.h>
#include <linux/compat.h>
#include <linux/thread_info.h>
#include <libcfs/libcfs.h>
Defines
#define DEBUG_SUBSYSTEM S_LNET
#define cfs_cap_pack(cap) (cap)
#define cfs_cap_unpack(cap) (cap)
Functions
void cfs_cap_raise (cfs_cap_t cap)
void cfs_cap_lower (cfs_cap_t cap)
int cfs_cap_raised (cfs_cap_t cap)
static void cfs_kernel_cap_pack (kernel_cap_t kcap, cfs_cap_t *cap)
static void cfs_kernel_cap_unpack (kernel_cap_t *kcap, cfs_cap_t cap)
cfs_cap_t cfs_curproc_cap_pack (void)
void cfs_curproc_cap_unpack (cfs_cap_t cap)
int cfs_capable (cfs_cap_t cap)
static int cfs_access_process_vm (struct task_struct *tsk, struct mm_struct *mm, unsigned long addr, void *buf, int len, int write)
int cfs_get_environ (const char *key, char *value, int *val_len)
Define Documentation
#define cfs_cap_pack (cap) (cap)
Definition at line 59 of file linux-curproc.c.
Referenced by cfs_kernel_cap_pack().
#define cfs_cap_unpack (cap) (cap)
Definition at line 60 of file linux-curproc.c.
Referenced by cfs_cap_lower(), cfs_cap_raise(), cfs_cap_raised(), cfs_capable(), and cfs_kernel_cap_unpack().
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 49 of file linux-curproc.c.
Function Documentation
static int cfs_access_process_vm (struct task_struct * tsk, struct mm_struct * mm, unsigned long addr, void * buf, int len, int write) [static]
Definition at line 133 of file linux-curproc.c.
Referenced by cfs_get_environ().
void cfs_cap_lower (cfs_cap_t cap)
Definition at line 71 of file linux-curproc.c.
References cfs_cap_unpack.
Referenced by llog_add(), llog_create(), llog_declare_add(), llog_declare_create(), llog_declare_write_rec(), llog_open(), and llog_write_rec().
void cfs_cap_raise (cfs_cap_t cap)
Definition at line 62 of file linux-curproc.c.
References cfs_cap_unpack.
Referenced by llog_add(), llog_create(), llog_declare_add(), llog_declare_create(), llog_declare_write_rec(), llog_open(), and llog_write_rec().
int cfs_cap_raised (cfs_cap_t cap)
Definition at line 80 of file linux-curproc.c.
References cfs_cap_unpack.
Referenced by llog_add(), llog_create(), llog_declare_add(), llog_declare_create(), llog_declare_write_rec(), llog_open(), and llog_write_rec().
int cfs_capable (cfs_cap_t cap)
Definition at line 128 of file linux-curproc.c.
References cfs_cap_unpack.
Referenced by echo_client_iocontrol(), ll_dir_ioctl(), ll_fid2path(), ll_getparent(), ll_hsm_state_set(), ll_lov_setea(), ll_setattr_raw(), obd_class_ioctl(), osc_page_submit(), quotactl_ioctl(), and xattr_type_filter().
cfs_cap_t cfs_curproc_cap_pack (void)
Definition at line 112 of file linux-curproc.c.
References cfs_kernel_cap_pack().
Referenced by __mdc_pack_body(), ll_dir_setdirstripe(), ll_new_node(), ll_prep_md_op_data(), lmv_link(), lmv_rename(), lmv_unlink(), mdc_open_pack(), mdc_setattr_pack_rec(), mdc_xattr_common(), and sptlrpc_pack_user_desc().
void cfs_curproc_cap_unpack (cfs_cap_t cap)
Definition at line 119 of file linux-curproc.c.
References cfs_kernel_cap_unpack().
int cfs_get_environ (const char * key, char * value, int * val_len)
Definition at line 187 of file linux-curproc.c.
References cfs_access_process_vm(), ENTRY, GOTO, LASSERT, min_t, RETURN, and unlikely.
Referenced by lustre_get_jobid().
static void cfs_kernel_cap_pack (kernel_cap_t kcap, cfs_cap_t * cap) [static]
Definition at line 85 of file linux-curproc.c.
References cfs_cap_pack.
Referenced by cfs_curproc_cap_pack().
static void cfs_kernel_cap_unpack (kernel_cap_t * kcap, cfs_cap_t cap) [static]
Definition at line 99 of file linux-curproc.c.
References cfs_cap_unpack.
Referenced by cfs_curproc_cap_unpack().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.