Lustre: libcfs/include/libcfs/linux/linux-crypto.h File Reference
libcfs/include/libcfs/linux/linux-crypto.h File Reference
Functions
int cfs_crypto_crc32_register (void)
Linux crypto hash specific functions.
void cfs_crypto_crc32_unregister (void)
int cfs_crypto_adler32_register (void)
Functions for start/stop shash adler32 algorithm.
void cfs_crypto_adler32_unregister (void)
int cfs_crypto_crc32_pclmul_register (void)
Functions for start/stop shash crc32 pclmulqdq.
void cfs_crypto_crc32_pclmul_unregister (void)
int cfs_crypto_crc32c_pclmul_register (void)
Functions for start/stop shash crc32c pclmulqdq.
void cfs_crypto_crc32c_pclmul_unregister (void)
Function Documentation
int cfs_crypto_adler32_register (void)
Functions for start/stop shash adler32 algorithm.
Definition at line 127 of file linux-crypto-adler.c.
References alg.
Referenced by cfs_crypto_register().
void cfs_crypto_adler32_unregister (void)
Definition at line 132 of file linux-crypto-adler.c.
References alg.
Referenced by cfs_crypto_unregister().
int cfs_crypto_crc32_pclmul_register (void)
Functions for start/stop shash crc32 pclmulqdq.
Definition at line 179 of file linux-crypto-crc32pclmul.c.
References CDEBUG, D_INFO, and X86_FEATURE_PCLMULQDQ.
Referenced by cfs_crypto_register().
void cfs_crypto_crc32_pclmul_unregister (void)
Definition at line 189 of file linux-crypto-crc32pclmul.c.
Referenced by cfs_crypto_unregister().
int cfs_crypto_crc32_register (void)
Linux crypto hash specific functions.
Functions for start/stop shash CRC32 algorithm.
Definition at line 140 of file linux-crypto-crc32.c.
References alg.
Referenced by cfs_crypto_register().
void cfs_crypto_crc32_unregister (void)
Definition at line 145 of file linux-crypto-crc32.c.
References alg.
Referenced by cfs_crypto_unregister().
int cfs_crypto_crc32c_pclmul_register (void)
Functions for start/stop shash crc32c pclmulqdq.
Definition at line 143 of file linux-crypto-crc32c-pclmul.c.
References alg, CDEBUG, D_INFO, and X86_FEATURE_XMM4_2.
Referenced by cfs_crypto_register().
void cfs_crypto_crc32c_pclmul_unregister (void)
Definition at line 152 of file linux-crypto-crc32c-pclmul.c.
References alg.
Referenced by cfs_crypto_unregister().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.