Lustre: libcfs/libcfs/linux/linux-debug.c File Reference
libcfs/libcfs/linux/linux-debug.c File Reference
#include <linux/module.h>
#include <linux/kmod.h>
#include <linux/notifier.h>
#include <linux/kernel.h>
#include <linux/mm.h>
#include <linux/string.h>
#include <linux/stat.h>
#include <linux/errno.h>
#include <linux/unistd.h>
#include <linux/interrupt.h>
#include <asm/uaccess.h>
#include <linux/completion.h>
#include <linux/fs.h>
#include <linux/miscdevice.h>
#include <linux/version.h>
#include <libcfs/libcfs.h>
#include "tracefile.h"
#include <linux/kallsyms.h>
Defines
#define DEBUG_SUBSYSTEM S_LNET
Functions
void libcfs_run_debug_log_upcall (char *file)
Upcall function once a Lustre log has been dumped.
void libcfs_run_upcall (char **argv)
void libcfs_run_lbug_upcall (struct libcfs_debug_msg_data *msgdata)
void lbug_with_loc (struct libcfs_debug_msg_data *msgdata)
static void libcfs_call_trace (struct task_struct *tsk)
void libcfs_debug_dumpstack (struct task_struct *tsk)
struct task_struct * libcfs_current (void)
static int panic_notifier (struct notifier_block *self, unsigned long unused1, void *unused2)
void libcfs_register_panic_notifier (void)
void libcfs_unregister_panic_notifier (void)
Variables
char lnet_upcall [1024] = "/usr/lib/lustre/lnet_upcall"
char lnet_debug_log_upcall [1024] = "/usr/lib/lustre/lnet_debug_log_upcall"
The path of debug log dump upcall script.
static struct notifier_block libcfs_panic_notifier
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 63 of file linux-debug.c.
Function Documentation
void lbug_with_loc (struct libcfs_debug_msg_data * msgdata)
Definition at line 164 of file linux-debug.c.
References libcfs_catastrophe, libcfs_debug_dumplog(), libcfs_debug_dumpstack, libcfs_debug_msg(), libcfs_panic_on_lbug, and libcfs_run_lbug_upcall().
static void libcfs_call_trace (struct task_struct * tsk) [static]
Definition at line 244 of file linux-debug.c.
References CWARN.
Referenced by libcfs_debug_dumpstack().
struct task_struct* libcfs_current (void) [read]
Definition at line 267 of file linux-debug.c.
References CWARN.
void libcfs_debug_dumpstack (struct task_struct * tsk)
Definition at line 254 of file linux-debug.c.
References libcfs_call_trace(), and printk.
void libcfs_register_panic_notifier (void)
Definition at line 305 of file linux-debug.c.
Referenced by libcfs_debug_init().
void libcfs_run_debug_log_upcall (char * file)
Upcall function once a Lustre log has been dumped.
Parameters:
file path of the dumped log
Definition at line 79 of file linux-debug.c.
References CDEBUG, CERROR, D_HA, ENTRY, EXIT, LASSERTF, and lnet_debug_log_upcall.
Referenced by libcfs_debug_dumplog_internal().
void libcfs_run_lbug_upcall (struct libcfs_debug_msg_data * msgdata)
Definition at line 145 of file linux-debug.c.
References buf, ENTRY, libcfs_run_upcall(), libcfs_debug_msg_data::msg_file, libcfs_debug_msg_data::msg_fn, and libcfs_debug_msg_data::msg_line.
Referenced by lbug_with_loc().
void libcfs_run_upcall (char ** argv)
Definition at line 109 of file linux-debug.c.
References CDEBUG, CERROR, D_HA, ENTRY, LASSERT, and lnet_upcall.
Referenced by libcfs_run_lbug_upcall().
void libcfs_unregister_panic_notifier (void)
Definition at line 310 of file linux-debug.c.
Referenced by libcfs_debug_cleanup().
static int panic_notifier (struct notifier_block * self, unsigned long unused1, void * unused2) [static]
Definition at line 273 of file linux-debug.c.
References cfs_trace_debug_print(), current_pid, libcfs_debug_dumplog_internal(), and libcfs_panic_in_progress.
Variable Documentation
struct notifier_block libcfs_panic_notifier [static]
Initial value:
 {
        notifier_call :     panic_notifier,
        next :              NULL,
        priority :          10000
}
Definition at line 299 of file linux-debug.c.
char lnet_debug_log_upcall[1024] = "/usr/lib/lustre/lnet_debug_log_upcall"
The path of debug log dump upcall script.
Definition at line 72 of file linux-debug.c.
Referenced by libcfs_run_debug_log_upcall().
char lnet_upcall[1024] = "/usr/lib/lustre/lnet_upcall"
Definition at line 71 of file linux-debug.c.
Referenced by libcfs_run_upcall().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.