Lustre: libcfs/libcfs/linux/linux-prim.c File Reference
libcfs/libcfs/linux/linux-prim.c File Reference
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/fs_struct.h>
#include <linux/sched.h>
#include <libcfs/libcfs.h>
Defines
#define DEBUG_SUBSYSTEM S_LNET
Functions
void cfs_init_timer (struct timer_list *t)
void cfs_timer_init (struct timer_list *t, cfs_timer_func_t *func, void *arg)
void cfs_timer_arm (struct timer_list *t, cfs_time_t deadline)
void cfs_timer_disarm (struct timer_list *t)
int cfs_timer_is_armed (struct timer_list *t)
cfs_time_t cfs_timer_deadline (struct timer_list *t)
sigset_t cfs_block_allsigs (void)
sigset_t cfs_block_sigs (unsigned long sigs)
sigset_t cfs_block_sigsinv (unsigned long sigs)
void cfs_restore_sigs (sigset_t old)
void cfs_clear_sigpending (void)
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 37 of file linux-prim.c.
Function Documentation
sigset_t cfs_block_allsigs (void)
Definition at line 88 of file linux-prim.c.
Referenced by cfs_wi_scheduler(), kgnilnd_dgram_mover(), kgnilnd_dgram_waitq(), kgnilnd_reaper(), kgnilnd_ruhroh_thread(), kgnilnd_scheduler(), kiblnd_connd(), kiblnd_failover_thread(), kiblnd_scheduler(), ksocknal_connd(), ksocknal_reaper(), ksocknal_scheduler(), lnet_acceptor(), lnet_ping(), lnet_ping_md_unlink(), lnet_router_checker(), and stt_timer_main().
sigset_t cfs_block_sigs (unsigned long sigs)
Definition at line 102 of file linux-prim.c.
sigset_t cfs_block_sigsinv (unsigned long sigs)
Definition at line 117 of file linux-prim.c.
Referenced by ll_fault(), ll_page_mkwrite0(), and ptlrpc_set_wait().
void cfs_clear_sigpending (void)
Definition at line 144 of file linux-prim.c.
void cfs_init_timer (struct timer_list * t)
Definition at line 49 of file linux-prim.c.
Referenced by class_attach().
void cfs_restore_sigs (sigset_t old)
Definition at line 132 of file linux-prim.c.
Referenced by ll_fault(), ll_page_mkwrite0(), lnet_ping(), lnet_ping_md_unlink(), and ptlrpc_set_wait().
void cfs_timer_arm (struct timer_list * t, cfs_time_t deadline)
Definition at line 63 of file linux-prim.c.
Referenced by osp_statfs_interpret(), and ptlrpc_at_set_timer().
cfs_time_t cfs_timer_deadline (struct timer_list * t)
Definition at line 81 of file linux-prim.c.
void cfs_timer_disarm (struct timer_list * t)
Definition at line 69 of file linux-prim.c.
Referenced by osp_precreate_fini(), osp_statfs_need_now(), osp_statfs_update(), ptlrpc_at_set_timer(), ptlrpc_service_del_atimer(), and ptlrpc_service_free().
void cfs_timer_init (struct timer_list * t, cfs_timer_func_t * func, void * arg)
Definition at line 55 of file linux-prim.c.
Referenced by ldlm_setup(), osp_init_precreate(), and ptlrpc_service_part_init().
int cfs_timer_is_armed (struct timer_list * t)
Definition at line 75 of file linux-prim.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.