Lustre: libcfs/include/libcfs/linux/linux-mem.h File Reference
libcfs/include/libcfs/linux/linux-mem.h File Reference
#include <linux/mm.h>
#include <linux/vmalloc.h>
#include <linux/pagemap.h>
#include <linux/slab.h>
Data Structures
struct shrink_control
struct shrinker_var
Defines
#define SHRINKER_ARGS(sc, nr_to_scan, gfp_mask) int nr_to_scan, gfp_t gfp_mask
#define HAVE_SHRINK_CONTROL_STRUCT 1
#define shrink_param(sc, var) (var)
#define DEF_SHRINKER_VAR(name, shrinker, count, scan) struct shrinker_var name = { .shrink = shrinker }
#define SHRINK_STOP (~0UL)
Functions
static struct shrinker * set_shrinker (int seek, struct shrinker_var *var)
static void remove_shrinker (struct shrinker *shrinker)
Define Documentation
#define DEF_SHRINKER_VAR (name, shrinker, count, scan) struct shrinker_var name = { .shrink = shrinker }
Definition at line 99 of file linux-mem.h.
Referenced by lu_global_init(), osc_init(), and sptlrpc_enc_pool_init().
#define HAVE_SHRINK_CONTROL_STRUCT 1
Definition at line 82 of file linux-mem.h.
#define shrink_param (sc, var) (var)
Definition at line 83 of file linux-mem.h.
Referenced by enc_pools_shrink(), lu_cache_shrink(), and osc_cache_shrink().
#define SHRINK_STOP (~0UL)
Definition at line 101 of file linux-mem.h.
Referenced by lu_cache_shrink_scan(), and osc_cache_shrink_scan().
#define SHRINKER_ARGS (sc, nr_to_scan, gfp_mask) int nr_to_scan, gfp_t gfp_mask
Definition at line 78 of file linux-mem.h.
Function Documentation
static void remove_shrinker (struct shrinker * shrinker) [inline, static]
Definition at line 127 of file linux-mem.h.
Referenced by lu_global_fini(), osc_exit(), and sptlrpc_enc_pool_fini().
static struct shrinker* set_shrinker (int seek, struct shrinker_var * var) [static, read]
Definition at line 105 of file linux-mem.h.
References shrinker_var::shrink.
Referenced by lu_global_init(), osc_init(), and sptlrpc_enc_pool_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.