Lustre: libcfs/libcfs/linux/linux-crypto-adler.c File Reference
libcfs/libcfs/linux/linux-crypto-adler.c File Reference
#include <linux/module.h>
#include <linux/zutil.h>
#include <libcfs/linux/linux-crypto.h>
#include <crypto/internal/hash.h>
Defines
#define CHKSUM_BLOCK_SIZE 1
#define CHKSUM_DIGEST_SIZE 4
Functions
static int adler32_cra_init (struct crypto_tfm *tfm)
static int adler32_setkey (struct crypto_shash *hash, const u8 *key, unsigned int keylen)
static int adler32_init (struct shash_desc *desc)
static int adler32_update (struct shash_desc *desc, const u8 *data, unsigned int len)
static int __adler32_finup (u32 *cksump, const u8 *data, unsigned int len, u8 *out)
static int adler32_finup (struct shash_desc *desc, const u8 *data, unsigned int len, u8 *out)
static int adler32_final (struct shash_desc *desc, u8 *out)
static int adler32_digest (struct shash_desc *desc, const u8 *data, unsigned int len, u8 *out)
int cfs_crypto_adler32_register (void)
Functions for start/stop shash adler32 algorithm.
void cfs_crypto_adler32_unregister (void)
Variables
static struct shash_alg alg
Define Documentation
#define CHKSUM_BLOCK_SIZE 1
Definition at line 37 of file linux-crypto-adler.c.
#define CHKSUM_DIGEST_SIZE 4
Definition at line 38 of file linux-crypto-adler.c.
Function Documentation
static int __adler32_finup (u32 * cksump, const u8 * data, unsigned int len, u8 * out) [static]
Definition at line 80 of file linux-crypto-adler.c.
Referenced by adler32_digest(), and adler32_finup().
static int adler32_cra_init (struct crypto_tfm * tfm) [static]
Definition at line 40 of file linux-crypto-adler.c.
static int adler32_digest (struct shash_desc * desc, const u8 * data, unsigned int len, u8 * out) [static]
Definition at line 101 of file linux-crypto-adler.c.
References __adler32_finup().
static int adler32_final (struct shash_desc * desc, u8 * out) [static]
Definition at line 93 of file linux-crypto-adler.c.
static int adler32_finup (struct shash_desc * desc, const u8 * data, unsigned int len, u8 * out) [static]
Definition at line 87 of file linux-crypto-adler.c.
References __adler32_finup().
static int adler32_init (struct shash_desc * desc) [static]
Definition at line 62 of file linux-crypto-adler.c.
static int adler32_setkey (struct crypto_shash * hash, const u8 * key, unsigned int keylen) [static]
Definition at line 49 of file linux-crypto-adler.c.
static int adler32_update (struct shash_desc * desc, const u8 * data, unsigned int len) [static]
Definition at line 72 of file linux-crypto-adler.c.
int cfs_crypto_adler32_register (void)
Functions for start/stop shash adler32 algorithm.
Definition at line 127 of file linux-crypto-adler.c.
References alg.
Referenced by cfs_crypto_register().
void cfs_crypto_adler32_unregister (void)
Definition at line 132 of file linux-crypto-adler.c.
References alg.
Referenced by cfs_crypto_unregister().
Variable Documentation
struct shash_alg alg [static]
Initial value:
 {
        .setkey         = adler32_setkey,
        .init           = adler32_init,
        .update         = adler32_update,
        .final          = adler32_final,
        .finup          = adler32_finup,
        .digest         = adler32_digest,
        .descsize       = sizeof(u32),
        .digestsize     = CHKSUM_DIGEST_SIZE,
        .base           = {
                .cra_name               = "adler32",
                .cra_driver_name        = "adler32-zlib",
                .cra_priority           = 100,
                .cra_blocksize          = CHKSUM_BLOCK_SIZE,
                .cra_ctxsize            = sizeof(u32),
                .cra_module             = THIS_MODULE,
                .cra_init               = adler32_cra_init,
        }
}
Definition at line 107 of file linux-crypto-adler.c.
Referenced by cfs_crypto_adler32_register(), cfs_crypto_adler32_unregister(), and sptlrpc_parse_flavor().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.