Lustre: libcfs/libcfs/linux/linux-tracefile.c File Reference
libcfs/libcfs/linux/linux-tracefile.c File Reference
#include <libcfs/libcfs.h>
#include "tracefile.h"
Defines
#define DEBUG_SUBSYSTEM S_LNET
#define LUSTRE_TRACEFILE_PRIVATE
Functions
static DECLARE_RWSEM (cfs_tracefile_sem)
int cfs_tracefile_init_arch ()
void cfs_tracefile_fini_arch ()
void cfs_tracefile_read_lock ()
void cfs_tracefile_read_unlock ()
void cfs_tracefile_write_lock ()
void cfs_tracefile_write_unlock ()
enum cfs_trace_buf_type cfs_trace_buf_idx_get ()
int cfs_trace_lock_tcd (struct cfs_trace_cpu_data *tcd, int walking) __acquires(&tcd->tcd_lock)
void cfs_trace_unlock_tcd (struct cfs_trace_cpu_data *tcd, int walking) __releases(&tcd->tcd_lock)
int cfs_tcd_owns_tage (struct cfs_trace_cpu_data *tcd, struct cfs_trace_page *tage)
void cfs_set_ptldebug_header (struct ptldebug_header *header, struct libcfs_debug_msg_data *msgdata, unsigned long stack)
static char * dbghdr_to_err_string (struct ptldebug_header *hdr)
static char * dbghdr_to_info_string (struct ptldebug_header *hdr)
void cfs_print_to_console (struct ptldebug_header *hdr, int mask, const char *buf, int len, const char *file, const char *fn)
int cfs_trace_max_debug_mb (void)
Variables
static unsigned int pages_factor [CFS_TCD_TYPE_MAX]
char * cfs_trace_console_buffers [NR_CPUS][CFS_TCD_TYPE_MAX]
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 37 of file linux-tracefile.c.
#define LUSTRE_TRACEFILE_PRIVATE
Definition at line 38 of file linux-tracefile.c.
Function Documentation
void cfs_print_to_console (struct ptldebug_header * hdr, int mask, const char * buf, int len, const char * file, const char * fn)
Definition at line 238 of file linux-tracefile.c.
References D_CONSOLE, D_EMERG, D_ERROR, D_WARNING, dbghdr_to_err_string(), dbghdr_to_info_string(), libcfs_printk, ptldebug_header::ph_extern_pid, ptldebug_header::ph_line_num, ptldebug_header::ph_pid, and printk.
Referenced by cfs_trace_assertion_failed(), cfs_trace_debug_print(), and libcfs_debug_vmsg2().
void cfs_set_ptldebug_header (struct ptldebug_header * header, struct libcfs_debug_msg_data * msgdata, unsigned long stack)
Definition at line 191 of file linux-tracefile.c.
References cfs_trace_buf_idx_get(), libcfs_debug_msg_data::msg_line, libcfs_debug_msg_data::msg_mask, libcfs_debug_msg_data::msg_subsys, ptldebug_header::ph_cpu_id, ptldebug_header::ph_extern_pid, ptldebug_header::ph_line_num, ptldebug_header::ph_mask, ptldebug_header::ph_pid, ptldebug_header::ph_sec, ptldebug_header::ph_stack, ptldebug_header::ph_subsys, ptldebug_header::ph_type, and ptldebug_header::ph_usec.
Referenced by cfs_trace_assertion_failed(), and libcfs_debug_vmsg2().
int cfs_tcd_owns_tage (struct cfs_trace_cpu_data * tcd, struct cfs_trace_page * tage)
Definition at line 180 of file linux-tracefile.c.
References cfs_trace_page::cpu.
enum cfs_trace_buf_type cfs_trace_buf_idx_get (void)
Definition at line 135 of file linux-tracefile.c.
References CFS_TCD_TYPE_IRQ, CFS_TCD_TYPE_PROC, and CFS_TCD_TYPE_SOFTIRQ.
Referenced by cfs_set_ptldebug_header(), cfs_trace_get_console_buffer(), and cfs_trace_get_tcd().
int cfs_trace_lock_tcd (struct cfs_trace_cpu_data * tcd, int walking)
Definition at line 151 of file linux-tracefile.c.
References __LASSERT, CFS_TCD_TYPE_IRQ, CFS_TCD_TYPE_MAX, CFS_TCD_TYPE_SOFTIRQ, and unlikely.
Referenced by cfs_trace_get_tcd().
int cfs_trace_max_debug_mb (void)
Definition at line 268 of file linux-tracefile.c.
References MAX.
Referenced by cfs_trace_set_debug_mb(), and libcfs_debug_init().
void cfs_trace_unlock_tcd (struct cfs_trace_cpu_data * tcd, int walking)
Definition at line 166 of file linux-tracefile.c.
References __LASSERT, CFS_TCD_TYPE_IRQ, CFS_TCD_TYPE_MAX, CFS_TCD_TYPE_SOFTIRQ, and unlikely.
Referenced by cfs_trace_put_tcd().
void cfs_tracefile_fini_arch (void)
Definition at line 97 of file linux-tracefile.c.
References cfs_trace_console_buffers, and cfs_trace_data.
Referenced by cfs_trace_cleanup(), and cfs_tracefile_init_arch().
int cfs_tracefile_init_arch (void)
Definition at line 54 of file linux-tracefile.c.
References cfs_tcd_for_each, CFS_TCD_TYPE_MAX, CFS_TRACE_CONSOLE_BUFFER_SIZE, cfs_trace_console_buffers, cfs_trace_data, cfs_tracefile_fini_arch(), pages_factor, and printk.
Referenced by cfs_tracefile_init().
void cfs_tracefile_read_lock (void)
Definition at line 115 of file linux-tracefile.c.
Referenced by cfs_trace_get_debug_mb(), and tracefiled().
void cfs_tracefile_read_unlock (void)
Definition at line 120 of file linux-tracefile.c.
Referenced by cfs_trace_get_debug_mb(), and tracefiled().
void cfs_tracefile_write_lock (void)
Definition at line 125 of file linux-tracefile.c.
Referenced by cfs_trace_daemon_command(), cfs_trace_set_debug_mb(), and cfs_tracefile_dump_all_pages().
void cfs_tracefile_write_unlock (void)
Definition at line 130 of file linux-tracefile.c.
Referenced by cfs_trace_daemon_command(), cfs_trace_set_debug_mb(), and cfs_tracefile_dump_all_pages().
static char* dbghdr_to_err_string (struct ptldebug_header * hdr) [static]
Definition at line 213 of file linux-tracefile.c.
References ptldebug_header::ph_subsys, S_LND, and S_LNET.
Referenced by cfs_print_to_console().
static char* dbghdr_to_info_string (struct ptldebug_header * hdr) [static]
Definition at line 226 of file linux-tracefile.c.
References ptldebug_header::ph_subsys, S_LND, and S_LNET.
Referenced by cfs_print_to_console().
static DECLARE_RWSEM (cfs_tracefile_sem) [static]
Variable Documentation
char* cfs_trace_console_buffers[NR_CPUS][CFS_TCD_TYPE_MAX]
Definition at line 50 of file linux-tracefile.c.
Referenced by cfs_tracefile_fini_arch(), and cfs_tracefile_init_arch().
unsigned int pages_factor[CFS_TCD_TYPE_MAX] [static]
Initial value:
 {
        80,
        10,
        10
}
Definition at line 44 of file linux-tracefile.c.
Referenced by cfs_tracefile_init_arch().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.