Lustre: libcfs/libcfs/linux/linux-crypto.c File Reference
libcfs/libcfs/linux/linux-crypto.c File Reference
#include <crypto/hash.h>
#include <linux/scatterlist.h>
#include <libcfs/libcfs.h>
#include <libcfs/libcfs_crypto.h>
#include <libcfs/linux/linux-crypto.h>
Functions
static const char * crypto_ahash_alg_name (struct crypto_ahash *tfm)
static const char * crypto_ahash_driver_name (struct crypto_ahash *tfm)
static int cfs_crypto_hash_alloc (enum cfs_crypto_hash_alg hash_alg, const struct cfs_crypto_hash_type **type, struct ahash_request **req, unsigned char *key, unsigned int key_len)
Initialize the state descriptor for the specified hash algorithm.
int cfs_crypto_hash_digest (enum cfs_crypto_hash_alg hash_alg, const void *buf, unsigned int buf_len, unsigned char *key, unsigned int key_len, unsigned char *hash, unsigned int *hash_len)
Calculate hash digest for the passed buffer.
struct cfs_crypto_hash_desc * cfs_crypto_hash_init (enum cfs_crypto_hash_alg hash_alg, unsigned char *key, unsigned int key_len)
Allocate and initialize desriptor for hash algorithm.
int cfs_crypto_hash_update_page (struct cfs_crypto_hash_desc *hdesc, struct page *page, unsigned int offset, unsigned int len)
Update hash digest computed on data within the given page.
int cfs_crypto_hash_update (struct cfs_crypto_hash_desc *hdesc, const void *buf, unsigned int buf_len)
Update hash digest computed on the specified data.
int cfs_crypto_hash_final (struct cfs_crypto_hash_desc *hdesc, unsigned char *hash, unsigned int *hash_len)
Finish hash calculation, copy hash digest to buffer, clean up hash descriptor.
static void cfs_crypto_performance_test (enum cfs_crypto_hash_alg hash_alg)
Compute the speed of specified hash function.
int cfs_crypto_hash_speed (enum cfs_crypto_hash_alg hash_alg)
hash speed in Mbytes per second for valid hash algorithm
static int cfs_crypto_test_hashes (void)
Run the performance test for all hash algorithms.
int cfs_crypto_register (void)
Register available hash functions.
void cfs_crypto_unregister (void)
Unregister previously registered hash functions.
Variables
static int cfs_crypto_hash_speeds [CFS_HASH_ALG_MAX]
Array of hash algorithm speed in MByte per second.
static int adler32
Function Documentation
static int cfs_crypto_hash_alloc (enum cfs_crypto_hash_alg hash_alg, const struct cfs_crypto_hash_type ** type, struct ahash_request ** req, unsigned char * key, unsigned int key_len) [static]
Initialize the state descriptor for the specified hash algorithm.
An internal routine to allocate the hash-specific state in hdesc for use with cfs_crypto_hash_digest() to compute the hash of a single message, though possibly in multiple chunks. The descriptor internal state should be freed with cfs_crypto_hash_final().
Parameters:
[in] hash_alg hash algorithm id (CFS_HASH_ALG_*)
[out] type pointer to the hash description in hash_types[] array
[in,out] req ahash request to be initialized
[in] key initial hash value/state, NULL to use default value
[in] key_len length of key
Return values:
0 on success
negative errno on failure
Definition at line 72 of file linux-crypto.c.
References CDEBUG, cfs_crypto_hash_speeds, cfs_crypto_hash_type(), CFS_HASH_ALG_MAX, crypto_ahash_alg_name(), crypto_ahash_driver_name(), CWARN, and D_INFO.
Referenced by cfs_crypto_hash_digest(), and cfs_crypto_hash_init().
int cfs_crypto_hash_digest (enum cfs_crypto_hash_alg hash_alg, const void * buf, unsigned int buf_len, unsigned char * key, unsigned int key_len, unsigned char * hash, unsigned int * hash_len)
Calculate hash digest for the passed buffer.
This should be used when computing the hash on a single contiguous buffer. It combines the hash initialization, computation, and cleanup.
Parameters:
[in] hash_alg id of hash algorithm (CFS_HASH_ALG_*)
[in] buf data buffer on which to compute hash
[in] buf_len length of buf in bytes
[in] key initial value/state for algorithm, if key = NULL use default initial value
[in] key_len length of key in bytes
[out] hash pointer to computed hash value, if hash = NULL then hash_len is to digest size in bytes, retval -ENOSPC
[in,out] hash_len size of hash buffer
Return values:
-EINVAL buf, buf_len, hash_len, hash_alg invalid
-ENOENT hash_alg is unsupported
-ENOSPC hash is NULL, or hash_len less than digest size
0 for success
negative errno for other errors from lower layers.
Definition at line 152 of file linux-crypto.c.
References cfs_crypto_hash_alloc(), and cfs_crypto_hash_type::cht_size.
Referenced by lustre_msg_calc_cksum(), plain_authorize(), and plain_ctx_verify().
int cfs_crypto_hash_final (struct cfs_crypto_hash_desc * hdesc, unsigned char * hash, unsigned int * hash_len)
Finish hash calculation, copy hash digest to buffer, clean up hash descriptor.
Parameters:
[in] hdesc hash descriptor
[out] hash pointer to hash buffer to store hash digest
[in,out] hash_len pointer to hash buffer size, if hash == NULL or hash_len == NULL only free hdesc instead of computing the hash
Return values:
0 for success
-EOVERFLOW if hash_len is too small for the hash digest
negative errno for other errors from lower layers
Definition at line 280 of file linux-crypto.c.
References size.
Referenced by cfs_crypto_performance_test(), osc_checksum_bulk(), sptlrpc_get_bulk_checksum(), and tgt_checksum_bulk().
struct cfs_crypto_hash_desc* cfs_crypto_hash_init (enum cfs_crypto_hash_alg hash_alg, unsigned char * key, unsigned int key_len) [read]
Allocate and initialize desriptor for hash algorithm.
This should be used to initialize a hash descriptor for multiple calls to a single hash function when computing the hash across multiple separate buffers or pages using cfs_crypto_hash_update{,_page}().
The hash descriptor should be freed with cfs_crypto_hash_final().
Parameters:
[in] hash_alg algorithm id (CFS_HASH_ALG_*)
[in] key initial value/state for algorithm, if key = NULL use default initial value
[in] key_len length of key in bytes
Return values:
pointer to descriptor of hash instance
ERR_PTR(errno) in case of error
Definition at line 204 of file linux-crypto.c.
References cfs_crypto_hash_alloc().
Referenced by cfs_crypto_performance_test(), osc_checksum_bulk(), sptlrpc_get_bulk_checksum(), and tgt_checksum_bulk().
int cfs_crypto_hash_speed (enum cfs_crypto_hash_alg hash_alg)
hash speed in Mbytes per second for valid hash algorithm
Return the performance of the specified hash_alg that was previously computed using cfs_crypto_performance_test().
Parameters:
[in] hash_alg hash algorithm id (CFS_HASH_ALG_*)
Return values:
positive speed of the hash function in MB/s
-ENOENT if hash_alg is unsupported
negative errno if hash_alg speed is unavailable
Definition at line 393 of file linux-crypto.c.
References cfs_crypto_hash_speeds, and CFS_HASH_ALG_MAX.
Referenced by cksum_type_pack(), cksum_types_supported_client(), and cksum_types_supported_server().
int cfs_crypto_hash_update (struct cfs_crypto_hash_desc * hdesc, const void * buf, unsigned int buf_len)
Update hash digest computed on the specified data.
Parameters:
[in] hdesc hash state descriptor
[in] buf data buffer on which to compute the hash
[in] buf_len length of on which to compute hash
Return values:
0 for success
negative errno on failure
Definition at line 254 of file linux-crypto.c.
int cfs_crypto_hash_update_page (struct cfs_crypto_hash_desc * hdesc, struct page * page, unsigned int offset, unsigned int len)
Update hash digest computed on data within the given page.
Parameters:
[in] hdesc hash state descriptor
[in] page data page on which to compute the hash
[in] offset offset within page at which to start hash
[in] len length of data on which to compute hash
Return values:
0 for success
negative errno on failure
Definition at line 229 of file linux-crypto.c.
Referenced by cfs_crypto_performance_test(), osc_checksum_bulk(), sptlrpc_get_bulk_checksum(), and tgt_checksum_bulk().
static void cfs_crypto_performance_test (enum cfs_crypto_hash_alg hash_alg) [static]
Compute the speed of specified hash function.
Run a speed test on the given hash algorithm on buffer of the given size. The speed is stored internally in the cfs_crypto_hash_speeds[] array, and is available through the cfs_crypto_hash_speed() function.
Parameters:
[in] hash_alg hash algorithm id (CFS_HASH_ALG_*)
[in] buf data buffer on which to compute the hash
[in] buf_len length of on which to compute hash
Definition at line 319 of file linux-crypto.c.
References buf, CDEBUG, CFS_CRYPTO_HASH_DIGESTSIZE_MAX, cfs_crypto_hash_final(), cfs_crypto_hash_init(), cfs_crypto_hash_name(), cfs_crypto_hash_speeds, cfs_crypto_hash_update_page(), D_CONFIG, D_INFO, end, max, and start.
Referenced by cfs_crypto_test_hashes().
int cfs_crypto_register (void)
Register available hash functions.
Return values:
0
Definition at line 449 of file linux-crypto.c.
References adler32, cfs_crypto_adler32_register(), cfs_crypto_crc32_pclmul_register(), cfs_crypto_crc32_register(), cfs_crypto_crc32c_pclmul_register(), and cfs_crypto_test_hashes().
Referenced by libcfs_init().
static int cfs_crypto_test_hashes (void) [static]
Run the performance test for all hash algorithms.
Run the cfs_crypto_performance_test() benchmark for all of the available hash functions using a 1MB buffer size. This is a reasonable buffer size for Lustre RPCs, even if the actual RPC size is larger or smaller.
Since the setup cost and computation speed of various hash algorithms is a function of the buffer size (and possibly internal contention of offload engines), this speed only represents an estimate of the actual speed under actual usage, but is reasonable for comparing available algorithms.
The actual speeds are available via cfs_crypto_hash_speed() for later comparison.
Return values:
0 on success
-ENOMEM if no memory is available for test buffer
Definition at line 420 of file linux-crypto.c.
References cfs_crypto_performance_test(), and CFS_HASH_ALG_MAX.
Referenced by cfs_crypto_register().
void cfs_crypto_unregister (void)
Unregister previously registered hash functions.
Definition at line 476 of file linux-crypto.c.
References adler32, cfs_crypto_adler32_unregister(), cfs_crypto_crc32_pclmul_unregister(), cfs_crypto_crc32_unregister(), and cfs_crypto_crc32c_pclmul_unregister().
Referenced by libcfs_exit(), and libcfs_init().
static const char* crypto_ahash_alg_name (struct crypto_ahash * tfm) [inline, static]
Definition at line 37 of file linux-crypto.c.
Referenced by cfs_crypto_hash_alloc().
static const char* crypto_ahash_driver_name (struct crypto_ahash * tfm) [inline, static]
Definition at line 44 of file linux-crypto.c.
Referenced by cfs_crypto_hash_alloc().
Variable Documentation
int adler32 [static]
Definition at line 430 of file linux-crypto.c.
Referenced by cfs_crypto_register(), and cfs_crypto_unregister().
int cfs_crypto_hash_speeds[CFS_HASH_ALG_MAX] [static]
Array of hash algorithm speed in MByte per second.
Definition at line 53 of file linux-crypto.c.
Referenced by cfs_crypto_hash_alloc(), cfs_crypto_hash_speed(), and cfs_crypto_performance_test().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.