Lustre: libcfs/libcfs/linux/linux-crypto-crc32.c File Reference
libcfs/libcfs/linux/linux-crypto-crc32.c File Reference
#include <linux/module.h>
#include <linux/crc32.h>
#include <libcfs/linux/linux-crypto.h>
#include <crypto/internal/hash.h>
Defines
#define CHKSUM_BLOCK_SIZE 1
#define CHKSUM_DIGEST_SIZE 4
Functions
static u32 __crc32_le (u32 crc, unsigned char const *p, size_t len)
static int crc32_cra_init (struct crypto_tfm *tfm)
No default init with ~0.
static int crc32_setkey (struct crypto_shash *hash, const u8 *key, unsigned int keylen)
static int crc32_init (struct shash_desc *desc)
static int crc32_update (struct shash_desc *desc, const u8 *data, unsigned int len)
static int __crc32_finup (u32 *crcp, const u8 *data, unsigned int len, u8 *out)
static int crc32_finup (struct shash_desc *desc, const u8 *data, unsigned int len, u8 *out)
static int crc32_final (struct shash_desc *desc, u8 *out)
static int crc32_digest (struct shash_desc *desc, const u8 *data, unsigned int len, u8 *out)
int cfs_crypto_crc32_register (void)
Linux crypto hash specific functions.
void cfs_crypto_crc32_unregister (void)
Variables
static struct shash_alg alg
Define Documentation
#define CHKSUM_BLOCK_SIZE 1
Definition at line 37 of file linux-crypto-crc32.c.
#define CHKSUM_DIGEST_SIZE 4
Definition at line 38 of file linux-crypto-crc32.c.
Function Documentation
static int __crc32_finup (u32 * crcp, const u8 * data, unsigned int len, u8 * out) [static]
Definition at line 93 of file linux-crypto-crc32.c.
References __crc32_le(), and cpu_to_le32.
Referenced by crc32_digest(), and crc32_finup().
static u32 __crc32_le (u32 crc, unsigned char const * p, size_t len) [static]
Definition at line 40 of file linux-crypto-crc32.c.
Referenced by __crc32_finup(), and crc32_update().
int cfs_crypto_crc32_register (void)
Linux crypto hash specific functions.
Functions for start/stop shash CRC32 algorithm.
Definition at line 140 of file linux-crypto-crc32.c.
References alg.
Referenced by cfs_crypto_register().
void cfs_crypto_crc32_unregister (void)
Definition at line 145 of file linux-crypto-crc32.c.
References alg.
Referenced by cfs_crypto_unregister().
static int crc32_cra_init (struct crypto_tfm * tfm) [static]
No default init with ~0.
Definition at line 46 of file linux-crypto-crc32.c.
static int crc32_digest (struct shash_desc * desc, const u8 * data, unsigned int len, u8 * out) [static]
Definition at line 114 of file linux-crypto-crc32.c.
References __crc32_finup().
static int crc32_final (struct shash_desc * desc, u8 * out) [static]
Definition at line 106 of file linux-crypto-crc32.c.
static int crc32_finup (struct shash_desc * desc, const u8 * data, unsigned int len, u8 * out) [static]
Definition at line 100 of file linux-crypto-crc32.c.
References __crc32_finup().
static int crc32_init (struct shash_desc * desc) [static]
Definition at line 74 of file linux-crypto-crc32.c.
static int crc32_setkey (struct crypto_shash * hash, const u8 * key, unsigned int keylen) [static]
Definition at line 61 of file linux-crypto-crc32.c.
static int crc32_update (struct shash_desc * desc, const u8 * data, unsigned int len) [static]
Definition at line 84 of file linux-crypto-crc32.c.
References __crc32_le().
Variable Documentation
struct shash_alg alg [static]
Initial value:
 {
        .setkey         = crc32_setkey,
        .init           = crc32_init,
        .update         = crc32_update,
        .final          = crc32_final,
        .finup          = crc32_finup,
        .digest         = crc32_digest,
        .descsize       = sizeof(u32),
        .digestsize     = CHKSUM_DIGEST_SIZE,
        .base           = {
                .cra_name               = "crc32",
                .cra_driver_name        = "crc32-table",
                .cra_priority           = 100,
                .cra_blocksize          = CHKSUM_BLOCK_SIZE,
                .cra_ctxsize            = sizeof(u32),
                .cra_module             = THIS_MODULE,
                .cra_init               = crc32_cra_init,
        }
}
Definition at line 120 of file linux-crypto-crc32.c.
Referenced by cfs_crypto_crc32_register(), and cfs_crypto_crc32_unregister().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.