Lustre: libcfs/include/libcfs/linux/linux-time.h File Reference
libcfs/include/libcfs/linux/linux-time.h File Reference
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/version.h>
#include <linux/time.h>
#include <asm/div64.h>
#include <linux/jiffies.h>
Defines
#define ONE_BILLION ((u_int64_t)1000000000)
#define ONE_MILLION 1000000
#define cfs_time_current_64 get_jiffies_64
#define CFS_TIME_T "%lu"
#define CFS_DURATION_T "%ld"
Typedefs
typedef struct timespec cfs_fs_time_t
typedef unsigned long cfs_time_t
typedef long cfs_duration_t
typedef cycles_t cfs_cycles_t
Functions
static void cfs_fs_time_usec (cfs_fs_time_t *t, struct timeval *v)
static void cfs_fs_time_nsec (cfs_fs_time_t *t, struct timespec *s)
static unsigned long long __cfs_fs_time_flat (cfs_fs_time_t *t)
static int cfs_time_before (cfs_time_t t1, cfs_time_t t2)
static int cfs_time_beforeq (cfs_time_t t1, cfs_time_t t2)
static cfs_time_t cfs_time_current (void)
static time_t cfs_time_current_sec (void)
static void cfs_fs_time_current (cfs_fs_time_t *t)
static time_t cfs_fs_time_sec (cfs_fs_time_t *t)
static int cfs_fs_time_before (cfs_fs_time_t *t1, cfs_fs_time_t *t2)
static int cfs_fs_time_beforeq (cfs_fs_time_t *t1, cfs_fs_time_t *t2)
static cfs_duration_t cfs_time_seconds (int seconds)
static time_t cfs_duration_sec (cfs_duration_t d)
static void cfs_duration_usec (cfs_duration_t d, struct timeval *s)
static void cfs_duration_nsec (cfs_duration_t d, struct timespec *s)
static __u64 cfs_time_add_64 (__u64 t, __u64 d)
static __u64 cfs_time_shift_64 (int seconds)
static int cfs_time_before_64 (__u64 t1, __u64 t2)
static int cfs_time_beforeq_64 (__u64 t1, __u64 t2)
Define Documentation
#define CFS_DURATION_T "%ld"
Definition at line 263 of file linux-time.h.
Referenced by ldlm_completion_tail(), ldlm_expired_completion_wait(), ptlrpc_at_adj_net_latency(), ptlrpc_at_check_timed(), ptlrpc_at_recv_early_reply(), ptlrpc_expire_one_request(), ptlrpc_pinger_main(), ptlrpc_server_handle_req_in(), ptlrpc_server_handle_request(), and sptlrpc_target_export_check().
#define cfs_time_current_64 get_jiffies_64
Definition at line 235 of file linux-time.h.
Referenced by cb_statfs_update(), cfs_time_shift_64(), import_select_connection(), lod_qos_statfs_update(), lov_fini_statfs(), mdd_changelog_data_store(), mdd_changelog_init(), mdd_changelog_llog_cancel(), mdd_changelog_ns_store(), mdd_changelog_write_header(), mdt_statfs(), obd_statfs(), ofd_statfs_internal(), qmt_adjust_qunit(), qmt_id_lock_glimpse(), qsd_adjust_schedule(), qsd_job_pending(), qsd_req_completion(), qsd_set_edquot(), and qsd_upd_thread().
#define CFS_TIME_T "%lu"
Definition at line 262 of file linux-time.h.
Referenced by _debug_req(), class_disconnect_export_list(), delay_rule_match(), drop_rule_match(), ldlm_expired_completion_wait(), mdc_setattr(), ptlrpc_pinger_main(), ptlrpc_update_export_timer(), sptlrpc_enc_pool_fini(), and sptlrpc_proc_enc_pool_seq_show().
#define ONE_BILLION ((u_int64_t)1000000000)
Definition at line 93 of file linux-time.h.
#define ONE_MILLION 1000000
Definition at line 94 of file linux-time.h.
Referenced by cfs_timeval_sub(), and ptlrpc_svcpt_health_check().
Typedef Documentation
typedef cycles_t cfs_cycles_t
Definition at line 140 of file linux-time.h.
typedef long cfs_duration_t
Definition at line 139 of file linux-time.h.
typedef struct timespec cfs_fs_time_t
Definition at line 112 of file linux-time.h.
typedef unsigned long cfs_time_t
Definition at line 138 of file linux-time.h.
Function Documentation
static unsigned long long __cfs_fs_time_flat (cfs_fs_time_t * t) [inline, static]
Definition at line 128 of file linux-time.h.
References NSEC_PER_SEC.
Referenced by cfs_fs_time_before(), and cfs_fs_time_beforeq().
static void cfs_duration_nsec (cfs_duration_t d, struct timespec * s) [inline, static]
Definition at line 219 of file linux-time.h.
References __u64, and NSEC_PER_SEC.
static time_t cfs_duration_sec (cfs_duration_t d) [inline, static]
Definition at line 188 of file linux-time.h.
Referenced by _kgnilnd_debug_conn(), _kgnilnd_debug_tx(), kgnilnd_check_conn_timeouts_locked(), kgnilnd_check_fma_rx(), kgnilnd_check_peer_timeouts_locked(), kgnilnd_complete_tx(), kgnilnd_conn_seq_show(), kgnilnd_dgram_mover(), kgnilnd_map_fmablk(), kgnilnd_peer_notify(), kgnilnd_process_dgram(), kgnilnd_process_fmaq(), kgnilnd_quiesce_wait(), kgnilnd_reaper(), kgnilnd_reaper_dgram_check(), kgnilnd_reset_stack(), kgnilnd_sendmsg_nolock(), kgnilnd_tx_done(), kgnilnd_tx_should_retry(), kiblnd_check_conns(), kiblnd_check_txs_locked(), kiblnd_query(), ksocknal_check_peer_timeouts(), ksocknal_destroy_conn(), ksocknal_find_connectable_route_locked(), ksocknal_query(), ldlm_cancel_lrur_policy(), lfsck_layout_double_scan_result(), lfsck_layout_dump(), lfsck_layout_master_checkpoint(), lfsck_layout_master_post(), lfsck_layout_slave_checkpoint(), lfsck_layout_slave_post(), lfsck_namespace_checkpoint(), lfsck_namespace_double_scan_one_trace_file(), lfsck_namespace_double_scan_result(), lfsck_namespace_dump(), lfsck_namespace_post(), lnet_notify(), lstcon_rpc_pinger(), osd_scrub_checkpoint(), osd_scrub_dump(), osd_scrub_post(), proc_console_max_delay_cs(), proc_console_min_delay_cs(), proc_lnet_peers(), proc_lnet_routers(), and round_timeout().
static void cfs_duration_usec (cfs_duration_t d, struct timeval * s) [inline, static]
Definition at line 194 of file linux-time.h.
References __u64.
Referenced by lnet_eq_wait_locked(), lprocfs_rd_ir_state(), lstcon_rpc_trans_interpreter(), mgs_ir_notify_complete(), and sfw_get_stats().
static int cfs_fs_time_before (cfs_fs_time_t * t1, cfs_fs_time_t * t2) [inline, static]
Definition at line 172 of file linux-time.h.
References __cfs_fs_time_flat().
static int cfs_fs_time_beforeq (cfs_fs_time_t * t1, cfs_fs_time_t * t2) [inline, static]
Definition at line 177 of file linux-time.h.
References __cfs_fs_time_flat().
static void cfs_fs_time_current (cfs_fs_time_t * t) [inline, static]
Definition at line 162 of file linux-time.h.
Referenced by cfs_fs_timeval(), and cl_time().
static void cfs_fs_time_nsec (cfs_fs_time_t * t, struct timespec * s) [inline, static]
Definition at line 120 of file linux-time.h.
static time_t cfs_fs_time_sec (cfs_fs_time_t * t) [inline, static]
Definition at line 167 of file linux-time.h.
static void cfs_fs_time_usec (cfs_fs_time_t * t, struct timeval * v) [inline, static]
Definition at line 114 of file linux-time.h.
Referenced by cfs_fs_timeval().
static __u64 cfs_time_add_64 (__u64 t, __u64 d) [inline, static]
Definition at line 237 of file linux-time.h.
Referenced by cfs_time_shift_64().
static int cfs_time_before (cfs_time_t t1, cfs_time_t t2) [inline, static]
Definition at line 142 of file linux-time.h.
Referenced by cfs_time_after(), check_unlink_entry(), exp_expired(), ir_state_graduate(), kiblnd_failover_thread(), kiblnd_fmr_pool_map(), kiblnd_pool_alloc_node(), ksocknal_send_keepalive_locked(), ldlm_cancel_aged_policy(), ldlm_namespace_dump(), ll_agl_trigger(), lnet_notify_locked(), lnet_peer_alive_locked(), mgs_ir_init_fs(), ofd_fmd_expire_nolock(), osd_scrub_checkpoint(), osp_statfs_need_update(), ptlrpc_expire_one_request(), and ptlrpc_send_limit_expired().
static int cfs_time_before_64 (__u64 t1, __u64 t2) [inline, static]
Definition at line 248 of file linux-time.h.
Referenced by import_select_connection(), mdd_changelog_data_store(), mdt_statfs(), obd_statfs(), obd_statfs_async(), ofd_statfs_internal(), qmt_adjust_edquot(), qsd_acquire_local(), and qsd_acquire_remote().
static int cfs_time_beforeq (cfs_time_t t1, cfs_time_t t2) [inline, static]
Definition at line 147 of file linux-time.h.
Referenced by cfs_time_aftereq(), lfsck_checkpoint(), and lfsck_namespace_double_scan_one_trace_file().
static int cfs_time_beforeq_64 (__u64 t1, __u64 t2) [inline, static]
Definition at line 253 of file linux-time.h.
Referenced by import_select_connection(), lod_qos_statfs_update(), qsd_job_pending(), and qsd_upd_thread().
static cfs_time_t cfs_time_current (void) [inline, static]
Definition at line 152 of file linux-time.h.
Referenced by cfs_time_shift(), check_unlink_entry(), ctx_start_timer_kr(), delay_rule_match(), delayed_msg_check(), drop_rule_match(), kgnilnd_finish_connect(), kiblnd_check_conns(), kiblnd_failover_thread(), kiblnd_fmr_pool_map(), kiblnd_fmr_pool_unmap(), kiblnd_peer_alive(), kiblnd_pool_alloc_node(), kiblnd_pool_free_node(), kiblnd_query(), ksocknal_check_peer_timeouts(), ksocknal_connd_get_route_locked(), ksocknal_connect(), ksocknal_create_conn(), ksocknal_destroy_conn(), ksocknal_find_conn_locked(), ksocknal_find_connectable_route_locked(), ksocknal_find_timed_out_conn(), ksocknal_flush_stale_txs(), ksocknal_process_transmit(), ksocknal_query(), ksocknal_queue_tx_locked(), ksocknal_reaper(), ksocknal_recv_iov(), ksocknal_recv_kiov(), ksocknal_send_keepalive_locked(), ksocknal_transmit(), ldlm_cancel_aged_policy(), ldlm_cancel_lrur_policy(), ldlm_expired_completion_wait(), ldlm_handle_gl_callback(), ldlm_lock_add_to_lru_nolock(), ldlm_namespace_dump(), ldlm_prepare_lru_list(), lfsck_assistant_engine(), lfsck_checkpoint(), lfsck_layout_double_scan_result(), lfsck_layout_dump(), lfsck_layout_master_checkpoint(), lfsck_layout_master_post(), lfsck_layout_slave_checkpoint(), lfsck_layout_slave_double_scan(), lfsck_layout_slave_post(), lfsck_namespace_assistant_handler_p2(), lfsck_namespace_checkpoint(), lfsck_namespace_double_scan_one_trace_file(), lfsck_namespace_double_scan_result(), lfsck_namespace_dump(), lfsck_namespace_post(), lfsck_post(), lfsck_prep(), libcfs_debug_vmsg2(), ll_agl_trigger(), ll_glimpse_size(), ll_update_remote_perm(), lnet_eq_wait_locked(), lnet_ni_query_locked(), lnet_nid2peer_locked(), lnet_notify(), lnet_peer_alive_locked(), lnet_peer_set_alive(), lnet_ping_router_locked(), lnet_router_checker_event(), LNetCtl(), lstcon_new_session_id(), lstcon_node_find(), lstcon_rpc_done(), lstcon_rpc_pinger(), lstcon_rpc_trans_abort(), mgs_ir_notify(), mgs_ir_notify_complete(), ofd_fmd_expire_nolock(), ofd_fmd_find_nolock(), ofd_fmd_get(), ofd_prolong_extent_locks(), osc_make_ready(), osc_object_is_contended(), osc_object_set_contended(), osc_page_submit(), osc_should_shrink_grant(), osc_submit_duration(), osd_bufs_get_read(), osd_do_bio(), osd_read(), osd_scrub_checkpoint(), osd_scrub_dump(), osd_scrub_file_store(), osd_scrub_post(), osp_init_precreate(), osp_precreate_reserve(), osp_statfs_need_update(), osp_sync(), osp_sync_llog_init(), pinger_check_timeout(), proc_lnet_peers(), proc_lnet_routers(), ptlrpc_at_check_timed(), ptlrpc_at_timer(), ptlrpc_ping_import_soon(), ptlrpc_pinger_main(), ptlrpc_send_limit_expired(), ptlrpc_set_add_new_req(), ptlrpc_set_add_req(), ptlrpcd_add_rqset(), sfw_get_stats(), sfw_init_session(), and sptlrpc_enc_pool_get_pages().
static time_t cfs_time_current_sec (void) [inline, static]
Definition at line 157 of file linux-time.h.
Referenced by __import_set_state(), after_reply(), at_measured(), at_reset_nolock(), class_new_export(), cli_ctx_check_death(), cli_ctx_expire(), ctx_create_kr(), enc_pools_shrink_count(), enc_pools_shrink_scan(), exp_expired(), gss_cli_ctx_uptodate(), gss_ctx_cache_gc_pf(), gss_pipe_destroy_msg(), gss_sec_display_kr(), gss_sec_lookup_ctx_pf(), gss_svc_upcall_expire_rvs_ctx(), hsm_restore_cb(), import_sec_check_expire(), ir_state_graduate(), ksocknal_base_startup(), ksocknal_connd(), ksocknal_connd_check_start(), ldlm_cli_enqueue(), ldlm_completion_ast(), ldlm_completion_tail(), ldlm_expired_completion_wait(), lfsck_create_lpf(), lfsck_layout_double_scan_result(), lfsck_layout_master_checkpoint(), lfsck_layout_master_post(), lfsck_layout_prep(), lfsck_layout_slave_checkpoint(), lfsck_layout_slave_post(), lfsck_namespace_checkpoint(), lfsck_namespace_double_scan_one_trace_file(), lfsck_namespace_double_scan_result(), lfsck_namespace_insert_normal(), lfsck_namespace_insert_orphan(), lfsck_namespace_post(), lfsck_namespace_prep(), lfsck_time_dump(), libcfs_debug_dumplog_internal(), ll_open_cleanup(), ll_prep_md_op_data(), ll_setattr_raw(), llog_read_header(), lnet_ni_alloc(), lnet_parse(), lnet_update_ni_status_locked(), LNetCtl(), lod_qos_calc_ppo(), lod_qos_used(), lstcon_console_init(), lstcon_ioctl_entry(), lstcon_rpc_pinger(), lstcon_rpc_pinger_start(), mdc_create(), mdc_enqueue(), mdc_xattr_common(), mdt_agent_record_add(), mdt_agent_record_update(), mdt_cancel_all_cb(), mdt_cdt_alloc_request(), mdt_cdt_update_request(), mdt_coordinator_cb(), mdt_getattr_name_lock(), mdt_hsm_cdt_start(), mdt_reint_setxattr(), mgs_init0(), mgs_ir_init_fs(), mgs_modify(), osc_brw_redo_request(), osc_cache_too_much(), osc_lru_add_batch(), osd_oii_insert(), osd_scrub_checkpoint(), osd_scrub_join(), osd_scrub_post(), osd_scrub_prep(), ping_evictor_main(), proc_lnet_nis(), ptl_send_rpc(), ptlrpc_at_adj_net_latency(), ptlrpc_at_check_timed(), ptlrpc_at_recv_early_reply(), ptlrpc_at_send_early_reply(), ptlrpc_at_set_reply(), ptlrpc_at_set_timer(), ptlrpc_check_set(), ptlrpc_client_bulk_active(), ptlrpc_client_early(), ptlrpc_client_recv(), ptlrpc_client_recv_or_unlink(), ptlrpc_client_replied(), ptlrpc_expired_set(), ptlrpc_inflight_timeout(), ptlrpc_init_xid(), ptlrpc_send_new_req(), ptlrpc_send_reply(), ptlrpc_server_handle_req_in(), ptlrpc_server_handle_request(), ptlrpc_set_next_timeout(), ptlrpc_unregister_bulk(), ptlrpc_unregister_reply(), ptlrpc_update_export_timer(), ptlrpcd_add_work_req(), qmt_dqacq0(), qmt_id_lock_glimpse(), qmt_revalidate(), qmt_set(), record_marker(), reply_in_callback(), request_out_callback(), rvs_sec_install_root_ctx_kr(), scrub_time_dump(), sec_do_gc(), sfw_add_session_timer(), sptlrpc_conf_client_adapt(), sptlrpc_enc_pool_get_pages(), sptlrpc_enc_pool_init(), sptlrpc_gc_add_sec(), sptlrpc_info_lprocfs_seq_show(), sptlrpc_proc_enc_pool_seq_show(), sptlrpc_target_export_check(), srpc_add_buffer(), srpc_add_client_rpc_timer(), srpc_lnet_ev_handler(), srpc_startup(), stt_add_timer(), stt_check_timers(), stt_startup(), tgt_brw_read(), tgt_brw_write(), and upcall_cache_flush_one().
static cfs_duration_t cfs_time_seconds (int seconds) [inline, static]
Definition at line 182 of file linux-time.h.
Referenced by __cfs_fail_timeout_set(), cfs_time_shift(), cfs_time_shift_64(), cfs_wi_sched_destroy(), cfs_wi_shutdown(), cl_sync_io_wait(), cleanup_resource(), delay_rule_match(), drop_rule_match(), echo_cleanup(), echo_device_free(), kgnilnd_base_shutdown(), kgnilnd_bump_timeouts(), kgnilnd_check_conn_timeouts_locked(), kgnilnd_check_fma_rx(), kgnilnd_check_peer_timeouts_locked(), kgnilnd_del_conn_or_peer(), kgnilnd_dgram_mover(), kgnilnd_finish_connect(), kgnilnd_map_fmablk(), kgnilnd_peer_increase_reconnect_locked(), kgnilnd_process_fmaq(), kgnilnd_process_rdmaq(), kgnilnd_quiesce_wait(), kgnilnd_reaper(), kgnilnd_reaper_dgram_check(), kgnilnd_ruhroh_thread(), kgnilnd_scheduler(), kgnilnd_sendmsg_nolock(), kgnilnd_shutdown(), kiblnd_base_shutdown(), kiblnd_current_hdev(), kiblnd_failover_thread(), kiblnd_pool_alloc_node(), kiblnd_shutdown(), ksocknal_base_shutdown(), ksocknal_connd_check_start(), ksocknal_connd_check_stop(), ksocknal_connect(), ksocknal_destroy_conn(), ksocknal_reaper(), ksocknal_receive(), ksocknal_send_keepalive_locked(), ksocknal_shutdown(), ksocknal_transmit(), ldlm_completion_ast(), ldlm_handle_cp_callback(), ldlm_handle_gl_callback(), ldlm_lock_match(), lfsck_assistant_engine(), lfsck_checkpoint(), lfsck_layout_lastid_load(), lfsck_layout_slave_double_scan(), lfsck_layout_slave_exec_oit(), lfsck_namespace_assistant_handler_p2(), lfsck_namespace_double_scan_one_trace_file(), lfsck_post(), lfsck_prep(), lfsck_query(), libcfs_debug_vmsg2(), lnet_acceptor(), lnet_clear_zombies_nis_locked(), lnet_eq_wait_locked(), lnet_peer_alive_locked(), lnet_peer_is_alive(), lnet_peer_table_deathrow_wait_locked(), lnet_ping_md_unlink(), lnet_ping_router_locked(), lnet_prune_rc_data(), lnet_router_checker(), lnet_wait_known_routerstate(), LNetCtl(), lov_check_and_wait_active(), lqe_cleanup(), lstcon_rpc_cleanup_wait(), lstcon_rpc_trans_postwait(), lustre_get_emerg_rs(), mdc_get_rpc_lock(), mdc_getpage(), mdt_coordinator(), mgc_process_log(), obd_exports_barrier(), osc_enter_cache(), osc_extent_wait(), osc_object_is_contended(), osd_scrub_file_store(), osd_scrub_next(), osp_sync_thread(), pinger_check_timeout(), proc_console_max_delay_cs(), proc_console_min_delay_cs(), ptlrpc_disconnect_import(), ptlrpc_invalidate_import(), ptlrpc_main(), ptlrpc_ni_fini(), ptlrpc_pinger_main(), ptlrpc_reconnect_import(), ptlrpc_recover_import(), ptlrpc_send_limit_expired(), ptlrpc_service_unlink_rqbd(), ptlrpc_set_wait(), ptlrpc_unregister_bulk(), ptlrpc_unregister_reply(), ptlrpc_wait_replies(), ptlrpcd(), ptlrpcd_add_req(), qsd_op_begin0(), qsd_qtype_fini(), qsd_upd_thread(), revalidate_statahead_dentry(), round_timeout(), srpc_startup(), srpc_wait_service_shutdown(), stt_timer_main(), tgt_brw_read(), tracefiled(), and upcall_cache_get_entry().
static __u64 cfs_time_shift_64 (int seconds) [inline, static]
Definition at line 242 of file linux-time.h.
References cfs_time_add_64(), cfs_time_current_64, and cfs_time_seconds().
Referenced by class_attach(), client_common_fill_super(), ll_statfs(), lmv_iocontrol(), lod_qos_statfs_update(), lov_iocontrol(), mdc_iocontrol(), mdt_init0(), mdt_statfs(), ofd_grant_statfs(), ofd_init0(), ofd_statfs_hdl(), qmt_adjust_edquot(), qsd_acquire_local(), qsd_acquire_remote(), and qsd_adjust_schedule().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.