Lustre: libcfs/libcfs/linux/linux-crypto-crc32c-pclmul.c File Reference
libcfs/libcfs/linux/linux-crypto-crc32c-pclmul.c File Reference
#include <linux/crc32.h>
#include <crypto/internal/hash.h>
#include <asm/cpufeature.h>
#include <asm/i387.h>
#include <libcfs/libcfs.h>
Defines
#define CHKSUM_BLOCK_SIZE 1
#define CHKSUM_DIGEST_SIZE 4
#define X86_FEATURE_XMM4_2 (4*32+20)
Functions
asmlinkage unsigned int crc_pcl (const u8 *buffer, int len, unsigned int crc_init)
static int crc32c_pclmul_cra_init (struct crypto_tfm *tfm)
static int crc32c_pclmul_setkey (struct crypto_shash *hash, const u8 *key, unsigned int keylen)
static int crc32c_pclmul_init (struct shash_desc *desc)
static int crc32c_pclmul_update (struct shash_desc *desc, const u8 *data, unsigned int len)
static int __crc32c_pclmul_finup (u32 *crcp, const u8 *data, unsigned int len, u8 *out)
static int crc32c_pclmul_finup (struct shash_desc *desc, const u8 *data, unsigned int len, u8 *out)
static int crc32c_pclmul_digest (struct shash_desc *desc, const u8 *data, unsigned int len, u8 *out)
static int crc32c_pclmul_final (struct shash_desc *desc, u8 *out)
int cfs_crypto_crc32c_pclmul_register (void)
Functions for start/stop shash crc32c pclmulqdq.
void cfs_crypto_crc32c_pclmul_unregister (void)
Variables
static struct shash_alg alg
Define Documentation
#define CHKSUM_BLOCK_SIZE 1
Definition at line 36 of file linux-crypto-crc32c-pclmul.c.
#define CHKSUM_DIGEST_SIZE 4
Definition at line 37 of file linux-crypto-crc32c-pclmul.c.
#define X86_FEATURE_XMM4_2 (4*32+20)
Definition at line 140 of file linux-crypto-crc32c-pclmul.c.
Referenced by cfs_crypto_crc32c_pclmul_register().
Function Documentation
static int __crc32c_pclmul_finup (u32 * crcp, const u8 * data, unsigned int len, u8 * out) [static]
Definition at line 89 of file linux-crypto-crc32c-pclmul.c.
References cpu_to_le32, and crc_pcl().
Referenced by crc32c_pclmul_digest(), and crc32c_pclmul_finup().
int cfs_crypto_crc32c_pclmul_register (void)
Functions for start/stop shash crc32c pclmulqdq.
Definition at line 143 of file linux-crypto-crc32c-pclmul.c.
References alg, CDEBUG, D_INFO, and X86_FEATURE_XMM4_2.
Referenced by cfs_crypto_register().
void cfs_crypto_crc32c_pclmul_unregister (void)
Definition at line 152 of file linux-crypto-crc32c-pclmul.c.
References alg.
Referenced by cfs_crypto_unregister().
static int crc32c_pclmul_cra_init (struct crypto_tfm * tfm) [static]
Definition at line 42 of file linux-crypto-crc32c-pclmul.c.
static int crc32c_pclmul_digest (struct shash_desc * desc, const u8 * data, unsigned int len, u8 * out) [static]
Definition at line 104 of file linux-crypto-crc32c-pclmul.c.
References __crc32c_pclmul_finup().
static int crc32c_pclmul_final (struct shash_desc * desc, u8 * out) [static]
Definition at line 111 of file linux-crypto-crc32c-pclmul.c.
static int crc32c_pclmul_finup (struct shash_desc * desc, const u8 * data, unsigned int len, u8 * out) [static]
Definition at line 98 of file linux-crypto-crc32c-pclmul.c.
References __crc32c_pclmul_finup().
static int crc32c_pclmul_init (struct shash_desc * desc) [static]
Definition at line 68 of file linux-crypto-crc32c-pclmul.c.
static int crc32c_pclmul_setkey (struct crypto_shash * hash, const u8 * key, unsigned int keylen) [static]
Definition at line 55 of file linux-crypto-crc32c-pclmul.c.
static int crc32c_pclmul_update (struct shash_desc * desc, const u8 * data, unsigned int len) [static]
Definition at line 77 of file linux-crypto-crc32c-pclmul.c.
References crc_pcl().
asmlinkage unsigned int crc_pcl (const u8 * buffer, int len, unsigned int crc_init)
Referenced by __crc32c_pclmul_finup(), and crc32c_pclmul_update().
Variable Documentation
struct shash_alg alg [static]
Initial value:
 {
        .setkey         = crc32c_pclmul_setkey,
        .init           = crc32c_pclmul_init,
        .update         = crc32c_pclmul_update,
        .final          = crc32c_pclmul_final,
        .finup          = crc32c_pclmul_finup,
        .digest         = crc32c_pclmul_digest,
        .descsize       = sizeof(u32),
        .digestsize     = CHKSUM_DIGEST_SIZE,
        .base           = {
                        .cra_name               = "crc32c",
                        .cra_driver_name        = "crc32c-pclmul",
                        .cra_priority           = 150,
                        .cra_blocksize          = CHKSUM_BLOCK_SIZE,
                        .cra_ctxsize            = sizeof(u32),
                        .cra_module             = THIS_MODULE,
                        .cra_init               = crc32c_pclmul_cra_init,
        }
}
Definition at line 119 of file linux-crypto-crc32c-pclmul.c.
Referenced by cfs_crypto_crc32c_pclmul_register(), and cfs_crypto_crc32c_pclmul_unregister().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.