Lustre: libcfs/include/libcfs/list.h File Reference
libcfs/include/libcfs/list.h File Reference
Data Structures
struct list_head
struct hlist_node
struct hlist_head
Defines
#define prefetch(a) ((void)a)
#define LIST_HEAD_INIT(name) { &(name), &(name) }
#define INIT_LIST_HEAD(ptr)
#define list_entry(ptr, type, member) ((type *)((char *)(ptr)-(char *)(&((type *)0)->member)))
Get the container of a list.
#define list_for_each(pos, head)
Iterate over a list.
#define list_for_each_safe(pos, n, head)
Iterate over a list safely.
#define list_for_each_entry_continue(pos, head, member)
Iterate over a list continuing after existing point.
#define NULL_P ((void *)0)
#define HLIST_HEAD_INIT { NULL_P }
#define HLIST_HEAD(name) struct hlist_head name = { NULL_P }
#define INIT_HLIST_HEAD(ptr) ((ptr)->first = NULL_P)
#define INIT_HLIST_NODE(ptr) ((ptr)->next = NULL_P, (ptr)->pprev = NULL_P)
#define hlist_entry(ptr, type, member) container_of(ptr,type,member)
#define hlist_for_each(pos, head)
#define hlist_for_each_safe(pos, n, head)
#define hlist_for_each_entry(tpos, pos, head, member)
Iterate over an hlist of given type.
#define hlist_for_each_entry_continue(tpos, pos, member)
Iterate over an hlist continuing after existing point.
#define hlist_for_each_entry_from(tpos, pos, member)
Iterate over an hlist continuing from an existing point.
#define hlist_for_each_entry_safe(tpos, pos, n, head, member)
Iterate over an hlist of given type safe against removal of list entry.
#define list_for_each_prev(pos, head)
Iterate over a list in reverse order.
#define list_for_each_entry(pos, head, member)
Iterate over a list of given type.
#define list_for_each_entry_reverse(pos, head, member)
Iterate backwards over a list of given type.
#define list_for_each_entry_safe(pos, n, head, member)
Iterate over a list of given type safe against removal of list entry.
#define cfs_hlist_for_each_entry(tpos, pos, head, member) hlist_for_each_entry(tpos, pos, head, member)
#define cfs_hlist_for_each_entry_safe(tpos, pos, n, head, member) hlist_for_each_entry_safe(tpos, pos, n, head, member)
#define cfs_hlist_for_each_entry_continue(tpos, pos, member) hlist_for_each_entry_continue(tpos, pos, member)
#define cfs_hlist_for_each_entry_from(tpos, pos, member) hlist_for_each_entry_from(tpos, pos, member)
Functions
static void __list_add (struct list_head *new, struct list_head *prev, struct list_head *next)
Insert a new entry between two known consecutive entries.
static void list_add (struct list_head *new, struct list_head *head)
Insert an entry at the start of a list.
static void list_add_tail (struct list_head *new, struct list_head *head)
Insert an entry at the end of a list.
static void __list_del (struct list_head *prev, struct list_head *next)
static void list_del (struct list_head *entry)
Remove an entry from the list it is currently in.
static void list_del_init (struct list_head *entry)
Remove an entry from the list it is currently in and reinitialize it.
static void list_move (struct list_head *list, struct list_head *head)
Remove an entry from the list it is currently in and insert it at the start of another list.
static void list_move_tail (struct list_head *list, struct list_head *head)
Remove an entry from the list it is currently in and insert it at the end of another list.
static int list_empty (struct list_head *head)
Test whether a list is empty.
static int list_empty_careful (const struct list_head *head)
Test whether a list is empty and not being modified.
static void __list_splice (struct list_head *list, struct list_head *head)
static void list_splice (struct list_head *list, struct list_head *head)
Join two lists.
static void list_splice_tail (struct list_head *list, struct list_head *head)
static void list_splice_init (struct list_head *list, struct list_head *head)
Join two lists and reinitialise the emptied list.
static int hlist_unhashed (const struct hlist_node *h)
static int hlist_empty (const struct hlist_head *h)
static void __hlist_del (struct hlist_node *n)
static void hlist_del (struct hlist_node *n)
static void hlist_del_init (struct hlist_node *n)
static void hlist_add_head (struct hlist_node *n, struct hlist_head *h)
static void hlist_add_before (struct hlist_node *n, struct hlist_node *next)
static void hlist_add_after (struct hlist_node *n, struct hlist_node *next)
Define Documentation
#define cfs_hlist_for_each_entry (tpos, pos, head, member) hlist_for_each_entry(tpos, pos, head, member)
Definition at line 502 of file list.h.
Referenced by do_check_remote_perm(), ll_update_remote_perm(), rvs_sec_install_root_ctx_kr(), and sec_lookup_root_ctx_kr().
#define cfs_hlist_for_each_entry_continue (tpos, pos, member) hlist_for_each_entry_continue(tpos, pos, member)
Definition at line 506 of file list.h.
#define cfs_hlist_for_each_entry_from (tpos, pos, member) hlist_for_each_entry_from(tpos, pos, member)
Definition at line 508 of file list.h.
#define cfs_hlist_for_each_entry_safe (tpos, pos, n, head, member) hlist_for_each_entry_safe(tpos, pos, n, head, member)
Definition at line 504 of file list.h.
Referenced by dispose_ctx_list_kr(), flush_spec_ctx_cache_kr(), free_rmtperm_hash(), gss_ctx_cache_gc_pf(), gss_sec_ctx_replace_pf(), gss_sec_display_kr(), gss_sec_flush_ctx_cache_pf(), gss_sec_gc_ctx_kr(), and gss_sec_lookup_ctx_pf().
#define INIT_LIST_HEAD (ptr)
Value:
do { \
        (ptr)->next = (ptr); (ptr)->prev = (ptr); \
} while (0)
Definition at line 48 of file list.h.
Referenced by add_nidrange(), alloc_entry(), cfs_expr_list_parse(), cfs_parse_nidlist(), cfs_tcd_shrink(), cfs_trace_cleanup(), cfs_tracefile_init(), cfs_wi_init(), cfs_wi_sched_create(), cfs_wi_startup(), cl_cache_init(), cl_env_new(), cl_env_percpu_init(), cl_global_init(), cl_io_init0(), cl_lock_init(), cl_page_alloc(), cl_page_list_init(), class_add_profile(), class_attach(), class_del_uuid(), class_dentry_readdir(), class_disconnect_exports(), class_disconnect_stale_exports(), class_handle_init(), class_init_uuidlist(), class_new_export(), class_new_import(), client_obd_setup(), collect_pages(), create_sub_thandle(), cYAML_build_tree(), cYAML_ll_push(), cYAML_print_tree(), cYAML_print_tree2file(), distribute_txn_commit_thread(), distribute_txn_init(), dt_device_init(), dtrq_create(), dtrq_sub_add_cookie(), dtrq_sub_create_and_insert(), dynlock_init(), echo_client_setup(), echo_lock_init(), fail_peer(), fld_cache_init(), fld_client_init(), gss_cli_ctx_init_common(), gss_ctx_refresh_pf(), gss_init_pipefs_upcall(), gss_sec_create_common(), idmap_entry_alloc(), init_blwi(), jt_lst_add_group(), jt_lst_add_test(), jt_lst_ping(), jt_lst_query_batch(), jt_lst_show_error(), jt_lst_start_batch(), jt_lst_stat(), jt_lst_stop_batch(), jt_lst_update_group(), jt_nodemap_add_range(), jt_nodemap_del_range(), kgnilnd_alloc_dgram(), kgnilnd_alloc_fmablk(), kgnilnd_alloc_tx(), kgnilnd_base_startup(), kgnilnd_cancel_net_dgrams(), kgnilnd_cancel_wc_dgrams(), kgnilnd_create_conn(), kgnilnd_create_peer_safe(), kgnilnd_reaper_check(), kgnilnd_startup(), kiblnd_alloc_freg_pool(), kiblnd_base_startup(), kiblnd_create_conn(), kiblnd_create_dev(), kiblnd_create_peer(), kiblnd_init_fmr_poolset(), kiblnd_init_pool(), kiblnd_init_poolset(), kiblnd_reconnect_peer(), ksocknal_base_startup(), ksocknal_create_conn(), ksocknal_create_peer(), ksocknal_reaper(), ldlm_handle_cp_callback(), ldlm_init(), ldlm_interval_alloc(), ldlm_lock_convert(), ldlm_lock_enqueue(), ldlm_lock_new(), ldlm_namespace_new(), ldlm_process_flock_lock(), ldlm_reprocess_all(), ldlm_resource_new(), ldlm_setup(), lfsck_add_target(), lfsck_assistant_data_init(), lfsck_init(), lfsck_layout_assistant_req_init(), lfsck_layout_llst_add(), lfsck_layout_setup(), lfsck_layout_slave_exec_oit(), lfsck_namespace_assistant_req_init(), lfsck_namespace_close_dir(), lfsck_namespace_notify_lmv_master_local(), lfsck_namespace_setup(), lfsck_register(), lfsck_tgt_descs_init(), libcfs_kkuc_group_add(), list_del_init(), list_splice_init(), ll_cl_add(), ll_init_sbi(), ll_lli_init(), ll_local_open(), ll_sai_alloc(), ll_xattr_cache_init(), llog_alloc_handle(), llog_init_handle(), lmd_parse_nidlist(), lnet_add_route(), lnet_create_rc_data_locked(), lnet_create_remote_nets_table(), lnet_delay_rule_add(), lnet_delay_rule_check(), lnet_delay_rule_del(), lnet_drop_routed_msgs_locked(), lnet_drop_rule_del(), lnet_dyn_add_ni(), lnet_fail_nid(), lnet_fault_init(), lnet_lib_init(), lnet_match_networks(), lnet_md_alloc(), lnet_msg_container_setup(), lnet_ni_alloc(), lnet_nid2peer_locked(), lnet_parse_route(), lnet_parse_routes(), lnet_peer_tables_cleanup(), lnet_peer_tables_create(), lnet_prepare(), lnet_prune_rc_data(), lnet_ptl_setup(), lnet_res_container_setup(), lnet_rtrpool_adjust_bufs(), lnet_rtrpool_free_bufs(), lnet_rtrpool_init(), lnet_str2tbs_expand(), lnet_str2tbs_sep(), LNetNIInit(), lod_pools_init(), lod_putref(), lov_init_set(), lov_io_init_raid0(), lov_setup(), lovsub_lock_init(), lqe_locate(), ls_device_get(), lst_print_stat(), lst_stat_req_param_alloc(), lstcon_batch_add(), lstcon_console_init(), lstcon_group_alloc(), lstcon_ndlink_find(), lstcon_ndlist_stat(), lstcon_rpc_init(), lstcon_rpc_module_init(), lstcon_rpc_trans_prep(), lstcon_test_add(), lu_context_init(), lu_device_init(), lu_device_type_init(), lu_global_init(), lu_object_free(), lu_object_header_init(), lu_object_init(), lu_site_init(), lu_site_purge(), lustre_idmap_init(), lustre_init_lsi(), lustre_pack_reply_v2(), lustre_register_lwp_item(), mdt_export_cleanup(), mdt_fs_setup(), mdt_hsm_cdt_init(), mdt_init0(), mdt_init_export(), mdt_lock_objects_in_linkea(), mdt_mfd_new(), mdt_reint_migrate_internal(), mgs_direntry_alloc(), mgs_fsc_attach(), mgs_init_export(), mgs_init_fsdb_list(), mgs_ir_init_fs(), mgs_nidtbl_init_fs(), mgs_nidtbl_write(), nodemap_create(), nodemap_process_keyrec(), nrs_fifo_start(), nrs_policy_register(), nrs_svcpt_setup_locked0(), null_init_internal(), obd_zombie_impexp_init(), obdclass_init(), ofd_add_inconsistency_item(), ofd_get_info_hdl(), ofd_grant_commit_cb_add(), ofd_init0(), ofd_init_export(), ofd_intent_policy(), ofd_seq_load(), ofd_seqs_free(), ofd_seqs_init(), ofd_soft_sync_cb_add(), osc_brw_prep_request(), osc_brw_redo_request(), osc_build_rpc(), osc_extent_alloc(), osc_lock_init(), osc_object_init(), osc_page_init(), osc_setup(), osd_device_init0(), osd_find_or_add_seq(), osd_ios_new_item(), osd_it_acct_init(), osd_it_add_processed(), osd_object_alloc(), osd_oii_insert(), osd_ost_init(), osd_ost_seq_init(), osd_process_scheduled_agent_removals(), osd_scrub_setup(), osd_seq_load(), osd_trans_create(), osd_trans_stop(), osp_init0(), osp_invalidate_request(), osp_oac_init(), osp_oac_xattr_find_or_add(), osp_oac_xattr_replace(), osp_object_update_request_create(), osp_sync_id_traction_init(), osp_sync_init(), osp_sync_process_committed(), osp_sync_send_new_rpc(), osp_trans_create(), osp_update_callback_init(), osp_update_init(), osp_update_request_create(), panic_collect_pages(), parse_addrange(), parse_nids(), ping_evictor_start(), plain_create_sec(), plain_sec_install_ctx(), ptlrpc_alloc_rqbd(), ptlrpc_at_check_timed(), ptlrpc_check_set(), ptlrpc_cli_req_init(), ptlrpc_hr_init(), ptlrpc_hr_main(), ptlrpc_init(), ptlrpc_init_rq_pool(), ptlrpc_new_timeout(), ptlrpc_nrs_init(), ptlrpc_prep_set(), ptlrpc_register_service(), ptlrpc_req_comm_init(), ptlrpc_service_part_init(), ptlrpc_srv_req_init(), ptlrpc_svcpt_stop_threads(), qmt_device_init0(), qmt_pool_alloc(), qmt_pool_init(), qsd_get_fsinfo(), qsd_init(), qsd_qtype_init(), qsd_upd_alloc(), qsd_upd_thread(), range_create(), range_lock_init(), rs_batch_init(), sa_alloc(), seq_update_cb_add(), sfw_add_test_instance(), sfw_bid2batch(), sfw_init_session(), sfw_startup(), sptlrpc_conf_get(), sptlrpc_conf_init(), sptlrpc_gc_init(), srpc_add_client_rpc_timer(), srpc_init_client_rpc(), srpc_service_init(), stt_startup(), sub_thandle_register_commit_cb(), sub_thandle_register_stop_cb(), sub_updates_write(), tgt_boot_epoch_update(), tgt_client_alloc(), tgt_init(), tgt_last_commit_cb_add(), tgt_mod_init(), tgt_new_client_cb_add(), top_trans_create_tmt(), and upcall_cache_init().
#define list_entry (ptr, type, member) ((type *)((char *)(ptr)-(char *)(&((type *)0)->member)))
Get the container of a list.
Parameters:
ptr the embedded list.
type the type of the struct this is embedded in.
member the member name of the list within the struct.
Definition at line 242 of file list.h.
Referenced by after_reply(), agl_first_entry(), cfs_expr_list_free(), cfs_expr_list_free_list(), cfs_free_nidlist(), cfs_tage_from_list(), cfs_wi_scheduler(), cfs_wi_shutdown(), cl_echo_cancel0(), cl_lock_fini(), cl_page_free(), cl_page_list_first(), cl_page_list_last(), class_del_uuid(), class_disconnect_export_list(), class_import_destroy(), class_search_type(), cleanup_resource(), cYAML_ll_pop(), delayed_msg_check(), delayed_msg_process(), distribute_txn_get_next_req(), distribute_txn_get_next_transno(), fail_peer(), fld_cache_shrink(), fld_client_lookup(), free_addrranges(), get_write_extents(), gss_pipe_release(), jt_lst_show_error(), jt_lst_stat(), kgnilnd_check_fma_rcv_cq(), kgnilnd_close_peer_conns_locked(), kgnilnd_close_stale_conns_locked(), kgnilnd_conn_isdup_locked(), kgnilnd_conn_seq_seek(), kgnilnd_cqid2conn_locked(), kgnilnd_del_conn_or_peer(), kgnilnd_get_conn_by_idx(), kgnilnd_get_peer_info(), kgnilnd_mdd_seq_seek(), kgnilnd_peer_seq_seek(), kgnilnd_reaper_check(), kgnilnd_smsg_seq_seek(), kiblnd_abort_txs(), kiblnd_check_conns(), kiblnd_check_sends(), kiblnd_check_txs_locked(), kiblnd_close_matching_conns(), kiblnd_close_peer_conns_locked(), kiblnd_close_stale_conns_locked(), kiblnd_connd(), kiblnd_connreq_done(), kiblnd_debug_conn(), kiblnd_del_peer(), kiblnd_del_peer_locked(), kiblnd_destroy_pool_list(), kiblnd_fail_fmr_poolset(), kiblnd_fail_poolset(), kiblnd_find_peer_locked(), kiblnd_find_waiting_tx_locked(), kiblnd_get_conn_by_idx(), kiblnd_get_conn_locked(), kiblnd_get_peer_info(), kiblnd_handle_early_rxs(), kiblnd_scheduler(), kiblnd_tx_init(), kiblnd_txlist_done(), ksocknal_add_interface(), ksocknal_add_peer(), ksocknal_add_route_locked(), ksocknal_alloc_tx(), ksocknal_check_peer_timeouts(), ksocknal_close_conn_locked(), ksocknal_close_matching_conns(), ksocknal_close_peer_conns_locked(), ksocknal_connd(), ksocknal_connect(), ksocknal_create_conn(), ksocknal_create_routes(), ksocknal_debug_peerhash(), ksocknal_del_interface(), ksocknal_del_peer(), ksocknal_del_peer_locked(), ksocknal_del_route_locked(), ksocknal_finalize_zcreq(), ksocknal_find_conn_locked(), ksocknal_find_connectable_route_locked(), ksocknal_find_connecting_route_locked(), ksocknal_find_peer_locked(), ksocknal_find_timed_out_conn(), ksocknal_flush_stale_txs(), ksocknal_free_buffers(), ksocknal_get_conn_by_idx(), ksocknal_get_peer_info(), ksocknal_handle_zcack(), ksocknal_next_tx_carrier(), ksocknal_peer_del_interface_locked(), ksocknal_push_peer(), ksocknal_query(), ksocknal_reaper(), ksocknal_scheduler(), ksocknal_txlist_done(), ldlm_bl_get_work(), ldlm_cli_cancel_list(), ldlm_dump_all_namespaces(), ldlm_export_cancel_blocked_locks(), ldlm_extent_shift_kms(), ldlm_interval_extent(), ldlm_process_flock_lock(), ldlm_resource_foreach(), ldlm_work_bl_ast_lock(), ldlm_work_cp_ast_lock(), ldlm_work_gl_ast_lock(), ldlm_work_revoke_ast_lock(), lfsck_add_target_from_orphan(), lfsck_assistant_engine(), lfsck_assistant_notify_others(), lfsck_assistant_query_others(), lfsck_layout_assistant_fill_pos(), lfsck_layout_assistant_handler_p2(), lfsck_layout_slave_notify_master(), lfsck_layout_slave_query_master(), lfsck_layout_slave_quit(), lfsck_lmv_put(), lfsck_master_oit_engine(), lfsck_namespace_assistant_fill_pos(), lfsck_namespace_assistant_handler_p2(), lfsck_namespace_release_lmv(), lfsck_namespace_rescan_striped_dir(), lfsck_post(), libcfs_num_match(), lnet_add_route(), lnet_check_routes(), lnet_clear_zombies_nis_locked(), lnet_count_acceptor_nis(), lnet_del_route(), lnet_delay_rule_check(), lnet_drop_delayed_msg_list(), lnet_dyn_add_ni(), lnet_fail_nid(), lnet_finalize(), lnet_find_lnd_by_type(), lnet_find_net_locked(), lnet_free_text_bufs(), lnet_get_net_config(), lnet_get_route(), lnet_lib_exit(), lnet_match_networks(), lnet_msg_container_cleanup(), lnet_net2ni_locked(), lnet_net_unique(), lnet_nid2ni_locked(), lnet_nid2peer_locked(), lnet_parse_networks(), lnet_parse_route(), lnet_parse_route_tbs(), lnet_peer_tables_cleanup(), lnet_post_routed_recv_locked(), lnet_print_text_bufs(), lnet_prune_rc_data(), lnet_ptl_cleanup(), lnet_recv_delayed_msg_list(), lnet_res_container_cleanup(), lnet_return_rx_credits_locked(), lnet_return_tx_credits_locked(), lnet_router_checker(), lnet_rtr_addref_locked(), lnet_rtrpool_adjust_bufs(), lnet_rtrpool_free_bufs(), lnet_schedule_blocked_locked(), lnet_shuffle_seed(), lnet_shutdown_lndnis(), lnet_splitnets(), lnet_startup_lndnis(), lnet_wait_known_routerstate(), LNetDist(), LNetGetId(), LNetNIInit(), lov_cleanup(), lov_finish_set(), lov_statfs_async(), lst_free_rpcent(), lst_print_stat(), lstcon_batch_destroy(), lstcon_group_move(), lstcon_rpc_cleanup_wait(), lstcon_rpc_prep(), lstcon_rpc_trans_interpreter(), lstcon_session_end(), lustre_dump_dentry(), lustre_get_emerg_rs(), lustre_idmap_fini(), lustre_stop_lwp(), mdt_export_cleanup(), mdt_finish_open(), mdt_hsm_active_requests_proc_show(), mdt_hsm_agent_proc_show(), mdt_steal_ack_locks(), mgs_cleanup_fsdb_list(), mgs_find_fsdb(), mgs_nidtbl_fini_fs(), next_lock(), nrs_fifo_req_get(), obd_put_request_slot(), obd_set_max_rpcs_in_flight(), obd_stale_export_get(), obd_zombie_impexp_cull(), ofd_inconsistency_verification_main(), osc_build_rpc(), osc_cache_shrink_scan(), osc_lock_wake_waiters(), osc_lru_reclaim(), osc_lru_shrink(), osc_wake_cache_waiters(), osd_initial_OI_scrub(), osd_object_sa_dirty_rele(), osd_scrub_check_update(), osd_scrub_main(), osd_scrub_next(), osd_unlinked_list_emptify(), osp_current_object_update_request(), osp_prep_inline_update_req(), osp_prep_update_req(), osp_sync_process_committed(), ping_evictor_main(), proc_lnet_nis(), proc_lnet_peers(), proc_lnet_routers(), proc_lnet_routes(), ptlrpc_abort_inflight(), ptlrpc_abort_set(), ptlrpc_add_unreplied(), ptlrpc_at_check_timed(), ptlrpc_check_set(), ptlrpc_expired_set(), ptlrpc_first_transno(), ptlrpc_free_rq_pool(), ptlrpc_hr_main(), ptlrpc_inflight_timeout(), ptlrpc_interrupted_set(), ptlrpc_invalidate_import(), ptlrpc_known_replied_xid(), ptlrpc_pinger_main(), ptlrpc_prep_req_from_pool(), ptlrpc_replay_next(), ptlrpc_retain_replayable_request(), ptlrpc_server_drop_request(), ptlrpc_server_handle_req_in(), ptlrpc_server_post_idle_rqbds(), ptlrpc_service_purge_all(), ptlrpc_set_destroy(), ptlrpc_set_next_timeout(), ptlrpc_set_wait(), ptlrpc_svcpt_stop_threads(), ptlrpc_update_export_timer(), ptlrpc_wake_delayed(), ptlrpcd_add_rqset(), ptlrpcd_check(), ptlrpcd_steal_rqset(), qmt_glimpse_lock(), qmt_pool_fini(), qmt_pool_prepare(), qsd_cleanup_adjust(), qsd_job_pending(), qsd_upd_thread(), sa_handle_callback(), search_granted_lock(), sec_process_ctx_list(), server_find_mount(), sfw_create_rpc(), sfw_create_test_rpc(), sfw_destroy_batch(), sfw_destroy_session(), sfw_destroy_test_instance(), sfw_shutdown(), srpc_finish_service(), srpc_lnet_ev_handler(), srpc_server_rpc_done(), srpc_service_fini(), stt_add_timer(), stt_expire_list(), and tdtd_ready_for_cancel_log().
#define list_for_each (pos, head)
Value:
for (pos = (head)->next, prefetch(pos->next); pos != (head); \
                pos = pos->next, prefetch(pos->next))
Iterate over a list.
Parameters:
pos the iterator
head the list to iterate over
Behaviour is undefined if pos is removed from the list in the body of the loop.
Definition at line 253 of file list.h.
Referenced by cl_echo_cancel0(), class_search_type(), cleanup_resource(), cYAML_ll_count(), kgnilnd_check_fma_rcv_cq(), kgnilnd_conn_isdup_locked(), kgnilnd_conn_seq_seek(), kgnilnd_count_list(), kgnilnd_cqid2conn_locked(), kgnilnd_get_conn_by_idx(), kgnilnd_get_peer_info(), kgnilnd_peer_seq_seek(), kiblnd_check_conns(), kiblnd_check_txs_locked(), kiblnd_debug_conn(), kiblnd_find_peer_locked(), kiblnd_find_waiting_tx_locked(), kiblnd_get_conn_by_idx(), kiblnd_get_peer_info(), ksocknal_add_interface(), ksocknal_add_peer(), ksocknal_add_route_locked(), ksocknal_close_conn_locked(), ksocknal_create_conn(), ksocknal_create_routes(), ksocknal_debug_peerhash(), ksocknal_find_conn_locked(), ksocknal_find_connectable_route_locked(), ksocknal_find_connecting_route_locked(), ksocknal_find_peer_locked(), ksocknal_find_timed_out_conn(), ksocknal_get_conn_by_idx(), ksocknal_get_peer_info(), ksocknal_push_peer(), ksocknal_query(), ldlm_dump_all_namespaces(), ldlm_extent_shift_kms(), ldlm_process_flock_lock(), lnet_add_route(), lnet_add_route_to_rnet(), lnet_check_routes(), lnet_count_acceptor_nis(), lnet_del_route(), lnet_find_lnd_by_type(), lnet_find_net_locked(), lnet_get_net_config(), lnet_get_route(), lnet_match_networks(), lnet_net2ni_locked(), lnet_net_unique(), lnet_nid2ni_locked(), lnet_parse_networks(), lnet_parse_route(), lnet_print_text_bufs(), lnet_router_checker(), lnet_shuffle_seed(), lnet_splitnets(), lnet_wait_known_routerstate(), LNetDist(), LNetGetId(), lov_statfs_async(), lstcon_rpc_cleanup_wait(), lustre_dump_dentry(), mdt_finish_open(), mdt_hsm_active_requests_proc_start(), mdt_hsm_agent_proc_start(), mdt_steal_ack_locks(), mgs_find_fsdb(), ptlrpc_expired_set(), ptlrpc_interrupted_set(), ptlrpc_pinger_main(), ptlrpc_server_drop_request(), ptlrpc_set_destroy(), ptlrpc_set_next_timeout(), ptlrpc_set_wait(), qmt_glimpse_lock(), qmt_pool_prepare(), search_granted_lock(), and server_find_mount().
#define list_for_each_entry (pos, head, member)
Value:
for (pos = list_entry((head)->next, typeof(*pos), member),      \
                     prefetch(pos->member.next);                            \
             &pos->member != (head);                                        \
             pos = list_entry(pos->member.next, typeof(*pos), member),  \
             prefetch(pos->member.next))
Iterate over a list of given type.
Parameters:
pos the type * to use as a loop counter.
head the head for your list.
member the name of the list_struct within the struct.
Definition at line 459 of file list.h.
Referenced by __lfsck_component_find(), __lfsck_instance_find(), __ls_find_dev(), add_nidrange(), brw_client_fini(), brw_client_init(), cdt_find_request_nolock(), cfs_expr_list_match(), cfs_expr_list_print(), cfs_expr_list_values(), cfs_ip_ar_min_max(), cfs_ip_is_contiguous(), cfs_ip_min_max(), cfs_match_nid(), cfs_nidrange_find_min_max(), cfs_nidrange_is_contiguous(), cfs_num_ar_min_max(), cfs_num_is_contiguous(), cfs_num_min_max(), cfs_print_addrranges(), cfs_print_nidlist(), cfs_wi_shutdown(), cl_conf_set(), cl_lock_at(), cl_lock_enqueue(), cl_lock_init(), cl_lock_print(), cl_lockset_merge(), cl_object_attr_get(), cl_object_fiemap(), cl_object_getstripe(), cl_object_layout_get(), cl_object_maxbytes(), cl_object_prune(), cl_page_alloc(), cl_page_at_trusted(), class_add_uuid(), class_check_uuid(), class_del_uuid(), class_get_profile(), client_import_del_conn(), client_import_find_conn(), config_log_find(), declare_updates_write(), distribute_txn_assign_batchid(), distribute_txn_cancel_records(), distribute_txn_insert_by_batchid(), distribute_txn_lookup_finish_list(), dt_locate_at(), dt_los_find(), dt_object_locate(), dt_txn_hook_commit(), dt_txn_hook_start(), dt_txn_hook_stop(), dtrq_list_dump(), dtrq_lookup(), dtrq_sub_lookup(), dump_exports(), dump_requests(), dynlock_is_locked(), dynlock_lock(), echo_device_alloc(), echo_device_free(), fld_cache_entry_lookup_nolock(), fld_cache_lookup(), fld_client_add_target(), fld_rrb_scan(), gss_find_upcall(), hsm_cancel_all_actions(), iam_format_guess(), idmap_lookup_gid(), idmap_lookup_uid(), idmap_search_entry(), import_select_connection(), import_set_conn(), it_test_performance(), itree_overlap_cb(), jt_lst_ping(), jt_lst_show_error(), jt_lst_stat(), kgnilnd_bump_timeouts(), kgnilnd_count_phys_mbox(), kgnilnd_find_conn_locked(), kgnilnd_find_dgram_locked(), kgnilnd_find_free_mbox(), kgnilnd_find_net(), kgnilnd_find_or_create_conn_locked(), kgnilnd_find_peer_locked(), kgnilnd_map_phys_fmablk(), kgnilnd_mark_for_detach_purgatory_all_locked(), kgnilnd_peer_notify(), kgnilnd_peer_seq_show(), kgnilnd_proc_peer_conns_seq_show(), kgnilnd_release_mbox(), kgnilnd_report_node_state(), kgnilnd_reset_stack(), kgnilnd_unmap_fma_blocks(), kiblnd_dev_failover(), kiblnd_dev_search(), kiblnd_failover_thread(), kiblnd_fmr_pool_map(), kiblnd_pool_alloc_node(), ksocknal_check_peer_timeouts(), ksocknal_close_conn_locked(), ksocknal_connd_get_route_locked(), ksocknal_connecting(), ksocknal_push(), ksocknal_search_new_ipif(), ldlm_cancel_pack(), ldlm_cancel_resource_local(), ldlm_resource_dump(), lfsck_checkpoint(), lfsck_close_dir(), lfsck_del_target(), lfsck_double_scan(), lfsck_exec_dir(), lfsck_exec_oit(), lfsck_fail(), lfsck_instance_add(), lfsck_interpret(), lfsck_layout_lastid_store(), lfsck_layout_llst_add(), lfsck_layout_llst_find_and_del(), lfsck_layout_seq_insert(), lfsck_layout_seq_lookup(), lfsck_open_dir(), lfsck_prep(), lfsck_start(), lfsck_stop(), lgss_name_to_mech(), lgss_subflavor_to_mech(), libcfs_ioctl(), libcfs_ip_addr_range_print(), libcfs_kkuc_group_foreach(), libcfs_kkuc_group_put(), libcfs_num_addr_range_print(), ll_cl_find(), ll_iocontrol_call(), ll_iocontrol_unregister(), ll_xattr_cache_find(), llog_cat_id2handle(), llog_cat_update_header(), lnet_cpt_of_nid_locked(), lnet_delay_rule_list(), lnet_delay_rule_match_locked(), lnet_delay_rule_reset(), lnet_drop_rule_list(), lnet_drop_rule_match(), lnet_drop_rule_reset(), lnet_find_peer_locked(), lnet_find_route_locked(), lnet_get_ni_count(), lnet_get_peer_info(), lnet_parse_rc_info(), lnet_ping_info_destroy(), lnet_ping_info_install_locked(), lnet_prune_rc_data(), lnet_res_lh_lookup(), lnet_router_ni_update_locked(), lnet_update_ni_status_locked(), LNetDist(), lod_qos_calc_ppo(), lod_qos_calc_rr(), lod_qos_used(), lookup_sub_thandle(), lov_io_call(), lov_io_data_version_end(), lov_io_fsync_end(), lov_page_init_raid0(), lprocfs_mdt_print_open_files(), lst_print_transerr(), lst_print_tsb_verbose(), lst_reset_rpcent(), lstcon_batch_find(), lstcon_batch_info(), lstcon_batch_list(), lstcon_dstnodes_prep(), lstcon_group_find(), lstcon_group_info(), lstcon_group_list(), lstcon_ndlink_find(), lstcon_node_find(), lstcon_nodes_getent(), lstcon_rpc_pinger(), lstcon_rpc_trans_abort(), lstcon_rpc_trans_interpreter(), lstcon_rpc_trans_ndlist(), lstcon_rpc_trans_postwait(), lstcon_rpc_trans_prep(), lstcon_rpc_trans_stat(), lstcon_session_info(), lstcon_test_find(), lstcon_verify_group(), lu_context_key_quiesce(), lu_object_alloc(), lu_object_invariant(), lu_object_locate(), lu_object_print(), lustre_deregister_lwp_item(), lustre_disconnect_lwp(), lustre_find_lwp_by_index(), lustre_notify_lwp_list(), lustre_uuid_to_peer(), mdt_handle2mfd(), mdt_hsm_agent_lookup(), mdt_hsm_agent_update_statistics(), mdt_hsm_find_best_agent(), mdt_hsm_restore_hdl_find(), mdt_hsm_restore_is_running(), mdt_lock_objects_in_linkea(), mgc_requeue_thread(), mgs_fsc_attach(), mgs_nidtbl_read(), mgs_nidtbl_write(), nidtbl_is_sane(), nodemap_exports_show(), nodemap_idx_action(), nodemap_process_keyrec(), nodemap_ranges_show(), nrs_policy_find_desc_locked(), nrs_policy_find_locked(), nrs_policy_unregister_locked(), nrs_register_policies_locked(), ofd_grant_sanity_check(), ofd_intent_cb(), ofd_prolong_extent_locks(), ofd_seq_add(), ofd_seq_get(), only_mgs_is_running(), osc_brw_redo_request(), osc_build_rpc(), osc_cache_shrink_count(), osc_extent_make_ready(), osc_extent_sanity_check0(), osc_extent_tree_dump0(), osc_grant_shrink_grant_cb(), osc_ldlm_resource_invalidate(), osc_ldlm_weigh_ast(), osc_lock_enqueue_wait(), osc_lru_add_batch(), osc_send_write_rpc(), osd_oii_lookup(), osd_seq_find_locked(), osp_oac_xattr_find_locked(), osp_prep_update_req(), osp_sync_id_traction_init(), osp_sync_inflight_conflict(), osp_sync_tracker_commit_cb(), osp_thandle_invalidate_object(), pinger_check_timeout(), print_export_data(), proc_lnet_routers(), ptlrpc_del_timeout_client(), ptlrpc_nrs_policy_register(), ptlrpc_nrs_req_get_nolock0(), ptlrpc_pinger_main(), ptlrpc_pinger_register_timeout(), ptlrpc_prepare_replay(), ptlrpc_server_check_resend_in_progress(), ptlrpc_service_nrs_cleanup(), ptlrpc_service_nrs_setup(), ptlrpc_service_unlink_rqbd(), ptlrpc_svcpt_stop_threads(), qos_add_tgt(), qsd_get_fsinfo(), qsd_pending_updates(), qsd_process_config(), range_unlock(), range_unlock_cb(), sa_get(), search_queue(), sec_gc_main(), sfw_deactivate_session(), sfw_find_batch(), sfw_find_test_case(), sfw_get_stats(), sfw_query_batch(), sfw_run_batch(), sfw_shutdown(), sfw_startup(), sfw_stop_batch(), sfw_test_unit_done(), sptlrpc_conf_get(), sptlrpc_conf_get_tgt(), sptlrpc_record_rules(), sptlrpc_target_update_exp_flavor(), srpc_abort_service(), srpc_shutdown_service(), sub_trans_commit_cb_internal(), sub_trans_stop_cb(), tgt_boot_epoch_update(), tgt_lookup_reply_by_xid(), top_multiple_thandle_dump(), top_trans_is_stopped(), top_trans_start(), top_trans_stop(), try_to_add_extent_for_io(), upcall_cache_downcall(), upcall_cache_flush_one(), and walk_block_dqentry().
#define list_for_each_entry_continue (pos, head, member)
Value:
for (pos = list_entry(pos->member.next, typeof(*pos), member);  \
             prefetch(pos->member.next), &pos->member != (head);        \
             pos = list_entry(pos->member.next, typeof(*pos), member))
Iterate over a list continuing after existing point.
Parameters:
pos the type * to use as a loop counter
head the list head
member the name of the list_struct within the struct
Definition at line 276 of file list.h.
#define list_for_each_entry_reverse (pos, head, member)
Value:
for (pos = list_entry((head)->prev, typeof(*pos), member);      \
             prefetch(pos->member.prev), &pos->member != (head);            \
             pos = list_entry(pos->member.prev, typeof(*pos), member))
Iterate backwards over a list of given type.
Parameters:
pos the type * to use as a loop counter.
head the head for your list.
member the name of the list_struct within the struct.
Definition at line 472 of file list.h.
Referenced by __sa_make_ready(), cfs_ip_addr_match(), cl_lock_cancel(), cl_object_attr_update(), cl_object_glimpse(), distribute_txn_insert_by_batchid(), dtrq_insert(), ldlm_resource_dump(), lu_object_alloc(), lu_object_free(), lu_object_put(), ofd_fmd_find_nolock(), ptlrpc_at_add_timed(), and ptlrpc_pinger_register_timeout().
#define list_for_each_entry_safe (pos, n, head, member)
Value:
for (pos = list_entry((head)->next, typeof(*pos), member),       \
                n = list_entry(pos->member.next, typeof(*pos), member);  \
             &pos->member != (head);                                         \
             pos = n, n = list_entry(n->member.next, typeof(*n), member))
Iterate over a list of given type safe against removal of list entry.
Parameters:
pos the type * to use as a loop counter.
n another type * to use as temporary storage
head the head for your list.
member the name of the list_struct within the struct.
Definition at line 484 of file list.h.
Referenced by brw_interpret(), cfs_tcd_shrink(), cfs_trace_debug_print(), cfs_trace_flush_pages(), cfs_tracefile_dump_all_pages(), cl_io_locks_sort(), cl_io_unlock(), cl_lockset_lock(), class_del_profiles(), class_disconnect_stale_exports(), cYAML_ll_free(), delayed_msg_check(), distribute_txn_commit_thread(), dtrq_destroy(), dtrq_list_destroy(), fld_cache_delete_nolock(), fld_cache_insert_nolock(), fld_client_del_target(), fld_client_fini(), fld_fix_new_list(), kgnilnd_cancel_dgrams(), kgnilnd_cancel_net_dgrams(), kgnilnd_cancel_peer_connect_locked(), kgnilnd_cancel_wc_dgrams(), kgnilnd_check_peer_timeouts_locked(), kgnilnd_complete_closed_conn(), kgnilnd_finish_connect(), kgnilnd_free_phys_fmablk(), kgnilnd_reaper_dgram_check(), kgnilnd_release_purgatory_list(), kgnilnd_reset_stack(), kgnilnd_txlist_done(), kiblnd_alloc_freg_pool(), kiblnd_destroy_fmr_pool(), kiblnd_destroy_fmr_pool_list(), kiblnd_fmr_pool_unmap(), kiblnd_pool_free_node(), ksocknal_create_conn(), ksocknal_finalize_zcreq(), ksocknal_handle_zcack(), ldlm_cli_cancel_list_local(), ldlm_prepare_lru_list(), ldlm_replay_locks(), lfsck_add_target_from_orphan(), lfsck_assistant_notify_others(), lfsck_double_scan(), lfsck_exit(), lfsck_instance_cleanup(), lfsck_layout_master_data_release(), lfsck_layout_master_double_scan(), lfsck_layout_master_quit(), lfsck_layout_slave_quit(), lfsck_namespace_data_release(), lfsck_namespace_double_scan(), lfsck_namespace_quit(), lfsck_post(), lfsck_prep(), lfsck_quit(), lfsck_start(), lfsck_tgt_descs_fini(), libcfs_kkuc_group_rem(), ll_invalidate_negative_children(), ll_sai_put(), ll_xattr_cache_list(), llog_cat_close(), lnet_clear_lazy_portal(), lnet_delay_rule_del(), lnet_drop_routed_msgs_locked(), lnet_drop_rule_del(), lnet_mt_match_md(), lnet_peer_table_cleanup_locked(), lnet_peer_table_del_rtrs_locked(), lnet_prune_rc_data(), lnet_ptl_attach_md(), lod_pools_fini(), lod_putref(), lov_putref(), lstcon_group_drain(), lstcon_rpc_trans_destroy(), lu_cache_shrink_count(), lu_cache_shrink_scan(), lu_site_purge(), mdt_export_cleanup(), mdt_hsm_cdt_stop(), mdt_unlock_list(), mgs_erase_logs(), mgs_fsc_cleanup(), mgs_fsc_cleanup_by_fsdb(), mgs_list_logs(), mgs_write_log_direct_all(), nm_member_delete_list(), nm_member_reclassify_nodemap(), nm_member_revoke_all(), nm_member_revoke_locks(), nodemap_config_cleanup(), nodemap_config_set_active(), nodemap_del(), nodemap_idx_nodemap_del(), nodemap_procfs_exit(), nrs_svcpt_cleanup_locked(), ofd_fmd_cleanup(), ofd_fmd_expire_nolock(), ofd_seqs_free(), osc_extent_truncate(), osc_send_read_rpc(), osc_send_write_rpc(), osd_it_acct_fini(), osd_ost_fini(), osd_ost_seq_fini(), osd_process_scheduled_agent_removals(), osd_trans_commit_cb(), osd_trans_stop_cb(), osp_get_next_request(), osp_invalidate_request(), osp_object_free(), osp_trans_callback(), osp_trans_commit_cb(), osp_trans_stop_cb(), osp_unplug_async_request(), osp_update_fini(), osp_update_interpret(), osp_update_request_destroy(), ptlrpc_at_check_timed(), ptlrpc_commit_replies(), ptlrpc_free_committed(), ptlrpc_nrs_fini(), ptlrpc_pinger_remove_timeouts(), ptlrpc_replay_interpret(), ptlrpc_resend(), ptlrpc_set_wait(), put_pages_back_on_all_cpus(), put_pages_on_tcd_daemon_list(), qmt_reba_thread(), qsd_cleanup_deferred(), qsd_kickoff_deferred(), qsd_pending_updates(), qsd_upd_thread(), sa_put(), sptlrpc_cli_ctx_wakeup(), sptlrpc_conf_fini(), sptlrpc_conf_free_rsets(), tgt_cancel_slc_locks(), tgt_client_free(), tgt_handle_received_xid(), tgt_handle_tag(), top_multiple_thandle_destroy(), trace_cleanup_on_all_cpus(), tracefiled(), unlock_zero_regions(), upcall_cache_flush(), upcall_cache_get_entry(), and update_is_committed().
#define list_for_each_prev (pos, head)
Value:
for (pos = (head)->prev, prefetch(pos->prev); pos != (head);     \
                pos = pos->prev, prefetch(pos->prev))
Iterate over a list in reverse order.
Parameters:
pos the &struct list_head to use as a loop counter.
head the head for your list.
Definition at line 449 of file list.h.
Referenced by lnet_rtr_addref_locked(), ptlrpc_add_unreplied(), ptlrpc_retain_replayable_request(), and stt_add_timer().
#define list_for_each_safe (pos, n, head)
Value:
for (pos = (head)->next, n = pos->next; pos != (head); \
                pos = n, n = pos->next)
Iterate over a list safely.
Parameters:
pos the iterator
n temporary storage
head the list to iterate over
This is safe to use if pos could be removed from the list in the body of the loop.
Definition at line 266 of file list.h.
Referenced by cfs_free_nidlist(), fail_peer(), kgnilnd_close_peer_conns_locked(), kgnilnd_close_stale_conns_locked(), kgnilnd_del_conn_or_peer(), kgnilnd_reaper_check(), kiblnd_abort_txs(), kiblnd_close_matching_conns(), kiblnd_close_peer_conns_locked(), kiblnd_close_stale_conns_locked(), kiblnd_del_peer(), kiblnd_del_peer_locked(), ksocknal_close_matching_conns(), ksocknal_close_peer_conns_locked(), ksocknal_del_interface(), ksocknal_del_peer(), ksocknal_del_peer_locked(), ksocknal_del_route_locked(), ksocknal_peer_del_interface_locked(), ldlm_resource_foreach(), lnet_fail_nid(), lnet_match_networks(), lov_cleanup(), lov_finish_set(), mgs_cleanup_fsdb_list(), osc_wake_cache_waiters(), ptlrpc_abort_inflight(), ptlrpc_abort_set(), ptlrpc_check_set(), ptlrpc_free_rq_pool(), ptlrpc_inflight_timeout(), ptlrpc_invalidate_import(), ptlrpc_replay_next(), ptlrpc_server_drop_request(), ptlrpc_set_destroy(), ptlrpc_wake_delayed(), ptlrpcd_add_rqset(), ptlrpcd_check(), ptlrpcd_steal_rqset(), qmt_glimpse_lock(), and qmt_pool_fini().
#define LIST_HEAD_INIT (name) { &(name), &(name) }
Definition at line 46 of file list.h.
Referenced by kiblnd_abort_txs(), kiblnd_check_conns(), kiblnd_del_peer(), kiblnd_dev_failover(), kiblnd_fmr_pool_unmap(), kiblnd_peer_connect_failed(), kiblnd_pool_free_node(), ksocknal_connect(), ksocknal_create_conn(), ksocknal_del_peer(), ksocknal_finalize_zcreq(), ksocknal_flush_stale_txs(), ksocknal_handle_zcack(), ksocknal_scheduler(), ldlm_cancel_lru(), ldlm_cancel_unused_locks_for_replay(), ldlm_cli_cancel(), ldlm_cli_cancel_list_local(), ldlm_cli_cancel_unused_resource(), ldlm_prep_elc_req(), ldlm_replay_locks(), lnet_clear_lazy_portal(), lnet_match_network_token(), LNetMDAttach(), lov_putref(), lustre_pack_request(), mdc_create(), mdc_intent_getxattr_pack(), mdc_intent_open_pack(), mdc_ioc_swap_layouts(), mdc_link(), mdc_rename(), mdc_setattr(), mdc_unlink(), mdc_xattr_common(), mgs_fsc_cleanup(), mgs_nidtbl_fini_fs(), osc_build_rpc(), osc_destroy(), osc_io_submit(), osc_lru_add_batch(), osc_send_read_rpc(), osc_send_write_rpc(), and qmt_glimpse_lock().
#define NULL_P ((void *)0)
Definition at line 305 of file list.h.
#define prefetch (a) ((void)a)
Definition at line 40 of file list.h.
Function Documentation
static void __list_add (struct list_head * new, struct list_head * prev, struct list_head * next) [inline, static]
Insert a new entry between two known consecutive entries.
This is only for internal list manipulation where we know the prev/next entries already!
Definition at line 58 of file list.h.
References list_head::next, and list_head::prev.
Referenced by list_add(), and list_add_tail().
static void __list_del (struct list_head * prev, struct list_head * next) [inline, static]
Definition at line 103 of file list.h.
References list_head::next, and list_head::prev.
Referenced by list_del(), list_del_init(), list_move(), and list_move_tail().
static void __list_splice (struct list_head * list, struct list_head * head) [inline, static]
Definition at line 184 of file list.h.
References list_head::next, and list_head::prev.
Referenced by list_splice(), list_splice_init(), and list_splice_tail().
static void list_add (struct list_head * new, struct list_head * head) [inline, static]
Insert an entry at the start of a list.
Parameters:
new new entry to be inserted
head list to add it to
Insert a new entry after the specified head. This is good for implementing stacks.
Definition at line 76 of file list.h.
References __list_add(), and list_head::next.
Referenced by __sa_make_ready(), cfs_wi_sched_create(), cfs_wi_schedule(), cl_echo_enqueue0(), cl_env_put(), cl_io_lock_add(), class_add_profile(), class_add_uuid(), class_dentry_readdir(), class_new_export(), class_register_type(), create_sub_thandle(), cYAML_ll_push(), distribute_txn_insert_by_batchid(), do_config_log_add(), dt_txn_callback_add(), dtrq_insert(), dtrq_sub_add_cookie(), dtrq_sub_create_and_insert(), dynlock_lock(), fail_peer(), fld_cache_entry_add(), iam_format_register(), import_set_conn(), init_blwi(), it_test_helper(), kgnilnd_tx_add_state_locked(), kiblnd_abort_txs(), kiblnd_check_conns(), kiblnd_connreq_done(), kiblnd_fail_fmr_poolset(), kiblnd_fail_poolset(), kiblnd_init_poolset(), kiblnd_map_tx_pool(), kiblnd_peer_connect_failed(), kiblnd_pool_free_node(), kiblnd_post_tx_locked(), ksocknal_create_conn(), ksocknal_finalize_zcreq(), ksocknal_free_buffers(), ksocknal_free_tx(), ksocknal_handle_zcack(), ksocknal_queue_tx_msg_v2(), ksocknal_reaper(), ksocknal_scheduler(), ksocknal_startup(), ldlm_add_bl_work_item(), ldlm_add_cp_work_item(), ldlm_cancel_resource_local(), ldlm_chain_lock_for_replay(), ldlm_cli_cancel(), ldlm_cli_cancel_list_local(), ldlm_granted_list_add_lock(), ldlm_namespace_register(), ldlm_prepare_lru_list(), ldlm_resource_insert_lock_after(), lgss_mech_register(), libcfs_kkuc_group_add(), list_move(), ll_cl_add(), ll_xattr_cache_add(), lnet_add_route_to_rnet(), lnet_clear_zombies_nis_locked(), lnet_delay_rule_add(), lnet_destroy_peer_locked(), lnet_drop_rule_add(), lnet_fail_nid(), lnet_match_networks(), lnet_md_link(), lnet_msg_commit(), lnet_nid2peer_locked(), lnet_prune_rc_data(), lnet_res_lh_initialize(), lnet_return_rx_credits_locked(), lnet_rtr_addref_locked(), lnet_rtr_decref_locked(), lnet_rtrpool_adjust_bufs(), LNetEQAlloc(), LNetMEAttach(), LNetMEInsert(), local_oid_storage_init(), lock_region(), lod_putref(), lov_putref(), lprocfs_nodemap_register(), ls_device_get(), lst_alloc_rpcent(), lstcon_rpc_cleanup_wait(), lstcon_rpc_put(), lu_context_init(), lu_dev_add_linkage(), lu_device_type_init(), lu_site_init_finish(), lustre_put_emerg_rs(), lustre_register_lwp_item(), mdt_mfd_open(), mgs_fsc_attach(), mgs_new_fsdb(), nm_config_file_register(), nm_hash_list_cb(), nm_member_add(), nm_member_reclassify_nodemap(), nodemap_add_range_helper(), nodemap_cleanup_iter_cb(), nodemap_process_keyrec(), obd_stale_export_put(), obd_zombie_export_add(), obd_zombie_import_add(), osc_lru_add_batch(), osc_set_info_async(), osd_find_or_add_seq(), osd_object_sa_dirty_add(), osd_object_unlinked_add(), osd_process_scheduled_agent_removals(), osd_schedule_agent_inode_removal(), osd_seq_load(), osd_trans_cb_add(), osp_sync_id_get(), osp_sync_id_traction_init(), osp_sync_interpret(), osp_sync_request_commit_cb(), osp_trans_cb_add(), ping_evictor_wake(), ptlrpc_add_timeout_client(), ptlrpc_add_unreplied(), ptlrpc_alloc_rqbd(), ptlrpc_at_add_timed(), ptlrpc_at_check_timed(), ptlrpc_connect_set_flags(), ptlrpc_main(), ptlrpc_pinger_register_timeout(), ptlrpc_register_service(), ptlrpc_request_change_export(), ptlrpc_retain_replayable_request(), ptlrpc_server_drop_request(), ptlrpc_server_post_idle_rqbds(), ptlrpc_server_request_add(), ptlrpc_start_thread(), ptlrpc_svcpt_stop_threads(), qsd_add_deferred(), qsd_adjust_schedule(), server_register_mount(), sfw_client_rpc_fini(), sfw_deactivate_session(), sfw_run_test(), sfw_test_rpc_fini(), sptlrpc_conf_get(), sptlrpc_conf_get_tgt(), sptlrpc_gc_add_ctx(), sptlrpc_req_refresh_ctx(), srpc_server_rpc_done(), srpc_service_init(), srpc_service_post_buffer(), stt_add_timer(), sub_updates_write(), target_send_reply(), tgt_add_reply_data(), tgt_reply_data_init(), upcall_cache_get_entry(), and upcall_msg_enlist().
static void list_add_tail (struct list_head * new, struct list_head * head) [inline, static]
Insert an entry at the end of a list.
Parameters:
new new entry to be inserted
head list to add it to
Insert a new entry before the specified head. This is useful for implementing queues.
Definition at line 90 of file list.h.
References __list_add(), and list_head::prev.
Referenced by __ldlm_bl_to_thread(), __ptlrpc_free_req_to_pool(), _kgnilnd_schedule_conn(), add_nidrange(), cfs_expr_list_parse(), cfs_ip_addr_parse(), cfs_trace_get_tage_try(), cfs_trace_refill_stock(), cfs_wi_schedule(), cl_io_slice_add(), cl_lock_slice_add(), cl_page_list_add(), cl_page_slice_add(), class_new_export(), delay_rule_match(), delay_timer_cb(), distribute_txn_assign_batchid(), echo_object_init(), fld_client_add_target(), hsm_restore_cb(), import_set_conn(), it_test_init(), jt_lst_show_error(), jt_lst_stat(), kgnilnd_add_peer_locked(), kgnilnd_add_purgatory_tx(), kgnilnd_alloc_fmablk(), kgnilnd_cancel_peer_connect_locked(), kgnilnd_cancel_wc_dgrams(), kgnilnd_check_peer_timeouts_locked(), kgnilnd_complete_closed_conn(), kgnilnd_detach_purgatory_locked(), kgnilnd_find_or_create_conn_locked(), kgnilnd_finish_connect(), kgnilnd_mem_add_map_list(), kgnilnd_post_dgram(), kgnilnd_release_dgram(), kgnilnd_start_outbound_dgrams(), kgnilnd_startup(), kgnilnd_tx_add_state_locked(), kiblnd_alloc_freg_pool(), kiblnd_check_sends(), kiblnd_close_conn_locked(), kiblnd_connd(), kiblnd_cq_completion(), kiblnd_create_conn(), kiblnd_create_dev(), kiblnd_failover_thread(), kiblnd_fmr_pool_map(), kiblnd_fmr_pool_unmap(), kiblnd_init_fmr_poolset(), kiblnd_launch_tx(), kiblnd_passive_connect(), kiblnd_pool_alloc_node(), kiblnd_queue_tx_locked(), kiblnd_rx_complete(), kiblnd_scheduler(), kiblnd_startup(), ksocknal_accept(), ksocknal_add_peer(), ksocknal_add_route_locked(), ksocknal_check_zc_req(), ksocknal_close_conn_locked(), ksocknal_connect(), ksocknal_create_conn(), ksocknal_flush_stale_txs(), ksocknal_launch_connection_locked(), ksocknal_launch_packet(), ksocknal_process_transmit(), ksocknal_queue_tx_locked(), ksocknal_queue_tx_msg_v1(), ksocknal_queue_tx_msg_v2(), ksocknal_queue_tx_zcack_v2(), ksocknal_queue_tx_zcack_v3(), ksocknal_queue_zombie_conn(), ksocknal_read_callback(), ksocknal_reaper(), ksocknal_recv(), ksocknal_scheduler(), ksocknal_terminate_conn(), ksocknal_write_callback(), ldlm_cleanup(), ldlm_interval_attach(), ldlm_lock_add_to_lru_nolock(), ldlm_resource_add_lock(), lfsck_add_target(), lfsck_assistant_notify_others(), lfsck_async_interpret_common(), lfsck_instance_add(), lfsck_layout_llst_add(), lfsck_layout_master_in_notify(), lfsck_layout_scan_stripes(), lfsck_layout_seq_insert(), lfsck_layout_setup(), lfsck_namespace_close_dir(), lfsck_namespace_exec_dir(), lfsck_namespace_in_notify(), lfsck_namespace_notify_lmv_master_local(), lfsck_namespace_prep(), lfsck_namespace_setup(), libcfs_num_parse(), libcfs_register_ioctl(), list_move_tail(), ll_agl_add(), ll_iocontrol_register(), ll_statahead_interpret(), llog_cat_declare_add_rec(), llog_cat_id2handle(), lnet_add_route(), lnet_expand1tb(), lnet_fail_nid(), lnet_finalize(), lnet_match_networks(), lnet_ni_alloc(), lnet_nid2peer_locked(), lnet_parse_route(), lnet_post_routed_recv_locked(), lnet_post_send_locked(), lnet_ptl_attach_md(), lnet_ptl_match_delay(), lnet_ptl_match_early(), lnet_ptl_match_md(), lnet_register_lnd(), lnet_splitnets(), lnet_startup_lndni(), lnet_str2tbs_sep(), LNetMEAttach(), LNetMEInsert(), lod_pool_new(), lov_io_iter_init(), lov_pool_new(), lov_set_add_req(), lst_print_stat(), lstcon_acceptor_handle(), lstcon_batch_add(), lstcon_group_add(), lstcon_group_ndlink_find(), lstcon_group_ndlink_move(), lstcon_ndlink_find(), lstcon_node_find(), lstcon_rpc_trans_addreq(), lstcon_rpc_trans_prep(), lstcon_test_add(), lstcon_testrpc_condition(), lu_object_put(), lustre_idmap_add(), lustre_lwp_setup(), mdt_cdt_add_request(), mdt_hsm_add_actions(), mdt_hsm_agent_register(), mdt_lock_objects_in_linkea(), nrs_fifo_req_add(), nrs_policy_register(), obd_get_request_slot(), obd_stale_export_put(), ofd_add_inconsistency_item(), ofd_fmd_find_nolock(), ofd_fmd_get(), ofd_intent_policy(), ofd_seq_add(), on_list(), osc_build_rpc(), osc_enter_cache(), osc_io_submit(), osc_lock_enqueue_wait(), osc_setup(), osd_ios_new_item(), osd_it_add_processed(), osd_oii_insert(), osp_check_and_set_rpc_version(), osp_insert_update_callback(), osp_oac_xattr_find_or_add(), osp_oac_xattr_replace(), osp_object_update_request_create(), osp_sync_send_new_rpc(), parse_addrange(), ptlrpc_add_rqs_to_pool(), ptlrpc_check_set(), ptlrpc_dispatch_difficult_reply(), ptlrpc_nrs_policy_register(), ptlrpc_nrs_req_add_nolock(), ptlrpc_pinger_add_import(), ptlrpc_req_add_history(), ptlrpc_send_new_req(), ptlrpc_server_drop_request(), ptlrpc_server_post_idle_rqbds(), ptlrpc_set_add_cb(), ptlrpc_set_add_new_req(), ptlrpc_set_add_req(), qmt_glimpse_lock(), qmt_id_lock_notify(), qmt_pool_alloc(), qos_add_tgt(), qsd_add_deferred(), qsd_adjust_schedule(), qsd_get_fsinfo(), qsd_init(), qsd_upd_add(), range_lock(), request_in_callback(), sa_rehash(), sfw_add_test_instance(), sfw_bid2batch(), sfw_register_test(), sfw_run_test(), sptlrpc_gc_add_sec(), srpc_lnet_ev_handler(), srpc_server_rpc_done(), target_send_reply(), and tgt_save_slc_lock().
static void list_del (struct list_head * entry) [inline, static]
Remove an entry from the list it is currently in.
Parameters:
entry the entry to remove Note: list_empty(entry) does not return true after this, the entry is in an undefined state.
Definition at line 116 of file list.h.
References __list_del(), list_head::next, and list_head::prev.
Referenced by cfs_expr_list_free(), cfs_expr_list_free_list(), cfs_free_nidlist(), cfs_trace_debug_print(), cfs_trace_flush_pages(), cfs_tracefile_dump_all_pages(), cfs_wi_sched_destroy(), cfs_wi_shutdown(), class_del_profile(), class_del_profiles(), class_del_uuid(), class_unregister_type(), client_common_put_super(), client_import_del_conn(), config_log_put(), cYAML_ll_pop(), dtrq_destroy(), dynlock_unlock(), fail_peer(), fld_cache_entry_delete(), fld_client_del_target(), fld_client_fini(), free_addrranges(), free_entry(), hsm_cdt_request_completed(), idmap_entry_free(), import_set_conn(), jt_lst_show_error(), jt_lst_stat(), kgnilnd_free_fmablk_locked(), kiblnd_abort_txs(), kiblnd_alloc_freg_pool(), kiblnd_check_conns(), kiblnd_check_sends(), kiblnd_close_conn_locked(), kiblnd_connd(), kiblnd_connreq_done(), kiblnd_destroy_dev(), kiblnd_destroy_fmr_pool(), kiblnd_destroy_fmr_pool_list(), kiblnd_destroy_pool_list(), kiblnd_destroy_tx_pool(), kiblnd_fail_fmr_poolset(), kiblnd_fail_poolset(), kiblnd_fmr_pool_map(), kiblnd_handle_completion(), kiblnd_handle_early_rxs(), kiblnd_handle_rx(), kiblnd_pool_alloc_node(), kiblnd_post_tx_locked(), kiblnd_scheduler(), kiblnd_shutdown(), kiblnd_tx_complete(), kiblnd_txlist_done(), ksocknal_alloc_tx(), ksocknal_close_conn_locked(), ksocknal_connd(), ksocknal_connect(), ksocknal_create_conn(), ksocknal_del_route_locked(), ksocknal_finalize_zcreq(), ksocknal_flush_stale_txs(), ksocknal_free_buffers(), ksocknal_handle_zcack(), ksocknal_queue_tx_msg_v2(), ksocknal_reaper(), ksocknal_scheduler(), ksocknal_shutdown(), ksocknal_txlist_done(), ksocknal_uncheck_zc_req(), ksocknal_unlink_peer_locked(), ldlm_bl_get_work(), lfsck_lmv_put(), lgss_mech_unregister(), libcfs_kkuc_group_rem(), ll_iocontrol_unregister(), ll_xattr_cache_del(), lnet_del_route(), lnet_drop_delayed_msg_list(), lnet_drop_rule_del(), lnet_fail_nid(), lnet_finalize(), lnet_free_text_bufs(), lnet_match_networks(), lnet_me_unlink(), lnet_msg_container_cleanup(), lnet_msg_decommit(), lnet_nid2peer_locked(), lnet_parse_networks(), lnet_parse_route(), lnet_parse_route_tbs(), lnet_peer_tables_cleanup(), lnet_post_routed_recv_locked(), lnet_ptl_cleanup(), lnet_recv_delayed_msg_list(), lnet_res_lh_invalidate(), lnet_return_rx_credits_locked(), lnet_return_tx_credits_locked(), lnet_rtr_decref_locked(), lnet_rtrpool_adjust_bufs(), lnet_rtrpool_free_bufs(), lnet_schedule_blocked_locked(), lnet_startup_lndnis(), lnet_unregister_lnd(), LNetEQFree(), local_oid_storage_fini(), local_oid_storage_init(), lod_putref(), lov_putref(), lprocfs_nodemap_remove(), ls_device_put(), lst_free_rpcent(), lst_print_stat(), lstcon_batch_destroy(), lstcon_group_decref(), lstcon_group_ndlink_move(), lstcon_ndlink_release(), lstcon_node_put(), lstcon_rpc_cleanup_wait(), lstcon_rpc_trans_destroy(), lustre_get_emerg_rs(), mdt_cdt_remove_request(), mdt_hsm_agent_send(), mdt_hsm_cdt_stop(), mdt_unlock_list(), mgs_free_fsdb(), mgs_nidtbl_fini_fs(), nm_config_file_deregister(), nm_config_file_register(), nodemap_add_range_helper(), nodemap_procfs_exit(), nrs_policy_unregister(), obd_get_request_slot(), ofd_fmd_find_nolock(), ofd_fmd_put_nolock(), osc_cleanup(), osd_object_delete(), osd_ost_seq_fini(), osd_process_scheduled_agent_removals(), osp_object_free(), osp_sync_id_traction_fini(), osp_update_request_destroy(), ptlrpc_connect_set_flags(), ptlrpc_del_timeout_client(), ptlrpc_free_rq_pool(), ptlrpc_free_rqbd(), ptlrpc_nrs_policy_unregister(), ptlrpc_pinger_remove_timeouts(), ptlrpc_server_drop_request(), ptlrpc_server_post_idle_rqbds(), ptlrpc_service_purge_all(), ptlrpc_start_thread(), ptlrpc_svcpt_stop_threads(), put_pages_on_tcd_daemon_list(), qmt_glimpse_lock(), qos_add_tgt(), qos_del_tgt(), qsd_put_fsinfo(), range_delete(), server_deregister_mount(), sfw_create_rpc(), sfw_destroy_test_instance(), sfw_shutdown(), sptlrpc_conf_free(), sptlrpc_conf_free_rsets(), srpc_lnet_ev_handler(), srpc_server_rpc_done(), srpc_service_fini(), srpc_service_post_buffer(), tgt_free_reply_data(), thandle_get_sub_by_dt(), top_multiple_thandle_destroy(), trace_cleanup_on_all_cpus(), and unlock_zero_regions().
static void list_del_init (struct list_head * entry) [inline, static]
Remove an entry from the list it is currently in and reinitialize it.
Parameters:
entry the entry to remove.
Definition at line 125 of file list.h.
References __list_del(), INIT_LIST_HEAD, list_head::next, and list_head::prev.
Referenced by __lfsck_instance_find(), __osc_extent_remove(), __osc_lru_del(), __ptlrpc_free_req(), after_reply(), brw_interpret(), cfs_trace_get_tage_try(), cfs_wi_deschedule(), cfs_wi_exit(), cfs_wi_scheduler(), check_unlink_entry(), cl_echo_cancel0(), cl_env_cache_purge(), cl_env_obtain(), cl_io_fini(), cl_io_unlock(), cl_lock_fini(), cl_page_free(), cl_page_list_del(), cl_page_list_disown(), class_disconnect_export_list(), class_import_destroy(), class_setup(), class_unlink_export(), delayed_msg_process(), distribute_txn_commit_thread(), distribute_txn_get_next_req(), dt_txn_callback_del(), dtrq_list_destroy(), echo_client_setup(), echo_object_free(), gss_unhash_msg_nolock(), htable_lookup(), init_blwi(), insert_update_records_to_replay_list(), it_test_helper(), kgnilnd_cancel_peer_connect_locked(), kgnilnd_cancel_wc_dgrams(), kgnilnd_close_conn_locked(), kgnilnd_complete_closed_conn(), kgnilnd_detach_purgatory_locked(), kgnilnd_finish_connect(), kgnilnd_mem_del_map_list(), kgnilnd_probe_and_process_dgram(), kgnilnd_probe_for_dgram(), kgnilnd_process_conns(), kgnilnd_release_purgatory_list(), kgnilnd_reset_stack(), kgnilnd_shutdown(), kgnilnd_start_outbound_dgrams(), kgnilnd_tx_del_state_locked(), kgnilnd_txlist_done(), kgnilnd_unlink_peer_locked(), kiblnd_connreq_done(), kiblnd_failover_thread(), kiblnd_peer_connect_failed(), kiblnd_unlink_peer_locked(), ksocknal_create_conn(), ksocknal_free_buffers(), ksocknal_reaper(), ksocknal_scheduler(), ldlm_cli_cancel_list_local(), ldlm_export_cancel_blocked_locks(), ldlm_flock_destroy(), ldlm_interval_detach(), ldlm_lock_remove_from_lru_nolock(), ldlm_namespace_unregister(), ldlm_process_flock_lock(), ldlm_replay_locks(), ldlm_resource_unlink_lock(), ldlm_unlink_lock_skiplist(), ldlm_work_bl_ast_lock(), ldlm_work_cp_ast_lock(), ldlm_work_gl_ast_lock(), ldlm_work_revoke_ast_lock(), lfsck_add_target_from_orphan(), lfsck_assistant_engine(), lfsck_assistant_notify_others(), lfsck_async_interpret_common(), lfsck_component_cleanup(), lfsck_del_target(), lfsck_exit(), lfsck_layout_assistant_handler_p2(), lfsck_layout_llst_del(), lfsck_layout_llst_find_and_del(), lfsck_layout_master_data_release(), lfsck_layout_master_double_scan(), lfsck_layout_master_in_notify(), lfsck_layout_master_quit(), lfsck_layout_slave_quit(), lfsck_master_oit_engine(), lfsck_namespace_assistant_handler_p2(), lfsck_namespace_data_release(), lfsck_namespace_double_scan(), lfsck_namespace_in_notify(), lfsck_namespace_post(), lfsck_namespace_prep(), lfsck_namespace_quit(), lfsck_namespace_rescan_striped_dir(), lfsck_post(), lfsck_quit(), lfsck_start(), lfsck_stop_notify(), lfsck_tgt_descs_fini(), libcfs_deregister_ioctl(), ll_agl_thread(), ll_cl_remove(), ll_statahead_thread(), llog_cat_cleanup(), llog_cat_close(), lnet_clear_zombies_nis_locked(), lnet_delay_rule_check(), lnet_delay_rule_del(), lnet_drop_routed_msgs_locked(), lnet_dyn_add_ni(), lnet_md_unlink(), lnet_ni_unlink_locked(), lnet_peer_table_cleanup_locked(), lnet_prune_rc_data(), lnet_ptl_attach_md(), lnet_ptl_match_delay(), lnet_res_container_cleanup(), LNetNIInit(), lod_pool_del(), lod_pool_new(), lov_finish_set(), lov_io_iter_fini(), lov_pool_del(), lov_pool_new(), lstcon_batch_destroy(), lstcon_group_ndlink_release(), lstcon_rpc_cleanup_wait(), lstcon_rpc_pinger(), lstcon_rpc_prep(), lstcon_rpc_trans_destroy(), lu_context_fini(), lu_dev_del_linkage(), lu_device_type_fini(), lu_object_free(), lu_object_unhash(), lu_site_fini(), lu_site_purge(), lustre_deregister_lwp_item(), lustre_stop_lwp(), mdt_close_internal(), mdt_connect_internal(), mdt_export_cleanup(), mdt_hsm_agent_unregister(), mdt_mfd_open(), mdt_obd_connect(), mdt_steal_ack_locks(), mgs_erase_logs(), mgs_fsc_cleanup(), mgs_fsc_cleanup_by_fsdb(), mgs_list_logs(), mgs_write_log_direct_all(), nm_member_del(), nm_member_delete_list(), nm_member_reclassify_nodemap(), nrs_fifo_req_del(), nrs_fifo_req_get(), nrs_request_removed(), obd_put_request_slot(), obd_set_max_rpcs_in_flight(), obd_stale_export_get(), obd_zombie_export_add(), obd_zombie_impexp_cull(), ofd_fmd_cleanup(), ofd_fmd_expire_nolock(), ofd_inconsistency_verification_main(), ofd_parse_connect_data(), ofd_seqs_free(), on_list(), osc_build_rpc(), osc_cleanup(), osc_enter_cache(), osc_extent_hold(), osc_extent_merge(), osc_extent_truncate(), osc_lock_wake_waiters(), osc_send_write_rpc(), osc_wake_cache_waiters(), osd_initial_OI_scrub(), osd_it_acct_fini(), osd_object_sa_dirty_rele(), osd_ost_fini(), osd_scrub_main(), osd_scrub_next(), osd_trans_commit_cb(), osd_trans_stop_cb(), osd_unlinked_list_emptify(), osp_get_next_request(), osp_invalidate_request(), osp_oac_xattr_find(), osp_oac_xattr_replace(), osp_sync_interpret(), osp_sync_process_committed(), osp_sync_remove_from_tracker(), osp_trans_callback(), osp_trans_commit_cb(), osp_trans_stop_cb(), osp_unplug_async_request(), osp_update_fini(), osp_update_interpret(), ping_evictor_main(), ptlrpc_at_check_timed(), ptlrpc_at_remove_timed(), ptlrpc_check_set(), ptlrpc_commit_replies(), ptlrpc_del_timeout_client(), ptlrpc_free_request(), ptlrpc_handle_rs(), ptlrpc_hr_main(), ptlrpc_nrs_fini(), ptlrpc_pinger_del_import(), ptlrpc_prep_req_from_pool(), ptlrpc_request_change_export(), ptlrpc_schedule_difficult_reply(), ptlrpc_send_new_req(), ptlrpc_server_drop_request(), ptlrpc_server_handle_req_in(), ptlrpc_server_hpreq_fini(), ptlrpc_set_destroy(), ptlrpc_set_wait(), ptlrpc_unregister_service(), ptlrpcd_check(), qmt_pool_fini(), qmt_reba_thread(), qsd_add_deferred(), qsd_adjust_schedule(), qsd_cleanup_adjust(), qsd_cleanup_deferred(), qsd_fini(), qsd_kickoff_deferred(), qsd_pending_updates(), qsd_upd_thread(), range_unlock(), req_off_ctx_list(), sa_handle_callback(), sa_kill(), sa_unhash(), sec_process_ctx_list(), sfw_create_test_rpc(), sfw_deactivate_session(), sfw_destroy_batch(), sfw_destroy_session(), sfw_test_rpc_done(), sfw_test_unit_done(), sptlrpc_cli_ctx_wakeup(), sptlrpc_gc_del_sec(), sptlrpc_req_put_ctx(), stt_del_timer(), stt_expire_list(), tgt_cancel_slc_locks(), tgt_discard_slc_lock(), tgt_release_reply_data(), upcall_cache_downcall(), upcall_msg_delist(), and work_interpreter().
static int list_empty (struct list_head * head) [inline, static]
Test whether a list is empty.
Parameters:
head the list to test.
Definition at line 161 of file list.h.
References list_head::next.
Referenced by __ldlm_resource_putref_final(), __osc_extent_remove(), __ptlrpc_free_req(), __ptlrpc_free_req_to_pool(), __sa_make_ready(), _kgnilnd_schedule_conn(), after_reply(), agl_list_empty(), brw_interpret(), cfs_expr_list_free(), cfs_expr_list_free_list(), cfs_print_nidlist(), cfs_trace_get_tage_try(), cfs_tracefile_dump_all_pages(), cfs_wi_deschedule(), cfs_wi_exit(), cfs_wi_sched_cansleep(), cfs_wi_sched_destroy(), cfs_wi_schedule(), cfs_wi_scheduler(), cfs_wi_shutdown(), cl_echo_enqueue0(), cl_env_cache_purge(), cl_env_obtain(), cl_io_fini(), cl_io_slice_add(), cl_io_submit_rw(), cl_io_submit_sync(), cl_lock_fini(), cl_page_free(), cl_page_list_add(), cl_page_put(), class_del_uuid(), class_disconnect_export_list(), class_disconnect_exports(), class_export_destroy(), class_export_put(), class_handle_hash(), class_handle_unhash_nolock(), class_import_destroy(), class_import_put(), client_import_del_conn(), cYAML_ll_pop(), cYAML_tree_init(), delay_rule_decref(), delay_timer_cb(), delayed_msg_check(), delayed_msg_process(), distribute_txn_get_next_req(), distribute_txn_get_next_transno(), distribute_txn_insert_by_batchid(), dtrq_destroy(), dtrq_insert(), echo_client_cleanup(), echo_device_free(), echo_lock_fini(), fail_peer(), free_addrranges(), get_write_extents(), gss_exit_pipefs_upcall(), gss_pipe_destroy_msg(), gss_pipe_release(), gss_release_msg(), gss_unhash_msg_nolock(), hrt_dont_sleep(), htable_lookup(), import_sec_validate_get(), import_select_connection(), jt_lst_show_error(), jt_lst_stat(), kgnilnd_add_purgatory_locked(), kgnilnd_base_shutdown(), kgnilnd_can_unlink_peer_locked(), kgnilnd_cancel_peer_connect_locked(), kgnilnd_check_fma_send_cq(), kgnilnd_check_peer_timeouts_locked(), kgnilnd_close_conn_locked(), kgnilnd_complete_closed_conn(), kgnilnd_destroy_conn(), kgnilnd_destroy_peer(), kgnilnd_dev_fini(), kgnilnd_finish_connect(), kgnilnd_free_tx(), kgnilnd_mem_add_map_list(), kgnilnd_mem_del_map_list(), kgnilnd_peer_active(), kgnilnd_probe_and_process_dgram(), kgnilnd_probe_for_dgram(), kgnilnd_process_conns(), kgnilnd_process_fmaq(), kgnilnd_process_mapped_tx(), kgnilnd_process_nak(), kgnilnd_process_rdmaq(), kgnilnd_release_dgram(), kgnilnd_reset_stack(), kgnilnd_shutdown(), kgnilnd_start_outbound_dgrams(), kgnilnd_tx_add_state_locked(), kgnilnd_tx_del_state_locked(), kgnilnd_txlist_done(), kgnilnd_unlink_peer_locked(), kiblnd_base_shutdown(), kiblnd_check_conns(), kiblnd_check_reconnect(), kiblnd_check_sends(), kiblnd_close_conn_locked(), kiblnd_connd(), kiblnd_connreq_done(), kiblnd_del_peer(), kiblnd_del_peer_locked(), kiblnd_destroy_conn(), kiblnd_destroy_dev(), kiblnd_destroy_peer(), kiblnd_destroy_pool_list(), kiblnd_dev_can_failover(), kiblnd_dev_failover(), kiblnd_fail_fmr_poolset(), kiblnd_fail_poolset(), kiblnd_failover_thread(), kiblnd_fini_pool(), kiblnd_fmr_pool_map(), kiblnd_fmr_pool_unmap(), kiblnd_get_conn_locked(), kiblnd_handle_early_rxs(), kiblnd_launch_tx(), kiblnd_need_noop(), kiblnd_peer_active(), kiblnd_peer_connect_failed(), kiblnd_peer_idle(), kiblnd_pool_alloc_node(), kiblnd_pool_free_node(), kiblnd_reconnect_peer(), kiblnd_scheduler(), kiblnd_shutdown(), kiblnd_txlist_done(), kiblnd_unlink_peer_locked(), ksocknal_alloc_tx(), ksocknal_base_shutdown(), ksocknal_check_peer_timeouts(), ksocknal_close_conn_locked(), ksocknal_connd(), ksocknal_connd_check_start(), ksocknal_connect(), ksocknal_create_conn(), ksocknal_debug_peerhash(), ksocknal_del_peer(), ksocknal_del_route_locked(), ksocknal_destroy_conn(), ksocknal_destroy_peer(), ksocknal_finalize_zcreq(), ksocknal_find_timed_out_conn(), ksocknal_flush_stale_txs(), ksocknal_free_buffers(), ksocknal_get_peer_info(), ksocknal_handle_zcack(), ksocknal_lib_send_iov(), ksocknal_lib_send_kiov(), ksocknal_next_tx_carrier(), ksocknal_peer_failed(), ksocknal_queue_tx_locked(), ksocknal_reaper(), ksocknal_sched_cansleep(), ksocknal_scheduler(), ksocknal_send_keepalive_locked(), ksocknal_terminate_conn(), ksocknal_txlist_done(), ksocknal_unlink_peer_locked(), ksocknal_write_callback(), ksocknal_write_space(), ldlm_add_bl_work_item(), ldlm_add_cp_work_item(), ldlm_bl_get_work(), ldlm_cancel_resource_local(), ldlm_chain_lock_for_replay(), ldlm_cleanup(), ldlm_cli_cancel(), ldlm_cli_cancel_list(), ldlm_export_cancel_blocked_locks(), ldlm_granted_list_add_lock(), ldlm_interval_detach(), ldlm_interval_extent(), ldlm_interval_free(), ldlm_lock_add_to_lru_nolock(), ldlm_lock_change_resource(), ldlm_lock_destroy_internal(), ldlm_lock_put(), ldlm_lock_remove_from_lru_check(), ldlm_lock_remove_from_lru_nolock(), ldlm_lock_touch_in_lru(), ldlm_namespace_first_locked(), ldlm_namespace_free_post(), ldlm_namespace_move_to_active_locked(), ldlm_namespace_move_to_inactive_locked(), ldlm_namespace_register(), ldlm_namespace_unregister(), ldlm_prepare_lru_list(), ldlm_reprocess_all(), ldlm_resource_add_lock(), ldlm_resource_dump(), ldlm_resource_insert_lock_after(), ldlm_run_ast_work(), ldlm_work_bl_ast_lock(), ldlm_work_cp_ast_lock(), ldlm_work_gl_ast_lock(), ldlm_work_revoke_ast_lock(), lfsck_add_target_from_orphan(), lfsck_assistant_engine(), lfsck_assistant_notify_others(), lfsck_assistant_query_others(), lfsck_assistant_req_empty(), lfsck_async_interpret_common(), lfsck_checkpoint_generic(), lfsck_component_cleanup(), lfsck_exit(), lfsck_instance_cleanup(), lfsck_layout_assistant_fill_pos(), lfsck_layout_assistant_handler_p2(), lfsck_layout_llst_del(), lfsck_layout_llst_put(), lfsck_layout_master_data_release(), lfsck_layout_master_double_scan(), lfsck_layout_master_in_notify(), lfsck_layout_master_quit(), lfsck_layout_slave_double_scan(), lfsck_layout_slave_in_notify(), lfsck_layout_slave_notify_master(), lfsck_layout_slave_prep(), lfsck_layout_slave_query_master(), lfsck_layout_slave_quit(), lfsck_master_engine(), lfsck_master_oit_engine(), lfsck_namespace_assistant_fill_pos(), lfsck_namespace_assistant_handler_p2(), lfsck_namespace_data_release(), lfsck_namespace_double_scan(), lfsck_namespace_in_notify(), lfsck_namespace_prep(), lfsck_namespace_quit(), lfsck_namespace_release_lmv(), lfsck_namespace_rescan_striped_dir(), lfsck_needs_scan_dir(), lfsck_phase2_next_ready(), lfsck_post(), lfsck_post_generic(), lfsck_start(), lfsck_stop_notify(), lfsck_tgt_descs_fini(), libcfs_deregister_ioctl(), libcfs_num_match(), libcfs_register_ioctl(), list_empty_marker(), list_splice(), list_splice_init(), list_splice_tail(), ll_agl_add(), ll_agl_trigger(), ll_clear_inode(), ll_compute_rootsquash_state(), ll_ddelete(), ll_free_sbi(), ll_invalidate_negative_children(), llog_free_handle(), llog_init_handle(), lnet_clear_zombies_nis_locked(), lnet_cpt_of_nid(), lnet_cpt_of_nid_locked(), lnet_del_route(), lnet_delay_rule_check(), lnet_delay_rule_daemon(), lnet_delay_rule_del(), lnet_destroy_peer_locked(), lnet_destroy_rc_data(), lnet_destroy_remote_nets_table(), lnet_drop_delayed_msg_list(), lnet_dyn_add_ni(), lnet_fail_nid(), lnet_fault_fini(), lnet_finalize(), lnet_free_text_bufs(), lnet_lib_exit(), lnet_match_networks(), lnet_md_link(), lnet_md_unlink(), lnet_msg_container_cleanup(), lnet_mt_match_md(), lnet_ni_unlink_locked(), lnet_nid2peer_locked(), lnet_parse(), lnet_parse_networks(), lnet_parse_route(), lnet_parse_route_tbs(), lnet_peer_tables_cleanup(), lnet_peer_tables_destroy(), lnet_post_routed_recv_locked(), lnet_post_send_locked(), lnet_prune_rc_data(), lnet_ptl_attach_md(), lnet_ptl_cleanup(), lnet_ptl_match_delay(), lnet_recv_delayed_msg_list(), lnet_res_container_cleanup(), lnet_return_rx_credits_locked(), lnet_return_tx_credits_locked(), lnet_router_checker_active(), lnet_rtr_decref_locked(), lnet_rtrpool_adjust_bufs(), lnet_rtrpool_free_bufs(), lnet_schedule_blocked_locked(), lnet_shutdown_lndnis(), lnet_splitnets(), lnet_startup_lndnis(), lnet_unprepare(), LNetDist(), LNetGet(), LNetNIInit(), LNetPut(), lod_pool_putref(), lov_io_iter_fini(), lov_pool_putref(), lov_statfs_async(), lovsub_lock_fini(), ls_device_put(), lst_free_rpcent(), lst_print_stat(), lstcon_batch_destroy(), lstcon_console_fini(), lstcon_group_clean(), lstcon_group_decref(), lstcon_group_move(), lstcon_group_ndlink_find(), lstcon_ndlink_release(), lstcon_node_put(), lstcon_nodes_remove(), lstcon_rpc_cleanup_wait(), lstcon_rpc_module_fini(), lstcon_rpc_pinger(), lstcon_rpc_pinger_start(), lstcon_rpc_prep(), lstcon_rpc_put(), lstcon_rpc_trans_check(), lstcon_rpc_trans_destroy(), lstcon_rpc_trans_postwait(), lstcon_session_end(), lstcon_session_new(), lstcon_testrpc_condition(), lu_context_fini(), lu_dev_add_linkage(), lu_object_fini(), lu_object_free(), lu_object_header_fini(), lu_object_header_print(), lu_object_put(), lu_object_top(), lu_object_unhash(), lu_site_obj_print(), lu_site_purge(), lustre_free_reply_state(), lustre_get_emerg_rs(), lustre_idmap_fini(), lustre_put_lwp_item(), lustre_stop_lwp(), mdt_coordinator(), mdt_destroy_export(), mdt_export_cleanup(), mdt_hsm_active_requests_proc_start(), mdt_hsm_agent_proc_start(), mdt_mfd_free(), mdt_nosquash_nids_seq_show(), mgs_direntry_free(), mgs_ir_fini_fs(), mgs_nidtbl_fini_fs(), nm_config_file_register(), nm_member_add(), nodemap_destroy(), nrs_fifo_req_del(), nrs_fifo_req_get(), nrs_fifo_stop(), nrs_policy_stop0(), obd_exports_barrier(), obd_get_request_slot(), obd_put_request_slot(), obd_request_slot_avail(), obd_set_max_rpcs_in_flight(), obd_stale_export_adjust(), obd_stale_export_get(), obd_stale_export_put(), obd_zombie_export_add(), obd_zombie_impexp_cull(), obd_zombie_import_add(), obdclass_exit(), ocw_granted(), ofd_add_inconsistency_item(), ofd_destroy_export(), ofd_get_info_hdl(), ofd_grant_sanity_check(), ofd_inconsistency_verification_main(), ofd_intent_policy(), ofd_seq_put(), ofd_seqs_fini(), ofd_seqs_free(), on_list(), osc_build_rpc(), osc_cache_shrink_scan(), osc_enter_cache(), osc_extent_put(), osc_extent_sanity_check0(), osc_extent_truncate(), osc_init_grant(), osc_io_commit_async(), osc_io_submit(), osc_is_ready(), osc_list(), osc_lock_wake_waiters(), osc_lru_add_batch(), osc_lru_del(), osc_lru_reclaim(), osc_lru_shrink(), osc_lru_use(), osc_makes_hprpc(), osc_makes_rpc(), osc_max_rpc_in_flight(), osc_next_obj(), osc_object_free(), osc_send_read_rpc(), osc_send_write_rpc(), osc_set_info_async(), osd_fid_lookup(), osd_initial_OI_scrub(), osd_inode_iteration(), osd_object_sa_dirty_add(), osd_object_sa_dirty_rele(), osd_object_unlinked_add(), osd_oii_insert(), osd_scrub_check_update(), osd_scrub_main(), osd_scrub_next(), osd_scrub_wakeup(), osd_unlinked_list_emptify(), osp_current_object_update_request(), osp_oac_xattr_put(), osp_sync_has_work(), osp_sync_id_get(), osp_sync_id_traction_fini(), osp_sync_inflight_conflict(), osp_sync_interpret(), osp_sync_process_committed(), osp_sync_process_queues(), osp_sync_remove_from_tracker(), osp_sync_request_commit_cb(), osp_sync_thread(), osp_thandle_destroy(), osp_trans_stop(), osp_update_callback_fini(), ping_evictor_main(), ping_evictor_wake(), ptl_send_rpc(), ptlrpc_add_rqs_to_pool(), ptlrpc_add_unreplied(), ptlrpc_at_add_timed(), ptlrpc_at_check_timed(), ptlrpc_at_remove_timed(), ptlrpc_check_set(), ptlrpc_del_timeout_client(), ptlrpc_dispatch_difficult_reply(), ptlrpc_first_transno(), ptlrpc_free_rqbd(), ptlrpc_handle_rs(), ptlrpc_hr_main(), ptlrpc_known_replied_xid(), ptlrpc_main(), ptlrpc_nrs_req_add_nolock(), ptlrpc_pinger_add_import(), ptlrpc_pinger_del_import(), ptlrpc_pinger_remove_timeouts(), ptlrpc_prep_req_from_pool(), ptlrpc_prepare_replay(), ptlrpc_replay_next(), ptlrpc_request_change_export(), ptlrpc_request_committed(), ptlrpc_retain_replayable_request(), ptlrpc_rqbd_pending(), ptlrpc_send_new_req(), ptlrpc_server_drop_request(), ptlrpc_server_free_request(), ptlrpc_server_handle_req_in(), ptlrpc_server_post_idle_rqbds(), ptlrpc_server_request_incoming(), ptlrpc_service_purge_all(), ptlrpc_set_add_req(), ptlrpc_set_wait(), ptlrpc_svcpt_stop_threads(), ptlrpc_update_export_timer(), ptlrpcd(), ptlrpcd_check(), ptlrpcd_steal_rqset(), put_pages_on_tcd_daemon_list(), qmt_glimpse_lock(), qmt_id_lock_notify(), qmt_pool_fini(), qmt_pool_free(), qmt_reba_thread(), qmt_stop_reba_thread(), qsd_adjust_schedule(), qsd_cleanup_adjust(), qsd_job_pending(), qsd_kickoff_deferred(), qsd_put_fsinfo(), qsd_qtype_fini(), qsd_upd_thread(), range_destroy(), range_unlock(), replay_one_lock(), req_off_ctx_list(), sa_free(), sa_has_callback(), sa_kill(), sa_unhashed(), sec_process_ctx_list(), sfw_client_rpc_fini(), sfw_create_rpc(), sfw_create_test_rpc(), sfw_destroy_batch(), sfw_destroy_session(), sfw_destroy_test_instance(), sfw_post_rpc(), sfw_shutdown(), sfw_test_rpc_done(), sfw_test_rpc_fini(), sfw_test_unit_done(), sptlrpc_conf_fini(), sptlrpc_conf_free_rsets(), sptlrpc_gc_add_ctx(), sptlrpc_gc_add_sec(), sptlrpc_gc_del_sec(), sptlrpc_import_check_ctx(), sptlrpc_req_put_ctx(), sptlrpc_req_refresh_ctx(), srpc_finish_service(), srpc_lnet_ev_handler(), srpc_server_rpc_done(), srpc_service_fini(), stt_add_timer(), stt_del_timer(), stt_expire_list(), stt_shutdown(), target_send_reply(), tdtd_ready_for_cancel_log(), tgt_discard_slc_lock(), tgt_save_slc_lock(), top_trans_stop(), tracefiled(), trunc_check_cb(), and vvp_page_print().
static int list_empty_careful (const struct list_head * head) [inline, static]
Test whether a list is empty and not being modified.
Parameters:
head the list to test
Tests whether a list is empty _and_ checks that no other CPU might be in the process of modifying either member (next or prev)
NOTE: using list_empty_careful() without synchronization can only be safe if the only activity that can happen to the list entry is list_del_init(). Eg. it cannot be used if another CPU could re-list_add() it.
Definition at line 178 of file list.h.
References list_head::next, and list_head::prev.
static void list_move (struct list_head * list, struct list_head * head) [inline, static]
Remove an entry from the list it is currently in and insert it at the start of another list.
Parameters:
list the entry to move
head the list to move it to
Definition at line 137 of file list.h.
References __list_del(), list_add(), list_head::next, and list_head::prev.
Referenced by cl_lockset_lock(), cl_page_list_move_head(), class_del_uuid(), class_disconnect_stale_exports(), class_unlink_export(), kiblnd_fmr_pool_unmap(), kiblnd_pool_free_node(), lnet_clear_lazy_portal(), lnet_delay_rule_del(), lnet_drop_rule_del(), lnet_ni_unlink_locked(), lnet_prune_rc_data(), lu_object_add(), lu_object_add_top(), lu_site_purge(), obd_stale_export_adjust(), ofd_seqs_free(), osp_invalidate_request(), rs_batch_add(), tgt_cancel_slc_locks(), upcall_cache_get_entry(), and update_is_committed().
static void list_move_tail (struct list_head * list, struct list_head * head) [inline, static]
Remove an entry from the list it is currently in and insert it at the end of another list.
Parameters:
list the entry to move
head the list to move it to
Definition at line 150 of file list.h.
References __list_del(), list_add_tail(), list_head::next, and list_head::prev.
Referenced by cfs_tage_to_tail(), cfs_tcd_shrink(), cfs_wi_scheduler(), cl_io_locks_sort(), cl_page_list_move(), delayed_msg_check(), distribute_txn_commit_thread(), ldlm_namespace_move_to_active_locked(), ldlm_namespace_move_to_inactive_locked(), lfsck_add_target_from_orphan(), lfsck_assistant_notify_others(), lfsck_assistant_query_others(), lfsck_double_scan(), lfsck_layout_master_post(), lfsck_layout_prep(), lfsck_layout_slave_notify_master(), lfsck_layout_slave_post(), lfsck_layout_slave_query_master(), lfsck_namespace_post(), lfsck_namespace_prep(), lfsck_quit(), lfsck_start(), lu_cache_shrink_scan(), mdt_export_cleanup(), mgs_nidtbl_write(), nrs_request_removed(), osc_cache_shrink_scan(), osc_lru_reclaim(), osc_lru_shrink(), ptlrpc_check_set(), ptlrpc_free_committed(), ptlrpc_update_export_timer(), and try_to_add_extent_for_io().
static void list_splice (struct list_head * list, struct list_head * head) [inline, static]
Join two lists.
Parameters:
list the new list to add.
head the place to add it in the first list.
The contents of list are added at the start of head. list is in an undefined state on return.
Definition at line 206 of file list.h.
References __list_splice(), and list_empty().
Referenced by lnet_str2tbs_expand(), lnet_str2tbs_sep(), lst_print_stat(), lu_cache_shrink_scan(), osp_sync_process_committed(), and ptlrpc_check_set().
static void list_splice_init (struct list_head * list, struct list_head * head) [inline, static]
Join two lists and reinitialise the emptied list.
Parameters:
list the new list to add.
head the place to add it in the first list.
The contents of list are added at the start of head. list is empty on return.
Definition at line 227 of file list.h.
References __list_splice(), INIT_LIST_HEAD, and list_empty().
Referenced by class_del_uuid(), class_disconnect_exports(), collect_pages_on_all_cpus(), hrt_dont_sleep(), kiblnd_connd(), kiblnd_del_peer(), kiblnd_reconnect_peer(), ksocknal_close_conn_locked(), ksocknal_connect(), ksocknal_del_peer(), lnet_clear_lazy_portal(), lnet_drop_routed_msgs_locked(), lnet_peer_tables_cleanup(), lnet_prune_rc_data(), lnet_rtrpool_free_bufs(), lu_object_free(), mgs_fsc_cleanup(), mgs_nidtbl_fini_fs(), osc_brw_redo_request(), osc_build_rpc(), osc_extent_merge(), osd_trans_stop(), panic_collect_pages(), ptlrpcd_add_rqset(), ptlrpcd_check(), ptlrpcd_steal_rqset(), qsd_job_pending(), rs_batch_dispatch(), and tgt_boot_epoch_update().
static void list_splice_tail (struct list_head * list, struct list_head * head) [inline, static]
Definition at line 213 of file list.h.
References __list_splice(), list_empty(), and list_head::prev.
Referenced by lnet_rtrpool_adjust_bufs(), and osc_lru_add_batch().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.