Lustre: lustre/tests/ll_dirstripe_verify.c File Reference
lustre/tests/ll_dirstripe_verify.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <sys/ioctl.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <dirent.h>
#include <libcfs/util/param.h>
#include <lustre/lustreapi.h>
Defines
#define MAX_LOV_UUID_COUNT 1000
Functions
int read_proc_entry (char *proc_path, char *buf, int len)
int compare (struct obd_uuid *puuid, struct lov_user_md *lum_dir, struct lov_user_md *lum_file1, struct lov_user_md *lum_file2)
int main (int argc, char **argv)
Define Documentation
#define MAX_LOV_UUID_COUNT 1000
Definition at line 57 of file ll_dirstripe_verify.c.
Referenced by main().
Function Documentation
int compare (struct obd_uuid * puuid, struct lov_user_md * lum_dir, struct lov_user_md * lum_file1, struct lov_user_md * lum_file2)
Definition at line 94 of file ll_dirstripe_verify.c.
References buf, cfs_free_param_data(), cfs_get_param_paths(), llapi_err_noerrno, LLAPI_MSG_ERROR, LLAPI_MSG_WARN, min_stripe_count(), path, read_proc_entry(), and obd_uuid::uuid.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 210 of file ll_dirstripe_verify.c.
References cleanup(), compare(), dir, llapi_err_noerrno, llapi_error(), llapi_file_get_lov_uuid(), llapi_file_get_stripe(), LLAPI_MSG_ERROR, LOV_USER_MAGIC, lov_user_md, lov_user_md_size(), and MAX_LOV_UUID_COUNT.
int read_proc_entry (char * proc_path, char * buf, int len)
Definition at line 63 of file ll_dirstripe_verify.c.
References llapi_err_noerrno, llapi_error(), and LLAPI_MSG_ERROR.
Referenced by compare().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.