Lustre: lustre/tests/llapi_layout_test.c File Reference
lustre/tests/llapi_layout_test.c File Reference
#include <unistd.h>
#include <stdlib.h>
#include <stdio.h>
#include <stdint.h>
#include <fcntl.h>
#include <sys/wait.h>
#include <sys/signal.h>
#include <sys/types.h>
#include <errno.h>
#include <lustre/lustreapi.h>
#include <pwd.h>
#include <limits.h>
#include <sys/stat.h>
#include <getopt.h>
#include <inttypes.h>
Data Structures
struct test_tbl_entry
Defines
#define ERROR(fmt,...)
#define DIE(fmt,...)
#define ASSERTF(cond, fmt,...)
#define T0FILE "t0"
#define T0_STRIPE_COUNT num_osts
#define T0_STRIPE_SIZE 1048576
#define T0_OST_OFFSET (num_osts - 1)
#define T0_DESC "Read/write layout attributes then create a file"
#define T1_DESC "Read test0 file by path and verify attributes"
#define T2_DESC "Read test0 file by FD and verify attributes"
#define T3_DESC "Read test0 file by FID and verify attributes"
#define T4FILE "t4"
#define T4_STRIPE_COUNT 2
#define T4_STRIPE_SIZE 2097152
#define T4_DESC "Verify compatibility with 'lfs setstripe'"
#define T5FILE "t5"
#define T5_DESC "llapi_layout_get_by_path ENOENT handling"
#define T6_DESC "llapi_layout_get_by_fd EBADF handling"
#define T7FILE "t7"
#define T7_DESC "llapi_layout_get_by_path EACCES handling"
#define T8FILE "t8"
#define T8_DESC "llapi_layout_get_by_path ENODATA handling"
#define T9_DESC "verify llapi_layout_pattern_set() return values"
#define T10_DESC "stripe_count error handling"
#define T11_DESC "stripe_size error handling"
#define T12_DESC "pool_name error handling"
#define T13FILE "t13"
#define T13_STRIPE_COUNT 2
#define T13_DESC "ost_index error handling"
#define T14_DESC "llapi_layout_file_create error handling"
#define T15FILE "t15"
#define T15_STRIPE_COUNT 2
#define T15_DESC "Can't change striping attributes of existing file"
#define T16FILE "t16"
#define T16_DESC "Default stripe attributes are applied as expected"
#define T17FILE "t17"
#define T17_DESC "LLAPI_LAYOUT_WIDE is honored"
#define T18FILE "t18"
#define T18_DESC "Setting pool with fsname.pool notation"
#define T19_DESC "Maximum length pool name is NULL-terminated"
#define T20FILE "t20"
#define T20_DESC "LLAPI_LAYOUT_DEFAULT is honored"
#define T21_DESC "llapi_layout_file_create fails for non-Lustre file"
#define T22FILE "t22"
#define T22_DESC "llapi_layout_file_create applied mode correctly"
#define T23_DESC "llapi_layout_get_by_path fails for non-Lustre file"
#define T24FILE "t24"
#define T24_DESC "LAYOUT_GET_EXPECTED works with existing file"
#define T25DIR "d25"
#define T25_DESC "LAYOUT_GET_EXPECTED works with directory"
#define T26DIR "d26"
#define T26_DESC "LAYOUT_GET_EXPECTED partially specified parent"
#define T26_STRIPE_SIZE (1048576 * 4)
#define T27DIR "d27"
#define T27_DESC "LAYOUT_GET_EXPECTED with non existing file"
#define T27_STRIPE_SIZE (1048576 * 3)
#define T28DIR "d28"
#define T28_DESC "LLAPI_LAYOUT_WIDE returned as expected"
#define TEST_DESC_LEN 50
#define NUM_TESTS (sizeof(test_tbl) / sizeof(struct test_tbl_entry))
Functions
void usage (char *prog)
void test0 (void)
void __test1_helper (struct llapi_layout *layout)
void test1 (void)
void test2 (void)
void test3 (void)
void test4 (void)
void test5 (void)
void test6 (void)
void test7 (void)
void test8 (void)
void test9 (void)
void test10 (void)
void test11 (void)
void test12 (void)
void test13 (void)
void test14 (void)
void test15 (void)
void test16 (void)
void test17 (void)
void test18 (void)
void test19 (void)
void test20 (void)
void test21 (void)
void test22 (void)
void test23 (void)
void test24 (void)
void test25 (void)
void test26 (void)
void test27 (void)
void test28 (void)
void print_test_desc (int test_num, const char *test_desc, const char *status)
int test (void(*test_fn)(), const char *test_desc, bool test_skip, int test_num)
static void process_args (int argc, char *argv[])
int main (int argc, char *argv[])
Variables
static char * lustre_dir
static char * poolname
static int num_osts = -1
static struct test_tbl_entry test_tbl []
Define Documentation
#define ASSERTF (cond, fmt, ...)
Value:
do {                                                                    \
        if (!(cond))                                                    \
                DIE("assertion '%s' failed: "fmt, #cond, ## __VA_ARGS__);\
} while (0)                                                             \
Definition at line 61 of file llapi_layout_test.c.
#define DIE (fmt, ...)
Value:
do {                                    \
        ERROR(fmt, ## __VA_ARGS__);     \
        exit(EXIT_FAILURE);             \
} while (0)
Definition at line 55 of file llapi_layout_test.c.
#define ERROR (fmt, ...)
Value:
fprintf(stderr, "%s: %s:%d: %s: " fmt "\n",                     \
                program_invocation_short_name, __FILE__, __LINE__,      \
                __func__, ## __VA_ARGS__);
Definition at line 50 of file llapi_layout_test.c.
#define NUM_TESTS (sizeof(test_tbl) / sizeof(struct test_tbl_entry))
Definition at line 1243 of file llapi_layout_test.c.
Referenced by main().
#define T0_DESC "Read/write layout attributes then create a file"
Definition at line 82 of file llapi_layout_test.c.
#define T0_OST_OFFSET (num_osts - 1)
Definition at line 81 of file llapi_layout_test.c.
Referenced by __test1_helper(), and test0().
#define T0_STRIPE_COUNT num_osts
Definition at line 79 of file llapi_layout_test.c.
Referenced by __test1_helper(), and test0().
#define T0_STRIPE_SIZE 1048576
Definition at line 80 of file llapi_layout_test.c.
Referenced by __test1_helper(), and test0().
#define T0FILE "t0"
Definition at line 78 of file llapi_layout_test.c.
Referenced by test0(), test1(), test2(), and test3().
#define T10_DESC "stripe_count error handling"
Definition at line 419 of file llapi_layout_test.c.
#define T11_DESC "stripe_size error handling"
Definition at line 461 of file llapi_layout_test.c.
#define T12_DESC "pool_name error handling"
Definition at line 504 of file llapi_layout_test.c.
#define T13_DESC "ost_index error handling"
Definition at line 545 of file llapi_layout_test.c.
#define T13_STRIPE_COUNT 2
Definition at line 544 of file llapi_layout_test.c.
Referenced by test13().
#define T13FILE "t13"
Definition at line 543 of file llapi_layout_test.c.
Referenced by test13().
#define T14_DESC "llapi_layout_file_create error handling"
Definition at line 616 of file llapi_layout_test.c.
#define T15_DESC "Can't change striping attributes of existing file"
Definition at line 633 of file llapi_layout_test.c.
#define T15_STRIPE_COUNT 2
Definition at line 632 of file llapi_layout_test.c.
Referenced by test15().
#define T15FILE "t15"
Definition at line 631 of file llapi_layout_test.c.
Referenced by test15().
#define T16_DESC "Default stripe attributes are applied as expected"
Definition at line 676 of file llapi_layout_test.c.
#define T16FILE "t16"
Definition at line 675 of file llapi_layout_test.c.
Referenced by test16().
#define T17_DESC "LLAPI_LAYOUT_WIDE is honored"
Definition at line 748 of file llapi_layout_test.c.
#define T17FILE "t17"
Definition at line 747 of file llapi_layout_test.c.
Referenced by test17().
#define T18_DESC "Setting pool with fsname.pool notation"
Definition at line 791 of file llapi_layout_test.c.
#define T18FILE "t18"
Definition at line 790 of file llapi_layout_test.c.
Referenced by test18().
#define T19_DESC "Maximum length pool name is NULL-terminated"
Definition at line 833 of file llapi_layout_test.c.
#define T1_DESC "Read test0 file by path and verify attributes"
Definition at line 164 of file llapi_layout_test.c.
#define T20_DESC "LLAPI_LAYOUT_DEFAULT is honored"
Definition at line 852 of file llapi_layout_test.c.
#define T20FILE "t20"
Definition at line 851 of file llapi_layout_test.c.
Referenced by test20().
#define T21_DESC "llapi_layout_file_create fails for non-Lustre file"
Definition at line 909 of file llapi_layout_test.c.
#define T22_DESC "llapi_layout_file_create applied mode correctly"
Definition at line 935 of file llapi_layout_test.c.
#define T22FILE "t22"
Definition at line 934 of file llapi_layout_test.c.
Referenced by test22().
#define T23_DESC "llapi_layout_get_by_path fails for non-Lustre file"
Definition at line 968 of file llapi_layout_test.c.
#define T24_DESC "LAYOUT_GET_EXPECTED works with existing file"
Definition at line 993 of file llapi_layout_test.c.
#define T24FILE "t24"
Definition at line 992 of file llapi_layout_test.c.
Referenced by test24().
#define T25_DESC "LAYOUT_GET_EXPECTED works with directory"
Definition at line 1034 of file llapi_layout_test.c.
#define T25DIR "d25"
Definition at line 1033 of file llapi_layout_test.c.
Referenced by test25().
#define T26_DESC "LAYOUT_GET_EXPECTED partially specified parent"
Definition at line 1072 of file llapi_layout_test.c.
#define T26_STRIPE_SIZE (1048576 * 4)
Definition at line 1073 of file llapi_layout_test.c.
Referenced by test26().
#define T26DIR "d26"
Definition at line 1071 of file llapi_layout_test.c.
Referenced by test26().
#define T27_DESC "LAYOUT_GET_EXPECTED with non existing file"
Definition at line 1120 of file llapi_layout_test.c.
#define T27_STRIPE_SIZE (1048576 * 3)
Definition at line 1121 of file llapi_layout_test.c.
Referenced by test27().
#define T27DIR "d27"
Definition at line 1119 of file llapi_layout_test.c.
Referenced by test27().
#define T28_DESC "LLAPI_LAYOUT_WIDE returned as expected"
Definition at line 1171 of file llapi_layout_test.c.
#define T28DIR "d28"
Definition at line 1170 of file llapi_layout_test.c.
Referenced by test28().
#define T2_DESC "Read test0 file by FD and verify attributes"
Definition at line 176 of file llapi_layout_test.c.
#define T3_DESC "Read test0 file by FID and verify attributes"
Definition at line 198 of file llapi_layout_test.c.
#define T4_DESC "Verify compatibility with 'lfs setstripe'"
Definition at line 224 of file llapi_layout_test.c.
#define T4_STRIPE_COUNT 2
Definition at line 222 of file llapi_layout_test.c.
Referenced by test4().
#define T4_STRIPE_SIZE 2097152
Definition at line 223 of file llapi_layout_test.c.
Referenced by test4().
#define T4FILE "t4"
Definition at line 221 of file llapi_layout_test.c.
Referenced by test4().
#define T5_DESC "llapi_layout_get_by_path ENOENT handling"
Definition at line 278 of file llapi_layout_test.c.
#define T5FILE "t5"
Definition at line 277 of file llapi_layout_test.c.
Referenced by test5().
#define T6_DESC "llapi_layout_get_by_fd EBADF handling"
Definition at line 295 of file llapi_layout_test.c.
#define T7_DESC "llapi_layout_get_by_path EACCES handling"
Definition at line 304 of file llapi_layout_test.c.
#define T7FILE "t7"
Definition at line 303 of file llapi_layout_test.c.
Referenced by test7().
#define T8_DESC "llapi_layout_get_by_path ENODATA handling"
Definition at line 348 of file llapi_layout_test.c.
#define T8FILE "t8"
Definition at line 347 of file llapi_layout_test.c.
Referenced by test8().
#define T9_DESC "verify llapi_layout_pattern_set() return values"
Definition at line 388 of file llapi_layout_test.c.
#define TEST_DESC_LEN 50
Definition at line 1205 of file llapi_layout_test.c.
Referenced by print_test_desc().
Function Documentation
void __test1_helper (struct llapi_layout * layout)
Definition at line 134 of file llapi_layout_test.c.
References ASSERTF, llapi_layout_ost_index_get(), llapi_layout_pool_name_get(), llapi_layout_stripe_count_get(), llapi_layout_stripe_size_get(), LOV_MAXPOOLNAME, poolname, size, T0_OST_OFFSET, T0_STRIPE_COUNT, and T0_STRIPE_SIZE.
Referenced by test1(), test2(), and test3().
int main (int argc, char * argv[])
Definition at line 1321 of file llapi_layout_test.c.
References DIE, LLAPI_MSG_OFF, llapi_msg_set_level(), llapi_search_fsname(), lustre_dir, num_osts, NUM_TESTS, poolname, process_args(), test(), test_tbl_entry::tte_desc, test_tbl_entry::tte_fn, and test_tbl_entry::tte_skip.
void print_test_desc (int test_num, const char * test_desc, const char * status)
Definition at line 1245 of file llapi_layout_test.c.
References TEST_DESC_LEN.
Referenced by test().
static void process_args (int argc, char * argv[]) [static]
Definition at line 1299 of file llapi_layout_test.c.
References lustre_dir, num_osts, optarg, poolname, and usage.
Referenced by main().
int test (void(*)() test_fn, const char * test_desc, bool test_skip, int test_num)
Definition at line 1257 of file llapi_layout_test.c.
References ERROR, print_test_desc(), and status.
void test0 (void)
Definition at line 83 of file llapi_layout_test.c.
References ASSERTF, llapi_layout_alloc(), llapi_layout_file_create(), llapi_layout_free(), llapi_layout_ost_index_set(), llapi_layout_pool_name_get(), llapi_layout_pool_name_set(), llapi_layout_stripe_count_get(), llapi_layout_stripe_count_set(), llapi_layout_stripe_size_get(), llapi_layout_stripe_size_set(), LOV_MAXPOOLNAME, lustre_dir, path, poolname, size, T0_OST_OFFSET, T0_STRIPE_COUNT, T0_STRIPE_SIZE, and T0FILE.
void test1 (void)
Definition at line 165 of file llapi_layout_test.c.
References __test1_helper(), ASSERTF, llapi_layout_free(), llapi_layout_get_by_path(), lustre_dir, path, and T0FILE.
void test10 (void)
Definition at line 420 of file llapi_layout_test.c.
References ASSERTF, llapi_layout_alloc(), llapi_layout_free(), LLAPI_LAYOUT_INVALID, llapi_layout_stripe_count_get(), llapi_layout_stripe_count_set(), and LOV_MAX_STRIPE_COUNT.
void test11 (void)
Definition at line 462 of file llapi_layout_test.c.
References ASSERTF, llapi_layout_alloc(), llapi_layout_free(), LLAPI_LAYOUT_INVALID, llapi_layout_stripe_size_get(), llapi_layout_stripe_size_set(), and size.
void test12 (void)
Definition at line 505 of file llapi_layout_test.c.
References ASSERTF, llapi_layout_alloc(), llapi_layout_free(), llapi_layout_pool_name_get(), llapi_layout_pool_name_set(), LOV_MAXPOOLNAME, and poolname.
void test13 (void)
Definition at line 546 of file llapi_layout_test.c.
References ASSERTF, llapi_layout_alloc(), llapi_layout_file_create(), llapi_layout_free(), llapi_layout_get_by_path(), LLAPI_LAYOUT_INVALID, llapi_layout_ost_index_get(), llapi_layout_ost_index_set(), llapi_layout_stripe_count_set(), lustre_dir, path, T13_STRIPE_COUNT, and T13FILE.
Referenced by main().
void test14 (void)
Definition at line 617 of file llapi_layout_test.c.
References ASSERTF, llapi_layout_alloc(), llapi_layout_file_create(), and llapi_layout_free().
Referenced by main().
void test15 (void)
Definition at line 634 of file llapi_layout_test.c.
References ASSERTF, llapi_layout_alloc(), llapi_layout_file_create(), llapi_layout_file_open(), llapi_layout_free(), llapi_layout_get_by_path(), llapi_layout_stripe_count_get(), llapi_layout_stripe_count_set(), lustre_dir, path, T15_STRIPE_COUNT, and T15FILE.
Referenced by main().
void test16 (void)
Definition at line 677 of file llapi_layout_test.c.
References ASSERTF, LAYOUT_GET_EXPECTED, llapi_layout_alloc(), llapi_layout_file_create(), llapi_layout_free(), llapi_layout_get_by_path(), llapi_layout_stripe_count_get(), llapi_layout_stripe_size_get(), lustre_dir, path, and T16FILE.
Referenced by main().
void test17 (void)
Definition at line 749 of file llapi_layout_test.c.
References ASSERTF, llapi_layout_alloc(), llapi_layout_file_create(), llapi_layout_free(), llapi_layout_get_by_path(), llapi_layout_stripe_count_get(), llapi_layout_stripe_count_set(), LLAPI_LAYOUT_WIDE, llapi_lov_get_uuids(), lustre_dir, path, and T17FILE.
void test18 (void)
Definition at line 792 of file llapi_layout_test.c.
References ASSERTF, llapi_layout_alloc(), llapi_layout_file_create(), llapi_layout_free(), llapi_layout_get_by_path(), llapi_layout_pool_name_get(), llapi_layout_pool_name_set(), LOV_MAXPOOLNAME, lustre_dir, path, poolname, and T18FILE.
void test19 (void)
Definition at line 834 of file llapi_layout_test.c.
References ASSERTF, llapi_layout_alloc(), llapi_layout_free(), llapi_layout_pool_name_get(), llapi_layout_pool_name_set(), LOV_MAXPOOLNAME, and name.
void test2 (void)
Definition at line 177 of file llapi_layout_test.c.
References __test1_helper(), ASSERTF, llapi_layout_free(), llapi_layout_get_by_fd(), lustre_dir, path, and T0FILE.
void test20 (void)
Definition at line 853 of file llapi_layout_test.c.
References ASSERTF, LAYOUT_GET_EXPECTED, llapi_layout_alloc(), LLAPI_LAYOUT_DEFAULT, llapi_layout_file_create(), llapi_layout_free(), llapi_layout_get_by_path(), llapi_layout_stripe_count_get(), llapi_layout_stripe_count_set(), llapi_layout_stripe_size_get(), llapi_layout_stripe_size_set(), lustre_dir, path, and T20FILE.
void test21 (void)
Definition at line 910 of file llapi_layout_test.c.
References ASSERTF, llapi_layout_alloc(), llapi_layout_file_create(), and llapi_layout_free().
void test22 (void)
Definition at line 936 of file llapi_layout_test.c.
References ASSERTF, llapi_layout_file_create(), lustre_dir, path, and T22FILE.
void test23 (void)
Definition at line 969 of file llapi_layout_test.c.
References ASSERTF, and llapi_layout_get_by_path().
void test24 (void)
Definition at line 994 of file llapi_layout_test.c.
References ASSERTF, LAYOUT_GET_EXPECTED, LLAPI_LAYOUT_DEFAULT, llapi_layout_free(), llapi_layout_get_by_path(), llapi_layout_pattern_get(), llapi_layout_stripe_count_get(), llapi_layout_stripe_size_get(), lustre_dir, path, size, and T24FILE.
void test25 (void)
Definition at line 1035 of file llapi_layout_test.c.
References ASSERTF, dir, LAYOUT_GET_EXPECTED, LLAPI_LAYOUT_DEFAULT, llapi_layout_free(), llapi_layout_get_by_path(), llapi_layout_pattern_get(), llapi_layout_stripe_count_get(), llapi_layout_stripe_size_get(), lustre_dir, size, and T25DIR.
void test26 (void)
Definition at line 1074 of file llapi_layout_test.c.
References ASSERTF, cmd, dir, LAYOUT_GET_EXPECTED, LLAPI_LAYOUT_DEFAULT, llapi_layout_free(), llapi_layout_get_by_path(), llapi_layout_pattern_get(), llapi_layout_stripe_count_get(), llapi_layout_stripe_size_get(), lustre_dir, size, T26_STRIPE_SIZE, and T26DIR.
void test27 (void)
Definition at line 1122 of file llapi_layout_test.c.
References ASSERTF, cmd, LAYOUT_GET_EXPECTED, LLAPI_LAYOUT_DEFAULT, llapi_layout_free(), llapi_layout_get_by_path(), llapi_layout_pattern_get(), llapi_layout_stripe_count_get(), llapi_layout_stripe_size_get(), lustre_dir, size, T27_STRIPE_SIZE, and T27DIR.
void test28 (void)
Definition at line 1172 of file llapi_layout_test.c.
References ASSERTF, cmd, llapi_layout_free(), llapi_layout_get_by_path(), llapi_layout_stripe_count_get(), LLAPI_LAYOUT_WIDE, lustre_dir, and T28DIR.
void test3 (void)
Definition at line 199 of file llapi_layout_test.c.
References __test1_helper(), ASSERTF, lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, llapi_layout_free(), llapi_layout_get_by_fid(), llapi_path2fid(), lustre_dir, path, and T0FILE.
void test4 (void)
Definition at line 225 of file llapi_layout_test.c.
References ASSERTF, cmd, llapi_layout_free(), llapi_layout_get_by_path(), llapi_layout_ost_index_get(), llapi_layout_pool_name_get(), llapi_layout_stripe_count_get(), llapi_layout_stripe_size_get(), LOV_MAXPOOLNAME, lustre_dir, path, poolname, size, T4_STRIPE_COUNT, T4_STRIPE_SIZE, and T4FILE.
void test5 (void)
Definition at line 279 of file llapi_layout_test.c.
References ASSERTF, llapi_layout_get_by_path(), lustre_dir, path, and T5FILE.
void test6 (void)
Definition at line 296 of file llapi_layout_test.c.
References ASSERTF, and llapi_layout_get_by_fd().
void test7 (void)
Definition at line 305 of file llapi_layout_test.c.
References ASSERTF, llapi_layout_get_by_path(), lustre_dir, path, and T7FILE.
void test8 (void)
Definition at line 349 of file llapi_layout_test.c.
References ASSERTF, LLAPI_LAYOUT_DEFAULT, llapi_layout_free(), llapi_layout_get_by_path(), llapi_layout_pattern_get(), llapi_layout_stripe_count_get(), llapi_layout_stripe_size_get(), lustre_dir, path, size, and T8FILE.
void test9 (void)
Definition at line 389 of file llapi_layout_test.c.
References ASSERTF, llapi_layout_alloc(), LLAPI_LAYOUT_DEFAULT, llapi_layout_free(), LLAPI_LAYOUT_INVALID, llapi_layout_pattern_set(), and LLAPI_LAYOUT_RAID0.
void usage (char * prog)
Definition at line 71 of file llapi_layout_test.c.
Variable Documentation
char* lustre_dir [static]
Definition at line 67 of file llapi_layout_test.c.
Referenced by main(), process_args(), test0(), test1(), test13(), test15(), test16(), test17(), test18(), test2(), test20(), test22(), test24(), test25(), test26(), test27(), test28(), test3(), test4(), test5(), test7(), and test8().
int num_osts = -1 [static]
Definition at line 69 of file llapi_layout_test.c.
Referenced by main(), and process_args().
char* poolname [static]
Definition at line 68 of file llapi_layout_test.c.
Referenced by __test1_helper(), jt_pool_cmd(), llapi_poollist(), main(), mgs_iocontrol_pool(), mntdf(), pool_hashfn(), process_args(), test0(), test12(), test18(), and test4().
struct test_tbl_entry test_tbl[] [static]
Definition at line 1212 of file llapi_layout_test.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.