Lustre: lustre/tests/llapi_hsm_test.c File Reference
lustre/tests/llapi_hsm_test.c File Reference
#include <stdlib.h>
#include <errno.h>
#include <getopt.h>
#include <fcntl.h>
#include <unistd.h>
#include <poll.h>
#include <time.h>
#include <lustre/lustreapi.h>
Defines
#define ERROR(fmt,...)
#define DIE(fmt,...)
#define ASSERTF(cond, fmt,...)
#define PERFORM(testfn)
Functions
int test1 (void)
int test2 (void)
int test3 (void)
int test4 (void)
int test5 (void)
int test6 (void)
int test7 (void)
static int create_testfile (size_t length)
void test50 (void)
void test51 (void)
void test52 (void)
void helper_archiving (void(*progress)(struct hsm_copyaction_private *hcp, size_t length), const size_t length)
void test100 (void)
static void test101_progress (struct hsm_copyaction_private *hcp, size_t length)
void test101 (void)
static void test102_progress (struct hsm_copyaction_private *hcp, size_t length)
void test102 (void)
static void test103_progress (struct hsm_copyaction_private *hcp, size_t length)
void test103 (void)
static void test104_progress (struct hsm_copyaction_private *hcp, size_t length)
void test104 (void)
static void test105_progress (struct hsm_copyaction_private *hcp, size_t length)
void test105 (void)
static void test106_progress (struct hsm_copyaction_private *hcp, size_t length)
void test106 (void)
static void test107_progress (struct hsm_copyaction_private *hcp, size_t length)
void test107 (void)
static void test108_progress (struct hsm_copyaction_private *hcp, size_t length)
void test108 (void)
static void test109_progress (struct hsm_copyaction_private *hcp, size_t length)
void test109 (void)
static void test110_progress (struct hsm_copyaction_private *hcp, size_t length)
void test110 (void)
static void test111_progress (struct hsm_copyaction_private *hcp, size_t length)
void test111 (void)
static void test112_progress (struct hsm_copyaction_private *hcp, size_t length)
void test112 (void)
static void usage (char *prog)
static void process_args (int argc, char *argv[])
int main (int argc, char *argv[])
Variables
static char fsmountdir [PATH_MAX]
static char * lustre_dir
static char testfile [PATH_MAX]
Define Documentation
#define ASSERTF (cond, fmt, ...)
Value:
do {                                                            \
                if (!(cond))                                            \
                        DIE("assertion '%s' failed: "fmt,               \
                            #cond, ## __VA_ARGS__);                     \
        } while (0)                                                     \
Definition at line 62 of file llapi_hsm_test.c.
#define DIE (fmt, ...)
Value:
do {                                    \
                ERROR(fmt, ## __VA_ARGS__);     \
                exit(EXIT_FAILURE);             \
        } while (0)
Definition at line 56 of file llapi_hsm_test.c.
#define ERROR (fmt, ...)
Value:
fprintf(stderr, "%s: %s:%d: %s: " fmt "\n",                     \
                program_invocation_short_name, __FILE__, __LINE__,      \
                __func__, ## __VA_ARGS__);
Definition at line 51 of file llapi_hsm_test.c.
#define PERFORM (testfn)
Value:
do {                                                            \
                fprintf(stderr, "Starting test " #testfn " at %llu\n",  \
                        (unsigned long long)time(NULL));                \
                testfn();                                               \
                fprintf(stderr, "Finishing test " #testfn " at %llu\n", \
                       (unsigned long long)time(NULL));                 \
        } while (0)
Definition at line 69 of file llapi_hsm_test.c.
Function Documentation
static int create_testfile (size_t length) [static]
Definition at line 286 of file llapi_hsm_test.c.
References ASSERTF, lustre_dir, and testfile.
Referenced by helper_archiving(), test50(), test51(), and test52().
void helper_archiving (void(*)(struct hsm_copyaction_private *hcp, size_t length) progress, const size_t length)
Definition at line 495 of file llapi_hsm_test.c.
References ASSERTF, create_testfile(), ctdata, fsmountdir, hsm_action_item::hai_action, hsm_action_item::hai_extent, hai_first(), hsm_action_list::hal_count, hsm_request::hr_action, hsm_request::hr_archive_id, hsm_request::hr_data_len, hsm_request::hr_flags, hsm_request::hr_itemcount, HS_ARCHIVED, HS_EXISTS, HSMA_ARCHIVE, HUA_ARCHIVE, hsm_user_item::hui_extent, hsm_user_item::hui_fid, hsm_user_request::hur_request, hsm_user_request::hur_user_item, hsm_user_state::hus_states, hsm_extent::length, llapi_fd2fid(), llapi_hsm_action_begin(), llapi_hsm_action_end(), llapi_hsm_copytool_recv(), llapi_hsm_copytool_register(), llapi_hsm_copytool_unregister(), llapi_hsm_request(), llapi_hsm_state_get(), llapi_hsm_user_request_alloc(), hsm_extent::offset, and testfile.
Referenced by test100(), test101(), test102(), test103(), test104(), test105(), test106(), test107(), test108(), test109(), test110(), test111(), and test112().
int main (int argc, char * argv[])
Definition at line 1030 of file llapi_hsm_test.c.
References fsmountdir, llapi_search_mounts(), lustre_dir, PERFORM, process_args(), test1(), test100(), test101(), test102(), test103(), test104(), test105(), test106(), test107(), test108(), test109(), test110(), test111(), test112(), test2(), test3(), test4(), test5(), test50(), test51(), test52(), test6(), and test7().
static void process_args (int argc, char * argv[]) [static]
Definition at line 1012 of file llapi_hsm_test.c.
References lustre_dir, optarg, and usage.
Referenced by main().
int test1 (void)
Definition at line 80 of file llapi_hsm_test.c.
References ASSERTF, ctdata, fsmountdir, llapi_hsm_copytool_register(), and llapi_hsm_copytool_unregister().
Referenced by main().
void test100 (void)
Definition at line 575 of file llapi_hsm_test.c.
References helper_archiving().
Referenced by main().
void test101 (void)
Definition at line 610 of file llapi_hsm_test.c.
References helper_archiving(), and test101_progress().
Referenced by main().
static void test101_progress (struct hsm_copyaction_private * hcp, size_t length) [static]
Definition at line 583 of file llapi_hsm_test.c.
References ASSERTF, hsm_current_action::hca_action, hsm_current_action::hca_location, hsm_current_action::hca_state, HPS_RUNNING, HUA_ARCHIVE, hsm_extent::length, llapi_hsm_action_progress(), llapi_hsm_current_action(), hsm_extent::offset, and testfile.
Referenced by test101().
void test102 (void)
Definition at line 645 of file llapi_hsm_test.c.
References helper_archiving(), and test102_progress().
Referenced by main().
static void test102_progress (struct hsm_copyaction_private * hcp, size_t length) [static]
Definition at line 618 of file llapi_hsm_test.c.
References ASSERTF, hsm_current_action::hca_action, hsm_current_action::hca_location, hsm_current_action::hca_state, HPS_RUNNING, HUA_ARCHIVE, hsm_extent::length, llapi_hsm_action_progress(), llapi_hsm_current_action(), hsm_extent::offset, and testfile.
Referenced by test102().
void test103 (void)
Definition at line 676 of file llapi_hsm_test.c.
References helper_archiving(), and test103_progress().
Referenced by main().
static void test103_progress (struct hsm_copyaction_private * hcp, size_t length) [static]
Definition at line 653 of file llapi_hsm_test.c.
References ASSERTF, hsm_current_action::hca_action, hsm_current_action::hca_location, hsm_current_action::hca_state, HPS_RUNNING, HUA_ARCHIVE, hsm_extent::length, llapi_hsm_action_progress(), llapi_hsm_current_action(), hsm_extent::offset, and testfile.
Referenced by test103().
void test104 (void)
Definition at line 713 of file llapi_hsm_test.c.
References helper_archiving(), and test104_progress().
Referenced by main().
static void test104_progress (struct hsm_copyaction_private * hcp, size_t length) [static]
Definition at line 684 of file llapi_hsm_test.c.
References ASSERTF, hsm_current_action::hca_action, hsm_current_action::hca_location, hsm_current_action::hca_state, HPS_RUNNING, HUA_ARCHIVE, hsm_extent::length, llapi_hsm_action_progress(), llapi_hsm_current_action(), hsm_extent::offset, and testfile.
Referenced by test104().
void test105 (void)
Definition at line 747 of file llapi_hsm_test.c.
References helper_archiving(), and test105_progress().
Referenced by main().
static void test105_progress (struct hsm_copyaction_private * hcp, size_t length) [static]
Definition at line 721 of file llapi_hsm_test.c.
References ASSERTF, hsm_current_action::hca_action, hsm_current_action::hca_location, hsm_current_action::hca_state, HPS_RUNNING, HUA_ARCHIVE, hsm_extent::length, llapi_hsm_action_progress(), llapi_hsm_current_action(), hsm_extent::offset, and testfile.
Referenced by test105().
void test106 (void)
Definition at line 778 of file llapi_hsm_test.c.
References helper_archiving(), and test106_progress().
Referenced by main().
static void test106_progress (struct hsm_copyaction_private * hcp, size_t length) [static]
Definition at line 755 of file llapi_hsm_test.c.
References ASSERTF, hsm_current_action::hca_action, hsm_current_action::hca_location, hsm_current_action::hca_state, HPS_RUNNING, HUA_ARCHIVE, hsm_extent::length, llapi_hsm_action_progress(), llapi_hsm_current_action(), hsm_extent::offset, and testfile.
Referenced by test106().
void test107 (void)
Definition at line 809 of file llapi_hsm_test.c.
References helper_archiving(), and test107_progress().
Referenced by main().
static void test107_progress (struct hsm_copyaction_private * hcp, size_t length) [static]
Definition at line 786 of file llapi_hsm_test.c.
References ASSERTF, hsm_current_action::hca_action, hsm_current_action::hca_location, hsm_current_action::hca_state, HPS_RUNNING, HUA_ARCHIVE, hsm_extent::length, llapi_hsm_action_progress(), llapi_hsm_current_action(), hsm_extent::offset, and testfile.
Referenced by test107().
void test108 (void)
Definition at line 843 of file llapi_hsm_test.c.
References helper_archiving(), and test108_progress().
Referenced by main().
static void test108_progress (struct hsm_copyaction_private * hcp, size_t length) [static]
Definition at line 817 of file llapi_hsm_test.c.
References ASSERTF, hsm_current_action::hca_action, hsm_current_action::hca_location, hsm_current_action::hca_state, HPS_RUNNING, HUA_ARCHIVE, hsm_extent::length, llapi_hsm_action_progress(), llapi_hsm_current_action(), hsm_extent::offset, and testfile.
Referenced by test108().
void test109 (void)
Definition at line 874 of file llapi_hsm_test.c.
References helper_archiving(), and test109_progress().
Referenced by main().
static void test109_progress (struct hsm_copyaction_private * hcp, size_t length) [static]
Definition at line 851 of file llapi_hsm_test.c.
References ASSERTF, hsm_current_action::hca_action, hsm_current_action::hca_location, hsm_current_action::hca_state, HPS_RUNNING, HUA_ARCHIVE, hsm_extent::length, llapi_hsm_action_progress(), llapi_hsm_current_action(), hsm_extent::offset, and testfile.
Referenced by test109().
void test110 (void)
Definition at line 909 of file llapi_hsm_test.c.
References helper_archiving(), and test110_progress().
Referenced by main().
static void test110_progress (struct hsm_copyaction_private * hcp, size_t length) [static]
Definition at line 882 of file llapi_hsm_test.c.
References ASSERTF, hsm_current_action::hca_action, hsm_current_action::hca_location, hsm_current_action::hca_state, HPS_RUNNING, HUA_ARCHIVE, hsm_extent::length, llapi_hsm_action_progress(), llapi_hsm_current_action(), hsm_extent::offset, and testfile.
Referenced by test110().
void test111 (void)
Definition at line 944 of file llapi_hsm_test.c.
References helper_archiving(), and test111_progress().
Referenced by main().
static void test111_progress (struct hsm_copyaction_private * hcp, size_t length) [static]
Definition at line 917 of file llapi_hsm_test.c.
References ASSERTF, hsm_current_action::hca_action, hsm_current_action::hca_location, hsm_current_action::hca_state, HPS_RUNNING, HUA_ARCHIVE, hsm_extent::length, llapi_hsm_action_progress(), llapi_hsm_current_action(), hsm_extent::offset, and testfile.
Referenced by test111().
void test112 (void)
Definition at line 999 of file llapi_hsm_test.c.
References helper_archiving(), and test112_progress().
Referenced by main().
static void test112_progress (struct hsm_copyaction_private * hcp, size_t length) [static]
Definition at line 953 of file llapi_hsm_test.c.
References ASSERTF, hsm_current_action::hca_action, hsm_current_action::hca_location, hsm_current_action::hca_state, HPS_RUNNING, HUA_ARCHIVE, hsm_extent::length, llapi_hsm_action_progress(), llapi_hsm_current_action(), hsm_extent::offset, and testfile.
Referenced by test112().
int test2 (void)
Definition at line 103 of file llapi_hsm_test.c.
References ASSERTF, fsmountdir, llapi_hsm_copytool_register(), and llapi_hsm_copytool_unregister().
Referenced by main().
int test3 (void)
Definition at line 129 of file llapi_hsm_test.c.
References hsm_copytool_private::archives, ASSERTF, ctdata, fsmountdir, and llapi_hsm_copytool_register().
Referenced by main().
int test4 (void)
Definition at line 168 of file llapi_hsm_test.c.
References ASSERTF, and llapi_hsm_copytool_unregister().
Referenced by main().
int test5 (void)
Definition at line 180 of file llapi_hsm_test.c.
References ASSERTF, ctdata, fsmountdir, llapi_hsm_copytool_recv(), llapi_hsm_copytool_register(), and llapi_hsm_copytool_unregister().
Referenced by main().
void test50 (void)
Definition at line 312 of file llapi_hsm_test.c.
References ASSERTF, create_testfile(), hsm_user_state::hus_archive_id, hsm_user_state::hus_in_progress_action, hsm_user_state::hus_in_progress_state, hsm_user_state::hus_states, llapi_hsm_state_get(), llapi_hsm_state_get_fd(), and testfile.
Referenced by main().
void test51 (void)
Definition at line 353 of file llapi_hsm_test.c.
References ASSERTF, create_testfile(), HS_ARCHIVED, HS_DIRTY, HS_EXISTS, HS_LOST, HS_NOARCHIVE, HS_NORELEASE, HS_RELEASED, hsm_user_state::hus_archive_id, hsm_user_state::hus_states, llapi_hsm_state_get_fd(), and llapi_hsm_state_set_fd().
Referenced by main().
void test52 (void)
Definition at line 473 of file llapi_hsm_test.c.
References ASSERTF, create_testfile(), hsm_current_action::hca_action, hsm_current_action::hca_state, llapi_hsm_current_action(), and testfile.
Referenced by main().
int test6 (void)
Definition at line 208 of file llapi_hsm_test.c.
References ASSERTF, ctdata, fsmountdir, llapi_hsm_copytool_recv(), llapi_hsm_copytool_register(), and llapi_hsm_copytool_unregister().
Referenced by main().
int test7 (void)
Definition at line 243 of file llapi_hsm_test.c.
References ASSERTF, ctdata, fsmountdir, llapi_hsm_copytool_get_fd(), llapi_hsm_copytool_recv(), llapi_hsm_copytool_register(), and llapi_hsm_copytool_unregister().
Referenced by main().
static void usage (char * prog) [static]
Definition at line 1006 of file llapi_hsm_test.c.
Variable Documentation
char fsmountdir[PATH_MAX] [static]
Definition at line 48 of file llapi_hsm_test.c.
Referenced by helper_archiving(), main(), test1(), test2(), test3(), test5(), test6(), and test7().
char* lustre_dir [static]
Definition at line 49 of file llapi_hsm_test.c.
Referenced by create_testfile(), main(), and process_args().
char testfile[PATH_MAX] [static]
Definition at line 285 of file llapi_hsm_test.c.
Referenced by create_testfile(), helper_archiving(), test101_progress(), test102_progress(), test103_progress(), test104_progress(), test105_progress(), test106_progress(), test107_progress(), test108_progress(), test109_progress(), test110_progress(), test111_progress(), test112_progress(), test50(), and test52().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.