Lustre: lustre/tests/llapi_fid_test.c File Reference
lustre/tests/llapi_fid_test.c File Reference
#include <stdlib.h>
#include <errno.h>
#include <getopt.h>
#include <fcntl.h>
#include <unistd.h>
#include <poll.h>
#include <sys/ioctl.h>
#include <time.h>
#include <lustre/lustreapi.h>
#include <lustre/lustre_idl.h>
Defines
#define ERROR(fmt,...)
#define DIE(fmt,...)
#define ASSERTF(cond, fmt,...)
#define PERFORM(testfn)
Functions
static void cleanup (void)
static void helper_fid2path (const char *filename, int fd)
static void test10 (void)
static void test11 (void)
static void test12 (void)
static void test20 (void)
static void test30 (void)
static void help_test40 (void)
static void test40 (void)
static void test41 (void)
static void test42 (void)
static void usage (char *prog)
static void process_args (int argc, char *argv[])
int main (int argc, char *argv[])
Variables
static char mainpath [PATH_MAX]
static const char * maindir = "llapi_fid_test_name_9585766"
static char fsmountdir [PATH_MAX]
static char * lustre_dir
Define Documentation
#define ASSERTF (cond, fmt, ...)
Value:
do {                                                            \
                if (!(cond))                                            \
                        DIE("assertion '%s' failed: "fmt,               \
                            #cond, ## __VA_ARGS__);                     \
        } while (0)
Definition at line 62 of file llapi_fid_test.c.
#define DIE (fmt, ...)
Value:
do {                           \
                ERROR(fmt, ## __VA_ARGS__);     \
                exit(EXIT_FAILURE);             \
        } while (0)
Definition at line 56 of file llapi_fid_test.c.
#define ERROR (fmt, ...)
Value:
fprintf(stderr, "%s: %s:%d: %s: " fmt "\n",                     \
                program_invocation_short_name, __FILE__, __LINE__,      \
                __func__, ## __VA_ARGS__);
Definition at line 51 of file llapi_fid_test.c.
#define PERFORM (testfn)
Value:
do {                                                            \
                cleanup();                                              \
                fprintf(stderr, "Starting test " #testfn " at %lld\n",  \
                        (unsigned long long)time(NULL));                \
                testfn();                                               \
                fprintf(stderr, "Finishing test " #testfn " at %lld\n", \
                       (unsigned long long)time(NULL));                 \
                cleanup();                                              \
        } while (0)
Definition at line 69 of file llapi_fid_test.c.
Function Documentation
static void cleanup (void) [static]
Definition at line 88 of file llapi_fid_test.c.
References ASSERTF, cmd, and mainpath.
static void help_test40 (void) [static]
Definition at line 478 of file llapi_fid_test.c.
References ASSERTF, buf, llapi_path2fid(), llapi_path2parent(), lustre_dir, maindir, and mainpath.
Referenced by test40().
static void helper_fid2path (const char * filename, int fd) [static]
Definition at line 104 of file llapi_fid_test.c.
References ASSERTF, DFID, DFID_NOBRACE, FID_LEN, fsmountdir, llapi_fd2fid(), llapi_fid2path(), llapi_path2fid(), lustre_dir, mainpath, and PFID.
Referenced by test10(), and test20().
int main (int argc, char * argv[])
Definition at line 700 of file llapi_fid_test.c.
References ASSERTF, cleanup(), fsmountdir, llapi_search_mounts(), lustre_dir, maindir, mainpath, PERFORM, process_args(), test10(), test11(), test12(), test20(), test30(), test40(), test41(), and test42().
static void process_args (int argc, char * argv[]) [static]
Definition at line 683 of file llapi_fid_test.c.
References lustre_dir, optarg, and usage.
Referenced by main().
static void test10 (void) [static]
Definition at line 171 of file llapi_fid_test.c.
References ASSERTF, helper_fid2path(), lustre_dir, and mainpath.
static void test11 (void) [static]
Definition at line 240 of file llapi_fid_test.c.
References ASSERTF, DFID_NOBRACE, FID_LEN, llapi_fid2path(), llapi_path2fid(), lustre_dir, mainpath, path, and PFID.
static void test12 (void) [static]
Definition at line 274 of file llapi_fid_test.c.
References ASSERTF, DFID_NOBRACE, llapi_create_volatile_idx(), llapi_fd2fid(), llapi_open_by_fid(), mainpath, and PFID.
static void test20 (void) [static]
Definition at line 317 of file llapi_fid_test.c.
References ASSERTF, helper_fid2path(), and mainpath.
static void test30 (void) [static]
Definition at line 361 of file llapi_fid_test.c.
References ASSERTF, buf, DFID_NOBRACE, FID_LEN, filename, fsmountdir, llapi_fid2path(), llapi_path2fid(), lustre_dir, maindir, mainpath, and PFID.
Referenced by main().
static void test40 (void) [static]
Definition at line 517 of file llapi_fid_test.c.
References ASSERTF, cleanup(), help_test40(), and mainpath.
Referenced by main().
static void test41 (void) [static]
Definition at line 538 of file llapi_fid_test.c.
References ASSERTF, buf, LL_IOC_GETPARENT, maindir, and mainpath.
Referenced by main().
static void test42 (void) [static]
Definition at line 572 of file llapi_fid_test.c.
References ASSERTF, buf, filename, llapi_path2fid(), llapi_path2parent(), and mainpath.
Referenced by main().
static void usage (char * prog) [static]
Definition at line 677 of file llapi_fid_test.c.
Variable Documentation
char fsmountdir[PATH_MAX] [static]
Definition at line 84 of file llapi_fid_test.c.
Referenced by helper_fid2path(), main(), and test30().
char* lustre_dir [static]
Definition at line 85 of file llapi_fid_test.c.
Referenced by help_test40(), helper_fid2path(), main(), process_args(), test10(), test11(), and test30().
const char* maindir = "llapi_fid_test_name_9585766" [static]
Definition at line 82 of file llapi_fid_test.c.
Referenced by help_test40(), main(), test30(), and test41().
char mainpath[PATH_MAX] [static]
Definition at line 81 of file llapi_fid_test.c.
Referenced by cleanup(), help_test40(), helper_fid2path(), main(), test10(), test11(), test12(), test20(), test30(), test40(), test41(), and test42().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.