Lustre: lustre/llite/llite_mmap.c File Reference
lustre/llite/llite_mmap.c File Reference
#include <linux/kernel.h>
#include <linux/mm.h>
#include <linux/string.h>
#include <linux/stat.h>
#include <linux/errno.h>
#include <linux/unistd.h>
#include <linux/version.h>
#include <asm/uaccess.h>
#include <linux/fs.h>
#include <linux/pagemap.h>
#include "llite_internal.h"
#include <lustre_compat.h>
Defines
#define DEBUG_SUBSYSTEM S_LLITE
Functions
void policy_from_vma (union ldlm_policy_data *policy, struct vm_area_struct *vma, unsigned long addr, size_t count)
struct vm_area_struct * our_vma (struct mm_struct *mm, unsigned long addr, size_t count)
static struct cl_io * ll_fault_io_init (struct vm_area_struct *vma, struct lu_env **env_ret, struct cl_env_nest *nest, pgoff_t index, unsigned long *ra_flags)
API independent part for page fault initialization.
static int ll_page_mkwrite0 (struct vm_area_struct *vma, struct page *vmpage, bool *retry)
static int to_fault_error (int result)
static int ll_fault0 (struct vm_area_struct *vma, struct vm_fault *vmf)
Lustre implementation of a vm_operations_struct::fault() method, called by VM to server page fault (both in kernel and user space).
static int ll_fault (struct vm_area_struct *vma, struct vm_fault *vmf)
static int ll_page_mkwrite (struct vm_area_struct *vma, struct vm_fault *vmf)
static void ll_vm_open (struct vm_area_struct *vma)
To avoid cancel the locks covering mmapped region for lock cache pressure, we track the mapped vma count in vvp_object::vob_mmap_cnt.
static void ll_vm_close (struct vm_area_struct *vma)
Dual to ll_vm_open().
int ll_teardown_mmaps (struct address_space *mapping, __u64 first, __u64 last)
int ll_file_mmap (struct file *file, struct vm_area_struct *vma)
Variables
static struct vm_operations_struct ll_file_vm_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_LLITE
Definition at line 52 of file llite_mmap.c.
Function Documentation
static int ll_fault (struct vm_area_struct * vma, struct vm_fault * vmf) [static]
Definition at line 343 of file llite_mmap.c.
References cfs_block_sigsinv(), cfs_restore_sigs(), CWARN, LASSERT, ll_fault0(), and unlikely.
static int ll_fault0 (struct vm_area_struct * vma, struct vm_fault * vmf) [static]
Lustre implementation of a vm_operations_struct::fault() method, called by VM to server page fault (both in kernel and user space).
Parameters:
vma - is virtiual area struct related to page fault
vmf - structure which describe type and address where hit fault
Returns:
allocated and filled _locked_ page for address
Return values:
VM_FAULT_ERROR on general error
NOPAGE_OOM not have memory for allocate new page
Definition at line 288 of file llite_mmap.c.
References CDEBUG, cl_io::ci_result, cl_env_nested_put(), cl_io_fini(), cl_io_loop(), D_MMAP, ENTRY, vvp_io::fault, ll_cl_add(), ll_cl_remove(), ll_fault_io_init(), RETURN, to_fault_error(), vvp_io::u, VM_FAULT_RETRY, and vvp_env_io().
Referenced by ll_fault().
static struct cl_io* ll_fault_io_init (struct vm_area_struct * vma, struct lu_env ** env_ret, struct cl_env_nest * nest, pgoff_t index, unsigned long * ra_flags) [static, read]
API independent part for page fault initialization.
Parameters:
vma - virtual memory area addressed to page fault
env - corespondent lu_env to processing
nest - nested level
index - page index corespondent to fault. ra_flags - vma readahead flags.
Returns:
allocated and initialized env for fault operation.
Return values:
EINVAL if env can't allocated
Returns:
other error codes from cl_io_init.
Definition at line 101 of file llite_mmap.c.
References CDEBUG, cl_io::ci_fault, cl_io::ci_lockreq, cl_io::ci_need_restart, cl_io::ci_obj, CILR_MANDATORY, cl_io_slice::cis_io, CIT_FAULT, cl_env_nested_get(), cl_env_nested_put(), cl_io_fini(), cl_io_init(), D_MMAP, ENTRY, LASSERT, ll_file_nolock(), ll_i2info(), ll_inode_info::lli_clob, LUSTRE_FPRIVATE, RETURN, cl_io::u, vvp_io::vui_cl, vvp_io::vui_fd, vvp_env_io(), and vvp_env_thread_io().
Referenced by ll_fault0(), and ll_page_mkwrite0().
int ll_file_mmap (struct file * file, struct vm_area_struct * vma)
Definition at line 485 of file llite_mmap.c.
References ENTRY, ll_file_nolock(), ll_file_vm_ops, ll_glimpse_size(), ll_i2sbi(), ll_stats_ops_tally(), LPROC_LL_MAP, and RETURN.
static int ll_page_mkwrite (struct vm_area_struct * vma, struct vm_fault * vmf) [static]
Definition at line 384 of file llite_mmap.c.
References CWARN, DFID, LASSERT, ll_inode2fid(), ll_page_mkwrite0(), PFID, and VM_FAULT_RETRY.
static int ll_page_mkwrite0 (struct vm_area_struct * vma, struct page * vmpage, bool * retry) [static]
Definition at line 177 of file llite_mmap.c.
References CDEBUG, cfs_block_sigsinv(), cfs_restore_sigs(), cl_io::ci_fault, cl_io::ci_obj, cl_io::ci_result, cl_env_nested_put(), cl_io_fini(), cl_io_loop(), D_MMAP, ENTRY, ergo, EXIT, vvp_io::fault, GOTO, LASSERT, ll_fault_io_init(), ll_file_set_flag(), ll_i2info(), LLIF_DATA_MODIFIED, vvp_io::u, cl_io::u, vvp_env_io(), and vvp_object_inode().
Referenced by ll_page_mkwrite().
int ll_teardown_mmaps (struct address_space * mapping, __u64 first, __u64 last)
Definition at line 463 of file llite_mmap.c.
References ENTRY, LASSERTF, LPU64, and RETURN.
Referenced by ll_invalidate_page().
static void ll_vm_close (struct vm_area_struct * vma) [static]
Dual to ll_vm_open().
Definition at line 449 of file llite_mmap.c.
References cl_inode2vvp(), ENTRY, EXIT, LASSERT, and vvp_object::vob_mmap_cnt.
static void ll_vm_open (struct vm_area_struct * vma) [static]
To avoid cancel the locks covering mmapped region for lock cache pressure, we track the mapped vma count in vvp_object::vob_mmap_cnt.
Definition at line 434 of file llite_mmap.c.
References cl_inode2vvp(), ENTRY, EXIT, LASSERT, and vvp_object::vob_mmap_cnt.
struct vm_area_struct* our_vma (struct mm_struct * mm, unsigned long addr, size_t count) [read]
Definition at line 68 of file llite_mmap.c.
References ENTRY, LASSERT, ll_file_vm_ops, ret, and RETURN.
Referenced by vvp_mmap_locks().
void policy_from_vma (union ldlm_policy_data * policy, struct vm_area_struct * vma, unsigned long addr, size_t count)
Definition at line 59 of file llite_mmap.c.
References ldlm_extent::end, ldlm_policy_data::l_extent, and ldlm_extent::start.
Referenced by vvp_mmap_locks().
static int to_fault_error (int result) [inline, static]
Definition at line 258 of file llite_mmap.c.
Referenced by ll_fault0().
Variable Documentation
static struct vm_operations_struct ll_file_vm_ops [static, read]
Initial value:
 {
        .fault                  = ll_fault,
        .page_mkwrite           = ll_page_mkwrite,
        .open                   = ll_vm_open,
        .close                  = ll_vm_close,
}
Definition at line 57 of file llite_mmap.c.
Referenced by ll_file_mmap(), and our_vma().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.