Lustre: lustre/llite/llite_lib.c File Reference
lustre/llite/llite_lib.c File Reference
#include <linux/module.h>
#include <linux/statfs.h>
#include <linux/time.h>
#include <linux/types.h>
#include <linux/version.h>
#include <linux/mm.h>
#include <linux/user_namespace.h>
#include <lustre_ioctl.h>
#include <lustre_ha.h>
#include <lustre_dlm.h>
#include <lprocfs_status.h>
#include <lustre_disk.h>
#include <lustre_param.h>
#include <lustre_log.h>
#include <cl_object.h>
#include <obd_cksum.h>
#include "llite_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LLITE
#define log2(n) ffz(~(n))
Functions
static struct ll_sb_info * ll_init_sbi (void)
static void ll_free_sbi (struct super_block *sb)
static int client_common_fill_super (struct super_block *sb, char *md, char *dt, struct vfsmount *mnt)
int ll_get_max_mdsize (struct ll_sb_info *sbi, int *lmmsize)
int ll_get_default_mdsize (struct ll_sb_info *sbi, int *lmmsize)
Get the value of the default_easize parameter.
int ll_set_default_mdsize (struct ll_sb_info *sbi, int lmmsize)
Set the default_easize parameter to the given value.
static void ll_dump_inode (struct inode *inode)
void lustre_dump_dentry (struct dentry *dentry, int recur)
static void client_common_put_super (struct super_block *sb)
void ll_kill_super (struct super_block *sb)
static int ll_set_opt (const char *opt, char *data, int fl)
static int ll_options (char *options, int *flags)
void ll_lli_init (struct ll_inode_info *lli)
static int ll_bdi_register (struct backing_dev_info *bdi)
int ll_fill_super (struct super_block *sb, struct vfsmount *mnt)
void ll_put_super (struct super_block *sb)
struct inode * ll_inode_from_resource_lock (struct ldlm_lock *lock)
void ll_dir_clear_lsm_md (struct inode *inode)
static struct inode * ll_iget_anon_dir (struct super_block *sb, const struct lu_fid *fid, struct lustre_md *md)
static int ll_init_lsm_md (struct inode *inode, struct lustre_md *md)
static int lli_lsm_md_eq (const struct lmv_stripe_md *lsm_md1, const struct lmv_stripe_md *lsm_md2)
static int ll_update_lsm_md (struct inode *inode, struct lustre_md *md)
void ll_clear_inode (struct inode *inode)
static int ll_md_setattr (struct dentry *dentry, struct md_op_data *op_data)
int ll_setattr_raw (struct dentry *dentry, struct iattr *attr, bool hsm_import)
int ll_setattr (struct dentry *de, struct iattr *attr)
int ll_statfs_internal (struct super_block *sb, struct obd_statfs *osfs, __u64 max_age, __u32 flags)
int ll_statfs (struct dentry *de, struct kstatfs *sfs)
void ll_inode_size_lock (struct inode *inode)
void ll_inode_size_unlock (struct inode *inode)
int ll_update_inode (struct inode *inode, struct lustre_md *md)
int ll_read_inode2 (struct inode *inode, void *opaque)
void ll_delete_inode (struct inode *inode)
int ll_iocontrol (struct inode *inode, struct file *file, unsigned int cmd, unsigned long arg)
int ll_flush_ctx (struct inode *inode)
void ll_umount_begin (struct super_block *sb)
int ll_remount_fs (struct super_block *sb, int *flags, char *data)
void ll_open_cleanup (struct super_block *sb, struct ptlrpc_request *open_req)
Cleanup the open handle that is cached on MDT-side.
int ll_prep_inode (struct inode **inode, struct ptlrpc_request *req, struct super_block *sb, struct lookup_intent *it)
int ll_obd_statfs (struct inode *inode, void __user *arg)
int ll_process_config (struct lustre_cfg *lcfg)
struct md_op_data * ll_prep_md_op_data (struct md_op_data *op_data, struct inode *i1, struct inode *i2, const char *name, size_t namelen, __u32 mode, __u32 opc, void *data)
void ll_finish_md_op_data (struct md_op_data *op_data)
int ll_show_options (struct seq_file *seq, struct vfsmount *vfs)
int ll_get_obd_name (struct inode *inode, unsigned int cmd, unsigned long arg)
Get obd name by cmd, and copy out to user space.
char * ll_get_fsname (struct super_block *sb, char *buf, int buflen)
Get lustre file system name by sbi.
static char * ll_d_path (struct dentry *dentry, char *buf, int bufsize)
void ll_dirty_page_discard_warn (struct page *page, int ioret)
ssize_t ll_copy_user_md (const struct lov_user_md __user *md, struct lov_user_md **kbuf)
void ll_compute_rootsquash_state (struct ll_sb_info *sbi)
static int ll_linkea_decode (struct linkea_data *ldata, unsigned int linkno, struct lu_fid *parent_fid, struct lu_name *ln)
Parse linkea content to extract information about a given hardlink.
int ll_getparent (struct file *file, struct getparent __user *arg)
Get parent FID and name of an identified link.
Variables
struct kmem_cache * ll_file_data_slab
Define Documentation
#define DEBUG_SUBSYSTEM S_LLITE
Definition at line 41 of file llite_lib.c.
#define log2 (n) ffz(~(n))
Definition at line 68 of file llite_lib.c.
Referenced by client_common_fill_super(), and server_fill_super_common().
Function Documentation
static int client_common_fill_super (struct super_block * sb, char * md, char * dt, struct vfsmount * mnt) [static]
Definition at line 164 of file llite_lib.c.
References buf, CDEBUG, CERROR, cfs_time_shift_64(), checksum, cksum_types_supported_client(), cl_fid_build_ino(), cl_ocd_update(), cl_sb_init(), class_name2obd(), CLIENT_CONNECT_MDT_REQD, d_make_root(), D_RPCTRACE, D_SUPER, DFID, DT_MAX_BRW_SIZE, ENTRY, obd_export::exp_connect_data, exp_connect_flags(), obd_export::exp_obd, fid_is_sane(), fid_zero(), get_uuid2int(), GOTO, KEY_CACHE_SET, KEY_CHECKSUM, KEY_CONN_DATA, LASSERT, lustre_client_ocd::lco_dt_exp, lustre_client_ocd::lco_flags, lustre_client_ocd::lco_lock, lustre_client_ocd::lco_md_exp, LCONSOLE_ERROR_MSG, LCONSOLE_INFO, ll_sb_info::ll_cache, ll_d_ops, ll_sb_info::ll_dt_exp, ll_sb_info::ll_et, ll_file_operations, ll_file_operations_flock, ll_file_operations_noflock, ll_sb_info::ll_flags, ll_sb_info::ll_fop, ll_get_fsname(), ll_iget(), ll_sb_info::ll_lco, ll_sb_info::ll_md_brw_pages, ll_sb_info::ll_md_exp, ll_sb_info::ll_namelen, ll_sb_info::ll_rct, ll_sb_info::ll_root_fid, ll_s2sbi, ll_sb_info::ll_sb_uuid, LL_SBI_32BIT_API, LL_SBI_64BIT_HASH, LL_SBI_ACL, LL_SBI_ALWAYS_PING, LL_SBI_CHECKSUM, LL_SBI_FLOCK, LL_SBI_LAYOUT_LOCK, LL_SBI_LOCALFLOCK, LL_SBI_LRU_RESIZE, LL_SBI_RMT_CLIENT, LL_SBI_USER_XATTR, LL_SBI_XATTR_CACHE, ll_sb_info::ll_sdev_orig, LL_SUPER_MAGIC, ll_sb_info::ll_xattr_cache_enabled, log2, lprocfs_register_mountpoint(), LPX64, lustre_export_operations, LUSTRE_SEQ_METADATA, lustre_super_operations, LUSTRE_VERSION_CODE, md_free_lustre_md(), md_get_lustre_md(), md_get_root(), md_getattr(), MD_MAX_BRW_SIZE, MDS_INODELOCK_FULL, MDS_INODELOCK_XATTR, OBD_ALLOC_PTR, OBD_ALLOC_WAIT, OBD_CKSUM_ADLER, obd_connect(), OBD_CONNECT_64BITHASH, OBD_CONNECT_ACL, OBD_CONNECT_AT, OBD_CONNECT_ATTRFID, OBD_CONNECT_BRW_SIZE, OBD_CONNECT_BULK_MBITS, OBD_CONNECT_CANCELSET, OBD_CONNECT_CKSUM, OBD_CONNECT_DIR_STRIPE, OBD_CONNECT_DISP_STRIPE, OBD_CONNECT_EINPROGRESS, OBD_CONNECT_FID, obd_connect_flags2str(), OBD_CONNECT_FLOCK_DEAD, OBD_CONNECT_FULL20, OBD_CONNECT_GRANT, OBD_CONNECT_GRANT_PARAM, OBD_CONNECT_IBITS, OBD_CONNECT_JOBSTATS, OBD_CONNECT_LAYOUTLOCK, OBD_CONNECT_LFSCK, OBD_CONNECT_LIGHTWEIGHT, OBD_CONNECT_LOV_V3, OBD_CONNECT_LRU_RESIZE, OBD_CONNECT_LVB_TYPE, OBD_CONNECT_MAX_EASIZE, OBD_CONNECT_MAXBYTES, OBD_CONNECT_MDS_CAPA, OBD_CONNECT_NODEVOH, OBD_CONNECT_OPEN_BY_FID, OBD_CONNECT_OSS_CAPA, OBD_CONNECT_PINGLESS, OBD_CONNECT_RDONLY, OBD_CONNECT_REAL, OBD_CONNECT_REQPORTAL, OBD_CONNECT_RMT_CLIENT, OBD_CONNECT_RMT_CLIENT_FORCE, OBD_CONNECT_SRVLOCK, OBD_CONNECT_SUBTREE, OBD_CONNECT_TRUNCLOCK, OBD_CONNECT_UMASK, OBD_CONNECT_VBR, OBD_CONNECT_VERSION, OBD_CONNECT_XATTR, obd_disconnect(), OBD_FAIL_CHECK, OBD_FAIL_MDC_LIGHTWEIGHT, OBD_FAIL_OSC_CKSUM_ADLER_ONLY, OBD_FAIL_OSC_CONNECT_CKSUM, OBD_FAIL_OSC_CONNECT_GRANT_PARAM, obd_fid_fini(), obd_fid_init(), OBD_FREE, OBD_FREE_PTR, obd_get_info(), obd_get_uuid(), OBD_MD_FLACL, OBD_MD_FLBLOCKS, OBD_MD_FLGETATTR, OBD_MD_FLMODEASIZE, OBD_MD_FLRMTPERM, obd_device::obd_name, obd_set_info_async(), obd_statfs(), OBD_STATFS_CACHE_SECONDS, OBD_STATFS_FOR_MDT0, obd_device::obd_upcall, obd_connect_data::ocd_brw_size, obd_connect_data::ocd_cksum_types, obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_grant, obd_connect_data::ocd_grant_blkbits, obd_connect_data::ocd_ibits_known, obd_connect_data::ocd_version, obd_notify_upcall::onu_owner, obd_notify_upcall::onu_upcall, md_op_data::op_data, md_op_data::op_fid1, md_op_data::op_mode, md_op_data::op_valid, obd_statfs::os_bsize, obd_statfs::os_namelen, PFID, proc_lustre_fs_root, ptlrpc_req_finished(), RETURN, size, obd_uuid::uuid, and uuid.
Referenced by ll_fill_super().
static void client_common_put_super (struct super_block * sb) [static]
Definition at line 733 of file llite_lib.c.
References cl_sb_fini(), ENTRY, EXIT, obd_export::exp_obd, list_del(), ll_sb_info::ll_conn_chain, ll_sb_info::ll_dt_exp, ll_sb_info::ll_et, ll_sb_info::ll_flags, ll_sb_info::ll_md_exp, ll_sb_info::ll_rct, ll_s2sbi, LL_SBI_RMT_CLIENT, lprocfs_unregister_mountpoint(), obd_disconnect(), and obd_fid_fini().
Referenced by ll_put_super().
static int ll_bdi_register (struct backing_dev_info * bdi) [inline, static]
Definition at line 983 of file llite_lib.c.
Referenced by ll_fill_super().
void ll_clear_inode (struct inode * inode)
Definition at line 1433 of file llite_lib.c.
References CDEBUG, cl_inode_fini(), D_VFSTRACE, DFID, ENTRY, EXIT, FMODE_EXEC, FMODE_READ, FMODE_WRITE, free_rmtperm_hash(), LASSERT, list_empty(), ll_dir_clear_lsm_md(), ll_sb_info::ll_flags, ll_i2info(), ll_i2sbi(), ll_inode2fid(), ll_sb_info::ll_md_exp, ll_md_real_close(), LL_SBI_RMT_CLIENT, ll_xattr_cache_destroy(), ll_inode_info::lli_agl_list, LLI_INODE_DEAD, ll_inode_info::lli_inode_magic, ll_inode_info::lli_mds_exec_och, ll_inode_info::lli_mds_read_och, ll_inode_info::lli_mds_write_och, ll_inode_info::lli_open_fd_exec_count, ll_inode_info::lli_open_fd_read_count, ll_inode_info::lli_open_fd_write_count, ll_inode_info::lli_opendir_key, ll_inode_info::lli_opendir_pid, ll_inode_info::lli_posix_acl, ll_inode_info::lli_remote_perms, ll_inode_info::lli_sai, ll_inode_info::lli_symlink_name, md_null_inode(), OBD_FREE, and PFID.
Referenced by ll_delete_inode().
void ll_compute_rootsquash_state (struct ll_sb_info * sbi)
Definition at line 2683 of file llite_lib.c.
References cfs_match_nid(), list_empty(), ll_sb_info::ll_flags, LL_SBI_NOROOTSQUASH, ll_sb_info::ll_squash, LNET_NETTYP(), LNET_NIDNET(), LNetGetId(), LOLND, root_squash_info::rsi_nosquash_nids, and root_squash_info::rsi_sem.
ssize_t ll_copy_user_md (const struct lov_user_md __user * md, struct lov_user_md ** kbuf)
Definition at line 2653 of file llite_lib.c.
References ENTRY, ll_lov_user_md_size(), lov_user_md, OBD_ALLOC, OBD_FREE, and RETURN.
Referenced by ll_lov_setstripe().
static char* ll_d_path (struct dentry * dentry, char * buf, int bufsize) [static]
Definition at line 2611 of file llite_lib.c.
References path.
Referenced by ll_dirty_page_discard_warn().
void ll_delete_inode (struct inode * inode)
Definition at line 2040 of file llite_lib.c.
References CL_FSYNC_LOCAL, cl_sync_file_range(), clear_inode, DFID, ENTRY, EXIT, LASSERTF, ll_clear_inode(), ll_i2info(), ll_inode2fid(), ll_inode_info::lli_clob, OBD_OBJECT_EOF, PFID, and truncate_inode_pages_final().
void ll_dir_clear_lsm_md (struct inode * inode)
Definition at line 1205 of file llite_lib.c.
References LASSERT, ll_i2info(), ll_inode_info::lli_lsm_md, and lmv_free_memmd().
Referenced by ll_clear_inode(), and ll_iget().
void ll_dirty_page_discard_warn (struct page * page, int ioret)
Definition at line 2625 of file llite_lib.c.
References buf, CDEBUG, D_WARNING, DFID, ll_d_path(), ll_get_fsname(), ll_inode2fid(), path, and PFID.
Referenced by vvp_vmpage_error().
static void ll_dump_inode (struct inode * inode) [static]
Definition at line 688 of file llite_lib.c.
References CERROR, DFID, LASSERT, ll_d_hlist_for_each, ll_d_hlist_node, ll_get_fsname(), ll_i2mdexp(), ll_inode2fid(), and PFID.
Referenced by lustre_dump_dentry().
int ll_fill_super (struct super_block * sb, struct vfsmount * mnt)
Definition at line 992 of file llite_lib.c.
References CDEBUG, config_llog_instance::cfg_callback, config_llog_instance::cfg_instance, config_llog_instance::cfg_uuid, class_config_llog_handler(), class_get_profile(), class_put_profile(), client_common_fill_super(), D_CONFIG, D_VFSTRACE, ENTRY, GOTO, LCONSOLE_ERROR_MSG, LCONSOLE_WARN, ll_bdi_register(), ll_sb_info::ll_client_common_fill_super_succeeded, ll_d_ops, ll_sb_info::ll_flags, ll_init_sbi(), ll_options(), ll_put_super(), LL_SBI_VERBOSE, lustre_profile::lp_dt, lustre_profile::lp_md, lustre_process_log(), OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, and RETURN.
Referenced by lustre_init().
void ll_finish_md_op_data (struct md_op_data * op_data)
Definition at line 2507 of file llite_lib.c.
References OBD_FREE_PTR.
Referenced by __ll_inode_revalidate(), get_hsm_state(), is_first_dirent(), ll_close_inode_openhandle(), ll_dir_get_parent_fid(), ll_dir_getstripe(), ll_dir_setdirstripe(), ll_dir_setstripe(), ll_file_flock(), ll_file_ioctl(), ll_get_fid_by_name(), ll_get_name(), ll_hsm_state_set(), ll_intent_file_open(), ll_iocontrol(), ll_layout_refresh_locked(), ll_lease_open(), ll_link(), ll_lookup_it(), ll_lov_getstripe_ea_info(), ll_migrate(), ll_new_node(), ll_open_cleanup(), ll_readdir(), ll_readlink_internal(), ll_rename(), ll_rmdir(), ll_rmdir_entry(), ll_setattr_raw(), ll_statahead_thread(), ll_swap_layouts(), ll_unlink(), and ll_xattr_find_get_lock().
int ll_flush_ctx (struct inode * inode)
Definition at line 2145 of file llite_lib.c.
References CDEBUG, D_SEC, from_kuid(), KEY_FLUSH_CTX, ll_sb_info::ll_dt_exp, ll_i2sbi(), ll_sb_info::ll_md_exp, and obd_set_info_async().
Referenced by ll_dir_ioctl(), and ll_file_ioctl().
static void ll_free_sbi (struct super_block * sb) [static]
Definition at line 147 of file llite_lib.c.
References cfs_free_nidlist(), cl_cache_decref(), ENTRY, EXIT, list_empty(), ll_sb_info::ll_cache, ll_s2sbi, ll_sb_info::ll_squash, OBD_FREE, and root_squash_info::rsi_nosquash_nids.
Referenced by ll_put_super().
int ll_get_default_mdsize (struct ll_sb_info * sbi, int * lmmsize)
Get the value of the default_easize parameter.
See also:
client_obd::cl_default_mds_easize
Parameters:
[in] sbi superblock info for this filesystem
[out] lmmsize pointer to storage location for value
Return values:
0 on success
negative negated errno on failure
Definition at line 649 of file llite_lib.c.
References CERROR, KEY_DEFAULT_EASIZE, ll_sb_info::ll_md_exp, obd_get_info(), RETURN, and size.
Referenced by __ll_inode_revalidate(), ll_dir_get_parent_fid(), ll_dir_getstripe(), ll_layout_fetch(), ll_lov_getstripe_ea_info(), and search_inode_for_lustre().
char* ll_get_fsname (struct super_block * sb, char * buf, int buflen)
Get lustre file system name by sbi.
If buf is provided(non-NULL), the fsname will be returned in this buffer; otherwise, a static buffer will be used to store the fsname and returned to caller.
Definition at line 2583 of file llite_lib.c.
References MTI_NAME_MAXLEN, and unlikely.
Referenced by client_common_fill_super(), is_first_dirent(), ll_close_inode_openhandle(), ll_dir_get_parent_fid(), ll_dir_ioctl(), ll_dir_setstripe(), ll_dirty_page_discard_warn(), ll_dump_inode(), ll_encode_fh(), ll_getxattr_common(), ll_hsm_release(), ll_iget_anon_dir(), ll_inode_revalidate_fini(), ll_invalidate_aliases(), ll_layout_lock_set(), ll_layout_refresh_locked(), ll_lease_open(), ll_migrate(), ll_open_cleanup(), ll_readlink_internal(), ll_setattr_raw(), ll_swap_layouts_close(), ll_update_lsm_md(), revalidate_statahead_dentry(), sa_instantiate(), vvp_io_init(), and vvp_io_write_start().
int ll_get_max_mdsize (struct ll_sb_info * sbi, int * lmmsize)
Definition at line 616 of file llite_lib.c.
References CERROR, obd_export::exp_obd, KEY_MAX_EASIZE, ll_sb_info::ll_dt_exp, ll_sb_info::ll_md_exp, obd_get_info(), obd_device::obd_name, RETURN, and size.
int ll_get_obd_name (struct inode * inode, unsigned int cmd, unsigned long arg)
Get obd name by cmd, and copy out to user space.
Definition at line 2555 of file llite_lib.c.
References __user, class_exp2obd(), ENTRY, ll_sb_info::ll_dt_exp, ll_i2sbi(), ll_sb_info::ll_md_exp, OBD_IOC_GETDTNAME, OBD_IOC_GETMDNAME, obd_device::obd_name, and RETURN.
Referenced by ll_dir_ioctl(), and ll_file_ioctl().
int ll_getparent (struct file * file, struct getparent __user * arg)
Get parent FID and name of an identified link.
Operation is performed for a given link number, letting the caller iterate over linkno to list one or all links of an entry.
Parameters:
[in] file - File descriptor against which to perform the operation
[in,out] arg - User-filled structure containing the linkno to operate on and the available size. It is eventually filled with the requested information or left untouched on error
Return values:
- 0 on success
- Appropriate negative error code on failure
Definition at line 2770 of file llite_lib.c.
References CFS_CAP_DAC_READ_SEARCH, cfs_capable(), ENTRY, GOTO, lu_buf::lb_buf, lu_buf::lb_len, linkea_data_new(), ll_getxattr(), ll_i2sbi(), ll_linkea_decode(), LL_SBI_USER_FID2PATH, lu_name::ln_name, lu_name::ln_namelen, lu_buf_free(), LU_BUF_NULL, OBD_ALLOC, OBD_FREE, RETURN, and XATTR_NAME_LINK.
Referenced by ll_dir_ioctl(), and ll_file_ioctl().
static struct inode* ll_iget_anon_dir (struct super_block * sb, const struct lu_fid * fid, struct lustre_md * md) [static, read]
Definition at line 1217 of file llite_lib.c.
References lustre_md::body, CDEBUG, CERROR, cl_fid_build_ino(), D_INODE, DFID, ENTRY, LASSERT, LASSERTF, ll_dir_inode_operations, ll_dir_operations, ll_sb_info::ll_flags, ll_get_fsname(), ll_i2info(), ll_lli_init(), ll_s2sbi, LL_SBI_32BIT_API, ll_inode_info::lli_fid, ll_inode_info::lli_pfid, lustre_md::lmv, LTIME_S, mdt_body::mbo_fid1, mdt_body::mbo_mode, PFID, and RETURN.
Referenced by ll_init_lsm_md().
static int ll_init_lsm_md (struct inode * inode, struct lustre_md * md) [static]
Definition at line 1270 of file llite_lib.c.
References LASSERT, ll_iget_anon_dir(), lmv_oinfo::lmo_fid, lmv_oinfo::lmo_root, lustre_md::lmv, LMV_HASH_FLAG_MIGRATION, lmv_stripe_md::lsm_md_hash_type, lmv_stripe_md::lsm_md_oinfo, and lmv_stripe_md::lsm_md_stripe_count.
Referenced by ll_update_lsm_md().
static struct ll_sb_info* ll_init_sbi (void) [static, read]
Definition at line 71 of file llite_lib.c.
References CDEBUG, cl_cache_init(), class_uuid_unparse(), D_CONFIG, ENTRY, INIT_LIST_HEAD, lustre_client_ocd::lco_lock, ll_sb_info::ll_agl_total, ll_sb_info::ll_cache, ll_sb_info::ll_conn_chain, ll_sb_info::ll_flags, ll_generate_random_uuid, ll_sb_info::ll_lco, ll_sb_info::ll_lock, ll_sb_info::ll_orphan_dentry_list, ll_sb_info::ll_pp_extent_lock, LL_PROCESS_HIST_MAX, ll_sb_info::ll_process_lock, ll_sb_info::ll_ra_info, ll_sb_info::ll_rw_extents_info, ll_sb_info::ll_rw_stats_on, ll_sb_info::ll_sa_max, LL_SA_RPC_DEF, ll_sb_info::ll_sa_running, ll_sb_info::ll_sa_total, ll_sb_info::ll_sa_wrong, ll_sb_info::ll_sb_uuid, LL_SBI_AGL_ENABLED, LL_SBI_CHECKSUM, LL_SBI_LRU_RESIZE, LL_SBI_VERBOSE, ll_sb_info::ll_squash, OBD_ALLOC_PTR, OBD_FREE, ll_rw_extents_info::pp_extents, ll_ra_info::ra_max_pages, ll_ra_info::ra_max_pages_per_file, ll_ra_info::ra_max_read_ahead_whole_pages, RETURN, root_squash_info::rsi_gid, root_squash_info::rsi_nosquash_nids, root_squash_info::rsi_sem, root_squash_info::rsi_uid, SBI_DEFAULT_READAHEAD_MAX, SBI_DEFAULT_READAHEAD_WHOLE_MAX, obd_uuid::uuid, and uuid.
Referenced by ll_fill_super().
struct inode* ll_inode_from_resource_lock (struct ldlm_lock * lock) [read]
Definition at line 1180 of file llite_lib.c.
References D_INFO, D_WARNING, ldlm_lock::l_resource, LDLM_DEBUG_LIMIT, ll_i2info(), LLI_INODE_MAGIC, ll_inode_info::lli_inode_magic, lock_res_and_lock(), ldlm_resource::lr_lvb_inode, and unlock_res_and_lock().
Referenced by ll_md_blocking_ast().
void ll_inode_size_lock (struct inode * inode)
Definition at line 1847 of file llite_lib.c.
References LASSERT, ll_i2info(), and ll_inode_info::lli_size_mutex.
Referenced by ll_follow_link(), ll_lov_setstripe_ea_info(), ll_merge_attr(), vvp_do_vmtruncate(), and vvp_object_size_lock().
void ll_inode_size_unlock (struct inode * inode)
Definition at line 1857 of file llite_lib.c.
References ll_i2info(), and ll_inode_info::lli_size_mutex.
Referenced by ll_follow_link(), ll_lov_setstripe_ea_info(), ll_merge_attr(), vvp_do_vmtruncate(), and vvp_object_size_unlock().
int ll_iocontrol (struct inode * inode, struct file * file, unsigned int cmd, unsigned long arg)
Definition at line 2064 of file llite_lib.c.
References __user, CERROR, cl_setattr_ost(), DFID, ENTRY, obd_export::exp_obd, FSFILT_IOC_GETFLAGS, FSFILT_IOC_SETFLAGS, ll_finish_md_op_data(), ll_i2info(), ll_i2sbi(), ll_inode2fid(), ll_sb_info::ll_md_exp, ll_prep_md_op_data(), ll_inode_info::lli_clob, LUSTRE_OPC_ANY, mdt_body::mbo_flags, md_getattr(), md_setattr(), OBD_ALLOC_PTR, OBD_FREE_PTR, OBD_MD_FLFLAGS, obd_device::obd_name, md_op_data::op_attr, md_op_data::op_attr_flags, md_op_data::op_data, md_op_data::op_valid, PFID, ptlrpc_req_finished(), req_capsule_server_get(), RETURN, RMF_MDT_BODY, and ptlrpc_request::rq_pill.
Referenced by ll_dir_ioctl(), and ll_file_ioctl().
void ll_kill_super (struct super_block * sb)
Definition at line 762 of file llite_lib.c.
References ENTRY, EXIT, ll_s2sbi, ll_sb_info::ll_sa_running, ll_sb_info::ll_sdev_orig, and ll_sb_info::ll_umounting.
Referenced by lustre_init().
static int ll_linkea_decode (struct linkea_data * ldata, unsigned int linkno, struct lu_fid * parent_fid, struct lu_name * ln) [static]
Parse linkea content to extract information about a given hardlink.
Parameters:
[in] ldata - Initialized linkea data
[in] linkno - Link identifier
[out] parent_fid - The entry's parent FID
[out] ln - Entry name destination buffer
Return values:
0 on success
Appropriate negative error code on failure
Definition at line 2726 of file llite_lib.c.
References ENTRY, linkea_data::ld_lee, linkea_data::ld_leh, linkea_data::ld_reclen, link_ea_header::leh_reccount, linkea_entry_unpack(), linkea_first_entry(), linkea_init(), linkea_next_entry(), and RETURN.
Referenced by ll_getparent().
void ll_lli_init (struct ll_inode_info * lli)
Definition at line 933 of file llite_lib.c.
References CL_LAYOUT_GEN_NONE, fid_zero(), INIT_LIST_HEAD, LASSERT, ll_layout_version_set(), ll_inode_info::lli_agl_index, ll_inode_info::lli_agl_list, ll_inode_info::lli_agl_lock, ll_inode_info::lli_async_rc, ll_inode_info::lli_clob, ll_inode_info::lli_def_stripe_offset, ll_inode_info::lli_flags, ll_inode_info::lli_glimpse_sem, ll_inode_info::lli_glimpse_time, LLI_INODE_MAGIC, ll_inode_info::lli_inode_magic, ll_inode_info::lli_layout_lock, ll_inode_info::lli_layout_mutex, ll_inode_info::lli_lock, ll_inode_info::lli_mds_exec_och, ll_inode_info::lli_mds_read_och, ll_inode_info::lli_mds_write_och, ll_inode_info::lli_och_mutex, ll_inode_info::lli_open_count, ll_inode_info::lli_open_fd_exec_count, ll_inode_info::lli_open_fd_read_count, ll_inode_info::lli_open_fd_write_count, ll_inode_info::lli_opendir_key, ll_inode_info::lli_opendir_pid, ll_inode_info::lli_pfid, ll_inode_info::lli_posix_acl, ll_inode_info::lli_readdir_mutex, ll_inode_info::lli_remote_perms, ll_inode_info::lli_rmtperm_mutex, ll_inode_info::lli_rmtperm_time, ll_inode_info::lli_sa_enabled, ll_inode_info::lli_sa_lock, ll_inode_info::lli_sai, ll_inode_info::lli_size_mutex, ll_inode_info::lli_symlink_name, ll_inode_info::lli_trunc_sem, ll_inode_info::lli_vfs_inode, ll_inode_info::lli_write_tree, ll_inode_info::lli_xattrs_enq_lock, ll_inode_info::lli_xattrs_list_rwsem, and range_lock_tree_init().
Referenced by ll_iget_anon_dir(), and ll_set_inode().
static int ll_md_setattr (struct dentry * dentry, struct md_op_data * op_data) [static]
Definition at line 1501 of file llite_lib.c.
References CERROR, ENTRY, ll_sb_info::ll_dt_exp, ll_i2sbi(), ll_sb_info::ll_md_exp, ll_prep_md_op_data(), ll_update_inode(), LUSTRE_OPC_ANY, md_get_lustre_md(), md_setattr(), md_op_data::op_attr, ptlrpc_req_finished(), RETURN, simple_setattr, and TIMES_SET_FLAGS.
Referenced by ll_setattr_raw().
int ll_obd_statfs (struct inode * inode, void __user * arg)
Definition at line 2369 of file llite_lib.c.
References buf, GOTO, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf2, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, IOC_OBD_STATFS, obd_ioctl_data::ioc_pbuf1, obd_ioctl_data::ioc_pbuf2, obd_ioctl_data::ioc_plen1, obd_ioctl_data::ioc_plen2, ll_sb_info::ll_dt_exp, ll_i2sbi(), ll_sb_info::ll_md_exp, LL_STATFS_LMV, LL_STATFS_LOV, obd_iocontrol(), and obd_ioctl_getdata().
Referenced by ll_dir_ioctl(), and ll_file_ioctl().
void ll_open_cleanup (struct super_block * sb, struct ptlrpc_request * open_req)
Cleanup the open handle that is cached on MDT-side.
For open case, the client side open handling thread may hit error after the MDT grant the open. Under such case, the client should send close RPC to the MDT as cleanup; otherwise, the open handle on the MDT will be leaked there until the client umount or evicted.
In further, if someone unlinked the file, because the open handle holds the reference on such file/object, then it will block the subsequent threads that want to locate such object via FID.
Parameters:
[in] sb super block for this file-system
[in] open_req pointer to the original open request
Definition at line 2256 of file llite_lib.c.
References cfs_time_current_sec(), CWARN, DFID, ENTRY, EXIT, ll_finish_md_op_data(), ll_get_fsname(), ll_s2sbi, mdt_body::mbo_fid1, mdt_body::mbo_handle, md_close(), OBD_ALLOC_PTR, md_op_data::op_data, md_op_data::op_fid1, md_op_data::op_handle, md_op_data::op_mod_time, PFID, ptlrpc_req_finished(), req_capsule_server_get(), RETURN_EXIT, RMF_MDT_BODY, and ptlrpc_request::rq_pill.
Referenced by ll_lookup_it_finish(), and ll_prep_inode().
static int ll_options (char * options, int * flags) [static]
Definition at line 798 of file llite_lib.c.
References CDEBUG, D_CONFIG, D_SUPER, ENTRY, LCONSOLE_ERROR_MSG, LL_SBI_32BIT_API, LL_SBI_ALWAYS_PING, LL_SBI_CHECKSUM, LL_SBI_FLOCK, LL_SBI_LAZYSTATFS, LL_SBI_LOCALFLOCK, LL_SBI_LRU_RESIZE, LL_SBI_NOLCK, LL_SBI_RMT_CLIENT, LL_SBI_USER_FID2PATH, LL_SBI_USER_XATTR, LL_SBI_VERBOSE, ll_set_opt(), and RETURN.
Referenced by ll_fill_super().
int ll_prep_inode (struct inode ** inode, struct ptlrpc_request * req, struct super_block * sb, struct lookup_intent * it)
Definition at line 2284 of file llite_lib.c.
References lustre_md::body, CERROR, cl_fid_build_ino(), cleanup(), cl_object_conf::coc_inode, cl_object_conf::coc_layout, cl_object_conf::coc_lock, cl_object_conf::coc_opc, lustre_handle::cookie, ENTRY, fid_is_sane(), GOTO, lookup_intent::it_lock_handle, lookup_intent::it_lock_mode, lookup_intent::it_op, IT_OPEN, LASSERT, lustre_md::layout, ldlm_handle2lock(), ldlm_has_layout(), LDLM_LOCK_PUT, ll_sb_info::ll_dt_exp, ll_sb_info::ll_flags, ll_i2sbi(), ll_iget(), ll_layout_conf(), ll_sb_info::ll_md_exp, ll_open_cleanup(), ll_s2sbi, LL_SBI_32BIT_API, ll_update_inode(), mdt_body::mbo_fid1, md_free_lustre_md(), md_get_lustre_md(), OBJECT_CONF_SET, and cl_object_conf::u.
Referenced by __ll_inode_revalidate(), ll_create_node(), ll_dir_setdirstripe(), ll_get_fid_by_name(), ll_intent_file_open(), ll_lookup_it_finish(), ll_new_node(), ll_revalidate_it_finish(), sa_instantiate(), and search_inode_for_lustre().
struct md_op_data* ll_prep_md_op_data (struct md_op_data * op_data, struct inode * i1, struct inode * i2, const char * name, size_t namelen, __u32 mode, __u32 opc, void * data) [read]
Definition at line 2440 of file llite_lib.c.
References cfs_curproc_cap_pack(), cfs_time_current_sec(), CLI_API32, CLI_HASH64, fid_zero(), filename_is_volatile(), from_kgid(), from_kuid(), LASSERT, ll_i2gids(), ll_i2info(), ll_i2sbi(), ll_inode2fid(), ll_need_32bit_api(), LL_SBI_64BIT_HASH, ll_inode_info::lli_def_stripe_offset, ll_inode_info::lli_lsm_md, lu_name_is_valid_2(), LUSTRE_OPC_CREATE, LUSTRE_OPC_MKDIR, MDS_CREATE_VOLATILE, OBD_ALLOC_PTR, md_op_data::op_bias, md_op_data::op_cap, md_op_data::op_cli_flags, md_op_data::op_data, md_op_data::op_default_stripe_offset, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_fsgid, md_op_data::op_fsuid, md_op_data::op_mds, md_op_data::op_mea1, md_op_data::op_mea2, md_op_data::op_mod_time, md_op_data::op_mode, md_op_data::op_name, md_op_data::op_namelen, and md_op_data::op_suppgids.
Referenced by __ll_inode_revalidate(), get_hsm_state(), is_first_dirent(), ll_dir_get_parent_fid(), ll_dir_getstripe(), ll_dir_setdirstripe(), ll_dir_setstripe(), ll_file_flock(), ll_file_ioctl(), ll_get_fid_by_name(), ll_get_name(), ll_hsm_state_set(), ll_intent_file_open(), ll_iocontrol(), ll_layout_refresh_locked(), ll_lease_open(), ll_link(), ll_lookup_it(), ll_lov_getstripe_ea_info(), ll_md_setattr(), ll_migrate(), ll_new_node(), ll_prepare_close(), ll_readdir(), ll_readlink_internal(), ll_rename(), ll_rmdir(), ll_rmdir_entry(), ll_statahead_thread(), ll_swap_layouts(), ll_unlink(), ll_xattr_find_get_lock(), and sa_prep_data().
int ll_process_config (struct lustre_cfg * lcfg)
Definition at line 2413 of file llite_lib.c.
References class_process_proc_param(), LASSERT, LMD_MAGIC, lustre_cfg_string(), and PARAM_LLITE.
Referenced by lustre_init().
void ll_put_super (struct super_block * sb)
Definition at line 1099 of file llite_lib.c.
References cl_client_cache::ccc_unstable_nr, cl_client_cache::ccc_unstable_waitq, CDEBUG, config_llog_instance::cfg_instance, cl_env_cache_purge(), class_del_profile(), class_devices_in_group(), class_exp2obd(), class_manual_cleanup(), client_common_put_super(), D_VFSTRACE, ENTRY, EXIT, l_wait_event, LASSERTF, LCONSOLE_WARN, ll_sb_info::ll_cache, ll_sb_info::ll_client_common_fill_super_succeeded, ll_sb_info::ll_flags, ll_free_sbi(), ll_sb_info::ll_md_exp, ll_s2sbi, ll_sb_info::ll_sb_uuid, LL_SBI_VERBOSE, lustre_common_put_super(), lustre_end_log(), LWI_INTR, LWI_ON_SIGNAL_NOOP, obd_device::obd_force, and PARAMS_FILENAME.
Referenced by ll_fill_super().
int ll_read_inode2 (struct inode * inode, void * opaque)
Definition at line 1987 of file llite_lib.c.
References CDEBUG, D_VFSTRACE, DFID, ENTRY, EXIT, ll_aops, ll_dir_inode_operations, ll_dir_operations, ll_fast_symlink_inode_operations, ll_file_inode_operations, ll_sb_info::ll_fop, ll_i2info(), ll_i2sbi(), ll_special_inode_operations, ll_update_inode(), ll_inode_info::lli_fid, LTIME_S, PFID, and RETURN.
Referenced by ll_iget().
int ll_remount_fs (struct super_block * sb, int * flags, char * data)
Definition at line 2209 of file llite_lib.c.
References KEY_READ_ONLY, LCONSOLE_WARN, ll_sb_info::ll_flags, ll_sb_info::ll_md_exp, ll_s2sbi, LL_SBI_VERBOSE, and obd_set_info_async().
int ll_set_default_mdsize (struct ll_sb_info * sbi, int lmmsize)
Set the default_easize parameter to the given value.
See also:
client_obd::cl_default_mds_easize
Parameters:
[in] sbi superblock info for this filesystem
[in] lmmsize the size to set
Return values:
0 on success
negative negated errno on failure
Definition at line 673 of file llite_lib.c.
References KEY_DEFAULT_EASIZE, ll_sb_info::ll_md_exp, lov_mds_md, OBD_MAX_DEFAULT_EA_SIZE, obd_set_info_async(), and RETURN.
static int ll_set_opt (const char * opt, char * data, int fl) [inline, static]
Definition at line 789 of file llite_lib.c.
Referenced by ll_options().
int ll_setattr (struct dentry * de, struct iattr * attr)
Definition at line 1727 of file llite_lib.c.
References ll_setattr_raw(), MDS_OPEN_OWNEROVERRIDE, and mode.
int ll_setattr_raw (struct dentry * dentry, struct iattr * attr, bool hsm_import)
Definition at line 1574 of file llite_lib.c.
References ATTR_CTIME_SET, CDEBUG, CFS_CAP_FOWNER, cfs_capable(), cfs_time_current_sec(), cl_setattr_ost(), D_INFO, D_INODE, D_VFSTRACE, DFID, ENTRY, EXIT, GOTO, HS_DIRTY, HSS_SETMASK, hsm_state_set::hss_valid, inode_dio_wait, inode_dio_write_done, ll_file_clear_flag(), ll_file_maxbytes(), ll_file_test_and_clear_flag(), ll_finish_md_op_data(), ll_get_fsname(), ll_hsm_state_set(), ll_i2info(), ll_i2sbi(), ll_inode2fid(), ll_md_setattr(), ll_stats_ops_tally(), ll_inode_info::lli_clob, ll_inode_info::lli_fid, LLIF_DATA_MODIFIED, LPROC_LL_SETATTR, LPROC_LL_TRUNC, LPU64, LTIME_S, MDS_DATA_MODIFIED, MDS_OPEN_OWNEROVERRIDE, OBD_ALLOC_PTR, md_op_data::op_attr, md_op_data::op_bias, md_op_data::op_data, PFID, RETURN, TIMES_SET_FLAGS, and uid_eq().
Referenced by ll_file_futimes_3(), ll_hsm_import(), and ll_setattr().
int ll_show_options (struct seq_file * seq, struct vfsmount * vfs)
Definition at line 2515 of file llite_lib.c.
References LASSERT, ll_sb_info::ll_flags, ll_s2sbi, LL_SBI_ALWAYS_PING, LL_SBI_FLOCK, LL_SBI_LAZYSTATFS, LL_SBI_LOCALFLOCK, LL_SBI_NOLCK, LL_SBI_USER_FID2PATH, LL_SBI_USER_XATTR, and RETURN.
int ll_statfs (struct dentry * de, struct kstatfs * sfs)
Definition at line 1806 of file llite_lib.c.
References __u64, CDEBUG, cfs_time_shift_64(), D_VFSTRACE, ll_s2sbi, ll_statfs_internal(), ll_stats_ops_tally(), LPROC_LL_STAFS, LPU64, OBD_STATFS_CACHE_SECONDS, obd_statfs::os_bavail, obd_statfs::os_bfree, obd_statfs::os_blocks, and statfs_unpack().
int ll_statfs_internal (struct super_block * sb, struct obd_statfs * osfs, __u64 max_age, __u32 flags)
Definition at line 1757 of file llite_lib.c.
References CDEBUG, CERROR, D_SUPER, ENTRY, ll_sb_info::ll_dt_exp, ll_sb_info::ll_flags, ll_sb_info::ll_md_exp, ll_s2sbi, LL_SBI_LAZYSTATFS, LPU64, obd_statfs(), OBD_STATFS_NODELAY, obd_statfs_rqset(), obd_statfs::os_bavail, obd_statfs::os_bfree, obd_statfs::os_blocks, obd_statfs::os_bsize, obd_statfs::os_ffree, obd_statfs::os_files, obd_statfs::os_type, and RETURN.
Referenced by ll_statfs().
void ll_umount_begin (struct super_block * sb)
Definition at line 2162 of file llite_lib.c.
References CDEBUG, CERROR, class_exp2obd(), D_VFSTRACE, ENTRY, EXIT, obd_export::exp_handle, portals_handle::h_cookie, IOC_OSC_SET_ACTIVE, ll_sb_info::ll_dt_exp, ll_sb_info::ll_md_exp, ll_s2sbi, LPX64, OBD_ALLOC_PTR, obd_device::obd_force, OBD_FREE_PTR, and obd_iocontrol().
int ll_update_inode (struct inode * inode, struct lustre_md * md)
Definition at line 1865 of file llite_lib.c.
References lustre_md::body, CDEBUG, cl_fid_build_gen(), cl_fid_build_ino(), cl_file_inode_init(), D_INODE, D_VFSTRACE, DFID, fid_is_sane(), LASSERT, LASSERTF, ll_file_clear_flag(), ll_file_set_flag(), ll_sb_info::ll_flags, ll_i2info(), ll_i2sbi(), ll_inode2fid(), LL_MAX_BLKSIZE_BITS, LL_SBI_32BIT_API, LL_SBI_RMT_CLIENT, ll_update_lsm_md(), ll_update_remote_perm(), ll_inode_info::lli_atime, ll_inode_info::lli_ctime, ll_inode_info::lli_fid, ll_inode_info::lli_lock, ll_inode_info::lli_mtime, ll_inode_info::lli_posix_acl, LLIF_FILE_RESTORING, LPU64, LTIME_S, lu_fid_eq(), make_kgid(), make_kuid(), mdt_body::mbo_atime, mdt_body::mbo_blocks, mdt_body::mbo_ctime, mdt_body::mbo_fid1, mdt_body::mbo_flags, mdt_body::mbo_gid, mdt_body::mbo_mode, mdt_body::mbo_mtime, mdt_body::mbo_nlink, mdt_body::mbo_rdev, mdt_body::mbo_size, mdt_body::mbo_t_state, mdt_body::mbo_uid, mdt_body::mbo_valid, MS_RESTORE, OBD_MD_FLACL, OBD_MD_FLATIME, OBD_MD_FLBLOCKS, OBD_MD_FLCTIME, OBD_MD_FLEASIZE, OBD_MD_FLFLAGS, OBD_MD_FLGID, OBD_MD_FLID, OBD_MD_FLMODE, OBD_MD_FLMTIME, OBD_MD_FLNLINK, OBD_MD_FLRDEV, OBD_MD_FLRMTPERM, OBD_MD_FLSIZE, OBD_MD_FLTYPE, OBD_MD_FLUID, OBD_MD_TSTATE, PFID, PTLRPC_MAX_BRW_BITS, lustre_md::remote_perm, and set_nlink().
Referenced by ll_iget(), ll_md_setattr(), ll_prep_inode(), and ll_read_inode2().
static int ll_update_lsm_md (struct inode * inode, struct lustre_md * md) [static]
Definition at line 1320 of file llite_lib.c.
References lustre_md::body, cl_attr::cat_atime, cl_attr::cat_ctime, cl_attr::cat_mtime, cl_attr::cat_nlink, cl_attr::cat_size, CDEBUG, CERROR, D_INODE, DFID, ENTRY, LASSERT, ll_get_fsname(), ll_i2info(), ll_i2mdexp(), ll_init_lsm_md(), ll_inode2fid(), ll_md_blocking_ast(), ll_inode_info::lli_fid, ll_inode_info::lli_lsm_md, lmv_oinfo::lmo_fid, lustre_md::lmv, lmv_free_memmd(), LMV_HASH_FLAG_MIGRATION, lsm_md_eq(), lmv_stripe_md::lsm_md_hash_type, lmv_stripe_md::lsm_md_layout_version, lmv_stripe_md::lsm_md_magic, lmv_stripe_md::lsm_md_master_mdt_index, lmv_stripe_md::lsm_md_oinfo, lmv_stripe_md::lsm_md_pool_name, lmv_stripe_md::lsm_md_stripe_count, mdt_body::mbo_atime, mdt_body::mbo_ctime, mdt_body::mbo_mtime, mdt_body::mbo_nlink, mdt_body::mbo_size, mdt_body::mbo_valid, md_merge_attr(), OBD_ALLOC_PTR, OBD_FREE_PTR, OBD_MD_FLATIME, OBD_MD_FLCTIME, OBD_MD_FLMTIME, OBD_MD_FLNLINK, OBD_MD_FLSIZE, PFID, and RETURN.
Referenced by ll_update_inode().
static int lli_lsm_md_eq (const struct lmv_stripe_md * lsm_md1, const struct lmv_stripe_md * lsm_md2) [inline, static]
Definition at line 1306 of file llite_lib.c.
References lmv_stripe_md::lsm_md_hash_type, lmv_stripe_md::lsm_md_layout_version, lmv_stripe_md::lsm_md_magic, lmv_stripe_md::lsm_md_master_mdt_index, lmv_stripe_md::lsm_md_pool_name, and lmv_stripe_md::lsm_md_stripe_count.
void lustre_dump_dentry (struct dentry * dentry, int recur)
Definition at line 705 of file llite_lib.c.
References CERROR, d_child, LASSERT, list_entry, list_for_each, ll_d_count, ll_dump_inode(), and lustre_dump_dentry().
Referenced by ll_invalidate_aliases(), and lustre_dump_dentry().
Variable Documentation
struct kmem_cache* ll_file_data_slab
Definition at line 65 of file llite_lib.c.
Referenced by ll_file_data_get(), ll_file_data_put(), lustre_exit(), and lustre_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.