Lustre: lustre/llite/llite_nfs.c File Reference
lustre/llite/llite_nfs.c File Reference
#include "llite_internal.h"
#include <linux/exportfs.h>
Data Structures
struct lustre_nfs_fid
Defines
#define DEBUG_SUBSYSTEM S_LLITE
#define FILEID_INVALID 0xff
#define FILEID_LUSTRE 0x97
Functions
__u32 get_uuid2int (const char *name, int len)
struct inode * search_inode_for_lustre (struct super_block *sb, const struct lu_fid *fid)
static struct dentry * ll_iget_for_nfs (struct super_block *sb, struct lu_fid *fid, struct lu_fid *parent)
static int ll_encode_fh (struct dentry *de, __u32 *fh, int *plen, int connectable)
connectable - is nfsd will connect himself or this should be done at lustre
static int ll_nfs_get_name_filldir (void *cookie, const char *name, int namelen, loff_t hash, u64 ino, unsigned type)
static int ll_get_name (struct dentry *dentry, char *name, struct dentry *child)
static struct dentry * ll_fh_to_dentry (struct super_block *sb, struct fid *fid, int fh_len, int fh_type)
static struct dentry * ll_fh_to_parent (struct super_block *sb, struct fid *fid, int fh_len, int fh_type)
int ll_dir_get_parent_fid (struct inode *dir, struct lu_fid *parent_fid)
static struct dentry * ll_get_parent (struct dentry *dchild)
Variables
struct export_operations lustre_export_operations
Define Documentation
#define DEBUG_SUBSYSTEM S_LLITE
Definition at line 44 of file llite_nfs.c.
#define FILEID_INVALID 0xff
Definition at line 145 of file llite_nfs.c.
Referenced by ll_encode_fh().
#define FILEID_LUSTRE 0x97
Definition at line 148 of file llite_nfs.c.
Referenced by ll_encode_fh(), ll_fh_to_dentry(), and ll_fh_to_parent().
Function Documentation
__u32 get_uuid2int (const char * name, int len)
Definition at line 48 of file llite_nfs.c.
Referenced by client_common_fill_super().
int ll_dir_get_parent_fid (struct inode * dir, struct lu_fid * parent_fid)
Definition at line 287 of file llite_nfs.c.
References CDEBUG, CERROR, D_INFO, DFID, dotdot, ENTRY, LASSERT, ll_finish_md_op_data(), ll_get_default_mdsize(), ll_get_fsname(), ll_inode2fid(), ll_sb_info::ll_md_exp, ll_prep_md_op_data(), ll_s2sbi, LUSTRE_OPC_ANY, mdt_body::mbo_fid1, mdt_body::mbo_valid, md_getattr_name(), OBD_MD_FLID, md_op_data::op_data, PFID, ptlrpc_req_finished(), req_capsule_server_get(), RETURN, RMF_MDT_BODY, and ptlrpc_request::rq_pill.
Referenced by ll_get_parent(), and ll_readdir().
static int ll_encode_fh (struct dentry * de, __u32 * fh, int * plen, int connectable) [static]
connectable - is nfsd will connect himself or this should be done at lustre
The return value is file handle type: 1 -- contains child file handle; 2 -- contains child file handle and parent file handle; 255 -- error.
Definition at line 161 of file llite_nfs.c.
References CDEBUG, D_INFO, DFID, ENTRY, fid_zero(), FILEID_INVALID, FILEID_LUSTRE, ll_get_fsname(), ll_inode2fid(), lustre_nfs_fid::lnf_child, lustre_nfs_fid::lnf_parent, PFID, and RETURN.
static struct dentry* ll_fh_to_dentry (struct super_block * sb, struct fid * fid, int fh_len, int fh_type) [static, read]
Definition at line 265 of file llite_nfs.c.
References FILEID_LUSTRE, ll_iget_for_nfs(), lustre_nfs_fid::lnf_child, lustre_nfs_fid::lnf_parent, and RETURN.
static struct dentry* ll_fh_to_parent (struct super_block * sb, struct fid * fid, int fh_len, int fh_type) [static, read]
Definition at line 276 of file llite_nfs.c.
References FILEID_LUSTRE, ll_iget_for_nfs(), lustre_nfs_fid::lnf_parent, and RETURN.
static int ll_get_name (struct dentry * dentry, char * name, struct dentry * child) [static]
Definition at line 221 of file llite_nfs.c.
References __u64, dir, ENTRY, EXIT, GOTO, ll_getname_data::lgd_found, ll_getname_data::lgd_name, ll_dir_read(), ll_finish_md_op_data(), ll_i2info(), ll_i2sbi(), ll_sb_info::ll_md_brw_pages, ll_nfs_get_name_filldir(), ll_prep_md_op_data(), ll_inode_info::lli_fid, LUSTRE_OPC_ANY, md_op_data::op_data, and md_op_data::op_max_pages.
static struct dentry* ll_get_parent (struct dentry * dchild) [static, read]
Definition at line 340 of file llite_nfs.c.
References ENTRY, ll_dir_get_parent_fid(), ll_iget_for_nfs(), and RETURN.
static struct dentry* ll_iget_for_nfs (struct super_block * sb, struct lu_fid * fid, struct lu_fid * parent) [static, read]
Definition at line 117 of file llite_nfs.c.
References CDEBUG, D_INFO, DFID, ENTRY, fid_is_sane(), PFID, RETURN, and search_inode_for_lustre().
Referenced by ll_fh_to_dentry(), ll_fh_to_parent(), and ll_get_parent().
static int ll_nfs_get_name_filldir (void * cookie, const char * name, int namelen, loff_t hash, u64 ino, unsigned type) [static]
Definition at line 196 of file llite_nfs.c.
References fid_le_to_cpu(), lu_dirent::lde_fid, lu_dirent::lde_name, ll_getname_data::lgd_fid, ll_getname_data::lgd_found, ll_getname_data::lgd_name, and lu_fid_eq().
Referenced by ll_get_name().
struct inode* search_inode_for_lustre (struct super_block * sb, const struct lu_fid * fid) [read]
Definition at line 60 of file llite_nfs.c.
References CDEBUG, cl_fid_build_ino(), D_INFO, DFID, ENTRY, ll_get_default_mdsize(), ll_sb_info::ll_md_exp, ll_need_32bit_api(), ll_prep_inode(), ll_s2sbi, ll_test_inode_by_fid(), md_getattr(), OBD_ALLOC_PTR, OBD_FREE_PTR, OBD_MD_FLEASIZE, md_op_data::op_data, md_op_data::op_fid1, md_op_data::op_mode, md_op_data::op_valid, PFID, ptlrpc_req_finished(), and RETURN.
Referenced by ll_dir_ioctl(), ll_iget_for_nfs(), ll_ioc_copy_end(), and ll_ioc_copy_start().
Variable Documentation
struct export_operations lustre_export_operations
Initial value:
 {
       .get_parent = ll_get_parent,
       .encode_fh  = ll_encode_fh,
       .get_name   = ll_get_name,
        .fh_to_dentry = ll_fh_to_dentry,
        .fh_to_parent = ll_fh_to_parent,
}
Definition at line 356 of file llite_nfs.c.
Referenced by client_common_fill_super().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.