Lustre: lustre/llite/llite_internal.h File Reference
lustre/llite/llite_internal.h File Reference
#include <lustre_debug.h>
#include <lustre_ver.h>
#include <lustre_disk.h>
#include <lustre_eacl.h>
#include <lustre_linkea.h>
#include <cl_object.h>
#include <lustre_lmv.h>
#include <lustre_mdc.h>
#include <lustre_intent.h>
#include <linux/compat.h>
#include <linux/aio.h>
#include "vvp_internal.h"
#include "range_lock.h"
Data Structures
struct ll_dentry_data
struct ll_getname_data
struct ll_remote_perm
struct ll_grouplock
struct ll_inode_info
struct ll_ra_info
struct ra_io_arg
struct per_process_info
struct ll_rw_extents_info
struct ll_rw_process_info
struct rmtacl_ctl_entry
struct rmtacl_ctl_table
struct eacl_entry
struct eacl_table
struct lustre_client_ocd
struct ll_sb_info
struct ll_readahead_state
struct ll_file_data
struct ll_dir_chain
struct vvp_io_args
IO arguments for various VFS I/O interfaces.
struct ll_cl_context
struct ll_thread_info
struct ll_statahead_info
struct ll_dio_pages
direct write pages
Defines
#define FMODE_EXEC 0
#define VM_FAULT_RETRY 0
#define LOOKUP_CONTINUE LOOKUP_PARENT
#define LL_DIR_END_OFF 0x7fffffffffffffffULL
Only used on client-side for indicating the tail of dir hash/offset.
#define LL_DIR_END_OFF_32BIT 0x7fffffffUL
#define LL_MAX_BLKSIZE_BITS 22
#define LL_IT2STR(it) ((it) ? ldlm_it2str((it)->it_op) : "0")
#define LUSTRE_FPRIVATE(file) ((file)->private_data)
#define ll_d2d(de) ((struct ll_dentry_data*)((de)->d_fsdata))
#define LLI_INODE_MAGIC 0x111d0de5
#define LLI_INODE_DEAD 0xdeadd00d
#define REMOTE_PERM_HASHSIZE 16
#define SBI_DEFAULT_READAHEAD_MAX (64UL << (20 - PAGE_CACHE_SHIFT))
#define SBI_DEFAULT_READAHEAD_WHOLE_MAX (2UL << (20 - PAGE_CACHE_SHIFT))
#define LL_HIST_MAX 28
#define LL_HIST_START 12
#define LL_PROCESS_HIST_MAX 10
#define LL_OFFSET_HIST_MAX 100
#define LL_SBI_NOLCK 0x01
#define LL_SBI_CHECKSUM 0x02
#define LL_SBI_FLOCK 0x04
#define LL_SBI_USER_XATTR 0x08
#define LL_SBI_ACL 0x10
#define LL_SBI_RMT_CLIENT 0x40
#define LL_SBI_MDS_CAPA 0x80
#define LL_SBI_OSS_CAPA 0x100
#define LL_SBI_LOCALFLOCK 0x200
#define LL_SBI_LRU_RESIZE 0x400
#define LL_SBI_LAZYSTATFS 0x800
#define LL_SBI_32BIT_API 0x2000
#define LL_SBI_64BIT_HASH 0x4000
#define LL_SBI_AGL_ENABLED 0x8000
#define LL_SBI_VERBOSE 0x10000
#define LL_SBI_LAYOUT_LOCK 0x20000
#define LL_SBI_USER_FID2PATH 0x40000
#define LL_SBI_XATTR_CACHE 0x80000
#define LL_SBI_NOROOTSQUASH 0x100000
#define LL_SBI_ALWAYS_PING 0x200000
#define LL_SBI_FLAGS
#define RCE_HASHES 32
#define EE_HASHES 32
#define ll_s2sbi(sb) (s2lsi(sb)->lsi_llsbi)
#define LL_SA_RPC_MIN 2
#define LL_SA_RPC_DEF 32
#define LL_SA_RPC_MAX 8192
#define LL_SA_CACHE_BIT 5
#define LL_SA_CACHE_SIZE (1 << LL_SA_CACHE_BIT)
#define LL_SA_CACHE_MASK (LL_SA_CACHE_SIZE - 1)
#define LLIOC_MAX_CMD 256
Enumerations
enum ll_file_flags { LLIF_DATA_MODIFIED = 0, LLIF_FILE_RESTORING = 1, LLIF_XATTR_CACHE = 2 }
enum ra_stat {
RA_STAT_HIT = 0, RA_STAT_MISS, RA_STAT_DISTANT_READPAGE, RA_STAT_MISS_IN_WINDOW,
RA_STAT_FAILED_GRAB_PAGE, RA_STAT_FAILED_MATCH, RA_STAT_DISCARDED, RA_STAT_ZERO_LEN,
RA_STAT_ZERO_WINDOW, RA_STAT_EOF, RA_STAT_MAX_IN_FLIGHT, RA_STAT_WRONG_GRAB_PAGE,
RA_STAT_FAILED_REACH_END, _NR_RA_STAT
}
enum stats_track_type {
STATS_TRACK_ALL = 0, STATS_TRACK_PID, STATS_TRACK_PPID, STATS_TRACK_GID,
STATS_TRACK_LAST
}
enum {
LPROC_LL_DIRTY_HITS, LPROC_LL_DIRTY_MISSES, LPROC_LL_READ_BYTES, LPROC_LL_WRITE_BYTES,
LPROC_LL_BRW_READ, LPROC_LL_BRW_WRITE, LPROC_LL_IOCTL, LPROC_LL_OPEN,
LPROC_LL_RELEASE, LPROC_LL_MAP, LPROC_LL_LLSEEK, LPROC_LL_FSYNC,
LPROC_LL_READDIR, LPROC_LL_SETATTR, LPROC_LL_TRUNC, LPROC_LL_FLOCK,
LPROC_LL_GETATTR, LPROC_LL_CREATE, LPROC_LL_LINK, LPROC_LL_UNLINK,
LPROC_LL_SYMLINK, LPROC_LL_MKDIR, LPROC_LL_RMDIR, LPROC_LL_MKNOD,
LPROC_LL_RENAME, LPROC_LL_STAFS, LPROC_LL_ALLOC_INODE, LPROC_LL_SETXATTR,
LPROC_LL_GETXATTR, LPROC_LL_GETXATTR_HITS, LPROC_LL_LISTXATTR, LPROC_LL_REMOVEXATTR,
LPROC_LL_INODE_PERM, LPROC_LL_FILE_OPCODES
}
enum {
LUSTRE_OPC_MKDIR = 0, LUSTRE_OPC_SYMLINK = 1, LUSTRE_OPC_MKNOD = 2, LUSTRE_OPC_CREATE = 3,
LUSTRE_OPC_ANY = 5
}
enum ras_update_flags { LL_RAS_HIT = 0x1, LL_RAS_MMAP = 0x2 }
enum llioc_iter { LLIOC_CONT = 0, LLIOC_STOP }
Functions
static __u32 ll_layout_version_get (struct ll_inode_info *lli)
static void ll_layout_version_set (struct ll_inode_info *lli, __u32 gen)
static void ll_file_set_flag (struct ll_inode_info *lli, enum ll_file_flags flag)
static void ll_file_clear_flag (struct ll_inode_info *lli, enum ll_file_flags flag)
static bool ll_file_test_flag (struct ll_inode_info *lli, enum ll_file_flags flag)
static bool ll_file_test_and_clear_flag (struct ll_inode_info *lli, enum ll_file_flags flag)
int ll_xattr_cache_destroy (struct inode *inode)
int ll_xattr_cache_get (struct inode *inode, const char *name, char *buffer, size_t size, __u64 valid)
int ll_init_security (struct dentry *dentry, struct inode *inode, struct inode *dir)
void ll_inode_size_lock (struct inode *inode)
void ll_inode_size_unlock (struct inode *inode)
static struct ll_inode_info * ll_i2info (struct inode *inode)
static struct inode * ll_info2i (struct ll_inode_info *lli)
__u32 ll_i2suppgid (struct inode *i)
void ll_i2gids (__u32 *suppgids, struct inode *i1, struct inode *i2)
static int ll_need_32bit_api (struct ll_sb_info *sbi)
void ll_ras_enter (struct file *f)
int cl_ocd_update (struct obd_device *host, struct obd_device *watched, enum obd_notify_event ev, void *owner, void *data)
This function is used as an upcall-callback hooked by liblustre and llite clients into obd_notify() listeners chain to handle notifications about change of import connect_flags.
int cl_get_grouplock (struct cl_object *obj, unsigned long gid, int nonblock, struct ll_grouplock *lg)
void cl_put_grouplock (struct ll_grouplock *lg)
static int lprocfs_register_mountpoint (struct proc_dir_entry *parent, struct super_block *sb, char *osc, char *mdc)
static void lprocfs_unregister_mountpoint (struct ll_sb_info *sbi)
static void ll_stats_ops_tally (struct ll_sb_info *sbi, int op, int count)
static void ll_dir_chain_init (struct ll_dir_chain *chain)
static void ll_dir_chain_fini (struct ll_dir_chain *chain)
int ll_dir_read (struct inode *inode, __u64 *pos, struct md_op_data *op_data, void *cookie, filldir_t filldir)
int ll_get_mdt_idx (struct inode *inode)
int ll_get_mdt_idx_by_fid (struct ll_sb_info *sbi, const struct lu_fid *fid)
struct page * ll_get_dir_page (struct inode *dir, struct md_op_data *op_data, __u64 offset, struct ll_dir_chain *chain)
void ll_release_page (struct inode *inode, struct page *page, bool remove)
struct inode * ll_iget (struct super_block *sb, ino_t hash, struct lustre_md *lic)
Get an inode by inode number(), which is already instantiated by the intent lookup).
int ll_test_inode_by_fid (struct inode *inode, void *opaque)
int ll_md_blocking_ast (struct ldlm_lock *, struct ldlm_lock_desc *, void *data, int flag)
struct dentry * ll_splice_alias (struct inode *inode, struct dentry *de)
int ll_rmdir_entry (struct inode *dir, char *name, int namelen)
Remove dir entry.
void ll_update_times (struct ptlrpc_request *request, struct inode *inode)
int ll_writepage (struct page *page, struct writeback_control *wbc)
int ll_writepages (struct address_space *, struct writeback_control *wbc)
int ll_readpage (struct file *file, struct page *page)
void ll_readahead_init (struct inode *inode, struct ll_readahead_state *ras)
int vvp_io_write_commit (const struct lu_env *env, struct cl_io *io)
struct ll_cl_context * ll_cl_find (struct file *file)
void ll_cl_add (struct file *file, const struct lu_env *env, struct cl_io *io)
void ll_cl_remove (struct file *file, const struct lu_env *env)
int ll_have_md_lock (struct inode *inode, __u64 *bits, enum ldlm_mode l_req_mode)
test if some locks matching bits and l_req_mode are acquired
bits can be in different locks
if found clear the common lock bits in *bits
the bits not found, are kept in *bits
enum ldlm_mode ll_take_md_lock (struct inode *inode, __u64 bits, struct lustre_handle *lockh, __u64 flags, enum ldlm_mode mode)
int ll_file_open (struct inode *inode, struct file *file)
int ll_file_release (struct inode *inode, struct file *file)
int ll_release_openhandle (struct dentry *, struct lookup_intent *)
Close inode open handle.
int ll_md_real_close (struct inode *inode, fmode_t fmode)
void ll_rw_stats_tally (struct ll_sb_info *sbi, pid_t pid, struct ll_file_data *file, loff_t pos, size_t count, int rw)
int ll_getattr (struct vfsmount *mnt, struct dentry *de, struct kstat *stat)
struct posix_acl * ll_get_acl (struct inode *inode, int type)
int ll_migrate (struct inode *parent, struct file *file, int mdtidx, const char *name, int namelen)
int ll_get_fid_by_name (struct inode *parent, const char *name, int namelen, struct lu_fid *fid, struct inode **inode)
int ll_inode_permission (struct inode *inode, int mask, struct nameidata *nd)
int ll_lov_setstripe_ea_info (struct inode *inode, struct file *file, __u64 flags, struct lov_user_md *lum, int lum_size)
int ll_lov_getstripe_ea_info (struct inode *inode, const char *filename, struct lov_mds_md **lmm, int *lmm_size, struct ptlrpc_request **request)
int ll_dir_setstripe (struct inode *inode, struct lov_user_md *lump, int set_default)
int ll_dir_getstripe (struct inode *inode, void **lmmp, int *lmm_size, struct ptlrpc_request **request, u64 valid)
This function will be used to get default LOV/LMV/Default LMV will be used to indicate which stripe it will retrieve OBD_MD_MEA LMV stripe EA OBD_MD_DEFAULT_MEA Default LMV stripe EA otherwise Default LOV EA.
int ll_fsync (struct file *file, struct dentry *dentry, int data)
int ll_merge_attr (const struct lu_env *env, struct inode *inode)
int ll_fid2path (struct inode *inode, void __user *arg)
int ll_data_version (struct inode *inode, __u64 *data_version, int flags)
int ll_hsm_release (struct inode *inode)
int ll_hsm_state_set (struct inode *inode, struct hsm_state_set *hss)
int ll_d_init (struct dentry *de)
void ll_intent_drop_lock (struct lookup_intent *)
void ll_intent_release (struct lookup_intent *)
void ll_invalidate_aliases (struct inode *)
void ll_lookup_finish_locks (struct lookup_intent *it, struct dentry *dentry)
int ll_revalidate_it_finish (struct ptlrpc_request *request, struct lookup_intent *it, struct dentry *de)
void ll_lli_init (struct ll_inode_info *lli)
int ll_fill_super (struct super_block *sb, struct vfsmount *mnt)
void ll_put_super (struct super_block *sb)
void ll_kill_super (struct super_block *sb)
struct inode * ll_inode_from_resource_lock (struct ldlm_lock *lock)
void ll_dir_clear_lsm_md (struct inode *inode)
void ll_clear_inode (struct inode *inode)
int ll_setattr_raw (struct dentry *dentry, struct iattr *attr, bool hsm_import)
int ll_setattr (struct dentry *de, struct iattr *attr)
int ll_statfs (struct dentry *de, struct kstatfs *sfs)
int ll_statfs_internal (struct super_block *sb, struct obd_statfs *osfs, __u64 max_age, __u32 flags)
int ll_update_inode (struct inode *inode, struct lustre_md *md)
int ll_read_inode2 (struct inode *inode, void *opaque)
void ll_delete_inode (struct inode *inode)
int ll_iocontrol (struct inode *inode, struct file *file, unsigned int cmd, unsigned long arg)
int ll_flush_ctx (struct inode *inode)
void ll_umount_begin (struct super_block *sb)
int ll_remount_fs (struct super_block *sb, int *flags, char *data)
int ll_show_options (struct seq_file *seq, struct vfsmount *vfs)
void ll_dirty_page_discard_warn (struct page *page, int ioret)
int ll_prep_inode (struct inode **inode, struct ptlrpc_request *req, struct super_block *, struct lookup_intent *)
void lustre_dump_dentry (struct dentry *, int recur)
int ll_obd_statfs (struct inode *inode, void __user *arg)
int ll_get_max_mdsize (struct ll_sb_info *sbi, int *max_mdsize)
int ll_get_default_mdsize (struct ll_sb_info *sbi, int *default_mdsize)
Get the value of the default_easize parameter.
int ll_set_default_mdsize (struct ll_sb_info *sbi, int default_mdsize)
Set the default_easize parameter to the given value.
int ll_process_config (struct lustre_cfg *lcfg)
struct md_op_data * ll_prep_md_op_data (struct md_op_data *op_data, struct inode *i1, struct inode *i2, const char *name, size_t namelen, __u32 mode, __u32 opc, void *data)
void ll_finish_md_op_data (struct md_op_data *op_data)
int ll_get_obd_name (struct inode *inode, unsigned int cmd, unsigned long arg)
Get obd name by cmd, and copy out to user space.
char * ll_get_fsname (struct super_block *sb, char *buf, int buflen)
Get lustre file system name by sbi.
void ll_compute_rootsquash_state (struct ll_sb_info *sbi)
ssize_t ll_copy_user_md (const struct lov_user_md __user *md, struct lov_user_md **kbuf)
void ll_open_cleanup (struct super_block *sb, struct ptlrpc_request *open_req)
Cleanup the open handle that is cached on MDT-side.
static ssize_t ll_lov_user_md_size (const struct lov_user_md *lum)
__u32 get_uuid2int (const char *name, int len)
struct inode * search_inode_for_lustre (struct super_block *sb, const struct lu_fid *fid)
int ll_dir_get_parent_fid (struct inode *dir, struct lu_fid *parent_fid)
static struct ll_thread_info * ll_env_info (const struct lu_env *env)
static struct vvp_io_args * ll_env_args (const struct lu_env *env, enum vvp_io_subtype type)
int ll_teardown_mmaps (struct address_space *mapping, __u64 first, __u64 last)
int ll_file_mmap (struct file *file, struct vm_area_struct *vma)
void policy_from_vma (union ldlm_policy_data *policy, struct vm_area_struct *vma, unsigned long addr, size_t count)
struct vm_area_struct * our_vma (struct mm_struct *mm, unsigned long addr, size_t count)
static void ll_invalidate_page (struct page *vmpage)
static struct obd_export * ll_s2dtexp (struct super_block *sb)
static struct obd_export * ll_s2mdexp (struct super_block *sb)
static struct client_obd * sbi2mdc (struct ll_sb_info *sbi)
static struct ll_sb_info * ll_i2sbi (struct inode *inode)
static struct obd_export * ll_i2dtexp (struct inode *inode)
static struct obd_export * ll_i2mdexp (struct inode *inode)
static struct lu_fid * ll_inode2fid (struct inode *inode)
static loff_t ll_file_maxbytes (struct inode *inode)
int ll_setxattr (struct dentry *dentry, const char *name, const void *value, size_t size, int flags)
ssize_t ll_getxattr (struct dentry *dentry, const char *name, void *buffer, size_t size)
ssize_t ll_listxattr (struct dentry *dentry, char *buffer, size_t size)
int ll_removexattr (struct dentry *dentry, const char *name)
void free_rmtperm_hash (struct hlist_head *hash)
int ll_update_remote_perm (struct inode *inode, struct mdt_remote_perm *perm)
int lustre_check_remote_perm (struct inode *inode, int mask)
int cl_sb_init (struct super_block *sb)
Common IO arguments for various VFS I/O interfaces.
int cl_sb_fini (struct super_block *sb)
void ll_ra_count_put (struct ll_sb_info *sbi, unsigned long len)
void ll_ra_stats_inc (struct inode *inode, enum ra_stat which)
int ll_statahead (struct inode *dir, struct dentry **dentry, bool unplug)
statahead entry function, this is called when client getattr on a file, it will start statahead thread if this is the first dir entry, else revalidate dentry from statahead cache.
void ll_authorize_statahead (struct inode *dir, void *key)
void ll_deauthorize_statahead (struct inode *dir, void *key)
blkcnt_t dirty_cnt (struct inode *inode)
int cl_glimpse_size0 (struct inode *inode, int agl)
int cl_glimpse_lock (const struct lu_env *env, struct cl_io *io, struct inode *inode, struct cl_object *clob, int agl)
static int cl_glimpse_size (struct inode *inode)
static int cl_agl (struct inode *inode)
static int ll_glimpse_size (struct inode *inode)
static bool dentry_may_statahead (struct inode *dir, struct dentry *dentry)
void * ll_iocontrol_register (llioc_callback_t cb, int count, unsigned int *cmd)
void ll_iocontrol_unregister (void *magic)
int cl_sync_file_range (struct inode *inode, loff_t start, loff_t end, enum cl_fsync_mode mode, int ignore_layout)
Called to make sure a portion of file has been written out.
ssize_t ll_direct_rw_pages (const struct lu_env *env, struct cl_io *io, int rw, struct inode *inode, struct ll_dio_pages *pv)
static int ll_file_nolock (const struct file *file)
static void ll_set_lock_data (struct obd_export *exp, struct inode *inode, struct lookup_intent *it, __u64 *bits)
static void ll_lock_dcache (struct inode *inode)
static void ll_unlock_dcache (struct inode *inode)
static int d_lustre_invalid (const struct dentry *dentry)
static void __d_lustre_invalidate (struct dentry *dentry)
static void d_lustre_invalidate (struct dentry *dentry, int nested)
static void d_lustre_revalidate (struct dentry *dentry)
int ll_layout_conf (struct inode *inode, const struct cl_object_conf *conf)
int ll_layout_refresh (struct inode *inode, __u32 *gen)
This function checks if there exists a LAYOUT lock on the client side, or enqueues it if it doesn't have one in cache.
int ll_layout_restore (struct inode *inode, loff_t start, __u64 length)
This function send a restore request to the MDT.
int ll_xattr_init (void)
void ll_xattr_fini (void)
int ll_getxattr_common (struct inode *inode, const char *name, void *buffer, size_t size, __u64 valid)
int ll_page_sync_io (const struct lu_env *env, struct cl_io *io, struct cl_page *page, enum cl_req_type crt)
int ll_getparent (struct file *file, struct getparent __user *arg)
Get parent FID and name of an identified link.
int cl_setattr_ost (struct cl_object *obj, const struct iattr *attr, unsigned int attr_flags)
int cl_file_inode_init (struct inode *inode, struct lustre_md *md)
Initialize or update CLIO structures for regular files when new meta-data arrives from the server.
void cl_inode_fini (struct inode *inode)
u64 cl_fid_build_ino (const struct lu_fid *fid, int api32)
build inode number from passed
u32 cl_fid_build_gen (const struct lu_fid *fid)
build inode generation from passed .
Variables
struct kmem_cache * ll_file_data_slab
spinlock_t inode_lock
struct proc_dir_entry * proc_lustre_fs_root
struct file_operations ll_dir_operations
struct inode_operations ll_dir_inode_operations
struct inode_operations ll_special_inode_operations
struct address_space_operations ll_aops
struct file_operations ll_file_operations
struct file_operations ll_file_operations_flock
struct file_operations ll_file_operations_noflock
struct inode_operations ll_file_inode_operations
struct dentry_operations ll_d_ops
struct super_operations lustre_super_operations
struct export_operations lustre_export_operations
struct inode_operations ll_fast_symlink_inode_operations
struct lu_context_key ll_thread_key
struct kmem_cache * ll_remote_perm_cachep
struct kmem_cache * ll_rmtperm_hash_cachep
enum llioc_iter(* llioc_callback_t)(struct inode *inode, struct file *file, unsigned int cmd, unsigned long arg, void *magic, int *rcp)
struct lu_env * cl_inode_fini_env
An `emergency' environment used by cl_inode_fini() when cl_env_get() fails.
__u16 cl_inode_fini_refcheck
Define Documentation
#define EE_HASHES 32
Definition at line 487 of file llite_internal.h.
#define FMODE_EXEC 0
Definition at line 57 of file llite_internal.h.
Referenced by ll_clear_inode(), ll_file_open(), ll_lease_open(), ll_local_open(), ll_md_blocking_ast(), ll_md_close(), ll_md_real_close(), mdc_intent_open_pack(), and mds_pack_open_flags().
#define ll_d2d (de) ((struct ll_dentry_data*)((de)->d_fsdata))
Definition at line 87 of file llite_internal.h.
Referenced by __d_lustre_invalidate(), d_lustre_invalid(), d_lustre_revalidate(), dentry_may_statahead(), ll_create_nd(), ll_lookup_nd(), ll_release(), and revalidate_statahead_dentry().
#define LL_DIR_END_OFF 0x7fffffffffffffffULL
Only used on client-side for indicating the tail of dir hash/offset.
Definition at line 71 of file llite_internal.h.
Referenced by ll_dir_seek(), and ll_readdir().
#define LL_DIR_END_OFF_32BIT 0x7fffffffUL
Definition at line 72 of file llite_internal.h.
Referenced by ll_dir_seek(), and ll_readdir().
#define LL_HIST_MAX 28
Definition at line 390 of file llite_internal.h.
#define LL_HIST_START 12
Definition at line 391 of file llite_internal.h.
#define LL_IT2STR (it) ((it) ? ldlm_it2str((it)->it_op) : "0")
Definition at line 77 of file llite_internal.h.
Referenced by ll_create_it(), ll_lookup_it(), lmv_enqueue(), and lmv_intent_lock().
#define LL_MAX_BLKSIZE_BITS 22
Definition at line 75 of file llite_internal.h.
Referenced by ll_update_inode().
#define LL_OFFSET_HIST_MAX 100
Definition at line 404 of file llite_internal.h.
#define LL_PROCESS_HIST_MAX 10
Definition at line 392 of file llite_internal.h.
Referenced by ll_init_sbi().
#define ll_s2sbi (sb) (s2lsi(sb)->lsi_llsbi)
Definition at line 1067 of file llite_internal.h.
Referenced by cl_sb_fini(), cl_sb_init(), client_common_fill_super(), client_common_put_super(), ll_alloc_inode(), ll_dir_get_parent_fid(), ll_free_sbi(), ll_i2sbi(), ll_iget_anon_dir(), ll_ioc_copy_end(), ll_ioc_copy_start(), ll_kill_super(), ll_open_cleanup(), ll_prep_inode(), ll_put_super(), ll_remount_fs(), ll_s2dtexp(), ll_s2mdexp(), ll_show_options(), ll_statfs(), ll_statfs_internal(), ll_umount_begin(), and search_inode_for_lustre().
#define LL_SA_CACHE_BIT 5
Definition at line 1179 of file llite_internal.h.
#define LL_SA_CACHE_MASK (LL_SA_CACHE_SIZE - 1)
Definition at line 1181 of file llite_internal.h.
Referenced by sa_hash().
#define LL_SA_CACHE_SIZE (1 << LL_SA_CACHE_BIT)
Definition at line 1180 of file llite_internal.h.
Referenced by ll_sai_alloc().
#define LL_SA_RPC_DEF 32
Definition at line 1176 of file llite_internal.h.
Referenced by ll_init_sbi().
#define LL_SA_RPC_MAX 8192
Definition at line 1177 of file llite_internal.h.
#define LL_SA_RPC_MIN 2
Definition at line 1175 of file llite_internal.h.
Referenced by ll_sai_alloc().
#define LL_SBI_32BIT_API 0x2000
Definition at line 438 of file llite_internal.h.
Referenced by client_common_fill_super(), ll_iget_anon_dir(), ll_need_32bit_api(), ll_options(), ll_prep_inode(), and ll_update_inode().
#define LL_SBI_64BIT_HASH 0x4000
Definition at line 439 of file llite_internal.h.
Referenced by client_common_fill_super(), ll_dir_read(), ll_dir_seek(), ll_prep_md_op_data(), and ll_readdir().
#define LL_SBI_ACL 0x10
Definition at line 430 of file llite_internal.h.
Referenced by client_common_fill_super(), and xattr_type_filter().
#define LL_SBI_AGL_ENABLED 0x8000
Definition at line 440 of file llite_internal.h.
Referenced by ll_init_sbi(), and ll_statahead_thread().
#define LL_SBI_ALWAYS_PING 0x200000
Definition at line 446 of file llite_internal.h.
Referenced by client_common_fill_super(), ll_options(), and ll_show_options().
#define LL_SBI_CHECKSUM 0x02
Definition at line 427 of file llite_internal.h.
Referenced by client_common_fill_super(), ll_init_sbi(), and ll_options().
#define LL_SBI_FLAGS
Value:
{       \
        "nolck",        \
        "checksum",     \
        "flock",        \
        "user_xattr",   \
        "acl",          \
        "???",          \
        "rmt_client",   \
        "mds_capa",     \
        "oss_capa",     \
        "flock",        \
        "lru_resize",   \
        "lazy_statfs",  \
        "som",          \
        "32bit_api",    \
        "64bit_hash",   \
        "agl",          \
        "verbose",      \
        "layout",       \
        "user_fid2path",\
        "xattr_cache",  \
        "norootsquash", \
        "always_ping",  \
}
Definition at line 449 of file llite_internal.h.
#define LL_SBI_FLOCK 0x04
Definition at line 428 of file llite_internal.h.
Referenced by client_common_fill_super(), ll_options(), and ll_show_options().
#define LL_SBI_LAYOUT_LOCK 0x20000
Definition at line 442 of file llite_internal.h.
Referenced by client_common_fill_super(), and ll_layout_refresh().
#define LL_SBI_LAZYSTATFS 0x800
Definition at line 436 of file llite_internal.h.
Referenced by ll_options(), ll_show_options(), and ll_statfs_internal().
#define LL_SBI_LOCALFLOCK 0x200
Definition at line 434 of file llite_internal.h.
Referenced by client_common_fill_super(), ll_options(), and ll_show_options().
#define LL_SBI_LRU_RESIZE 0x400
Definition at line 435 of file llite_internal.h.
Referenced by client_common_fill_super(), ll_init_sbi(), and ll_options().
#define LL_SBI_MDS_CAPA 0x80
Definition at line 432 of file llite_internal.h.
#define LL_SBI_NOLCK 0x01
Definition at line 426 of file llite_internal.h.
Referenced by ll_file_nolock(), ll_options(), and ll_show_options().
#define LL_SBI_NOROOTSQUASH 0x100000
Definition at line 445 of file llite_internal.h.
Referenced by ll_compute_rootsquash_state(), and ll_inode_permission().
#define LL_SBI_OSS_CAPA 0x100
Definition at line 433 of file llite_internal.h.
#define LL_SBI_RMT_CLIENT 0x40
Definition at line 431 of file llite_internal.h.
Referenced by client_common_fill_super(), client_common_put_super(), ll_clear_inode(), ll_dir_ioctl(), ll_file_release(), ll_getxattr_common(), ll_inode_permission(), ll_options(), ll_setxattr_common(), ll_update_inode(), ll_update_remote_perm(), and quotactl_ioctl().
#define LL_SBI_USER_FID2PATH 0x40000
Definition at line 443 of file llite_internal.h.
Referenced by ll_fid2path(), ll_getparent(), ll_options(), and ll_show_options().
#define LL_SBI_USER_XATTR 0x08
Definition at line 429 of file llite_internal.h.
Referenced by client_common_fill_super(), ll_getxattr_common(), ll_options(), ll_setxattr_common(), ll_show_options(), and xattr_type_filter().
#define LL_SBI_VERBOSE 0x10000
Definition at line 441 of file llite_internal.h.
Referenced by ll_fill_super(), ll_init_sbi(), ll_options(), ll_put_super(), and ll_remount_fs().
#define LL_SBI_XATTR_CACHE 0x80000
Definition at line 444 of file llite_internal.h.
Referenced by client_common_fill_super().
#define LLI_INODE_DEAD 0xdeadd00d
Definition at line 90 of file llite_internal.h.
Referenced by ll_clear_inode().
#define LLI_INODE_MAGIC 0x111d0de5
Definition at line 89 of file llite_internal.h.
Referenced by ll_inode_from_resource_lock(), and ll_lli_init().
#define LLIOC_MAX_CMD 256
Definition at line 1310 of file llite_internal.h.
Referenced by ll_iocontrol_register().
#define LOOKUP_CONTINUE LOOKUP_PARENT
Definition at line 67 of file llite_internal.h.
Referenced by ll_lookup_nd(), and ll_revalidate_dentry().
#define LUSTRE_FPRIVATE (file) ((file)->private_data)
Definition at line 78 of file llite_internal.h.
Referenced by cl_setattr_ost(), ll_cl_add(), ll_cl_find(), ll_cl_remove(), ll_dir_ioctl(), ll_dir_seek(), ll_fault_io_init(), ll_file_io_generic(), ll_file_ioctl(), ll_file_nolock(), ll_file_open(), ll_file_release(), ll_flush(), ll_fsync(), ll_get_grouplock(), ll_lease_open(), ll_local_open(), ll_md_close(), ll_put_grouplock(), ll_ras_enter(), and ll_readdir().
#define RCE_HASHES 32
Definition at line 474 of file llite_internal.h.
#define REMOTE_PERM_HASHSIZE 16
Definition at line 93 of file llite_internal.h.
Referenced by alloc_rmtperm_hash(), free_rmtperm_hash(), lustre_init(), and remote_perm_hashfunc().
#define SBI_DEFAULT_READAHEAD_MAX (64UL << (20 - PAGE_CACHE_SHIFT))
Definition at line 338 of file llite_internal.h.
Referenced by ll_init_sbi().
#define SBI_DEFAULT_READAHEAD_WHOLE_MAX (2UL << (20 - PAGE_CACHE_SHIFT))
Definition at line 341 of file llite_internal.h.
Referenced by ll_init_sbi().
#define VM_FAULT_RETRY 0
Definition at line 61 of file llite_internal.h.
Referenced by ll_fault0(), ll_page_mkwrite(), and vvp_io_kernel_fault().
Enumeration Type Documentation
anonymous enum
Enumerator:
LPROC_LL_DIRTY_HITS
LPROC_LL_DIRTY_MISSES
LPROC_LL_READ_BYTES
LPROC_LL_WRITE_BYTES
LPROC_LL_BRW_READ
LPROC_LL_BRW_WRITE
LPROC_LL_IOCTL
LPROC_LL_OPEN
LPROC_LL_RELEASE
LPROC_LL_MAP
LPROC_LL_LLSEEK
LPROC_LL_FSYNC
LPROC_LL_READDIR
LPROC_LL_SETATTR
LPROC_LL_TRUNC
LPROC_LL_FLOCK
LPROC_LL_GETATTR
LPROC_LL_CREATE
LPROC_LL_LINK
LPROC_LL_UNLINK
LPROC_LL_SYMLINK
LPROC_LL_MKDIR
LPROC_LL_RMDIR
LPROC_LL_MKNOD
LPROC_LL_RENAME
LPROC_LL_STAFS
LPROC_LL_ALLOC_INODE
LPROC_LL_SETXATTR
LPROC_LL_GETXATTR
LPROC_LL_GETXATTR_HITS
LPROC_LL_LISTXATTR
LPROC_LL_REMOVEXATTR
LPROC_LL_INODE_PERM
LPROC_LL_FILE_OPCODES
Definition at line 740 of file llite_internal.h.
anonymous enum
Enumerator:
LUSTRE_OPC_MKDIR
LUSTRE_OPC_SYMLINK
LUSTRE_OPC_MKNOD
LUSTRE_OPC_CREATE
LUSTRE_OPC_ANY
Definition at line 935 of file llite_internal.h.
enum ll_file_flags
Enumerator:
LLIF_DATA_MODIFIED
LLIF_FILE_RESTORING
LLIF_XATTR_CACHE
Definition at line 275 of file llite_internal.h.
enum llioc_iter
Enumerator:
LLIOC_CONT
LLIOC_STOP
Definition at line 1305 of file llite_internal.h.
enum ra_stat
Enumerator:
RA_STAT_HIT
RA_STAT_MISS
RA_STAT_DISTANT_READPAGE
RA_STAT_MISS_IN_WINDOW
RA_STAT_FAILED_GRAB_PAGE
RA_STAT_FAILED_MATCH
RA_STAT_DISCARDED
RA_STAT_ZERO_LEN
RA_STAT_ZERO_WINDOW
RA_STAT_EOF
RA_STAT_MAX_IN_FLIGHT
RA_STAT_WRONG_GRAB_PAGE
RA_STAT_FAILED_REACH_END
_NR_RA_STAT
Definition at line 343 of file llite_internal.h.
enum ras_update_flags
Enumerator:
LL_RAS_HIT
LL_RAS_MMAP
Definition at line 1147 of file llite_internal.h.
enum stats_track_type
Enumerator:
STATS_TRACK_ALL
STATS_TRACK_PID
STATS_TRACK_PPID
STATS_TRACK_GID
STATS_TRACK_LAST
Definition at line 417 of file llite_internal.h.
Function Documentation
static void __d_lustre_invalidate (struct dentry * dentry) [inline, static]
Definition at line 1441 of file llite_internal.h.
References ll_d2d, and ll_dentry_data::lld_invalid.
Referenced by d_lustre_invalidate(), and ll_d_init().
static int cl_agl (struct inode * inode) [inline, static]
Definition at line 1242 of file llite_internal.h.
References cl_glimpse_size0().
Referenced by ll_agl_trigger().
u32 cl_fid_build_gen (const struct lu_fid * fid)
build inode generation from passed .
If our FID overflows the 32-bit inode number then return a non-zero generation to distinguish them.
Definition at line 280 of file lcommon_cl.c.
References ENTRY, fid_flatten(), fid_is_igif(), lu_igif_gen(), and RETURN.
Referenced by ll_update_inode().
u64 cl_fid_build_ino (const struct lu_fid * fid, int api32)
build inode number from passed
Definition at line 269 of file lcommon_cl.c.
References fid_flatten(), fid_flatten32(), and RETURN.
Referenced by client_common_fill_super(), ll_dir_read(), ll_getattr(), ll_iget_anon_dir(), ll_md_blocking_ast(), ll_prep_inode(), ll_update_inode(), and search_inode_for_lustre().
int cl_file_inode_init (struct inode * inode, struct lustre_md * md)
Initialize or update CLIO structures for regular files when new meta-data arrives from the server.
Parameters:
inode regular file inode
md new file metadata from MDS
allocates cl_object if necessary,
updated layout, if object was already here.
Definition at line 131 of file lcommon_cl.c.
References lustre_md::body, CERROR, cl_conf_set(), cl_env_get(), cl_env_put(), cl_object_find(), cl_object::co_lu, cl_object_conf::coc_inode, cl_object_conf::coc_lu, DFID, fid_is_sane(), LASSERT, lustre_md::layout, ll_i2info(), ll_i2sbi(), ll_sb_info::ll_site, ll_inode_info::lli_clob, ll_inode_info::lli_fid, LOC_F_NEW, lu_object_conf::loc_flags, lu_site::ls_top_dev, lu2cl_dev(), lu_object_ref_add(), mdt_body::mbo_valid, OBD_MD_FLID, and PFID.
Referenced by ll_iget(), and ll_update_inode().
int cl_get_grouplock (struct cl_object * obj, unsigned long gid, int nonblock, struct ll_grouplock * lg)
Definition at line 124 of file lcommon_misc.c.
References CEF_MUST, CEF_NONBLOCK, cl_io::ci_ignore_layout, cl_io::ci_obj, CIT_MISC, cl_env_get(), cl_env_put(), cl_env_unplant(), cl_io_fini(), cl_io_init(), cl_lock_request(), CL_PAGE_EOF, cl_lock_descr::cld_end, cl_lock_descr::cld_enq_flags, cl_lock_descr::cld_gid, cl_lock_descr::cld_mode, cl_lock_descr::cld_obj, cl_lock_descr::cld_start, cl_lock::cll_descr, CLM_GROUP, LASSERT, ll_grouplock::lg_env, ll_grouplock::lg_gid, ll_grouplock::lg_io, ll_grouplock::lg_lock, vvp_env_lock(), and vvp_env_thread_io().
Referenced by ll_get_grouplock().
int cl_glimpse_lock (const struct lu_env * env, struct cl_io * io, struct inode * inode, struct cl_object * clob, int agl)
Definition at line 85 of file glimpse.c.
References CDEBUG, CEF_AGL, CEF_ASYNC, CEF_MUST, cl_lock_release(), cl_lock_request(), cl_lock_descr::cld_enq_flags, cl_lock_descr::cld_mode, cl_lock_descr::cld_obj, cl_lock::cll_descr, CLM_READ, cl_object::co_lu, D_DLMTRACE, DFID, dirty_cnt(), ENTRY, ll_merge_attr(), lu_object_fid(), PFID, RETURN, and vvp_env_lock().
Referenced by cl_glimpse_size0(), and vvp_prep_size().
static int cl_glimpse_size (struct inode * inode) [inline, static]
Definition at line 1237 of file llite_internal.h.
References cl_glimpse_size0().
Referenced by ll_glimpse_size().
int cl_glimpse_size0 (struct inode * inode, int agl)
Definition at line 171 of file glimpse.c.
References cl_io::ci_need_restart, cl_io::ci_obj, cl_io::ci_result, cl_io::ci_verify_layout, CIT_MISC, cl_env_put(), cl_glimpse_lock(), cl_io_fini(), cl_io_get(), cl_io_init(), ENTRY, OBD_FAIL_GLIMPSE_DELAY, OBD_FAIL_TIMEOUT, RETURN, and unlikely.
Referenced by cl_agl(), and cl_glimpse_size().
void cl_inode_fini (struct inode * inode)
Definition at line 226 of file lcommon_cl.c.
References cl_env_get(), cl_env_implant(), cl_env_put(), cl_env_reenter(), cl_env_reexit(), cl_env_unplant(), cl_object_kill(), cl_object_put_last(), cl_object::co_lu, LASSERT, ll_i2info(), ll_inode_info::lli_clob, and lu_object_ref_del().
Referenced by ll_clear_inode().
int cl_ocd_update (struct obd_device * host, struct obd_device * watched, enum obd_notify_event ev, void * owner, void * data)
This function is used as an upcall-callback hooked by liblustre and llite clients into obd_notify() listeners chain to handle notifications about change of import connect_flags.
See llu_fsswop_mount() and lustre_common_fill_super().
Definition at line 86 of file lcommon_misc.c.
References __u64, CDEBUG, CERROR, client_obd::cl_import, cl_init_ea_size(), obd_device::cli, D_SUPER, ENTRY, obd_import::imp_connect_data, lustre_client_ocd::lco_dt_exp, lustre_client_ocd::lco_flags, lustre_client_ocd::lco_lock, lustre_client_ocd::lco_md_exp, LPX64, LUSTRE_OSC_NAME, obd_device::obd_name, obd_device::obd_set_up, obd_device::obd_stopping, obd_device::obd_type, obd_connect_data::ocd_connect_flags, RETURN, obd_type::typ_name, and obd_device::u.
Referenced by client_common_fill_super().
void cl_put_grouplock (struct ll_grouplock * lg)
Definition at line 181 of file lcommon_misc.c.
References cl_env_implant(), cl_env_put(), cl_io_fini(), cl_lock_release(), LASSERT, ll_grouplock::lg_env, ll_grouplock::lg_gid, ll_grouplock::lg_io, and ll_grouplock::lg_lock.
Referenced by ll_get_grouplock(), and ll_put_grouplock().
int cl_sb_fini (struct super_block * sb)
Definition at line 337 of file vvp_dev.c.
References CERROR, cl_env_get(), cl_env_put(), cl_stack_fini(), ENTRY, ll_sb_info::ll_cl, ll_s2sbi, ll_sb_info::ll_site, and RETURN.
Referenced by client_common_put_super().
int cl_sb_init (struct super_block * sb)
Common IO arguments for various VFS I/O interfaces.
Definition at line 314 of file vvp_dev.c.
References cl2lu_dev(), cl_env_get(), cl_env_put(), cl_type_setup(), obd_export::exp_obd, lu_device::ld_site, ll_sb_info::ll_cl, ll_sb_info::ll_dt_exp, ll_s2sbi, ll_sb_info::ll_site, obd_device::obd_lu_dev, RETURN, and vvp_device_type.
Referenced by client_common_fill_super().
int cl_setattr_ost (struct cl_object * obj, const struct iattr * attr, unsigned int attr_flags)
Definition at line 75 of file lcommon_cl.c.
References cl_io::ci_need_restart, cl_io::ci_obj, cl_io::ci_result, cl_io::ci_setattr, cl_io::ci_verify_layout, CIT_SETATTR, cl_env_get(), cl_env_put(), cl_io_fini(), cl_io_init(), cl_io_loop(), cl_object::co_lu, ENTRY, LTIME_S, lu_object_fid(), LUSTRE_FPRIVATE, RETURN, cl_io::u, unlikely, vvp_io::vui_fd, vvp_env_io(), and vvp_env_thread_io().
Referenced by ll_iocontrol(), and ll_setattr_raw().
int cl_sync_file_range (struct inode * inode, loff_t start, loff_t end, enum cl_fsync_mode mode, int ignore_layout)
Called to make sure a portion of file has been written out.
if is not CL_FSYNC_LOCAL, it will send OST_SYNC RPCs to OST.
Return how many pages have been written.
Definition at line 2787 of file file.c.
References cl_io::ci_fsync, cl_io::ci_ignore_layout, cl_io::ci_obj, cl_io::ci_result, CIT_FSYNC, cl_env_nested_get(), cl_env_nested_put(), CL_FSYNC_ALL, CL_FSYNC_DISCARD, CL_FSYNC_LOCAL, CL_FSYNC_NONE, cl_io_fini(), cl_io_init(), cl_io_loop(), ENTRY, ll_i2info(), ll_inode2fid(), ll_inode_info::lli_clob, RETURN, cl_io::u, and vvp_env_thread_io().
Referenced by ll_delete_inode(), ll_fsync(), ll_writepage(), ll_writepages(), and vvp_prune().
static int d_lustre_invalid (const struct dentry * dentry) [inline, static]
Definition at line 1434 of file llite_internal.h.
References ll_d2d, and ll_dentry_data::lld_invalid.
Referenced by ll_dcompare(), ll_ddelete(), and revalidate_statahead_dentry().
static void d_lustre_invalidate (struct dentry * dentry, int nested) [inline, static]
Definition at line 1454 of file llite_internal.h.
References __d_lustre_invalidate(), CDEBUG, D_DENTRY, and ll_d_count.
Referenced by __ll_inode_revalidate(), ll_invalidate_aliases(), and ll_invalidate_negative_children().
static void d_lustre_revalidate (struct dentry * dentry) [inline, static]
Definition at line 1476 of file llite_internal.h.
References LASSERT, and ll_d2d.
Referenced by ll_lookup_it_finish(), and revalidate_statahead_dentry().
static bool dentry_may_statahead (struct inode * dir, struct dentry * dentry) [inline, static]
Definition at line 1262 of file llite_internal.h.
References current_pid, ll_d2d, ll_i2info(), ll_i2sbi(), ll_dentry_data::lld_sa_generation, ll_inode_info::lli_opendir_pid, ll_inode_info::lli_sa_enabled, and ll_inode_info::lli_sa_generation.
Referenced by ll_lookup_it(), and ll_revalidate_dentry().
blkcnt_t dirty_cnt (struct inode * inode)
Definition at line 69 of file glimpse.c.
References cl_inode2vvp(), and vvp_object::vob_mmap_cnt.
Referenced by cl_glimpse_lock(), and vvp_object_glimpse().
void free_rmtperm_hash (struct hlist_head * hash)
Definition at line 103 of file remote_perm.c.
References cfs_hlist_for_each_entry_safe, free_ll_remote_perm(), ll_rmtperm_hash_cachep, hlist_node::next, OBD_SLAB_FREE, and REMOTE_PERM_HASHSIZE.
Referenced by ll_clear_inode(), and ll_update_remote_perm().
__u32 get_uuid2int (const char * name, int len)
Definition at line 48 of file llite_nfs.c.
Referenced by client_common_fill_super().
void ll_authorize_statahead (struct inode * dir, void * key)
Definition at line 1198 of file statahead.c.
References current_pid, LASSERT, ll_i2info(), ll_inode_info::lli_opendir_key, ll_inode_info::lli_opendir_pid, ll_inode_info::lli_sa_enabled, ll_inode_info::lli_sa_lock, and ll_inode_info::lli_sai.
Referenced by ll_file_open().
void ll_cl_add (struct file * file, const struct lu_env * env, struct cl_io * io)
Definition at line 1051 of file rw.c.
References ll_file_data::fd_lccs, ll_file_data::fd_lock, INIT_LIST_HEAD, ll_cl_context::lcc_cookie, ll_cl_context::lcc_env, ll_cl_context::lcc_io, ll_cl_context::lcc_list, list_add(), ll_env_info(), ll_thread_info::lti_io_ctx, and LUSTRE_FPRIVATE.
Referenced by ll_fault0(), and ll_file_io_generic().
struct ll_cl_context* ll_cl_find (struct file * file) [read]
Definition at line 1033 of file rw.c.
References ll_file_data::fd_lccs, ll_file_data::fd_lock, ll_cl_context::lcc_cookie, ll_cl_context::lcc_list, list_for_each_entry, and LUSTRE_FPRIVATE.
Referenced by ll_readpage(), and ll_write_begin().
void ll_cl_remove (struct file * file, const struct lu_env * env)
Definition at line 1067 of file rw.c.
References ll_file_data::fd_lock, ll_cl_context::lcc_list, list_del_init(), ll_env_info(), ll_thread_info::lti_io_ctx, and LUSTRE_FPRIVATE.
Referenced by ll_fault0(), and ll_file_io_generic().
void ll_clear_inode (struct inode * inode)
Definition at line 1433 of file llite_lib.c.
References CDEBUG, cl_inode_fini(), D_VFSTRACE, DFID, ENTRY, EXIT, FMODE_EXEC, FMODE_READ, FMODE_WRITE, free_rmtperm_hash(), LASSERT, list_empty(), ll_dir_clear_lsm_md(), ll_sb_info::ll_flags, ll_i2info(), ll_i2sbi(), ll_inode2fid(), ll_sb_info::ll_md_exp, ll_md_real_close(), LL_SBI_RMT_CLIENT, ll_xattr_cache_destroy(), ll_inode_info::lli_agl_list, LLI_INODE_DEAD, ll_inode_info::lli_inode_magic, ll_inode_info::lli_mds_exec_och, ll_inode_info::lli_mds_read_och, ll_inode_info::lli_mds_write_och, ll_inode_info::lli_open_fd_exec_count, ll_inode_info::lli_open_fd_read_count, ll_inode_info::lli_open_fd_write_count, ll_inode_info::lli_opendir_key, ll_inode_info::lli_opendir_pid, ll_inode_info::lli_posix_acl, ll_inode_info::lli_remote_perms, ll_inode_info::lli_sai, ll_inode_info::lli_symlink_name, md_null_inode(), OBD_FREE, and PFID.
Referenced by ll_delete_inode().
void ll_compute_rootsquash_state (struct ll_sb_info * sbi)
Definition at line 2683 of file llite_lib.c.
References cfs_match_nid(), list_empty(), ll_sb_info::ll_flags, LL_SBI_NOROOTSQUASH, ll_sb_info::ll_squash, LNET_NETTYP(), LNET_NIDNET(), LNetGetId(), LOLND, root_squash_info::rsi_nosquash_nids, and root_squash_info::rsi_sem.
ssize_t ll_copy_user_md (const struct lov_user_md __user * md, struct lov_user_md ** kbuf)
Definition at line 2653 of file llite_lib.c.
References ENTRY, ll_lov_user_md_size(), lov_user_md, OBD_ALLOC, OBD_FREE, and RETURN.
Referenced by ll_lov_setstripe().
int ll_d_init (struct dentry * de)
Definition at line 169 of file dcache.c.
References __d_lustre_invalidate(), CDEBUG, D_DENTRY, ENTRY, LASSERT, likely, ll_d_count, ll_d_ops, OBD_ALLOC_PTR, OBD_FREE_PTR, and RETURN.
Referenced by ll_splice_alias().
int ll_data_version (struct inode * inode, __u64 * data_version, int flags)
Definition at line 1869 of file file.c.
References cl_io::ci_data_version, cl_io::ci_need_restart, cl_io::ci_obj, cl_io::ci_result, CIT_DATA_VERSION, cl_env_get(), cl_env_put(), cl_io_fini(), cl_io_init(), cl_io_loop(), ENTRY, ll_i2info(), ll_inode_info::lli_clob, RETURN, cl_io::u, unlikely, and vvp_env_thread_io().
Referenced by ll_file_ioctl(), ll_hsm_release(), ll_ioc_copy_end(), ll_ioc_copy_start(), ll_migrate(), and ll_swap_layouts().
void ll_deauthorize_statahead (struct inode * dir, void * key)
Definition at line 1220 of file statahead.c.
References CDEBUG, D_READA, DFID, LASSERT, ll_i2info(), ll_inode_info::lli_fid, ll_inode_info::lli_opendir_key, ll_inode_info::lli_opendir_pid, ll_inode_info::lli_sa_enabled, ll_inode_info::lli_sa_lock, ll_inode_info::lli_sai, PFID, ll_statahead_info::sai_thread, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, thread_is_running(), and thread_set_flags().
Referenced by ll_file_open(), and ll_file_release().
void ll_delete_inode (struct inode * inode)
Definition at line 2040 of file llite_lib.c.
References CL_FSYNC_LOCAL, cl_sync_file_range(), clear_inode, DFID, ENTRY, EXIT, LASSERTF, ll_clear_inode(), ll_i2info(), ll_inode2fid(), ll_inode_info::lli_clob, OBD_OBJECT_EOF, PFID, and truncate_inode_pages_final().
static void ll_dir_chain_fini (struct ll_dir_chain * chain) [inline, static]
Definition at line 785 of file llite_internal.h.
Referenced by is_first_dirent(), ll_dir_read(), and ll_statahead_thread().
static void ll_dir_chain_init (struct ll_dir_chain * chain) [inline, static]
Definition at line 781 of file llite_internal.h.
Referenced by is_first_dirent(), ll_dir_read(), and ll_statahead_thread().
void ll_dir_clear_lsm_md (struct inode * inode)
Definition at line 1205 of file llite_lib.c.
References LASSERT, ll_i2info(), ll_inode_info::lli_lsm_md, and lmv_free_memmd().
Referenced by ll_clear_inode(), and ll_iget().
int ll_dir_get_parent_fid (struct inode * dir, struct lu_fid * parent_fid)
Definition at line 287 of file llite_nfs.c.
References CDEBUG, CERROR, D_INFO, DFID, dotdot, ENTRY, LASSERT, ll_finish_md_op_data(), ll_get_default_mdsize(), ll_get_fsname(), ll_inode2fid(), ll_sb_info::ll_md_exp, ll_prep_md_op_data(), ll_s2sbi, LUSTRE_OPC_ANY, mdt_body::mbo_fid1, mdt_body::mbo_valid, md_getattr_name(), OBD_MD_FLID, md_op_data::op_data, PFID, ptlrpc_req_finished(), req_capsule_server_get(), RETURN, RMF_MDT_BODY, and ptlrpc_request::rq_pill.
Referenced by ll_get_parent(), and ll_readdir().
int ll_dir_getstripe (struct inode * inode, void ** plmm, int * plmm_size, struct ptlrpc_request ** request, u64 valid)
This function will be used to get default LOV/LMV/Default LMV will be used to indicate which stripe it will retrieve OBD_MD_MEA LMV stripe EA OBD_MD_DEFAULT_MEA Default LMV stripe EA otherwise Default LOV EA.
Each time, it can only retrieve 1 stripe EA
Definition at line 631 of file dir.c.
References CDEBUG, CERROR, cpu_to_le32, D_INFO, DFID, ENTRY, GOTO, LASSERT, le32_to_cpu, ll_finish_md_op_data(), ll_get_default_mdsize(), ll_i2sbi(), ll_inode2fid(), ll_sb_info::ll_md_exp, ll_prep_md_op_data(), LMV_MAGIC, LMV_MAGIC_V1, LMV_USER_MAGIC, lmv_user_md, LOV_MAGIC, LOV_MAGIC_V1, LOV_MAGIC_V3, lov_mds_md, LUSTRE_OPC_ANY, lustre_swab_lmv_mds_md(), lustre_swab_lmv_user_md, lustre_swab_lov_user_md_v1(), lustre_swab_lov_user_md_v3(), mdt_body::mbo_eadatasize, mdt_body::mbo_valid, md_getattr(), OBD_MD_FLDIREA, OBD_MD_FLEASIZE, md_op_data::op_valid, PFID, req_capsule_server_get(), req_capsule_server_sized_get(), RETURN, RMF_MDT_BODY, RMF_MDT_MD, and ptlrpc_request::rq_pill.
Referenced by ll_dir_ioctl(), ll_getxattr_lov(), and ll_new_node().
int ll_dir_read (struct inode * inode, __u64 * pos, struct md_op_data * op_data, void * cookie, filldir_t filldir)
Definition at line 214 of file dir.c.
References __u64, cl_fid_build_ino(), done, ENTRY, fid_le_to_cpu(), lu_dirent::lde_fid, lu_dirent::lde_hash, lu_dirent::lde_name, lu_dirent::lde_namelen, LDF_COLLIDE, lu_dirpage::ldp_flags, lu_dirpage::ldp_hash_end, le16_to_cpu, le32_to_cpu, le64_to_cpu, ll_dir_chain_fini(), ll_dir_chain_init(), ll_dirent_type_get(), ll_sb_info::ll_flags, ll_get_dir_page(), ll_i2sbi(), ll_need_32bit_api(), ll_release_page(), LL_SBI_64BIT_HASH, lu_dirent_next(), lu_dirent_start(), MDS_DIR_END_OFF, and RETURN.
Referenced by ll_get_name(), and ll_readdir().
int ll_dir_setstripe (struct inode * inode, struct lov_user_md * lump, int set_default)
Definition at line 514 of file dir.c.
References buf, CDEBUG, CERROR, client_obd::cl_mgc_mgsexp, obd_device::cli, cpu_to_le32, D_IOCTL, end, ENTRY, GOTO, le16_to_cpu, le32_to_cpu, ll_finish_md_op_data(), ll_get_fsname(), ll_i2sbi(), ll_sb_info::ll_md_exp, ll_prep_md_op_data(), ll_send_mgc_param(), LMV_USER_MAGIC, lmv_user_md, LOV_USER_MAGIC_V1, LOV_USER_MAGIC_V3, LUSTRE_OPC_ANY, lustre_swab_lmv_user_md, lustre_swab_lov_user_md_v1(), lustre_swab_lov_user_md_v3(), md_setattr(), MGS_PARAM_MAXLEN, MTI_NAME_MAXLEN, OBD_ALLOC, OBD_FREE, ptlrpc_req_finished(), RETURN, and obd_device::u.
Referenced by ll_dir_ioctl(), and ll_setxattr().
ssize_t ll_direct_rw_pages (const struct lu_env * env, struct cl_io * io, int rw, struct inode * inode, struct ll_dio_pages * pv)
Definition at line 189 of file rw26.c.
References cl_io::ci_obj, cl_io::ci_queue, cl_2queue_add(), cl_2queue_discard(), cl_2queue_disown(), cl_2queue_fini(), cl_2queue_init(), cl_index(), cl_io_submit_sync(), cl_page_clip(), cl_page_disown(), cl_page_find(), cl_page_own(), cl_page_put(), cl_page_size(), cl_page_vmpage(), cl_page::cp_state, cl_page::cp_type, CPS_FREEING, CPT_CACHEABLE, CPT_TRANSIENT, CRT_READ, CRT_WRITE, ENTRY, LASSERT, ll_dio_pages::ldp_nr, ll_dio_pages::ldp_offsets, ll_dio_pages::ldp_pages, ll_dio_pages::ldp_size, ll_dio_pages::ldp_start_offset, likely, ll_kmap_atomic, ll_kunmap_atomic, page_size, READ, RETURN, size, and WRITE.
Referenced by do_bio_lustrebacked(), and ll_direct_IO_seg().
void ll_dirty_page_discard_warn (struct page * page, int ioret)
Definition at line 2625 of file llite_lib.c.
References buf, CDEBUG, D_WARNING, DFID, ll_d_path(), ll_get_fsname(), ll_inode2fid(), path, and PFID.
Referenced by vvp_vmpage_error().
static struct vvp_io_args* ll_env_args (const struct lu_env * env, enum vvp_io_subtype type) [static, read]
Definition at line 1031 of file llite_internal.h.
References ll_env_info(), ll_thread_info::lti_args, and vvp_io_args::via_io_subtype.
Referenced by ll_file_read_iter(), ll_file_splice_read(), and ll_file_write_iter().
static struct ll_thread_info* ll_env_info (const struct lu_env * env) [static, read]
Definition at line 1021 of file llite_internal.h.
References LASSERT, lu_env::le_ctx, ll_thread_key, and lu_context_key_get().
Referenced by ll_cl_add(), ll_cl_remove(), ll_env_args(), ll_file_aio_read(), ll_file_aio_write(), ll_file_read(), ll_file_write(), and ll_readahead().
int ll_fid2path (struct inode * inode, void __user * arg)
Definition at line 1811 of file file.c.
References CFS_CAP_DAC_READ_SEARCH, cfs_capable(), ENTRY, getinfo_fid2path::gf_pathlen, getinfo_fid2path::gf_root_fid, getinfo_fid2path::gf_u, GOTO, ll_i2mdexp(), ll_i2sbi(), ll_inode2fid(), LL_SBI_USER_FID2PATH, OBD_ALLOC, OBD_FREE, OBD_IOC_FID2PATH, obd_iocontrol(), and RETURN.
Referenced by ll_dir_ioctl(), and ll_file_ioctl().
static void ll_file_clear_flag (struct ll_inode_info * lli, enum ll_file_flags flag) [inline, static]
Definition at line 290 of file llite_internal.h.
References ll_inode_info::lli_flags.
Referenced by ll_setattr_raw(), ll_update_inode(), ll_xattr_cache_destroy_locked(), and vvp_io_fini().
static loff_t ll_file_maxbytes (struct inode * inode) [inline, static]
Definition at line 1115 of file llite_internal.h.
References cl_object_maxbytes(), ll_i2info(), ll_inode_info::lli_clob, and min_t.
Referenced by ll_file_seek(), ll_setattr_raw(), and vvp_io_write_start().
int ll_file_mmap (struct file * file, struct vm_area_struct * vma)
Definition at line 485 of file llite_mmap.c.
References ENTRY, ll_file_nolock(), ll_file_vm_ops, ll_glimpse_size(), ll_i2sbi(), ll_stats_ops_tally(), LPROC_LL_MAP, and RETURN.
static int ll_file_nolock (const struct file * file) [inline, static]
Definition at line 1369 of file llite_internal.h.
References ll_file_data::fd_flags, LASSERT, LL_FILE_IGNORE_LOCK, ll_i2sbi(), LL_SBI_NOLCK, and LUSTRE_FPRIVATE.
Referenced by ll_fault_io_init(), ll_file_mmap(), ll_get_grouplock(), ll_io_init(), and vvp_mmap_locks().
int ll_file_open (struct inode * inode, struct file * file)
Definition at line 491 of file file.c.
References __u64, CDEBUG, cl_lov_delay_create_clear(), D_VFSTRACE, DFID, DISP_ENQ_OPEN_REF, DISP_OPEN_OPEN, ENTRY, ll_file_data::fd_file, FMODE_EXEC, FMODE_READ, FMODE_WRITE, GOTO, it_clear_disposition(), IT_CREAT, it_disposition(), lookup_intent::it_disposition, lookup_intent::it_flags, lookup_intent::it_op, IT_OPEN, it_open_error(), lookup_intent::it_request, lookup_intent::it_status, LASSERT, LASSERTF, ll_authorize_statahead(), ll_deauthorize_statahead(), ll_file_data_get(), ll_file_data_put(), ll_i2info(), ll_i2sbi(), ll_inode2fid(), ll_intent_file_open(), ll_local_open(), ll_release_openhandle(), ll_stats_ops_tally(), ll_inode_info::lli_mds_exec_och, ll_inode_info::lli_mds_read_och, ll_inode_info::lli_mds_write_och, ll_inode_info::lli_och_mutex, ll_inode_info::lli_open_fd_exec_count, ll_inode_info::lli_open_fd_read_count, ll_inode_info::lli_open_fd_write_count, ll_inode_info::lli_opendir_key, LPROC_LL_OPEN, LUSTRE_FPRIVATE, MDS_OPEN_BY_FID, MDS_OPEN_LOCK, MDS_OPEN_OWNEROVERRIDE, OBD_ALLOC, OBD_FREE, PFID, ptlrpc_req_finished(), and RETURN.
Referenced by ll_dir_open().
int ll_file_release (struct inode * inode, struct file * file)
Definition at line 314 of file file.c.
References CDEBUG, CFS_FAIL_TIMEOUT_MS, cfs_fail_val, current_pid, D_VFSTRACE, DFID, ENTRY, ll_file_data::fd_flags, LASSERT, libcfs_debug_dumplog(), ll_deauthorize_statahead(), ll_sb_info::ll_et, ll_file_data_put(), LL_FILE_RMTACL, ll_sb_info::ll_flags, ll_i2info(), ll_i2sbi(), ll_inode2fid(), ll_md_close(), ll_sb_info::ll_rct, LL_SBI_RMT_CLIENT, ll_stats_ops_tally(), ll_inode_info::lli_async_rc, ll_inode_info::lli_clob, ll_inode_info::lli_opendir_key, lov_read_and_clear_async_rc(), LPROC_LL_RELEASE, LUSTRE_FPRIVATE, OBD_FAIL_PTLRPC_DUMP_LOG, PFID, RETURN, and unlikely.
Referenced by ll_dir_release().
static void ll_file_set_flag (struct ll_inode_info * lli, enum ll_file_flags flag) [inline, static]
Definition at line 284 of file llite_internal.h.
References ll_inode_info::lli_flags.
Referenced by ll_page_mkwrite0(), ll_update_inode(), ll_xattr_cache_init(), vvp_io_setattr_fini(), and vvp_io_write_start().
static bool ll_file_test_and_clear_flag (struct ll_inode_info * lli, enum ll_file_flags flag) [inline, static]
Definition at line 302 of file llite_internal.h.
References ll_inode_info::lli_flags.
Referenced by ll_prepare_close(), and ll_setattr_raw().
static bool ll_file_test_flag (struct ll_inode_info * lli, enum ll_file_flags flag) [inline, static]
Definition at line 296 of file llite_internal.h.
References ll_inode_info::lli_flags.
Referenced by ll_inode_revalidate(), and ll_xattr_cache_valid().
int ll_fill_super (struct super_block * sb, struct vfsmount * mnt)
Definition at line 992 of file llite_lib.c.
References CDEBUG, config_llog_instance::cfg_callback, config_llog_instance::cfg_instance, config_llog_instance::cfg_uuid, class_config_llog_handler(), class_get_profile(), class_put_profile(), client_common_fill_super(), D_CONFIG, D_VFSTRACE, ENTRY, GOTO, LCONSOLE_ERROR_MSG, LCONSOLE_WARN, ll_bdi_register(), ll_sb_info::ll_client_common_fill_super_succeeded, ll_d_ops, ll_sb_info::ll_flags, ll_init_sbi(), ll_options(), ll_put_super(), LL_SBI_VERBOSE, lustre_profile::lp_dt, lustre_profile::lp_md, lustre_process_log(), OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, and RETURN.
Referenced by lustre_init().
void ll_finish_md_op_data (struct md_op_data * op_data)
Definition at line 2507 of file llite_lib.c.
References OBD_FREE_PTR.
Referenced by __ll_inode_revalidate(), get_hsm_state(), is_first_dirent(), ll_close_inode_openhandle(), ll_dir_get_parent_fid(), ll_dir_getstripe(), ll_dir_setdirstripe(), ll_dir_setstripe(), ll_file_flock(), ll_file_ioctl(), ll_get_fid_by_name(), ll_get_name(), ll_hsm_state_set(), ll_intent_file_open(), ll_iocontrol(), ll_layout_refresh_locked(), ll_lease_open(), ll_link(), ll_lookup_it(), ll_lov_getstripe_ea_info(), ll_migrate(), ll_new_node(), ll_open_cleanup(), ll_readdir(), ll_readlink_internal(), ll_rename(), ll_rmdir(), ll_rmdir_entry(), ll_setattr_raw(), ll_statahead_thread(), ll_swap_layouts(), ll_unlink(), and ll_xattr_find_get_lock().
int ll_flush_ctx (struct inode * inode)
Definition at line 2145 of file llite_lib.c.
References CDEBUG, D_SEC, from_kuid(), KEY_FLUSH_CTX, ll_sb_info::ll_dt_exp, ll_i2sbi(), ll_sb_info::ll_md_exp, and obd_set_info_async().
Referenced by ll_dir_ioctl(), and ll_file_ioctl().
int ll_fsync (struct file * file, struct dentry * dentry, int data)
Definition at line 2846 of file file.c.
References CDEBUG, CL_FSYNC_ALL, cl_sync_file_range(), D_VFSTRACE, DFID, ENTRY, ll_file_data::fd_write_failed, ll_i2info(), ll_i2sbi(), ll_inode2fid(), ll_stats_ops_tally(), ll_inode_info::lli_async_rc, ll_inode_info::lli_clob, lov_read_and_clear_async_rc(), LPROC_LL_FSYNC, LUSTRE_FPRIVATE, md_fsync(), PFID, ptlrpc_req_finished(), and RETURN.
struct posix_acl* ll_get_acl (struct inode * inode, int type) [read]
Definition at line 3549 of file file.c.
References ENTRY, ll_i2info(), ll_inode_info::lli_lock, ll_inode_info::lli_posix_acl, and RETURN.
Referenced by ll_check_acl().
int ll_get_default_mdsize (struct ll_sb_info * sbi, int * lmmsize)
Get the value of the default_easize parameter.
See also:
client_obd::cl_default_mds_easize
Parameters:
[in] sbi superblock info for this filesystem
[out] lmmsize pointer to storage location for value
Return values:
0 on success
negative negated errno on failure
Definition at line 649 of file llite_lib.c.
References CERROR, KEY_DEFAULT_EASIZE, ll_sb_info::ll_md_exp, obd_get_info(), RETURN, and size.
Referenced by __ll_inode_revalidate(), ll_dir_get_parent_fid(), ll_dir_getstripe(), ll_layout_fetch(), ll_lov_getstripe_ea_info(), and search_inode_for_lustre().
struct page* ll_get_dir_page (struct inode * dir, struct md_op_data * op_data, __u64 offset, struct ll_dir_chain * chain) [read]
Definition at line 149 of file dir.c.
References ll_i2mdexp(), ll_md_blocking_ast(), md_callback::md_blocking_ast, and md_read_page().
Referenced by is_first_dirent(), ll_dir_read(), and ll_statahead_thread().
int ll_get_fid_by_name (struct inode * parent, const char * name, int namelen, struct lu_fid * fid, struct inode ** inode)
Definition at line 3049 of file file.c.
References ENTRY, GOTO, ll_finish_md_op_data(), ll_i2sbi(), ll_prep_inode(), ll_prep_md_op_data(), LUSTRE_OPC_ANY, mdt_body::mbo_fid1, md_getattr_name(), OBD_MD_FLID, OBD_MD_FLTYPE, md_op_data::op_data, md_op_data::op_valid, ptlrpc_req_finished(), req_capsule_server_get(), RETURN, RMF_MDT_BODY, and ptlrpc_request::rq_pill.
Referenced by ll_dir_ioctl(), and ll_migrate().
char* ll_get_fsname (struct super_block * sb, char * buf, int buflen)
Get lustre file system name by sbi.
If buf is provided(non-NULL), the fsname will be returned in this buffer; otherwise, a static buffer will be used to store the fsname and returned to caller.
Definition at line 2583 of file llite_lib.c.
References MTI_NAME_MAXLEN, and unlikely.
Referenced by client_common_fill_super(), is_first_dirent(), ll_close_inode_openhandle(), ll_dir_get_parent_fid(), ll_dir_ioctl(), ll_dir_setstripe(), ll_dirty_page_discard_warn(), ll_dump_inode(), ll_encode_fh(), ll_getxattr_common(), ll_hsm_release(), ll_iget_anon_dir(), ll_inode_revalidate_fini(), ll_invalidate_aliases(), ll_layout_lock_set(), ll_layout_refresh_locked(), ll_lease_open(), ll_migrate(), ll_open_cleanup(), ll_readlink_internal(), ll_setattr_raw(), ll_swap_layouts_close(), ll_update_lsm_md(), revalidate_statahead_dentry(), sa_instantiate(), vvp_io_init(), and vvp_io_write_start().
int ll_get_max_mdsize (struct ll_sb_info * sbi, int * max_mdsize)
Definition at line 616 of file llite_lib.c.
References CERROR, obd_export::exp_obd, KEY_MAX_EASIZE, ll_sb_info::ll_dt_exp, ll_sb_info::ll_md_exp, obd_get_info(), obd_device::obd_name, RETURN, and size.
int ll_get_mdt_idx (struct inode * inode)
Definition at line 734 of file dir.c.
References ll_get_mdt_idx_by_fid(), ll_i2sbi(), and ll_inode2fid().
Referenced by ll_dir_ioctl(), and ll_file_ioctl().
int ll_get_mdt_idx_by_fid (struct ll_sb_info * sbi, const struct lu_fid * fid)
Definition at line 709 of file dir.c.
References ENTRY, ll_sb_info::ll_md_exp, md_getattr(), MF_GET_MDT_IDX, OBD_ALLOC_PTR, OBD_FREE_PTR, md_op_data::op_fid1, md_op_data::op_flags, md_op_data::op_mds, and RETURN.
Referenced by ll_dir_ioctl(), ll_get_mdt_idx(), and ll_migrate().
int ll_get_obd_name (struct inode * inode, unsigned int cmd, unsigned long arg)
Get obd name by cmd, and copy out to user space.
Definition at line 2555 of file llite_lib.c.
References __user, class_exp2obd(), ENTRY, ll_sb_info::ll_dt_exp, ll_i2sbi(), ll_sb_info::ll_md_exp, OBD_IOC_GETDTNAME, OBD_IOC_GETMDNAME, obd_device::obd_name, and RETURN.
Referenced by ll_dir_ioctl(), and ll_file_ioctl().
int ll_getattr (struct vfsmount * mnt, struct dentry * de, struct kstat * stat)
Definition at line 3474 of file file.c.
References cl_fid_build_ino(), ll_i2info(), ll_i2sbi(), ll_inode_revalidate(), ll_need_32bit_api(), ll_stats_ops_tally(), ll_inode_info::lli_fid, LPROC_LL_GETATTR, MDS_INODELOCK_LOOKUP, MDS_INODELOCK_UPDATE, OBD_FAIL_GETATTR_DELAY, and OBD_FAIL_TIMEOUT.
int ll_getparent (struct file * file, struct getparent __user * arg)
Get parent FID and name of an identified link.
Operation is performed for a given link number, letting the caller iterate over linkno to list one or all links of an entry.
Parameters:
[in] file - File descriptor against which to perform the operation
[in,out] arg - User-filled structure containing the linkno to operate on and the available size. It is eventually filled with the requested information or left untouched on error
Return values:
- 0 on success
- Appropriate negative error code on failure
Definition at line 2770 of file llite_lib.c.
References CFS_CAP_DAC_READ_SEARCH, cfs_capable(), ENTRY, GOTO, lu_buf::lb_buf, lu_buf::lb_len, linkea_data_new(), ll_getxattr(), ll_i2sbi(), ll_linkea_decode(), LL_SBI_USER_FID2PATH, lu_name::ln_name, lu_name::ln_namelen, lu_buf_free(), LU_BUF_NULL, OBD_ALLOC, OBD_FREE, RETURN, and XATTR_NAME_LINK.
Referenced by ll_dir_ioctl(), and ll_file_ioctl().
ssize_t ll_getxattr (struct dentry * dentry, const char * name, void * buffer, size_t size)
Definition at line 592 of file xattr.c.
References CDEBUG, D_VFSTRACE, DFID, LASSERT, ll_getxattr_common(), ll_getxattr_lov(), ll_i2sbi(), ll_inode2fid(), ll_stats_ops_tally(), LPROC_LL_GETXATTR, OBD_MD_FLXATTR, PFID, XATTR_LUSTRE_LOV, and XATTR_NAME_LOV.
Referenced by ll_getparent().
int ll_getxattr_common (struct inode * inode, const char * name, void * buffer, size_t size, __u64 valid)
Definition at line 357 of file xattr.c.
References CDEBUG, CERROR, current_pid, D_VFSTRACE, DFID, ENTRY, EXIT, get_xattr_type(), GOTO, LASSERT, LCONSOLE_INFO, ll_sb_info::ll_et, ll_sb_info::ll_flags, ll_get_fsname(), ll_i2info(), ll_i2sbi(), ll_inode2fid(), ll_sb_info::ll_md_exp, ll_sb_info::ll_rct, LL_SBI_RMT_CLIENT, LL_SBI_USER_XATTR, ll_sb_info::ll_xattr_cache_enabled, ll_xattr_cache_get(), ll_inode_info::lli_lock, ll_inode_info::lli_posix_acl, mdt_body::mbo_eadatasize, md_getxattr(), OBD_MD_FLXATTRLS, PFID, posix_acl_to_xattr, ptlrpc_req_finished(), rmtacl_ctl_entry::rce_ops, req_capsule_server_get(), req_capsule_server_sized_get(), RETURN, RMF_EADATA, RMF_MDT_BODY, RMT_LGETFACL, RMT_LSETFACL, RMT_RGETFACL, RMT_RSETFACL, ptlrpc_request::rq_pill, unlikely, XATTR_ACL_ACCESS_T, XATTR_ACL_DEFAULT_T, XATTR_NAME_ACL_ACCESS, XATTR_OTHER_T, XATTR_SECURITY_T, xattr_type_filter(), and XATTR_USER_T.
Referenced by ll_getxattr(), and ll_listxattr().
static int ll_glimpse_size (struct inode * inode) [inline, static]
Definition at line 1247 of file llite_internal.h.
References cfs_time_current(), cl_glimpse_size(), ll_i2info(), ll_inode_info::lli_glimpse_sem, and ll_inode_info::lli_glimpse_time.
Referenced by ll_do_fiemap(), ll_file_mmap(), ll_file_seek(), and ll_inode_revalidate().
int ll_have_md_lock (struct inode * inode, __u64 * bits, enum ldlm_mode l_req_mode)
test if some locks matching bits and l_req_mode are acquired
bits can be in different locks
if found clear the common lock bits in *bits
the bits not found, are kept in *bits
Parameters:
inode [IN]
bits [IN] searched lock bits [IN]
l_req_mode [IN] searched lock mode
Return values:
boolean,true iff all bits are found
Definition at line 3238 of file file.c.
References __u64, ldlm_inodebits::bits, CDEBUG, D_INFO, DFID, ENTRY, ldlm_policy_data::l_inodebits, ldlm_lock::l_policy_data, LCK_CR, LCK_CW, LCK_MINMODE, LCK_PR, LCK_PW, LDLM_FL_BLOCK_GRANTED, LDLM_FL_CBPENDING, LDLM_FL_TEST_LOCK, ldlm_handle2lock(), LDLM_IBITS, LDLM_LOCK_PUT, ldlm_lockname, ll_i2info(), ll_i2mdexp(), ll_inode_info::lli_fid, md_lock_match(), MDS_INODELOCK_MAXSHIFT, mode, PFID, and RETURN.
Referenced by __ll_inode_revalidate(), ll_md_blocking_ast(), and ll_readdir().
int ll_hsm_release (struct inode * inode)
Definition at line 1915 of file file.c.
References __u64, CDEBUG, cl_env_nested_get(), cl_env_nested_put(), D_INODE, DFID, ENTRY, EXIT, FMODE_WRITE, GOTO, ll_close_inode_openhandle(), ll_data_version(), LL_DV_WR_FLUSH, ll_get_fsname(), ll_i2info(), ll_lease_close(), ll_lease_open(), ll_merge_attr(), MDS_HSM_RELEASE, MDS_OPEN_RELEASE, and PFID.
Referenced by ll_dir_ioctl().
int ll_hsm_state_set (struct inode * inode, struct hsm_state_set * hss)
Definition at line 2074 of file file.c.
References CFS_CAP_SYS_ADMIN, cfs_capable(), ENTRY, HSM_FLAGS_MASK, HSM_USER_MASK, hsm_state_set::hss_archive_id, HSS_ARCHIVE_ID, hsm_state_set::hss_clearmask, hsm_state_set::hss_setmask, hsm_state_set::hss_valid, ll_finish_md_op_data(), LL_HSM_MAX_ARCHIVE, ll_i2mdexp(), LL_IOC_HSM_STATE_SET, ll_prep_md_op_data(), LUSTRE_OPC_ANY, obd_iocontrol(), md_op_data::op_data, and RETURN.
Referenced by ll_file_ioctl(), ll_hsm_import(), and ll_setattr_raw().
static struct obd_export* ll_i2dtexp (struct inode * inode) [static, read]
Definition at line 1095 of file llite_internal.h.
References ll_s2dtexp().
Referenced by ll_file_ioctl(), and ll_writepage().
void ll_i2gids (__u32 * suppgids, struct inode * i1, struct inode * i2)
Definition at line 366 of file namei.c.
References LASSERT, and ll_i2suppgid().
Referenced by ll_prep_md_op_data().
static struct ll_inode_info* ll_i2info (struct inode * inode) [static, read]
Definition at line 332 of file llite_internal.h.
References ll_inode_info::lli_vfs_inode.
Referenced by can_populate_pages(), cl_file_inode_init(), cl_inode2vvp(), cl_inode_fini(), cl_io_get(), cl_sync_file_range(), dentry_may_statahead(), do_bio_lustrebacked(), is_first_dirent(), ll_agl_add(), ll_agl_thread(), ll_agl_trigger(), ll_authorize_statahead(), ll_clear_inode(), ll_close_inode_openhandle(), ll_data_version(), ll_deauthorize_statahead(), ll_delete_inode(), ll_destroy_inode(), ll_dir_clear_lsm_md(), ll_do_fiemap(), ll_fault_io_init(), ll_file_getstripe(), ll_file_io_generic(), ll_file_ioctl(), ll_file_maxbytes(), ll_file_open(), ll_file_release(), ll_flush(), ll_fsync(), ll_get_acl(), ll_get_grouplock(), ll_get_name(), ll_getattr(), ll_getxattr_common(), ll_getxattr_lov(), ll_glimpse_size(), ll_have_md_lock(), ll_hsm_release(), ll_iget(), ll_iget_anon_dir(), ll_inode2fid(), ll_inode_from_resource_lock(), ll_inode_revalidate(), ll_inode_revalidate_fini(), ll_inode_size_lock(), ll_inode_size_unlock(), ll_invalidatepage(), ll_io_init(), ll_iocontrol(), ll_ladvise(), ll_layout_conf(), ll_layout_lock_set(), ll_layout_refresh(), ll_layout_refresh_locked(), ll_layout_restore(), ll_lease_close(), ll_lease_open(), ll_lookup_it_finish(), ll_md_blocking_ast(), ll_md_close(), ll_md_real_close(), ll_merge_attr(), ll_merge_md_attr(), ll_new_node(), ll_page_mkwrite0(), ll_prep_md_op_data(), ll_prepare_close(), ll_put_grouplock(), ll_read_inode2(), ll_readlink_internal(), ll_readpage(), ll_release_page(), ll_releasepage(), ll_sai_alloc(), ll_sai_get(), ll_sai_put(), ll_set_inode(), ll_setattr_raw(), ll_start_agl(), ll_statahead_interpret(), ll_statahead_thread(), ll_take_md_lock(), ll_test_inode(), ll_test_inode_by_fid(), ll_update_inode(), ll_update_lsm_md(), ll_update_remote_perm(), ll_write_begin(), ll_writepage(), ll_writepages(), ll_xattr_cache_destroy(), ll_xattr_cache_get(), ll_xattr_cache_refill(), ll_xattr_find_get_lock(), lo_ioctl(), lustre_check_remote_perm(), revalidate_statahead_dentry(), sa_alloc(), sa_handle_callback(), sa_kill(), sa_make_ready(), sa_statahead(), start_statahead_thread(), vvp_conf_set(), vvp_io_fault_end(), vvp_io_fault_start(), vvp_io_fini(), vvp_io_init(), vvp_io_read_start(), vvp_io_rw_end(), vvp_io_setattr_end(), vvp_io_setattr_fini(), vvp_io_setattr_start(), vvp_io_write_start(), vvp_mmap_locks(), vvp_object_invariant(), vvp_object_print(), and vvp_req_attr_set().
static struct obd_export* ll_i2mdexp (struct inode * inode) [static, read]
Definition at line 1100 of file llite_internal.h.
References ll_s2mdexp().
Referenced by __ll_inode_revalidate(), get_hsm_state(), ll_close_inode_openhandle(), ll_dir_ioctl(), ll_dir_setdirstripe(), ll_dump_inode(), ll_fid2path(), ll_file_ioctl(), ll_get_dir_page(), ll_have_md_lock(), ll_hsm_state_set(), ll_lookup_it(), ll_lookup_it_finish(), ll_md_close(), ll_merge_md_attr(), ll_mkdir(), ll_mknod(), ll_swap_layouts(), ll_take_md_lock(), ll_update_lsm_md(), revalidate_statahead_dentry(), sa_instantiate(), sa_lookup(), and sa_revalidate().
static struct ll_sb_info* ll_i2sbi (struct inode * inode) [static, read]
Definition at line 1090 of file llite_internal.h.
References ll_s2sbi.
Referenced by __ll_inode_revalidate(), cl_file_inode_init(), dentry_may_statahead(), do_bio_lustrebacked(), is_first_dirent(), ll_agl_thread(), ll_clear_inode(), ll_create_nd(), ll_create_node(), ll_dir_getstripe(), ll_dir_ioctl(), ll_dir_read(), ll_dir_seek(), ll_dir_setdirstripe(), ll_dir_setstripe(), ll_fid2path(), ll_file_flock(), ll_file_io_generic(), ll_file_ioctl(), ll_file_mmap(), ll_file_nolock(), ll_file_open(), ll_file_release(), ll_file_seek(), ll_flush_ctx(), ll_fsync(), ll_get_fid_by_name(), ll_get_mdt_idx(), ll_get_name(), ll_get_obd_name(), ll_getattr(), ll_getparent(), ll_getxattr(), ll_getxattr_common(), ll_inode_permission(), ll_intent_file_open(), ll_io_read_page(), ll_iocontrol(), ll_layout_fetch(), ll_layout_lock_set(), ll_layout_refresh(), ll_layout_refresh_locked(), ll_layout_restore(), ll_lease_open(), ll_link(), ll_listxattr(), ll_local_open(), ll_lookup_finish_locks(), ll_lookup_it(), ll_lookup_it_finish(), ll_lov_getstripe_ea_info(), ll_md_blocking_ast(), ll_md_setattr(), ll_migrate(), ll_mkdir(), ll_mknod(), ll_new_node(), ll_obd_statfs(), ll_prep_inode(), ll_prep_md_op_data(), ll_ra_stats_inc(), ll_read_inode2(), ll_readahead(), ll_readdir(), ll_readlink_internal(), ll_release_openhandle(), ll_removexattr(), ll_rename(), ll_rmdir(), ll_rmdir_entry(), ll_sai_put(), ll_setattr_raw(), ll_setxattr(), ll_setxattr_common(), ll_statahead_thread(), ll_symlink(), ll_unlink(), ll_update_inode(), ll_update_remote_perm(), ll_writepages(), ll_xattr_cache_get(), ll_xattr_cache_refill(), ll_xattr_find_get_lock(), lustre_check_remote_perm(), sa_instantiate(), sa_put(), start_statahead_thread(), vvp_io_read_start(), vvp_io_write_start(), and vvp_page_completion_read().
__u32 ll_i2suppgid (struct inode * i)
Definition at line 354 of file namei.c.
References __kgid_val(), from_kgid(), and INVALID_GID.
Referenced by ll_i2gids(), ll_setxattr_common(), and lustre_check_remote_perm().
struct inode* ll_iget (struct super_block * sb, ino_t hash, struct lustre_md * lic) [read]
Get an inode by inode number(), which is already instantiated by the intent lookup).
Definition at line 111 of file namei.c.
References lustre_md::body, CDEBUG, cl_file_inode_init(), D_VFSTRACE, DFID, ENTRY, LASSERT, ll_dir_clear_lsm_md(), ll_i2info(), ll_read_inode2(), ll_set_inode(), ll_test_inode(), ll_update_inode(), mdt_body::mbo_fid1, PFID, and RETURN.
Referenced by client_common_fill_super(), and ll_prep_inode().
static struct inode* ll_info2i (struct ll_inode_info * lli) [static, read]
Definition at line 698 of file llite_internal.h.
References ll_inode_info::lli_vfs_inode.
int ll_init_security (struct dentry * dentry, struct inode * inode, struct inode * dir)
Definition at line 112 of file xattr_security.c.
References GOTO, ll_security_inode_init_security, ll_setxattr(), name, OBD_ALLOC, OBD_FREE, strlcat(), strlcpy(), and XATTR_SECURITY_PREFIX.
Referenced by ll_create_it(), ll_dir_setdirstripe(), and ll_new_node().
static struct lu_fid* ll_inode2fid (struct inode * inode) [static, read]
Definition at line 1105 of file llite_internal.h.
References LASSERT, ll_i2info(), and ll_inode_info::lli_fid.
Referenced by __ll_inode_revalidate(), cl_sync_file_range(), is_first_dirent(), ll_clear_inode(), ll_close_inode_openhandle(), ll_create_it(), ll_create_node(), ll_delete_inode(), ll_dir_get_parent_fid(), ll_dir_getstripe(), ll_dir_ioctl(), ll_dir_setdirstripe(), ll_direct_IO(), ll_dirty_page_discard_warn(), ll_dump_inode(), ll_encode_fh(), ll_fid2path(), ll_file_flock(), ll_file_ioctl(), ll_file_open(), ll_file_release(), ll_file_seek(), ll_fsync(), ll_get_mdt_idx(), ll_getxattr(), ll_getxattr_common(), ll_inode_permission(), ll_inode_revalidate_fini(), ll_invalidate_aliases(), ll_io_read_page(), ll_iocontrol(), ll_ladvise(), ll_layout_fetch(), ll_layout_refresh(), ll_lease_open(), ll_link(), ll_listxattr(), ll_lookup_finish_locks(), ll_lookup_it(), ll_md_blocking_ast(), ll_md_close(), ll_migrate(), ll_mkdir(), ll_mknod(), ll_page_mkwrite(), ll_prep_md_op_data(), ll_readdir(), ll_readlink_internal(), ll_removexattr(), ll_rename(), ll_rmdir(), ll_rmdir_entry(), ll_set_lock_data(), ll_setattr_raw(), ll_setxattr(), ll_setxattr_common(), ll_statahead_thread(), ll_swap_layouts(), ll_swap_layouts_close(), ll_symlink(), ll_unlink(), ll_update_inode(), ll_update_lsm_md(), ll_update_times(), ll_xattr_cache_refill(), ll_xattr_find_get_lock(), lustre_check_remote_perm(), revalidate_statahead_dentry(), sa_instantiate(), sa_revalidate(), vvp_io_write_start(), and vvp_pgcache_page_show().
struct inode* ll_inode_from_resource_lock (struct ldlm_lock * lock) [read]
Definition at line 1180 of file llite_lib.c.
References D_INFO, D_WARNING, ldlm_lock::l_resource, LDLM_DEBUG_LIMIT, ll_i2info(), LLI_INODE_MAGIC, ll_inode_info::lli_inode_magic, lock_res_and_lock(), ldlm_resource::lr_lvb_inode, and unlock_res_and_lock().
Referenced by ll_md_blocking_ast().
int ll_inode_permission (struct inode * inode, int mask, struct nameidata * nd)
Definition at line 3601 of file file.c.
References __kgid_val(), __kuid_val(), __ll_inode_revalidate(), CDEBUG, CFS_CAP_FS_MASK, D_OTHER, D_VFSTRACE, DFID, ENTRY, GLOBAL_ROOT_UID, ll_check_acl(), ll_sb_info::ll_flags, ll_generic_permission, ll_i2sbi(), ll_inode2fid(), LL_SBI_NOROOTSQUASH, LL_SBI_RMT_CLIENT, ll_sb_info::ll_squash, ll_stats_ops_tally(), LPROC_LL_INODE_PERM, lustre_check_remote_perm(), make_kgid(), make_kuid(), MDS_INODELOCK_LOOKUP, PFID, RETURN, root_squash_info::rsi_gid, root_squash_info::rsi_uid, uid_eq(), and unlikely.
void ll_inode_size_lock (struct inode * inode)
Definition at line 1847 of file llite_lib.c.
References LASSERT, ll_i2info(), and ll_inode_info::lli_size_mutex.
Referenced by ll_follow_link(), ll_lov_setstripe_ea_info(), ll_merge_attr(), vvp_do_vmtruncate(), and vvp_object_size_lock().
void ll_inode_size_unlock (struct inode * inode)
Definition at line 1857 of file llite_lib.c.
References ll_i2info(), and ll_inode_info::lli_size_mutex.
Referenced by ll_follow_link(), ll_lov_setstripe_ea_info(), ll_merge_attr(), vvp_do_vmtruncate(), and vvp_object_size_unlock().
void ll_intent_drop_lock (struct lookup_intent *)
Definition at line 204 of file dcache.c.
References CDEBUG, lustre_handle::cookie, D_DLMTRACE, lookup_intent::it_lock_handle, lookup_intent::it_lock_mode, lookup_intent::it_op, lookup_intent::it_remote_lock_handle, lookup_intent::it_remote_lock_mode, ldlm_lock_decref(), and LPX64.
Referenced by ll_intent_file_open(), ll_intent_release(), ll_layout_refresh_locked(), ll_lookup_finish_locks(), ll_statahead_interpret(), and ll_xattr_cache_refill().
void ll_intent_release (struct lookup_intent *)
Definition at line 230 of file dcache.c.
References CDEBUG, D_INFO, DISP_ENQ_CREATE_REF, DISP_ENQ_OPEN_REF, ENTRY, EXIT, lookup_intent::it_disposition, it_disposition(), lookup_intent::it_request, ll_intent_drop_lock(), and ptlrpc_req_finished().
Referenced by __ll_inode_revalidate(), ll_create_nd(), ll_lease_open(), ll_lookup_it(), ll_lookup_it_finish(), ll_lookup_nd(), ll_lov_setstripe_ea_info(), ll_release(), ll_statahead_interpret(), revalidate_statahead_dentry(), sa_make_ready(), and sa_revalidate().
void ll_invalidate_aliases (struct inode *)
Definition at line 248 of file dcache.c.
References CDEBUG, CERROR, D_DENTRY, D_INODE, d_lustre_invalidate(), DECLARE_LL_D_HLIST_NODE_PTR, DFID, ENTRY, EXIT, LASSERT, libcfs_debug_dumpstack, ll_d_hlist_for_each_entry, ll_get_fsname(), ll_inode2fid(), ll_lock_dcache(), ll_unlock_dcache(), lustre_dump_dentry(), PFID, and unlikely.
Referenced by ll_md_blocking_ast().
static void ll_invalidate_page (struct page * vmpage) [inline, static]
Definition at line 1050 of file llite_internal.h.
References LASSERT, ll_teardown_mmaps(), mapping, and truncate_complete_page().
Referenced by vvp_io_fault_start(), and vvp_page_discard().
int ll_iocontrol (struct inode * inode, struct file * file, unsigned int cmd, unsigned long arg)
Definition at line 2064 of file llite_lib.c.
References __user, CERROR, cl_setattr_ost(), DFID, ENTRY, obd_export::exp_obd, FSFILT_IOC_GETFLAGS, FSFILT_IOC_SETFLAGS, ll_finish_md_op_data(), ll_i2info(), ll_i2sbi(), ll_inode2fid(), ll_sb_info::ll_md_exp, ll_prep_md_op_data(), ll_inode_info::lli_clob, LUSTRE_OPC_ANY, mdt_body::mbo_flags, md_getattr(), md_setattr(), OBD_ALLOC_PTR, OBD_FREE_PTR, OBD_MD_FLFLAGS, obd_device::obd_name, md_op_data::op_attr, md_op_data::op_attr_flags, md_op_data::op_data, md_op_data::op_valid, PFID, ptlrpc_req_finished(), req_capsule_server_get(), RETURN, RMF_MDT_BODY, and ptlrpc_request::rq_pill.
Referenced by ll_dir_ioctl(), and ll_file_ioctl().
void* ll_iocontrol_register (llioc_callback_t cb, int count, unsigned int * cmd)
Definition at line 3789 of file file.c.
References ENTRY, llioc_ctl_data::ioc_head, llioc_ctl_data::ioc_sem, llioc_data::iocd_cb, llioc_data::iocd_cmd, llioc_data::iocd_count, llioc_data::iocd_list, llioc_data::iocd_size, list_add_tail(), llioc, LLIOC_MAX_CMD, OBD_ALLOC, RETURN, and size.
Referenced by lloop_init().
void ll_iocontrol_unregister (void * magic)
Definition at line 3817 of file file.c.
References CWARN, llioc_ctl_data::ioc_head, llioc_ctl_data::ioc_sem, llioc_data::iocd_list, llioc_data::iocd_size, list_del(), list_for_each_entry, llioc, OBD_FREE, and size.
Referenced by lloop_exit(), and lloop_init().
void ll_kill_super (struct super_block * sb)
Definition at line 762 of file llite_lib.c.
References ENTRY, EXIT, ll_s2sbi, ll_sb_info::ll_sa_running, ll_sb_info::ll_sdev_orig, and ll_sb_info::ll_umounting.
Referenced by lustre_init().
int ll_layout_conf (struct inode * inode, const struct cl_object_conf * conf)
Definition at line 3872 of file file.c.
References CDEBUG, cl_conf_set(), cl_env_nested_get(), cl_env_nested_put(), cl_layout::cl_layout_gen, cl_object_layout_get(), cl_object_conf::coc_lock, cl_object_conf::coc_opc, D_VFSTRACE, DFID, ENTRY, GOTO, LASSERT, ldlm_has_layout(), ldlm_lock_allow_match(), ll_i2info(), ll_layout_version_get(), ll_layout_version_set(), ll_inode_info::lli_clob, ll_inode_info::lli_fid, OBJECT_CONF_SET, PFID, and RETURN.
Referenced by ll_layout_lock_set(), ll_md_blocking_ast(), and ll_prep_inode().
int ll_layout_refresh (struct inode * inode, __u32 * gen)
This function checks if there exists a LAYOUT lock on the client side, or enqueues it if it doesn't have one in cache.
This function will not hold layout lock so it may be revoked any time after this function returns. Any operations depend on layout should be redone in that case.
This function should be called before lov_io_init() to get an uptodate layout version, the caller should save the version number and after IO is finished, this function should be called again to verify that layout is not changed during IO time.
Definition at line 4155 of file file.c.
References CL_LAYOUT_GEN_NONE, ENTRY, fid_is_sane(), GOTO, LASSERT, ll_sb_info::ll_flags, ll_i2info(), ll_i2sbi(), ll_inode2fid(), ll_layout_refresh_locked(), ll_layout_version_get(), LL_SBI_LAYOUT_LOCK, ll_inode_info::lli_layout_mutex, and RETURN.
Referenced by ll_lov_setstripe(), vvp_io_fini(), and vvp_io_init().
int ll_layout_restore (struct inode * inode, loff_t start, __u64 length)
This function send a restore request to the MDT.
Definition at line 4187 of file file.c.
References ENTRY, hsm_request::hr_action, hsm_request::hr_archive_id, hsm_request::hr_flags, hsm_request::hr_itemcount, HUA_RESTORE, hsm_user_item::hui_extent, hsm_user_item::hui_fid, hsm_user_request::hur_request, hsm_user_request::hur_user_item, hsm_extent::length, ll_i2info(), ll_i2sbi(), LL_IOC_HSM_REQUEST, OBD_ALLOC, OBD_FREE, obd_iocontrol(), hsm_extent::offset, and RETURN.
Referenced by vvp_io_fini().
static __u32 ll_layout_version_get (struct ll_inode_info * lli) [inline, static]
Definition at line 257 of file llite_internal.h.
References ll_inode_info::lli_layout_gen, and ll_inode_info::lli_layout_lock.
Referenced by can_populate_pages(), ll_layout_conf(), and ll_layout_refresh().
static void ll_layout_version_set (struct ll_inode_info * lli, __u32 gen) [inline, static]
Definition at line 268 of file llite_internal.h.
References ll_inode_info::lli_layout_gen, and ll_inode_info::lli_layout_lock.
Referenced by ll_layout_conf(), ll_lli_init(), and vvp_conf_set().
ssize_t ll_listxattr (struct dentry * dentry, char * buffer, size_t size)
Definition at line 613 of file xattr.c.
References CDEBUG, D_VFSTRACE, DFID, get_xattr_type(), ll_getxattr_common(), ll_getxattr_lov(), ll_i2sbi(), ll_inode2fid(), ll_stats_ops_tally(), LPROC_LL_LISTXATTR, OBD_MD_FLXATTRLS, PFID, RETURN, strnlen, XATTR_LUSTRE_LOV, and xattr_type_filter().
void ll_lli_init (struct ll_inode_info * lli)
Definition at line 933 of file llite_lib.c.
References CL_LAYOUT_GEN_NONE, fid_zero(), INIT_LIST_HEAD, LASSERT, ll_layout_version_set(), ll_inode_info::lli_agl_index, ll_inode_info::lli_agl_list, ll_inode_info::lli_agl_lock, ll_inode_info::lli_async_rc, ll_inode_info::lli_clob, ll_inode_info::lli_def_stripe_offset, ll_inode_info::lli_flags, ll_inode_info::lli_glimpse_sem, ll_inode_info::lli_glimpse_time, LLI_INODE_MAGIC, ll_inode_info::lli_inode_magic, ll_inode_info::lli_layout_lock, ll_inode_info::lli_layout_mutex, ll_inode_info::lli_lock, ll_inode_info::lli_mds_exec_och, ll_inode_info::lli_mds_read_och, ll_inode_info::lli_mds_write_och, ll_inode_info::lli_och_mutex, ll_inode_info::lli_open_count, ll_inode_info::lli_open_fd_exec_count, ll_inode_info::lli_open_fd_read_count, ll_inode_info::lli_open_fd_write_count, ll_inode_info::lli_opendir_key, ll_inode_info::lli_opendir_pid, ll_inode_info::lli_pfid, ll_inode_info::lli_posix_acl, ll_inode_info::lli_readdir_mutex, ll_inode_info::lli_remote_perms, ll_inode_info::lli_rmtperm_mutex, ll_inode_info::lli_rmtperm_time, ll_inode_info::lli_sa_enabled, ll_inode_info::lli_sa_lock, ll_inode_info::lli_sai, ll_inode_info::lli_size_mutex, ll_inode_info::lli_symlink_name, ll_inode_info::lli_trunc_sem, ll_inode_info::lli_vfs_inode, ll_inode_info::lli_write_tree, ll_inode_info::lli_xattrs_enq_lock, ll_inode_info::lli_xattrs_list_rwsem, and range_lock_tree_init().
Referenced by ll_iget_anon_dir(), and ll_set_inode().
static void ll_lock_dcache (struct inode * inode) [inline, static]
Definition at line 1416 of file llite_internal.h.
Referenced by __ll_inode_revalidate(), ll_find_alias(), ll_invalidate_aliases(), and ll_invalidate_negative_children().
void ll_lookup_finish_locks (struct lookup_intent * it, struct dentry * dentry)
Definition at line 299 of file dcache.c.
References CDEBUG, D_DLMTRACE, DFID, IT_GETATTR, lookup_intent::it_lock_mode, IT_LOOKUP, lookup_intent::it_op, LASSERT, ll_i2sbi(), ll_inode2fid(), ll_intent_drop_lock(), ll_sb_info::ll_md_exp, ll_set_lock_data(), and PFID.
Referenced by __ll_inode_revalidate(), and ll_lookup_it().
int ll_lov_getstripe_ea_info (struct inode * inode, const char * filename, struct lov_mds_md ** lmm, int * lmm_size, struct ptlrpc_request ** request)
Definition at line 1471 of file file.c.
References CDEBUG, cpu_to_le32, D_INFO, GOTO, LASSERT, le16_to_cpu, le32_to_cpu, ll_finish_md_op_data(), ll_get_default_mdsize(), ll_i2sbi(), ll_sb_info::ll_md_exp, ll_prep_md_op_data(), LOV_MAGIC, LOV_MAGIC_V1, LOV_MAGIC_V3, lov_mds_md, LOV_PATTERN_F_RELEASED, LUSTRE_OPC_ANY, lustre_swab_lov_user_md_objects(), lustre_swab_lov_user_md_v1(), lustre_swab_lov_user_md_v3(), mdt_body::mbo_eadatasize, mdt_body::mbo_mode, mdt_body::mbo_valid, md_getattr_name(), OBD_MD_FLDIREA, OBD_MD_FLEASIZE, md_op_data::op_data, md_op_data::op_valid, req_capsule_server_get(), req_capsule_server_sized_get(), RETURN, RMF_MDT_BODY, RMF_MDT_MD, and ptlrpc_request::rq_pill.
Referenced by ll_dir_ioctl().
int ll_lov_setstripe_ea_info (struct inode * inode, struct file * file, __u64 flags, struct lov_user_md * lum, int lum_size)
Definition at line 1445 of file file.c.
References cl_lov_delay_create_clear(), ENTRY, GOTO, lookup_intent::it_op, IT_OPEN, ll_inode_size_lock(), ll_inode_size_unlock(), ll_intent_file_open(), ll_intent_release(), ll_release_openhandle(), MDS_OPEN_BY_FID, and RETURN.
Referenced by ll_lov_setea(), ll_lov_setstripe(), and ll_setxattr().
static ssize_t ll_lov_user_md_size (const struct lov_user_md * lum) [inline, static]
Definition at line 956 of file llite_internal.h.
References LOV_MAX_STRIPE_COUNT, LOV_USER_MAGIC_SPECIFIC, LOV_USER_MAGIC_V1, LOV_USER_MAGIC_V3, and lov_user_md_size().
Referenced by ll_copy_user_md(), and ll_setxattr().
int ll_md_blocking_ast (struct ldlm_lock * , struct ldlm_lock_desc * , void * data, int flag)
Definition at line 187 of file namei.c.
References __u64, ldlm_inodebits::bits, CDEBUG, cl_fid_build_ino(), cl_object_conf::coc_opc, D_INODE, DFID, ENTRY, fid_is_zero(), fid_res_name_eq(), FMODE_EXEC, FMODE_READ, FMODE_WRITE, ldlm_lock::l_ast_data, ldlm_policy_data::l_inodebits, ldlm_lock::l_policy_data, ldlm_lock::l_req_mode, ldlm_lock::l_resource, LASSERT, LBUG, LCF_ASYNC, LCK_CR, LCK_CW, LCK_MINMODE, LCK_PR, LDLM_CB_BLOCKING, LDLM_CB_CANCELING, ldlm_cli_cancel(), LDLM_ERROR, ldlm_is_canceling, ldlm_lock2handle(), ll_have_md_lock(), ll_i2info(), ll_i2sbi(), ll_inode2fid(), ll_inode_from_resource_lock(), ll_invalidate_aliases(), ll_invalidate_negative_children(), ll_layout_conf(), ll_md_real_close(), ll_need_32bit_api(), ll_test_inode_by_fid(), ll_xattr_cache_destroy(), ll_inode_info::lli_def_stripe_offset, ll_inode_info::lli_pfid, ldlm_resource::lr_name, MDS_INODELOCK_LAYOUT, MDS_INODELOCK_LOOKUP, MDS_INODELOCK_OPEN, MDS_INODELOCK_PERM, MDS_INODELOCK_UPDATE, MDS_INODELOCK_XATTR, OBJECT_CONF_INVALIDATE, PFID, RETURN, and unlikely.
Referenced by __ll_inode_revalidate(), ll_get_dir_page(), ll_intent_file_open(), ll_layout_refresh_locked(), ll_lookup_it(), ll_merge_md_attr(), ll_update_lsm_md(), ll_xattr_find_get_lock(), and sa_prep_data().
int ll_md_real_close (struct inode * inode, fmode_t fmode)
Definition at line 203 of file file.c.
References __u64, ENTRY, FMODE_EXEC, FMODE_READ, FMODE_WRITE, LASSERT, ll_close_inode_openhandle(), ll_i2info(), ll_inode_info::lli_mds_exec_och, ll_inode_info::lli_mds_read_och, ll_inode_info::lli_mds_write_och, ll_inode_info::lli_och_mutex, ll_inode_info::lli_open_fd_exec_count, ll_inode_info::lli_open_fd_read_count, ll_inode_info::lli_open_fd_write_count, and RETURN.
Referenced by ll_clear_inode(), ll_md_blocking_ast(), and ll_md_close().
int ll_merge_attr (const struct lu_env * env, struct inode * inode)
Definition at line 929 of file file.c.
References cl_attr::cat_atime, cl_attr::cat_blocks, cl_attr::cat_ctime, cl_attr::cat_mtime, cl_attr::cat_size, CDEBUG, cl_object_attr_get(), cl_object_attr_lock(), cl_object_attr_unlock(), D_VFSTRACE, DFID, ENTRY, GOTO, ll_i2info(), ll_inode_size_lock(), ll_inode_size_unlock(), ll_inode_info::lli_atime, ll_inode_info::lli_clob, ll_inode_info::lli_ctime, ll_inode_info::lli_fid, ll_inode_info::lli_mtime, LPU64, LTIME_S, PFID, RETURN, and vvp_env_thread_attr().
Referenced by cl_glimpse_lock(), ll_hsm_release(), vvp_io_write_commit(), and vvp_io_write_start().
int ll_migrate (struct inode * parent, struct file * file, int mdtidx, const char * name, int namelen)
Definition at line 3083 of file file.c.
References __u64, CDEBUG, CERROR, CLI_MIGRATE, lustre_handle::cookie, D_INFO, D_VFSTRACE, DEAD_HANDLE_MAGIC, DFID, ENTRY, fid_is_sane(), FMODE_WRITE, GOTO, ll_data_version(), LL_DV_WR_FLUSH, ll_finish_md_op_data(), ll_get_fid_by_name(), ll_get_fsname(), ll_get_mdt_idx_by_fid(), ll_i2sbi(), ll_inode2fid(), ll_lease_close(), ll_lease_open(), ll_prep_md_op_data(), ll_update_times(), LUSTRE_OPC_ANY, mdt_body::mbo_valid, md_clear_open_replay_data(), md_rename(), MDS_RENAME_MIGRATE, OBD_FREE_PTR, OBD_MD_CLOSE_INTENT_EXECED, obd_mod_put, obd_client_handle::och_fh, obd_client_handle::och_lease_handle, obd_client_handle::och_mod, md_op_data::op_bias, md_op_data::op_cli_flags, md_op_data::op_data, md_op_data::op_data_version, md_op_data::op_fid3, md_op_data::op_handle, md_op_data::op_lease_handle, md_op_data::op_mds, PFID, ptlrpc_req_finished(), req_capsule_server_get(), RETURN, RMF_MDT_BODY, and ptlrpc_request::rq_pill.
Referenced by ll_dir_ioctl().
static int ll_need_32bit_api (struct ll_sb_info * sbi) [inline, static]
Definition at line 706 of file llite_internal.h.
References ll_sb_info::ll_flags, LL_SBI_32BIT_API, and unlikely.
Referenced by ll_dir_read(), ll_dir_seek(), ll_getattr(), ll_md_blocking_ast(), ll_prep_md_op_data(), ll_readdir(), and search_inode_for_lustre().
int ll_obd_statfs (struct inode * inode, void __user * arg)
Definition at line 2369 of file llite_lib.c.
References buf, GOTO, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf2, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, IOC_OBD_STATFS, obd_ioctl_data::ioc_pbuf1, obd_ioctl_data::ioc_pbuf2, obd_ioctl_data::ioc_plen1, obd_ioctl_data::ioc_plen2, ll_sb_info::ll_dt_exp, ll_i2sbi(), ll_sb_info::ll_md_exp, LL_STATFS_LMV, LL_STATFS_LOV, obd_iocontrol(), and obd_ioctl_getdata().
Referenced by ll_dir_ioctl(), and ll_file_ioctl().
void ll_open_cleanup (struct super_block * sb, struct ptlrpc_request * open_req)
Cleanup the open handle that is cached on MDT-side.
For open case, the client side open handling thread may hit error after the MDT grant the open. Under such case, the client should send close RPC to the MDT as cleanup; otherwise, the open handle on the MDT will be leaked there until the client umount or evicted.
In further, if someone unlinked the file, because the open handle holds the reference on such file/object, then it will block the subsequent threads that want to locate such object via FID.
Parameters:
[in] sb super block for this file-system
[in] open_req pointer to the original open request
Definition at line 2256 of file llite_lib.c.
References cfs_time_current_sec(), CWARN, DFID, ENTRY, EXIT, ll_finish_md_op_data(), ll_get_fsname(), ll_s2sbi, mdt_body::mbo_fid1, mdt_body::mbo_handle, md_close(), OBD_ALLOC_PTR, md_op_data::op_data, md_op_data::op_fid1, md_op_data::op_handle, md_op_data::op_mod_time, PFID, ptlrpc_req_finished(), req_capsule_server_get(), RETURN_EXIT, RMF_MDT_BODY, and ptlrpc_request::rq_pill.
Referenced by ll_lookup_it_finish(), and ll_prep_inode().
int ll_page_sync_io (const struct lu_env * env, struct cl_io * io, struct cl_page * page, enum cl_req_type crt)
Definition at line 1176 of file rw.c.
References cl_2queue::c2_qin, cl_io::ci_queue, cl_io::ci_type, CIT_READ, CIT_WRITE, cl_2queue_fini(), cl_2queue_init_page(), cl_io_submit_sync(), cl_page_is_owned(), cl_page_list_disown(), CRT_READ, and LASSERT.
Referenced by ll_prepare_partial_page().
int ll_prep_inode (struct inode ** inode, struct ptlrpc_request * req, struct super_block * , struct lookup_intent *)
Definition at line 2284 of file llite_lib.c.
References lustre_md::body, CERROR, cl_fid_build_ino(), cleanup(), cl_object_conf::coc_inode, cl_object_conf::coc_layout, cl_object_conf::coc_lock, cl_object_conf::coc_opc, lustre_handle::cookie, ENTRY, fid_is_sane(), GOTO, lookup_intent::it_lock_handle, lookup_intent::it_lock_mode, lookup_intent::it_op, IT_OPEN, LASSERT, lustre_md::layout, ldlm_handle2lock(), ldlm_has_layout(), LDLM_LOCK_PUT, ll_sb_info::ll_dt_exp, ll_sb_info::ll_flags, ll_i2sbi(), ll_iget(), ll_layout_conf(), ll_sb_info::ll_md_exp, ll_open_cleanup(), ll_s2sbi, LL_SBI_32BIT_API, ll_update_inode(), mdt_body::mbo_fid1, md_free_lustre_md(), md_get_lustre_md(), OBJECT_CONF_SET, and cl_object_conf::u.
Referenced by __ll_inode_revalidate(), ll_create_node(), ll_dir_setdirstripe(), ll_get_fid_by_name(), ll_intent_file_open(), ll_lookup_it_finish(), ll_new_node(), ll_revalidate_it_finish(), sa_instantiate(), and search_inode_for_lustre().
struct md_op_data* ll_prep_md_op_data (struct md_op_data * op_data, struct inode * i1, struct inode * i2, const char * name, size_t namelen, __u32 mode, __u32 opc, void * data) [read]
Definition at line 2440 of file llite_lib.c.
References cfs_curproc_cap_pack(), cfs_time_current_sec(), CLI_API32, CLI_HASH64, fid_zero(), filename_is_volatile(), from_kgid(), from_kuid(), LASSERT, ll_i2gids(), ll_i2info(), ll_i2sbi(), ll_inode2fid(), ll_need_32bit_api(), LL_SBI_64BIT_HASH, ll_inode_info::lli_def_stripe_offset, ll_inode_info::lli_lsm_md, lu_name_is_valid_2(), LUSTRE_OPC_CREATE, LUSTRE_OPC_MKDIR, MDS_CREATE_VOLATILE, OBD_ALLOC_PTR, md_op_data::op_bias, md_op_data::op_cap, md_op_data::op_cli_flags, md_op_data::op_data, md_op_data::op_default_stripe_offset, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_fsgid, md_op_data::op_fsuid, md_op_data::op_mds, md_op_data::op_mea1, md_op_data::op_mea2, md_op_data::op_mod_time, md_op_data::op_mode, md_op_data::op_name, md_op_data::op_namelen, and md_op_data::op_suppgids.
Referenced by __ll_inode_revalidate(), get_hsm_state(), is_first_dirent(), ll_dir_get_parent_fid(), ll_dir_getstripe(), ll_dir_setdirstripe(), ll_dir_setstripe(), ll_file_flock(), ll_file_ioctl(), ll_get_fid_by_name(), ll_get_name(), ll_hsm_state_set(), ll_intent_file_open(), ll_iocontrol(), ll_layout_refresh_locked(), ll_lease_open(), ll_link(), ll_lookup_it(), ll_lov_getstripe_ea_info(), ll_md_setattr(), ll_migrate(), ll_new_node(), ll_prepare_close(), ll_readdir(), ll_readlink_internal(), ll_rename(), ll_rmdir(), ll_rmdir_entry(), ll_statahead_thread(), ll_swap_layouts(), ll_unlink(), ll_xattr_find_get_lock(), and sa_prep_data().
int ll_process_config (struct lustre_cfg * lcfg)
Definition at line 2413 of file llite_lib.c.
References class_process_proc_param(), LASSERT, LMD_MAGIC, lustre_cfg_string(), and PARAM_LLITE.
Referenced by lustre_init().
void ll_put_super (struct super_block * sb)
Definition at line 1099 of file llite_lib.c.
References cl_client_cache::ccc_unstable_nr, cl_client_cache::ccc_unstable_waitq, CDEBUG, config_llog_instance::cfg_instance, cl_env_cache_purge(), class_del_profile(), class_devices_in_group(), class_exp2obd(), class_manual_cleanup(), client_common_put_super(), D_VFSTRACE, ENTRY, EXIT, l_wait_event, LASSERTF, LCONSOLE_WARN, ll_sb_info::ll_cache, ll_sb_info::ll_client_common_fill_super_succeeded, ll_sb_info::ll_flags, ll_free_sbi(), ll_sb_info::ll_md_exp, ll_s2sbi, ll_sb_info::ll_sb_uuid, LL_SBI_VERBOSE, lustre_common_put_super(), lustre_end_log(), LWI_INTR, LWI_ON_SIGNAL_NOOP, obd_device::obd_force, and PARAMS_FILENAME.
Referenced by ll_fill_super().
void ll_ra_count_put (struct ll_sb_info * sbi, unsigned long len)
Definition at line 115 of file rw.c.
References ll_sb_info::ll_ra_info, and ll_ra_info::ra_cur_pages.
Referenced by ll_readahead(), and vvp_page_completion_read().
void ll_ra_stats_inc (struct inode * inode, enum ra_stat which)
Definition at line 127 of file rw.c.
References ll_i2sbi(), and ll_ra_stats_inc_sbi().
Referenced by ll_read_ahead_page(), ll_readahead(), and vvp_page_discard().
void ll_ras_enter (struct file * f)
Definition at line 158 of file rw.c.
References ll_file_data::fd_ras, LUSTRE_FPRIVATE, ll_readahead_state::ras_consecutive_requests, ll_readahead_state::ras_lock, ll_readahead_state::ras_request_index, and ll_readahead_state::ras_requests.
Referenced by vvp_io_read_start().
int ll_read_inode2 (struct inode * inode, void * opaque)
Definition at line 1987 of file llite_lib.c.
References CDEBUG, D_VFSTRACE, DFID, ENTRY, EXIT, ll_aops, ll_dir_inode_operations, ll_dir_operations, ll_fast_symlink_inode_operations, ll_file_inode_operations, ll_sb_info::ll_fop, ll_i2info(), ll_i2sbi(), ll_special_inode_operations, ll_update_inode(), ll_inode_info::lli_fid, LTIME_S, PFID, and RETURN.
Referenced by ll_iget().
void ll_readahead_init (struct inode * inode, struct ll_readahead_state * ras)
Definition at line 605 of file rw.c.
References PTLRPC_MAX_BRW_PAGES, ll_readahead_state::ras_lock, ll_readahead_state::ras_requests, ras_reset(), and ll_readahead_state::ras_rpc_size.
Referenced by ll_local_open().
int ll_readpage (struct file * file, struct page * page)
Definition at line 1136 of file rw.c.
References cl_io::ci_state, CIS_IO_GOING, cl_page_assume(), cl_page_find(), cl_page_put(), cl_page::cp_type, CPT_CACHEABLE, ENTRY, LASSERT, ll_cl_context::lcc_env, ll_cl_context::lcc_io, likely, ll_cl_find(), ll_i2info(), ll_io_read_page(), ll_inode_info::lli_clob, and RETURN.
int ll_release_openhandle (struct dentry * dentry, struct lookup_intent * it)
Close inode open handle.
Parameters:
dentry [in] dentry which contains the inode
it [in,out] intent which contains open info and result
Return values:
0 success
<0 failure
Definition at line 1719 of file file.c.
References DISP_ENQ_OPEN_REF, DISP_OPEN_OPEN, ENTRY, GOTO, it_clear_disposition(), it_disposition(), it_open_error(), lookup_intent::it_request, LASSERT, ll_close_inode_openhandle(), ll_i2sbi(), ll_och_fill(), OBD_ALLOC, ptlrpc_req_finished(), and RETURN.
Referenced by ll_file_open(), ll_intent_file_open(), ll_lookup_it(), and ll_lov_setstripe_ea_info().
void ll_release_page (struct inode * inode, struct page * page, bool remove)
Definition at line 164 of file dir.c.
References likely, ll_i2info(), and truncate_complete_page().
Referenced by is_first_dirent(), ll_dir_read(), and ll_statahead_thread().
int ll_remount_fs (struct super_block * sb, int * flags, char * data)
Definition at line 2209 of file llite_lib.c.
References KEY_READ_ONLY, LCONSOLE_WARN, ll_sb_info::ll_flags, ll_sb_info::ll_md_exp, ll_s2sbi, LL_SBI_VERBOSE, and obd_set_info_async().
int ll_removexattr (struct dentry * dentry, const char * name)
Definition at line 342 of file xattr.c.
References CDEBUG, D_VFSTRACE, DFID, LASSERT, ll_i2sbi(), ll_inode2fid(), ll_setxattr_common(), ll_stats_ops_tally(), LPROC_LL_REMOVEXATTR, OBD_MD_FLXATTRRM, and PFID.
int ll_revalidate_it_finish (struct ptlrpc_request * request, struct lookup_intent * it, struct dentry * de)
Definition at line 281 of file dcache.c.
References DISP_LOOKUP_NEG, ENTRY, it_disposition(), ll_prep_inode(), and RETURN.
Referenced by __ll_inode_revalidate().
int ll_rmdir_entry (struct inode * dir, char * name, int namelen)
Remove dir entry.
Definition at line 1243 of file namei.c.
References CDEBUG, CLI_RM_ENTRY, D_VFSTRACE, DFID, ENTRY, ll_finish_md_op_data(), ll_i2sbi(), ll_inode2fid(), ll_prep_md_op_data(), ll_stats_ops_tally(), ll_update_times(), LPROC_LL_RMDIR, LUSTRE_OPC_ANY, md_unlink(), md_op_data::op_cli_flags, md_op_data::op_data, PFID, ptlrpc_req_finished(), and RETURN.
Referenced by ll_dir_ioctl().
void ll_rw_stats_tally (struct ll_sb_info * sbi, pid_t pid, struct ll_file_data * file, loff_t pos, size_t count, int rw)
Referenced by vvp_io_read_start(), and vvp_io_write_start().
static struct obd_export* ll_s2dtexp (struct super_block * sb) [static, read]
Definition at line 1070 of file llite_internal.h.
References ll_s2sbi.
Referenced by ll_i2dtexp().
static struct obd_export* ll_s2mdexp (struct super_block * sb) [static, read]
Definition at line 1076 of file llite_internal.h.
References ll_s2sbi.
Referenced by ll_i2mdexp().
int ll_set_default_mdsize (struct ll_sb_info * sbi, int lmmsize)
Set the default_easize parameter to the given value.
See also:
client_obd::cl_default_mds_easize
Parameters:
[in] sbi superblock info for this filesystem
[in] lmmsize the size to set
Return values:
0 on success
negative negated errno on failure
Definition at line 673 of file llite_lib.c.
References KEY_DEFAULT_EASIZE, ll_sb_info::ll_md_exp, lov_mds_md, OBD_MAX_DEFAULT_EA_SIZE, obd_set_info_async(), and RETURN.
static void ll_set_lock_data (struct obd_export * exp, struct inode * inode, struct lookup_intent * it, __u64 * bits) [inline, static]
Definition at line 1379 of file llite_internal.h.
References CDEBUG, lustre_handle::cookie, D_DLMTRACE, DFID, lookup_intent::it_lock_bits, lookup_intent::it_lock_handle, lookup_intent::it_lock_set, lookup_intent::it_remote_lock_handle, lookup_intent::it_remote_lock_mode, ll_inode2fid(), LPX64, md_set_lock_data(), and PFID.
Referenced by ll_create_node(), ll_intent_file_open(), ll_layout_refresh_locked(), ll_lease_open(), ll_lookup_finish_locks(), ll_lookup_it_finish(), ll_xattr_cache_refill(), and sa_instantiate().
int ll_setattr (struct dentry * de, struct iattr * attr)
Definition at line 1727 of file llite_lib.c.
References ll_setattr_raw(), MDS_OPEN_OWNEROVERRIDE, and mode.
int ll_setattr_raw (struct dentry * dentry, struct iattr * attr, bool hsm_import)
Definition at line 1574 of file llite_lib.c.
References ATTR_CTIME_SET, CDEBUG, CFS_CAP_FOWNER, cfs_capable(), cfs_time_current_sec(), cl_setattr_ost(), D_INFO, D_INODE, D_VFSTRACE, DFID, ENTRY, EXIT, GOTO, HS_DIRTY, HSS_SETMASK, hsm_state_set::hss_valid, inode_dio_wait, inode_dio_write_done, ll_file_clear_flag(), ll_file_maxbytes(), ll_file_test_and_clear_flag(), ll_finish_md_op_data(), ll_get_fsname(), ll_hsm_state_set(), ll_i2info(), ll_i2sbi(), ll_inode2fid(), ll_md_setattr(), ll_stats_ops_tally(), ll_inode_info::lli_clob, ll_inode_info::lli_fid, LLIF_DATA_MODIFIED, LPROC_LL_SETATTR, LPROC_LL_TRUNC, LPU64, LTIME_S, MDS_DATA_MODIFIED, MDS_OPEN_OWNEROVERRIDE, OBD_ALLOC_PTR, md_op_data::op_attr, md_op_data::op_bias, md_op_data::op_data, PFID, RETURN, TIMES_SET_FLAGS, and uid_eq().
Referenced by ll_file_futimes_3(), ll_hsm_import(), and ll_setattr().
int ll_setxattr (struct dentry * dentry, const char * name, const void * value, size_t size, int flags)
Definition at line 265 of file xattr.c.
References __u64, CDEBUG, D_VFSTRACE, DFID, FMODE_WRITE, get_hsm_state(), HS_ARCHIVED, HS_NONE, LASSERT, ll_dir_setstripe(), ll_i2sbi(), ll_inode2fid(), ll_lov_setstripe_ea_info(), ll_lov_user_md_size(), ll_setxattr_common(), ll_stats_ops_tally(), LOV_PATTERN_F_RELEASED, lov_user_md, LPROC_LL_SETXATTR, OBD_MD_FLXATTR, PFID, RETURN, state, XATTR_LUSTRE_PREFIX, XATTR_NAME_LINK, XATTR_NAME_LMA, and XATTR_TRUSTED_PREFIX.
Referenced by ll_init_security().
int ll_show_options (struct seq_file * seq, struct vfsmount * vfs)
Definition at line 2515 of file llite_lib.c.
References LASSERT, ll_sb_info::ll_flags, ll_s2sbi, LL_SBI_ALWAYS_PING, LL_SBI_FLOCK, LL_SBI_LAZYSTATFS, LL_SBI_LOCALFLOCK, LL_SBI_NOLCK, LL_SBI_USER_FID2PATH, LL_SBI_USER_XATTR, and RETURN.
struct dentry* ll_splice_alias (struct inode * inode, struct dentry * de) [read]
Definition at line 431 of file namei.c.
References CDEBUG, D_DENTRY, ll_d_count, ll_d_init(), and ll_find_alias().
Referenced by ll_lookup_it_finish(), and revalidate_statahead_dentry().
int ll_statahead (struct inode * dir, struct dentry ** dentryp, bool unplug)
statahead entry function, this is called when client getattr on a file, it will start statahead thread if this is the first dir entry, else revalidate dentry from statahead cache.
Parameters:
[in] dir parent directory
[out] dentryp dentry to getattr
[in] unplug unplug statahead window only (normally for negative dentry)
Return values:
1 on success
0 revalidation from statahead cache failed, caller needs to getattr from server directly
negative number on error, caller often ignores this and then getattr from server
Definition at line 1624 of file statahead.c.
References CDEBUG, D_READA, ll_sai_get(), ll_sai_put(), revalidate_statahead_dentry(), and start_statahead_thread().
Referenced by ll_lookup_it(), and ll_revalidate_dentry().
int ll_statfs (struct dentry * de, struct kstatfs * sfs)
Definition at line 1806 of file llite_lib.c.
References __u64, CDEBUG, cfs_time_shift_64(), D_VFSTRACE, ll_s2sbi, ll_statfs_internal(), ll_stats_ops_tally(), LPROC_LL_STAFS, LPU64, OBD_STATFS_CACHE_SECONDS, obd_statfs::os_bavail, obd_statfs::os_bfree, obd_statfs::os_blocks, and statfs_unpack().
int ll_statfs_internal (struct super_block * sb, struct obd_statfs * osfs, __u64 max_age, __u32 flags)
Definition at line 1757 of file llite_lib.c.
References CDEBUG, CERROR, D_SUPER, ENTRY, ll_sb_info::ll_dt_exp, ll_sb_info::ll_flags, ll_sb_info::ll_md_exp, ll_s2sbi, LL_SBI_LAZYSTATFS, LPU64, obd_statfs(), OBD_STATFS_NODELAY, obd_statfs_rqset(), obd_statfs::os_bavail, obd_statfs::os_bfree, obd_statfs::os_blocks, obd_statfs::os_bsize, obd_statfs::os_ffree, obd_statfs::os_files, obd_statfs::os_type, and RETURN.
Referenced by ll_statfs().
static void ll_stats_ops_tally (struct ll_sb_info * sbi, int op, int count) [static]
Definition at line 737 of file llite_internal.h.
Referenced by do_bio_lustrebacked(), ll_alloc_inode(), ll_create_nd(), ll_dir_ioctl(), ll_file_flock(), ll_file_io_generic(), ll_file_ioctl(), ll_file_mmap(), ll_file_open(), ll_file_release(), ll_file_seek(), ll_fsync(), ll_getattr(), ll_getxattr(), ll_inode_permission(), ll_link(), ll_listxattr(), ll_mkdir(), ll_mknod(), ll_readdir(), ll_removexattr(), ll_rename(), ll_rmdir(), ll_rmdir_entry(), ll_setattr_raw(), ll_setxattr(), ll_statfs(), ll_symlink(), ll_unlink(), ll_xattr_cache_get(), and ll_xattr_cache_refill().
enum ldlm_mode ll_take_md_lock (struct inode * inode, __u64 bits, struct lustre_handle * lockh, __u64 flags, enum ldlm_mode mode)
Definition at line 3279 of file file.c.
References CDEBUG, D_INFO, DFID, ENTRY, ldlm_policy_data::l_inodebits, LDLM_FL_BLOCK_GRANTED, LDLM_IBITS, ll_i2info(), ll_i2mdexp(), ll_inode_info::lli_fid, md_lock_match(), PFID, and RETURN.
Referenced by ll_layout_refresh_locked(), and ll_xattr_find_get_lock().
int ll_teardown_mmaps (struct address_space * mapping, __u64 first, __u64 last)
Definition at line 463 of file llite_mmap.c.
References ENTRY, LASSERTF, LPU64, and RETURN.
Referenced by ll_invalidate_page().
int ll_test_inode_by_fid (struct inode * inode, void * opaque)
Definition at line 182 of file namei.c.
References ll_i2info(), and lu_fid_eq().
Referenced by ll_md_blocking_ast(), and search_inode_for_lustre().
void ll_umount_begin (struct super_block * sb)
Definition at line 2162 of file llite_lib.c.
References CDEBUG, CERROR, class_exp2obd(), D_VFSTRACE, ENTRY, EXIT, obd_export::exp_handle, portals_handle::h_cookie, IOC_OSC_SET_ACTIVE, ll_sb_info::ll_dt_exp, ll_sb_info::ll_md_exp, ll_s2sbi, LPX64, OBD_ALLOC_PTR, obd_device::obd_force, OBD_FREE_PTR, and obd_iocontrol().
static void ll_unlock_dcache (struct inode * inode) [inline, static]
Definition at line 1425 of file llite_internal.h.
Referenced by __ll_inode_revalidate(), ll_find_alias(), ll_invalidate_aliases(), and ll_invalidate_negative_children().
int ll_update_inode (struct inode * inode, struct lustre_md * md)
Definition at line 1865 of file llite_lib.c.
References lustre_md::body, CDEBUG, cl_fid_build_gen(), cl_fid_build_ino(), cl_file_inode_init(), D_INODE, D_VFSTRACE, DFID, fid_is_sane(), LASSERT, LASSERTF, ll_file_clear_flag(), ll_file_set_flag(), ll_sb_info::ll_flags, ll_i2info(), ll_i2sbi(), ll_inode2fid(), LL_MAX_BLKSIZE_BITS, LL_SBI_32BIT_API, LL_SBI_RMT_CLIENT, ll_update_lsm_md(), ll_update_remote_perm(), ll_inode_info::lli_atime, ll_inode_info::lli_ctime, ll_inode_info::lli_fid, ll_inode_info::lli_lock, ll_inode_info::lli_mtime, ll_inode_info::lli_posix_acl, LLIF_FILE_RESTORING, LPU64, LTIME_S, lu_fid_eq(), make_kgid(), make_kuid(), mdt_body::mbo_atime, mdt_body::mbo_blocks, mdt_body::mbo_ctime, mdt_body::mbo_fid1, mdt_body::mbo_flags, mdt_body::mbo_gid, mdt_body::mbo_mode, mdt_body::mbo_mtime, mdt_body::mbo_nlink, mdt_body::mbo_rdev, mdt_body::mbo_size, mdt_body::mbo_t_state, mdt_body::mbo_uid, mdt_body::mbo_valid, MS_RESTORE, OBD_MD_FLACL, OBD_MD_FLATIME, OBD_MD_FLBLOCKS, OBD_MD_FLCTIME, OBD_MD_FLEASIZE, OBD_MD_FLFLAGS, OBD_MD_FLGID, OBD_MD_FLID, OBD_MD_FLMODE, OBD_MD_FLMTIME, OBD_MD_FLNLINK, OBD_MD_FLRDEV, OBD_MD_FLRMTPERM, OBD_MD_FLSIZE, OBD_MD_FLTYPE, OBD_MD_FLUID, OBD_MD_TSTATE, PFID, PTLRPC_MAX_BRW_BITS, lustre_md::remote_perm, and set_nlink().
Referenced by ll_iget(), ll_md_setattr(), ll_prep_inode(), and ll_read_inode2().
int ll_update_remote_perm (struct inode * inode, struct mdt_remote_perm * perm)
Definition at line 169 of file remote_perm.c.
References alloc_ll_remote_perm(), alloc_rmtperm_hash(), CDEBUG, CERROR, cfs_hlist_for_each_entry, cfs_time_current(), D_SEC, ENTRY, free_ll_remote_perm(), free_rmtperm_hash(), head, hlist_add_head(), LASSERT, ll_i2info(), ll_i2sbi(), LL_SBI_RMT_CLIENT, ll_inode_info::lli_lock, ll_inode_info::lli_remote_perms, ll_inode_info::lli_rmtperm_time, ll_remote_perm::lrp_access_perm, ll_remote_perm::lrp_fsgid, ll_remote_perm::lrp_fsuid, ll_remote_perm::lrp_gid, ll_remote_perm::lrp_list, ll_remote_perm::lrp_uid, remote_perm_hashfunc(), RETURN, mdt_remote_perm::rp_access_perm, mdt_remote_perm::rp_fsgid, mdt_remote_perm::rp_fsuid, mdt_remote_perm::rp_gid, and mdt_remote_perm::rp_uid.
Referenced by ll_update_inode(), and lustre_check_remote_perm().
void ll_update_times (struct ptlrpc_request * request, struct inode * inode)
Definition at line 927 of file namei.c.
References CDEBUG, D_INODE, DFID, LASSERT, ll_inode2fid(), LPU64, LTIME_S, mdt_body::mbo_ctime, mdt_body::mbo_mtime, mdt_body::mbo_valid, OBD_MD_FLCTIME, OBD_MD_FLMTIME, PFID, req_capsule_server_get(), RMF_MDT_BODY, and ptlrpc_request::rq_pill.
Referenced by ll_link(), ll_migrate(), ll_new_node(), ll_rename(), ll_rmdir(), ll_rmdir_entry(), and ll_unlink().
int ll_writepage (struct page * page, struct writeback_control * wbc)
Definition at line 887 of file rw.c.
References cl_io::ci_ignore_layout, cl_io::ci_obj, CIT_MISC, cl_env_nested_get(), cl_env_nested_put(), CL_FSYNC_LOCAL, cl_io_fini(), cl_io_init(), cl_offset(), cl_page_assume(), cl_page_disown(), cl_page_find(), cl_page_flush(), cl_page_put(), cl_sync_file_range(), cl_page::cp_reference, CPT_CACHEABLE, ENTRY, GOTO, LASSERT, ll_i2dtexp(), ll_i2info(), ll_inode_info::lli_async_rc, ll_inode_info::lli_clob, lu_ref_add(), lu_ref_del(), and vvp_env_thread_io().
int ll_writepages (struct address_space * , struct writeback_control * wbc)
Definition at line 981 of file rw.c.
References CL_FSYNC_LOCAL, CL_FSYNC_NONE, cl_sync_file_range(), end, ENTRY, ll_i2info(), ll_i2sbi(), ll_sb_info::ll_umounting, mode, OBD_OBJECT_EOF, RETURN, and start.
int ll_xattr_cache_destroy (struct inode * inode)
Definition at line 286 of file xattr_cache.c.
References ENTRY, ll_i2info(), ll_xattr_cache_destroy_locked(), ll_inode_info::lli_xattrs_list_rwsem, and RETURN.
Referenced by ll_clear_inode(), and ll_md_blocking_ast().
int ll_xattr_cache_get (struct inode * inode, const char * name, char * buffer, size_t size, __u64 valid)
Definition at line 522 of file xattr_cache.c.
References ENTRY, GOTO, IT_GETXATTR, lookup_intent::it_op, LASSERT, ll_i2info(), ll_i2sbi(), ll_stats_ops_tally(), ll_xattr_cache_find(), ll_xattr_cache_list(), ll_xattr_cache_refill(), ll_xattr_cache_valid(), ll_inode_info::lli_xattrs, ll_inode_info::lli_xattrs_list_rwsem, LPROC_LL_GETXATTR_HITS, OBD_MD_FLXATTR, OBD_MD_FLXATTRLS, RETURN, ll_xattr_entry::xe_vallen, and ll_xattr_entry::xe_value.
Referenced by ll_getxattr_common().
void ll_xattr_fini (void)
Definition at line 72 of file xattr_cache.c.
References lu_kmem_fini().
Referenced by lustre_exit().
int ll_xattr_init (void)
Definition at line 67 of file xattr_cache.c.
References lu_kmem_init().
Referenced by lustre_init().
static int lprocfs_register_mountpoint (struct proc_dir_entry * parent, struct super_block * sb, char * osc, char * mdc) [inline, static]
Definition at line 734 of file llite_internal.h.
Referenced by client_common_fill_super().
static void lprocfs_unregister_mountpoint (struct ll_sb_info * sbi) [inline, static]
Definition at line 736 of file llite_internal.h.
Referenced by client_common_put_super().
int lustre_check_remote_perm (struct inode * inode, int mask)
Definition at line 256 of file remote_perm.c.
References CERROR, do_check_remote_perm(), ENTRY, LBUG, ll_i2info(), ll_i2sbi(), ll_i2suppgid(), ll_inode2fid(), ll_sb_info::ll_md_exp, ll_update_remote_perm(), ll_inode_info::lli_rmtperm_mutex, ll_inode_info::lli_rmtperm_time, lustre_swab_mdt_remote_perm(), md_get_remote_perm(), ptlrpc_req_finished(), req_capsule_server_swab_get(), RETURN, RMF_ACL, ptlrpc_request::rq_pill, and unlikely.
Referenced by ll_inode_permission().
void lustre_dump_dentry (struct dentry * , int recur)
Definition at line 705 of file llite_lib.c.
References CERROR, d_child, LASSERT, list_entry, list_for_each, ll_d_count, ll_dump_inode(), and lustre_dump_dentry().
Referenced by ll_invalidate_aliases(), and lustre_dump_dentry().
struct vm_area_struct* our_vma (struct mm_struct * mm, unsigned long addr, size_t count) [read]
Definition at line 68 of file llite_mmap.c.
References ENTRY, LASSERT, ll_file_vm_ops, ret, and RETURN.
Referenced by vvp_mmap_locks().
void policy_from_vma (union ldlm_policy_data * policy, struct vm_area_struct * vma, unsigned long addr, size_t count)
Definition at line 59 of file llite_mmap.c.
References ldlm_extent::end, ldlm_policy_data::l_extent, and ldlm_extent::start.
Referenced by vvp_mmap_locks().
static struct client_obd* sbi2mdc (struct ll_sb_info * sbi) [static, read]
Definition at line 1081 of file llite_internal.h.
References obd_device::cli, obd_export::exp_obd, LBUG, ll_sb_info::ll_md_exp, and obd_device::u.
struct inode* search_inode_for_lustre (struct super_block * sb, const struct lu_fid * fid) [read]
Definition at line 60 of file llite_nfs.c.
References CDEBUG, cl_fid_build_ino(), D_INFO, DFID, ENTRY, ll_get_default_mdsize(), ll_sb_info::ll_md_exp, ll_need_32bit_api(), ll_prep_inode(), ll_s2sbi, ll_test_inode_by_fid(), md_getattr(), OBD_ALLOC_PTR, OBD_FREE_PTR, OBD_MD_FLEASIZE, md_op_data::op_data, md_op_data::op_fid1, md_op_data::op_mode, md_op_data::op_valid, PFID, ptlrpc_req_finished(), and RETURN.
Referenced by ll_dir_ioctl(), ll_iget_for_nfs(), ll_ioc_copy_end(), and ll_ioc_copy_start().
int vvp_io_write_commit (const struct lu_env * env, struct cl_io * io)
Definition at line 968 of file vvp_io.c.
Referenced by ll_write_begin(), ll_write_end(), and vvp_io_write_start().
Variable Documentation
struct lu_env* cl_inode_fini_env
An `emergency' environment used by cl_inode_fini() when cl_env_get() fails.
Access to this environment is serialized by cl_inode_fini_guard mutex.
Definition at line 66 of file lcommon_cl.c.
Referenced by lustre_exit(), and lustre_init().
__u16 cl_inode_fini_refcheck
Definition at line 67 of file lcommon_cl.c.
Referenced by lustre_exit(), and lustre_init().
spinlock_t inode_lock
struct address_space_operations ll_aops
Definition at line 809 of file rw26.c.
Referenced by ll_read_inode2().
struct dentry_operations ll_d_ops
Definition at line 394 of file dcache.c.
Referenced by client_common_fill_super(), ll_d_init(), and ll_fill_super().
struct inode_operations ll_dir_inode_operations
Definition at line 1360 of file namei.c.
Referenced by ll_iget_anon_dir(), and ll_read_inode2().
struct file_operations ll_dir_operations
Definition at line 1790 of file dir.c.
Referenced by ll_iget_anon_dir(), and ll_read_inode2().
struct inode_operations ll_fast_symlink_inode_operations
Definition at line 193 of file symlink.c.
Referenced by ll_read_inode2().
struct kmem_cache* ll_file_data_slab
Definition at line 65 of file llite_lib.c.
Referenced by ll_file_data_get(), ll_file_data_put(), lustre_exit(), and lustre_init().
struct inode_operations ll_file_inode_operations
Definition at line 3757 of file file.c.
Referenced by ll_read_inode2().
struct file_operations ll_file_operations
Definition at line 3680 of file file.c.
Referenced by client_common_fill_super().
struct file_operations ll_file_operations_flock
Definition at line 3704 of file file.c.
Referenced by client_common_fill_super().
struct file_operations ll_file_operations_noflock
Definition at line 3731 of file file.c.
Referenced by client_common_fill_super().
struct kmem_cache* ll_remote_perm_cachep
Definition at line 63 of file remote_perm.c.
Referenced by alloc_ll_remote_perm(), free_ll_remote_perm(), lustre_exit(), and lustre_init().
struct kmem_cache* ll_rmtperm_hash_cachep
Definition at line 64 of file remote_perm.c.
Referenced by alloc_rmtperm_hash(), free_rmtperm_hash(), lustre_exit(), and lustre_init().
struct inode_operations ll_special_inode_operations
Definition at line 1386 of file namei.c.
Referenced by ll_read_inode2().
struct lu_context_key ll_thread_key
Definition at line 116 of file vvp_dev.c.
Referenced by ll_env_info().
enum llioc_iter(* llioc_callback_t)(struct inode *inode, struct file *file, unsigned int cmd, unsigned long arg, void *magic, int *rcp)
struct export_operations lustre_export_operations
Definition at line 356 of file llite_nfs.c.
Referenced by client_common_fill_super().
struct super_operations lustre_super_operations
Definition at line 85 of file super25.c.
Referenced by client_common_fill_super(), and lustre_init().
struct proc_dir_entry* proc_lustre_fs_root
Definition at line 50 of file lproc_llite.c.
Referenced by client_common_fill_super(), lustre_exit(), and lustre_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.