Lustre: lustre/obdclass/llog_obd.c File Reference
lustre/obdclass/llog_obd.c File Reference
#include <obd_class.h>
#include <lustre_log.h>
#include "llog_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LOG
Functions
static struct llog_ctxt * llog_new_ctxt (struct obd_device *obd)
static void llog_ctxt_destroy (struct llog_ctxt *ctxt)
int __llog_ctxt_put (const struct lu_env *env, struct llog_ctxt *ctxt)
int llog_cleanup (const struct lu_env *env, struct llog_ctxt *ctxt)
int llog_setup (const struct lu_env *env, struct obd_device *obd, struct obd_llog_group *olg, int index, struct obd_device *disk_obd, struct llog_operations *op)
int llog_sync (struct llog_ctxt *ctxt, struct obd_export *exp, int flags)
int llog_cancel (const struct lu_env *env, struct llog_ctxt *ctxt, struct llog_cookie *cookies, int flags)
LU_KEY_INIT_FINI (llog, struct llog_thread_info)
LU_CONTEXT_KEY_DEFINE (llog, LCT_MD_THREAD|LCT_MG_THREAD|LCT_LOCAL)
LU_KEY_INIT_GENERIC (llog)
int llog_info_init (void)
void llog_info_fini (void)
Define Documentation
#define DEBUG_SUBSYSTEM S_LOG
Definition at line 37 of file llog_obd.c.
Function Documentation
static void llog_ctxt_destroy (struct llog_ctxt * ctxt) [static]
Definition at line 59 of file llog_obd.c.
References class_export_put(), class_import_put(), llog_ctxt::loc_exp, llog_ctxt::loc_imp, and OBD_FREE_PTR.
Referenced by __llog_ctxt_put(), and llog_setup().
void llog_info_fini (void)
Definition at line 267 of file llog_obd.c.
References llog_thread_key, and lu_context_key_degister().
Referenced by obdclass_exit().
int llog_info_init (void)
Definition at line 260 of file llog_obd.c.
References llog_thread_key, and lu_context_key_register().
Referenced by obdclass_init().
static struct llog_ctxt* llog_new_ctxt (struct obd_device * obd) [static, read]
Definition at line 45 of file llog_obd.c.
References llog_ctxt::loc_obd, llog_ctxt::loc_refcount, and OBD_ALLOC_PTR.
Referenced by llog_setup().
LU_CONTEXT_KEY_DEFINE (llog , LCT_MD_THREAD|LCT_MG_THREAD| LCT_LOCAL)
LU_KEY_INIT_FINI (llog , struct llog_thread_info)
LU_KEY_INIT_GENERIC (llog)
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.