Lustre: lustre/obdclass/llog_ioctl.c File Reference
lustre/obdclass/llog_ioctl.c File Reference
#include <obd_class.h>
#include <lustre_ioctl.h>
#include <lustre_log.h>
#include "llog_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LOG
Functions
static int str2logid (struct llog_logid *logid, char *str, int len)
static int llog_check_cb (const struct lu_env *env, struct llog_handle *handle, struct llog_rec_hdr *rec, void *data)
static int llog_print_cb (const struct lu_env *env, struct llog_handle *handle, struct llog_rec_hdr *rec, void *data)
static int llog_remove_log (const struct lu_env *env, struct llog_handle *cat, struct llog_logid *logid)
static int llog_delete_cb (const struct lu_env *env, struct llog_handle *handle, struct llog_rec_hdr *rec, void *data)
int llog_ioctl (const struct lu_env *env, struct llog_ctxt *ctxt, int cmd, struct obd_ioctl_data *data)
int llog_catalog_list (const struct lu_env *env, struct dt_device *d, int count, struct obd_ioctl_data *data, const struct lu_fid *fid)
Define Documentation
#define DEBUG_SUBSYSTEM S_LOG
Definition at line 37 of file llog_ioctl.c.
Function Documentation
static int llog_check_cb (const struct lu_env * env, struct llog_handle * handle, struct llog_rec_hdr * rec, void * data) [static]
Definition at line 91 of file llog_ioctl.c.
References CDEBUG, CERROR, cfs_size_round(), D_IOCTL, DOSTID, ENTRY, obd_ioctl_data::ioc_bulk, obd_ioctl_data::ioc_inlbuf2, obd_ioctl_data::ioc_inlbuf3, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, obd_ioctl_data::ioc_inllen3, obd_ioctl_data::ioc_inllen4, llog_handle::lgh_ctxt, llog_handle::lgh_hdr, llog_logid::lgl_ogen, llog_logid::lgl_oi, llog_logid_rec::lid_id, llog_log_hdr::llh_flags, llog_cat_id2handle(), LLOG_EEMPTY, LLOG_F_IS_CAT, LLOG_GEN_REC, llog_handle_put(), LLOG_HDR_MAGIC, LLOG_LOGID_MAGIC, llog_process(), llog_ctxt::loc_obd, llog_rec_hdr::lrh_index, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, MDS_SETATTR64_REC, MDS_UNLINK64_REC, MDS_UNLINK_REC, OBD_CFG_REC, obd_device::obd_name, OST_SZ_REC, POSTID, and RETURN.
Referenced by llog_ioctl().
static int llog_delete_cb (const struct lu_env * env, struct llog_handle * handle, struct llog_rec_hdr * rec, void * data) [static]
Definition at line 271 of file llog_ioctl.c.
References ENTRY, llog_logid_rec::lid_id, LLOG_LOGID_MAGIC, llog_remove_log(), llog_rec_hdr::lrh_type, and RETURN.
Referenced by llog_ioctl().
static int llog_print_cb (const struct lu_env * env, struct llog_handle * handle, struct llog_rec_hdr * rec, void * data) [static]
Definition at line 178 of file llog_ioctl.c.
References CERROR, cfs_size_round(), class_config_yaml_output(), DOSTID, ENTRY, obd_ioctl_data::ioc_bulk, obd_ioctl_data::ioc_inlbuf2, obd_ioctl_data::ioc_inlbuf3, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, obd_ioctl_data::ioc_inllen3, obd_ioctl_data::ioc_inllen4, llog_handle::lgh_hdr, llog_logid::lgl_ogen, llog_logid::lgl_oi, llog_logid_rec::lid_id, llog_log_hdr::llh_flags, LLOG_EEMPTY, LLOG_F_IS_CAT, LLOG_LOGID_MAGIC, llog_rec_hdr::lrh_index, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, OBD_CFG_REC, POSTID, and RETURN.
Referenced by llog_ioctl().
static int llog_remove_log (const struct lu_env * env, struct llog_handle * cat, struct llog_logid * logid) [static]
Definition at line 244 of file llog_ioctl.c.
References CDEBUG, D_IOCTL, DOSTID, ENTRY, GOTO, llog_cookie::lgc_index, llog_logid::lgl_ogen, llog_logid::lgl_oi, llog_cat_cleanup(), llog_cat_id2handle(), llog_destroy(), llog_handle_put(), llog_handle::phd, plain_handle_data::phd_cookie, POSTID, RETURN, and llog_handle::u.
Referenced by llog_delete_cb(), and llog_ioctl().
static int str2logid (struct llog_logid * logid, char * str, int len) [static]
Definition at line 44 of file llog_ioctl.c.
References __u64, end, ENTRY, llog_logid::lgl_ogen, llog_logid::lgl_oi, ostid_set_id(), ostid_set_seq(), RETURN, and start.
Referenced by llog_ioctl().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.