Lustre: lustre/ptlrpc/llog_client.c File Reference
lustre/ptlrpc/llog_client.c File Reference
#include <libcfs/libcfs.h>
#include <obd_class.h>
#include <lustre_log.h>
#include <lustre_net.h>
#include <libcfs/list.h>
Defines
#define DEBUG_SUBSYSTEM S_LOG
#define LLOG_CLIENT_ENTRY(ctxt, imp)
#define LLOG_CLIENT_EXIT(ctxt, imp)
Functions
static int llog_client_open (const struct lu_env *env, struct llog_handle *lgh, struct llog_logid *logid, char *name, enum llog_open_param open_param)
static int llog_client_destroy (const struct lu_env *env, struct llog_handle *loghandle, struct thandle *th)
static int llog_client_next_block (const struct lu_env *env, struct llog_handle *loghandle, int *cur_idx, int next_idx, __u64 *cur_offset, void *buf, int len)
static int llog_client_prev_block (const struct lu_env *env, struct llog_handle *loghandle, int prev_idx, void *buf, int len)
static int llog_client_read_header (const struct lu_env *env, struct llog_handle *handle)
static int llog_client_close (const struct lu_env *env, struct llog_handle *handle)
Variables
struct llog_operations llog_client_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_LOG
Definition at line 43 of file llog_client.c.
#define LLOG_CLIENT_ENTRY (ctxt, imp)
Value:
do {                             \
        mutex_lock(&ctxt->loc_mutex);                             \
        if (ctxt->loc_imp) {                                          \
                imp = class_import_get(ctxt->loc_imp);                \
        } else {                                                      \
                CERROR("ctxt->loc_imp == NULL for context idx %d."    \
                       "Unable to complete MDS/OSS recovery,"         \
                       "but I'll try again next time.  Not fatal.\n", \
                       ctxt->loc_idx);                                \
                imp = NULL;                                           \
                mutex_unlock(&ctxt->loc_mutex);                   \
                return (-EINVAL);                                     \
        }                                                             \
        mutex_unlock(&ctxt->loc_mutex);                           \
} while(0)
Definition at line 52 of file llog_client.c.
Referenced by llog_client_destroy(), llog_client_next_block(), llog_client_open(), llog_client_prev_block(), and llog_client_read_header().
#define LLOG_CLIENT_EXIT (ctxt, imp)
Value:
do {                              \
        mutex_lock(&ctxt->loc_mutex);                             \
        if (ctxt->loc_imp != imp)                                     \
                CWARN("loc_imp has changed from %p to %p\n",          \
                       ctxt->loc_imp, imp);                           \
        class_import_put(imp);                                        \
        mutex_unlock(&ctxt->loc_mutex);                           \
} while(0)
Definition at line 68 of file llog_client.c.
Referenced by llog_client_destroy(), llog_client_next_block(), llog_client_open(), llog_client_prev_block(), and llog_client_read_header().
Function Documentation
static int llog_client_close (const struct lu_env * env, struct llog_handle * handle) [static]
Definition at line 346 of file llog_client.c.
static int llog_client_destroy (const struct lu_env * env, struct llog_handle * loghandle, struct thandle * th) [static]
Definition at line 143 of file llog_client.c.
References CERROR, ENTRY, GOTO, obd_import::imp_obd, llogd_body::lgd_llh_flags, llogd_body::lgd_logid, llog_handle::lgh_ctxt, llog_handle::lgh_hdr, llog_handle::lgh_id, llog_log_hdr::llh_flags, LLOG_CLIENT_ENTRY, LLOG_CLIENT_EXIT, LLOG_F_IS_PLAIN, LLOG_ORIGIN_HANDLE_DESTROY, LUSTRE_LOG_VERSION, obd_device::obd_name, ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc_pack(), ptlrpc_request_set_replen(), req_capsule_client_get(), RETURN, RMF_LLOGD_BODY, ptlrpc_request::rq_pill, and RQF_LLOG_ORIGIN_HANDLE_DESTROY.
static int llog_client_next_block (const struct lu_env * env, struct llog_handle * loghandle, int * cur_idx, int next_idx, __u64 * cur_offset, void * buf, int len) [static]
Definition at line 178 of file llog_client.c.
References ENTRY, EXIT, GOTO, llogd_body::lgd_ctxt_idx, llogd_body::lgd_cur_offset, llogd_body::lgd_index, llogd_body::lgd_len, llogd_body::lgd_llh_flags, llogd_body::lgd_logid, llogd_body::lgd_saved_index, llog_handle::lgh_ctxt, llog_handle::lgh_hdr, llog_handle::lgh_id, llog_log_hdr::llh_flags, LLOG_CLIENT_ENTRY, LLOG_CLIENT_EXIT, LLOG_ORIGIN_HANDLE_NEXT_BLOCK, llog_ctxt::loc_idx, LUSTRE_LOG_VERSION, ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc_pack(), ptlrpc_request_set_replen(), RCL_SERVER, req_capsule_client_get(), req_capsule_server_get(), req_capsule_set_size(), RMF_EADATA, RMF_LLOGD_BODY, ptlrpc_request::rq_pill, and RQF_LLOG_ORIGIN_HANDLE_NEXT_BLOCK.
static int llog_client_open (const struct lu_env * env, struct llog_handle * lgh, struct llog_logid * logid, char * name, enum llog_open_param open_param) [static]
Definition at line 79 of file llog_client.c.
References ENTRY, EXIT, GOTO, LASSERT, LASSERTF, llogd_body::lgd_ctxt_idx, llogd_body::lgd_logid, llog_handle::lgh_ctxt, llog_handle::lgh_id, LLOG_CLIENT_ENTRY, LLOG_CLIENT_EXIT, LLOG_OPEN_NEW, LLOG_ORIGIN_HANDLE_CREATE, llog_ctxt::loc_idx, LUSTRE_LOG_VERSION, ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), RCL_CLIENT, req_capsule_client_get(), req_capsule_client_sized_get(), req_capsule_server_get(), req_capsule_set_size(), RMF_LLOGD_BODY, RMF_NAME, ptlrpc_request::rq_pill, and RQF_LLOG_ORIGIN_HANDLE_CREATE.
static int llog_client_prev_block (const struct lu_env * env, struct llog_handle * loghandle, int prev_idx, void * buf, int len) [static]
Definition at line 233 of file llog_client.c.
References ENTRY, EXIT, GOTO, llogd_body::lgd_ctxt_idx, llogd_body::lgd_index, llogd_body::lgd_len, llogd_body::lgd_llh_flags, llogd_body::lgd_logid, llog_handle::lgh_ctxt, llog_handle::lgh_hdr, llog_handle::lgh_id, llog_log_hdr::llh_flags, LLOG_CLIENT_ENTRY, LLOG_CLIENT_EXIT, LLOG_ORIGIN_HANDLE_PREV_BLOCK, llog_ctxt::loc_idx, LUSTRE_LOG_VERSION, ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc_pack(), ptlrpc_request_set_replen(), RCL_SERVER, req_capsule_client_get(), req_capsule_server_get(), req_capsule_set_size(), RMF_EADATA, RMF_LLOGD_BODY, ptlrpc_request::rq_pill, and RQF_LLOG_ORIGIN_HANDLE_PREV_BLOCK.
static int llog_client_read_header (const struct lu_env * env, struct llog_handle * handle) [static]
Definition at line 282 of file llog_client.c.
References CERROR, ENTRY, EXIT, GOTO, llogd_body::lgd_ctxt_idx, llogd_body::lgd_llh_flags, llogd_body::lgd_logid, llog_handle::lgh_ctxt, llog_handle::lgh_hdr, llog_handle::lgh_hdr_size, llog_handle::lgh_id, llog_handle::lgh_last_idx, llog_log_hdr::llh_flags, llog_log_hdr::llh_hdr, LLOG_CLIENT_ENTRY, LLOG_CLIENT_EXIT, LLOG_HDR_MAGIC, LLOG_HDR_TAIL, LLOG_MIN_CHUNK_SIZE, LLOG_ORIGIN_HANDLE_READ_HEADER, llog_ctxt::loc_idx, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, LUSTRE_LOG_VERSION, ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc_pack(), ptlrpc_request_set_replen(), req_capsule_client_get(), req_capsule_server_get(), RMF_LLOG_LOG_HDR, RMF_LLOGD_BODY, ptlrpc_request::rq_pill, and RQF_LLOG_ORIGIN_HANDLE_READ_HEADER.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.