Lustre: lustre/obdclass/llog_cat.c File Reference
lustre/obdclass/llog_cat.c File Reference
#include <obd_class.h>
#include "llog_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LOG
Enumerations
enum { LLOGH_CAT, LLOGH_LOG }
lockdep markers for nested struct llog_handle::lgh_lock locking.
Functions
static int llog_cat_new_log (const struct lu_env *env, struct llog_handle *cathandle, struct llog_handle *loghandle, struct thandle *th)
int llog_cat_id2handle (const struct lu_env *env, struct llog_handle *cathandle, struct llog_handle **res, struct llog_logid *logid)
int llog_cat_close (const struct lu_env *env, struct llog_handle *cathandle)
static struct llog_handle * llog_cat_current_log (struct llog_handle *cathandle, struct thandle *th)
Return the currently active log handle.
static int llog_cat_update_header (const struct lu_env *env, struct llog_handle *cathandle)
int llog_cat_add_rec (const struct lu_env *env, struct llog_handle *cathandle, struct llog_rec_hdr *rec, struct llog_cookie *reccookie, struct thandle *th)
int llog_cat_declare_add_rec (const struct lu_env *env, struct llog_handle *cathandle, struct llog_rec_hdr *rec, struct thandle *th)
int llog_cat_add (const struct lu_env *env, struct llog_handle *cathandle, struct llog_rec_hdr *rec, struct llog_cookie *reccookie)
int llog_cat_cancel_records (const struct lu_env *env, struct llog_handle *cathandle, int count, struct llog_cookie *cookies)
static int llog_cat_process_cb (const struct lu_env *env, struct llog_handle *cat_llh, struct llog_rec_hdr *rec, void *data)
int llog_cat_process_or_fork (const struct lu_env *env, struct llog_handle *cat_llh, llog_cb_t cat_cb, llog_cb_t cb, void *data, int startcat, int startidx, bool fork)
int llog_cat_process (const struct lu_env *env, struct llog_handle *cat_llh, llog_cb_t cb, void *data, int startcat, int startidx)
static int llog_cat_size_cb (const struct lu_env *env, struct llog_handle *cat_llh, struct llog_rec_hdr *rec, void *data)
__u64 llog_cat_size (const struct lu_env *env, struct llog_handle *cat_llh)
static int llog_cat_reverse_process_cb (const struct lu_env *env, struct llog_handle *cat_llh, struct llog_rec_hdr *rec, void *data)
int llog_cat_reverse_process (const struct lu_env *env, struct llog_handle *cat_llh, llog_cb_t cb, void *data)
static int llog_cat_set_first_idx (struct llog_handle *cathandle, int idx)
int llog_cat_cleanup (const struct lu_env *env, struct llog_handle *cathandle, struct llog_handle *loghandle, int index)
Define Documentation
#define DEBUG_SUBSYSTEM S_LOG
Definition at line 49 of file llog_cat.c.
Enumeration Type Documentation
anonymous enum
lockdep markers for nested struct llog_handle::lgh_lock locking.
Enumerator:
LLOGH_CAT
LLOGH_LOG
Definition at line 312 of file llog_cat.c.
Function Documentation
int llog_cat_cleanup (const struct lu_env * env, struct llog_handle * cathandle, struct llog_handle * loghandle, int index)
Definition at line 1041 of file llog_cat.c.
References CDEBUG, llog_handle::chd, cat_handle_data::chd_current_log, D_HA, DOSTID, LASSERT, llog_cookie::lgc_index, llog_handle::lgh_id, llog_handle::lgh_lock, llog_handle::lgh_obj, llog_logid::lgl_oi, list_del_init(), llog_cancel_rec(), llog_cat_set_first_idx(), llog_close(), llog_handle::phd, plain_handle_data::phd_cookie, plain_handle_data::phd_entry, POSTID, and llog_handle::u.
Referenced by llog_cat_cancel_records(), llog_cat_close(), llog_cat_process_cb(), llog_cat_reverse_process_cb(), and llog_remove_log().
static struct llog_handle* llog_cat_current_log (struct llog_handle * cathandle, struct thandle * th) [static, read]
Return the currently active log handle.
If the current log handle doesn't have enough space left for the current record, start a new one.
If reclen is 0, we only want to know what the currently active log is, otherwise we get a lock on this log so nobody can steal our space.
Assumes caller has already pushed us into the kernel context and is locking.
NOTE: loghandle is write-locked upon successful return
Definition at line 327 of file llog_cat.c.
References CDEBUG, llog_handle::chd, cat_handle_data::chd_current_log, cat_handle_data::chd_next_log, D_INODE, ENTRY, GOTO, LASSERT, llog_handle::lgh_hdr, llog_handle::lgh_lock, llog_is_full(), LLOGH_CAT, LLOGH_LOG, OBD_FAIL_CHECK, OBD_FAIL_MDS_LLOG_CREATE_FAILED2, RETURN, and llog_handle::u.
Referenced by llog_cat_add_rec().
int llog_cat_id2handle (const struct lu_env * env, struct llog_handle * cathandle, struct llog_handle ** res, struct llog_logid * logid)
Definition at line 206 of file llog_cat.c.
References CERROR, llog_handle::chd, cat_handle_data::chd_head, DOSTID, ENTRY, EXIT, GOTO, llog_cookie::lgc_index, llog_cookie::lgc_lgl, llog_handle::lgh_ctxt, llog_handle::lgh_hdr, llog_handle::lgh_id, llog_handle::lgh_lock, llog_logid::lgl_ogen, llog_logid::lgl_oi, list_add_tail(), list_for_each_entry, llog_log_hdr::llh_cat_idx, llog_log_hdr::llh_flags, llog_close(), LLOG_F_EXT_MASK, LLOG_F_IS_PLAIN, llog_handle_get(), llog_init_handle(), llog_open(), LLOG_OPEN_EXISTS, llog_ctxt::loc_obd, obd_device::obd_name, ostid_id(), ostid_seq(), llog_handle::phd, plain_handle_data::phd_cat_handle, plain_handle_data::phd_cookie, plain_handle_data::phd_entry, POSTID, RETURN, and llog_handle::u.
Referenced by llog_cat_cancel_records(), llog_cat_process_cb(), llog_cat_reverse_process_cb(), llog_cat_size_cb(), llog_check_cb(), and llog_remove_log().
static int llog_cat_new_log (const struct lu_env * env, struct llog_handle * cathandle, struct llog_handle * loghandle, struct thandle * th) [static]
Definition at line 61 of file llog_cat.c.
References CDEBUG, CERROR, cfs_fail_val, CWARN, D_OTHER, dt_object::do_lu, DOSTID, dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), ENTRY, GOTO, LASSERT, llog_handle::lgh_ctxt, llog_handle::lgh_hdr, llog_handle::lgh_hdr_size, llog_handle::lgh_id, llog_handle::lgh_last_idx, llog_handle::lgh_obj, llog_thread_info::lgi_logid, llog_logid::lgl_ogen, llog_logid::lgl_oi, llog_logid_rec::lid_hdr, llog_logid_rec::lid_id, llog_log_hdr::llh_cat_idx, llog_log_hdr::llh_count, llog_log_hdr::llh_flags, llog_log_hdr::llh_tgtuuid, llog_create(), LLOG_CTXT_FLAG_NORMAL_FID, llog_declare_create(), llog_declare_write_rec(), llog_exist(), LLOG_F_IS_PLAIN, LLOG_F_ZAP_WHEN_EMPTY, LLOG_HDR_BITMAP_SIZE, llog_info(), llog_init_handle(), LLOG_LOGID_MAGIC, LLOG_NEXT_IDX, llog_trans_destroy(), llog_write_rec(), lu_object::lo_dev, llog_ctxt::loc_flags, llog_ctxt::loc_obd, llog_rec_hdr::lrh_index, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, lu2dt_dev(), OBD_FAIL_CAT_RECORDS, OBD_FAIL_CHECK, OBD_FAIL_MDS_LLOG_CREATE_FAILED, OBD_FAIL_PRECHECK, OBD_FREE_LARGE, obd_device::obd_name, out_destroy(), llog_handle::phd, plain_handle_data::phd_cookie, POSTID, RETURN, thandle::th_result, thandle::th_sync, thandle::th_wait_submit, and llog_handle::u.
Referenced by llog_cat_add_rec(), and llog_cat_declare_add_rec().
static int llog_cat_process_cb (const struct lu_env * env, struct llog_handle * cat_llh, struct llog_rec_hdr * rec, void * data) [static]
Definition at line 718 of file llog_cat.c.
References CDEBUG, CERROR, llog_handle::chd, cat_handle_data::chd_current_log, D_HA, DOSTID, ENTRY, GOTO, llog_cookie::lgc_index, llog_handle::lgh_ctxt, llog_handle::lgh_hdr, llog_handle::lgh_id, llog_handle::lgh_obj, llog_logid::lgl_ogen, llog_logid::lgl_oi, llog_logid_rec::lid_id, llog_log_hdr::llh_count, llog_log_hdr::llh_flags, llog_cat_cleanup(), llog_cat_id2handle(), LLOG_DEL_PLAIN, llog_destroy(), LLOG_F_ZAP_WHEN_EMPTY, llog_handle_put(), LLOG_LOGID_MAGIC, llog_process_or_fork(), llog_ctxt::loc_obd, llog_process_cat_data::lpcd_first_idx, llog_process_cat_data::lpcd_last_idx, llog_process_data::lpd_cb, llog_process_data::lpd_data, llog_process_data::lpd_startcat, llog_process_data::lpd_startidx, llog_rec_hdr::lrh_index, llog_rec_hdr::lrh_type, obd_device::obd_name, llog_handle::phd, plain_handle_data::phd_cookie, POSTID, RETURN, and llog_handle::u.
Referenced by llog_cat_process().
static int llog_cat_reverse_process_cb (const struct lu_env * env, struct llog_handle * cat_llh, struct llog_rec_hdr * rec, void * data) [static]
Definition at line 897 of file llog_cat.c.
References CDEBUG, CERROR, llog_handle::chd, cat_handle_data::chd_current_log, D_HA, DOSTID, GOTO, le32_to_cpu, llog_cookie::lgc_index, llog_handle::lgh_ctxt, llog_handle::lgh_hdr, llog_handle::lgh_id, llog_logid::lgl_ogen, llog_logid::lgl_oi, llog_logid_rec::lid_id, llog_log_hdr::llh_count, llog_log_hdr::llh_flags, llog_cat_cleanup(), llog_cat_id2handle(), LLOG_DEL_PLAIN, llog_destroy(), LLOG_F_ZAP_WHEN_EMPTY, llog_handle_put(), LLOG_LOGID_MAGIC, llog_reverse_process(), llog_ctxt::loc_obd, llog_process_data::lpd_cb, llog_process_data::lpd_data, llog_rec_hdr::lrh_index, llog_rec_hdr::lrh_type, obd_device::obd_name, llog_handle::phd, plain_handle_data::phd_cookie, POSTID, RETURN, and llog_handle::u.
Referenced by llog_cat_reverse_process().
static int llog_cat_set_first_idx (struct llog_handle * cathandle, int idx) [static]
Definition at line 1000 of file llog_cat.c.
References CDEBUG, D_RPCTRACE, DOSTID, ENTRY, ext2_test_bit, llog_handle::lgh_hdr, llog_handle::lgh_id, llog_handle::lgh_last_idx, llog_logid::lgl_oi, llog_log_hdr::llh_cat_idx, LLOG_HDR_BITMAP, LLOG_HDR_BITMAP_SIZE, POSTID, and RETURN.
Referenced by llog_cat_cleanup().
static int llog_cat_size_cb (const struct lu_env * env, struct llog_handle * cat_llh, struct llog_rec_hdr * rec, void * data) [static]
Definition at line 846 of file llog_cat.c.
References __u64, CDEBUG, CERROR, CWARN, D_HA, D_INFO, DOSTID, ENTRY, llog_handle::lgh_ctxt, llog_handle::lgh_id, llog_logid::lgl_ogen, llog_logid::lgl_oi, llog_logid_rec::lid_id, llog_cat_id2handle(), llog_handle_put(), LLOG_LOGID_MAGIC, llog_size(), llog_ctxt::loc_obd, llog_process_data::lpd_data, LPU64, llog_rec_hdr::lrh_index, llog_rec_hdr::lrh_type, obd_device::obd_name, POSTID, RETURN, and size.
Referenced by llog_cat_size().
static int llog_cat_update_header (const struct lu_env * env, struct llog_handle * cathandle) [static]
Definition at line 386 of file llog_cat.c.
References llog_handle::chd, cat_handle_data::chd_head, ENTRY, GOTO, llog_handle::lgh_lock, llog_handle::lgh_stale, list_for_each_entry, llog_exist(), llog_read_header(), RETURN, and llog_handle::u.
Referenced by llog_cat_declare_add_rec().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.