Lustre: lustre/ptlrpc/llog_server.c File Reference
lustre/ptlrpc/llog_server.c File Reference
#include <obd_class.h>
#include <lu_target.h>
#include <lustre_log.h>
#include <lustre_net.h>
Defines
#define DEBUG_SUBSYSTEM S_LOG
Functions
static int llog_origin_close (const struct lu_env *env, struct llog_handle *lgh)
int llog_origin_handle_open (struct ptlrpc_request *req)
int llog_origin_handle_destroy (struct ptlrpc_request *req)
int llog_origin_handle_next_block (struct ptlrpc_request *req)
int llog_origin_handle_prev_block (struct ptlrpc_request *req)
int llog_origin_handle_read_header (struct ptlrpc_request *req)
int llog_origin_handle_close (struct ptlrpc_request *req)
Define Documentation
#define DEBUG_SUBSYSTEM S_LOG
Definition at line 43 of file llog_server.c.
Function Documentation
static int llog_origin_close (const struct lu_env * env, struct llog_handle * lgh) [static]
Definition at line 50 of file llog_server.c.
References llog_handle::lgh_hdr, llog_log_hdr::llh_flags, llog_cat_close(), llog_close(), and LLOG_F_IS_CAT.
Referenced by llog_origin_handle_next_block(), llog_origin_handle_open(), llog_origin_handle_prev_block(), and llog_origin_handle_read_header().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.