Lustre: lustre/obdclass/llog.c File Reference
lustre/obdclass/llog.c File Reference
#include <linux/kthread.h>
#include <llog_swab.h>
#include <lustre_log.h>
#include <obd_class.h>
#include "llog_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LOG
Functions
static struct llog_handle * llog_alloc_handle (void)
static void llog_free_handle (struct llog_handle *loghandle)
void llog_handle_get (struct llog_handle *loghandle)
void llog_handle_put (struct llog_handle *loghandle)
static int llog_declare_destroy (const struct lu_env *env, struct llog_handle *handle, struct thandle *th)
int llog_trans_destroy (const struct lu_env *env, struct llog_handle *handle, struct thandle *th)
int llog_destroy (const struct lu_env *env, struct llog_handle *handle)
int llog_cancel_rec (const struct lu_env *env, struct llog_handle *loghandle, int index)
int llog_read_header (const struct lu_env *env, struct llog_handle *handle, const struct obd_uuid *uuid)
int llog_init_handle (const struct lu_env *env, struct llog_handle *handle, int flags, struct obd_uuid *uuid)
static int llog_process_thread (void *arg)
static int llog_process_thread_daemonize (void *arg)
int llog_process_or_fork (const struct lu_env *env, struct llog_handle *loghandle, llog_cb_t cb, void *data, void *catdata, bool fork)
int llog_process (const struct lu_env *env, struct llog_handle *loghandle, llog_cb_t cb, void *data, void *catdata)
int llog_reverse_process (const struct lu_env *env, struct llog_handle *loghandle, llog_cb_t cb, void *data, void *catdata)
int llog_exist (struct llog_handle *loghandle)
new llog API
int llog_declare_create (const struct lu_env *env, struct llog_handle *loghandle, struct thandle *th)
int llog_create (const struct lu_env *env, struct llog_handle *handle, struct thandle *th)
int llog_declare_write_rec (const struct lu_env *env, struct llog_handle *handle, struct llog_rec_hdr *rec, int idx, struct thandle *th)
int llog_write_rec (const struct lu_env *env, struct llog_handle *handle, struct llog_rec_hdr *rec, struct llog_cookie *logcookies, int idx, struct thandle *th)
int llog_add (const struct lu_env *env, struct llog_handle *lgh, struct llog_rec_hdr *rec, struct llog_cookie *logcookies, struct thandle *th)
int llog_declare_add (const struct lu_env *env, struct llog_handle *lgh, struct llog_rec_hdr *rec, struct thandle *th)
int llog_open_create (const struct lu_env *env, struct llog_ctxt *ctxt, struct llog_handle **res, struct llog_logid *logid, char *name)
Helper function to open llog or create it if doesn't exist.
int llog_erase (const struct lu_env *env, struct llog_ctxt *ctxt, struct llog_logid *logid, char *name)
Helper function to delete existent llog.
int llog_write (const struct lu_env *env, struct llog_handle *loghandle, struct llog_rec_hdr *rec, int idx)
int llog_open (const struct lu_env *env, struct llog_ctxt *ctxt, struct llog_handle **lgh, struct llog_logid *logid, char *name, enum llog_open_param open_param)
int llog_close (const struct lu_env *env, struct llog_handle *loghandle)
int llog_is_empty (const struct lu_env *env, struct llog_ctxt *ctxt, char *name)
Helper function to get the llog size in records.
int llog_copy_handler (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *rec, void *data)
int llog_backup (const struct lu_env *env, struct obd_device *obd, struct llog_ctxt *ctxt, struct llog_ctxt *bctxt, char *name, char *backup)
__u64 llog_size (const struct lu_env *env, struct llog_handle *llh)
Define Documentation
#define DEBUG_SUBSYSTEM S_LOG
Definition at line 48 of file llog.c.
Function Documentation
static struct llog_handle* llog_alloc_handle (void) [static, read]
Definition at line 59 of file llog.c.
References INIT_LIST_HEAD, llog_handle::lgh_hdr_mutex, llog_handle::lgh_lock, llog_handle::lgh_refcount, OBD_ALLOC_PTR, llog_handle::phd, plain_handle_data::phd_entry, and llog_handle::u.
Referenced by llog_open().
static int llog_declare_destroy (const struct lu_env * env, struct llog_handle * handle, struct thandle * th) [static]
Definition at line 107 of file llog.c.
References ENTRY, llog_handle2ops(), llog_operations::lop_declare_destroy, and RETURN.
Referenced by llog_cancel_rec(), and llog_destroy().
static void llog_free_handle (struct llog_handle * loghandle) [static]
Definition at line 78 of file llog.c.
References llog_handle::chd, cat_handle_data::chd_head, LASSERT, llog_handle::lgh_hdr, llog_handle::lgh_hdr_size, list_empty(), llog_log_hdr::llh_flags, LLOG_F_IS_CAT, LLOG_F_IS_PLAIN, OBD_FREE_LARGE, OBD_FREE_PTR, llog_handle::phd, plain_handle_data::phd_entry, and llog_handle::u.
Referenced by llog_handle_put(), and llog_open().
void llog_handle_get (struct llog_handle * loghandle)
Definition at line 95 of file llog.c.
References llog_handle::lgh_refcount.
Referenced by llog_cat_id2handle().
void llog_handle_put (struct llog_handle * loghandle)
Definition at line 100 of file llog.c.
References LASSERT, llog_handle::lgh_refcount, and llog_free_handle().
Referenced by llog_cat_cancel_records(), llog_cat_process_cb(), llog_cat_reverse_process_cb(), llog_cat_size_cb(), llog_check_cb(), llog_close(), and llog_remove_log().
static int llog_process_thread (void * arg) [static]
Definition at line 419 of file llog.c.
References __u64, buf, CDEBUG, CERROR, CWARN, D_OTHER, dt_object_remote(), ENTRY, ext2_test_bit, GOTO, LASSERT, llog_handle::lgh_ctxt, llog_handle::lgh_cur_idx, llog_handle::lgh_cur_offset, llog_handle::lgh_hdr, llog_handle::lgh_last_idx, llog_handle::lgh_obj, llog_log_hdr::llh_hdr, llog_cancel_rec(), LLOG_DEL_RECORD, LLOG_HDR_BITMAP, LLOG_HDR_BITMAP_SIZE, llog_next_block(), LLOG_PROC_BREAK, LLOG_REC_HDR_NEEDS_SWABBING, llog_rec_hdr_next(), llog_ctxt::loc_obd, llog_process_cat_data::lpcd_first_idx, llog_process_cat_data::lpcd_last_idx, llog_process_info::lpi_catdata, llog_process_info::lpi_cb, llog_process_info::lpi_cbdata, llog_process_info::lpi_env, llog_process_info::lpi_loghandle, llog_process_info::lpi_rc, llog_rec_hdr::lrh_index, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, lustre_swab_llog_rec(), OBD_ALLOC_LARGE, OBD_FREE_LARGE, obd_device::obd_name, RETURN, and unlikely.
Referenced by llog_process_or_fork(), and llog_process_thread_daemonize().
static int llog_process_thread_daemonize (void * arg) [static]
Definition at line 618 of file llog.c.
References LCT_LOCAL, LCT_MG_THREAD, llog_process_thread(), llog_process_info::lpi_completion, llog_process_info::lpi_env, lu_env_fini(), and lu_env_init().
Referenced by llog_process_or_fork().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.