Lustre: lustre/obdclass/llog_internal.h File Reference
lustre/obdclass/llog_internal.h File Reference
#include <lustre_log.h>
Data Structures
struct llog_process_info
struct llog_thread_info
Functions
static struct llog_thread_info * llog_info (const struct lu_env *env)
static void lustre_build_llog_lvfs_oid (struct llog_logid *logid, __u64 ino, __u32 gen)
int llog_info_init (void)
void llog_info_fini (void)
void llog_handle_get (struct llog_handle *loghandle)
void llog_handle_put (struct llog_handle *loghandle)
int llog_cat_id2handle (const struct lu_env *env, struct llog_handle *cathandle, struct llog_handle **res, struct llog_logid *logid)
int class_config_dump_handler (const struct lu_env *env, struct llog_handle *handle, struct llog_rec_hdr *rec, void *data)
int class_config_yaml_output (struct llog_rec_hdr *rec, char *buf, int size)
parse config record and output dump in supplied buffer.
int llog_process_or_fork (const struct lu_env *env, struct llog_handle *loghandle, llog_cb_t cb, void *data, void *catdata, bool fork)
int llog_cat_cleanup (const struct lu_env *env, struct llog_handle *cathandle, struct llog_handle *loghandle, int index)
static struct llog_rec_hdr * llog_rec_hdr_next (struct llog_rec_hdr *rec)
Variables
struct lu_context_key llog_thread_key
Function Documentation
int class_config_dump_handler (const struct lu_env * env, struct llog_handle * handle, struct llog_rec_hdr * rec, void * data)
Definition at line 1881 of file obd_config.c.
References class_config_parse_rec(), D_WARNING, ENTRY, LCONSOLE, llog_rec_hdr::lrh_type, OBD_ALLOC, OBD_CFG_REC, OBD_FREE, and RETURN.
Referenced by class_config_llog_handler().
int class_config_yaml_output (struct llog_rec_hdr * rec, char * buf, int size)
parse config record and output dump in supplied buffer.
This is separated from class_config_dump_handler() to use for ioctl needs as well
Sample Output:
{ event: attach, device: lustrewt-clilov, type: lov, UUID: lustrewt-clilov_UUID }
Definition at line 1772 of file obd_config.c.
References end, LASSERT, lustre_cfg::lcfg_bufcount, lcfg_cmd2data(), lustre_cfg::lcfg_command, lustre_cfg::lcfg_flags, LCFG_MARKER, lustre_cfg::lcfg_nid, lustre_cfg::lcfg_num, libcfs_nid2str_r(), LNET_NIDSTR_SIZE, LPX64, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, lcfg_type_data::ltd_bufs, lcfg_type_data::ltd_name, LUSTRE_CFG_BUFLEN, lustre_cfg_sanity_check(), lustre_cfg_string(), and OBD_CFG_REC.
Referenced by llog_print_cb().
int llog_cat_cleanup (const struct lu_env * env, struct llog_handle * cathandle, struct llog_handle * loghandle, int index)
Definition at line 1041 of file llog_cat.c.
References CDEBUG, llog_handle::chd, cat_handle_data::chd_current_log, D_HA, DOSTID, LASSERT, llog_cookie::lgc_index, llog_handle::lgh_id, llog_handle::lgh_lock, llog_handle::lgh_obj, llog_logid::lgl_oi, list_del_init(), llog_cancel_rec(), llog_cat_set_first_idx(), llog_close(), llog_handle::phd, plain_handle_data::phd_cookie, plain_handle_data::phd_entry, POSTID, and llog_handle::u.
Referenced by llog_cat_cancel_records(), llog_cat_close(), llog_cat_process_cb(), llog_cat_reverse_process_cb(), and llog_remove_log().
int llog_cat_id2handle (const struct lu_env * env, struct llog_handle * cathandle, struct llog_handle ** res, struct llog_logid * logid)
Definition at line 206 of file llog_cat.c.
References CERROR, llog_handle::chd, cat_handle_data::chd_head, DOSTID, ENTRY, EXIT, GOTO, llog_cookie::lgc_index, llog_cookie::lgc_lgl, llog_handle::lgh_ctxt, llog_handle::lgh_hdr, llog_handle::lgh_id, llog_handle::lgh_lock, llog_logid::lgl_ogen, llog_logid::lgl_oi, list_add_tail(), list_for_each_entry, llog_log_hdr::llh_cat_idx, llog_log_hdr::llh_flags, llog_close(), LLOG_F_EXT_MASK, LLOG_F_IS_PLAIN, llog_handle_get(), llog_init_handle(), llog_open(), LLOG_OPEN_EXISTS, llog_ctxt::loc_obd, obd_device::obd_name, ostid_id(), ostid_seq(), llog_handle::phd, plain_handle_data::phd_cat_handle, plain_handle_data::phd_cookie, plain_handle_data::phd_entry, POSTID, RETURN, and llog_handle::u.
Referenced by llog_cat_cancel_records(), llog_cat_process_cb(), llog_cat_reverse_process_cb(), llog_cat_size_cb(), llog_check_cb(), and llog_remove_log().
void llog_handle_get (struct llog_handle * loghandle)
Definition at line 95 of file llog.c.
References llog_handle::lgh_refcount.
Referenced by llog_cat_id2handle().
void llog_handle_put (struct llog_handle * loghandle)
Definition at line 100 of file llog.c.
References LASSERT, llog_handle::lgh_refcount, and llog_free_handle().
Referenced by llog_cat_cancel_records(), llog_cat_process_cb(), llog_cat_reverse_process_cb(), llog_cat_size_cb(), llog_check_cb(), llog_close(), and llog_remove_log().
static struct llog_thread_info* llog_info (const struct lu_env * env) [static, read]
Definition at line 67 of file llog_internal.h.
References LASSERT, lu_env::le_ctx, llog_thread_key, and lu_context_key_get().
Referenced by llog_cancel_rec(), llog_cat_declare_add_rec(), llog_cat_new_log(), llog_osd_create(), llog_osd_create_new_object(), llog_osd_declare_create(), llog_osd_declare_new_object(), llog_osd_declare_write_rec(), llog_osd_get_cat_list(), llog_osd_get_regular_fid_dir(), llog_osd_next_block(), llog_osd_open(), llog_osd_pad(), llog_osd_prev_block(), llog_osd_put_cat_list(), llog_osd_read_header(), llog_osd_regular_fid_add_name_entry(), llog_osd_regular_fid_del_name_entry(), llog_osd_setup(), and llog_osd_write_rec().
void llog_info_fini (void)
Definition at line 267 of file llog_obd.c.
References llog_thread_key, and lu_context_key_degister().
Referenced by obdclass_exit().
int llog_info_init (void)
Definition at line 260 of file llog_obd.c.
References llog_thread_key, and lu_context_key_register().
Referenced by obdclass_init().
static struct llog_rec_hdr* llog_rec_hdr_next (struct llog_rec_hdr * rec) [static, read]
Definition at line 101 of file llog_internal.h.
References llog_rec_hdr::lrh_len.
Referenced by changelog_block_trim_ext(), and llog_process_thread().
static void lustre_build_llog_lvfs_oid (struct llog_logid * logid, __u64 ino, __u32 gen) [inline, static]
Definition at line 77 of file llog_internal.h.
References llog_logid::lgl_ogen, llog_logid::lgl_oi, ostid_set_id(), and ostid_set_seq_llog().
Variable Documentation
struct lu_context_key llog_thread_key
Referenced by llog_info(), llog_info_fini(), and llog_info_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.