Lustre: lustre/obdclass/llog_osd.c File Reference
lustre/obdclass/llog_osd.c File Reference
#include <dt_object.h>
#include <llog_swab.h>
#include <lustre_fid.h>
#include <obd.h>
#include <obd_class.h>
#include "llog_internal.h"
#include "local_storage.h"
Defines
#define DEBUG_SUBSYSTEM S_LOG
Functions
static int llog_osd_declare_new_object (const struct lu_env *env, struct local_oid_storage *los, struct dt_object *o, struct thandle *th)
Implementation of the llog_operations::lop_declare_create.
static int llog_osd_create_new_object (const struct lu_env *env, struct local_oid_storage *los, struct dt_object *o, struct thandle *th)
Implementation of the llog_operations::lop_create.
static int llog_osd_exist (struct llog_handle *handle)
Implementation of the llog_operations::lop_exist.
static int llog_osd_pad (const struct lu_env *env, struct dt_object *o, loff_t *off, int len, int index, struct thandle *th)
Write a padding record to the llog.
static int llog_osd_read_header (const struct lu_env *env, struct llog_handle *handle)
Implementation of the llog_operations::lop_read_header.
static int llog_osd_declare_write_rec (const struct lu_env *env, struct llog_handle *loghandle, struct llog_rec_hdr *rec, int idx, struct thandle *th)
Implementation of the llog_operations::lop_declare_write.
static int llog_osd_write_rec (const struct lu_env *env, struct llog_handle *loghandle, struct llog_rec_hdr *rec, struct llog_cookie *reccookie, int idx, struct thandle *th)
Implementation of the llog_operations::lop_write.
static void llog_skip_over (struct llog_handle *lgh, __u64 *off, int curr, int goal, __u32 chunk_size, bool force_mini_rec)
We can skip reading at least as many log blocks as the number of minimum sized log records we are skipping.
static void changelog_block_trim_ext (struct llog_rec_hdr *hdr, struct llog_rec_hdr *last_hdr, enum changelog_rec_flags flags)
Remove optional fields that the client doesn't expect.
static int llog_osd_next_block (const struct lu_env *env, struct llog_handle *loghandle, int *cur_idx, int next_idx, __u64 *cur_offset, void *buf, int len)
Implementation of the llog_operations::lop_next_block.
static int llog_osd_prev_block (const struct lu_env *env, struct llog_handle *loghandle, int prev_idx, void *buf, int len)
Implementation of the llog_operations::lop_prev_block.
static struct dt_object * llog_osd_dir_get (const struct lu_env *env, struct llog_ctxt *ctxt)
This is helper function to get llog directory object.
static int llog_osd_open (const struct lu_env *env, struct llog_handle *handle, struct llog_logid *logid, char *name, enum llog_open_param open_param)
Implementation of the llog_operations::lop_open.
struct dt_object * llog_osd_get_regular_fid_dir (const struct lu_env *env, struct dt_object *dto)
Get dir for regular fid log object.
static int llog_osd_regular_fid_add_name_entry (const struct lu_env *env, struct dt_object *dto, struct thandle *th, bool declare)
Add llog object with regular FID to name entry.
static int llog_osd_declare_create (const struct lu_env *env, struct llog_handle *res, struct thandle *th)
Implementation of the llog_operations::lop_declare_create.
static int llog_osd_create (const struct lu_env *env, struct llog_handle *res, struct thandle *th)
Implementation of the llog_operations::lop_create.
static int llog_osd_close (const struct lu_env *env, struct llog_handle *handle)
Implementation of the llog_operations::lop_close.
static int llog_osd_regular_fid_del_name_entry (const struct lu_env *env, struct dt_object *dto, struct thandle *th, bool declare)
delete llog object name entry
static int llog_osd_declare_destroy (const struct lu_env *env, struct llog_handle *loghandle, struct thandle *th)
Implementation of the llog_operations::lop_declare_destroy.
static int llog_osd_destroy (const struct lu_env *env, struct llog_handle *loghandle, struct thandle *th)
Implementation of the llog_operations::lop_destroy.
static int llog_osd_setup (const struct lu_env *env, struct obd_device *obd, struct obd_llog_group *olg, int ctxt_idx, struct obd_device *disk_obd)
Implementation of the llog_operations::lop_setup.
static int llog_osd_cleanup (const struct lu_env *env, struct llog_ctxt *ctxt)
Implementation of the llog_operations::lop_cleanup.
int llog_osd_get_cat_list (const struct lu_env *env, struct dt_device *d, int idx, int count, struct llog_catid *idarray, const struct lu_fid *fid)
Read the special file which contains the list of llog catalogs IDs.
int llog_osd_put_cat_list (const struct lu_env *env, struct dt_device *d, int idx, int count, struct llog_catid *idarray, const struct lu_fid *fid)
Write the special file which contains the list of llog catalogs IDs.
Variables
struct llog_operations llog_osd_ops
struct llog_operations llog_common_cat_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_LOG
Definition at line 45 of file llog_osd.c.
Function Documentation
static void changelog_block_trim_ext (struct llog_rec_hdr * hdr, struct llog_rec_hdr * last_hdr, enum changelog_rec_flags flags) [static]
Remove optional fields that the client doesn't expect.
This is typically in order to ensure compatibility with older clients. It is assumed that since we exclusively remove fields, the block will be big enough to handle the remapped records. It is also assumed that records of a block have the same format (i.e.: the same features enabled).
Parameters:
[in,out] hdr Header of the block of records to remap.
[in,out] last_hdr Last header, don't read past this point.
[in] flags Flags describing the fields to keep.
Definition at line 787 of file llog_osd.c.
References CHANGELOG_REC, changelog_remap_rec(), changelog_rec::cr_flags, llog_rec_hdr_next(), and llog_rec_hdr::lrh_type.
Referenced by llog_osd_next_block(), and llog_osd_prev_block().
static int llog_osd_cleanup (const struct lu_env * env, struct llog_ctxt * ctxt) [static]
Implementation of the llog_operations::lop_cleanup.
This function cleanups the llog on local storage.
Parameters:
[in] env execution environment
[in] ctxt the llog context
Return values:
0
Definition at line 1839 of file llog_osd.c.
References llog_ctxt::loc_los_named, llog_ctxt::loc_los_nameless, and local_oid_storage_fini().
static int llog_osd_close (const struct lu_env * env, struct llog_handle * handle) [static]
Implementation of the llog_operations::lop_close.
This function closes the llog. It just put llog object and referenced local storage.
Parameters:
[in] env execution environment
[in] handle llog handle of the current llog
Return values:
0 on successful llog close
negative value on error
Definition at line 1561 of file llog_osd.c.
References dt_object::do_lu, dt_los_put(), ENTRY, LASSERT, llog_handle::lgh_ctxt, llog_handle::lgh_name, llog_handle::lgh_obj, LLOG_CTXT_FLAG_NORMAL_FID, llog_ctxt::loc_flags, lu_object_put(), lu_object_put_nocache(), OBD_FREE, llog_handle::private_data, and RETURN.
static int llog_osd_create (const struct lu_env * env, struct llog_handle * res, struct thandle * th) [static]
Implementation of the llog_operations::lop_create.
This function creates the llog according with llog_handle::lgh_obj and llog_handle::lgh_name.
Parameters:
[in] env execution environment
[in] res llog handle of the current llog
[in] th current transaction handle
Return values:
0 on successful create
negative value on error
Definition at line 1473 of file llog_osd.c.
References CERROR, dt_object::do_lu, dt_object_format::dof_type, dt_create(), dt_insert(), dt_key, dt_mode_to_dft(), dt_object_exists(), dt_read_lock(), dt_read_unlock(), dt_write_lock(), dt_write_unlock(), ENTRY, lu_attr::la_mode, LA_MODE, lu_attr::la_size, LA_SIZE, LA_TYPE, lu_attr::la_valid, LASSERT, lu_device::ld_obd, llog_handle::lgh_ctxt, llog_handle::lgh_id, llog_handle::lgh_name, llog_handle::lgh_obj, llog_thread_info::lgi_attr, llog_thread_info::lgi_dof, llog_thread_info::lgi_dt_rec, llog_thread_info::lgi_fid, LLOG_CTXT_FLAG_NORMAL_FID, llog_info(), llog_osd_create_new_object(), llog_osd_dir_get(), llog_osd_regular_fid_add_name_entry(), lu_object::lo_dev, llog_ctxt::loc_flags, logid_to_fid(), lu_object_put(), obd_device::obd_name, llog_handle::private_data, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, and RETURN.
static int llog_osd_create_new_object (const struct lu_env * env, struct local_oid_storage * los, struct dt_object * o, struct thandle * th) [static]
Implementation of the llog_operations::lop_create.
This function is a wrapper over local_storage API function local_object_create().
Parameters:
[in] env execution environment
[in] los local_storage for bottom storage device
[in] o dt_object to create
[in] th current transaction handle
Return values:
0 on successful creation of the new object
negative error if creation was failed
Definition at line 99 of file llog_osd.c.
References dt_object_format::dof_type, dt_mode_to_dft(), lu_attr::la_mode, LA_MODE, lu_attr::la_valid, llog_thread_info::lgi_attr, llog_thread_info::lgi_dof, llog_info(), and local_object_create().
Referenced by llog_osd_create().
static int llog_osd_declare_create (const struct lu_env * env, struct llog_handle * res, struct thandle * th) [static]
Implementation of the llog_operations::lop_declare_create.
This function declares the llog create. It declares also name insert into llog directory in case of named llog.
Parameters:
[in] env execution environment
[in] res llog handle of the current llog
[in] th current transaction handle
Return values:
0 on successful create declaration
negative value on error
Definition at line 1392 of file llog_osd.c.
References CERROR, dt_object::do_lu, dt_object_format::dof_type, dt_declare_create(), dt_declare_insert(), dt_key, dt_mode_to_dft(), dt_object_exists(), ENTRY, lu_attr::la_mode, LA_MODE, lu_attr::la_size, LA_SIZE, lu_attr::la_valid, LASSERT, lu_device::ld_obd, llog_handle::lgh_ctxt, llog_handle::lgh_id, llog_handle::lgh_name, llog_handle::lgh_obj, llog_thread_info::lgi_attr, llog_thread_info::lgi_dof, llog_thread_info::lgi_dt_rec, llog_thread_info::lgi_fid, LLOG_CTXT_FLAG_NORMAL_FID, llog_info(), llog_osd_declare_new_object(), llog_osd_dir_get(), llog_osd_regular_fid_add_name_entry(), lu_object::lo_dev, llog_ctxt::loc_flags, logid_to_fid(), lu_object_put(), obd_device::obd_name, llog_handle::private_data, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, and RETURN.
static int llog_osd_declare_destroy (const struct lu_env * env, struct llog_handle * loghandle, struct thandle * th) [static]
Implementation of the llog_operations::lop_declare_destroy.
This function declare destroys the llog and deletes also entry in the llog directory in case of named llog. Llog should be opened prior that.
Parameters:
[in] env execution environment
[in] loghandle llog handle of the current llog
Return values:
0 on successful destroy
negative value on error
Definition at line 1648 of file llog_osd.c.
References dt_object::do_lu, dt_declare_delete(), dt_declare_destroy(), dt_declare_ref_del(), dt_key, ENTRY, GOTO, LASSERT, llog_handle::lgh_ctxt, llog_handle::lgh_name, llog_handle::lgh_obj, LLOG_CTXT_FLAG_NORMAL_FID, llog_osd_dir_get(), llog_osd_regular_fid_del_name_entry(), llog_ctxt::loc_flags, lu_object_put(), and RETURN.
static int llog_osd_declare_new_object (const struct lu_env * env, struct local_oid_storage * los, struct dt_object * o, struct thandle * th) [static]
Implementation of the llog_operations::lop_declare_create.
This function is a wrapper over local_storage API function local_object_declare_create().
Parameters:
[in] env execution environment
[in] los local_storage for bottom storage device
[in] o dt_object to create
[in] th current transaction handle
Return values:
0 on successful declaration of the new object
negative error if declaration was failed
Definition at line 70 of file llog_osd.c.
References dt_object_format::dof_type, dt_mode_to_dft(), lu_attr::la_mode, LA_MODE, lu_attr::la_valid, llog_thread_info::lgi_attr, llog_thread_info::lgi_dof, llog_info(), and local_object_declare_create().
Referenced by llog_osd_declare_create().
static int llog_osd_declare_write_rec (const struct lu_env * env, struct llog_handle * loghandle, struct llog_rec_hdr * rec, int idx, struct thandle * th) [static]
Implementation of the llog_operations::lop_declare_write.
This function declares the new record write.
Parameters:
[in] env execution environment
[in] loghandle llog handle of the current llog
[in] rec llog record header. This is a real header of the full llog record to write. This is the beginning of buffer to write, the length of buffer is stored in rec::lrh_len
[in] idx index of the llog record. If idx == -1 then this is append case, otherwise idx is the index of record to modify
[in] th current transaction handle
Return values:
0 on successful declaration
negative error if declaration failed
the pad record can be inserted so take into account double record size
Definition at line 307 of file llog_osd.c.
References dt_declare_record_write(), ENTRY, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, llog_handle::lgh_ctxt, llog_handle::lgh_obj, llog_thread_info::lgi_buf, llog_info(), llog_ctxt::loc_chunk_size, llog_rec_hdr::lrh_len, and RETURN.
static int llog_osd_destroy (const struct lu_env * env, struct llog_handle * loghandle, struct thandle * th) [static]
Implementation of the llog_operations::lop_destroy.
This function destroys the llog and deletes also entry in the llog directory in case of named llog. Llog should be opened prior that. Destroy method is not part of external transaction and does everything inside.
Parameters:
[in] env execution environment
[in] loghandle llog handle of the current llog
Return values:
0 on successful destroy
negative value on error
Definition at line 1712 of file llog_osd.c.
References CERROR, dt_object::do_lu, dt_delete(), dt_destroy(), dt_key, dt_object_exists(), dt_read_lock(), dt_read_unlock(), dt_ref_del(), dt_write_lock(), dt_write_unlock(), ENTRY, GOTO, LASSERT, lu_device::ld_obd, llog_handle::lgh_ctxt, llog_handle::lgh_name, llog_handle::lgh_obj, LLOG_CTXT_FLAG_NORMAL_FID, llog_osd_dir_get(), llog_osd_regular_fid_del_name_entry(), lu_object::lo_dev, llog_ctxt::loc_flags, lu_object_put(), obd_device::obd_name, and RETURN.
static struct dt_object* llog_osd_dir_get (const struct lu_env * env, struct llog_ctxt * ctxt) [static, read]
This is helper function to get llog directory object.
It is used by named llog operations to find/insert/delete llog entry from llog directory.
Parameters:
[in] env execution environment
[in] ctxt llog context
Return values:
dt_object of llog directory
ERR_PTR of negative value on error
Definition at line 1120 of file llog_osd.c.
References dir, dt_object::do_lu, lvfs_run_ctxt::dt, dt_info(), dt_locate(), dt_root_get(), dt_try_as_dir(), dt_thread_info::dti_fid, obd_export::exp_obd, llog_ctxt::loc_dir, llog_ctxt::loc_exp, lu_object_get(), lu_object_put(), and obd_device::obd_lvfs_ctxt.
Referenced by llog_osd_create(), llog_osd_declare_create(), llog_osd_declare_destroy(), llog_osd_destroy(), and llog_osd_open().
static int llog_osd_exist (struct llog_handle * handle) [static]
Implementation of the llog_operations::lop_exist.
This function checks that llog exists on storage.
Parameters:
[in] handle llog handle of the current llog
Return values:
true if llog object exists and is not just destroyed
false if llog doesn't exist or just destroyed
Definition at line 124 of file llog_osd.c.
References dt_object::do_lu, dt_object_exists(), LASSERT, llog_handle::lgh_obj, lu_object::lo_header, and lu_object_is_dying().
Referenced by llog_osd_write_rec().
struct dt_object* llog_osd_get_regular_fid_dir (const struct lu_env * env, struct dt_object * dto) [read]
Get dir for regular fid log object.
Get directory for regular fid log object, and these regular fid log object will be inserted under this directory, to satisfy the FS consistency check, e2fsck etc.
Parameters:
[in] env execution environment
[in] dto llog object
Return values:
pointer to the directory if it is found.
ERR_PTR(negative errno) if it fails.
Definition at line 1295 of file llog_osd.c.
References dir, dt_object::do_lu, dt_locate(), dt_try_as_dir(), ENTRY, fld_range_set_any(), LASSERT, lu_site::ld_seq_site, lu_device::ld_site, llog_thread_info::lgi_fid, llog_thread_info::lgi_range, llog_info(), lu_object::lo_dev, lu_server_fld::lsf_seq_lookup, lu_seq_range::lsr_index, lu2dt_dev(), lu_object_fid(), lu_object_put(), lu_update_log_dir_fid(), RETURN, and seq_server_site::ss_server_fld.
Referenced by llog_osd_regular_fid_add_name_entry(), and llog_osd_regular_fid_del_name_entry().
static int llog_osd_next_block (const struct lu_env * env, struct llog_handle * loghandle, int * cur_idx, int next_idx, __u64 * cur_offset, void * buf, int len) [static]
Implementation of the llog_operations::lop_next_block.
This function finds the the next llog block to return which contains record with required index. It is main part of llog processing.
Parameters:
[in] env execution environment
[in] loghandle llog handle of the current llog
[in,out] cur_idx index preceeding cur_offset
[in] next_idx target index to find
[in,out] cur_offset furtherst point read in the file
[in] buf pointer to data buffer to fill
[in] len required len to read, it is usually llog chunk_size.
Return values:
0 on successful buffer read
negative value on error
Definition at line 820 of file llog_osd.c.
References __u64, CDEBUG, CERROR, changelog_block_trim_ext(), CLF_RENAME, CLF_VERSION, D_OTHER, DFID, dt_object::do_lu, DOSTID, dt_attr_get(), dt_object_exists(), dt_read(), ENTRY, GOTO, lu_attr::la_size, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lu_device::ld_obd, llog_handle::lgh_ctxt, llog_handle::lgh_hdr, llog_handle::lgh_id, llog_handle::lgh_obj, llog_thread_info::lgi_attr, llog_thread_info::lgi_buf, llog_logid::lgl_ogen, llog_logid::lgl_oi, llog_log_hdr::llh_flags, llog_log_hdr::llh_hdr, LLOG_F_EXT_JOBID, llog_info(), LLOG_REC_HDR_NEEDS_SWABBING, llog_skip_over(), lu_object::lo_dev, LPU64, llog_rec_hdr::lrh_index, llog_rec_hdr::lrh_len, llog_rec_tail::lrt_index, llog_rec_tail::lrt_len, lu2dt_dev(), lu_object_fid(), lustre_swab_llog_rec(), obd_device::obd_name, PFID, POSTID, and RETURN.
static int llog_osd_open (const struct lu_env * env, struct llog_handle * handle, struct llog_logid * logid, char * name, enum llog_open_param open_param) [static]
Implementation of the llog_operations::lop_open.
This function opens the llog by its logid or by name, it may open also non existent llog and assing then new id to it. The llog_open/llog_close pair works similar to lu_object_find/put, the object may not exist prior open. The result of open is just dt_object in the llog header.
Parameters:
[in] env execution environment
[in] handle llog handle of the current llog
[in] logid logid of llog to open (nameless llog)
[in] name name of llog to open (named llog)
[in] open_param LLOG_OPEN_NEW - new llog, may not exist LLOG_OPEN_EXIST - old llog, must exist
Return values:
0 on successful open, llog_handle::lgh_obj contains the dt_object of the llog.
negative value on error
Definition at line 1168 of file llog_osd.c.
References dt_device::dd_lu_dev, dt_object::do_lu, lvfs_run_ctxt::dt, dt_locate_at(), dt_lookup_dir(), dt_los_find(), dt_los_put(), dt_object_exists(), dt_read_lock(), dt_read_unlock(), ENTRY, obd_export::exp_obd, FID_SEQ_LLOG, FID_SEQ_LLOG_NAME, fid_to_logid(), GOTO, LASSERT, LASSERTF, lu_device::ld_site, llog_handle::lgh_ctxt, llog_handle::lgh_id, llog_handle::lgh_name, llog_handle::lgh_obj, llog_thread_info::lgi_fid, LLOG_CTXT_FLAG_NORMAL_FID, llog_info(), LLOG_OPEN_NEW, llog_osd_dir_get(), llog_ctxt::loc_exp, LOC_F_NEW, lu_object_conf::loc_flags, llog_ctxt::loc_flags, local_object_fid_generate(), logid_to_fid(), ls_device_get(), ls_device_put(), ls_locate(), ls_device::ls_los_mutex, lu_site::ls_top_dev, lu_object_put(), OBD_ALLOC, obd_fid_alloc(), OBD_FREE, obd_device::obd_lvfs_ctxt, llog_handle::private_data, and RETURN.
static int llog_osd_pad (const struct lu_env * env, struct dt_object * o, loff_t * off, int len, int index, struct thandle * th) [static]
Write a padding record to the llog.
This function writes a padding record to the end of llog. That may be needed if llog contains records of variable size, e.g. config logs or changelogs. The padding record just aligns llog to the llog chunk_size boundary if the current record doesn't fit in the remaining space.
It allocates full length to avoid two separate writes for header and tail. Such 2-steps scheme needs extra protection and complex error handling.
Parameters:
[in] env execution environment
[in] o dt_object to create
[in,out] off pointer to the padding start offset
[in] len padding length
[in] index index of the padding record in a llog
[in] th current transaction handle
Return values:
0 on successful padding write
negative error if write failed
Definition at line 153 of file llog_osd.c.
References CERROR, dt_object::do_lu, dt_record_write(), ENTRY, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lu_device::ld_obd, llog_thread_info::lgi_buf, llog_info(), LLOG_MIN_REC_SIZE, LLOG_PAD_MAGIC, lu_object::lo_dev, llog_rec_hdr::lrh_index, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, llog_rec_tail::lrt_index, llog_rec_tail::lrt_len, OBD_ALLOC, OBD_FREE, obd_device::obd_name, rec_tail(), and RETURN.
Referenced by llog_osd_write_rec().
static int llog_osd_prev_block (const struct lu_env * env, struct llog_handle * loghandle, int prev_idx, void * buf, int len) [static]
Implementation of the llog_operations::lop_prev_block.
This function finds the llog block to return which contains record with required index but in reverse order - from end of llog to the beginning. It is main part of reverse llog processing.
Parameters:
[in] env execution environment
[in] loghandle llog handle of the current llog
[in] prev_idx target index to find
[in] buf pointer to data buffer to fill
[in] len required len to read, it is llog_chunk_size usually.
Return values:
0 on successful buffer read
negative value on error
Definition at line 998 of file llog_osd.c.
References CDEBUG, CERROR, changelog_block_trim_ext(), CLF_RENAME, CLF_VERSION, D_OTHER, DFID, dt_object::do_lu, DOSTID, dt_attr_get(), dt_object_exists(), dt_read(), ENTRY, GOTO, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lu_device::ld_obd, le32_to_cpu, llog_handle::lgh_ctxt, llog_handle::lgh_hdr, llog_handle::lgh_id, llog_handle::lgh_obj, llog_thread_info::lgi_attr, llog_thread_info::lgi_buf, llog_logid::lgl_ogen, llog_logid::lgl_oi, llog_log_hdr::llh_flags, llog_log_hdr::llh_hdr, LLOG_F_EXT_JOBID, llog_info(), LLOG_REC_HDR_NEEDS_SWABBING, llog_skip_over(), lu_object::lo_dev, LPU64, llog_rec_hdr::lrh_index, llog_rec_hdr::lrh_len, llog_rec_tail::lrt_index, llog_rec_tail::lrt_len, lu2dt_dev(), lu_object_fid(), lustre_swab_llog_rec(), obd_device::obd_name, PFID, POSTID, and RETURN.
static int llog_osd_read_header (const struct lu_env * env, struct llog_handle * handle) [static]
Implementation of the llog_operations::lop_read_header.
This function reads the current llog header from the bottom storage device.
Parameters:
[in] env execution environment
[in] handle llog handle of the current llog
Return values:
0 on successful header read
negative error if read failed
Definition at line 202 of file llog_osd.c.
References CDEBUG, CERROR, D_HA, DFID, dt_object::do_lu, dt_attr_get(), dt_read(), ENTRY, lu_attr::la_size, LA_SIZE, lu_attr::la_valid, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lu_device::ld_obd, llog_handle::lgh_hdr, llog_handle::lgh_hdr_size, llog_handle::lgh_last_idx, llog_handle::lgh_name, llog_handle::lgh_obj, llog_handle::lgh_write_offset, llog_thread_info::lgi_attr, llog_thread_info::lgi_buf, llog_thread_info::lgi_off, llog_log_hdr::llh_flags, llog_log_hdr::llh_hdr, LLOG_EEMPTY, LLOG_F_EXT_MASK, LLOG_HDR_BITMAP_SIZE, LLOG_HDR_MAGIC, LLOG_HDR_TAIL, llog_info(), LLOG_MIN_CHUNK_SIZE, LLOG_REC_HDR_NEEDS_SWABBING, lu_object::lo_dev, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, lu_object_fid(), lustre_swab_llog_hdr, obd_device::obd_name, PFID, and RETURN.
static int llog_osd_regular_fid_add_name_entry (const struct lu_env * env, struct dt_object * dto, struct thandle * th, bool declare) [static]
Add llog object with regular FID to name entry.
Add llog object with regular FID to name space, and each llog object on each MDT will be /update_log_dir/[seq:oid:ver], so to satisfy the namespace consistency check, e2fsck etc.
Parameters:
[in] env execution environment
[in] dto llog object
[in] th thandle
[in] declare if it is declare or execution
Return values:
0 if insertion succeeds.
negative errno if insertion fails.
Definition at line 1342 of file llog_osd.c.
References DFID, dir, dt_object::do_lu, dt_declare_insert(), dt_insert(), dt_key, dt_write_lock(), dt_write_unlock(), ENTRY, fid_is_norm(), llog_thread_info::lgi_dt_rec, llog_thread_info::lgi_name, llog_info(), llog_osd_get_regular_fid_dir(), lu_object_fid(), lu_object_put(), name, PFID, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, and RETURN.
Referenced by llog_osd_create(), and llog_osd_declare_create().
static int llog_osd_regular_fid_del_name_entry (const struct lu_env * env, struct dt_object * dto, struct thandle * th, bool declare) [static]
delete llog object name entry
Delete llog object (with regular FID) from name space (under update_log_dir).
Parameters:
[in] env execution environment
[in] dto llog object
[in] th thandle
[in] declare if it is declare or execution
Return values:
0 if deletion succeeds.
negative errno if deletion fails.
Definition at line 1604 of file llog_osd.c.
References DFID, dir, dt_object::do_lu, dt_declare_delete(), dt_delete(), dt_key, dt_write_lock(), dt_write_unlock(), ENTRY, fid_is_norm(), llog_thread_info::lgi_name, llog_info(), llog_osd_get_regular_fid_dir(), lu_object_fid(), lu_object_put(), name, PFID, and RETURN.
Referenced by llog_osd_declare_destroy(), and llog_osd_destroy().
static int llog_osd_setup (const struct lu_env * env, struct obd_device * obd, struct obd_llog_group * olg, int ctxt_idx, struct obd_device * disk_obd) [static]
Implementation of the llog_operations::lop_setup.
This function setup the llog on local storage.
Parameters:
[in] env execution environment
[in] obd obd device the llog belongs to
[in] olg the llog group, it is always zero group now.
[in] ctxt_idx the llog index, it defines the purpose of this llog. Every new llog type have to use own index.
[in] disk_obd the storage obd, where llog is stored.
Return values:
0 on successful llog setup
negative value on error
Definition at line 1782 of file llog_osd.c.
References lvfs_run_ctxt::dt, ENTRY, lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, FID_SEQ_LLOG, FID_SEQ_LLOG_NAME, GOTO, LASSERT, llog_thread_info::lgi_fid, llog_ctxt_get(), llog_ctxt_put(), llog_info(), llog_ctxt::loc_los_named, llog_ctxt::loc_los_nameless, local_oid_storage_fini(), local_oid_storage_init(), obd_device::obd_lvfs_ctxt, and obd_llog_group::olg_ctxts.
static int llog_osd_write_rec (const struct lu_env * env, struct llog_handle * loghandle, struct llog_rec_hdr * rec, struct llog_cookie * reccookie, int idx, struct thandle * th) [static]
Implementation of the llog_operations::lop_write.
This function writes the new record in the llog or modify the existed one.
Parameters:
[in] env execution environment
[in] loghandle llog handle of the current llog
[in] rec llog record header. This is a real header of the full llog record to write. This is the beginning of buffer to write, the length of buffer is stored in rec::lrh_len
[out] reccookie pointer to the cookie to return back if needed. It is used for further cancel of this llog record.
[in] idx index of the llog record. If idx == -1 then this is append case, otherwise idx is the index of record to modify
[in] th current transaction handle
Return values:
0 on successful write && reccookie == NULL 1 on successful write && reccookie != NULL
negative error if write failed
The modification case. If idx set then the record with that index must be modified. There are three cases possible: 1) the common case is the llog header update (idx == 0) 2) the llog record modification during llog process. This is indicated by the loghandle::lgh_cur_idx > 0. In that case the loghandle::lgh_cur_offset 3) otherwise this is assumed that llog consist of records of fixed size, i.e. catalog. The llog header must has llh_size field equal to record size. The record offset is calculated just by /a idx value
During modification we don't need extra header update because the bitmap and record count are not changed. The record header and tail remains the same too.
The lgh_cur_offset can be used only if index is the same.
The append case. The most common case of using llog. The new index is assigned to the new record, new bit is set in llog bitmap and llog count is incremented.
Make sure that records don't cross a chunk boundary, so we can process them page-at-a-time if needed. If it will cross a chunk boundary, write in a fake (but referenced) entry to pad the chunk.
NB: the caller should make sure only 1 process access the lgh_last_idx, e.g. append should be exclusive. Otherwise it might hit the assert.
Definition at line 372 of file llog_osd.c.
References __u64, CDEBUG, CERROR, cfs_fail_val, D_HA, D_OTHER, DFID, dt_object::do_lu, DOSTID, dt_attr_get(), dt_object_remote(), dt_record_write(), ENTRY, ergo, ext2_clear_bit, ext2_set_bit, ext2_test_bit, GOTO, LA_SIZE, lu_attr::la_size, lu_attr::la_valid, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, LBUG, lu_device::ld_obd, llog_cookie::lgc_index, llog_cookie::lgc_lgl, llog_cookie::lgc_subsys, llog_handle::lgh_cur_idx, llog_handle::lgh_cur_offset, llog_handle::lgh_hdr, llog_handle::lgh_hdr_mutex, llog_handle::lgh_id, llog_handle::lgh_last_idx, llog_handle::lgh_obj, llog_handle::lgh_write_offset, llog_thread_info::lgi_attr, llog_thread_info::lgi_buf, llog_thread_info::lgi_off, llog_logid::lgl_oi, llog_log_hdr::llh_bitmap_offset, llog_log_hdr::llh_cat_idx, llog_log_hdr::llh_count, llog_log_hdr::llh_flags, llog_log_hdr::llh_hdr, llog_log_hdr::llh_size, llog_log_hdr::llh_tail, LLOG_F_IS_CAT, LLOG_F_IS_FIXSIZE, LLOG_HDR_BITMAP, LLOG_HDR_BITMAP_SIZE, LLOG_HDR_TAIL, LLOG_HEADER_IDX, llog_info(), llog_is_full(), LLOG_MDS_OST_ORIG_CTXT, LLOG_MIN_REC_SIZE, LLOG_NEXT_IDX, llog_osd_exist(), llog_osd_pad(), LLOG_SIZE_ORIG_CTXT, lu_object::lo_dev, LPU64, llog_rec_hdr::lrh_index, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, llog_rec_tail::lrt_index, llog_rec_tail::lrt_len, lu_object_fid(), MDS_SETATTR64_REC, MDS_UNLINK_REC, OBD_FAIL_CAT_RECORDS, OBD_FAIL_CHECK, OBD_FAIL_MDS_LLOG_CREATE_FAILED2, OBD_FAIL_PRECHECK, obd_device::obd_name, OST_SZ_REC, PFID, POSTID, REC_DATA, REC_DATA_LEN, rec_tail(), RETURN, and unlikely.
static void llog_skip_over (struct llog_handle * lgh, __u64 * off, int curr, int goal, __u32 chunk_size, bool force_mini_rec) [inline, static]
We can skip reading at least as many log blocks as the number of minimum sized log records we are skipping.
If it turns out that we are not far enough along the log (because the actual records are larger than minimum size) we just skip some more records.
Note: in llog_process_thread, it will use bitmap offset as the index to locate the record, which also includs some pad records, whose record size is very small, and it also does not consider pad record when recording minimum record size (otherwise min_record size might be too small), so in some rare cases, it might skip too much record for , see llog_osd_next_block().
When force_mini_rec is true, it means we have to use LLOG_MIN_REC_SIZE as the min record size to skip over, usually because in the previous try, it skip too much record, see loog_osd_next(prev)_block().
Definition at line 750 of file llog_osd.c.
References __u64, llog_handle::lgh_hdr, llog_handle::lgh_last_idx, llog_log_hdr::llh_flags, llog_log_hdr::llh_size, LLOG_F_IS_FIXSIZE, and LLOG_MIN_REC_SIZE.
Referenced by llog_osd_next_block(), and llog_osd_prev_block().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.