Lustre: lustre/obdclass/llog_swab.c File Reference
lustre/obdclass/llog_swab.c File Reference
#include <lustre_log.h>
#include <lustre_update.h>
Data Structures
struct cfg_marker32
Defines
#define DEBUG_SUBSYSTEM S_LOG
#define MTI_NAMELEN32
Functions
static void print_llogd_body (struct llogd_body *d)
void lustre_swab_lu_fid (struct lu_fid *fid)
void lustre_swab_ost_id (struct ost_id *oid)
void lustre_swab_llog_id (struct llog_logid *log_id)
void lustre_swab_llogd_body (struct llogd_body *d)
void lustre_swab_llogd_conn_body (struct llogd_conn_body *d)
void lustre_swab_ll_fid (struct ll_fid *fid)
void lustre_swab_lu_seq_range (struct lu_seq_range *range)
void lustre_swab_update_ops (struct update_ops *uops, unsigned int op_count)
void lustre_swab_llog_rec (struct llog_rec_hdr *rec)
static void print_llog_hdr (struct llog_log_hdr *h)
void lustre_swab_llog_hdr (struct llog_log_hdr *h)
static void print_lustre_cfg (struct lustre_cfg *lcfg)
void lustre_swab_lustre_cfg (struct lustre_cfg *lcfg)
void lustre_swab_cfg_marker (struct cfg_marker *marker, int swab, int size)
Define Documentation
#define DEBUG_SUBSYSTEM S_LOG
Definition at line 43 of file llog_swab.c.
#define MTI_NAMELEN32
Value:
(MTI_NAME_MAXLEN - \
        (sizeof(struct cfg_marker) - sizeof(struct cfg_marker32)))
Definition at line 413 of file llog_swab.c.
Referenced by lustre_swab_cfg_marker().
Function Documentation
void lustre_swab_cfg_marker (struct cfg_marker * marker, int swab, int size)
Definition at line 416 of file llog_swab.c.
References __swab32s, __swab64s, CDEBUG, cfg_marker::cm_canceltime, cfg_marker32::cm_canceltime, cfg_marker32::cm_comment, cfg_marker::cm_comment, cfg_marker::cm_createtime, cfg_marker32::cm_createtime, cfg_marker::cm_flags, cfg_marker::cm_step, cfg_marker32::cm_tgtname, cfg_marker::cm_tgtname, cfg_marker::cm_vers, D_CONFIG, ENTRY, EXIT, and MTI_NAMELEN32.
Referenced by class_config_llog_handler(), and client_lwp_config_process().
void lustre_swab_ll_fid (struct ll_fid * fid)
Definition at line 115 of file llog_swab.c.
References __swab32s, __swab64s, ll_fid::f_type, ll_fid::generation, and ll_fid::id.
Referenced by lustre_swab_llog_rec().
void lustre_swab_llog_hdr (struct llog_log_hdr * h)
Definition at line 339 of file llog_swab.c.
References ENTRY, EXIT, llog_log_hdr::llh_hdr, lustre_swab_llog_rec(), and print_llog_hdr().
void lustre_swab_llog_id (struct llog_logid * log_id)
Definition at line 83 of file llog_swab.c.
References __swab32s, __swab64s, llog_logid::lgl_ogen, llog_logid::lgl_oi, and ost_id::oi.
Referenced by lustre_swab_llog_rec(), lustre_swab_llogd_body(), and lustre_swab_llogd_conn_body().
void lustre_swab_llog_rec (struct llog_rec_hdr * rec)
Definition at line 146 of file llog_swab.c.
References __swab16s, __swab32s, __swab64s, llog_agent_req_rec::arr_hai, CERROR, CHANGELOG_REC, changelog_rec_rename(), changelog_rec_size(), CHANGELOG_USER_REC, CLF_RENAME, llog_gen::conn_cnt, llog_changelog_rec::cr, changelog_rec::cr_flags, changelog_rec::cr_index, changelog_rec::cr_namelen, changelog_rec::cr_pfid, changelog_rec::cr_prev, changelog_ext_rename::cr_sfid, changelog_ext_rename::cr_spfid, changelog_rec::cr_tfid, changelog_rec::cr_time, changelog_rec::cr_type, llog_changelog_user_rec::cur_endrec, llog_changelog_user_rec::cur_id, llog_changelog_user_rec::cur_tail, hsm_action_item::hai_action, hsm_action_item::hai_cookie, hsm_action_item::hai_dfid, hsm_action_item::hai_extent, hsm_action_item::hai_fid, hsm_action_item::hai_gid, hsm_action_item::hai_len, HSM_AGENT_REC, hsm_extent::length, lgr, llog_gen_rec::lgr_gen, llog_gen_rec::lgr_tail, llog_logid_rec::lid_id, llog_logid_rec::lid_tail, llog_log_hdr::llh_bitmap_offset, llog_log_hdr::llh_cat_idx, llog_log_hdr::llh_count, llog_log_hdr::llh_flags, llog_log_hdr::llh_size, llog_log_hdr::llh_timestamp, LLOG_GEN_REC, LLOG_HDR_MAGIC, LLOG_HDR_TAIL, LLOG_LOGID_MAGIC, LLOG_PAD_MAGIC, llog_rec_hdr::lrh_id, llog_rec_hdr::lrh_index, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, llog_rec_tail::lrt_index, llog_rec_tail::lrt_len, llog_size_change_rec::lsc_fid, llog_size_change_rec::lsc_ioepoch, llog_size_change_rec::lsc_tail, llog_setattr64_rec::lsr_gid, llog_setattr64_rec::lsr_gid_h, llog_setattr64_rec::lsr_oi, llog_setattr64_rec::lsr_tail, llog_setattr64_rec::lsr_uid, llog_setattr64_rec::lsr_uid_h, llog_setattr64_rec::lsr_valid, lur, llog_unlink64_rec::lur_count, llog_unlink_rec::lur_count, llog_unlink64_rec::lur_fid, llog_unlink_rec::lur_oid, llog_unlink_rec::lur_oseq, llog_unlink64_rec::lur_tail, llog_unlink_rec::lur_tail, llog_update_record::lur_update_rec, lustre_swab_ll_fid(), lustre_swab_llog_id(), lustre_swab_lu_fid, lustre_swab_ost_id, lustre_swab_update_ops(), MDS_SETATTR64_REC, MDS_UNLINK64_REC, MDS_UNLINK_REC, llog_gen::mnt_cnt, OBD_CFG_REC, hsm_extent::offset, OST_SZ_REC, UPDATE_REC, update_records_size(), update_records::ur_batchid, update_records::ur_flags, update_records::ur_master_transno, update_records::ur_ops, update_records::ur_param_count, and update_records::ur_update_count.
Referenced by llog_osd_next_block(), llog_osd_prev_block(), llog_process_thread(), llog_reverse_process(), and lustre_swab_llog_hdr().
void lustre_swab_llogd_body (struct llogd_body * d)
Definition at line 90 of file llog_swab.c.
References __swab32s, __swab64s, ENTRY, EXIT, llogd_body::lgd_ctxt_idx, llogd_body::lgd_cur_offset, llogd_body::lgd_index, llogd_body::lgd_len, llogd_body::lgd_llh_flags, llogd_body::lgd_logid, llogd_body::lgd_saved_index, lustre_swab_llog_id(), and print_llogd_body().
void lustre_swab_llogd_conn_body (struct llogd_conn_body * d)
Definition at line 106 of file llog_swab.c.
References __swab32s, __swab64s, llog_gen::conn_cnt, llogd_conn_body::lgdc_ctxt_idx, llogd_conn_body::lgdc_gen, llogd_conn_body::lgdc_logid, lustre_swab_llog_id(), and llog_gen::mnt_cnt.
void lustre_swab_lu_fid (struct lu_fid * fid)
Definition at line 63 of file llog_swab.c.
References __swab32s, __swab64s, lu_fid::f_oid, lu_fid::f_seq, and lu_fid::f_ver.
void lustre_swab_lu_seq_range (struct lu_seq_range * range)
Definition at line 122 of file llog_swab.c.
References __swab32s, __swab64s, lu_seq_range::lsr_end, lu_seq_range::lsr_flags, lu_seq_range::lsr_index, and lu_seq_range::lsr_start.
void lustre_swab_lustre_cfg (struct lustre_cfg * lcfg)
Definition at line 374 of file llog_swab.c.
References __swab32s, __swab64s, CERROR, ENTRY, EXIT, lustre_cfg::lcfg_bufcount, lustre_cfg::lcfg_buflens, lustre_cfg::lcfg_command, lustre_cfg::lcfg_flags, lustre_cfg::lcfg_nid, lustre_cfg::lcfg_num, lustre_cfg::lcfg_version, LUSTRE_CFG_MAX_BUFCOUNT, LUSTRE_CFG_VERSION, and print_lustre_cfg().
Referenced by class_config_llog_handler(), and client_lwp_config_process().
void lustre_swab_ost_id (struct ost_id * oid)
Definition at line 71 of file llog_swab.c.
References __swab64s, fid_seq_is_default(), fid_seq_is_mdt0(), lustre_swab_lu_fid, ost_id::oi, and ost_id::oi_fid.
void lustre_swab_update_ops (struct update_ops * uops, unsigned int op_count)
Definition at line 131 of file llog_swab.c.
References __swab16s, lustre_swab_lu_fid, update_op::uop_fid, update_op::uop_param_count, update_op::uop_params_off, update_op::uop_type, and update_ops::uops_op.
Referenced by lustre_swab_llog_rec().
static void print_llog_hdr (struct llog_log_hdr * h) [static]
Definition at line 321 of file llog_swab.c.
References CDEBUG, D_OTHER, llog_log_hdr::llh_bitmap_offset, llog_log_hdr::llh_cat_idx, llog_log_hdr::llh_count, llog_log_hdr::llh_flags, llog_log_hdr::llh_hdr, llog_log_hdr::llh_size, llog_log_hdr::llh_timestamp, LLOG_HDR_TAIL, LPX64, llog_rec_hdr::lrh_index, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, llog_rec_tail::lrt_index, and llog_rec_tail::lrt_len.
Referenced by lustre_swab_llog_hdr().
static void print_llogd_body (struct llogd_body * d) [static]
Definition at line 49 of file llog_swab.c.
References CDEBUG, D_OTHER, DOSTID, llogd_body::lgd_ctxt_idx, llogd_body::lgd_cur_offset, llogd_body::lgd_index, llogd_body::lgd_len, llogd_body::lgd_llh_flags, llogd_body::lgd_logid, llogd_body::lgd_saved_index, llog_logid::lgl_ogen, llog_logid::lgl_oi, LPX64, and POSTID.
Referenced by lustre_swab_llogd_body().
static void print_lustre_cfg (struct lustre_cfg * lcfg) [static]
Definition at line 351 of file llog_swab.c.
References CDEBUG, D_OTHER, ENTRY, EXIT, lustre_cfg::lcfg_bufcount, lustre_cfg::lcfg_buflens, lustre_cfg::lcfg_command, lustre_cfg::lcfg_flags, lustre_cfg::lcfg_nid, lustre_cfg::lcfg_num, lustre_cfg::lcfg_version, libcfs_debug, libcfs_nid2str(), and LUSTRE_CFG_MAX_BUFCOUNT.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.