Lustre: lustre/obdclass/llog_test.c File Reference
lustre/obdclass/llog_test.c File Reference
#include <linux/module.h>
#include <linux/init.h>
#include <obd_class.h>
#include <lustre_fid.h>
#include <lustre_log.h>
Data Structures
struct llog_mini_rec
Defines
#define DEBUG_SUBSYSTEM S_CLASS
#define LLOG_TEST_RECNUM (LLOG_MIN_CHUNK_SIZE * 8)
Functions
static int verify_handle (char *test, struct llog_handle *llh, int num_recs)
static int llog_test_1 (const struct lu_env *env, struct obd_device *obd, char *name)
static int test_2_cancel_cb (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *rec, void *data)
static int llog_test_2 (const struct lu_env *env, struct obd_device *obd, char *name, struct llog_handle **llh)
static int test3_check_n_add_cb (const struct lu_env *env, struct llog_handle *lgh, struct llog_rec_hdr *rec, void *data)
static int test3_check_cb (const struct lu_env *env, struct llog_handle *lgh, struct llog_rec_hdr *rec, void *data)
static int llog_test3_process (const struct lu_env *env, struct llog_handle *lgh, llog_cb_t cb, int start)
static int llog_test_3 (const struct lu_env *env, struct obd_device *obd, struct llog_handle *llh)
static int llog_test_4 (const struct lu_env *env, struct obd_device *obd)
static int cat_print_cb (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *rec, void *data)
static int plain_print_cb (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *rec, void *data)
static int llog_cancel_rec_cb (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *rec, void *data)
static int llog_test_5 (const struct lu_env *env, struct obd_device *obd)
static int llog_test_6 (const struct lu_env *env, struct obd_device *obd, char *name)
static int test_7_print_cb (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *rec, void *data)
static int test_7_cancel_cb (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *rec, void *data)
static int llog_test_7_sub (const struct lu_env *env, struct llog_ctxt *ctxt)
static int llog_test_7 (const struct lu_env *env, struct obd_device *obd)
static int llog_truncate (const struct lu_env *env, struct dt_object *o)
static int test_8_cb (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *rec, void *data)
static int llog_test_8 (const struct lu_env *env, struct obd_device *obd)
static int llog_test_9_sub (const struct lu_env *env, struct llog_ctxt *ctxt)
static int llog_test_9 (const struct lu_env *env, struct obd_device *obd)
static int llog_test_10 (const struct lu_env *env, struct obd_device *obd)
static int llog_run_tests (const struct lu_env *env, struct obd_device *obd)
static int llog_test_cleanup (struct obd_device *obd)
static int llog_test_setup (struct obd_device *obd, struct lustre_cfg *lcfg)
static int __init llog_test_init (void)
static void __exit llog_test_exit (void)
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Log test module")
MODULE_VERSION (LUSTRE_VERSION_STRING)
MODULE_LICENSE ("GPL")
module_init (llog_test_init)
module_exit (llog_test_exit)
Variables
static int llog_test_rand
static struct obd_uuid uuid = { .uuid = "test_uuid" }
static struct llog_logid cat_logid
struct llog_mini_rec packed
static int test_3_rec_num
static off_t test_3_rec_off
static int test_3_paddings
static int test_3_start_idx
static int cat_counter
static int plain_counter
static int cancel_count
union {
struct llog_rec_hdr lrh
struct llog_logid_rec llr
struct llog_unlink64_rec lur
struct llog_setattr64_rec lsr64
struct llog_size_change_rec lscr
struct llog_changelog_rec lcr
struct llog_changelog_user_rec lcur
struct llog_gen_rec lgr
} llog_records
static struct obd_ops llog_obd_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_CLASS
Definition at line 42 of file llog_test.c.
#define LLOG_TEST_RECNUM (LLOG_MIN_CHUNK_SIZE * 8)
Definition at line 54 of file llog_test.c.
Referenced by llog_cancel_rec_cb(), llog_test_10(), llog_test_4(), and llog_test_5().
Function Documentation
static int cat_print_cb (const struct lu_env * env, struct llog_handle * llh, struct llog_rec_hdr * rec, void * data) [static]
Definition at line 684 of file llog_test.c.
References CERROR, CWARN, DFID, dt_object::do_lu, llog_handle::lgh_obj, llog_logid_rec::lid_id, LLOG_LOGID_MAGIC, logid_to_fid(), llog_rec_hdr::lrh_index, llog_rec_hdr::lrh_type, lu_object_fid(), PFID, and RETURN.
Referenced by llog_test_10(), and llog_test_5().
static int llog_cancel_rec_cb (const struct lu_env * env, struct llog_handle * llh, struct llog_rec_hdr * rec, void * data) [static]
Definition at line 730 of file llog_test.c.
References CERROR, llog_cookie::lgc_index, llog_cookie::lgc_lgl, llog_handle::lgh_hdr, llog_handle::lgh_id, llog_log_hdr::llh_flags, llog_cat_cancel_records(), LLOG_EEMPTY, LLOG_F_IS_PLAIN, LLOG_TEST_RECNUM, llog_rec_hdr::lrh_index, llog_handle::phd, plain_handle_data::phd_cat_handle, RETURN, and llog_handle::u.
Referenced by llog_test_10(), and llog_test_5().
static int llog_run_tests (const struct lu_env * env, struct obd_device * obd) [static]
Definition at line 1960 of file llog_test.c.
References CERROR, cleanup(), ENTRY, GOTO, LASSERT, llog_close(), llog_ctxt_put(), llog_destroy(), llog_get_context(), llog_test_1(), llog_test_10(), llog_test_2(), llog_test_3(), llog_test_4(), llog_test_5(), llog_test_6(), llog_test_7(), llog_test_8(), llog_test_9(), LLOG_TEST_ORIG_CTXT, llog_test_rand, and name.
Referenced by llog_test_setup().
static int llog_test3_process (const struct lu_env * env, struct llog_handle * lgh, llog_cb_t cb, int start) [static]
Definition at line 372 of file llog_test.c.
References CWARN, llog_handle::lgh_last_idx, llog_process(), llog_process_cat_data::lpcd_first_idx, and llog_process_cat_data::lpcd_last_idx.
Referenced by llog_test_3().
static int llog_test_1 (const struct lu_env * env, struct obd_device * obd, char * name) [static]
Definition at line 105 of file llog_test.c.
References CERROR, CWARN, ENTRY, GOTO, LASSERT, llog_close(), llog_ctxt_put(), LLOG_F_IS_PLAIN, llog_get_context(), llog_init_handle(), llog_open_create(), LLOG_TEST_ORIG_CTXT, RETURN, and verify_handle().
Referenced by llog_run_tests().
static int llog_test_10 (const struct lu_env * env, struct obd_device * obd) [static]
Definition at line 1450 of file llog_test.c.
References __u64, cat_logid, cat_print_cb(), CERROR, cfs_fail_loc, CFS_FAIL_SKIP, cfs_fail_val, CWARN, dt_object::do_lu, dt_attr_get(), dt_sync(), ENTRY, GOTO, lu_attr::la_size, LASSERT, llog_handle::lgh_hdr, llog_handle::lgh_id, llog_handle::lgh_last_idx, llog_handle::lgh_obj, llog_log_hdr::llh_cat_idx, llog_cancel_rec_cb(), llog_cat_add(), llog_cat_close(), llog_cat_process(), llog_ctxt_put(), LLOG_EEMPTY, LLOG_F_IS_CAT, llog_get_context(), llog_init_handle(), LLOG_MIN_REC_SIZE, llog_open_create(), llog_process(), LLOG_TEST_ORIG_CTXT, llog_test_rand, LLOG_TEST_RECNUM, llog_mini_rec::lmr_hdr, llog_mini_rec::lmr_tail, lu_object::lo_dev, LPU64, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, llog_rec_tail::lrt_len, lu2dt_dev(), name, OBD_FAIL_CAT_RECORDS, RETURN, and verify_handle().
Referenced by llog_run_tests().
static int llog_test_2 (const struct lu_env * env, struct obd_device * obd, char * name, struct llog_handle ** llh) [static]
Definition at line 152 of file llog_test.c.
References CERROR, CWARN, ENTRY, GOTO, LASSERT, llog_handle::lgh_id, llog_close(), llog_ctxt_put(), llog_destroy(), LLOG_F_IS_PLAIN, llog_get_context(), llog_init_handle(), LLOG_MIN_REC_SIZE, LLOG_NEXT_IDX, llog_open(), llog_open_create(), LLOG_OPEN_EXISTS, llog_process(), LLOG_TEST_ORIG_CTXT, llog_write(), llog_mini_rec::lmr_hdr, llog_mini_rec::lmr_tail, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, llog_rec_tail::lrt_len, RETURN, test_2_cancel_cb(), and verify_handle().
Referenced by llog_run_tests().
static int llog_test_3 (const struct lu_env * env, struct obd_device * obd, struct llog_handle * llh) [static]
Definition at line 395 of file llog_test.c.
References buf, CERROR, CWARN, ENTRY, llog_handle::lgh_hdr, llog_log_hdr::llh_flags, llog_log_hdr::llh_hdr, llog_log_hdr::llh_size, LLOG_F_IS_FIXSIZE, LLOG_GEN_REC, LLOG_HDR_BITMAP_SIZE, LLOG_HEADER_IDX, LLOG_NEXT_IDX, llog_test3_process(), llog_write(), llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, OBD_CFG_REC, RETURN, test3_check_cb(), test3_check_n_add_cb(), and verify_handle().
Referenced by llog_run_tests().
static int llog_test_4 (const struct lu_env * env, struct obd_device * obd) [static]
Definition at line 571 of file llog_test.c.
References buf, cat_logid, CERROR, llog_handle::chd, cat_handle_data::chd_current_log, CWARN, ENTRY, GOTO, LASSERT, llog_handle::lgh_id, llog_cat_add(), llog_cat_cancel_records(), llog_cat_close(), llog_ctxt_put(), LLOG_F_IS_CAT, llog_get_context(), llog_init_handle(), LLOG_MIN_CHUNK_SIZE, LLOG_MIN_REC_SIZE, llog_open_create(), LLOG_TEST_ORIG_CTXT, llog_test_rand, LLOG_TEST_RECNUM, llog_mini_rec::lmr_hdr, llog_mini_rec::lmr_tail, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, llog_rec_tail::lrt_len, name, OBD_ALLOC, OBD_CFG_REC, OBD_FREE, RETURN, llog_handle::u, and verify_handle().
Referenced by llog_run_tests().
static int llog_test_5 (const struct lu_env * env, struct obd_device * obd) [static]
Definition at line 752 of file llog_test.c.
References cat_logid, cat_print_cb(), CERROR, CWARN, ENTRY, GOTO, LASSERT, llog_cancel_rec_cb(), llog_cat_add(), llog_cat_close(), llog_cat_process(), llog_cat_reverse_process(), llog_ctxt_put(), LLOG_EEMPTY, LLOG_F_IS_CAT, llog_get_context(), llog_init_handle(), LLOG_MIN_REC_SIZE, llog_open(), LLOG_OPEN_EXISTS, llog_process(), LLOG_TEST_ORIG_CTXT, LLOG_TEST_RECNUM, llog_mini_rec::lmr_hdr, llog_mini_rec::lmr_tail, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, llog_rec_tail::lrt_len, name, plain_print_cb(), and RETURN.
Referenced by llog_run_tests().
static int llog_test_6 (const struct lu_env * env, struct obd_device * obd, char * name) [static]
Definition at line 861 of file llog_test.c.
References CERROR, class_find_client_obd(), CWARN, obd_export::exp_obd, GOTO, LASSERT, llog_close(), LLOG_CONFIG_REPL_CTXT, llog_ctxt_put(), LLOG_F_IS_PLAIN, llog_get_context(), llog_init_handle(), llog_open(), LLOG_OPEN_EXISTS, llog_process(), llog_reverse_process(), LLOG_TEST_ORIG_CTXT, llog_ctxt::loc_exp, LUSTRE_MGC_NAME, obd_connect(), obd_disconnect(), obd_device::obd_name, obd_device::obd_uuid, plain_print_cb(), RETURN, obd_uuid::uuid, and verify_handle().
Referenced by llog_run_tests().
static int llog_test_7 (const struct lu_env * env, struct obd_device * obd) [static]
Definition at line 1062 of file llog_test.c.
References CERROR, CHANGELOG_REC, CHANGELOG_USER_REC, CWARN, ENTRY, GOTO, llog_ctxt_put(), LLOG_GEN_REC, llog_get_context(), LLOG_LOGID_MAGIC, llog_records, llog_test_7_sub(), LLOG_TEST_ORIG_CTXT, MDS_SETATTR64_REC, MDS_UNLINK64_REC, OST_SZ_REC, and RETURN.
Referenced by llog_run_tests().
static int llog_test_7_sub (const struct lu_env * env, struct llog_ctxt * ctxt) [static]
Definition at line 977 of file llog_test.c.
References CERROR, CWARN, ENTRY, GOTO, llog_handle::lgh_hdr, llog_close(), LLOG_DEL_PLAIN, llog_destroy(), llog_exist(), LLOG_F_IS_PLAIN, LLOG_F_ZAP_WHEN_EMPTY, LLOG_HDR_BITMAP_SIZE, llog_init_handle(), LLOG_NEXT_IDX, llog_open_create(), llog_process(), llog_records, llog_reverse_process(), llog_write(), RETURN, test_7_cancel_cb(), test_7_print_cb(), and verify_handle().
Referenced by llog_test_7().
static int llog_test_8 (const struct lu_env * env, struct obd_device * obd) [static]
Definition at line 1215 of file llog_test.c.
References cat_logid, CERROR, llog_handle::chd, cat_handle_data::chd_current_log, CWARN, DFID, dt_object::do_lu, ENTRY, GOTO, LASSERT, llog_handle::lgh_obj, llog_cat_add(), llog_cat_close(), llog_cat_process(), llog_ctxt_put(), LLOG_F_IS_CAT, llog_get_context(), llog_init_handle(), LLOG_MIN_REC_SIZE, llog_open(), LLOG_OPEN_EXISTS, LLOG_TEST_ORIG_CTXT, llog_truncate(), llog_mini_rec::lmr_hdr, llog_mini_rec::lmr_tail, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, llog_rec_tail::lrt_len, lu_object_fid(), lu_object_get(), lu_object_put(), name, PFID, RETURN, test_8_cb(), and llog_handle::u.
Referenced by llog_run_tests().
static int llog_test_9 (const struct lu_env * env, struct obd_device * obd) [static]
Definition at line 1390 of file llog_test.c.
References CERROR, CHANGELOG_REC, CHANGELOG_USER_REC, CWARN, ENTRY, GOTO, llog_ctxt_put(), llog_get_context(), LLOG_LOGID_MAGIC, llog_records, llog_test_9_sub(), LLOG_TEST_ORIG_CTXT, OBD_CFG_REC, and RETURN.
Referenced by llog_run_tests().
static int llog_test_9_sub (const struct lu_env * env, struct llog_ctxt * ctxt) [static]
Definition at line 1353 of file llog_test.c.
References CERROR, CWARN, DFID_NOBRACE, ENTRY, fid_to_logid(), GOTO, llog_handle::lgh_id, llog_close(), LLOG_F_IS_PLAIN, LLOG_F_ZAP_WHEN_EMPTY, llog_init_handle(), LLOG_NEXT_IDX, llog_open_create(), llog_records, llog_write(), logid_to_fid(), PFID, and RETURN.
Referenced by llog_test_9().
static int llog_test_cleanup (struct obd_device * obd) [static]
Definition at line 2025 of file llog_test.c.
References CERROR, dt_device::dd_lu_dev, lvfs_run_ctxt::dt, ENTRY, LCT_LOCAL, LCT_MG_THREAD, lu_device::ld_obd, llog_cleanup(), llog_get_context(), LLOG_TEST_ORIG_CTXT, lu_env_fini(), lu_env_init(), obd_device::obd_lvfs_ctxt, and RETURN.
Referenced by llog_test_setup().
static void __exit llog_test_exit (void) [static]
Definition at line 2132 of file llog_test.c.
References class_unregister_type().
static int __init llog_test_init (void) [static]
Definition at line 2126 of file llog_test.c.
References class_register_type().
static int llog_test_setup (struct obd_device * obd, struct lustre_cfg * lcfg) [static]
Definition at line 2045 of file llog_test.c.
References CERROR, cfs_rand(), class_name2obd(), CWARN, lvfs_run_ctxt::dt, ENTRY, GOTO, LASSERT, lu_context::lc_thread, lustre_cfg::lcfg_bufcount, lustre_cfg::lcfg_buflens, LCT_LOCAL, LCT_MG_THREAD, LCT_SERVER_SESSION, lu_env::le_ses, LLOG_CONFIG_ORIG_CTXT, llog_ctxt_put(), llog_get_context(), llog_osd_ops, llog_run_tests(), llog_setup(), llog_test_cleanup(), LLOG_TEST_ORIG_CTXT, llog_test_rand, llog_ctxt::loc_dir, lu2dt_dev(), lu_context_enter(), lu_context_exit(), lu_context_fini(), lu_context_init(), lu_env_fini(), lu_env_init(), lustre_cfg_string(), obd_device::obd_attached, obd_device::obd_lu_dev, obd_device::obd_lvfs_ctxt, obd_device::obd_olg, OBD_SET_CTXT_MAGIC(), obd_device::obd_set_up, and RETURN.
static int llog_truncate (const struct lu_env * env, struct dt_object * o) [static]
Definition at line 1153 of file llog_test.c.
References CDEBUG, CERROR, D_OTHER, dt_object::do_lu, dt_attr_get(), dt_attr_set(), dt_declare_attr_set(), dt_declare_punch(), dt_punch(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), ENTRY, GOTO, LA_SIZE, lu_attr::la_size, lu_attr::la_valid, LASSERT, lu_object::lo_dev, LPU64, lu2dt_dev(), OBD_OBJECT_EOF, RETURN, and stop.
Referenced by llog_test_8().
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Log test module")
module_exit (llog_test_exit)
module_init (llog_test_init)
MODULE_LICENSE ("GPL")
MODULE_VERSION (LUSTRE_VERSION_STRING)
static int plain_print_cb (const struct lu_env * env, struct llog_handle * llh, struct llog_rec_hdr * rec, void * data) [static]
Definition at line 708 of file llog_test.c.
References CDEBUG, CERROR, D_INFO, DFID, llog_handle::lgh_hdr, llog_handle::lgh_id, llog_log_hdr::llh_flags, LLOG_F_IS_PLAIN, logid_to_fid(), llog_rec_hdr::lrh_index, PFID, and RETURN.
Referenced by llog_test_5(), and llog_test_6().
static int test3_check_cb (const struct lu_env * env, struct llog_handle * lgh, struct llog_rec_hdr * rec, void * data) [static]
Definition at line 358 of file llog_test.c.
References CERROR, llog_gen::conn_cnt, lgr, llog_gen_rec::lgr_gen, and llog_rec_hdr::lrh_index.
Referenced by llog_test_3().
static int test3_check_n_add_cb (const struct lu_env * env, struct llog_handle * lgh, struct llog_rec_hdr * rec, void * data) [static]
Definition at line 288 of file llog_test.c.
References __u64, CERROR, llog_gen::conn_cnt, LASSERT, llog_handle::lgh_cur_offset, llog_handle::lgh_hdr, lgr, llog_gen_rec::lgr_gen, llog_log_hdr::llh_flags, llog_log_hdr::llh_hdr, llog_log_hdr::llh_size, LLOG_F_IS_FIXSIZE, LLOG_MIN_REC_SIZE, LLOG_NEXT_IDX, llog_write(), LPU64, llog_rec_hdr::lrh_index, and llog_rec_hdr::lrh_len.
Referenced by llog_test_3().
static int test_2_cancel_cb (const struct lu_env * env, struct llog_handle * llh, struct llog_rec_hdr * rec, void * data) [static]
Definition at line 145 of file llog_test.c.
References LLOG_DEL_RECORD.
Referenced by llog_test_2().
static int test_7_cancel_cb (const struct lu_env * env, struct llog_handle * llh, struct llog_rec_hdr * rec, void * data) [static]
Definition at line 969 of file llog_test.c.
References LLOG_DEL_RECORD.
Referenced by llog_test_7_sub().
static int test_7_print_cb (const struct lu_env * env, struct llog_handle * llh, struct llog_rec_hdr * rec, void * data) [static]
Definition at line 955 of file llog_test.c.
References CDEBUG, D_OTHER, DFID, llog_handle::lgh_id, logid_to_fid(), llog_rec_hdr::lrh_index, llog_rec_hdr::lrh_type, and PFID.
Referenced by llog_test_7_sub().
static int test_8_cb (const struct lu_env * env, struct llog_handle * llh, struct llog_rec_hdr * rec, void * data) [static]
Definition at line 1208 of file llog_test.c.
Referenced by llog_test_8().
static int verify_handle (char * test, struct llog_handle * llh, int num_recs) [static]
Definition at line 65 of file llog_test.c.
References CERROR, ext2_test_bit, llog_handle::lgh_hdr, llog_handle::lgh_last_idx, llog_log_hdr::llh_count, llog_log_hdr::llh_flags, LLOG_F_IS_CAT, LLOG_HDR_BITMAP, LLOG_HDR_BITMAP_SIZE, LLOG_HDR_TAIL, and RETURN.
Referenced by llog_test_1(), llog_test_10(), llog_test_2(), llog_test_3(), llog_test_4(), llog_test_6(), and llog_test_7_sub().
Variable Documentation
int cancel_count [static]
Definition at line 728 of file llog_test.c.
int cat_counter [static]
Definition at line 682 of file llog_test.c.
struct llog_logid cat_logid [static]
Definition at line 58 of file llog_test.c.
Referenced by llog_test_10(), llog_test_4(), llog_test_5(), and llog_test_8().
struct llog_changelog_rec lcr
Definition at line 950 of file llog_test.c.
Referenced by lustre_cfg_rec_new(), mgs_srpc_set_param_disk(), mgs_wlp_lcfg(), mgs_write_log_quota(), mgs_write_log_sys(), record_base(), record_lmv_setup(), record_lov_setup(), record_marker(), and sptlrpc_record_rule_set().
struct llog_changelog_user_rec lcur
Definition at line 951 of file llog_test.c.
struct llog_gen_rec lgr
Definition at line 952 of file llog_test.c.
Referenced by lustre_swab_llog_rec(), test3_check_cb(), and test3_check_n_add_cb().
struct obd_ops llog_obd_ops [static]
Initial value:
 {
        .o_owner       = THIS_MODULE,
        .o_setup       = llog_test_setup,
        .o_cleanup     = llog_test_cleanup,
}
Definition at line 2120 of file llog_test.c.
union { ... } llog_records [static]
Referenced by llog_test_7(), llog_test_7_sub(), llog_test_9(), and llog_test_9_sub().
int llog_test_rand [static]
Definition at line 56 of file llog_test.c.
Referenced by llog_run_tests(), llog_test_10(), llog_test_4(), and llog_test_setup().
struct llog_logid_rec llr
Definition at line 946 of file llog_test.c.
Referenced by lfsck_layout_assistant_fill_pos(), lfsck_layout_assistant_handler_p1(), lfsck_layout_assistant_req_fini(), lfsck_layout_assistant_req_init(), and lfsck_layout_scan_stripes().
struct llog_rec_hdr lrh
Definition at line 945 of file llog_test.c.
Referenced by tgt_reply_data_init().
struct llog_size_change_rec lscr
Definition at line 949 of file llog_test.c.
struct llog_setattr64_rec lsr64
Definition at line 948 of file llog_test.c.
struct llog_unlink64_rec lur
Definition at line 947 of file llog_test.c.
Referenced by check_and_prepare_update_record(), lustre_swab_llog_rec(), prepare_writing_updates(), sub_updates_write(), top_trans_stop(), update_recovery_attr_set(), update_recovery_create(), and update_recovery_exec().
struct llog_mini_rec packed
int plain_counter [static]
Definition at line 706 of file llog_test.c.
int test_3_paddings [static]
Definition at line 278 of file llog_test.c.
int test_3_rec_num [static]
Definition at line 276 of file llog_test.c.
off_t test_3_rec_off [static]
Definition at line 277 of file llog_test.c.
int test_3_start_idx [static]
Definition at line 279 of file llog_test.c.
struct obd_uuid uuid = { .uuid = "test_uuid" } [static]
Definition at line 57 of file llog_test.c.
Referenced by class_attach(), class_uuid_unparse(), client_common_fill_super(), gss_svc_handle_init(), ll_init_sbi(), llapi_get_target_uuids(), llapi_getname(), lmv_notify(), lov_notify(), lustre_lwp_connect(), lustre_register_lwp_item(), lustre_start_mgc(), lwp_setup(), mdt_quota_init(), mdt_stack_init(), mgc_apply_recover_logs(), mgs_write_log_lmv(), mgs_write_log_lov(), mgs_write_log_mdt0(), obd_get_uuid(), osp_init0(), qmt_dqacq(), qmt_glimpse_lock(), qmt_intent_policy(), setup_indexes(), and uuid_hash().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.