Lustre: lustre/llite/lloop.c File Reference
lustre/llite/lloop.c File Reference
#include <linux/module.h>
#include <linux/sched.h>
#include <linux/kthread.h>
#include <linux/fs.h>
#include <linux/file.h>
#include <linux/stat.h>
#include <linux/errno.h>
#include <linux/major.h>
#include <linux/wait.h>
#include <linux/blkdev.h>
#include <linux/blkpg.h>
#include <linux/init.h>
#include <linux/swap.h>
#include <linux/slab.h>
#include <linux/suspend.h>
#include <linux/writeback.h>
#include <linux/buffer_head.h>
#include <linux/completion.h>
#include <linux/highmem.h>
#include <linux/gfp.h>
#include <linux/pagevec.h>
#include <asm/uaccess.h>
#include <lustre_lib.h>
#include "llite_internal.h"
Data Structures
struct lloop_device
struct lloop_device::lo_request_data
Defines
#define LLOOP_MAX_SEGMENTS LNET_MAX_IOV
#define MAX_LOOP_DEFAULT 16
Enumerations
enum { LLOOP_UNBOUND, LLOOP_BOUND, LLOOP_RUNDOWN }
enum { LO_FLAGS_READ_ONLY = 1 }
Functions
static loff_t get_loop_size (struct lloop_device *lo, struct file *file)
static int do_bio_lustrebacked (struct lloop_device *lo, struct bio *head)
static void loop_add_bio (struct lloop_device *lo, struct bio *bio)
static unsigned int loop_get_bio (struct lloop_device *lo, struct bio **req)
static ll_mrf_ret loop_make_request (struct request_queue *q, struct bio *old_bio)
static void loop_handle_bio (struct lloop_device *lo, struct bio *bio)
static int loop_active (struct lloop_device *lo)
static int loop_thread (void *data)
static int loop_set_fd (struct lloop_device *lo, struct file *unused, struct block_device *bdev, struct file *file)
static int loop_clr_fd (struct lloop_device *lo, struct block_device *bdev, int count)
static int lo_open (struct block_device *bdev, fmode_t mode)
static void lo_release (struct gendisk *disk, fmode_t mode)
static int lo_ioctl (struct block_device *bdev, fmode_t mode, unsigned int cmd, unsigned long arg)
static enum llioc_iter lloop_ioctl (struct inode *unused, struct file *file, unsigned int cmd, unsigned long arg, void *magic, int *rcp)
static int __init lloop_init (void)
static void __exit lloop_exit (void)
module_param (max_loop, int, 0444)
MODULE_PARM_DESC (max_loop,"maximum of lloop_device")
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre virtual block device")
MODULE_VERSION (LUSTRE_VERSION_STRING)
MODULE_LICENSE ("GPL")
module_init (lloop_init)
module_exit (lloop_exit)
Variables
static int lloop_major
static int max_loop = MAX_LOOP_DEFAULT
static struct lloop_device * loop_dev
static struct gendisk ** disks
static struct mutex lloop_mutex
static void * ll_iocontrol_magic = NULL
static struct
block_device_operations lo_fops
Define Documentation
#define LLOOP_MAX_SEGMENTS LNET_MAX_IOV
Definition at line 111 of file lloop.c.
Referenced by do_bio_lustrebacked(), loop_get_bio(), and loop_set_fd().
#define MAX_LOOP_DEFAULT 16
Definition at line 162 of file lloop.c.
Referenced by lloop_init().
Enumeration Type Documentation
anonymous enum
Enumerator:
LLOOP_UNBOUND
LLOOP_BOUND
LLOOP_RUNDOWN
Definition at line 114 of file lloop.c.
anonymous enum
Enumerator:
LO_FLAGS_READ_ONLY
Definition at line 157 of file lloop.c.
Function Documentation
static int do_bio_lustrebacked (struct lloop_device * lo, struct bio * head) [static]
Definition at line 187 of file lloop.c.
References cl_io::ci_lockreq, cl_io::ci_obj, cl_io::ci_result, CILR_NEVER, CIT_MISC, cl_io_fini(), cl_io_init(), LASSERT, ll_dio_pages::ldp_nr, ll_dio_pages::ldp_offsets, ll_dio_pages::ldp_pages, ll_dio_pages::ldp_size, ll_direct_rw_pages(), ll_i2info(), ll_i2sbi(), ll_stats_ops_tally(), ll_inode_info::lli_clob, LLOOP_MAX_SEGMENTS, lloop_device::lo_backing_file, lloop_device::lo_env, lloop_device::lo_io, lloop_device::lo_offset, lloop_device::lo_pvec, LPROC_LL_BRW_READ, LPROC_LL_BRW_WRITE, ret, and WRITE.
Referenced by loop_handle_bio().
static loff_t get_loop_size (struct lloop_device * lo, struct file * file) [static]
Definition at line 169 of file lloop.c.
References lloop_device::lo_offset, lloop_device::lo_sizelimit, and size.
Referenced by loop_set_fd().
static void __exit lloop_exit (void) [static]
Definition at line 897 of file lloop.c.
References disks, ll_iocontrol_magic, ll_iocontrol_unregister(), lloop_major, max_loop, and OBD_FREE.
static int __init lloop_init (void) [static]
Definition at line 813 of file lloop.c.
References CDEBUG, CERROR, cmdlist, CWARN, D_CONFIG, disks, LL_IOC_LLOOP_ATTACH, LL_IOC_LLOOP_DETACH_BYDEV, ll_iocontrol_magic, ll_iocontrol_register(), ll_iocontrol_unregister(), lloop_ioctl(), lloop_major, lloop_mutex, lloop_device::lo_bh_wait, lloop_device::lo_ctl_mutex, lloop_device::lo_lock, lloop_device::lo_number, lloop_device::lo_queue, lloop_device::lo_sem, max_loop, MAX_LOOP_DEFAULT, OBD_ALLOC_WAIT, and OBD_FREE.
static enum llioc_iter lloop_ioctl (struct inode * unused, struct file * file, unsigned int cmd, unsigned long arg, void * magic, int * rcp) [static]
Definition at line 718 of file lloop.c.
References __user, blkdev_get_by_dev, CWARN, disks, GOTO, LL_IOC_LLOOP_ATTACH, LL_IOC_LLOOP_DETACH_BYDEV, ll_iocontrol_magic, LLIOC_CONT, LLIOC_STOP, LLOOP_BOUND, lloop_major, lloop_mutex, LLOOP_UNBOUND, lloop_device::lo_device, lloop_device::lo_state, loop_clr_fd(), loop_set_fd(), max_loop, and MKDEV.
Referenced by lloop_init().
static int lo_ioctl (struct block_device * bdev, fmode_t mode, unsigned int cmd, unsigned long arg) [static]
Definition at line 660 of file lloop.c.
References __user, fid_zero(), ll_i2info(), LL_IOC_LLOOP_DETACH, LL_IOC_LLOOP_INFO, ll_inode_info::lli_fid, LLOOP_BOUND, lloop_mutex, lloop_device::lo_backing_file, lloop_device::lo_state, and loop_clr_fd().
static int lo_open (struct block_device * bdev, fmode_t mode) [static]
Definition at line 631 of file lloop.c.
References lloop_device::lo_ctl_mutex, and lloop_device::lo_refcnt.
static void lo_release (struct gendisk * disk, fmode_t mode) [static]
Definition at line 647 of file lloop.c.
References lloop_device::lo_ctl_mutex, and lloop_device::lo_refcnt.
static int loop_active (struct lloop_device * lo) [inline, static]
Definition at line 434 of file lloop.c.
References LLOOP_RUNDOWN, lloop_device::lo_pending, and lloop_device::lo_state.
Referenced by loop_thread().
static void loop_add_bio (struct lloop_device * lo, struct bio * bio) [static]
Definition at line 290 of file lloop.c.
References lloop_device::lo_bh_wait, lloop_device::lo_bio, lloop_device::lo_biotail, lloop_device::lo_lock, and lloop_device::lo_pending.
Referenced by loop_make_request().
static int loop_clr_fd (struct lloop_device * lo, struct block_device * bdev, int count) [static]
Definition at line 594 of file lloop.c.
References disks, LLOOP_BOUND, LLOOP_RUNDOWN, LLOOP_UNBOUND, lloop_device::lo_backing_file, lloop_device::lo_bh_wait, lloop_device::lo_device, lloop_device::lo_flags, lloop_device::lo_lock, lloop_device::lo_number, lloop_device::lo_offset, lloop_device::lo_refcnt, lloop_device::lo_sem, lloop_device::lo_sizelimit, lloop_device::lo_state, and lloop_device::old_gfp_mask.
Referenced by lloop_ioctl(), and lo_ioctl().
static unsigned int loop_get_bio (struct lloop_device * lo, struct bio ** req) [static]
Definition at line 310 of file lloop.c.
References CDEBUG, D_INFO, LASSERT, LLOOP_MAX_SEGMENTS, lloop_device::lo_bio, lloop_device::lo_biotail, lloop_device::lo_lock, and unlikely.
Referenced by loop_thread().
static void loop_handle_bio (struct lloop_device * lo, struct bio * bio) [inline, static]
Definition at line 415 of file lloop.c.
References do_bio_lustrebacked().
Referenced by loop_thread().
static ll_mrf_ret loop_make_request (struct request_queue * q, struct bio * old_bio) [static]
Definition at line 362 of file lloop.c.
References CDEBUG, CERROR, D_INFO, LL_MRF_RETURN, LLOOP_BOUND, lloop_device::lo_flags, LO_FLAGS_READ_ONLY, lloop_device::lo_lock, lloop_device::lo_state, loop_add_bio(), READ, and WRITE.
Referenced by loop_set_fd().
static int loop_set_fd (struct lloop_device * lo, struct file * unused, struct block_device * bdev, struct file * file) [static]
Definition at line 516 of file lloop.c.
References blk_queue_max_segments, disks, error, FMODE_WRITE, get_loop_size(), LL_SUPER_MAGIC, LLOOP_MAX_SEGMENTS, LLOOP_UNBOUND, lloop_device::lo_backing_file, lloop_device::lo_bio, lloop_device::lo_biotail, lloop_device::lo_blocksize, lloop_device::lo_device, lloop_device::lo_flags, LO_FLAGS_READ_ONLY, lloop_device::lo_number, lloop_device::lo_queue, lloop_device::lo_sem, lloop_device::lo_sizelimit, lloop_device::lo_state, loop_make_request(), loop_thread(), mapping, lloop_device::old_gfp_mask, and size.
Referenced by lloop_ioctl().
static int loop_thread (void * data) [static]
Definition at line 444 of file lloop.c.
References CDEBUG, cl_env_get(), cl_env_put(), CWARN, D_INFO, GOTO, LASSERT, ll_dio_pages::ldp_offsets, ll_dio_pages::ldp_pages, LLOOP_BOUND, LLOOP_RUNDOWN, lloop_device::lo_bh_wait, lloop_device::lo_env, lloop_device::lo_lock, lloop_device::lo_number, lloop_device::lo_pending, lloop_device::lo_pvec, lloop_device::lo_requests, lloop_device::lo_sem, lloop_device::lo_state, loop_active(), loop_get_bio(), loop_handle_bio(), lloop_device::lo_request_data::lrd_offsets, and lloop_device::lo_request_data::lrd_pages.
Referenced by loop_set_fd().
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre virtual block device")
module_exit (lloop_exit)
module_init (lloop_init)
MODULE_LICENSE ("GPL")
module_param (max_loop , int , 0444)
MODULE_PARM_DESC (max_loop , "maximum of lloop_device")
MODULE_VERSION (LUSTRE_VERSION_STRING)
Variable Documentation
struct gendisk** disks [static]
Definition at line 165 of file lloop.c.
Referenced by lloop_exit(), lloop_init(), lloop_ioctl(), loop_clr_fd(), and loop_set_fd().
void* ll_iocontrol_magic = NULL [static]
Definition at line 167 of file lloop.c.
Referenced by lloop_exit(), lloop_init(), and lloop_ioctl().
int lloop_major [static]
Definition at line 161 of file lloop.c.
Referenced by lloop_exit(), lloop_init(), and lloop_ioctl().
struct mutex lloop_mutex [static]
Definition at line 166 of file lloop.c.
Referenced by lloop_init(), lloop_ioctl(), and lo_ioctl().
struct block_device_operations lo_fops [static]
Initial value:
 {
        .owner =        THIS_MODULE,
        .open =         lo_open,
        .release =      lo_release,
        .ioctl =        lo_ioctl,
}
Definition at line 704 of file lloop.c.
struct lloop_device* loop_dev [static]
Definition at line 164 of file lloop.c.
int max_loop = MAX_LOOP_DEFAULT [static]
Definition at line 163 of file lloop.c.
Referenced by lloop_exit(), lloop_init(), and lloop_ioctl().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.