Lustre: lustre/utils/llverfs.c File Reference
lustre/utils/llverfs.c File Reference
#include <features.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <fcntl.h>
#include <unistd.h>
#include <limits.h>
#include <errno.h>
#include <getopt.h>
#include <time.h>
#include <dirent.h>
#include <mntent.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/vfs.h>
#include <sys/time.h>
#include <gnu/stubs.h>
Data Structures
struct block_data
Defines
#define ONE_MB (1024 * 1024)
#define ONE_GB ((unsigned long long)(1024 * 1024 * 1024))
#define BLOCKSIZE 4096
Functions
void usage (int status)
static int open_file (const char *file, int flag)
int verify_chunk (char *chunk_buf, const size_t chunksize, unsigned long long chunk_off, const unsigned long long time_st, const unsigned long long inode_st, const char *file)
void fill_chunk (char *chunk_buf, size_t chunksize, loff_t chunk_off, const time_t time_st, const ino_t inode_st)
int write_retry (int fd, const char *chunk_buf, size_t nrequested, unsigned long long offset, const char *file)
int write_chunks (int fd, unsigned long long offset, unsigned long long write_end, char *chunk_buf, size_t chunksize, const time_t time_st, const ino_t inode_st, const char *file)
int read_chunks (int fd, unsigned long long offset, unsigned long long read_end, char *chunk_buf, size_t chunksize, const time_t time_st, const ino_t inode_st, const char *file)
char * new_file (char *tempfile, char *cur_dir, int file_num)
char * new_dir (char *tempdir, int dir_num)
static unsigned long long calc_total_bytes (const char *op)
void show_rate (char *op, char *filename, const struct timeval *start_time, const unsigned long long total_bytes, const unsigned long long curr_bytes)
static int dir_write (char *chunk_buf, size_t chunksize, time_t time_st, unsigned long dir_num)
static int dir_read (char *chunk_buf, size_t chunksize, time_t time_st, unsigned long dir_num)
int main (int argc, char **argv)
Variables
static char * progname
static unsigned verbose = 1
static int readoption
static int writeoption
char * testdir
static unsigned full = 1
static int error_count
char filecount [PATH_MAX]
static unsigned long num_files
static loff_t file_size = 4*ONE_GB
static unsigned files_in_dir = 32
static unsigned num_dirs = 30000
const int dirmode = S_IRWXU | S_IRGRP | S_IXGRP | S_IROTH | S_IXOTH
static int isatty_flag
static int perms = S_IRWXU | S_IRGRP | S_IROTH
static struct option const longopts []
Define Documentation
#define BLOCKSIZE 4096
Definition at line 103 of file llverfs.c.
#define ONE_GB ((unsigned long long)(1024 * 1024 * 1024))
Definition at line 102 of file llverfs.c.
#define ONE_MB (1024 * 1024)
Definition at line 101 of file llverfs.c.
Function Documentation
static unsigned long long calc_total_bytes (const char * op) [static]
Definition at line 416 of file llverfs.c.
References file_size, files_in_dir, full, num_dirs, progname, and testdir.
Referenced by dir_read(), and dir_write().
static int dir_read (char * chunk_buf, size_t chunksize, time_t time_st, unsigned long dir_num) [static]
Definition at line 646 of file llverfs.c.
References calc_total_bytes(), file_size, files_in_dir, new_dir(), new_file(), num_dirs, num_files, open_file(), progname, read_chunks(), ret, show_rate(), and verbose.
Referenced by main().
static int dir_write (char * chunk_buf, size_t chunksize, time_t time_st, unsigned long dir_num) [static]
Definition at line 518 of file llverfs.c.
References calc_total_bytes(), dirmode, file_size, filecount, files_in_dir, full, new_dir(), new_file(), num_dirs, num_files, open_file(), progname, ret, show_rate(), testdir, verbose, and write_chunks().
Referenced by main().
void fill_chunk (char * chunk_buf, size_t chunksize, loff_t chunk_off, const time_t time_st, const ino_t inode_st)
Definition at line 215 of file llverfs.c.
References block_data::bd_inode, block_data::bd_offset, block_data::bd_time, and BLOCKSIZE.
int main (int argc, char ** argv)
Definition at line 723 of file llverfs.c.
References dir_read(), dir_write(), dirmode, error, error_count, file_size, filecount, files_in_dir, full, isatty_flag, longopts, num_dirs, num_files, ONE_MB, optarg, optind, progname, readoption, testdir, usage, verbose, and writeoption.
char* new_dir (char * tempdir, int dir_num)
Definition at line 406 of file llverfs.c.
References testdir.
Referenced by dir_read(), and dir_write().
char* new_file (char * tempfile, char * cur_dir, int file_num)
Definition at line 397 of file llverfs.c.
Referenced by dir_read(), and dir_write().
static int open_file (const char * file, int flag) [static]
Definition at line 173 of file llverfs.c.
References perms, and progname.
Referenced by dir_read(), and dir_write().
int read_chunks (int fd, unsigned long long offset, unsigned long long read_end, char * chunk_buf, size_t chunksize, const time_t time_st, const ino_t inode_st, const char * file)
Definition at line 320 of file llverfs.c.
References error_count, full, ONE_GB, progname, and verify_chunk().
void show_rate (char * op, char * filename, const struct timeval * start_time, const unsigned long long total_bytes, const unsigned long long curr_bytes)
Definition at line 451 of file llverfs.c.
References isatty_flag, ONE_MB, and verbose.
void usage (int status)
Definition at line 148 of file llverfs.c.
References progname.
int verify_chunk (char * chunk_buf, const size_t chunksize, unsigned long long chunk_off, const unsigned long long time_st, const unsigned long long inode_st, const char * file)
Definition at line 187 of file llverfs.c.
References block_data::bd_inode, block_data::bd_offset, block_data::bd_time, BLOCKSIZE, and progname.
int write_chunks (int fd, unsigned long long offset, unsigned long long write_end, char * chunk_buf, size_t chunksize, const time_t time_st, const ino_t inode_st, const char * file)
Definition at line 280 of file llverfs.c.
References fill_chunk(), full, ONE_GB, progname, ret, and write_retry().
int write_retry (int fd, const char * chunk_buf, size_t nrequested, unsigned long long offset, const char * file)
Definition at line 245 of file llverfs.c.
References error_count, and progname.
Variable Documentation
const int dirmode = S_IRWXU | S_IRGRP | S_IXGRP | S_IROTH | S_IXOTH
Definition at line 123 of file llverfs.c.
Referenced by dir_write(), and main().
int error_count [static]
Definition at line 117 of file llverfs.c.
Referenced by main(), read_chunks(), and write_retry().
loff_t file_size = 4*ONE_GB [static]
Definition at line 120 of file llverfs.c.
char filecount[PATH_MAX]
Definition at line 118 of file llverfs.c.
Referenced by dir_write(), and main().
unsigned files_in_dir = 32 [static]
Definition at line 121 of file llverfs.c.
Referenced by calc_total_bytes(), dir_read(), dir_write(), and main().
unsigned full = 1 [static]
Definition at line 116 of file llverfs.c.
Referenced by calc_total_bytes(), dir_write(), main(), read_chunks(), and write_chunks().
int isatty_flag [static]
Definition at line 124 of file llverfs.c.
Referenced by main(), and show_rate().
struct option const longopts[] [static]
Initial value:
{
        { "chunksize", required_argument, 0, 'c' },
        { "help", no_argument, 0, 'h' },
        { "offset", required_argument, 0, 'o' },
        { "long", no_argument, 0, 'l' },
        { "full", no_argument, 0, 'l' },
        { "partial", required_argument, 0, 'p' },
        { "quiet", required_argument, 0, 'q' },
        { "read", no_argument, 0, 'r' },
        { "filesize", no_argument, 0, 's' },
        { "timestamp", required_argument, 0, 't' },
        { "verbose", no_argument, 0, 'v' },
        { "write", no_argument, 0, 'w' },
        { 0, 0, 0, 0}
}
Definition at line 127 of file llverfs.c.
unsigned num_dirs = 30000 [static]
Definition at line 122 of file llverfs.c.
Referenced by calc_total_bytes(), dir_read(), dir_write(), and main().
unsigned long num_files [static]
Definition at line 119 of file llverfs.c.
Referenced by dir_read(), dir_write(), and main().
int perms = S_IRWXU | S_IRGRP | S_IROTH [static]
Definition at line 125 of file llverfs.c.
Referenced by main(), mdt_identity_parse_downcall(), and open_file().
char* progname [static]
Definition at line 111 of file llverfs.c.
int readoption [static]
Definition at line 113 of file llverfs.c.
Referenced by main().
char* testdir
Definition at line 115 of file llverfs.c.
Referenced by calc_total_bytes(), create_file(), dir_write(), grouplock_file(), main(), new_dir(), remove_file(), and rw_file().
unsigned verbose = 1 [static]
Definition at line 112 of file llverfs.c.
int writeoption [static]
Definition at line 114 of file llverfs.c.
Referenced by main().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.