Lustre: lustre/utils/llverdev.c File Reference
lustre/utils/llverdev.c File Reference
#include <features.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include <fcntl.h>
#include <unistd.h>
#include <limits.h>
#include <errno.h>
#include <getopt.h>
#include <time.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/ioctl.h>
#include <sys/mount.h>
#include <sys/time.h>
#include <gnu/stubs.h>
Data Structures
struct block_data
Defines
#define _FILE_OFFSET_BITS 64
#define ONE_MB (1024 * 1024)
#define ONE_GB (1024 * 1024 * 1024)
#define HALF_MB (ONE_MB / 2)
#define ONE_KB 1024
#define HALF_KB (ONE_KB / 2)
#define BLOCKSIZE 4096
Functions
void usage (int status)
static int open_dev (const char *devname, int mode)
static loff_t sizeof_dev (int fd)
int verify_chunk (char *chunk_buf, const size_t chunksize, unsigned long long chunk_off, const unsigned long long time_st, const unsigned long long inode_st, const char *file)
void fill_chunk (char *chunk_buf, size_t chunksize, loff_t chunk_off, const time_t time_st, const ino_t inode_st)
void show_rate (char *op, unsigned long long offset, unsigned long long *count)
size_t write_retry (int fd, const char *chunk_buf, size_t nrequested, unsigned long long offset, const char *file)
int write_chunks (int fd, unsigned long long offset, unsigned long long write_end, char *chunk_buf, size_t chunksize, const time_t time_st, const ino_t inode_st, const char *file)
int read_chunks (int fd, unsigned long long offset, unsigned long long read_end, char *chunk_buf, size_t chunksize, const time_t time_st, const ino_t inode_st, const char *file)
int main (int argc, char **argv)
Variables
static char * progname
static unsigned verbose = 1
static int readoption
static int writeoption
const char * devname
static unsigned full = 1
static int error_count
static int isatty_flag
static struct option const longopts []
Define Documentation
#define _FILE_OFFSET_BITS 64
Definition at line 69 of file llverdev.c.
Referenced by file_create().
#define BLOCKSIZE 4096
Definition at line 100 of file llverdev.c.
Referenced by fill_chunk(), main(), and verify_chunk().
#define HALF_KB (ONE_KB / 2)
Definition at line 99 of file llverdev.c.
#define HALF_MB (ONE_MB / 2)
Definition at line 97 of file llverdev.c.
#define ONE_GB (1024 * 1024 * 1024)
Definition at line 96 of file llverdev.c.
Referenced by read_chunks(), sizeof_dev(), and write_chunks().
#define ONE_KB 1024
Definition at line 98 of file llverdev.c.
Referenced by main(), and show_rate().
#define ONE_MB (1024 * 1024)
Definition at line 95 of file llverdev.c.
Function Documentation
void fill_chunk (char * chunk_buf, size_t chunksize, loff_t chunk_off, const time_t time_st, const ino_t inode_st)
Definition at line 280 of file llverdev.c.
References block_data::bd_inode, block_data::bd_offset, block_data::bd_time, and BLOCKSIZE.
Referenced by write_chunks().
int main (int argc, char ** argv)
Definition at line 512 of file llverdev.c.
References BLOCKSIZE, devname, error, error_count, full, isatty_flag, longopts, mode, ONE_KB, ONE_MB, open_dev(), optarg, optind, progname, read_chunks(), readoption, sizeof_dev(), usage, verbose, write_chunks(), and writeoption.
static int open_dev (const char * devname, int mode) [static]
Definition at line 164 of file llverdev.c.
References progname.
Referenced by main().
int read_chunks (int fd, unsigned long long offset, unsigned long long read_end, char * chunk_buf, size_t chunksize, const time_t time_st, const ino_t inode_st, const char * file)
Definition at line 427 of file llverdev.c.
References error_count, full, ONE_GB, progname, show_rate(), verbose, and verify_chunk().
Referenced by dir_read(), and main().
void show_rate (char * op, unsigned long long offset, unsigned long long * count)
Definition at line 296 of file llverdev.c.
References isatty_flag, now(), ONE_KB, and ONE_MB.
Referenced by dir_read(), dir_write(), read_chunks(), and write_chunks().
static loff_t sizeof_dev (int fd) [static]
Definition at line 197 of file llverdev.c.
References devname, ONE_GB, progname, and verbose.
Referenced by main().
void usage (int status)
Definition at line 138 of file llverdev.c.
References progname.
int verify_chunk (char * chunk_buf, const size_t chunksize, unsigned long long chunk_off, const unsigned long long time_st, const unsigned long long inode_st, const char * file)
Definition at line 250 of file llverdev.c.
References block_data::bd_inode, block_data::bd_offset, block_data::bd_time, BLOCKSIZE, error_count, and progname.
Referenced by read_chunks().
int write_chunks (int fd, unsigned long long offset, unsigned long long write_end, char * chunk_buf, size_t chunksize, const time_t time_st, const ino_t inode_st, const char * file)
Definition at line 371 of file llverdev.c.
References fill_chunk(), full, ONE_GB, progname, ret, show_rate(), verbose, and write_retry().
Referenced by dir_write(), and main().
size_t write_retry (int fd, const char * chunk_buf, size_t nrequested, unsigned long long offset, const char * file)
Definition at line 336 of file llverdev.c.
References error_count, and progname.
Referenced by write_chunks().
Variable Documentation
const char* devname
Definition at line 112 of file llverdev.c.
Referenced by client_lwp_config_process(), jt_blockdev_attach(), lmd_parse(), main(), mgs_setparam(), osd_dirent_check_repair(), and sizeof_dev().
int error_count [static]
Definition at line 114 of file llverdev.c.
Referenced by main(), read_chunks(), verify_chunk(), and write_retry().
unsigned full = 1 [static]
Definition at line 113 of file llverdev.c.
Referenced by main(), osd_inode_iteration(), read_chunks(), and write_chunks().
int isatty_flag [static]
Definition at line 115 of file llverdev.c.
Referenced by main(), and show_rate().
struct option const longopts[] [static]
Initial value:
{
        { "chunksize", required_argument, 0, 'c' },
        { "force", no_argument, 0, 'f' },
        { "help", no_argument, 0, 'h' },
        { "offset", required_argument, 0, 'o' },
        { "partial", required_argument, 0, 'p' },
        { "quiet", required_argument, 0, 'q' },
        { "read", no_argument, 0, 'r' },
        { "timestamp", required_argument, 0, 't' },
        { "verbose", no_argument, 0, 'v' },
        { "write", no_argument, 0, 'w' },
        { "long", no_argument, 0, 'l' },
        { "full", no_argument, 0, 'l' },
        { 0, 0, 0, 0}
}
Definition at line 117 of file llverdev.c.
char* progname [static]
Definition at line 108 of file llverdev.c.
int readoption [static]
Definition at line 110 of file llverdev.c.
Referenced by main().
unsigned verbose = 1 [static]
Definition at line 109 of file llverdev.c.
int writeoption [static]
Definition at line 111 of file llverdev.c.
Referenced by main().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.