Lustre: lustre/lmv/lmv_intent.c File Reference
lustre/lmv/lmv_intent.c File Reference
#include <linux/slab.h>
#include <linux/module.h>
#include <linux/init.h>
#include <linux/pagemap.h>
#include <linux/math64.h>
#include <linux/seq_file.h>
#include <linux/namei.h>
#include <lustre_intent.h>
#include <obd_support.h>
#include <lustre/lustre_idl.h>
#include <lustre_lib.h>
#include <lustre_net.h>
#include <lustre_dlm.h>
#include <lustre_mdc.h>
#include <obd_class.h>
#include <lprocfs_status.h>
#include "lmv_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LMV
Functions
static int lmv_intent_remote (struct obd_export *exp, struct lookup_intent *it, const struct lu_fid *parent_fid, struct ptlrpc_request **reqp, ldlm_blocking_callback cb_blocking, __u64 extra_lock_flags)
int lmv_revalidate_slaves (struct obd_export *exp, const struct lmv_stripe_md *lsm, ldlm_blocking_callback cb_blocking, int extra_lock_flags)
static int lmv_intent_open (struct obd_export *exp, struct md_op_data *op_data, struct lookup_intent *it, struct ptlrpc_request **reqp, ldlm_blocking_callback cb_blocking, __u64 extra_lock_flags)
static int lmv_intent_lookup (struct obd_export *exp, struct md_op_data *op_data, struct lookup_intent *it, struct ptlrpc_request **reqp, ldlm_blocking_callback cb_blocking, __u64 extra_lock_flags)
int lmv_intent_lock (struct obd_export *exp, struct md_op_data *op_data, struct lookup_intent *it, struct ptlrpc_request **reqp, ldlm_blocking_callback cb_blocking, __u64 extra_lock_flags)
Define Documentation
#define DEBUG_SUBSYSTEM S_LMV
Definition at line 37 of file lmv_intent.c.
Function Documentation
int lmv_intent_lock (struct obd_export * exp, struct md_op_data * op_data, struct lookup_intent * it, struct ptlrpc_request ** reqp, ldlm_blocking_callback cb_blocking, __u64 extra_lock_flags)
Definition at line 469 of file lmv_intent.c.
References CDEBUG, lustre_handle::cookie, D_INODE, DFID, ENTRY, obd_export::exp_obd, fid_is_sane(), IT_GETATTR, IT_LAYOUT, lookup_intent::it_lock_handle, lookup_intent::it_lock_mode, IT_LOOKUP, lookup_intent::it_op, IT_OPEN, lookup_intent::it_remote_lock_handle, lookup_intent::it_remote_lock_mode, LASSERT, LBUG, ldlm_lock_decref(), LL_IT2STR, lmv_check_connect(), lmv_intent_lookup(), lmv_intent_open(), md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_name, md_op_data::op_namelen, PFID, and RETURN.
static int lmv_intent_lookup (struct obd_export * exp, struct md_op_data * op_data, struct lookup_intent * it, struct ptlrpc_request ** reqp, ldlm_blocking_callback cb_blocking, __u64 extra_lock_flags) [static]
Definition at line 354 of file lmv_intent.c.
References CDEBUG, D_INODE, DFID, DISP_ENQ_COMPLETE, DISP_LOOKUP_NEG, ENTRY, obd_export::exp_obd, fid_is_sane(), fid_zero(), lookup_intent::it_disposition, it_disposition(), lookup_intent::it_request, lmv_oinfo::lmo_fid, lmv_oinfo::lmo_mds, obd_device::lmv, lmv_find_target(), lmv_get_target(), lmv_intent_remote(), lmv_is_known_hash_type(), lmv_locate_mds(), lmv_need_try_all_stripes(), lmv_revalidate_slaves(), lmv_stripe_md::lsm_md_hash_type, lmv_stripe_md::lsm_md_magic, lmv_stripe_md::lsm_md_oinfo, lmv_stripe_md::lsm_md_stripe_count, lmv_tgt_desc::ltd_exp, lmv_tgt_desc::ltd_idx, mdt_body::mbo_valid, md_intent_lock(), MDS_CROSS_REF, OBD_MD_MDS, md_op_data::op_bias, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_mds, md_op_data::op_mea1, md_op_data::op_mea2, md_op_data::op_name, PFID, ptlrpc_req_finished(), req_capsule_server_get(), RETURN, RMF_MDT_BODY, obd_device::u, and unlikely.
Referenced by lmv_intent_lock().
static int lmv_intent_open (struct obd_export * exp, struct md_op_data * op_data, struct lookup_intent * it, struct ptlrpc_request ** reqp, ldlm_blocking_callback cb_blocking, __u64 extra_lock_flags) [static]
Definition at line 265 of file lmv_intent.c.
References CDEBUG, D_INODE, DFID, DISP_LOOKUP_NEG, DISP_OPEN_CREATE, DISP_OPEN_OPEN, ENTRY, obd_export::exp_obd, fid_is_sane(), fid_is_zero(), IT_CREAT, lookup_intent::it_disposition, lookup_intent::it_flags, lookup_intent::it_op, LASSERT, obd_device::lmv, lmv_fid_alloc(), lmv_find_target(), lmv_intent_remote(), lmv_locate_mds(), lmv_tgt_desc::ltd_exp, lmv_tgt_desc::ltd_idx, mdt_body::mbo_valid, md_intent_lock(), MDS_OPEN_BY_FID, OBD_MD_MDS, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_mds, md_op_data::op_mea1, md_op_data::op_name, PFID, req_capsule_server_get(), RETURN, RMF_MDT_BODY, obd_device::u, and unlikely.
Referenced by lmv_intent_lock().
static int lmv_intent_remote (struct obd_export * exp, struct lookup_intent * it, const struct lu_fid * parent_fid, struct ptlrpc_request ** reqp, ldlm_blocking_callback cb_blocking, __u64 extra_lock_flags) [static]
Definition at line 58 of file lmv_intent.c.
References CDEBUG, lustre_handle::cookie, D_INODE, DFID, ENTRY, EXIT, obd_export::exp_obd, fid_is_sane(), GOTO, IT_GETATTR, lookup_intent::it_lock_handle, lookup_intent::it_lock_mode, IT_LOOKUP, lookup_intent::it_op, IT_OPEN, lookup_intent::it_remote_lock_handle, lookup_intent::it_remote_lock_mode, lookup_intent::it_request, LASSERT, ldlm_lock_decref(), obd_device::lmv, lmv_find_target(), lmv_tgt_desc::ltd_exp, lmv_tgt_desc::ltd_idx, mdt_body::mbo_fid1, mdt_body::mbo_valid, md_intent_lock(), MDS_CROSS_REF, OBD_ALLOC_PTR, OBD_FREE_PTR, OBD_MD_MDS, md_op_data::op_bias, md_op_data::op_data, md_op_data::op_fid1, md_op_data::op_fid2, PFID, ptlrpc_req_finished(), req_capsule_server_get(), RETURN, RMF_MDT_BODY, and obd_device::u.
Referenced by lmv_intent_lookup(), and lmv_intent_open().
int lmv_revalidate_slaves (struct obd_export * exp, const struct lmv_stripe_md * lsm, ldlm_blocking_callback cb_blocking, int extra_lock_flags)
revalidate slaves has some problems, temporarily return, we may not need that
Loop over the stripe information, check validity and update them from MDS if needed.
Definition at line 155 of file lmv_intent.c.
References CDEBUG, cleanup(), lustre_handle::cookie, D_INODE, DFID, ENTRY, obd_export::exp_obd, GOTO, IT_GETATTR, lookup_intent::it_lock_handle, lookup_intent::it_lock_mode, lookup_intent::it_op, ldlm_lock_decref(), lmv_oinfo::lmo_fid, lmv_oinfo::lmo_root, obd_device::lmv, lmv_locate_mds(), lmv_stripe_md::lsm_md_oinfo, lmv_stripe_md::lsm_md_stripe_count, lmv_tgt_desc::ltd_exp, lmv_tgt_desc::ltd_idx, LTIME_S, mdt_body::mbo_atime, mdt_body::mbo_blocks, mdt_body::mbo_ctime, mdt_body::mbo_mtime, mdt_body::mbo_nlink, mdt_body::mbo_size, md_intent_lock(), md_set_lock_data(), OBD_ALLOC_PTR, OBD_FREE_PTR, md_op_data::op_data, md_op_data::op_fid1, md_op_data::op_fid2, PFID, ptlrpc_req_finished(), req_capsule_server_get(), RETURN, RMF_MDT_BODY, ptlrpc_request::rq_pill, set_nlink(), and obd_device::u.
Referenced by lmv_intent_lookup(), and lmv_merge_attr().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.