Lustre: lustre/lmv/lmv_obd.c File Reference
lustre/lmv/lmv_obd.c File Reference
#include <linux/slab.h>
#include <linux/module.h>
#include <linux/init.h>
#include <linux/user_namespace.h>
#include <linux/pagemap.h>
#include <linux/mm.h>
#include <linux/math64.h>
#include <linux/seq_file.h>
#include <linux/namei.h>
#include <lustre/lustre_idl.h>
#include <obd_support.h>
#include <lustre_lib.h>
#include <lustre_net.h>
#include <obd_class.h>
#include <lustre_lmv.h>
#include <lprocfs_status.h>
#include <cl_object.h>
#include <lustre_fid.h>
#include <lustre_ioctl.h>
#include <lustre_kernelcomm.h>
#include "lmv_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LMV
#define MAX_STRING_SIZE 128
#define md_op_data_fid(op_data, fl)
Functions
static void lmv_activate_target (struct lmv_obd *lmv, struct lmv_tgt_desc *tgt, int activate)
static int lmv_set_mdc_active (struct lmv_obd *lmv, const struct obd_uuid *uuid, int activate)
Error codes:.
struct obd_uuid * lmv_get_uuid (struct obd_export *exp)
static int lmv_notify (struct obd_device *obd, struct obd_device *watched, enum obd_notify_event ev, void *data)
static int lmv_connect (const struct lu_env *env, struct obd_export **exp, struct obd_device *obd, struct obd_uuid *cluuid, struct obd_connect_data *data, void *localdata)
This is fake connect function.
static int lmv_init_ea_size (struct obd_export *exp, __u32 easize, __u32 def_easize)
int lmv_connect_mdc (struct obd_device *obd, struct lmv_tgt_desc *tgt)
static void lmv_del_target (struct lmv_obd *lmv, int index)
static int lmv_add_target (struct obd_device *obd, struct obd_uuid *uuidp, __u32 index, int gen)
int lmv_check_connect (struct obd_device *obd)
static int lmv_disconnect_mdc (struct obd_device *obd, struct lmv_tgt_desc *tgt)
static int lmv_disconnect (struct obd_export *exp)
static int lmv_fid2path (struct obd_export *exp, int len, void *karg, void __user *uarg)
static int lmv_hsm_req_count (struct lmv_obd *lmv, const struct hsm_user_request *hur, const struct lmv_tgt_desc *tgt_mds)
static void lmv_hsm_req_build (struct lmv_obd *lmv, struct hsm_user_request *hur_in, const struct lmv_tgt_desc *tgt_mds, struct hsm_user_request *hur_out)
static int lmv_hsm_ct_unregister (struct lmv_obd *lmv, unsigned int cmd, int len, struct lustre_kernelcomm *lk, void __user *uarg)
static int lmv_hsm_ct_register (struct lmv_obd *lmv, unsigned int cmd, int len, struct lustre_kernelcomm *lk, __user void *uarg)
static int lmv_iocontrol (unsigned int cmd, struct obd_export *exp, int len, void *karg, void __user *uarg)
static int lmv_placement_policy (struct obd_device *obd, struct md_op_data *op_data, u32 *mds)
This is _inode_ placement policy function (not name).
int __lmv_fid_alloc (struct lmv_obd *lmv, struct lu_fid *fid, u32 mds)
int lmv_fid_alloc (const struct lu_env *env, struct obd_export *exp, struct lu_fid *fid, struct md_op_data *op_data)
static int lmv_setup (struct obd_device *obd, struct lustre_cfg *lcfg)
static int lmv_cleanup (struct obd_device *obd)
static int lmv_process_config (struct obd_device *obd, size_t len, void *buf)
static int lmv_statfs (const struct lu_env *env, struct obd_export *exp, struct obd_statfs *osfs, __u64 max_age, __u32 flags)
static int lmv_get_root (struct obd_export *exp, const char *fileset, struct lu_fid *fid)
static int lmv_getxattr (struct obd_export *exp, const struct lu_fid *fid, u64 valid, const char *name, const char *input, int input_size, int output_size, int flags, struct ptlrpc_request **request)
static int lmv_setxattr (struct obd_export *exp, const struct lu_fid *fid, u64 valid, const char *name, const char *input, int input_size, int output_size, int flags, __u32 suppgid, struct ptlrpc_request **request)
static int lmv_getattr (struct obd_export *exp, struct md_op_data *op_data, struct ptlrpc_request **request)
static int lmv_null_inode (struct obd_export *exp, const struct lu_fid *fid)
static int lmv_close (struct obd_export *exp, struct md_op_data *op_data, struct md_open_data *mod, struct ptlrpc_request **request)
struct lmv_tgt_desc * lmv_locate_target_for_name (struct lmv_obd *lmv, struct lmv_stripe_md *lsm, const char *name, int namelen, struct lu_fid *fid, u32 *mds)
Choosing the MDT by name or FID in .
struct lmv_tgt_desc * lmv_locate_mds (struct lmv_obd *lmv, struct md_op_data *op_data, struct lu_fid *fid)
Locate mds by fid or name.
int lmv_create (struct obd_export *exp, struct md_op_data *op_data, const void *data, size_t datalen, umode_t mode, uid_t uid, gid_t gid, cfs_cap_t cap_effective, __u64 rdev, struct ptlrpc_request **request)
static int lmv_enqueue (struct obd_export *exp, struct ldlm_enqueue_info *einfo, const union ldlm_policy_data *policy, struct lookup_intent *it, struct md_op_data *op_data, struct lustre_handle *lockh, __u64 extra_lock_flags)
static int lmv_getattr_name (struct obd_export *exp, struct md_op_data *op_data, struct ptlrpc_request **preq)
static int lmv_early_cancel (struct obd_export *exp, struct lmv_tgt_desc *tgt, struct md_op_data *op_data, __u32 op_tgt, enum ldlm_mode mode, int bits, int flag)
static int lmv_link (struct obd_export *exp, struct md_op_data *op_data, struct ptlrpc_request **request)
static int lmv_rename (struct obd_export *exp, struct md_op_data *op_data, const char *old, size_t oldlen, const char *new, size_t newlen, struct ptlrpc_request **request)
static int lmv_setattr (struct obd_export *exp, struct md_op_data *op_data, void *ea, size_t ealen, struct ptlrpc_request **request)
static int lmv_fsync (struct obd_export *exp, const struct lu_fid *fid, struct ptlrpc_request **request)
static int lmv_get_min_striped_entry (struct obd_export *exp, struct md_op_data *op_data, struct md_callback *cb_op, __u64 hash_offset, int *stripe_offset, struct lu_dirent **entp, struct page **ppage)
Get current minimum entry from striped directory.
static int lmv_read_striped_page (struct obd_export *exp, struct md_op_data *op_data, struct md_callback *cb_op, __u64 offset, struct page **ppage)
Build dir entry page from a striped directory.
int lmv_read_page (struct obd_export *exp, struct md_op_data *op_data, struct md_callback *cb_op, __u64 offset, struct page **ppage)
static int lmv_unlink (struct obd_export *exp, struct md_op_data *op_data, struct ptlrpc_request **request)
Unlink a file/directory.
static int lmv_precleanup (struct obd_device *obd)
static int lmv_get_info (const struct lu_env *env, struct obd_export *exp, __u32 keylen, void *key, __u32 *vallen, void *val)
Get by key a value associated with a LMV device.
int lmv_set_info_async (const struct lu_env *env, struct obd_export *exp, __u32 keylen, void *key, __u32 vallen, void *val, struct ptlrpc_request_set *set)
Asynchronously set by key a value associated with a LMV device.
static int lmv_unpack_md_v1 (struct obd_export *exp, struct lmv_stripe_md *lsm, const struct lmv_mds_md_v1 *lmm1)
static int lmv_unpackmd (struct obd_export *exp, struct lmv_stripe_md **lsmp, const union lmv_mds_md *lmm, size_t lmm_size)
void lmv_free_memmd (struct lmv_stripe_md *lsm)
static int lmv_cancel_unused (struct obd_export *exp, const struct lu_fid *fid, union ldlm_policy_data *policy, enum ldlm_mode mode, enum ldlm_cancel_flags flags, void *opaque)
int lmv_set_lock_data (struct obd_export *exp, __u64 *lockh, void *data, __u64 *bits)
enum ldlm_mode lmv_lock_match (struct obd_export *exp, __u64 flags, const struct lu_fid *fid, enum ldlm_type type, union ldlm_policy_data *policy, enum ldlm_mode mode, struct lustre_handle *lockh)
int lmv_get_lustre_md (struct obd_export *exp, struct ptlrpc_request *req, struct obd_export *dt_exp, struct obd_export *md_exp, struct lustre_md *md)
int lmv_free_lustre_md (struct obd_export *exp, struct lustre_md *md)
int lmv_set_open_replay_data (struct obd_export *exp, struct obd_client_handle *och, struct lookup_intent *it)
int lmv_clear_open_replay_data (struct obd_export *exp, struct obd_client_handle *och)
static int lmv_get_remote_perm (struct obd_export *exp, const struct lu_fid *fid, u32 suppgid, struct ptlrpc_request **request)
int lmv_intent_getattr_async (struct obd_export *exp, struct md_enqueue_info *minfo)
int lmv_revalidate_lock (struct obd_export *exp, struct lookup_intent *it, struct lu_fid *fid, __u64 *bits)
int lmv_get_fid_from_lsm (struct obd_export *exp, const struct lmv_stripe_md *lsm, const char *name, int namelen, struct lu_fid *fid)
int lmv_quotactl (struct obd_device *unused, struct obd_export *exp, struct obd_quotactl *oqctl)
For lmv, only need to send request to master MDT, and the master MDT will process with other slave MDTs.
static int lmv_merge_attr (struct obd_export *exp, const struct lmv_stripe_md *lsm, struct cl_attr *attr, ldlm_blocking_callback cb_blocking)
static int __init lmv_init (void)
static void __exit lmv_exit (void)
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Logical Metadata Volume")
MODULE_VERSION (LUSTRE_VERSION_STRING)
MODULE_LICENSE ("GPL")
module_init (lmv_init)
module_exit (lmv_exit)
Variables
struct obd_ops lmv_obd_ops
struct md_ops lmv_md_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_LMV
Definition at line 37 of file lmv_obd.c.
#define MAX_STRING_SIZE 128
Definition at line 313 of file lmv_obd.c.
#define md_op_data_fid (op_data, fl)
Value:
(fl == MF_MDC_CANCEL_FID1 ? &op_data->op_fid1 : \
         fl == MF_MDC_CANCEL_FID2 ? &op_data->op_fid2 : \
         fl == MF_MDC_CANCEL_FID3 ? &op_data->op_fid3 : \
         fl == MF_MDC_CANCEL_FID4 ? &op_data->op_fid4 : \
         NULL)
Definition at line 1891 of file lmv_obd.c.
Referenced by lmv_early_cancel().
Function Documentation
int __lmv_fid_alloc (struct lmv_obd * lmv, struct lu_fid * fid, u32 mds)
Definition at line 1276 of file lmv_obd.c.
References ENTRY, EXIT, fid_is_sane(), GOTO, LASSERT, lmv_get_target(), lmv_tgt_desc::ltd_active, lmv_tgt_desc::ltd_exp, lmv_tgt_desc::ltd_fid_mutex, obd_fid_alloc(), and RETURN.
Referenced by lmv_fid_alloc().
static void lmv_activate_target (struct lmv_obd * lmv, struct lmv_tgt_desc * tgt, int activate) [static]
Definition at line 65 of file lmv_obd.c.
References lmv_obd::desc, obd_export::exp_obd, lmv_desc::ld_active_tgt_count, lmv_tgt_desc::ltd_active, lmv_tgt_desc::ltd_exp, and obd_device::obd_inactive.
Referenced by lmv_disconnect_mdc(), and lmv_set_mdc_active().
static int lmv_add_target (struct obd_device * obd, struct obd_uuid * uuidp, __u32 index, int gen) [static]
Definition at line 424 of file lmv_obd.c.
References CDEBUG, CERROR, class_find_client_obd(), lmv_obd::connected, D_CONFIG, lmv_obd::desc, ENTRY, lmv_desc::ld_tgt_count, obd_device::lmv, lmv_connect_mdc(), lmv_init_ea_size(), lmv_obd::lmv_init_mutex, lmv_obd::lmv_lock, lmv_tgt_desc::ltd_active, lmv_tgt_desc::ltd_fid_mutex, lmv_tgt_desc::ltd_idx, lmv_tgt_desc::ltd_uuid, LUSTRE_MDC_NAME, OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, obd_device::obd_name, obd_device::obd_self_export, obd_device::obd_uuid, obd_uuid2str(), RETURN, lmv_obd::tgts, lmv_obd::tgts_size, obd_device::u, and obd_uuid::uuid.
Referenced by lmv_process_config().
static int lmv_cancel_unused (struct obd_export * exp, const struct lu_fid * fid, union ldlm_policy_data * policy, enum ldlm_mode mode, enum ldlm_cancel_flags flags, void * opaque) [static]
Definition at line 2978 of file lmv_obd.c.
References lmv_obd::desc, ENTRY, obd_export::exp_obd, LASSERT, lmv_desc::ld_tgt_count, obd_device::lmv, lmv_tgt_desc::ltd_active, lmv_tgt_desc::ltd_exp, md_cancel_unused(), RETURN, lmv_obd::tgts, and obd_device::u.
int lmv_check_connect (struct obd_device * obd)
Definition at line 524 of file lmv_obd.c.
References CDEBUG, CERROR, class_disconnect(), class_export_put(), lmv_obd::cluuid, lmv_obd::connected, D_CONFIG, lmv_obd::desc, ENTRY, lmv_obd::exp, GOTO, LASSERT, lmv_desc::ld_active_tgt_count, lmv_desc::ld_tgt_count, obd_device::lmv, lmv_connect_mdc(), lmv_init_ea_size(), lmv_obd::lmv_init_mutex, LMV_MAGIC, lmv_mds_md_size(), lmv_tgt_desc::ltd_active, lmv_tgt_desc::ltd_exp, lmv_tgt_desc::ltd_uuid, obd_disconnect(), obd_device::obd_name, obd_device::obd_self_export, RETURN, lmv_obd::tgts, obd_device::u, and obd_uuid::uuid.
Referenced by lmv_close(), lmv_connect(), lmv_create(), lmv_enqueue(), lmv_fsync(), lmv_get_info(), lmv_get_remote_perm(), lmv_get_root(), lmv_getattr(), lmv_getattr_name(), lmv_getxattr(), lmv_intent_getattr_async(), lmv_intent_lock(), lmv_link(), lmv_null_inode(), lmv_read_page(), lmv_read_striped_page(), lmv_rename(), lmv_revalidate_lock(), lmv_setattr(), lmv_setxattr(), lmv_statfs(), and lmv_unlink().
static int lmv_cleanup (struct obd_device * obd) [static]
Definition at line 1395 of file lmv_obd.c.
References lmv_obd::desc, ENTRY, fld_client_fini(), lmv_desc::ld_tgt_count, obd_device::lmv, lmv_del_target(), lmv_obd::lmv_fld, OBD_FREE, RETURN, lmv_obd::tgts, lmv_obd::tgts_size, and obd_device::u.
int lmv_clear_open_replay_data (struct obd_export * exp, struct obd_client_handle * och)
Definition at line 3107 of file lmv_obd.c.
References ENTRY, obd_export::exp_obd, obd_device::lmv, lmv_find_target(), lmv_tgt_desc::ltd_exp, md_clear_open_replay_data(), obd_client_handle::och_fid, RETURN, and obd_device::u.
static int lmv_close (struct obd_export * exp, struct md_op_data * op_data, struct md_open_data * mod, struct ptlrpc_request ** request) [static]
Definition at line 1624 of file lmv_obd.c.
References CDEBUG, D_INODE, DFID, ENTRY, obd_export::exp_obd, obd_device::lmv, lmv_check_connect(), lmv_find_target(), lmv_tgt_desc::ltd_exp, md_close(), md_op_data::op_fid1, PFID, RETURN, and obd_device::u.
static int lmv_connect (const struct lu_env * env, struct obd_export ** exp, struct obd_device * obd, struct obd_uuid * cluuid, struct obd_connect_data * data, void * localdata) [static]
This is fake connect function.
Its purpose is to initialize lmv and say caller that everything is okay. Real connection will be performed later.
Definition at line 207 of file lmv_obd.c.
References CERROR, class_conn2export(), class_connect(), class_export_get(), lmv_obd::cluuid, lmv_obd::conn_data, lmv_obd::connected, ENTRY, lmv_obd::exp, obd_device::lmv, lmv_check_connect(), lprocfs_register(), lprocfs_remove(), OBD_CONNECT_REAL, obd_device::obd_name, obd_device::obd_proc_entry, obd_device::obd_type, obd_connect_data::ocd_connect_flags, lmv_obd::refcount, RETURN, lmv_obd::targets_proc_entry, obd_type::typ_name, and obd_device::u.
int lmv_connect_mdc (struct obd_device * obd, struct lmv_tgt_desc * tgt)
Definition at line 315 of file lmv_obd.c.
References CDEBUG, CERROR, class_find_client_obd(), lmv_obd::cluuid, lmv_obd::conn_data, D_CONFIG, lmv_obd::desc, ENTRY, obd_export::exp_obd, fld_client_add_target(), lu_fld_target::ft_exp, lu_fld_target::ft_idx, lu_fld_target::ft_srv, LASSERT, lmv_desc::ld_active_tgt_count, obd_device::lmv, lmv_obd::lmv_fld, lprocfs_add_symlink(), lmv_tgt_desc::ltd_active, lmv_tgt_desc::ltd_exp, lmv_tgt_desc::ltd_idx, lmv_tgt_desc::ltd_uuid, LUSTRE_MDC_NAME, LUSTRE_SEQ_METADATA, lmv_obd::max_def_easize, lmv_obd::max_easize, md_init_ea_size(), obd_connect(), obd_disconnect(), obd_fid_init(), obd_device::obd_name, obd_notify(), OBD_NOTIFY_ACTIVE, obd_device::obd_observer, obd_device::obd_refcount, obd_register_observer(), obd_device::obd_set_up, obd_device::obd_type, obd_device::obd_uuid, RETURN, lmv_obd::targets_proc_entry, lmv_obd::tgts, obd_type::typ_name, obd_device::u, and obd_uuid::uuid.
Referenced by lmv_add_target(), and lmv_check_connect().
int lmv_create (struct obd_export * exp, struct md_op_data * op_data, const void * data, size_t datalen, umode_t mode, uid_t uid, gid_t gid, cfs_cap_t cap_effective, __u64 rdev, struct ptlrpc_request ** request)
Definition at line 1749 of file lmv_obd.c.
References CDEBUG, D_CONFIG, D_INODE, lmv_obd::desc, DFID, ENTRY, exp_connect_flags(), obd_export::exp_obd, lmv_desc::ld_active_tgt_count, obd_device::lmv, lmv_check_connect(), lmv_fid_alloc(), lmv_find_target(), lmv_locate_mds(), lmv_tgt_desc::ltd_exp, lmv_tgt_desc::ltd_idx, md_create(), MF_MDC_CANCEL_FID1, OBD_CONNECT_DIR_STRIPE, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_flags, md_op_data::op_mds, md_op_data::op_name, md_op_data::op_namelen, PFID, RETURN, and obd_device::u.
static void lmv_del_target (struct lmv_obd * lmv, int index) [static]
Definition at line 414 of file lmv_obd.c.
References OBD_FREE_PTR, and lmv_obd::tgts.
Referenced by lmv_cleanup().
static int lmv_disconnect (struct obd_export * exp) [static]
Definition at line 642 of file lmv_obd.c.
References CERROR, class_disconnect(), class_exp2obd(), class_export_put(), lmv_obd::connected, lmv_obd::desc, ENTRY, lmv_desc::ld_tgt_count, obd_device::lmv, lmv_disconnect_mdc(), lprocfs_remove(), lmv_tgt_desc::ltd_exp, obd_device::obd_name, obd_device::obd_type, lmv_obd::refcount, RETURN, lmv_obd::targets_proc_entry, lmv_obd::tgts, obd_type::typ_name, and obd_device::u.
static int lmv_disconnect_mdc (struct obd_device * obd, struct lmv_tgt_desc * tgt) [static]
Definition at line 598 of file lmv_obd.c.
References CDEBUG, CERROR, class_exp2obd(), D_INFO, ENTRY, obd_export::exp_obd, LASSERT, obd_device::lmv, lmv_activate_target(), lprocfs_remove_proc_entry(), lmv_tgt_desc::ltd_active, lmv_tgt_desc::ltd_exp, lmv_tgt_desc::ltd_uuid, obd_disconnect(), obd_device::obd_fail, obd_fid_fini(), obd_device::obd_force, obd_device::obd_name, obd_device::obd_no_recov, obd_register_observer(), obd_device::obd_uuid, RETURN, lmv_obd::targets_proc_entry, obd_device::u, and obd_uuid::uuid.
Referenced by lmv_disconnect().
static int lmv_early_cancel (struct obd_export * exp, struct lmv_tgt_desc * tgt, struct md_op_data * op_data, __u32 op_tgt, enum ldlm_mode mode, int bits, int flag) [static]
Definition at line 1898 of file lmv_obd.c.
References ldlm_inodebits::bits, CDEBUG, D_INODE, DFID, ENTRY, obd_export::exp_obd, fid_is_sane(), ldlm_policy_data::l_inodebits, LCF_ASYNC, obd_device::lmv, lmv_find_target(), lmv_tgt_desc::ltd_exp, lmv_tgt_desc::ltd_idx, md_cancel_unused(), md_op_data_fid, md_op_data::op_flags, PFID, RETURN, and obd_device::u.
Referenced by lmv_link(), lmv_rename(), and lmv_unlink().
static int lmv_enqueue (struct obd_export * exp, struct ldlm_enqueue_info * einfo, const union ldlm_policy_data * policy, struct lookup_intent * it, struct md_op_data * op_data, struct lustre_handle * lockh, __u64 extra_lock_flags) [static]
Definition at line 1805 of file lmv_obd.c.
References CDEBUG, D_INODE, DFID, ENTRY, obd_export::exp_obd, LL_IT2STR, obd_device::lmv, lmv_check_connect(), lmv_locate_mds(), lmv_tgt_desc::ltd_exp, lmv_tgt_desc::ltd_idx, md_enqueue(), md_op_data::op_fid1, PFID, RETURN, and obd_device::u.
static void __exit lmv_exit (void) [static]
Definition at line 3371 of file lmv_obd.c.
References class_unregister_type(), and LUSTRE_LMV_NAME.
static int lmv_fid2path (struct obd_export * exp, int len, void * karg, void __user * uarg) [static]
Definition at line 686 of file lmv_obd.c.
References CDEBUG, CERROR, class_exp2obd(), D_INFO, DFID, obd_export::exp_obd, fid_is_sane(), getinfo_fid2path::gf_fid, getinfo_fid2path::gf_linkno, getinfo_fid2path::gf_path, getinfo_fid2path::gf_pathlen, getinfo_fid2path::gf_recno, getinfo_fid2path::gf_root_fid, getinfo_fid2path::gf_u, GOTO, LASSERT, obd_device::lmv, lmv_find_target(), LPU64, lmv_tgt_desc::ltd_exp, OBD_ALLOC, OBD_FREE, OBD_IOC_FID2PATH, obd_iocontrol(), obd_device::obd_name, PFID, RETURN, and obd_device::u.
Referenced by lmv_iocontrol().
int lmv_fid_alloc (const struct lu_env * env, struct obd_export * exp, struct lu_fid * fid, struct md_op_data * op_data)
Definition at line 1310 of file lmv_obd.c.
References __lmv_fid_alloc(), CERROR, class_exp2obd(), ENTRY, LASSERT, obd_device::lmv, lmv_placement_policy(), RETURN, and obd_device::u.
Referenced by lmv_create(), lmv_intent_open(), and lmv_rename().
int lmv_free_lustre_md (struct obd_export * exp, struct lustre_md * md)
Definition at line 3075 of file lmv_obd.c.
References ENTRY, obd_export::exp_obd, lustre_md::lmv, obd_device::lmv, lmv_free_memmd(), lmv_tgt_desc::ltd_exp, md_free_lustre_md(), RETURN, lmv_obd::tgts, and obd_device::u.
void lmv_free_memmd (struct lmv_stripe_md * lsm)
Definition at line 2972 of file lmv_obd.c.
References lmv_unpackmd().
Referenced by ll_dir_clear_lsm_md(), ll_update_lsm_md(), and lmv_free_lustre_md().
static int lmv_fsync (struct obd_export * exp, const struct lu_fid * fid, struct ptlrpc_request ** request) [static]
Definition at line 2190 of file lmv_obd.c.
References ENTRY, obd_export::exp_obd, obd_device::lmv, lmv_check_connect(), lmv_find_target(), lmv_tgt_desc::ltd_exp, md_fsync(), RETURN, and obd_device::u.
int lmv_get_fid_from_lsm (struct obd_export * exp, const struct lmv_stripe_md * lsm, const char * name, int namelen, struct lu_fid * fid)
Definition at line 3203 of file lmv_obd.c.
References LASSERT, lmv_oinfo::lmo_fid, lsm_name_to_stripe_info(), and RETURN.
static int lmv_get_info (const struct lu_env * env, struct obd_export * exp, __u32 keylen, void * key, __u32 * vallen, void * val) [static]
Get by key a value associated with a LMV device.
Dispatch request to lower-layer devices as needed.
Parameters:
[in] env execution environment for this thread
[in] exp export for the LMV device
[in] keylen length of key identifier
[in] key identifier of key to get value for
[in] vallen size of val
[out] val pointer to storage location for value
[in] lsm optional striping metadata of object
Return values:
0 on success
negative negated errno on failure
Definition at line 2732 of file lmv_obd.c.
References CDEBUG, class_exp2obd(), D_IOCTL, lmv_obd::desc, ENTRY, obd_export::exp_connect_data, obd_export::exp_handle, portals_handle::h_cookie, KEY_CONN_DATA, KEY_DEFAULT_EASIZE, KEY_IS, KEY_MAX_EASIZE, KEY_TGT_COUNT, LASSERT, lmv_desc::ld_tgt_count, obd_device::lmv, lmv_check_connect(), LPX64, lmv_tgt_desc::ltd_exp, obd_get_info(), RETURN, lmv_obd::tgts, and obd_device::u.
int lmv_get_lustre_md (struct obd_export * exp, struct ptlrpc_request * req, struct obd_export * dt_exp, struct obd_export * md_exp, struct lustre_md * md)
Definition at line 3062 of file lmv_obd.c.
References obd_export::exp_obd, obd_device::lmv, lmv_tgt_desc::ltd_exp, md_get_lustre_md(), RETURN, lmv_obd::tgts, and obd_device::u.
static int lmv_get_min_striped_entry (struct obd_export * exp, struct md_op_data * op_data, struct md_callback * cb_op, __u64 hash_offset, int * stripe_offset, struct lu_dirent ** entp, struct page ** ppage) [static]
Get current minimum entry from striped directory.
This function will search the dir entry, whose hash value is the closest(>=) to , from all of sub-stripes, and it is only being called for striped directory.
Parameters:
[in] exp export of LMV
[in] op_data parameters transferred beween client MD stack stripe_information will be included in this parameter
[in] cb_op ldlm callback being used in enqueue in mdc_read_page
[in] hash_offset the hash value, which is used to locate minum(closet) dir entry
in|out] stripe_offset the caller use this to indicate the stripe index of last entry, so to avoid hash conflict between stripes. It will also be used to return the stripe index of current dir entry.
in|out] entp the minum entry and it also is being used to input the last dir entry to resolve the hash conflict
[out] ppage the page which holds the minum entry
Return values:
= 0 get the entry successfully negative errno (< 0) does not get the entry
Definition at line 2239 of file lmv_obd.c.
References __u64, ENTRY, obd_export::exp_obd, GOTO, lu_dirent::lde_hash, lu_dirent::lde_name, lu_dirent::lde_namelen, lu_dirpage::ldp_hash_end, le16_to_cpu, le64_to_cpu, lmv_oinfo::lmo_fid, lmv_oinfo::lmo_mds, lmv_oinfo::lmo_root, obd_device::lmv, lmv_get_target(), lmv_stripe_md::lsm_md_oinfo, lmv_stripe_md::lsm_md_stripe_count, lmv_tgt_desc::ltd_exp, lu_dirent_next(), lu_dirent_start(), md_read_page(), MDS_DIR_END_OFF, md_op_data::op_data, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_mea1, RETURN, and obd_device::u.
Referenced by lmv_read_striped_page().
static int lmv_get_remote_perm (struct obd_export * exp, const struct lu_fid * fid, u32 suppgid, struct ptlrpc_request ** request) [static]
Definition at line 3122 of file lmv_obd.c.
References ENTRY, obd_export::exp_obd, obd_device::lmv, lmv_check_connect(), lmv_find_target(), lmv_tgt_desc::ltd_exp, md_get_remote_perm(), RETURN, and obd_device::u.
static int lmv_get_root (struct obd_export * exp, const char * fileset, struct lu_fid * fid) [static]
Definition at line 1501 of file lmv_obd.c.
References ENTRY, obd_export::exp_obd, obd_device::lmv, lmv_check_connect(), lmv_tgt_desc::ltd_exp, md_get_root(), RETURN, lmv_obd::tgts, and obd_device::u.
struct obd_uuid* lmv_get_uuid (struct obd_export * exp) [read]
Definition at line 139 of file lmv_obd.c.
References obd_export::exp_obd, obd_device::lmv, lmv_tgt_desc::ltd_exp, obd_get_uuid(), lmv_obd::tgts, and obd_device::u.
static int lmv_getattr (struct obd_export * exp, struct md_op_data * op_data, struct ptlrpc_request ** request) [static]
Definition at line 1569 of file lmv_obd.c.
References ENTRY, obd_export::exp_obd, obd_device::lmv, lmv_check_connect(), lmv_find_target(), lmv_tgt_desc::ltd_exp, lmv_tgt_desc::ltd_idx, md_getattr(), MF_GET_MDT_IDX, md_op_data::op_fid1, md_op_data::op_flags, md_op_data::op_mds, RETURN, and obd_device::u.
static int lmv_getattr_name (struct obd_export * exp, struct md_op_data * op_data, struct ptlrpc_request ** preq) [static]
Definition at line 1837 of file lmv_obd.c.
References CDEBUG, D_INODE, DFID, ENTRY, obd_export::exp_obd, LASSERT, obd_device::lmv, lmv_check_connect(), lmv_find_target(), lmv_locate_mds(), lmv_tgt_desc::ltd_exp, lmv_tgt_desc::ltd_idx, mdt_body::mbo_fid1, mdt_body::mbo_valid, md_getattr_name(), OBD_MD_FLCROSSREF, OBD_MD_MDS, md_op_data::op_fid1, md_op_data::op_name, md_op_data::op_namelen, md_op_data::op_valid, PFID, ptlrpc_req_finished(), req_capsule_server_get(), RETURN, RMF_MDT_BODY, and obd_device::u.
static int lmv_getxattr (struct obd_export * exp, const struct lu_fid * fid, u64 valid, const char * name, const char * input, int input_size, int output_size, int flags, struct ptlrpc_request ** request) [static]
Definition at line 1517 of file lmv_obd.c.
References ENTRY, obd_export::exp_obd, obd_device::lmv, lmv_check_connect(), lmv_find_target(), lmv_tgt_desc::ltd_exp, md_getxattr(), RETURN, and obd_device::u.
static int lmv_hsm_ct_register (struct lmv_obd * lmv, unsigned int cmd, int len, struct lustre_kernelcomm * lk, __user void * uarg) [static]
Definition at line 845 of file lmv_obd.c.
References CERROR, class_exp2obd(), lmv_obd::cluuid, lmv_obd::desc, ENTRY, lmv_obd::exp, kkuc_ct_data::kcd_archive, kkuc_ct_data::kcd_magic, kkuc_ct_data::kcd_uuid, KKUC_CT_DATA_MAGIC, lmv_desc::ld_tgt_count, libcfs_kkuc_group_add(), lustre_kernelcomm::lk_data, lustre_kernelcomm::lk_flags, LK_FLG_STOP, lustre_kernelcomm::lk_group, lustre_kernelcomm::lk_uid, lustre_kernelcomm::lk_wfd, lmv_tgt_desc::ltd_active, lmv_tgt_desc::ltd_exp, lmv_tgt_desc::ltd_uuid, obd_iocontrol(), obd_device::obd_name, RETURN, lmv_obd::tgts, and obd_uuid::uuid.
Referenced by lmv_iocontrol().
static int lmv_hsm_ct_unregister (struct lmv_obd * lmv, unsigned int cmd, int len, struct lustre_kernelcomm * lk, void __user * uarg) [static]
Definition at line 817 of file lmv_obd.c.
References lmv_obd::desc, ENTRY, lmv_desc::ld_tgt_count, libcfs_kkuc_group_rem(), lustre_kernelcomm::lk_group, lustre_kernelcomm::lk_uid, lmv_tgt_desc::ltd_exp, obd_iocontrol(), RETURN, and lmv_obd::tgts.
Referenced by lmv_iocontrol().
static void lmv_hsm_req_build (struct lmv_obd * lmv, struct hsm_user_request * hur_in, const struct lmv_tgt_desc * tgt_mds, struct hsm_user_request * hur_out) [static]
Definition at line 792 of file lmv_obd.c.
References hsm_request::hr_data_len, hsm_request::hr_itemcount, hsm_user_item::hui_fid, hur_data(), hsm_user_request::hur_request, hsm_user_request::hur_user_item, lmv_find_target(), lmv_tgt_desc::ltd_uuid, and obd_uuid_equals().
Referenced by lmv_iocontrol().
static int lmv_hsm_req_count (struct lmv_obd * lmv, const struct hsm_user_request * hur, const struct lmv_tgt_desc * tgt_mds) [static]
Definition at line 775 of file lmv_obd.c.
References hsm_request::hr_itemcount, hsm_user_item::hui_fid, hsm_user_request::hur_request, hsm_user_request::hur_user_item, lmv_find_target(), lmv_tgt_desc::ltd_uuid, and obd_uuid_equals().
Referenced by lmv_iocontrol().
static int __init lmv_init (void) [static]
Definition at line 3365 of file lmv_obd.c.
References class_register_type(), and LUSTRE_LMV_NAME.
static int lmv_init_ea_size (struct obd_export * exp, __u32 easize, __u32 def_easize) [static]
Definition at line 270 of file lmv_obd.c.
References CERROR, lmv_obd::connected, CWARN, lmv_obd::desc, ENTRY, obd_export::exp_obd, lmv_desc::ld_tgt_count, obd_device::lmv, lmv_tgt_desc::ltd_active, lmv_tgt_desc::ltd_exp, lmv_obd::max_def_easize, lmv_obd::max_easize, md_init_ea_size(), obd_device::obd_name, RETURN, lmv_obd::tgts, and obd_device::u.
Referenced by lmv_add_target(), and lmv_check_connect().
int lmv_intent_getattr_async (struct obd_export * exp, struct md_enqueue_info * minfo)
Definition at line 3143 of file lmv_obd.c.
References ENTRY, obd_export::exp_obd, fid_is_sane(), obd_device::lmv, lmv_check_connect(), lmv_locate_mds(), lmv_tgt_desc::ltd_exp, md_intent_getattr_async(), md_enqueue_info::mi_data, md_op_data::op_fid1, md_op_data::op_fid2, RETURN, and obd_device::u.
static int lmv_iocontrol (unsigned int cmd, struct obd_export * exp, int len, void * karg, void __user * uarg) [static]
Definition at line 915 of file lmv_obd.c.
References CERROR, cfs_time_shift_64(), class_exp2obd(), lmv_obd::desc, ENTRY, hsm_progress_kernel::hpk_fid, hsm_request::hr_data_len, hsm_request::hr_itemcount, hsm_user_item::hui_fid, hsm_user_request::hur_request, hsm_user_request::hur_user_item, ioc_changelog::icc_mdtindex, obd_ioctl_data::ioc_inlbuf2, IOC_OBD_STATFS, obd_ioctl_data::ioc_pbuf1, obd_ioctl_data::ioc_pbuf2, obd_ioctl_data::ioc_plen1, obd_ioctl_data::ioc_plen2, LASSERT, lmv_desc::ld_tgt_count, lustre_kernelcomm::lk_flags, LK_FLG_STOP, LL_IOC_FID2MDTIDX, LL_IOC_GET_CONNECT_FLAGS, LL_IOC_HSM_ACTION, LL_IOC_HSM_CT_START, LL_IOC_HSM_PROGRESS, LL_IOC_HSM_REQUEST, LL_IOC_HSM_STATE_GET, LL_IOC_HSM_STATE_SET, LL_IOC_LOV_SWAP_LAYOUTS, obd_device::lmv, lmv_fid2path(), lmv_find_target(), lmv_fld_lookup(), lmv_hsm_ct_register(), lmv_hsm_ct_unregister(), lmv_hsm_req_build(), lmv_hsm_req_count(), lmv_tgt_desc::ltd_active, lmv_tgt_desc::ltd_exp, lmv_tgt_desc::ltd_idx, lmv_tgt_desc::ltd_uuid, obd2cli_tgt, OBD_ALLOC_LARGE, OBD_ALLOC_PTR, obd_device::obd_force, OBD_FREE_LARGE, OBD_FREE_PTR, OBD_IOC_CHANGELOG_CLEAR, OBD_IOC_CHANGELOG_SEND, OBD_IOC_FID2PATH, OBD_IOC_QUOTACTL, obd_iocontrol(), obd_quotactl(), obd_statfs(), OBD_STATFS_CACHE_SECONDS, if_quotactl::obd_uuid, obd_uuid_equals(), offsetof, md_op_data::op_data, md_op_data::op_fid1, md_op_data::op_fid2, if_quotactl::qc_idx, QC_MDTIDX, QC_UUID, if_quotactl::qc_valid, QCTL_COPY, RETURN, lmv_obd::tgts, obd_device::u, and obd_uuid::uuid.
static int lmv_link (struct obd_export * exp, struct md_op_data * op_data, struct ptlrpc_request ** request) [static]
Definition at line 1937 of file lmv_obd.c.
References CDEBUG, cfs_curproc_cap_pack(), D_INODE, DFID, ENTRY, obd_export::exp_obd, from_kgid(), from_kuid(), LASSERT, LCK_EX, lmv_oinfo::lmo_fid, obd_device::lmv, lmv_check_connect(), lmv_early_cancel(), lmv_locate_mds(), lsm_name_to_stripe_info(), lmv_tgt_desc::ltd_exp, lmv_tgt_desc::ltd_idx, md_link(), MDS_INODELOCK_UPDATE, MF_MDC_CANCEL_FID1, MF_MDC_CANCEL_FID2, md_op_data::op_cap, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_flags, md_op_data::op_fsgid, md_op_data::op_fsuid, md_op_data::op_mea2, md_op_data::op_name, md_op_data::op_namelen, PFID, RETURN, and obd_device::u.
struct lmv_tgt_desc* lmv_locate_mds (struct lmv_obd * lmv, struct md_op_data * op_data, struct lu_fid * fid) [read]
Locate mds by fid or name.
For striped directory (lsm != NULL), it will locate the stripe by name hash (see lsm_name_to_stripe_info()). Note: if the hash_type is unknown, it will return -EBADFD, and lmv_intent_lookup might need walk through all of stripes to locate the entry.
For normal direcotry, it will locate MDS by FID directly.
Parameters:
[in] lmv LMV device
[in] op_data client MD stack parameters, name, namelen mds_num etc.
[in] fid object FID used to locate MDS.
retval pointer to the lmv_tgt_desc if succeed. ERR_PTR(errno) if failed.
Definition at line 1700 of file lmv_obd.c.
References lmv_oinfo::lmo_fid, lmv_oinfo::lmo_mds, lmv_find_target(), lmv_get_target(), lmv_locate_target_for_name(), lmv_stripe_md::lsm_md_oinfo, lmv_stripe_md::lsm_md_stripe_count, lmv_tgt_desc::ltd_idx, MDS_CREATE_VOLATILE, md_op_data::op_bias, md_op_data::op_mds, md_op_data::op_mea1, md_op_data::op_name, and md_op_data::op_namelen.
Referenced by lmv_create(), lmv_enqueue(), lmv_getattr_name(), lmv_intent_getattr_async(), lmv_intent_lookup(), lmv_intent_open(), lmv_link(), lmv_revalidate_slaves(), and lmv_unlink().
struct lmv_tgt_desc* lmv_locate_target_for_name (struct lmv_obd * lmv, struct lmv_stripe_md * lsm, const char * name, int namelen, struct lu_fid * fid, u32 * mds) [read]
Choosing the MDT by name or FID in .
For non-striped directory, it will locate MDT by fid. For striped-directory, it will locate MDT by name. And also it will reset op_fid1 with the FID of the choosen stripe.
Definition at line 1653 of file lmv_obd.c.
References CDEBUG, cfs_fail_val, D_INFO, DFID, lmv_oinfo::lmo_fid, lmv_oinfo::lmo_mds, lmv_get_target(), lmv_stripe_md::lsm_md_oinfo, lmv_stripe_md::lsm_md_stripe_count, lsm_name_to_stripe_info(), OBD_FAIL_CHECK, OBD_FAIL_LFSCK_BAD_NAME_HASH, PFID, and RETURN.
Referenced by lmv_locate_mds(), lmv_rename(), and lmv_unlink().
enum ldlm_mode lmv_lock_match (struct obd_export * exp, __u64 flags, const struct lu_fid * fid, enum ldlm_type type, union ldlm_policy_data * policy, enum ldlm_mode mode, struct lustre_handle * lockh)
Definition at line 3019 of file lmv_obd.c.
References CDEBUG, D_HA, D_INODE, lmv_obd::desc, DFID, ENTRY, obd_export::exp_obd, lmv_desc::ld_tgt_count, obd_device::lmv, lmv_find_target_index(), lmv_tgt_desc::ltd_active, lmv_tgt_desc::ltd_exp, md_lock_match(), obd_device::obd_name, PFID, RETURN, lmv_obd::tgts, and obd_device::u.
static int lmv_merge_attr (struct obd_export * exp, const struct lmv_stripe_md * lsm, struct cl_attr * attr, ldlm_blocking_callback cb_blocking) [static]
Definition at line 3272 of file lmv_obd.c.
References cl_attr::cat_atime, cl_attr::cat_blocks, cl_attr::cat_ctime, cl_attr::cat_mtime, cl_attr::cat_nlink, cl_attr::cat_size, CDEBUG, D_INFO, DFID, lmv_oinfo::lmo_fid, lmv_oinfo::lmo_root, lmv_revalidate_slaves(), lmv_stripe_md::lsm_md_oinfo, lmv_stripe_md::lsm_md_stripe_count, LTIME_S, and PFID.
static int lmv_notify (struct obd_device * obd, struct obd_device * watched, enum obd_notify_event ev, void * data) [static]
Definition at line 147 of file lmv_obd.c.
References CERROR, client_obd::cl_import, client_obd::cl_target_uuid, obd_device::cli, ENTRY, obd_export::exp_connect_data, fld_client_flush(), obd_import::imp_connect_data, obd_device::lmv, lmv_obd::lmv_fld, lmv_set_mdc_active(), LUSTRE_MDC_NAME, obd_device::obd_name, obd_notify(), OBD_NOTIFY_ACTIVE, OBD_NOTIFY_DISCON, OBD_NOTIFY_INACTIVE, OBD_NOTIFY_OCD, obd_device::obd_observer, obd_device::obd_self_export, obd_device::obd_type, RETURN, obd_type::typ_name, obd_device::u, obd_uuid::uuid, and uuid.
static int lmv_null_inode (struct obd_export * exp, const struct lu_fid * fid) [static]
Definition at line 1596 of file lmv_obd.c.
References CDEBUG, D_INODE, lmv_obd::desc, DFID, ENTRY, obd_export::exp_obd, lmv_desc::ld_tgt_count, obd_device::lmv, lmv_check_connect(), lmv_tgt_desc::ltd_exp, md_null_inode(), PFID, RETURN, lmv_obd::tgts, and obd_device::u.
static int lmv_placement_policy (struct obd_device * obd, struct md_op_data * op_data, u32 * mds) [static]
This is _inode_ placement policy function (not name).
If stripe_offset is provided during setdirstripe (setdirstripe -i xx), xx MDS will be choosen.
Definition at line 1232 of file lmv_obd.c.
References CLI_SET_MEA, cpu_to_le32, lmv_obd::desc, ENTRY, LASSERT, lmv_desc::ld_tgt_count, le32_to_cpu, obd_device::lmv, lmv_user_md, md_op_data::op_cli_flags, md_op_data::op_data, md_op_data::op_default_stripe_offset, md_op_data::op_mds, RETURN, and obd_device::u.
Referenced by lmv_fid_alloc().
static int lmv_precleanup (struct obd_device * obd) [static]
Definition at line 2707 of file lmv_obd.c.
References ENTRY, fld_client_proc_fini(), obd_device::lmv, lmv_obd::lmv_fld, lprocfs_free_md_stats(), lprocfs_obd_cleanup(), RETURN, and obd_device::u.
static int lmv_process_config (struct obd_device * obd, size_t len, void * buf) [static]
Definition at line 1414 of file lmv_obd.c.
References CERROR, ENTRY, GOTO, LCFG_ADD_MDC, lustre_cfg::lcfg_command, lmv_add_target(), lustre_cfg_buf(), LUSTRE_CFG_BUFLEN, obd_str2uuid(), RETURN, and obd_uuid::uuid.
int lmv_quotactl (struct obd_device * unused, struct obd_export * exp, struct obd_quotactl * oqctl)
For lmv, only need to send request to master MDT, and the master MDT will process with other slave MDTs.
The only exception is Q_GETOQUOTA for which we directly fetch data from the slave MDTs.
Definition at line 3224 of file lmv_obd.c.
References __u64, CERROR, class_exp2obd(), lmv_obd::desc, obd_dqblk::dqb_curinodes, obd_dqblk::dqb_curspace, ENTRY, lmv_desc::ld_tgt_count, obd_device::lmv, lmv_tgt_desc::ltd_active, lmv_tgt_desc::ltd_exp, obd_quotactl(), Q_GETOQUOTA, obd_quotactl::qc_cmd, obd_quotactl::qc_dqblk, RETURN, lmv_obd::tgts, and obd_device::u.
int lmv_read_page (struct obd_export * exp, struct md_op_data * op_data, struct md_callback * cb_op, __u64 offset, struct page ** ppage)
Definition at line 2498 of file lmv_obd.c.
References ENTRY, obd_export::exp_obd, obd_device::lmv, lmv_check_connect(), lmv_find_target(), lmv_read_striped_page(), lmv_tgt_desc::ltd_exp, md_read_page(), md_op_data::op_fid1, md_op_data::op_mea1, RETURN, obd_device::u, and unlikely.
static int lmv_read_striped_page (struct obd_export * exp, struct md_op_data * op_data, struct md_callback * cb_op, __u64 offset, struct page ** ppage) [static]
Build dir entry page from a striped directory.
This function gets one entry by from a striped directory. It will read entries from all of stripes, and choose one closest to the required offset(&offset). A few notes 1. skip . and .. for non-zero stripes, because there can only have one . and .. in a directory. 2. op_data will be shared by all of stripes, instead of allocating new one, so need to restore before reusing. 3. release the entry page if that is not being chosen.
Parameters:
[in] exp obd export refer to LMV
[in] op_data hold those MD parameters of read_entry
[in] cb_op ldlm callback being used in enqueue in mdc_read_entry
[out] ldp the entry being read
[out] ppage the page holding the entry. Note: because the entry will be accessed in upper layer, so we need hold the page until the usages of entry is finished, see ll_dir_entry_next.
retval =0 if get entry successfully <0 cannot get entry
Definition at line 2373 of file lmv_obd.c.
References __u64, cpu_to_le16, cpu_to_le32, cpu_to_le64, ENTRY, obd_export::exp_obd, fid_cpu_to_le(), GOTO, lu_dirent::lde_attrs, lu_dirent::lde_fid, lu_dirent::lde_hash, lu_dirent::lde_name, lu_dirent::lde_namelen, lu_dirent::lde_reclen, LDF_COLLIDE, LDF_EMPTY, lu_dirpage::ldp_flags, lu_dirpage::ldp_hash_start, le16_to_cpu, le32_to_cpu, le64_to_cpu, lmv_check_connect(), lmv_get_min_striped_entry(), lu_dirent_calc_size(), MDS_DIR_END_OFF, md_op_data::op_data, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_fid3, RETURN, and unlikely.
Referenced by lmv_read_page().
static int lmv_rename (struct obd_export * exp, struct md_op_data * op_data, const char * old, size_t oldlen, const char * new, size_t newlen, struct ptlrpc_request ** request) [static]
Definition at line 1989 of file lmv_obd.c.
References CDEBUG, cfs_curproc_cap_pack(), CLI_MIGRATE, D_INODE, DFID, ENTRY, obd_export::exp_obd, fid_is_sane(), from_kgid(), from_kuid(), LASSERT, LASSERTF, LCK_EX, likely, obd_device::lmv, lmv_check_connect(), lmv_early_cancel(), lmv_fid_alloc(), lmv_find_target(), lmv_locate_target_for_name(), lmv_stripe_md::lsm_md_stripe_count, lmv_tgt_desc::ltd_exp, lmv_tgt_desc::ltd_idx, mdt_body::mbo_fid1, mdt_body::mbo_valid, md_rename(), MDS_INODELOCK_FULL, MDS_INODELOCK_LOOKUP, MDS_INODELOCK_UPDATE, MF_MDC_CANCEL_FID1, MF_MDC_CANCEL_FID2, MF_MDC_CANCEL_FID3, MF_MDC_CANCEL_FID4, OBD_MD_MDS, obd_device::obd_name, md_op_data::op_cap, md_op_data::op_cli_flags, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_fid3, md_op_data::op_fid4, md_op_data::op_flags, md_op_data::op_fsgid, md_op_data::op_fsuid, md_op_data::op_mds, md_op_data::op_mea1, md_op_data::op_mea2, PFID, ptlrpc_req_finished(), req_capsule_server_get(), RETURN, RMF_MDT_BODY, and obd_device::u.
int lmv_revalidate_lock (struct obd_export * exp, struct lookup_intent * it, struct lu_fid * fid, __u64 * bits)
Definition at line 3182 of file lmv_obd.c.
References ENTRY, obd_export::exp_obd, obd_device::lmv, lmv_check_connect(), lmv_find_target(), lmv_tgt_desc::ltd_exp, md_revalidate_lock(), RETURN, and obd_device::u.
int lmv_set_info_async (const struct lu_env * env, struct obd_export * exp, __u32 keylen, void * key, __u32 vallen, void * val, struct ptlrpc_request_set * set)
Asynchronously set by key a value associated with a LMV device.
Dispatch request to lower-layer devices as needed.
Parameters:
[in] env execution environment for this thread
[in] exp export for the LMV device
[in] keylen length of key identifier
[in] key identifier of key to store value for
[in] vallen size of value to store
[in] val pointer to data to be stored
[in] set optional list of related ptlrpc requests
Return values:
0 on success
negative negated errno on failure
Definition at line 2810 of file lmv_obd.c.
References CDEBUG, class_exp2obd(), D_IOCTL, lmv_obd::desc, ENTRY, obd_export::exp_handle, portals_handle::h_cookie, KEY_DEFAULT_EASIZE, KEY_FLUSH_CTX, KEY_IS, KEY_READ_ONLY, lmv_desc::ld_tgt_count, obd_device::lmv, LPX64, lmv_tgt_desc::ltd_exp, obd_set_info_async(), RETURN, lmv_obd::tgts, and obd_device::u.
int lmv_set_lock_data (struct obd_export * exp, __u64 * lockh, void * data, __u64 * bits)
Definition at line 3005 of file lmv_obd.c.
References ENTRY, obd_export::exp_obd, obd_device::lmv, lmv_tgt_desc::ltd_exp, md_set_lock_data(), RETURN, lmv_obd::tgts, and obd_device::u.
static int lmv_set_mdc_active (struct lmv_obd * lmv, const struct obd_uuid * uuid, int activate) [static]
Error codes:.
-EINVAL : UUID can't be found in the LMV's target list -ENOTCONN: The UUID is found, but the target connection is bad (!) -EBADF : The UUID is found, but the OBD of the wrong type (!)
Definition at line 85 of file lmv_obd.c.
References CDEBUG, class_exp2obd(), D_INFO, lmv_obd::desc, ENTRY, EXIT, obd_export::exp_handle, GOTO, portals_handle::h_cookie, LASSERT, lmv_desc::ld_tgt_count, lmv_activate_target(), lmv_obd::lmv_lock, LPX64, lmv_tgt_desc::ltd_active, lmv_tgt_desc::ltd_exp, lmv_tgt_desc::ltd_uuid, LUSTRE_MDC_NAME, obd_device::obd_minor, obd_device::obd_name, obd_device::obd_type, obd_device::obd_uuid, obd_uuid_equals(), lmv_obd::tgts, obd_type::typ_name, and obd_uuid::uuid.
Referenced by lmv_notify().
int lmv_set_open_replay_data (struct obd_export * exp, struct obd_client_handle * och, struct lookup_intent * it)
Definition at line 3091 of file lmv_obd.c.
References ENTRY, obd_export::exp_obd, obd_device::lmv, lmv_find_target(), lmv_tgt_desc::ltd_exp, md_set_open_replay_data(), obd_client_handle::och_fid, RETURN, and obd_device::u.
static int lmv_setattr (struct obd_export * exp, struct md_op_data * op_data, void * ea, size_t ealen, struct ptlrpc_request ** request) [static]
Definition at line 2164 of file lmv_obd.c.
References CDEBUG, D_INODE, DFID, ENTRY, obd_export::exp_obd, obd_device::lmv, lmv_check_connect(), lmv_find_target(), lmv_tgt_desc::ltd_exp, md_setattr(), MF_MDC_CANCEL_FID1, md_op_data::op_attr, md_op_data::op_fid1, md_op_data::op_flags, PFID, RETURN, and obd_device::u.
static int lmv_setup (struct obd_device * obd, struct lustre_cfg * lcfg) [static]
Definition at line 1338 of file lmv_obd.c.
References CERROR, CWARN, lmv_obd::desc, ENTRY, fld_client_init(), GOTO, lmv_desc::ld_active_tgt_count, lmv_desc::ld_tgt_count, lmv_desc::ld_uuid, obd_device::lmv, lmv_obd::lmv_fld, lmv_obd::lmv_init_mutex, lmv_obd::lmv_lock, lmv_obd::lmv_placement, lmv_proc_target_fops, lprocfs_alloc_md_stats(), lprocfs_obd_setup(), lustre_cfg_buf(), LUSTRE_CFG_BUFLEN, LUSTRE_CLI_FLD_HASH_DHT, lmv_obd::max_def_easize, lmv_obd::max_easize, OBD_ALLOC, obd_device::obd_name, obd_device::obd_proc_entry, obd_str2uuid(), obd_device::obd_vars, PLACEMENT_CHAR_POLICY, RETURN, lmv_obd::tgts, lmv_obd::tgts_size, obd_device::u, and obd_uuid::uuid.
static int lmv_setxattr (struct obd_export * exp, const struct lu_fid * fid, u64 valid, const char * name, const char * input, int input_size, int output_size, int flags, __u32 suppgid, struct ptlrpc_request ** request) [static]
Definition at line 1542 of file lmv_obd.c.
References ENTRY, obd_export::exp_obd, obd_device::lmv, lmv_check_connect(), lmv_find_target(), lmv_tgt_desc::ltd_exp, md_setxattr(), RETURN, and obd_device::u.
static int lmv_statfs (const struct lu_env * env, struct obd_export * exp, struct obd_statfs * osfs, __u64 max_age, __u32 flags) [static]
Definition at line 1446 of file lmv_obd.c.
References CERROR, class_exp2obd(), lmv_obd::desc, ENTRY, EXIT, obd_export::exp_obd, GOTO, lmv_desc::ld_tgt_count, obd_device::lmv, lmv_check_connect(), lmv_tgt_desc::ltd_exp, OBD_ALLOC, OBD_FREE, obd_device::obd_name, obd_statfs(), OBD_STATFS_FOR_MDT0, obd_statfs::os_bavail, obd_statfs::os_blocks, obd_statfs::os_ffree, obd_statfs::os_files, RETURN, lmv_obd::tgts, and obd_device::u.
static int lmv_unlink (struct obd_export * exp, struct md_op_data * op_data, struct ptlrpc_request ** request) [static]
Unlink a file/directory.
Unlink a file or directory under the parent dir. The unlink request usually will be sent to the MDT where the child is located, but if the client does not have the child FID then request will be sent to the MDT where the parent is located.
If the parent is a striped directory then it also needs to locate which stripe the name of the child is located, and replace the parent FID (->op_fid1) with the stripe FID. Note: if the stripe is unknown, it will walk through all of sub-stripes until the child is being unlinked finally.
Parameters:
[in] exp export refer to LMV
[in] op_data different parameters transferred beween client MD stacks, name, namelen, FIDs etc. op_fid1 is the parent FID, op_fid2 is the child FID.
[out] request point to the request of unlink.
retval 0 if succeed negative errno if failed.
Definition at line 2551 of file lmv_obd.c.
References CDEBUG, cfs_curproc_cap_pack(), D_INODE, DFID, ENTRY, obd_export::exp_obd, fid_is_zero(), from_kgid(), from_kuid(), LASSERT, LCK_EX, likely, lmv_oinfo::lmo_fid, lmv_oinfo::lmo_mds, obd_device::lmv, lmv_check_connect(), lmv_early_cancel(), lmv_find_target(), lmv_get_target(), lmv_is_known_hash_type(), lmv_locate_mds(), lmv_locate_target_for_name(), lmv_need_try_all_stripes(), lmv_stripe_md::lsm_md_hash_type, lmv_stripe_md::lsm_md_oinfo, lmv_stripe_md::lsm_md_stripe_count, lmv_tgt_desc::ltd_exp, lmv_tgt_desc::ltd_idx, mdt_body::mbo_fid1, mdt_body::mbo_valid, md_unlink(), MDS_INODELOCK_FULL, MDS_INODELOCK_LOOKUP, MF_MDC_CANCEL_FID1, MF_MDC_CANCEL_FID3, OBD_MD_MDS, obd_device::obd_name, md_op_data::op_cap, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_flags, md_op_data::op_fsgid, md_op_data::op_fsuid, md_op_data::op_mds, md_op_data::op_mea1, md_op_data::op_name, md_op_data::op_namelen, PFID, ptlrpc_req_finished(), req_capsule_server_get(), RETURN, RMF_MDT_BODY, and obd_device::u.
static int lmv_unpack_md_v1 (struct obd_export * exp, struct lmv_stripe_md * lsm, const struct lmv_mds_md_v1 * lmm1) [static]
Definition at line 2850 of file lmv_obd.c.
References CDEBUG, D_INFO, DFID, ENTRY, obd_export::exp_obd, fid_le_to_cpu(), le32_to_cpu, lmv_oinfo::lmo_fid, lmv_oinfo::lmo_mds, obd_device::lmv, lmv_fld_lookup(), lmv_mds_md_v1::lmv_hash_type, LMV_HASH_TYPE_UNKNOWN, lmv_mds_md_v1::lmv_layout_version, lmv_mds_md_v1::lmv_magic, lmv_mds_md_v1::lmv_master_mdt_index, lmv_mds_md_v1::lmv_pool_name, lmv_mds_md_v1::lmv_stripe_count, lmv_mds_md_v1::lmv_stripe_fids, lmv_stripe_md::lsm_md_hash_type, lmv_stripe_md::lsm_md_layout_version, lmv_stripe_md::lsm_md_magic, lmv_stripe_md::lsm_md_master_mdt_index, lmv_stripe_md::lsm_md_oinfo, lmv_stripe_md::lsm_md_pool_name, lmv_stripe_md::lsm_md_stripe_count, OBD_FAIL_CHECK, OBD_FAIL_UNKNOWN_LMV_STRIPE, PFID, RETURN, strlcpy(), and obd_device::u.
Referenced by lmv_unpackmd().
static int lmv_unpackmd (struct obd_export * exp, struct lmv_stripe_md ** lsmp, const union lmv_mds_md * lmm, size_t lmm_size) [static]
Unpack default dirstripe(lmv_user_md) to lmv_stripe_md, stripecount should be 0 then.
Definition at line 2894 of file lmv_obd.c.
References CERROR, ENTRY, obd_export::exp_obd, LASSERT, le32_to_cpu, lmv_oinfo::lmo_root, LMV_HASH_FLAG_MIGRATION, lmv_mds_md::lmv_magic, LMV_MAGIC_STRIPE, LMV_MAGIC_V1, lmv_mds_md::lmv_md_v1, lmv_mds_md_stripe_count_get(), lmv_stripe_md_size(), lmv_unpack_md_v1(), LMV_USER_MAGIC, lmv_stripe_md::lsm_md_hash_type, lmv_stripe_md::lsm_md_oinfo, lmv_stripe_md::lsm_md_stripe_count, OBD_ALLOC, OBD_FREE, obd_device::obd_name, and RETURN.
Referenced by lmv_free_memmd().
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Logical Metadata Volume")
module_exit (lmv_exit)
module_init (lmv_init)
MODULE_LICENSE ("GPL")
MODULE_VERSION (LUSTRE_VERSION_STRING)
Variable Documentation
struct md_ops lmv_md_ops
Definition at line 3332 of file lmv_obd.c.
struct obd_ops lmv_obd_ops
Initial value:
 {
        .o_owner                = THIS_MODULE,
        .o_setup                = lmv_setup,
        .o_cleanup              = lmv_cleanup,
        .o_precleanup           = lmv_precleanup,
        .o_process_config       = lmv_process_config,
        .o_connect              = lmv_connect,
        .o_disconnect           = lmv_disconnect,
        .o_statfs               = lmv_statfs,
        .o_get_info             = lmv_get_info,
        .o_set_info_async       = lmv_set_info_async,
        .o_notify               = lmv_notify,
        .o_get_uuid             = lmv_get_uuid,
        .o_iocontrol            = lmv_iocontrol,
        .o_quotactl             = lmv_quotactl
}
Definition at line 3315 of file lmv_obd.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.