Lustre: lustre/lmv/lmv_internal.h File Reference
lustre/lmv/lmv_internal.h File Reference
#include <lustre/lustre_idl.h>
#include <obd.h>
#include <lustre_lmv.h>
Defines
#define LMV_MAX_TGT_COUNT 128
#define LL_IT2STR(it) ((it) ? ldlm_it2str((it)->it_op) : "0")
Functions
int lmv_check_connect (struct obd_device *obd)
int lmv_intent_lock (struct obd_export *exp, struct md_op_data *op_data, struct lookup_intent *it, struct ptlrpc_request **reqp, ldlm_blocking_callback cb_blocking, __u64 extra_lock_flags)
int lmv_blocking_ast (struct ldlm_lock *, struct ldlm_lock_desc *, void *, int)
int lmv_fld_lookup (struct lmv_obd *lmv, const struct lu_fid *fid, u32 *mds)
int __lmv_fid_alloc (struct lmv_obd *lmv, struct lu_fid *fid, u32 mds)
int lmv_fid_alloc (const struct lu_env *env, struct obd_export *exp, struct lu_fid *fid, struct md_op_data *op_data)
int lmv_revalidate_slaves (struct obd_export *exp, const struct lmv_stripe_md *lsm, ldlm_blocking_callback cb_blocking, int extra_lock_flags)
static struct obd_device * lmv2obd_dev (struct lmv_obd *lmv)
static struct lmv_tgt_desc * lmv_get_target (struct lmv_obd *lmv, u32 mdt_idx, int *index)
static int lmv_find_target_index (struct lmv_obd *lmv, const struct lu_fid *fid)
static struct lmv_tgt_desc * lmv_find_target (struct lmv_obd *lmv, const struct lu_fid *fid)
static int lmv_stripe_md_size (int stripe_count)
static struct lmv_oinfo * lsm_name_to_stripe_info (const struct lmv_stripe_md *lsm, const char *name, int namelen)
static bool lmv_need_try_all_stripes (const struct lmv_stripe_md *lsm)
struct lmv_tgt_desc * lmv_locate_mds (struct lmv_obd *lmv, struct md_op_data *op_data, struct lu_fid *fid)
Locate mds by fid or name.
Variables
struct file_operations lmv_proc_target_fops
Define Documentation
#define LL_IT2STR (it) ((it) ? ldlm_it2str((it)->it_op) : "0")
Definition at line 46 of file lmv_internal.h.
#define LMV_MAX_TGT_COUNT 128
Definition at line 44 of file lmv_internal.h.
Function Documentation
int __lmv_fid_alloc (struct lmv_obd * lmv, struct lu_fid * fid, u32 mds)
Definition at line 1276 of file lmv_obd.c.
References ENTRY, EXIT, fid_is_sane(), GOTO, LASSERT, lmv_get_target(), lmv_tgt_desc::ltd_active, lmv_tgt_desc::ltd_exp, lmv_tgt_desc::ltd_fid_mutex, obd_fid_alloc(), and RETURN.
Referenced by lmv_fid_alloc().
static struct obd_device* lmv2obd_dev (struct lmv_obd * lmv) [static, read]
Definition at line 68 of file lmv_internal.h.
References obd_device::u.
Referenced by lmv_fld_lookup().
int lmv_blocking_ast (struct ldlm_lock * , struct ldlm_lock_desc * , void * , int)
int lmv_check_connect (struct obd_device * obd)
Definition at line 524 of file lmv_obd.c.
References CDEBUG, CERROR, class_disconnect(), class_export_put(), lmv_obd::cluuid, lmv_obd::connected, D_CONFIG, lmv_obd::desc, ENTRY, lmv_obd::exp, GOTO, LASSERT, lmv_desc::ld_active_tgt_count, lmv_desc::ld_tgt_count, obd_device::lmv, lmv_connect_mdc(), lmv_init_ea_size(), lmv_obd::lmv_init_mutex, LMV_MAGIC, lmv_mds_md_size(), lmv_tgt_desc::ltd_active, lmv_tgt_desc::ltd_exp, lmv_tgt_desc::ltd_uuid, obd_disconnect(), obd_device::obd_name, obd_device::obd_self_export, RETURN, lmv_obd::tgts, obd_device::u, and obd_uuid::uuid.
Referenced by lmv_close(), lmv_connect(), lmv_create(), lmv_enqueue(), lmv_fsync(), lmv_get_info(), lmv_get_remote_perm(), lmv_get_root(), lmv_getattr(), lmv_getattr_name(), lmv_getxattr(), lmv_intent_getattr_async(), lmv_intent_lock(), lmv_link(), lmv_null_inode(), lmv_read_page(), lmv_read_striped_page(), lmv_rename(), lmv_revalidate_lock(), lmv_setattr(), lmv_setxattr(), lmv_statfs(), and lmv_unlink().
int lmv_fid_alloc (const struct lu_env * env, struct obd_export * exp, struct lu_fid * fid, struct md_op_data * op_data)
Definition at line 1310 of file lmv_obd.c.
References __lmv_fid_alloc(), CERROR, class_exp2obd(), ENTRY, LASSERT, obd_device::lmv, lmv_placement_policy(), RETURN, and obd_device::u.
Referenced by lmv_create(), lmv_intent_open(), and lmv_rename().
static struct lmv_tgt_desc* lmv_find_target (struct lmv_obd * lmv, const struct lu_fid * fid) [static, read]
Definition at line 114 of file lmv_internal.h.
References lmv_find_target_index(), and lmv_obd::tgts.
Referenced by lmv_clear_open_replay_data(), lmv_close(), lmv_create(), lmv_early_cancel(), lmv_fid2path(), lmv_fsync(), lmv_get_remote_perm(), lmv_getattr(), lmv_getattr_name(), lmv_getxattr(), lmv_hsm_req_build(), lmv_hsm_req_count(), lmv_intent_lookup(), lmv_intent_open(), lmv_intent_remote(), lmv_iocontrol(), lmv_locate_mds(), lmv_read_page(), lmv_rename(), lmv_revalidate_lock(), lmv_set_open_replay_data(), lmv_setattr(), lmv_setxattr(), and lmv_unlink().
static int lmv_find_target_index (struct lmv_obd * lmv, const struct lu_fid * fid) [inline, static]
Definition at line 93 of file lmv_internal.h.
References lmv_obd::desc, lmv_desc::ld_tgt_count, lmv_fld_lookup(), and lmv_get_target().
Referenced by lmv_find_target(), and lmv_lock_match().
int lmv_fld_lookup (struct lmv_obd * lmv, const struct lu_fid * fid, u32 * mds)
Definition at line 56 of file lmv_fld.c.
References CDEBUG, CERROR, D_INODE, lmv_obd::desc, DFID, ENTRY, fid_is_sane(), fid_seq_in_fldb(), fid_seq_is_local_file(), fld_client_lookup(), lmv_desc::ld_tgt_count, lmv2obd_dev(), lmv_obd::lmv_fld, LPX64, LU_SEQ_RANGE_MDT, obd_device::obd_name, PFID, and RETURN.
Referenced by lmv_find_target_index(), lmv_iocontrol(), and lmv_unpack_md_v1().
static struct lmv_tgt_desc* lmv_get_target (struct lmv_obd * lmv, u32 mdt_idx, int * index) [static, read]
Definition at line 74 of file lmv_internal.h.
References lmv_obd::desc, lmv_desc::ld_tgt_count, lmv_tgt_desc::ltd_idx, and lmv_obd::tgts.
Referenced by __lmv_fid_alloc(), lmv_find_target_index(), lmv_get_min_striped_entry(), lmv_intent_lookup(), lmv_locate_mds(), lmv_locate_target_for_name(), and lmv_unlink().
int lmv_intent_lock (struct obd_export * exp, struct md_op_data * op_data, struct lookup_intent * it, struct ptlrpc_request ** reqp, ldlm_blocking_callback cb_blocking, __u64 extra_lock_flags)
Definition at line 469 of file lmv_intent.c.
References CDEBUG, lustre_handle::cookie, D_INODE, DFID, ENTRY, obd_export::exp_obd, fid_is_sane(), IT_GETATTR, IT_LAYOUT, lookup_intent::it_lock_handle, lookup_intent::it_lock_mode, IT_LOOKUP, lookup_intent::it_op, IT_OPEN, lookup_intent::it_remote_lock_handle, lookup_intent::it_remote_lock_mode, LASSERT, LBUG, ldlm_lock_decref(), LL_IT2STR, lmv_check_connect(), lmv_intent_lookup(), lmv_intent_open(), md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_name, md_op_data::op_namelen, PFID, and RETURN.
struct lmv_tgt_desc* lmv_locate_mds (struct lmv_obd * lmv, struct md_op_data * op_data, struct lu_fid * fid) [read]
Locate mds by fid or name.
For striped directory (lsm != NULL), it will locate the stripe by name hash (see lsm_name_to_stripe_info()). Note: if the hash_type is unknown, it will return -EBADFD, and lmv_intent_lookup might need walk through all of stripes to locate the entry.
For normal direcotry, it will locate MDS by FID directly.
Parameters:
[in] lmv LMV device
[in] op_data client MD stack parameters, name, namelen mds_num etc.
[in] fid object FID used to locate MDS.
retval pointer to the lmv_tgt_desc if succeed. ERR_PTR(errno) if failed.
Definition at line 1700 of file lmv_obd.c.
References lmv_oinfo::lmo_fid, lmv_oinfo::lmo_mds, lmv_find_target(), lmv_get_target(), lmv_locate_target_for_name(), lmv_stripe_md::lsm_md_oinfo, lmv_stripe_md::lsm_md_stripe_count, lmv_tgt_desc::ltd_idx, MDS_CREATE_VOLATILE, md_op_data::op_bias, md_op_data::op_mds, md_op_data::op_mea1, md_op_data::op_name, and md_op_data::op_namelen.
Referenced by lmv_create(), lmv_enqueue(), lmv_getattr_name(), lmv_intent_getattr_async(), lmv_intent_lookup(), lmv_intent_open(), lmv_link(), lmv_revalidate_slaves(), and lmv_unlink().
static bool lmv_need_try_all_stripes (const struct lmv_stripe_md * lsm) [inline, static]
Definition at line 152 of file lmv_internal.h.
References LMV_HASH_FLAG_MIGRATION, lmv_is_known_hash_type(), and lmv_stripe_md::lsm_md_hash_type.
Referenced by lmv_intent_lookup(), and lmv_unlink().
int lmv_revalidate_slaves (struct obd_export * exp, const struct lmv_stripe_md * lsm, ldlm_blocking_callback cb_blocking, int extra_lock_flags)
revalidate slaves has some problems, temporarily return, we may not need that
Loop over the stripe information, check validity and update them from MDS if needed.
Definition at line 155 of file lmv_intent.c.
References CDEBUG, cleanup(), lustre_handle::cookie, D_INODE, DFID, ENTRY, obd_export::exp_obd, GOTO, IT_GETATTR, lookup_intent::it_lock_handle, lookup_intent::it_lock_mode, lookup_intent::it_op, ldlm_lock_decref(), lmv_oinfo::lmo_fid, lmv_oinfo::lmo_root, obd_device::lmv, lmv_locate_mds(), lmv_stripe_md::lsm_md_oinfo, lmv_stripe_md::lsm_md_stripe_count, lmv_tgt_desc::ltd_exp, lmv_tgt_desc::ltd_idx, LTIME_S, mdt_body::mbo_atime, mdt_body::mbo_blocks, mdt_body::mbo_ctime, mdt_body::mbo_mtime, mdt_body::mbo_nlink, mdt_body::mbo_size, md_intent_lock(), md_set_lock_data(), OBD_ALLOC_PTR, OBD_FREE_PTR, md_op_data::op_data, md_op_data::op_fid1, md_op_data::op_fid2, PFID, ptlrpc_req_finished(), req_capsule_server_get(), RETURN, RMF_MDT_BODY, ptlrpc_request::rq_pill, set_nlink(), and obd_device::u.
Referenced by lmv_intent_lookup(), and lmv_merge_attr().
static int lmv_stripe_md_size (int stripe_count) [inline, static]
Definition at line 125 of file lmv_internal.h.
References lmv_stripe_md::lsm_md_oinfo.
Referenced by lmv_unpackmd().
static struct lmv_oinfo* lsm_name_to_stripe_info (const struct lmv_stripe_md * lsm, const char * name, int namelen) [static, read]
Definition at line 133 of file lmv_internal.h.
References LASSERTF, lmv_name_to_stripe_index(), lmv_stripe_md::lsm_md_hash_type, lmv_stripe_md::lsm_md_oinfo, and lmv_stripe_md::lsm_md_stripe_count.
Referenced by lmv_get_fid_from_lsm(), lmv_link(), and lmv_locate_target_for_name().
Variable Documentation
struct file_operations lmv_proc_target_fops
Referenced by lmv_setup().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.