Lustre: lustre/lmv/lmv_fld.c File Reference
lustre/lmv/lmv_fld.c File Reference
#include <linux/slab.h>
#include <linux/module.h>
#include <linux/init.h>
#include <linux/pagemap.h>
#include <linux/math64.h>
#include <linux/seq_file.h>
#include <obd_support.h>
#include <lustre/lustre_idl.h>
#include <lustre_fid.h>
#include <lustre_lib.h>
#include <lustre_net.h>
#include <lustre_dlm.h>
#include <obd_class.h>
#include <lprocfs_status.h>
#include "lmv_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LMV
Functions
int lmv_fld_lookup (struct lmv_obd *lmv, const struct lu_fid *fid, u32 *mds)
Define Documentation
#define DEBUG_SUBSYSTEM S_LMV
Definition at line 37 of file lmv_fld.c.
Function Documentation
int lmv_fld_lookup (struct lmv_obd * lmv, const struct lu_fid * fid, u32 * mds)
Definition at line 56 of file lmv_fld.c.
References CDEBUG, CERROR, D_INODE, lmv_obd::desc, DFID, ENTRY, fid_is_sane(), fid_seq_in_fldb(), fid_seq_is_local_file(), fld_client_lookup(), lmv_desc::ld_tgt_count, lmv2obd_dev(), lmv_obd::lmv_fld, LPX64, LU_SEQ_RANGE_MDT, obd_device::obd_name, PFID, and RETURN.
Referenced by lmv_find_target_index(), lmv_iocontrol(), and lmv_unpack_md_v1().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.