Lustre: lnet/lnet/module.c File Reference
lnet/lnet/module.c File Reference
#include <lnet/lib-lnet.h>
#include <lnet/lib-dlc.h>
Defines
#define DEBUG_SUBSYSTEM S_LNET
Functions
module_param (config_on_load, int, 0444)
MODULE_PARM_DESC (config_on_load,"configure network at module load")
static int lnet_configure (void *arg)
static int lnet_unconfigure (void)
static int lnet_dyn_configure (struct libcfs_ioctl_hdr *hdr)
static int lnet_dyn_unconfigure (struct libcfs_ioctl_hdr *hdr)
static int lnet_ioctl (unsigned int cmd, struct libcfs_ioctl_hdr *hdr)
DECLARE_IOCTL_HANDLER (lnet_ioctl_handler, lnet_ioctl)
static int __init lnet_init (void)
static void __exit lnet_exit (void)
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Networking layer")
MODULE_VERSION (LNET_VERSION)
MODULE_LICENSE ("GPL")
module_init (lnet_init)
module_exit (lnet_exit)
Variables
static int config_on_load = 0
static struct mutex lnet_config_mutex
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 37 of file module.c.
Function Documentation
DECLARE_IOCTL_HANDLER (lnet_ioctl_handler , lnet_ioctl)
static int lnet_configure (void * arg) [static]
Definition at line 48 of file module.c.
References lnet_t::ln_niinit_self, lnet_config_mutex, LNET_PID_LUSTRE, LNetNIInit(), and the_lnet.
Referenced by lnet_init(), and lnet_ioctl().
static int lnet_dyn_configure (struct libcfs_ioctl_hdr * hdr) [static]
Definition at line 98 of file module.c.
References lnet_t::ln_niinit_self, lnet_config_mutex, lnet_dyn_add_ni(), LNET_PID_LUSTRE, and the_lnet.
Referenced by lnet_ioctl().
static int lnet_dyn_unconfigure (struct libcfs_ioctl_hdr * hdr) [static]
Definition at line 114 of file module.c.
References lnet_ioctl_config_data::cfg_net, lnet_t::ln_niinit_self, lnet_config_mutex, lnet_dyn_del_ni(), and the_lnet.
Referenced by lnet_ioctl().
static void __exit lnet_exit (void) [static]
Definition at line 192 of file module.c.
References LASSERT, libcfs_deregister_ioctl(), and lnet_lib_exit().
static int __init lnet_init (void) [static]
Definition at line 167 of file module.c.
References CERROR, config_on_load, ENTRY, LASSERT, libcfs_register_ioctl(), lnet_config_mutex, lnet_configure(), lnet_lib_init(), and RETURN.
static int lnet_ioctl (unsigned int cmd, struct libcfs_ioctl_hdr * hdr) [static]
Definition at line 131 of file module.c.
References libcfs_ioctl_data::ioc_flags, IOC_LIBCFS_ADD_NET, IOC_LIBCFS_CONFIGURE, IOC_LIBCFS_DEL_NET, IOC_LIBCFS_UNCONFIGURE, lnet_t::ln_nis_from_mod_params, lnet_configure(), lnet_dyn_configure(), lnet_dyn_unconfigure(), LNET_PID_ANY, lnet_unconfigure(), LNetCtl(), LNetNIFini(), LNetNIInit(), and the_lnet.
static int lnet_unconfigure (void) [static]
Definition at line 76 of file module.c.
References lnet_t::ln_api_mutex, lnet_t::ln_niinit_self, lnet_t::ln_refcount, lnet_config_mutex, LNetNIFini(), and the_lnet.
Referenced by lnet_ioctl().
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Networking layer")
module_exit (lnet_exit)
module_init (lnet_init)
MODULE_LICENSE ("GPL")
module_param (config_on_load , int , 0444)
MODULE_PARM_DESC (config_on_load , "configure network at module load")
MODULE_VERSION (LNET_VERSION)
Variable Documentation
int config_on_load = 0 [static]
Definition at line 41 of file module.c.
Referenced by lnet_init().
struct mutex lnet_config_mutex [static]
Definition at line 45 of file module.c.
Referenced by lnet_configure(), lnet_dyn_configure(), lnet_dyn_unconfigure(), lnet_init(), and lnet_unconfigure().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.