Lustre: lnet/selftest/module.c File Reference
lnet/selftest/module.c File Reference
#include "selftest.h"
#include "console.h"
Defines
#define DEBUG_SUBSYSTEM S_LNET
Enumerations
enum {
LST_INIT_NONE = 0, LST_INIT_WI_SERIAL, LST_INIT_WI_TEST, LST_INIT_RPC,
LST_INIT_FW, LST_INIT_CONSOLE
}
Functions
static void lnet_selftest_exit (void)
void lnet_selftest_structure_assertion (void)
static int __init lnet_selftest_init (void)
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("LNet Selftest")
MODULE_VERSION ("2.8.0")
MODULE_LICENSE ("GPL")
module_init (lnet_selftest_init)
module_exit (lnet_selftest_exit)
Variables
static int lst_init_step = LST_INIT_NONE
struct cfs_wi_sched * lst_sched_serial
struct cfs_wi_sched ** lst_sched_test
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 37 of file module.c.
Enumeration Type Documentation
anonymous enum
Enumerator:
LST_INIT_NONE
LST_INIT_WI_SERIAL
LST_INIT_WI_TEST
LST_INIT_RPC
LST_INIT_FW
LST_INIT_CONSOLE
Definition at line 42 of file module.c.
Function Documentation
static void lnet_selftest_exit (void) [static]
Definition at line 57 of file module.c.
References cfs_cpt_number(), cfs_wi_sched_destroy(), LBUG, LIBCFS_FREE, lnet_cpt_table, LST_INIT_CONSOLE, LST_INIT_FW, LST_INIT_NONE, LST_INIT_RPC, lst_init_step, LST_INIT_WI_SERIAL, LST_INIT_WI_TEST, lstcon_console_fini(), sfw_shutdown(), and srpc_shutdown().
Referenced by lnet_selftest_init().
static int __init lnet_selftest_init (void) [static]
Definition at line 103 of file module.c.
References CERROR, CFS_CPT_ANY, cfs_cpt_number(), cfs_cpt_weight(), cfs_wi_sched_create(), error, LIBCFS_ALLOC, lnet_cpt_table, lnet_selftest_exit(), LST_INIT_CONSOLE, LST_INIT_FW, LST_INIT_RPC, lst_init_step, LST_INIT_WI_SERIAL, LST_INIT_WI_TEST, lstcon_console_init(), max, nscheds, sfw_startup(), and srpc_startup().
void lnet_selftest_structure_assertion (void)
Definition at line 92 of file module.c.
References CLASSERT, and offsetof.
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("LNet Selftest")
module_exit (lnet_selftest_exit)
module_init (lnet_selftest_init)
MODULE_LICENSE ("GPL")
MODULE_VERSION ("2.8.0")
Variable Documentation
int lst_init_step = LST_INIT_NONE [static]
Definition at line 51 of file module.c.
Referenced by lnet_selftest_exit(), and lnet_selftest_init().
struct cfs_wi_sched* lst_sched_serial
Definition at line 53 of file module.c.
Referenced by srpc_init_server_rpc().
struct cfs_wi_sched** lst_sched_test
Definition at line 54 of file module.c.
Referenced by sfw_run_batch(), srpc_init_server_rpc(), and srpc_service_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.