Lustre: lnet/utils/lnetctl.c File Reference
lnet/utils/lnetctl.c File Reference
#include <getopt.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <libcfs/util/ioctl.h>
#include <libcfs/util/parser.h>
#include <lnet/lnetctl.h>
#include "cyaml/cyaml.h"
#include "lnetconfig/liblnetconfig.h"
Defines
#define LNET_CONFIGURE true
#define LNET_UNCONFIGURE false
Functions
static int jt_config_lnet (int argc, char **argv)
static int jt_unconfig_lnet (int argc, char **argv)
static int jt_add_route (int argc, char **argv)
static int jt_add_net (int argc, char **argv)
static int jt_set_routing (int argc, char **argv)
static int jt_del_route (int argc, char **argv)
static int jt_del_net (int argc, char **argv)
static int jt_show_route (int argc, char **argv)
static int jt_show_net (int argc, char **argv)
static int jt_show_routing (int argc, char **argv)
static int jt_show_stats (int argc, char **argv)
static int jt_show_peer_credits (int argc, char **argv)
static int jt_set_tiny (int argc, char **argv)
static int jt_set_small (int argc, char **argv)
static int jt_set_large (int argc, char **argv)
static void print_help (const command_t cmds[], const char *cmd_type, const char *pc_name)
static int parse_long (const char *number, long int *value)
static int handle_help (const command_t *cmd_list, const char *cmd, const char *sub_cmd, int argc, char **argv)
static int jt_lnet (int argc, char **argv)
static int jt_route (int argc, char **argv)
static int jt_net (int argc, char **argv)
static int jt_routing (int argc, char **argv)
static int jt_stats (int argc, char **argv)
static int jt_peer_credits (int argc, char **argv)
static int jt_set (int argc, char **argv)
static int jt_import (int argc, char **argv)
static int jt_export (int argc, char **argv)
int main (int argc, char **argv)
Variables
command_t lnet_cmds []
command_t route_cmds []
command_t net_cmds []
command_t routing_cmds []
command_t stats_cmds []
command_t credits_cmds []
command_t set_cmds []
command_t list []
Define Documentation
#define LNET_CONFIGURE true
Definition at line 36 of file lnetctl.c.
Referenced by jt_config_lnet().
#define LNET_UNCONFIGURE false
Definition at line 37 of file lnetctl.c.
Referenced by jt_unconfig_lnet().
Function Documentation
static int handle_help (const command_t * cmd_list, const char * cmd, const char * sub_cmd, int argc, char ** argv) [static]
Definition at line 155 of file lnetctl.c.
References opt, optind, and print_help().
Referenced by jt_lnet(), jt_net(), jt_peer_credits(), jt_route(), jt_routing(), jt_set(), jt_set_large(), jt_set_routing(), jt_set_small(), jt_set_tiny(), jt_show_peer_credits(), jt_show_routing(), jt_show_stats(), jt_stats(), and jt_unconfig_lnet().
static int jt_add_net (int argc, char ** argv) [static]
Definition at line 413 of file lnetctl.c.
References cYAML_free_tree(), cYAML_print_tree2file(), LUSTRE_CFG_RC_NO_ERR, lustre_lnet_config_net(), opt, optarg, parse_long(), and print_help().
static int jt_add_route (int argc, char ** argv) [static]
Definition at line 353 of file lnetctl.c.
References cYAML_free_tree(), cYAML_print_tree2file(), LUSTRE_CFG_RC_NO_ERR, lustre_lnet_config_route(), opt, optarg, parse_long(), and print_help().
static int jt_config_lnet (int argc, char ** argv) [static]
Definition at line 298 of file lnetctl.c.
References cYAML_free_tree(), cYAML_print_tree2file(), LNET_CONFIGURE, LUSTRE_CFG_RC_NO_ERR, lustre_lnet_config_ni_system(), opt, and print_help().
static int jt_del_net (int argc, char ** argv) [static]
Definition at line 541 of file lnetctl.c.
References cYAML_free_tree(), cYAML_print_tree2file(), LUSTRE_CFG_RC_NO_ERR, lustre_lnet_del_net(), opt, optarg, and print_help().
static int jt_del_route (int argc, char ** argv) [static]
Definition at line 500 of file lnetctl.c.
References cYAML_free_tree(), cYAML_print_tree2file(), LUSTRE_CFG_RC_NO_ERR, lustre_lnet_del_route(), opt, optarg, and print_help().
static int jt_export (int argc, char ** argv) [static]
Definition at line 906 of file lnetctl.c.
References cYAML_free_tree(), cYAML_print_tree2file(), LUSTRE_CFG_RC_NO_ERR, lustre_lnet_show_net(), lustre_lnet_show_route(), lustre_lnet_show_routing(), and opt.
static int jt_import (int argc, char ** argv) [static]
Definition at line 837 of file lnetctl.c.
References cmd, cYAML_free_tree(), cYAML_print_tree(), cYAML_print_tree2file(), LUSTRE_CFG_RC_NO_ERR, lustre_yaml_config(), lustre_yaml_del(), lustre_yaml_show(), and opt.
static int jt_lnet (int argc, char ** argv) [inline, static]
Definition at line 753 of file lnetctl.c.
References CMD_HELP, handle_help(), and Parser_execarg().
static int jt_net (int argc, char ** argv) [inline, static]
Definition at line 777 of file lnetctl.c.
References CMD_HELP, handle_help(), and Parser_execarg().
static int jt_peer_credits (int argc, char ** argv) [inline, static]
Definition at line 813 of file lnetctl.c.
References CMD_HELP, handle_help(), and Parser_execarg().
static int jt_route (int argc, char ** argv) [inline, static]
Definition at line 765 of file lnetctl.c.
References CMD_HELP, handle_help(), and Parser_execarg().
static int jt_routing (int argc, char ** argv) [inline, static]
Definition at line 789 of file lnetctl.c.
References CMD_HELP, handle_help(), and Parser_execarg().
static int jt_set (int argc, char ** argv) [inline, static]
Definition at line 825 of file lnetctl.c.
References CMD_HELP, handle_help(), and Parser_execarg().
static int jt_set_large (int argc, char ** argv) [static]
Definition at line 241 of file lnetctl.c.
References cYAML_build_error(), cYAML_free_tree(), cYAML_print_tree2file(), handle_help(), LUSTRE_CFG_RC_NO_ERR, lustre_lnet_config_buffers(), and parse_long().
static int jt_set_routing (int argc, char ** argv) [static]
Definition at line 268 of file lnetctl.c.
References cYAML_build_error(), cYAML_free_tree(), cYAML_print_tree2file(), handle_help(), LUSTRE_CFG_RC_NO_ERR, lustre_lnet_enable_routing(), and parse_long().
static int jt_set_small (int argc, char ** argv) [static]
Definition at line 214 of file lnetctl.c.
References cYAML_build_error(), cYAML_free_tree(), cYAML_print_tree2file(), handle_help(), LUSTRE_CFG_RC_NO_ERR, lustre_lnet_config_buffers(), and parse_long().
static int jt_set_tiny (int argc, char ** argv) [static]
Definition at line 187 of file lnetctl.c.
References cYAML_build_error(), cYAML_free_tree(), cYAML_print_tree2file(), handle_help(), LUSTRE_CFG_RC_NO_ERR, lustre_lnet_config_buffers(), and parse_long().
static int jt_show_net (int argc, char ** argv) [static]
Definition at line 646 of file lnetctl.c.
References cYAML_free_tree(), cYAML_print_tree(), cYAML_print_tree2file(), LUSTRE_CFG_RC_NO_ERR, lustre_lnet_show_net(), opt, optarg, and print_help().
static int jt_show_peer_credits (int argc, char ** argv) [static]
Definition at line 732 of file lnetctl.c.
References cYAML_free_tree(), cYAML_print_tree(), cYAML_print_tree2file(), handle_help(), LUSTRE_CFG_RC_NO_ERR, and lustre_lnet_show_peer_credits().
static int jt_show_route (int argc, char ** argv) [static]
Definition at line 578 of file lnetctl.c.
References cYAML_free_tree(), cYAML_print_tree(), cYAML_print_tree2file(), LUSTRE_CFG_RC_NO_ERR, lustre_lnet_show_route(), opt, optarg, parse_long(), and print_help().
static int jt_show_routing (int argc, char ** argv) [static]
Definition at line 690 of file lnetctl.c.
References cYAML_free_tree(), cYAML_print_tree(), cYAML_print_tree2file(), handle_help(), LUSTRE_CFG_RC_NO_ERR, and lustre_lnet_show_routing().
static int jt_show_stats (int argc, char ** argv) [static]
Definition at line 711 of file lnetctl.c.
References cYAML_free_tree(), cYAML_print_tree(), cYAML_print_tree2file(), handle_help(), LUSTRE_CFG_RC_NO_ERR, and lustre_lnet_show_stats().
static int jt_stats (int argc, char ** argv) [inline, static]
Definition at line 801 of file lnetctl.c.
References CMD_HELP, handle_help(), and Parser_execarg().
static int jt_unconfig_lnet (int argc, char ** argv) [static]
Definition at line 336 of file lnetctl.c.
References cYAML_free_tree(), cYAML_print_tree2file(), handle_help(), LNET_UNCONFIGURE, LUSTRE_CFG_RC_NO_ERR, and lustre_lnet_config_ni_system().
int main (int argc, char ** argv)
Definition at line 987 of file lnetctl.c.
References cYAML_build_error(), cYAML_print_tree2file(), lustre_lnet_config_lib_init(), Parser_commands(), Parser_execarg(), and Parser_init().
static int parse_long (const char * number, long int * value) [static]
Definition at line 144 of file lnetctl.c.
References end.
Referenced by jt_add_net(), jt_add_route(), jt_set_large(), jt_set_routing(), jt_set_small(), jt_set_tiny(), and jt_show_route().
static void print_help (const command_t cmds[], const char * cmd_type, const char * pc_name) [inline, static]
Definition at line 126 of file lnetctl.c.
References cmd, parser_cmd::pc_help, and parser_cmd::pc_name.
Referenced by handle_help(), jt_add_net(), jt_add_route(), jt_config_lnet(), jt_del_net(), jt_del_route(), jt_show_net(), and jt_show_route().
Variable Documentation
command_t credits_cmds[]
Initial value:
 {
        {"show", jt_show_peer_credits, 0, "show peer credits\n"},
        { 0, 0, 0, NULL }
}
Definition at line 108 of file lnetctl.c.
command_t list[]
Initial value:
 {
        {"lnet", jt_lnet, 0, "lnet {configure | unconfigure} [--all]"},
        {"route", jt_route, 0, "route {add | del | show | help}"},
        {"net", jt_net, 0, "net {add | del | show | help}"},
        {"routing", jt_routing, 0, "routing {show | help}"},
        {"set", jt_set, 0, "set {tiny_buffers | small_buffers | large_buffers"
                           " | routing}"},
        {"import", jt_import, 0, "import {--add | --del | --show | "
                                 "--help} FILE.yaml"},
        {"export", jt_export, 0, "export {--help} FILE.yaml"},
        {"stats", jt_stats, 0, "stats {show | help}"},
        {"peer_credits", jt_peer_credits, 0, "peer_credits {show | help}"},
        {"help", Parser_help, 0, "help"},
        {"exit", Parser_quit, 0, "quit"},
        {"quit", Parser_quit, 0, "quit"},
        { 0, 0, 0, NULL }
}
Definition at line 969 of file lnetctl.c.
Referenced by ct_copy_xattr(), cYAML_ll_free(), expand_strs(), insert_new_clnt(), it_test_init(), it_test_performance(), kgnilnd_conn_seq_seek(), kgnilnd_peer_seq_seek(), kgnilnd_tx_add_state_locked(), ldlm_chain_lock_for_replay(), lfsck_assistant_notify_others(), lfsck_async_interpret_common(), lfsck_stop_notify(), llapi_json_add_item(), llapi_json_destroy_list(), llapi_json_write_list(), llapi_poollist(), lustre_idmap_fini(), osp_invalidate_request(), process_clnt_dir(), qos_add_tgt(), qsd_bump_version(), qsd_upd_schedule(), tgt_cancel_slc_locks(), unlock_zero_regions(), and update_old_clients().
command_t lnet_cmds[]
Initial value:
 {
        {"configure", jt_config_lnet, 0, "configure lnet\n"
         "\t--all: load NI configuration from module parameters\n"},
        {"unconfigure", jt_unconfig_lnet, 0, "unconfigure lnet\n"},
        { 0, 0, 0, NULL }
}
Definition at line 55 of file lnetctl.c.
command_t net_cmds[]
Initial value:
 {
        {"add", jt_add_net, 0, "add a network\n"
         "\t--net: net name (e.g. tcp0)\n"
         "\t--if: physical interface (e.g. eth0)\n"
         "\t--ip2net: specify networks based on IP address patterns\n"
         "\t--peer-timeout: time to wait before declaring a peer dead\n"
         "\t--peer-credits: define the max number of inflight messages\n"
         "\t--peer-buffer-credits: the number of buffer credits per peer\n"
         "\t--credits: Network Interface credits\n"
         "\t--cpt: CPU Partitions configured net uses (e.g. [0,1]\n"},
        {"del", jt_del_net, 0, "delete a network\n"
         "\t--net: net name (e.g. tcp0)\n"},
        {"show", jt_show_net, 0, "show networks\n"
         "\t--net: net name (e.g. tcp0) to filter on\n"
         "\t--verbose: display detailed output per network\n"},
        { 0, 0, 0, NULL }
}
Definition at line 80 of file lnetctl.c.
command_t route_cmds[]
Initial value:
 {
        {"add", jt_add_route, 0, "add a route\n"
         "\t--net: net name (e.g. tcp0)\n"
         "\t--gateway: gateway nid (e.g. 10.1.1.2@tcp)\n"
         "\t--hop: number to final destination (1 < hops < 255)\n"
         "\t--priority: priority of route (0 - highest prio\n"},
        {"del", jt_del_route, 0, "delete a route\n"
         "\t--net: net name (e.g. tcp0)\n"
         "\t--gateway: gateway nid (e.g. 10.1.1.2@tcp)\n"},
        {"show", jt_show_route, 0, "show routes\n"
         "\t--net: net name (e.g. tcp0) to filter on\n"
         "\t--gateway: gateway nid (e.g. 10.1.1.2@tcp) to filter on\n"
         "\t--hop: number to final destination (1 < hops < 255) to filter on\n"
         "\t--priority: priority of route (0 - highest prio to filter on\n"
         "\t--verbose: display detailed output per route\n"},
        { 0, 0, 0, NULL }
}
Definition at line 62 of file lnetctl.c.
command_t routing_cmds[]
Initial value:
 {
        {"show", jt_show_routing, 0, "show routing information\n"},
        { 0, 0, 0, NULL }
}
Definition at line 98 of file lnetctl.c.
command_t set_cmds[]
Initial value:
 {
        {"tiny_buffers", jt_set_tiny, 0, "set tiny routing buffers\n"
         "\tVALUE must be greater than 0\n"},
        {"small_buffers", jt_set_small, 0, "set small routing buffers\n"
         "\tVALUE must be greater than 0\n"},
        {"large_buffers", jt_set_large, 0, "set large routing buffers\n"
         "\tVALUE must be greater than 0\n"},
        {"routing", jt_set_routing, 0, "enable/disable routing\n"
         "\t0 - disable routing\n"
         "\t1 - enable routing\n"},
        { 0, 0, 0, NULL }
}
Definition at line 113 of file lnetctl.c.
command_t stats_cmds[]
Initial value:
 {
        {"show", jt_show_stats, 0, "show LNET statistics\n"},
        { 0, 0, 0, NULL }
}
Definition at line 103 of file lnetctl.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.