Lustre: lnet/lnet/nidstrings.c File Reference
lnet/lnet/nidstrings.c File Reference
#include <libcfs/libcfs.h>
#include <lnet/nidstr.h>
Data Structures
struct nidrange
Nid range list syntax.
struct addrrange
Structure to represent <addrrange> token of the syntax.
Defines
#define DEBUG_SUBSYSTEM S_LNET
#define MAX_NUMERIC_VALUE 0xffffffff
#define IPSTRING_LENGTH 16
Functions
static DEFINE_SPINLOCK (libcfs_nidstring_lock)
static struct netstrfns * libcfs_namenum2netstrfns (const char *name)
char * libcfs_next_nidstring (void)
static int parse_addrange (const struct cfs_lstr *src, struct nidrange *nidrange)
Parses <addrrange> token on the syntax.
static struct nidrange * add_nidrange (const struct cfs_lstr *src, struct list_head *nidlist)
Finds or creates struct nidrange.
static int parse_nidrange (struct cfs_lstr *src, struct list_head *nidlist)
Parses <nidrange> token of the syntax.
static void free_addrranges (struct list_head *list)
Frees addrrange structures of list.
void cfs_free_nidlist (struct list_head *list)
Frees nidrange strutures of list.
int cfs_parse_nidlist (char *str, int len, struct list_head *nidlist)
Parses nid range list.
int cfs_match_nid (lnet_nid_t nid, struct list_head *nidlist)
Matches a nid (nid) against the compiled list of nidranges (nidlist).
static int cfs_print_network (char *buffer, int count, struct nidrange *nr)
Print the network part of the nidrange nr into the specified buffer.
static int cfs_print_addrranges (char *buffer, int count, struct list_head *addrranges, struct nidrange *nr)
Print a list of addrrange (addrranges) into the specified buffer.
int cfs_print_nidlist (char *buffer, int count, struct list_head *nidlist)
Print a list of nidranges (nidlist) into the specified buffer.
static void cfs_ip_ar_min_max (struct addrrange *ar, __u32 *min_nid, __u32 *max_nid)
Determines minimum and maximum addresses for a single numeric address range.
static void cfs_num_ar_min_max (struct addrrange *ar, __u32 *min_nid, __u32 *max_nid)
Determines minimum and maximum addresses for a single numeric address range.
bool cfs_nidrange_is_contiguous (struct list_head *nidlist)
Determines whether an expression list in an nidrange contains exactly one contiguous address range.
static bool cfs_num_is_contiguous (struct list_head *nidlist)
Determines whether an expression list in an num nidrange contains exactly one contiguous address range.
static bool cfs_ip_is_contiguous (struct list_head *nidlist)
Determines whether an expression list in an ip nidrange contains exactly one contiguous address range.
void cfs_nidrange_find_min_max (struct list_head *nidlist, char *min_nid, char *max_nid, size_t nidstr_length)
Takes a linked list of nidrange expressions, determines the minimum and maximum nid and creates appropriate nid structures.
static void cfs_num_min_max (struct list_head *nidlist, __u32 *min_nid, __u32 *max_nid)
Determines the min and max NID values for num LNDs.
static void cfs_ip_min_max (struct list_head *nidlist, __u32 *min_nid, __u32 *max_nid)
Takes an nidlist and determines the minimum and maximum ip addresses.
static int libcfs_lo_str2addr (const char *str, int nob, __u32 *addr)
static void libcfs_ip_addr2str (__u32 addr, char *str, size_t size)
static int libcfs_ip_str2addr (const char *str, int nob, __u32 *addr)
int cfs_ip_addr_parse (char *str, int len, struct list_head *list)
static int libcfs_ip_addr_range_print (char *buffer, int count, struct list_head *list)
int cfs_ip_addr_match (__u32 addr, struct list_head *list)
Matches address (addr) against address set encoded in list.
static void libcfs_decnum_addr2str (__u32 addr, char *str, size_t size)
Print the network part of the nidrange nr into the specified buffer.
static int libcfs_num_str2addr (const char *str, int nob, __u32 *addr)
static int libcfs_num_parse (char *str, int len, struct list_head *list)
Nf_parse_addrlist method for networks using numeric addresses.
static int libcfs_num_addr_range_print (char *buffer, int count, struct list_head *list)
static int libcfs_num_match (__u32 addr, struct list_head *numaddr)
static struct netstrfns * libcfs_lnd2netstrfns (__u32 lnd)
static struct netstrfns * libcfs_name2netstrfns (const char *name)
int libcfs_isknown_lnd (__u32 lnd)
char * libcfs_lnd2modname (__u32 lnd)
int libcfs_str2lnd (const char *str)
char * libcfs_lnd2str_r (__u32 lnd, char *buf, size_t buf_size)
char * libcfs_net2str_r (__u32 net, char *buf, size_t buf_size)
char * libcfs_nid2str_r (lnet_nid_t nid, char *buf, size_t buf_size)
static struct netstrfns * libcfs_str2net_internal (const char *str, __u32 *net)
__u32 libcfs_str2net (const char *str)
lnet_nid_t libcfs_str2nid (const char *str)
char * libcfs_id2str (lnet_process_id_t id)
int libcfs_str2anynid (lnet_nid_t *nidp, const char *str)
Variables
static char libcfs_nidstrings [LNET_NIDSTR_COUNT][LNET_NIDSTR_SIZE]
static int libcfs_nidstring_idx
static struct netstrfns libcfs_netstrfns []
static const size_t libcfs_nnetstrfns = ARRAY_SIZE(libcfs_netstrfns)
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 41 of file nidstrings.c.
#define IPSTRING_LENGTH 16
Definition at line 49 of file nidstrings.c.
Referenced by cfs_nidrange_find_min_max().
#define MAX_NUMERIC_VALUE 0xffffffff
Definition at line 47 of file nidstrings.c.
Referenced by add_nidrange(), and libcfs_num_parse().
Function Documentation
static struct nidrange* add_nidrange (const struct cfs_lstr * src, struct list_head * nidlist) [static, read]
Finds or creates struct nidrange.
Checks if src is a valid network name, looks for corresponding nidrange on the ist of nidranges (nidlist), creates new struct nidrange if it is not found.
Return values:
pointer to struct nidrange matching network specified via src
NULL if src does not match any network
Definition at line 194 of file nidstrings.c.
References cfs_str2num_check(), INIT_LIST_HEAD, LIBCFS_ALLOC, libcfs_namenum2netstrfns(), list_add_tail(), list_for_each_entry, LNET_NIDSTR_SIZE, cfs_lstr::ls_len, cfs_lstr::ls_str, MAX_NUMERIC_VALUE, netstrfns::nf_name, nidrange::nr_addrranges, nidrange::nr_all, nidrange::nr_link, nidrange::nr_netnum, and nidrange::nr_netstrfns.
Referenced by parse_nidrange().
void cfs_free_nidlist (struct list_head * list)
Frees nidrange strutures of list.
For each struct nidrange structure found on list it frees addrrange list attached to it and frees the nidrange itself.
Return values:
none
Definition at line 305 of file nidstrings.c.
References free_addrranges(), LIBCFS_FREE, list_del(), list_entry, list_for_each_safe, list_head::next, nidrange::nr_addrranges, and nidrange::nr_link.
int cfs_ip_addr_match (__u32 addr, struct list_head * list)
Matches address (addr) against address set encoded in list.
Return values:
1 if addr matches
0 otherwise
Definition at line 874 of file nidstrings.c.
int cfs_ip_addr_parse (char * str, int len, struct list_head * list)
Definition at line 815 of file nidstrings.c.
static void cfs_ip_ar_min_max (struct addrrange * ar, __u32 * min_nid, __u32 * max_nid) [static]
Determines minimum and maximum addresses for a single numeric address range.
Parameters:
ar
min_nid
max_nid
Definition at line 468 of file nidstrings.c.
References addrrange::ar_numaddr_ranges, cfs_expr_list::el_exprs, list_for_each_entry, cfs_range_expr::re_hi, cfs_range_expr::re_link, and cfs_range_expr::re_lo.
Referenced by cfs_ip_is_contiguous(), and cfs_ip_min_max().
static bool cfs_ip_is_contiguous (struct list_head * nidlist) [static]
Determines whether an expression list in an ip nidrange contains exactly one contiguous address range.
Parameters:
*nidlist
Return values:
true if contiguous
false if not contiguous
Definition at line 623 of file nidstrings.c.
References addrrange::ar_numaddr_ranges, cfs_ip_ar_min_max(), cfs_expr_list::el_exprs, list_for_each_entry, nidrange::nr_addrranges, cfs_range_expr::re_hi, cfs_range_expr::re_link, cfs_range_expr::re_lo, and cfs_range_expr::re_stride.
static void cfs_ip_min_max (struct list_head * nidlist, __u32 * min_nid, __u32 * max_nid) [static]
Takes an nidlist and determines the minimum and maximum ip addresses.
Parameters:
*nidlist
*min_nid
*max_nid
Definition at line 745 of file nidstrings.c.
References addrrange::ar_link, cfs_ip_ar_min_max(), list_for_each_entry, and nidrange::nr_addrranges.
int cfs_match_nid (lnet_nid_t nid, struct list_head * nidlist)
Matches a nid (nid) against the compiled list of nidranges (nidlist).
See also:
cfs_parse_nidlist()
Return values:
1 on match
0 otherwises
Definition at line 366 of file nidstrings.c.
References addrrange::ar_link, addrrange::ar_numaddr_ranges, list_for_each_entry, LNET_NETNUM(), LNET_NETTYP(), LNET_NIDADDR(), LNET_NIDNET(), netstrfns::nf_match_addr, netstrfns::nf_type, nidrange::nr_addrranges, nidrange::nr_all, nidrange::nr_netnum, and nidrange::nr_netstrfns.
void cfs_nidrange_find_min_max (struct list_head * nidlist, char * min_nid, char * max_nid, size_t nidstr_length)
Takes a linked list of nidrange expressions, determines the minimum and maximum nid and creates appropriate nid structures.
Parameters:
*nidlist
*min_nid
*max_nid
Definition at line 676 of file nidstrings.c.
References IPSTRING_LENGTH, list_for_each_entry, netstrfns::nf_addr2str, netstrfns::nf_min_max, netstrfns::nf_name, nidrange::nr_netnum, and nidrange::nr_netstrfns.
bool cfs_nidrange_is_contiguous (struct list_head * nidlist)
Determines whether an expression list in an nidrange contains exactly one contiguous address range.
Calls the correct netstrfns for the LND
Parameters:
*nidlist
Return values:
true if contiguous
false if not contiguous
Definition at line 539 of file nidstrings.c.
References list_for_each_entry, netstrfns::nf_is_contiguous, netstrfns::nf_name, nidrange::nr_netnum, and nidrange::nr_netstrfns.
static void cfs_num_ar_min_max (struct addrrange * ar, __u32 * min_nid, __u32 * max_nid) [static]
Determines minimum and maximum addresses for a single numeric address range.
Parameters:
ar
min_nid
max_nid
Definition at line 507 of file nidstrings.c.
References addrrange::ar_numaddr_ranges, cfs_expr_list::el_exprs, list_for_each_entry, cfs_range_expr::re_hi, cfs_range_expr::re_link, and cfs_range_expr::re_lo.
Referenced by cfs_num_is_contiguous(), and cfs_num_min_max().
static bool cfs_num_is_contiguous (struct list_head * nidlist) [static]
Determines whether an expression list in an num nidrange contains exactly one contiguous address range.
Parameters:
*nidlist
Return values:
true if contiguous
false if not contiguous
Definition at line 577 of file nidstrings.c.
References addrrange::ar_numaddr_ranges, cfs_num_ar_min_max(), cfs_expr_list::el_exprs, list_for_each_entry, nidrange::nr_addrranges, cfs_range_expr::re_hi, cfs_range_expr::re_link, and cfs_range_expr::re_stride.
static void cfs_num_min_max (struct list_head * nidlist, __u32 * min_nid, __u32 * max_nid) [static]
Determines the min and max NID values for num LNDs.
Parameters:
*nidlist
*min_nid
*max_nid
Definition at line 713 of file nidstrings.c.
References addrrange::ar_link, cfs_num_ar_min_max(), list_for_each_entry, and nidrange::nr_addrranges.
int cfs_parse_nidlist (char * str, int len, struct list_head * nidlist)
Parses nid range list.
Parses with rigorous syntax and overflow checking str into <nidrange> [ ' ' <nidrange> ], compiles str into set of structures and links that structure to nidlist. The resulting list can be used to match a NID againts set of NIDS defined by str.
See also:
cfs_match_nid
Return values:
1 on success
0 otherwise
Definition at line 333 of file nidstrings.c.
References cfs_free_nidlist(), cfs_gettok(), INIT_LIST_HEAD, cfs_lstr::ls_len, cfs_lstr::ls_str, and parse_nidrange().
static int cfs_print_addrranges (char * buffer, int count, struct list_head * addrranges, struct nidrange * nr) [static]
Print a list of addrrange (addrranges) into the specified buffer.
At max count characters can be printed into buffer.
Return values:
number of characters written
Definition at line 411 of file nidstrings.c.
References addrrange::ar_numaddr_ranges, cfs_print_network(), list_for_each_entry, netstrfns::nf_print_addrlist, and nidrange::nr_netstrfns.
Referenced by cfs_print_nidlist().
static int cfs_print_network (char * buffer, int count, struct nidrange * nr) [static]
Print the network part of the nidrange nr into the specified buffer.
Return values:
number of characters written
Definition at line 393 of file nidstrings.c.
References netstrfns::nf_name, nidrange::nr_netnum, and nidrange::nr_netstrfns.
Referenced by cfs_print_addrranges(), and cfs_print_nidlist().
int cfs_print_nidlist (char * buffer, int count, struct list_head * nidlist)
Print a list of nidranges (nidlist) into the specified buffer.
At max count characters can be printed into buffer. Nidranges are separated by a space character.
Return values:
number of characters written
Definition at line 435 of file nidstrings.c.
References cfs_print_addrranges(), cfs_print_network(), LASSERT, list_empty(), list_for_each_entry, nidrange::nr_addrranges, nidrange::nr_all, and nidrange::nr_link.
static DEFINE_SPINLOCK (libcfs_nidstring_lock) [static]
static void free_addrranges (struct list_head * list) [static]
Frees addrrange structures of list.
For each struct addrrange structure found on list it frees cfs_expr_list list attached to it and frees the addrrange itself.
Return values:
none
Definition at line 283 of file nidstrings.c.
References addrrange::ar_link, addrrange::ar_numaddr_ranges, cfs_expr_list_free_list(), LIBCFS_FREE, list_del(), list_empty(), list_entry, and list_head::next.
Referenced by cfs_free_nidlist().
static void libcfs_decnum_addr2str (__u32 addr, char * str, size_t size) [static]
Print the network part of the nidrange nr into the specified buffer.
Return values:
number of characters written
Definition at line 895 of file nidstrings.c.
char* libcfs_id2str (lnet_process_id_t id)
Definition at line 1236 of file nidstrings.c.
References libcfs_next_nidstring(), libcfs_nid2str(), LNET_NIDSTR_SIZE, LNET_PID_ANY, and LNET_PID_USERFLAG.
static void libcfs_ip_addr2str (__u32 addr, char * str, size_t size) [static]
Definition at line 780 of file nidstrings.c.
static int libcfs_ip_addr_range_print (char * buffer, int count, struct list_head * list) [static]
Definition at line 853 of file nidstrings.c.
References cfs_expr_list_print(), cfs_expr_list::el_link, LASSERT, and list_for_each_entry.
static int libcfs_ip_str2addr (const char * str, int nob, __u32 * addr) [static]
Definition at line 794 of file nidstrings.c.
int libcfs_isknown_lnd (__u32 lnd)
Definition at line 1065 of file nidstrings.c.
References libcfs_lnd2netstrfns().
char* libcfs_lnd2modname (__u32 lnd)
Definition at line 1072 of file nidstrings.c.
References libcfs_lnd2netstrfns(), and netstrfns::nf_modname.
static struct netstrfns* libcfs_lnd2netstrfns (__u32 lnd) [static, read]
Definition at line 1027 of file nidstrings.c.
References libcfs_nnetstrfns, and netstrfns::nf_type.
Referenced by libcfs_isknown_lnd(), libcfs_lnd2modname(), libcfs_lnd2str_r(), libcfs_net2str_r(), libcfs_nid2str_r(), and libcfs_str2nid().
char* libcfs_lnd2str_r (__u32 lnd, char * buf, size_t buf_size)
Definition at line 1093 of file nidstrings.c.
References libcfs_lnd2netstrfns(), and netstrfns::nf_name.
static int libcfs_lo_str2addr (const char * str, int nob, __u32 * addr) [static]
Definition at line 773 of file nidstrings.c.
static struct netstrfns* libcfs_name2netstrfns (const char * name) [static, read]
Definition at line 1053 of file nidstrings.c.
References libcfs_nnetstrfns, and netstrfns::nf_name.
Referenced by libcfs_str2lnd().
static struct netstrfns * libcfs_namenum2netstrfns (const char * name) [static, read]
Definition at line 1039 of file nidstrings.c.
References libcfs_nnetstrfns, and netstrfns::nf_name.
Referenced by add_nidrange().
char* libcfs_net2str_r (__u32 net, char * buf, size_t buf_size)
Definition at line 1108 of file nidstrings.c.
References libcfs_lnd2netstrfns(), LNET_NETNUM(), LNET_NETTYP(), and netstrfns::nf_name.
char* libcfs_next_nidstring (void)
Definition at line 71 of file nidstrings.c.
References ARRAY_SIZE, libcfs_nidstring_idx, and libcfs_nidstrings.
char* libcfs_nid2str_r (lnet_nid_t nid, char * buf, size_t buf_size)
Definition at line 1127 of file nidstrings.c.
References libcfs_lnd2netstrfns(), LNET_NETNUM(), LNET_NETTYP(), LNET_NID_ANY, LNET_NIDADDR(), LNET_NIDNET(), netstrfns::nf_addr2str, and netstrfns::nf_name.
static int libcfs_num_addr_range_print (char * buffer, int count, struct list_head * list) [static]
Definition at line 942 of file nidstrings.c.
References cfs_expr_list_print(), cfs_expr_list::el_link, LASSERT, and list_for_each_entry.
static int libcfs_num_match (__u32 addr, struct list_head * numaddr) [static]
Definition at line 961 of file nidstrings.c.
References cfs_expr_list_match(), cfs_expr_list::el_link, LASSERT, list_empty(), list_entry, and list_head::next.
static int libcfs_num_parse (char * str, int len, struct list_head * list) [static]
Nf_parse_addrlist method for networks using numeric addresses.
Examples of such networks are gm and elan.
Return values:
0 if str parsed to numeric address
errno otherwise
Definition at line 929 of file nidstrings.c.
References cfs_expr_list_parse(), cfs_expr_list::el_link, list_add_tail(), and MAX_NUMERIC_VALUE.
static int libcfs_num_str2addr (const char * str, int nob, __u32 * addr) [static]
Definition at line 901 of file nidstrings.c.
int libcfs_str2anynid (lnet_nid_t * nidp, const char * str)
Definition at line 1254 of file nidstrings.c.
References libcfs_str2nid(), and LNET_NID_ANY.
int libcfs_str2lnd (const char * str)
Definition at line 1081 of file nidstrings.c.
References libcfs_name2netstrfns(), and netstrfns::nf_type.
__u32 libcfs_str2net (const char * str)
Definition at line 1198 of file nidstrings.c.
References libcfs_str2net_internal(), LNET_NID_ANY, and LNET_NIDNET().
static struct netstrfns* libcfs_str2net_internal (const char * str, __u32 * net) [static, read]
Definition at line 1162 of file nidstrings.c.
References libcfs_nnetstrfns, LNET_MKNET(), LOLND, netstrfns::nf_name, and netstrfns::nf_type.
Referenced by libcfs_str2net(), and libcfs_str2nid().
lnet_nid_t libcfs_str2nid (const char * str)
Definition at line 1210 of file nidstrings.c.
References LASSERT, libcfs_lnd2netstrfns(), libcfs_str2net_internal(), LNET_MKNET(), LNET_MKNID(), LNET_NID_ANY, netstrfns::nf_str2addr, and SOCKLND.
static int parse_addrange (const struct cfs_lstr * src, struct nidrange * nidrange) [static]
Parses <addrrange> token on the syntax.
Allocates struct addrrange and links to nidrange via (nidrange::nr_addrranges)
Return values:
0 if src parses to '*' | <ipaddr_range> | <cfs_expr_list>
-errno otherwise
Definition at line 163 of file nidstrings.c.
References addrrange::ar_link, addrrange::ar_numaddr_ranges, INIT_LIST_HEAD, LIBCFS_ALLOC, list_add_tail(), cfs_lstr::ls_len, cfs_lstr::ls_str, netstrfns::nf_parse_addrlist, nidrange::nr_addrranges, nidrange::nr_all, and nidrange::nr_netstrfns.
Referenced by parse_nidrange().
static int parse_nidrange (struct cfs_lstr * src, struct list_head * nidlist) [static]
Parses <nidrange> token of the syntax.
Return values:
1 if src parses to <addrrange> '@' <net>
0 otherwise
Definition at line 248 of file nidstrings.c.
References add_nidrange(), cfs_gettok(), cfs_lstr::ls_str, and parse_addrange().
Referenced by cfs_parse_nidlist().
Variable Documentation
struct netstrfns libcfs_netstrfns[] [static]
Definition at line 971 of file nidstrings.c.
int libcfs_nidstring_idx [static]
Definition at line 64 of file nidstrings.c.
Referenced by libcfs_next_nidstring().
char libcfs_nidstrings[LNET_NIDSTR_COUNT][LNET_NIDSTR_SIZE] [static]
Definition at line 63 of file nidstrings.c.
Referenced by libcfs_next_nidstring().
const size_t libcfs_nnetstrfns = ARRAY_SIZE(libcfs_netstrfns) [static]
Definition at line 1024 of file nidstrings.c.
Referenced by libcfs_lnd2netstrfns(), libcfs_name2netstrfns(), libcfs_namenum2netstrfns(), and libcfs_str2net_internal().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.