Lustre: lnet/lnet/lo.c File Reference
lnet/lnet/lo.c File Reference
#include <lnet/lib-lnet.h>
Defines
#define DEBUG_SUBSYSTEM S_LNET
Functions
static int lolnd_send (lnet_ni_t *ni, void *private, lnet_msg_t *lntmsg)
static int lolnd_recv (lnet_ni_t *ni, void *private, lnet_msg_t *lntmsg, int delayed, unsigned int niov, struct kvec *iov, lnet_kiov_t *kiov, unsigned int offset, unsigned int mlen, unsigned int rlen)
static void lolnd_shutdown (lnet_ni_t *ni)
static int lolnd_startup (lnet_ni_t *ni)
Variables
static int lolnd_instanced
lnd_t the_lolnd
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 35 of file lo.c.
Function Documentation
static int lolnd_recv (lnet_ni_t * ni, void * private, lnet_msg_t * lntmsg, int delayed, unsigned int niov, struct kvec * iov, lnet_kiov_t * kiov, unsigned int offset, unsigned int mlen, unsigned int rlen) [static]
Definition at line 48 of file lo.c.
References lnet_copy_iov2iov(), lnet_copy_iov2kiov(), lnet_copy_kiov2iov(), lnet_copy_kiov2kiov(), lnet_finalize(), lnet_msg::msg_iov, lnet_msg::msg_kiov, lnet_msg::msg_niov, and lnet_msg::msg_offset.
static int lolnd_send (lnet_ni_t * ni, void * private, lnet_msg_t * lntmsg) [static]
Definition at line 39 of file lo.c.
References LASSERT, lnet_parse(), lnet_msg::msg_hdr, lnet_msg::msg_routing, lnet_msg::msg_target_is_router, and lnet_ni::ni_nid.
static void lolnd_shutdown (lnet_ni_t * ni) [static]
Definition at line 90 of file lo.c.
References CDEBUG, D_NET, LASSERT, and lolnd_instanced.
static int lolnd_startup (lnet_ni_t * ni) [static]
Definition at line 99 of file lo.c.
References LASSERT, lolnd_instanced, lnet_ni::ni_lnd, and the_lolnd.
Variable Documentation
int lolnd_instanced [static]
Definition at line 87 of file lo.c.
Referenced by lolnd_shutdown(), and lolnd_startup().
lnd_t the_lolnd
Initial value:
 {
         {&the_lolnd.lnd_list, &the_lolnd.lnd_list},
         0,
         LOLND,
         lolnd_startup,
         lolnd_shutdown,
         NULL,
         lolnd_send,
         lolnd_recv,
         NULL,
         NULL,
         NULL
}
Definition at line 108 of file lo.c.
Referenced by lnet_lib_init(), and lolnd_startup().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.