Lustre: lustre/obdclass/local_storage.h File Reference
lustre/obdclass/local_storage.h File Reference
#include <dt_object.h>
#include <obd.h>
#include <lustre_fid.h>
#include <lustre_disk.h>
Data Structures
struct ls_device
struct ls_object
struct los_ondisk
Defines
#define LOS_MAGIC 0xdecafbee
Enumerations
enum los_object_role { LOS_PARENT, LOS_CHILD }
Used in __local_file_create() for object lock role.
Functions
static struct ls_device * dt2ls_dev (struct dt_device *d)
static struct ls_object * lu2ls_obj (struct lu_object *o)
static struct dt_object * ls_locate (const struct lu_env *env, struct ls_device *ls, const struct lu_fid *fid, const struct lu_object_conf *conf)
struct ls_device * ls_device_get (struct dt_device *dev)
void ls_device_put (const struct lu_env *env, struct ls_device *ls)
struct local_oid_storage * dt_los_find (struct ls_device *ls, __u64 seq)
void dt_los_put (struct local_oid_storage *los)
Define Documentation
#define LOS_MAGIC 0xdecafbee
Definition at line 92 of file local_storage.h.
Referenced by lastid_compat_check().
Enumeration Type Documentation
enum los_object_role
Used in __local_file_create() for object lock role.
Enumerator:
LOS_PARENT
LOS_CHILD
Definition at line 97 of file local_storage.h.
Function Documentation
static struct ls_device* dt2ls_dev (struct dt_device * d) [static, read]
Definition at line 53 of file local_storage.h.
References ls_device::ls_top_dev.
Referenced by local_file_find_or_create(), local_index_find_or_create(), and local_oid_storage_fini().
struct local_oid_storage* dt_los_find (struct ls_device * ls, __u64 seq) [read]
Definition at line 689 of file local_storage.c.
References list_for_each_entry, local_oid_storage::los_list, local_oid_storage::los_refcount, local_oid_storage::los_seq, ls_device::ls_los_list, and ret.
Referenced by llog_osd_open(), and local_oid_storage_init().
void dt_los_put (struct local_oid_storage * los)
Definition at line 703 of file local_storage.c.
References LBUG, and local_oid_storage::los_refcount.
Referenced by llog_osd_close(), and llog_osd_open().
struct ls_device* ls_device_get (struct dt_device * dev) [read]
Definition at line 142 of file local_storage.c.
References __ls_find_dev(), dt_device::dd_lu_dev, ENTRY, GOTO, INIT_LIST_HEAD, LASSERT, lu_device::ld_ops, lu_device::ld_site, list_add(), ls_device::ls_linkage, ls_device::ls_los_list, ls_device::ls_los_mutex, ls_device::ls_osd, ls_device::ls_refcount, ls_device::ls_top_dev, lu_device_init(), OBD_ALLOC_PTR, and RETURN.
Referenced by llog_osd_open(), local_file_find_or_create_with_fid(), local_index_find_or_create_with_fid(), and local_oid_storage_init().
void ls_device_put (const struct lu_env * env, struct ls_device * ls)
Definition at line 176 of file local_storage.c.
References dt_device::dd_lu_dev, LASSERT, lu_device::ld_site, list_del(), list_empty(), ls_device::ls_linkage, ls_device::ls_los_list, ls_device::ls_refcount, ls_device::ls_top_dev, lu_device_fini(), lu_site_purge(), and OBD_FREE_PTR.
Referenced by llog_osd_open(), local_file_find_or_create_with_fid(), local_index_find_or_create_with_fid(), local_oid_storage_fini(), and local_oid_storage_init().
static struct dt_object* ls_locate (const struct lu_env * env, struct ls_device * ls, const struct lu_fid * fid, const struct lu_object_conf * conf) [static, read]
Definition at line 68 of file local_storage.h.
References dt_device::dd_lu_dev, dt_locate_at(), ls_device::ls_osd, and ls_device::ls_top_dev.
Referenced by __local_file_create(), lastid_compat_check(), llog_osd_open(), local_file_find_or_create(), local_index_find_or_create(), and local_oid_storage_init().
static struct ls_object* lu2ls_obj (struct lu_object * o) [static, read]
Definition at line 63 of file local_storage.h.
References dt_object::do_lu, and ls_object::ls_obj.
Referenced by ls_object_free().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.