Lustre: lustre/obdclass/local_storage.c File Reference
lustre/obdclass/local_storage.c File Reference
#include "local_storage.h"
Defines
#define DEBUG_SUBSYSTEM S_CLASS
Functions
static DEFINE_MUTEX (ls_list_mutex)
static int ls_object_init (const struct lu_env *env, struct lu_object *o, const struct lu_object_conf *unused)
static void ls_object_free (const struct lu_env *env, struct lu_object *o)
static struct lu_object * ls_object_alloc (const struct lu_env *env, const struct lu_object_header *_h, struct lu_device *d)
static struct ls_device * __ls_find_dev (struct dt_device *dev)
struct ls_device * ls_find_dev (struct dt_device *dev)
struct ls_device * ls_device_get (struct dt_device *dev)
void ls_device_put (const struct lu_env *env, struct ls_device *ls)
int local_object_fid_generate (const struct lu_env *env, struct local_oid_storage *los, struct lu_fid *fid)
local file fid generation
int local_object_declare_create (const struct lu_env *env, struct local_oid_storage *los, struct dt_object *o, struct lu_attr *attr, struct dt_object_format *dof, struct thandle *th)
int local_object_create (const struct lu_env *env, struct local_oid_storage *los, struct dt_object *o, struct lu_attr *attr, struct dt_object_format *dof, struct thandle *th)
static struct dt_object * __local_file_create (const struct lu_env *env, const struct lu_fid *fid, struct local_oid_storage *los, struct ls_device *ls, struct dt_object *parent, const char *name, struct lu_attr *attr, struct dt_object_format *dof)
struct dt_object * local_file_find_or_create (const struct lu_env *env, struct local_oid_storage *los, struct dt_object *parent, const char *name, __u32 mode)
struct dt_object * local_file_find_or_create_with_fid (const struct lu_env *env, struct dt_device *dt, const struct lu_fid *fid, struct dt_object *parent, const char *name, __u32 mode)
struct dt_object * local_index_find_or_create (const struct lu_env *env, struct local_oid_storage *los, struct dt_object *parent, const char *name, __u32 mode, const struct dt_index_features *ft)
struct dt_object * local_index_find_or_create_with_fid (const struct lu_env *env, struct dt_device *dt, const struct lu_fid *fid, struct dt_object *parent, const char *name, __u32 mode, const struct dt_index_features *ft)
static int local_object_declare_unlink (const struct lu_env *env, struct dt_device *dt, struct dt_object *p, struct dt_object *c, const char *name, struct thandle *th)
int local_object_unlink (const struct lu_env *env, struct dt_device *dt, struct dt_object *parent, const char *name)
struct local_oid_storage * dt_los_find (struct ls_device *ls, __u64 seq)
void dt_los_put (struct local_oid_storage *los)
static int lastid_compat_check (const struct lu_env *env, struct dt_device *dev, __u64 lastid_seq, __u32 *first_oid, struct ls_device *ls)
int local_oid_storage_init (const struct lu_env *env, struct dt_device *dev, const struct lu_fid *first_fid, struct local_oid_storage **los)
Initialize local OID storage for required sequence.
void local_oid_storage_fini (const struct lu_env *env, struct local_oid_storage *los)
Variables
static struct list_head ls_list_head = LIST_HEAD_INIT(ls_list_head)
static struct lu_object_operations ls_lu_obj_ops
static struct lu_device_operations ls_lu_dev_ops
static struct
lu_device_type_operations ls_device_type_ops
static struct lu_device_type ls_lu_type
Define Documentation
#define DEBUG_SUBSYSTEM S_CLASS
Definition at line 33 of file local_storage.c.
Function Documentation
static struct dt_object* __local_file_create (const struct lu_env * env, const struct lu_fid * fid, struct local_oid_storage * los, struct ls_device * ls, struct dt_object * parent, const char * name, struct lu_attr * attr, struct dt_object_format * dof) [static, read]
Definition at line 294 of file local_storage.c.
References CDEBUG, D_OTHER, DFID, DFT_DIR, dt_object::do_lu, dt_object_format::dof_type, dt_declare_insert(), dt_declare_ref_add(), dt_destroy(), dt_info(), dt_insert(), dt_key, dt_object_exists(), dt_ref_add(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_try_as_dir(), dt_write_lock(), dt_write_unlock(), dt_thread_info::dti_conf, dt_thread_info::dti_dof, dt_thread_info::dti_dt_rec, GOTO, lu_attr::la_mode, LASSERT, lu_object::lo_header, LOC_F_NEW, lu_object_conf::loc_flags, local_object_create(), local_object_declare_create(), lu_object_header::loh_attr, LOS_CHILD, LOS_PARENT, ls_locate(), ls_device::ls_osd, lu_object_fid(), lu_object_put_nocache(), PFID, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, RETURN, and unlikely.
Referenced by local_file_find_or_create(), local_file_find_or_create_with_fid(), local_index_find_or_create(), and local_index_find_or_create_with_fid().
static struct ls_device* __ls_find_dev (struct dt_device * dev) [static, read]
Definition at line 107 of file local_storage.c.
References list_for_each_entry, ls_device::ls_linkage, ls_device::ls_osd, ls_device::ls_refcount, and ret.
Referenced by ls_device_get(), and ls_find_dev().
static DEFINE_MUTEX (ls_list_mutex) [static]
struct local_oid_storage* dt_los_find (struct ls_device * ls, __u64 seq) [read]
Definition at line 689 of file local_storage.c.
References list_for_each_entry, local_oid_storage::los_list, local_oid_storage::los_refcount, local_oid_storage::los_seq, ls_device::ls_los_list, and ret.
Referenced by llog_osd_open(), and local_oid_storage_init().
void dt_los_put (struct local_oid_storage * los)
Definition at line 703 of file local_storage.c.
References LBUG, and local_oid_storage::los_refcount.
Referenced by llog_osd_close(), and llog_osd_open().
static int lastid_compat_check (const struct lu_env * env, struct dt_device * dev, __u64 lastid_seq, __u32 * first_oid, struct ls_device * ls) [static]
Definition at line 715 of file local_storage.c.
References CDEBUG, CERROR, D_INFO, dt_object::do_lu, dt_info(), dt_lookup_dir(), dt_object_exists(), dt_read_lock(), dt_read_unlock(), dt_record_read(), dt_root_get(), dt_thread_info::dti_buf, dt_thread_info::dti_fid, dt_thread_info::dti_lb, dt_thread_info::dti_off, lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, FID_SEQ_LLOG, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lu_device::ld_obd, le32_to_cpu, lu_object::lo_dev, LOS_MAGIC, LPX64, ls_locate(), los_ondisk::lso_magic, los_ondisk::lso_next_oid, lu_object_put_nocache(), and obd_device::obd_name.
Referenced by local_oid_storage_init().
static int local_object_declare_unlink (const struct lu_env * env, struct dt_device * dt, struct dt_object * p, struct dt_object * c, const char * name, struct thandle * th) [static]
Definition at line 611 of file local_storage.c.
References dt_declare_delete(), dt_declare_destroy(), dt_declare_ref_del(), and dt_key.
Referenced by local_object_unlink().
struct ls_device* ls_device_get (struct dt_device * dev) [read]
Definition at line 142 of file local_storage.c.
References __ls_find_dev(), dt_device::dd_lu_dev, ENTRY, GOTO, INIT_LIST_HEAD, LASSERT, lu_device::ld_ops, lu_device::ld_site, list_add(), ls_device::ls_linkage, ls_device::ls_los_list, ls_device::ls_los_mutex, ls_device::ls_osd, ls_device::ls_refcount, ls_device::ls_top_dev, lu_device_init(), OBD_ALLOC_PTR, and RETURN.
Referenced by llog_osd_open(), local_file_find_or_create_with_fid(), local_index_find_or_create_with_fid(), and local_oid_storage_init().
void ls_device_put (const struct lu_env * env, struct ls_device * ls)
Definition at line 176 of file local_storage.c.
References dt_device::dd_lu_dev, LASSERT, lu_device::ld_site, list_del(), list_empty(), ls_device::ls_linkage, ls_device::ls_los_list, ls_device::ls_refcount, ls_device::ls_top_dev, lu_device_fini(), lu_site_purge(), and OBD_FREE_PTR.
Referenced by llog_osd_open(), local_file_find_or_create_with_fid(), local_index_find_or_create_with_fid(), local_oid_storage_fini(), and local_oid_storage_init().
struct ls_device* ls_find_dev (struct dt_device * dev) [read]
Definition at line 121 of file local_storage.c.
References __ls_find_dev().
static struct lu_object* ls_object_alloc (const struct lu_env * env, const struct lu_object_header * _h, struct lu_device * d) [static, read]
Definition at line 76 of file local_storage.c.
References dt_object::do_lu, dt_object_init(), LASSERT, lu_object::lo_ops, ls_object::ls_header, ls_object::ls_obj, lu_object_add_top(), lu_object_header_init(), and OBD_ALLOC_PTR.
static void ls_object_free (const struct lu_env * env, struct lu_object * o) [static]
Definition at line 61 of file local_storage.c.
References dt_object_fini(), lu_object::lo_header, ls_object::ls_obj, lu2ls_obj(), lu_object_header_fini(), and OBD_FREE_PTR.
static int ls_object_init (const struct lu_env * env, struct lu_object * o, const struct lu_object_conf * unused) [static]
Definition at line 41 of file local_storage.c.
References dt_device::dd_lu_dev, ENTRY, lu_device::ld_ops, lu_device_operations::ldo_object_alloc, lu_object::lo_dev, lu_object::lo_header, ls_device::ls_osd, lu_object_add(), and RETURN.
Variable Documentation
struct lu_device_type_operations ls_device_type_ops [static]
Initial value:
 {
        .ldto_start = NULL,
        .ldto_stop  = NULL,
}
Definition at line 132 of file local_storage.c.
struct list_head ls_list_head = LIST_HEAD_INIT(ls_list_head) [static]
Definition at line 38 of file local_storage.c.
struct lu_device_operations ls_lu_dev_ops [static]
Initial value:
 {
        .ldo_object_alloc =     ls_object_alloc
}
Definition at line 103 of file local_storage.c.
struct lu_object_operations ls_lu_obj_ops [static]
Initial value:
 {
        .loo_object_init  = ls_object_init,
        .loo_object_free  = ls_object_free,
}
Definition at line 71 of file local_storage.c.
struct lu_device_type ls_lu_type [static]
Initial value:
 {
        .ldt_name = "local_storage",
        .ldt_ops  = &ls_device_type_ops,
}
Definition at line 137 of file local_storage.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.