Lustre: lustre/lod/lod_dev.c File Reference
lustre/lod/lod_dev.c File Reference
#include <linux/kthread.h>
#include <obd_class.h>
#include <md_object.h>
#include <lustre_fid.h>
#include <lustre_param.h>
#include <lustre_update.h>
#include <lustre_log.h>
#include "lod_internal.h"
Data Structures
struct lod_recovery_data
Defines
#define DEBUG_SUBSYSTEM S_MDS
The Logical Object Device (LOD) layer manages access to striped objects (both regular files and directories).
Functions
int lod_fld_lookup (const struct lu_env *env, struct lod_device *lod, const struct lu_fid *fid, __u32 *tgt, int *type)
static struct lu_device * lod_device_fini (const struct lu_env *env, struct lu_device *d)
Implementation of lu_device_type_operations::ldto_device_fini() for LOD.
static struct lu_object * lod_object_alloc (const struct lu_env *env, const struct lu_object_header *hdr, struct lu_device *dev)
Implementation of lu_device_operations::ldo_object_alloc() for LOD.
static int lod_sub_process_config (const struct lu_env *env, struct lod_device *lod, struct lod_tgt_descs *ltd, struct lustre_cfg *lcfg)
Process the config log for all sub device.
static int lod_process_recovery_updates (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *rec, void *data)
process update recovery record
static int lod_sub_recovery_thread (void *arg)
recovery thread for update log
void lod_sub_fini_llog (const struct lu_env *env, struct dt_device *dt, struct ptlrpc_thread *thread)
finish sub llog context
int lodname2mdt_index (char *lodname, __u32 *mdt_index)
Extract MDT target index from a device name.
int lod_sub_init_llog (const struct lu_env *env, struct lod_device *lod, struct dt_device *dt)
Init sub llog context.
static void lod_sub_stop_recovery_threads (const struct lu_env *env, struct lod_device *lod)
Stop sub recovery thread.
static void lod_sub_fini_all_llogs (const struct lu_env *env, struct lod_device *lod)
finish all sub llog
static int lod_prepare_distribute_txn (const struct lu_env *env, struct lod_device *lod)
Prepare distribute txn.
static void lod_fini_distribute_txn (const struct lu_env *env, struct lod_device *lod)
Finish distribute txn.
static int lod_process_config (const struct lu_env *env, struct lu_device *dev, struct lustre_cfg *lcfg)
Implementation of lu_device_operations::ldo_process_config() for LOD.
static int lod_recovery_complete (const struct lu_env *env, struct lu_device *dev)
Implementation of lu_device_operations::ldo_recovery_complete() for LOD.
static int lod_sub_init_llogs (const struct lu_env *env, struct lod_device *lod)
Init update logs on all sub device.
static int lod_prepare (const struct lu_env *env, struct lu_device *pdev, struct lu_device *cdev)
Implementation of lu_device_operations::ldo_prepare() for LOD.
static int lod_root_get (const struct lu_env *env, struct dt_device *dev, struct lu_fid *f)
Implementation of dt_device_operations::dt_root_get() for LOD.
static int lod_statfs (const struct lu_env *env, struct dt_device *dev, struct obd_statfs *sfs)
Implementation of dt_device_operations::dt_statfs() for LOD.
static struct thandle * lod_trans_create (const struct lu_env *env, struct dt_device *dt)
Implementation of dt_device_operations::dt_trans_create() for LOD.
static int lod_trans_start (const struct lu_env *env, struct dt_device *dt, struct thandle *th)
Implementation of dt_device_operations::dt_trans_start() for LOD.
static int lod_trans_cb_add (struct thandle *th, struct dt_txn_commit_cb *dcb)
static int lod_add_noop_records (const struct lu_env *env, struct dt_device *dt, struct thandle *th, int count)
add noop update to the update records
static int lod_trans_stop (const struct lu_env *env, struct dt_device *dt, struct thandle *th)
Implementation of dt_device_operations::dt_trans_stop() for LOD.
static void lod_conf_get (const struct lu_env *env, const struct dt_device *dev, struct dt_device_param *param)
Implementation of dt_device_operations::dt_conf_get() for LOD.
static int lod_sync (const struct lu_env *env, struct dt_device *dev)
Implementation of dt_device_operations::dt_sync() for LOD.
static int lod_ro (const struct lu_env *env, struct dt_device *dev)
Implementation of dt_device_operations::dt_ro() for LOD.
static int lod_commit_async (const struct lu_env *env, struct dt_device *dev)
Implementation of dt_device_operations::dt_commit_async() for LOD.
static int lod_connect_to_osd (const struct lu_env *env, struct lod_device *lod, struct lustre_cfg *cfg)
Connect to a local OSD.
static int lod_tgt_desc_init (struct lod_tgt_descs *ltd)
Allocate and initialize target table.
static int lod_init0 (const struct lu_env *env, struct lod_device *lod, struct lu_device_type *ldt, struct lustre_cfg *cfg)
Initialize LOD device at setup.
static struct lu_device * lod_device_free (const struct lu_env *env, struct lu_device *lu)
Implementation of lu_device_type_operations::ldto_device_free() for LOD.
static struct lu_device * lod_device_alloc (const struct lu_env *env, struct lu_device_type *type, struct lustre_cfg *lcfg)
Implementation of lu_device_type_operations::ldto_device_alloc() for LOD.
static int lod_obd_connect (const struct lu_env *env, struct obd_export **exp, struct obd_device *obd, struct obd_uuid *cluuid, struct obd_connect_data *data, void *localdata)
Implementation of obd_ops::o_connect() for LOD.
static int lod_obd_disconnect (struct obd_export *exp)
Implementation of obd_ops::o_disconnect() for LOD.
LU_KEY_INIT (lod, struct lod_thread_info)
static void lod_key_fini (const struct lu_context *ctx, struct lu_context_key *key, void *data)
LU_CONTEXT_KEY_DEFINE (lod, LCT_MD_THREAD)
LU_TYPE_INIT_FINI (lod,&lod_thread_key)
static int lod_obd_get_info (const struct lu_env *env, struct obd_export *exp, __u32 keylen, void *key, __u32 *vallen, void *val)
Implementation of obd_ops::o_get_info() for LOD.
static int lod_obd_set_info_async (const struct lu_env *env, struct obd_export *exp, __u32 keylen, void *key, __u32 vallen, void *val, struct ptlrpc_request_set *set)
static int __init lod_init (void)
static void __exit lod_exit (void)
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Logical Object Device ("LUSTRE_LOD_NAME")")
MODULE_VERSION (LUSTRE_VERSION_STRING)
MODULE_LICENSE ("GPL")
module_init (lod_init)
module_exit (lod_exit)
Variables
static const char lod_update_log_name [] = "update_log"
static const char lod_update_log_dir_name [] = "update_log_dir"
struct kmem_cache * lod_object_kmem
struct kmem_cache * lod_txn_callback_kmem
static struct lu_kmem_descr lod_caches []
struct lu_device_operations lod_lu_ops
static struct dt_device_operations lod_dt_ops
static struct
lu_device_type_operations lod_device_type_ops
static struct lu_device_type lod_device_type
static struct obd_ops lod_obd_device_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
The Logical Object Device (LOD) layer manages access to striped objects (both regular files and directories).
It implements the DT device and object APIs and is responsible for creating, storing, and loading striping information as an extended attribute of the underlying OSD object. LOD is the server side analog of the LOV and LMV layers on the client side.
Metadata LU object stack (layers of the same compound LU object, all have the same FID):
MDT | MD API MDD | DT API LOD / \ DT API OSD OSP
During LOD object initialization the localness or remoteness of the object FID dictates the choice between OSD and OSP.
An LOD object (file or directory) with N stripes (each has a different FID):
LOD | +---+---+---+...+ | | | | | S0 S1 S2 S3 S(N-1) OS[DP] objects, seen as DT objects by LOD
When upper layers must access an object's stripes (which are themselves OST or MDT LU objects) LOD finds these objects by their FIDs and stores them as an array of DT object pointers on the object. Declarations and operations on LOD objects are received by LOD (as DT object operations) and performed on the underlying OS[DP] object and (as needed) on the stripes. From the perspective of LOD, a stripe-less file (created by mknod() or open with O_LOV_DELAY_CREATE) is an object which does not yet have stripes, while a non-striped directory (created by mkdir()) is an object which will never have stripes.
The LOD layer also implements a small subset of the OBD device API to support MDT stack initialization and finalization (an MDD device connects and disconnects itself to and from the underlying LOD device), and pool management. In turn LOD uses the OBD device API to connect it self to the underlying OSD, and to connect itself to OSP devices representing the MDTs and OSTs that bear the stripes of its objects.
Definition at line 90 of file lod_dev.c.
Function Documentation
static int lod_add_noop_records (const struct lu_env * env, struct dt_device * dt, struct thandle * th, int count) [static]
add noop update to the update records
Add noop updates to the update records, which is only used in test right now.
Parameters:
[in] env execution environment
[in] dt dt device of lod
[in] th thandle
[in] count the count of update records to be added.
Return values:
0 if adding succeeds.
negative errno if adding fails.
Definition at line 1258 of file lod_dev.c.
References fid_zero(), lod_env_info(), lod_thread_info::lti_fid, top_thandle::tt_multiple_thandle, and update_record_pack.
Referenced by lod_trans_stop().
static int lod_commit_async (const struct lu_env * env, struct dt_device * dev) [static]
Implementation of dt_device_operations::dt_commit_async() for LOD.
Asks local OSD to commit sooner.
see include/dt_object.h for the details.
Definition at line 1368 of file lod_dev.c.
References dt2lod_dev(), and dt_commit_async().
static void lod_conf_get (const struct lu_env * env, const struct dt_device * dev, struct dt_device_param * param) [static]
Implementation of dt_device_operations::dt_conf_get() for LOD.
Currently returns the configuration provided by the local OSD.
see include/dt_object.h for the details.
Definition at line 1308 of file lod_dev.c.
References dt2lod_dev(), and dt_conf_get().
static int lod_connect_to_osd (const struct lu_env * env, struct lod_device * lod, struct lustre_cfg * cfg) [static]
Connect to a local OSD.
Used to connect to the local OSD at mount. OSD name is taken from the configuration command passed. This connection is used to identify LU site and pin the OSD from early removal.
Parameters:
[in] env LU environment provided by the caller
[in] lod lod device
[in] cfg configuration command to apply
Return values:
0 on success
negative negated errno on error
Definition at line 1400 of file lod_dev.c.
References CERROR, class_name2obd(), dt_device::dd_lu_dev, ENTRY, obd_export::exp_obd, GOTO, LASSERT, lu_device::ld_site, lod_device::lod_child, lod_device::lod_child_exp, lod_device::lod_dt_dev, lu2dt_dev(), lustre_cfg_string(), LUSTRE_VERSION_CODE, OBD_ALLOC, OBD_ALLOC_PTR, obd_connect(), OBD_CONNECT_VERSION, OBD_FREE, OBD_FREE_PTR, obd_device::obd_lu_dev, obd_device::obd_uuid, obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_version, RETURN, and unlikely.
Referenced by lod_init0().
static struct lu_device* lod_device_alloc (const struct lu_env * env, struct lu_device_type * type, struct lustre_cfg * lcfg) [static, read]
Implementation of lu_device_type_operations::ldto_device_alloc() for LOD.
Allocates LOD device and calls the helpers to initialize it.
see include/lu_object.h for the details.
Definition at line 1606 of file lod_dev.c.
References dt_device_init(), lod2lu_dev(), lod_device_free(), lod_device::lod_dt_dev, lod_init0(), and OBD_ALLOC_PTR.
static struct lu_device * lod_device_fini (const struct lu_env * env, struct lu_device * d) [static, read]
Implementation of lu_device_type_operations::ldto_device_fini() for LOD.
Releases the internal resources used by LOD device.
see include/lu_object.h for the details.
Definition at line 1638 of file lod_dev.c.
References CERROR, ENTRY, lod2obd(), lod_fini_tgt(), lod_device::lod_mdt_descs, lod_device::lod_ost_descs, lod_pools_fini(), lod_procfs_fini(), lu2lod_dev(), and RETURN.
static struct lu_device* lod_device_free (const struct lu_env * env, struct lu_device * lu) [static, read]
Implementation of lu_device_type_operations::ldto_device_free() for LOD.
Releases the memory allocated for LOD device.
see include/lu_object.h for the details.
Definition at line 1586 of file lod_dev.c.
References dt_device::dd_lu_dev, dt_device_fini(), ENTRY, LASSERTF, lu_device::ld_ref, lod_device::lod_child, lod_device::lod_dt_dev, lu2lod_dev(), OBD_FREE_PTR, and RETURN.
Referenced by lod_device_alloc().
static void __exit lod_exit (void) [static]
Definition at line 1978 of file lod_dev.c.
References class_unregister_type(), lu_kmem_fini(), and LUSTRE_LOD_NAME.
static void lod_fini_distribute_txn (const struct lu_env * env, struct lod_device * lod) [static]
Finish distribute txn.
Release the resource holding by distribute txn, i.e. stop distribute txn thread.
Parameters:
[in] env execution environment
[in] lod lod device
Definition at line 792 of file lod_dev.c.
References distribute_txn_fini(), lu_device::ld_site, lod2lu_dev(), lu_site::ls_tgt, lu_target::lut_tdtd, and OBD_FREE_PTR.
Referenced by lod_process_config().
int lod_fld_lookup (const struct lu_env * env, struct lod_device * lod, const struct lu_fid * fid, __u32 * tgt, int * type)
Definition at line 121 of file lod_dev.c.
References CDEBUG, CERROR, D_INFO, DFID, ENTRY, fid_idif_ost_idx(), fid_is_idif(), fid_is_sane(), fid_is_update_log(), fid_is_update_log_dir(), fid_oid(), fid_seq_in_fldb(), fld_range_set_type(), fld_server_lookup(), LASSERT, lod2lu_dev(), lod2obd(), lod_device::lod_initialized, LPX64, lu_seq_range::lsr_flags, lu_seq_range::lsr_index, LU_SEQ_RANGE_MDT, LU_SEQ_RANGE_OST, lu_site2seq(), PFID, RETURN, seq_server_site::ss_node_id, and seq_server_site::ss_server_fld.
Referenced by lod_generate_and_set_lovea(), lod_object_init(), lod_parse_dir_striping(), lod_prep_lmv_md(), and lod_sub_get_thandle().
static int __init lod_init (void) [static]
Definition at line 1946 of file lod_dev.c.
References CERROR, class_register_type(), class_search_type(), lprocfs_register(), lu_kmem_fini(), lu_kmem_init(), LUSTRE_LOD_NAME, LUSTRE_LOV_NAME, proc_lustre_root, obd_type::typ_procroot, and obd_type::typ_procsym.
static int lod_init0 (const struct lu_env * env, struct lod_device * lod, struct lu_device_type * ldt, struct lustre_cfg * cfg) [static]
Initialize LOD device at setup.
Initializes the given LOD device using the original configuration command. The function initiates a connection to the local OSD and initializes few internal structures like pools, target tables, etc.
Parameters:
[in] env LU environment provided by the caller
[in] lod lod device
[in] ldt not used
[in] cfg configuration command
Return values:
0 on success
negative negated errno on error
Definition at line 1529 of file lod_dev.c.
References CERROR, class_name2obd(), dt_device::dd_lu_dev, dt_device::dd_ops, dt_device_param::ddp_max_ea_size, dt_conf_get(), ENTRY, GOTO, lu_device::ld_obd, lu_device::ld_ops, lod_device::lod_child_exp, lod_connect_to_osd(), lod_device::lod_connects_lock, lod_device::lod_desc_lock, lod_device::lod_dt_dev, lod_device::lod_mdt_descs, lod_device::lod_osd_max_easize, lod_device::lod_ost_descs, lod_pools_fini(), lod_pools_init(), lod_procfs_init(), lod_tgt_desc_init(), lustre_cfg_string(), obd_disconnect(), obd_device::obd_lu_dev, and RETURN.
Referenced by lod_device_alloc().
static void lod_key_fini (const struct lu_context * ctx, struct lu_context_key * key, void * data) [static]
Definition at line 1749 of file lod_dev.c.
References lod_thread_info::lti_ea_store, lod_thread_info::lti_ea_store_size, lod_thread_info::lti_linkea_buf, lu_buf_free(), OBD_FREE_LARGE, and OBD_FREE_PTR.
static int lod_obd_connect (const struct lu_env * env, struct obd_export ** exp, struct obd_device * obd, struct obd_uuid * cluuid, struct obd_connect_data * data, void * localdata) [static]
Implementation of obd_ops::o_connect() for LOD.
Used to track all the users of this specific LOD device, so the device stays up until the last user disconnected.
Parameters:
[in] env LU environment provided by the caller
[out] exp export the caller will be using to access LOD
[in] obd OBD device representing LOD device
[in] cluuid unique identifier of the caller
[in] data not used
[in] localdata not used
Return values:
0 on success
negative negated errno on error
Definition at line 1678 of file lod_dev.c.
References CDEBUG, class_conn2export(), class_connect(), D_CONFIG, ENTRY, LASSERT, lod_device::lod_connects, lod_device::lod_connects_lock, lu2lod_dev(), obd_device::obd_lu_dev, and RETURN.
static int lod_obd_disconnect (struct obd_export * exp) [static]
Implementation of obd_ops::o_disconnect() for LOD.
When the caller doesn't need to use this LOD instance, it calls obd_disconnect() and LOD releases corresponding export/reference count. Once all the users gone, LOD device is released.
Parameters:
[in] exp export provided to the caller in obd_connect()
Return values:
0 on success
negative negated errno on error
Definition at line 1717 of file lod_dev.c.
References CERROR, class_disconnect(), class_manual_cleanup(), ENTRY, obd_export::exp_obd, lod_device::lod_connects, lod_device::lod_connects_lock, lu2lod_dev(), obd_device::obd_lu_dev, obd_device::obd_name, and RETURN.
static int lod_obd_get_info (const struct lu_env * env, struct obd_export * exp, __u32 keylen, void * key, __u32 * vallen, void * val) [static]
Implementation of obd_ops::o_get_info() for LOD.
Currently, there is only one supported key: KEY_OSP_CONNECTED , to provide the caller binary status whether LOD has seen connection to any OST target. It will also check if the MDT update log context being initialized (if needed).
Parameters:
[in] env LU environment provided by the caller
[in] exp export of the caller
[in] keylen len of the key
[in] key the key
[in] vallen not used
[in] val not used
Return values:
0 if a connection was seen
-EAGAIN if LOD isn't running yet or no connection has been seen yet
-EINVAL if not supported key is requested
Definition at line 1811 of file lod_dev.c.
References CDEBUG, D_INFO, dt_device::dd_lu_dev, obd_export::exp_obd, KEY_IS, KEY_OSP_CONNECTED, LASSERT, lu_device::ld_obd, llog_ctxt_put(), llog_get_context(), LLOG_UPDATELOG_ORIG_CTXT, llog_ctxt::loc_handle, lod_foreach_mdt, lod_foreach_ost, lod_getref(), lod_device::lod_mdt_descs, lod_device::lod_ost_descs, lod_putref(), lod_tgt_desc::ltd_active, lod_tgt_desc::ltd_exp, lod_tgt_desc::ltd_tgt, lu2lod_dev(), MDT_TGT, obd_get_info(), obd_device::obd_lu_dev, obd_device::obd_name, obd_device::obd_set_up, obd_device::obd_stopping, OST_TGT, and RETURN.
static int lod_obd_set_info_async (const struct lu_env * env, struct obd_export * exp, __u32 keylen, void * key, __u32 vallen, void * val, struct ptlrpc_request_set * set) [static]
Definition at line 1876 of file lod_dev.c.
References class_exp2obd(), ENTRY, LASSERT, lod_foreach_mdt, lod_foreach_ost, lod_getref(), lod_device::lod_mdt_descs, lod_device::lod_ost_descs, lod_putref(), lod_tgt_desc::ltd_active, lod_tgt_desc::ltd_exp, lod_tgt_desc::ltd_tgt, lu2lod_dev(), MDT_TGT, obd_device::obd_lu_dev, obd_set_info_async(), OST_TGT, ptlrpc_prep_set(), ptlrpc_set_destroy(), ptlrpc_set_wait(), and RETURN.
static struct lu_object* lod_object_alloc (const struct lu_env * env, const struct lu_object_header * hdr, struct lu_device * dev) [static, read]
Implementation of lu_device_operations::ldo_object_alloc() for LOD.
Allocates and initializes LOD's slice in the given object.
see include/lu_object.h for the details.
Definition at line 204 of file lod_dev.c.
References dt_object::do_ops, dt_object_init(), ENTRY, lod_object::ldo_obj, lu_object::lo_ops, lod2lu_obj(), lod_lu_obj_ops, lod_obj(), lod_obj_ops, lod_object_kmem, OBD_SLAB_ALLOC_PTR_GFP, and RETURN.
static int lod_prepare (const struct lu_env * env, struct lu_device * pdev, struct lu_device * cdev) [static]
Implementation of lu_device_operations::ldo_prepare() for LOD.
see include/lu_object.h for the details.
Definition at line 1105 of file lod_dev.c.
References CERROR, dt_device::dd_lu_dev, dt_object::do_lu, dt_locate(), dt_root_get(), ENTRY, GOTO, lu_device::ld_ops, lu_device_operations::ldo_prepare, local_file_find_or_create_with_fid(), lod2lu_dev(), lod2obd(), lod_device::lod_child, lod_env_info(), lod_device::lod_initialized, lod_prepare_distribute_txn(), lod_sub_init_llogs(), lod_update_log_dir_name, lod_update_log_name, lod_thread_info::lti_fid, lu2lod_dev(), lu_object_put(), lu_site2seq(), lu_update_log_dir_fid(), lu_update_log_fid(), RETURN, and seq_server_site::ss_node_id.
static int lod_prepare_distribute_txn (const struct lu_env * env, struct lod_device * lod) [static]
Prepare distribute txn.
Prepare distribute txn structure for LOD
Parameters:
[in] env execution environment
[in] lod_device LOD device
Return values:
0 if preparation succeeds.
negative errno if preparation fails.
Definition at line 753 of file lod_dev.c.
References CERROR, distribute_txn_init(), ENTRY, lu_device::ld_site, lod2lu_dev(), lod2obd(), lod_device::lod_dt_dev, lu_site::ls_tgt, lu_site2seq(), lu_target::lut_tdtd, OBD_ALLOC_PTR, OBD_FREE_PTR, RETURN, and target_distribute_txn_data::tdtd_dt.
Referenced by lod_prepare().
static int lod_process_config (const struct lu_env * env, struct lu_device * dev, struct lustre_cfg * lcfg) [static]
Implementation of lu_device_operations::ldo_process_config() for LOD.
The method is called by the configuration subsystem during setup, cleanup and when the configuration changes. The method processes few specific commands like adding/removing the targets, changing the runtime parameters.
Parameters:
[in] env LU environment provided by the caller
[in] dev lod device
[in] lcfg configuration command to apply
Return values:
0 on success
negative negated errno on error
The examples are below.
Add osc config log: marker 20 (flags=0x01, v2.2.49.56) lustre-OST0001 'add osc' add_uuid nid=192.168.122.162(0x20000c0a87aa2) 0: 1:nidxxx attach 0:lustre-OST0001-osc-MDT0001 1:osc 2:lustre-MDT0001-mdtlov_UUID setup 0:lustre-OST0001-osc-MDT0001 1:lustre-OST0001_UUID 2:nid lov_modify_tgts add 0:lustre-MDT0001-mdtlov 1:lustre-OST0001_UUID 2:1 3:1 marker 20 (flags=0x02, v2.2.49.56) lustre-OST0001 'add osc'
Add mdc config log: marker 10 (flags=0x01, v2.2.49.56) lustre-MDT0000 'add osp' add_uuid nid=192.168.122.162(0x20000c0a87aa2) 0: 1:nid attach 0:lustre-MDT0000-osp-MDT0001 1:osp 2:lustre-MDT0001-mdtlov_UUID setup 0:lustre-MDT0000-osp-MDT0001 1:lustre-MDT0000_UUID 2:nid modify_mdc_tgts add 0:lustre-MDT0001 1:lustre-MDT0000_UUID 2:0 3:1 marker 10 (flags=0x02, v2.2.49.56) lustre-MDT0000_UUID 'add osp'
Definition at line 840 of file lod_dev.c.
References CDEBUG, CERROR, cfs_foreach_bit, class_name2obd(), class_process_proc_param(), D_HA, dt_device::dd_lu_dev, ENTRY, GOTO, LCFG_ADD_MDC, LCFG_CLEANUP, lustre_cfg::lcfg_command, LCFG_LOV_ADD_INA, LCFG_LOV_ADD_OBD, LCFG_LOV_DEL_OBD, LCFG_PARAM, LCFG_PRE_CLEANUP, lu_device::ld_obd, lu_device::ld_ops, lu_device::ld_site, lu_device_operations::ldo_process_config, llog_common_cat_ops, llog_ctxt_put(), llog_get_context(), llog_setup(), LLOG_UPDATELOG_ORIG_CTXT, lod2obd(), lod_add_device(), lod_device::lod_child, lod_device::lod_child_exp, lod_del_device(), lod_fini_distribute_txn(), lod_device::lod_mdt_descs, lod_device::lod_ost_descs, lod_sub_fini_all_llogs(), lod_sub_fini_llog(), lod_sub_prep_llog(), lod_sub_process_config(), lod_sub_stop_recovery_threads(), lodname2mdt_index(), lod_tgt_desc::ltd_active, lod_tgt_desc::ltd_index, lod_tgt_desc::ltd_tgt, LTD_TGT, lod_tgt_descs::ltd_tgt_bitmap, lu2lod_dev(), lu_dev_del_linkage(), lustre_cfg_buf(), lustre_cfg_string(), LUSTRE_MDC_NAME, LUSTRE_OSC_NAME, obd_disconnect(), obd_device::obd_olg, obd_device::obd_vars, PARAM_LOV, and RETURN.
static int lod_process_recovery_updates (const struct lu_env * env, struct llog_handle * llh, struct llog_rec_hdr * rec, void * data) [static]
process update recovery record
Add the update recovery recode to the update recovery list in lod_recovery_data. Then the recovery thread (target_recovery_thread) will redo these updates.
Parameters:
[in] execution environment
[in] log handle of update record
[in] update record to be replayed
[in] update recovery data which holds the necessary arguments for recovery (see struct lod_recovery_data)
Return values:
0 if the record is processed successfully.
negative errno if the record processing fails.
Definition at line 296 of file lod_dev.c.
References CDEBUG, CERROR, D_HA, DOSTID, ENTRY, insert_update_records_to_replay_list(), lu_device::ld_site, llog_cookie::lgc_index, llog_cookie::lgc_lgl, llog_cookie::lgc_subsys, llog_handle::lgh_id, llog_logid::lgl_oi, llog_update_record_size(), LLOG_UPDATELOG_ORIG_CTXT, lod2lu_dev(), lod2obd(), lod_env_info(), lodname2mdt_index(), lod_recovery_data::lrd_lod, lod_recovery_data::lrd_ltd, llog_rec_hdr::lrh_len, lu_site::ls_tgt, lod_tgt_desc::ltd_index, lod_thread_info::lti_cookie, lu_target::lut_obd, lu_target::lut_tdtd, obd_device::obd_abort_recovery, obd_device::obd_name, obd_device::obd_stopping, and POSTID.
Referenced by lod_sub_recovery_thread().
static int lod_recovery_complete (const struct lu_env * env, struct lu_device * dev) [static]
Implementation of lu_device_operations::ldo_recovery_complete() for LOD.
The method is called once the recovery is complete. This implementation distributes the notification to all the known targets.
see include/lu_object.h for the details
Definition at line 1029 of file lod_dev.c.
References CERROR, cfs_foreach_bit, dt_device::dd_lu_dev, ENTRY, LASSERT, lu_device::ld_ops, lu_device_operations::ldo_recovery_complete, lod2obd(), lod_device::lod_child, lod_getref(), lod_device::lod_ost_descs, lod_putref(), lod_device::lod_recovery_completed, lod_tgt_desc::ltd_tgt, lu2lod_dev(), OST_TGT, and RETURN.
static int lod_ro (const struct lu_env * env, struct dt_device * dev) [static]
Implementation of dt_device_operations::dt_ro() for LOD.
Turns local OSD read-only, used for the testing only.
see include/dt_object.h for the details.
Definition at line 1356 of file lod_dev.c.
References dt2lod_dev(), and dt_ro().
static int lod_root_get (const struct lu_env * env, struct dt_device * dev, struct lu_fid * f) [static]
Implementation of dt_device_operations::dt_root_get() for LOD.
see include/dt_object.h for the details.
Definition at line 1184 of file lod_dev.c.
References dt2lod_dev(), and dt_root_get().
static int lod_statfs (const struct lu_env * env, struct dt_device * dev, struct obd_statfs * sfs) [static]
Implementation of dt_device_operations::dt_statfs() for LOD.
see include/dt_object.h for the details.
Definition at line 1195 of file lod_dev.c.
References dt2lod_dev(), and dt_statfs().
static void lod_sub_fini_all_llogs (const struct lu_env * env, struct lod_device * lod) [static]
finish all sub llog
cleanup all of sub llog ctxt on the LOD.
Parameters:
[in] env execution environment
[in] lod lod device to do update recovery
Definition at line 720 of file lod_dev.c.
References cfs_foreach_bit, lod_device::lod_child, lod_device::lod_child_recovery_thread, lod_getref(), lod_device::lod_mdt_descs, lod_putref(), lod_sub_fini_llog(), lod_tgt_desc::ltd_recovery_thread, lod_tgt_desc::ltd_tgt, LTD_TGT, and lod_tgt_descs::ltd_tgt_bitmap.
Referenced by lod_process_config().
void lod_sub_fini_llog (const struct lu_env * env, struct dt_device * dt, struct ptlrpc_thread * thread)
finish sub llog context
Stop update recovery thread for the sub device, then cleanup the correspondent llog ctxt.
Parameters:
[in] env execution environment
[in] lod lod device to do update recovery
[in] thread recovery thread on this sub device
Definition at line 482 of file lod_dev.c.
References CDEBUG, D_INFO, dt_device::dd_lu_dev, ENTRY, lu_device::ld_obd, llog_cat_close(), llog_cleanup(), llog_get_context(), LLOG_UPDATELOG_ORIG_CTXT, llog_ctxt::loc_handle, obd_device::obd_name, RETURN_EXIT, SVC_RUNNING, SVC_STOPPED, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, and ptlrpc_thread::t_flags.
Referenced by lod_add_device(), lod_process_config(), lod_sub_fini_all_llogs(), and lod_sub_init_llog().
int lod_sub_init_llog (const struct lu_env * env, struct lod_device * lod, struct dt_device * dt)
Init sub llog context.
Setup update llog ctxt for update recovery threads, then start the recovery thread (lod_sub_recovery_thread) to read update llog from the correspondent MDT to do update recovery.
Parameters:
[in] env execution environment
[in] lod lod device to do update recovery
[in] dt sub dt device for which the recovery thread is
Return values:
0 if initialization succeeds.
negative errno if initialization fails.
Definition at line 578 of file lod_dev.c.
References CDEBUG, CERROR, cfs_foreach_bit, D_INFO, dt_device::dd_lu_dev, lvfs_run_ctxt::dt, ENTRY, GOTO, l_wait_event, LASSERT, lu_device::ld_obd, llog_common_cat_ops, llog_setup(), LLOG_UPDATELOG_ORIG_CTXT, lod2obd(), lod_device::lod_child, lod_device::lod_child_recovery_thread, lod_device::lod_mdt_descs, lod_sub_fini_llog(), lod_sub_recovery_thread(), lodname2mdt_index(), lod_recovery_data::lrd_idx, lod_recovery_data::lrd_lod, lod_recovery_data::lrd_ltd, lod_recovery_data::lrd_thread, lod_tgt_desc::ltd_index, lod_tgt_desc::ltd_recovery_thread, lod_tgt_desc::ltd_tgt, LTD_TGT, lod_tgt_descs::ltd_tgt_bitmap, OBD_ALLOC_PTR, OBD_FREE_PTR, obd_device::obd_lvfs_ctxt, obd_device::obd_name, obd_device::obd_olg, RETURN, SVC_RUNNING, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, ptlrpc_thread::t_flags, and thread.
Referenced by lod_add_device(), and lod_sub_init_llogs().
static int lod_sub_init_llogs (const struct lu_env * env, struct lod_device * lod) [static]
Init update logs on all sub device.
LOD initialize update logs on all of sub devices. Because the initialization process might need FLD lookup, see llog_osd_open()->dt_locate()->...-> lod_object_init(), this API has to be called after LOD is initialized.
Parameters:
[in] env execution environment
[in] lod lod device
Return values:
0 if update log is initialized successfully.
negative errno if initialization fails.
Definition at line 1072 of file lod_dev.c.
References cfs_foreach_bit, ENTRY, LASSERT, lod_device::lod_child, lod_device::lod_initialized, lod_device::lod_mdt_descs, lod_sub_init_llog(), lod_tgt_desc::ltd_tgt, LTD_TGT, lod_tgt_descs::ltd_tgt_bitmap, and RETURN.
Referenced by lod_prepare().
static int lod_sub_process_config (const struct lu_env * env, struct lod_device * lod, struct lod_tgt_descs * ltd, struct lustre_cfg * lcfg) [static]
Process the config log for all sub device.
The function goes through all the targets in the given table and apply given configuration command on to the targets. Used to cleanup the targets at unmount.
Parameters:
[in] env LU environment provided by the caller
[in] lod lod device
[in] ltd target's table to go through
[in] lcfg configuration command to apply
Return values:
0 on success
negative negated errno on error
Definition at line 239 of file lod_dev.c.
References CERROR, cfs_foreach_bit, dt_device::dd_lu_dev, LASSERT, lustre_cfg::lcfg_command, lu_device::ld_ops, lu_device_operations::ldo_process_config, lod2obd(), lod_getref(), lod_putref(), lod_tgt_desc::ltd_tgt, LTD_TGT, lod_tgt_descs::ltd_tgt_bitmap, and lod_tgt_descs::ltd_tgts_size.
Referenced by lod_process_config().
static int lod_sub_recovery_thread (void * arg) [static]
recovery thread for update log
Start recovery thread and prepare the sub llog, then it will retrieve the update records from the correpondent MDT and do recovery.
Parameters:
[in] arg pointer to the recovery data
Return values:
0 if recovery succeeds
negative errno if recovery failed.
Definition at line 354 of file lod_dev.c.
References CDEBUG, CERROR, cfs_foreach_bit, D_HA, dt_device::dd_lu_dev, ENTRY, GOTO, LASSERT, LCT_LOCAL, LCT_MD_THREAD, lu_device::ld_obd, lu_device::ld_site, llog_cat_close(), llog_cat_process(), llog_ctxt_put(), llog_get_context(), LLOG_UPDATELOG_ORIG_CTXT, llog_ctxt::loc_handle, lod2lu_dev(), lod2obd(), lod_device::lod_child, lod_device::lod_child_got_update_log, lod_device::lod_dt_dev, lod_device::lod_mdt_descs, lod_process_recovery_updates(), lod_sub_prep_llog(), lod_recovery_data::lrd_idx, lod_recovery_data::lrd_lod, lod_recovery_data::lrd_ltd, lod_recovery_data::lrd_thread, lu_site::ls_tgt, lu_site::ls_top_dev, lod_tgt_desc::ltd_got_update_log, LTD_TGT, lod_tgt_desc::ltd_tgt, lod_tgt_descs::ltd_tgt_bitmap, lu_env_fini(), lu_env_init(), lu_target::lut_obd, lu_target::lut_tdtd, obd_device::obd_abort_recovery, obd_device::obd_dev_lock, OBD_FREE_PTR, obd_device::obd_name, obd_device::obd_next_transno_waitq, obd_device::obd_stopping, RETURN, SVC_RUNNING, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, ptlrpc_thread::t_flags, target_distribute_txn_data::tdtd_recovery_threads_count, target_distribute_txn_data::tdtd_recovery_threads_waitq, target_distribute_txn_data::tdtd_replay_ready, and thread.
Referenced by lod_sub_init_llog().
static void lod_sub_stop_recovery_threads (const struct lu_env * env, struct lod_device * lod) [static]
Stop sub recovery thread.
Stop sub recovery thread on all subs.
Parameters:
[in] env execution environment
[in] lod lod device to do update recovery
Definition at line 676 of file lod_dev.c.
References cfs_foreach_bit, lod_device::lod_child_recovery_thread, lod_getref(), lod_device::lod_mdt_descs, lod_putref(), lod_tgt_desc::ltd_recovery_thread, LTD_TGT, lod_tgt_descs::ltd_tgt_bitmap, OBD_FREE_PTR, SVC_RUNNING, SVC_STOPPED, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, ptlrpc_thread::t_flags, and thread.
Referenced by lod_process_config().
static int lod_sync (const struct lu_env * env, struct dt_device * dev) [static]
Implementation of dt_device_operations::dt_sync() for LOD.
Syncs all known OST targets. Very very expensive and used rarely by LFSCK now. Should not be used in general.
see include/dt_object.h for the details.
Definition at line 1323 of file lod_dev.c.
References CERROR, dt2lod_dev(), dt_sync(), ENTRY, LASSERT, lod2obd(), lod_device::lod_child, lod_foreach_ost, lod_getref(), lod_ost_desc, lod_device::lod_ost_descs, lod_putref(), OST_TGT, and RETURN.
static int lod_tgt_desc_init (struct lod_tgt_descs * ltd) [static]
Allocate and initialize target table.
A helper function to initialize the target table and allocate a bitmap of the available targets.
Parameters:
[in] ltd target's table to initialize
Return values:
0 on success
negative negated errno on error
Definition at line 1495 of file lod_dev.c.
References CFS_ALLOCATE_BITMAP(), lod_tgt_descs::ltd_death_row, lod_tgt_descs::ltd_mutex, lod_tgt_descs::ltd_refcount, lod_tgt_descs::ltd_rw_sem, lod_tgt_descs::ltd_tgt_bitmap, lod_tgt_descs::ltd_tgtnr, lod_tgt_descs::ltd_tgts_size, and RETURN.
Referenced by lod_init0().
static int lod_trans_cb_add (struct thandle * th, struct dt_txn_commit_cb * dcb) [static]
Definition at line 1236 of file lod_dev.c.
References dt_trans_cb_add(), top_thandle::tt_master_sub_thandle, and top_thandle::tt_super.
static struct thandle* lod_trans_create (const struct lu_env * env, struct dt_device * dt) [static, read]
Implementation of dt_device_operations::dt_trans_create() for LOD.
Creates a transaction using local (to this node) OSD.
see include/dt_object.h for the details.
Definition at line 1208 of file lod_dev.c.
References dt2lod_dev(), thandle::th_dev, and top_trans_create().
static int lod_trans_start (const struct lu_env * env, struct dt_device * dt, struct thandle * th) [static]
Implementation of dt_device_operations::dt_trans_start() for LOD.
Starts the set of local transactions using the targets involved in declare phase. Initial support for the distributed transactions.
see include/dt_object.h for the details.
Definition at line 1230 of file lod_dev.c.
References dt2lod_dev(), and top_trans_start().
static int lod_trans_stop (const struct lu_env * env, struct dt_device * dt, struct thandle * th) [static]
Implementation of dt_device_operations::dt_trans_stop() for LOD.
Stops the set of local transactions using the targets involved in declare phase. Initial support for the distributed transactions.
see include/dt_object.h for the details.
Definition at line 1288 of file lod_dev.c.
References dt2lod_dev(), lod_add_noop_records(), OBD_FAIL_CHECK, OBD_FAIL_SPLIT_UPDATE_REC, RETURN, and top_trans_stop().
int lodname2mdt_index (char * lodname, __u32 * mdt_index)
Extract MDT target index from a device name.
a helper function to extract index from the given device name like "fsname-MDTxxxx-mdtlov"
Parameters:
[in] lodname device name
[out] mdt_index extracted index
Return values:
0 on success
-EINVAL if the name is invalid
Definition at line 522 of file lod_dev.c.
References CERROR.
Referenced by lod_process_config(), lod_process_recovery_updates(), lod_sub_init_llog(), and lod_sub_prep_llog().
LU_CONTEXT_KEY_DEFINE (lod , LCT_MD_THREAD)
LU_KEY_INIT (lod , struct lod_thread_info)
LU_TYPE_INIT_FINI (lod , & lod_thread_key)
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Logical Object Device ("LUSTRE_LOD_NAME")")
module_exit (lod_exit)
module_init (lod_init)
MODULE_LICENSE ("GPL")
MODULE_VERSION (LUSTRE_VERSION_STRING)
Variable Documentation
struct lu_kmem_descr lod_caches[] [static]
Initial value:
 {
        {
                .ckd_cache = &lod_object_kmem,
                .ckd_name  = "lod_obj",
                .ckd_size  = sizeof(struct lod_object)
        },
        {
                .ckd_cache = &lod_txn_callback_kmem,
                .ckd_name  = "lod_txn_callback",
                .ckd_size  = sizeof(struct dt_txn_callback)
        },
        {
                .ckd_cache = NULL
        }
}
Definition at line 178 of file lod_dev.c.
struct lu_device_type lod_device_type [static]
Initial value:
 {
        .ldt_tags     = LU_DEVICE_DT,
        .ldt_name     = LUSTRE_LOD_NAME,
        .ldt_ops      = &lod_device_type_ops,
        .ldt_ctx_tags = LCT_MD_THREAD,
}
Definition at line 1784 of file lod_dev.c.
struct lu_device_type_operations lod_device_type_ops [static]
Initial value:
 {
        .ldto_init           = lod_type_init,
        .ldto_fini           = lod_type_fini,
        .ldto_start          = lod_type_start,
        .ldto_stop           = lod_type_stop,
        .ldto_device_alloc   = lod_device_alloc,
        .ldto_device_free    = lod_device_free,
        .ldto_device_fini    = lod_device_fini
}
Definition at line 1771 of file lod_dev.c.
struct dt_device_operations lod_dt_ops [static]
Initial value:
 {
        .dt_root_get         = lod_root_get,
        .dt_statfs           = lod_statfs,
        .dt_trans_create     = lod_trans_create,
        .dt_trans_start      = lod_trans_start,
        .dt_trans_stop       = lod_trans_stop,
        .dt_conf_get         = lod_conf_get,
        .dt_sync             = lod_sync,
        .dt_ro               = lod_ro,
        .dt_commit_async     = lod_commit_async,
        .dt_trans_cb_add     = lod_trans_cb_add,
}
Definition at line 1373 of file lod_dev.c.
struct lu_device_operations lod_lu_ops
Initial value:
 {
        .ldo_object_alloc       = lod_object_alloc,
        .ldo_process_config     = lod_process_config,
        .ldo_recovery_complete  = lod_recovery_complete,
        .ldo_prepare            = lod_prepare,
}
Definition at line 1172 of file lod_dev.c.
Referenced by lu_device_is_lod().
struct obd_ops lod_obd_device_ops [static]
Initial value:
 {
        .o_owner        = THIS_MODULE,
        .o_connect      = lod_obd_connect,
        .o_disconnect   = lod_obd_disconnect,
        .o_get_info     = lod_obd_get_info,
        .o_set_info_async = lod_obd_set_info_async,
        .o_pool_new     = lod_pool_new,
        .o_pool_rem     = lod_pool_remove,
        .o_pool_add     = lod_pool_add,
        .o_pool_del     = lod_pool_del,
}
Definition at line 1934 of file lod_dev.c.
struct kmem_cache* lod_object_kmem
Definition at line 174 of file lod_dev.c.
Referenced by lod_object_alloc(), and lod_object_free().
struct kmem_cache* lod_txn_callback_kmem
Definition at line 177 of file lod_dev.c.
const char lod_update_log_dir_name[] = "update_log_dir" [static]
Definition at line 103 of file lod_dev.c.
Referenced by lod_prepare().
const char lod_update_log_name[] = "update_log" [static]
Definition at line 102 of file lod_dev.c.
Referenced by lod_prepare().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.