Lustre: lustre/lod/lod_sub_object.c File Reference
lustre/lod/lod_sub_object.c File Reference
#include <obd.h>
#include <obd_class.h>
#include <lustre_ver.h>
#include <obd_support.h>
#include <lprocfs_status.h>
#include <lustre_fid.h>
#include <lustre_param.h>
#include <md_object.h>
#include <lustre_linkea.h>
#include <lustre_log.h>
#include "lod_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_MDS
Functions
struct thandle * lod_sub_get_thandle (const struct lu_env *env, struct thandle *th, const struct dt_object *sub_obj, bool *record_update)
int lod_sub_object_declare_create (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *th)
Declare sub-object creation.
int lod_sub_object_create (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *th)
Create sub-object.
int lod_sub_object_declare_ref_add (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Declare adding reference for the sub-object.
int lod_sub_object_ref_add (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Add reference for the sub-object.
int lod_sub_object_declare_ref_del (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Declare deleting reference for the sub-object.
int lod_sub_object_ref_del (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Delete reference for the sub-object.
int lod_sub_object_declare_destroy (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Declare destroying sub-object.
int lod_sub_object_destroy (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Destroy sub-object.
int lod_sub_object_declare_insert (const struct lu_env *env, struct dt_object *dt, const struct dt_rec *rec, const struct dt_key *key, struct thandle *th)
Declare sub-object index insert.
int lod_sub_object_index_insert (const struct lu_env *env, struct dt_object *dt, const struct dt_rec *rec, const struct dt_key *key, struct thandle *th, int ign)
Insert index of sub object.
int lod_sub_object_declare_delete (const struct lu_env *env, struct dt_object *dt, const struct dt_key *key, struct thandle *th)
Declare sub-object index delete.
int lod_sub_object_delete (const struct lu_env *env, struct dt_object *dt, const struct dt_key *name, struct thandle *th)
Delete index of sub object.
int lod_sub_object_declare_xattr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, const char *name, int fl, struct thandle *th)
Declare xattr_set.
int lod_sub_object_xattr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, const char *name, int fl, struct thandle *th)
Set xattr.
int lod_sub_object_declare_attr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_attr *attr, struct thandle *th)
Declare attr_set.
int lod_sub_object_attr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_attr *attr, struct thandle *th)
attributes set
int lod_sub_object_declare_xattr_del (const struct lu_env *env, struct dt_object *dt, const char *name, struct thandle *th)
Declare xattr_del.
int lod_sub_object_xattr_del (const struct lu_env *env, struct dt_object *dt, const char *name, struct thandle *th)
xattribute deletion
int lod_sub_object_declare_write (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, loff_t pos, struct thandle *th)
Declare buffer write.
ssize_t lod_sub_object_write (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, loff_t *pos, struct thandle *th, int rq)
Write buffer to sub object.
int lod_sub_object_declare_punch (const struct lu_env *env, struct dt_object *dt, __u64 start, __u64 end, struct thandle *th)
Declare punch.
int lod_sub_object_punch (const struct lu_env *env, struct dt_object *dt, __u64 start, __u64 end, struct thandle *th)
Punch to sub object.
int lod_sub_prep_llog (const struct lu_env *env, struct lod_device *lod, struct dt_device *dt, int index)
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 41 of file lod_sub_object.c.
Function Documentation
struct thandle* lod_sub_get_thandle (const struct lu_env * env, struct thandle * th, const struct dt_object * sub_obj, bool * record_update) [read]
Definition at line 57 of file lod_sub_object.c.
References dt_object::do_lu, dt2lod_dev(), dt_object_remote(), ENTRY, fid_is_sane(), fid_is_zero(), lod_fld_lookup(), lu_object_fid(), LU_SEQ_RANGE_ANY, LU_SEQ_RANGE_OST, RETURN, thandle::th_complex, thandle::th_dev, thandle::th_result, thandle::th_top, thandle_get_sub(), top_thandle::tt_master_sub_thandle, and top_thandle::tt_multiple_thandle.
Referenced by lod_sub_object_attr_set(), lod_sub_object_create(), lod_sub_object_declare_attr_set(), lod_sub_object_declare_create(), lod_sub_object_declare_delete(), lod_sub_object_declare_destroy(), lod_sub_object_declare_insert(), lod_sub_object_declare_punch(), lod_sub_object_declare_ref_add(), lod_sub_object_declare_ref_del(), lod_sub_object_declare_write(), lod_sub_object_declare_xattr_del(), lod_sub_object_declare_xattr_set(), lod_sub_object_delete(), lod_sub_object_destroy(), lod_sub_object_index_insert(), lod_sub_object_punch(), lod_sub_object_ref_add(), lod_sub_object_ref_del(), lod_sub_object_write(), lod_sub_object_xattr_del(), and lod_sub_object_xattr_set().
int lod_sub_object_attr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_attr * attr, struct thandle * th)
attributes set
Get transaction of next layer, record updates if it belongs to cross-MDT operation, and set attributes to the object.
Parameters:
[in] env execution environment
[in] dt object on which to set attr
[in] attr attrbutes to be set
[in] th transaction handle
Return values:
0 if attributes setting succeeds.
negative errno if the attributes setting fails.
Definition at line 678 of file lod_sub_object.c.
References dt_object::do_lu, dt_attr_set(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_pack.
Referenced by lod_attr_set().
int lod_sub_object_create (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof, struct thandle * th)
Create sub-object.
Get transaction of next layer, record updates if it belongs to cross-MDT operation, and create the object.
Parameters:
[in] env execution environment
[in] dt the object being created
[in] attr the attributes of the object being created
[in] hint the hint of the creation
[in] dof the object format of the creation
th] th the transaction handle
Return values:
0 if the creation succeeds
negative errno if the creation fails.
Definition at line 166 of file lod_sub_object.c.
References dt_object::do_lu, dt_create(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_pack.
Referenced by lod_object_create(), lod_striping_create(), and lod_xattr_set_lmv().
int lod_sub_object_declare_attr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_attr * attr, struct thandle * th)
Declare attr_set.
Get transaction of next layer, and declare attr set.
Parameters:
[in] env execution environment
[in] dt object on which to set attr
[in] attr attributes to be set
[in] th transaction handle
Return values:
0 if the declaration succeeds.
negative errno if the declaration fails.
Definition at line 641 of file lod_sub_object.c.
References dt_object::do_lu, dt_declare_attr_set(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_size.
Referenced by lod_declare_attr_set(), and lod_declare_init_size().
int lod_sub_object_declare_create (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof, struct thandle * th)
Declare sub-object creation.
Get transaction of next layer and declare the creation of the object.
Parameters:
[in] env execution environment
[in] dt the object being created
[in] attr the attributes of the object being created
[in] hint the hint of the creation
[in] dof the object format of the creation
th] th the transaction handle
Return values:
0 if the declaration succeeds
negative errno if the declaration fails.
Definition at line 129 of file lod_sub_object.c.
References dt_object::do_lu, dt_declare_create(), lod_sub_get_thandle(), lu_object_fid(), and update_record_size.
Referenced by lod_declare_object_create(), lod_dir_declare_create_stripes(), lod_qos_declare_object_on(), and lod_qos_prep_create().
int lod_sub_object_declare_delete (const struct lu_env * env, struct dt_object * dt, const struct dt_key * key, struct thandle * th)
Declare sub-object index delete.
Get transaction of next layer and declare index deletion.
Parameters:
[in] env execution environment
[in] dt object for which to delete index
[in] key key of the index which will be deleted
[in] th the transaction handle
Return values:
0 if the declaration succeeds.
negative errno if the declaration fails.
Definition at line 491 of file lod_sub_object.c.
References dt_object::do_lu, dt_declare_delete(), lod_sub_get_thandle(), lu_object_fid(), and update_record_size.
Referenced by lod_declare_index_delete(), and lod_declare_object_destroy().
int lod_sub_object_declare_destroy (const struct lu_env * env, struct dt_object * dt, struct thandle * th)
Declare destroying sub-object.
Get transaction of next layer and declare the sub-object destroy.
Parameters:
[in] env execution environment
[in] dt dt object to be destroyed
[in] th transaction handle
Return values:
0 if the declaration succeeds.
negative errno if the declaration fails.
Definition at line 346 of file lod_sub_object.c.
References dt_object::do_lu, dt_declare_destroy(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_size.
Referenced by lod_declare_object_destroy().
int lod_sub_object_declare_insert (const struct lu_env * env, struct dt_object * dt, const struct dt_rec * rec, const struct dt_key * key, struct thandle * th)
Declare sub-object index insert.
Get transaction of next layer and declare index insert.
Parameters:
[in] env execution environment
[in] dt object for which to insert index
[in] rec record of the index which will be inserted
[in] key key of the index which will be inserted
[in] th the transaction handle
Return values:
0 if the declaration succeeds.
negative errno if the declaration fails.
Definition at line 419 of file lod_sub_object.c.
References dt_object::do_lu, dt_declare_insert(), lod_sub_get_thandle(), lu_object_fid(), and update_record_size.
Referenced by lod_declare_index_insert(), and lod_dir_declare_create_stripes().
int lod_sub_object_declare_punch (const struct lu_env * env, struct dt_object * dt, __u64 start, __u64 end, struct thandle * th)
Declare punch.
Get transaction of next layer and declare punch.
Parameters:
[in] env execution environment
[in] dt object to be written
[in] start start offset of punch
[in] end end offet of punch
[in] th transaction handle
Return values:
0 if the insertion succeeds.
negative errno if the insertion fails.
Definition at line 873 of file lod_sub_object.c.
References dt_object::do_lu, dt_declare_punch(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_size.
Referenced by lod_declare_punch().
int lod_sub_object_declare_ref_add (const struct lu_env * env, struct dt_object * dt, struct thandle * th)
Declare adding reference for the sub-object.
Get transaction of next layer and declare the reference adding.
Parameters:
[in] env execution environment
[in] dt dt object to add reference
[in] th transaction handle
Return values:
0 if the declaration succeeds.
negative errno if the declaration fails.
Definition at line 206 of file lod_sub_object.c.
References dt_object::do_lu, dt_declare_ref_add(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_size.
Referenced by lod_declare_ref_add(), and lod_dir_declare_create_stripes().
int lod_sub_object_declare_ref_del (const struct lu_env * env, struct dt_object * dt, struct thandle * th)
Declare deleting reference for the sub-object.
Get transaction of next layer and declare the reference deleting.
Parameters:
[in] env execution environment
[in] dt dt object to delete reference
[in] th transaction handle
Return values:
0 if the declaration succeeds.
negative errno if the declaration fails.
Definition at line 276 of file lod_sub_object.c.
References dt_object::do_lu, dt_declare_ref_del(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_size.
Referenced by lod_declare_object_destroy(), and lod_declare_ref_del().
int lod_sub_object_declare_write (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, loff_t pos, struct thandle * th)
Declare buffer write.
Get transaction of next layer and declare buffer write.
Parameters:
[in] env execution environment
[in] dt object to be written
[in] buf buffer to write which includes an embedded size field
[in] pos offet in the object to start writing at
[in] th transaction handle
Return values:
0 if the insertion succeeds.
negative errno if the insertion fails.
Definition at line 795 of file lod_sub_object.c.
References dt_object::do_lu, dt_declare_write(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_size.
Referenced by lod_declare_write().
int lod_sub_object_declare_xattr_del (const struct lu_env * env, struct dt_object * dt, const char * name, struct thandle * th)
Declare xattr_del.
Get transaction of next layer, and declare xattr deletion.
Parameters:
[in] env execution environment
[in] dt object on which to delete xattr
[in] name name of the xattr to be deleted
[in] th transaction handle
Return values:
0 if the declaration succeeds.
negative errno if the declaration fails.
Definition at line 717 of file lod_sub_object.c.
References dt_object::do_lu, dt_declare_xattr_del(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_size.
Referenced by lod_declare_attr_set(), and lod_declare_xattr_del().
int lod_sub_object_declare_xattr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, const char * name, int fl, struct thandle * th)
Declare xattr_set.
Get transaction of next layer, and declare xattr set.
Parameters:
[in] env execution environment
[in] dt object on which to set xattr
[in] buf xattr to be set
[in] name name of the xattr
[in] fl flag for setting xattr
Return values:
0 if the declaration succeeds.
negative errno if the declaration fails.
Definition at line 561 of file lod_sub_object.c.
References dt_object::do_lu, dt_declare_xattr_set(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_size.
Referenced by lod_declare_attr_set(), lod_declare_striped_object(), lod_declare_xattr_set(), lod_dir_declare_create_stripes(), lod_dir_declare_xattr_set(), and lod_object_replace_parent_fid().
int lod_sub_object_delete (const struct lu_env * env, struct dt_object * dt, const struct dt_key * name, struct thandle * th)
Delete index of sub object.
Get transaction of next layer, record updates if it belongs to cross-MDT operation, and delete the index.
Parameters:
[in] env execution environment
[in] dt object for which to delete index
[in] key key of the index to be deleted
[in] th the transaction handle
Return values:
0 if the deletion succeeds.
negative errno if the deletion fails.
Definition at line 524 of file lod_sub_object.c.
References dt_object::do_lu, dt_delete(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_pack.
Referenced by lod_index_delete(), and lod_object_destroy().
int lod_sub_object_destroy (const struct lu_env * env, struct dt_object * dt, struct thandle * th)
Destroy sub-object.
Get transaction of next layer, record updates if it belongs to cross-MDT operation and destroy the object.
Parameters:
[in] env execution environment
[in] dt dt object to be destroyed
[in] th transaction handle
Return values:
0 if the destroy succeeds.
negative errno if the destroy fails.
Definition at line 381 of file lod_sub_object.c.
References dt_object::do_lu, dt_destroy(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_pack.
Referenced by lod_object_destroy().
int lod_sub_object_index_insert (const struct lu_env * env, struct dt_object * dt, const struct dt_rec * rec, const struct dt_key * key, struct thandle * th, int ign)
Insert index of sub object.
Get transaction of next layer, record updates if it belongs to cross-MDT operation, and insert the index.
Parameters:
[in] env execution environment
[in] dt object for which to insert index
[in] rec record of the index to be inserted
[in] key key of the index to be inserted
[in] th the transaction handle
[in] ign whether ignore quota
Return values:
0 if the insertion succeeds.
negative errno if the insertion fails.
Definition at line 455 of file lod_sub_object.c.
References dt_object::do_lu, dt_insert(), lod_sub_get_thandle(), lu_object_fid(), and update_record_pack.
Referenced by lod_index_insert(), and lod_xattr_set_lmv().
int lod_sub_object_punch (const struct lu_env * env, struct dt_object * dt, __u64 start, __u64 end, struct thandle * th)
Punch to sub object.
Get transaction of next layer, records buffer write if it belongs to Cross-MDT operation, and punch object.
Parameters:
[in] env execution environment
[in] dt object to be written
[in] start start offset of punch
[in] end end offset of punch
[in] th transaction handle
[in] capa capability of the write
Return values:
the buffer size in bytes if it succeeds.
negative errno if it fails.
Definition at line 913 of file lod_sub_object.c.
References dt_object::do_lu, dt_punch(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_pack.
Referenced by lod_punch().
int lod_sub_object_ref_add (const struct lu_env * env, struct dt_object * dt, struct thandle * th)
Add reference for the sub-object.
Get transaction of next layer, record updates if it belongs to cross-MDT operation and add reference of the object.
Parameters:
[in] env execution environment
[in] dt dt object to add reference
[in] th transaction handle
Return values:
0 if it succeeds.
negative errno if it fails.
Definition at line 240 of file lod_sub_object.c.
References dt_object::do_lu, dt_ref_add(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_pack.
Referenced by lod_ref_add(), and lod_xattr_set_lmv().
int lod_sub_object_ref_del (const struct lu_env * env, struct dt_object * dt, struct thandle * th)
Delete reference for the sub-object.
Get transaction of next layer, record updates if it belongs to cross-MDT operation and delete reference of the object.
Parameters:
[in] env execution environment
[in] dt dt object to delete reference
[in] th transaction handle
Return values:
0 if it succeeds.
negative errno if it fails.
Definition at line 310 of file lod_sub_object.c.
References dt_object::do_lu, dt_ref_del(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_pack.
Referenced by lod_object_destroy(), and lod_ref_del().
ssize_t lod_sub_object_write (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, loff_t * pos, struct thandle * th, int rq)
Write buffer to sub object.
Get transaction of next layer, records buffer write if it belongs to Cross-MDT operation, and write buffer.
Parameters:
[in] env execution environment
[in] dt object to be written
[in] buf buffer to write which includes an embedded size field
[in] pos offet in the object to start writing at
[in] th transaction handle
[in] rq enforcement for this write
Return values:
the buffer size in bytes if it succeeds.
negative errno if it fails.
Definition at line 835 of file lod_sub_object.c.
References dt_object::do_lu, dt_write(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_pack.
Referenced by lod_write().
int lod_sub_object_xattr_del (const struct lu_env * env, struct dt_object * dt, const char * name, struct thandle * th)
xattribute deletion
Get transaction of next layer, record update if it belongs to cross-MDT operation and delete xattr.
Parameters:
[in] env execution environment
[in] dt object on which to delete xattr
[in] name name of the xattr to be deleted
[in] th transaction handle
Return values:
0 if the deletion succeeds.
negative errno if the deletion fails.
Definition at line 755 of file lod_sub_object.c.
References dt_object::do_lu, dt_xattr_del(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_pack.
Referenced by lod_attr_set(), lod_xattr_del(), and lod_xattr_del_internal().
int lod_sub_object_xattr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, const char * name, int fl, struct thandle * th)
Set xattr.
Get transaction of next layer, record updates if it belongs to cross-MDT operation, and set xattr to the object.
Parameters:
[in] env execution environment
[in] dt object on which to set xattr
[in] buf xattr to be set
[in] name name of the xattr
[in] fl flag for setting xattr
[in] th transaction handle
Return values:
0 if the xattr setting succeeds.
negative errno if xattr setting fails.
Definition at line 602 of file lod_sub_object.c.
References dt_object::do_lu, dt_xattr_set(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_pack.
Referenced by lod_attr_set(), lod_generate_and_set_lovea(), lod_object_replace_parent_fid(), lod_xattr_set(), lod_xattr_set_internal(), and lod_xattr_set_lmv().
int lod_sub_prep_llog (const struct lu_env * env, struct lod_device * lod, struct dt_device * dt, int index)
Definition at line 937 of file lod_sub_object.c.
References CDEBUG, CERROR, D_INFO, dt_device::dd_lu_dev, DOSTID, ENTRY, GOTO, LASSERT, llog_catid::lci_logid, lu_device::ld_obd, llog_handle::lgh_id, llog_logid::lgl_ogen, llog_logid::lgl_oi, likely, llog_cat_close(), LLOG_CTXT_FLAG_NORMAL_FID, llog_ctxt_put(), LLOG_F_IS_CAT, llog_get_context(), llog_init_handle(), LLOG_MIN_CHUNK_SIZE, llog_open(), llog_open_create(), LLOG_OPEN_EXISTS, llog_osd_get_cat_list(), llog_osd_put_cat_list(), LLOG_UPDATELOG_ORIG_CTXT, llog_ctxt::loc_chunk_size, llog_ctxt::loc_flags, llog_ctxt::loc_handle, lod2obd(), lod_env_info(), lodname2mdt_index(), logid_id(), logid_set_id(), lod_thread_info::lti_cid, lod_thread_info::lti_fid, lu_update_log_fid(), obd_device::obd_name, POSTID, RETURN, and unlikely.
Referenced by lod_process_config(), and lod_sub_recovery_thread().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.