Lustre: lustre/lod/lod_lov.c File Reference
lustre/lod/lod_lov.c File Reference
#include <obd_class.h>
#include <lustre_lfsck.h>
#include <lustre_lmv.h>
#include <lustre_swab.h>
#include "lod_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_MDS
Functions
void lod_getref (struct lod_tgt_descs *ltd)
Increase reference count on the target table.
void lod_putref (struct lod_device *lod, struct lod_tgt_descs *ltd)
Decrease reference count on the target table.
static int ltd_bitmap_resize (struct lod_tgt_descs *ltd, __u32 newsize)
Expand size of target table.
int lod_add_device (const struct lu_env *env, struct lod_device *lod, char *osp, unsigned index, unsigned gen, int tgt_index, char *type, int active)
Connect LOD to a new OSP and add it to the target table.
static void __lod_del_device (const struct lu_env *env, struct lod_device *lod, struct lod_tgt_descs *ltd, unsigned idx, bool for_ost)
Schedule target removal from the target table.
int lod_fini_tgt (const struct lu_env *env, struct lod_device *lod, struct lod_tgt_descs *ltd, bool for_ost)
Schedule removal of all the targets from the given target table.
int lod_del_device (const struct lu_env *env, struct lod_device *lod, struct lod_tgt_descs *ltd, char *osp, unsigned idx, unsigned gen, bool for_ost)
Remove device by name.
int lod_ea_store_resize (struct lod_thread_info *info, size_t size)
Resize per-thread storage to hold specified size.
int lod_generate_and_set_lovea (const struct lu_env *env, struct lod_object *lo, struct thandle *th)
Make LOV EA for striped object.
int lod_get_ea (const struct lu_env *env, struct lod_object *lo, const char *name)
Get LOV EA.
static int validate_lod_and_idx (struct lod_device *md, __u32 idx)
Verify the target index is present in the current configuration.
int lod_initialize_objects (const struct lu_env *env, struct lod_object *lo, struct lov_ost_data_v1 *objs)
Instantiate objects for stripes.
int lod_parse_striping (const struct lu_env *env, struct lod_object *lo, const struct lu_buf *buf)
Instantiate objects for striping.
int lod_load_striping_locked (const struct lu_env *env, struct lod_object *lo)
Initialize the object representing the stripes.
int lod_load_striping (const struct lu_env *env, struct lod_object *lo)
A generic function to initialize the stripe objects.
int lod_verify_striping (struct lod_device *d, const struct lu_buf *buf, bool is_from_disk)
Verify striping.
void lod_fix_desc_stripe_size (__u64 *val)
void lod_fix_desc_stripe_count (__u32 *val)
void lod_fix_desc_pattern (__u32 *val)
void lod_fix_desc_qos_maxage (__u32 *val)
void lod_fix_desc (struct lov_desc *desc)
Used to fix insane default striping.
int lod_pools_init (struct lod_device *lod, struct lustre_cfg *lcfg)
Initialize the structures used to store pools and default striping.
int lod_pools_fini (struct lod_device *lod)
Release the structures describing the pools.
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 37 of file lod_lov.c.
Function Documentation
static void __lod_del_device (const struct lu_env * env, struct lod_device * lod, struct lod_tgt_descs * ltd, unsigned idx, bool for_ost) [static]
Schedule target removal from the target table.
Mark the device as dead. The device is not removed here because it may still be in use. The device will be removed in lod_putref() when the last reference is released.
Parameters:
[in] env execution environment for this thread
[in] lod LOD device the target table belongs to
[in] ltd target table
[in] idx index of the target
[in] for_ost type of the target: 0 - MDT, 1 - OST
Definition at line 456 of file lod_lov.c.
References LASSERT, lfsck_del_target(), lod_device::lod_child, lod_tgt_descs::ltd_death_row, LTD_TGT, OBD_FREE_PTR, and thread.
Referenced by lod_del_device(), and lod_fini_tgt().
int lod_add_device (const struct lu_env * env, struct lod_device * lod, char * osp, unsigned index, unsigned gen, int tgt_index, char * type, int active)
Connect LOD to a new OSP and add it to the target table.
Connect to the OSP device passed, initialize all the internal structures related to the device and add it to the target table.
Parameters:
[in] env execution environment for this thread
[in] lod LOD device to be connected to the new OSP
[in] osp name of OSP device name to be added
[in] index index of the new target
[in] gen target's generation number
[in] tgt_index OSP's group
[in] type type of device (mdc or osc)
[in] active state of OSP: 0 - inactive, 1 - active
Return values:
0 if added successfully
negative error number on failure
Definition at line 207 of file lod_lov.c.
References CDEBUG, CERROR, cfs_bitmap_check(), cfs_bitmap_clear(), cfs_bitmap_set(), client_obd::cl_import, client_obd::cl_target_uuid, class_find_client_obd(), obd_device::cli, ptlrpc_client::cli_request_portal, D_CONFIG, D_OTHER, dt_device::dd_lu_dev, ENTRY, GOTO, obd_import::imp_client, obd_import::imp_lock, obd_import::imp_server_timeout, LASSERT, LCFG_CLEANUP, lustre_cfg::lcfg_command, lustre_cfg::lcfg_version, lov_desc::ld_active_tgt_count, lu_device::ld_obd, lu_device::ld_ops, lu_device::ld_site, lov_desc::ld_tgt_count, lu_device_operations::ldo_process_config, lu_device_operations::ldo_recovery_complete, lfsck_add_target(), lod2obd(), lod_device::lod_child, lod_device::lod_desc, lod_device::lod_dt_dev, lod_env_info(), lod_getref(), lod_device::lod_initialized, lod_device::lod_mdt_descs, lod_device::lod_ost_descs, lod_ost_pool_add(), lod_ost_pool_remove(), lod_device::lod_pool_info, lod_putref(), lod_device::lod_recovery_completed, lod_sub_fini_llog(), lod_sub_init_llog(), lod_tgt_desc::ltd_active, ltd_bitmap_resize(), lod_tgt_desc::ltd_exp, lod_tgt_desc::ltd_gen, lod_tgt_desc::ltd_index, lod_tgt_descs::ltd_mutex, lod_tgt_desc::ltd_recovery_thread, LTD_TGT, lod_tgt_desc::ltd_tgt, lod_tgt_descs::ltd_tgt_bitmap, lod_tgt_descs::ltd_tgt_idx, lod_tgt_descs::ltd_tgtnr, lod_tgt_descs::ltd_tgts_size, lod_tgt_desc::ltd_uuid, lod_thread_info::lti_lustre_cfg, lu2dt_dev(), LUSTRE_CFG_VERSION, LUSTRE_OSC_NAME, LUSTRE_OSP_NAME, LUSTRE_VERSION_CODE, max, MDS_INODELOCK_UPDATE, OBD_ALLOC_PTR, obd_connect(), OBD_CONNECT_ACL, OBD_CONNECT_AT, OBD_CONNECT_BULK_MBITS, OBD_CONNECT_FID, OBD_CONNECT_FULL20, OBD_CONNECT_IBITS, OBD_CONNECT_INDEX, OBD_CONNECT_LFSCK, OBD_CONNECT_LRU_RESIZE, OBD_CONNECT_LVB_TYPE, OBD_CONNECT_MDS, OBD_CONNECT_MDS_MDS, OBD_CONNECT_PINGLESS, OBD_CONNECT_REQPORTAL, OBD_CONNECT_SKIP_ORPHAN, OBD_CONNECT_VERSION, obd_disconnect(), OBD_FREE_PTR, obd_device::obd_lu_dev, obd_device::obd_name, obd_str2uuid(), obd_device::obd_uuid, obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_group, obd_connect_data::ocd_ibits_known, obd_connect_data::ocd_index, obd_connect_data::ocd_version, OUT_PORTAL, qos_add_tgt(), RETURN, TGT_PTRS_PER_BLOCK, thread, and obd_device::u.
Referenced by lod_process_config().
int lod_del_device (const struct lu_env * env, struct lod_device * lod, struct lod_tgt_descs * ltd, char * osp, unsigned idx, unsigned gen, bool for_ost)
Remove device by name.
Remove a device identified by osp from the target table. Given the device can be in use, the real deletion happens in lod_putref().
Parameters:
[in] env execution environment for this thread
[in] lod LOD device to be connected to the new OSP
[in] ltd target table
[in] osp name of OSP device to be removed
[in] idx index of the target
[in] gen generation number, not used currently
[in] for_ost type of the target: 0 - MDT, 1 - OST
Return values:
0 if the device was scheduled for removal
-EINVAL if no device was found
Definition at line 529 of file lod_lov.c.
References __lod_del_device(), CDEBUG, CERROR, cfs_bitmap_check(), class_find_client_obd(), D_CONFIG, dt_device::dd_lu_dev, ENTRY, EXIT, GOTO, lu_device::ld_obd, lod_device::lod_dt_dev, lod_getref(), lod_putref(), lod_tgt_descs::ltd_mutex, LTD_TGT, lod_tgt_descs::ltd_tgt_bitmap, LUSTRE_OSP_NAME, obd_device::obd_name, obd_str2uuid(), obd_device::obd_uuid, obd_uuid2str(), obd_uuid_equals(), and RETURN.
Referenced by lod_process_config().
int lod_ea_store_resize (struct lod_thread_info * info, size_t size)
Resize per-thread storage to hold specified size.
A helper function to resize per-thread temporary storage. This storage is used to process LOV/LVM EAs and may be quite large. We do not want to allocate/release it every time, so instead we put it into the env and reallocate on demand. The memory is released when the correspondent thread is finished.
Parameters:
[in] info LOD-specific storage in the environment
[in] size new size to grow the buffer to
Return values:
0 on success, -ENOMEM if reallocation failed
Definition at line 596 of file lod_lov.c.
References CDEBUG, D_INFO, LASSERT, LOV_MAGIC_V3, LOV_MAX_STRIPE_COUNT, lov_mds_md_size(), lod_thread_info::lti_ea_store, lod_thread_info::lti_ea_store_size, OBD_ALLOC_LARGE, OBD_FREE_LARGE, RETURN, and size_roundup_power2().
Referenced by lod_dir_striping_create_internal(), lod_generate_and_set_lovea(), lod_get_ea(), lod_object_replace_parent_fid(), lod_prep_lmv_md(), and lod_qos_ost_in_use_clear().
int lod_fini_tgt (const struct lu_env * env, struct lod_device * lod, struct lod_tgt_descs * ltd, bool for_ost)
Schedule removal of all the targets from the given target table.
See more details in the description for __lod_del_device()
Parameters:
[in] env execution environment for this thread
[in] lod LOD device the target table belongs to
[in] ltd target table
[in] for_ost type of the target: MDT or OST
Return values:
0 always
Definition at line 490 of file lod_lov.c.
References __lod_del_device(), cfs_foreach_bit, CFS_FREE_BITMAP, lod_getref(), lod_putref(), lod_tgt_descs::ltd_mutex, lod_tgt_descs::ltd_tgt_bitmap, lod_tgt_descs::ltd_tgt_idx, lod_tgt_descs::ltd_tgts_size, OBD_FREE_PTR, and TGT_PTRS.
Referenced by lod_device_fini().
void lod_fix_desc (struct lov_desc * desc)
Used to fix insane default striping.
Parameters:
[in] desc striping description
Definition at line 1263 of file lod_lov.c.
References lov_desc::ld_default_stripe_count, lov_desc::ld_default_stripe_size, lov_desc::ld_pattern, lov_desc::ld_qos_maxage, lod_fix_desc_pattern(), lod_fix_desc_qos_maxage(), lod_fix_desc_stripe_count(), and lod_fix_desc_stripe_size().
Referenced by lod_pools_init().
void lod_fix_desc_pattern (__u32 * val)
Definition at line 1242 of file lod_lov.c.
References LCONSOLE_WARN, and LOV_PATTERN_RAID0.
Referenced by lod_fix_desc().
void lod_fix_desc_qos_maxage (__u32 * val)
Definition at line 1251 of file lod_lov.c.
References LOV_DESC_QOS_MAXAGE_DEFAULT.
Referenced by lod_fix_desc().
void lod_fix_desc_stripe_count (__u32 * val)
Definition at line 1236 of file lod_lov.c.
Referenced by lod_fix_desc().
void lod_fix_desc_stripe_size (__u64 * val)
Definition at line 1220 of file lod_lov.c.
References LCONSOLE_INFO, LCONSOLE_WARN, LOV_DESC_STRIPE_SIZE_DEFAULT, LOV_MIN_STRIPE_SIZE, and LPU64.
Referenced by lod_fix_desc().
int lod_generate_and_set_lovea (const struct lu_env * env, struct lod_object * lo, struct thandle * th)
Make LOV EA for striped object.
Generate striping information and store it in the LOV EA of the given object. The caller must ensure nobody else is calling the function against the object concurrently. The transaction must be started. FLDB service must be running as well; it's used to map FID to the target, which is stored in LOV EA.
Parameters:
[in] env execution environment for this thread
[in] lo LOD object
[in] th transaction handle
Return values:
0 if LOV EA is stored successfully
negative error number on failure
Definition at line 636 of file lod_lov.c.
References CERROR, cfs_fail_val, cpu_to_le16, cpu_to_le32, DFID, dt_object::do_lu, dt_object_child(), ENTRY, lu_fid::f_oid, fid_to_lmm_oi(), fid_to_ostid(), lov_ost_data_v1::l_ost_gen, lov_ost_data_v1::l_ost_idx, lov_ost_data_v1::l_ost_oi, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lod_object::ldo_obj, lod_object::ldo_pattern, lod_object::ldo_pool, lod_object::ldo_released_stripenr, lod_object::ldo_stripe, lod_object::ldo_stripe_size, lod_object::ldo_stripenr, lov_mds_md_v1::lmm_layout_gen, lov_mds_md_v1::lmm_magic, lov_mds_md_v3::lmm_objects, lov_mds_md_v1::lmm_objects, lov_mds_md_v1::lmm_oi, lmm_oi_cpu_to_le(), lov_mds_md_v1::lmm_pattern, lov_mds_md_v3::lmm_pool_name, lov_mds_md_v1::lmm_stripe_count, lov_mds_md_v1::lmm_stripe_size, lu_object::lo_dev, lod2obd(), lod_ea_store_resize(), lod_env_info(), lod_fld_lookup(), lod_object_free_striping(), lod_sub_object_xattr_set(), LOV_MAGIC_V1, LOV_MAGIC_V3, lov_mds_md_size(), LOV_PATTERN_F_RELEASED, LOV_PATTERN_RAID0, lod_thread_info::lti_buf, lod_thread_info::lti_ea_store, lod_thread_info::lti_ea_store_size, lod_thread_info::lti_fid, lod_thread_info::lti_ostid, lu2lod_dev(), lu_object_fid(), LU_SEQ_RANGE_OST, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_BAD_LMMOI, OBD_FAIL_LFSCK_MULTIPLE_REF, OBD_FAIL_MDS_FLD_LOOKUP, ost_id::oi, ostid_cpu_to_le(), PFID, RETURN, strlcpy(), and XATTR_NAME_LOV.
Referenced by lod_striping_create().
int lod_get_ea (const struct lu_env * env, struct lod_object * lo, const char * name)
Get LOV EA.
Fill lti_ea_store buffer in the environment with a value for the given EA. The buffer is reallocated if the value doesn't fit.
Parameters:
[in,out] env execution environment for this thread .lti_ea_store buffer is filled with EA's value
[in] lo LOD object
[in] name name of the EA
Return values:
0 if EA is fetched successfully
negative error number on failure
Definition at line 748 of file lod_lov.c.
References dt_object_child(), dt_xattr_get(), ENTRY, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lod_object::ldo_obj, lod_ea_store_resize(), lod_env_info(), lod_thread_info::lti_buf, lod_thread_info::lti_ea_store, lod_thread_info::lti_ea_store_size, LU_BUF_NULL, RETURN, and unlikely.
Referenced by lod_get_default_lmv_ea(), lod_get_lmv_ea(), and lod_get_lov_ea().
void lod_getref (struct lod_tgt_descs * ltd)
Increase reference count on the target table.
Increase reference count on the target table usage to prevent racing with addition/deletion. Any function that expects the table to remain stationary must take a ref.
Parameters:
[in] ltd target table (lod_ost_descs or lod_mdt_descs)
Definition at line 55 of file lod_lov.c.
References lod_tgt_descs::ltd_mutex, lod_tgt_descs::ltd_refcount, and lod_tgt_descs::ltd_rw_sem.
Referenced by lod_add_device(), lod_del_device(), lod_fini_tgt(), lod_initialize_objects(), lod_obd_get_info(), lod_obd_set_info_async(), lod_object_init(), lod_pool_add(), lod_pool_remove(), lod_qos_prep_create(), lod_recovery_complete(), lod_sub_fini_all_llogs(), lod_sub_process_config(), lod_sub_stop_recovery_threads(), and lod_sync().
int lod_initialize_objects (const struct lu_env * env, struct lod_object * lo, struct lov_ost_data_v1 * objs)
Instantiate objects for stripes.
Allocate and initialize LU-objects representing the stripes. The number of the stripes (ldo_stripenr) must be initialized already. The caller must ensure nobody else is calling the function on the object at the same time. FLDB service must be running to be able to map a FID to the targets and find appropriate device representing that target.
Parameters:
[in] env execution environment for this thread
[in,out] lo LOD object
[in] objs an array of IDs to creates the objects from
Return values:
0 if the objects are instantiated successfully
negative error number on failure
Definition at line 839 of file lod_lov.c.
References DFID, dt_object::do_lu, ENTRY, fid_is_sane(), GOTO, LASSERT, LASSERTF, lu_device::ld_type, lod_object::ldo_obj, lod_object::ldo_stripe, lod_object::ldo_stripe_size, lod_object::ldo_stripenr, lod_object::ldo_stripes_allocated, le32_to_cpu, lu_object::lo_dev, lu_object::lo_header, lod_env_info(), lod_getref(), lod_device::lod_ost_descs, lod_putref(), lovea_slot_is_dummy(), lod_thread_info::lti_fid, lod_thread_info::lti_ostid, lu2lod_dev(), lu_object_find_at(), lu_object_locate(), lu_object_put(), OBD_ALLOC, OBD_FREE, OST_TGT, ostid_le_to_cpu(), ostid_to_fid(), PFID, RETURN, unlikely, and validate_lod_and_idx().
Referenced by lod_parse_striping(), and lod_use_defined_striping().
int lod_load_striping (const struct lu_env * env, struct lod_object * lo)
A generic function to initialize the stripe objects.
A protected version of lod_load_striping_locked() - load the striping information from storage, parse that and instantiate LU objects to represent the stripes. The LOD object lo supplies a pointer to the next sub-object in the LU stack so we can lock it. Also use lo to return an array of references to the newly instantiated objects.
Parameters:
[in] env execution environment for this thread
[in,out] lo LOD object, where striping is stored and which gets an array of references
Return values:
0 if parsing and object creation succeed
negative error number on failure
Definition at line 1067 of file lod_lov.c.
References dt_object_child(), dt_write_lock(), dt_write_unlock(), lod_object::ldo_obj, and lod_load_striping_locked().
Referenced by lod_ah_init(), lod_declare_attr_set(), lod_declare_object_destroy(), lod_declare_xattr_del(), lod_dir_declare_xattr_set(), lod_object_lock(), and lod_object_replace_parent_fid().
int lod_load_striping_locked (const struct lu_env * env, struct lod_object * lo)
Initialize the object representing the stripes.
Unless the stripes are initialized already, fetch LOV (for regular objects) or LMV (for directory objects) EA and call lod_parse_striping() to instantiate the objects representing the stripes.
Parameters:
[in] env execution environment for this thread
[in,out] lo LOD object
Return values:
0 if parsing and object creation succeed
negative error number on failure
Definition at line 988 of file lod_lov.c.
References buf, dt_object_child(), dt_object_exists(), ENTRY, GOTO, lu_buf::lb_buf, lu_buf::lb_len, lod_object::ldo_dir_slave_stripe, lod_object::ldo_obj, lod_object::ldo_stripe, lod_object::ldo_striping_cached, lod2lu_obj(), lod_env_info(), lod_get_lmv_ea(), lod_get_lov_ea(), lod_load_lmv_shards(), lod_parse_dir_striping(), lod_parse_striping(), lod_thread_info::lti_buf, lod_thread_info::lti_ea_store, lod_thread_info::lti_ea_store_size, lu_object_attr(), OBD_FREE_LARGE, and RETURN.
Referenced by lod_index_try(), and lod_load_striping().
int lod_parse_striping (const struct lu_env * env, struct lod_object * lo, const struct lu_buf * buf)
Instantiate objects for striping.
Parse striping information in buf and instantiate the objects representing the stripes.
Parameters:
[in] env execution environment for this thread
[in] lo LOD object
[in] buf buffer storing LOV EA to parse
Return values:
0 if parsing and objects creation succeed
negative error number on failure
Definition at line 927 of file lod_lov.c.
References ENTRY, GOTO, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lod_object::ldo_layout_gen, lod_object::ldo_pattern, lod_object::ldo_stripe_size, lod_object::ldo_stripenr, le16_to_cpu, le32_to_cpu, lov_mds_md_v1::lmm_layout_gen, lov_mds_md_v1::lmm_magic, lov_mds_md_v1::lmm_objects, lov_mds_md_v3::lmm_objects, lov_mds_md_v1::lmm_pattern, lov_mds_md_v3::lmm_pool_name, lov_mds_md_v1::lmm_stripe_count, lov_mds_md_v1::lmm_stripe_size, lod_initialize_objects(), lod_object_set_pool(), LOV_MAGIC_V1, LOV_MAGIC_V3, lov_mds_md_size(), lov_pattern, LOV_PATTERN_F_RELEASED, LOV_PATTERN_RAID0, and RETURN.
Referenced by lod_load_striping_locked().
int lod_pools_fini (struct lod_device * lod)
Release the structures describing the pools.
Parameters:
[in] lod LOD device from which we release the structures
Return values:
0 always
Definition at line 1372 of file lod_lov.c.
References CDEBUG, cfs_hash_putref(), D_INFO, ENTRY, list_for_each_entry_safe, lod2obd(), lod_ost_pool_free(), lod_pool_del(), lod_device::lod_pool_info, lod_device::lod_pool_list, lod_device::lod_pools_hash_body, lod_device::lod_qos, lod_qos::lq_rr, lod_qos_rr::lqr_pool, pool_desc::pool_list, pool_desc::pool_name, and RETURN.
Referenced by lod_device_fini(), and lod_init0().
int lod_pools_init (struct lod_device * lod, struct lustre_cfg * lcfg)
Initialize the structures used to store pools and default striping.
Parameters:
[in] lod LOD device
[in] lcfg configuration structure storing default striping.
Return values:
0 if initialization succeeds
negative error number on failure
Definition at line 1280 of file lod_lov.c.
References __swab32, CDEBUG, CERROR, cfs_hash_create(), CFS_HASH_DEFAULT, CFS_HASH_MAX_THETA, CFS_HASH_MIN_THETA, cfs_hash_putref(), class_name2obd(), D_OTHER, dt_device::dd_lu_dev, ENTRY, GOTO, HASH_POOLS_BKT_BITS, HASH_POOLS_CUR_BITS, HASH_POOLS_MAX_BITS, INIT_LIST_HEAD, LASSERT, lov_desc::ld_active_tgt_count, lod_device::lod_desc, lod_device::lod_dt_dev, lod_fix_desc(), lod_ost_pool_free(), lod_ost_pool_init(), lod_device::lod_pool_count, lod_device::lod_pool_info, lod_device::lod_pool_list, lod_device::lod_pools_hash_body, lod_device::lod_qos, lod_qos_rr_init(), lod_device::lod_sp_me, LOV_DESC_MAGIC, lod_qos::lq_dirty, lod_qos::lq_oss_list, lod_qos::lq_prio_free, lod_qos::lq_reset, lod_qos::lq_rr, lod_qos::lq_rw_sem, lod_qos::lq_threshold_rr, lod_qos_rr::lqr_dirty, lod_qos_rr::lqr_pool, lustre_cfg_buf(), LUSTRE_CFG_BUFLEN, lustre_cfg_string(), LUSTRE_SP_CLI, lustre_swab_lov_desc(), obd_device::obd_lu_dev, obd_device::obd_name, pool_hash_operations, and RETURN.
Referenced by lod_init0().
void lod_putref (struct lod_device * lod, struct lod_tgt_descs * ltd)
Decrease reference count on the target table.
Companion of lod_getref() to release a reference on the target table. If this is the last reference and the OST entry was scheduled for deletion, the descriptor is removed from the table.
Parameters:
[in] lod LOD device from which we release a reference
[in] ltd target table (lod_ost_descs or lod_mdt_descs)
Definition at line 73 of file lod_lov.c.
References CDEBUG, CERROR, cfs_bitmap_clear(), cfs_foreach_bit, D_CONFIG, INIT_LIST_HEAD, LASSERT, lov_desc::ld_active_tgt_count, list_add(), list_del(), list_for_each_entry_safe, lod2obd(), lod_device::lod_desc, lod_device::lod_ost_descs, lod_ost_pool_remove(), lod_device::lod_pool_info, lod_tgt_desc::ltd_active, lod_tgt_descs::ltd_death_row, lod_tgt_desc::ltd_exp, lod_tgt_desc::ltd_kill, lod_tgt_descs::ltd_mutex, lod_tgt_desc::ltd_reap, lod_tgt_descs::ltd_refcount, lod_tgt_descs::ltd_rw_sem, LTD_TGT, lod_tgt_descs::ltd_tgt_bitmap, lod_tgt_descs::ltd_tgtnr, lod_tgt_desc::ltd_uuid, obd_disconnect(), OBD_FREE_PTR, obd_uuid2str(), and qos_del_tgt().
Referenced by lod_add_device(), lod_del_device(), lod_fini_tgt(), lod_initialize_objects(), lod_obd_get_info(), lod_obd_set_info_async(), lod_object_init(), lod_pool_add(), lod_pool_remove(), lod_qos_prep_create(), lod_recovery_complete(), lod_sub_fini_all_llogs(), lod_sub_process_config(), lod_sub_stop_recovery_threads(), and lod_sync().
int lod_verify_striping (struct lod_device * d, const struct lu_buf * buf, bool is_from_disk)
Verify striping.
Check the validity of all fields including the magic, stripe size, stripe count, stripe offset and that the pool is present. Also check that each target index points to an existing target. The additional is_from_disk turns additional checks. In some cases zero fields are allowed (like pattern=0).
Parameters:
[in] d LOD device
[in] buf buffer with LOV EA to verify
[in] is_from_disk 0 - from user, allow some fields to be 0 1 - from disk, do not allow
Return values:
0 if the striping is valid
-EINVAL if striping is invalid
Definition at line 1097 of file lod_lov.c.
References CDEBUG, cfs_bitmap_check(), cpu_to_le32, D_IOCTL, ENTRY, GOTO, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, le16_to_cpu, le32_to_cpu, lov_user_md_v1::lmm_magic, lov_user_md_v1::lmm_pattern, lov_user_md_v3::lmm_pool_name, lov_user_md_v1::lmm_stripe_count, lov_user_md_v1::lmm_stripe_offset, lov_user_md_v1::lmm_stripe_size, lod_check_index_in_pool(), lod_find_pool(), lod_pool_putref(), LOV_MAGIC_V1_DEF, LOV_MAGIC_V3_DEF, LOV_MIN_STRIPE_SIZE, LOV_OFFSET_DEFAULT, LOV_PATTERN_RAID0, LOV_USER_MAGIC_V1, LOV_USER_MAGIC_V3, offsetof, pool_tgt_count, and RETURN.
Referenced by lod_xattr_set_lov_on_dir().
static int ltd_bitmap_resize (struct lod_tgt_descs * ltd, __u32 newsize) [static]
Expand size of target table.
When the target table is full, we have to extend the table. To do so, we allocate new memory with some reserve, move data from the old table to the new one and release memory consumed by the old table. Notice we take ltd_rw_sem exclusively to ensure atomic switch.
Parameters:
[in] ltd target table
[in] newsize new size of the table
Return values:
0 on success
-ENOMEM if reallocation failed
Definition at line 149 of file lod_lov.c.
References CDEBUG, CFS_ALLOCATE_BITMAP(), cfs_bitmap_copy(), CFS_FREE_BITMAP, D_CONFIG, ENTRY, EXIT, GOTO, lod_tgt_descs::ltd_rw_sem, lod_tgt_descs::ltd_tgt_bitmap, and lod_tgt_descs::ltd_tgts_size.
Referenced by lod_add_device().
static int validate_lod_and_idx (struct lod_device * md, __u32 idx) [static]
Verify the target index is present in the current configuration.
Parameters:
[in] md LOD device where the target table is stored
[in] idx target's index
Return values:
0 if the index is present
-EINVAL if not
Definition at line 799 of file lod_lov.c.
References CERROR, cfs_bitmap_check(), lod2obd(), lod_device::lod_ost_descs, ltd_ost, lod_tgt_descs::ltd_tgts_size, OST_TGT, and unlikely.
Referenced by lod_initialize_objects().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.