Lustre: lustre/lod/lod_object.c File Reference
lustre/lod/lod_object.c File Reference
#include <obd.h>
#include <obd_class.h>
#include <obd_support.h>
#include <lustre_fid.h>
#include <lustre_linkea.h>
#include <lustre_lmv.h>
#include <lustre_param.h>
#include <lustre_swab.h>
#include <lustre_ver.h>
#include <lprocfs_status.h>
#include <md_object.h>
#include "lod_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_MDS
#define LOD_CHECK_IT(env, it)
#define LOD_CHECK_STRIPED_IT(env, it, lo)
#define ll_do_div64(aaa, bbb) do_div((aaa), (bbb))
Functions
static int lod_index_lookup (const struct lu_env *env, struct dt_object *dt, struct dt_rec *rec, const struct dt_key *key)
Implementation of dt_index_operations::dio_lookup.
static int lod_declare_index_insert (const struct lu_env *env, struct dt_object *dt, const struct dt_rec *rec, const struct dt_key *key, struct thandle *th)
Implementation of dt_index_operations::dio_declare_insert.
static int lod_index_insert (const struct lu_env *env, struct dt_object *dt, const struct dt_rec *rec, const struct dt_key *key, struct thandle *th, int ign)
Implementation of dt_index_operations::dio_insert.
static int lod_declare_index_delete (const struct lu_env *env, struct dt_object *dt, const struct dt_key *key, struct thandle *th)
Implementation of dt_index_operations::dio_declare_delete.
static int lod_index_delete (const struct lu_env *env, struct dt_object *dt, const struct dt_key *key, struct thandle *th)
Implementation of dt_index_operations::dio_delete.
static struct dt_it * lod_it_init (const struct lu_env *env, struct dt_object *dt, __u32 attr)
Implementation of dt_it_ops::init.
static void lod_it_fini (const struct lu_env *env, struct dt_it *di)
Implementation of dt_index_operations::dio_it.fini.
static int lod_it_get (const struct lu_env *env, struct dt_it *di, const struct dt_key *key)
Implementation of dt_it_ops::get.
static void lod_it_put (const struct lu_env *env, struct dt_it *di)
Implementation of dt_it_ops::put.
static int lod_it_next (const struct lu_env *env, struct dt_it *di)
Implementation of dt_it_ops::next.
static struct dt_key * lod_it_key (const struct lu_env *env, const struct dt_it *di)
Implementation of dt_it_ops::key.
static int lod_it_key_size (const struct lu_env *env, const struct dt_it *di)
Implementation of dt_it_ops::key_size.
static int lod_it_rec (const struct lu_env *env, const struct dt_it *di, struct dt_rec *rec, __u32 attr)
Implementation of dt_it_ops::rec.
static int lod_it_rec_size (const struct lu_env *env, const struct dt_it *di, __u32 attr)
Implementation of dt_it_ops::rec_size.
static __u64 lod_it_store (const struct lu_env *env, const struct dt_it *di)
Implementation of dt_it_ops::store.
static int lod_it_load (const struct lu_env *env, const struct dt_it *di, __u64 hash)
Implementation of dt_it_ops::load.
static int lod_it_key_rec (const struct lu_env *env, const struct dt_it *di, void *key_rec)
Implementation of dt_it_ops::key_rec.
static struct dt_it * lod_striped_it_init (const struct lu_env *env, struct dt_object *dt, __u32 attr)
Implementation of dt_it_ops::init.
static void lod_striped_it_fini (const struct lu_env *env, struct dt_it *di)
Implementation of dt_it_ops::fini.
static int lod_striped_it_get (const struct lu_env *env, struct dt_it *di, const struct dt_key *key)
Implementation of dt_it_ops::get.
static void lod_striped_it_put (const struct lu_env *env, struct dt_it *di)
Implementation of dt_it_ops::put.
static int lod_striped_it_next (const struct lu_env *env, struct dt_it *di)
Implementation of dt_it_ops::next.
static struct dt_key * lod_striped_it_key (const struct lu_env *env, const struct dt_it *di)
Implementation of dt_it_ops::key.
static int lod_striped_it_key_size (const struct lu_env *env, const struct dt_it *di)
Implementation of dt_it_ops::key_size.
static int lod_striped_it_rec (const struct lu_env *env, const struct dt_it *di, struct dt_rec *rec, __u32 attr)
Implementation of dt_it_ops::rec.
static int lod_striped_it_rec_size (const struct lu_env *env, const struct dt_it *di, __u32 attr)
Implementation of dt_it_ops::rec_size.
static __u64 lod_striped_it_store (const struct lu_env *env, const struct dt_it *di)
Implementation of dt_it_ops::store.
static int lod_striped_it_load (const struct lu_env *env, const struct dt_it *di, __u64 hash)
Implementation of dt_it_ops::load.
int lod_load_lmv_shards (const struct lu_env *env, struct lod_object *lo, struct lu_buf *buf, bool resize)
Append the FID for each shard of the striped directory after the given LMV EA header.
static int lod_index_try (const struct lu_env *env, struct dt_object *dt, const struct dt_index_features *feat)
Implementation of dt_object_operations::do_index_try.
static void lod_object_read_lock (const struct lu_env *env, struct dt_object *dt, unsigned role)
Implementation of dt_object_operations::do_read_lock.
static void lod_object_write_lock (const struct lu_env *env, struct dt_object *dt, unsigned role)
Implementation of dt_object_operations::do_write_lock.
static void lod_object_read_unlock (const struct lu_env *env, struct dt_object *dt)
Implementation of dt_object_operations::do_read_unlock.
static void lod_object_write_unlock (const struct lu_env *env, struct dt_object *dt)
Implementation of dt_object_operations::do_write_unlock.
static int lod_object_write_locked (const struct lu_env *env, struct dt_object *dt)
Implementation of dt_object_operations::do_write_locked.
static int lod_attr_get (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr)
Implementation of dt_object_operations::do_attr_get.
static int lod_declare_attr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_attr *attr, struct thandle *th)
Implementation of dt_object_operations::do_declare_attr_set.
static int lod_attr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_attr *attr, struct thandle *th)
Implementation of dt_object_operations::do_attr_set.
static int lod_xattr_get (const struct lu_env *env, struct dt_object *dt, struct lu_buf *buf, const char *name)
Implementation of dt_object_operations::do_xattr_get.
static int lod_verify_md_striping (struct lod_device *lod, const struct lmv_user_md_v1 *lum)
Verify LVM EA.
static void lod_prep_slave_lmv_md (struct lmv_mds_md_v1 *slave_lmv, const struct lmv_mds_md_v1 *master_lmv)
Initialize LMV EA for a slave.
static int lod_prep_lmv_md (const struct lu_env *env, struct dt_object *dt, struct lu_buf *lmv_buf)
Generate LMV EA.
int lod_parse_dir_striping (const struct lu_env *env, struct lod_object *lo, const struct lu_buf *buf)
Create in-core represenation for a striped directory.
static int lod_dir_declare_create_stripes (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_object_format *dof, struct thandle *th)
Declare create a striped directory.
static int lod_prep_md_striped_create (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, const struct lmv_user_md_v1 *lum, struct dt_object_format *dof, struct thandle *th)
static int lod_declare_xattr_set_lmv (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, const struct lu_buf *lum_buf, struct dt_object_format *dof, struct thandle *th)
Declare create striped md object.
static int lod_dir_declare_xattr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, const char *name, int fl, struct thandle *th)
Implementation of dt_object_operations::do_declare_xattr_set.
static int lod_object_replace_parent_fid (const struct lu_env *env, struct dt_object *dt, struct thandle *th, bool declare)
Reset parent FID on OST object.
static int lod_declare_xattr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, const char *name, int fl, struct thandle *th)
Implementation of dt_object_operations::do_declare_xattr_set.
static void lod_lov_stripe_cache_clear (struct lod_object *lo)
Resets cached default striping in the object.
static int lod_xattr_set_internal (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, const char *name, int fl, struct thandle *th)
Apply xattr changes to the object.
static int lod_xattr_del_internal (const struct lu_env *env, struct dt_object *dt, const char *name, struct thandle *th)
Delete an extended attribute.
static int lod_xattr_set_lov_on_dir (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, const char *name, int fl, struct thandle *th)
Set default striping on a directory.
static int lod_xattr_set_default_lmv_on_dir (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, const char *name, int fl, struct thandle *th)
Set default striping on a directory object.
static int lod_xattr_set_lmv (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, const char *name, int fl, struct thandle *th)
Turn directory into a striped directory.
static int lod_dir_striping_create_internal (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_object_format *dof, struct thandle *th, bool declare)
Helper function to declare/execute creation of a striped directory.
static int lod_declare_dir_striping_create (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_object_format *dof, struct thandle *th)
static int lod_dir_striping_create (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_object_format *dof, struct thandle *th)
static int lod_xattr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, const char *name, int fl, struct thandle *th)
Implementation of dt_object_operations::do_xattr_set.
static int lod_declare_xattr_del (const struct lu_env *env, struct dt_object *dt, const char *name, struct thandle *th)
Implementation of dt_object_operations::do_declare_xattr_del.
static int lod_xattr_del (const struct lu_env *env, struct dt_object *dt, const char *name, struct thandle *th)
Implementation of dt_object_operations::do_xattr_del.
static int lod_xattr_list (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf)
Implementation of dt_object_operations::do_xattr_list.
int lod_object_set_pool (struct lod_object *o, char *pool)
Initialize a pool the object belongs to.
static int lod_object_will_be_striped (int is_reg, const struct lu_fid *fid)
static int lod_cache_parent_lov_striping (const struct lu_env *env, struct lod_object *lp)
Cache default regular striping in the object.
static int lod_cache_parent_lmv_striping (const struct lu_env *env, struct lod_object *lp)
Cache default directory striping in the object.
static int lod_cache_parent_striping (const struct lu_env *env, struct lod_object *lp, umode_t child_mode)
Cache default striping in the object.
static void lod_ah_init (const struct lu_env *env, struct dt_allocation_hint *ah, struct dt_object *parent, struct dt_object *child, umode_t child_mode)
Implementation of dt_object_operations::do_ah_init.
static int lod_declare_init_size (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Size initialization on late striping.
int lod_declare_striped_object (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, const struct lu_buf *lovea, struct thandle *th)
Declare creation of striped object.
static int lod_declare_object_create (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *th)
Implementation of dt_object_operations::do_declare_create.
int lod_striping_create (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_object_format *dof, struct thandle *th)
Creation of a striped regular object.
static int lod_object_create (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *th)
Implementation of dt_object_operations::do_create.
static int lod_declare_object_destroy (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Implementation of dt_object_operations::do_declare_destroy.
static int lod_object_destroy (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Implementation of dt_object_operations::do_destroy.
static int lod_declare_ref_add (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Implementation of dt_object_operations::do_declare_ref_add.
static int lod_ref_add (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Implementation of dt_object_operations::do_ref_add.
static int lod_declare_ref_del (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Implementation of dt_object_operations::do_declare_ref_del.
static int lod_ref_del (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Implementation of dt_object_operations::do_ref_del.
static int lod_object_sync (const struct lu_env *env, struct dt_object *dt, __u64 start, __u64 end)
Implementation of dt_object_operations::do_object_sync.
static int lod_object_unlock_internal (const struct lu_env *env, struct dt_object *dt, struct ldlm_enqueue_info *einfo, union ldlm_policy_data *policy)
Release LDLM locks on the stripes of a striped directory.
static int lod_object_unlock (const struct lu_env *env, struct dt_object *dt, struct ldlm_enqueue_info *einfo, union ldlm_policy_data *policy)
Implementation of dt_object_operations::do_object_unlock.
static int lod_object_lock (const struct lu_env *env, struct dt_object *dt, struct lustre_handle *lh, struct ldlm_enqueue_info *einfo, union ldlm_policy_data *policy)
Implementation of dt_object_operations::do_object_lock.
static ssize_t lod_read (const struct lu_env *env, struct dt_object *dt, struct lu_buf *buf, loff_t *pos)
Implementation of dt_body_operations::dbo_read.
static ssize_t lod_declare_write (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, loff_t pos, struct thandle *th)
Implementation of dt_body_operations::dbo_declare_write.
static ssize_t lod_write (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, loff_t *pos, struct thandle *th, int iq)
Implementation of dt_body_operations::dbo_write.
static int lod_declare_punch (const struct lu_env *env, struct dt_object *dt, __u64 start, __u64 end, struct thandle *th)
static int lod_punch (const struct lu_env *env, struct dt_object *dt, __u64 start, __u64 end, struct thandle *th)
static int lod_object_init (const struct lu_env *env, struct lu_object *lo, const struct lu_object_conf *conf)
Implementation of lu_object_operations::loo_object_init.
void lod_object_free_striping (const struct lu_env *env, struct lod_object *lo)
Release resources associated with striping.
static int lod_object_start (const struct lu_env *env, struct lu_object *o)
Implementation of lu_object_operations::loo_object_start.
static void lod_object_free (const struct lu_env *env, struct lu_object *o)
Implementation of lu_object_operations::loo_object_free.
static void lod_object_release (const struct lu_env *env, struct lu_object *o)
Implementation of lu_object_operations::loo_object_release.
static int lod_object_print (const struct lu_env *env, void *cookie, lu_printer_t p, const struct lu_object *l)
Implementation of lu_object_operations::loo_object_print.
Variables
static const char dot [] = "."
static const char dotdot [] = ".."
static struct dt_body_operations lod_body_lnk_ops
static struct dt_body_operations lod_body_ops
static struct dt_index_operations lod_index_ops
static struct dt_index_operations lod_striped_index_ops
struct dt_object_operations lod_obj_ops
struct lu_object_operations lod_lu_obj_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 41 of file lod_object.c.
#define ll_do_div64 (aaa, bbb) do_div((aaa), (bbb))
Definition at line 3258 of file lod_object.c.
Referenced by lod_declare_init_size().
#define LOD_CHECK_IT (env, it)
Value:
do {                                                            \
        LASSERT((it)->lit_obj != NULL);                         \
        LASSERT((it)->lit_it != NULL);                          \
} while (0)
Definition at line 176 of file lod_object.c.
Referenced by lod_it_fini(), lod_it_get(), lod_it_key(), lod_it_key_rec(), lod_it_key_size(), lod_it_load(), lod_it_next(), lod_it_put(), lod_it_rec(), lod_it_rec_size(), and lod_it_store().
#define LOD_CHECK_STRIPED_IT (env, it, lo)
Value:
do {                                                            \
        LASSERT((it)->lit_obj != NULL);                         \
        LASSERT((it)->lit_it != NULL);                          \
        LASSERT((lo)->ldo_stripenr > 0);                        \
        LASSERT((it)->lit_stripe_index < (lo)->ldo_stripenr);   \
} while (0)
Definition at line 422 of file lod_object.c.
Referenced by lod_striped_it_fini(), lod_striped_it_get(), lod_striped_it_key(), lod_striped_it_key_size(), lod_striped_it_load(), lod_striped_it_next(), lod_striped_it_put(), lod_striped_it_rec(), lod_striped_it_rec_size(), and lod_striped_it_store().
Function Documentation
static void lod_ah_init (const struct lu_env * env, struct dt_allocation_hint * ah, struct dt_object * parent, struct dt_object * child, umode_t child_mode) [static]
Implementation of dt_object_operations::do_ah_init.
This method is used to make a decision on the striping configuration for the object being created. It can be taken from the parent object if it exists, or filesystem's default. The resulting configuration (number of stripes, stripe size/offset, pool name, etc) is stored in the object itself and will be used by the methods like ->doo_declare_create().
See also:
dt_object_operations::do_ah_init() in the API description for details.
Definition at line 3075 of file lod_object.c.
References CDEBUG, D_INFO, D_OTHER, dt_allocation_hint::dah_eadata, dt_allocation_hint::dah_eadata_len, dt_object_operations::do_ah_init, dt_object::do_lu, dt_object::do_ops, dt_object_child(), dt_object_exists(), ENTRY, EXIT, LASSERT, lov_desc::ld_default_stripe_count, lov_desc::ld_default_stripe_size, lod_object::ldo_def_stripe_offset, lod_object::ldo_def_stripe_size, lod_object::ldo_def_stripenr, lod_object::ldo_def_striping_cached, lod_object::ldo_def_striping_set, lod_object::ldo_dir_slave_stripe, lod_object::ldo_dir_stripe, lod_object::ldo_pool, lod_object::ldo_stripe, lod_object::ldo_stripe_size, lod_object::ldo_stripenr, le32_to_cpu, likely, lu_object::lo_dev, lod_cache_parent_striping(), lod_device::lod_desc, lod_dt_obj(), lod_load_striping(), lod_lov_stripe_cache_clear(), lod_object_set_pool(), lod_object_will_be_striped(), lod_verify_md_striping(), LOV_OFFSET_DEFAULT, lu2lod_dev(), lu_object_fid(), lmv_user_md_v1::lum_hash_type, lmv_user_md_v1::lum_stripe_count, lmv_user_md_v1::lum_stripe_offset, OBD_ALLOC_PTR, OBD_FAIL_CHECK, and OBD_FAIL_LARGE_STRIPE.
static int lod_attr_get (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr) [static]
Implementation of dt_object_operations::do_attr_get.
See also:
dt_object_operations::do_attr_get() in the API description for details.
Definition at line 1056 of file lod_object.c.
References dt_attr_get(), and dt_object_child().
static int lod_attr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_attr * attr, struct thandle * th) [static]
Implementation of dt_object_operations::do_attr_set.
If the object is striped, then apply the changes to all or subset of the stripes depending on the object type and specific attributes.
See also:
dt_object_operations::do_attr_set() in the API description for details.
Definition at line 1167 of file lod_object.c.
References buf, dt_object::do_lu, dt_object_child(), dt_object_exists(), dt_object_remote(), ENTRY, lu_fid::f_oid, fid_to_ostid(), lov_ost_data_v1::l_ost_idx, lov_ost_data_v1::l_ost_oi, LA_ATIME, LA_CTIME, LA_FLAGS, LA_GID, lu_attr::la_mode, LA_MODE, LA_MTIME, LA_UID, lu_attr::la_valid, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lod_object::ldo_stripe, lod_object::ldo_stripenr, le32_to_cpu, lov_mds_md_v1::lmm_magic, lov_mds_md_v1::lmm_objects, lu_object::lo_header, lod_dt_obj(), lod_env_info(), lod_get_lov_ea(), lod_sub_object_attr_set(), lod_sub_object_xattr_del(), lod_sub_object_xattr_set(), lu_object_header::loh_attr, LOV_MAGIC_V1, lod_thread_info::lti_buf, lod_thread_info::lti_ea_store, lod_thread_info::lti_ea_store_size, lod_thread_info::lti_fid, lod_thread_info::lti_ostid, LU_XATTR_REPLACE, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_BAD_OWNER, OBD_FAIL_LFSCK_CHANGE_STRIPE, OBD_FAIL_LFSCK_LOST_STRIPE, ost_id::oi, ostid_cpu_to_le(), ostid_le_to_cpu(), ostid_to_fid(), RETURN, unlikely, and XATTR_NAME_LOV.
static int lod_cache_parent_lmv_striping (const struct lu_env * env, struct lod_object * lp) [static]
Cache default directory striping in the object.
To improve performance of striped directory creation we cache default directory striping (if it exists) in the parent directory object.
Parameters:
[in] env execution environment
[in] lp object
Return values:
0 on success
negative if failed
Definition at line 2981 of file lod_object.c.
References dt_object_child(), dt_write_lock(), dt_write_unlock(), ENTRY, EXIT, GOTO, lod_object::ldo_obj, le32_to_cpu, LMV_HASH_TYPE_FNV_1A_64, lmv_user_md, lod_env_info(), lod_get_default_lmv_ea(), lod_thread_info::lti_ea_store, lmv_user_md_v1::lum_hash_type, lmv_user_md_v1::lum_stripe_count, and lmv_user_md_v1::lum_stripe_offset.
Referenced by lod_cache_parent_striping().
static int lod_cache_parent_lov_striping (const struct lu_env * env, struct lod_object * lp) [static]
Cache default regular striping in the object.
To improve performance of striped regular object creation we cache default LOV striping (if it exists) in the parent directory object.
Parameters:
[in] env execution environment
[in] lp object
Return values:
0 on success
negative if failed
Definition at line 2905 of file lod_object.c.
References __swab32, CDEBUG, D_INFO, DFID, dt_object::do_lu, dt_object_child(), dt_write_lock(), dt_write_unlock(), ENTRY, EXIT, GOTO, lod_object::ldo_def_stripe_offset, lod_object::ldo_def_stripe_size, lod_object::ldo_def_stripenr, lod_object::ldo_def_striping_cached, lod_object::ldo_def_striping_set, lod_object::ldo_obj, lov_user_md_v1::lmm_magic, lov_user_md_v1::lmm_pattern, lov_user_md_v3::lmm_pool_name, lov_user_md_v1::lmm_stripe_count, lov_user_md_v1::lmm_stripe_offset, lov_user_md_v1::lmm_stripe_size, lod_env_info(), lod_get_lov_ea(), lod_object_set_pool(), LOV_MAGIC_V1, LOV_MAGIC_V3, LOV_PATTERN_RAID0, LOV_USER_MAGIC_V1, LOV_USER_MAGIC_V3, lov_user_md, lod_thread_info::lti_ea_store, lu_object_fid(), lustre_swab_lov_user_md_v1(), lustre_swab_lov_user_md_v3(), and PFID.
Referenced by lod_cache_parent_striping().
static int lod_cache_parent_striping (const struct lu_env * env, struct lod_object * lp, umode_t child_mode) [static]
Cache default striping in the object.
To improve performance of striped object creation we cache default striping (if it exists) in the parent directory object. We always cache default striping for the regular files (stored in LOV EA) and we cache default striping for the directories if requested by child_mode (when a new directory is being created).
Parameters:
[in] env execution environment
[in] lp object
[in] child_mode new object's mode
Return values:
0 on success
negative if failed
Definition at line 3038 of file lod_object.c.
References dt_object_remote(), ENTRY, lod_object::ldo_def_striping_cached, lod_object::ldo_obj, lod_cache_parent_lmv_striping(), lod_cache_parent_lov_striping(), and RETURN.
Referenced by lod_ah_init().
static int lod_declare_attr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_attr * attr, struct thandle * th) [static]
Implementation of dt_object_operations::do_declare_attr_set.
If the object is striped, then apply the changes to all the stripes.
See also:
dt_object_operations::do_declare_attr_set() in the API description for details.
Definition at line 1075 of file lod_object.c.
References buf, dt_object::do_lu, dt_object_child(), dt_object_exists(), dt_object_remote(), ENTRY, LA_ATIME, LA_CTIME, LA_FLAGS, LA_GID, lu_attr::la_mode, LA_MODE, LA_MTIME, LA_UID, lu_attr::la_valid, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lod_object::ldo_stripe, lod_object::ldo_stripenr, lu_object::lo_header, lod_dt_obj(), lod_env_info(), lod_load_striping(), lod_sub_object_declare_attr_set(), lod_sub_object_declare_xattr_del(), lod_sub_object_declare_xattr_set(), lu_object_header::loh_attr, lod_thread_info::lti_buf, lod_thread_info::lti_ea_store, lod_thread_info::lti_ea_store_size, LU_XATTR_REPLACE, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_BAD_OWNER, OBD_FAIL_LFSCK_CHANGE_STRIPE, OBD_FAIL_LFSCK_LOST_STRIPE, RETURN, and XATTR_NAME_LOV.
static int lod_declare_dir_striping_create (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, struct dt_object_format * dof, struct thandle * th) [static]
Definition at line 2651 of file lod_object.c.
References lod_dir_striping_create_internal().
Referenced by lod_declare_object_create().
static int lod_declare_index_delete (const struct lu_env * env, struct dt_object * dt, const struct dt_key * key, struct thandle * th) [static]
Implementation of dt_index_operations::dio_declare_delete.
Used with regular (non-striped) objects.
See also:
dt_index_operations::dio_declare_delete() in the API description for details.
Definition at line 122 of file lod_object.c.
References dt_object_child(), and lod_sub_object_declare_delete().
static int lod_declare_index_insert (const struct lu_env * env, struct dt_object * dt, const struct dt_rec * rec, const struct dt_key * key, struct thandle * th) [static]
Implementation of dt_index_operations::dio_declare_insert.
Used with regular (non-striped) objects.
See also:
dt_index_operations::dio_declare_insert() in the API description for details.
Definition at line 86 of file lod_object.c.
References dt_object_child(), and lod_sub_object_declare_insert().
static int lod_declare_init_size (const struct lu_env * env, struct dt_object * dt, struct thandle * th) [static]
Size initialization on late striping.
Propagate the size of a truncated object to a deferred striping. This function handles a special case when truncate was done on a non-striped object and now while the striping is being created we can't lose that size, so we have to propagate it to the stripes being created.
Parameters:
[in] env execution environment
[in] dt object
[in] th transaction handle
Return values:
0 on success
negative if failed
Definition at line 3275 of file lod_object.c.
References __u64, dt_attr_get(), dt_object_child(), ENTRY, lu_attr::la_size, LA_SIZE, lu_attr::la_valid, LASSERT, lod_object::ldo_stripe, lod_object::ldo_stripe_size, lod_object::ldo_stripenr, ll_do_div64, lod_dt_obj(), lod_env_info(), lod_sub_object_declare_attr_set(), lod_thread_info::lti_attr, RETURN, and size.
Referenced by lod_declare_striped_object().
static int lod_declare_object_create (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof, struct thandle * th) [static]
Implementation of dt_object_operations::do_declare_create.
The method declares creation of a new object. If the object will be striped, then helper functions are called to find FIDs for the stripes, declare creation of the stripes and declare initialization of the striping information to be stored in the master object.
See also:
dt_object_operations::do_declare_create() in the API description for details.
Definition at line 3407 of file lod_object.c.
References cfs_foreach_bit, dt_allocation_hint::dah_eadata, dt_allocation_hint::dah_parent, DFT_DIR, DFT_REGULAR, DFT_SYM, dt_object::do_body_ops, dt_object::do_lu, dt_object_format::dof_reg, dt_object_format::dof_type, dt_object_child(), dt_object_remote(), ENTRY, GOTO, LASSERT, lu_device::ld_site, lod_object::ldo_dir_stripe, lod_object::ldo_obj, lod_object::ldo_stripenr, lu_object::lo_dev, lod_body_lnk_ops, lod_body_ops, lod_declare_dir_striping_create(), lod_declare_striped_object(), lod_dt_obj(), lod_device::lod_mdt_descs, lod_sub_object_declare_create(), lod_tgt_desc::ltd_index, LTD_TGT, lod_tgt_descs::ltd_tgt_bitmap, lu2lod_dev(), lu_site2seq(), OBD_FAIL_CHECK, OBD_FAIL_MDS_STALE_DIR_LAYOUT, RETURN, seq_server_site::ss_node_id, and dt_object_format::u.
static int lod_declare_object_destroy (const struct lu_env * env, struct dt_object * dt, struct thandle * th) [static]
Implementation of dt_object_operations::do_declare_destroy.
If the object is a striped directory, then the function declares reference removal from the master object (this is an index) to the stripes and declares destroy of all the stripes. In all the cases, it declares an intention to destroy the object itself.
See also:
dt_object_operations::do_declare_destroy() in the API description for details.
Definition at line 3600 of file lod_object.c.
References DFID, dt_object_operations::do_index_try, dt_object::do_lu, dt_object::do_ops, dt_directory_features, dt_key, dt_object_child(), ENTRY, lod_object::ldo_stripe, lod_object::ldo_stripenr, lu_object::lo_header, lod_dt_obj(), lod_env_info(), lod_load_striping(), lod_sub_object_declare_delete(), lod_sub_object_declare_destroy(), lod_sub_object_declare_ref_del(), lu_object_header::loh_attr, lod_thread_info::lti_key, lu_object_fid(), OBD_FAIL_CHECK, OBD_FAIL_LFSCK_LOST_MDTOBJ, PFID, and RETURN.
static int lod_declare_punch (const struct lu_env * env, struct dt_object * dt, __u64 start, __u64 end, struct thandle * th) [static]
Definition at line 4051 of file lod_object.c.
References dt_object_child(), dt_object_remote(), and lod_sub_object_declare_punch().
static int lod_declare_ref_add (const struct lu_env * env, struct dt_object * dt, struct thandle * th) [static]
Implementation of dt_object_operations::do_declare_ref_add.
See also:
dt_object_operations::do_declare_ref_add() in the API description for details.
Definition at line 3754 of file lod_object.c.
References dt_object_child(), and lod_sub_object_declare_ref_add().
static int lod_declare_ref_del (const struct lu_env * env, struct dt_object * dt, struct thandle * th) [static]
Implementation of dt_object_operations::do_declare_ref_del.
See also:
dt_object_operations::do_declare_ref_del() in the API description for details.
Definition at line 3777 of file lod_object.c.
References dt_object_child(), and lod_sub_object_declare_ref_del().
int lod_declare_striped_object (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, const struct lu_buf * lovea, struct thandle * th)
Declare creation of striped object.
The function declares creation stripes for a regular object. The function also declares whether the stripes will be created with non-zero size if previously size was set non-zero on the master object. If object dt is not local, then only fully defined striping can be applied in lovea. Otherwise lovea can be in the form of pattern, see lod_qos_parse_config() for the details.
Parameters:
[in] env execution environment
[in] dt object
[in] attr attributes the stripes will be created with
[in] lovea a buffer containing striping description
[in] th transaction handle
Return values:
0 on success
negative if failed
Definition at line 3337 of file lod_object.c.
References dt_object_child(), dt_object_exists(), dt_object_remote(), ENTRY, GOTO, LASSERT, lu_buf::lb_len, lod_object::ldo_pool, lod_object::ldo_stripenr, lod_declare_init_size(), lod_dt_obj(), lod_env_info(), lod_object_free_striping(), lod_qos_prep_create(), lod_sub_object_declare_xattr_set(), LOV_MAGIC_V1, LOV_MAGIC_V3, lov_mds_md_size(), lod_thread_info::lti_buf, OBD_FAIL_CHECK, OBD_FAIL_MDS_ALLOC_OBDO, RETURN, and XATTR_NAME_LOV.
Referenced by lod_declare_object_create(), and lod_declare_xattr_set().
static ssize_t lod_declare_write (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, loff_t pos, struct thandle * th) [static]
Implementation of dt_body_operations::dbo_declare_write.
See also:
dt_body_operations::dbo_declare_write() in the API description for details.
Definition at line 4030 of file lod_object.c.
References dt_object_child(), and lod_sub_object_declare_write().
static int lod_declare_xattr_del (const struct lu_env * env, struct dt_object * dt, const char * name, struct thandle * th) [static]
Implementation of dt_object_operations::do_declare_xattr_del.
See also:
dt_object_operations::do_declare_xattr_del() in the API description for details.
Definition at line 2769 of file lod_object.c.
References dt_object::do_lu, dt_object_child(), ENTRY, LASSERT, lod_object::ldo_stripe, lod_object::ldo_stripenr, lu_object::lo_header, lod_dt_obj(), lod_load_striping(), lod_sub_object_declare_xattr_del(), lu_object_header::loh_attr, and RETURN.
static int lod_declare_xattr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, const char * name, int fl, struct thandle * th) [static]
Implementation of dt_object_operations::do_declare_xattr_set.
See also:
dt_object_operations::do_declare_xattr_set() in the API description for details.
the extension to the API:
declaring LOVEA requests striping creation
LU_XATTR_REPLACE means layout swap
Definition at line 2061 of file lod_object.c.
References dt_object::do_lu, dt_attr_get(), dt_object_child(), dt_object_exists(), ENTRY, lu_attr::la_mode, LA_MODE, LA_TYPE, lu_attr::la_valid, lu_object::lo_header, lod_declare_striped_object(), lod_dir_declare_xattr_set(), lod_env_info(), lod_object_replace_parent_fid(), lod_sub_object_declare_xattr_set(), lu_object_header::loh_attr, lod_thread_info::lti_attr, LU_XATTR_REPLACE, mode, RETURN, XATTR_NAME_FID, and XATTR_NAME_LOV.
static int lod_declare_xattr_set_lmv (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, const struct lu_buf * lum_buf, struct dt_object_format * dof, struct thandle * th) [static]
Declare create striped md object.
The function declares intention to create a striped directory. This is a wrapper for lod_prep_md_striped_create(). The only additional functionality is to verify pattern lum_buf is good. Check that function for the details.
Parameters:
[in] env execution environment
[in] dt object
[in] attr attributes to initialize the objects with
[in] lum_buf a pattern specifying the number of stripes and MDT to start from
[in] dof type of objects to be created
[in] th transaction handle
Return values:
0 on success
negative if failed
Definition at line 1869 of file lod_object.c.
References CDEBUG, D_INFO, dt_object::do_lu, ENTRY, GOTO, LASSERT, lu_buf::lb_buf, le32_to_cpu, lu_object::lo_dev, lod_dt_obj(), lod_object_free_striping(), lod_prep_md_striped_create(), lod_verify_md_striping(), lu2lod_dev(), lmv_user_md_v1::lum_magic, lmv_user_md_v1::lum_stripe_count, lmv_user_md_v1::lum_stripe_offset, and RETURN.
Referenced by lod_dir_striping_create_internal().
static int lod_dir_declare_create_stripes (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, struct dt_object_format * dof, struct thandle * th) [static]
Declare create a striped directory.
Declare creating a striped directory with a given stripe pattern on the specified MDTs. A striped directory is represented as a regular directory
an index listing all the stripes. The stripes point back to the master object with ".." and LinkEA. The master object gets LMV EA which identifies it as a striped directory. The function allocates FIDs for all stripes.
Parameters:
[in] env execution environment
[in] dt object
[in] attr attributes to initialize the objects with
[in] dof type of objects to be created
[in] th transaction handle
Return values:
0 on success
negative if failed
Definition at line 1558 of file lod_object.c.
References cfs_fail_val, cpu_to_le32, DFID, dt_object::do_lu, dot, dotdot, dt_key, dt_object_child(), dt_try_as_dir(), ENTRY, GOTO, lu_buf::lb_buf, lu_buf::lb_len, linkea_data::ld_buf, linkea_data::ld_leh, lod_object::ldo_stripe, lod_object::ldo_stripenr, link_ea_header::leh_len, linkea_add_buf(), linkea_data_new(), lmv_mds_md_v1::lmv_master_mdt_index, lod_dt_obj(), lod_env_info(), lod_name_get(), lod_prep_lmv_md(), lod_prep_slave_lmv_md(), lod_sub_object_declare_create(), lod_sub_object_declare_insert(), lod_sub_object_declare_ref_add(), lod_sub_object_declare_xattr_set(), lod_thread_info::lti_dt_rec, lod_thread_info::lti_key, lod_thread_info::lti_linkea_buf, lu_object_fid(), OBD_ALLOC_PTR, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_BAD_SLAVE_LMV, OBD_FAIL_LFSCK_BAD_SLAVE_NAME, OBD_FAIL_LFSCK_LOST_SLAVE_LMV, OBD_FREE_PTR, PFID, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, RETURN, XATTR_NAME_LINK, and XATTR_NAME_LMV.
Referenced by lod_prep_md_striped_create().
static int lod_dir_declare_xattr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, const char * name, int fl, struct thandle * th) [static]
Implementation of dt_object_operations::do_declare_xattr_set.
Used with regular (non-striped) objects. Basically it initializes the striping information and applies the change to all the stripes.
See also:
dt_object_operations::do_declare_xattr_set() in the API description for details.
Definition at line 1918 of file lod_object.c.
References dt_object::do_lu, dt_object_child(), ENTRY, LASSERT, lu_buf::lb_buf, lod_object::ldo_stripe, lod_object::ldo_stripenr, lu_object::lo_dev, lod_dt_obj(), lod_load_striping(), lod_sub_object_declare_xattr_set(), lod_verify_md_striping(), lu2lod_dev(), RETURN, XATTR_NAME_DEFAULT_LMV, and XATTR_NAME_LINK.
Referenced by lod_declare_xattr_set(), and lod_dir_striping_create_internal().
static int lod_dir_striping_create (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, struct dt_object_format * dof, struct thandle * th) [static]
Definition at line 2660 of file lod_object.c.
References lod_object::ldo_striping_cached, lod_dir_striping_create_internal(), and lod_dt_obj().
Referenced by lod_xattr_set().
static int lod_dir_striping_create_internal (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, struct dt_object_format * dof, struct thandle * th, bool declare) [static]
Helper function to declare/execute creation of a striped directory.
Called in declare/create object path, prepare striping for a directory and prepare defaults data striping for the objects to be created in that directory. Notice the function calls "declaration" or "execution" methods depending on declare param. This is a consequence of the current approach while we don't have natural distributed transactions: we basically execute non-local updates in the declare phase. So, the arguments for the both phases are the same and this is the reason for this function to exist.
Parameters:
[in] env execution environment
[in] dt object
[in] attr attributes the stripes will be created with
[in] dof format of stripes (see OSD API description)
[in] th transaction handle
[in] declare where to call "declare" or "execute" methods
Return values:
0 on success
negative if failed
Definition at line 2531 of file lod_object.c.
References cpu_to_le16, cpu_to_le32, ENTRY, lu_buf::lb_buf, lu_buf::lb_len, lod_object::ldo_def_stripe_offset, lod_object::ldo_def_stripe_size, lod_object::ldo_def_stripenr, lod_object::ldo_def_striping_set, lod_object::ldo_pool, lod_object::ldo_stripenr, lov_user_md_v3::lmm_magic, lov_user_md_v3::lmm_pool_name, lov_user_md_v3::lmm_stripe_count, lov_user_md_v3::lmm_stripe_offset, lov_user_md_v3::lmm_stripe_size, LMV_USER_MAGIC, LMVEA_DELETE_VALUES, lod_declare_xattr_set_lmv(), lod_dir_declare_xattr_set(), lod_dt_obj(), lod_ea_store_resize(), lod_env_info(), lod_xattr_set_default_lmv_on_dir(), lod_xattr_set_lmv(), lod_xattr_set_lov_on_dir(), LOV_USER_MAGIC_V3, LOVEA_DELETE_VALUES, lod_thread_info::lti_buf, lod_thread_info::lti_ea_store, lod_thread_info::lti_ea_store_size, lmv_user_md_v1::lum_hash_type, lmv_user_md_v1::lum_magic, lmv_user_md_v1::lum_stripe_count, lmv_user_md_v1::lum_stripe_offset, RETURN, strlcpy(), XATTR_NAME_DEFAULT_LMV, XATTR_NAME_LMV, and XATTR_NAME_LOV.
Referenced by lod_declare_dir_striping_create(), and lod_dir_striping_create().
static int lod_index_delete (const struct lu_env * env, struct dt_object * dt, const struct dt_key * key, struct thandle * th) [static]
Implementation of dt_index_operations::dio_delete.
Used with regular (non-striped) objects.
See also:
dt_index_operations::dio_delete() in the API description for details.
Definition at line 138 of file lod_object.c.
References dt_object_child(), and lod_sub_object_delete().
static int lod_index_insert (const struct lu_env * env, struct dt_object * dt, const struct dt_rec * rec, const struct dt_key * key, struct thandle * th, int ign) [static]
Implementation of dt_index_operations::dio_insert.
Used with regular (non-striped) objects
See also:
dt_index_operations::dio_insert() in the API description for details.
Definition at line 103 of file lod_object.c.
References dt_object_child(), and lod_sub_object_index_insert().
static int lod_index_lookup (const struct lu_env * env, struct dt_object * dt, struct dt_rec * rec, const struct dt_key * key) [static]
Implementation of dt_index_operations::dio_lookup.
Used with regular (non-striped) objects.
See also:
dt_index_operations::dio_lookup() in the API description for details.
Definition at line 71 of file lod_object.c.
References dt_index_operations::dio_lookup, dt_object::do_index_ops, and dt_object_child().
static int lod_index_try (const struct lu_env * env, struct dt_object * dt, const struct dt_index_features * feat) [static]
Implementation of dt_object_operations::do_index_try.
See also:
dt_object_operations::do_index_try() in the API description for details.
Definition at line 954 of file lod_object.c.
References dt_object::do_index_ops, dt_object_operations::do_index_try, dt_object::do_ops, dt_object_child(), dt_object_exists(), ENTRY, LASSERT, lod_object::ldo_stripe, lod_object::ldo_stripenr, lod_dt_obj(), lod_load_striping_locked(), and RETURN.
static void lod_it_fini (const struct lu_env * env, struct dt_it * di) [static]
Implementation of dt_index_operations::dio_it.fini.
Used with regular (non-striped) objects.
See also:
dt_index_operations::dio_it.fini() in the API description for details.
Definition at line 189 of file lod_object.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, dt_index_operations::dt_it_ops::fini, lod_it::lit_it, lod_it::lit_obj, and LOD_CHECK_IT.
static int lod_it_get (const struct lu_env * env, struct dt_it * di, const struct dt_key * key) [static]
Implementation of dt_it_ops::get.
Used with regular (non-striped) objects.
See also:
dt_it_ops::get() in the API description for details.
Definition at line 208 of file lod_object.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, dt_index_operations::dt_it_ops::get, lod_it::lit_it, lod_it::lit_obj, and LOD_CHECK_IT.
static struct dt_it* lod_it_init (const struct lu_env * env, struct dt_object * dt, __u32 attr) [static, read]
Implementation of dt_it_ops::init.
Used with regular (non-striped) objects.
See also:
dt_it_ops::init() in the API description for details.
Definition at line 153 of file lod_object.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, dt_object_child(), dt_index_operations::dt_it_ops::init, LASSERT, lod_it::lit_it, lod_it::lit_obj, lod_env_info(), and lod_thread_info::lti_it.
static struct dt_key* lod_it_key (const struct lu_env * env, const struct dt_it * di) [static, read]
Implementation of dt_it_ops::key.
Used with regular (non-striped) objects.
See also:
dt_it_ops::key() in the API description for details.
Definition at line 254 of file lod_object.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, dt_index_operations::dt_it_ops::key, lod_it::lit_it, lod_it::lit_obj, and LOD_CHECK_IT.
static int lod_it_key_rec (const struct lu_env * env, const struct dt_it * di, void * key_rec) [static]
Implementation of dt_it_ops::key_rec.
Used with regular (non-striped) objects.
See also:
dt_it_ops::rec() in the API description for details.
Definition at line 350 of file lod_object.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, dt_index_operations::dt_it_ops::key_rec, lod_it::lit_it, lod_it::lit_obj, and LOD_CHECK_IT.
static int lod_it_key_size (const struct lu_env * env, const struct dt_it * di) [static]
Implementation of dt_it_ops::key_size.
Used with regular (non-striped) objects.
See also:
dt_it_ops::key_size() in the API description for details.
Definition at line 270 of file lod_object.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, dt_index_operations::dt_it_ops::key_size, lod_it::lit_it, lod_it::lit_obj, and LOD_CHECK_IT.
static int lod_it_load (const struct lu_env * env, const struct dt_it * di, __u64 hash) [static]
Implementation of dt_it_ops::load.
Used with regular (non-striped) objects.
See also:
dt_it_ops::load() in the API description for details.
Definition at line 334 of file lod_object.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, lod_it::lit_it, lod_it::lit_obj, dt_index_operations::dt_it_ops::load, and LOD_CHECK_IT.
static int lod_it_next (const struct lu_env * env, struct dt_it * di) [static]
Implementation of dt_it_ops::next.
Used with regular (non-striped) objects
See also:
dt_it_ops::next() in the API description for details.
Definition at line 239 of file lod_object.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, lod_it::lit_it, lod_it::lit_obj, LOD_CHECK_IT, and dt_index_operations::dt_it_ops::next.
static void lod_it_put (const struct lu_env * env, struct dt_it * di) [static]
Implementation of dt_it_ops::put.
Used with regular (non-striped) objects.
See also:
dt_it_ops::put() in the API description for details.
Definition at line 224 of file lod_object.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, lod_it::lit_it, lod_it::lit_obj, LOD_CHECK_IT, and dt_index_operations::dt_it_ops::put.
static int lod_it_rec (const struct lu_env * env, const struct dt_it * di, struct dt_rec * rec, __u32 attr) [static]
Implementation of dt_it_ops::rec.
Used with regular (non-striped) objects.
See also:
dt_it_ops::rec() in the API description for details.
Definition at line 285 of file lod_object.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, lod_it::lit_it, lod_it::lit_obj, LOD_CHECK_IT, and dt_index_operations::dt_it_ops::rec.
static int lod_it_rec_size (const struct lu_env * env, const struct dt_it * di, __u32 attr) [static]
Implementation of dt_it_ops::rec_size.
Used with regular (non-striped) objects.
See also:
dt_it_ops::rec_size() in the API description for details.
Definition at line 302 of file lod_object.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, lod_it::lit_it, lod_it::lit_obj, LOD_CHECK_IT, and dt_index_operations::dt_it_ops::rec_size.
static __u64 lod_it_store (const struct lu_env * env, const struct dt_it * di) [static]
Implementation of dt_it_ops::store.
Used with regular (non-striped) objects.
See also:
dt_it_ops::store() in the API description for details.
Definition at line 319 of file lod_object.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, lod_it::lit_it, lod_it::lit_obj, LOD_CHECK_IT, and dt_index_operations::dt_it_ops::store.
int lod_load_lmv_shards (const struct lu_env * env, struct lod_object * lo, struct lu_buf * buf, bool resize)
Append the FID for each shard of the striped directory after the given LMV EA header.
To simplify striped directory and the consistency verification, we only store the LMV EA header on disk, for both master object and slave objects. When someone wants to know the whole LMV EA, such as client readdir(), we can build the entrie LMV EA on the MDT side (in RAM) via iterating the sub-directory entries that are contained in the master object of the stripe directory.
For the master object of the striped directroy, the valid name for each shard is composed of the ${shard_FID}:${shard_idx}.
There may be holes in the LMV EA if some shards' name entries are corrupted or lost.
Parameters:
[in] env pointer to the thread context
[in] lo pointer to the master object of the striped directory
[in] buf pointer to the lu_buf which will hold the LMV EA
[in] resize whether re-allocate the buffer if it is not big enough
Return values:
positive size of the LMV EA
0 for nothing to be loaded
negative error number on failure
Definition at line 776 of file lod_object.c.
References CDEBUG, CERROR, D_ERROR, D_INFO, DFID, dt_index_operations::dio_it, dt_object::do_index_ops, dt_object::do_lu, dt_object_child(), dt_try_as_dir(), ENTRY, fid_is_zero(), fid_le_to_cpu(), FID_LEN, dt_index_operations::dt_it_ops::init, lu_buf::lb_buf, lu_buf::lb_len, lod_object::ldo_obj, le16_to_cpu, le32_to_cpu, LMV_HASH_FLAG_MIGRATION, lmv_mds_md_v1::lmv_hash_type, lmv_mds_md_v1::lmv_magic, LMV_MAGIC_V1, lmv_mds_md_size(), lmv_mds_md_v1::lmv_stripe_count, lmv_mds_md_v1::lmv_stripe_fids, lu_object::lo_dev, lod2obd(), lod_env_info(), lod_device::lod_lmv_failout, lod_thread_info::lti_key, lu2lod_dev(), lu_buf_alloc(), lu_object_fid(), LUDA_64BITHASH, name, PFID, RETURN, stripes, and unlikely.
Referenced by lod_load_striping_locked(), and lod_xattr_get().
static void lod_lov_stripe_cache_clear (struct lod_object * lo) [static]
Resets cached default striping in the object.
Parameters:
[in] lo object
Definition at line 2112 of file lod_object.c.
References lod_object::ldo_def_stripe_size, lod_object::ldo_def_stripenr, lod_object::ldo_def_striping_cached, lod_object::ldo_def_striping_set, lod_object::ldo_dir_stripe, and lod_object_set_pool().
Referenced by lod_ah_init(), and lod_xattr_set_lov_on_dir().
static int lod_object_create (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof, struct thandle * th) [static]
Implementation of dt_object_operations::do_create.
If any of preceeding methods (like ->do_declare_create(), ->do_ah_init(), etc) chose to create a striped object, then this method will create the master and the stripes.
See also:
dt_object_operations::do_create() in the API description for details.
Definition at line 3567 of file lod_object.c.
References dt_object::do_lu, dt_object_format::dof_reg, dt_object_child(), ENTRY, lod_object::ldo_stripe, lu_object::lo_header, lod_dt_obj(), lod_striping_create(), lod_sub_object_create(), lu_object_header::loh_attr, RETURN, and dt_object_format::u.
static int lod_object_destroy (const struct lu_env * env, struct dt_object * dt, struct thandle * th) [static]
Implementation of dt_object_operations::do_destroy.
If the object is a striped directory, then the function removes references from the master object (this is an index) to the stripes and destroys all the stripes. In all the cases, the function destroys the object itself.
See also:
dt_object_operations::do_destroy() in the API description for details.
Definition at line 3679 of file lod_object.c.
References CDEBUG, cfs_fail_val, D_INFO, DFID, dt_object_operations::do_index_try, dt_object::do_lu, dt_object::do_ops, dt_directory_features, dt_key, dt_object_child(), dt_write_lock(), dt_write_unlock(), ENTRY, lod_object::ldo_stripe, lod_object::ldo_stripenr, likely, lu_object::lo_header, lod_dt_obj(), lod_env_info(), lod_sub_object_delete(), lod_sub_object_destroy(), lod_sub_object_ref_del(), lu_object_header::loh_attr, lod_thread_info::lti_key, lu_object_fid(), MOR_TGT_CHILD, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_LOST_MDTOBJ, OBD_FAIL_LFSCK_LOST_SPEOBJ, PFID, and RETURN.
static void lod_object_free (const struct lu_env * env, struct lu_object * o) [static]
Implementation of lu_object_operations::loo_object_free.
See also:
lu_object_operations::loo_object_free() in the API description for details.
Definition at line 4222 of file lod_object.c.
References lod_object_free_striping(), lod_object_kmem, lod_object_set_pool(), lu2lod_obj(), lu_object_fini(), and OBD_SLAB_FREE_PTR.
void lod_object_free_striping (const struct lu_env * env, struct lod_object * lo)
Release resources associated with striping.
If the object is striped (regular or directory), then release the stripe objects references and free the ldo_stripe array.
Parameters:
[in] env execution environment
[in] lo object
Definition at line 4168 of file lod_object.c.
References dt_object::do_lu, LASSERT, lod_object::ldo_dir_stripe, lod_object::ldo_pattern, lod_object::ldo_stripe, lod_object::ldo_stripenr, lod_object::ldo_stripes_allocated, lod_object::ldo_striping_cached, lu_object_put(), OBD_FREE, and OBD_FREE_PTR.
Referenced by lod_declare_striped_object(), lod_declare_xattr_set_lmv(), lod_generate_and_set_lovea(), lod_object_free(), lod_parse_dir_striping(), lod_xattr_del(), and lod_xattr_set().
static int lod_object_init (const struct lu_env * env, struct lu_object * lo, const struct lu_object_conf * conf) [static]
Implementation of lu_object_operations::loo_object_init.
The function determines the type and the index of the target device using sequence of the object's FID. Then passes control down to the corresponding device: OSD for the local objects, OSP for remote
See also:
lu_object_operations::loo_object_init() in the API description for details.
Definition at line 4095 of file lod_object.c.
References cfs_bitmap_check(), dt_device::dd_lu_dev, ENTRY, LASSERT, LBUG, lu_device::ld_ops, lu_device::ld_site, lu_device_operations::ldo_object_alloc, lu_object::lo_dev, lu_object::lo_header, lod_device::lod_child, lod_fld_lookup(), lod_getref(), lod_device::lod_mdt_descs, lod_device::lod_ost_descs, lod_putref(), lod_tgt_desc::ltd_tgt, LTD_TGT, lod_tgt_descs::ltd_tgt_bitmap, lod_tgt_descs::ltd_tgts_size, lu2lod_dev(), lu_object_add(), lu_object_fid(), LU_SEQ_RANGE_ANY, LU_SEQ_RANGE_MDT, LU_SEQ_RANGE_OST, lu_site2seq(), RETURN, seq_server_site::ss_node_id, and unlikely.
static int lod_object_lock (const struct lu_env * env, struct dt_object * dt, struct lustre_handle * lh, struct ldlm_enqueue_info * einfo, union ldlm_policy_data * policy) [static]
Implementation of dt_object_operations::do_object_lock.
Used to get LDLM lock on the non-striped and striped objects.
See also:
dt_object_operations::do_object_lock() in the API description for details.
Definition at line 3889 of file lod_object.c.
References __u64, lustre_handle_array::count, dt_object::do_lu, dt_object_child(), dt_object_lock(), dt_object_remote(), ldlm_enqueue_info::ei_cb_cp, ldlm_enqueue_info::ei_cb_local_bl, ldlm_enqueue_info::ei_cbdata, ldlm_enqueue_info::ei_enq_slave, ldlm_enqueue_info::ei_mode, ldlm_enqueue_info::ei_namespace, ENTRY, fid_build_reg_res_name(), GOTO, lustre_handle_array::handles, LASSERT, LCK_EX, LCK_PW, ldlm_cli_enqueue_local(), LDLM_FL_ATOMIC_CB, LDLM_FL_COS_INCOMPAT, LDLM_IBITS, lod_object::ldo_stripe, lod_object::ldo_stripenr, likely, lu_object::lo_header, lod_dt_obj(), lod_env_info(), lod_load_striping(), lod_object_unlock_internal(), lu_object_header::loh_attr, lod_thread_info::lti_res_id, lu_object_fid(), LVB_T_NONE, OBD_ALLOC, OBD_FREE, and RETURN.
static int lod_object_print (const struct lu_env * env, void * cookie, lu_printer_t p, const struct lu_object * l) [static]
Implementation of lu_object_operations::loo_object_print.
See also:
lu_object_operations::loo_object_print() in the API description for details.
Definition at line 4256 of file lod_object.c.
References lu2lod_obj(), and LUSTRE_LOD_NAME.
static void lod_object_read_lock (const struct lu_env * env, struct dt_object * dt, unsigned role) [static]
Implementation of dt_object_operations::do_read_lock.
See also:
dt_object_operations::do_read_lock() in the API description for details.
Definition at line 997 of file lod_object.c.
References dt_object_child(), and dt_read_lock().
static void lod_object_read_unlock (const struct lu_env * env, struct dt_object * dt) [static]
Implementation of dt_object_operations::do_read_unlock.
See also:
dt_object_operations::do_read_unlock() in the API description for details.
Definition at line 1021 of file lod_object.c.
References dt_object_child(), and dt_read_unlock().
static void lod_object_release (const struct lu_env * env, struct lu_object * o) [static]
Implementation of lu_object_operations::loo_object_release.
See also:
lu_object_operations::loo_object_release() in the API description for details.
Definition at line 4244 of file lod_object.c.
static int lod_object_replace_parent_fid (const struct lu_env * env, struct dt_object * dt, struct thandle * th, bool declare) [static]
Reset parent FID on OST object.
Replace parent FID with object FID, which is only called during migration to reset the parent FID after the MDT object is migrated to the new MDT, i.e. the FID is changed.
Parameters:
[in] env execution environment
[in] dt dt_object whose stripes's parent FID will be reset [in] th thandle
[in] declare if it is declare
Return values:
0 if reset succeeds
negative errno if reset fais
Definition at line 1987 of file lod_object.c.
References buf, dt_object::do_lu, dt_xattr_get(), ENTRY, lu_fid::f_oid, lu_fid::f_seq, filter_fid::ff_parent, fid_cpu_to_le(), fid_le_to_cpu(), LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lod_object::ldo_stripe, lod_object::ldo_stripenr, lu_object::lo_header, lod_dt_obj(), lod_ea_store_resize(), lod_env_info(), lod_load_striping(), lod_sub_object_declare_xattr_set(), lod_sub_object_xattr_set(), lu_object_header::loh_attr, lod_thread_info::lti_buf, lod_thread_info::lti_ea_store, lod_thread_info::lti_ea_store_size, lu_object_fid(), LU_XATTR_REPLACE, RETURN, and XATTR_NAME_FID.
Referenced by lod_declare_xattr_set(), and lod_xattr_set().
int lod_object_set_pool (struct lod_object * o, char * pool)
Initialize a pool the object belongs to.
When a striped object is being created, striping configuration may demand the stripes are allocated on a limited set of the targets. These limited sets are known as "pools". So we copy a pool name into the object and later actual creation methods (like lod_object_create()) will use this information to allocate the stripes properly.
Parameters:
[in] o object
[in] pool pool name
Definition at line 2868 of file lod_object.c.
References lod_object::ldo_pool, OBD_ALLOC, and OBD_FREE.
Referenced by lod_ah_init(), lod_cache_parent_lov_striping(), lod_lov_stripe_cache_clear(), lod_object_free(), lod_parse_striping(), lod_qos_parse_config(), and lod_use_defined_striping().
static int lod_object_start (const struct lu_env * env, struct lu_object * o) [static]
Implementation of lu_object_operations::loo_object_start.
See also:
lu_object_operations::loo_object_start() in the API description for details.
Definition at line 4201 of file lod_object.c.
References dt_object::do_body_ops, fid_is_local_file(), lod_object::ldo_obj, lu_object::lo_header, lu_object_header::loh_attr, lu2lod_obj(), and lu_object_fid().
static int lod_object_sync (const struct lu_env * env, struct dt_object * dt, __u64 start, __u64 end) [static]
Implementation of dt_object_operations::do_object_sync.
See also:
dt_object_operations::do_object_sync() in the API description for details.
Definition at line 3800 of file lod_object.c.
References dt_object_child(), and dt_object_sync().
static int lod_object_unlock (const struct lu_env * env, struct dt_object * dt, struct ldlm_enqueue_info * einfo, union ldlm_policy_data * policy) [static]
Implementation of dt_object_operations::do_object_unlock.
Used to release LDLM lock(s).
See also:
dt_object_operations::do_object_unlock() in the API description for details.
Definition at line 3850 of file lod_object.c.
References lustre_handle_array::count, dt_object::do_lu, dt_object_child(), dt_object_remote(), ldlm_enqueue_info::ei_cbdata, ENTRY, lustre_handle_array::handles, LASSERT, lod_object::ldo_stripenr, lu_object::lo_header, lod_dt_obj(), lu_object_header::loh_attr, lustre_handle_is_used(), OBD_FREE, and RETURN.
static int lod_object_unlock_internal (const struct lu_env * env, struct dt_object * dt, struct ldlm_enqueue_info * einfo, union ldlm_policy_data * policy) [static]
Release LDLM locks on the stripes of a striped directory.
Iterates over all the locks taken on the stripe objects and release them using ->do_object_unlock() method.
Parameters:
[in] env execution environment
[in] dt striped object
[in] einfo lock description
[in] policy data describing requested lock
Return values:
0 on success
negative if failed
Definition at line 3820 of file lod_object.c.
References lustre_handle_array::count, ldlm_enqueue_info::ei_cbdata, ldlm_enqueue_info::ei_mode, ENTRY, lustre_handle_array::handles, ldlm_lock_decref(), lustre_handle_is_used(), and RETURN.
Referenced by lod_object_lock().
static int lod_object_will_be_striped (int is_reg, const struct lu_fid * fid) [inline, static]
Definition at line 2887 of file lod_object.c.
References FID_SEQ_LOCAL_FILE.
Referenced by lod_ah_init().
static void lod_object_write_lock (const struct lu_env * env, struct dt_object * dt, unsigned role) [static]
Implementation of dt_object_operations::do_write_lock.
See also:
dt_object_operations::do_write_lock() in the API description for details.
Definition at line 1009 of file lod_object.c.
References dt_object_child(), and dt_write_lock().
static int lod_object_write_locked (const struct lu_env * env, struct dt_object * dt) [static]
Implementation of dt_object_operations::do_write_locked.
See also:
dt_object_operations::do_write_locked() in the API description for details.
Definition at line 1045 of file lod_object.c.
References dt_object_child(), and dt_write_locked().
static void lod_object_write_unlock (const struct lu_env * env, struct dt_object * dt) [static]
Implementation of dt_object_operations::do_write_unlock.
See also:
dt_object_operations::do_write_unlock() in the API description for details.
Definition at line 1033 of file lod_object.c.
References dt_object_child(), and dt_write_unlock().
int lod_parse_dir_striping (const struct lu_env * env, struct lod_object * lo, const struct lu_buf * buf)
Create in-core represenation for a striped directory.
Parse the buffer containing LMV EA and instantiate LU objects representing the stripe objects. The pointers to the objects are stored in ldo_stripe field of lo. This function is used when we need to access an already created object (i.e. load from a disk).
Parameters:
[in] env execution environment
[in] lo lod object
[in] buf buffer containing LMV EA
Return values:
0 on success
negative if failed
Definition at line 1462 of file lod_object.c.
References dt_object::do_lu, dt_locate_at(), ENTRY, fid_is_sane(), fid_le_to_cpu(), GOTO, LASSERT, lu_buf::lb_buf, lu_device::ld_site, lod_object::ldo_dir_slave_stripe, lod_object::ldo_obj, lod_object::ldo_stripe, lod_object::ldo_stripenr, lod_object::ldo_stripes_allocated, le32_to_cpu, LMV_HASH_FLAG_MIGRATION, lmv_mds_md_v1::lmv_hash_type, lmv_mds_md_v1::lmv_magic, LMV_MAGIC_STRIPE, LMV_MAGIC_V1, lmv_mds_md::lmv_md_v1, lmv_mds_md_v1::lmv_stripe_count, lmv_mds_md_v1::lmv_stripe_fids, lu_object::lo_dev, lod2lu_dev(), lod_device::lod_child, lod_env_info(), lod_fld_lookup(), lod_device::lod_mdt_descs, lod_object_free_striping(), lu_site::ls_top_dev, lod_tgt_desc::ltd_tgt, LTD_TGT, lod_thread_info::lti_fid, lu2lod_dev(), LU_SEQ_RANGE_ANY, OBD_ALLOC, and RETURN.
Referenced by lod_load_striping_locked().
static int lod_prep_lmv_md (const struct lu_env * env, struct dt_object * dt, struct lu_buf * lmv_buf) [static]
Generate LMV EA.
Generate LMV EA from the object passed as dt. The object must have the stripes created and initialized.
Parameters:
[in] env execution environment
[in] dt object
[out] lmv_buf buffer storing generated LMV EA
Return values:
0 on success
negative if failed
Definition at line 1406 of file lod_object.c.
References cpu_to_le32, dt_object::do_lu, ENTRY, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lod_object::ldo_stripenr, lmv_mds_md_v1::lmv_hash_type, LMV_MAGIC, lmv_mds_md_v1::lmv_magic, lmv_mds_md_v1::lmv_master_mdt_index, lmv_mds_md_v1::lmv_stripe_count, lu_object::lo_dev, lod_dt_obj(), lod_ea_store_resize(), lod_env_info(), lod_fld_lookup(), lod_thread_info::lti_ea_store, lod_thread_info::lti_ea_store_size, lu2lod_dev(), lu_object_fid(), LU_SEQ_RANGE_ANY, and RETURN.
Referenced by lod_dir_declare_create_stripes(), and lod_xattr_set_lmv().
static int lod_prep_md_striped_create (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, const struct lmv_user_md_v1 * lum, struct dt_object_format * dof, struct thandle * th) [static]
Definition at line 1691 of file lod_object.c.
References CDEBUG, cfs_bitmap_check(), D_INFO, DFID, dt_object::do_lu, dt_locate_at(), dt_statfs(), ENTRY, fid_is_sane(), GOTO, LASSERT, lu_device::ld_site, lod_object::ldo_stripe, lod_object::ldo_stripenr, lod_object::ldo_stripes_allocated, le32_to_cpu, likely, LMV_USER_MAGIC, lu_object::lo_dev, LOC_F_NEW, lu_object_conf::loc_flags, lod2lu_dev(), lod2obd(), lod_device::lod_child, lod_device::lod_child_exp, lod_dir_declare_create_stripes(), lod_dt_obj(), lod_device::lod_mdt_descs, lu_site::ls_top_dev, lod_tgt_desc::ltd_exp, lod_tgt_desc::ltd_tgt, LTD_TGT, lod_tgt_descs::ltd_tgt_bitmap, lu2lod_dev(), lu_object_put(), lu_site2seq(), lmv_user_md_v1::lum_magic, lmv_user_md_v1::lum_stripe_count, OBD_ALLOC, OBD_FAIL_CHECK, OBD_FAIL_LARGE_STRIPE, obd_fid_alloc(), OBD_FREE, PFID, RETURN, and seq_server_site::ss_node_id.
Referenced by lod_declare_xattr_set_lmv().
static void lod_prep_slave_lmv_md (struct lmv_mds_md_v1 * slave_lmv, const struct lmv_mds_md_v1 * master_lmv) [static]
Initialize LMV EA for a slave.
Initialize slave's LMV EA from the master's LMV EA.
Parameters:
[in] master_lmv a buffer containing master's EA
[out] slave_lmv a buffer where slave's EA will be stored
Definition at line 1386 of file lod_object.c.
References cpu_to_le32, lmv_mds_md_v1::lmv_magic, and LMV_MAGIC_STRIPE.
Referenced by lod_dir_declare_create_stripes(), and lod_xattr_set_lmv().
static int lod_punch (const struct lu_env * env, struct dt_object * dt, __u64 start, __u64 end, struct thandle * th) [static]
Definition at line 4061 of file lod_object.c.
References dt_object_child(), dt_object_remote(), and lod_sub_object_punch().
static ssize_t lod_read (const struct lu_env * env, struct dt_object * dt, struct lu_buf * buf, loff_t * pos) [static]
Implementation of dt_body_operations::dbo_read.
See also:
dt_body_operations::dbo_read() in the API description for details.
Definition at line 4017 of file lod_object.c.
References dt_body_operations::dbo_read, dt_object::do_body_ops, and dt_object_child().
static int lod_ref_add (const struct lu_env * env, struct dt_object * dt, struct thandle * th) [static]
Implementation of dt_object_operations::do_ref_add.
See also:
dt_object_operations::do_ref_add() in the API description for details.
Definition at line 3765 of file lod_object.c.
References dt_object_child(), and lod_sub_object_ref_add().
static int lod_ref_del (const struct lu_env * env, struct dt_object * dt, struct thandle * th) [static]
Implementation of dt_object_operations::do_ref_del.
See also:
dt_object_operations::do_ref_del() in the API description for details.
Definition at line 3788 of file lod_object.c.
References dt_object_child(), and lod_sub_object_ref_del().
static void lod_striped_it_fini (const struct lu_env * env, struct dt_it * di) [static]
Implementation of dt_it_ops::fini.
Used with striped objects.
See also:
dt_it_ops::fini() in the API description for details.
Definition at line 437 of file lod_object.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, dt_index_operations::dt_it_ops::fini, LASSERT, lod_object::ldo_stripe, lod_it::lit_it, lod_it::lit_obj, lod_it::lit_stripe_index, LOD_CHECK_STRIPED_IT, and lod_dt_obj().
static int lod_striped_it_get (const struct lu_env * env, struct dt_it * di, const struct dt_key * key) [static]
Implementation of dt_it_ops::get.
Right now it's not used widely, only to reset the iterator to the initial position. It should be possible to implement a full version which chooses a correct stripe to be able to position with any key.
See also:
dt_it_ops::get() in the API description for details.
Definition at line 470 of file lod_object.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, ENTRY, dt_index_operations::dt_it_ops::get, LASSERT, lod_object::ldo_stripe, lod_it::lit_it, lod_it::lit_obj, lod_it::lit_stripe_index, LOD_CHECK_STRIPED_IT, and lod_dt_obj().
static struct dt_it* lod_striped_it_init (const struct lu_env * env, struct dt_object * dt, __u32 attr) [static, read]
Implementation of dt_it_ops::init.
Used with striped objects. Internally just initializes the iterator on the first stripe.
See also:
dt_it_ops::init() in the API description for details.
Definition at line 390 of file lod_object.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, ENTRY, dt_index_operations::dt_it_ops::init, LASSERT, lod_object::ldo_stripe, lod_object::ldo_stripenr, lod_it::lit_attr, lod_it::lit_it, lod_it::lit_obj, lod_it::lit_stripe_index, lod_dt_obj(), lod_env_info(), and lod_thread_info::lti_it.
static struct dt_key* lod_striped_it_key (const struct lu_env * env, const struct dt_it * di) [static, read]
Implementation of dt_it_ops::key.
Used with striped objects.
See also:
dt_it_ops::key() in the API description for details.
Definition at line 598 of file lod_object.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, dt_index_operations::dt_it_ops::key, LASSERT, lod_object::ldo_stripe, lod_it::lit_it, lod_it::lit_obj, lod_it::lit_stripe_index, LOD_CHECK_STRIPED_IT, and lod_dt_obj().
static int lod_striped_it_key_size (const struct lu_env * env, const struct dt_it * di) [static]
Implementation of dt_it_ops::key_size.
Used with striped objects.
See also:
dt_it_ops::size() in the API description for details.
Definition at line 621 of file lod_object.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, dt_index_operations::dt_it_ops::key_size, LASSERT, lod_object::ldo_stripe, lod_it::lit_it, lod_it::lit_obj, lod_it::lit_stripe_index, LOD_CHECK_STRIPED_IT, and lod_dt_obj().
static int lod_striped_it_load (const struct lu_env * env, const struct dt_it * di, __u64 hash) [static]
Implementation of dt_it_ops::load.
Used with striped objects.
See also:
dt_it_ops::load() in the API description for details.
Definition at line 713 of file lod_object.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, LASSERT, lod_object::ldo_stripe, lod_it::lit_it, lod_it::lit_obj, lod_it::lit_stripe_index, dt_index_operations::dt_it_ops::load, LOD_CHECK_STRIPED_IT, and lod_dt_obj().
static int lod_striped_it_next (const struct lu_env * env, struct dt_it * di) [static]
Implementation of dt_it_ops::next.
Used with striped objects. When the end of the current stripe is reached, the method takes the next stripe's iterator.
See also:
dt_it_ops::next() in the API description for details.
Definition at line 517 of file lod_object.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, dt_object_operations::do_index_try, dt_object::do_ops, dt_directory_features, ENTRY, dt_index_operations::dt_it_ops::fini, dt_index_operations::dt_it_ops::init, LASSERT, lod_object::ldo_stripe, lod_object::ldo_stripenr, le16_to_cpu, lod_it::lit_attr, lod_it::lit_it, lod_it::lit_obj, lod_it::lit_stripe_index, LOD_CHECK_STRIPED_IT, lod_dt_obj(), lod_env_info(), lod_thread_info::lti_key, dt_index_operations::dt_it_ops::next, dt_index_operations::dt_it_ops::put, dt_index_operations::dt_it_ops::rec, and RETURN.
static void lod_striped_it_put (const struct lu_env * env, struct dt_it * di) [static]
Implementation of dt_it_ops::put.
Used with striped objects.
See also:
dt_it_ops::put() in the API description for details.
Definition at line 494 of file lod_object.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, LASSERT, lod_object::ldo_stripe, lod_it::lit_it, lod_it::lit_obj, lod_it::lit_stripe_index, LOD_CHECK_STRIPED_IT, lod_dt_obj(), and dt_index_operations::dt_it_ops::put.
static int lod_striped_it_rec (const struct lu_env * env, const struct dt_it * di, struct dt_rec * rec, __u32 attr) [static]
Implementation of dt_it_ops::rec.
Used with striped objects.
See also:
dt_it_ops::rec() in the API description for details.
Definition at line 644 of file lod_object.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, LASSERT, lod_object::ldo_stripe, lod_it::lit_it, lod_it::lit_obj, lod_it::lit_stripe_index, LOD_CHECK_STRIPED_IT, lod_dt_obj(), and dt_index_operations::dt_it_ops::rec.
static int lod_striped_it_rec_size (const struct lu_env * env, const struct dt_it * di, __u32 attr) [static]
Implementation of dt_it_ops::rec_size.
Used with striped objects.
See also:
dt_it_ops::rec_size() in the API description for details.
Definition at line 667 of file lod_object.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, LASSERT, lod_object::ldo_stripe, lod_it::lit_it, lod_it::lit_obj, lod_it::lit_stripe_index, LOD_CHECK_STRIPED_IT, lod_dt_obj(), and dt_index_operations::dt_it_ops::rec_size.
static __u64 lod_striped_it_store (const struct lu_env * env, const struct dt_it * di) [static]
Implementation of dt_it_ops::store.
Used with striped objects.
See also:
dt_it_ops::store() in the API description for details.
Definition at line 690 of file lod_object.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, LASSERT, lod_object::ldo_stripe, lod_it::lit_it, lod_it::lit_obj, lod_it::lit_stripe_index, LOD_CHECK_STRIPED_IT, lod_dt_obj(), and dt_index_operations::dt_it_ops::store.
int lod_striping_create (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, struct dt_object_format * dof, struct thandle * th)
Creation of a striped regular object.
The function is called to create the stripe objects for a regular striped file. This can happen at the initial object creation or when the caller asks LOD to do so using ->do_xattr_set() method (so called late striping). Notice all the information are already prepared in the form of the list of objects (ldo_stripe field). This is done during declare phase.
Parameters:
[in] env execution environment
[in] dt object
[in] attr attributes the stripes will be created with
[in] dof format of stripes (see OSD API description)
[in] th transaction handle
Return values:
0 on success
negative if failed
Definition at line 3530 of file lod_object.c.
References ENTRY, LASSERT, lod_object::ldo_stripe, lod_object::ldo_stripenr, lod_object::ldo_striping_cached, lod_dt_obj(), lod_generate_and_set_lovea(), lod_sub_object_create(), and RETURN.
Referenced by lod_object_create(), and lod_xattr_set().
static int lod_verify_md_striping (struct lod_device * lod, const struct lmv_user_md_v1 * lum) [static]
Verify LVM EA.
Checks that the magic of the stripe is sane.
Parameters:
[in] lod lod device
[in] lum a buffer storing LMV EA to verify
Return values:
0 if the EA is sane
negative otherwise
Definition at line 1362 of file lod_object.c.
References CERROR, le32_to_cpu, LMV_USER_MAGIC, lod2obd(), lmv_user_md_v1::lum_magic, lmv_user_md_v1::lum_stripe_count, lmv_user_md_v1::lum_stripe_offset, and unlikely.
Referenced by lod_ah_init(), lod_declare_xattr_set_lmv(), and lod_dir_declare_xattr_set().
static ssize_t lod_write (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, loff_t * pos, struct thandle * th, int iq) [static]
Implementation of dt_body_operations::dbo_write.
See also:
dt_body_operations::dbo_write() in the API description for details.
Definition at line 4044 of file lod_object.c.
References dt_object_child(), and lod_sub_object_write().
static int lod_xattr_del (const struct lu_env * env, struct dt_object * dt, const char * name, struct thandle * th) [static]
Implementation of dt_object_operations::do_xattr_del.
If EA storing a regular striping is being deleted, then release all the references to the stripe objects in core.
See also:
dt_object_operations::do_xattr_del() in the API description for details.
Definition at line 2813 of file lod_object.c.
References dt_object::do_lu, dt_object_child(), ENTRY, LASSERT, lod_object::ldo_stripe, lod_object::ldo_stripenr, lu_object::lo_header, lod_dt_obj(), lod_object_free_striping(), lod_sub_object_xattr_del(), lu_object_header::loh_attr, RETURN, and XATTR_NAME_LOV.
static int lod_xattr_del_internal (const struct lu_env * env, struct dt_object * dt, const char * name, struct thandle * th) [static]
Delete an extended attribute.
Deletes specified xattr from the object and the stripes if the latter exist.
Parameters:
[in] env execution environment
[in] dt object
[in] name name of xattr
[in] th transaction handle
Return values:
0 on success
negative if failed
Definition at line 2186 of file lod_object.c.
References dt_object::do_lu, dt_object_child(), ENTRY, LASSERT, lod_object::ldo_stripe, lod_object::ldo_stripenr, lu_object::lo_header, lod_dt_obj(), lod_sub_object_xattr_del(), lu_object_header::loh_attr, and RETURN.
Referenced by lod_xattr_set_default_lmv_on_dir(), and lod_xattr_set_lov_on_dir().
static int lod_xattr_get (const struct lu_env * env, struct dt_object * dt, struct lu_buf * buf, const char * name) [static]
Implementation of dt_object_operations::do_xattr_get.
If LOV EA is requested from the root object and it's not found, then return default striping for the filesystem.
See also:
dt_object_operations::do_xattr_get() in the API description for details.
Definition at line 1267 of file lod_object.c.
References CLASSERT, cpu_to_le16, cpu_to_le32, dt_object::do_lu, dt_object_child(), dt_root_get(), dt_xattr_get(), ENTRY, FID_SEQ_LOV_DEFAULT, lu_buf::lb_buf, lu_buf::lb_len, lov_desc::ld_default_stripe_count, lov_desc::ld_default_stripe_offset, lov_desc::ld_default_stripe_size, lov_desc::ld_pattern, le32_to_cpu, lmm_oi_cpu_to_le(), lmm_oi_set_id(), lmm_oi_set_seq(), lmv_mds_md_v1::lmv_magic, LMV_MAGIC_V1, lmv_mds_md_size(), lmv_mds_md_v1::lmv_stripe_count, lu_object::lo_dev, lu_object::lo_header, lod_device::lod_child, lod_device::lod_desc, lod_dt_obj(), lod_env_info(), lod_load_lmv_shards(), lu_object_header::loh_attr, LOV_USER_MAGIC_V1, lov_user_md, lod_thread_info::lti_buf, lod_thread_info::lti_fid, lod_thread_info::lti_key, lu2lod_dev(), lu_fid_eq(), lu_object_fid(), RETURN, unlikely, XATTR_NAME_LMV, and XATTR_NAME_LOV.
static int lod_xattr_list (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf) [static]
Implementation of dt_object_operations::do_xattr_list.
See also:
dt_object_operations::do_xattr_list() in the API description for details.
Definition at line 2849 of file lod_object.c.
References dt_object_child(), and dt_xattr_list().
static int lod_xattr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, const char * name, int fl, struct thandle * th) [static]
Implementation of dt_object_operations::do_xattr_set.
Sets specified extended attribute on the object. Three types of EAs are special: LOV EA - stores striping for a regular file or default striping (when set on a directory) LMV EA - stores a marker for the striped directories DMV EA - stores default directory striping
When striping is applied to a non-striped existing object (this is called late striping), then LOD notices the caller wants to turn the object into a striped one. The stripe objects are created and appropriate EA is set: LOV EA storing all the stripes directly or LMV EA storing just a small header with striping configuration.
See also:
dt_object_operations::do_xattr_set() in the API description for details.
Definition at line 2694 of file lod_object.c.
References dt_object::do_lu, dt_object_child(), dt_object_remote(), ENTRY, lu_buf::lb_buf, le32_to_cpu, LMV_HASH_FLAG_MIGRATION, lmv_mds_md_v1::lmv_hash_type, lu_object::lo_header, lod_dir_striping_create(), lod_dt_obj(), lod_object_free_striping(), lod_object_replace_parent_fid(), lod_striping_create(), lod_sub_object_xattr_set(), lod_xattr_set_default_lmv_on_dir(), lod_xattr_set_internal(), lod_xattr_set_lov_on_dir(), lu_object_header::loh_attr, LU_XATTR_REPLACE, RETURN, XATTR_NAME_DEFAULT_LMV, XATTR_NAME_FID, XATTR_NAME_LMV, and XATTR_NAME_LOV.
static int lod_xattr_set_default_lmv_on_dir (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, const char * name, int fl, struct thandle * th) [static]
Set default striping on a directory object.
Sets specified striping on a directory object unless it matches the default striping (LOVEA_DELETE_VALUES() macro). In the latter case remove existing EA. This striping will be used when a new directory is being created in the directory.
Parameters:
[in] env execution environment
[in] dt the striped object
[in] buf buffer with the striping
[in] name name of EA
[in] fl xattr flag (see OSD API description)
[in] th transaction handle
Return values:
0 on success
negative if failed
Definition at line 2305 of file lod_object.c.
References CDEBUG, D_OTHER, ENTRY, LASSERT, lu_buf::lb_buf, lod_object::ldo_dir_stripe, le32_to_cpu, LMV_USER_MAGIC, LMVEA_DELETE_VALUES, lod_dt_obj(), lod_xattr_del_internal(), lod_xattr_set_internal(), lmv_user_md_v1::lum_magic, lmv_user_md_v1::lum_stripe_count, lmv_user_md_v1::lum_stripe_offset, OBD_ALLOC_PTR, and RETURN.
Referenced by lod_dir_striping_create_internal(), and lod_xattr_set().
static int lod_xattr_set_internal (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, const char * name, int fl, struct thandle * th) [static]
Apply xattr changes to the object.
Applies xattr changes to the object and the stripes if the latter exist.
Parameters:
[in] env execution environment
[in] dt object
[in] buf buffer pointing to the new value of xattr
[in] name name of xattr
[in] fl flags
[in] th transaction handle
Return values:
0 on success
negative if failed
Definition at line 2138 of file lod_object.c.
References dt_object::do_lu, dt_object_child(), ENTRY, LASSERT, lod_object::ldo_stripe, lod_object::ldo_stripenr, lu_object::lo_header, lod_dt_obj(), lod_sub_object_xattr_set(), lu_object_header::loh_attr, RETURN, and XATTR_NAME_LINK.
Referenced by lod_xattr_set(), lod_xattr_set_default_lmv_on_dir(), and lod_xattr_set_lov_on_dir().
static int lod_xattr_set_lmv (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, const char * name, int fl, struct thandle * th) [static]
Turn directory into a striped directory.
During replay the client sends the striping created before MDT failure, then the layer above LOD sends this defined striping using ->do_xattr_set(), so LOD uses this method to replay creation of the stripes. Notice the original information for the striping (stripes, FIDs, etc) was transferred in declare path.
Parameters:
[in] env execution environment
[in] dt the striped object
[in] buf not used currently
[in] name not used currently
[in] fl xattr flag (see OSD API description)
[in] th transaction handle
Return values:
0 on success
negative if failed
Definition at line 2365 of file lod_object.c.
References cfs_fail_val, cpu_to_le32, DFID, DFT_DIR, dt_object::do_lu, dt_object_format::dof_type, dot, dotdot, dt_attr_get(), dt_key, dt_object_child(), dt_write_lock(), dt_write_unlock(), ENTRY, GOTO, LA_ATIME, LA_CTIME, LA_GID, LA_MODE, LA_MTIME, LA_TYPE, LA_UID, lu_attr::la_valid, lu_buf::lb_buf, lu_buf::lb_len, linkea_data::ld_buf, linkea_data::ld_leh, lod_object::ldo_stripe, lod_object::ldo_stripenr, link_ea_header::leh_len, linkea_add_buf(), linkea_data_new(), lmv_mds_md_v1::lmv_master_mdt_index, lu_object::lo_header, lod_dt_obj(), lod_env_info(), lod_name_get(), lod_prep_lmv_md(), lod_prep_slave_lmv_md(), lod_sub_object_create(), lod_sub_object_index_insert(), lod_sub_object_ref_add(), lod_sub_object_xattr_set(), lu_object_header::loh_attr, lod_thread_info::lti_attr, lod_thread_info::lti_dt_rec, lod_thread_info::lti_format, lod_thread_info::lti_key, lod_thread_info::lti_linkea_buf, lu_object_fid(), MOR_TGT_CHILD, OBD_ALLOC_PTR, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_BAD_SLAVE_LMV, OBD_FAIL_LFSCK_BAD_SLAVE_NAME, OBD_FAIL_LFSCK_LOST_MASTER_LMV, OBD_FAIL_LFSCK_LOST_SLAVE_LMV, OBD_FREE_PTR, PFID, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, RETURN, XATTR_NAME_LINK, and XATTR_NAME_LMV.
Referenced by lod_dir_striping_create_internal().
static int lod_xattr_set_lov_on_dir (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, const char * name, int fl, struct thandle * th) [static]
Set default striping on a directory.
Sets specified striping on a directory object unless it matches the default striping (LOVEA_DELETE_VALUES() macro). In the latter case remove existing EA. This striping will be used when regular file is being created in this directory.
Parameters:
[in] env execution environment
[in] dt the striped object
[in] buf buffer with the striping
[in] name name of EA
[in] fl xattr flag (see OSD API description)
[in] th transaction handle
Return values:
0 on success
negative if failed
Definition at line 2233 of file lod_object.c.
References CDEBUG, D_OTHER, dt_object::do_lu, ENTRY, LASSERT, lu_buf::lb_buf, lov_user_md_v1::lmm_magic, lov_user_md_v3::lmm_pool_name, lov_user_md_v1::lmm_stripe_count, lov_user_md_v1::lmm_stripe_offset, lov_user_md_v1::lmm_stripe_size, lu_object::lo_dev, lod_dt_obj(), lod_lov_stripe_cache_clear(), lod_verify_striping(), lod_xattr_del_internal(), lod_xattr_set_internal(), LOV_USER_MAGIC_V3, LOVEA_DELETE_VALUES, lu2lod_dev(), and RETURN.
Referenced by lod_dir_striping_create_internal(), and lod_xattr_set().
Variable Documentation
const char dot[] = "." [static]
Definition at line 58 of file lod_object.c.
const char dotdot[] = ".." [static]
Definition at line 59 of file lod_object.c.
static struct dt_body_operations lod_body_lnk_ops [static, read]
Initial value:
 {
        .dbo_read               = lod_read,
        .dbo_declare_write      = lod_declare_write,
        .dbo_write              = lod_write
}
Definition at line 61 of file lod_object.c.
Referenced by lod_declare_object_create().
static struct dt_body_operations lod_body_ops [static, read]
Initial value:
 {
        .dbo_read               = lod_read,
        .dbo_declare_write      = lod_declare_write,
        .dbo_write              = lod_write,
        .dbo_declare_punch      = lod_declare_punch,
        .dbo_punch              = lod_punch,
}
Definition at line 62 of file lod_object.c.
Referenced by lod_declare_object_create().
struct dt_index_operations lod_index_ops [static]
Initial value:
 {
        .dio_lookup             = lod_index_lookup,
        .dio_declare_insert     = lod_declare_index_insert,
        .dio_insert             = lod_index_insert,
        .dio_declare_delete     = lod_declare_index_delete,
        .dio_delete             = lod_index_delete,
        .dio_it = {
                .init           = lod_it_init,
                .fini           = lod_it_fini,
                .get            = lod_it_get,
                .put            = lod_it_put,
                .next           = lod_it_next,
                .key            = lod_it_key,
                .key_size       = lod_it_key_size,
                .rec            = lod_it_rec,
                .rec_size       = lod_it_rec_size,
                .store          = lod_it_store,
                .load           = lod_it_load,
                .key_rec        = lod_it_key_rec,
        }
}
Definition at line 360 of file lod_object.c.
struct lu_object_operations lod_lu_obj_ops
Initial value:
 {
        .loo_object_init        = lod_object_init,
        .loo_object_start       = lod_object_start,
        .loo_object_free        = lod_object_free,
        .loo_object_release     = lod_object_release,
        .loo_object_print       = lod_object_print,
}
Definition at line 4264 of file lod_object.c.
Referenced by lod_object_alloc().
struct dt_object_operations lod_obj_ops
Initial value:
 {
        .do_read_lock           = lod_object_read_lock,
        .do_write_lock          = lod_object_write_lock,
        .do_read_unlock         = lod_object_read_unlock,
        .do_write_unlock        = lod_object_write_unlock,
        .do_write_locked        = lod_object_write_locked,
        .do_attr_get            = lod_attr_get,
        .do_declare_attr_set    = lod_declare_attr_set,
        .do_attr_set            = lod_attr_set,
        .do_xattr_get           = lod_xattr_get,
        .do_declare_xattr_set   = lod_declare_xattr_set,
        .do_xattr_set           = lod_xattr_set,
        .do_declare_xattr_del   = lod_declare_xattr_del,
        .do_xattr_del           = lod_xattr_del,
        .do_xattr_list          = lod_xattr_list,
        .do_ah_init             = lod_ah_init,
        .do_declare_create      = lod_declare_object_create,
        .do_create              = lod_object_create,
        .do_declare_destroy     = lod_declare_object_destroy,
        .do_destroy             = lod_object_destroy,
        .do_index_try           = lod_index_try,
        .do_declare_ref_add     = lod_declare_ref_add,
        .do_ref_add             = lod_ref_add,
        .do_declare_ref_del     = lod_declare_ref_del,
        .do_ref_del             = lod_ref_del,
        .do_object_sync         = lod_object_sync,
        .do_object_lock         = lod_object_lock,
        .do_object_unlock       = lod_object_unlock,
}
Definition at line 3982 of file lod_object.c.
Referenced by lod_object_alloc().
struct dt_index_operations lod_striped_index_ops [static]
Initial value:
 {
        .dio_lookup             = lod_index_lookup,
        .dio_declare_insert     = lod_declare_index_insert,
        .dio_insert             = lod_index_insert,
        .dio_declare_delete     = lod_declare_index_delete,
        .dio_delete             = lod_index_delete,
        .dio_it = {
                .init           = lod_striped_it_init,
                .fini           = lod_striped_it_fini,
                .get            = lod_striped_it_get,
                .put            = lod_striped_it_put,
                .next           = lod_striped_it_next,
                .key            = lod_striped_it_key,
                .key_size       = lod_striped_it_key_size,
                .rec            = lod_striped_it_rec,
                .rec_size       = lod_striped_it_rec_size,
                .store          = lod_striped_it_store,
                .load           = lod_striped_it_load,
        }
}
Definition at line 729 of file lod_object.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.