Lustre: lustre/lod/lod_pool.c File Reference
lustre/lod/lod_pool.c File Reference
#include <libcfs/libcfs.h>
#include <obd.h>
#include "lod_internal.h"
Data Structures
struct lod_pool_iterator
Defines
#define DEBUG_SUBSYSTEM S_LOV
#define pool_tgt(_p, _i)
#define POOL_IT_MAGIC 0xB001CEA0
#define POOL_INIT_COUNT 2
Initialize the pool data structures at startup.
Functions
static void pool_getref (struct pool_desc *pool)
Get a reference on the specified pool.
void lod_pool_putref (struct pool_desc *pool)
Drop a reference on the specified pool and free its memory if needed.
static void pool_putref_locked (struct pool_desc *pool)
Drop the refcount in cases where the caller holds a spinlock.
static __u32 pool_hashfn (struct cfs_hash *hash_body, const void *key, unsigned mask)
Hash the pool name for use by the cfs_hash handlers.
static void * pool_key (struct hlist_node *hnode)
Return the actual key (pool name) from the hashed hnode.
static int pool_hashkey_keycmp (const void *key, struct hlist_node *compared)
Check if the specified hash key matches the hash node.
static void * pool_hashobject (struct hlist_node *hnode)
Return the actual pool data structure from the hash table entry.
static void pool_hashrefcount_get (struct cfs_hash *hs, struct hlist_node *hnode)
static void pool_hashrefcount_put_locked (struct cfs_hash *hs, struct hlist_node *hnode)
static void * pool_proc_next (struct seq_file *seq, void *v, loff_t *pos)
Return the next configured target within one pool for seq_file iteration.
static void * pool_proc_start (struct seq_file *seq, loff_t *pos)
Start seq_file iteration via /proc for a single pool.
static void pool_proc_stop (struct seq_file *seq, void *v)
Finish seq_file iteration for a single pool.
static int pool_proc_show (struct seq_file *seq, void *v)
Print out one target entry from the pool for seq_file iteration.
static int pool_proc_open (struct inode *inode, struct file *file)
Open a new /proc file for seq_file iteration of targets in one pool.
void lod_dump_pool (int level, struct pool_desc *pool)
Dump the pool target list into the Lustre debug log.
int lod_ost_pool_init (struct ost_pool *op, unsigned int count)
int lod_ost_pool_extend (struct ost_pool *op, unsigned int min_count)
Increase the op_array size to hold more targets in this pool.
int lod_ost_pool_add (struct ost_pool *op, __u32 idx, unsigned int min_count)
Add a new target to an existing pool.
int lod_ost_pool_remove (struct ost_pool *op, __u32 idx)
Remove an existing pool from the system.
int lod_ost_pool_free (struct ost_pool *op)
Free the pool after it was emptied and removed from /proc.
int lod_pool_new (struct obd_device *obd, char *poolname)
Allocate a new pool for the specified device.
int lod_pool_del (struct obd_device *obd, char *poolname)
Remove the named pool from the OBD device.
int lod_pool_add (struct obd_device *obd, char *poolname, char *ostname)
Add a single target device to the named pool.
int lod_pool_remove (struct obd_device *obd, char *poolname, char *ostname)
Remove the named target from the specified pool.
int lod_check_index_in_pool (__u32 idx, struct pool_desc *pool)
Check if the specified target exists in the pool.
struct pool_desc * lod_find_pool (struct lod_device *lod, char *poolname)
Find the pool descriptor for the specified pool and return it with a reference to the caller if found.
Variables
struct cfs_hash_ops pool_hash_operations
static struct seq_operations pool_proc_ops
static struct file_operations pool_proc_operations
Define Documentation
#define DEBUG_SUBSYSTEM S_LOV
Definition at line 58 of file lod_pool.c.
#define POOL_INIT_COUNT 2
Initialize the pool data structures at startup.
Allocate and initialize the pool data structures with the specified array size. If pool count is not specified (count == 0), then POOL_INIT_COUNT will be used. Allocating a non-zero initial array size avoids the need to reallocate as new pools are added.
Parameters:
[in] op pool structure
[in] count initial size of the target op_array[] array
Return values:
0 indicates successful pool initialization
negative error number on failure
Definition at line 467 of file lod_pool.c.
Referenced by lod_ost_pool_init().
#define POOL_IT_MAGIC 0xB001CEA0
Definition at line 229 of file lod_pool.c.
Referenced by pool_proc_next(), pool_proc_show(), pool_proc_start(), and pool_proc_stop().
#define pool_tgt (_p, _i)
Value:
OST_TGT(lu2lod_dev((_p)->pool_lobd->obd_lu_dev), \
                                 (_p)->pool_obds.op_array[_i])
Definition at line 64 of file lod_pool.c.
Referenced by lod_dump_pool(), lov_dump_pool(), and pool_proc_show().
Function Documentation
int lod_check_index_in_pool (__u32 idx, struct pool_desc * pool)
Check if the specified target exists in the pool.
The caller may not have a reference on pool if it got the pool without calling lod_find_pool() (e.g. directly from the lod pool list)
Parameters:
[in] idx Target index to check
[in] pool Pool in which to check if target is added.
Return values:
0 successfully found index in pool
negative error if device not found in pool
Definition at line 876 of file lod_pool.c.
References ENTRY, EXIT, GOTO, lod_pool_putref(), pool_getref(), pool_tgt_array, pool_tgt_count, and pool_tgt_rw_sem.
Referenced by lod_qos_parse_config(), and lod_verify_striping().
void lod_dump_pool (int level, struct pool_desc * pool)
Dump the pool target list into the Lustre debug log.
This is a debugging function to allow dumping the list of targets in pool to the Lustre kernel debug log at the given level.
This is not currently called by any existing code, but can be called from within gdb/crash to display the contents of the pool, or from code under development.
Parameters:
[in] level Lustre debug level (D_INFO, D_WARN, D_ERROR, etc)
[in] pool pool descriptor to be dumped
Definition at line 431 of file lod_pool.c.
References CDEBUG, lod_pool_putref(), LOV_POOLNAMEF, obd_uuid2str(), ost_pool::op_count, pool_getref(), pool_desc::pool_name, pool_desc::pool_obds, pool_tgt, pool_tgt_count, and pool_tgt_rw_sem.
struct pool_desc* lod_find_pool (struct lod_device * lod, char * poolname) [read]
Find the pool descriptor for the specified pool and return it with a reference to the caller if found.
Parameters:
[in] lod LOD on which the pools are configured
[in] poolname NUL-terminated name of the pool
Return values:
pointer to pool descriptor on success
NULL if poolname could not be found or poolname is empty
Definition at line 909 of file lod_pool.c.
References CDEBUG, cfs_hash_lookup(), D_CONFIG, obd_export::exp_obd, lod_device::lod_child_exp, lod_pool_putref(), lod_device::lod_pools_hash_body, LOV_POOLNAMEF, obd_device::obd_name, and pool_tgt_count.
Referenced by lod_alloc_qos(), lod_alloc_rr(), lod_alloc_specific(), lod_qos_parse_config(), and lod_verify_striping().
int lod_ost_pool_add (struct ost_pool * op, __u32 idx, unsigned int min_count)
Add a new target to an existing pool.
Add a new target device to the pool previously created and returned by lod_pool_new(). Each target can only be in each pool at most one time.
Parameters:
[in] op target pool to add new entry
[in] idx pool index number to add to the op array
[in] min_count minimum number of entries to expect in the pool
Return values:
0 if target could be added to the pool
negative error if target idx was not added
Definition at line 537 of file lod_pool.c.
References ENTRY, EXIT, GOTO, lod_ost_pool_extend(), ost_pool::op_array, ost_pool::op_count, and ost_pool::op_rw_sem.
Referenced by lod_add_device(), and lod_pool_add().
int lod_ost_pool_extend (struct ost_pool * op, unsigned int min_count)
Increase the op_array size to hold more targets in this pool.
The size is increased to at least min_count, but may be larger for an existing pool since ->op_array[] is growing exponentially. Caller must hold write op_rwlock.
Parameters:
[in] op pool structure
[in] min_count minimum number of entries to handle
Return values:
0 on success
negative error number on failure.
Definition at line 500 of file lod_pool.c.
References LASSERT, max, OBD_ALLOC, OBD_FREE, ost_pool::op_array, ost_pool::op_count, and ost_pool::op_size.
Referenced by lod_ost_pool_add(), and lod_qos_calc_rr().
int lod_ost_pool_free (struct ost_pool * op)
Free the pool after it was emptied and removed from /proc.
Note that all of the child/target entries referenced by this pool must have been removed by lod_ost_pool_remove() before it can be deleted from memory.
Parameters:
[in] op pool to be freed.
Return values:
0 on success or if pool was already freed
Definition at line 611 of file lod_pool.c.
References ENTRY, OBD_FREE, ost_pool::op_array, ost_pool::op_count, ost_pool::op_rw_sem, ost_pool::op_size, and RETURN.
Referenced by lod_pool_new(), lod_pool_putref(), lod_pools_fini(), and lod_pools_init().
int lod_ost_pool_init (struct ost_pool * op, unsigned int count)
Definition at line 468 of file lod_pool.c.
References ENTRY, EXIT, OBD_ALLOC, ost_pool::op_array, ost_pool::op_count, ost_pool::op_rw_sem, ost_pool::op_size, POOL_INIT_COUNT, and RETURN.
Referenced by lod_pool_new(), and lod_pools_init().
int lod_ost_pool_remove (struct ost_pool * op, __u32 idx)
Remove an existing pool from the system.
The specified pool must have previously been allocated by lod_pool_new() and not have any target members in the pool. If the removed target is not the last, compact the array to remove empty spaces.
Parameters:
[in] op pointer to the original data structure
[in] idx target index to be removed
Return values:
0 on success
negative error number on failure
Definition at line 577 of file lod_pool.c.
References ENTRY, EXIT, ost_pool::op_array, ost_pool::op_count, ost_pool::op_rw_sem, and RETURN.
Referenced by lod_add_device(), lod_pool_remove(), and lod_putref().
int lod_pool_add (struct obd_device * obd, char * poolname, char * ostname)
Add a single target device to the named pool.
Add the target specified by ostname to the specified poolname.
Parameters:
[in] obd OBD device on which to add the pool
[in] poolname name of the pool to which to add the target ostname
[in] ostname name of the target device to be added
Return values:
0 if ostname was (previously) added to the named pool
negative error number on failure
Definition at line 766 of file lod_pool.c.
References CDEBUG, cfs_hash_lookup(), D_CONFIG, ENTRY, EXIT, GOTO, lod_foreach_ost, lod_getref(), lod_device::lod_ost_descs, lod_ost_pool_add(), lod_pool_putref(), lod_device::lod_pools_hash_body, lod_putref(), LOV_POOLNAMEF, lod_qos_rr::lqr_dirty, lu2lod_dev(), obd_device::obd_lu_dev, obd_str2uuid(), obd_uuid_equals(), OST_TGT, pool_desc::pool_obds, pool_desc::pool_rr, pool_tgt_count, and RETURN.
int lod_pool_del (struct obd_device * obd, char * poolname)
Remove the named pool from the OBD device.
Parameters:
[in] obd OBD device on which pool was previously created
[in] poolname name of pool to remove from obd
Return values:
0 on successfully removing the pool
negative error numbers for failures
Definition at line 726 of file lod_pool.c.
References CDEBUG, cfs_hash_del_key(), D_INFO, ENTRY, list_del_init(), lod_device::lod_pool_count, lod_pool_putref(), lod_device::lod_pools_hash_body, lprocfs_remove(), lu2lod_dev(), obd_device::obd_dev_lock, obd_device::obd_lu_dev, pool_desc::pool_list, pool_desc::pool_proc_entry, and RETURN.
Referenced by lod_pools_fini().
int lod_pool_new (struct obd_device * obd, char * poolname)
Allocate a new pool for the specified device.
Allocate a new pool_desc structure for the specified new_pool device to create a pool with the given poolname. The new pool structure is created with a single reference, and is freed when the reference count drops to zero.
Parameters:
[in] obd Lustre OBD device on which to add a pool iterator
[in] poolname the name of the pool to be created
Return values:
0 in case of success
negative error code in case of error
Definition at line 643 of file lod_pool.c.
References CDEBUG, cfs_hash_add_unique(), D_CONFIG, D_INFO, ENTRY, GOTO, INIT_HLIST_NODE, list_add_tail(), list_del_init(), lod_ost_pool_free(), lod_ost_pool_init(), lod_device::lod_pool_count, lod_device::lod_pool_list, lod_device::lod_pool_proc_entry, lod_pool_putref(), lod_device::lod_pools_hash_body, lod_qos_rr_init(), LOV_MAXPOOLNAME, LOV_POOLNAMEF, lprocfs_add_simple(), lprocfs_remove(), lod_qos_rr::lqr_pool, lu2lod_dev(), OBD_ALLOC_PTR, obd_device::obd_dev_lock, OBD_FREE_PTR, obd_device::obd_lu_dev, obd_device::obd_name, pool_getref(), pool_desc::pool_hash, pool_desc::pool_list, pool_desc::pool_lobd, pool_desc::pool_name, pool_desc::pool_obds, pool_desc::pool_proc_entry, pool_proc_operations, pool_desc::pool_refcount, pool_desc::pool_rr, RETURN, and strlcpy().
void lod_pool_putref (struct pool_desc * pool)
Drop a reference on the specified pool and free its memory if needed.
One reference is held by the LOD OBD device while it is configured, from the time the configuration log defines the pool until the time when it is dropped when the LOD OBD is cleaned up or the pool is deleted. This means that the pool will not be freed while the LOD device is configured, unless it is explicitly destroyed by the sysadmin. The pool structure is freed after the last reference on the structure is released.
Parameters:
[in] pool pool descriptor to drop reference on and possibly free
Definition at line 95 of file lod_pool.c.
References CDEBUG, D_INFO, EXIT, hlist_unhashed(), LASSERT, list_empty(), lod_ost_pool_free(), lod_qos_rr::lqr_pool, OBD_FREE_PTR, pool_desc::pool_hash, pool_desc::pool_list, pool_desc::pool_obds, pool_desc::pool_proc_entry, pool_desc::pool_refcount, and pool_desc::pool_rr.
Referenced by lod_alloc_qos(), lod_alloc_rr(), lod_alloc_specific(), lod_check_index_in_pool(), lod_dump_pool(), lod_find_pool(), lod_pool_add(), lod_pool_del(), lod_pool_new(), lod_pool_remove(), lod_qos_parse_config(), lod_verify_striping(), pool_proc_start(), and pool_proc_stop().
int lod_pool_remove (struct obd_device * obd, char * poolname, char * ostname)
Remove the named target from the specified pool.
Remove one target named ostname from poolname. The ostname is searched for in the lod_device lod_ost_bitmap array, to ensure the specified name actually exists in the pool.
Parameters:
[in] obd OBD device from which to remove poolname
[in] poolname name of the pool to be changed
[in] ostname name of the target to remove from poolname
Return values:
0 on successfully removing ostname from the pool
negative number on error (e.g. ostname not in pool)
Definition at line 823 of file lod_pool.c.
References CDEBUG, cfs_foreach_bit, cfs_hash_lookup(), D_CONFIG, ENTRY, EXIT, GOTO, lod_getref(), lod_device::lod_ost_descs, lod_ost_pool_remove(), lod_pool_putref(), lod_device::lod_pools_hash_body, lod_putref(), LOV_POOLNAMEF, lod_qos_rr::lqr_dirty, lu2lod_dev(), obd_device::obd_lu_dev, obd_str2uuid(), obd_uuid_equals(), OST_TGT, pool_desc::pool_obds, pool_desc::pool_rr, and RETURN.
static void pool_getref (struct pool_desc * pool) [static]
Get a reference on the specified pool.
To ensure the pool descriptor is not freed before the caller is finished with it. Any process that is accessing pool directly needs to hold reference on it, including /proc since a userspace thread may be holding the /proc file open and busy in the kernel.
Parameters:
[in] pool pool descriptor on which to gain reference
Definition at line 77 of file lod_pool.c.
References CDEBUG, D_INFO, and pool_desc::pool_refcount.
Referenced by lod_check_index_in_pool(), lod_dump_pool(), lod_pool_new(), pool_hashrefcount_get(), and pool_proc_start().
static __u32 pool_hashfn (struct cfs_hash * hash_body, const void * key, unsigned mask) [static]
Hash the pool name for use by the cfs_hash handlers.
Use the standard DJB2 hash function for ASCII strings in Lustre.
Parameters:
[in] hash_body hash structure where this key is embedded (unused)
[in] key key to be hashed (in this case the pool name)
[in] mask bitmask to limit the hash value to the desired size
Return values:
computed hash value from key and limited by mask
Definition at line 143 of file lod_pool.c.
References cfs_hash_djb2_hash(), LOV_MAXPOOLNAME, and strnlen.
static int pool_hashkey_keycmp (const void * key, struct hlist_node * compared) [static]
Check if the specified hash key matches the hash node.
This is needed in case there is a hash key collision, allowing the hash table lookup/iteration to distinguish between the two entries.
Parameters:
[in] key key (pool name) being searched for
[in] compared current entry being compared
Return values:
0 if key is the same as the key of compared
1 if key is different from the key of compared
Definition at line 178 of file lod_pool.c.
References LOV_MAXPOOLNAME, and pool_key().
static void* pool_hashobject (struct hlist_node * hnode) [static]
Return the actual pool data structure from the hash table entry.
Once the hash table entry is found, extract the pool data from it. The return type of this function is void * because it needs to be assigned to the generic hash operations table.
Parameters:
[in] hnode hash table entry
Return values:
struct pool_desc for the specified hnode
Definition at line 194 of file lod_pool.c.
References hlist_entry, and pool_desc::pool_hash.
static void pool_hashrefcount_get (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 199 of file lod_pool.c.
References hlist_entry, pool_getref(), and pool_desc::pool_hash.
static void pool_hashrefcount_put_locked (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 207 of file lod_pool.c.
References hlist_entry, pool_desc::pool_hash, and pool_putref_locked().
static void* pool_key (struct hlist_node * hnode) [static]
Return the actual key (pool name) from the hashed hnode.
Allows extracting the key name when iterating over all hash entries.
Parameters:
[in] hnode hash node found by lookup or iteration
Return values:
char array referencing the pool name (no refcount)
Definition at line 158 of file lod_pool.c.
References hlist_entry, pool_desc::pool_hash, and pool_desc::pool_name.
Referenced by pool_hashkey_keycmp().
static void* pool_proc_next (struct seq_file * seq, void * v, loff_t * pos) [static]
Return the next configured target within one pool for seq_file iteration.
Iterator is used to go through the target entries of a single pool (i.e. the list of OSTs configured for a named pool). lpi_idx is the current target index in the pool's op_array[].
The return type is a void * because this function is one of the struct seq_operations methods and must match the function template.
Parameters:
[in] seq /proc sequence file iteration tracking structure
[in] v unused
[in] pos position within iteration; 0 to number of targets - 1
Return values:
struct pool_iterator of the next pool descriptor
Definition at line 252 of file lod_pool.c.
References LASSERTF, lod_pool_iterator::lpi_idx, lod_pool_iterator::lpi_magic, lod_pool_iterator::lpi_pool, POOL_IT_MAGIC, pool_tgt_count, and pool_tgt_rw_sem.
Referenced by pool_proc_start().
static int pool_proc_open (struct inode * inode, struct file * file) [static]
Open a new /proc file for seq_file iteration of targets in one pool.
Initialize the seq_file private pointer to reference the pool.
Parameters:
inode inode to store iteration state for /proc
file file descriptor to store iteration methods
Return values:
0 for success
negative error number on failure
Definition at line 399 of file lod_pool.c.
References pool_proc_ops.
static int pool_proc_show (struct seq_file * seq, void * v) [static]
Print out one target entry from the pool for seq_file iteration.
The currently referenced pool target is given by op_array[lpi_idx].
Parameters:
[in] seq new sequence file structure to initialize
[in] v (unused)
Definition at line 363 of file lod_pool.c.
References LASSERT, LASSERTF, lod_pool_iterator::lpi_idx, lod_pool_iterator::lpi_magic, lod_pool_iterator::lpi_pool, lod_tgt_desc::ltd_uuid, obd_uuid2str(), POOL_IT_MAGIC, pool_tgt, pool_tgt_count, and pool_tgt_rw_sem.
static void* pool_proc_start (struct seq_file * seq, loff_t * pos) [static]
Start seq_file iteration via /proc for a single pool.
The pos parameter may be non-zero, indicating that the iteration is starting at some offset in the target list. Use the seq_file private field to memorize the iterator so we can free it at stop(). Need to restore the private pointer to the pool before freeing it.
Parameters:
[in] seq new sequence file structure to initialize
[in] pos initial target number at which to start iteration
Return values:
initialized pool iterator private structure
NULL if pos exceeds the number of targets in pool
negative error number on failure
Definition at line 293 of file lod_pool.c.
References lod_pool_putref(), lod_pool_iterator::lpi_idx, lod_pool_iterator::lpi_magic, lod_pool_iterator::lpi_pool, OBD_ALLOC_PTR, pool_getref(), POOL_IT_MAGIC, pool_proc_next(), and pool_tgt_count.
static void pool_proc_stop (struct seq_file * seq, void * v) [static]
Finish seq_file iteration for a single pool.
Once iteration has been completed, the pool_iterator struct must be freed, and the seq_file private pointer restored to the pool, as it was initially when pool_proc_start() was called.
In some cases the stop() method may be called 2 times, without calling the start() method (see seq_read() from fs/seq_file.c). We have to free the private iterator struct only if seq->private points to the iterator.
Parameters:
[in] seq sequence file structure to clean up
[in] v (unused)
Definition at line 344 of file lod_pool.c.
References lod_pool_putref(), lod_pool_iterator::lpi_magic, lod_pool_iterator::lpi_pool, OBD_FREE_PTR, and POOL_IT_MAGIC.
static void pool_putref_locked (struct pool_desc * pool) [static]
Drop the refcount in cases where the caller holds a spinlock.
This is needed if the caller cannot be blocked while freeing memory. It assumes that there is some other known refcount held on the pool and the memory cannot actually be freed, but the refcounting needs to be kept accurate.
Parameters:
[in] pool pool descriptor on which to drop reference
Definition at line 119 of file lod_pool.c.
References CDEBUG, D_INFO, LASSERT, and pool_desc::pool_refcount.
Referenced by pool_hashrefcount_put_locked().
Variable Documentation
struct cfs_hash_ops pool_hash_operations
Initial value:
 {
        .hs_hash        = pool_hashfn,
        .hs_key         = pool_key,
        .hs_keycmp      = pool_hashkey_keycmp,
        .hs_object      = pool_hashobject,
        .hs_get         = pool_hashrefcount_get,
        .hs_put_locked  = pool_hashrefcount_put_locked,
}
Definition at line 216 of file lod_pool.c.
struct file_operations pool_proc_operations [static]
Initial value:
 {
        .open           = pool_proc_open,
        .read           = seq_read,
        .llseek         = seq_lseek,
        .release        = seq_release,
}
Definition at line 411 of file lod_pool.c.
Referenced by lod_pool_new().
struct seq_operations pool_proc_ops [static]
Initial value:
 {
        .start  = pool_proc_start,
        .next   = pool_proc_next,
        .stop   = pool_proc_stop,
        .show   = pool_proc_show,
}
Definition at line 381 of file lod_pool.c.
Referenced by pool_proc_open().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.