Lustre: lustre/lod/lod_internal.h File Reference
lustre/lod/lod_internal.h File Reference
#include <libcfs/libcfs.h>
#include <lustre_cfg.h>
#include <obd.h>
#include <dt_object.h>
Data Structures
struct lod_qos_rr
struct pool_desc
struct lod_qos
struct lod_qos_oss
struct ltd_qos
struct lod_tgt_desc
struct lod_tgt_desc_idx
struct lod_tgt_descs
struct lod_device
struct lod_dir_stripe_info
struct lod_object
struct lod_it
struct lod_thread_info
Defines
#define LOV_USES_ASSIGNED_STRIPE 0
#define LOV_USES_DEFAULT_STRIPE 1
#define LOVEA_DELETE_VALUES(size, count, offset, pool)
#define LMVEA_DELETE_VALUES(count, offset) ((count) == 0 && (offset) == (typeof(offset))(-1))
#define LOV_OFFSET_DEFAULT ((__u16)-1)
#define pool_tgt_size(p) ((p)->pool_obds.op_size)
#define pool_tgt_count(p) ((p)->pool_obds.op_count)
#define pool_tgt_array(p) ((p)->pool_obds.op_array)
#define pool_tgt_rw_sem(p) ((p)->pool_obds.op_rw_sem)
#define TGT_PTRS 256
#define TGT_PTRS_PER_BLOCK 256
#define LTD_TGT(ltd, index)
#define OST_TGT(lod, index) LTD_TGT(&lod->lod_ost_descs, index)
#define MDT_TGT(lod, index) LTD_TGT(&lod->lod_mdt_descs, index)
#define lod_osts lod_ost_descs.ltd_tgts
#define lod_ost_bitmap lod_ost_descs.ltd_tgt_bitmap
#define lod_ostnr lod_ost_descs.ltd_tgtnr
#define lod_osts_size lod_ost_descs.ltd_tgts_size
#define ltd_ost ltd_tgt
#define lod_ost_desc lod_tgt_desc
#define lod_mdts lod_mdt_descs.ltd_tgts
#define lod_mdt_bitmap lod_mdt_descs.ltd_tgt_bitmap
#define lod_remote_mdt_count lod_mdt_descs.ltd_tgtnr
#define lod_mdts_size lod_mdt_descs.ltd_tgts_size
#define ltd_mdt ltd_tgt
#define lod_mdt_desc lod_tgt_desc
#define ldo_dir_stripe_offset ldo_dir_stripe->ldsi_stripe_offset
#define ldo_dir_def_stripenr ldo_dir_stripe->ldsi_def_stripenr
#define ldo_dir_hash_type ldo_dir_stripe->ldsi_hash_type
#define ldo_dir_def_hash_type ldo_dir_stripe->ldsi_def_hash_type
#define ldo_dir_striped ldo_dir_stripe->ldsi_striped
#define ldo_dir_def_striping_set ldo_dir_stripe->ldsi_def_striping_set
#define ldo_dir_def_striping_cached ldo_dir_stripe->ldsi_def_striping_cached
#define ldo_dir_def_stripe_offset ldo_dir_stripe->ldsi_def_stripe_offset
#define lod_foreach_ost(__dev, index)
#define lod_foreach_mdt(mdt_dev, index) cfs_foreach_bit((mdt_dev)->lod_mdt_bitmap, (index))
Functions
static int lu_device_is_lod (struct lu_device *d)
static struct lod_device * lu2lod_dev (struct lu_device *d)
static struct lu_device * lod2lu_dev (struct lod_device *d)
static struct obd_device * lod2obd (struct lod_device *d)
static struct lod_device * dt2lod_dev (struct dt_device *d)
static struct lod_object * lu2lod_obj (struct lu_object *o)
static struct lu_object * lod2lu_obj (struct lod_object *obj)
static struct lod_object * lod_obj (const struct lu_object *o)
static struct lod_object * lod_dt_obj (const struct dt_object *d)
static struct dt_object * lod_object_child (struct lod_object *o)
static struct lod_thread_info * lod_env_info (const struct lu_env *env)
static struct lu_name * lod_name_get (const struct lu_env *env, const void *area, int len)
int lod_fld_lookup (const struct lu_env *env, struct lod_device *lod, const struct lu_fid *fid, __u32 *tgt, int *flags)
int lod_sub_init_llog (const struct lu_env *env, struct lod_device *lod, struct dt_device *dt)
Init sub llog context.
void lod_sub_fini_llog (const struct lu_env *env, struct dt_device *dt, struct ptlrpc_thread *thread)
finish sub llog context
int lodname2mdt_index (char *lodname, __u32 *mdt_index)
Extract MDT target index from a device name.
void lod_getref (struct lod_tgt_descs *ltd)
Increase reference count on the target table.
void lod_putref (struct lod_device *lod, struct lod_tgt_descs *ltd)
Decrease reference count on the target table.
int lod_add_device (const struct lu_env *env, struct lod_device *lod, char *osp, unsigned index, unsigned gen, int mdt_index, char *type, int active)
Connect LOD to a new OSP and add it to the target table.
int lod_del_device (const struct lu_env *env, struct lod_device *lod, struct lod_tgt_descs *ltd, char *osp, unsigned idx, unsigned gen, bool for_ost)
Remove device by name.
int lod_fini_tgt (const struct lu_env *env, struct lod_device *lod, struct lod_tgt_descs *ltd, bool for_ost)
Schedule removal of all the targets from the given target table.
int lod_load_striping_locked (const struct lu_env *env, struct lod_object *lo)
Initialize the object representing the stripes.
int lod_load_striping (const struct lu_env *env, struct lod_object *lo)
A generic function to initialize the stripe objects.
int lod_get_ea (const struct lu_env *env, struct lod_object *lo, const char *name)
Get LOV EA.
static int lod_get_lov_ea (const struct lu_env *env, struct lod_object *lo)
static int lod_get_lmv_ea (const struct lu_env *env, struct lod_object *lo)
static int lod_get_default_lmv_ea (const struct lu_env *env, struct lod_object *lo)
void lod_fix_desc (struct lov_desc *desc)
Used to fix insane default striping.
void lod_fix_desc_qos_maxage (__u32 *val)
void lod_fix_desc_pattern (__u32 *val)
void lod_fix_desc_stripe_count (__u32 *val)
void lod_fix_desc_stripe_size (__u64 *val)
int lod_pools_init (struct lod_device *m, struct lustre_cfg *cfg)
Initialize the structures used to store pools and default striping.
int lod_pools_fini (struct lod_device *m)
Release the structures describing the pools.
int lod_parse_striping (const struct lu_env *env, struct lod_object *mo, const struct lu_buf *buf)
Instantiate objects for striping.
int lod_parse_dir_striping (const struct lu_env *env, struct lod_object *lo, const struct lu_buf *buf)
Create in-core represenation for a striped directory.
int lod_initialize_objects (const struct lu_env *env, struct lod_object *mo, struct lov_ost_data_v1 *objs)
Instantiate objects for stripes.
int lod_verify_striping (struct lod_device *d, const struct lu_buf *buf, bool is_from_disk)
Verify striping.
int lod_generate_and_set_lovea (const struct lu_env *env, struct lod_object *mo, struct thandle *th)
Make LOV EA for striped object.
int lod_ea_store_resize (struct lod_thread_info *info, size_t size)
Resize per-thread storage to hold specified size.
int lod_ost_pool_add (struct ost_pool *op, __u32 idx, unsigned int min_count)
Add a new target to an existing pool.
int lod_ost_pool_remove (struct ost_pool *op, __u32 idx)
Remove an existing pool from the system.
int lod_ost_pool_extend (struct ost_pool *op, unsigned int min_count)
Increase the op_array size to hold more targets in this pool.
struct pool_desc * lod_find_pool (struct lod_device *lod, char *poolname)
Find the pool descriptor for the specified pool and return it with a reference to the caller if found.
void lod_pool_putref (struct pool_desc *pool)
Drop a reference on the specified pool and free its memory if needed.
int lod_ost_pool_free (struct ost_pool *op)
Free the pool after it was emptied and removed from /proc.
int lod_pool_del (struct obd_device *obd, char *poolname)
Remove the named pool from the OBD device.
int lod_ost_pool_init (struct ost_pool *op, unsigned int count)
int lod_check_index_in_pool (__u32 idx, struct pool_desc *pool)
Check if the specified target exists in the pool.
int lod_pool_new (struct obd_device *obd, char *poolname)
Allocate a new pool for the specified device.
int lod_pool_add (struct obd_device *obd, char *poolname, char *ostname)
Add a single target device to the named pool.
int lod_pool_remove (struct obd_device *obd, char *poolname, char *ostname)
Remove the named target from the specified pool.
int lod_qos_prep_create (const struct lu_env *env, struct lod_object *lo, struct lu_attr *attr, const struct lu_buf *buf, struct thandle *th)
Create a striping for an obejct.
int qos_add_tgt (struct lod_device *, struct lod_tgt_desc *)
Add a new target to Quality of Service (QoS) target table.
int qos_del_tgt (struct lod_device *, struct lod_tgt_desc *)
Remove OST target from QoS table.
void lod_qos_rr_init (struct lod_qos_rr *lqr)
int lod_procfs_init (struct lod_device *lod)
void lod_procfs_fini (struct lod_device *lod)
int lod_load_lmv_shards (const struct lu_env *env, struct lod_object *lo, struct lu_buf *buf, bool resize)
Append the FID for each shard of the striped directory after the given LMV EA header.
int lod_object_set_pool (struct lod_object *o, char *pool)
Initialize a pool the object belongs to.
int lod_declare_striped_object (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, const struct lu_buf *lovea, struct thandle *th)
Declare creation of striped object.
int lod_striping_create (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_object_format *dof, struct thandle *th)
Creation of a striped regular object.
void lod_object_free_striping (const struct lu_env *env, struct lod_object *lo)
Release resources associated with striping.
struct thandle * lod_sub_get_thandle (const struct lu_env *env, struct thandle *th, const struct dt_object *sub_obj, bool *record_update)
int lod_sub_object_declare_create (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *th)
Declare sub-object creation.
int lod_sub_object_create (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *th)
Create sub-object.
int lod_sub_object_declare_ref_add (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Declare adding reference for the sub-object.
int lod_sub_object_ref_add (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Add reference for the sub-object.
int lod_sub_object_declare_ref_del (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Declare deleting reference for the sub-object.
int lod_sub_object_ref_del (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Delete reference for the sub-object.
int lod_sub_object_declare_destroy (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Declare destroying sub-object.
int lod_sub_object_destroy (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Destroy sub-object.
int lod_sub_object_declare_insert (const struct lu_env *env, struct dt_object *dt, const struct dt_rec *rec, const struct dt_key *key, struct thandle *th)
Declare sub-object index insert.
int lod_sub_object_index_insert (const struct lu_env *env, struct dt_object *dt, const struct dt_rec *rec, const struct dt_key *key, struct thandle *th, int ign)
Insert index of sub object.
int lod_sub_object_declare_delete (const struct lu_env *env, struct dt_object *dt, const struct dt_key *key, struct thandle *th)
Declare sub-object index delete.
int lod_sub_object_delete (const struct lu_env *env, struct dt_object *dt, const struct dt_key *name, struct thandle *th)
Delete index of sub object.
int lod_sub_object_declare_xattr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, const char *name, int fl, struct thandle *th)
Declare xattr_set.
int lod_sub_object_xattr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, const char *name, int fl, struct thandle *th)
Set xattr.
int lod_sub_object_declare_attr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_attr *attr, struct thandle *th)
Declare attr_set.
int lod_sub_object_attr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_attr *attr, struct thandle *th)
attributes set
int lod_sub_object_declare_xattr_del (const struct lu_env *env, struct dt_object *dt, const char *name, struct thandle *th)
Declare xattr_del.
int lod_sub_object_xattr_del (const struct lu_env *env, struct dt_object *dt, const char *name, struct thandle *th)
xattribute deletion
int lod_sub_object_declare_write (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, loff_t pos, struct thandle *th)
Declare buffer write.
ssize_t lod_sub_object_write (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, loff_t *pos, struct thandle *th, int rq)
Write buffer to sub object.
int lod_sub_object_declare_punch (const struct lu_env *env, struct dt_object *dt, __u64 start, __u64 end, struct thandle *th)
Declare punch.
int lod_sub_object_punch (const struct lu_env *env, struct dt_object *dt, __u64 start, __u64 end, struct thandle *th)
Punch to sub object.
int lod_sub_prep_llog (const struct lu_env *env, struct lod_device *lod, struct dt_device *dt, int index)
Variables
struct lu_device_operations lod_lu_ops
struct lu_context_key lod_thread_key
struct kmem_cache * lod_object_kmem
struct cfs_hash_ops pool_hash_operations
struct dt_object_operations lod_obj_ops
struct lu_object_operations lod_lu_obj_ops
Define Documentation
#define ldo_dir_def_hash_type ldo_dir_stripe->ldsi_def_hash_type
Definition at line 276 of file lod_internal.h.
#define ldo_dir_def_stripe_offset ldo_dir_stripe->ldsi_def_stripe_offset
Definition at line 280 of file lod_internal.h.
#define ldo_dir_def_stripenr ldo_dir_stripe->ldsi_def_stripenr
Definition at line 274 of file lod_internal.h.
#define ldo_dir_def_striping_cached ldo_dir_stripe->ldsi_def_striping_cached
Definition at line 279 of file lod_internal.h.
#define ldo_dir_def_striping_set ldo_dir_stripe->ldsi_def_striping_set
Definition at line 278 of file lod_internal.h.
#define ldo_dir_hash_type ldo_dir_stripe->ldsi_hash_type
Definition at line 275 of file lod_internal.h.
#define ldo_dir_stripe_offset ldo_dir_stripe->ldsi_stripe_offset
Definition at line 273 of file lod_internal.h.
#define ldo_dir_striped ldo_dir_stripe->ldsi_striped
Definition at line 277 of file lod_internal.h.
#define LMVEA_DELETE_VALUES (count, offset) ((count) == 0 && (offset) == (typeof(offset))(-1))
Definition at line 54 of file lod_internal.h.
Referenced by lod_dir_striping_create_internal(), and lod_xattr_set_default_lmv_on_dir().
#define lod_foreach_mdt (mdt_dev, index) cfs_foreach_bit((mdt_dev)->lod_mdt_bitmap, (index))
Definition at line 395 of file lod_internal.h.
Referenced by lod_obd_get_info(), and lod_obd_set_info_async().
#define lod_foreach_ost (__dev, index)
Value:
if ((__dev)->lod_osts_size > 0) \
                cfs_foreach_bit((__dev)->lod_ost_bitmap, (index))
Definition at line 391 of file lod_internal.h.
Referenced by lod_obd_get_info(), lod_obd_set_info_async(), lod_pool_add(), and lod_sync().
#define lod_mdt_bitmap lod_mdt_descs.ltd_tgt_bitmap
Definition at line 223 of file lod_internal.h.
#define lod_mdt_desc lod_tgt_desc
Definition at line 227 of file lod_internal.h.
#define lod_mdts lod_mdt_descs.ltd_tgts
Definition at line 222 of file lod_internal.h.
#define lod_mdts_size lod_mdt_descs.ltd_tgts_size
Definition at line 225 of file lod_internal.h.
#define lod_ost_bitmap lod_ost_descs.ltd_tgt_bitmap
Definition at line 216 of file lod_internal.h.
#define lod_ost_desc lod_tgt_desc
Definition at line 220 of file lod_internal.h.
Referenced by lod_sync().
#define lod_ostnr lod_ost_descs.ltd_tgtnr
Definition at line 217 of file lod_internal.h.
#define lod_osts lod_ost_descs.ltd_tgts
Definition at line 215 of file lod_internal.h.
#define lod_osts_size lod_ost_descs.ltd_tgts_size
Definition at line 218 of file lod_internal.h.
Referenced by lod_qos_declare_object_on().
#define lod_remote_mdt_count lod_mdt_descs.ltd_tgtnr
Definition at line 224 of file lod_internal.h.
#define LOV_OFFSET_DEFAULT ((__u16)-1)
Definition at line 57 of file lod_internal.h.
Referenced by lod_ah_init(), lod_qos_parse_config(), lod_qos_prep_create(), and lod_verify_striping().
#define LOV_USES_ASSIGNED_STRIPE 0
Definition at line 46 of file lod_internal.h.
Referenced by lod_qos_prep_create().
#define LOV_USES_DEFAULT_STRIPE 1
Definition at line 47 of file lod_internal.h.
Referenced by min_stripe_count().
#define LOVEA_DELETE_VALUES (size, count, offset, pool)
Value:
((size) == 0 && (count) == 0 &&                                 \
         (offset) == (typeof(offset))(-1) && (pool) == NULL)
Definition at line 50 of file lod_internal.h.
Referenced by lod_dir_striping_create_internal(), and lod_xattr_set_lov_on_dir().
#define ltd_mdt ltd_tgt
Definition at line 226 of file lod_internal.h.
#define ltd_ost ltd_tgt
Definition at line 219 of file lod_internal.h.
Referenced by validate_lod_and_idx().
#define LTD_TGT (ltd, index)
Value:
((ltd)->ltd_tgt_idx[(index) / \
         TGT_PTRS_PER_BLOCK]->ldi_tgt[(index) % TGT_PTRS_PER_BLOCK])
Definition at line 142 of file lod_internal.h.
Referenced by __lod_del_device(), lod_add_device(), lod_declare_object_create(), lod_del_device(), lod_object_init(), lod_parse_dir_striping(), lod_prep_md_striped_create(), lod_process_config(), lod_putref(), lod_sub_fini_all_llogs(), lod_sub_init_llog(), lod_sub_init_llogs(), lod_sub_process_config(), lod_sub_recovery_thread(), and lod_sub_stop_recovery_threads().
#define MDT_TGT (lod, index) LTD_TGT(&lod->lod_mdt_descs, index)
Definition at line 147 of file lod_internal.h.
Referenced by lod_obd_get_info(), and lod_obd_set_info_async().
#define OST_TGT (lod, index) LTD_TGT(&lod->lod_ost_descs, index)
Definition at line 146 of file lod_internal.h.
Referenced by lod_alloc_qos(), lod_alloc_rr(), lod_initialize_objects(), lod_obd_get_info(), lod_obd_set_info_async(), lod_pool_add(), lod_pool_remove(), lod_qos_calc_ppo(), lod_qos_calc_rr(), lod_qos_calc_weight(), lod_qos_declare_object_on(), lod_qos_statfs_update(), lod_qos_used(), lod_recovery_complete(), lod_statfs_and_check(), lod_sync(), and validate_lod_and_idx().
#define pool_tgt_array (p) ((p)->pool_obds.op_array)
Definition at line 81 of file lod_internal.h.
Referenced by lod_check_index_in_pool().
#define pool_tgt_count (p) ((p)->pool_obds.op_count)
Definition at line 80 of file lod_internal.h.
Referenced by lod_check_index_in_pool(), lod_dump_pool(), lod_find_pool(), lod_pool_add(), lod_qos_parse_config(), lod_verify_striping(), lov_dump_pool(), lov_pool_add(), pool_proc_next(), pool_proc_show(), and pool_proc_start().
#define pool_tgt_rw_sem (p) ((p)->pool_obds.op_rw_sem)
Definition at line 82 of file lod_internal.h.
Referenced by lod_alloc_qos(), lod_alloc_rr(), lod_alloc_specific(), lod_check_index_in_pool(), lod_dump_pool(), lov_dump_pool(), pool_proc_next(), and pool_proc_show().
#define pool_tgt_size (p) ((p)->pool_obds.op_size)
Definition at line 79 of file lod_internal.h.
#define TGT_PTRS 256
Definition at line 135 of file lod_internal.h.
#define TGT_PTRS_PER_BLOCK 256
Definition at line 136 of file lod_internal.h.
Function Documentation
static struct lod_device* dt2lod_dev (struct dt_device * d) [static, read]
Definition at line 336 of file lod_internal.h.
References dt_device::dd_lu_dev, LASSERT, lod_device::lod_dt_dev, and lu_device_is_lod().
Referenced by lod_commit_async(), lod_conf_get(), lod_ro(), lod_root_get(), lod_statfs(), lod_sub_get_thandle(), lod_sync(), lod_trans_create(), lod_trans_start(), and lod_trans_stop().
static struct lu_device* lod2lu_dev (struct lod_device * d) [static, read]
Definition at line 326 of file lod_internal.h.
References dt_device::dd_lu_dev, and lod_device::lod_dt_dev.
Referenced by lod_device_alloc(), lod_fini_distribute_txn(), lod_fld_lookup(), lod_parse_dir_striping(), lod_prep_md_striped_create(), lod_prepare(), lod_prepare_distribute_txn(), lod_process_recovery_updates(), and lod_sub_recovery_thread().
static struct lu_object* lod2lu_obj (struct lod_object * obj) [static, read]
Definition at line 348 of file lod_internal.h.
References dt_object::do_lu, and lod_object::ldo_obj.
Referenced by lod_alloc_specific(), lod_load_striping_locked(), lod_object_alloc(), lod_object_child(), lod_qos_parse_config(), and lod_qos_prep_create().
static struct obd_device* lod2obd (struct lod_device * d) [static, read]
Definition at line 331 of file lod_internal.h.
References dt_device::dd_lu_dev, lu_device::ld_obd, and lod_device::lod_dt_dev.
Referenced by lod_add_device(), lod_alloc_ost_list(), lod_device_fini(), lod_fld_lookup(), lod_generate_and_set_lovea(), lod_load_lmv_shards(), lod_pools_fini(), lod_prep_md_striped_create(), lod_prepare(), lod_prepare_distribute_txn(), lod_process_config(), lod_process_recovery_updates(), lod_putref(), lod_qos_parse_config(), lod_qos_statfs_update(), lod_recovery_complete(), lod_statfs_and_check(), lod_sub_init_llog(), lod_sub_prep_llog(), lod_sub_process_config(), lod_sub_recovery_thread(), lod_sync(), lod_verify_md_striping(), and validate_lod_and_idx().
int lod_add_device (const struct lu_env * env, struct lod_device * lod, char * osp, unsigned index, unsigned gen, int tgt_index, char * type, int active)
Connect LOD to a new OSP and add it to the target table.
Connect to the OSP device passed, initialize all the internal structures related to the device and add it to the target table.
Parameters:
[in] env execution environment for this thread
[in] lod LOD device to be connected to the new OSP
[in] osp name of OSP device name to be added
[in] index index of the new target
[in] gen target's generation number
[in] tgt_index OSP's group
[in] type type of device (mdc or osc)
[in] active state of OSP: 0 - inactive, 1 - active
Return values:
0 if added successfully
negative error number on failure
Definition at line 207 of file lod_lov.c.
References CDEBUG, CERROR, cfs_bitmap_check(), cfs_bitmap_clear(), cfs_bitmap_set(), client_obd::cl_import, client_obd::cl_target_uuid, class_find_client_obd(), obd_device::cli, ptlrpc_client::cli_request_portal, D_CONFIG, D_OTHER, dt_device::dd_lu_dev, ENTRY, GOTO, obd_import::imp_client, obd_import::imp_lock, obd_import::imp_server_timeout, LASSERT, LCFG_CLEANUP, lustre_cfg::lcfg_command, lustre_cfg::lcfg_version, lov_desc::ld_active_tgt_count, lu_device::ld_obd, lu_device::ld_ops, lu_device::ld_site, lov_desc::ld_tgt_count, lu_device_operations::ldo_process_config, lu_device_operations::ldo_recovery_complete, lfsck_add_target(), lod2obd(), lod_device::lod_child, lod_device::lod_desc, lod_device::lod_dt_dev, lod_env_info(), lod_getref(), lod_device::lod_initialized, lod_device::lod_mdt_descs, lod_device::lod_ost_descs, lod_ost_pool_add(), lod_ost_pool_remove(), lod_device::lod_pool_info, lod_putref(), lod_device::lod_recovery_completed, lod_sub_fini_llog(), lod_sub_init_llog(), lod_tgt_desc::ltd_active, ltd_bitmap_resize(), lod_tgt_desc::ltd_exp, lod_tgt_desc::ltd_gen, lod_tgt_desc::ltd_index, lod_tgt_descs::ltd_mutex, lod_tgt_desc::ltd_recovery_thread, LTD_TGT, lod_tgt_desc::ltd_tgt, lod_tgt_descs::ltd_tgt_bitmap, lod_tgt_descs::ltd_tgt_idx, lod_tgt_descs::ltd_tgtnr, lod_tgt_descs::ltd_tgts_size, lod_tgt_desc::ltd_uuid, lod_thread_info::lti_lustre_cfg, lu2dt_dev(), LUSTRE_CFG_VERSION, LUSTRE_OSC_NAME, LUSTRE_OSP_NAME, LUSTRE_VERSION_CODE, max, MDS_INODELOCK_UPDATE, OBD_ALLOC_PTR, obd_connect(), OBD_CONNECT_ACL, OBD_CONNECT_AT, OBD_CONNECT_BULK_MBITS, OBD_CONNECT_FID, OBD_CONNECT_FULL20, OBD_CONNECT_IBITS, OBD_CONNECT_INDEX, OBD_CONNECT_LFSCK, OBD_CONNECT_LRU_RESIZE, OBD_CONNECT_LVB_TYPE, OBD_CONNECT_MDS, OBD_CONNECT_MDS_MDS, OBD_CONNECT_PINGLESS, OBD_CONNECT_REQPORTAL, OBD_CONNECT_SKIP_ORPHAN, OBD_CONNECT_VERSION, obd_disconnect(), OBD_FREE_PTR, obd_device::obd_lu_dev, obd_device::obd_name, obd_str2uuid(), obd_device::obd_uuid, obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_group, obd_connect_data::ocd_ibits_known, obd_connect_data::ocd_index, obd_connect_data::ocd_version, OUT_PORTAL, qos_add_tgt(), RETURN, TGT_PTRS_PER_BLOCK, thread, and obd_device::u.
Referenced by lod_process_config().
int lod_check_index_in_pool (__u32 idx, struct pool_desc * pool)
Check if the specified target exists in the pool.
The caller may not have a reference on pool if it got the pool without calling lod_find_pool() (e.g. directly from the lod pool list)
Parameters:
[in] idx Target index to check
[in] pool Pool in which to check if target is added.
Return values:
0 successfully found index in pool
negative error if device not found in pool
Definition at line 876 of file lod_pool.c.
References ENTRY, EXIT, GOTO, lod_pool_putref(), pool_getref(), pool_tgt_array, pool_tgt_count, and pool_tgt_rw_sem.
Referenced by lod_qos_parse_config(), and lod_verify_striping().
int lod_declare_striped_object (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, const struct lu_buf * lovea, struct thandle * th)
Declare creation of striped object.
The function declares creation stripes for a regular object. The function also declares whether the stripes will be created with non-zero size if previously size was set non-zero on the master object. If object dt is not local, then only fully defined striping can be applied in lovea. Otherwise lovea can be in the form of pattern, see lod_qos_parse_config() for the details.
Parameters:
[in] env execution environment
[in] dt object
[in] attr attributes the stripes will be created with
[in] lovea a buffer containing striping description
[in] th transaction handle
Return values:
0 on success
negative if failed
Definition at line 3337 of file lod_object.c.
References dt_object_child(), dt_object_exists(), dt_object_remote(), ENTRY, GOTO, LASSERT, lu_buf::lb_len, lod_object::ldo_pool, lod_object::ldo_stripenr, lod_declare_init_size(), lod_dt_obj(), lod_env_info(), lod_object_free_striping(), lod_qos_prep_create(), lod_sub_object_declare_xattr_set(), LOV_MAGIC_V1, LOV_MAGIC_V3, lov_mds_md_size(), lod_thread_info::lti_buf, OBD_FAIL_CHECK, OBD_FAIL_MDS_ALLOC_OBDO, RETURN, and XATTR_NAME_LOV.
Referenced by lod_declare_object_create(), and lod_declare_xattr_set().
int lod_del_device (const struct lu_env * env, struct lod_device * lod, struct lod_tgt_descs * ltd, char * osp, unsigned idx, unsigned gen, bool for_ost)
Remove device by name.
Remove a device identified by osp from the target table. Given the device can be in use, the real deletion happens in lod_putref().
Parameters:
[in] env execution environment for this thread
[in] lod LOD device to be connected to the new OSP
[in] ltd target table
[in] osp name of OSP device to be removed
[in] idx index of the target
[in] gen generation number, not used currently
[in] for_ost type of the target: 0 - MDT, 1 - OST
Return values:
0 if the device was scheduled for removal
-EINVAL if no device was found
Definition at line 529 of file lod_lov.c.
References __lod_del_device(), CDEBUG, CERROR, cfs_bitmap_check(), class_find_client_obd(), D_CONFIG, dt_device::dd_lu_dev, ENTRY, EXIT, GOTO, lu_device::ld_obd, lod_device::lod_dt_dev, lod_getref(), lod_putref(), lod_tgt_descs::ltd_mutex, LTD_TGT, lod_tgt_descs::ltd_tgt_bitmap, LUSTRE_OSP_NAME, obd_device::obd_name, obd_str2uuid(), obd_device::obd_uuid, obd_uuid2str(), obd_uuid_equals(), and RETURN.
Referenced by lod_process_config().
static struct lod_object* lod_dt_obj (const struct dt_object * d) [static, read]
Definition at line 359 of file lod_internal.h.
References dt_object::do_lu, and lod_obj().
Referenced by lod_ah_init(), lod_attr_set(), lod_declare_attr_set(), lod_declare_init_size(), lod_declare_object_create(), lod_declare_object_destroy(), lod_declare_striped_object(), lod_declare_xattr_del(), lod_declare_xattr_set_lmv(), lod_dir_declare_create_stripes(), lod_dir_declare_xattr_set(), lod_dir_striping_create(), lod_dir_striping_create_internal(), lod_index_try(), lod_object_create(), lod_object_destroy(), lod_object_lock(), lod_object_replace_parent_fid(), lod_object_unlock(), lod_prep_lmv_md(), lod_prep_md_striped_create(), lod_striped_it_fini(), lod_striped_it_get(), lod_striped_it_init(), lod_striped_it_key(), lod_striped_it_key_size(), lod_striped_it_load(), lod_striped_it_next(), lod_striped_it_put(), lod_striped_it_rec(), lod_striped_it_rec_size(), lod_striped_it_store(), lod_striping_create(), lod_xattr_del(), lod_xattr_del_internal(), lod_xattr_get(), lod_xattr_set(), lod_xattr_set_default_lmv_on_dir(), lod_xattr_set_internal(), lod_xattr_set_lmv(), and lod_xattr_set_lov_on_dir().
int lod_ea_store_resize (struct lod_thread_info * info, size_t size)
Resize per-thread storage to hold specified size.
A helper function to resize per-thread temporary storage. This storage is used to process LOV/LVM EAs and may be quite large. We do not want to allocate/release it every time, so instead we put it into the env and reallocate on demand. The memory is released when the correspondent thread is finished.
Parameters:
[in] info LOD-specific storage in the environment
[in] size new size to grow the buffer to
Return values:
0 on success, -ENOMEM if reallocation failed
Definition at line 596 of file lod_lov.c.
References CDEBUG, D_INFO, LASSERT, LOV_MAGIC_V3, LOV_MAX_STRIPE_COUNT, lov_mds_md_size(), lod_thread_info::lti_ea_store, lod_thread_info::lti_ea_store_size, OBD_ALLOC_LARGE, OBD_FREE_LARGE, RETURN, and size_roundup_power2().
Referenced by lod_dir_striping_create_internal(), lod_generate_and_set_lovea(), lod_get_ea(), lod_object_replace_parent_fid(), lod_prep_lmv_md(), and lod_qos_ost_in_use_clear().
static struct lod_thread_info* lod_env_info (const struct lu_env * env) [static, read]
Definition at line 372 of file lod_internal.h.
References LASSERT, lu_env::le_ctx, lod_thread_key, and lu_context_key_get().
Referenced by lod_add_device(), lod_add_noop_records(), lod_alloc_ost_list(), lod_alloc_qos(), lod_alloc_rr(), lod_alloc_specific(), lod_attr_set(), lod_cache_parent_lmv_striping(), lod_cache_parent_lov_striping(), lod_declare_attr_set(), lod_declare_init_size(), lod_declare_object_destroy(), lod_declare_striped_object(), lod_declare_xattr_set(), lod_dir_declare_create_stripes(), lod_dir_striping_create_internal(), lod_generate_and_set_lovea(), lod_get_ea(), lod_initialize_objects(), lod_it_init(), lod_load_lmv_shards(), lod_load_striping_locked(), lod_name_get(), lod_object_destroy(), lod_object_lock(), lod_object_replace_parent_fid(), lod_parse_dir_striping(), lod_prep_lmv_md(), lod_prepare(), lod_process_recovery_updates(), lod_qos_is_ost_used(), lod_qos_ost_in_use(), lod_qos_ost_in_use_clear(), lod_striped_it_init(), lod_striped_it_next(), lod_sub_prep_llog(), lod_xattr_get(), and lod_xattr_set_lmv().
struct pool_desc* lod_find_pool (struct lod_device * lod, char * poolname) [read]
Find the pool descriptor for the specified pool and return it with a reference to the caller if found.
Parameters:
[in] lod LOD on which the pools are configured
[in] poolname NUL-terminated name of the pool
Return values:
pointer to pool descriptor on success
NULL if poolname could not be found or poolname is empty
Definition at line 909 of file lod_pool.c.
References CDEBUG, cfs_hash_lookup(), D_CONFIG, obd_export::exp_obd, lod_device::lod_child_exp, lod_pool_putref(), lod_device::lod_pools_hash_body, LOV_POOLNAMEF, obd_device::obd_name, and pool_tgt_count.
Referenced by lod_alloc_qos(), lod_alloc_rr(), lod_alloc_specific(), lod_qos_parse_config(), and lod_verify_striping().
int lod_fini_tgt (const struct lu_env * env, struct lod_device * lod, struct lod_tgt_descs * ltd, bool for_ost)
Schedule removal of all the targets from the given target table.
See more details in the description for __lod_del_device()
Parameters:
[in] env execution environment for this thread
[in] lod LOD device the target table belongs to
[in] ltd target table
[in] for_ost type of the target: MDT or OST
Return values:
0 always
Definition at line 490 of file lod_lov.c.
References __lod_del_device(), cfs_foreach_bit, CFS_FREE_BITMAP, lod_getref(), lod_putref(), lod_tgt_descs::ltd_mutex, lod_tgt_descs::ltd_tgt_bitmap, lod_tgt_descs::ltd_tgt_idx, lod_tgt_descs::ltd_tgts_size, OBD_FREE_PTR, and TGT_PTRS.
Referenced by lod_device_fini().
void lod_fix_desc (struct lov_desc * desc)
Used to fix insane default striping.
Parameters:
[in] desc striping description
Definition at line 1263 of file lod_lov.c.
References lov_desc::ld_default_stripe_count, lov_desc::ld_default_stripe_size, lov_desc::ld_pattern, lov_desc::ld_qos_maxage, lod_fix_desc_pattern(), lod_fix_desc_qos_maxage(), lod_fix_desc_stripe_count(), and lod_fix_desc_stripe_size().
Referenced by lod_pools_init().
void lod_fix_desc_pattern (__u32 * val)
Definition at line 1242 of file lod_lov.c.
References LCONSOLE_WARN, and LOV_PATTERN_RAID0.
Referenced by lod_fix_desc().
void lod_fix_desc_qos_maxage (__u32 * val)
Definition at line 1251 of file lod_lov.c.
References LOV_DESC_QOS_MAXAGE_DEFAULT.
Referenced by lod_fix_desc().
void lod_fix_desc_stripe_count (__u32 * val)
Definition at line 1236 of file lod_lov.c.
Referenced by lod_fix_desc().
void lod_fix_desc_stripe_size (__u64 * val)
Definition at line 1220 of file lod_lov.c.
References LCONSOLE_INFO, LCONSOLE_WARN, LOV_DESC_STRIPE_SIZE_DEFAULT, LOV_MIN_STRIPE_SIZE, and LPU64.
Referenced by lod_fix_desc().
int lod_fld_lookup (const struct lu_env * env, struct lod_device * lod, const struct lu_fid * fid, __u32 * tgt, int * flags)
Definition at line 121 of file lod_dev.c.
References CDEBUG, CERROR, D_INFO, DFID, ENTRY, fid_idif_ost_idx(), fid_is_idif(), fid_is_sane(), fid_is_update_log(), fid_is_update_log_dir(), fid_oid(), fid_seq_in_fldb(), fld_range_set_type(), fld_server_lookup(), LASSERT, lod2lu_dev(), lod2obd(), lod_device::lod_initialized, LPX64, lu_seq_range::lsr_flags, lu_seq_range::lsr_index, LU_SEQ_RANGE_MDT, LU_SEQ_RANGE_OST, lu_site2seq(), PFID, RETURN, seq_server_site::ss_node_id, and seq_server_site::ss_server_fld.
Referenced by lod_generate_and_set_lovea(), lod_object_init(), lod_parse_dir_striping(), lod_prep_lmv_md(), and lod_sub_get_thandle().
int lod_generate_and_set_lovea (const struct lu_env * env, struct lod_object * lo, struct thandle * th)
Make LOV EA for striped object.
Generate striping information and store it in the LOV EA of the given object. The caller must ensure nobody else is calling the function against the object concurrently. The transaction must be started. FLDB service must be running as well; it's used to map FID to the target, which is stored in LOV EA.
Parameters:
[in] env execution environment for this thread
[in] lo LOD object
[in] th transaction handle
Return values:
0 if LOV EA is stored successfully
negative error number on failure
Definition at line 636 of file lod_lov.c.
References CERROR, cfs_fail_val, cpu_to_le16, cpu_to_le32, DFID, dt_object::do_lu, dt_object_child(), ENTRY, lu_fid::f_oid, fid_to_lmm_oi(), fid_to_ostid(), lov_ost_data_v1::l_ost_gen, lov_ost_data_v1::l_ost_idx, lov_ost_data_v1::l_ost_oi, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lod_object::ldo_obj, lod_object::ldo_pattern, lod_object::ldo_pool, lod_object::ldo_released_stripenr, lod_object::ldo_stripe, lod_object::ldo_stripe_size, lod_object::ldo_stripenr, lov_mds_md_v1::lmm_layout_gen, lov_mds_md_v1::lmm_magic, lov_mds_md_v3::lmm_objects, lov_mds_md_v1::lmm_objects, lov_mds_md_v1::lmm_oi, lmm_oi_cpu_to_le(), lov_mds_md_v1::lmm_pattern, lov_mds_md_v3::lmm_pool_name, lov_mds_md_v1::lmm_stripe_count, lov_mds_md_v1::lmm_stripe_size, lu_object::lo_dev, lod2obd(), lod_ea_store_resize(), lod_env_info(), lod_fld_lookup(), lod_object_free_striping(), lod_sub_object_xattr_set(), LOV_MAGIC_V1, LOV_MAGIC_V3, lov_mds_md_size(), LOV_PATTERN_F_RELEASED, LOV_PATTERN_RAID0, lod_thread_info::lti_buf, lod_thread_info::lti_ea_store, lod_thread_info::lti_ea_store_size, lod_thread_info::lti_fid, lod_thread_info::lti_ostid, lu2lod_dev(), lu_object_fid(), LU_SEQ_RANGE_OST, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_BAD_LMMOI, OBD_FAIL_LFSCK_MULTIPLE_REF, OBD_FAIL_MDS_FLD_LOOKUP, ost_id::oi, ostid_cpu_to_le(), PFID, RETURN, strlcpy(), and XATTR_NAME_LOV.
Referenced by lod_striping_create().
static int lod_get_default_lmv_ea (const struct lu_env * env, struct lod_object * lo) [inline, static]
Definition at line 437 of file lod_internal.h.
References lod_get_ea(), and XATTR_NAME_DEFAULT_LMV.
Referenced by lod_cache_parent_lmv_striping().
int lod_get_ea (const struct lu_env * env, struct lod_object * lo, const char * name)
Get LOV EA.
Fill lti_ea_store buffer in the environment with a value for the given EA. The buffer is reallocated if the value doesn't fit.
Parameters:
[in,out] env execution environment for this thread .lti_ea_store buffer is filled with EA's value
[in] lo LOD object
[in] name name of the EA
Return values:
0 if EA is fetched successfully
negative error number on failure
Definition at line 748 of file lod_lov.c.
References dt_object_child(), dt_xattr_get(), ENTRY, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lod_object::ldo_obj, lod_ea_store_resize(), lod_env_info(), lod_thread_info::lti_buf, lod_thread_info::lti_ea_store, lod_thread_info::lti_ea_store_size, LU_BUF_NULL, RETURN, and unlikely.
Referenced by lod_get_default_lmv_ea(), lod_get_lmv_ea(), and lod_get_lov_ea().
static int lod_get_lmv_ea (const struct lu_env * env, struct lod_object * lo) [inline, static]
Definition at line 431 of file lod_internal.h.
References lod_get_ea(), and XATTR_NAME_LMV.
Referenced by lod_load_striping_locked().
static int lod_get_lov_ea (const struct lu_env * env, struct lod_object * lo) [inline, static]
Definition at line 425 of file lod_internal.h.
References lod_get_ea(), and XATTR_NAME_LOV.
Referenced by lod_attr_set(), lod_cache_parent_lov_striping(), and lod_load_striping_locked().
void lod_getref (struct lod_tgt_descs * ltd)
Increase reference count on the target table.
Increase reference count on the target table usage to prevent racing with addition/deletion. Any function that expects the table to remain stationary must take a ref.
Parameters:
[in] ltd target table (lod_ost_descs or lod_mdt_descs)
Definition at line 55 of file lod_lov.c.
References lod_tgt_descs::ltd_mutex, lod_tgt_descs::ltd_refcount, and lod_tgt_descs::ltd_rw_sem.
Referenced by lod_add_device(), lod_del_device(), lod_fini_tgt(), lod_initialize_objects(), lod_obd_get_info(), lod_obd_set_info_async(), lod_object_init(), lod_pool_add(), lod_pool_remove(), lod_qos_prep_create(), lod_recovery_complete(), lod_sub_fini_all_llogs(), lod_sub_process_config(), lod_sub_stop_recovery_threads(), and lod_sync().
int lod_initialize_objects (const struct lu_env * env, struct lod_object * lo, struct lov_ost_data_v1 * objs)
Instantiate objects for stripes.
Allocate and initialize LU-objects representing the stripes. The number of the stripes (ldo_stripenr) must be initialized already. The caller must ensure nobody else is calling the function on the object at the same time. FLDB service must be running to be able to map a FID to the targets and find appropriate device representing that target.
Parameters:
[in] env execution environment for this thread
[in,out] lo LOD object
[in] objs an array of IDs to creates the objects from
Return values:
0 if the objects are instantiated successfully
negative error number on failure
Definition at line 839 of file lod_lov.c.
References DFID, dt_object::do_lu, ENTRY, fid_is_sane(), GOTO, LASSERT, LASSERTF, lu_device::ld_type, lod_object::ldo_obj, lod_object::ldo_stripe, lod_object::ldo_stripe_size, lod_object::ldo_stripenr, lod_object::ldo_stripes_allocated, le32_to_cpu, lu_object::lo_dev, lu_object::lo_header, lod_env_info(), lod_getref(), lod_device::lod_ost_descs, lod_putref(), lovea_slot_is_dummy(), lod_thread_info::lti_fid, lod_thread_info::lti_ostid, lu2lod_dev(), lu_object_find_at(), lu_object_locate(), lu_object_put(), OBD_ALLOC, OBD_FREE, OST_TGT, ostid_le_to_cpu(), ostid_to_fid(), PFID, RETURN, unlikely, and validate_lod_and_idx().
Referenced by lod_parse_striping(), and lod_use_defined_striping().
int lod_load_lmv_shards (const struct lu_env * env, struct lod_object * lo, struct lu_buf * buf, bool resize)
Append the FID for each shard of the striped directory after the given LMV EA header.
To simplify striped directory and the consistency verification, we only store the LMV EA header on disk, for both master object and slave objects. When someone wants to know the whole LMV EA, such as client readdir(), we can build the entrie LMV EA on the MDT side (in RAM) via iterating the sub-directory entries that are contained in the master object of the stripe directory.
For the master object of the striped directroy, the valid name for each shard is composed of the ${shard_FID}:${shard_idx}.
There may be holes in the LMV EA if some shards' name entries are corrupted or lost.
Parameters:
[in] env pointer to the thread context
[in] lo pointer to the master object of the striped directory
[in] buf pointer to the lu_buf which will hold the LMV EA
[in] resize whether re-allocate the buffer if it is not big enough
Return values:
positive size of the LMV EA
0 for nothing to be loaded
negative error number on failure
Definition at line 776 of file lod_object.c.
References CDEBUG, CERROR, D_ERROR, D_INFO, DFID, dt_index_operations::dio_it, dt_object::do_index_ops, dt_object::do_lu, dt_object_child(), dt_try_as_dir(), ENTRY, fid_is_zero(), fid_le_to_cpu(), FID_LEN, dt_index_operations::dt_it_ops::init, lu_buf::lb_buf, lu_buf::lb_len, lod_object::ldo_obj, le16_to_cpu, le32_to_cpu, LMV_HASH_FLAG_MIGRATION, lmv_mds_md_v1::lmv_hash_type, lmv_mds_md_v1::lmv_magic, LMV_MAGIC_V1, lmv_mds_md_size(), lmv_mds_md_v1::lmv_stripe_count, lmv_mds_md_v1::lmv_stripe_fids, lu_object::lo_dev, lod2obd(), lod_env_info(), lod_device::lod_lmv_failout, lod_thread_info::lti_key, lu2lod_dev(), lu_buf_alloc(), lu_object_fid(), LUDA_64BITHASH, name, PFID, RETURN, stripes, and unlikely.
Referenced by lod_load_striping_locked(), and lod_xattr_get().
int lod_load_striping (const struct lu_env * env, struct lod_object * lo)
A generic function to initialize the stripe objects.
A protected version of lod_load_striping_locked() - load the striping information from storage, parse that and instantiate LU objects to represent the stripes. The LOD object lo supplies a pointer to the next sub-object in the LU stack so we can lock it. Also use lo to return an array of references to the newly instantiated objects.
Parameters:
[in] env execution environment for this thread
[in,out] lo LOD object, where striping is stored and which gets an array of references
Return values:
0 if parsing and object creation succeed
negative error number on failure
Definition at line 1067 of file lod_lov.c.
References dt_object_child(), dt_write_lock(), dt_write_unlock(), lod_object::ldo_obj, and lod_load_striping_locked().
Referenced by lod_ah_init(), lod_declare_attr_set(), lod_declare_object_destroy(), lod_declare_xattr_del(), lod_dir_declare_xattr_set(), lod_object_lock(), and lod_object_replace_parent_fid().
int lod_load_striping_locked (const struct lu_env * env, struct lod_object * lo)
Initialize the object representing the stripes.
Unless the stripes are initialized already, fetch LOV (for regular objects) or LMV (for directory objects) EA and call lod_parse_striping() to instantiate the objects representing the stripes.
Parameters:
[in] env execution environment for this thread
[in,out] lo LOD object
Return values:
0 if parsing and object creation succeed
negative error number on failure
Definition at line 988 of file lod_lov.c.
References buf, dt_object_child(), dt_object_exists(), ENTRY, GOTO, lu_buf::lb_buf, lu_buf::lb_len, lod_object::ldo_dir_slave_stripe, lod_object::ldo_obj, lod_object::ldo_stripe, lod_object::ldo_striping_cached, lod2lu_obj(), lod_env_info(), lod_get_lmv_ea(), lod_get_lov_ea(), lod_load_lmv_shards(), lod_parse_dir_striping(), lod_parse_striping(), lod_thread_info::lti_buf, lod_thread_info::lti_ea_store, lod_thread_info::lti_ea_store_size, lu_object_attr(), OBD_FREE_LARGE, and RETURN.
Referenced by lod_index_try(), and lod_load_striping().
static struct lu_name* lod_name_get (const struct lu_env * env, const void * area, int len) [static, read]
Definition at line 381 of file lod_internal.h.
References lu_name::ln_name, lu_name::ln_namelen, lod_env_info(), and lod_thread_info::lti_name.
Referenced by lod_dir_declare_create_stripes(), and lod_xattr_set_lmv().
static struct lod_object* lod_obj (const struct lu_object * o) [static, read]
Definition at line 353 of file lod_internal.h.
References dt_object::do_lu, LASSERT, lod_object::ldo_obj, lu_object::lo_dev, and lu_device_is_lod().
Referenced by lod_dt_obj(), and lod_object_alloc().
static struct dt_object* lod_object_child (struct lod_object * o) [static, read]
Definition at line 364 of file lod_internal.h.
References dt_object::do_lu, lod2lu_obj(), and lu_object_next().
void lod_object_free_striping (const struct lu_env * env, struct lod_object * lo)
Release resources associated with striping.
If the object is striped (regular or directory), then release the stripe objects references and free the ldo_stripe array.
Parameters:
[in] env execution environment
[in] lo object
Definition at line 4168 of file lod_object.c.
References dt_object::do_lu, LASSERT, lod_object::ldo_dir_stripe, lod_object::ldo_pattern, lod_object::ldo_stripe, lod_object::ldo_stripenr, lod_object::ldo_stripes_allocated, lod_object::ldo_striping_cached, lu_object_put(), OBD_FREE, and OBD_FREE_PTR.
Referenced by lod_declare_striped_object(), lod_declare_xattr_set_lmv(), lod_generate_and_set_lovea(), lod_object_free(), lod_parse_dir_striping(), lod_xattr_del(), and lod_xattr_set().
int lod_object_set_pool (struct lod_object * o, char * pool)
Initialize a pool the object belongs to.
When a striped object is being created, striping configuration may demand the stripes are allocated on a limited set of the targets. These limited sets are known as "pools". So we copy a pool name into the object and later actual creation methods (like lod_object_create()) will use this information to allocate the stripes properly.
Parameters:
[in] o object
[in] pool pool name
Definition at line 2868 of file lod_object.c.
References lod_object::ldo_pool, OBD_ALLOC, and OBD_FREE.
Referenced by lod_ah_init(), lod_cache_parent_lov_striping(), lod_lov_stripe_cache_clear(), lod_object_free(), lod_parse_striping(), lod_qos_parse_config(), and lod_use_defined_striping().
int lod_ost_pool_add (struct ost_pool * op, __u32 idx, unsigned int min_count)
Add a new target to an existing pool.
Add a new target device to the pool previously created and returned by lod_pool_new(). Each target can only be in each pool at most one time.
Parameters:
[in] op target pool to add new entry
[in] idx pool index number to add to the op array
[in] min_count minimum number of entries to expect in the pool
Return values:
0 if target could be added to the pool
negative error if target idx was not added
Definition at line 537 of file lod_pool.c.
References ENTRY, EXIT, GOTO, lod_ost_pool_extend(), ost_pool::op_array, ost_pool::op_count, and ost_pool::op_rw_sem.
Referenced by lod_add_device(), and lod_pool_add().
int lod_ost_pool_extend (struct ost_pool * op, unsigned int min_count)
Increase the op_array size to hold more targets in this pool.
The size is increased to at least min_count, but may be larger for an existing pool since ->op_array[] is growing exponentially. Caller must hold write op_rwlock.
Parameters:
[in] op pool structure
[in] min_count minimum number of entries to handle
Return values:
0 on success
negative error number on failure.
Definition at line 500 of file lod_pool.c.
References LASSERT, max, OBD_ALLOC, OBD_FREE, ost_pool::op_array, ost_pool::op_count, and ost_pool::op_size.
Referenced by lod_ost_pool_add(), and lod_qos_calc_rr().
int lod_ost_pool_free (struct ost_pool * op)
Free the pool after it was emptied and removed from /proc.
Note that all of the child/target entries referenced by this pool must have been removed by lod_ost_pool_remove() before it can be deleted from memory.
Parameters:
[in] op pool to be freed.
Return values:
0 on success or if pool was already freed
Definition at line 611 of file lod_pool.c.
References ENTRY, OBD_FREE, ost_pool::op_array, ost_pool::op_count, ost_pool::op_rw_sem, ost_pool::op_size, and RETURN.
Referenced by lod_pool_new(), lod_pool_putref(), lod_pools_fini(), and lod_pools_init().
int lod_ost_pool_init (struct ost_pool * op, unsigned int count)
Definition at line 468 of file lod_pool.c.
References ENTRY, EXIT, OBD_ALLOC, ost_pool::op_array, ost_pool::op_count, ost_pool::op_rw_sem, ost_pool::op_size, POOL_INIT_COUNT, and RETURN.
Referenced by lod_pool_new(), and lod_pools_init().
int lod_ost_pool_remove (struct ost_pool * op, __u32 idx)
Remove an existing pool from the system.
The specified pool must have previously been allocated by lod_pool_new() and not have any target members in the pool. If the removed target is not the last, compact the array to remove empty spaces.
Parameters:
[in] op pointer to the original data structure
[in] idx target index to be removed
Return values:
0 on success
negative error number on failure
Definition at line 577 of file lod_pool.c.
References ENTRY, EXIT, ost_pool::op_array, ost_pool::op_count, ost_pool::op_rw_sem, and RETURN.
Referenced by lod_add_device(), lod_pool_remove(), and lod_putref().
int lod_parse_dir_striping (const struct lu_env * env, struct lod_object * lo, const struct lu_buf * buf)
Create in-core represenation for a striped directory.
Parse the buffer containing LMV EA and instantiate LU objects representing the stripe objects. The pointers to the objects are stored in ldo_stripe field of lo. This function is used when we need to access an already created object (i.e. load from a disk).
Parameters:
[in] env execution environment
[in] lo lod object
[in] buf buffer containing LMV EA
Return values:
0 on success
negative if failed
Definition at line 1462 of file lod_object.c.
References dt_object::do_lu, dt_locate_at(), ENTRY, fid_is_sane(), fid_le_to_cpu(), GOTO, LASSERT, lu_buf::lb_buf, lu_device::ld_site, lod_object::ldo_dir_slave_stripe, lod_object::ldo_obj, lod_object::ldo_stripe, lod_object::ldo_stripenr, lod_object::ldo_stripes_allocated, le32_to_cpu, LMV_HASH_FLAG_MIGRATION, lmv_mds_md_v1::lmv_hash_type, lmv_mds_md_v1::lmv_magic, LMV_MAGIC_STRIPE, LMV_MAGIC_V1, lmv_mds_md::lmv_md_v1, lmv_mds_md_v1::lmv_stripe_count, lmv_mds_md_v1::lmv_stripe_fids, lu_object::lo_dev, lod2lu_dev(), lod_device::lod_child, lod_env_info(), lod_fld_lookup(), lod_device::lod_mdt_descs, lod_object_free_striping(), lu_site::ls_top_dev, lod_tgt_desc::ltd_tgt, LTD_TGT, lod_thread_info::lti_fid, lu2lod_dev(), LU_SEQ_RANGE_ANY, OBD_ALLOC, and RETURN.
Referenced by lod_load_striping_locked().
int lod_parse_striping (const struct lu_env * env, struct lod_object * lo, const struct lu_buf * buf)
Instantiate objects for striping.
Parse striping information in buf and instantiate the objects representing the stripes.
Parameters:
[in] env execution environment for this thread
[in] lo LOD object
[in] buf buffer storing LOV EA to parse
Return values:
0 if parsing and objects creation succeed
negative error number on failure
Definition at line 927 of file lod_lov.c.
References ENTRY, GOTO, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lod_object::ldo_layout_gen, lod_object::ldo_pattern, lod_object::ldo_stripe_size, lod_object::ldo_stripenr, le16_to_cpu, le32_to_cpu, lov_mds_md_v1::lmm_layout_gen, lov_mds_md_v1::lmm_magic, lov_mds_md_v1::lmm_objects, lov_mds_md_v3::lmm_objects, lov_mds_md_v1::lmm_pattern, lov_mds_md_v3::lmm_pool_name, lov_mds_md_v1::lmm_stripe_count, lov_mds_md_v1::lmm_stripe_size, lod_initialize_objects(), lod_object_set_pool(), LOV_MAGIC_V1, LOV_MAGIC_V3, lov_mds_md_size(), lov_pattern, LOV_PATTERN_F_RELEASED, LOV_PATTERN_RAID0, and RETURN.
Referenced by lod_load_striping_locked().
int lod_pool_add (struct obd_device * obd, char * poolname, char * ostname)
Add a single target device to the named pool.
Add the target specified by ostname to the specified poolname.
Parameters:
[in] obd OBD device on which to add the pool
[in] poolname name of the pool to which to add the target ostname
[in] ostname name of the target device to be added
Return values:
0 if ostname was (previously) added to the named pool
negative error number on failure
Definition at line 766 of file lod_pool.c.
References CDEBUG, cfs_hash_lookup(), D_CONFIG, ENTRY, EXIT, GOTO, lod_foreach_ost, lod_getref(), lod_device::lod_ost_descs, lod_ost_pool_add(), lod_pool_putref(), lod_device::lod_pools_hash_body, lod_putref(), LOV_POOLNAMEF, lod_qos_rr::lqr_dirty, lu2lod_dev(), obd_device::obd_lu_dev, obd_str2uuid(), obd_uuid_equals(), OST_TGT, pool_desc::pool_obds, pool_desc::pool_rr, pool_tgt_count, and RETURN.
int lod_pool_del (struct obd_device * obd, char * poolname)
Remove the named pool from the OBD device.
Parameters:
[in] obd OBD device on which pool was previously created
[in] poolname name of pool to remove from obd
Return values:
0 on successfully removing the pool
negative error numbers for failures
Definition at line 726 of file lod_pool.c.
References CDEBUG, cfs_hash_del_key(), D_INFO, ENTRY, list_del_init(), lod_device::lod_pool_count, lod_pool_putref(), lod_device::lod_pools_hash_body, lprocfs_remove(), lu2lod_dev(), obd_device::obd_dev_lock, obd_device::obd_lu_dev, pool_desc::pool_list, pool_desc::pool_proc_entry, and RETURN.
Referenced by lod_pools_fini().
int lod_pool_new (struct obd_device * obd, char * poolname)
Allocate a new pool for the specified device.
Allocate a new pool_desc structure for the specified new_pool device to create a pool with the given poolname. The new pool structure is created with a single reference, and is freed when the reference count drops to zero.
Parameters:
[in] obd Lustre OBD device on which to add a pool iterator
[in] poolname the name of the pool to be created
Return values:
0 in case of success
negative error code in case of error
Definition at line 643 of file lod_pool.c.
References CDEBUG, cfs_hash_add_unique(), D_CONFIG, D_INFO, ENTRY, GOTO, INIT_HLIST_NODE, list_add_tail(), list_del_init(), lod_ost_pool_free(), lod_ost_pool_init(), lod_device::lod_pool_count, lod_device::lod_pool_list, lod_device::lod_pool_proc_entry, lod_pool_putref(), lod_device::lod_pools_hash_body, lod_qos_rr_init(), LOV_MAXPOOLNAME, LOV_POOLNAMEF, lprocfs_add_simple(), lprocfs_remove(), lod_qos_rr::lqr_pool, lu2lod_dev(), OBD_ALLOC_PTR, obd_device::obd_dev_lock, OBD_FREE_PTR, obd_device::obd_lu_dev, obd_device::obd_name, pool_getref(), pool_desc::pool_hash, pool_desc::pool_list, pool_desc::pool_lobd, pool_desc::pool_name, pool_desc::pool_obds, pool_desc::pool_proc_entry, pool_proc_operations, pool_desc::pool_refcount, pool_desc::pool_rr, RETURN, and strlcpy().
void lod_pool_putref (struct pool_desc * pool)
Drop a reference on the specified pool and free its memory if needed.
One reference is held by the LOD OBD device while it is configured, from the time the configuration log defines the pool until the time when it is dropped when the LOD OBD is cleaned up or the pool is deleted. This means that the pool will not be freed while the LOD device is configured, unless it is explicitly destroyed by the sysadmin. The pool structure is freed after the last reference on the structure is released.
Parameters:
[in] pool pool descriptor to drop reference on and possibly free
Definition at line 95 of file lod_pool.c.
References CDEBUG, D_INFO, EXIT, hlist_unhashed(), LASSERT, list_empty(), lod_ost_pool_free(), lod_qos_rr::lqr_pool, OBD_FREE_PTR, pool_desc::pool_hash, pool_desc::pool_list, pool_desc::pool_obds, pool_desc::pool_proc_entry, pool_desc::pool_refcount, and pool_desc::pool_rr.
Referenced by lod_alloc_qos(), lod_alloc_rr(), lod_alloc_specific(), lod_check_index_in_pool(), lod_dump_pool(), lod_find_pool(), lod_pool_add(), lod_pool_del(), lod_pool_new(), lod_pool_remove(), lod_qos_parse_config(), lod_verify_striping(), pool_proc_start(), and pool_proc_stop().
int lod_pool_remove (struct obd_device * obd, char * poolname, char * ostname)
Remove the named target from the specified pool.
Remove one target named ostname from poolname. The ostname is searched for in the lod_device lod_ost_bitmap array, to ensure the specified name actually exists in the pool.
Parameters:
[in] obd OBD device from which to remove poolname
[in] poolname name of the pool to be changed
[in] ostname name of the target to remove from poolname
Return values:
0 on successfully removing ostname from the pool
negative number on error (e.g. ostname not in pool)
Definition at line 823 of file lod_pool.c.
References CDEBUG, cfs_foreach_bit, cfs_hash_lookup(), D_CONFIG, ENTRY, EXIT, GOTO, lod_getref(), lod_device::lod_ost_descs, lod_ost_pool_remove(), lod_pool_putref(), lod_device::lod_pools_hash_body, lod_putref(), LOV_POOLNAMEF, lod_qos_rr::lqr_dirty, lu2lod_dev(), obd_device::obd_lu_dev, obd_str2uuid(), obd_uuid_equals(), OST_TGT, pool_desc::pool_obds, pool_desc::pool_rr, and RETURN.
int lod_pools_fini (struct lod_device * lod)
Release the structures describing the pools.
Parameters:
[in] lod LOD device from which we release the structures
Return values:
0 always
Definition at line 1372 of file lod_lov.c.
References CDEBUG, cfs_hash_putref(), D_INFO, ENTRY, list_for_each_entry_safe, lod2obd(), lod_ost_pool_free(), lod_pool_del(), lod_device::lod_pool_info, lod_device::lod_pool_list, lod_device::lod_pools_hash_body, lod_device::lod_qos, lod_qos::lq_rr, lod_qos_rr::lqr_pool, pool_desc::pool_list, pool_desc::pool_name, and RETURN.
Referenced by lod_device_fini(), and lod_init0().
int lod_pools_init (struct lod_device * lod, struct lustre_cfg * lcfg)
Initialize the structures used to store pools and default striping.
Parameters:
[in] lod LOD device
[in] lcfg configuration structure storing default striping.
Return values:
0 if initialization succeeds
negative error number on failure
Definition at line 1280 of file lod_lov.c.
References __swab32, CDEBUG, CERROR, cfs_hash_create(), CFS_HASH_DEFAULT, CFS_HASH_MAX_THETA, CFS_HASH_MIN_THETA, cfs_hash_putref(), class_name2obd(), D_OTHER, dt_device::dd_lu_dev, ENTRY, GOTO, HASH_POOLS_BKT_BITS, HASH_POOLS_CUR_BITS, HASH_POOLS_MAX_BITS, INIT_LIST_HEAD, LASSERT, lov_desc::ld_active_tgt_count, lod_device::lod_desc, lod_device::lod_dt_dev, lod_fix_desc(), lod_ost_pool_free(), lod_ost_pool_init(), lod_device::lod_pool_count, lod_device::lod_pool_info, lod_device::lod_pool_list, lod_device::lod_pools_hash_body, lod_device::lod_qos, lod_qos_rr_init(), lod_device::lod_sp_me, LOV_DESC_MAGIC, lod_qos::lq_dirty, lod_qos::lq_oss_list, lod_qos::lq_prio_free, lod_qos::lq_reset, lod_qos::lq_rr, lod_qos::lq_rw_sem, lod_qos::lq_threshold_rr, lod_qos_rr::lqr_dirty, lod_qos_rr::lqr_pool, lustre_cfg_buf(), LUSTRE_CFG_BUFLEN, lustre_cfg_string(), LUSTRE_SP_CLI, lustre_swab_lov_desc(), obd_device::obd_lu_dev, obd_device::obd_name, pool_hash_operations, and RETURN.
Referenced by lod_init0().
void lod_procfs_fini (struct lod_device * lod)
Referenced by lod_device_fini().
int lod_procfs_init (struct lod_device * lod)
Referenced by lod_init0().
void lod_putref (struct lod_device * lod, struct lod_tgt_descs * ltd)
Decrease reference count on the target table.
Companion of lod_getref() to release a reference on the target table. If this is the last reference and the OST entry was scheduled for deletion, the descriptor is removed from the table.
Parameters:
[in] lod LOD device from which we release a reference
[in] ltd target table (lod_ost_descs or lod_mdt_descs)
Definition at line 73 of file lod_lov.c.
References CDEBUG, CERROR, cfs_bitmap_clear(), cfs_foreach_bit, D_CONFIG, INIT_LIST_HEAD, LASSERT, lov_desc::ld_active_tgt_count, list_add(), list_del(), list_for_each_entry_safe, lod2obd(), lod_device::lod_desc, lod_device::lod_ost_descs, lod_ost_pool_remove(), lod_device::lod_pool_info, lod_tgt_desc::ltd_active, lod_tgt_descs::ltd_death_row, lod_tgt_desc::ltd_exp, lod_tgt_desc::ltd_kill, lod_tgt_descs::ltd_mutex, lod_tgt_desc::ltd_reap, lod_tgt_descs::ltd_refcount, lod_tgt_descs::ltd_rw_sem, LTD_TGT, lod_tgt_descs::ltd_tgt_bitmap, lod_tgt_descs::ltd_tgtnr, lod_tgt_desc::ltd_uuid, obd_disconnect(), OBD_FREE_PTR, obd_uuid2str(), and qos_del_tgt().
Referenced by lod_add_device(), lod_del_device(), lod_fini_tgt(), lod_initialize_objects(), lod_obd_get_info(), lod_obd_set_info_async(), lod_object_init(), lod_pool_add(), lod_pool_remove(), lod_qos_prep_create(), lod_recovery_complete(), lod_sub_fini_all_llogs(), lod_sub_process_config(), lod_sub_stop_recovery_threads(), and lod_sync().
int lod_qos_prep_create (const struct lu_env * env, struct lod_object * lo, struct lu_attr * attr, const struct lu_buf * buf, struct thandle * th)
Create a striping for an obejct.
The function creates a new striping for the object. A buffer containing configuration hints can be provided optionally. The function tries QoS algorithm first unless free space is distributed evenly among OSTs, but by default RR algorithm is preferred due to internal concurrency (QoS is serialized). The caller must ensure no concurrent calls to the function are made against the same object.
Parameters:
[in] env execution environment for this thread
[in] lo LOD object
[in] attr attributes OST objects will be declared with
[in] buf suggested striping configuration or NULL
[in] th transaction handle
Return values:
0 on success
negative negated errno on error
Definition at line 1848 of file lod_qos.c.
References CDEBUG, CERROR, D_OTHER, ENTRY, GOTO, LASSERT, lu_buf::lb_buf, lov_desc::ld_tgt_count, lod_object::ldo_def_stripe_offset, lod_object::ldo_stripe, lod_object::ldo_stripenr, lod_object::ldo_stripes_allocated, likely, lod2lu_obj(), lod_alloc_ost_list(), lod_alloc_qos(), lod_alloc_rr(), lod_alloc_specific(), lod_device::lod_desc, lod_get_stripecnt(), lod_getref(), lod_device::lod_ost_descs, lod_putref(), lod_qos_parse_config(), lod_qos_statfs_update(), lod_sub_object_declare_create(), LOV_MAGIC, LOV_OFFSET_DEFAULT, LOV_USER_MAGIC_SPECIFIC, lov_user_md, LOV_USES_ASSIGNED_STRIPE, lu2lod_dev(), lu_object_put(), OBD_ALLOC, OBD_FREE, and RETURN.
Referenced by lod_declare_striped_object().
void lod_qos_rr_init (struct lod_qos_rr * lqr)
Definition at line 534 of file lod_qos.c.
References lod_qos_rr::lqr_alloc, and lod_qos_rr::lqr_dirty.
Referenced by lod_pool_new(), and lod_pools_init().
int lod_striping_create (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, struct dt_object_format * dof, struct thandle * th)
Creation of a striped regular object.
The function is called to create the stripe objects for a regular striped file. This can happen at the initial object creation or when the caller asks LOD to do so using ->do_xattr_set() method (so called late striping). Notice all the information are already prepared in the form of the list of objects (ldo_stripe field). This is done during declare phase.
Parameters:
[in] env execution environment
[in] dt object
[in] attr attributes the stripes will be created with
[in] dof format of stripes (see OSD API description)
[in] th transaction handle
Return values:
0 on success
negative if failed
Definition at line 3530 of file lod_object.c.
References ENTRY, LASSERT, lod_object::ldo_stripe, lod_object::ldo_stripenr, lod_object::ldo_striping_cached, lod_dt_obj(), lod_generate_and_set_lovea(), lod_sub_object_create(), and RETURN.
Referenced by lod_object_create(), and lod_xattr_set().
void lod_sub_fini_llog (const struct lu_env * env, struct dt_device * dt, struct ptlrpc_thread * thread)
finish sub llog context
Stop update recovery thread for the sub device, then cleanup the correspondent llog ctxt.
Parameters:
[in] env execution environment
[in] lod lod device to do update recovery
[in] thread recovery thread on this sub device
Definition at line 482 of file lod_dev.c.
References CDEBUG, D_INFO, dt_device::dd_lu_dev, ENTRY, lu_device::ld_obd, llog_cat_close(), llog_cleanup(), llog_get_context(), LLOG_UPDATELOG_ORIG_CTXT, llog_ctxt::loc_handle, obd_device::obd_name, RETURN_EXIT, SVC_RUNNING, SVC_STOPPED, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, and ptlrpc_thread::t_flags.
Referenced by lod_add_device(), lod_process_config(), lod_sub_fini_all_llogs(), and lod_sub_init_llog().
struct thandle* lod_sub_get_thandle (const struct lu_env * env, struct thandle * th, const struct dt_object * sub_obj, bool * record_update) [read]
Definition at line 57 of file lod_sub_object.c.
References dt_object::do_lu, dt2lod_dev(), dt_object_remote(), ENTRY, fid_is_sane(), fid_is_zero(), lod_fld_lookup(), lu_object_fid(), LU_SEQ_RANGE_ANY, LU_SEQ_RANGE_OST, RETURN, thandle::th_complex, thandle::th_dev, thandle::th_result, thandle::th_top, thandle_get_sub(), top_thandle::tt_master_sub_thandle, and top_thandle::tt_multiple_thandle.
Referenced by lod_sub_object_attr_set(), lod_sub_object_create(), lod_sub_object_declare_attr_set(), lod_sub_object_declare_create(), lod_sub_object_declare_delete(), lod_sub_object_declare_destroy(), lod_sub_object_declare_insert(), lod_sub_object_declare_punch(), lod_sub_object_declare_ref_add(), lod_sub_object_declare_ref_del(), lod_sub_object_declare_write(), lod_sub_object_declare_xattr_del(), lod_sub_object_declare_xattr_set(), lod_sub_object_delete(), lod_sub_object_destroy(), lod_sub_object_index_insert(), lod_sub_object_punch(), lod_sub_object_ref_add(), lod_sub_object_ref_del(), lod_sub_object_write(), lod_sub_object_xattr_del(), and lod_sub_object_xattr_set().
int lod_sub_init_llog (const struct lu_env * env, struct lod_device * lod, struct dt_device * dt)
Init sub llog context.
Setup update llog ctxt for update recovery threads, then start the recovery thread (lod_sub_recovery_thread) to read update llog from the correspondent MDT to do update recovery.
Parameters:
[in] env execution environment
[in] lod lod device to do update recovery
[in] dt sub dt device for which the recovery thread is
Return values:
0 if initialization succeeds.
negative errno if initialization fails.
Definition at line 578 of file lod_dev.c.
References CDEBUG, CERROR, cfs_foreach_bit, D_INFO, dt_device::dd_lu_dev, lvfs_run_ctxt::dt, ENTRY, GOTO, l_wait_event, LASSERT, lu_device::ld_obd, llog_common_cat_ops, llog_setup(), LLOG_UPDATELOG_ORIG_CTXT, lod2obd(), lod_device::lod_child, lod_device::lod_child_recovery_thread, lod_device::lod_mdt_descs, lod_sub_fini_llog(), lod_sub_recovery_thread(), lodname2mdt_index(), lod_recovery_data::lrd_idx, lod_recovery_data::lrd_lod, lod_recovery_data::lrd_ltd, lod_recovery_data::lrd_thread, lod_tgt_desc::ltd_index, lod_tgt_desc::ltd_recovery_thread, lod_tgt_desc::ltd_tgt, LTD_TGT, lod_tgt_descs::ltd_tgt_bitmap, OBD_ALLOC_PTR, OBD_FREE_PTR, obd_device::obd_lvfs_ctxt, obd_device::obd_name, obd_device::obd_olg, RETURN, SVC_RUNNING, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, ptlrpc_thread::t_flags, and thread.
Referenced by lod_add_device(), and lod_sub_init_llogs().
int lod_sub_object_attr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_attr * attr, struct thandle * th)
attributes set
Get transaction of next layer, record updates if it belongs to cross-MDT operation, and set attributes to the object.
Parameters:
[in] env execution environment
[in] dt object on which to set attr
[in] attr attrbutes to be set
[in] th transaction handle
Return values:
0 if attributes setting succeeds.
negative errno if the attributes setting fails.
Definition at line 678 of file lod_sub_object.c.
References dt_object::do_lu, dt_attr_set(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_pack.
Referenced by lod_attr_set().
int lod_sub_object_create (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof, struct thandle * th)
Create sub-object.
Get transaction of next layer, record updates if it belongs to cross-MDT operation, and create the object.
Parameters:
[in] env execution environment
[in] dt the object being created
[in] attr the attributes of the object being created
[in] hint the hint of the creation
[in] dof the object format of the creation
th] th the transaction handle
Return values:
0 if the creation succeeds
negative errno if the creation fails.
Definition at line 166 of file lod_sub_object.c.
References dt_object::do_lu, dt_create(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_pack.
Referenced by lod_object_create(), lod_striping_create(), and lod_xattr_set_lmv().
int lod_sub_object_declare_attr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_attr * attr, struct thandle * th)
Declare attr_set.
Get transaction of next layer, and declare attr set.
Parameters:
[in] env execution environment
[in] dt object on which to set attr
[in] attr attributes to be set
[in] th transaction handle
Return values:
0 if the declaration succeeds.
negative errno if the declaration fails.
Definition at line 641 of file lod_sub_object.c.
References dt_object::do_lu, dt_declare_attr_set(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_size.
Referenced by lod_declare_attr_set(), and lod_declare_init_size().
int lod_sub_object_declare_create (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof, struct thandle * th)
Declare sub-object creation.
Get transaction of next layer and declare the creation of the object.
Parameters:
[in] env execution environment
[in] dt the object being created
[in] attr the attributes of the object being created
[in] hint the hint of the creation
[in] dof the object format of the creation
th] th the transaction handle
Return values:
0 if the declaration succeeds
negative errno if the declaration fails.
Definition at line 129 of file lod_sub_object.c.
References dt_object::do_lu, dt_declare_create(), lod_sub_get_thandle(), lu_object_fid(), and update_record_size.
Referenced by lod_declare_object_create(), lod_dir_declare_create_stripes(), lod_qos_declare_object_on(), and lod_qos_prep_create().
int lod_sub_object_declare_delete (const struct lu_env * env, struct dt_object * dt, const struct dt_key * key, struct thandle * th)
Declare sub-object index delete.
Get transaction of next layer and declare index deletion.
Parameters:
[in] env execution environment
[in] dt object for which to delete index
[in] key key of the index which will be deleted
[in] th the transaction handle
Return values:
0 if the declaration succeeds.
negative errno if the declaration fails.
Definition at line 491 of file lod_sub_object.c.
References dt_object::do_lu, dt_declare_delete(), lod_sub_get_thandle(), lu_object_fid(), and update_record_size.
Referenced by lod_declare_index_delete(), and lod_declare_object_destroy().
int lod_sub_object_declare_destroy (const struct lu_env * env, struct dt_object * dt, struct thandle * th)
Declare destroying sub-object.
Get transaction of next layer and declare the sub-object destroy.
Parameters:
[in] env execution environment
[in] dt dt object to be destroyed
[in] th transaction handle
Return values:
0 if the declaration succeeds.
negative errno if the declaration fails.
Definition at line 346 of file lod_sub_object.c.
References dt_object::do_lu, dt_declare_destroy(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_size.
Referenced by lod_declare_object_destroy().
int lod_sub_object_declare_insert (const struct lu_env * env, struct dt_object * dt, const struct dt_rec * rec, const struct dt_key * key, struct thandle * th)
Declare sub-object index insert.
Get transaction of next layer and declare index insert.
Parameters:
[in] env execution environment
[in] dt object for which to insert index
[in] rec record of the index which will be inserted
[in] key key of the index which will be inserted
[in] th the transaction handle
Return values:
0 if the declaration succeeds.
negative errno if the declaration fails.
Definition at line 419 of file lod_sub_object.c.
References dt_object::do_lu, dt_declare_insert(), lod_sub_get_thandle(), lu_object_fid(), and update_record_size.
Referenced by lod_declare_index_insert(), and lod_dir_declare_create_stripes().
int lod_sub_object_declare_punch (const struct lu_env * env, struct dt_object * dt, __u64 start, __u64 end, struct thandle * th)
Declare punch.
Get transaction of next layer and declare punch.
Parameters:
[in] env execution environment
[in] dt object to be written
[in] start start offset of punch
[in] end end offet of punch
[in] th transaction handle
Return values:
0 if the insertion succeeds.
negative errno if the insertion fails.
Definition at line 873 of file lod_sub_object.c.
References dt_object::do_lu, dt_declare_punch(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_size.
Referenced by lod_declare_punch().
int lod_sub_object_declare_ref_add (const struct lu_env * env, struct dt_object * dt, struct thandle * th)
Declare adding reference for the sub-object.
Get transaction of next layer and declare the reference adding.
Parameters:
[in] env execution environment
[in] dt dt object to add reference
[in] th transaction handle
Return values:
0 if the declaration succeeds.
negative errno if the declaration fails.
Definition at line 206 of file lod_sub_object.c.
References dt_object::do_lu, dt_declare_ref_add(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_size.
Referenced by lod_declare_ref_add(), and lod_dir_declare_create_stripes().
int lod_sub_object_declare_ref_del (const struct lu_env * env, struct dt_object * dt, struct thandle * th)
Declare deleting reference for the sub-object.
Get transaction of next layer and declare the reference deleting.
Parameters:
[in] env execution environment
[in] dt dt object to delete reference
[in] th transaction handle
Return values:
0 if the declaration succeeds.
negative errno if the declaration fails.
Definition at line 276 of file lod_sub_object.c.
References dt_object::do_lu, dt_declare_ref_del(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_size.
Referenced by lod_declare_object_destroy(), and lod_declare_ref_del().
int lod_sub_object_declare_write (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, loff_t pos, struct thandle * th)
Declare buffer write.
Get transaction of next layer and declare buffer write.
Parameters:
[in] env execution environment
[in] dt object to be written
[in] buf buffer to write which includes an embedded size field
[in] pos offet in the object to start writing at
[in] th transaction handle
Return values:
0 if the insertion succeeds.
negative errno if the insertion fails.
Definition at line 795 of file lod_sub_object.c.
References dt_object::do_lu, dt_declare_write(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_size.
Referenced by lod_declare_write().
int lod_sub_object_declare_xattr_del (const struct lu_env * env, struct dt_object * dt, const char * name, struct thandle * th)
Declare xattr_del.
Get transaction of next layer, and declare xattr deletion.
Parameters:
[in] env execution environment
[in] dt object on which to delete xattr
[in] name name of the xattr to be deleted
[in] th transaction handle
Return values:
0 if the declaration succeeds.
negative errno if the declaration fails.
Definition at line 717 of file lod_sub_object.c.
References dt_object::do_lu, dt_declare_xattr_del(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_size.
Referenced by lod_declare_attr_set(), and lod_declare_xattr_del().
int lod_sub_object_declare_xattr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, const char * name, int fl, struct thandle * th)
Declare xattr_set.
Get transaction of next layer, and declare xattr set.
Parameters:
[in] env execution environment
[in] dt object on which to set xattr
[in] buf xattr to be set
[in] name name of the xattr
[in] fl flag for setting xattr
Return values:
0 if the declaration succeeds.
negative errno if the declaration fails.
Definition at line 561 of file lod_sub_object.c.
References dt_object::do_lu, dt_declare_xattr_set(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_size.
Referenced by lod_declare_attr_set(), lod_declare_striped_object(), lod_declare_xattr_set(), lod_dir_declare_create_stripes(), lod_dir_declare_xattr_set(), and lod_object_replace_parent_fid().
int lod_sub_object_delete (const struct lu_env * env, struct dt_object * dt, const struct dt_key * name, struct thandle * th)
Delete index of sub object.
Get transaction of next layer, record updates if it belongs to cross-MDT operation, and delete the index.
Parameters:
[in] env execution environment
[in] dt object for which to delete index
[in] key key of the index to be deleted
[in] th the transaction handle
Return values:
0 if the deletion succeeds.
negative errno if the deletion fails.
Definition at line 524 of file lod_sub_object.c.
References dt_object::do_lu, dt_delete(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_pack.
Referenced by lod_index_delete(), and lod_object_destroy().
int lod_sub_object_destroy (const struct lu_env * env, struct dt_object * dt, struct thandle * th)
Destroy sub-object.
Get transaction of next layer, record updates if it belongs to cross-MDT operation and destroy the object.
Parameters:
[in] env execution environment
[in] dt dt object to be destroyed
[in] th transaction handle
Return values:
0 if the destroy succeeds.
negative errno if the destroy fails.
Definition at line 381 of file lod_sub_object.c.
References dt_object::do_lu, dt_destroy(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_pack.
Referenced by lod_object_destroy().
int lod_sub_object_index_insert (const struct lu_env * env, struct dt_object * dt, const struct dt_rec * rec, const struct dt_key * key, struct thandle * th, int ign)
Insert index of sub object.
Get transaction of next layer, record updates if it belongs to cross-MDT operation, and insert the index.
Parameters:
[in] env execution environment
[in] dt object for which to insert index
[in] rec record of the index to be inserted
[in] key key of the index to be inserted
[in] th the transaction handle
[in] ign whether ignore quota
Return values:
0 if the insertion succeeds.
negative errno if the insertion fails.
Definition at line 455 of file lod_sub_object.c.
References dt_object::do_lu, dt_insert(), lod_sub_get_thandle(), lu_object_fid(), and update_record_pack.
Referenced by lod_index_insert(), and lod_xattr_set_lmv().
int lod_sub_object_punch (const struct lu_env * env, struct dt_object * dt, __u64 start, __u64 end, struct thandle * th)
Punch to sub object.
Get transaction of next layer, records buffer write if it belongs to Cross-MDT operation, and punch object.
Parameters:
[in] env execution environment
[in] dt object to be written
[in] start start offset of punch
[in] end end offset of punch
[in] th transaction handle
[in] capa capability of the write
Return values:
the buffer size in bytes if it succeeds.
negative errno if it fails.
Definition at line 913 of file lod_sub_object.c.
References dt_object::do_lu, dt_punch(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_pack.
Referenced by lod_punch().
int lod_sub_object_ref_add (const struct lu_env * env, struct dt_object * dt, struct thandle * th)
Add reference for the sub-object.
Get transaction of next layer, record updates if it belongs to cross-MDT operation and add reference of the object.
Parameters:
[in] env execution environment
[in] dt dt object to add reference
[in] th transaction handle
Return values:
0 if it succeeds.
negative errno if it fails.
Definition at line 240 of file lod_sub_object.c.
References dt_object::do_lu, dt_ref_add(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_pack.
Referenced by lod_ref_add(), and lod_xattr_set_lmv().
int lod_sub_object_ref_del (const struct lu_env * env, struct dt_object * dt, struct thandle * th)
Delete reference for the sub-object.
Get transaction of next layer, record updates if it belongs to cross-MDT operation and delete reference of the object.
Parameters:
[in] env execution environment
[in] dt dt object to delete reference
[in] th transaction handle
Return values:
0 if it succeeds.
negative errno if it fails.
Definition at line 310 of file lod_sub_object.c.
References dt_object::do_lu, dt_ref_del(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_pack.
Referenced by lod_object_destroy(), and lod_ref_del().
ssize_t lod_sub_object_write (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, loff_t * pos, struct thandle * th, int rq)
Write buffer to sub object.
Get transaction of next layer, records buffer write if it belongs to Cross-MDT operation, and write buffer.
Parameters:
[in] env execution environment
[in] dt object to be written
[in] buf buffer to write which includes an embedded size field
[in] pos offet in the object to start writing at
[in] th transaction handle
[in] rq enforcement for this write
Return values:
the buffer size in bytes if it succeeds.
negative errno if it fails.
Definition at line 835 of file lod_sub_object.c.
References dt_object::do_lu, dt_write(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_pack.
Referenced by lod_write().
int lod_sub_object_xattr_del (const struct lu_env * env, struct dt_object * dt, const char * name, struct thandle * th)
xattribute deletion
Get transaction of next layer, record update if it belongs to cross-MDT operation and delete xattr.
Parameters:
[in] env execution environment
[in] dt object on which to delete xattr
[in] name name of the xattr to be deleted
[in] th transaction handle
Return values:
0 if the deletion succeeds.
negative errno if the deletion fails.
Definition at line 755 of file lod_sub_object.c.
References dt_object::do_lu, dt_xattr_del(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_pack.
Referenced by lod_attr_set(), lod_xattr_del(), and lod_xattr_del_internal().
int lod_sub_object_xattr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, const char * name, int fl, struct thandle * th)
Set xattr.
Get transaction of next layer, record updates if it belongs to cross-MDT operation, and set xattr to the object.
Parameters:
[in] env execution environment
[in] dt object on which to set xattr
[in] buf xattr to be set
[in] name name of the xattr
[in] fl flag for setting xattr
[in] th transaction handle
Return values:
0 if the xattr setting succeeds.
negative errno if xattr setting fails.
Definition at line 602 of file lod_sub_object.c.
References dt_object::do_lu, dt_xattr_set(), ENTRY, lod_sub_get_thandle(), lu_object_fid(), RETURN, and update_record_pack.
Referenced by lod_attr_set(), lod_generate_and_set_lovea(), lod_object_replace_parent_fid(), lod_xattr_set(), lod_xattr_set_internal(), and lod_xattr_set_lmv().
int lod_sub_prep_llog (const struct lu_env * env, struct lod_device * lod, struct dt_device * dt, int index)
Definition at line 937 of file lod_sub_object.c.
References CDEBUG, CERROR, D_INFO, dt_device::dd_lu_dev, DOSTID, ENTRY, GOTO, LASSERT, llog_catid::lci_logid, lu_device::ld_obd, llog_handle::lgh_id, llog_logid::lgl_ogen, llog_logid::lgl_oi, likely, llog_cat_close(), LLOG_CTXT_FLAG_NORMAL_FID, llog_ctxt_put(), LLOG_F_IS_CAT, llog_get_context(), llog_init_handle(), LLOG_MIN_CHUNK_SIZE, llog_open(), llog_open_create(), LLOG_OPEN_EXISTS, llog_osd_get_cat_list(), llog_osd_put_cat_list(), LLOG_UPDATELOG_ORIG_CTXT, llog_ctxt::loc_chunk_size, llog_ctxt::loc_flags, llog_ctxt::loc_handle, lod2obd(), lod_env_info(), lodname2mdt_index(), logid_id(), logid_set_id(), lod_thread_info::lti_cid, lod_thread_info::lti_fid, lu_update_log_fid(), obd_device::obd_name, POSTID, RETURN, and unlikely.
Referenced by lod_process_config(), and lod_sub_recovery_thread().
int lod_verify_striping (struct lod_device * d, const struct lu_buf * buf, bool is_from_disk)
Verify striping.
Check the validity of all fields including the magic, stripe size, stripe count, stripe offset and that the pool is present. Also check that each target index points to an existing target. The additional is_from_disk turns additional checks. In some cases zero fields are allowed (like pattern=0).
Parameters:
[in] d LOD device
[in] buf buffer with LOV EA to verify
[in] is_from_disk 0 - from user, allow some fields to be 0 1 - from disk, do not allow
Return values:
0 if the striping is valid
-EINVAL if striping is invalid
Definition at line 1097 of file lod_lov.c.
References CDEBUG, cfs_bitmap_check(), cpu_to_le32, D_IOCTL, ENTRY, GOTO, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, le16_to_cpu, le32_to_cpu, lov_user_md_v1::lmm_magic, lov_user_md_v1::lmm_pattern, lov_user_md_v3::lmm_pool_name, lov_user_md_v1::lmm_stripe_count, lov_user_md_v1::lmm_stripe_offset, lov_user_md_v1::lmm_stripe_size, lod_check_index_in_pool(), lod_find_pool(), lod_pool_putref(), LOV_MAGIC_V1_DEF, LOV_MAGIC_V3_DEF, LOV_MIN_STRIPE_SIZE, LOV_OFFSET_DEFAULT, LOV_PATTERN_RAID0, LOV_USER_MAGIC_V1, LOV_USER_MAGIC_V3, offsetof, pool_tgt_count, and RETURN.
Referenced by lod_xattr_set_lov_on_dir().
int lodname2mdt_index (char * lodname, __u32 * mdt_index)
Extract MDT target index from a device name.
a helper function to extract index from the given device name like "fsname-MDTxxxx-mdtlov"
Parameters:
[in] lodname device name
[out] mdt_index extracted index
Return values:
0 on success
-EINVAL if the name is invalid
Definition at line 522 of file lod_dev.c.
References CERROR.
Referenced by lod_process_config(), lod_process_recovery_updates(), lod_sub_init_llog(), and lod_sub_prep_llog().
static struct lod_device* lu2lod_dev (struct lu_device * d) [static, read]
Definition at line 320 of file lod_internal.h.
References dt_device::dd_lu_dev, LASSERT, lod_device::lod_dt_dev, and lu_device_is_lod().
Referenced by lod_ah_init(), lod_alloc_ost_list(), lod_alloc_qos(), lod_alloc_rr(), lod_alloc_specific(), lod_declare_object_create(), lod_declare_xattr_set_lmv(), lod_device_fini(), lod_device_free(), lod_dir_declare_xattr_set(), lod_generate_and_set_lovea(), lod_initialize_objects(), lod_load_lmv_shards(), lod_obd_connect(), lod_obd_disconnect(), lod_obd_get_info(), lod_obd_set_info_async(), lod_object_init(), lod_parse_dir_striping(), lod_pool_add(), lod_pool_del(), lod_pool_new(), lod_pool_remove(), lod_prep_lmv_md(), lod_prep_md_striped_create(), lod_prepare(), lod_process_config(), lod_qos_parse_config(), lod_qos_prep_create(), lod_recovery_complete(), lod_xattr_get(), and lod_xattr_set_lov_on_dir().
static struct lod_object* lu2lod_obj (struct lu_object * o) [static, read]
Definition at line 342 of file lod_internal.h.
References dt_object::do_lu, ergo, LASSERT, lod_object::ldo_obj, lu_object::lo_dev, and lu_device_is_lod().
Referenced by lod_object_free(), lod_object_print(), and lod_object_start().
static int lu_device_is_lod (struct lu_device * d) [inline, static]
Definition at line 315 of file lod_internal.h.
References ergo, lu_device::ld_ops, and lod_lu_ops.
Referenced by dt2lod_dev(), lod_obj(), lu2lod_dev(), and lu2lod_obj().
int qos_add_tgt (struct lod_device * lod, struct lod_tgt_desc * ost_desc)
Add a new target to Quality of Service (QoS) target table.
Add a new OST target to the structure representing an OSS. Resort the list of known OSSs by the number of OSTs attached to each OSS. The OSS list is protected internally and no external locking is required.
Parameters:
[in] lod LOD device
[in] ost_desc OST description
Return values:
0 on success
-ENOMEM on error
Definition at line 74 of file lod_qos.c.
References ptlrpc_connection::c_remote_uuid, CDEBUG, D_QOS, ENTRY, obd_export::exp_connection, GOTO, list, list_add_tail(), list_del(), list_for_each_entry, lod_device::lod_qos, lod_qos::lq_dirty, lod_qos::lq_oss_list, lod_qos::lq_rr, lod_qos::lq_rw_sem, lod_qos_oss::lqo_oss_list, lod_qos_oss::lqo_ost_count, lod_qos_oss::lqo_uuid, lod_qos_rr::lqr_dirty, lod_tgt_desc::ltd_exp, lod_tgt_desc::ltd_qos, lod_tgt_desc::ltd_uuid, ltd_qos::ltq_oss, OBD_ALLOC_PTR, obd_uuid2str(), obd_uuid_equals(), and RETURN.
Referenced by lod_add_device().
int qos_del_tgt (struct lod_device * lod, struct lod_tgt_desc * ost_desc)
Remove OST target from QoS table.
Removes given OST target from QoS table and releases related OSS structure if no OSTs remain on the OSS.
Parameters:
[in] lod LOD device
[in] ost_desc OST description
Return values:
0 on success
-ENOENT if no OSS was found
Definition at line 145 of file lod_qos.c.
References CDEBUG, D_QOS, ENTRY, GOTO, list_del(), lod_device::lod_qos, lod_qos::lq_dirty, lod_qos::lq_rr, lod_qos::lq_rw_sem, lod_qos_oss::lqo_oss_list, lod_qos_oss::lqo_ost_count, lod_qos_oss::lqo_uuid, lod_qos_rr::lqr_dirty, lod_tgt_desc::ltd_qos, ltd_qos::ltq_oss, OBD_FREE_PTR, obd_uuid2str(), and RETURN.
Referenced by lod_putref().
Variable Documentation
struct lu_object_operations lod_lu_obj_ops
Definition at line 4264 of file lod_object.c.
Referenced by lod_object_alloc().
struct lu_device_operations lod_lu_ops
Definition at line 1172 of file lod_dev.c.
Referenced by lu_device_is_lod().
struct dt_object_operations lod_obj_ops
Definition at line 3982 of file lod_object.c.
Referenced by lod_object_alloc().
struct kmem_cache* lod_object_kmem
Definition at line 174 of file lod_dev.c.
Referenced by lod_object_alloc(), and lod_object_free().
struct lu_context_key lod_thread_key
Referenced by lod_env_info().
struct cfs_hash_ops pool_hash_operations
Definition at line 216 of file lod_pool.c.
Referenced by lod_pools_init(), and lov_setup().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.