Lustre: lustre/lod/lod_qos.c File Reference
lustre/lod/lod_qos.c File Reference
#include <asm/div64.h>
#include <libcfs/libcfs.h>
#include <lustre/lustre_idl.h>
#include <lustre_swab.h>
#include <obd_class.h>
#include "lod_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LOV
#define FORCE_QOS_
#define D_QOS D_OTHER
#define QOS_DEBUG(fmt,...) CDEBUG(D_QOS, fmt, ## __VA_ARGS__)
#define QOS_CONSOLE(fmt,...) LCONSOLE(D_QOS, fmt, ## __VA_ARGS__)
#define TGT_BAVAIL(i)
#define LOV_QOS_EMPTY ((__u32)-1)
#define LOV_CREATE_RESEED_MULT 30
#define LOV_CREATE_RESEED_MIN 2000
Functions
int qos_add_tgt (struct lod_device *lod, struct lod_tgt_desc *ost_desc)
Add a new target to Quality of Service (QoS) target table.
int qos_del_tgt (struct lod_device *lod, struct lod_tgt_desc *ost_desc)
Remove OST target from QoS table.
static int lod_statfs_and_check (const struct lu_env *env, struct lod_device *d, int index, struct obd_statfs *sfs)
Check whether the target is available for new OST objects.
static void lod_qos_statfs_update (const struct lu_env *env, struct lod_device *lod)
Maintain per-target statfs data.
static int lod_qos_calc_ppo (struct lod_device *lod)
Calculate per-OST and per-OSS penalties.
static int lod_qos_calc_weight (struct lod_device *lod, int i)
Calculate weight for a given OST target.
static int lod_qos_used (struct lod_device *lod, struct ost_pool *osts, __u32 index, __u64 *total_wt)
Re-calculate weights.
void lod_qos_rr_init (struct lod_qos_rr *lqr)
static int lod_qos_calc_rr (struct lod_device *lod, struct ost_pool *src_pool, struct lod_qos_rr *lqr)
Calculate optimal round-robin order with regard to OSSes.
static struct dt_object * lod_qos_declare_object_on (const struct lu_env *env, struct lod_device *d, __u32 ost_idx, struct thandle *th)
Instantiate and declare creation of a new object.
static int min_stripe_count (__u32 stripe_cnt, int flags)
Calculate a minimum acceptable stripe count.
static int lod_qos_dev_is_full (struct obd_statfs *msfs)
Check if an OST is full.
static int lod_qos_ost_in_use_clear (const struct lu_env *env, __u32 stripes)
Initialize temporary OST-in-use array.
static void lod_qos_ost_in_use (const struct lu_env *env, int idx, int ost)
Remember a target in the array of used targets.
static int lod_qos_is_ost_used (const struct lu_env *env, int ost, __u32 stripes)
Check is OST used in a striping.
static int lod_check_and_reserve_ost (const struct lu_env *env, struct lod_device *m, struct obd_statfs *sfs, __u32 ost_idx, __u32 speed, __u32 *s_idx, struct dt_object **stripe, struct thandle *th)
static int lod_alloc_rr (const struct lu_env *env, struct lod_object *lo, struct dt_object **stripe, int flags, struct thandle *th)
Allocate a striping using round-robin algorithm.
static int lod_alloc_ost_list (const struct lu_env *env, struct lod_object *lo, struct dt_object **stripe, struct lov_user_md *lum, struct thandle *th)
Allocate a specific striping layout on a user defined set of OSTs.
static int lod_alloc_specific (const struct lu_env *env, struct lod_object *lo, struct dt_object **stripe, int flags, struct thandle *th)
Allocate a striping on a predefined set of OSTs.
static int lod_qos_is_usable (struct lod_device *lod)
Check whether QoS allocation should be used.
static int lod_alloc_qos (const struct lu_env *env, struct lod_object *lo, struct dt_object **stripe, int flags, struct thandle *th)
Allocate a striping using an algorithm with weights.
static __u16 lod_get_stripecnt (struct lod_device *lod, __u32 magic, __u16 stripe_count)
Find largest stripe count the caller can use.
static int lod_use_defined_striping (const struct lu_env *env, struct lod_object *mo, const struct lu_buf *buf)
Create in-core respresentation for a fully-defined striping.
static int lod_qos_parse_config (const struct lu_env *env, struct lod_object *lo, const struct lu_buf *buf)
Parse suggested striping configuration.
int lod_qos_prep_create (const struct lu_env *env, struct lod_object *lo, struct lu_attr *attr, const struct lu_buf *buf, struct thandle *th)
Create a striping for an obejct.
Define Documentation
#define D_QOS D_OTHER
Definition at line 53 of file lod_qos.c.
Referenced by qos_add_tgt(), and qos_del_tgt().
#define DEBUG_SUBSYSTEM S_LOV
Definition at line 38 of file lod_qos.c.
#define FORCE_QOS_
Definition at line 51 of file lod_qos.c.
#define LOV_CREATE_RESEED_MIN 2000
Definition at line 742 of file lod_qos.c.
Referenced by lod_alloc_rr().
#define LOV_CREATE_RESEED_MULT 30
Definition at line 741 of file lod_qos.c.
Referenced by lod_alloc_rr().
#define LOV_QOS_EMPTY ((__u32)-1)
Definition at line 541 of file lod_qos.c.
Referenced by lod_alloc_rr(), and lod_qos_calc_rr().
#define QOS_CONSOLE (fmt, ...) LCONSOLE(D_QOS, fmt, ## __VA_ARGS__)
Definition at line 56 of file lod_qos.c.
Referenced by lod_qos_calc_rr().
#define QOS_DEBUG (fmt, ...) CDEBUG(D_QOS, fmt, ## __VA_ARGS__)
Definition at line 55 of file lod_qos.c.
Referenced by lod_alloc_qos(), lod_alloc_rr(), lod_check_and_reserve_ost(), and lod_qos_used().
#define TGT_BAVAIL (i)
Value:
(OST_TGT(lod,i)->ltd_statfs.os_bavail * \
                       OST_TGT(lod,i)->ltd_statfs.os_bsize)
Definition at line 58 of file lod_qos.c.
Referenced by lod_qos_calc_ppo(), lod_qos_calc_weight(), and lod_qos_used().
Function Documentation
static int lod_alloc_ost_list (const struct lu_env * env, struct lod_object * lo, struct dt_object ** stripe, struct lov_user_md * lum, struct thandle * th) [static]
Allocate a specific striping layout on a user defined set of OSTs.
Allocates new striping using the OST index range provided by the data from the lmm_obejcts contained in the lov_user_md passed to this method. Full OSTs are not considered. The exact order of OSTs requested by the user is respected as much as possible depending on OST status. The number of stripes needed and stripe offset are taken from the object. If that number can not be met, then the function returns a failure and then it's the caller's responsibility to release the stripes allocated. All the internal structures are protected, but no concurrent allocation is allowed on the same objects.
Parameters:
[in] env execution environment for this thread
[in] lo LOD object
[out] stripe striping created
[in] lum stripe md to specify list of OSTs
[in] th transaction handle
Return values:
0 on success
-ENODEV OST index does not exist on file system
-EINVAL requested OST index is invalid
negative negated errno on error
Definition at line 1084 of file lod_qos.c.
References CDEBUG, cfs_bitmap_check(), D_OTHER, dt_object::do_lu, ENTRY, lov_user_ost_data_v1::l_ost_idx, LASSERT, lod_object::ldo_def_stripe_offset, lod_object::ldo_obj, lod_object::ldo_stripenr, lov_user_md_v3::lmm_objects, lu_object::lo_dev, lod2obd(), lod_env_info(), lod_qos_declare_object_on(), lod_qos_is_ost_used(), lod_qos_ost_in_use(), lod_qos_ost_in_use_clear(), lod_statfs_and_check(), LOV_USER_MAGIC_SPECIFIC, lod_thread_info::lti_osfs, lu2lod_dev(), lustre_print_user_md(), and RETURN.
Referenced by lod_qos_prep_create().
static int lod_alloc_qos (const struct lu_env * env, struct lod_object * lo, struct dt_object ** stripe, int flags, struct thandle * th) [static]
Allocate a striping using an algorithm with weights.
The function allocates OST objects to create a striping. The algorithm used is based on weights (currently only using the free space), and it's trying to ensure the space is used evenly by OSTs and OSSs. The striping configuration (# of stripes, offset, pool) is taken from the object and is prepared by the caller.
If LOV_USES_DEFAULT_STRIPE is not passed and prepared configuration can't be met due to too few OSTs, then allocation fails. If the flag is passed fewer than 3/4 of the requested number of stripes can be allocated, then allocation fails.
No concurrent allocation is allowed on the object and this must be ensured by the caller. All the internal structures are protected by the function.
The algorithm has two steps: find available OSTs and calculate their weights, then select the OSTs with their weights used as the probability. An OST with a higher weight is proportionately more likely to be selected than one with a lower weight.
Parameters:
[in] env execution environment for this thread
[in] lo LOD object
[out] stripe striping created
[in] flags 0 or LOV_USES_DEFAULT_STRIPE
[in] th transaction handle
Return values:
0 on success
-EAGAIN not enough OSTs are found for specified stripe count
-EINVAL requested OST index is invalid
negative errno on failure
Definition at line 1375 of file lod_qos.c.
References __u64, cfs_bitmap_check(), cfs_rand(), dt_object::do_lu, ENTRY, GOTO, LASSERT, LCONSOLE_INFO, lod_object::ldo_obj, lod_object::ldo_pool, lod_object::ldo_stripenr, lu_object::lo_dev, lod_env_info(), lod_find_pool(), lod_device::lod_pool_info, lod_pool_putref(), lod_device::lod_qos, lod_qos_calc_ppo(), lod_qos_calc_weight(), lod_qos_declare_object_on(), lod_qos_dev_is_full(), lod_qos_is_ost_used(), lod_qos_is_usable(), lod_qos_ost_in_use(), lod_qos_ost_in_use_clear(), lod_qos_used(), lod_statfs_and_check(), LPU64, lod_qos::lq_dirty, lod_qos::lq_rw_sem, lod_qos::lq_same_space, lod_tgt_desc::ltd_qos, lod_thread_info::lti_osfs, ltd_qos::ltq_usable, ltd_qos::ltq_weight, lu2lod_dev(), lu_object_put(), min_stripe_count(), OBD_FAIL_CHECK, OBD_FAIL_MDS_OSC_PRECREATE, ost_pool::op_array, ost_pool::op_count, OST_TGT, pool_desc::pool_obds, pool_tgt_rw_sem, QOS_DEBUG, RETURN, and unlikely.
Referenced by lod_qos_prep_create().
static int lod_alloc_rr (const struct lu_env * env, struct lod_object * lo, struct dt_object ** stripe, int flags, struct thandle * th) [static]
Allocate a striping using round-robin algorithm.
Allocates a new striping using round-robin algorithm. The function refreshes all the internal structures (statfs cache, array of available OSTs sorted with regard to OSS, etc). The number of stripes required is taken from the object (must be prepared by the caller), but can change if the flag LOV_USES_DEFAULT_STRIPE is supplied. The caller should ensure nobody else is trying to create a striping on the object in parallel. All the internal structures (like pools, etc) are protected and no additional locking is required. The function succeeds even if a single stripe is allocated. To save time we give priority to targets which already have objects precreated. Full OSTs are skipped (see lod_qos_dev_is_full() for the details).
Parameters:
[in] env execution environment for this thread
[in] lo LOD object
[out] stripe striping created
[in] flags allocation flags (0 or LOV_USES_DEFAULT_STRIPE)
[in] th transaction handle
Return values:
0 on success
-ENOSPC if not enough OSTs are found
negative negated errno for other failures
Definition at line 933 of file lod_qos.c.
References cfs_bitmap_check(), cfs_rand(), dt_object::do_lu, ENTRY, GOTO, lod_object::ldo_obj, lod_object::ldo_pool, lod_object::ldo_stripenr, lu_object::lo_dev, lod_check_and_reserve_ost(), lod_env_info(), lod_find_pool(), lod_device::lod_pool_info, lod_pool_putref(), lod_device::lod_qos, lod_qos_calc_rr(), lod_qos_ost_in_use_clear(), LOV_CREATE_RESEED_MIN, LOV_CREATE_RESEED_MULT, LOV_QOS_EMPTY, lod_qos::lq_rr, lod_qos::lq_rw_sem, lod_qos_rr::lqr_alloc, lod_qos_rr::lqr_offset_idx, lod_qos_rr::lqr_pool, lod_qos_rr::lqr_start_count, lod_qos_rr::lqr_start_idx, lod_thread_info::lti_osfs, lu2lod_dev(), max, min_stripe_count(), OBD_FAIL_CHECK, OBD_FAIL_MDS_OSC_PRECREATE, ost_pool::op_array, ost_pool::op_count, OST_TGT, pool_desc::pool_obds, pool_desc::pool_rr, pool_tgt_rw_sem, QOS_DEBUG, and RETURN.
Referenced by lod_qos_prep_create().
static int lod_alloc_specific (const struct lu_env * env, struct lod_object * lo, struct dt_object ** stripe, int flags, struct thandle * th) [static]
Allocate a striping on a predefined set of OSTs.
Allocates new layout starting from OST index in lo->ldo_def_stripe_offset. Full OSTs are not considered. The exact order of OSTs is not important and varies depending on OST status. The allocation procedure prefers the targets with precreated objects ready. The number of stripes needed and stripe offset are taken from the object. If that number cannot be met, then the function returns an error and then it's the caller's responsibility to release the stripes allocated. All the internal structures are protected, but no concurrent allocation is allowed on the same objects.
Parameters:
[in] env execution environment for this thread
[in] lo LOD object
[out] stripe striping created
[in] flags not used
[in] th transaction handle
Return values:
0 on success
-ENOSPC if no OST objects are available at all
-EFBIG if not enough OST objects are found
-EINVAL requested offset is invalid
negative errno on failure
Definition at line 1185 of file lod_qos.c.
References CDEBUG, CERROR, cfs_bitmap_check(), D_OTHER, DFID, dt_object::do_lu, ENTRY, GOTO, lod_object::ldo_def_stripe_offset, lod_object::ldo_obj, lod_object::ldo_pool, lod_object::ldo_stripenr, lu_object::lo_dev, lod2lu_obj(), lod_env_info(), lod_find_pool(), lod_device::lod_pool_info, lod_pool_putref(), lod_qos_declare_object_on(), lod_qos_is_ost_used(), lod_qos_ost_in_use(), lod_qos_ost_in_use_clear(), lod_statfs_and_check(), lod_thread_info::lti_osfs, lu2lod_dev(), lu_object_fid(), OBD_FAIL_CHECK, OBD_FAIL_MDS_OSC_PRECREATE, ost_pool::op_array, ost_pool::op_count, obd_statfs::os_fprecreated, PFID, pool_desc::pool_obds, pool_tgt_rw_sem, and RETURN.
Referenced by lod_qos_prep_create().
static int lod_check_and_reserve_ost (const struct lu_env * env, struct lod_device * m, struct obd_statfs * sfs, __u32 ost_idx, __u32 speed, __u32 * s_idx, struct dt_object ** stripe, struct thandle * th) [static]
Definition at line 841 of file lod_qos.c.
References CDEBUG, D_OTHER, lod_qos_declare_object_on(), lod_qos_dev_is_full(), lod_qos_is_ost_used(), lod_qos_ost_in_use(), lod_statfs_and_check(), obd_statfs::os_fprecreated, obd_statfs::os_state, OS_STATE_DEGRADED, and QOS_DEBUG.
Referenced by lod_alloc_rr().
static __u16 lod_get_stripecnt (struct lod_device * lod, __u32 magic, __u16 stripe_count) [static]
Find largest stripe count the caller can use.
Find the maximal possible stripe count not greater than stripe_count. Sometimes suggested stripecount can't be reached for a number of reasons: lack of enough active OSTs or the backend does not support EAs that large. If the passed one is 0, then the filesystem's default one is used.
Parameters:
[in] lod LOD device
[in] magic the format if striping
[in] stripe_count count the caller would like to use
Return values:
the maximum usable stripe count
Definition at line 1601 of file lod_qos.c.
References lov_desc::ld_active_tgt_count, lov_desc::ld_default_stripe_count, lod_device::lod_desc, lod_device::lod_osd_max_easize, LOV_MAX_STRIPE_COUNT_OLD, and lov_mds_md_max_stripe_count().
Referenced by lod_qos_prep_create().
static int lod_qos_calc_ppo (struct lod_device * lod) [static]
Calculate per-OST and per-OSS penalties.
Re-calculate penalties when the configuration changes, active targets change and after statfs refresh (all these are reflected by lq_dirty flag). On every OST and OSS: decay the penalty by half for every 8x the update interval that the device has been idle. That gives lots of time for the statfs information to be updated (which the penalty is only a proxy for), and avoids penalizing OSS/OSTs under light load. See lod_qos_calc_weight() for how penalties are factored into the weight.
Parameters:
[in] lod LOD device
Return values:
0 on success
-EAGAIN the number of OSTs isn't enough
Definition at line 310 of file lod_qos.c.
References __u64, cfs_foreach_bit, cfs_time_current_sec(), ENTRY, GOTO, LASSERT, lov_desc::ld_active_tgt_count, lov_desc::ld_qos_maxage, list_for_each_entry, lod_device::lod_desc, lod_device::lod_qos, lod_qos::lq_active_oss_count, lod_qos::lq_dirty, lod_qos::lq_oss_list, lod_qos::lq_prio_free, lod_qos::lq_reset, lod_qos::lq_same_space, lod_qos::lq_threshold_rr, lod_qos_oss::lqo_bavail, lod_qos_oss::lqo_oss_list, lod_qos_oss::lqo_ost_count, lod_qos_oss::lqo_penalty, lod_qos_oss::lqo_penalty_per_obj, lod_qos_oss::lqo_used, max, now(), OST_TGT, RETURN, and TGT_BAVAIL.
Referenced by lod_alloc_qos().
static int lod_qos_calc_rr (struct lod_device * lod, struct ost_pool * src_pool, struct lod_qos_rr * lqr) [static]
Calculate optimal round-robin order with regard to OSSes.
Place all the OSTs from pool src_pool in a special array to be used for round-robin (RR) stripe allocation. The placement algorithm interleaves OSTs from the different OSSs so that RR allocation can balance OSSs evenly. Resorts the targets when the number of active targets changes (because of a new target or activation/deactivation).
Parameters:
[in] lod LOD device
[in] src_pool OST pool
[in] lqr round-robin list
Return values:
0 on success
-ENOMEM fails to allocate the array
Definition at line 559 of file lod_qos.c.
References cfs_bitmap_check(), D_WARNING, ENTRY, LASSERT, LCONSOLE, LCONSOLE_ERROR_MSG, list_for_each_entry, lod_ost_pool_extend(), lod_device::lod_qos, LOV_QOS_EMPTY, lod_qos::lq_oss_list, lod_qos::lq_rw_sem, lod_qos_oss::lqo_ost_count, lod_qos_rr::lqr_dirty, lod_qos_rr::lqr_pool, lod_tgt_desc::ltd_qos, ltd_qos::ltq_oss, ost_pool::op_array, ost_pool::op_count, ost_pool::op_size, OST_TGT, QOS_CONSOLE, and RETURN.
Referenced by lod_alloc_rr().
static int lod_qos_calc_weight (struct lod_device * lod, int i) [static]
Calculate weight for a given OST target.
The final OST weight is the number of bytes available minus the OST and OSS penalties. See lod_qos_calc_ppo() for how penalties are calculated.
Parameters:
[in] lod LOD device, where OST targets are listed
[in] i OST target index
Return values:
0
Definition at line 429 of file lod_qos.c.
References __u64, OST_TGT, and TGT_BAVAIL.
Referenced by lod_alloc_qos(), and lod_qos_used().
static struct dt_object* lod_qos_declare_object_on (const struct lu_env * env, struct lod_device * d, __u32 ost_idx, struct thandle * th) [static, read]
Instantiate and declare creation of a new object.
The function instantiates LU representation for a new object on the specified device. Also it declares an intention to create that object on the storage target.
Note lu_object_anon() is used which is a trick with regard to LU/OSD infrastructure - in the existing precreation framework we can't assign FID at this moment, we do this later once a transaction is started. So the special method instantiates FID-less object in the cache and later it will get a FID and proper placement in LU cache.
Parameters:
[in] env execution environment for this thread
[in] d LOD device
[in] ost_idx OST target index where the object is being created
[in] th transaction handle
Return values:
object ptr on success, ERR_PTR() otherwise
Definition at line 674 of file lod_qos.c.
References CDEBUG, CERROR, D_OTHER, dt_object::do_lu, ENTRY, GOTO, LASSERT, lu_device::ld_type, lu_object::lo_header, lod_osts_size, lod_sub_object_declare_create(), lu_object_anon(), lu_object_locate(), lu_object_put(), OST_TGT, RETURN, and unlikely.
Referenced by lod_alloc_ost_list(), lod_alloc_qos(), lod_alloc_specific(), and lod_check_and_reserve_ost().
static int lod_qos_dev_is_full (struct obd_statfs * msfs) [inline, static]
Check if an OST is full.
Check whether an OST should be considered full based on the given statfs data.
Parameters:
[in] msfs statfs data
Return values:
false not full
true full
Definition at line 755 of file lod_qos.c.
References __u64, LASSERT, min_t, obd_statfs::os_bavail, obd_statfs::os_bfree, obd_statfs::os_blocks, and obd_statfs::os_bsize.
Referenced by lod_alloc_qos(), and lod_check_and_reserve_ost().
static int lod_qos_is_ost_used (const struct lu_env * env, int ost, __u32 stripes) [static]
Check is OST used in a striping.
Checks whether OST with the given index is marked as used in the temporary array (see lod_qos_ost_in_use()).
Parameters:
[in] env execution environment for this thread
[in] ost OST target index to check
[in] stripes the number of items used in the array already
Return values:
0 not used
1 used
Definition at line 828 of file lod_qos.c.
References lod_env_info(), and lod_thread_info::lti_ea_store.
Referenced by lod_alloc_ost_list(), lod_alloc_qos(), lod_alloc_specific(), and lod_check_and_reserve_ost().
static int lod_qos_is_usable (struct lod_device * lod) [inline, static]
Check whether QoS allocation should be used.
A simple helper to decide when QoS allocation should be used: if it's just a single available target or the used space is evenly distributed among the targets at the moment, then QoS allocation algorithm should not be used.
Parameters:
[in] lod LOD device
Return values:
0 should not be used
1 should be used
Definition at line 1325 of file lod_qos.c.
References lov_desc::ld_active_tgt_count, lod_device::lod_desc, lod_device::lod_qos, lod_qos::lq_dirty, and lod_qos::lq_same_space.
Referenced by lod_alloc_qos().
static void lod_qos_ost_in_use (const struct lu_env * env, int idx, int ost) [inline, static]
Remember a target in the array of used targets.
Mark the given target as used for a new striping being created. The status of an OST in a striping can be checked with lod_qos_is_ost_used().
Parameters:
[in] env execution environment for this thread
[in] idx index in the array
[in] ost OST target index to mark as used
Definition at line 805 of file lod_qos.c.
References LASSERT, lod_env_info(), lod_thread_info::lti_ea_store, and lod_thread_info::lti_ea_store_size.
Referenced by lod_alloc_ost_list(), lod_alloc_qos(), lod_alloc_specific(), and lod_check_and_reserve_ost().
static int lod_qos_ost_in_use_clear (const struct lu_env * env, __u32 stripes) [inline, static]
Initialize temporary OST-in-use array.
Allocate or extend the array used to mark targets already assigned to a new striping so they are not used more than once.
Parameters:
[in] env execution environment for this thread
[in] stripes number of items needed in the array
Return values:
0 on success
-ENOMEM on error
Definition at line 780 of file lod_qos.c.
References CERROR, lod_ea_store_resize(), lod_env_info(), lod_thread_info::lti_ea_store, and lod_thread_info::lti_ea_store_size.
Referenced by lod_alloc_ost_list(), lod_alloc_qos(), lod_alloc_rr(), and lod_alloc_specific().
static int lod_qos_parse_config (const struct lu_env * env, struct lod_object * lo, const struct lu_buf * buf) [static]
Parse suggested striping configuration.
The caller gets a suggested striping configuration from a number of sources including per-directory default and applications. Then it needs to verify the suggested striping is valid, apply missing bits and store the resulting configuration in the object to be used by the allocator later. Must not be called concurrently against the same object. It's OK to provide a fully-defined striping.
Parameters:
[in] env execution environment for this thread
[in] lo LOD object
[in] buf buffer containing the striping
Return values:
0 on success
negative negated errno on error
Definition at line 1696 of file lod_qos.c.
References __swab32, CERROR, D_OTHER, ENTRY, lov_user_ost_data_v1::l_ost_idx, lu_buf::lb_buf, lu_buf::lb_len, lod_object::ldo_def_stripe_offset, lod_object::ldo_pattern, lod_object::ldo_released_stripenr, lod_object::ldo_stripe_size, lod_object::ldo_stripenr, lov_user_md_v3::lmm_magic, lov_user_md_v1::lmm_magic, lov_user_md_v3::lmm_objects, lov_user_md_v1::lmm_pattern, lov_user_md_v3::lmm_pool_name, lov_user_md_v1::lmm_stripe_count, lov_user_md_v3::lmm_stripe_count, lov_user_md_v1::lmm_stripe_offset, lov_user_md_v3::lmm_stripe_offset, lov_user_md_v1::lmm_stripe_size, lod2lu_obj(), lod2obd(), lod_check_index_in_pool(), lod_find_pool(), lod_object_set_pool(), lod_pool_putref(), lod_use_defined_striping(), LOV_MAGIC_V1_DEF, LOV_MAGIC_V3_DEF, LOV_MIN_STRIPE_SIZE, LOV_OFFSET_DEFAULT, lov_pattern, LOV_PATTERN_F_RELEASED, LOV_PATTERN_RAID0, LOV_USER_MAGIC_SPECIFIC, LOV_USER_MAGIC_V1, LOV_USER_MAGIC_V3, lov_user_md_size(), lu2lod_dev(), lustre_print_user_md(), lustre_swab_lov_user_md_objects(), lustre_swab_lov_user_md_v1(), lustre_swab_lov_user_md_v3(), pool_tgt_count, RETURN, size, and unlikely.
Referenced by lod_qos_prep_create().
int lod_qos_prep_create (const struct lu_env * env, struct lod_object * lo, struct lu_attr * attr, const struct lu_buf * buf, struct thandle * th)
Create a striping for an obejct.
The function creates a new striping for the object. A buffer containing configuration hints can be provided optionally. The function tries QoS algorithm first unless free space is distributed evenly among OSTs, but by default RR algorithm is preferred due to internal concurrency (QoS is serialized). The caller must ensure no concurrent calls to the function are made against the same object.
Parameters:
[in] env execution environment for this thread
[in] lo LOD object
[in] attr attributes OST objects will be declared with
[in] buf suggested striping configuration or NULL
[in] th transaction handle
Return values:
0 on success
negative negated errno on error
Definition at line 1848 of file lod_qos.c.
References CDEBUG, CERROR, D_OTHER, ENTRY, GOTO, LASSERT, lu_buf::lb_buf, lov_desc::ld_tgt_count, lod_object::ldo_def_stripe_offset, lod_object::ldo_stripe, lod_object::ldo_stripenr, lod_object::ldo_stripes_allocated, likely, lod2lu_obj(), lod_alloc_ost_list(), lod_alloc_qos(), lod_alloc_rr(), lod_alloc_specific(), lod_device::lod_desc, lod_get_stripecnt(), lod_getref(), lod_device::lod_ost_descs, lod_putref(), lod_qos_parse_config(), lod_qos_statfs_update(), lod_sub_object_declare_create(), LOV_MAGIC, LOV_OFFSET_DEFAULT, LOV_USER_MAGIC_SPECIFIC, lov_user_md, LOV_USES_ASSIGNED_STRIPE, lu2lod_dev(), lu_object_put(), OBD_ALLOC, OBD_FREE, and RETURN.
Referenced by lod_declare_striped_object().
void lod_qos_rr_init (struct lod_qos_rr * lqr)
Definition at line 534 of file lod_qos.c.
References lod_qos_rr::lqr_alloc, and lod_qos_rr::lqr_dirty.
Referenced by lod_pool_new(), and lod_pools_init().
static void lod_qos_statfs_update (const struct lu_env * env, struct lod_device * lod) [static]
Maintain per-target statfs data.
The function refreshes statfs data for all the targets every N seconds. The actual N is controlled via procfs and set to LOV_DESC_QOS_MAXAGE_DEFAULT initially.
Parameters:
[in] env execution environment for this thread
[in] lod LOD device
Definition at line 257 of file lod_qos.c.
References __u64, cfs_time_beforeq_64(), cfs_time_current_64, cfs_time_shift_64(), ENTRY, EXIT, lov_desc::ld_qos_maxage, lod2obd(), lod_device::lod_desc, lod_device::lod_pool_info, lod_device::lod_qos, lod_statfs_and_check(), lod_qos::lq_dirty, lod_qos::lq_rw_sem, obd_device::obd_osfs_age, ost_pool::op_array, ost_pool::op_count, OST_TGT, and RETURN_EXIT.
Referenced by lod_qos_prep_create().
static int lod_qos_used (struct lod_device * lod, struct ost_pool * osts, __u32 index, __u64 * total_wt) [static]
Re-calculate weights.
The function is called when some OST target was used for a new object. In this case we should re-calculate all the weights to keep new allocations balanced well.
Parameters:
[in] lod LOD device
[in] osts OST pool where a new object was placed
[in] index OST target where a new object was placed
[out] total_wt new total weight for the pool
Return values:
0
Definition at line 457 of file lod_qos.c.
References cfs_bitmap_check(), cfs_time_current_sec(), ENTRY, LASSERT, list_for_each_entry, lod_device::lod_qos, lod_qos_calc_weight(), LPU64, lod_qos::lq_active_oss_count, lod_qos::lq_oss_list, lod_qos_oss::lqo_oss_list, lod_qos_oss::lqo_penalty, lod_qos_oss::lqo_penalty_per_obj, lod_qos_oss::lqo_used, lod_tgt_desc::ltd_qos, ltd_qos::ltq_oss, ltd_qos::ltq_penalty, ltd_qos::ltq_penalty_per_obj, ltd_qos::ltq_usable, ltd_qos::ltq_used, ltd_qos::ltq_weight, ost_pool::op_array, ost_pool::op_count, OST_TGT, QOS_DEBUG, RETURN, and TGT_BAVAIL.
Referenced by lod_alloc_qos().
static int lod_statfs_and_check (const struct lu_env * env, struct lod_device * d, int index, struct obd_statfs * sfs) [static]
Check whether the target is available for new OST objects.
Request statfs data from the given target and verify it's active and not read-only. If so, then it can be used to place new OST objects. This function also maintains the number of active/inactive targets and sets dirty flags if those numbers change so others can run re-balance procedures. No external locking is required.
Parameters:
[in] env execution environment for this thread
[in] d LOD device
[in] index index of OST target to check
[out] sfs buffer for statfs data
Return values:
0 if the target is good
negative negated errno on error
Definition at line 190 of file lod_qos.c.
References CDEBUG, CERROR, D_CONFIG, dt_statfs(), ENTRY, obd_export::exp_obd, LASSERT, LASSERTF, lov_desc::ld_active_tgt_count, lod2obd(), lod_device::lod_desc, lod_device::lod_desc_lock, lod_device::lod_qos, lod_qos::lq_dirty, lod_qos::lq_rr, lod_qos_rr::lqr_dirty, lod_tgt_desc::ltd_active, lod_tgt_desc::ltd_connecting, lod_tgt_desc::ltd_exp, obd_device::obd_name, obd_statfs::os_state, OS_STATE_READONLY, OST_TGT, and RETURN.
Referenced by lod_alloc_ost_list(), lod_alloc_qos(), lod_alloc_specific(), lod_check_and_reserve_ost(), and lod_qos_statfs_update().
static int lod_use_defined_striping (const struct lu_env * env, struct lod_object * mo, const struct lu_buf * buf) [static]
Create in-core respresentation for a fully-defined striping.
When the caller passes a fully-defined striping (i.e. everything including OST object FIDs are defined), then we still need to instantiate LU-cache with the objects representing the stripes defined. This function completes that task.
Parameters:
[in] env execution environment for this thread
[in] mo LOD object
[in] buf buffer containing the striping
Return values:
0 on success
negative negated errno on error
Definition at line 1636 of file lod_qos.c.
References ENTRY, GOTO, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lod_object::ldo_layout_gen, lod_object::ldo_pattern, lod_object::ldo_released_stripenr, lod_object::ldo_stripe_size, lod_object::ldo_stripenr, le16_to_cpu, le32_to_cpu, lov_mds_md_v1::lmm_layout_gen, lov_mds_md_v1::lmm_magic, lov_mds_md_v3::lmm_objects, lov_mds_md_v1::lmm_objects, lov_mds_md_v1::lmm_pattern, lov_mds_md_v3::lmm_pool_name, lov_mds_md_v1::lmm_stripe_count, lov_mds_md_v1::lmm_stripe_size, lod_initialize_objects(), lod_object_set_pool(), LOV_MAGIC_V1, LOV_MAGIC_V1_DEF, LOV_MAGIC_V3, LOV_MAGIC_V3_DEF, lov_mds_md_size(), LOV_PATTERN_F_RELEASED, and RETURN.
Referenced by lod_qos_parse_config().
static int min_stripe_count (__u32 stripe_cnt, int flags) [static]
Calculate a minimum acceptable stripe count.
Return an acceptable stripe count depending on flag LOV_USES_DEFAULT_STRIPE: all stripes or 3/4 of stripes.
Parameters:
[in] stripe_cnt number of stripes requested
[in] flags 0 or LOV_USES_DEFAULT_STRIPE
Return values:
acceptable stripecount
Definition at line 735 of file lod_qos.c.
References LOV_USES_DEFAULT_STRIPE.
Referenced by compare(), lod_alloc_qos(), and lod_alloc_rr().
int qos_add_tgt (struct lod_device * lod, struct lod_tgt_desc * ost_desc)
Add a new target to Quality of Service (QoS) target table.
Add a new OST target to the structure representing an OSS. Resort the list of known OSSs by the number of OSTs attached to each OSS. The OSS list is protected internally and no external locking is required.
Parameters:
[in] lod LOD device
[in] ost_desc OST description
Return values:
0 on success
-ENOMEM on error
Definition at line 74 of file lod_qos.c.
References ptlrpc_connection::c_remote_uuid, CDEBUG, D_QOS, ENTRY, obd_export::exp_connection, GOTO, list, list_add_tail(), list_del(), list_for_each_entry, lod_device::lod_qos, lod_qos::lq_dirty, lod_qos::lq_oss_list, lod_qos::lq_rr, lod_qos::lq_rw_sem, lod_qos_oss::lqo_oss_list, lod_qos_oss::lqo_ost_count, lod_qos_oss::lqo_uuid, lod_qos_rr::lqr_dirty, lod_tgt_desc::ltd_exp, lod_tgt_desc::ltd_qos, lod_tgt_desc::ltd_uuid, ltd_qos::ltq_oss, OBD_ALLOC_PTR, obd_uuid2str(), obd_uuid_equals(), and RETURN.
Referenced by lod_add_device().
int qos_del_tgt (struct lod_device * lod, struct lod_tgt_desc * ost_desc)
Remove OST target from QoS table.
Removes given OST target from QoS table and releases related OSS structure if no OSTs remain on the OSS.
Parameters:
[in] lod LOD device
[in] ost_desc OST description
Return values:
0 on success
-ENOENT if no OSS was found
Definition at line 145 of file lod_qos.c.
References CDEBUG, D_QOS, ENTRY, GOTO, list_del(), lod_device::lod_qos, lod_qos::lq_dirty, lod_qos::lq_rr, lod_qos::lq_rw_sem, lod_qos_oss::lqo_oss_list, lod_qos_oss::lqo_ost_count, lod_qos_oss::lqo_uuid, lod_qos_rr::lqr_dirty, lod_tgt_desc::ltd_qos, ltd_qos::ltq_oss, OBD_FREE_PTR, obd_uuid2str(), and RETURN.
Referenced by lod_putref().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.