Lustre: lustre/lov/lov_object.c File Reference
lustre/lov/lov_object.c File Reference
#include "lov_cl_internal.h"
Data Structures
struct lov_layout_operations
Defines
#define DEBUG_SUBSYSTEM S_LOV
#define LOV_2DISPATCH_NOLOCK(obj, op,...)
Performs a double-dispatch based on the layout type of an object.
#define LOV_2DISPATCH_MAYLOCK(obj, op, lock,...)
#define LOV_2DISPATCH(obj, op,...) LOV_2DISPATCH_MAYLOCK(obj, op, 1, __VA_ARGS__)
Performs a locked double-dispatch based on the layout type of an object.
#define LOV_2DISPATCH_VOID(obj, op,...)
#define FIEMAP_BUFFER_SIZE 4096
Functions
static struct lov_device * lov_object_dev (struct lov_object *obj)
static int lov_layout_wait (const struct lu_env *env, struct lov_object *lov)
static void lov_lsm_put (struct lov_stripe_md *lsm)
static void lov_install_empty (const struct lu_env *env, struct lov_object *lov, union lov_layout_state *state)
static int lov_init_empty (const struct lu_env *env, struct lov_device *dev, struct lov_object *lov, struct lov_stripe_md *lsm, const struct cl_object_conf *conf, union lov_layout_state *state)
static void lov_install_raid0 (const struct lu_env *env, struct lov_object *lov, union lov_layout_state *state)
static struct cl_object * lov_sub_find (const struct lu_env *env, struct cl_device *dev, const struct lu_fid *fid, const struct cl_object_conf *conf)
static int lov_init_sub (const struct lu_env *env, struct lov_object *lov, struct cl_object *stripe, struct lov_layout_raid0 *r0, int idx)
static int lov_page_slice_fixup (struct lov_object *lov, struct cl_object *stripe)
static int lov_init_raid0 (const struct lu_env *env, struct lov_device *dev, struct lov_object *lov, struct lov_stripe_md *lsm, const struct cl_object_conf *conf, union lov_layout_state *state)
static int lov_init_released (const struct lu_env *env, struct lov_device *dev, struct lov_object *lov, struct lov_stripe_md *lsm, const struct cl_object_conf *conf, union lov_layout_state *state)
static struct cl_object * lov_find_subobj (const struct lu_env *env, struct lov_object *lov, struct lov_stripe_md *lsm, int stripe_idx)
static int lov_delete_empty (const struct lu_env *env, struct lov_object *lov, union lov_layout_state *state)
static void lov_subobject_kill (const struct lu_env *env, struct lov_object *lov, struct lovsub_object *los, int idx)
static int lov_delete_raid0 (const struct lu_env *env, struct lov_object *lov, union lov_layout_state *state)
static void lov_fini_empty (const struct lu_env *env, struct lov_object *lov, union lov_layout_state *state)
static void lov_fini_raid0 (const struct lu_env *env, struct lov_object *lov, union lov_layout_state *state)
static void lov_fini_released (const struct lu_env *env, struct lov_object *lov, union lov_layout_state *state)
static int lov_print_empty (const struct lu_env *env, void *cookie, lu_printer_t p, const struct lu_object *o)
static int lov_print_raid0 (const struct lu_env *env, void *cookie, lu_printer_t p, const struct lu_object *o)
static int lov_print_released (const struct lu_env *env, void *cookie, lu_printer_t p, const struct lu_object *o)
static int lov_attr_get_empty (const struct lu_env *env, struct cl_object *obj, struct cl_attr *attr)
Implements cl_object_operations::coo_attr_get() method for an object without stripes (LLT_EMPTY layout type).
static int lov_attr_get_raid0 (const struct lu_env *env, struct cl_object *obj, struct cl_attr *attr)
static enum lov_layout_type lov_type (struct lov_stripe_md *lsm)
Return lov_layout_type associated with a given lsm.
static void lov_conf_freeze (struct lov_object *lov)
static void lov_conf_thaw (struct lov_object *lov)
static void lov_conf_lock (struct lov_object *lov)
static void lov_conf_unlock (struct lov_object *lov)
static int lov_layout_change (const struct lu_env *unused, struct lov_object *lov, struct lov_stripe_md *lsm, const struct cl_object_conf *conf)
int lov_object_init (const struct lu_env *env, struct lu_object *obj, const struct lu_object_conf *conf)
static int lov_conf_set (const struct lu_env *env, struct cl_object *obj, const struct cl_object_conf *conf)
static void lov_object_delete (const struct lu_env *env, struct lu_object *obj)
static void lov_object_free (const struct lu_env *env, struct lu_object *obj)
static int lov_object_print (const struct lu_env *env, void *cookie, lu_printer_t p, const struct lu_object *o)
int lov_page_init (const struct lu_env *env, struct cl_object *ob, struct cl_page *page, pgoff_t index)
int lov_io_init (const struct lu_env *env, struct cl_object *obj, struct cl_io *io)
Implements cl_object_operations::clo_io_init() method for lov layer.
static int lov_attr_get (const struct lu_env *env, struct cl_object *obj, struct cl_attr *attr)
An implementation of cl_object_operations::clo_attr_get() method for lov layer.
static int lov_attr_update (const struct lu_env *env, struct cl_object *obj, const struct cl_attr *attr, unsigned valid)
int lov_lock_init (const struct lu_env *env, struct cl_object *obj, struct cl_lock *lock, const struct cl_io *io)
static int fiemap_calc_last_stripe (struct lov_stripe_md *lsm, loff_t fm_start, loff_t fm_end, int start_stripe, int *stripe_count)
We calculate on which OST the mapping will end.
static void fiemap_prepare_and_copy_exts (struct fiemap *fiemap, struct fiemap_extent *lcl_fm_ext, int ost_index, unsigned int ext_count, int current_extent)
Set fe_device and copy extents from local buffer into main return buffer.
static loff_t fiemap_calc_fm_end_offset (struct fiemap *fiemap, struct lov_stripe_md *lsm, loff_t fm_start, loff_t fm_end, int *start_stripe)
Non-zero fe_logical indicates that this is a continuation FIEMAP call.
static int lov_object_fiemap (const struct lu_env *env, struct cl_object *obj, struct ll_fiemap_info_key *fmkey, struct fiemap *fiemap, size_t *buflen)
Break down the FIEMAP request and send appropriate calls to individual OSTs.
static int lov_object_getstripe (const struct lu_env *env, struct cl_object *obj, struct lov_user_md __user *lum)
static int lov_object_layout_get (const struct lu_env *env, struct cl_object *obj, struct cl_layout *cl)
static loff_t lov_object_maxbytes (struct cl_object *obj)
struct lu_object * lov_object_alloc (const struct lu_env *env, const struct lu_object_header *hdr, struct lu_device *dev)
struct lov_stripe_md * lov_lsm_addref (struct lov_object *lov)
int lov_read_and_clear_async_rc (struct cl_object *clob)
Variables
static const struct
lov_layout_operations lov_dispatch []
static struct cl_object_operations lov_ops
static struct lu_object_operations lov_lu_obj_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_LOV
Definition at line 42 of file lov_object.c.
Function Documentation
static struct lov_device* lov_object_dev (struct lov_object * obj) [static, read]
Definition at line 46 of file lov_object.c.
References cl_object::co_lu, lov_object::lo_cl, lu_object::lo_dev, and lu2lov_dev().
Referenced by lov_conf_set(), lov_layout_change(), and lov_object_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.