Lustre: lustre/lov/lov_ea.c File Reference
lustre/lov/lov_ea.c File Reference
#include <linux/math64.h>
#include <libcfs/libcfs.h>
#include <obd_class.h>
#include <lustre/lustre_idl.h>
#include "lov_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LOV
Functions
static int lsm_lmm_verify_common (struct lov_mds_md *lmm, int lmm_bytes, __u16 stripe_count)
struct lov_stripe_md * lsm_alloc_plain (u16 stripe_count)
void lsm_free_plain (struct lov_stripe_md *lsm)
static loff_t lov_tgt_maxbytes (struct lov_tgt_desc *tgt)
static int lsm_unpackmd_common (struct lov_obd *lov, struct lov_stripe_md *lsm, struct lov_mds_md *lmm, struct lov_ost_data_v1 *objects)
static void lsm_stripe_by_index_plain (struct lov_stripe_md *lsm, int *stripeno, loff_t *lov_off, loff_t *swidth)
static void lsm_stripe_by_offset_plain (struct lov_stripe_md *lsm, int *stripeno, loff_t *lov_off, loff_t *swidth)
static int lsm_lmm_verify_v1 (struct lov_mds_md_v1 *lmm, int lmm_bytes, __u16 *stripe_count)
static int lsm_unpackmd_v1 (struct lov_obd *lov, struct lov_stripe_md *lsm, struct lov_mds_md_v1 *lmm)
static int lsm_lmm_verify_v3 (struct lov_mds_md *lmmv1, int lmm_bytes, __u16 *stripe_count)
static int lsm_unpackmd_v3 (struct lov_obd *lov, struct lov_stripe_md *lsm, struct lov_mds_md *lmm)
void dump_lsm (unsigned int level, const struct lov_stripe_md *lsm)
Variables
struct lsm_operations lsm_v1_ops
struct lsm_operations lsm_v3_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_LOV
Definition at line 41 of file lov_ea.c.
Function Documentation
void dump_lsm (unsigned int level, const struct lov_stripe_md * lsm)
Definition at line 324 of file lov_ea.c.
References CDEBUG, DOSTID, LOV_POOLNAMEF, LPX64, lov_stripe_md::lsm_layout_gen, lov_stripe_md::lsm_magic, lov_stripe_md::lsm_maxbytes, lov_stripe_md::lsm_oi, lov_stripe_md::lsm_pool_name, lov_stripe_md::lsm_refc, lov_stripe_md::lsm_stripe_count, lov_stripe_md::lsm_stripe_size, and POSTID.
Referenced by lov_delete_raid0(), lov_fini_raid0(), lov_fini_released(), and lov_init_raid0().
static loff_t lov_tgt_maxbytes (struct lov_tgt_desc * tgt) [static]
Definition at line 131 of file lov_ea.c.
References client_obd::cl_import, obd_device::cli, obd_import::imp_connect_data, obd_import::imp_lock, obd_import::imp_state, lov_tgt_desc::ltd_active, lov_tgt_desc::ltd_obd, LUSTRE_EXT3_STRIPE_MAXBYTES, LUSTRE_IMP_FULL, OBD_CONNECT_MAXBYTES, obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_maxbytes, and obd_device::u.
Referenced by lsm_unpackmd_common().
struct lov_stripe_md* lsm_alloc_plain (u16 stripe_count) [read]
Definition at line 82 of file lov_ea.c.
References LASSERT, LOV_MAX_STRIPE_COUNT, lov_oinfo_slab, lov_stripe_md::lsm_oinfo, lov_stripe_md::lsm_stripe_count, OBD_ALLOC_LARGE, OBD_FREE_LARGE, OBD_SLAB_ALLOC_PTR_GFP, and OBD_SLAB_FREE.
Referenced by lov_lsm_alloc().
void lsm_free_plain (struct lov_stripe_md * lsm)
Definition at line 117 of file lov_ea.c.
References lov_oinfo_slab, lov_stripe_md::lsm_oinfo, lov_stripe_md::lsm_stripe_count, OBD_FREE_LARGE, and OBD_SLAB_FREE.
static int lsm_lmm_verify_common (struct lov_mds_md * lmm, int lmm_bytes, __u16 stripe_count) [static]
Definition at line 51 of file lov_ea.c.
References CERROR, D_WARNING, le32_to_cpu, lmm_oi_id(), lov_dump_lmm_common(), LOV_MIN_STRIPE_SIZE, lov_pattern, LOV_PATTERN_RAID0, and LOV_V1_INSANE_STRIPE_COUNT.
Referenced by lsm_lmm_verify_v1(), and lsm_lmm_verify_v3().
static int lsm_lmm_verify_v1 (struct lov_mds_md_v1 * lmm, int lmm_bytes, __u16 * stripe_count) [static]
Definition at line 232 of file lov_ea.c.
References CERROR, D_WARNING, le16_to_cpu, le32_to_cpu, lov_mds_md_v1::lmm_pattern, lov_mds_md_v1::lmm_stripe_count, lov_dump_lmm_common(), LOV_MAGIC_V1, lov_mds_md_size(), LOV_PATTERN_F_RELEASED, and lsm_lmm_verify_common().
static int lsm_lmm_verify_v3 (struct lov_mds_md * lmmv1, int lmm_bytes, __u16 * stripe_count) [static]
Definition at line 269 of file lov_ea.c.
References CERROR, D_WARNING, le16_to_cpu, le32_to_cpu, lov_mds_md_v3::lmm_pattern, lov_mds_md_v3::lmm_stripe_count, lov_dump_lmm_common(), LOV_MAGIC_V3, lov_mds_md_size(), LOV_PATTERN_F_RELEASED, and lsm_lmm_verify_common().
static void lsm_stripe_by_index_plain (struct lov_stripe_md * lsm, int * stripeno, loff_t * lov_off, loff_t * swidth) [static]
Definition at line 217 of file lov_ea.c.
References lov_stripe_md::lsm_stripe_count, and lov_stripe_md::lsm_stripe_size.
static void lsm_stripe_by_offset_plain (struct lov_stripe_md * lsm, int * stripeno, loff_t * lov_off, loff_t * swidth) [static]
Definition at line 225 of file lov_ea.c.
References lov_stripe_md::lsm_stripe_count, and lov_stripe_md::lsm_stripe_size.
static int lsm_unpackmd_common (struct lov_obd * lov, struct lov_stripe_md * lsm, struct lov_mds_md * lmm, struct lov_ost_data_v1 * objects) [static]
Definition at line 154 of file lov_ea.c.
References CERROR, D_WARNING, lov_obd::desc, lov_desc::ld_tgt_count, lov_desc::ld_uuid, le16_to_cpu, le32_to_cpu, lmm_oi_le_to_cpu(), lov_oinfo::loi_oi, lov_oinfo::loi_ost_gen, lov_oinfo::loi_ost_idx, lov2obd(), lov_dump_lmm_v1(), lov_oinfo_is_dummy(), lov_tgt_maxbytes(), lov_obd::lov_tgts, lsm_is_released(), lov_stripe_md::lsm_layout_gen, lov_stripe_md::lsm_maxbytes, lov_stripe_md::lsm_oi, lov_stripe_md::lsm_oinfo, lov_stripe_md::lsm_pattern, lov_stripe_md::lsm_pool_name, lov_stripe_md::lsm_stripe_count, lov_stripe_md::lsm_stripe_size, LUSTRE_EXT3_STRIPE_MAXBYTES, min_t, ostid_le_to_cpu(), and obd_uuid::uuid.
Referenced by lsm_unpackmd_v1(), and lsm_unpackmd_v3().
static int lsm_unpackmd_v1 (struct lov_obd * lov, struct lov_stripe_md * lsm, struct lov_mds_md_v1 * lmm) [static]
Definition at line 255 of file lov_ea.c.
References lov_mds_md_v1::lmm_objects, and lsm_unpackmd_common().
static int lsm_unpackmd_v3 (struct lov_obd * lov, struct lov_stripe_md * lsm, struct lov_mds_md * lmm) [static]
Definition at line 297 of file lov_ea.c.
References lov_mds_md_v3::lmm_objects, lov_mds_md_v3::lmm_pool_name, lov_stripe_md::lsm_pool_name, lsm_unpackmd_common(), and strlcpy().
Variable Documentation
struct lsm_operations lsm_v1_ops
Initial value:
 {
        .lsm_free            = lsm_free_plain,
        .lsm_stripe_by_index    = lsm_stripe_by_index_plain,
        .lsm_stripe_by_offset   = lsm_stripe_by_offset_plain,
        .lsm_lmm_verify         = lsm_lmm_verify_v1,
        .lsm_unpackmd           = lsm_unpackmd_v1,
}
Definition at line 261 of file lov_ea.c.
Referenced by lsm_op_find().
struct lsm_operations lsm_v3_ops
Initial value:
 {
        .lsm_free            = lsm_free_plain,
        .lsm_stripe_by_index    = lsm_stripe_by_index_plain,
        .lsm_stripe_by_offset   = lsm_stripe_by_offset_plain,
        .lsm_lmm_verify         = lsm_lmm_verify_v3,
        .lsm_unpackmd           = lsm_unpackmd_v3,
}
Definition at line 316 of file lov_ea.c.
Referenced by lsm_op_find().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.