Lustre: lustre/lov/lov_pool.c File Reference
lustre/lov/lov_pool.c File Reference
#include <libcfs/libcfs.h>
#include <obd.h>
#include "lov_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LOV
#define pool_tgt(_p, _i) _p->pool_lobd->u.lov.lov_tgts[_p->pool_obds.op_array[_i]]
#define LOV_POOL_INIT_COUNT 2
Functions
static void lov_pool_getref (struct pool_desc *pool)
static void lov_pool_putref (struct pool_desc *pool)
static void lov_pool_putref_locked (struct pool_desc *pool)
static __u32 pool_hashfn (struct cfs_hash *hash_body, const void *key, unsigned mask)
static void * pool_key (struct hlist_node *hnode)
static int pool_hashkey_keycmp (const void *key, struct hlist_node *compared_hnode)
static void * pool_hashobject (struct hlist_node *hnode)
static void pool_hashrefcount_get (struct cfs_hash *hs, struct hlist_node *hnode)
static void pool_hashrefcount_put_locked (struct cfs_hash *hs, struct hlist_node *hnode)
void lov_dump_pool (int level, struct pool_desc *pool)
int lov_ost_pool_init (struct ost_pool *op, unsigned int count)
int lov_ost_pool_extend (struct ost_pool *op, unsigned int min_count)
int lov_ost_pool_add (struct ost_pool *op, __u32 idx, unsigned int min_count)
int lov_ost_pool_remove (struct ost_pool *op, __u32 idx)
int lov_ost_pool_free (struct ost_pool *op)
int lov_pool_new (struct obd_device *obd, char *poolname)
int lov_pool_del (struct obd_device *obd, char *poolname)
int lov_pool_add (struct obd_device *obd, char *poolname, char *ostname)
int lov_pool_remove (struct obd_device *obd, char *poolname, char *ostname)
Variables
struct cfs_hash_ops pool_hash_operations
Define Documentation
#define DEBUG_SUBSYSTEM S_LOV
Definition at line 45 of file lov_pool.c.
#define LOV_POOL_INIT_COUNT 2
Definition at line 323 of file lov_pool.c.
Referenced by lov_ost_pool_init().
#define pool_tgt (_p, _i) _p->pool_lobd->u.lov.lov_tgts[_p->pool_obds.op_array[_i]]
Definition at line 52 of file lov_pool.c.
Function Documentation
void lov_dump_pool (int level, struct pool_desc * pool)
Definition at line 301 of file lov_pool.c.
References CDEBUG, lov_pool_getref(), lov_pool_putref(), LOV_POOLNAMEF, obd_uuid2str(), ost_pool::op_count, pool_desc::pool_name, pool_desc::pool_obds, pool_tgt, pool_tgt_count, and pool_tgt_rw_sem.
int lov_ost_pool_add (struct ost_pool * op, __u32 idx, unsigned int min_count)
Definition at line 367 of file lov_pool.c.
References ENTRY, EXIT, GOTO, lov_ost_pool_extend(), ost_pool::op_array, ost_pool::op_count, and ost_pool::op_rw_sem.
Referenced by lov_add_target(), and lov_pool_add().
int lov_ost_pool_extend (struct ost_pool * op, unsigned int min_count)
Definition at line 344 of file lov_pool.c.
References LASSERT, max, OBD_ALLOC, OBD_FREE, ost_pool::op_array, ost_pool::op_count, and ost_pool::op_size.
Referenced by lov_ost_pool_add().
int lov_ost_pool_free (struct ost_pool * op)
Definition at line 414 of file lov_pool.c.
References ENTRY, OBD_FREE, ost_pool::op_array, ost_pool::op_count, ost_pool::op_rw_sem, ost_pool::op_size, and RETURN.
Referenced by lov_cleanup(), lov_pool_new(), and lov_pool_putref().
int lov_ost_pool_init (struct ost_pool * op, unsigned int count)
Definition at line 324 of file lov_pool.c.
References ENTRY, EXIT, LOV_POOL_INIT_COUNT, OBD_ALLOC, ost_pool::op_array, ost_pool::op_count, ost_pool::op_rw_sem, ost_pool::op_size, and RETURN.
Referenced by lov_pool_new(), and lov_setup().
int lov_ost_pool_remove (struct ost_pool * op, __u32 idx)
Definition at line 392 of file lov_pool.c.
References ENTRY, EXIT, ost_pool::op_array, ost_pool::op_count, ost_pool::op_rw_sem, and RETURN.
Referenced by lov_pool_remove(), and lov_putref().
int lov_pool_add (struct obd_device * obd, char * poolname, char * ostname)
Definition at line 535 of file lov_pool.c.
References CDEBUG, cfs_hash_lookup(), D_CONFIG, lov_obd::desc, ENTRY, EXIT, GOTO, lov_desc::ld_tgt_count, obd_device::lov, lov_ost_pool_add(), lov_pool_putref(), LOV_POOLNAMEF, lov_obd::lov_pools_hash_body, lov_obd::lov_tgt_size, lov_obd::lov_tgts, lov_tgt_desc::ltd_uuid, obd_getref(), obd_putref(), obd_str2uuid(), obd_uuid_equals(), pool_desc::pool_obds, pool_tgt_count, RETURN, and obd_device::u.
int lov_pool_del (struct obd_device * obd, char * poolname)
Definition at line 504 of file lov_pool.c.
References CDEBUG, cfs_hash_del_key(), D_INFO, ENTRY, list_del_init(), obd_device::lov, lov_obd::lov_pool_count, lov_pool_putref(), lov_obd::lov_pools_hash_body, lprocfs_remove(), obd_device::obd_dev_lock, pool_desc::pool_list, pool_desc::pool_proc_entry, RETURN, and obd_device::u.
Referenced by lov_cleanup().
static void lov_pool_getref (struct pool_desc * pool) [static]
Definition at line 55 of file lov_pool.c.
References CDEBUG, D_INFO, and pool_desc::pool_refcount.
Referenced by lov_dump_pool(), lov_pool_new(), and pool_hashrefcount_get().
int lov_pool_new (struct obd_device * obd, char * poolname)
Definition at line 433 of file lov_pool.c.
References CDEBUG, cfs_hash_add_unique(), CWARN, D_CONFIG, D_INFO, ENTRY, GOTO, INIT_HLIST_NODE, list_add_tail(), list_del_init(), obd_device::lov, LOV_MAXPOOLNAME, lov_ost_pool_free(), lov_ost_pool_init(), lov_obd::lov_pool_count, lov_pool_getref(), lov_obd::lov_pool_list, lov_obd::lov_pool_proc_entry, lov_pool_putref(), LOV_POOLNAMEF, lov_obd::lov_pools_hash_body, lprocfs_add_simple(), lprocfs_remove(), OBD_ALLOC_PTR, obd_device::obd_dev_lock, OBD_FREE_PTR, pool_desc::pool_hash, pool_desc::pool_list, pool_desc::pool_lobd, pool_desc::pool_name, pool_desc::pool_obds, pool_desc::pool_proc_entry, pool_desc::pool_refcount, RETURN, strlcpy(), and obd_device::u.
static void lov_pool_putref (struct pool_desc * pool) [static]
Definition at line 61 of file lov_pool.c.
References CDEBUG, D_INFO, EXIT, hlist_unhashed(), LASSERT, list_empty(), lov_ost_pool_free(), OBD_FREE_PTR, pool_desc::pool_hash, pool_desc::pool_list, pool_desc::pool_obds, pool_desc::pool_proc_entry, and pool_desc::pool_refcount.
Referenced by lov_dump_pool(), lov_pool_add(), lov_pool_del(), lov_pool_new(), and lov_pool_remove().
static void lov_pool_putref_locked (struct pool_desc * pool) [static]
Definition at line 74 of file lov_pool.c.
References CDEBUG, D_INFO, LASSERT, and pool_desc::pool_refcount.
Referenced by pool_hashrefcount_put_locked().
int lov_pool_remove (struct obd_device * obd, char * poolname, char * ostname)
Definition at line 580 of file lov_pool.c.
References CDEBUG, cfs_hash_lookup(), D_CONFIG, lov_obd::desc, ENTRY, EXIT, GOTO, lov_desc::ld_tgt_count, obd_device::lov, lov_ost_pool_remove(), lov_pool_putref(), LOV_POOLNAMEF, lov_obd::lov_pools_hash_body, lov_obd::lov_tgts, lov_tgt_desc::ltd_uuid, obd_getref(), obd_putref(), obd_str2uuid(), obd_uuid_equals(), pool_desc::pool_obds, RETURN, and obd_device::u.
static __u32 pool_hashfn (struct cfs_hash * hash_body, const void * key, unsigned mask) [static]
Definition at line 89 of file lov_pool.c.
References LOV_MAXPOOLNAME, and poolname.
static int pool_hashkey_keycmp (const void * key, struct hlist_node * compared_hnode) [static]
Definition at line 115 of file lov_pool.c.
References hlist_entry, LOV_MAXPOOLNAME, pool_desc::pool_hash, and pool_desc::pool_name.
static void* pool_hashobject (struct hlist_node * hnode) [static]
Definition at line 125 of file lov_pool.c.
References hlist_entry, and pool_desc::pool_hash.
static void pool_hashrefcount_get (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 130 of file lov_pool.c.
References hlist_entry, lov_pool_getref(), and pool_desc::pool_hash.
static void pool_hashrefcount_put_locked (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 138 of file lov_pool.c.
References hlist_entry, lov_pool_putref_locked(), and pool_desc::pool_hash.
static void* pool_key (struct hlist_node * hnode) [static]
Definition at line 106 of file lov_pool.c.
References hlist_entry, pool_desc::pool_hash, and pool_desc::pool_name.
Variable Documentation
struct cfs_hash_ops pool_hash_operations
Initial value:
 {
        .hs_hash        = pool_hashfn,
        .hs_key         = pool_key,
        .hs_keycmp      = pool_hashkey_keycmp,
        .hs_object      = pool_hashobject,
        .hs_get         = pool_hashrefcount_get,
        .hs_put_locked  = pool_hashrefcount_put_locked,
}
Definition at line 147 of file lov_pool.c.
Referenced by lod_pools_init(), and lov_setup().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.