Lustre: lustre/lov/lov_obd.c File Reference
lustre/lov/lov_obd.c File Reference
#include <libcfs/libcfs.h>
#include <lustre/lustre_idl.h>
#include <cl_object.h>
#include <lustre_dlm.h>
#include <lustre_fid.h>
#include <lustre_ioctl.h>
#include <lustre_lib.h>
#include <lustre_mds.h>
#include <lustre_net.h>
#include <lustre_param.h>
#include <lustre_swab.h>
#include <lprocfs_status.h>
#include <obd_class.h>
#include <obd_support.h>
#include "lov_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LOV
Functions
static void lov_getref (struct obd_device *obd)
static void __lov_del_obd (struct obd_device *obd, struct lov_tgt_desc *tgt)
static void lov_putref (struct obd_device *obd)
static int lov_set_osc_active (struct obd_device *obd, struct obd_uuid *uuid, enum obd_notify_event ev)
static int lov_notify (struct obd_device *obd, struct obd_device *watched, enum obd_notify_event ev, void *data)
int lov_connect_obd (struct obd_device *obd, __u32 index, int activate, struct obd_connect_data *data)
static int lov_connect (const struct lu_env *env, struct obd_export **exp, struct obd_device *obd, struct obd_uuid *cluuid, struct obd_connect_data *data, void *localdata)
static int lov_disconnect_obd (struct obd_device *obd, struct lov_tgt_desc *tgt)
static int lov_disconnect (struct obd_export *exp)
static int lov_add_target (struct obd_device *obd, struct obd_uuid *uuidp, __u32 index, int gen, int active)
int lov_del_target (struct obd_device *obd, __u32 index, struct obd_uuid *uuidp, int gen)
void lov_fix_desc_stripe_size (__u64 *val)
void lov_fix_desc_stripe_count (__u32 *val)
void lov_fix_desc_pattern (__u32 *val)
void lov_fix_desc_qos_maxage (__u32 *val)
void lov_fix_desc (struct lov_desc *desc)
int lov_setup (struct obd_device *obd, struct lustre_cfg *lcfg)
static int lov_cleanup (struct obd_device *obd)
int lov_process_config_base (struct obd_device *obd, struct lustre_cfg *lcfg, __u32 *indexp, int *genp)
int lov_statfs_interpret (struct ptlrpc_request_set *rqset, void *data, int rc)
static int lov_statfs_async (struct obd_export *exp, struct obd_info *oinfo, __u64 max_age, struct ptlrpc_request_set *rqset)
static int lov_statfs (const struct lu_env *env, struct obd_export *exp, struct obd_statfs *osfs, __u64 max_age, __u32 flags)
static int lov_iocontrol (unsigned int cmd, struct obd_export *exp, int len, void *karg, void __user *uarg)
static int lov_get_info (const struct lu_env *env, struct obd_export *exp, __u32 keylen, void *key, __u32 *vallen, void *val)
static int lov_set_info_async (const struct lu_env *env, struct obd_export *exp, __u32 keylen, void *key, __u32 vallen, void *val, struct ptlrpc_request_set *set)
void lov_stripe_lock (struct lov_stripe_md *md) __acquires(&md->lsm_lock)
void lov_stripe_unlock (struct lov_stripe_md *md) __releases(&md->lsm_lock)
static int lov_quotactl (struct obd_device *obd, struct obd_export *exp, struct obd_quotactl *oqctl)
static int __init lov_init (void)
static void __exit lov_exit (void)
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Logical Object Volume")
MODULE_VERSION (LUSTRE_VERSION_STRING)
MODULE_LICENSE ("GPL")
module_init (lov_init)
module_exit (lov_exit)
Variables
static struct obd_ops lov_obd_ops
struct kmem_cache * lov_oinfo_slab
Define Documentation
#define DEBUG_SUBSYSTEM S_LOV
Definition at line 44 of file lov_obd.c.
Function Documentation
static void __lov_del_obd (struct obd_device * obd, struct lov_tgt_desc * tgt) [static]
Definition at line 712 of file lov_obd.c.
References CDEBUG, class_exp2obd(), class_manual_cleanup(), D_CONFIG, LASSERT, lov_disconnect_obd(), lov_tgt_desc::ltd_exp, lov_tgt_desc::ltd_reap, lov_tgt_desc::ltd_uuid, OBD_FREE_PTR, obd_device::obd_name, and obd_uuid::uuid.
Referenced by lov_putref().
static int lov_add_target (struct obd_device * obd, struct obd_uuid * uuidp, __u32 index, int gen, int active) [static]
Definition at line 532 of file lov_obd.c.
References CDEBUG, CERROR, class_find_client_obd(), D_CONFIG, lov_obd::desc, ENTRY, obd_export::exp_obd, GOTO, KEY_CACHE_SET, lov_desc::ld_tgt_count, obd_device::lov, lov_obd::lov_cache, lov_connect_obd(), lov_obd::lov_connects, lov_del_target(), lov_obd::lov_lock, lov_notify(), lov_obd::lov_ocd, lov_ost_pool_add(), lov_obd::lov_packed, lov_obd::lov_tgt_size, lov_obd::lov_tgts, lov_tgt_desc::ltd_activate, lov_tgt_desc::ltd_exp, lov_tgt_desc::ltd_gen, lov_tgt_desc::ltd_index, lov_tgt_desc::ltd_obd, lov_tgt_desc::ltd_uuid, LUSTRE_OSC_NAME, max, OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, obd_getref(), obd_notify(), OBD_NOTIFY_CONNECT, OBD_NOTIFY_CREATE, OBD_NOTIFY_INACTIVE, obd_putref(), obd_set_info_async(), obd_device::obd_uuid, obd_uuid2str(), RETURN, obd_device::u, and obd_uuid::uuid.
Referenced by lov_process_config_base().
static int lov_cleanup (struct obd_device * obd) [static]
Definition at line 886 of file lov_obd.c.
References CDEBUG, CERROR, cfs_hash_putref(), cl_cache_decref(), D_INFO, lov_obd::desc, ENTRY, lov_desc::ld_tgt_count, list_entry, list_for_each_safe, obd_device::lov, lov_obd::lov_cache, lov_obd::lov_death_row, lov_del_target(), lov_ost_pool_free(), lov_obd::lov_packed, lov_pool_del(), lov_obd::lov_pool_list, lov_obd::lov_pools_hash_body, lov_obd::lov_refcount, lov_obd::lov_tgt_size, lov_obd::lov_tgts, lprocfs_obd_cleanup(), lov_tgt_desc::ltd_active, OBD_FREE, obd_getref(), obd_device::obd_name, obd_putref(), pool_desc::pool_list, pool_desc::pool_name, RETURN, and obd_device::u.
static int lov_connect (const struct lu_env * env, struct obd_export ** exp, struct obd_device * obd, struct obd_uuid * cluuid, struct obd_connect_data * data, void * localdata) [static]
Definition at line 214 of file lov_obd.c.
References CDEBUG, CERROR, class_conn2export(), class_connect(), D_CONFIG, lov_obd::desc, ENTRY, obd_export::exp_obd, LASSERT, lov_desc::ld_tgt_count, obd_device::lov, lov_connect_obd(), lov_obd::lov_connects, lov_notify(), lov_obd::lov_ocd, lov_obd::lov_tgts, lprocfs_register(), lov_tgt_desc::ltd_activate, lov_tgt_desc::ltd_exp, lov_tgt_desc::ltd_uuid, obd_getref(), obd_device::obd_name, OBD_NOTIFY_CONNECT, obd_device::obd_proc_entry, obd_putref(), obd_device::obd_type, obd_uuid_empty(), RETURN, lov_obd::targets_proc_entry, obd_type::typ_name, and obd_device::u.
int lov_connect_obd (struct obd_device * obd, __u32 index, int activate, struct obd_connect_data * data)
Definition at line 122 of file lov_obd.c.
References CDEBUG, CERROR, client_obd::cl_import, client_obd::cl_sp_me, obd_device::cli, D_CONFIG, ENTRY, obd_export::exp_obd, obd_import::imp_invalid, LASSERT, obd_device::lov, lov_obd::lov_sp_me, lov_obd::lov_tgts, lprocfs_add_symlink(), lov_tgt_desc::ltd_exp, lov_tgt_desc::ltd_obd, lov_tgt_desc::ltd_reap, lov_tgt_desc::ltd_uuid, obd_connect(), OBD_CONNECT_INDEX, OBD_DEVICE_MAGIC, obd_device::obd_magic, obd_device::obd_name, obd_device::obd_no_recov, obd_register_observer(), obd_device::obd_set_up, obd_device::obd_type, obd_uuid2str(), obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_index, ptlrpc_activate_import(), RETURN, lov_obd::targets_proc_entry, obd_type::typ_name, and obd_device::u.
Referenced by lov_add_target(), and lov_connect().
int lov_del_target (struct obd_device * obd, __u32 index, struct obd_uuid * uuidp, int gen)
Definition at line 667 of file lov_obd.c.
References CDEBUG, CERROR, D_CONFIG, lov_obd::desc, ENTRY, GOTO, lov_desc::ld_tgt_count, obd_device::lov, lov_obd::lov_death_row, lov_obd::lov_notify_lock, lov_obd::lov_tgts, lov_uuid2str, lov_tgt_desc::ltd_active, lov_tgt_desc::ltd_exp, lov_tgt_desc::ltd_gen, lov_tgt_desc::ltd_reap, lov_tgt_desc::ltd_uuid, obd_getref(), obd_putref(), obd_uuid2str(), obd_uuid_equals(), RETURN, and obd_device::u.
Referenced by lov_add_target(), lov_cleanup(), lov_disconnect(), lov_process_config(), and lov_process_config_base().
static int lov_disconnect (struct obd_export * exp) [static]
Definition at line 323 of file lov_obd.c.
References CERROR, class_disconnect(), class_exp2obd(), lov_obd::desc, ENTRY, lov_desc::ld_tgt_count, obd_device::lov, lov_obd::lov_connects, lov_del_target(), lov_obd::lov_tgts, lprocfs_remove(), lov_tgt_desc::ltd_exp, lov_tgt_desc::ltd_gen, obd_getref(), obd_putref(), RETURN, lov_obd::targets_proc_entry, and obd_device::u.
static int lov_disconnect_obd (struct obd_device * obd, struct lov_tgt_desc * tgt) [static]
Definition at line 279 of file lov_obd.c.
References CDEBUG, CERROR, class_exp2obd(), D_CONFIG, lov_obd::desc, ENTRY, obd_export::exp_obd, lov_desc::ld_active_tgt_count, obd_device::lov, lprocfs_remove_proc_entry(), lov_tgt_desc::ltd_active, lov_tgt_desc::ltd_exp, lov_tgt_desc::ltd_uuid, obd_disconnect(), obd_device::obd_fail, obd_device::obd_force, obd_device::obd_inactive, obd_device::obd_name, obd_device::obd_no_recov, obd_register_observer(), RETURN, lov_obd::targets_proc_entry, obd_device::u, and obd_uuid::uuid.
Referenced by __lov_del_obd().
static void __exit lov_exit (void) [static]
Definition at line 1504 of file lov_obd.c.
References class_unregister_type(), lov_caches, lov_oinfo_slab, lu_kmem_fini(), and LUSTRE_LOV_NAME.
void lov_fix_desc (struct lov_desc * desc)
Definition at line 774 of file lov_obd.c.
References lov_desc::ld_default_stripe_count, lov_desc::ld_default_stripe_size, lov_desc::ld_pattern, lov_desc::ld_qos_maxage, lov_fix_desc_pattern(), lov_fix_desc_qos_maxage(), lov_fix_desc_stripe_count(), and lov_fix_desc_stripe_size().
Referenced by lov_setup().
void lov_fix_desc_pattern (__u32 * val)
Definition at line 759 of file lov_obd.c.
References LCONSOLE_WARN, and LOV_PATTERN_RAID0.
Referenced by lov_fix_desc().
void lov_fix_desc_qos_maxage (__u32 * val)
Definition at line 768 of file lov_obd.c.
References LOV_DESC_QOS_MAXAGE_DEFAULT.
Referenced by lov_fix_desc().
void lov_fix_desc_stripe_count (__u32 * val)
Definition at line 753 of file lov_obd.c.
Referenced by lov_fix_desc().
void lov_fix_desc_stripe_size (__u64 * val)
Definition at line 737 of file lov_obd.c.
References LCONSOLE_INFO, LCONSOLE_WARN, LOV_DESC_STRIPE_SIZE_DEFAULT, LOV_MIN_STRIPE_SIZE, and LPU64.
Referenced by lov_fix_desc().
static int lov_get_info (const struct lu_env * env, struct obd_export * exp, __u32 keylen, void * key, __u32 * vallen, void * val) [static]
Definition at line 1269 of file lov_obd.c.
References class_exp2obd(), lov_obd::desc, ENTRY, KEY_DEFAULT_EASIZE, KEY_IS, KEY_MAX_EASIZE, KEY_TGT_COUNT, lov_desc::ld_active_tgt_count, lov_desc::ld_default_stripe_count, lov_desc::ld_tgt_count, obd_device::lov, LOV_MAGIC_V3, LOV_MAX_STRIPE_COUNT, lov_mds_md_size(), min_t, obd_getref(), obd_putref(), RETURN, and obd_device::u.
static void lov_getref (struct obd_device * obd) [static]
Definition at line 66 of file lov_obd.c.
References obd_device::lov, lov_obd::lov_lock, lov_obd::lov_refcount, and obd_device::u.
static int __init lov_init (void) [static]
Definition at line 1465 of file lov_obd.c.
References CDEBUG, class_register_type(), class_search_type(), D_INFO, ENTRY, lov_caches, lov_device_type, lov_oinfo_slab, lu_kmem_fini(), lu_kmem_init(), LUSTRE_LOD_NAME, LUSTRE_LOV_NAME, RETURN, and obd_type::typ_procsym.
static int lov_iocontrol (unsigned int cmd, struct obd_export * exp, int len, void * karg, void __user * uarg) [static]
Definition at line 1082 of file lov_obd.c.
References buf, CDEBUG, cfs_time_shift_64(), class_exp2obd(), D_IOCTL, D_WARNING, lov_obd::desc, ENTRY, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf2, obd_ioctl_data::ioc_inlbuf3, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, obd_ioctl_data::ioc_inllen3, IOC_OBD_STATFS, obd_ioctl_data::ioc_pbuf1, obd_ioctl_data::ioc_pbuf2, obd_ioctl_data::ioc_plen1, obd_ioctl_data::ioc_plen2, LASSERT, lov_desc::ld_tgt_count, LL_STATFS_NODELAY, obd_device::lov, lov_obd::lov_tgts, lov_uuid2str, lov_tgt_desc::ltd_active, lov_tgt_desc::ltd_exp, lov_tgt_desc::ltd_gen, lov_tgt_desc::ltd_uuid, min_t, obd2cli_tgt, OBD_ALLOC_PTR, obd_device::obd_force, OBD_FREE_PTR, OBD_IOC_LOV_GET_CONFIG, OBD_IOC_QUOTACTL, obd_iocontrol(), obd_ioctl_getdata(), obd_quotactl(), obd_statfs(), OBD_STATFS_CACHE_SECONDS, OBD_STATFS_NODELAY, if_quotactl::obd_uuid, obd_uuid_equals(), if_quotactl::qc_idx, QC_OSTIDX, QC_UUID, if_quotactl::qc_valid, QCTL_COPY, RETURN, obd_device::u, and obd_uuid::uuid.
static int lov_notify (struct obd_device * obd, struct obd_device * watched, enum obd_notify_event ev, void * data) [static]
Definition at line 450 of file lov_obd.c.
References CERROR, client_obd::cl_target_uuid, obd_device::cli, lov_obd::desc, ENTRY, LASSERT, lov_desc::ld_tgt_count, obd_device::lov, lov_obd::lov_connects, lov_obd::lov_notify_lock, lov_set_osc_active(), lov_obd::lov_tgts, lov_tgt_desc::ltd_active, lov_tgt_desc::ltd_obd, LUSTRE_OSC_NAME, obd_getref(), obd_device::obd_name, OBD_NOTIFY_ACTIVATE, OBD_NOTIFY_ACTIVE, OBD_NOTIFY_DEACTIVATE, OBD_NOTIFY_INACTIVE, obd_notify_observer(), OBD_NOTIFY_SYNC, OBD_NOTIFY_SYNC_NONBLOCK, obd_device::obd_observer, obd_putref(), obd_device::obd_type, obd_uuid2str(), RETURN, obd_type::typ_name, obd_device::u, and uuid.
Referenced by lov_add_target(), and lov_connect().
int lov_process_config_base (struct obd_device * obd, struct lustre_cfg * lcfg, __u32 * indexp, int * genp)
Definition at line 939 of file lov_obd.c.
References CERROR, class_process_proc_param(), cmd, lov_obd::desc, ENTRY, GOTO, lustre_cfg::lcfg_command, LCFG_LOV_ADD_INA, LCFG_LOV_ADD_OBD, LCFG_LOV_DEL_OBD, LCFG_PARAM, LCFG_POOL_ADD, LCFG_POOL_DEL, LCFG_POOL_NEW, LCFG_POOL_REM, obd_device::lov, lov_add_target(), lov_del_target(), lustre_cfg_buf(), LUSTRE_CFG_BUFLEN, obd_str2uuid(), obd_device::obd_vars, PARAM_LOV, RETURN, obd_device::u, and obd_uuid::uuid.
Referenced by lov_process_config().
static void lov_putref (struct obd_device * obd) [static]
Definition at line 79 of file lov_obd.c.
References __lov_del_obd(), CDEBUG, D_CONFIG, lov_obd::desc, lov_desc::ld_tgt_count, list_add(), list_del(), list_for_each_entry_safe, LIST_HEAD_INIT, obd_device::lov, lov_obd::lov_death_row, lov_obd::lov_lock, lov_ost_pool_remove(), lov_obd::lov_packed, lov_obd::lov_refcount, lov_obd::lov_tgts, lov_tgt_desc::ltd_kill, lov_tgt_desc::ltd_reap, and obd_device::u.
static int lov_quotactl (struct obd_device * obd, struct obd_export * exp, struct obd_quotactl * oqctl) [static]
Definition at line 1383 of file lov_obd.c.
References __u64, CDEBUG, CERROR, D_HA, lov_obd::desc, obd_dqblk::dqb_bhardlimit, obd_dqblk::dqb_curspace, ENTRY, lov_desc::ld_tgt_count, obd_device::lov, lov_obd::lov_tgts, lov_tgt_desc::ltd_activate, lov_tgt_desc::ltd_active, lov_tgt_desc::ltd_exp, lov_tgt_desc::ltd_reap, LUSTRE_Q_SETQUOTA, obd_getref(), obd_device::obd_name, obd_putref(), obd_quotactl(), Q_GETOQUOTA, obd_quotactl::qc_cmd, obd_quotactl::qc_dqblk, RETURN, and obd_device::u.
static int lov_set_info_async (const struct lu_env * env, struct obd_export * exp, __u32 keylen, void * key, __u32 vallen, void * val, struct ptlrpc_request_set * set) [static]
Definition at line 1304 of file lov_obd.c.
References cl_cache_incref(), class_exp2obd(), lov_obd::desc, ENTRY, KEY_CACHE_SET, KEY_CHECKSUM, KEY_IS, LASSERT, lov_desc::ld_tgt_count, obd_device::lov, lov_obd::lov_cache, lov_obd::lov_tgts, lov_tgt_desc::ltd_active, lov_tgt_desc::ltd_exp, obd_getref(), obd_putref(), obd_set_info_async(), ptlrpc_prep_set(), ptlrpc_set_destroy(), ptlrpc_set_wait(), RETURN, and obd_device::u.
static int lov_set_osc_active (struct obd_device * obd, struct obd_uuid * uuid, enum obd_notify_event ev) [static]
Definition at line 368 of file lov_obd.c.
References CDEBUG, CERROR, D_CONFIG, D_INFO, lov_obd::desc, ENTRY, obd_export::exp_handle, obd_export::exp_obd, GOTO, portals_handle::h_cookie, lov_desc::ld_active_tgt_count, lov_desc::ld_tgt_count, obd_device::lov, lov_obd::lov_ocd, lov_obd::lov_tgts, LPX64, lov_tgt_desc::ltd_activate, lov_tgt_desc::ltd_active, lov_tgt_desc::ltd_exp, lov_tgt_desc::ltd_obd, lov_tgt_desc::ltd_uuid, obd_connect(), obd_getref(), obd_device::obd_inactive, obd_device::obd_name, OBD_NOTIFY_ACTIVATE, OBD_NOTIFY_ACTIVE, OBD_NOTIFY_DEACTIVATE, OBD_NOTIFY_INACTIVE, obd_putref(), obd_uuid2str(), obd_uuid_equals(), RETURN, obd_device::u, and obd_uuid::uuid.
Referenced by lov_notify().
int lov_setup (struct obd_device * obd, struct lustre_cfg * lcfg)
Definition at line 782 of file lov_obd.c.
References __swab32, CDEBUG, CERROR, cfs_hash_create(), CFS_HASH_DEFAULT, CFS_HASH_MAX_THETA, CFS_HASH_MIN_THETA, class_search_type(), CWARN, D_OTHER, lov_obd::desc, ENTRY, GOTO, HASH_POOLS_BKT_BITS, HASH_POOLS_CUR_BITS, HASH_POOLS_MAX_BITS, INIT_LIST_HEAD, lov_desc::ld_active_tgt_count, obd_device::lov, LOV_DESC_MAGIC, lov_fix_desc(), lov_obd::lov_lock, lov_obd::lov_notify_lock, lov_ost_pool_init(), lov_obd::lov_packed, lov_obd::lov_pool_count, lov_obd::lov_pool_list, lov_obd::lov_pool_proc_entry, lov_obd::lov_pools_hash_body, lov_proc_target_fops, lov_obd::lov_refcount, lov_obd::lov_sp_me, lov_obd::lov_tgt_size, lprocfs_obd_setup(), lprocfs_register(), lustre_cfg_buf(), LUSTRE_CFG_BUFLEN, LUSTRE_LOD_NAME, LUSTRE_SP_CLI, lustre_swab_lov_desc(), obd_device::obd_name, obd_device::obd_proc_entry, obd_device::obd_vars, pool_hash_operations, RETURN, obd_type::typ_procsym, and obd_device::u.
Referenced by lov_device_alloc().
static int lov_statfs (const struct lu_env * env, struct obd_export * exp, struct obd_statfs * osfs, __u64 max_age, __u32 flags) [static]
Definition at line 1055 of file lov_obd.c.
References ENTRY, lov_statfs_async(), obd_info::oi_osfs, ptlrpc_prep_set(), ptlrpc_set_destroy(), ptlrpc_set_wait(), and RETURN.
static int lov_statfs_async (struct obd_export * exp, struct obd_info * oinfo, __u64 max_age, struct ptlrpc_request_set * rqset) [static]
Definition at line 1014 of file lov_obd.c.
References class_exp2obd(), ENTRY, LASSERT, list_empty(), list_entry, list_for_each, obd_device::lov, lov_fini_statfs_set(), lov_prep_statfs_set(), lov_statfs_interpret(), lov_obd::lov_tgts, lov_tgt_desc::ltd_exp, obd_statfs_async(), obd_info::oi_osfs, RETURN, lov_request::rq_idx, lov_request::rq_oi, ptlrpc_request_set::set_arg, ptlrpc_request_set::set_interpret, ptlrpc_request_set::set_requests, and obd_device::u.
Referenced by lov_statfs().
int lov_statfs_interpret (struct ptlrpc_request_set * rqset, void * data, int rc)
Definition at line 1001 of file lov_obd.c.
References ENTRY, lov_fini_statfs_set(), RETURN, and lov_request_set::set_completes.
Referenced by cb_statfs_update(), and lov_statfs_async().
void lov_stripe_lock (struct lov_stripe_md * md)
Definition at line 1366 of file lov_obd.c.
References current_pid, and LASSERT.
Referenced by lov_attr_get_raid0().
void lov_stripe_unlock (struct lov_stripe_md * md)
Definition at line 1375 of file lov_obd.c.
References current_pid, and LASSERT.
Referenced by lov_attr_get_raid0().
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Logical Object Volume")
module_exit (lov_exit)
module_init (lov_init)
MODULE_LICENSE ("GPL")
MODULE_VERSION (LUSTRE_VERSION_STRING)
Variable Documentation
struct obd_ops lov_obd_ops [static]
Initial value:
 {
        .o_owner                = THIS_MODULE,
        .o_setup                = lov_setup,
        .o_cleanup              = lov_cleanup,
        .o_connect              = lov_connect,
        .o_disconnect           = lov_disconnect,
        .o_statfs               = lov_statfs,
        .o_statfs_async         = lov_statfs_async,
        .o_iocontrol            = lov_iocontrol,
        .o_get_info             = lov_get_info,
        .o_set_info_async       = lov_set_info_async,
        .o_notify               = lov_notify,
        .o_pool_new             = lov_pool_new,
        .o_pool_rem             = lov_pool_remove,
        .o_pool_add             = lov_pool_add,
        .o_pool_del             = lov_pool_del,
        .o_getref               = lov_getref,
        .o_putref               = lov_putref,
        .o_quotactl             = lov_quotactl,
}
Definition at line 1442 of file lov_obd.c.
struct kmem_cache* lov_oinfo_slab
Definition at line 1463 of file lov_obd.c.
Referenced by lov_exit(), lov_init(), lsm_alloc_plain(), and lsm_free_plain().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.