Lustre: lustre/lov/lov_internal.h File Reference
lustre/lov/lov_internal.h File Reference
#include <obd_class.h>
#include <lustre/lustre_user.h>
Data Structures
struct lov_stripe_md
struct lsm_operations
struct pool_desc
struct lov_request
struct lov_request_set
Defines
#define LUSTRE_EXT3_STRIPE_MAXBYTES 0x1fffffff000ULL
#define pool_tgt_size(p) ((p)->pool_obds.op_size)
#define pool_tgt_count(p) ((p)->pool_obds.op_count)
#define pool_tgt_array(p) ((p)->pool_obds.op_array)
#define pool_tgt_rw_sem(p) ((p)->pool_obds.op_rw_sem)
#define lov_uuid2str(lv, index) (char *)((lv)->lov_tgts[index]->ltd_uuid.uuid)
Functions
static bool lsm_is_released (struct lov_stripe_md *lsm)
static bool lsm_has_objects (struct lov_stripe_md *lsm)
static struct lsm_operations * lsm_op_find (int magic)
void lov_finish_set (struct lov_request_set *set)
static void lov_put_reqset (struct lov_request_set *set)
int lov_merge_lvb_kms (struct lov_stripe_md *lsm, struct ost_lvb *lvb, __u64 *kms_place)
Merge the lock value block(&lvb) attributes and KMS from each of the stripes in a file into a single lvb.
u64 lov_stripe_size (struct lov_stripe_md *lsm, u64 ost_size, int stripeno)
int lov_stripe_offset (struct lov_stripe_md *lsm, loff_t lov_off, int stripeno, loff_t *obd_off)
loff_t lov_size_to_stripe (struct lov_stripe_md *lsm, u64 file_size, int stripeno)
int lov_stripe_intersects (struct lov_stripe_md *lsm, int stripeno, loff_t start, loff_t end, loff_t *obd_start, loff_t *obd_end)
int lov_stripe_number (struct lov_stripe_md *lsm, loff_t lov_off)
pgoff_t lov_stripe_pgoff (struct lov_stripe_md *lsm, pgoff_t stripe_index, int stripe)
Compute file level page index by stripe level page offset.
void lov_set_add_req (struct lov_request *req, struct lov_request_set *set)
int lov_set_finished (struct lov_request_set *set, int idempotent)
void lov_update_set (struct lov_request_set *set, struct lov_request *req, int rc)
int lov_check_and_wait_active (struct lov_obd *lov, int ost_idx)
int lov_prep_statfs_set (struct obd_device *obd, struct obd_info *oinfo, struct lov_request_set **reqset)
void lov_update_statfs (struct obd_statfs *osfs, struct obd_statfs *lov_sfs, int success)
int lov_fini_statfs (struct obd_device *obd, struct obd_statfs *osfs, int success)
int lov_fini_statfs_set (struct lov_request_set *set)
int lov_statfs_interpret (struct ptlrpc_request_set *rqset, void *data, int rc)
void lov_stripe_lock (struct lov_stripe_md *md)
void lov_stripe_unlock (struct lov_stripe_md *md)
void lov_fix_desc (struct lov_desc *desc)
void lov_fix_desc_stripe_size (__u64 *val)
void lov_fix_desc_stripe_count (__u32 *val)
void lov_fix_desc_pattern (__u32 *val)
void lov_fix_desc_qos_maxage (__u32 *val)
__u16 lov_get_stripecnt (struct lov_obd *lov, __u32 magic, __u16 stripe_count)
int lov_connect_obd (struct obd_device *obd, __u32 index, int activate, struct obd_connect_data *data)
int lov_setup (struct obd_device *obd, struct lustre_cfg *lcfg)
int lov_process_config_base (struct obd_device *obd, struct lustre_cfg *lcfg, __u32 *indexp, int *genp)
int lov_del_target (struct obd_device *obd, __u32 index, struct obd_uuid *uuidp, int gen)
ssize_t lov_lsm_pack (const struct lov_stripe_md *lsm, void *buf, size_t buf_size)
Pack LOV striping metadata for disk storage format (in little endian byte order).
struct lov_stripe_md * lov_unpackmd (struct lov_obd *lov, struct lov_mds_md *lmm, size_t lmm_size)
int lov_free_memmd (struct lov_stripe_md **lsmp)
void lov_dump_lmm_v1 (int level, struct lov_mds_md_v1 *lmm)
void lov_dump_lmm_v3 (int level, struct lov_mds_md_v3 *lmm)
void lov_dump_lmm_common (int level, void *lmmp)
void lov_dump_lmm (int level, void *lmm)
struct lov_stripe_md * lsm_alloc_plain (u16 stripe_count)
void lsm_free_plain (struct lov_stripe_md *lsm)
void dump_lsm (unsigned int level, const struct lov_stripe_md *lsm)
int lov_ost_pool_init (struct ost_pool *op, unsigned int count)
int lov_ost_pool_extend (struct ost_pool *op, unsigned int min_count)
int lov_ost_pool_add (struct ost_pool *op, __u32 idx, unsigned int min_count)
int lov_ost_pool_remove (struct ost_pool *op, __u32 idx)
int lov_ost_pool_free (struct ost_pool *op)
int lov_pool_new (struct obd_device *obd, char *poolname)
int lov_pool_del (struct obd_device *obd, char *poolname)
int lov_pool_add (struct obd_device *obd, char *poolname, char *ostname)
int lov_pool_remove (struct obd_device *obd, char *poolname, char *ostname)
void lov_dump_pool (int level, struct pool_desc *pool)
static struct lov_stripe_md * lsm_addref (struct lov_stripe_md *lsm)
static bool lov_oinfo_is_dummy (const struct lov_oinfo *loi)
static struct obd_device * lov2obd (const struct lov_obd *lov)
Variables
struct lsm_operations lsm_v1_ops
struct lsm_operations lsm_v3_ops
struct kmem_cache * lov_oinfo_slab
struct lu_kmem_descr lov_caches []
struct file_operations lov_proc_target_fops
struct lu_device_type lov_device_type
struct cfs_hash_ops pool_hash_operations
Define Documentation
#define lov_uuid2str (lv, index) (char *)((lv)->lov_tgts[index]->ltd_uuid.uuid)
Definition at line 192 of file lov_internal.h.
Referenced by lov_del_target(), and lov_iocontrol().
#define LUSTRE_EXT3_STRIPE_MAXBYTES 0x1fffffff000ULL
Definition at line 46 of file lov_internal.h.
Referenced by lov_lsm_alloc(), lov_tgt_maxbytes(), and lsm_unpackmd_common().
#define pool_tgt_array (p) ((p)->pool_obds.op_array)
Definition at line 142 of file lov_internal.h.
#define pool_tgt_count (p) ((p)->pool_obds.op_count)
Definition at line 141 of file lov_internal.h.
#define pool_tgt_rw_sem (p) ((p)->pool_obds.op_rw_sem)
Definition at line 143 of file lov_internal.h.
#define pool_tgt_size (p) ((p)->pool_obds.op_size)
Definition at line 140 of file lov_internal.h.
Function Documentation
void dump_lsm (unsigned int level, const struct lov_stripe_md * lsm)
Definition at line 324 of file lov_ea.c.
References CDEBUG, DOSTID, LOV_POOLNAMEF, LPX64, lov_stripe_md::lsm_layout_gen, lov_stripe_md::lsm_magic, lov_stripe_md::lsm_maxbytes, lov_stripe_md::lsm_oi, lov_stripe_md::lsm_pool_name, lov_stripe_md::lsm_refc, lov_stripe_md::lsm_stripe_count, lov_stripe_md::lsm_stripe_size, and POSTID.
Referenced by lov_delete_raid0(), lov_fini_raid0(), lov_fini_released(), and lov_init_raid0().
static struct obd_device* lov2obd (const struct lov_obd * lov) [static, read]
Definition at line 304 of file lov_internal.h.
References obd_device::u.
Referenced by lsm_unpackmd_common().
int lov_check_and_wait_active (struct lov_obd * lov, int ost_idx)
Definition at line 132 of file lov_request.c.
References cfs_time_seconds(), class_exp2cliimp(), GOTO, obd_import::imp_connect_tried, l_wait_event, likely, lov_check_set(), lov_obd::lov_lock, lov_obd::lov_tgts, lov_tgt_desc::ltd_active, lov_tgt_desc::ltd_exp, LWI_TIMEOUT_INTERVAL, obd_timeout, and unlikely.
Referenced by lov_prep_statfs_set().
int lov_connect_obd (struct obd_device * obd, __u32 index, int activate, struct obd_connect_data * data)
Definition at line 122 of file lov_obd.c.
References CDEBUG, CERROR, client_obd::cl_import, client_obd::cl_sp_me, obd_device::cli, D_CONFIG, ENTRY, obd_export::exp_obd, obd_import::imp_invalid, LASSERT, obd_device::lov, lov_obd::lov_sp_me, lov_obd::lov_tgts, lprocfs_add_symlink(), lov_tgt_desc::ltd_exp, lov_tgt_desc::ltd_obd, lov_tgt_desc::ltd_reap, lov_tgt_desc::ltd_uuid, obd_connect(), OBD_CONNECT_INDEX, OBD_DEVICE_MAGIC, obd_device::obd_magic, obd_device::obd_name, obd_device::obd_no_recov, obd_register_observer(), obd_device::obd_set_up, obd_device::obd_type, obd_uuid2str(), obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_index, ptlrpc_activate_import(), RETURN, lov_obd::targets_proc_entry, obd_type::typ_name, and obd_device::u.
Referenced by lov_add_target(), and lov_connect().
int lov_del_target (struct obd_device * obd, __u32 index, struct obd_uuid * uuidp, int gen)
Definition at line 667 of file lov_obd.c.
References CDEBUG, CERROR, D_CONFIG, lov_obd::desc, ENTRY, GOTO, lov_desc::ld_tgt_count, obd_device::lov, lov_obd::lov_death_row, lov_obd::lov_notify_lock, lov_obd::lov_tgts, lov_uuid2str, lov_tgt_desc::ltd_active, lov_tgt_desc::ltd_exp, lov_tgt_desc::ltd_gen, lov_tgt_desc::ltd_reap, lov_tgt_desc::ltd_uuid, obd_getref(), obd_putref(), obd_uuid2str(), obd_uuid_equals(), RETURN, and obd_device::u.
Referenced by lov_add_target(), lov_cleanup(), lov_disconnect(), lov_process_config(), and lov_process_config_base().
void lov_dump_lmm (int level, void * lmm)
Definition at line 107 of file lov_pack.c.
References CDEBUG, le32_to_cpu, lov_dump_lmm_common(), lov_dump_lmm_v1(), lov_dump_lmm_v3(), LOV_MAGIC_V1, LOV_MAGIC_V3, and lov_mds_md.
void lov_dump_lmm_common (int level, void * lmmp)
Definition at line 57 of file lov_pack.c.
References CDEBUG, DOSTID, le16_to_cpu, le32_to_cpu, lmm_oi_le_to_cpu(), lov_mds_md, and POSTID.
Referenced by lov_dump_lmm(), lov_dump_lmm_v1(), lov_dump_lmm_v3(), lsm_lmm_verify_common(), lsm_lmm_verify_v1(), and lsm_lmm_verify_v3().
void lov_dump_lmm_v1 (int level, struct lov_mds_md_v1 * lmm)
Definition at line 92 of file lov_pack.c.
References le16_to_cpu, lov_mds_md_v1::lmm_objects, lov_mds_md_v1::lmm_stripe_count, lov_dump_lmm_common(), and lov_dump_lmm_objects().
Referenced by lov_dump_lmm(), and lsm_unpackmd_common().
void lov_dump_lmm_v3 (int level, struct lov_mds_md_v3 * lmm)
Definition at line 99 of file lov_pack.c.
References CDEBUG, le16_to_cpu, lov_mds_md_v3::lmm_objects, lov_mds_md_v3::lmm_pool_name, lov_mds_md_v3::lmm_stripe_count, lov_dump_lmm_common(), lov_dump_lmm_objects(), and LOV_POOLNAMEF.
Referenced by lov_dump_lmm().
void lov_dump_pool (int level, struct pool_desc * pool)
Definition at line 301 of file lov_pool.c.
References CDEBUG, lov_pool_getref(), lov_pool_putref(), LOV_POOLNAMEF, obd_uuid2str(), ost_pool::op_count, pool_desc::pool_name, pool_desc::pool_obds, pool_tgt, pool_tgt_count, and pool_tgt_rw_sem.
int lov_fini_statfs (struct obd_device * obd, struct obd_statfs * osfs, int success)
Definition at line 178 of file lov_request.c.
References cfs_time_current_64, ENTRY, obd_device::lov, lov_get_stripecnt(), LOV_MAGIC, LOV_U64_MAX, obd_device::obd_osfs, obd_device::obd_osfs_age, obd_device::obd_osfs_lock, obd_statfs::os_ffree, obd_statfs::os_files, RETURN, and obd_device::u.
Referenced by lov_fini_statfs_set().
int lov_fini_statfs_set (struct lov_request_set * set)
Definition at line 200 of file lov_request.c.
References ENTRY, lov_fini_statfs(), lov_put_reqset(), and RETURN.
Referenced by lov_prep_statfs_set(), lov_statfs_async(), and lov_statfs_interpret().
void lov_finish_set (struct lov_request_set * set)
Definition at line 57 of file lov_request.c.
References ENTRY, EXIT, LASSERT, list_del_init(), list_entry, list_for_each_safe, OBD_FREE_PTR, obd_info::oi_osfs, lov_request::rq_link, and lov_request::rq_oi.
Referenced by lov_put_reqset().
void lov_fix_desc (struct lov_desc * desc)
Definition at line 774 of file lov_obd.c.
References lov_desc::ld_default_stripe_count, lov_desc::ld_default_stripe_size, lov_desc::ld_pattern, lov_desc::ld_qos_maxage, lov_fix_desc_pattern(), lov_fix_desc_qos_maxage(), lov_fix_desc_stripe_count(), and lov_fix_desc_stripe_size().
Referenced by lov_setup().
void lov_fix_desc_pattern (__u32 * val)
Definition at line 759 of file lov_obd.c.
References LCONSOLE_WARN, and LOV_PATTERN_RAID0.
Referenced by lov_fix_desc().
void lov_fix_desc_qos_maxage (__u32 * val)
Definition at line 768 of file lov_obd.c.
References LOV_DESC_QOS_MAXAGE_DEFAULT.
Referenced by lov_fix_desc().
void lov_fix_desc_stripe_count (__u32 * val)
Definition at line 753 of file lov_obd.c.
Referenced by lov_fix_desc().
void lov_fix_desc_stripe_size (__u64 * val)
Definition at line 737 of file lov_obd.c.
References LCONSOLE_INFO, LCONSOLE_WARN, LOV_DESC_STRIPE_SIZE_DEFAULT, LOV_MIN_STRIPE_SIZE, and LPU64.
Referenced by lov_fix_desc().
int lov_free_memmd (struct lov_stripe_md ** lsmp)
Definition at line 269 of file lov_pack.c.
References LASSERT, lsm_operations::lsm_free, lov_stripe_md::lsm_magic, lsm_op_find(), and lov_stripe_md::lsm_refc.
Referenced by lov_fini_raid0(), lov_fini_released(), lov_lsm_put(), and lov_unpackmd().
__u16 lov_get_stripecnt (struct lov_obd * lov, __u32 magic, __u16 stripe_count)
Definition at line 184 of file lov_pack.c.
References lov_obd::desc, lov_desc::ld_active_tgt_count, lov_desc::ld_default_stripe_count, LOV_MAX_STRIPE_COUNT_OLD, lov_mds_md_max_stripe_count(), lov_obd::lov_ocd, OBD_CONNECT_MAX_EASIZE, obd_connect_data::ocd_connect_flags, and obd_connect_data::ocd_max_easize.
Referenced by lov_fini_statfs().
ssize_t lov_lsm_pack (const struct lov_stripe_md * lsm, void * buf, size_t buf_size)
Pack LOV striping metadata for disk storage format (in little endian byte order).
This follows the getxattr() conventions. If buf_size is zero then return the size needed. If buf_size is too small then return -ERANGE. Otherwise return the size of the result.
Definition at line 135 of file lov_pack.c.
References CLASSERT, cpu_to_le16, cpu_to_le32, ENTRY, lov_ost_data_v1::l_ost_gen, lov_ost_data_v1::l_ost_idx, lov_ost_data_v1::l_ost_oi, lov_mds_md_v1::lmm_layout_gen, lov_mds_md_v1::lmm_magic, lov_mds_md_v1::lmm_objects, lov_mds_md_v3::lmm_objects, lov_mds_md_v1::lmm_oi, lmm_oi_cpu_to_le(), lov_mds_md_v1::lmm_pattern, lov_mds_md_v3::lmm_pool_name, lov_mds_md_v1::lmm_stripe_count, lov_mds_md_v1::lmm_stripe_size, lov_oinfo::loi_oi, lov_oinfo::loi_ost_gen, lov_oinfo::loi_ost_idx, LOV_MAGIC_V3, lov_mds_md_size(), lov_stripe_md::lsm_layout_gen, lov_stripe_md::lsm_magic, lov_stripe_md::lsm_oi, lov_stripe_md::lsm_oinfo, lov_stripe_md::lsm_pattern, lov_stripe_md::lsm_pool_name, lov_stripe_md::lsm_stripe_count, lov_stripe_md::lsm_stripe_size, ostid_cpu_to_le(), RETURN, and strlcpy().
Referenced by lov_getstripe(), and lov_object_layout_get().
int lov_merge_lvb_kms (struct lov_stripe_md * lsm, struct ost_lvb * lvb, __u64 * kms_place)
Merge the lock value block(&lvb) attributes and KMS from each of the stripes in a file into a single lvb.
It is expected that the caller initializes the current atime, mtime, ctime to avoid regressing a more uptodate time on the local client.
Definition at line 49 of file lov_merge.c.
References CDEBUG, current_pid, D_INODE, DOSTID, LASSERT, lov_oinfo::loi_kms, lov_oinfo::loi_lvb, lov_oinfo::loi_ost_idx, lov_stripe_size(), LPU64, lov_stripe_md::lsm_lock, lov_stripe_md::lsm_lock_owner, lov_stripe_md::lsm_oi, lov_stripe_md::lsm_oinfo, lov_stripe_md::lsm_stripe_count, ost_lvb::lvb_atime, ost_lvb::lvb_blocks, ost_lvb::lvb_ctime, ost_lvb::lvb_mtime, ost_lvb::lvb_size, OST_LVB_GET_ERR, OST_LVB_IS_ERR, POSTID, RETURN, and size.
Referenced by lov_attr_get_raid0().
static bool lov_oinfo_is_dummy (const struct lov_oinfo * loi) [inline, static]
Definition at line 293 of file lov_internal.h.
References lov_oinfo::loi_oi, lov_oinfo::loi_ost_gen, lov_oinfo::loi_ost_idx, ost_id::oi, and unlikely.
Referenced by fiemap_calc_fm_end_offset(), lov_init_raid0(), lov_object_fiemap(), lov_read_and_clear_async_rc(), and lsm_unpackmd_common().
int lov_ost_pool_add (struct ost_pool * op, __u32 idx, unsigned int min_count)
Definition at line 367 of file lov_pool.c.
References ENTRY, EXIT, GOTO, lov_ost_pool_extend(), ost_pool::op_array, ost_pool::op_count, and ost_pool::op_rw_sem.
Referenced by lov_add_target(), and lov_pool_add().
int lov_ost_pool_extend (struct ost_pool * op, unsigned int min_count)
Definition at line 344 of file lov_pool.c.
References LASSERT, max, OBD_ALLOC, OBD_FREE, ost_pool::op_array, ost_pool::op_count, and ost_pool::op_size.
Referenced by lov_ost_pool_add().
int lov_ost_pool_free (struct ost_pool * op)
Definition at line 414 of file lov_pool.c.
References ENTRY, OBD_FREE, ost_pool::op_array, ost_pool::op_count, ost_pool::op_rw_sem, ost_pool::op_size, and RETURN.
Referenced by lov_cleanup(), lov_pool_new(), and lov_pool_putref().
int lov_ost_pool_init (struct ost_pool * op, unsigned int count)
Definition at line 324 of file lov_pool.c.
References ENTRY, EXIT, LOV_POOL_INIT_COUNT, OBD_ALLOC, ost_pool::op_array, ost_pool::op_count, ost_pool::op_rw_sem, ost_pool::op_size, and RETURN.
Referenced by lov_pool_new(), and lov_setup().
int lov_ost_pool_remove (struct ost_pool * op, __u32 idx)
Definition at line 392 of file lov_pool.c.
References ENTRY, EXIT, ost_pool::op_array, ost_pool::op_count, ost_pool::op_rw_sem, and RETURN.
Referenced by lov_pool_remove(), and lov_putref().
int lov_pool_add (struct obd_device * obd, char * poolname, char * ostname)
Definition at line 535 of file lov_pool.c.
References CDEBUG, cfs_hash_lookup(), D_CONFIG, lov_obd::desc, ENTRY, EXIT, GOTO, lov_desc::ld_tgt_count, obd_device::lov, lov_ost_pool_add(), lov_pool_putref(), LOV_POOLNAMEF, lov_obd::lov_pools_hash_body, lov_obd::lov_tgt_size, lov_obd::lov_tgts, lov_tgt_desc::ltd_uuid, obd_getref(), obd_putref(), obd_str2uuid(), obd_uuid_equals(), pool_desc::pool_obds, pool_tgt_count, RETURN, and obd_device::u.
int lov_pool_del (struct obd_device * obd, char * poolname)
Definition at line 504 of file lov_pool.c.
References CDEBUG, cfs_hash_del_key(), D_INFO, ENTRY, list_del_init(), obd_device::lov, lov_obd::lov_pool_count, lov_pool_putref(), lov_obd::lov_pools_hash_body, lprocfs_remove(), obd_device::obd_dev_lock, pool_desc::pool_list, pool_desc::pool_proc_entry, RETURN, and obd_device::u.
Referenced by lov_cleanup().
int lov_pool_new (struct obd_device * obd, char * poolname)
Definition at line 433 of file lov_pool.c.
References CDEBUG, cfs_hash_add_unique(), CWARN, D_CONFIG, D_INFO, ENTRY, GOTO, INIT_HLIST_NODE, list_add_tail(), list_del_init(), obd_device::lov, LOV_MAXPOOLNAME, lov_ost_pool_free(), lov_ost_pool_init(), lov_obd::lov_pool_count, lov_pool_getref(), lov_obd::lov_pool_list, lov_obd::lov_pool_proc_entry, lov_pool_putref(), LOV_POOLNAMEF, lov_obd::lov_pools_hash_body, lprocfs_add_simple(), lprocfs_remove(), OBD_ALLOC_PTR, obd_device::obd_dev_lock, OBD_FREE_PTR, pool_desc::pool_hash, pool_desc::pool_list, pool_desc::pool_lobd, pool_desc::pool_name, pool_desc::pool_obds, pool_desc::pool_proc_entry, pool_desc::pool_refcount, RETURN, strlcpy(), and obd_device::u.
int lov_pool_remove (struct obd_device * obd, char * poolname, char * ostname)
Definition at line 580 of file lov_pool.c.
References CDEBUG, cfs_hash_lookup(), D_CONFIG, lov_obd::desc, ENTRY, EXIT, GOTO, lov_desc::ld_tgt_count, obd_device::lov, lov_ost_pool_remove(), lov_pool_putref(), LOV_POOLNAMEF, lov_obd::lov_pools_hash_body, lov_obd::lov_tgts, lov_tgt_desc::ltd_uuid, obd_getref(), obd_putref(), obd_str2uuid(), obd_uuid_equals(), pool_desc::pool_obds, RETURN, and obd_device::u.
int lov_prep_statfs_set (struct obd_device * obd, struct obd_info * oinfo, struct lov_request_set ** reqset)
Definition at line 337 of file lov_request.c.
References cb_statfs_update(), CDEBUG, D_HA, lov_obd::desc, ENTRY, GOTO, lov_desc::ld_tgt_count, obd_device::lov, lov_check_and_wait_active(), lov_fini_statfs_set(), lov_init_set(), lov_set_add_req(), lov_obd::lov_tgts, lov_tgt_desc::ltd_active, lov_tgt_desc::ltd_exp, OBD_ALLOC, OBD_FREE, OBD_STATFS_NODELAY, obd_info::oi_cb_up, obd_info::oi_flags, obd_info::oi_osfs, RETURN, lov_request::rq_idx, lov_request::rq_oi, and obd_device::u.
Referenced by lov_statfs_async().
int lov_process_config_base (struct obd_device * obd, struct lustre_cfg * lcfg, __u32 * indexp, int * genp)
Definition at line 939 of file lov_obd.c.
References CERROR, class_process_proc_param(), cmd, lov_obd::desc, ENTRY, GOTO, lustre_cfg::lcfg_command, LCFG_LOV_ADD_INA, LCFG_LOV_ADD_OBD, LCFG_LOV_DEL_OBD, LCFG_PARAM, LCFG_POOL_ADD, LCFG_POOL_DEL, LCFG_POOL_NEW, LCFG_POOL_REM, obd_device::lov, lov_add_target(), lov_del_target(), lustre_cfg_buf(), LUSTRE_CFG_BUFLEN, obd_str2uuid(), obd_device::obd_vars, PARAM_LOV, RETURN, obd_device::u, and obd_uuid::uuid.
Referenced by lov_process_config().
static void lov_put_reqset (struct lov_request_set * set) [inline, static]
Definition at line 186 of file lov_internal.h.
References lov_finish_set().
Referenced by lov_fini_statfs_set().
void lov_set_add_req (struct lov_request * req, struct lov_request_set * set)
Definition at line 106 of file lov_request.c.
References list_add_tail(), lov_request::rq_link, and lov_request::rq_rqset.
Referenced by lov_prep_statfs_set().
int lov_set_finished (struct lov_request_set * set, int idempotent)
Definition at line 78 of file lov_request.c.
References CDEBUG, and D_INFO.
Referenced by cb_statfs_update().
int lov_setup (struct obd_device * obd, struct lustre_cfg * lcfg)
Definition at line 782 of file lov_obd.c.
References __swab32, CDEBUG, CERROR, cfs_hash_create(), CFS_HASH_DEFAULT, CFS_HASH_MAX_THETA, CFS_HASH_MIN_THETA, class_search_type(), CWARN, D_OTHER, lov_obd::desc, ENTRY, GOTO, HASH_POOLS_BKT_BITS, HASH_POOLS_CUR_BITS, HASH_POOLS_MAX_BITS, INIT_LIST_HEAD, lov_desc::ld_active_tgt_count, obd_device::lov, LOV_DESC_MAGIC, lov_fix_desc(), lov_obd::lov_lock, lov_obd::lov_notify_lock, lov_ost_pool_init(), lov_obd::lov_packed, lov_obd::lov_pool_count, lov_obd::lov_pool_list, lov_obd::lov_pool_proc_entry, lov_obd::lov_pools_hash_body, lov_proc_target_fops, lov_obd::lov_refcount, lov_obd::lov_sp_me, lov_obd::lov_tgt_size, lprocfs_obd_setup(), lprocfs_register(), lustre_cfg_buf(), LUSTRE_CFG_BUFLEN, LUSTRE_LOD_NAME, LUSTRE_SP_CLI, lustre_swab_lov_desc(), obd_device::obd_name, obd_device::obd_proc_entry, obd_device::obd_vars, pool_hash_operations, RETURN, obd_type::typ_procsym, and obd_device::u.
Referenced by lov_device_alloc().
loff_t lov_size_to_stripe (struct lov_stripe_md * lsm, u64 file_size, int stripeno)
Definition at line 190 of file lov_offset.c.
References LASSERT, lov_stripe_md::lsm_magic, lsm_op_find(), lsm_operations::lsm_stripe_by_index, lov_stripe_md::lsm_stripe_size, and OBD_OBJECT_EOF.
Referenced by lov_io_sub_inherit(), and lov_object_fiemap().
int lov_statfs_interpret (struct ptlrpc_request_set * rqset, void * data, int rc)
Definition at line 1001 of file lov_obd.c.
References ENTRY, lov_fini_statfs_set(), RETURN, and lov_request_set::set_completes.
Referenced by cb_statfs_update(), and lov_statfs_async().
int lov_stripe_intersects (struct lov_stripe_md * lsm, int stripeno, loff_t start, loff_t end, loff_t * obd_start, loff_t * obd_end)
Definition at line 233 of file lov_offset.c.
References CDEBUG, D_INODE, lov_stripe_offset(), and LPD64.
Referenced by fiemap_calc_fm_end_offset(), fiemap_calc_last_stripe(), lov_io_iter_init(), lov_lock_sub_init(), and lov_object_fiemap().
void lov_stripe_lock (struct lov_stripe_md * md)
Definition at line 1366 of file lov_obd.c.
References current_pid, and LASSERT.
Referenced by lov_attr_get_raid0().
int lov_stripe_number (struct lov_stripe_md * lsm, loff_t lov_off)
Definition at line 266 of file lov_offset.c.
References LASSERT, lov_stripe_md::lsm_magic, lsm_op_find(), lsm_operations::lsm_stripe_by_offset, and lov_stripe_md::lsm_stripe_size.
Referenced by lov_io_read_ahead(), lov_object_fiemap(), and lov_page_init_raid0().
int lov_stripe_offset (struct lov_stripe_md * lsm, loff_t lov_off, int stripeno, loff_t * obd_off)
Definition at line 132 of file lov_offset.c.
References LASSERT, lov_stripe_md::lsm_magic, lsm_op_find(), lsm_operations::lsm_stripe_by_index, lov_stripe_md::lsm_stripe_size, OBD_OBJECT_EOF, and ret.
Referenced by lov_io_read_ahead(), lov_page_init_raid0(), and lov_stripe_intersects().
pgoff_t lov_stripe_pgoff (struct lov_stripe_md * lsm, pgoff_t stripe_index, int stripe)
Compute file level page index by stripe level page offset.
Definition at line 74 of file lov_offset.c.
References lov_stripe_size().
Referenced by lov_io_read_ahead().
u64 lov_stripe_size (struct lov_stripe_md * lsm, u64 ost_size, int stripeno)
Definition at line 46 of file lov_offset.c.
References ENTRY, LASSERT, lov_stripe_md::lsm_magic, lsm_op_find(), lsm_operations::lsm_stripe_by_index, lov_stripe_md::lsm_stripe_size, and RETURN.
Referenced by lov_merge_lvb_kms(), lov_object_fiemap(), and lov_stripe_pgoff().
void lov_stripe_unlock (struct lov_stripe_md * md)
Definition at line 1375 of file lov_obd.c.
References current_pid, and LASSERT.
Referenced by lov_attr_get_raid0().
struct lov_stripe_md* lov_unpackmd (struct lov_obd * lov, struct lov_mds_md * lmm, size_t lmm_size) [read]
Definition at line 287 of file lov_pack.c.
References ENTRY, LASSERT, le32_to_cpu, lov_free_memmd(), lov_lsm_alloc(), lov_verify_lmm(), lsm_op_find(), lsm_operations::lsm_unpackmd, and RETURN.
Referenced by lov_conf_set(), and lov_object_init().
void lov_update_set (struct lov_request_set * set, struct lov_request * req, int rc)
Definition at line 93 of file lov_request.c.
References lov_request::rq_complete, and lov_request::rq_rc.
Referenced by cb_statfs_update().
void lov_update_statfs (struct obd_statfs * osfs, struct obd_statfs * lov_sfs, int success)
Definition at line 216 of file lov_request.c.
References __u64, LOV_SUM_MAX, obd_statfs::os_bavail, obd_statfs::os_bfree, obd_statfs::os_blocks, obd_statfs::os_bsize, obd_statfs::os_ffree, obd_statfs::os_files, and quit.
Referenced by cb_statfs_update().
static struct lov_stripe_md* lsm_addref (struct lov_stripe_md * lsm) [static, read]
Definition at line 286 of file lov_internal.h.
References LASSERT, and lov_stripe_md::lsm_refc.
Referenced by lov_init_raid0(), lov_init_released(), and lov_lsm_addref().
struct lov_stripe_md* lsm_alloc_plain (u16 stripe_count) [read]
Definition at line 82 of file lov_ea.c.
References LASSERT, LOV_MAX_STRIPE_COUNT, lov_oinfo_slab, lov_stripe_md::lsm_oinfo, lov_stripe_md::lsm_stripe_count, OBD_ALLOC_LARGE, OBD_FREE_LARGE, OBD_SLAB_ALLOC_PTR_GFP, and OBD_SLAB_FREE.
Referenced by lov_lsm_alloc().
void lsm_free_plain (struct lov_stripe_md * lsm)
Definition at line 117 of file lov_ea.c.
References lov_oinfo_slab, lov_stripe_md::lsm_oinfo, lov_stripe_md::lsm_stripe_count, OBD_FREE_LARGE, and OBD_SLAB_FREE.
static bool lsm_has_objects (struct lov_stripe_md * lsm) [inline, static]
Definition at line 71 of file lov_internal.h.
References lsm_is_released().
static bool lsm_is_released (struct lov_stripe_md * lsm) [inline, static]
Definition at line 66 of file lov_internal.h.
References LOV_PATTERN_F_RELEASED, and lov_stripe_md::lsm_pattern.
Referenced by lov_getstripe(), lov_init_released(), lov_object_fiemap(), lov_type(), lsm_has_objects(), and lsm_unpackmd_common().
static struct lsm_operations* lsm_op_find (int magic) [static, read]
Definition at line 96 of file lov_internal.h.
References CERROR, LOV_MAGIC_V1, LOV_MAGIC_V3, lsm_v1_ops, and lsm_v3_ops.
Referenced by lov_free_memmd(), lov_size_to_stripe(), lov_stripe_number(), lov_stripe_offset(), lov_stripe_size(), lov_unpackmd(), and lov_verify_lmm().
Variable Documentation
struct lu_kmem_descr lov_caches[]
Definition at line 61 of file lov_dev.c.
Referenced by lov_exit(), and lov_init().
struct kmem_cache* lov_oinfo_slab
Definition at line 1463 of file lov_obd.c.
Referenced by lov_exit(), lov_init(), lsm_alloc_plain(), and lsm_free_plain().
struct file_operations lov_proc_target_fops
Referenced by lov_setup().
struct lsm_operations lsm_v1_ops
Definition at line 261 of file lov_ea.c.
Referenced by lsm_op_find().
struct lsm_operations lsm_v3_ops
Definition at line 316 of file lov_ea.c.
Referenced by lsm_op_find().
struct cfs_hash_ops pool_hash_operations
Definition at line 216 of file lod_pool.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.