Lustre: lustre/lov/lov_pack.c File Reference
lustre/lov/lov_pack.c File Reference
#include <lustre/lustre_idl.h>
#include <lustre/lustre_user.h>
#include <lustre_net.h>
#include <lustre_swab.h>
#include <obd.h>
#include <obd_class.h>
#include <obd_support.h>
#include "lov_cl_internal.h"
#include "lov_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LOV
Functions
void lov_dump_lmm_common (int level, void *lmmp)
static void lov_dump_lmm_objects (int level, struct lov_ost_data *lod, int stripe_count)
void lov_dump_lmm_v1 (int level, struct lov_mds_md_v1 *lmm)
void lov_dump_lmm_v3 (int level, struct lov_mds_md_v3 *lmm)
void lov_dump_lmm (int level, void *lmm)
ssize_t lov_lsm_pack (const struct lov_stripe_md *lsm, void *buf, size_t buf_size)
Pack LOV striping metadata for disk storage format (in little endian byte order).
__u16 lov_get_stripecnt (struct lov_obd *lov, __u32 magic, __u16 stripe_count)
static int lov_verify_lmm (void *lmm, int lmm_bytes, __u16 *stripe_count)
struct lov_stripe_md * lov_lsm_alloc (u16 stripe_count, u32 pattern, u32 magic)
int lov_free_memmd (struct lov_stripe_md **lsmp)
struct lov_stripe_md * lov_unpackmd (struct lov_obd *lov, struct lov_mds_md *lmm, size_t lmm_size)
int lov_getstripe (struct lov_object *obj, struct lov_stripe_md *lsm, struct lov_user_md __user *lump)
Define Documentation
#define DEBUG_SUBSYSTEM S_LOV
Definition at line 43 of file lov_pack.c.
Function Documentation
void lov_dump_lmm (int level, void * lmm)
Definition at line 107 of file lov_pack.c.
References CDEBUG, le32_to_cpu, lov_dump_lmm_common(), lov_dump_lmm_v1(), lov_dump_lmm_v3(), LOV_MAGIC_V1, LOV_MAGIC_V3, and lov_mds_md.
void lov_dump_lmm_common (int level, void * lmmp)
Definition at line 57 of file lov_pack.c.
References CDEBUG, DOSTID, le16_to_cpu, le32_to_cpu, lmm_oi_le_to_cpu(), lov_mds_md, and POSTID.
Referenced by lov_dump_lmm(), lov_dump_lmm_v1(), lov_dump_lmm_v3(), lsm_lmm_verify_common(), lsm_lmm_verify_v1(), and lsm_lmm_verify_v3().
static void lov_dump_lmm_objects (int level, struct lov_ost_data * lod, int stripe_count) [static]
Definition at line 72 of file lov_pack.c.
References CDEBUG, DOSTID, le32_to_cpu, LOV_V1_INSANE_STRIPE_COUNT, ostid_le_to_cpu(), and POSTID.
Referenced by lov_dump_lmm_v1(), and lov_dump_lmm_v3().
void lov_dump_lmm_v1 (int level, struct lov_mds_md_v1 * lmm)
Definition at line 92 of file lov_pack.c.
References le16_to_cpu, lov_mds_md_v1::lmm_objects, lov_mds_md_v1::lmm_stripe_count, lov_dump_lmm_common(), and lov_dump_lmm_objects().
Referenced by lov_dump_lmm(), and lsm_unpackmd_common().
void lov_dump_lmm_v3 (int level, struct lov_mds_md_v3 * lmm)
Definition at line 99 of file lov_pack.c.
References CDEBUG, le16_to_cpu, lov_mds_md_v3::lmm_objects, lov_mds_md_v3::lmm_pool_name, lov_mds_md_v3::lmm_stripe_count, lov_dump_lmm_common(), lov_dump_lmm_objects(), and LOV_POOLNAMEF.
Referenced by lov_dump_lmm().
int lov_free_memmd (struct lov_stripe_md ** lsmp)
Definition at line 269 of file lov_pack.c.
References LASSERT, lsm_operations::lsm_free, lov_stripe_md::lsm_magic, lsm_op_find(), and lov_stripe_md::lsm_refc.
Referenced by lov_fini_raid0(), lov_fini_released(), lov_lsm_put(), and lov_unpackmd().
__u16 lov_get_stripecnt (struct lov_obd * lov, __u32 magic, __u16 stripe_count)
Definition at line 184 of file lov_pack.c.
References lov_obd::desc, lov_desc::ld_active_tgt_count, lov_desc::ld_default_stripe_count, LOV_MAX_STRIPE_COUNT_OLD, lov_mds_md_max_stripe_count(), lov_obd::lov_ocd, OBD_CONNECT_MAX_EASIZE, obd_connect_data::ocd_connect_flags, and obd_connect_data::ocd_max_easize.
Referenced by lov_fini_statfs().
struct lov_stripe_md* lov_lsm_alloc (u16 stripe_count, u32 pattern, u32 magic) [read]
Definition at line 236 of file lov_pack.c.
References CDEBUG, CERROR, D_INFO, ENTRY, loi_init(), lov_oinfo::loi_ost_idx, lsm_alloc_plain(), lov_stripe_md::lsm_layout_gen, lov_stripe_md::lsm_lock, lov_stripe_md::lsm_magic, lov_stripe_md::lsm_maxbytes, lov_stripe_md::lsm_oinfo, lov_stripe_md::lsm_pattern, lov_stripe_md::lsm_pool_name, lov_stripe_md::lsm_refc, lov_stripe_md::lsm_stripe_count, LUSTRE_EXT3_STRIPE_MAXBYTES, and RETURN.
Referenced by lov_unpackmd().
ssize_t lov_lsm_pack (const struct lov_stripe_md * lsm, void * buf, size_t buf_size)
Pack LOV striping metadata for disk storage format (in little endian byte order).
This follows the getxattr() conventions. If buf_size is zero then return the size needed. If buf_size is too small then return -ERANGE. Otherwise return the size of the result.
Definition at line 135 of file lov_pack.c.
References CLASSERT, cpu_to_le16, cpu_to_le32, ENTRY, lov_ost_data_v1::l_ost_gen, lov_ost_data_v1::l_ost_idx, lov_ost_data_v1::l_ost_oi, lov_mds_md_v1::lmm_layout_gen, lov_mds_md_v1::lmm_magic, lov_mds_md_v1::lmm_objects, lov_mds_md_v3::lmm_objects, lov_mds_md_v1::lmm_oi, lmm_oi_cpu_to_le(), lov_mds_md_v1::lmm_pattern, lov_mds_md_v3::lmm_pool_name, lov_mds_md_v1::lmm_stripe_count, lov_mds_md_v1::lmm_stripe_size, lov_oinfo::loi_oi, lov_oinfo::loi_ost_gen, lov_oinfo::loi_ost_idx, LOV_MAGIC_V3, lov_mds_md_size(), lov_stripe_md::lsm_layout_gen, lov_stripe_md::lsm_magic, lov_stripe_md::lsm_oi, lov_stripe_md::lsm_oinfo, lov_stripe_md::lsm_pattern, lov_stripe_md::lsm_pool_name, lov_stripe_md::lsm_stripe_count, lov_stripe_md::lsm_stripe_size, ostid_cpu_to_le(), RETURN, and strlcpy().
Referenced by lov_getstripe(), and lov_object_layout_get().
struct lov_stripe_md* lov_unpackmd (struct lov_obd * lov, struct lov_mds_md * lmm, size_t lmm_size) [read]
Definition at line 287 of file lov_pack.c.
References ENTRY, LASSERT, le32_to_cpu, lov_free_memmd(), lov_lsm_alloc(), lov_verify_lmm(), lsm_op_find(), lsm_operations::lsm_unpackmd, and RETURN.
Referenced by lov_conf_set(), and lov_object_init().
static int lov_verify_lmm (void * lmm, int lmm_bytes, __u16 * stripe_count) [static]
Definition at line 208 of file lov_pack.c.
References CERROR, le32_to_cpu, lsm_operations::lsm_lmm_verify, lsm_op_find(), OBD_ALLOC_LARGE, and OBD_FREE_LARGE.
Referenced by lov_unpackmd().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.