Lustre: lustre/lov/lov_request.c File Reference
lustre/lov/lov_request.c File Reference
#include <libcfs/libcfs.h>
#include <obd_class.h>
#include <lustre/lustre_idl.h>
#include "lov_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LOV
#define LOV_U64_MAX ((__u64)~0ULL)
#define LOV_SUM_MAX(tot, add)
Functions
static void lov_init_set (struct lov_request_set *set)
void lov_finish_set (struct lov_request_set *set)
int lov_set_finished (struct lov_request_set *set, int idempotent)
void lov_update_set (struct lov_request_set *set, struct lov_request *req, int rc)
void lov_set_add_req (struct lov_request *req, struct lov_request_set *set)
static int lov_check_set (struct lov_obd *lov, int idx)
int lov_check_and_wait_active (struct lov_obd *lov, int ost_idx)
int lov_fini_statfs (struct obd_device *obd, struct obd_statfs *osfs, int success)
int lov_fini_statfs_set (struct lov_request_set *set)
void lov_update_statfs (struct obd_statfs *osfs, struct obd_statfs *lov_sfs, int success)
static int cb_statfs_update (void *cookie, int rc)
int lov_prep_statfs_set (struct obd_device *obd, struct obd_info *oinfo, struct lov_request_set **reqset)
Define Documentation
#define DEBUG_SUBSYSTEM S_LOV
Definition at line 37 of file lov_request.c.
#define LOV_SUM_MAX (tot, add)
Value:
do {                                                            \
                if ((tot) + (add) < (tot))                              \
                        (tot) = LOV_U64_MAX;                            \
                else                                                    \
                        (tot) += (add);                                 \
        } while(0)
Definition at line 170 of file lov_request.c.
Referenced by lov_update_statfs().
#define LOV_U64_MAX ((__u64)~0ULL)
Definition at line 169 of file lov_request.c.
Referenced by lov_fini_statfs().
Function Documentation
static int cb_statfs_update (void * cookie, int rc) [static]
Definition at line 286 of file lov_request.c.
References cfs_time_current_64, class_exp2obd(), ENTRY, GOTO, obd_device::lov, lov_set_finished(), lov_statfs_interpret(), lov_obd::lov_tgts, lov_update_set(), lov_update_statfs(), lov_tgt_desc::ltd_active, lov_tgt_desc::ltd_exp, obd_getref(), obd_device::obd_osfs, obd_device::obd_osfs_age, obd_device::obd_osfs_lock, obd_putref(), OBD_STATFS_FROM_CACHE, OBD_STATFS_PTLRPCD, obd_info::oi_flags, obd_info::oi_osfs, RETURN, lov_request::rq_idx, lov_request::rq_rqset, and obd_device::u.
Referenced by lov_prep_statfs_set().
int lov_check_and_wait_active (struct lov_obd * lov, int ost_idx)
Definition at line 132 of file lov_request.c.
References cfs_time_seconds(), class_exp2cliimp(), GOTO, obd_import::imp_connect_tried, l_wait_event, likely, lov_check_set(), lov_obd::lov_lock, lov_obd::lov_tgts, lov_tgt_desc::ltd_active, lov_tgt_desc::ltd_exp, LWI_TIMEOUT_INTERVAL, obd_timeout, and unlikely.
Referenced by lov_prep_statfs_set().
static int lov_check_set (struct lov_obd * lov, int idx) [static]
Definition at line 113 of file lov_request.c.
References class_exp2cliimp(), obd_import::imp_connect_tried, lov_obd::lov_lock, lov_obd::lov_tgts, lov_tgt_desc::ltd_active, and lov_tgt_desc::ltd_exp.
Referenced by lov_check_and_wait_active().
int lov_fini_statfs (struct obd_device * obd, struct obd_statfs * osfs, int success)
Definition at line 178 of file lov_request.c.
References cfs_time_current_64, ENTRY, obd_device::lov, lov_get_stripecnt(), LOV_MAGIC, LOV_U64_MAX, obd_device::obd_osfs, obd_device::obd_osfs_age, obd_device::obd_osfs_lock, obd_statfs::os_ffree, obd_statfs::os_files, RETURN, and obd_device::u.
Referenced by lov_fini_statfs_set().
int lov_fini_statfs_set (struct lov_request_set * set)
Definition at line 200 of file lov_request.c.
References ENTRY, lov_fini_statfs(), lov_put_reqset(), and RETURN.
Referenced by lov_prep_statfs_set(), lov_statfs_async(), and lov_statfs_interpret().
void lov_finish_set (struct lov_request_set * set)
Definition at line 57 of file lov_request.c.
References ENTRY, EXIT, LASSERT, list_del_init(), list_entry, list_for_each_safe, OBD_FREE_PTR, obd_info::oi_osfs, lov_request::rq_link, and lov_request::rq_oi.
Referenced by lov_put_reqset().
static void lov_init_set (struct lov_request_set * set) [static]
Definition at line 46 of file lov_request.c.
References INIT_LIST_HEAD.
Referenced by lov_prep_statfs_set().
int lov_prep_statfs_set (struct obd_device * obd, struct obd_info * oinfo, struct lov_request_set ** reqset)
Definition at line 337 of file lov_request.c.
References cb_statfs_update(), CDEBUG, D_HA, lov_obd::desc, ENTRY, GOTO, lov_desc::ld_tgt_count, obd_device::lov, lov_check_and_wait_active(), lov_fini_statfs_set(), lov_init_set(), lov_set_add_req(), lov_obd::lov_tgts, lov_tgt_desc::ltd_active, lov_tgt_desc::ltd_exp, OBD_ALLOC, OBD_FREE, OBD_STATFS_NODELAY, obd_info::oi_cb_up, obd_info::oi_flags, obd_info::oi_osfs, RETURN, lov_request::rq_idx, lov_request::rq_oi, and obd_device::u.
Referenced by lov_statfs_async().
void lov_set_add_req (struct lov_request * req, struct lov_request_set * set)
Definition at line 106 of file lov_request.c.
References list_add_tail(), lov_request::rq_link, and lov_request::rq_rqset.
Referenced by lov_prep_statfs_set().
int lov_set_finished (struct lov_request_set * set, int idempotent)
Definition at line 78 of file lov_request.c.
References CDEBUG, and D_INFO.
Referenced by cb_statfs_update().
void lov_update_set (struct lov_request_set * set, struct lov_request * req, int rc)
Definition at line 93 of file lov_request.c.
References lov_request::rq_complete, and lov_request::rq_rc.
Referenced by cb_statfs_update().
void lov_update_statfs (struct obd_statfs * osfs, struct obd_statfs * lov_sfs, int success)
Definition at line 216 of file lov_request.c.
References __u64, LOV_SUM_MAX, obd_statfs::os_bavail, obd_statfs::os_bfree, obd_statfs::os_blocks, obd_statfs::os_bsize, obd_statfs::os_ffree, obd_statfs::os_files, and quit.
Referenced by cb_statfs_update().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.