Lustre: lustre/lov/lov_offset.c File Reference
lustre/lov/lov_offset.c File Reference
#include <libcfs/libcfs.h>
#include <obd_class.h>
#include "lov_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LOV
Functions
u64 lov_stripe_size (struct lov_stripe_md *lsm, u64 ost_size, int stripeno)
pgoff_t lov_stripe_pgoff (struct lov_stripe_md *lsm, pgoff_t stripe_index, int stripe)
Compute file level page index by stripe level page offset.
int lov_stripe_offset (struct lov_stripe_md *lsm, loff_t lov_off, int stripeno, loff_t *obdoff)
loff_t lov_size_to_stripe (struct lov_stripe_md *lsm, u64 file_size, int stripeno)
int lov_stripe_intersects (struct lov_stripe_md *lsm, int stripeno, loff_t start, loff_t end, loff_t *obd_start, loff_t *obd_end)
int lov_stripe_number (struct lov_stripe_md *lsm, loff_t lov_off)
Define Documentation
#define DEBUG_SUBSYSTEM S_LOV
Definition at line 37 of file lov_offset.c.
Function Documentation
loff_t lov_size_to_stripe (struct lov_stripe_md * lsm, u64 file_size, int stripeno)
Definition at line 190 of file lov_offset.c.
References LASSERT, lov_stripe_md::lsm_magic, lsm_op_find(), lsm_operations::lsm_stripe_by_index, lov_stripe_md::lsm_stripe_size, and OBD_OBJECT_EOF.
Referenced by lov_io_sub_inherit(), and lov_object_fiemap().
int lov_stripe_intersects (struct lov_stripe_md * lsm, int stripeno, loff_t start, loff_t end, loff_t * obd_start, loff_t * obd_end)
Definition at line 233 of file lov_offset.c.
References CDEBUG, D_INODE, lov_stripe_offset(), and LPD64.
Referenced by fiemap_calc_fm_end_offset(), fiemap_calc_last_stripe(), lov_io_iter_init(), lov_lock_sub_init(), and lov_object_fiemap().
int lov_stripe_number (struct lov_stripe_md * lsm, loff_t lov_off)
Definition at line 266 of file lov_offset.c.
References LASSERT, lov_stripe_md::lsm_magic, lsm_op_find(), lsm_operations::lsm_stripe_by_offset, and lov_stripe_md::lsm_stripe_size.
Referenced by lov_io_read_ahead(), lov_object_fiemap(), and lov_page_init_raid0().
int lov_stripe_offset (struct lov_stripe_md * lsm, loff_t lov_off, int stripeno, loff_t * obdoff)
Definition at line 132 of file lov_offset.c.
References LASSERT, lov_stripe_md::lsm_magic, lsm_op_find(), lsm_operations::lsm_stripe_by_index, lov_stripe_md::lsm_stripe_size, OBD_OBJECT_EOF, and ret.
Referenced by lov_io_read_ahead(), lov_page_init_raid0(), and lov_stripe_intersects().
pgoff_t lov_stripe_pgoff (struct lov_stripe_md * lsm, pgoff_t stripe_index, int stripe)
Compute file level page index by stripe level page offset.
Definition at line 74 of file lov_offset.c.
References lov_stripe_size().
Referenced by lov_io_read_ahead().
u64 lov_stripe_size (struct lov_stripe_md * lsm, u64 ost_size, int stripeno)
Definition at line 46 of file lov_offset.c.
References ENTRY, LASSERT, lov_stripe_md::lsm_magic, lsm_op_find(), lsm_operations::lsm_stripe_by_index, lov_stripe_md::lsm_stripe_size, and RETURN.
Referenced by lov_merge_lvb_kms(), lov_object_fiemap(), and lov_stripe_pgoff().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.