Lustre: lustre/lov/lov_dev.c File Reference
lustre/lov/lov_dev.c File Reference
#include <obd_class.h>
#include "lov_cl_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LOV
Functions
static void * lov_key_init (const struct lu_context *ctx, struct lu_context_key *key)
static void lov_key_fini (const struct lu_context *ctx, struct lu_context_key *key, void *data)
static void * lov_session_key_init (const struct lu_context *ctx, struct lu_context_key *key)
static void lov_session_key_fini (const struct lu_context *ctx, struct lu_context_key *key, void *data)
LU_TYPE_INIT_FINI (lov,&lov_key,&lov_session_key)
static struct lu_device * lov_device_fini (const struct lu_env *env, struct lu_device *d)
static int lov_device_init (const struct lu_env *env, struct lu_device *d, const char *name, struct lu_device *next)
static void lov_emerg_free (struct lov_device_emerg **emrg, int nr)
static struct lu_device * lov_device_free (const struct lu_env *env, struct lu_device *d)
static void lov_cl_del_target (const struct lu_env *env, struct lu_device *dev, __u32 index)
static struct lov_device_emerg ** lov_emerg_alloc (int nr)
static int lov_expand_targets (const struct lu_env *env, struct lov_device *dev)
static int lov_cl_add_target (const struct lu_env *env, struct lu_device *dev, __u32 index)
static int lov_process_config (const struct lu_env *env, struct lu_device *d, struct lustre_cfg *cfg)
static struct lu_device * lov_device_alloc (const struct lu_env *env, struct lu_device_type *t, struct lustre_cfg *cfg)
Variables
struct kmem_cache * lov_lock_kmem
struct kmem_cache * lov_object_kmem
struct kmem_cache * lov_thread_kmem
struct kmem_cache * lov_session_kmem
struct kmem_cache * lovsub_lock_kmem
struct kmem_cache * lovsub_object_kmem
struct kmem_cache * lov_lock_link_kmem
static struct lock_class_key cl_lov_device_mutex_class
Lock class of lov_device::ld_mutex.
struct lu_kmem_descr lov_caches []
struct lu_context_key lov_key
struct lu_context_key lov_session_key
static struct lu_device_operations lov_lu_ops
static struct
lu_device_type_operations lov_device_type_ops
struct lu_device_type lov_device_type
Define Documentation
#define DEBUG_SUBSYSTEM S_LOV
Definition at line 41 of file lov_dev.c.
Function Documentation
static int lov_cl_add_target (const struct lu_env * env, struct lu_device * dev, __u32 index) [static]
Definition at line 342 of file lov_dev.c.
References lovsub_device::acid_idx, lovsub_device::acid_super, CERROR, cl2lovsub_dev(), cl_type_setup(), ENTRY, LASSERT, lov_device::ld_flags, lu_device::ld_obd, lu_device::ld_site, lov_device::ld_target, obd_device::lov, lov_cl_del_target(), LOV_DEV_INITIALIZED, lov_expand_targets(), lov_obd::lov_tgts, lovsub_device_type, lov_tgt_desc::ltd_obd, lov_tgt_desc::ltd_uuid, lu2lov_dev(), obd_getref(), obd_device::obd_lu_dev, obd_putref(), obd_device::obd_set_up, obd_uuid2str(), RETURN, and obd_device::u.
Referenced by lov_process_config().
static void lov_cl_del_target (const struct lu_env * env, struct lu_device * dev, __u32 index) [static]
Definition at line 254 of file lov_dev.c.
References cl_stack_fini(), ENTRY, EXIT, lov_device::ld_target, lovsub2cl_dev(), and lu2lov_dev().
Referenced by lov_cl_add_target(), and lov_process_config().
static struct lu_device* lov_device_alloc (const struct lu_env * env, struct lu_device_type * t, struct lustre_cfg * cfg) [static, read]
Definition at line 421 of file lov_dev.c.
References cl_device_init(), cl_lov_device_mutex_class, class_name2obd(), LASSERT, lov_device::ld_cl, lov_device::ld_lov, lov_device::ld_mutex, lu_device::ld_ops, obd_device::lov, lov2lu_dev(), lov_device_free(), lov_lu_ops, lov_setup(), lustre_cfg_string(), OBD_ALLOC_PTR, RETURN, and obd_device::u.
static struct lu_device* lov_device_fini (const struct lu_env * env, struct lu_device * d) [static, read]
Definition at line 159 of file lov_dev.c.
References cl_stack_fini(), LASSERT, lov_device::ld_lov, lov_device::ld_target, lov_foreach_target, lovsub2cl_dev(), lu2lov_dev(), and RETURN.
Referenced by lov_device_init().
static struct lu_device* lov_device_free (const struct lu_env * env, struct lu_device * d) [static, read]
Definition at line 239 of file lov_dev.c.
References cl_device_fini(), lov_device::ld_emrg, lov_device::ld_target, lov_device::ld_target_nr, lov_emerg_free(), lu2cl_dev(), lu2lov_dev(), OBD_FREE, and OBD_FREE_PTR.
Referenced by lov_device_alloc().
static int lov_device_init (const struct lu_env * env, struct lu_device * d, const char * name, struct lu_device * next) [static]
Definition at line 181 of file lov_dev.c.
References lovsub_device::acid_idx, lovsub_device::acid_super, cl2lovsub_dev(), cl_type_setup(), LASSERT, lov_device::ld_flags, lov_device::ld_lov, lu_device::ld_site, lov_device::ld_target, LOV_DEV_INITIALIZED, lov_device_fini(), lov_foreach_target, lov_obd::lov_tgts, lovsub_device_type, lov_tgt_desc::ltd_obd, lu2lov_dev(), obd_device::obd_lu_dev, and RETURN.
static struct lov_device_emerg** lov_emerg_alloc (int nr) [static, read]
Definition at line 267 of file lov_dev.c.
References cl_env_alloc(), cl_page_list_init(), lov_device_emerg::emrg_env, lov_device_emerg::emrg_page_list, lov_device_emerg::emrg_refcheck, lu_context::lc_cookie, LCT_NOREF, LCT_REMEMBER, lu_env::le_ctx, lov_emerg_free(), OBD_ALLOC, and OBD_ALLOC_PTR.
Referenced by lov_expand_targets().
static void lov_emerg_free (struct lov_device_emerg ** emrg, int nr) [static]
Definition at line 221 of file lov_dev.c.
References cl_env_put(), lov_device_emerg::emrg_env, lov_device_emerg::emrg_page_list, lov_device_emerg::emrg_refcheck, LASSERT, OBD_FREE, OBD_FREE_PTR, and cl_page_list::pl_nr.
Referenced by lov_device_free(), lov_emerg_alloc(), and lov_expand_targets().
static int lov_expand_targets (const struct lu_env * env, struct lov_device * dev) [static]
Definition at line 301 of file lov_dev.c.
References ENTRY, lov_device::ld_emrg, lov_device::ld_lov, lov_device::ld_mutex, lov_device::ld_target, lov_device::ld_target_nr, lov_emerg_alloc(), lov_emerg_free(), lov_obd::lov_tgt_size, OBD_ALLOC, OBD_FREE, and RETURN.
Referenced by lov_cl_add_target().
static void lov_key_fini (const struct lu_context * ctx, struct lu_context_key * key, void * data) [static]
Definition at line 119 of file lov_dev.c.
References lov_thread_kmem, and OBD_SLAB_FREE_PTR.
static void* lov_key_init (const struct lu_context * ctx, struct lu_context_key * key) [static]
Definition at line 108 of file lov_dev.c.
References lov_thread_kmem, and OBD_SLAB_ALLOC_PTR_GFP.
static int lov_process_config (const struct lu_env * env, struct lu_device * d, struct lustre_cfg * cfg) [static]
Definition at line 386 of file lov_dev.c.
References cmd, lustre_cfg::lcfg_command, LCFG_LOV_ADD_INA, LCFG_LOV_ADD_OBD, LCFG_LOV_DEL_OBD, lu_device::ld_obd, lov_cl_add_target(), lov_cl_del_target(), lov_del_target(), lov_process_config_base(), obd_getref(), obd_putref(), and RETURN.
static void lov_session_key_fini (const struct lu_context * ctx, struct lu_context_key * key, void * data) [static]
Definition at line 143 of file lov_dev.c.
References lov_session_kmem, and OBD_SLAB_FREE_PTR.
static void* lov_session_key_init (const struct lu_context * ctx, struct lu_context_key * key) [static]
Definition at line 132 of file lov_dev.c.
References lov_session_kmem, and OBD_SLAB_ALLOC_PTR_GFP.
LU_TYPE_INIT_FINI (lov , & lov_key, & lov_session_key)
Variable Documentation
struct lock_class_key cl_lov_device_mutex_class [static]
Lock class of lov_device::ld_mutex.
Definition at line 59 of file lov_dev.c.
Referenced by lov_device_alloc().
struct lu_kmem_descr lov_caches[]
Definition at line 61 of file lov_dev.c.
Referenced by lov_exit(), and lov_init().
struct lu_device_type_operations lov_device_type_ops [static]
Initial value:
 {
        .ldto_init = lov_type_init,
        .ldto_fini = lov_type_fini,
        .ldto_start = lov_type_start,
        .ldto_stop  = lov_type_stop,
        .ldto_device_alloc = lov_device_alloc,
        .ldto_device_free  = lov_device_free,
        .ldto_device_init    = lov_device_init,
        .ldto_device_fini    = lov_device_fini
}
Definition at line 454 of file lov_dev.c.
struct lu_device_operations lov_lu_ops [static]
Initial value:
 {
        .ldo_object_alloc      = lov_object_alloc,
        .ldo_process_config    = lov_process_config,
}
Definition at line 416 of file lov_dev.c.
Referenced by lov_device_alloc().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.