Lustre: lustre/tests/lp_utils.c File Reference
lustre/tests/lp_utils.c File Reference
#include <mpi.h>
#include <stdio.h>
#include <string.h>
#include <time.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <sys/ioctl.h>
#include <fcntl.h>
#include <errno.h>
#include "lustre/lustre_user.h"
#include "lustre/tests/lp_utils.h"
Defines
#define MAX_PROCESSES 8
Functions
char * timestamp ()
void begin (char *str)
void end (char *str)
void dump_diff (char *orig_buf, char *buf, int size, long _off)
void lp_gethostname (void)
void remove_file_or_dir (char *name)
void create_file (char *name, long filesize, int fill)
void check_stat (char *filename, struct stat *state, struct stat *old_state)
void remove_file (char *name)
void fill_stride (char *buf, int buf_size, long long rank, long long _off)
Variables
int verbose = 0
int debug = 0
char hostname [1024]
struct timeval t1 t2
Define Documentation
#define MAX_PROCESSES 8
Definition at line 55 of file lp_utils.c.
Function Documentation
void begin (char * str) [inline]
Definition at line 75 of file lp_utils.c.
void check_stat (char * filename, struct stat * state, struct stat * old_state)
Definition at line 236 of file lp_utils.c.
void create_file (char * name, long filesize, int fill)
Definition at line 181 of file lp_utils.c.
void dump_diff (char * orig_buf, char * buf, int size, long _off)
Definition at line 103 of file lp_utils.c.
Referenced by rw_file().
void end (char * str) [inline]
Definition at line 83 of file lp_utils.c.
void fill_stride (char * buf, int buf_size, long long rank, long long _off)
Definition at line 267 of file lp_utils.c.
Referenced by rw_file().
void lp_gethostname (void)
Definition at line 146 of file lp_utils.c.
Referenced by main().
void remove_file (char * name)
Definition at line 252 of file lp_utils.c.
Referenced by cascading_rw().
void remove_file_or_dir (char * name)
Definition at line 158 of file lp_utils.c.
Referenced by create_file(), and rw_file().
char* timestamp ()
Definition at line 64 of file lp_utils.c.
Referenced by begin(), end(), kgnilnd_check_fma_rx(), kgnilnd_rdma(), kgnilnd_release_msg(), kgnilnd_sendmsg(), kgnilnd_sendmsg_trylock(), main(), and timestamp().
Variable Documentation
int debug = 0
Definition at line 58 of file lp_utils.c.
char hostname[1024]
Definition at line 60 of file lp_utils.c.
Referenced by lp_gethostname(), main(), process_args(), and rprintf().
struct timeval t1 t2
Definition at line 62 of file lp_utils.c.
Referenced by end(), lnet_match_networks(), and main().
int verbose = 0
Definition at line 57 of file lp_utils.c.
Referenced by begin(), dir_read(), dir_write(), end(), fatal(), get_verbose(), jt_lst_list_batch(), jt_lst_list_group(), jt_lst_query_batch(), ldiskfs_make_lustre(), lr_parse_line(), lr_print_status(), lr_replicate(), main(), parse_opts(), process_args(), read_chunks(), run_command(), set_blockdev_scheduler(), set_blockdev_tunables(), show_rate(), sizeof_dev(), and write_chunks().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.