Lustre: lustre/ptlrpc/gss/lproc_gss.c File Reference
lustre/ptlrpc/gss/lproc_gss.c File Reference
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/dcache.h>
#include <linux/fs.h>
#include <linux/mutex.h>
#include <obd.h>
#include <obd_class.h>
#include <obd_support.h>
#include <lustre/lustre_idl.h>
#include <lustre_net.h>
#include <lustre_import.h>
#include <lprocfs_status.h>
#include <lustre_sec.h>
#include "gss_err.h"
#include "gss_internal.h"
#include "gss_api.h"
Defines
#define DEBUG_SUBSYSTEM S_SEC
Functions
void gss_stat_oos_record_cli (int behind)
void gss_stat_oos_record_svc (int phase, int replay)
static int gss_proc_oos_seq_show (struct seq_file *m, void *v)
LPROC_SEQ_FOPS_RO (gss_proc_oos)
static ssize_t gss_proc_write_secinit (struct file *file, const char *buffer, size_t count, loff_t *off)
static int gss_lk_proc_dl_seq_show (struct seq_file *m, void *v)
static ssize_t gss_lk_proc_dl_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
LPROC_SEQ_FOPS (gss_lk_proc_dl)
void gss_exit_lproc (void)
int gss_init_lproc (void)
Variables
static struct proc_dir_entry * gss_proc_root = NULL
static struct proc_dir_entry * gss_proc_lk = NULL
struct {
spinlock_t oos_lock
atomic_t oos_cli_count
int oos_cli_behind
atomic_t oos_svc_replay [3]
atomic_t oos_svc_pass [3]
} gss_stat_oos
static struct file_operations gss_proc_secinit
static struct lprocfs_vars gss_lprocfs_vars []
static int gss_lk_debug_level = 1
static struct lprocfs_vars gss_lk_lprocfs_vars []
Define Documentation
#define DEBUG_SUBSYSTEM S_SEC
Definition at line 37 of file lproc_gss.c.
Function Documentation
void gss_exit_lproc (void)
Definition at line 188 of file lproc_gss.c.
References gss_proc_lk, gss_proc_root, and lprocfs_remove().
Referenced by gss_init_lproc(), sptlrpc_gss_exit(), and sptlrpc_gss_init().
int gss_init_lproc (void)
Definition at line 201 of file lproc_gss.c.
References CERROR, GOTO, gss_exit_lproc(), gss_proc_lk, gss_proc_root, gss_stat_oos, lprocfs_register(), and sptlrpc_proc_root.
Referenced by sptlrpc_gss_init().
static int gss_lk_proc_dl_seq_show (struct seq_file * m, void * v) [static]
Definition at line 156 of file lproc_gss.c.
References gss_lk_debug_level.
static ssize_t gss_lk_proc_dl_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Definition at line 163 of file lproc_gss.c.
References gss_lk_debug_level.
static int gss_proc_oos_seq_show (struct seq_file * m, void * v) [static]
Definition at line 97 of file lproc_gss.c.
References GSS_SEQ_WIN_BACK, GSS_SEQ_WIN_MAIN, and gss_stat_oos.
static ssize_t gss_proc_write_secinit (struct file * file, const char * buffer, size_t count, loff_t * off) [static]
Definition at line 123 of file lproc_gss.c.
References gss_do_ctx_init_rpc(), and LASSERT.
void gss_stat_oos_record_cli (int behind)
Definition at line 77 of file lproc_gss.c.
References gss_stat_oos.
Referenced by gss_cli_ctx_seal(), and gss_cli_ctx_sign().
void gss_stat_oos_record_svc (int phase, int replay)
Definition at line 87 of file lproc_gss.c.
References gss_stat_oos, and LASSERT.
Referenced by gss_check_seq_num().
LPROC_SEQ_FOPS (gss_lk_proc_dl)
LPROC_SEQ_FOPS_RO (gss_proc_oos)
Variable Documentation
int gss_lk_debug_level = 1 [static]
Definition at line 154 of file lproc_gss.c.
Referenced by gss_lk_proc_dl_seq_show(), and gss_lk_proc_dl_seq_write().
struct lprocfs_vars gss_lk_lprocfs_vars[] [static]
Initial value:
 {
        { .name =       "debug_level",
          .fops =       &gss_lk_proc_dl_fops    },
        { NULL }
}
Definition at line 182 of file lproc_gss.c.
struct lprocfs_vars gss_lprocfs_vars[] [static]
Initial value:
 {
        { .name =       "replays",
          .fops =       &gss_proc_oos_fops      },
        { .name =       "init_channel",
          .fops =       &gss_proc_secinit,
          .proc_mode =  0222                    },
        { NULL }
}
Definition at line 140 of file lproc_gss.c.
struct proc_dir_entry* gss_proc_lk = NULL [static]
Definition at line 59 of file lproc_gss.c.
Referenced by gss_exit_lproc(), and gss_init_lproc().
struct proc_dir_entry* gss_proc_root = NULL [static]
Definition at line 58 of file lproc_gss.c.
Referenced by gss_exit_lproc(), and gss_init_lproc().
struct file_operations gss_proc_secinit [static]
Initial value:
 {
        .write = gss_proc_write_secinit,
}
Definition at line 136 of file lproc_gss.c.
struct { ... } gss_stat_oos [static]
Referenced by gss_init_lproc(), gss_proc_oos_seq_show(), gss_stat_oos_record_cli(), and gss_stat_oos_record_svc().
int oos_cli_behind
Definition at line 67 of file lproc_gss.c.
atomic_t oos_cli_count
Definition at line 66 of file lproc_gss.c.
spinlock_t oos_lock
Definition at line 65 of file lproc_gss.c.
atomic_t oos_svc_pass[3]
Definition at line 69 of file lproc_gss.c.
atomic_t oos_svc_replay[3]
Definition at line 68 of file lproc_gss.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.