Lustre: lustre/include/lprocfs_status.h File Reference
lustre/include/lprocfs_status.h File Reference
#include <linux/fs.h>
#include <linux/proc_fs.h>
#include <linux/rwsem.h>
#include <linux/spinlock.h>
#include <linux/seq_file.h>
#include <lustre/lustre_idl.h>
Data Structures
struct lprocfs_vars
struct obd_histogram
struct brw_stats
struct rename_stats
struct lprocfs_counter_header
struct lprocfs_counter
struct lprocfs_percpu
struct lprocfs_stats
struct dhms
struct obd_job_stats
Defines
#define OBD_HIST_MAX 32
#define LC_MIN_INIT ((~(__u64)0) >> 1)
#define lc_sum lc_array_sum[0]
#define lc_sum_irq lc_array_sum[1]
#define OPC_RANGE(seg) (seg ## _LAST_OPC - seg ## _FIRST_OPC)
#define LUSTRE_MAX_OPCODES
#define EXTRA_MAX_OPCODES
#define PTLRPC_FIRST_CNTR PTLRPC_REQWAIT_CNTR
#define EXTRA_FIRST_OPC LDLM_GLIMPSE_ENQUEUE
#define DHMS_FMT "%dd%dh%02dm%02ds"
#define DHMS_VARS(x) (x)->d, (x)->h, (x)->m, (x)->s
#define JOBSTATS_JOBID_VAR_MAX_LEN 20
#define JOBSTATS_DISABLE "disable"
#define JOBSTATS_PROCNAME_UID "procname_uid"
#define JOBSTATS_NODELOCAL "nodelocal"
#define proc_lustre_root NULL
#define LPROC_SEQ_FOPS_RO(name)
#define LPROC_SEQ_FOPS(name)
#define LPROC_SEQ_FOPS_RO_TYPE(name, type)
#define LPROC_SEQ_FOPS_RW_TYPE(name, type)
#define LPROC_SEQ_FOPS_WO_TYPE(name, type)
#define target_print_req NULL
Typedefs
typedef void(* cntr_init_callback)(struct lprocfs_stats *stats)
Enumerations
enum {
BRW_R_PAGES = 0, BRW_W_PAGES, BRW_R_RPC_HIST, BRW_W_RPC_HIST,
BRW_R_IO_TIME, BRW_W_IO_TIME, BRW_R_DISCONT_PAGES, BRW_W_DISCONT_PAGES,
BRW_R_DISCONT_BLOCKS, BRW_W_DISCONT_BLOCKS, BRW_R_DISK_IOSIZE, BRW_W_DISK_IOSIZE,
BRW_R_DIO_FRAGS, BRW_W_DIO_FRAGS, BRW_LAST
}
enum { RENAME_SAMEDIR_SIZE = 0, RENAME_CROSSDIR_SRC_SIZE, RENAME_CROSSDIR_TGT_SIZE, RENAME_LAST }
enum {
LPROCFS_CNTR_EXTERNALLOCK = 0x0001, LPROCFS_CNTR_AVGMINMAX = 0x0002, LPROCFS_CNTR_STDDEV = 0x0004, LPROCFS_TYPE_REGS = 0x0100,
LPROCFS_TYPE_BYTES = 0x0200, LPROCFS_TYPE_PAGES = 0x0400, LPROCFS_TYPE_CYCLE = 0x0800
}
enum lprocfs_stats_lock_ops { LPROCFS_GET_NUM_CPU = 0x0001, LPROCFS_GET_SMP_ID = 0x0002 }
enum lprocfs_stats_flags { LPROCFS_STATS_FLAG_NONE = 0x0000, LPROCFS_STATS_FLAG_NOPERCPU = 0x0001, LPROCFS_STATS_FLAG_IRQ_SAFE = 0x0002 }
enum lprocfs_fields_flags {
LPROCFS_FIELDS_FLAGS_CONFIG = 0x0001, LPROCFS_FIELDS_FLAGS_SUM = 0x0002, LPROCFS_FIELDS_FLAGS_MIN = 0x0003, LPROCFS_FIELDS_FLAGS_MAX = 0x0004,
LPROCFS_FIELDS_FLAGS_AVG = 0x0005, LPROCFS_FIELDS_FLAGS_SUMSQUARE = 0x0006, LPROCFS_FIELDS_FLAGS_COUNT = 0x0007
}
enum {
PTLRPC_REQWAIT_CNTR = 0, PTLRPC_REQQDEPTH_CNTR, PTLRPC_REQACTIVE_CNTR, PTLRPC_TIMEOUT,
PTLRPC_REQBUF_AVAIL_CNTR, PTLRPC_LAST_CNTR
}
enum lprocfs_extra_opc {
LDLM_GLIMPSE_ENQUEUE = 0, LDLM_PLAIN_ENQUEUE, LDLM_EXTENT_ENQUEUE, LDLM_FLOCK_ENQUEUE,
LDLM_IBITS_ENQUEUE, MDS_REINT_SETATTR, MDS_REINT_CREATE, MDS_REINT_LINK,
MDS_REINT_UNLINK, MDS_REINT_RENAME, MDS_REINT_OPEN, MDS_REINT_SETXATTR,
BRW_READ_BYTES, BRW_WRITE_BYTES, EXTRA_LAST_OPC
}
Functions
static int opcode_offset (__u32 opc)
static void s2dhms (struct dhms *ts, time_t secs)
static void lprocfs_counter_add (struct lprocfs_stats *stats, int index, long amount)
static void lprocfs_counter_incr (struct lprocfs_stats *stats, int index)
static void lprocfs_counter_sub (struct lprocfs_stats *stats, int index, long amount)
static void lprocfs_counter_decr (struct lprocfs_stats *stats, int index)
static void lprocfs_counter_init (struct lprocfs_stats *stats, int index, unsigned conf, const char *name, const char *units)
static __u64 lc_read_helper (struct lprocfs_counter *lc, enum lprocfs_fields_flags field)
static struct lprocfs_stats * lprocfs_alloc_stats (unsigned int num, enum lprocfs_stats_flags flags)
static void lprocfs_clear_stats (struct lprocfs_stats *stats)
static void lprocfs_free_stats (struct lprocfs_stats **stats)
static int lprocfs_register_stats (struct proc_dir_entry *root, const char *name, struct lprocfs_stats *stats)
static void lprocfs_init_ops_stats (int num_private_stats, struct lprocfs_stats *stats)
static void lprocfs_init_mps_stats (int num_private_stats, struct lprocfs_stats *stats)
static void lprocfs_init_ldlm_stats (struct lprocfs_stats *ldlm_stats)
static int lprocfs_alloc_obd_stats (struct obd_device *obddev, unsigned int num_private_stats)
static int lprocfs_alloc_md_stats (struct obd_device *obddev, unsigned int num_private_stats)
static void lprocfs_free_obd_stats (struct obd_device *obddev)
static void lprocfs_free_md_stats (struct obd_device *obddev)
static int lprocfs_add_clear_entry (struct obd_export *exp)
static void lprocfs_free_per_client_stats (struct obd_device *obd)
static int lprocfs_exp_cleanup (struct obd_export *exp)
static struct proc_dir_entry * lprocfs_add_simple (struct proc_dir_entry *root, char *name, void *data, const struct file_operations *fops)
static struct proc_dir_entry * lprocfs_add_symlink (const char *name, struct proc_dir_entry *parent, const char *format,...)
static int lprocfs_add_vars (struct proc_dir_entry *root, struct lprocfs_vars *var, void *data)
static struct proc_dir_entry * lprocfs_register (const char *name, struct proc_dir_entry *parent, struct lprocfs_vars *list, void *data)
static void lprocfs_remove (struct proc_dir_entry **root)
static void lprocfs_remove_proc_entry (const char *name, struct proc_dir_entry *parent)
static int lprocfs_obd_setup (struct obd_device *dev)
static int lprocfs_obd_cleanup (struct obd_device *dev)
static int lprocfs_uuid_seq_show (struct seq_file *m, void *data)
static int lprocfs_name_seq_show (struct seq_file *m, void *data)
static int lprocfs_server_seq_show (struct seq_file *m, void *data)
static int lprocfs_conn_uuid_seq_show (struct seq_file *m, void *data)
static int lprocfs_import_seq_show (struct seq_file *m, void *data)
static int lprocfs_state_seq_show (struct seq_file *m, void *data)
static int lprocfs_connect_flags_seq_show (struct seq_file *m, void *data)
static int lprocfs_at_hist_helper (struct seq_file *m, struct adaptive_timeout *at)
static int lprocfs_timeouts_seq_show (struct seq_file *m, void *data)
static ssize_t lprocfs_timeouts_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
static ssize_t lprocfs_ping_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
static ssize_t lprocfs_import_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
static int lprocfs_pinger_recov_seq_show (struct seq_file *m, void *data)
static ssize_t lprocfs_pinger_recov_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
static int lprocfs_blksize_seq_show (struct seq_file *m, void *data)
static int lprocfs_kbytestotal_seq_show (struct seq_file *m, void *data)
static int lprocfs_kbytesfree_seq_show (struct seq_file *m, void *data)
static int lprocfs_kbytesavail_seq_show (struct seq_file *m, void *data)
static int lprocfs_filestotal_seq_show (struct seq_file *m, void *data)
static int lprocfs_filesfree_seq_show (struct seq_file *m, void *data)
static void lprocfs_oh_tally (struct obd_histogram *oh, unsigned int value)
static void lprocfs_oh_tally_log2 (struct obd_histogram *oh, unsigned int value)
static void lprocfs_oh_clear (struct obd_histogram *oh)
static unsigned long lprocfs_oh_sum (struct obd_histogram *oh)
static void lprocfs_stats_collect (struct lprocfs_stats *stats, int idx, struct lprocfs_counter *cnt)
static __u64 lprocfs_stats_collector (struct lprocfs_stats *stats, int idx, enum lprocfs_fields_flags field)
static int lprocfs_job_stats_log (struct obd_device *obd, char *jobid, int event, long amount)
static void lprocfs_job_stats_fini (struct obd_device *obd)
static int lprocfs_job_stats_init (struct obd_device *obd, int cntr_num, cntr_init_callback fn)
Variables
struct proc_dir_entry * proc_lustre_root
Define Documentation
#define DHMS_FMT "%dd%dh%02dm%02ds"
Definition at line 379 of file lprocfs_status.h.
#define DHMS_VARS (x) (x)->d, (x)->h, (x)->m, (x)->s
Definition at line 380 of file lprocfs_status.h.
#define EXTRA_FIRST_OPC LDLM_GLIMPSE_ENQUEUE
Definition at line 359 of file lprocfs_status.h.
#define EXTRA_MAX_OPCODES
Value:
((PTLRPC_LAST_CNTR - PTLRPC_FIRST_CNTR)  + \
                            OPC_RANGE(EXTRA))
Definition at line 327 of file lprocfs_status.h.
Referenced by ptlrpc_server_handle_request().
#define JOBSTATS_DISABLE "disable"
Definition at line 383 of file lprocfs_status.h.
Referenced by lustre_get_jobid().
#define JOBSTATS_JOBID_VAR_MAX_LEN 20
Definition at line 382 of file lprocfs_status.h.
Referenced by class_set_global().
#define JOBSTATS_NODELOCAL "nodelocal"
Definition at line 385 of file lprocfs_status.h.
Referenced by lustre_get_jobid().
#define JOBSTATS_PROCNAME_UID "procname_uid"
Definition at line 384 of file lprocfs_status.h.
Referenced by lustre_get_jobid().
#define LC_MIN_INIT ((~(__u64)0) >> 1)
Definition at line 136 of file lprocfs_status.h.
#define lc_sum lc_array_sum[0]
Definition at line 157 of file lprocfs_status.h.
#define lc_sum_irq lc_array_sum[1]
Definition at line 158 of file lprocfs_status.h.
#define LPROC_SEQ_FOPS (name)
Definition at line 1052 of file lprocfs_status.h.
#define LPROC_SEQ_FOPS_RO (name)
Definition at line 1051 of file lprocfs_status.h.
#define LPROC_SEQ_FOPS_RO_TYPE (name, type)
Definition at line 1053 of file lprocfs_status.h.
#define LPROC_SEQ_FOPS_RW_TYPE (name, type)
Definition at line 1054 of file lprocfs_status.h.
#define LPROC_SEQ_FOPS_WO_TYPE (name, type)
Definition at line 1055 of file lprocfs_status.h.
#define LUSTRE_MAX_OPCODES
Value:
(OPC_RANGE(OST)  + \
                            OPC_RANGE(MDS)  + \
                            OPC_RANGE(LDLM) + \
                            OPC_RANGE(MGS)  + \
                            OPC_RANGE(OBD)  + \
                            OPC_RANGE(LLOG) + \
                            OPC_RANGE(SEC)  + \
                            OPC_RANGE(SEQ)  + \
                            OPC_RANGE(SEC)  + \
                            OPC_RANGE(FLD)  + \
                            OPC_RANGE(OUT_UPDATE) + \
                            OPC_RANGE(LFSCK))
Definition at line 314 of file lprocfs_status.h.
Referenced by ll_opcode2str(), and ptlrpc_server_handle_request().
#define OBD_HIST_MAX 32
Definition at line 64 of file lprocfs_status.h.
Referenced by display_rename_stats(), and obd_mod_rpc_stats_seq_show().
#define OPC_RANGE (seg) (seg ## _LAST_OPC - seg ## _FIRST_OPC)
Definition at line 201 of file lprocfs_status.h.
Referenced by opcode_offset().
#define proc_lustre_root NULL
Definition at line 864 of file lprocfs_status.h.
Referenced by class_register_type(), class_unregister_type(), fid_init(), fld_init(), lod_init(), lustre_init(), nodemap_procfs_init(), osp_init(), and sptlrpc_lproc_init().
#define PTLRPC_FIRST_CNTR PTLRPC_REQWAIT_CNTR
Definition at line 339 of file lprocfs_status.h.
#define target_print_req NULL
Definition at line 1072 of file lprocfs_status.h.
Referenced by mds_start_ptlrpc_service(), mgs_init0(), and ost_setup().
Typedef Documentation
typedef void(* cntr_init_callback)(struct lprocfs_stats *stats)
Definition at line 387 of file lprocfs_status.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
BRW_R_PAGES
BRW_W_PAGES
BRW_R_RPC_HIST
BRW_W_RPC_HIST
BRW_R_IO_TIME
BRW_W_IO_TIME
BRW_R_DISCONT_PAGES
BRW_W_DISCONT_PAGES
BRW_R_DISCONT_BLOCKS
BRW_W_DISCONT_BLOCKS
BRW_R_DISK_IOSIZE
BRW_W_DISK_IOSIZE
BRW_R_DIO_FRAGS
BRW_W_DIO_FRAGS
BRW_LAST
Definition at line 70 of file lprocfs_status.h.
anonymous enum
Enumerator:
RENAME_SAMEDIR_SIZE
RENAME_CROSSDIR_SRC_SIZE
RENAME_CROSSDIR_TGT_SIZE
RENAME_LAST
Definition at line 92 of file lprocfs_status.h.
anonymous enum
Enumerator:
LPROCFS_CNTR_EXTERNALLOCK
LPROCFS_CNTR_AVGMINMAX
LPROCFS_CNTR_STDDEV
LPROCFS_TYPE_REGS
LPROCFS_TYPE_BYTES
LPROCFS_TYPE_PAGES
LPROCFS_TYPE_CYCLE
Definition at line 124 of file lprocfs_status.h.
anonymous enum
Enumerator:
PTLRPC_REQWAIT_CNTR
PTLRPC_REQQDEPTH_CNTR
PTLRPC_REQACTIVE_CNTR
PTLRPC_TIMEOUT
PTLRPC_REQBUF_AVAIL_CNTR
PTLRPC_LAST_CNTR
Definition at line 330 of file lprocfs_status.h.
enum lprocfs_extra_opc
Enumerator:
LDLM_GLIMPSE_ENQUEUE
LDLM_PLAIN_ENQUEUE
LDLM_EXTENT_ENQUEUE
LDLM_FLOCK_ENQUEUE
LDLM_IBITS_ENQUEUE
MDS_REINT_SETATTR
MDS_REINT_CREATE
MDS_REINT_LINK
MDS_REINT_UNLINK
MDS_REINT_RENAME
MDS_REINT_OPEN
MDS_REINT_SETXATTR
BRW_READ_BYTES
BRW_WRITE_BYTES
EXTRA_LAST_OPC
Definition at line 341 of file lprocfs_status.h.
enum lprocfs_fields_flags
Enumerator:
LPROCFS_FIELDS_FLAGS_CONFIG
LPROCFS_FIELDS_FLAGS_SUM
LPROCFS_FIELDS_FLAGS_MIN
LPROCFS_FIELDS_FLAGS_MAX
LPROCFS_FIELDS_FLAGS_AVG
LPROCFS_FIELDS_FLAGS_SUMSQUARE
LPROCFS_FIELDS_FLAGS_COUNT
Definition at line 176 of file lprocfs_status.h.
enum lprocfs_stats_flags
Enumerator:
LPROCFS_STATS_FLAG_NONE
LPROCFS_STATS_FLAG_NOPERCPU
LPROCFS_STATS_FLAG_IRQ_SAFE
Definition at line 169 of file lprocfs_status.h.
enum lprocfs_stats_lock_ops
Enumerator:
LPROCFS_GET_NUM_CPU
LPROCFS_GET_SMP_ID
Definition at line 164 of file lprocfs_status.h.
Function Documentation
static __u64 lc_read_helper (struct lprocfs_counter * lc, enum lprocfs_fields_flags field) [inline, static]
Definition at line 883 of file lprocfs_status.h.
static int lprocfs_add_clear_entry (struct obd_export * exp) [inline, static]
Definition at line 919 of file lprocfs_status.h.
static struct proc_dir_entry* lprocfs_add_simple (struct proc_dir_entry * root, char * name, void * data, const struct file_operations * fops) [static, read]
Definition at line 938 of file lprocfs_status.h.
Referenced by lod_pool_new(), lov_pool_new(), mdt_procfs_init(), and ofd_procfs_init().
static struct proc_dir_entry* lprocfs_add_symlink (const char * name, struct proc_dir_entry * parent, const char * format, ...) [static, read]
Definition at line 942 of file lprocfs_status.h.
Referenced by lmv_connect_mdc(), lov_connect_obd(), and ofd_procfs_add_brw_stats_symlink().
static int lprocfs_add_vars (struct proc_dir_entry * root, struct lprocfs_vars * var, void * data) [inline, static]
Definition at line 945 of file lprocfs_status.h.
Referenced by ldlm_add_var(), lprocfs_nodemap_register(), seq_client_proc_init(), and seq_server_proc_init().
static int lprocfs_alloc_md_stats (struct obd_device * obddev, unsigned int num_private_stats) [inline, static]
Definition at line 910 of file lprocfs_status.h.
Referenced by lmv_setup(), mdc_setup(), and mdt_procfs_init().
static int lprocfs_alloc_obd_stats (struct obd_device * obddev, unsigned int num_private_stats) [inline, static]
Definition at line 907 of file lprocfs_status.h.
Referenced by echo_setup(), and ofd_procfs_init().
static struct lprocfs_stats* lprocfs_alloc_stats (unsigned int num, enum lprocfs_stats_flags flags) [static, read]
Definition at line 889 of file lprocfs_status.h.
Referenced by lprocfs_nid_ldlm_stats_init(), lu_site_init(), mdt_export_stats_init(), mgs_export_stats_init(), obdclass_init(), and ofd_export_stats_init().
static int lprocfs_at_hist_helper (struct seq_file * m, struct adaptive_timeout * at) [inline, static]
Definition at line 980 of file lprocfs_status.h.
static int lprocfs_blksize_seq_show (struct seq_file * m, void * data) [inline, static]
Definition at line 1013 of file lprocfs_status.h.
static void lprocfs_clear_stats (struct lprocfs_stats * stats) [inline, static]
Definition at line 891 of file lprocfs_status.h.
static int lprocfs_conn_uuid_seq_show (struct seq_file * m, void * data) [inline, static]
Definition at line 967 of file lprocfs_status.h.
static int lprocfs_connect_flags_seq_show (struct seq_file * m, void * data) [inline, static]
Definition at line 973 of file lprocfs_status.h.
static void lprocfs_counter_add (struct lprocfs_stats * stats, int index, long amount) [inline, static]
Definition at line 866 of file lprocfs_status.h.
Referenced by after_reply(), echo_preprw(), ofd_counter_incr(), osd_bufs_get_write(), osd_get_page(), osd_read_prep(), osd_write_prep(), ptl_send_rpc(), ptlrpc_check_rqbd_pool(), and ptlrpc_server_handle_request().
static void lprocfs_counter_decr (struct lprocfs_stats * stats, int index) [inline, static]
Definition at line 875 of file lprocfs_status.h.
Referenced by htable_lookup(), ldlm_lock_put(), lu_object_unhash(), and lu_site_purge().
static void lprocfs_counter_incr (struct lprocfs_stats * stats, int index) [inline, static]
Definition at line 869 of file lprocfs_status.h.
Referenced by htable_lookup(), ldlm_lock_new(), ll_ra_stats_inc_sbi(), lu_object_alloc(), lu_object_find_try(), lu_object_put(), lu_site_purge(), mdt_counter_incr(), mdt_reint_rec(), and tgt_counter_incr().
static void lprocfs_counter_init (struct lprocfs_stats * stats, int index, unsigned conf, const char * name, const char * units) [inline, static]
Definition at line 878 of file lprocfs_status.h.
Referenced by echo_setup(), lu_site_init(), mdt_stats_counter_init(), and obdclass_init().
static void lprocfs_counter_sub (struct lprocfs_stats * stats, int index, long amount) [inline, static]
Definition at line 872 of file lprocfs_status.h.
static int lprocfs_exp_cleanup (struct obd_export * exp) [inline, static]
Definition at line 935 of file lprocfs_status.h.
Referenced by class_export_put().
static int lprocfs_filesfree_seq_show (struct seq_file * m, void * data) [inline, static]
Definition at line 1028 of file lprocfs_status.h.
static int lprocfs_filestotal_seq_show (struct seq_file * m, void * data) [inline, static]
Definition at line 1025 of file lprocfs_status.h.
static void lprocfs_free_md_stats (struct obd_device * obddev) [inline, static]
Definition at line 915 of file lprocfs_status.h.
Referenced by lmv_precleanup(), mdc_precleanup(), and mdt_procfs_fini().
static void lprocfs_free_obd_stats (struct obd_device * obddev) [inline, static]
Definition at line 913 of file lprocfs_status.h.
Referenced by echo_cleanup(), mdt_procfs_fini(), ofd_procfs_fini(), and ofd_procfs_init().
static void lprocfs_free_per_client_stats (struct obd_device * obd) [inline, static]
Definition at line 921 of file lprocfs_status.h.
Referenced by mdt_procfs_fini(), and ofd_procfs_fini().
static void lprocfs_free_stats (struct lprocfs_stats ** stats) [inline, static]
Definition at line 893 of file lprocfs_status.h.
Referenced by lu_site_fini(), mdt_export_stats_init(), mgs_export_stats_init(), obdclass_exit(), and ofd_export_stats_init().
static int lprocfs_import_seq_show (struct seq_file * m, void * data) [inline, static]
Definition at line 969 of file lprocfs_status.h.
static ssize_t lprocfs_import_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [inline, static]
Definition at line 1000 of file lprocfs_status.h.
static void lprocfs_init_ldlm_stats (struct lprocfs_stats * ldlm_stats) [inline, static]
Definition at line 905 of file lprocfs_status.h.
Referenced by lprocfs_nid_ldlm_stats_init().
static void lprocfs_init_mps_stats (int num_private_stats, struct lprocfs_stats * stats) [inline, static]
Definition at line 902 of file lprocfs_status.h.
static void lprocfs_init_ops_stats (int num_private_stats, struct lprocfs_stats * stats) [inline, static]
Definition at line 899 of file lprocfs_status.h.
Referenced by mgs_export_stats_init(), and ofd_export_stats_init().
static void lprocfs_job_stats_fini (struct obd_device * obd) [inline, static]
Definition at line 1063 of file lprocfs_status.h.
Referenced by mdt_procfs_fini(), and ofd_procfs_fini().
static int lprocfs_job_stats_init (struct obd_device * obd, int cntr_num, cntr_init_callback fn) [inline, static]
Definition at line 1066 of file lprocfs_status.h.
Referenced by mdt_procfs_init(), and ofd_procfs_init().
static int lprocfs_job_stats_log (struct obd_device * obd, char * jobid, int event, long amount) [inline, static]
Definition at line 1059 of file lprocfs_status.h.
Referenced by mdt_counter_incr(), and ofd_counter_incr().
static int lprocfs_kbytesavail_seq_show (struct seq_file * m, void * data) [inline, static]
Definition at line 1022 of file lprocfs_status.h.
static int lprocfs_kbytesfree_seq_show (struct seq_file * m, void * data) [inline, static]
Definition at line 1019 of file lprocfs_status.h.
static int lprocfs_kbytestotal_seq_show (struct seq_file * m, void * data) [inline, static]
Definition at line 1016 of file lprocfs_status.h.
static int lprocfs_name_seq_show (struct seq_file * m, void * data) [inline, static]
Definition at line 963 of file lprocfs_status.h.
static int lprocfs_obd_cleanup (struct obd_device * dev) [inline, static]
Definition at line 959 of file lprocfs_status.h.
Referenced by echo_cleanup(), lmv_precleanup(), lov_cleanup(), lwp_device_fini(), mdc_precleanup(), mds_device_fini(), mdt_procfs_fini(), mgc_cleanup(), ofd_procfs_fini(), ofd_procfs_init(), osc_precleanup(), osp_device_fini(), osp_init0(), ost_cleanup(), and ost_setup().
static int lprocfs_obd_setup (struct obd_device * dev) [inline, static]
Definition at line 957 of file lprocfs_status.h.
Referenced by echo_setup(), lmv_setup(), lov_setup(), lwp_init0(), mdc_setup(), mds_device_alloc(), mdt_procfs_init(), mgc_setup(), ofd_procfs_init(), osc_setup(), and ost_setup().
static void lprocfs_oh_clear (struct obd_histogram * oh) [inline, static]
Definition at line 1037 of file lprocfs_status.h.
Referenced by mdt_rename_stats_seq_write().
static unsigned long lprocfs_oh_sum (struct obd_histogram * oh) [inline, static]
Definition at line 1040 of file lprocfs_status.h.
Referenced by display_rename_stats(), and obd_mod_rpc_stats_seq_show().
static void lprocfs_oh_tally (struct obd_histogram * oh, unsigned int value) [inline, static]
Definition at line 1031 of file lprocfs_status.h.
Referenced by obd_get_mod_rpc_slot(), osc_build_rpc(), osd_fini_iobuf(), and record_start_io().
static void lprocfs_oh_tally_log2 (struct obd_histogram * oh, unsigned int value) [inline, static]
Definition at line 1034 of file lprocfs_status.h.
Referenced by mdt_rename_counter_tally(), osc_build_rpc(), osd_fini_iobuf(), record_end_io(), and record_start_io().
static ssize_t lprocfs_ping_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [inline, static]
Definition at line 996 of file lprocfs_status.h.
static int lprocfs_pinger_recov_seq_show (struct seq_file * m, void * data) [inline, static]
Definition at line 1004 of file lprocfs_status.h.
static ssize_t lprocfs_pinger_recov_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [inline, static]
Definition at line 1007 of file lprocfs_status.h.
static struct proc_dir_entry* lprocfs_register (const char * name, struct proc_dir_entry * parent, struct lprocfs_vars * list, void * data) [static, read]
Definition at line 949 of file lprocfs_status.h.
Referenced by class_procfs_init(), class_register_type(), fid_init(), fld_init(), gss_init_lproc(), hsm_cdt_procfs_init(), lmv_connect(), lod_init(), lov_connect(), lov_setup(), lustre_init(), mdd_procfs_init(), nodemap_procfs_init(), ofd_procfs_init(), osc_setup(), osp_init(), qmt_device_init0(), qmt_pool_alloc(), qsd_init(), seq_client_proc_init(), seq_server_proc_init(), and sptlrpc_lproc_init().
static int lprocfs_register_stats (struct proc_dir_entry * root, const char * name, struct lprocfs_stats * stats) [inline, static]
Definition at line 895 of file lprocfs_status.h.
Referenced by lprocfs_nid_ldlm_stats_init(), mdt_export_stats_init(), mgs_export_stats_init(), and ofd_export_stats_init().
static void lprocfs_remove (struct proc_dir_entry ** root) [inline, static]
Definition at line 952 of file lprocfs_status.h.
Referenced by class_procfs_clean(), class_procfs_init(), class_unregister_type(), fid_exit(), fld_exit(), gss_exit_lproc(), hsm_cdt_procfs_fini(), lmv_connect(), lmv_disconnect(), lod_pool_del(), lod_pool_new(), lov_disconnect(), lov_pool_del(), lov_pool_new(), lprocfs_nodemap_register(), lprocfs_nodemap_remove(), lustre_exit(), lustre_init(), mdd_procfs_fini(), nodemap_procfs_exit(), osp_device_fini(), osp_init0(), qmt_device_fini(), qmt_pool_free(), qsd_fini(), seq_client_proc_fini(), seq_server_proc_fini(), and sptlrpc_lproc_fini().
static void lprocfs_remove_proc_entry (const char * name, struct proc_dir_entry * parent) [inline, static]
Definition at line 954 of file lprocfs_status.h.
Referenced by lmv_disconnect_mdc(), lov_disconnect_obd(), and mdt_procfs_fini().
static int lprocfs_server_seq_show (struct seq_file * m, void * data) [inline, static]
Definition at line 965 of file lprocfs_status.h.
static int lprocfs_state_seq_show (struct seq_file * m, void * data) [inline, static]
Definition at line 971 of file lprocfs_status.h.
static void lprocfs_stats_collect (struct lprocfs_stats * stats, int idx, struct lprocfs_counter * cnt) [inline, static]
Definition at line 1043 of file lprocfs_status.h.
Referenced by ls_stats_read().
static __u64 lprocfs_stats_collector (struct lprocfs_stats * stats, int idx, enum lprocfs_fields_flags field) [inline, static]
Definition at line 1047 of file lprocfs_status.h.
References __u64.
static int lprocfs_timeouts_seq_show (struct seq_file * m, void * data) [inline, static]
Definition at line 983 of file lprocfs_status.h.
static ssize_t lprocfs_timeouts_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [inline, static]
Definition at line 986 of file lprocfs_status.h.
static int lprocfs_uuid_seq_show (struct seq_file * m, void * data) [inline, static]
Definition at line 961 of file lprocfs_status.h.
static int opcode_offset (__u32 opc) [inline, static]
Definition at line 204 of file lprocfs_status.h.
References FLD_FIRST_OPC, FLD_LAST_OPC, LDLM_FIRST_OPC, LDLM_LAST_OPC, LFSCK_FIRST_OPC, LFSCK_LAST_OPC, LLOG_FIRST_OPC, LLOG_LAST_OPC, MDS_FIRST_OPC, MDS_LAST_OPC, MGS_FIRST_OPC, MGS_LAST_OPC, OBD_FIRST_OPC, OBD_LAST_OPC, OPC_RANGE, OST_FIRST_OPC, OST_LAST_OPC, OUT_UPDATE, OUT_UPDATE_FIRST_OPC, OUT_UPDATE_LAST_OPC, QUOTA_FIRST_OPC, QUOTA_LAST_OPC, SEC_FIRST_OPC, SEC_LAST_OPC, SEQ_FIRST_OPC, and SEQ_LAST_OPC.
Referenced by ll_opcode2str(), and ptlrpc_server_handle_request().
static void s2dhms (struct dhms * ts, time_t secs) [inline, static]
Definition at line 370 of file lprocfs_status.h.
References dhms::d, dhms::h, dhms::m, and dhms::s.
Variable Documentation
struct proc_dir_entry* proc_lustre_root
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.