Lustre: lustre/quota/lquota_disk.c File Reference
lustre/quota/lquota_disk.c File Reference
#include "lquota_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LQUOTA
#define LQUOTA_MODE (S_IFREG | S_IRUGO | S_IWUSR)
Functions
static struct dt_object * lquota_disk_find_create (const struct lu_env *env, struct dt_device *dev, struct dt_object *parent, struct lu_fid *fid, const struct dt_index_features *idx_feat, char *name)
static int lquota_disk_slv_filename (const struct lu_fid *glb_fid, struct obd_uuid *uuid, char *filename)
struct dt_object * lquota_disk_dir_find_create (const struct lu_env *env, struct dt_device *dev, struct dt_object *parent, const char *name)
struct dt_object * lquota_disk_glb_find_create (const struct lu_env *env, struct dt_device *dev, struct dt_object *parent, struct lu_fid *fid, bool local)
struct dt_object * lquota_disk_slv_find (const struct lu_env *env, struct dt_device *dev, struct dt_object *parent, const struct lu_fid *glb_fid, struct obd_uuid *uuid)
struct dt_object * lquota_disk_slv_find_create (const struct lu_env *env, struct dt_device *dev, struct dt_object *parent, struct lu_fid *glb_fid, struct obd_uuid *uuid, bool local)
int lquota_disk_for_each_slv (const struct lu_env *env, struct dt_object *parent, struct lu_fid *glb_fid, lquota_disk_slv_cb_t func, void *arg)
int lquota_disk_read (const struct lu_env *env, struct dt_object *obj, union lquota_id *id, struct dt_rec *rec)
int lquota_disk_declare_write (const struct lu_env *env, struct thandle *th, struct dt_object *obj, union lquota_id *id)
int lquota_disk_write (const struct lu_env *env, struct thandle *th, struct dt_object *obj, union lquota_id *id, struct dt_rec *rec, __u32 flags, __u64 *ver)
int lquota_disk_update_ver (const struct lu_env *env, struct dt_device *dev, struct dt_object *obj, __u64 ver)
int lquota_disk_write_glb (const struct lu_env *env, struct dt_object *obj, __u64 id, struct lquota_glb_rec *rec)
Define Documentation
#define DEBUG_SUBSYSTEM S_LQUOTA
Definition at line 51 of file lquota_disk.c.
#define LQUOTA_MODE (S_IFREG | S_IRUGO | S_IWUSR)
Definition at line 55 of file lquota_disk.c.
Referenced by lquota_disk_find_create(), lquota_disk_glb_find_create(), and lquota_disk_slv_find_create().
Function Documentation
int lquota_disk_declare_write (const struct lu_env * env, struct thandle * th, struct dt_object * obj, union lquota_id * id)
Definition at line 589 of file lquota_disk.c.
References dt_object::do_index_ops, dt_declare_delete(), dt_declare_insert(), dt_declare_version_set(), dt_key, dt_object_exists(), ENTRY, LASSERT, lquota_info(), lquota_id::qid_uid, lquota_thread_info::qti_rec, and RETURN.
Referenced by qmt_trans_start_with_slv(), and qsd_update_index().
struct dt_object* lquota_disk_dir_find_create (const struct lu_env * env, struct dt_device * dev, struct dt_object * parent, const char * name) [read]
Definition at line 158 of file lquota_disk.c.
References dt_device::dd_lu_dev, dt_object::do_lu, dt_locate(), dt_locate_at(), dt_root_get(), dt_try_as_dir(), ENTRY, EXIT, GOTO, lu_device::ld_site, lu_object::lo_header, local_file_find_or_create(), local_oid_storage_fini(), local_oid_storage_init(), lu_object_header::loh_fid, lquota_info(), lu_site::ls_top_dev, lu_local_name_obj_fid(), lu_object_get(), lu_object_put(), lu_object_put_nocache(), lquota_thread_info::qti_fid, and RETURN.
Referenced by qmt_device_prepare(), qmt_pool_prepare(), and qsd_prepare().
static struct dt_object* lquota_disk_find_create (const struct lu_env * env, struct dt_device * dev, struct dt_object * parent, struct lu_fid * fid, const struct dt_index_features * idx_feat, char * name) [static, read]
Definition at line 62 of file lquota_disk.c.
References dt_object::do_lu, dt_locate(), ENTRY, GOTO, lu_object::lo_header, local_index_find_or_create(), local_oid_storage_fini(), local_oid_storage_init(), lu_object_header::loh_fid, lquota_info(), LQUOTA_MODE, lu_object_put_nocache(), lquota_thread_info::qti_fid, and RETURN.
Referenced by lquota_disk_glb_find_create(), and lquota_disk_slv_find_create().
int lquota_disk_for_each_slv (const struct lu_env * env, struct dt_object * parent, struct lu_fid * glb_fid, lquota_disk_slv_cb_t func, void * arg)
Definition at line 461 of file lquota_disk.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, dt_key, dt_lookup_dir(), ENTRY, lu_fid::f_oid, lu_fid::f_seq, FID_SEQ_QUOTA, dt_index_operations::dt_it_ops::init, lquota_info(), LQUOTA_NAME_MAX, name, OBD_ALLOC, OBD_FREE, lquota_thread_info::qti_buf, lquota_thread_info::qti_fid, and RETURN.
Referenced by qmt_pool_prepare().
struct dt_object* lquota_disk_glb_find_create (const struct lu_env * env, struct dt_device * dev, struct dt_object * parent, struct lu_fid * fid, bool local) [read]
Definition at line 234 of file lquota_disk.c.
References CDEBUG, CERROR, D_QUOTA, dt_device::dd_lu_dev, DFID, dt_object::do_index_ops, dt_object_operations::do_index_try, dt_object::do_lu, dt_object::do_ops, dt_quota_glb_features, ENTRY, lu_fid::f_oid, lu_device::ld_obd, local_index_find_or_create_with_fid(), lquota_disk_find_create(), lquota_info(), LQUOTA_MODE, lu_local_name_obj_fid(), lu_object_fid(), lu_object_put(), obd_device::obd_name, PFID, lquota_thread_info::qti_buf, lquota_thread_info::qti_fid, and RETURN.
Referenced by qmt_pool_prepare(), and qsd_qtype_init().
int lquota_disk_read (const struct lu_env * env, struct dt_object * obj, union lquota_id * id, struct dt_rec * rec)
Definition at line 562 of file lquota_disk.c.
References dt_object::do_index_ops, dt_key, dt_lookup(), dt_object_exists(), dt_read_lock(), dt_read_unlock(), ENTRY, LASSERT, lquota_id::qid_uid, and RETURN.
Referenced by qmt_lqe_read(), qmt_slv_read(), qsd_lqe_read(), and qsd_refresh_usage().
static int lquota_disk_slv_filename (const struct lu_fid * glb_fid, struct obd_uuid * uuid, char * filename) [inline, static]
Definition at line 99 of file lquota_disk.c.
References CERROR, lu_fid::f_oid, name, OBD_ALLOC, OBD_FREE, RETURN, and obd_uuid::uuid.
Referenced by lquota_disk_slv_find(), and lquota_disk_slv_find_create().
struct dt_object* lquota_disk_slv_find (const struct lu_env * env, struct dt_device * dev, struct dt_object * parent, const struct lu_fid * glb_fid, struct obd_uuid * uuid) [read]
Definition at line 307 of file lquota_disk.c.
References CDEBUG, CERROR, D_QUOTA, dt_device::dd_lu_dev, dt_object::do_index_ops, dt_object_operations::do_index_try, dt_object::do_lu, dt_object::do_ops, dt_locate(), dt_lookup_dir(), dt_quota_slv_features, ENTRY, LASSERT, lu_device::ld_obd, lquota_disk_slv_filename(), lquota_info(), lu_object_put(), obd_device::obd_name, obd_uuid2str(), lquota_thread_info::qti_buf, lquota_thread_info::qti_fid, and RETURN.
Referenced by qmt_dqacq0(), and qmt_pool_new_conn().
struct dt_object* lquota_disk_slv_find_create (const struct lu_env * env, struct dt_device * dev, struct dt_object * parent, struct lu_fid * glb_fid, struct obd_uuid * uuid, bool local) [read]
Definition at line 375 of file lquota_disk.c.
References CDEBUG, CERROR, D_QUOTA, dt_device::dd_lu_dev, DFID, dt_object::do_index_ops, dt_object_operations::do_index_try, dt_object::do_lu, dt_object::do_ops, dt_quota_slv_features, ENTRY, lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, FID_SEQ_QUOTA, LASSERT, lu_device::ld_obd, local_index_find_or_create_with_fid(), lquota_disk_find_create(), lquota_disk_slv_filename(), lquota_extract_fid(), LQUOTA_GENERATED_OID, LQUOTA_GRP_OID, lquota_info(), LQUOTA_MODE, LQUOTA_USR_OID, lu_object_fid(), lu_object_put(), obd_device::obd_name, obd_uuid2str(), PFID, lquota_thread_info::qti_buf, lquota_thread_info::qti_fid, and RETURN.
Referenced by qmt_pool_new_conn(), and qsd_qtype_init().
int lquota_disk_update_ver (const struct lu_env * env, struct dt_device * dev, struct dt_object * obj, __u64 ver)
Definition at line 703 of file lquota_disk.c.
References dt_declare_version_set(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_version_set(), ENTRY, EXIT, GOTO, RETURN, and thandle::th_sync.
Referenced by qmt_pool_prepare(), and qsd_write_version().
int lquota_disk_write (const struct lu_env * env, struct thandle * th, struct dt_object * obj, union lquota_id * id, struct dt_rec * rec, __u32 flags, __u64 * ver)
Definition at line 633 of file lquota_disk.c.
References DFID, dt_object::do_index_ops, dt_object::do_lu, dt_delete(), dt_insert(), dt_key, dt_lookup(), dt_object_exists(), dt_version_get(), dt_version_set(), dt_write_lock(), dt_write_unlock(), ENTRY, EXIT, GOTO, LASSERT, LASSERTF, LQUOTA_BUMP_VER, lquota_info(), LQUOTA_SET_VER, lu_object_fid(), PFID, lquota_id::qid_uid, and lquota_thread_info::qti_rec.
Referenced by qmt_glb_write(), qmt_slv_write(), and qsd_update_index().
int lquota_disk_write_glb (const struct lu_env * env, struct dt_object * obj, __u64 id, struct lquota_glb_rec * rec)
Definition at line 738 of file lquota_disk.c.
References dt_object::do_lu, dt_declare_delete(), dt_declare_insert(), dt_delete(), dt_insert(), dt_key, dt_lookup(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), ENTRY, GOTO, lu_object::lo_dev, lu2dt_dev(), OBD_ALLOC_PTR, OBD_FREE_PTR, and RETURN.
Referenced by qmt_pool_prepare().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.