Lustre: lustre/quota/lquota_lib.c File Reference
lustre/quota/lquota_lib.c File Reference
#include <linux/version.h>
#include <linux/module.h>
#include <linux/init.h>
#include "lquota_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LQUOTA
Functions
LU_KEY_INIT_FINI (lquota, struct lquota_thread_info)
LU_CONTEXT_KEY_DEFINE (lquota, LCT_MD_THREAD|LCT_DT_THREAD|LCT_LOCAL)
LU_KEY_INIT_GENERIC (lquota)
struct dt_object * acct_obj_lookup (const struct lu_env *env, struct dt_device *dev, int type)
Look-up accounting object to collect space usage information for user or group.
static struct dt_object * quota_obj_lookup (const struct lu_env *env, struct dt_device *dev, int type)
Initialize slave index object to collect local quota limit for user or group.
int lquotactl_slv (const struct lu_env *env, struct dt_device *dev, struct obd_quotactl *oqctl)
void lquota_generate_fid (struct lu_fid *fid, int pool_id, int pool_type, int quota_type)
Helper routine returning the FID associated with the global index storing quota settings for the storage pool , resource type and the quota type .
int lquota_extract_fid (const struct lu_fid *fid, int *pool_id, int *pool_type, int *quota_type)
Helper routine used to extract pool ID, pool type and quota type from a given FID.
static int __init lquota_init (void)
static void __exit lquota_exit (void)
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Quota")
MODULE_VERSION (LUSTRE_VERSION_STRING)
MODULE_LICENSE ("GPL")
module_init (lquota_init)
module_exit (lquota_exit)
Variables
struct kmem_cache * lqe_kmem
struct lu_kmem_descr lquota_caches []
Define Documentation
#define DEBUG_SUBSYSTEM S_LQUOTA
Definition at line 31 of file lquota_lib.c.
Function Documentation
struct dt_object* acct_obj_lookup (const struct lu_env * env, struct dt_device * dev, int type) [read]
Look-up accounting object to collect space usage information for user or group.
Parameters:
env - is the environment passed by the caller
dev - is the dt_device storing the accounting object
type - is the quota type, either USRQUOTA or GRPQUOTA
Definition at line 65 of file lquota_lib.c.
References ACCT_GROUP_OID, ACCT_USER_OID, CERROR, dt_device::dd_lu_dev, dt_object::do_index_ops, dt_object_operations::do_index_try, dt_object::do_lu, dt_object::do_ops, dt_acct_features, dt_locate(), dt_object_exists(), ENTRY, lu_device::ld_obd, lquota_info(), lu_local_obj_fid(), lu_object_put(), obd_device::obd_name, lquota_thread_info::qti_fid, QTYPE_NAME, and RETURN.
Referenced by lquotactl_slv(), and qsd_qtype_init().
static void __exit lquota_exit (void) [static]
Definition at line 323 of file lquota_lib.c.
References lquota_thread_key, lu_context_key_degister(), lu_kmem_fini(), qmt_glb_fini(), and qsd_glb_fini().
int lquota_extract_fid (const struct lu_fid * fid, int * pool_id, int * pool_type, int * quota_type)
Helper routine used to extract pool ID, pool type and quota type from a given FID.
Definition at line 256 of file lquota_lib.c.
References ENTRY, lu_fid::f_oid, lu_fid::f_seq, FID_SEQ_QUOTA_GLB, LQUOTA_LAST_RES, LQUOTA_TYPE_MAX, LQUOTA_TYPE_USR, and RETURN.
Referenced by lquota_disk_slv_find_create(), qmt_dqacq(), qmt_lvbo_init(), and qmt_pool_new_conn().
void lquota_generate_fid (struct lu_fid * fid, int pool_id, int pool_type, int quota_type)
Helper routine returning the FID associated with the global index storing quota settings for the storage pool , resource type and the quota type .
Definition at line 240 of file lquota_lib.c.
References lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, FID_SEQ_QUOTA_GLB, LQUOTA_TYPE_GRP, and LQUOTA_TYPE_USR.
Referenced by qmt_glb_lock_notify(), qmt_id_lock_glimpse(), qmt_pool_prepare(), and qsd_qtype_init().
static int __init lquota_init (void) [static]
Definition at line 292 of file lquota_lib.c.
References ENTRY, GOTO, lquota_thread_key, lu_context_key_degister(), lu_context_key_register(), lu_kmem_fini(), lu_kmem_init(), qmt_glb_fini(), qmt_glb_init(), qsd_glb_init(), and RETURN.
int lquotactl_slv (const struct lu_env * env, struct dt_device * dev, struct obd_quotactl * oqctl)
Definition at line 158 of file lquota_lib.c.
References __u64, acct_obj_lookup(), CERROR, dt_device::dd_lu_dev, dt_object::do_index_ops, dt_object::do_lu, obd_dqblk::dqb_bhardlimit, obd_dqblk::dqb_curinodes, obd_dqblk::dqb_curspace, obd_dqblk::dqb_ihardlimit, obd_dqblk::dqb_valid, dt_key, dt_lookup(), ENTRY, GOTO, lu_device::ld_obd, lu_device::ld_site, lquota_info(), lu_site::ls_top_dev, lu_device_is_md(), lu_object_put(), obd_device::obd_name, Q_GETOQUOTA, obd_quotactl::qc_cmd, obd_quotactl::qc_dqblk, obd_quotactl::qc_id, obd_quotactl::qc_type, QIF_LIMITS, QIF_USAGE, quota_obj_lookup(), and RETURN.
Referenced by mdt_quotactl(), and ofd_quotactl().
LU_CONTEXT_KEY_DEFINE (lquota , LCT_MD_THREAD|LCT_DT_THREAD| LCT_LOCAL)
LU_KEY_INIT_FINI (lquota , struct lquota_thread_info)
LU_KEY_INIT_GENERIC (lquota)
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Quota")
module_exit (lquota_exit)
module_init (lquota_init)
MODULE_LICENSE ("GPL")
MODULE_VERSION (LUSTRE_VERSION_STRING)
static struct dt_object* quota_obj_lookup (const struct lu_env * env, struct dt_device * dev, int type) [static, read]
Initialize slave index object to collect local quota limit for user or group.
Parameters:
env - is the environment passed by the caller
dev - is the dt_device storing the slave index object
type - is the quota type, either USRQUOTA or GRPQUOTA
Definition at line 109 of file lquota_lib.c.
References CERROR, dt_device::dd_lu_dev, dt_object::do_index_ops, dt_object_operations::do_index_try, dt_object::do_lu, dt_object::do_ops, dt_locate(), dt_object_exists(), dt_quota_slv_features, ENTRY, lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, FID_SEQ_QUOTA, lu_device::ld_obd, LQUOTA_GRP_OID, lquota_info(), LQUOTA_USR_OID, lu_object_put(), obd_device::obd_name, lquota_thread_info::qti_fid, QTYPE_NAME, and RETURN.
Referenced by lquotactl_slv().
Variable Documentation
struct kmem_cache* lqe_kmem
Definition at line 39 of file lquota_lib.c.
Referenced by lqe_locate(), and lqe_putref().
struct lu_kmem_descr lquota_caches[]
Initial value:
 {
        {
                .ckd_cache = &lqe_kmem,
                .ckd_name  = "lqe_kmem",
                .ckd_size  = sizeof(struct lquota_entry)
        },
        {
                .ckd_cache = NULL
        }
}
Definition at line 41 of file lquota_lib.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.