Lustre: lustre/quota/lquota_entry.c File Reference
lustre/quota/lquota_entry.c File Reference
#include <linux/module.h>
#include <linux/slab.h>
#include <obd_class.h>
#include "lquota_internal.h"
Data Structures
struct lqe_iter_data
Defines
#define DEBUG_SUBSYSTEM S_LQUOTA
Functions
module_param (hash_lqs_cur_bits, int, 0444)
MODULE_PARM_DESC (hash_lqs_cur_bits,"the current bits of lqe hash")
static unsigned lqe64_hash_hash (struct cfs_hash *hs, const void *key, unsigned mask)
static void * lqe64_hash_key (struct hlist_node *hnode)
static int lqe64_hash_keycmp (const void *key, struct hlist_node *hnode)
static void * lqe_hash_object (struct hlist_node *hnode)
static void lqe_hash_get (struct cfs_hash *hs, struct hlist_node *hnode)
static void lqe_hash_put_locked (struct cfs_hash *hs, struct hlist_node *hnode)
static void lqe_hash_exit (struct cfs_hash *hs, struct hlist_node *hnode)
void lquota_lqe_debug0 (struct lquota_entry *lqe, struct libcfs_debug_msg_data *msgdata, const char *fmt,...)
static int lqe_iter_cb (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode, void *data)
static void lqe_cleanup (struct cfs_hash *hash, bool free_all)
Cleanup the entries in the hashtable.
struct lquota_site * lquota_site_alloc (const struct lu_env *env, void *parent, bool is_master, short qtype, struct lquota_entry_operations *ops)
void lquota_site_free (const struct lu_env *env, struct lquota_site *site)
static void lqe_init (struct lquota_entry *lqe)
static int lqe_read (const struct lu_env *env, struct lquota_entry *lqe)
struct lquota_entry * lqe_locate (const struct lu_env *env, struct lquota_site *site, union lquota_id *qid)
Variables
static int hash_lqs_cur_bits = HASH_LQE_CUR_BITS
static struct cfs_hash_ops lqe64_hash_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_LQUOTA
Definition at line 30 of file lquota_entry.c.
Function Documentation
static unsigned lqe64_hash_hash (struct cfs_hash * hs, const void * key, unsigned mask) [static]
Definition at line 42 of file lquota_entry.c.
References __u64, and cfs_hash_u64_hash().
static void* lqe64_hash_key (struct hlist_node * hnode) [static]
Definition at line 47 of file lquota_entry.c.
References hlist_entry, lquota_entry::lqe_hash, lquota_entry::lqe_id, and lquota_id::qid_uid.
static int lqe64_hash_keycmp (const void * key, struct hlist_node * hnode) [static]
Definition at line 54 of file lquota_entry.c.
References __u64, hlist_entry, lquota_entry::lqe_hash, lquota_entry::lqe_id, and lquota_id::qid_uid.
static void lqe_cleanup (struct cfs_hash * hash, bool free_all) [static]
Cleanup the entries in the hashtable.
Parameters:
hash - hash table which stores quota entries
free_all - free all entries or only free the entries without quota enforce ?
Definition at line 155 of file lquota_entry.c.
References CDEBUG, cfs_hash_for_each_safe(), cfs_time_seconds(), D_QUOTA, ENTRY, EXIT, lqe_iter_data::lid_free_all, lqe_iter_data::lid_freed, lqe_iter_data::lid_inuse, and lqe_iter_cb().
Referenced by lquota_site_free().
static void lqe_hash_exit (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 80 of file lquota_entry.c.
References CERROR.
static void lqe_hash_get (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 66 of file lquota_entry.c.
References hlist_entry, lqe_getref(), and lquota_entry::lqe_hash.
static void* lqe_hash_object (struct hlist_node * hnode) [static]
Definition at line 61 of file lquota_entry.c.
References hlist_entry, and lquota_entry::lqe_hash.
static void lqe_hash_put_locked (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 73 of file lquota_entry.c.
References hlist_entry, lquota_entry::lqe_hash, and lqe_putref().
static void lqe_init (struct lquota_entry * lqe) [static]
Definition at line 260 of file lquota_entry.c.
References ENTRY, LASSERT, lquota_entry_operations::lqe_init, lquota_entry::lqe_site, lquota_site::lqs_ops, lquota_site::lqs_parent, and LQUOTA_DEBUG.
Referenced by lqe_locate().
static int lqe_iter_cb (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode, void * data) [static]
Definition at line 118 of file lquota_entry.c.
References cfs_hash_bd_del_locked(), hlist_entry, LASSERT, lqe_iter_data::lid_free_all, lqe_iter_data::lid_freed, lqe_iter_data::lid_inuse, lquota_entry::lqe_enforced, lquota_entry::lqe_hash, lqe_is_master(), lquota_entry::lqe_ref, and LQUOTA_ERROR.
Referenced by lqe_cleanup().
struct lquota_entry* lqe_locate (const struct lu_env * env, struct lquota_site * site, union lquota_id * qid) [read]
Definition at line 313 of file lquota_entry.c.
References CERROR, cfs_hash_findadd_unique(), cfs_hash_lookup(), ENTRY, GOTO, cfs_hash::hs_name, INIT_LIST_HEAD, LASSERT, LPU64, lqe_init(), lqe_kmem, lqe_putref(), lqe_read(), lquota_entry::lqe_uptodate, lquota_site::lqs_hash, OBD_SLAB_ALLOC_PTR_GFP, lquota_id::qid_uid, and RETURN.
Referenced by qmt_pool_lqe_lookup(), qmt_pool_prepare(), qsd_op_adjust(), qsd_op_begin0(), qsd_process_upd(), qsd_reconciliation(), and qsd_reint_qid().
static int lqe_read (const struct lu_env * env, struct lquota_entry * lqe) [static]
Definition at line 282 of file lquota_entry.c.
References ENTRY, LASSERT, lquota_entry_operations::lqe_read, lquota_entry::lqe_site, lquota_entry::lqe_uptodate, lquota_site::lqs_ops, lquota_site::lqs_parent, LQUOTA_DEBUG, and RETURN.
Referenced by lqe_locate().
void lquota_lqe_debug0 (struct lquota_entry * lqe, struct libcfs_debug_msg_data * msgdata, const char * fmt, ...)
Definition at line 98 of file lquota_entry.c.
References LASSERT, lquota_entry_operations::lqe_debug, lquota_entry::lqe_site, lquota_site::lqs_ops, and lquota_site::lqs_parent.
struct lquota_site* lquota_site_alloc (const struct lu_env * env, void * parent, bool is_master, short qtype, struct lquota_entry_operations * ops) [read]
Definition at line 198 of file lquota_entry.c.
References CFS_HASH_BIGNAME, cfs_hash_create(), CFS_HASH_DEFAULT, CFS_HASH_MAX_THETA, CFS_HASH_MIN_THETA, ENTRY, HASH_LQE_BKT_BITS, HASH_LQE_MAX_BITS, hash_lqs_cur_bits, LASSERT, lquota_site::lqs_hash, lquota_site::lqs_is_mst, lquota_site::lqs_ops, lquota_site::lqs_parent, lquota_site::lqs_qtype, OBD_ALLOC_PTR, OBD_FREE_PTR, and RETURN.
Referenced by qmt_pool_prepare(), and qsd_qtype_init().
void lquota_site_free (const struct lu_env * env, struct lquota_site * site)
Definition at line 245 of file lquota_entry.c.
References cfs_hash_putref(), lqe_cleanup(), lquota_site::lqs_hash, lquota_site::lqs_parent, and OBD_FREE_PTR.
Referenced by qmt_pool_free(), and qsd_qtype_fini().
module_param (hash_lqs_cur_bits , int , 0444)
MODULE_PARM_DESC (hash_lqs_cur_bits , "the current bits of lqe hash")
Variable Documentation
int hash_lqs_cur_bits = HASH_LQE_CUR_BITS [static]
Definition at line 37 of file lquota_entry.c.
Referenced by lquota_site_alloc().
struct cfs_hash_ops lqe64_hash_ops [static]
Initial value:
 {
        .hs_hash       = lqe64_hash_hash,
        .hs_key        = lqe64_hash_key,
        .hs_keycmp     = lqe64_hash_keycmp,
        .hs_object     = lqe_hash_object,
        .hs_get        = lqe_hash_get,
        .hs_put_locked = lqe_hash_put_locked,
        .hs_exit       = lqe_hash_exit
}
Definition at line 87 of file lquota_entry.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.