Lustre: lustre/quota/lquota_internal.h File Reference
lustre/quota/lquota_internal.h File Reference
#include <obd.h>
#include <lustre_quota.h>
Data Structures
struct lquota_entry_operations
struct lquota_mst_entry
struct lquota_slv_entry
struct lquota_entry
struct lquota_site
struct lquota_thread_info
Defines
#define QTYPE_NAME(qtype) ((qtype) == USRQUOTA ? "usr" : "grp")
#define RES_NAME(res) ((res) == LQUOTA_RES_MD ? "md" : "dt")
#define QIF_IFLAGS (QIF_INODES | QIF_ITIME | QIF_ILIMITS)
#define QIF_BFLAGS (QIF_SPACE | QIF_BTIME | QIF_BLIMITS)
#define LQUOTA_NAME_MAX 52
#define lqe_hardlimit u.me.lme_hardlimit
#define lqe_softlimit u.me.lme_softlimit
#define lqe_gracetime u.me.lme_gracetime
#define lqe_revoke_time u.me.lme_revoke_time
#define lqe_sem u.me.lme_sem
#define lqe_may_rel u.me.lme_may_rel
#define lqe_qtune u.se.lse_qtune
#define lqe_pending_write u.se.lse_pending_write
#define lqe_waiting_write u.se.lse_waiting_write
#define lqe_pending_rel u.se.lse_pending_rel
#define lqe_pending_req u.se.lse_pending_req
#define lqe_waiters u.se.lse_waiters
#define lqe_lock u.se.lse_lock
#define lqe_usage u.se.lse_usage
#define lqe_adjust_time u.se.lse_adjust_time
#define lqe_lockh u.se.lse_lockh
#define lqe_acq_rc u.se.lse_acq_rc
#define lqe_acq_time u.se.lse_acq_time
#define lqe_edquot_time u.se.lse_edquot_time
#define LQUOTA_BUMP_VER 0x1
#define LQUOTA_SET_VER 0x2
#define LQUOTA_LEAST_QUNIT(type) (type == LQUOTA_RES_MD ? (1 << 10) : toqb(OFD_MAX_BRW_SIZE))
#define LQUOTA_OVER_FL(type) (type == USRQUOTA ? QUOTA_FL_OVER_USRQUOTA : QUOTA_FL_OVER_GRPQUOTA)
#define qti_glb_rec qti_rec.lqr_glb_rec
#define qti_acct_rec qti_rec.lqr_acct_rec
#define qti_slv_rec qti_rec.lqr_slv_rec
#define LQUOTA_BUMP_VER 0x1
#define LQUOTA_SET_VER 0x2
#define req_is_acq(flags) ((flags & QUOTA_DQACQ_FL_ACQ) != 0)
#define req_is_preacq(flags) ((flags & QUOTA_DQACQ_FL_PREACQ) != 0)
#define req_is_rel(flags) ((flags & QUOTA_DQACQ_FL_REL) != 0)
#define req_has_rep(flags) ((flags & QUOTA_DQACQ_FL_REPORT) != 0)
#define LQUOTA_DEBUG(lqe, fmt, a...) ((void)0)
#define LQUOTA_ERROR(lqe, fmt, a...) ((void)0)
#define LQUOTA_WARN(lqe, fmt, a...) ((void)0)
#define LQUOTA_CONSOLE(lqe, fmt, a...) ((void)0)
#define lquota_lqe_debug(cdls, level, lqe, file, func, line, fmt, a...) ((void)0)
Typedefs
typedef int(* lquota_disk_slv_cb_t)(const struct lu_env *, struct lu_fid *, char *, struct lu_fid *, void *)
Enumerations
enum lquota_local_oid { LQUOTA_USR_OID = 1UL, LQUOTA_GRP_OID = 2UL, LQUOTA_GENERATED_OID = 4096UL }
Functions
static void lqe_getref (struct lquota_entry *lqe)
static void lqe_putref (struct lquota_entry *lqe)
static int lqe_is_master (struct lquota_entry *lqe)
static void lqe_write_lock (struct lquota_entry *lqe)
static void lqe_write_unlock (struct lquota_entry *lqe)
static void lqe_read_lock (struct lquota_entry *lqe)
static void lqe_read_unlock (struct lquota_entry *lqe)
static struct lquota_thread_info * lquota_info (const struct lu_env *env)
struct dt_object * acct_obj_lookup (const struct lu_env *, struct dt_device *, int)
Look-up accounting object to collect space usage information for user or group.
void lquota_generate_fid (struct lu_fid *, int, int, int)
Helper routine returning the FID associated with the global index storing quota settings for the storage pool , resource type and the quota type .
int lquota_extract_fid (const struct lu_fid *, int *, int *, int *)
Helper routine used to extract pool ID, pool type and quota type from a given FID.
struct dt_index_features * glb_idx_feature (struct lu_fid *)
struct lquota_site * lquota_site_alloc (const struct lu_env *, void *, bool, short, struct lquota_entry_operations *)
void lquota_site_free (const struct lu_env *, struct lquota_site *)
struct lquota_entry * lqe_locate (const struct lu_env *, struct lquota_site *, union lquota_id *)
struct dt_object * lquota_disk_dir_find_create (const struct lu_env *, struct dt_device *, struct dt_object *, const char *)
struct dt_object * lquota_disk_glb_find_create (const struct lu_env *, struct dt_device *, struct dt_object *, struct lu_fid *, bool)
struct dt_object * lquota_disk_slv_find_create (const struct lu_env *, struct dt_device *, struct dt_object *, struct lu_fid *, struct obd_uuid *, bool)
int lquota_disk_for_each_slv (const struct lu_env *, struct dt_object *, struct lu_fid *, lquota_disk_slv_cb_t, void *)
struct dt_object * lquota_disk_slv_find (const struct lu_env *, struct dt_device *, struct dt_object *, const struct lu_fid *, struct obd_uuid *)
int lquota_disk_read (const struct lu_env *, struct dt_object *, union lquota_id *, struct dt_rec *)
int lquota_disk_declare_write (const struct lu_env *, struct thandle *, struct dt_object *, union lquota_id *)
int lquota_disk_write (const struct lu_env *, struct thandle *, struct dt_object *, union lquota_id *, struct dt_rec *, __u32, __u64 *)
int lquota_disk_update_ver (const struct lu_env *, struct dt_device *, struct dt_object *, __u64)
int lquota_disk_write_glb (const struct lu_env *, struct dt_object *, __u64, struct lquota_glb_rec *)
int qmt_glb_init (void)
void qmt_glb_fini (void)
int qsd_glb_init (void)
void qsd_glb_fini (void)
Variables
struct kmem_cache * lqe_kmem
struct lu_context_key lquota_thread_key
struct file_operations lprocfs_quota_seq_fops
Define Documentation
#define lqe_acq_rc u.se.lse_acq_rc
Definition at line 212 of file lquota_internal.h.
#define lqe_acq_time u.se.lse_acq_time
Definition at line 213 of file lquota_internal.h.
#define lqe_adjust_time u.se.lse_adjust_time
Definition at line 210 of file lquota_internal.h.
#define lqe_edquot_time u.se.lse_edquot_time
Definition at line 214 of file lquota_internal.h.
#define lqe_gracetime u.me.lme_gracetime
Definition at line 197 of file lquota_internal.h.
#define lqe_hardlimit u.me.lme_hardlimit
Definition at line 195 of file lquota_internal.h.
#define lqe_lock u.se.lse_lock
Definition at line 208 of file lquota_internal.h.
#define lqe_lockh u.se.lse_lockh
Definition at line 211 of file lquota_internal.h.
#define lqe_may_rel u.me.lme_may_rel
Definition at line 200 of file lquota_internal.h.
#define lqe_pending_rel u.se.lse_pending_rel
Definition at line 205 of file lquota_internal.h.
#define lqe_pending_req u.se.lse_pending_req
Definition at line 206 of file lquota_internal.h.
#define lqe_pending_write u.se.lse_pending_write
Definition at line 203 of file lquota_internal.h.
#define lqe_qtune u.se.lse_qtune
Definition at line 202 of file lquota_internal.h.
Referenced by qsd_calc_adjust().
#define lqe_revoke_time u.me.lme_revoke_time
Definition at line 198 of file lquota_internal.h.
#define lqe_sem u.me.lme_sem
Definition at line 199 of file lquota_internal.h.
#define lqe_softlimit u.me.lme_softlimit
Definition at line 196 of file lquota_internal.h.
#define lqe_usage u.se.lse_usage
Definition at line 209 of file lquota_internal.h.
#define lqe_waiters u.se.lse_waiters
Definition at line 207 of file lquota_internal.h.
#define lqe_waiting_write u.se.lse_waiting_write
Definition at line 204 of file lquota_internal.h.
#define LQUOTA_BUMP_VER 0x1
Definition at line 301 of file lquota_internal.h.
#define LQUOTA_BUMP_VER 0x1
Definition at line 301 of file lquota_internal.h.
Referenced by lquota_disk_write(), qmt_dqacq0(), qmt_glb_write(), and qmt_set().
#define LQUOTA_CONSOLE (lqe, fmt, a...) ((void)0)
Definition at line 362 of file lquota_internal.h.
#define LQUOTA_DEBUG (lqe, fmt, a...) ((void)0)
Definition at line 359 of file lquota_internal.h.
Referenced by lqe_init(), lqe_read(), qmt_adjust_edquot(), qmt_adjust_qunit(), qmt_dqacq0(), qmt_get(), qmt_glb_lock_notify(), qmt_glb_write(), qmt_id_lock_glimpse(), qmt_lqe_read(), qmt_lvbo_init(), qmt_lvbo_update(), qmt_set(), qmt_slv_read(), qmt_slv_write(), qmt_trans_start(), qmt_trans_start_with_slv(), qsd_acquire(), qsd_acquire_remote(), qsd_adjust(), qsd_calc_adjust(), qsd_id_blocking_ast(), qsd_id_glimpse_ast(), qsd_lqe_read(), qsd_op_begin0(), qsd_ready(), qsd_refresh_usage(), qsd_reint_qid(), qsd_req_completion(), qsd_request_enter(), qsd_set_qunit(), and qsd_update_lqe().
#define LQUOTA_ERROR (lqe, fmt, a...) ((void)0)
Definition at line 360 of file lquota_internal.h.
Referenced by lqe_iter_cb(), qmt_adjust_qunit(), qmt_dqacq0(), qmt_glb_write(), qmt_lqe_read(), qmt_lvbo_update(), qmt_slv_read(), qmt_slv_write(), qmt_trans_start_with_slv(), qsd_add_deferred(), qsd_lqe_read(), qsd_op_begin0(), qsd_process_upd(), qsd_refresh_usage(), qsd_req_completion(), qsd_request_enter(), and qsd_request_exit().
#define LQUOTA_LEAST_QUNIT (type) (type == LQUOTA_RES_MD ? (1 << 10) : toqb(OFD_MAX_BRW_SIZE))
Definition at line 279 of file lquota_internal.h.
Referenced by qmt_pool_alloc(), and qsd_prepare().
#define lquota_lqe_debug (cdls, level, lqe, file, func, line, fmt, a...) ((void)0)
Definition at line 363 of file lquota_internal.h.
#define LQUOTA_NAME_MAX 52
Definition at line 43 of file lquota_internal.h.
Referenced by lquota_disk_for_each_slv().
#define LQUOTA_OVER_FL (type) (type == USRQUOTA ? QUOTA_FL_OVER_USRQUOTA : QUOTA_FL_OVER_GRPQUOTA)
Definition at line 282 of file lquota_internal.h.
Referenced by qsd_op_begin0().
#define LQUOTA_SET_VER 0x2
Definition at line 302 of file lquota_internal.h.
#define LQUOTA_SET_VER 0x2
Definition at line 302 of file lquota_internal.h.
Referenced by lquota_disk_write(), qmt_glb_write(), and qsd_update_index().
#define LQUOTA_WARN (lqe, fmt, a...) ((void)0)
Definition at line 361 of file lquota_internal.h.
Referenced by qsd_add_deferred(), and qsd_upd_add().
#define QIF_BFLAGS (QIF_SPACE | QIF_BTIME | QIF_BLIMITS)
Definition at line 38 of file lquota_internal.h.
Referenced by qmt_quotactl().
#define QIF_IFLAGS (QIF_INODES | QIF_ITIME | QIF_ILIMITS)
Definition at line 37 of file lquota_internal.h.
Referenced by qmt_quotactl().
#define qti_acct_rec qti_rec.lqr_acct_rec
Definition at line 298 of file lquota_internal.h.
#define qti_glb_rec qti_rec.lqr_glb_rec
Definition at line 297 of file lquota_internal.h.
#define qti_slv_rec qti_rec.lqr_slv_rec
Definition at line 299 of file lquota_internal.h.
#define QTYPE_NAME (qtype) ((qtype) == USRQUOTA ? "usr" : "grp")
Definition at line 34 of file lquota_internal.h.
Referenced by acct_obj_lookup(), qmt_pool_prepare(), qpi_state_seq_show(), qsd_glb_blocking_ast(), qsd_lqe_debug(), qsd_prepare(), qsd_qtype_init(), and quota_obj_lookup().
#define req_has_rep (flags) ((flags & QUOTA_DQACQ_FL_REPORT) != 0)
Definition at line 324 of file lquota_internal.h.
Referenced by qmt_dqacq0(), and qsd_adjust().
#define req_is_acq (flags) ((flags & QUOTA_DQACQ_FL_ACQ) != 0)
Definition at line 321 of file lquota_internal.h.
Referenced by qmt_dqacq(), qmt_dqacq0(), qsd_adjust(), and qsd_req_completion().
#define req_is_preacq (flags) ((flags & QUOTA_DQACQ_FL_PREACQ) != 0)
Definition at line 322 of file lquota_internal.h.
Referenced by qmt_dqacq(), qmt_dqacq0(), qsd_adjust(), and qsd_req_completion().
#define req_is_rel (flags) ((flags & QUOTA_DQACQ_FL_REL) != 0)
Definition at line 323 of file lquota_internal.h.
Referenced by qmt_dqacq(), qmt_dqacq0(), qsd_adjust(), and qsd_req_completion().
#define RES_NAME (res) ((res) == LQUOTA_RES_MD ? "md" : "dt")
Definition at line 35 of file lquota_internal.h.
Referenced by qmt_lqe_debug(), qmt_pool_alloc(), qmt_pool_prepare(), and qpi_state_seq_show().
Typedef Documentation
typedef int(* lquota_disk_slv_cb_t)(const struct lu_env *, struct lu_fid *, char *, struct lu_fid *, void *)
Definition at line 396 of file lquota_internal.h.
Enumeration Type Documentation
enum lquota_local_oid
Enumerator:
LQUOTA_USR_OID
LQUOTA_GRP_OID
LQUOTA_GENERATED_OID
Definition at line 46 of file lquota_internal.h.
Function Documentation
struct dt_object* acct_obj_lookup (const struct lu_env * env, struct dt_device * dev, int type) [read]
Look-up accounting object to collect space usage information for user or group.
Parameters:
env - is the environment passed by the caller
dev - is the dt_device storing the accounting object
type - is the quota type, either USRQUOTA or GRPQUOTA
Definition at line 65 of file lquota_lib.c.
References ACCT_GROUP_OID, ACCT_USER_OID, CERROR, dt_device::dd_lu_dev, dt_object::do_index_ops, dt_object_operations::do_index_try, dt_object::do_lu, dt_object::do_ops, dt_acct_features, dt_locate(), dt_object_exists(), ENTRY, lu_device::ld_obd, lquota_info(), lu_local_obj_fid(), lu_object_put(), obd_device::obd_name, lquota_thread_info::qti_fid, QTYPE_NAME, and RETURN.
Referenced by lquotactl_slv(), and qsd_qtype_init().
struct dt_index_features* glb_idx_feature (struct lu_fid *) [read]
static void lqe_getref (struct lquota_entry * lqe) [inline, static]
Definition at line 222 of file lquota_internal.h.
References LASSERT, and lquota_entry::lqe_ref.
Referenced by lqe_hash_get(), qmt_id_lock_notify(), qmt_intent_policy(), qmt_lvbo_fill(), qmt_lvbo_update(), qmt_pool_lqe_lookup(), qsd_acquire_remote(), qsd_adjust(), qsd_adjust_schedule(), qsd_id_ast_data_get(), qsd_intent_lock(), and qsd_upd_alloc().
static int lqe_is_master (struct lquota_entry * lqe) [inline, static]
Definition at line 236 of file lquota_internal.h.
References lquota_entry::lqe_site, and lquota_site::lqs_is_mst.
Referenced by lqe2qpi(), lqe2qqi(), lqe_is_locked(), lqe_iter_cb(), lqe_read_lock(), lqe_read_unlock(), lqe_write_lock(), lqe_write_unlock(), qmt_glb_write(), qmt_lqe_init(), qmt_lqe_read(), qmt_slv_read(), qmt_slv_write(), qmt_trans_start_with_slv(), qsd_lqe_init(), qsd_lqe_read(), and qsd_update_lqe().
struct lquota_entry* lqe_locate (const struct lu_env * , struct lquota_site * , union lquota_id *) [read]
Definition at line 313 of file lquota_entry.c.
References CERROR, cfs_hash_findadd_unique(), cfs_hash_lookup(), ENTRY, GOTO, cfs_hash::hs_name, INIT_LIST_HEAD, LASSERT, LPU64, lqe_init(), lqe_kmem, lqe_putref(), lqe_read(), lquota_entry::lqe_uptodate, lquota_site::lqs_hash, OBD_SLAB_ALLOC_PTR_GFP, lquota_id::qid_uid, and RETURN.
Referenced by qmt_pool_lqe_lookup(), qmt_pool_prepare(), qsd_op_adjust(), qsd_op_begin0(), qsd_process_upd(), qsd_reconciliation(), and qsd_reint_qid().
static void lqe_putref (struct lquota_entry * lqe) [inline, static]
Definition at line 228 of file lquota_internal.h.
References LASSERT, lqe_kmem, lquota_entry::lqe_ref, and OBD_SLAB_FREE_PTR.
Referenced by lqe_hash_put_locked(), lqe_locate(), qmt_dqacq(), qmt_get(), qmt_id_lock_notify(), qmt_intent_policy(), qmt_lvbo_fill(), qmt_lvbo_free(), qmt_lvbo_update(), qmt_pool_free(), qmt_reba_thread(), qmt_set(), qsd_adjust_schedule(), qsd_cleanup_adjust(), qsd_id_ast_data_get(), qsd_id_blocking_ast(), qsd_id_glimpse_ast(), qsd_op_adjust(), qsd_op_begin0(), qsd_op_end0(), qsd_pending_updates(), qsd_process_upd(), qsd_reconciliation(), qsd_reint_qid(), qsd_req_completion(), qsd_upd_free(), and qsd_upd_thread().
static void lqe_read_lock (struct lquota_entry * lqe) [inline, static]
Definition at line 258 of file lquota_internal.h.
References lqe_is_master().
Referenced by qmt_get(), qsd_entry_iter_cb(), qsd_op_adjust(), and qsd_op_begin0().
static void lqe_read_unlock (struct lquota_entry * lqe) [inline, static]
Definition at line 266 of file lquota_internal.h.
References lqe_is_master().
Referenced by qmt_get(), qsd_entry_iter_cb(), qsd_op_adjust(), and qsd_op_begin0().
static void lqe_write_lock (struct lquota_entry * lqe) [inline, static]
Definition at line 242 of file lquota_internal.h.
References lqe_is_master().
Referenced by qmt_dqacq0(), qmt_id_lock_glimpse(), qmt_set(), qsd_acquire_local(), qsd_acquire_remote(), qsd_adjust(), qsd_id_blocking_ast(), qsd_id_glimpse_ast(), qsd_id_lock_cancel(), qsd_op_begin0(), qsd_op_end0(), and qsd_req_completion().
static void lqe_write_unlock (struct lquota_entry * lqe) [inline, static]
Definition at line 250 of file lquota_internal.h.
References lqe_is_master().
Referenced by lqe_is_locked(), qmt_dqacq0(), qmt_id_lock_glimpse(), qmt_set(), qsd_acquire_local(), qsd_acquire_remote(), qsd_adjust(), qsd_id_blocking_ast(), qsd_id_glimpse_ast(), qsd_id_lock_cancel(), qsd_op_begin0(), qsd_op_end0(), and qsd_req_completion().
int lquota_disk_declare_write (const struct lu_env * , struct thandle * , struct dt_object * , union lquota_id *)
Definition at line 589 of file lquota_disk.c.
References dt_object::do_index_ops, dt_declare_delete(), dt_declare_insert(), dt_declare_version_set(), dt_key, dt_object_exists(), ENTRY, LASSERT, lquota_info(), lquota_id::qid_uid, lquota_thread_info::qti_rec, and RETURN.
Referenced by qmt_trans_start_with_slv(), and qsd_update_index().
struct dt_object* lquota_disk_dir_find_create (const struct lu_env * , struct dt_device * , struct dt_object * , const char *) [read]
Definition at line 158 of file lquota_disk.c.
References dt_device::dd_lu_dev, dt_object::do_lu, dt_locate(), dt_locate_at(), dt_root_get(), dt_try_as_dir(), ENTRY, EXIT, GOTO, lu_device::ld_site, lu_object::lo_header, local_file_find_or_create(), local_oid_storage_fini(), local_oid_storage_init(), lu_object_header::loh_fid, lquota_info(), lu_site::ls_top_dev, lu_local_name_obj_fid(), lu_object_get(), lu_object_put(), lu_object_put_nocache(), lquota_thread_info::qti_fid, and RETURN.
Referenced by qmt_device_prepare(), qmt_pool_prepare(), and qsd_prepare().
int lquota_disk_for_each_slv (const struct lu_env * , struct dt_object * , struct lu_fid * , lquota_disk_slv_cb_t , void *)
Definition at line 461 of file lquota_disk.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, dt_key, dt_lookup_dir(), ENTRY, lu_fid::f_oid, lu_fid::f_seq, FID_SEQ_QUOTA, dt_index_operations::dt_it_ops::init, lquota_info(), LQUOTA_NAME_MAX, name, OBD_ALLOC, OBD_FREE, lquota_thread_info::qti_buf, lquota_thread_info::qti_fid, and RETURN.
Referenced by qmt_pool_prepare().
struct dt_object* lquota_disk_glb_find_create (const struct lu_env * , struct dt_device * , struct dt_object * , struct lu_fid * , bool) [read]
Definition at line 234 of file lquota_disk.c.
References CDEBUG, CERROR, D_QUOTA, dt_device::dd_lu_dev, DFID, dt_object::do_index_ops, dt_object_operations::do_index_try, dt_object::do_lu, dt_object::do_ops, dt_quota_glb_features, ENTRY, lu_fid::f_oid, lu_device::ld_obd, local_index_find_or_create_with_fid(), lquota_disk_find_create(), lquota_info(), LQUOTA_MODE, lu_local_name_obj_fid(), lu_object_fid(), lu_object_put(), obd_device::obd_name, PFID, lquota_thread_info::qti_buf, lquota_thread_info::qti_fid, and RETURN.
Referenced by qmt_pool_prepare(), and qsd_qtype_init().
int lquota_disk_read (const struct lu_env * , struct dt_object * , union lquota_id * , struct dt_rec *)
Definition at line 562 of file lquota_disk.c.
References dt_object::do_index_ops, dt_key, dt_lookup(), dt_object_exists(), dt_read_lock(), dt_read_unlock(), ENTRY, LASSERT, lquota_id::qid_uid, and RETURN.
Referenced by qmt_lqe_read(), qmt_slv_read(), qsd_lqe_read(), and qsd_refresh_usage().
struct dt_object* lquota_disk_slv_find (const struct lu_env * , struct dt_device * , struct dt_object * , const struct lu_fid * , struct obd_uuid *) [read]
Definition at line 307 of file lquota_disk.c.
References CDEBUG, CERROR, D_QUOTA, dt_device::dd_lu_dev, dt_object::do_index_ops, dt_object_operations::do_index_try, dt_object::do_lu, dt_object::do_ops, dt_locate(), dt_lookup_dir(), dt_quota_slv_features, ENTRY, LASSERT, lu_device::ld_obd, lquota_disk_slv_filename(), lquota_info(), lu_object_put(), obd_device::obd_name, obd_uuid2str(), lquota_thread_info::qti_buf, lquota_thread_info::qti_fid, and RETURN.
Referenced by qmt_dqacq0(), and qmt_pool_new_conn().
struct dt_object* lquota_disk_slv_find_create (const struct lu_env * , struct dt_device * , struct dt_object * , struct lu_fid * , struct obd_uuid * , bool) [read]
Definition at line 375 of file lquota_disk.c.
References CDEBUG, CERROR, D_QUOTA, dt_device::dd_lu_dev, DFID, dt_object::do_index_ops, dt_object_operations::do_index_try, dt_object::do_lu, dt_object::do_ops, dt_quota_slv_features, ENTRY, lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, FID_SEQ_QUOTA, LASSERT, lu_device::ld_obd, local_index_find_or_create_with_fid(), lquota_disk_find_create(), lquota_disk_slv_filename(), lquota_extract_fid(), LQUOTA_GENERATED_OID, LQUOTA_GRP_OID, lquota_info(), LQUOTA_MODE, LQUOTA_USR_OID, lu_object_fid(), lu_object_put(), obd_device::obd_name, obd_uuid2str(), PFID, lquota_thread_info::qti_buf, lquota_thread_info::qti_fid, and RETURN.
Referenced by qmt_pool_new_conn(), and qsd_qtype_init().
int lquota_disk_update_ver (const struct lu_env * , struct dt_device * , struct dt_object * , __u64)
Definition at line 703 of file lquota_disk.c.
References dt_declare_version_set(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_version_set(), ENTRY, EXIT, GOTO, RETURN, and thandle::th_sync.
Referenced by qmt_pool_prepare(), and qsd_write_version().
int lquota_disk_write (const struct lu_env * , struct thandle * , struct dt_object * , union lquota_id * , struct dt_rec * , __u32 , __u64 *)
Definition at line 633 of file lquota_disk.c.
References DFID, dt_object::do_index_ops, dt_object::do_lu, dt_delete(), dt_insert(), dt_key, dt_lookup(), dt_object_exists(), dt_version_get(), dt_version_set(), dt_write_lock(), dt_write_unlock(), ENTRY, EXIT, GOTO, LASSERT, LASSERTF, LQUOTA_BUMP_VER, lquota_info(), LQUOTA_SET_VER, lu_object_fid(), PFID, lquota_id::qid_uid, and lquota_thread_info::qti_rec.
Referenced by qmt_glb_write(), qmt_slv_write(), and qsd_update_index().
int lquota_disk_write_glb (const struct lu_env * , struct dt_object * , __u64 , struct lquota_glb_rec *)
Definition at line 738 of file lquota_disk.c.
References dt_object::do_lu, dt_declare_delete(), dt_declare_insert(), dt_delete(), dt_insert(), dt_key, dt_lookup(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), ENTRY, GOTO, lu_object::lo_dev, lu2dt_dev(), OBD_ALLOC_PTR, OBD_FREE_PTR, and RETURN.
Referenced by qmt_pool_prepare().
int lquota_extract_fid (const struct lu_fid * , int * , int * , int *)
Helper routine used to extract pool ID, pool type and quota type from a given FID.
Definition at line 256 of file lquota_lib.c.
References ENTRY, lu_fid::f_oid, lu_fid::f_seq, FID_SEQ_QUOTA_GLB, LQUOTA_LAST_RES, LQUOTA_TYPE_MAX, LQUOTA_TYPE_USR, and RETURN.
Referenced by lquota_disk_slv_find_create(), qmt_dqacq(), qmt_lvbo_init(), and qmt_pool_new_conn().
void lquota_generate_fid (struct lu_fid * , int , int , int)
Helper routine returning the FID associated with the global index storing quota settings for the storage pool , resource type and the quota type .
Definition at line 240 of file lquota_lib.c.
References lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, FID_SEQ_QUOTA_GLB, LQUOTA_TYPE_GRP, and LQUOTA_TYPE_USR.
Referenced by qmt_glb_lock_notify(), qmt_id_lock_glimpse(), qmt_pool_prepare(), and qsd_qtype_init().
static struct lquota_thread_info* lquota_info (const struct lu_env * env) [static, read]
Definition at line 308 of file lquota_internal.h.
References LASSERT, lu_env::le_ctx, lquota_thread_key, lu_context_key_get(), and lu_env_refill().
Referenced by acct_obj_lookup(), lquota_disk_declare_write(), lquota_disk_dir_find_create(), lquota_disk_find_create(), lquota_disk_for_each_slv(), lquota_disk_glb_find_create(), lquota_disk_slv_find(), lquota_disk_slv_find_create(), lquota_disk_write(), lquotactl_slv(), and quota_obj_lookup().
struct lquota_site* lquota_site_alloc (const struct lu_env * , void * , bool , short , struct lquota_entry_operations *) [read]
Definition at line 198 of file lquota_entry.c.
References CFS_HASH_BIGNAME, cfs_hash_create(), CFS_HASH_DEFAULT, CFS_HASH_MAX_THETA, CFS_HASH_MIN_THETA, ENTRY, HASH_LQE_BKT_BITS, HASH_LQE_MAX_BITS, hash_lqs_cur_bits, LASSERT, lquota_site::lqs_hash, lquota_site::lqs_is_mst, lquota_site::lqs_ops, lquota_site::lqs_parent, lquota_site::lqs_qtype, OBD_ALLOC_PTR, OBD_FREE_PTR, and RETURN.
Referenced by qmt_pool_prepare(), and qsd_qtype_init().
void lquota_site_free (const struct lu_env * , struct lquota_site *)
Definition at line 245 of file lquota_entry.c.
References cfs_hash_putref(), lqe_cleanup(), lquota_site::lqs_hash, lquota_site::lqs_parent, and OBD_FREE_PTR.
Referenced by qmt_pool_free(), and qsd_qtype_fini().
void qmt_glb_fini (void)
Definition at line 480 of file qmt_dev.c.
References class_unregister_type(), and LUSTRE_QMT_NAME.
Referenced by lquota_exit(), and lquota_init().
int qmt_glb_init (void)
Definition at line 469 of file qmt_dev.c.
References class_register_type(), ENTRY, LUSTRE_QMT_NAME, and RETURN.
Referenced by lquota_init().
void qsd_glb_fini (void)
Definition at line 827 of file qsd_lib.c.
References lu_context_key_degister(), lu_kmem_fini(), lustre_register_quota_process_config(), and qsd_thread_key.
Referenced by lquota_exit().
int qsd_glb_init (void)
Definition at line 809 of file qsd_lib.c.
References lu_context_key_register(), lu_kmem_init(), lustre_register_quota_process_config(), qsd_process_config(), and qsd_thread_key.
Referenced by lquota_init().
Variable Documentation
struct file_operations lprocfs_quota_seq_fops
Referenced by qmt_pool_prepare(), and qsd_qtype_init().
struct kmem_cache* lqe_kmem
Definition at line 39 of file lquota_lib.c.
Referenced by lqe_locate(), and lqe_putref().
struct lu_context_key lquota_thread_key
Referenced by lquota_exit(), lquota_info(), and lquota_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.