Lustre: lustre/utils/lr_reader.c File Reference
lustre/utils/lr_reader.c File Reference
#include <errno.h>
#include <limits.h>
#include <stdbool.h>
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <fcntl.h>
#include <stdarg.h>
#include <mntent.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/mount.h>
#include <string.h>
#include <getopt.h>
#include <lustre_disk.h>
#include <lustre_ver.h>
Functions
int run_command (char *cmd, size_t cmdsz)
void display_usage (void)
int main (int argc, char *const argv[])
Variables
char * progname
static struct option const longopts []
Function Documentation
void display_usage (void)
Definition at line 118 of file lr_reader.c.
References progname.
Referenced by main().
int main (int argc, char *const argv[])
Definition at line 129 of file lr_reader.c.
References cmd, display_usage(), LAST_RCVD, lsd_client_data::lcd_generation, lsd_client_data::lcd_last_close_data, lsd_client_data::lcd_last_close_result, lsd_client_data::lcd_last_close_transno, lsd_client_data::lcd_last_close_xid, lsd_client_data::lcd_last_data, lsd_client_data::lcd_last_result, lsd_client_data::lcd_last_transno, lsd_client_data::lcd_last_xid, lsd_client_data::lcd_uuid, le16_to_cpu, le32_to_cpu, le64_to_cpu, longopts, lsd_reply_data::lrd_client_gen, lsd_reply_data::lrd_data, lsd_reply_data::lrd_result, lsd_reply_data::lrd_transno, lsd_reply_data::lrd_xid, lsd_reply_header::lrh_header_size, LRH_MAGIC, lsd_reply_header::lrh_magic, lsd_reply_header::lrh_reply_size, lr_server_data::lsd_client_size, lr_server_data::lsd_client_start, lr_server_data::lsd_feature_compat, lr_server_data::lsd_feature_incompat, lr_server_data::lsd_feature_rocompat, lr_server_data::lsd_last_transno, lr_server_data::lsd_mount_count, lr_server_data::lsd_osd_index, lr_server_data::lsd_uuid, optind, progname, REPLY_DATA, ret, and run_command().
int run_command (char * cmd, size_t cmdsz)
Definition at line 79 of file lr_reader.c.
References buf.
Referenced by ldiskfs_enable_quota(), ldiskfs_label_lustre(), ldiskfs_make_lustre(), ldiskfs_read_ldd(), loop_cleanup(), loop_setup(), main(), and zfs_make_lustre().
Variable Documentation
struct option const longopts[] [static]
Initial value:
 {
        { "help", no_argument, 0, 'h' },
        { "client", no_argument, 0, 'c' },
        { "reply", no_argument, 0, 'r' },
        { 0, 0, 0, 0}
}
Definition at line 70 of file lr_reader.c.
char* progname
Definition at line 69 of file lr_reader.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.