Lustre: lnet/utils/lst.c File Reference
lnet/utils/lst.c File Reference
#include <errno.h>
#include <getopt.h>
#include <inttypes.h>
#include <pwd.h>
#include <unistd.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <time.h>
#include <libcfs/list.h>
#include <libcfs/util/ioctl.h>
#include <libcfs/util/parser.h>
#include <lnet/lnetctl.h>
#include <lnet/lnetst.h>
#include <lnet/lnet.h>
#include <utils/obdctl.h>
Data Structures
struct list_string
struct lst_stat_req_param_t
struct lst_srpc_stat_result
struct lst_lnet_stat_result_t
Defines
#define LST_NODES_TITLE "\tACTIVE\tBUSY\tDOWN\tUNKNOWN\tTOTAL\n"
#define LST_LNET_AVG 0
#define LST_LNET_MIN 1
#define LST_LNET_MAX 2
Typedefs
typedef struct list_string lstr_t
Functions
lstr_t * alloc_lstr (int sz)
void free_lstr (lstr_t *lstr)
void free_lstrs (lstr_t **list)
void new_lstrs (lstr_t **list, char *prefix, char *postfix, int lo, int hi, int stride)
int expand_lstr (lstr_t **list, lstr_t *l)
int expand_strs (char *str, lstr_t **head)
int lst_parse_nids (char *str, int *countp, lnet_process_id_t **idspp)
char * lst_node_state2str (int state)
int lst_node_str2state (char *str)
char * lst_test_type2name (int type)
int lst_test_name2type (char *name)
void lst_print_usage (char *cmd)
void lst_print_error (char *sub, const char *def_format,...)
void lst_free_rpcent (struct list_head *head)
void lst_reset_rpcent (struct list_head *head)
int lst_alloc_rpcent (struct list_head *head, int count, int offset)
void lst_print_transerr (struct list_head *head, char *optstr)
int lst_info_batch_ioctl (char *batch, int test, int server, lstcon_test_batch_ent_t *entp, int *idxp, int *ndentp, lstcon_node_ent_t *dentsp)
int lst_info_group_ioctl (char *name, lstcon_ndlist_ent_t *gent, int *idx, int *count, lstcon_node_ent_t *dents)
int lst_query_batch_ioctl (char *batch, int test, int server, int timeout, struct list_head *head)
int lst_ioctl (unsigned int opc, void *buf, int len)
int lst_new_session_ioctl (char *name, int timeout, int force, lst_sid_t *sid)
int jt_lst_new_session (int argc, char **argv)
int lst_session_info_ioctl (char *name, int len, int *key, unsigned *featp, lst_sid_t *sid, lstcon_ndlist_ent_t *ndinfo)
int jt_lst_show_session (int argc, char **argv)
int lst_end_session_ioctl (void)
int jt_lst_end_session (int argc, char **argv)
int lst_ping_ioctl (char *str, int type, int timeout, int count, lnet_process_id_t *ids, struct list_head *head)
int lst_get_node_count (int type, char *str, int *countp, lnet_process_id_t **idspp)
int jt_lst_ping (int argc, char **argv)
int lst_add_nodes_ioctl (char *name, int count, lnet_process_id_t *ids, unsigned *featp, struct list_head *resultp)
int lst_del_group_ioctl (char *name)
int lst_del_group (char *grp_name)
int lst_add_group_ioctl (char *name)
int jt_lst_add_group (int argc, char **argv)
int jt_lst_del_group (int argc, char **argv)
int lst_update_group_ioctl (int opc, char *name, int clean, int count, lnet_process_id_t *ids, struct list_head *resultp)
int jt_lst_update_group (int argc, char **argv)
int lst_list_group_ioctl (int len, char *name, int idx)
int lst_list_group_all (void)
int jt_lst_list_group (int argc, char **argv)
int lst_stat_ioctl (char *name, int count, lnet_process_id_t *idsp, int timeout, struct list_head *resultp)
static void lst_stat_req_param_free (lst_stat_req_param_t *srp)
static int lst_stat_req_param_alloc (char *name, lst_stat_req_param_t **srpp, int save_old)
static float lst_lnet_stat_value (int bw, int send, int off)
static void lst_timeval_diff (struct timeval *tv1, struct timeval *tv2, struct timeval *df)
void lst_cal_lnet_stat (float delta, lnet_counters_t *lnet_new, lnet_counters_t *lnet_old)
void lst_print_lnet_stat (char *name, int bwrt, int rdwr, int type)
void lst_print_stat (char *name, struct list_head *resultp, int idx, int lnet, int bwrt, int rdwr, int type)
int jt_lst_stat (int argc, char **argv)
int jt_lst_show_error (int argc, char **argv)
int lst_add_batch_ioctl (char *name)
int jt_lst_add_batch (int argc, char **argv)
int lst_start_batch_ioctl (char *name, int timeout, struct list_head *resultp)
int jt_lst_start_batch (int argc, char **argv)
int lst_stop_batch_ioctl (char *name, int force, struct list_head *resultp)
int jt_lst_stop_batch (int argc, char **argv)
int lst_list_batch_ioctl (int len, char *name, int index)
int lst_list_batch_all (void)
int lst_list_tsb_nodes (char *batch, int test, int server, int count, int active, int invalid)
int jt_lst_list_batch (int argc, char **argv)
void lst_print_tsb_verbose (struct list_head *head, int active, int idle, int error)
int jt_lst_query_batch (int argc, char **argv)
int lst_parse_distribute (char *dstr, int *dist, int *span)
int lst_get_bulk_param (int argc, char **argv, lst_test_bulk_param_t *bulk)
int lst_get_test_param (char *test, int argc, char **argv, void **param, int *plen)
int lst_add_test_ioctl (char *batch, int type, int loop, int concur, int dist, int span, char *sgrp, char *dgrp, void *param, int plen, int *retp, struct list_head *resultp)
int jt_lst_add_test (int argc, char **argv)
int lst_initialize (void)
int main (int argc, char **argv)
Variables
lst_sid_t LST_INVALID_SID = {LNET_NID_ANY, -1}
static lst_sid_t session_id
static int session_key
static unsigned session_features = LST_FEATS_MASK
static lstcon_trans_stat_t trans_stat
static int alloc_count = 0
static int alloc_nob = 0
lst_lnet_stat_result_t lnet_stat_result
static command_t lst_cmdlist []
Define Documentation
#define LST_LNET_AVG 0
Definition at line 1596 of file lst.c.
#define LST_LNET_MAX 2
Definition at line 1598 of file lst.c.
#define LST_LNET_MIN 1
Definition at line 1597 of file lst.c.
#define LST_NODES_TITLE "\tACTIVE\tBUSY\tDOWN\tUNKNOWN\tTOTAL\n"
Definition at line 1348 of file lst.c.
Referenced by jt_lst_list_batch(), and jt_lst_list_group().
Typedef Documentation
typedef struct list_string lstr_t
Function Documentation
lstr_t* alloc_lstr (int sz)
Definition at line 82 of file lst.c.
References alloc_count, alloc_nob, list_string::lstr_str, list_string::lstr_sz, and offsetof.
Referenced by expand_strs(), and new_lstrs().
int expand_lstr (lstr_t ** list, lstr_t * l)
Definition at line 140 of file lst.c.
References free_lstr(), list_string::lstr_next, list_string::lstr_str, and new_lstrs().
Referenced by expand_strs().
int expand_strs (char * str, lstr_t ** head)
Definition at line 206 of file lst.c.
References alloc_lstr(), expand_lstr(), free_lstr(), list, list_string::lstr_next, and list_string::lstr_str.
Referenced by lst_parse_nids().
void free_lstr (lstr_t * lstr)
Definition at line 100 of file lst.c.
References alloc_count, alloc_nob, and list_string::lstr_sz.
Referenced by expand_lstr(), expand_strs(), free_lstrs(), and lst_parse_nids().
void free_lstrs (lstr_t ** list)
Definition at line 108 of file lst.c.
References free_lstr(), and list_string::lstr_next.
int jt_lst_add_batch (int argc, char ** argv)
Definition at line 2190 of file lst.c.
References lst_add_batch_ioctl(), LST_NAME_SIZE, lst_print_error(), lst_print_usage(), name, and session_key.
int jt_lst_add_group (int argc, char ** argv)
Definition at line 995 of file lst.c.
References INIT_LIST_HEAD, lst_add_group_ioctl(), lst_add_nodes_ioctl(), lst_alloc_rpcent(), lst_del_group(), lst_free_rpcent(), LST_NAME_SIZE, lst_parse_nids(), lst_print_error(), lst_print_transerr(), lst_print_usage(), name, session_features, session_key, and lstcon_trans_stat_t::trs_fwk_errno.
int jt_lst_add_test (int argc, char ** argv)
Definition at line 3080 of file lst.c.
References INIT_LIST_HEAD, lst_add_test_ioctl(), lst_alloc_rpcent(), LST_DEFAULT_BATCH, lst_free_rpcent(), lst_get_node_count(), lst_get_test_param(), LST_MAX_CONCUR, LST_OPC_GROUP, lst_parse_distribute(), lst_print_error(), lst_print_transerr(), lst_print_usage(), optarg, optind, ret, session_key, and test().
int jt_lst_del_group (int argc, char ** argv)
Definition at line 1127 of file lst.c.
References lst_del_group(), lst_print_usage(), and session_key.
int jt_lst_end_session (int argc, char ** argv)
Definition at line 682 of file lst.c.
References lst_end_session_ioctl(), lst_print_error(), lstcon_rpc_stat_failure(), lstcon_sesop_stat_failure(), session_key, lstcon_trans_stat_t::trs_fwk_errno, and lstcon_trans_stat_t::trs_rpc_errno.
int jt_lst_list_batch (int argc, char ** argv)
Definition at line 2557 of file lst.c.
References lstcon_batch_ent_t::bae_ntest, lstcon_batch_ent_t::bae_state, lst_info_batch_ioctl(), lst_list_batch_all(), lst_list_tsb_nodes(), LST_NODES_TITLE, lst_print_error(), lst_print_usage(), lst_test_type2name(), lstcon_ndlist_ent_t::nle_nactive, lstcon_ndlist_ent_t::nle_nbusy, lstcon_ndlist_ent_t::nle_ndown, lstcon_ndlist_ent_t::nle_nnode, lstcon_ndlist_ent_t::nle_nunknown, optarg, optind, session_key, lstcon_test_batch_ent_t::tbe_batch, lstcon_test_batch_ent_t::tbe_cli_nle, lstcon_test_batch_ent_t::tbe_srv_nle, lstcon_test_batch_ent_t::tbe_test, test(), lstcon_test_ent_t::tse_concur, lstcon_test_ent_t::tse_loop, lstcon_test_ent_t::tse_type, lstcon_test_batch_ent_t::u, and verbose.
int jt_lst_list_group (int argc, char ** argv)
Definition at line 1351 of file lst.c.
References libcfs_id2str(), lst_info_group_ioctl(), lst_list_group_all(), LST_NODE_ACTIVE, LST_NODE_BUSY, LST_NODE_DOWN, lst_node_state2str(), LST_NODE_UNKNOWN, LST_NODES_TITLE, lst_print_error(), lst_print_usage(), lstcon_ndlist_ent_t::nle_nactive, lstcon_ndlist_ent_t::nle_nbusy, lstcon_ndlist_ent_t::nle_ndown, lstcon_ndlist_ent_t::nle_nnode, lstcon_ndlist_ent_t::nle_nunknown, optind, session_key, and verbose.
int jt_lst_new_session (int argc, char ** argv)
Definition at line 539 of file lst.c.
References buf, LST_NAME_SIZE, lst_new_session_ioctl(), lst_print_error(), lst_print_usage(), name, optarg, optind, session_features, session_key, and timeout.
int jt_lst_ping (int argc, char ** argv)
Definition at line 784 of file lst.c.
References INIT_LIST_HEAD, libcfs_id2str(), libcfs_nid2str(), list_for_each_entry, lst_alloc_rpcent(), lst_free_rpcent(), lst_get_node_count(), LST_NAME_SIZE, LST_NODE_ACTIVE, LST_NODE_BUSY, lst_node_state2str(), LST_OPC_BATCHCLI, LST_OPC_BATCHSRV, LST_OPC_GROUP, LST_OPC_NODES, LST_OPC_SESSION, lst_ping_ioctl(), lst_print_error(), lst_print_usage(), optarg, optind, lstcon_rpc_ent_t::rpe_payload, lstcon_rpc_ent_t::rpe_peer, lstcon_rpc_ent_t::rpe_rpc_errno, lstcon_rpc_ent_t::rpe_sid, lstcon_rpc_ent_t::rpe_state, lst_sid_t::ses_nid, session_key, and timeout.
int jt_lst_query_batch (int argc, char ** argv)
Definition at line 2737 of file lst.c.
References error, INIT_LIST_HEAD, lst_alloc_rpcent(), LST_DEFAULT_BATCH, lst_free_rpcent(), lst_info_batch_ioctl(), lst_print_tsb_verbose(), lst_print_usage(), lst_query_batch_ioctl(), lstcon_rpc_stat_failure(), lstcon_rpc_stat_total(), lstcon_tsbqry_stat_failure(), lstcon_tsbqry_stat_idle(), lstcon_tsbqry_stat_run(), lstcon_ndlist_ent_t::nle_nnode, now(), optarg, optind, session_key, lstcon_test_batch_ent_t::tbe_cli_nle, lstcon_test_batch_ent_t::tbe_srv_nle, test(), timeout, and verbose.
int jt_lst_show_error (int argc, char ** argv)
Definition at line 2053 of file lst.c.
References INIT_LIST_HEAD, libcfs_id2str(), list_add_tail(), list_del(), list_empty(), list_entry, list_for_each_entry, lst_print_error(), lst_print_usage(), lst_stat_ioctl(), lst_stat_req_param_alloc(), lst_stat_req_param_free(), list_head::next, optind, lstcon_rpc_ent_t::rpe_fwk_errno, lstcon_rpc_ent_t::rpe_payload, lstcon_rpc_ent_t::rpe_peer, lstcon_rpc_ent_t::rpe_rpc_errno, and session_key.
int jt_lst_show_session (int argc, char ** argv)
Definition at line 647 of file lst.c.
References libcfs_nid2str(), LST_NAME_SIZE, lst_print_error(), lst_session_info_ioctl(), name, lstcon_ndlist_ent_t::nle_nnode, lst_sid_t::ses_nid, and lst_sid_t::ses_stamp.
int jt_lst_start_batch (int argc, char ** argv)
Definition at line 2238 of file lst.c.
References INIT_LIST_HEAD, lst_alloc_rpcent(), LST_DEFAULT_BATCH, lst_free_rpcent(), lst_get_node_count(), LST_OPC_BATCHCLI, lst_print_error(), lst_print_transerr(), lst_print_usage(), lst_start_batch_ioctl(), optarg, optind, session_key, and timeout.
int jt_lst_stat (int argc, char ** argv)
Definition at line 1879 of file lst.c.
References INIT_LIST_HEAD, list_add_tail(), list_del(), list_empty(), list_entry, list_for_each_entry, lst_print_error(), lst_print_stat(), lst_print_usage(), lst_reset_rpcent(), lst_stat_ioctl(), lst_stat_req_param_alloc(), lst_stat_req_param_free(), list_head::next, now(), optarg, optind, session_key, and timeout.
int jt_lst_stop_batch (int argc, char ** argv)
Definition at line 2341 of file lst.c.
References INIT_LIST_HEAD, lst_alloc_rpcent(), LST_DEFAULT_BATCH, lst_free_rpcent(), lst_get_node_count(), LST_OPC_BATCHCLI, lst_print_error(), lst_print_transerr(), lst_print_usage(), lst_query_batch_ioctl(), lst_reset_rpcent(), lst_stop_batch_ioctl(), lstcon_tsbqry_stat_failure(), lstcon_tsbqry_stat_run(), optind, and session_key.
int jt_lst_update_group (int argc, char ** argv)
Definition at line 1166 of file lst.c.
References INIT_LIST_HEAD, lst_alloc_rpcent(), lst_free_rpcent(), lst_get_node_count(), LST_GROUP_CLEAN, LST_GROUP_REFRESH, LST_GROUP_RMND, lst_node_str2state(), LST_OPC_GROUP, LST_OPC_NODES, lst_print_error(), lst_print_transerr(), lst_print_usage(), lst_update_group_ioctl(), optarg, optind, and session_key.
int lst_add_batch_ioctl (char * name)
Definition at line 2178 of file lst.c.
References lst_ioctl(), lstio_batch_add_args_t::lstio_bat_key, lstio_batch_add_args_t::lstio_bat_namep, lstio_batch_add_args_t::lstio_bat_nmlen, LSTIO_BATCH_ADD, and session_key.
Referenced by jt_lst_add_batch().
int lst_add_group_ioctl (char * name)
Definition at line 983 of file lst.c.
References lst_ioctl(), LSTIO_GROUP_ADD, lstio_group_add_args_t::lstio_grp_key, lstio_group_add_args_t::lstio_grp_namep, lstio_group_add_args_t::lstio_grp_nmlen, and session_key.
Referenced by jt_lst_add_group().
int lst_add_nodes_ioctl (char * name, int count, lnet_process_id_t * ids, unsigned * featp, struct list_head * resultp)
Definition at line 918 of file lst.c.
References lst_ioctl(), lstio_group_nodes_args_t::lstio_grp_count, lstio_group_nodes_args_t::lstio_grp_featp, lstio_group_nodes_args_t::lstio_grp_idsp, lstio_group_nodes_args_t::lstio_grp_key, lstio_group_nodes_args_t::lstio_grp_namep, lstio_group_nodes_args_t::lstio_grp_nmlen, lstio_group_nodes_args_t::lstio_grp_resultp, LSTIO_NODES_ADD, and session_key.
Referenced by jt_lst_add_group().
int lst_add_test_ioctl (char * batch, int type, int loop, int concur, int dist, int span, char * sgrp, char * dgrp, void * param, int plen, int * retp, struct list_head * resultp)
Definition at line 3052 of file lst.c.
References lst_ioctl(), lstio_test_args_t::lstio_tes_bat_name, lstio_test_args_t::lstio_tes_bat_nmlen, lstio_test_args_t::lstio_tes_concur, lstio_test_args_t::lstio_tes_dgrp_name, lstio_test_args_t::lstio_tes_dgrp_nmlen, lstio_test_args_t::lstio_tes_dist, lstio_test_args_t::lstio_tes_key, lstio_test_args_t::lstio_tes_loop, lstio_test_args_t::lstio_tes_oneside, lstio_test_args_t::lstio_tes_param, lstio_test_args_t::lstio_tes_param_len, lstio_test_args_t::lstio_tes_resultp, lstio_test_args_t::lstio_tes_retp, lstio_test_args_t::lstio_tes_sgrp_name, lstio_test_args_t::lstio_tes_sgrp_nmlen, lstio_test_args_t::lstio_tes_span, lstio_test_args_t::lstio_tes_type, LSTIO_TEST_ADD, and session_key.
Referenced by jt_lst_add_test().
int lst_alloc_rpcent (struct list_head * head, int count, int offset)
Definition at line 435 of file lst.c.
References list_add(), LNET_NID_ANY, LNET_PID_ANY, lst_free_rpcent(), lnet_process_id_t::nid, offsetof, lnet_process_id_t::pid, lstcon_rpc_ent_t::rpe_link, lstcon_rpc_ent_t::rpe_peer, and lstcon_rpc_ent_t::rpe_sid.
Referenced by jt_lst_add_group(), jt_lst_add_test(), jt_lst_ping(), jt_lst_query_batch(), jt_lst_start_batch(), jt_lst_stop_batch(), jt_lst_update_group(), and lst_stat_req_param_alloc().
void lst_cal_lnet_stat (float delta, lnet_counters_t * lnet_new, lnet_counters_t * lnet_old)
Definition at line 1659 of file lst.c.
References lst_lnet_stat_result_t::lnet_avg_rcvperf, lst_lnet_stat_result_t::lnet_avg_rcvrate, lst_lnet_stat_result_t::lnet_avg_sndperf, lst_lnet_stat_result_t::lnet_avg_sndrate, lst_lnet_stat_result_t::lnet_max_rcvperf, lst_lnet_stat_result_t::lnet_max_rcvrate, lst_lnet_stat_result_t::lnet_max_sndperf, lst_lnet_stat_result_t::lnet_max_sndrate, lst_lnet_stat_result_t::lnet_min_rcvperf, lst_lnet_stat_result_t::lnet_min_rcvrate, lst_lnet_stat_result_t::lnet_min_sndperf, lst_lnet_stat_result_t::lnet_min_sndrate, lst_lnet_stat_result_t::lnet_stat_count, lst_lnet_stat_result_t::lnet_total_rcvperf, lst_lnet_stat_result_t::lnet_total_rcvrate, lst_lnet_stat_result_t::lnet_total_sndperf, lst_lnet_stat_result_t::lnet_total_sndrate, lnet_counters::recv_count, lnet_counters::recv_length, lnet_counters::send_count, and lnet_counters::send_length.
Referenced by lst_print_stat().
int lst_del_group (char * grp_name)
Definition at line 947 of file lst.c.
References lst_del_group_ioctl(), lst_print_error(), lstcon_rpc_stat_failure(), lstcon_sesop_stat_failure(), lstcon_trans_stat_t::trs_fwk_errno, and lstcon_trans_stat_t::trs_rpc_errno.
Referenced by jt_lst_add_group(), and jt_lst_del_group().
int lst_del_group_ioctl (char * name)
Definition at line 935 of file lst.c.
References lst_ioctl(), LSTIO_GROUP_DEL, lstio_group_del_args_t::lstio_grp_key, lstio_group_del_args_t::lstio_grp_namep, lstio_group_del_args_t::lstio_grp_nmlen, and session_key.
Referenced by lst_del_group().
int lst_end_session_ioctl (void)
Definition at line 673 of file lst.c.
References lst_ioctl(), lstio_session_end_args_t::lstio_ses_key, LSTIO_SESSION_END, and session_key.
Referenced by jt_lst_end_session().
void lst_free_rpcent (struct list_head * head)
Definition at line 409 of file lst.c.
References list_del(), list_empty(), list_entry, list_head::next, and lstcon_rpc_ent_t::rpe_link.
Referenced by jt_lst_add_group(), jt_lst_add_test(), jt_lst_ping(), jt_lst_query_batch(), jt_lst_start_batch(), jt_lst_stop_batch(), jt_lst_update_group(), lst_alloc_rpcent(), and lst_stat_req_param_free().
int lst_get_bulk_param (int argc, char ** argv, lst_test_bulk_param_t * bulk)
Definition at line 2938 of file lst.c.
References lst_test_bulk_param_t::blk_flags, lst_test_bulk_param_t::blk_opc, lst_test_bulk_param_t::blk_size, end, LNET_MAX_IOV, LST_BRW_CHECK_FULL, LST_BRW_CHECK_NONE, LST_BRW_CHECK_SIMPLE, LST_BRW_READ, and LST_BRW_WRITE.
Referenced by lst_get_test_param().
int lst_get_node_count (int type, char * str, int * countp, lnet_process_id_t ** idspp)
Definition at line 742 of file lst.c.
References buf, lst_info_batch_ioctl(), lst_info_group_ioctl(), LST_NAME_SIZE, LST_OPC_BATCHCLI, LST_OPC_BATCHSRV, LST_OPC_GROUP, LST_OPC_NODES, LST_OPC_SESSION, lst_parse_nids(), lst_session_info_ioctl(), lstcon_ndlist_ent_t::nle_nnode, lstcon_test_batch_ent_t::tbe_cli_nle, and lstcon_test_batch_ent_t::tbe_srv_nle.
Referenced by jt_lst_add_test(), jt_lst_ping(), jt_lst_start_batch(), jt_lst_stop_batch(), jt_lst_update_group(), and lst_stat_req_param_alloc().
int lst_get_test_param (char * test, int argc, char ** argv, void ** param, int * plen)
Definition at line 3009 of file lst.c.
References lst_get_bulk_param(), LST_TEST_BULK, lst_test_name2type(), and LST_TEST_PING.
Referenced by jt_lst_add_test().
int lst_info_batch_ioctl (char * batch, int test, int server, lstcon_test_batch_ent_t * entp, int * idxp, int * ndentp, lstcon_node_ent_t * dentsp)
Definition at line 2460 of file lst.c.
References lst_ioctl(), lstio_batch_info_args_t::lstio_bat_dentsp, lstio_batch_info_args_t::lstio_bat_entp, lstio_batch_info_args_t::lstio_bat_idxp, lstio_batch_info_args_t::lstio_bat_key, lstio_batch_info_args_t::lstio_bat_namep, lstio_batch_info_args_t::lstio_bat_ndentp, lstio_batch_info_args_t::lstio_bat_nmlen, lstio_batch_info_args_t::lstio_bat_server, lstio_batch_info_args_t::lstio_bat_testidx, LSTIO_BATCH_INFO, and session_key.
Referenced by jt_lst_list_batch(), jt_lst_query_batch(), lst_get_node_count(), and lst_list_tsb_nodes().
int lst_info_group_ioctl (char * name, lstcon_ndlist_ent_t * gent, int * idx, int * count, lstcon_node_ent_t * dents)
Definition at line 1304 of file lst.c.
References lst_ioctl(), LSTIO_GROUP_INFO, lstio_group_info_args_t::lstio_grp_dentsp, lstio_group_info_args_t::lstio_grp_entp, lstio_group_info_args_t::lstio_grp_idxp, lstio_group_info_args_t::lstio_grp_key, lstio_group_info_args_t::lstio_grp_namep, lstio_group_info_args_t::lstio_grp_ndentp, lstio_group_info_args_t::lstio_grp_nmlen, and session_key.
Referenced by jt_lst_list_group(), and lst_get_node_count().
int lst_initialize (void)
Definition at line 3276 of file lst.c.
References LST_FEATS_MASK, session_features, and session_key.
Referenced by main().
int lst_ioctl (unsigned int opc, void * buf, int len)
Definition at line 491 of file lst.c.
References IOC_LIBCFS_LNETST, libcfs_ioctl_data::ioc_pbuf1, libcfs_ioctl_data::ioc_pbuf2, libcfs_ioctl_data::ioc_plen1, libcfs_ioctl_data::ioc_plen2, libcfs_ioctl_data::ioc_u32, l_ioctl(), LIBCFS_IOC_INIT, LNET_DEV_ID, lstcon_trans_stat_t::trs_fwk_errno, and lstcon_trans_stat_t::trs_rpc_errno.
Referenced by lst_add_batch_ioctl(), lst_add_group_ioctl(), lst_add_nodes_ioctl(), lst_add_test_ioctl(), lst_del_group_ioctl(), lst_end_session_ioctl(), lst_info_batch_ioctl(), lst_info_group_ioctl(), lst_list_batch_ioctl(), lst_list_group_ioctl(), lst_new_session_ioctl(), lst_ping_ioctl(), lst_query_batch_ioctl(), lst_session_info_ioctl(), lst_start_batch_ioctl(), lst_stat_ioctl(), lst_stop_batch_ioctl(), and lst_update_group_ioctl().
int lst_list_batch_all (void)
Definition at line 2480 of file lst.c.
References lst_list_batch_ioctl(), LST_NAME_SIZE, lst_print_error(), and name.
Referenced by jt_lst_list_batch().
int lst_list_batch_ioctl (int len, char * name, int index)
Definition at line 2447 of file lst.c.
References lst_ioctl(), lstio_batch_list_args_t::lstio_bat_idx, lstio_batch_list_args_t::lstio_bat_key, lstio_batch_list_args_t::lstio_bat_namep, lstio_batch_list_args_t::lstio_bat_nmlen, LSTIO_BATCH_LIST, and session_key.
Referenced by lst_list_batch_all().
int lst_list_group_all (void)
Definition at line 1321 of file lst.c.
References lst_list_group_ioctl(), LST_NAME_SIZE, lst_print_error(), and name.
Referenced by jt_lst_list_group().
int lst_list_group_ioctl (int len, char * name, int idx)
Definition at line 1291 of file lst.c.
References lst_ioctl(), LSTIO_GROUP_LIST, lstio_group_list_args_t::lstio_grp_idx, lstio_group_list_args_t::lstio_grp_key, lstio_group_list_args_t::lstio_grp_namep, lstio_group_list_args_t::lstio_grp_nmlen, and session_key.
Referenced by lst_list_group_all().
int lst_list_tsb_nodes (char * batch, int test, int server, int count, int active, int invalid)
Definition at line 2507 of file lst.c.
References libcfs_id2str(), lst_info_batch_ioctl(), LST_NODE_ACTIVE, LST_NODE_BUSY, LST_NODE_DOWN, lst_node_state2str(), LST_NODE_UNKNOWN, and lst_print_error().
Referenced by jt_lst_list_batch().
static float lst_lnet_stat_value (int bw, int send, int off) [static]
Definition at line 1627 of file lst.c.
References lst_lnet_stat_result_t::lnet_avg_sndperf, and lst_lnet_stat_result_t::lnet_avg_sndrate.
Referenced by lst_print_lnet_stat().
int lst_new_session_ioctl (char * name, int timeout, int force, lst_sid_t * sid)
Definition at line 523 of file lst.c.
References lst_ioctl(), lstio_session_new_args_t::lstio_ses_feats, lstio_session_new_args_t::lstio_ses_force, lstio_session_new_args_t::lstio_ses_idp, lstio_session_new_args_t::lstio_ses_key, lstio_session_new_args_t::lstio_ses_namep, lstio_session_new_args_t::lstio_ses_nmlen, lstio_session_new_args_t::lstio_ses_timeout, LSTIO_SESSION_NEW, session_features, and session_key.
Referenced by jt_lst_new_session().
char* lst_node_state2str (int state)
Definition at line 314 of file lst.c.
References LST_NODE_ACTIVE, LST_NODE_BUSY, and LST_NODE_DOWN.
Referenced by jt_lst_list_group(), jt_lst_ping(), lst_list_tsb_nodes(), and lst_print_tsb_verbose().
int lst_node_str2state (char * str)
Definition at line 327 of file lst.c.
References LST_NODE_ACTIVE, LST_NODE_BUSY, LST_NODE_DOWN, and LST_NODE_UNKNOWN.
Referenced by jt_lst_update_group().
int lst_parse_distribute (char * dstr, int * dist, int * span)
Definition at line 2920 of file lst.c.
Referenced by jt_lst_add_test().
int lst_parse_nids (char * str, int * countp, lnet_process_id_t ** idspp)
Definition at line 259 of file lst.c.
References expand_strs(), free_lstr(), head, libcfs_str2nid(), LNET_NID_ANY, LNET_PID_LUSTRE, list_string::lstr_next, and list_string::lstr_str.
Referenced by jt_lst_add_group(), and lst_get_node_count().
int lst_ping_ioctl (char * str, int type, int timeout, int count, lnet_process_id_t * ids, struct list_head * head)
Definition at line 723 of file lst.c.
References lst_ioctl(), lstio_debug_args_t::lstio_dbg_count, lstio_debug_args_t::lstio_dbg_flags, lstio_debug_args_t::lstio_dbg_idsp, lstio_debug_args_t::lstio_dbg_key, lstio_debug_args_t::lstio_dbg_namep, lstio_debug_args_t::lstio_dbg_nmlen, lstio_debug_args_t::lstio_dbg_resultp, lstio_debug_args_t::lstio_dbg_timeout, lstio_debug_args_t::lstio_dbg_type, LSTIO_DEBUG, and session_key.
Referenced by jt_lst_ping().
void lst_print_error (char * sub, const char * def_format, ...)
Definition at line 372 of file lst.c.
Referenced by jt_lst_add_batch(), jt_lst_add_group(), jt_lst_add_test(), jt_lst_end_session(), jt_lst_list_batch(), jt_lst_list_group(), jt_lst_new_session(), jt_lst_ping(), jt_lst_show_error(), jt_lst_show_session(), jt_lst_start_batch(), jt_lst_stat(), jt_lst_stop_batch(), jt_lst_update_group(), lst_del_group(), lst_list_batch_all(), lst_list_group_all(), and lst_list_tsb_nodes().
void lst_print_lnet_stat (char * name, int bwrt, int rdwr, int type)
Definition at line 1722 of file lst.c.
References lst_lnet_stat_result_t::lnet_stat_count, and lst_lnet_stat_value().
Referenced by lst_print_stat().
void lst_print_stat (char * name, struct list_head * resultp, int idx, int lnet, int bwrt, int rdwr, int type)
Definition at line 1777 of file lst.c.
References INIT_LIST_HEAD, list_add_tail(), list_del(), list_empty(), list_entry, list_splice(), LNET_NID_ANY, lst_cal_lnet_stat(), lst_print_lnet_stat(), lst_timeval_diff(), list_head::next, lnet_process_id_t::nid, lnet_process_id_t::pid, lstcon_rpc_ent_t::rpe_fwk_errno, lstcon_rpc_ent_t::rpe_link, lstcon_rpc_ent_t::rpe_payload, lstcon_rpc_ent_t::rpe_peer, lstcon_rpc_ent_t::rpe_rpc_errno, and lstcon_rpc_ent_t::rpe_stamp.
Referenced by jt_lst_stat().
void lst_print_transerr (struct list_head * head, char * optstr)
Definition at line 459 of file lst.c.
References libcfs_id2str(), list_for_each_entry, lstcon_rpc_ent_t::rpe_fwk_errno, lstcon_rpc_ent_t::rpe_peer, and lstcon_rpc_ent_t::rpe_rpc_errno.
Referenced by jt_lst_add_group(), jt_lst_add_test(), jt_lst_start_batch(), jt_lst_stop_batch(), and jt_lst_update_group().
void lst_print_tsb_verbose (struct list_head * head, int active, int idle, int error)
Definition at line 2712 of file lst.c.
References libcfs_id2str(), list_for_each_entry, lst_node_state2str(), lstcon_rpc_ent_t::rpe_fwk_errno, lstcon_rpc_ent_t::rpe_peer, lstcon_rpc_ent_t::rpe_priv, lstcon_rpc_ent_t::rpe_rpc_errno, and lstcon_rpc_ent_t::rpe_state.
Referenced by jt_lst_query_batch().
void lst_print_usage (char * cmd)
Definition at line 366 of file lst.c.
References Parser_printhelp().
Referenced by jt_lst_add_batch(), jt_lst_add_group(), jt_lst_add_test(), jt_lst_del_group(), jt_lst_list_batch(), jt_lst_list_group(), jt_lst_new_session(), jt_lst_ping(), jt_lst_query_batch(), jt_lst_show_error(), jt_lst_start_batch(), jt_lst_stat(), jt_lst_stop_batch(), and jt_lst_update_group().
int lst_query_batch_ioctl (char * batch, int test, int server, int timeout, struct list_head * head)
Definition at line 2695 of file lst.c.
References lst_ioctl(), lstio_batch_query_args_t::lstio_bat_client, lstio_batch_query_args_t::lstio_bat_key, lstio_batch_query_args_t::lstio_bat_namep, lstio_batch_query_args_t::lstio_bat_nmlen, lstio_batch_query_args_t::lstio_bat_resultp, lstio_batch_query_args_t::lstio_bat_testidx, lstio_batch_query_args_t::lstio_bat_timeout, LSTIO_BATCH_QUERY, and session_key.
Referenced by jt_lst_query_batch(), and jt_lst_stop_batch().
void lst_reset_rpcent (struct list_head * head)
Definition at line 422 of file lst.c.
References list_for_each_entry, LNET_NID_ANY, LNET_PID_ANY, lnet_process_id_t::nid, lnet_process_id_t::pid, lstcon_rpc_ent_t::rpe_fwk_errno, lstcon_rpc_ent_t::rpe_peer, lstcon_rpc_ent_t::rpe_rpc_errno, and lstcon_rpc_ent_t::rpe_sid.
Referenced by jt_lst_stat(), and jt_lst_stop_batch().
int lst_session_info_ioctl (char * name, int len, int * key, unsigned * featp, lst_sid_t * sid, lstcon_ndlist_ent_t * ndinfo)
Definition at line 631 of file lst.c.
References lst_ioctl(), lstio_session_info_args_t::lstio_ses_featp, lstio_session_info_args_t::lstio_ses_idp, lstio_session_info_args_t::lstio_ses_keyp, lstio_session_info_args_t::lstio_ses_namep, lstio_session_info_args_t::lstio_ses_ndinfo, lstio_session_info_args_t::lstio_ses_nmlen, and LSTIO_SESSION_INFO.
Referenced by jt_lst_show_session(), and lst_get_node_count().
int lst_start_batch_ioctl (char * name, int timeout, struct list_head * resultp)
Definition at line 2224 of file lst.c.
References lst_ioctl(), lstio_batch_run_args_t::lstio_bat_key, lstio_batch_run_args_t::lstio_bat_namep, lstio_batch_run_args_t::lstio_bat_nmlen, lstio_batch_run_args_t::lstio_bat_resultp, lstio_batch_run_args_t::lstio_bat_timeout, LSTIO_BATCH_START, and session_key.
Referenced by jt_lst_start_batch().
int lst_stat_ioctl (char * name, int count, lnet_process_id_t * idsp, int timeout, struct list_head * resultp)
Definition at line 1498 of file lst.c.
References lst_ioctl(), lstio_stat_args_t::lstio_sta_count, lstio_stat_args_t::lstio_sta_idsp, lstio_stat_args_t::lstio_sta_key, lstio_stat_args_t::lstio_sta_namep, lstio_stat_args_t::lstio_sta_nmlen, lstio_stat_args_t::lstio_sta_resultp, lstio_stat_args_t::lstio_sta_timeout, LSTIO_STAT_QUERY, and session_key.
Referenced by jt_lst_show_error(), and jt_lst_stat().
static int lst_stat_req_param_alloc (char * name, lst_stat_req_param_t ** srpp, int save_old) [static]
Definition at line 1537 of file lst.c.
References INIT_LIST_HEAD, lst_alloc_rpcent(), lst_get_node_count(), LST_OPC_GROUP, LST_OPC_NODES, lst_stat_req_param_free(), lst_stat_req_param_t::srp_count, lst_stat_req_param_t::srp_ids, lst_stat_req_param_t::srp_name, and lst_stat_req_param_t::srp_result.
Referenced by jt_lst_show_error(), and jt_lst_stat().
static void lst_stat_req_param_free (lst_stat_req_param_t * srp) [static]
Definition at line 1523 of file lst.c.
References lst_free_rpcent(), lst_stat_req_param_t::srp_ids, and lst_stat_req_param_t::srp_result.
Referenced by jt_lst_show_error(), jt_lst_stat(), and lst_stat_req_param_alloc().
int lst_stop_batch_ioctl (char * name, int force, struct list_head * resultp)
Definition at line 2327 of file lst.c.
References lst_ioctl(), lstio_batch_stop_args_t::lstio_bat_force, lstio_batch_stop_args_t::lstio_bat_key, lstio_batch_stop_args_t::lstio_bat_namep, lstio_batch_stop_args_t::lstio_bat_nmlen, lstio_batch_stop_args_t::lstio_bat_resultp, LSTIO_BATCH_STOP, and session_key.
Referenced by jt_lst_stop_batch().
int lst_test_name2type (char * name)
Definition at line 355 of file lst.c.
References LST_TEST_BULK, and LST_TEST_PING.
Referenced by lst_get_test_param().
char* lst_test_type2name (int type)
Definition at line 344 of file lst.c.
References LST_TEST_BULK, and LST_TEST_PING.
Referenced by jt_lst_list_batch().
static void lst_timeval_diff (struct timeval * tv1, struct timeval * tv2, struct timeval * df) [static]
Definition at line 1643 of file lst.c.
Referenced by lst_print_stat().
int lst_update_group_ioctl (int opc, char * name, int clean, int count, lnet_process_id_t * ids, struct list_head * resultp)
Definition at line 1148 of file lst.c.
References lst_ioctl(), LSTIO_GROUP_UPDATE, lstio_group_update_args_t::lstio_grp_args, lstio_group_update_args_t::lstio_grp_count, lstio_group_update_args_t::lstio_grp_idsp, lstio_group_update_args_t::lstio_grp_key, lstio_group_update_args_t::lstio_grp_namep, lstio_group_update_args_t::lstio_grp_nmlen, lstio_group_update_args_t::lstio_grp_opc, lstio_group_update_args_t::lstio_grp_resultp, and session_key.
Referenced by jt_lst_update_group().
int main (int argc, char ** argv)
Definition at line 3306 of file lst.c.
References lst_initialize(), Parser_commands(), Parser_execarg(), Parser_init(), and ptl_initialize().
void new_lstrs (lstr_t ** list, char * prefix, char * postfix, int lo, int hi, int stride)
Definition at line 119 of file lst.c.
References alloc_lstr(), list_string::lstr_next, and list_string::lstr_str.
Referenced by expand_lstr().
Variable Documentation
int alloc_count = 0 [static]
Definition at line 78 of file lst.c.
Referenced by alloc_lstr(), and free_lstr().
int alloc_nob = 0 [static]
Definition at line 79 of file lst.c.
Referenced by alloc_lstr(), and free_lstr().
lst_lnet_stat_result_t lnet_stat_result
Definition at line 1624 of file lst.c.
command_t lst_cmdlist[] [static]
Definition at line 3236 of file lst.c.
lst_sid_t LST_INVALID_SID = {LNET_NID_ANY, -1}
Definition at line 60 of file lst.c.
Referenced by lstcon_console_init(), and lstcon_session_end().
unsigned session_features = LST_FEATS_MASK [static]
Definition at line 65 of file lst.c.
Referenced by jt_lst_add_group(), jt_lst_new_session(), lst_initialize(), and lst_new_session_ioctl().
lst_sid_t session_id [static]
Definition at line 61 of file lst.c.
int session_key [static]
Definition at line 62 of file lst.c.
Referenced by jt_lst_add_batch(), jt_lst_add_group(), jt_lst_add_test(), jt_lst_del_group(), jt_lst_end_session(), jt_lst_list_batch(), jt_lst_list_group(), jt_lst_new_session(), jt_lst_ping(), jt_lst_query_batch(), jt_lst_show_error(), jt_lst_start_batch(), jt_lst_stat(), jt_lst_stop_batch(), jt_lst_update_group(), lst_add_batch_ioctl(), lst_add_group_ioctl(), lst_add_nodes_ioctl(), lst_add_test_ioctl(), lst_del_group_ioctl(), lst_end_session_ioctl(), lst_info_batch_ioctl(), lst_info_group_ioctl(), lst_initialize(), lst_list_batch_ioctl(), lst_list_group_ioctl(), lst_new_session_ioctl(), lst_ping_ioctl(), lst_query_batch_ioctl(), lst_start_batch_ioctl(), lst_stat_ioctl(), lst_stop_batch_ioctl(), and lst_update_group_ioctl().
lstcon_trans_stat_t trans_stat [static]
Definition at line 66 of file lst.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.