Lustre: lustre/utils/gss/lsupport.c File Reference
lustre/utils/gss/lsupport.c File Reference
#include "config.h"
#include <sys/param.h>
#include <sys/utsname.h>
#include <sys/stat.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <sys/types.h>
#include <sys/ipc.h>
#include <sys/sem.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <pwd.h>
#include <grp.h>
#include <string.h>
#include <dirent.h>
#include <poll.h>
#include <fcntl.h>
#include <signal.h>
#include <unistd.h>
#include <errno.h>
#include <assert.h>
#include <lnet/nidstr.h>
#include "err_util.h"
#include "gssd.h"
#include "lsupport.h"
Data Structures
struct __sem_s
struct convert_struct
struct user_map_item
struct user_mapping
Defines
#define LND_MAX (sizeof(converter) / sizeof(converter[0]))
#define MAPPING_GROW_SIZE 512
#define MAX_LINE_LEN 256
Typedefs
typedef int lnd_nid2hostname_t (char *lnd, uint32_t net, uint32_t addr, char *buf, int buflen)
Functions
void gssd_init_unique (int type)
void gssd_exit_unique (int type)
static int ipv4_nid2hostname (char *lnd, uint32_t net, uint32_t addr, char *buf, int buflen)
static int lolnd_nid2hostname (char *lnd, uint32_t net, uint32_t addr, char *buf, int buflen)
static int is_space (char c)
static int external_nid2hostname (char *lnd, uint32_t net, uint32_t addr, char *namebuf, int namebuflen)
int lnet_nid2hostname (lnet_nid_t nid, char *buf, int buflen)
void cleanup_mapping (void)
static int grow_mapping (int nitems)
uid_t parse_uid (char *uidstr)
static int read_mapping_db (void)
static int mapping_changed (void)
int lookup_mapping (char *princ, lnet_nid_t nid, uid_t *uid)
Variables
const char * lustre_svc_name []
static struct __sem_s sems [2]
char gethostname_ex [PATH_MAX] = GSSD_DEFAULT_GETHOSTNAME_EX
static struct convert_struct converter []
static struct user_mapping mapping = {0, NULL}
static int mapping_mtime = 0
Define Documentation
#define LND_MAX (sizeof(converter) / sizeof(converter[0]))
Definition at line 310 of file lsupport.c.
Referenced by lnet_nid2hostname().
#define MAPPING_GROW_SIZE 512
Definition at line 341 of file lsupport.c.
#define MAX_LINE_LEN 256
Definition at line 342 of file lsupport.c.
Referenced by read_mapping_db().
Typedef Documentation
typedef int lnd_nid2hostname_t(char *lnd, uint32_t net, uint32_t addr, char *buf, int buflen)
Definition at line 168 of file lsupport.c.
Function Documentation
void cleanup_mapping (void)
Definition at line 359 of file lsupport.c.
References user_mapping::items, user_mapping::nitems, and user_map_item::principal.
Referenced by main(), read_mapping_db(), and sig_die().
static int external_nid2hostname (char * lnd, uint32_t net, uint32_t addr, char * namebuf, int namebuflen) [static]
Definition at line 235 of file lsupport.c.
References buf, bufsize, gethostname_ex, head, is_space(), and printerr.
static int grow_mapping (int nitems) [static]
Definition at line 371 of file lsupport.c.
References user_mapping::items, user_mapping::nitems, and printerr.
Referenced by read_mapping_db().
void gssd_exit_unique (int type)
Definition at line 150 of file lsupport.c.
References assert, GSSD_CLI, and GSSD_SVC.
void gssd_init_unique (int type)
Definition at line 95 of file lsupport.c.
References assert, GSSD_CLI, GSSD_SVC, __sem_s::name, printerr, sem, __sem_s::sem_id, __sem_s::sem_key, and sems.
Referenced by main().
static int ipv4_nid2hostname (char * lnd, uint32_t net, uint32_t addr, char * buf, int buflen) [static]
Definition at line 173 of file lsupport.c.
References printerr.
static int is_space (char c) [static]
Definition at line 229 of file lsupport.c.
Referenced by external_nid2hostname().
int lnet_nid2hostname (lnet_nid_t nid, char * buf, int buflen)
Definition at line 312 of file lsupport.c.
References LND_MAX, LNET_NETTYP(), LNET_NIDADDR(), LNET_NIDNET(), name, convert_struct::nid2name, and printerr.
Referenced by construct_service_name(), get_ids(), lgss_get_service_str(), and svc_princ_verify_host().
static int lolnd_nid2hostname (char * lnd, uint32_t net, uint32_t addr, char * buf, int buflen) [static]
Definition at line 196 of file lsupport.c.
References printerr.
int lookup_mapping (char * princ, lnet_nid_t nid, uid_t * uid)
Definition at line 521 of file lsupport.c.
References user_mapping::items, LNET_NID_ANY, mapping_changed(), user_map_item::nid, user_mapping::nitems, user_map_item::principal, printerr, read_mapping_db(), and user_map_item::uid.
Referenced by get_ids(), and main().
static int mapping_changed (void) [inline, static]
Definition at line 496 of file lsupport.c.
References MAPPING_DATABASE_FILE, mapping_mtime, and printerr.
Referenced by lookup_mapping().
uid_t parse_uid (char * uidstr)
Definition at line 399 of file lsupport.c.
Referenced by read_mapping_db().
static int read_mapping_db (void) [static]
Definition at line 416 of file lsupport.c.
References cleanup_mapping(), grow_mapping(), user_mapping::items, libcfs_str2nid(), LNET_NID_ANY, MAPPING_DATABASE_FILE, MAX_LINE_LEN, name, user_map_item::nid, user_mapping::nitems, parse_uid(), user_map_item::principal, printerr, and user_map_item::uid.
Referenced by lookup_mapping().
Variable Documentation
struct convert_struct converter[] [static]
Initial value:
 {
        [0]             = { "UNUSED0",  NULL},
        [QSWLND]        = { "QSWLND",   external_nid2hostname},
        [SOCKLND]       = { "SOCKLND",  ipv4_nid2hostname },
        [GMLND]         = { "GMLND",    external_nid2hostname},
        [PTLLND]        = { "PTLLND",   external_nid2hostname },
        [O2IBLND]       = { "O2IBLND",  ipv4_nid2hostname },
        [LOLND]         = { "LOLND",    lolnd_nid2hostname },
        [RALND]         = { "RALND",    external_nid2hostname },
        [MXLND]         = { "MXLND",    external_nid2hostname },
}
Definition at line 298 of file lsupport.c.
char gethostname_ex[PATH_MAX] = GSSD_DEFAULT_GETHOSTNAME_EX
Definition at line 166 of file lsupport.c.
Referenced by external_nid2hostname().
const char* lustre_svc_name[]
Initial value:
{
        [LUSTRE_GSS_SVC_MGS]    = "MGS",
        [LUSTRE_GSS_SVC_MDS]    = "MDS",
        [LUSTRE_GSS_SVC_OSS]    = "OSS",
}
Definition at line 75 of file lsupport.c.
Referenced by get_ids().
struct user_mapping mapping = {0, NULL} [static]
Definition at line 355 of file lsupport.c.
Referenced by ll_invalidate_page(), ll_releasepage(), ll_remove_from_page_cache(), loop_set_fd(), and mdc_read_page().
int mapping_mtime = 0 [static]
Definition at line 357 of file lsupport.c.
Referenced by mapping_changed().
struct __sem_s sems[2] [static]
Referenced by gssd_init_unique().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.