Lustre: lustre/utils/gss/lsupport.h File Reference
lustre/utils/gss/lsupport.h File Reference
#include <assert.h>
#include <unistd.h>
#include <stdint.h>
#include <lnet/types.h>
Data Structures
struct lgssd_upcall_data
struct lgssd_ioctl_param
Defines
#define GSSD_CLI (0)
#define GSSD_SVC (1)
#define LUSTRE_GSS_SVC_MGS 0
#define LUSTRE_GSS_SVC_MDS 1
#define LUSTRE_GSS_SVC_OSS 2
#define GSSD_INTERFACE_VERSION (1)
#define GSSD_DEFAULT_GETHOSTNAME_EX "/etc/lustre/nid2hostname"
#define MAPPING_DATABASE_FILE "/etc/lustre/idmap.conf"
Functions
void gssd_init_unique (int type)
void gssd_exit_unique (int type)
int lnet_nid2hostname (lnet_nid_t nid, char *buf, int buflen)
void cleanup_mapping (void)
int lookup_mapping (char *princ, lnet_nid_t nid, uid_t *uid)
Variables
const char * lustre_svc_name []
Define Documentation
#define GSSD_CLI (0)
Definition at line 45 of file lsupport.h.
Referenced by gssd_exit_unique(), gssd_init_unique(), and main().
#define GSSD_DEFAULT_GETHOSTNAME_EX "/etc/lustre/nid2hostname"
Definition at line 87 of file lsupport.h.
#define GSSD_INTERFACE_VERSION (1)
Definition at line 70 of file lsupport.h.
#define GSSD_SVC (1)
Definition at line 46 of file lsupport.h.
Referenced by gssd_exit_unique(), gssd_init_unique(), and main().
#define LUSTRE_GSS_SVC_MDS 1
Definition at line 56 of file lsupport.h.
Referenced by construct_service_name(), get_ids(), gssd_select_svc_cred(), and handle_krb5_upcall().
#define LUSTRE_GSS_SVC_MGS 0
Definition at line 55 of file lsupport.h.
Referenced by get_ids(), and gssd_select_svc_cred().
#define LUSTRE_GSS_SVC_OSS 2
Definition at line 57 of file lsupport.h.
Referenced by get_ids(), gssd_select_svc_cred(), and handle_krb5_upcall().
#define MAPPING_DATABASE_FILE "/etc/lustre/idmap.conf"
Definition at line 88 of file lsupport.h.
Referenced by mapping_changed(), and read_mapping_db().
Function Documentation
void cleanup_mapping (void)
Definition at line 359 of file lsupport.c.
References user_mapping::items, user_mapping::nitems, and user_map_item::principal.
Referenced by main(), read_mapping_db(), and sig_die().
void gssd_exit_unique (int type)
Definition at line 150 of file lsupport.c.
References assert, GSSD_CLI, and GSSD_SVC.
void gssd_init_unique (int type)
Definition at line 95 of file lsupport.c.
References assert, GSSD_CLI, GSSD_SVC, __sem_s::name, printerr, sem, __sem_s::sem_id, __sem_s::sem_key, and sems.
Referenced by main().
int lnet_nid2hostname (lnet_nid_t nid, char * buf, int buflen)
Definition at line 312 of file lsupport.c.
References LND_MAX, LNET_NETTYP(), LNET_NIDADDR(), LNET_NIDNET(), name, convert_struct::nid2name, and printerr.
Referenced by construct_service_name(), get_ids(), lgss_get_service_str(), and svc_princ_verify_host().
int lookup_mapping (char * princ, lnet_nid_t nid, uid_t * uid)
Definition at line 521 of file lsupport.c.
References user_mapping::items, LNET_NID_ANY, mapping_changed(), user_map_item::nid, user_mapping::nitems, user_map_item::principal, printerr, read_mapping_db(), and user_map_item::uid.
Referenced by get_ids(), and main().
Variable Documentation
const char* lustre_svc_name[]
Definition at line 75 of file lsupport.c.
Referenced by get_ids().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.