Lustre: lustre/include/lu_target.h File Reference
lustre/include/lu_target.h File Reference
#include <dt_object.h>
#include <lustre_export.h>
#include <lustre_update.h>
#include <lustre_disk.h>
#include <lustre_lfsck.h>
Data Structures
struct distribute_txn_replay_req
struct distribute_txn_replay_req_sub
struct target_distribute_txn_data
struct lu_target
struct tg_reply_data
Target reply data.
struct tgt_session_info
struct tgt_handler
struct tgt_opc_slice
struct tgt_commit_cb
Defines
#define LUT_REPLY_SLOTS_PER_CHUNK (1<<20)
#define LUT_REPLY_SLOTS_MAX_CHUNKS 16
#define TGT_RPC_HANDLER_HP(base, flags, opc, fn, hp, fmt, version)
#define TGT_RPC_HANDLER(base, flags, opc, fn, fmt, version) TGT_RPC_HANDLER_HP(base, flags, opc, fn, NULL, fmt, version)
#define TGT_MDT_HDL(flags, name, fn)
#define TGT_MDT_HDL_VAR(flags, name, fn)
#define TGT_OST_HDL(flags, name, fn)
#define TGT_OST_HDL_HP(flags, name, fn, hp)
#define TGT_MGS_HDL(flags, name, fn)
#define TGT_MGS_HDL_VAR(flags, name, fn)
#define TGT_OBD_HDL(flags, name, fn)
#define TGT_OBD_HDL_VAR(flags, name, fn)
#define TGT_DLM_HDL_VAR(flags, name, fn)
#define TGT_DLM_HDL(flags, name, fn)
#define TGT_LLOG_HDL_VAR(flags, name, fn)
#define TGT_LLOG_HDL(flags, name, fn)
#define TGT_SEC_HDL_VAR(flags, name, fn)
#define TGT_QUOTA_HDL(flags, name, fn)
#define TGT_SEQ_HDL(flags, name, fn)
#define TGT_FLD_HDL_VAR(flags, name, fn)
#define TGT_LFSCK_HDL(flags, name, fn)
#define TGT_UPDATE_HDL(flags, name, fn)
Typedefs
typedef int(* distribute_txn_replay_handler_t)(struct lu_env *env, struct target_distribute_txn_data *tdtd, struct distribute_txn_replay_req *dtrq)
typedef void(* tgt_cb_t)(struct lu_target *lut, __u64 transno, void *data, int err)
Enumerations
enum tgt_handler_flags { HABEO_CORPUS = (1 << 0), HABEO_CLAVIS = (1 << 1), HABEO_REFERO = (1 << 2), MUTABOR = (1 << 3) }
enum { ESERIOUS = 0x0001000 }
Functions
static struct tgt_session_info * tgt_ses_info (const struct lu_env *env)
static void tgt_vbr_obj_set (const struct lu_env *env, struct dt_object *obj)
static void tgt_opdata_set (const struct lu_env *env, __u64 flags)
static void tgt_opdata_clear (const struct lu_env *env, __u64 flags)
static struct ptlrpc_request * tgt_ses_req (struct tgt_session_info *tsi)
static __u64 tgt_conn_flags (struct tgt_session_info *tsi)
static int req_is_replay (struct ptlrpc_request *req)
static bool tgt_is_multimodrpcs_client (struct obd_export *exp)
int tgt_request_handle (struct ptlrpc_request *req)
char * tgt_name (struct lu_target *tgt)
void tgt_counter_incr (struct obd_export *exp, int opcode)
int tgt_connect_check_sptlrpc (struct ptlrpc_request *req, struct obd_export *exp)
int tgt_adapt_sptlrpc_conf (struct lu_target *tgt, int initial)
int tgt_connect (struct tgt_session_info *tsi)
int tgt_disconnect (struct tgt_session_info *uti)
int tgt_obd_ping (struct tgt_session_info *tsi)
int tgt_enqueue (struct tgt_session_info *tsi)
int tgt_convert (struct tgt_session_info *tsi)
int tgt_bl_callback (struct tgt_session_info *tsi)
int tgt_cp_callback (struct tgt_session_info *tsi)
int tgt_llog_open (struct tgt_session_info *tsi)
int tgt_llog_close (struct tgt_session_info *tsi)
int tgt_llog_destroy (struct tgt_session_info *tsi)
int tgt_llog_read_header (struct tgt_session_info *tsi)
int tgt_llog_next_block (struct tgt_session_info *tsi)
int tgt_llog_prev_block (struct tgt_session_info *tsi)
int tgt_sec_ctx_init (struct tgt_session_info *tsi)
int tgt_sec_ctx_init_cont (struct tgt_session_info *tsi)
int tgt_sec_ctx_fini (struct tgt_session_info *tsi)
int tgt_sendpage (struct tgt_session_info *tsi, struct lu_rdpg *rdpg, int nob)
int tgt_send_buffer (struct tgt_session_info *tsi, struct lu_rdbuf *rdbuf)
int tgt_validate_obdo (struct tgt_session_info *tsi, struct obdo *oa)
Validate oa from client.
int tgt_sync (const struct lu_env *env, struct lu_target *tgt, struct dt_object *obj, __u64 start, __u64 end)
int tgt_io_thread_init (struct ptlrpc_thread *thread)
void tgt_io_thread_done (struct ptlrpc_thread *thread)
int tgt_extent_lock (struct ldlm_namespace *ns, struct ldlm_res_id *res_id, __u64 start, __u64 end, struct lustre_handle *lh, int mode, __u64 *flags)
Helper function for getting server side [start, start+count] DLM lock if asked by client.
void tgt_extent_unlock (struct lustre_handle *lh, enum ldlm_mode mode)
int tgt_brw_lock (struct ldlm_namespace *ns, struct ldlm_res_id *res_id, struct obd_ioobj *obj, struct niobuf_remote *nb, struct lustre_handle *lh, enum ldlm_mode mode)
void tgt_brw_unlock (struct obd_ioobj *obj, struct niobuf_remote *niob, struct lustre_handle *lh, enum ldlm_mode mode)
int tgt_brw_read (struct tgt_session_info *tsi)
int tgt_brw_write (struct tgt_session_info *tsi)
int tgt_hpreq_handler (struct ptlrpc_request *req)
Assign high priority operations to the request if needed.
void tgt_register_lfsck_in_notify (int(*notify)(const struct lu_env *, struct dt_device *, struct lfsck_request *, struct thandle *))
void tgt_register_lfsck_query (int(*query)(const struct lu_env *, struct dt_device *, struct lfsck_request *, struct lfsck_reply *, struct lfsck_query *))
bool req_can_reconstruct (struct ptlrpc_request *req, struct tg_reply_data *trd)
void tgt_boot_epoch_update (struct lu_target *lut)
Update boot epoch when recovery ends.
void tgt_save_slc_lock (struct ldlm_lock *lock, __u64 transno)
void tgt_discard_slc_lock (struct ldlm_lock *lock)
int tgt_last_commit_cb_add (struct thandle *th, struct lu_target *lut, struct obd_export *exp, __u64 transno)
int tgt_new_client_cb_add (struct thandle *th, struct obd_export *exp)
int tgt_init (const struct lu_env *env, struct lu_target *lut, struct obd_device *obd, struct dt_device *dt, struct tgt_opc_slice *slice, int request_fail_id, int reply_fail_id)
void tgt_fini (const struct lu_env *env, struct lu_target *lut)
int tgt_client_alloc (struct obd_export *exp)
Allocate in-memory data for client slot related to export.
void tgt_client_free (struct obd_export *exp)
Free in-memory data for client slot related to export.
int tgt_client_del (const struct lu_env *env, struct obd_export *exp)
int tgt_client_add (const struct lu_env *env, struct obd_export *exp, int)
int tgt_client_new (const struct lu_env *env, struct obd_export *exp)
Add new client to the last_rcvd upon new connection.
int tgt_client_data_read (const struct lu_env *env, struct lu_target *tg, struct lsd_client_data *lcd, loff_t *off, int index)
int tgt_client_data_write (const struct lu_env *env, struct lu_target *tg, struct lsd_client_data *lcd, loff_t *off, struct thandle *th)
int tgt_server_data_read (const struct lu_env *env, struct lu_target *tg)
int tgt_server_data_write (const struct lu_env *env, struct lu_target *tg, struct thandle *th)
int tgt_server_data_update (const struct lu_env *env, struct lu_target *tg, int sync)
Update server data in last_rcvd.
int tgt_truncate_last_rcvd (const struct lu_env *env, struct lu_target *tg, loff_t off)
int tgt_reply_data_init (const struct lu_env *env, struct lu_target *tgt)
bool tgt_lookup_reply (struct ptlrpc_request *req, struct tg_reply_data *trd)
int tgt_add_reply_data (const struct lu_env *env, struct lu_target *tgt, struct tg_export_data *ted, struct tg_reply_data *trd, struct thandle *th, bool update_lrd_file)
struct tg_reply_data * tgt_lookup_reply_by_xid (struct tg_export_data *ted, __u64 xid)
int distribute_txn_init (const struct lu_env *env, struct lu_target *lut, struct target_distribute_txn_data *tdtd, __u32 index)
Start llog cancel thread.
void distribute_txn_fini (const struct lu_env *env, struct target_distribute_txn_data *tdtd)
Stop llog cancel thread.
int insert_update_records_to_replay_list (struct target_distribute_txn_data *, struct llog_update_record *, struct llog_cookie *, __u32)
Insert update records to the replay list.
void dtrq_list_dump (struct target_distribute_txn_data *tdtd, unsigned int mask)
Dump updates of distribute txns.
void dtrq_list_destroy (struct target_distribute_txn_data *tdtd)
Destroy all of replay req.
int distribute_txn_replay_handle (struct lu_env *env, struct target_distribute_txn_data *tdtd, struct distribute_txn_replay_req *dtrq)
redo updates on MDT if needed.
__u64 distribute_txn_get_next_transno (struct target_distribute_txn_data *tdtd)
Get next transno in the replay list, because this is the sorted list, so it will return the transno of next req in the list.
struct distribute_txn_replay_req * distribute_txn_get_next_req (struct target_distribute_txn_data *tdtd)
Get next req in the replay list.
void dtrq_destroy (struct distribute_txn_replay_req *dtrq)
Destroy distribute txn replay req.
struct
distribute_txn_replay_req_sub * dtrq_sub_lookup (struct distribute_txn_replay_req *dtrq, __u32 mdt_index)
Lookup distribute sub replay.
struct distribute_txn_replay_req * distribute_txn_lookup_finish_list (struct target_distribute_txn_data *tdtd, __u64 transno)
bool is_req_replayed_by_update (struct ptlrpc_request *req)
static int err_serious (int rc)
static int clear_serious (int rc)
static int is_serious (int rc)
static void tgt_drop_id (struct obd_export *exp, struct obdo *oa)
Do not return server-side uid/gid to remote client.
Variables
struct lu_context_key tgt_session_key
struct tgt_handler tgt_sec_ctx_handlers []
struct tgt_handler tgt_lfsck_handlers []
struct tgt_handler tgt_obd_handlers []
struct tgt_handler tgt_dlm_handlers []
struct tgt_handler tgt_llog_handlers []
struct tgt_handler tgt_out_handlers []
struct tgt_handler fld_handlers []
struct tgt_handler seq_handlers []
Define Documentation
#define LUT_REPLY_SLOTS_MAX_CHUNKS 16
Definition at line 168 of file lu_target.h.
Referenced by tgt_clear_reply_slot(), tgt_find_free_reply_slot(), tgt_fini(), tgt_init(), and tgt_set_reply_slot().
#define LUT_REPLY_SLOTS_PER_CHUNK (1<<20)
Definition at line 167 of file lu_target.h.
Referenced by tgt_bitmap_chunk_alloc(), tgt_clear_reply_slot(), tgt_find_free_reply_slot(), tgt_fini(), and tgt_set_reply_slot().
#define TGT_DLM_HDL (flags, name, fn)
Value:
TGT_RPC_HANDLER(LDLM_FIRST_OPC, flags, name, fn, &RQF_ ## name, \
                        LUSTRE_DLM_VERSION)
Definition at line 586 of file lu_target.h.
#define TGT_DLM_HDL_VAR (flags, name, fn)
Value:
TGT_RPC_HANDLER(LDLM_FIRST_OPC, flags, name, fn, NULL,          \
                        LUSTRE_DLM_VERSION)
Definition at line 583 of file lu_target.h.
#define TGT_FLD_HDL_VAR (flags, name, fn)
Value:
TGT_RPC_HANDLER(FLD_QUERY, flags, name, fn, NULL,               \
                        LUSTRE_MDS_VERSION)
Definition at line 617 of file lu_target.h.
#define TGT_LFSCK_HDL (flags, name, fn)
Value:
TGT_RPC_HANDLER(LFSCK_FIRST_OPC, flags, name, fn,               \
                        &RQF_ ## name, LUSTRE_OBD_VERSION)
Definition at line 622 of file lu_target.h.
#define TGT_LLOG_HDL (flags, name, fn)
Value:
TGT_RPC_HANDLER(LLOG_FIRST_OPC, flags, name, fn, &RQF_ ## name, \
                        LUSTRE_LOG_VERSION)
Definition at line 596 of file lu_target.h.
#define TGT_LLOG_HDL_VAR (flags, name, fn)
Value:
TGT_RPC_HANDLER(LLOG_FIRST_OPC, flags, name, fn, NULL,          \
                        LUSTRE_LOG_VERSION)
Definition at line 593 of file lu_target.h.
#define TGT_MDT_HDL (flags, name, fn)
Value:
TGT_RPC_HANDLER(MDS_FIRST_OPC, flags, name, fn, &RQF_ ## name,  \
                        LUSTRE_MDS_VERSION)
Definition at line 546 of file lu_target.h.
#define TGT_MDT_HDL_VAR (flags, name, fn)
Value:
TGT_RPC_HANDLER(MDS_FIRST_OPC, flags, name, fn, NULL,           \
                        LUSTRE_MDS_VERSION)
Definition at line 550 of file lu_target.h.
#define TGT_MGS_HDL (flags, name, fn)
Value:
TGT_RPC_HANDLER(MGS_FIRST_OPC, flags, name, fn, &RQF_ ## name,  \
                        LUSTRE_MGS_VERSION)
Definition at line 563 of file lu_target.h.
#define TGT_MGS_HDL_VAR (flags, name, fn)
Value:
TGT_RPC_HANDLER(MGS_FIRST_OPC, flags, name, fn, NULL,           \
                        LUSTRE_MGS_VERSION)
Definition at line 566 of file lu_target.h.
#define TGT_OBD_HDL (flags, name, fn)
Value:
TGT_RPC_HANDLER(OBD_FIRST_OPC, flags, name, fn, &RQF_ ## name,  \
                        LUSTRE_OBD_VERSION)
Definition at line 573 of file lu_target.h.
#define TGT_OBD_HDL_VAR (flags, name, fn)
Value:
TGT_RPC_HANDLER(OBD_FIRST_OPC, flags, name, fn, NULL,           \
                        LUSTRE_OBD_VERSION)
Definition at line 576 of file lu_target.h.
#define TGT_OST_HDL (flags, name, fn)
Value:
TGT_RPC_HANDLER(OST_FIRST_OPC, flags, name, fn, &RQF_ ## name,  \
                        LUSTRE_OST_VERSION)
Definition at line 555 of file lu_target.h.
#define TGT_OST_HDL_HP (flags, name, fn, hp)
Value:
TGT_RPC_HANDLER_HP(OST_FIRST_OPC, flags, name, fn, hp,          \
                           &RQF_ ## name, LUSTRE_OST_VERSION)
Definition at line 558 of file lu_target.h.
#define TGT_QUOTA_HDL (flags, name, fn)
Value:
TGT_RPC_HANDLER(QUOTA_DQACQ, flags, name, fn, &RQF_ ## name,    \
                        LUSTRE_MDS_VERSION)
Definition at line 607 of file lu_target.h.
#define TGT_RPC_HANDLER (base, flags, opc, fn, fmt, version) TGT_RPC_HANDLER_HP(base, flags, opc, fn, NULL, fmt, version)
Definition at line 542 of file lu_target.h.
#define TGT_RPC_HANDLER_HP (base, flags, opc, fn, hp, fmt, version)
Value:
[opc - base] = {                                                        \
        .th_name        = #opc,                                         \
        .th_fail_id     = OBD_FAIL_ ## opc ## _NET,                     \
        .th_opc         = opc,                                          \
        .th_flags       = flags,                                        \
        .th_act         = fn,                                           \
        .th_fmt         = fmt,                                          \
        .th_version     = version,                                      \
        .th_hp          = hp,                                           \
}
Definition at line 531 of file lu_target.h.
#define TGT_SEC_HDL_VAR (flags, name, fn)
Value:
TGT_RPC_HANDLER(SEC_FIRST_OPC, flags, name, fn, NULL,           \
                        LUSTRE_OBD_VERSION)
Definition at line 603 of file lu_target.h.
#define TGT_SEQ_HDL (flags, name, fn)
Value:
TGT_RPC_HANDLER(SEQ_QUERY, flags, name, fn, &RQF_ ## name,      \
                        LUSTRE_MDS_VERSION)
Definition at line 612 of file lu_target.h.
#define TGT_UPDATE_HDL (flags, name, fn)
Value:
TGT_RPC_HANDLER(OUT_UPDATE, flags, name, fn, &RQF_ ## name,     \
                        LUSTRE_MDS_VERSION)
Definition at line 627 of file lu_target.h.
Typedef Documentation
typedef int(* distribute_txn_replay_handler_t)(struct lu_env *env, struct target_distribute_txn_data *tdtd, struct distribute_txn_replay_req *dtrq)
Definition at line 83 of file lu_target.h.
typedef void(* tgt_cb_t)(struct lu_target *lut, __u64 transno, void *data, int err)
Definition at line 421 of file lu_target.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
ESERIOUS
Definition at line 494 of file lu_target.h.
enum tgt_handler_flags
Enumerator:
HABEO_CORPUS
HABEO_CLAVIS
HABEO_REFERO
MUTABOR
Definition at line 279 of file lu_target.h.
Function Documentation
static int clear_serious (int rc) [inline, static]
Definition at line 504 of file lu_target.h.
References ESERIOUS.
Referenced by mdt_intent_getattr(), mdt_intent_reint(), and tgt_handle_request0().
void distribute_txn_fini (const struct lu_env * env, struct target_distribute_txn_data * tdtd)
Stop llog cancel thread.
Stop llog cancel(master/slave) thread on LOD and also destory all of transaction in the list.
Parameters:
[in] cancel log thread to be stopped.
Definition at line 1732 of file update_trans.c.
References distribute_txn_commit_thread_running(), dt_object::do_lu, dtrq_list_destroy(), lu_object_put(), lu_target::lut_tdtd_commit_thread, SVC_STOPPED, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, ptlrpc_thread::t_flags, target_distribute_txn_data::tdtd_batchid_lock, target_distribute_txn_data::tdtd_batchid_obj, target_distribute_txn_data::tdtd_commit_thread_waitq, and target_distribute_txn_data::tdtd_lut.
Referenced by lod_fini_distribute_txn().
struct distribute_txn_replay_req* distribute_txn_get_next_req (struct target_distribute_txn_data * tdtd) [read]
Get next req in the replay list.
Get next req needs to be replayed, since it is a sorted list (by master MDT transno)
Parameters:
[in] tdtd distribute txn data where the replay list is
Return values:
the pointer of update recovery header
Definition at line 565 of file update_recovery.c.
References distribute_txn_replay_req::dtrq_list, list_del_init(), list_empty(), list_entry, list_head::next, target_distribute_txn_data::tdtd_replay_list, and target_distribute_txn_data::tdtd_replay_list_lock.
__u64 distribute_txn_get_next_transno (struct target_distribute_txn_data * tdtd)
Get next transno in the replay list, because this is the sorted list, so it will return the transno of next req in the list.
Parameters:
[in] tdtd distribute txn data where the replay list is
Return values:
the transno of next update in the list
Definition at line 589 of file update_recovery.c.
References __u64, CDEBUG, D_HA, distribute_txn_replay_req::dtrq_list, distribute_txn_replay_req::dtrq_master_transno, list_empty(), list_entry, LPU64, lu_target::lut_obd, list_head::next, obd_device::obd_name, target_distribute_txn_data::tdtd_lut, target_distribute_txn_data::tdtd_replay_list, and target_distribute_txn_data::tdtd_replay_list_lock.
int distribute_txn_init (const struct lu_env * env, struct lu_target * lut, struct target_distribute_txn_data * tdtd, __u32 index)
Start llog cancel thread.
Start llog cancel(master/slave) thread on LOD
Parameters:
[in] cancel log thread to be started.
Return values:
0 if the thread is started successfully.
negative errno if the thread is not being started.
Definition at line 1681 of file update_trans.c.
References distribute_txn_commit_batchid_init(), distribute_txn_commit_thread(), distribute_txn_commit_thread_running(), distribute_txn_commit_thread_stopped(), distribute_txn_replay_handle(), ENTRY, INIT_LIST_HEAD, l_wait_event, lu_target::lut_last_transno, lu_target::lut_tdtd_commit_thread, RETURN, ptlrpc_thread::t_ctl_waitq, target_distribute_txn_data::tdtd_batchid, target_distribute_txn_data::tdtd_batchid_lock, target_distribute_txn_data::tdtd_commit_thread_waitq, target_distribute_txn_data::tdtd_list, target_distribute_txn_data::tdtd_lut, target_distribute_txn_data::tdtd_recovery_threads_count, target_distribute_txn_data::tdtd_recovery_threads_waitq, target_distribute_txn_data::tdtd_refcount, target_distribute_txn_data::tdtd_replay_finish_list, target_distribute_txn_data::tdtd_replay_handler, target_distribute_txn_data::tdtd_replay_list, target_distribute_txn_data::tdtd_replay_list_lock, and target_distribute_txn_data::tdtd_replay_ready.
Referenced by lod_prepare_distribute_txn().
struct distribute_txn_replay_req* distribute_txn_lookup_finish_list (struct target_distribute_txn_data * tdtd, __u64 transno) [read]
Definition at line 609 of file update_recovery.c.
References distribute_txn_replay_req::dtrq_list, distribute_txn_replay_req::dtrq_xid, list_for_each_entry, target_distribute_txn_data::tdtd_replay_finish_list, and target_distribute_txn_data::tdtd_replay_list_lock.
Referenced by is_req_replayed_by_update().
int distribute_txn_replay_handle (struct lu_env * env, struct target_distribute_txn_data * tdtd, struct distribute_txn_replay_req * dtrq)
redo updates on MDT if needed.
During DNE recovery, the recovery thread (target_recovery_thread) will call this function to replay distribute txn updates on all MDTs. It only replay updates on the MDT where the update record is missing.
If the update already exists on the MDT, then it does not need replay the updates on that MDT, and only mark the sub transaction has been committed there.
Parameters:
[in] env execution environment
[in] tdtd target distribute txn data, which holds the replay list and all parameters needed by replay process.
[in] dtrq distribute txn replay req.
Return values:
0 if replay succeeds.
negative errno if replay failes.
Definition at line 1285 of file update_recovery.c.
References CDEBUG, CERROR, class_export_put(), D_HA, distribute_txn_insert_by_batchid(), dt_object::do_lu, dt_obd_name(), distribute_txn_replay_req::dtrq_batchid, distribute_txn_replay_req::dtrq_lur, distribute_txn_replay_req::dtrq_lur_size, distribute_txn_replay_req::dtrq_master_transno, ENTRY, tx_arg::exec_fn, tx_arg::file, GOTO, LASSERT, LCT_NOREF, LCT_SERVER_SESSION, lu_env::le_ses, tx_arg::line, lu_object::lo_dev, lookup_sub_thandle(), lu2dt_dev(), lu_context_enter(), lu_context_exit(), lu_context_fini(), lu_context_init(), lu_env_refill(), lu_object_put(), llog_update_record::lur_update_rec, lu_target::lut_bottom, lu_target::lut_obd, lu_target::lut_reply_data, obd_device::obd_name, tx_arg::object, RETURN, sub_thandle::st_sub_th, thandle_exec_args::ta_argno, thandle_exec_args::ta_args, thandle_exec_args::ta_handle, target_distribute_txn_data::tdtd_committed_batchid, target_distribute_txn_data::tdtd_dt, target_distribute_txn_data::tdtd_lut, tgt_ses_info(), tgt_th_info(), thandle::th_dev, thandle::th_result, top_multiple_thandle::tmt_batchid, top_multiple_thandle::tmt_committed, top_multiple_thandle::tmt_master_sub_dt, top_multiple_thandle::tmt_update_records, top_trans_create(), top_trans_create_tmt(), top_trans_start(), top_trans_stop(), tgt_session_info::tsi_exp, top_thandle::tt_multiple_thandle, tgt_thread_info::tti_transno, thandle_update_records::tur_update_param_count, thandle_update_records::tur_update_params, thandle_update_records::tur_update_records, thandle_update_records::tur_update_records_buf_size, tx_arg::undo_fn, unlikely, update_env_info(), update_records_dump(), update_recovery_exec(), update_recovery_update_ses(), update_thread_info::uti_dtrq, update_thread_info::uti_tea, and update_thread_info::uti_tur.
Referenced by distribute_txn_init().
void dtrq_destroy (struct distribute_txn_replay_req * dtrq)
Destroy distribute txn replay req.
Destroy distribute txn replay req and all of subs.
Parameters:
[in] dtrq distribute txn replqy req to be destroyed.
Definition at line 499 of file update_recovery.c.
References distribute_txn_replay_req::dtrq_list, distribute_txn_replay_req::dtrq_lur, distribute_txn_replay_req::dtrq_lur_size, distribute_txn_replay_req::dtrq_sub_list, distribute_txn_replay_req::dtrq_sub_list_lock, distribute_txn_replay_req_sub::dtrqs_cookie_list, distribute_txn_replay_req_sub::dtrqs_list, LASSERT, list_del(), list_empty(), list_for_each_entry_safe, OBD_FREE_LARGE, OBD_FREE_PTR, and sub_thandle_cookie::stc_list.
Referenced by dtrq_list_destroy(), and insert_update_records_to_replay_list().
void dtrq_list_destroy (struct target_distribute_txn_data * tdtd)
Destroy all of replay req.
Destroy all of replay req in the replay list.
Parameters:
[in] tdtd target distribute txn data where the replay list is.
Definition at line 534 of file update_recovery.c.
References dtrq_destroy(), distribute_txn_replay_req::dtrq_list, list_del_init(), list_for_each_entry_safe, target_distribute_txn_data::tdtd_replay_finish_list, target_distribute_txn_data::tdtd_replay_list, and target_distribute_txn_data::tdtd_replay_list_lock.
Referenced by distribute_txn_fini().
void dtrq_list_dump (struct target_distribute_txn_data * tdtd, unsigned int mask)
Dump updates of distribute txns.
Output all of recovery updates in the distribute txn list to the debug log.
Parameters:
[in] tdtd distribute txn data where all of distribute txn are listed.
[in] mask debug mask
Definition at line 480 of file update_recovery.c.
References distribute_txn_replay_req::dtrq_list, distribute_txn_replay_req::dtrq_lur, list_for_each_entry, llog_update_record::lur_update_rec, target_distribute_txn_data::tdtd_replay_list, target_distribute_txn_data::tdtd_replay_list_lock, and update_records_dump().
struct distribute_txn_replay_req_sub* dtrq_sub_lookup (struct distribute_txn_replay_req * dtrq, __u32 mdt_index) [read]
Lookup distribute sub replay.
Lookup distribute sub replay in the sub list of distribute_txn_replay by mdt_index.
Parameters:
[in] distribute_txn_replay_req the distribute txn replay req to lookup
[in] mdt_index the mdt_index as the key of lookup
Return values:
the pointer of sub replay if it can be found.
NULL if it can not find.
Definition at line 197 of file update_recovery.c.
References distribute_txn_replay_req::dtrq_sub_list, distribute_txn_replay_req_sub::dtrqs_list, distribute_txn_replay_req_sub::dtrqs_mdt_index, and list_for_each_entry.
Referenced by dtrq_sub_create_and_insert(), and update_is_committed().
static int err_serious (int rc) [inline, static]
Definition at line 498 of file lu_target.h.
References ESERIOUS, and LASSERT.
Referenced by fld_handle_lookup(), fld_handle_read(), llog_origin_handle_close(), llog_origin_handle_destroy(), llog_origin_handle_next_block(), llog_origin_handle_open(), llog_origin_handle_prev_block(), llog_origin_handle_read_header(), mdt_close(), mdt_get_info(), mdt_get_root(), mdt_getattr(), mdt_getattr_internal(), mdt_getattr_name_lock(), mdt_getxattr(), mdt_hsm_action(), mdt_hsm_ct_register(), mdt_hsm_progress(), mdt_hsm_state_get(), mdt_hsm_state_set(), mdt_intent_getxattr(), mdt_intent_policy(), mdt_intent_reint(), mdt_quota_dqacq(), mdt_quotactl(), mdt_readpage(), mdt_reint_create(), mdt_reint_internal(), mdt_reint_link(), mdt_reint_opcode(), mdt_reint_open(), mdt_reint_setxattr(), mdt_reint_unlink(), mdt_set_info(), mdt_statfs(), mdt_sync(), mgs_config_read(), mgs_disconnect(), mgs_set_info(), mgs_target_reg(), ofd_get_info_hdl(), ofd_ladvise_hdl(), ofd_punch_hdl(), ofd_quotactl(), ofd_set_info_hdl(), out_handle(), qmt_dqacq(), qmt_intent_policy(), seq_handler(), tgt_bl_callback(), tgt_brw_write(), tgt_convert(), tgt_cp_callback(), tgt_disconnect(), tgt_enqueue(), tgt_obd_idx_read(), tgt_obd_log_cancel(), and tgt_obd_ping().
int insert_update_records_to_replay_list (struct target_distribute_txn_data * tdtd, struct llog_update_record * lur, struct llog_cookie * cookie, __u32 mdt_index)
Insert update records to the replay list.
Allocate distribute txn replay req and insert it into the replay list, then insert the update records into the replay req.
Parameters:
[in] tdtd distribute txn replay data where the replay list is.
[in] record the update record
[in] cookie cookie of the record
[in] index mdt index of the record
Return values:
0 if the adding succeeds.
negative errno if the adding fails.
Definition at line 373 of file update_recovery.c.
References CDEBUG, D_HA, dtrq_append_updates(), dtrq_create(), dtrq_destroy(), dtrq_insert(), distribute_txn_replay_req::dtrq_list, dtrq_lookup(), distribute_txn_replay_req::dtrq_lur, distribute_txn_replay_req::dtrq_lur_size, distribute_txn_replay_req::dtrq_master_transno, dtrq_sub_create_and_insert(), ENTRY, list_del_init(), llog_update_record_size(), LPU64, llog_update_record::lur_update_rec, lu_target::lut_obd, OBD_ALLOC_LARGE, OBD_FREE_LARGE, obd_device::obd_name, RETURN, target_distribute_txn_data::tdtd_batchid, target_distribute_txn_data::tdtd_batchid_lock, target_distribute_txn_data::tdtd_lut, target_distribute_txn_data::tdtd_replay_list_lock, UPDATE_RECORD_CONTINUE, update_records::ur_batchid, update_records::ur_flags, and update_records::ur_master_transno.
Referenced by lod_process_recovery_updates().
bool is_req_replayed_by_update (struct ptlrpc_request * req)
Definition at line 626 of file update_recovery.c.
References distribute_txn_lookup_finish_list(), lu_target::lut_tdtd, ptlrpc_request::rq_export, and ptlrpc_request::rq_xid.
static int is_serious (int rc) [inline, static]
Definition at line 511 of file lu_target.h.
References ESERIOUS.
Referenced by tgt_handle_request0().
bool req_can_reconstruct (struct ptlrpc_request * req, struct tg_reply_data * trd)
Definition at line 2310 of file tgt_handler.c.
References lsd_client_data::lcd_last_close_result, lsd_client_data::lcd_last_close_transno, lsd_client_data::lcd_last_close_xid, lsd_client_data::lcd_last_data, lsd_client_data::lcd_last_result, lsd_client_data::lcd_last_transno, lsd_client_data::lcd_last_xid, lsd_client_data::lcd_pre_versions, lsd_reply_data::lrd_data, lsd_reply_data::lrd_result, lsd_reply_data::lrd_transno, lsd_reply_data::lrd_xid, lustre_msg_get_opc(), MDS_CLOSE, ptlrpc_request::rq_export, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_xid, tg_export_data::ted_lcd, tg_export_data::ted_lcd_lock, tgt_is_multimodrpcs_client(), tgt_lookup_reply(), tg_reply_data::trd_pre_versions, and tg_reply_data::trd_reply.
Referenced by mdt_check_resent(), mdt_intent_fixup_resent(), and tgt_handle_recovery().
static int req_is_replay (struct ptlrpc_request * req) [inline, static]
Definition at line 345 of file lu_target.h.
References LASSERT, lustre_msg_get_flags(), MSG_REPLAY, and ptlrpc_request::rq_reqmsg.
Referenced by mdt_close_internal(), mdt_enoent_version_save(), mdt_fix_lov_magic(), mdt_lookup_version_check(), mdt_mfd_open(), mdt_object_open_lock(), mdt_object_open_unlock(), mdt_open_unpack(), mdt_reint_link(), mdt_reint_open(), mdt_reint_rename_or_migrate(), mdt_rename_unpack(), mdt_unlink_unpack(), mdt_version_check(), mdt_version_get_check(), mdt_version_get_check_save(), mdt_version_get_save(), mdt_version_save(), out_handle(), and tgt_last_rcvd_update().
int tgt_adapt_sptlrpc_conf (struct lu_target * tgt, int initial)
Definition at line 1010 of file tgt_handler.c.
References CERROR, lu_target::lut_obd, lu_target::lut_sptlrpc_lock, lu_target::lut_sptlrpc_rset, sptlrpc_conf_target_get_rules(), sptlrpc_rule_set_free(), sptlrpc_rule_set_init(), sptlrpc_target_update_exp_flavor(), tgt_name(), and unlikely.
Referenced by mdt_init0(), mdt_obd_set_info_async(), ofd_init0(), ofd_set_info_async(), and ofd_set_info_hdl().
int tgt_add_reply_data (const struct lu_env * env, struct lu_target * tgt, struct tg_export_data * ted, struct tg_reply_data * trd, struct thandle * th, bool update_lrd_file)
Definition at line 1075 of file tgt_lastrcvd.c.
References CDEBUG, CERROR, D_TRACE, lsd_client_data::lcd_last_transno, list_add(), lsd_reply_data::lrd_client_gen, lsd_reply_data::lrd_transno, lsd_reply_data::lrd_xid, REPLY_DATA, RETURN, tg_export_data::ted_lcd, tg_export_data::ted_lcd_lock, tg_export_data::ted_reply_cnt, tg_export_data::ted_reply_list, tg_export_data::ted_reply_max, tgt_find_free_reply_slot(), tgt_name(), tgt_reply_data_write(), tg_reply_data::trd_index, tg_reply_data::trd_list, tg_reply_data::trd_reply, tg_reply_data::trd_tag, and unlikely.
Referenced by tgt_last_rcvd_update().
int tgt_bl_callback (struct tgt_session_info * tsi)
Definition at line 1433 of file tgt_handler.c.
References err_serious().
void tgt_boot_epoch_update (struct lu_target * lut)
Update boot epoch when recovery ends.
The recovery is not yet finished and final queue can still be updated with resend requests. Move final list to separate one for processing
go through list of exports participated in recovery and set new epoch for them
return list back at once
Clear MULTI RPCS incompatibility flag if
target is MDT and
there is no client to recover or the recovery was aborted
update server epoch
Definition at line 690 of file tgt_lastrcvd.c.
References __u64, CERROR, obd_export::exp_delayed, obd_export::exp_vbr_failed, INIT_LIST_HEAD, LASSERT, LCT_DT_THREAD, list_for_each_entry, list_splice_init(), lr_epoch, LR_EPOCH_BITS, lr_server_data::lsd_feature_incompat, lr_server_data::lsd_start_epoch, lu_env_fini(), lu_env_init(), LUSTRE_MDT_NAME, lu_target::lut_last_transno, lu_target::lut_lsd, lu_target::lut_obd, lu_target::lut_translock, obd_device::obd_abort_recovery, obd_device::obd_final_req_queue, OBD_INCOMPAT_MULTI_RPCS, obd_device::obd_max_recoverable_clients, obd_device::obd_name, obd_device::obd_recovery_task_lock, obd_device::obd_stopping, obd_device::obd_type, ptlrpc_request::rq_export, tgt_client_epoch_update(), tgt_server_data_update(), and obd_type::typ_name.
int tgt_brw_lock (struct ldlm_namespace * ns, struct ldlm_res_id * res_id, struct obd_ioobj * obj, struct niobuf_remote * nb, struct lustre_handle * lh, enum ldlm_mode mode)
Definition at line 1716 of file tgt_handler.c.
References __u64, ENTRY, obd_ioobj::ioo_bufcnt, LASSERT, LCK_PR, LCK_PW, lustre_handle_is_used(), OBD_BRW_SRVLOCK, RETURN, and tgt_extent_lock().
Referenced by tgt_brw_read(), and tgt_brw_write().
int tgt_brw_read (struct tgt_session_info * tsi)
Definition at line 1837 of file tgt_handler.c.
References ptlrpc_bulk_frag_ops::add_kiov_frag, ptlrpc_bulk_desc::bd_frag_ops, CDEBUG, CERROR, CFS_FAIL_PRECHECK(), cfs_fail_val, cfs_time_current_sec(), cfs_time_seconds(), cksum_type_pack(), cksum_type_unpack(), D_INFO, D_PAGE, DOSTID, ENTRY, obd_export::exp_client_uuid, obd_export::exp_obd, GOTO, obd_ioobj::ioo_oid, ioobj_max_brw_get, l_wait_event, LASSERT, LCK_PR, LCONSOLE_WARN, libcfs_id2str(), likely, niobuf_local::lnb_rc, tgt_thread_big_cache::local, LWI_INTR, LWI_TIMEOUT_INTR, obdo::o_flags, obdo::o_valid, ost_body::oa, OBD_BRW_READ, obd_commitrw(), obd_device::obd_evict_inprogress, obd_device::obd_evict_inprogress_waitq, obd_export_nid2str(), OBD_FAIL_CHECK, OBD_FAIL_OST_BRW_PAUSE_BULK, OBD_FAIL_OST_BRW_READ_BULK, OBD_FAIL_OST_DROP_REQ, OBD_FAIL_OST_READ_SIZE, OBD_FAIL_PTLRPC_CLIENT_BULK_CB2, OBD_FAIL_TIMEOUT, OBD_MD_FLCKSUM, OBD_MD_FLFLAGS, obd_device::obd_name, obd_device::obd_namespace, obd_preprw(), obd_timeout, obd_uuid2str(), OST_BULK_PORTAL, OST_IO_PORTAL, OST_READ, POSTID, PTLRPC_BULK_BUF_KIOV, ptlrpc_bulk_kiov_nopin_ops, PTLRPC_BULK_PUT_SOURCE, ptlrpc_free_bulk(), ptlrpc_lprocfs_brw(), PTLRPC_MAX_BRW_PAGES, ptlrpc_req2svc(), ptlrpc_req_drop_rs(), req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_NIOBUF_REMOTE, RMF_OBD_IOOBJ, RMF_OST_BODY, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_deadline, ptlrpc_request::rq_export, ptlrpc_request::rq_no_reply, ptlrpc_request::rq_peer, ptlrpc_request::rq_pill, tgt_brw_lock(), tgt_brw_unlock(), tgt_checksum_bulk(), tgt_drop_id(), tgt_name(), tgt_ses_req(), tgt_session_info::tsi_env, tgt_session_info::tsi_exp, tgt_session_info::tsi_ost_body, tgt_session_info::tsi_pill, tgt_session_info::tsi_resid, tgt_session_info::tsi_tgt, and unlikely.
void tgt_brw_unlock (struct obd_ioobj * obj, struct niobuf_remote * niob, struct lustre_handle * lh, enum ldlm_mode mode)
Definition at line 1742 of file tgt_handler.c.
References ENTRY, EXIT, obd_ioobj::ioo_bufcnt, LASSERT, LCK_PR, LCK_PW, lustre_handle_is_used(), OBD_BRW_SRVLOCK, niobuf_remote::rnb_flags, and tgt_extent_unlock().
Referenced by tgt_brw_read(), and tgt_brw_write().
int tgt_brw_write (struct tgt_session_info * tsi)
Definition at line 2073 of file tgt_handler.c.
References ptlrpc_bulk_frag_ops::add_kiov_frag, ptlrpc_bulk_desc::bd_frag_ops, ptlrpc_connection::c_peer, ptlrpc_connection::c_self, CDEBUG, CERROR, CFS_FAIL_TIMEOUT, cfs_fail_val, cfs_time_current_sec(), cksum_type_pack(), cksum_type_unpack(), D_CACHE, D_INFO, DEBUG_REQ, DOSTID, ENTRY, err_serious(), obd_export::exp_client_uuid, obd_export::exp_connection, obd_export::exp_obd, GOTO, obd_ioobj::ioo_oid, ioobj_max_brw_get, LASSERT, LCK_PW, LCONSOLE_WARN, libcfs_id2str(), niobuf_local::lnb_len, niobuf_local::lnb_page, niobuf_local::lnb_page_offset, niobuf_local::lnb_rc, tgt_thread_big_cache::local, lustre_msg_get_flags(), memory_pressure_clr(), memory_pressure_set(), MSG_REPLAY, MSG_RESENT, lnet_process_id_t::nid, obdo::o_flags, obdo::o_valid, ost_body::oa, OBD_BRW_MEMALLOC, OBD_BRW_WRITE, OBD_CKSUM_CRC32, obd_commitrw(), obd_export_nid2str(), OBD_FAIL_CHECK, OBD_FAIL_OST_BRW_PAUSE_BULK, OBD_FAIL_OST_BRW_PAUSE_PACK, OBD_FAIL_OST_BRW_WRITE_BULK, OBD_FAIL_OST_BRW_WRITE_BULK2, OBD_FAIL_OST_DROP_REQ, OBD_FAIL_OST_ENOSPC, OBD_FAIL_OST_EROFS, OBD_FAIL_TIMEOUT, OBD_FL_CKSUM_ALL, OBD_FL_MMAP, OBD_MD_FLATIME, OBD_MD_FLCKSUM, OBD_MD_FLFLAGS, OBD_MD_FLGRANT, OBD_MD_FLMTIME, obd_device::obd_name, obd_device::obd_namespace, obd_preprw(), obd_timeout, obd_uuid2str(), OST_BULK_PORTAL, OST_IO_PORTAL, OST_WRITE, POSTID, PTLRPC_BULK_BUF_KIOV, PTLRPC_BULK_GET_SINK, ptlrpc_bulk_kiov_nopin_ops, ptlrpc_free_bulk(), ptlrpc_lprocfs_brw(), PTLRPC_MAX_BRW_PAGES, ptlrpc_req2svc(), ptlrpc_req_drop_rs(), RCL_CLIENT, RCL_SERVER, req_capsule_client_get(), req_capsule_get_size(), req_capsule_server_get(), req_capsule_server_pack(), req_capsule_set_size(), RETURN, RMF_NIOBUF_REMOTE, RMF_OBD_IOOBJ, RMF_OST_BODY, RMF_RCS, niobuf_remote::rnb_len, ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_deadline, ptlrpc_request::rq_export, ptlrpc_request::rq_no_reply, ptlrpc_request::rq_peer, ptlrpc_request::rq_pill, ptlrpc_request::rq_reqmsg, tgt_brw_lock(), tgt_brw_unlock(), tgt_checksum_bulk(), tgt_drop_id(), tgt_name(), tgt_ses_req(), tgt_warn_on_cksum(), tgt_session_info::tsi_env, tgt_session_info::tsi_ost_body, tgt_session_info::tsi_resid, tgt_session_info::tsi_tgt, and unlikely.
int tgt_client_add (const struct lu_env * env, struct obd_export * exp, int)
Definition at line 976 of file tgt_lastrcvd.c.
References CDEBUG, CERROR, D_INFO, ENTRY, exp_connect_flags(), LASSERT, LASSERTF, LBUG, lsd_client_data::lcd_generation, lsd_client_data::lcd_uuid, lr_server_data::lsd_client_size, lr_server_data::lsd_client_start, lu_target::lut_client_bitmap, lu_target::lut_lsd, lu_target::lut_num_clients, lu_target::lut_obd, OBD_CONNECT_LIGHTWEIGHT, obd_device::obd_name, obd_device::obd_uuid, RETURN, tg_export_data::ted_lcd, tg_export_data::ted_lcd_lock, tg_export_data::ted_lr_idx, tg_export_data::ted_lr_off, and obd_uuid::uuid.
Referenced by tgt_clients_data_init().
int tgt_client_alloc (struct obd_export * exp)
Allocate in-memory data for client slot related to export.
Definition at line 376 of file tgt_lastrcvd.c.
References ENTRY, obd_export::exp_obd, INIT_LIST_HEAD, LASSERT, OBD_ALLOC_PTR, obd_device::obd_self_export, and RETURN.
Referenced by mdt_init_export(), and ofd_init_export().
int tgt_client_data_read (const struct lu_env * env, struct lu_target * tg, struct lsd_client_data * lcd, loff_t * off, int index)
Definition at line 441 of file tgt_lastrcvd.c.
References CDEBUG, check_lcd(), D_INFO, dt_record_read(), lsd_client_data::lcd_last_close_result, lsd_client_data::lcd_last_close_transno, lsd_client_data::lcd_last_close_xid, lsd_client_data::lcd_last_data, lsd_client_data::lcd_last_result, lsd_client_data::lcd_last_transno, lsd_client_data::lcd_last_xid, lcd_le_to_cpu(), lsd_client_data::lcd_uuid, LPU64, lu_target::lut_last_rcvd, lu_target::lut_obd, obd_device::obd_name, ptlrpc_status_ntoh(), tgt_th_info(), tgt_thread_info::tti_buf, tti_buf_lcd(), and tgt_thread_info::tti_lcd.
Referenced by tgt_clients_data_init().
int tgt_client_data_write (const struct lu_env * env, struct lu_target * tg, struct lsd_client_data * lcd, loff_t * off, struct thandle * th)
Definition at line 468 of file tgt_lastrcvd.c.
References dt_object_locate(), dt_record_write(), lcd_cpu_to_le(), lsd_client_data::lcd_last_close_result, lsd_client_data::lcd_last_result, lu_target::lut_last_rcvd, ptlrpc_status_hton(), tgt_th_info(), thandle::th_dev, tgt_thread_info::tti_buf, tti_buf_lcd(), and tgt_thread_info::tti_lcd.
Referenced by tgt_client_data_update(), tgt_last_rcvd_update(), and tgt_last_rcvd_update_echo().
int tgt_client_del (const struct lu_env * env, struct obd_export * exp)
Definition at line 1013 of file tgt_lastrcvd.c.
References CDEBUG, CERROR, class_exp2obd(), D_ERROR, D_INFO, ENTRY, exp_connect_flags(), obd_export::exp_flags, LASSERT, LBUG, lsd_client_data::lcd_uuid, lu_target::lut_client_bitmap, lu_target::lut_obd, OBD_CONNECT_LIGHTWEIGHT, obd_device::obd_name, OBD_OPT_FAILOVER, obd_device::obd_uuid, RETURN, tg_export_data::ted_lcd, tg_export_data::ted_lcd_lock, tg_export_data::ted_lr_idx, tg_export_data::ted_lr_off, tgt_client_data_update(), tgt_server_data_update(), unlikely, and obd_uuid::uuid.
Referenced by mdt_export_cleanup(), and ofd_obd_disconnect().
void tgt_client_free (struct obd_export * exp)
Free in-memory data for client slot related to export.
Definition at line 395 of file tgt_lastrcvd.c.
References CERROR, cfs_hash_del(), obd_export::exp_gen_hash, obd_export::exp_obd, hlist_unhashed(), LASSERT, LBUG, lsd_client_data::lcd_generation, list_for_each_entry_safe, lu_target::lut_client_bitmap, lu_target::lut_num_clients, OBD_FREE_PTR, obd_device::obd_gen_hash, obd_device::obd_name, obd_device::obd_self_export, obd_device::obd_stopping, OBT_MAGIC, tg_export_data::ted_lcd, tg_export_data::ted_lcd_lock, tg_export_data::ted_lr_idx, tg_export_data::ted_reply_last, tg_export_data::ted_reply_list, tgt_free_reply_data(), tgt_is_multimodrpcs_client(), tgt_release_reply_data(), tg_reply_data::trd_list, and obd_device::u.
Referenced by mdt_destroy_export(), mdt_init_export(), and ofd_destroy_export().
int tgt_client_new (const struct lu_env * env, struct obd_export * exp)
Add new client to the last_rcvd upon new connection.
We use a bitmap to locate a free space in the last_rcvd file and initialize tg_export_data.
Definition at line 890 of file tgt_lastrcvd.c.
References CDEBUG, CERROR, D_INFO, ENTRY, exp_connect_flags(), obd_export::exp_obd, LASSERT, LASSERTF, lsd_client_data::lcd_generation, lsd_client_data::lcd_uuid, LR_MAX_CLIENTS, lr_server_data::lsd_client_size, lr_server_data::lsd_client_start, lr_server_data::lsd_feature_incompat, lu_target::lut_client_bitmap, lu_target::lut_client_generation, lu_target::lut_lsd, lu_target::lut_num_clients, lu_target::lut_obd, OBD_CONNECT_LIGHTWEIGHT, OBD_FAIL_CHECK, OBD_FAIL_MDS_CLIENT_ADD, OBD_FAIL_TGT_CLIENT_ADD, OBD_INCOMPAT_MULTI_RPCS, obd_device::obd_name, obd_device::obd_uuid, RETURN, tg_export_data::ted_lcd, tg_export_data::ted_lr_idx, tg_export_data::ted_lr_off, tgt_client_data_update(), tgt_is_multimodrpcs_client(), tgt_server_data_update(), and obd_uuid::uuid.
Referenced by mdt_obd_connect(), and ofd_obd_connect().
static __u64 tgt_conn_flags (struct tgt_session_info * tsi) [inline, static]
Definition at line 339 of file lu_target.h.
References exp_connect_flags(), LASSERT, and tgt_session_info::tsi_exp.
Referenced by tgt_request_preprocess().
int tgt_connect (struct tgt_session_info * tsi)
Definition at line 1039 of file tgt_handler.c.
References class_export_get(), ENTRY, obd_export::exp_connect_data, exp_connect_flags_ptr(), obd_export::exp_lock, GOTO, obd_disconnect(), obd_connect_data::ocd_brw_size, obd_connect_data::ocd_connect_flags, req_capsule_server_get(), RETURN, RMF_CONNECT_DATA, tgt_connect_check_sptlrpc(), tgt_init_sec_level(), tgt_ses_req(), tgt_session_info::tsi_exp, and tgt_session_info::tsi_pill.
Referenced by mdt_tgt_connect(), and mgs_connect().
int tgt_connect_check_sptlrpc (struct ptlrpc_request * req, struct obd_export * exp)
Definition at line 947 of file tgt_handler.c.
References ptlrpc_connection::c_peer, CERROR, obd_export::exp_connection, obd_export::exp_flvr, obd_export::exp_lock, obd_export::exp_obd, obd_export::exp_sp_peer, LASSERT, libcfs_nid2str(), LNET_NETTYP(), LNET_NIDNET(), LOLND, LUSTRE_ECHO_NAME, LUSTRE_MGS_NAME, lu_target::lut_obd, lu_target::lut_slice, lu_target::lut_sptlrpc_lock, lu_target::lut_sptlrpc_rset, lnet_process_id_t::nid, obd_device::obd_type, ptlrpc_request::rq_flvr, ptlrpc_request::rq_peer, sptlrpc_flavor::sf_rpc, SPTLRPC_FLVR_ANY, SPTLRPC_FLVR_INVALID, SPTLRPC_FLVR_NULL, sptlrpc_part2name(), sptlrpc_target_choose_flavor(), sptlrpc_target_export_check(), tgt_name(), obd_type::typ_name, and unlikely.
Referenced by tgt_connect().
int tgt_convert (struct tgt_session_info * tsi)
Definition at line 1419 of file tgt_handler.c.
References ENTRY, err_serious(), LASSERT, RETURN, ptlrpc_request::rq_status, tgt_ses_req(), and tgt_session_info::tsi_dlm_req.
void tgt_counter_incr (struct obd_export * exp, int opcode)
Definition at line 818 of file tgt_handler.c.
References obd_export::exp_nid_stats, obd_export::exp_obd, lprocfs_counter_incr(), nid_stat::nid_stats, and obd_device::obd_stats.
Referenced by mgs_exception(), mgs_obd_connect(), mgs_obd_disconnect(), mgs_obd_reconnect(), mgs_target_del(), and mgs_target_reg().
int tgt_cp_callback (struct tgt_session_info * tsi)
Definition at line 1438 of file tgt_handler.c.
References err_serious().
void tgt_discard_slc_lock (struct ldlm_lock * lock)
Definition at line 86 of file tgt_main.c.
References LASSERT, ldlm_is_cbpending, LDLM_LOCK_PUT, list_del_init(), list_empty(), lock_res_and_lock(), uncommitted_slc_locks_guard, and unlock_res_and_lock().
Referenced by mdt_remote_blocking_ast().
int tgt_disconnect (struct tgt_session_info * uti)
Definition at line 1076 of file tgt_handler.c.
References ENTRY, err_serious(), RETURN, and tgt_ses_req().
Referenced by mgs_disconnect().
static void tgt_drop_id (struct obd_export * exp, struct obdo * oa) [inline, static]
Do not return server-side uid/gid to remote client.
Definition at line 519 of file lu_target.h.
References exp_connect_rmtclient(), obdo::o_gid, obdo::o_uid, obdo::o_valid, OBD_MD_FLGID, OBD_MD_FLUID, and unlikely.
Referenced by ofd_getattr_hdl(), ofd_setattr_hdl(), tgt_brw_read(), and tgt_brw_write().
int tgt_enqueue (struct tgt_session_info * tsi)
Definition at line 1385 of file tgt_handler.c.
References ENTRY, err_serious(), obd_export::exp_obd, LASSERT, ldlm_handle_enqueue0(), LUT_FAIL_CLASS, LUT_FAIL_MDT, LUT_FAIL_MGT, LUT_FAIL_OST, OBD_FAIL_LDLM_REPLY, OBD_FAIL_MDS_LDLM_REPLY_NET, OBD_FAIL_MGS_LDLM_REPLY_NET, OBD_FAIL_OST_LDLM_REPLY_NET, obd_device::obd_namespace, RETURN, ptlrpc_request::rq_status, tgt_ses_req(), tgt_session_info::tsi_dlm_req, tgt_session_info::tsi_exp, and tgt_session_info::tsi_reply_fail_id.
int tgt_extent_lock (struct ldlm_namespace * ns, struct ldlm_res_id * res_id, __u64 start, __u64 end, struct lustre_handle * lh, int mode, __u64 * flags)
Helper function for getting server side [start, start+count] DLM lock if asked by client.
Definition at line 1676 of file tgt_handler.c.
References ELDLM_OK, ldlm_extent::end, ENTRY, ldlm_extent::gid, ldlm_policy_data::l_extent, LASSERT, ldlm_blocking_ast(), ldlm_cli_enqueue_local(), ldlm_completion_ast(), LDLM_EXTENT, ldlm_glimpse_ast(), lustre_handle_is_used(), LVB_T_NONE, OBD_OBJECT_EOF, RETURN, and ldlm_extent::start.
Referenced by lock_region(), ofd_getattr_hdl(), ofd_punch_hdl(), and tgt_brw_lock().
void tgt_extent_unlock (struct lustre_handle * lh, enum ldlm_mode mode)
Definition at line 1709 of file tgt_handler.c.
References LASSERT, ldlm_lock_decref(), and lustre_handle_is_used().
Referenced by ofd_getattr_hdl(), ofd_punch_hdl(), tgt_brw_unlock(), and unlock_zero_regions().
void tgt_fini (const struct lu_env * env, struct lu_target * lut)
Definition at line 283 of file tgt_main.c.
References CERROR, dt_object::do_lu, dt_txn_callback_del(), ENTRY, EXIT, LR_MAX_CLIENTS, lr_server_data::lsd_feature_incompat, lu_object_put(), lu_target::lut_bottom, lu_target::lut_client_bitmap, lu_target::lut_last_rcvd, lu_target::lut_lsd, lu_target::lut_num_clients, lu_target::lut_obd, lu_target::lut_reply_bitmap, lu_target::lut_reply_data, LUT_REPLY_SLOTS_MAX_CHUNKS, LUT_REPLY_SLOTS_PER_CHUNK, lu_target::lut_sptlrpc_rset, lu_target::lut_txn_cb, OBD_FREE, OBD_INCOMPAT_MULTI_RPCS, obd_device::obd_name, sptlrpc_rule_set_free(), and tgt_server_data_update().
Referenced by mdt_fini(), mdt_init0(), mgs_device_fini(), mgs_init0(), ofd_fini(), and ofd_init0().
int tgt_hpreq_handler (struct ptlrpc_request * req)
Assign high priority operations to the request if needed.
Definition at line 785 of file tgt_handler.c.
References ENTRY, RCL_SERVER, req_capsule_init(), RETURN, ptlrpc_request::rq_export, ptlrpc_request::rq_pill, tgt_handler_find_check(), tgt_request_preprocess(), tgt_ses_info(), tgt_handler::th_hp, tgt_session_info::tsi_env, tgt_session_info::tsi_exp, tgt_session_info::tsi_pill, tgt_session_info::tsi_tgt, and unlikely.
Referenced by ost_setup().
int tgt_init (const struct lu_env * env, struct lu_target * lut, struct obd_device * obd, struct dt_device * dt, struct tgt_opc_slice * slice, int request_fail_id, int reply_fail_id)
Definition at line 147 of file tgt_main.c.
References CERROR, dt_device::dd_lu_dev, dt_object::do_lu, dt_object_format::dof_type, dt_find_or_create(), dt_mode_to_dft(), dt_txn_callback_add(), dt_txn_callback_del(), dt_txn_callback::dtc_cookie, dt_txn_callback::dtc_linkage, dt_txn_callback::dtc_tag, dt_txn_callback::dtc_txn_commit, dt_txn_callback::dtc_txn_start, dt_txn_callback::dtc_txn_stop, ENTRY, GOTO, INIT_LIST_HEAD, lu_attr::la_mode, LA_MODE, lu_attr::la_valid, LASSERT, LAST_RECV_OID, LCT_DT_THREAD, LCT_MD_THREAD, lu_device::ld_site, LR_MAX_CLIENTS, lu_site::ls_tgt, lu_local_obj_fid(), lu_object_put(), LUSTRE_MDT_NAME, lu_target::lut_bottom, lu_target::lut_client_bitmap, lu_target::lut_client_bitmap_lock, lu_target::lut_client_generation, lu_target::lut_flags_lock, lu_target::lut_last_rcvd, lu_target::lut_num_clients, lu_target::lut_obd, lu_target::lut_reply_bitmap, lu_target::lut_reply_data, lu_target::lut_reply_fail_id, LUT_REPLY_SLOTS_MAX_CHUNKS, lu_target::lut_request_fail_id, lu_target::lut_slice, lu_target::lut_sptlrpc_lock, lu_target::lut_sptlrpc_rset, lu_target::lut_sync_count, lu_target::lut_sync_lock_cancel, lu_target::lut_translock, lu_target::lut_txn_cb, NEVER_SYNC_ON_CANCEL, OBD_ALLOC, OBD_FREE, obd_device::obd_replayable, obd_device::obd_type, OBT_MAGIC, REPLY_DATA_OID, RETURN, sptlrpc_rule_set_init(), tgt_name(), tgt_reply_data_init(), tgt_server_data_init(), tgt_txn_start_cb(), tgt_txn_stop_cb(), obd_type::typ_name, and obd_device::u.
Referenced by mdt_init0(), mgs_init0(), and ofd_init0().
void tgt_io_thread_done (struct ptlrpc_thread * thread)
Definition at line 1652 of file tgt_handler.c.
References ENTRY, EXIT, LASSERT, OBD_FREE_LARGE, and ptlrpc_thread::t_data.
Referenced by ost_setup().
int tgt_io_thread_init (struct ptlrpc_thread * thread)
Definition at line 1632 of file tgt_handler.c.
References ENTRY, LASSERT, OBD_ALLOC_LARGE, RETURN, and ptlrpc_thread::t_data.
Referenced by ost_setup().
static bool tgt_is_multimodrpcs_client (struct obd_export * exp) [inline, static]
Definition at line 351 of file lu_target.h.
References exp_connect_flags(), and OBD_CONNECT_MULTIMODRPCS.
Referenced by mdt_empty_transno(), process_req_last_xid(), req_can_reconstruct(), tgt_client_free(), tgt_client_new(), tgt_last_rcvd_update(), and tgt_txn_start_cb().
int tgt_last_commit_cb_add (struct thandle * th, struct lu_target * lut, struct obd_export * exp, __u64 transno)
Definition at line 798 of file tgt_lastrcvd.c.
References class_export_cb_get, class_export_cb_put, dt_txn_commit_cb::dcb_func, dt_txn_commit_cb::dcb_linkage, dt_txn_commit_cb::dcb_name, dt_trans_cb_add(), exp_connect_flags(), INIT_LIST_HEAD, tgt_last_committed_callback::llcc_cb, tgt_last_committed_callback::llcc_exp, tgt_last_committed_callback::llcc_tgt, tgt_last_committed_callback::llcc_transno, OBD_ALLOC_PTR, OBD_CONNECT_LIGHTWEIGHT, OBD_FREE_PTR, strlcpy(), and tgt_cb_last_committed().
Referenced by tgt_last_rcvd_update(), and tgt_last_rcvd_update_echo().
int tgt_llog_close (struct tgt_session_info * tsi)
Definition at line 1467 of file tgt_handler.c.
References ENTRY, llog_origin_handle_close(), RETURN, and tgt_ses_req().
int tgt_llog_destroy (struct tgt_session_info * tsi)
Definition at line 1480 of file tgt_handler.c.
References ENTRY, llog_origin_handle_destroy(), RETURN, and tgt_ses_req().
int tgt_llog_next_block (struct tgt_session_info * tsi)
Definition at line 1503 of file tgt_handler.c.
References ENTRY, llog_origin_handle_next_block(), RETURN, and tgt_ses_req().
int tgt_llog_open (struct tgt_session_info * tsi)
Definition at line 1455 of file tgt_handler.c.
References ENTRY, llog_origin_handle_open(), RETURN, and tgt_ses_req().
Referenced by mgs_llog_open().
int tgt_llog_prev_block (struct tgt_session_info * tsi)
Definition at line 1515 of file tgt_handler.c.
References ENTRY, llog_origin_handle_prev_block(), RETURN, and tgt_ses_req().
int tgt_llog_read_header (struct tgt_session_info * tsi)
Definition at line 1491 of file tgt_handler.c.
References ENTRY, llog_origin_handle_read_header(), RETURN, and tgt_ses_req().
bool tgt_lookup_reply (struct ptlrpc_request * req, struct tg_reply_data * trd)
Definition at line 1974 of file tgt_lastrcvd.c.
References CDEBUG, D_TRACE, ptlrpc_request::rq_export, ptlrpc_request::rq_xid, tgt_lookup_reply_by_xid(), and tgt_name().
Referenced by req_can_reconstruct().
struct tg_reply_data* tgt_lookup_reply_by_xid (struct tg_export_data * ted, __u64 xid) [read]
Definition at line 1953 of file tgt_lastrcvd.c.
References list_for_each_entry, lsd_reply_data::lrd_xid, tg_export_data::ted_lcd_lock, tg_export_data::ted_reply_list, tg_reply_data::trd_list, and tg_reply_data::trd_reply.
Referenced by tgt_lookup_reply().
char* tgt_name (struct lu_target * tgt)
Definition at line 51 of file tgt_handler.c.
References LASSERT, lu_target::lut_obd, and obd_device::obd_name.
Referenced by ll_rename(), mdt_get_info(), mdt_init_idmap(), mdt_set_info(), mgs_llog_open(), mgs_set_info(), ofd_get_info_hdl(), ofd_punch_hpreq_check(), ofd_rw_hpreq_check(), ofd_set_info_hdl(), ofd_statfs_hdl(), out_attr_get(), out_attr_set(), out_create(), out_destroy(), out_handle(), out_index_delete(), out_index_insert(), out_index_lookup(), out_read(), out_write(), out_xattr_del(), out_xattr_get(), out_xattr_set(), tgt_adapt_sptlrpc_conf(), tgt_add_reply_data(), tgt_blocking_ast(), tgt_brw_read(), tgt_brw_write(), tgt_checksum_bulk(), tgt_clear_reply_slot(), tgt_clients_data_init(), tgt_connect_check_sptlrpc(), tgt_free_reply_data(), tgt_handle_request0(), tgt_handler_find_check(), tgt_init(), tgt_init_sec_level(), tgt_io_data_unpack(), tgt_last_rcvd_update(), tgt_lookup_reply(), tgt_mdt_body_unpack(), tgt_ost_body_unpack(), tgt_release_reply_data(), tgt_reply_data_init(), tgt_request_handle(), tgt_server_data_init(), tgt_set_reply_slot(), and tgt_validate_obdo().
int tgt_new_client_cb_add (struct thandle * th, struct obd_export * exp)
Definition at line 859 of file tgt_lastrcvd.c.
References class_export_cb_get, class_export_cb_put, dt_txn_commit_cb::dcb_func, dt_txn_commit_cb::dcb_linkage, dt_txn_commit_cb::dcb_name, dt_trans_cb_add(), INIT_LIST_HEAD, tgt_new_client_callback::lncc_cb, tgt_new_client_callback::lncc_exp, OBD_ALLOC_PTR, OBD_FREE_PTR, strlcpy(), and tgt_cb_new_client().
Referenced by tgt_client_data_update().
int tgt_obd_ping (struct tgt_session_info * tsi)
Definition at line 1093 of file tgt_handler.c.
References ENTRY, err_serious(), RETURN, and tgt_ses_req().
static void tgt_opdata_clear (const struct lu_env * env, __u64 flags) [inline, static]
Definition at line 266 of file lu_target.h.
References lu_env::le_ses, tgt_ses_info(), and tgt_session_info::tsi_opdata.
Referenced by mdt_clear_disposition().
static void tgt_opdata_set (const struct lu_env * env, __u64 flags) [inline, static]
Definition at line 256 of file lu_target.h.
References lu_env::le_ses, tgt_ses_info(), and tgt_session_info::tsi_opdata.
Referenced by mdt_set_disposition().
void tgt_register_lfsck_in_notify (int(*)(const struct lu_env *, struct dt_device *, struct lfsck_request *, struct thandle *) notify)
Definition at line 1559 of file tgt_handler.c.
References tgt_lfsck_in_notify.
Referenced by lfsck_init().
void tgt_register_lfsck_query (int(*)(const struct lu_env *, struct dt_device *, struct lfsck_request *, struct lfsck_reply *, struct lfsck_query *) query)
Definition at line 1574 of file tgt_handler.c.
References tgt_lfsck_query.
Referenced by lfsck_init().
int tgt_reply_data_init (const struct lu_env * env, struct lu_target * tgt)
Definition at line 1806 of file tgt_lastrcvd.c.
References CDEBUG, CERROR, cfs_hash_getref(), cfs_hash_lookup(), cfs_hash_putref(), class_export_put(), D_HA, D_INFO, dt_attr_get(), obd_export::exp_last_committed, GOTO, lu_attr::la_size, list_add(), lsd_reply_data::lrd_client_gen, lsd_reply_data::lrd_transno, lsd_reply_data::lrd_xid, lrh, lsd_reply_header::lrh_header_size, LRH_MAGIC, lsd_reply_header::lrh_magic, lsd_reply_header::lrh_reply_size, lu_target::lut_last_transno, lu_target::lut_obd, lu_target::lut_reply_data, lu_target::lut_translock, max, OBD_ALLOC_PTR, OBD_FREE_PTR, obd_device::obd_gen_hash, obd_device::obd_last_committed, REPLY_DATA, tg_export_data::ted_lcd_lock, tg_export_data::ted_reply_cnt, tg_export_data::ted_reply_list, tg_export_data::ted_reply_max, tgt_name(), tgt_reply_data_read(), tgt_reply_header_read(), tgt_reply_header_write(), tgt_set_reply_slot(), tgt_th_info(), tg_reply_data::trd_index, tg_reply_data::trd_list, tg_reply_data::trd_pre_versions, tg_reply_data::trd_reply, tg_reply_data::trd_tag, tgt_thread_info::tti_attr, and tgt_thread_info::tti_lrd.
Referenced by tgt_init().
int tgt_request_handle (struct ptlrpc_request * req)
Definition at line 653 of file tgt_handler.c.
Referenced by mds_start_ptlrpc_service(), mdt_prepare(), mgs_init0(), ofd_prepare(), and ost_setup().
void tgt_save_slc_lock (struct ldlm_lock * lock, __u64 transno)
Definition at line 54 of file tgt_main.c.
References ldlm_is_cbpending, LDLM_LOCK_PUT, list_add_tail(), list_empty(), lock_res_and_lock(), uncommitted_slc_locks, uncommitted_slc_locks_guard, and unlock_res_and_lock().
Referenced by mdt_save_remote_lock().
int tgt_sec_ctx_fini (struct tgt_session_info * tsi)
int tgt_sec_ctx_init (struct tgt_session_info * tsi)
int tgt_sec_ctx_init_cont (struct tgt_session_info * tsi)
int tgt_send_buffer (struct tgt_session_info * tsi, struct lu_rdbuf * rdbuf)
Definition at line 1112 of file tgt_handler.c.
References ptlrpc_bulk_frag_ops::add_iov_frag, ptlrpc_bulk_desc::bd_frag_ops, ENTRY, lu_buf::lb_buf, lu_buf::lb_len, MDS_BULK_PORTAL, PTLRPC_BULK_BUF_KVEC, ptlrpc_bulk_kvec_ops, PTLRPC_BULK_PUT_SOURCE, ptlrpc_free_bulk(), lu_rdbuf::rb_bufs, lu_rdbuf::rb_nbufs, RETURN, ptlrpc_request::rq_export, tgt_ses_req(), tgt_th_info(), tgt_session_info::tsi_env, tgt_thread_info::tti_u, and tgt_thread_info::update.
Referenced by out_read().
int tgt_sendpage (struct tgt_session_info * tsi, struct lu_rdpg * rdpg, int nob)
Definition at line 1141 of file tgt_handler.c.
References ptlrpc_bulk_frag_ops::add_kiov_frag, ptlrpc_bulk_desc::bd_frag_ops, ptlrpc_bulk_desc::bd_nob, ENTRY, exp_connect_flags(), LASSERT, MDS_BULK_PORTAL, min_t, OBD_CONNECT_BRW_SIZE, PTLRPC_BULK_BUF_KIOV, ptlrpc_bulk_kiov_pin_ops, PTLRPC_BULK_PUT_SOURCE, ptlrpc_free_bulk(), tgt_thread_info::rdpg, RETURN, lu_rdpg::rp_count, lu_rdpg::rp_npages, lu_rdpg::rp_pages, ptlrpc_request::rq_export, tgt_ses_req(), tgt_th_info(), tgt_session_info::tsi_env, and tgt_thread_info::tti_u.
Referenced by mdt_readpage(), and tgt_obd_idx_read().
int tgt_server_data_read (const struct lu_env * env, struct lu_target * tg)
Definition at line 547 of file tgt_lastrcvd.c.
References CDEBUG, D_INFO, dt_record_read(), LPU64, lr_server_data::lsd_last_transno, lsd_le_to_cpu(), lr_server_data::lsd_uuid, lu_target::lut_last_rcvd, lu_target::lut_lsd, lu_target::lut_obd, obd_device::obd_name, tgt_th_info(), tgt_thread_info::tti_buf, tti_buf_lsd(), tgt_thread_info::tti_lsd, and tgt_thread_info::tti_off.
Referenced by tgt_server_data_init().
int tgt_server_data_update (const struct lu_env * env, struct lu_target * tg, int sync)
Update server data in last_rcvd.
Definition at line 591 of file tgt_lastrcvd.c.
References CDEBUG, D_INFO, D_SUPER, dt_declare_record_write(), dt_trans_create(), dt_trans_start(), dt_trans_stop(), ENTRY, GOTO, LPU64, lr_server_data::lsd_last_transno, lr_server_data::lsd_uuid, lu_target::lut_bottom, lu_target::lut_last_rcvd, lu_target::lut_last_transno, lu_target::lut_lsd, lu_target::lut_obd, lu_target::lut_translock, obd_device::obd_name, RETURN, tgt_server_data_write(), tgt_th_info(), thandle::th_sync, tgt_thread_info::tti_buf, tti_buf_lsd(), tgt_thread_info::tti_off, and obd_device::u.
Referenced by ofd_parse_connect_data(), tgt_boot_epoch_update(), tgt_client_del(), tgt_client_new(), tgt_fini(), and tgt_server_data_init().
int tgt_server_data_write (const struct lu_env * env, struct lu_target * tg, struct thandle * th)
Definition at line 565 of file tgt_lastrcvd.c.
References CDEBUG, D_INFO, dt_object_locate(), dt_record_write(), ENTRY, LPU64, lsd_cpu_to_le(), lr_server_data::lsd_last_transno, lr_server_data::lsd_uuid, lu_target::lut_last_rcvd, lu_target::lut_lsd, lu_target::lut_obd, obd_device::obd_name, RETURN, tgt_th_info(), thandle::th_dev, tgt_thread_info::tti_buf, tti_buf_lsd(), tgt_thread_info::tti_lsd, and tgt_thread_info::tti_off.
Referenced by tgt_last_rcvd_update(), and tgt_server_data_update().
static struct tgt_session_info* tgt_ses_info (const struct lu_env * env) [static, read]
Definition at line 235 of file lu_target.h.
References LASSERT, lu_env::le_ses, lu_context_key_get(), and tgt_session_key.
Referenced by distribute_txn_replay_handle(), echo_client_iocontrol(), mdt_intent_policy(), ofd_preprw(), out_tx_end(), out_tx_xattr_set_exec(), out_xattr_set_add_exec(), tgt_hpreq_handler(), tgt_last_rcvd_update(), tgt_opdata_clear(), tgt_opdata_set(), tgt_request_handle(), tgt_txn_start_cb(), tgt_txn_stop_cb(), tgt_vbr_obj_set(), and update_recovery_update_ses().
static struct ptlrpc_request* tgt_ses_req (struct tgt_session_info * tsi) [static, read]
Definition at line 334 of file lu_target.h.
References req_capsule::rc_req, and tgt_session_info::tsi_pill.
Referenced by mdt_close(), mdt_handle_idmap(), mdt_init_idmap(), mdt_quota_dqacq(), mdt_reint(), mdt_sec_ctx_handle(), mdt_set_info(), mdt_statfs(), mdt_swap_layouts(), mdt_sync(), mdt_tgt_connect(), mgs_config_read(), mgs_connect(), mgs_llog_open(), mgs_target_reg(), ofd_create_hdl(), ofd_destroy_hdl(), ofd_get_info_hdl(), ofd_hp_brw(), ofd_hp_punch(), ofd_ladvise_hdl(), ofd_preprw(), ofd_prolong_one_lock(), ofd_set_info_hdl(), out_handle(), seq_handler(), tgt_brw_read(), tgt_brw_write(), tgt_connect(), tgt_convert(), tgt_disconnect(), tgt_enqueue(), tgt_io_data_unpack(), tgt_llog_close(), tgt_llog_destroy(), tgt_llog_next_block(), tgt_llog_open(), tgt_llog_prev_block(), tgt_llog_read_header(), tgt_obd_ping(), tgt_send_buffer(), tgt_sendpage(), tgt_txn_stop_cb(), tsi2mdt_info(), and tsi2ofd_info().
int tgt_sync (const struct lu_env * env, struct lu_target * tgt, struct dt_object * obj, __u64 start, __u64 end)
Definition at line 1274 of file tgt_handler.c.
References dt_object_sync(), dt_sync(), dt_version_get(), ENTRY, lu_target::lut_bottom, lu_target::lut_obd, lu_target::lut_sync_count, obd_device::obd_last_committed, and RETURN.
Referenced by ofd_sync_hdl(), and tgt_blocking_ast().
int tgt_truncate_last_rcvd (const struct lu_env * env, struct lu_target * tg, loff_t off)
Definition at line 637 of file tgt_lastrcvd.c.
References cleanup(), dt_attr_set(), dt_declare_attr_set(), dt_declare_punch(), dt_punch(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), ENTRY, GOTO, LA_SIZE, lu_attr::la_size, lu_attr::la_valid, lu_target::lut_bottom, lu_target::lut_last_rcvd, OBD_OBJECT_EOF, and RETURN.
Referenced by tgt_server_data_init().
int tgt_validate_obdo (struct tgt_session_info * tsi, struct obdo * oa)
Validate oa from client.
If the request comes from 2.0 clients, currently only RSVD seq and IDIF req are valid. a. objects in Single MDT FS seq = FID_SEQ_OST_MDT0, oi_id != 0 b. Echo objects(seq = 2), old echo client still use oi_id/oi_seq to pack ost_id. Because non-zero oi_seq will make it diffcult to tell whether this is oi_fid or real ostid. So it will check OBD_CONNECT_FID, then convert the ostid to FID for old client. c. Old FID-disable osc will send IDIF. d. new FID-enable osc/osp will send normal FID.
And also oi_id/f_oid should always start from 1. oi_id/f_oid = 0 will be used for LAST_ID file, and only being accessed inside OST now.
Definition at line 134 of file tgt_handler.c.
References CERROR, DOSTID, ENTRY, exp_connect_flags(), lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, FID_SEQ_ECHO, fid_seq_is_echo(), fid_seq_is_idif(), fid_seq_is_mdt0(), fid_seq_is_norm(), GOTO, lr_server_data::lsd_osd_index, lu_target::lut_lsd, obdo::o_oi, obdo::o_valid, OBD_CONNECT_FID, obd_export_nid2str(), OBD_MD_FLGROUP, OBD_MD_FLID, ost_id::oi, ost_id::oi_fid, ostid_id(), ostid_seq(), ostid_set_seq_mdt0(), ostid_to_fid(), RETURN, tgt_name(), tgt_th_info(), tgt_session_info::tsi_env, tgt_session_info::tsi_exp, tgt_session_info::tsi_tgt, tgt_thread_info::tti_fid1, and unlikely.
Referenced by ofd_get_info_hdl(), and tgt_ost_body_unpack().
static void tgt_vbr_obj_set (const struct lu_env * env, struct dt_object * obj) [inline, static]
Definition at line 245 of file lu_target.h.
References lu_env::le_ses, tgt_ses_info(), and tgt_session_info::tsi_vbr_obj.
Referenced by mdt_attr_set(), mdt_md_create(), mdt_reint_link(), mdt_reint_open(), mdt_reint_rename_internal(), mdt_reint_setxattr(), and ofd_trans_start().
Variable Documentation
struct tgt_handler fld_handlers[]
Definition at line 504 of file fld_handler.c.
struct tgt_handler seq_handlers[]
Definition at line 434 of file fid_handler.c.
struct tgt_handler tgt_dlm_handlers[]
Definition at line 1444 of file tgt_handler.c.
struct tgt_handler tgt_lfsck_handlers[]
Definition at line 1623 of file tgt_handler.c.
struct tgt_handler tgt_llog_handlers[]
Definition at line 1528 of file tgt_handler.c.
struct tgt_handler tgt_obd_handlers[]
Definition at line 1267 of file tgt_handler.c.
struct tgt_handler tgt_out_handlers[]
Definition at line 1166 of file out_handler.c.
struct tgt_handler tgt_sec_ctx_handlers[]
Definition at line 1547 of file tgt_handler.c.
struct lu_context_key tgt_session_key
Definition at line 375 of file tgt_main.c.
Referenced by ofd_punch_hpreq_check(), ofd_punch_hpreq_lock_match(), ofd_rw_hpreq_check(), and tgt_ses_info().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.