Lustre: lustre/obdclass/lu_object.c File Reference
lustre/obdclass/lu_object.c File Reference
#include <libcfs/libcfs.h>
#include <linux/module.h>
#include <libcfs/libcfs_hash.h>
#include <obd_class.h>
#include <obd_support.h>
#include <lustre_disk.h>
#include <lustre_fid.h>
#include <lu_object.h>
#include <lu_ref.h>
#include <libcfs/list.h>
Data Structures
struct lu_cdebug_data
struct lu_site_print_arg
struct lu_site_stats
Defines
#define DEBUG_SUBSYSTEM S_CLASS
#define LU_CACHE_NR_MAX_ADJUST 128
#define LU_CACHE_NR_UNLIMITED -1
#define LU_CACHE_NR_DEFAULT LU_CACHE_NR_UNLIMITED
#define LU_CACHE_NR_LDISKFS_LIMIT LU_CACHE_NR_UNLIMITED
#define LU_CACHE_NR_ZFS_LIMIT 10240
This is set to roughly (20 * OSS_NTHRS_MAX) to prevent thrashing.
#define LU_SITE_BITS_MIN 12
#define LU_SITE_BITS_MAX 24
#define LU_SITE_BITS_MAX_CL 19
#define LU_SITE_BKT_BITS 8
total 256 buckets, we don't want too many buckets because:
consume too much memory
avoid unbalanced LRU list
Typedefs
typedef struct lu_site_stats lu_site_stats_t
Enumerations
enum { LU_CACHE_PERCENT_MAX = 50, LU_CACHE_PERCENT_DEFAULT = 20 }
enum { LU_CDEBUG_LINE = 512 }
enum { LU_CONTEXT_KEY_NR = 40 }
Functions
module_param (lu_cache_percent, int, 0644)
MODULE_PARM_DESC (lu_cache_percent,"Percentage of memory to be used as lu_object cache")
module_param (lu_cache_nr, long, 0644)
MODULE_PARM_DESC (lu_cache_nr,"Maximum number of objects in lu_object cache")
static void lu_object_free (const struct lu_env *env, struct lu_object *o)
Free an object.
static __u32 ls_stats_read (struct lprocfs_stats *stats, int idx)
void lu_object_put (const struct lu_env *env, struct lu_object *o)
Decrease reference counter on object.
void lu_object_put_nocache (const struct lu_env *env, struct lu_object *o)
Put object and don't keep in cache.
void lu_object_unhash (const struct lu_env *env, struct lu_object *o)
Kill the object and take it out of LRU cache.
static struct lu_object * lu_object_alloc (const struct lu_env *env, struct lu_device *dev, const struct lu_fid *f, const struct lu_object_conf *conf)
Allocate new object.
int lu_site_purge (const struct lu_env *env, struct lu_site *s, int nr)
Free nr objects from the cold end of the site LRU list.
LU_KEY_INIT_FINI (lu_global, struct lu_cdebug_data)
int lu_cdebug_printer (const struct lu_env *env, void *cookie, const char *format,...)
Printer function emitting messages through libcfs_debug_msg().
void lu_object_header_print (const struct lu_env *env, void *cookie, lu_printer_t printer, const struct lu_object_header *hdr)
Print object header.
void lu_object_print (const struct lu_env *env, void *cookie, lu_printer_t printer, const struct lu_object *o)
Print human readable representation of the o to the printer.
int lu_object_invariant (const struct lu_object *o)
Check object consistency.
static struct lu_object * htable_lookup (struct lu_site *s, struct cfs_hash_bd *bd, const struct lu_fid *f, wait_queue_t *waiter, __u64 *version)
struct lu_object * lu_object_find (const struct lu_env *env, struct lu_device *dev, const struct lu_fid *f, const struct lu_object_conf *conf)
Search cache for an object with the fid f.
static void lu_object_limit (const struct lu_env *env, struct lu_device *dev)
static struct lu_object * lu_object_new (const struct lu_env *env, struct lu_device *dev, const struct lu_fid *f, const struct lu_object_conf *conf)
static struct lu_object * lu_object_find_try (const struct lu_env *env, struct lu_device *dev, const struct lu_fid *f, const struct lu_object_conf *conf, wait_queue_t *waiter)
Core logic of lu_object_find*() functions.
struct lu_object * lu_object_find_at (const struct lu_env *env, struct lu_device *dev, const struct lu_fid *f, const struct lu_object_conf *conf)
Much like lu_object_find(), but top level device of object is specifically dev rather than top level device of the site.
struct lu_object * lu_object_find_slice (const struct lu_env *env, struct lu_device *dev, const struct lu_fid *f, const struct lu_object_conf *conf)
Find object with given fid, and return its slice belonging to given device.
int lu_device_type_init (struct lu_device_type *ldt)
Helpers to initialize and finalize device types.
void lu_device_type_fini (struct lu_device_type *ldt)
static DEFINE_MUTEX (lu_sites_guard)
static int lu_site_obj_print (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode, void *data)
void lu_site_print (const struct lu_env *env, struct lu_site *s, void *cookie, lu_printer_t printer)
Print all objects in s.
static unsigned long lu_htable_order (struct lu_device *top)
Return desired hash table order.
static unsigned lu_obj_hop_hash (struct cfs_hash *hs, const void *key, unsigned mask)
static void * lu_obj_hop_object (struct hlist_node *hnode)
static void * lu_obj_hop_key (struct hlist_node *hnode)
static int lu_obj_hop_keycmp (const void *key, struct hlist_node *hnode)
static void lu_obj_hop_get (struct cfs_hash *hs, struct hlist_node *hnode)
static void lu_obj_hop_put_locked (struct cfs_hash *hs, struct hlist_node *hnode)
void lu_dev_add_linkage (struct lu_site *s, struct lu_device *d)
void lu_dev_del_linkage (struct lu_site *s, struct lu_device *d)
int lu_site_init (struct lu_site *s, struct lu_device *top)
Initialize site s, with d as the top level device.
void lu_site_fini (struct lu_site *s)
Finalize s and release its resources.
int lu_site_init_finish (struct lu_site *s)
Called when initialization of stack for this site is completed.
void lu_device_get (struct lu_device *d)
Acquire additional reference on device d.
void lu_device_put (struct lu_device *d)
Release reference on device d.
int lu_device_init (struct lu_device *d, struct lu_device_type *t)
Initialize device d of type t.
void lu_device_fini (struct lu_device *d)
Finalize device d.
int lu_object_init (struct lu_object *o, struct lu_object_header *h, struct lu_device *d)
Initialize object o that is part of compound object h and was created by device d.
void lu_object_fini (struct lu_object *o)
Finalize object and release its resources.
void lu_object_add_top (struct lu_object_header *h, struct lu_object *o)
Add object o as first layer of compound object h.
void lu_object_add (struct lu_object *before, struct lu_object *o)
Add object o as a layer of compound object, going after before.
int lu_object_header_init (struct lu_object_header *h)
Initialize compound object.
void lu_object_header_fini (struct lu_object_header *h)
Finalize compound object.
struct lu_object * lu_object_locate (struct lu_object_header *h, const struct lu_device_type *dtype)
Given a compound object, find its slice, corresponding to the device type dtype.
void lu_stack_fini (const struct lu_env *env, struct lu_device *top)
Finalize and free devices in the device stack.
DEFINE_RWLOCK (lu_keys_guard)
int lu_context_key_register (struct lu_context_key *key)
Register new key.
static void key_fini (struct lu_context *ctx, int index)
void lu_context_key_degister (struct lu_context_key *key)
Deregister key.
int lu_context_key_register_many (struct lu_context_key *k,...)
Register a number of keys.
void lu_context_key_degister_many (struct lu_context_key *k,...)
De-register a number of keys.
void lu_context_key_revive_many (struct lu_context_key *k,...)
Revive a number of keys.
void lu_context_key_quiesce_many (struct lu_context_key *k,...)
Quiescent a number of keys.
void * lu_context_key_get (const struct lu_context *ctx, const struct lu_context_key *key)
Return value associated with key key in context ctx.
void lu_context_key_quiesce (struct lu_context_key *key)
Destroy key in all remembered contexts.
void lu_context_key_revive (struct lu_context_key *key)
static void keys_fini (struct lu_context *ctx)
static int keys_fill (struct lu_context *ctx)
static int keys_init (struct lu_context *ctx)
int lu_context_init (struct lu_context *ctx, __u32 tags)
Initialize context data-structure.
void lu_context_fini (struct lu_context *ctx)
Finalize context data-structure.
void lu_context_enter (struct lu_context *ctx)
Called before entering context.
void lu_context_exit (struct lu_context *ctx)
Called after exiting from ctx.
int lu_context_refill (struct lu_context *ctx)
Allocate for context all missing keys that were registered after context creation.
void lu_context_tags_update (__u32 tags)
void lu_context_tags_clear (__u32 tags)
void lu_session_tags_update (__u32 tags)
void lu_session_tags_clear (__u32 tags)
int lu_env_init (struct lu_env *env, __u32 tags)
void lu_env_fini (struct lu_env *env)
int lu_env_refill (struct lu_env *env)
int lu_env_refill_by_tags (struct lu_env *env, __u32 ctags, __u32 stags)
Currently, this API will only be used by echo client.
static void lu_site_stats_get (struct cfs_hash *hs, lu_site_stats_t *stats, int populated)
static unsigned long lu_cache_shrink_count (struct shrinker *sk, struct shrink_control *sc)
static unsigned long lu_cache_shrink_scan (struct shrinker *sk, struct shrink_control *sc)
static int lu_cache_shrink (SHRINKER_ARGS(sc, nr_to_scan, gfp_mask))
int lu_printk_printer (const struct lu_env *env, void *unused, const char *format,...)
Debugging printer function using printk().
int lu_debugging_setup (void)
void lu_context_keys_dump (void)
int lu_global_init (void)
Initialization of global lu_* data.
void lu_global_fini (void)
Dual to lu_global_init().
int lu_site_stats_seq_print (const struct lu_site *s, struct seq_file *m)
Output site statistical counters into a buffer.
int lu_kmem_init (struct lu_kmem_descr *caches)
Helper function to initialize a number of kmem slab caches at once.
void lu_kmem_fini (struct lu_kmem_descr *caches)
Helper function to finalize a number of kmem slab cached at once.
void lu_object_assign_fid (const struct lu_env *env, struct lu_object *o, const struct lu_fid *fid)
Temporary solution to be able to assign fid in ->do_create() till we have fully-functional OST fids.
struct lu_object * lu_object_anon (const struct lu_env *env, struct lu_device *dev, const struct lu_object_conf *conf)
allocates object with 0 (non-assiged) fid XXX: temporary solution to be able to assign fid in ->do_create() till we have fully-functional OST fids
void lu_buf_free (struct lu_buf *buf)
void lu_buf_alloc (struct lu_buf *buf, size_t size)
void lu_buf_realloc (struct lu_buf *buf, size_t size)
struct lu_buf * lu_buf_check_and_alloc (struct lu_buf *buf, size_t len)
int lu_buf_check_and_grow (struct lu_buf *buf, size_t len)
Increase the size of the buf.
Variables
static unsigned int lu_cache_percent = LU_CACHE_PERCENT_DEFAULT
static long lu_cache_nr = LU_CACHE_NR_DEFAULT
static struct lu_context_key lu_global_key
Key, holding temporary buffer.
static struct list_head lu_device_types
Global list of all device types.
static struct list_head lu_sites
Global list of all sites on this node.
static struct lu_env lu_shrink_env
Global environment used by site shrinker.
static struct cfs_hash_ops lu_site_hash_ops
static struct lu_context_key * lu_keys [LU_CONTEXT_KEY_NR] = { NULL, }
static atomic_t lu_key_initing_cnt = ATOMIC_INIT(0)
static unsigned key_set_version = 0
Global counter incremented whenever key is registered, unregistered, revived or quiesced.
static struct list_head lu_context_remembered
List of remembered contexts.
__u32 lu_context_tags_default = 0
lu_ctx_tags/lu_ses_tags will be updated if there are new types of obd being added.
__u32 lu_session_tags_default = 0
static struct shrinker * lu_site_shrinker
static struct lu_env lu_debugging_env
Environment to be used in debugger, contains all tags.
struct lu_buf LU_BUF_NULL
null buffer
Define Documentation
#define DEBUG_SUBSYSTEM S_CLASS
Definition at line 45 of file lu_object.c.
#define LU_CACHE_NR_DEFAULT LU_CACHE_NR_UNLIMITED
Definition at line 65 of file lu_object.c.
#define LU_CACHE_NR_LDISKFS_LIMIT LU_CACHE_NR_UNLIMITED
Definition at line 66 of file lu_object.c.
#define LU_CACHE_NR_MAX_ADJUST 128
Definition at line 63 of file lu_object.c.
Referenced by lu_object_limit().
#define LU_CACHE_NR_UNLIMITED -1
Definition at line 64 of file lu_object.c.
Referenced by lu_object_limit().
#define LU_CACHE_NR_ZFS_LIMIT 10240
This is set to roughly (20 * OSS_NTHRS_MAX) to prevent thrashing.
Definition at line 68 of file lu_object.c.
Referenced by lu_htable_order().
#define LU_SITE_BITS_MAX 24
Definition at line 71 of file lu_object.c.
Referenced by lu_htable_order().
#define LU_SITE_BITS_MAX_CL 19
Definition at line 72 of file lu_object.c.
Referenced by lu_htable_order().
#define LU_SITE_BITS_MIN 12
Definition at line 70 of file lu_object.c.
Referenced by lu_htable_order(), and lu_site_init().
#define LU_SITE_BKT_BITS 8
total 256 buckets, we don't want too many buckets because:
consume too much memory
avoid unbalanced LRU list
Definition at line 78 of file lu_object.c.
Referenced by lu_site_init().
Typedef Documentation
typedef struct lu_site_stats lu_site_stats_t
Enumeration Type Documentation
anonymous enum
Enumerator:
LU_CACHE_PERCENT_MAX
LU_CACHE_PERCENT_DEFAULT
Definition at line 58 of file lu_object.c.
anonymous enum
Enumerator:
LU_CDEBUG_LINE
Maximal line size.
XXX overflow is not handled correctly.
Definition at line 458 of file lu_object.c.
anonymous enum
Enumerator:
LU_CONTEXT_KEY_NR
Maximal number of tld slots.
Definition at line 1378 of file lu_object.c.
Function Documentation
static DEFINE_MUTEX (lu_sites_guard) [static]
DEFINE_RWLOCK (lu_keys_guard)
static struct lu_object* htable_lookup (struct lu_site * s, struct cfs_hash_bd * bd, const struct lu_fid * f, wait_queue_t * waiter, __u64 * version) [static, read]
Definition at line 586 of file lu_object.c.
References __u64, cfs_hash_bd_extra_get(), cfs_hash_bd_peek_locked(), cfs_hash_bd_version_get(), cfs_hash_get(), likely, list_del_init(), list_empty(), lu_object_header::loh_lru, lprocfs_counter_decr(), lprocfs_counter_incr(), lu_site::ls_obj_hash, lu_site::ls_stats, lu_site_bkt_data::lsb_lru_len, lu_site_bkt_data::lsb_marche_funebre, lu_object_is_dying(), lu_object_top(), LU_SS_CACHE_DEATH_RACE, LU_SS_CACHE_HIT, LU_SS_CACHE_MISS, and LU_SS_LRU_LEN.
Referenced by lu_object_assign_fid(), and lu_object_find_try().
static void key_fini (struct lu_context * ctx, int index) [static]
Definition at line 1429 of file lu_object.c.
References LASSERT, lu_context::lc_tags, lu_context::lc_value, lu_context_key::lct_fini, LCT_NOREF, lu_context_key::lct_owner, lu_context_key::lct_reference, lu_context_key::lct_used, LINVRNT, and lu_ref_del().
Referenced by keys_fini(), lu_context_key_degister(), and lu_context_key_quiesce().
static int keys_fill (struct lu_context * ctx) [static]
Definition at line 1653 of file lu_object.c.
References ARRAY_SIZE, LASSERT, lu_context::lc_tags, lu_context::lc_value, lu_context::lc_version, lu_context_key::lct_exit, LCT_HAS_EXIT, lu_context_key::lct_index, lu_context_key::lct_init, LCT_NOREF, lu_context_key::lct_owner, LCT_QUIESCENT, lu_context_key::lct_reference, lu_context_key::lct_tags, lu_context_key::lct_used, LINVRNT, lu_ref_add_atomic(), and unlikely.
Referenced by keys_init(), and lu_context_refill().
static void keys_fini (struct lu_context * ctx) [static]
Definition at line 1639 of file lu_object.c.
References ARRAY_SIZE, key_fini(), lu_context::lc_value, and OBD_FREE.
Referenced by lu_context_fini().
static int keys_init (struct lu_context * ctx) [static]
Definition at line 1717 of file lu_object.c.
References ARRAY_SIZE, keys_fill(), lu_context::lc_value, likely, and OBD_ALLOC.
Referenced by lu_context_init().
static __u32 ls_stats_read (struct lprocfs_stats * stats, int idx) [static]
Definition at line 2201 of file lu_object.c.
References lprocfs_counter::lc_count, lprocfs_stats_collect(), and LU_SS_LRU_LEN.
Referenced by lu_cache_shrink_count(), and lu_site_stats_seq_print().
static int lu_cache_shrink (SHRINKER_ARGS(sc, nr_to_scan, gfp_mask)) [static]
Definition at line 2059 of file lu_object.c.
References CDEBUG, D_INODE, shrink_control::gfp_mask, lu_cache_shrink_count(), lu_cache_shrink_scan(), shrink_control::nr_to_scan, and shrink_param.
Referenced by lu_global_init().
static unsigned long lu_cache_shrink_count (struct shrinker * sk, struct shrink_control * sc) [static]
Definition at line 1980 of file lu_object.c.
References CDEBUG, D_INODE, shrink_control::gfp_mask, list_for_each_entry_safe, lu_site::ls_linkage, lu_site::ls_stats, ls_stats_read(), lu_sites, and LU_SS_LRU_LEN.
Referenced by lu_cache_shrink(), and lu_global_init().
static unsigned long lu_cache_shrink_scan (struct shrinker * sk, struct shrink_control * sc) [static]
Definition at line 2003 of file lu_object.c.
References shrink_control::gfp_mask, list_for_each_entry_safe, LIST_HEAD(), list_move_tail(), list_splice(), lu_site::ls_linkage, lu_shrink_env, lu_site_purge(), lu_sites, shrink_control::nr_to_scan, list_head::prev, and SHRINK_STOP.
Referenced by lu_cache_shrink(), and lu_global_init().
void lu_context_keys_dump (void)
Definition at line 2111 of file lu_object.c.
References ARRAY_SIZE, CERROR, lu_context_key::lct_exit, lu_context_key::lct_fini, lu_context_key::lct_index, lu_context_key::lct_init, lu_context_key::lct_owner, lu_context_key::lct_reference, lu_context_key::lct_tags, lu_context_key::lct_used, and lu_ref_print().
int lu_debugging_setup (void)
Definition at line 2106 of file lu_object.c.
References lu_debugging_env, and lu_env_init().
static unsigned long lu_htable_order (struct lu_device * top) [static]
Return desired hash table order.
Definition at line 921 of file lu_object.c.
References CWARN, lu_device::ld_type, lu_device_type::ldt_name, lu_cache_nr, LU_CACHE_NR_ZFS_LIMIT, lu_cache_percent, LU_CACHE_PERCENT_DEFAULT, LU_CACHE_PERCENT_MAX, LU_SITE_BITS_MAX, LU_SITE_BITS_MAX_CL, LU_SITE_BITS_MIN, LUSTRE_OSD_ZFS_NAME, and LUSTRE_VVP_NAME.
Referenced by lu_site_init().
LU_KEY_INIT_FINI (lu_global , struct lu_cdebug_data)
static void lu_obj_hop_get (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 1016 of file lu_object.c.
References hlist_entry, lu_object_header::loh_hash, and lu_object_header::loh_ref.
static unsigned lu_obj_hop_hash (struct cfs_hash * hs, const void * key, unsigned mask) [static]
Definition at line 976 of file lu_object.c.
References CFS_HASH_NBKT, fid_flatten32(), fid_oid(), and cfs_hash::hs_bkt_bits.
static void* lu_obj_hop_key (struct hlist_node * hnode) [static]
Definition at line 1000 of file lu_object.c.
References hlist_entry, lu_object_header::loh_fid, and lu_object_header::loh_hash.
static int lu_obj_hop_keycmp (const void * key, struct hlist_node * hnode) [static]
Definition at line 1008 of file lu_object.c.
References hlist_entry, lu_object_header::loh_fid, lu_object_header::loh_hash, and lu_fid_eq().
static void* lu_obj_hop_object (struct hlist_node * hnode) [static]
Definition at line 995 of file lu_object.c.
References hlist_entry.
static void lu_obj_hop_put_locked (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 1024 of file lu_object.c.
References LBUG.
static struct lu_object* lu_object_alloc (const struct lu_env * env, struct lu_device * dev, const struct lu_fid * f, const struct lu_object_conf * conf) [static, read]
Allocate new object.
This follows object creation protocol, described in the comment within struct lu_device_operations definition.
Definition at line 236 of file lu_object.c.
References ENTRY, lu_device::ld_ops, lu_device::ld_site, lu_device_operations::ldo_object_alloc, list_for_each_entry, list_for_each_entry_reverse, lu_object::lo_header, lu_object::lo_ops, lu_object_header::loh_fid, lu_object_header::loh_layers, lu_object_operations::loo_object_init, lu_object_operations::loo_object_start, lprocfs_counter_incr(), lu_site::ls_stats, lu_object_free(), LU_SS_CREATED, list_head::next, and RETURN.
Referenced by lu_object_anon(), lu_object_find_try(), and lu_object_new().
static struct lu_object* lu_object_find_try (const struct lu_env * env, struct lu_device * dev, const struct lu_fid * f, const struct lu_object_conf * conf, wait_queue_t * waiter) [static, read]
Core logic of lu_object_find*() functions.
Definition at line 701 of file lu_object.c.
References __u64, cfs_hash_bd_add_locked(), cfs_hash_bd_get_and_lock(), cfs_hash_bd_lock(), cfs_hash_bd_unlock(), htable_lookup(), LASSERT, lu_device::ld_site, likely, lu_object::lo_header, LOC_F_NEW, lu_object_conf::loc_flags, lu_object_header::loh_hash, lprocfs_counter_incr(), lu_site::ls_obj_hash, lu_site::ls_stats, lu_fid_eq(), lu_object_alloc(), lu_object_fid(), lu_object_free(), lu_object_limit(), lu_object_new(), LU_SS_CACHE_RACE, unlikely, and version.
Referenced by lu_object_find_at().
static void lu_object_free (const struct lu_env * env, struct lu_object * o) [static]
Free an object.
Definition at line 306 of file lu_object.c.
References INIT_LIST_HEAD, LASSERT, lu_device::ld_site, list_del_init(), list_empty(), list_for_each_entry_reverse, list_splice_init(), lu_object::lo_dev, lu_object::lo_header, lu_object::lo_linkage, lu_object::lo_ops, lu_object_header::loh_fid, lu_object_header::loh_layers, lu_object_operations::loo_object_delete, lu_object_operations::loo_object_free, lu_site_bkt_data::lsb_marche_funebre, lu_site_bkt_from_fid(), and list_head::prev.
Referenced by lu_object_alloc(), lu_object_find_try(), lu_object_put(), and lu_site_purge().
static void lu_object_limit (const struct lu_env * env, struct lu_device * dev) [static]
Definition at line 658 of file lu_object.c.
References __u64, cfs_hash_size_get(), lu_device::ld_site, lu_site::ls_obj_hash, lu_cache_nr, LU_CACHE_NR_MAX_ADJUST, LU_CACHE_NR_UNLIMITED, lu_site_purge(), MIN, and size.
Referenced by lu_object_find_try(), and lu_object_new().
static struct lu_object* lu_object_new (const struct lu_env * env, struct lu_device * dev, const struct lu_fid * f, const struct lu_object_conf * conf) [static, read]
Definition at line 675 of file lu_object.c.
References cfs_hash_bd_add_locked(), cfs_hash_bd_get_and_lock(), cfs_hash_bd_unlock(), lu_device::ld_site, lu_site::ls_obj_hash, lu_object_alloc(), lu_object_limit(), and unlikely.
Referenced by lu_object_find_try().
int lu_printk_printer (const struct lu_env * env, void * unused, const char * format, ...)
Debugging printer function using printk().
Definition at line 2095 of file lu_object.c.
static int lu_site_obj_print (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode, void * data) [static]
Definition at line 882 of file lu_object.c.
References hlist_entry, list_empty(), lu_object_header::loh_hash, lu_object_header::loh_layers, lu_site_print_arg::lsp_cookie, lu_site_print_arg::lsp_env, lu_site_print_arg::lsp_printer, lu_object_header_print(), lu_object_print(), and lu_object_top().
Referenced by lu_site_print().
static void lu_site_stats_get (struct cfs_hash * hs, lu_site_stats_t * stats, int populated) [static]
Definition at line 1937 of file lu_object.c.
References cfs_hash_bd_count_get(), cfs_hash_bd_depmax_get(), cfs_hash_bd_extra_get(), cfs_hash_bd_for_each_hlist, cfs_hash_bd_lock(), cfs_hash_bd_unlock(), cfs_hash_for_each_bucket, hlist_empty(), lu_site_bkt_data::lsb_lru_len, lu_site_stats::lss_busy, lu_site_stats::lss_max_search, lu_site_stats::lss_populated, lu_site_stats::lss_total, and max.
Referenced by lu_site_stats_seq_print().
module_param (lu_cache_nr , long , 0644)
module_param (lu_cache_percent , int , 0644)
MODULE_PARM_DESC (lu_cache_nr , "Maximum number of objects in lu_object cache")
MODULE_PARM_DESC (lu_cache_percent , "Percentage of memory to be used as lu_object cache")
Variable Documentation
unsigned key_set_version = 0 [static]
Global counter incremented whenever key is registered, unregistered, revived or quiesced.
This is used to void unnecessary calls to lu_context_refill(). No locking is provided, as initialization and shutdown are supposed to be externally serialized.
Definition at line 1396 of file lu_object.c.
long lu_cache_nr = LU_CACHE_NR_DEFAULT [static]
Definition at line 85 of file lu_object.c.
Referenced by lu_htable_order(), and lu_object_limit().
unsigned int lu_cache_percent = LU_CACHE_PERCENT_DEFAULT [static]
Definition at line 81 of file lu_object.c.
Referenced by lu_htable_order().
struct list_head lu_context_remembered [static]
List of remembered contexts.
XXX document me.
Definition at line 1587 of file lu_object.c.
Referenced by lu_context_init(), lu_context_key_quiesce(), and lu_global_init().
struct lu_env lu_debugging_env [static]
Environment to be used in debugger, contains all tags.
Definition at line 2090 of file lu_object.c.
Referenced by lu_debugging_setup().
struct list_head lu_device_types [static]
Global list of all device types.
Definition at line 833 of file lu_object.c.
Referenced by lu_device_type_init(), and lu_global_init().
struct lu_context_key lu_global_key [static]
Initial value:
 {
        .lct_tags = LCT_MD_THREAD | LCT_DT_THREAD |
                    LCT_MG_THREAD | LCT_CL_THREAD | LCT_LOCAL,
        .lct_init = lu_global_key_init,
        .lct_fini = lu_global_key_fini
}
Key, holding temporary buffer.
This key is registered very early by lu_global_init().
Definition at line 481 of file lu_object.c.
atomic_t lu_key_initing_cnt = ATOMIC_INIT(0) [static]
Definition at line 1388 of file lu_object.c.
struct lu_context_key* lu_keys[LU_CONTEXT_KEY_NR] = { NULL, } [static]
Definition at line 1385 of file lu_object.c.
struct lu_env lu_shrink_env [static]
Global environment used by site shrinker.
Definition at line 873 of file lu_object.c.
Referenced by lu_cache_shrink_scan(), lu_context_key_degister(), lu_global_fini(), lu_global_init(), and lu_site_init_finish().
struct cfs_hash_ops lu_site_hash_ops [static]
Initial value:
 {
        .hs_hash        = lu_obj_hop_hash,
        .hs_key         = lu_obj_hop_key,
        .hs_keycmp      = lu_obj_hop_keycmp,
        .hs_object      = lu_obj_hop_object,
        .hs_get         = lu_obj_hop_get,
        .hs_put_locked  = lu_obj_hop_put_locked,
}
Definition at line 1029 of file lu_object.c.
struct shrinker* lu_site_shrinker [static]
Definition at line 1928 of file lu_object.c.
struct list_head lu_sites [static]
Global list of all sites on this node.
Definition at line 867 of file lu_object.c.
Referenced by lu_cache_shrink_count(), lu_cache_shrink_scan(), lu_global_init(), and lu_site_init_finish().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.