Lustre: lustre/obdclass/lustre_peer.c File Reference
lustre/obdclass/lustre_peer.c File Reference
#include <obd.h>
#include <obd_support.h>
#include <obd_class.h>
#include <lustre_lib.h>
#include <lustre_ha.h>
#include <lustre_net.h>
#include <lprocfs_status.h>
Data Structures
struct uuid_nid_data
Defines
#define DEBUG_SUBSYSTEM S_RPC
#define NIDS_MAX 32
Functions
void class_init_uuidlist (void)
void class_exit_uuidlist (void)
int lustre_uuid_to_peer (const char *uuid, lnet_nid_t *peer_nid, int index)
int class_add_uuid (const char *uuid, __u64 nid)
int class_del_uuid (const char *uuid)
int class_check_uuid (struct obd_uuid *uuid, __u64 nid)
Variables
static struct list_head g_uuid_list
static spinlock_t g_uuid_lock
Define Documentation
#define DEBUG_SUBSYSTEM S_RPC
Definition at line 37 of file lustre_peer.c.
#define NIDS_MAX 32
Definition at line 47 of file lustre_peer.c.
Referenced by class_add_uuid().
Function Documentation
int class_add_uuid (const char * uuid, __u64 nid)
Definition at line 97 of file lustre_peer.c.
References CDEBUG, D_INFO, g_uuid_list, g_uuid_lock, LASSERT, libcfs_nid2str(), list_add(), list_for_each_entry, NIDS_MAX, OBD_ALLOC_PTR, OBD_FREE, obd_str2uuid(), obd_uuid_equals(), uuid_nid_data::un_list, uuid_nid_data::un_nid_count, uuid_nid_data::un_nids, uuid_nid_data::un_uuid, and UUID_MAX.
Referenced by class_process_config(), client_lwp_config_process(), and lustre_lwp_setup().
int class_check_uuid (struct obd_uuid * uuid, __u64 nid)
Definition at line 190 of file lustre_peer.c.
References CDEBUG, D_INFO, ENTRY, g_uuid_list, g_uuid_lock, libcfs_nid2str(), list_for_each_entry, obd_uuid2str(), obd_uuid_equals(), RETURN, uuid_nid_data::un_list, uuid_nid_data::un_nid_count, uuid_nid_data::un_nids, and uuid_nid_data::un_uuid.
Referenced by client_import_find_conn().
int class_del_uuid (const char * uuid)
Definition at line 147 of file lustre_peer.c.
References CDEBUG, D_INFO, g_uuid_list, g_uuid_lock, INIT_LIST_HEAD, libcfs_nid2str(), list_del(), list_empty(), list_entry, list_for_each_entry, list_move(), list_splice_init(), list_head::next, OBD_FREE, obd_str2uuid(), obd_uuid2str(), obd_uuid_equals(), uuid_nid_data::un_list, uuid_nid_data::un_nid_count, uuid_nid_data::un_nids, and uuid_nid_data::un_uuid.
Referenced by class_exit_uuidlist(), and class_process_config().
void class_exit_uuidlist (void)
Definition at line 66 of file lustre_peer.c.
References class_del_uuid().
Referenced by obdclass_exit().
void class_init_uuidlist (void)
Definition at line 60 of file lustre_peer.c.
References g_uuid_list, g_uuid_lock, and INIT_LIST_HEAD.
Referenced by obdclass_init().
int lustre_uuid_to_peer (const char * uuid, lnet_nid_t * peer_nid, int index)
Definition at line 72 of file lustre_peer.c.
References g_uuid_list, g_uuid_lock, list_for_each_entry, obd_str2uuid(), obd_uuid_equals(), uuid_nid_data::un_nid_count, uuid_nid_data::un_nids, and uuid_nid_data::un_uuid.
Referenced by ptlrpc_uuid_to_peer().
Variable Documentation
struct list_head g_uuid_list [static]
Definition at line 57 of file lustre_peer.c.
Referenced by class_add_uuid(), class_check_uuid(), class_del_uuid(), class_init_uuidlist(), and lustre_uuid_to_peer().
spinlock_t g_uuid_lock [static]
Definition at line 58 of file lustre_peer.c.
Referenced by class_add_uuid(), class_check_uuid(), class_del_uuid(), class_init_uuidlist(), and lustre_uuid_to_peer().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.