Lustre: lustre/include/lustre_lmv.h File Reference
lustre/include/lustre_lmv.h File Reference
#include <lustre/lustre_idl.h>
Data Structures
struct lmv_oinfo
struct lmv_stripe_md
Functions
static bool lsm_md_eq (const struct lmv_stripe_md *lsm1, const struct lmv_stripe_md *lsm2)
void lmv_free_memmd (struct lmv_stripe_md *lsm)
int lmvea_load_shards (const struct lu_env *env, struct dt_object *obj, struct lu_dirent *ent, struct lu_buf *buf, bool resize)
static void lmv1_le_to_cpu (struct lmv_mds_md_v1 *lmv_dst, const struct lmv_mds_md_v1 *lmv_src)
static void lmv_le_to_cpu (union lmv_mds_md *lmv_dst, const union lmv_mds_md *lmv_src)
static unsigned int lmv_hash_all_chars (unsigned int count, const char *name, int namelen)
static unsigned int lmv_hash_fnv1a (unsigned int count, const char *name, int namelen)
static int lmv_name_to_stripe_index (__u32 lmv_hash_type, unsigned int stripe_count, const char *name, int namelen)
static bool lmv_is_known_hash_type (__u32 type)
Function Documentation
static void lmv1_le_to_cpu (struct lmv_mds_md_v1 * lmv_dst, const struct lmv_mds_md_v1 * lmv_src) [inline, static]
Definition at line 87 of file lustre_lmv.h.
References fid_le_to_cpu(), le32_to_cpu, lmv_mds_md_v1::lmv_hash_type, lmv_mds_md_v1::lmv_layout_version, lmv_mds_md_v1::lmv_magic, lmv_mds_md_v1::lmv_master_mdt_index, lmv_mds_md_v1::lmv_stripe_count, and lmv_mds_md_v1::lmv_stripe_fids.
Referenced by lmv_le_to_cpu().
void lmv_free_memmd (struct lmv_stripe_md * lsm)
Definition at line 2972 of file lmv_obd.c.
References lmv_unpackmd().
Referenced by ll_dir_clear_lsm_md(), ll_update_lsm_md(), and lmv_free_lustre_md().
static unsigned int lmv_hash_all_chars (unsigned int count, const char * name, int namelen) [inline, static]
Definition at line 117 of file lustre_lmv.h.
Referenced by lmv_name_to_stripe_index().
static unsigned int lmv_hash_fnv1a (unsigned int count, const char * name, int namelen) [inline, static]
Definition at line 131 of file lustre_lmv.h.
References __u64, and lustre_hash_fnv_1a_64().
Referenced by lmv_name_to_stripe_index().
static bool lmv_is_known_hash_type (__u32 type) [inline, static]
Definition at line 173 of file lustre_lmv.h.
References LMV_HASH_TYPE_ALL_CHARS, LMV_HASH_TYPE_FNV_1A_64, and LMV_HASH_TYPE_MASK.
Referenced by lfsck_is_valid_slave_lmv(), lfsck_namespace_striped_dir_rescan(), lfsck_record_lmv(), lfsck_replace_lmv(), lmv_intent_lookup(), lmv_need_try_all_stripes(), and lmv_unlink().
static void lmv_le_to_cpu (union lmv_mds_md * lmv_dst, const union lmv_mds_md * lmv_src) [inline, static]
Definition at line 103 of file lustre_lmv.h.
References le32_to_cpu, lmv1_le_to_cpu(), lmv_mds_md::lmv_magic, LMV_MAGIC_V1, and lmv_mds_md::lmv_md_v1.
Referenced by mdt_reint_migrate_internal().
static int lmv_name_to_stripe_index (__u32 lmv_hash_type, unsigned int stripe_count, const char * name, int namelen) [inline, static]
Definition at line 140 of file lustre_lmv.h.
References CDEBUG, D_INFO, LASSERT, lmv_hash_all_chars(), LMV_HASH_FLAG_MIGRATION, lmv_hash_fnv1a(), LMV_HASH_TYPE_ALL_CHARS, LMV_HASH_TYPE_FNV_1A_64, and LMV_HASH_TYPE_MASK.
Referenced by lfsck_is_valid_slave_name_entry(), lfsck_namespace_check_name(), and lsm_name_to_stripe_info().
int lmvea_load_shards (const struct lu_env * env, struct dt_object * obj, struct lu_dirent * ent, struct lu_buf * buf, bool resize)
static bool lsm_md_eq (const struct lmv_stripe_md * lsm1, const struct lmv_stripe_md * lsm2) [inline, static]
Definition at line 56 of file lustre_lmv.h.
References lmv_oinfo::lmo_fid, lmv_stripe_md::lsm_md_hash_type, lmv_stripe_md::lsm_md_layout_version, lmv_stripe_md::lsm_md_magic, lmv_stripe_md::lsm_md_master_mdt_index, lmv_stripe_md::lsm_md_oinfo, lmv_stripe_md::lsm_md_pool_name, lmv_stripe_md::lsm_md_stripe_count, and lu_fid_eq().
Referenced by ll_update_lsm_md().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.