Lustre: lustre/obdclass/linux/linux-module.c File Reference
lustre/obdclass/linux/linux-module.c File Reference
#include <linux/module.h>
#include <linux/errno.h>
#include <linux/kernel.h>
#include <linux/major.h>
#include <linux/sched.h>
#include <linux/lp.h>
#include <linux/slab.h>
#include <linux/ioport.h>
#include <linux/fcntl.h>
#include <linux/delay.h>
#include <linux/skbuff.h>
#include <linux/proc_fs.h>
#include <linux/fs.h>
#include <linux/poll.h>
#include <linux/init.h>
#include <linux/list.h>
#include <linux/highmem.h>
#include <asm/io.h>
#include <asm/ioctls.h>
#include <asm/poll.h>
#include <asm/uaccess.h>
#include <linux/miscdevice.h>
#include <linux/seq_file.h>
#include <libcfs/libcfs.h>
#include <obd_support.h>
#include <obd_class.h>
#include <lnet/lnetctl.h>
#include <lprocfs_status.h>
#include <lustre_ioctl.h>
#include <lustre_ver.h>
Defines
#define DEBUG_SUBSYSTEM S_CLASS
#define lprocfs_base NULL
Functions
int obd_ioctl_getdata (char **buf, int *len, void __user *arg)
int obd_ioctl_popdata (void __user *arg, void *data, int len)
static int obd_class_open (struct inode *inode, struct file *file)
static int obd_class_release (struct inode *inode, struct file *file)
static long obd_class_ioctl (struct file *filp, unsigned int cmd, unsigned long arg)
static void * obd_device_list_seq_start (struct seq_file *p, loff_t *pos)
static void obd_device_list_seq_stop (struct seq_file *p, void *v)
static void * obd_device_list_seq_next (struct seq_file *p, void *v, loff_t *pos)
static int obd_device_list_seq_show (struct seq_file *p, void *v)
static int obd_device_list_open (struct inode *inode, struct file *file)
int class_procfs_init (void)
int class_procfs_clean (void)
Variables
int proc_version
static struct file_operations obd_psdev_fops
struct miscdevice obd_psdev
static struct seq_operations obd_device_list_sops
static struct file_operations obd_device_list_fops
Define Documentation
#define DEBUG_SUBSYSTEM S_CLASS
Definition at line 43 of file linux-module.c.
#define lprocfs_base NULL
Definition at line 364 of file linux-module.c.
Function Documentation
int class_procfs_clean (void)
Definition at line 477 of file linux-module.c.
References ENTRY, lprocfs_remove(), and RETURN.
Referenced by obdclass_exit().
int class_procfs_init (void)
Definition at line 444 of file linux-module.c.
References CERROR, ENTRY, GOTO, lprocfs_register(), lprocfs_remove(), obd_sysctl_init(), and RETURN.
Referenced by obdclass_init().
static long obd_class_ioctl (struct file * filp, unsigned int cmd, unsigned long arg) [static]
Definition at line 181 of file linux-module.c.
References CFS_CAP_SYS_ADMIN, cfs_capable(), class_handle_ioctl(), ENTRY, OBD_IOC_PING_TARGET, and RETURN.
static int obd_class_open (struct inode * inode, struct file * file) [static]
Definition at line 163 of file linux-module.c.
References ENTRY, and RETURN.
static int obd_class_release (struct inode * inode, struct file * file) [static]
Definition at line 172 of file linux-module.c.
References ENTRY, and RETURN.
static int obd_device_list_open (struct inode * inode, struct file * file) [static]
Definition at line 423 of file linux-module.c.
static void* obd_device_list_seq_next (struct seq_file * p, void * v, loff_t * pos) [static]
Definition at line 379 of file linux-module.c.
References class_devno_max().
static int obd_device_list_seq_show (struct seq_file * p, void * v) [static]
Definition at line 388 of file linux-module.c.
References class_num2obd(), LASSERT, obd_device::obd_attached, OBD_DEVICE_MAGIC, obd_device::obd_inactive, obd_device::obd_magic, obd_device::obd_name, obd_device::obd_refcount, obd_device::obd_set_up, obd_device::obd_stopping, obd_device::obd_type, obd_device::obd_uuid, status, obd_type::typ_name, and obd_uuid::uuid.
static void* obd_device_list_seq_start (struct seq_file * p, loff_t * pos) [static]
Definition at line 367 of file linux-module.c.
References class_devno_max().
static void obd_device_list_seq_stop (struct seq_file * p, void * v) [static]
Definition at line 375 of file linux-module.c.
int obd_ioctl_getdata (char ** buf, int * len, void __user * arg)
Definition at line 80 of file linux-module.c.
References CERROR, cfs_size_round(), ENTRY, obd_ioctl_data::ioc_bulk, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf2, obd_ioctl_data::ioc_inlbuf3, obd_ioctl_data::ioc_inlbuf4, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, obd_ioctl_data::ioc_inllen3, obd_ioctl_data::ioc_inllen4, obd_ioctl_hdr::ioc_len, obd_ioctl_hdr::ioc_version, OBD_ALLOC_LARGE, OBD_FREE_LARGE, obd_ioctl_is_invalid(), OBD_IOCTL_VERSION, OBD_MAX_IOCTL_BUFFER, and RETURN.
Referenced by class_handle_ioctl(), ll_dir_ioctl(), ll_obd_statfs(), and lov_iocontrol().
int obd_ioctl_popdata (void __user * arg, void * data, int len)
Definition at line 153 of file linux-module.c.
References ENTRY, and RETURN.
Referenced by class_handle_ioctl().
Variable Documentation
struct file_operations obd_device_list_fops [static]
Initial value:
 {
        .owner   = THIS_MODULE,
        .open    = obd_device_list_open,
        .read    = seq_read,
        .llseek  = seq_lseek,
        .release = seq_release,
}
Definition at line 436 of file linux-module.c.
struct seq_operations obd_device_list_sops [static]
Initial value:
 {
        .start = obd_device_list_seq_start,
        .stop = obd_device_list_seq_stop,
        .next = obd_device_list_seq_next,
        .show = obd_device_list_seq_show,
}
Definition at line 416 of file linux-module.c.
struct miscdevice obd_psdev
Initial value:
 {
        .minor = OBD_DEV_MINOR,
        .name  = OBD_DEV_NAME,
        .fops  = &obd_psdev_fops,
}
Definition at line 207 of file linux-module.c.
Referenced by obdclass_exit(), and obdclass_init().
struct file_operations obd_psdev_fops [static]
Initial value:
 {
        .owner          = THIS_MODULE,
        .unlocked_ioctl = obd_class_ioctl,
        .open           = obd_class_open,
        .release        = obd_class_release,
}
Definition at line 199 of file linux-module.c.
int proc_version
Definition at line 77 of file linux-module.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.