Lustre: lustre/include/lustre_patchless_compat.h File Reference
lustre/include/lustre_patchless_compat.h File Reference
#include <linux/fs.h>
#include <linux/mm.h>
#include <linux/list.h>
#include <linux/hash.h>
Defines
#define ll_d_count(d) ((d)->d_count)
#define ATTR_FROM_OPEN 0
#define ATTR_RAW 0
#define ATTR_CTIME_SET (1 << 28)
Functions
static void ll_remove_from_page_cache (struct page *page)
static void ll_delete_from_page_cache (struct page *page)
static void ll_cancel_dirty_page (struct address_space *mapping, struct page *page)
static void truncate_complete_page (struct address_space *mapping, struct page *page)
Define Documentation
#define ATTR_CTIME_SET (1 << 28)
Definition at line 135 of file lustre_patchless_compat.h.
Referenced by attr_pack(), ll_file_futimes_3(), ll_prepare_close(), ll_setattr_raw(), and osc_io_setattr_start().
#define ATTR_FROM_OPEN 0
Definition at line 122 of file lustre_patchless_compat.h.
Referenced by attr_pack().
#define ATTR_RAW 0
Definition at line 127 of file lustre_patchless_compat.h.
#define ll_d_count (d) ((d)->d_count)
Definition at line 115 of file lustre_patchless_compat.h.
Referenced by d_lustre_invalidate(), ll_d_init(), ll_dcompare(), ll_ddelete(), ll_splice_alias(), lustre_dump_dentry(), and push_ctxt().
Function Documentation
static void ll_cancel_dirty_page (struct address_space * mapping, struct page * page) [inline, static]
Definition at line 78 of file lustre_patchless_compat.h.
Referenced by truncate_complete_page().
static void ll_delete_from_page_cache (struct page * page) [inline, static]
Definition at line 68 of file lustre_patchless_compat.h.
References ll_remove_from_page_cache().
Referenced by truncate_complete_page().
static void ll_remove_from_page_cache (struct page * page) [inline, static]
Definition at line 50 of file lustre_patchless_compat.h.
References mapping.
Referenced by ll_delete_from_page_cache().
static void truncate_complete_page (struct address_space * mapping, struct page * page) [inline, static]
Definition at line 91 of file lustre_patchless_compat.h.
References ll_cancel_dirty_page(), and ll_delete_from_page_cache().
Referenced by ll_invalidate_page(), ll_release_page(), and mdc_release_page().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.