Lustre: lustre/include/lustre_param.h File Reference
lustre/include/lustre_param.h File Reference
#include <libcfs/libcfs.h>
#include <lnet/types.h>
Data Structures
struct cfg_interop_param
Defines
#define PARAM_TIMEOUT "timeout="
#define PARAM_LDLM_TIMEOUT "ldlm_timeout="
#define PARAM_AT_MIN "at_min="
#define PARAM_AT_MAX "at_max="
#define PARAM_AT_EXTRA "at_extra="
#define PARAM_AT_EARLY_MARGIN "at_early_margin="
#define PARAM_AT_HISTORY "at_history="
#define PARAM_JOBID_VAR "jobid_var="
#define PARAM_MGSNODE "mgsnode="
#define PARAM_FAILNODE "failover.node="
#define PARAM_FAILMODE "failover.mode="
#define PARAM_ACTIVE "active="
#define PARAM_NETWORK "network="
#define PARAM_ID_UPCALL "identity_upcall="
#define PARAM_OST "ost."
#define PARAM_OSD "osd."
#define PARAM_OSC "osc."
#define PARAM_MDT "mdt."
#define PARAM_HSM "mdt.hsm."
#define PARAM_MDD "mdd."
#define PARAM_MDC "mdc."
#define PARAM_LLITE "llite."
#define PARAM_LOV "lov."
#define PARAM_LOD "lod."
#define PARAM_OSP "osp."
#define PARAM_SYS "sys."
#define PARAM_SRPC "srpc."
#define PARAM_SRPC_FLVR "srpc.flavor."
#define PARAM_SRPC_UDESC "srpc.udesc.cli2mdt"
#define PARAM_SEC "security."
#define PARAM_QUOTA "quota."
#define LUSTRE_MAXFSNAME 8
Functions
int class_find_param (char *buf, char *key, char **valp)
struct cfg_interop_param * class_find_old_param (const char *param, struct cfg_interop_param *ptr)
Check whether the proc parameter param is an old parameter or not from the array ptr which contains the mapping from old parameters to new ones.
int class_get_next_param (char **params, char *copy)
Finds a parameter in params and copies it to copy.
int class_match_param (char *buf, const char *key, char **valp)
int class_parse_nid (char *buf, lnet_nid_t *nid, char **endh)
int class_parse_nid_quiet (char *buf, lnet_nid_t *nid, char **endh)
int class_parse_net (char *buf, __u32 *net, char **endh)
int class_match_nid (char *buf, char *key, lnet_nid_t nid)
int class_match_net (char *buf, char *key, __u32 net)
int do_lcfg (char *cfgname, lnet_nid_t nid, int cmd, char *s1, char *s2, char *s3, char *s4)
lustre_cfg_bufs are a holdover from 1.4; we can still set these up from lctl (and do for echo cli/srv.
static int lustre_is_name_valid (const char *name, const int minlen, const int maxlen)
Check whether the name is valid.
static int lustre_is_fsname_valid (const char *fsname, const int minlen, const int maxlen)
Check whether the fsname is valid.
static int lustre_is_poolname_valid (const char *poolname, const int minlen, const int maxlen)
Check whether the poolname is valid.
Define Documentation
#define LUSTRE_MAXFSNAME 8
Definition at line 126 of file lustre_param.h.
Referenced by extract_fsname_poolname(), and parse_opts().
Function Documentation
static int lustre_is_fsname_valid (const char * fsname, const int minlen, const int maxlen) [inline, static]
Check whether the fsname is valid.
Parameters:
fsname [in] the fsname to be checked
minlen [in] the minimum length of the fsname
maxlen [in] the maximum length of the fsname
Return values:
0 the fsname is valid
>0 the invalid character in the fsname
-1 the fsname is too short
-2 the fsname is too long
Definition at line 176 of file lustre_param.h.
References lustre_is_name_valid().
Referenced by extract_fsname_poolname(), and parse_opts().
static int lustre_is_name_valid (const char * name, const int minlen, const int maxlen) [inline, static]
Check whether the name is valid.
Parameters:
name [in] the name to be checked
minlen [in] the minimum length of the name
maxlen [in] the maximum length of the name
Return values:
0 the name is valid
>0 the invalid character in the name
-1 the name is too short
-2 the name is too long
Definition at line 140 of file lustre_param.h.
Referenced by lustre_is_fsname_valid(), and lustre_is_poolname_valid().
static int lustre_is_poolname_valid (const char * poolname, const int minlen, const int maxlen) [inline, static]
Check whether the poolname is valid.
Parameters:
poolname [in] the poolname to be checked
minlen [in] the minimum length of the poolname
maxlen [in] the maximum length of the poolname
Return values:
0 the poolname is valid
>0 the invalid character in the poolname
-1 the poolname is too short
-2 the poolname is too long
Definition at line 194 of file lustre_param.h.
References lustre_is_name_valid().
Referenced by extract_fsname_poolname(), and lfs_setstripe().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.