Lustre: lustre/utils/lustreapi_internal.h File Reference
lustre/utils/lustreapi_internal.h File Reference
#include <libcfs/util/param.h>
#include <uapi_kernelcomm.h>
Defines
#define WANT_PATH 0x1
#define WANT_FSNAME 0x2
#define WANT_FD 0x4
#define WANT_INDEX 0x8
#define WANT_ERROR 0x10
#define PROC_MOUNTS "/proc/mounts"
#define LLAPI_LAYOUT_MAGIC 0x11AD1107
#define llapi_stripe_offset_is_valid(os) llapi_stripe_index_is_valid(os)
Enumerations
enum param_filter { FILTER_BY_EXACT, FILTER_BY_FS_NAME, FILTER_BY_PATH }
Often when determining the parameter path in sysfs/procfs we are often only interest set of data.
Functions
int get_root_path (int want, char *fsname, int *outfd, char *path, int index)
int root_ioctl (const char *mdtname, int opc, void *data, int *mdtidxp, int want_error)
ioctl on filsystem root, with mdtindex sent as data
int get_lustre_param_path (const char *obd_type, const char *filter, enum param_filter type, const char *param_name, glob_t *param)
return the parameter's path for a specific device type or mountpoint
int get_lustre_param_value (const char *obd_type, const char *filter, enum param_filter type, const char *param_name, char *value, size_t val_len)
return a parameter of a single line value for a specific device type or mountpoint
static int poolpath (glob_t *pool_path, const char *fsname, char *pathname)
static bool llapi_stripe_size_is_aligned (uint64_t size)
static bool llapi_stripe_size_is_too_big (uint64_t size)
static bool llapi_stripe_count_is_valid (int64_t count)
static bool llapi_stripe_index_is_valid (int64_t index)
int libcfs_ukuc_start (struct lustre_kernelcomm *l, int groups, int rfd_flags)
Start the userspace side of a KUC pipe.
int libcfs_ukuc_stop (struct lustre_kernelcomm *l)
int libcfs_ukuc_get_rfd (struct lustre_kernelcomm *link)
Returns the file descriptor for the read side of the pipe, to be used with poll/select.
int libcfs_ukuc_msg_get (struct lustre_kernelcomm *l, char *buf, int maxsize, int transport)
Read a message from the link.
Define Documentation
#define LLAPI_LAYOUT_MAGIC 0x11AD1107
Definition at line 94 of file lustreapi_internal.h.
Referenced by llapi_layout_alloc(), llapi_layout_file_open(), llapi_layout_from_lum(), llapi_layout_ost_index_get(), llapi_layout_ost_index_set(), llapi_layout_pattern_get(), llapi_layout_pattern_set(), llapi_layout_pool_name_get(), llapi_layout_pool_name_set(), llapi_layout_stripe_count_get(), llapi_layout_stripe_count_set(), llapi_layout_stripe_size_get(), and llapi_layout_stripe_size_set().
#define llapi_stripe_offset_is_valid (os) llapi_stripe_index_is_valid(os)
Definition at line 120 of file lustreapi_internal.h.
#define PROC_MOUNTS "/proc/mounts"
Definition at line 49 of file lustreapi_internal.h.
Referenced by get_root_path().
#define WANT_ERROR 0x10
Definition at line 45 of file lustreapi_internal.h.
Referenced by changelog_ioctl(), get_root_path(), and llapi_search_fsname().
#define WANT_FD 0x4
Definition at line 43 of file lustreapi_internal.h.
Referenced by get_root_path(), llapi_hsm_request(), and root_ioctl().
#define WANT_FSNAME 0x2
Definition at line 42 of file lustreapi_internal.h.
Referenced by get_root_path(), llapi_search_fsname(), and llapi_search_mounts().
#define WANT_INDEX 0x8
Definition at line 44 of file lustreapi_internal.h.
Referenced by get_root_path(), and llapi_search_mounts().
#define WANT_PATH 0x1
Definition at line 41 of file lustreapi_internal.h.
Referenced by get_root_path(), llapi_search_mounts(), and llapi_search_rootpath().
Enumeration Type Documentation
enum param_filter
Often when determining the parameter path in sysfs/procfs we are often only interest set of data.
This enum gives use the ability to return data of parameters for:
FILTER_BY_FS_NAME: a specific file system mount FILTER_BY_PATH: Using a Lustre file path to determine which file system is of interest FILTER_BY_EXACT: The default behavior. Search the parameter path as is.
Enumerator:
FILTER_BY_EXACT
FILTER_BY_FS_NAME
FILTER_BY_PATH
Definition at line 67 of file lustreapi_internal.h.
Function Documentation
int get_lustre_param_path (const char * obd_type, const char * filter, enum param_filter type, const char * param_name, glob_t * param)
return the parameter's path for a specific device type or mountpoint
Parameters:
param the results returned to the caller
obd_type Lustre OBD device type
filter filter combined with the type agrument allow the
type caller to limit the scope of the search for the parameter's path. Typical options are search by Lustre filesystem name or by the path to a file or directory in the filesystem.
param_name parameter name to fetch
Using filter and the type argument we can limit the scope of the search to either the parameter belonging to a specific lustre filesystem (if it exists) or using a given file or directory path located on a mounted Lustre filesystem. The last case it can do is a special search based on exactly what the user passed instead of scanning file paths or specific file systems.
If "obd_type" matches a Lustre device then the first matching device (as with "lctl dl", constrained by
Parameters:
filter and
type) will be used to provide the return value, otherwise the first such device found will be used.
Return 0 for success, with the results stored in
Parameters:
param. Return -ve value for error.
Definition at line 63 of file liblustreapi_param.c.
References cfs_get_param_paths(), FILTER_BY_FS_NAME, FILTER_BY_PATH, llapi_error(), LLAPI_MSG_ERROR, and llapi_search_fsname().
Referenced by get_lustre_param_value(), llapi_get_target_uuids(), llapi_search_ost(), poolpath(), and setup_obd_uuid().
int get_lustre_param_value (const char * obd_type, const char * filter, enum param_filter type, const char * param_name, char * value, size_t val_len)
return a parameter of a single line value for a specific device type or mountpoint
Parameters:
obd_type Lustre OBD device type
filter filter combined with the type agruments allow the
type caller to limit the scope of the search for the parameter's path. Typical options are search by Lustre filesystem name or by the path to a file or directory in the filesystem.
param_name parameter name to fetch
value return buffer for parameter value string
val_len size of buffer for return value
Using filter and the type argument we can limit the scope of the search to either the parameter belonging to a specific lustre filesystem (if it exists) or using a given file or directory path located on a mounted Lustre filesystem. The last case it can do is a special search based on exactly what the user passed instead of scanning file paths or specific file systems.
If "obd_type" matches a Lustre device then the first matching device (as with "lctl dl", constrained by
Parameters:
filter and
type) will be used to provide the return value, otherwise the first such device found will be used.
Return 0 for success, with a NUL-terminated string in
Parameters:
value. Return negative errno value for error.
Definition at line 146 of file liblustreapi_param.c.
References cfs_free_param_data(), get_lustre_param_path(), llapi_error(), and LLAPI_MSG_ERROR.
Referenced by get_mds_md_size(), get_param_lmv(), get_param_lov(), llapi_poollist(), and sattr_get_defaults().
int get_root_path (int want, char * fsname, int * outfd, char * path, int index)
Definition at line 848 of file liblustreapi.c.
References buf, llapi_err_noerrno, llapi_error(), llapi_is_lustre_mnt(), LLAPI_MSG_ERROR, PROC_MOUNTS, WANT_ERROR, WANT_FD, WANT_FSNAME, WANT_INDEX, and WANT_PATH.
Referenced by llapi_hsm_request(), llapi_search_fsname(), llapi_search_mounts(), llapi_search_rootpath(), and root_ioctl().
int libcfs_ukuc_get_rfd (struct lustre_kernelcomm * link)
Returns the file descriptor for the read side of the pipe, to be used with poll/select.
Parameters:
link Private descriptor for pipe/socket.
Definition at line 93 of file liblustreapi_kernelconn.c.
References lustre_kernelcomm::lk_rfd.
Referenced by llapi_hsm_copytool_get_fd().
int libcfs_ukuc_msg_get (struct lustre_kernelcomm * link, char * buf, int maxsize, int transport)
Read a message from the link.
Allocates memory, returns handle
Parameters:
link Private descriptor for pipe/socket.
buf Buffer to read into, must include size for kuc_hdr
maxsize Maximum message size allowed
transport Only listen to messages on this transport (and the generic transport)
Definition at line 109 of file liblustreapi_kernelconn.c.
References KUC_MAGIC, kuc_hdr::kuc_magic, kuc_hdr::kuc_msglen, kuc_hdr::kuc_transport, KUC_TRANSPORT_GENERIC, lhsz, lustre_kernelcomm::lk_rfd, llapi_err_noerrno, and LLAPI_MSG_ERROR.
Referenced by llapi_changelog_recv(), and llapi_hsm_copytool_recv().
int libcfs_ukuc_start (struct lustre_kernelcomm * link, int group, int rfd_flags)
Start the userspace side of a KUC pipe.
Parameters:
link Private descriptor for pipe/socket.
groups KUC broadcast group to listen to (can be null for unicast to this pid)
rfd_flags flags for read side of pipe (e.g. O_NONBLOCK)
Definition at line 52 of file liblustreapi_kernelconn.c.
References lustre_kernelcomm::lk_group, LK_NOFD, lustre_kernelcomm::lk_rfd, lustre_kernelcomm::lk_uid, and lustre_kernelcomm::lk_wfd.
Referenced by llapi_changelog_start(), and llapi_hsm_copytool_register().
int libcfs_ukuc_stop (struct lustre_kernelcomm * l)
Definition at line 78 of file liblustreapi_kernelconn.c.
References LK_NOFD, lustre_kernelcomm::lk_rfd, and lustre_kernelcomm::lk_wfd.
Referenced by llapi_changelog_fini(), llapi_hsm_copytool_register(), and llapi_hsm_copytool_unregister().
static bool llapi_stripe_count_is_valid (int64_t count) [inline, static]
Definition at line 108 of file lustreapi_internal.h.
References LOV_MAX_STRIPE_COUNT.
Referenced by llapi_layout_stripe_count_is_valid(), and llapi_stripe_limit_check().
static bool llapi_stripe_index_is_valid (int64_t index) [inline, static]
Definition at line 113 of file lustreapi_internal.h.
References LOV_V1_INSANE_STRIPE_COUNT.
Referenced by llapi_layout_stripe_index_is_valid(), and llapi_stripe_limit_check().
static bool llapi_stripe_size_is_aligned (uint64_t size) [inline, static]
Definition at line 98 of file lustreapi_internal.h.
References LOV_MIN_STRIPE_SIZE.
Referenced by llapi_layout_stripe_size_is_valid(), and llapi_stripe_limit_check().
static bool llapi_stripe_size_is_too_big (uint64_t size) [inline, static]
Definition at line 103 of file lustreapi_internal.h.
Referenced by llapi_layout_stripe_size_is_valid(), and llapi_stripe_limit_check().
static int poolpath (glob_t * pool_path, const char * fsname, char * pathname) [inline, static]
Definition at line 81 of file lustreapi_internal.h.
References FILTER_BY_FS_NAME, FILTER_BY_PATH, and get_lustre_param_path().
Referenced by llapi_get_poollist(), llapi_get_poolmembers(), and llapi_search_ost().
int root_ioctl (const char * mdtname, int opc, void * data, int * mdtidxp, int want_error)
ioctl on filsystem root, with mdtindex sent as data
Parameters:
mdtname path, fsname, or mdtname (lutre-MDT0004)
mdtidxp pointer to integer within data to be filled in with the mdt index (0 if no mdt is specified). NULL won't be filled.
Definition at line 3867 of file liblustreapi.c.
References get_mdtname(), get_root_path(), llapi_err_noerrno, LLAPI_MSG_ERROR, and WANT_FD.
Referenced by changelog_ioctl(), and llapi_fid2path().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.