Lustre: lustre/include/lustre/lustreapi.h File Reference
lustre/include/lustre/lustreapi.h File Reference
#include <stdarg.h>
#include <stdint.h>
#include <lustre/lustre_user.h>
Data Structures
struct llapi_stripe_param
struct find_param
Defines
#define ARRAY_SIZE(a) ((sizeof(a)) / (sizeof((a)[0])))
#define LLAPI_MSG_MASK 0x00000007
#define LLAPI_MSG_NO_ERRNO 0x00000010
#define llapi_err_noerrno(level, fmt, a...) llapi_error((level) | LLAPI_MSG_NO_ERRNO, 0, fmt, ## a)
#define HAVE_LLAPI_FILE_LOOKUP
#define VERBOSE_COUNT 0x1
#define VERBOSE_SIZE 0x2
#define VERBOSE_OFFSET 0x4
#define VERBOSE_POOL 0x8
#define VERBOSE_DETAIL 0x10
#define VERBOSE_OBJID 0x20
#define VERBOSE_GENERATION 0x40
#define VERBOSE_MDTINDEX 0x80
#define VERBOSE_LAYOUT 0x100
#define VERBOSE_ALL
#define HAVE_LLAPI_IS_LUSTRE_MNT
#define HAVE_CHANGELOG_EXTEND_REC 1
#define LAYOUT_GET_EXPECTED 0x1
#define LLAPI_LAYOUT_INVALID 0x1000000000000001ULL
Not a valid stripe size, offset, or RAID pattern.
#define LLAPI_LAYOUT_DEFAULT (LLAPI_LAYOUT_INVALID + 1)
When specified or returned as the value for stripe count, stripe size, offset, or RAID pattern, the filesystem-wide default behavior will apply.
#define LLAPI_LAYOUT_WIDE (LLAPI_LAYOUT_INVALID + 2)
When specified or returned as the value for stripe count, all available OSTs will be used.
#define LLAPI_LAYOUT_RAID0 0
When specified as the value for layout pattern, file objects will be stored using RAID0.
Typedefs
typedef void(* llapi_cb_t)(char *obd_type_name, char *obd_name, char *obd_uuid, void *args)
typedef void(* llapi_log_callback_t)(enum llapi_message_level level, int err, const char *fmt, va_list ap)
Enumerations
enum llapi_message_level {
LLAPI_MSG_OFF = 0, LLAPI_MSG_FATAL = 1, LLAPI_MSG_ERROR = 2, LLAPI_MSG_WARN = 3,
LLAPI_MSG_NORMAL = 4, LLAPI_MSG_INFO = 5, LLAPI_MSG_DEBUG = 6, LLAPI_MSG_MAX
}
Functions
static const char * llapi_msg_level2str (enum llapi_message_level level)
void llapi_msg_set_level (int level)
int llapi_msg_get_level (void)
llapi_log_callback_t llapi_error_callback_set (llapi_log_callback_t cb)
Set a custom error logging function.
llapi_log_callback_t llapi_info_callback_set (llapi_log_callback_t cb)
Set a custom info logging function.
void llapi_error (enum llapi_message_level level, int err, const char *fmt,...) __attribute__((__format__(__printf__
void llapi_printf (enum llapi_message_level level, const char *fmt,...) __attribute__((__format__(__printf__
int llapi_file_open_param (const char *name, int flags, mode_t mode, const struct llapi_stripe_param *param)
Open a Lustre file.
int llapi_file_create (const char *name, unsigned long long stripe_size, int stripe_offset, int stripe_count, int stripe_pattern)
int llapi_file_open (const char *name, int flags, int mode, unsigned long long stripe_size, int stripe_offset, int stripe_count, int stripe_pattern)
int llapi_file_create_pool (const char *name, unsigned long long stripe_size, int stripe_offset, int stripe_count, int stripe_pattern, char *pool_name)
int llapi_file_open_pool (const char *name, int flags, int mode, unsigned long long stripe_size, int stripe_offset, int stripe_count, int stripe_pattern, char *pool_name)
int llapi_poollist (const char *name)
int llapi_get_poollist (const char *name, char **poollist, int list_size, char *buffer, int buffer_size)
Get the list of pools in a filesystem.
int llapi_get_poolmembers (const char *poolname, char **members, int list_size, char *buffer, int buffer_size)
Get the list of pool members.
int llapi_file_get_stripe (const char *path, struct lov_user_md *lum)
int llapi_file_lookup (int dirfd, const char *name)
int llapi_ostlist (char *path, struct find_param *param)
int llapi_uuid_match (char *real_uuid, char *search_uuid)
int llapi_getstripe (char *path, struct find_param *param)
int llapi_find (char *path, struct find_param *param)
int llapi_file_fget_mdtidx (int fd, int *mdtidx)
int llapi_dir_set_default_lmv_stripe (const char *name, int stripe_offset, int stripe_count, int stripe_pattern, const char *pool_name)
int llapi_dir_create_pool (const char *name, int flags, int stripe_offset, int stripe_count, int stripe_pattern, const char *poolname)
int llapi_direntry_remove (char *dname)
int llapi_obd_statfs (char *path, __u32 type, __u32 index, struct obd_statfs *stat_buf, struct obd_uuid *uuid_buf)
int llapi_ping (char *obd_type, char *obd_name)
int llapi_target_check (int num_types, char **obd_types, char *dir)
int llapi_file_get_lov_uuid (const char *path, struct obd_uuid *lov_uuid)
int llapi_file_get_lmv_uuid (const char *path, struct obd_uuid *lmv_uuid)
int llapi_file_fget_lov_uuid (int fd, struct obd_uuid *lov_uuid)
int llapi_lov_get_uuids (int fd, struct obd_uuid *uuidp, int *ost_count)
int llapi_lmv_get_uuids (int fd, struct obd_uuid *uuidp, int *mdt_count)
int llapi_is_lustre_mnttype (const char *type)
int llapi_search_ost (char *fsname, char *poolname, char *ostname)
int llapi_get_obd_count (char *mnt, int *count, int is_mdt)
int llapi_parse_size (const char *optarg, unsigned long long *size, unsigned long long *size_units, int bytes_spec)
size_units is to be initialized (or zeroed) by caller.
int llapi_search_mounts (const char *pathname, int index, char *mntdir, char *fsname)
int llapi_search_fsname (const char *pathname, char *fsname)
int llapi_getname (const char *path, char *buf, size_t size)
int llapi_search_fileset (const char *pathname, char *fileset)
int llapi_search_rootpath (char *pathname, const char *fsname)
int llapi_nodemap_exists (const char *name)
int llapi_migrate_mdt (char *path, struct find_param *param)
int llapi_mv (char *path, struct find_param *param)
int llapi_is_lustre_mnt (struct mntent *mnt)
int llapi_quotactl (char *mnt, struct if_quotactl *qctl)
int llapi_target_iterate (int type_num, char **obd_type, void *args, llapi_cb_t cb)
int llapi_get_connect_flags (const char *mnt, __u64 *flags)
int llapi_lsetfacl (int argc, char *argv[])
int llapi_lgetfacl (int argc, char *argv[])
int llapi_rsetfacl (int argc, char *argv[])
int llapi_rgetfacl (int argc, char *argv[])
int llapi_cp (int argc, char *argv[])
int llapi_ls (int argc, char *argv[])
int llapi_fid2path (const char *device, const char *fidstr, char *path, int pathlen, long long *recno, int *linkno)
int llapi_path2fid (const char *path, lustre_fid *fid)
int llapi_get_mdt_index_by_fid (int fd, const lustre_fid *fid, int *mdt_index)
int llapi_fd2fid (const int fd, lustre_fid *fid)
int llapi_path2parent (const char *path, unsigned int linkno, lustre_fid *parent_fid, char *name, size_t name_size)
int llapi_fd2parent (int fd, unsigned int linkno, lustre_fid *parent_fid, char *name, size_t name_size)
int llapi_chomp_string (char *buf)
int llapi_open_by_fid (const char *dir, const lustre_fid *fid, int open_flags)
Attempt to open a file with Lustre file identifier fid and return an open file descriptor.
int llapi_get_version (char *buffer, int buffer_size, char **version)
int llapi_get_data_version (int fd, __u64 *data_version, __u64 flags)
Get a 64-bit value representing the version of file data pointed by fd.
int llapi_hsm_state_get_fd (int fd, struct hsm_user_state *hus)
Return the current HSM states and HSM requests related to file pointed by path.
int llapi_hsm_state_get (const char *path, struct hsm_user_state *hus)
Return the current HSM states and HSM requests related to file pointed by path.
int llapi_hsm_state_set_fd (int fd, __u64 setmask, __u64 clearmask, __u32 archive_id)
Set HSM states of file pointed by fd.
int llapi_hsm_state_set (const char *path, __u64 setmask, __u64 clearmask, __u32 archive_id)
Set HSM states of file pointed by path.
int llapi_hsm_register_event_fifo (const char *path)
Given a path to a FIFO, create a filehandle for nonblocking writes to it.
int llapi_hsm_unregister_event_fifo (const char *path)
Given a path to a FIFO, close its filehandle and delete the FIFO.
void llapi_hsm_log_error (enum llapi_message_level level, int _rc, const char *fmt, va_list args)
Custom logging callback to be used when a monitoring FIFO has been registered.
int llapi_get_agent_uuid (char *path, char *buf, size_t bufsize)
int llapi_create_volatile_idx (char *directory, int idx, int mode)
static int llapi_create_volatile (char *directory, int mode)
int llapi_fswap_layouts_grouplock (int fd1, int fd2, __u64 dv1, __u64 dv2, int gid, __u64 flags)
Swap the layouts between 2 file descriptors the 2 files must be open for writing first fd received the ioctl, second fd is passed as arg this is assymetric but avoid use of root path for ioctl.
int llapi_fswap_layouts (int fd1, int fd2, __u64 dv1, __u64 dv2, __u64 flags)
int llapi_swap_layouts (const char *path1, const char *path2, __u64 dv1, __u64 dv2, __u64 flags)
Swap the layouts between 2 files the 2 files are open in write.
int llapi_changelog_start (void **priv, enum changelog_send_flag flags, const char *mdtname, long long startrec)
Start reading from a changelog.
int llapi_changelog_fini (void **priv)
Finish reading from a changelog.
int llapi_changelog_recv (void *priv, struct changelog_rec **rech)
int llapi_changelog_free (struct changelog_rec **rech)
Release the changelog record when done with it.
int llapi_changelog_clear (const char *mdtname, const char *idstr, long long endrec)
int llapi_hsm_copytool_register (struct hsm_copytool_private **priv, const char *mnt, int archive_count, int *archives, int rfd_flags)
Register a copytool.
int llapi_hsm_copytool_unregister (struct hsm_copytool_private **priv)
Deregister a copytool Note: under Linux, until llapi_hsm_copytool_unregister is called (or the program is killed), the libcfs module will be referenced and unremovable, even after Lustre services stop.
int llapi_hsm_copytool_get_fd (struct hsm_copytool_private *ct)
Returns a file descriptor to poll/select on.
int llapi_hsm_copytool_recv (struct hsm_copytool_private *priv, struct hsm_action_list **hal, int *msgsize)
Wait for the next hsm_action_list.
int llapi_hsm_action_begin (struct hsm_copyaction_private **phcp, const struct hsm_copytool_private *ct, const struct hsm_action_item *hai, int restore_mdt_index, int restore_open_flags, bool is_error)
Start processing an HSM action.
int llapi_hsm_action_end (struct hsm_copyaction_private **phcp, const struct hsm_extent *he, int hp_flags, int errval)
Terminate an HSM action processing.
int llapi_hsm_action_progress (struct hsm_copyaction_private *hcp, const struct hsm_extent *he, __u64 total, int hp_flags)
Notify a progress in processing an HSM action.
int llapi_hsm_action_get_dfid (const struct hsm_copyaction_private *hcp, lustre_fid *fid)
Get the fid of object to be used for copying data.
int llapi_hsm_action_get_fd (const struct hsm_copyaction_private *hcp)
Get a file descriptor to be used for copying data.
int llapi_hsm_import (const char *dst, int archive, const struct stat *st, unsigned long long stripe_size, int stripe_offset, int stripe_count, int stripe_pattern, char *pool_name, lustre_fid *newfid)
Import an existing hsm-archived file into Lustre.
struct hsm_user_request * llapi_hsm_user_request_alloc (int itemcount, int data_len)
Allocate a hsm_user_request with the specified carateristics.
int llapi_hsm_request (const char *path, const struct hsm_user_request *request)
Send a HSM request to Lustre, described in.
int llapi_hsm_current_action (const char *path, struct hsm_current_action *hca)
Return the current HSM request related to file pointed by path.
int llapi_json_init_list (struct llapi_json_item_list **item_list)
Create a list to hold JSON items.
int llapi_json_destroy_list (struct llapi_json_item_list **item_list)
Deallocate a list of JSON items.
int llapi_json_add_item (struct llapi_json_item_list **item_list, char *key, __u32 type, void *val)
Add an item to a list of JSON items.
int llapi_json_write_list (struct llapi_json_item_list **item_list, FILE *fp)
Write a list of JSON items to a filehandle.
int llapi_lease_get (int fd, int mode)
Get a lease on an open file.
int llapi_lease_check (int fd)
Check if a lease is still set on a file.
int llapi_lease_put (int fd)
Remove a lease.
int llapi_group_lock (int fd, int gid)
Take group lock.
int llapi_group_unlock (int fd, int gid)
Put group lock.
int llapi_ladvise (int fd, unsigned long long flags, int num_advise, struct lu_ladvise *ladvise)
struct llapi_layout * llapi_layout_get_by_path (const char *path, uint32_t flags)
Return a pointer to a newly-allocated opaque data structure containing the layout for the file at path.
struct llapi_layout * llapi_layout_get_by_fd (int fd, uint32_t flags)
Return a pointer to a newly-allocated opaque data type containing the layout for the file referenced by open file descriptor fd.
struct llapi_layout * llapi_layout_get_by_fid (const char *path, const lustre_fid *fid, uint32_t flags)
Return a pointer to a newly-allocated opaque data type containing the layout for the file associated with Lustre file identifier string fidstr.
struct llapi_layout * llapi_layout_alloc (void)
Allocate a new layout.
void llapi_layout_free (struct llapi_layout *layout)
Free memory allocated for layout.
int llapi_layout_stripe_count_get (const struct llapi_layout *layout, uint64_t *count)
Flags to modify how layouts are retrieved.
int llapi_layout_stripe_count_set (struct llapi_layout *layout, uint64_t count)
Set the stripe count of layout to count.
int llapi_layout_stripe_size_get (const struct llapi_layout *layout, uint64_t *size)
Store the stripe size of layout in size.
int llapi_layout_stripe_size_set (struct llapi_layout *layout, uint64_t size)
Set the stripe size of layout to stripe_size.
int llapi_layout_pattern_get (const struct llapi_layout *layout, uint64_t *pattern)
Store the stripe pattern of layout in pattern.
int llapi_layout_pattern_set (struct llapi_layout *layout, uint64_t pattern)
Set the stripe pattern of layout to pattern.
int llapi_layout_ost_index_get (const struct llapi_layout *layout, uint64_t stripe_number, uint64_t *index)
Store the index of the OST where stripe number stripe_number is stored in index.
int llapi_layout_ost_index_set (struct llapi_layout *layout, int stripe_number, uint64_t index)
Set the OST index associated with stripe number stripe_number to ost_index.
int llapi_layout_pool_name_get (const struct llapi_layout *layout, char *pool_name, size_t pool_name_len)
Store up to pool_name_len characters of the name of the pool of OSTs associated with layout into the buffer pointed to by pool_name.
int llapi_layout_pool_name_set (struct llapi_layout *layout, const char *pool_name)
Set the name of the pool of OSTs from which file objects will be allocated to pool_name.
int llapi_layout_file_open (const char *path, int open_flags, mode_t mode, const struct llapi_layout *layout)
Open an existing file at path, or create it with the specified layout and mode.
int llapi_layout_file_create (const char *path, int open_flags, int mode, const struct llapi_layout *layout)
Create a new file at path with the specified layout and mode.
Variables
bool liblustreapi_initialized
Define Documentation
#define LAYOUT_GET_EXPECTED 0x1
Definition at line 423 of file lustreapi.h.
Referenced by llapi_layout_get_by_path(), test16(), test20(), test24(), test25(), test26(), and test27().
#define LLAPI_LAYOUT_DEFAULT (LLAPI_LAYOUT_INVALID + 1)
When specified or returned as the value for stripe count, stripe size, offset, or RAID pattern, the filesystem-wide default behavior will apply.
Definition at line 475 of file lustreapi.h.
Referenced by inherit_layout_attributes(), is_fully_specified(), llapi_layout_alloc(), llapi_layout_from_lum(), llapi_layout_ost_index_get(), llapi_layout_pattern_set(), llapi_layout_stripe_count_is_valid(), llapi_layout_stripe_index_is_valid(), llapi_layout_stripe_size_is_valid(), llapi_layout_to_lum(), test20(), test24(), test25(), test26(), test27(), test8(), and test9().
#define LLAPI_LAYOUT_INVALID 0x1000000000000001ULL
Not a valid stripe size, offset, or RAID pattern.
Definition at line 468 of file lustreapi.h.
Referenced by test10(), test11(), test13(), and test9().
#define LLAPI_LAYOUT_RAID0 0
When specified as the value for layout pattern, file objects will be stored using RAID0.
That is, data will be split evenly and without redundancy across all OSTs in the layout.
Definition at line 488 of file lustreapi.h.
Referenced by llapi_layout_from_lum(), llapi_layout_pattern_set(), llapi_layout_to_lum(), and test9().
#define LLAPI_LAYOUT_WIDE (LLAPI_LAYOUT_INVALID + 2)
When specified or returned as the value for stripe count, all available OSTs will be used.
Definition at line 481 of file lustreapi.h.
Referenced by llapi_layout_from_lum(), llapi_layout_stripe_count_is_valid(), llapi_layout_to_lum(), test17(), and test28().
Function Documentation
struct llapi_layout* llapi_layout_alloc (void) [read]
Allocate a new layout.
Use this when creating a new file with llapi_layout_file_create().
Allocate a new layout.
Return values:
valid llapi_layout pointer on success
NULL if memory allocation fails
Definition at line 304 of file liblustreapi_layout.c.
References __llapi_layout_alloc(), LLAPI_LAYOUT_DEFAULT, LLAPI_LAYOUT_MAGIC, llapi_layout::llot_magic, llapi_layout::llot_objects_are_valid, llapi_layout::llot_pattern, llapi_layout::llot_pool_name, llapi_layout::llot_stripe_count, llapi_layout::llot_stripe_offset, and llapi_layout::llot_stripe_size.
Referenced by llapi_layout_expected(), llapi_layout_get_by_fd(), test0(), test10(), test11(), test12(), test13(), test14(), test15(), test16(), test17(), test18(), test19(), test20(), test21(), and test9().
int llapi_layout_file_create (const char * path, int open_flags, int mode, const struct llapi_layout * layout)
Create a new file at path with the specified layout and mode.
One access mode and zero or more file creation flags and file status flags May be bitwise-or'd in open_flags (see open(2)). Return an open file descriptor for the file. If layout is non-NULL and path is not on a Lustre filesystem this function will fail and set errno to ENOTTY.
The function call
llapi_layout_file_create(path, open_flags, mode, layout)
shall be equivalent to:
llapi_layout_file_open(path, open_flags|O_CREAT|O_EXCL, mode, layout)
It is an error if path specifies an existing file.
A NULL layout may be specified, in which the standard Lustre behavior for assigning layouts to newly-created files will apply.
Return values:
0+ An open file descriptor.
-1 Error with status code in errno.
Create a new file at path with the specified layout and mode.
Force O_CREAT and O_EXCL flags on so caller is assured that file was created with the given layout on successful function return.
Parameters:
[in] path name of the file to open
[in] open_flags open() flags
[in] mode permissions to create new file with
[in] layout layout to create new file with
Return values:
non-negative file descriptor on successful open
-1 if an error occurred
Definition at line 1002 of file liblustreapi_layout.c.
References llapi_layout_file_open().
Referenced by test0(), test13(), test14(), test15(), test16(), test17(), test18(), test20(), test21(), and test22().
int llapi_layout_file_open (const char * path, int open_flags, mode_t mode, const struct llapi_layout * layout)
Open an existing file at path, or create it with the specified layout and mode.
One access mode and zero or more file creation flags and file status flags May be bitwise-or'd in open_flags (see open(2)). Return an open file descriptor for the file. If layout is non-NULL and path is not on a Lustre filesystem this function will fail and set errno to ENOTTY.
An already existing file may be opened with this function, but layout and mode will not be applied to it. Callers requiring a guarantee that the opened file is created with the specified layout and mode should use llapi_layout_file_create().
A NULL layout may be specified, in which case the standard Lustre behavior for assigning layouts to newly-created files will apply.
Return values:
0+ An open file descriptor.
-1 Error with status code in errno.
Open an existing file at path, or create it with the specified layout and mode.
If layout is NULL this function acts as a simple wrapper for open(). By convention, ENOTTY is returned in errno if path refers to a non-Lustre file.
Parameters:
[in] path name of the file to open
[in] open_flags open() flags
[in] mode permissions to create new file with
[in] layout layout to create new file with
Return values:
non-negative file descriptor on successful open
-1 if an error occurred
Definition at line 938 of file liblustreapi_layout.c.
References LLAPI_LAYOUT_MAGIC, llapi_layout_to_lum(), llapi_layout::llot_magic, lov_user_md, lov_user_md_size(), O_LOV_DELAY_CREATE, and XATTR_LUSTRE_LOV.
Referenced by llapi_layout_file_create(), and test15().
void llapi_layout_free (struct llapi_layout * layout)
Free memory allocated for layout.
Definition at line 625 of file liblustreapi_layout.c.
Referenced by llapi_layout_expected(), test0(), test1(), test10(), test11(), test12(), test13(), test14(), test15(), test16(), test17(), test18(), test19(), test2(), test20(), test21(), test24(), test25(), test26(), test27(), test28(), test3(), test4(), test8(), and test9().
struct llapi_layout* llapi_layout_get_by_fd (int fd, uint32_t flags) [read]
Return a pointer to a newly-allocated opaque data type containing the layout for the file referenced by open file descriptor fd.
The pointer should be freed with llapi_layout_free() when it is no longer needed. Failure is indicated by a NULL return value and an appropriate error code stored in errno.
Return a pointer to a newly-allocated opaque data type containing the layout for the file referenced by open file descriptor fd.
If the filesystem does not support the "lustre." xattr namespace, the file must be on a non-Lustre filesystem, so set errno to ENOTTY per convention. If the file has no "lustre.lov" data, the file will inherit default values, so return a default layout.
If the kernel gives us back less than the expected amount of data, we fail with errno set to EINTR.
Parameters:
[in] fd open file descriptor
[in] flags open file descriptor
Return values:
valid llapi_layout pointer on success
NULL if an error occurs
Definition at line 398 of file liblustreapi_layout.c.
References __swab16, __swab32, llapi_layout_alloc(), llapi_layout_from_lum(), llapi_layout_lum_truncated(), llapi_layout_objects_in_lum(), llapi_layout_swab_lov_user_md(), LOV_MAGIC_V1, LOV_MAGIC_V3, lov_user_md, and XATTR_LUSTRE_LOV.
Referenced by llapi_layout_expected(), llapi_layout_get_by_fid(), llapi_layout_get_by_path(), test2(), and test6().
struct llapi_layout* llapi_layout_get_by_fid (const char * lustre_dir, const lustre_fid * fid, uint32_t flags) [read]
Return a pointer to a newly-allocated opaque data type containing the layout for the file associated with Lustre file identifier string fidstr.
The string path must name a path within the filesystem that contains the file being looked up, such as the filesystem root. The returned pointer should be freed with llapi_layout_free() when it is no longer needed. Failure is indicated with a NULL return value and an appropriate error code stored in errno.
Return a pointer to a newly-allocated opaque data type containing the layout for the file associated with Lustre file identifier string fidstr.
Parameters:
[in] lustre_dir path within Lustre filesystem containing fid
[in] fid Lustre identifier of file to get layout for
Return values:
valid llapi_layout pointer on success
NULL if an error occurs
Definition at line 597 of file liblustreapi_layout.c.
References llapi_layout_get_by_fd(), llapi_msg_get_level(), LLAPI_MSG_OFF, llapi_msg_set_level(), and llapi_open_by_fid().
Referenced by test3().
struct llapi_layout* llapi_layout_get_by_path (const char * path, uint32_t flags) [read]
Return a pointer to a newly-allocated opaque data structure containing the layout for the file at path.
The pointer should be freed with llapi_layout_free() when it is no longer needed. Failure is indicated by a NULL return value and an appropriate error code stored in errno.
Return a pointer to a newly-allocated opaque data structure containing the layout for the file at path.
If flags contains LAYOUT_GET_EXPECTED, substitute expected inherited attribute values for unspecified attributes. See llapi_layout_expected().
Parameters:
[in] path path for which to get the layout
[in] flags flags to control how layout is retrieved
Return values:
valid llapi_layout pointer on success
NULL if an error occurs
Definition at line 567 of file liblustreapi_layout.c.
References LAYOUT_GET_EXPECTED, llapi_layout_expected(), and llapi_layout_get_by_fd().
Referenced by llapi_layout_expected(), test1(), test13(), test15(), test16(), test17(), test18(), test20(), test23(), test24(), test25(), test26(), test27(), test28(), test4(), test5(), test7(), and test8().
int llapi_layout_ost_index_get (const struct llapi_layout * layout, uint64_t stripe_number, uint64_t * index)
Store the index of the OST where stripe number stripe_number is stored in index.
An error return value will result from a NULL layout, if stripe_number is out of range, or if layout was not initialized with llapi_layout_lookup_by{path,fd,fid}().
Return values:
0 Success
-1 Invalid argument, errno set to EINVAL.
Store the index of the OST where stripe number stripe_number is stored in index.
Stripes are indexed starting from zero.
Parameters:
[in] layout layout to get index from
[in] stripe_number stripe number to get index for
[out] index integer to store index in
Return values:
0 on success
-1 if arguments are invalid
Definition at line 844 of file liblustreapi_layout.c.
References lov_user_ost_data_v1::l_ost_idx, LLAPI_LAYOUT_DEFAULT, LLAPI_LAYOUT_MAGIC, llapi_layout::llot_magic, llapi_layout::llot_objects, llapi_layout::llot_objects_are_valid, and llapi_layout::llot_stripe_count.
Referenced by __test1_helper(), test13(), and test4().
int llapi_layout_ost_index_set (struct llapi_layout * layout, int stripe_number, uint64_t ost_index)
Set the OST index associated with stripe number stripe_number to ost_index.
NB: This is currently supported only for stripe_number = 0 and other usage will return ENOTSUPP in errno. A NULL layout or out-of-range stripe_number will return EINVAL in errno.
Return values:
0 Success.
-1 Error with errno set to non-zero value.
Set the OST index associated with stripe number stripe_number to ost_index.
The index may only be set for stripe number 0 for now.
Parameters:
[in] layout layout to set OST index in
[in] stripe_number stripe number to set index for
[in] ost_index the index to set
Return values:
0 on success
-1 if arguments are invalid or an unsupported stripe number was specified
Definition at line 813 of file liblustreapi_layout.c.
References LLAPI_LAYOUT_MAGIC, llapi_layout_stripe_index_is_valid(), llapi_layout::llot_magic, and llapi_layout::llot_stripe_offset.
Referenced by test0(), and test13().
int llapi_layout_pattern_get (const struct llapi_layout * layout, uint64_t * pattern)
Store the stripe pattern of layout in pattern.
Return values:
0 Success.
-1 Error with status code in errno.
Store the stripe pattern of layout in pattern.
Parameters:
[in] layout layout to get pattern from
[out] pattern integer to store pattern in
Return values:
0 on success
-1 if arguments are invalid
Definition at line 758 of file liblustreapi_layout.c.
References LLAPI_LAYOUT_MAGIC, llapi_layout::llot_magic, and llapi_layout::llot_pattern.
Referenced by test24(), test25(), test26(), test27(), and test8().
int llapi_layout_pattern_set (struct llapi_layout * layout, uint64_t pattern)
Set the stripe pattern of layout to pattern.
Return values:
0 Success.
-1 Invalid argument, errno set to EINVAL.
Set the stripe pattern of layout to pattern.
Parameters:
[in] layout layout to set pattern in
[in] pattern value to be set
Return values:
0 on success
-1 if arguments are invalid or RAID pattern is unsupported
Definition at line 782 of file liblustreapi_layout.c.
References LLAPI_LAYOUT_DEFAULT, LLAPI_LAYOUT_MAGIC, LLAPI_LAYOUT_RAID0, llapi_layout::llot_magic, and llapi_layout::llot_pattern.
Referenced by test9().
int llapi_layout_pool_name_get (const struct llapi_layout * layout, char * dest, size_t n)
Store up to pool_name_len characters of the name of the pool of OSTs associated with layout into the buffer pointed to by pool_name.
The correct calling form is:
llapi_layout_pool_name_get(layout, pool_name, sizeof(pool_name));
A pool defines a set of OSTs from which file objects may be allocated for a file using layout.
On success, the number of bytes stored is returned, excluding the terminating '' character (zero indicates that layout does not have an associated OST pool). On error, -1 is returned and errno is set appropriately. Possible sources of error include a NULL pointer argument or insufficient space in dest to store the pool name, in which cases errno will be set to EINVAL.
Return values:
0+ The number of bytes stored in dest.
-1 Invalid argument, errno set to EINVAL.
Store up to pool_name_len characters of the name of the pool of OSTs associated with layout into the buffer pointed to by pool_name.
Parameters:
[in] layout layout to get pool name from
[out] dest buffer to store pool name in
[in] n size in bytes of buffer dest
Return values:
0 on success
-1 if arguments are invalid
Definition at line 873 of file liblustreapi_layout.c.
References LLAPI_LAYOUT_MAGIC, llapi_layout::llot_magic, and llapi_layout::llot_pool_name.
Referenced by __test1_helper(), test0(), test12(), test18(), test19(), and test4().
int llapi_layout_pool_name_set (struct llapi_layout * layout, const char * pool_name)
Set the name of the pool of OSTs from which file objects will be allocated to pool_name.
If the pool name uses "fsname.pool" notation to qualify the pool name with a filesystem name, the "fsname." portion will be silently discarded before storing the value. No validation that pool_name is an existing non-empty pool in filesystem fsname will be performed. Such validation can be performed by the application if desired using the llapi_search_ost() function. The maximum length of the stored value is defined by the constant LOV_MAXPOOLNAME.
Return values:
0 Success.
-1 Invalid argument, errno set to EINVAL.
Set the name of the pool of OSTs from which file objects will be allocated to pool_name.
Parameters:
[in] layout layout to set pool name in
[in] pool_name pool name to set
Return values:
0 on success
-1 if arguments are invalid or pool name is too long
Definition at line 896 of file liblustreapi_layout.c.
References LLAPI_LAYOUT_MAGIC, llapi_layout::llot_magic, llapi_layout::llot_pool_name, and LOV_MAXPOOLNAME.
Referenced by test0(), test12(), test18(), and test19().
int llapi_layout_stripe_count_get (const struct llapi_layout * layout, uint64_t * count)
Flags to modify how layouts are retrieved.
Store the stripe count of layout in count.
Return values:
0 Success
-1 Error with status code in errno.
Flags to modify how layouts are retrieved.
Parameters:
[in] layout layout to get stripe count from
[out] count integer to store stripe count in
Return values:
0 on success
-1 if arguments are invalid
Definition at line 639 of file liblustreapi_layout.c.
References LLAPI_LAYOUT_MAGIC, llapi_layout::llot_magic, and llapi_layout::llot_stripe_count.
Referenced by __test1_helper(), test0(), test10(), test15(), test16(), test17(), test20(), test24(), test25(), test26(), test27(), test28(), test4(), and test8().
int llapi_layout_stripe_count_set (struct llapi_layout * layout, uint64_t count)
Set the stripe count of layout to count.
Return values:
0 Success.
-1 Invalid argument, errno set to EINVAL.
Set the stripe count of layout to count.
Parameters:
[in] layout layout to set stripe count in
[in] count value to be set
Return values:
0 on success
-1 if arguments are invalid
Definition at line 689 of file liblustreapi_layout.c.
References LLAPI_LAYOUT_MAGIC, llapi_layout_stripe_count_is_valid(), llapi_layout::llot_magic, and llapi_layout::llot_stripe_count.
Referenced by test0(), test10(), test13(), test15(), test17(), and test20().
int llapi_layout_stripe_size_get (const struct llapi_layout * layout, uint64_t * size)
Store the stripe size of layout in size.
Return values:
0 Success.
-1 Invalid argument, errno set to EINVAL.
Store the stripe size of layout in size.
Parameters:
[in] layout layout to get stripe size from
[out] size integer to store stripe size in
Return values:
0 on success
-1 if arguments are invalid
Definition at line 712 of file liblustreapi_layout.c.
References LLAPI_LAYOUT_MAGIC, llapi_layout::llot_magic, and llapi_layout::llot_stripe_size.
Referenced by __test1_helper(), test0(), test11(), test16(), test20(), test24(), test25(), test26(), test27(), test4(), and test8().
int llapi_layout_stripe_size_set (struct llapi_layout * layout, uint64_t size)
Set the stripe size of layout to stripe_size.
Return values:
0 Success.
-1 Invalid argument, errno set to EINVAL.
Set the stripe size of layout to stripe_size.
Parameters:
[in] layout layout to set stripe size in
[in] size value to be set
Return values:
0 on success
-1 if arguments are invalid
Definition at line 735 of file liblustreapi_layout.c.
References LLAPI_LAYOUT_MAGIC, llapi_layout_stripe_size_is_valid(), llapi_layout::llot_magic, and llapi_layout::llot_stripe_size.
Referenced by test0(), test11(), and test20().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.