Lustre: lustre/utils/lustre_rsync.c File Reference
lustre/utils/lustre_rsync.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <getopt.h>
#include <stdarg.h>
#include <fcntl.h>
#include <signal.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <errno.h>
#include <limits.h>
#include <utime.h>
#include <time.h>
#include <sys/xattr.h>
#include <libcfs/util/parser.h>
#include <lustre/lustreapi.h>
#include <lustre/lustre_idl.h>
#include "lustre_rsync.h"
Data Structures
struct lr_info
struct lr_parent_child_list
Defines
#define REPLICATE_STATUS_VER 1
#define CLEAR_INTERVAL 100
#define DEFAULT_RSYNC_THRESHOLD 0xA00000
#define TYPE_STR_LEN 16
#define DEFAULT_MDT "-MDT0000"
#define SPECIAL_DIR ".lustrerepl"
#define RSYNC "rsync"
#define TYPE "type"
#define DINFO 1
#define DTRACE 2
#define DEBUG_ENTRY(info)
#define DEBUG_EXIT(info, rc)
Functions
int obd_initialize (int argc, char **argv)
void lr_usage ()
void lr_debug (int level, const char *fmt,...)
void * lr_grow_buf (void *buf, int size)
int lr_rsync_data (struct lr_info *info)
int lr_copy_data (struct lr_info *info)
int lr_sync_data (struct lr_info *info)
int lr_copy_attr (char *src, char *dest)
int lr_copy_xattr (struct lr_info *info)
int lr_get_path_ln (struct lr_info *info, char *fidstr, int linkno)
int lr_get_path (struct lr_info *info, char *fidstr)
void lr_get_FID_PATH (char *mntpt, char *fidstr, char *buf, int bufsize)
int lr_get_symlink (struct lr_info *info)
int lr_mkfile (struct lr_info *info)
int lr_add_pc (const char *pfid, const char *tfid, const char *name)
void lr_cascade_move (const char *fid, const char *dest, struct lr_info *info)
int lr_remove_pc (const char *pfid, const char *tfid)
int lr_mk_special (struct lr_info *info)
int lr_rmfile (struct lr_info *info)
int lr_rm_recursive (struct lr_info *info)
int lr_rm_special (struct lr_info *info)
int lr_create (struct lr_info *info)
int lr_remove (struct lr_info *info)
int lr_move (struct lr_info *info)
int lr_link (struct lr_info *info)
int lr_setattr (struct lr_info *info)
int lr_setxattr (struct lr_info *info)
int lr_parse_line (void *priv, struct lr_info *info)
int lr_init_status ()
void lr_backup_log ()
int lr_write_log ()
int lr_read_log ()
int lr_clear_cl (struct lr_info *info, int force)
int lr_locate_rsync ()
void lr_print_status (struct lr_info *info)
void lr_print_failure (struct lr_info *info, int rc)
int lr_replicate ()
void termination_handler (int signum)
int main (int argc, char *argv[])
Variables
command_t cmdlist [0]
struct lustre_rsync_status * status
char * statuslog
int logbackedup
int noxattr
int noclear
int debug
int verbose
long long rec_count
int errors
int dryrun
int use_rsync
long long rsync_threshold = DEFAULT_RSYNC_THRESHOLD
int quit
int abort_on_err = 0
char rsync [PATH_MAX]
char rsync_ver [PATH_MAX]
struct lr_parent_child_list * parents
FILE * debug_log
struct option long_opts []
Define Documentation
#define CLEAR_INTERVAL 100
Definition at line 133 of file lustre_rsync.c.
Referenced by lr_clear_cl().
#define DEBUG_ENTRY (info)
Value:
lr_debug(D_TRACE, "***** Start %lld %s (%d) %s %s %s *****\n",         \
                 (info)->recno, changelog_type2str((info)->type),              \
                 (info)->type, (info)->tfid, (info)->pfid, (info)->name);
Definition at line 245 of file lustre_rsync.c.
Referenced by lr_replicate().
#define DEBUG_EXIT (info, rc)
Value:
lr_debug(D_TRACE, "##### End %lld %s (%d) %s %s %s rc=%d #####\n",     \
                 (info)->recno, changelog_type2str((info)->type),              \
                 (info)->type, (info)->tfid, (info)->pfid, (info)->name, rc);
Definition at line 250 of file lustre_rsync.c.
Referenced by lr_replicate().
#define DEFAULT_MDT "-MDT0000"
Definition at line 138 of file lustre_rsync.c.
Referenced by lr_replicate().
#define DEFAULT_RSYNC_THRESHOLD 0xA00000
Definition at line 134 of file lustre_rsync.c.
#define DINFO 1
Definition at line 144 of file lustre_rsync.c.
Referenced by lr_copy_xattr(), lr_create(), lr_link(), lr_mkfile(), lr_move(), lr_remove(), lr_rm_special(), lr_rsync_data(), lr_setattr(), and lr_setxattr().
#define DTRACE 2
Definition at line 145 of file lustre_rsync.c.
Referenced by lr_copy_data(), lr_copy_xattr(), lr_create(), lr_get_symlink(), lr_link(), lr_mkfile(), and lr_rsync_data().
#define REPLICATE_STATUS_VER 1
Definition at line 132 of file lustre_rsync.c.
Referenced by lr_init_status().
#define RSYNC "rsync"
Definition at line 140 of file lustre_rsync.c.
Referenced by lr_locate_rsync(), and main().
#define SPECIAL_DIR ".lustrerepl"
Definition at line 139 of file lustre_rsync.c.
Referenced by lr_cascade_move(), lr_link(), lr_mk_special(), lr_move(), lr_replicate(), and lr_rm_special().
#define TYPE "type"
Definition at line 141 of file lustre_rsync.c.
Referenced by lr_locate_rsync().
#define TYPE_STR_LEN 16
Definition at line 136 of file lustre_rsync.c.
Function Documentation
int lr_add_pc (const char * pfid, const char * tfid, const char * name)
Definition at line 639 of file lustre_rsync.c.
References lr_parent_child_list::pc_log, lr_parent_child_list::pc_next, lr_parent_child_log::pcl_name, lr_parent_child_log::pcl_pfid, lr_parent_child_log::pcl_tfid, and strlcpy().
Referenced by lr_mk_special(), and lr_move().
void lr_backup_log ()
Definition at line 1205 of file lustre_rsync.c.
References logbackedup, and statuslog.
Referenced by lr_write_log().
void lr_cascade_move (const char * fid, const char * dest, struct lr_info * info)
Definition at line 666 of file lustre_rsync.c.
References errors, lustre_rsync_status::ls_targets, lr_parent_child_list::pc_log, lr_parent_child_list::pc_next, lr_parent_child_log::pcl_name, lr_parent_child_log::pcl_pfid, lr_parent_child_log::pcl_tfid, SPECIAL_DIR, lr_info::src, and lr_info::target_no.
Referenced by lr_move().
int lr_clear_cl (struct lr_info * info, int force)
Definition at line 1370 of file lustre_rsync.c.
References CL_RENAME, CLEAR_INTERVAL, dryrun, llapi_changelog_clear(), LR_NAME_MAXLEN, lr_write_log(), lustre_rsync_status::ls_last_recno, lustre_rsync_status::ls_mdt_device, lustre_rsync_status::ls_registration, noclear, lr_info::recno, strlcpy(), and lr_info::type.
Referenced by lr_replicate().
int lr_copy_attr (char * src, char * dest)
Definition at line 440 of file lustre_rsync.c.
Referenced by lr_mkfile(), and lr_setattr().
int lr_copy_data (struct lr_info * info)
Definition at line 348 of file lustre_rsync.c.
References buf, lr_info::buf, lr_info::bufsize, bufsize, lr_info::dest, DTRACE, lr_debug(), lr_grow_buf(), lr_rsync_data(), rsync, rsync_threshold, lr_info::src, and lr_info::tfid.
Referenced by lr_sync_data().
int lr_copy_xattr (struct lr_info * info)
Definition at line 458 of file lustre_rsync.c.
References lr_info::dest, DINFO, DTRACE, errors, lr_debug(), lr_grow_buf(), noxattr, size, lr_info::src, start, lr_info::xlist, lr_info::xsize, lr_info::xvalue, and lr_info::xvsize.
Referenced by lr_mkfile(), and lr_setxattr().
int lr_create (struct lr_info * info)
Definition at line 785 of file lustre_rsync.c.
References lr_info::dest, DINFO, DTRACE, lr_debug(), lr_get_FID_PATH(), lr_get_path(), lr_mk_special(), lr_mkfile(), lustre_rsync_status::ls_num_targets, lustre_rsync_status::ls_source, lustre_rsync_status::ls_targets, lr_info::name, lr_info::path, lr_info::pfid, lr_info::savedpath, lr_info::src, lr_info::target_no, and lr_info::tfid.
Referenced by lr_replicate().
void lr_debug (int level, const char * fmt, ...)
Definition at line 257 of file lustre_rsync.c.
References debug, and debug_log.
Referenced by lr_copy_data(), lr_copy_xattr(), lr_create(), lr_get_symlink(), lr_link(), lr_mkfile(), lr_move(), lr_remove(), lr_rm_special(), lr_rsync_data(), lr_setattr(), and lr_setxattr().
void lr_get_FID_PATH (char * mntpt, char * fidstr, char * buf, int bufsize)
Definition at line 551 of file lustre_rsync.c.
References dot_lustre_name.
Referenced by lr_create(), lr_get_symlink(), lr_link(), lr_mkfile(), lr_setattr(), and lr_setxattr().
int lr_get_path (struct lr_info * info, char * fidstr)
Definition at line 545 of file lustre_rsync.c.
References lr_get_path_ln().
Referenced by lr_create(), lr_link(), lr_move(), lr_remove(), lr_setattr(), and lr_setxattr().
int lr_get_path_ln (struct lr_info * info, char * fidstr, int linkno)
Definition at line 528 of file lustre_rsync.c.
References llapi_fid2path(), lustre_rsync_status::ls_source, and lr_info::path.
Referenced by lr_get_path(), and lr_link().
int lr_get_symlink (struct lr_info * info)
Definition at line 560 of file lustre_rsync.c.
References DTRACE, lr_info::link, lr_info::linktmp, lr_debug(), lr_get_FID_PATH(), lustre_rsync_status::ls_source, lustre_rsync_status::ls_targets, lr_info::src, strlcpy(), lr_info::target_no, and lr_info::tfid.
Referenced by lr_mkfile().
void* lr_grow_buf (void * buf, int size)
Definition at line 273 of file lustre_rsync.c.
Referenced by lr_copy_data(), lr_copy_xattr(), lr_read_log(), and main().
int lr_init_status ()
Definition at line 1189 of file lustre_rsync.c.
References lustre_rsync_status::ls_last_recno, lustre_rsync_status::ls_size, lustre_rsync_status::ls_version, REPLICATE_STATUS_VER, and size.
Referenced by main().
int lr_link (struct lr_info * info)
Definition at line 989 of file lustre_rsync.c.
References lr_info::dest, DINFO, DTRACE, lr_debug(), lr_get_FID_PATH(), lr_get_path(), lr_get_path_ln(), lustre_rsync_status::ls_num_targets, lustre_rsync_status::ls_source, lustre_rsync_status::ls_targets, lr_info::name, lr_info::path, lr_info::pfid, SPECIAL_DIR, lr_info::src, strlcpy(), lr_info::target_no, and lr_info::tfid.
Referenced by lr_replicate().
int lr_locate_rsync ()
Definition at line 1408 of file lustre_rsync.c.
References RSYNC, rsync, rsync_ver, and TYPE.
Referenced by main().
int lr_mk_special (struct lr_info * info)
Definition at line 725 of file lustre_rsync.c.
References lr_info::dest, lr_add_pc(), lr_mkfile(), lustre_rsync_status::ls_targets, lr_info::name, lr_info::pfid, SPECIAL_DIR, lr_info::target_no, and lr_info::tfid.
Referenced by lr_create().
int lr_mkfile (struct lr_info * info)
Definition at line 589 of file lustre_rsync.c.
References CL_CREATE, CL_MKDIR, CL_MKNOD, CL_SOFTLINK, lr_info::dest, DINFO, DTRACE, lr_info::link, lr_copy_attr(), lr_copy_xattr(), lr_debug(), lr_get_FID_PATH(), lr_get_symlink(), lr_sync_data(), lustre_rsync_status::ls_source, lr_info::src, lr_info::tfid, and lr_info::type.
Referenced by lr_create(), and lr_mk_special().
int lr_move (struct lr_info * info)
Definition at line 902 of file lustre_rsync.c.
References lr_info::dest, DINFO, lr_info::is_extended, LASSERT, lr_add_pc(), lr_cascade_move(), lr_debug(), lr_get_path(), lr_remove_pc(), lustre_rsync_status::ls_num_targets, lustre_rsync_status::ls_targets, lr_info::name, lr_info::path, lr_info::pfid, lr_info::sfid, lr_info::sname, SPECIAL_DIR, lr_info::spfid, lr_info::src, and lr_info::target_no.
Referenced by lr_replicate().
int lr_parse_line (void * priv, struct lr_info * info)
Definition at line 1138 of file lustre_rsync.c.
References changelog_rec_name(), changelog_rec_rename(), changelog_rec_sname(), changelog_rec_snamelen(), CLF_RENAME, changelog_rec::cr_flags, changelog_rec::cr_index, changelog_rec::cr_namelen, changelog_rec::cr_pfid, changelog_ext_rename::cr_sfid, changelog_ext_rename::cr_spfid, changelog_rec::cr_tfid, changelog_rec::cr_type, DFID, fid_is_zero(), lr_info::is_extended, llapi_changelog_free(), llapi_changelog_recv(), lr_info::name, lr_info::pfid, PFID, rec_count, lr_info::recno, lr_info::sfid, lr_info::sname, lr_info::spfid, strlcpy(), strnlen, lr_info::tfid, lr_info::type, and verbose.
Referenced by lr_replicate().
void lr_print_failure (struct lr_info * info, int rc)
Definition at line 1474 of file lustre_rsync.c.
References changelog_type2str(), lr_info::name, lr_info::pfid, lr_info::recno, lr_info::tfid, and lr_info::type.
Referenced by lr_replicate().
void lr_print_status (struct lr_info * info)
Definition at line 1449 of file lustre_rsync.c.
References lustre_rsync_status::ls_last_recno, lustre_rsync_status::ls_mdt_device, lustre_rsync_status::ls_num_targets, lustre_rsync_status::ls_registration, lustre_rsync_status::ls_source, lustre_rsync_status::ls_source_fs, lustre_rsync_status::ls_targets, noclear, noxattr, rsync, rsync_ver, statuslog, use_rsync, and verbose.
Referenced by lr_replicate().
int lr_read_log ()
Definition at line 1263 of file lustre_rsync.c.
References lr_grow_buf(), lustre_rsync_status::ls_last_recno, lustre_rsync_status::ls_mdt_device, lustre_rsync_status::ls_num_targets, lustre_rsync_status::ls_registration, lustre_rsync_status::ls_size, lustre_rsync_status::ls_source, lustre_rsync_status::ls_source_fs, lustre_rsync_status::ls_targets, lr_parent_child_list::pc_log, lr_parent_child_list::pc_next, size, statuslog, and strlcpy().
Referenced by main().
int lr_remove (struct lr_info * info)
Definition at line 861 of file lustre_rsync.c.
References lr_info::dest, DINFO, lr_debug(), lr_get_path(), lr_rm_recursive(), lr_rm_special(), lr_rmfile(), lustre_rsync_status::ls_num_targets, lustre_rsync_status::ls_targets, lr_info::name, lr_info::path, lr_info::pfid, and lr_info::target_no.
Referenced by lr_replicate().
int lr_remove_pc (const char * pfid, const char * tfid)
Definition at line 706 of file lustre_rsync.c.
References lr_parent_child_list::pc_next.
Referenced by lr_move().
int lr_replicate ()
Definition at line 1483 of file lustre_rsync.c.
References abort_on_err, CHANGELOG_FLAG_BLOCK, CHANGELOG_FLAG_JOBID, CL_CLOSE, CL_CREATE, CL_EXT, CL_HARDLINK, CL_LAYOUT, CL_MARK, CL_MKDIR, CL_MKNOD, CL_OPEN, CL_RENAME, CL_RMDIR, CL_SETATTR, CL_SOFTLINK, CL_TRUNC, CL_UNLINK, CL_XATTR, debug, DEBUG_ENTRY, DEBUG_EXIT, DEFAULT_MDT, lr_info::dest, dryrun, errors, lr_info::is_extended, llapi_changelog_fini(), llapi_changelog_start(), llapi_search_fsname(), lr_clear_cl(), lr_create(), lr_link(), lr_move(), LR_NAME_MAXLEN, lr_parse_line(), lr_print_failure(), lr_print_status(), lr_remove(), lr_setattr(), lr_setxattr(), lustre_rsync_status::ls_last_recno, lustre_rsync_status::ls_mdt_device, lustre_rsync_status::ls_num_targets, lustre_rsync_status::ls_source, lustre_rsync_status::ls_source_fs, lustre_rsync_status::ls_targets, lr_info::name, noxattr, lr_info::pfid, quit, rec_count, lr_info::sfid, lr_info::sname, SPECIAL_DIR, lr_info::spfid, lr_info::src, start, strlcpy(), lr_info::tfid, lr_info::type, verbose, lr_info::xlist, and lr_info::xsize.
Referenced by main().
int lr_rm_recursive (struct lr_info * info)
Definition at line 756 of file lustre_rsync.c.
References lr_info::cmd, and lr_info::dest.
Referenced by lr_remove().
int lr_rm_special (struct lr_info * info)
Definition at line 769 of file lustre_rsync.c.
References lr_info::dest, DINFO, lr_debug(), lr_rmfile(), lustre_rsync_status::ls_targets, SPECIAL_DIR, lr_info::target_no, and lr_info::tfid.
Referenced by lr_remove().
int lr_rmfile (struct lr_info * info)
Definition at line 742 of file lustre_rsync.c.
References CL_RMDIR, lr_info::dest, and lr_info::type.
Referenced by lr_remove(), and lr_rm_special().
int lr_rsync_data (struct lr_info * info)
Definition at line 285 of file lustre_rsync.c.
References cmd, lr_info::dest, DINFO, DTRACE, lr_debug(), lr_info::name, rsync, lr_info::src, and lr_info::tfid.
Referenced by lr_copy_data(), and lr_sync_data().
int lr_setattr (struct lr_info * info)
Definition at line 1076 of file lustre_rsync.c.
References lr_info::dest, DINFO, lr_copy_attr(), lr_debug(), lr_get_FID_PATH(), lr_get_path(), lr_sync_data(), lustre_rsync_status::ls_num_targets, lustre_rsync_status::ls_source, lustre_rsync_status::ls_targets, lr_info::path, lr_info::src, lr_info::target_no, and lr_info::tfid.
Referenced by lr_replicate().
int lr_setxattr (struct lr_info * info)
Definition at line 1108 of file lustre_rsync.c.
References lr_info::dest, DINFO, lr_copy_xattr(), lr_debug(), lr_get_FID_PATH(), lr_get_path(), lustre_rsync_status::ls_num_targets, lustre_rsync_status::ls_source, lustre_rsync_status::ls_targets, lr_info::path, lr_info::src, lr_info::target_no, and lr_info::tfid.
Referenced by lr_replicate().
int lr_sync_data (struct lr_info * info)
Definition at line 431 of file lustre_rsync.c.
References lr_copy_data(), lr_rsync_data(), and use_rsync.
Referenced by lr_mkfile(), and lr_setattr().
void lr_usage ()
Definition at line 231 of file lustre_rsync.c.
Referenced by main().
int lr_write_log ()
Definition at line 1219 of file lustre_rsync.c.
References lr_backup_log(), lustre_rsync_status::ls_size, lr_parent_child_list::pc_log, lr_parent_child_list::pc_next, size, and statuslog.
Referenced by lr_clear_cl().
int main (int argc, char * argv[])
Definition at line 1651 of file lustre_rsync.c.
References abort_on_err, debug, debug_log, dryrun, long_opts, lr_grow_buf(), lr_init_status(), lr_locate_rsync(), LR_NAME_MAXLEN, lr_read_log(), lr_replicate(), lr_usage(), lustre_rsync_status::ls_last_recno, lustre_rsync_status::ls_mdt_device, lustre_rsync_status::ls_num_targets, lustre_rsync_status::ls_registration, lustre_rsync_status::ls_size, lustre_rsync_status::ls_source, lustre_rsync_status::ls_targets, noclear, noxattr, obd_initialize(), optarg, optind, RSYNC, rsync_threshold, statuslog, strlcpy(), strnlen, termination_handler(), use_rsync, and verbose.
int obd_initialize (int argc, char ** argv)
Definition at line 2945 of file obd.c.
Referenced by lctl_main(), and main().
void termination_handler (int signum)
Definition at line 1644 of file lustre_rsync.c.
References quit.
Referenced by main().
Variable Documentation
int abort_on_err = 0
Definition at line 201 of file lustre_rsync.c.
Referenced by lr_replicate(), and main().
command_t cmdlist[0]
Definition at line 148 of file lustre_rsync.c.
int debug
Definition at line 192 of file lustre_rsync.c.
FILE* debug_log
Definition at line 207 of file lustre_rsync.c.
Referenced by lr_debug(), and main().
int dryrun
Definition at line 196 of file lustre_rsync.c.
Referenced by lr_clear_cl(), lr_replicate(), and main().
int errors
Definition at line 195 of file lustre_rsync.c.
Referenced by check_mountfsoptions(), lr_cascade_move(), lr_copy_xattr(), lr_replicate(), ping_client_fini(), and srpc_lnet_ev_handler().
int logbackedup
Definition at line 189 of file lustre_rsync.c.
Referenced by lr_backup_log().
struct option long_opts[]
Initial value:
 {
        {"source",      required_argument, 0, 's'},
        {"target",      required_argument, 0, 't'},
        {"mdt",         required_argument, 0, 'm'},
        {"user",        required_argument, 0, 'u'},
        {"statuslog",   required_argument, 0, 'l'},
        {"verbose",     no_argument,       0, 'v'},
        {"xattr",       required_argument, 0, 'x'},
        {"dry-run",     no_argument,       0, 'z'},
        {"cl-clear",    required_argument, 0, 'c'},
        {"use-rsync",   no_argument,       0, 'r'},
        {"rsync-threshold", required_argument, 0, 'y'},
        {"start-recno", required_argument, 0, 'n'},
        {"abort-on-err",no_argument,       0, 'a'},
        {"debug",       required_argument, 0, 'd'},
        {"debuglog",    required_argument, 0, 'D'},
        {0, 0, 0, 0}
}
Definition at line 210 of file lustre_rsync.c.
Referenced by main().
int noclear
Definition at line 191 of file lustre_rsync.c.
Referenced by lr_clear_cl(), lr_print_status(), and main().
int noxattr
Definition at line 190 of file lustre_rsync.c.
Referenced by lr_copy_xattr(), lr_print_status(), lr_replicate(), and main().
struct lr_parent_child_list* parents
Definition at line 205 of file lustre_rsync.c.
int quit
Definition at line 199 of file lustre_rsync.c.
Referenced by lov_update_statfs(), lr_replicate(), and termination_handler().
long long rec_count
Definition at line 194 of file lustre_rsync.c.
Referenced by lr_parse_line(), and lr_replicate().
char rsync[PATH_MAX]
Definition at line 203 of file lustre_rsync.c.
Referenced by lr_copy_data(), lr_locate_rsync(), lr_print_status(), and lr_rsync_data().
long long rsync_threshold = DEFAULT_RSYNC_THRESHOLD
Definition at line 198 of file lustre_rsync.c.
Referenced by lr_copy_data(), and main().
char rsync_ver[PATH_MAX]
Definition at line 204 of file lustre_rsync.c.
Referenced by lr_locate_rsync(), and lr_print_status().
struct lustre_rsync_status* status
Definition at line 187 of file lustre_rsync.c.
Referenced by cancel_lru_locks(), class_handle_ioctl(), class_obd_list(), ctx_init_parse_reply(), do_rmtacl(), init_kerberos_module(), init_null_module(), init_sk_module(), lnet_complete_msg_locked(), lstcon_sesnew_stat_reply(), main(), mdt_coordinator(), mdt_hsm_update_request_state(), mmap_tst8(), mydaemon(), obd_device_list_seq_show(), ptlrpc_check_set(), release_parent(), rsc_parse(), rsi_parse(), sfw_server_rpc_done(), test(), and wait_for_threads().
char* statuslog
Definition at line 188 of file lustre_rsync.c.
Referenced by lr_backup_log(), lr_print_status(), lr_read_log(), lr_write_log(), and main().
int use_rsync
Definition at line 197 of file lustre_rsync.c.
Referenced by lr_print_status(), lr_sync_data(), and main().
int verbose
Definition at line 193 of file lustre_rsync.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.