Lustre: lustre/utils/lustre_lfsck.c File Reference
lustre/utils/lustre_lfsck.c File Reference
#include <stdio.h>
#include <unistd.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <getopt.h>
#include <sys/ioctl.h>
#include <time.h>
#include "obdctl.h"
#include <lustre/lustre_lfsck_user.h>
#include <lnet/lnetctl.h>
#include <lustre_ioctl.h>
#include <libcfs/util/ioctl.h>
Data Structures
struct lfsck_type_name
Functions
static enum lfsck_type lfsck_name2type (const char *name)
static const char * lfsck_type2name (__u16 type)
static void usage_start (void)
static void usage_stop (void)
static void usage_query (void)
static int lfsck_pack_dev (struct obd_ioctl_data *data, char *device, char *arg)
int jt_lfsck_start (int argc, char **argv)
int jt_lfsck_stop (int argc, char **argv)
int jt_lfsck_query (int argc, char **argv)
Variables
static struct option long_opt_start []
static struct option long_opt_stop []
static struct option long_opt_query []
static struct lfsck_type_name lfsck_types_names []
Function Documentation
int jt_lfsck_query (int argc, char ** argv)
Definition at line 441 of file lustre_lfsck.c.
References buf, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf4, obd_ioctl_data::ioc_inllen1, l_ioctl(), lcfg_get_devname(), lfsck_name2type(), lfsck_pack_dev(), lfsck_status2name(), lfsck_type2name(), LFSCK_TYPE_BITS, LFSCK_TYPES_ALL, long_opt_query, LPF_WAIT, LS_MAX, lfsck_type_name::ltn_name, lfsck_query::lu_flags, lfsck_query::lu_mdts_count, lfsck_query::lu_osts_count, lfsck_query::lu_repaired, lfsck_query::lu_types, MAX_IOC_BUFLEN, MAX_OBD_NAME, name, OBD_DEV_ID, OBD_IOC_QUERY_LFSCK, obd_ioctl_pack(), obd_ioctl_unpack(), opt, optarg, rawbuf, and usage_query().
int jt_lfsck_start (int argc, char ** argv)
Definition at line 192 of file lustre_lfsck.c.
References buf, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf4, obd_ioctl_data::ioc_inllen1, l_ioctl(), lcfg_get_devname(), LFSCK_ASYNC_WIN_MAX, lfsck_name2type(), lfsck_pack_dev(), LFSCK_TYPES_ALL, LFSCK_TYPES_DEF, LFSCK_VERSION_V1, long_opt_start, LPF_ALL_TGT, LPF_BROADCAST, LPF_CREATE_MDTOBJ, LPF_CREATE_OSTOBJ, LPF_DRYRUN, LPF_FAILOUT, LPF_OST_ORPHAN, LPF_RESET, lfsck_start::ls_active, lfsck_start::ls_async_windows, lfsck_start::ls_flags, lfsck_start::ls_speed_limit, lfsck_start::ls_valid, lfsck_start::ls_version, LSV_ASYNC_WINDOWS, LSV_CREATE_MDTOBJ, LSV_CREATE_OSTOBJ, LSV_DRYRUN, LSV_ERROR_HANDLE, LSV_SPEED_LIMIT, lfsck_type_name::ltn_name, lfsck_type_name::ltn_type, MAX_IOC_BUFLEN, MAX_OBD_NAME, OBD_DEV_ID, OBD_IOC_START_LFSCK, obd_ioctl_pack(), obd_ioctl_unpack(), opt, optarg, optind, rawbuf, and usage_start().
int jt_lfsck_stop (int argc, char ** argv)
Definition at line 374 of file lustre_lfsck.c.
References buf, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf4, obd_ioctl_data::ioc_inllen1, l_ioctl(), lcfg_get_devname(), lfsck_pack_dev(), long_opt_stop, LPF_ALL_TGT, LPF_BROADCAST, lfsck_stop::ls_flags, MAX_IOC_BUFLEN, MAX_OBD_NAME, OBD_DEV_ID, OBD_IOC_STOP_LFSCK, obd_ioctl_pack(), opt, optarg, optind, rawbuf, and usage_stop().
static enum lfsck_type lfsck_name2type (const char * name) [static]
Definition at line 95 of file lustre_lfsck.c.
References lfsck_type_name::ltn_name, and lfsck_type_name::ltn_type.
Referenced by jt_lfsck_query(), and jt_lfsck_start().
static int lfsck_pack_dev (struct obd_ioctl_data * data, char * device, char * arg) [static]
Definition at line 175 of file lustre_lfsck.c.
References obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_inlbuf4, obd_ioctl_data::ioc_inllen4, MAX_OBD_NAME, and OBD_DEV_BY_DEVNAME.
Referenced by jt_lfsck_query(), jt_lfsck_start(), and jt_lfsck_stop().
static const char* lfsck_type2name (__u16 type) [static]
Definition at line 106 of file lustre_lfsck.c.
References lfsck_type_name::ltn_name, and lfsck_type_name::ltn_type.
Referenced by jt_lfsck_query().
static void usage_query (void) [static]
Definition at line 161 of file lustre_lfsck.c.
Referenced by jt_lfsck_query().
static void usage_start (void) [static]
Definition at line 118 of file lustre_lfsck.c.
References LFSCK_SPEED_NO_LIMIT.
Referenced by jt_lfsck_start().
static void usage_stop (void) [static]
Definition at line 149 of file lustre_lfsck.c.
Referenced by jt_lfsck_stop().
Variable Documentation
struct lfsck_type_name lfsck_types_names[] [static]
Initial value:
 {
        { "scrub",      LFSCK_TYPE_SCRUB },
        { "layout",     LFSCK_TYPE_LAYOUT },
        { "namespace",  LFSCK_TYPE_NAMESPACE },
        { "default",    LFSCK_TYPES_DEF },
        { "all",        LFSCK_TYPES_SUPPORTED },
        { NULL,         0 }
}
Definition at line 86 of file lustre_lfsck.c.
struct option long_opt_query[] [static]
Initial value:
 {
        {"device",      required_argument, 0, 'M'},
        {"type",        required_argument, 0, 't'},
        {"help",        no_argument,       0, 'h'},
        {"wait",        no_argument,       0, 'w'},
        {0,             0,                 0,  0 }
}
Definition at line 73 of file lustre_lfsck.c.
Referenced by jt_lfsck_query().
struct option long_opt_start[] [static]
Initial value:
 {
        {"device",              required_argument, 0, 'M'},
        {"all",                 no_argument,       0, 'A'},
        {"create_ostobj",       optional_argument, 0, 'c'},
        {"create_mdtobj",       optional_argument, 0, 'C'},
        {"error",               required_argument, 0, 'e'},
        {"help",                no_argument,       0, 'h'},
        {"dryrun",              optional_argument, 0, 'n'},
        {"orphan",              no_argument,       0, 'o'},
        {"reset",               no_argument,       0, 'r'},
        {"speed",               required_argument, 0, 's'},
        {"type",                required_argument, 0, 't'},
        {"window_size",         required_argument, 0, 'w'},
        {0,                     0,                 0,  0 }
}
Definition at line 50 of file lustre_lfsck.c.
Referenced by jt_lfsck_start().
struct option long_opt_stop[] [static]
Initial value:
 {
        {"device",      required_argument, 0, 'M'},
        {"all",         no_argument,       0, 'A'},
        {"help",        no_argument,       0, 'h'},
        {0,             0,                 0,  0 }
}
Definition at line 66 of file lustre_lfsck.c.
Referenced by jt_lfsck_stop().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.