Lustre: lustre/include/lustre_intent.h File Reference
lustre/include/lustre_intent.h File Reference
Data Structures
struct lookup_intent
Functions
static int it_disposition (const struct lookup_intent *it, int flag)
static void it_set_disposition (struct lookup_intent *it, int flag)
static void it_clear_disposition (struct lookup_intent *it, int flag)
Function Documentation
static void it_clear_disposition (struct lookup_intent * it, int flag) [inline, static]
Definition at line 67 of file lustre_intent.h.
References lookup_intent::it_disposition.
Referenced by ll_create_node(), ll_file_open(), and ll_release_openhandle().
static int it_disposition (const struct lookup_intent * it, int flag) [inline, static]
Definition at line 57 of file lustre_intent.h.
References lookup_intent::it_disposition.
Referenced by it_open_error(), ll_create_node(), ll_file_open(), ll_intent_file_open(), ll_intent_release(), ll_lease_open(), ll_lookup_it(), ll_lookup_it_finish(), ll_lookup_nd(), ll_release_openhandle(), ll_revalidate_it_finish(), ll_statahead_interpret(), lmv_intent_lookup(), mdc_finish_enqueue(), mdc_finish_intent_lock(), and mdc_set_open_replay_data().
static void it_set_disposition (struct lookup_intent * it, int flag) [inline, static]
Definition at line 62 of file lustre_intent.h.
References lookup_intent::it_disposition.
Referenced by mdc_finish_intent_lock().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.