Lustre: lustre/include/lustre_quota.h File Reference
lustre/include/lustre_quota.h File Reference
#include <linux/fs.h>
#include <linux/quota.h>
#include <linux/quotaops.h>
#include <dt_object.h>
#include <lustre_fid.h>
#include <lustre_dlm.h>
Data Structures
union lquota_rec
struct qmt_handlers
struct lquota_id_info
struct lquota_trans
Defines
#define MAX_IQ_TIME 604800
#define MAX_DQ_TIME 604800
#define QUOTA_METAPOOL_NAME "mdt="
#define QUOTA_DATAPOOL_NAME "ost="
#define QUOTA_MAX_TRANSIDS 4
#define QUOTA_FL_OVER_USRQUOTA 0x01
#define QUOTA_FL_OVER_GRPQUOTA 0x02
#define QUOTA_FL_SYNC 0x04
#define IS_LQUOTA_RES(res)
Functions
struct qsd_instance * qsd_init (const struct lu_env *, char *, struct dt_device *, struct proc_dir_entry *)
int qsd_prepare (const struct lu_env *, struct qsd_instance *)
int qsd_start (const struct lu_env *, struct qsd_instance *)
void qsd_fini (const struct lu_env *, struct qsd_instance *)
int qsd_op_begin (const struct lu_env *, struct qsd_instance *, struct lquota_trans *, struct lquota_id_info *, int *)
Enforce quota, it's called in the declaration of each operation.
void qsd_op_end (const struct lu_env *, struct qsd_instance *, struct lquota_trans *)
Post quota operation.
void qsd_op_adjust (const struct lu_env *, struct qsd_instance *, union lquota_id *, int)
Trigger pre-acquire/release if necessary.
int lquotactl_slv (const struct lu_env *, struct dt_device *, struct obd_quotactl *)
Variables
struct dt_index_features dt_quota_iusr_features
struct dt_index_features dt_quota_busr_features
struct dt_index_features dt_quota_igrp_features
struct dt_index_features dt_quota_bgrp_features
struct qmt_handlers qmt_hdls
Define Documentation
#define IS_LQUOTA_RES (res)
Value:
(res->lr_name.name[LUSTRE_RES_ID_SEQ_OFF] == FID_SEQ_QUOTA ||   \
         res->lr_name.name[LUSTRE_RES_ID_SEQ_OFF] == FID_SEQ_QUOTA_GLB)
Definition at line 227 of file lustre_quota.h.
Referenced by mdt_lvbo_fill(), mdt_lvbo_free(), mdt_lvbo_init(), mdt_lvbo_size(), and mdt_lvbo_update().
#define MAX_DQ_TIME 604800
Definition at line 47 of file lustre_quota.h.
Referenced by qmt_pool_prepare().
#define MAX_IQ_TIME 604800
Definition at line 43 of file lustre_quota.h.
Referenced by qmt_pool_prepare().
#define QUOTA_DATAPOOL_NAME "ost="
Definition at line 74 of file lustre_quota.h.
Referenced by mgs_write_log_quota(), and qsd_process_config().
#define QUOTA_FL_OVER_GRPQUOTA 0x02
Definition at line 224 of file lustre_quota.h.
Referenced by osd_declare_write_commit().
#define QUOTA_FL_OVER_USRQUOTA 0x01
Definition at line 223 of file lustre_quota.h.
Referenced by osd_declare_write_commit().
#define QUOTA_FL_SYNC 0x04
Definition at line 225 of file lustre_quota.h.
Referenced by osd_declare_write_commit(), and qsd_op_begin0().
#define QUOTA_MAX_TRANSIDS 4
Definition at line 214 of file lustre_quota.h.
Referenced by qsd_op_begin().
#define QUOTA_METAPOOL_NAME "mdt="
Definition at line 73 of file lustre_quota.h.
Referenced by mgs_write_log_quota(), and qsd_process_config().
Function Documentation
int lquotactl_slv (const struct lu_env * , struct dt_device * , struct obd_quotactl *)
Definition at line 158 of file lquota_lib.c.
References __u64, acct_obj_lookup(), CERROR, dt_device::dd_lu_dev, dt_object::do_index_ops, dt_object::do_lu, obd_dqblk::dqb_bhardlimit, obd_dqblk::dqb_curinodes, obd_dqblk::dqb_curspace, obd_dqblk::dqb_ihardlimit, obd_dqblk::dqb_valid, dt_key, dt_lookup(), ENTRY, GOTO, lu_device::ld_obd, lu_device::ld_site, lquota_info(), lu_site::ls_top_dev, lu_device_is_md(), lu_object_put(), obd_device::obd_name, Q_GETOQUOTA, obd_quotactl::qc_cmd, obd_quotactl::qc_dqblk, obd_quotactl::qc_id, obd_quotactl::qc_type, QIF_LIMITS, QIF_USAGE, quota_obj_lookup(), and RETURN.
Referenced by mdt_quotactl(), and ofd_quotactl().
void qsd_fini (const struct lu_env * , struct qsd_instance *)
Definition at line 474 of file qsd_lib.c.
References CDEBUG, D_QUOTA, dt_device::dd_lu_dev, dt_object::do_lu, ENTRY, EXIT, lu_device::ld_reference, list_del_init(), lprocfs_remove(), lu_device_put(), lu_object_put(), lu_ref_del(), lustre_deregister_lwp_item(), OBD_FREE_PTR, qsd_fsinfo::qfs_mutex, qsd_instance::qsd_dev, qsd_instance::qsd_exp, qsd_instance::qsd_exp_valid, qsd_instance::qsd_fsinfo, qsd_instance::qsd_link, qsd_instance::qsd_lock, qsd_instance::qsd_ns, qsd_instance::qsd_proc, qsd_put_fsinfo(), qsd_qtype_fini(), qsd_instance::qsd_root, qsd_stop_reint_thread(), qsd_stop_upd_thread(), qsd_instance::qsd_stopping, qsd_instance::qsd_svname, qsd_instance::qsd_type_array, RETURN_EXIT, and unlikely.
Referenced by osd_shutdown(), and qsd_init().
struct qsd_instance* qsd_init (const struct lu_env * , char * , struct dt_device * , struct proc_dir_entry *) [read]
Definition at line 557 of file qsd_lib.c.
References CERROR, dt_device::dd_lu_dev, ENTRY, EXIT, GOTO, INIT_LIST_HEAD, lu_device::ld_reference, LDD_F_SV_TYPE_MDT, LDD_F_SV_TYPE_OST, list_add_tail(), lprocfs_register(), lu_device_get(), lu_ref_add(), OBD_ALLOC_PTR, qsd_fsinfo::qfs_mutex, qsd_fsinfo::qfs_qsd_list, qsd_instance::qsd_adjust_list, qsd_instance::qsd_adjust_lock, qsd_instance::qsd_dev, QSD_DIR, qsd_fini(), qsd_instance::qsd_fsinfo, qsd_get_fsinfo(), qsd_info(), qsd_instance::qsd_link, qsd_instance::qsd_lock, qsd_instance::qsd_pool_id, qsd_instance::qsd_prepared, qsd_instance::qsd_proc, qsd_instance::qsd_started, qsd_instance::qsd_svname, qsd_instance::qsd_upd_list, qsd_instance::qsd_upd_thread, qsd_thread_info::qti_buf, RETURN, server_name2fsname(), server_name2index(), strlcpy(), SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, and thread_set_flags().
Referenced by osd_device_init0(), and osd_mount().
void qsd_op_adjust (const struct lu_env * env, struct qsd_instance * qsd, union lquota_id * qid, int qtype)
Trigger pre-acquire/release if necessary.
It's only used by ldiskfs osd so far. When unlink a file in ldiskfs, the quota accounting isn't updated when the transaction stopped. Instead, it'll be updated on the final iput, so qsd_op_adjust() will be called then (in osd_object_delete()) to trigger quota release if necessary.
Parameters:
env - the environment passed by the caller
qsd - is the qsd instance associated with the device in charge of the operation.
qid - is the lquota ID of the user/group for which to trigger quota space adjustment
qtype - is the quota type (USRQUOTA or GRPQUOTA)
Definition at line 1119 of file qsd_handler.c.
References CERROR, ENTRY, EXIT, LASSERT, LPU64, lqe_locate(), lqe_putref(), lqe_read_lock(), lqe_read_unlock(), lquota_id::qid_uid, qsd_qtype_info::qqi_acct_obj, qsd_qtype_info::qqi_site, qsd_adjust(), qsd_adjust_needed(), qsd_instance::qsd_lock, qsd_refresh_usage(), qsd_instance::qsd_started, qsd_instance::qsd_svname, qsd_instance::qsd_type_array, qsd_type_enabled(), RETURN_EXIT, and unlikely.
Referenced by osd_object_delete().
int qsd_op_begin (const struct lu_env * env, struct qsd_instance * qsd, struct lquota_trans * trans, struct lquota_id_info * qi, int * flags)
Enforce quota, it's called in the declaration of each operation.
qsd_op_end() will then be called later once all the operations have been completed in order to release/adjust the quota space.
Parameters:
env - the environment passed by the caller
qsd - is the qsd instance associated with the device in charge of the operation.
trans - is the quota transaction information
qi - qid & space required by current operation
flags - if the operation is write, return caller no user/group and sync commit flags
Return values:
0 - success
-EDQUOT - out of quota
-EINPROGRESS - inform client to retry write
-ve - other appropriate errors
Definition at line 825 of file qsd_handler.c.
References CERROR, ENTRY, LASSERT, LASSERTF, lquota_id_info::lqi_id, lquota_id_info::lqi_is_blk, lquota_id_info::lqi_space, lquota_id_info::lqi_type, lquota_trans::lqt_id_cnt, lquota_trans::lqt_ids, qid_equal(), lquota_id::qid_uid, qsd_instance::qsd_acct_failed, qsd_instance::qsd_is_md, qsd_instance::qsd_lock, qsd_op_begin0(), qsd_instance::qsd_started, qsd_instance::qsd_svname, qsd_instance::qsd_type_array, qsd_type_enabled(), QUOTA_MAX_TRANSIDS, RETURN, and unlikely.
Referenced by osd_declare_qid(), osd_declare_quota(), and qsd_transfer().
void qsd_op_end (const struct lu_env * env, struct qsd_instance * qsd, struct lquota_trans * trans)
Post quota operation.
It's called after each operation transaction stopped.
Parameters:
env - the environment passed by the caller
qsd - is the qsd instance associated with device which is handling the operation.
qids - all qids information attached in the transaction handle
count - is the number of qid entries in the qids array.
Return values:
0 - success
-ve - failure
Definition at line 1069 of file qsd_handler.c.
References ENTRY, EXIT, LASSERT, lquota_id_info::lqi_qentry, lquota_id_info::lqi_type, lquota_trans::lqt_id_cnt, lquota_trans::lqt_ids, qsd_instance::qsd_lock, qsd_op_end0(), qsd_instance::qsd_started, qsd_instance::qsd_type_array, RETURN_EXIT, and unlikely.
Referenced by osd_trans_commit_cb(), and osd_trans_stop().
int qsd_prepare (const struct lu_env * , struct qsd_instance *)
Definition at line 656 of file qsd_lib.c.
References CERROR, dt_device::dd_lu_dev, ENTRY, LCONSOLE_ERROR, lu_device::ld_site, lquota_disk_dir_find_create(), LQUOTA_LEAST_QUNIT, LQUOTA_RES_DT, LQUOTA_RES_MD, lu_site::ls_top_dev, lu_device_is_md(), lustre_register_lwp_item(), MTI_NAME_MAXLEN, qsd_instance::qsd_acct_failed, qsd_conn_callback(), qsd_instance::qsd_dev, QSD_DIR, qsd_instance::qsd_exp, qsd_info(), qsd_instance::qsd_is_md, qsd_instance::qsd_lock, qsd_instance::qsd_prepared, qsd_qtype_init(), qsd_instance::qsd_root, qsd_start_reint_thread(), qsd_start_upd_thread(), qsd_instance::qsd_svname, qsd_instance::qsd_sync_threshold, qsd_instance::qsd_type_array, qsd_type_enabled(), qsd_thread_info::qti_buf, QTYPE_NAME, RETURN, tgt_name2lwp_name(), and unlikely.
Referenced by osd_prepare().
int qsd_start (const struct lu_env * , struct qsd_instance *)
Definition at line 768 of file qsd_lib.c.
References CERROR, ENTRY, qsd_qtype_info::qqi_reint_thread, qsd_instance::qsd_lock, qsd_instance::qsd_prepared, qsd_instance::qsd_started, qsd_instance::qsd_svname, qsd_instance::qsd_type_array, RETURN, ptlrpc_thread::t_ctl_waitq, and unlikely.
Referenced by osd_recovery_complete().
Variable Documentation
struct dt_index_features dt_quota_bgrp_features
struct dt_index_features dt_quota_busr_features
struct dt_index_features dt_quota_igrp_features
struct dt_index_features dt_quota_iusr_features
struct qmt_handlers qmt_hdls
Definition at line 680 of file qmt_handler.c.
Referenced by mdt_intent_opc(), mdt_lvbo_fill(), mdt_lvbo_free(), mdt_lvbo_init(), mdt_lvbo_size(), mdt_lvbo_update(), mdt_quota_dqacq(), and mdt_quotactl().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.