Lustre: lustre/utils/lustre_cfg.c File Reference
lustre/utils/lustre_cfg.c File Reference
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/stat.h>
#include <unistd.h>
#include <stdio.h>
#include <stdarg.h>
#include <ctype.h>
#include <libcfs/util/param.h>
#include <libcfs/util/parser.h>
#include <lnet/nidstr.h>
#include <lustre_cfg.h>
#include <lustre_ioctl.h>
#include <lustre/lustre_idl.h>
#include <lustre_ver.h>
#include <sys/un.h>
#include <time.h>
#include <sys/time.h>
#include "obdctl.h"
#include <lnet/lnetctl.h>
Data Structures
struct param_opts
Enumerations
enum parameter_operation { LIST_PARAM, GET_PARAM, SET_PARAM }
The application lctl can perform three operations for lustre tunables.
Functions
int lcfg_set_devname (char *name)
char * lcfg_get_devname (void)
int jt_lcfg_device (int argc, char **argv)
int jt_lcfg_attach (int argc, char **argv)
int jt_lcfg_setup (int argc, char **argv)
int jt_obd_detach (int argc, char **argv)
int jt_obd_cleanup (int argc, char **argv)
static int do_add_uuid (char *func, char *uuid, lnet_nid_t nid)
int jt_lcfg_add_uuid (int argc, char **argv)
int jt_lcfg_del_uuid (int argc, char **argv)
int jt_lcfg_del_mount_option (int argc, char **argv)
int jt_lcfg_set_timeout (int argc, char **argv)
int jt_lcfg_add_conn (int argc, char **argv)
int jt_lcfg_del_conn (int argc, char **argv)
int jt_lcfg_param (int argc, char **argv)
static int jt_lcfg_mgsparam2 (int argc, char **argv, struct param_opts *popt)
int jt_lcfg_mgsparam (int argc, char **argv)
static char * display_name (const char *filename, struct stat *st, struct param_opts *popt)
Display a parameter path in the same format as sysctl.
static char * strnchr (const char *p, char c, size_t n)
static int clean_path (struct param_opts *popt, char *path)
Turns a lctl parameter string into a procfs/sysfs subdirectory path pattern.
static int read_param (const char *path, const char *param_name, struct param_opts *popt)
Read the value of parameter.
static int write_param (const char *path, const char *param_name, struct param_opts *popt, const char *value)
Set a parameter to a specified value.
static int param_display (struct param_opts *popt, char *pattern, char *value, enum parameter_operation mode)
Perform a read, write or just a listing of a parameter.
static int listparam_cmdline (int argc, char **argv, struct param_opts *popt)
int jt_lcfg_listparam (int argc, char **argv)
static int getparam_cmdline (int argc, char **argv, struct param_opts *popt)
int jt_lcfg_getparam (int argc, char **argv)
int jt_nodemap_info (int argc, char **argv)
Output information about nodemaps.
static int setparam_cmdline (int argc, char **argv, struct param_opts *popt)
int jt_lcfg_setparam (int argc, char **argv)
Variables
static char * lcfg_devname
char * parameter_opname []
Enumeration Type Documentation
enum parameter_operation
The application lctl can perform three operations for lustre tunables.
This enum defines those three operations which are
1) LIST_PARAM - list available tunables 2) GET_PARAM - report the current setting of a tunable 3) SET_PARAM - set the tunable to a new value
Enumerator:
LIST_PARAM
GET_PARAM
SET_PARAM
Definition at line 872 of file lustre_cfg.c.
Function Documentation
static int clean_path (struct param_opts * popt, char * path) [static]
Turns a lctl parameter string into a procfs/sysfs subdirectory path pattern.
Parameters:
[in] popt Used to control parameter usage. For this function it is used to see if the path has a added suffix.
[in,out] path lctl parameter string that is turned into the subdirectory path pattern that is used to search the procfs/sysfs tree.
Return values:
-errno on error.
Definition at line 768 of file lustre_cfg.c.
References libcfs_nid2str(), libcfs_str2nid(), LNET_NID_ANY, and param_opts::po_show_type.
Referenced by jt_lcfg_getparam(), jt_lcfg_listparam(), jt_lcfg_setparam(), and param_display().
static char* display_name (const char * filename, struct stat * st, struct param_opts * popt) [static]
Display a parameter path in the same format as sysctl.
E.g. obdfilter.lustre-OST0000.stats
Parameters:
[in] filename file name of the parameter
[in] st parameter file stats
[in] popt set/get param options
Return values:
allocated pointer containing modified filename
Definition at line 691 of file lustre_cfg.c.
References param_opts::po_show_type.
Referenced by param_display().
static int do_add_uuid (char * func, char * uuid, lnet_nid_t nid) [static]
Definition at line 277 of file lustre_cfg.c.
References LCFG_ADD_UUID, lcfg_devname, lcfg_ioctl(), lustre_cfg::lcfg_nid, libcfs_nid2str(), lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), and OBD_DEV_ID.
Referenced by jt_lcfg_add_uuid().
static int getparam_cmdline (int argc, char ** argv, struct param_opts * popt) [static]
Definition at line 1263 of file lustre_cfg.c.
References optind, param_opts::po_only_path, param_opts::po_recursive, param_opts::po_show_path, and param_opts::po_show_type.
Referenced by jt_lcfg_getparam().
int jt_lcfg_add_conn (int argc, char ** argv)
Definition at line 415 of file lustre_cfg.c.
References CMD_HELP, jt_cmdname(), LCFG_ADD_CONN, lcfg_devname, lcfg_ioctl(), lustre_cfg::lcfg_num, lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), and OBD_DEV_ID.
int jt_lcfg_add_uuid (int argc, char ** argv)
Definition at line 308 of file lustre_cfg.c.
References CMD_HELP, do_add_uuid(), libcfs_str2nid(), and LNET_NID_ANY.
int jt_lcfg_attach (int argc, char ** argv)
Definition at line 121 of file lustre_cfg.c.
References CMD_HELP, jt_cmdname(), LCFG_ATTACH, lcfg_ioctl(), lcfg_set_devname(), lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), and OBD_DEV_ID.
int jt_lcfg_del_conn (int argc, char ** argv)
Definition at line 457 of file lustre_cfg.c.
References CMD_HELP, jt_cmdname(), LCFG_DEL_MOUNTOPT, lcfg_devname, lcfg_ioctl(), lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), and OBD_DEV_ID.
int jt_lcfg_del_mount_option (int argc, char ** argv)
Definition at line 355 of file lustre_cfg.c.
References CMD_HELP, jt_cmdname(), LCFG_DEL_MOUNTOPT, lcfg_devname, lcfg_ioctl(), lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), and OBD_DEV_ID.
int jt_lcfg_del_uuid (int argc, char ** argv)
Definition at line 325 of file lustre_cfg.c.
References LCFG_DEL_UUID, lcfg_devname, lcfg_ioctl(), lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), and OBD_DEV_ID.
int jt_lcfg_device (int argc, char ** argv)
Definition at line 116 of file lustre_cfg.c.
References jt_obd_device().
int jt_lcfg_getparam (int argc, char ** argv)
Definition at line 1291 of file lustre_cfg.c.
References clean_path(), CMD_HELP, GET_PARAM, getparam_cmdline(), jt_cmdname(), LIST_PARAM, param_display(), path, and param_opts::po_only_path.
int jt_lcfg_listparam (int argc, char ** argv)
Definition at line 1225 of file lustre_cfg.c.
References clean_path(), CMD_HELP, jt_cmdname(), LIST_PARAM, listparam_cmdline(), param_display(), and path.
int jt_lcfg_mgsparam (int argc, char ** argv)
Definition at line 612 of file lustre_cfg.c.
References buf, CMD_HELP, jt_cmdname(), lcfg_mgs_ioctl(), LCFG_PARAM, lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), OBD_DEV_ID, and optind.
static int jt_lcfg_mgsparam2 (int argc, char ** argv, struct param_opts * popt) [static]
Definition at line 537 of file lustre_cfg.c.
References buf, CMD_HELP, jt_cmdname(), lcfg_mgs_ioctl(), LCFG_SET_PARAM, lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), OBD_DEV_ID, optind, and param_opts::po_delete.
Referenced by jt_lcfg_setparam().
int jt_lcfg_param (int argc, char ** argv)
Definition at line 494 of file lustre_cfg.c.
References CMD_HELP, jt_cmdname(), lcfg_ioctl(), LCFG_PARAM, lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), LUSTRE_CFG_MAX_BUFCOUNT, lustre_cfg_new(), and OBD_DEV_ID.
int jt_lcfg_set_timeout (int argc, char ** argv)
Definition at line 383 of file lustre_cfg.c.
References CMD_HELP, jt_cmdname(), lcfg_devname, lcfg_ioctl(), lustre_cfg::lcfg_num, LCFG_SET_TIMEOUT, lustre_cfg_bufs_reset(), lustre_cfg_free(), lustre_cfg_new(), and OBD_DEV_ID.
int jt_lcfg_setparam (int argc, char ** argv)
Definition at line 1401 of file lustre_cfg.c.
References clean_path(), CMD_HELP, jt_cmdname(), jt_lcfg_mgsparam2(), param_display(), path, param_opts::po_params2, SET_PARAM, and setparam_cmdline().
int jt_lcfg_setup (int argc, char ** argv)
Definition at line 153 of file lustre_cfg.c.
References CMD_HELP, jt_cmdname(), lcfg_devname, lcfg_ioctl(), LCFG_SETUP, lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), and OBD_DEV_ID.
int jt_nodemap_info (int argc, char ** argv)
Output information about nodemaps.
Parameters:
argc number of args
argv[] variable string arguments
[list|nodemap_name|all] list will list all nodemaps (default). Specifying a nodemap_name will display info about that specific nodemap. all will display info for all nodemaps.
Return values:
0 on success
Definition at line 1339 of file lustre_cfg.c.
References LIST_PARAM, param_display(), param_opts::po_only_dir, param_opts::po_only_path, and param_opts::po_show_path.
int jt_obd_cleanup (int argc, char ** argv)
Definition at line 222 of file lustre_cfg.c.
References CMD_HELP, failover, jt_cmdname(), LCFG_CLEANUP, lcfg_devname, lcfg_ioctl(), lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), and OBD_DEV_ID.
int jt_obd_detach (int argc, char ** argv)
Definition at line 190 of file lustre_cfg.c.
References CMD_HELP, jt_cmdname(), LCFG_DETACH, lcfg_devname, lcfg_ioctl(), lustre_cfg_bufs_reset(), lustre_cfg_free(), lustre_cfg_new(), and OBD_DEV_ID.
char* lcfg_get_devname (void)
Definition at line 111 of file lustre_cfg.c.
References lcfg_devname.
Referenced by jt_changelog_deregister(), jt_changelog_register(), jt_lfsck_query(), jt_lfsck_start(), jt_lfsck_stop(), and jt_obd_device().
int lcfg_set_devname (char * name)
Definition at line 78 of file lustre_cfg.c.
References lcfg_devname.
Referenced by do_device(), do_disconnect(), and jt_lcfg_attach().
static int listparam_cmdline (int argc, char ** argv, struct param_opts * popt) [static]
Definition at line 1199 of file lustre_cfg.c.
References optind, param_opts::po_only_dir, param_opts::po_only_path, param_opts::po_recursive, param_opts::po_show_path, and param_opts::po_show_type.
Referenced by jt_lcfg_listparam().
static int param_display (struct param_opts * popt, char * pattern, char * value, enum parameter_operation mode) [static]
Perform a read, write or just a listing of a parameter.
Parameters:
[in] popt list,set,get parameter options
[in] pattern search filter for the path of the parameter
[in] value value to set the parameter if write operation
[in] mode what operation to perform with the parameter
Return values:
number of bytes written on success.
-errno on error and prints error message.
For the upstream client the parameter files locations are split between under both /sys/kernel/debug/lustre and /sys/fs/lustre. The parameter files containing small amounts of data, less than a page in size, are located under /sys/fs/lustre and in the case of large parameter data files, think stats for example, are located in the debugfs tree. Since the files are split across two trees the directories are often duplicated which means these directories are listed twice which leads to duplicate output to the user. To avoid scanning a directory twice we have to cache any directory and check if a search has been requested twice.
Definition at line 1030 of file lustre_cfg.c.
References cfs_free_param_data(), cfs_get_param_paths(), clean_path(), display_name(), GET_PARAM, LIST_PARAM, parameter_opname, param_opts::po_only_dir, param_opts::po_recursive, param_opts::po_show_path, read_param(), SET_PARAM, and write_param().
Referenced by jt_lcfg_getparam(), jt_lcfg_listparam(), jt_lcfg_setparam(), and jt_nodemap_info().
static int read_param (const char * path, const char * param_name, struct param_opts * popt) [static]
Read the value of parameter.
Parameters:
[in] path full path to the parameter
[in] param_name lctl parameter format of the parameter path
[in] popt set/get param options
Return values:
0 on success.
-errno on error.
Definition at line 896 of file lustre_cfg.c.
References buf, page_size, param_opts::po_show_path, and strnchr().
Referenced by param_display().
static int setparam_cmdline (int argc, char ** argv, struct param_opts * popt) [static]
Definition at line 1372 of file lustre_cfg.c.
References optind, param_opts::po_delete, param_opts::po_only_path, param_opts::po_params2, param_opts::po_recursive, param_opts::po_show_path, and param_opts::po_show_type.
Referenced by jt_lcfg_setparam().
static char* strnchr (const char * p, char c, size_t n) [static]
Definition at line 742 of file lustre_cfg.c.
Referenced by read_param().
static int write_param (const char * path, const char * param_name, struct param_opts * popt, const char * value) [static]
Set a parameter to a specified value.
Parameters:
[in] path full path to the parameter
[in] param_name lctl parameter format of the parameter path
[in] popt set/get param options
[in] value value to set the parameter to
Return values:
number of bytes written on success.
-errno on error.
Definition at line 981 of file lustre_cfg.c.
References param_opts::po_show_path.
Referenced by param_display().
Variable Documentation
char* lcfg_devname [static]
Definition at line 76 of file lustre_cfg.c.
Referenced by do_add_uuid(), jt_lcfg_add_conn(), jt_lcfg_del_conn(), jt_lcfg_del_mount_option(), jt_lcfg_del_uuid(), jt_lcfg_set_timeout(), jt_lcfg_setup(), jt_obd_cleanup(), jt_obd_detach(), lcfg_get_devname(), and lcfg_set_devname().
char* parameter_opname[]
Initial value:
 {
        [LIST_PARAM] = "list_param",
        [GET_PARAM] = "get_param",
        [SET_PARAM] = "set_param",
}
Definition at line 878 of file lustre_cfg.c.
Referenced by param_display().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.