Lustre: lustre/include/lustre_obdo.h File Reference
lustre/include/lustre_obdo.h File Reference
#include <lustre/lustre_idl.h>
Functions
void dump_obdo (struct obdo *oa)
Dumper for struct obdo.
static void lustre_set_wire_obdo (const struct obd_connect_data *ocd, struct obdo *wobdo, const struct obdo *lobdo)
Create an obdo to send over the wire.
static void lustre_get_wire_obdo (const struct obd_connect_data *ocd, struct obdo *lobdo, const struct obdo *wobdo)
Create a local obdo from a wire based odbo.
Function Documentation
void dump_obdo (struct obdo * oa)
Dumper for struct obdo.
Definition at line 2295 of file pack_generic.c.
References CDEBUG, lustre_handle::cookie, D_RPCTRACE, DOSTID, LPD64, LPX64, obdo::o_atime, obdo::o_blksize, obdo::o_blocks, obdo::o_ctime, obdo::o_flags, obdo::o_gid, obdo::o_gid_h, obdo::o_grant, obdo::o_handle, obdo::o_ioepoch, obdo::o_mode, obdo::o_mtime, obdo::o_nlink, obdo::o_oi, obdo::o_parent_oid, obdo::o_parent_seq, obdo::o_parent_ver, obdo::o_size, obdo::o_stripe_idx, obdo::o_uid, obdo::o_uid_h, obdo::o_valid, OBD_MD_FLATIME, OBD_MD_FLBLKSZ, OBD_MD_FLBLOCKS, OBD_MD_FLCKSUM, OBD_MD_FLCTIME, OBD_MD_FLEPOCH, OBD_MD_FLFID, OBD_MD_FLFLAGS, OBD_MD_FLGENER, OBD_MD_FLGID, OBD_MD_FLGRANT, OBD_MD_FLHANDLE, OBD_MD_FLID, OBD_MD_FLMODE, OBD_MD_FLMTIME, OBD_MD_FLNLINK, OBD_MD_FLSIZE, OBD_MD_FLTYPE, OBD_MD_FLUID, and POSTID.
static void lustre_get_wire_obdo (const struct obd_connect_data * ocd, struct obdo * lobdo, const struct obdo * wobdo) [inline, static]
Create a local obdo from a wire based odbo.
Definition at line 69 of file lustre_obdo.h.
References lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, fid_seq_is_echo(), obdo::o_flags, obdo::o_oi, obdo::o_valid, OBD_CONNECT_FID, OBD_FL_LOCAL_MASK, OBD_MD_FLFLAGS, obd_connect_data::ocd_connect_flags, ost_id::oi, ost_id::oi_fid, and unlikely.
Referenced by osc_brw_fini_request(), osc_create(), osc_data_version_interpret(), osc_getattr(), osc_setattr(), osc_setattr_interpret(), osp_get_attr_from_reply(), out_attr_set(), out_create(), update_recovery_attr_set(), and update_recovery_create().
static void lustre_set_wire_obdo (const struct obd_connect_data * ocd, struct obdo * wobdo, const struct obdo * lobdo) [inline, static]
Create an obdo to send over the wire.
Definition at line 48 of file lustre_obdo.h.
References fid_oid(), fid_seq_is_echo(), obdo::o_flags, obdo::o_oi, OBD_CONNECT_FID, OBD_FL_LOCAL_MASK, obd_connect_data::ocd_connect_flags, ost_id::oi, ost_id::oi_fid, ostid_seq(), and unlikely.
Referenced by osc_brw_prep_request(), osc_create(), osc_destroy(), osc_io_data_version_start(), osc_ladvise_base(), osc_pack_req_body(), osc_punch_base(), osc_sync_base(), osp_object_truncate(), out_attr_get(), out_attr_set_pack(), out_create_pack(), update_records_attr_set_pack(), and update_records_create_pack().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.