Lustre: lustre/include/lustre_nodemap.h File Reference
lustre/include/lustre_nodemap.h File Reference
#include <lustre/lustre_idl.h>
Data Structures
struct nodemap_pde
struct lu_nodemap
The nodemap id 0 will be the default nodemap.
struct nm_config_file
Defines
#define LUSTRE_NODEMAP_NAME "nodemap"
#define LUSTRE_NODEMAP_DEFAULT_ID 0
Enumerations
enum nodemap_id_type { NODEMAP_UID, NODEMAP_GID }
enums containing the types of ids contained in a nodemap kept so other modules (mgs, mdt, etc) can define the type of search easily
enum nodemap_tree_type { NODEMAP_FS_TO_CLIENT, NODEMAP_CLIENT_TO_FS }
Functions
void nodemap_activate (const bool value)
activate nodemap functions
int nodemap_add (const char *nodemap_name)
Add a nodemap.
int nodemap_del (const char *nodemap_name)
Delete a nodemap.
int nodemap_add_member (lnet_nid_t nid, struct obd_export *exp)
add a member to a nodemap
void nodemap_del_member (struct obd_export *exp)
delete a member from a nodemap
int nodemap_parse_range (const char *range_string, lnet_nid_t range[2])
parse a nodemap range string into two nids
int nodemap_parse_idmap (char *idmap_string, __u32 idmap[2])
parse a string containing an id map of form "client_id:filesystem_id" into an array of __u32 * for use in mapping functions
int nodemap_add_range (const char *name, const lnet_nid_t nid[2])
int nodemap_del_range (const char *name, const lnet_nid_t nid[2])
delete a range
int nodemap_set_allow_root (const char *name, bool allow_root)
update flag to turn on or off nodemap functions
int nodemap_set_trust_client_ids (const char *name, bool trust_client_ids)
updated trust_client_ids flag for nodemap
int nodemap_set_squash_uid (const char *name, uid_t uid)
update the squash_uid for a nodemap
int nodemap_set_squash_gid (const char *name, gid_t gid)
Update the squash_gid for a nodemap.
bool nodemap_can_setquota (const struct lu_nodemap *nodemap)
Returns true if this nodemap has root user access.
int nodemap_add_idmap (const char *name, enum nodemap_id_type id_type, const __u32 map[2])
int nodemap_del_idmap (const char *name, enum nodemap_id_type id_type, const __u32 map[2])
delete idmap from proper nodemap tree
__u32 nodemap_map_id (struct lu_nodemap *nodemap, enum nodemap_id_type id_type, enum nodemap_tree_type tree_type, __u32 id)
mapping function for nodemap idmaps
ssize_t nodemap_map_acl (struct lu_nodemap *nodemap, void *buf, size_t size, enum nodemap_tree_type tree_type)
Map posix ACL entries according to the nodemap membership.
void nodemap_test_nid (lnet_nid_t nid, char *name_buf, size_t name_len)
Returns the nodemap classification for a given nid into an ioctl buffer.
__u32 nodemap_test_id (lnet_nid_t nid, enum nodemap_id_type idtype, __u32 client_id)
Returns the id mapping for a given nid/id pair.
struct nm_config_file * nm_config_file_register (const struct lu_env *env, struct dt_object *obj)
Register a dt_object representing the config index file.
void nm_config_file_deregister (const struct lu_env *env, struct nm_config_file *ncf)
Deregister a nm_config_file.
Define Documentation
#define LUSTRE_NODEMAP_DEFAULT_ID 0
Definition at line 34 of file lustre_nodemap.h.
Referenced by nodemap_create(), and nodemap_process_keyrec().
#define LUSTRE_NODEMAP_NAME "nodemap"
Definition at line 32 of file lustre_nodemap.h.
Referenced by mgs_fs_setup(), and nodemap_procfs_init().
Enumeration Type Documentation
enum nodemap_id_type
enums containing the types of ids contained in a nodemap kept so other modules (mgs, mdt, etc) can define the type of search easily
Enumerator:
NODEMAP_UID
NODEMAP_GID
Definition at line 41 of file lustre_nodemap.h.
enum nodemap_tree_type
Enumerator:
NODEMAP_FS_TO_CLIENT
NODEMAP_CLIENT_TO_FS
Definition at line 46 of file lustre_nodemap.h.
Function Documentation
void nm_config_file_deregister (const struct lu_env * env, struct nm_config_file * ncf)
Deregister a nm_config_file.
Should be called by targets during cleanup.
Parameters:
ncf config file to deregister
Definition at line 782 of file nodemap_storage.c.
References dt_object::do_lu, ENTRY, EXIT, list_del(), lu_object_put(), nm_config_file::ncf_list, nm_config_file::ncf_obj, and OBD_FREE_PTR.
Referenced by mgs_fs_cleanup(), and mgs_fs_setup().
struct nm_config_file* nm_config_file_register (const struct lu_env * env, struct dt_object * obj) [read]
Register a dt_object representing the config index file.
This should be called by targets in order to load the nodemap configuration from disk. The dt_object should be created with local_index_find_or_create and the index features should be enabled with do_index_try.
Parameters:
obj dt_object returned by local_index_find_or_create
Return values:
on success: nm_config_file handle for later deregistration
-ENOMEM memory allocation failure
-ENOENT error loading nodemap config
-EINVAL error loading nodemap config
Definition at line 740 of file nodemap_storage.c.
References ENTRY, list_add(), list_del(), list_empty(), nm_config_file::ncf_list, nm_config_file::ncf_obj, nodemap_load_entries(), OBD_ALLOC_PTR, OBD_FREE_PTR, and RETURN.
Referenced by mgs_fs_setup().
void nodemap_activate (const bool value)
activate nodemap functions
Parameters:
value 1 for on, 0 for off
Definition at line 1088 of file nodemap_handler.c.
References active_config_lock, nm_member_revoke_all(), nodemap_config::nmc_nodemap_is_active, nodemap_active, and nodemap_idx_nodemap_activate().
Referenced by mgs_iocontrol_nodemap(), and nodemap_active_seq_write().
int nodemap_add (const char * nodemap_name)
Add a nodemap.
Parameters:
name name of nodemap
Return values:
0 success
-EINVAL invalid nodemap name
-EEXIST nodemap already exists
-ENOMEM cannot allocate memory for nodemap
Definition at line 1002 of file nodemap_handler.c.
References active_config_lock, lprocfs_nodemap_register(), nodemap_create(), nodemap_idx_nodemap_add(), and nodemap_putref().
Referenced by lprocfs_add_nodemap_seq_write(), and mgs_nodemap_cmd().
int nodemap_add_idmap (const char * name, enum nodemap_id_type id_type, const __u32 map[2])
Definition at line 416 of file nodemap_handler.c.
References active_config_lock, GOTO, is_default_nodemap(), nodemap_add_idmap_helper(), nodemap_idx_idmap_add(), nodemap_lookup(), and nodemap_putref().
Referenced by lprocfs_add_nodemap_idmap_seq_write(), and mgs_nodemap_cmd().
int nodemap_add_member (lnet_nid_t nid, struct obd_export * exp)
add a member to a nodemap
Parameters:
nid nid to add to the members
exp obd_export structure for the connection that is being added
Return values:
-EINVAL export is NULL
-EEXIST export is already member of a nodemap
Definition at line 351 of file nodemap_handler.c.
References active_config_lock, nm_member_add(), nodemap_config::nmc_range_tree_lock, nodemap_classify_nid(), and nodemap_putref().
Referenced by mdt_obd_connect(), mdt_obd_reconnect(), ofd_obd_connect(), and ofd_obd_reconnect().
int nodemap_add_range (const char * name, const lnet_nid_t nid[2])
Definition at line 684 of file nodemap_handler.c.
References active_config_lock, GOTO, is_default_nodemap(), nodemap_add_range_helper(), nodemap_lookup(), and nodemap_putref().
Referenced by lprocfs_add_nodemap_range_seq_write(), and mgs_nodemap_cmd().
bool nodemap_can_setquota (const struct lu_nodemap * nodemap)
Returns true if this nodemap has root user access.
Always returns true if nodemaps are not active.
Parameters:
nodemap nodemap to check access for
Definition at line 987 of file nodemap_handler.c.
References lu_nodemap::nmf_allow_root_access, and nodemap_active.
Referenced by mdt_quotactl().
int nodemap_del (const char * nodemap_name)
Delete a nodemap.
Parameters:
name name of nodemmap
Return values:
0 success
-EINVAL invalid input
-ENOENT no existing nodemap
Definition at line 1033 of file nodemap_handler.c.
References active_config_lock, cfs_hash_del_key(), DEFAULT_NODEMAP, GOTO, list_for_each_entry_safe, lprocfs_nodemap_remove(), lu_nodemap::nm_pde_data, lu_nodemap::nm_ranges, nodemap_config::nmc_nodemap_hash, nodemap_config::nmc_range_tree, nodemap_config::nmc_range_tree_lock, nodemap_idx_nodemap_del(), nodemap_idx_range_del(), nodemap_putref(), range_delete(), RETURN, and lu_nid_range::rn_list.
Referenced by lprocfs_del_nodemap_seq_write(), and mgs_nodemap_cmd().
int nodemap_del_idmap (const char * name, enum nodemap_id_type id_type, const __u32 map[2])
delete idmap from proper nodemap tree
Parameters:
name name of nodemap
id_type NODEMAP_UID or NODEMAP_GID
map array[2] __u32 containing the mapA values map[0] is client id map[1] is the filesystem id
Return values:
0 on success
Definition at line 455 of file nodemap_handler.c.
References active_config_lock, GOTO, idmap_delete(), idmap_search(), is_default_nodemap(), lu_nodemap::nm_idmap_lock, nm_member_revoke_locks(), NODEMAP_CLIENT_TO_FS, nodemap_idx_idmap_del(), nodemap_lookup(), and nodemap_putref().
Referenced by lprocfs_del_nodemap_idmap_seq_write(), and mgs_nodemap_cmd().
void nodemap_del_member (struct obd_export * exp)
delete a member from a nodemap
Parameters:
exp export to remove from a nodemap
Definition at line 376 of file nodemap_handler.c.
References nm_member_del().
Referenced by mdt_obd_connect(), mdt_obd_disconnect(), mdt_obd_reconnect(), ofd_obd_connect(), ofd_obd_disconnect(), and ofd_obd_reconnect().
int nodemap_del_range (const char * name, const lnet_nid_t nid[2])
delete a range
Parameters:
name nodemap name
range_str string containing range
Return values:
0 on success
Delete range from global range tree, and remove it from the list in the associated nodemap.
Definition at line 716 of file nodemap_handler.c.
References active_config_lock, GOTO, is_default_nodemap(), nm_member_reclassify_nodemap(), nm_member_revoke_locks(), nodemap_config::nmc_default_nodemap, nodemap_config::nmc_range_tree, nodemap_config::nmc_range_tree_lock, nodemap_idx_range_del(), nodemap_lookup(), nodemap_putref(), range_delete(), and range_find().
Referenced by lprocfs_del_nodemap_range_seq_write(), and mgs_nodemap_cmd().
ssize_t nodemap_map_acl (struct lu_nodemap * nodemap, void * buf, size_t size, enum nodemap_tree_type tree_type)
Map posix ACL entries according to the nodemap membership.
Removes any squashed ACLs.
Parameters:
lu_nodemap nodemap
buf buffer containing xattr encoded ACLs
size size of ACLs in bytes
tree_type direction of mapping
Return values:
size new size of ACLs in bytes
-EINVAL bad size param, see posix_acl_xattr_count()
Definition at line 580 of file nodemap_handler.c.
References posix_acl_xattr_header::a_entries, cpu_to_le32, posix_acl_xattr_entry::e_id, posix_acl_xattr_entry::e_tag, end, header, le16_to_cpu, le32_to_cpu, lu_nodemap::nm_squash_gid, lu_nodemap::nm_squash_uid, nodemap_active, NODEMAP_GID, nodemap_map_id(), NODEMAP_UID, and unlikely.
Referenced by mdt_reint_setxattr().
__u32 nodemap_map_id (struct lu_nodemap * nodemap, enum nodemap_id_type id_type, enum nodemap_tree_type tree_type, __u32 id)
mapping function for nodemap idmaps
Parameters:
nodemap lu_nodemap structure defining nodemap
node_type NODEMAP_UID or NODEMAP_GID
tree_type NODEMAP_CLIENT_TO_FS or NODEMAP_FS_TO_CLIENT
id id to map
Return values:
mapped id according to the rules below.
if the nodemap_active is false, just return the passed id without mapping
if the id to be looked up is 0, check that root access is allowed and if it is, return 0. Otherwise, return the squash uid or gid.
if the nodemap is configured to trusted the ids from the client system, just return the passwd id without mapping.
if by this point, we haven't returned and the nodemap in question is the default nodemap, return the squash uid or gid.
after these checks, search the proper tree for the mapping, and if found return the mapped value, otherwise return the squash uid or gid.
Definition at line 519 of file nodemap_handler.c.
References lu_idmap::id_client, lu_idmap::id_fs, idmap_search(), is_default_nodemap(), lu_nodemap::nm_idmap_lock, lu_nodemap::nm_squash_gid, lu_nodemap::nm_squash_uid, lu_nodemap::nmf_allow_root_access, lu_nodemap::nmf_trust_client_ids, nodemap_active, NODEMAP_FS_TO_CLIENT, NODEMAP_UID, and unlikely.
Referenced by mdt_pack_attr2body(), mdt_quotactl(), mdt_setattr_unpack_rec(), nodemap_map_acl(), nodemap_test_id(), ofd_quotactl(), old_init_ucred(), old_init_ucred_reint(), and tgt_ost_body_unpack().
int nodemap_parse_idmap (char * idmap_str, __u32 idmap[2])
parse a string containing an id map of form "client_id:filesystem_id" into an array of __u32 * for use in mapping functions
Parameters:
idmap_str map string
idmap array[2] of __u32
Return values:
0 on success
-EINVAL if idmap cannot be parsed
Definition at line 313 of file nodemap_handler.c.
References kstrtoul().
Referenced by lprocfs_add_nodemap_idmap_seq_write(), lprocfs_del_nodemap_idmap_seq_write(), and mgs_nodemap_cmd().
int nodemap_parse_range (const char * range_str, lnet_nid_t range[2])
parse a nodemap range string into two nids
Parameters:
range_str string to parse
range[2] array of two nids 0 on success
Definition at line 278 of file nodemap_handler.c.
References buf, GOTO, libcfs_str2nid(), and LNET_NIDSTR_SIZE.
Referenced by mgs_nodemap_cmd(), and parse_nids().
int nodemap_set_allow_root (const char * name, bool allow_root)
update flag to turn on or off nodemap functions
Parameters:
name nodemap name
admin_string string containing updated value
Return values:
0 on success
Update admin flag to turn on or off nodemap functions.
Definition at line 864 of file nodemap_handler.c.
References active_config_lock, GOTO, nm_member_revoke_locks(), lu_nodemap::nmf_allow_root_access, nodemap_idx_nodemap_update(), nodemap_lookup(), and nodemap_putref().
Referenced by mgs_nodemap_cmd(), and nodemap_admin_seq_write().
int nodemap_set_squash_gid (const char * name, gid_t gid)
Update the squash_gid for a nodemap.
Parameters:
name nodemap name
gid_string string containing new squash_gid value
Return values:
0 on success
Update the squash_gid for a nodemap. The squash_uid is the gid that the all client gids are mapped to if nodemap is active, the trust_client_ids flag is not set, and the gid is not in the idmap tree.
Definition at line 960 of file nodemap_handler.c.
References active_config_lock, GOTO, nm_member_revoke_locks(), lu_nodemap::nm_squash_gid, nodemap_idx_nodemap_update(), nodemap_lookup(), and nodemap_putref().
Referenced by mgs_nodemap_cmd(), and nodemap_squash_gid_seq_write().
int nodemap_set_squash_uid (const char * name, uid_t uid)
update the squash_uid for a nodemap
Parameters:
name nodemap name
uid_string string containing new squash_uid value
Return values:
0 on success
Update the squash_uid for a nodemap. The squash_uid is the uid that the all client uids are mapped to if nodemap is active, the trust_client_ids flag is not set, and the uid is not in the idmap tree.
Definition at line 927 of file nodemap_handler.c.
References active_config_lock, GOTO, nm_member_revoke_locks(), lu_nodemap::nm_squash_uid, nodemap_idx_nodemap_update(), nodemap_lookup(), and nodemap_putref().
Referenced by mgs_nodemap_cmd(), and nodemap_squash_uid_seq_write().
int nodemap_set_trust_client_ids (const char * name, bool trust_client_ids)
updated trust_client_ids flag for nodemap
Parameters:
name nodemap name
trust_string new value for trust flag
Return values:
0 on success
Update the trust_client_ids flag for a nodemap.
Definition at line 894 of file nodemap_handler.c.
References active_config_lock, GOTO, nm_member_revoke_locks(), lu_nodemap::nmf_trust_client_ids, nodemap_idx_nodemap_update(), nodemap_lookup(), and nodemap_putref().
Referenced by mgs_nodemap_cmd(), and nodemap_trusted_seq_write().
__u32 nodemap_test_id (lnet_nid_t nid, enum nodemap_id_type idtype, __u32 client_id)
Returns the id mapping for a given nid/id pair.
Useful for testing the nodemap configuration to make sure it is working as expected.
Parameters:
nid nid to classify
idtype uid or gid
client_id id to map to fs
Return values:
the mapped fs_id of the given client_id
Definition at line 1339 of file nodemap_handler.c.
References active_config_lock, nodemap_config::nmc_range_tree_lock, nodemap_classify_nid(), NODEMAP_CLIENT_TO_FS, nodemap_map_id(), and nodemap_putref().
Referenced by mgs_iocontrol_nodemap().
void nodemap_test_nid (lnet_nid_t nid, char * name_buf, size_t name_len)
Returns the nodemap classification for a given nid into an ioctl buffer.
Useful for testing the nodemap configuration to make sure it is working as expected.
Parameters:
nid nid to classify
[out] name_buf buffer to write the nodemap name to
name_len length of buffer
Definition at line 1311 of file nodemap_handler.c.
References active_config_lock, lu_nodemap::nm_name, nodemap_config::nmc_range_tree_lock, nodemap_classify_nid(), and nodemap_putref().
Referenced by mgs_iocontrol_nodemap().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.