Lustre: lustre/include/lustre_lfsck.h File Reference
lustre/include/lustre_lfsck.h File Reference
#include <lustre/lustre_lfsck_user.h>
#include <lustre_dlm.h>
#include <lu_object.h>
#include <dt_object.h>
Data Structures
struct lfsck_start_param
Typedefs
typedef int(* lfsck_out_notify)(const struct lu_env *env, void *data, enum lfsck_events event)
Enumerations
enum lfsck_pv_status { LPVS_INIT = 0, LPVS_INCONSISTENT = 1, LPVS_INCONSISTENT_TOFIX = 2 }
Functions
int lfsck_register_namespace (const struct lu_env *env, struct dt_device *key, struct ldlm_namespace *ns)
int lfsck_register (const struct lu_env *env, struct dt_device *key, struct dt_device *next, struct obd_device *obd, lfsck_out_notify notify, void *notify_data, bool master)
void lfsck_degister (const struct lu_env *env, struct dt_device *key)
int lfsck_add_target (const struct lu_env *env, struct dt_device *key, struct dt_device *tgt, struct obd_export *exp, __u32 index, bool for_ost)
void lfsck_del_target (const struct lu_env *env, struct dt_device *key, struct dt_device *tgt, __u32 index, bool for_ost)
int lfsck_start (const struct lu_env *env, struct dt_device *key, struct lfsck_start_param *lsp)
int lfsck_stop (const struct lu_env *env, struct dt_device *key, struct lfsck_stop *stop)
int lfsck_in_notify (const struct lu_env *env, struct dt_device *key, struct lfsck_request *lr, struct thandle *th)
int lfsck_query (const struct lu_env *env, struct dt_device *key, struct lfsck_request *req, struct lfsck_reply *rep, struct lfsck_query *que)
int lfsck_get_speed (struct seq_file *m, struct dt_device *key)
int lfsck_set_speed (struct dt_device *key, __u32 val)
int lfsck_get_windows (struct seq_file *m, struct dt_device *key)
int lfsck_set_windows (struct dt_device *key, int val)
int lfsck_dump (struct seq_file *m, struct dt_device *key, enum lfsck_type type)
static void lfsck_pack_rfa (struct lfsck_request *lr, const struct lu_fid *fid, __u32 event, __u16 com)
Typedef Documentation
typedef int(* lfsck_out_notify)(const struct lu_env *env, void *data, enum lfsck_events event)
Definition at line 54 of file lustre_lfsck.h.
Enumeration Type Documentation
enum lfsck_pv_status
Enumerator:
LPVS_INIT
LPVS_INCONSISTENT
LPVS_INCONSISTENT_TOFIX
Definition at line 48 of file lustre_lfsck.h.
Function Documentation
int lfsck_add_target (const struct lu_env * env, struct dt_device * key, struct dt_device * tgt, struct obd_export * exp, __u32 index, bool for_ost)
Definition at line 3661 of file lfsck_lib.c.
References __lfsck_add_target(), __lfsck_instance_find(), ENTRY, INIT_LIST_HEAD, lfsck_instance_put(), lfsck_mdt_orphan_list, lfsck_ost_orphan_list, lfsck_tgt_put(), list_add_tail(), lfsck_tgt_desc::ltd_exp, lfsck_tgt_desc::ltd_index, lfsck_tgt_desc::ltd_key, lfsck_tgt_desc::ltd_layout_list, lfsck_tgt_desc::ltd_layout_phase_list, lfsck_tgt_desc::ltd_namespace_list, lfsck_tgt_desc::ltd_namespace_phase_list, lfsck_tgt_desc::ltd_orphan_list, lfsck_tgt_desc::ltd_ref, lfsck_tgt_desc::ltd_tgt, OBD_ALLOC_PTR, and RETURN.
Referenced by lod_add_device().
void lfsck_degister (const struct lu_env * env, struct dt_device * key)
Definition at line 3651 of file lfsck_lib.c.
References lfsck_instance_find(), and lfsck_instance_put().
Referenced by mdd_device_shutdown(), and ofd_fini().
void lfsck_del_target (const struct lu_env * env, struct dt_device * key, struct dt_device * tgt, __u32 index, bool for_ost)
Definition at line 3710 of file lfsck_lib.c.
References __lfsck_instance_find(), cfs_bitmap_clear(), head, LASSERT, lfsck_assign_tgt(), lfsck_instance_put(), lfsck_ltd2tgt(), lfsck_mdt_orphan_list, lfsck_ost_orphan_list, lfsck_stop_notify(), lfsck_tgt_put(), LFSCK_TYPE_LAYOUT, LFSCK_TYPE_NAMESPACE, lfsck_instance::li_mdt_descs, lfsck_instance::li_ost_descs, list_del_init(), list_for_each_entry, lfsck_tgt_desc::ltd_dead, lfsck_tgt_descs::ltd_lock, lfsck_tgt_descs::ltd_orphan, lfsck_tgt_desc::ltd_orphan_list, lfsck_tgt_descs::ltd_rw_sem, lfsck_tgt_desc::ltd_tgt, lfsck_tgt_descs::ltd_tgtnr, lfsck_tgt_descs::ltd_tgts_bitmap, cfs_bitmap::size, and unlikely.
Referenced by __lod_del_device().
int lfsck_dump (struct seq_file * m, struct dt_device * key, enum lfsck_type type)
Definition at line 2745 of file lfsck_lib.c.
References ENTRY, lfsck_component::lc_ops, LCT_DT_THREAD, LCT_MD_THREAD, lfsck_component_find(), lfsck_component_put(), lfsck_operations::lfsck_dump, lfsck_instance_find(), lfsck_instance_put(), likely, lu_env_fini(), lu_env_init(), and RETURN.
Referenced by mdd_lfsck_layout_seq_show(), and mdd_lfsck_namespace_seq_show().
int lfsck_get_speed (struct seq_file * m, struct dt_device * key)
Definition at line 2631 of file lfsck_lib.c.
References ENTRY, lfsck_bookmark::lb_speed_limit, LCT_DT_THREAD, LCT_MD_THREAD, lfsck_instance_find(), lfsck_instance_put(), lfsck_instance::li_bookmark_ram, likely, lu_env_fini(), lu_env_init(), and RETURN.
Referenced by mdd_lfsck_speed_limit_seq_show().
int lfsck_get_windows (struct seq_file * m, struct dt_device * key)
Definition at line 2684 of file lfsck_lib.c.
References ENTRY, lfsck_bookmark::lb_async_windows, LCT_DT_THREAD, LCT_MD_THREAD, lfsck_instance_find(), lfsck_instance_put(), lfsck_instance::li_bookmark_ram, likely, lu_env_fini(), lu_env_init(), and RETURN.
Referenced by mdd_lfsck_async_windows_seq_show().
int lfsck_in_notify (const struct lu_env * env, struct dt_device * key, struct lfsck_request * lr, struct thandle * th)
Definition at line 3296 of file lfsck_lib.c.
References ENTRY, lfsck_component::lc_ops, LE_CONDITIONAL_DESTROY, LE_FID_ACCESSED, LE_PAIRS_VERIFY, LE_PEER_EXIT, LE_PHASE1_DONE, LE_PHASE2_DONE, LE_SET_LMV_MASTER, LE_SET_LMV_SLAVE, LE_SKIP_NLINK, LE_SKIP_NLINK_DECLARE, LE_START, LE_STOP, lfsck_component_find(), lfsck_component_put(), lfsck_env_info(), lfsck_operations::lfsck_in_notify, lfsck_instance_find(), lfsck_instance_put(), lfsck_start(), lfsck_stop(), likely, LPF_BROADCAST, lfsck_request::lr_active, lfsck_request::lr_async_windows, lfsck_request::lr_event, lfsck_request::lr_index, lfsck_request::lr_param, lfsck_request::lr_speed, lfsck_request::lr_status, lfsck_request::lr_valid, lfsck_request::lr_version, lfsck_start::ls_active, lfsck_start::ls_async_windows, lfsck_stop::ls_flags, lfsck_start::ls_flags, lfsck_start::ls_speed_limit, lfsck_stop::ls_status, lfsck_start::ls_valid, lfsck_start::ls_version, lfsck_start_param::lsp_index, lfsck_start_param::lsp_index_valid, lfsck_start_param::lsp_start, lfsck_thread_info::lti_start, lfsck_thread_info::lti_stop, RETURN, start, stop, and unlikely.
Referenced by lfsck_init(), mdd_declare_links_add(), mdd_links_write(), ofd_inconsistency_verify_one(), and ofd_precreate_objects().
static void lfsck_pack_rfa (struct lfsck_request * lr, const struct lu_fid * fid, __u32 event, __u16 com) [inline, static]
Definition at line 87 of file lustre_lfsck.h.
References lfsck_request::lr_active, lfsck_request::lr_event, and lfsck_request::lr_fid.
Referenced by mdd_declare_links_add(), mdd_links_write(), ofd_precreate_objects(), out_handle(), out_tx_xattr_set_exec(), and out_xattr_set_add_exec().
int lfsck_query (const struct lu_env * env, struct dt_device * key, struct lfsck_request * req, struct lfsck_reply * rep, struct lfsck_query * que)
Definition at line 3364 of file lfsck_lib.c.
References cfs_time_seconds(), ENTRY, GOTO, l_wait_event, lfsck_component::lc_ops, lfsck_component_find(), lfsck_component_put(), lfsck_instance_find(), lfsck_instance_put(), lfsck_operations::lfsck_query, LFSCK_TYPE_BITS, LFSCK_TYPE_SCRUB, LFSCK_TYPES_ALL, LFSCK_TYPES_SUPPORTED, lfsck_instance::li_thread, likely, LPF_WAIT, lfsck_request::lr_active, LS_MAX, LS_SCANNING_PHASE1, LS_SCANNING_PHASE2, lfsck_query::lu_flags, lfsck_query::lu_mdts_count, lfsck_query::lu_osts_count, lfsck_query::lu_repaired, lfsck_query::lu_types, LWI_ON_SIGNAL_NOOP, LWI_TIMEOUT_INTR, RETURN, ptlrpc_thread::t_ctl_waitq, and unlikely.
Referenced by mdd_iocontrol().
int lfsck_register (const struct lu_env * env, struct dt_device * key, struct dt_device * next, struct obd_device * obd, lfsck_out_notify notify, void * notify_data, bool master)
Definition at line 3474 of file lfsck_lib.c.
References dt_object_operations::do_index_try, dt_object::do_lu, dt_object::do_ops, dotlustre, dt_key, dt_locate(), dt_lookup(), dt_otable_features, dt_root_get(), dt_try_as_dir(), ENTRY, lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, FID_SEQ_LOCAL_FILE, FID_SEQ_LOCAL_NAME, GOTO, INIT_LIST_HEAD, lfsck_add_target_from_orphan(), lfsck_bookmark_setup(), lfsck_dev_idx(), LFSCK_DIR, lfsck_env_info(), lfsck_fid_init(), lfsck_instance_add(), lfsck_instance_cleanup(), lfsck_instance_find(), lfsck_layout_setup(), lfsck_name_get_const(), lfsck_namespace_setup(), lfsck_object_put(), lfsck_tgt_descs_init(), lfsck_verify_linkea(), lfsck_instance::li_bottom, lfsck_instance::li_double_scan_count, lfsck_instance::li_global_root_fid, lfsck_instance::li_lfsck_dir, lfsck_instance::li_link, lfsck_instance::li_list_dir, lfsck_instance::li_list_double_scan, lfsck_instance::li_list_idle, lfsck_instance::li_list_lmv, lfsck_instance::li_list_scan, lfsck_instance::li_local_root_fid, lfsck_instance::li_lock, lfsck_instance::li_los, lfsck_instance::li_master, lfsck_instance::li_mdt_descs, lfsck_instance::li_mutex, lfsck_instance::li_next, lfsck_instance::li_obd, lfsck_instance::li_obj_oit, lfsck_instance::li_ost_descs, lfsck_instance::li_out_notify, lfsck_instance::li_out_notify_data, lfsck_instance::li_ref, lfsck_instance::li_thread, local_file_find_or_create(), local_oid_storage_init(), lostfound, lfsck_thread_info::lti_fid, lfsck_thread_info::lti_fid2, lu_object_get(), OBD_ALLOC_PTR, OTABLE_IT_OID, RETURN, ptlrpc_thread::t_ctl_waitq, and unlikely.
Referenced by mdd_prepare(), and ofd_prepare().
int lfsck_register_namespace (const struct lu_env * env, struct dt_device * key, struct ldlm_namespace * ns)
Definition at line 3457 of file lfsck_lib.c.
References lfsck_instance_find(), lfsck_instance_put(), lfsck_instance::li_namespace, and likely.
Referenced by mdt_prepare(), and ofd_prepare().
int lfsck_set_speed (struct dt_device * key, __u32 val)
Definition at line 2656 of file lfsck_lib.c.
References __lfsck_set_speed(), ENTRY, LCT_DT_THREAD, LCT_MD_THREAD, lfsck_bookmark_store(), lfsck_instance_find(), lfsck_instance_put(), lfsck_instance::li_mutex, likely, lu_env_fini(), lu_env_init(), and RETURN.
Referenced by mdd_lfsck_speed_limit_seq_write().
int lfsck_set_windows (struct dt_device * key, int val)
Definition at line 2709 of file lfsck_lib.c.
References CWARN, ENTRY, lfsck_bookmark::lb_async_windows, LCT_DT_THREAD, LCT_MD_THREAD, LFSCK_ASYNC_WIN_MAX, lfsck_bookmark_store(), lfsck_instance_find(), lfsck_instance_put(), lfsck_lfsck2name(), lfsck_instance::li_bookmark_ram, lfsck_instance::li_mutex, likely, lu_env_fini(), lu_env_init(), and RETURN.
Referenced by mdd_lfsck_async_windows_seq_write().
int lfsck_start (const struct lu_env * env, struct dt_device * key, struct lfsck_start_param * lsp)
Definition at line 2937 of file lfsck_lib.c.
References __lfsck_component_find(), __lfsck_set_speed(), CERROR, cfs_foreach_bit, DOIF_DRYRUN, DOIF_FAILOUT, DOIF_OUTUSED, DOIF_RESET, DOIV_DRYRUN, DOIV_ERROR_HANDLE, DT_OTABLE_IT_FLAGS_SHIFT, ENTRY, GOTO, l_wait_event, LASSERT, lfsck_bookmark::lb_param, lfsck_bookmark::lb_speed_limit, lfsck_bookmark::lb_version, lfsck_component::lc_link, lfsck_component::lc_ops, lfsck_component::lc_type, lfsck_bookmark_store(), lfsck_instance_find(), lfsck_instance_put(), lfsck_operations::lfsck_join, lfsck_lfsck2name(), lfsck_ltd2tgt(), lfsck_master_engine(), lfsck_operations::lfsck_post, lfsck_operations::lfsck_reset, lfsck_reset_ltd_status(), lfsck_set_param(), lfsck_start_all(), lfsck_thread_args_fini(), lfsck_thread_args_init(), LFSCK_TYPE_LAYOUT, LFSCK_TYPE_NAMESPACE, LFSCK_TYPES_ALL, LFSCK_TYPES_SUPPORTED, lfsck_instance::li_args_dir, lfsck_instance::li_args_oit, lfsck_instance::li_bookmark_ram, lfsck_instance::li_drop_dryrun, lfsck_instance::li_flags, lfsck_instance::li_list_double_scan, lfsck_instance::li_list_idle, lfsck_instance::li_list_scan, lfsck_instance::li_lock, lfsck_instance::li_master, lfsck_instance::li_mdt_descs, lfsck_instance::li_mutex, lfsck_instance::li_namespace, lfsck_instance::li_new_scanned, lfsck_instance::li_oit_over, lfsck_instance::li_ost_descs, lfsck_instance::li_start_unplug, lfsck_instance::li_status, lfsck_instance::li_thread, list_del_init(), list_empty(), list_for_each_entry, list_for_each_entry_safe, list_move_tail(), LPF_BROADCAST, LPF_DRYRUN, LPF_FAILOUT, LPF_RESET, lfsck_start::ls_active, LS_FAILED, lfsck_start::ls_flags, lfsck_start::ls_speed_limit, lfsck_start::ls_valid, lfsck_start::ls_version, lfsck_start_param::lsp_start, LSV_DRYRUN, LSV_ERROR_HANDLE, LSV_SPEED_LIMIT, lfsck_tgt_desc::ltd_layout_done, lfsck_tgt_desc::ltd_layout_list, lfsck_tgt_desc::ltd_layout_phase_list, lfsck_tgt_desc::ltd_namespace_done, lfsck_tgt_desc::ltd_namespace_list, lfsck_tgt_desc::ltd_namespace_phase_list, lfsck_tgt_descs::ltd_rw_sem, lfsck_tgt_desc::ltd_synced_failures, lfsck_tgt_descs::ltd_tgts_bitmap, LUDA_64BITHASH, LUDA_TYPE, LUDA_VERIFY, LUDA_VERIFY_DRYRUN, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_NO_AUTO, RETURN, start, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, thread, thread_is_init(), thread_is_running(), thread_is_stopped(), thread_set_flags(), and unlikely.
Referenced by lfsck_in_notify(), mdd_iocontrol(), ofd_iocontrol(), and ofd_postrecov().
int lfsck_stop (const struct lu_env * env, struct dt_device * key, struct lfsck_stop * stop)
Definition at line 3213 of file lfsck_lib.c.
References CERROR, ENTRY, GOTO, l_wait_event, lfsck_assistant_data::lad_lock, lfsck_assistant_data::lad_task, lfsck_component::lc_data, lfsck_instance_find(), lfsck_instance_put(), lfsck_lfsck2name(), lfsck_stop_all(), lfsck_instance::li_flags, lfsck_instance::li_list_double_scan, lfsck_instance::li_list_scan, lfsck_instance::li_lock, lfsck_instance::li_master, lfsck_instance::li_mutex, lfsck_instance::li_status, lfsck_instance::li_thread, list_for_each_entry, LPF_BROADCAST, lfsck_stop::ls_flags, lfsck_stop::ls_status, LS_STOPPED, RETURN, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, thread, thread_is_init(), thread_is_stopped(), thread_set_flags(), and unlikely.
Referenced by lfsck_in_notify(), lfsck_layout_master_in_notify(), lfsck_layout_slave_in_notify(), lfsck_namespace_in_notify(), mdd_iocontrol(), ofd_fini(), and ofd_iocontrol().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.