Lustre: lustre/include/lustre_update.h File Reference
lustre/include/lustre_update.h File Reference
#include <lustre_net.h>
#include <dt_object.h>
Data Structures
struct thandle_update_records
Attached in the thandle to record the updates for distribute distribution.
struct top_multiple_thandle
struct top_thandle
struct sub_thandle_cookie
struct sub_thandle
struct tx_arg
struct thandle_exec_args
Defines
#define OUT_UPDATE_INIT_BUFFER_SIZE 4096
#define OUT_UPDATE_REPLY_SIZE 4096
#define OUT_BULK_BUFFER_SIZE 4096
#define TOP_THANDLE_MAGIC 0x20140917
#define update_record_pack(name, th,...)
#define update_record_size(env, name, th,...)
Typedefs
typedef int(* tx_exec_func_t)(const struct lu_env *env, struct thandle *th, struct tx_arg *ta)
Functions
static size_t update_params_size (const struct update_params *params, unsigned int param_count)
static struct object_update_param * update_params_get_param (const struct update_params *params, unsigned int index, unsigned int param_count)
static void * update_params_get_param_buf (const struct update_params *params, __u16 index, unsigned int param_count, __u16 *size)
static size_t update_op_size (unsigned int param_count)
static struct update_op * update_op_next_op (const struct update_op *uop)
static size_t update_ops_size (const struct update_ops *ops, unsigned int update_count)
static struct update_params * update_records_get_params (const struct update_records *record)
static size_t update_records_size (const struct update_records *record)
static size_t llog_update_record_size (const struct llog_update_record *lur)
static struct update_op * update_ops_get_op (const struct update_ops *ops, unsigned int index, unsigned int update_count)
static void * object_update_param_get (const struct object_update *update, size_t index, size_t *size)
static unsigned long object_update_request_size (const struct object_update_request *our)
static void object_update_result_insert (struct object_update_reply *reply, void *data, size_t data_len, size_t index, int rc)
static int object_update_result_data_get (const struct object_update_reply *reply, struct lu_buf *lbuf, size_t index)
int out_update_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, enum update_type op, const struct lu_fid *fid, unsigned int params_count, __u16 *param_sizes, const void **param_bufs, __u32 reply_size)
Packs one update into the update_buffer.
int out_create_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, const struct lu_fid *fid, const struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof)
Pack various updates into the update_buffer.
int out_object_destroy_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, const struct lu_fid *fid)
int out_index_delete_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, const struct lu_fid *fid, const struct dt_key *key)
int out_index_insert_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, const struct lu_fid *fid, const struct dt_rec *rec, const struct dt_key *key)
int out_xattr_set_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, const struct lu_fid *fid, const struct lu_buf *buf, const char *name, __u32 flag)
int out_xattr_del_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, const struct lu_fid *fid, const char *name)
int out_attr_set_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, const struct lu_fid *fid, const struct lu_attr *attr)
int out_ref_add_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, const struct lu_fid *fid)
int out_ref_del_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, const struct lu_fid *fid)
int out_write_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, const struct lu_fid *fid, const struct lu_buf *buf, __u64 pos)
int out_attr_get_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, const struct lu_fid *fid)
int out_index_lookup_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, const struct lu_fid *fid, struct dt_rec *rec, const struct dt_key *key)
Pack various readonly updates into the update_buffer.
int out_xattr_get_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, const struct lu_fid *fid, const char *name, const int bufsize)
int out_read_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_length, const struct lu_fid *fid, size_t size, loff_t pos)
const char * update_op_str (__u16 opcode)
struct thandle * thandle_get_sub_by_dt (const struct lu_env *env, struct thandle *th, struct dt_device *sub_dt)
Get sub thandle.
static struct thandle * thandle_get_sub (const struct lu_env *env, struct thandle *th, const struct dt_object *sub_obj)
struct thandle * top_trans_create (const struct lu_env *env, struct dt_device *master_dev)
Create the top transaction.
int top_trans_start (const struct lu_env *env, struct dt_device *master_dev, struct thandle *th)
start the top transaction.
int top_trans_stop (const struct lu_env *env, struct dt_device *master_dev, struct thandle *th)
Stop the top transaction.
void top_multiple_thandle_destroy (struct top_multiple_thandle *tmt)
Top multiple thandle destroy.
static void top_multiple_thandle_get (struct top_multiple_thandle *tmt)
static void top_multiple_thandle_put (struct top_multiple_thandle *tmt)
struct sub_thandle * lookup_sub_thandle (struct top_multiple_thandle *tmt, struct dt_device *dt_dev)
int sub_thandle_trans_create (const struct lu_env *env, struct top_thandle *top_th, struct sub_thandle *st)
Create sub thandle.
size_t update_records_create_size (const struct lu_env *env, const struct lu_fid *fid, const struct lu_attr *attr, const struct dt_allocation_hint *hint, struct dt_object_format *dof)
Calculate create update size.
size_t update_records_attr_set_size (const struct lu_env *env, const struct lu_fid *fid, const struct lu_attr *attr)
Calculate attr set update size.
size_t update_records_ref_add_size (const struct lu_env *env, const struct lu_fid *fid)
Calculate ref add update size.
size_t update_records_ref_del_size (const struct lu_env *env, const struct lu_fid *fid)
Calculate ref del update size.
size_t update_records_object_destroy_size (const struct lu_env *env, const struct lu_fid *fid)
Calculate object destroy update size.
size_t update_records_index_insert_size (const struct lu_env *env, const struct lu_fid *fid, const struct dt_rec *rec, const struct dt_key *key)
Calculate index insert update size.
size_t update_records_index_delete_size (const struct lu_env *env, const struct lu_fid *fid, const struct dt_key *key)
Calculate index delete update size.
size_t update_records_xattr_set_size (const struct lu_env *env, const struct lu_fid *fid, const struct lu_buf *buf, const char *name, __u32 flag)
Calculate xattr set size.
size_t update_records_xattr_del_size (const struct lu_env *env, const struct lu_fid *fid, const char *name)
Calculate xattr delete update size.
size_t update_records_write_size (const struct lu_env *env, const struct lu_fid *fid, const struct lu_buf *buf, __u64 pos)
Calculate write update size.
size_t update_records_punch_size (const struct lu_env *env, const struct lu_fid *fid, __u64 start, __u64 end)
Calculate size of punch update.
int update_records_create_pack (const struct lu_env *env, struct update_ops *ops, unsigned int *op_count, size_t *max_ops_size, struct update_params *params, unsigned int *param_count, size_t *max_param_size, const struct lu_fid *fid, const struct lu_attr *attr, const struct dt_allocation_hint *hint, struct dt_object_format *dof)
Pack create update.
int update_records_attr_set_pack (const struct lu_env *env, struct update_ops *ops, unsigned int *op_count, size_t *max_ops_size, struct update_params *params, unsigned int *param_count, size_t *max_param_size, const struct lu_fid *fid, const struct lu_attr *attr)
Pack attr set update.
int update_records_ref_add_pack (const struct lu_env *env, struct update_ops *ops, unsigned int *op_count, size_t *max_ops_size, struct update_params *params, unsigned int *param_count, size_t *max_param_size, const struct lu_fid *fid)
Pack ref add update.
int update_records_ref_del_pack (const struct lu_env *env, struct update_ops *ops, unsigned int *op_count, size_t *max_ops_size, struct update_params *params, unsigned int *param_count, size_t *max_param_size, const struct lu_fid *fid)
Pack ref del update.
int update_records_object_destroy_pack (const struct lu_env *env, struct update_ops *ops, unsigned int *op_count, size_t *max_ops_size, struct update_params *params, unsigned int *param_count, size_t *max_param_size, const struct lu_fid *fid)
Pack object destroy update.
int update_records_index_insert_pack (const struct lu_env *env, struct update_ops *ops, unsigned int *op_count, size_t *max_ops_size, struct update_params *params, unsigned int *param_count, size_t *max_param_size, const struct lu_fid *fid, const struct dt_rec *rec, const struct dt_key *key)
Pack index insert update.
int update_records_index_delete_pack (const struct lu_env *env, struct update_ops *ops, unsigned int *op_count, size_t *max_ops_size, struct update_params *params, unsigned int *param_count, size_t *max_param_size, const struct lu_fid *fid, const struct dt_key *key)
Pack index delete update.
int update_records_xattr_set_pack (const struct lu_env *env, struct update_ops *ops, unsigned int *op_count, size_t *max_ops_size, struct update_params *params, unsigned int *param_count, size_t *max_param_size, const struct lu_fid *fid, const struct lu_buf *buf, const char *name, __u32 flag)
Pack xattr set update.
int update_records_xattr_del_pack (const struct lu_env *env, struct update_ops *ops, unsigned int *op_count, size_t *max_ops_size, struct update_params *params, unsigned int *param_count, size_t *max_param_size, const struct lu_fid *fid, const char *name)
Pack xattr delete update.
int update_records_write_pack (const struct lu_env *env, struct update_ops *ops, unsigned int *op_count, size_t *max_ops_size, struct update_params *params, unsigned int *param_count, size_t *max_param_size, const struct lu_fid *fid, const struct lu_buf *buf, __u64 pos)
Pack write update.
int update_records_punch_pack (const struct lu_env *env, struct update_ops *ops, unsigned int *op_count, size_t *max_ops_size, struct update_params *params, unsigned int *param_count, size_t *max_param_size, const struct lu_fid *fid, __u64 start, __u64 end)
Pack punch.
int update_records_noop_pack (const struct lu_env *env, struct update_ops *ops, unsigned int *op_count, size_t *max_ops_size, struct update_params *params, unsigned int *param_count, size_t *max_param_size, const struct lu_fid *fid)
Pack noop update.
int tur_update_records_extend (struct thandle_update_records *tur, size_t new_size)
Extend update records.
int tur_update_params_extend (struct thandle_update_records *tur, size_t new_size)
Extend update params.
int tur_update_extend (struct thandle_update_records *tur, size_t new_op_size, size_t new_param_size)
Extend update records.
Define Documentation
#define OUT_BULK_BUFFER_SIZE 4096
Definition at line 38 of file lustre_update.h.
Referenced by osp_md_read(), and out_read().
#define OUT_UPDATE_INIT_BUFFER_SIZE 4096
Definition at line 36 of file lustre_update.h.
Referenced by osp_object_update_request_create(), and osp_update_request_create().
#define OUT_UPDATE_REPLY_SIZE 4096
Definition at line 37 of file lustre_update.h.
Referenced by osp_attr_get(), osp_md_index_lookup(), osp_md_read(), osp_prep_update_req(), osp_update_interpret(), and osp_xattr_get().
#define TOP_THANDLE_MAGIC 0x20140917
Definition at line 282 of file lustre_update.h.
Referenced by top_multiple_thandle_destroy(), top_multiple_thandle_dump(), and top_trans_create_tmt().
#define update_record_pack (name, th, ...)
Definition at line 640 of file lustre_update.h.
Referenced by lod_add_noop_records(), lod_sub_object_attr_set(), lod_sub_object_create(), lod_sub_object_delete(), lod_sub_object_destroy(), lod_sub_object_index_insert(), lod_sub_object_punch(), lod_sub_object_ref_add(), lod_sub_object_ref_del(), lod_sub_object_write(), lod_sub_object_xattr_del(), and lod_sub_object_xattr_set().
#define update_record_size (env, name, th, ...)
Value:
({                                                                      \
        struct top_thandle *top_th;                                     \
        struct top_multiple_thandle *tmt;                               \
                                                                        \
        top_th = container_of(th, struct top_thandle, tt_super);        \
                                                                        \
        LASSERT(top_th->tt_multiple_thandle != NULL);                   \
        tmt = top_th->tt_multiple_thandle;                              \
        tmt->tmt_record_size +=                                         \
                update_records_##name##_size(env, __VA_ARGS__);         \
})
Definition at line 680 of file lustre_update.h.
Referenced by lod_sub_object_declare_attr_set(), lod_sub_object_declare_create(), lod_sub_object_declare_delete(), lod_sub_object_declare_destroy(), lod_sub_object_declare_insert(), lod_sub_object_declare_punch(), lod_sub_object_declare_ref_add(), lod_sub_object_declare_ref_del(), lod_sub_object_declare_write(), lod_sub_object_declare_xattr_del(), and lod_sub_object_declare_xattr_set().
Typedef Documentation
typedef int(* tx_exec_func_t)(const struct lu_env *env, struct thandle *th, struct tx_arg *ta)
Definition at line 338 of file lustre_update.h.
Function Documentation
static size_t llog_update_record_size (const struct llog_update_record * lur) [inline, static]
Definition at line 154 of file lustre_update.h.
References cfs_size_round(), llog_update_record::lur_hdr, llog_update_record::lur_update_rec, and update_records_size().
Referenced by dtrq_append_updates(), dtrq_create(), insert_update_records_to_replay_list(), lod_process_recovery_updates(), prepare_writing_updates(), sub_updates_write(), and tur_update_extend().
struct sub_thandle* lookup_sub_thandle (struct top_multiple_thandle * tmt, struct dt_device * dt_dev) [read]
Definition at line 423 of file update_trans.c.
References list_for_each_entry, sub_thandle::st_dt, sub_thandle::st_sub_list, and top_multiple_thandle::tmt_sub_thandle_list.
Referenced by distribute_txn_replay_handle(), thandle_get_sub_by_dt(), top_trans_stop(), and update_recovery_exec().
static void* object_update_param_get (const struct object_update * update, size_t index, size_t * size) [inline, static]
Definition at line 179 of file lustre_update.h.
References object_update_param_size(), object_update::ou_params, object_update::ou_params_count, object_update_param::oup_buf, and object_update_param::oup_len.
Referenced by out_attr_set(), out_attr_set_pack(), out_create(), out_create_pack(), out_index_delete(), out_index_insert(), out_index_lookup(), out_read(), out_write(), out_xattr_del(), out_xattr_get(), and out_xattr_set().
static unsigned long object_update_request_size (const struct object_update_request * our) [inline, static]
Definition at line 203 of file lustre_update.h.
References object_update_size(), offsetof, object_update_request::ourq_count, and size.
Referenced by osp_insert_async_request(), osp_prep_inline_update_req(), and osp_prep_update_req().
static int object_update_result_data_get (const struct object_update_reply * reply, struct lu_buf * lbuf, size_t index) [inline, static]
Definition at line 243 of file lustre_update.h.
References cfs_size_round(), LASSERT, lu_buf::lb_buf, lu_buf::lb_len, object_update_result_get(), object_update_result::our_data, object_update_result::our_datalen, object_update_result::our_rc, ptlrpc_status_ntoh(), RETURN, and size.
Referenced by osp_get_attr_from_reply(), osp_md_index_lookup(), osp_md_read(), osp_xattr_get(), and osp_xattr_get_interpterer().
static void object_update_result_insert (struct object_update_reply * reply, void * data, size_t data_len, size_t index, int rc) [inline, static]
Definition at line 219 of file lustre_update.h.
References cfs_size_round(), LASSERT, object_update_result_get(), object_update_result::our_datalen, object_update_result::our_rc, object_update_reply::ourp_lens, and ptlrpc_status_hton().
Referenced by out_attr_get(), out_index_lookup(), out_reconstruct(), out_tx_attr_set_exec(), out_tx_create_exec(), out_tx_destroy_exec(), out_tx_index_delete_exec(), out_tx_index_insert_exec(), out_tx_ref_add_exec(), out_tx_ref_del_exec(), out_tx_write_exec(), out_tx_xattr_del_exec(), out_tx_xattr_set_exec(), and out_xattr_get().
int out_attr_get_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, const struct lu_fid * fid)
Definition at line 387 of file out_lib.c.
References OUT_ATTR_GET, and out_update_pack().
int out_attr_set_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, const struct lu_fid * fid, const struct lu_attr * attr)
Definition at line 249 of file out_lib.c.
References ENTRY, lu_attr::la_valid, lustre_set_wire_obdo(), obdo::o_valid, obdo_from_la(), object_update_param_get(), OUT_ATTR_SET, out_update_header_pack(), RETURN, and size.
int out_create_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, const struct lu_fid * fid, const struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof)
Pack various updates into the update_buffer.
The following functions pack different updates into the update_buffer So parameters of these API is basically same as its correspondent OSD/OSP API, for detail description of these parameters see osd_handler.c or osp_md_object.c.
Parameters:
[in] env execution environment
[in] ubuf update buffer
[in] fid fid of this object for the update
Return values:
0 if insertion succeeds.
negative errno if insertion fails.
Definition at line 188 of file out_lib.c.
References dt_allocation_hint::dah_parent, dt_object::do_lu, ENTRY, fid_cpu_to_le(), lu_attr::la_valid, lu_object_fid(), lustre_set_wire_obdo(), obdo::o_valid, obdo_from_la(), object_update_param_get(), OUT_CREATE, out_update_header_pack(), and RETURN.
int out_index_delete_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, const struct lu_fid * fid, const struct dt_key * key)
Definition at line 321 of file out_lib.c.
References OUT_INDEX_DELETE, out_update_pack(), and size.
int out_index_insert_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, const struct lu_fid * fid, const struct dt_rec * rec, const struct dt_key * key)
Definition at line 299 of file out_lib.c.
References ARRAY_SIZE, cpu_to_le32, fid_cpu_to_le(), OUT_INDEX_INSERT, out_index_insert_pack(), out_update_pack(), dt_insert_rec::rec_fid, and dt_insert_rec::rec_type.
Referenced by out_index_insert_pack().
int out_index_lookup_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, const struct lu_fid * fid, struct dt_rec * rec, const struct dt_key * key)
Pack various readonly updates into the update_buffer.
The following update funcs are only used by read-only ops, lookup, getattr etc, so it does not need transaction here. Currently they are only used by OSP.
Parameters:
[in] env execution environment
[in] fid fid of this object for the update
[in] ubuf update buffer
Return values:
= 0 pack succeed. < 0 pack failed.
Definition at line 373 of file out_lib.c.
References OUT_INDEX_LOOKUP, out_update_pack(), and size.
int out_object_destroy_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, const struct lu_fid * fid)
Definition at line 334 of file out_lib.c.
References OUT_DESTROY, and out_update_pack().
int out_read_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_length, const struct lu_fid * fid, size_t size, loff_t pos)
Definition at line 409 of file out_lib.c.
References ARRAY_SIZE, cpu_to_le64, LASSERT, OUT_READ, and out_update_pack().
int out_ref_add_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, const struct lu_fid * fid)
Definition at line 241 of file out_lib.c.
References OUT_REF_ADD, and out_update_pack().
int out_ref_del_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, const struct lu_fid * fid)
Definition at line 233 of file out_lib.c.
References OUT_REF_DEL, and out_update_pack().
int out_update_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, enum update_type op, const struct lu_fid * fid, unsigned int param_count, __u16 * param_sizes, const void ** param_bufs, __u32 reply_size)
Packs one update into the update_buffer.
Parameters:
[in] env execution environment
[in] update update to be packed
[in] max_update_size *maximum size of update
[in] op update operation (enum update_type)
[in] fid object FID for this update
[in] param_count number of parameters for this update
[in] param_sizes array of parameters length of this update
[in] param_bufs parameter buffers
Return values:
= 0 if updates packing succeeds
negative errno if updates packing fails
Definition at line 146 of file out_lib.c.
References ENTRY, object_update_param_size(), object_update::ou_params, object_update_param::oup_buf, out_update_header_pack(), and RETURN.
Referenced by osp_insert_async_request(), out_attr_get_pack(), out_index_delete_pack(), out_index_insert_pack(), out_index_lookup_pack(), out_object_destroy_pack(), out_read_pack(), out_ref_add_pack(), out_ref_del_pack(), out_write_pack(), out_xattr_del_pack(), out_xattr_get_pack(), and out_xattr_set_pack().
int out_write_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, const struct lu_fid * fid, const struct lu_buf * buf, __u64 pos)
Definition at line 343 of file out_lib.c.
References ARRAY_SIZE, cpu_to_le64, lu_buf::lb_buf, lu_buf::lb_len, out_update_pack(), OUT_WRITE, and out_write_pack().
Referenced by out_write_pack().
int out_xattr_del_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, const struct lu_fid * fid, const char * name)
Definition at line 288 of file out_lib.c.
References out_update_pack(), OUT_XATTR_DEL, and size.
int out_xattr_get_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, const struct lu_fid * fid, const char * name, const int bufsize)
Definition at line 395 of file out_lib.c.
References LASSERT, out_update_pack(), OUT_XATTR_GET, and size.
int out_xattr_set_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, const struct lu_fid * fid, const struct lu_buf * buf, const char * name, __u32 flag)
Definition at line 275 of file out_lib.c.
References ARRAY_SIZE, lu_buf::lb_buf, lu_buf::lb_len, out_update_pack(), OUT_XATTR_SET, and out_xattr_set_pack().
Referenced by out_xattr_set_pack().
int sub_thandle_trans_create (const struct lu_env * env, struct top_thandle * top_th, struct sub_thandle * st)
Create sub thandle.
Create transaction handle for sub_thandle
Parameters:
[in] env execution environment
[in] th top thandle
[in] st sub_thandle
Return values:
0 if creation succeeds.
negative errno if creation fails.
Definition at line 567 of file update_trans.c.
Referenced by update_recovery_exec().
static struct thandle* thandle_get_sub (const struct lu_env * env, struct thandle * th, const struct dt_object * sub_obj) [static, read]
Definition at line 454 of file lustre_update.h.
References dt_object::do_lu, lu_object::lo_dev, lu2dt_dev(), and thandle_get_sub_by_dt().
Referenced by lod_sub_get_thandle(), mdd_changelog_store(), and mdd_declare_changelog_store().
struct thandle* thandle_get_sub_by_dt (const struct lu_env * env, struct thandle * th, struct dt_device * sub_dt) [read]
Get sub thandle.
Get sub thandle from the top thandle according to the sub dt_device.
Parameters:
[in] env execution environment
[in] th thandle on the top layer.
[in] sub_dt sub dt_device used to get sub transaction
Return values:
thandle of sub transaction if succeed
PTR_ERR(errno) if failed
Definition at line 1164 of file update_trans.c.
References create_sub_thandle_with_thandle(), dt_trans_create(), dt_trans_stop(), ENTRY, GOTO, likely, list_del(), lookup_sub_thandle(), OBD_FREE_PTR, RETURN, sub_thandle::st_sub_list, sub_thandle::st_sub_th, thandle::th_dev, thandle::th_result, thandle::th_wait_submit, top_multiple_thandle::tmt_master_sub_dt, top_trans_create_tmt(), top_thandle::tt_master_sub_thandle, and top_thandle::tt_multiple_thandle.
Referenced by mdd_declare_links_add(), mdd_links_write(), osp_get_storage_thandle(), osp_sync_add_rec(), osp_sync_declare_add(), and thandle_get_sub().
void top_multiple_thandle_destroy (struct top_multiple_thandle * tmt)
Top multiple thandle destroy.
Destroy multiple thandle and all its sub thandle.
Parameters:
[in] tmt top_multiple_thandle to be destroyed.
Definition at line 1242 of file update_trans.c.
References LASSERT, list_del(), list_for_each_entry_safe, OBD_FREE_PTR, sub_thandle::st_cookie_list, sub_thandle::st_sub_list, sub_thandle_cookie::stc_list, top_multiple_thandle::tmt_magic, top_multiple_thandle::tmt_sub_thandle_list, and TOP_THANDLE_MAGIC.
Referenced by top_multiple_thandle_put().
static void top_multiple_thandle_get (struct top_multiple_thandle * tmt) [inline, static]
Definition at line 468 of file lustre_update.h.
References top_multiple_thandle::tmt_refcount.
Referenced by distribute_txn_assign_batchid(), distribute_txn_insert_by_batchid(), and sub_thandle_register_commit_cb().
static void top_multiple_thandle_put (struct top_multiple_thandle * tmt) [inline, static]
Definition at line 473 of file lustre_update.h.
References top_multiple_thandle::tmt_refcount, and top_multiple_thandle_destroy().
Referenced by distribute_txn_commit_thread(), sub_trans_commit_cb_internal(), and top_trans_stop().
struct thandle* top_trans_create (const struct lu_env * env, struct dt_device * master_dev) [read]
Create the top transaction.
Create the top transaction on the master device. It will create a top thandle and a sub thandle on the master device.
Parameters:
[in] env execution environment
[in] master_dev master_dev the top thandle will be created
Return values:
pointer to the created thandle.
ERR_PTR(errno) if creation failed.
Definition at line 598 of file update_trans.c.
References dt_trans_create(), OBD_ALLOC_GFP, OBD_FREE_PTR, thandle::th_tags, thandle::th_top, thandle::th_wait_submit, top_thandle::tt_master_sub_thandle, and top_thandle::tt_super.
Referenced by distribute_txn_replay_handle(), and lod_trans_create().
int top_trans_start (const struct lu_env * env, struct dt_device * master_dev, struct thandle * th)
start the top transaction.
Start all of its sub transactions, then start master sub transaction.
Parameters:
[in] env execution environment
[in] master_dev master_dev the top thandle will be start
[in] th top thandle
Return values:
0 if transaction start succeeds.
negative errno if start fails.
Definition at line 784 of file update_trans.c.
References dt_trans_start(), ENTRY, GOTO, LASSERT, list_for_each_entry, prepare_multiple_node_trans(), RETURN, sub_thandle::st_started, sub_thandle::st_sub_th, thandle::th_dev, thandle::th_local, thandle::th_result, thandle::th_sync, thandle::th_tags, top_multiple_thandle::tmt_sub_thandle_list, top_thandle::tt_master_sub_thandle, top_thandle::tt_multiple_thandle, and top_thandle::tt_super.
Referenced by distribute_txn_replay_handle(), and lod_trans_start().
int top_trans_stop (const struct lu_env * env, struct dt_device * master_dev, struct thandle * th)
Stop the top transaction.
Stop the transaction on the master device first, then stop transactions on other sub devices.
Parameters:
[in] env execution environment
[in] master_dev master_dev the top thandle will be created
[in] th top thandle
Return values:
0 if stop transaction succeeds.
negative errno if stop transaction fails.
Definition at line 935 of file update_trans.c.
References CERROR, dt_device::dd_lu_dev, dt_trans_stop(), ENTRY, GOTO, LASSERT, lu_device::ld_obd, likely, list_empty(), list_for_each_entry, lookup_sub_thandle(), lur, llog_update_record::lur_update_rec, OBD_FREE_PTR, obd_device::obd_name, prepare_writing_updates(), RETURN, sub_thandle::st_dt, sub_thandle::st_started, sub_thandle::st_sub_th, sub_trans_commit_cb_internal(), sub_updates_write(), tgt_th_info(), thandle::th_dev, thandle::th_local, thandle::th_result, thandle::th_sync, thandle::th_tags, top_multiple_thandle::tmt_commit_list, top_multiple_thandle::tmt_master_sub_dt, top_multiple_thandle::tmt_result, top_multiple_thandle::tmt_sub_thandle_list, top_multiple_thandle::tmt_update_records, top_check_write_updates(), top_multiple_thandle_put(), top_trans_wait_result(), top_thandle::tt_master_sub_thandle, top_thandle::tt_multiple_thandle, top_thandle::tt_super, tgt_thread_info::tti_transno, thandle_update_records::tur_update_params, thandle_update_records::tur_update_records, unlikely, update_records::ur_master_transno, and update_records::ur_param_count.
Referenced by distribute_txn_replay_handle(), and lod_trans_stop().
int tur_update_extend (struct thandle_update_records * tur, size_t new_op_size, size_t new_param_size)
Extend update records.
Extend update records in thandle to make sure it is able to hold the update with certain update_op and params size.
Parameters:
[in] tur thandle_update_records to be extend
[in] new_op_size update_op size of the update record
[in] new_param_size params size of the update record
Return values:
0 if the update_records is being extended.
negative errno if the update_records is not being extended.
Definition at line 1054 of file update_records.c.
References ENTRY, llog_update_record_size(), RETURN, thandle_update_records::tur_update_param_count, thandle_update_records::tur_update_params, thandle_update_records::tur_update_params_buf_size, tur_update_params_extend(), thandle_update_records::tur_update_records, thandle_update_records::tur_update_records_buf_size, tur_update_records_extend(), UPDATE_PARAMS_BUFFER_SIZE, update_params_size(), and UPDATE_RECORDS_BUFFER_SIZE.
int tur_update_params_extend (struct thandle_update_records * tur, size_t new_size)
Extend update params.
Extend update_params to the new size in thandle_update_records.
Parameters:
[in] tur thandle_update_records where update_params will be extended.
Return values:
0 if extension succeeds.
negative errno if extension fails.
Definition at line 1126 of file update_records.c.
References OBD_ALLOC_LARGE, OBD_FREE_LARGE, thandle_update_records::tur_update_params, and thandle_update_records::tur_update_params_buf_size.
Referenced by tur_update_extend().
int tur_update_records_extend (struct thandle_update_records * tur, size_t new_size)
Extend update records.
Extend update_records to the new size in thandle_update_records.
Parameters:
[in] tur thandle_update_records where update_records will be extended.
Return values:
0 if extension succeeds.
negative errno if extension fails.
Definition at line 1017 of file update_records.c.
References OBD_ALLOC_LARGE, OBD_FREE_LARGE, thandle_update_records::tur_update_records, and thandle_update_records::tur_update_records_buf_size.
Referenced by prepare_writing_updates(), and tur_update_extend().
static struct update_op* update_op_next_op (const struct update_op * uop) [static, read]
Definition at line 105 of file lustre_update.h.
References update_op::uop_param_count, and update_op_size().
Referenced by sub_updates_write(), update_ops_get_op(), update_ops_size(), update_records_dump(), and update_recovery_exec().
static size_t update_op_size (unsigned int param_count) [inline, static]
Definition at line 99 of file lustre_update.h.
References offsetof.
Referenced by update_op_next_op(), update_ops_size(), update_records_update_pack(), and update_records_update_size().
const char* update_op_str (__u16 opcode)
Definition at line 43 of file out_lib.c.
Referenced by object_update_request_dump(), update_records_dump(), and update_records_update_pack().
static struct update_op* update_ops_get_op (const struct update_ops * ops, unsigned int index, unsigned int update_count) [static, read]
Definition at line 162 of file lustre_update.h.
References update_ops::uops_op, and update_op_next_op().
Referenced by update_records_update_pack().
static size_t update_ops_size (const struct update_ops * ops, unsigned int update_count) [inline, static]
Definition at line 111 of file lustre_update.h.
References update_ops::uops_op, update_op_next_op(), and update_op_size().
Referenced by update_records_get_params(), and update_records_size().
static struct object_update_param* update_params_get_param (const struct update_params * params, unsigned int index, unsigned int param_count) [static, read]
Definition at line 64 of file lustre_update.h.
References object_update_param_size(), and update_params::up_params.
Referenced by update_params_get_param_buf(), update_records_dump(), and update_records_param_pack().
static void* update_params_get_param_buf (const struct update_params * params, __u16 index, unsigned int param_count, __u16 * size) [inline, static]
Definition at line 82 of file lustre_update.h.
References object_update_param::oup_buf, object_update_param::oup_len, and update_params_get_param().
Referenced by update_recovery_attr_set(), update_recovery_create(), update_recovery_index_delete(), update_recovery_index_insert(), update_recovery_write(), update_recovery_xattr_del(), and update_recovery_xattr_set().
static size_t update_params_size (const struct update_params * params, unsigned int param_count) [inline, static]
Definition at line 45 of file lustre_update.h.
References object_update_param_size(), size, and update_params::up_params.
Referenced by prepare_writing_updates(), tur_update_extend(), update_records_param_pack(), and update_records_size().
int update_records_attr_set_pack (const struct lu_env * env, struct update_ops * ops, unsigned int * op_count, size_t * max_ops_size, struct update_params * params, unsigned int * param_count, size_t * max_param_size, const struct lu_fid * fid, const struct lu_attr * attr)
Pack attr set update.
Pack attr_set update into update records.
Parameters:
[in] env execution environment
[in] ops ur_ops in update records
in|out] op_count pointer to the count of ops
in|out] max_op_size maximum size of the update
[in] params ur_params in update records
in|out] param_count pointer to the count of params
in|out] max_param_size maximum size of the parameter
[in] fid FID of the object to set attr
[in] attr attribute of attr set
Return values:
0 if packing succeeds.
negative errno if packing fails.
Definition at line 410 of file update_records.c.
References lu_attr::la_valid, lustre_set_wire_obdo(), obdo::o_valid, obdo_from_la(), OUT_ATTR_SET, size, update_env_info(), update_records_update_pack(), and update_thread_info::uti_obdo.
size_t update_records_attr_set_size (const struct lu_env * env, const struct lu_fid * fid, const struct lu_attr * attr)
Calculate attr set update size.
Parameters:
[in] env execution environment
[in] ops ur_ops in update records
[in] fid FID of the object to set attr
[in] attr attribute of attr set
Return values:
size of attr set update.
Definition at line 382 of file update_records.c.
References size, and update_records_update_size().
int update_records_create_pack (const struct lu_env * env, struct update_ops * ops, unsigned int * op_count, size_t * max_ops_size, struct update_params * params, unsigned int * param_count, size_t * max_param_size, const struct lu_fid * fid, const struct lu_attr * attr, const struct dt_allocation_hint * hint, struct dt_object_format * dof)
Pack create update.
Pack create update into update records.
Parameters:
[in] env execution environment
[in] ops ur_ops in update records
in|out] op_count pointer to the count of ops
in|out] max_op_size maximum size of the update
[in] params ur_params in update records
in|out] param_count pointer to the count of params
in|out] max_param_size maximum size of the parameter
[in] fid FID of the object to be created
[in] attr attribute of the object to be created
[in] hint creation hint
[in] dof creation format information
Return values:
0 if packing succeeds.
negative errno if packing fails.
Definition at line 327 of file update_records.c.
References dt_allocation_hint::dah_parent, dt_object::do_lu, fid_cpu_to_le(), lu_attr::la_valid, lu_object_fid(), lustre_set_wire_obdo(), obdo::o_valid, obdo_from_la(), OUT_CREATE, update_env_info(), update_records_update_pack(), and update_thread_info::uti_obdo.
size_t update_records_create_size (const struct lu_env * env, const struct lu_fid * fid, const struct lu_attr * attr, const struct dt_allocation_hint * hint, struct dt_object_format * dof)
Calculate create update size.
Parameters:
[in] env execution environment
[in] ops ur_ops in update records
[in] fid FID of the object to be created
[in] attr attribute of the object to be created
[in] hint creation hint
[in] dof creation format information
Return values:
size of create update.
Definition at line 284 of file update_records.c.
References dt_allocation_hint::dah_parent, and update_records_update_size().
static struct update_params* update_records_get_params (const struct update_records * record) [static, read]
Definition at line 126 of file lustre_update.h.
References offsetof, update_ops_size(), update_records::ur_ops, and update_records::ur_update_count.
Referenced by prepare_writing_updates(), sub_updates_write(), update_records_dump(), update_records_size(), and update_recovery_exec().
int update_records_index_delete_pack (const struct lu_env * env, struct update_ops * ops, unsigned int * op_count, size_t * max_ops_size, struct update_params * params, unsigned int * param_count, size_t * max_param_size, const struct lu_fid * fid, const struct dt_key * key)
Pack index delete update.
Pack index delete update into update records.
Parameters:
[in] env execution environment
[in] ops ur_ops in update records
in|out] op_count pointer to the count of ops
in|out] max_op_size maximum size of the update
[in] params ur_params in update records
in|ount] param_count pointer to the count of params
in|out] max_param_size maximum size of the parameter
[in] fid FID of the object to delete index
[in] key key of deletion
Return values:
0 if packing succeeds.
negative errno if packing fails.
Definition at line 716 of file update_records.c.
References OUT_INDEX_DELETE, size, and update_records_update_pack().
size_t update_records_index_delete_size (const struct lu_env * env, const struct lu_fid * fid, const struct dt_key * key)
Calculate index delete update size.
Parameters:
[in] env execution environment
[in] fid FID of the object to delete index
[in] key key of deletion
Return values:
the size of index delete update
Definition at line 688 of file update_records.c.
References size, and update_records_update_size().
int update_records_index_insert_pack (const struct lu_env * env, struct update_ops * ops, unsigned int * op_count, size_t * max_ops_size, struct update_params * params, unsigned int * param_count, size_t * max_param_size, const struct lu_fid * fid, const struct dt_rec * rec, const struct dt_key * key)
Pack index insert update.
Pack index insert update into update records.
Parameters:
[in] env execution environment
[in] ops ur_ops in update records
[in] op_count pointer to the count of ops
in|out] max_op_size maximum size of the update
[in] params ur_params in update records
[in] param_count pointer to the count of params
in|out] max_param_size maximum size of the parameter
[in] fid FID of the object to insert index
[in] rec record of insertion
[in] key key of insertion
Return values:
0 if packing succeeds.
negative errno if packing fails.
Definition at line 649 of file update_records.c.
References cpu_to_le32, fid_cpu_to_le(), OUT_INDEX_INSERT, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, and update_records_update_pack().
size_t update_records_index_insert_size (const struct lu_env * env, const struct lu_fid * fid, const struct dt_rec * rec, const struct dt_key * key)
Calculate index insert update size.
Parameters:
[in] env execution environment
[in] fid FID of the object to insert index
[in] rec record of insertion
[in] key key of insertion
Return values:
the size of index insert update.
Definition at line 618 of file update_records.c.
References update_records_index_insert_size(), and update_records_update_size().
Referenced by update_records_index_insert_size().
int update_records_noop_pack (const struct lu_env * env, struct update_ops * ops, unsigned int * op_count, size_t * max_ops_size, struct update_params * params, unsigned int * param_count, size_t * max_param_size, const struct lu_fid * fid)
Pack noop update.
Pack no op update into update records. Note: no op means the update does not need do anything, which is only used in test case to verify large size record.
Parameters:
[in] env execution environment
[in] ops ur_ops in update records
in|out] op_count pointer to the count of ops
in|out] max_op_size maximum size of the update
[in] params ur_params in update records
in|out] param_count pointer to the count of params
in|out] max_param_size maximum size of the parameter
[in] fid FID of the object to add reference
Return values:
0 if packing succeeds.
negative errno if packing fails.
Definition at line 499 of file update_records.c.
References OUT_NOOP, and update_records_update_pack().
int update_records_object_destroy_pack (const struct lu_env * env, struct update_ops * ops, unsigned int * op_count, size_t * max_ops_size, struct update_params * params, unsigned int * param_count, size_t * max_param_size, const struct lu_fid * fid)
Pack object destroy update.
Pack object destroy update into update records.
Parameters:
[in] env execution environment
[in] ops ur_ops in update records
in|out] op_count pointer to the count of ops
in|out] max_op_size maximum size of the update
[in] params ur_params in update records
in|out] param_count pointer to the count of params
in|out] max_param_size maximum size of the parameter
[in] fid FID of the object to delete reference
Return values:
0 if packing succeeds.
negative errno if packing fails.
Definition at line 593 of file update_records.c.
References OUT_DESTROY, and update_records_update_pack().
size_t update_records_object_destroy_size (const struct lu_env * env, const struct lu_fid * fid)
Calculate object destroy update size.
Parameters:
[in] env execution environment
[in] fid FID of the object to delete reference
Return values:
size of object destroy update.
Definition at line 569 of file update_records.c.
References update_records_update_size().
int update_records_punch_pack (const struct lu_env * env, struct update_ops * ops, unsigned int * op_count, size_t * max_ops_size, struct update_params * params, unsigned int * param_count, size_t * max_param_size, const struct lu_fid * fid, __u64 start, __u64 end)
Pack punch.
Pack punch update into update records.
Parameters:
[in] env execution environment
[in] ops ur_ops in update records
in|out] op_count pointer to the count of ops
in|out] max_op_size maximum size of the update
[in] params ur_params in update records
in|out] param_count pointer to the count of params
in|out] max_param_size maximum size of the parameter
[in] fid FID of the object to write into
[in] start start offset of punch
[in] end end offet of punch
Return values:
0 if packing succeeds.
negative errno if packing fails.
Definition at line 958 of file update_records.c.
References cpu_to_le64, OUT_PUNCH, and update_records_update_pack().
size_t update_records_punch_size (const struct lu_env * env, const struct lu_fid * fid, __u64 start, __u64 end)
Calculate size of punch update.
Parameters:
[in] env execution environment
[in] fid FID of the object to write into
[in] start start offset of punch
[in] end end offet of punch
Return values:
size of update punch.
Definition at line 929 of file update_records.c.
References update_records_update_size().
int update_records_ref_add_pack (const struct lu_env * env, struct update_ops * ops, unsigned int * op_count, size_t * max_ops_size, struct update_params * params, unsigned int * param_count, size_t * max_param_size, const struct lu_fid * fid)
Pack ref add update.
Pack ref add update into update records.
Parameters:
[in] env execution environment
[in] ops ur_ops in update records
in|out] op_count pointer to the count of ops
in|out] max_op_size maximum size of the update
[in] params ur_params in update records
in|out] param_count pointer to the count of params
in|out] max_param_size maximum size of the parameter
[in] fid FID of the object to add reference
Return values:
0 if packing succeeds.
negative errno if packing fails.
Definition at line 465 of file update_records.c.
References OUT_REF_ADD, and update_records_update_pack().
size_t update_records_ref_add_size (const struct lu_env * env, const struct lu_fid * fid)
Calculate ref add update size.
Parameters:
[in] env execution environment
[in] fid FID of the object to add reference
Return values:
size of ref_add udpate.
Definition at line 441 of file update_records.c.
References update_records_update_size().
int update_records_ref_del_pack (const struct lu_env * env, struct update_ops * ops, unsigned int * op_count, size_t * max_ops_size, struct update_params * params, unsigned int * param_count, size_t * max_param_size, const struct lu_fid * fid)
Pack ref del update.
Pack ref del update into update records.
Parameters:
[in] env execution environment
[in] ops ur_ops in update records
in|out] op_count pointer to the count of ops
in|out] max_op_size maximum size of the update
[in] params ur_params in update records
[in] param_count pointer to the count of params
in|out] max_param_size maximum size of the parameter
[in] fid FID of the object to delete reference
Return values:
0 if packing succeeds.
negative errno if packing fails.
Definition at line 546 of file update_records.c.
References OUT_REF_DEL, and update_records_update_pack().
size_t update_records_ref_del_size (const struct lu_env * env, const struct lu_fid * fid)
Calculate ref del update size.
Parameters:
[in] env execution environment
[in] fid FID of the object to delete reference
Return values:
size of ref_del update.
Definition at line 522 of file update_records.c.
References update_records_update_size().
static size_t update_records_size (const struct update_records * record) [inline, static]
Definition at line 134 of file lustre_update.h.
References cfs_size_round(), offsetof, update_ops_size(), update_params_size(), update_records_get_params(), update_records::ur_ops, update_records::ur_param_count, and update_records::ur_update_count.
Referenced by dtrq_append_updates(), llog_update_record_size(), and lustre_swab_llog_rec().
int update_records_write_pack (const struct lu_env * env, struct update_ops * ops, unsigned int * op_count, size_t * max_ops_size, struct update_params * params, unsigned int * param_count, size_t * max_param_size, const struct lu_fid * fid, const struct lu_buf * buf, __u64 pos)
Pack write update.
Pack write update into update records.
Parameters:
[in] env execution environment
[in] ops ur_ops in update records
in|out] op_count pointer to the count of ops
in|out] max_op_size maximum size of the update
[in] params ur_params in update records
in|out] param_count pointer to the count of params
in|out] max_param_size maximum size of the parameter
[in] fid FID of the object to write into
[in] buf buffer to write which includes an embedded size field
[in] pos offet in the object to start writing at
Return values:
0 if packing succeeds.
negative errno if packing fails.
Definition at line 896 of file update_records.c.
References cpu_to_le64, lu_buf::lb_buf, lu_buf::lb_len, OUT_WRITE, update_records_update_pack(), and update_records_write_pack().
Referenced by update_records_write_pack().
size_t update_records_write_size (const struct lu_env * env, const struct lu_fid * fid, const struct lu_buf * buf, __u64 pos)
Calculate write update size.
Parameters:
[in] env execution environment
[in] fid FID of the object to write into
[in] buf buffer to write which includes an embedded size field
[in] pos offet in the object to start writing at
Return values:
size of write udpate.
Definition at line 866 of file update_records.c.
References lu_buf::lb_len, update_records_update_size(), and update_records_write_size().
Referenced by update_records_write_size().
int update_records_xattr_del_pack (const struct lu_env * env, struct update_ops * ops, unsigned int * op_count, size_t * max_ops_size, struct update_params * params, unsigned int * param_count, size_t * max_param_size, const struct lu_fid * fid, const char * name)
Pack xattr delete update.
Pack xattr delete update into update records.
Parameters:
[in] env execution environment
[in] ops ur_ops in update records
in|out] op_count pointer to the count of ops
in|out] max_op_size maximum size of the update
[in] params ur_params in update records
in|out] param_count pointer to the count of params
in|out] max_param_size maximum size of the parameter
[in] fid FID of the object to delete xattr
[in] name name of the xattr
Return values:
0 if packing succeeds.
negative errno if packing fails.
Definition at line 837 of file update_records.c.
References OUT_XATTR_DEL, size, and update_records_update_pack().
size_t update_records_xattr_del_size (const struct lu_env * env, const struct lu_fid * fid, const char * name)
Calculate xattr delete update size.
Parameters:
[in] env execution environment
[in] fid FID of the object to delete xattr
[in] name name of the xattr
Return values:
size of xattr delet updatee.
Definition at line 809 of file update_records.c.
References size, and update_records_update_size().
int update_records_xattr_set_pack (const struct lu_env * env, struct update_ops * ops, unsigned int * op_count, size_t * max_ops_size, struct update_params * params, unsigned int * param_count, size_t * max_param_size, const struct lu_fid * fid, const struct lu_buf * buf, const char * name, __u32 flag)
Pack xattr set update.
Pack xattr set update into update records.
Parameters:
[in] env execution environment
[in] ops ur_ops in update records
in|out] op_count pointer to the count of ops
in|out] max_op_size maximum size of the update
[in] params ur_params in update records
in|out] param_count pointer to the count of params
in|out] max_param_size maximum size of the parameter
[in] fid FID of the object to set xattr
[in] buf xattr to be set
[in] name name of the xattr
[in] flag flag for setting xattr
Return values:
0 if packing succeeds.
negative errno if packing fails.
Definition at line 777 of file update_records.c.
References cpu_to_le32, lu_buf::lb_buf, lu_buf::lb_len, OUT_XATTR_SET, update_records_update_pack(), and update_records_xattr_set_pack().
Referenced by update_records_xattr_set_pack().
size_t update_records_xattr_set_size (const struct lu_env * env, const struct lu_fid * fid, const struct lu_buf * buf, const char * name, __u32 flag)
Calculate xattr set size.
Parameters:
[in] env execution environment
[in] fid FID of the object to set xattr
[in] buf xattr to be set
[in] name name of the xattr
[in] flag flag for setting xattr
Return values:
size of xattr set update.
Definition at line 746 of file update_records.c.
References lu_buf::lb_len, update_records_update_size(), and update_records_xattr_set_size().
Referenced by update_records_xattr_set_size().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.