Lustre: lustre/utils/wirecheck.c File Reference
lustre/utils/wirecheck.c File Reference
#include <stdio.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <lustre/lustre_idl.h>
#include <lustre/lustre_lfsck_user.h>
#include <lustre_disk.h>
Data Structures
struct posix_acl_xattr_entry
struct posix_acl_xattr_header
Defines
#define BLANK_LINE()
#define COMMENT(c)
#define STRINGIFY(a) #a
#define CHECK_CDEFINE(a) printf(" CLASSERT("#a" == "STRINGIFY(a) ");\n")
#define CHECK_CVALUE(a) printf(" CLASSERT("#a" == %lld);\n", (long long)a)
#define CHECK_CVALUE_X(a) printf(" CLASSERT("#a" == 0x%.8x);\n", a)
#define CHECK_DEFINE(a)
#define CHECK_DEFINE_X(a)
#define CHECK_DEFINE_64X(a)
#define CHECK_VALUE(a)
#define CHECK_VALUE_X(a)
#define CHECK_VALUE_O(a)
#define CHECK_VALUE_64X(a)
#define CHECK_VALUE_64O(a)
#define CHECK_MEMBER_OFFSET(s, m)
#define CHECK_MEMBER_OFFSET_TYPEDEF(s, m)
#define CHECK_MEMBER_SIZEOF(s, m)
#define CHECK_MEMBER_SIZEOF_TYPEDEF(s, m)
#define CHECK_MEMBER(s, m)
#define CHECK_MEMBER_TYPEDEF(s, m)
#define CHECK_STRUCT(s)
#define CHECK_STRUCT_TYPEDEF(s)
#define CHECK_UNION(s)
#define CHECK_VALUE_SAME(v1, v2)
#define CHECK_MEMBER_SAME(s1, s2, m)
Functions
static void check_lu_seq_range (void)
static void check_lustre_mdt_attrs (void)
static void check_hsm_attrs (void)
static void check_ost_id (void)
static void check_lu_dirent (void)
static void check_luda_type (void)
static void check_lu_dirpage (void)
static void check_lu_ladvise (void)
static void check_lustre_handle (void)
static void check_lustre_msg_v2 (void)
static void check_ptlrpc_body (void)
static void check_obd_connect_data (void)
static void check_obdo (void)
static void check_lov_ost_data_v1 (void)
static void check_lov_mds_md_v1 (void)
static void check_lov_mds_md_v3 (void)
static void check_lmv_mds_md_v1 (void)
static void check_obd_statfs (void)
static void check_obd_ioobj (void)
static void check_obd_quotactl (void)
static void check_obd_idx_read (void)
static void check_niobuf_remote (void)
static void check_ost_body (void)
static void check_ll_fid (void)
static void check_mdt_body (void)
static void check_mdt_ioepoch (void)
static void check_mdt_remote_perm (void)
static void check_mdt_rec_setattr (void)
static void check_mdt_rec_create (void)
static void check_mdt_rec_link (void)
static void check_mdt_rec_unlink (void)
static void check_mdt_rec_rename (void)
static void check_mdt_rec_setxattr (void)
static void check_mdt_rec_reint (void)
static void check_lmv_desc (void)
static void check_lov_desc (void)
static void check_ldlm_res_id (void)
static void check_ldlm_extent (void)
static void check_ldlm_inodebits (void)
static void check_ldlm_flock (void)
static void check_ldlm_intent (void)
static void check_ldlm_resource_desc (void)
static void check_ldlm_lock_desc (void)
static void check_ldlm_request (void)
static void check_ldlm_reply (void)
static void check_ldlm_ost_lvb_v1 (void)
static void check_ldlm_ost_lvb (void)
static void check_ldlm_lquota_lvb (void)
static void check_ldlm_gl_lquota_desc (void)
static void check_mgs_send_param (void)
static void check_cfg_marker (void)
static void check_llog_logid (void)
static void check_llog_catid (void)
static void check_llog_rec_hdr (void)
static void check_llog_rec_tail (void)
static void check_llog_logid_rec (void)
static void check_llog_unlink_rec (void)
static void check_llog_unlink64_rec (void)
static void check_llog_setattr64_rec (void)
static void check_llog_size_change_rec (void)
static void check_changelog_rec (void)
static void check_changelog_ext_rename (void)
static void check_changelog_ext_jobid (void)
static void check_changelog_setinfo (void)
static void check_llog_changelog_rec (void)
static void check_llog_changelog_user_rec (void)
static void check_llog_gen (void)
static void check_llog_gen_rec (void)
static void check_llog_log_hdr (void)
static void check_llog_cookie (void)
static void check_llogd_body (void)
static void check_llogd_conn_body (void)
static void check_ll_fiemap_info_key (void)
static void check_quota_body (void)
static void check_mgs_target_info (void)
static void check_lustre_capa (void)
static void check_lustre_capa_key (void)
static void check_getinfo_fid2path (void)
static void check_posix_acl_xattr_entry (void)
static void check_posix_acl_xattr_header (void)
static void check_ll_user_fiemap (void)
static void check_ll_fiemap_extent (void)
static void check_link_ea_header (void)
static void check_link_ea_entry (void)
static void check_hsm_user_item (void)
static void check_hsm_user_state (void)
static void check_hsm_action_item (void)
static void check_hsm_action_list (void)
static void check_hsm_progress_kernel (void)
static void check_hsm_progress (void)
static void check_hsm_copy (void)
static void check_layout_intent (void)
static void check_hsm_state_set (void)
static void check_hsm_current_action (void)
static void check_hsm_request (void)
static void check_hsm_user_request (void)
static void check_hsm_user_import (void)
static void check_object_update_param (void)
static void check_object_update (void)
static void check_object_update_request (void)
static void check_object_update_result (void)
static void check_object_update_reply (void)
static void check_out_update_header (void)
static void check_out_update_buffer (void)
static void check_nodemap_cluster_rec (void)
static void check_nodemap_range_rec (void)
static void check_nodemap_id_rec (void)
static void check_nodemap_global_rec (void)
static void check_nodemap_rec (void)
static void check_lfsck_request (void)
static void check_lfsck_reply (void)
static void check_update_params (void)
static void check_update_op (void)
static void check_update_ops (void)
static void check_update_records (void)
static void check_llog_update_record (void)
static void system_string (char *cmdline, char *str, int len)
int main (int argc, char **argv)
Define Documentation
#define BLANK_LINE ()
Value:
do {                                                            \
        printf("\n");                                           \
} while(0)
Definition at line 45 of file wirecheck.c.
Referenced by check_cfg_marker(), check_changelog_ext_jobid(), check_changelog_ext_rename(), check_changelog_rec(), check_changelog_setinfo(), check_getinfo_fid2path(), check_hsm_action_item(), check_hsm_action_list(), check_hsm_attrs(), check_hsm_copy(), check_hsm_current_action(), check_hsm_progress(), check_hsm_progress_kernel(), check_hsm_request(), check_hsm_state_set(), check_hsm_user_import(), check_hsm_user_item(), check_hsm_user_request(), check_hsm_user_state(), check_layout_intent(), check_ldlm_extent(), check_ldlm_flock(), check_ldlm_gl_lquota_desc(), check_ldlm_inodebits(), check_ldlm_intent(), check_ldlm_lock_desc(), check_ldlm_lquota_lvb(), check_ldlm_ost_lvb(), check_ldlm_ost_lvb_v1(), check_ldlm_reply(), check_ldlm_request(), check_ldlm_res_id(), check_ldlm_resource_desc(), check_lfsck_reply(), check_lfsck_request(), check_link_ea_entry(), check_link_ea_header(), check_ll_fid(), check_ll_fiemap_extent(), check_ll_fiemap_info_key(), check_ll_user_fiemap(), check_llog_catid(), check_llog_changelog_rec(), check_llog_changelog_user_rec(), check_llog_cookie(), check_llog_gen(), check_llog_gen_rec(), check_llog_log_hdr(), check_llog_logid(), check_llog_logid_rec(), check_llog_rec_hdr(), check_llog_rec_tail(), check_llog_setattr64_rec(), check_llog_size_change_rec(), check_llog_unlink_rec(), check_llog_update_record(), check_llogd_body(), check_llogd_conn_body(), check_lmv_desc(), check_lmv_mds_md_v1(), check_lnet_hdr(), check_lov_desc(), check_lov_mds_md_v1(), check_lov_mds_md_v3(), check_lov_ost_data_v1(), check_lu_dirent(), check_lu_dirpage(), check_lu_ladvise(), check_lu_seq_range(), check_luda_type(), check_lustre_capa(), check_lustre_capa_key(), check_lustre_handle(), check_lustre_mdt_attrs(), check_lustre_msg_v2(), check_mdt_body(), check_mdt_ioepoch(), check_mdt_rec_create(), check_mdt_rec_link(), check_mdt_rec_reint(), check_mdt_rec_rename(), check_mdt_rec_setattr(), check_mdt_rec_setxattr(), check_mdt_rec_unlink(), check_mdt_remote_perm(), check_mgs_send_param(), check_mgs_target_info(), check_niobuf_remote(), check_nodemap_cluster_rec(), check_nodemap_global_rec(), check_nodemap_id_rec(), check_nodemap_range_rec(), check_nodemap_rec(), check_obd_connect_data(), check_obd_idx_read(), check_obd_ioobj(), check_obd_quotactl(), check_obd_statfs(), check_obdo(), check_object_update(), check_object_update_param(), check_object_update_reply(), check_object_update_request(), check_object_update_result(), check_ost_body(), check_ost_id(), check_out_update_buffer(), check_out_update_header(), check_posix_acl_xattr_entry(), check_posix_acl_xattr_header(), check_ptlrpc_body(), check_quota_body(), check_update_op(), check_update_ops(), check_update_params(), check_update_records(), and main().
#define CHECK_CDEFINE (a) printf(" CLASSERT("#a" == "STRINGIFY(a) ");\n")
Definition at line 57 of file wirecheck.c.
Referenced by check_link_ea_header(), check_ll_fiemap_extent(), check_ll_user_fiemap(), check_lmv_mds_md_v1(), check_lov_desc(), check_lov_mds_md_v1(), check_lov_mds_md_v3(), and check_obd_idx_read().
#define CHECK_CVALUE (a) printf(" CLASSERT("#a" == %lld);\n", (long long)a)
Definition at line 60 of file wirecheck.c.
Referenced by check_ldlm_res_id(), check_llog_logid(), check_llogd_body(), check_lov_mds_md_v3(), check_lustre_capa(), check_lustre_capa_key(), check_mgs_send_param(), check_ptlrpc_body(), and main().
#define CHECK_CVALUE_X (a) printf(" CLASSERT("#a" == 0x%.8x);\n", a)
Definition at line 63 of file wirecheck.c.
Referenced by check_obdo().
#define CHECK_DEFINE (a)
Value:
do {                                                            \
        printf("        LASSERTF("#a" == "STRINGIFY(a)          \
                ", \"found %%lld\\n\",\n                        "\
                "(long long)"#a");\n");                         \
} while(0)
Definition at line 66 of file wirecheck.c.
Referenced by main().
#define CHECK_DEFINE_64X (a)
Value:
do {                                                            \
        printf("        LASSERTF("#a" == "STRINGIFY(a)          \
                ", \"found 0x%%.16llxULL\\n\",\n                "\
                " "#a");\n");                                   \
} while(0)
Definition at line 80 of file wirecheck.c.
Referenced by check_obd_connect_data(), check_obdo(), and main().
#define CHECK_DEFINE_X (a)
Value:
do {                                                            \
        printf("        LASSERTF("#a" == "STRINGIFY(a)          \
                ", \"found 0x%%.8x\\n\",\n              "#a     \
                ");\n");                                        \
} while(0)
Definition at line 73 of file wirecheck.c.
Referenced by check_hsm_progress(), check_lustre_msg_v2(), check_mdt_body(), check_niobuf_remote(), check_obd_quotactl(), and check_ptlrpc_body().
#define CHECK_MEMBER (s, m)
Value:
do {                                                            \
        CHECK_MEMBER_OFFSET(s, m);                              \
        CHECK_MEMBER_SIZEOF(s, m);                              \
} while(0)
Definition at line 142 of file wirecheck.c.
Referenced by check_cfg_marker(), check_changelog_ext_jobid(), check_changelog_ext_rename(), check_changelog_rec(), check_changelog_setinfo(), check_getinfo_fid2path(), check_hsm_action_item(), check_hsm_action_list(), check_hsm_attrs(), check_hsm_copy(), check_hsm_current_action(), check_hsm_progress(), check_hsm_progress_kernel(), check_hsm_request(), check_hsm_state_set(), check_hsm_user_import(), check_hsm_user_item(), check_hsm_user_request(), check_hsm_user_state(), check_layout_intent(), check_ldlm_extent(), check_ldlm_flock(), check_ldlm_gl_lquota_desc(), check_ldlm_inodebits(), check_ldlm_intent(), check_ldlm_lock_desc(), check_ldlm_lquota_lvb(), check_ldlm_ost_lvb(), check_ldlm_ost_lvb_v1(), check_ldlm_reply(), check_ldlm_request(), check_ldlm_res_id(), check_ldlm_resource_desc(), check_lfsck_reply(), check_lfsck_request(), check_link_ea_entry(), check_link_ea_header(), check_ll_fid(), check_ll_fiemap_extent(), check_ll_fiemap_info_key(), check_ll_user_fiemap(), check_llog_catid(), check_llog_changelog_rec(), check_llog_changelog_user_rec(), check_llog_cookie(), check_llog_gen(), check_llog_gen_rec(), check_llog_log_hdr(), check_llog_logid(), check_llog_logid_rec(), check_llog_rec_hdr(), check_llog_rec_tail(), check_llog_setattr64_rec(), check_llog_size_change_rec(), check_llog_unlink64_rec(), check_llog_unlink_rec(), check_llog_update_record(), check_llogd_body(), check_llogd_conn_body(), check_lmv_desc(), check_lmv_mds_md_v1(), check_lnet_handle_wire(), check_lnet_hdr(), check_lnet_magicversion(), check_lov_desc(), check_lov_mds_md_v1(), check_lov_mds_md_v3(), check_lov_ost_data_v1(), check_lu_dirent(), check_lu_dirpage(), check_lu_ladvise(), check_lu_seq_range(), check_luda_type(), check_lustre_capa(), check_lustre_capa_key(), check_lustre_handle(), check_lustre_mdt_attrs(), check_lustre_msg_v2(), check_mdt_body(), check_mdt_ioepoch(), check_mdt_rec_create(), check_mdt_rec_link(), check_mdt_rec_reint(), check_mdt_rec_rename(), check_mdt_rec_setattr(), check_mdt_rec_setxattr(), check_mdt_rec_unlink(), check_mdt_remote_perm(), check_mgs_send_param(), check_mgs_target_info(), check_niobuf_remote(), check_nodemap_cluster_rec(), check_nodemap_global_rec(), check_nodemap_id_rec(), check_nodemap_range_rec(), check_obd_connect_data(), check_obd_idx_read(), check_obd_ioobj(), check_obd_quotactl(), check_obd_statfs(), check_obdo(), check_object_update(), check_object_update_param(), check_object_update_reply(), check_object_update_request(), check_object_update_result(), check_ost_body(), check_ost_id(), check_out_update_buffer(), check_out_update_header(), check_ptlrpc_body(), check_quota_body(), check_update_op(), check_update_ops(), check_update_params(), and check_update_records().
#define CHECK_MEMBER_OFFSET (s, m)
Value:
do {                                                            \
        CHECK_VALUE((int)offsetof(struct s, m));                \
} while(0)
Definition at line 122 of file wirecheck.c.
#define CHECK_MEMBER_OFFSET_TYPEDEF (s, m)
Value:
do {                                                            \
        CHECK_VALUE((int)offsetof(s, m));                       \
} while(0)
Definition at line 127 of file wirecheck.c.
#define CHECK_MEMBER_SAME (s1, s2, m)
Value:
do {                                                            \
        CHECK_VALUE_SAME((int)offsetof(struct s1, m),           \
                         (int)offsetof(struct s2, m));          \
        CHECK_VALUE_SAME((int)sizeof(((struct s1 *)0)->m),      \
                         (int)sizeof(((struct s2 *)0)->m));     \
} while (0)
Definition at line 179 of file wirecheck.c.
Referenced by check_ptlrpc_body().
#define CHECK_MEMBER_SIZEOF (s, m)
Value:
do {                                                            \
        CHECK_VALUE((int)sizeof(((struct s *)0)->m));           \
} while(0)
Definition at line 132 of file wirecheck.c.
#define CHECK_MEMBER_SIZEOF_TYPEDEF (s, m)
Value:
do {                                                            \
        CHECK_VALUE((int)sizeof(((s *)0)->m));                  \
} while(0)
Definition at line 137 of file wirecheck.c.
#define CHECK_MEMBER_TYPEDEF (s, m)
Value:
do {                                                            \
        CHECK_MEMBER_OFFSET_TYPEDEF(s, m);                      \
        CHECK_MEMBER_SIZEOF_TYPEDEF(s, m);                      \
} while(0)
Definition at line 148 of file wirecheck.c.
Referenced by check_posix_acl_xattr_entry(), and check_posix_acl_xattr_header().
#define CHECK_STRUCT (s)
Value:
do {                                                            \
        COMMENT("Checks for struct "#s);                        \
                CHECK_VALUE((int)sizeof(struct s));             \
} while(0)
Definition at line 154 of file wirecheck.c.
Referenced by check_cfg_marker(), check_changelog_ext_jobid(), check_changelog_ext_rename(), check_changelog_rec(), check_changelog_setinfo(), check_getinfo_fid2path(), check_hsm_action_item(), check_hsm_action_list(), check_hsm_attrs(), check_hsm_current_action(), check_hsm_progress(), check_hsm_progress_kernel(), check_hsm_request(), check_hsm_state_set(), check_hsm_user_import(), check_hsm_user_item(), check_hsm_user_request(), check_hsm_user_state(), check_layout_intent(), check_ldlm_extent(), check_ldlm_flock(), check_ldlm_gl_lquota_desc(), check_ldlm_inodebits(), check_ldlm_intent(), check_ldlm_lock_desc(), check_ldlm_lquota_lvb(), check_ldlm_ost_lvb(), check_ldlm_ost_lvb_v1(), check_ldlm_reply(), check_ldlm_request(), check_ldlm_res_id(), check_ldlm_resource_desc(), check_lfsck_reply(), check_lfsck_request(), check_link_ea_entry(), check_link_ea_header(), check_ll_fid(), check_ll_fiemap_extent(), check_ll_fiemap_info_key(), check_ll_user_fiemap(), check_llog_catid(), check_llog_changelog_rec(), check_llog_changelog_user_rec(), check_llog_cookie(), check_llog_gen(), check_llog_gen_rec(), check_llog_log_hdr(), check_llog_logid(), check_llog_logid_rec(), check_llog_rec_hdr(), check_llog_rec_tail(), check_llog_setattr64_rec(), check_llog_size_change_rec(), check_llog_unlink64_rec(), check_llog_unlink_rec(), check_llog_update_record(), check_llogd_body(), check_llogd_conn_body(), check_lmv_desc(), check_lmv_mds_md_v1(), check_lnet_handle_wire(), check_lnet_hdr(), check_lnet_magicversion(), check_lov_desc(), check_lov_mds_md_v1(), check_lov_mds_md_v3(), check_lov_ost_data_v1(), check_lu_dirent(), check_lu_dirpage(), check_lu_ladvise(), check_lu_seq_range(), check_luda_type(), check_lustre_capa(), check_lustre_capa_key(), check_lustre_handle(), check_lustre_mdt_attrs(), check_lustre_msg_v2(), check_mdt_body(), check_mdt_ioepoch(), check_mdt_rec_create(), check_mdt_rec_link(), check_mdt_rec_reint(), check_mdt_rec_rename(), check_mdt_rec_setattr(), check_mdt_rec_setxattr(), check_mdt_rec_unlink(), check_mdt_remote_perm(), check_mgs_send_param(), check_mgs_target_info(), check_niobuf_remote(), check_nodemap_cluster_rec(), check_nodemap_global_rec(), check_nodemap_id_rec(), check_nodemap_range_rec(), check_obd_connect_data(), check_obd_idx_read(), check_obd_ioobj(), check_obd_quotactl(), check_obd_statfs(), check_obdo(), check_object_update(), check_object_update_param(), check_object_update_reply(), check_object_update_request(), check_object_update_result(), check_ost_body(), check_ost_id(), check_out_update_buffer(), check_out_update_header(), check_ptlrpc_body(), check_quota_body(), check_update_op(), check_update_ops(), check_update_params(), check_update_records(), and main().
#define CHECK_STRUCT_TYPEDEF (s)
Value:
do {                                                            \
        COMMENT("Checks for type "#s);                          \
                CHECK_VALUE((int)sizeof(s));                    \
} while(0)
Definition at line 160 of file wirecheck.c.
Referenced by check_posix_acl_xattr_entry(), and check_posix_acl_xattr_header().
#define CHECK_UNION (s)
Value:
do {                                                            \
        COMMENT("Checks for union "#s);                         \
        CHECK_VALUE((int)sizeof(union s));                      \
} while(0)
Definition at line 166 of file wirecheck.c.
Referenced by check_lu_dirpage(), check_nodemap_rec(), and check_obd_quotactl().
#define CHECK_VALUE (a)
Value:
do {                                                            \
        printf("        LASSERTF("#a                            \
                " == %lld, \"found %%lld\\n\",\n                "\
                " (long long)"#a");\n", (long long)a);          \
} while(0)
Definition at line 87 of file wirecheck.c.
Referenced by check_layout_intent(), check_ldlm_intent(), check_ldlm_lquota_lvb(), check_lfsck_request(), check_lu_dirpage(), check_lu_seq_range(), check_obd_idx_read(), check_obd_ioobj(), check_obd_quotactl(), check_ost_id(), check_ptlrpc_body(), and main().
#define CHECK_VALUE_64O (a)
Value:
do {                                                            \
        printf("        LASSERTF("#a" == 0%.22lloULL, "         \
                "\"found 0%%.22lloULL\\n\",\n                   "\
                "(long long)"#a");\n", (long long)a);           \
} while(0)
Definition at line 115 of file wirecheck.c.
Referenced by check_mdt_body().
#define CHECK_VALUE_64X (a)
Value:
do {                                                            \
        printf("        LASSERTF("#a" == 0x%.16llxULL, "        \
                "\"found 0x%%.16llxULL\\n\",\n                  "\
                "(long long)"#a");\n", (long long)a);           \
} while(0)
Definition at line 108 of file wirecheck.c.
Referenced by check_ost_id(), and main().
#define CHECK_VALUE_O (a)
Value:
do {                                                            \
        printf("        LASSERTF("#a                            \
                " == 0%.11oUL, \"found 0%%.11oUL\\n\",\n        "\
                "       "#a");\n", a);                          \
} while(0)
Definition at line 101 of file wirecheck.c.
Referenced by check_mdt_body().
#define CHECK_VALUE_SAME (v1, v2)
Value:
do {                                                            \
        printf("\tLASSERTF("#v1" == "#v2", "                    \
                "\"%%d != %%d\\n\",\n"                          \
                "\t\t "#v1", "#v2");\n");                       \
} while (0)
Definition at line 172 of file wirecheck.c.
#define CHECK_VALUE_X (a)
Value:
do {                                                            \
        printf("        LASSERTF("#a                            \
                " == 0x%.8xUL, \"found 0x%%.8xUL\\n\",\n        "\
                "       (unsigned)"#a");\n", (unsigned)a);      \
} while(0)
Definition at line 94 of file wirecheck.c.
Referenced by check_hsm_request(), check_lfsck_request(), check_lov_mds_md_v3(), check_lu_dirent(), check_lustre_mdt_attrs(), check_mdt_body(), check_mdt_remote_perm(), check_obd_connect_data(), check_ost_id(), check_ptlrpc_body(), check_update_records(), and main().
#define COMMENT (c)
Value:
do {                                                            \
        printf("        /* "c" */\n");                          \
} while(0)
Definition at line 50 of file wirecheck.c.
Referenced by check_lnet_hdr(), and main().
#define STRINGIFY (a) #a
Definition at line 55 of file wirecheck.c.
Function Documentation
static void check_cfg_marker (void) [static]
Definition at line 1460 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_changelog_ext_jobid (void) [static]
Definition at line 1617 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_changelog_ext_rename (void) [static]
Definition at line 1608 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_changelog_rec (void) [static]
Definition at line 1593 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_changelog_setinfo (void) [static]
Definition at line 1625 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_getinfo_fid2path (void) [static]
Definition at line 1827 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_hsm_action_item (void) [static]
Definition at line 1966 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_hsm_action_list (void) [static]
Definition at line 1981 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_hsm_attrs (void) [static]
Definition at line 221 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_hsm_copy (void) [static]
Definition at line 2025 of file wirecheck.c.
References BLANK_LINE, and CHECK_MEMBER.
Referenced by main().
static void check_hsm_current_action (void) [static]
Definition at line 2063 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_hsm_progress (void) [static]
Definition at line 2010 of file wirecheck.c.
References BLANK_LINE, CHECK_DEFINE_X, CHECK_MEMBER, CHECK_STRUCT, HP_FLAG_COMPLETED, and HP_FLAG_RETRY.
Referenced by main().
static void check_hsm_progress_kernel (void) [static]
Definition at line 1995 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_hsm_request (void) [static]
Definition at line 2072 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, CHECK_STRUCT, CHECK_VALUE_X, HSM_FORCE_ACTION, and HSM_GHOST_COPY.
Referenced by main().
static void check_hsm_state_set (void) [static]
Definition at line 2053 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_hsm_user_import (void) [static]
Definition at line 2093 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_hsm_user_item (void) [static]
Definition at line 1945 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_hsm_user_request (void) [static]
Definition at line 2085 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_hsm_user_state (void) [static]
Definition at line 1954 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_layout_intent (void) [static]
Definition at line 2035 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, CHECK_STRUCT, CHECK_VALUE, LAYOUT_INTENT_ACCESS, LAYOUT_INTENT_GLIMPSE, LAYOUT_INTENT_READ, LAYOUT_INTENT_RELEASE, LAYOUT_INTENT_RESTORE, LAYOUT_INTENT_TRUNC, and LAYOUT_INTENT_WRITE.
Referenced by main().
static void check_ldlm_extent (void) [static]
Definition at line 1298 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, CHECK_STRUCT, end, and start.
Referenced by main().
static void check_ldlm_flock (void) [static]
Definition at line 1316 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_ldlm_gl_lquota_desc (void) [static]
Definition at line 1436 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_ldlm_inodebits (void) [static]
Definition at line 1308 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_ldlm_intent (void) [static]
Definition at line 1328 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, CHECK_STRUCT, CHECK_VALUE, IT_CREAT, IT_EXEC, IT_GETATTR, IT_GETXATTR, IT_LAYOUT, IT_LOOKUP, IT_OPEN, IT_PIN, IT_QUOTA_CONN, IT_QUOTA_DQACQ, IT_READDIR, IT_SETXATTR, IT_TRUNC, and IT_UNLINK.
Referenced by main().
static void check_ldlm_lock_desc (void) [static]
Definition at line 1360 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_ldlm_lquota_lvb (void) [static]
Definition at line 1423 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, CHECK_STRUCT, CHECK_VALUE, and LQUOTA_FL_EDQUOT.
Referenced by main().
static void check_ldlm_ost_lvb (void) [static]
Definition at line 1407 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_ldlm_ost_lvb_v1 (void) [static]
Definition at line 1395 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_ldlm_reply (void) [static]
Definition at line 1382 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_ldlm_request (void) [static]
Definition at line 1371 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_ldlm_res_id (void) [static]
Definition at line 1289 of file wirecheck.c.
References BLANK_LINE, CHECK_CVALUE, CHECK_MEMBER, CHECK_STRUCT, name, and RES_NAME_SIZE.
Referenced by main().
static void check_ldlm_resource_desc (void) [static]
Definition at line 1350 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_lfsck_reply (void) [static]
Definition at line 2281 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_lfsck_request (void) [static]
Definition at line 2233 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, CHECK_STRUCT, CHECK_VALUE, CHECK_VALUE_X, LE_CONDITIONAL_DESTROY, LE_FID_ACCESSED, LE_LASTID_REBUILDING, LE_LASTID_REBUILT, LE_PAIRS_VERIFY, LE_PEER_EXIT, LE_PHASE1_DONE, LE_PHASE2_DONE, LE_QUERY, LE_SET_LMV_MASTER, LE_SET_LMV_SLAVE, LE_SKIP_NLINK, LE_SKIP_NLINK_DECLARE, LE_START, LE_STOP, LEF_FROM_OST, LEF_QUERY_ALL, LEF_RECHECK_NAME_HASH, LEF_SET_LMV_ALL, LEF_SET_LMV_HASH, LEF_TO_OST, LFSCK_TYPE_LAYOUT, LFSCK_TYPE_NAMESPACE, and LFSCK_TYPE_SCRUB.
Referenced by main().
static void check_link_ea_entry (void) [static]
Definition at line 1935 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_link_ea_header (void) [static]
Definition at line 1921 of file wirecheck.c.
References BLANK_LINE, CHECK_CDEFINE, CHECK_MEMBER, CHECK_STRUCT, and LINK_EA_MAGIC.
Referenced by main().
static void check_ll_fid (void) [static]
Definition at line 916 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_ll_fiemap_extent (void) [static]
Definition at line 1896 of file wirecheck.c.
References BLANK_LINE, CHECK_CDEFINE, CHECK_MEMBER, CHECK_STRUCT, fe_device, FIEMAP_EXTENT_NET, and FIEMAP_EXTENT_NO_DIRECT.
Referenced by main().
static void check_ll_fiemap_info_key (void) [static]
Definition at line 1753 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_ll_user_fiemap (void) [static]
Definition at line 1878 of file wirecheck.c.
References BLANK_LINE, CHECK_CDEFINE, CHECK_MEMBER, CHECK_STRUCT, and FIEMAP_FLAG_DEVICE_ORDER.
Referenced by main().
static void check_llog_catid (void) [static]
Definition at line 1495 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_llog_changelog_rec (void) [static]
Definition at line 1634 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_llog_changelog_user_rec (void) [static]
Definition at line 1644 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_llog_cookie (void) [static]
Definition at line 1690 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_llog_gen (void) [static]
Definition at line 1656 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_llog_gen_rec (void) [static]
Definition at line 1665 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_llog_log_hdr (void) [static]
Definition at line 1675 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_llog_logid (void) [static]
Definition at line 1475 of file wirecheck.c.
References BLANK_LINE, CHANGELOG_REC, CHANGELOG_USER_REC, CHECK_CVALUE, CHECK_MEMBER, CHECK_STRUCT, LLOG_GEN_REC, LLOG_HDR_MAGIC, LLOG_LOGID_MAGIC, MDS_SETATTR64_REC, MDS_UNLINK64_REC, MDS_UNLINK_REC, OBD_CFG_REC, and OST_SZ_REC.
Referenced by main().
static void check_llog_logid_rec (void) [static]
Definition at line 1526 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_llog_rec_hdr (void) [static]
Definition at line 1506 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_llog_rec_tail (void) [static]
Definition at line 1517 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_llog_setattr64_rec (void) [static]
Definition at line 1564 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_llog_size_change_rec (void) [static]
Definition at line 1579 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_llog_unlink64_rec (void) [static]
Definition at line 1551 of file wirecheck.c.
References CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_llog_unlink_rec (void) [static]
Definition at line 1539 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_llog_update_record (void) [static]
Definition at line 2328 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_llogd_body (void) [static]
Definition at line 1701 of file wirecheck.c.
References BLANK_LINE, CHECK_CVALUE, CHECK_MEMBER, CHECK_STRUCT, LLOG_AGENT_ORIG_CTXT, LLOG_CATINFO, LLOG_CHANGELOG_ORIG_CTXT, LLOG_CHANGELOG_REPL_CTXT, LLOG_CHANGELOG_USER_ORIG_CTXT, LLOG_CONFIG_ORIG_CTXT, LLOG_CONFIG_REPL_CTXT, LLOG_FIRST_OPC, LLOG_LAST_OPC, LLOG_MAX_CTXTS, LLOG_MDS_OST_ORIG_CTXT, LLOG_MDS_OST_REPL_CTXT, LLOG_ORIGIN_CONNECT, LLOG_ORIGIN_HANDLE_CLOSE, LLOG_ORIGIN_HANDLE_CREATE, LLOG_ORIGIN_HANDLE_DESTROY, LLOG_ORIGIN_HANDLE_NEXT_BLOCK, LLOG_ORIGIN_HANDLE_PREV_BLOCK, LLOG_ORIGIN_HANDLE_READ_HEADER, LLOG_ORIGIN_HANDLE_WRITE_REC, LLOG_SIZE_ORIG_CTXT, LLOG_SIZE_REPL_CTXT, LLOG_TEST_ORIG_CTXT, LLOG_TEST_REPL_CTXT, LLOG_UPDATELOG_ORIG_CTXT, and LLOG_UPDATELOG_REPL_CTXT.
Referenced by main().
static void check_llogd_conn_body (void) [static]
Definition at line 1743 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_lmv_desc (void) [static]
Definition at line 1251 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_lmv_mds_md_v1 (void) [static]
Definition at line 721 of file wirecheck.c.
References BLANK_LINE, CHECK_CDEFINE, CHECK_MEMBER, CHECK_STRUCT, LMV_HASH_FLAG_BAD_TYPE, LMV_HASH_FLAG_LOST_LMV, LMV_HASH_FLAG_MIGRATION, LMV_HASH_TYPE_MASK, LMV_MAGIC_STRIPE, LMV_MAGIC_V1, and LOV_MAXPOOLNAME.
Referenced by main().
static void check_lov_desc (void) [static]
Definition at line 1269 of file wirecheck.c.
References BLANK_LINE, CHECK_CDEFINE, CHECK_MEMBER, CHECK_STRUCT, and LOV_DESC_MAGIC.
Referenced by main().
static void check_lov_mds_md_v1 (void) [static]
Definition at line 682 of file wirecheck.c.
References BLANK_LINE, CHECK_CDEFINE, CHECK_MEMBER, CHECK_STRUCT, and LOV_MAGIC_V1.
Referenced by main().
static void check_lov_mds_md_v3 (void) [static]
Definition at line 698 of file wirecheck.c.
References BLANK_LINE, CHECK_CDEFINE, CHECK_CVALUE, CHECK_MEMBER, CHECK_STRUCT, CHECK_VALUE_X, LOV_MAGIC_V3, LOV_MAXPOOLNAME, LOV_PATTERN_CMOBD, LOV_PATTERN_FIRST, LOV_PATTERN_RAID0, and LOV_PATTERN_RAID1.
Referenced by main().
static void check_lov_ost_data_v1 (void) [static]
Definition at line 672 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_lu_dirent (void) [static]
Definition at line 269 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, CHECK_STRUCT, CHECK_VALUE_X, LUDA_64BITHASH, LUDA_FID, and LUDA_TYPE.
Referenced by main().
static void check_lu_dirpage (void) [static]
Definition at line 294 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, CHECK_STRUCT, CHECK_UNION, CHECK_VALUE, LDF_COLLIDE, LDF_EMPTY, and LU_PAGE_SIZE.
Referenced by main().
static void check_lu_ladvise (void) [static]
Definition at line 311 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_lu_seq_range (void) [static]
Definition at line 188 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, CHECK_STRUCT, CHECK_VALUE, LU_SEQ_RANGE_MDT, and LU_SEQ_RANGE_OST.
Referenced by main().
static void check_luda_type (void) [static]
Definition at line 286 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_lustre_capa (void) [static]
Definition at line 1798 of file wirecheck.c.
References BLANK_LINE, CAPA_HMAC_MAX_LEN, CHECK_CVALUE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_lustre_capa_key (void) [static]
Definition at line 1815 of file wirecheck.c.
References BLANK_LINE, CAPA_HMAC_KEY_MAX_LEN, CHECK_CVALUE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_lustre_handle (void) [static]
Definition at line 322 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_lustre_mdt_attrs (void) [static]
Definition at line 202 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, CHECK_STRUCT, CHECK_VALUE_X, LMAC_FID_ON_OST, LMAC_HSM, LMAC_NOT_IN_OI, LMAI_AGENT, LMAI_ORPHAN, LMAI_RELEASED, LMAI_REMOTE_PARENT, and LMAI_STRIPED.
Referenced by main().
static void check_lustre_msg_v2 (void) [static]
Definition at line 330 of file wirecheck.c.
References BLANK_LINE, CHECK_DEFINE_X, CHECK_MEMBER, CHECK_STRUCT, LUSTRE_MSG_MAGIC_V2, and LUSTRE_MSG_MAGIC_V2_SWABBED.
Referenced by main().
static void check_mdt_body (void) [static]
Definition at line 926 of file wirecheck.c.
References BLANK_LINE, CHECK_DEFINE_X, CHECK_MEMBER, CHECK_STRUCT, CHECK_VALUE_64O, CHECK_VALUE_O, CHECK_VALUE_X, LUSTRE_APPEND_FL, LUSTRE_DIRECTIO_FL, LUSTRE_DIRSYNC_FL, LUSTRE_IMMUTABLE_FL, LUSTRE_INDEX_FL, LUSTRE_INLINE_DATA_FL, LUSTRE_NOATIME_FL, LUSTRE_NODUMP_FL, LUSTRE_ORPHAN_FL, LUSTRE_SYNC_FL, LUSTRE_TOPDIR_FL, MDS_FMODE_CLOSED, MDS_FMODE_EXEC, MDS_INODELOCK_LAYOUT, MDS_INODELOCK_LOOKUP, MDS_INODELOCK_OPEN, MDS_INODELOCK_UPDATE, MDS_OPEN_APPEND, MDS_OPEN_BY_FID, MDS_OPEN_CREAT, MDS_OPEN_CREATED, MDS_OPEN_CROSS, MDS_OPEN_DELAY_CREATE, MDS_OPEN_DIRECTORY, MDS_OPEN_EXCL, MDS_OPEN_HAS_EA, MDS_OPEN_HAS_OBJS, MDS_OPEN_JOIN_FILE, MDS_OPEN_LOCK, MDS_OPEN_NEWSTRIPE, MDS_OPEN_NORESTORE, MDS_OPEN_OWNEROVERRIDE, MDS_OPEN_SYNC, MDS_OPEN_TRUNC, and MDS_OPEN_VOLATILE.
Referenced by main().
static void check_mdt_ioepoch (void) [static]
Definition at line 1007 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_mdt_rec_create (void) [static]
Definition at line 1069 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_mdt_rec_link (void) [static]
Definition at line 1099 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_mdt_rec_reint (void) [static]
Definition at line 1221 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_mdt_rec_rename (void) [static]
Definition at line 1159 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_mdt_rec_setattr (void) [static]
Definition at line 1037 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_mdt_rec_setxattr (void) [static]
Definition at line 1189 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_mdt_rec_unlink (void) [static]
Definition at line 1129 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_mdt_remote_perm (void) [static]
Definition at line 1018 of file wirecheck.c.
References BLANK_LINE, CFS_RMTACL_PERM, CFS_RMTOWN_PERM, CFS_SETGID_PERM, CFS_SETGRP_PERM, CFS_SETUID_PERM, CHECK_MEMBER, CHECK_STRUCT, and CHECK_VALUE_X.
Referenced by main().
static void check_mgs_send_param (void) [static]
Definition at line 1451 of file wirecheck.c.
References BLANK_LINE, CHECK_CVALUE, CHECK_MEMBER, CHECK_STRUCT, and MGS_PARAM_MAXLEN.
Referenced by main().
static void check_mgs_target_info (void) [static]
Definition at line 1780 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_niobuf_remote (void) [static]
Definition at line 883 of file wirecheck.c.
References BLANK_LINE, CHECK_DEFINE_X, CHECK_MEMBER, CHECK_STRUCT, OBD_BRW_ASYNC, OBD_BRW_CHECK, OBD_BRW_FROM_GRANT, OBD_BRW_GRANTED, OBD_BRW_MEMALLOC, OBD_BRW_NOCACHE, OBD_BRW_NOQUOTA, OBD_BRW_OVER_GRPQUOTA, OBD_BRW_OVER_USRQUOTA, OBD_BRW_READ, OBD_BRW_SOFT_SYNC, OBD_BRW_SRVLOCK, OBD_BRW_SYNC, and OBD_BRW_WRITE.
Referenced by main().
static void check_nodemap_cluster_rec (void) [static]
Definition at line 2181 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_nodemap_global_rec (void) [static]
Definition at line 2214 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_nodemap_id_rec (void) [static]
Definition at line 2203 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_nodemap_range_rec (void) [static]
Definition at line 2193 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_nodemap_rec (void) [static]
Definition at line 2227 of file wirecheck.c.
References BLANK_LINE, and CHECK_UNION.
Referenced by main().
static void check_obd_connect_data (void) [static]
Definition at line 458 of file wirecheck.c.
References BLANK_LINE, CHECK_DEFINE_64X, CHECK_MEMBER, CHECK_STRUCT, CHECK_VALUE_X, OBD_CKSUM_ADLER, OBD_CKSUM_CRC32, OBD_CKSUM_CRC32C, OBD_CONNECT_64BITHASH, OBD_CONNECT_ACL, OBD_CONNECT_AT, OBD_CONNECT_ATTRFID, OBD_CONNECT_BRW_SIZE, OBD_CONNECT_BULK_MBITS, OBD_CONNECT_CANCELSET, OBD_CONNECT_CHANGE_QS, OBD_CONNECT_CKSUM, OBD_CONNECT_CROW, OBD_CONNECT_DIR_STRIPE, OBD_CONNECT_EINPROGRESS, OBD_CONNECT_FID, OBD_CONNECT_FLAGS2, OBD_CONNECT_FLOCK_DEAD, OBD_CONNECT_FLOCK_OWNER, OBD_CONNECT_FULL20, OBD_CONNECT_GRANT, OBD_CONNECT_GRANT_PARAM, OBD_CONNECT_GRANT_SHRINK, OBD_CONNECT_IBITS, OBD_CONNECT_IMP_RECOV, OBD_CONNECT_INDEX, OBD_CONNECT_JOBSTATS, OBD_CONNECT_JOIN, OBD_CONNECT_LAYOUTLOCK, OBD_CONNECT_LFSCK, OBD_CONNECT_LIGHTWEIGHT, OBD_CONNECT_LOCK_AHEAD, OBD_CONNECT_LOV_V3, OBD_CONNECT_LRU_RESIZE, OBD_CONNECT_LVB_TYPE, OBD_CONNECT_MAX_EASIZE, OBD_CONNECT_MAXBYTES, OBD_CONNECT_MDS, OBD_CONNECT_MDS_CAPA, OBD_CONNECT_MDS_MDS, OBD_CONNECT_MULTIMODRPCS, OBD_CONNECT_NANOSEC_TIME, OBD_CONNECT_NODEVOH, OBD_CONNECT_OBDOPACK, OBD_CONNECT_OPEN_BY_FID, OBD_CONNECT_OSS_CAPA, OBD_CONNECT_PINGLESS, OBD_CONNECT_QUOTA64, OBD_CONNECT_RDONLY, OBD_CONNECT_REAL, OBD_CONNECT_REQPORTAL, OBD_CONNECT_RMT_CLIENT, OBD_CONNECT_RMT_CLIENT_FORCE, OBD_CONNECT_SHORTIO, OBD_CONNECT_SKIP_ORPHAN, OBD_CONNECT_SOM, OBD_CONNECT_SRVLOCK, OBD_CONNECT_SUBTREE, OBD_CONNECT_TRANSNO, OBD_CONNECT_TRUNCLOCK, OBD_CONNECT_UMASK, OBD_CONNECT_UNLINK_CLOSE, OBD_CONNECT_VBR, OBD_CONNECT_VERSION, and OBD_CONNECT_XATTR.
Referenced by main().
static void check_obd_idx_read (void) [static]
Definition at line 846 of file wirecheck.c.
References BLANK_LINE, CHECK_CDEFINE, CHECK_MEMBER, CHECK_STRUCT, CHECK_VALUE, IDX_INFO_MAGIC, II_FL_NOHASH, II_FL_NONUNQ, II_FL_VARKEY, II_FL_VARREC, LIP_HDR_SIZE, and LIP_MAGIC.
Referenced by main().
static void check_obd_ioobj (void) [static]
Definition at line 771 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, CHECK_STRUCT, CHECK_VALUE, and IOOBJ_MAX_BRW_BITS.
Referenced by main().
static void check_obd_quotactl (void) [static]
Definition at line 782 of file wirecheck.c.
References BLANK_LINE, CHECK_DEFINE_X, CHECK_MEMBER, CHECK_STRUCT, CHECK_UNION, CHECK_VALUE, Q_FINVALIDATE, Q_GETOINFO, Q_GETOQUOTA, Q_INITQUOTA, Q_QUOTACHECK, QUOTABLOCK_BITS, and QUOTABLOCK_SIZE.
Referenced by main().
static void check_obd_statfs (void) [static]
Definition at line 746 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_obdo (void) [static]
Definition at line 565 of file wirecheck.c.
References BLANK_LINE, CHECK_CVALUE_X, CHECK_DEFINE_64X, CHECK_MEMBER, CHECK_STRUCT, OBD_FL_CKSUM_ADLER, OBD_FL_CKSUM_CRC32, OBD_FL_CKSUM_CRC32C, OBD_FL_CKSUM_RSVD2, OBD_FL_CKSUM_RSVD3, OBD_FL_CREATE_CROW, OBD_FL_DEBUG_CHECK, OBD_FL_DELORPHAN, OBD_FL_FLUSH, OBD_FL_IDONLY, OBD_FL_INLINEDATA, OBD_FL_LOCAL_MASK, OBD_FL_MMAP, OBD_FL_NO_GRPQUOTA, OBD_FL_NO_USRQUOTA, OBD_FL_NORPC, OBD_FL_NOSPC_BLK, OBD_FL_OBDMDEXISTS, OBD_FL_RECOV_RESEND, OBD_FL_RECREATE_OBJS, OBD_FL_SHORT_IO, OBD_FL_SHRINK_GRANT, OBD_FL_SRVLOCK, OBD_MD_FLACL, OBD_MD_FLATIME, OBD_MD_FLBLKSZ, OBD_MD_FLBLOCKS, OBD_MD_FLCKSPLIT, OBD_MD_FLCKSUM, OBD_MD_FLCROSSREF, OBD_MD_FLCTIME, OBD_MD_FLDATAVERSION, OBD_MD_FLDIREA, OBD_MD_FLEASIZE, OBD_MD_FLEPOCH, OBD_MD_FLFID, OBD_MD_FLFLAGS, OBD_MD_FLGENER, OBD_MD_FLGETATTRLOCK, OBD_MD_FLGID, OBD_MD_FLGRANT, OBD_MD_FLGROUP, OBD_MD_FLGRPQUOTA, OBD_MD_FLHANDLE, OBD_MD_FLID, OBD_MD_FLMDSCAPA, OBD_MD_FLMODE, OBD_MD_FLMODEASIZE, OBD_MD_FLMTIME, OBD_MD_FLNLINK, OBD_MD_FLOSSCAPA, OBD_MD_FLQOS, OBD_MD_FLRDEV, OBD_MD_FLRMTLGETFACL, OBD_MD_FLRMTLSETFACL, OBD_MD_FLRMTPERM, OBD_MD_FLRMTRGETFACL, OBD_MD_FLRMTRSETFACL, OBD_MD_FLSIZE, OBD_MD_FLTYPE, OBD_MD_FLUID, OBD_MD_FLUSRQUOTA, OBD_MD_FLXATTR, OBD_MD_FLXATTRLS, OBD_MD_FLXATTRRM, OBD_MD_LINKNAME, OBD_MD_MDS, OBD_MD_MEA, OBD_MD_REINT, and OBD_MD_TSTATE.
Referenced by main().
static void check_object_update (void) [static]
Definition at line 2118 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_object_update_param (void) [static]
Definition at line 2108 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_object_update_reply (void) [static]
Definition at line 2152 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_object_update_request (void) [static]
Definition at line 2132 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_object_update_result (void) [static]
Definition at line 2142 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_ost_body (void) [static]
Definition at line 908 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_ost_id (void) [static]
Definition at line 232 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, CHECK_STRUCT, CHECK_VALUE, CHECK_VALUE_64X, CHECK_VALUE_X, FID_OID_DOT_LUSTRE, FID_OID_DOT_LUSTRE_OBF, FID_OID_SPECIAL_BFL, FID_SEQ_DOT_LUSTRE, FID_SEQ_ECHO, FID_SEQ_IDIF, FID_SEQ_IDIF_MAX, FID_SEQ_IGIF, FID_SEQ_IGIF_MAX, FID_SEQ_LAYOUT_RBTREE, FID_SEQ_LLOG, FID_SEQ_LOCAL_FILE, FID_SEQ_LOV_DEFAULT, FID_SEQ_NORMAL, FID_SEQ_OST_MDT0, FID_SEQ_QUOTA, FID_SEQ_QUOTA_GLB, FID_SEQ_ROOT, FID_SEQ_RSVD, FID_SEQ_SPECIAL, FID_SEQ_START, FID_SEQ_UNUSED_END, FID_SEQ_UNUSED_START, FID_SEQ_UPDATE_LOG, FID_SEQ_UPDATE_LOG_DIR, and LUSTRE_FID_INIT_OID.
Referenced by main().
static void check_out_update_buffer (void) [static]
Definition at line 2173 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_out_update_header (void) [static]
Definition at line 2162 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_posix_acl_xattr_entry (void) [static]
Definition at line 1855 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER_TYPEDEF, and CHECK_STRUCT_TYPEDEF.
Referenced by main().
static void check_posix_acl_xattr_header (void) [static]
Definition at line 1867 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER_TYPEDEF, and CHECK_STRUCT_TYPEDEF.
Referenced by main().
static void check_ptlrpc_body (void) [static]
Definition at line 349 of file wirecheck.c.
References BLANK_LINE, CHECK_CVALUE, CHECK_DEFINE_X, CHECK_MEMBER, CHECK_MEMBER_SAME, CHECK_STRUCT, CHECK_VALUE, CHECK_VALUE_X, DLM_INTENT_IT_OFF, DLM_INTENT_REC_OFF, DLM_LOCKREPLY_OFF, DLM_LOCKREQ_OFF, DLM_REPLY_REC_OFF, DLM_REQ_REC_OFF, LUSTRE_DLM_VERSION, LUSTRE_JOBID_SIZE, LUSTRE_LOG_VERSION, LUSTRE_MDS_VERSION, LUSTRE_MGS_VERSION, LUSTRE_OBD_VERSION, LUSTRE_OST_VERSION, LUSTRE_VERSION_MASK, MSG_CONNECT_ASYNC, MSG_CONNECT_INITIAL, MSG_CONNECT_LIBCLIENT, MSG_CONNECT_NEXT_VER, MSG_CONNECT_RECONNECT, MSG_CONNECT_RECOVERING, MSG_CONNECT_REPLAYABLE, MSG_CONNECT_TRANSNO, MSG_DELAY_REPLAY, MSG_GEN_FLAG_MASK, MSG_LAST_REPLAY, MSG_LOCK_REPLAY_DONE, MSG_OP_FLAG_MASK, MSG_OP_FLAG_SHIFT, MSG_PTLRPC_BODY_OFF, MSG_PTLRPC_HEADER_OFF, MSG_REPLAY, MSG_REQ_REPLAY_DONE, MSG_RESENT, MSG_VERSION_REPLAY, MSGHDR_AT_SUPPORT, MSGHDR_CKSUM_INCOMPAT18, ptlrpc_body, PTLRPC_MSG_VERSION, PTLRPC_NUM_VERSIONS, REPLY_REC_OFF, and REQ_REC_OFF.
Referenced by main().
static void check_quota_body (void) [static]
Definition at line 1763 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_update_op (void) [static]
Definition at line 2297 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_update_ops (void) [static]
Definition at line 2307 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_update_params (void) [static]
Definition at line 2290 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, and CHECK_STRUCT.
Referenced by main().
static void check_update_records (void) [static]
Definition at line 2314 of file wirecheck.c.
References BLANK_LINE, CHECK_MEMBER, CHECK_STRUCT, CHECK_VALUE_X, and UPDATE_RECORD_CONTINUE.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 2387 of file wirecheck.c.
References BLANK_LINE, check_cfg_marker(), check_changelog_ext_jobid(), check_changelog_ext_rename(), check_changelog_rec(), check_changelog_setinfo(), CHECK_CVALUE, CHECK_DEFINE_64X, check_getinfo_fid2path(), check_hsm_action_item(), check_hsm_action_list(), check_hsm_attrs(), check_hsm_copy(), check_hsm_current_action(), check_hsm_progress(), check_hsm_progress_kernel(), check_hsm_request(), check_hsm_state_set(), check_hsm_user_import(), check_hsm_user_item(), check_hsm_user_request(), check_hsm_user_state(), check_layout_intent(), check_ldlm_extent(), check_ldlm_flock(), check_ldlm_gl_lquota_desc(), check_ldlm_inodebits(), check_ldlm_intent(), check_ldlm_lock_desc(), check_ldlm_lquota_lvb(), check_ldlm_ost_lvb(), check_ldlm_ost_lvb_v1(), check_ldlm_reply(), check_ldlm_request(), check_ldlm_res_id(), check_ldlm_resource_desc(), check_lfsck_reply(), check_lfsck_request(), check_link_ea_entry(), check_link_ea_header(), check_ll_fid(), check_ll_fiemap_extent(), check_ll_fiemap_info_key(), check_ll_user_fiemap(), check_llog_catid(), check_llog_changelog_rec(), check_llog_changelog_user_rec(), check_llog_cookie(), check_llog_gen(), check_llog_gen_rec(), check_llog_log_hdr(), check_llog_logid(), check_llog_logid_rec(), check_llog_rec_hdr(), check_llog_rec_tail(), check_llog_setattr64_rec(), check_llog_size_change_rec(), check_llog_unlink64_rec(), check_llog_unlink_rec(), check_llog_update_record(), check_llogd_body(), check_llogd_conn_body(), check_lmv_desc(), check_lmv_mds_md_v1(), check_lov_desc(), check_lov_mds_md_v1(), check_lov_mds_md_v3(), check_lov_ost_data_v1(), check_lu_dirent(), check_lu_dirpage(), check_lu_ladvise(), check_lu_seq_range(), check_luda_type(), check_lustre_capa(), check_lustre_capa_key(), check_lustre_handle(), check_lustre_mdt_attrs(), check_lustre_msg_v2(), check_mdt_body(), check_mdt_ioepoch(), check_mdt_rec_create(), check_mdt_rec_link(), check_mdt_rec_reint(), check_mdt_rec_rename(), check_mdt_rec_setattr(), check_mdt_rec_setxattr(), check_mdt_rec_unlink(), check_mdt_remote_perm(), check_mgs_send_param(), check_mgs_target_info(), check_niobuf_remote(), check_nodemap_cluster_rec(), check_nodemap_global_rec(), check_nodemap_id_rec(), check_nodemap_range_rec(), check_nodemap_rec(), check_obd_connect_data(), check_obd_idx_read(), check_obd_ioobj(), check_obd_quotactl(), check_obd_statfs(), check_obdo(), check_object_update(), check_object_update_param(), check_object_update_reply(), check_object_update_request(), check_object_update_result(), check_ost_body(), check_ost_id(), check_out_update_buffer(), check_out_update_header(), check_posix_acl_xattr_entry(), check_posix_acl_xattr_header(), check_ptlrpc_body(), check_quota_body(), CHECK_STRUCT, check_update_op(), check_update_ops(), check_update_params(), check_update_records(), CHECK_VALUE, CHECK_VALUE_64X, CHECK_VALUE_X, COMMENT, DEAD_HANDLE_MAGIC, DISP_ENQ_COMPLETE, DISP_ENQ_CREATE_REF, DISP_ENQ_OPEN_REF, DISP_IT_EXECD, DISP_LOOKUP_EXECD, DISP_LOOKUP_NEG, DISP_LOOKUP_POS, DISP_OPEN_CREATE, DISP_OPEN_LOCK, DISP_OPEN_OPEN, FLD_FIRST_OPC, FLD_LAST_OPC, FLD_QUERY, FLD_READ, LCK_COS, LCK_CR, LCK_CW, LCK_EX, LCK_GROUP, LCK_MAXMODE, LCK_MINMODE, LCK_MODE_NUM, LCK_NL, LCK_PR, LCK_PW, LDLM_BL_CALLBACK, LDLM_CANCEL, LDLM_CONVERT, LDLM_CP_CALLBACK, LDLM_ENQUEUE, LDLM_EXTENT, LDLM_FLOCK, LDLM_GL_CALLBACK, LDLM_IBITS, LDLM_LAST_OPC, LDLM_MAX_TYPE, LDLM_PLAIN, LDLM_SET_INFO, LFSCK_FIRST_OPC, LFSCK_LAST_OPC, LFSCK_NOTIFY, LFSCK_QUERY, LQUOTA_RES_DT, LQUOTA_RES_MD, LQUOTA_TYPE_GRP, LQUOTA_TYPE_USR, LUSTRE_RES_ID_HSH_OFF, LUSTRE_RES_ID_QUOTA_SEQ_OFF, LUSTRE_RES_ID_QUOTA_VER_OID_OFF, LUSTRE_RES_ID_SEQ_OFF, LUSTRE_RES_ID_VER_OID_OFF, MDS_ATTR_ATIME, MDS_ATTR_ATIME_SET, MDS_ATTR_ATTR_FLAG, MDS_ATTR_BLOCKS, MDS_ATTR_CTIME, MDS_ATTR_CTIME_SET, MDS_ATTR_FORCE, MDS_ATTR_FROM_OPEN, MDS_ATTR_GID, MDS_ATTR_KILL_SGID, MDS_ATTR_KILL_SUID, MDS_ATTR_MODE, MDS_ATTR_MTIME, MDS_ATTR_MTIME_SET, MDS_ATTR_SIZE, MDS_ATTR_UID, MDS_CLOSE, MDS_CONNECT, MDS_DIR_END_OFF, MDS_DISCONNECT, MDS_DONE_WRITING, MDS_FIRST_OPC, MDS_GET_INFO, MDS_GET_ROOT, MDS_GETATTR, MDS_GETATTR_NAME, MDS_GETXATTR, MDS_HSM_ACTION, MDS_HSM_CT_REGISTER, MDS_HSM_CT_UNREGISTER, MDS_HSM_PROGRESS, MDS_HSM_REQUEST, MDS_HSM_STATE_GET, MDS_HSM_STATE_SET, MDS_IS_SUBDIR, MDS_LAST_OPC, MDS_PIN, MDS_QUOTACHECK, MDS_QUOTACTL, MDS_READPAGE, MDS_REINT, MDS_SET_INFO, MDS_SETXATTR, MDS_STATFS, MDS_STATUS_CONN, MDS_STATUS_LOV, MDS_SWAP_LAYOUTS, MDS_SYNC, MDS_UNPIN, MDS_WRITEPAGE, MGS_CONNECT, MGS_DISCONNECT, MGS_EXCEPTION, MGS_LAST_OPC, MGS_SET_INFO, MGS_TARGET_DEL, MGS_TARGET_REG, MTI_NAME_MAXLEN, OBD_IDX_READ, OBD_LAST_OPC, OBD_LOG_CANCEL, OBD_OBJECT_EOF, OBD_PING, OBD_QC_CALLBACK, OST_CLOSE, OST_CONNECT, OST_CREATE, OST_DESTROY, OST_DISCONNECT, OST_GET_INFO, OST_GETATTR, OST_LADVISE, OST_LAST_OPC, OST_LVB_ERR_INIT, OST_LVB_ERR_MASK, OST_MAX_PRECREATE, OST_MIN_PRECREATE, OST_OPEN, OST_PUNCH, OST_QUOTA_ADJUST_QUNIT, OST_QUOTACHECK, OST_QUOTACTL, OST_READ, OST_REPLY, OST_SET_INFO, OST_SETATTR, OST_STATFS, OST_SYNC, OST_WRITE, OUT_ATTR_GET, OUT_ATTR_SET, OUT_CREATE, OUT_DESTROY, OUT_INDEX_DELETE, OUT_INDEX_INSERT, OUT_INDEX_LOOKUP, OUT_PUNCH, OUT_READ, OUT_REF_ADD, OUT_REF_DEL, OUT_UPDATE, OUT_UPDATE_LAST_OPC, OUT_WRITE, OUT_XATTR_DEL, OUT_XATTR_GET, OUT_XATTR_SET, PTL_RPC_MSG_ERR, PTL_RPC_MSG_REPLY, PTL_RPC_MSG_REQUEST, QUOTA_DQACQ, QUOTA_DQREL, QUOTA_LAST_OPC, REINT_CREATE, REINT_LINK, REINT_MAX, REINT_MIGRATE, REINT_OPEN, REINT_RENAME, REINT_RMENTRY, REINT_SETATTR, REINT_SETXATTR, REINT_UNLINK, SEC_CTX_FINI, SEC_CTX_INIT, SEC_CTX_INIT_CONT, SEC_LAST_OPC, SEQ_ALLOC_META, SEQ_ALLOC_SUPER, SEQ_FIRST_OPC, SEQ_LAST_OPC, SEQ_QUERY, and system_string().
static void system_string (char * cmdline, char * str, int len) [static]
Definition at line 2336 of file wirecheck.c.
References strnlen.
Referenced by main().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.