Lustre: lustre/include/lustre/lustre_errno.h File Reference
lustre/include/lustre/lustre_errno.h File Reference
Defines
#define LUSTRE_EPERM 1
#define LUSTRE_ENOENT 2
#define LUSTRE_ESRCH 3
#define LUSTRE_EINTR 4
#define LUSTRE_EIO 5
#define LUSTRE_ENXIO 6
#define LUSTRE_E2BIG 7
#define LUSTRE_ENOEXEC 8
#define LUSTRE_EBADF 9
#define LUSTRE_ECHILD 10
#define LUSTRE_EAGAIN 11
#define LUSTRE_ENOMEM 12
#define LUSTRE_EACCES 13
#define LUSTRE_EFAULT 14
#define LUSTRE_ENOTBLK 15
#define LUSTRE_EBUSY 16
#define LUSTRE_EEXIST 17
#define LUSTRE_EXDEV 18
#define LUSTRE_ENODEV 19
#define LUSTRE_ENOTDIR 20
#define LUSTRE_EISDIR 21
#define LUSTRE_EINVAL 22
#define LUSTRE_ENFILE 23
#define LUSTRE_EMFILE 24
#define LUSTRE_ENOTTY 25
#define LUSTRE_ETXTBSY 26
#define LUSTRE_EFBIG 27
#define LUSTRE_ENOSPC 28
#define LUSTRE_ESPIPE 29
#define LUSTRE_EROFS 30
#define LUSTRE_EMLINK 31
#define LUSTRE_EPIPE 32
#define LUSTRE_EDOM 33
#define LUSTRE_ERANGE 34
#define LUSTRE_EDEADLK 35
#define LUSTRE_ENAMETOOLONG 36
#define LUSTRE_ENOLCK 37
#define LUSTRE_ENOSYS 38
#define LUSTRE_ENOTEMPTY 39
#define LUSTRE_ELOOP 40
#define LUSTRE_ENOMSG 42
#define LUSTRE_EIDRM 43
#define LUSTRE_ECHRNG 44
#define LUSTRE_EL2NSYNC 45
#define LUSTRE_EL3HLT 46
#define LUSTRE_EL3RST 47
#define LUSTRE_ELNRNG 48
#define LUSTRE_EUNATCH 49
#define LUSTRE_ENOCSI 50
#define LUSTRE_EL2HLT 51
#define LUSTRE_EBADE 52
#define LUSTRE_EBADR 53
#define LUSTRE_EXFULL 54
#define LUSTRE_ENOANO 55
#define LUSTRE_EBADRQC 56
#define LUSTRE_EBADSLT 57
#define LUSTRE_EBFONT 59
#define LUSTRE_ENOSTR 60
#define LUSTRE_ENODATA 61
#define LUSTRE_ETIME 62
#define LUSTRE_ENOSR 63
#define LUSTRE_ENONET 64
#define LUSTRE_ENOPKG 65
#define LUSTRE_EREMOTE 66
#define LUSTRE_ENOLINK 67
#define LUSTRE_EADV 68
#define LUSTRE_ESRMNT 69
#define LUSTRE_ECOMM 70
#define LUSTRE_EPROTO 71
#define LUSTRE_EMULTIHOP 72
#define LUSTRE_EDOTDOT 73
#define LUSTRE_EBADMSG 74
#define LUSTRE_EOVERFLOW 75
#define LUSTRE_ENOTUNIQ 76
#define LUSTRE_EBADFD 77
#define LUSTRE_EREMCHG 78
#define LUSTRE_ELIBACC 79
#define LUSTRE_ELIBBAD 80
#define LUSTRE_ELIBSCN 81
#define LUSTRE_ELIBMAX 82
#define LUSTRE_ELIBEXEC 83
#define LUSTRE_EILSEQ 84
#define LUSTRE_ERESTART 85
#define LUSTRE_ESTRPIPE 86
#define LUSTRE_EUSERS 87
#define LUSTRE_ENOTSOCK 88
#define LUSTRE_EDESTADDRREQ 89
#define LUSTRE_EMSGSIZE 90
#define LUSTRE_EPROTOTYPE 91
#define LUSTRE_ENOPROTOOPT 92
#define LUSTRE_EPROTONOSUPPORT 93
#define LUSTRE_ESOCKTNOSUPPORT 94
#define LUSTRE_EOPNOTSUPP 95
#define LUSTRE_EPFNOSUPPORT 96
#define LUSTRE_EAFNOSUPPORT 97
#define LUSTRE_EADDRINUSE 98
#define LUSTRE_EADDRNOTAVAIL 99
#define LUSTRE_ENETDOWN 100
#define LUSTRE_ENETUNREACH 101
#define LUSTRE_ENETRESET 102
#define LUSTRE_ECONNABORTED 103
#define LUSTRE_ECONNRESET 104
#define LUSTRE_ENOBUFS 105
#define LUSTRE_EISCONN 106
#define LUSTRE_ENOTCONN 107
#define LUSTRE_ESHUTDOWN 108
#define LUSTRE_ETOOMANYREFS 109
#define LUSTRE_ETIMEDOUT 110
#define LUSTRE_ECONNREFUSED 111
#define LUSTRE_EHOSTDOWN 112
#define LUSTRE_EHOSTUNREACH 113
#define LUSTRE_EALREADY 114
#define LUSTRE_EINPROGRESS 115
#define LUSTRE_ESTALE 116
#define LUSTRE_EUCLEAN 117
#define LUSTRE_ENOTNAM 118
#define LUSTRE_ENAVAIL 119
#define LUSTRE_EISNAM 120
#define LUSTRE_EREMOTEIO 121
#define LUSTRE_EDQUOT 122
#define LUSTRE_ENOMEDIUM 123
#define LUSTRE_EMEDIUMTYPE 124
#define LUSTRE_ECANCELED 125
#define LUSTRE_ENOKEY 126
#define LUSTRE_EKEYEXPIRED 127
#define LUSTRE_EKEYREVOKED 128
#define LUSTRE_EKEYREJECTED 129
#define LUSTRE_EOWNERDEAD 130
#define LUSTRE_ENOTRECOVERABLE 131
#define LUSTRE_ERESTARTSYS 512
#define LUSTRE_ERESTARTNOINTR 513
#define LUSTRE_ERESTARTNOHAND 514
#define LUSTRE_ENOIOCTLCMD 515
#define LUSTRE_ERESTART_RESTARTBLOCK 516
#define LUSTRE_EBADHANDLE 521
#define LUSTRE_ENOTSYNC 522
#define LUSTRE_EBADCOOKIE 523
#define LUSTRE_ENOTSUPP 524
#define LUSTRE_ETOOSMALL 525
#define LUSTRE_ESERVERFAULT 526
#define LUSTRE_EBADTYPE 527
#define LUSTRE_EJUKEBOX 528
#define LUSTRE_EIOCBQUEUED 529
#define LUSTRE_TRANSLATE_ERRNOS
Functions
unsigned int lustre_errno_hton (unsigned int h)
unsigned int lustre_errno_ntoh (unsigned int n)
Define Documentation
#define LUSTRE_E2BIG 7
Definition at line 47 of file lustre_errno.h.
#define LUSTRE_EACCES 13
Definition at line 53 of file lustre_errno.h.
#define LUSTRE_EADDRINUSE 98
Definition at line 146 of file lustre_errno.h.
#define LUSTRE_EADDRNOTAVAIL 99
Definition at line 147 of file lustre_errno.h.
#define LUSTRE_EADV 68
Definition at line 108 of file lustre_errno.h.
#define LUSTRE_EAFNOSUPPORT 97
Definition at line 144 of file lustre_errno.h.
#define LUSTRE_EAGAIN 11
Definition at line 51 of file lustre_errno.h.
#define LUSTRE_EALREADY 114
Definition at line 166 of file lustre_errno.h.
#define LUSTRE_EBADCOOKIE 523
Definition at line 192 of file lustre_errno.h.
#define LUSTRE_EBADE 52
Definition at line 93 of file lustre_errno.h.
#define LUSTRE_EBADF 9
Definition at line 49 of file lustre_errno.h.
#define LUSTRE_EBADFD 77
Definition at line 118 of file lustre_errno.h.
#define LUSTRE_EBADHANDLE 521
Definition at line 190 of file lustre_errno.h.
#define LUSTRE_EBADMSG 74
Definition at line 114 of file lustre_errno.h.
#define LUSTRE_EBADR 53
Definition at line 94 of file lustre_errno.h.
#define LUSTRE_EBADRQC 56
Definition at line 97 of file lustre_errno.h.
#define LUSTRE_EBADSLT 57
Definition at line 98 of file lustre_errno.h.
#define LUSTRE_EBADTYPE 527
Definition at line 196 of file lustre_errno.h.
#define LUSTRE_EBFONT 59
Definition at line 99 of file lustre_errno.h.
#define LUSTRE_EBUSY 16
Definition at line 56 of file lustre_errno.h.
#define LUSTRE_ECANCELED 125
Definition at line 177 of file lustre_errno.h.
#define LUSTRE_ECHILD 10
Definition at line 50 of file lustre_errno.h.
#define LUSTRE_ECHRNG 44
Definition at line 85 of file lustre_errno.h.
#define LUSTRE_ECOMM 70
Definition at line 110 of file lustre_errno.h.
#define LUSTRE_ECONNABORTED 103
Definition at line 152 of file lustre_errno.h.
#define LUSTRE_ECONNREFUSED 111
Definition at line 163 of file lustre_errno.h.
#define LUSTRE_ECONNRESET 104
Definition at line 153 of file lustre_errno.h.
#define LUSTRE_EDEADLK 35
Definition at line 76 of file lustre_errno.h.
Referenced by ldlm_cli_convert(), and ldlm_cli_convert_local().
#define LUSTRE_EDESTADDRREQ 89
Definition at line 135 of file lustre_errno.h.
#define LUSTRE_EDOM 33
Definition at line 73 of file lustre_errno.h.
#define LUSTRE_EDOTDOT 73
Definition at line 113 of file lustre_errno.h.
#define LUSTRE_EDQUOT 122
Definition at line 174 of file lustre_errno.h.
#define LUSTRE_EEXIST 17
Definition at line 57 of file lustre_errno.h.
#define LUSTRE_EFAULT 14
Definition at line 54 of file lustre_errno.h.
#define LUSTRE_EFBIG 27
Definition at line 67 of file lustre_errno.h.
#define LUSTRE_EHOSTDOWN 112
Definition at line 164 of file lustre_errno.h.
#define LUSTRE_EHOSTUNREACH 113
Definition at line 165 of file lustre_errno.h.
#define LUSTRE_EIDRM 43
Definition at line 84 of file lustre_errno.h.
#define LUSTRE_EILSEQ 84
Definition at line 129 of file lustre_errno.h.
#define LUSTRE_EINPROGRESS 115
Definition at line 167 of file lustre_errno.h.
#define LUSTRE_EINTR 4
Definition at line 44 of file lustre_errno.h.
#define LUSTRE_EINVAL 22
Definition at line 62 of file lustre_errno.h.
#define LUSTRE_EIO 5
Definition at line 45 of file lustre_errno.h.
Referenced by lustre_errno_hton().
#define LUSTRE_EIOCBQUEUED 529
Definition at line 199 of file lustre_errno.h.
#define LUSTRE_EISCONN 106
Definition at line 155 of file lustre_errno.h.
#define LUSTRE_EISDIR 21
Definition at line 61 of file lustre_errno.h.
#define LUSTRE_EISNAM 120
Definition at line 172 of file lustre_errno.h.
#define LUSTRE_EJUKEBOX 528
Definition at line 197 of file lustre_errno.h.
#define LUSTRE_EKEYEXPIRED 127
Definition at line 179 of file lustre_errno.h.
#define LUSTRE_EKEYREJECTED 129
Definition at line 181 of file lustre_errno.h.
#define LUSTRE_EKEYREVOKED 128
Definition at line 180 of file lustre_errno.h.
#define LUSTRE_EL2HLT 51
Definition at line 92 of file lustre_errno.h.
#define LUSTRE_EL2NSYNC 45
Definition at line 86 of file lustre_errno.h.
#define LUSTRE_EL3HLT 46
Definition at line 87 of file lustre_errno.h.
#define LUSTRE_EL3RST 47
Definition at line 88 of file lustre_errno.h.
#define LUSTRE_ELIBACC 79
Definition at line 120 of file lustre_errno.h.
#define LUSTRE_ELIBBAD 80
Definition at line 122 of file lustre_errno.h.
#define LUSTRE_ELIBEXEC 83
Definition at line 127 of file lustre_errno.h.
#define LUSTRE_ELIBMAX 82
Definition at line 125 of file lustre_errno.h.
#define LUSTRE_ELIBSCN 81
Definition at line 124 of file lustre_errno.h.
#define LUSTRE_ELNRNG 48
Definition at line 89 of file lustre_errno.h.
#define LUSTRE_ELOOP 40
Definition at line 81 of file lustre_errno.h.
#define LUSTRE_EMEDIUMTYPE 124
Definition at line 176 of file lustre_errno.h.
#define LUSTRE_EMFILE 24
Definition at line 64 of file lustre_errno.h.
#define LUSTRE_EMLINK 31
Definition at line 71 of file lustre_errno.h.
#define LUSTRE_EMSGSIZE 90
Definition at line 136 of file lustre_errno.h.
#define LUSTRE_EMULTIHOP 72
Definition at line 112 of file lustre_errno.h.
#define LUSTRE_ENAMETOOLONG 36
Definition at line 77 of file lustre_errno.h.
#define LUSTRE_ENAVAIL 119
Definition at line 171 of file lustre_errno.h.
#define LUSTRE_ENETDOWN 100
Definition at line 148 of file lustre_errno.h.
#define LUSTRE_ENETRESET 102
Definition at line 150 of file lustre_errno.h.
#define LUSTRE_ENETUNREACH 101
Definition at line 149 of file lustre_errno.h.
#define LUSTRE_ENFILE 23
Definition at line 63 of file lustre_errno.h.
#define LUSTRE_ENOANO 55
Definition at line 96 of file lustre_errno.h.
#define LUSTRE_ENOBUFS 105
Definition at line 154 of file lustre_errno.h.
#define LUSTRE_ENOCSI 50
Definition at line 91 of file lustre_errno.h.
#define LUSTRE_ENODATA 61
Definition at line 101 of file lustre_errno.h.
#define LUSTRE_ENODEV 19
Definition at line 59 of file lustre_errno.h.
#define LUSTRE_ENOENT 2
Definition at line 42 of file lustre_errno.h.
#define LUSTRE_ENOEXEC 8
Definition at line 48 of file lustre_errno.h.
#define LUSTRE_ENOIOCTLCMD 515
Definition at line 187 of file lustre_errno.h.
#define LUSTRE_ENOKEY 126
Definition at line 178 of file lustre_errno.h.
#define LUSTRE_ENOLCK 37
Definition at line 78 of file lustre_errno.h.
#define LUSTRE_ENOLINK 67
Definition at line 107 of file lustre_errno.h.
#define LUSTRE_ENOMEDIUM 123
Definition at line 175 of file lustre_errno.h.
#define LUSTRE_ENOMEM 12
Definition at line 52 of file lustre_errno.h.
#define LUSTRE_ENOMSG 42
Definition at line 83 of file lustre_errno.h.
#define LUSTRE_ENONET 64
Definition at line 104 of file lustre_errno.h.
#define LUSTRE_ENOPKG 65
Definition at line 105 of file lustre_errno.h.
#define LUSTRE_ENOPROTOOPT 92
Definition at line 138 of file lustre_errno.h.
#define LUSTRE_ENOSPC 28
Definition at line 68 of file lustre_errno.h.
#define LUSTRE_ENOSR 63
Definition at line 103 of file lustre_errno.h.
#define LUSTRE_ENOSTR 60
Definition at line 100 of file lustre_errno.h.
#define LUSTRE_ENOSYS 38
Definition at line 79 of file lustre_errno.h.
#define LUSTRE_ENOTBLK 15
Definition at line 55 of file lustre_errno.h.
#define LUSTRE_ENOTCONN 107
Definition at line 157 of file lustre_errno.h.
#define LUSTRE_ENOTDIR 20
Definition at line 60 of file lustre_errno.h.
#define LUSTRE_ENOTEMPTY 39
Definition at line 80 of file lustre_errno.h.
#define LUSTRE_ENOTNAM 118
Definition at line 170 of file lustre_errno.h.
#define LUSTRE_ENOTRECOVERABLE 131
Definition at line 183 of file lustre_errno.h.
#define LUSTRE_ENOTSOCK 88
Definition at line 134 of file lustre_errno.h.
#define LUSTRE_ENOTSUPP 524
Definition at line 193 of file lustre_errno.h.
#define LUSTRE_ENOTSYNC 522
Definition at line 191 of file lustre_errno.h.
#define LUSTRE_ENOTTY 25
Definition at line 65 of file lustre_errno.h.
#define LUSTRE_ENOTUNIQ 76
Definition at line 117 of file lustre_errno.h.
#define LUSTRE_ENXIO 6
Definition at line 46 of file lustre_errno.h.
#define LUSTRE_EOPNOTSUPP 95
Definition at line 141 of file lustre_errno.h.
#define LUSTRE_EOVERFLOW 75
Definition at line 115 of file lustre_errno.h.
#define LUSTRE_EOWNERDEAD 130
Definition at line 182 of file lustre_errno.h.
#define LUSTRE_EPERM 1
Definition at line 41 of file lustre_errno.h.
#define LUSTRE_EPFNOSUPPORT 96
Definition at line 143 of file lustre_errno.h.
#define LUSTRE_EPIPE 32
Definition at line 72 of file lustre_errno.h.
#define LUSTRE_EPROTO 71
Definition at line 111 of file lustre_errno.h.
#define LUSTRE_EPROTONOSUPPORT 93
Definition at line 139 of file lustre_errno.h.
#define LUSTRE_EPROTOTYPE 91
Definition at line 137 of file lustre_errno.h.
#define LUSTRE_ERANGE 34
Definition at line 75 of file lustre_errno.h.
#define LUSTRE_EREMCHG 78
Definition at line 119 of file lustre_errno.h.
#define LUSTRE_EREMOTE 66
Definition at line 106 of file lustre_errno.h.
#define LUSTRE_EREMOTEIO 121
Definition at line 173 of file lustre_errno.h.
#define LUSTRE_ERESTART 85
Definition at line 130 of file lustre_errno.h.
#define LUSTRE_ERESTART_RESTARTBLOCK 516
Definition at line 188 of file lustre_errno.h.
#define LUSTRE_ERESTARTNOHAND 514
Definition at line 186 of file lustre_errno.h.
#define LUSTRE_ERESTARTNOINTR 513
Definition at line 185 of file lustre_errno.h.
#define LUSTRE_ERESTARTSYS 512
Definition at line 184 of file lustre_errno.h.
#define LUSTRE_EROFS 30
Definition at line 70 of file lustre_errno.h.
#define LUSTRE_ESERVERFAULT 526
Definition at line 195 of file lustre_errno.h.
#define LUSTRE_ESHUTDOWN 108
Definition at line 159 of file lustre_errno.h.
#define LUSTRE_ESOCKTNOSUPPORT 94
Definition at line 140 of file lustre_errno.h.
#define LUSTRE_ESPIPE 29
Definition at line 69 of file lustre_errno.h.
#define LUSTRE_ESRCH 3
Definition at line 43 of file lustre_errno.h.
#define LUSTRE_ESRMNT 69
Definition at line 109 of file lustre_errno.h.
#define LUSTRE_ESTALE 116
Definition at line 168 of file lustre_errno.h.
Referenced by ldlm_cli_cancel_req().
#define LUSTRE_ESTRPIPE 86
Definition at line 132 of file lustre_errno.h.
#define LUSTRE_ETIME 62
Definition at line 102 of file lustre_errno.h.
#define LUSTRE_ETIMEDOUT 110
Definition at line 162 of file lustre_errno.h.
#define LUSTRE_ETOOMANYREFS 109
Definition at line 161 of file lustre_errno.h.
#define LUSTRE_ETOOSMALL 525
Definition at line 194 of file lustre_errno.h.
#define LUSTRE_ETXTBSY 26
Definition at line 66 of file lustre_errno.h.
#define LUSTRE_EUCLEAN 117
Definition at line 169 of file lustre_errno.h.
#define LUSTRE_EUNATCH 49
Definition at line 90 of file lustre_errno.h.
#define LUSTRE_EUSERS 87
Definition at line 133 of file lustre_errno.h.
#define LUSTRE_EXDEV 18
Definition at line 58 of file lustre_errno.h.
#define LUSTRE_EXFULL 54
Definition at line 95 of file lustre_errno.h.
#define LUSTRE_TRANSLATE_ERRNOS
Definition at line 207 of file lustre_errno.h.
Function Documentation
unsigned int lustre_errno_hton (unsigned int h)
Definition at line 337 of file errno.c.
References ARRAY_SIZE, LUSTRE_EIO, and lustre_errno_hton_mapping.
Referenced by mdc_ioc_hsm_progress(), and ptlrpc_status_hton().
unsigned int lustre_errno_ntoh (unsigned int n)
Definition at line 360 of file errno.c.
References ARRAY_SIZE, and lustre_errno_ntoh_mapping.
Referenced by mdt_hsm_progress(), and ptlrpc_status_ntoh().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.