Lustre: lustre/include/lustre_log_user.h File Reference
lustre/include/lustre_log_user.h File Reference
Functions
static void logid_to_fid (struct llog_logid *id, struct lu_fid *fid)
static void fid_to_logid (struct lu_fid *fid, struct llog_logid *id)
static void logid_set_id (struct llog_logid *log_id, __u64 id)
static __u64 logid_id (struct llog_logid *log_id)
Function Documentation
static void fid_to_logid (struct lu_fid * fid, struct llog_logid * id) [inline, static]
Definition at line 60 of file lustre_log_user.h.
References lu_fid::f_oid, and lu_fid::f_seq.
Referenced by llog_osd_open(), and llog_test_9_sub().
static __u64 logid_id (struct llog_logid * log_id) [inline, static]
Definition at line 72 of file lustre_log_user.h.
References llog_logid::lgl_oi, and ost_id::oi.
Referenced by lod_sub_prep_llog(), and osp_sync_llog_init().
static void logid_set_id (struct llog_logid * log_id, __u64 id) [inline, static]
Definition at line 67 of file lustre_log_user.h.
References llog_logid::lgl_oi, and ost_id::oi.
Referenced by lod_sub_prep_llog(), and osp_sync_llog_init().
static void logid_to_fid (struct llog_logid * id, struct lu_fid * fid) [inline, static]
Definition at line 46 of file lustre_log_user.h.
References lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, llog_logid::lgl_ogen, llog_logid::lgl_oi, lu_igif_build(), and ost_id::oi.
Referenced by cat_print_cb(), llog_osd_create(), llog_osd_declare_create(), llog_osd_open(), llog_test_9_sub(), plain_print_cb(), print_log_path(), and test_7_print_cb().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.