Lustre: lustre/include/lvfs.h File Reference
lustre/include/lvfs.h File Reference
#include <linux/dcache.h>
#include <linux/err.h>
#include <linux/fs.h>
#include <linux/mutex.h>
#include <linux/namei.h>
#include <lustre_compat.h>
Data Structures
struct lvfs_run_ctxt
Defines
#define OBD_RUN_CTXT_MAGIC 0xC0FFEEAA
#define OBD_CTXT_DEBUG
Functions
static void OBD_SET_CTXT_MAGIC (struct lvfs_run_ctxt *ctxt)
void push_ctxt (struct lvfs_run_ctxt *save, struct lvfs_run_ctxt *new_ctx)
void pop_ctxt (struct lvfs_run_ctxt *saved, struct lvfs_run_ctxt *new_ctx)
static struct dentry * ll_lookup_one_len (const char *fid_name, struct dentry *dparent, int fid_namelen)
Define Documentation
#define OBD_CTXT_DEBUG
Definition at line 52 of file lvfs.h.
#define OBD_RUN_CTXT_MAGIC 0xC0FFEEAA
Definition at line 51 of file lvfs.h.
Referenced by OBD_SET_CTXT_MAGIC().
Function Documentation
static struct dentry* ll_lookup_one_len (const char * fid_name, struct dentry * dparent, int fid_namelen) [static, read]
Definition at line 84 of file lvfs.h.
References CERROR.
Referenced by lustre_rename(), osd_ios_lookup_one_len(), osd_last_rcvd_subdir_count(), osd_obj_spec_lookup(), osd_oi_index_open(), osd_ost_init(), osd_remove_oi_one(), simple_mkdir(), and sptlrpc_target_local_copy_conf().
static void OBD_SET_CTXT_MAGIC (struct lvfs_run_ctxt * ctxt) [inline, static]
Definition at line 67 of file lvfs.h.
References lvfs_run_ctxt::magic, and OBD_RUN_CTXT_MAGIC.
Referenced by llog_test_setup(), mdd_changelog_llog_init(), mdd_hsm_actions_llog_init(), mgs_fs_setup(), osd_push_ctxt(), osd_scrub_setup(), osd_start(), osp_sync_llog_init(), and push_ctxt().
void pop_ctxt (struct lvfs_run_ctxt * saved, struct lvfs_run_ctxt * new_ctx)
Definition at line 78 of file sec_ctx.c.
References ASSERT_CTXT_MAGIC, ASSERT_KERNEL_CTXT, lvfs_run_ctxt::dt, lvfs_run_ctxt::fs, LASSERTF, ll_set_fs_pwd(), lvfs_run_ctxt::magic, lvfs_run_ctxt::pwd, lvfs_run_ctxt::pwdmnt, and lvfs_run_ctxt::umask.
Referenced by osd_mdt_init(), osd_ost_init(), osd_scrub_setup(), sptlrpc_target_local_copy_conf(), and sptlrpc_target_local_read_conf().
void push_ctxt (struct lvfs_run_ctxt * save, struct lvfs_run_ctxt * new_ctx)
Definition at line 50 of file sec_ctx.c.
References ASSERT_CTXT_MAGIC, lvfs_run_ctxt::dt, lvfs_run_ctxt::fs, LASSERT, ll_d_count, ll_set_fs_pwd(), lvfs_run_ctxt::magic, OBD_SET_CTXT_MAGIC(), lvfs_run_ctxt::pwd, lvfs_run_ctxt::pwdmnt, and lvfs_run_ctxt::umask.
Referenced by osd_push_ctxt(), osd_scrub_setup(), sptlrpc_target_local_copy_conf(), and sptlrpc_target_local_read_conf().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.