Lustre: lustre/osp/lwp_dev.c File Reference
lustre/osp/lwp_dev.c File Reference
#include <obd_class.h>
#include <lustre_param.h>
#include <lustre_log.h>
#include <linux/kthread.h>
#include "osp_internal.h"
Data Structures
struct lwp_device
Defines
#define DEBUG_SUBSYSTEM S_OST
Functions
static struct lwp_device * lu2lwp_dev (struct lu_device *d)
static struct lu_device * lwp2lu_dev (struct lwp_device *d)
static int lwp_setup (const struct lu_env *env, struct lwp_device *lwp, char *nidstring)
Setup LWP device.
static int lwp_disconnect (struct lwp_device *d)
Disconnect the import from LWP.
static int lwp_process_config (const struct lu_env *env, struct lu_device *dev, struct lustre_cfg *lcfg)
Implementation of lu_device_operations::ldo_process_config.
static int lwp_init0 (const struct lu_env *env, struct lwp_device *lwp, struct lu_device_type *ldt, struct lustre_cfg *cfg)
Initialize LWP device.
static struct lu_device * lwp_device_free (const struct lu_env *env, struct lu_device *lu)
Implementation of lu_device_type_operations::ldto_device_free.
static struct lu_device * lwp_device_alloc (const struct lu_env *env, struct lu_device_type *ldt, struct lustre_cfg *lcfg)
Implementation of lu_device_type_operations::ldto_device_alloc.
static struct lu_device * lwp_device_fini (const struct lu_env *env, struct lu_device *ludev)
Implementation of lu_device_type_operations::ltdo_device_fini.
static int lwp_notify_main (void *args)
static void lwp_notify_users (struct obd_export *exp)
static int lwp_obd_connect (const struct lu_env *env, struct obd_export **exp, struct obd_device *obd, struct obd_uuid *cluuid, struct obd_connect_data *data, void *localdata)
Implementation of OBD device operations obd_ops::o_connect.
static int lwp_obd_disconnect (struct obd_export *exp)
Implementation of OBD device operations obd_ops::o_disconnect.
static int lwp_import_event (struct obd_device *obd, struct obd_import *imp, enum obd_import_event event)
Handle import events for the LWP device.
static int lwp_set_info_async (const struct lu_env *env, struct obd_export *exp, u32 keylen, void *key, u32 vallen, void *val, struct ptlrpc_request_set *set)
Variables
static struct lu_device_operations lwp_lu_ops
static struct
lu_device_type_operations lwp_device_type_ops
struct lu_device_type lwp_device_type
struct obd_ops lwp_obd_device_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_OST
Definition at line 40 of file lwp_dev.c.
Function Documentation
static struct lwp_device* lu2lwp_dev (struct lu_device * d) [static, read]
Definition at line 58 of file lwp_dev.c.
References lwp_device::lpd_dev.
Referenced by lwp_device_fini(), lwp_device_free(), lwp_notify_main(), lwp_notify_users(), lwp_obd_connect(), lwp_obd_disconnect(), and lwp_process_config().
static struct lu_device* lwp2lu_dev (struct lwp_device * d) [static, read]
Definition at line 63 of file lwp_dev.c.
References lwp_device::lpd_dev.
Referenced by lwp_device_alloc().
static struct lu_device* lwp_device_alloc (const struct lu_env * env, struct lu_device_type * ldt, struct lustre_cfg * lcfg) [static, read]
Implementation of lu_device_type_operations::ldto_device_alloc.
Allocate a LWP device.
Parameters:
[in] env environment passed by caller
[in] ldt device type whose name is LUSTRE_LWP_NAME
[in] lcfg lustre_cfg contains remote target UUID
Return values:
pointer of allocated LWP device on success
ERR_PTR(errno) on error
Definition at line 323 of file lwp_dev.c.
References lwp_device::lpd_dev, lu_device_init(), lwp2lu_dev(), lwp_device_free(), lwp_init0(), and OBD_ALLOC_PTR.
static struct lu_device* lwp_device_fini (const struct lu_env * env, struct lu_device * ludev) [static, read]
Implementation of lu_device_type_operations::ltdo_device_fini.
Finalize LWP device.
Parameters:
[in] env environment passed by caller
[in] ludev device to be finalized
Return values:
NULL on success
Definition at line 358 of file lwp_dev.c.
References client_obd::cl_import, class_disconnect(), obd_device::cli, client_obd_cleanup(), ENTRY, l_wait_event, LASSERT, LASSERTF, lwp_device::lpd_exp, lwp_device::lpd_notify_thread, lwp_device::lpd_obd, lprocfs_obd_cleanup(), lu2lwp_dev(), ptlrpc_lprocfs_unregister_obd(), ptlrpcd_decref(), RETURN, ptlrpc_thread::t_ctl_waitq, thread, thread_is_stopped(), and obd_device::u.
static struct lu_device* lwp_device_free (const struct lu_env * env, struct lu_device * lu) [static, read]
Implementation of lu_device_type_operations::ldto_device_free.
Free a LWP device.
Parameters:
[in] env environment passed by caller
[in] lu device to be freed
Return values:
NULL to indicate that this is the bottom device of the stack and there are no more devices below this one to be cleaned up.
Definition at line 296 of file lwp_dev.c.
References D_ERROR, ENTRY, lu_device::ld_ref, lu_device::ld_site, LIBCFS_DEBUG_MSG_DATA_DECL, lwp_device::lpd_dev, lu2lwp_dev(), lu_cdebug_printer(), lu_device_fini(), lu_site_print(), OBD_FREE_PTR, and RETURN.
Referenced by lwp_device_alloc().
static int lwp_disconnect (struct lwp_device * d) [static]
Disconnect the import from LWP.
Parameters:
[in] d LWP device to be disconnected
Return values:
0 on success
negative number on error
Definition at line 156 of file lwp_dev.c.
References client_obd::cl_import, obd_device::cli, CWARN, obd_import::imp_deactive, obd_import::imp_lock, LASSERT, lwp_device::lpd_obd, obd_device::obd_name, ptlrpc_deactivate_import(), ptlrpc_disconnect_import(), ptlrpc_invalidate_import(), ptlrpc_pinger_del_import(), RETURN, and obd_device::u.
Referenced by lwp_process_config().
static int lwp_import_event (struct obd_device * obd, struct obd_import * imp, enum obd_import_event event) [static]
Handle import events for the LWP device.
Parameters:
[in] obd OBD device associated with the import
[in] imp the import which event happened on
[in] event event type
Return values:
0 on success
negative number on error
Definition at line 582 of file lwp_dev.c.
References CERROR, IMP_EVENT_ACTIVE, IMP_EVENT_DISCON, IMP_EVENT_INACTIVE, IMP_EVENT_INVALIDATE, IMP_EVENT_OCD, LDLM_FL_LOCAL_ONLY, ldlm_namespace_cleanup(), obd_device::obd_name, and obd_device::obd_namespace.
static int lwp_init0 (const struct lu_env * env, struct lwp_device * lwp, struct lu_device_type * ldt, struct lustre_cfg * cfg) [static]
Initialize LWP device.
Parameters:
[in] env environment passed by caller
[in] lwp device to be initialized
[in] ldt not used
[in] cfg lustre_cfg contains remote target uuid
Return values:
0 on success
-ENODEV if the device name cannot be found
negative numbers on other errors
Definition at line 245 of file lwp_dev.c.
References CERROR, class_name2obd(), ENTRY, lu_device::ld_ops, lwp_device::lpd_dev, lwp_device::lpd_obd, lprocfs_obd_setup(), lustre_cfg_string(), lwp_setup(), obd_device::obd_lu_dev, obd_device::obd_name, ptlrpc_lprocfs_register_obd(), ptlrpcd_addref(), ptlrpcd_decref(), RETURN, and sptlrpc_lprocfs_cliobd_attach().
Referenced by lwp_device_alloc().
static int lwp_notify_main (void * args) [static]
Definition at line 402 of file lwp_dev.c.
References obd_export::exp_obd, LASSERT, lwp_device::lpd_notify_thread, lu2lwp_dev(), lustre_notify_lwp_list(), obd_device::obd_lu_dev, SVC_RUNNING, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, thread, and thread_set_flags().
Referenced by lwp_notify_users().
static void lwp_notify_users (struct obd_export * exp) [static]
Definition at line 427 of file lwp_dev.c.
References CERROR, obd_export::exp_obd, l_wait_event, LASSERT, lwp_device::lpd_notify_thread, lu2lwp_dev(), lwp_notify_main(), MTI_NAME_MAXLEN, name, obd_device::obd_lu_dev, obd_device::obd_name, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, thread, thread_is_running(), thread_is_stopped(), and thread_set_flags().
Referenced by lwp_obd_connect().
static int lwp_obd_connect (const struct lu_env * env, struct obd_export ** exp, struct obd_device * obd, struct obd_uuid * cluuid, struct obd_connect_data * data, void * localdata) [static]
Implementation of OBD device operations obd_ops::o_connect.
Create export for LWP, and connect to target server.
Parameters:
[in] env the environment passed by caller
[out] exp export for the connection to be established
[in] obd OBD device to perform the connect on
[in] cluuid UUID of the OBD device
[in] data connect data containing compatibility flags
[in] localdata not used
Return values:
0 on success
negative number on error
Definition at line 476 of file lwp_dev.c.
References CDEBUG, CERROR, client_obd::cl_import, client_obd::cl_sem, class_conn2export(), class_connect(), class_disconnect(), obd_device::cli, D_CONFIG, ENTRY, GOTO, obd_import::imp_connect_data, obd_import::imp_connect_flags_orig, obd_import::imp_dlm_handle, LASSERT, lwp_device::lpd_connects, lwp_device::lpd_exp, lwp_device::lpd_obd, lu2lwp_dev(), LUSTRE_VERSION_CODE, lwp_notify_users(), OBD_CONNECT_LIGHTWEIGHT, obd_device::obd_lu_dev, obd_device::obd_name, obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_version, ptlrpc_connect_import(), ptlrpc_init_import(), ptlrpc_pinger_add_import(), and obd_device::u.
static int lwp_obd_disconnect (struct obd_export * exp) [static]
Implementation of OBD device operations obd_ops::o_disconnect.
Release export for the LWP. Only disconnect the underlying layers on the final disconnect.
Parameters:
[in] exp the export to perform disconnect on
Return values:
0 on success
negative number on error
Definition at line 554 of file lwp_dev.c.
References CERROR, class_disconnect(), ENTRY, obd_export::exp_obd, LASSERT, lwp_device::lpd_connects, lu2lwp_dev(), obd_device::obd_lu_dev, obd_device::obd_name, and RETURN.
static int lwp_process_config (const struct lu_env * env, struct lu_device * dev, struct lustre_cfg * lcfg) [static]
Implementation of lu_device_operations::ldo_process_config.
Process a Lustre configuration request.
Parameters:
[in] env environment passed by caller
[in] dev device to be processed
[in] lcfg lustre_cfg, LCFG_PRE_CLEANUP or LCFG_CLEANUP
Return values:
0 on success
negative number on error
Definition at line 204 of file lwp_dev.c.
References CERROR, ENTRY, LCFG_CLEANUP, lustre_cfg::lcfg_command, LCFG_PARAM, LCFG_PRE_CLEANUP, lu2lwp_dev(), lustre_cfg_string(), lwp_disconnect(), and RETURN.
static int lwp_set_info_async (const struct lu_env * env, struct obd_export * exp, u32 keylen, void * key, u32 vallen, void * val, struct ptlrpc_request_set * set) [static]
Definition at line 604 of file lwp_dev.c.
References CERROR, ENTRY, obd_export::exp_obd, KEY_IS, KEY_SPTLRPC_CONF, RETURN, and sptlrpc_conf_client_adapt().
static int lwp_setup (const struct lu_env * env, struct lwp_device * lwp, char * nidstring) [static]
Setup LWP device.
Parameters:
[in] env environment passed by caller
[in] lwp LWP device to be setup
[in] nidstring remote target NID
Return values:
0 on success
negative number on error
Definition at line 78 of file lwp_dev.c.
References CERROR, cfs_strrstr(), client_obd::cl_import, class_uuid_unparse(), obd_device::cli, client_obd_cleanup(), client_obd_setup(), ENTRY, GOTO, LCFG_SETUP, ll_generate_random_uuid, lwp_device::lpd_cluuid, lwp_device::lpd_notify_thread, lwp_device::lpd_obd, lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), LUSTRE_LWP_NAME, OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, obd_device::obd_name, ptlrpc_init_import(), RETURN, strlcat(), SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, thread_set_flags(), obd_device::u, and uuid.
Referenced by lwp_init0().
Variable Documentation
struct lu_device_type lwp_device_type
Initial value:
 {
        .ldt_tags     = LU_DEVICE_DT,
        .ldt_name     = LUSTRE_LWP_NAME,
        .ldt_ops      = &lwp_device_type_ops,
        .ldt_ctx_tags = LCT_MD_THREAD
}
Definition at line 395 of file lwp_dev.c.
Referenced by osp_init().
struct lu_device_type_operations lwp_device_type_ops [static]
Initial value:
 {
        .ldto_device_alloc   = lwp_device_alloc,
        .ldto_device_free    = lwp_device_free,
        .ldto_device_fini    = lwp_device_fini
}
Definition at line 389 of file lwp_dev.c.
struct lu_device_operations lwp_lu_ops [static]
Initial value:
 {
        .ldo_process_config     = lwp_process_config,
}
Definition at line 229 of file lwp_dev.c.
struct obd_ops lwp_obd_device_ops
Initial value:
 {
        .o_owner        = THIS_MODULE,
        .o_add_conn     = client_import_add_conn,
        .o_del_conn     = client_import_del_conn,
        .o_connect      = lwp_obd_connect,
        .o_disconnect   = lwp_obd_disconnect,
        .o_import_event = lwp_import_event,
        .o_set_info_async   = lwp_set_info_async,
}
Definition at line 621 of file lwp_dev.c.
Referenced by osp_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.