Lustre: lustre/mdc/mdc_lib.c File Reference
lustre/mdc/mdc_lib.c File Reference
#include <linux/user_namespace.h>
#include <lustre_net.h>
#include <lustre/lustre_idl.h>
#include <obd_class.h>
#include <obd.h>
#include <cl_object.h>
#include "mdc_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_MDC
Functions
static void __mdc_pack_body (struct mdt_body *b, __u32 suppgid)
void mdc_swap_layouts_pack (struct ptlrpc_request *req, struct md_op_data *op_data)
void mdc_pack_body (struct ptlrpc_request *req, const struct lu_fid *fid, u64 valid, size_t ea_size, u32 suppgid, u32 flags)
static void mdc_pack_name (struct ptlrpc_request *req, const struct req_msg_field *field, const char *name, size_t name_len)
Pack a name (path component) into a request.
void mdc_readdir_pack (struct ptlrpc_request *req, __u64 pgoff, size_t size, const struct lu_fid *fid)
void mdc_create_pack (struct ptlrpc_request *req, struct md_op_data *op_data, const void *data, size_t datalen, umode_t mode, uid_t uid, gid_t gid, cfs_cap_t cap_effective, __u64 rdev)
static __u64 mds_pack_open_flags (__u64 flags)
void mdc_open_pack (struct ptlrpc_request *req, struct md_op_data *op_data, umode_t mode, __u64 rdev, __u64 flags, const void *lmm, size_t lmmlen)
static __u64 attr_pack (unsigned int ia_valid)
static void mdc_setattr_pack_rec (struct mdt_rec_setattr *rec, struct md_op_data *op_data)
static void mdc_ioepoch_pack (struct mdt_ioepoch *epoch, struct md_op_data *op_data)
void mdc_setattr_pack (struct ptlrpc_request *req, struct md_op_data *op_data, void *ea, size_t ealen)
void mdc_unlink_pack (struct ptlrpc_request *req, struct md_op_data *op_data)
void mdc_link_pack (struct ptlrpc_request *req, struct md_op_data *op_data)
static void mdc_intent_close_pack (struct ptlrpc_request *req, struct md_op_data *op_data)
void mdc_rename_pack (struct ptlrpc_request *req, struct md_op_data *op_data, const char *old, size_t oldlen, const char *new, size_t newlen)
void mdc_getattr_pack (struct ptlrpc_request *req, __u64 valid, __u32 flags, struct md_op_data *op_data, size_t ea_size)
void mdc_close_pack (struct ptlrpc_request *req, struct md_op_data *op_data)
Define Documentation
#define DEBUG_SUBSYSTEM S_MDC
Definition at line 37 of file mdc_lib.c.
Function Documentation
static void __mdc_pack_body (struct mdt_body * b, __u32 suppgid) [static]
Definition at line 50 of file mdc_lib.c.
References cfs_curproc_cap_pack(), from_kgid(), from_kuid(), LASSERT, mdt_body::mbo_capability, mdt_body::mbo_fsgid, mdt_body::mbo_fsuid, mdt_body::mbo_gid, mdt_body::mbo_suppgid, and mdt_body::mbo_uid.
Referenced by mdc_getattr_pack(), mdc_pack_body(), mdc_readdir_pack(), and mdc_swap_layouts_pack().
static __u64 attr_pack (unsigned int ia_valid) [inline, static]
Definition at line 250 of file mdc_lib.c.
References __u64, ATTR_BLOCKS, ATTR_CTIME_SET, ATTR_FROM_OPEN, MDS_ATTR_ATIME, MDS_ATTR_ATIME_SET, MDS_ATTR_ATTR_FLAG, MDS_ATTR_BLOCKS, MDS_ATTR_CTIME, MDS_ATTR_CTIME_SET, MDS_ATTR_FORCE, MDS_ATTR_FROM_OPEN, MDS_ATTR_GID, MDS_ATTR_KILL_SGID, MDS_ATTR_KILL_SUID, MDS_ATTR_MODE, MDS_ATTR_MTIME, MDS_ATTR_MTIME_SET, MDS_ATTR_SIZE, MDS_ATTR_UID, and MDS_OPEN_OWNEROVERRIDE.
Referenced by mdc_setattr_pack_rec().
void mdc_close_pack (struct ptlrpc_request * req, struct md_op_data * op_data)
Definition at line 487 of file mdc_lib.c.
References mdc_intent_close_pack(), mdc_ioepoch_pack(), mdc_setattr_pack_rec(), MDS_ATTR_ATIME, req_capsule_client_get(), RMF_MDT_EPOCH, RMF_REC_REINT, ptlrpc_request::rq_pill, mdt_rec_setattr::sa_atime, and mdt_rec_setattr::sa_valid.
Referenced by mdc_close().
void mdc_create_pack (struct ptlrpc_request * req, struct md_op_data * op_data, const void * data, size_t datalen, umode_t mode, uid_t uid, gid_t gid, cfs_cap_t cap_effective, __u64 rdev)
Definition at line 136 of file mdc_lib.c.
References __u64, CLASSERT, mdt_rec_create::cr_bias, mdt_rec_create::cr_cap, mdt_rec_create::cr_fid1, mdt_rec_create::cr_fid2, mdt_rec_create::cr_fsgid, mdt_rec_create::cr_fsuid, mdt_rec_create::cr_mode, mdt_rec_create::cr_opcode, mdt_rec_create::cr_rdev, mdt_rec_create::cr_suppgid1, mdt_rec_create::cr_suppgid2, mdt_rec_create::cr_time, mdt_rec_create::cr_umask, mdc_pack_name(), MDS_CREATE_VOLATILE, MDS_OPEN_VOLATILE, md_op_data::op_bias, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_mod_time, md_op_data::op_name, md_op_data::op_namelen, md_op_data::op_suppgids, REINT_CREATE, req_capsule_client_get(), RMF_EADATA, RMF_NAME, RMF_REC_REINT, ptlrpc_request::rq_pill, and set_mrc_cr_flags().
Referenced by mdc_create().
void mdc_getattr_pack (struct ptlrpc_request * req, __u64 valid, __u32 flags, struct md_op_data * op_data, size_t ea_size)
Definition at line 463 of file mdc_lib.c.
References __mdc_pack_body(), mdt_body::mbo_eadatasize, mdt_body::mbo_fid1, mdt_body::mbo_fid2, mdt_body::mbo_flags, mdt_body::mbo_valid, mdc_pack_name(), MDS_CHECK_SPLIT, MDS_CROSS_REF, OBD_MD_FLCKSPLIT, OBD_MD_FLCROSSREF, OBD_MD_FLID, md_op_data::op_bias, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_name, md_op_data::op_namelen, md_op_data::op_suppgids, req_capsule_client_get(), RMF_MDT_BODY, RMF_NAME, and ptlrpc_request::rq_pill.
Referenced by mdc_intent_getattr_pack().
static void mdc_intent_close_pack (struct ptlrpc_request * req, struct md_op_data * op_data) [static]
Definition at line 400 of file mdc_lib.c.
References close_data::cd_data_version, close_data::cd_fid, close_data::cd_handle, ldlm_lock::l_remote_handle, LASSERT, LCF_LOCAL, ldlm_cli_cancel(), ldlm_handle2lock(), LDLM_LOCK_PUT, MDS_CLOSE_LAYOUT_SWAP, MDS_HSM_RELEASE, MDS_RENAME_MIGRATE, md_op_data::op_bias, md_op_data::op_data_version, md_op_data::op_fid2, md_op_data::op_lease_handle, req_capsule_client_get(), RMF_CLOSE_DATA, and ptlrpc_request::rq_pill.
Referenced by mdc_close_pack(), and mdc_rename_pack().
static void mdc_ioepoch_pack (struct mdt_ioepoch * epoch, struct md_op_data * op_data) [static]
Definition at line 321 of file mdc_lib.c.
References mdt_ioepoch::mio_handle, mdt_ioepoch::mio_padding, mdt_ioepoch::mio_unused1, mdt_ioepoch::mio_unused2, and md_op_data::op_handle.
Referenced by mdc_close_pack(), and mdc_rename_pack().
void mdc_link_pack (struct ptlrpc_request * req, struct md_op_data * op_data)
Definition at line 378 of file mdc_lib.c.
References CLASSERT, LASSERT, mdt_rec_link::lk_bias, mdt_rec_link::lk_cap, mdt_rec_link::lk_fid1, mdt_rec_link::lk_fid2, mdt_rec_link::lk_fsgid, mdt_rec_link::lk_fsuid, mdt_rec_link::lk_opcode, mdt_rec_link::lk_suppgid1, mdt_rec_link::lk_suppgid2, mdt_rec_link::lk_time, mdc_pack_name(), md_op_data::op_bias, md_op_data::op_cap, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_fsgid, md_op_data::op_fsuid, md_op_data::op_mod_time, md_op_data::op_name, md_op_data::op_namelen, md_op_data::op_suppgids, REINT_LINK, req_capsule_client_get(), RMF_NAME, RMF_REC_REINT, and ptlrpc_request::rq_pill.
Referenced by mdc_link().
void mdc_open_pack (struct ptlrpc_request * req, struct md_op_data * op_data, umode_t mode, __u64 rdev, __u64 flags, const void * lmm, size_t lmmlen)
Definition at line 204 of file mdc_lib.c.
References __u64, cfs_curproc_cap_pack(), CLASSERT, mdt_rec_create::cr_bias, mdt_rec_create::cr_cap, mdt_rec_create::cr_fid1, mdt_rec_create::cr_fid2, mdt_rec_create::cr_fsgid, mdt_rec_create::cr_fsuid, mdt_rec_create::cr_mode, mdt_rec_create::cr_old_handle, mdt_rec_create::cr_opcode, mdt_rec_create::cr_rdev, mdt_rec_create::cr_suppgid1, mdt_rec_create::cr_suppgid2, mdt_rec_create::cr_time, mdt_rec_create::cr_umask, from_kgid(), from_kuid(), mdc_pack_name(), MDS_CREATE_VOLATILE, MDS_OPEN_HAS_EA, MDS_OPEN_VOLATILE, mds_pack_open_flags(), md_op_data::op_bias, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_handle, md_op_data::op_mod_time, md_op_data::op_name, md_op_data::op_namelen, md_op_data::op_suppgids, REINT_OPEN, req_capsule_client_get(), RMF_EADATA, RMF_NAME, RMF_REC_REINT, ptlrpc_request::rq_pill, and set_mrc_cr_flags().
Referenced by mdc_intent_open_pack().
void mdc_pack_body (struct ptlrpc_request * req, const struct lu_fid * fid, u64 valid, size_t ea_size, u32 suppgid, u32 flags)
Definition at line 74 of file mdc_lib.c.
References __mdc_pack_body(), LASSERT, mdt_body::mbo_eadatasize, mdt_body::mbo_fid1, mdt_body::mbo_flags, mdt_body::mbo_valid, OBD_MD_FLID, req_capsule_client_get(), RMF_MDT_BODY, and ptlrpc_request::rq_pill.
Referenced by mdc_fsync(), mdc_get_remote_perm(), mdc_get_root(), mdc_getattr(), mdc_getattr_name(), mdc_intent_getxattr_pack(), mdc_ioc_hsm_ct_register(), mdc_ioc_hsm_ct_unregister(), mdc_ioc_hsm_current_action(), mdc_ioc_hsm_progress(), mdc_ioc_hsm_request(), mdc_ioc_hsm_state_get(), mdc_ioc_hsm_state_set(), and mdc_xattr_common().
static void mdc_pack_name (struct ptlrpc_request * req, const struct req_msg_field * field, const char * name, size_t name_len) [static]
Pack a name (path component) into a request.
Parameters:
[in] req request
[in] field request field (usually RMF_NAME)
[in] name path component
[in] name_len length of path component
field must be present in req and of size name_len + 1.
name must be '' terminated of length name_len and represent a single path component (not contain '/').
Definition at line 103 of file mdc_lib.c.
References buf, LASSERT, lu_name_is_valid_2(), RCL_CLIENT, req_capsule_client_get(), req_capsule_get_size(), ptlrpc_request::rq_pill, and strlcpy().
Referenced by mdc_create_pack(), mdc_getattr_pack(), mdc_link_pack(), mdc_open_pack(), mdc_rename_pack(), and mdc_unlink_pack().
void mdc_readdir_pack (struct ptlrpc_request * req, __u64 pgoff, size_t size, const struct lu_fid * fid)
Definition at line 122 of file mdc_lib.c.
References __mdc_pack_body(), LUDA_FID, LUDA_TYPE, mdt_body::mbo_fid1, mdt_body::mbo_mode, mdt_body::mbo_nlink, mdt_body::mbo_size, mdt_body::mbo_valid, OBD_MD_FLID, req_capsule_client_get(), RMF_MDT_BODY, and ptlrpc_request::rq_pill.
Referenced by mdc_getpage().
void mdc_rename_pack (struct ptlrpc_request * req, struct md_op_data * op_data, const char * old, size_t oldlen, const char * new, size_t newlen)
Definition at line 425 of file mdc_lib.c.
References CLASSERT, CLI_MIGRATE, mdc_intent_close_pack(), mdc_ioepoch_pack(), mdc_pack_name(), MDS_RENAME_MIGRATE, md_op_data::op_bias, md_op_data::op_cap, md_op_data::op_cli_flags, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_fsgid, md_op_data::op_fsuid, md_op_data::op_mod_time, md_op_data::op_mode, md_op_data::op_suppgids, REINT_MIGRATE, REINT_RENAME, req_capsule_client_get(), RMF_MDT_EPOCH, RMF_NAME, RMF_REC_REINT, RMF_SYMTGT, mdt_rec_rename::rn_bias, mdt_rec_rename::rn_cap, mdt_rec_rename::rn_fid1, mdt_rec_rename::rn_fid2, mdt_rec_rename::rn_fsgid, mdt_rec_rename::rn_fsuid, mdt_rec_rename::rn_mode, mdt_rec_rename::rn_opcode, mdt_rec_rename::rn_suppgid1, mdt_rec_rename::rn_suppgid2, mdt_rec_rename::rn_time, and ptlrpc_request::rq_pill.
Referenced by mdc_rename().
void mdc_setattr_pack (struct ptlrpc_request * req, struct md_op_data * op_data, void * ea, size_t ealen)
Definition at line 330 of file mdc_lib.c.
References CLASSERT, cpu_to_le32, LOV_USER_MAGIC_V1, lov_user_md, mdc_setattr_pack_rec(), req_capsule_client_get(), RMF_EADATA, RMF_REC_REINT, and ptlrpc_request::rq_pill.
Referenced by mdc_setattr().
static void mdc_setattr_pack_rec (struct mdt_rec_setattr * rec, struct md_op_data * op_data) [static]
Definition at line 291 of file mdc_lib.c.
References attr_pack(), cfs_curproc_cap_pack(), from_kgid(), from_kuid(), LTIME_S, md_op_data::op_attr, md_op_data::op_attr_blocks, md_op_data::op_attr_flags, md_op_data::op_bias, md_op_data::op_fid1, md_op_data::op_suppgids, REINT_SETATTR, mdt_rec_setattr::sa_atime, mdt_rec_setattr::sa_attr_flags, mdt_rec_setattr::sa_bias, mdt_rec_setattr::sa_blocks, mdt_rec_setattr::sa_cap, mdt_rec_setattr::sa_ctime, mdt_rec_setattr::sa_fid, mdt_rec_setattr::sa_fsgid, mdt_rec_setattr::sa_fsuid, mdt_rec_setattr::sa_gid, mdt_rec_setattr::sa_mode, mdt_rec_setattr::sa_mtime, mdt_rec_setattr::sa_opcode, mdt_rec_setattr::sa_size, mdt_rec_setattr::sa_suppgid, mdt_rec_setattr::sa_uid, and mdt_rec_setattr::sa_valid.
Referenced by mdc_close_pack(), and mdc_setattr_pack().
void mdc_swap_layouts_pack (struct ptlrpc_request * req, struct md_op_data * op_data)
Definition at line 62 of file mdc_lib.c.
References __mdc_pack_body(), mdt_body::mbo_fid1, mdt_body::mbo_fid2, mdt_body::mbo_valid, OBD_MD_FLID, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_suppgids, req_capsule_client_get(), RMF_MDT_BODY, and ptlrpc_request::rq_pill.
Referenced by mdc_ioc_swap_layouts().
void mdc_unlink_pack (struct ptlrpc_request * req, struct md_op_data * op_data)
Definition at line 354 of file mdc_lib.c.
References CLASSERT, CLI_RM_ENTRY, LASSERT, mdc_pack_name(), md_op_data::op_bias, md_op_data::op_cap, md_op_data::op_cli_flags, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_fsgid, md_op_data::op_fsuid, md_op_data::op_mod_time, md_op_data::op_mode, md_op_data::op_name, md_op_data::op_namelen, md_op_data::op_suppgids, REINT_RMENTRY, REINT_UNLINK, req_capsule_client_get(), RMF_NAME, RMF_REC_REINT, ptlrpc_request::rq_pill, mdt_rec_unlink::ul_bias, mdt_rec_unlink::ul_cap, mdt_rec_unlink::ul_fid1, mdt_rec_unlink::ul_fid2, mdt_rec_unlink::ul_fsgid, mdt_rec_unlink::ul_fsuid, mdt_rec_unlink::ul_mode, mdt_rec_unlink::ul_opcode, mdt_rec_unlink::ul_suppgid1, mdt_rec_unlink::ul_suppgid2, and mdt_rec_unlink::ul_time.
Referenced by mdc_intent_unlink_pack(), and mdc_unlink().
static __u64 mds_pack_open_flags (__u64 flags) [inline, static]
Definition at line 173 of file mdc_lib.c.
References __u64, cl_is_lov_delay_create(), FMODE_EXEC, FMODE_READ, FMODE_WRITE, MDS_FMODE_EXEC, MDS_OPEN_APPEND, MDS_OPEN_CREAT, MDS_OPEN_DELAY_CREATE, MDS_OPEN_DIRECTORY, MDS_OPEN_EXCL, MDS_OPEN_FL_INTERNAL, MDS_OPEN_NORESTORE, MDS_OPEN_SYNC, and MDS_OPEN_TRUNC.
Referenced by mdc_open_pack().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.