Lustre: lustre/mdc/mdc_reint.c File Reference
lustre/mdc/mdc_reint.c File Reference
#include <linux/module.h>
#include <linux/kernel.h>
#include <obd_class.h>
#include "mdc_internal.h"
#include <lustre_fid.h>
Defines
#define DEBUG_SUBSYSTEM S_MDC
Functions
static int mdc_reint (struct ptlrpc_request *request, int level)
int mdc_resource_get_unused (struct obd_export *exp, const struct lu_fid *fid, struct list_head *cancels, enum ldlm_mode mode, __u64 bits)
int mdc_setattr (struct obd_export *exp, struct md_op_data *op_data, void *ea, size_t ealen, struct ptlrpc_request **request)
int mdc_create (struct obd_export *exp, struct md_op_data *op_data, const void *data, size_t datalen, umode_t mode, uid_t uid, gid_t gid, cfs_cap_t cap_effective, __u64 rdev, struct ptlrpc_request **request)
int mdc_unlink (struct obd_export *exp, struct md_op_data *op_data, struct ptlrpc_request **request)
int mdc_link (struct obd_export *exp, struct md_op_data *op_data, struct ptlrpc_request **request)
int mdc_rename (struct obd_export *exp, struct md_op_data *op_data, const char *old, size_t oldlen, const char *new, size_t newlen, struct ptlrpc_request **request)
Define Documentation
#define DEBUG_SUBSYSTEM S_MDC
Definition at line 37 of file mdc_reint.c.
Function Documentation
int mdc_create (struct obd_export * exp, struct md_op_data * op_data, const void * data, size_t datalen, umode_t mode, uid_t uid, gid_t gid, cfs_cap_t cap_effective, __u64 rdev, struct ptlrpc_request ** request)
Definition at line 155 of file mdc_reint.c.
References CDEBUG, cfs_time_current_sec(), client_obd::cl_import, class_exp2cliimp(), obd_device::cli, D_HA, DFID, ENTRY, obd_export::exp_obd, fid_is_sane(), obd_import::imp_generation, LCK_EX, ldlm_lock_list_put, LIST_HEAD_INIT, LUSTRE_IMP_FULL, LUSTRE_IMP_RECOVER, mdc_create_pack(), mdc_fid_alloc(), mdc_prep_elc_req(), mdc_reint(), mdc_resource_get_unused(), MDS_INODELOCK_UPDATE, MDS_REINT, MF_MDC_CANCEL_FID1, obd_device::obd_name, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_flags, md_op_data::op_namelen, PFID, ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_set_replen(), RCL_CLIENT, req_capsule_set_size(), RETURN, RMF_EADATA, RMF_NAME, ptlrpc_request::rq_generation_set, ptlrpc_request::rq_no_retry_einprogress, ptlrpc_request::rq_pill, ptlrpc_request::rq_sent, RQF_MDS_REINT_CREATE_RMT_ACL, and obd_device::u.
int mdc_link (struct obd_export * exp, struct md_op_data * op_data, struct ptlrpc_request ** request)
Definition at line 305 of file mdc_reint.c.
References class_exp2cliimp(), ENTRY, fid_is_sane(), LCK_EX, ldlm_lock_list_put, LIST_HEAD_INIT, LUSTRE_IMP_FULL, mdc_link_pack(), mdc_prep_elc_req(), mdc_reint(), mdc_resource_get_unused(), MDS_INODELOCK_UPDATE, MDS_REINT, MF_MDC_CANCEL_FID1, MF_MDC_CANCEL_FID2, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_flags, md_op_data::op_namelen, ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_set_replen(), RCL_CLIENT, req_capsule_set_size(), RETURN, RMF_NAME, ptlrpc_request::rq_pill, and RQF_MDS_REINT_LINK.
static int mdc_reint (struct ptlrpc_request * request, int level) [static]
Definition at line 47 of file mdc_reint.c.
References CDEBUG, D_INFO, mdc_get_mod_rpc_slot(), mdc_put_mod_rpc_slot(), ptlrpc_queue_wait(), req_capsule_server_get(), RMF_MDT_BODY, and ptlrpc_request::rq_pill.
Referenced by mdc_create(), mdc_link(), mdc_rename(), mdc_setattr(), and mdc_unlink().
int mdc_rename (struct obd_export * exp, struct md_op_data * op_data, const char * old, size_t oldlen, const char * new, size_t newlen, struct ptlrpc_request ** request)
Definition at line 350 of file mdc_reint.c.
References client_obd::cl_default_mds_easize, class_exp2cliimp(), obd_device::cli, CLI_MIGRATE, D_HA, DEBUG_REQ, ENTRY, exp_connect_cancelset(), obd_export::exp_obd, fid_is_sane(), LASSERTF, LCK_EX, ldlm_cli_cancel_list(), ldlm_lock_list_put, LIST_HEAD_INIT, LUSTRE_IMP_FULL, mdc_prep_elc_req(), mdc_reint(), mdc_rename_pack(), mdc_resource_get_unused(), MDS_INODELOCK_FULL, MDS_INODELOCK_LOOKUP, MDS_INODELOCK_UPDATE, MDS_REINT, MF_MDC_CANCEL_FID1, MF_MDC_CANCEL_FID2, MF_MDC_CANCEL_FID3, MF_MDC_CANCEL_FID4, md_open_data::mod_open_req, md_op_data::op_cli_flags, md_op_data::op_data, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_fid3, md_op_data::op_fid4, md_op_data::op_flags, ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_set_replen(), RCL_CLIENT, RCL_SERVER, req_capsule_set_size(), RETURN, RMF_MDT_MD, RMF_NAME, RMF_SYMTGT, ptlrpc_request::rq_lock, ptlrpc_request::rq_pill, ptlrpc_request::rq_replay, ptlrpc_request::rq_type, RQF_MDS_REINT_MIGRATE, RQF_MDS_REINT_RENAME, and obd_device::u.
int mdc_resource_get_unused (struct obd_export * exp, const struct lu_fid * fid, struct list_head * cancels, enum ldlm_mode mode, __u64 bits)
Definition at line 67 of file mdc_reint.c.
References ldlm_inodebits::bits, ENTRY, exp_connect_cancelset(), obd_export::exp_obd, fid_build_reg_res_name(), ldlm_policy_data::l_inodebits, ldlm_cancel_resource_local(), LDLM_RESOURCE_ADDREF, LDLM_RESOURCE_DELREF, ldlm_resource_get(), ldlm_resource_putref(), ns_connect_cancelset(), obd_device::obd_namespace, and RETURN.
Referenced by mdc_create(), mdc_intent_open_pack(), mdc_ioc_swap_layouts(), mdc_link(), mdc_rename(), mdc_setattr(), mdc_unlink(), and mdc_xattr_common().
int mdc_setattr (struct obd_export * exp, struct md_op_data * op_data, void * ea, size_t ealen, struct ptlrpc_request ** request)
Definition at line 102 of file mdc_reint.c.
References __u64, CDEBUG, CFS_TIME_T, class_exp2cliimp(), D_INODE, ENTRY, fid_is_sane(), LASSERT, LCK_EX, ldlm_lock_list_put, LIST_HEAD_INIT, LTIME_S, LUSTRE_IMP_FULL, mdc_prep_elc_req(), mdc_reint(), mdc_resource_get_unused(), mdc_setattr_pack(), MDS_INODELOCK_LOOKUP, MDS_INODELOCK_UPDATE, MDS_REINT, MF_MDC_CANCEL_FID1, md_op_data::op_attr, md_op_data::op_fid1, md_op_data::op_flags, ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_set_replen(), RCL_CLIENT, req_capsule_set_size(), RETURN, RMF_EADATA, RMF_LOGCOOKIES, RMF_MDT_EPOCH, ptlrpc_request::rq_pill, and RQF_MDS_REINT_SETATTR.
int mdc_unlink (struct obd_export * exp, struct md_op_data * op_data, struct ptlrpc_request ** request)
Definition at line 254 of file mdc_reint.c.
References client_obd::cl_default_mds_easize, class_exp2cliimp(), class_exp2obd(), obd_device::cli, ENTRY, fid_is_sane(), LASSERT, LCK_EX, ldlm_lock_list_put, LIST_HEAD_INIT, LUSTRE_IMP_FULL, mdc_prep_elc_req(), mdc_reint(), mdc_resource_get_unused(), mdc_unlink_pack(), MDS_INODELOCK_FULL, MDS_INODELOCK_UPDATE, MDS_REINT, MF_MDC_CANCEL_FID1, MF_MDC_CANCEL_FID3, md_op_data::op_fid1, md_op_data::op_fid3, md_op_data::op_flags, md_op_data::op_namelen, ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_set_replen(), RCL_CLIENT, RCL_SERVER, req_capsule_set_size(), RETURN, RMF_MDT_MD, RMF_NAME, ptlrpc_request::rq_pill, RQF_MDS_REINT_UNLINK, and obd_device::u.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.