Lustre: lustre/mdc/mdc_internal.h File Reference
lustre/mdc/mdc_internal.h File Reference
#include <lustre_mdc.h>
Functions
void mdc_pack_body (struct ptlrpc_request *req, const struct lu_fid *fid, u64 valid, size_t ea_size, u32 suppgid, u32 flags)
void mdc_swap_layouts_pack (struct ptlrpc_request *req, struct md_op_data *op_data)
void mdc_readdir_pack (struct ptlrpc_request *req, __u64 pgoff, size_t size, const struct lu_fid *fid)
void mdc_getattr_pack (struct ptlrpc_request *req, __u64 valid, __u32 flags, struct md_op_data *data, size_t ea_size)
void mdc_setattr_pack (struct ptlrpc_request *req, struct md_op_data *op_data, void *ea, size_t ealen)
void mdc_create_pack (struct ptlrpc_request *req, struct md_op_data *op_data, const void *data, size_t datalen, umode_t mode, uid_t uid, gid_t gid, cfs_cap_t capability, __u64 rdev)
void mdc_open_pack (struct ptlrpc_request *req, struct md_op_data *op_data, umode_t mode, __u64 rdev, __u64 flags, const void *data, size_t datalen)
void mdc_unlink_pack (struct ptlrpc_request *req, struct md_op_data *op_data)
void mdc_getxattr_pack (struct ptlrpc_request *req, struct md_op_data *op_data)
void mdc_link_pack (struct ptlrpc_request *req, struct md_op_data *op_data)
void mdc_rename_pack (struct ptlrpc_request *req, struct md_op_data *op_data, const char *old, size_t oldlen, const char *new, size_t newlen)
void mdc_close_pack (struct ptlrpc_request *req, struct md_op_data *op_data)
int mdc_set_lock_data (struct obd_export *exp, __u64 *lockh, void *data, __u64 *bits)
int mdc_null_inode (struct obd_export *exp, const struct lu_fid *fid)
int mdc_intent_lock (struct obd_export *exp, struct md_op_data *op_data, struct lookup_intent *it, struct ptlrpc_request **reqp, ldlm_blocking_callback cb_blocking, __u64 extra_lock_flags)
int mdc_enqueue (struct obd_export *exp, struct ldlm_enqueue_info *einfo, const union ldlm_policy_data *policy, struct lookup_intent *it, struct md_op_data *op_data, struct lustre_handle *lockh, __u64 extra_lock_flags)
int mdc_resource_get_unused (struct obd_export *exp, const struct lu_fid *fid, struct list_head *cancels, enum ldlm_mode mode, __u64 bits)
int mdc_fid_alloc (const struct lu_env *env, struct obd_export *exp, struct lu_fid *fid, struct md_op_data *op_data)
int mdc_get_lustre_md (struct obd_export *md_exp, struct ptlrpc_request *req, struct obd_export *dt_exp, struct obd_export *lmv_exp, struct lustre_md *md)
int mdc_free_lustre_md (struct obd_export *exp, struct lustre_md *md)
int mdc_set_open_replay_data (struct obd_export *exp, struct obd_client_handle *och, struct lookup_intent *it)
int mdc_clear_open_replay_data (struct obd_export *exp, struct obd_client_handle *och)
void mdc_commit_open (struct ptlrpc_request *req)
void mdc_replay_open (struct ptlrpc_request *req)
int mdc_create (struct obd_export *exp, struct md_op_data *op_data, const void *data, size_t datalen, umode_t mode, uid_t uid, gid_t gid, cfs_cap_t capability, __u64 rdev, struct ptlrpc_request **request)
int mdc_link (struct obd_export *exp, struct md_op_data *op_data, struct ptlrpc_request **request)
int mdc_rename (struct obd_export *exp, struct md_op_data *op_data, const char *old, size_t oldlen, const char *new, size_t newlen, struct ptlrpc_request **request)
int mdc_setattr (struct obd_export *exp, struct md_op_data *op_data, void *ea, size_t ealen, struct ptlrpc_request **request)
int mdc_unlink (struct obd_export *exp, struct md_op_data *op_data, struct ptlrpc_request **request)
int mdc_cancel_unused (struct obd_export *exp, const struct lu_fid *fid, union ldlm_policy_data *policy, enum ldlm_mode mode, enum ldlm_cancel_flags flags, void *opaque)
int mdc_revalidate_lock (struct obd_export *exp, struct lookup_intent *it, struct lu_fid *fid, __u64 *bits)
int mdc_intent_getattr_async (struct obd_export *exp, struct md_enqueue_info *minfo)
enum ldlm_mode mdc_lock_match (struct obd_export *exp, __u64 flags, const struct lu_fid *fid, enum ldlm_type type, union ldlm_policy_data *policy, enum ldlm_mode mode, struct lustre_handle *lockh)
static int mdc_prep_elc_req (struct obd_export *exp, struct ptlrpc_request *req, int opc, struct list_head *cancels, int count)
static unsigned long hash_x_index (__u64 hash, int hash64)
Function Documentation
static unsigned long hash_x_index (__u64 hash, int hash64) [inline, static]
Definition at line 149 of file mdc_internal.h.
Referenced by mdc_page_locate(), mdc_read_page(), and mdc_read_page_remote().
int mdc_cancel_unused (struct obd_export * exp, const struct lu_fid * fid, union ldlm_policy_data * policy, enum ldlm_mode mode, enum ldlm_cancel_flags flags, void * opaque)
Definition at line 156 of file mdc_locks.c.
References class_exp2obd(), ENTRY, fid_build_reg_res_name(), ldlm_cli_cancel_unused_resource(), obd_device::obd_namespace, and RETURN.
int mdc_clear_open_replay_data (struct obd_export * exp, struct obd_client_handle * och)
It is possible to not have lookup and ll_file_open().
Definition at line 733 of file mdc_request.c.
References ENTRY, LASSERT, mdc_free_open(), md_open_data::mod_och, md_open_data::mod_open_req, obd_mod_put, obd_client_handle::och_mod, and RETURN.
void mdc_close_pack (struct ptlrpc_request * req, struct md_op_data * op_data)
Definition at line 487 of file mdc_lib.c.
References mdc_intent_close_pack(), mdc_ioepoch_pack(), mdc_setattr_pack_rec(), MDS_ATTR_ATIME, req_capsule_client_get(), RMF_MDT_EPOCH, RMF_REC_REINT, ptlrpc_request::rq_pill, mdt_rec_setattr::sa_atime, and mdt_rec_setattr::sa_valid.
Referenced by mdc_close().
void mdc_commit_open (struct ptlrpc_request * req)
No need to touch md_open_data::mod_och, it holds a reference on
freed after that when md_open_data::mod_och will put the reference.
Definition at line 624 of file mdc_request.c.
References obd_mod_put, ptlrpc_request_addref(), ptlrpc_request::rq_committed, and ptlrpc_request::rq_lock.
Referenced by mdc_set_open_replay_data().
int mdc_create (struct obd_export * exp, struct md_op_data * op_data, const void * data, size_t datalen, umode_t mode, uid_t uid, gid_t gid, cfs_cap_t capability, __u64 rdev, struct ptlrpc_request ** request)
Definition at line 155 of file mdc_reint.c.
References CDEBUG, cfs_time_current_sec(), client_obd::cl_import, class_exp2cliimp(), obd_device::cli, D_HA, DFID, ENTRY, obd_export::exp_obd, fid_is_sane(), obd_import::imp_generation, LCK_EX, ldlm_lock_list_put, LIST_HEAD_INIT, LUSTRE_IMP_FULL, LUSTRE_IMP_RECOVER, mdc_create_pack(), mdc_fid_alloc(), mdc_prep_elc_req(), mdc_reint(), mdc_resource_get_unused(), MDS_INODELOCK_UPDATE, MDS_REINT, MF_MDC_CANCEL_FID1, obd_device::obd_name, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_flags, md_op_data::op_namelen, PFID, ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_set_replen(), RCL_CLIENT, req_capsule_set_size(), RETURN, RMF_EADATA, RMF_NAME, ptlrpc_request::rq_generation_set, ptlrpc_request::rq_no_retry_einprogress, ptlrpc_request::rq_pill, ptlrpc_request::rq_sent, RQF_MDS_REINT_CREATE_RMT_ACL, and obd_device::u.
void mdc_create_pack (struct ptlrpc_request * req, struct md_op_data * op_data, const void * data, size_t datalen, umode_t mode, uid_t uid, gid_t gid, cfs_cap_t capability, __u64 rdev)
Definition at line 136 of file mdc_lib.c.
References __u64, CLASSERT, mdt_rec_create::cr_bias, mdt_rec_create::cr_cap, mdt_rec_create::cr_fid1, mdt_rec_create::cr_fid2, mdt_rec_create::cr_fsgid, mdt_rec_create::cr_fsuid, mdt_rec_create::cr_mode, mdt_rec_create::cr_opcode, mdt_rec_create::cr_rdev, mdt_rec_create::cr_suppgid1, mdt_rec_create::cr_suppgid2, mdt_rec_create::cr_time, mdt_rec_create::cr_umask, mdc_pack_name(), MDS_CREATE_VOLATILE, MDS_OPEN_VOLATILE, md_op_data::op_bias, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_mod_time, md_op_data::op_name, md_op_data::op_namelen, md_op_data::op_suppgids, REINT_CREATE, req_capsule_client_get(), RMF_EADATA, RMF_NAME, RMF_REC_REINT, ptlrpc_request::rq_pill, and set_mrc_cr_flags().
Referenced by mdc_create().
int mdc_enqueue (struct obd_export * exp, struct ldlm_enqueue_info * einfo, const union ldlm_policy_data * policy, struct lookup_intent * it, struct md_op_data * op_data, struct lustre_handle * lockh, __u64 extra_lock_flags)
Definition at line 724 of file mdc_locks.c.
References __u64, CDEBUG, cfs_time_current_sec(), client_obd::cl_import, class_exp2cliimp(), class_exp2obd(), obd_device::cli, D_HA, D_INFO, DFID, ldlm_enqueue_info::ei_mode, ldlm_enqueue_info::ei_type, ENTRY, fid_build_reg_res_name(), imp_connect_lvb_type(), obd_import::imp_generation, IT_GETATTR, IT_GETXATTR, IT_LAYOUT, lookup_intent::it_lock_handle, lookup_intent::it_lock_mode, IT_LOOKUP, lookup_intent::it_op, IT_OPEN, IT_READDIR, lookup_intent::it_request, IT_SETXATTR, IT_UNLINK, ldlm_policy_data::l_inodebits, LASSERT, LASSERTF, LBUG, LCK_NL, ldlm_cli_enqueue(), LDLM_FL_HAS_INTENT, LDLM_FLOCK, LDLM_IBITS, ldlm_lock_decref(), ldlm_reply::lock_policy_res2, lustre_handle_is_used(), LVB_T_LAYOUT, mdc_clear_replay_flag(), mdc_enqueue_pack(), mdc_finish_enqueue(), mdc_get_mod_rpc_slot(), mdc_intent_getattr_pack(), mdc_intent_getxattr_pack(), mdc_intent_layout_pack(), mdc_intent_open_pack(), mdc_intent_unlink_pack(), mdc_put_mod_rpc_slot(), MDS_INODELOCK_LAYOUT, MDS_INODELOCK_LOOKUP, MDS_INODELOCK_UPDATE, MDS_INODELOCK_XATTR, ldlm_res_id::name, obd_get_request_slot(), obd_device::obd_name, obd_put_request_slot(), md_op_data::op_fid1, md_op_data::op_fid2, PFID, ptlrpc_req_finished(), ptlrpc_status_ntoh(), req_capsule_server_get(), RETURN, RMF_DLM_REP, ptlrpc_request::rq_generation_set, ptlrpc_request::rq_pill, ptlrpc_request::rq_sent, and obd_device::u.
Referenced by mdc_intent_lock().
int mdc_fid_alloc (const struct lu_env * env, struct obd_export * exp, struct lu_fid * fid, struct md_op_data * op_data)
Definition at line 2563 of file mdc_request.c.
References client_obd::cl_seq, obd_device::cli, ENTRY, obd_export::exp_obd, RETURN, seq_client_alloc_fid(), and obd_device::u.
Referenced by mdc_close(), mdc_create(), and mdc_intent_lock().
int mdc_free_lustre_md (struct obd_export * exp, struct lustre_md * md)
Definition at line 568 of file mdc_request.c.
References ENTRY, and RETURN.
int mdc_get_lustre_md (struct obd_export * md_exp, struct ptlrpc_request * req, struct obd_export * dt_exp, struct obd_export * lmv_exp, struct lustre_md * md)
Definition at line 465 of file mdc_request.c.
References lustre_md::body, CDEBUG, client_is_remote(), D_INFO, ENTRY, EXIT, GOTO, LASSERT, lustre_md::layout, lu_buf::lb_buf, lu_buf::lb_len, lustre_md::lmv, lustre_swab_mdt_remote_perm(), mdt_body::mbo_aclsize, mdt_body::mbo_eadatasize, mdt_body::mbo_mode, mdt_body::mbo_valid, md_unpackmd(), mdc_unpack_acl, OBD_MD_FLACL, OBD_MD_FLDIREA, OBD_MD_FLEASIZE, OBD_MD_FLRMTPERM, OBD_MD_MEA, lustre_md::remote_perm, req_capsule_server_get(), req_capsule_server_sized_get(), req_capsule_server_swab_get(), RETURN, RMF_ACL, RMF_MDT_BODY, RMF_MDT_MD, and ptlrpc_request::rq_pill.
void mdc_getattr_pack (struct ptlrpc_request * req, __u64 valid, __u32 flags, struct md_op_data * data, size_t ea_size)
Definition at line 463 of file mdc_lib.c.
References __mdc_pack_body(), mdt_body::mbo_eadatasize, mdt_body::mbo_fid1, mdt_body::mbo_fid2, mdt_body::mbo_flags, mdt_body::mbo_valid, mdc_pack_name(), MDS_CHECK_SPLIT, MDS_CROSS_REF, OBD_MD_FLCKSPLIT, OBD_MD_FLCROSSREF, OBD_MD_FLID, md_op_data::op_bias, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_name, md_op_data::op_namelen, md_op_data::op_suppgids, req_capsule_client_get(), RMF_MDT_BODY, RMF_NAME, and ptlrpc_request::rq_pill.
Referenced by mdc_intent_getattr_pack().
void mdc_getxattr_pack (struct ptlrpc_request * req, struct md_op_data * op_data)
int mdc_intent_getattr_async (struct obd_export * exp, struct md_enqueue_info * minfo)
Definition at line 1181 of file mdc_locks.c.
References __u64, CDEBUG, class_exp2obd(), CLASSERT, obd_device::cli, D_DLMTRACE, DFID, ENTRY, fid_build_reg_res_name(), mdc_getattr_args::ga_exp, mdc_getattr_args::ga_minfo, lookup_intent::it_flags, lookup_intent::it_op, ldlm_policy_data::l_inodebits, ldlm_cli_enqueue(), LDLM_FL_HAS_INTENT, ldlm_it2str(), LVB_T_NONE, mdc_intent_getattr_async_interpret(), mdc_intent_getattr_pack(), MDS_INODELOCK_LOOKUP, MDS_INODELOCK_UPDATE, md_enqueue_info::mi_data, md_enqueue_info::mi_einfo, md_enqueue_info::mi_it, md_enqueue_info::mi_lockh, obd_get_request_slot(), obd_put_request_slot(), md_op_data::op_data, md_op_data::op_fid1, md_op_data::op_name, md_op_data::op_namelen, PFID, ptlrpc_req_async_args, ptlrpc_req_finished(), ptlrpcd_add_req(), RETURN, and obd_device::u.
int mdc_intent_lock (struct obd_export * exp, struct md_op_data * op_data, struct lookup_intent * it, struct ptlrpc_request ** reqp, ldlm_blocking_callback cb_blocking, __u64 extra_lock_flags)
Definition at line 1077 of file mdc_locks.c.
References CDEBUG, CERROR, lustre_handle::cookie, D_DLMTRACE, DFID, ldlm_enqueue_info::ei_type, ENTRY, fid_is_sane(), IT_CREAT, lookup_intent::it_flags, IT_GETATTR, lookup_intent::it_lock_handle, IT_LOOKUP, lookup_intent::it_op, IT_READDIR, lookup_intent::it_request, it_to_lock_mode(), LASSERT, ldlm_completion_ast(), LDLM_IBITS, ldlm_it2str(), mdc_enqueue(), mdc_fid_alloc(), mdc_finish_intent_lock(), mdc_revalidate_lock(), md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_name, md_op_data::op_namelen, PFID, and RETURN.
Referenced by mdc_read_page().
int mdc_link (struct obd_export * exp, struct md_op_data * op_data, struct ptlrpc_request ** request)
Definition at line 305 of file mdc_reint.c.
References class_exp2cliimp(), ENTRY, fid_is_sane(), LCK_EX, ldlm_lock_list_put, LIST_HEAD_INIT, LUSTRE_IMP_FULL, mdc_link_pack(), mdc_prep_elc_req(), mdc_reint(), mdc_resource_get_unused(), MDS_INODELOCK_UPDATE, MDS_REINT, MF_MDC_CANCEL_FID1, MF_MDC_CANCEL_FID2, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_flags, md_op_data::op_namelen, ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_set_replen(), RCL_CLIENT, req_capsule_set_size(), RETURN, RMF_NAME, ptlrpc_request::rq_pill, and RQF_MDS_REINT_LINK.
void mdc_link_pack (struct ptlrpc_request * req, struct md_op_data * op_data)
Definition at line 378 of file mdc_lib.c.
References CLASSERT, LASSERT, mdt_rec_link::lk_bias, mdt_rec_link::lk_cap, mdt_rec_link::lk_fid1, mdt_rec_link::lk_fid2, mdt_rec_link::lk_fsgid, mdt_rec_link::lk_fsuid, mdt_rec_link::lk_opcode, mdt_rec_link::lk_suppgid1, mdt_rec_link::lk_suppgid2, mdt_rec_link::lk_time, mdc_pack_name(), md_op_data::op_bias, md_op_data::op_cap, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_fsgid, md_op_data::op_fsuid, md_op_data::op_mod_time, md_op_data::op_name, md_op_data::op_namelen, md_op_data::op_suppgids, REINT_LINK, req_capsule_client_get(), RMF_NAME, RMF_REC_REINT, and ptlrpc_request::rq_pill.
Referenced by mdc_link().
enum ldlm_mode mdc_lock_match (struct obd_export * exp, __u64 flags, const struct lu_fid * fid, enum ldlm_type type, union ldlm_policy_data * policy, enum ldlm_mode mode, struct lustre_handle * lockh)
Definition at line 139 of file mdc_locks.c.
References ldlm_inodebits::bits, class_exp2obd(), ENTRY, exp_connect_ibits(), fid_build_reg_res_name(), ldlm_policy_data::l_inodebits, ldlm_lock_match(), and RETURN.
Referenced by mdc_revalidate_lock().
int mdc_null_inode (struct obd_export * exp, const struct lu_fid * fid)
Definition at line 172 of file mdc_locks.c.
References class_exp2obd(), ENTRY, fid_build_reg_res_name(), LASSERTF, ldlm_resource_get(), ldlm_resource_putref(), lock_res(), ldlm_resource::lr_lvb_inode, obd_device::obd_namespace, RETURN, and unlock_res().
void mdc_open_pack (struct ptlrpc_request * req, struct md_op_data * op_data, umode_t mode, __u64 rdev, __u64 flags, const void * data, size_t datalen)
Definition at line 204 of file mdc_lib.c.
References __u64, cfs_curproc_cap_pack(), CLASSERT, mdt_rec_create::cr_bias, mdt_rec_create::cr_cap, mdt_rec_create::cr_fid1, mdt_rec_create::cr_fid2, mdt_rec_create::cr_fsgid, mdt_rec_create::cr_fsuid, mdt_rec_create::cr_mode, mdt_rec_create::cr_old_handle, mdt_rec_create::cr_opcode, mdt_rec_create::cr_rdev, mdt_rec_create::cr_suppgid1, mdt_rec_create::cr_suppgid2, mdt_rec_create::cr_time, mdt_rec_create::cr_umask, from_kgid(), from_kuid(), mdc_pack_name(), MDS_CREATE_VOLATILE, MDS_OPEN_HAS_EA, MDS_OPEN_VOLATILE, mds_pack_open_flags(), md_op_data::op_bias, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_handle, md_op_data::op_mod_time, md_op_data::op_name, md_op_data::op_namelen, md_op_data::op_suppgids, REINT_OPEN, req_capsule_client_get(), RMF_EADATA, RMF_NAME, RMF_REC_REINT, ptlrpc_request::rq_pill, and set_mrc_cr_flags().
Referenced by mdc_intent_open_pack().
void mdc_pack_body (struct ptlrpc_request * req, const struct lu_fid * fid, u64 valid, size_t ea_size, u32 suppgid, u32 flags)
Definition at line 74 of file mdc_lib.c.
References __mdc_pack_body(), LASSERT, mdt_body::mbo_eadatasize, mdt_body::mbo_fid1, mdt_body::mbo_flags, mdt_body::mbo_valid, OBD_MD_FLID, req_capsule_client_get(), RMF_MDT_BODY, and ptlrpc_request::rq_pill.
Referenced by mdc_fsync(), mdc_get_remote_perm(), mdc_get_root(), mdc_getattr(), mdc_getattr_name(), mdc_intent_getxattr_pack(), mdc_ioc_hsm_ct_register(), mdc_ioc_hsm_ct_unregister(), mdc_ioc_hsm_current_action(), mdc_ioc_hsm_progress(), mdc_ioc_hsm_request(), mdc_ioc_hsm_state_get(), mdc_ioc_hsm_state_set(), and mdc_xattr_common().
static int mdc_prep_elc_req (struct obd_export * exp, struct ptlrpc_request * req, int opc, struct list_head * cancels, int count) [inline, static]
Definition at line 141 of file mdc_internal.h.
References ldlm_prep_elc_req(), and LUSTRE_MDS_VERSION.
Referenced by mdc_create(), mdc_ioc_swap_layouts(), mdc_link(), mdc_rename(), mdc_setattr(), mdc_unlink(), and mdc_xattr_common().
void mdc_readdir_pack (struct ptlrpc_request * req, __u64 pgoff, size_t size, const struct lu_fid * fid)
Definition at line 122 of file mdc_lib.c.
References __mdc_pack_body(), LUDA_FID, LUDA_TYPE, mdt_body::mbo_fid1, mdt_body::mbo_mode, mdt_body::mbo_nlink, mdt_body::mbo_size, mdt_body::mbo_valid, OBD_MD_FLID, req_capsule_client_get(), RMF_MDT_BODY, and ptlrpc_request::rq_pill.
Referenced by mdc_getpage().
int mdc_rename (struct obd_export * exp, struct md_op_data * op_data, const char * old, size_t oldlen, const char * new, size_t newlen, struct ptlrpc_request ** request)
Definition at line 350 of file mdc_reint.c.
References client_obd::cl_default_mds_easize, class_exp2cliimp(), obd_device::cli, CLI_MIGRATE, D_HA, DEBUG_REQ, ENTRY, exp_connect_cancelset(), obd_export::exp_obd, fid_is_sane(), LASSERTF, LCK_EX, ldlm_cli_cancel_list(), ldlm_lock_list_put, LIST_HEAD_INIT, LUSTRE_IMP_FULL, mdc_prep_elc_req(), mdc_reint(), mdc_rename_pack(), mdc_resource_get_unused(), MDS_INODELOCK_FULL, MDS_INODELOCK_LOOKUP, MDS_INODELOCK_UPDATE, MDS_REINT, MF_MDC_CANCEL_FID1, MF_MDC_CANCEL_FID2, MF_MDC_CANCEL_FID3, MF_MDC_CANCEL_FID4, md_open_data::mod_open_req, md_op_data::op_cli_flags, md_op_data::op_data, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_fid3, md_op_data::op_fid4, md_op_data::op_flags, ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_set_replen(), RCL_CLIENT, RCL_SERVER, req_capsule_set_size(), RETURN, RMF_MDT_MD, RMF_NAME, RMF_SYMTGT, ptlrpc_request::rq_lock, ptlrpc_request::rq_pill, ptlrpc_request::rq_replay, ptlrpc_request::rq_type, RQF_MDS_REINT_MIGRATE, RQF_MDS_REINT_RENAME, and obd_device::u.
void mdc_rename_pack (struct ptlrpc_request * req, struct md_op_data * op_data, const char * old, size_t oldlen, const char * new, size_t newlen)
Definition at line 425 of file mdc_lib.c.
References CLASSERT, CLI_MIGRATE, mdc_intent_close_pack(), mdc_ioepoch_pack(), mdc_pack_name(), MDS_RENAME_MIGRATE, md_op_data::op_bias, md_op_data::op_cap, md_op_data::op_cli_flags, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_fsgid, md_op_data::op_fsuid, md_op_data::op_mod_time, md_op_data::op_mode, md_op_data::op_suppgids, REINT_MIGRATE, REINT_RENAME, req_capsule_client_get(), RMF_MDT_EPOCH, RMF_NAME, RMF_REC_REINT, RMF_SYMTGT, mdt_rec_rename::rn_bias, mdt_rec_rename::rn_cap, mdt_rec_rename::rn_fid1, mdt_rec_rename::rn_fid2, mdt_rec_rename::rn_fsgid, mdt_rec_rename::rn_fsuid, mdt_rec_rename::rn_mode, mdt_rec_rename::rn_opcode, mdt_rec_rename::rn_suppgid1, mdt_rec_rename::rn_suppgid2, mdt_rec_rename::rn_time, and ptlrpc_request::rq_pill.
Referenced by mdc_rename().
void mdc_replay_open (struct ptlrpc_request * req)
Definition at line 574 of file mdc_request.c.
References CDEBUG, lustre_handle::cookie, D_ERROR, D_HA, DEBUG_REQ, ENTRY, EXIT, LASSERT, LPX64, lustre_msg_get_opc(), mdt_body::mbo_handle, MDS_CLOSE, mdt_ioepoch::mio_handle, md_open_data::mod_close_req, md_open_data::mod_och, OBD_CLIENT_HANDLE_MAGIC, obd_client_handle::och_fh, obd_client_handle::och_magic, req_capsule_client_get(), req_capsule_server_get(), RMF_MDT_BODY, RMF_MDT_EPOCH, ptlrpc_request::rq_pill, and ptlrpc_request::rq_reqmsg.
Referenced by mdc_set_open_replay_data().
int mdc_resource_get_unused (struct obd_export * exp, const struct lu_fid * fid, struct list_head * cancels, enum ldlm_mode mode, __u64 bits)
Definition at line 67 of file mdc_reint.c.
References ldlm_inodebits::bits, ENTRY, exp_connect_cancelset(), obd_export::exp_obd, fid_build_reg_res_name(), ldlm_policy_data::l_inodebits, ldlm_cancel_resource_local(), LDLM_RESOURCE_ADDREF, LDLM_RESOURCE_DELREF, ldlm_resource_get(), ldlm_resource_putref(), ns_connect_cancelset(), obd_device::obd_namespace, and RETURN.
Referenced by mdc_create(), mdc_intent_open_pack(), mdc_ioc_swap_layouts(), mdc_link(), mdc_rename(), mdc_setattr(), mdc_unlink(), and mdc_xattr_common().
int mdc_revalidate_lock (struct obd_export * exp, struct lookup_intent * it, struct lu_fid * fid, __u64 * bits)
Definition at line 985 of file mdc_locks.c.
References ldlm_inodebits::bits, lustre_handle::cookie, ENTRY, fid_build_reg_res_name(), IT_GETATTR, IT_LAYOUT, lookup_intent::it_lock_handle, lookup_intent::it_lock_mode, lookup_intent::it_op, IT_READDIR, ldlm_policy_data::l_inodebits, LCK_CR, LCK_CW, LCK_PR, LCK_PW, LDLM_FL_BLOCK_GRANTED, LDLM_IBITS, ldlm_revalidate_lock_handle(), mdc_lock_match(), MDS_INODELOCK_LAYOUT, MDS_INODELOCK_LOOKUP, MDS_INODELOCK_PERM, MDS_INODELOCK_UPDATE, mode, and RETURN.
Referenced by mdc_intent_lock().
int mdc_set_lock_data (struct obd_export * exp, __u64 * lockh, void * data, __u64 * bits)
Definition at line 102 of file mdc_locks.c.
References ldlm_inodebits::bits, ENTRY, ldlm_policy_data::l_inodebits, ldlm_lock::l_policy_data, ldlm_lock::l_resource, LASSERT, LASSERTF, ldlm_handle2lock(), LDLM_LOCK_PUT, lock_res_and_lock(), ldlm_resource::lr_lvb_inode, RETURN, and unlock_res_and_lock().
Referenced by mdc_read_page().
int mdc_set_open_replay_data (struct obd_export * exp, struct obd_client_handle * och, struct lookup_intent * it)
Take a reference on It protects
Definition at line 652 of file mdc_request.c.
References lustre_handle::cookie, mdt_rec_create::cr_fid2, mdt_rec_create::cr_ioepoch, mdt_rec_create::cr_old_handle, D_ERROR, D_RPCTRACE, DEBUG_REQ, DISP_OPEN_CREATE, DISP_OPEN_STRIPE, ENTRY, fid_is_sane(), obd_import::imp_replayable, it_disposition(), lookup_intent::it_request, LASSERT, LBUG, mdt_body::mbo_fid1, mdt_body::mbo_handle, mdt_body::mbo_ioepoch, mdc_commit_open(), mdc_replay_open(), md_open_data::mod_is_create, md_open_data::mod_och, md_open_data::mod_open_req, obd_mod_alloc(), obd_mod_get, obd_client_handle::och_mod, req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_MDT_BODY, RMF_REC_REINT, ptlrpc_request::rq_import, ptlrpc_request::rq_lock, ptlrpc_request::rq_pill, and ptlrpc_request::rq_replay.
Referenced by mdc_finish_enqueue().
int mdc_setattr (struct obd_export * exp, struct md_op_data * op_data, void * ea, size_t ealen, struct ptlrpc_request ** request)
Definition at line 102 of file mdc_reint.c.
References __u64, CDEBUG, CFS_TIME_T, class_exp2cliimp(), D_INODE, ENTRY, fid_is_sane(), LASSERT, LCK_EX, ldlm_lock_list_put, LIST_HEAD_INIT, LTIME_S, LUSTRE_IMP_FULL, mdc_prep_elc_req(), mdc_reint(), mdc_resource_get_unused(), mdc_setattr_pack(), MDS_INODELOCK_LOOKUP, MDS_INODELOCK_UPDATE, MDS_REINT, MF_MDC_CANCEL_FID1, md_op_data::op_attr, md_op_data::op_fid1, md_op_data::op_flags, ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_set_replen(), RCL_CLIENT, req_capsule_set_size(), RETURN, RMF_EADATA, RMF_LOGCOOKIES, RMF_MDT_EPOCH, ptlrpc_request::rq_pill, and RQF_MDS_REINT_SETATTR.
void mdc_setattr_pack (struct ptlrpc_request * req, struct md_op_data * op_data, void * ea, size_t ealen)
Definition at line 330 of file mdc_lib.c.
References CLASSERT, cpu_to_le32, LOV_USER_MAGIC_V1, lov_user_md, mdc_setattr_pack_rec(), req_capsule_client_get(), RMF_EADATA, RMF_REC_REINT, and ptlrpc_request::rq_pill.
Referenced by mdc_setattr().
void mdc_swap_layouts_pack (struct ptlrpc_request * req, struct md_op_data * op_data)
Definition at line 62 of file mdc_lib.c.
References __mdc_pack_body(), mdt_body::mbo_fid1, mdt_body::mbo_fid2, mdt_body::mbo_valid, OBD_MD_FLID, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_suppgids, req_capsule_client_get(), RMF_MDT_BODY, and ptlrpc_request::rq_pill.
Referenced by mdc_ioc_swap_layouts().
int mdc_unlink (struct obd_export * exp, struct md_op_data * op_data, struct ptlrpc_request ** request)
Definition at line 254 of file mdc_reint.c.
References client_obd::cl_default_mds_easize, class_exp2cliimp(), class_exp2obd(), obd_device::cli, ENTRY, fid_is_sane(), LASSERT, LCK_EX, ldlm_lock_list_put, LIST_HEAD_INIT, LUSTRE_IMP_FULL, mdc_prep_elc_req(), mdc_reint(), mdc_resource_get_unused(), mdc_unlink_pack(), MDS_INODELOCK_FULL, MDS_INODELOCK_UPDATE, MDS_REINT, MF_MDC_CANCEL_FID1, MF_MDC_CANCEL_FID3, md_op_data::op_fid1, md_op_data::op_fid3, md_op_data::op_flags, md_op_data::op_namelen, ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_set_replen(), RCL_CLIENT, RCL_SERVER, req_capsule_set_size(), RETURN, RMF_MDT_MD, RMF_NAME, ptlrpc_request::rq_pill, RQF_MDS_REINT_UNLINK, and obd_device::u.
void mdc_unlink_pack (struct ptlrpc_request * req, struct md_op_data * op_data)
Definition at line 354 of file mdc_lib.c.
References CLASSERT, CLI_RM_ENTRY, LASSERT, mdc_pack_name(), md_op_data::op_bias, md_op_data::op_cap, md_op_data::op_cli_flags, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_fsgid, md_op_data::op_fsuid, md_op_data::op_mod_time, md_op_data::op_mode, md_op_data::op_name, md_op_data::op_namelen, md_op_data::op_suppgids, REINT_RMENTRY, REINT_UNLINK, req_capsule_client_get(), RMF_NAME, RMF_REC_REINT, ptlrpc_request::rq_pill, mdt_rec_unlink::ul_bias, mdt_rec_unlink::ul_cap, mdt_rec_unlink::ul_fid1, mdt_rec_unlink::ul_fid2, mdt_rec_unlink::ul_fsgid, mdt_rec_unlink::ul_fsuid, mdt_rec_unlink::ul_mode, mdt_rec_unlink::ul_opcode, mdt_rec_unlink::ul_suppgid1, mdt_rec_unlink::ul_suppgid2, and mdt_rec_unlink::ul_time.
Referenced by mdc_intent_unlink_pack(), and mdc_unlink().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.