Lustre: lustre/mdc/mdc_locks.c File Reference
lustre/mdc/mdc_locks.c File Reference
#include <linux/module.h>
#include <obd.h>
#include <obd_class.h>
#include <lustre_dlm.h>
#include <lustre_fid.h>
#include <lustre_intent.h>
#include <lustre_mdc.h>
#include <lustre_net.h>
#include <lustre_req_layout.h>
#include <lustre_swab.h>
#include "mdc_internal.h"
Data Structures
struct mdc_getattr_args
Defines
#define DEBUG_SUBSYSTEM S_MDC
Functions
int it_open_error (int phase, struct lookup_intent *it)
int mdc_set_lock_data (struct obd_export *exp, __u64 *lockh, void *data, __u64 *bits)
enum ldlm_mode mdc_lock_match (struct obd_export *exp, __u64 flags, const struct lu_fid *fid, enum ldlm_type type, union ldlm_policy_data *policy, enum ldlm_mode mode, struct lustre_handle *lockh)
int mdc_cancel_unused (struct obd_export *exp, const struct lu_fid *fid, union ldlm_policy_data *policy, enum ldlm_mode mode, enum ldlm_cancel_flags flags, void *opaque)
int mdc_null_inode (struct obd_export *exp, const struct lu_fid *fid)
static void mdc_clear_replay_flag (struct ptlrpc_request *req, int rc)
static void mdc_realloc_openmsg (struct ptlrpc_request *req, struct mdt_body *body)
static struct ptlrpc_request * mdc_intent_open_pack (struct obd_export *exp, struct lookup_intent *it, struct md_op_data *op_data)
static struct ptlrpc_request * mdc_intent_getxattr_pack (struct obd_export *exp, struct lookup_intent *it, struct md_op_data *op_data)
static struct ptlrpc_request * mdc_intent_unlink_pack (struct obd_export *exp, struct lookup_intent *it, struct md_op_data *op_data)
static struct ptlrpc_request * mdc_intent_getattr_pack (struct obd_export *exp, struct lookup_intent *it, struct md_op_data *op_data)
static struct ptlrpc_request * mdc_intent_layout_pack (struct obd_export *exp, struct lookup_intent *it, struct md_op_data *unused)
static struct ptlrpc_request * mdc_enqueue_pack (struct obd_export *exp, int lvb_len)
static int mdc_finish_enqueue (struct obd_export *exp, struct ptlrpc_request *req, struct ldlm_enqueue_info *einfo, struct lookup_intent *it, struct lustre_handle *lockh, int rc)
int mdc_enqueue (struct obd_export *exp, struct ldlm_enqueue_info *einfo, const union ldlm_policy_data *policy, struct lookup_intent *it, struct md_op_data *op_data, struct lustre_handle *lockh, __u64 extra_lock_flags)
static int mdc_finish_intent_lock (struct obd_export *exp, struct ptlrpc_request *request, struct md_op_data *op_data, struct lookup_intent *it, struct lustre_handle *lockh)
int mdc_revalidate_lock (struct obd_export *exp, struct lookup_intent *it, struct lu_fid *fid, __u64 *bits)
int mdc_intent_lock (struct obd_export *exp, struct md_op_data *op_data, struct lookup_intent *it, struct ptlrpc_request **reqp, ldlm_blocking_callback cb_blocking, __u64 extra_lock_flags)
static int mdc_intent_getattr_async_interpret (const struct lu_env *env, struct ptlrpc_request *req, void *args, int rc)
int mdc_intent_getattr_async (struct obd_export *exp, struct md_enqueue_info *minfo)
Define Documentation
#define DEBUG_SUBSYSTEM S_MDC
Definition at line 37 of file mdc_locks.c.
Function Documentation
int mdc_cancel_unused (struct obd_export * exp, const struct lu_fid * fid, union ldlm_policy_data * policy, enum ldlm_mode mode, enum ldlm_cancel_flags flags, void * opaque)
Definition at line 156 of file mdc_locks.c.
References class_exp2obd(), ENTRY, fid_build_reg_res_name(), ldlm_cli_cancel_unused_resource(), obd_device::obd_namespace, and RETURN.
static void mdc_clear_replay_flag (struct ptlrpc_request * req, int rc) [inline, static]
Definition at line 196 of file mdc_locks.c.
References D_ERROR, DEBUG_REQ, LBUG, ptlrpc_request::rq_lock, ptlrpc_request::rq_replay, and ptlrpc_request::rq_transno.
Referenced by mdc_enqueue(), mdc_finish_enqueue(), and mdc_intent_getattr_async_interpret().
int mdc_enqueue (struct obd_export * exp, struct ldlm_enqueue_info * einfo, const union ldlm_policy_data * policy, struct lookup_intent * it, struct md_op_data * op_data, struct lustre_handle * lockh, __u64 extra_lock_flags)
Definition at line 724 of file mdc_locks.c.
References __u64, CDEBUG, cfs_time_current_sec(), client_obd::cl_import, class_exp2cliimp(), class_exp2obd(), obd_device::cli, D_HA, D_INFO, DFID, ldlm_enqueue_info::ei_mode, ldlm_enqueue_info::ei_type, ENTRY, fid_build_reg_res_name(), imp_connect_lvb_type(), obd_import::imp_generation, IT_GETATTR, IT_GETXATTR, IT_LAYOUT, lookup_intent::it_lock_handle, lookup_intent::it_lock_mode, IT_LOOKUP, lookup_intent::it_op, IT_OPEN, IT_READDIR, lookup_intent::it_request, IT_SETXATTR, IT_UNLINK, ldlm_policy_data::l_inodebits, LASSERT, LASSERTF, LBUG, LCK_NL, ldlm_cli_enqueue(), LDLM_FL_HAS_INTENT, LDLM_FLOCK, LDLM_IBITS, ldlm_lock_decref(), ldlm_reply::lock_policy_res2, lustre_handle_is_used(), LVB_T_LAYOUT, mdc_clear_replay_flag(), mdc_enqueue_pack(), mdc_finish_enqueue(), mdc_get_mod_rpc_slot(), mdc_intent_getattr_pack(), mdc_intent_getxattr_pack(), mdc_intent_layout_pack(), mdc_intent_open_pack(), mdc_intent_unlink_pack(), mdc_put_mod_rpc_slot(), MDS_INODELOCK_LAYOUT, MDS_INODELOCK_LOOKUP, MDS_INODELOCK_UPDATE, MDS_INODELOCK_XATTR, ldlm_res_id::name, obd_get_request_slot(), obd_device::obd_name, obd_put_request_slot(), md_op_data::op_fid1, md_op_data::op_fid2, PFID, ptlrpc_req_finished(), ptlrpc_status_ntoh(), req_capsule_server_get(), RETURN, RMF_DLM_REP, ptlrpc_request::rq_generation_set, ptlrpc_request::rq_pill, ptlrpc_request::rq_sent, and obd_device::u.
Referenced by mdc_intent_lock().
static struct ptlrpc_request* mdc_enqueue_pack (struct obd_export * exp, int lvb_len) [static, read]
Definition at line 502 of file mdc_locks.c.
References class_exp2cliimp(), ENTRY, ldlm_prep_enqueue_req(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_set_replen(), RCL_SERVER, req_capsule_set_size(), RETURN, RMF_DLM_LVB, ptlrpc_request::rq_pill, and RQF_LDLM_ENQUEUE.
Referenced by mdc_enqueue().
static int mdc_finish_enqueue (struct obd_export * exp, struct ptlrpc_request * req, struct ldlm_enqueue_info * einfo, struct lookup_intent * it, struct lustre_handle * lockh, int rc) [static]
Definition at line 523 of file mdc_locks.c.
References CERROR, client_is_remote(), lustre_handle::cookie, D_RPCTRACE, DEBUG_REQ, DISP_OPEN_OPEN, ldlm_enqueue_info::ei_mode, ELDLM_LOCK_ABORTED, ENTRY, it_disposition(), lookup_intent::it_disposition, IT_GETATTR, IT_LAYOUT, lookup_intent::it_lock_handle, lookup_intent::it_lock_mode, IT_LOOKUP, lookup_intent::it_op, IT_OPEN, it_open_error(), lookup_intent::it_request, lookup_intent::it_status, IT_UNLINK, ldlm_lock::l_lvb_data, ldlm_lock::l_lvb_len, ldlm_lock::l_lvb_type, ldlm_lock::l_req_mode, LASSERT, LDLM_DEBUG, LDLM_FL_BLOCKED_MASK, LDLM_FL_INTENT_ONLY, ldlm_flags_to_wire, ldlm_handle2lock(), ldlm_has_layout(), ldlm_it2str(), ldlm_lock_addref(), ldlm_lock_decref(), LDLM_LOCK_PUT, ldlm_reply::lock_flags, ldlm_request::lock_flags, ldlm_reply::lock_policy_res1, ldlm_reply::lock_policy_res2, lock_res_and_lock(), lustre_swab_mdt_remote_perm(), LVB_T_LAYOUT, mdt_body::mbo_eadatasize, mdt_body::mbo_valid, mdc_clear_replay_flag(), mdc_realloc_openmsg(), mdc_set_open_replay_data(), mdc_update_max_ea_from_body(), OBD_ALLOC_LARGE, OBD_FREE_LARGE, OBD_MD_FLDIREA, OBD_MD_FLEASIZE, OBD_MD_FLRMTPERM, RCL_CLIENT, RCL_SERVER, req_capsule_client_get(), req_capsule_get_size(), req_capsule_server_get(), req_capsule_server_sized_get(), req_capsule_server_swab_get(), req_capsule_set_size(), req_capsule_shrink(), RETURN, RMF_ACL, RMF_DLM_LVB, RMF_DLM_REP, RMF_DLM_REQ, RMF_EADATA, RMF_MDT_BODY, RMF_MDT_MD, ptlrpc_request::rq_pill, ptlrpc_request::rq_replay, ptlrpc_request::rq_transno, and unlock_res_and_lock().
Referenced by mdc_enqueue(), and mdc_intent_getattr_async_interpret().
static int mdc_finish_intent_lock (struct obd_export * exp, struct ptlrpc_request * request, struct md_op_data * op_data, struct lookup_intent * it, struct lustre_handle * lockh) [static]
Definition at line 890 of file mdc_locks.c.
References CDEBUG, lustre_handle::cookie, D_DENTRY, DFID, DISP_ENQ_CREATE_REF, DISP_ENQ_OPEN_REF, DISP_IT_EXECD, DISP_LOOKUP_EXECD, DISP_OPEN_CREATE, DISP_OPEN_OPEN, DLDLMRES, ENTRY, fid_res_name_eq(), IT_CREAT, lookup_intent::it_disposition, it_disposition(), IT_GETATTR, IT_LAYOUT, lookup_intent::it_lock_handle, lookup_intent::it_lock_mode, IT_LOOKUP, lookup_intent::it_op, IT_OPEN, it_open_error(), IT_READDIR, it_set_disposition(), lookup_intent::it_status, ldlm_lock::l_policy_data, ldlm_lock::l_resource, LASSERT, LASSERTF, LCK_NL, LDLM_DEBUG, LDLM_FL_BLOCK_GRANTED, ldlm_handle2lock(), LDLM_IBITS, ldlm_it2str(), ldlm_lock_decref_and_cancel(), ldlm_lock_match(), LDLM_LOCK_PUT, ldlm_resource::lr_name, mdt_body::mbo_fid1, OBD_FAIL_MDC_ENQUEUE_PAUSE, OBD_FAIL_TIMEOUT, obd_timeout, md_op_data::op_name, md_op_data::op_namelen, PFID, PLDLMRES, ptlrpc_request_addref(), req_capsule_server_get(), RETURN, RMF_MDT_BODY, ptlrpc_request::rq_pill, and ptlrpc_request::rq_repmsg.
Referenced by mdc_intent_getattr_async_interpret(), and mdc_intent_lock().
int mdc_intent_getattr_async (struct obd_export * exp, struct md_enqueue_info * minfo)
Definition at line 1181 of file mdc_locks.c.
References __u64, CDEBUG, class_exp2obd(), CLASSERT, obd_device::cli, D_DLMTRACE, DFID, ENTRY, fid_build_reg_res_name(), mdc_getattr_args::ga_exp, mdc_getattr_args::ga_minfo, lookup_intent::it_flags, lookup_intent::it_op, ldlm_policy_data::l_inodebits, ldlm_cli_enqueue(), LDLM_FL_HAS_INTENT, ldlm_it2str(), LVB_T_NONE, mdc_intent_getattr_async_interpret(), mdc_intent_getattr_pack(), MDS_INODELOCK_LOOKUP, MDS_INODELOCK_UPDATE, md_enqueue_info::mi_data, md_enqueue_info::mi_einfo, md_enqueue_info::mi_it, md_enqueue_info::mi_lockh, obd_get_request_slot(), obd_put_request_slot(), md_op_data::op_data, md_op_data::op_fid1, md_op_data::op_name, md_op_data::op_namelen, PFID, ptlrpc_req_async_args, ptlrpc_req_finished(), ptlrpcd_add_req(), RETURN, and obd_device::u.
static int mdc_intent_getattr_async_interpret (const struct lu_env * env, struct ptlrpc_request * req, void * args, int rc) [static]
Definition at line 1131 of file mdc_locks.c.
References __u64, CERROR, class_exp2obd(), obd_device::cli, ldlm_enqueue_info::ei_mode, ldlm_enqueue_info::ei_type, ENTRY, EXIT, mdc_getattr_args::ga_exp, mdc_getattr_args::ga_minfo, GOTO, LASSERT, ldlm_cli_enqueue_fini(), LDLM_FL_HAS_INTENT, ldlm_reply::lock_policy_res2, mdc_clear_replay_flag(), mdc_finish_enqueue(), mdc_finish_intent_lock(), md_enqueue_info::mi_cb, md_enqueue_info::mi_data, md_enqueue_info::mi_einfo, md_enqueue_info::mi_it, md_enqueue_info::mi_lockh, OBD_FAIL_CHECK, OBD_FAIL_MDC_GETATTR_ENQUEUE, obd_put_request_slot(), ptlrpc_status_ntoh(), req_capsule_server_get(), RMF_DLM_REP, ptlrpc_request::rq_pill, and obd_device::u.
Referenced by mdc_intent_getattr_async().
static struct ptlrpc_request* mdc_intent_getattr_pack (struct obd_export * exp, struct lookup_intent * it, struct md_op_data * op_data) [static, read]
Definition at line 412 of file mdc_locks.c.
References __u64, client_obd::cl_default_mds_easize, client_obd::cl_max_mds_easize, class_exp2cliimp(), class_exp2obd(), obd_device::cli, client_is_remote(), ENTRY, lookup_intent::it_flags, lookup_intent::it_op, ldlm_prep_enqueue_req(), mdc_getattr_pack(), OBD_MD_FLACL, OBD_MD_FLDIREA, OBD_MD_FLEASIZE, OBD_MD_FLGETATTR, OBD_MD_FLMODEASIZE, OBD_MD_FLRMTPERM, OBD_MD_MEA, md_op_data::op_namelen, ldlm_intent::opc, ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_set_replen(), RCL_CLIENT, RCL_SERVER, req_capsule_client_get(), req_capsule_set_size(), RETURN, RMF_ACL, RMF_LDLM_INTENT, RMF_MDT_MD, RMF_NAME, ptlrpc_request::rq_pill, RQF_LDLM_INTENT_GETATTR, and obd_device::u.
Referenced by mdc_enqueue(), and mdc_intent_getattr_async().
static struct ptlrpc_request* mdc_intent_getxattr_pack (struct obd_export * exp, struct lookup_intent * it, struct md_op_data * op_data) [static, read]
Definition at line 328 of file mdc_locks.c.
References class_exp2cliimp(), ENTRY, obd_import::imp_connect_data, IT_GETXATTR, ldlm_prep_enqueue_req(), LIST_HEAD_INIT, mdc_pack_body(), obd_connect_data::ocd_max_easize, md_op_data::op_fid1, md_op_data::op_valid, ldlm_intent::opc, ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_set_replen(), RCL_SERVER, req_capsule_client_get(), req_capsule_set_size(), RETURN, RMF_EADATA, RMF_EAVALS, RMF_EAVALS_LENS, RMF_LDLM_INTENT, ptlrpc_request::rq_pill, and RQF_LDLM_INTENT_GETXATTR.
Referenced by mdc_enqueue().
static struct ptlrpc_request* mdc_intent_layout_pack (struct obd_export * exp, struct lookup_intent * it, struct md_op_data * unused) [static, read]
Definition at line 462 of file mdc_locks.c.
References __u64, client_obd::cl_default_mds_easize, class_exp2cliimp(), class_exp2obd(), obd_device::cli, ENTRY, lookup_intent::it_op, LAYOUT_INTENT_ACCESS, ldlm_prep_enqueue_req(), layout_intent::li_opc, ldlm_intent::opc, ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_set_replen(), RCL_CLIENT, RCL_SERVER, req_capsule_client_get(), req_capsule_set_size(), RETURN, RMF_DLM_LVB, RMF_EADATA, RMF_LAYOUT_INTENT, RMF_LDLM_INTENT, ptlrpc_request::rq_pill, RQF_LDLM_INTENT_LAYOUT, and obd_device::u.
Referenced by mdc_enqueue().
int mdc_intent_lock (struct obd_export * exp, struct md_op_data * op_data, struct lookup_intent * it, struct ptlrpc_request ** reqp, ldlm_blocking_callback cb_blocking, __u64 extra_lock_flags)
Definition at line 1077 of file mdc_locks.c.
References CDEBUG, CERROR, lustre_handle::cookie, D_DLMTRACE, DFID, ldlm_enqueue_info::ei_type, ENTRY, fid_is_sane(), IT_CREAT, lookup_intent::it_flags, IT_GETATTR, lookup_intent::it_lock_handle, IT_LOOKUP, lookup_intent::it_op, IT_READDIR, lookup_intent::it_request, it_to_lock_mode(), LASSERT, ldlm_completion_ast(), LDLM_IBITS, ldlm_it2str(), mdc_enqueue(), mdc_fid_alloc(), mdc_finish_intent_lock(), mdc_revalidate_lock(), md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_name, md_op_data::op_namelen, PFID, and RETURN.
Referenced by mdc_read_page().
static struct ptlrpc_request* mdc_intent_open_pack (struct obd_export * exp, struct lookup_intent * it, struct md_op_data * op_data) [static, read]
Definition at line 238 of file mdc_locks.c.
References __u64, client_obd::cl_default_mds_easize, client_obd::cl_max_mds_easize, class_exp2cliimp(), class_exp2obd(), obd_device::cli, client_is_remote(), ENTRY, fid_is_sane(), FMODE_EXEC, FMODE_WRITE, obd_import::imp_replayable, IT_CREAT, lookup_intent::it_create_mode, lookup_intent::it_flags, lookup_intent::it_op, LCK_CR, LCK_CW, LCK_EX, LCK_PR, ldlm_lock_list_put, ldlm_prep_enqueue_req(), LIST_HEAD_INIT, max, mdc_open_pack(), mdc_resource_get_unused(), MDS_INODELOCK_OPEN, MDS_INODELOCK_UPDATE, MDS_OPEN_LEASE, MDS_OPEN_TRUNC, mode, md_op_data::op_data, md_op_data::op_data_size, md_op_data::op_fid1, md_op_data::op_fid2, md_op_data::op_namelen, ldlm_intent::opc, ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_set_replen(), RCL_CLIENT, RCL_SERVER, req_capsule_client_get(), req_capsule_set_size(), RETURN, RMF_ACL, RMF_EADATA, RMF_LDLM_INTENT, RMF_MDT_MD, RMF_NAME, ptlrpc_request::rq_import, ptlrpc_request::rq_lock, ptlrpc_request::rq_pill, ptlrpc_request::rq_replay, RQF_LDLM_INTENT_OPEN, and obd_device::u.
Referenced by mdc_enqueue().
static struct ptlrpc_request* mdc_intent_unlink_pack (struct obd_export * exp, struct lookup_intent * it, struct md_op_data * op_data) [static, read]
Definition at line 375 of file mdc_locks.c.
References __u64, client_obd::cl_default_mds_easize, class_exp2cliimp(), class_exp2obd(), obd_device::cli, ENTRY, lookup_intent::it_op, ldlm_prep_enqueue_req(), mdc_unlink_pack(), md_op_data::op_namelen, ldlm_intent::opc, ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_set_replen(), RCL_CLIENT, RCL_SERVER, req_capsule_client_get(), req_capsule_set_size(), RETURN, RMF_LDLM_INTENT, RMF_MDT_MD, RMF_NAME, ptlrpc_request::rq_pill, RQF_LDLM_INTENT_UNLINK, and obd_device::u.
Referenced by mdc_enqueue().
enum ldlm_mode mdc_lock_match (struct obd_export * exp, __u64 flags, const struct lu_fid * fid, enum ldlm_type type, union ldlm_policy_data * policy, enum ldlm_mode mode, struct lustre_handle * lockh)
Definition at line 139 of file mdc_locks.c.
References ldlm_inodebits::bits, class_exp2obd(), ENTRY, exp_connect_ibits(), fid_build_reg_res_name(), ldlm_policy_data::l_inodebits, ldlm_lock_match(), and RETURN.
Referenced by mdc_revalidate_lock().
int mdc_null_inode (struct obd_export * exp, const struct lu_fid * fid)
Definition at line 172 of file mdc_locks.c.
References class_exp2obd(), ENTRY, fid_build_reg_res_name(), LASSERTF, ldlm_resource_get(), ldlm_resource_putref(), lock_res(), ldlm_resource::lr_lvb_inode, obd_device::obd_namespace, RETURN, and unlock_res().
static void mdc_realloc_openmsg (struct ptlrpc_request * req, struct mdt_body * body) [static]
Definition at line 221 of file mdc_locks.c.
References CERROR, DLM_INTENT_REC_OFF, mdt_body::mbo_eadatasize, mdt_body::mbo_valid, OBD_MD_FLEASIZE, and sptlrpc_cli_enlarge_reqbuf().
Referenced by mdc_finish_enqueue().
int mdc_revalidate_lock (struct obd_export * exp, struct lookup_intent * it, struct lu_fid * fid, __u64 * bits)
Definition at line 985 of file mdc_locks.c.
References ldlm_inodebits::bits, lustre_handle::cookie, ENTRY, fid_build_reg_res_name(), IT_GETATTR, IT_LAYOUT, lookup_intent::it_lock_handle, lookup_intent::it_lock_mode, lookup_intent::it_op, IT_READDIR, ldlm_policy_data::l_inodebits, LCK_CR, LCK_CW, LCK_PR, LCK_PW, LDLM_FL_BLOCK_GRANTED, LDLM_IBITS, ldlm_revalidate_lock_handle(), mdc_lock_match(), MDS_INODELOCK_LAYOUT, MDS_INODELOCK_LOOKUP, MDS_INODELOCK_PERM, MDS_INODELOCK_UPDATE, mode, and RETURN.
Referenced by mdc_intent_lock().
int mdc_set_lock_data (struct obd_export * exp, __u64 * lockh, void * data, __u64 * bits)
Definition at line 102 of file mdc_locks.c.
References ldlm_inodebits::bits, ENTRY, ldlm_policy_data::l_inodebits, ldlm_lock::l_policy_data, ldlm_lock::l_resource, LASSERT, LASSERTF, ldlm_handle2lock(), LDLM_LOCK_PUT, lock_res_and_lock(), ldlm_resource::lr_lvb_inode, RETURN, and unlock_res_and_lock().
Referenced by mdc_read_page().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.