Lustre: lustre/mdc/mdc_request.c File Reference
lustre/mdc/mdc_request.c File Reference
#include <linux/init.h>
#include <linux/kthread.h>
#include <linux/miscdevice.h>
#include <linux/module.h>
#include <linux/pagemap.h>
#include <linux/user_namespace.h>
#include <linux/utsname.h>
#include <cl_object.h>
#include <llog_swab.h>
#include <lprocfs_status.h>
#include <lustre_acl.h>
#include <lustre_fid.h>
#include <lustre_ioctl.h>
#include <lustre_kernelcomm.h>
#include <lustre_lmv.h>
#include <lustre_log.h>
#include <lustre_param.h>
#include <lustre_swab.h>
#include <obd_class.h>
#include "mdc_internal.h"
Data Structures
struct readpage_param
struct changelog_show
Defines
#define DEBUG_SUBSYSTEM S_MDC
#define REQUEST_MINOR 244
#define mdc_unpack_acl(req, md) 0
#define mdc_adjust_dirpages(pages, cfs_pgs, lu_pgs) do {} while (0)
Functions
static int mdc_cleanup (struct obd_device *obd)
static int mdc_queue_wait (struct ptlrpc_request *req)
static int mdc_get_root (struct obd_export *exp, const char *fileset, struct lu_fid *rootfid)
static int mdc_getattr_common (struct obd_export *exp, struct ptlrpc_request *req)
static int mdc_getattr (struct obd_export *exp, struct md_op_data *op_data, struct ptlrpc_request **request)
static int mdc_getattr_name (struct obd_export *exp, struct md_op_data *op_data, struct ptlrpc_request **request)
static int mdc_xattr_common (struct obd_export *exp, const struct req_format *fmt, const struct lu_fid *fid, int opcode, u64 valid, const char *xattr_name, const char *input, int input_size, int output_size, int flags, __u32 suppgid, struct ptlrpc_request **request)
static int mdc_setxattr (struct obd_export *exp, const struct lu_fid *fid, u64 valid, const char *xattr_name, const char *input, int input_size, int output_size, int flags, __u32 suppgid, struct ptlrpc_request **request)
static int mdc_getxattr (struct obd_export *exp, const struct lu_fid *fid, u64 valid, const char *xattr_name, const char *input, int input_size, int output_size, int flags, struct ptlrpc_request **request)
int mdc_get_lustre_md (struct obd_export *exp, struct ptlrpc_request *req, struct obd_export *dt_exp, struct obd_export *md_exp, struct lustre_md *md)
int mdc_free_lustre_md (struct obd_export *exp, struct lustre_md *md)
void mdc_replay_open (struct ptlrpc_request *req)
static void mdc_free_open (struct md_open_data *mod)
static int mdc_close (struct obd_export *exp, struct md_op_data *op_data, struct md_open_data *mod, struct ptlrpc_request **request)
static int mdc_getpage (struct obd_export *exp, const struct lu_fid *fid, u64 offset, struct page **pages, int npages, struct ptlrpc_request **request)
static void mdc_release_page (struct page *page, int remove)
static struct page * mdc_page_locate (struct address_space *mapping, __u64 *hash, __u64 *start, __u64 *end, int hash64)
static void delete_from_page_cache (struct page *page)
static int mdc_read_page_remote (void *data, struct page *page0)
Read pages from server.
static int mdc_read_page (struct obd_export *exp, struct md_op_data *op_data, struct md_callback *cb_op, __u64 hash_offset, struct page **ppage)
Read dir page from cache first, if it can not find it, read it from server and add into the cache.
static int mdc_statfs (const struct lu_env *env, struct obd_export *exp, struct obd_statfs *osfs, __u64 max_age, __u32 flags)
static int mdc_ioc_fid2path (struct obd_export *exp, struct getinfo_fid2path *gf)
static int mdc_ioc_hsm_progress (struct obd_export *exp, struct hsm_progress_kernel *hpk)
static int mdc_ioc_hsm_ct_register (struct obd_import *imp, __u32 archives)
static int mdc_ioc_hsm_current_action (struct obd_export *exp, struct md_op_data *op_data)
static int mdc_ioc_hsm_ct_unregister (struct obd_import *imp)
static int mdc_ioc_hsm_state_get (struct obd_export *exp, struct md_op_data *op_data)
static int mdc_ioc_hsm_state_set (struct obd_export *exp, struct md_op_data *op_data)
static int mdc_ioc_hsm_request (struct obd_export *exp, struct hsm_user_request *hur)
static struct kuc_hdr * changelog_kuc_hdr (char *buf, size_t len, __u32 flags)
static char * cs_obd_name (struct changelog_show *cs)
static int changelog_kkuc_cb (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *hdr, void *data)
static int mdc_changelog_send_thread (void *csdata)
static int mdc_ioc_changelog_send (struct obd_device *obd, struct ioc_changelog *icc)
static int mdc_ioc_hsm_ct_start (struct obd_export *exp, struct lustre_kernelcomm *lk)
static int mdc_quotactl (struct obd_device *unused, struct obd_export *exp, struct obd_quotactl *oqctl)
static int mdc_ioc_swap_layouts (struct obd_export *exp, struct md_op_data *op_data)
static int mdc_iocontrol (unsigned int cmd, struct obd_export *exp, int len, void *karg, void __user *uarg)
static int mdc_get_info_rpc (struct obd_export *exp, u32 keylen, void *key, u32 vallen, void *val)
static void lustre_swab_hai (struct hsm_action_item *h)
static void lustre_swab_hal (struct hsm_action_list *h)
static void lustre_swab_kuch (struct kuc_hdr *l)
static int mdc_hsm_copytool_send (size_t len, void *val)
Send a message to any listening copytools.
static int mdc_hsm_ct_reregister (void *data, void *cb_arg)
callback function passed to kuc for re-registering each HSM copytool running on MDC, after MDT shutdown/recovery.
static int mdc_kuc_reregister (struct obd_import *imp)
Re-establish all kuc contexts with MDT after MDT shutdown/recovery.
static int mdc_set_info_async (const struct lu_env *env, struct obd_export *exp, u32 keylen, void *key, u32 vallen, void *val, struct ptlrpc_request_set *set)
static int mdc_get_info (const struct lu_env *env, struct obd_export *exp, __u32 keylen, void *key, __u32 *vallen, void *val)
static int mdc_fsync (struct obd_export *exp, const struct lu_fid *fid, struct ptlrpc_request **request)
static int mdc_import_event (struct obd_device *obd, struct obd_import *imp, enum obd_import_event event)
int mdc_fid_alloc (const struct lu_env *env, struct obd_export *exp, struct lu_fid *fid, struct md_op_data *op_data)
static struct obd_uuid * mdc_get_uuid (struct obd_export *exp)
static int mdc_cancel_weight (struct ldlm_lock *lock)
Determine whether the lock can be canceled before replaying it during recovery, non zero value will be return if the lock can be canceled, or zero returned for not.
static int mdc_resource_inode_free (struct ldlm_resource *res)
static int mdc_llog_init (struct obd_device *obd)
static void mdc_llog_finish (struct obd_device *obd)
static int mdc_setup (struct obd_device *obd, struct lustre_cfg *cfg)
static int mdc_init_ea_size (struct obd_export *exp, __u32 easize, __u32 def_easize)
static int mdc_precleanup (struct obd_device *obd)
static int mdc_process_config (struct obd_device *obd, size_t len, void *buf)
static int mdc_get_remote_perm (struct obd_export *exp, const struct lu_fid *fid, u32 suppgid, struct ptlrpc_request **request)
static int __init mdc_init (void)
static void __exit mdc_exit (void)
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Metadata Client")
MODULE_VERSION (LUSTRE_VERSION_STRING)
MODULE_LICENSE ("GPL")
module_init (mdc_init)
module_exit (mdc_exit)
Variables
static struct ldlm_valblock_ops inode_lvbo
static struct obd_ops mdc_obd_ops
static struct md_ops mdc_md_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_MDC
Definition at line 37 of file mdc_request.c.
#define mdc_adjust_dirpages (pages, cfs_pgs, lu_pgs) do {} while (0)
Definition at line 1144 of file mdc_request.c.
Referenced by mdc_read_page_remote().
#define mdc_unpack_acl (req, md) 0
Definition at line 462 of file mdc_request.c.
Referenced by mdc_get_lustre_md().
#define REQUEST_MINOR 244
Definition at line 65 of file mdc_request.c.
Function Documentation
static int changelog_kkuc_cb (const struct lu_env * env, struct llog_handle * llh, struct llog_rec_hdr * hdr, void * data) [static]
Definition at line 1830 of file mdc_request.c.
References CDEBUG, CERROR, changelog_kuc_hdr(), CHANGELOG_REC, changelog_rec_name(), changelog_rec_size(), changelog_type2str(), CLF_FLAGMASK, llog_changelog_rec::cr, changelog_rec::cr_flags, llog_changelog_rec::cr_hdr, changelog_rec::cr_index, changelog_rec::cr_namelen, changelog_rec::cr_pfid, changelog_rec::cr_tfid, changelog_rec::cr_time, changelog_rec::cr_type, changelog_show::cs_buf, changelog_show::cs_flags, changelog_show::cs_fp, cs_obd_name(), changelog_show::cs_startrec, D_HSM, DFID, ENTRY, libcfs_kkuc_msg_put(), LPU64, llog_rec_hdr::lrh_type, PFID, and RETURN.
Referenced by mdc_changelog_send_thread().
static struct kuc_hdr* changelog_kuc_hdr (char * buf, size_t len, __u32 flags) [static, read]
Definition at line 1803 of file mdc_request.c.
References CL_RECORD, KUC_CHANGELOG_MSG_MAXSIZE, kuc_hdr::kuc_flags, KUC_MAGIC, kuc_hdr::kuc_magic, kuc_hdr::kuc_msglen, kuc_hdr::kuc_msgtype, kuc_hdr::kuc_transport, KUC_TRANSPORT_CHANGELOG, and LASSERT.
Referenced by changelog_kkuc_cb(), and mdc_changelog_send_thread().
static char* cs_obd_name (struct changelog_show * cs) [inline, static]
Definition at line 1825 of file mdc_request.c.
References changelog_show::cs_obd, and obd_device::obd_name.
Referenced by changelog_kkuc_cb(), mdc_changelog_send_thread(), and mdc_ioc_changelog_send().
static void delete_from_page_cache (struct page * page) [inline, static]
Definition at line 1157 of file mdc_request.c.
Referenced by mdc_read_page_remote().
static void lustre_swab_hai (struct hsm_action_item * h) [static]
Definition at line 2246 of file mdc_request.c.
References __swab32s, __swab64s, hsm_action_item::hai_action, hsm_action_item::hai_cookie, hsm_action_item::hai_dfid, hsm_action_item::hai_extent, hsm_action_item::hai_fid, hsm_action_item::hai_gid, hsm_action_item::hai_len, hsm_extent::length, lustre_swab_lu_fid, and hsm_extent::offset.
Referenced by lustre_swab_hal().
static void lustre_swab_hal (struct hsm_action_list * h) [static]
Definition at line 2258 of file mdc_request.c.
References __swab32s, __swab64s, hai_first(), hai_next(), hsm_action_list::hal_archive_id, hsm_action_list::hal_count, hsm_action_list::hal_flags, hsm_action_list::hal_version, and lustre_swab_hai().
Referenced by mdc_hsm_copytool_send().
static void lustre_swab_kuch (struct kuc_hdr * l) [static]
Definition at line 2272 of file mdc_request.c.
References __swab16s, kuc_hdr::kuc_magic, kuc_hdr::kuc_msglen, and kuc_hdr::kuc_msgtype.
Referenced by mdc_hsm_copytool_send().
static int mdc_cancel_weight (struct ldlm_lock * lock) [static]
Determine whether the lock can be canceled before replaying it during recovery, non zero value will be return if the lock can be canceled, or zero returned for not.
Definition at line 2583 of file mdc_request.c.
References ldlm_inodebits::bits, ldlm_policy_data::l_inodebits, ldlm_lock::l_policy_data, ldlm_lock::l_resource, LDLM_IBITS, ldlm_resource::lr_type, MDS_INODELOCK_OPEN, and RETURN.
Referenced by mdc_setup().
static int mdc_changelog_send_thread (void * csdata) [static]
Definition at line 1874 of file mdc_request.c.
References CDEBUG, CERROR, CHANGELOG_CATALOG, CHANGELOG_FLAG_JOBID, changelog_kkuc_cb(), changelog_kuc_hdr(), CL_EOF, changelog_show::cs_buf, changelog_show::cs_flags, changelog_show::cs_fp, changelog_show::cs_obd, cs_obd_name(), changelog_show::cs_startrec, D_HSM, GOTO, KUC_CHANGELOG_MSG_MAXSIZE, kuc_hdr::kuc_msgtype, libcfs_kkuc_msg_put(), llog_cat_close(), llog_cat_process(), LLOG_CHANGELOG_REPL_CTXT, llog_ctxt_put(), LLOG_F_EXT_JOBID, LLOG_F_IS_CAT, llog_get_context(), llog_init_handle(), llog_open(), LLOG_OPEN_EXISTS, LPU64, OBD_ALLOC, OBD_FREE, and OBD_FREE_PTR.
Referenced by mdc_ioc_changelog_send().
static int mdc_cleanup (struct obd_device * obd) [static]
Definition at line 2720 of file mdc_request.c.
References client_obd_cleanup(), and ptlrpcd_decref().
Referenced by mdc_setup().
static int mdc_close (struct obd_export * exp, struct md_op_data * op_data, struct md_open_data * mod, struct ptlrpc_request ** request) [static]
it can be allowed error after 3633 if open was committed and server failed before close was sent. Let's check if mod exists and return no error in that case
Definition at line 757 of file mdc_request.c.
References CDEBUG, CERROR, client_obd::cl_default_mds_easize, class_exp2cliimp(), class_exp2obd(), obd_device::cli, D_ERROR, D_HA, D_RPCTRACE, DEBUG_REQ, DFID, ENTRY, LASSERT, LASSERTF, likely, LUSTRE_MDS_VERSION, lustre_msg_get_status(), lustre_msg_get_type(), mdc_close_pack(), mdc_fid_alloc(), mdc_get_mod_rpc_slot(), mdc_put_mod_rpc_slot(), MDS_CLOSE, MDS_CLOSE_LAYOUT_SWAP, MDS_HSM_RELEASE, MDS_READPAGE_PORTAL, md_open_data::mod_close_req, md_open_data::mod_open_req, obd_mod_put, obd_device::obd_name, md_op_data::op_bias, md_op_data::op_fid1, md_op_data::op_fid2, PFID, PTL_RPC_MSG_ERR, ptlrpc_at_set_req_timeout(), ptlrpc_queue_wait(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), RCL_SERVER, req_capsule_server_get(), req_capsule_set_size(), RETURN, RMF_MDT_BODY, RMF_MDT_MD, ptlrpc_request::rq_committed, ptlrpc_request::rq_lock, ptlrpc_request::rq_pill, ptlrpc_request::rq_replay, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_status, ptlrpc_request::rq_type, RQF_MDS_CLOSE, RQF_MDS_INTENT_CLOSE, and obd_device::u.
static void __exit mdc_exit (void) [static]
Definition at line 2829 of file mdc_request.c.
References class_unregister_type(), and LUSTRE_MDC_NAME.
int mdc_fid_alloc (const struct lu_env * env, struct obd_export * exp, struct lu_fid * fid, struct md_op_data * op_data)
Definition at line 2563 of file mdc_request.c.
References client_obd::cl_seq, obd_device::cli, ENTRY, obd_export::exp_obd, RETURN, seq_client_alloc_fid(), and obd_device::u.
Referenced by mdc_close(), mdc_create(), and mdc_intent_lock().
int mdc_free_lustre_md (struct obd_export * exp, struct lustre_md * md)
Definition at line 568 of file mdc_request.c.
References ENTRY, and RETURN.
static void mdc_free_open (struct md_open_data * mod) [static]
Definition at line 716 of file mdc_request.c.
References D_RPCTRACE, DEBUG_REQ, imp_connect_disp_stripe(), LASSERT, md_open_data::mod_close_req, md_open_data::mod_is_create, md_open_data::mod_open_req, ptlrpc_request_committed(), ptlrpc_request::rq_import, and ptlrpc_request::rq_replay.
Referenced by mdc_clear_open_replay_data().
static int mdc_fsync (struct obd_export * exp, const struct lu_fid * fid, struct ptlrpc_request ** request) [static]
Definition at line 2480 of file mdc_request.c.
References class_exp2cliimp(), ENTRY, LUSTRE_MDS_VERSION, mdc_pack_body(), MDS_SYNC, ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), RETURN, and RQF_MDS_SYNC.
static int mdc_get_info (const struct lu_env * env, struct obd_export * exp, __u32 keylen, void * key, __u32 * vallen, void * val) [static]
Definition at line 2437 of file mdc_request.c.
References client_obd::cl_default_mds_easize, client_obd::cl_max_mds_easize, class_exp2cliimp(), obd_device::cli, obd_export::exp_obd, obd_import::imp_connect_data, KEY_CONN_DATA, KEY_DEFAULT_EASIZE, KEY_IS, KEY_MAX_EASIZE, KEY_TGT_COUNT, mdc_get_info_rpc(), RETURN, and obd_device::u.
static int mdc_get_info_rpc (struct obd_export * exp, u32 keylen, void * key, u32 vallen, void * val) [static]
Definition at line 2196 of file mdc_request.c.
References class_exp2cliimp(), ENTRY, KEY_FID2PATH, KEY_IS, LUSTRE_MDS_VERSION, lustre_swab_fid2path(), MDS_GET_INFO, ptlrpc_queue_wait(), ptlrpc_rep_need_swab(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), RCL_CLIENT, RCL_SERVER, req_capsule_client_get(), req_capsule_server_get(), req_capsule_set_size(), RETURN, RMF_GETINFO_KEY, RMF_GETINFO_VAL, RMF_GETINFO_VALLEN, ptlrpc_request::rq_pill, and RQF_MDS_GET_INFO.
Referenced by mdc_get_info().
int mdc_get_lustre_md (struct obd_export * exp, struct ptlrpc_request * req, struct obd_export * dt_exp, struct obd_export * md_exp, struct lustre_md * md)
Definition at line 465 of file mdc_request.c.
References lustre_md::body, CDEBUG, client_is_remote(), D_INFO, ENTRY, EXIT, GOTO, LASSERT, lustre_md::layout, lu_buf::lb_buf, lu_buf::lb_len, lustre_md::lmv, lustre_swab_mdt_remote_perm(), mdt_body::mbo_aclsize, mdt_body::mbo_eadatasize, mdt_body::mbo_mode, mdt_body::mbo_valid, md_unpackmd(), mdc_unpack_acl, OBD_MD_FLACL, OBD_MD_FLDIREA, OBD_MD_FLEASIZE, OBD_MD_FLRMTPERM, OBD_MD_MEA, lustre_md::remote_perm, req_capsule_server_get(), req_capsule_server_sized_get(), req_capsule_server_swab_get(), RETURN, RMF_ACL, RMF_MDT_BODY, RMF_MDT_MD, and ptlrpc_request::rq_pill.
static int mdc_get_remote_perm (struct obd_export * exp, const struct lu_fid * fid, u32 suppgid, struct ptlrpc_request ** request) [static]
Definition at line 2736 of file mdc_request.c.
References class_exp2cliimp(), client_is_remote(), ENTRY, LASSERT, LUSTRE_MDS_VERSION, mdc_pack_body(), MDS_GETATTR, OBD_MD_FLRMTPERM, ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), RCL_SERVER, req_capsule_set_size(), RETURN, RMF_ACL, ptlrpc_request::rq_pill, and RQF_MDS_GETATTR.
static int mdc_get_root (struct obd_export * exp, const char * fileset, struct lu_fid * rootfid) [static]
Definition at line 101 of file mdc_request.c.
References CDEBUG, class_exp2cliimp(), D_NET, DFID, ENTRY, EXIT, exp_connect_flags(), GOTO, LPU64, LUSTRE_IMP_FULL, LUSTRE_MDS_VERSION, lustre_msg_add_flags(), lustre_msg_get_last_committed(), mdt_body::mbo_fid1, mdc_pack_body(), MDS_GET_ROOT, name, OBD_CONNECT_SUBTREE, PFID, ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), RCL_CLIENT, req_capsule_client_get(), req_capsule_server_get(), req_capsule_set_size(), RETURN, RMF_MDT_BODY, RMF_NAME, ptlrpc_request::rq_pill, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_reqmsg, and RQF_MDS_GET_ROOT.
static struct obd_uuid* mdc_get_uuid (struct obd_export * exp) [static, read]
Definition at line 2572 of file mdc_request.c.
References client_obd::cl_target_uuid, obd_device::cli, obd_export::exp_obd, and obd_device::u.
static int mdc_getattr (struct obd_export * exp, struct md_op_data * op_data, struct ptlrpc_request ** request) [static]
Definition at line 207 of file mdc_request.c.
References class_exp2cliimp(), client_is_remote(), ENTRY, LASSERT, LUSTRE_MDS_VERSION, mdc_getattr_common(), mdc_pack_body(), MDS_GETATTR, MF_GET_MDT_IDX, OBD_MD_FLRMTPERM, md_op_data::op_fid1, md_op_data::op_flags, md_op_data::op_mds, md_op_data::op_mode, md_op_data::op_valid, ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), RCL_SERVER, req_capsule_set_size(), RETURN, RMF_ACL, RMF_MDT_MD, ptlrpc_request::rq_pill, and RQF_MDS_GETATTR.
static int mdc_getattr_common (struct obd_export * exp, struct ptlrpc_request * req) [static]
Definition at line 165 of file mdc_request.c.
References CDEBUG, client_is_remote(), D_NET, ENTRY, LASSERT, lustre_swab_mdt_remote_perm(), mdt_body::mbo_eadatasize, mdt_body::mbo_mode, mdt_body::mbo_valid, mdc_update_max_ea_from_body(), OBD_MD_FLRMTPERM, ptlrpc_queue_wait(), req_capsule_server_get(), req_capsule_server_sized_get(), req_capsule_server_swab_get(), RETURN, RMF_ACL, RMF_MDT_BODY, RMF_MDT_MD, and ptlrpc_request::rq_pill.
Referenced by mdc_getattr(), and mdc_getattr_name().
static int mdc_getattr_name (struct obd_export * exp, struct md_op_data * op_data, struct ptlrpc_request ** request) [static]
Definition at line 250 of file mdc_request.c.
References class_exp2cliimp(), ENTRY, LASSERT, LUSTRE_MDS_VERSION, mdc_getattr_common(), mdc_pack_body(), MDS_GETATTR_NAME, name, md_op_data::op_fid1, md_op_data::op_mode, md_op_data::op_name, md_op_data::op_namelen, md_op_data::op_suppgids, md_op_data::op_valid, ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), RCL_CLIENT, RCL_SERVER, req_capsule_client_get(), req_capsule_set_size(), RETURN, RMF_MDT_MD, RMF_NAME, ptlrpc_request::rq_pill, RQF_MDS_GETATTR_NAME, and strnlen.
static int mdc_getpage (struct obd_export * exp, const struct lu_fid * fid, u64 offset, struct page ** pages, int npages, struct ptlrpc_request ** request) [static]
Definition at line 874 of file mdc_request.c.
References ptlrpc_bulk_frag_ops::add_kiov_frag, ptlrpc_bulk_desc::bd_frag_ops, CERROR, cfs_time_seconds(), class_exp2cliimp(), obd_device::cli, client_should_resend(), ENTRY, obd_export::exp_obd, l_wait_event, LU_PAGE_MASK, LUSTRE_MDS_VERSION, LWI_TIMEOUT_INTR, mdc_readdir_pack(), MDS_BULK_PORTAL, MDS_READPAGE, MDS_READPAGE_PORTAL, obd_device::obd_name, ptlrpc_at_set_req_timeout(), PTLRPC_BULK_BUF_KIOV, ptlrpc_bulk_kiov_pin_ops, PTLRPC_BULK_PUT_SINK, ptlrpc_prep_bulk_imp(), ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), RETURN, RQF_MDS_READPAGE, sptlrpc_cli_unwrap_bulk_read(), and obd_device::u.
Referenced by mdc_read_page_remote().
static int mdc_getxattr (struct obd_export * exp, const struct lu_fid * fid, u64 valid, const char * xattr_name, const char * input, int input_size, int output_size, int flags, struct ptlrpc_request ** request) [static]
Definition at line 413 of file mdc_request.c.
References mdc_xattr_common(), MDS_GETXATTR, and RQF_MDS_GETXATTR.
static int mdc_hsm_copytool_send (size_t len, void * val) [static]
Send a message to any listening copytools.
Parameters:
val KUC message (kuc_hdr + hsm_action_list)
len total length of message
Definition at line 2310 of file mdc_request.c.
References __swab16, CDEBUG, CERROR, D_HSM, ENTRY, hsm_action_list::hal_count, hsm_action_list::hal_fsname, KUC_GRP_HSM, KUC_MAGIC, kuc_hdr::kuc_magic, kuc_hdr::kuc_msglen, kuc_hdr::kuc_msgtype, kuc_hdr::kuc_transport, libcfs_kkuc_group_put(), lustre_swab_hal(), lustre_swab_kuch(), and RETURN.
Referenced by mdc_set_info_async().
static int mdc_hsm_ct_reregister (void * data, void * cb_arg) [static]
callback function passed to kuc for re-registering each HSM copytool running on MDC, after MDT shutdown/recovery.
Parameters:
data copytool registration data
cb_arg callback argument (obd_import)
Definition at line 2347 of file mdc_request.c.
References CDEBUG, D_HA, obd_import::imp_obd, kkuc_ct_data::kcd_archive, kkuc_ct_data::kcd_magic, kkuc_ct_data::kcd_uuid, KKUC_CT_DATA_MAGIC, mdc_ioc_hsm_ct_register(), obd_device::obd_name, obd_device::obd_uuid, and obd_uuid_equals().
Referenced by mdc_kuc_reregister().
static int mdc_import_event (struct obd_device * obd, struct obd_import * imp, enum obd_import_event event) [static]
Definition at line 2510 of file mdc_request.c.
References CERROR, client_obd::cl_seq, obd_device::cli, IMP_EVENT_ACTIVATE, IMP_EVENT_ACTIVE, IMP_EVENT_DEACTIVATE, IMP_EVENT_DISCON, IMP_EVENT_INACTIVE, IMP_EVENT_INVALIDATE, IMP_EVENT_OCD, obd_import::imp_obd, LASSERT, LBUG, LDLM_FL_LOCAL_ONLY, ldlm_namespace_cleanup(), mdc_kuc_reregister(), obd_device::obd_namespace, OBD_NOTIFY_ACTIVE, OBD_NOTIFY_DISCON, OBD_NOTIFY_INACTIVE, obd_notify_observer(), OBD_NOTIFY_OCD, RETURN, seq_client_flush(), and obd_device::u.
static int __init mdc_init (void) [static]
Definition at line 2823 of file mdc_request.c.
References class_register_type(), and LUSTRE_MDC_NAME.
static int mdc_init_ea_size (struct obd_export * exp, __u32 easize, __u32 def_easize) [static]
Definition at line 2688 of file mdc_request.c.
References client_obd::cl_default_mds_easize, client_obd::cl_max_mds_easize, obd_device::cli, ENTRY, obd_export::exp_obd, RETURN, and obd_device::u.
static int mdc_ioc_changelog_send (struct obd_device * obd, struct ioc_changelog * icc) [static]
Definition at line 1930 of file mdc_request.c.
References CDEBUG, CERROR, changelog_show::cs_flags, changelog_show::cs_fp, changelog_show::cs_obd, cs_obd_name(), changelog_show::cs_startrec, D_HSM, ioc_changelog::icc_flags, ioc_changelog::icc_id, ioc_changelog::icc_recno, mdc_changelog_send_thread(), OBD_ALLOC_PTR, and OBD_FREE_PTR.
Referenced by mdc_iocontrol().
static int mdc_ioc_fid2path (struct obd_export * exp, struct getinfo_fid2path * gf) [static]
Definition at line 1477 of file mdc_request.c.
References CDEBUG, cfs_size_round(), D_IOCTL, DFID, fid_is_sane(), getinfo_fid2path::gf_fid, getinfo_fid2path::gf_linkno, getinfo_fid2path::gf_path, getinfo_fid2path::gf_pathlen, getinfo_fid2path::gf_recno, getinfo_fid2path::gf_root_fid, getinfo_fid2path::gf_u, GOTO, KEY_FID2PATH, LPU64, OBD_ALLOC, OBD_FREE, obd_get_info(), PFID, and RETURN.
Referenced by mdc_iocontrol().
static int mdc_ioc_hsm_ct_register (struct obd_import * imp, __u32 archives) [static]
Definition at line 1563 of file mdc_request.c.
References ENTRY, GOTO, LUSTRE_MDS_VERSION, mdc_pack_body(), mdc_queue_wait(), MDS_HSM_CT_REGISTER, OBD_MD_FLRMTPERM, ptlrpc_req_finished(), ptlrpc_request_alloc_pack(), ptlrpc_request_set_replen(), req_capsule_client_get(), RMF_MDS_HSM_ARCHIVE, ptlrpc_request::rq_pill, and RQF_MDS_HSM_CT_REGISTER.
Referenced by mdc_hsm_ct_reregister(), and mdc_ioc_hsm_ct_start().
static int mdc_ioc_hsm_ct_start (struct obd_export * exp, struct lustre_kernelcomm * lk) [static]
Definition at line 2280 of file mdc_request.c.
References CDEBUG, CERROR, class_exp2cliimp(), D_HSM, KUC_GRP_HSM, lustre_kernelcomm::lk_data, lustre_kernelcomm::lk_flags, LK_FLG_STOP, lustre_kernelcomm::lk_group, lustre_kernelcomm::lk_rfd, lustre_kernelcomm::lk_uid, lustre_kernelcomm::lk_wfd, mdc_ioc_hsm_ct_register(), and mdc_ioc_hsm_ct_unregister().
Referenced by mdc_iocontrol().
static int mdc_ioc_hsm_ct_unregister (struct obd_import * imp) [static]
Definition at line 1637 of file mdc_request.c.
References ENTRY, GOTO, LUSTRE_MDS_VERSION, mdc_pack_body(), mdc_queue_wait(), MDS_HSM_CT_UNREGISTER, OBD_MD_FLRMTPERM, ptlrpc_req_finished(), ptlrpc_request_alloc_pack(), ptlrpc_request_set_replen(), and RQF_MDS_HSM_CT_UNREGISTER.
Referenced by mdc_ioc_hsm_ct_start().
static int mdc_ioc_hsm_current_action (struct obd_export * exp, struct md_op_data * op_data) [static]
Definition at line 1595 of file mdc_request.c.
References class_exp2cliimp(), ENTRY, EXIT, GOTO, LUSTRE_MDS_VERSION, mdc_pack_body(), mdc_queue_wait(), MDS_HSM_ACTION, OBD_MD_FLRMTPERM, md_op_data::op_data, md_op_data::op_fid1, md_op_data::op_suppgids, ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), req_capsule_server_get(), RETURN, RMF_MDS_HSM_CURRENT_ACTION, ptlrpc_request::rq_pill, and RQF_MDS_HSM_ACTION.
Referenced by mdc_iocontrol().
static int mdc_ioc_hsm_progress (struct obd_export * exp, struct hsm_progress_kernel * hpk) [static]
Definition at line 1527 of file mdc_request.c.
References class_exp2cliimp(), ENTRY, GOTO, hsm_progress_kernel::hpk_errval, lustre_errno_hton(), LUSTRE_MDS_VERSION, mdc_get_mod_rpc_slot(), mdc_pack_body(), mdc_put_mod_rpc_slot(), MDS_HSM_PROGRESS, OBD_MD_FLRMTPERM, ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc_pack(), ptlrpc_request_set_replen(), req_capsule_client_get(), RMF_MDS_HSM_PROGRESS, ptlrpc_request::rq_pill, and RQF_MDS_HSM_PROGRESS.
Referenced by mdc_iocontrol().
static int mdc_ioc_hsm_request (struct obd_export * exp, struct hsm_user_request * hur) [static]
Definition at line 1742 of file mdc_request.c.
References class_exp2cliimp(), ENTRY, GOTO, hsm_request::hr_data_len, hsm_request::hr_itemcount, hur_data(), hsm_user_request::hur_request, hsm_user_request::hur_user_item, LUSTRE_MDS_VERSION, mdc_get_mod_rpc_slot(), mdc_pack_body(), mdc_put_mod_rpc_slot(), MDS_HSM_REQUEST, OBD_MD_FLRMTPERM, ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), RCL_CLIENT, req_capsule_client_get(), req_capsule_set_size(), RETURN, RMF_GENERIC_DATA, RMF_MDS_HSM_REQUEST, RMF_MDS_HSM_USER_ITEM, ptlrpc_request::rq_pill, and RQF_MDS_HSM_REQUEST.
Referenced by mdc_iocontrol().
static int mdc_ioc_hsm_state_get (struct obd_export * exp, struct md_op_data * op_data) [static]
Definition at line 1660 of file mdc_request.c.
References class_exp2cliimp(), ENTRY, EXIT, GOTO, LUSTRE_MDS_VERSION, mdc_pack_body(), mdc_queue_wait(), MDS_HSM_STATE_GET, OBD_MD_FLRMTPERM, md_op_data::op_data, md_op_data::op_fid1, md_op_data::op_suppgids, ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), req_capsule_server_get(), RETURN, RMF_HSM_USER_STATE, ptlrpc_request::rq_pill, and RQF_MDS_HSM_STATE_GET.
Referenced by mdc_iocontrol().
static int mdc_ioc_hsm_state_set (struct obd_export * exp, struct md_op_data * op_data) [static]
Definition at line 1701 of file mdc_request.c.
References class_exp2cliimp(), ENTRY, GOTO, LUSTRE_MDS_VERSION, mdc_get_mod_rpc_slot(), mdc_pack_body(), mdc_put_mod_rpc_slot(), MDS_HSM_STATE_SET, OBD_MD_FLRMTPERM, md_op_data::op_data, md_op_data::op_fid1, md_op_data::op_suppgids, ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), req_capsule_client_get(), RETURN, RMF_HSM_STATE_SET, ptlrpc_request::rq_pill, and RQF_MDS_HSM_STATE_SET.
Referenced by mdc_iocontrol().
static int mdc_ioc_swap_layouts (struct obd_export * exp, struct md_op_data * op_data) [static]
Definition at line 2008 of file mdc_request.c.
References class_exp2cliimp(), ENTRY, EXIT, GOTO, LASSERT, LCK_EX, ldlm_lock_list_put, LIST_HEAD_INIT, mdc_prep_elc_req(), mdc_resource_get_unused(), mdc_swap_layouts_pack(), MDS_INODELOCK_LAYOUT, MDS_INODELOCK_XATTR, MDS_SWAP_LAYOUTS, md_op_data::op_data, md_op_data::op_fid1, md_op_data::op_fid2, ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_set_replen(), req_capsule_client_get(), RETURN, RMF_SWAP_LAYOUTS, ptlrpc_request::rq_pill, and RQF_MDS_SWAP_LAYOUTS.
Referenced by mdc_iocontrol().
static int mdc_iocontrol (unsigned int cmd, struct obd_export * exp, int len, void * karg, void __user * uarg) [static]
Definition at line 2064 of file mdc_request.c.
References CERROR, cfs_time_shift_64(), client_obd::cl_import, client_obd::cl_target_uuid, obd_device::cli, changelog_setinfo::cs_recno, ENTRY, exp_connect_flags_ptr(), obd_export::exp_obd, GOTO, ioc_changelog::icc_id, ioc_changelog::icc_recno, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf2, IOC_OBD_STATFS, obd_ioctl_data::ioc_offset, IOC_OSC_SET_ACTIVE, obd_ioctl_data::ioc_pbuf1, obd_ioctl_data::ioc_pbuf2, obd_ioctl_data::ioc_plen1, obd_ioctl_data::ioc_plen2, KEY_CHANGELOG_CLEAR, LL_IOC_GET_CONNECT_FLAGS, LL_IOC_HSM_ACTION, LL_IOC_HSM_CT_START, LL_IOC_HSM_PROGRESS, LL_IOC_HSM_REQUEST, LL_IOC_HSM_STATE_GET, LL_IOC_HSM_STATE_SET, LL_IOC_LOV_SWAP_LAYOUTS, mdc_ioc_changelog_send(), mdc_ioc_fid2path(), mdc_ioc_hsm_ct_start(), mdc_ioc_hsm_current_action(), mdc_ioc_hsm_progress(), mdc_ioc_hsm_request(), mdc_ioc_hsm_state_get(), mdc_ioc_hsm_state_set(), mdc_ioc_swap_layouts(), mdc_statfs(), obd2cli_tgt, OBD_ALLOC_PTR, OBD_FREE_PTR, OBD_IOC_CHANGELOG_CLEAR, OBD_IOC_CHANGELOG_SEND, OBD_IOC_CLIENT_RECOVER, OBD_IOC_FID2PATH, OBD_IOC_PING_TARGET, OBD_IOC_QUOTACTL, obd_device::obd_name, obd_quotactl(), obd_device::obd_self_export, obd_set_info_async(), OBD_STATFS_CACHE_SECONDS, if_quotactl::obd_uuid, ptlrpc_obd_ping(), ptlrpc_recover_import(), ptlrpc_set_import_active(), QC_MDTIDX, if_quotactl::qc_valid, QCTL_COPY, and obd_device::u.
static int mdc_kuc_reregister (struct obd_import * imp) [static]
Re-establish all kuc contexts with MDT after MDT shutdown/recovery.
Definition at line 2371 of file mdc_request.c.
References KUC_GRP_HSM, libcfs_kkuc_group_foreach(), and mdc_hsm_ct_reregister().
Referenced by mdc_import_event().
static void mdc_llog_finish (struct obd_device * obd) [static]
Definition at line 2629 of file mdc_request.c.
References ENTRY, EXIT, LLOG_CHANGELOG_REPL_CTXT, llog_cleanup(), and llog_get_context().
Referenced by mdc_precleanup().
static int mdc_llog_init (struct obd_device * obd) [static]
Definition at line 2609 of file mdc_request.c.
References ENTRY, LLOG_CHANGELOG_REPL_CTXT, llog_client_ops, llog_ctxt_put(), llog_group_get_ctxt(), llog_initiator_connect(), llog_setup(), obd_device::obd_olg, and RETURN.
Referenced by mdc_setup().
static struct page* mdc_page_locate (struct address_space * mapping, __u64 * hash, __u64 * start, __u64 * end, int hash64) [static, read]
Definition at line 970 of file mdc_request.c.
References CDEBUG, D_VFSTRACE, hash_x_index(), LASSERTF, LDF_COLLIDE, lu_dirpage::ldp_flags, lu_dirpage::ldp_hash_end, lu_dirpage::ldp_hash_start, le32_to_cpu, le64_to_cpu, LPX64, mdc_release_page(), radix_tree_exceptional_entry(), and unlikely.
Referenced by mdc_read_page().
static int mdc_precleanup (struct obd_device * obd) [static]
Definition at line 2704 of file mdc_request.c.
References ENTRY, KUC_GRP_HSM, libcfs_kkuc_group_rem(), lprocfs_free_md_stats(), lprocfs_obd_cleanup(), mdc_llog_finish(), obd_cleanup_client_import(), obd_device::obd_type, ptlrpc_lprocfs_unregister_obd(), RETURN, and obd_type::typ_refcnt.
static int mdc_process_config (struct obd_device * obd, size_t len, void * buf) [static]
Definition at line 2727 of file mdc_request.c.
References class_process_proc_param(), obd_device::obd_vars, and PARAM_MDC.
static int mdc_queue_wait (struct ptlrpc_request * req) [inline, static]
Definition at line 69 of file mdc_request.c.
References obd_device::cli, obd_import::imp_obd, obd_get_request_slot(), obd_put_request_slot(), ptlrpc_queue_wait(), ptlrpc_request::rq_import, and obd_device::u.
Referenced by mdc_ioc_hsm_ct_register(), mdc_ioc_hsm_ct_unregister(), mdc_ioc_hsm_current_action(), and mdc_ioc_hsm_state_get().
static int mdc_quotactl (struct obd_device * unused, struct obd_export * exp, struct obd_quotactl * oqctl) [static]
Definition at line 1971 of file mdc_request.c.
References CERROR, class_exp2cliimp(), ENTRY, LUSTRE_MDS_VERSION, MDS_QUOTACTL, ptlrpc_at_set_req_timeout(), ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc_pack(), ptlrpc_request_set_replen(), req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_OBD_QUOTACTL, ptlrpc_request::rq_no_resend, ptlrpc_request::rq_pill, ptlrpc_request::rq_repmsg, and RQF_MDS_QUOTACTL.
static int mdc_read_page (struct obd_export * exp, struct md_op_data * op_data, struct md_callback * cb_op, __u64 hash_offset, struct page ** ppage) [static]
Read dir page from cache first, if it can not find it, read it from server and add into the cache.
Parameters:
[in] exp MDC export
[in] op_data client MD stack parameters, transfering parameters between different layers on client MD stack.
[in] cb_op callback required for ldlm lock enqueue during read page
[in] hash_offset the hash offset of the page to be read
[in] ppage the page to be read
retval = 0 get the page successfully errno(<0) get the page failed
Definition at line 1286 of file mdc_request.c.
References __u64, CDEBUG, CERROR, CLI_HASH64, lustre_handle::cookie, CWARN, D_INFO, DFID, dir, end, ENTRY, obd_export::exp_obd, GOTO, hash_x_index(), lookup_intent::it_lock_handle, lookup_intent::it_lock_mode, lookup_intent::it_op, IT_READDIR, LASSERT, ldlm_lock_decref(), lu_dirpage::ldp_hash_end, lu_dirpage::ldp_hash_start, le64_to_cpu, LPU64, mapping, md_callback::md_blocking_ast, mdc_intent_lock(), mdc_page_locate(), mdc_read_page_remote(), mdc_release_page(), mdc_set_lock_data(), obd_device::obd_name, md_op_data::op_cli_flags, md_op_data::op_data, md_op_data::op_fid1, PFID, ptlrpc_req_finished(), RETURN, readpage_param::rp_exp, readpage_param::rp_hash64, readpage_param::rp_mod, readpage_param::rp_off, and start.
static int mdc_read_page_remote (void * data, struct page * page0) [static]
Read pages from server.
Page in MDS_READPAGE RPC is packed in LU_PAGE_SIZE, and each page contains a header lu_dirpage which describes the start/end hash, and whether this page is empty (contains no dir entry) or hash collide with next page. After client receives reply, several pages will be integrated into dir page in PAGE_SIZE (if PAGE_SIZE greater than LU_PAGE_SIZE), and the lu_dirpage for this integrated page will be adjusted.
Definition at line 1174 of file mdc_request.c.
References __u64, CDEBUG, D_CACHE, D_INODE, D_VFSTRACE, delete_from_page_cache(), ENTRY, hash_x_index(), LASSERT, lu_dirpage::ldp_hash_start, le64_to_cpu, LU_PAGE_MASK, LU_PAGE_SHIFT, mdc_adjust_dirpages, mdc_getpage(), OBD_ALLOC, OBD_FREE, md_op_data::op_data, md_op_data::op_fid1, md_op_data::op_max_pages, PTLRPC_MAX_BRW_PAGES, ptlrpc_req_finished(), ret, RETURN, readpage_param::rp_exp, readpage_param::rp_hash64, readpage_param::rp_mod, and readpage_param::rp_off.
Referenced by mdc_read_page().
static void mdc_release_page (struct page * page, int remove) [static]
Definition at line 959 of file mdc_request.c.
References likely, and truncate_complete_page().
Referenced by mdc_page_locate(), and mdc_read_page().
void mdc_replay_open (struct ptlrpc_request * req)
Definition at line 574 of file mdc_request.c.
References CDEBUG, lustre_handle::cookie, D_ERROR, D_HA, DEBUG_REQ, ENTRY, EXIT, LASSERT, LPX64, lustre_msg_get_opc(), mdt_body::mbo_handle, MDS_CLOSE, mdt_ioepoch::mio_handle, md_open_data::mod_close_req, md_open_data::mod_och, OBD_CLIENT_HANDLE_MAGIC, obd_client_handle::och_fh, obd_client_handle::och_magic, req_capsule_client_get(), req_capsule_server_get(), RMF_MDT_BODY, RMF_MDT_EPOCH, ptlrpc_request::rq_pill, and ptlrpc_request::rq_reqmsg.
Referenced by mdc_set_open_replay_data().
static int mdc_resource_inode_free (struct ldlm_resource * res) [static]
Definition at line 2597 of file mdc_request.c.
References ldlm_resource::lr_lvb_inode.
static int mdc_set_info_async (const struct lu_env * env, struct obd_export * exp, u32 keylen, void * key, u32 vallen, void * val, struct ptlrpc_request_set * set) [static]
Definition at line 2378 of file mdc_request.c.
References CERROR, client_obd::cl_default_mds_easize, class_exp2cliimp(), obd_device::cli, do_set_info_async(), ENTRY, obd_export::exp_obd, obd_import::imp_connect_data, obd_import::imp_connect_flags_orig, obd_import::imp_lock, KEY_CHANGELOG_CLEAR, KEY_DEFAULT_EASIZE, KEY_FLUSH_CTX, KEY_HSM_COPYTOOL_SEND, KEY_IS, KEY_READ_ONLY, KEY_SPTLRPC_CONF, LUSTRE_MDS_VERSION, mdc_hsm_copytool_send(), MDS_SET_INFO, OBD_CONNECT_RDONLY, obd_connect_data::ocd_connect_flags, RETURN, sptlrpc_conf_client_adapt(), sptlrpc_import_flush_my_ctx(), and obd_device::u.
static int mdc_setup (struct obd_device * obd, struct lustre_cfg * cfg) [static]
Definition at line 2642 of file mdc_request.c.
References CERROR, client_obd_setup(), ENTRY, GOTO, lprocfs_alloc_md_stats(), lprocfs_obd_setup(), mdc_cancel_weight(), mdc_cleanup(), mdc_llog_init(), ldlm_namespace::ns_lvbo, ns_register_cancel(), obd_device::obd_namespace, obd_device::obd_vars, ptlrpc_lprocfs_register_obd(), ptlrpcd_addref(), ptlrpcd_decref(), RETURN, and sptlrpc_lprocfs_cliobd_attach().
static int mdc_setxattr (struct obd_export * exp, const struct lu_fid * fid, u64 valid, const char * xattr_name, const char * input, int input_size, int output_size, int flags, __u32 suppgid, struct ptlrpc_request ** request) [static]
Definition at line 401 of file mdc_request.c.
References mdc_xattr_common(), MDS_REINT, and RQF_MDS_REINT_SETXATTR.
static int mdc_statfs (const struct lu_env * env, struct obd_export * exp, struct obd_statfs * osfs, __u64 max_age, __u32 flags) [static]
Definition at line 1421 of file mdc_request.c.
References client_obd::cl_import, client_obd::cl_sem, class_exp2obd(), class_import_get(), class_import_put(), obd_device::cli, ENTRY, EXIT, GOTO, obd_import::imp_connect_error, LUSTRE_MDS_VERSION, MDS_STATFS, OBD_STATFS_NODELAY, ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc_pack(), ptlrpc_request_set_replen(), req_capsule_server_get(), RETURN, RMF_OBD_STATFS, ptlrpc_request::rq_no_delay, ptlrpc_request::rq_no_resend, ptlrpc_request::rq_pill, RQF_MDS_STATFS, and obd_device::u.
Referenced by mdc_iocontrol().
static int mdc_xattr_common (struct obd_export * exp, const struct req_format * fmt, const struct lu_fid * fid, int opcode, u64 valid, const char * xattr_name, const char * input, int input_size, int output_size, int flags, __u32 suppgid, struct ptlrpc_request ** request) [static]
Definition at line 294 of file mdc_request.c.
References cfs_curproc_cap_pack(), cfs_time_current_sec(), class_exp2cliimp(), CLASSERT, ENTRY, obd_export::exp_connect_data, fid_is_sane(), from_kgid(), from_kuid(), LASSERT, LCK_EX, LIST_HEAD_INIT, LUSTRE_MDS_VERSION, mdc_get_mod_rpc_slot(), mdc_pack_body(), mdc_prep_elc_req(), mdc_put_mod_rpc_slot(), mdc_resource_get_unused(), MDS_INODELOCK_XATTR, MDS_REINT, OBD_MD_FLCTIME, obd_connect_data::ocd_ibits_known, ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), RCL_CLIENT, RCL_SERVER, REINT_SETXATTR, req_capsule_client_get(), req_capsule_has_field(), req_capsule_set_size(), RETURN, RMF_EADATA, RMF_NAME, RMF_REC_REINT, ptlrpc_request::rq_pill, mdt_rec_setxattr::sx_cap, mdt_rec_setxattr::sx_fid, mdt_rec_setxattr::sx_flags, mdt_rec_setxattr::sx_fsgid, mdt_rec_setxattr::sx_fsuid, mdt_rec_setxattr::sx_opcode, mdt_rec_setxattr::sx_size, mdt_rec_setxattr::sx_suppgid1, mdt_rec_setxattr::sx_suppgid2, mdt_rec_setxattr::sx_time, and mdt_rec_setxattr::sx_valid.
Referenced by mdc_getxattr(), and mdc_setxattr().
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Metadata Client")
module_exit (mdc_exit)
module_init (mdc_init)
MODULE_LICENSE ("GPL")
MODULE_VERSION (LUSTRE_VERSION_STRING)
Variable Documentation
struct ldlm_valblock_ops inode_lvbo [static]
Initial value:
 {
        .lvbo_free = mdc_resource_inode_free
}
Definition at line 2605 of file mdc_request.c.
struct md_ops mdc_md_ops [static]
Initial value:
 {
        .m_get_root         = mdc_get_root,
        .m_null_inode       = mdc_null_inode,
        .m_close            = mdc_close,
        .m_create           = mdc_create,
        .m_enqueue          = mdc_enqueue,
        .m_getattr          = mdc_getattr,
        .m_getattr_name     = mdc_getattr_name,
        .m_intent_lock      = mdc_intent_lock,
        .m_link             = mdc_link,
        .m_rename           = mdc_rename,
        .m_setattr          = mdc_setattr,
        .m_setxattr         = mdc_setxattr,
        .m_getxattr         = mdc_getxattr,
        .m_fsync                = mdc_fsync,
        .m_read_page            = mdc_read_page,
        .m_unlink           = mdc_unlink,
        .m_cancel_unused    = mdc_cancel_unused,
        .m_init_ea_size     = mdc_init_ea_size,
        .m_set_lock_data    = mdc_set_lock_data,
        .m_lock_match       = mdc_lock_match,
        .m_get_lustre_md    = mdc_get_lustre_md,
        .m_free_lustre_md   = mdc_free_lustre_md,
        .m_set_open_replay_data = mdc_set_open_replay_data,
        .m_clear_open_replay_data = mdc_clear_open_replay_data,
        .m_get_remote_perm  = mdc_get_remote_perm,
        .m_intent_getattr_async = mdc_intent_getattr_async,
        .m_revalidate_lock      = mdc_revalidate_lock
}
Definition at line 2793 of file mdc_request.c.
struct obd_ops mdc_obd_ops [static]
Initial value:
 {
        .o_owner            = THIS_MODULE,
        .o_setup            = mdc_setup,
        .o_precleanup       = mdc_precleanup,
        .o_cleanup          = mdc_cleanup,
        .o_add_conn         = client_import_add_conn,
        .o_del_conn         = client_import_del_conn,
        .o_connect          = client_connect_import,
        .o_disconnect       = client_disconnect_export,
        .o_iocontrol        = mdc_iocontrol,
        .o_set_info_async   = mdc_set_info_async,
        .o_statfs           = mdc_statfs,
        .o_fid_init         = client_fid_init,
        .o_fid_fini         = client_fid_fini,
        .o_fid_alloc        = mdc_fid_alloc,
        .o_import_event     = mdc_import_event,
        .o_get_info         = mdc_get_info,
        .o_process_config   = mdc_process_config,
        .o_get_uuid         = mdc_get_uuid,
        .o_quotactl         = mdc_quotactl,
}
Definition at line 2771 of file mdc_request.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.