Lustre: lustre/mdd/mdd_trans.c File Reference
lustre/mdd/mdd_trans.c File Reference
#include <obd_class.h>
#include <lprocfs_status.h>
#include <lustre_mds.h>
#include "mdd_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_MDS
Functions
struct thandle * mdd_trans_create (const struct lu_env *env, struct mdd_device *mdd)
int mdd_trans_start (const struct lu_env *env, struct mdd_device *mdd, struct thandle *th)
int mdd_trans_stop (const struct lu_env *env, struct mdd_device *mdd, int result, struct thandle *handle)
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 43 of file mdd_trans.c.
Function Documentation
struct thandle* mdd_trans_create (const struct lu_env * env, struct mdd_device * mdd) [read]
Definition at line 51 of file mdd_trans.c.
References dt_device_operations::dt_trans_create, mdd_device::mdd_child, and mdd_child_ops().
Referenced by mdd_attr_set(), mdd_changelog(), mdd_close(), mdd_create(), mdd_create_data(), mdd_index_delete(), mdd_link(), mdd_migrate_create(), mdd_migrate_entries(), mdd_migrate_update_name(), mdd_migrate_xattrs(), mdd_rename(), mdd_swap_layouts(), mdd_unlink(), mdd_xattr_del(), mdd_xattr_set(), and orphan_object_destroy().
int mdd_trans_start (const struct lu_env * env, struct mdd_device * mdd, struct thandle * th)
Definition at line 57 of file mdd_trans.c.
References dt_device_operations::dt_trans_start, mdd_device::mdd_child, and mdd_child_ops().
Referenced by mdd_attr_set(), mdd_changelog(), mdd_close(), mdd_create(), mdd_create_data(), mdd_index_delete(), mdd_link(), mdd_migrate_create(), mdd_migrate_entries(), mdd_migrate_update_name(), mdd_migrate_xattrs(), mdd_rename(), mdd_swap_layouts(), mdd_unlink(), mdd_xattr_del(), mdd_xattr_set(), and orphan_object_destroy().
int mdd_trans_stop (const struct lu_env * env, struct mdd_device * mdd, int result, struct thandle * handle)
Definition at line 63 of file mdd_trans.c.
References dt_device_operations::dt_trans_stop, mdd_device::mdd_child, mdd_child_ops(), and thandle::th_result.
Referenced by mdd_attr_set(), mdd_changelog(), mdd_close(), mdd_create(), mdd_create_data(), mdd_index_delete(), mdd_link(), mdd_migrate_create(), mdd_migrate_entries(), mdd_migrate_update_name(), mdd_migrate_xattrs(), mdd_rename(), mdd_swap_layouts(), mdd_unlink(), mdd_xattr_del(), mdd_xattr_set(), and orphan_object_destroy().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.