Lustre: lustre/mdd/mdd_lock.c File Reference
lustre/mdd/mdd_lock.c File Reference
#include <linux/module.h>
#include <lustre_ver.h>
#include "mdd_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_MDS
Functions
void mdd_write_lock (const struct lu_env *env, struct mdd_object *obj, enum mdd_object_role role)
void mdd_read_lock (const struct lu_env *env, struct mdd_object *obj, enum mdd_object_role role)
void mdd_write_unlock (const struct lu_env *env, struct mdd_object *obj)
void mdd_read_unlock (const struct lu_env *env, struct mdd_object *obj)
int mdd_write_locked (const struct lu_env *env, struct mdd_object *obj)
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 43 of file mdd_lock.c.
Function Documentation
void mdd_read_lock (const struct lu_env * env, struct mdd_object * obj, enum mdd_object_role role)
Definition at line 57 of file mdd_lock.c.
References dt_read_lock(), and mdd_object_child().
Referenced by __mdd_permission_internal(), mdd_acl_init(), mdd_declare_attr_set(), mdd_migrate(), mdd_readlink(), mdd_readpage(), mdd_xattr_get(), and mdd_xattr_list().
void mdd_read_unlock (const struct lu_env * env, struct mdd_object * obj)
Definition at line 72 of file mdd_lock.c.
References dt_read_unlock(), and mdd_object_child().
Referenced by __mdd_permission_internal(), mdd_acl_init(), mdd_declare_attr_set(), mdd_migrate(), mdd_readlink(), mdd_readpage(), mdd_xattr_get(), and mdd_xattr_list().
void mdd_write_lock (const struct lu_env * env, struct mdd_object * obj, enum mdd_object_role role)
Definition at line 49 of file mdd_lock.c.
References dt_write_lock(), and mdd_object_child().
Referenced by __mdd_index_delete(), __mdd_index_insert(), mdd_attr_set(), mdd_close(), mdd_create(), mdd_link(), mdd_migrate_entries(), mdd_migrate_update_name(), mdd_object_create(), mdd_open(), mdd_rename(), mdd_swap_layouts(), mdd_unlink(), mdd_update_linkea_internal(), mdd_xattr_del(), mdd_xattr_set(), orph_key_test_and_del(), and orphan_object_destroy().
int mdd_write_locked (const struct lu_env * env, struct mdd_object * obj)
Definition at line 79 of file mdd_lock.c.
References dt_write_locked(), and mdd_object_child().
Referenced by mdd_finish_unlink(), orph_index_delete(), and orph_index_insert().
void mdd_write_unlock (const struct lu_env * env, struct mdd_object * obj)
Definition at line 65 of file mdd_lock.c.
References dt_write_unlock(), and mdd_object_child().
Referenced by __mdd_index_delete(), __mdd_index_insert(), mdd_attr_set(), mdd_close(), mdd_create(), mdd_link(), mdd_migrate_entries(), mdd_migrate_update_name(), mdd_object_create(), mdd_open(), mdd_rename(), mdd_swap_layouts(), mdd_unlink(), mdd_update_linkea_internal(), mdd_xattr_del(), mdd_xattr_set(), orph_key_test_and_del(), and orphan_object_destroy().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.