Lustre: lustre/mdd/mdd_object.c File Reference
lustre/mdd/mdd_object.c File Reference
#include <linux/module.h>
#include <obd.h>
#include <obd_class.h>
#include <obd_support.h>
#include <lprocfs_status.h>
#include <lustre_fid.h>
#include <lustre_idmap.h>
#include <lustre_param.h>
#include <lustre_mds.h>
#include <lustre/lustre_idl.h>
#include "mdd_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_MDS
Functions
static int mdd_xattr_get (const struct lu_env *env, struct md_object *obj, struct lu_buf *buf, const char *name)
int mdd_la_get (const struct lu_env *env, struct mdd_object *obj, struct lu_attr *la)
struct mdd_thread_info * mdd_env_info (const struct lu_env *env)
struct lu_buf * mdd_buf_get (const struct lu_env *env, void *area, ssize_t len)
struct lu_buf * mdd_buf_get_const (const struct lu_env *env, const void *area, ssize_t len)
struct lu_object * mdd_object_alloc (const struct lu_env *env, const struct lu_object_header *hdr, struct lu_device *d)
static int mdd_object_init (const struct lu_env *env, struct lu_object *o, const struct lu_object_conf *unused)
static int mdd_object_start (const struct lu_env *env, struct lu_object *o)
static void mdd_object_free (const struct lu_env *env, struct lu_object *o)
static int mdd_object_print (const struct lu_env *env, void *cookie, lu_printer_t p, const struct lu_object *o)
struct mdd_object * mdd_object_find (const struct lu_env *env, struct mdd_device *d, const struct lu_fid *f)
int mdd_attr_get (const struct lu_env *env, struct md_object *obj, struct md_attr *ma)
int mdd_readlink (const struct lu_env *env, struct md_object *obj, struct lu_buf *buf)
static int mdd_xattr_list (const struct lu_env *env, struct md_object *obj, struct lu_buf *buf)
int mdd_declare_object_create_internal (const struct lu_env *env, struct mdd_object *p, struct mdd_object *c, struct lu_attr *attr, struct thandle *handle, const struct md_op_spec *spec, struct dt_allocation_hint *hint)
int mdd_object_create_internal (const struct lu_env *env, struct mdd_object *p, struct mdd_object *c, struct lu_attr *attr, struct thandle *handle, const struct md_op_spec *spec, struct dt_allocation_hint *hint)
int mdd_attr_set_internal (const struct lu_env *env, struct mdd_object *obj, const struct lu_attr *attr, struct thandle *handle, int needacl)
int mdd_update_time (const struct lu_env *env, struct mdd_object *obj, const struct lu_attr *oattr, struct lu_attr *attr, struct thandle *handle)
static int mdd_fix_attr (const struct lu_env *env, struct mdd_object *obj, const struct lu_attr *oattr, struct lu_attr *la, const unsigned long flags)
int mdd_changelog_data_store (const struct lu_env *env, struct mdd_device *mdd, enum changelog_rec_type type, int flags, struct mdd_object *mdd_obj, struct thandle *handle)
Store a data change changelog record If this fails, we must fail the whole transaction; we don't want the change to commit without the log entry.
static int mdd_changelog (const struct lu_env *env, enum changelog_rec_type type, int flags, struct md_object *obj)
static int mdd_attr_set_changelog (const struct lu_env *env, struct md_object *obj, struct thandle *handle, __u64 valid)
Save LMA extended attributes with data from ma.
static int mdd_declare_attr_set (const struct lu_env *env, struct mdd_device *mdd, struct mdd_object *obj, const struct lu_attr *attr, struct thandle *handle)
static bool permission_needs_sync (const struct lu_attr *old, const struct lu_attr *new)
int mdd_attr_set (const struct lu_env *env, struct md_object *obj, const struct md_attr *ma)
static int mdd_xattr_sanity_check (const struct lu_env *env, struct mdd_object *obj, const struct lu_attr *attr)
static int mdd_declare_xattr_set (const struct lu_env *env, struct mdd_device *mdd, struct mdd_object *obj, const struct lu_buf *buf, const char *name, int fl, struct thandle *handle)
static int mdd_hsm_update_locked (const struct lu_env *env, struct md_object *obj, const struct lu_buf *buf, struct thandle *handle)
static int mdd_xattr_del (const struct lu_env *env, struct md_object *obj, const char *name)
The caller should guarantee to update the object ctime after xattr_set if needed.
static int mdd_xattr_set (const struct lu_env *env, struct md_object *obj, const struct lu_buf *buf, const char *name, int fl)
The caller should guarantee to update the object ctime after xattr_set if needed.
static int mdd_declare_xattr_del (const struct lu_env *env, struct mdd_device *mdd, struct mdd_object *obj, const char *name, struct thandle *handle)
int mdd_get_lov_ea (const struct lu_env *env, struct mdd_object *obj, struct lu_buf *lmm_buf)
static int mdd_xattr_hsm_replace (const struct lu_env *env, struct mdd_object *o, struct lu_buf *buf, struct thandle *handle)
static int mdd_layout_swap_allowed (const struct lu_env *env, struct mdd_object *o1, const struct lu_attr *attr1, struct mdd_object *o2, const struct lu_attr *attr2)
static int mdd_swap_layouts (const struct lu_env *env, struct md_object *obj1, struct md_object *obj2, __u64 flags)
swap layouts between 2 lustre objects
void mdd_object_make_hint (const struct lu_env *env, struct mdd_object *parent, struct mdd_object *child, const struct lu_attr *attr, const struct md_op_spec *spec, struct dt_allocation_hint *hint)
int accmode (const struct lu_env *env, const struct lu_attr *la, int flags)
static int mdd_open_sanity_check (const struct lu_env *env, struct mdd_object *obj, const struct lu_attr *attr, int flag)
static int mdd_open (const struct lu_env *env, struct md_object *obj, int flags)
static int mdd_declare_close (const struct lu_env *env, struct mdd_object *obj, struct md_attr *ma, struct thandle *handle)
static int mdd_close (const struct lu_env *env, struct md_object *obj, struct md_attr *ma, int mode)
static int mdd_readpage_sanity_check (const struct lu_env *env, struct mdd_object *obj)
static int mdd_dir_page_build (const struct lu_env *env, union lu_page *lp, size_t nob, const struct dt_it_ops *iops, struct dt_it *it, __u32 attr, void *arg)
int mdd_readpage (const struct lu_env *env, struct md_object *obj, const struct lu_rdpg *rdpg)
static int mdd_object_sync (const struct lu_env *env, struct md_object *obj)
static int mdd_object_lock (const struct lu_env *env, struct md_object *obj, struct lustre_handle *lh, struct ldlm_enqueue_info *einfo, union ldlm_policy_data *policy)
static int mdd_object_unlock (const struct lu_env *env, struct md_object *obj, struct ldlm_enqueue_info *einfo, union ldlm_policy_data *policy)
Variables
static struct lu_object_operations mdd_lu_obj_ops
struct md_object_operations mdd_obj_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 43 of file mdd_object.c.
Function Documentation
int accmode (const struct lu_env * env, const struct lu_attr * la, int flags)
Definition at line 1601 of file mdd_object.c.
References FMODE_READ, FMODE_WRITE, lu_attr::la_uid, lu_ucred_check(), MDS_FMODE_EXEC, MDS_OPEN_APPEND, MDS_OPEN_OWNEROVERRIDE, MDS_OPEN_TRUNC, and lu_ucred::uc_fsuid.
Referenced by mdd_open_sanity_check(), and mdd_permission().
int mdd_attr_get (const struct lu_env * env, struct md_object * obj, struct md_attr * ma)
Definition at line 212 of file mdd_object.c.
References ENTRY, lu_attr::la_nlink, md_attr::ma_attr, MA_INODE, md_attr::ma_need, md2mdd_obj(), mdd_is_dead_obj(), mdd_la_get(), and RETURN.
int mdd_attr_set (const struct lu_env * env, struct md_object * obj, const struct md_attr * ma)
Definition at line 834 of file mdd_object.c.
References CDEBUG, D_INODE, DFID, ENTRY, GOTO, lu_attr::la_ctime, LA_CTIME, LA_FLAGS, lu_attr::la_mtime, LA_MTIME, lu_attr::la_valid, LASSERT, LPU64, LPX64, md_attr::ma_attr, md_attr::ma_attr_flags, MA_HSM, MA_LOV, md_attr::ma_valid, md2mdd_obj(), mdd2obd_dev(), mdd_attr_set_changelog(), mdd_attr_set_internal(), mdd_declare_attr_set(), mdd_env_info(), MDD_ENV_VAR, mdd_fix_attr(), mdd_la_get(), mdd_device::mdd_sync_permission, mdd_trans_create(), mdd_trans_start(), mdd_trans_stop(), mdd_write_lock(), mdd_write_unlock(), mdo2fid(), mdo2mdd(), MOR_TGT_CHILD, mdd_thread_info::mti_la_for_fix, permission_needs_sync(), PFID, RETURN, stop, and thandle::th_sync.
static int mdd_attr_set_changelog (const struct lu_env * env, struct md_object * obj, struct thandle * handle, __u64 valid) [static]
Save LMA extended attributes with data from ma.
HSM and Size-On-MDS data will be extracted from if they are valid, if not, LMA EA will be first read from disk, modified and write back.
Definition at line 738 of file mdd_object.c.
References CL_ATIME, CL_CTIME, CL_LAST, CL_MTIME, CL_SETATTR, CL_TRUNC, CLASSERT, LA_ATIME, LA_CTIME, LA_MTIME, LA_SIZE, mdd_changelog::mc_mask, md2mdd_obj(), mdd_changelog_data_store(), mdd_device::mdd_cl, and mdo2mdd().
Referenced by mdd_attr_set().
int mdd_attr_set_internal (const struct lu_env * env, struct mdd_object * obj, const struct lu_attr * attr, struct thandle * handle, int needacl)
Definition at line 394 of file mdd_object.c.
References ENTRY, lu_attr::la_mode, LA_MODE, lu_attr::la_valid, mdd_acl_chmod(), mdo_attr_set(), and RETURN.
Referenced by mdd_attr_set(), mdd_migrate_update_name(), and mdd_update_time().
struct lu_buf* mdd_buf_get (const struct lu_env * env, void * area, ssize_t len) [read]
Definition at line 100 of file mdd_object.c.
References buf, lu_buf::lb_buf, lu_buf::lb_len, mdd_env_info(), and mdd_thread_info::mti_buf.
Referenced by mdd_check_acl(), mdd_declare_attr_set(), mdd_hsm_archive_exists(), and mdd_hsm_update_locked().
struct lu_buf* mdd_buf_get_const (const struct lu_env * env, const void * area, ssize_t len) [read]
Definition at line 110 of file mdd_object.c.
References buf, lu_buf::lb_buf, lu_buf::lb_len, mdd_env_info(), and mdd_thread_info::mti_buf.
Referenced by mdd_create_data(), mdd_declare_links_add(), mdd_declare_migrate_create(), mdd_declare_object_create(), mdd_links_write(), mdd_migrate_create(), and mdd_object_create().
static int mdd_changelog (const struct lu_env * env, enum changelog_rec_type type, int flags, struct md_object * obj) [static]
Definition at line 697 of file mdd_object.c.
References ENTRY, GOTO, md2mdd_obj(), mdd_changelog_data_store(), mdd_declare_changelog_store(), mdd_trans_create(), mdd_trans_start(), mdd_trans_stop(), mdo2mdd(), RETURN, and stop.
int mdd_changelog_data_store (const struct lu_env * env, struct mdd_device * mdd, enum changelog_rec_type type, int flags, struct mdd_object * mdd_obj, struct thandle * handle)
Store a data change changelog record If this fails, we must fail the whole transaction; we don't want the change to commit without the log entry.
Parameters:
mdd_obj - mdd_object of change
handle - transaction handle
Definition at line 643 of file mdd_object.c.
References buf, cfs_time_before_64(), cfs_time_current_64, changelog_rec_offset(), CL_ATIME, CL_MTIME, CLF_FLAGMASK, CLF_JOBID, CLF_SUPPORTED, CLF_VERSION, CLM_ON, llog_changelog_rec::cr, changelog_rec::cr_flags, changelog_rec::cr_namelen, changelog_rec::cr_tfid, changelog_rec::cr_type, LASSERT, lu_buf::lb_buf, llog_data_len(), lu_buf_check_and_alloc(), lu_ucred(), mdd_changelog::mc_flags, mdd_changelog::mc_mask, mdd_changelog::mc_starttime, mdd_changelog_rec_ext_jobid(), mdd_changelog_store(), mdd_device::mdd_cl, mdd_env_info(), mdo2fid(), mdd_object::mod_cltime, RETURN, and lu_ucred::uc_jobid.
Referenced by mdd_attr_set_changelog(), mdd_changelog(), mdd_close(), mdd_create_data(), mdd_hsm_update_locked(), mdd_swap_layouts(), mdd_xattr_del(), mdd_xattr_hsm_replace(), and mdd_xattr_set().
static int mdd_close (const struct lu_env * env, struct md_object * obj, struct md_attr * ma, int mode) [static]
Definition at line 1722 of file mdd_object.c.
References __mdd_orphan_del(), CDEBUG, CERROR, CL_CLOSE, D_HA, DEAD_OBJ, DFID, ENTRY, EXIT, FMODE_WRITE, GOTO, lu_attr::la_nlink, LASSERT, lu_dev_name(), md_attr::ma_attr, md_attr::ma_attr_flags, MA_FLAGS, md_attr::ma_valid, md2mdd_obj(), mdd2lu_dev(), mdd_changelog_data_store(), mdd_declare_changelog_store(), mdd_declare_close(), mdd_la_get(), mdd_object_fid(), mdd_trans_create(), mdd_trans_start(), mdd_trans_stop(), mdd_write_lock(), mdd_write_unlock(), mdo2mdd(), mdo_destroy(), MDS_KEEP_ORPHAN, MDS_OPEN_APPEND, MDS_OPEN_TRUNC, MDS_RECOV_OPEN, mdd_object::mod_count, mdd_object::mod_flags, MOR_TGT_CHILD, ORPHAN_OBJ, PFID, RETURN, and stop.
static int mdd_declare_attr_set (const struct lu_env * env, struct mdd_device * mdd, struct mdd_object * obj, const struct lu_attr * attr, struct thandle * handle) [static]
Definition at line 764 of file mdd_object.c.
References buf, LA_MODE, lu_attr::la_valid, LU_BUF_NULL, mdd_buf_get(), mdd_declare_changelog_store(), mdd_read_lock(), mdd_read_unlock(), mdo_declare_attr_set(), mdo_declare_xattr_set(), mdo_xattr_get(), MOR_TGT_CHILD, and XATTR_NAME_ACL_ACCESS.
Referenced by mdd_attr_set().
static int mdd_declare_close (const struct lu_env * env, struct mdd_object * obj, struct md_attr * ma, struct thandle * handle) [static]
Definition at line 1705 of file mdd_object.c.
References mdo_declare_destroy(), and orph_declare_index_delete().
Referenced by mdd_close().
int mdd_declare_object_create_internal (const struct lu_env * env, struct mdd_object * p, struct mdd_object * c, struct lu_attr * attr, struct thandle * handle, const struct md_op_spec * spec, struct dt_allocation_hint * hint)
Definition at line 342 of file mdd_object.c.
References DFT_INDEX, DFT_REGULAR, dt_object_format::dof_idx, dt_object_format::dof_reg, dt_object_format::dof_type, dt_directory_features, dt_mode_to_dft(), ENTRY, lu_attr::la_mode, md_should_create(), mdd_env_info(), mdo_declare_create_obj(), MDS_OPEN_HAS_EA, mdd_thread_info::mti_dof, md_op_spec::no_create, RETURN, md_op_spec::sp_cr_flags, md_op_spec::sp_feat, and dt_object_format::u.
Referenced by mdd_declare_migrate_create(), and mdd_declare_object_create().
static int mdd_declare_xattr_del (const struct lu_env * env, struct mdd_device * mdd, struct mdd_object * obj, const char * name, struct thandle * handle) [static]
Definition at line 1109 of file mdd_object.c.
References mdd_declare_changelog_store(), mdo_declare_xattr_del(), and XATTR_USER_PREFIX.
Referenced by mdd_swap_layouts(), and mdd_xattr_del().
static int mdd_declare_xattr_set (const struct lu_env * env, struct mdd_device * mdd, struct mdd_object * obj, const struct lu_buf * buf, const char * name, int fl, struct thandle * handle) [static]
Definition at line 921 of file mdd_object.c.
References mdd_declare_changelog_store(), mdo_declare_xattr_set(), XATTR_NAME_HSM, XATTR_NAME_LOV, and XATTR_USER_PREFIX.
Referenced by mdd_swap_layouts(), and mdd_xattr_set().
static int mdd_dir_page_build (const struct lu_env * env, union lu_page * lp, size_t nob, const struct dt_it_ops * iops, struct dt_it * it, __u32 attr, void * arg) [static]
Definition at line 1873 of file mdd_object.c.
References __u64, cpu_to_le32, cpu_to_le64, CWARN, fid_is_dot_lustre(), fid_le_to_cpu(), lu_dirent::lde_hash, lu_dirent::lde_reclen, LDF_COLLIDE, lu_dirpage::ldp_flags, lu_dirpage::ldp_hash_end, lu_dirpage::ldp_hash_start, le16_to_cpu, le32_to_cpu, lu_page::lp_dir, lu_dirent_calc_size(), LUDA_FID, MDS_DIR_END_OFF, and unlikely.
Referenced by mdd_readpage().
struct mdd_thread_info* mdd_env_info (const struct lu_env * env) [read]
Definition at line 90 of file mdd_object.c.
References LASSERT, lu_env::le_ctx, lu_context_key_get(), lu_env_refill(), and mdd_thread_key.
Referenced by __mdd_index_insert_only(), __mdd_links_add(), mdd_attr_set(), mdd_buf_get(), mdd_buf_get_const(), mdd_changelog_data_store(), mdd_changelog_ns_store(), mdd_changelog_write_header(), mdd_check_acl(), mdd_create(), mdd_create_data(), mdd_create_sanity_check(), mdd_declare_changelog_store(), mdd_declare_create(), mdd_declare_links_add(), mdd_declare_object_create_internal(), mdd_declare_rename(), mdd_declare_unlink(), mdd_fld_lookup(), mdd_get_lov_ea(), mdd_hsm_update_locked(), mdd_is_parent(), mdd_link(), mdd_linkea_update_child_internal(), mdd_links_read(), mdd_links_rename(), mdd_links_write(), mdd_migrate_create(), mdd_migrate_entries(), mdd_migrate_sanity_check(), mdd_migrate_update_name(), mdd_migrate_xattrs(), mdd_object_create_internal(), mdd_orphan_insert_obj(), mdd_parent_fid(), mdd_rename(), mdd_swap_layouts(), mdd_unlink(), mdd_update_linkea_internal(), mdo_declare_index_insert(), orph_declare_index_insert(), orph_index_insert(), orph_index_iterate(), orph_key_fill(), and orph_key_fill_18().
static int mdd_fix_attr (const struct lu_env * env, struct mdd_object * obj, const struct lu_attr * oattr, struct lu_attr * la, const unsigned long flags) [static]
Definition at line 441 of file mdd_object.c.
References CFS_CAP_CHOWN, CFS_CAP_FOWNER, CFS_CAP_FSETID, CFS_CAP_LINUX_IMMUTABLE, ENTRY, lu_attr::la_atime, LA_ATIME, LA_BLKSIZE, LA_BLOCKS, lu_attr::la_ctime, LA_CTIME, lu_attr::la_flags, LA_FLAGS, lu_attr::la_gid, LA_GID, LA_KILL_SGID, LA_KILL_SUID, LA_MODE, lu_attr::la_mode, LA_MTIME, LA_NLINK, LA_RDEV, LA_SIZE, LA_TYPE, LA_UID, lu_attr::la_uid, lu_attr::la_valid, LASSERT, lu_ucred_check(), LUSTRE_APPEND_FL, LUSTRE_DIRSYNC_FL, LUSTRE_IMMUTABLE_FL, lustre_in_group_p(), LUSTRE_TOPDIR_FL, md_capable(), mdd_may_delete(), mdd_obj2mdd_dev(), mdd_permission_internal(), MDS_OWNEROVERRIDE, MDS_PERM_BYPASS, RETURN, and lu_ucred::uc_fsuid.
Referenced by mdd_attr_set().
int mdd_get_lov_ea (const struct lu_env * env, struct mdd_object * obj, struct lu_buf * lmm_buf)
Definition at line 1193 of file mdd_object.c.
References buf, bufsize, ENTRY, EXIT, GOTO, lu_buf::lb_buf, lu_buf::lb_len, lu_buf_alloc(), lu_buf_check_and_alloc(), lu_buf_free(), LU_BUF_NULL, mdd_env_info(), mdo_xattr_get(), mdd_thread_info::mti_big_buf, RETURN, and XATTR_NAME_LOV.
Referenced by mdd_migrate_create(), and mdd_swap_layouts().
static int mdd_hsm_update_locked (const struct lu_env * env, struct md_object * obj, const struct lu_buf * buf, struct thandle * handle) [static]
Definition at line 963 of file mdd_object.c.
References CL_HSM, CLASSERT, CLF_HSM_DIRTY, ENTRY, GOTO, HE_STATE, HS_DIRTY, hsm_set_cl_event(), hsm_set_cl_flags(), lu_buf::lb_buf, lu_buf::lb_len, lustre_buf2hsm(), md2mdd_obj(), mdd_buf_get(), mdd_changelog_data_store(), mdd_env_info(), mdo2mdd(), mdo_xattr_get(), md_hsm::mh_flags, mdd_thread_info::mti_xattr_buf, OBD_ALLOC_PTR, OBD_FREE_PTR, RETURN, and XATTR_NAME_HSM.
Referenced by mdd_xattr_set().
int mdd_la_get (const struct lu_env * env, struct mdd_object * obj, struct lu_attr * la)
Definition at line 65 of file mdd_object.c.
References CERROR, DEAD_OBJ, DFID, lu_attr::la_flags, LA_FLAGS, lu_attr::la_valid, LUSTRE_ORPHAN_FL, mdd_obj_dev_name(), mdd_object_exists(), mdd_object_fid(), mdo_attr_get(), mdd_object::mod_flags, ORPHAN_OBJ, PFID, and unlikely.
Referenced by mdd_attr_get(), mdd_attr_set(), mdd_close(), mdd_create(), mdd_create_data(), mdd_is_subdir(), mdd_link(), mdd_lookup(), mdd_migrate(), mdd_migrate_update_name(), mdd_object_start(), mdd_open(), mdd_permission(), mdd_rename(), mdd_swap_layouts(), mdd_unlink(), mdd_xattr_del(), and mdd_xattr_set().
static int mdd_layout_swap_allowed (const struct lu_env * env, struct mdd_object * o1, const struct lu_attr * attr1, struct mdd_object * o2, const struct lu_attr * attr2) [static]
Definition at line 1278 of file mdd_object.c.
References ENTRY, fid_is_igif(), fid_is_norm(), lu_attr::la_gid, lu_attr::la_uid, mdd_links_get(), mdd_object_type(), mdo2fid(), and RETURN.
Referenced by mdd_swap_layouts().
struct lu_object* mdd_object_alloc (const struct lu_env * env, const struct lu_object_header * hdr, struct lu_device * d) [read]
Definition at line 121 of file mdd_object.c.
References lu_object::lo_ops, lu_object_init(), mdd2lu_obj(), mdd_dir_ops, mdd_lu_obj_ops, mdd_obj_ops, mdd_object_kmem, md_object::mo_dir_ops, md_object::mo_ops, mdd_object::mod_count, mdd_object::mod_obj, and OBD_SLAB_ALLOC_PTR_GFP.
int mdd_object_create_internal (const struct lu_env * env, struct mdd_object * p, struct mdd_object * c, struct lu_attr * attr, struct thandle * handle, const struct md_op_spec * spec, struct dt_allocation_hint * hint)
Definition at line 377 of file mdd_object.c.
References ENTRY, LASSERT, mdd_env_info(), mdd_object_exists(), mdo_create_obj(), mdd_thread_info::mti_dof, and RETURN.
Referenced by mdd_object_create().
struct mdd_object* mdd_object_find (const struct lu_env * env, struct mdd_device * d, const struct lu_fid * f) [read]
Definition at line 202 of file mdd_object.c.
References md2mdd_obj(), md_object_find_slice(), and mdd_device::mdd_md_dev.
Referenced by mdd_is_parent(), mdd_migrate_entries(), mdd_rename(), mdd_update_linkea_internal(), obf_lookup(), and orph_key_test_and_del().
static void mdd_object_free (const struct lu_env * env, struct lu_object * o) [static]
Definition at line 177 of file mdd_object.c.
References lu2mdd_obj(), lu_object_fini(), mdd_object_kmem, and OBD_SLAB_FREE_PTR.
static int mdd_object_init (const struct lu_env * env, struct lu_object * o, const struct lu_object_conf * unused) [static]
Definition at line 143 of file mdd_object.c.
References dt_device::dd_lu_dev, ENTRY, lu_device::ld_ops, lu_device_operations::ldo_object_alloc, lu_object::lo_dev, lu_object::lo_header, lu2mdd_dev(), lu2mdd_obj(), lu_object_add(), mdd_device::mdd_child, mdd_object::mod_cltime, and RETURN.
static int mdd_object_lock (const struct lu_env * env, struct md_object * obj, struct lustre_handle * lh, struct ldlm_enqueue_info * einfo, union ldlm_policy_data * policy) [static]
Definition at line 2042 of file mdd_object.c.
References dt_object_lock(), md2mdd_obj(), and mdd_object_child().
void mdd_object_make_hint (const struct lu_env * env, struct mdd_object * parent, struct mdd_object * child, const struct lu_attr * attr, const struct md_op_spec * spec, struct dt_allocation_hint * hint)
Definition at line 1571 of file mdd_object.c.
References CDEBUG, D_INFO, dt_allocation_hint::dah_eadata, dt_allocation_hint::dah_eadata_len, DFID, dt_object_operations::do_ah_init, dt_object::do_ops, lu_attr::la_mode, mdd_object_child(), mdd_object_fid(), MDS_OPEN_HAS_EA, PFID, md_op_spec::sp_cr_flags, md_op_spec::sp_ea, md_op_spec::u, and unlikely.
Referenced by mdd_create(), mdd_create_data(), and mdd_migrate_create().
static int mdd_object_print (const struct lu_env * env, void * cookie, lu_printer_t p, const struct lu_object * o) [static]
Definition at line 185 of file mdd_object.c.
References LPU64, lu2mdd_obj(), LUSTRE_MDD_NAME, and mdd_object::mod_count.
static int mdd_object_start (const struct lu_env * env, struct lu_object * o) [static]
Definition at line 163 of file mdd_object.c.
References lu2mdd_obj(), lu_object_exists, MDD_ENV_VAR, and mdd_la_get().
static int mdd_object_sync (const struct lu_env * env, struct md_object * obj) [static]
Definition at line 2026 of file mdd_object.c.
References CERROR, DFID, dt_object_sync(), md2mdd_obj(), mdd_obj_dev_name(), mdd_object_child(), mdd_object_exists(), mdd_object_fid(), OBD_OBJECT_EOF, and PFID.
static int mdd_object_unlock (const struct lu_env * env, struct md_object * obj, struct ldlm_enqueue_info * einfo, union ldlm_policy_data * policy) [static]
Definition at line 2053 of file mdd_object.c.
References dt_object_unlock(), md2mdd_obj(), and mdd_object_child().
static int mdd_open (const struct lu_env * env, struct md_object * obj, int flags) [static]
Definition at line 1681 of file mdd_object.c.
References EXIT, GOTO, md2mdd_obj(), MDD_ENV_VAR, mdd_la_get(), mdd_open_sanity_check(), mdd_write_lock(), mdd_write_unlock(), mdd_object::mod_count, and MOR_TGT_CHILD.
static int mdd_open_sanity_check (const struct lu_env * env, struct mdd_object * obj, const struct lu_attr * attr, int flag) [static]
Definition at line 1626 of file mdd_object.c.
References accmode(), CFS_CAP_FOWNER, ENTRY, FMODE_WRITE, lu_attr::la_flags, lu_attr::la_mode, lu_attr::la_uid, lu_ucred(), LUSTRE_APPEND_FL, md_capable(), mdd_is_dead_obj(), mdd_permission_internal(), MDS_OPEN_APPEND, MDS_OPEN_CREATED, MDS_OPEN_TRUNC, mode, RETURN, lu_ucred::uc_fsuid, lu_ucred::uc_valid, UCRED_NEW, and UCRED_OLD.
Referenced by mdd_open().
int mdd_readlink (const struct lu_env * env, struct md_object * obj, struct lu_buf * buf)
Definition at line 271 of file mdd_object.c.
References CERROR, dt_body_operations::dbo_read, DFID, dt_object::do_body_ops, dt_read(), ENTRY, LASSERT, md2mdd_obj(), mdd_obj_dev_name(), mdd_object_child(), mdd_object_exists(), mdd_object_fid(), mdd_read_lock(), mdd_read_unlock(), MOR_TGT_CHILD, PFID, and RETURN.
Referenced by mdd_migrate_create().
int mdd_readpage (const struct lu_env * env, struct md_object * obj, const struct lu_rdpg * rdpg)
Definition at line 1958 of file mdd_object.c.
References CDEBUG, CERROR, cpu_to_le32, cpu_to_le64, D_INODE, DFID, dt_index_walk(), ENTRY, GOTO, LASSERT, LDF_EMPTY, lu_dirpage::ldp_flags, lu_dirpage::ldp_hash_end, lu_dirpage::ldp_hash_start, LU_PAGE_SIZE, md2mdd_obj(), mdd_dir_page_build(), mdd_is_dead_obj(), mdd_obj_dev_name(), mdd_object_child(), mdd_object_exists(), mdd_object_fid(), mdd_read_lock(), mdd_read_unlock(), mdd_readpage_sanity_check(), MDS_DIR_END_OFF, min_t, MOR_TGT_CHILD, PFID, lu_rdpg::rp_count, lu_rdpg::rp_hash, and lu_rdpg::rp_pages.
static int mdd_readpage_sanity_check (const struct lu_env * env, struct mdd_object * obj) [static]
Definition at line 1858 of file mdd_object.c.
References dt_try_as_dir(), ENTRY, mdd_object_child(), mdd_object_type(), and RETURN.
Referenced by mdd_readpage().
static int mdd_swap_layouts (const struct lu_env * env, struct md_object * obj1, struct md_object * obj2, __u64 flags) [static]
swap layouts between 2 lustre objects
Definition at line 1316 of file mdd_object.c.
References ARRAY_SIZE, CERROR, CL_LAYOUT, CLASSERT, cpu_to_le16, cpu_to_le32, DFID, ENTRY, EXIT, GOTO, lu_buf::lb_buf, LBUG, le16_to_cpu, LOV_MAGIC_V1, LOV_MAGIC_V1_DEF, LOV_MAGIC_V3, LOV_MAGIC_V3_DEF, lov_mds_md, lu_buf_alloc(), lu_buf_free(), lu_fid_cmp(), LU_XATTR_CREATE, LU_XATTR_REPLACE, md2mdd_obj(), mdd_changelog_data_store(), mdd_declare_xattr_del(), mdd_declare_xattr_set(), mdd_env_info(), MDD_ENV_VAR, mdd_get_lov_ea(), mdd_la_get(), mdd_layout_swap_allowed(), mdd_obj_dev_name(), mdd_trans_create(), mdd_trans_start(), mdd_trans_stop(), mdd_write_lock(), mdd_write_unlock(), mdd_xattr_hsm_replace(), mdo2fid(), mdo2mdd(), mdo_xattr_del(), mdo_xattr_get(), mdo_xattr_set(), MOR_TGT_CHILD, mdd_thread_info::mti_buf, mdd_thread_info::mti_oa, obdo::o_oi, OBD_FAIL_CHECK, OBD_FAIL_MDS_HSM_SWAP_LAYOUTS, PFID, RETURN, stop, swap, SWAP_LAYOUTS_MDS_HSM, unlikely, XATTR_NAME_HSM, and XATTR_NAME_LOV.
int mdd_update_time (const struct lu_env * env, struct mdd_object * obj, const struct lu_attr * oattr, struct lu_attr * attr, struct thandle * handle)
Definition at line 409 of file mdd_object.c.
References ENTRY, lu_attr::la_ctime, LA_CTIME, LA_MTIME, lu_attr::la_valid, LASSERT, mdd_attr_set_internal(), and RETURN.
Referenced by mdd_create(), mdd_link(), mdd_rename(), and mdd_unlink().
static int mdd_xattr_del (const struct lu_env * env, struct md_object * obj, const char * name) [static]
The caller should guarantee to update the object ctime after xattr_set if needed.
Definition at line 1137 of file mdd_object.c.
References CL_XATTR, ENTRY, GOTO, md2mdd_obj(), mdd_changelog_data_store(), mdd_declare_xattr_del(), MDD_ENV_VAR, mdd_la_get(), mdd_trans_create(), mdd_trans_start(), mdd_trans_stop(), mdd_write_lock(), mdd_write_unlock(), mdd_xattr_sanity_check(), mdo2mdd(), mdo_xattr_del(), MOR_TGT_CHILD, RETURN, stop, and XATTR_USER_PREFIX.
Referenced by mdd_xattr_set().
static int mdd_xattr_get (const struct lu_env * env, struct md_object * obj, struct lu_buf * buf, const char * name) [static]
Definition at line 230 of file mdd_object.c.
References CERROR, DEAD_OBJ, DFID, ENTRY, md2mdd_obj(), mdd_obj_dev_name(), mdd_object_exists(), mdd_object_fid(), mdd_read_lock(), mdd_read_unlock(), mdo_xattr_get(), mdd_object::mod_flags, MOR_TGT_CHILD, ORPHAN_OBJ, PFID, RETURN, unlikely, XATTR_NAME_LINK, and XATTR_NAME_LMV.
static int mdd_xattr_hsm_replace (const struct lu_env * env, struct mdd_object * o, struct lu_buf * buf, struct thandle * handle) [static]
Definition at line 1244 of file mdd_object.c.
References CL_HSM, ENTRY, HE_RELEASE, HS_RELEASED, hsm_attrs::hsm_flags, hsm_set_cl_event(), lu_buf::lb_buf, le32_to_cpu, LU_XATTR_REPLACE, mdd_changelog_data_store(), mdd_is_dead_obj(), mdo2mdd(), mdo_xattr_set(), mdd_object::mod_obj, RETURN, and XATTR_NAME_HSM.
Referenced by mdd_swap_layouts().
static int mdd_xattr_list (const struct lu_env * env, struct md_object * obj, struct lu_buf * buf) [static]
Definition at line 299 of file mdd_object.c.
References CDEBUG, D_INFO, DEAD_OBJ, DFID, end, ENTRY, lu_buf::lb_buf, md2mdd_obj(), mdd_object_fid(), mdd_read_lock(), mdd_read_unlock(), mdo_xattr_list(), mdd_object::mod_flags, MOR_TGT_CHILD, ORPHAN_OBJ, PFID, RETURN, unlikely, and XATTR_NAME_LINK.
static int mdd_xattr_sanity_check (const struct lu_env * env, struct mdd_object * obj, const struct lu_attr * attr) [static]
Definition at line 905 of file mdd_object.c.
References CFS_CAP_FOWNER, ENTRY, lu_attr::la_flags, lu_attr::la_uid, lu_ucred_assert(), LUSTRE_APPEND_FL, LUSTRE_IMMUTABLE_FL, md_capable(), RETURN, and lu_ucred::uc_fsuid.
Referenced by mdd_xattr_del(), and mdd_xattr_set().
static int mdd_xattr_set (const struct lu_env * env, struct md_object * obj, const struct lu_buf * buf, const char * name, int fl) [static]
The caller should guarantee to update the object ctime after xattr_set if needed.
Definition at line 1023 of file mdd_object.c.
References CL_LAYOUT, CL_XATTR, ENTRY, GOTO, lu_buf::lb_buf, lu_buf::lb_len, md2mdd_obj(), mdd_acl_set(), mdd_changelog_data_store(), mdd_declare_xattr_set(), MDD_ENV_VAR, mdd_hsm_update_locked(), mdd_la_get(), mdd_trans_create(), mdd_trans_start(), mdd_trans_stop(), mdd_write_lock(), mdd_write_unlock(), mdd_xattr_del(), mdd_xattr_sanity_check(), mdo2mdd(), mdo_xattr_set(), MOR_TGT_CHILD, posix_acl_from_xattr, RETURN, stop, XATTR_NAME_ACL_ACCESS, XATTR_NAME_ACL_DEFAULT, XATTR_NAME_HSM, XATTR_NAME_LOV, and XATTR_USER_PREFIX.
static bool permission_needs_sync (const struct lu_attr * old, const struct lu_attr * new) [inline, static]
Definition at line 812 of file mdd_object.c.
References LA_GID, LA_MODE, lu_attr::la_mode, and LA_UID.
Referenced by mdd_attr_set().
Variable Documentation
static struct lu_object_operations mdd_lu_obj_ops [static, read]
Initial value:
 {
        .loo_object_init    = mdd_object_init,
        .loo_object_start   = mdd_object_start,
        .loo_object_free    = mdd_object_free,
        .loo_object_print   = mdd_object_print,
}
Definition at line 59 of file mdd_object.c.
Referenced by mdd_object_alloc().
struct md_object_operations mdd_obj_ops
Initial value:
 {
        .moo_permission         = mdd_permission,
        .moo_attr_get           = mdd_attr_get,
        .moo_attr_set           = mdd_attr_set,
        .moo_xattr_get          = mdd_xattr_get,
        .moo_xattr_set          = mdd_xattr_set,
        .moo_xattr_list         = mdd_xattr_list,
        .moo_xattr_del          = mdd_xattr_del,
        .moo_swap_layouts       = mdd_swap_layouts,
        .moo_open               = mdd_open,
        .moo_close              = mdd_close,
        .moo_readpage           = mdd_readpage,
        .moo_readlink           = mdd_readlink,
        .moo_changelog          = mdd_changelog,
        .moo_object_sync        = mdd_object_sync,
        .moo_object_lock        = mdd_object_lock,
        .moo_object_unlock      = mdd_object_unlock,
}
Definition at line 2062 of file mdd_object.c.
Referenced by mdd_object_alloc().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.