Lustre: lustre/mdd/mdd_internal.h File Reference
lustre/mdd/mdd_internal.h File Reference
#include <lustre_acl.h>
#include <lustre_eacl.h>
#include <md_object.h>
#include <dt_object.h>
#include <lustre_lfsck.h>
#include <lustre_fid.h>
#include <lprocfs_status.h>
#include <lustre_log.h>
#include <lustre_linkea.h>
Data Structures
struct mdd_changelog
struct mdd_dot_lustre_objs
Objects in .lustre dir.
struct mdd_generic_thread
struct mdd_device
struct mdd_object
struct mdd_thread_info
Defines
#define CLM_ON 0x00001
changelog is recording
#define CLM_ERR 0x00002
internal error prevented changelogs from starting
#define CLM_START 0x10000
changelogs turned on
#define CLM_FINI 0x20000
changelogs turned off
#define CLM_PURGE 0x40000
some changelog records purged
#define MDD_ENV_VAR(env, var) (&mdd_env_info(env)->mti_##var)
#define MAX_ATIME_DIFF 60
Enumerations
enum mod_flags { DEAD_OBJ = 1 << 0, ORPHAN_OBJ = 1 << 1 }
enum mdd_links_add_overflow { MLAO_IGNORE = false, MLAO_CHECK = true }
Functions
static __u64 cl_time (void)
int mdd_la_get (const struct lu_env *env, struct mdd_object *obj, struct lu_attr *la)
int mdd_attr_get (const struct lu_env *env, struct md_object *obj, struct md_attr *ma)
int mdd_attr_set (const struct lu_env *env, struct md_object *obj, const struct md_attr *ma)
int mdd_attr_set_internal (const struct lu_env *env, struct mdd_object *obj, const struct lu_attr *attr, struct thandle *handle, int needacl)
int mdd_update_time (const struct lu_env *env, struct mdd_object *obj, const struct lu_attr *oattr, struct lu_attr *attr, struct thandle *handle)
int mdd_object_create_internal (const struct lu_env *env, struct mdd_object *p, struct mdd_object *c, struct lu_attr *attr, struct thandle *handle, const struct md_op_spec *spec, struct dt_allocation_hint *hint)
void mdd_write_lock (const struct lu_env *env, struct mdd_object *obj, enum mdd_object_role role)
void mdd_read_lock (const struct lu_env *env, struct mdd_object *obj, enum mdd_object_role role)
void mdd_write_unlock (const struct lu_env *env, struct mdd_object *obj)
void mdd_read_unlock (const struct lu_env *env, struct mdd_object *obj)
int mdd_write_locked (const struct lu_env *env, struct mdd_object *obj)
int mdd_is_subdir (const struct lu_env *env, struct md_object *mo, const struct lu_fid *fid, struct lu_fid *sfid)
int mdd_may_create (const struct lu_env *env, struct mdd_object *pobj, const struct lu_attr *pattr, struct mdd_object *cobj, bool check_perm)
Check whether it may create the cobj under the pobj.
int mdd_may_unlink (const struct lu_env *env, struct mdd_object *pobj, const struct lu_attr *pattr, const struct lu_attr *attr)
int mdd_may_delete (const struct lu_env *env, struct mdd_object *tpobj, const struct lu_attr *tpattr, struct mdd_object *tobj, const struct lu_attr *tattr, const struct lu_attr *cattr, int check_perm, int check_empty)
int mdd_unlink_sanity_check (const struct lu_env *env, struct mdd_object *pobj, const struct lu_attr *pattr, struct mdd_object *cobj, const struct lu_attr *cattr)
int mdd_finish_unlink (const struct lu_env *env, struct mdd_object *obj, struct md_attr *ma, const struct mdd_object *pobj, const struct lu_name *lname, struct thandle *th)
int mdd_is_root (struct mdd_device *mdd, const struct lu_fid *fid)
int mdd_lookup (const struct lu_env *env, struct md_object *pobj, const struct lu_name *lname, struct lu_fid *fid, struct md_op_spec *spec)
int mdd_links_read (const struct lu_env *env, struct mdd_object *mdd_obj, struct linkea_data *ldata)
Read the link EA into a temp buffer.
int mdd_declare_links_add (const struct lu_env *env, struct mdd_object *mdd_obj, struct thandle *handle, struct linkea_data *ldata, enum mdd_links_add_overflow overflow)
int mdd_links_write (const struct lu_env *env, struct mdd_object *mdd_obj, struct linkea_data *ldata, struct thandle *handle)
struct lu_buf * mdd_links_get (const struct lu_env *env, struct mdd_object *mdd_obj)
Read the link EA into a temp buffer.
int mdd_links_rename (const struct lu_env *env, struct mdd_object *mdd_obj, const struct lu_fid *oldpfid, const struct lu_name *oldlname, const struct lu_fid *newpfid, const struct lu_name *newlname, struct thandle *handle, struct linkea_data *ldata, int first, int check)
struct mdd_thread_info * mdd_env_info (const struct lu_env *env)
struct lu_buf * mdd_buf_get (const struct lu_env *env, void *area, ssize_t len)
struct lu_buf * mdd_buf_get_const (const struct lu_env *env, const void *area, ssize_t len)
int mdd_orphan_cleanup (const struct lu_env *env, struct mdd_device *d)
Iterate orphan index to cleanup orphan objects after recovery is done.
int __mdd_orphan_add (const struct lu_env *, struct mdd_object *, struct thandle *)
add an orphan obj to the orphan index.
int __mdd_orphan_del (const struct lu_env *, struct mdd_object *, struct thandle *)
delete an orphan obj from orphan index.
int orph_index_init (const struct lu_env *env, struct mdd_device *mdd)
open the PENDING directory for device mdd
void orph_index_fini (const struct lu_env *env, struct mdd_device *mdd)
int orph_declare_index_insert (const struct lu_env *, struct mdd_object *, umode_t mode, struct thandle *)
int orph_declare_index_delete (const struct lu_env *, struct mdd_object *, struct thandle *)
int mdd_procfs_init (struct mdd_device *mdd, const char *name)
void mdd_procfs_fini (struct mdd_device *mdd)
int mdd_readlink (const struct lu_env *env, struct md_object *obj, struct lu_buf *buf)
int accmode (const struct lu_env *env, const struct lu_attr *la, int flags)
struct mdd_object * mdd_object_find (const struct lu_env *env, struct mdd_device *d, const struct lu_fid *f)
int mdd_readpage (const struct lu_env *env, struct md_object *obj, const struct lu_rdpg *rdpg)
int mdd_declare_changelog_store (const struct lu_env *env, struct mdd_device *mdd, const struct lu_name *tname, const struct lu_name *sname, struct thandle *handle)
void mdd_changelog_rec_ext_jobid (struct changelog_rec *rec, const char *jobid)
int mdd_changelog_store (const struct lu_env *env, struct mdd_device *mdd, struct llog_changelog_rec *rec, struct thandle *th)
Add a changelog entry rec to the changelog llog.
int mdd_changelog_data_store (const struct lu_env *env, struct mdd_device *mdd, enum changelog_rec_type type, int flags, struct mdd_object *mdd_obj, struct thandle *handle)
Store a data change changelog record If this fails, we must fail the whole transaction; we don't want the change to commit without the log entry.
int mdd_changelog_ns_store (const struct lu_env *env, struct mdd_device *mdd, enum changelog_rec_type type, enum changelog_rec_flags crf, struct mdd_object *target, const struct lu_fid *tpfid, const struct lu_fid *sfid, const struct lu_fid *spfid, const struct lu_name *tname, const struct lu_name *sname, struct thandle *handle)
Store a namespace change changelog record If this fails, we must fail the whole transaction; we don't want the change to commit without the log entry.
int mdd_declare_object_create_internal (const struct lu_env *env, struct mdd_object *p, struct mdd_object *c, struct lu_attr *attr, struct thandle *handle, const struct md_op_spec *spec, struct dt_allocation_hint *hint)
int mdd_get_lov_ea (const struct lu_env *env, struct mdd_object *obj, struct lu_buf *lmm_buf)
void mdd_object_make_hint (const struct lu_env *env, struct mdd_object *parent, struct mdd_object *child, const struct lu_attr *attr, const struct md_op_spec *spec, struct dt_allocation_hint *hint)
static void mdd_object_get (struct mdd_object *o)
static void mdd_object_put (const struct lu_env *env, struct mdd_object *o)
struct thandle * mdd_trans_create (const struct lu_env *env, struct mdd_device *mdd)
int mdd_trans_start (const struct lu_env *env, struct mdd_device *mdd, struct thandle *th)
int mdd_trans_stop (const struct lu_env *env, struct mdd_device *mdd, int rc, struct thandle *handle)
struct lu_object * mdd_object_alloc (const struct lu_env *env, const struct lu_object_header *hdr, struct lu_device *d)
int mdd_local_file_create (const struct lu_env *env, struct mdd_device *mdd, const struct lu_fid *pfid, const char *name, __u32 mode, struct lu_fid *fid)
int mdd_acl_chmod (const struct lu_env *env, struct mdd_object *o, __u32 mode, struct thandle *handle)
int mdd_acl_set (const struct lu_env *env, struct mdd_object *obj, struct lu_attr *attr, const struct lu_buf *buf, int fl)
int __mdd_fix_mode_acl (const struct lu_env *env, struct lu_buf *buf, __u32 *mode)
int __mdd_permission_internal (const struct lu_env *env, struct mdd_object *obj, const struct lu_attr *la, int mask, int role)
int mdd_permission (const struct lu_env *env, struct md_object *pobj, struct md_object *cobj, struct md_attr *ma, int mask)
int mdd_generic_thread_start (struct mdd_generic_thread *thread, int(*func)(void *), void *data, char *name)
void mdd_generic_thread_stop (struct mdd_generic_thread *thread)
int mdd_compat_fixes (const struct lu_env *env, struct mdd_device *mdd)
static int lu_device_is_mdd (struct lu_device *d)
static struct mdd_device * lu2mdd_dev (struct lu_device *d)
static struct lu_device * mdd2lu_dev (struct mdd_device *d)
static struct mdd_object * lu2mdd_obj (struct lu_object *o)
static struct mdd_device * mdo2mdd (struct md_object *mdo)
static struct mdd_object * md2mdd_obj (struct md_object *mdo)
static struct
dt_device_operations * mdd_child_ops (struct mdd_device *d)
static struct lu_object * mdd2lu_obj (struct mdd_object *obj)
static struct dt_object * mdd_object_child (struct mdd_object *o)
static struct obd_device * mdd2obd_dev (struct mdd_device *mdd)
static struct mdd_device * mdd_obj2mdd_dev (struct mdd_object *obj)
static struct lu_fid * mdo2fid (const struct mdd_object *obj)
static umode_t mdd_object_type (const struct mdd_object *obj)
static int mdd_is_dead_obj (struct mdd_object *obj)
static int mdd_object_exists (struct mdd_object *obj)
static int mdd_object_remote (struct mdd_object *obj)
static struct lu_fid * mdd_object_fid (struct mdd_object *obj)
static struct seq_server_site * mdd_seq_site (struct mdd_device *mdd)
static const char * mdd_obj_dev_name (const struct mdd_object *obj)
static int mdd_permission_internal (const struct lu_env *env, struct mdd_object *obj, const struct lu_attr *la, int mask)
static int mdd_permission_internal_locked (const struct lu_env *env, struct mdd_object *obj, const struct lu_attr *la, int mask, enum mdd_object_role role)
static int mdo_attr_get (const struct lu_env *env, struct mdd_object *obj, struct lu_attr *la)
static int mdo_declare_attr_set (const struct lu_env *env, struct mdd_object *obj, const struct lu_attr *la, struct thandle *handle)
static int mdo_attr_set (const struct lu_env *env, struct mdd_object *obj, const struct lu_attr *la, struct thandle *handle)
static int mdo_xattr_get (const struct lu_env *env, struct mdd_object *obj, struct lu_buf *buf, const char *name)
static int mdo_declare_xattr_set (const struct lu_env *env, struct mdd_object *obj, const struct lu_buf *buf, const char *name, int fl, struct thandle *handle)
static int mdo_xattr_set (const struct lu_env *env, struct mdd_object *obj, const struct lu_buf *buf, const char *name, int fl, struct thandle *handle)
static int mdo_declare_xattr_del (const struct lu_env *env, struct mdd_object *obj, const char *name, struct thandle *handle)
static int mdo_xattr_del (const struct lu_env *env, struct mdd_object *obj, const char *name, struct thandle *handle)
static int mdo_xattr_list (const struct lu_env *env, struct mdd_object *obj, struct lu_buf *buf)
static int mdo_declare_index_insert (const struct lu_env *env, struct mdd_object *obj, const struct lu_fid *fid, __u32 type, const char *name, struct thandle *handle)
static int mdo_declare_index_delete (const struct lu_env *env, struct mdd_object *obj, const char *name, struct thandle *handle)
static int mdo_declare_ref_add (const struct lu_env *env, struct mdd_object *obj, struct thandle *handle)
static int mdo_ref_add (const struct lu_env *env, struct mdd_object *obj, struct thandle *handle)
static int mdo_declare_ref_del (const struct lu_env *env, struct mdd_object *obj, struct thandle *handle)
static int mdo_ref_del (const struct lu_env *env, struct mdd_object *obj, struct thandle *handle)
static int mdo_declare_create_obj (const struct lu_env *env, struct mdd_object *o, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *handle)
static int mdo_create_obj (const struct lu_env *env, struct mdd_object *o, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *handle)
static int mdo_declare_destroy (const struct lu_env *env, struct mdd_object *o, struct thandle *handle)
static int mdo_destroy (const struct lu_env *env, struct mdd_object *o, struct thandle *handle)
Variables
const char orph_index_name []
struct kmem_cache * mdd_object_kmem
struct md_dir_operations mdd_dir_ops
struct md_object_operations mdd_obj_ops
struct lu_context_key mdd_thread_key
struct lu_device_operations mdd_lu_ops
Define Documentation
#define CLM_ERR 0x00002
internal error prevented changelogs from starting
Definition at line 58 of file mdd_internal.h.
Referenced by mdd_changelog_init(), and mdd_changelog_on().
#define CLM_FINI 0x20000
changelogs turned off
Definition at line 63 of file mdd_internal.h.
Referenced by mdd_changelog_off().
#define CLM_ON 0x00001
changelog is recording
Definition at line 56 of file mdd_internal.h.
Referenced by mdd_changelog_data_store(), mdd_changelog_ns_store(), mdd_changelog_off(), mdd_changelog_on(), and mdd_declare_changelog_store().
#define CLM_PURGE 0x40000
some changelog records purged
Definition at line 65 of file mdd_internal.h.
Referenced by mdd_changelog_llog_cancel().
#define CLM_START 0x10000
changelogs turned on
Definition at line 61 of file mdd_internal.h.
Referenced by mdd_changelog_on().
#define MAX_ATIME_DIFF 60
Definition at line 465 of file mdd_internal.h.
Referenced by mdd_init0().
#define MDD_ENV_VAR (env, var) (&mdd_env_info(env)->mti_##var)
Definition at line 246 of file mdd_internal.h.
Referenced by mdd_attr_set(), mdd_create_data(), mdd_declare_migrate_create(), mdd_declare_migrate_update_name(), mdd_is_subdir(), mdd_link(), mdd_lookup(), mdd_mark_orphan_object(), mdd_migrate(), mdd_migrate_create(), mdd_migrate_update_name(), mdd_object_start(), mdd_open(), mdd_permission(), mdd_rename(), mdd_swap_layouts(), mdd_unlink(), mdd_xattr_del(), and mdd_xattr_set().
Enumeration Type Documentation
enum mdd_links_add_overflow
Enumerator:
MLAO_IGNORE
MLAO_CHECK
Definition at line 165 of file mdd_internal.h.
enum mod_flags
Enumerator:
DEAD_OBJ
ORPHAN_OBJ
Definition at line 118 of file mdd_internal.h.
Function Documentation
int __mdd_fix_mode_acl (const struct lu_env * env, struct lu_buf * buf, __u32 * mode)
Referenced by mdd_acl_init().
int __mdd_orphan_add (const struct lu_env * env, struct mdd_object * obj, struct thandle * th)
add an orphan obj to the orphan index.
Parameters:
obj file or directory.
th transaction for index insert.
Precondition:
obj nlink == 0 && obj->mod_count != 0
Return values:
0 success
-ve index operation error.
Definition at line 628 of file mdd_orphans.c.
References orph_index_insert(), and ORPH_OP_UNLINK.
Referenced by mdd_create(), mdd_finish_unlink(), and mdd_migrate_update_name().
int __mdd_orphan_del (const struct lu_env * env, struct mdd_object * obj, struct thandle * th)
delete an orphan obj from orphan index.
Parameters:
obj file or directory.
th transaction for index deletion and object destruction.
Precondition:
obj->mod_count == 0 && ORPHAN_OBJ is set for obj.
Return values:
0 success
-ve index operation error.
Definition at line 644 of file mdd_orphans.c.
References orph_index_delete(), and ORPH_OP_UNLINK.
Referenced by mdd_close(), and mdd_create().
int __mdd_permission_internal (const struct lu_env * env, struct mdd_object * obj, const struct lu_attr * la, int mask, int role)
Definition at line 240 of file mdd_permission.c.
References CDEBUG, CFS_CAP_DAC_OVERRIDE, CFS_CAP_DAC_READ_SEARCH, D_SEC, ENTRY, lu_attr::la_flags, lu_attr::la_gid, lu_attr::la_mode, lu_attr::la_uid, LASSERT, lu_ucred(), LUSTRE_IMMUTABLE_FL, lustre_in_group_p(), md_capable(), mdd_check_acl(), mdd_read_lock(), mdd_read_unlock(), RETURN, lu_ucred::uc_fsuid, lu_ucred::uc_valid, UCRED_INIT, and UCRED_INVALID.
Referenced by mdd_permission_internal(), and mdd_permission_internal_locked().
int accmode (const struct lu_env * env, const struct lu_attr * la, int flags)
Definition at line 1601 of file mdd_object.c.
References FMODE_READ, FMODE_WRITE, lu_attr::la_uid, lu_ucred_check(), MDS_FMODE_EXEC, MDS_OPEN_APPEND, MDS_OPEN_OWNEROVERRIDE, MDS_OPEN_TRUNC, and lu_ucred::uc_fsuid.
Referenced by mdd_open_sanity_check(), and mdd_permission().
static __u64 cl_time (void) [inline, static]
Definition at line 77 of file mdd_internal.h.
References __u64, and cfs_fs_time_current().
Referenced by mdd_changelog_store(), and mdd_changelog_write_header().
static struct mdd_device* lu2mdd_dev (struct lu_device * d) [static, read]
Definition at line 371 of file mdd_internal.h.
References LASSERT, lu_device_is_mdd(), md_device::md_lu_dev, and mdd_device::mdd_md_dev.
Referenced by mdd_device_fini(), mdd_device_free(), mdd_iocontrol(), mdd_llog_ctxt_get(), mdd_maxeasize_get(), mdd_obd_connect(), mdd_obd_disconnect(), mdd_obd_get_info(), mdd_obd_set_info_async(), mdd_object_init(), mdd_prepare(), mdd_process_config(), mdd_recovery_complete(), mdd_root_get(), mdd_statfs(), and mdo2mdd().
static struct mdd_object* lu2mdd_obj (struct lu_object * o) [static, read]
Definition at line 382 of file mdd_internal.h.
References ergo, LASSERT, lu_object::lo_dev, lu_device_is_mdd(), md_object::mo_lu, and mdd_object::mod_obj.
Referenced by mdd_object_free(), mdd_object_init(), mdd_object_print(), and mdd_object_start().
static int lu_device_is_mdd (struct lu_device * d) [inline, static]
Definition at line 366 of file mdd_internal.h.
References ergo, lu_device::ld_ops, and mdd_lu_ops.
Referenced by lu2mdd_dev(), and lu2mdd_obj().
static struct mdd_object* md2mdd_obj (struct md_object * mdo) [static, read]
Definition at line 393 of file mdd_internal.h.
References mdd_object::mod_obj.
Referenced by __mdd_lookup(), mdd_attr_get(), mdd_attr_set(), mdd_attr_set_changelog(), mdd_changelog(), mdd_close(), mdd_create(), mdd_create_data(), mdd_create_sanity_check(), mdd_dot_lustre_setup(), mdd_hsm_update_locked(), mdd_is_subdir(), mdd_link(), mdd_lookup(), mdd_lpf_setup(), mdd_migrate(), mdd_obf_setup(), mdd_object_find(), mdd_object_lock(), mdd_object_sync(), mdd_object_unlock(), mdd_open(), mdd_permission(), mdd_readlink(), mdd_readpage(), mdd_rename(), mdd_swap_layouts(), mdd_unlink(), mdd_xattr_del(), mdd_xattr_get(), mdd_xattr_list(), and mdd_xattr_set().
static struct lu_device* mdd2lu_dev (struct mdd_device * d) [static, read]
Definition at line 377 of file mdd_internal.h.
References md_device::md_lu_dev, and mdd_device::mdd_md_dev.
Referenced by mdd_close(), mdd_connect_to_next(), mdd_device_alloc(), mdd_device_shutdown(), and mdd_seq_site().
static struct lu_object* mdd2lu_obj (struct mdd_object * obj) [static, read]
Definition at line 404 of file mdd_internal.h.
References md_object::mo_lu, and mdd_object::mod_obj.
Referenced by mdd_object_alloc(), mdd_object_child(), mdd_object_exists(), mdd_object_fid(), and mdd_object_remote().
static struct obd_device* mdd2obd_dev (struct mdd_device * mdd) [static, read]
Definition at line 415 of file mdd_internal.h.
References lu_device::ld_obd, md_device::md_lu_dev, and mdd_device::mdd_md_dev.
Referenced by __mdd_lookup(), mdd_attr_set(), mdd_changelog_fini(), mdd_changelog_init(), mdd_changelog_llog_cancel(), mdd_changelog_llog_init(), mdd_changelog_ns_store(), mdd_changelog_off(), mdd_changelog_on(), mdd_changelog_size_ctxt(), mdd_changelog_store(), mdd_changelog_user_purge(), mdd_changelog_user_register(), mdd_changelog_users_seq_show(), mdd_changelog_write_header(), mdd_declare_changelog_store(), mdd_dot_lustre_setup(), mdd_hsm_actions_llog_fini(), mdd_hsm_actions_llog_init(), mdd_linkea_update_child_internal(), mdd_llog_ctxt_get(), mdd_migrate(), mdd_migrate_create(), mdd_migrate_entries(), mdd_migrate_sanity_check(), mdd_migrate_update_name(), mdd_orphan_cleanup(), mdd_prepare(), mdd_process_config(), mdd_procfs_init(), mdd_rename(), mdd_update_linkea_internal(), obf_lookup(), orph_index_init(), orph_index_iterate(), and orph_key_test_and_del().
int mdd_acl_chmod (const struct lu_env * env, struct mdd_object * o, __u32 mode, struct thandle * handle)
Referenced by mdd_attr_set_internal().
int mdd_acl_set (const struct lu_env * env, struct mdd_object * obj, struct lu_attr * attr, const struct lu_buf * buf, int fl)
Referenced by mdd_xattr_set().
int mdd_attr_get (const struct lu_env * env, struct md_object * obj, struct md_attr * ma)
Definition at line 212 of file mdd_object.c.
References ENTRY, lu_attr::la_nlink, md_attr::ma_attr, MA_INODE, md_attr::ma_need, md2mdd_obj(), mdd_is_dead_obj(), mdd_la_get(), and RETURN.
int mdd_attr_set (const struct lu_env * env, struct md_object * obj, const struct md_attr * ma)
Definition at line 834 of file mdd_object.c.
References CDEBUG, D_INODE, DFID, ENTRY, GOTO, lu_attr::la_ctime, LA_CTIME, LA_FLAGS, lu_attr::la_mtime, LA_MTIME, lu_attr::la_valid, LASSERT, LPU64, LPX64, md_attr::ma_attr, md_attr::ma_attr_flags, MA_HSM, MA_LOV, md_attr::ma_valid, md2mdd_obj(), mdd2obd_dev(), mdd_attr_set_changelog(), mdd_attr_set_internal(), mdd_declare_attr_set(), mdd_env_info(), MDD_ENV_VAR, mdd_fix_attr(), mdd_la_get(), mdd_device::mdd_sync_permission, mdd_trans_create(), mdd_trans_start(), mdd_trans_stop(), mdd_write_lock(), mdd_write_unlock(), mdo2fid(), mdo2mdd(), MOR_TGT_CHILD, mdd_thread_info::mti_la_for_fix, permission_needs_sync(), PFID, RETURN, stop, and thandle::th_sync.
int mdd_attr_set_internal (const struct lu_env * env, struct mdd_object * obj, const struct lu_attr * attr, struct thandle * handle, int needacl)
Definition at line 394 of file mdd_object.c.
References ENTRY, lu_attr::la_mode, LA_MODE, lu_attr::la_valid, mdd_acl_chmod(), mdo_attr_set(), and RETURN.
Referenced by mdd_attr_set(), mdd_migrate_update_name(), and mdd_update_time().
struct lu_buf* mdd_buf_get (const struct lu_env * env, void * area, ssize_t len) [read]
Definition at line 100 of file mdd_object.c.
References buf, lu_buf::lb_buf, lu_buf::lb_len, mdd_env_info(), and mdd_thread_info::mti_buf.
Referenced by mdd_check_acl(), mdd_declare_attr_set(), mdd_hsm_archive_exists(), and mdd_hsm_update_locked().
struct lu_buf* mdd_buf_get_const (const struct lu_env * env, const void * area, ssize_t len) [read]
Definition at line 110 of file mdd_object.c.
References buf, lu_buf::lb_buf, lu_buf::lb_len, mdd_env_info(), and mdd_thread_info::mti_buf.
Referenced by mdd_create_data(), mdd_declare_links_add(), mdd_declare_migrate_create(), mdd_declare_object_create(), mdd_links_write(), mdd_migrate_create(), and mdd_object_create().
int mdd_changelog_data_store (const struct lu_env * env, struct mdd_device * mdd, enum changelog_rec_type type, int flags, struct mdd_object * mdd_obj, struct thandle * handle)
Store a data change changelog record If this fails, we must fail the whole transaction; we don't want the change to commit without the log entry.
Parameters:
mdd_obj - mdd_object of change
handle - transaction handle
Definition at line 643 of file mdd_object.c.
References buf, cfs_time_before_64(), cfs_time_current_64, changelog_rec_offset(), CL_ATIME, CL_MTIME, CLF_FLAGMASK, CLF_JOBID, CLF_SUPPORTED, CLF_VERSION, CLM_ON, llog_changelog_rec::cr, changelog_rec::cr_flags, changelog_rec::cr_namelen, changelog_rec::cr_tfid, changelog_rec::cr_type, LASSERT, lu_buf::lb_buf, llog_data_len(), lu_buf_check_and_alloc(), lu_ucred(), mdd_changelog::mc_flags, mdd_changelog::mc_mask, mdd_changelog::mc_starttime, mdd_changelog_rec_ext_jobid(), mdd_changelog_store(), mdd_device::mdd_cl, mdd_env_info(), mdo2fid(), mdd_object::mod_cltime, RETURN, and lu_ucred::uc_jobid.
Referenced by mdd_attr_set_changelog(), mdd_changelog(), mdd_close(), mdd_create_data(), mdd_hsm_update_locked(), mdd_swap_layouts(), mdd_xattr_del(), mdd_xattr_hsm_replace(), and mdd_xattr_set().
int mdd_changelog_ns_store (const struct lu_env * env, struct mdd_device * mdd, enum changelog_rec_type type, enum changelog_rec_flags crf, struct mdd_object * target, const struct lu_fid * tpfid, const struct lu_fid * sfid, const struct lu_fid * spfid, const struct lu_name * tname, const struct lu_name * sname, struct thandle * handle)
Store a namespace change changelog record If this fails, we must fail the whole transaction; we don't want the change to commit without the log entry.
Parameters:
target - mdd_object of change
tpfid - target parent dir/object fid
sfid - source object fid
spfid - source parent fid
tname - target name string
sname - source name string
handle - transaction handle
Definition at line 817 of file mdd_dir.c.
References buf, CERROR, cfs_time_current_64, changelog_rec_name(), CLF_FLAGMASK, CLF_JOBID, CLF_RENAME, CLF_VERSION, CLM_ON, llog_changelog_rec::cr, changelog_rec::cr_flags, changelog_rec::cr_namelen, changelog_rec::cr_pfid, changelog_rec::cr_tfid, changelog_rec::cr_type, DFID, ENTRY, fid_zero(), LASSERT, lu_buf::lb_buf, likely, lu_name::ln_name, lu_name::ln_namelen, lu_buf_check_and_alloc(), lu_ucred(), mdd_changelog::mc_flags, mdd_changelog::mc_mask, mdd2obd_dev(), mdd_changelog_rec_ext_jobid(), mdd_changelog_rec_ext_rename(), mdd_changelog_store(), mdd_device::mdd_cl, mdd_env_info(), mdd_llog_record_calc_size(), mdo2fid(), mdd_object::mod_cltime, PFID, RETURN, and lu_ucred::uc_jobid.
Referenced by mdd_create(), mdd_link(), mdd_migrate_update_name(), mdd_rename(), and mdd_unlink().
void mdd_changelog_rec_ext_jobid (struct changelog_rec * rec, const char * jobid)
Definition at line 796 of file mdd_dir.c.
References changelog_rec_jobid(), changelog_ext_jobid::cr_jobid, and strlcpy().
Referenced by mdd_changelog_data_store(), and mdd_changelog_ns_store().
int mdd_changelog_store (const struct lu_env * env, struct mdd_device * mdd, struct llog_changelog_rec * rec, struct thandle * th)
Add a changelog entry rec to the changelog llog.
Parameters:
mdd
rec
handle - currently ignored since llogs start their own transaction; this will hopefully be fixed in llog rewrite
Return values:
0 ok
Definition at line 736 of file mdd_dir.c.
References CHANGELOG_REC, changelog_rec_varsize(), cl_time(), llog_changelog_rec::cr, llog_changelog_rec::cr_hdr, changelog_rec::cr_index, changelog_rec::cr_time, GOTO, llog_handle::lgh_obj, llog_add(), LLOG_CHANGELOG_ORIG_CTXT, llog_ctxt_put(), llog_data_len(), llog_get_context(), llog_ctxt::loc_handle, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, mdd_changelog::mc_index, mdd_changelog::mc_lock, mdd2obd_dev(), mdd_device::mdd_cl, and thandle_get_sub().
Referenced by mdd_changelog_data_store(), and mdd_changelog_ns_store().
static struct dt_device_operations* mdd_child_ops (struct mdd_device * d) [static, read]
Definition at line 399 of file mdd_internal.h.
References dt_device::dd_ops, and mdd_device::mdd_child.
Referenced by mdd_statfs(), mdd_trans_create(), mdd_trans_start(), and mdd_trans_stop().
int mdd_compat_fixes (const struct lu_env * env, struct mdd_device * mdd)
int mdd_declare_changelog_store (const struct lu_env * env, struct mdd_device * mdd, const struct lu_name * tname, const struct lu_name * sname, struct thandle * handle)
Definition at line 686 of file mdd_dir.c.
References buf, CHANGELOG_REC, CLM_ON, llog_changelog_rec::cr_hdr, GOTO, lu_buf::lb_buf, llog_handle::lgh_obj, LLOG_CHANGELOG_ORIG_CTXT, llog_ctxt_put(), llog_declare_add(), llog_get_context(), llog_ctxt::loc_handle, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, lu_buf_check_and_alloc(), mdd_changelog::mc_flags, mdd2obd_dev(), mdd_device::mdd_cl, mdd_env_info(), mdd_llog_record_calc_size(), and thandle_get_sub().
Referenced by mdd_changelog(), mdd_close(), mdd_create_data(), mdd_declare_attr_set(), mdd_declare_create(), mdd_declare_link(), mdd_declare_migrate_update_name(), mdd_declare_rename(), mdd_declare_unlink(), mdd_declare_xattr_del(), and mdd_declare_xattr_set().
int mdd_declare_links_add (const struct lu_env * env, struct mdd_object * mdd_obj, struct thandle * handle, struct linkea_data * ldata, enum mdd_links_add_overflow overflow)
Definition at line 1188 of file mdd_dir.c.
References DEFAULT_LINKEA_SIZE, lu_buf::lb_buf, linkea_data::ld_buf, linkea_data::ld_leh, LE_SKIP_NLINK_DECLARE, link_ea_header::leh_len, lfsck_in_notify(), lfsck_pack_rfa(), LFSCK_TYPE_NAMESPACE, mdd_device::mdd_bottom, mdd_buf_get_const(), mdd_env_info(), mdd_object_remote(), mdo2fid(), mdo2mdd(), mdo_declare_xattr_set(), MLAO_CHECK, mdd_object::mod_obj, mdd_thread_info::mti_lr, thandle_get_sub_by_dt(), and XATTR_NAME_LINK.
Referenced by mdd_declare_create(), mdd_declare_link(), mdd_declare_links_del(), mdd_declare_migrate_create(), mdd_declare_migrate_update_name(), mdd_declare_rename(), and mdd_linkea_update_child_internal().
int mdd_declare_object_create_internal (const struct lu_env * env, struct mdd_object * p, struct mdd_object * c, struct lu_attr * attr, struct thandle * handle, const struct md_op_spec * spec, struct dt_allocation_hint * hint)
Definition at line 342 of file mdd_object.c.
References DFT_INDEX, DFT_REGULAR, dt_object_format::dof_idx, dt_object_format::dof_reg, dt_object_format::dof_type, dt_directory_features, dt_mode_to_dft(), ENTRY, lu_attr::la_mode, md_should_create(), mdd_env_info(), mdo_declare_create_obj(), MDS_OPEN_HAS_EA, mdd_thread_info::mti_dof, md_op_spec::no_create, RETURN, md_op_spec::sp_cr_flags, md_op_spec::sp_feat, and dt_object_format::u.
Referenced by mdd_declare_migrate_create(), and mdd_declare_object_create().
struct mdd_thread_info* mdd_env_info (const struct lu_env * env) [read]
Definition at line 90 of file mdd_object.c.
References LASSERT, lu_env::le_ctx, lu_context_key_get(), lu_env_refill(), and mdd_thread_key.
Referenced by __mdd_index_insert_only(), __mdd_links_add(), mdd_attr_set(), mdd_buf_get(), mdd_buf_get_const(), mdd_changelog_data_store(), mdd_changelog_ns_store(), mdd_changelog_write_header(), mdd_check_acl(), mdd_create(), mdd_create_data(), mdd_create_sanity_check(), mdd_declare_changelog_store(), mdd_declare_create(), mdd_declare_links_add(), mdd_declare_object_create_internal(), mdd_declare_rename(), mdd_declare_unlink(), mdd_fld_lookup(), mdd_get_lov_ea(), mdd_hsm_update_locked(), mdd_is_parent(), mdd_link(), mdd_linkea_update_child_internal(), mdd_links_read(), mdd_links_rename(), mdd_links_write(), mdd_migrate_create(), mdd_migrate_entries(), mdd_migrate_sanity_check(), mdd_migrate_update_name(), mdd_migrate_xattrs(), mdd_object_create_internal(), mdd_orphan_insert_obj(), mdd_parent_fid(), mdd_rename(), mdd_swap_layouts(), mdd_unlink(), mdd_update_linkea_internal(), mdo_declare_index_insert(), orph_declare_index_insert(), orph_index_insert(), orph_index_iterate(), orph_key_fill(), and orph_key_fill_18().
int mdd_finish_unlink (const struct lu_env * env, struct mdd_object * obj, struct md_attr * ma, const struct mdd_object * pobj, const struct lu_name * lname, struct thandle * th)
Definition at line 1453 of file mdd_dir.c.
References __mdd_orphan_add(), CDEBUG, CERROR, D_HA, DEAD_OBJ, DFID, ENTRY, lu_attr::la_mode, lu_attr::la_nlink, LASSERT, md_attr::ma_attr, mdd_links_del(), mdd_mark_orphan_object(), mdd_object_fid(), mdd_write_locked(), mdo2fid(), mdo_destroy(), mdd_object::mod_count, mdd_object::mod_flags, PFID, and RETURN.
Referenced by mdd_rename(), and mdd_unlink().
int mdd_generic_thread_start (struct mdd_generic_thread * thread, int(*)(void *) func, void * data, char * name)
Definition at line 1571 of file mdd_device.c.
References LASSERT, mdd_generic_thread::mgt_abort, mdd_generic_thread::mgt_data, mdd_generic_thread::mgt_finished, mdd_generic_thread::mgt_init, and mdd_generic_thread::mgt_started.
Referenced by mdd_orphan_cleanup().
void mdd_generic_thread_stop (struct mdd_generic_thread * thread)
Definition at line 1592 of file mdd_device.c.
References mdd_generic_thread::mgt_abort, mdd_generic_thread::mgt_finished, and mdd_generic_thread::mgt_init.
Referenced by mdd_device_shutdown().
int mdd_get_lov_ea (const struct lu_env * env, struct mdd_object * obj, struct lu_buf * lmm_buf)
Definition at line 1193 of file mdd_object.c.
References buf, bufsize, ENTRY, EXIT, GOTO, lu_buf::lb_buf, lu_buf::lb_len, lu_buf_alloc(), lu_buf_check_and_alloc(), lu_buf_free(), LU_BUF_NULL, mdd_env_info(), mdo_xattr_get(), mdd_thread_info::mti_big_buf, RETURN, and XATTR_NAME_LOV.
Referenced by mdd_migrate_create(), and mdd_swap_layouts().
static int mdd_is_dead_obj (struct mdd_object * obj) [inline, static]
Definition at line 435 of file mdd_internal.h.
References DEAD_OBJ, and mdd_object::mod_flags.
Referenced by __mdd_lookup(), mdd_attr_get(), mdd_cd_sanity_check(), mdd_create_sanity_check(), mdd_link_sanity_check(), mdd_may_create(), mdd_may_delete(), mdd_may_delete_entry(), mdd_may_unlink(), mdd_open_sanity_check(), mdd_readpage(), mdd_rename(), and mdd_xattr_hsm_replace().
int mdd_is_root (struct mdd_device * mdd, const struct lu_fid * fid)
Definition at line 184 of file mdd_dir.c.
References fid_oid(), and mdd_device::mdd_root_fid.
Referenced by mdd_is_parent().
int mdd_is_subdir (const struct lu_env * env, struct md_object * mo, const struct lu_fid * fid, struct lu_fid * sfid)
Definition at line 259 of file mdd_dir.c.
References ENTRY, fid_zero(), md2mdd_obj(), MDD_ENV_VAR, mdd_is_parent(), mdd_la_get(), mdd_object_type(), mdo2mdd(), and RETURN.
int mdd_la_get (const struct lu_env * env, struct mdd_object * obj, struct lu_attr * la)
Definition at line 65 of file mdd_object.c.
References CERROR, DEAD_OBJ, DFID, lu_attr::la_flags, LA_FLAGS, lu_attr::la_valid, LUSTRE_ORPHAN_FL, mdd_obj_dev_name(), mdd_object_exists(), mdd_object_fid(), mdo_attr_get(), mdd_object::mod_flags, ORPHAN_OBJ, PFID, and unlikely.
Referenced by mdd_attr_get(), mdd_attr_set(), mdd_close(), mdd_create(), mdd_create_data(), mdd_is_subdir(), mdd_link(), mdd_lookup(), mdd_migrate(), mdd_migrate_update_name(), mdd_object_start(), mdd_open(), mdd_permission(), mdd_rename(), mdd_swap_layouts(), mdd_unlink(), mdd_xattr_del(), and mdd_xattr_set().
struct lu_buf* mdd_links_get (const struct lu_env * env, struct mdd_object * mdd_obj) [read]
Read the link EA into a temp buffer.
Uses the name_buf since it is generally large.
Return values:
IS_ERR err
ptr to lu_buf (always mti_big_buf)
Definition at line 1139 of file mdd_dir.c.
References linkea_data::ld_buf, and mdd_links_read().
Referenced by mdd_layout_swap_allowed().
int mdd_links_read (const struct lu_env * env, struct mdd_object * mdd_obj, struct linkea_data * ldata)
Read the link EA into a temp buffer.
Uses the mdd_thread_info::mti_big_buf since it is generally large. A pointer to the buffer is stored in ldata::ld_buf.
Return values:
0 or error
Definition at line 1096 of file mdd_dir.c.
References LASSERT, lu_buf::lb_buf, linkea_data::ld_buf, linkea_init(), lu_buf_check_and_alloc(), lu_buf_free(), mdd_env_info(), mdd_object_exists(), mdo_xattr_get(), and XATTR_NAME_LINK.
Referenced by __mdd_links_add(), __mdd_links_del(), mdd_linkea_update_child_internal(), mdd_links_get(), mdd_migrate_create(), mdd_migrate_sanity_check(), mdd_migrate_update_name(), and mdd_parent_fid().
int mdd_links_rename (const struct lu_env * env, struct mdd_object * mdd_obj, const struct lu_fid * oldpfid, const struct lu_name * oldlname, const struct lu_fid * newpfid, const struct lu_name * newlname, struct thandle * handle, struct linkea_data * ldata, int first, int check)
Definition at line 1008 of file mdd_dir.c.
References CDEBUG, D_ERROR, D_OTHER, DFID, ENTRY, error, EXIT, GOTO, linkea_data::ld_buf, linkea_data::ld_reclen, lu_name::ln_name, lu_name::ln_namelen, lu_buf_free(), mdd_env_info(), mdd_linkea_prepare(), mdd_links_write(), mdd_object_fid(), mdd_thread_info::mti_link_data, and PFID.
Referenced by mdd_links_add(), mdd_links_del(), and mdd_rename().
int mdd_links_write (const struct lu_env * env, struct mdd_object * mdd_obj, struct linkea_data * ldata, struct thandle * handle)
Definition at line 1149 of file mdd_dir.c.
References buf, lu_buf::lb_buf, linkea_data::ld_buf, linkea_data::ld_leh, LE_SKIP_NLINK, link_ea_header::leh_len, lfsck_in_notify(), lfsck_pack_rfa(), LFSCK_TYPE_NAMESPACE, mdd_device::mdd_bottom, mdd_buf_get_const(), mdd_env_info(), mdd_object_remote(), mdd_object_type(), mdo2fid(), mdo2mdd(), mdo_xattr_set(), mdd_object::mod_obj, mdd_thread_info::mti_lr, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_NO_LINKEA, thandle_get_sub_by_dt(), unlikely, and XATTR_NAME_LINK.
Referenced by mdd_linkea_update_child_internal(), mdd_links_rename(), and mdd_migrate_create().
int mdd_local_file_create (const struct lu_env * env, struct mdd_device * mdd, const struct lu_fid * pfid, const char * name, __u32 mode, struct lu_fid * fid)
Definition at line 950 of file mdd_device.c.
References dt_object::do_lu, dt_locate(), ENTRY, EXIT, fid_is_zero(), GOTO, LASSERT, local_file_find_or_create(), local_file_find_or_create_with_fid(), lu_object_fid(), lu_object_put(), lu_object_put_nocache(), mdd_device::mdd_bottom, mdd_device::mdd_los, RETURN, and unlikely.
Referenced by mdd_dot_lustre_setup(), mdd_lpf_setup(), mdd_obf_setup(), mdd_prepare(), and orph_index_init().
int mdd_lookup (const struct lu_env * env, struct md_object * pobj, const struct lu_name * lname, struct lu_fid * fid, struct md_op_spec * spec)
Definition at line 110 of file mdd_dir.c.
References __mdd_lookup(), ENTRY, md2mdd_obj(), MDD_ENV_VAR, mdd_la_get(), RETURN, and md_op_spec::sp_permitted.
Referenced by mdd_update_linkea_internal().
int mdd_may_create (const struct lu_env * env, struct mdd_object * pobj, const struct lu_attr * pattr, struct mdd_object * cobj, bool check_perm)
Check whether it may create the cobj under the pobj.
Parameters:
[in] env execution environment
[in] pobj the parent directory
[in] pattr the attribute of the parent directory
[in] cobj the child to be created
[in] check_perm if check WRITE|EXEC permission for parent
Return values:
= 0 create the child under this dir is allowed
negative errno create the child under this dir is not allowed
Definition at line 379 of file mdd_dir.c.
References ENTRY, mdd_is_dead_obj(), mdd_object_exists(), mdd_permission_internal_locked(), MOR_TGT_PARENT, and RETURN.
Referenced by mdd_create_sanity_check(), mdd_link_sanity_check(), and mdd_rename_sanity_check().
int mdd_may_delete (const struct lu_env * env, struct mdd_object * tpobj, const struct lu_attr * tpattr, struct mdd_object * tobj, const struct lu_attr * tattr, const struct lu_attr * cattr, int check_perm, int check_empty)
Definition at line 485 of file mdd_dir.c.
References ENTRY, lu_attr::la_flags, lu_attr::la_mode, LASSERT, lu_fid_eq(), LUSTRE_APPEND_FL, LUSTRE_IMMUTABLE_FL, mdd_dir_is_empty(), mdd_is_dead_obj(), mdd_is_sticky(), mdd_may_delete_entry(), mdd_object_exists(), mdd_device::mdd_root_fid, mdo2fid(), mdo2mdd(), mdd_object::mod_obj, and RETURN.
Referenced by mdd_fix_attr(), mdd_rename_sanity_check(), and mdd_unlink_sanity_check().
int mdd_may_unlink (const struct lu_env * env, struct mdd_object * pobj, const struct lu_attr * pattr, const struct lu_attr * attr)
Definition at line 402 of file mdd_dir.c.
References ENTRY, lu_attr::la_flags, LUSTRE_APPEND_FL, LUSTRE_IMMUTABLE_FL, mdd_is_dead_obj(), mdd_permission_internal_locked(), MOR_TGT_PARENT, and RETURN.
static struct mdd_device* mdd_obj2mdd_dev (struct mdd_object * obj) [static, read]
Definition at line 420 of file mdd_internal.h.
References mdo2mdd(), and mdd_object::mod_obj.
Referenced by __mdd_may_link(), mdd_fix_attr(), and mdd_link_sanity_check().
static const char* mdd_obj_dev_name (const struct mdd_object * obj) [inline, static]
Definition at line 460 of file mdd_internal.h.
References lu_object::lo_dev, lu_dev_name(), md_object::mo_lu, and mdd_object::mod_obj.
Referenced by mdd_la_get(), mdd_object_sync(), mdd_readlink(), mdd_readpage(), mdd_swap_layouts(), and mdd_xattr_get().
struct lu_object* mdd_object_alloc (const struct lu_env * env, const struct lu_object_header * hdr, struct lu_device * d) [read]
Definition at line 121 of file mdd_object.c.
References lu_object::lo_ops, lu_object_init(), mdd2lu_obj(), mdd_dir_ops, mdd_lu_obj_ops, mdd_obj_ops, mdd_object_kmem, md_object::mo_dir_ops, md_object::mo_ops, mdd_object::mod_count, mdd_object::mod_obj, and OBD_SLAB_ALLOC_PTR_GFP.
static struct dt_object* mdd_object_child (struct mdd_object * o) [static, read]
Definition at line 409 of file mdd_internal.h.
References dt_object::do_lu, lu_object_next(), and mdd2lu_obj().
Referenced by __mdd_index_delete_only(), __mdd_index_insert_only(), __mdd_lookup(), mdd_create_data(), mdd_declare_migrate_create(), mdd_declare_object_create(), mdd_dir_is_empty(), mdd_migrate_entries(), mdd_object_create(), mdd_object_lock(), mdd_object_make_hint(), mdd_object_sync(), mdd_object_unlock(), mdd_read_lock(), mdd_read_unlock(), mdd_readlink(), mdd_readpage(), mdd_readpage_sanity_check(), mdd_write_lock(), mdd_write_locked(), mdd_write_unlock(), mdo_attr_get(), mdo_attr_set(), mdo_create_obj(), mdo_declare_attr_set(), mdo_declare_create_obj(), mdo_declare_destroy(), mdo_declare_index_delete(), mdo_declare_index_insert(), mdo_declare_ref_add(), mdo_declare_ref_del(), mdo_declare_xattr_del(), mdo_declare_xattr_set(), mdo_destroy(), mdo_ref_add(), mdo_ref_del(), mdo_xattr_del(), mdo_xattr_get(), mdo_xattr_list(), mdo_xattr_set(), and orph_index_insert().
int mdd_object_create_internal (const struct lu_env * env, struct mdd_object * p, struct mdd_object * c, struct lu_attr * attr, struct thandle * handle, const struct md_op_spec * spec, struct dt_allocation_hint * hint)
Definition at line 377 of file mdd_object.c.
References ENTRY, LASSERT, mdd_env_info(), mdd_object_exists(), mdo_create_obj(), mdd_thread_info::mti_dof, and RETURN.
Referenced by mdd_object_create().
static int mdd_object_exists (struct mdd_object * obj) [inline, static]
Definition at line 440 of file mdd_internal.h.
References lu_object_exists, and mdd2lu_obj().
Referenced by __mdd_lookup(), mdd_declare_rename(), mdd_is_parent(), mdd_la_get(), mdd_link_sanity_check(), mdd_links_read(), mdd_may_create(), mdd_may_delete(), mdd_may_delete_entry(), mdd_migrate(), mdd_object_create_internal(), mdd_object_sync(), mdd_readlink(), mdd_readpage(), mdd_rename(), mdd_unlink(), mdd_update_linkea_internal(), mdd_xattr_get(), mdo_attr_set(), mdo_ref_add(), mdo_ref_del(), mdo_xattr_del(), mdo_xattr_list(), mdo_xattr_set(), and obf_lookup().
static struct lu_fid* mdd_object_fid (struct mdd_object * obj) [static, read]
Definition at line 450 of file mdd_internal.h.
References lu_object_fid(), and mdd2lu_obj().
Referenced by mdd_close(), mdd_create(), mdd_finish_unlink(), mdd_la_get(), mdd_linkea_update_child_internal(), mdd_links_rename(), mdd_lpf_setup(), mdd_migrate(), mdd_migrate_create(), mdd_migrate_entries(), mdd_migrate_sanity_check(), mdd_migrate_update_name(), mdd_obf_setup(), mdd_object_make_hint(), mdd_object_sync(), mdd_readlink(), mdd_readpage(), mdd_rename(), mdd_update_linkea_internal(), mdd_xattr_get(), and mdd_xattr_list().
struct mdd_object* mdd_object_find (const struct lu_env * env, struct mdd_device * d, const struct lu_fid * f) [read]
Definition at line 202 of file mdd_object.c.
References md2mdd_obj(), md_object_find_slice(), and mdd_device::mdd_md_dev.
Referenced by mdd_is_parent(), mdd_migrate_entries(), mdd_rename(), mdd_update_linkea_internal(), obf_lookup(), and orph_key_test_and_del().
static void mdd_object_get (struct mdd_object * o) [inline, static]
Definition at line 321 of file mdd_internal.h.
References lu_object_get(), md_object::mo_lu, and mdd_object::mod_obj.
void mdd_object_make_hint (const struct lu_env * env, struct mdd_object * parent, struct mdd_object * child, const struct lu_attr * attr, const struct md_op_spec * spec, struct dt_allocation_hint * hint)
Definition at line 1571 of file mdd_object.c.
References CDEBUG, D_INFO, dt_allocation_hint::dah_eadata, dt_allocation_hint::dah_eadata_len, DFID, dt_object_operations::do_ah_init, dt_object::do_ops, lu_attr::la_mode, mdd_object_child(), mdd_object_fid(), MDS_OPEN_HAS_EA, PFID, md_op_spec::sp_cr_flags, md_op_spec::sp_ea, md_op_spec::u, and unlikely.
Referenced by mdd_create(), mdd_create_data(), and mdd_migrate_create().
static void mdd_object_put (const struct lu_env * env, struct mdd_object * o) [inline, static]
Definition at line 326 of file mdd_internal.h.
References lu_object_put(), md_object::mo_lu, and mdd_object::mod_obj.
Referenced by mdd_dot_lustre_cleanup(), mdd_is_parent(), mdd_migrate_entries(), mdd_rename(), mdd_update_linkea_internal(), obf_lookup(), and orph_key_test_and_del().
static int mdd_object_remote (struct mdd_object * obj) [inline, static]
Definition at line 445 of file mdd_internal.h.
References lu_object_remote, and mdd2lu_obj().
Referenced by __mdd_lookup(), mdd_create(), mdd_declare_links_add(), and mdd_links_write().
static umode_t mdd_object_type (const struct mdd_object * obj) [inline, static]
Definition at line 430 of file mdd_internal.h.
References lu_object_attr(), md_object::mo_lu, and mdd_object::mod_obj.
Referenced by __mdd_lookup(), mdd_declare_finish_unlink(), mdd_declare_link(), mdd_declare_links_del(), mdd_declare_migrate_update_name(), mdd_declare_rename(), mdd_is_subdir(), mdd_layout_swap_allowed(), mdd_link(), mdd_link_sanity_check(), mdd_links_write(), mdd_mark_orphan_object(), mdd_migrate_entries(), mdd_migrate_update_name(), mdd_orphan_insert_obj(), mdd_parent_fid(), mdd_readpage_sanity_check(), mdd_rename(), mdd_unlink(), mdd_update_linkea_internal(), orph_declare_index_delete(), orph_index_delete(), orph_index_insert(), and orphan_object_destroy().
int mdd_orphan_cleanup (const struct lu_env * env, struct mdd_device * d)
Iterate orphan index to cleanup orphan objects after recovery is done.
Parameters:
d mdd device in recovery.
Definition at line 595 of file mdd_orphans.c.
References __mdd_orphan_cleanup(), CERROR, mdd2obd_dev(), mdd_generic_thread_start(), mdd_device::mdd_orph_cleanup_thread, MTI_NAME_MAXLEN, name, OBD_ALLOC, and OBD_FREE.
Referenced by mdd_recovery_complete().
int mdd_permission (const struct lu_env * env, struct md_object * pobj, struct md_object * cobj, struct md_attr * ma, int mask)
Definition at line 307 of file mdd_permission.c.
References accmode(), CFS_CAP_FOWNER, ENTRY, lu_attr::la_uid, LASSERT, likely, lu_ucred_assert(), MAY_RGETFACL, md2mdd_obj(), md_capable(), MDD_ENV_VAR, mdd_la_get(), mdd_permission_internal_locked(), MDS_OPEN_CROSS, MOR_TGT_CHILD, RETURN, lu_ucred::uc_fsuid, and unlikely.
static int mdd_permission_internal (const struct lu_env * env, struct mdd_object * obj, const struct lu_attr * la, int mask) [inline, static]
Definition at line 467 of file mdd_internal.h.
References __mdd_permission_internal().
Referenced by mdd_fix_attr(), and mdd_open_sanity_check().
static int mdd_permission_internal_locked (const struct lu_env * env, struct mdd_object * obj, const struct lu_attr * la, int mask, enum mdd_object_role role) [inline, static]
Definition at line 474 of file mdd_internal.h.
References __mdd_permission_internal().
Referenced by __mdd_lookup(), mdd_may_create(), mdd_may_delete_entry(), mdd_may_unlink(), and mdd_permission().
void mdd_procfs_fini (struct mdd_device * mdd)
Definition at line 396 of file mdd_lproc.c.
References lprocfs_remove(), and mdd_device::mdd_proc_entry.
Referenced by mdd_device_fini(), and mdd_procfs_init().
int mdd_procfs_init (struct mdd_device * mdd, const char * name)
Definition at line 362 of file mdd_lproc.c.
References CERROR, class_search_type(), ENTRY, EXIT, GOTO, LASSERT, lprocfs_register(), LUSTRE_MDD_NAME, mdd2obd_dev(), mdd_device::mdd_proc_entry, mdd_procfs_fini(), obd_device::obd_vars, and obd_type::typ_procroot.
Referenced by mdd_init0().
void mdd_read_lock (const struct lu_env * env, struct mdd_object * obj, enum mdd_object_role role)
Definition at line 57 of file mdd_lock.c.
References dt_read_lock(), and mdd_object_child().
Referenced by __mdd_permission_internal(), mdd_acl_init(), mdd_declare_attr_set(), mdd_migrate(), mdd_readlink(), mdd_readpage(), mdd_xattr_get(), and mdd_xattr_list().
void mdd_read_unlock (const struct lu_env * env, struct mdd_object * obj)
Definition at line 72 of file mdd_lock.c.
References dt_read_unlock(), and mdd_object_child().
Referenced by __mdd_permission_internal(), mdd_acl_init(), mdd_declare_attr_set(), mdd_migrate(), mdd_readlink(), mdd_readpage(), mdd_xattr_get(), and mdd_xattr_list().
int mdd_readlink (const struct lu_env * env, struct md_object * obj, struct lu_buf * buf)
Definition at line 271 of file mdd_object.c.
References CERROR, dt_body_operations::dbo_read, DFID, dt_object::do_body_ops, dt_read(), ENTRY, LASSERT, md2mdd_obj(), mdd_obj_dev_name(), mdd_object_child(), mdd_object_exists(), mdd_object_fid(), mdd_read_lock(), mdd_read_unlock(), MOR_TGT_CHILD, PFID, and RETURN.
Referenced by mdd_migrate_create().
int mdd_readpage (const struct lu_env * env, struct md_object * obj, const struct lu_rdpg * rdpg)
Definition at line 1958 of file mdd_object.c.
References CDEBUG, CERROR, cpu_to_le32, cpu_to_le64, D_INODE, DFID, dt_index_walk(), ENTRY, GOTO, LASSERT, LDF_EMPTY, lu_dirpage::ldp_flags, lu_dirpage::ldp_hash_end, lu_dirpage::ldp_hash_start, LU_PAGE_SIZE, md2mdd_obj(), mdd_dir_page_build(), mdd_is_dead_obj(), mdd_obj_dev_name(), mdd_object_child(), mdd_object_exists(), mdd_object_fid(), mdd_read_lock(), mdd_read_unlock(), mdd_readpage_sanity_check(), MDS_DIR_END_OFF, min_t, MOR_TGT_CHILD, PFID, lu_rdpg::rp_count, lu_rdpg::rp_hash, and lu_rdpg::rp_pages.
static struct seq_server_site* mdd_seq_site (struct mdd_device * mdd) [static, read]
Definition at line 455 of file mdd_internal.h.
References lu_site::ld_seq_site, lu_device::ld_site, and mdd2lu_dev().
Referenced by mdd_migrate_create(), and mdd_prepare().
struct thandle* mdd_trans_create (const struct lu_env * env, struct mdd_device * mdd) [read]
Definition at line 51 of file mdd_trans.c.
References dt_device_operations::dt_trans_create, mdd_device::mdd_child, and mdd_child_ops().
Referenced by mdd_attr_set(), mdd_changelog(), mdd_close(), mdd_create(), mdd_create_data(), mdd_index_delete(), mdd_link(), mdd_migrate_create(), mdd_migrate_entries(), mdd_migrate_update_name(), mdd_migrate_xattrs(), mdd_rename(), mdd_swap_layouts(), mdd_unlink(), mdd_xattr_del(), mdd_xattr_set(), and orphan_object_destroy().
int mdd_trans_start (const struct lu_env * env, struct mdd_device * mdd, struct thandle * th)
Definition at line 57 of file mdd_trans.c.
References dt_device_operations::dt_trans_start, mdd_device::mdd_child, and mdd_child_ops().
Referenced by mdd_attr_set(), mdd_changelog(), mdd_close(), mdd_create(), mdd_create_data(), mdd_index_delete(), mdd_link(), mdd_migrate_create(), mdd_migrate_entries(), mdd_migrate_update_name(), mdd_migrate_xattrs(), mdd_rename(), mdd_swap_layouts(), mdd_unlink(), mdd_xattr_del(), mdd_xattr_set(), and orphan_object_destroy().
int mdd_trans_stop (const struct lu_env * env, struct mdd_device * mdd, int rc, struct thandle * handle)
Definition at line 63 of file mdd_trans.c.
References dt_device_operations::dt_trans_stop, mdd_device::mdd_child, mdd_child_ops(), and thandle::th_result.
Referenced by mdd_attr_set(), mdd_changelog(), mdd_close(), mdd_create(), mdd_create_data(), mdd_index_delete(), mdd_link(), mdd_migrate_create(), mdd_migrate_entries(), mdd_migrate_update_name(), mdd_migrate_xattrs(), mdd_rename(), mdd_swap_layouts(), mdd_unlink(), mdd_xattr_del(), mdd_xattr_set(), and orphan_object_destroy().
int mdd_unlink_sanity_check (const struct lu_env * env, struct mdd_object * pobj, const struct lu_attr * pattr, struct mdd_object * cobj, const struct lu_attr * cattr)
Definition at line 1503 of file mdd_dir.c.
References ENTRY, mdd_may_delete(), and RETURN.
Referenced by mdd_unlink().
int mdd_update_time (const struct lu_env * env, struct mdd_object * obj, const struct lu_attr * oattr, struct lu_attr * attr, struct thandle * handle)
Definition at line 409 of file mdd_object.c.
References ENTRY, lu_attr::la_ctime, LA_CTIME, LA_MTIME, lu_attr::la_valid, LASSERT, mdd_attr_set_internal(), and RETURN.
Referenced by mdd_create(), mdd_link(), mdd_rename(), and mdd_unlink().
void mdd_write_lock (const struct lu_env * env, struct mdd_object * obj, enum mdd_object_role role)
Definition at line 49 of file mdd_lock.c.
References dt_write_lock(), and mdd_object_child().
Referenced by __mdd_index_delete(), __mdd_index_insert(), mdd_attr_set(), mdd_close(), mdd_create(), mdd_link(), mdd_migrate_entries(), mdd_migrate_update_name(), mdd_object_create(), mdd_open(), mdd_rename(), mdd_swap_layouts(), mdd_unlink(), mdd_update_linkea_internal(), mdd_xattr_del(), mdd_xattr_set(), orph_key_test_and_del(), and orphan_object_destroy().
int mdd_write_locked (const struct lu_env * env, struct mdd_object * obj)
Definition at line 79 of file mdd_lock.c.
References dt_write_locked(), and mdd_object_child().
Referenced by mdd_finish_unlink(), orph_index_delete(), and orph_index_insert().
void mdd_write_unlock (const struct lu_env * env, struct mdd_object * obj)
Definition at line 65 of file mdd_lock.c.
References dt_write_unlock(), and mdd_object_child().
Referenced by __mdd_index_delete(), __mdd_index_insert(), mdd_attr_set(), mdd_close(), mdd_create(), mdd_link(), mdd_migrate_entries(), mdd_migrate_update_name(), mdd_object_create(), mdd_open(), mdd_rename(), mdd_swap_layouts(), mdd_unlink(), mdd_update_linkea_internal(), mdd_xattr_del(), mdd_xattr_set(), orph_key_test_and_del(), and orphan_object_destroy().
static struct lu_fid* mdo2fid (const struct mdd_object * obj) [static, read]
Definition at line 425 of file mdd_internal.h.
References lu_object_fid(), md_object::mo_lu, and mdd_object::mod_obj.
Referenced by __mdd_lookup(), mdd_attr_set(), mdd_changelog_data_store(), mdd_changelog_ns_store(), mdd_create(), mdd_declare_create(), mdd_declare_link(), mdd_declare_links_add(), mdd_declare_migrate_update_name(), mdd_declare_object_initialize(), mdd_declare_rename(), mdd_finish_unlink(), mdd_is_parent(), mdd_layout_swap_allowed(), mdd_link(), mdd_links_write(), mdd_may_delete(), mdd_migrate_update_name(), mdd_object_create(), mdd_object_initialize(), mdd_orphan_insert_obj(), mdd_rename(), mdd_rename_order(), mdd_swap_layouts(), mdd_unlink(), orph_declare_index_delete(), orph_declare_index_insert(), and orph_index_delete().
static struct mdd_device* mdo2mdd (struct md_object * mdo) [static, read]
Definition at line 388 of file mdd_internal.h.
References lu_object::lo_dev, lu2mdd_dev(), and md_object::mo_lu.
Referenced by __mdd_lookup(), mdd_attr_set(), mdd_attr_set_changelog(), mdd_changelog(), mdd_close(), mdd_create(), mdd_create_data(), mdd_create_sanity_check(), mdd_declare_links_add(), mdd_declare_migrate_update_name(), mdd_hsm_update_locked(), mdd_index_delete(), mdd_is_subdir(), mdd_link(), mdd_linkea_update_child_internal(), mdd_links_write(), mdd_may_delete(), mdd_migrate(), mdd_migrate_create(), mdd_migrate_entries(), mdd_migrate_sanity_check(), mdd_migrate_update_name(), mdd_migrate_xattrs(), mdd_obj2mdd_dev(), mdd_rename(), mdd_swap_layouts(), mdd_unlink(), mdd_update_linkea_internal(), mdd_xattr_del(), mdd_xattr_hsm_replace(), mdd_xattr_set(), obf_lookup(), orph_declare_index_delete(), orph_declare_index_insert(), orph_index_delete(), orph_index_insert(), and orphan_object_destroy().
static int mdo_attr_get (const struct lu_env * env, struct mdd_object * obj, struct lu_attr * la) [inline, static]
Definition at line 484 of file mdd_internal.h.
References dt_attr_get(), and mdd_object_child().
Referenced by mdd_la_get().
static int mdo_attr_set (const struct lu_env * env, struct mdd_object * obj, const struct lu_attr * la, struct thandle * handle) [inline, static]
Definition at line 500 of file mdd_internal.h.
References dt_attr_set(), mdd_object_child(), and mdd_object_exists().
Referenced by mdd_attr_set_internal(), mdd_mark_orphan_object(), mdd_migrate_create(), and mdd_migrate_update_name().
static int mdo_create_obj (const struct lu_env * env, struct mdd_object * o, struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof, struct thandle * handle) [inline, static]
Definition at line 663 of file mdd_internal.h.
References dt_create(), and mdd_object_child().
Referenced by mdd_object_create_internal().
static int mdo_declare_attr_set (const struct lu_env * env, struct mdd_object * obj, const struct lu_attr * la, struct thandle * handle) [inline, static]
Definition at line 491 of file mdd_internal.h.
References dt_declare_attr_set(), and mdd_object_child().
Referenced by mdd_declare_attr_set(), mdd_declare_create(), mdd_declare_link(), mdd_declare_migrate_create(), mdd_declare_migrate_update_name(), mdd_declare_object_create(), mdd_declare_object_initialize(), mdd_declare_rename(), mdd_declare_unlink(), and mdd_mark_orphan_object().
static int mdo_declare_create_obj (const struct lu_env * env, struct mdd_object * o, struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof, struct thandle * handle) [inline, static]
Definition at line 652 of file mdd_internal.h.
References dt_declare_create(), and mdd_object_child().
Referenced by mdd_declare_object_create_internal().
static int mdo_declare_destroy (const struct lu_env * env, struct mdd_object * o, struct thandle * handle) [inline, static]
Definition at line 674 of file mdd_internal.h.
References dt_declare_destroy(), and mdd_object_child().
Referenced by mdd_declare_close(), mdd_declare_finish_unlink(), and orphan_object_destroy().
static int mdo_declare_index_delete (const struct lu_env * env, struct mdd_object * obj, const char * name, struct thandle * handle) [inline, static]
Definition at line 601 of file mdd_internal.h.
References dt_declare_delete(), dt_key, dt_try_as_dir(), and mdd_object_child().
Referenced by mdd_declare_migrate_update_name(), mdd_declare_rename(), mdd_declare_unlink(), mdd_index_delete(), mdd_migrate_entries(), mdd_update_linkea_internal(), and orph_declare_index_insert().
static int mdo_declare_index_insert (const struct lu_env * env, struct mdd_object * obj, const struct lu_fid * fid, __u32 type, const char * name, struct thandle * handle) [inline, static]
Definition at line 575 of file mdd_internal.h.
References dt_declare_insert(), dt_key, dt_try_as_dir(), mdd_env_info(), mdd_object_child(), mdd_thread_info::mti_dt_rec, dt_insert_rec::rec_fid, and dt_insert_rec::rec_type.
Referenced by mdd_declare_create(), mdd_declare_link(), mdd_declare_migrate_update_name(), mdd_declare_object_initialize(), mdd_declare_rename(), mdd_migrate_entries(), mdd_update_linkea_internal(), and orph_declare_index_insert().
static int mdo_declare_ref_add (const struct lu_env * env, struct mdd_object * obj, struct thandle * handle) [inline, static]
Definition at line 613 of file mdd_internal.h.
References dt_declare_ref_add(), and mdd_object_child().
Referenced by mdd_declare_create(), mdd_declare_link(), mdd_declare_migrate_update_name(), mdd_declare_object_initialize(), mdd_declare_rename(), mdd_migrate_entries(), mdd_update_linkea_internal(), and orph_declare_index_insert().
static int mdo_declare_ref_del (const struct lu_env * env, struct mdd_object * obj, struct thandle * handle) [inline, static]
Definition at line 632 of file mdd_internal.h.
References dt_declare_ref_del(), and mdd_object_child().
Referenced by mdd_declare_migrate_update_name(), mdd_declare_rename(), mdd_declare_unlink(), mdd_index_delete(), mdd_migrate_entries(), mdd_update_linkea_internal(), and orph_declare_index_delete().
static int mdo_declare_xattr_del (const struct lu_env * env, struct mdd_object * obj, const char * name, struct thandle * handle) [inline, static]
Definition at line 542 of file mdd_internal.h.
References dt_declare_xattr_del(), and mdd_object_child().
Referenced by mdd_declare_migrate_update_name(), and mdd_declare_xattr_del().
static int mdo_declare_xattr_set (const struct lu_env * env, struct mdd_object * obj, const struct lu_buf * buf, const char * name, int fl, struct thandle * handle) [inline, static]
Definition at line 520 of file mdd_internal.h.
References dt_declare_xattr_set(), and mdd_object_child().
Referenced by mdd_declare_attr_set(), mdd_declare_links_add(), mdd_declare_migrate_create(), mdd_declare_migrate_update_name(), mdd_declare_object_create(), mdd_declare_xattr_set(), and mdd_migrate_xattrs().
static int mdo_destroy (const struct lu_env * env, struct mdd_object * o, struct thandle * handle) [inline, static]
Definition at line 682 of file mdd_internal.h.
References dt_destroy(), and mdd_object_child().
Referenced by mdd_close(), mdd_create(), mdd_finish_unlink(), mdd_object_create(), and orphan_object_destroy().
static int mdo_ref_add (const struct lu_env * env, struct mdd_object * obj, struct thandle * handle) [inline, static]
Definition at line 621 of file mdd_internal.h.
References dt_ref_add(), mdd_object_child(), and mdd_object_exists().
Referenced by __mdd_index_insert(), mdd_link(), mdd_object_initialize(), mdd_rename(), mdd_update_linkea_internal(), and orph_index_insert().
static int mdo_ref_del (const struct lu_env * env, struct mdd_object * obj, struct thandle * handle) [inline, static]
Definition at line 640 of file mdd_internal.h.
References dt_ref_del(), mdd_object_child(), and mdd_object_exists().
Referenced by __mdd_index_delete(), mdd_create(), mdd_link(), mdd_migrate_update_name(), mdd_object_create(), mdd_object_initialize(), mdd_rename(), mdd_unlink(), mdd_update_linkea_internal(), orph_index_delete(), and orphan_object_destroy().
static int mdo_xattr_del (const struct lu_env * env, struct mdd_object * obj, const char * name, struct thandle * handle) [inline, static]
Definition at line 551 of file mdd_internal.h.
References dt_xattr_del(), mdd_object_child(), and mdd_object_exists().
Referenced by mdd_migrate_update_name(), mdd_swap_layouts(), and mdd_xattr_del().
static int mdo_xattr_get (const struct lu_env * env, struct mdd_object * obj, struct lu_buf * buf, const char * name) [inline, static]
Definition at line 513 of file mdd_internal.h.
References dt_xattr_get(), and mdd_object_child().
Referenced by mdd_acl_init(), mdd_check_acl(), mdd_declare_attr_set(), mdd_get_lov_ea(), mdd_hsm_archive_exists(), mdd_hsm_update_locked(), mdd_links_read(), mdd_migrate_sanity_check(), mdd_migrate_xattrs(), mdd_swap_layouts(), and mdd_xattr_get().
static int mdo_xattr_list (const struct lu_env * env, struct mdd_object * obj, struct lu_buf * buf) [inline, static]
Definition at line 563 of file mdd_internal.h.
References dt_xattr_list(), mdd_object_child(), and mdd_object_exists().
Referenced by mdd_migrate_xattrs(), and mdd_xattr_list().
static int mdo_xattr_set (const struct lu_env * env, struct mdd_object * obj, const struct lu_buf * buf, const char * name, int fl, struct thandle * handle) [inline, static]
Definition at line 530 of file mdd_internal.h.
References dt_xattr_set(), mdd_object_child(), and mdd_object_exists().
Referenced by mdd_links_write(), mdd_migrate_create(), mdd_migrate_update_name(), mdd_migrate_xattrs(), mdd_object_create(), mdd_swap_layouts(), mdd_xattr_hsm_replace(), and mdd_xattr_set().
int orph_declare_index_delete (const struct lu_env * , struct mdd_object * , struct thandle *)
Definition at line 245 of file mdd_orphans.c.
References dt_declare_delete(), dt_declare_ref_del(), dt_key, mdd_object_type(), mdd_device::mdd_orphans, mdo2fid(), mdo2mdd(), mdo_declare_ref_del(), mdd_object::mod_obj, orph_key_fill(), and ORPH_OP_UNLINK.
Referenced by mdd_declare_close(), and orphan_object_destroy().
int orph_declare_index_insert (const struct lu_env * , struct mdd_object * , umode_t mode, struct thandle *)
Definition at line 152 of file mdd_orphans.c.
References dt_object::do_lu, dotdot, dt_declare_insert(), dt_declare_ref_add(), dt_key, lu_object_fid(), mdd_env_info(), mdd_device::mdd_orphans, mdo2fid(), mdo2mdd(), mdo_declare_index_delete(), mdo_declare_index_insert(), mdo_declare_ref_add(), mdd_object::mod_obj, mdd_thread_info::mti_dt_rec, orph_key_fill(), ORPH_OP_UNLINK, dt_insert_rec::rec_fid, and dt_insert_rec::rec_type.
Referenced by mdd_declare_create(), and mdd_declare_finish_unlink().
void orph_index_fini (const struct lu_env * env, struct mdd_device * mdd)
Definition at line 553 of file mdd_orphans.c.
References dt_object::do_lu, ENTRY, EXIT, lu_object_put(), and mdd_device::mdd_orphans.
Referenced by mdd_device_shutdown(), and mdd_prepare().
int orph_index_init (const struct lu_env * env, struct mdd_device * mdd)
open the PENDING directory for device mdd
The PENDING directory persistently tracks files and directories that were unlinked from the namespace (nlink == 0) but are still held open by clients. Those inodes shouldn't be deleted if the MDS crashes, because the clients would not be able to recover and reopen those files. Instead, these inodes are linked into the PENDING directory on disk, and only deleted if all clients close them, or the MDS finishes client recovery without any client reopening them (i.e. former clients didn't join recovery).
Parameters:
d mdd device being started.
Return values:
0 success
-ve index operation error.
Definition at line 523 of file mdd_orphans.c.
References CERROR, dt_object::do_lu, dt_locate(), dt_try_as_dir(), ENTRY, fid_zero(), LASSERT, lu_object_exists, lu_object_put(), mdd2obd_dev(), mdd_device::mdd_child, mdd_local_file_create(), mdd_device::mdd_local_root_fid, mdd_device::mdd_orphans, orph_index_name, and RETURN.
Referenced by mdd_prepare().
Variable Documentation
struct md_dir_operations mdd_dir_ops
Definition at line 4311 of file mdd_dir.c.
Referenced by mdd_object_alloc().
struct lu_device_operations mdd_lu_ops
Definition at line 1082 of file mdd_device.c.
Referenced by lu_device_is_mdd(), and mdd_init0().
struct md_object_operations mdd_obj_ops
Definition at line 2062 of file mdd_object.c.
Referenced by mdd_object_alloc().
struct kmem_cache* mdd_object_kmem
Definition at line 65 of file mdd_device.c.
Referenced by mdd_object_alloc(), and mdd_object_free().
struct lu_context_key mdd_thread_key
Referenced by mdd_env_info().
const char orph_index_name[]
Definition at line 53 of file mdd_orphans.c.
Referenced by orph_index_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.