Lustre: lustre/mdd/mdd_lproc.c File Reference
lustre/mdd/mdd_lproc.c File Reference
#include <obd.h>
#include <obd_class.h>
#include <obd_support.h>
#include <lprocfs_status.h>
#include <libcfs/libcfs_string.h>
#include "mdd_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_MDS
Functions
static ssize_t mdd_atime_diff_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
static int mdd_atime_diff_seq_show (struct seq_file *m, void *data)
LPROC_SEQ_FOPS (mdd_atime_diff)
static int mdd_changelog_mask_seq_show (struct seq_file *m, void *data)
static ssize_t mdd_changelog_mask_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
LPROC_SEQ_FOPS (mdd_changelog_mask)
static int lprocfs_changelog_users_cb (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *hdr, void *data)
static int mdd_changelog_users_seq_show (struct seq_file *m, void *data)
LPROC_SEQ_FOPS_RO (mdd_changelog_users)
static int mdd_changelog_size_ctxt (const struct lu_env *env, struct mdd_device *mdd, int index, __u64 *val)
static int mdd_changelog_size_seq_show (struct seq_file *m, void *data)
LPROC_SEQ_FOPS_RO (mdd_changelog_size)
static int mdd_sync_perm_seq_show (struct seq_file *m, void *data)
static ssize_t mdd_sync_perm_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
LPROC_SEQ_FOPS (mdd_sync_perm)
static int mdd_lfsck_speed_limit_seq_show (struct seq_file *m, void *data)
static ssize_t mdd_lfsck_speed_limit_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
LPROC_SEQ_FOPS (mdd_lfsck_speed_limit)
static int mdd_lfsck_async_windows_seq_show (struct seq_file *m, void *data)
static ssize_t mdd_lfsck_async_windows_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
LPROC_SEQ_FOPS (mdd_lfsck_async_windows)
static int mdd_lfsck_namespace_seq_show (struct seq_file *m, void *data)
LPROC_SEQ_FOPS_RO (mdd_lfsck_namespace)
static int mdd_lfsck_layout_seq_show (struct seq_file *m, void *data)
LPROC_SEQ_FOPS_RO (mdd_lfsck_layout)
int mdd_procfs_init (struct mdd_device *mdd, const char *name)
void mdd_procfs_fini (struct mdd_device *mdd)
Variables
static struct lprocfs_vars lprocfs_mdd_obd_vars []
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 43 of file mdd_lproc.c.
Function Documentation
LPROC_SEQ_FOPS (mdd_lfsck_async_windows)
LPROC_SEQ_FOPS (mdd_lfsck_speed_limit)
LPROC_SEQ_FOPS (mdd_sync_perm)
LPROC_SEQ_FOPS (mdd_changelog_mask)
LPROC_SEQ_FOPS (mdd_atime_diff)
LPROC_SEQ_FOPS_RO (mdd_lfsck_layout)
LPROC_SEQ_FOPS_RO (mdd_lfsck_namespace)
LPROC_SEQ_FOPS_RO (mdd_changelog_size)
LPROC_SEQ_FOPS_RO (mdd_changelog_users)
static int lprocfs_changelog_users_cb (const struct lu_env * env, struct llog_handle * llh, struct llog_rec_hdr * hdr, void * data) [static]
Definition at line 129 of file mdd_lproc.c.
References CHANGELOG_USER_PREFIX, llog_changelog_user_rec::cur_endrec, llog_changelog_user_rec::cur_id, LASSERT, llog_handle::lgh_hdr, llog_log_hdr::llh_flags, LLOG_F_IS_PLAIN, and LPU64.
Referenced by mdd_changelog_users_seq_show().
static int mdd_atime_diff_seq_show (struct seq_file * m, void * data) [static]
Definition at line 77 of file mdd_lproc.c.
References mdd_device::mdd_atime_diff.
static ssize_t mdd_atime_diff_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Definition at line 53 of file mdd_lproc.c.
References end, and mdd_device::mdd_atime_diff.
static int mdd_changelog_mask_seq_show (struct seq_file * m, void * data) [static]
Definition at line 87 of file mdd_lproc.c.
References changelog_type2str(), CL_LAST, mdd_changelog::mc_mask, and mdd_device::mdd_cl.
static ssize_t mdd_changelog_mask_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Definition at line 101 of file mdd_lproc.c.
References cfs_str2mask(), CHANGELOG_ALLMASK, CHANGELOG_MINMASK, changelog_type2str(), ENTRY, GOTO, mdd_changelog::mc_mask, mdd_device::mdd_cl, OBD_ALLOC, OBD_FREE, and RETURN.
static int mdd_changelog_size_ctxt (const struct lu_env * env, struct mdd_device * mdd, int index, __u64 * val) [static]
Definition at line 181 of file mdd_lproc.c.
References CERROR, llog_handle::lgh_hdr, llog_log_hdr::llh_flags, llog_cat_size(), llog_ctxt_put(), LLOG_F_IS_CAT, llog_get_context(), llog_ctxt::loc_handle, llog_ctxt::loc_obd, mdd2obd_dev(), and obd_device::obd_name.
Referenced by mdd_changelog_size_seq_show().
static int mdd_changelog_size_seq_show (struct seq_file * m, void * data) [static]
Definition at line 206 of file mdd_lproc.c.
References __u64, LCT_LOCAL, LLOG_CHANGELOG_ORIG_CTXT, LLOG_CHANGELOG_USER_ORIG_CTXT, LPU64, lu_env_fini(), lu_env_init(), and mdd_changelog_size_ctxt().
static int mdd_changelog_users_seq_show (struct seq_file * m, void * data) [static]
Definition at line 145 of file mdd_lproc.c.
References __u64, LASSERT, LCT_LOCAL, llog_handle::lgh_hdr, llog_log_hdr::llh_flags, llog_cat_process(), LLOG_CHANGELOG_USER_ORIG_CTXT, llog_ctxt_put(), LLOG_F_IS_CAT, llog_get_context(), llog_ctxt::loc_handle, lprocfs_changelog_users_cb(), LPU64, lu_env_fini(), lu_env_init(), mdd_changelog::mc_index, mdd_changelog::mc_lock, mdd2obd_dev(), and mdd_device::mdd_cl.
static int mdd_lfsck_async_windows_seq_show (struct seq_file * m, void * data) [static]
Definition at line 290 of file mdd_lproc.c.
References LASSERT, lfsck_get_windows(), and mdd_device::mdd_bottom.
static ssize_t mdd_lfsck_async_windows_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Definition at line 299 of file mdd_lproc.c.
References LASSERT, lfsck_set_windows(), and mdd_device::mdd_bottom.
static int mdd_lfsck_layout_seq_show (struct seq_file * m, void * data) [static]
Definition at line 330 of file mdd_lproc.c.
References LASSERT, lfsck_dump(), LFSCK_TYPE_LAYOUT, and mdd_device::mdd_bottom.
static int mdd_lfsck_namespace_seq_show (struct seq_file * m, void * data) [static]
Definition at line 320 of file mdd_lproc.c.
References LASSERT, lfsck_dump(), LFSCK_TYPE_NAMESPACE, and mdd_device::mdd_bottom.
static int mdd_lfsck_speed_limit_seq_show (struct seq_file * m, void * data) [static]
Definition at line 261 of file mdd_lproc.c.
References LASSERT, lfsck_get_speed(), and mdd_device::mdd_bottom.
static ssize_t mdd_lfsck_speed_limit_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Definition at line 270 of file mdd_lproc.c.
References LASSERT, lfsck_set_speed(), and mdd_device::mdd_bottom.
void mdd_procfs_fini (struct mdd_device * mdd)
Definition at line 396 of file mdd_lproc.c.
References lprocfs_remove(), and mdd_device::mdd_proc_entry.
Referenced by mdd_device_fini(), and mdd_procfs_init().
int mdd_procfs_init (struct mdd_device * mdd, const char * name)
Definition at line 362 of file mdd_lproc.c.
References CERROR, class_search_type(), ENTRY, EXIT, GOTO, LASSERT, lprocfs_register(), LUSTRE_MDD_NAME, mdd2obd_dev(), mdd_device::mdd_proc_entry, mdd_procfs_fini(), obd_device::obd_vars, and obd_type::typ_procroot.
Referenced by mdd_init0().
static int mdd_sync_perm_seq_show (struct seq_file * m, void * data) [static]
Definition at line 232 of file mdd_lproc.c.
References LASSERT, and mdd_device::mdd_sync_permission.
static ssize_t mdd_sync_perm_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Definition at line 242 of file mdd_lproc.c.
References LASSERT, and mdd_device::mdd_sync_permission.
Variable Documentation
struct lprocfs_vars lprocfs_mdd_obd_vars[] [static]
Initial value:
 {
        { .name =       "atime_diff",
          .fops =       &mdd_atime_diff_fops            },
        { .name =       "changelog_mask",
          .fops =       &mdd_changelog_mask_fops        },
        { .name =       "changelog_users",
          .fops =       &mdd_changelog_users_fops       },
        { .name =       "changelog_size",
          .fops =       &mdd_changelog_size_fops        },
        { .name =       "sync_permission",
          .fops =       &mdd_sync_perm_fops             },
        { .name =       "lfsck_speed_limit",
          .fops =       &mdd_lfsck_speed_limit_fops     },
        { .name =       "lfsck_async_windows",
          .fops =       &mdd_lfsck_async_windows_fops   },
        { .name =       "lfsck_namespace",
          .fops =       &mdd_lfsck_namespace_fops       },
        { .name =       "lfsck_layout",
          .fops =       &mdd_lfsck_layout_fops          },
        { NULL }
}
Definition at line 340 of file mdd_lproc.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.