Lustre: lustre/mdd/mdd_orphans.c File Reference
lustre/mdd/mdd_orphans.c File Reference
#include <obd.h>
#include <obd_class.h>
#include <lustre_ver.h>
#include <obd_support.h>
#include <lustre_fid.h>
#include "mdd_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_MDS
#define ORPHAN_FILE_NAME_FORMAT "%016llx:%08x:%08x:%2x"
#define ORPHAN_FILE_NAME_FORMAT_18 "%llx:%08x"
Enumerations
enum { ORPH_OP_UNLINK, ORPH_OP_TRUNCATE }
Functions
static struct dt_key * orph_key_fill (const struct lu_env *env, const struct lu_fid *lf, __u32 op)
static struct dt_key * orph_key_fill_18 (const struct lu_env *env, const struct lu_fid *lf)
static void mdd_orphan_write_lock (const struct lu_env *env, struct mdd_device *mdd)
static void mdd_orphan_write_unlock (const struct lu_env *env, struct mdd_device *mdd)
static int mdd_orphan_insert_obj (const struct lu_env *env, struct mdd_device *mdd, struct mdd_object *obj, __u32 op, struct thandle *th)
static int mdd_orphan_delete_obj (const struct lu_env *env, struct mdd_device *mdd, struct dt_key *key, struct thandle *th)
static int mdd_orphan_ref_add (const struct lu_env *env, struct mdd_device *mdd, struct thandle *th)
static int mdd_orphan_ref_del (const struct lu_env *env, struct mdd_device *mdd, struct thandle *th)
int orph_declare_index_insert (const struct lu_env *env, struct mdd_object *obj, umode_t mode, struct thandle *th)
static int orph_index_insert (const struct lu_env *env, struct mdd_object *obj, __u32 op, struct thandle *th)
int orph_declare_index_delete (const struct lu_env *env, struct mdd_object *obj, struct thandle *th)
static int orph_index_delete (const struct lu_env *env, struct mdd_object *obj, __u32 op, struct thandle *th)
static int orphan_object_destroy (const struct lu_env *env, struct mdd_object *obj, struct dt_key *key)
static int orph_key_test_and_del (const struct lu_env *env, struct mdd_device *mdd, struct lu_fid *lf, struct dt_key *key)
Delete unused orphan with FID lf from PENDING directory.
static int orph_index_iterate (const struct lu_env *env, struct mdd_generic_thread *thread)
delete unreferenced files and directories in the PENDING directory
int orph_index_init (const struct lu_env *env, struct mdd_device *mdd)
open the PENDING directory for device mdd
void orph_index_fini (const struct lu_env *env, struct mdd_device *mdd)
static int __mdd_orphan_cleanup (void *args)
int mdd_orphan_cleanup (const struct lu_env *env, struct mdd_device *d)
Iterate orphan index to cleanup orphan objects after recovery is done.
int __mdd_orphan_add (const struct lu_env *env, struct mdd_object *obj, struct thandle *th)
add an orphan obj to the orphan index.
int __mdd_orphan_del (const struct lu_env *env, struct mdd_object *obj, struct thandle *th)
delete an orphan obj from orphan index.
Variables
const char orph_index_name [] = "PENDING"
static const char dotdot [] = ".."
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 44 of file mdd_orphans.c.
#define ORPHAN_FILE_NAME_FORMAT "%016llx:%08x:%08x:%2x"
Definition at line 61 of file mdd_orphans.c.
Referenced by orph_key_fill().
#define ORPHAN_FILE_NAME_FORMAT_18 "%llx:%08x"
Definition at line 62 of file mdd_orphans.c.
Referenced by orph_key_fill_18().
Enumeration Type Documentation
anonymous enum
Enumerator:
ORPH_OP_UNLINK
ORPH_OP_TRUNCATE
Definition at line 56 of file mdd_orphans.c.
Function Documentation
int __mdd_orphan_add (const struct lu_env * env, struct mdd_object * obj, struct thandle * th)
add an orphan obj to the orphan index.
Parameters:
obj file or directory.
th transaction for index insert.
Precondition:
obj nlink == 0 && obj->mod_count != 0
Return values:
0 success
-ve index operation error.
Definition at line 628 of file mdd_orphans.c.
References orph_index_insert(), and ORPH_OP_UNLINK.
Referenced by mdd_create(), mdd_finish_unlink(), and mdd_migrate_update_name().
static int __mdd_orphan_cleanup (void * args) [static]
Definition at line 563 of file mdd_orphans.c.
References ENTRY, GOTO, LCT_MD_THREAD, lu_env_fini(), lu_env_init(), mdd_generic_thread::mgt_finished, mdd_generic_thread::mgt_started, OBD_ALLOC_PTR, OBD_FREE_PTR, orph_index_iterate(), and thread.
Referenced by mdd_orphan_cleanup().
int __mdd_orphan_del (const struct lu_env * env, struct mdd_object * obj, struct thandle * th)
delete an orphan obj from orphan index.
Parameters:
obj file or directory.
th transaction for index deletion and object destruction.
Precondition:
obj->mod_count == 0 && ORPHAN_OBJ is set for obj.
Return values:
0 success
-ve index operation error.
Definition at line 644 of file mdd_orphans.c.
References orph_index_delete(), and ORPH_OP_UNLINK.
Referenced by mdd_close(), and mdd_create().
int mdd_orphan_cleanup (const struct lu_env * env, struct mdd_device * d)
Iterate orphan index to cleanup orphan objects after recovery is done.
Parameters:
d mdd device in recovery.
Definition at line 595 of file mdd_orphans.c.
References __mdd_orphan_cleanup(), CERROR, mdd2obd_dev(), mdd_generic_thread_start(), mdd_device::mdd_orph_cleanup_thread, MTI_NAME_MAXLEN, name, OBD_ALLOC, and OBD_FREE.
Referenced by mdd_recovery_complete().
static int mdd_orphan_delete_obj (const struct lu_env * env, struct mdd_device * mdd, struct dt_key * key, struct thandle * th) [inline, static]
Definition at line 125 of file mdd_orphans.c.
References dt_delete(), and mdd_device::mdd_orphans.
Referenced by orph_index_delete(), and orphan_object_destroy().
static int mdd_orphan_insert_obj (const struct lu_env * env, struct mdd_device * mdd, struct mdd_object * obj, __u32 op, struct thandle * th) [inline, static]
Definition at line 109 of file mdd_orphans.c.
References dt_insert(), dt_key, mdd_env_info(), mdd_object_type(), mdd_device::mdd_orphans, mdo2fid(), mdd_thread_info::mti_dt_rec, orph_key_fill(), dt_insert_rec::rec_fid, and dt_insert_rec::rec_type.
Referenced by orph_index_insert().
static int mdd_orphan_ref_add (const struct lu_env * env, struct mdd_device * mdd, struct thandle * th) [inline, static]
Definition at line 135 of file mdd_orphans.c.
References dt_ref_add(), and mdd_device::mdd_orphans.
Referenced by orph_index_insert().
static int mdd_orphan_ref_del (const struct lu_env * env, struct mdd_device * mdd, struct thandle * th) [inline, static]
Definition at line 143 of file mdd_orphans.c.
References dt_ref_del(), and mdd_device::mdd_orphans.
Referenced by orph_index_delete(), and orphan_object_destroy().
static void mdd_orphan_write_lock (const struct lu_env * env, struct mdd_device * mdd) [inline, static]
Definition at line 95 of file mdd_orphans.c.
References dt_write_lock(), mdd_device::mdd_orphans, and MOR_TGT_ORPHAN.
Referenced by orph_index_delete(), orph_index_insert(), and orphan_object_destroy().
static void mdd_orphan_write_unlock (const struct lu_env * env, struct mdd_device * mdd) [inline, static]
Definition at line 102 of file mdd_orphans.c.
References dt_write_unlock(), and mdd_device::mdd_orphans.
Referenced by orph_index_delete(), orph_index_insert(), and orphan_object_destroy().
int orph_declare_index_delete (const struct lu_env * env, struct mdd_object * obj, struct thandle * th)
Definition at line 245 of file mdd_orphans.c.
References dt_declare_delete(), dt_declare_ref_del(), dt_key, mdd_object_type(), mdd_device::mdd_orphans, mdo2fid(), mdo2mdd(), mdo_declare_ref_del(), mdd_object::mod_obj, orph_key_fill(), and ORPH_OP_UNLINK.
Referenced by mdd_declare_close(), and orphan_object_destroy().
int orph_declare_index_insert (const struct lu_env * env, struct mdd_object * obj, umode_t mode, struct thandle * th)
Definition at line 152 of file mdd_orphans.c.
References dt_object::do_lu, dotdot, dt_declare_insert(), dt_declare_ref_add(), dt_key, lu_object_fid(), mdd_env_info(), mdd_device::mdd_orphans, mdo2fid(), mdo2mdd(), mdo_declare_index_delete(), mdo_declare_index_insert(), mdo_declare_ref_add(), mdd_object::mod_obj, mdd_thread_info::mti_dt_rec, orph_key_fill(), ORPH_OP_UNLINK, dt_insert_rec::rec_fid, and dt_insert_rec::rec_type.
Referenced by mdd_declare_create(), and mdd_declare_finish_unlink().
static int orph_index_delete (const struct lu_env * env, struct mdd_object * obj, __u32 op, struct thandle * th) [static]
Definition at line 275 of file mdd_orphans.c.
References CERROR, dt_key, ENTRY, LASSERT, mdd_object_type(), mdd_orphan_delete_obj(), mdd_orphan_ref_del(), mdd_orphan_write_lock(), mdd_orphan_write_unlock(), mdd_device::mdd_orphans, mdd_write_locked(), mdo2fid(), mdo2mdd(), mdo_ref_del(), mdd_object::mod_count, mdd_object::mod_flags, mdd_object::mod_obj, orph_key_fill(), orph_key_fill_18(), ORPHAN_OBJ, and RETURN.
Referenced by __mdd_orphan_del().
void orph_index_fini (const struct lu_env * env, struct mdd_device * mdd)
Definition at line 553 of file mdd_orphans.c.
References dt_object::do_lu, ENTRY, EXIT, lu_object_put(), and mdd_device::mdd_orphans.
Referenced by mdd_device_shutdown(), and mdd_prepare().
int orph_index_init (const struct lu_env * env, struct mdd_device * mdd)
open the PENDING directory for device mdd
The PENDING directory persistently tracks files and directories that were unlinked from the namespace (nlink == 0) but are still held open by clients. Those inodes shouldn't be deleted if the MDS crashes, because the clients would not be able to recover and reopen those files. Instead, these inodes are linked into the PENDING directory on disk, and only deleted if all clients close them, or the MDS finishes client recovery without any client reopening them (i.e. former clients didn't join recovery).
Parameters:
d mdd device being started.
Return values:
0 success
-ve index operation error.
Definition at line 523 of file mdd_orphans.c.
References CERROR, dt_object::do_lu, dt_locate(), dt_try_as_dir(), ENTRY, fid_zero(), LASSERT, lu_object_exists, lu_object_put(), mdd2obd_dev(), mdd_device::mdd_child, mdd_local_file_create(), mdd_device::mdd_local_root_fid, mdd_device::mdd_orphans, orph_index_name, and RETURN.
Referenced by mdd_prepare().
static int orph_index_insert (const struct lu_env * env, struct mdd_object * obj, __u32 op, struct thandle * th) [static]
Definition at line 196 of file mdd_orphans.c.
References dt_object::do_lu, dotdot, dt_delete(), dt_insert(), dt_key, dt_try_as_dir(), ENTRY, GOTO, LASSERT, lu_object_fid(), mdd_env_info(), mdd_object_child(), mdd_object_type(), mdd_orphan_insert_obj(), mdd_orphan_ref_add(), mdd_orphan_write_lock(), mdd_orphan_write_unlock(), mdd_device::mdd_orphans, mdd_write_locked(), mdo2mdd(), mdo_ref_add(), mdd_object::mod_flags, mdd_object::mod_obj, mdd_thread_info::mti_dt_rec, ORPHAN_OBJ, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, and RETURN.
Referenced by __mdd_orphan_add().
static int orph_index_iterate (const struct lu_env * env, struct mdd_generic_thread * thread) [static]
delete unreferenced files and directories in the PENDING directory
Files that remain in PENDING after client->MDS recovery has completed have to be referenced (opened) by some client during recovery, or they will be deleted here (for clients that did not complete recovery).
Parameters:
thread info about orphan cleanup thread
Return values:
0 success
-ve error
Definition at line 427 of file mdd_orphans.c.
References __u64, CERROR, DFID, dt_key, ENTRY, fid_is_sane(), fid_le_to_cpu(), GOTO, LUDA_64BITHASH, mdd2obd_dev(), mdd_env_info(), mdd_device::mdd_orphans, mdd_generic_thread::mgt_abort, mdd_generic_thread::mgt_data, mdd_thread_info::mti_ent, orph_key_test_and_del(), and PFID.
Referenced by __mdd_orphan_cleanup().
static struct dt_key* orph_key_fill (const struct lu_env * env, const struct lu_fid * lf, __u32 op) [static, read]
Definition at line 64 of file mdd_orphans.c.
References dt_key, fid_oid(), fid_ver(), LASSERT, mdd_env_info(), mdd_thread_info::mti_key, and ORPHAN_FILE_NAME_FORMAT.
Referenced by mdd_orphan_insert_obj(), orph_declare_index_delete(), orph_declare_index_insert(), and orph_index_delete().
static struct dt_key* orph_key_fill_18 (const struct lu_env * env, const struct lu_fid * lf) [static, read]
Definition at line 80 of file mdd_orphans.c.
References dt_key, fid_oid(), LASSERT, mdd_env_info(), mdd_thread_info::mti_key, and ORPHAN_FILE_NAME_FORMAT_18.
Referenced by orph_index_delete().
static int orph_key_test_and_del (const struct lu_env * env, struct mdd_device * mdd, struct lu_fid * lf, struct dt_key * key) [static]
Delete unused orphan with FID lf from PENDING directory.
Parameters:
mdd MDD device finishing recovery
lf FID of file or directory to delete
key cookie for this entry in index iterator
Return values:
0 success
-ve error
Definition at line 380 of file mdd_orphans.c.
References CDEBUG, CERROR, D_HA, DFID, likely, mdd2obd_dev(), mdd_object_find(), mdd_object_put(), mdd_write_lock(), mdd_write_unlock(), mdd_object::mod_count, mdd_object::mod_flags, MOR_TGT_CHILD, ORPHAN_OBJ, orphan_object_destroy(), and PFID.
Referenced by orph_index_iterate().
static int orphan_object_destroy (const struct lu_env * env, struct mdd_object * obj, struct dt_key * key) [static]
Definition at line 320 of file mdd_orphans.c.
References CERROR, ENTRY, GOTO, likely, mdd_object_type(), mdd_orphan_delete_obj(), mdd_orphan_ref_del(), mdd_orphan_write_lock(), mdd_orphan_write_unlock(), mdd_trans_create(), mdd_trans_start(), mdd_trans_stop(), mdd_write_lock(), mdd_write_unlock(), mdo2mdd(), mdo_declare_destroy(), mdo_destroy(), mdo_ref_del(), mdd_object::mod_count, mdd_object::mod_obj, MOR_TGT_CHILD, orph_declare_index_delete(), RETURN, and stop.
Referenced by orph_key_test_and_del().
Variable Documentation
const char dotdot[] = ".." [static]
Definition at line 54 of file mdd_orphans.c.
const char orph_index_name[] = "PENDING"
Definition at line 53 of file mdd_orphans.c.
Referenced by orph_index_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.