Lustre: lustre/mdd/mdd_dir.c File Reference
lustre/mdd/mdd_dir.c File Reference
#include <obd_class.h>
#include <obd_support.h>
#include <lustre_mds.h>
#include <lustre_fid.h>
#include "mdd_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_MDS
Enumerations
enum rename_order { MDD_RN_SAME, MDD_RN_SRCTGT, MDD_RN_TGTSRC }
Functions
static int mdd_name_check (struct mdd_device *m, const struct lu_name *ln)
static int __mdd_lookup (const struct lu_env *env, struct md_object *pobj, const struct lu_attr *pattr, const struct lu_name *lname, struct lu_fid *fid, int mask)
int mdd_lookup (const struct lu_env *env, struct md_object *pobj, const struct lu_name *lname, struct lu_fid *fid, struct md_op_spec *spec)
static int mdd_parent_fid (const struct lu_env *env, struct mdd_object *obj, const struct lu_attr *attr, struct lu_fid *fid)
Get parent FID of the directory.
int mdd_is_root (struct mdd_device *mdd, const struct lu_fid *fid)
static int mdd_is_parent (const struct lu_env *env, struct mdd_device *mdd, struct mdd_object *p1, const struct lu_attr *attr, const struct lu_fid *lf, struct lu_fid *pf)
int mdd_is_subdir (const struct lu_env *env, struct md_object *mo, const struct lu_fid *fid, struct lu_fid *sfid)
static int mdd_dir_is_empty (const struct lu_env *env, struct mdd_object *dir)
static int __mdd_may_link (const struct lu_env *env, struct mdd_object *obj, const struct lu_attr *la)
Determine if the target object can be hard linked, and right now it only checks if the link count reach the maximum limit.
int mdd_may_create (const struct lu_env *env, struct mdd_object *pobj, const struct lu_attr *pattr, struct mdd_object *cobj, bool check_perm)
Check whether it may create the cobj under the pobj.
int mdd_may_unlink (const struct lu_env *env, struct mdd_object *pobj, const struct lu_attr *pattr, const struct lu_attr *attr)
static int mdd_is_sticky (const struct lu_env *env, struct mdd_object *pobj, const struct lu_attr *pattr, struct mdd_object *cobj, const struct lu_attr *cattr)
static int mdd_may_delete_entry (const struct lu_env *env, struct mdd_object *pobj, const struct lu_attr *pattr, int check_perm)
int mdd_may_delete (const struct lu_env *env, struct mdd_object *tpobj, const struct lu_attr *tpattr, struct mdd_object *tobj, const struct lu_attr *tattr, const struct lu_attr *cattr, int check_perm, int check_empty)
static int mdd_link_sanity_check (const struct lu_env *env, struct mdd_object *tgt_obj, const struct lu_attr *tattr, const struct lu_name *lname, struct mdd_object *src_obj, const struct lu_attr *cattr)
Check whether it can create the link file(linked to) under the target directory(), and src_obj has been locked by mdd_write_lock.
static int __mdd_index_delete_only (const struct lu_env *env, struct mdd_object *pobj, const char *name, struct thandle *handle)
static int __mdd_index_insert_only (const struct lu_env *env, struct mdd_object *pobj, const struct lu_fid *lf, __u32 type, const char *name, struct thandle *handle)
static int __mdd_index_insert (const struct lu_env *env, struct mdd_object *pobj, const struct lu_fid *lf, __u32 type, const char *name, struct thandle *handle)
static int __mdd_index_delete (const struct lu_env *env, struct mdd_object *pobj, const char *name, int is_dir, struct thandle *handle)
static int mdd_llog_record_calc_size (const struct lu_env *env, const struct lu_name *tname, const struct lu_name *sname)
int mdd_declare_changelog_store (const struct lu_env *env, struct mdd_device *mdd, const struct lu_name *tname, const struct lu_name *sname, struct thandle *handle)
int mdd_changelog_store (const struct lu_env *env, struct mdd_device *mdd, struct llog_changelog_rec *rec, struct thandle *th)
Add a changelog entry rec to the changelog llog.
static void mdd_changelog_rec_ext_rename (struct changelog_rec *rec, const struct lu_fid *sfid, const struct lu_fid *spfid, const struct lu_name *sname)
void mdd_changelog_rec_ext_jobid (struct changelog_rec *rec, const char *jobid)
int mdd_changelog_ns_store (const struct lu_env *env, struct mdd_device *mdd, enum changelog_rec_type type, enum changelog_rec_flags crf, struct mdd_object *target, const struct lu_fid *tpfid, const struct lu_fid *sfid, const struct lu_fid *spfid, const struct lu_name *tname, const struct lu_name *sname, struct thandle *handle)
Store a namespace change changelog record If this fails, we must fail the whole transaction; we don't want the change to commit without the log entry.
static int __mdd_links_add (const struct lu_env *env, struct mdd_object *mdd_obj, struct linkea_data *ldata, const struct lu_name *lname, const struct lu_fid *pfid, int first, int check)
static int __mdd_links_del (const struct lu_env *env, struct mdd_object *mdd_obj, struct linkea_data *ldata, const struct lu_name *lname, const struct lu_fid *pfid)
static int mdd_linkea_prepare (const struct lu_env *env, struct mdd_object *mdd_obj, const struct lu_fid *oldpfid, const struct lu_name *oldlname, const struct lu_fid *newpfid, const struct lu_name *newlname, int first, int check, struct linkea_data *ldata)
int mdd_links_rename (const struct lu_env *env, struct mdd_object *mdd_obj, const struct lu_fid *oldpfid, const struct lu_name *oldlname, const struct lu_fid *newpfid, const struct lu_name *newlname, struct thandle *handle, struct linkea_data *ldata, int first, int check)
static int mdd_links_add (const struct lu_env *env, struct mdd_object *mdd_obj, const struct lu_fid *pfid, const struct lu_name *lname, struct thandle *handle, struct linkea_data *ldata, int first)
static int mdd_links_del (const struct lu_env *env, struct mdd_object *mdd_obj, const struct lu_fid *pfid, const struct lu_name *lname, struct thandle *handle)
int mdd_links_read (const struct lu_env *env, struct mdd_object *mdd_obj, struct linkea_data *ldata)
Read the link EA into a temp buffer.
struct lu_buf * mdd_links_get (const struct lu_env *env, struct mdd_object *mdd_obj)
Read the link EA into a temp buffer.
int mdd_links_write (const struct lu_env *env, struct mdd_object *mdd_obj, struct linkea_data *ldata, struct thandle *handle)
int mdd_declare_links_add (const struct lu_env *env, struct mdd_object *mdd_obj, struct thandle *handle, struct linkea_data *ldata, enum mdd_links_add_overflow overflow)
static int mdd_declare_links_del (const struct lu_env *env, struct mdd_object *c, struct thandle *handle)
static int mdd_declare_link (const struct lu_env *env, struct mdd_device *mdd, struct mdd_object *p, struct mdd_object *c, const struct lu_name *name, struct thandle *handle, struct lu_attr *la, struct linkea_data *data)
static int mdd_link (const struct lu_env *env, struct md_object *tgt_obj, struct md_object *src_obj, const struct lu_name *lname, struct md_attr *ma)
static int mdd_mark_orphan_object (const struct lu_env *env, struct mdd_object *obj, struct thandle *handle, bool declare)
static int mdd_declare_finish_unlink (const struct lu_env *env, struct mdd_object *obj, struct thandle *handle)
int mdd_finish_unlink (const struct lu_env *env, struct mdd_object *obj, struct md_attr *ma, const struct mdd_object *pobj, const struct lu_name *lname, struct thandle *th)
int mdd_unlink_sanity_check (const struct lu_env *env, struct mdd_object *pobj, const struct lu_attr *pattr, struct mdd_object *cobj, const struct lu_attr *cattr)
static int mdd_declare_unlink (const struct lu_env *env, struct mdd_device *mdd, struct mdd_object *p, struct mdd_object *c, const struct lu_name *name, struct md_attr *ma, struct thandle *handle, int no_name, int is_dir)
static bool mdd_hsm_archive_exists (const struct lu_env *env, struct mdd_object *obj, struct md_attr *ma)
static int mdd_unlink (const struct lu_env *env, struct md_object *pobj, struct md_object *cobj, const struct lu_name *lname, struct md_attr *ma, int no_name)
Delete name entry and the object.
static int mdd_cd_sanity_check (const struct lu_env *env, struct mdd_object *obj)
static int mdd_create_data (const struct lu_env *env, struct md_object *pobj, struct md_object *cobj, const struct md_op_spec *spec, struct md_attr *ma)
static int mdd_declare_object_initialize (const struct lu_env *env, struct mdd_object *parent, struct mdd_object *child, struct lu_attr *attr, struct thandle *handle)
static int mdd_object_initialize (const struct lu_env *env, const struct lu_fid *pfid, struct mdd_object *child, struct lu_attr *attr, struct thandle *handle, const struct md_op_spec *spec)
static int mdd_create_sanity_check (const struct lu_env *env, struct md_object *pobj, const struct lu_attr *pattr, const struct lu_name *lname, struct lu_attr *cattr, struct md_op_spec *spec)
This function checks whether it can create a file/dir under the directory().
static int mdd_declare_object_create (const struct lu_env *env, struct mdd_device *mdd, struct mdd_object *p, struct mdd_object *c, struct lu_attr *attr, struct thandle *handle, const struct md_op_spec *spec, struct lu_buf *def_acl_buf, struct lu_buf *acl_buf, struct dt_allocation_hint *hint)
static int mdd_declare_create (const struct lu_env *env, struct mdd_device *mdd, struct mdd_object *p, struct mdd_object *c, const struct lu_name *name, struct lu_attr *attr, struct thandle *handle, const struct md_op_spec *spec, struct linkea_data *ldata, struct lu_buf *def_acl_buf, struct lu_buf *acl_buf, struct dt_allocation_hint *hint)
static int mdd_acl_init (const struct lu_env *env, struct mdd_object *pobj, struct lu_attr *la, struct lu_buf *def_acl_buf, struct lu_buf *acl_buf)
static int mdd_object_create (const struct lu_env *env, struct mdd_object *pobj, struct mdd_object *son, struct lu_attr *attr, struct md_op_spec *spec, struct lu_buf *acl_buf, struct lu_buf *def_acl_buf, struct dt_allocation_hint *hint, struct thandle *handle)
Create a metadata object and initialize it, set acl, xattr.
static int mdd_index_delete (const struct lu_env *env, struct mdd_object *mdd_pobj, struct lu_attr *cattr, const struct lu_name *lname)
static int mdd_create (const struct lu_env *env, struct md_object *pobj, const struct lu_name *lname, struct md_object *child, struct md_op_spec *spec, struct md_attr *ma)
static int mdd_rename_order (const struct lu_env *env, struct mdd_device *mdd, struct mdd_object *src_pobj, const struct lu_attr *pattr, struct mdd_object *tgt_pobj)
static int mdd_rename_sanity_check (const struct lu_env *env, struct mdd_object *src_pobj, const struct lu_attr *pattr, struct mdd_object *tgt_pobj, const struct lu_attr *tpattr, struct mdd_object *sobj, const struct lu_attr *cattr, struct mdd_object *tobj, const struct lu_attr *tattr)
static int mdd_declare_rename (const struct lu_env *env, struct mdd_device *mdd, struct mdd_object *mdd_spobj, struct mdd_object *mdd_tpobj, struct mdd_object *mdd_sobj, struct mdd_object *mdd_tobj, const struct lu_name *sname, const struct lu_name *tname, struct md_attr *ma, struct linkea_data *ldata, struct thandle *handle)
static int mdd_rename (const struct lu_env *env, struct md_object *src_pobj, struct md_object *tgt_pobj, const struct lu_fid *lf, const struct lu_name *lsname, struct md_object *tobj, const struct lu_name *ltname, struct md_attr *ma)
static int mdd_linkea_update_child_internal (const struct lu_env *env, struct mdd_object *parent, struct mdd_object *newparent, struct mdd_object *child, const char *name, int namelen, struct thandle *handle, bool declare)
During migration once the parent FID has been changed, we need update the parent FID in linkea.
static int mdd_linkea_declare_update_child (const struct lu_env *env, struct mdd_object *parent, struct mdd_object *newparent, struct mdd_object *child, const char *name, int namelen, struct thandle *handle)
static int mdd_linkea_update_child (const struct lu_env *env, struct mdd_object *parent, struct mdd_object *newparent, struct mdd_object *child, const char *name, int namelen, struct thandle *handle)
static int mdd_update_linkea_internal (const struct lu_env *env, struct mdd_object *mdd_pobj, struct mdd_object *mdd_sobj, struct mdd_object *mdd_tobj, const struct lu_name *child_name, struct linkea_data *ldata, struct thandle *handle, int declare)
static int mdd_migrate_xattrs (const struct lu_env *env, struct mdd_object *mdd_sobj, struct mdd_object *mdd_tobj)
static int mdd_declare_migrate_create (const struct lu_env *env, struct mdd_object *mdd_pobj, struct mdd_object *mdd_sobj, struct mdd_object *mdd_tobj, struct md_op_spec *spec, struct lu_attr *la, union lmv_mds_md *mgr_ea, struct linkea_data *ldata, struct thandle *handle)
static int mdd_migrate_create (const struct lu_env *env, struct mdd_object *mdd_pobj, struct mdd_object *mdd_sobj, struct mdd_object *mdd_tobj, const struct lu_name *lname, struct lu_attr *la)
static int mdd_migrate_entries (const struct lu_env *env, struct mdd_object *mdd_sobj, struct mdd_object *mdd_tobj)
static int mdd_declare_update_linkea (const struct lu_env *env, struct mdd_object *mdd_pobj, struct mdd_object *mdd_sobj, struct mdd_object *mdd_tobj, const struct lu_name *child_name, struct linkea_data *ldata, struct thandle *handle)
static int mdd_update_linkea (const struct lu_env *env, struct mdd_object *mdd_pobj, struct mdd_object *mdd_sobj, struct mdd_object *mdd_tobj, const struct lu_name *child_name, struct linkea_data *ldata, struct thandle *handle)
static int mdd_declare_migrate_update_name (const struct lu_env *env, struct mdd_object *mdd_pobj, struct mdd_object *mdd_sobj, struct mdd_object *mdd_tobj, const struct lu_name *lname, struct lu_attr *la, struct lu_attr *parent_la, struct linkea_data *ldata, struct thandle *handle)
static int mdd_migrate_update_name (const struct lu_env *env, struct mdd_object *mdd_pobj, struct mdd_object *mdd_sobj, struct mdd_object *mdd_tobj, const struct lu_name *lname, struct md_attr *ma)
static int mdd_fld_lookup (const struct lu_env *env, struct mdd_device *mdd, const struct lu_fid *fid, __u32 *mdt_index)
static int mdd_migrate_sanity_check (const struct lu_env *env, struct mdd_object *pobj, const struct lu_attr *pattr, struct mdd_object *sobj, struct lu_attr *sattr)
Check whether we should migrate the file/dir return val < 0 permission check failed or other error.
static int mdd_migrate (const struct lu_env *env, struct md_object *pobj, struct md_object *sobj, const struct lu_name *lname, struct md_object *tobj, struct md_attr *ma)
Variables
static const char dot [] = "."
static const char dotdot [] = ".."
static struct lu_name lname_dotdot
struct md_dir_operations mdd_dir_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 43 of file mdd_dir.c.
Enumeration Type Documentation
enum rename_order
Enumerator:
MDD_RN_SAME
MDD_RN_SRCTGT
MDD_RN_TGTSRC
Definition at line 2557 of file mdd_dir.c.
Function Documentation
static int __mdd_index_delete (const struct lu_env * env, struct mdd_object * pobj, const char * name, int is_dir, struct thandle * handle) [static]
Definition at line 649 of file mdd_dir.c.
References __mdd_index_delete_only(), ENTRY, mdd_write_lock(), mdd_write_unlock(), mdo_ref_del(), MOR_TGT_PARENT, and RETURN.
Referenced by mdd_create(), mdd_index_delete(), mdd_migrate_entries(), mdd_migrate_update_name(), mdd_rename(), mdd_unlink(), and mdd_update_linkea_internal().
static int __mdd_index_delete_only (const struct lu_env * env, struct mdd_object * pobj, const char * name, struct thandle * handle) [static]
Definition at line 588 of file mdd_dir.c.
References dt_delete(), dt_key, dt_try_as_dir(), ENTRY, mdd_object_child(), and RETURN.
Referenced by __mdd_index_delete(), mdd_migrate_entries(), and mdd_rename().
static int __mdd_index_insert (const struct lu_env * env, struct mdd_object * pobj, const struct lu_fid * lf, __u32 type, const char * name, struct thandle * handle) [static]
Definition at line 631 of file mdd_dir.c.
References __mdd_index_insert_only(), ENTRY, mdd_write_lock(), mdd_write_unlock(), mdo_ref_add(), MOR_TGT_PARENT, and RETURN.
Referenced by mdd_create(), mdd_migrate_entries(), mdd_migrate_update_name(), mdd_rename(), and mdd_update_linkea_internal().
static int __mdd_index_insert_only (const struct lu_env * env, struct mdd_object * pobj, const struct lu_fid * lf, __u32 type, const char * name, struct thandle * handle) [static]
Definition at line 603 of file mdd_dir.c.
References CFS_CAP_SYS_RESOURCE_MASK, dt_insert(), dt_key, dt_try_as_dir(), ENTRY, lu_ucred_check(), mdd_env_info(), mdd_object_child(), mdd_thread_info::mti_dt_rec, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, RETURN, and lu_ucred::uc_cap.
Referenced by __mdd_index_insert(), mdd_link(), mdd_migrate_entries(), mdd_object_initialize(), mdd_rename(), and mdd_unlink().
static int __mdd_links_add (const struct lu_env * env, struct mdd_object * mdd_obj, struct linkea_data * ldata, const struct lu_name * lname, const struct lu_fid * pfid, int first, int check) [static]
Definition at line 894 of file mdd_dir.c.
References lu_fid::f_ver, linkea_data::ld_leh, linkea_add_buf(), linkea_data_new(), linkea_links_find(), mdd_env_info(), mdd_links_read(), mdd_thread_info::mti_fid2, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_LINKEA_MORE, and OBD_FAIL_LFSCK_LINKEA_MORE2.
Referenced by mdd_linkea_prepare().
static int __mdd_links_del (const struct lu_env * env, struct mdd_object * mdd_obj, struct linkea_data * ldata, const struct lu_name * lname, const struct lu_fid * pfid) [static]
Definition at line 937 of file mdd_dir.c.
References linkea_data::ld_leh, linkea_del_buf(), linkea_links_find(), and mdd_links_read().
Referenced by mdd_linkea_prepare().
static int __mdd_lookup (const struct lu_env * env, struct md_object * pobj, const struct lu_attr * pattr, const struct lu_name * lname, struct lu_fid * fid, int mask) [static]
Definition at line 73 of file mdd_dir.c.
References CDEBUG, D_INFO, DFID, dir, dt_key, dt_lookup(), dt_try_as_dir(), ENTRY, likely, lu_name::ln_name, md2mdd_obj(), mdd2obd_dev(), mdd_is_dead_obj(), mdd_object_child(), mdd_object_exists(), mdd_object_remote(), mdd_object_type(), mdd_permission_internal_locked(), mdo2fid(), mdo2mdd(), MOR_TGT_PARENT, name, PFID, RETURN, and unlikely.
Referenced by mdd_create_sanity_check(), mdd_lookup(), and mdd_parent_fid().
static int __mdd_may_link (const struct lu_env * env, struct mdd_object * obj, const struct lu_attr * la) [static]
Determine if the target object can be hard linked, and right now it only checks if the link count reach the maximum limit.
Note: for ldiskfs, the directory nlink count might exceed the maximum link count(see osd_object_ref_add), so it only check nlink for non-directories.
Parameters:
[in] env thread environment
[in] obj object being linked to
[in] la attributes of obj
Return values:
0 if obj can be hard linked
negative error if obj is a directory or has too many links
Definition at line 349 of file mdd_dir.c.
References dt_device_param::ddp_max_nlink, ENTRY, lu_attr::la_mode, lu_attr::la_nlink, LASSERT, mdd_device::mdd_dt_conf, mdd_obj2mdd_dev(), and RETURN.
Referenced by mdd_link_sanity_check(), and mdd_rename_sanity_check().
static int mdd_acl_init (const struct lu_env * env, struct mdd_object * pobj, struct lu_attr * la, struct lu_buf * def_acl_buf, struct lu_buf * acl_buf) [static]
Definition at line 2144 of file mdd_dir.c.
References __mdd_fix_mode_acl(), ENTRY, lu_attr::la_mode, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lu_ucred(), mdd_read_lock(), mdd_read_unlock(), mdo_xattr_get(), MOR_TGT_PARENT, RETURN, lu_ucred::uc_umask, unlikely, and XATTR_NAME_ACL_DEFAULT.
Referenced by mdd_create().
static int mdd_cd_sanity_check (const struct lu_env * env, struct mdd_object * obj) [static]
Definition at line 1770 of file mdd_dir.c.
References ENTRY, mdd_is_dead_obj(), and RETURN.
Referenced by mdd_create_data().
int mdd_changelog_ns_store (const struct lu_env * env, struct mdd_device * mdd, enum changelog_rec_type type, enum changelog_rec_flags crf, struct mdd_object * target, const struct lu_fid * tpfid, const struct lu_fid * sfid, const struct lu_fid * spfid, const struct lu_name * tname, const struct lu_name * sname, struct thandle * handle)
Store a namespace change changelog record If this fails, we must fail the whole transaction; we don't want the change to commit without the log entry.
Parameters:
target - mdd_object of change
tpfid - target parent dir/object fid
sfid - source object fid
spfid - source parent fid
tname - target name string
sname - source name string
handle - transaction handle
Definition at line 817 of file mdd_dir.c.
References buf, CERROR, cfs_time_current_64, changelog_rec_name(), CLF_FLAGMASK, CLF_JOBID, CLF_RENAME, CLF_VERSION, CLM_ON, llog_changelog_rec::cr, changelog_rec::cr_flags, changelog_rec::cr_namelen, changelog_rec::cr_pfid, changelog_rec::cr_tfid, changelog_rec::cr_type, DFID, ENTRY, fid_zero(), LASSERT, lu_buf::lb_buf, likely, lu_name::ln_name, lu_name::ln_namelen, lu_buf_check_and_alloc(), lu_ucred(), mdd_changelog::mc_flags, mdd_changelog::mc_mask, mdd2obd_dev(), mdd_changelog_rec_ext_jobid(), mdd_changelog_rec_ext_rename(), mdd_changelog_store(), mdd_device::mdd_cl, mdd_env_info(), mdd_llog_record_calc_size(), mdo2fid(), mdd_object::mod_cltime, PFID, RETURN, and lu_ucred::uc_jobid.
Referenced by mdd_create(), mdd_link(), mdd_migrate_update_name(), mdd_rename(), and mdd_unlink().
void mdd_changelog_rec_ext_jobid (struct changelog_rec * rec, const char * jobid)
Definition at line 796 of file mdd_dir.c.
References changelog_rec_jobid(), changelog_ext_jobid::cr_jobid, and strlcpy().
Referenced by mdd_changelog_data_store(), and mdd_changelog_ns_store().
static void mdd_changelog_rec_ext_rename (struct changelog_rec * rec, const struct lu_fid * sfid, const struct lu_fid * spfid, const struct lu_name * sname) [static]
Definition at line 776 of file mdd_dir.c.
References changelog_rec_name(), changelog_rec_rename(), changelog_rec_sname(), changelog_rec::cr_namelen, changelog_ext_rename::cr_sfid, changelog_ext_rename::cr_spfid, LASSERT, lu_name::ln_name, lu_name::ln_namelen, and strlcpy().
Referenced by mdd_changelog_ns_store().
int mdd_changelog_store (const struct lu_env * env, struct mdd_device * mdd, struct llog_changelog_rec * rec, struct thandle * th)
Add a changelog entry rec to the changelog llog.
Parameters:
mdd
rec
handle - currently ignored since llogs start their own transaction; this will hopefully be fixed in llog rewrite
Return values:
0 ok
Definition at line 736 of file mdd_dir.c.
References CHANGELOG_REC, changelog_rec_varsize(), cl_time(), llog_changelog_rec::cr, llog_changelog_rec::cr_hdr, changelog_rec::cr_index, changelog_rec::cr_time, GOTO, llog_handle::lgh_obj, llog_add(), LLOG_CHANGELOG_ORIG_CTXT, llog_ctxt_put(), llog_data_len(), llog_get_context(), llog_ctxt::loc_handle, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, mdd_changelog::mc_index, mdd_changelog::mc_lock, mdd2obd_dev(), mdd_device::mdd_cl, and thandle_get_sub().
Referenced by mdd_changelog_data_store(), and mdd_changelog_ns_store().
static int mdd_create (const struct lu_env * env, struct md_object * pobj, const struct lu_name * lname, struct md_object * child, struct md_op_spec * spec, struct md_attr * ma) [static]
Definition at line 2347 of file mdd_dir.c.
References __mdd_index_delete(), __mdd_index_insert(), __mdd_orphan_add(), __mdd_orphan_del(), CL_CREATE, CL_MKDIR, CL_MKNOD, CL_SOFTLINK, ENTRY, EXIT, lu_fid::f_oid, fid_is_namespace_visible(), GOTO, LA_CTIME, lu_attr::la_mode, LA_MTIME, lu_attr::la_valid, lu_buf::lb_buf, lu_buf::lb_len, linkea_data::ld_buf, likely, lu_name::ln_name, lu_object::lo_header, lu_object_header::loh_flags, lu_buf_free(), LU_OBJECT_HEARD_BANSHEE, md_attr::ma_attr, md2mdd_obj(), mdd_acl_init(), mdd_changelog_ns_store(), mdd_create_sanity_check(), mdd_declare_create(), mdd_env_info(), mdd_index_delete(), mdd_la_get(), mdd_linkea_prepare(), mdd_links_add(), mdd_object_create(), mdd_object_fid(), mdd_object_make_hint(), mdd_object_remote(), mdd_trans_create(), mdd_trans_start(), mdd_trans_stop(), mdd_update_time(), mdd_write_lock(), mdd_write_unlock(), mdo2fid(), mdo2mdd(), mdo_destroy(), mdo_ref_del(), MDS_OPEN_VOLATILE, md_object::mo_lu, MOR_TGT_CHILD, mdd_thread_info::mti_hint, mdd_thread_info::mti_key, mdd_thread_info::mti_la_for_fix, mdd_thread_info::mti_link_data, mdd_thread_info::mti_pattr, mdd_thread_info::mti_xattr_buf, name, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_BAD_PARENT, OBD_FAIL_MDS_DQACQ_NET, RETURN, md_op_spec::sp_cr_flags, and unlikely.
static int mdd_create_data (const struct lu_env * env, struct md_object * pobj, struct md_object * cobj, const struct md_op_spec * spec, struct md_attr * ma) [static]
Definition at line 1782 of file mdd_dir.c.
References buf, CDEBUG, CL_LAYOUT, D_OTHER, dt_declare_xattr_set(), dt_xattr_set(), ENTRY, GOTO, LPO64, LU_BUF_NULL, md2mdd_obj(), md_should_create(), mdd_buf_get_const(), mdd_cd_sanity_check(), mdd_changelog_data_store(), mdd_declare_changelog_store(), mdd_env_info(), MDD_ENV_VAR, mdd_la_get(), mdd_object_child(), mdd_object_make_hint(), mdd_trans_create(), mdd_trans_start(), mdd_trans_stop(), mdo2mdd(), MDS_OPEN_HAS_EA, mdd_thread_info::mti_hint, md_op_spec::no_create, RETURN, md_op_spec::sp_cr_flags, md_op_spec::sp_ea, stop, md_op_spec::u, and XATTR_NAME_LOV.
static int mdd_create_sanity_check (const struct lu_env * env, struct md_object * pobj, const struct lu_attr * pattr, const struct lu_name * lname, struct lu_attr * cattr, struct md_op_spec * spec) [static]
This function checks whether it can create a file/dir under the directory().
The directory() is not being locked by mdd lock.
Parameters:
[in] env execution environment
[in] pobj the directory to create files
[in] pattr the attributes of the directory
[in] lname the name of the created file/dir
[in] cattr the attributes of the file/dir
[in] spec create specification
Return values:
= 0 it is allowed to create file/dir under the directory
negative error not allowed to create file/dir under the directory
Definition at line 1940 of file mdd_dir.c.
References __mdd_lookup(), dt_device_param::ddp_symlink_max, ENTRY, lu_attr::la_gid, LA_MODE, lu_attr::la_mode, lu_attr::la_valid, md2mdd_obj(), mdd_device::mdd_dt_conf, mdd_env_info(), mdd_is_dead_obj(), mdd_may_create(), mdd_name_check(), mdo2mdd(), mdd_thread_info::mti_fid, RETURN, md_op_spec::sp_cr_lookup, md_op_spec::sp_symname, and md_op_spec::u.
Referenced by mdd_create().
int mdd_declare_changelog_store (const struct lu_env * env, struct mdd_device * mdd, const struct lu_name * tname, const struct lu_name * sname, struct thandle * handle)
Definition at line 686 of file mdd_dir.c.
References buf, CHANGELOG_REC, CLM_ON, llog_changelog_rec::cr_hdr, GOTO, lu_buf::lb_buf, llog_handle::lgh_obj, LLOG_CHANGELOG_ORIG_CTXT, llog_ctxt_put(), llog_declare_add(), llog_get_context(), llog_ctxt::loc_handle, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, lu_buf_check_and_alloc(), mdd_changelog::mc_flags, mdd2obd_dev(), mdd_device::mdd_cl, mdd_env_info(), mdd_llog_record_calc_size(), and thandle_get_sub().
Referenced by mdd_changelog(), mdd_close(), mdd_create_data(), mdd_declare_attr_set(), mdd_declare_create(), mdd_declare_link(), mdd_declare_migrate_update_name(), mdd_declare_rename(), mdd_declare_unlink(), mdd_declare_xattr_del(), and mdd_declare_xattr_set().
static int mdd_declare_create (const struct lu_env * env, struct mdd_device * mdd, struct mdd_object * p, struct mdd_object * c, const struct lu_name * name, struct lu_attr * attr, struct thandle * handle, const struct md_op_spec * spec, struct linkea_data * ldata, struct lu_buf * def_acl_buf, struct lu_buf * acl_buf, struct dt_allocation_hint * hint) [static]
Definition at line 2090 of file mdd_dir.c.
References GOTO, LA_CTIME, lu_attr::la_mode, LA_MTIME, lu_attr::la_valid, lu_name::ln_name, mdd_declare_changelog_store(), mdd_declare_links_add(), mdd_declare_object_create(), mdd_env_info(), mdo2fid(), mdo_declare_attr_set(), mdo_declare_index_insert(), mdo_declare_ref_add(), MDS_OPEN_VOLATILE, MLAO_IGNORE, mdd_thread_info::mti_la_for_fix, orph_declare_index_insert(), md_op_spec::sp_cr_flags, and unlikely.
Referenced by mdd_create().
static int mdd_declare_finish_unlink (const struct lu_env * env, struct mdd_object * obj, struct thandle * handle) [static]
Definition at line 1428 of file mdd_dir.c.
References mdd_declare_links_del(), mdd_mark_orphan_object(), mdd_object_type(), mdo_declare_destroy(), and orph_declare_index_insert().
Referenced by mdd_declare_migrate_update_name(), mdd_declare_rename(), and mdd_declare_unlink().
static int mdd_declare_link (const struct lu_env * env, struct mdd_device * mdd, struct mdd_object * p, struct mdd_object * c, const struct lu_name * name, struct thandle * handle, struct lu_attr * la, struct linkea_data * data) [static]
Definition at line 1248 of file mdd_dir.c.
References LA_CTIME, LA_MTIME, lu_attr::la_valid, lu_name::ln_name, mdd_declare_changelog_store(), mdd_declare_links_add(), mdd_object_type(), mdo2fid(), mdo_declare_attr_set(), mdo_declare_index_insert(), mdo_declare_ref_add(), MLAO_CHECK, MLAO_IGNORE, OBD_FAIL_CHECK, and OBD_FAIL_LFSCK_MORE_NLINK.
Referenced by mdd_link().
int mdd_declare_links_add (const struct lu_env * env, struct mdd_object * mdd_obj, struct thandle * handle, struct linkea_data * ldata, enum mdd_links_add_overflow overflow)
Definition at line 1188 of file mdd_dir.c.
References DEFAULT_LINKEA_SIZE, lu_buf::lb_buf, linkea_data::ld_buf, linkea_data::ld_leh, LE_SKIP_NLINK_DECLARE, link_ea_header::leh_len, lfsck_in_notify(), lfsck_pack_rfa(), LFSCK_TYPE_NAMESPACE, mdd_device::mdd_bottom, mdd_buf_get_const(), mdd_env_info(), mdd_object_remote(), mdo2fid(), mdo2mdd(), mdo_declare_xattr_set(), MLAO_CHECK, mdd_object::mod_obj, mdd_thread_info::mti_lr, thandle_get_sub_by_dt(), and XATTR_NAME_LINK.
Referenced by mdd_declare_create(), mdd_declare_link(), mdd_declare_links_del(), mdd_declare_migrate_create(), mdd_declare_migrate_update_name(), mdd_declare_rename(), and mdd_linkea_update_child_internal().
static int mdd_declare_links_del (const struct lu_env * env, struct mdd_object * c, struct thandle * handle) [inline, static]
Definition at line 1234 of file mdd_dir.c.
References mdd_declare_links_add(), mdd_object_type(), and MLAO_IGNORE.
Referenced by mdd_declare_finish_unlink().
static int mdd_declare_migrate_create (const struct lu_env * env, struct mdd_object * mdd_pobj, struct mdd_object * mdd_sobj, struct mdd_object * mdd_tobj, struct md_op_spec * spec, struct lu_attr * la, union lmv_mds_md * mgr_ea, struct linkea_data * ldata, struct thandle * handle) [static]
Definition at line 3402 of file mdd_dir.c.
References buf, dt_declare_record_write(), lu_attr::la_flags, LA_FLAGS, lu_attr::la_mode, lu_attr::la_valid, LMV_MAGIC_V1, lmv_mds_md_size(), LUSTRE_IMMUTABLE_FL, mdd_buf_get_const(), mdd_declare_links_add(), mdd_declare_object_create_internal(), mdd_declare_object_initialize(), MDD_ENV_VAR, mdd_object_child(), mdo_declare_attr_set(), mdo_declare_xattr_set(), MLAO_IGNORE, md_op_spec::sp_ea, md_op_spec::sp_symname, md_op_spec::u, XATTR_NAME_LMV, and XATTR_NAME_LOV.
Referenced by mdd_migrate_create().
static int mdd_declare_migrate_update_name (const struct lu_env * env, struct mdd_object * mdd_pobj, struct mdd_object * mdd_sobj, struct mdd_object * mdd_tobj, const struct lu_name * lname, struct lu_attr * la, struct lu_attr * parent_la, struct linkea_data * ldata, struct thandle * handle) [static]
Definition at line 3834 of file mdd_dir.c.
References lu_attr::la_flags, LA_FLAGS, lu_attr::la_valid, linkea_data::ld_buf, lu_name::ln_name, LU_XATTR_REPLACE, LUSTRE_IMMUTABLE_FL, mdd_declare_changelog_store(), mdd_declare_finish_unlink(), mdd_declare_links_add(), mdd_declare_update_linkea(), MDD_ENV_VAR, mdd_object_type(), mdo2fid(), mdo2mdd(), mdo_declare_attr_set(), mdo_declare_index_delete(), mdo_declare_index_insert(), mdo_declare_ref_add(), mdo_declare_ref_del(), mdo_declare_xattr_del(), mdo_declare_xattr_set(), MLAO_IGNORE, mdd_object::mod_obj, thandle::th_complex, XATTR_NAME_FID, and XATTR_NAME_LOV.
Referenced by mdd_migrate_update_name().
static int mdd_declare_object_create (const struct lu_env * env, struct mdd_device * mdd, struct mdd_object * p, struct mdd_object * c, struct lu_attr * attr, struct thandle * handle, const struct md_op_spec * spec, struct lu_buf * def_acl_buf, struct lu_buf * acl_buf, struct dt_allocation_hint * hint) [static]
Definition at line 2020 of file mdd_dir.c.
References buf, dt_declare_record_write(), GOTO, lu_attr::la_mode, lu_buf::lb_len, mdd_buf_get_const(), mdd_declare_object_create_internal(), mdd_declare_object_initialize(), mdd_object_child(), mdo_declare_attr_set(), mdo_declare_xattr_set(), MDS_OPEN_HAS_EA, md_op_spec::no_create, md_op_spec::sp_cr_flags, md_op_spec::sp_ea, md_op_spec::sp_symname, md_op_spec::u, XATTR_NAME_ACL_ACCESS, XATTR_NAME_ACL_DEFAULT, and XATTR_NAME_LOV.
Referenced by mdd_declare_create().
static int mdd_declare_object_initialize (const struct lu_env * env, struct mdd_object * parent, struct mdd_object * child, struct lu_attr * attr, struct thandle * handle) [static]
Definition at line 1862 of file mdd_dir.c.
References dot, dotdot, ENTRY, lu_attr::la_mode, LA_MODE, LA_TYPE, lu_attr::la_valid, LASSERT, mdo2fid(), mdo_declare_attr_set(), mdo_declare_index_insert(), mdo_declare_ref_add(), and RETURN.
Referenced by mdd_declare_migrate_create(), and mdd_declare_object_create().
static int mdd_declare_rename (const struct lu_env * env, struct mdd_device * mdd, struct mdd_object * mdd_spobj, struct mdd_object * mdd_tpobj, struct mdd_object * mdd_sobj, struct mdd_object * mdd_tobj, const struct lu_name * sname, const struct lu_name * tname, struct md_attr * ma, struct linkea_data * ldata, struct thandle * handle) [static]
Definition at line 2637 of file mdd_dir.c.
References dotdot, lu_attr::la_ctime, LA_CTIME, LA_MTIME, lu_attr::la_mtime, lu_attr::la_valid, LASSERT, lu_name::ln_name, md_attr::ma_attr, mdd_declare_changelog_store(), mdd_declare_finish_unlink(), mdd_declare_links_add(), mdd_env_info(), mdd_object_exists(), mdd_object_type(), mdo2fid(), mdo_declare_attr_set(), mdo_declare_index_delete(), mdo_declare_index_insert(), mdo_declare_ref_add(), mdo_declare_ref_del(), MLAO_CHECK, MLAO_IGNORE, and mdd_thread_info::mti_la_for_fix.
Referenced by mdd_rename().
static int mdd_declare_unlink (const struct lu_env * env, struct mdd_device * mdd, struct mdd_object * p, struct mdd_object * c, const struct lu_name * name, struct md_attr * ma, struct thandle * handle, int no_name, int is_dir) [static]
Definition at line 1516 of file mdd_dir.c.
References lu_attr::la_ctime, LA_CTIME, LA_MTIME, lu_attr::la_mtime, lu_attr::la_valid, LASSERT, likely, lu_name::ln_name, md_attr::ma_attr, mdd_declare_changelog_store(), mdd_declare_finish_unlink(), mdd_env_info(), mdo_declare_attr_set(), mdo_declare_index_delete(), mdo_declare_ref_del(), mdd_thread_info::mti_la_for_fix, OBD_FAIL_CHECK, and OBD_FAIL_LFSCK_DANGLING2.
Referenced by mdd_unlink().
static int mdd_declare_update_linkea (const struct lu_env * env, struct mdd_object * mdd_pobj, struct mdd_object * mdd_sobj, struct mdd_object * mdd_tobj, const struct lu_name * child_name, struct linkea_data * ldata, struct thandle * handle) [static]
Definition at line 3810 of file mdd_dir.c.
References mdd_update_linkea_internal().
Referenced by mdd_declare_migrate_update_name().
static int mdd_dir_is_empty (const struct lu_env * env, struct mdd_object * dir) [static]
Definition at line 297 of file mdd_dir.c.
References dt_index_operations::dio_it, dt_object::do_index_ops, dt_key, dt_try_as_dir(), ENTRY, dt_index_operations::dt_it_ops::init, LUDA_64BITHASH, mdd_object_child(), and RETURN.
Referenced by mdd_may_delete().
int mdd_finish_unlink (const struct lu_env * env, struct mdd_object * obj, struct md_attr * ma, const struct mdd_object * pobj, const struct lu_name * lname, struct thandle * th)
Definition at line 1453 of file mdd_dir.c.
References __mdd_orphan_add(), CDEBUG, CERROR, D_HA, DEAD_OBJ, DFID, ENTRY, lu_attr::la_mode, lu_attr::la_nlink, LASSERT, md_attr::ma_attr, mdd_links_del(), mdd_mark_orphan_object(), mdd_object_fid(), mdd_write_locked(), mdo2fid(), mdo_destroy(), mdd_object::mod_count, mdd_object::mod_flags, PFID, and RETURN.
Referenced by mdd_rename(), and mdd_unlink().
static int mdd_fld_lookup (const struct lu_env * env, struct mdd_device * mdd, const struct lu_fid * fid, __u32 * mdt_index) [static]
Definition at line 4091 of file mdd_dir.c.
References lu_fid::f_seq, fld_server_lookup(), lu_site::ld_seq_site, lu_device::ld_site, lu_seq_range::lsr_flags, lu_seq_range::lsr_index, LU_SEQ_RANGE_MDT, md_device::md_lu_dev, mdd_env_info(), mdd_device::mdd_md_dev, mdd_thread_info::mti_range, and seq_server_site::ss_server_fld.
Referenced by mdd_migrate_sanity_check().
static bool mdd_hsm_archive_exists (const struct lu_env * env, struct mdd_object * obj, struct md_attr * ma) [static]
Definition at line 1576 of file mdd_dir.c.
References ENTRY, HS_EXISTS, lu_buf::lb_buf, lu_buf_alloc(), lu_buf_free(), lustre_buf2hsm(), md_attr::ma_hsm, MA_HSM, md_attr::ma_valid, mdd_buf_get(), mdo_xattr_get(), md_hsm::mh_flags, RETURN, and XATTR_NAME_HSM.
Referenced by mdd_rename(), and mdd_unlink().
static int mdd_index_delete (const struct lu_env * env, struct mdd_object * mdd_pobj, struct lu_attr * cattr, const struct lu_name * lname) [static]
Definition at line 2303 of file mdd_dir.c.
References __mdd_index_delete(), ENTRY, GOTO, lu_attr::la_mode, lu_name::ln_name, mdd_trans_create(), mdd_trans_start(), mdd_trans_stop(), mdo2mdd(), mdo_declare_index_delete(), mdo_declare_ref_del(), mdd_object::mod_obj, RETURN, stop, and thandle::th_local.
Referenced by mdd_create().
static int mdd_is_parent (const struct lu_env * env, struct mdd_device * mdd, struct mdd_object * p1, const struct lu_attr * attr, const struct lu_fid * lf, struct lu_fid * pf) [static]
Definition at line 199 of file mdd_dir.c.
References ENTRY, EXIT, GOTO, LASSERT, lu_fid_eq(), mdd_env_info(), mdd_is_root(), mdd_device::mdd_local_root_fid, mdd_object_exists(), mdd_object_find(), mdd_object_put(), mdd_parent_fid(), mdo2fid(), mdd_thread_info::mti_fid, and RETURN.
Referenced by mdd_is_subdir(), and mdd_rename_order().
int mdd_is_root (struct mdd_device * mdd, const struct lu_fid * fid)
Definition at line 184 of file mdd_dir.c.
References fid_oid(), and mdd_device::mdd_root_fid.
Referenced by mdd_is_parent().
static int mdd_is_sticky (const struct lu_env * env, struct mdd_object * pobj, const struct lu_attr * pattr, struct mdd_object * cobj, const struct lu_attr * cattr) [inline, static]
Definition at line 430 of file mdd_dir.c.
References CFS_CAP_FOWNER, lu_attr::la_mode, lu_attr::la_uid, LASSERT, lu_ucred_assert(), md_capable(), and lu_ucred::uc_fsuid.
Referenced by mdd_may_delete().
int mdd_is_subdir (const struct lu_env * env, struct md_object * mo, const struct lu_fid * fid, struct lu_fid * sfid)
Definition at line 259 of file mdd_dir.c.
References ENTRY, fid_zero(), md2mdd_obj(), MDD_ENV_VAR, mdd_is_parent(), mdd_la_get(), mdd_object_type(), mdo2mdd(), and RETURN.
static int mdd_link (const struct lu_env * env, struct md_object * tgt_obj, struct md_object * src_obj, const struct lu_name * lname, struct md_attr * ma) [static]
Definition at line 1294 of file mdd_dir.c.
References __mdd_index_insert_only(), CL_HARDLINK, ENTRY, EXIT, lu_fid::f_oid, GOTO, lu_attr::la_ctime, LA_CTIME, LA_MTIME, lu_attr::la_mtime, lu_attr::la_valid, LASSERT, linkea_data::ld_buf, lu_name::ln_name, lu_buf_free(), md_attr::ma_attr, md2mdd_obj(), mdd_changelog_ns_store(), mdd_declare_link(), mdd_env_info(), MDD_ENV_VAR, mdd_la_get(), mdd_link_sanity_check(), mdd_linkea_prepare(), mdd_links_add(), mdd_object_type(), mdd_trans_create(), mdd_trans_start(), mdd_trans_stop(), mdd_update_time(), mdd_write_lock(), mdd_write_unlock(), mdo2fid(), mdo2mdd(), mdo_ref_add(), mdo_ref_del(), MOR_TGT_CHILD, mdd_thread_info::mti_la_for_fix, mdd_thread_info::mti_link_data, name, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_DANGLING3, OBD_FAIL_LFSCK_LESS_NLINK, OBD_FAIL_LFSCK_MORE_NLINK, RETURN, and stop.
static int mdd_link_sanity_check (const struct lu_env * env, struct mdd_object * tgt_obj, const struct lu_attr * tattr, const struct lu_name * lname, struct mdd_object * src_obj, const struct lu_attr * cattr) [static]
Check whether it can create the link file(linked to) under the target directory(), and src_obj has been locked by mdd_write_lock.
Parameters:
[in] env execution environment
[in] tgt_obj the target directory
[in] tattr attributes of target directory
[in] lname the link name
[in] src_obj source object for link
[in] cattr attributes for source object
Return values:
= 0 it is allowed to create the link file under tgt_obj
negative error not allowed to create the link file
Definition at line 550 of file mdd_dir.c.
References __mdd_may_link(), ENTRY, lu_attr::la_flags, LASSERT, LUSTRE_APPEND_FL, LUSTRE_IMMUTABLE_FL, mdd_is_dead_obj(), mdd_may_create(), mdd_name_check(), mdd_obj2mdd_dev(), mdd_object_exists(), mdd_object_type(), and RETURN.
Referenced by mdd_link().
static int mdd_linkea_declare_update_child (const struct lu_env * env, struct mdd_object * parent, struct mdd_object * newparent, struct mdd_object * child, const char * name, int namelen, struct thandle * handle) [static]
Definition at line 3126 of file mdd_dir.c.
References mdd_linkea_update_child_internal().
Referenced by mdd_migrate_entries().
static int mdd_linkea_prepare (const struct lu_env * env, struct mdd_object * mdd_obj, const struct lu_fid * oldpfid, const struct lu_name * oldlname, const struct lu_fid * newpfid, const struct lu_name * newlname, int first, int check, struct linkea_data * ldata) [static]
Definition at line 959 of file mdd_dir.c.
References __mdd_links_add(), __mdd_links_del(), DEAD_OBJ, ENTRY, LASSERT, linkea_data::ld_reclen, mdd_object::mod_flags, OBD_FAIL_CHECK, OBD_FAIL_FID_IGIF, and RETURN.
Referenced by mdd_create(), mdd_link(), mdd_links_rename(), and mdd_rename().
static int mdd_linkea_update_child (const struct lu_env * env, struct mdd_object * parent, struct mdd_object * newparent, struct mdd_object * child, const char * name, int namelen, struct thandle * handle) [static]
Definition at line 3138 of file mdd_dir.c.
References mdd_linkea_update_child_internal().
Referenced by mdd_migrate_entries().
static int mdd_linkea_update_child_internal (const struct lu_env * env, struct mdd_object * parent, struct mdd_object * newparent, struct mdd_object * child, const char * name, int namelen, struct thandle * handle, bool declare) [static]
During migration once the parent FID has been changed, we need update the parent FID in linkea.
Definition at line 3063 of file mdd_dir.c.
References buf, CDEBUG, D_INFO, DFID, ENTRY, LASSERT, lu_buf::lb_buf, linkea_data::ld_buf, linkea_data::ld_lee, linkea_data::ld_leh, linkea_data::ld_reclen, link_ea_header::leh_reccount, linkea_entry_pack(), linkea_entry_unpack(), lu_name::ln_name, lu_name::ln_namelen, lu_buf_check_and_alloc(), lu_fid_eq(), mdd2obd_dev(), mdd_declare_links_add(), mdd_env_info(), mdd_links_read(), mdd_links_write(), mdd_object_fid(), mdo2mdd(), MLAO_IGNORE, mdd_object::mod_obj, mdd_thread_info::mti_link_buf, PFID, and RETURN.
Referenced by mdd_linkea_declare_update_child(), and mdd_linkea_update_child().
static int mdd_links_add (const struct lu_env * env, struct mdd_object * mdd_obj, const struct lu_fid * pfid, const struct lu_name * lname, struct thandle * handle, struct linkea_data * ldata, int first) [inline, static]
Definition at line 1069 of file mdd_dir.c.
References mdd_links_rename().
Referenced by mdd_create(), mdd_link(), mdd_migrate_update_name(), and mdd_rename().
static int mdd_links_del (const struct lu_env * env, struct mdd_object * mdd_obj, const struct lu_fid * pfid, const struct lu_name * lname, struct thandle * handle) [inline, static]
Definition at line 1080 of file mdd_dir.c.
References mdd_links_rename().
Referenced by mdd_finish_unlink().
struct lu_buf* mdd_links_get (const struct lu_env * env, struct mdd_object * mdd_obj) [read]
Read the link EA into a temp buffer.
Uses the name_buf since it is generally large.
Return values:
IS_ERR err
ptr to lu_buf (always mti_big_buf)
Definition at line 1139 of file mdd_dir.c.
References linkea_data::ld_buf, and mdd_links_read().
Referenced by mdd_layout_swap_allowed().
int mdd_links_read (const struct lu_env * env, struct mdd_object * mdd_obj, struct linkea_data * ldata)
Read the link EA into a temp buffer.
Uses the mdd_thread_info::mti_big_buf since it is generally large. A pointer to the buffer is stored in ldata::ld_buf.
Return values:
0 or error
Definition at line 1096 of file mdd_dir.c.
References LASSERT, lu_buf::lb_buf, linkea_data::ld_buf, linkea_init(), lu_buf_check_and_alloc(), lu_buf_free(), mdd_env_info(), mdd_object_exists(), mdo_xattr_get(), and XATTR_NAME_LINK.
Referenced by __mdd_links_add(), __mdd_links_del(), mdd_linkea_update_child_internal(), mdd_links_get(), mdd_migrate_create(), mdd_migrate_sanity_check(), mdd_migrate_update_name(), and mdd_parent_fid().
int mdd_links_rename (const struct lu_env * env, struct mdd_object * mdd_obj, const struct lu_fid * oldpfid, const struct lu_name * oldlname, const struct lu_fid * newpfid, const struct lu_name * newlname, struct thandle * handle, struct linkea_data * ldata, int first, int check)
Definition at line 1008 of file mdd_dir.c.
References CDEBUG, D_ERROR, D_OTHER, DFID, ENTRY, error, EXIT, GOTO, linkea_data::ld_buf, linkea_data::ld_reclen, lu_name::ln_name, lu_name::ln_namelen, lu_buf_free(), mdd_env_info(), mdd_linkea_prepare(), mdd_links_write(), mdd_object_fid(), mdd_thread_info::mti_link_data, and PFID.
Referenced by mdd_links_add(), mdd_links_del(), and mdd_rename().
int mdd_links_write (const struct lu_env * env, struct mdd_object * mdd_obj, struct linkea_data * ldata, struct thandle * handle)
Definition at line 1149 of file mdd_dir.c.
References buf, lu_buf::lb_buf, linkea_data::ld_buf, linkea_data::ld_leh, LE_SKIP_NLINK, link_ea_header::leh_len, lfsck_in_notify(), lfsck_pack_rfa(), LFSCK_TYPE_NAMESPACE, mdd_device::mdd_bottom, mdd_buf_get_const(), mdd_env_info(), mdd_object_remote(), mdd_object_type(), mdo2fid(), mdo2mdd(), mdo_xattr_set(), mdd_object::mod_obj, mdd_thread_info::mti_lr, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_NO_LINKEA, thandle_get_sub_by_dt(), unlikely, and XATTR_NAME_LINK.
Referenced by mdd_linkea_update_child_internal(), mdd_links_rename(), and mdd_migrate_create().
static int mdd_llog_record_calc_size (const struct lu_env * env, const struct lu_name * tname, const struct lu_name * sname) [static]
Definition at line 666 of file mdd_dir.c.
References changelog_rec_offset(), CLF_JOBID, CLF_RENAME, llog_data_len(), lu_name::ln_namelen, lu_ucred(), and lu_ucred::uc_jobid.
Referenced by mdd_changelog_ns_store(), and mdd_declare_changelog_store().
int mdd_lookup (const struct lu_env * env, struct md_object * pobj, const struct lu_name * lname, struct lu_fid * fid, struct md_op_spec * spec)
Definition at line 110 of file mdd_dir.c.
References __mdd_lookup(), ENTRY, md2mdd_obj(), MDD_ENV_VAR, mdd_la_get(), RETURN, and md_op_spec::sp_permitted.
Referenced by mdd_update_linkea_internal().
static int mdd_mark_orphan_object (const struct lu_env * env, struct mdd_object * obj, struct thandle * handle, bool declare) [static]
Definition at line 1407 of file mdd_dir.c.
References lu_attr::la_flags, LA_FLAGS, lu_attr::la_valid, LUSTRE_ORPHAN_FL, MDD_ENV_VAR, mdd_object_type(), mdo_attr_set(), and mdo_declare_attr_set().
Referenced by mdd_declare_finish_unlink(), mdd_finish_unlink(), and mdd_migrate_update_name().
int mdd_may_create (const struct lu_env * env, struct mdd_object * pobj, const struct lu_attr * pattr, struct mdd_object * cobj, bool check_perm)
Check whether it may create the cobj under the pobj.
Parameters:
[in] env execution environment
[in] pobj the parent directory
[in] pattr the attribute of the parent directory
[in] cobj the child to be created
[in] check_perm if check WRITE|EXEC permission for parent
Return values:
= 0 create the child under this dir is allowed
negative errno create the child under this dir is not allowed
Definition at line 379 of file mdd_dir.c.
References ENTRY, mdd_is_dead_obj(), mdd_object_exists(), mdd_permission_internal_locked(), MOR_TGT_PARENT, and RETURN.
Referenced by mdd_create_sanity_check(), mdd_link_sanity_check(), and mdd_rename_sanity_check().
int mdd_may_delete (const struct lu_env * env, struct mdd_object * tpobj, const struct lu_attr * tpattr, struct mdd_object * tobj, const struct lu_attr * tattr, const struct lu_attr * cattr, int check_perm, int check_empty)
Definition at line 485 of file mdd_dir.c.
References ENTRY, lu_attr::la_flags, lu_attr::la_mode, LASSERT, lu_fid_eq(), LUSTRE_APPEND_FL, LUSTRE_IMMUTABLE_FL, mdd_dir_is_empty(), mdd_is_dead_obj(), mdd_is_sticky(), mdd_may_delete_entry(), mdd_object_exists(), mdd_device::mdd_root_fid, mdo2fid(), mdo2mdd(), mdd_object::mod_obj, and RETURN.
Referenced by mdd_fix_attr(), mdd_rename_sanity_check(), and mdd_unlink_sanity_check().
static int mdd_may_delete_entry (const struct lu_env * env, struct mdd_object * pobj, const struct lu_attr * pattr, int check_perm) [static]
Definition at line 452 of file mdd_dir.c.
References ENTRY, lu_attr::la_flags, LASSERT, LUSTRE_APPEND_FL, mdd_is_dead_obj(), mdd_object_exists(), mdd_permission_internal_locked(), MOR_TGT_PARENT, and RETURN.
Referenced by mdd_may_delete().
int mdd_may_unlink (const struct lu_env * env, struct mdd_object * pobj, const struct lu_attr * pattr, const struct lu_attr * attr)
Definition at line 402 of file mdd_dir.c.
References ENTRY, lu_attr::la_flags, LUSTRE_APPEND_FL, LUSTRE_IMMUTABLE_FL, mdd_is_dead_obj(), mdd_permission_internal_locked(), MOR_TGT_PARENT, and RETURN.
static int mdd_migrate (const struct lu_env * env, struct md_object * pobj, struct md_object * sobj, const struct lu_name * lname, struct md_object * tobj, struct md_attr * ma) [static]
Definition at line 4213 of file mdd_dir.c.
References CERROR, cfs_fail_val, DFID, ENTRY, GOTO, LASSERT, lu_name::ln_name, lu_object_attr(), md2mdd_obj(), mdd2obd_dev(), MDD_ENV_VAR, mdd_la_get(), mdd_migrate_create(), mdd_migrate_entries(), mdd_migrate_sanity_check(), mdd_migrate_update_name(), mdd_migrate_xattrs(), mdd_object_exists(), mdd_object_fid(), mdd_read_lock(), mdd_read_unlock(), mdo2mdd(), md_object::mo_lu, mdd_object::mod_count, mdd_object::mod_obj, MOR_SRC_CHILD, OBD_FAIL_CHECK_RESET, OBD_FAIL_MDS_REINT_NET_REP, OBD_FAIL_MIGRATE_DELAY, OBD_FAIL_MIGRATE_NET_REP, OBD_FAIL_TIMEOUT, PFID, RETURN, and unlikely.
static int mdd_migrate_create (const struct lu_env * env, struct mdd_object * mdd_pobj, struct mdd_object * mdd_sobj, struct mdd_object * mdd_tobj, const struct lu_name * lname, struct lu_attr * la) [static]
Definition at line 3467 of file mdd_dir.c.
References buf, CERROR, cpu_to_le32, DFID, dt_directory_features, ENTRY, fid_cpu_to_le(), GOTO, lu_attr::la_flags, LA_FLAGS, lu_attr::la_mode, LA_NLINK, lu_attr::la_size, lu_attr::la_valid, lu_buf::lb_buf, lu_buf::lb_len, LMV_HASH_FLAG_MIGRATION, lmv_mds_md_v1::lmv_hash_type, lmv_mds_md_v1::lmv_magic, LMV_MAGIC_V1, lmv_mds_md_v1::lmv_master_mdt_index, lmv_mds_md_size(), lmv_mds_md_v1::lmv_stripe_count, lmv_mds_md_v1::lmv_stripe_fids, lu_buf_check_and_alloc(), LUSTRE_IMMUTABLE_FL, mdd2obd_dev(), mdd_buf_get_const(), mdd_declare_migrate_create(), mdd_env_info(), MDD_ENV_VAR, mdd_get_lov_ea(), mdd_links_read(), mdd_links_write(), mdd_object_create(), mdd_object_fid(), mdd_object_make_hint(), mdd_readlink(), mdd_seq_site(), mdd_trans_create(), mdd_trans_start(), mdd_trans_stop(), mdo2mdd(), mdo_attr_set(), mdo_xattr_set(), MDS_OPEN_HAS_EA, mdd_object::mod_obj, mdd_thread_info::mti_hint, mdd_thread_info::mti_link_data, mdd_thread_info::mti_spec, mdd_thread_info::mti_xattr_buf, OBD_FREE, PFID, RETURN, md_op_spec::sp_cr_flags, md_op_spec::sp_cr_lookup, md_op_spec::sp_ea, md_op_spec::sp_feat, md_op_spec::sp_symname, seq_server_site::ss_node_id, thandle::th_local, md_op_spec::u, and XATTR_NAME_LMV.
Referenced by mdd_migrate().
static int mdd_migrate_entries (const struct lu_env * env, struct mdd_object * mdd_sobj, struct mdd_object * mdd_tobj) [static]
Definition at line 3606 of file mdd_dir.c.
References __mdd_index_delete(), __mdd_index_delete_only(), __mdd_index_insert(), __mdd_index_insert_only(), CERROR, dt_index_operations::dio_it, dt_object::do_index_ops, dotdot, dt_key, dt_lookup(), dt_try_as_dir(), ENTRY, fid_le_to_cpu(), GOTO, dt_index_operations::dt_it_ops::init, le16_to_cpu, likely, LUDA_FID, LUDA_TYPE, mdd2obd_dev(), mdd_env_info(), mdd_linkea_declare_update_child(), mdd_linkea_update_child(), mdd_object_child(), mdd_object_fid(), mdd_object_find(), mdd_object_put(), mdd_object_type(), mdd_trans_create(), mdd_trans_start(), mdd_trans_stop(), mdd_write_lock(), mdd_write_unlock(), mdo2mdd(), mdo_declare_index_delete(), mdo_declare_index_insert(), mdo_declare_ref_add(), mdo_declare_ref_del(), mdd_object::mod_obj, MOR_SRC_CHILD, mdd_thread_info::mti_fid2, mdd_thread_info::mti_key, name, OBD_ALLOC, OBD_FAIL_CHECK, OBD_FAIL_MIGRATE_ENTRIES, OBD_FREE, RETURN, thandle::th_local, and unlikely.
Referenced by mdd_migrate().
static int mdd_migrate_sanity_check (const struct lu_env * env, struct mdd_object * pobj, const struct lu_attr * pattr, struct mdd_object * sobj, struct lu_attr * sattr) [static]
Check whether we should migrate the file/dir return val < 0 permission check failed or other error.
= 0 the file can be migrated. > 0 the file does not need to be migrated, mostly for multiple link file
Definition at line 4117 of file mdd_dir.c.
References __u64, CDEBUG, D_HA, D_INFO, DFID, ENTRY, lu_attr::la_flags, lu_attr::la_mode, lu_attr::la_nlink, LASSERT, lu_buf::lb_buf, linkea_data::ld_lee, linkea_data::ld_leh, linkea_data::ld_reclen, lu_site::ld_seq_site, lu_device::ld_site, le32_to_cpu, link_ea_header::leh_reccount, linkea_entry_unpack(), LMV_HASH_FLAG_MIGRATION, lmv_mds_md_v1::lmv_hash_type, LMV_MAGIC_V1, lmv_mds_md::lmv_md_v1, lmv_mds_md_size(), lu_name::ln_name, lu_name::ln_namelen, lu_buf_check_and_alloc(), LUSTRE_IMMUTABLE_FL, md_device::md_lu_dev, mdd2obd_dev(), mdd_env_info(), mdd_fld_lookup(), mdd_links_read(), mdd_device::mdd_md_dev, mdd_object_fid(), mdd_rename_sanity_check(), mdo2mdd(), mdo_xattr_get(), mdd_object::mod_obj, mdd_thread_info::mti_big_buf, mdd_thread_info::mti_link_data, PFID, RETURN, seq_server_site::ss_node_id, and XATTR_NAME_LMV.
Referenced by mdd_migrate().
static int mdd_migrate_update_name (const struct lu_env * env, struct mdd_object * mdd_pobj, struct mdd_object * mdd_sobj, struct mdd_object * mdd_tobj, const struct lu_name * lname, struct md_attr * ma) [static]
Definition at line 3933 of file mdd_dir.c.
References __mdd_index_delete(), __mdd_index_insert(), __mdd_orphan_add(), CDEBUG, CL_MIGRATE, CWARN, D_INFO, DEAD_OBJ, DFID, ENTRY, GOTO, lu_attr::la_ctime, LA_CTIME, lu_attr::la_flags, LA_FLAGS, lu_attr::la_mode, lu_attr::la_mtime, lu_attr::la_nlink, lu_attr::la_valid, LASSERT, linkea_data::ld_buf, linkea_add_buf(), lu_name::ln_name, LU_XATTR_REPLACE, LUSTRE_IMMUTABLE_FL, md_attr::ma_attr, MA_INODE, md_attr::ma_valid, mdd2obd_dev(), mdd_attr_set_internal(), mdd_changelog_ns_store(), mdd_declare_migrate_update_name(), mdd_env_info(), MDD_ENV_VAR, mdd_la_get(), mdd_links_add(), mdd_links_read(), mdd_mark_orphan_object(), mdd_object_fid(), mdd_object_type(), mdd_trans_create(), mdd_trans_start(), mdd_trans_stop(), mdd_update_linkea(), mdd_write_lock(), mdd_write_unlock(), mdo2fid(), mdo2mdd(), mdo_attr_set(), mdo_ref_del(), mdo_xattr_del(), mdo_xattr_set(), mdd_object::mod_flags, mdd_object::mod_obj, MOR_TGT_CHILD, mdd_thread_info::mti_link_data, name, PFID, RETURN, XATTR_NAME_FID, and XATTR_NAME_LOV.
Referenced by mdd_migrate().
static int mdd_migrate_xattrs (const struct lu_env * env, struct mdd_object * mdd_sobj, struct mdd_object * mdd_tobj) [static]
Definition at line 3299 of file mdd_dir.c.
References GOTO, lu_buf::lb_buf, lu_buf::lb_len, lu_buf_check_and_alloc(), LU_BUF_NULL, lu_object_attr(), mdd_env_info(), mdd_trans_create(), mdd_trans_start(), mdd_trans_stop(), mdo2mdd(), mdo_declare_xattr_set(), mdo_xattr_get(), mdo_xattr_list(), mdo_xattr_set(), md_object::mo_lu, mdd_object::mod_obj, mdd_thread_info::mti_big_buf, mdd_thread_info::mti_link_buf, strnlen, thandle::th_local, XATTR_NAME_LINK, XATTR_NAME_LMA, XATTR_NAME_LMV, and XATTR_NAME_LOV.
Referenced by mdd_migrate().
static int mdd_name_check (struct mdd_device * m, const struct lu_name * ln) [inline, static]
Definition at line 61 of file mdd_dir.c.
References dt_device_param::ddp_max_name_len, lu_name::ln_namelen, lu_name_is_valid(), and mdd_device::mdd_dt_conf.
Referenced by mdd_create_sanity_check(), mdd_link_sanity_check(), and mdd_rename().
static int mdd_object_create (const struct lu_env * env, struct mdd_object * pobj, struct mdd_object * son, struct lu_attr * attr, struct md_op_spec * spec, struct lu_buf * acl_buf, struct lu_buf * def_acl_buf, struct dt_allocation_hint * hint, struct thandle * handle) [static]
Create a metadata object and initialize it, set acl, xattr.
Definition at line 2189 of file mdd_dir.c.
References buf, CFS_CAP_SYS_RESOURCE_MASK, dt_body_operations::dbo_write, dt_object::do_body_ops, GOTO, lu_attr::la_mode, lu_buf::lb_len, lu_ucred_assert(), mdd_buf_get_const(), mdd_object_child(), mdd_object_create_internal(), mdd_object_initialize(), mdd_write_lock(), mdd_write_unlock(), mdo2fid(), mdo_destroy(), mdo_ref_del(), mdo_xattr_set(), MDS_OPEN_HAS_EA, MOR_TGT_CHILD, md_op_spec::no_create, RETURN, md_op_spec::sp_cr_flags, md_op_spec::sp_ea, md_op_spec::sp_symname, md_op_spec::u, lu_ucred::uc_cap, unlikely, XATTR_NAME_ACL_ACCESS, XATTR_NAME_ACL_DEFAULT, XATTR_NAME_LMV, and XATTR_NAME_LOV.
Referenced by mdd_create(), and mdd_migrate_create().
static int mdd_object_initialize (const struct lu_env * env, const struct lu_fid * pfid, struct mdd_object * child, struct lu_attr * attr, struct thandle * handle, const struct md_op_spec * spec) [static]
Definition at line 1899 of file mdd_dir.c.
References __mdd_index_insert_only(), dot, dotdot, ENTRY, lu_attr::la_mode, mdo2fid(), mdo_ref_add(), mdo_ref_del(), and RETURN.
Referenced by mdd_object_create().
static int mdd_parent_fid (const struct lu_env * env, struct mdd_object * obj, const struct lu_attr * attr, struct lu_fid * fid) [inline, static]
Get parent FID of the directory.
Read parent FID from linkEA, if that fails, then do lookup dotdot to get the parent FID.
Parameters:
[in] env execution environment
[in] obj object from which to find the parent FID
[in] attr attribute of the object
[out] fid fid to get the parent FID
Return values:
0 if getting the parent FID succeeds.
negative errno if getting the parent FID fails.
Definition at line 141 of file mdd_dir.c.
References __mdd_lookup(), buf, ENTRY, fid_is_sane(), GOTO, LASSERT, lu_buf::lb_buf, linkea_data::ld_buf, linkea_data::ld_lee, linkea_data::ld_leh, linkea_data::ld_reclen, link_ea_header::leh_reccount, likely, linkea_entry_unpack(), lookup(), lu_buf_check_and_alloc(), mdd_env_info(), mdd_links_read(), mdd_object_type(), mdd_object::mod_obj, mdd_thread_info::mti_link_buf, and RETURN.
Referenced by mdd_is_parent().
static int mdd_rename (const struct lu_env * env, struct md_object * src_pobj, struct md_object * tgt_pobj, const struct lu_fid * lf, const struct lu_name * lsname, struct md_object * tobj, const struct lu_name * ltname, struct md_attr * ma) [static]
Definition at line 2759 of file mdd_dir.c.
References __mdd_index_delete(), __mdd_index_delete_only(), __mdd_index_insert(), __mdd_index_insert_only(), CERROR, CL_RENAME, cleanup(), CLF_RENAME_LAST, CLF_RENAME_LAST_EXISTS, CWARN, DFID, dotdot, ENTRY, EXIT, GOTO, lu_attr::la_ctime, LA_CTIME, lu_attr::la_mode, LA_MTIME, lu_attr::la_mtime, lu_attr::la_nlink, lu_attr::la_valid, LASSERT, lu_name::ln_name, lu_fid_eq(), md_attr::ma_attr, MA_INODE, md_attr::ma_valid, md2mdd_obj(), mdd2obd_dev(), mdd_changelog_ns_store(), mdd_declare_rename(), mdd_env_info(), MDD_ENV_VAR, mdd_finish_unlink(), mdd_hsm_archive_exists(), mdd_is_dead_obj(), mdd_la_get(), mdd_linkea_prepare(), mdd_links_add(), mdd_links_rename(), mdd_name_check(), mdd_object_exists(), mdd_object_fid(), mdd_object_find(), mdd_object_put(), mdd_object_type(), mdd_rename_order(), mdd_rename_sanity_check(), mdd_trans_create(), mdd_trans_start(), mdd_trans_stop(), mdd_update_time(), mdd_write_lock(), mdd_write_unlock(), mdo2fid(), mdo2mdd(), mdo_ref_add(), mdo_ref_del(), MOR_SRC_CHILD, MOR_TGT_CHILD, mdd_thread_info::mti_la_for_fix, mdd_thread_info::mti_link_data, PFID, RETURN, and stop.
static int mdd_rename_order (const struct lu_env * env, struct mdd_device * mdd, struct mdd_object * src_pobj, const struct lu_attr * pattr, struct mdd_object * tgt_pobj) [static]
Definition at line 2563 of file mdd_dir.c.
References ENTRY, lu_fid_eq(), mdd_is_parent(), MDD_RN_SAME, MDD_RN_SRCTGT, MDD_RN_TGTSRC, mdd_device::mdd_root_fid, mdo2fid(), and RETURN.
Referenced by mdd_rename().
static int mdd_rename_sanity_check (const struct lu_env * env, struct mdd_object * src_pobj, const struct lu_attr * pattr, struct mdd_object * tgt_pobj, const struct lu_attr * tpattr, struct mdd_object * sobj, const struct lu_attr * cattr, struct mdd_object * tobj, const struct lu_attr * tattr) [static]
Definition at line 2597 of file mdd_dir.c.
References __mdd_may_link(), ENTRY, lu_attr::la_mode, LASSERT, mdd_may_create(), mdd_may_delete(), and RETURN.
Referenced by mdd_migrate_sanity_check(), and mdd_rename().
static int mdd_unlink (const struct lu_env * env, struct md_object * pobj, struct md_object * cobj, const struct lu_name * lname, struct md_attr * ma, int no_name) [static]
Delete name entry and the object.
Note: no_name == 1 means it only destory the object, i.e. name_entry does not exist for this object, and it could only happen during resending of remote unlink. see the comments in mdt_reint_unlink. Unfortunately, lname is also needed in this case(needed by changelog), so we have to add another parameter(no_name)here. XXX: this is only needed in DNE phase I, on Phase II, the ENOENT failure should be able to be fixed by redo mechanism.
Definition at line 1612 of file mdd_dir.c.
References __mdd_index_delete(), __mdd_index_insert_only(), CL_RMDIR, CL_UNLINK, cleanup(), CLF_UNLINK_HSM_EXISTS, CLF_UNLINK_LAST, ENTRY, EXIT, GOTO, lu_attr::la_ctime, LA_CTIME, lu_attr::la_mode, LA_MTIME, lu_attr::la_mtime, lu_attr::la_nlink, lu_attr::la_valid, LASSERT, likely, lu_name::ln_name, md_attr::ma_attr, MA_INODE, md_attr::ma_valid, md2mdd_obj(), mdd_changelog_ns_store(), mdd_declare_unlink(), mdd_env_info(), MDD_ENV_VAR, mdd_finish_unlink(), mdd_hsm_archive_exists(), mdd_la_get(), mdd_object_exists(), mdd_object_type(), mdd_trans_create(), mdd_trans_start(), mdd_trans_stop(), mdd_unlink_sanity_check(), mdd_update_time(), mdd_write_lock(), mdd_write_unlock(), mdo2fid(), mdo2mdd(), mdo_ref_del(), mdd_object::mod_count, MOR_TGT_CHILD, mdd_thread_info::mti_la_for_fix, name, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_DANGLING2, OBD_FAIL_LFSCK_MUL_REF, OBD_FAIL_LFSCK_NO_NAMEENTRY, RETURN, stop, and unlikely.
int mdd_unlink_sanity_check (const struct lu_env * env, struct mdd_object * pobj, const struct lu_attr * pattr, struct mdd_object * cobj, const struct lu_attr * cattr)
Definition at line 1503 of file mdd_dir.c.
References ENTRY, mdd_may_delete(), and RETURN.
Referenced by mdd_unlink().
static int mdd_update_linkea (const struct lu_env * env, struct mdd_object * mdd_pobj, struct mdd_object * mdd_sobj, struct mdd_object * mdd_tobj, const struct lu_name * child_name, struct linkea_data * ldata, struct thandle * handle) [static]
Definition at line 3822 of file mdd_dir.c.
References mdd_update_linkea_internal().
Referenced by mdd_migrate_update_name().
static int mdd_update_linkea_internal (const struct lu_env * env, struct mdd_object * mdd_pobj, struct mdd_object * mdd_sobj, struct mdd_object * mdd_tobj, const struct lu_name * child_name, struct linkea_data * ldata, struct thandle * handle, int declare) [static]
Definition at line 3150 of file mdd_dir.c.
References __mdd_index_delete(), __mdd_index_insert(), CDEBUG, CWARN, D_INFO, DFID, DNAME, ENTRY, GOTO, LASSERT, linkea_data::ld_buf, linkea_data::ld_lee, linkea_data::ld_leh, linkea_data::ld_reclen, link_ea_header::leh_reccount, linkea_del_buf(), linkea_entry_unpack(), lu_name::ln_name, lu_name::ln_namelen, lu_fid_eq(), mdd2obd_dev(), mdd_env_info(), mdd_lookup(), mdd_object_exists(), mdd_object_fid(), mdd_object_find(), mdd_object_put(), mdd_object_type(), mdd_write_lock(), mdd_write_unlock(), mdo2mdd(), mdo_declare_index_delete(), mdo_declare_index_insert(), mdo_declare_ref_add(), mdo_declare_ref_del(), mdo_ref_add(), mdo_ref_del(), mdd_object::mod_obj, MOR_SRC_CHILD, MOR_TGT_CHILD, mdd_thread_info::mti_fid, mdd_thread_info::mti_key, PFID, PNAME, and RETURN.
Referenced by mdd_declare_update_linkea(), and mdd_update_linkea().
Variable Documentation
const char dot[] = "." [static]
Definition at line 52 of file mdd_dir.c.
const char dotdot[] = ".." [static]
Definition at line 53 of file mdd_dir.c.
struct lu_name lname_dotdot [static]
Initial value:
 {
        (char *) dotdot,
        sizeof(dotdot) - 1
}
Definition at line 55 of file mdd_dir.c.
struct md_dir_operations mdd_dir_ops
Initial value:
 {
        .mdo_is_subdir     = mdd_is_subdir,
        .mdo_lookup        = mdd_lookup,
        .mdo_create        = mdd_create,
        .mdo_rename        = mdd_rename,
        .mdo_link          = mdd_link,
        .mdo_unlink        = mdd_unlink,
        .mdo_create_data   = mdd_create_data,
        .mdo_migrate       = mdd_migrate,
}
Definition at line 4311 of file mdd_dir.c.
Referenced by mdd_object_alloc().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.