Lustre: lustre/mdd/mdd_permission.c File Reference
lustre/mdd/mdd_permission.c File Reference
#include <obd_class.h>
#include <lustre_ver.h>
#include <lprocfs_status.h>
#include <lustre_mds.h>
#include <lustre_idmap.h>
#include "mdd_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_MDS
Functions
static int mdd_check_acl (const struct lu_env *env, struct mdd_object *obj, const struct lu_attr *la, int mask)
int __mdd_permission_internal (const struct lu_env *env, struct mdd_object *obj, const struct lu_attr *la, int mask, int role)
int mdd_permission (const struct lu_env *env, struct md_object *pobj, struct md_object *cobj, struct md_attr *ma, int mask)
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 44 of file mdd_permission.c.
Function Documentation
int __mdd_permission_internal (const struct lu_env * env, struct mdd_object * obj, const struct lu_attr * la, int mask, int role)
Definition at line 240 of file mdd_permission.c.
References CDEBUG, CFS_CAP_DAC_OVERRIDE, CFS_CAP_DAC_READ_SEARCH, D_SEC, ENTRY, lu_attr::la_flags, lu_attr::la_gid, lu_attr::la_mode, lu_attr::la_uid, LASSERT, lu_ucred(), LUSTRE_IMMUTABLE_FL, lustre_in_group_p(), md_capable(), mdd_check_acl(), mdd_read_lock(), mdd_read_unlock(), RETURN, lu_ucred::uc_fsuid, lu_ucred::uc_valid, UCRED_INIT, and UCRED_INVALID.
Referenced by mdd_permission_internal(), and mdd_permission_internal_locked().
static int mdd_check_acl (const struct lu_env * env, struct mdd_object * obj, const struct lu_attr * la, int mask) [static]
Definition at line 204 of file mdd_permission.c.
References posix_acl_xattr_header::a_entries, ENTRY, lu_buf::lb_buf, lu_buf::lb_len, lu_ucred_assert(), mdd_buf_get(), mdd_env_info(), mdo_xattr_get(), RETURN, and XATTR_NAME_ACL_ACCESS.
Referenced by __mdd_permission_internal().
int mdd_permission (const struct lu_env * env, struct md_object * pobj, struct md_object * cobj, struct md_attr * ma, int mask)
Definition at line 307 of file mdd_permission.c.
References accmode(), CFS_CAP_FOWNER, ENTRY, lu_attr::la_uid, LASSERT, likely, lu_ucred_assert(), MAY_RGETFACL, md2mdd_obj(), md_capable(), MDD_ENV_VAR, mdd_la_get(), mdd_permission_internal_locked(), MDS_OPEN_CROSS, MOR_TGT_CHILD, RETURN, lu_ucred::uc_fsuid, and unlikely.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.