Lustre: lustre/mdd/mdd_device.c File Reference
lustre/mdd/mdd_device.c File Reference
#include <linux/module.h>
#include <linux/kthread.h>
#include <obd_class.h>
#include <lustre_ioctl.h>
#include <lustre_mds.h>
#include <obd_support.h>
#include <lu_object.h>
#include <lustre_param.h>
#include <lustre_fid.h>
#include "mdd_internal.h"
Data Structures
struct mdd_changelog_user_data
Defines
#define DEBUG_SUBSYSTEM S_MDS
#define MCUD_UNREGISTER -1LL
Functions
static int mdd_connect_to_next (const struct lu_env *env, struct mdd_device *m, const char *nextdev)
static int mdd_init0 (const struct lu_env *env, struct mdd_device *mdd, struct lu_device_type *t, struct lustre_cfg *lcfg)
static struct lu_device * mdd_device_fini (const struct lu_env *env, struct lu_device *d)
static int changelog_init_cb (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *hdr, void *data)
static int changelog_user_init_cb (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *hdr, void *data)
static int llog_changelog_cancel_cb (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *hdr, void *data)
static int llog_changelog_cancel (const struct lu_env *env, struct llog_ctxt *ctxt, struct llog_cookie *cookies, int flags)
static int mdd_changelog_write_header (const struct lu_env *env, struct mdd_device *mdd, int markerflags)
Add a CL_MARK record to the changelog.
static int mdd_changelog_on (const struct lu_env *env, struct mdd_device *mdd)
static int mdd_changelog_off (const struct lu_env *env, struct mdd_device *mdd)
static int mdd_changelog_llog_init (const struct lu_env *env, struct mdd_device *mdd)
static int mdd_changelog_init (const struct lu_env *env, struct mdd_device *mdd)
static void mdd_changelog_fini (const struct lu_env *env, struct mdd_device *mdd)
static int mdd_changelog_llog_cancel (const struct lu_env *env, struct mdd_device *mdd, long long endrec)
Remove entries with indicies up to and including endrec from the changelog.
static int obf_lookup (const struct lu_env *env, struct md_object *p, const struct lu_name *lname, struct lu_fid *f, struct md_op_spec *spec)
Lookup method for "fid" object.
static int mdd_dummy_create (const struct lu_env *env, struct md_object *pobj, const struct lu_name *lname, struct md_object *child, struct md_op_spec *spec, struct md_attr *ma)
static int mdd_dummy_rename (const struct lu_env *env, struct md_object *src_pobj, struct md_object *tgt_pobj, const struct lu_fid *lf, const struct lu_name *lsname, struct md_object *tobj, const struct lu_name *ltname, struct md_attr *ma)
static int mdd_dummy_link (const struct lu_env *env, struct md_object *tgt_obj, struct md_object *src_obj, const struct lu_name *lname, struct md_attr *ma)
static int mdd_dummy_unlink (const struct lu_env *env, struct md_object *pobj, struct md_object *cobj, const struct lu_name *lname, struct md_attr *ma, int no_name)
static struct md_object * mdo_locate (const struct lu_env *env, struct md_device *md, const struct lu_fid *fid)
static int mdd_lpf_setup (const struct lu_env *env, struct mdd_device *m)
static int mdd_obf_setup (const struct lu_env *env, struct mdd_device *m)
Create special in-memory "fid" object for open-by-fid.
static void mdd_dot_lustre_cleanup (const struct lu_env *env, struct mdd_device *m)
static int mdd_dot_lustre_setup (const struct lu_env *env, struct mdd_device *m)
Setup ".lustre" directory object.
static int mdd_hsm_actions_llog_init (const struct lu_env *env, struct mdd_device *m)
set llog methods and create LLOG_AGENT_ORIG_CTXT llog object in obd_device
static int mdd_hsm_actions_llog_fini (const struct lu_env *env, struct mdd_device *m)
cleanup the context created by llog_setup_named()
static void mdd_device_shutdown (const struct lu_env *env, struct mdd_device *m, struct lustre_cfg *cfg)
static int mdd_process_config (const struct lu_env *env, struct lu_device *d, struct lustre_cfg *cfg)
static int mdd_recovery_complete (const struct lu_env *env, struct lu_device *d)
int mdd_local_file_create (const struct lu_env *env, struct mdd_device *mdd, const struct lu_fid *pfid, const char *name, __u32 mode, struct lu_fid *fid)
static int mdd_lfsck_out_notify (const struct lu_env *env, void *data, enum lfsck_events event)
static int mdd_prepare (const struct lu_env *env, struct lu_device *pdev, struct lu_device *cdev)
static int mdd_root_get (const struct lu_env *env, struct md_device *m, struct lu_fid *f)
static int mdd_statfs (const struct lu_env *env, struct md_device *m, struct obd_statfs *sfs)
static int mdd_maxeasize_get (const struct lu_env *env, struct md_device *m, int *easize)
static int mdd_llog_ctxt_get (const struct lu_env *env, struct md_device *m, int idx, void **h)
static struct lu_device * mdd_device_free (const struct lu_env *env, struct lu_device *lu)
static struct lu_device * mdd_device_alloc (const struct lu_env *env, struct lu_device_type *t, struct lustre_cfg *lcfg)
static int mdd_obd_connect (const struct lu_env *env, struct obd_export **exp, struct obd_device *obd, struct obd_uuid *cluuid, struct obd_connect_data *data, void *localdata)
static int mdd_obd_disconnect (struct obd_export *exp)
static int mdd_obd_get_info (const struct lu_env *env, struct obd_export *exp, __u32 keylen, void *key, __u32 *vallen, void *val)
static int mdd_obd_set_info_async (const struct lu_env *env, struct obd_export *exp, __u32 keylen, void *key, __u32 vallen, void *val, struct ptlrpc_request_set *set)
static int mdd_changelog_user_register (const struct lu_env *env, struct mdd_device *mdd, int *id)
static int mdd_changelog_user_purge_cb (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *hdr, void *data)
Two things: 1.
static int mdd_changelog_user_purge (const struct lu_env *env, struct mdd_device *mdd, int id, long long endrec)
static int mdd_iocontrol (const struct lu_env *env, struct md_device *m, unsigned int cmd, int len, void *karg)
mdd_iocontrol May be called remotely from mdt_iocontrol_handle or locally from mdt_iocontrol.
LU_TYPE_INIT_FINI (mdd,&mdd_thread_key)
LU_KEY_INIT (mdd, struct mdd_thread_info)
static void mdd_key_fini (const struct lu_context *ctx, struct lu_context_key *key, void *data)
LU_CONTEXT_KEY_DEFINE (mdd, LCT_MD_THREAD)
int mdd_generic_thread_start (struct mdd_generic_thread *thread, int(*func)(void *), void *data, char *name)
void mdd_generic_thread_stop (struct mdd_generic_thread *thread)
static int __init mdd_init (void)
static void __exit mdd_exit (void)
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Meta-data Device Driver ("LUSTRE_MDD_NAME")")
MODULE_VERSION (LUSTRE_VERSION_STRING)
MODULE_LICENSE ("GPL")
module_init (mdd_init)
module_exit (mdd_exit)
Variables
static struct md_device_operations mdd_ops
static struct lu_device_type mdd_device_type
static const char mdd_root_dir_name [] = "ROOT"
static const char mdd_obf_dir_name [] = "fid"
static const char mdd_lpf_dir_name [] = "lost+found"
struct kmem_cache * mdd_object_kmem
static struct lu_kmem_descr mdd_caches []
static struct llog_operations changelog_orig_logops
static struct md_dir_operations mdd_obf_dir_ops
static struct md_dir_operations mdd_lpf_dir_ops
static struct llog_operations hsm_actions_logops
struct lu_device_operations mdd_lu_ops
static struct obd_ops mdd_obd_device_ops
static struct
lu_device_type_operations mdd_device_type_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 43 of file mdd_device.c.
#define MCUD_UNREGISTER -1LL
Definition at line 1326 of file mdd_device.c.
Referenced by mdd_changelog_user_purge(), mdd_changelog_user_purge_cb(), and mdd_iocontrol().
Function Documentation
static int changelog_init_cb (const struct lu_env * env, struct llog_handle * llh, struct llog_rec_hdr * hdr, void * data) [static]
Definition at line 169 of file mdd_device.c.
References CDEBUG, CHANGELOG_REC, changelog_rec_name(), llog_changelog_rec::cr, llog_changelog_rec::cr_hdr, changelog_rec::cr_index, changelog_rec::cr_namelen, changelog_rec::cr_type, D_INFO, DOSTID, LASSERT, llog_handle::lgh_hdr, llog_handle::lgh_id, llog_logid::lgl_oi, llog_log_hdr::llh_flags, LLOG_F_IS_PLAIN, LLOG_PROC_BREAK, LPU64, llog_rec_hdr::lrh_index, llog_rec_hdr::lrh_type, mdd_changelog::mc_index, mdd_device::mdd_cl, and POSTID.
Referenced by mdd_changelog_llog_init().
static int changelog_user_init_cb (const struct lu_env * env, struct llog_handle * llh, struct llog_rec_hdr * hdr, void * data) [static]
Definition at line 188 of file mdd_device.c.
References CDEBUG, CHANGELOG_USER_REC, llog_changelog_user_rec::cur_endrec, llog_changelog_user_rec::cur_hdr, llog_changelog_user_rec::cur_id, D_INFO, DOSTID, LASSERT, llog_handle::lgh_hdr, llog_handle::lgh_id, llog_logid::lgl_oi, llog_log_hdr::llh_flags, LLOG_F_IS_PLAIN, LLOG_PROC_BREAK, LPU64, llog_rec_hdr::lrh_index, llog_rec_hdr::lrh_type, mdd_changelog::mc_index, mdd_changelog::mc_lastuser, mdd_changelog::mc_user_lock, mdd_device::mdd_cl, and POSTID.
Referenced by mdd_changelog_llog_init().
static int llog_changelog_cancel (const struct lu_env * env, struct llog_ctxt * ctxt, struct llog_cookie * cookies, int flags) [static]
Definition at line 241 of file mdd_device.c.
References CERROR, DOSTID, ENTRY, LASSERT, llog_handle::lgh_hdr, llog_handle::lgh_id, llog_handle::lgh_last_idx, llog_logid::lgl_oi, llog_log_hdr::llh_flags, llog_cat_process(), llog_changelog_cancel_cb(), LLOG_F_IS_CAT, llog_ctxt::loc_handle, llog_ctxt::loc_obd, obd_device::obd_name, POSTID, and RETURN.
Referenced by mdd_init().
static int llog_changelog_cancel_cb (const struct lu_env * env, struct llog_handle * llh, struct llog_rec_hdr * hdr, void * data) [static]
Definition at line 212 of file mdd_device.c.
References llog_changelog_rec::cr, changelog_rec::cr_index, ENTRY, LASSERT, llog_cookie::lgc_index, llog_cookie::lgc_lgl, llog_handle::lgh_hdr, llog_handle::lgh_id, llog_log_hdr::llh_flags, llog_cat_cancel_records(), LLOG_F_IS_PLAIN, LLOG_PROC_BREAK, llog_rec_hdr::lrh_index, llog_handle::phd, plain_handle_data::phd_cat_handle, RETURN, and llog_handle::u.
Referenced by llog_changelog_cancel().
LU_CONTEXT_KEY_DEFINE (mdd , LCT_MD_THREAD)
LU_KEY_INIT (mdd , struct mdd_thread_info)
LU_TYPE_INIT_FINI (mdd , & mdd_thread_key)
static void mdd_changelog_fini (const struct lu_env * env, struct mdd_device * mdd) [static]
Definition at line 434 of file mdd_device.c.
References llog_cat_close(), LLOG_CHANGELOG_ORIG_CTXT, LLOG_CHANGELOG_USER_ORIG_CTXT, llog_cleanup(), llog_get_context(), llog_ctxt::loc_handle, mdd_changelog::mc_flags, mdd2obd_dev(), and mdd_device::mdd_cl.
Referenced by mdd_device_shutdown(), and mdd_prepare().
static int mdd_changelog_init (const struct lu_env * env, struct mdd_device * mdd) [static]
Definition at line 411 of file mdd_device.c.
References CERROR, cfs_time_current_64, CHANGELOG_DEFMASK, CLM_ERR, mdd_changelog::mc_flags, mdd_changelog::mc_index, mdd_changelog::mc_lastuser, mdd_changelog::mc_lock, mdd_changelog::mc_mask, mdd_changelog::mc_starttime, mdd_changelog::mc_user_lock, mdd2obd_dev(), mdd_changelog_llog_init(), mdd_device::mdd_cl, and obd_device::obd_name.
Referenced by mdd_prepare().
static int mdd_changelog_llog_cancel (const struct lu_env * env, struct mdd_device * mdd, long long endrec) [static]
Remove entries with indicies up to and including endrec from the changelog.
Parameters:
mdd
endrec
Return values:
0 ok
Definition at line 461 of file mdd_device.c.
References cfs_time_current_64, CLM_PURGE, llog_cancel(), LLOG_CHANGELOG_ORIG_CTXT, llog_ctxt_put(), llog_get_context(), mdd_changelog::mc_index, mdd_changelog::mc_lock, mdd_changelog::mc_starttime, mdd2obd_dev(), mdd_changelog_write_header(), and mdd_device::mdd_cl.
Referenced by mdd_changelog_user_purge().
static int mdd_changelog_llog_init (const struct lu_env * env, struct mdd_device * mdd) [static]
Definition at line 312 of file mdd_device.c.
References CDEBUG, CERROR, CHANGELOG_CATALOG, changelog_init_cb(), changelog_orig_logops, changelog_user_init_cb(), CHANGELOG_USERS, D_IOCTL, lvfs_run_ctxt::dt, ENTRY, GOTO, LASSERT, llog_cat_add_rec(), llog_cat_close(), llog_cat_declare_add_rec(), llog_cat_reverse_process(), LLOG_CHANGELOG_ORIG_CTXT, LLOG_CHANGELOG_USER_ORIG_CTXT, llog_cleanup(), llog_ctxt_put(), LLOG_F_IS_CAT, llog_get_context(), llog_init_handle(), llog_open_create(), llog_setup(), llog_ctxt::loc_handle, LPU64, mdd_changelog::mc_index, mdd_changelog::mc_lastuser, mdd2obd_dev(), mdd_device::mdd_bottom, mdd_changelog_on(), mdd_device::mdd_cl, OBD_FAIL_CHECK, OBD_FAIL_MDS_CHANGELOG_INIT, obd_device::obd_lvfs_ctxt, obd_device::obd_name, obd_device::obd_olg, OBD_SET_CTXT_MAGIC(), and RETURN.
Referenced by mdd_changelog_init().
static int mdd_changelog_off (const struct lu_env * env, struct mdd_device * mdd) [static]
Definition at line 296 of file mdd_device.c.
References CLM_FINI, CLM_ON, LCONSOLE_INFO, mdd_changelog::mc_flags, mdd_changelog::mc_lock, mdd2obd_dev(), mdd_changelog_write_header(), and mdd_device::mdd_cl.
Referenced by mdd_changelog_user_purge().
static int mdd_changelog_on (const struct lu_env * env, struct mdd_device * mdd) [static]
Definition at line 273 of file mdd_device.c.
References CERROR, CLM_ERR, CLM_ON, CLM_START, LCONSOLE_INFO, mdd_changelog::mc_flags, mdd_changelog::mc_lock, mdd2obd_dev(), mdd_changelog_write_header(), and mdd_device::mdd_cl.
Referenced by mdd_changelog_llog_init(), and mdd_changelog_user_register().
static int mdd_changelog_user_purge (const struct lu_env * env, struct mdd_device * mdd, int id, long long endrec) [static]
Definition at line 1389 of file mdd_device.c.
References CDEBUG, CHANGELOG_USER_PREFIX, CWARN, D_IOCTL, ENTRY, LASSERT, llog_handle::lgh_hdr, llog_log_hdr::llh_flags, llog_cat_process(), LLOG_CHANGELOG_USER_ORIG_CTXT, llog_ctxt_put(), LLOG_F_IS_CAT, llog_get_context(), llog_ctxt::loc_handle, LPD64, mdd_changelog::mc_index, mdd_changelog::mc_lock, mdd_changelog_user_data::mcud_endrec, mdd_changelog_user_data::mcud_id, mdd_changelog_user_data::mcud_minid, mdd_changelog_user_data::mcud_minrec, MCUD_UNREGISTER, mdd_changelog_user_data::mcud_usercount, mdd2obd_dev(), mdd_changelog_llog_cancel(), mdd_changelog_off(), mdd_changelog_user_purge_cb(), mdd_device::mdd_cl, and RETURN.
Referenced by mdd_iocontrol().
static int mdd_changelog_user_purge_cb (const struct lu_env * env, struct llog_handle * llh, struct llog_rec_hdr * hdr, void * data) [static]
Two things: 1.
Find the smallest record everyone is willing to purge 2. Update the last purgeable record for this user
Definition at line 1332 of file mdd_device.c.
References CDEBUG, llog_changelog_user_rec::cur_endrec, llog_changelog_user_rec::cur_id, D_IOCTL, ENTRY, LASSERT, llog_cookie::lgc_index, llog_cookie::lgc_lgl, llog_handle::lgh_hdr, llog_handle::lgh_id, llog_log_hdr::llh_flags, llog_cat_cancel_records(), LLOG_F_IS_PLAIN, llog_write(), LPU64, llog_rec_hdr::lrh_index, max, mdd_changelog_user_data::mcud_endrec, mdd_changelog_user_data::mcud_found, mdd_changelog_user_data::mcud_id, mdd_changelog_user_data::mcud_minid, mdd_changelog_user_data::mcud_minrec, MCUD_UNREGISTER, mdd_changelog_user_data::mcud_usercount, llog_handle::phd, plain_handle_data::phd_cat_handle, RETURN, and llog_handle::u.
Referenced by mdd_changelog_user_purge().
static int mdd_changelog_user_register (const struct lu_env * env, struct mdd_device * mdd, int * id) [static]
Definition at line 1273 of file mdd_device.c.
References CDEBUG, CERROR, CHANGELOG_USER_REC, llog_changelog_user_rec::cur_endrec, llog_changelog_user_rec::cur_hdr, llog_changelog_user_rec::cur_id, D_IOCTL, ENTRY, GOTO, llog_cat_add(), LLOG_CHANGELOG_USER_ORIG_CTXT, llog_ctxt_put(), llog_get_context(), llog_ctxt::loc_handle, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, mdd_changelog::mc_index, mdd_changelog::mc_lastuser, mdd_changelog::mc_user_lock, mdd2obd_dev(), mdd_changelog_on(), mdd_device::mdd_cl, OBD_ALLOC_PTR, OBD_FREE_PTR, and RETURN.
Referenced by mdd_iocontrol().
int mdd_changelog_write_header (const struct lu_env * env, struct mdd_device * mdd, int markerflags) [static]
Add a CL_MARK record to the changelog.
Parameters:
mdd
markerflags - CLM_*
Return values:
0 ok
Definition at line 510 of file mdd_device.c.
References buf, cfs_time_current_64, CHANGELOG_REC, changelog_rec_name(), changelog_rec_size(), CL_MARK, cl_time(), CLF_VERSION, llog_changelog_rec::cr, changelog_rec::cr_flags, llog_changelog_rec::cr_hdr, changelog_rec::cr_index, changelog_rec::cr_markerflags, changelog_rec::cr_namelen, changelog_rec::cr_time, changelog_rec::cr_type, ENTRY, LASSERT, lu_buf::lb_buf, llog_cat_add(), LLOG_CHANGELOG_ORIG_CTXT, llog_ctxt_put(), llog_data_len(), llog_get_context(), llog_ctxt::loc_handle, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, lu_buf_check_and_alloc(), mdd_changelog::mc_flags, mdd_changelog::mc_index, mdd_changelog::mc_lock, mdd_changelog::mc_mask, mdd_changelog::mc_starttime, mdd2obd_dev(), mdd_device::mdd_cl, mdd_env_info(), obd_device::obd_name, and RETURN.
Referenced by mdd_changelog_llog_cancel(), mdd_changelog_off(), and mdd_changelog_on().
static int mdd_connect_to_next (const struct lu_env * env, struct mdd_device * m, const char * nextdev) [static]
Definition at line 78 of file mdd_device.c.
References CERROR, class_name2obd(), ENTRY, obd_export::exp_obd, GOTO, LASSERT, lu_device::ld_site, lu_site::ls_bottom_dev, lu2dt_dev(), lu_dev_add_linkage(), LUSTRE_VERSION_CODE, mdd2lu_dev(), mdd_device::mdd_bottom, mdd_device::mdd_child, mdd_device::mdd_child_exp, OBD_ALLOC, obd_connect(), OBD_CONNECT_VERSION, OBD_FREE, obd_device::obd_lu_dev, obd_device::obd_uuid, obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_version, and RETURN.
Referenced by mdd_init0().
static struct lu_device* mdd_device_alloc (const struct lu_env * env, struct lu_device_type * t, struct lustre_cfg * lcfg) [static, read]
Definition at line 1149 of file mdd_device.c.
References md_device_init(), mdd2lu_dev(), mdd_device_free(), mdd_init0(), mdd_device::mdd_md_dev, and OBD_ALLOC_PTR.
static struct lu_device* mdd_device_fini (const struct lu_env * env, struct lu_device * d) [static, read]
Definition at line 157 of file mdd_device.c.
References lu_device::ld_site, lu2mdd_dev(), lu_dev_del_linkage(), and mdd_procfs_fini().
static struct lu_device* mdd_device_free (const struct lu_env * env, struct lu_device * lu) [static, read]
Definition at line 1137 of file mdd_device.c.
References ENTRY, LASSERT, lu_device::ld_ref, lu2mdd_dev(), md_device_fini(), mdd_device::mdd_md_dev, OBD_FREE_PTR, and RETURN.
Referenced by mdd_device_alloc().
static void mdd_device_shutdown (const struct lu_env * env, struct mdd_device * m, struct lustre_cfg * cfg) [static]
Definition at line 875 of file mdd_device.c.
References lfsck_degister(), local_oid_storage_fini(), lu_site_purge(), mdd2lu_dev(), mdd_device::mdd_bottom, mdd_changelog_fini(), mdd_device::mdd_child_exp, mdd_dot_lustre_cleanup(), mdd_generic_thread_stop(), mdd_hsm_actions_llog_fini(), mdd_device::mdd_los, mdd_device::mdd_orph_cleanup_thread, obd_disconnect(), and orph_index_fini().
Referenced by mdd_process_config().
static void mdd_dot_lustre_cleanup (const struct lu_env * env, struct mdd_device * m) [static]
Definition at line 740 of file mdd_device.c.
References mdd_device::mdd_dot_lustre, mdd_device::mdd_dot_lustre_objs, mdd_dot_lustre_objs::mdd_lpf, mdd_dot_lustre_objs::mdd_obf, and mdd_object_put().
Referenced by mdd_device_shutdown(), mdd_dot_lustre_setup(), and mdd_prepare().
static int mdd_dot_lustre_setup (const struct lu_env * env, struct mdd_device * m) [static]
Setup ".lustre" directory object.
Definition at line 758 of file mdd_device.c.
References CERROR, dot_lustre_name, ENTRY, GOTO, LASSERT, LU_DOT_LUSTRE_FID, lu_object_exists, md2mdd_obj(), mdd2obd_dev(), mdd_device::mdd_dot_lustre, mdd_dot_lustre_cleanup(), mdd_local_file_create(), mdd_lpf_setup(), mdd_device::mdd_md_dev, mdd_obf_setup(), mdd_device::mdd_root_fid, mdo_locate(), md_object::mo_lu, and RETURN.
Referenced by mdd_prepare().
static int mdd_dummy_create (const struct lu_env * env, struct md_object * pobj, const struct lu_name * lname, struct md_object * child, struct md_op_spec * spec, struct md_attr * ma) [static]
Definition at line 610 of file mdd_device.c.
static int mdd_dummy_link (const struct lu_env * env, struct md_object * tgt_obj, struct md_object * src_obj, const struct lu_name * lname, struct md_attr * ma) [static]
Definition at line 632 of file mdd_device.c.
static int mdd_dummy_rename (const struct lu_env * env, struct md_object * src_pobj, struct md_object * tgt_pobj, const struct lu_fid * lf, const struct lu_name * lsname, struct md_object * tobj, const struct lu_name * ltname, struct md_attr * ma) [static]
Definition at line 620 of file mdd_device.c.
static int mdd_dummy_unlink (const struct lu_env * env, struct md_object * pobj, struct md_object * cobj, const struct lu_name * lname, struct md_attr * ma, int no_name) [static]
Definition at line 641 of file mdd_device.c.
static void __exit mdd_exit (void) [static]
Definition at line 1624 of file mdd_device.c.
References class_unregister_type(), lu_kmem_fini(), and LUSTRE_MDD_NAME.
int mdd_generic_thread_start (struct mdd_generic_thread * thread, int(*)(void *) func, void * data, char * name)
Definition at line 1571 of file mdd_device.c.
References LASSERT, mdd_generic_thread::mgt_abort, mdd_generic_thread::mgt_data, mdd_generic_thread::mgt_finished, mdd_generic_thread::mgt_init, and mdd_generic_thread::mgt_started.
Referenced by mdd_orphan_cleanup().
void mdd_generic_thread_stop (struct mdd_generic_thread * thread)
Definition at line 1592 of file mdd_device.c.
References mdd_generic_thread::mgt_abort, mdd_generic_thread::mgt_finished, and mdd_generic_thread::mgt_init.
Referenced by mdd_device_shutdown().
static int mdd_hsm_actions_llog_fini (const struct lu_env * env, struct mdd_device * m) [static]
cleanup the context created by llog_setup_named()
Definition at line 858 of file mdd_device.c.
References ENTRY, LLOG_AGENT_ORIG_CTXT, llog_cat_close(), llog_cleanup(), llog_get_context(), llog_ctxt::loc_handle, mdd2obd_dev(), and RETURN.
Referenced by mdd_device_shutdown(), and mdd_prepare().
static int mdd_hsm_actions_llog_init (const struct lu_env * env, struct mdd_device * m) [static]
set llog methods and create LLOG_AGENT_ORIG_CTXT llog object in obd_device
Definition at line 809 of file mdd_device.c.
References CERROR, lvfs_run_ctxt::dt, ENTRY, GOTO, HSM_ACTIONS, hsm_actions_logops, LASSERT, LLOG_AGENT_ORIG_CTXT, llog_cat_close(), llog_cleanup(), llog_ctxt_put(), LLOG_F_IS_CAT, llog_get_context(), llog_init_handle(), llog_open_create(), llog_setup(), llog_ctxt::loc_handle, mdd2obd_dev(), mdd_device::mdd_bottom, obd_device::obd_lvfs_ctxt, obd_device::obd_name, obd_device::obd_olg, OBD_SET_CTXT_MAGIC(), and RETURN.
Referenced by mdd_prepare().
static int __init mdd_init (void) [static]
Definition at line 1600 of file mdd_device.c.
References changelog_orig_logops, class_register_type(), hsm_actions_logops, llog_cat_add_rec(), llog_cat_declare_add_rec(), llog_changelog_cancel(), llog_osd_ops, llog_operations::lop_add, llog_operations::lop_cancel, llog_operations::lop_declare_add, lu_kmem_fini(), lu_kmem_init(), and LUSTRE_MDD_NAME.
static int mdd_init0 (const struct lu_env * env, struct mdd_device * mdd, struct lu_device_type * t, struct lustre_cfg * lcfg) [static]
Definition at line 120 of file mdd_device.c.
References class_name2obd(), dt_conf_get(), ENTRY, lu_device::ld_obd, lu_device::ld_ops, lustre_cfg_string(), MAX_ATIME_DIFF, md_device::md_lu_dev, md_device::md_ops, mdd_device::mdd_atime_diff, mdd_device::mdd_child, mdd_device::mdd_child_exp, mdd_connect_to_next(), mdd_device::mdd_dt_conf, mdd_lu_ops, mdd_device::mdd_md_dev, mdd_ops, mdd_procfs_init(), mdd_device::mdd_sync_permission, obd_disconnect(), and RETURN.
Referenced by mdd_device_alloc().
static int mdd_iocontrol (const struct lu_env * env, struct md_device * m, unsigned int cmd, int len, void * karg) [static]
mdd_iocontrol May be called remotely from mdt_iocontrol_handle or locally from mdt_iocontrol.
Data may be freeform - remote handling doesn't enforce an obd_ioctl_data format (but local ioctl handler does).
Parameters:
cmd - ioc
len - data len
karg - ioctl data, in kernel space
Definition at line 1457 of file mdd_device.c.
References CERROR, changelog_setinfo::cs_id, changelog_setinfo::cs_recno, dt_device_param::ddp_mntopts, ENTRY, obd_ioctl_data::ioc_u32_1, obd_ioctl_data::ioc_version, lfsck_query(), lfsck_start(), lfsck_stop(), lu2mdd_dev(), MCUD_UNREGISTER, md_device::md_lu_dev, mdd_device::mdd_bottom, mdd_changelog_user_purge(), mdd_changelog_user_register(), mdd_device::mdd_dt_conf, OBD_IOC_CHANGELOG_CLEAR, OBD_IOC_CHANGELOG_DEREG, OBD_IOC_CHANGELOG_REG, OBD_IOC_GET_MNTOPT, OBD_IOC_QUERY_LFSCK, OBD_IOC_START_LFSCK, OBD_IOC_STOP_LFSCK, OBD_IOCTL_VERSION, and RETURN.
static void mdd_key_fini (const struct lu_context * ctx, struct lu_context_key * key, void * data) [static]
Definition at line 1557 of file mdd_device.c.
References lu_buf_free(), mdd_thread_info::mti_big_buf, mdd_thread_info::mti_link_buf, and OBD_FREE_PTR.
static int mdd_lfsck_out_notify (const struct lu_env * env, void * data, enum lfsck_events event) [static]
Definition at line 984 of file mdd_device.c.
Referenced by mdd_prepare().
static int mdd_llog_ctxt_get (const struct lu_env * env, struct md_device * m, int idx, void ** h) [static]
Definition at line 1128 of file mdd_device.c.
References llog_group_get_ctxt(), lu2mdd_dev(), md_device::md_lu_dev, and mdd2obd_dev().
int mdd_local_file_create (const struct lu_env * env, struct mdd_device * mdd, const struct lu_fid * pfid, const char * name, __u32 mode, struct lu_fid * fid)
Definition at line 950 of file mdd_device.c.
References dt_object::do_lu, dt_locate(), ENTRY, EXIT, fid_is_zero(), GOTO, LASSERT, local_file_find_or_create(), local_file_find_or_create_with_fid(), lu_object_fid(), lu_object_put(), lu_object_put_nocache(), mdd_device::mdd_bottom, mdd_device::mdd_los, RETURN, and unlikely.
Referenced by mdd_dot_lustre_setup(), mdd_lpf_setup(), mdd_obf_setup(), mdd_prepare(), and orph_index_init().
static int mdd_lpf_setup (const struct lu_env * env, struct mdd_device * m) [static]
Definition at line 685 of file mdd_device.c.
References ENTRY, LASSERT, LU_LPF_FID, lu_object_exists, md2mdd_obj(), mdd_device::mdd_dot_lustre, mdd_device::mdd_dot_lustre_objs, mdd_local_file_create(), mdd_dot_lustre_objs::mdd_lpf, mdd_lpf_dir_name, mdd_device::mdd_md_dev, mdd_object_fid(), mdo_locate(), md_object::mo_dir_ops, md_object::mo_lu, mdd_object::mod_obj, and RETURN.
Referenced by mdd_dot_lustre_setup().
static int mdd_maxeasize_get (const struct lu_env * env, struct md_device * m, int * easize) [static]
Definition at line 1117 of file mdd_device.c.
References dt_device_param::ddp_max_ea_size, ENTRY, lu2mdd_dev(), md_device::md_lu_dev, mdd_device::mdd_dt_conf, and RETURN.
static int mdd_obd_connect (const struct lu_env * env, struct obd_export ** exp, struct obd_device * obd, struct obd_uuid * cluuid, struct obd_connect_data * data, void * localdata) [static]
Definition at line 1177 of file mdd_device.c.
References CDEBUG, class_conn2export(), class_connect(), D_CONFIG, ENTRY, LASSERT, lu2mdd_dev(), mdd_device::mdd_connects, obd_device::obd_lu_dev, and RETURN.
static int mdd_obd_disconnect (struct obd_export * exp) [static]
Definition at line 1205 of file mdd_device.c.
References class_disconnect(), class_manual_cleanup(), ENTRY, obd_export::exp_obd, lu2mdd_dev(), mdd_device::mdd_connects, obd_device::obd_lu_dev, and RETURN.
static int mdd_obd_get_info (const struct lu_env * env, struct obd_export * exp, __u32 keylen, void * key, __u32 * vallen, void * val) [static]
Definition at line 1223 of file mdd_device.c.
References obd_export::exp_obd, KEY_IS, KEY_OSP_CONNECTED, LASSERT, lu2mdd_dev(), mdd_device::mdd_child_exp, obd_get_info(), obd_device::obd_lu_dev, obd_device::obd_set_up, obd_device::obd_stopping, and RETURN.
static int mdd_obd_set_info_async (const struct lu_env * env, struct obd_export * exp, __u32 keylen, void * key, __u32 vallen, void * val, struct ptlrpc_request_set * set) [static]
Definition at line 1245 of file mdd_device.c.
References obd_export::exp_obd, LASSERT, lu2mdd_dev(), mdd_device::mdd_child_exp, obd_device::obd_lu_dev, obd_set_info_async(), obd_device::obd_set_up, obd_device::obd_stopping, and RETURN.
static int mdd_obf_setup (const struct lu_env * env, struct mdd_device * m) [static]
Create special in-memory "fid" object for open-by-fid.
Definition at line 715 of file mdd_device.c.
References LASSERT, LU_OBF_FID, lu_object_exists, md2mdd_obj(), mdd_device::mdd_dot_lustre, mdd_device::mdd_dot_lustre_objs, mdd_local_file_create(), mdd_device::mdd_md_dev, mdd_dot_lustre_objs::mdd_obf, mdd_obf_dir_name, mdd_object_fid(), mdo_locate(), md_object::mo_dir_ops, md_object::mo_lu, mdd_object::mod_obj, and RETURN.
Referenced by mdd_dot_lustre_setup().
static int mdd_prepare (const struct lu_env * env, struct lu_device * pdev, struct lu_device * cdev) [static]
Definition at line 990 of file mdd_device.c.
References CERROR, dt_device::dd_lu_dev, dt_root_get(), ENTRY, lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, FID_SEQ_LOCAL_NAME, GOTO, lu_device::ld_ops, lu_device_operations::ldo_prepare, lfsck_register(), local_oid_storage_fini(), local_oid_storage_init(), lu2mdd_dev(), lu_root_fid(), mdd2obd_dev(), mdd_device::mdd_bottom, mdd_changelog_fini(), mdd_changelog_init(), mdd_device::mdd_child, mdd_dot_lustre_cleanup(), mdd_dot_lustre_setup(), mdd_hsm_actions_llog_fini(), mdd_hsm_actions_llog_init(), mdd_lfsck_out_notify(), mdd_local_file_create(), mdd_device::mdd_local_root_fid, mdd_device::mdd_los, mdd_root_dir_name, mdd_device::mdd_root_fid, mdd_seq_site(), orph_index_fini(), orph_index_init(), and RETURN.
static int mdd_process_config (const struct lu_env * env, struct lu_device * d, struct lustre_cfg * cfg) [static]
Definition at line 894 of file mdd_device.c.
References class_process_proc_param(), dt_device::dd_lu_dev, dt_conf_get(), ENTRY, GOTO, LCFG_CLEANUP, lustre_cfg::lcfg_command, LCFG_PARAM, LCFG_SETUP, lu_device::ld_ops, lu_device::ld_site, lu_device_operations::ldo_process_config, lu2mdd_dev(), lu_dev_del_linkage(), mdd2obd_dev(), mdd_device::mdd_child, mdd_device_shutdown(), mdd_device::mdd_dt_conf, obd_device::obd_vars, PARAM_MDD, and RETURN.
static int mdd_recovery_complete (const struct lu_env * env, struct lu_device * d) [static]
Definition at line 932 of file mdd_device.c.
References dt_device::dd_lu_dev, ENTRY, LASSERT, lu_device::ld_ops, lu_device_operations::ldo_recovery_complete, lu2mdd_dev(), mdd_device::mdd_child, mdd_orphan_cleanup(), and RETURN.
static int mdd_root_get (const struct lu_env * env, struct md_device * m, struct lu_fid * f) [static]
Definition at line 1089 of file mdd_device.c.
References ENTRY, lu2mdd_dev(), md_device::md_lu_dev, mdd_device::mdd_root_fid, and RETURN.
static int mdd_statfs (const struct lu_env * env, struct md_device * m, struct obd_statfs * sfs) [static]
Definition at line 1102 of file mdd_device.c.
References dt_device_operations::dt_statfs, ENTRY, lu2mdd_dev(), md_device::md_lu_dev, mdd_device::mdd_child, mdd_child_ops(), min_t, obd_statfs::os_namelen, and RETURN.
static struct md_object* mdo_locate (const struct lu_env * env, struct md_device * md, const struct lu_fid * fid) [static, read]
Definition at line 667 of file mdd_device.c.
References LASSERT, lu_device::ld_type, lu_object::lo_header, lu2md(), lu_object_find(), lu_object_locate(), and md_device::md_lu_dev.
Referenced by mdd_dot_lustre_setup(), mdd_lpf_setup(), and mdd_obf_setup().
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Meta-data Device Driver ("LUSTRE_MDD_NAME")")
module_exit (mdd_exit)
module_init (mdd_init)
MODULE_LICENSE ("GPL")
MODULE_VERSION (LUSTRE_VERSION_STRING)
static int obf_lookup (const struct lu_env * env, struct md_object * p, const struct lu_name * lname, struct lu_fid * f, struct md_op_spec * spec) [static]
Lookup method for "fid" object.
Only filenames with correct SEQ:OID format are valid. We also check if object with passed fid exists or not.
Definition at line 565 of file mdd_device.c.
References __u64, CWARN, DFID, dot_lustre_name, lu_fid::f_seq, fid_is_igif(), fid_is_norm(), fid_is_root(), fid_is_sane(), FID_SEQ_IGIF, FID_SEQ_IGIF_MAX, fid_seq_is_dot(), FID_SEQ_NORMAL, GOTO, lu_name::ln_name, LPX64, mdd2obd_dev(), mdd_obf_dir_name, mdd_object_exists(), mdd_object_find(), mdd_object_put(), mdo2mdd(), name, PFID, RFID, and SFID.
Variable Documentation
struct llog_operations changelog_orig_logops [static]
Definition at line 266 of file mdd_device.c.
Referenced by mdd_changelog_llog_init(), and mdd_init().
struct llog_operations hsm_actions_logops [static]
Definition at line 803 of file mdd_device.c.
Referenced by mdd_hsm_actions_llog_init(), and mdd_init().
struct lu_kmem_descr mdd_caches[] [static]
Initial value:
 {
        {
                .ckd_cache = &mdd_object_kmem,
                .ckd_name  = "mdd_obj",
                .ckd_size  = sizeof(struct mdd_object)
        },
        {
                .ckd_cache = NULL
        }
}
Definition at line 67 of file mdd_device.c.
static struct lu_device_type mdd_device_type [static, read]
Initial value:
 {
        .ldt_tags     = LU_DEVICE_MD,
        .ldt_name     = LUSTRE_MDD_NAME,
        .ldt_ops      = &mdd_device_type_ops,
        .ldt_ctx_tags = LCT_MD_THREAD
}
Definition at line 58 of file mdd_device.c.
struct lu_device_type_operations mdd_device_type_ops [static]
Initial value:
 {
        .ldto_init = mdd_type_init,
        .ldto_fini = mdd_type_fini,
        .ldto_start = mdd_type_start,
        .ldto_stop  = mdd_type_stop,
        .ldto_device_alloc = mdd_device_alloc,
        .ldto_device_free  = mdd_device_free,
        .ldto_device_fini    = mdd_device_fini
}
Definition at line 1534 of file mdd_device.c.
const char mdd_lpf_dir_name[] = "lost+found" [static]
Definition at line 62 of file mdd_device.c.
Referenced by mdd_lpf_setup().
struct md_dir_operations mdd_lpf_dir_ops [static]
Initial value:
 {
        .mdo_lookup = mdd_lookup,
        .mdo_create = mdd_dummy_create,
        .mdo_rename = mdd_dummy_rename,
        .mdo_link   = mdd_dummy_link,
        .mdo_unlink = mdd_dummy_unlink
}
Definition at line 659 of file mdd_device.c.
struct lu_device_operations mdd_lu_ops
Initial value:
 {
        .ldo_object_alloc      = mdd_object_alloc,
        .ldo_process_config    = mdd_process_config,
        .ldo_recovery_complete = mdd_recovery_complete,
        .ldo_prepare           = mdd_prepare,
}
Definition at line 1082 of file mdd_device.c.
Referenced by lu_device_is_mdd(), and mdd_init0().
struct obd_ops mdd_obd_device_ops [static]
Initial value:
 {
        .o_owner        = THIS_MODULE,
        .o_connect      = mdd_obd_connect,
        .o_disconnect   = mdd_obd_disconnect,
        .o_get_info     = mdd_obd_get_info,
        .o_set_info_async = mdd_obd_set_info_async,
}
Definition at line 1265 of file mdd_device.c.
const char mdd_obf_dir_name[] = "fid" [static]
Definition at line 61 of file mdd_device.c.
Referenced by mdd_obf_setup(), and obf_lookup().
struct md_dir_operations mdd_obf_dir_ops [static]
Initial value:
 {
        .mdo_lookup = obf_lookup,
        .mdo_create = mdd_dummy_create,
        .mdo_rename = mdd_dummy_rename,
        .mdo_link   = mdd_dummy_link,
        .mdo_unlink = mdd_dummy_unlink
}
Definition at line 651 of file mdd_device.c.
struct kmem_cache* mdd_object_kmem
Definition at line 65 of file mdd_device.c.
Referenced by mdd_object_alloc(), and mdd_object_free().
static struct md_device_operations mdd_ops [static, read]
Initial value:
 {
        .mdo_statfs         = mdd_statfs,
        .mdo_root_get       = mdd_root_get,
        .mdo_llog_ctxt_get  = mdd_llog_ctxt_get,
        .mdo_iocontrol      = mdd_iocontrol,
        .mdo_maxeasize_get  = mdd_maxeasize_get,
}
Definition at line 57 of file mdd_device.c.
Referenced by mdd_init0().
const char mdd_root_dir_name[] = "ROOT" [static]
Definition at line 60 of file mdd_device.c.
Referenced by mdd_prepare().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.