Lustre: lustre/mdt/mdt_hsm.c File Reference
lustre/mdt/mdt_hsm.c File Reference
#include "mdt_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_MDS
#define MDT_HSM_ALLOC_MAX (1 << 20)
#define MDT_HSM_ALLOC(ptr, size)
#define MDT_HSM_FREE(ptr, size) OBD_FREE_LARGE((ptr), (size))
Functions
int mdt_hsm_attr_set (struct mdt_thread_info *info, struct mdt_object *obj, const struct md_hsm *mh)
Update on-disk HSM attributes.
static bool mdt_hsm_is_admin (struct mdt_thread_info *info)
int mdt_hsm_progress (struct tgt_session_info *tsi)
Extract information coming from a copytool and asks coordinator to update a request status depending on the update content.
int mdt_hsm_ct_register (struct tgt_session_info *tsi)
int mdt_hsm_ct_unregister (struct tgt_session_info *tsi)
int mdt_hsm_state_get (struct tgt_session_info *tsi)
Retrieve the current HSM flags, archive id and undergoing HSM requests for the fid provided in RPC body.
int mdt_hsm_state_set (struct tgt_session_info *tsi)
Change HSM state and archive number of a file.
int mdt_hsm_action (struct tgt_session_info *tsi)
Retrieve undergoing HSM requests for the fid provided in RPC body.
int mdt_hsm_request (struct tgt_session_info *tsi)
Process the HSM actions described in a struct hsm_user_request.
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 38 of file mdt_hsm.c.
#define MDT_HSM_ALLOC (ptr, size)
Value:
do {                                            \
                if ((size) <= MDT_HSM_ALLOC_MAX)        \
                        OBD_ALLOC_LARGE((ptr), (size)); \
                else                                    \
                        (ptr) = NULL;                   \
        } while (0)
Definition at line 45 of file mdt_hsm.c.
Referenced by mdt_hsm_action(), and mdt_hsm_request().
#define MDT_HSM_ALLOC_MAX (1 << 20)
Definition at line 43 of file mdt_hsm.c.
#define MDT_HSM_FREE (ptr, size) OBD_FREE_LARGE((ptr), (size))
Definition at line 53 of file mdt_hsm.c.
Referenced by mdt_hsm_action(), and mdt_hsm_request().
Function Documentation
int mdt_hsm_action (struct tgt_session_info * tsi)
Retrieve undergoing HSM requests for the fid provided in RPC body.
Current requests are read from coordinator states.
This is MDS_HSM_ACTION RPC handler.
Definition at line 371 of file mdt_hsm.c.
References CERROR, cfs_size_round(), DFID, ENTRY, err_serious(), EXIT, GOTO, hsm_action_item::hai_action, hsm_action_item::hai_cookie, hsm_action_item::hai_extent, hsm_action_item::hai_fid, hai_first(), hsm_action_item::hai_gid, hsm_action_item::hai_len, hsm_action_list::hal_archive_id, hsm_action_list::hal_count, hsm_action_list::hal_flags, hsm_action_list::hal_fsname, hal_size(), HAL_VERSION, hsm_action_list::hal_version, hsm_current_action::hca_action, hsm_current_action::hca_location, hsm_current_action::hca_state, HPS_RUNNING, HPS_WAITING, HSMA_ARCHIVE, HSMA_CANCEL, HSMA_NONE, HSMA_REMOVE, HSMA_RESTORE, HUA_ARCHIVE, HUA_CANCEL, HUA_NONE, HUA_REMOVE, HUA_RESTORE, mdt_body::mbo_fid1, mdt_exit_ucred(), MDT_HSM_ALLOC, MDT_HSM_FREE, mdt_hsm_get_actions(), mdt_init_ucred(), mdt_obd_name(), mdt_thread_info_fini(), mdt_thread_info::mti_body, mdt_thread_info::mti_mdt, MTI_NAME_MAXLEN, obd_uuid2fsname(), PFID, req_capsule_server_get(), RETURN, RMF_MDS_HSM_CURRENT_ACTION, tsi2mdt_info(), tgt_session_info::tsi_mdt_body, and tgt_session_info::tsi_pill.
int mdt_hsm_attr_set (struct mdt_thread_info * info, struct mdt_object * obj, const struct md_hsm * mh)
Update on-disk HSM attributes.
Definition at line 58 of file mdt_hsm.c.
References buf, CLASSERT, ENTRY, lu_buf::lb_buf, lu_buf::lb_len, lustre_hsm2buf(), mdt_object_child(), mo_xattr_set(), mdt_thread_info::mti_buf, mdt_thread_info::mti_env, mdt_thread_info::mti_xattr_buf, RETURN, and XATTR_NAME_HSM.
Referenced by hsm_cdt_request_completed(), hsm_swap_layouts(), mdt_add_dirty_flag(), mdt_hsm_add_hal(), and mdt_hsm_state_set().
int mdt_hsm_ct_register (struct tgt_session_info * tsi)
Definition at line 146 of file mdt_hsm.c.
References ENTRY, err_serious(), obd_export::exp_client_uuid, GOTO, mdt_hsm_agent_register_mask(), mdt_hsm_is_admin(), mdt_thread_info_fini(), req_capsule_client_get(), RETURN, RMF_MDS_HSM_ARCHIVE, tsi2mdt_info(), tgt_session_info::tsi_exp, and tgt_session_info::tsi_pill.
int mdt_hsm_ct_unregister (struct tgt_session_info * tsi)
Definition at line 169 of file mdt_hsm.c.
References ENTRY, obd_export::exp_client_uuid, GOTO, mdt_hsm_agent_unregister(), mdt_hsm_is_admin(), mdt_thread_info_fini(), RETURN, tsi2mdt_info(), tgt_session_info::tsi_exp, and tgt_session_info::tsi_mdt_body.
static bool mdt_hsm_is_admin (struct mdt_thread_info * info) [inline, static]
Definition at line 81 of file mdt_hsm.c.
References CFS_CAP_SYS_ADMIN, md_capable(), mdt_exit_ucred(), mdt_init_ucred(), mdt_ucred(), and mdt_thread_info::mti_body.
Referenced by mdt_hsm_ct_register(), mdt_hsm_ct_unregister(), and mdt_hsm_progress().
int mdt_hsm_progress (struct tgt_session_info * tsi)
Extract information coming from a copytool and asks coordinator to update a request status depending on the update content.
Copytools could use this to report failure in their process.
This is HSM_PROGRESS RPC handler.
Definition at line 108 of file mdt_hsm.c.
References CDEBUG, D_HSM, DFID, ENTRY, err_serious(), GOTO, HP_FLAG_COMPLETED, HP_FLAG_RETRY, hsm_progress_kernel::hpk_cookie, hsm_progress_kernel::hpk_errval, hsm_progress_kernel::hpk_extent, hsm_progress_kernel::hpk_fid, hsm_progress_kernel::hpk_flags, hsm_extent::length, LPU64, LPX64, lustre_errno_ntoh(), mdt_hsm_coordinator_update(), mdt_hsm_is_admin(), mdt_thread_info_fini(), PFID, req_capsule_client_get(), RETURN, RMF_MDS_HSM_PROGRESS, tsi2mdt_info(), tgt_session_info::tsi_mdt_body, and tgt_session_info::tsi_pill.
int mdt_hsm_request (struct tgt_session_info * tsi)
Process the HSM actions described in a struct hsm_user_request.
The action described in hur will be send to coordinator to be saved and processed later or either handled directly if hur.hur_action is HUA_RELEASE.
This is MDS_HSM_REQUEST RPC handler.
Definition at line 471 of file mdt_hsm.c.
References __u64, CERROR, cfs_size_round(), ENTRY, GOTO, hai_first(), hai_next(), hsm_action_list::hal_archive_id, hsm_action_list::hal_count, hsm_action_list::hal_flags, hsm_action_list::hal_fsname, hal_size(), HAL_VERSION, hsm_action_list::hal_version, hsm_request::hr_action, hsm_request::hr_archive_id, hsm_request::hr_data_len, hsm_request::hr_flags, hsm_request::hr_itemcount, HSMA_ARCHIVE, HSMA_CANCEL, HSMA_NONE, HSMA_REMOVE, HSMA_RESTORE, HUA_ARCHIVE, HUA_CANCEL, HUA_RELEASE, HUA_REMOVE, HUA_RESTORE, hsm_user_item::hui_extent, hsm_user_item::hui_fid, mdt_exit_ucred(), mdt_hsm_add_actions(), MDT_HSM_ALLOC, MDT_HSM_FREE, mdt_init_ucred(), mdt_obd_name(), mdt_thread_info_fini(), mdt_thread_info::mti_body, mdt_thread_info::mti_mdt, MTI_NAME_MAXLEN, obd_uuid2fsname(), RCL_CLIENT, req_capsule_client_get(), req_capsule_get_size(), RETURN, RMF_GENERIC_DATA, RMF_MDS_HSM_REQUEST, RMF_MDS_HSM_USER_ITEM, tsi2mdt_info(), tgt_session_info::tsi_mdt_body, and tgt_session_info::tsi_pill.
int mdt_hsm_state_get (struct tgt_session_info * tsi)
Retrieve the current HSM flags, archive id and undergoing HSM requests for the fid provided in RPC body.
Current requests are read from coordinator states.
This is MDS_HSM_STATE_GET RPC handler.
Definition at line 197 of file mdt_hsm.c.
References ENTRY, err_serious(), EXIT, GOTO, hsm_user_state::hus_archive_id, hsm_user_state::hus_states, LCK_PR, md_attr::ma_hsm, MA_HSM, md_attr::ma_need, md_attr::ma_valid, MDS_INODELOCK_LOOKUP, mdt_attr_get_complex(), mdt_exit_ucred(), mdt_init_ucred(), MDT_LH_CHILD, mdt_lock_reg_init(), mdt_object_lock(), mdt_object_unlock(), mdt_thread_info_fini(), md_hsm::mh_arch_id, md_hsm::mh_flags, mdt_thread_info::mti_attr, mdt_thread_info::mti_body, mdt_thread_info::mti_lh, mdt_thread_info::mti_object, req_capsule_server_get(), RMF_HSM_USER_STATE, tsi2mdt_info(), and tgt_session_info::tsi_pill.
int mdt_hsm_state_set (struct tgt_session_info * tsi)
Change HSM state and archive number of a file.
Archive number is changed iif the value is not 0. The new flagset that will be computed should result in a coherent state. This function checks that flags are compatible.
This is MDS_HSM_STATE_SET RPC handler.
Definition at line 254 of file mdt_hsm.c.
References __u64, CDEBUG, CFS_CAP_SYS_ADMIN, D_HSM, DFID, ENTRY, err_serious(), EXIT, GOTO, HS_ARCHIVED, HS_DIRTY, HS_EXISTS, HS_LOST, HS_RELEASED, HSM_FLAGS_MASK, HSM_USER_MASK, hsm_state_set::hss_archive_id, HSS_ARCHIVE_ID, HSS_CLEARMASK, hsm_state_set::hss_clearmask, HSS_SETMASK, hsm_state_set::hss_setmask, hsm_state_set::hss_valid, LCK_PW, LL_HSM_MAX_ARCHIVE, LPX64, md_attr::ma_hsm, MA_HSM, md_attr::ma_need, md_attr::ma_valid, mdt_body::mbo_fid1, md_capable(), MDS_INODELOCK_LOOKUP, MDS_INODELOCK_XATTR, mdt_attr_get_complex(), mdt_exit_ucred(), mdt_hsm_attr_set(), mdt_init_ucred(), MDT_LH_CHILD, mdt_lock_reg_init(), mdt_object_lock(), mdt_object_unlock(), mdt_thread_info_fini(), mdt_ucred(), md_hsm::mh_arch_id, md_hsm::mh_flags, mdt_thread_info::mti_attr, mdt_thread_info::mti_body, mdt_thread_info::mti_lh, mdt_thread_info::mti_object, mdt_thread_info::mti_pill, PFID, req_capsule_client_get(), RMF_HSM_STATE_SET, and tsi2mdt_info().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.