Lustre: lustre/mdt/mdt_hsm_cdt_agent.c File Reference
lustre/mdt/mdt_hsm_cdt_agent.c File Reference
#include <obd.h>
#include <obd_support.h>
#include <lustre_export.h>
#include <lustre/lustre_user.h>
#include <lprocfs_status.h>
#include <lustre_kernelcomm.h>
#include "mdt_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_MDS
Functions
static struct hsm_agent * mdt_hsm_agent_lookup (struct coordinator *cdt, const struct obd_uuid *uuid)
int mdt_hsm_agent_register (struct mdt_thread_info *mti, const struct obd_uuid *uuid, int nr_archives, __u32 *archive_id)
register a copy tool
int mdt_hsm_agent_register_mask (struct mdt_thread_info *mti, const struct obd_uuid *uuid, __u32 archive_mask)
register a copy tool
int mdt_hsm_agent_unregister (struct mdt_thread_info *mti, const struct obd_uuid *uuid)
unregister a copy tool
int mdt_hsm_agent_update_statistics (struct coordinator *cdt, int succ_rq, int fail_rq, int new_rq, const struct obd_uuid *uuid)
update agent statistics
int mdt_hsm_find_best_agent (struct coordinator *cdt, __u32 archive, struct obd_uuid *uuid)
find the best agent
int mdt_hsm_agent_send (struct mdt_thread_info *mti, struct hsm_action_list *hal, bool purge)
send a compound request to the agent
int mdt_hsm_coordinator_update (struct mdt_thread_info *mti, struct hsm_progress_kernel *pgs)
update status of a request
static void * mdt_hsm_agent_proc_start (struct seq_file *s, loff_t *off)
seq_file method called to start access to /proc file
static void * mdt_hsm_agent_proc_next (struct seq_file *s, void *v, loff_t *p)
seq_file method called to get next item just returns NULL at eof
static int mdt_hsm_agent_proc_show (struct seq_file *s, void *v)
static void mdt_hsm_agent_proc_stop (struct seq_file *s, void *v)
seq_file method called to stop access to /proc file
static int lprocfs_open_hsm_agent (struct inode *inode, struct file *file)
public function called at open of /proc file to get list of agents
Variables
static struct seq_operations mdt_hsm_agent_proc_ops
struct file_operations mdt_hsm_agent_fops
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 36 of file mdt_hsm_cdt_agent.c.
Function Documentation
static int lprocfs_open_hsm_agent (struct inode * inode, struct file * file) [static]
public function called at open of /proc file to get list of agents
Definition at line 637 of file mdt_hsm_cdt_agent.c.
References ENTRY, mdt_hsm_agent_proc_ops, and RETURN.
static struct hsm_agent* mdt_hsm_agent_lookup (struct coordinator * cdt, const struct obd_uuid * uuid) [static, read]
Definition at line 57 of file mdt_hsm_cdt_agent.c.
References coordinator::cdt_agents, hsm_agent::ha_list, hsm_agent::ha_uuid, list_for_each_entry, and obd_uuid_equals().
Referenced by mdt_hsm_agent_register(), and mdt_hsm_agent_unregister().
static void* mdt_hsm_agent_proc_next (struct seq_file * s, void * v, loff_t * p) [static]
seq_file method called to get next item just returns NULL at eof
Definition at line 566 of file mdt_hsm_cdt_agent.c.
References coordinator::cdt_agents, ENTRY, mdt_device::mdt_coordinator, list_head::next, and RETURN.
static int mdt_hsm_agent_proc_show (struct seq_file * s, void * v) [static]
Definition at line 587 of file mdt_hsm_cdt_agent.c.
References ENTRY, hsm_agent::ha_archive_cnt, hsm_agent::ha_archive_id, hsm_agent::ha_failure, hsm_agent::ha_list, hsm_agent::ha_requests, hsm_agent::ha_success, hsm_agent::ha_uuid, list_entry, RETURN, and obd_uuid::uuid.
static void* mdt_hsm_agent_proc_start (struct seq_file * s, loff_t * off) [static]
seq_file method called to start access to /proc file
Definition at line 536 of file mdt_hsm_cdt_agent.c.
References coordinator::cdt_agent_lock, coordinator::cdt_agents, ENTRY, list_empty(), list_for_each, mdt_device::mdt_coordinator, and RETURN.
static void mdt_hsm_agent_proc_stop (struct seq_file * s, void * v) [static]
seq_file method called to stop access to /proc file
Definition at line 617 of file mdt_hsm_cdt_agent.c.
References coordinator::cdt_agent_lock, and mdt_device::mdt_coordinator.
int mdt_hsm_agent_register (struct mdt_thread_info * mti, const struct obd_uuid * uuid, int nr_archives, __u32 * archive_id)
register a copy tool
Parameters:
mti [IN] MDT context
uuid [IN] client UUID to be registered
count [IN] number of archives agent serves
archive_id [IN] vector of archive number served by the copytool
Return values:
0 success
-ve failure
Definition at line 78 of file mdt_hsm_cdt_agent.c.
References CDEBUG, coordinator::cdt_agent_lock, coordinator::cdt_agents, coordinator::cdt_state, CDT_STOPPED, D_HSM, ENTRY, GOTO, hsm_agent::ha_archive_cnt, hsm_agent::ha_archive_id, hsm_agent::ha_failure, hsm_agent::ha_list, hsm_agent::ha_requests, hsm_agent::ha_success, hsm_agent::ha_uuid, LCONSOLE_WARN, list_add_tail(), mdt_device::mdt_coordinator, mdt_hsm_agent_lookup(), mdt_thread_info::mti_mdt, OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, obd_uuid2str(), and RETURN.
Referenced by mdt_hsm_agent_register_mask().
int mdt_hsm_agent_register_mask (struct mdt_thread_info * mti, const struct obd_uuid * uuid, __u32 archive_mask)
register a copy tool
Parameters:
mti [IN] MDT context
uuid [IN] uuid to be registered
archive_mask [IN] bitmask of archive number served by the copytool
Return values:
0 success
-ve failure
Definition at line 153 of file mdt_hsm_cdt_agent.c.
References ENTRY, mdt_hsm_agent_register(), OBD_ALLOC, OBD_FREE, and RETURN.
Referenced by mdt_hsm_ct_register().
int mdt_hsm_agent_send (struct mdt_thread_info * mti, struct hsm_action_list * hal, bool purge)
send a compound request to the agent
Parameters:
mti [IN] context
hal [IN] request (can be a kuc payload)
purge [IN] purge mode (no record)
Return values:
0 success
-ve failure This function supposes:
all actions are for the same archive number
in case of cancel, all cancel are for the same agent This implies that request split has to be done before when building the hal
Definition at line 322 of file mdt_hsm_cdt_agent.c.
References agent_req_status2name(), ARS_FAILED, buf, CDEBUG, coordinator::cdt_restore_lock, CERROR, cfs_hash_lookup(), class_export_put(), cdt_restore_handle::crh_lh, cdt_restore_handle::crh_list, D_HSM, do_set_info_async(), ENTRY, obd_export::exp_disconnected, obd_export::exp_imp_reverse, GOTO, hai_first(), hai_next(), hsm_action_list::hal_archive_id, hsm_action_list::hal_count, hsm_action_list::hal_flags, hal_size(), HMT_ACTION_LIST, HSMA_CANCEL, HSMA_REMOVE, HSMA_RESTORE, KEY_HSM_COPYTOOL_SEND, kuc_alloc(), kuc_free(), kuc_len(), kuc_ptr(), KUC_TRANSPORT_HSM, LDLM_SET_INFO, list_del(), LPX64, LUSTRE_OBD_VERSION, mdt2obd_dev(), mdt_agent_record_update(), mdt_cdt_remove_request(), mdt_device::mdt_coordinator, mdt_hsm_add_hal(), mdt_hsm_agent_unregister(), mdt_hsm_cdt_kmem, mdt_hsm_find_best_agent(), mdt_hsm_get_md_hsm(), mdt_hsm_is_action_compat(), mdt_hsm_restore_hdl_find(), mdt_obd_name(), mdt_object_find(), mdt_object_put(), mdt_object_unlock(), mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, OBD_SLAB_FREE_PTR, obd_uuid2str(), and RETURN.
Referenced by hsm_cancel_all_actions(), and mdt_coordinator().
int mdt_hsm_agent_unregister (struct mdt_thread_info * mti, const struct obd_uuid * uuid)
unregister a copy tool
Parameters:
mti [IN] MDT context
uuid [IN] uuid to be unregistered
Return values:
0 success
-ve failure
Definition at line 191 of file mdt_hsm_cdt_agent.c.
References CDEBUG, coordinator::cdt_agent_lock, coordinator::cdt_state, CDT_STOPPED, D_HSM, ENTRY, GOTO, hsm_agent::ha_archive_cnt, hsm_agent::ha_archive_id, hsm_agent::ha_list, list_del_init(), mdt_device::mdt_coordinator, mdt_hsm_agent_lookup(), mdt_thread_info::mti_mdt, OBD_FREE, OBD_FREE_PTR, obd_uuid2str(), and RETURN.
Referenced by mdt_hsm_agent_send(), and mdt_hsm_ct_unregister().
int mdt_hsm_agent_update_statistics (struct coordinator * cdt, int succ_rq, int fail_rq, int new_rq, const struct obd_uuid * uuid)
update agent statistics
Parameters:
mdt [IN] MDT device
succ_rq [IN] number of success
fail_rq [IN] number of failure
new_rq [IN] number of new requests
uuid [IN] agent uuid if all counters == 0, clear counters
Return values:
0 success
-ve failure
Definition at line 237 of file mdt_hsm_cdt_agent.c.
References coordinator::cdt_agent_lock, coordinator::cdt_agents, ENTRY, GOTO, hsm_agent::ha_failure, hsm_agent::ha_list, hsm_agent::ha_requests, hsm_agent::ha_success, hsm_agent::ha_uuid, list_for_each_entry, obd_uuid_equals(), and RETURN.
Referenced by mdt_cdt_add_request(), and mdt_cdt_update_request().
int mdt_hsm_coordinator_update (struct mdt_thread_info * mti, struct hsm_progress_kernel * pgs)
update status of a request
Parameters:
mti [IN]
pgs [IN] progress of the copy tool
Return values:
0 success
-ve failure
Definition at line 521 of file mdt_hsm_cdt_agent.c.
References ENTRY, mdt_hsm_update_request_state(), and RETURN.
Referenced by mdt_hsm_progress().
int mdt_hsm_find_best_agent (struct coordinator * cdt, __u32 archive, struct obd_uuid * uuid)
find the best agent
Parameters:
cdt [IN] coordinator
archive [IN] archive number
uuid [OUT] agent who can serve archive
Return values:
0 success
-ve failure
Definition at line 277 of file mdt_hsm_cdt_agent.c.
References coordinator::cdt_agent_lock, coordinator::cdt_agents, ENTRY, hsm_agent::ha_archive_cnt, hsm_agent::ha_archive_id, hsm_agent::ha_list, hsm_agent::ha_requests, hsm_agent::ha_uuid, list_for_each_entry, and RETURN.
Referenced by mdt_hsm_agent_send().
Variable Documentation
struct file_operations mdt_hsm_agent_fops
Initial value:
 {
        .owner          = THIS_MODULE,
        .open           = lprocfs_open_hsm_agent,
        .read           = seq_read,
        .llseek         = seq_lseek,
        .release        = lprocfs_seq_release,
}
Definition at line 654 of file mdt_hsm_cdt_agent.c.
struct seq_operations mdt_hsm_agent_proc_ops [static]
Initial value:
 {
        .start  = mdt_hsm_agent_proc_start,
        .next   = mdt_hsm_agent_proc_next,
        .show   = mdt_hsm_agent_proc_show,
        .stop   = mdt_hsm_agent_proc_stop,
}
Definition at line 626 of file mdt_hsm_cdt_agent.c.
Referenced by lprocfs_open_hsm_agent().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.