Lustre: lustre/mdt/mdt_fs.c File Reference
lustre/mdt/mdt_fs.c File Reference
#include "mdt_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_MDS
Functions
int mdt_export_stats_init (struct obd_device *obd, struct obd_export *exp, void *localdata)
Initialize MDT per-export statistics.
Variables
static struct file_operations mdt_open_files_seq_fops
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 41 of file mdt_fs.c.
Function Documentation
int mdt_export_stats_init (struct obd_device * obd, struct obd_export * exp, void * localdata)
Initialize MDT per-export statistics.
This function sets up procfs entries for various MDT export counters. These counters are for per-client statistics tracked on the server.
Parameters:
[in] obd OBD device
[in] exp OBD export
[in] localdata NID of client
Return values:
0 if successful
negative value on error
Definition at line 66 of file mdt_fs.c.
References CWARN, ENTRY, obd_export::exp_nid_stats, GOTO, LASSERT, LPROC_MDT_LAST, lprocfs_alloc_stats(), lprocfs_free_stats(), lprocfs_nid_ldlm_stats_init(), lprocfs_register_stats(), LPROCFS_STATS_FLAG_NOPERCPU, mdt_open_files_seq_fops, mdt_stats_counter_init(), nid_stat::nid_proc, nid_stat::nid_stats, obd_device::obd_name, obd_device::obd_uses_nid_stats, and RETURN.
Referenced by mdt_obd_connect(), and mdt_obd_reconnect().
Variable Documentation
struct file_operations mdt_open_files_seq_fops [static]
Initial value:
 {
        .owner   = THIS_MODULE,
        .open    = lprocfs_mdt_open_files_seq_open,
        .read    = seq_read,
        .llseek  = seq_lseek,
        .release = seq_release,
}
Definition at line 45 of file mdt_fs.c.
Referenced by mdt_export_stats_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.