Lustre: lustre/mdt/mdt_hsm_cdt_actions.c File Reference
lustre/mdt/mdt_hsm_cdt_actions.c File Reference
#include <obd_support.h>
#include <lustre_net.h>
#include <lustre_export.h>
#include <obd.h>
#include <lprocfs_status.h>
#include <lustre_log.h>
#include "mdt_internal.h"
Data Structures
struct data_update_cb
data passed to llog_cat_process() callback to find requests
struct agent_action_iterator
Defines
#define DEBUG_SUBSYSTEM S_MDS
#define AGENT_ACTIONS_IT_MAGIC 0x19660426
seq_file iterator for agent_action entry
Functions
void dump_llog_agent_req_rec (const char *prefix, const struct llog_agent_req_rec *larr)
int cdt_llog_process (const struct lu_env *env, struct mdt_device *mdt, llog_cb_t cb, void *data)
int mdt_agent_record_add (const struct lu_env *env, struct mdt_device *mdt, __u64 compound_id, __u32 archive_id, __u64 flags, struct hsm_action_item *hai)
add an entry in agent llog
static int mdt_agent_record_update_cb (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *hdr, void *data)
llog_cat_process() callback, used to update a record
int mdt_agent_record_update (const struct lu_env *env, struct mdt_device *mdt, __u64 *cookies, int cookies_count, enum agent_req_status status)
update an entry in agent llog
static void * mdt_hsm_actions_proc_start (struct seq_file *s, loff_t *pos)
seq_file method called to start access to /proc file get llog context + llog handle
static void * mdt_hsm_actions_proc_next (struct seq_file *s, void *v, loff_t *pos)
static int hsm_actions_show_cb (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *hdr, void *data)
llog_cat_process() callback, used to fill a seq_file buffer
static int mdt_hsm_actions_proc_show (struct seq_file *s, void *v)
mdt_hsm_actions_proc_show() is called at for each seq record process the llog, with a cb which fill the file_seq buffer to be faster, one show will fill multiple records
static void mdt_hsm_actions_proc_stop (struct seq_file *s, void *v)
seq_file method called to stop access to /proc file clean + put llog context
static int lprocfs_open_hsm_actions (struct inode *inode, struct file *file)
static int lprocfs_release_hsm_actions (struct inode *inode, struct file *file)
lprocfs_release_hsm_actions() is called at end of /proc access.
Variables
static struct seq_operations mdt_hsm_actions_proc_ops
struct file_operations mdt_hsm_actions_fops
Define Documentation
#define AGENT_ACTIONS_IT_MAGIC 0x19660426
seq_file iterator for agent_action entry
Definition at line 302 of file mdt_hsm_cdt_actions.c.
Referenced by hsm_actions_show_cb(), lprocfs_open_hsm_actions(), mdt_hsm_actions_proc_show(), mdt_hsm_actions_proc_start(), and mdt_hsm_actions_proc_stop().
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 37 of file mdt_hsm_cdt_actions.c.
Function Documentation
int cdt_llog_process (const struct lu_env * env, struct mdt_device * mdt, llog_cb_t cb, void * data)
Definition at line 87 of file mdt_hsm_cdt_actions.c.
References coordinator::cdt_llog_lock, CERROR, ENTRY, LLOG_AGENT_ORIG_CTXT, llog_cat_process(), llog_ctxt_put(), llog_get_context(), llog_ctxt::loc_handle, mdt2obd_dev(), mdt_device::mdt_coordinator, mdt_obd_name(), and RETURN.
Referenced by hsm_cancel_all_actions(), hsm_find_compatible(), mdt_agent_record_update(), mdt_coordinator(), and mdt_hsm_pending_restore().
void dump_llog_agent_req_rec (const char * prefix, const struct llog_agent_req_rec * larr)
Definition at line 47 of file mdt_hsm_cdt_actions.c.
References agent_req_status2name(), llog_agent_req_rec::arr_archive_id, llog_agent_req_rec::arr_compound_id, llog_agent_req_rec::arr_flags, llog_agent_req_rec::arr_hai, llog_agent_req_rec::arr_hdr, llog_agent_req_rec::arr_req_change, llog_agent_req_rec::arr_req_create, llog_agent_req_rec::arr_status, buf, CDEBUG, D_HSM, DFID, hsm_action_item::hai_action, hsm_action_item::hai_cookie, hsm_action_item::hai_dfid, hai_dump_data_field(), hsm_action_item::hai_extent, hsm_action_item::hai_fid, hsm_action_item::hai_gid, hsm_action_item::hai_len, hsm_copytool_action2name(), hsm_extent::length, LPU64, LPX64, llog_rec_hdr::lrh_index, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, hsm_extent::offset, and PFID.
Referenced by mdt_coordinator_cb().
static int hsm_actions_show_cb (const struct lu_env * env, struct llog_handle * llh, struct llog_rec_hdr * hdr, void * data) [static]
llog_cat_process() callback, used to fill a seq_file buffer
Definition at line 357 of file mdt_hsm_cdt_actions.c.
References agent_action_iterator::aai_cat_index, agent_action_iterator::aai_index, agent_action_iterator::aai_magic, AGENT_ACTIONS_IT_MAGIC, agent_req_status2name(), llog_agent_req_rec::arr_archive_id, llog_agent_req_rec::arr_compound_id, llog_agent_req_rec::arr_flags, llog_agent_req_rec::arr_hai, llog_agent_req_rec::arr_status, buf, DFID, ENTRY, hsm_action_item::hai_action, hsm_action_item::hai_cookie, hsm_action_item::hai_dfid, hai_dump_data_field(), hsm_action_item::hai_extent, hsm_action_item::hai_fid, hsm_action_item::hai_gid, hsm_action_item::hai_len, hsm_copytool_action2name(), LASSERTF, hsm_extent::length, llog_handle::lgh_hdr, llog_log_hdr::llh_cat_idx, LPX64, llog_rec_hdr::lrh_index, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, hsm_extent::offset, PFID, RETURN, and unlikely.
Referenced by mdt_hsm_actions_proc_show().
static int lprocfs_open_hsm_actions (struct inode * inode, struct file * file) [static]
Definition at line 467 of file mdt_hsm_cdt_actions.c.
References agent_action_iterator::aai_env, agent_action_iterator::aai_magic, agent_action_iterator::aai_mdt, AGENT_ACTIONS_IT_MAGIC, ENTRY, GOTO, LCT_LOCAL, lu_env::le_ses, lu_env_init(), mdt_hsm_actions_proc_ops, OBD_ALLOC_PTR, OBD_FREE_PTR, and RETURN.
static int lprocfs_release_hsm_actions (struct inode * inode, struct file * file) [static]
lprocfs_release_hsm_actions() is called at end of /proc access.
It frees allocated resources and calls cleanup lprocfs methods.
Definition at line 512 of file mdt_hsm_cdt_actions.c.
References agent_action_iterator::aai_env, lu_env_fini(), and OBD_FREE_PTR.
int mdt_agent_record_add (const struct lu_env * env, struct mdt_device * mdt, __u64 compound_id, __u32 archive_id, __u64 flags, struct hsm_action_item * hai)
add an entry in agent llog
Parameters:
env [IN] environment
mdt [IN] PDT device
compound_id [IN] global id associated with the record
archive_id [IN] backend archive number
hai [IN] record to register
Return values:
0 success
-ve failure
Definition at line 124 of file mdt_hsm_cdt_actions.c.
References llog_agent_req_rec::arr_archive_id, llog_agent_req_rec::arr_compound_id, llog_agent_req_rec::arr_flags, llog_agent_req_rec::arr_hai, llog_agent_req_rec::arr_hdr, llog_agent_req_rec::arr_req_change, llog_agent_req_rec::arr_req_create, llog_agent_req_rec::arr_status, ARS_WAITING, coordinator::cdt_last_cookie, coordinator::cdt_llog_lock, cfs_time_current_sec(), ENTRY, EXIT, GOTO, hsm_action_item::hai_action, hsm_action_item::hai_cookie, hsm_action_item::hai_len, HSM_AGENT_REC, HSMA_CANCEL, LLOG_AGENT_ORIG_CTXT, llog_cat_add(), llog_ctxt_put(), llog_data_len(), llog_get_context(), llog_ctxt::loc_handle, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, mdt2obd_dev(), mdt_device::mdt_coordinator, OBD_ALLOC, OBD_FREE, and RETURN.
Referenced by mdt_hsm_add_actions().
int mdt_agent_record_update (const struct lu_env * env, struct mdt_device * mdt, __u64 * cookies, int cookies_count, enum agent_req_status status)
update an entry in agent llog
Parameters:
env [IN] environment
mdt [IN] MDT device
cookie [IN] entries to update log cookie are returned by register
status [IN] new status of the request
Return values:
0 success
-ve failure
Definition at line 261 of file mdt_hsm_cdt_actions.c.
References agent_req_status2name(), cdt_llog_process(), CERROR, cfs_time_current_sec(), data_update_cb::change_time, data_update_cb::cookies, data_update_cb::cookies_count, data_update_cb::cookies_done, ENTRY, data_update_cb::mdt, mdt_agent_record_update_cb(), mdt_obd_name(), RETURN, and data_update_cb::status.
Referenced by mdt_coordinator(), mdt_hsm_add_hal(), mdt_hsm_agent_send(), and mdt_hsm_update_request_state().
static int mdt_agent_record_update_cb (const struct lu_env * env, struct llog_handle * llh, struct llog_rec_hdr * hdr, void * data) [static]
llog_cat_process() callback, used to update a record
Parameters:
env [IN] environment
llh [IN] llog handle
hdr [IN] llog record
data [IN] cb data = data_update_cb
Return values:
0 success
-ve failure
Definition at line 200 of file mdt_hsm_cdt_actions.c.
References agent_req_in_final_state(), llog_agent_req_rec::arr_hai, llog_agent_req_rec::arr_req_change, llog_agent_req_rec::arr_status, ARS_CANCELED, CDEBUG, CERROR, data_update_cb::change_time, data_update_cb::cookies, data_update_cb::cookies_count, data_update_cb::cookies_done, D_HSM, ENTRY, hsm_action_item::hai_action, hsm_action_item::hai_cookie, HSMA_CANCEL, LLOG_PROC_BREAK, llog_write(), LPX64, llog_rec_hdr::lrh_index, data_update_cb::mdt, mdt_obd_name(), RETURN, and data_update_cb::status.
Referenced by mdt_agent_record_update().
static void* mdt_hsm_actions_proc_next (struct seq_file * s, void * v, loff_t * pos) [static]
Definition at line 348 of file mdt_hsm_cdt_actions.c.
References RETURN.
static int mdt_hsm_actions_proc_show (struct seq_file * s, void * v) [static]
mdt_hsm_actions_proc_show() is called at for each seq record process the llog, with a cb which fill the file_seq buffer to be faster, one show will fill multiple records
Definition at line 414 of file mdt_hsm_cdt_actions.c.
References agent_action_iterator::aai_cat_index, agent_action_iterator::aai_ctxt, agent_action_iterator::aai_env, agent_action_iterator::aai_eof, agent_action_iterator::aai_index, agent_action_iterator::aai_magic, agent_action_iterator::aai_mdt, AGENT_ACTIONS_IT_MAGIC, CDEBUG, coordinator::cdt_llog_lock, D_HSM, ENTRY, hsm_actions_show_cb(), LASSERTF, llog_cat_process(), LLOG_PROC_BREAK, llog_ctxt::loc_handle, mdt_device::mdt_coordinator, and RETURN.
static void* mdt_hsm_actions_proc_start (struct seq_file * s, loff_t * pos) [static]
seq_file method called to start access to /proc file get llog context + llog handle
Definition at line 317 of file mdt_hsm_cdt_actions.c.
References agent_action_iterator::aai_cat_index, agent_action_iterator::aai_ctxt, agent_action_iterator::aai_eof, agent_action_iterator::aai_index, agent_action_iterator::aai_magic, agent_action_iterator::aai_mdt, AGENT_ACTIONS_IT_MAGIC, CDEBUG, CERROR, D_HSM, ENTRY, LASSERTF, LLOG_AGENT_ORIG_CTXT, llog_get_context(), llog_ctxt::loc_handle, LPD64, mdt2obd_dev(), and RETURN.
static void mdt_hsm_actions_proc_stop (struct seq_file * s, void * v) [static]
seq_file method called to stop access to /proc file clean + put llog context
Definition at line 445 of file mdt_hsm_cdt_actions.c.
References agent_action_iterator::aai_ctxt, agent_action_iterator::aai_magic, AGENT_ACTIONS_IT_MAGIC, ENTRY, EXIT, LASSERTF, and llog_ctxt_put().
Variable Documentation
struct file_operations mdt_hsm_actions_fops
Initial value:
 {
        .owner          = THIS_MODULE,
        .open           = lprocfs_open_hsm_actions,
        .read           = seq_read,
        .llseek         = seq_lseek,
        .release        = lprocfs_release_hsm_actions,
}
Definition at line 526 of file mdt_hsm_cdt_actions.c.
struct seq_operations mdt_hsm_actions_proc_ops [static]
Initial value:
 {
        .start  = mdt_hsm_actions_proc_start,
        .next   = mdt_hsm_actions_proc_next,
        .show   = mdt_hsm_actions_proc_show,
        .stop   = mdt_hsm_actions_proc_stop,
}
Definition at line 460 of file mdt_hsm_cdt_actions.c.
Referenced by lprocfs_open_hsm_actions().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.