Lustre: lustre/mdt/mdt_lproc.c File Reference
lustre/mdt/mdt_lproc.c File Reference
#include <linux/version.h>
#include <asm/statfs.h>
#include <linux/module.h>
#include <lnet/nidstr.h>
#include <lustre_ver.h>
#include <obd_support.h>
#include <lustre_export.h>
#include <obd.h>
#include <obd_class.h>
#include <lustre_mds.h>
#include <lprocfs_status.h>
#include "mdt_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_MDS
#define pct(a, b) (b ? a * 100 / b : 0)
The rename stats output would be YAML formats, like rename_stats:
snapshot_time: 1234567890.123456
same_dir: 4kB: { samples: 1230, pct: 33, cum_pct: 45 } 8kB: { samples: 1242, pct: 33, cum_pct: 78 } 16kB: { samples: 132, pct: 3, cum_pct: 81 }
crossdir_src: 4kB: { samples: 123, pct: 33, cum_pct: 45 } 8kB: { samples: 124, pct: 33, cum_pct: 78 } 16kB: { samples: 12, pct: 3, cum_pct: 81 }
crossdir_tgt: 4kB: { samples: 123, pct: 33, cum_pct: 45 } 8kB: { samples: 124, pct: 33, cum_pct: 78 } 16kB: { samples: 12, pct: 3, cum_pct: 81 }.
#define BUFLEN (UUID_MAX + 4)
Functions
static void display_rename_stats (struct seq_file *seq, char *name, struct obd_histogram *hist)
static void rename_stats_show (struct seq_file *seq, struct rename_stats *rename_stats)
static int mdt_rename_stats_seq_show (struct seq_file *seq, void *v)
static ssize_t mdt_rename_stats_seq_write (struct file *file, const char __user *buf, size_t len, loff_t *off)
LPROC_SEQ_FOPS (mdt_rename_stats)
static int lproc_mdt_attach_rename_seqstat (struct mdt_device *mdt)
void mdt_rename_counter_tally (struct mdt_thread_info *info, struct mdt_device *mdt, struct ptlrpc_request *req, struct mdt_object *src, struct mdt_object *tgt)
static int mdt_identity_expire_seq_show (struct seq_file *m, void *data)
static ssize_t mdt_identity_expire_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
LPROC_SEQ_FOPS (mdt_identity_expire)
static int mdt_identity_acquire_expire_seq_show (struct seq_file *m, void *data)
static ssize_t mdt_identity_acquire_expire_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
LPROC_SEQ_FOPS (mdt_identity_acquire_expire)
static int mdt_identity_upcall_seq_show (struct seq_file *m, void *data)
static ssize_t mdt_identity_upcall_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
LPROC_SEQ_FOPS (mdt_identity_upcall)
static ssize_t lprocfs_identity_flush_seq_write (struct file *file, const char __user *buffer, size_t count, void *data)
LPROC_SEQ_FOPS_WO_TYPE (mdt, identity_flush)
static ssize_t lprocfs_identity_info_seq_write (struct file *file, const char __user *buffer, size_t count, void *data)
LPROC_SEQ_FOPS_WO_TYPE (mdt, identity_info)
static int mdt_site_stats_seq_show (struct seq_file *m, void *data)
LPROC_SEQ_FOPS_RO (mdt_site_stats)
static ssize_t lprocfs_mds_evict_client_seq_write (struct file *file, const char __user *buf, size_t count, loff_t *off)
static int mdt_evict_tgt_nids_seq_show (struct seq_file *m, void *data)
static ssize_t mdt_evict_tgt_nids_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
LPROC_SEQ_FOPS (mdt_evict_tgt_nids)
static int mdt_sec_level_seq_show (struct seq_file *m, void *data)
static ssize_t mdt_sec_level_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
LPROC_SEQ_FOPS (mdt_sec_level)
static int mdt_cos_seq_show (struct seq_file *m, void *data)
static ssize_t mdt_cos_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
LPROC_SEQ_FOPS (mdt_cos)
static int mdt_root_squash_seq_show (struct seq_file *m, void *data)
static ssize_t mdt_root_squash_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
LPROC_SEQ_FOPS (mdt_root_squash)
static int mdt_nosquash_nids_seq_show (struct seq_file *m, void *data)
static ssize_t mdt_nosquash_nids_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
LPROC_SEQ_FOPS (mdt_nosquash_nids)
static int mdt_enable_remote_dir_seq_show (struct seq_file *m, void *data)
static ssize_t mdt_enable_remote_dir_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
LPROC_SEQ_FOPS (mdt_enable_remote_dir)
static int mdt_enable_remote_dir_gid_seq_show (struct seq_file *m, void *data)
static ssize_t mdt_enable_remote_dir_gid_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
LPROC_SEQ_FOPS (mdt_enable_remote_dir_gid)
static int mdt_slc_seq_show (struct seq_file *m, void *data)
Show MDT policy for handling dirty metadata under a lock being cancelled.
LPROC_SEQ_FOPS_RO (mdt_slc)
static int mdt_async_commit_count_seq_show (struct seq_file *m, void *data)
Show MDT async commit count.
static ssize_t mdt_async_commit_count_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
LPROC_SEQ_FOPS (mdt_async_commit_count)
static int mdt_sync_count_seq_show (struct seq_file *m, void *data)
Show MDT sync count.
static ssize_t mdt_sync_count_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
LPROC_SEQ_FOPS (mdt_sync_count)
LPROC_SEQ_FOPS_RO_TYPE (mdt, uuid)
LPROC_SEQ_FOPS_RO_TYPE (mdt, recovery_status)
LPROC_SEQ_FOPS_RO_TYPE (mdt, num_exports)
LPROC_SEQ_FOPS_RO_TYPE (mdt, target_instance)
LPROC_SEQ_FOPS_RO_TYPE (mdt, hash)
LPROC_SEQ_FOPS_WO_TYPE (mdt, mds_evict_client)
LPROC_SEQ_FOPS_RW_TYPE (mdt, job_interval)
LPROC_SEQ_FOPS_RW_TYPE (mdt, ir_factor)
LPROC_SEQ_FOPS_RW_TYPE (mdt, nid_stats_clear)
LPROC_SEQ_FOPS (mdt_hsm_cdt_control)
LPROC_SEQ_FOPS_RW_TYPE (mdt, recovery_time_hard)
LPROC_SEQ_FOPS_RW_TYPE (mdt, recovery_time_soft)
static int lprocfs_mdt_print_open_files (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode, void *v)
static int lprocfs_mdt_open_files_seq_show (struct seq_file *seq, void *v)
int lprocfs_mdt_open_files_seq_open (struct inode *inode, struct file *file)
void mdt_counter_incr (struct ptlrpc_request *req, int opcode)
void mdt_stats_counter_init (struct lprocfs_stats *stats)
int mdt_procfs_init (struct mdt_device *mdt, const char *name)
void mdt_procfs_fini (struct mdt_device *mdt)
Variables
static struct lprocfs_vars lprocfs_mdt_obd_vars []
Define Documentation
#define BUFLEN (UUID_MAX + 4)
Definition at line 434 of file mdt_lproc.c.
Referenced by lprocfs_mds_evict_client_seq_write().
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 42 of file mdt_lproc.c.
#define pct (a, b) (b ? a * 100 / b : 0)
The rename stats output would be YAML formats, like rename_stats:
snapshot_time: 1234567890.123456
same_dir: 4kB: { samples: 1230, pct: 33, cum_pct: 45 } 8kB: { samples: 1242, pct: 33, cum_pct: 78 } 16kB: { samples: 132, pct: 3, cum_pct: 81 }
crossdir_src: 4kB: { samples: 123, pct: 33, cum_pct: 45 } 8kB: { samples: 124, pct: 33, cum_pct: 78 } 16kB: { samples: 12, pct: 3, cum_pct: 81 }
crossdir_tgt: 4kB: { samples: 123, pct: 33, cum_pct: 45 } 8kB: { samples: 124, pct: 33, cum_pct: 78 } 16kB: { samples: 12, pct: 3, cum_pct: 81 }.
Definition at line 83 of file mdt_lproc.c.
Referenced by display_rename_stats(), fld_cache_fini(), and obd_mod_rpc_stats_seq_show().
Function Documentation
static void display_rename_stats (struct seq_file * seq, char * name, struct obd_histogram * hist) [static]
Definition at line 85 of file mdt_lproc.c.
References lprocfs_oh_sum(), OBD_HIST_MAX, obd_histogram::oh_buckets, and pct.
Referenced by rename_stats_show().
static int lproc_mdt_attach_rename_seqstat (struct mdt_device * mdt) [static]
Definition at line 161 of file mdt_lproc.c.
References rename_stats::hist, mdt2obd_dev(), mdt_device::mdt_rename_stats, obd_histogram::oh_lock, and RENAME_LAST.
Referenced by mdt_procfs_init().
LPROC_SEQ_FOPS (mdt_hsm_cdt_control)
LPROC_SEQ_FOPS (mdt_sync_count)
LPROC_SEQ_FOPS (mdt_async_commit_count)
LPROC_SEQ_FOPS (mdt_enable_remote_dir_gid)
LPROC_SEQ_FOPS (mdt_enable_remote_dir)
LPROC_SEQ_FOPS (mdt_nosquash_nids)
LPROC_SEQ_FOPS (mdt_root_squash)
LPROC_SEQ_FOPS (mdt_cos)
LPROC_SEQ_FOPS (mdt_sec_level)
LPROC_SEQ_FOPS (mdt_evict_tgt_nids)
LPROC_SEQ_FOPS (mdt_identity_upcall)
LPROC_SEQ_FOPS (mdt_identity_acquire_expire)
LPROC_SEQ_FOPS (mdt_identity_expire)
LPROC_SEQ_FOPS (mdt_rename_stats)
LPROC_SEQ_FOPS_RO (mdt_slc)
LPROC_SEQ_FOPS_RO (mdt_site_stats)
LPROC_SEQ_FOPS_RO_TYPE (mdt , hash)
LPROC_SEQ_FOPS_RO_TYPE (mdt , target_instance)
LPROC_SEQ_FOPS_RO_TYPE (mdt , num_exports)
LPROC_SEQ_FOPS_RO_TYPE (mdt , recovery_status)
LPROC_SEQ_FOPS_RO_TYPE (mdt , uuid)
LPROC_SEQ_FOPS_RW_TYPE (mdt , recovery_time_soft)
LPROC_SEQ_FOPS_RW_TYPE (mdt , recovery_time_hard)
LPROC_SEQ_FOPS_RW_TYPE (mdt , nid_stats_clear)
LPROC_SEQ_FOPS_RW_TYPE (mdt , ir_factor)
LPROC_SEQ_FOPS_RW_TYPE (mdt , job_interval)
LPROC_SEQ_FOPS_WO_TYPE (mdt , mds_evict_client)
LPROC_SEQ_FOPS_WO_TYPE (mdt , identity_info)
LPROC_SEQ_FOPS_WO_TYPE (mdt , identity_flush)
static ssize_t lprocfs_identity_flush_seq_write (struct file * file, const char __user * buffer, size_t count, void * data) [static]
Definition at line 337 of file mdt_lproc.c.
References mdt_dev(), mdt_flush_identity(), mdt_device::mdt_identity_cache, and obd_device::obd_lu_dev.
static ssize_t lprocfs_identity_info_seq_write (struct file * file, const char __user * buffer, size_t count, void * data) [static]
Definition at line 358 of file mdt_lproc.c.
References CERROR, GOTO, identity_downcall_data::idd_err, identity_downcall_data::idd_groups, identity_downcall_data::idd_magic, identity_downcall_data::idd_ngroups, identity_downcall_data::idd_nperms, identity_downcall_data::idd_uid, IDENTITY_DOWNCALL_MAGIC, mdt_dev(), mdt_device::mdt_identity_cache, mdt_obd_name(), N_PERMS_MAX, NGROUPS_MAX, OBD_ALLOC, OBD_FREE, obd_device::obd_lu_dev, offsetof, size, and upcall_cache_downcall().
static ssize_t lprocfs_mds_evict_client_seq_write (struct file * file, const char __user * buf, size_t count, loff_t * off) [static]
Definition at line 437 of file mdt_lproc.c.
References BUFLEN, CERROR, cfs_firststr(), class_decref(), class_incref(), GOTO, KEY_EVICT_BY_NID, mdt_device::mdt_child_exp, mdt_dev(), mdt_device::mdt_opts, min_t, mdt_device::mo_evict_tgt_nids, OBD_ALLOC, obd_export_evict_by_nid(), OBD_FREE, obd_device::obd_lu_dev, and obd_set_info_async().
int lprocfs_mdt_open_files_seq_open (struct inode * inode, struct file * file)
Definition at line 914 of file mdt_lproc.c.
References lprocfs_mdt_open_files_seq_show().
static int lprocfs_mdt_open_files_seq_show (struct seq_file * seq, void * v) [static]
Definition at line 903 of file mdt_lproc.c.
References cfs_hash_for_each_key(), lprocfs_mdt_print_open_files(), nid_stat::nid, nid_stat::nid_obd, and obd_device::obd_nid_hash.
Referenced by lprocfs_mdt_open_files_seq_open().
static int lprocfs_mdt_print_open_files (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode, void * v) [static]
Definition at line 882 of file mdt_lproc.c.
References cfs_hash_object(), DFID, obd_export::exp_lock_hash, list_for_each_entry, mdt_object_fid(), mdt_export_data::med_open_head, mdt_export_data::med_open_lock, mdt_file_data::mfd_list, mdt_file_data::mfd_object, and PFID.
Referenced by lprocfs_mdt_open_files_seq_show().
static int mdt_async_commit_count_seq_show (struct seq_file * m, void * data) [static]
Show MDT async commit count.
Parameters:
[in] m seq_file handle
[in] data unused for single entry
Return values:
0 on success
negative value on error
Definition at line 735 of file mdt_lproc.c.
References mdt_device::mdt_async_commit_count, mdt_dev(), and obd_device::obd_lu_dev.
static ssize_t mdt_async_commit_count_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Definition at line 745 of file mdt_lproc.c.
References mdt_device::mdt_async_commit_count, mdt_dev(), and obd_device::obd_lu_dev.
static int mdt_cos_seq_show (struct seq_file * m, void * data) [static]
Definition at line 556 of file mdt_lproc.c.
References mdt_cos_is_enabled(), mdt_dev(), and obd_device::obd_lu_dev.
static ssize_t mdt_cos_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Definition at line 566 of file mdt_lproc.c.
References mdt_dev(), mdt_enable_cos(), and obd_device::obd_lu_dev.
void mdt_counter_incr (struct ptlrpc_request * req, int opcode)
Definition at line 929 of file mdt_lproc.c.
References exp_connect_flags(), obd_export::exp_nid_stats, obd_export::exp_obd, lprocfs_counter_incr(), lprocfs_job_stats_log(), lustre_msg_get_jobid(), nid_stat::nid_stats, OBD_CONNECT_JOBSTATS, obd_device::obd_md_stats, ptlrpc_request::rq_export, ptlrpc_request::rq_reqmsg, and obd_device::u.
Referenced by mdt_close(), mdt_getattr_internal(), mdt_getxattr(), mdt_reint_create(), mdt_reint_link(), mdt_reint_open(), mdt_reint_rename_internal(), mdt_reint_setattr(), mdt_reint_setxattr(), mdt_reint_unlink(), mdt_rename_counter_tally(), mdt_statfs(), and mdt_sync().
static int mdt_enable_remote_dir_gid_seq_show (struct seq_file * m, void * data) [static]
Definition at line 676 of file mdt_lproc.c.
References mdt_dev(), mdt_device::mdt_enable_remote_dir_gid, and obd_device::obd_lu_dev.
static ssize_t mdt_enable_remote_dir_gid_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Definition at line 687 of file mdt_lproc.c.
References mdt_dev(), mdt_device::mdt_enable_remote_dir_gid, and obd_device::obd_lu_dev.
static int mdt_enable_remote_dir_seq_show (struct seq_file * m, void * data) [static]
Definition at line 645 of file mdt_lproc.c.
References mdt_dev(), mdt_device::mdt_enable_remote_dir, and obd_device::obd_lu_dev.
static ssize_t mdt_enable_remote_dir_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Definition at line 655 of file mdt_lproc.c.
References mdt_dev(), mdt_device::mdt_enable_remote_dir, and obd_device::obd_lu_dev.
static int mdt_evict_tgt_nids_seq_show (struct seq_file * m, void * data) [static]
Definition at line 490 of file mdt_lproc.c.
References mdt_dev(), mdt_device::mdt_opts, mdt_device::mo_evict_tgt_nids, and obd_device::obd_lu_dev.
static ssize_t mdt_evict_tgt_nids_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Definition at line 500 of file mdt_lproc.c.
References mdt_dev(), mdt_device::mdt_opts, mdt_device::mo_evict_tgt_nids, and obd_device::obd_lu_dev.
static int mdt_identity_acquire_expire_seq_show (struct seq_file * m, void * data) [static]
Definition at line 246 of file mdt_lproc.c.
References mdt_dev(), mdt_device::mdt_identity_cache, obd_device::obd_lu_dev, and upcall_cache::uc_acquire_expire.
static ssize_t mdt_identity_acquire_expire_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Definition at line 256 of file mdt_lproc.c.
References mdt_dev(), mdt_device::mdt_identity_cache, obd_device::obd_lu_dev, and upcall_cache::uc_acquire_expire.
static int mdt_identity_expire_seq_show (struct seq_file * m, void * data) [static]
Definition at line 215 of file mdt_lproc.c.
References mdt_dev(), mdt_device::mdt_identity_cache, obd_device::obd_lu_dev, and upcall_cache::uc_entry_expire.
static ssize_t mdt_identity_expire_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Definition at line 225 of file mdt_lproc.c.
References mdt_dev(), mdt_device::mdt_identity_cache, obd_device::obd_lu_dev, and upcall_cache::uc_entry_expire.
static int mdt_identity_upcall_seq_show (struct seq_file * m, void * data) [static]
Definition at line 278 of file mdt_lproc.c.
References mdt_dev(), mdt_device::mdt_identity_cache, obd_device::obd_lu_dev, upcall_cache::uc_upcall, and upcall_cache::uc_upcall_rwlock.
static ssize_t mdt_identity_upcall_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Definition at line 291 of file mdt_lproc.c.
References CDEBUG, CERROR, CWARN, D_CONFIG, GOTO, mdt_dev(), mdt_device::mdt_identity_cache, mdt_obd_name(), mdt_device::mdt_opts, mdt_device::mo_acl, OBD_ALLOC, OBD_FREE, obd_device::obd_lu_dev, RETURN, UC_CACHE_UPCALL_MAXPATH, upcall_cache::uc_name, upcall_cache::uc_upcall, and upcall_cache::uc_upcall_rwlock.
static int mdt_nosquash_nids_seq_show (struct seq_file * m, void * data) [static]
Definition at line 611 of file mdt_lproc.c.
References cfs_print_nidlist(), list_empty(), mdt_dev(), mdt_device::mdt_squash, obd_device::obd_lu_dev, root_squash_info::rsi_nosquash_nids, and root_squash_info::rsi_sem.
static ssize_t mdt_nosquash_nids_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Definition at line 632 of file mdt_lproc.c.
References mdt_dev(), mdt_obd_name(), mdt_device::mdt_squash, and obd_device::obd_lu_dev.
void mdt_procfs_fini (struct mdt_device * mdt)
Definition at line 1010 of file mdt_lproc.c.
References hsm_cdt_procfs_fini(), lprocfs_free_md_stats(), lprocfs_free_obd_stats(), lprocfs_free_per_client_stats(), lprocfs_job_stats_fini(), lprocfs_obd_cleanup(), lprocfs_remove_proc_entry(), mdt2obd_dev(), and obd_device::obd_proc_exports_entry.
Referenced by mdt_fini(), and mdt_init0().
int mdt_procfs_init (struct mdt_device * mdt, const char * name)
Definition at line 966 of file mdt_lproc.c.
References CERROR, ENTRY, hsm_cdt_procfs_init(), LASSERT, lproc_mdt_attach_rename_seqstat(), LPROC_MDT_LAST, lprocfs_add_simple(), lprocfs_alloc_md_stats(), lprocfs_job_stats_init(), lprocfs_obd_setup(), mdt2obd_dev(), mdt_obd_name(), mdt_stats_counter_init(), obd_device::obd_md_stats, obd_device::obd_proc_entry, obd_device::obd_proc_exports_entry, obd_device::obd_vars, and RETURN.
Referenced by mdt_init0().
void mdt_rename_counter_tally (struct mdt_thread_info * info, struct mdt_device * mdt, struct ptlrpc_request * req, struct mdt_object * src, struct mdt_object * tgt)
Definition at line 172 of file mdt_lproc.c.
References CERROR, DFID, rename_stats::hist, lu_attr::la_size, LPROC_MDT_CROSSDIR_RENAME, LPROC_MDT_SAMEDIR_RENAME, lprocfs_oh_tally_log2(), md_attr::ma_attr, MA_INODE, md_attr::ma_need, md_attr::ma_valid, mdt_counter_incr(), mdt_obd_name(), mdt_object_child(), mdt_object_fid(), mdt_device::mdt_rename_stats, mo_attr_get(), mdt_thread_info::mti_attr, mdt_thread_info::mti_env, PFID, RENAME_CROSSDIR_SRC_SIZE, RENAME_CROSSDIR_TGT_SIZE, and RENAME_SAMEDIR_SIZE.
Referenced by mdt_reint_rename_internal().
static int mdt_rename_stats_seq_show (struct seq_file * seq, void * v) [static]
Definition at line 137 of file mdt_lproc.c.
References mdt_device::mdt_rename_stats, and rename_stats_show().
static ssize_t mdt_rename_stats_seq_write (struct file * file, const char __user * buf, size_t len, loff_t * off) [static]
Definition at line 147 of file mdt_lproc.c.
References rename_stats::hist, lprocfs_oh_clear(), mdt_device::mdt_rename_stats, and RENAME_LAST.
static int mdt_root_squash_seq_show (struct seq_file * m, void * data) [static]
Definition at line 586 of file mdt_lproc.c.
References mdt_dev(), mdt_device::mdt_squash, obd_device::obd_lu_dev, root_squash_info::rsi_gid, and root_squash_info::rsi_uid.
static ssize_t mdt_root_squash_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Definition at line 598 of file mdt_lproc.c.
References mdt_dev(), mdt_obd_name(), mdt_device::mdt_squash, and obd_device::obd_lu_dev.
static int mdt_sec_level_seq_show (struct seq_file * m, void * data) [static]
Definition at line 518 of file mdt_lproc.c.
References lu_target::lut_sec_level, mdt_dev(), mdt_device::mdt_lut, and obd_device::obd_lu_dev.
static ssize_t mdt_sec_level_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Definition at line 528 of file mdt_lproc.c.
References CWARN, LUSTRE_SEC_ALL, LUSTRE_SEC_NONE, LUSTRE_SEC_SPECIFY, lu_target::lut_sec_level, mdt_dev(), mdt_device::mdt_lut, and obd_device::obd_lu_dev.
static int mdt_site_stats_seq_show (struct seq_file * m, void * data) [static]
Definition at line 425 of file mdt_lproc.c.
References lu_site_stats_seq_print(), mdt_dev(), mdt_lu_site(), and obd_device::obd_lu_dev.
static int mdt_slc_seq_show (struct seq_file * m, void * data) [static]
Show MDT policy for handling dirty metadata under a lock being cancelled.
Parameters:
[in] m seq_file handle
[in] data unused for single entry
Return values:
0 on success
negative value on error
Definition at line 715 of file mdt_lproc.c.
References lu_target::lut_sync_lock_cancel, and obd_device::u.
void mdt_stats_counter_init (struct lprocfs_stats * stats)
Definition at line 944 of file mdt_lproc.c.
References LPROC_MDT_CLOSE, LPROC_MDT_CROSSDIR_RENAME, LPROC_MDT_GETATTR, LPROC_MDT_GETXATTR, LPROC_MDT_LINK, LPROC_MDT_MKDIR, LPROC_MDT_MKNOD, LPROC_MDT_OPEN, LPROC_MDT_RENAME, LPROC_MDT_RMDIR, LPROC_MDT_SAMEDIR_RENAME, LPROC_MDT_SETATTR, LPROC_MDT_SETXATTR, LPROC_MDT_STATFS, LPROC_MDT_SYNC, LPROC_MDT_UNLINK, and lprocfs_counter_init().
Referenced by mdt_export_stats_init(), and mdt_procfs_init().
static int mdt_sync_count_seq_show (struct seq_file * m, void * data) [static]
Show MDT sync count.
Parameters:
[in] m seq_file handle
[in] data unused for single entry
Return values:
0 on success
negative value on error
Definition at line 776 of file mdt_lproc.c.
References lu_target::lut_sync_count, and obd_device::u.
static ssize_t mdt_sync_count_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Definition at line 786 of file mdt_lproc.c.
References lu_target::lut_sync_count, and obd_device::u.
static void rename_stats_show (struct seq_file * seq, struct rename_stats * rename_stats) [static]
Definition at line 116 of file mdt_lproc.c.
References display_rename_stats(), rename_stats::hist, RENAME_CROSSDIR_SRC_SIZE, RENAME_CROSSDIR_TGT_SIZE, and RENAME_SAMEDIR_SIZE.
Referenced by mdt_rename_stats_seq_show().
Variable Documentation
struct lprocfs_vars lprocfs_mdt_obd_vars[] [static]
Definition at line 823 of file mdt_lproc.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.