Lustre: lustre/mdt/mdt_identity.c File Reference
lustre/mdt/mdt_identity.c File Reference
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/mm.h>
#include <linux/kmod.h>
#include <linux/string.h>
#include <linux/stat.h>
#include <linux/errno.h>
#include <linux/version.h>
#include <linux/unistd.h>
#include <asm/uaccess.h>
#include <linux/fs.h>
#include <linux/slab.h>
#include <libcfs/libcfs.h>
#include <obd.h>
#include <obd_class.h>
#include <obd_support.h>
#include <lustre_net.h>
#include <lustre_import.h>
#include <lustre_dlm.h>
#include <lustre_lib.h>
#include "mdt_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_MDS
Functions
static void mdt_identity_entry_init (struct upcall_cache_entry *entry, void *unused)
static void mdt_identity_entry_free (struct upcall_cache *cache, struct upcall_cache_entry *entry)
static int mdt_identity_do_upcall (struct upcall_cache *cache, struct upcall_cache_entry *entry)
static int mdt_identity_parse_downcall (struct upcall_cache *cache, struct upcall_cache_entry *entry, void *args)
struct md_identity * mdt_identity_get (struct upcall_cache *cache, __u32 uid)
void mdt_identity_put (struct upcall_cache *cache, struct md_identity *identity)
void mdt_flush_identity (struct upcall_cache *cache, int uid)
__u32 mdt_identity_get_perm (struct md_identity *identity, __u32 is_rmtclient, lnet_nid_t nid)
int mdt_pack_remote_perm (struct mdt_thread_info *info, struct mdt_object *o, void *buf)
Variables
struct upcall_cache_ops mdt_identity_upcall_cache_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 42 of file mdt_identity.c.
Function Documentation
void mdt_flush_identity (struct upcall_cache * cache, int uid)
Definition at line 236 of file mdt_identity.c.
References __u64, upcall_cache_flush_idle(), and upcall_cache_flush_one().
Referenced by lprocfs_identity_flush_seq_write().
static int mdt_identity_do_upcall (struct upcall_cache * cache, struct upcall_cache_entry * entry) [static]
Definition at line 94 of file mdt_identity.c.
References CDEBUG, CERROR, cfs_timeval_sub(), D_HA, D_INFO, ENTRY, EXIT, GOTO, LPU64, upcall_cache::uc_name, upcall_cache::uc_upcall, upcall_cache::uc_upcall_rwlock, upcall_cache_entry::ue_key, and unlikely.
static void mdt_identity_entry_free (struct upcall_cache * cache, struct upcall_cache_entry * entry) [static]
Definition at line 76 of file mdt_identity.c.
References upcall_cache_entry::identity, LASSERT, md_identity::mi_ginfo, md_identity::mi_nperms, md_identity::mi_perms, OBD_FREE, and upcall_cache_entry::u.
static void mdt_identity_entry_init (struct upcall_cache_entry * entry, void * unused) [static]
Definition at line 70 of file mdt_identity.c.
References upcall_cache_entry::identity, md_identity::mi_uc_entry, and upcall_cache_entry::u.
struct md_identity* mdt_identity_get (struct upcall_cache * cache, __u32 uid) [read]
Definition at line 204 of file mdt_identity.c.
References __u64, upcall_cache_entry::identity, upcall_cache_entry::u, unlikely, and upcall_cache_get_entry().
Referenced by mdt_check_ucred(), mdt_handle_idmap(), new_init_ucred(), and old_init_ucred_common().
__u32 mdt_identity_get_perm (struct md_identity * identity, __u32 is_rmtclient, lnet_nid_t nid)
Definition at line 248 of file mdt_identity.c.
References CFS_SETGRP_PERM, LASSERT, LNET_NID_ANY, md_identity::mi_nperms, md_identity::mi_perms, md_perm::mp_nid, and md_perm::mp_perm.
Referenced by allow_client_chgrp(), mdt_check_ucred(), mdt_getxattr(), mdt_reint_setxattr(), and new_init_ucred().
static int mdt_identity_parse_downcall (struct upcall_cache * cache, struct upcall_cache_entry * entry, void * args) [static]
Definition at line 148 of file mdt_identity.c.
References CDEBUG, CERROR, D_OTHER, ENTRY, identity_downcall_data::idd_gid, identity_downcall_data::idd_groups, identity_downcall_data::idd_ngroups, identity_downcall_data::idd_nperms, identity_downcall_data::idd_perms, identity_downcall_data::idd_uid, upcall_cache_entry::identity, LASSERT, lustre_groups_from_list(), lustre_groups_sort(), md_identity::mi_gid, md_identity::mi_ginfo, md_identity::mi_nperms, md_identity::mi_perms, md_identity::mi_uid, md_perm::mp_nid, md_perm::mp_perm, NGROUPS_MAX, OBD_ALLOC, perm_downcall_data::pdd_nid, perm_downcall_data::pdd_perm, perms, RETURN, size, and upcall_cache_entry::u.
void mdt_identity_put (struct upcall_cache * cache, struct md_identity * identity)
Definition at line 220 of file mdt_identity.c.
References LASSERT, md_identity::mi_uc_entry, and upcall_cache_put_entry().
Referenced by mdt_check_ucred(), mdt_exit_ucred(), mdt_handle_idmap(), and new_init_ucred().
int mdt_pack_remote_perm (struct mdt_thread_info * info, struct mdt_object * o, void * buf)
Definition at line 276 of file mdt_identity.c.
References ENTRY, exp_connect_rmtclient(), LASSERT, mdt_object_child(), mdt_ucred_check(), mo_permission(), mdt_thread_info::mti_env, mdt_thread_info::mti_exp, RETURN, mdt_remote_perm::rp_access_perm, mdt_remote_perm::rp_fsgid, mdt_remote_perm::rp_fsuid, mdt_remote_perm::rp_gid, mdt_remote_perm::rp_uid, lu_ucred::uc_o_fsgid, lu_ucred::uc_o_fsuid, lu_ucred::uc_o_gid, and lu_ucred::uc_o_uid.
Referenced by mdt_finish_open(), and mdt_getattr_internal().
Variable Documentation
struct upcall_cache_ops mdt_identity_upcall_cache_ops
Initial value:
 {
        .init_entry     = mdt_identity_entry_init,
        .free_entry     = mdt_identity_entry_free,
        .do_upcall      = mdt_identity_do_upcall,
        .parse_downcall = mdt_identity_parse_downcall,
}
Definition at line 229 of file mdt_identity.c.
Referenced by mdt_init0().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.