Lustre: lustre/mdt/mdt_xattr.c File Reference
lustre/mdt/mdt_xattr.c File Reference
#include <linux/xattr.h>
#include <obd_class.h>
#include <lustre_nodemap.h>
#include <lustre_acl.h>
#include "mdt_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_MDS
Functions
static int mdt_getxattr_pack_reply (struct mdt_thread_info *info)
static int mdt_getxattr_one (struct mdt_thread_info *info, char *xattr_name, struct md_object *next, struct lu_buf *buf, struct mdt_export_data *med, struct lu_ucred *uc)
static int mdt_getxattr_all (struct mdt_thread_info *info, struct mdt_body *reqbody, struct mdt_body *repbody, struct lu_buf *buf, struct md_object *next)
int mdt_getxattr (struct mdt_thread_info *info)
static int mdt_rmtlsetfacl (struct mdt_thread_info *info, struct md_object *next, const char *xattr_name, ext_acl_xattr_header *header, posix_acl_xattr_header **out)
int mdt_reint_setxattr (struct mdt_thread_info *info, struct mdt_lock_handle *unused)
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 46 of file mdt_xattr.c.
Function Documentation
int mdt_getxattr (struct mdt_thread_info * info)
Definition at line 227 of file mdt_xattr.c.
References buf, CDEBUG, CFS_RMTACL_PERM, D_INFO, D_INODE, DFID, ENTRY, err_serious(), EXIT, exp_connect_rmtclient(), GOTO, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, LBUG, LPROC_MDT_GETXATTR, lu_object_assert_exists(), lu_ucred(), MAY_RGETFACL, mdt_body::mbo_eadatasize, mdt_body::mbo_fid1, mdt_body::mbo_valid, mdt_counter_incr(), mdt_exit_ucred(), mdt_getxattr_all(), mdt_getxattr_one(), mdt_getxattr_pack_reply(), mdt_identity_get_perm(), mdt_info_req(), mdt_init_ucred(), mdt_object_child(), mdt_req2med(), mo_permission(), mo_xattr_list(), mdt_object::mot_obj, mdt_thread_info::mti_body, mdt_thread_info::mti_buf, mdt_thread_info::mti_env, mdt_thread_info::mti_exp, mdt_thread_info::mti_object, mdt_thread_info::mti_pill, lnet_process_id_t::nid, OBD_MD_FLRMTRGETFACL, OBD_MD_FLXATTR, OBD_MD_FLXATTRALL, OBD_MD_FLXATTRLS, PFID, req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_EADATA, RMF_MDT_BODY, RMF_NAME, ptlrpc_request::rq_peer, lu_ucred::uc_identity, and unlikely.
Referenced by mdt_intent_getxattr(), and mdt_tgt_getxattr().
static int mdt_getxattr_all (struct mdt_thread_info * info, struct mdt_body * reqbody, struct mdt_body * repbody, struct lu_buf * buf, struct md_object * next) [static]
Definition at line 161 of file mdt_xattr.c.
References ENTRY, GOTO, lu_buf::lb_buf, lu_buf::lb_len, mdt_body::mbo_aclsize, mdt_body::mbo_eadatasize, mdt_body::mbo_max_mdsize, mdt_getxattr_one(), mdt_info_req(), mdt_req2med(), mdt_ucred(), mo_xattr_list(), mdt_thread_info::mti_env, mdt_thread_info::mti_pill, RCL_SERVER, req_capsule_server_get(), req_capsule_shrink(), RETURN, RMF_EADATA, RMF_EAVALS, and RMF_EAVALS_LENS.
Referenced by mdt_getxattr().
static int mdt_getxattr_one (struct mdt_thread_info * info, char * xattr_name, struct md_object * next, struct lu_buf * buf, struct mdt_export_data * med, struct lu_ucred * uc) [static]
Definition at line 121 of file mdt_xattr.c.
References CDEBUG, CFS_IC_ALL, CFS_IC_MAPPED, CFS_IC_NOTHING, D_INODE, ENTRY, exp_connect_rmtclient(), GOTO, lu_buf::lb_buf, mdt_body::mbo_valid, mdt_export_data::med_idmap, mo_xattr_get(), mdt_thread_info::mti_body, mdt_thread_info::mti_env, mdt_thread_info::mti_exp, OBD_MD_FLRMTLGETFACL, OBD_MD_FLRMTLSETFACL, OBD_MD_FLRMTRGETFACL, and unlikely.
Referenced by mdt_getxattr(), and mdt_getxattr_all().
static int mdt_getxattr_pack_reply (struct mdt_thread_info * info) [static]
Definition at line 56 of file mdt_xattr.c.
References __u64, CDEBUG, CERROR, D_INFO, ENTRY, exp_connect_flags(), LASSERT, LPX64, LU_BUF_NULL, mdt_body::mbo_eadatasize, mdt_body::mbo_valid, mdt_info_req(), mdt_object_child(), mo_xattr_get(), mo_xattr_list(), mdt_thread_info::mti_body, mdt_thread_info::mti_env, mdt_thread_info::mti_object, mdt_thread_info::mti_pill, OBD_CONNECT_XATTR, OBD_FAIL_CHECK, OBD_FAIL_MDS_GETXATTR_PACK, OBD_MD_FLXATTR, OBD_MD_FLXATTRALL, OBD_MD_FLXATTRLS, RCL_SERVER, req_capsule_client_get(), req_capsule_server_pack(), req_capsule_set_size(), RETURN, RMF_EADATA, RMF_EAVALS, RMF_EAVALS_LENS, RMF_NAME, ptlrpc_request::rq_export, and size.
Referenced by mdt_getxattr().
int mdt_reint_setxattr (struct mdt_thread_info * info, struct mdt_lock_handle * unused)
Definition at line 363 of file mdt_xattr.c.
References __u64, buf, CDEBUG, CFS_CAP_SYS_ADMIN, CFS_RMTACL_PERM, cfs_time_current_sec(), CWARN, D_INFO, D_INODE, DFID, ENTRY, err_serious(), EXIT, exp_connect_flags(), exp_connect_rmtclient(), GOTO, LA_CTIME, lu_attr::la_ctime, lu_attr::la_flags, lu_attr::la_valid, LATF_SKIP, lu_buf::lb_buf, lu_buf::lb_len, LCK_EX, lu_name::ln_name, LPROC_MDT_SETXATTR, LPU64, LPX64, lu_ucred(), LU_XATTR_CREATE, LU_XATTR_REPLACE, LUSTRE_POSIX_ACL_MAX_SIZE, md_attr::ma_attr, md_attr::ma_attr_flags, md_capable(), MDS_INODELOCK_LOOKUP, MDS_INODELOCK_PERM, MDS_INODELOCK_UPDATE, MDS_INODELOCK_XATTR, MDS_PERM_BYPASS, mdt_device::mdt_bottom, mdt_counter_incr(), mdt_exit_ucred(), mdt_fail_write(), mdt_identity_get_perm(), mdt_info_req(), mdt_init_ucred_reint(), MDT_LH_PARENT, mdt_lock_reg_init(), mdt_obd_name(), mdt_obj2dt(), mdt_object_child(), mdt_object_find_lock(), mdt_object_unlock_put(), mdt_rmtlsetfacl(), mdt_ucred(), mdt_version_get_check_save(), mo_attr_set(), mo_xattr_del(), mo_xattr_set(), mdt_thread_info::mti_attr, mdt_thread_info::mti_buf, mdt_thread_info::mti_dlm_req, mdt_thread_info::mti_env, mdt_thread_info::mti_exp, mdt_thread_info::mti_lh, mdt_thread_info::mti_mdt, mdt_thread_info::mti_rr, lnet_process_id_t::nid, NODEMAP_CLIENT_TO_FS, nodemap_map_acl(), OBD_CONNECT_XATTR, OBD_FAIL_CHECK, OBD_FAIL_MDS_SETXATTR, OBD_FAIL_MDS_SETXATTR_WRITE, OBD_MD_FLCTIME, OBD_MD_FLRMTLSETFACL, OBD_MD_FLRMTRSETFACL, OBD_MD_FLXATTR, OBD_MD_FLXATTRRM, PFID, RETURN, ptlrpc_request::rq_export, ptlrpc_request::rq_peer, mdt_reint_record::rr_eadata, mdt_reint_record::rr_eadatalen, mdt_reint_record::rr_fid1, mdt_reint_record::rr_name, tgt_vbr_obj_set(), lu_ucred::uc_identity, unlikely, XATTR_NAME_ACL_ACCESS, XATTR_NAME_ACL_DEFAULT, XATTR_NAME_FID, XATTR_NAME_HSM, XATTR_NAME_LFSCK_NAMESPACE, XATTR_NAME_LINK, XATTR_NAME_LMA, XATTR_NAME_LMV, XATTR_NAME_LOV, XATTR_NAME_SOM, XATTR_NAME_VERSION, XATTR_TRUSTED_PREFIX, and XATTR_USER_PREFIX.
static int mdt_rmtlsetfacl (struct mdt_thread_info * info, struct md_object * next, const char * xattr_name, ext_acl_xattr_header * header, posix_acl_xattr_header ** out) [static]
Definition at line 316 of file mdt_xattr.c.
References buf, CERROR, ENTRY, EXIT, GOTO, lu_buf::lb_buf, lu_buf::lb_len, LU_BUF_NULL, mdt_info_req(), mdt_req2med(), mdt_ucred(), mdt_export_data::med_idmap, mo_xattr_get(), mdt_thread_info::mti_buf, mdt_thread_info::mti_env, OBD_ALLOC_LARGE, OBD_FREE_LARGE, RETURN, and unlikely.
Referenced by mdt_reint_setxattr().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.