Lustre: lustre/mdt/mdt_reint.c File Reference
lustre/mdt/mdt_reint.c File Reference
#include <lprocfs_status.h>
#include "mdt_internal.h"
#include <lustre_lmv.h>
Data Structures
struct mdt_lock_list
struct mdt_reinter
Defines
#define DEBUG_SUBSYSTEM S_MDS
Functions
static void mdt_reint_init_ma (struct mdt_thread_info *info, struct md_attr *ma)
static void mdt_obj_version_get (struct mdt_thread_info *info, struct mdt_object *o, __u64 *version)
Get version of object by fid.
static int mdt_version_check (struct ptlrpc_request *req, __u64 version, int idx)
Check version is correct.
static void mdt_version_save (struct ptlrpc_request *req, __u64 version, int idx)
Save pre-versions in reply.
static void mdt_enoent_version_save (struct mdt_thread_info *info, int idx)
Save enoent version, it is needed when it is obvious that object doesn't exist, e.g.
void mdt_version_get_save (struct mdt_thread_info *info, struct mdt_object *mto, int idx)
Get version from disk and save in reply buffer.
int mdt_version_get_check (struct mdt_thread_info *info, struct mdt_object *mto, int idx)
Get version from disk and check it, no save in reply.
int mdt_version_get_check_save (struct mdt_thread_info *info, struct mdt_object *mto, int idx)
Get version from disk and check if recovery or just save.
static int mdt_lookup_version_check (struct mdt_thread_info *info, struct mdt_object *p, const struct lu_name *lname, struct lu_fid *fid, int idx)
Lookup with version checking.
static int mdt_remote_permission_check (struct mdt_thread_info *info)
static int mdt_remote_permission (struct mdt_thread_info *info)
mdt_remote_permission: Check whether the remote operation is permitted,
static int mdt_unlock_slaves (struct mdt_thread_info *mti, struct mdt_object *obj, __u64 ibits, struct mdt_lock_handle *s0_lh, struct mdt_object *s0_obj, struct ldlm_enqueue_info *einfo, int decref)
static int mdt_init_slaves (struct mdt_thread_info *mti, struct mdt_object *obj, struct lu_fid *fid)
static int mdt_lock_slaves (struct mdt_thread_info *mti, struct mdt_object *obj, enum ldlm_mode mode, __u64 ibits, struct lu_fid *s0_fid, struct mdt_lock_handle *s0_lh, struct mdt_object **s0_objp, struct ldlm_enqueue_info *einfo)
Lock slave stripes if necessary, the lock handles of slave stripes will be stored in einfo->ei_cbdata.
static int mdt_md_create (struct mdt_thread_info *info)
static int mdt_attr_set (struct mdt_thread_info *info, struct mdt_object *mo, struct md_attr *ma)
int mdt_add_dirty_flag (struct mdt_thread_info *info, struct mdt_object *mo, struct md_attr *ma)
Check HSM flags and add HS_DIRTY flag if relevant.
static int mdt_reint_setattr (struct mdt_thread_info *info, struct mdt_lock_handle *lhc)
static int mdt_reint_create (struct mdt_thread_info *info, struct mdt_lock_handle *lhc)
static int mdt_reint_unlink (struct mdt_thread_info *info, struct mdt_lock_handle *lhc)
static int mdt_reint_link (struct mdt_thread_info *info, struct mdt_lock_handle *lhc)
static int mdt_pdir_hash_lock (struct mdt_thread_info *info, struct mdt_lock_handle *lh, struct mdt_object *obj, __u64 ibits, bool cos_incompat)
lock the part of the directory according to the hash of the name (lh->mlh_pdo_hash) in parallel directory lock.
static int mdt_rename_lock (struct mdt_thread_info *info, struct lustre_handle *lh)
Get BFL lock for rename or migrate process.
static void mdt_rename_unlock (struct lustre_handle *lh)
static int mdt_is_subdir (struct mdt_thread_info *info, struct mdt_object *dir, const struct lu_fid *fid)
static void mdt_unlock_list (struct mdt_thread_info *info, struct list_head *list, int rc)
static int mdt_lock_objects_in_linkea (struct mdt_thread_info *info, struct mdt_object *obj, struct mdt_object *pobj, struct list_head *lock_list)
static int mdt_reint_migrate_internal (struct mdt_thread_info *info, struct mdt_lock_handle *lhc)
static struct mdt_object * mdt_object_find_check (struct mdt_thread_info *info, const struct lu_fid *fid, int idx)
static int mdt_object_lock_save (struct mdt_thread_info *info, struct mdt_object *dir, struct mdt_lock_handle *lh, int idx, bool cos_incompat)
static int mdt_reint_rename_internal (struct mdt_thread_info *info, struct mdt_lock_handle *lhc)
For DNE phase I, only these renames are allowed mv src_p/src_c tgt_p/tgt_c 1.
static int mdt_reint_rename_or_migrate (struct mdt_thread_info *info, struct mdt_lock_handle *lhc, bool rename)
static int mdt_reint_rename (struct mdt_thread_info *info, struct mdt_lock_handle *lhc)
static int mdt_reint_migrate (struct mdt_thread_info *info, struct mdt_lock_handle *lhc)
int mdt_reint_rec (struct mdt_thread_info *info, struct mdt_lock_handle *lhc)
Variables
static struct mdt_reinter mdt_reinters []
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 47 of file mdt_reint.c.
Function Documentation
int mdt_add_dirty_flag (struct mdt_thread_info * info, struct mdt_object * mo, struct md_attr * ma)
Check HSM flags and add HS_DIRTY flag if relevant.
A file could be set dirty only if it has a copy in the backend (HS_EXISTS) and is not RELEASED.
Definition at line 678 of file mdt_reint.c.
References CERROR, DFID, ENTRY, HS_DIRTY, HS_EXISTS, HS_RELEASED, LCK_PW, md_attr::ma_hsm, MA_HSM, md_attr::ma_need, md_attr::ma_valid, MDS_INODELOCK_XATTR, mdt_attr_get_complex(), mdt_hsm_attr_set(), MDT_LH_CHILD, mdt_lock_reg_init(), mdt_object_fid(), mdt_object_lock(), mdt_object_unlock(), md_hsm::mh_flags, mdt_thread_info::mti_lh, PFID, and RETURN.
Referenced by mdt_ctxt_add_dirty_flag(), mdt_mfd_close(), and mdt_reint_setattr().
static int mdt_attr_set (struct mdt_thread_info * info, struct mdt_object * mo, struct md_attr * ma) [static]
Definition at line 596 of file mdt_reint.c.
References __u64, ENTRY, EXIT, GOTO, LA_CTIME, LA_FLAGS, LA_GID, LA_MODE, LA_UID, lu_attr::la_valid, LCK_PW, md_attr::ma_attr, md_attr::ma_attr_flags, MDS_INODELOCK_LOOKUP, MDS_INODELOCK_PERM, MDS_INODELOCK_UPDATE, MDS_VTX_BYPASS, mdt_device::mdt_bottom, mdt_fail_write(), mdt_init_slaves(), MDT_LH_LOCAL, MDT_LH_PARENT, mdt_lock_reg_init(), mdt_lock_slaves(), mdt_obj2dt(), mdt_object_child(), mdt_object_unlock(), mdt_reint_object_lock(), mdt_unlock_slaves(), mdt_version_get_check_save(), mo_attr_set(), mdt_object::mot_lov_mutex, mdt_thread_info::mti_einfo, mdt_thread_info::mti_env, mdt_thread_info::mti_lh, mdt_thread_info::mti_mdt, mdt_thread_info::mti_tmp_fid1, OBD_FAIL_MDS_REINT_SETATTR_WRITE, RETURN, tgt_vbr_obj_set(), and unlikely.
Referenced by mdt_reint_setattr().
static void mdt_enoent_version_save (struct mdt_thread_info * info, int idx) [static]
Save enoent version, it is needed when it is obvious that object doesn't exist, e.g.
child during create.
Definition at line 135 of file mdt_reint.c.
References ENOENT_VERSION, mdt_info_req(), mdt_version_save(), mdt_thread_info::mti_ver, and req_is_replay().
Referenced by mdt_md_create(), and mdt_reint_rename_internal().
static int mdt_init_slaves (struct mdt_thread_info * mti, struct mdt_object * obj, struct lu_fid * fid) [static]
Definition at line 336 of file mdt_reint.c.
References buf, ENTRY, fid_le_to_cpu(), lu_buf::lb_buf, lu_buf::lb_len, le32_to_cpu, lmv_mds_md_v1::lmv_magic, LMV_MAGIC_V1, lmv_mds_md_v1::lmv_stripe_fids, lu_object_header::loh_attr, mdt_big_xattr_get(), mdt_object_child(), mo_xattr_get(), mdt_object::mot_header, mdt_thread_info::mti_big_lmm, mdt_thread_info::mti_big_lmmsize, mdt_thread_info::mti_buf, mdt_thread_info::mti_env, mdt_thread_info::mti_xattr_buf, RETURN, and XATTR_NAME_LMV.
Referenced by mdt_attr_set(), mdt_lock_slaves(), mdt_md_create(), and mdt_reint_unlink().
static int mdt_is_subdir (struct mdt_thread_info * info, struct mdt_object * dir, const struct lu_fid * fid) [static]
Definition at line 1308 of file mdt_reint.c.
References CERROR, DFID, ENTRY, lu_object_header::loh_fid, lu_fid_eq(), mdo_is_subdir(), mdt_obd_name(), mdt_object_child(), mdt_object_exists(), mdt_object::mot_header, mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, PFID, and RETURN.
Referenced by mdt_reint_rename_internal().
static int mdt_lock_objects_in_linkea (struct mdt_thread_info * info, struct mdt_object * obj, struct mdt_object * pobj, struct list_head * lock_list) [static]
Definition at line 1362 of file mdt_reint.c.
References buf, CDEBUG, CWARN, D_INFO, DFID, ENTRY, GOTO, INIT_LIST_HEAD, LASSERT, lu_buf::lb_buf, LCK_PW, linkea_data::ld_buf, linkea_data::ld_lee, linkea_data::ld_leh, linkea_data::ld_reclen, ldlm_handle2lock(), LDLM_LOCK_PUT, ldlm_set_atomic_cb, link_ea_header::leh_reccount, linkea_entry_unpack(), list_add_tail(), list_for_each_entry, lu_name::ln_name, lock_res_and_lock(), lu_buf_check_and_alloc(), lu_object_attr(), MDS_INODELOCK_UPDATE, mdt_links_read(), mdt_lock_pdo_init(), mdt_obd_name(), mdt_object_exists(), mdt_object_find(), mdt_object_lock(), mdt_object_put(), mdt_object_remote(), mdt_object_unlock_put(), mdt_reint_object_lock_try(), mdt_unlock_list(), mdt_lock_handle::mlh_rreg_lh, mdt_lock_list::mll_lh, mdt_lock_list::mll_list, mdt_lock_list::mll_obj, mdt_object::mot_obj, mdt_thread_info::mti_big_buf, mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, OBD_ALLOC_PTR, OBD_FREE_PTR, PFID, retry_count, RETURN, and unlock_res_and_lock().
Referenced by mdt_reint_migrate_internal().
static int mdt_lock_slaves (struct mdt_thread_info * mti, struct mdt_object * obj, enum ldlm_mode mode, __u64 ibits, struct lu_fid * s0_fid, struct mdt_lock_handle * s0_lh, struct mdt_object ** s0_objp, struct ldlm_enqueue_info * einfo) [static]
Lock slave stripes if necessary, the lock handles of slave stripes will be stored in einfo->ei_cbdata.
Definition at line 378 of file mdt_reint.c.
References ldlm_inodebits::bits, ldlm_enqueue_info::ei_cb_bl, ldlm_enqueue_info::ei_cb_cp, ldlm_enqueue_info::ei_cb_local_bl, ldlm_enqueue_info::ei_enq_slave, ldlm_enqueue_info::ei_mode, ldlm_enqueue_info::ei_namespace, ldlm_enqueue_info::ei_type, ENTRY, ldlm_policy_data::l_inodebits, LASSERT, ldlm_completion_ast(), LDLM_IBITS, lu_object_header::loh_attr, lu_fid_eq(), mdt_blocking_ast(), mdt_init_slaves(), mdt_device::mdt_namespace, mdt_object_child(), mdt_object_fid(), mdt_object_find(), mdt_object_put(), mdt_reint_object_lock(), mdt_remote_blocking_ast(), mo_object_lock(), mdt_object::mot_header, mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, mdt_thread_info::mti_policy, and RETURN.
Referenced by mdt_attr_set(), mdt_md_create(), and mdt_reint_unlink().
static int mdt_lookup_version_check (struct mdt_thread_info * info, struct mdt_object * p, const struct lu_name * lname, struct lu_fid * fid, int idx) [static]
Lookup with version checking.
This checks version of 'name'. Many reint functions uses 'name' for child not FID, therefore we need to get object by name and check its version.
Definition at line 196 of file mdt_reint.c.
References ENOENT_VERSION, likely, mdo_lookup(), mdt_info_req(), mdt_obj_version_get(), mdt_object_child(), mdt_object_find(), mdt_object_put(), mdt_version_check(), mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, mdt_thread_info::mti_spec, mdt_thread_info::mti_ver, and req_is_replay().
Referenced by mdt_md_create(), mdt_reint_link(), mdt_reint_migrate_internal(), mdt_reint_rename_internal(), and mdt_reint_unlink().
static int mdt_md_create (struct mdt_thread_info * info) [static]
Definition at line 436 of file mdt_reint.c.
References D_INODE, DEBUG_REQ, DFID, DNAME, dt_directory_features, ENTRY, fid_is_md_operative(), GOTO, lu_attr::la_mode, LCK_PW, md_attr::ma_attr, MA_INODE, md_attr::ma_need, md_attr::ma_valid, mdo_create(), MDS_INODELOCK_UPDATE, mdt_attr_get_complex(), mdt_device::mdt_bottom, mdt_dlm_mode2mdl_mode(), mdt_enoent_version_save(), mdt_fail_write(), mdt_info_req(), mdt_init_slaves(), MDT_LH_CHILD, MDT_LH_LOCAL, MDT_LH_PARENT, mdt_lock_handle_init(), mdt_lock_pdo_init(), mdt_lock_reg_init(), mdt_lock_slaves(), mdt_lookup_version_check(), mdt_obj2dt(), mdt_object_child(), mdt_object_exists(), mdt_object_fid(), mdt_object_find(), mdt_object_lock(), mdt_object_new(), mdt_object_put(), mdt_object_remote(), mdt_object_unlock(), mdt_pack_attr2body(), mdt_reint_object_lock(), mdt_remote_permission(), mdt_slc_is_enabled(), mdt_unlock_slaves(), mdt_version_get_check_save(), mdt_lock_handle::mlh_pdo_mode, mdt_thread_info::mti_attr, mdt_thread_info::mti_einfo, mdt_thread_info::mti_env, mdt_thread_info::mti_lh, mdt_thread_info::mti_mdt, mdt_thread_info::mti_pill, mdt_thread_info::mti_rr, mdt_thread_info::mti_spec, mdt_thread_info::mti_tmp_fid1, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_BAD_SLAVE_NAME, OBD_FAIL_MDS_REINT_CREATE_WRITE, PFID, PNAME, req_capsule_server_get(), RETURN, RMF_MDT_BODY, mdt_reint_record::rr_fid1, mdt_reint_record::rr_fid2, mdt_reint_record::rr_name, md_op_spec::sp_cr_lookup, md_op_spec::sp_cr_mode, md_op_spec::sp_feat, tgt_vbr_obj_set(), and unlikely.
Referenced by mdt_reint_create().
static void mdt_obj_version_get (struct mdt_thread_info * info, struct mdt_object * o, __u64 * version) [static]
Get version of object by fid.
Return real version or ENOENT_VERSION if object doesn't exist
Definition at line 65 of file mdt_reint.c.
References CDEBUG, D_INODE, DFID, dt_version_get(), ENOENT_VERSION, fid_is_obf(), LASSERT, LPX64, mdt_obj2dt(), mdt_object_exists(), mdt_object_fid(), mdt_object_remote(), mdt_thread_info::mti_env, and PFID.
Referenced by mdt_lookup_version_check(), mdt_version_get_check(), mdt_version_get_check_save(), and mdt_version_get_save().
static struct mdt_object* mdt_object_find_check (struct mdt_thread_info * info, const struct lu_fid * fid, int idx) [static, read]
Definition at line 1776 of file mdt_reint.c.
References dir, ENTRY, GOTO, mdt_object_find(), mdt_object_put(), mdt_version_get_check(), mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, and RETURN.
Referenced by mdt_reint_rename_internal().
static int mdt_object_lock_save (struct mdt_thread_info * info, struct mdt_object * dir, struct mdt_lock_handle * lh, int idx, bool cos_incompat) [static]
Definition at line 1799 of file mdt_reint.c.
References MDS_INODELOCK_UPDATE, mdt_reint_object_lock(), and mdt_version_get_save().
Referenced by mdt_reint_rename_internal().
static int mdt_pdir_hash_lock (struct mdt_thread_info * info, struct mdt_lock_handle * lh, struct mdt_object * obj, __u64 ibits, bool cos_incompat) [static]
lock the part of the directory according to the hash of the name (lh->mlh_pdo_hash) in parallel directory lock.
Definition at line 1215 of file mdt_reint.c.
References __u64, ldlm_inodebits::bits, obd_export::exp_handle, fid_build_pdo_res_name(), portals_handle::h_cookie, ldlm_policy_data::l_inodebits, LASSERT, LCK_EX, LCK_PW, LDLM_FL_ATOMIC_CB, LDLM_FL_COS_INCOMPAT, LDLM_FL_LOCAL_ONLY, mdt_fid_lock(), mdt_device::mdt_namespace, mdt_object_fid(), mdt_lock_handle::mlh_pdo_hash, mdt_lock_handle::mlh_reg_lh, mdt_lock_handle::mlh_reg_mode, mdt_thread_info::mti_exp, mdt_thread_info::mti_mdt, mdt_thread_info::mti_policy, and mdt_thread_info::mti_res_id.
Referenced by mdt_reint_rename_internal().
static int mdt_reint_create (struct mdt_thread_info * info, struct mdt_lock_handle * lhc) [static]
Definition at line 826 of file mdt_reint.c.
References CERROR, ENTRY, err_serious(), lu_attr::la_mode, LATF_SKIP, LPROC_MDT_MKDIR, LPROC_MDT_MKNOD, lu_name_is_valid(), md_attr::ma_attr, mdt_counter_incr(), mdt_info_req(), mdt_md_create(), mdt_obd_name(), mdt_thread_info::mti_attr, mdt_thread_info::mti_dlm_req, mdt_thread_info::mti_mdt, mdt_thread_info::mti_rr, OBD_FAIL_CHECK, OBD_FAIL_MDS_REINT_CREATE, RETURN, and mdt_reint_record::rr_name.
static void mdt_reint_init_ma (struct mdt_thread_info * info, struct md_attr * ma) [inline, static]
Definition at line 53 of file mdt_reint.c.
References MA_INODE, md_attr::ma_need, and md_attr::ma_valid.
Referenced by mdt_reint_migrate_internal(), and mdt_reint_rename_internal().
static int mdt_reint_link (struct mdt_thread_info * info, struct mdt_lock_handle * lhc) [static]
check target version by name during replay
Definition at line 1098 of file mdt_reint.c.
References CDEBUG, D_INFO, D_INODE, DEBUG_REQ, DFID, DNAME, ENOENT_VERSION, ENTRY, err_serious(), EXIT, fid_is_md_operative(), GOTO, LATF_SKIP, LCK_EX, LCK_PW, LPROC_MDT_LINK, lu_fid_eq(), mdo_link(), MDS_INODELOCK_UPDATE, MDS_INODELOCK_XATTR, mdt_device::mdt_bottom, mdt_counter_incr(), mdt_fail_write(), mdt_info_req(), MDT_LH_CHILD, MDT_LH_PARENT, mdt_lock_pdo_init(), mdt_lock_reg_init(), mdt_lookup_version_check(), mdt_obd_name(), mdt_obj2dt(), mdt_object_child(), mdt_object_exists(), mdt_object_find(), mdt_object_put(), mdt_object_remote(), mdt_object_unlock(), mdt_reint_object_lock(), mdt_version_get_check_save(), mdt_version_save(), mdt_thread_info::mti_attr, mdt_thread_info::mti_dlm_req, mdt_thread_info::mti_env, mdt_thread_info::mti_lh, mdt_thread_info::mti_mdt, mdt_thread_info::mti_rr, mdt_thread_info::mti_tmp_fid1, mdt_thread_info::mti_ver, OBD_FAIL_CHECK, OBD_FAIL_MDS_REINT_LINK, OBD_FAIL_MDS_REINT_LINK_WRITE, OBD_FAIL_MDS_RENAME3, OBD_FAIL_TIMEOUT, PFID, PNAME, req_is_replay(), RETURN, mdt_reint_record::rr_fid1, mdt_reint_record::rr_fid2, mdt_reint_record::rr_name, and tgt_vbr_obj_set().
static int mdt_reint_migrate (struct mdt_thread_info * info, struct mdt_lock_handle * lhc) [static]
Definition at line 2185 of file mdt_reint.c.
References mdt_reint_rename_or_migrate().
static int mdt_reint_migrate_internal (struct mdt_thread_info * info, struct mdt_lock_handle * lhc) [static]
Definition at line 1503 of file mdt_reint.c.
References __u64, close_data::cd_handle, CDEBUG, CERROR, D_INODE, DFID, DNAME, ELDLM_OK, ENTRY, fid_is_md_operative(), fid_is_sane(), fid_zero(), GOTO, INIT_LIST_HEAD, ldlm_lock::l_resource, LCK_EX, LCK_PW, LDLM_DEBUG, ldlm_handle2lock(), ldlm_is_cancel, ldlm_lock_cancel(), LDLM_LOCK_PUT, ldlm_reprocess_all(), LMV_HASH_FLAG_MIGRATION, lmv_mds_md_v1::lmv_hash_type, lmv_le_to_cpu(), lmv_mds_md::lmv_md_v1, lmv_mds_md_v1::lmv_stripe_fids, lock_res_and_lock(), lu_fid_eq(), lu_object_attr(), md_attr::ma_hsm, MA_HSM, md_attr::ma_lmv, MA_LMV, md_attr::ma_lmv_size, md_attr::ma_need, md_attr::ma_valid, mdt_body::mbo_valid, mdo_migrate(), MDS_INODELOCK_LAYOUT, MDS_INODELOCK_LOOKUP, MDS_INODELOCK_UPDATE, mdt_attr_get_complex(), mdt_device::mdt_bottom, mdt_close_internal(), mdt_fail_write(), mdt_info_req(), MDT_LH_CHILD, MDT_LH_OLD, MDT_LH_PARENT, mdt_lock_objects_in_linkea(), mdt_lock_pdo_init(), mdt_lock_reg_init(), mdt_lookup_version_check(), mdt_device::mdt_md_root_fid, mdt_obd_name(), mdt_object_child(), mdt_object_fid(), mdt_object_find(), mdt_object_put(), mdt_object_remote(), mdt_object_unlock(), mdt_reint_init_ma(), mdt_reint_object_lock(), mdt_remote_object_lock(), mdt_remote_permission(), mdt_stripe_get(), mdt_unlock_list(), mdt_version_get_check_save(), md_hsm::mh_flags, mdt_lock_handle::mlh_rreg_lh, mdt_lock_handle::mlh_rreg_mode, mdt_object::mot_obj, mdt_object::mot_open_sem, mdt_thread_info::mti_attr, mdt_thread_info::mti_env, mdt_thread_info::mti_lh, mdt_thread_info::mti_mdt, mdt_thread_info::mti_pill, mdt_thread_info::mti_rr, mdt_thread_info::mti_spec, mdt_thread_info::mti_tmp_fid1, mdt_thread_info::mti_xattr_buf, OBD_FAIL_MDS_REINT_RENAME_WRITE, OBD_MD_CLOSE_INTENT_EXECED, PFID, PNAME, RCL_CLIENT, req_capsule_client_get(), req_capsule_field_present(), req_capsule_server_get(), RETURN, RMF_CLOSE_DATA, RMF_MDT_BODY, RMF_MDT_EPOCH, mdt_reint_record::rr_fid1, mdt_reint_record::rr_fid2, mdt_reint_record::rr_name, md_op_spec::sp_migrate_close, unlock_res_and_lock(), and XATTR_NAME_LMV.
Referenced by mdt_reint_rename_or_migrate().
int mdt_reint_rec (struct mdt_thread_info * info, struct mdt_lock_handle * lhc)
Definition at line 2235 of file mdt_reint.c.
References ARRAY_SIZE, ENTRY, lprocfs_counter_incr(), mdt_info_req(), mdt_reinter::mr_extra_opc, mdt_reinter::mr_handler, mdt_thread_info::mti_rr, PTLRPC_LAST_CNTR, ptlrpc_req2svc(), RETURN, and mdt_reint_record::rr_opcode.
Referenced by mdt_reint_internal().
static int mdt_reint_rename (struct mdt_thread_info * info, struct mdt_lock_handle * lhc) [static]
Definition at line 2179 of file mdt_reint.c.
References mdt_reint_rename_or_migrate().
static int mdt_reint_rename_internal (struct mdt_thread_info * info, struct mdt_lock_handle * lhc) [static]
For DNE phase I, only these renames are allowed mv src_p/src_c tgt_p/tgt_c 1.
src_p/src_c/tgt_p/tgt_c are in the same MDT. 2. src_p and tgt_p are same directory, and tgt_c does not exists. In this case, all of modification will happen in the MDT where ithesource parent is, only one remote update is needed, i.e. set c_time/m_time on the child. And tgt_c will be still in the same MDT as the original src_c.
Definition at line 1833 of file mdt_reint.c.
References __u64, D_INODE, DEBUG_REQ, DFID, DNAME, ELDLM_OK, ENTRY, EXIT, fid_is_md_operative(), fid_zero(), GOTO, LASSERT, LCK_EX, LCK_PW, LPROC_MDT_RENAME, lu_fid_eq(), lu_object_attr(), mdt_body::mbo_fid1, mdt_body::mbo_valid, mdo_rename(), MDS_INODELOCK_LOOKUP, MDS_INODELOCK_UPDATE, MDS_INODELOCK_XATTR, mdt_device::mdt_bottom, mdt_counter_incr(), mdt_enoent_version_save(), mdt_fail_write(), mdt_handle_last_unlink(), mdt_info_req(), mdt_is_subdir(), MDT_LH_CHILD, MDT_LH_NEW, MDT_LH_OLD, MDT_LH_PARENT, mdt_lock_pdo_init(), mdt_lock_reg_init(), mdt_lookup_version_check(), mdt_obj2dt(), mdt_object_child(), mdt_object_fid(), mdt_object_find(), mdt_object_find_check(), mdt_object_get(), mdt_object_lock_save(), mdt_object_put(), mdt_object_remote(), mdt_object_unlock(), mdt_pdir_hash_lock(), mdt_reint_init_ma(), mdt_reint_object_lock(), mdt_remote_object_lock(), mdt_rename_counter_tally(), mdt_version_get_save(), mdt_lock_handle::mlh_pdo_hash, mdt_lock_handle::mlh_rreg_lh, mdt_lock_handle::mlh_rreg_mode, mdt_object::mot_lov_mutex, mdt_object::mot_obj, mdt_thread_info::mti_attr, mdt_thread_info::mti_env, mdt_thread_info::mti_lh, mdt_thread_info::mti_mdt, mdt_thread_info::mti_pill, mdt_thread_info::mti_rr, mdt_thread_info::mti_tmp_fid1, mdt_thread_info::mti_tmp_fid2, OBD_FAIL_MDS_PDO_LOCK2, OBD_FAIL_MDS_REINT_RENAME_WRITE, OBD_FAIL_MDS_RENAME, OBD_FAIL_MDS_RENAME2, OBD_FAIL_MDS_RENAME3, OBD_FAIL_MDS_RENAME4, OBD_FAIL_TIMEOUT, OBD_MD_FLID, OBD_MD_MDS, PFID, PNAME, req_capsule_server_get(), RETURN, RMF_MDT_BODY, mdt_reint_record::rr_fid1, mdt_reint_record::rr_fid2, mdt_reint_record::rr_name, mdt_reint_record::rr_tgt_name, and tgt_vbr_obj_set().
Referenced by mdt_reint_rename_or_migrate().
static int mdt_reint_rename_or_migrate (struct mdt_thread_info * info, struct mdt_lock_handle * lhc, bool rename) [static]
Definition at line 2139 of file mdt_reint.c.
References CERROR, ENTRY, fid_is_md_operative(), LATF_SKIP, lustre_handle_is_used(), mdt_info_req(), mdt_obd_name(), mdt_reint_migrate_internal(), mdt_reint_rename_internal(), mdt_rename_lock(), mdt_rename_unlock(), mdt_thread_info::mti_dlm_req, mdt_thread_info::mti_mdt, mdt_thread_info::mti_rr, req_is_replay(), RETURN, mdt_reint_record::rr_fid1, and mdt_reint_record::rr_fid2.
Referenced by mdt_reint_migrate(), and mdt_reint_rename().
static int mdt_reint_setattr (struct mdt_thread_info * info, struct mdt_lock_handle * lhc) [static]
Definition at line 715 of file mdt_reint.c.
References buf, D_INODE, DEBUG_REQ, DFID, ENTRY, EXIT, GOTO, LA_SIZE, lu_attr::la_valid, LATF_SKIP, lu_buf::lb_buf, lu_buf::lb_len, LCK_PW, LPROC_MDT_SETATTR, md_attr::ma_attr, md_attr::ma_attr_flags, MA_INODE, md_attr::ma_lmm, md_attr::ma_lmm_size, md_attr::ma_lmv, MA_LMV, md_attr::ma_lmv_size, MA_LOV, md_attr::ma_need, md_attr::ma_valid, MDS_DATA_MODIFIED, MDS_INODELOCK_XATTR, mdt_add_dirty_flag(), mdt_attr_get_complex(), mdt_attr_set(), mdt_client_compatibility(), mdt_counter_incr(), mdt_fix_reply(), mdt_info_req(), MDT_LH_PARENT, mdt_lock_reg_init(), mdt_object_child(), mdt_object_exists(), mdt_object_fid(), mdt_object_find(), mdt_object_lock(), mdt_object_put(), mdt_object_remote(), mdt_object_unlock(), mdt_pack_attr2body(), mdt_remote_permission(), mdt_write_read(), mo_xattr_set(), MRF_OPEN_TRUNC, mdt_thread_info::mti_attr, mdt_thread_info::mti_buf, mdt_thread_info::mti_dlm_req, mdt_thread_info::mti_env, mdt_thread_info::mti_lh, mdt_thread_info::mti_mdt, mdt_thread_info::mti_pill, mdt_thread_info::mti_rr, PFID, req_capsule_server_get(), RMF_MDT_BODY, mdt_reint_record::rr_fid1, mdt_reint_record::rr_flags, XATTR_NAME_DEFAULT_LMV, and XATTR_NAME_LOV.
static int mdt_reint_unlink (struct mdt_thread_info * info, struct mdt_lock_handle * lhc) [static]
Definition at line 871 of file mdt_reint.c.
References __u64, CDEBUG, CFS_CAP_SYS_ADMIN, D_INFO, D_INODE, DEBUG_REQ, DFID, DNAME, ELDLM_OK, ENTRY, err_serious(), EXIT, fid_is_md_operative(), fid_is_zero(), fid_zero(), GOTO, lu_attr::la_mode, LASSERT, LASSERTF, LATF_SKIP, LCK_EX, LCK_PW, LPROC_MDT_RMDIR, LPROC_MDT_UNLINK, lu_object_is_dying(), lustre_msg_get_flags(), md_attr::ma_attr, MA_INODE, md_attr::ma_need, md_attr::ma_valid, mdt_body::mbo_fid1, mdt_body::mbo_valid, md_capable(), mdo_unlink(), MDS_INODELOCK_LOOKUP, MDS_INODELOCK_UPDATE, mdt_attr_get_complex(), mdt_device::mdt_bottom, mdt_counter_incr(), mdt_fail_write(), mdt_handle_last_unlink(), mdt_info_req(), mdt_init_slaves(), mdt_is_dne_client(), MDT_LH_CHILD, MDT_LH_LOCAL, MDT_LH_PARENT, mdt_lock_pdo_init(), mdt_lock_reg_init(), mdt_lock_slaves(), mdt_lookup_version_check(), mdt_obd_name(), mdt_object_child(), mdt_object_fid(), mdt_object_find(), mdt_object_lock(), mdt_object_put(), mdt_object_remote(), mdt_object_unlock(), mdt_reint_object_lock(), mdt_remote_object_lock(), mdt_ucred(), mdt_unlock_slaves(), mdt_version_get_check_save(), mdt_version_get_save(), mdt_lock_handle::mlh_rreg_lh, mdt_lock_handle::mlh_rreg_mode, mdt_object::mot_header, mdt_object::mot_lov_mutex, MSG_RESENT, mdt_thread_info::mti_attr, mdt_thread_info::mti_dlm_req, mdt_thread_info::mti_einfo, mdt_thread_info::mti_env, mdt_thread_info::mti_lh, mdt_thread_info::mti_mdt, mdt_thread_info::mti_pill, mdt_thread_info::mti_rr, mdt_thread_info::mti_spec, mdt_thread_info::mti_tmp_fid1, mdt_thread_info::mti_tmp_fid2, OBD_FAIL_CHECK, OBD_FAIL_MDS_REINT_UNLINK, OBD_FAIL_MDS_REINT_UNLINK_WRITE, OBD_MD_FLID, OBD_MD_MDS, PFID, PNAME, req_capsule_server_get(), RETURN, RMF_MDT_BODY, ptlrpc_request::rq_export, ptlrpc_request::rq_reqmsg, mdt_reint_record::rr_fid1, mdt_reint_record::rr_fid2, mdt_reint_record::rr_name, and md_op_spec::sp_rm_entry.
static int mdt_remote_permission (struct mdt_thread_info * info) [static]
mdt_remote_permission: Check whether the remote operation is permitted,
Only sysadmin can create remote directory / striped directory, migrate directory and set default stripedEA on directory, unless
lctl set_param mdt.*.enable_remote_dir_gid=allow_gid.
param[in] info: mdt_thread_info.
retval = 0 remote operation is allowed. < 0 remote operation is denied.
Definition at line 250 of file mdt_reint.c.
References lu_attr::la_mode, le32_to_cpu, lmv_user_md, md_attr::ma_attr, MA_LMV, md_attr::ma_valid, mdt_info_req(), mdt_is_dne_client(), mdt_is_striped_client(), mdt_remote_permission_check(), mdt_thread_info::mti_attr, mdt_thread_info::mti_rr, mdt_thread_info::mti_spec, REINT_CREATE, REINT_MIGRATE, REINT_SETATTR, ptlrpc_request::rq_export, mdt_reint_record::rr_opcode, md_op_spec::sp_ea, and md_op_spec::u.
Referenced by mdt_md_create(), mdt_reint_migrate_internal(), and mdt_reint_setattr().
static int mdt_remote_permission_check (struct mdt_thread_info * info) [inline, static]
Definition at line 223 of file mdt_reint.c.
References CFS_CAP_SYS_ADMIN, md_capable(), mdt_device::mdt_enable_remote_dir_gid, mdt_ucred(), mdt_thread_info::mti_mdt, and lu_ucred::uc_gid.
Referenced by mdt_remote_permission().
static int mdt_rename_lock (struct mdt_thread_info * info, struct lustre_handle * lh) [static]
Get BFL lock for rename or migrate process.
Definition at line 1250 of file mdt_reint.c.
References __u64, ldlm_inodebits::bits, ENTRY, obd_export::exp_handle, fid_build_reg_res_name(), portals_handle::h_cookie, ldlm_policy_data::l_inodebits, LCK_EX, ldlm_blocking_ast(), ldlm_cli_enqueue_local(), ldlm_completion_ast(), LDLM_FL_ATOMIC_CB, LDLM_FL_LOCAL_ONLY, LDLM_IBITS, lu_root_fid(), LUSTRE_BFL_FID, LVB_T_NONE, MDS_INODELOCK_UPDATE, mdt_device::mdt_namespace, mdt_object_find(), mdt_object_put(), mdt_remote_object_lock(), mdt_seq_site(), mdt_thread_info::mti_env, mdt_thread_info::mti_exp, mdt_thread_info::mti_mdt, mdt_thread_info::mti_policy, mdt_thread_info::mti_res_id, mdt_thread_info::mti_tmp_fid1, RETURN, and seq_server_site::ss_node_id.
Referenced by mdt_reint_rename_or_migrate().
static void mdt_rename_unlock (struct lustre_handle * lh) [static]
Definition at line 1294 of file mdt_reint.c.
References ENTRY, EXIT, LASSERT, LCK_EX, ldlm_lock_decref_and_cancel(), and lustre_handle_is_used().
Referenced by mdt_reint_rename_or_migrate().
static void mdt_unlock_list (struct mdt_thread_info * info, struct list_head * list, int rc) [static]
Definition at line 1349 of file mdt_reint.c.
References list_del(), list_for_each_entry_safe, mdt_object_unlock_put(), mdt_lock_list::mll_lh, mdt_lock_list::mll_list, mdt_lock_list::mll_obj, and OBD_FREE_PTR.
Referenced by mdt_lock_objects_in_linkea(), and mdt_reint_migrate_internal().
static int mdt_unlock_slaves (struct mdt_thread_info * mti, struct mdt_object * obj, __u64 ibits, struct mdt_lock_handle * s0_lh, struct mdt_object * s0_obj, struct ldlm_enqueue_info * einfo, int decref) [static]
Definition at line 295 of file mdt_reint.c.
References ldlm_inodebits::bits, lustre_handle::cookie, lustre_handle_array::count, ldlm_enqueue_info::ei_cbdata, ldlm_enqueue_info::ei_mode, ENTRY, lustre_handle_array::handles, ldlm_policy_data::l_inodebits, LASSERT, lu_object_header::loh_attr, lustre_handle_is_used(), mdt_lock_reg_init(), mdt_object_child(), mdt_object_unlock(), mdt_object_unlock_put(), mdt_lock_handle::mlh_reg_lh, mdt_lock_handle::mlh_rreg_lh, mo_object_unlock(), mdt_object::mot_header, mdt_thread_info::mti_env, mdt_thread_info::mti_policy, and RETURN.
Referenced by mdt_attr_set(), mdt_md_create(), and mdt_reint_unlink().
static int mdt_version_check (struct ptlrpc_request * req, __u64 version, int idx) [static]
Check version is correct.
Should be called only during replay.
VBR: version is checked always because costs nothing
Sanity check for malformed buffers
Definition at line 83 of file mdt_reint.c.
References __u64, CDEBUG, CERROR, D_INODE, ENTRY, exp_connect_vbr(), obd_export::exp_lock, obd_export::exp_vbr_failed, LASSERT, LPX64, lustre_msg_get_versions(), PTLRPC_NUM_VERSIONS, req_is_replay(), RETURN, ptlrpc_request::rq_export, and ptlrpc_request::rq_reqmsg.
Referenced by mdt_lookup_version_check(), mdt_version_get_check(), and mdt_version_get_check_save().
int mdt_version_get_check (struct mdt_thread_info * info, struct mdt_object * mto, int idx)
Get version from disk and check it, no save in reply.
Definition at line 162 of file mdt_reint.c.
References mdt_info_req(), mdt_obj_version_get(), mdt_version_check(), mdt_thread_info::mti_ver, and req_is_replay().
Referenced by mdt_object_find_check(), and mdt_reint_open().
int mdt_version_get_check_save (struct mdt_thread_info * info, struct mdt_object * mto, int idx)
Get version from disk and check if recovery or just save.
Definition at line 176 of file mdt_reint.c.
References mdt_info_req(), mdt_obj_version_get(), mdt_version_check(), mdt_version_save(), mdt_thread_info::mti_ver, and req_is_replay().
Referenced by mdt_attr_set(), mdt_md_create(), mdt_reint_link(), mdt_reint_migrate_internal(), mdt_reint_setxattr(), and mdt_reint_unlink().
void mdt_version_get_save (struct mdt_thread_info * info, struct mdt_object * mto, int idx)
Get version from disk and save in reply buffer.
Versions are saved in reply only during normal operations not replays.
Definition at line 149 of file mdt_reint.c.
References mdt_info_req(), mdt_obj_version_get(), mdt_version_save(), mdt_thread_info::mti_ver, and req_is_replay().
Referenced by mdt_object_lock_save(), mdt_reint_open(), mdt_reint_rename_internal(), and mdt_reint_unlink().
static void mdt_version_save (struct ptlrpc_request * req, __u64 version, int idx) [static]
Save pre-versions in reply.
Definition at line 116 of file mdt_reint.c.
References __u64, exp_connect_vbr(), LASSERT, lustre_msg_get_versions(), req_is_replay(), ptlrpc_request::rq_export, and ptlrpc_request::rq_repmsg.
Referenced by mdt_enoent_version_save(), mdt_reint_link(), mdt_version_get_check_save(), and mdt_version_get_save().
Variable Documentation
struct mdt_reinter mdt_reinters[] [static]
Definition at line 2196 of file mdt_reint.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.