Lustre: lustre/mdt/mdt_mds.c File Reference
lustre/mdt/mdt_mds.c File Reference
#include <linux/module.h>
#include <obd_support.h>
#include <lustre_net.h>
#include <lustre_export.h>
#include <obd.h>
#include <dt_object.h>
#include <lustre_mds.h>
#include "mdt_internal.h"
#include <lustre_quota.h>
#include <lustre_acl.h>
#include <lustre_param.h>
Data Structures
struct mds_device
Defines
#define DEBUG_SUBSYSTEM S_MDS
Functions
module_param (mdt_num_threads, ulong, 0444)
MODULE_PARM_DESC (mdt_num_threads,"number of MDS service threads to start (deprecated in favor of mds_num_threads)")
module_param (mds_num_threads, ulong, 0444)
MODULE_PARM_DESC (mds_num_threads,"number of MDS service threads to start")
module_param (mds_num_cpts, charp, 0444)
MODULE_PARM_DESC (mds_num_cpts,"CPU partitions MDS threads should run on")
module_param (mds_rdpg_num_threads, ulong, 0444)
MODULE_PARM_DESC (mds_rdpg_num_threads,"number of MDS readpage service threads to start")
module_param (mds_rdpg_num_cpts, charp, 0444)
MODULE_PARM_DESC (mds_rdpg_num_cpts,"CPU partitions MDS readpage threads should run on")
module_param (mds_attr_num_threads, ulong, 0444)
MODULE_PARM_DESC (mds_attr_num_threads,"number of MDS setattr service threads to start")
module_param (mds_attr_num_cpts, charp, 0444)
MODULE_PARM_DESC (mds_attr_num_cpts,"CPU partitions MDS setattr threads should run on")
static void mds_stop_ptlrpc_service (struct mds_device *m)
static int mds_start_ptlrpc_service (struct mds_device *m)
static struct mds_device * mds_dev (struct lu_device *d)
static struct lu_device * mds_device_fini (const struct lu_env *env, struct lu_device *d)
static struct lu_device * mds_device_free (const struct lu_env *env, struct lu_device *d)
LPROC_SEQ_FOPS_RO_TYPE (mds, uuid)
static struct lu_device * mds_device_alloc (const struct lu_env *env, struct lu_device_type *t, struct lustre_cfg *cfg)
LU_TYPE_INIT_FINI (mds,&mdt_thread_key)
static int mds_health_check (const struct lu_env *env, struct obd_device *obd)
int mds_mod_init (void)
void mds_mod_exit (void)
Variables
static unsigned long mdt_num_threads
static unsigned long mds_num_threads
static char * mds_num_cpts
static unsigned long mds_rdpg_num_threads
static char * mds_rdpg_num_cpts
static unsigned long mds_attr_num_threads
static char * mds_attr_num_cpts
static struct lprocfs_vars lprocfs_mds_obd_vars []
static struct
lu_device_type_operations mds_device_type_ops
static struct lu_device_type mds_device_type
static struct obd_ops mds_obd_device_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 38 of file mdt_mds.c.
Function Documentation
LPROC_SEQ_FOPS_RO_TYPE (mds , uuid)
LU_TYPE_INIT_FINI (mds , & mdt_thread_key)
static struct mds_device* mds_dev (struct lu_device * d) [static, read]
Definition at line 443 of file mdt_mds.c.
References md_device::md_lu_dev, and mds_device::mds_md_dev.
Referenced by mds_device_fini(), mds_device_free(), and mds_health_check().
static struct lu_device* mds_device_alloc (const struct lu_env * env, struct lu_device_type * t, struct lustre_cfg * cfg) [static, read]
Definition at line 478 of file mdt_mds.c.
References class_name2obd(), LASSERT, lu_device::ld_obd, lprocfs_obd_setup(), lustre_cfg_string(), md_device_init(), md_device::md_lu_dev, mds_device_free(), mds_device::mds_health_mutex, mds_device::mds_md_dev, mds_start_ptlrpc_service(), OBD_ALLOC_PTR, obd_device::obd_lu_dev, and obd_device::obd_vars.
static struct lu_device* mds_device_fini (const struct lu_env * env, struct lu_device * d) [static, read]
Definition at line 448 of file mdt_mds.c.
References ENTRY, lu_device::ld_obd, lprocfs_obd_cleanup(), mds_dev(), mds_stop_ptlrpc_service(), and RETURN.
static struct lu_device* mds_device_free (const struct lu_env * env, struct lu_device * d) [static, read]
Definition at line 460 of file mdt_mds.c.
References ENTRY, md_device_fini(), mds_dev(), mds_device::mds_md_dev, OBD_FREE_PTR, and RETURN.
Referenced by mds_device_alloc().
static int mds_health_check (const struct lu_env * env, struct obd_device * obd) [static]
Definition at line 543 of file mdt_mds.c.
References mds_dev(), mds_device::mds_fld_service, mds_device::mds_health_mutex, mds_device::mds_mdsc_service, mds_device::mds_mdss_service, mds_device::mds_out_service, mds_device::mds_readpage_service, mds_device::mds_regular_service, mds_device::mds_setattr_service, obd_device::obd_lu_dev, and ptlrpc_service_health_check().
void mds_mod_exit (void)
Definition at line 580 of file mdt_mds.c.
References class_unregister_type(), and LUSTRE_MDS_NAME.
Referenced by mdt_exit(), and mdt_init().
int mds_mod_init (void)
Definition at line 567 of file mdt_mds.c.
References class_register_type(), LCONSOLE_INFO, LUSTRE_MDS_NAME, mds_num_threads, and mdt_num_threads.
Referenced by mdt_init().
static int mds_start_ptlrpc_service (struct mds_device * m) [static]
Definition at line 141 of file mdt_mds.c.
References CERROR, ENTRY, EXIT, FLD_BUFSIZE, FLD_MAXREPSIZE, FLD_MAXREQSIZE, FLD_REQUEST_PORTAL, GOTO, LASSERT, LCT_DT_THREAD, LCT_MD_THREAD, lu_device::ld_obd, LUSTRE_MDT_NAME, md_device::md_lu_dev, MDC_REPLY_PORTAL, mds_attr_num_cpts, mds_attr_num_threads, MDS_BUFSIZE, mds_device::mds_fld_service, MDS_LOV_MAXREPSIZE, MDS_MAXREPSIZE, MDS_MAXREQSIZE, mds_device::mds_md_dev, mds_device::mds_mdsc_service, mds_device::mds_mdss_service, MDS_NBUFS, MDS_NTHRS_BASE, MDS_NTHRS_INIT, MDS_NTHRS_MAX, mds_num_cpts, mds_num_threads, MDS_OTHR_NTHRS_INIT, MDS_OTHR_NTHRS_MAX, mds_device::mds_out_service, MDS_RDPG_NTHRS_BASE, MDS_RDPG_NTHRS_INIT, MDS_RDPG_NTHRS_MAX, mds_rdpg_num_cpts, mds_rdpg_num_threads, MDS_RDPG_THR_FACTOR, MDS_READPAGE_PORTAL, mds_device::mds_readpage_service, MDS_REG_BUFSIZE, MDS_REG_MAXREPSIZE, MDS_REG_MAXREQSIZE, mds_device::mds_regular_service, MDS_REQUEST_PORTAL, MDS_SETA_NTHRS_BASE, MDS_SETA_NTHRS_INIT, MDS_SETA_NTHRS_MAX, MDS_SETA_THR_FACTOR, MDS_SETATTR_PORTAL, mds_device::mds_setattr_service, mds_stop_ptlrpc_service(), MDS_THR_FACTOR, MDT_SERVICE_WATCHDOG_FACTOR, obd_device::obd_proc_entry, OSC_REPLY_PORTAL, OUT_BUFSIZE, OUT_MAXREPSIZE, OUT_MAXREQSIZE, OUT_PORTAL, ptlrpc_service_conf::psc_name, ptlrpc_hpreq_handler(), ptlrpc_register_service(), RETURN, SEQ_BUFSIZE, SEQ_CONTROLLER_PORTAL, SEQ_MAXREPSIZE, SEQ_MAXREQSIZE, SEQ_METADATA_PORTAL, target_print_req, and tgt_request_handle().
Referenced by mds_device_alloc().
static void mds_stop_ptlrpc_service (struct mds_device * m) [static]
Definition at line 103 of file mdt_mds.c.
References ENTRY, EXIT, mds_device::mds_fld_service, mds_device::mds_health_mutex, mds_device::mds_mdsc_service, mds_device::mds_mdss_service, mds_device::mds_out_service, mds_device::mds_readpage_service, mds_device::mds_regular_service, mds_device::mds_setattr_service, and ptlrpc_unregister_service().
Referenced by mds_device_fini(), and mds_start_ptlrpc_service().
module_param (mds_attr_num_cpts , charp , 0444)
module_param (mds_attr_num_threads , ulong , 0444)
module_param (mds_rdpg_num_cpts , charp , 0444)
module_param (mds_rdpg_num_threads , ulong , 0444)
module_param (mds_num_cpts , charp , 0444)
module_param (mds_num_threads , ulong , 0444)
module_param (mdt_num_threads , ulong , 0444)
MODULE_PARM_DESC (mds_attr_num_cpts , "CPU partitions MDS setattr threads should run on")
MODULE_PARM_DESC (mds_attr_num_threads , "number of MDS setattr service threads to start")
MODULE_PARM_DESC (mds_rdpg_num_cpts , "CPU partitions MDS readpage threads should run on")
MODULE_PARM_DESC (mds_rdpg_num_threads , "number of MDS readpage service threads to start")
MODULE_PARM_DESC (mds_num_cpts , "CPU partitions MDS threads should run on")
MODULE_PARM_DESC (mds_num_threads , "number of MDS service threads to start")
MODULE_PARM_DESC (mdt_num_threads , "number of MDS service threads to start (deprecated in favor of mds_num_threads)")
Variable Documentation
struct lprocfs_vars lprocfs_mds_obd_vars[] [static]
Initial value:
 {
        { "uuid",       &mds_uuid_fops  },
        { NULL }
}
Definition at line 473 of file mdt_mds.c.
char* mds_attr_num_cpts [static]
Definition at line 98 of file mdt_mds.c.
Referenced by mds_start_ptlrpc_service().
unsigned long mds_attr_num_threads [static]
Definition at line 94 of file mdt_mds.c.
Referenced by mds_start_ptlrpc_service().
struct lu_device_type mds_device_type [static]
Initial value:
 {
        .ldt_tags     = LU_DEVICE_MD,
        .ldt_name     = LUSTRE_MDS_NAME,
        .ldt_ops      = &mds_device_type_ops,
        .ldt_ctx_tags = LCT_MD_THREAD
}
Definition at line 536 of file mdt_mds.c.
struct lu_device_type_operations mds_device_type_ops [static]
Initial value:
 {
        .ldto_init = mds_type_init,
        .ldto_fini = mds_type_fini,
        .ldto_start = mds_type_start,
        .ldto_stop  = mds_type_stop,
        .ldto_device_alloc = mds_device_alloc,
        .ldto_device_free  = mds_device_free,
        .ldto_device_fini  = mds_device_fini
}
Definition at line 524 of file mdt_mds.c.
char* mds_num_cpts [static]
Definition at line 81 of file mdt_mds.c.
Referenced by mds_start_ptlrpc_service().
unsigned long mds_num_threads [static]
Definition at line 77 of file mdt_mds.c.
Referenced by mds_mod_init(), and mds_start_ptlrpc_service().
struct obd_ops mds_obd_device_ops [static]
Initial value:
 {
        .o_owner           = THIS_MODULE,
        .o_health_check    = mds_health_check,
}
Definition at line 562 of file mdt_mds.c.
char* mds_rdpg_num_cpts [static]
Definition at line 89 of file mdt_mds.c.
Referenced by mds_start_ptlrpc_service().
unsigned long mds_rdpg_num_threads [static]
Definition at line 85 of file mdt_mds.c.
Referenced by mds_start_ptlrpc_service().
unsigned long mdt_num_threads [static]
Definition at line 73 of file mdt_mds.c.
Referenced by mds_mod_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.