Lustre: lustre/mdt/mdt_coordinator.c File Reference
lustre/mdt/mdt_coordinator.c File Reference
#include <linux/kthread.h>
#include <obd_support.h>
#include <lustre_net.h>
#include <lustre_export.h>
#include <obd.h>
#include <lprocfs_status.h>
#include <lustre_log.h>
#include <lustre_kernelcomm.h>
#include "mdt_internal.h"
Data Structures
struct hsm_scan_data
data passed to llog_cat_process() callback to scan requests and take actions
struct hsm_restore_data
data passed to llog_cat_process() callback to scan requests and take actions
struct hsm_cancel_all_data
data passed to llog_cat_process() callback to cancel requests
Defines
#define DEBUG_SUBSYSTEM S_MDS
#define GENERATE_PROC_METHOD(VAR)
#define CDT_ENABLE_CMD "enabled"
#define CDT_STOP_CMD "shutdown"
#define CDT_DISABLE_CMD "disabled"
#define CDT_PURGE_CMD "purge"
#define CDT_HELP_CMD "help"
#define CDT_MAX_CMD_LEN 10
Functions
struct mdt_object * mdt_hsm_get_md_hsm (struct mdt_thread_info *mti, const struct lu_fid *fid, struct md_hsm *hsm)
get obj and HSM attributes on a fid
void mdt_hsm_dump_hal (int level, const char *prefix, struct hsm_action_list *hal)
static int mdt_coordinator_cb (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *hdr, void *data)
llog_cat_process() callback, used to:
find waiting request and start action
purge canceled and done requests
int hsm_cdt_procfs_init (struct mdt_device *mdt)
create /proc entries for coordinator
void hsm_cdt_procfs_fini (struct mdt_device *mdt)
remove /proc entries for coordinator
struct lprocfs_vars * hsm_cdt_get_proc_vars (void)
get vector of hsm cdt /proc vars
static int mdt_coordinator (void *data)
coordinator thread
struct cdt_restore_handle * mdt_hsm_restore_hdl_find (struct coordinator *cdt, const struct lu_fid *fid)
lookup a restore handle by FID caller needs to hold cdt_restore_lock
static int hsm_restore_cb (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *hdr, void *data)
llog_cat_process() callback, used to:
find restore request and allocate the restore handle
static int mdt_hsm_pending_restore (struct mdt_thread_info *mti)
restore coordinator state at startup the goal is to take a layout lock for each registered restore request
static int hsm_init_ucred (struct lu_ucred *uc)
int mdt_hsm_cdt_wakeup (struct mdt_device *mdt)
wake up coordinator thread
int mdt_hsm_cdt_init (struct mdt_device *mdt)
initialize coordinator struct
int mdt_hsm_cdt_fini (struct mdt_device *mdt)
free a coordinator thread
int mdt_hsm_cdt_start (struct mdt_device *mdt)
start a coordinator thread
int mdt_hsm_cdt_stop (struct mdt_device *mdt)
stop a coordinator thread
int mdt_hsm_add_hal (struct mdt_thread_info *mti, struct hsm_action_list *hal, struct obd_uuid *uuid)
register all requests from an hal in the memory list
static int hsm_swap_layouts (struct mdt_thread_info *mti, const lustre_fid *fid, const lustre_fid *dfid, struct md_hsm *mh_common)
swap layouts between 2 fids
static int hsm_cdt_request_completed (struct mdt_thread_info *mti, struct hsm_progress_kernel *pgs, const struct cdt_agent_req *car, enum agent_req_status *status)
update status of a completed request
int mdt_hsm_update_request_state (struct mdt_thread_info *mti, struct hsm_progress_kernel *pgs, const int update_record)
update status of a request
static int mdt_cancel_all_cb (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *hdr, void *data)
llog_cat_process() callback, used to:
purge all requests
static int hsm_cancel_all_actions (struct mdt_device *mdt)
cancel all actions
bool mdt_hsm_is_action_compat (const struct hsm_action_item *hai, const int hal_an, const __u64 rq_flags, const struct md_hsm *hsm)
check if a request is compatible with file status
static __u64 hsm_policy_str2bit (const char *name)
convert a policy name to a bit
static void hsm_policy_bit2str (struct seq_file *m, const __u64 mask, const bool hexa)
convert a policy bit field to a string
static int mdt_hsm_policy_seq_show (struct seq_file *m, void *data)
static ssize_t mdt_hsm_policy_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
LPROC_SEQ_FOPS (mdt_hsm_policy)
ssize_t mdt_hsm_cdt_control_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
int mdt_hsm_cdt_control_seq_show (struct seq_file *m, void *data)
static int mdt_hsm_request_mask_show (struct seq_file *m, __u64 mask)
static int mdt_hsm_user_request_mask_seq_show (struct seq_file *m, void *data)
static int mdt_hsm_group_request_mask_seq_show (struct seq_file *m, void *data)
static int mdt_hsm_other_request_mask_seq_show (struct seq_file *m, void *data)
static enum hsm_copytool_action hsm_copytool_name2action (const char *name)
static ssize_t mdt_write_hsm_request_mask (struct file *file, const char __user *user_buf, size_t user_count, __u64 *mask)
static ssize_t mdt_hsm_user_request_mask_seq_write (struct file *file, const char __user *buf, size_t count, loff_t *off)
static ssize_t mdt_hsm_group_request_mask_seq_write (struct file *file, const char __user *buf, size_t count, loff_t *off)
static ssize_t mdt_hsm_other_request_mask_seq_write (struct file *file, const char __user *buf, size_t count, loff_t *off)
LPROC_SEQ_FOPS (mdt_hsm_cdt_loop_period)
LPROC_SEQ_FOPS (mdt_hsm_cdt_grace_delay)
LPROC_SEQ_FOPS (mdt_hsm_cdt_active_req_timeout)
LPROC_SEQ_FOPS (mdt_hsm_cdt_max_requests)
LPROC_SEQ_FOPS (mdt_hsm_cdt_default_archive_id)
LPROC_SEQ_FOPS (mdt_hsm_user_request_mask)
LPROC_SEQ_FOPS (mdt_hsm_group_request_mask)
LPROC_SEQ_FOPS (mdt_hsm_other_request_mask)
Variables
static struct lprocfs_vars lprocfs_mdt_hsm_vars []
struct {
__u64 bit
char * name
char * nickname
} hsm_policy_names []
Define Documentation
#define CDT_DISABLE_CMD "disabled"
Definition at line 1894 of file mdt_coordinator.c.
Referenced by mdt_hsm_cdt_control_seq_write().
#define CDT_ENABLE_CMD "enabled"
Definition at line 1892 of file mdt_coordinator.c.
Referenced by mdt_hsm_cdt_control_seq_write().
#define CDT_HELP_CMD "help"
Definition at line 1896 of file mdt_coordinator.c.
Referenced by mdt_hsm_cdt_control_seq_write().
#define CDT_MAX_CMD_LEN 10
Definition at line 1897 of file mdt_coordinator.c.
Referenced by mdt_hsm_cdt_control_seq_write().
#define CDT_PURGE_CMD "purge"
Definition at line 1895 of file mdt_coordinator.c.
Referenced by mdt_hsm_cdt_control_seq_write().
#define CDT_STOP_CMD "shutdown"
Definition at line 1893 of file mdt_coordinator.c.
Referenced by mdt_hsm_cdt_control_seq_write().
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 39 of file mdt_coordinator.c.
#define GENERATE_PROC_METHOD (VAR)
Value:
static int mdt_hsm_##VAR##_seq_show(struct seq_file *m, void *data)     \
{                                                                       \
        struct mdt_device       *mdt = m->private;                      \
        struct coordinator      *cdt = &mdt->mdt_coordinator;           \
        ENTRY;                                                          \
                                                                        \
        seq_printf(m, LPU64"\n", (__u64)cdt->VAR);                      \
        RETURN(0);                                                      \
}                                                                       \
static ssize_t                                                          \
mdt_hsm_##VAR##_seq_write(struct file *file, const char __user *buffer, \
                          size_t count, loff_t *off)                    \
                                                                        \
{                                                                       \
        struct seq_file         *m = file->private_data;                \
        struct mdt_device       *mdt = m->private;                      \
        struct coordinator      *cdt = &mdt->mdt_coordinator;           \
        __s64                    val;                                   \
        int                      rc;                                    \
        ENTRY;                                                          \
                                                                        \
        rc = lprocfs_str_to_s64(buffer, count, &val);                   \
        if (rc)                                                         \
                RETURN(rc);                                             \
        if (val > 0 && val < INT_MAX) {                                 \
                cdt->VAR = val;                                         \
                RETURN(count);                                          \
        }                                                               \
        RETURN(-EINVAL);                                                \
}                                                                       \
Definition at line 1850 of file mdt_coordinator.c.
Function Documentation
static int hsm_cancel_all_actions (struct mdt_device * mdt) [static]
cancel all actions
Parameters:
obd [IN] MDT device
Definition at line 1544 of file mdt_coordinator.c.
References cdt_agent_req::car_archive_id, cdt_agent_req::car_compound_id, cdt_agent_req::car_flags, cdt_agent_req::car_hai, CDT_DISABLE, coordinator::cdt_env, cdt_llog_process(), coordinator::cdt_request_lock, coordinator::cdt_requests, coordinator::cdt_state, cfs_size_round(), ENTRY, GOTO, hsm_action_item::hai_action, hai_first(), hsm_action_item::hai_len, hsm_action_list::hal_archive_id, hsm_action_list::hal_compound_id, hsm_action_list::hal_count, hsm_action_list::hal_flags, hsm_action_list::hal_fsname, HAL_VERSION, hsm_action_list::hal_version, HSMA_CANCEL, lu_env::le_ctx, list_for_each_entry, lu_context_key_get(), hsm_cancel_all_data::mdt, mdt_cancel_all_cb(), mdt_cdt_get_request(), mdt_cdt_put_request(), mdt_device::mdt_coordinator, mdt_hsm_agent_send(), mdt_obd_name(), mdt_thread_key, mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, MTI_NAME_MAXLEN, OBD_ALLOC, OBD_FREE, obd_uuid2fsname(), and RETURN.
Referenced by mdt_hsm_cdt_control_seq_write().
struct lprocfs_vars* hsm_cdt_get_proc_vars (void) [read]
get vector of hsm cdt /proc vars
Parameters:
none
Return values:
var vector
Definition at line 414 of file mdt_coordinator.c.
References lprocfs_mdt_hsm_vars.
Referenced by mdt_process_config().
void hsm_cdt_procfs_fini (struct mdt_device * mdt)
remove /proc entries for coordinator
Parameters:
mdt [IN]
Definition at line 400 of file mdt_coordinator.c.
References coordinator::cdt_proc_dir, coordinator::cdt_state, CDT_STOPPED, LASSERT, lprocfs_remove(), and mdt_device::mdt_coordinator.
Referenced by mdt_procfs_fini().
int hsm_cdt_procfs_init (struct mdt_device * mdt)
create /proc entries for coordinator
Parameters:
mdt [IN]
Return values:
0 success
-ve failure
Definition at line 375 of file mdt_coordinator.c.
References coordinator::cdt_proc_dir, CERROR, ENTRY, lprocfs_mdt_hsm_vars, lprocfs_register(), mdt2obd_dev(), mdt_device::mdt_coordinator, mdt_obd_name(), and RETURN.
Referenced by mdt_procfs_init().
static int hsm_cdt_request_completed (struct mdt_thread_info * mti, struct hsm_progress_kernel * pgs, const struct cdt_agent_req * car, enum agent_req_status * status) [static]
update status of a completed request
Parameters:
mti [IN] context
pgs [IN] progress of the copy tool
update_record [IN] update llog record
Return values:
0 success
-ve failure
Definition at line 1161 of file mdt_coordinator.c.
References ARS_FAILED, ARS_SUCCEED, ARS_WAITING, cdt_agent_req::car_hai, CDT_NORETRY_ACTION, coordinator::cdt_policy, coordinator::cdt_restore_lock, CERROR, CL_HSM, CLF_HSM_DIRTY, CLF_HSM_ERROVERFLOW, CLF_HSM_MAXERROR, cdt_restore_handle::crh_lh, cdt_restore_handle::crh_list, DFID, ENTRY, GOTO, hsm_action_item::hai_action, hsm_action_item::hai_dfid, hsm_action_item::hai_fid, HE_ARCHIVE, HE_CANCEL, HE_REMOVE, HE_RESTORE, HP_FLAG_RETRY, hsm_progress_kernel::hpk_cookie, hsm_progress_kernel::hpk_data_version, hsm_progress_kernel::hpk_errval, hsm_progress_kernel::hpk_fid, hsm_progress_kernel::hpk_flags, HS_ARCHIVED, HS_DIRTY, HS_EXISTS, HS_LOST, hsm_set_cl_error(), hsm_set_cl_event(), hsm_set_cl_flags(), hsm_swap_layouts(), HSMA_ARCHIVE, HSMA_CANCEL, HSMA_REMOVE, HSMA_RESTORE, list_del(), LPX64, mdt_device::mdt_coordinator, mdt_hsm_attr_set(), mdt_hsm_cdt_kmem, mdt_hsm_get_md_hsm(), mdt_hsm_restore_hdl_find(), mdt_obd_name(), mdt_object_child(), mdt_object_put(), mdt_object_unlock(), md_hsm::mh_arch_ver, md_hsm::mh_flags, mo_changelog(), mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, OBD_SLAB_FREE_PTR, PFID, and RETURN.
Referenced by mdt_hsm_update_request_state().
static enum hsm_copytool_action hsm_copytool_name2action (const char * name) [inline, static]
Definition at line 2039 of file mdt_coordinator.c.
References HSMA_ARCHIVE, HSMA_CANCEL, HSMA_NONE, HSMA_REMOVE, and HSMA_RESTORE.
Referenced by mdt_write_hsm_request_mask().
static int hsm_init_ucred (struct lu_ucred * uc) [static]
Definition at line 745 of file mdt_coordinator.c.
References CFS_CAP_FS_MASK, ENTRY, RETURN, lu_ucred::uc_cap, lu_ucred::uc_fsgid, lu_ucred::uc_fsuid, lu_ucred::uc_gid, lu_ucred::uc_ginfo, lu_ucred::uc_identity, lu_ucred::uc_o_fsgid, lu_ucred::uc_o_fsuid, lu_ucred::uc_o_gid, lu_ucred::uc_o_uid, lu_ucred::uc_suppgids, lu_ucred::uc_uid, lu_ucred::uc_umask, lu_ucred::uc_valid, and UCRED_OLD.
Referenced by mdt_hsm_cdt_init(), and mdt_hsm_update_request_state().
static void hsm_policy_bit2str (struct seq_file * m, const __u64 mask, const bool hexa) [static]
convert a policy bit field to a string
Parameters:
mask [IN] policy bit field
hexa [IN] print mask before bit names
buffer [OUT] string
count [IN] size of buffer
Definition at line 1725 of file mdt_coordinator.c.
References __u64, bit, CDT_POLICY_SHIFT_COUNT, ENTRY, hsm_policy_names, LPX64, and name.
Referenced by mdt_hsm_policy_seq_show(), and mdt_hsm_policy_seq_write().
static __u64 hsm_policy_str2bit (const char * name) [static]
convert a policy name to a bit
Parameters:
name [IN] policy name
Return values:
0 unknown
policy bit
Definition at line 1707 of file mdt_coordinator.c.
References hsm_policy_names, and nickname.
Referenced by mdt_hsm_policy_seq_write().
static int hsm_restore_cb (const struct lu_env * env, struct llog_handle * llh, struct llog_rec_hdr * hdr, void * data) [static]
llog_cat_process() callback, used to:
find restore request and allocate the restore handle
Parameters:
env [IN] environment
llh [IN] llog handle
hdr [IN] llog record
data [IN/OUT] cb data = struct hsm_restore_data
Return values:
0 success
-ve failure
Definition at line 654 of file mdt_coordinator.c.
References agent_req_in_final_state(), llog_agent_req_rec::arr_hai, llog_agent_req_rec::arr_req_change, llog_agent_req_rec::arr_status, ARS_STARTED, ARS_WAITING, coordinator::cdt_last_cookie, coordinator::cdt_restore_hdl, coordinator::cdt_restore_lock, cfs_time_current_sec(), cdt_restore_handle::crh_extent, cdt_restore_handle::crh_fid, cdt_restore_handle::crh_lh, cdt_restore_handle::crh_list, ldlm_extent::end, ENTRY, GOTO, hsm_action_item::hai_action, hsm_action_item::hai_cookie, hsm_action_item::hai_extent, hsm_action_item::hai_fid, hsm_restore_data::hrd_mti, HSMA_RESTORE, LCK_EX, hsm_extent::length, list_add_tail(), llog_write(), llog_rec_hdr::lrh_index, MDS_INODELOCK_LAYOUT, mdt_device::mdt_coordinator, mdt_hsm_cdt_kmem, mdt_lock_reg_init(), mdt_object_find_lock(), mdt_object_put(), mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, OBD_SLAB_ALLOC_PTR, RETURN, and ldlm_extent::start.
Referenced by mdt_hsm_pending_restore().
static int hsm_swap_layouts (struct mdt_thread_info * mti, const lustre_fid * fid, const lustre_fid * dfid, struct md_hsm * mh_common) [static]
swap layouts between 2 fids
Parameters:
mti [IN] context
fid1 [IN]
fid2 [IN]
mh_common [IN] MD HSM
Definition at line 1099 of file mdt_coordinator.c.
References CERROR, DFID, ENTRY, GOTO, HS_DIRTY, HS_RELEASED, LCK_EX, MDS_INODELOCK_LAYOUT, mdt_hsm_attr_set(), MDT_LH_OLD, mdt_lock_reg_init(), mdt_obd_name(), mdt_object_child(), mdt_object_exists(), mdt_object_find(), mdt_object_find_lock(), mdt_object_put(), mdt_object_unlock_put(), md_hsm::mh_flags, mo_swap_layouts(), mdt_thread_info::mti_env, mdt_thread_info::mti_lh, mdt_thread_info::mti_mdt, PFID, RETURN, and SWAP_LAYOUTS_MDS_HSM.
Referenced by hsm_cdt_request_completed().
LPROC_SEQ_FOPS (mdt_hsm_other_request_mask)
LPROC_SEQ_FOPS (mdt_hsm_group_request_mask)
LPROC_SEQ_FOPS (mdt_hsm_user_request_mask)
LPROC_SEQ_FOPS (mdt_hsm_cdt_default_archive_id)
LPROC_SEQ_FOPS (mdt_hsm_cdt_max_requests)
LPROC_SEQ_FOPS (mdt_hsm_cdt_active_req_timeout)
LPROC_SEQ_FOPS (mdt_hsm_cdt_grace_delay)
LPROC_SEQ_FOPS (mdt_hsm_cdt_loop_period)
LPROC_SEQ_FOPS (mdt_hsm_policy)
static int mdt_cancel_all_cb (const struct lu_env * env, struct llog_handle * llh, struct llog_rec_hdr * hdr, void * data) [static]
llog_cat_process() callback, used to:
purge all requests
Parameters:
env [IN] environment
llh [IN] llog handle
hdr [IN] llog record
data [IN] cb data = struct hsm_cancel_all_data
Return values:
0 success
-ve failure
Definition at line 1519 of file mdt_coordinator.c.
References llog_agent_req_rec::arr_req_change, llog_agent_req_rec::arr_status, ARS_CANCELED, ARS_STARTED, ARS_WAITING, cfs_time_current_sec(), ENTRY, llog_write(), llog_rec_hdr::lrh_index, and RETURN.
Referenced by hsm_cancel_all_actions().
static int mdt_coordinator (void * data) [static]
coordinator thread
Parameters:
data [IN] obd device
Return values:
0 success
-ve failure
Definition at line 425 of file mdt_coordinator.c.
References __u64, agent_req_status2name(), ARS_STARTED, ARS_WAITING, CDEBUG, coordinator::cdt_agents, CDT_DISABLE, cdt_llog_process(), coordinator::cdt_loop_period, coordinator::cdt_max_requests, coordinator::cdt_request_count, coordinator::cdt_state, CDT_STOPPING, coordinator::cdt_thread, CERROR, cfs_time_seconds(), current_pid, D_HSM, ENTRY, EXIT, hsm_scan_data::fs_name, GOTO, hsm_action_item::hai_cookie, hai_first(), hai_next(), hsm_scan_data::hal, hsm_action_list::hal_compound_id, hsm_action_list::hal_count, hsm_scan_data::hal_sz, l_wait_event, LASSERT, list_empty(), LPX64, LWI_TIMEOUT, hsm_scan_data::max_requests, mdt_agent_record_update(), mdt_device::mdt_coordinator, mdt_coordinator_cb(), mdt_hsm_agent_send(), mdt_hsm_cdt_stop(), mdt_obd_name(), mdt_device::mdt_opts, mdt_device::mo_coordinator, hsm_scan_data::mti, mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, MTI_NAME_MAXLEN, OBD_ALLOC, OBD_FREE, obd_uuid2fsname(), hsm_scan_data::request, hsm_scan_data::request_cnt, hsm_scan_data::request_sz, status, SVC_EVENT, SVC_RUNNING, SVC_STOPPED, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, and ptlrpc_thread::t_flags.
Referenced by mdt_hsm_cdt_start().
static int mdt_coordinator_cb (const struct lu_env * env, struct llog_handle * llh, struct llog_rec_hdr * hdr, void * data) [static]
llog_cat_process() callback, used to:
find waiting request and start action
purge canceled and done requests
Parameters:
env [IN] environment
llh [IN] llog handle
hdr [IN] llog record
data [IN/OUT] cb data = struct hsm_scan_data
Return values:
0 success
-ve failure
Definition at line 158 of file mdt_coordinator.c.
References llog_agent_req_rec::arr_archive_id, llog_agent_req_rec::arr_compound_id, llog_agent_req_rec::arr_flags, llog_agent_req_rec::arr_hai, llog_agent_req_rec::arr_req_change, llog_agent_req_rec::arr_req_create, llog_agent_req_rec::arr_status, ARS_CANCELED, ARS_FAILED, ARS_STARTED, ARS_SUCCEED, ARS_WAITING, cdt_agent_req::car_req_update, coordinator::cdt_grace_delay, coordinator::cdt_max_requests, coordinator::cdt_request_count, CERROR, cfs_size_round(), cfs_time_current_sec(), DFID, dump_llog_agent_req_rec(), ENTRY, hsm_scan_data::fs_name, hsm_action_item::hai_action, hsm_action_item::hai_cookie, hsm_action_item::hai_extent, hsm_action_item::hai_fid, hai_first(), hsm_action_item::hai_gid, hsm_action_item::hai_len, hai_next(), hsm_scan_data::hal, hsm_action_list::hal_archive_id, hsm_action_list::hal_compound_id, hsm_action_list::hal_count, hsm_action_list::hal_flags, hsm_action_list::hal_fsname, hal_size(), hsm_scan_data::hal_sz, hsm_scan_data::hal_used_sz, HAL_VERSION, hsm_action_list::hal_version, HP_FLAG_COMPLETED, hsm_progress_kernel::hpk_cookie, hsm_progress_kernel::hpk_data_version, hsm_progress_kernel::hpk_errval, hsm_progress_kernel::hpk_extent, hsm_progress_kernel::hpk_fid, hsm_progress_kernel::hpk_flags, hsm_copytool_action2name(), HSMA_CANCEL, LLOG_DEL_RECORD, llog_write(), LPX64, llog_rec_hdr::lrh_index, hsm_scan_data::max_requests, mdt_cdt_find_request(), mdt_cdt_put_request(), mdt_device::mdt_coordinator, mdt_hsm_update_request_state(), mdt_obd_name(), hsm_scan_data::mti, mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, MTI_NAME_MAXLEN, now(), OBD_ALLOC, OBD_FREE, PFID, hsm_scan_data::request, hsm_scan_data::request_cnt, RETURN, and strlcpy().
Referenced by mdt_coordinator().
int mdt_hsm_add_hal (struct mdt_thread_info * mti, struct hsm_action_list * hal, struct obd_uuid * uuid)
register all requests from an hal in the memory list
Parameters:
mti [IN] context
hal [IN] request
uuid [OUT] in case of CANCEL, the uuid of the agent which is running the CT
Return values:
0 success
-ve failure
Definition at line 1011 of file mdt_coordinator.c.
References agent_req_status2name(), ARS_CANCELED, cdt_agent_req::car_canceled, cdt_agent_req::car_uuid, CERROR, ENTRY, GOTO, hai_first(), hai_next(), hsm_action_list::hal_archive_id, hsm_action_list::hal_compound_id, hsm_action_list::hal_count, hsm_action_list::hal_flags, HS_EXISTS, HSMA_ARCHIVE, HSMA_CANCEL, LPX64, mdt_agent_record_update(), mdt_cdt_add_request(), mdt_cdt_alloc_request(), mdt_cdt_find_request(), mdt_cdt_free_request(), mdt_cdt_put_request(), mdt_device::mdt_coordinator, mdt_hsm_attr_set(), mdt_hsm_get_md_hsm(), mdt_obd_name(), mdt_object_put(), md_hsm::mh_arch_id, md_hsm::mh_flags, mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, and RETURN.
Referenced by mdt_hsm_agent_send().
int mdt_hsm_cdt_control_seq_show (struct seq_file * m, void * data)
Definition at line 1968 of file mdt_coordinator.c.
References CDT_DISABLE, CDT_INIT, CDT_RUNNING, coordinator::cdt_state, CDT_STOPPED, CDT_STOPPING, ENTRY, mdt_device::mdt_coordinator, mdt_dev(), obd_device::obd_lu_dev, and RETURN.
ssize_t mdt_hsm_cdt_control_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off)
Definition at line 1900 of file mdt_coordinator.c.
References CDT_DISABLE, CDT_DISABLE_CMD, CDT_ENABLE_CMD, CDT_HELP_CMD, CDT_MAX_CMD_LEN, CDT_PURGE_CMD, CDT_RUNNING, coordinator::cdt_state, CDT_STOP_CMD, CDT_STOPPED, CDT_STOPPING, CERROR, ENTRY, hsm_cancel_all_actions(), mdt_device::mdt_coordinator, mdt_dev(), mdt_hsm_cdt_start(), mdt_hsm_cdt_wakeup(), mdt_obd_name(), obd_device::obd_lu_dev, RETURN, and usage.
int mdt_hsm_cdt_fini (struct mdt_device * mdt)
free a coordinator thread
Parameters:
mdt [IN] device
Definition at line 852 of file mdt_coordinator.c.
References coordinator::cdt_env, ENTRY, lu_env::le_ses, lu_context_exit(), lu_context_fini(), lu_env_fini(), mdt_device::mdt_coordinator, and RETURN.
Referenced by mdt_fini(), and mdt_init0().
int mdt_hsm_cdt_init (struct mdt_device * mdt)
initialize coordinator struct
Parameters:
mdt [IN] device
Return values:
0 success
-ve failure
Definition at line 795 of file mdt_coordinator.c.
References coordinator::cdt_active_req_timeout, coordinator::cdt_agent_lock, coordinator::cdt_agents, coordinator::cdt_default_archive_id, CDT_DEFAULT_POLICY, coordinator::cdt_env, coordinator::cdt_grace_delay, coordinator::cdt_llog_lock, coordinator::cdt_loop_period, coordinator::cdt_max_requests, coordinator::cdt_policy, coordinator::cdt_request_lock, coordinator::cdt_requests, coordinator::cdt_restore_hdl, coordinator::cdt_restore_lock, coordinator::cdt_session, coordinator::cdt_state, CDT_STOPPED, coordinator::cdt_thread, ENTRY, hsm_init_ucred(), INIT_LIST_HEAD, LASSERT, LCT_MD_THREAD, LCT_SERVER_SESSION, lu_env::le_ctx, lu_env::le_ses, lu_context_enter(), lu_context_init(), lu_context_key_get(), lu_env_fini(), lu_env_init(), mdt_device::mdt_coordinator, mdt_thread_key, mdt_ucred(), mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, RETURN, and ptlrpc_thread::t_ctl_waitq.
Referenced by mdt_init0().
int mdt_hsm_cdt_start (struct mdt_device * mdt)
start a coordinator thread
Parameters:
mdt [IN] device
Return values:
0 success
-ve failure
Definition at line 871 of file mdt_coordinator.c.
References CDEBUG, coordinator::cdt_compound_id, CDT_DEFAULT_POLICY, coordinator::cdt_env, coordinator::cdt_group_request_mask, CDT_INIT, coordinator::cdt_last_cookie, coordinator::cdt_other_request_mask, coordinator::cdt_policy, CDT_POLICY_LAST, CDT_POLICY_SHIFT_COUNT, coordinator::cdt_request_count, CDT_RUNNING, coordinator::cdt_state, CDT_STOPPED, coordinator::cdt_thread, coordinator::cdt_user_request_mask, CERROR, cfs_time_current_sec(), CLASSERT, D_HSM, dump_requests(), ENTRY, HSMA_RESTORE, lu_env::le_ctx, lu_context_key_get(), mdt_coordinator(), mdt_device::mdt_coordinator, mdt_hsm_pending_restore(), mdt_obd_name(), mdt_device::mdt_opts, mdt_thread_key, mdt_device::mo_coordinator, RETURN, SVC_RUNNING, ptlrpc_thread::t_ctl_waitq, and ptlrpc_thread::t_flags.
Referenced by mdt_hsm_cdt_control_seq_write().
int mdt_hsm_cdt_stop (struct mdt_device * mdt)
stop a coordinator thread
Parameters:
mdt [IN] device
Definition at line 941 of file mdt_coordinator.c.
References cdt_agent_req::car_request_list, coordinator::cdt_agent_lock, coordinator::cdt_agents, coordinator::cdt_env, coordinator::cdt_request_lock, coordinator::cdt_requests, coordinator::cdt_restore_hdl, coordinator::cdt_restore_lock, coordinator::cdt_state, CDT_STOPPED, CDT_STOPPING, coordinator::cdt_thread, CERROR, cdt_restore_handle::crh_fid, cdt_restore_handle::crh_lh, cdt_restore_handle::crh_list, ENTRY, hsm_agent::ha_list, lu_env::le_ctx, list_del(), list_for_each_entry_safe, lu_context_key_get(), mdt_cdt_free_request(), mdt_device::mdt_coordinator, mdt_hsm_cdt_kmem, mdt_obd_name(), mdt_object_find(), mdt_object_unlock_put(), mdt_device::mdt_opts, mdt_thread_key, mdt_device::mo_coordinator, OBD_FREE_PTR, OBD_SLAB_FREE_PTR, RETURN, SVC_STOPPED, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, and ptlrpc_thread::t_flags.
Referenced by mdt_coordinator(), and mdt_fini().
int mdt_hsm_cdt_wakeup (struct mdt_device * mdt)
wake up coordinator thread
Parameters:
mdt [IN] device
Return values:
0 success
-ve failure
Definition at line 774 of file mdt_coordinator.c.
References coordinator::cdt_state, CDT_STOPPED, coordinator::cdt_thread, ENTRY, mdt_device::mdt_coordinator, RETURN, SVC_EVENT, ptlrpc_thread::t_ctl_waitq, and ptlrpc_thread::t_flags.
Referenced by mdt_hsm_add_actions(), mdt_hsm_cdt_control_seq_write(), and mdt_hsm_update_request_state().
void mdt_hsm_dump_hal (int level, const char * prefix, struct hsm_action_list * hal)
Definition at line 98 of file mdt_coordinator.c.
References buf, CDEBUG, DFID, hsm_action_item::hai_action, hsm_action_item::hai_cookie, hsm_action_item::hai_dfid, hai_dump_data_field(), hsm_action_item::hai_extent, hsm_action_item::hai_fid, hai_first(), hsm_action_item::hai_gid, hsm_action_item::hai_len, hai_next(), hsm_action_list::hal_archive_id, hsm_action_list::hal_compound_id, hsm_action_list::hal_count, hsm_action_list::hal_flags, hsm_action_list::hal_version, hsm_copytool_action2name(), hsm_extent::length, LPX64, hsm_extent::offset, and PFID.
struct mdt_object* mdt_hsm_get_md_hsm (struct mdt_thread_info * mti, const struct lu_fid * fid, struct md_hsm * hsm) [read]
get obj and HSM attributes on a fid
Parameters:
mti [IN] context
fid [IN] object fid
hsm [OUT] HSM meta data
Return values:
obj or error (-ENOENT if not found)
Definition at line 60 of file mdt_coordinator.c.
References ENTRY, md_attr::ma_hsm, MA_HSM, md_attr::ma_need, md_attr::ma_valid, mdt_attr_get_complex(), mdt_object_exists(), mdt_object_find(), mdt_object_put(), mdt_thread_info::mti_attr, mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, and RETURN.
Referenced by hsm_cdt_request_completed(), mdt_hsm_add_actions(), mdt_hsm_add_hal(), and mdt_hsm_agent_send().
static int mdt_hsm_group_request_mask_seq_show (struct seq_file * m, void * data) [static]
Definition at line 2021 of file mdt_coordinator.c.
References coordinator::cdt_group_request_mask, mdt_device::mdt_coordinator, and mdt_hsm_request_mask_show().
static ssize_t mdt_hsm_group_request_mask_seq_write (struct file * file, const char __user * buf, size_t count, loff_t * off) [static]
Definition at line 2114 of file mdt_coordinator.c.
References coordinator::cdt_group_request_mask, mdt_device::mdt_coordinator, and mdt_write_hsm_request_mask().
bool mdt_hsm_is_action_compat (const struct hsm_action_item * hai, const int hal_an, const __u64 rq_flags, const struct md_hsm * hsm)
check if a request is compatible with file status
Parameters:
hai [IN] request description
hal_an [IN] request archive number (not used)
rq_flags [IN] request flags
hsm [IN] file HSM metadata
Return values:
boolean
Definition at line 1648 of file mdt_coordinator.c.
References CDEBUG, D_HSM, DFID, ENTRY, hsm_action_item::hai_action, hsm_action_item::hai_extent, hsm_action_item::hai_fid, HS_ARCHIVED, HS_DIRTY, HS_EXISTS, HS_LOST, HS_NOARCHIVE, HS_RELEASED, hsm_copytool_action2name(), HSMA_ARCHIVE, HSMA_CANCEL, HSMA_REMOVE, HSMA_RESTORE, hsm_extent::length, LPX64, md_hsm::mh_flags, hsm_extent::offset, PFID, and RETURN.
Referenced by mdt_hsm_add_actions(), and mdt_hsm_agent_send().
static int mdt_hsm_other_request_mask_seq_show (struct seq_file * m, void * data) [static]
Definition at line 2030 of file mdt_coordinator.c.
References coordinator::cdt_other_request_mask, mdt_device::mdt_coordinator, and mdt_hsm_request_mask_show().
static ssize_t mdt_hsm_other_request_mask_seq_write (struct file * file, const char __user * buf, size_t count, loff_t * off) [static]
Definition at line 2126 of file mdt_coordinator.c.
References coordinator::cdt_other_request_mask, mdt_device::mdt_coordinator, and mdt_write_hsm_request_mask().
static int mdt_hsm_pending_restore (struct mdt_thread_info * mti) [static]
restore coordinator state at startup the goal is to take a layout lock for each registered restore request
Parameters:
mti [IN] context
Definition at line 731 of file mdt_coordinator.c.
References cdt_llog_process(), ENTRY, hsm_restore_data::hrd_mti, hsm_restore_cb(), mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, and RETURN.
Referenced by mdt_hsm_cdt_start().
static int mdt_hsm_policy_seq_show (struct seq_file * m, void * data) [static]
Definition at line 1753 of file mdt_coordinator.c.
References coordinator::cdt_policy, ENTRY, hsm_policy_bit2str(), mdt_device::mdt_coordinator, and RETURN.
static ssize_t mdt_hsm_policy_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Definition at line 1764 of file mdt_coordinator.c.
References __u64, buf, CDEBUG, coordinator::cdt_policy, CWARN, D_HSM, ENTRY, GOTO, hsm_policy_bit2str(), hsm_policy_str2bit(), LPX64, mdt_device::mdt_coordinator, mdt_obd_name(), OBD_ALLOC, OBD_FREE, RETURN, and start.
static int mdt_hsm_request_mask_show (struct seq_file * m, __u64 mask) [static]
Definition at line 1993 of file mdt_coordinator.c.
References ENTRY, hsm_copytool_action2name(), and RETURN.
Referenced by mdt_hsm_group_request_mask_seq_show(), mdt_hsm_other_request_mask_seq_show(), and mdt_hsm_user_request_mask_seq_show().
struct cdt_restore_handle* mdt_hsm_restore_hdl_find (struct coordinator * cdt, const struct lu_fid * fid) [read]
lookup a restore handle by FID caller needs to hold cdt_restore_lock
Parameters:
cdt [IN] coordinator
fid [IN] FID
Return values:
cdt_restore_handle found
NULL not found
Definition at line 623 of file mdt_coordinator.c.
References coordinator::cdt_restore_hdl, cdt_restore_handle::crh_fid, cdt_restore_handle::crh_list, ENTRY, list_for_each_entry, lu_fid_eq(), and RETURN.
Referenced by hsm_cdt_request_completed(), and mdt_hsm_agent_send().
int mdt_hsm_update_request_state (struct mdt_thread_info * mti, struct hsm_progress_kernel * pgs, const int update_record)
update status of a request
Parameters:
mti [IN] context
pgs [IN] progress of the copy tool
update_record [IN] update llog record
Return values:
0 success
-ve failure
Definition at line 1382 of file mdt_coordinator.c.
References agent_req_status2name(), cdt_agent_req::car_canceled, cdt_agent_req::car_hai, CDEBUG, coordinator::cdt_state, CDT_STOPPED, CERROR, D_HSM, DFID, ENTRY, GOTO, hsm_action_item::hai_action, hsm_action_item::hai_dfid, hsm_action_item::hai_fid, HP_FLAG_COMPLETED, hsm_progress_kernel::hpk_cookie, hsm_progress_kernel::hpk_errval, hsm_progress_kernel::hpk_fid, hsm_progress_kernel::hpk_flags, hsm_cdt_request_completed(), hsm_copytool_action2name(), hsm_init_ucred(), HSMA_ARCHIVE, HSMA_RESTORE, LPX64, lu_fid_eq(), mdt_agent_record_update(), mdt_cdt_put_request(), mdt_cdt_remove_request(), mdt_cdt_update_request(), mdt_device::mdt_coordinator, mdt_hsm_cdt_wakeup(), mdt_obd_name(), mdt_ucred(), mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, PFID, RETURN, and status.
Referenced by mdt_coordinator_cb(), and mdt_hsm_coordinator_update().
static int mdt_hsm_user_request_mask_seq_show (struct seq_file * m, void * data) [static]
Definition at line 2012 of file mdt_coordinator.c.
References coordinator::cdt_user_request_mask, mdt_device::mdt_coordinator, and mdt_hsm_request_mask_show().
static ssize_t mdt_hsm_user_request_mask_seq_write (struct file * file, const char __user * buf, size_t count, loff_t * off) [static]
Definition at line 2102 of file mdt_coordinator.c.
References coordinator::cdt_user_request_mask, mdt_device::mdt_coordinator, and mdt_write_hsm_request_mask().
static ssize_t mdt_write_hsm_request_mask (struct file * file, const char __user * user_buf, size_t user_count, __u64 * mask) [static]
Definition at line 2056 of file mdt_coordinator.c.
References __u64, buf, ENTRY, GOTO, hsm_copytool_name2action(), name, OBD_ALLOC, OBD_FREE, and RETURN.
Referenced by mdt_hsm_group_request_mask_seq_write(), mdt_hsm_other_request_mask_seq_write(), and mdt_hsm_user_request_mask_seq_write().
Variable Documentation
__u64 bit
Definition at line 1692 of file mdt_coordinator.c.
Referenced by hsm_policy_bit2str(), libcfs_debug_mask2str(), and libcfs_debug_str2mask().
struct { ... } hsm_policy_names[] [static]
Referenced by hsm_policy_bit2str(), and hsm_policy_str2bit().
static struct lprocfs_vars lprocfs_mdt_hsm_vars [static, read]
Initial value:
 {
        { .name =       "agents",
          .fops =       &mdt_hsm_agent_fops                     },
        { .name =       "actions",
          .fops =       &mdt_hsm_actions_fops,
          .proc_mode =  0444                                    },
        { .name =       "default_archive_id",
          .fops =       &mdt_hsm_cdt_default_archive_id_fops    },
        { .name =       "grace_delay",
          .fops =       &mdt_hsm_cdt_grace_delay_fops           },
        { .name =       "loop_period",
          .fops =       &mdt_hsm_cdt_loop_period_fops           },
        { .name =       "max_requests",
          .fops =       &mdt_hsm_cdt_max_requests_fops          },
        { .name =       "policy",
          .fops =       &mdt_hsm_policy_fops                    },
        { .name =       "active_request_timeout",
          .fops =       &mdt_hsm_cdt_active_req_timeout_fops    },
        { .name =       "active_requests",
          .fops =       &mdt_hsm_active_requests_fops           },
        { .name =       "user_request_mask",
          .fops =       &mdt_hsm_user_request_mask_fops,        },
        { .name =       "group_request_mask",
          .fops =       &mdt_hsm_group_request_mask_fops,       },
        { .name =       "other_request_mask",
          .fops =       &mdt_hsm_other_request_mask_fops,       },
        { 0 }
}
Definition at line 51 of file mdt_coordinator.c.
Referenced by hsm_cdt_get_proc_vars(), and hsm_cdt_procfs_init().
char* name
Definition at line 1693 of file mdt_coordinator.c.
Referenced by __mdd_lookup(), check_ldlm_res_id(), class_attach(), class_process_proc_param(), client_obd_setup(), construct_service_name(), ct_copy_xattr(), find_obj_iter(), fld_client_add_target(), gssd_acquire_cred(), hsm_policy_bit2str(), import_to_gss_svc(), is_first_dirent(), jt_lfsck_query(), jt_lst_add_batch(), jt_lst_add_group(), jt_lst_new_session(), jt_lst_show_session(), jt_obd_md_common(), kgnilnd_dgram_mover(), kgnilnd_dgram_waitq(), kiblnd_start_schedulers(), ksocknal_base_startup(), ksocknal_connd_check_start(), ksocknal_start_schedulers(), lfsck_create_lpf(), lfsck_layout_recreate_parent(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_load_sub_trace_files(), lfsck_namespace_replace_cond(), lfsck_namespace_verify_stripe_slave(), lfsck_verify_lpf(), ll_init_security(), ll_intent_file_open(), ll_link(), ll_mkdir(), ll_mknod(), ll_new_node(), ll_rmdir(), ll_statahead_thread(), ll_symlink(), ll_unlink(), llog_ioctl(), llog_origin_handle_open(), llog_osd_regular_fid_add_name_entry(), llog_osd_regular_fid_del_name_entry(), llog_run_tests(), llog_test_10(), llog_test_4(), llog_test_5(), llog_test_8(), lnet_nid2hostname(), load_backfs_module(), lod_load_lmv_shards(), lookup_fn(), lprocfs_add_nodemap_idmap_seq_write(), lprocfs_add_nodemap_range_seq_write(), lprocfs_del_nodemap_idmap_seq_write(), lprocfs_del_nodemap_range_seq_write(), lquota_disk_for_each_slv(), lquota_disk_slv_filename(), lst_batch_add_ioctl(), lst_batch_info_ioctl(), lst_batch_query_ioctl(), lst_batch_run_ioctl(), lst_batch_stop_ioctl(), lst_debug_ioctl(), lst_group_add_ioctl(), lst_group_del_ioctl(), lst_group_info_ioctl(), lst_group_update_ioctl(), lst_list_batch_all(), lst_list_group_all(), lst_nodes_add_ioctl(), lst_session_new_ioctl(), lst_stat_query_ioctl(), lu_site_init(), lustre_assert_wire_constants(), lvar_key_cmp(), lvar_key_eq(), lvar_lookup(), lvar_node_load(), lwp_notify_users(), main(), mdc_get_root(), mdc_getattr_name(), mdd_create(), mdd_link(), mdd_migrate_entries(), mdd_migrate_update_name(), mdd_orphan_cleanup(), mdd_unlink(), mdt_lookup_fileset(), mdt_stack_init(), mdt_write_hsm_request_mask(), mgs_ir_notify(), obf_lookup(), ofd_fid_init(), osd_add_to_remote_parent(), osd_delete_from_remote_parent(), osd_dir_delete(), osd_dir_insert(), osd_dir_it_get(), osd_dir_lookup(), osd_ea_lookup_rec(), osd_get_name_n_idx(), osd_index_ea_insert(), osd_it_iam_rec(), osd_lookup_in_remote_parent(), osd_obj_map_delete(), osd_obj_map_insert(), osd_obj_map_lookup(), osd_obj_map_recover(), osd_obj_map_update(), osd_obj_spec_insert(), osd_obj_spec_lookup(), osd_obj_spec_update(), osd_oi_open_table(), osd_oi_probe(), osd_oi_table_open(), osd_remove_ois(), osd_sa_xattr_list(), out_index_delete(), out_index_insert(), out_index_lookup(), out_xattr_del(), out_xattr_get(), out_xattr_set(), parse_opts(), parse_perm(), process_args(), qsd_start_reint_thread(), read_mapping_db(), seq_store_init(), sptlrpc_conf_choose_flavor(), test19(), update_recovery_index_delete(), update_recovery_index_insert(), update_recovery_xattr_del(), and update_recovery_xattr_set().
char* nickname
Definition at line 1694 of file mdt_coordinator.c.
Referenced by hsm_policy_str2bit().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.