Lustre: lustre/mdt/mdt_hsm_cdt_client.c File Reference
lustre/mdt/mdt_hsm_cdt_client.c File Reference
#include <obd_support.h>
#include <lustre_net.h>
#include <lustre_export.h>
#include <obd.h>
#include <lprocfs_status.h>
#include <lustre_log.h>
#include "mdt_internal.h"
Data Structures
struct hsm_compat_data_cb
data passed to llog_cat_process() callback to find compatible requests
Defines
#define DEBUG_SUBSYSTEM S_MDS
Functions
static int hsm_find_compatible_cb (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *hdr, void *data)
llog_cat_process() callback, used to find record compatibles with a new hsm_action_list
static int hsm_find_compatible (const struct lu_env *env, struct mdt_device *mdt, struct hsm_action_list *hal)
find compatible requests already recorded
static bool hsm_action_is_needed (struct hsm_action_item *hai, int hal_an, __u64 rq_flags, struct md_hsm *hsm)
check if an action is really needed
static bool hal_is_sane (struct hsm_action_list *hal)
test sanity of an hal FID must be valid action must be known
static int hsm_action_permission (struct mdt_thread_info *mti, struct mdt_object *obj, enum hsm_copytool_action hsma)
int mdt_hsm_add_actions (struct mdt_thread_info *mti, struct hsm_action_list *hal, __u64 *compound_id)
register a list of requests
int mdt_hsm_get_running (struct mdt_thread_info *mti, struct hsm_action_list *hal)
get running action on a FID list or from cookie
bool mdt_hsm_restore_is_running (struct mdt_thread_info *mti, const struct lu_fid *fid)
check if a restore is running on a FID this is redundant with mdt_hsm_coordinator_get_running() but as it can be called frequently when getting attr we make an optimized/simpler version only for a FID
int mdt_hsm_get_actions (struct mdt_thread_info *mti, struct hsm_action_list *hal)
get registered action on a FID list
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 37 of file mdt_hsm_cdt_client.c.
Function Documentation
static bool hal_is_sane (struct hsm_action_list * hal) [static]
test sanity of an hal FID must be valid action must be known
Parameters:
hal [IN]
Return values:
boolean
Definition at line 221 of file mdt_hsm_cdt_client.c.
References ENTRY, fid_is_sane(), hai_first(), hai_next(), hsm_action_list::hal_count, HSMA_ARCHIVE, HSMA_CANCEL, HSMA_NONE, HSMA_REMOVE, HSMA_RESTORE, and RETURN.
Referenced by mdt_hsm_add_actions().
static bool hsm_action_is_needed (struct hsm_action_item * hai, int hal_an, __u64 rq_flags, struct md_hsm * hsm) [static]
check if an action is really needed
Parameters:
hai [IN] request description
hal_an [IN] request archive number (not used)
rq_flags [IN] request flags
hsm [IN] file HSM metadata
Return values:
boolean
Definition at line 171 of file mdt_hsm_cdt_client.c.
References CDEBUG, D_HSM, DFID, ENTRY, hsm_action_item::hai_action, hsm_action_item::hai_extent, hsm_action_item::hai_fid, HS_ARCHIVED, HS_DIRTY, HS_EXISTS, HS_RELEASED, hsm_copytool_action2name(), HSM_FORCE_ACTION, HSMA_ARCHIVE, HSMA_CANCEL, HSMA_REMOVE, HSMA_RESTORE, hsm_extent::length, LPX64, md_hsm::mh_flags, hsm_extent::offset, PFID, and RETURN.
Referenced by mdt_hsm_add_actions().
static int hsm_action_permission (struct mdt_thread_info * mti, struct mdt_object * obj, enum hsm_copytool_action hsma) [static]
Definition at line 249 of file mdt_hsm_cdt_client.c.
References __u64, coordinator::cdt_group_request_mask, coordinator::cdt_other_request_mask, coordinator::cdt_user_request_mask, CFS_CAP_SYS_ADMIN, ENTRY, exp_connect_flags(), HSMA_RESTORE, lu_attr::la_gid, lu_attr::la_uid, lustre_in_group_p(), md_attr::ma_attr, MA_INODE, md_attr::ma_need, md_capable(), mdt_attr_get_complex(), mdt_device::mdt_coordinator, mdt_ucred(), mdt_thread_info::mti_attr, mdt_thread_info::mti_exp, mdt_thread_info::mti_mdt, OBD_CONNECT_RDONLY, RETURN, and lu_ucred::uc_fsuid.
Referenced by mdt_hsm_add_actions().
static int hsm_find_compatible (const struct lu_env * env, struct mdt_device * mdt, struct hsm_action_list * hal) [static]
find compatible requests already recorded
Parameters:
env [IN] environment
mdt [IN] MDT device
hal [IN/OUT] new request cookie set to compatible found or to 0 if not found for cancel request, see callback hsm_find_compatible_cb()
Return values:
0 success
-ve failure
Definition at line 130 of file mdt_hsm_cdt_client.c.
References hsm_compat_data_cb::cdt, cdt_llog_process(), ENTRY, hai_first(), hai_next(), hsm_compat_data_cb::hal, hsm_action_list::hal_count, hsm_find_compatible_cb(), HSMA_CANCEL, mdt_device::mdt_coordinator, and RETURN.
Referenced by mdt_hsm_add_actions(), and mdt_hsm_get_actions().
static int hsm_find_compatible_cb (const struct lu_env * env, struct llog_handle * llh, struct llog_rec_hdr * hdr, void * data) [static]
llog_cat_process() callback, used to find record compatibles with a new hsm_action_list
Parameters:
env [IN] environment
llh [IN] llog handle
hdr [IN] llog record
data [IN] cb data = hsm_compat_data_cb
Return values:
0 success
-ve failure
Definition at line 66 of file mdt_hsm_cdt_client.c.
References llog_agent_req_rec::arr_archive_id, llog_agent_req_rec::arr_flags, llog_agent_req_rec::arr_hai, llog_agent_req_rec::arr_status, ARS_STARTED, ARS_WAITING, ENTRY, hsm_action_item::hai_action, hsm_action_item::hai_cookie, hsm_action_item::hai_fid, hai_first(), hai_next(), hsm_compat_data_cb::hal, hsm_action_list::hal_archive_id, hsm_action_list::hal_count, hsm_action_list::hal_flags, HSMA_CANCEL, HSMA_NONE, lu_fid_eq(), and RETURN.
Referenced by hsm_find_compatible().
int mdt_hsm_add_actions (struct mdt_thread_info * mti, struct hsm_action_list * hal, __u64 * compound_id)
register a list of requests
Parameters:
mti [IN]
hal [IN] list of requests
compound_id [OUT] id of the compound request
Return values:
0 success
-ve failure in case of restore, caller must hold layout lock
Definition at line 298 of file mdt_hsm_cdt_client.c.
References __u64, coordinator::cdt_compound_id, coordinator::cdt_default_archive_id, CDT_NONBLOCKING_RESTORE, coordinator::cdt_policy, coordinator::cdt_restore_hdl, coordinator::cdt_restore_lock, coordinator::cdt_state, CDT_STOPPED, CERROR, CFS_CAP_SYS_ADMIN, cdt_restore_handle::crh_extent, cdt_restore_handle::crh_fid, cdt_restore_handle::crh_lh, cdt_restore_handle::crh_list, DFID, ldlm_extent::end, ENTRY, GOTO, hai_first(), hai_next(), hsm_action_list::hal_archive_id, hsm_action_list::hal_count, hsm_action_list::hal_flags, hal_is_sane(), hsm_action_is_needed(), hsm_action_permission(), hsm_find_compatible(), HSMA_CANCEL, HSMA_REMOVE, HSMA_RESTORE, LCK_EX, list_add_tail(), md_capable(), MDS_INODELOCK_LAYOUT, mdt_agent_record_add(), mdt_device::mdt_coordinator, mdt_hsm_cdt_kmem, mdt_hsm_cdt_wakeup(), mdt_hsm_get_md_hsm(), mdt_hsm_is_action_compat(), mdt_lock_reg_init(), mdt_obd_name(), mdt_object_find_lock(), mdt_object_put(), mdt_ucred(), md_hsm::mh_arch_id, mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, OBD_SLAB_ALLOC_PTR, OBD_SLAB_FREE_PTR, PFID, RETURN, and ldlm_extent::start.
Referenced by mdt_hsm_request().
int mdt_hsm_get_actions (struct mdt_thread_info * mti, struct hsm_action_list * hal)
get registered action on a FID list
Parameters:
mti [IN]
hal [IN/OUT] requests
Return values:
0 success
-ve failure
Definition at line 549 of file mdt_hsm_cdt_client.c.
References __u64, ENTRY, fid_is_sane(), hai_first(), hai_next(), hsm_action_list::hal_count, hsm_find_compatible(), HSMA_NONE, mdt_cdt_find_request(), mdt_cdt_get_work_done(), mdt_cdt_put_request(), mdt_device::mdt_coordinator, mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, and RETURN.
Referenced by mdt_hsm_action().
int mdt_hsm_get_running (struct mdt_thread_info * mti, struct hsm_action_list * hal)
get running action on a FID list or from cookie
Parameters:
mti [IN]
hal [IN/OUT] requests
Return values:
0 success
-ve failure
Definition at line 482 of file mdt_hsm_cdt_client.c.
References cdt_agent_req::car_hai, ENTRY, fid_is_sane(), hai_first(), hai_next(), hsm_action_list::hal_count, HSMA_NONE, mdt_cdt_find_request(), mdt_cdt_put_request(), mdt_device::mdt_coordinator, mdt_thread_info::mti_mdt, and RETURN.
bool mdt_hsm_restore_is_running (struct mdt_thread_info * mti, const struct lu_fid * fid)
check if a restore is running on a FID this is redundant with mdt_hsm_coordinator_get_running() but as it can be called frequently when getting attr we make an optimized/simpler version only for a FID
Parameters:
mti [IN]
fid [IN] file FID
Return values:
boolean
Definition at line 519 of file mdt_hsm_cdt_client.c.
References coordinator::cdt_restore_hdl, coordinator::cdt_restore_lock, cdt_restore_handle::crh_fid, cdt_restore_handle::crh_list, ENTRY, fid_is_sane(), list_for_each_entry, lu_fid_eq(), mdt_device::mdt_coordinator, mdt_thread_info::mti_mdt, and RETURN.
Referenced by mdt_getattr_internal().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.