Lustre: lustre/mdt/mdt_internal.h File Reference
lustre/mdt/mdt_internal.h File Reference
#include <upcall_cache.h>
#include <lustre_net.h>
#include <lustre/lustre_idl.h>
#include <obd_class.h>
#include <lustre_disk.h>
#include <lu_target.h>
#include <md_object.h>
#include <lustre_fid.h>
#include <lustre_fld.h>
#include <lustre_req_layout.h>
#include <lustre_sec.h>
#include <lustre_idmap.h>
#include <lustre_eacl.h>
#include <lustre_quota.h>
#include <lustre_linkea.h>
Data Structures
struct mdt_file_data
struct coordinator
struct mdt_device
struct mdt_object
struct mdt_lock_handle
struct mdt_reint_record
struct mdt_thread_info
struct cdt_req_progress
struct cdt_agent_req
struct hsm_agent
struct cdt_restore_handle
Defines
#define CDT_NONBLOCKING_RESTORE (1ULL << 0)
#define CDT_NORETRY_ACTION (1ULL << 1)
#define CDT_POLICY_LAST CDT_NORETRY_ACTION
#define CDT_POLICY_SHIFT_COUNT 2
#define CDT_POLICY_ALL
#define CDT_DEFAULT_POLICY CDT_NORETRY_ACTION
#define MDT_FL_CFGLOG 0
#define MDT_FL_SYNCED 1
#define MDT_SERVICE_WATCHDOG_FACTOR (2)
#define MDT_COS_DEFAULT (0)
#define MDT_EREMOTE_OPEN (EREMOTE + 1024)
#define MDT_IDENTITY_UPCALL_PATH "/usr/sbin/l_getidentity"
Typedefs
typedef void(* mdt_reconstruct_t)(struct mdt_thread_info *mti, struct mdt_lock_handle *lhc)
Enumerations
enum cdt_states {
CDT_STOPPED = 0, CDT_INIT, CDT_RUNNING, CDT_DISABLE,
CDT_STOPPING
}
enum mdt_object_flags { MOF_LOV_CREATED = 1 << 0 }
enum {
MDT_LH_PARENT, MDT_LH_CHILD, MDT_LH_OLD, MDT_LH_LAYOUT = MDT_LH_OLD,
MDT_LH_NEW, MDT_LH_RMT, MDT_LH_LOCAL, MDT_LH_NR
}
enum { MDT_LOCAL_LOCK, MDT_CROSS_LOCK }
enum mdt_reint_flag { MRF_OPEN_TRUNC = 1 << 0 }
enum mdt_name_flags { MNF_FIX_ANON = 1 }
enum {
LPROC_MDT_OPEN = 0, LPROC_MDT_CLOSE, LPROC_MDT_MKNOD, LPROC_MDT_LINK,
LPROC_MDT_UNLINK, LPROC_MDT_MKDIR, LPROC_MDT_RMDIR, LPROC_MDT_RENAME,
LPROC_MDT_GETATTR, LPROC_MDT_SETATTR, LPROC_MDT_GETXATTR, LPROC_MDT_SETXATTR,
LPROC_MDT_STATFS, LPROC_MDT_SYNC, LPROC_MDT_SAMEDIR_RENAME, LPROC_MDT_CROSSDIR_RENAME,
LPROC_MDT_LAST
}
Functions
static struct mdt_thread_info * mdt_th_info (const struct lu_env *env)
static struct
md_device_operations * mdt_child_ops (struct mdt_device *m)
restore handle slab cache
static struct md_object * mdt_object_child (struct mdt_object *o)
static struct ptlrpc_request * mdt_info_req (struct mdt_thread_info *info)
static __u64 mdt_conn_flags (struct mdt_thread_info *info)
static void mdt_object_get (const struct lu_env *env, struct mdt_object *o)
static void mdt_object_put (const struct lu_env *env, struct mdt_object *o)
static int mdt_object_exists (const struct mdt_object *o)
static int mdt_object_remote (const struct mdt_object *o)
static struct lu_fid * mdt_object_fid (const struct mdt_object *o)
static struct lu_site * mdt_lu_site (const struct mdt_device *mdt)
static struct seq_server_site * mdt_seq_site (struct mdt_device *mdt)
static void mdt_export_evict (struct obd_export *exp)
static bool mdt_is_dne_client (struct obd_export *exp)
static bool mdt_is_striped_client (struct obd_export *exp)
__u64 mdt_get_disposition (struct ldlm_reply *rep, __u64 op_flag)
void mdt_set_disposition (struct mdt_thread_info *info, struct ldlm_reply *rep, __u64 op_flag)
void mdt_clear_disposition (struct mdt_thread_info *info, struct ldlm_reply *rep, __u64 op_flag)
void mdt_lock_pdo_init (struct mdt_lock_handle *lh, enum ldlm_mode lock_mode, const struct lu_name *lname)
void mdt_lock_reg_init (struct mdt_lock_handle *lh, enum ldlm_mode lm)
int mdt_lock_setup (struct mdt_thread_info *info, struct mdt_object *mo, struct mdt_lock_handle *lh)
int mdt_check_resent_lock (struct mdt_thread_info *info, struct mdt_object *mo, struct mdt_lock_handle *lhc)
int mdt_object_lock (struct mdt_thread_info *info, struct mdt_object *mo, struct mdt_lock_handle *lh, __u64 ibits)
int mdt_reint_object_lock (struct mdt_thread_info *info, struct mdt_object *o, struct mdt_lock_handle *lh, __u64 ibits, bool cos_incompat)
int mdt_object_lock_try (struct mdt_thread_info *info, struct mdt_object *mo, struct mdt_lock_handle *lh, __u64 ibits)
int mdt_reint_object_lock_try (struct mdt_thread_info *info, struct mdt_object *o, struct mdt_lock_handle *lh, __u64 ibits, bool cos_incompat)
void mdt_object_unlock (struct mdt_thread_info *info, struct mdt_object *mo, struct mdt_lock_handle *lh, int decref)
Unlock mdt object.
struct mdt_object * mdt_object_new (const struct lu_env *env, struct mdt_device *, const struct lu_fid *)
struct mdt_object * mdt_object_find (const struct lu_env *, struct mdt_device *, const struct lu_fid *)
struct mdt_object * mdt_object_find_lock (struct mdt_thread_info *, const struct lu_fid *, struct mdt_lock_handle *, __u64)
void mdt_object_unlock_put (struct mdt_thread_info *, struct mdt_object *, struct mdt_lock_handle *, int decref)
void mdt_client_compatibility (struct mdt_thread_info *info)
int mdt_remote_object_lock (struct mdt_thread_info *mti, struct mdt_object *o, const struct lu_fid *fid, struct lustre_handle *lh, enum ldlm_mode mode, __u64 ibits, bool nonblock)
int mdt_name_unpack (struct req_capsule *pill, const struct req_msg_field *field, struct lu_name *ln, enum mdt_name_flags flags)
int mdt_close_unpack (struct mdt_thread_info *info)
int mdt_reint_unpack (struct mdt_thread_info *info, __u32 op)
int mdt_reint_rec (struct mdt_thread_info *, struct mdt_lock_handle *)
void mdt_pack_attr2body (struct mdt_thread_info *info, struct mdt_body *b, const struct lu_attr *attr, const struct lu_fid *fid)
int mdt_getxattr (struct mdt_thread_info *info)
int mdt_reint_setxattr (struct mdt_thread_info *info, struct mdt_lock_handle *lh)
void mdt_lock_handle_init (struct mdt_lock_handle *lh)
void mdt_lock_handle_fini (struct mdt_lock_handle *lh)
void mdt_reconstruct (struct mdt_thread_info *, struct mdt_lock_handle *)
void mdt_reconstruct_generic (struct mdt_thread_info *mti, struct mdt_lock_handle *lhc)
void target_recovery_fini (struct obd_device *obd)
void target_recovery_init (struct lu_target *lut, svc_handler_t handler)
int mdt_fs_setup (const struct lu_env *, struct mdt_device *, struct obd_device *, struct lustre_sb_info *lsi)
void mdt_fs_cleanup (const struct lu_env *, struct mdt_device *)
int mdt_export_stats_init (struct obd_device *obd, struct obd_export *exp, void *client_nid)
Initialize MDT per-export statistics.
int mdt_lock_new_child (struct mdt_thread_info *info, struct mdt_object *o, struct mdt_lock_handle *child_lockh)
void mdt_mfd_set_mode (struct mdt_file_data *mfd, __u64 mode)
int mdt_reint_open (struct mdt_thread_info *info, struct mdt_lock_handle *lhc)
struct mdt_file_data * mdt_handle2mfd (struct mdt_export_data *med, const struct lustre_handle *handle, bool is_replay)
int mdt_get_info (struct tgt_session_info *tsi)
int mdt_attr_get_complex (struct mdt_thread_info *info, struct mdt_object *o, struct md_attr *ma)
int mdt_big_xattr_get (struct mdt_thread_info *info, struct mdt_object *o, const char *name)
int mdt_stripe_get (struct mdt_thread_info *info, struct mdt_object *o, struct md_attr *ma, const char *name)
int mdt_write_get (struct mdt_object *o)
void mdt_write_put (struct mdt_object *o)
int mdt_write_read (struct mdt_object *o)
struct mdt_file_data * mdt_mfd_new (const struct mdt_export_data *med)
int mdt_mfd_close (struct mdt_thread_info *info, struct mdt_file_data *mfd)
void mdt_mfd_free (struct mdt_file_data *mfd)
int mdt_close (struct tgt_session_info *tsi)
int mdt_add_dirty_flag (struct mdt_thread_info *info, struct mdt_object *mo, struct md_attr *ma)
Check HSM flags and add HS_DIRTY flag if relevant.
int mdt_fix_reply (struct mdt_thread_info *info)
int mdt_handle_last_unlink (struct mdt_thread_info *, struct mdt_object *, const struct md_attr *)
void mdt_reconstruct_open (struct mdt_thread_info *, struct mdt_lock_handle *)
struct lu_buf * mdt_buf (const struct lu_env *env, void *area, ssize_t len)
struct lu_buf * mdt_buf_const (const struct lu_env *env, const void *area, ssize_t len)
void mdt_dump_lmm (int level, const struct lov_mds_md *lmm, __u64 valid)
void mdt_dump_lmv (unsigned int level, const union lmv_mds_md *lmv)
bool allow_client_chgrp (struct mdt_thread_info *info, struct lu_ucred *uc)
Check whether allow the client to set supplementary group IDs or not.
int mdt_check_ucred (struct mdt_thread_info *)
int mdt_init_ucred (struct mdt_thread_info *, struct mdt_body *)
int mdt_init_ucred_intent_getattr (struct mdt_thread_info *, struct mdt_body *)
int mdt_init_ucred_reint (struct mdt_thread_info *)
void mdt_exit_ucred (struct mdt_thread_info *)
int mdt_version_get_check (struct mdt_thread_info *, struct mdt_object *, int)
Get version from disk and check it, no save in reply.
void mdt_version_get_save (struct mdt_thread_info *, struct mdt_object *, int)
Get version from disk and save in reply buffer.
int mdt_version_get_check_save (struct mdt_thread_info *, struct mdt_object *, int)
Get version from disk and check if recovery or just save.
void mdt_thread_info_init (struct ptlrpc_request *req, struct mdt_thread_info *mti)
void mdt_thread_info_fini (struct mdt_thread_info *mti)
struct mdt_thread_info * tsi2mdt_info (struct tgt_session_info *tsi)
int mdt_hsm_attr_set (struct mdt_thread_info *info, struct mdt_object *obj, const struct md_hsm *mh)
Update on-disk HSM attributes.
int mdt_remote_blocking_ast (struct ldlm_lock *lock, struct ldlm_lock_desc *desc, void *data, int flag)
int mdt_links_read (struct mdt_thread_info *info, struct mdt_object *mdt_obj, struct linkea_data *ldata)
int mdt_close_internal (struct mdt_thread_info *info, struct ptlrpc_request *req, struct mdt_body *repbody)
int mdt_init_idmap (struct tgt_session_info *tsi)
void mdt_cleanup_idmap (struct mdt_export_data *)
int mdt_handle_idmap (struct tgt_session_info *tsi)
int ptlrpc_user_desc_do_idmap (struct ptlrpc_request *, struct ptlrpc_user_desc *)
void mdt_body_reverse_idmap (struct mdt_thread_info *, struct mdt_body *)
int mdt_remote_perm_reverse_idmap (struct ptlrpc_request *, struct mdt_remote_perm *)
int mdt_fix_attr_ucred (struct mdt_thread_info *, __u32)
static struct mdt_device * mdt_dev (struct lu_device *d)
static struct mdt_object * mdt_obj (struct lu_object *o)
static struct dt_object * mdt_obj2dt (struct mdt_object *mo)
struct md_identity * mdt_identity_get (struct upcall_cache *, __u32)
void mdt_identity_put (struct upcall_cache *, struct md_identity *)
void mdt_flush_identity (struct upcall_cache *, int)
__u32 mdt_identity_get_perm (struct md_identity *, __u32, lnet_nid_t)
int mdt_pack_remote_perm (struct mdt_thread_info *, struct mdt_object *, void *)
__u64 mdt_req_from_lrd (struct ptlrpc_request *req, struct tg_reply_data *trd)
int mdt_hsm_state_get (struct tgt_session_info *tsi)
Retrieve the current HSM flags, archive id and undergoing HSM requests for the fid provided in RPC body.
int mdt_hsm_state_set (struct tgt_session_info *tsi)
Change HSM state and archive number of a file.
int mdt_hsm_action (struct tgt_session_info *tsi)
Retrieve undergoing HSM requests for the fid provided in RPC body.
int mdt_hsm_progress (struct tgt_session_info *tsi)
Extract information coming from a copytool and asks coordinator to update a request status depending on the update content.
int mdt_hsm_ct_register (struct tgt_session_info *tsi)
int mdt_hsm_ct_unregister (struct tgt_session_info *tsi)
int mdt_hsm_request (struct tgt_session_info *tsi)
Process the HSM actions described in a struct hsm_user_request.
void dump_llog_agent_req_rec (const char *prefix, const struct llog_agent_req_rec *larr)
int cdt_llog_process (const struct lu_env *env, struct mdt_device *mdt, llog_cb_t cb, void *data)
int mdt_agent_record_add (const struct lu_env *env, struct mdt_device *mdt, __u64 compound_id, __u32 archive_id, __u64 flags, struct hsm_action_item *hai)
add an entry in agent llog
int mdt_agent_record_update (const struct lu_env *env, struct mdt_device *mdt, __u64 *cookies, int cookies_count, enum agent_req_status status)
update an entry in agent llog
int mdt_hsm_agent_register (struct mdt_thread_info *info, const struct obd_uuid *uuid, int nr_archives, __u32 *archive_num)
register a copy tool
int mdt_hsm_agent_register_mask (struct mdt_thread_info *info, const struct obd_uuid *uuid, __u32 archive_mask)
register a copy tool
int mdt_hsm_agent_unregister (struct mdt_thread_info *info, const struct obd_uuid *uuid)
unregister a copy tool
int mdt_hsm_agent_update_statistics (struct coordinator *cdt, int succ_rq, int fail_rq, int new_rq, const struct obd_uuid *uuid)
update agent statistics
int mdt_hsm_find_best_agent (struct coordinator *cdt, __u32 archive, struct obd_uuid *uuid)
find the best agent
int mdt_hsm_agent_send (struct mdt_thread_info *mti, struct hsm_action_list *hal, bool purge)
send a compound request to the agent
int mdt_hsm_coordinator_update (struct mdt_thread_info *mti, struct hsm_progress_kernel *pgs)
update status of a request
int mdt_hsm_add_actions (struct mdt_thread_info *info, struct hsm_action_list *hal, __u64 *compound_id)
register a list of requests
int mdt_hsm_get_actions (struct mdt_thread_info *mti, struct hsm_action_list *hal)
get registered action on a FID list
int mdt_hsm_get_running (struct mdt_thread_info *mti, struct hsm_action_list *hal)
get running action on a FID list or from cookie
bool mdt_hsm_restore_is_running (struct mdt_thread_info *mti, const struct lu_fid *fid)
check if a restore is running on a FID this is redundant with mdt_hsm_coordinator_get_running() but as it can be called frequently when getting attr we make an optimized/simpler version only for a FID
void dump_requests (char *prefix, struct coordinator *cdt)
dump requests list
struct cdt_agent_req * mdt_cdt_alloc_request (__u64 compound_id, __u32 archive_id, __u64 flags, struct obd_uuid *uuid, struct hsm_action_item *hai)
Allocate/init an agent request and its sub-structures.
void mdt_cdt_free_request (struct cdt_agent_req *car)
Free an agent request and its sub-structures.
int mdt_cdt_add_request (struct coordinator *cdt, struct cdt_agent_req *new_car)
add a request to the list
struct cdt_agent_req * mdt_cdt_find_request (struct coordinator *cdt, const __u64 cookie, const struct lu_fid *fid)
find request in the list by cookie or by fid
void mdt_cdt_get_work_done (struct cdt_agent_req *car, __u64 *done_sz)
scan the interval tree associated to a request to compute the amount of work done
void mdt_cdt_get_request (struct cdt_agent_req *car)
inc refcount of a request
void mdt_cdt_put_request (struct cdt_agent_req *car)
dec refcount of a request free if no more refcount
struct cdt_agent_req * mdt_cdt_update_request (struct coordinator *cdt, const struct hsm_progress_kernel *pgs)
update a request in the list on success, add a ref to the request returned
int mdt_cdt_remove_request (struct coordinator *cdt, __u64 cookie)
remove request from the list
void mdt_hsm_dump_hal (int level, const char *prefix, struct hsm_action_list *hal)
struct cdt_restore_handle * mdt_hsm_restore_hdl_find (struct coordinator *cdt, const struct lu_fid *fid)
lookup a restore handle by FID caller needs to hold cdt_restore_lock
int mdt_hsm_cdt_init (struct mdt_device *mdt)
initialize coordinator struct
int mdt_hsm_cdt_start (struct mdt_device *mdt)
start a coordinator thread
int mdt_hsm_cdt_stop (struct mdt_device *mdt)
stop a coordinator thread
int mdt_hsm_cdt_fini (struct mdt_device *mdt)
free a coordinator thread
int mdt_hsm_cdt_wakeup (struct mdt_device *mdt)
wake up coordinator thread
ssize_t mdt_hsm_cdt_control_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
int mdt_hsm_cdt_control_seq_show (struct seq_file *m, void *data)
int hsm_cdt_procfs_init (struct mdt_device *mdt)
create /proc entries for coordinator
void hsm_cdt_procfs_fini (struct mdt_device *mdt)
remove /proc entries for coordinator
struct lprocfs_vars * hsm_cdt_get_proc_vars (void)
get vector of hsm cdt /proc vars
struct mdt_object * mdt_hsm_get_md_hsm (struct mdt_thread_info *mti, const struct lu_fid *fid, struct md_hsm *hsm)
get obj and HSM attributes on a fid
int mdt_hsm_add_hal (struct mdt_thread_info *mti, struct hsm_action_list *hal, struct obd_uuid *uuid)
register all requests from an hal in the memory list
bool mdt_hsm_is_action_compat (const struct hsm_action_item *hai, const int hal_an, const __u64 rq_flags, const struct md_hsm *hsm)
check if a request is compatible with file status
int mdt_hsm_update_request_state (struct mdt_thread_info *mti, struct hsm_progress_kernel *pgs, const int update_record)
update status of a request
int mdt_close_swap_layouts (struct mdt_thread_info *info, struct mdt_object *o, struct md_attr *ma)
static int mdt_fail_write (const struct lu_env *env, struct dt_device *dd, int id)
static struct mdt_export_data * mdt_req2med (struct ptlrpc_request *req)
static struct mdt_device * mdt_exp2dev (struct obd_export *exp)
static int mdt_check_resent (struct mdt_thread_info *info, mdt_reconstruct_t reconstruct, struct mdt_lock_handle *lhc)
struct lu_ucred * mdt_ucred (const struct mdt_thread_info *info)
struct lu_ucred * mdt_ucred_check (const struct mdt_thread_info *info)
static int is_identity_get_disabled (struct upcall_cache *cache)
int mdt_blocking_ast (struct ldlm_lock *, struct ldlm_lock_desc *, void *, int)
Blocking AST for mdt locks.
static int mdt_fid_lock (struct ldlm_namespace *ns, struct lustre_handle *lh, enum ldlm_mode mode, union ldlm_policy_data *policy, const struct ldlm_res_id *res_id, __u64 flags, const __u64 *client_cookie)
static void mdt_fid_unlock (struct lustre_handle *lh, enum ldlm_mode mode)
static bool mdt_slc_is_enabled (struct mdt_device *mdt)
static mdl_mode_t mdt_dlm_mode2mdl_mode (enum ldlm_mode mode)
static enum ldlm_mode mdt_mdl_mode2dlm_mode (mdl_mode_t mode)
void mdt_enable_cos (struct mdt_device *, int)
Enable/disable COS (Commit On Sharing).
int mdt_cos_is_enabled (struct mdt_device *)
Check COS (Commit On Sharing) status.
void mdt_counter_incr (struct ptlrpc_request *req, int opcode)
void mdt_stats_counter_init (struct lprocfs_stats *stats)
int mdt_procfs_init (struct mdt_device *mdt, const char *name)
void mdt_procfs_fini (struct mdt_device *mdt)
int lprocfs_mdt_open_files_seq_open (struct inode *inode, struct file *file)
void mdt_rename_counter_tally (struct mdt_thread_info *info, struct mdt_device *mdt, struct ptlrpc_request *req, struct mdt_object *src, struct mdt_object *tgt)
static struct obd_device * mdt2obd_dev (const struct mdt_device *mdt)
static char * mdt_obd_name (struct mdt_device *mdt)
int mds_mod_init (void)
void mds_mod_exit (void)
static char * mdt_req_get_jobid (struct ptlrpc_request *req)
Variables
struct lu_context_key mdt_thread_key
struct kmem_cache * mdt_hsm_car_kmem
struct kmem_cache * mdt_hsm_cdt_kmem
struct upcall_cache_ops mdt_identity_upcall_cache_ops
struct file_operations mdt_hsm_actions_fops
struct file_operations mdt_hsm_agent_fops
struct file_operations mdt_hsm_active_requests_fops
mdl_mode_t mdt_mdl_lock_modes []
enum ldlm_mode mdt_dlm_lock_modes []
struct ldlm_valblock_ops mdt_lvbo
struct lu_device_operations mdt_lu_ops
Define Documentation
#define CDT_DEFAULT_POLICY CDT_NORETRY_ACTION
Definition at line 96 of file mdt_internal.h.
Referenced by mdt_hsm_cdt_init(), and mdt_hsm_cdt_start().
#define CDT_NONBLOCKING_RESTORE (1ULL << 0)
Definition at line 86 of file mdt_internal.h.
Referenced by mdt_hsm_add_actions().
#define CDT_NORETRY_ACTION (1ULL << 1)
Definition at line 87 of file mdt_internal.h.
Referenced by hsm_cdt_request_completed().
#define CDT_POLICY_ALL
Value:
(CDT_NONBLOCKING_RESTORE | \
                                        CDT_NORETRY_ACTION)
Definition at line 90 of file mdt_internal.h.
#define CDT_POLICY_LAST CDT_NORETRY_ACTION
Definition at line 88 of file mdt_internal.h.
Referenced by mdt_hsm_cdt_start().
#define CDT_POLICY_SHIFT_COUNT 2
Definition at line 89 of file mdt_internal.h.
Referenced by hsm_policy_bit2str(), and mdt_hsm_cdt_start().
#define MDT_COS_DEFAULT (0)
Definition at line 228 of file mdt_internal.h.
Referenced by mdt_init0().
#define MDT_EREMOTE_OPEN (EREMOTE + 1024)
Definition at line 289 of file mdt_internal.h.
Referenced by mdt_intent_reint(), mdt_object_open_unlock(), and mdt_reint_open().
#define MDT_FL_CFGLOG 0
Definition at line 154 of file mdt_internal.h.
Referenced by mdt_prepare().
#define MDT_FL_SYNCED 1
Definition at line 155 of file mdt_internal.h.
Referenced by mdt_obd_connect().
#define MDT_IDENTITY_UPCALL_PATH "/usr/sbin/l_getidentity"
Definition at line 772 of file mdt_internal.h.
Referenced by mdt_init0().
#define MDT_SERVICE_WATCHDOG_FACTOR (2)
Definition at line 227 of file mdt_internal.h.
Referenced by mds_start_ptlrpc_service(), and mdt_statfs().
Typedef Documentation
typedef void(* mdt_reconstruct_t)(struct mdt_thread_info *mti, struct mdt_lock_handle *lhc)
Definition at line 919 of file mdt_internal.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
MDT_LH_PARENT
MDT_LH_CHILD
MDT_LH_OLD
MDT_LH_LAYOUT
MDT_LH_NEW
MDT_LH_RMT
MDT_LH_LOCAL
MDT_LH_NR
Definition at line 268 of file mdt_internal.h.
anonymous enum
Enumerator:
MDT_LOCAL_LOCK
MDT_CROSS_LOCK
Definition at line 279 of file mdt_internal.h.
anonymous enum
Enumerator:
LPROC_MDT_OPEN
LPROC_MDT_CLOSE
LPROC_MDT_MKNOD
LPROC_MDT_LINK
LPROC_MDT_UNLINK
LPROC_MDT_MKDIR
LPROC_MDT_RMDIR
LPROC_MDT_RENAME
LPROC_MDT_GETATTR
LPROC_MDT_SETATTR
LPROC_MDT_GETXATTR
LPROC_MDT_SETXATTR
LPROC_MDT_STATFS
LPROC_MDT_SYNC
LPROC_MDT_SAMEDIR_RENAME
LPROC_MDT_CROSSDIR_RENAME
LPROC_MDT_LAST
Definition at line 1009 of file mdt_internal.h.
enum cdt_states
Enumerator:
CDT_STOPPED
CDT_INIT
CDT_RUNNING
CDT_DISABLE
CDT_STOPPING
Definition at line 98 of file mdt_internal.h.
enum mdt_name_flags
Enumerator:
MNF_FIX_ANON
Definition at line 631 of file mdt_internal.h.
enum mdt_object_flags
Enumerator:
MOF_LOV_CREATED
lov object has been created.
Definition at line 230 of file mdt_internal.h.
enum mdt_reint_flag
Enumerator:
MRF_OPEN_TRUNC
Definition at line 303 of file mdt_internal.h.
Function Documentation
bool allow_client_chgrp (struct mdt_thread_info * info, struct lu_ucred * uc)
Check whether allow the client to set supplementary group IDs or not.
Parameters:
[in] info pointer to the thread context
[in] uc pointer to the RPC user descriptor
Return values:
true if allow to set supplementary group IDs
false for other cases
Definition at line 334 of file mdt_lib.c.
References CFS_SETGRP_PERM, exp_connect_rmtclient(), is_identity_get_disabled(), mdt_device::mdt_identity_cache, mdt_identity_get_perm(), mdt_info_req(), mdt_thread_info::mti_exp, mdt_thread_info::mti_mdt, and lu_ucred::uc_identity.
Referenced by mdt_mfd_open().
int cdt_llog_process (const struct lu_env * env, struct mdt_device * mdt, llog_cb_t cb, void * data)
Definition at line 87 of file mdt_hsm_cdt_actions.c.
References coordinator::cdt_llog_lock, CERROR, ENTRY, LLOG_AGENT_ORIG_CTXT, llog_cat_process(), llog_ctxt_put(), llog_get_context(), llog_ctxt::loc_handle, mdt2obd_dev(), mdt_device::mdt_coordinator, mdt_obd_name(), and RETURN.
Referenced by hsm_cancel_all_actions(), hsm_find_compatible(), mdt_agent_record_update(), mdt_coordinator(), and mdt_hsm_pending_restore().
void dump_llog_agent_req_rec (const char * prefix, const struct llog_agent_req_rec * larr)
Definition at line 47 of file mdt_hsm_cdt_actions.c.
References agent_req_status2name(), llog_agent_req_rec::arr_archive_id, llog_agent_req_rec::arr_compound_id, llog_agent_req_rec::arr_flags, llog_agent_req_rec::arr_hai, llog_agent_req_rec::arr_hdr, llog_agent_req_rec::arr_req_change, llog_agent_req_rec::arr_req_create, llog_agent_req_rec::arr_status, buf, CDEBUG, D_HSM, DFID, hsm_action_item::hai_action, hsm_action_item::hai_cookie, hsm_action_item::hai_dfid, hai_dump_data_field(), hsm_action_item::hai_extent, hsm_action_item::hai_fid, hsm_action_item::hai_gid, hsm_action_item::hai_len, hsm_copytool_action2name(), hsm_extent::length, LPU64, LPX64, llog_rec_hdr::lrh_index, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, hsm_extent::offset, and PFID.
Referenced by mdt_coordinator_cb().
void dump_requests (char * prefix, struct coordinator * cdt)
dump requests list
Parameters:
cdt [IN] coordinator
Definition at line 48 of file mdt_hsm_cdt_requests.c.
References cdt_agent_req::car_archive_id, cdt_agent_req::car_canceled, cdt_agent_req::car_compound_id, cdt_agent_req::car_flags, cdt_agent_req::car_hai, cdt_agent_req::car_refcount, cdt_agent_req::car_request_list, CDEBUG, coordinator::cdt_request_lock, coordinator::cdt_requests, D_HSM, DFID, hsm_action_item::hai_action, hsm_action_item::hai_cookie, hsm_action_item::hai_dfid, hsm_action_item::hai_extent, hsm_action_item::hai_fid, hsm_action_item::hai_gid, hsm_copytool_action2name(), hsm_extent::length, list_for_each_entry, LPX64, hsm_extent::offset, and PFID.
Referenced by mdt_hsm_cdt_start().
struct lprocfs_vars* hsm_cdt_get_proc_vars (void) [read]
get vector of hsm cdt /proc vars
Parameters:
none
Return values:
var vector
Definition at line 414 of file mdt_coordinator.c.
References lprocfs_mdt_hsm_vars.
Referenced by mdt_process_config().
void hsm_cdt_procfs_fini (struct mdt_device * mdt)
remove /proc entries for coordinator
Parameters:
mdt [IN]
Definition at line 400 of file mdt_coordinator.c.
References coordinator::cdt_proc_dir, coordinator::cdt_state, CDT_STOPPED, LASSERT, lprocfs_remove(), and mdt_device::mdt_coordinator.
Referenced by mdt_procfs_fini().
int hsm_cdt_procfs_init (struct mdt_device * mdt)
create /proc entries for coordinator
Parameters:
mdt [IN]
Return values:
0 success
-ve failure
Definition at line 375 of file mdt_coordinator.c.
References coordinator::cdt_proc_dir, CERROR, ENTRY, lprocfs_mdt_hsm_vars, lprocfs_register(), mdt2obd_dev(), mdt_device::mdt_coordinator, mdt_obd_name(), and RETURN.
Referenced by mdt_procfs_init().
static int is_identity_get_disabled (struct upcall_cache * cache) [inline, static]
Definition at line 951 of file mdt_internal.h.
References upcall_cache::uc_upcall.
Referenced by allow_client_chgrp(), mdt_check_ucred(), mdt_handle_idmap(), new_init_ucred(), and old_init_ucred_common().
int lprocfs_mdt_open_files_seq_open (struct inode * inode, struct file * file)
Definition at line 914 of file mdt_lproc.c.
References lprocfs_mdt_open_files_seq_show().
void mds_mod_exit (void)
Definition at line 580 of file mdt_mds.c.
References class_unregister_type(), and LUSTRE_MDS_NAME.
Referenced by mdt_exit(), and mdt_init().
int mds_mod_init (void)
Definition at line 567 of file mdt_mds.c.
References class_register_type(), LCONSOLE_INFO, LUSTRE_MDS_NAME, mds_num_threads, and mdt_num_threads.
Referenced by mdt_init().
static struct obd_device* mdt2obd_dev (const struct mdt_device * mdt) [static, read]
Definition at line 1041 of file mdt_internal.h.
References lu_device::ld_obd, and mdt_device::mdt_lu_dev.
Referenced by cdt_llog_process(), hsm_cdt_procfs_init(), lproc_mdt_attach_rename_seqstat(), mdt_agent_record_add(), mdt_fini(), mdt_hsm_actions_proc_start(), mdt_hsm_agent_send(), mdt_init0(), mdt_llog_ctxt_clone(), mdt_llog_ctxt_unclone(), mdt_procfs_fini(), mdt_procfs_init(), mdt_stack_fini(), and old_init_ucred_common().
int mdt_add_dirty_flag (struct mdt_thread_info * info, struct mdt_object * mo, struct md_attr * ma)
Check HSM flags and add HS_DIRTY flag if relevant.
A file could be set dirty only if it has a copy in the backend (HS_EXISTS) and is not RELEASED.
Definition at line 678 of file mdt_reint.c.
References CERROR, DFID, ENTRY, HS_DIRTY, HS_EXISTS, HS_RELEASED, LCK_PW, md_attr::ma_hsm, MA_HSM, md_attr::ma_need, md_attr::ma_valid, MDS_INODELOCK_XATTR, mdt_attr_get_complex(), mdt_hsm_attr_set(), MDT_LH_CHILD, mdt_lock_reg_init(), mdt_object_fid(), mdt_object_lock(), mdt_object_unlock(), md_hsm::mh_flags, mdt_thread_info::mti_lh, PFID, and RETURN.
Referenced by mdt_ctxt_add_dirty_flag(), mdt_mfd_close(), and mdt_reint_setattr().
int mdt_agent_record_add (const struct lu_env * env, struct mdt_device * mdt, __u64 compound_id, __u32 archive_id, __u64 flags, struct hsm_action_item * hai)
add an entry in agent llog
Parameters:
env [IN] environment
mdt [IN] PDT device
compound_id [IN] global id associated with the record
archive_id [IN] backend archive number
hai [IN] record to register
Return values:
0 success
-ve failure
Definition at line 124 of file mdt_hsm_cdt_actions.c.
References llog_agent_req_rec::arr_archive_id, llog_agent_req_rec::arr_compound_id, llog_agent_req_rec::arr_flags, llog_agent_req_rec::arr_hai, llog_agent_req_rec::arr_hdr, llog_agent_req_rec::arr_req_change, llog_agent_req_rec::arr_req_create, llog_agent_req_rec::arr_status, ARS_WAITING, coordinator::cdt_last_cookie, coordinator::cdt_llog_lock, cfs_time_current_sec(), ENTRY, EXIT, GOTO, hsm_action_item::hai_action, hsm_action_item::hai_cookie, hsm_action_item::hai_len, HSM_AGENT_REC, HSMA_CANCEL, LLOG_AGENT_ORIG_CTXT, llog_cat_add(), llog_ctxt_put(), llog_data_len(), llog_get_context(), llog_ctxt::loc_handle, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, mdt2obd_dev(), mdt_device::mdt_coordinator, OBD_ALLOC, OBD_FREE, and RETURN.
Referenced by mdt_hsm_add_actions().
int mdt_agent_record_update (const struct lu_env * env, struct mdt_device * mdt, __u64 * cookies, int cookies_count, enum agent_req_status status)
update an entry in agent llog
Parameters:
env [IN] environment
mdt [IN] MDT device
cookie [IN] entries to update log cookie are returned by register
status [IN] new status of the request
Return values:
0 success
-ve failure
Definition at line 261 of file mdt_hsm_cdt_actions.c.
References agent_req_status2name(), cdt_llog_process(), CERROR, cfs_time_current_sec(), data_update_cb::change_time, data_update_cb::cookies, data_update_cb::cookies_count, data_update_cb::cookies_done, ENTRY, data_update_cb::mdt, mdt_agent_record_update_cb(), mdt_obd_name(), RETURN, and data_update_cb::status.
Referenced by mdt_coordinator(), mdt_hsm_add_hal(), mdt_hsm_agent_send(), and mdt_hsm_update_request_state().
int mdt_attr_get_complex (struct mdt_thread_info * info, struct mdt_object * o, struct md_attr * ma)
Definition at line 819 of file mdt_handler.c.
References CDEBUG, CLASSERT, D_INODE, ENTRY, GOTO, lu_buf::lb_buf, lu_buf::lb_len, LPX64, lu_object_attr(), lustre_buf2hsm(), md_attr::ma_acl, MA_ACL_DEF, md_attr::ma_acl_size, md_attr::ma_hsm, MA_HSM, MA_INODE, md_attr::ma_lmm, MA_LMV, MA_LMV_DEF, MA_LOV, md_attr::ma_need, md_attr::ma_pfid, MA_PFID, md_attr::ma_valid, mdt_attr_get_pfid(), mdt_object_child(), mdt_object_exists(), mdt_stripe_get(), mo_attr_get(), md_object::mo_lu, mo_xattr_get(), mode, mdt_thread_info::mti_buf, mdt_thread_info::mti_env, mdt_thread_info::mti_xattr_buf, RETURN, XATTR_NAME_ACL_DEFAULT, XATTR_NAME_DEFAULT_LMV, XATTR_NAME_HSM, XATTR_NAME_LMV, and XATTR_NAME_LOV.
Referenced by hsm_action_permission(), mdt_add_dirty_flag(), mdt_create_data(), mdt_cross_open(), mdt_getattr_internal(), mdt_getattr_name_lock(), mdt_hsm_get_md_hsm(), mdt_hsm_release(), mdt_hsm_state_get(), mdt_hsm_state_set(), mdt_md_create(), mdt_open_by_fid(), mdt_open_by_fid_lock(), mdt_reconstruct_create(), mdt_reconstruct_open(), mdt_reconstruct_setattr(), mdt_reint_migrate_internal(), mdt_reint_open(), mdt_reint_setattr(), mdt_reint_unlink(), and mdt_sync().
int mdt_big_xattr_get (struct mdt_thread_info * info, struct mdt_object * o, const char * name)
Definition at line 658 of file mdt_handler.c.
References ENTRY, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, LU_BUF_NULL, mdt_object_child(), mo_xattr_get(), mdt_thread_info::mti_big_lmm, mdt_thread_info::mti_big_lmm_used, mdt_thread_info::mti_big_lmmsize, mdt_thread_info::mti_buf, mdt_thread_info::mti_env, OBD_ALLOC_LARGE, OBD_FREE_LARGE, RETURN, size, and size_roundup_power2().
Referenced by mdt_attr_get_pfid(), mdt_init_slaves(), and mdt_stripe_get().
int mdt_blocking_ast (struct ldlm_lock * lock, struct ldlm_lock_desc * desc, void * data, int flag)
Blocking AST for mdt locks.
Starts transaction commit if in case of COS lock conflict or deffers such a commit to the mdt_save_lock.
Parameters:
lock the lock which blocks a request or cancelling lock
desc unused
data unused
flag indicates whether this cancelling or blocking callback
Return values:
0
See also:
ldlm_blocking_ast_nocheck
Definition at line 2308 of file mdt_handler.c.
References CWARN, ENTRY, ldlm_lock::l_blocking_ast, ldlm_lock::l_blocking_lock, ldlm_lock::l_client_cookie, ldlm_lock::l_req_mode, LCK_COS, LCK_EX, LCK_PW, LCT_LOCAL, ldlm_blocking_ast_nocheck(), LDLM_CB_CANCELING, ldlm_is_cos_incompat, ldlm_lock_to_ns(), lock_res_and_lock(), lu_env_fini(), lu_env_init(), mdt_blocking_ast(), mdt_cos_is_enabled(), mdt_dev(), mdt_device_commit_async(), mdt_set_lock_sync(), mdt_slc_is_enabled(), ldlm_namespace::ns_obd, obd_device::obd_lu_dev, obd_device::obd_name, RETURN, unlikely, and unlock_res_and_lock().
Referenced by mdt_blocking_ast(), mdt_fid_lock(), and mdt_lock_slaves().
void mdt_body_reverse_idmap (struct mdt_thread_info * , struct mdt_body *)
Definition at line 275 of file mdt_idmap.c.
References CFS_IDMAP_NOTFOUND, exp_connect_rmtclient(), lustre_idmap_lookup_gid(), lustre_idmap_lookup_uid(), mdt_body::mbo_gid, mdt_body::mbo_mode, mdt_body::mbo_uid, mdt_body::mbo_valid, mdt_info_req(), mdt_req2med(), mdt_ucred(), mdt_export_data::med_idmap, mdt_thread_info::mti_exp, NOBODY_GID, NOBODY_UID, OBD_MD_FLGID, OBD_MD_FLMODE, and OBD_MD_FLUID.
Referenced by mdt_pack_attr2body().
struct lu_buf* mdt_buf (const struct lu_env * env, void * area, ssize_t len) [read]
Definition at line 48 of file mdt_recovery.c.
References buf, lu_buf::lb_buf, lu_buf::lb_len, lu_env::le_ctx, lu_context_key_get(), mdt_thread_key, and mdt_thread_info::mti_buf.
struct lu_buf* mdt_buf_const (const struct lu_env * env, const void * area, ssize_t len) [read]
Definition at line 60 of file mdt_recovery.c.
References buf, lu_buf::lb_buf, lu_buf::lb_len, lu_env::le_ctx, lu_context_key_get(), mdt_thread_key, and mdt_thread_info::mti_buf.
int mdt_cdt_add_request (struct coordinator * cdt, struct cdt_agent_req * new_car)
add a request to the list
Parameters:
cdt [IN] coordinator
car [IN] request
Return values:
0 success
-ve failure
Definition at line 336 of file mdt_hsm_cdt_requests.c.
References cdt_agent_req::car_hai, cdt_agent_req::car_request_list, cdt_agent_req::car_uuid, cdt_find_request_nolock(), coordinator::cdt_request_count, coordinator::cdt_request_lock, coordinator::cdt_requests, ENTRY, hsm_action_item::hai_action, hsm_action_item::hai_cookie, HSMA_CANCEL, LASSERT, list_add_tail(), mdt_cdt_put_request(), mdt_hsm_agent_update_statistics(), and RETURN.
Referenced by mdt_hsm_add_hal().
struct cdt_agent_req* mdt_cdt_alloc_request (__u64 compound_id, __u32 archive_id, __u64 flags, struct obd_uuid * uuid, struct hsm_action_item * hai) [read]
Allocate/init an agent request and its sub-structures.
Parameters:
compound_id [IN]
archive_id [IN]
flags [IN]
uuid [IN]
hai [IN]
Return values:
car [OUT] success valid structure
car [OUT]
Definition at line 238 of file mdt_hsm_cdt_requests.c.
References cdt_agent_req::car_archive_id, cdt_agent_req::car_canceled, cdt_agent_req::car_compound_id, cdt_agent_req::car_flags, cdt_agent_req::car_hai, cdt_agent_req::car_progress, cdt_agent_req::car_refcount, cdt_agent_req::car_req_start, cdt_agent_req::car_req_update, cdt_agent_req::car_uuid, cfs_time_current_sec(), ENTRY, hsm_action_item::hai_len, mdt_cdt_init_request_tree(), mdt_hsm_car_kmem, OBD_ALLOC, OBD_SLAB_ALLOC_PTR, OBD_SLAB_FREE_PTR, and RETURN.
Referenced by mdt_hsm_add_hal().
struct cdt_agent_req* mdt_cdt_find_request (struct coordinator * cdt, const __u64 cookie, const struct lu_fid * fid) [read]
find request in the list by cookie or by fid
Parameters:
cdt [IN] coordinator
cookie [IN] request cookie
fid [IN] fid
Return values:
request pointer or NULL if not found
Definition at line 369 of file mdt_hsm_cdt_requests.c.
References cdt_find_request_nolock(), coordinator::cdt_request_lock, ENTRY, and RETURN.
Referenced by mdt_cdt_update_request(), mdt_coordinator_cb(), mdt_hsm_add_hal(), mdt_hsm_get_actions(), and mdt_hsm_get_running().
void mdt_cdt_free_request (struct cdt_agent_req * car)
Free an agent request and its sub-structures.
Parameters:
car [IN] Request to be freed.
Definition at line 273 of file mdt_hsm_cdt_requests.c.
References cdt_agent_req::car_hai, cdt_agent_req::car_progress, hsm_action_item::hai_len, mdt_cdt_free_request_tree(), mdt_hsm_car_kmem, OBD_FREE, and OBD_SLAB_FREE_PTR.
Referenced by mdt_cdt_put_request(), mdt_hsm_add_hal(), and mdt_hsm_cdt_stop().
void mdt_cdt_get_request (struct cdt_agent_req * car)
inc refcount of a request
Parameters:
car [IN] request
Definition at line 284 of file mdt_hsm_cdt_requests.c.
References cdt_agent_req::car_refcount.
Referenced by cdt_find_request_nolock(), and hsm_cancel_all_actions().
void mdt_cdt_get_work_done (struct cdt_agent_req * car, __u64 * done_sz)
scan the interval tree associated to a request to compute the amount of work done
Parameters:
car [IN] request
done_sz [OUT] will be set to the size of work done
Definition at line 98 of file mdt_hsm_cdt_requests.c.
References cdt_agent_req::car_progress, req_interval_data::crp, cdt_req_progress::crp_lock, cdt_req_progress::crp_root, req_interval_data::done_sz, interval_iterate(), and req_interval_cb().
Referenced by mdt_hsm_active_requests_proc_show(), and mdt_hsm_get_actions().
void mdt_cdt_put_request (struct cdt_agent_req * car)
dec refcount of a request free if no more refcount
Parameters:
car [IN] request
Definition at line 294 of file mdt_hsm_cdt_requests.c.
References cdt_agent_req::car_refcount, LASSERT, and mdt_cdt_free_request().
Referenced by hsm_cancel_all_actions(), mdt_cdt_add_request(), mdt_cdt_remove_request(), mdt_cdt_update_request(), mdt_coordinator_cb(), mdt_hsm_add_hal(), mdt_hsm_get_actions(), mdt_hsm_get_running(), and mdt_hsm_update_request_state().
int mdt_cdt_remove_request (struct coordinator * cdt, __u64 cookie)
remove request from the list
Parameters:
cdt [IN] coordinator
cookie [IN] request cookie
Return values:
request pointer
Definition at line 389 of file mdt_hsm_cdt_requests.c.
References cdt_agent_req::car_request_list, cdt_find_request_nolock(), coordinator::cdt_request_count, coordinator::cdt_request_lock, ENTRY, LASSERT, list_del(), mdt_cdt_put_request(), and RETURN.
Referenced by mdt_hsm_agent_send(), and mdt_hsm_update_request_state().
struct cdt_agent_req* mdt_cdt_update_request (struct coordinator * cdt, const struct hsm_progress_kernel * pgs) [read]
update a request in the list on success, add a ref to the request returned
Parameters:
cdt [IN] coordinator
pgs [IN] progression (cookie + extent + err)
Return values:
request pointer
-ve failure
Definition at line 424 of file mdt_hsm_cdt_requests.c.
References cdt_agent_req::car_progress, cdt_agent_req::car_req_update, cdt_agent_req::car_uuid, cfs_time_current_sec(), ENTRY, HP_FLAG_COMPLETED, hsm_progress_kernel::hpk_cookie, hsm_progress_kernel::hpk_errval, hsm_progress_kernel::hpk_extent, hsm_progress_kernel::hpk_flags, hsm_update_work(), hsm_extent::length, mdt_cdt_find_request(), mdt_cdt_put_request(), mdt_hsm_agent_update_statistics(), and RETURN.
Referenced by mdt_hsm_update_request_state().
static int mdt_check_resent (struct mdt_thread_info * info, mdt_reconstruct_t reconstruct, struct mdt_lock_handle * lhc) [inline, static]
Definition at line 921 of file mdt_internal.h.
References D_HA, DEBUG_REQ, ENTRY, lustre_msg_get_flags(), mdt_info_req(), MSG_RESENT, mdt_thread_info::mti_reply_data, OBD_ALLOC_PTR, OBD_FREE_PTR, req_can_reconstruct(), RETURN, and ptlrpc_request::rq_reqmsg.
Referenced by mdt_close(), and mdt_reint_internal().
int mdt_check_resent_lock (struct mdt_thread_info * info, struct mdt_object * mo, struct mdt_lock_handle * lhc)
Definition at line 2396 of file mdt_handler.c.
References lustre_handle::cookie, CWARN, DFID, obd_export::exp_obd, fid_res_name_eq(), ldlm_lock::l_resource, LASSERT, LDLM_DEBUG_NOLOCK, ldlm_handle2lock(), LDLM_LOCK_PUT, LPX64, ldlm_resource::lr_name, lustre_handle_is_used(), lustre_msg_get_flags(), mdt_info_req(), mdt_object_fid(), mdt_lock_handle::mlh_reg_lh, MSG_RESENT, mdt_thread_info::mti_exp, obd_device::obd_name, PFID, RETURN, ptlrpc_request::rq_reqmsg, and unlikely.
Referenced by mdt_getattr_name_lock(), mdt_open_by_fid_lock(), and mdt_reint_open().
int mdt_check_ucred (struct mdt_thread_info *)
Definition at line 362 of file mdt_lib.c.
References CDEBUG, CFS_SETGID_PERM, CFS_SETUID_PERM, D_SEC, ENTRY, EXIT, exp_connect_rmtclient(), GOTO, is_identity_get_disabled(), LASSERT, libcfs_nid2str(), make_kuid(), mdt_device::mdt_identity_cache, mdt_identity_get(), mdt_identity_get_perm(), mdt_identity_put(), mdt_info_req(), mdt_ucred(), md_identity::mi_gid, mdt_thread_info::mti_exp, mdt_thread_info::mti_mdt, lnet_process_id_t::nid, ptlrpc_user_desc_do_idmap(), ptlrpc_user_desc::pud_fsgid, ptlrpc_user_desc::pud_fsuid, ptlrpc_user_desc::pud_gid, ptlrpc_user_desc::pud_uid, RETURN, ptlrpc_request::rq_auth_gss, ptlrpc_request::rq_auth_usr_mdt, ptlrpc_request::rq_peer, lu_ucred::uc_valid, UCRED_NEW, UCRED_OLD, uid_valid(), and unlikely.
Referenced by mdt_get_root(), mdt_getattr(), and mdt_statfs().
static struct md_device_operations* mdt_child_ops (struct mdt_device * m) [static, read]
restore handle slab cache
Definition at line 494 of file mdt_internal.h.
References LASSERT, md_device::md_ops, and mdt_device::mdt_child.
void mdt_cleanup_idmap (struct mdt_export_data *)
Definition at line 116 of file mdt_idmap.c.
References lustre_idmap_fini(), mdt_export_data::med_idmap, and mdt_export_data::med_idmap_mutex.
Referenced by mdt_destroy_export().
void mdt_clear_disposition (struct mdt_thread_info * info, struct ldlm_reply * rep, __u64 op_flag)
Definition at line 141 of file mdt_handler.c.
References ldlm_reply::lock_policy_res1, mdt_thread_info::mti_env, mdt_thread_info::mti_opdata, and tgt_opdata_clear().
Referenced by mdt_object_open_unlock(), and mdt_reint_open().
void mdt_client_compatibility (struct mdt_thread_info * info)
Definition at line 600 of file mdt_handler.c.
References ENTRY, EXIT, exp_connect_layout(), lu_attr::la_mode, md_attr::ma_attr, md_attr::ma_lmm, mdt_body_has_lov(), mdt_info_req(), mdt_thread_info::mti_attr, mdt_thread_info::mti_pill, req_capsule_server_get(), RETURN_EXIT, RMF_MDT_BODY, and ptlrpc_request::rq_export.
Referenced by mdt_close(), mdt_getattr(), mdt_getattr_name(), mdt_intent_getattr(), mdt_reint_internal(), and mdt_reint_setattr().
int mdt_close (struct tgt_session_info * tsi)
Definition at line 2047 of file mdt_open.c.
References ENTRY, err_serious(), GOTO, LPROC_MDT_CLOSE, lustre_msg_get_status(), MA_INODE, md_attr::ma_lmm, md_attr::ma_lmm_size, MA_LOV, md_attr::ma_need, mdt_body::mbo_aclsize, mdt_body::mbo_eadatasize, mdt_check_resent(), mdt_client_compatibility(), mdt_close_internal(), mdt_close_unpack(), mdt_counter_incr(), mdt_empty_transno(), mdt_exit_ucred(), mdt_fix_reply(), mdt_reconstruct_generic(), mdt_thread_info_fini(), mdt_thread_info::mti_attr, mdt_thread_info::mti_pill, OBD_FAIL_CHECK, OBD_FAIL_CHECK_RESET, OBD_FAIL_MDS_CLOSE_NET_REP, OBD_FAIL_MDS_CLOSE_PACK, RCL_SERVER, req_capsule_get_size(), req_capsule_server_get(), req_capsule_server_pack(), req_capsule_set_size(), ret, RETURN, RMF_LOGCOOKIES, RMF_MDT_BODY, RMF_MDT_MD, ptlrpc_request::rq_repmsg, tgt_ses_req(), tsi2mdt_info(), and tgt_session_info::tsi_reply_fail_id.
int mdt_close_internal (struct mdt_thread_info * info, struct ptlrpc_request * req, struct mdt_body * repbody)
not serious error since bug 3633
Definition at line 2009 of file mdt_open.c.
References CDEBUG, class_handle_unhash(), lustre_handle::cookie, D_INODE, DFID, ENTRY, list_del_init(), LPX64, mdt_handle2mfd(), mdt_handle_last_unlink(), mdt_mfd_close(), mdt_mfd_closed(), mdt_object_get(), mdt_object_put(), mdt_export_data::med_open_lock, mdt_file_data::mfd_handle, mdt_file_data::mfd_list, mdt_file_data::mfd_object, mdt_thread_info::mti_attr, mdt_thread_info::mti_close_handle, mdt_thread_info::mti_env, mdt_thread_info::mti_rr, PFID, req_is_replay(), ret, RETURN, ptlrpc_request::rq_export, and mdt_reint_record::rr_fid1.
Referenced by mdt_close(), and mdt_reint_migrate_internal().
int mdt_close_swap_layouts (struct mdt_thread_info * info, struct mdt_object * o, struct md_attr * ma)
Definition at line 1797 of file mdt_open.c.
References close_data::cd_fid, close_data::cd_handle, DFID, ENTRY, EXIT, exp_connect_flags(), fid_is_sane(), fid_is_zero(), GOTO, ldlm_lock::l_resource, LASSERT, LCK_EX, LDLM_DEBUG, ldlm_handle2lock(), ldlm_is_cancel, ldlm_lock_cancel(), LDLM_LOCK_PUT, ldlm_reprocess_all(), lock_res_and_lock(), lu_fid_cmp(), lu_object_attr(), md_attr::ma_need, md_attr::ma_valid, mdt_body::mbo_valid, MDS_INODELOCK_LAYOUT, MDS_INODELOCK_XATTR, MDT_LH_NEW, MDT_LH_OLD, mdt_lock_reg_init(), mdt_object_child(), mdt_object_fid(), mdt_object_find(), mdt_object_lock(), mdt_object_put(), mdt_object_unlock(), mo_permission(), mo_swap_layouts(), mdt_object::mot_obj, mdt_object::mot_open_sem, mdt_thread_info::mti_env, mdt_thread_info::mti_exp, mdt_thread_info::mti_lh, mdt_thread_info::mti_mdt, mdt_thread_info::mti_pill, OBD_CONNECT_RDONLY, OBD_MD_CLOSE_INTENT_EXECED, PFID, req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_CLOSE_DATA, RMF_MDT_BODY, swap, unlikely, and unlock_res_and_lock().
Referenced by mdt_mfd_close().
int mdt_close_unpack (struct mdt_thread_info * info)
Definition at line 1053 of file mdt_lib.c.
References ENTRY, mdt_close_handle_unpack(), mdt_init_ucred_reint(), mdt_intent_close_unpack(), mdt_setattr_unpack_rec(), and RETURN.
Referenced by mdt_close().
static __u64 mdt_conn_flags (struct mdt_thread_info * info) [inline, static]
Definition at line 511 of file mdt_internal.h.
References exp_connect_flags(), LASSERT, and mdt_thread_info::mti_exp.
int mdt_cos_is_enabled (struct mdt_device * mdt)
Check COS (Commit On Sharing) status.
Return COS flag status.
Parameters:
mdt mdt device
Definition at line 6104 of file mdt_handler.c.
References mdt_device::mdt_opts, and mdt_device::mo_cos.
Referenced by mdt_blocking_ast(), mdt_cos_seq_show(), mdt_object_local_lock(), and mdt_save_lock().
void mdt_counter_incr (struct ptlrpc_request * req, int opcode)
Definition at line 929 of file mdt_lproc.c.
References exp_connect_flags(), obd_export::exp_nid_stats, obd_export::exp_obd, lprocfs_counter_incr(), lprocfs_job_stats_log(), lustre_msg_get_jobid(), nid_stat::nid_stats, OBD_CONNECT_JOBSTATS, obd_device::obd_md_stats, ptlrpc_request::rq_export, ptlrpc_request::rq_reqmsg, and obd_device::u.
Referenced by mdt_close(), mdt_getattr_internal(), mdt_getxattr(), mdt_reint_create(), mdt_reint_link(), mdt_reint_open(), mdt_reint_rename_internal(), mdt_reint_setattr(), mdt_reint_setxattr(), mdt_reint_unlink(), mdt_rename_counter_tally(), mdt_statfs(), and mdt_sync().
static struct mdt_device* mdt_dev (struct lu_device * d) [static, read]
Definition at line 750 of file mdt_internal.h.
References mdt_device::mdt_lu_dev.
Referenced by mdt_exp2dev(), and mdt_obj2dt().
static mdl_mode_t mdt_dlm_mode2mdl_mode (enum ldlm_mode mode) [inline, static]
Definition at line 990 of file mdt_internal.h.
References LASSERT, and mdt_mdl_lock_modes.
Referenced by mdt_lock_pdo_mode(), mdt_md_create(), and mdt_reint_open().
void mdt_dump_lmm (int level, const struct lov_mds_md * lmm, __u64 valid)
Definition at line 630 of file mdt_lib.c.
References CDEBUG, cfs_cdebug_show(), DEBUG_SUBSYSTEM, DOSTID, lov_ost_data_v1::l_ost_idx, lov_ost_data_v1::l_ost_oi, LASSERT, le16_to_cpu, le32_to_cpu, likely, LOV_MAX_STRIPE_COUNT, LOV_PATTERN_F_RELEASED, lov_user_md, OBD_MD_FLDIREA, ostid_le_to_cpu(), and POSTID.
Referenced by mdt_getattr_internal().
void mdt_dump_lmv (unsigned int level, const union lmv_mds_md * lmv)
Definition at line 663 of file mdt_lib.c.
References CDEBUG, cfs_cdebug_show(), DEBUG_SUBSYSTEM, DFID, fid_le_to_cpu(), le32_to_cpu, likely, lmv_mds_md_v1::lmv_magic, LMV_MAGIC_STRIPE, lmv_mds_md_v1::lmv_master_mdt_index, lmv_mds_md::lmv_md_v1, lmv_mds_md_v1::lmv_stripe_count, lmv_mds_md_v1::lmv_stripe_fids, and PFID.
Referenced by mdt_getattr_internal().
void mdt_enable_cos (struct mdt_device * mdt, int val)
Enable/disable COS (Commit On Sharing).
Set/Clear the COS flag in mdt options.
Parameters:
mdt mdt device
val 0 disables COS, other values enable COS
Definition at line 6081 of file mdt_handler.c.
References CWARN, LCT_LOCAL, lu_env_fini(), lu_env_init(), mdt_device_sync(), mdt_obd_name(), mdt_device::mdt_opts, mdt_device::mo_cos, and unlikely.
Referenced by mdt_cos_seq_write().
void mdt_exit_ucred (struct mdt_thread_info *)
Definition at line 65 of file mdt_lib.c.
References LASSERT, mdt_device::mdt_identity_cache, mdt_identity_put(), mdt_ucred(), mdt_thread_info::mti_mdt, lu_ucred::uc_ginfo, lu_ucred::uc_identity, lu_ucred::uc_suppgids, lu_ucred::uc_valid, and UCRED_INIT.
Referenced by __mdt_init_ucred(), mdt_close(), mdt_getattr(), mdt_getattr_name(), mdt_getxattr(), mdt_hsm_action(), mdt_hsm_is_admin(), mdt_hsm_request(), mdt_hsm_state_get(), mdt_hsm_state_set(), mdt_init_ucred_reint(), mdt_intent_getattr(), mdt_reint_internal(), and mdt_reint_setxattr().
static struct mdt_device* mdt_exp2dev (struct obd_export * exp) [static, read]
Definition at line 914 of file mdt_internal.h.
References obd_export::exp_obd, mdt_dev(), and obd_device::obd_lu_dev.
Referenced by mdt_handle_idmap(), mdt_quota_dqacq(), mdt_quotactl(), mdt_reint_opcode(), and mdt_sync().
static void mdt_export_evict (struct obd_export * exp) [inline, static]
Definition at line 558 of file mdt_internal.h.
References class_fail_export().
Referenced by mdt_reconstruct_create(), mdt_reconstruct_open(), and mdt_reconstruct_setattr().
int mdt_export_stats_init (struct obd_device * obd, struct obd_export * exp, void * localdata)
Initialize MDT per-export statistics.
This function sets up procfs entries for various MDT export counters. These counters are for per-client statistics tracked on the server.
Parameters:
[in] obd OBD device
[in] exp OBD export
[in] localdata NID of client
Return values:
0 if successful
negative value on error
Definition at line 66 of file mdt_fs.c.
References CWARN, ENTRY, obd_export::exp_nid_stats, GOTO, LASSERT, LPROC_MDT_LAST, lprocfs_alloc_stats(), lprocfs_free_stats(), lprocfs_nid_ldlm_stats_init(), lprocfs_register_stats(), LPROCFS_STATS_FLAG_NOPERCPU, mdt_open_files_seq_fops, mdt_stats_counter_init(), nid_stat::nid_proc, nid_stat::nid_stats, obd_device::obd_name, obd_device::obd_uses_nid_stats, and RETURN.
Referenced by mdt_obd_connect(), and mdt_obd_reconnect().
static int mdt_fail_write (const struct lu_env * env, struct dt_device * dd, int id) [inline, static]
Definition at line 896 of file mdt_internal.h.
References CERROR, dt_device::dd_ops, dt_device_operations::dt_ro, LUSTRE_MDT_NAME, OBD_FAIL_CHECK_ORSET, and OBD_FAIL_ONCE.
Referenced by mdt_attr_set(), mdt_md_create(), mdt_reint_link(), mdt_reint_migrate_internal(), mdt_reint_rename_internal(), mdt_reint_setxattr(), and mdt_reint_unlink().
static int mdt_fid_lock (struct ldlm_namespace * ns, struct lustre_handle * lh, enum ldlm_mode mode, union ldlm_policy_data * policy, const struct ldlm_res_id * res_id, __u64 flags, const __u64 * client_cookie) [inline, static]
Definition at line 959 of file mdt_internal.h.
References ELDLM_OK, LASSERT, ldlm_cli_enqueue_local(), ldlm_completion_ast(), LDLM_IBITS, LVB_T_NONE, and mdt_blocking_ast().
Referenced by mdt_object_local_lock(), and mdt_pdir_hash_lock().
static void mdt_fid_unlock (struct lustre_handle * lh, enum ldlm_mode mode) [inline, static]
Definition at line 977 of file mdt_internal.h.
References ldlm_lock_decref().
Referenced by mdt_save_lock().
int mdt_fix_attr_ucred (struct mdt_thread_info * , __u32)
Definition at line 317 of file mdt_idmap.c.
References CDEBUG, CFS_IDMAP_NOTFOUND, D_SEC, exp_connect_rmtclient(), lu_attr::la_gid, LA_GID, lu_attr::la_uid, LA_UID, lu_attr::la_valid, lustre_idmap_lookup_gid(), lustre_idmap_lookup_uid(), md_attr::ma_attr, mdt_info_req(), mdt_req2med(), mdt_ucred_check(), mdt_export_data::med_idmap, mdt_thread_info::mti_attr, mdt_thread_info::mti_exp, REINT_SETATTR, lu_ucred::uc_fsgid, and lu_ucred::uc_fsuid.
Referenced by mdt_reint_internal().
int mdt_fix_reply (struct mdt_thread_info * info)
Definition at line 689 of file mdt_lib.c.
References CDEBUG, D_INFO, ENTRY, LASSERT, lustre_msg_set_transno(), md_attr::ma_lmm, md_attr::ma_lmm_size, md_attr::ma_lmv, MA_LMV, md_attr::ma_lmv_size, MA_LOV, md_attr::ma_valid, mdt_body::mbo_aclsize, mdt_body::mbo_eadatasize, mdt_body::mbo_valid, mdt_device::mdt_max_mdsize, mdt_thread_info::mti_attr, mdt_thread_info::mti_big_lmm_used, mdt_thread_info::mti_mdt, mdt_thread_info::mti_pill, mdt_thread_info::mti_spec, md_op_spec::no_create, OBD_MD_FLDIREA, OBD_MD_FLEASIZE, OBD_MD_FLMDSCAPA, OBD_MD_FLOSSCAPA, OBD_MD_LINKNAME, req_capsule::rc_req, RCL_SERVER, req_capsule_get_size(), req_capsule_has_field(), req_capsule_server_get(), req_capsule_server_grow(), req_capsule_shrink(), RETURN, RMF_ACL, RMF_CAPA1, RMF_CAPA2, RMF_LOGCOOKIES, RMF_MDT_BODY, RMF_MDT_MD, and ptlrpc_request::rq_repmsg.
Referenced by mdt_close(), mdt_getattr(), mdt_getattr_name(), mdt_intent_getattr(), mdt_reint_internal(), and mdt_reint_setattr().
void mdt_flush_identity (struct upcall_cache * , int)
Definition at line 236 of file mdt_identity.c.
References __u64, upcall_cache_flush_idle(), and upcall_cache_flush_one().
Referenced by lprocfs_identity_flush_seq_write().
void mdt_fs_cleanup (const struct lu_env * , struct mdt_device *)
Definition at line 120 of file mdt_recovery.c.
References dt_txn_callback_del(), ENTRY, EXIT, mdt_device::mdt_bottom, and mdt_device::mdt_txn_cb.
Referenced by mdt_fini(), and mdt_init0().
int mdt_fs_setup (const struct lu_env * , struct mdt_device * , struct obd_device * , struct lustre_sb_info * lsi)
Definition at line 97 of file mdt_recovery.c.
References dt_txn_callback_add(), dt_txn_callback::dtc_cookie, dt_txn_callback::dtc_linkage, dt_txn_callback::dtc_tag, dt_txn_callback::dtc_txn_commit, dt_txn_callback::dtc_txn_start, dt_txn_callback::dtc_txn_stop, ENTRY, INIT_LIST_HEAD, LCT_MD_THREAD, mdt_device::mdt_bottom, mdt_device::mdt_txn_cb, mdt_txn_stop_cb(), OBD_FAIL_CHECK, OBD_FAIL_MDS_FS_SETUP, and RETURN.
Referenced by mdt_init0().
__u64 mdt_get_disposition (struct ldlm_reply * rep, __u64 op_flag)
Definition at line 134 of file mdt_handler.c.
References ldlm_reply::lock_policy_res1.
Referenced by mdt_intent_getattr(), mdt_intent_reint(), and mdt_reconstruct_open().
int mdt_get_info (struct tgt_session_info * tsi)
Definition at line 5728 of file mdt_handler.c.
References CDEBUG, D_IOCTL, ENTRY, err_serious(), KEY_FID2PATH, KEY_IS, mdt_rpc_fid2path(), mdt_thread_info_fini(), RCL_CLIENT, RCL_SERVER, req_capsule_client_get(), req_capsule_get_size(), req_capsule_server_get(), req_capsule_server_pack(), req_capsule_set_size(), RETURN, RMF_GETINFO_KEY, RMF_GETINFO_VAL, RMF_GETINFO_VALLEN, tgt_name(), tsi2mdt_info(), tgt_session_info::tsi_pill, and tgt_session_info::tsi_tgt.
int mdt_getxattr (struct mdt_thread_info * info)
Definition at line 227 of file mdt_xattr.c.
References buf, CDEBUG, CFS_RMTACL_PERM, D_INFO, D_INODE, DFID, ENTRY, err_serious(), EXIT, exp_connect_rmtclient(), GOTO, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, LBUG, LPROC_MDT_GETXATTR, lu_object_assert_exists(), lu_ucred(), MAY_RGETFACL, mdt_body::mbo_eadatasize, mdt_body::mbo_fid1, mdt_body::mbo_valid, mdt_counter_incr(), mdt_exit_ucred(), mdt_getxattr_all(), mdt_getxattr_one(), mdt_getxattr_pack_reply(), mdt_identity_get_perm(), mdt_info_req(), mdt_init_ucred(), mdt_object_child(), mdt_req2med(), mo_permission(), mo_xattr_list(), mdt_object::mot_obj, mdt_thread_info::mti_body, mdt_thread_info::mti_buf, mdt_thread_info::mti_env, mdt_thread_info::mti_exp, mdt_thread_info::mti_object, mdt_thread_info::mti_pill, lnet_process_id_t::nid, OBD_MD_FLRMTRGETFACL, OBD_MD_FLXATTR, OBD_MD_FLXATTRALL, OBD_MD_FLXATTRLS, PFID, req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_EADATA, RMF_MDT_BODY, RMF_NAME, ptlrpc_request::rq_peer, lu_ucred::uc_identity, and unlikely.
Referenced by mdt_intent_getxattr(), and mdt_tgt_getxattr().
struct mdt_file_data* mdt_handle2mfd (struct mdt_export_data * med, const struct lustre_handle * handle, bool is_replay) [read]
Definition at line 84 of file mdt_open.c.
References class_handle2object(), lustre_handle::cookie, ENTRY, LASSERT, list_for_each_entry, mdt_export_data::med_open_head, mdt_file_data::mfd_list, mdt_file_data::mfd_old_handle, and RETURN.
Referenced by mdt_close_internal(), mdt_mfd_open(), and mdt_object_open_lock().
int mdt_handle_idmap (struct tgt_session_info * tsi)
Definition at line 135 of file mdt_idmap.c.
References CDEBUG, D_SEC, ENTRY, exp_connect_rmtclient(), is_identity_get_disabled(), LASSERT, lustre_idmap_add(), lustre_idmap_del(), lustre_msg_get_opc(), make_kuid(), MDS_CONNECT, mdt_exp2dev(), mdt_device::mdt_identity_cache, mdt_identity_get(), mdt_identity_put(), mdt_req2med(), mdt_revoke_export_locks(), mdt_export_data::med_idmap, md_identity::mi_gid, md_identity::mi_uid, ptlrpc_user_desc::pud_gid, ptlrpc_user_desc::pud_uid, RETURN, ptlrpc_request::rq_export, ptlrpc_request::rq_reqmsg, SEC_CTX_FINI, SEC_CTX_INIT, SEC_CTX_INIT_CONT, tgt_ses_req(), uid_valid(), and unlikely.
Referenced by mdt_init_idmap(), and mdt_sec_ctx_handle().
int mdt_handle_last_unlink (struct mdt_thread_info * , struct mdt_object * , const struct md_attr *)
Definition at line 811 of file mdt_lib.c.
References CERROR, ENTRY, LASSERT, md_attr::ma_attr, MA_INODE, MA_LOV, md_attr::ma_valid, mdt_body::mbo_eadatasize, mdt_object_fid(), mdt_pack_attr2body(), mdt_thread_info::mti_pill, req_capsule_server_get(), RETURN, and RMF_MDT_BODY.
Referenced by mdt_close_internal(), mdt_reint_rename_internal(), and mdt_reint_unlink().
int mdt_hsm_action (struct tgt_session_info * tsi)
Retrieve undergoing HSM requests for the fid provided in RPC body.
Current requests are read from coordinator states.
This is MDS_HSM_ACTION RPC handler.
Definition at line 371 of file mdt_hsm.c.
References CERROR, cfs_size_round(), DFID, ENTRY, err_serious(), EXIT, GOTO, hsm_action_item::hai_action, hsm_action_item::hai_cookie, hsm_action_item::hai_extent, hsm_action_item::hai_fid, hai_first(), hsm_action_item::hai_gid, hsm_action_item::hai_len, hsm_action_list::hal_archive_id, hsm_action_list::hal_count, hsm_action_list::hal_flags, hsm_action_list::hal_fsname, hal_size(), HAL_VERSION, hsm_action_list::hal_version, hsm_current_action::hca_action, hsm_current_action::hca_location, hsm_current_action::hca_state, HPS_RUNNING, HPS_WAITING, HSMA_ARCHIVE, HSMA_CANCEL, HSMA_NONE, HSMA_REMOVE, HSMA_RESTORE, HUA_ARCHIVE, HUA_CANCEL, HUA_NONE, HUA_REMOVE, HUA_RESTORE, mdt_body::mbo_fid1, mdt_exit_ucred(), MDT_HSM_ALLOC, MDT_HSM_FREE, mdt_hsm_get_actions(), mdt_init_ucred(), mdt_obd_name(), mdt_thread_info_fini(), mdt_thread_info::mti_body, mdt_thread_info::mti_mdt, MTI_NAME_MAXLEN, obd_uuid2fsname(), PFID, req_capsule_server_get(), RETURN, RMF_MDS_HSM_CURRENT_ACTION, tsi2mdt_info(), tgt_session_info::tsi_mdt_body, and tgt_session_info::tsi_pill.
int mdt_hsm_add_actions (struct mdt_thread_info * mti, struct hsm_action_list * hal, __u64 * compound_id)
register a list of requests
Parameters:
mti [IN]
hal [IN] list of requests
compound_id [OUT] id of the compound request
Return values:
0 success
-ve failure in case of restore, caller must hold layout lock
Definition at line 298 of file mdt_hsm_cdt_client.c.
References __u64, coordinator::cdt_compound_id, coordinator::cdt_default_archive_id, CDT_NONBLOCKING_RESTORE, coordinator::cdt_policy, coordinator::cdt_restore_hdl, coordinator::cdt_restore_lock, coordinator::cdt_state, CDT_STOPPED, CERROR, CFS_CAP_SYS_ADMIN, cdt_restore_handle::crh_extent, cdt_restore_handle::crh_fid, cdt_restore_handle::crh_lh, cdt_restore_handle::crh_list, DFID, ldlm_extent::end, ENTRY, GOTO, hai_first(), hai_next(), hsm_action_list::hal_archive_id, hsm_action_list::hal_count, hsm_action_list::hal_flags, hal_is_sane(), hsm_action_is_needed(), hsm_action_permission(), hsm_find_compatible(), HSMA_CANCEL, HSMA_REMOVE, HSMA_RESTORE, LCK_EX, list_add_tail(), md_capable(), MDS_INODELOCK_LAYOUT, mdt_agent_record_add(), mdt_device::mdt_coordinator, mdt_hsm_cdt_kmem, mdt_hsm_cdt_wakeup(), mdt_hsm_get_md_hsm(), mdt_hsm_is_action_compat(), mdt_lock_reg_init(), mdt_obd_name(), mdt_object_find_lock(), mdt_object_put(), mdt_ucred(), md_hsm::mh_arch_id, mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, OBD_SLAB_ALLOC_PTR, OBD_SLAB_FREE_PTR, PFID, RETURN, and ldlm_extent::start.
Referenced by mdt_hsm_request().
int mdt_hsm_add_hal (struct mdt_thread_info * mti, struct hsm_action_list * hal, struct obd_uuid * uuid)
register all requests from an hal in the memory list
Parameters:
mti [IN] context
hal [IN] request
uuid [OUT] in case of CANCEL, the uuid of the agent which is running the CT
Return values:
0 success
-ve failure
Definition at line 1011 of file mdt_coordinator.c.
References agent_req_status2name(), ARS_CANCELED, cdt_agent_req::car_canceled, cdt_agent_req::car_uuid, CERROR, ENTRY, GOTO, hai_first(), hai_next(), hsm_action_list::hal_archive_id, hsm_action_list::hal_compound_id, hsm_action_list::hal_count, hsm_action_list::hal_flags, HS_EXISTS, HSMA_ARCHIVE, HSMA_CANCEL, LPX64, mdt_agent_record_update(), mdt_cdt_add_request(), mdt_cdt_alloc_request(), mdt_cdt_find_request(), mdt_cdt_free_request(), mdt_cdt_put_request(), mdt_device::mdt_coordinator, mdt_hsm_attr_set(), mdt_hsm_get_md_hsm(), mdt_obd_name(), mdt_object_put(), md_hsm::mh_arch_id, md_hsm::mh_flags, mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, and RETURN.
Referenced by mdt_hsm_agent_send().
int mdt_hsm_agent_register (struct mdt_thread_info * mti, const struct obd_uuid * uuid, int nr_archives, __u32 * archive_id)
register a copy tool
Parameters:
mti [IN] MDT context
uuid [IN] client UUID to be registered
count [IN] number of archives agent serves
archive_id [IN] vector of archive number served by the copytool
Return values:
0 success
-ve failure
Definition at line 78 of file mdt_hsm_cdt_agent.c.
References CDEBUG, coordinator::cdt_agent_lock, coordinator::cdt_agents, coordinator::cdt_state, CDT_STOPPED, D_HSM, ENTRY, GOTO, hsm_agent::ha_archive_cnt, hsm_agent::ha_archive_id, hsm_agent::ha_failure, hsm_agent::ha_list, hsm_agent::ha_requests, hsm_agent::ha_success, hsm_agent::ha_uuid, LCONSOLE_WARN, list_add_tail(), mdt_device::mdt_coordinator, mdt_hsm_agent_lookup(), mdt_thread_info::mti_mdt, OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, obd_uuid2str(), and RETURN.
Referenced by mdt_hsm_agent_register_mask().
int mdt_hsm_agent_register_mask (struct mdt_thread_info * mti, const struct obd_uuid * uuid, __u32 archive_mask)
register a copy tool
Parameters:
mti [IN] MDT context
uuid [IN] uuid to be registered
archive_mask [IN] bitmask of archive number served by the copytool
Return values:
0 success
-ve failure
Definition at line 153 of file mdt_hsm_cdt_agent.c.
References ENTRY, mdt_hsm_agent_register(), OBD_ALLOC, OBD_FREE, and RETURN.
Referenced by mdt_hsm_ct_register().
int mdt_hsm_agent_send (struct mdt_thread_info * mti, struct hsm_action_list * hal, bool purge)
send a compound request to the agent
Parameters:
mti [IN] context
hal [IN] request (can be a kuc payload)
purge [IN] purge mode (no record)
Return values:
0 success
-ve failure This function supposes:
all actions are for the same archive number
in case of cancel, all cancel are for the same agent This implies that request split has to be done before when building the hal
Definition at line 322 of file mdt_hsm_cdt_agent.c.
References agent_req_status2name(), ARS_FAILED, buf, CDEBUG, coordinator::cdt_restore_lock, CERROR, cfs_hash_lookup(), class_export_put(), cdt_restore_handle::crh_lh, cdt_restore_handle::crh_list, D_HSM, do_set_info_async(), ENTRY, obd_export::exp_disconnected, obd_export::exp_imp_reverse, GOTO, hai_first(), hai_next(), hsm_action_list::hal_archive_id, hsm_action_list::hal_count, hsm_action_list::hal_flags, hal_size(), HMT_ACTION_LIST, HSMA_CANCEL, HSMA_REMOVE, HSMA_RESTORE, KEY_HSM_COPYTOOL_SEND, kuc_alloc(), kuc_free(), kuc_len(), kuc_ptr(), KUC_TRANSPORT_HSM, LDLM_SET_INFO, list_del(), LPX64, LUSTRE_OBD_VERSION, mdt2obd_dev(), mdt_agent_record_update(), mdt_cdt_remove_request(), mdt_device::mdt_coordinator, mdt_hsm_add_hal(), mdt_hsm_agent_unregister(), mdt_hsm_cdt_kmem, mdt_hsm_find_best_agent(), mdt_hsm_get_md_hsm(), mdt_hsm_is_action_compat(), mdt_hsm_restore_hdl_find(), mdt_obd_name(), mdt_object_find(), mdt_object_put(), mdt_object_unlock(), mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, OBD_SLAB_FREE_PTR, obd_uuid2str(), and RETURN.
Referenced by hsm_cancel_all_actions(), and mdt_coordinator().
int mdt_hsm_agent_unregister (struct mdt_thread_info * mti, const struct obd_uuid * uuid)
unregister a copy tool
Parameters:
mti [IN] MDT context
uuid [IN] uuid to be unregistered
Return values:
0 success
-ve failure
Definition at line 191 of file mdt_hsm_cdt_agent.c.
References CDEBUG, coordinator::cdt_agent_lock, coordinator::cdt_state, CDT_STOPPED, D_HSM, ENTRY, GOTO, hsm_agent::ha_archive_cnt, hsm_agent::ha_archive_id, hsm_agent::ha_list, list_del_init(), mdt_device::mdt_coordinator, mdt_hsm_agent_lookup(), mdt_thread_info::mti_mdt, OBD_FREE, OBD_FREE_PTR, obd_uuid2str(), and RETURN.
Referenced by mdt_hsm_agent_send(), and mdt_hsm_ct_unregister().
int mdt_hsm_agent_update_statistics (struct coordinator * cdt, int succ_rq, int fail_rq, int new_rq, const struct obd_uuid * uuid)
update agent statistics
Parameters:
mdt [IN] MDT device
succ_rq [IN] number of success
fail_rq [IN] number of failure
new_rq [IN] number of new requests
uuid [IN] agent uuid if all counters == 0, clear counters
Return values:
0 success
-ve failure
Definition at line 237 of file mdt_hsm_cdt_agent.c.
References coordinator::cdt_agent_lock, coordinator::cdt_agents, ENTRY, GOTO, hsm_agent::ha_failure, hsm_agent::ha_list, hsm_agent::ha_requests, hsm_agent::ha_success, hsm_agent::ha_uuid, list_for_each_entry, obd_uuid_equals(), and RETURN.
Referenced by mdt_cdt_add_request(), and mdt_cdt_update_request().
int mdt_hsm_attr_set (struct mdt_thread_info * info, struct mdt_object * obj, const struct md_hsm * mh)
Update on-disk HSM attributes.
Definition at line 58 of file mdt_hsm.c.
References buf, CLASSERT, ENTRY, lu_buf::lb_buf, lu_buf::lb_len, lustre_hsm2buf(), mdt_object_child(), mo_xattr_set(), mdt_thread_info::mti_buf, mdt_thread_info::mti_env, mdt_thread_info::mti_xattr_buf, RETURN, and XATTR_NAME_HSM.
Referenced by hsm_cdt_request_completed(), hsm_swap_layouts(), mdt_add_dirty_flag(), mdt_hsm_add_hal(), and mdt_hsm_state_set().
int mdt_hsm_cdt_control_seq_show (struct seq_file * m, void * data)
Definition at line 1968 of file mdt_coordinator.c.
References CDT_DISABLE, CDT_INIT, CDT_RUNNING, coordinator::cdt_state, CDT_STOPPED, CDT_STOPPING, ENTRY, mdt_device::mdt_coordinator, mdt_dev(), obd_device::obd_lu_dev, and RETURN.
ssize_t mdt_hsm_cdt_control_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off)
Definition at line 1900 of file mdt_coordinator.c.
References CDT_DISABLE, CDT_DISABLE_CMD, CDT_ENABLE_CMD, CDT_HELP_CMD, CDT_MAX_CMD_LEN, CDT_PURGE_CMD, CDT_RUNNING, coordinator::cdt_state, CDT_STOP_CMD, CDT_STOPPED, CDT_STOPPING, CERROR, ENTRY, hsm_cancel_all_actions(), mdt_device::mdt_coordinator, mdt_dev(), mdt_hsm_cdt_start(), mdt_hsm_cdt_wakeup(), mdt_obd_name(), obd_device::obd_lu_dev, RETURN, and usage.
int mdt_hsm_cdt_fini (struct mdt_device * mdt)
free a coordinator thread
Parameters:
mdt [IN] device
Definition at line 852 of file mdt_coordinator.c.
References coordinator::cdt_env, ENTRY, lu_env::le_ses, lu_context_exit(), lu_context_fini(), lu_env_fini(), mdt_device::mdt_coordinator, and RETURN.
Referenced by mdt_fini(), and mdt_init0().
int mdt_hsm_cdt_init (struct mdt_device * mdt)
initialize coordinator struct
Parameters:
mdt [IN] device
Return values:
0 success
-ve failure
Definition at line 795 of file mdt_coordinator.c.
References coordinator::cdt_active_req_timeout, coordinator::cdt_agent_lock, coordinator::cdt_agents, coordinator::cdt_default_archive_id, CDT_DEFAULT_POLICY, coordinator::cdt_env, coordinator::cdt_grace_delay, coordinator::cdt_llog_lock, coordinator::cdt_loop_period, coordinator::cdt_max_requests, coordinator::cdt_policy, coordinator::cdt_request_lock, coordinator::cdt_requests, coordinator::cdt_restore_hdl, coordinator::cdt_restore_lock, coordinator::cdt_session, coordinator::cdt_state, CDT_STOPPED, coordinator::cdt_thread, ENTRY, hsm_init_ucred(), INIT_LIST_HEAD, LASSERT, LCT_MD_THREAD, LCT_SERVER_SESSION, lu_env::le_ctx, lu_env::le_ses, lu_context_enter(), lu_context_init(), lu_context_key_get(), lu_env_fini(), lu_env_init(), mdt_device::mdt_coordinator, mdt_thread_key, mdt_ucred(), mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, RETURN, and ptlrpc_thread::t_ctl_waitq.
Referenced by mdt_init0().
int mdt_hsm_cdt_start (struct mdt_device * mdt)
start a coordinator thread
Parameters:
mdt [IN] device
Return values:
0 success
-ve failure
Definition at line 871 of file mdt_coordinator.c.
References CDEBUG, coordinator::cdt_compound_id, CDT_DEFAULT_POLICY, coordinator::cdt_env, coordinator::cdt_group_request_mask, CDT_INIT, coordinator::cdt_last_cookie, coordinator::cdt_other_request_mask, coordinator::cdt_policy, CDT_POLICY_LAST, CDT_POLICY_SHIFT_COUNT, coordinator::cdt_request_count, CDT_RUNNING, coordinator::cdt_state, CDT_STOPPED, coordinator::cdt_thread, coordinator::cdt_user_request_mask, CERROR, cfs_time_current_sec(), CLASSERT, D_HSM, dump_requests(), ENTRY, HSMA_RESTORE, lu_env::le_ctx, lu_context_key_get(), mdt_coordinator(), mdt_device::mdt_coordinator, mdt_hsm_pending_restore(), mdt_obd_name(), mdt_device::mdt_opts, mdt_thread_key, mdt_device::mo_coordinator, RETURN, SVC_RUNNING, ptlrpc_thread::t_ctl_waitq, and ptlrpc_thread::t_flags.
Referenced by mdt_hsm_cdt_control_seq_write().
int mdt_hsm_cdt_stop (struct mdt_device * mdt)
stop a coordinator thread
Parameters:
mdt [IN] device
Definition at line 941 of file mdt_coordinator.c.
References cdt_agent_req::car_request_list, coordinator::cdt_agent_lock, coordinator::cdt_agents, coordinator::cdt_env, coordinator::cdt_request_lock, coordinator::cdt_requests, coordinator::cdt_restore_hdl, coordinator::cdt_restore_lock, coordinator::cdt_state, CDT_STOPPED, CDT_STOPPING, coordinator::cdt_thread, CERROR, cdt_restore_handle::crh_fid, cdt_restore_handle::crh_lh, cdt_restore_handle::crh_list, ENTRY, hsm_agent::ha_list, lu_env::le_ctx, list_del(), list_for_each_entry_safe, lu_context_key_get(), mdt_cdt_free_request(), mdt_device::mdt_coordinator, mdt_hsm_cdt_kmem, mdt_obd_name(), mdt_object_find(), mdt_object_unlock_put(), mdt_device::mdt_opts, mdt_thread_key, mdt_device::mo_coordinator, OBD_FREE_PTR, OBD_SLAB_FREE_PTR, RETURN, SVC_STOPPED, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, and ptlrpc_thread::t_flags.
Referenced by mdt_coordinator(), and mdt_fini().
int mdt_hsm_cdt_wakeup (struct mdt_device * mdt)
wake up coordinator thread
Parameters:
mdt [IN] device
Return values:
0 success
-ve failure
Definition at line 774 of file mdt_coordinator.c.
References coordinator::cdt_state, CDT_STOPPED, coordinator::cdt_thread, ENTRY, mdt_device::mdt_coordinator, RETURN, SVC_EVENT, ptlrpc_thread::t_ctl_waitq, and ptlrpc_thread::t_flags.
Referenced by mdt_hsm_add_actions(), mdt_hsm_cdt_control_seq_write(), and mdt_hsm_update_request_state().
int mdt_hsm_coordinator_update (struct mdt_thread_info * mti, struct hsm_progress_kernel * pgs)
update status of a request
Parameters:
mti [IN]
pgs [IN] progress of the copy tool
Return values:
0 success
-ve failure
Definition at line 521 of file mdt_hsm_cdt_agent.c.
References ENTRY, mdt_hsm_update_request_state(), and RETURN.
Referenced by mdt_hsm_progress().
int mdt_hsm_ct_register (struct tgt_session_info * tsi)
Definition at line 146 of file mdt_hsm.c.
References ENTRY, err_serious(), obd_export::exp_client_uuid, GOTO, mdt_hsm_agent_register_mask(), mdt_hsm_is_admin(), mdt_thread_info_fini(), req_capsule_client_get(), RETURN, RMF_MDS_HSM_ARCHIVE, tsi2mdt_info(), tgt_session_info::tsi_exp, and tgt_session_info::tsi_pill.
int mdt_hsm_ct_unregister (struct tgt_session_info * tsi)
Definition at line 169 of file mdt_hsm.c.
References ENTRY, obd_export::exp_client_uuid, GOTO, mdt_hsm_agent_unregister(), mdt_hsm_is_admin(), mdt_thread_info_fini(), RETURN, tsi2mdt_info(), tgt_session_info::tsi_exp, and tgt_session_info::tsi_mdt_body.
void mdt_hsm_dump_hal (int level, const char * prefix, struct hsm_action_list * hal)
Definition at line 98 of file mdt_coordinator.c.
References buf, CDEBUG, DFID, hsm_action_item::hai_action, hsm_action_item::hai_cookie, hsm_action_item::hai_dfid, hai_dump_data_field(), hsm_action_item::hai_extent, hsm_action_item::hai_fid, hai_first(), hsm_action_item::hai_gid, hsm_action_item::hai_len, hai_next(), hsm_action_list::hal_archive_id, hsm_action_list::hal_compound_id, hsm_action_list::hal_count, hsm_action_list::hal_flags, hsm_action_list::hal_version, hsm_copytool_action2name(), hsm_extent::length, LPX64, hsm_extent::offset, and PFID.
int mdt_hsm_find_best_agent (struct coordinator * cdt, __u32 archive, struct obd_uuid * uuid)
find the best agent
Parameters:
cdt [IN] coordinator
archive [IN] archive number
uuid [OUT] agent who can serve archive
Return values:
0 success
-ve failure
Definition at line 277 of file mdt_hsm_cdt_agent.c.
References coordinator::cdt_agent_lock, coordinator::cdt_agents, ENTRY, hsm_agent::ha_archive_cnt, hsm_agent::ha_archive_id, hsm_agent::ha_list, hsm_agent::ha_requests, hsm_agent::ha_uuid, list_for_each_entry, and RETURN.
Referenced by mdt_hsm_agent_send().
int mdt_hsm_get_actions (struct mdt_thread_info * mti, struct hsm_action_list * hal)
get registered action on a FID list
Parameters:
mti [IN]
hal [IN/OUT] requests
Return values:
0 success
-ve failure
Definition at line 549 of file mdt_hsm_cdt_client.c.
References __u64, ENTRY, fid_is_sane(), hai_first(), hai_next(), hsm_action_list::hal_count, hsm_find_compatible(), HSMA_NONE, mdt_cdt_find_request(), mdt_cdt_get_work_done(), mdt_cdt_put_request(), mdt_device::mdt_coordinator, mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, and RETURN.
Referenced by mdt_hsm_action().
struct mdt_object* mdt_hsm_get_md_hsm (struct mdt_thread_info * mti, const struct lu_fid * fid, struct md_hsm * hsm) [read]
get obj and HSM attributes on a fid
Parameters:
mti [IN] context
fid [IN] object fid
hsm [OUT] HSM meta data
Return values:
obj or error (-ENOENT if not found)
Definition at line 60 of file mdt_coordinator.c.
References ENTRY, md_attr::ma_hsm, MA_HSM, md_attr::ma_need, md_attr::ma_valid, mdt_attr_get_complex(), mdt_object_exists(), mdt_object_find(), mdt_object_put(), mdt_thread_info::mti_attr, mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, and RETURN.
Referenced by hsm_cdt_request_completed(), mdt_hsm_add_actions(), mdt_hsm_add_hal(), and mdt_hsm_agent_send().
int mdt_hsm_get_running (struct mdt_thread_info * mti, struct hsm_action_list * hal)
get running action on a FID list or from cookie
Parameters:
mti [IN]
hal [IN/OUT] requests
Return values:
0 success
-ve failure
Definition at line 482 of file mdt_hsm_cdt_client.c.
References cdt_agent_req::car_hai, ENTRY, fid_is_sane(), hai_first(), hai_next(), hsm_action_list::hal_count, HSMA_NONE, mdt_cdt_find_request(), mdt_cdt_put_request(), mdt_device::mdt_coordinator, mdt_thread_info::mti_mdt, and RETURN.
bool mdt_hsm_is_action_compat (const struct hsm_action_item * hai, const int hal_an, const __u64 rq_flags, const struct md_hsm * hsm)
check if a request is compatible with file status
Parameters:
hai [IN] request description
hal_an [IN] request archive number (not used)
rq_flags [IN] request flags
hsm [IN] file HSM metadata
Return values:
boolean
Definition at line 1648 of file mdt_coordinator.c.
References CDEBUG, D_HSM, DFID, ENTRY, hsm_action_item::hai_action, hsm_action_item::hai_extent, hsm_action_item::hai_fid, HS_ARCHIVED, HS_DIRTY, HS_EXISTS, HS_LOST, HS_NOARCHIVE, HS_RELEASED, hsm_copytool_action2name(), HSMA_ARCHIVE, HSMA_CANCEL, HSMA_REMOVE, HSMA_RESTORE, hsm_extent::length, LPX64, md_hsm::mh_flags, hsm_extent::offset, PFID, and RETURN.
Referenced by mdt_hsm_add_actions(), and mdt_hsm_agent_send().
int mdt_hsm_progress (struct tgt_session_info * tsi)
Extract information coming from a copytool and asks coordinator to update a request status depending on the update content.
Copytools could use this to report failure in their process.
This is HSM_PROGRESS RPC handler.
Definition at line 108 of file mdt_hsm.c.
References CDEBUG, D_HSM, DFID, ENTRY, err_serious(), GOTO, HP_FLAG_COMPLETED, HP_FLAG_RETRY, hsm_progress_kernel::hpk_cookie, hsm_progress_kernel::hpk_errval, hsm_progress_kernel::hpk_extent, hsm_progress_kernel::hpk_fid, hsm_progress_kernel::hpk_flags, hsm_extent::length, LPU64, LPX64, lustre_errno_ntoh(), mdt_hsm_coordinator_update(), mdt_hsm_is_admin(), mdt_thread_info_fini(), PFID, req_capsule_client_get(), RETURN, RMF_MDS_HSM_PROGRESS, tsi2mdt_info(), tgt_session_info::tsi_mdt_body, and tgt_session_info::tsi_pill.
int mdt_hsm_request (struct tgt_session_info * tsi)
Process the HSM actions described in a struct hsm_user_request.
The action described in hur will be send to coordinator to be saved and processed later or either handled directly if hur.hur_action is HUA_RELEASE.
This is MDS_HSM_REQUEST RPC handler.
Definition at line 471 of file mdt_hsm.c.
References __u64, CERROR, cfs_size_round(), ENTRY, GOTO, hai_first(), hai_next(), hsm_action_list::hal_archive_id, hsm_action_list::hal_count, hsm_action_list::hal_flags, hsm_action_list::hal_fsname, hal_size(), HAL_VERSION, hsm_action_list::hal_version, hsm_request::hr_action, hsm_request::hr_archive_id, hsm_request::hr_data_len, hsm_request::hr_flags, hsm_request::hr_itemcount, HSMA_ARCHIVE, HSMA_CANCEL, HSMA_NONE, HSMA_REMOVE, HSMA_RESTORE, HUA_ARCHIVE, HUA_CANCEL, HUA_RELEASE, HUA_REMOVE, HUA_RESTORE, hsm_user_item::hui_extent, hsm_user_item::hui_fid, mdt_exit_ucred(), mdt_hsm_add_actions(), MDT_HSM_ALLOC, MDT_HSM_FREE, mdt_init_ucred(), mdt_obd_name(), mdt_thread_info_fini(), mdt_thread_info::mti_body, mdt_thread_info::mti_mdt, MTI_NAME_MAXLEN, obd_uuid2fsname(), RCL_CLIENT, req_capsule_client_get(), req_capsule_get_size(), RETURN, RMF_GENERIC_DATA, RMF_MDS_HSM_REQUEST, RMF_MDS_HSM_USER_ITEM, tsi2mdt_info(), tgt_session_info::tsi_mdt_body, and tgt_session_info::tsi_pill.
struct cdt_restore_handle* mdt_hsm_restore_hdl_find (struct coordinator * cdt, const struct lu_fid * fid) [read]
lookup a restore handle by FID caller needs to hold cdt_restore_lock
Parameters:
cdt [IN] coordinator
fid [IN] FID
Return values:
cdt_restore_handle found
NULL not found
Definition at line 623 of file mdt_coordinator.c.
References coordinator::cdt_restore_hdl, cdt_restore_handle::crh_fid, cdt_restore_handle::crh_list, ENTRY, list_for_each_entry, lu_fid_eq(), and RETURN.
Referenced by hsm_cdt_request_completed(), and mdt_hsm_agent_send().
bool mdt_hsm_restore_is_running (struct mdt_thread_info * mti, const struct lu_fid * fid)
check if a restore is running on a FID this is redundant with mdt_hsm_coordinator_get_running() but as it can be called frequently when getting attr we make an optimized/simpler version only for a FID
Parameters:
mti [IN]
fid [IN] file FID
Return values:
boolean
Definition at line 519 of file mdt_hsm_cdt_client.c.
References coordinator::cdt_restore_hdl, coordinator::cdt_restore_lock, cdt_restore_handle::crh_fid, cdt_restore_handle::crh_list, ENTRY, fid_is_sane(), list_for_each_entry, lu_fid_eq(), mdt_device::mdt_coordinator, mdt_thread_info::mti_mdt, and RETURN.
Referenced by mdt_getattr_internal().
int mdt_hsm_state_get (struct tgt_session_info * tsi)
Retrieve the current HSM flags, archive id and undergoing HSM requests for the fid provided in RPC body.
Current requests are read from coordinator states.
This is MDS_HSM_STATE_GET RPC handler.
Definition at line 197 of file mdt_hsm.c.
References ENTRY, err_serious(), EXIT, GOTO, hsm_user_state::hus_archive_id, hsm_user_state::hus_states, LCK_PR, md_attr::ma_hsm, MA_HSM, md_attr::ma_need, md_attr::ma_valid, MDS_INODELOCK_LOOKUP, mdt_attr_get_complex(), mdt_exit_ucred(), mdt_init_ucred(), MDT_LH_CHILD, mdt_lock_reg_init(), mdt_object_lock(), mdt_object_unlock(), mdt_thread_info_fini(), md_hsm::mh_arch_id, md_hsm::mh_flags, mdt_thread_info::mti_attr, mdt_thread_info::mti_body, mdt_thread_info::mti_lh, mdt_thread_info::mti_object, req_capsule_server_get(), RMF_HSM_USER_STATE, tsi2mdt_info(), and tgt_session_info::tsi_pill.
int mdt_hsm_state_set (struct tgt_session_info * tsi)
Change HSM state and archive number of a file.
Archive number is changed iif the value is not 0. The new flagset that will be computed should result in a coherent state. This function checks that flags are compatible.
This is MDS_HSM_STATE_SET RPC handler.
Definition at line 254 of file mdt_hsm.c.
References __u64, CDEBUG, CFS_CAP_SYS_ADMIN, D_HSM, DFID, ENTRY, err_serious(), EXIT, GOTO, HS_ARCHIVED, HS_DIRTY, HS_EXISTS, HS_LOST, HS_RELEASED, HSM_FLAGS_MASK, HSM_USER_MASK, hsm_state_set::hss_archive_id, HSS_ARCHIVE_ID, HSS_CLEARMASK, hsm_state_set::hss_clearmask, HSS_SETMASK, hsm_state_set::hss_setmask, hsm_state_set::hss_valid, LCK_PW, LL_HSM_MAX_ARCHIVE, LPX64, md_attr::ma_hsm, MA_HSM, md_attr::ma_need, md_attr::ma_valid, mdt_body::mbo_fid1, md_capable(), MDS_INODELOCK_LOOKUP, MDS_INODELOCK_XATTR, mdt_attr_get_complex(), mdt_exit_ucred(), mdt_hsm_attr_set(), mdt_init_ucred(), MDT_LH_CHILD, mdt_lock_reg_init(), mdt_object_lock(), mdt_object_unlock(), mdt_thread_info_fini(), mdt_ucred(), md_hsm::mh_arch_id, md_hsm::mh_flags, mdt_thread_info::mti_attr, mdt_thread_info::mti_body, mdt_thread_info::mti_lh, mdt_thread_info::mti_object, mdt_thread_info::mti_pill, PFID, req_capsule_client_get(), RMF_HSM_STATE_SET, and tsi2mdt_info().
int mdt_hsm_update_request_state (struct mdt_thread_info * mti, struct hsm_progress_kernel * pgs, const int update_record)
update status of a request
Parameters:
mti [IN] context
pgs [IN] progress of the copy tool
update_record [IN] update llog record
Return values:
0 success
-ve failure
Definition at line 1382 of file mdt_coordinator.c.
References agent_req_status2name(), cdt_agent_req::car_canceled, cdt_agent_req::car_hai, CDEBUG, coordinator::cdt_state, CDT_STOPPED, CERROR, D_HSM, DFID, ENTRY, GOTO, hsm_action_item::hai_action, hsm_action_item::hai_dfid, hsm_action_item::hai_fid, HP_FLAG_COMPLETED, hsm_progress_kernel::hpk_cookie, hsm_progress_kernel::hpk_errval, hsm_progress_kernel::hpk_fid, hsm_progress_kernel::hpk_flags, hsm_cdt_request_completed(), hsm_copytool_action2name(), hsm_init_ucred(), HSMA_ARCHIVE, HSMA_RESTORE, LPX64, lu_fid_eq(), mdt_agent_record_update(), mdt_cdt_put_request(), mdt_cdt_remove_request(), mdt_cdt_update_request(), mdt_device::mdt_coordinator, mdt_hsm_cdt_wakeup(), mdt_obd_name(), mdt_ucred(), mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, PFID, RETURN, and status.
Referenced by mdt_coordinator_cb(), and mdt_hsm_coordinator_update().
struct md_identity* mdt_identity_get (struct upcall_cache * , __u32) [read]
Definition at line 204 of file mdt_identity.c.
References __u64, upcall_cache_entry::identity, upcall_cache_entry::u, unlikely, and upcall_cache_get_entry().
Referenced by mdt_check_ucred(), mdt_handle_idmap(), new_init_ucred(), and old_init_ucred_common().
__u32 mdt_identity_get_perm (struct md_identity * , __u32 , lnet_nid_t)
Definition at line 248 of file mdt_identity.c.
References CFS_SETGRP_PERM, LASSERT, LNET_NID_ANY, md_identity::mi_nperms, md_identity::mi_perms, md_perm::mp_nid, and md_perm::mp_perm.
Referenced by allow_client_chgrp(), mdt_check_ucred(), mdt_getxattr(), mdt_reint_setxattr(), and new_init_ucred().
void mdt_identity_put (struct upcall_cache * , struct md_identity *)
Definition at line 220 of file mdt_identity.c.
References LASSERT, md_identity::mi_uc_entry, and upcall_cache_put_entry().
Referenced by mdt_check_ucred(), mdt_exit_ucred(), mdt_handle_idmap(), and new_init_ucred().
static struct ptlrpc_request* mdt_info_req (struct mdt_thread_info * info) [static, read]
Definition at line 506 of file mdt_internal.h.
References mdt_thread_info::mti_pill, and req_capsule::rc_req.
Referenced by __mdt_init_ucred(), allow_client_chgrp(), mdt_body_reverse_idmap(), mdt_check_resent(), mdt_check_resent_lock(), mdt_check_ucred(), mdt_client_compatibility(), mdt_empty_transno(), mdt_enoent_version_save(), mdt_finish_open(), mdt_fix_attr_ucred(), mdt_fix_lov_magic(), mdt_getattr(), mdt_getattr_internal(), mdt_getattr_name_lock(), mdt_getxattr(), mdt_getxattr_all(), mdt_getxattr_pack_reply(), mdt_init_ucred_reint(), mdt_intent_fixup_resent(), mdt_intent_getxattr(), mdt_intent_lock_replace(), mdt_intent_opc(), mdt_intent_reint(), mdt_lookup_version_check(), mdt_md_create(), mdt_mfd_open(), mdt_object_open_lock(), mdt_object_open_unlock(), mdt_open_unpack(), mdt_reconstruct_create(), mdt_reconstruct_generic(), mdt_reconstruct_open(), mdt_reconstruct_setattr(), mdt_reint_create(), mdt_reint_internal(), mdt_reint_link(), mdt_reint_migrate_internal(), mdt_reint_open(), mdt_reint_rec(), mdt_reint_rename_internal(), mdt_reint_rename_or_migrate(), mdt_reint_setattr(), mdt_reint_setxattr(), mdt_reint_unlink(), mdt_remote_permission(), mdt_rename_unpack(), mdt_rmtlsetfacl(), mdt_save_lock(), mdt_save_remote_lock(), mdt_unlink_unpack(), mdt_version_get_check(), mdt_version_get_check_save(), mdt_version_get_save(), new_init_ucred(), old_init_ucred_common(), and ucred_set_jobid().
int mdt_init_idmap (struct tgt_session_info * tsi)
Definition at line 75 of file mdt_idmap.c.
References CDEBUG, CERROR, D_SEC, ENTRY, exp_connect_rmtclient(), libcfs_nid2str(), lustre_idmap_init(), mdt_handle_idmap(), mdt_req2med(), mdt_export_data::med_idmap, mdt_export_data::med_idmap_mutex, lnet_process_id_t::nid, RETURN, ptlrpc_request::rq_export, ptlrpc_request::rq_peer, tgt_name(), tgt_ses_req(), and tgt_session_info::tsi_tgt.
Referenced by mdt_tgt_connect().
int mdt_init_ucred (struct mdt_thread_info * , struct mdt_body *)
Definition at line 596 of file mdt_lib.c.
References __mdt_init_ucred().
Referenced by mdt_getattr(), mdt_getxattr(), mdt_hsm_action(), mdt_hsm_is_admin(), mdt_hsm_request(), mdt_hsm_state_get(), and mdt_hsm_state_set().
int mdt_init_ucred_intent_getattr (struct mdt_thread_info * , struct mdt_body *)
Definition at line 606 of file mdt_lib.c.
References __mdt_init_ucred().
Referenced by mdt_getattr_name(), and mdt_intent_getattr().
int mdt_init_ucred_reint (struct mdt_thread_info *)
Definition at line 612 of file mdt_lib.c.
References LASSERT, mdt_exit_ucred(), mdt_info_req(), mdt_ucred(), new_init_ucred(), old_init_ucred_reint(), REC_INIT, ptlrpc_request::rq_auth_gss, ptlrpc_request::rq_auth_usr_mdt, lu_ucred::uc_valid, UCRED_NEW, and UCRED_OLD.
Referenced by mdt_close_unpack(), mdt_reint_internal(), and mdt_reint_setxattr().
static bool mdt_is_dne_client (struct obd_export * exp) [inline, static]
Definition at line 565 of file mdt_internal.h.
References exp_connect_flags(), and OBD_CONNECT_LVB_TYPE.
Referenced by mdt_getattr_internal(), mdt_reconstruct_create(), mdt_reconstruct_open(), mdt_reint_unlink(), and mdt_remote_permission().
static bool mdt_is_striped_client (struct obd_export * exp) [inline, static]
Definition at line 570 of file mdt_internal.h.
References exp_connect_flags(), and OBD_CONNECT_DIR_STRIPE.
Referenced by mdt_getattr_internal(), and mdt_remote_permission().
int mdt_links_read (struct mdt_thread_info * info, struct mdt_object * mdt_obj, struct linkea_data * ldata)
Definition at line 5420 of file mdt_handler.c.
References LASSERT, lu_buf::lb_buf, linkea_data::ld_buf, linkea_init(), lu_buf_check_and_alloc(), lu_buf_free(), mdt_object_child(), mdt_object_exists(), mo_xattr_get(), mdt_thread_info::mti_env, and XATTR_NAME_LINK.
Referenced by mdt_lock_objects_in_linkea(), and mdt_path_current().
void mdt_lock_handle_fini (struct mdt_lock_handle * lh)
Definition at line 2899 of file mdt_handler.c.
References LASSERT, lustre_handle_is_used(), mdt_lock_handle::mlh_pdo_lh, and mdt_lock_handle::mlh_reg_lh.
Referenced by mdt_thread_info_fini().
void mdt_lock_handle_init (struct mdt_lock_handle * lh)
Definition at line 2888 of file mdt_handler.c.
References lustre_handle::cookie, LCK_MINMODE, MDT_NUL_LOCK, mdt_lock_handle::mlh_pdo_lh, mdt_lock_handle::mlh_pdo_mode, mdt_lock_handle::mlh_reg_lh, mdt_lock_handle::mlh_reg_mode, mdt_lock_handle::mlh_rreg_lh, mdt_lock_handle::mlh_rreg_mode, and mdt_lock_handle::mlh_type.
Referenced by mdt_getattr_name_lock(), mdt_md_create(), mdt_object_open_lock(), mdt_reint_open(), and mdt_thread_info_init().
int mdt_lock_new_child (struct mdt_thread_info * info, struct mdt_object * o, struct mdt_lock_handle * child_lockh)
void mdt_lock_pdo_init (struct mdt_lock_handle * lh, enum ldlm_mode lock_mode, const struct lu_name * lname)
Definition at line 171 of file mdt_handler.c.
References LCK_MINMODE, lu_name::ln_name, lu_name::ln_namelen, lu_name_is_valid(), MDT_PDO_LOCK, mdt_lock_handle::mlh_pdo_hash, mdt_lock_handle::mlh_pdo_mode, mdt_lock_handle::mlh_reg_mode, mdt_lock_handle::mlh_rreg_mode, mdt_lock_handle::mlh_type, and unlikely.
Referenced by mdt_getattr_name_lock(), mdt_lock_objects_in_linkea(), mdt_md_create(), mdt_reint_link(), mdt_reint_migrate_internal(), mdt_reint_open(), mdt_reint_rename_internal(), and mdt_reint_unlink().
void mdt_lock_reg_init (struct mdt_lock_handle * lh, enum ldlm_mode lm)
Definition at line 163 of file mdt_handler.c.
References MDT_REG_LOCK, mdt_lock_handle::mlh_pdo_hash, mdt_lock_handle::mlh_reg_mode, mdt_lock_handle::mlh_rreg_mode, and mdt_lock_handle::mlh_type.
Referenced by hsm_restore_cb(), hsm_swap_layouts(), mdt_add_dirty_flag(), mdt_attr_set(), mdt_close_swap_layouts(), mdt_getattr_name_lock(), mdt_hsm_add_actions(), mdt_hsm_release(), mdt_hsm_state_get(), mdt_hsm_state_set(), mdt_intent_getxattr(), mdt_ioc_version_get(), mdt_md_create(), mdt_object_open_lock(), mdt_reint_link(), mdt_reint_migrate_internal(), mdt_reint_open(), mdt_reint_rename_internal(), mdt_reint_setattr(), mdt_reint_setxattr(), mdt_reint_unlink(), mdt_swap_layouts(), and mdt_unlock_slaves().
int mdt_lock_setup (struct mdt_thread_info * info, struct mdt_object * mo, struct mdt_lock_handle * lh)
static struct lu_site* mdt_lu_site (const struct mdt_device * mdt) [static, read]
Definition at line 548 of file mdt_internal.h.
References lu_device::ld_site, and mdt_device::mdt_lu_dev.
Referenced by mdt_init0(), mdt_site_stats_seq_show(), and mdt_stack_init().
static enum ldlm_mode mdt_mdl_mode2dlm_mode (mdl_mode_t mode) [inline, static]
Definition at line 996 of file mdt_internal.h.
References LASSERT, and mdt_dlm_lock_modes.
Referenced by mdt_lock_pdo_mode().
int mdt_mfd_close (struct mdt_thread_info * info, struct mdt_file_data * mfd)
Definition at line 1939 of file mdt_open.c.
References __u64, CDEBUG, D_HSM, D_INODE, DFID, ENTRY, FMODE_READ, FMODE_WRITE, LA_ATIME, lu_attr::la_valid, LASSERT, md_attr::ma_attr, md_attr::ma_attr_flags, MA_INODE, md_attr::ma_need, md_attr::ma_valid, MDS_CLOSE_LAYOUT_SWAP, MDS_DATA_MODIFIED, MDS_FMODE_EXEC, MDS_HSM_RELEASE, MDS_OPEN_LEASE, mdt_add_dirty_flag(), mdt_close_swap_layouts(), mdt_hsm_release(), mdt_mfd_free(), mdt_obd_name(), mdt_object_child(), mdt_object_fid(), mdt_object_put(), mdt_write_allow(), mdt_write_put(), MFD_CLOSED, mdt_file_data::mfd_mode, mdt_file_data::mfd_object, mo_attr_set(), mo_close(), mode, mdt_object::mot_lease_count, mdt_object::mot_open_count, mdt_thread_info::mti_attr, mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, PFID, and RETURN.
Referenced by mdt_close_internal(), mdt_export_cleanup(), and mdt_mfd_open().
void mdt_mfd_free (struct mdt_file_data * mfd)
Definition at line 106 of file mdt_open.c.
References LASSERT, list_empty(), mdt_file_data::mfd_handle, mdt_file_data::mfd_list, and OBD_FREE_RCU.
Referenced by mdt_mfd_close().
struct mdt_file_data* mdt_mfd_new (const struct mdt_export_data * med) [read]
Definition at line 62 of file mdt_open.c.
References class_handle_hash(), ENTRY, portals_handle::h_link, portals_handle::h_owner, INIT_LIST_HEAD, mdt_file_data::mfd_handle, mdt_file_data::mfd_list, OBD_ALLOC_PTR, and RETURN.
Referenced by mdt_mfd_open().
void mdt_mfd_set_mode (struct mdt_file_data * mfd, __u64 mode)
Definition at line 294 of file mdt_open.c.
References CDEBUG, D_HA, DFID, LASSERT, LPO64, mdt_object_fid(), mdt_file_data::mfd_mode, mdt_file_data::mfd_object, and PFID.
Referenced by mdt_mfd_open().
int mdt_name_unpack (struct req_capsule * pill, const struct req_msg_field * field, struct lu_name * ln, enum mdt_name_flags flags)
Definition at line 882 of file mdt_lib.c.
References lu_name::ln_name, lu_name::ln_namelen, lu_name_is_valid(), MNF_FIX_ANON, RCL_CLIENT, req_capsule_client_get(), and req_capsule_get_size().
Referenced by mdt_create_unpack(), mdt_getattr_name_lock(), mdt_link_unpack(), mdt_open_unpack(), mdt_rename_unpack(), mdt_setxattr_unpack(), and mdt_unlink_unpack().
static char* mdt_obd_name (struct mdt_device * mdt) [inline, static]
Definition at line 1048 of file mdt_internal.h.
References lu_device::ld_obd, mdt_device::mdt_lu_dev, and obd_device::obd_name.
Referenced by cdt_llog_process(), hsm_cancel_all_actions(), hsm_cdt_procfs_init(), hsm_cdt_request_completed(), hsm_swap_layouts(), lprocfs_identity_info_seq_write(), mdt_agent_record_update(), mdt_agent_record_update_cb(), mdt_connect_internal(), mdt_connect_to_next(), mdt_coordinator(), mdt_coordinator_cb(), mdt_cross_open(), mdt_device_commit_async(), mdt_empty_transno(), mdt_enable_cos(), mdt_fid2path(), mdt_fini(), mdt_getattr_internal(), mdt_getattr_name_lock(), mdt_hsm_action(), mdt_hsm_add_actions(), mdt_hsm_add_hal(), mdt_hsm_agent_send(), mdt_hsm_cdt_control_seq_write(), mdt_hsm_cdt_start(), mdt_hsm_cdt_stop(), mdt_hsm_policy_seq_write(), mdt_hsm_release(), mdt_hsm_request(), mdt_hsm_update_request_state(), mdt_identity_upcall_seq_write(), mdt_init0(), mdt_intent_layout(), mdt_iocontrol(), mdt_is_subdir(), mdt_lock_objects_in_linkea(), mdt_lvbo_fill(), mdt_mfd_close(), mdt_nosquash_nids_seq_write(), mdt_object_lock_internal(), mdt_object_sync(), mdt_open_by_fid_lock(), mdt_orphan_open(), mdt_postrecov(), mdt_procfs_init(), mdt_register_lwp_callback(), mdt_register_seq_exp(), mdt_reint_create(), mdt_reint_link(), mdt_reint_migrate_internal(), mdt_reint_open(), mdt_reint_rename_or_migrate(), mdt_reint_setxattr(), mdt_reint_unlink(), mdt_rename_counter_tally(), mdt_root_squash_seq_write(), mdt_seq_init(), mdt_seq_init_cli(), mdt_stack_fini(), and mdt_stack_pre_fini().
static struct mdt_object* mdt_obj (struct lu_object * o) [static, read]
Definition at line 755 of file mdt_internal.h.
References mdt_object::mot_obj.
Referenced by mdt_object_find(), mdt_object_free(), mdt_object_new(), mdt_object_print(), mdt_path_current(), mdt_readpage(), and tsi2mdt_info().
static struct dt_object* mdt_obj2dt (struct mdt_object * mo) [static, read]
Definition at line 760 of file mdt_internal.h.
References dt_device::dd_lu_dev, lu_device::ld_type, lu_object::lo_dev, lu_object::lo_header, lu2dt(), lu_object_locate(), mdt_device::mdt_bottom, mdt_dev(), and mdt_object::mot_obj.
Referenced by mdt_attr_set(), mdt_ioc_version_get(), mdt_md_create(), mdt_obj_version_get(), mdt_reint_link(), mdt_reint_open(), mdt_reint_rename_internal(), and mdt_reint_setxattr().
static struct md_object* mdt_object_child (struct mdt_object * o) [static, read]
Definition at line 500 of file mdt_internal.h.
References LASSERT, lu2md(), lu_object_next(), and mdt_object::mot_obj.
Referenced by hsm_cdt_request_completed(), hsm_swap_layouts(), mdt_attr_get_complex(), mdt_attr_get_eabuf_size(), mdt_attr_get_pfid(), mdt_attr_set(), mdt_big_xattr_get(), mdt_close_swap_layouts(), mdt_create_data(), mdt_cross_open(), mdt_getattr_internal(), mdt_getattr_name_lock(), mdt_getxattr(), mdt_getxattr_pack_reply(), mdt_hsm_attr_set(), mdt_hsm_release(), mdt_init_slaves(), mdt_is_subdir(), mdt_links_read(), mdt_lock_pdo_mode(), mdt_lock_slaves(), mdt_lookup_fileset(), mdt_lookup_version_check(), mdt_lvbo_fill(), mdt_md_create(), mdt_mfd_close(), mdt_mfd_open(), mdt_object_sync(), mdt_orphan_open(), mdt_pack_remote_perm(), mdt_path_current(), mdt_raw_lookup(), mdt_readpage(), mdt_reint_link(), mdt_reint_migrate_internal(), mdt_reint_open(), mdt_reint_rename_internal(), mdt_reint_setattr(), mdt_reint_setxattr(), mdt_reint_unlink(), mdt_remote_object_lock(), mdt_rename_counter_tally(), mdt_stripe_get(), mdt_swap_layouts(), and mdt_unlock_slaves().
static int mdt_object_exists (const struct mdt_object * o) [inline, static]
Definition at line 533 of file mdt_internal.h.
References lu_object_exists, and mdt_object::mot_obj.
Referenced by hsm_swap_layouts(), mdt_attr_get_complex(), mdt_body_unpack(), mdt_cross_open(), mdt_fid2path(), mdt_getattr_name_lock(), mdt_hsm_get_md_hsm(), mdt_intent_layout(), mdt_ioc_version_get(), mdt_is_subdir(), mdt_links_read(), mdt_lock_objects_in_linkea(), mdt_lvbo_fill(), mdt_md_create(), mdt_obj_version_get(), mdt_object_local_lock(), mdt_object_sync(), mdt_open_by_fid(), mdt_open_by_fid_lock(), mdt_path_current(), mdt_reconstruct_open(), mdt_reint_link(), mdt_reint_open(), mdt_reint_setattr(), and mdt_swap_layouts().
static struct lu_fid* mdt_object_fid (const struct mdt_object * o) [static, read]
Definition at line 543 of file mdt_internal.h.
References lu_object_fid(), and mdt_object::mot_obj.
Referenced by lprocfs_mdt_print_open_files(), mdt_add_dirty_flag(), mdt_attr_get_pfid(), mdt_check_resent_lock(), mdt_close_swap_layouts(), mdt_finish_open(), mdt_getattr(), mdt_getattr_internal(), mdt_getattr_name_lock(), mdt_handle_last_unlink(), mdt_hsm_release(), mdt_lock_slaves(), mdt_md_create(), mdt_mfd_close(), mdt_mfd_open(), mdt_mfd_set_mode(), mdt_obj_version_get(), mdt_object_local_lock(), mdt_object_lock_internal(), mdt_object_open_lock(), mdt_object_sync(), mdt_path(), mdt_path_current(), mdt_pdir_hash_lock(), mdt_reconstruct_create(), mdt_reconstruct_setattr(), mdt_reint_migrate_internal(), mdt_reint_open(), mdt_reint_rename_internal(), mdt_reint_setattr(), mdt_reint_unlink(), mdt_rename_counter_tally(), and mdt_sync().
struct mdt_object* mdt_object_find (const struct lu_env * , struct mdt_device * , const struct lu_fid *) [read]
Definition at line 2224 of file mdt_handler.c.
References CDEBUG, D_INFO, DFID, ENTRY, lu_object_find(), mdt_device::mdt_lu_dev, mdt_obj(), PFID, RETURN, and unlikely.
Referenced by hsm_swap_layouts(), mdt_body_unpack(), mdt_close_swap_layouts(), mdt_cross_open(), mdt_fid2path(), mdt_getattr_internal(), mdt_getattr_name_lock(), mdt_hsm_agent_send(), mdt_hsm_cdt_stop(), mdt_hsm_get_md_hsm(), mdt_intent_layout(), mdt_lock_objects_in_linkea(), mdt_lock_slaves(), mdt_lookup_fileset(), mdt_lookup_version_check(), mdt_lvbo_fill(), mdt_md_create(), mdt_object_find_check(), mdt_object_find_lock(), mdt_open_by_fid(), mdt_open_by_fid_lock(), mdt_orphan_open(), mdt_path_current(), mdt_reconstruct_create(), mdt_reconstruct_open(), mdt_reconstruct_setattr(), mdt_reint_link(), mdt_reint_migrate_internal(), mdt_reint_open(), mdt_reint_rename_internal(), mdt_reint_setattr(), mdt_reint_unlink(), mdt_rename_lock(), and mdt_swap_layouts().
struct mdt_object* mdt_object_find_lock (struct mdt_thread_info * , const struct lu_fid * , struct mdt_lock_handle * , __u64) [read]
Definition at line 2783 of file mdt_handler.c.
References mdt_object_find(), mdt_object_lock(), mdt_object_put(), mdt_thread_info::mti_env, and mdt_thread_info::mti_mdt.
Referenced by hsm_restore_cb(), hsm_swap_layouts(), mdt_hsm_add_actions(), mdt_ioc_version_get(), and mdt_reint_setxattr().
static void mdt_object_get (const struct lu_env * env, struct mdt_object * o) [inline, static]
Definition at line 517 of file mdt_internal.h.
References ENTRY, EXIT, lu_object_get(), and mdt_object::mot_obj.
Referenced by mdt_close_internal(), mdt_getattr_name_lock(), mdt_mfd_open(), and mdt_reint_rename_internal().
int mdt_object_lock (struct mdt_thread_info * info, struct mdt_object * mo, struct mdt_lock_handle * lh, __u64 ibits)
Definition at line 2619 of file mdt_handler.c.
References mdt_object_lock_internal().
Referenced by mdt_add_dirty_flag(), mdt_close_swap_layouts(), mdt_getattr_name_lock(), mdt_hsm_release(), mdt_hsm_state_get(), mdt_hsm_state_set(), mdt_intent_getxattr(), mdt_lock_objects_in_linkea(), mdt_md_create(), mdt_object_find_lock(), mdt_object_open_lock(), mdt_reint_open(), mdt_reint_setattr(), mdt_reint_unlink(), and mdt_swap_layouts().
int mdt_object_lock_try (struct mdt_thread_info * info, struct mdt_object * mo, struct mdt_lock_handle * lh, __u64 ibits)
Definition at line 2634 of file mdt_handler.c.
References mdt_object_lock_internal().
Referenced by mdt_getattr_name_lock(), and mdt_object_open_lock().
struct mdt_object* mdt_object_new (const struct lu_env * env, struct mdt_device * , const struct lu_fid *) [read]
Definition at line 2206 of file mdt_handler.c.
References CDEBUG, D_INFO, DFID, ENTRY, LOC_F_NEW, lu_object_conf::loc_flags, lu_object_find(), mdt_device::mdt_lu_dev, mdt_obj(), PFID, RETURN, and unlikely.
Referenced by mdt_md_create(), mdt_orphan_open(), and mdt_reint_open().
static void mdt_object_put (const struct lu_env * env, struct mdt_object * o) [inline, static]
Definition at line 525 of file mdt_internal.h.
References ENTRY, EXIT, lu_object_put(), and mdt_object::mot_obj.
Referenced by hsm_cdt_request_completed(), hsm_restore_cb(), hsm_swap_layouts(), mdt_body_unpack(), mdt_close_internal(), mdt_close_swap_layouts(), mdt_cross_open(), mdt_fid2path(), mdt_getattr_internal(), mdt_getattr_name_lock(), mdt_hsm_add_actions(), mdt_hsm_add_hal(), mdt_hsm_agent_send(), mdt_hsm_get_md_hsm(), mdt_hsm_release(), mdt_intent_layout(), mdt_lock_objects_in_linkea(), mdt_lock_slaves(), mdt_lookup_fileset(), mdt_lookup_version_check(), mdt_lvbo_fill(), mdt_md_create(), mdt_mfd_close(), mdt_object_find_check(), mdt_object_find_lock(), mdt_object_unlock_put(), mdt_open_by_fid(), mdt_open_by_fid_lock(), mdt_orphan_open(), mdt_path_current(), mdt_reconstruct_create(), mdt_reconstruct_open(), mdt_reconstruct_setattr(), mdt_reint_link(), mdt_reint_migrate_internal(), mdt_reint_open(), mdt_reint_rename_internal(), mdt_reint_setattr(), mdt_reint_unlink(), mdt_rename_lock(), mdt_swap_layouts(), and mdt_thread_info_fini().
static int mdt_object_remote (const struct mdt_object * o) [inline, static]
Definition at line 538 of file mdt_internal.h.
References lu_object_remote, and mdt_object::mot_obj.
Referenced by mdt_cross_open(), mdt_fid2path(), mdt_getattr_internal(), mdt_getattr_name_lock(), mdt_intent_layout(), mdt_ioc_version_get(), mdt_lock_objects_in_linkea(), mdt_lvbo_fill(), mdt_md_create(), mdt_obj_version_get(), mdt_object_local_lock(), mdt_object_lock_internal(), mdt_open_by_fid(), mdt_open_by_fid_lock(), mdt_path_current(), mdt_reconstruct_open(), mdt_reint_link(), mdt_reint_migrate_internal(), mdt_reint_open(), mdt_reint_rename_internal(), mdt_reint_setattr(), mdt_reint_unlink(), mdt_remote_object_lock(), and mdt_swap_layouts().
void mdt_object_unlock (struct mdt_thread_info * info, struct mdt_object * o, struct mdt_lock_handle * lh, int decref)
Unlock mdt object.
Immeditely release the regular lock and the PDO lock or save the lock in request and keep them referenced until client ACK or transaction commit.
Parameters:
info thread info object
o mdt object
lh mdt lock handle referencing regular and PDO locks
decref force immediate lock releasing
Definition at line 2771 of file mdt_handler.c.
References ENTRY, EXIT, mdt_save_lock(), mdt_save_remote_lock(), mdt_lock_handle::mlh_pdo_lh, mdt_lock_handle::mlh_pdo_mode, mdt_lock_handle::mlh_reg_lh, mdt_lock_handle::mlh_reg_mode, mdt_lock_handle::mlh_rreg_lh, and mdt_lock_handle::mlh_rreg_mode.
Referenced by hsm_cdt_request_completed(), mdt_add_dirty_flag(), mdt_attr_set(), mdt_close_swap_layouts(), mdt_getattr_name_lock(), mdt_hsm_agent_send(), mdt_hsm_release(), mdt_hsm_state_get(), mdt_hsm_state_set(), mdt_md_create(), mdt_object_local_lock(), mdt_object_lock_internal(), mdt_object_open_lock(), mdt_object_open_unlock(), mdt_object_unlock_put(), mdt_reint_link(), mdt_reint_migrate_internal(), mdt_reint_rename_internal(), mdt_reint_setattr(), mdt_reint_unlink(), mdt_swap_layouts(), and mdt_unlock_slaves().
void mdt_object_unlock_put (struct mdt_thread_info * , struct mdt_object * , struct mdt_lock_handle * , int decref)
Definition at line 2803 of file mdt_handler.c.
References mdt_object_put(), mdt_object_unlock(), and mdt_thread_info::mti_env.
Referenced by hsm_swap_layouts(), mdt_hsm_cdt_stop(), mdt_ioc_version_get(), mdt_lock_objects_in_linkea(), mdt_reint_open(), mdt_reint_setxattr(), mdt_unlock_list(), and mdt_unlock_slaves().
void mdt_pack_attr2body (struct mdt_thread_info * info, struct mdt_body * b, const struct lu_attr * attr, const struct lu_fid * fid)
Definition at line 501 of file mdt_handler.c.
References CDEBUG, D_INODE, D_VFSTRACE, DFID, lu_attr::la_atime, LA_ATIME, lu_attr::la_blocks, lu_attr::la_ctime, LA_CTIME, lu_attr::la_flags, LA_FLAGS, lu_attr::la_gid, LA_GID, LA_MODE, lu_attr::la_mode, lu_attr::la_mtime, LA_MTIME, lu_attr::la_nlink, LA_NLINK, lu_attr::la_rdev, lu_attr::la_size, LA_TYPE, lu_attr::la_uid, LA_UID, lu_attr::la_valid, LASSERT, LOV_PATTERN_F_RELEASED, LPX64, MA_INODE, md_attr::ma_lmm, MA_LOV, md_attr::ma_need, md_attr::ma_valid, mdt_body::mbo_atime, mdt_body::mbo_blocks, mdt_body::mbo_ctime, mdt_body::mbo_fid1, mdt_body::mbo_flags, mdt_body::mbo_gid, mdt_body::mbo_mode, mdt_body::mbo_mtime, mdt_body::mbo_nlink, mdt_body::mbo_rdev, mdt_body::mbo_size, mdt_body::mbo_uid, mdt_body::mbo_valid, mdt_body_reverse_idmap(), mdt_thread_info::mti_attr, mdt_thread_info::mti_exp, NODEMAP_FS_TO_CLIENT, NODEMAP_GID, nodemap_map_id(), NODEMAP_UID, OBD_MD_FLATIME, OBD_MD_FLBLOCKS, OBD_MD_FLCTIME, OBD_MD_FLFLAGS, OBD_MD_FLGID, OBD_MD_FLID, OBD_MD_FLMODE, OBD_MD_FLMTIME, OBD_MD_FLNLINK, OBD_MD_FLRDEV, OBD_MD_FLSIZE, OBD_MD_FLTYPE, OBD_MD_FLUID, PFID, and unlikely.
Referenced by mdt_finish_open(), mdt_getattr_internal(), mdt_handle_last_unlink(), mdt_md_create(), mdt_reconstruct_create(), mdt_reconstruct_setattr(), mdt_reint_setattr(), and mdt_sync().
int mdt_pack_remote_perm (struct mdt_thread_info * , struct mdt_object * , void *)
Definition at line 276 of file mdt_identity.c.
References ENTRY, exp_connect_rmtclient(), LASSERT, mdt_object_child(), mdt_ucred_check(), mo_permission(), mdt_thread_info::mti_env, mdt_thread_info::mti_exp, RETURN, mdt_remote_perm::rp_access_perm, mdt_remote_perm::rp_fsgid, mdt_remote_perm::rp_fsuid, mdt_remote_perm::rp_gid, mdt_remote_perm::rp_uid, lu_ucred::uc_o_fsgid, lu_ucred::uc_o_fsuid, lu_ucred::uc_o_gid, and lu_ucred::uc_o_uid.
Referenced by mdt_finish_open(), and mdt_getattr_internal().
void mdt_procfs_fini (struct mdt_device * mdt)
Definition at line 1010 of file mdt_lproc.c.
References hsm_cdt_procfs_fini(), lprocfs_free_md_stats(), lprocfs_free_obd_stats(), lprocfs_free_per_client_stats(), lprocfs_job_stats_fini(), lprocfs_obd_cleanup(), lprocfs_remove_proc_entry(), mdt2obd_dev(), and obd_device::obd_proc_exports_entry.
Referenced by mdt_fini(), and mdt_init0().
int mdt_procfs_init (struct mdt_device * mdt, const char * name)
Definition at line 966 of file mdt_lproc.c.
References CERROR, ENTRY, hsm_cdt_procfs_init(), LASSERT, lproc_mdt_attach_rename_seqstat(), LPROC_MDT_LAST, lprocfs_add_simple(), lprocfs_alloc_md_stats(), lprocfs_job_stats_init(), lprocfs_obd_setup(), mdt2obd_dev(), mdt_obd_name(), mdt_stats_counter_init(), obd_device::obd_md_stats, obd_device::obd_proc_entry, obd_device::obd_proc_exports_entry, obd_device::obd_vars, and RETURN.
Referenced by mdt_init0().
void mdt_reconstruct (struct mdt_thread_info * , struct mdt_lock_handle *)
Definition at line 338 of file mdt_recovery.c.
References ENTRY, EXIT, mdt_thread_info::mti_rr, reconstructors, and mdt_reint_record::rr_opcode.
Referenced by mdt_reint_internal().
void mdt_reconstruct_generic (struct mdt_thread_info * mti, struct mdt_lock_handle * lhc)
Definition at line 210 of file mdt_recovery.c.
References mdt_info_req(), mdt_req_from_lrd(), and mdt_thread_info::mti_reply_data.
Referenced by mdt_close().
void mdt_reconstruct_open (struct mdt_thread_info * , struct mdt_lock_handle *)
Definition at line 623 of file mdt_open.c.
References __u64, CDEBUG, D_INODE, DFID, DISP_OPEN_CREATE, ENTRY, ergo, EXIT, obd_export::exp_client_uuid, GOTO, LASSERT, LCONSOLE_WARN, ldlm_reply::lock_policy_res1, LPX64, lustre_msg_get_transno(), lustre_msg_set_status(), MA_HSM, MA_INODE, md_attr::ma_need, md_attr::ma_valid, mdt_body::mbo_fid1, mdt_body::mbo_valid, mdt_attr_get_complex(), mdt_export_evict(), mdt_finish_open(), mdt_get_disposition(), mdt_info_req(), mdt_is_dne_client(), mdt_object_exists(), mdt_object_find(), mdt_object_put(), mdt_object_remote(), mdt_prep_ma_buf_from_rep(), mdt_reint_open(), mdt_req_from_lrd(), mdt_set_disposition(), mdt_thread_info::mti_attr, mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, mdt_thread_info::mti_pill, mdt_thread_info::mti_reply_data, mdt_thread_info::mti_rr, mdt_thread_info::mti_spec, obd_export_nid2str(), OBD_MD_FLID, OBD_MD_MDS, obd_uuid2str(), PFID, req_capsule::rc_fmt, req_capsule_server_get(), RETURN_EXIT, RMF_DLM_REP, RMF_MDT_BODY, ptlrpc_request::rq_export, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_status, RQF_LDLM_INTENT_OPEN, mdt_reint_record::rr_fid1, mdt_reint_record::rr_fid2, md_op_spec::sp_cr_flags, and unlikely.
int mdt_reint_object_lock (struct mdt_thread_info * info, struct mdt_object * o, struct mdt_lock_handle * lh, __u64 ibits, bool cos_incompat)
Definition at line 2625 of file mdt_handler.c.
References LASSERT, LCK_EX, LCK_PW, mdt_object_lock_internal(), and mdt_lock_handle::mlh_reg_mode.
Referenced by mdt_attr_set(), mdt_lock_slaves(), mdt_md_create(), mdt_object_lock_save(), mdt_reint_link(), mdt_reint_migrate_internal(), mdt_reint_rename_internal(), and mdt_reint_unlink().
int mdt_reint_object_lock_try (struct mdt_thread_info * info, struct mdt_object * o, struct mdt_lock_handle * lh, __u64 ibits, bool cos_incompat)
Definition at line 2647 of file mdt_handler.c.
References LASSERT, LCK_EX, LCK_PW, mdt_object_lock_internal(), and mdt_lock_handle::mlh_reg_mode.
Referenced by mdt_lock_objects_in_linkea().
int mdt_reint_open (struct mdt_thread_info * info, struct mdt_lock_handle * lhc)
check version of child
Definition at line 1180 of file mdt_open.c.
References __u64, CDEBUG, CERROR, D_ERROR, D_INFO, D_INODE, DEBUG_REQ, DFID, DISP_IT_EXECD, DISP_LOOKUP_EXECD, DISP_LOOKUP_NEG, DISP_LOOKUP_POS, DISP_OPEN_CREATE, DISP_OPEN_LOCK, DNAME, dt_directory_features, ENTRY, ergo, err_serious(), EXIT, exp_connect_flags(), obd_export::exp_libclient, fid_is_md_operative(), fid_is_sane(), fid_le_to_cpu(), fid_zero(), FMODE_WRITE, GOTO, lu_attr::la_mode, LASSERT, LASSERTF, lu_buf::lb_buf, lu_buf::lb_len, LCK_PR, LCK_PW, le32_to_cpu, LMV_HASH_FLAG_MIGRATION, lmv_mds_md_v1::lmv_hash_type, lmv_mds_md_v1::lmv_stripe_fids, LPO64, LPROC_MDT_OPEN, lu_name_is_valid(), lustre_msg_get_flags(), lustre_msg_set_transno(), md_attr::ma_attr, MA_HSM, MA_INODE, md_attr::ma_need, md_attr::ma_valid, mdt_body::mbo_fid1, mdt_body::mbo_valid, mdo_create(), mdo_lookup(), mdo_unlink(), MDS_INODELOCK_LOOKUP, MDS_INODELOCK_UPDATE, MDS_OPEN_BY_FID, MDS_OPEN_CREAT, MDS_OPEN_HAS_EA, MDS_OPEN_HAS_OBJS, MDS_OPEN_JOIN_FILE, MDS_OPEN_LOCK, MDS_OPEN_VOLATILE, mdt_attr_get_complex(), mdt_check_resent_lock(), mdt_clear_disposition(), mdt_counter_incr(), mdt_cross_open(), mdt_dlm_mode2mdl_mode(), MDT_EREMOTE_OPEN, mdt_finish_open(), mdt_info_req(), MDT_LH_PARENT, mdt_lock_handle_init(), mdt_lock_pdo_init(), mdt_lock_reg_init(), mdt_obd_name(), mdt_obj2dt(), mdt_object_child(), mdt_object_exists(), mdt_object_fid(), mdt_object_find(), mdt_object_lock(), mdt_object_new(), mdt_object_open_lock(), mdt_object_open_unlock(), mdt_object_put(), mdt_object_remote(), mdt_object_unlock_put(), mdt_open_by_fid(), mdt_open_by_fid_lock(), mdt_prep_ma_buf_from_rep(), mdt_set_disposition(), mdt_version_get_check(), mdt_version_get_save(), mdt_lock_handle::mlh_pdo_mode, mo_xattr_get(), MSG_RESENT, mdt_thread_info::mti_attr, mdt_thread_info::mti_cross_ref, mdt_thread_info::mti_env, mdt_thread_info::mti_lh, mdt_thread_info::mti_mdt, mdt_thread_info::mti_pill, mdt_thread_info::mti_rr, mdt_thread_info::mti_spec, mdt_thread_info::mti_tmp_fid1, mdt_thread_info::mti_xattr_buf, OBD_CONNECT_RDONLY, OBD_FAIL_CHECK, OBD_FAIL_MDS_OPEN_PACK, OBD_FAIL_MDS_PAUSE_OPEN, OBD_FAIL_ONCE, OBD_FAIL_TIMEOUT_ORSET, OBD_MD_FLID, OBD_MD_MDS, obd_timeout, PFID, PNAME, req_capsule::rc_fmt, req_capsule_server_get(), req_is_replay(), RMF_DLM_REP, RMF_MDT_BODY, ptlrpc_request::rq_export, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_reqmsg, RQF_LDLM_INTENT_OPEN, mdt_reint_record::rr_fid1, mdt_reint_record::rr_fid2, mdt_reint_record::rr_name, md_op_spec::sp_cr_flags, md_op_spec::sp_cr_lookup, md_op_spec::sp_cr_mode, md_op_spec::sp_ea, md_op_spec::sp_feat, tgt_vbr_obj_set(), md_op_spec::u, unlikely, and XATTR_NAME_LMV.
Referenced by mdt_reconstruct_open().
int mdt_reint_rec (struct mdt_thread_info * , struct mdt_lock_handle *)
Definition at line 2235 of file mdt_reint.c.
References ARRAY_SIZE, ENTRY, lprocfs_counter_incr(), mdt_info_req(), mdt_reinter::mr_extra_opc, mdt_reinter::mr_handler, mdt_thread_info::mti_rr, PTLRPC_LAST_CNTR, ptlrpc_req2svc(), RETURN, and mdt_reint_record::rr_opcode.
Referenced by mdt_reint_internal().
int mdt_reint_setxattr (struct mdt_thread_info * info, struct mdt_lock_handle * lh)
Definition at line 363 of file mdt_xattr.c.
References __u64, buf, CDEBUG, CFS_CAP_SYS_ADMIN, CFS_RMTACL_PERM, cfs_time_current_sec(), CWARN, D_INFO, D_INODE, DFID, ENTRY, err_serious(), EXIT, exp_connect_flags(), exp_connect_rmtclient(), GOTO, LA_CTIME, lu_attr::la_ctime, lu_attr::la_flags, lu_attr::la_valid, LATF_SKIP, lu_buf::lb_buf, lu_buf::lb_len, LCK_EX, lu_name::ln_name, LPROC_MDT_SETXATTR, LPU64, LPX64, lu_ucred(), LU_XATTR_CREATE, LU_XATTR_REPLACE, LUSTRE_POSIX_ACL_MAX_SIZE, md_attr::ma_attr, md_attr::ma_attr_flags, md_capable(), MDS_INODELOCK_LOOKUP, MDS_INODELOCK_PERM, MDS_INODELOCK_UPDATE, MDS_INODELOCK_XATTR, MDS_PERM_BYPASS, mdt_device::mdt_bottom, mdt_counter_incr(), mdt_exit_ucred(), mdt_fail_write(), mdt_identity_get_perm(), mdt_info_req(), mdt_init_ucred_reint(), MDT_LH_PARENT, mdt_lock_reg_init(), mdt_obd_name(), mdt_obj2dt(), mdt_object_child(), mdt_object_find_lock(), mdt_object_unlock_put(), mdt_rmtlsetfacl(), mdt_ucred(), mdt_version_get_check_save(), mo_attr_set(), mo_xattr_del(), mo_xattr_set(), mdt_thread_info::mti_attr, mdt_thread_info::mti_buf, mdt_thread_info::mti_dlm_req, mdt_thread_info::mti_env, mdt_thread_info::mti_exp, mdt_thread_info::mti_lh, mdt_thread_info::mti_mdt, mdt_thread_info::mti_rr, lnet_process_id_t::nid, NODEMAP_CLIENT_TO_FS, nodemap_map_acl(), OBD_CONNECT_XATTR, OBD_FAIL_CHECK, OBD_FAIL_MDS_SETXATTR, OBD_FAIL_MDS_SETXATTR_WRITE, OBD_MD_FLCTIME, OBD_MD_FLRMTLSETFACL, OBD_MD_FLRMTRSETFACL, OBD_MD_FLXATTR, OBD_MD_FLXATTRRM, PFID, RETURN, ptlrpc_request::rq_export, ptlrpc_request::rq_peer, mdt_reint_record::rr_eadata, mdt_reint_record::rr_eadatalen, mdt_reint_record::rr_fid1, mdt_reint_record::rr_name, tgt_vbr_obj_set(), lu_ucred::uc_identity, unlikely, XATTR_NAME_ACL_ACCESS, XATTR_NAME_ACL_DEFAULT, XATTR_NAME_FID, XATTR_NAME_HSM, XATTR_NAME_LFSCK_NAMESPACE, XATTR_NAME_LINK, XATTR_NAME_LMA, XATTR_NAME_LMV, XATTR_NAME_LOV, XATTR_NAME_SOM, XATTR_NAME_VERSION, XATTR_TRUSTED_PREFIX, and XATTR_USER_PREFIX.
int mdt_reint_unpack (struct mdt_thread_info * info, __u32 op)
Definition at line 1464 of file mdt_lib.c.
References CERROR, ENTRY, mdt_reint_unpackers, mdt_thread_info::mti_rr, REINT_MAX, RETURN, and mdt_reint_record::rr_opcode.
Referenced by mdt_reint_internal().
int mdt_remote_blocking_ast (struct ldlm_lock * lock, struct ldlm_lock_desc * desc, void * data, int flag)
Definition at line 2366 of file mdt_handler.c.
References CDEBUG, D_INODE, ENTRY, LBUG, LCF_ASYNC, LDLM_CB_BLOCKING, LDLM_CB_CANCELING, ldlm_cli_cancel(), LDLM_DEBUG, ldlm_is_atomic_cb, ldlm_lock2handle(), RETURN, and tgt_discard_slc_lock().
Referenced by mdt_lock_slaves(), and mdt_remote_object_lock().
int mdt_remote_object_lock (struct mdt_thread_info * mti, struct mdt_object * o, const struct lu_fid * fid, struct lustre_handle * lh, enum ldlm_mode mode, __u64 ibits, bool nonblock)
Definition at line 2431 of file mdt_handler.c.
References ldlm_inodebits::bits, ldlm_enqueue_info::ei_cb_bl, ldlm_enqueue_info::ei_cb_cp, ldlm_enqueue_info::ei_enq_slave, ldlm_enqueue_info::ei_mode, ldlm_enqueue_info::ei_nonblock, ldlm_enqueue_info::ei_type, ENTRY, fid_build_reg_res_name(), ldlm_policy_data::l_inodebits, LASSERT, ldlm_completion_ast(), LDLM_IBITS, mdt_object_child(), mdt_object_remote(), mdt_remote_blocking_ast(), mo_object_lock(), mdt_thread_info::mti_einfo, mdt_thread_info::mti_env, mdt_thread_info::mti_policy, mdt_thread_info::mti_res_id, and RETURN.
Referenced by mdt_object_lock_internal(), mdt_reint_migrate_internal(), mdt_reint_rename_internal(), mdt_reint_unlink(), and mdt_rename_lock().
int mdt_remote_perm_reverse_idmap (struct ptlrpc_request * , struct mdt_remote_perm *)
void mdt_rename_counter_tally (struct mdt_thread_info * info, struct mdt_device * mdt, struct ptlrpc_request * req, struct mdt_object * src, struct mdt_object * tgt)
Definition at line 172 of file mdt_lproc.c.
References CERROR, DFID, rename_stats::hist, lu_attr::la_size, LPROC_MDT_CROSSDIR_RENAME, LPROC_MDT_SAMEDIR_RENAME, lprocfs_oh_tally_log2(), md_attr::ma_attr, MA_INODE, md_attr::ma_need, md_attr::ma_valid, mdt_counter_incr(), mdt_obd_name(), mdt_object_child(), mdt_object_fid(), mdt_device::mdt_rename_stats, mo_attr_get(), mdt_thread_info::mti_attr, mdt_thread_info::mti_env, PFID, RENAME_CROSSDIR_SRC_SIZE, RENAME_CROSSDIR_TGT_SIZE, and RENAME_SAMEDIR_SIZE.
Referenced by mdt_reint_rename_internal().
static struct mdt_export_data* mdt_req2med (struct ptlrpc_request * req) [static, read]
Definition at line 909 of file mdt_internal.h.
References ptlrpc_request::rq_export.
Referenced by mdt_body_reverse_idmap(), mdt_fix_attr_ucred(), mdt_getxattr(), mdt_getxattr_all(), mdt_handle_idmap(), mdt_init_idmap(), mdt_rmtlsetfacl(), and ptlrpc_user_desc_do_idmap().
__u64 mdt_req_from_lrd (struct ptlrpc_request * req, struct tg_reply_data * trd)
Definition at line 180 of file mdt_recovery.c.
References D_HA, D_RPCTRACE, DEBUG_REQ, LASSERT, LPD64, lsd_reply_data::lrd_data, lsd_reply_data::lrd_result, lsd_reply_data::lrd_transno, lustre_msg_set_status(), lustre_msg_set_transno(), lustre_msg_set_versions(), mdt_steal_ack_locks(), ptlrpc_request::rq_repmsg, ptlrpc_request::rq_status, ptlrpc_request::rq_transno, tg_reply_data::trd_pre_versions, and tg_reply_data::trd_reply.
Referenced by mdt_reconstruct_create(), mdt_reconstruct_generic(), mdt_reconstruct_open(), and mdt_reconstruct_setattr().
static char* mdt_req_get_jobid (struct ptlrpc_request * req) [inline, static]
Definition at line 1056 of file mdt_internal.h.
References exp_connect_flags(), lustre_msg_get_jobid(), OBD_CONNECT_JOBSTATS, ptlrpc_request::rq_export, and ptlrpc_request::rq_reqmsg.
Referenced by ucred_set_jobid().
static struct seq_server_site* mdt_seq_site (struct mdt_device * mdt) [static, read]
Definition at line 553 of file mdt_internal.h.
References mdt_device::mdt_seq_site.
Referenced by mdt_deregister_seq_exp(), mdt_fld_fini(), mdt_fld_init(), mdt_init0(), mdt_register_lwp_callback(), mdt_register_seq_exp(), mdt_rename_lock(), mdt_seq_fini(), mdt_seq_fini_cli(), mdt_seq_init(), and mdt_seq_init_cli().
void mdt_set_disposition (struct mdt_thread_info * info, struct ldlm_reply * rep, __u64 op_flag)
Definition at line 152 of file mdt_handler.c.
References ldlm_reply::lock_policy_res1, mdt_thread_info::mti_env, mdt_thread_info::mti_opdata, and tgt_opdata_set().
Referenced by mdt_finish_open(), mdt_getattr_name_lock(), mdt_intent_getattr(), mdt_intent_reint(), mdt_mfd_open(), mdt_open_by_fid(), mdt_open_by_fid_lock(), mdt_raw_lookup(), mdt_reconstruct_open(), and mdt_reint_open().
static bool mdt_slc_is_enabled (struct mdt_device * mdt) [inline, static]
Definition at line 982 of file mdt_internal.h.
References BLOCKING_SYNC_ON_CANCEL, lu_target::lut_sync_lock_cancel, and mdt_device::mdt_lut.
Referenced by mdt_blocking_ast(), mdt_md_create(), and mdt_save_lock().
void mdt_stats_counter_init (struct lprocfs_stats * stats)
Definition at line 944 of file mdt_lproc.c.
References LPROC_MDT_CLOSE, LPROC_MDT_CROSSDIR_RENAME, LPROC_MDT_GETATTR, LPROC_MDT_GETXATTR, LPROC_MDT_LINK, LPROC_MDT_MKDIR, LPROC_MDT_MKNOD, LPROC_MDT_OPEN, LPROC_MDT_RENAME, LPROC_MDT_RMDIR, LPROC_MDT_SAMEDIR_RENAME, LPROC_MDT_SETATTR, LPROC_MDT_SETXATTR, LPROC_MDT_STATFS, LPROC_MDT_SYNC, LPROC_MDT_UNLINK, and lprocfs_counter_init().
Referenced by mdt_export_stats_init(), and mdt_procfs_init().
int mdt_stripe_get (struct mdt_thread_info * info, struct mdt_object * o, struct md_attr * ma, const char * name)
Definition at line 697 of file mdt_handler.c.
References exp_connect_flags(), LASSERT, lu_buf::lb_buf, lu_buf::lb_len, le32_to_cpu, LOV_PATTERN_F_HOLE, md_attr::ma_lmm, md_attr::ma_lmm_size, MA_LMV, md_attr::ma_lmv, MA_LMV_DEF, md_attr::ma_lmv_size, MA_LOV, md_attr::ma_valid, mdt_big_xattr_get(), mdt_device::mdt_max_mdsize, mdt_object_child(), mo_xattr_get(), mdt_thread_info::mti_big_lmm, mdt_thread_info::mti_big_lmm_used, mdt_thread_info::mti_buf, mdt_thread_info::mti_env, mdt_thread_info::mti_exp, mdt_thread_info::mti_mdt, OBD_CONNECT_LFSCK, unlikely, XATTR_NAME_DEFAULT_LMV, XATTR_NAME_LMV, and XATTR_NAME_LOV.
Referenced by mdt_attr_get_complex(), mdt_getattr_internal(), and mdt_reint_migrate_internal().
static struct mdt_thread_info* mdt_th_info (const struct lu_env * env) [static, read]
Definition at line 436 of file mdt_internal.h.
References LASSERT, lu_context_key_get(), lu_env_refill(), and mdt_thread_key.
Referenced by mdt_readpage(), and tsi2mdt_info().
void mdt_thread_info_fini (struct mdt_thread_info * mti)
Definition at line 2949 of file mdt_handler.c.
References ARRAY_SIZE, lu_buf::lb_buf, lu_buf_free(), mdt_lock_handle_fini(), mdt_object_put(), mdt_thread_info::mti_big_buf, mdt_thread_info::mti_env, mdt_thread_info::mti_exp, mdt_thread_info::mti_lh, mdt_thread_info::mti_object, mdt_thread_info::mti_pill, and unlikely.
Referenced by mdt_close(), mdt_get_info(), mdt_get_root(), mdt_getattr(), mdt_getattr_name(), mdt_hsm_action(), mdt_hsm_ct_register(), mdt_hsm_ct_unregister(), mdt_hsm_progress(), mdt_hsm_request(), mdt_hsm_state_get(), mdt_hsm_state_set(), mdt_intent_policy(), mdt_reint(), mdt_statfs(), mdt_swap_layouts(), mdt_sync(), and mdt_tgt_getxattr().
void mdt_thread_info_init (struct ptlrpc_request * req, struct mdt_thread_info * mti)
Definition at line 2910 of file mdt_handler.c.
References ARRAY_SIZE, obd_export::exp_obd, LU_BUF_NULL, lustre_msg_get_transno(), mdt_dev(), mdt_lock_handle_init(), mdt_thread_info::mti_attr, mdt_thread_info::mti_big_buf, mdt_thread_info::mti_big_lmm_used, mdt_thread_info::mti_body, mdt_thread_info::mti_cross_ref, mdt_thread_info::mti_dlm_req, mdt_thread_info::mti_env, mdt_thread_info::mti_exp, mdt_thread_info::mti_has_trans, mdt_thread_info::mti_lh, mdt_thread_info::mti_mdt, mdt_thread_info::mti_object, mdt_thread_info::mti_opdata, mdt_thread_info::mti_pill, mdt_thread_info::mti_spec, mdt_thread_info::mti_transno, md_op_spec::no_create, obd_device::obd_lu_dev, ptlrpc_request::rq_export, ptlrpc_request::rq_pill, ptlrpc_request::rq_reqmsg, md_op_spec::sp_ea, md_op_spec::sp_migrate_close, md_op_spec::sp_permitted, md_op_spec::sp_rm_entry, and md_op_spec::u.
Referenced by tsi2mdt_info().
struct lu_ucred* mdt_ucred (const struct mdt_thread_info * info) [read]
Definition at line 6063 of file mdt_handler.c.
References lu_ucred(), and mdt_thread_info::mti_env.
Referenced by __mdt_init_ucred(), hsm_action_permission(), mdt_body_reverse_idmap(), mdt_check_ucred(), mdt_create_unpack(), mdt_ctxt_add_dirty_flag(), mdt_exit_ucred(), mdt_getxattr_all(), mdt_hsm_add_actions(), mdt_hsm_cdt_init(), mdt_hsm_is_admin(), mdt_hsm_state_set(), mdt_hsm_update_request_state(), mdt_init_ucred_reint(), mdt_link_unpack(), mdt_open_unpack(), mdt_reint_setxattr(), mdt_reint_unlink(), mdt_remote_permission_check(), mdt_rename_unpack(), mdt_rmtlsetfacl(), mdt_root_squash(), mdt_setattr_unpack_rec(), mdt_setxattr_unpack(), mdt_unlink_unpack(), new_init_ucred(), old_init_ucred(), old_init_ucred_common(), and old_init_ucred_reint().
struct lu_ucred* mdt_ucred_check (const struct mdt_thread_info * info) [read]
Definition at line 6068 of file mdt_handler.c.
References lu_ucred_check(), and mdt_thread_info::mti_env.
Referenced by mdt_fix_attr_ucred(), and mdt_pack_remote_perm().
int mdt_version_get_check (struct mdt_thread_info * , struct mdt_object * , int)
Get version from disk and check it, no save in reply.
Definition at line 162 of file mdt_reint.c.
References mdt_info_req(), mdt_obj_version_get(), mdt_version_check(), mdt_thread_info::mti_ver, and req_is_replay().
Referenced by mdt_object_find_check(), and mdt_reint_open().
int mdt_version_get_check_save (struct mdt_thread_info * , struct mdt_object * , int)
Get version from disk and check if recovery or just save.
Definition at line 176 of file mdt_reint.c.
References mdt_info_req(), mdt_obj_version_get(), mdt_version_check(), mdt_version_save(), mdt_thread_info::mti_ver, and req_is_replay().
Referenced by mdt_attr_set(), mdt_md_create(), mdt_reint_link(), mdt_reint_migrate_internal(), mdt_reint_setxattr(), and mdt_reint_unlink().
void mdt_version_get_save (struct mdt_thread_info * info, struct mdt_object * mto, int idx)
Get version from disk and save in reply buffer.
Versions are saved in reply only during normal operations not replays.
Definition at line 149 of file mdt_reint.c.
References mdt_info_req(), mdt_obj_version_get(), mdt_version_save(), mdt_thread_info::mti_ver, and req_is_replay().
Referenced by mdt_object_lock_save(), mdt_reint_open(), mdt_reint_rename_internal(), and mdt_reint_unlink().
int mdt_write_get (struct mdt_object * o)
Definition at line 151 of file mdt_open.c.
References ENTRY, mdt_object::mot_write_count, mdt_object::mot_write_lock, and RETURN.
Referenced by mdt_mfd_open().
void mdt_write_put (struct mdt_object * o)
Definition at line 165 of file mdt_open.c.
References ENTRY, EXIT, mdt_object::mot_write_count, and mdt_object::mot_write_lock.
Referenced by mdt_mfd_close(), and mdt_mfd_open().
int mdt_write_read (struct mdt_object * o)
Definition at line 141 of file mdt_open.c.
References ENTRY, mdt_object::mot_write_count, mdt_object::mot_write_lock, and RETURN.
Referenced by mdt_reint_setattr().
int ptlrpc_user_desc_do_idmap (struct ptlrpc_request * , struct ptlrpc_user_desc *)
Definition at line 218 of file mdt_idmap.c.
References CDEBUG, CFS_IDMAP_NOTFOUND, D_SEC, exp_connect_rmtclient(), lustre_idmap_lookup_gid(), lustre_idmap_lookup_uid(), mdt_req2med(), mdt_export_data::med_idmap, ptlrpc_user_desc::pud_fsgid, ptlrpc_user_desc::pud_fsuid, ptlrpc_user_desc::pud_gid, ptlrpc_user_desc::pud_uid, and ptlrpc_request::rq_export.
Referenced by mdt_check_ucred(), and new_init_ucred().
void target_recovery_fini (struct obd_device * obd)
Referenced by mdt_fini(), mdt_init0(), and ofd_fini().
void target_recovery_init (struct lu_target * lut, svc_handler_t handler)
Referenced by mdt_prepare(), and ofd_prepare().
struct mdt_thread_info* tsi2mdt_info (struct tgt_session_info * tsi) [read]
Definition at line 2968 of file mdt_handler.c.
References LASSERT, lu_object_get(), mdt_obj(), mdt_th_info(), mdt_thread_info_init(), mdt_thread_info::mti_body, mdt_thread_info::mti_dlm_req, mdt_thread_info::mti_object, tgt_ses_req(), tgt_session_info::tsi_corpus, tgt_session_info::tsi_dlm_req, tgt_session_info::tsi_env, and tgt_session_info::tsi_mdt_body.
Referenced by mdt_close(), mdt_get_info(), mdt_get_root(), mdt_getattr(), mdt_getattr_name(), mdt_hsm_action(), mdt_hsm_ct_register(), mdt_hsm_ct_unregister(), mdt_hsm_progress(), mdt_hsm_request(), mdt_hsm_state_get(), mdt_hsm_state_set(), mdt_intent_policy(), mdt_reint(), mdt_statfs(), mdt_swap_layouts(), mdt_sync(), mdt_tgt_connect(), and mdt_tgt_getxattr().
Variable Documentation
enum ldlm_mode mdt_dlm_lock_modes[]
Definition at line 88 of file mdt_handler.c.
Referenced by mdt_mdl_mode2dlm_mode().
struct file_operations mdt_hsm_actions_fops
Definition at line 526 of file mdt_hsm_cdt_actions.c.
struct file_operations mdt_hsm_active_requests_fops
Definition at line 589 of file mdt_hsm_cdt_requests.c.
struct file_operations mdt_hsm_agent_fops
Definition at line 654 of file mdt_hsm_cdt_agent.c.
struct kmem_cache* mdt_hsm_car_kmem
Definition at line 111 of file mdt_handler.c.
Referenced by mdt_cdt_alloc_request(), and mdt_cdt_free_request().
struct kmem_cache* mdt_hsm_cdt_kmem
Definition at line 108 of file mdt_handler.c.
Referenced by hsm_cdt_request_completed(), hsm_restore_cb(), mdt_hsm_add_actions(), mdt_hsm_agent_send(), and mdt_hsm_cdt_stop().
struct upcall_cache_ops mdt_identity_upcall_cache_ops
Definition at line 229 of file mdt_identity.c.
Referenced by mdt_init0().
struct lu_device_operations mdt_lu_ops
Definition at line 4967 of file mdt_handler.c.
Referenced by mdt_init0().
struct ldlm_valblock_ops mdt_lvbo
Definition at line 199 of file mdt_lvb.c.
Referenced by mdt_init0().
mdl_mode_t mdt_mdl_lock_modes[]
Definition at line 77 of file mdt_handler.c.
Referenced by mdt_dlm_mode2mdl_mode().
struct lu_context_key mdt_thread_key [read]
Definition at line 893 of file mdt_internal.h.
Referenced by hsm_cancel_all_actions(), mdt_buf(), mdt_buf_const(), mdt_export_cleanup(), mdt_hsm_cdt_init(), mdt_hsm_cdt_start(), mdt_hsm_cdt_stop(), mdt_init0(), mdt_iocontrol(), mdt_lvbo_fill(), mdt_stack_fini(), mdt_stack_pre_fini(), mdt_th_info(), and mdt_txn_stop_cb().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.