Lustre: lustre/mdt/mdt_recovery.c File Reference
lustre/mdt/mdt_recovery.c File Reference
#include "mdt_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_MDS
Typedefs
typedef void(* mdt_reconstructor)(struct mdt_thread_info *mti, struct mdt_lock_handle *lhc)
Functions
struct lu_buf * mdt_buf (const struct lu_env *env, void *area, ssize_t len)
struct lu_buf * mdt_buf_const (const struct lu_env *env, const void *area, ssize_t len)
static int mdt_txn_stop_cb (const struct lu_env *env, struct thandle *txn, void *cookie)
int mdt_fs_setup (const struct lu_env *env, struct mdt_device *mdt, struct obd_device *obd, struct lustre_sb_info *lsi)
void mdt_fs_cleanup (const struct lu_env *env, struct mdt_device *mdt)
static void mdt_steal_ack_locks (struct ptlrpc_request *req)
__u64 mdt_req_from_lrd (struct ptlrpc_request *req, struct tg_reply_data *trd)
void mdt_reconstruct_generic (struct mdt_thread_info *mti, struct mdt_lock_handle *lhc)
static void mdt_fake_ma (struct md_attr *ma)
Generate fake attributes for a non-existing object.
static void mdt_reconstruct_create (struct mdt_thread_info *mti, struct mdt_lock_handle *lhc)
static void mdt_reconstruct_setattr (struct mdt_thread_info *mti, struct mdt_lock_handle *lhc)
void mdt_reconstruct (struct mdt_thread_info *mti, struct mdt_lock_handle *lhc)
Variables
struct lu_context_key mdt_thread_key
static mdt_reconstructor reconstructors [REINT_MAX]
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 44 of file mdt_recovery.c.
Typedef Documentation
typedef void(* mdt_reconstructor)(struct mdt_thread_info *mti, struct mdt_lock_handle *lhc)
Definition at line 325 of file mdt_recovery.c.
Function Documentation
struct lu_buf* mdt_buf (const struct lu_env * env, void * area, ssize_t len) [read]
Definition at line 48 of file mdt_recovery.c.
References buf, lu_buf::lb_buf, lu_buf::lb_len, lu_env::le_ctx, lu_context_key_get(), mdt_thread_key, and mdt_thread_info::mti_buf.
struct lu_buf* mdt_buf_const (const struct lu_env * env, const void * area, ssize_t len) [read]
Definition at line 60 of file mdt_recovery.c.
References buf, lu_buf::lb_buf, lu_buf::lb_len, lu_env::le_ctx, lu_context_key_get(), mdt_thread_key, and mdt_thread_info::mti_buf.
static void mdt_fake_ma (struct md_attr * ma) [static]
Generate fake attributes for a non-existing object.
While the client was waiting for the reply, the original transaction got committed and corresponding rep-ack lock got released, then another client was able to destroy the object. But we still need to send some attributes back. So we fake them and set nlink=0, so the client will be able to detect a non-existing object and drop it from the cache immediately.
Parameters:
[out] ma attributes to fill
Definition at line 231 of file mdt_recovery.c.
References lu_attr::la_mode, LA_NLINK, lu_attr::la_valid, md_attr::ma_attr, MA_INODE, and md_attr::ma_valid.
Referenced by mdt_reconstruct_create(), and mdt_reconstruct_setattr().
void mdt_fs_cleanup (const struct lu_env * env, struct mdt_device * mdt)
Definition at line 120 of file mdt_recovery.c.
References dt_txn_callback_del(), ENTRY, EXIT, mdt_device::mdt_bottom, and mdt_device::mdt_txn_cb.
Referenced by mdt_fini(), and mdt_init0().
int mdt_fs_setup (const struct lu_env * env, struct mdt_device * mdt, struct obd_device * obd, struct lustre_sb_info * lsi)
Definition at line 97 of file mdt_recovery.c.
References dt_txn_callback_add(), dt_txn_callback::dtc_cookie, dt_txn_callback::dtc_linkage, dt_txn_callback::dtc_tag, dt_txn_callback::dtc_txn_commit, dt_txn_callback::dtc_txn_start, dt_txn_callback::dtc_txn_stop, ENTRY, INIT_LIST_HEAD, LCT_MD_THREAD, mdt_device::mdt_bottom, mdt_device::mdt_txn_cb, mdt_txn_stop_cb(), OBD_FAIL_CHECK, OBD_FAIL_MDS_FS_SETUP, and RETURN.
Referenced by mdt_init0().
void mdt_reconstruct (struct mdt_thread_info * mti, struct mdt_lock_handle * lhc)
Definition at line 338 of file mdt_recovery.c.
References ENTRY, EXIT, mdt_thread_info::mti_rr, reconstructors, and mdt_reint_record::rr_opcode.
Referenced by mdt_reint_internal().
static void mdt_reconstruct_create (struct mdt_thread_info * mti, struct mdt_lock_handle * lhc) [static]
Definition at line 239 of file mdt_recovery.c.
References DFID, obd_export::exp_client_uuid, LCONSOLE_WARN, md_attr::ma_attr, MA_INODE, md_attr::ma_need, md_attr::ma_valid, mdt_body::mbo_valid, mdt_attr_get_complex(), mdt_export_evict(), mdt_fake_ma(), mdt_info_req(), mdt_is_dne_client(), mdt_object_fid(), mdt_object_find(), mdt_object_put(), mdt_pack_attr2body(), mdt_req_from_lrd(), mdt_thread_info::mti_attr, mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, mdt_thread_info::mti_pill, mdt_thread_info::mti_reply_data, mdt_thread_info::mti_rr, obd_export_nid2str(), OBD_MD_MDS, obd_uuid2str(), PFID, req_capsule_server_get(), RETURN_EXIT, RMF_MDT_BODY, ptlrpc_request::rq_export, ptlrpc_request::rq_status, and mdt_reint_record::rr_fid2.
void mdt_reconstruct_generic (struct mdt_thread_info * mti, struct mdt_lock_handle * lhc)
Definition at line 210 of file mdt_recovery.c.
References mdt_info_req(), mdt_req_from_lrd(), and mdt_thread_info::mti_reply_data.
Referenced by mdt_close().
static void mdt_reconstruct_setattr (struct mdt_thread_info * mti, struct mdt_lock_handle * lhc) [static]
Definition at line 286 of file mdt_recovery.c.
References DFID, obd_export::exp_client_uuid, LCONSOLE_WARN, md_attr::ma_attr, MA_INODE, md_attr::ma_need, md_attr::ma_valid, mdt_attr_get_complex(), mdt_export_evict(), mdt_fake_ma(), mdt_info_req(), mdt_object_fid(), mdt_object_find(), mdt_object_put(), mdt_pack_attr2body(), mdt_req_from_lrd(), mdt_thread_info::mti_attr, mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, mdt_thread_info::mti_pill, mdt_thread_info::mti_reply_data, mdt_thread_info::mti_rr, obd_export_nid2str(), obd_uuid2str(), PFID, req_capsule_server_get(), RETURN_EXIT, RMF_MDT_BODY, ptlrpc_request::rq_export, ptlrpc_request::rq_status, and mdt_reint_record::rr_fid1.
__u64 mdt_req_from_lrd (struct ptlrpc_request * req, struct tg_reply_data * trd)
Definition at line 180 of file mdt_recovery.c.
References D_HA, D_RPCTRACE, DEBUG_REQ, LASSERT, LPD64, lsd_reply_data::lrd_data, lsd_reply_data::lrd_result, lsd_reply_data::lrd_transno, lustre_msg_set_status(), lustre_msg_set_transno(), lustre_msg_set_versions(), mdt_steal_ack_locks(), ptlrpc_request::rq_repmsg, ptlrpc_request::rq_status, ptlrpc_request::rq_transno, tg_reply_data::trd_pre_versions, and tg_reply_data::trd_reply.
Referenced by mdt_reconstruct_create(), mdt_reconstruct_generic(), mdt_reconstruct_open(), and mdt_reconstruct_setattr().
static void mdt_steal_ack_locks (struct ptlrpc_request * req) [static]
Definition at line 130 of file mdt_recovery.c.
References ptlrpc_connection::c_peer, CDEBUG, CERROR, D_HA, DEBUG_REQ, obd_export::exp_connection, obd_export::exp_lock, obd_export::exp_outstanding_replies, libcfs_nid2str(), list_del_init(), list_entry, list_for_each, LPD64, LPU64, lustre_msg_get_opc(), lnet_process_id_t::nid, ptlrpc_save_lock(), ptlrpc_schedule_difficult_reply(), ptlrpc_request::rq_export, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_xid, ptlrpc_reply_state::rs_exp_list, ptlrpc_reply_state::rs_lock, ptlrpc_reply_state::rs_locks, ptlrpc_reply_state::rs_modes, ptlrpc_reply_state::rs_nlocks, ptlrpc_reply_state::rs_opc, ptlrpc_reply_state::rs_svcpt, ptlrpc_reply_state::rs_transno, and ptlrpc_reply_state::rs_xid.
Referenced by mdt_req_from_lrd().
static int mdt_txn_stop_cb (const struct lu_env * env, struct thandle * txn, void * cookie) [static]
Definition at line 82 of file mdt_recovery.c.
References CDEBUG, D_INFO, LASSERT, lu_env::le_ctx, lu_context_key_get(), mdt_thread_key, and mdt_thread_info::mti_has_trans.
Referenced by mdt_fs_setup().
Variable Documentation
struct lu_context_key mdt_thread_key
mdt_reconstructor reconstructors[REINT_MAX] [static]
Initial value:
 {
        [REINT_SETATTR]  = mdt_reconstruct_setattr,
        [REINT_CREATE]   = mdt_reconstruct_create,
        [REINT_LINK]     = mdt_reconstruct_generic,
        [REINT_UNLINK]   = mdt_reconstruct_generic,
        [REINT_RENAME]   = mdt_reconstruct_generic,
        [REINT_OPEN]     = mdt_reconstruct_open,
        [REINT_SETXATTR] = mdt_reconstruct_generic
}
Definition at line 328 of file mdt_recovery.c.
Referenced by mdt_reconstruct().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.