Lustre: lustre/mdt/mdt_handler.c File Reference
lustre/mdt/mdt_handler.c File Reference
#include <linux/module.h>
#include <dt_object.h>
#include <lustre_acl.h>
#include <lustre_export.h>
#include <lustre_ioctl.h>
#include <lustre_lfsck.h>
#include <lustre_log.h>
#include <lustre_net.h>
#include <lustre_nodemap.h>
#include <lustre_mds.h>
#include <lustre_param.h>
#include <lustre_quota.h>
#include <lustre_swab.h>
#include <obd.h>
#include <obd_support.h>
#include <llog_swab.h>
#include "mdt_internal.h"
Data Structures
struct mdt_it_flavor
Defines
#define DEBUG_SUBSYSTEM S_MDS
Enumerations
enum mdt_it_code {
MDT_IT_OPEN, MDT_IT_OCREAT, MDT_IT_CREATE, MDT_IT_GETATTR,
MDT_IT_READDIR, MDT_IT_LOOKUP, MDT_IT_UNLINK, MDT_IT_TRUNC,
MDT_IT_GETXATTR, MDT_IT_LAYOUT, MDT_IT_QUOTA, MDT_IT_NR
}
Functions
module_param (max_mod_rpcs_per_client, uint, 0644)
MODULE_PARM_DESC (max_mod_rpcs_per_client,"maximum number of modify RPCs in flight allowed per client")
static struct mdt_device * mdt_dev (struct lu_device *d)
static int mdt_unpack_req_pack_rep (struct mdt_thread_info *info, __u32 flags)
__u64 mdt_get_disposition (struct ldlm_reply *rep, __u64 op_flag)
void mdt_clear_disposition (struct mdt_thread_info *info, struct ldlm_reply *rep, __u64 op_flag)
void mdt_set_disposition (struct mdt_thread_info *info, struct ldlm_reply *rep, __u64 op_flag)
void mdt_lock_reg_init (struct mdt_lock_handle *lh, enum ldlm_mode lm)
void mdt_lock_pdo_init (struct mdt_lock_handle *lh, enum ldlm_mode lock_mode, const struct lu_name *lname)
static void mdt_lock_pdo_mode (struct mdt_thread_info *info, struct mdt_object *o, struct mdt_lock_handle *lh)
static int mdt_lookup_fileset (struct mdt_thread_info *info, const char *fileset, struct lu_fid *fid)
static int mdt_get_root (struct tgt_session_info *tsi)
static int mdt_statfs (struct tgt_session_info *tsi)
void mdt_pack_attr2body (struct mdt_thread_info *info, struct mdt_body *b, const struct lu_attr *attr, const struct lu_fid *fid)
static int mdt_body_has_lov (const struct lu_attr *la, const struct mdt_body *body)
void mdt_client_compatibility (struct mdt_thread_info *info)
static int mdt_attr_get_eabuf_size (struct mdt_thread_info *info, struct mdt_object *o)
int mdt_big_xattr_get (struct mdt_thread_info *info, struct mdt_object *o, const char *name)
int mdt_stripe_get (struct mdt_thread_info *info, struct mdt_object *o, struct md_attr *ma, const char *name)
static int mdt_attr_get_pfid (struct mdt_thread_info *info, struct mdt_object *o, struct lu_fid *pfid)
int mdt_attr_get_complex (struct mdt_thread_info *info, struct mdt_object *o, struct md_attr *ma)
static int mdt_getattr_internal (struct mdt_thread_info *info, struct mdt_object *o, int ma_need)
static int mdt_getattr (struct tgt_session_info *tsi)
static void mdt_swap_lov_flag (struct mdt_object *o1, struct mdt_object *o2)
Exchange MOF_LOV_CREATED flags between two objects after a layout swap.
static int mdt_swap_layouts (struct tgt_session_info *tsi)
static int mdt_raw_lookup (struct mdt_thread_info *info, struct mdt_object *parent, const struct lu_name *lname, struct ldlm_reply *ldlm_rep)
static int mdt_getattr_name_lock (struct mdt_thread_info *info, struct mdt_lock_handle *lhc, __u64 child_bits, struct ldlm_reply *ldlm_rep)
static int mdt_getattr_name (struct tgt_session_info *tsi)
static int mdt_iocontrol (unsigned int cmd, struct obd_export *exp, int len, void *karg, void __user *uarg)
static int mdt_set_info (struct tgt_session_info *tsi)
static int mdt_readpage (struct tgt_session_info *tsi)
static int mdt_reint_internal (struct mdt_thread_info *info, struct mdt_lock_handle *lhc, __u32 op)
static long mdt_reint_opcode (struct ptlrpc_request *req, const struct req_format **fmt)
static int mdt_reint (struct tgt_session_info *tsi)
static int mdt_device_sync (const struct lu_env *env, struct mdt_device *mdt)
static int mdt_object_sync (struct mdt_thread_info *info)
static int mdt_sync (struct tgt_session_info *tsi)
static int mdt_quotactl (struct tgt_session_info *tsi)
static int mdt_llog_ctxt_clone (const struct lu_env *env, struct mdt_device *mdt, int idx)
clone llog ctxt from child (mdd) This allows remote llog (replicator) access.
static int mdt_llog_ctxt_unclone (const struct lu_env *env, struct mdt_device *mdt, int idx)
static int mdt_sec_ctx_handle (struct tgt_session_info *tsi)
static int mdt_quota_dqacq (struct tgt_session_info *tsi)
struct mdt_object * mdt_object_new (const struct lu_env *env, struct mdt_device *d, const struct lu_fid *f)
struct mdt_object * mdt_object_find (const struct lu_env *env, struct mdt_device *d, const struct lu_fid *f)
static void mdt_device_commit_async (const struct lu_env *env, struct mdt_device *mdt)
Asyncronous commit for mdt device.
static void mdt_set_lock_sync (struct ldlm_lock *lock)
Mark the lock as "synchonous".
static int mdt_is_lock_sync (struct ldlm_lock *lock)
Check whehter the lock "synchonous" or not.
int mdt_blocking_ast (struct ldlm_lock *lock, struct ldlm_lock_desc *desc, void *data, int flag)
Blocking AST for mdt locks.
int mdt_remote_blocking_ast (struct ldlm_lock *lock, struct ldlm_lock_desc *desc, void *data, int flag)
int mdt_check_resent_lock (struct mdt_thread_info *info, struct mdt_object *mo, struct mdt_lock_handle *lhc)
int mdt_remote_object_lock (struct mdt_thread_info *mti, struct mdt_object *o, const struct lu_fid *fid, struct lustre_handle *lh, enum ldlm_mode mode, __u64 ibits, bool nonblock)
static int mdt_object_local_lock (struct mdt_thread_info *info, struct mdt_object *o, struct mdt_lock_handle *lh, __u64 ibits, bool nonblock, bool cos_incompat)
static int mdt_object_lock_internal (struct mdt_thread_info *info, struct mdt_object *o, struct mdt_lock_handle *lh, __u64 ibits, bool nonblock, bool cos_incompat)
int mdt_object_lock (struct mdt_thread_info *info, struct mdt_object *o, struct mdt_lock_handle *lh, __u64 ibits)
int mdt_reint_object_lock (struct mdt_thread_info *info, struct mdt_object *o, struct mdt_lock_handle *lh, __u64 ibits, bool cos_incompat)
int mdt_object_lock_try (struct mdt_thread_info *info, struct mdt_object *o, struct mdt_lock_handle *lh, __u64 ibits)
int mdt_reint_object_lock_try (struct mdt_thread_info *info, struct mdt_object *o, struct mdt_lock_handle *lh, __u64 ibits, bool cos_incompat)
static void mdt_save_lock (struct mdt_thread_info *info, struct lustre_handle *h, enum ldlm_mode mode, int decref)
Save a lock within request object.
static void mdt_save_remote_lock (struct mdt_thread_info *info, struct lustre_handle *h, enum ldlm_mode mode, int decref)
Save cross-MDT lock in uncommitted_slc_locks.
void mdt_object_unlock (struct mdt_thread_info *info, struct mdt_object *o, struct mdt_lock_handle *lh, int decref)
Unlock mdt object.
struct mdt_object * mdt_object_find_lock (struct mdt_thread_info *info, const struct lu_fid *f, struct mdt_lock_handle *lh, __u64 ibits)
void mdt_object_unlock_put (struct mdt_thread_info *info, struct mdt_object *o, struct mdt_lock_handle *lh, int decref)
static int mdt_body_unpack (struct mdt_thread_info *info, __u32 flags)
void mdt_lock_handle_init (struct mdt_lock_handle *lh)
void mdt_lock_handle_fini (struct mdt_lock_handle *lh)
void mdt_thread_info_init (struct ptlrpc_request *req, struct mdt_thread_info *info)
void mdt_thread_info_fini (struct mdt_thread_info *info)
struct mdt_thread_info * tsi2mdt_info (struct tgt_session_info *tsi)
static int mdt_tgt_connect (struct tgt_session_info *tsi)
static int mdt_intent_getattr (enum mdt_it_code opcode, struct mdt_thread_info *info, struct ldlm_lock **, __u64)
static int mdt_intent_getxattr (enum mdt_it_code opcode, struct mdt_thread_info *info, struct ldlm_lock **lockp, __u64 flags)
static int mdt_intent_layout (enum mdt_it_code opcode, struct mdt_thread_info *info, struct ldlm_lock **, __u64)
static int mdt_intent_reint (enum mdt_it_code opcode, struct mdt_thread_info *info, struct ldlm_lock **, __u64)
static int mdt_intent_lock_replace (struct mdt_thread_info *info, struct ldlm_lock **lockp, struct mdt_lock_handle *lh, __u64 flags, int result)
static void mdt_intent_fixup_resent (struct mdt_thread_info *info, struct ldlm_lock *new_lock, struct mdt_lock_handle *lh, __u64 flags)
static int mdt_intent_code (enum ldlm_intent_flags itcode)
static int mdt_intent_opc (enum ldlm_intent_flags itopc, struct mdt_thread_info *info, struct ldlm_lock **lockp, __u64 flags)
static int mdt_intent_policy (struct ldlm_namespace *ns, struct ldlm_lock **lockp, void *req_cookie, enum ldlm_mode mode, __u64 flags, void *data)
static void mdt_deregister_seq_exp (struct mdt_device *mdt)
static void mdt_seq_fini_cli (struct mdt_device *mdt)
static int mdt_seq_fini (const struct lu_env *env, struct mdt_device *mdt)
static int mdt_register_lwp_callback (void *data)
It will retrieve its FLDB entries from MDT0, and it only happens when upgrading existent FS to 2.6 or when local FLDB is corrupted, and it needs to refresh FLDB from the MDT0.
static int mdt_register_seq_exp (struct mdt_device *mdt)
static int mdt_seq_init_cli (const struct lu_env *env, struct mdt_device *mdt)
static int mdt_seq_init (const struct lu_env *env, struct mdt_device *mdt)
static int mdt_fld_fini (const struct lu_env *env, struct mdt_device *m)
static int mdt_fld_init (const struct lu_env *env, const char *uuid, struct mdt_device *m)
static void mdt_stack_pre_fini (const struct lu_env *env, struct mdt_device *m, struct lu_device *top)
static void mdt_stack_fini (const struct lu_env *env, struct mdt_device *m, struct lu_device *top)
static int mdt_connect_to_next (const struct lu_env *env, struct mdt_device *m, const char *next, struct obd_export **exp)
static int mdt_stack_init (const struct lu_env *env, struct mdt_device *mdt, struct lustre_cfg *cfg)
static int mdt_quota_init (const struct lu_env *env, struct mdt_device *mdt, struct lustre_cfg *cfg)
static void mdt_quota_fini (const struct lu_env *env, struct mdt_device *mdt)
static int mdt_tgt_getxattr (struct tgt_session_info *tsi)
static void mdt_fini (const struct lu_env *env, struct mdt_device *m)
static int mdt_postrecov (const struct lu_env *, struct mdt_device *)
static int mdt_init0 (const struct lu_env *env, struct mdt_device *m, struct lu_device_type *ldt, struct lustre_cfg *cfg)
static int mdt_process_config (const struct lu_env *env, struct lu_device *d, struct lustre_cfg *cfg)
static struct lu_object * mdt_object_alloc (const struct lu_env *env, const struct lu_object_header *hdr, struct lu_device *d)
static int mdt_object_init (const struct lu_env *env, struct lu_object *o, const struct lu_object_conf *unused)
static void mdt_object_free (const struct lu_env *env, struct lu_object *o)
static int mdt_object_print (const struct lu_env *env, void *cookie, lu_printer_t p, const struct lu_object *o)
static int mdt_prepare (const struct lu_env *env, struct lu_device *pdev, struct lu_device *cdev)
static int mdt_obd_set_info_async (const struct lu_env *env, struct obd_export *exp, __u32 keylen, void *key, __u32 vallen, void *val, struct ptlrpc_request_set *set)
static int mdt_connect_internal (struct obd_export *exp, struct mdt_device *mdt, struct obd_connect_data *data)
Match client and server connection feature flags.
static int mdt_ctxt_add_dirty_flag (struct lu_env *env, struct mdt_thread_info *info, struct mdt_file_data *mfd)
static int mdt_export_cleanup (struct obd_export *exp)
static void mdt_enable_slc (struct mdt_device *mdt)
static void mdt_disable_slc (struct mdt_device *mdt)
static int mdt_obd_disconnect (struct obd_export *exp)
static int mdt_obd_connect (const struct lu_env *env, struct obd_export **exp, struct obd_device *obd, struct obd_uuid *cluuid, struct obd_connect_data *data, void *localdata)
static int mdt_obd_reconnect (const struct lu_env *env, struct obd_export *exp, struct obd_device *obd, struct obd_uuid *cluuid, struct obd_connect_data *data, void *localdata)
static int mdt_init_export (struct obd_export *exp)
static int mdt_destroy_export (struct obd_export *exp)
int mdt_links_read (struct mdt_thread_info *info, struct mdt_object *mdt_obj, struct linkea_data *ldata)
static int mdt_path_current (struct mdt_thread_info *info, struct mdt_object *obj, struct getinfo_fid2path *fp, struct lu_fid *root_fid)
Given an MDT object, try to look up the full path to the object.
static int mdt_path (struct mdt_thread_info *info, struct mdt_object *obj, struct getinfo_fid2path *fp, struct lu_fid *root_fid)
Given an MDT object, use mdt_path_current to get the path.
static int mdt_fid2path (struct mdt_thread_info *info, struct lu_fid *root_fid, struct getinfo_fid2path *fp)
Get the full path of the provided FID, as of changelog record recno.
static int mdt_rpc_fid2path (struct mdt_thread_info *info, void *key, int keylen, void *val, int vallen)
int mdt_get_info (struct tgt_session_info *tsi)
static int mdt_ioc_child (struct lu_env *env, struct mdt_device *mdt, unsigned int cmd, int len, void *data)
static int mdt_ioc_version_get (struct mdt_thread_info *mti, void *karg)
static int mdt_obd_postrecov (struct obd_device *obd)
static struct lu_device * mdt_device_fini (const struct lu_env *env, struct lu_device *d)
static struct lu_device * mdt_device_free (const struct lu_env *env, struct lu_device *d)
static struct lu_device * mdt_device_alloc (const struct lu_env *env, struct lu_device_type *t, struct lustre_cfg *cfg)
LU_KEY_INIT (mdt, struct mdt_thread_info)
static void mdt_key_fini (const struct lu_context *ctx, struct lu_context_key *key, void *data)
LU_CONTEXT_KEY_DEFINE (mdt, LCT_MD_THREAD)
struct lu_ucred * mdt_ucred (const struct mdt_thread_info *info)
struct lu_ucred * mdt_ucred_check (const struct mdt_thread_info *info)
void mdt_enable_cos (struct mdt_device *mdt, int val)
Enable/disable COS (Commit On Sharing).
int mdt_cos_is_enabled (struct mdt_device *mdt)
Check COS (Commit On Sharing) status.
static int __init mdt_init (void)
static void __exit mdt_exit (void)
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Metadata Target ("LUSTRE_MDT_NAME")")
MODULE_VERSION (LUSTRE_VERSION_STRING)
MODULE_LICENSE ("GPL")
module_init (mdt_init)
module_exit (mdt_exit)
Variables
static unsigned int max_mod_rpcs_per_client = 8
mdl_mode_t mdt_mdl_lock_modes []
enum ldlm_mode mdt_dlm_lock_modes []
static struct lu_object_operations mdt_obj_ops
static struct kmem_cache * mdt_object_kmem
struct kmem_cache * mdt_hsm_cdt_kmem
struct kmem_cache * mdt_hsm_car_kmem
static struct lu_kmem_descr mdt_caches []
static struct tgt_handler mdt_tgt_handlers []
static struct tgt_handler mdt_sec_ctx_ops []
static struct tgt_handler mdt_quota_ops []
static struct tgt_opc_slice mdt_common_slice []
static struct cfg_interop_param mdt_interop_param []
struct lu_device_operations mdt_lu_ops
static struct obd_ops mdt_obd_device_ops
static struct
lu_device_type_operations mdt_device_type_ops
static struct lu_device_type mdt_device_type
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 49 of file mdt_handler.c.
Enumeration Type Documentation
enum mdt_it_code
Enumerator:
MDT_IT_OPEN
MDT_IT_OCREAT
MDT_IT_CREATE
MDT_IT_GETATTR
MDT_IT_READDIR
MDT_IT_LOOKUP
MDT_IT_UNLINK
MDT_IT_TRUNC
MDT_IT_GETXATTR
MDT_IT_LAYOUT
MDT_IT_QUOTA
MDT_IT_NR
Definition at line 3013 of file mdt_handler.c.
Function Documentation
LU_CONTEXT_KEY_DEFINE (mdt , LCT_MD_THREAD)
LU_KEY_INIT (mdt , struct mdt_thread_info)
int mdt_attr_get_complex (struct mdt_thread_info * info, struct mdt_object * o, struct md_attr * ma)
Definition at line 819 of file mdt_handler.c.
References CDEBUG, CLASSERT, D_INODE, ENTRY, GOTO, lu_buf::lb_buf, lu_buf::lb_len, LPX64, lu_object_attr(), lustre_buf2hsm(), md_attr::ma_acl, MA_ACL_DEF, md_attr::ma_acl_size, md_attr::ma_hsm, MA_HSM, MA_INODE, md_attr::ma_lmm, MA_LMV, MA_LMV_DEF, MA_LOV, md_attr::ma_need, md_attr::ma_pfid, MA_PFID, md_attr::ma_valid, mdt_attr_get_pfid(), mdt_object_child(), mdt_object_exists(), mdt_stripe_get(), mo_attr_get(), md_object::mo_lu, mo_xattr_get(), mode, mdt_thread_info::mti_buf, mdt_thread_info::mti_env, mdt_thread_info::mti_xattr_buf, RETURN, XATTR_NAME_ACL_DEFAULT, XATTR_NAME_DEFAULT_LMV, XATTR_NAME_HSM, XATTR_NAME_LMV, and XATTR_NAME_LOV.
Referenced by hsm_action_permission(), mdt_add_dirty_flag(), mdt_create_data(), mdt_cross_open(), mdt_getattr_internal(), mdt_getattr_name_lock(), mdt_hsm_get_md_hsm(), mdt_hsm_release(), mdt_hsm_state_get(), mdt_hsm_state_set(), mdt_md_create(), mdt_open_by_fid(), mdt_open_by_fid_lock(), mdt_reconstruct_create(), mdt_reconstruct_open(), mdt_reconstruct_setattr(), mdt_reint_migrate_internal(), mdt_reint_open(), mdt_reint_setattr(), mdt_reint_unlink(), and mdt_sync().
static int mdt_attr_get_eabuf_size (struct mdt_thread_info * info, struct mdt_object * o) [static]
Definition at line 625 of file mdt_handler.c.
References LU_BUF_NULL, lu_object_attr(), mdt_object_child(), mo_xattr_get(), mdt_thread_info::mti_env, XATTR_NAME_DEFAULT_LMV, XATTR_NAME_LMV, and XATTR_NAME_LOV.
Referenced by mdt_getattr(), and mdt_intent_layout().
static int mdt_attr_get_pfid (struct mdt_thread_info * info, struct mdt_object * o, struct lu_fid * pfid) [static]
Definition at line 772 of file mdt_handler.c.
References __swab32, __swab64, CERROR, DFID, ENTRY, fid_be_to_cpu(), lu_buf::lb_buf, lu_buf::lb_len, link_ea_entry::lee_parent_fid, link_ea_header::leh_len, link_ea_header::leh_magic, link_ea_header::leh_reccount, LINK_EA_MAGIC, mdt_big_xattr_get(), mdt_object_child(), mdt_object_fid(), mo_xattr_get(), mdt_thread_info::mti_big_lmm, mdt_thread_info::mti_big_lmmsize, mdt_thread_info::mti_buf, mdt_thread_info::mti_env, PFID, RETURN, and XATTR_NAME_LINK.
Referenced by mdt_attr_get_complex().
int mdt_big_xattr_get (struct mdt_thread_info * info, struct mdt_object * o, const char * name)
Definition at line 658 of file mdt_handler.c.
References ENTRY, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, LU_BUF_NULL, mdt_object_child(), mo_xattr_get(), mdt_thread_info::mti_big_lmm, mdt_thread_info::mti_big_lmm_used, mdt_thread_info::mti_big_lmmsize, mdt_thread_info::mti_buf, mdt_thread_info::mti_env, OBD_ALLOC_LARGE, OBD_FREE_LARGE, RETURN, size, and size_roundup_power2().
Referenced by mdt_attr_get_pfid(), mdt_init_slaves(), and mdt_stripe_get().
int mdt_blocking_ast (struct ldlm_lock * lock, struct ldlm_lock_desc * desc, void * data, int flag)
Blocking AST for mdt locks.
Starts transaction commit if in case of COS lock conflict or deffers such a commit to the mdt_save_lock.
Parameters:
lock the lock which blocks a request or cancelling lock
desc unused
data unused
flag indicates whether this cancelling or blocking callback
Return values:
0
See also:
ldlm_blocking_ast_nocheck
Definition at line 2308 of file mdt_handler.c.
References CWARN, ENTRY, ldlm_lock::l_blocking_ast, ldlm_lock::l_blocking_lock, ldlm_lock::l_client_cookie, ldlm_lock::l_req_mode, LCK_COS, LCK_EX, LCK_PW, LCT_LOCAL, ldlm_blocking_ast_nocheck(), LDLM_CB_CANCELING, ldlm_is_cos_incompat, ldlm_lock_to_ns(), lock_res_and_lock(), lu_env_fini(), lu_env_init(), mdt_blocking_ast(), mdt_cos_is_enabled(), mdt_dev(), mdt_device_commit_async(), mdt_set_lock_sync(), mdt_slc_is_enabled(), ldlm_namespace::ns_obd, obd_device::obd_lu_dev, obd_device::obd_name, RETURN, unlikely, and unlock_res_and_lock().
Referenced by mdt_blocking_ast(), mdt_fid_lock(), and mdt_lock_slaves().
static int mdt_body_has_lov (const struct lu_attr * la, const struct mdt_body * body) [inline, static]
Definition at line 593 of file mdt_handler.c.
References lu_attr::la_mode, mdt_body::mbo_valid, OBD_MD_FLDIREA, and OBD_MD_FLEASIZE.
Referenced by mdt_client_compatibility(), and mdt_getattr_internal().
static int mdt_body_unpack (struct mdt_thread_info * info, __u32 flags) [static]
Definition at line 2824 of file mdt_handler.c.
References CERROR, DFID, ENTRY, fid_is_sane(), HABEO_CORPUS, mdt_body::mbo_fid1, mdt_body::mbo_valid, mdt_object_exists(), mdt_object_find(), mdt_object_put(), mdt_thread_info::mti_body, mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, mdt_thread_info::mti_object, mdt_thread_info::mti_pill, OBD_MD_FLID, PFID, req_capsule_client_get(), RETURN, and RMF_MDT_BODY.
Referenced by mdt_unpack_req_pack_rep().
int mdt_check_resent_lock (struct mdt_thread_info * info, struct mdt_object * mo, struct mdt_lock_handle * lhc)
Definition at line 2396 of file mdt_handler.c.
References lustre_handle::cookie, CWARN, DFID, obd_export::exp_obd, fid_res_name_eq(), ldlm_lock::l_resource, LASSERT, LDLM_DEBUG_NOLOCK, ldlm_handle2lock(), LDLM_LOCK_PUT, LPX64, ldlm_resource::lr_name, lustre_handle_is_used(), lustre_msg_get_flags(), mdt_info_req(), mdt_object_fid(), mdt_lock_handle::mlh_reg_lh, MSG_RESENT, mdt_thread_info::mti_exp, obd_device::obd_name, PFID, RETURN, ptlrpc_request::rq_reqmsg, and unlikely.
Referenced by mdt_getattr_name_lock(), mdt_open_by_fid_lock(), and mdt_reint_open().
void mdt_clear_disposition (struct mdt_thread_info * info, struct ldlm_reply * rep, __u64 op_flag)
Definition at line 141 of file mdt_handler.c.
References ldlm_reply::lock_policy_res1, mdt_thread_info::mti_env, mdt_thread_info::mti_opdata, and tgt_opdata_clear().
Referenced by mdt_object_open_unlock(), and mdt_reint_open().
void mdt_client_compatibility (struct mdt_thread_info * info)
Definition at line 600 of file mdt_handler.c.
References ENTRY, EXIT, exp_connect_layout(), lu_attr::la_mode, md_attr::ma_attr, md_attr::ma_lmm, mdt_body_has_lov(), mdt_info_req(), mdt_thread_info::mti_attr, mdt_thread_info::mti_pill, req_capsule_server_get(), RETURN_EXIT, RMF_MDT_BODY, and ptlrpc_request::rq_export.
Referenced by mdt_close(), mdt_getattr(), mdt_getattr_name(), mdt_intent_getattr(), mdt_reint_internal(), and mdt_reint_setattr().
static int mdt_connect_internal (struct obd_export * exp, struct mdt_device * mdt, struct obd_connect_data * data) [static]
Match client and server connection feature flags.
Compute the compatibility flags for a connection request based on features mutually supported by client and server.
The obd_export::exp_connect_data.ocd_connect_flags field in exp must not be updated here, otherwise a partially initialized value may be exposed. After the connection request is successfully processed, the top-level MDT connect request handler atomically updates the export connect flags from the obd_connect_data::ocd_connect_flags field of the reply.
See also:
mdt_connect().
Parameters:
exp the obd_export associated with this client/target pair
mdt the target device for the connection
data stores data for this connect request
Return values:
0 success
-EPROTO data unexpectedly has zero obd_connect_data::ocd_brw_size
-EBADE client and server feature requirements are incompatible
Definition at line 5018 of file mdt_handler.c.
References CERROR, CWARN, obd_export::exp_client_uuid, exp_connect_flags_ptr(), obd_export::exp_lock, obd_export::exp_obd, obd_export::exp_obd_chain_timed, LASSERT, list_del_init(), LPX64, LUSTRE_VERSION_CODE, max_mod_rpcs_per_client, MD_MAX_BRW_SIZE, MDS_INODELOCK_FULL, MDT_CONNECT_SUPPORTED, mdt_device::mdt_max_ea_size, mdt_obd_name(), mdt_device::mdt_opts, mdt_device::mo_acl, mdt_device::mo_user_xattr, OBD_CONNECT_ACL, OBD_CONNECT_BRW_SIZE, OBD_CONNECT_FID, OBD_CONNECT_IBITS, OBD_CONNECT_LIGHTWEIGHT, OBD_CONNECT_MDS_MDS, OBD_CONNECT_MULTIMODRPCS, OBD_CONNECT_PINGLESS, OBD_CONNECT_XATTR, obd_device::obd_dev_lock, obd_connect_data::ocd_brw_size, obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_grant, OCD_HAS_FLAG, obd_connect_data::ocd_ibits_known, obd_connect_data::ocd_index, obd_connect_data::ocd_max_easize, obd_connect_data::ocd_maxmodrpcs, obd_connect_data::ocd_version, ptlrpc_pinger_suppress_pings(), and obd_uuid::uuid.
Referenced by mdt_obd_connect(), and mdt_obd_reconnect().
static int mdt_connect_to_next (const struct lu_env * env, struct mdt_device * m, const char * next, struct obd_export ** exp) [static]
Definition at line 3994 of file mdt_handler.c.
References CERROR, class_name2obd(), ENTRY, GOTO, LUSTRE_VERSION_CODE, mdt_obd_name(), OBD_ALLOC_PTR, obd_connect(), OBD_CONNECT_VERSION, OBD_FREE_PTR, obd_device::obd_uuid, obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_version, and RETURN.
Referenced by mdt_stack_init().
int mdt_cos_is_enabled (struct mdt_device * mdt)
Check COS (Commit On Sharing) status.
Return COS flag status.
Parameters:
mdt mdt device
Definition at line 6104 of file mdt_handler.c.
References mdt_device::mdt_opts, and mdt_device::mo_cos.
Referenced by mdt_blocking_ast(), mdt_cos_seq_show(), mdt_object_local_lock(), and mdt_save_lock().
static int mdt_ctxt_add_dirty_flag (struct lu_env * env, struct mdt_thread_info * info, struct mdt_file_data * mfd) [static]
Definition at line 5106 of file mdt_handler.c.
References ENTRY, LCT_SERVER_SESSION, lu_env::le_ses, lu_context_enter(), lu_context_exit(), lu_context_fini(), lu_context_init(), mdt_add_dirty_flag(), mdt_ucred(), mdt_file_data::mfd_object, mdt_thread_info::mti_attr, RETURN, lu_ucred::uc_valid, and UCRED_OLD.
Referenced by mdt_export_cleanup().
static void mdt_deregister_seq_exp (struct mdt_device * mdt) [static]
Definition at line 3668 of file mdt_handler.c.
References lu_client_seq::lcs_exp, lu_server_fld::lsf_control_exp, lustre_deregister_lwp_item(), mdt_seq_site(), seq_server_site::ss_client_seq, seq_server_site::ss_node_id, and seq_server_site::ss_server_fld.
Referenced by mdt_seq_fini().
static int mdt_destroy_export (struct obd_export * exp) [static]
Definition at line 5397 of file mdt_handler.c.
References ENTRY, obd_export::exp_client_uuid, exp_connect_rmtclient(), obd_export::exp_obd, obd_export::exp_outstanding_replies, LASSERT, ldlm_destroy_export(), list_empty(), mdt_cleanup_idmap(), obd_device::obd_uuid, obd_uuid_equals(), RETURN, tgt_client_free(), and unlikely.
static struct mdt_device* mdt_dev (struct lu_device * d) [static, read]
Referenced by lprocfs_identity_flush_seq_write(), lprocfs_identity_info_seq_write(), lprocfs_mds_evict_client_seq_write(), mdt_async_commit_count_seq_show(), mdt_async_commit_count_seq_write(), mdt_blocking_ast(), mdt_cos_seq_show(), mdt_cos_seq_write(), mdt_device_fini(), mdt_device_free(), mdt_enable_remote_dir_gid_seq_show(), mdt_enable_remote_dir_gid_seq_write(), mdt_enable_remote_dir_seq_show(), mdt_enable_remote_dir_seq_write(), mdt_evict_tgt_nids_seq_show(), mdt_evict_tgt_nids_seq_write(), mdt_export_cleanup(), mdt_hsm_cdt_control_seq_show(), mdt_hsm_cdt_control_seq_write(), mdt_identity_acquire_expire_seq_show(), mdt_identity_acquire_expire_seq_write(), mdt_identity_expire_seq_show(), mdt_identity_expire_seq_write(), mdt_identity_upcall_seq_show(), mdt_identity_upcall_seq_write(), mdt_iocontrol(), mdt_nosquash_nids_seq_show(), mdt_nosquash_nids_seq_write(), mdt_obd_connect(), mdt_obd_disconnect(), mdt_obd_postrecov(), mdt_obd_reconnect(), mdt_object_init(), mdt_prepare(), mdt_process_config(), mdt_root_squash_seq_show(), mdt_root_squash_seq_write(), mdt_sec_level_seq_show(), mdt_sec_level_seq_write(), mdt_site_stats_seq_show(), and mdt_thread_info_init().
static struct lu_device* mdt_device_alloc (const struct lu_env * env, struct lu_device_type * t, struct lustre_cfg * cfg) [static, read]
Definition at line 6021 of file mdt_handler.c.
References mdt_device_free(), mdt_init0(), mdt_device::mdt_lu_dev, and OBD_ALLOC_PTR.
static void mdt_device_commit_async (const struct lu_env * env, struct mdt_device * mdt) [static]
Asyncronous commit for mdt device.
Pass asynchonous commit call down the MDS stack.
Parameters:
env environment
mdt the mdt device
Definition at line 2250 of file mdt_handler.c.
References CWARN, dt_device::dd_ops, dt_device_operations::dt_commit_async, ENTRY, EXIT, mdt_device::mdt_async_commit_count, mdt_device::mdt_bottom, mdt_obd_name(), and unlikely.
Referenced by mdt_blocking_ast(), and mdt_save_lock().
static struct lu_device* mdt_device_fini (const struct lu_env * env, struct lu_device * d) [static, read]
Definition at line 5999 of file mdt_handler.c.
References ENTRY, mdt_dev(), mdt_fini(), and RETURN.
static struct lu_device* mdt_device_free (const struct lu_env * env, struct lu_device * d) [static, read]
Definition at line 6009 of file mdt_handler.c.
References ENTRY, lu_device_fini(), mdt_dev(), mdt_device::mdt_lu_dev, OBD_FREE_PTR, and RETURN.
Referenced by mdt_device_alloc().
static int mdt_device_sync (const struct lu_env * env, struct mdt_device * mdt) [static]
Definition at line 1941 of file mdt_handler.c.
References dt_device::dd_ops, dt_device_operations::dt_sync, ENTRY, mdt_device::mdt_bottom, and RETURN.
Referenced by mdt_enable_cos(), mdt_iocontrol(), and mdt_sync().
static void mdt_disable_slc (struct mdt_device * mdt) [inline, static]
Definition at line 5219 of file mdt_handler.c.
References BLOCKING_SYNC_ON_CANCEL, lu_target::lut_sync_lock_cancel, mdt_device::mdt_lut, and NEVER_SYNC_ON_CANCEL.
Referenced by mdt_obd_disconnect().
void mdt_enable_cos (struct mdt_device * mdt, int val)
Enable/disable COS (Commit On Sharing).
Set/Clear the COS flag in mdt options.
Parameters:
mdt mdt device
val 0 disables COS, other values enable COS
Definition at line 6081 of file mdt_handler.c.
References CWARN, LCT_LOCAL, lu_env_fini(), lu_env_init(), mdt_device_sync(), mdt_obd_name(), mdt_device::mdt_opts, mdt_device::mo_cos, and unlikely.
Referenced by mdt_cos_seq_write().
static void mdt_enable_slc (struct mdt_device * mdt) [inline, static]
Definition at line 5213 of file mdt_handler.c.
References BLOCKING_SYNC_ON_CANCEL, lu_target::lut_sync_lock_cancel, mdt_device::mdt_lut, and NEVER_SYNC_ON_CANCEL.
Referenced by mdt_obd_connect().
static void __exit mdt_exit (void) [static]
Definition at line 6151 of file mdt_handler.c.
References class_unregister_type(), lu_kmem_fini(), LUSTRE_MDT_NAME, and mds_mod_exit().
static int mdt_export_cleanup (struct obd_export * exp) [static]
Definition at line 5131 of file mdt_handler.c.
References class_handle_unhash(), ENTRY, obd_export::exp_failed, obd_export::exp_flags, obd_export::exp_obd, FMODE_WRITE, INIT_LIST_HEAD, LASSERT, LCT_MD_THREAD, lu_env::le_ctx, list_del_init(), list_empty(), list_entry, list_for_each_entry_safe, list_move_tail(), lu_context_key_get(), lu_env_fini(), lu_env_init(), md_attr::ma_attr_flags, MA_FLAGS, md_attr::ma_need, md_attr::ma_valid, MDS_KEEP_ORPHAN, mdt_ctxt_add_dirty_flag(), mdt_dev(), mdt_mfd_close(), mdt_thread_key, mdt_export_data::med_open_head, mdt_export_data::med_open_lock, mdt_file_data::mfd_handle, mdt_file_data::mfd_list, mdt_file_data::mfd_mode, mdt_thread_info::mti_attr, mdt_thread_info::mti_env, mdt_thread_info::mti_exp, mdt_thread_info::mti_mdt, list_head::next, obd_device::obd_lu_dev, OBD_OPT_FAILOVER, RETURN, and tgt_client_del().
Referenced by mdt_obd_disconnect().
static int mdt_fid2path (struct mdt_thread_info * info, struct lu_fid * root_fid, struct getinfo_fid2path * fp) [static]
Get the full path of the provided FID, as of changelog record recno.
This checks sanity and looks up object for user provided FID before calling the actual path lookup code.
Part of the MDT layer implementation of lfs fid2path.
Parameters:
[in] info Per-thread common data shared by mdt level handlers.
[in,out] fp User-provided struct for arguments and to store path information
Return values:
0 Lookup successful, path information and recno stored in fp
-ENOENT,object does not exist
negative errno if there was a problem
Definition at line 5641 of file mdt_handler.c.
References __u64, CDEBUG, CWARN, D_INFO, D_IOCTL, DFID, ENTRY, fid_is_namespace_visible(), fid_is_sane(), FID_SEQ_NORMAL, getinfo_fid2path::gf_fid, getinfo_fid2path::gf_linkno, getinfo_fid2path::gf_path, getinfo_fid2path::gf_recno, getinfo_fid2path::gf_u, LPU64, LPX64, mdt_obd_name(), mdt_object_exists(), mdt_object_find(), mdt_object_put(), mdt_object_remote(), mdt_path(), mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, PFID, and RETURN.
Referenced by mdt_rpc_fid2path().
static void mdt_fini (const struct lu_env * env, struct mdt_device * m) [static]
Definition at line 4447 of file mdt_handler.c.
References cfs_free_nidlist(), ENTRY, EXIT, LASSERT, lu_device::ld_obd, lu_device::ld_ref, ldlm_namespace_free_post(), ldlm_namespace_free_prior(), LLOG_AGENT_ORIG_CTXT, LLOG_CHANGELOG_ORIG_CTXT, lfsck_stop::ls_flags, LS_PAUSED, lfsck_stop::ls_status, md2lu_dev(), md_device::md_ops, md_device_operations::mdo_iocontrol, mdt2obd_dev(), mdt_device::mdt_child, mdt_fld_fini(), mdt_fs_cleanup(), mdt_hsm_cdt_fini(), mdt_hsm_cdt_stop(), mdt_device::mdt_identity_cache, mdt_llog_ctxt_unclone(), mdt_device::mdt_lu_dev, mdt_device::mdt_lut, mdt_device::mdt_namespace, mdt_obd_name(), mdt_device::mdt_opts, mdt_procfs_fini(), mdt_quota_fini(), mdt_seq_fini(), mdt_device::mdt_squash, mdt_stack_fini(), mdt_stack_pre_fini(), mdt_device::mo_coordinator, obd_exports_barrier(), obd_device::obd_force, OBD_IOC_STOP_LFSCK, obd_device::obd_namespace, obd_zombie_barrier(), ping_evictor_stop(), root_squash_info::rsi_nosquash_nids, server_put_mount(), target_recovery_fini(), tgt_fini(), and upcall_cache_cleanup().
Referenced by mdt_device_fini().
static int mdt_fld_fini (const struct lu_env * env, struct mdt_device * m) [static]
Definition at line 3874 of file mdt_handler.c.
References ENTRY, fld_server_fini(), mdt_seq_site(), OBD_FREE_PTR, RETURN, and seq_server_site::ss_server_fld.
Referenced by mdt_fini(), and mdt_init0().
static int mdt_fld_init (const struct lu_env * env, const char * uuid, struct mdt_device * m) [static]
Definition at line 3889 of file mdt_handler.c.
References ENTRY, fld_server_init(), LU_SEQ_RANGE_MDT, mdt_device::mdt_bottom, mdt_seq_site(), OBD_ALLOC_PTR, OBD_FREE_PTR, RETURN, and seq_server_site::ss_server_fld.
Referenced by mdt_init0().
__u64 mdt_get_disposition (struct ldlm_reply * rep, __u64 op_flag)
Definition at line 134 of file mdt_handler.c.
References ldlm_reply::lock_policy_res1.
Referenced by mdt_intent_getattr(), mdt_intent_reint(), and mdt_reconstruct_open().
int mdt_get_info (struct tgt_session_info * tsi)
Definition at line 5728 of file mdt_handler.c.
References CDEBUG, D_IOCTL, ENTRY, err_serious(), KEY_FID2PATH, KEY_IS, mdt_rpc_fid2path(), mdt_thread_info_fini(), RCL_CLIENT, RCL_SERVER, req_capsule_client_get(), req_capsule_get_size(), req_capsule_server_get(), req_capsule_server_pack(), req_capsule_set_size(), RETURN, RMF_GETINFO_KEY, RMF_GETINFO_VAL, RMF_GETINFO_VALLEN, tgt_name(), tsi2mdt_info(), tgt_session_info::tsi_pill, and tgt_session_info::tsi_tgt.
static int mdt_get_root (struct tgt_session_info * tsi) [static]
Definition at line 354 of file mdt_handler.c.
References ENTRY, err_serious(), EXIT, GOTO, mdt_body::mbo_fid1, mdt_body::mbo_valid, mdt_check_ucred(), mdt_lookup_fileset(), mdt_device::mdt_md_root_fid, mdt_thread_info_fini(), mdt_thread_info::mti_mdt, mdt_thread_info::mti_pill, OBD_FAIL_CHECK, OBD_FAIL_MDS_GET_ROOT_PACK, OBD_MD_FLID, RCL_CLIENT, req_capsule_client_get(), req_capsule_get_size(), req_capsule_server_get(), RMF_MDT_BODY, RMF_NAME, and tsi2mdt_info().
static int mdt_getattr (struct tgt_session_info * tsi) [static]
Definition at line 1136 of file mdt_handler.c.
References DEF_REP_MD_SIZE, ENTRY, err_serious(), EXIT, GOTO, LASSERT, lu_fid_eq(), lu_object_assert_exists(), lustre_msg_get_opc(), mdt_body::mbo_aclsize, mdt_body::mbo_eadatasize, mdt_body::mbo_valid, MDS_GETATTR, mdt_attr_get_eabuf_size(), mdt_check_ucred(), mdt_client_compatibility(), mdt_exit_ucred(), mdt_fix_reply(), mdt_getattr_internal(), mdt_info_req(), mdt_init_ucred(), mdt_device::mdt_md_root_fid, mdt_object_fid(), mdt_thread_info_fini(), mdt_object::mot_obj, mdt_thread_info::mti_cross_ref, mdt_thread_info::mti_mdt, mdt_thread_info::mti_object, mdt_thread_info::mti_pill, OBD_MD_FLCROSSREF, OBD_MD_FLDIREA, OBD_MD_FLRMTPERM, OBD_MD_LINKNAME, RCL_SERVER, req_capsule_client_get(), req_capsule_server_get(), req_capsule_server_pack(), req_capsule_set_size(), RMF_MDT_BODY, RMF_MDT_MD, tsi2mdt_info(), and unlikely.
static int mdt_getattr_internal (struct mdt_thread_info * info, struct mdt_object * o, int ma_need) [static]
Definition at line 905 of file mdt_handler.c.
References CDEBUG, CERROR, D_INFO, D_INODE, DFID, dt_root_get(), ENTRY, err_serious(), obd_export::exp_client_uuid, exp_connect_flags(), exp_connect_rmtclient(), GOTO, HS_RELEASED, lu_attr::la_mode, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, likely, LPROC_MDT_GETATTR, lu_fid_eq(), lu_object_attr(), lustre_msg_get_opc(), md_attr::ma_attr, md_attr::ma_hsm, MA_HSM, MA_INODE, md_attr::ma_lmm, md_attr::ma_lmm_size, md_attr::ma_lmv, MA_LMV, MA_LMV_DEF, md_attr::ma_lmv_size, MA_LOV, MA_LOV_DEF, md_attr::ma_need, md_attr::ma_valid, mdt_body::mbo_aclsize, mdt_body::mbo_eadatasize, mdt_body::mbo_fid1, mdt_body::mbo_max_mdsize, mdt_body::mbo_t_state, mdt_body::mbo_valid, MDS_GETATTR, mdt_attr_get_complex(), mdt_body_has_lov(), mdt_device::mdt_bottom, mdt_counter_incr(), mdt_dump_lmm(), mdt_dump_lmv(), mdt_hsm_restore_is_running(), mdt_info_req(), mdt_is_dne_client(), mdt_is_striped_client(), mdt_device::mdt_max_mdsize, mdt_device::mdt_md_root_fid, mdt_obd_name(), mdt_object_child(), mdt_object_fid(), mdt_object_find(), mdt_object_put(), mdt_object_remote(), mdt_pack_attr2body(), mdt_pack_remote_perm(), mdt_stripe_get(), md_hsm::mh_flags, min_t, md_object::mo_lu, mo_readlink(), MS_RESTORE, mdt_thread_info::mti_attr, mdt_thread_info::mti_body, mdt_thread_info::mti_buf, mdt_thread_info::mti_env, mdt_thread_info::mti_exp, mdt_thread_info::mti_mdt, mdt_thread_info::mti_pill, OBD_CONNECT_ACL, OBD_FAIL_CHECK, OBD_FAIL_MDS_GETATTR_PACK, OBD_FAIL_MDS_READLINK_EPROTO, OBD_MD_DEFAULT_MEA, OBD_MD_FLACL, OBD_MD_FLDIREA, OBD_MD_FLEASIZE, OBD_MD_FLID, OBD_MD_FLMODEASIZE, OBD_MD_FLRMTPERM, OBD_MD_LINKNAME, OBD_MD_MDS, OBD_MD_MEA, OBD_MD_TSTATE, PFID, RCL_SERVER, req_capsule_get_size(), req_capsule_server_get(), RETURN, RMF_ACL, RMF_MDT_BODY, RMF_MDT_MD, ptlrpc_request::rq_export, ptlrpc_request::rq_reqmsg, unlikely, obd_uuid::uuid, and XATTR_NAME_LOV.
Referenced by mdt_getattr(), and mdt_getattr_name_lock().
static int mdt_getattr_name (struct tgt_session_info * tsi) [static]
Definition at line 1634 of file mdt_handler.c.
References lustre_handle::cookie, ENTRY, EXIT, GOTO, LASSERT, ldlm_lock_decref(), lustre_handle_is_used(), mdt_body::mbo_aclsize, mdt_body::mbo_eadatasize, mdt_body::mbo_valid, MDS_INODELOCK_UPDATE, mdt_client_compatibility(), mdt_exit_ucred(), mdt_fix_reply(), mdt_getattr_name_lock(), mdt_init_ucred_intent_getattr(), MDT_LH_CHILD, mdt_thread_info_fini(), mdt_lock_handle::mlh_reg_lh, mdt_lock_handle::mlh_reg_mode, mdt_thread_info::mti_cross_ref, mdt_thread_info::mti_lh, mdt_thread_info::mti_pill, OBD_MD_FLCROSSREF, req_capsule_client_get(), req_capsule_server_get(), RMF_MDT_BODY, tsi2mdt_info(), and unlikely.
static int mdt_getattr_name_lock (struct mdt_thread_info * info, struct mdt_lock_handle * lhc, __u64 child_bits, struct ldlm_reply * ldlm_rep) [static]
Definition at line 1366 of file mdt_handler.c.
References CDEBUG, CERROR, cfs_time_current_sec(), D_INFO, D_INODE, DFID, DISP_LOOKUP_EXECD, DISP_LOOKUP_NEG, DISP_LOOKUP_POS, DLDLMRES, DNAME, ENTRY, ergo, err_serious(), EXIT, exp_connect_layout(), fid_is_sane(), fid_res_name_eq(), fid_zero(), GOTO, ldlm_lock::l_resource, lu_attr::la_ctime, LA_CTIME, lu_attr::la_valid, LASSERT, LASSERTF, LCK_PR, LDLM_DEBUG, ldlm_handle2lock(), LDLM_LOCK_PUT, lu_name::ln_name, lu_name::ln_namelen, ldlm_resource::lr_name, lu_fid_eq(), lu_name_is_valid(), lu_object_attr(), LU_OBJECT_DEBUG, lustre_handle_is_used(), lustre_msg_get_flags(), md_attr::ma_attr, MA_INODE, MA_LOV, md_attr::ma_need, md_attr::ma_valid, mdt_body::mbo_fid2, mdt_body::mbo_valid, mdo_lookup(), MDS_INODELOCK_LAYOUT, MDS_INODELOCK_LOOKUP, MDS_INODELOCK_PERM, MDS_INODELOCK_UPDATE, mdt_attr_get_complex(), mdt_check_resent_lock(), mdt_getattr_internal(), mdt_info_req(), MDT_LH_PARENT, mdt_lock_handle_init(), mdt_lock_pdo_init(), mdt_lock_reg_init(), mdt_name_unpack(), mdt_device::mdt_namespace, mdt_obd_name(), mdt_object_child(), mdt_object_exists(), mdt_object_fid(), mdt_object_find(), mdt_object_get(), mdt_object_lock(), mdt_object_lock_try(), mdt_object_put(), mdt_object_remote(), mdt_object_unlock(), mdt_raw_lookup(), mdt_set_disposition(), mdt_lock_handle::mlh_reg_lh, MNF_FIX_ANON, mdt_object::mot_obj, MSG_RESENT, mdt_thread_info::mti_attr, mdt_thread_info::mti_body, mdt_thread_info::mti_cross_ref, mdt_thread_info::mti_env, mdt_thread_info::mti_exp, mdt_thread_info::mti_lh, mdt_thread_info::mti_mdt, mdt_thread_info::mti_name, mdt_thread_info::mti_object, mdt_thread_info::mti_pill, mdt_thread_info::mti_spec, mdt_thread_info::mti_tmp_fid1, ldlm_namespace::ns_ctime_age_limit, OBD_FAIL_CHECK, OBD_FAIL_MDS_NO_LL_GETATTR, OBD_FAIL_MDS_RESEND, OBD_FAIL_TIMEOUT, OBD_MD_FLID, obd_timeout, PFID, PLDLMRES, PNAME, req_capsule_client_get(), RETURN, RMF_MDT_BODY, RMF_NAME, ptlrpc_request::rq_reqmsg, md_op_spec::sp_permitted, and unlikely.
Referenced by mdt_getattr_name(), and mdt_intent_getattr().
static int __init mdt_init (void) [static]
Definition at line 6122 of file mdt_handler.c.
References class_register_type(), CLASSERT, FID_LEN, FID_NOBRACE_LEN, GOTO, lu_kmem_fini(), lu_kmem_init(), LUSTRE_MDT_NAME, mds_mod_exit(), mds_mod_init(), mdt_device_type, and mdt_obd_device_ops.
static int mdt_init0 (const struct lu_env * env, struct mdt_device * m, struct lu_device_type * ldt, struct lustre_cfg * cfg) [static]
Definition at line 4511 of file mdt_handler.c.
References CERROR, cfs_time_shift_64(), class_name2obd(), CWARN, ENTRY, GOTO, INIT_LIST_HEAD, LASSERT, lustre_cfg::lcfg_bufcount, lu_device::ld_obd, lu_device::ld_ops, lu_site::ld_seq_site, LDLM_CB_REPLY_PORTAL, LDLM_CB_REQUEST_PORTAL, ldlm_namespace_free(), LDLM_NAMESPACE_GREEDY, ldlm_namespace_new(), LDLM_NAMESPACE_SERVER, LDLM_NS_TYPE_MDT, ldlm_register_intent(), ldlm_timeout, LDLM_TIMEOUT_DEFAULT, lu_env::le_ctx, LMD_FLG_SKIP_LFSCK, lustre_mount_info::lmi_sb, lu_context_key_get(), lu_device_init(), lu_env_refill(), LUSTRE_CFG_BUFLEN, lustre_cfg_string(), LUSTRE_MDT_NAME, MAX_MD_SIZE, md2lu_dev(), md_device::md_ops, md_device_operations::mdo_iocontrol, md_device_operations::mdo_maxeasize_get, MDS_LDLM_TIMEOUT_DEFAULT, mdt2obd_dev(), mdt_device::mdt_async_commit_count, mdt_device::mdt_bottom, mdt_device::mdt_child, mdt_common_slice, MDT_COS_DEFAULT, mdt_device::mdt_enable_remote_dir, mdt_device::mdt_enable_remote_dir_gid, mdt_fld_fini(), mdt_fld_init(), mdt_fs_cleanup(), mdt_fs_setup(), mdt_hsm_cdt_fini(), mdt_hsm_cdt_init(), mdt_device::mdt_identity_cache, mdt_identity_upcall_cache_ops, MDT_IDENTITY_UPCALL_PATH, mdt_intent_policy(), mdt_device::mdt_ldlm_client, mdt_device::mdt_lu_dev, mdt_lu_ops, mdt_lu_site(), mdt_device::mdt_lut, mdt_lvbo, mdt_device::mdt_max_ea_size, mdt_device::mdt_max_mdsize, mdt_device::mdt_mds_mds_conns, mdt_device::mdt_namespace, mdt_obd_name(), mdt_device::mdt_opts, mdt_device::mdt_osfs_age, mdt_device::mdt_osfs_lock, mdt_procfs_fini(), mdt_procfs_init(), mdt_quota_init(), mdt_seq_fini(), mdt_seq_init(), mdt_seq_site(), mdt_device::mdt_skip_lfsck, mdt_device::mdt_squash, mdt_stack_fini(), mdt_stack_init(), mdt_thread_key, MNTOPT_ACL, MNTOPT_USERXATTR, mdt_device::mo_acl, mdt_device::mo_coordinator, mdt_device::mo_cos, mdt_device::mo_evict_tgt_nids, mdt_device::mo_user_xattr, mdt_thread_info::mti_u, ldlm_namespace::ns_lvbo, ldlm_namespace::ns_lvbp, mdt_thread_info::ns_name, OBD_FAIL_MDS_ALL_REPLY_NET, OBD_FAIL_MDS_ALL_REQUEST_NET, OBD_IOC_GET_MNTOPT, obd_device::obd_ldlm_client, obd_device::obd_lu_dev, obd_device::obd_namespace, obd_device::obd_no_conn, obd_device::obd_replayable, obd_device::obd_uuid, OBT_MAGIC, ping_evictor_start(), ptlrpc_init_client(), RETURN, root_squash_info::rsi_gid, root_squash_info::rsi_nosquash_nids, root_squash_info::rsi_sem, root_squash_info::rsi_uid, server_get_mount(), server_put_mount(), seq_server_site::ss_lu, seq_server_site::ss_node_id, target_recovery_fini(), tgt_adapt_sptlrpc_conf(), tgt_fini(), tgt_init(), obd_device::u, upcall_cache_cleanup(), upcall_cache_init(), and obd_uuid::uuid.
Referenced by mdt_device_alloc().
static int mdt_init_export (struct obd_export * exp) [static]
Definition at line 5360 of file mdt_handler.c.
References CERROR, ENTRY, obd_export::exp_client_uuid, obd_export::exp_connecting, obd_export::exp_lock, obd_export::exp_obd, GOTO, INIT_LIST_HEAD, ldlm_init_export(), mdt_export_data::med_idmap, mdt_export_data::med_idmap_mutex, mdt_export_data::med_open_head, mdt_export_data::med_open_lock, obd_device::obd_name, obd_device::obd_uuid, obd_uuid_equals(), RETURN, tgt_client_alloc(), tgt_client_free(), and unlikely.
static int mdt_intent_code (enum ldlm_intent_flags itcode) [static]
Definition at line 3507 of file mdt_handler.c.
References CERROR, IT_CREAT, IT_GETATTR, IT_GETXATTR, IT_LAYOUT, IT_LOOKUP, IT_OPEN, IT_QUOTA_CONN, IT_QUOTA_DQACQ, IT_READDIR, IT_TRUNC, IT_UNLINK, MDT_IT_CREATE, MDT_IT_GETATTR, MDT_IT_GETXATTR, MDT_IT_LAYOUT, MDT_IT_LOOKUP, MDT_IT_OCREAT, MDT_IT_OPEN, MDT_IT_QUOTA, MDT_IT_READDIR, MDT_IT_TRUNC, and MDT_IT_UNLINK.
Referenced by mdt_intent_opc().
static void mdt_intent_fixup_resent (struct mdt_thread_info * info, struct ldlm_lock * new_lock, struct mdt_lock_handle * lh, __u64 flags) [static]
Definition at line 3215 of file mdt_handler.c.
References lustre_handle::cookie, D_DLMTRACE, DEBUG_REQ, portals_handle::h_cookie, ldlm_lock::l_granted_mode, ldlm_lock::l_handle, LDLM_DEBUG, LDLM_FL_RESENT, ldlm_request::lock_handle, LPX64, lustre_msg_clear_flags(), lustre_msg_get_flags(), mdt_info_req(), mdt_lock_handle::mlh_reg_lh, mdt_lock_handle::mlh_reg_mode, MSG_RESENT, mdt_thread_info::mti_pill, req_can_reconstruct(), req_capsule_client_get(), RMF_DLM_REQ, and ptlrpc_request::rq_reqmsg.
Referenced by mdt_intent_getattr(), mdt_intent_getxattr(), mdt_intent_layout(), and mdt_intent_reint().
static int mdt_intent_getattr (enum mdt_it_code opcode, struct mdt_thread_info * info, struct ldlm_lock ** lockp, __u64 flags) [static]
Definition at line 3296 of file mdt_handler.c.
References __u64, CERROR, clear_serious(), lustre_handle::cookie, DISP_IT_EXECD, DISP_LOOKUP_NEG, DISP_LOOKUP_POS, ELDLM_LOCK_ABORTED, ENTRY, EXIT, GOTO, LASSERT, ldlm_reply::lock_policy_res2, mdt_body::mbo_aclsize, mdt_body::mbo_eadatasize, mdt_body::mbo_valid, MDS_INODELOCK_LOOKUP, MDS_INODELOCK_PERM, MDS_INODELOCK_UPDATE, mdt_client_compatibility(), mdt_exit_ucred(), mdt_fix_reply(), mdt_get_disposition(), mdt_getattr_name_lock(), mdt_init_ucred_intent_getattr(), mdt_intent_fixup_resent(), mdt_intent_lock_replace(), MDT_IT_GETATTR, MDT_IT_LOOKUP, MDT_LH_RMT, mdt_set_disposition(), mdt_lock_handle::mlh_reg_lh, mdt_thread_info::mti_cross_ref, mdt_thread_info::mti_lh, mdt_thread_info::mti_pill, OBD_MD_FLCROSSREF, req_capsule_client_get(), req_capsule_server_get(), RMF_DLM_REP, and RMF_MDT_BODY.
static int mdt_intent_getxattr (enum mdt_it_code opcode, struct mdt_thread_info * info, struct ldlm_lock ** lockp, __u64 flags) [static]
Definition at line 3259 of file mdt_handler.c.
References err_serious(), ldlm_reply::lock_policy_res2, lustre_handle_is_used(), MDS_INODELOCK_XATTR, mdt_getxattr(), mdt_info_req(), mdt_intent_fixup_resent(), mdt_intent_lock_replace(), MDT_LH_RMT, mdt_lock_reg_init(), mdt_object_lock(), mdt_lock_handle::mlh_reg_lh, mdt_thread_info::mti_lh, mdt_thread_info::mti_object, mdt_thread_info::mti_pill, req_capsule_server_get(), RETURN, and RMF_DLM_REP.
static int mdt_intent_layout (enum mdt_it_code opcode, struct mdt_thread_info * info, struct ldlm_lock ** lockp, __u64 flags) [static]
Definition at line 3365 of file mdt_handler.c.
References CERROR, lustre_handle::cookie, ENTRY, fid_extract_from_res_name(), GOTO, LAYOUT_INTENT_ACCESS, layout_intent::li_opc, lustre_handle_is_used(), LVB_T_LAYOUT, mdt_attr_get_eabuf_size(), mdt_intent_fixup_resent(), mdt_intent_lock_replace(), MDT_IT_LAYOUT, MDT_LH_LAYOUT, mdt_device::mdt_max_mdsize, mdt_obd_name(), mdt_object_exists(), mdt_object_find(), mdt_object_put(), mdt_object_remote(), mdt_lock_handle::mlh_reg_lh, mdt_thread_info::mti_env, mdt_thread_info::mti_lh, mdt_thread_info::mti_mdt, mdt_thread_info::mti_pill, mdt_thread_info::mti_tmp_fid2, RCL_SERVER, req_capsule_client_get(), req_capsule_server_pack(), req_capsule_set_size(), RETURN, RMF_DLM_LVB, and RMF_LAYOUT_INTENT.
static int mdt_intent_lock_replace (struct mdt_thread_info * info, struct ldlm_lock ** lockp, struct mdt_lock_handle * lh, __u64 flags, int result) [static]
Definition at line 3121 of file mdt_handler.c.
References cfs_hash_add(), class_export_lock_get, lustre_handle::cookie, ELDLM_LOCK_REPLACED, obd_export::exp_lock_hash, ldlm_lock::l_blocking_ast, ldlm_lock::l_completion_ast, ldlm_lock::l_exp_hash, ldlm_lock::l_export, ldlm_lock::l_flags, ldlm_lock::l_readers, ldlm_lock::l_reference, ldlm_lock::l_remote_handle, ldlm_lock::l_writers, LASSERT, LASSERTF, LDLM_DEBUG_NOLOCK, LDLM_FL_INTENT_ONLY, LDLM_FL_LOCAL, LDLM_FL_RESENT, ldlm_handle2lock_long(), LDLM_LOCK_RELEASE, lock_res_and_lock(), LPX64, lu_ref_del(), lustre_msg_get_flags(), mdt_info_req(), mdt_lock_handle::mlh_reg_lh, MSG_RESENT, RETURN, ptlrpc_request::rq_export, ptlrpc_request::rq_reqmsg, and unlock_res_and_lock().
Referenced by mdt_intent_getattr(), mdt_intent_getxattr(), mdt_intent_layout(), and mdt_intent_reint().
static int mdt_intent_opc (enum ldlm_intent_flags itopc, struct mdt_thread_info * info, struct ldlm_lock ** lockp, __u64 flags) [static]
Definition at line 3554 of file mdt_handler.c.
References ENTRY, exp_connect_flags(), mdt_it_flavor::it_act, mdt_it_flavor::it_flags, mdt_it_flavor::it_fmt, ldlm_reply::lock_policy_res2, LVB_T_LQUOTA, mdt_info_req(), mdt_intent_code(), MDT_IT_QUOTA, mdt_device::mdt_qmt_dev, mdt_unpack_req_pack_rep(), mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, mdt_thread_info::mti_pill, MUTABOR, OBD_CONNECT_RDONLY, OBD_FAIL_MDS_INTENT_DELAY, OBD_FAIL_TIMEOUT, ptlrpc_status_hton(), qmt_hdls, qmt_handlers::qmth_intent_policy, req_capsule_extend(), req_capsule_server_get(), RETURN, RMF_DLM_REP, ptlrpc_request::rq_export, and ptlrpc_request::rq_repmsg.
Referenced by mdt_intent_policy().
static int mdt_intent_policy (struct ldlm_namespace * ns, struct ldlm_lock ** lockp, void * req_cookie, enum ldlm_mode mode, __u64 flags, void * data) [static]
Definition at line 3615 of file mdt_handler.c.
References DLM_INTENT_IT_OFF, ELDLM_OK, ENTRY, ergo, err_serious(), ldlm_lock_desc::l_resource, LASSERT, LDLM_IBITS, ldlm_request::lock_desc, mdt_intent_opc(), mdt_thread_info_fini(), mdt_thread_info::mti_dlm_req, mdt_thread_info::mti_pill, ldlm_intent::opc, req_capsule::rc_fmt, req_capsule::rc_req, RCL_SERVER, req_capsule_client_get(), req_capsule_extend(), req_capsule_server_pack(), req_capsule_set_size(), RETURN, RMF_DLM_LVB, RMF_LDLM_INTENT, ptlrpc_request::rq_reqmsg, RQF_LDLM_ENQUEUE, RQF_LDLM_INTENT_BASIC, tgt_ses_info(), and tsi2mdt_info().
Referenced by mdt_init0().
static int mdt_intent_reint (enum mdt_it_code opcode, struct mdt_thread_info * info, struct ldlm_lock ** lockp, __u64 flags) [static]
< if VBR failure then return error
Definition at line 3431 of file mdt_handler.c.
References CERROR, clear_serious(), lustre_handle::cookie, DISP_LOOKUP_EXECD, DISP_LOOKUP_NEG, DISP_OPEN_CREATE, ELDLM_LOCK_ABORTED, ENTRY, err_serious(), ldlm_reply::lock_policy_res2, lustre_handle_is_used(), MDT_EREMOTE_OPEN, mdt_get_disposition(), mdt_info_req(), mdt_intent_fixup_resent(), mdt_intent_lock_replace(), MDT_LH_RMT, mdt_reint_internal(), mdt_reint_opcode(), mdt_set_disposition(), mdt_lock_handle::mlh_reg_lh, mdt_thread_info::mti_lh, mdt_thread_info::mti_pill, REINT_CREATE, REINT_MAX, REINT_OPEN, req_capsule_server_get(), RETURN, RMF_DLM_REP, RQF_LDLM_INTENT_CREATE, and RQF_LDLM_INTENT_OPEN.
static int mdt_ioc_child (struct lu_env * env, struct mdt_device * mdt, unsigned int cmd, int len, void * data) [static]
Definition at line 5778 of file mdt_handler.c.
References ENTRY, LASSERT, lu_context::lc_thread, LCT_SERVER_SESSION, lu_env::le_ses, lu_context_enter(), lu_context_exit(), lu_context_fini(), lu_context_init(), md_device::md_ops, md_device_operations::mdo_iocontrol, mdt_device::mdt_child, and RETURN.
Referenced by mdt_iocontrol().
static int mdt_ioc_version_get (struct mdt_thread_info * mti, void * karg) [static]
before calling version get the correct MDS should be fid, this is error to find remote object here
Definition at line 5801 of file mdt_handler.c.
References __u64, CDEBUG, CERROR, D_IOCTL, DFID, dt_version_get(), ENOENT_VERSION, ENTRY, fid_is_sane(), obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf2, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, LCK_CR, MDS_INODELOCK_UPDATE, MDT_LH_PARENT, mdt_lock_reg_init(), mdt_obj2dt(), mdt_object_exists(), mdt_object_find_lock(), mdt_object_remote(), mdt_object_unlock_put(), mdt_thread_info::mti_env, mdt_thread_info::mti_lh, PFID, RETURN, and version.
Referenced by mdt_iocontrol().
static int mdt_iocontrol (unsigned int cmd, struct obd_export * exp, int len, void * karg, void __user * uarg) [static]
Definition at line 5849 of file mdt_handler.c.
References CDEBUG, CERROR, D_IOCTL, dt_device::dd_ops, dt_device_operations::dt_ro, ENTRY, obd_export::exp_obd, obd_ioctl_data::ioc_inlbuf1, LCT_MD_THREAD, lu_env::le_ctx, llog_catalog_list(), LLOG_CATALOGS_OID, lfsck_stop::ls_flags, lfsck_stop::ls_status, LS_STOPPED, lfsck_start_param::lsp_index_valid, lfsck_start_param::lsp_start, lu_context_key_get(), lu_env_fini(), lu_env_init(), lu_local_obj_fid(), md_device::md_ops, md_device_operations::mdo_iocontrol, mdt_device::mdt_bottom, mdt_device::mdt_child, mdt_dev(), mdt_device_sync(), mdt_ioc_child(), mdt_ioc_version_get(), mdt_obd_name(), mdt_thread_key, mdt_thread_info::mti_env, mdt_thread_info::mti_exp, mdt_thread_info::mti_mdt, mdt_thread_info::mti_tmp_fid1, obd_device::obd_abort_recovery, OBD_IOC_ABORT_RECOVERY, OBD_IOC_CATLOGLIST, OBD_IOC_CHANGELOG_CLEAR, OBD_IOC_CHANGELOG_DEREG, OBD_IOC_CHANGELOG_REG, OBD_IOC_GET_OBJ_VERSION, OBD_IOC_QUERY_LFSCK, OBD_IOC_SET_READONLY, OBD_IOC_START_LFSCK, OBD_IOC_STOP_LFSCK, OBD_IOC_SYNC, obd_device::obd_lu_dev, RETURN, and unlikely.
Referenced by mdt_set_info().
static int mdt_is_lock_sync (struct ldlm_lock * lock) [inline, static]
Check whehter the lock "synchonous" or not.
Parameters:
lock the lock to check
Return values:
1 the lock is "synchonous"
0 the lock isn't "synchronous"
See also:
mdt_set_lock_sync
mdt_save_lock
Definition at line 2290 of file mdt_handler.c.
References ldlm_lock::l_ast_data.
Referenced by mdt_save_lock().
static void mdt_key_fini (const struct lu_context * ctx, struct lu_context_key * key, void * data) [static]
Definition at line 6047 of file mdt_handler.c.
References mdt_thread_info::mti_big_lmm, mdt_thread_info::mti_big_lmmsize, OBD_FREE_LARGE, and OBD_FREE_PTR.
int mdt_links_read (struct mdt_thread_info * info, struct mdt_object * mdt_obj, struct linkea_data * ldata)
Definition at line 5420 of file mdt_handler.c.
References LASSERT, lu_buf::lb_buf, linkea_data::ld_buf, linkea_init(), lu_buf_check_and_alloc(), lu_buf_free(), mdt_object_child(), mdt_object_exists(), mo_xattr_get(), mdt_thread_info::mti_env, and XATTR_NAME_LINK.
Referenced by mdt_lock_objects_in_linkea(), and mdt_path_current().
static int mdt_llog_ctxt_clone (const struct lu_env * env, struct mdt_device * mdt, int idx) [static]
clone llog ctxt from child (mdd) This allows remote llog (replicator) access.
We can either pass all llog RPCs (eg mdt_llog_create) on to child where the context was originally set up, or we can handle them directly. I choose the latter, but that means I need any llog contexts set up by child to be accessable by the mdt. So we clone the context into our context list here.
Definition at line 2131 of file mdt_handler.c.
References CERROR, llog_ctxt_null(), llog_group_set_ctxt(), md_device::md_ops, md_device_operations::mdo_llog_ctxt_get, mdt2obd_dev(), and mdt_device::mdt_child.
Referenced by mdt_prepare().
static int mdt_llog_ctxt_unclone (const struct lu_env * env, struct mdt_device * mdt, int idx) [static]
Definition at line 2153 of file mdt_handler.c.
References llog_ctxt_put(), llog_get_context(), and mdt2obd_dev().
Referenced by mdt_fini().
void mdt_lock_handle_fini (struct mdt_lock_handle * lh)
Definition at line 2899 of file mdt_handler.c.
References LASSERT, lustre_handle_is_used(), mdt_lock_handle::mlh_pdo_lh, and mdt_lock_handle::mlh_reg_lh.
Referenced by mdt_thread_info_fini().
void mdt_lock_handle_init (struct mdt_lock_handle * lh)
Definition at line 2888 of file mdt_handler.c.
References lustre_handle::cookie, LCK_MINMODE, MDT_NUL_LOCK, mdt_lock_handle::mlh_pdo_lh, mdt_lock_handle::mlh_pdo_mode, mdt_lock_handle::mlh_reg_lh, mdt_lock_handle::mlh_reg_mode, mdt_lock_handle::mlh_rreg_lh, mdt_lock_handle::mlh_rreg_mode, and mdt_lock_handle::mlh_type.
Referenced by mdt_getattr_name_lock(), mdt_md_create(), mdt_object_open_lock(), mdt_reint_open(), and mdt_thread_info_init().
void mdt_lock_pdo_init (struct mdt_lock_handle * lh, enum ldlm_mode lock_mode, const struct lu_name * lname)
Definition at line 171 of file mdt_handler.c.
References LCK_MINMODE, lu_name::ln_name, lu_name::ln_namelen, lu_name_is_valid(), MDT_PDO_LOCK, mdt_lock_handle::mlh_pdo_hash, mdt_lock_handle::mlh_pdo_mode, mdt_lock_handle::mlh_reg_mode, mdt_lock_handle::mlh_rreg_mode, mdt_lock_handle::mlh_type, and unlikely.
Referenced by mdt_getattr_name_lock(), mdt_lock_objects_in_linkea(), mdt_md_create(), mdt_reint_link(), mdt_reint_migrate_internal(), mdt_reint_open(), mdt_reint_rename_internal(), and mdt_reint_unlink().
static void mdt_lock_pdo_mode (struct mdt_thread_info * info, struct mdt_object * o, struct mdt_lock_handle * lh) [static]
Definition at line 196 of file mdt_handler.c.
References CERROR, ENTRY, EXIT, LASSERT, LBUG, LCK_CR, LCK_CW, LCK_EX, LCK_MINMODE, LCK_PR, LCK_PW, MDL_MINMODE, mdo_lock_mode(), mdt_dlm_mode2mdl_mode(), mdt_mdl_mode2dlm_mode(), mdt_object_child(), mdt_lock_handle::mlh_pdo_mode, mdt_lock_handle::mlh_reg_mode, mode, and mdt_thread_info::mti_env.
Referenced by mdt_object_local_lock().
void mdt_lock_reg_init (struct mdt_lock_handle * lh, enum ldlm_mode lm)
Definition at line 163 of file mdt_handler.c.
References MDT_REG_LOCK, mdt_lock_handle::mlh_pdo_hash, mdt_lock_handle::mlh_reg_mode, mdt_lock_handle::mlh_rreg_mode, and mdt_lock_handle::mlh_type.
Referenced by hsm_restore_cb(), hsm_swap_layouts(), mdt_add_dirty_flag(), mdt_attr_set(), mdt_close_swap_layouts(), mdt_getattr_name_lock(), mdt_hsm_add_actions(), mdt_hsm_release(), mdt_hsm_state_get(), mdt_hsm_state_set(), mdt_intent_getxattr(), mdt_ioc_version_get(), mdt_md_create(), mdt_object_open_lock(), mdt_reint_link(), mdt_reint_migrate_internal(), mdt_reint_open(), mdt_reint_rename_internal(), mdt_reint_setattr(), mdt_reint_setxattr(), mdt_reint_unlink(), mdt_swap_layouts(), and mdt_unlock_slaves().
static int mdt_lookup_fileset (struct mdt_thread_info * info, const char * fileset, struct lu_fid * fid) [static]
Definition at line 271 of file mdt_handler.c.
References fid_zero(), LASSERT, lu_name::ln_name, lu_name::ln_namelen, lu_object_attr(), mdo_lookup(), mdt_device::mdt_md_root_fid, mdt_object_child(), mdt_object_find(), mdt_object_put(), mode, mdt_object::mot_obj, mdt_thread_info::mti_cross_ref, mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, mdt_thread_info::mti_name, mdt_thread_info::mti_spec, name, OBD_ALLOC, and OBD_FREE.
Referenced by mdt_get_root().
static int mdt_obd_connect (const struct lu_env * env, struct obd_export ** exp, struct obd_device * obd, struct obd_uuid * cluuid, struct obd_connect_data * data, void * localdata) [static]
Definition at line 5252 of file mdt_handler.c.
References class_conn2export(), class_connect(), class_disconnect(), ENTRY, obd_export::exp_obd, obd_export::exp_obd_chain_timed, GOTO, KEY_OSP_CONNECTED, LASSERT, lsd_client_data::lcd_uuid, list_del_init(), mdt_device::mdt_child_exp, mdt_connect_internal(), mdt_dev(), mdt_enable_slc(), mdt_export_stats_init(), MDT_FL_SYNCED, mdt_device::mdt_mds_mds_conns, mdt_device::mdt_state, nodemap_add_member(), nodemap_del_member(), OBD_CONNECT_LIGHTWEIGHT, OBD_CONNECT_MDS_MDS, obd_device::obd_dev_lock, obd_get_info(), obd_device::obd_lu_dev, obd_connect_data::ocd_connect_flags, RETURN, and tgt_client_new().
static int mdt_obd_disconnect (struct obd_export * exp) [static]
Definition at line 5225 of file mdt_handler.c.
References CDEBUG, class_export_get(), class_export_put(), D_IOCTL, ENTRY, exp_connect_flags(), obd_export::exp_obd, LASSERT, mdt_dev(), mdt_disable_slc(), mdt_export_cleanup(), mdt_device::mdt_mds_mds_conns, nodemap_del_member(), OBD_CONNECT_LIGHTWEIGHT, OBD_CONNECT_MDS_MDS, obd_device::obd_lu_dev, and RETURN.
static int mdt_obd_postrecov (struct obd_device * obd) [static]
Definition at line 5974 of file mdt_handler.c.
References LCT_MD_THREAD, lu_env_fini(), lu_env_init(), mdt_dev(), mdt_postrecov(), obd_device::obd_lu_dev, and RETURN.
static int mdt_obd_reconnect (const struct lu_env * env, struct obd_export * exp, struct obd_device * obd, struct obd_uuid * cluuid, struct obd_connect_data * data, void * localdata) [static]
Definition at line 5333 of file mdt_handler.c.
References ENTRY, mdt_connect_internal(), mdt_dev(), mdt_export_stats_init(), nodemap_add_member(), nodemap_del_member(), obd_device::obd_lu_dev, and RETURN.
static int mdt_obd_set_info_async (const struct lu_env * env, struct obd_export * exp, __u32 keylen, void * key, __u32 vallen, void * val, struct ptlrpc_request_set * set) [static]
Definition at line 4979 of file mdt_handler.c.
References ENTRY, KEY_IS, KEY_SPTLRPC_CONF, RETURN, and tgt_adapt_sptlrpc_conf().
static struct lu_object* mdt_object_alloc (const struct lu_env * env, const struct lu_object_header * hdr, struct lu_device * d) [static, read]
Definition at line 4836 of file mdt_handler.c.
References ENTRY, lu_object::lo_ops, lu_object_add_top(), lu_object_header_init(), lu_object_init(), mdt_obj_ops, mdt_object_kmem, mdt_object::mot_header, mdt_object::mot_lov_mutex, mdt_object::mot_obj, mdt_object::mot_open_sem, mdt_object::mot_write_lock, OBD_SLAB_ALLOC_PTR_GFP, and RETURN.
struct mdt_object* mdt_object_find (const struct lu_env * env, struct mdt_device * d, const struct lu_fid * f) [read]
Definition at line 2224 of file mdt_handler.c.
References CDEBUG, D_INFO, DFID, ENTRY, lu_object_find(), mdt_device::mdt_lu_dev, mdt_obj(), PFID, RETURN, and unlikely.
Referenced by hsm_swap_layouts(), mdt_body_unpack(), mdt_close_swap_layouts(), mdt_cross_open(), mdt_fid2path(), mdt_getattr_internal(), mdt_getattr_name_lock(), mdt_hsm_agent_send(), mdt_hsm_cdt_stop(), mdt_hsm_get_md_hsm(), mdt_intent_layout(), mdt_lock_objects_in_linkea(), mdt_lock_slaves(), mdt_lookup_fileset(), mdt_lookup_version_check(), mdt_lvbo_fill(), mdt_md_create(), mdt_object_find_check(), mdt_object_find_lock(), mdt_open_by_fid(), mdt_open_by_fid_lock(), mdt_orphan_open(), mdt_path_current(), mdt_reconstruct_create(), mdt_reconstruct_open(), mdt_reconstruct_setattr(), mdt_reint_link(), mdt_reint_migrate_internal(), mdt_reint_open(), mdt_reint_rename_internal(), mdt_reint_setattr(), mdt_reint_unlink(), mdt_rename_lock(), and mdt_swap_layouts().
struct mdt_object* mdt_object_find_lock (struct mdt_thread_info * info, const struct lu_fid * f, struct mdt_lock_handle * lh, __u64 ibits) [read]
Definition at line 2783 of file mdt_handler.c.
References mdt_object_find(), mdt_object_lock(), mdt_object_put(), mdt_thread_info::mti_env, and mdt_thread_info::mti_mdt.
Referenced by hsm_restore_cb(), hsm_swap_layouts(), mdt_hsm_add_actions(), mdt_ioc_version_get(), and mdt_reint_setxattr().
static void mdt_object_free (const struct lu_env * env, struct lu_object * o) [static]
Definition at line 4885 of file mdt_handler.c.
References CDEBUG, D_INFO, DFID, ENTRY, EXIT, LASSERT, lu_object::lo_header, lu_object_fid(), lu_object_fini(), lu_object_header_fini(), mdt_obj(), mdt_object_kmem, mdt_object::mot_lease_count, mdt_object::mot_open_count, OBD_SLAB_FREE_PTR, and PFID.
static int mdt_object_init (const struct lu_env * env, struct lu_object * o, const struct lu_object_conf * unused) [static]
Definition at line 4863 of file mdt_handler.c.
References CDEBUG, D_INFO, DFID, ENTRY, lu_device::ld_ops, lu_device_operations::ldo_object_alloc, lu_object::lo_dev, lu_object::lo_header, lu_object_add(), lu_object_fid(), md_device::md_lu_dev, mdt_device::mdt_child, mdt_dev(), PFID, and RETURN.
static int mdt_object_local_lock (struct mdt_thread_info * info, struct mdt_object * o, struct mdt_lock_handle * lh, __u64 ibits, bool nonblock, bool cos_incompat) [static]
Definition at line 2463 of file mdt_handler.c.
References __u64, ldlm_inodebits::bits, ENTRY, obd_export::exp_handle, fid_build_reg_res_name(), GOTO, portals_handle::h_cookie, ldlm_policy_data::l_inodebits, LASSERT, LCK_EX, LCK_MINMODE, LCK_NL, LCK_PW, LDLM_FL_ATOMIC_CB, LDLM_FL_BLOCK_NOWAIT, LDLM_FL_COS_ENABLED, LDLM_FL_COS_INCOMPAT, LDLM_FL_LOCAL_ONLY, lu_object_attr(), lustre_handle_is_used(), LUSTRE_RES_ID_HSH_OFF, MDS_INODELOCK_LOOKUP, MDS_INODELOCK_UPDATE, mdt_cos_is_enabled(), mdt_fid_lock(), mdt_lock_pdo_mode(), mdt_device::mdt_namespace, MDT_NUL_LOCK, mdt_object_exists(), mdt_object_fid(), mdt_object_remote(), mdt_object_unlock(), MDT_PDO_LOCK, mdt_lock_handle::mlh_pdo_hash, mdt_lock_handle::mlh_pdo_lh, mdt_lock_handle::mlh_pdo_mode, mdt_lock_handle::mlh_reg_lh, mdt_lock_handle::mlh_reg_mode, mdt_lock_handle::mlh_type, mdt_object::mot_obj, mdt_thread_info::mti_exp, mdt_thread_info::mti_mdt, mdt_thread_info::mti_policy, mdt_thread_info::mti_res_id, ldlm_res_id::name, OBD_FAIL_MDS_PDO_LOCK, OBD_FAIL_PRECHECK, OBD_FAIL_TIMEOUT, RETURN, and unlikely.
Referenced by mdt_object_lock_internal().
int mdt_object_lock (struct mdt_thread_info * info, struct mdt_object * o, struct mdt_lock_handle * lh, __u64 ibits)
Definition at line 2619 of file mdt_handler.c.
References mdt_object_lock_internal().
Referenced by mdt_add_dirty_flag(), mdt_close_swap_layouts(), mdt_getattr_name_lock(), mdt_hsm_release(), mdt_hsm_state_get(), mdt_hsm_state_set(), mdt_intent_getxattr(), mdt_lock_objects_in_linkea(), mdt_md_create(), mdt_object_find_lock(), mdt_object_open_lock(), mdt_reint_open(), mdt_reint_setattr(), mdt_reint_unlink(), and mdt_swap_layouts().
static int mdt_object_lock_internal (struct mdt_thread_info * info, struct mdt_object * o, struct mdt_lock_handle * lh, __u64 ibits, bool nonblock, bool cos_incompat) [static]
Definition at line 2563 of file mdt_handler.c.
References CDEBUG, D_INFO, DFID, ELDLM_OK, ENTRY, LCK_EX, MDS_INODELOCK_LAYOUT, MDS_INODELOCK_LOOKUP, MDS_INODELOCK_PERM, MDS_INODELOCK_UPDATE, MDS_INODELOCK_XATTR, mdt_obd_name(), mdt_object_fid(), mdt_object_local_lock(), mdt_object_remote(), mdt_object_unlock(), MDT_PDO_LOCK, MDT_REG_LOCK, mdt_remote_object_lock(), mdt_lock_handle::mlh_pdo_hash, mdt_lock_handle::mlh_rreg_lh, mdt_lock_handle::mlh_rreg_mode, mdt_lock_handle::mlh_type, mdt_thread_info::mti_mdt, PFID, and RETURN.
Referenced by mdt_object_lock(), mdt_object_lock_try(), mdt_reint_object_lock(), and mdt_reint_object_lock_try().
int mdt_object_lock_try (struct mdt_thread_info * info, struct mdt_object * o, struct mdt_lock_handle * lh, __u64 ibits)
Definition at line 2634 of file mdt_handler.c.
References mdt_object_lock_internal().
Referenced by mdt_getattr_name_lock(), and mdt_object_open_lock().
struct mdt_object* mdt_object_new (const struct lu_env * env, struct mdt_device * d, const struct lu_fid * f) [read]
Definition at line 2206 of file mdt_handler.c.
References CDEBUG, D_INFO, DFID, ENTRY, LOC_F_NEW, lu_object_conf::loc_flags, lu_object_find(), mdt_device::mdt_lu_dev, mdt_obj(), PFID, RETURN, and unlikely.
Referenced by mdt_md_create(), mdt_orphan_open(), and mdt_reint_open().
static int mdt_object_print (const struct lu_env * env, void * cookie, lu_printer_t p, const struct lu_object * o) [static]
Definition at line 4905 of file mdt_handler.c.
References LUSTRE_MDT_NAME, mdt_obj(), and mdt_object::mot_flags.
static int mdt_object_sync (struct mdt_thread_info * info) [static]
Definition at line 1952 of file mdt_handler.c.
References CWARN, DFID, ENTRY, mdt_obd_name(), mdt_object_child(), mdt_object_exists(), mdt_object_fid(), mo_object_sync(), mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, mdt_thread_info::mti_object, PFID, and RETURN.
Referenced by mdt_sync().
void mdt_object_unlock (struct mdt_thread_info * info, struct mdt_object * o, struct mdt_lock_handle * lh, int decref)
Unlock mdt object.
Immeditely release the regular lock and the PDO lock or save the lock in request and keep them referenced until client ACK or transaction commit.
Parameters:
info thread info object
o mdt object
lh mdt lock handle referencing regular and PDO locks
decref force immediate lock releasing
Definition at line 2771 of file mdt_handler.c.
References ENTRY, EXIT, mdt_save_lock(), mdt_save_remote_lock(), mdt_lock_handle::mlh_pdo_lh, mdt_lock_handle::mlh_pdo_mode, mdt_lock_handle::mlh_reg_lh, mdt_lock_handle::mlh_reg_mode, mdt_lock_handle::mlh_rreg_lh, and mdt_lock_handle::mlh_rreg_mode.
Referenced by hsm_cdt_request_completed(), mdt_add_dirty_flag(), mdt_attr_set(), mdt_close_swap_layouts(), mdt_getattr_name_lock(), mdt_hsm_agent_send(), mdt_hsm_release(), mdt_hsm_state_get(), mdt_hsm_state_set(), mdt_md_create(), mdt_object_local_lock(), mdt_object_lock_internal(), mdt_object_open_lock(), mdt_object_open_unlock(), mdt_object_unlock_put(), mdt_reint_link(), mdt_reint_migrate_internal(), mdt_reint_rename_internal(), mdt_reint_setattr(), mdt_reint_unlink(), mdt_swap_layouts(), and mdt_unlock_slaves().
void mdt_object_unlock_put (struct mdt_thread_info * info, struct mdt_object * o, struct mdt_lock_handle * lh, int decref)
Definition at line 2803 of file mdt_handler.c.
References mdt_object_put(), mdt_object_unlock(), and mdt_thread_info::mti_env.
Referenced by hsm_swap_layouts(), mdt_hsm_cdt_stop(), mdt_ioc_version_get(), mdt_lock_objects_in_linkea(), mdt_reint_open(), mdt_reint_setxattr(), mdt_unlock_list(), and mdt_unlock_slaves().
void mdt_pack_attr2body (struct mdt_thread_info * info, struct mdt_body * b, const struct lu_attr * attr, const struct lu_fid * fid)
Definition at line 501 of file mdt_handler.c.
References CDEBUG, D_INODE, D_VFSTRACE, DFID, lu_attr::la_atime, LA_ATIME, lu_attr::la_blocks, lu_attr::la_ctime, LA_CTIME, lu_attr::la_flags, LA_FLAGS, lu_attr::la_gid, LA_GID, LA_MODE, lu_attr::la_mode, lu_attr::la_mtime, LA_MTIME, lu_attr::la_nlink, LA_NLINK, lu_attr::la_rdev, lu_attr::la_size, LA_TYPE, lu_attr::la_uid, LA_UID, lu_attr::la_valid, LASSERT, LOV_PATTERN_F_RELEASED, LPX64, MA_INODE, md_attr::ma_lmm, MA_LOV, md_attr::ma_need, md_attr::ma_valid, mdt_body::mbo_atime, mdt_body::mbo_blocks, mdt_body::mbo_ctime, mdt_body::mbo_fid1, mdt_body::mbo_flags, mdt_body::mbo_gid, mdt_body::mbo_mode, mdt_body::mbo_mtime, mdt_body::mbo_nlink, mdt_body::mbo_rdev, mdt_body::mbo_size, mdt_body::mbo_uid, mdt_body::mbo_valid, mdt_body_reverse_idmap(), mdt_thread_info::mti_attr, mdt_thread_info::mti_exp, NODEMAP_FS_TO_CLIENT, NODEMAP_GID, nodemap_map_id(), NODEMAP_UID, OBD_MD_FLATIME, OBD_MD_FLBLOCKS, OBD_MD_FLCTIME, OBD_MD_FLFLAGS, OBD_MD_FLGID, OBD_MD_FLID, OBD_MD_FLMODE, OBD_MD_FLMTIME, OBD_MD_FLNLINK, OBD_MD_FLRDEV, OBD_MD_FLSIZE, OBD_MD_FLTYPE, OBD_MD_FLUID, PFID, and unlikely.
Referenced by mdt_finish_open(), mdt_getattr_internal(), mdt_handle_last_unlink(), mdt_md_create(), mdt_reconstruct_create(), mdt_reconstruct_setattr(), mdt_reint_setattr(), and mdt_sync().
static int mdt_path (struct mdt_thread_info * info, struct mdt_object * obj, struct getinfo_fid2path * fp, struct lu_fid * root_fid) [static]
Given an MDT object, use mdt_path_current to get the path.
Essentially a wrapper to retry mdt_path_current a set number of times if -EAGAIN is returned (usually because an object is being moved).
Part of the MDT layer implementation of lfs fid2path.
Parameters:
[in] info Per-thread common data shared by mdt level handlers.
[in] obj Object to do path lookup of
[in,out] fp User-provided struct for arguments and to store path information
Return values:
0 Lookup successful, path information stored in fp
negative errno if there was a problem
Definition at line 5599 of file mdt_handler.c.
References ENTRY, getinfo_fid2path::gf_path, getinfo_fid2path::gf_pathlen, getinfo_fid2path::gf_u, lu_fid_eq(), mdt_device::mdt_md_root_fid, mdt_object_fid(), mdt_path_current(), mdt_thread_info::mti_mdt, and RETURN.
Referenced by mdt_fid2path().
static int mdt_path_current (struct mdt_thread_info * info, struct mdt_object * obj, struct getinfo_fid2path * fp, struct lu_fid * root_fid) [static]
Given an MDT object, try to look up the full path to the object.
Part of the MDT layer implementation of lfs fid2path.
Parameters:
[in] info Per-thread common data shared by MDT level handlers.
[in] obj Object to do path lookup of
[in,out] fp User-provided struct to store path information
[in] root_fid Root FID of current path should reach
Return values:
0 Lookup successful, path information stored in fp
-EAGAIN Lookup failed, usually because object is being moved
negative errno if there was a problem
Definition at line 5464 of file mdt_handler.c.
References ENTRY, getinfo_fid2path::gf_fid, getinfo_fid2path::gf_linkno, getinfo_fid2path::gf_path, getinfo_fid2path::gf_pathlen, getinfo_fid2path::gf_u, GOTO, lu_buf::lb_buf, lu_buf::lb_len, linkea_data::ld_buf, le32_to_cpu, link_ea_header::leh_reccount, linkea_entry_unpack(), lmv_mds_md::lmv_magic, LMV_MAGIC_STRIPE, lu_name::ln_name, lu_name::ln_namelen, lu_buf_check_and_alloc(), lu_fid_eq(), mdt_links_read(), mdt_device::mdt_md_root_fid, mdt_obj(), mdt_object_child(), mdt_object_exists(), mdt_object_fid(), mdt_object_find(), mdt_object_put(), mdt_object_remote(), mo_xattr_get(), mdt_thread_info::mti_big_buf, mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, mdt_thread_info::mti_name, mdt_thread_info::mti_tmp_fid1, mdt_thread_info::mti_xattr_buf, RETURN, and XATTR_NAME_LMV.
Referenced by mdt_path().
static int mdt_postrecov (const struct lu_env * env, struct mdt_device * mdt) [static]
Definition at line 5951 of file mdt_handler.c.
References CWARN, ENTRY, lu_device::ld_ops, lu_device_operations::ldo_recovery_complete, lfsck_start_param::lsp_index_valid, lfsck_start_param::lsp_start, md2lu_dev(), md_device::md_ops, md_device_operations::mdo_iocontrol, mdt_device::mdt_child, mdt_obd_name(), mdt_device::mdt_skip_lfsck, OBD_IOC_START_LFSCK, and RETURN.
Referenced by mdt_obd_postrecov(), and mdt_prepare().
static int mdt_prepare (const struct lu_env * env, struct lu_device * pdev, struct lu_device * cdev) [static]
Definition at line 4915 of file mdt_handler.c.
References ENTRY, LASSERT, LASSERTF, lu_device::ld_obd, lu_device::ld_ops, lu_device_operations::ldo_prepare, lfsck_register_namespace(), LLOG_AGENT_ORIG_CTXT, LLOG_CHANGELOG_ORIG_CTXT, md_device::md_lu_dev, md_device::md_ops, md_device_operations::mdo_root_get, mdt_device::mdt_bottom, mdt_device::mdt_child, mdt_dev(), MDT_FL_CFGLOG, mdt_llog_ctxt_clone(), mdt_device::mdt_lut, mdt_device::mdt_md_root_fid, mdt_device::mdt_namespace, mdt_postrecov(), mdt_device::mdt_seq_site, mdt_device::mdt_state, obd_device::obd_dev_lock, obd_device::obd_no_conn, obd_device::obd_recovering, RETURN, seq_server_site::ss_node_id, target_recovery_init(), and tgt_request_handle().
static int mdt_process_config (const struct lu_env * env, struct lu_device * d, struct lustre_cfg * cfg) [static]
Definition at line 4765 of file mdt_handler.c.
References CERROR, class_find_old_param(), class_process_proc_param(), CWARN, ENTRY, hsm_cdt_get_proc_vars(), lustre_cfg::lcfg_command, LCFG_PARAM, lu_device::ld_obd, lu_device::ld_ops, lu_device_operations::ldo_process_config, lustre_cfg_free(), lustre_cfg_rename(), lustre_cfg_string(), md2lu_dev(), mdt_device::mdt_child, mdt_dev(), mdt_interop_param, cfg_interop_param::new_param, obd_device::obd_vars, cfg_interop_param::old_param, PARAM_HSM, PARAM_MDT, and RETURN.
static int mdt_quota_dqacq (struct tgt_session_info * tsi) [static]
Definition at line 2192 of file mdt_handler.c.
References ENTRY, err_serious(), mdt_exp2dev(), mdt_device::mdt_qmt_dev, qmt_hdls, qmt_handlers::qmth_dqacq, RETURN, tgt_ses_req(), tgt_session_info::tsi_env, and tgt_session_info::tsi_exp.
static void mdt_quota_fini (const struct lu_env * env, struct mdt_device * mdt) [static]
Definition at line 4311 of file mdt_handler.c.
References ENTRY, EXIT, LASSERT, mdt_device::mdt_qmt_dev, mdt_device::mdt_qmt_exp, obd_disconnect(), and RETURN_EXIT.
Referenced by mdt_fini().
static int mdt_quota_init (const struct lu_env * env, struct mdt_device * mdt, struct lustre_cfg * cfg) [static]
Definition at line 4175 of file mdt_handler.c.
References CERROR, class_attach(), class_cleanup(), class_detach(), class_get_profile(), class_manual_cleanup(), class_name2obd(), class_put_profile(), class_setup(), dt_device::dd_lu_dev, ENTRY, EXIT, GOTO, LASSERT, LCFG_ATTACH, LCFG_SETUP, lu_device::ld_obd, lu_device::ld_ops, lu_device_operations::ldo_prepare, lustre_profile::lp_dt, lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), lustre_cfg_string(), LUSTRE_QMT_NAME, LUSTRE_VERSION_CODE, MAX_OBD_NAME, mdt_device::mdt_bottom, mdt_device::mdt_lu_dev, mdt_device::mdt_qmt_dev, mdt_device::mdt_qmt_exp, mdt_device::mdt_seq_site, OBD_ALLOC, OBD_ALLOC_PTR, obd_connect(), OBD_CONNECT_VERSION, OBD_FREE, OBD_FREE_PTR, obd_device::obd_lu_dev, obd_device::obd_name, obd_device::obd_uuid, obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_version, RETURN, seq_server_site::ss_node_id, uuid, and UUID_MAX.
Referenced by mdt_init0().
static int mdt_quotactl (struct tgt_session_info * tsi) [static]
Definition at line 2016 of file mdt_handler.c.
References CDEBUG, CERROR, CFS_IDMAP_NOTFOUND, D_QUOTA, ENTRY, err_serious(), exp_connect_rmtclient(), lquotactl_slv(), lustre_idmap_lookup_gid(), lustre_idmap_lookup_uid(), lu_target::lut_bottom, mdt_exp2dev(), mdt_device::mdt_qmt_dev, nodemap_can_setquota(), NODEMAP_CLIENT_TO_FS, nodemap_map_id(), NODEMAP_UID, Q_GETOINFO, Q_GETOQUOTA, obd_quotactl::qc_cmd, obd_quotactl::qc_id, obd_quotactl::qc_type, qmt_hdls, qmt_handlers::qmth_quotactl, req_capsule_client_get(), req_capsule_server_get(), req_capsule_server_pack(), RETURN, RMF_OBD_QUOTACTL, swap, tgt_session_info::tsi_env, tgt_session_info::tsi_exp, tgt_session_info::tsi_pill, tgt_session_info::tsi_tgt, and unlikely.
static int mdt_raw_lookup (struct mdt_thread_info * info, struct mdt_object * parent, const struct lu_name * lname, struct ldlm_reply * ldlm_rep) [static]
Definition at line 1331 of file mdt_handler.c.
References DISP_LOOKUP_NEG, DISP_LOOKUP_POS, ENTRY, fid_zero(), LASSERT, mdt_body::mbo_fid1, mdt_body::mbo_valid, mdo_lookup(), mdt_object_child(), mdt_set_disposition(), mdt_thread_info::mti_cross_ref, mdt_thread_info::mti_env, mdt_thread_info::mti_object, mdt_thread_info::mti_pill, mdt_thread_info::mti_spec, mdt_thread_info::mti_tmp_fid1, OBD_MD_FLID, req_capsule_server_get(), RETURN, and RMF_MDT_BODY.
Referenced by mdt_getattr_name_lock().
static int mdt_readpage (struct tgt_session_info * tsi) [static]
Definition at line 1736 of file mdt_handler.c.
References CERROR, ENTRY, err_serious(), EXIT, exp_connect_flags(), exp_max_brw_size(), GOTO, LPX64, LUDA_64BITHASH, mdt_body::mbo_mode, mdt_body::mbo_nlink, mdt_body::mbo_size, mdt_obj(), mdt_object_child(), mdt_th_info(), min_t, mo_readpage(), mdt_thread_info::mti_u, OBD_ALLOC, OBD_CONNECT_64BITHASH, OBD_FAIL_CHECK, OBD_FAIL_MDS_READPAGE_PACK, OBD_FAIL_MDS_SENDPAGE, OBD_FREE, mdt_thread_info::rdpg, req_capsule_server_get(), RETURN, RMF_MDT_BODY, lu_rdpg::rp_attrs, lu_rdpg::rp_count, lu_rdpg::rp_hash, lu_rdpg::rp_npages, lu_rdpg::rp_pages, tgt_sendpage(), tgt_session_info::tsi_corpus, tgt_session_info::tsi_env, tgt_session_info::tsi_exp, tgt_session_info::tsi_mdt_body, and tgt_session_info::tsi_pill.
static int mdt_register_lwp_callback (void * data) [static]
It will retrieve its FLDB entries from MDT0, and it only happens when upgrading existent FS to 2.6 or when local FLDB is corrupted, and it needs to refresh FLDB from the MDT0.
Definition at line 3710 of file mdt_handler.c.
References CERROR, ENTRY, fld_update_from_controller(), GOTO, LASSERT, LCT_MD_THREAD, lu_server_fld::lsf_new, lu_env_fini(), lu_env_init(), mdt_obd_name(), mdt_seq_site(), RETURN, seq_server_check_and_alloc_super(), and seq_server_site::ss_server_fld.
Referenced by mdt_register_seq_exp().
static int mdt_register_seq_exp (struct mdt_device * mdt) [static]
Definition at line 3746 of file mdt_handler.c.
References GOTO, lu_client_seq::lcs_exp, lu_server_fld::lsf_control_exp, lustre_deregister_lwp_item(), lustre_register_lwp_item(), MAX_OBD_NAME, mdt_obd_name(), mdt_register_lwp_callback(), mdt_seq_site(), OBD_ALLOC, OBD_FREE, seq_server_site::ss_client_seq, seq_server_site::ss_node_id, seq_server_site::ss_server_fld, and tgt_name2lwp_name().
Referenced by mdt_seq_init().
static int mdt_reint (struct tgt_session_info * tsi) [static]
Definition at line 1905 of file mdt_handler.c.
References ENTRY, mdt_reint_internal(), mdt_reint_opcode(), mdt_thread_info_fini(), OBD_FAIL_MDS_REINT_NET_REP, REINT_CREATE, REINT_LINK, REINT_MAX, REINT_MIGRATE, REINT_OPEN, REINT_RENAME, REINT_RMENTRY, REINT_SETATTR, REINT_SETXATTR, REINT_UNLINK, RETURN, RQF_MDS_REINT_CREATE, RQF_MDS_REINT_LINK, RQF_MDS_REINT_OPEN, RQF_MDS_REINT_RENAME, RQF_MDS_REINT_SETATTR, RQF_MDS_REINT_SETXATTR, RQF_MDS_REINT_UNLINK, tgt_ses_req(), tsi2mdt_info(), and tgt_session_info::tsi_reply_fail_id.
static int mdt_reint_internal (struct mdt_thread_info * info, struct mdt_lock_handle * lhc, __u32 op) [static]
Definition at line 1806 of file mdt_handler.c.
References CERROR, D_INODE, DEBUG_REQ, DEF_REP_MD_SIZE, ENTRY, err_serious(), EXIT, GOTO, LASSERT, lustre_msg_get_status(), mdt_body::mbo_aclsize, mdt_body::mbo_eadatasize, mdt_check_resent(), mdt_client_compatibility(), mdt_exit_ucred(), mdt_fix_attr_ucred(), mdt_fix_reply(), mdt_info_req(), mdt_init_ucred_reint(), mdt_reconstruct(), mdt_reint_rec(), mdt_reint_unpack(), mdt_thread_info::mti_pill, mdt_thread_info::mti_spec, md_op_spec::no_create, OBD_FAIL_MDS_REINT_DELAY, OBD_FAIL_TIMEOUT, RCL_SERVER, req_capsule_has_field(), req_capsule_server_get(), req_capsule_server_pack(), req_capsule_set_size(), RETURN, RMF_LOGCOOKIES, RMF_MDT_BODY, and RMF_MDT_MD.
Referenced by mdt_intent_reint(), and mdt_reint().
int mdt_reint_object_lock (struct mdt_thread_info * info, struct mdt_object * o, struct mdt_lock_handle * lh, __u64 ibits, bool cos_incompat)
Definition at line 2625 of file mdt_handler.c.
References LASSERT, LCK_EX, LCK_PW, mdt_object_lock_internal(), and mdt_lock_handle::mlh_reg_mode.
Referenced by mdt_attr_set(), mdt_lock_slaves(), mdt_md_create(), mdt_object_lock_save(), mdt_reint_link(), mdt_reint_migrate_internal(), mdt_reint_rename_internal(), and mdt_reint_unlink().
int mdt_reint_object_lock_try (struct mdt_thread_info * info, struct mdt_object * o, struct mdt_lock_handle * lh, __u64 ibits, bool cos_incompat)
Definition at line 2647 of file mdt_handler.c.
References LASSERT, LCK_EX, LCK_PW, mdt_object_lock_internal(), and mdt_lock_handle::mlh_reg_mode.
Referenced by mdt_lock_objects_in_linkea().
static long mdt_reint_opcode (struct ptlrpc_request * req, const struct req_format ** fmt) [static]
Definition at line 1879 of file mdt_handler.c.
References CERROR, ptlrpc_client::cli_name, D_INODE, DEBUG_REQ, err_serious(), obd_export::exp_obd, mdt_exp2dev(), mdt_device::mdt_ldlm_client, obd_device::obd_name, REINT_MAX, req_capsule_client_get(), req_capsule_extend(), RMF_REC_REINT, ptlrpc_request::rq_export, ptlrpc_request::rq_pill, and mdt_rec_reint::rr_opcode.
Referenced by mdt_intent_reint(), and mdt_reint().
int mdt_remote_blocking_ast (struct ldlm_lock * lock, struct ldlm_lock_desc * desc, void * data, int flag)
Definition at line 2366 of file mdt_handler.c.
References CDEBUG, D_INODE, ENTRY, LBUG, LCF_ASYNC, LDLM_CB_BLOCKING, LDLM_CB_CANCELING, ldlm_cli_cancel(), LDLM_DEBUG, ldlm_is_atomic_cb, ldlm_lock2handle(), RETURN, and tgt_discard_slc_lock().
Referenced by mdt_lock_slaves(), and mdt_remote_object_lock().
int mdt_remote_object_lock (struct mdt_thread_info * mti, struct mdt_object * o, const struct lu_fid * fid, struct lustre_handle * lh, enum ldlm_mode mode, __u64 ibits, bool nonblock)
Definition at line 2431 of file mdt_handler.c.
References ldlm_inodebits::bits, ldlm_enqueue_info::ei_cb_bl, ldlm_enqueue_info::ei_cb_cp, ldlm_enqueue_info::ei_enq_slave, ldlm_enqueue_info::ei_mode, ldlm_enqueue_info::ei_nonblock, ldlm_enqueue_info::ei_type, ENTRY, fid_build_reg_res_name(), ldlm_policy_data::l_inodebits, LASSERT, ldlm_completion_ast(), LDLM_IBITS, mdt_object_child(), mdt_object_remote(), mdt_remote_blocking_ast(), mo_object_lock(), mdt_thread_info::mti_einfo, mdt_thread_info::mti_env, mdt_thread_info::mti_policy, mdt_thread_info::mti_res_id, and RETURN.
Referenced by mdt_object_lock_internal(), mdt_reint_migrate_internal(), mdt_reint_rename_internal(), mdt_reint_unlink(), and mdt_rename_lock().
static int mdt_rpc_fid2path (struct mdt_thread_info * info, void * key, int keylen, void * val, int vallen) [static]
Definition at line 5696 of file mdt_handler.c.
References cfs_size_round(), fid_is_sane(), getinfo_fid2path::gf_pathlen, getinfo_fid2path::gf_root_fid, getinfo_fid2path::gf_u, KEY_FID2PATH, lustre_swab_fid2path(), lustre_swab_lu_fid, mdt_fid2path(), mdt_thread_info::mti_pill, ptlrpc_req_need_swab(), req_capsule::rc_req, and RETURN.
Referenced by mdt_get_info().
static void mdt_save_lock (struct mdt_thread_info * info, struct lustre_handle * h, enum ldlm_mode mode, int decref) [static]
Save a lock within request object.
Keep the lock referenced until whether client ACK or transaction commit happens or release the lock immediately depending on input parameters. If COS is ON, a write lock is converted to COS lock before saving.
Parameters:
info thead info object
h lock handle
mode lock mode
decref force immediate lock releasing
Definition at line 2675 of file mdt_handler.c.
References CDEBUG, lustre_handle::cookie, D_HA, ENTRY, EXIT, LASSERTF, LCK_COS, LCK_EX, LCK_PW, ldlm_handle2lock(), ldlm_lock_downgrade(), LDLM_LOCK_PUT, likely, LPD64, LPX64, lustre_handle_is_used(), mdt_cos_is_enabled(), mdt_device_commit_async(), mdt_fid_unlock(), mdt_info_req(), mdt_is_lock_sync(), mdt_slc_is_enabled(), mdt_thread_info::mti_env, mdt_thread_info::mti_has_trans, mdt_thread_info::mti_mdt, ptlrpc_save_lock(), and ptlrpc_request::rq_transno.
Referenced by mdt_object_unlock().
static void mdt_save_remote_lock (struct mdt_thread_info * info, struct lustre_handle * h, enum ldlm_mode mode, int decref) [static]
Save cross-MDT lock in uncommitted_slc_locks.
Keep the lock referenced until transaction commit happens or release the lock immediately depending on input parameters.
Parameters:
info thead info object
h lock handle
mode lock mode
decref force immediate lock releasing
Definition at line 2735 of file mdt_handler.c.
References lustre_handle::cookie, ENTRY, EXIT, LASSERT, LCK_EX, LCK_PW, ldlm_handle2lock(), ldlm_lock_decref(), ldlm_lock_decref_and_cancel(), lustre_handle_is_used(), mdt_info_req(), mdt_thread_info::mti_has_trans, ptlrpc_request::rq_transno, and tgt_save_slc_lock().
Referenced by mdt_object_unlock().
static int mdt_sec_ctx_handle (struct tgt_session_info * tsi) [static]
Definition at line 2170 of file mdt_handler.c.
References CFS_FAIL_TIMEOUT, cfs_fail_val, lustre_msg_get_opc(), mdt_handle_idmap(), OBD_FAIL_SEC_CTX_HDL_PAUSE, ptlrpc_request::rq_reqmsg, SEC_CTX_INIT, SEC_CTX_INIT_CONT, sptlrpc_svc_ctx_invalidate(), tgt_ses_req(), and unlikely.
static int mdt_seq_fini (const struct lu_env * env, struct mdt_device * mdt) [static]
Definition at line 3697 of file mdt_handler.c.
References mdt_deregister_seq_exp(), mdt_seq_fini_cli(), mdt_seq_site(), and seq_site_fini().
Referenced by mdt_fini(), mdt_init0(), and mdt_seq_init().
static void mdt_seq_fini_cli (struct mdt_device * mdt) [static]
Definition at line 3686 of file mdt_handler.c.
References mdt_seq_site(), seq_server_set_cli(), and seq_server_site::ss_server_seq.
Referenced by mdt_seq_fini().
static int mdt_seq_init (const struct lu_env * env, struct mdt_device * mdt) [static]
Definition at line 3824 of file mdt_handler.c.
References ENTRY, EXIT, GOTO, LUSTRE_SEQ_CONTROLLER, LUSTRE_SEQ_SERVER, mdt_device::mdt_bottom, mdt_obd_name(), mdt_register_seq_exp(), mdt_seq_fini(), mdt_seq_init_cli(), mdt_seq_site(), OBD_ALLOC_PTR, RETURN, seq_server_init(), seq_server_site::ss_control_seq, seq_server_site::ss_node_id, and seq_server_site::ss_server_seq.
Referenced by mdt_init0().
static int mdt_seq_init_cli (const struct lu_env * env, struct mdt_device * mdt) [static]
Definition at line 3787 of file mdt_handler.c.
References ENTRY, LUSTRE_SEQ_METADATA, MAX_OBD_NAME, mdt_obd_name(), mdt_seq_site(), OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, RETURN, seq_client_init(), seq_server_set_cli(), seq_server_site::ss_client_seq, seq_server_site::ss_control_seq, seq_server_site::ss_node_id, and seq_server_site::ss_server_seq.
Referenced by mdt_seq_init().
void mdt_set_disposition (struct mdt_thread_info * info, struct ldlm_reply * rep, __u64 op_flag)
Definition at line 152 of file mdt_handler.c.
References ldlm_reply::lock_policy_res1, mdt_thread_info::mti_env, mdt_thread_info::mti_opdata, and tgt_opdata_set().
Referenced by mdt_finish_open(), mdt_getattr_name_lock(), mdt_intent_getattr(), mdt_intent_reint(), mdt_mfd_open(), mdt_open_by_fid(), mdt_open_by_fid_lock(), mdt_raw_lookup(), mdt_reconstruct_open(), and mdt_reint_open().
static int mdt_set_info (struct tgt_session_info * tsi) [static]
Definition at line 1675 of file mdt_handler.c.
References __swab32s, __swab64s, CERROR, changelog_setinfo::cs_id, changelog_setinfo::cs_recno, D_HA, DEBUG_REQ, ENTRY, err_serious(), exp_connect_flags_ptr(), obd_export::exp_lock, obd_export::exp_obd, KEY_CHANGELOG_CLEAR, KEY_EVICT_BY_NID, KEY_IS, KEY_READ_ONLY, mdt_iocontrol(), OBD_CONNECT_RDONLY, obd_export_evict_by_nid(), OBD_IOC_CHANGELOG_CLEAR, ptlrpc_req_need_swab(), RCL_CLIENT, req_capsule_client_get(), req_capsule_get_size(), RETURN, RMF_SETINFO_KEY, RMF_SETINFO_VAL, ptlrpc_request::rq_export, tgt_name(), tgt_ses_req(), tgt_session_info::tsi_pill, and tgt_session_info::tsi_tgt.
static void mdt_set_lock_sync (struct ldlm_lock * lock) [inline, static]
Mark the lock as "synchonous".
Mark the lock to deffer transaction commit to the unlock time.
Parameters:
lock the lock to mark as "synchonous"
See also:
mdt_is_lock_sync
mdt_save_lock
Definition at line 2275 of file mdt_handler.c.
References ldlm_lock::l_ast_data.
Referenced by mdt_blocking_ast().
static void mdt_stack_fini (const struct lu_env * env, struct mdt_device * m, struct lu_device * top) [static]
Definition at line 3948 of file mdt_handler.c.
References mdt_thread_info::bufs, ENTRY, LASSERT, LCFG_CLEANUP, lu_device::ld_ops, lu_device::ld_site, lu_device_operations::ldo_process_config, lu_env::le_ctx, lu_context_key_get(), lu_dev_del_linkage(), lu_site_purge(), lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), mdt2obd_dev(), mdt_device::mdt_bottom, mdt_device::mdt_bottom_exp, mdt_device::mdt_child, mdt_device::mdt_child_exp, mdt_obd_name(), mdt_thread_key, mdt_thread_info::mti_u, obd_disconnect(), obd_device::obd_fail, obd_device::obd_force, and RETURN_EXIT.
Referenced by mdt_fini(), and mdt_init0().
static int mdt_stack_init (const struct lu_env * env, struct mdt_device * mdt, struct lustre_cfg * cfg) [static]
Definition at line 4029 of file mdt_handler.c.
References CERROR, class_attach(), class_detach(), class_get_profile(), class_name2obd(), class_put_profile(), class_setup(), ENTRY, EXIT, obd_export::exp_obd, GOTO, LASSERT, LCFG_ATTACH, LCFG_SETUP, lu_device::ld_site, lustre_profile::lp_dt, lu_site::ls_top_dev, lu2dt_dev(), lu2md_dev(), lu_dev_add_linkage(), lu_env_refill(), lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), lustre_cfg_string(), LUSTRE_MDD_NAME, MAX_OBD_NAME, MDD_OBD_NAME, mdt_device::mdt_bottom, mdt_device::mdt_bottom_exp, mdt_device::mdt_child, mdt_device::mdt_child_exp, mdt_connect_to_next(), mdt_device::mdt_lu_dev, mdt_lu_site(), name, OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, obd_device::obd_lu_dev, RETURN, and uuid.
Referenced by mdt_init0().
static void mdt_stack_pre_fini (const struct lu_env * env, struct mdt_device * m, struct lu_device * top) [static]
Definition at line 3914 of file mdt_handler.c.
References mdt_thread_info::bufs, ENTRY, EXIT, obd_export::exp_obd, LASSERT, LCFG_PRE_CLEANUP, lu_device::ld_ops, lu_device_operations::ldo_process_config, lu_env::le_ctx, lu_context_key_get(), lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), mdt_device::mdt_child_exp, mdt_obd_name(), mdt_thread_key, mdt_thread_info::mti_u, and RETURN_EXIT.
Referenced by mdt_fini().
static int mdt_statfs (struct tgt_session_info * tsi) [static]
statfs information are cached in the mdt_device
statfs data is too old, get up-to-date one
use cached statfs data
Definition at line 391 of file mdt_handler.c.
References at_get(), cfs_time_before_64(), cfs_time_current_64, cfs_time_shift_64(), ENTRY, err_serious(), GOTO, LPROC_MDT_STATFS, md_device::md_ops, md_device_operations::mdo_statfs, mdt_check_ucred(), mdt_device::mdt_child, mdt_counter_incr(), mdt_device::mdt_osfs, mdt_device::mdt_osfs_age, mdt_device::mdt_osfs_lock, MDT_SERVICE_WATCHDOG_FACTOR, mdt_thread_info_fini(), mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, mdt_thread_info::mti_pill, OBD_FAIL_CHECK, OBD_FAIL_MDS_STATFS_LCW_SLEEP, OBD_FAIL_MDS_STATFS_PACK, OBD_FAIL_TIMEOUT, OBD_STATFS_CACHE_SECONDS, req_capsule_server_get(), RETURN, RMF_OBD_STATFS, ptlrpc_service_part::scp_at_estimate, tgt_ses_req(), and tsi2mdt_info().
int mdt_stripe_get (struct mdt_thread_info * info, struct mdt_object * o, struct md_attr * ma, const char * name)
Definition at line 697 of file mdt_handler.c.
References exp_connect_flags(), LASSERT, lu_buf::lb_buf, lu_buf::lb_len, le32_to_cpu, LOV_PATTERN_F_HOLE, md_attr::ma_lmm, md_attr::ma_lmm_size, MA_LMV, md_attr::ma_lmv, MA_LMV_DEF, md_attr::ma_lmv_size, MA_LOV, md_attr::ma_valid, mdt_big_xattr_get(), mdt_device::mdt_max_mdsize, mdt_object_child(), mo_xattr_get(), mdt_thread_info::mti_big_lmm, mdt_thread_info::mti_big_lmm_used, mdt_thread_info::mti_buf, mdt_thread_info::mti_env, mdt_thread_info::mti_exp, mdt_thread_info::mti_mdt, OBD_CONNECT_LFSCK, unlikely, XATTR_NAME_DEFAULT_LMV, XATTR_NAME_LMV, and XATTR_NAME_LOV.
Referenced by mdt_attr_get_complex(), mdt_getattr_internal(), and mdt_reint_migrate_internal().
static int mdt_swap_layouts (struct tgt_session_info * tsi) [static]
Definition at line 1240 of file mdt_handler.c.
References ENTRY, exp_connect_layout(), GOTO, LATF_SKIP, LCK_EX, lu_fid_cmp(), mdt_body::mbo_fid1, mdt_body::mbo_fid2, MDS_INODELOCK_LAYOUT, MDS_INODELOCK_XATTR, MDT_LH_NEW, MDT_LH_OLD, mdt_lock_reg_init(), mdt_object_child(), mdt_object_exists(), mdt_object_find(), mdt_object_lock(), mdt_object_put(), mdt_object_remote(), mdt_object_unlock(), mdt_swap_lov_flag(), mdt_thread_info_fini(), mo_permission(), mo_swap_layouts(), mdc_swap_layouts::msl_flags, mdt_thread_info::mti_body, mdt_thread_info::mti_dlm_req, mdt_thread_info::mti_env, mdt_thread_info::mti_lh, mdt_thread_info::mti_mdt, mdt_thread_info::mti_object, mdt_thread_info::mti_pill, req_capsule_client_get(), RETURN, RMF_SWAP_LAYOUTS, ptlrpc_request::rq_export, swap, tgt_ses_req(), tsi2mdt_info(), and unlikely.
static void mdt_swap_lov_flag (struct mdt_object * o1, struct mdt_object * o2) [static]
Exchange MOF_LOV_CREATED flags between two objects after a layout swap.
No assumption is made on whether o1 or o2 have created objects or not.
Parameters:
[in,out] o1 First swap layout object
[in,out] o2 Second swap layout object
Definition at line 1222 of file mdt_handler.c.
References __u64, MOF_LOV_CREATED, mdt_object::mot_flags, and mdt_object::mot_lov_mutex.
Referenced by mdt_swap_layouts().
static int mdt_sync (struct tgt_session_info * tsi) [static]
Definition at line 1970 of file mdt_handler.c.
References ENTRY, err_serious(), LPROC_MDT_SYNC, md_attr::ma_attr, MA_INODE, md_attr::ma_need, md_attr::ma_valid, mdt_body::mbo_fid1, mdt_attr_get_complex(), mdt_counter_incr(), mdt_device_sync(), mdt_exp2dev(), mdt_object_fid(), mdt_object_sync(), mdt_pack_attr2body(), mdt_thread_info_fini(), mdt_thread_info::mti_attr, mdt_thread_info::mti_object, OBD_FAIL_CHECK, OBD_FAIL_MDS_SYNC_PACK, req_capsule_server_get(), RETURN, RMF_MDT_BODY, tgt_ses_req(), tsi2mdt_info(), tgt_session_info::tsi_env, tgt_session_info::tsi_exp, tgt_session_info::tsi_mdt_body, and tgt_session_info::tsi_pill.
static int mdt_tgt_connect (struct tgt_session_info * tsi) [static]
Definition at line 2986 of file mdt_handler.c.
References cfs_fail_val, class_export_get(), ENTRY, GOTO, mdt_init_idmap(), obd_disconnect(), OBD_FAIL_CHECK, OBD_FAIL_TGT_DELAY_CONDITIONAL, RETURN, ptlrpc_request::rq_export, tgt_connect(), tgt_ses_req(), and tsi2mdt_info().
static int mdt_tgt_getxattr (struct tgt_session_info * tsi) [static]
Definition at line 4329 of file mdt_handler.c.
References mdt_getxattr(), mdt_thread_info_fini(), and tsi2mdt_info().
void mdt_thread_info_fini (struct mdt_thread_info * info)
Definition at line 2949 of file mdt_handler.c.
References ARRAY_SIZE, lu_buf::lb_buf, lu_buf_free(), mdt_lock_handle_fini(), mdt_object_put(), mdt_thread_info::mti_big_buf, mdt_thread_info::mti_env, mdt_thread_info::mti_exp, mdt_thread_info::mti_lh, mdt_thread_info::mti_object, mdt_thread_info::mti_pill, and unlikely.
Referenced by mdt_close(), mdt_get_info(), mdt_get_root(), mdt_getattr(), mdt_getattr_name(), mdt_hsm_action(), mdt_hsm_ct_register(), mdt_hsm_ct_unregister(), mdt_hsm_progress(), mdt_hsm_request(), mdt_hsm_state_get(), mdt_hsm_state_set(), mdt_intent_policy(), mdt_reint(), mdt_statfs(), mdt_swap_layouts(), mdt_sync(), and mdt_tgt_getxattr().
void mdt_thread_info_init (struct ptlrpc_request * req, struct mdt_thread_info * info)
Definition at line 2910 of file mdt_handler.c.
References ARRAY_SIZE, obd_export::exp_obd, LU_BUF_NULL, lustre_msg_get_transno(), mdt_dev(), mdt_lock_handle_init(), mdt_thread_info::mti_attr, mdt_thread_info::mti_big_buf, mdt_thread_info::mti_big_lmm_used, mdt_thread_info::mti_body, mdt_thread_info::mti_cross_ref, mdt_thread_info::mti_dlm_req, mdt_thread_info::mti_env, mdt_thread_info::mti_exp, mdt_thread_info::mti_has_trans, mdt_thread_info::mti_lh, mdt_thread_info::mti_mdt, mdt_thread_info::mti_object, mdt_thread_info::mti_opdata, mdt_thread_info::mti_pill, mdt_thread_info::mti_spec, mdt_thread_info::mti_transno, md_op_spec::no_create, obd_device::obd_lu_dev, ptlrpc_request::rq_export, ptlrpc_request::rq_pill, ptlrpc_request::rq_reqmsg, md_op_spec::sp_ea, md_op_spec::sp_migrate_close, md_op_spec::sp_permitted, md_op_spec::sp_rm_entry, and md_op_spec::u.
Referenced by tsi2mdt_info().
struct lu_ucred* mdt_ucred (const struct mdt_thread_info * info) [read]
Definition at line 6063 of file mdt_handler.c.
References lu_ucred(), and mdt_thread_info::mti_env.
Referenced by __mdt_init_ucred(), hsm_action_permission(), mdt_body_reverse_idmap(), mdt_check_ucred(), mdt_create_unpack(), mdt_ctxt_add_dirty_flag(), mdt_exit_ucred(), mdt_getxattr_all(), mdt_hsm_add_actions(), mdt_hsm_cdt_init(), mdt_hsm_is_admin(), mdt_hsm_state_set(), mdt_hsm_update_request_state(), mdt_init_ucred_reint(), mdt_link_unpack(), mdt_open_unpack(), mdt_reint_setxattr(), mdt_reint_unlink(), mdt_remote_permission_check(), mdt_rename_unpack(), mdt_rmtlsetfacl(), mdt_root_squash(), mdt_setattr_unpack_rec(), mdt_setxattr_unpack(), mdt_unlink_unpack(), new_init_ucred(), old_init_ucred(), old_init_ucred_common(), and old_init_ucred_reint().
struct lu_ucred* mdt_ucred_check (const struct mdt_thread_info * info) [read]
Definition at line 6068 of file mdt_handler.c.
References lu_ucred_check(), and mdt_thread_info::mti_env.
Referenced by mdt_fix_attr_ucred(), and mdt_pack_remote_perm().
static int mdt_unpack_req_pack_rep (struct mdt_thread_info * info, __u32 flags) [static]
Definition at line 2863 of file mdt_handler.c.
References DEF_REP_MD_SIZE, ENTRY, HABEO_REFERO, mdt_body_unpack(), mdt_thread_info::mti_pill, RCL_CLIENT, RCL_SERVER, req_capsule_has_field(), req_capsule_server_pack(), req_capsule_set_size(), RETURN, RMF_LOGCOOKIES, RMF_MDT_BODY, and RMF_MDT_MD.
Referenced by mdt_intent_opc().
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Metadata Target ("LUSTRE_MDT_NAME")")
module_exit (mdt_exit)
module_init (mdt_init)
MODULE_LICENSE ("GPL")
module_param (max_mod_rpcs_per_client , uint , 0644)
MODULE_PARM_DESC (max_mod_rpcs_per_client , "maximum number of modify RPCs in flight allowed per client")
MODULE_VERSION (LUSTRE_VERSION_STRING)
struct mdt_thread_info* tsi2mdt_info (struct tgt_session_info * tsi) [read]
Definition at line 2968 of file mdt_handler.c.
References LASSERT, lu_object_get(), mdt_obj(), mdt_th_info(), mdt_thread_info_init(), mdt_thread_info::mti_body, mdt_thread_info::mti_dlm_req, mdt_thread_info::mti_object, tgt_ses_req(), tgt_session_info::tsi_corpus, tgt_session_info::tsi_dlm_req, tgt_session_info::tsi_env, and tgt_session_info::tsi_mdt_body.
Referenced by mdt_close(), mdt_get_info(), mdt_get_root(), mdt_getattr(), mdt_getattr_name(), mdt_hsm_action(), mdt_hsm_ct_register(), mdt_hsm_ct_unregister(), mdt_hsm_progress(), mdt_hsm_request(), mdt_hsm_state_get(), mdt_hsm_state_set(), mdt_intent_policy(), mdt_reint(), mdt_statfs(), mdt_swap_layouts(), mdt_sync(), mdt_tgt_connect(), and mdt_tgt_getxattr().
Variable Documentation
unsigned int max_mod_rpcs_per_client = 8 [static]
Definition at line 73 of file mdt_handler.c.
Referenced by mdt_connect_internal().
struct lu_kmem_descr mdt_caches[] [static]
Initial value:
 {
        {
                .ckd_cache = &mdt_object_kmem,
                .ckd_name  = "mdt_obj",
                .ckd_size  = sizeof(struct mdt_object)
        },
        {
                .ckd_cache      = &mdt_hsm_cdt_kmem,
                .ckd_name       = "mdt_cdt_restore_handle",
                .ckd_size       = sizeof(struct cdt_restore_handle)
        },
        {
                .ckd_cache      = &mdt_hsm_car_kmem,
                .ckd_name       = "mdt_cdt_agent_req",
                .ckd_size       = sizeof(struct cdt_agent_req)
        },
        {
                .ckd_cache = NULL
        }
}
Definition at line 113 of file mdt_handler.c.
struct tgt_opc_slice mdt_common_slice[] [static]
Definition at line 4390 of file mdt_handler.c.
Referenced by mdt_init0().
struct lu_device_type mdt_device_type [static]
Initial value:
 {
        .ldt_tags     = LU_DEVICE_MD,
        .ldt_name     = LUSTRE_MDT_NAME,
        .ldt_ops      = &mdt_device_type_ops,
        .ldt_ctx_tags = LCT_MD_THREAD
}
Definition at line 6115 of file mdt_handler.c.
Referenced by mdt_init().
struct lu_device_type_operations mdt_device_type_ops [static]
Initial value:
 {
        .ldto_device_alloc = mdt_device_alloc,
        .ldto_device_free  = mdt_device_free,
        .ldto_device_fini  = mdt_device_fini
}
Definition at line 6109 of file mdt_handler.c.
enum ldlm_mode mdt_dlm_lock_modes[]
Initial value:
 {
        [MDL_MINMODE]   = LCK_MINMODE,
        [MDL_EX]        = LCK_EX,
        [MDL_PW]        = LCK_PW,
        [MDL_PR]        = LCK_PR,
        [MDL_CW]        = LCK_CW,
        [MDL_CR]        = LCK_CR,
        [MDL_NL]        = LCK_NL,
        [MDL_GROUP]     = LCK_GROUP
}
Definition at line 88 of file mdt_handler.c.
Referenced by mdt_mdl_mode2dlm_mode().
struct kmem_cache* mdt_hsm_car_kmem
Definition at line 111 of file mdt_handler.c.
Referenced by mdt_cdt_alloc_request(), and mdt_cdt_free_request().
struct kmem_cache* mdt_hsm_cdt_kmem
Definition at line 108 of file mdt_handler.c.
Referenced by hsm_cdt_request_completed(), hsm_restore_cb(), mdt_hsm_add_actions(), mdt_hsm_agent_send(), and mdt_hsm_cdt_stop().
struct cfg_interop_param mdt_interop_param[] [static]
Initial value:
 {
        { "mdt.group_upcall",   NULL },
        { "mdt.quota_type",     NULL },
        { "mdd.quota_type",     NULL },
        { "mdt.som",            NULL },
        { "mdt.rootsquash",     "mdt.root_squash" },
        { "mdt.nosquash_nid",   "mdt.nosquash_nids" },
        { NULL }
}
Definition at line 4754 of file mdt_handler.c.
Referenced by mdt_process_config().
struct lu_device_operations mdt_lu_ops
Initial value:
 {
        .ldo_object_alloc   = mdt_object_alloc,
        .ldo_process_config = mdt_process_config,
        .ldo_prepare        = mdt_prepare,
}
Definition at line 4967 of file mdt_handler.c.
Referenced by mdt_init0().
mdl_mode_t mdt_mdl_lock_modes[]
Initial value:
 {
        [LCK_MINMODE] = MDL_MINMODE,
        [LCK_EX]      = MDL_EX,
        [LCK_PW]      = MDL_PW,
        [LCK_PR]      = MDL_PR,
        [LCK_CW]      = MDL_CW,
        [LCK_CR]      = MDL_CR,
        [LCK_NL]      = MDL_NL,
        [LCK_GROUP]   = MDL_GROUP
}
Definition at line 77 of file mdt_handler.c.
Referenced by mdt_dlm_mode2mdl_mode().
struct obd_ops mdt_obd_device_ops [static]
Initial value:
 {
        .o_owner          = THIS_MODULE,
        .o_set_info_async = mdt_obd_set_info_async,
        .o_connect        = mdt_obd_connect,
        .o_reconnect      = mdt_obd_reconnect,
        .o_disconnect     = mdt_obd_disconnect,
        .o_init_export    = mdt_init_export,
        .o_destroy_export = mdt_destroy_export,
        .o_iocontrol      = mdt_iocontrol,
        .o_postrecov      = mdt_obd_postrecov,
}
Definition at line 5987 of file mdt_handler.c.
Referenced by mdt_init().
static struct lu_object_operations mdt_obj_ops [static, read]
Initial value:
 {
        .loo_object_init    = mdt_object_init,
        .loo_object_free    = mdt_object_free,
        .loo_object_print   = mdt_object_print
}
Definition at line 102 of file mdt_handler.c.
Referenced by mdt_object_alloc().
struct kmem_cache* mdt_object_kmem [static]
Definition at line 105 of file mdt_handler.c.
Referenced by mdt_object_alloc(), and mdt_object_free().
struct tgt_handler mdt_quota_ops[] [static]
Initial value:
 {
TGT_QUOTA_HDL(HABEO_REFERO,             QUOTA_DQACQ,      mdt_quota_dqacq),
}
Definition at line 4386 of file mdt_handler.c.
struct tgt_handler mdt_sec_ctx_ops[] [static]
Initial value:
 {
TGT_SEC_HDL_VAR(0,                      SEC_CTX_INIT,     mdt_sec_ctx_handle),
TGT_SEC_HDL_VAR(0,                      SEC_CTX_INIT_CONT,mdt_sec_ctx_handle),
}
Definition at line 4380 of file mdt_handler.c.
struct tgt_handler mdt_tgt_handlers[] [static]
Definition at line 4340 of file mdt_handler.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.