Lustre: lustre/mdt/mdt_lvb.c File Reference
lustre/mdt/mdt_lvb.c File Reference
#include "mdt_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_MDS
Functions
static int mdt_lvbo_init (struct ldlm_resource *res)
static int mdt_lvbo_update (struct ldlm_resource *res, struct ptlrpc_request *req, int increase_only)
static int mdt_lvbo_size (struct ldlm_lock *lock)
static int mdt_lvbo_fill (struct ldlm_lock *lock, void *lvb, int lvblen)
static int mdt_lvbo_free (struct ldlm_resource *res)
Variables
struct ldlm_valblock_ops mdt_lvbo
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 32 of file mdt_lvb.c.
Function Documentation
static int mdt_lvbo_fill (struct ldlm_lock * lock, void * lvb, int lvblen) [static]
Definition at line 95 of file mdt_lvb.c.
References CERROR, ENTRY, fid_extract_from_res_name(), GOTO, IS_LQUOTA_RES, ldlm_lock::l_export, ldlm_lock::l_granted_mode, ldlm_lock::l_req_mode, ldlm_lock::l_resource, lu_buf::lb_buf, lu_buf::lb_len, LCT_MD_THREAD, ldlm_has_layout(), ldlm_lock_to_ns(), lu_env::le_ctx, ldlm_resource::lr_name, LU_BUF_NULL, lu_context_key_get(), lu_env_fini(), lu_env_init(), mdt_obd_name(), mdt_object_child(), mdt_object_exists(), mdt_object_find(), mdt_object_put(), mdt_object_remote(), mdt_device::mdt_qmt_dev, mdt_thread_key, mo_xattr_get(), mdt_thread_info::mti_buf, mdt_thread_info::mti_env, mdt_thread_info::mti_exp, mdt_thread_info::mti_mdt, mdt_thread_info::mti_tmp_fid2, ldlm_namespace::ns_lvbp, qmt_hdls, qmt_handlers::qmth_lvbo_fill, RETURN, and XATTR_NAME_LOV.
static int mdt_lvbo_free (struct ldlm_resource * res) [static]
Definition at line 183 of file mdt_lvb.c.
References IS_LQUOTA_RES, ldlm_res_to_ns(), mdt_device::mdt_qmt_dev, ldlm_namespace::ns_lvbp, qmt_hdls, and qmt_handlers::qmth_lvbo_free.
static int mdt_lvbo_init (struct ldlm_resource * res) [static]
Definition at line 37 of file mdt_lvb.c.
References IS_LQUOTA_RES, ldlm_res_to_ns(), mdt_device::mdt_qmt_dev, ldlm_namespace::ns_lvbp, qmt_hdls, and qmt_handlers::qmth_lvbo_init.
static int mdt_lvbo_size (struct ldlm_lock * lock) [static]
Definition at line 73 of file mdt_lvb.c.
References IS_LQUOTA_RES, ldlm_lock::l_resource, LASSERT, ldlm_has_layout(), ldlm_res_to_ns(), mdt_device::mdt_max_mdsize, mdt_device::mdt_qmt_dev, ldlm_namespace::ns_lvbp, qmt_hdls, and qmt_handlers::qmth_lvbo_size.
static int mdt_lvbo_update (struct ldlm_resource * res, struct ptlrpc_request * req, int increase_only) [static]
Definition at line 53 of file mdt_lvb.c.
References IS_LQUOTA_RES, ldlm_res_to_ns(), mdt_device::mdt_qmt_dev, ldlm_namespace::ns_lvbp, qmt_hdls, and qmt_handlers::qmth_lvbo_update.
Variable Documentation
struct ldlm_valblock_ops mdt_lvbo
Initial value:
 {
        lvbo_init:      mdt_lvbo_init,
        lvbo_update:    mdt_lvbo_update,
        lvbo_size:      mdt_lvbo_size,
        lvbo_fill:      mdt_lvbo_fill,
        lvbo_free:      mdt_lvbo_free
}
Definition at line 199 of file mdt_lvb.c.
Referenced by mdt_init0().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.