Lustre: lustre/mdt/mdt_open.c File Reference
lustre/mdt/mdt_open.c File Reference
#include <lustre_acl.h>
#include <lustre_mds.h>
#include "mdt_internal.h"
#include <lustre_nodemap.h>
Defines
#define DEBUG_SUBSYSTEM S_MDS
#define MFD_CLOSED(mode) ((mode) == MDS_FMODE_CLOSED)
Functions
static void mdt_mfd_get (void *mfdp)
struct mdt_file_data * mdt_mfd_new (const struct mdt_export_data *med)
struct mdt_file_data * mdt_handle2mfd (struct mdt_export_data *med, const struct lustre_handle *handle, bool is_replay_or_resent)
void mdt_mfd_free (struct mdt_file_data *mfd)
static int mdt_create_data (struct mdt_thread_info *info, struct mdt_object *p, struct mdt_object *o)
int mdt_write_read (struct mdt_object *o)
int mdt_write_get (struct mdt_object *o)
void mdt_write_put (struct mdt_object *o)
static int mdt_write_deny (struct mdt_object *o)
static void mdt_write_allow (struct mdt_object *o)
static void mdt_empty_transno (struct mdt_thread_info *info, int rc)
void mdt_mfd_set_mode (struct mdt_file_data *mfd, __u64 mode)
static void mdt_prep_ma_buf_from_rep (struct mdt_thread_info *info, struct mdt_object *obj, struct md_attr *ma)
prep ma_lmm/ma_lmv for md_attr from reply
static int mdt_mfd_open (struct mdt_thread_info *info, struct mdt_object *p, struct mdt_object *o, __u64 flags, int created, struct ldlm_reply *rep)
static int mdt_finish_open (struct mdt_thread_info *info, struct mdt_object *p, struct mdt_object *o, __u64 flags, int created, struct ldlm_reply *rep)
void mdt_reconstruct_open (struct mdt_thread_info *info, struct mdt_lock_handle *lhc)
static int mdt_open_by_fid (struct mdt_thread_info *info, struct ldlm_reply *rep)
static int mdt_object_open_lock (struct mdt_thread_info *info, struct mdt_object *obj, struct mdt_lock_handle *lhc, __u64 *ibits)
static void mdt_object_open_unlock (struct mdt_thread_info *info, struct mdt_object *obj, struct mdt_lock_handle *lhc, __u64 ibits, int rc)
static bool mdt_hsm_release_allow (const struct md_attr *ma)
Check release is permitted for the current HSM flags.
static int mdt_open_by_fid_lock (struct mdt_thread_info *info, struct ldlm_reply *rep, struct mdt_lock_handle *lhc)
static int mdt_cross_open (struct mdt_thread_info *info, const struct lu_fid *parent_fid, const struct lu_fid *fid, struct ldlm_reply *rep, __u32 flags)
int mdt_reint_open (struct mdt_thread_info *info, struct mdt_lock_handle *lhc)
static struct mdt_object * mdt_orphan_open (struct mdt_thread_info *info, struct mdt_device *mdt, const struct lu_fid *fid, struct md_attr *attr, fmode_t fmode)
Create an orphan object use local root.
static int mdt_hsm_release (struct mdt_thread_info *info, struct mdt_object *o, struct md_attr *ma)
int mdt_close_swap_layouts (struct mdt_thread_info *info, struct mdt_object *o, struct md_attr *ma)
static int mdt_mfd_closed (struct mdt_file_data *mfd)
int mdt_mfd_close (struct mdt_thread_info *info, struct mdt_file_data *mfd)
int mdt_close_internal (struct mdt_thread_info *info, struct ptlrpc_request *req, struct mdt_body *repbody)
int mdt_close (struct tgt_session_info *tsi)
Variables
static struct portals_handle_ops mfd_handle_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 43 of file mdt_open.c.
#define MFD_CLOSED (mode) ((mode) == MDS_FMODE_CLOSED)
Definition at line 1933 of file mdt_open.c.
Referenced by mdt_mfd_close(), and mdt_mfd_closed().
Function Documentation
int mdt_close (struct tgt_session_info * tsi)
Definition at line 2047 of file mdt_open.c.
References ENTRY, err_serious(), GOTO, LPROC_MDT_CLOSE, lustre_msg_get_status(), MA_INODE, md_attr::ma_lmm, md_attr::ma_lmm_size, MA_LOV, md_attr::ma_need, mdt_body::mbo_aclsize, mdt_body::mbo_eadatasize, mdt_check_resent(), mdt_client_compatibility(), mdt_close_internal(), mdt_close_unpack(), mdt_counter_incr(), mdt_empty_transno(), mdt_exit_ucred(), mdt_fix_reply(), mdt_reconstruct_generic(), mdt_thread_info_fini(), mdt_thread_info::mti_attr, mdt_thread_info::mti_pill, OBD_FAIL_CHECK, OBD_FAIL_CHECK_RESET, OBD_FAIL_MDS_CLOSE_NET_REP, OBD_FAIL_MDS_CLOSE_PACK, RCL_SERVER, req_capsule_get_size(), req_capsule_server_get(), req_capsule_server_pack(), req_capsule_set_size(), ret, RETURN, RMF_LOGCOOKIES, RMF_MDT_BODY, RMF_MDT_MD, ptlrpc_request::rq_repmsg, tgt_ses_req(), tsi2mdt_info(), and tgt_session_info::tsi_reply_fail_id.
int mdt_close_internal (struct mdt_thread_info * info, struct ptlrpc_request * req, struct mdt_body * repbody)
not serious error since bug 3633
Definition at line 2009 of file mdt_open.c.
References CDEBUG, class_handle_unhash(), lustre_handle::cookie, D_INODE, DFID, ENTRY, list_del_init(), LPX64, mdt_handle2mfd(), mdt_handle_last_unlink(), mdt_mfd_close(), mdt_mfd_closed(), mdt_object_get(), mdt_object_put(), mdt_export_data::med_open_lock, mdt_file_data::mfd_handle, mdt_file_data::mfd_list, mdt_file_data::mfd_object, mdt_thread_info::mti_attr, mdt_thread_info::mti_close_handle, mdt_thread_info::mti_env, mdt_thread_info::mti_rr, PFID, req_is_replay(), ret, RETURN, ptlrpc_request::rq_export, and mdt_reint_record::rr_fid1.
Referenced by mdt_close(), and mdt_reint_migrate_internal().
int mdt_close_swap_layouts (struct mdt_thread_info * info, struct mdt_object * o, struct md_attr * ma)
Definition at line 1797 of file mdt_open.c.
References close_data::cd_fid, close_data::cd_handle, DFID, ENTRY, EXIT, exp_connect_flags(), fid_is_sane(), fid_is_zero(), GOTO, ldlm_lock::l_resource, LASSERT, LCK_EX, LDLM_DEBUG, ldlm_handle2lock(), ldlm_is_cancel, ldlm_lock_cancel(), LDLM_LOCK_PUT, ldlm_reprocess_all(), lock_res_and_lock(), lu_fid_cmp(), lu_object_attr(), md_attr::ma_need, md_attr::ma_valid, mdt_body::mbo_valid, MDS_INODELOCK_LAYOUT, MDS_INODELOCK_XATTR, MDT_LH_NEW, MDT_LH_OLD, mdt_lock_reg_init(), mdt_object_child(), mdt_object_fid(), mdt_object_find(), mdt_object_lock(), mdt_object_put(), mdt_object_unlock(), mo_permission(), mo_swap_layouts(), mdt_object::mot_obj, mdt_object::mot_open_sem, mdt_thread_info::mti_env, mdt_thread_info::mti_exp, mdt_thread_info::mti_lh, mdt_thread_info::mti_mdt, mdt_thread_info::mti_pill, OBD_CONNECT_RDONLY, OBD_MD_CLOSE_INTENT_EXECED, PFID, req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_CLOSE_DATA, RMF_MDT_BODY, swap, unlikely, and unlock_res_and_lock().
Referenced by mdt_mfd_close().
static int mdt_create_data (struct mdt_thread_info * info, struct mdt_object * p, struct mdt_object * o) [static]
Definition at line 112 of file mdt_open.c.
References ENTRY, MA_INODE, MA_LOV, md_attr::ma_need, md_attr::ma_valid, md_should_create(), mdo_create_data(), mdt_attr_get_complex(), mdt_object_child(), MOF_LOV_CREATED, mdt_object::mot_flags, mdt_object::mot_lov_mutex, mdt_thread_info::mti_attr, mdt_thread_info::mti_env, mdt_thread_info::mti_spec, RETURN, and md_op_spec::sp_cr_flags.
Referenced by mdt_mfd_open().
static int mdt_cross_open (struct mdt_thread_info * info, const struct lu_fid * parent_fid, const struct lu_fid * fid, struct ldlm_reply * rep, __u32 flags) [static]
Definition at line 1128 of file mdt_open.c.
References CERROR, D_WARNING, DFID, ENTRY, GOTO, LU_OBJECT_DEBUG, MDS_OPEN_CROSS, mdt_attr_get_complex(), mdt_finish_open(), mdt_obd_name(), mdt_object_child(), mdt_object_exists(), mdt_object_find(), mdt_object_put(), mdt_object_remote(), mdt_prep_ma_buf_from_rep(), mo_permission(), mdt_object::mot_obj, mdt_thread_info::mti_attr, mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, PFID, and RETURN.
Referenced by mdt_reint_open().
static void mdt_empty_transno (struct mdt_thread_info * info, int rc) [static]
Definition at line 197 of file mdt_open.c.
References __u64, ptlrpc_connection::c_peer, CDEBUG, CERROR, D_HA, D_INODE, dt_trans_create(), dt_trans_start(), dt_trans_stop(), ENTRY, EXIT, obd_export::exp_connection, obd_export::exp_obd, LASSERT, lsd_client_data::lcd_last_close_result, lsd_client_data::lcd_last_close_transno, lsd_client_data::lcd_last_close_xid, lsd_client_data::lcd_last_data, lsd_client_data::lcd_last_result, lsd_client_data::lcd_last_transno, lsd_client_data::lcd_last_xid, lsd_client_data::lcd_pre_versions, libcfs_nid2str(), LPU64, lustre_msg_get_opc(), lustre_msg_get_transno(), lustre_msg_get_versions(), lustre_msg_set_transno(), lu_target::lut_last_transno, lu_target::lut_translock, MDS_CLOSE, mdt_device::mdt_bottom, mdt_info_req(), mdt_device::mdt_lut, mdt_obd_name(), mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, mdt_thread_info::mti_opdata, mdt_thread_info::mti_transno, lnet_process_id_t::nid, obd_device::obd_last_committed, RETURN_EXIT, ptlrpc_request::rq_export, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_transno, ptlrpc_request::rq_xid, tg_export_data::ted_lcd, tg_export_data::ted_lcd_lock, and tgt_is_multimodrpcs_client().
Referenced by mdt_close(), and mdt_mfd_open().
static int mdt_finish_open (struct mdt_thread_info * info, struct mdt_object * p, struct mdt_object * o, __u64 flags, int created, struct ldlm_reply * rep) [static]
Definition at line 500 of file mdt_open.c.
References buf, lustre_handle::cookie, DISP_LOOKUP_NEG, DISP_LOOKUP_POS, DISP_OPEN_LOCK, DISP_OPEN_OPEN, ENTRY, exp_connect_flags(), exp_connect_rmtclient(), FMODE_WRITE, portals_handle::h_cookie, lu_attr::la_mode, LASSERT, list_entry, list_for_each, lustre_msg_get_flags(), lustre_msg_set_transno(), md_attr::ma_attr, MA_INODE, md_attr::ma_lmm_size, MA_LOV, md_attr::ma_valid, mdt_body::mbo_aclsize, mdt_body::mbo_eadatasize, mdt_body::mbo_handle, mdt_body::mbo_valid, MDS_OPEN_CREAT, MDS_OPEN_DIRECTORY, MDS_OPEN_EXCL, MDS_OPEN_LOCK, mdt_info_req(), mdt_mfd_open(), mdt_object_fid(), mdt_pack_attr2body(), mdt_pack_remote_perm(), mdt_set_disposition(), mdt_export_data::med_open_head, mdt_export_data::med_open_lock, mdt_file_data::mfd_handle, mdt_file_data::mfd_xid, MSG_RESENT, mdt_thread_info::mti_attr, mdt_thread_info::mti_pill, OBD_CONNECT_ACL, OBD_CONNECT_NODEVOH, OBD_FAIL_CHECK, OBD_FAIL_CHECK_RESET, OBD_FAIL_LDLM_REPLY, OBD_FAIL_MDS_NEGATIVE_POSITIVE, OBD_FAIL_MDS_OPEN_CREATE, OBD_FAIL_ONCE, OBD_MD_FLDIREA, OBD_MD_FLEASIZE, OBD_MD_FLRMTPERM, req_capsule_server_get(), RETURN, RMF_ACL, RMF_MDT_BODY, ptlrpc_request::rq_export, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_reqmsg, and ptlrpc_request::rq_xid.
Referenced by mdt_cross_open(), mdt_open_by_fid(), mdt_open_by_fid_lock(), mdt_reconstruct_open(), and mdt_reint_open().
struct mdt_file_data* mdt_handle2mfd (struct mdt_export_data * med, const struct lustre_handle * handle, bool is_replay_or_resent) [read]
Definition at line 84 of file mdt_open.c.
References class_handle2object(), lustre_handle::cookie, ENTRY, LASSERT, list_for_each_entry, mdt_export_data::med_open_head, mdt_file_data::mfd_list, mdt_file_data::mfd_old_handle, and RETURN.
Referenced by mdt_close_internal(), mdt_mfd_open(), and mdt_object_open_lock().
static int mdt_hsm_release (struct mdt_thread_info * info, struct mdt_object * o, struct md_attr * ma) [static]
Definition at line 1613 of file mdt_open.c.
References buf, close_data::cd_data_version, close_data::cd_fid, close_data::cd_handle, CDEBUG, CERROR, CLASSERT, cpu_to_le32, D_HSM, DFID, ENTRY, EXIT, exp_connect_flags(), fid_is_sane(), fid_is_zero(), FMODE_WRITE, GOTO, HS_RELEASED, mdt_thread_info::hsm, ldlm_lock::l_resource, LA_ATIME, LA_CTIME, LA_GID, lu_attr::la_gid, LA_MODE, lu_attr::la_mode, LA_MTIME, LA_SIZE, LA_UID, lu_attr::la_uid, lu_attr::la_valid, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, LCK_EX, LDLM_DEBUG, ldlm_handle2lock(), ldlm_is_cancel, ldlm_lock_cancel(), LDLM_LOCK_PUT, ldlm_reprocess_all(), le32_to_cpu, lock_res_and_lock(), LOV_MAGIC_V1, LOV_MAGIC_V1_DEF, LOV_MAGIC_V3, LOV_MAGIC_V3_DEF, LOV_MIN_STRIPE_SIZE, LOV_PATTERN_F_RELEASED, LOV_PATTERN_RAID0, LPU64, LU_OBJECT_DEBUG, lustre_hsm2buf(), md_attr::ma_attr, md_attr::ma_hsm, MA_HSM, MA_INODE, md_attr::ma_lmm, md_attr::ma_lmm_size, MA_LOV, md_attr::ma_need, md_attr::ma_valid, mdt_body::mbo_valid, MDS_INODELOCK_LAYOUT, MDS_INODELOCK_XATTR, mdt_attr_get_complex(), mdt_hsm_release_allow(), MDT_LH_LAYOUT, mdt_lock_reg_init(), mdt_obd_name(), mdt_object_child(), mdt_object_fid(), mdt_object_lock(), mdt_object_put(), mdt_object_unlock(), mdt_orphan_open(), md_hsm::mh_arch_ver, md_hsm::mh_flags, mo_attr_set(), mo_close(), mo_swap_layouts(), mo_xattr_set(), mdt_object::mot_obj, mdt_object::mot_open_sem, mdt_thread_info::mti_buf, mdt_thread_info::mti_env, mdt_thread_info::mti_exp, mdt_thread_info::mti_lh, mdt_thread_info::mti_mdt, mdt_thread_info::mti_pill, mdt_thread_info::mti_u, mdt_thread_info::mti_xattr_buf, OBD_CONNECT_RDONLY, OBD_MD_CLOSE_INTENT_EXECED, PFID, req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_CLOSE_DATA, RMF_MDT_BODY, SWAP_LAYOUTS_MDS_HSM, unlock_res_and_lock(), and XATTR_NAME_HSM.
Referenced by mdt_mfd_close().
static bool mdt_hsm_release_allow (const struct md_attr * ma) [static]
Check release is permitted for the current HSM flags.
Definition at line 1004 of file mdt_open.c.
References HS_ARCHIVED, HS_DIRTY, HS_LOST, HS_NORELEASE, md_attr::ma_hsm, MA_HSM, md_attr::ma_valid, and md_hsm::mh_flags.
Referenced by mdt_hsm_release(), and mdt_open_by_fid_lock().
int mdt_mfd_close (struct mdt_thread_info * info, struct mdt_file_data * mfd)
Definition at line 1939 of file mdt_open.c.
References __u64, CDEBUG, D_HSM, D_INODE, DFID, ENTRY, FMODE_READ, FMODE_WRITE, LA_ATIME, lu_attr::la_valid, LASSERT, md_attr::ma_attr, md_attr::ma_attr_flags, MA_INODE, md_attr::ma_need, md_attr::ma_valid, MDS_CLOSE_LAYOUT_SWAP, MDS_DATA_MODIFIED, MDS_FMODE_EXEC, MDS_HSM_RELEASE, MDS_OPEN_LEASE, mdt_add_dirty_flag(), mdt_close_swap_layouts(), mdt_hsm_release(), mdt_mfd_free(), mdt_obd_name(), mdt_object_child(), mdt_object_fid(), mdt_object_put(), mdt_write_allow(), mdt_write_put(), MFD_CLOSED, mdt_file_data::mfd_mode, mdt_file_data::mfd_object, mo_attr_set(), mo_close(), mode, mdt_object::mot_lease_count, mdt_object::mot_open_count, mdt_thread_info::mti_attr, mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, PFID, and RETURN.
Referenced by mdt_close_internal(), mdt_export_cleanup(), and mdt_mfd_open().
static int mdt_mfd_closed (struct mdt_file_data * mfd) [static]
Definition at line 1934 of file mdt_open.c.
References MFD_CLOSED, and mdt_file_data::mfd_mode.
Referenced by mdt_close_internal().
void mdt_mfd_free (struct mdt_file_data * mfd)
Definition at line 106 of file mdt_open.c.
References LASSERT, list_empty(), mdt_file_data::mfd_handle, mdt_file_data::mfd_list, and OBD_FREE_RCU.
Referenced by mdt_mfd_close().
static void mdt_mfd_get (void * mfdp) [static]
Definition at line 51 of file mdt_open.c.
struct mdt_file_data* mdt_mfd_new (const struct mdt_export_data * med) [read]
Definition at line 62 of file mdt_open.c.
References class_handle_hash(), ENTRY, portals_handle::h_link, portals_handle::h_owner, INIT_LIST_HEAD, mdt_file_data::mfd_handle, mdt_file_data::mfd_list, OBD_ALLOC_PTR, and RETURN.
Referenced by mdt_mfd_open().
static int mdt_mfd_open (struct mdt_thread_info * info, struct mdt_object * p, struct mdt_object * o, __u64 flags, int created, struct ldlm_reply * rep) [static]
Definition at line 331 of file mdt_open.c.
References allow_client_chgrp(), CDEBUG, class_handle_unhash(), lustre_handle::cookie, D_HA, D_INODE, DFID, DISP_OPEN_DENY, DISP_OPEN_STRIPE, ENTRY, exp_connect_flags(), obd_export::exp_disconnected, FMODE_WRITE, GOTO, portals_handle::h_cookie, lu_attr::la_mode, lu_attr::la_valid, LASSERT, list_add(), list_del_init(), LPX64, lu_ucred(), md_attr::ma_attr, md_attr::ma_attr_flags, MA_FLAGS, md_attr::ma_lmm_size, MA_LMV, md_attr::ma_lmv_size, MA_LOV, md_attr::ma_valid, mdt_body::mbo_eadatasize, mdt_body::mbo_handle, mdt_body::mbo_valid, MDS_FMODE_EXEC, MDS_OPEN_CREATED, MDS_OPEN_LEASE, MDS_OPEN_RELEASE, MDS_RECOV_OPEN, mdt_create_data(), mdt_empty_transno(), mdt_handle2mfd(), mdt_info_req(), mdt_mfd_close(), mdt_mfd_new(), mdt_mfd_set_mode(), mdt_object_child(), mdt_object_fid(), mdt_object_get(), mdt_set_disposition(), mdt_write_allow(), mdt_write_deny(), mdt_write_get(), mdt_write_put(), mdt_export_data::med_open_head, mdt_export_data::med_open_lock, mdt_file_data::mfd_handle, mdt_file_data::mfd_list, mdt_file_data::mfd_object, mdt_file_data::mfd_old_handle, mdt_file_data::mfd_xid, mo_open(), mdt_object::mot_lease_count, mdt_object::mot_open_count, mdt_thread_info::mti_attr, mdt_thread_info::mti_env, mdt_thread_info::mti_pill, mdt_thread_info::mti_rr, OBD_CONNECT_DISP_STRIPE, OBD_MD_FLDIREA, OBD_MD_FLEASIZE, OBD_MD_MEA, PFID, RCL_SERVER, req_capsule_get_size(), req_capsule_server_get(), req_is_replay(), RETURN, RMF_MDT_BODY, RMF_MDT_MD, ptlrpc_request::rq_export, ptlrpc_request::rq_xid, and mdt_reint_record::rr_handle.
Referenced by mdt_finish_open().
void mdt_mfd_set_mode (struct mdt_file_data * mfd, __u64 mode)
Definition at line 294 of file mdt_open.c.
References CDEBUG, D_HA, DFID, LASSERT, LPO64, mdt_object_fid(), mdt_file_data::mfd_mode, mdt_file_data::mfd_object, and PFID.
Referenced by mdt_mfd_open().
static int mdt_object_open_lock (struct mdt_thread_info * info, struct mdt_object * obj, struct mdt_lock_handle * lhc, __u64 * ibits) [static]
Definition at line 777 of file mdt_open.c.
References __u64, CDEBUG, CERROR, D_INODE, DFID, ENTRY, exp_connect_layout(), FMODE_WRITE, GOTO, LASSERT, LCK_CR, LCK_CW, LCK_EX, LCK_PR, LPO64, LPX64, lu_object_attr(), lustre_handle_is_used(), lustre_msg_get_flags(), MA_LOV, md_attr::ma_need, md_attr::ma_valid, md_should_create(), MDS_FMODE_EXEC, MDS_INODELOCK_LAYOUT, MDS_INODELOCK_LOOKUP, MDS_INODELOCK_OPEN, MDS_OPEN_LEASE, MDS_OPEN_LOCK, mdt_handle2mfd(), mdt_info_req(), MDT_LH_LAYOUT, MDT_LH_LOCAL, mdt_lock_handle_init(), mdt_lock_reg_init(), mdt_object_fid(), mdt_object_lock(), mdt_object_lock_try(), mdt_object_unlock(), mdt_lock_handle::mlh_reg_lh, mdt_object::mot_lease_count, mdt_object::mot_obj, mdt_object::mot_open_count, mdt_object::mot_open_sem, MSG_RESENT, mdt_thread_info::mti_attr, mdt_thread_info::mti_exp, mdt_thread_info::mti_lh, mdt_thread_info::mti_rr, mdt_thread_info::mti_spec, OBD_FAIL_CHECK, OBD_FAIL_MDS_LL_BLOCK, OBD_FAIL_MDS_NO_LL_OPEN, OBD_FAIL_TIMEOUT, PFID, req_is_replay(), RETURN, ptlrpc_request::rq_export, ptlrpc_request::rq_reqmsg, mdt_reint_record::rr_handle, and md_op_spec::sp_cr_flags.
Referenced by mdt_open_by_fid_lock(), and mdt_reint_open().
static void mdt_object_open_unlock (struct mdt_thread_info * info, struct mdt_object * obj, struct mdt_lock_handle * lhc, __u64 ibits, int rc) [static]
Definition at line 951 of file mdt_open.c.
References __u64, DISP_OPEN_LOCK, ENTRY, LASSERT, lustre_handle_is_used(), MDS_INODELOCK_LAYOUT, MDS_OPEN_LEASE, MDS_OPEN_LOCK, mdt_clear_disposition(), MDT_EREMOTE_OPEN, mdt_info_req(), MDT_LH_LAYOUT, MDT_LH_LOCAL, mdt_object_unlock(), mdt_lock_handle::mlh_reg_lh, mdt_object::mot_open_sem, mdt_thread_info::mti_lh, mdt_thread_info::mti_pill, mdt_thread_info::mti_spec, req_capsule_server_get(), req_is_replay(), RETURN_EXIT, RMF_DLM_REP, and md_op_spec::sp_cr_flags.
Referenced by mdt_open_by_fid_lock(), and mdt_reint_open().
static int mdt_open_by_fid (struct mdt_thread_info * info, struct ldlm_reply * rep) [static]
Definition at line 733 of file mdt_open.c.
References __u64, DISP_IT_EXECD, DISP_LOOKUP_EXECD, DISP_LOOKUP_POS, ENTRY, mdt_body::mbo_fid1, mdt_body::mbo_valid, mdt_attr_get_complex(), mdt_finish_open(), mdt_object_exists(), mdt_object_find(), mdt_object_put(), mdt_object_remote(), mdt_prep_ma_buf_from_rep(), mdt_set_disposition(), mdt_thread_info::mti_attr, mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, mdt_thread_info::mti_pill, mdt_thread_info::mti_rr, mdt_thread_info::mti_spec, OBD_MD_FLID, OBD_MD_MDS, req_capsule_server_get(), RETURN, RMF_MDT_BODY, mdt_reint_record::rr_fid2, md_op_spec::sp_cr_flags, and unlikely.
Referenced by mdt_reint_open().
static int mdt_open_by_fid_lock (struct mdt_thread_info * info, struct ldlm_reply * rep, struct mdt_lock_handle * lhc) [static]
Definition at line 1018 of file mdt_open.c.
References __u64, CDEBUG, D_INFO, D_INODE, DFID, DISP_IT_EXECD, DISP_LOOKUP_EXECD, DISP_LOOKUP_NEG, DISP_LOOKUP_POS, DISP_OPEN_LEASE, DISP_OPEN_LOCK, ENTRY, GOTO, lu_fid_eq(), lu_object_attr(), MA_HSM, MA_LOV, md_attr::ma_need, md_attr::ma_pfid, MA_PFID, md_attr::ma_valid, md_should_create(), MDS_OPEN_HAS_EA, MDS_OPEN_LEASE, MDS_OPEN_LOCK, MDS_OPEN_RELEASE, mdt_attr_get_complex(), mdt_check_resent_lock(), mdt_finish_open(), mdt_hsm_release_allow(), mdt_obd_name(), mdt_object_exists(), mdt_object_find(), mdt_object_open_lock(), mdt_object_open_unlock(), mdt_object_put(), mdt_object_remote(), mdt_prep_ma_buf_from_rep(), mdt_set_disposition(), mdt_object::mot_obj, mdt_thread_info::mti_attr, mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, mdt_thread_info::mti_rr, mdt_thread_info::mti_spec, PFID, mdt_reint_record::rr_fid1, mdt_reint_record::rr_fid2, and md_op_spec::sp_cr_flags.
Referenced by mdt_reint_open().
static struct mdt_object* mdt_orphan_open (struct mdt_thread_info * info, struct mdt_device * mdt, const struct lu_fid * fid, struct md_attr * attr, fmode_t fmode) [static, read]
Create an orphan object use local root.
Definition at line 1540 of file mdt_open.c.
References CERROR, CFS_CAP_DAC_OVERRIDE, DFID, dt_directory_features, dt_root_get(), ENTRY, GOTO, lu_name::ln_name, lu_ucred(), md_attr::ma_lmm, md_attr::ma_lmm_size, MA_LOV, md_attr::ma_valid, MDL_MINMODE, mdo_create(), MDS_OPEN_CREATED, MDS_OPEN_DELAY_CREATE, MDS_OPEN_HAS_EA, MDS_OPEN_VOLATILE, mdt_device::mdt_bottom, mdt_obd_name(), mdt_object_child(), mdt_object_find(), mdt_object_new(), mdt_object_put(), mo_open(), mdt_thread_info::mti_env, mdt_thread_info::mti_spec, mdt_thread_info::mti_tmp_fid1, PFID, RETURN, md_op_spec::sp_cr_flags, md_op_spec::sp_cr_lookup, md_op_spec::sp_cr_mode, md_op_spec::sp_ea, md_op_spec::sp_feat, md_op_spec::u, and lu_ucred::uc_cap.
Referenced by mdt_hsm_release().
static void mdt_prep_ma_buf_from_rep (struct mdt_thread_info * info, struct mdt_object * obj, struct md_attr * ma) [static]
prep ma_lmm/ma_lmv for md_attr from reply
Definition at line 307 of file mdt_open.c.
References LASSERT, lu_object_header::loh_attr, md_attr::ma_lmm, md_attr::ma_lmm_size, MA_LMV, md_attr::ma_lmv, md_attr::ma_lmv_size, MA_LOV, md_attr::ma_need, mdt_object::mot_header, mdt_thread_info::mti_pill, RCL_SERVER, req_capsule_get_size(), req_capsule_server_get(), and RMF_MDT_MD.
Referenced by mdt_cross_open(), mdt_open_by_fid(), mdt_open_by_fid_lock(), mdt_reconstruct_open(), and mdt_reint_open().
void mdt_reconstruct_open (struct mdt_thread_info * info, struct mdt_lock_handle * lhc)
Definition at line 623 of file mdt_open.c.
References __u64, CDEBUG, D_INODE, DFID, DISP_OPEN_CREATE, ENTRY, ergo, EXIT, obd_export::exp_client_uuid, GOTO, LASSERT, LCONSOLE_WARN, ldlm_reply::lock_policy_res1, LPX64, lustre_msg_get_transno(), lustre_msg_set_status(), MA_HSM, MA_INODE, md_attr::ma_need, md_attr::ma_valid, mdt_body::mbo_fid1, mdt_body::mbo_valid, mdt_attr_get_complex(), mdt_export_evict(), mdt_finish_open(), mdt_get_disposition(), mdt_info_req(), mdt_is_dne_client(), mdt_object_exists(), mdt_object_find(), mdt_object_put(), mdt_object_remote(), mdt_prep_ma_buf_from_rep(), mdt_reint_open(), mdt_req_from_lrd(), mdt_set_disposition(), mdt_thread_info::mti_attr, mdt_thread_info::mti_env, mdt_thread_info::mti_mdt, mdt_thread_info::mti_pill, mdt_thread_info::mti_reply_data, mdt_thread_info::mti_rr, mdt_thread_info::mti_spec, obd_export_nid2str(), OBD_MD_FLID, OBD_MD_MDS, obd_uuid2str(), PFID, req_capsule::rc_fmt, req_capsule_server_get(), RETURN_EXIT, RMF_DLM_REP, RMF_MDT_BODY, ptlrpc_request::rq_export, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_status, RQF_LDLM_INTENT_OPEN, mdt_reint_record::rr_fid1, mdt_reint_record::rr_fid2, md_op_spec::sp_cr_flags, and unlikely.
int mdt_reint_open (struct mdt_thread_info * info, struct mdt_lock_handle * lhc)
check version of child
Definition at line 1180 of file mdt_open.c.
References __u64, CDEBUG, CERROR, D_ERROR, D_INFO, D_INODE, DEBUG_REQ, DFID, DISP_IT_EXECD, DISP_LOOKUP_EXECD, DISP_LOOKUP_NEG, DISP_LOOKUP_POS, DISP_OPEN_CREATE, DISP_OPEN_LOCK, DNAME, dt_directory_features, ENTRY, ergo, err_serious(), EXIT, exp_connect_flags(), obd_export::exp_libclient, fid_is_md_operative(), fid_is_sane(), fid_le_to_cpu(), fid_zero(), FMODE_WRITE, GOTO, lu_attr::la_mode, LASSERT, LASSERTF, lu_buf::lb_buf, lu_buf::lb_len, LCK_PR, LCK_PW, le32_to_cpu, LMV_HASH_FLAG_MIGRATION, lmv_mds_md_v1::lmv_hash_type, lmv_mds_md_v1::lmv_stripe_fids, LPO64, LPROC_MDT_OPEN, lu_name_is_valid(), lustre_msg_get_flags(), lustre_msg_set_transno(), md_attr::ma_attr, MA_HSM, MA_INODE, md_attr::ma_need, md_attr::ma_valid, mdt_body::mbo_fid1, mdt_body::mbo_valid, mdo_create(), mdo_lookup(), mdo_unlink(), MDS_INODELOCK_LOOKUP, MDS_INODELOCK_UPDATE, MDS_OPEN_BY_FID, MDS_OPEN_CREAT, MDS_OPEN_HAS_EA, MDS_OPEN_HAS_OBJS, MDS_OPEN_JOIN_FILE, MDS_OPEN_LOCK, MDS_OPEN_VOLATILE, mdt_attr_get_complex(), mdt_check_resent_lock(), mdt_clear_disposition(), mdt_counter_incr(), mdt_cross_open(), mdt_dlm_mode2mdl_mode(), MDT_EREMOTE_OPEN, mdt_finish_open(), mdt_info_req(), MDT_LH_PARENT, mdt_lock_handle_init(), mdt_lock_pdo_init(), mdt_lock_reg_init(), mdt_obd_name(), mdt_obj2dt(), mdt_object_child(), mdt_object_exists(), mdt_object_fid(), mdt_object_find(), mdt_object_lock(), mdt_object_new(), mdt_object_open_lock(), mdt_object_open_unlock(), mdt_object_put(), mdt_object_remote(), mdt_object_unlock_put(), mdt_open_by_fid(), mdt_open_by_fid_lock(), mdt_prep_ma_buf_from_rep(), mdt_set_disposition(), mdt_version_get_check(), mdt_version_get_save(), mdt_lock_handle::mlh_pdo_mode, mo_xattr_get(), MSG_RESENT, mdt_thread_info::mti_attr, mdt_thread_info::mti_cross_ref, mdt_thread_info::mti_env, mdt_thread_info::mti_lh, mdt_thread_info::mti_mdt, mdt_thread_info::mti_pill, mdt_thread_info::mti_rr, mdt_thread_info::mti_spec, mdt_thread_info::mti_tmp_fid1, mdt_thread_info::mti_xattr_buf, OBD_CONNECT_RDONLY, OBD_FAIL_CHECK, OBD_FAIL_MDS_OPEN_PACK, OBD_FAIL_MDS_PAUSE_OPEN, OBD_FAIL_ONCE, OBD_FAIL_TIMEOUT_ORSET, OBD_MD_FLID, OBD_MD_MDS, obd_timeout, PFID, PNAME, req_capsule::rc_fmt, req_capsule_server_get(), req_is_replay(), RMF_DLM_REP, RMF_MDT_BODY, ptlrpc_request::rq_export, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_reqmsg, RQF_LDLM_INTENT_OPEN, mdt_reint_record::rr_fid1, mdt_reint_record::rr_fid2, mdt_reint_record::rr_name, md_op_spec::sp_cr_flags, md_op_spec::sp_cr_lookup, md_op_spec::sp_cr_mode, md_op_spec::sp_ea, md_op_spec::sp_feat, tgt_vbr_obj_set(), md_op_spec::u, unlikely, and XATTR_NAME_LMV.
Referenced by mdt_reconstruct_open().
static void mdt_write_allow (struct mdt_object * o) [static]
Definition at line 187 of file mdt_open.c.
References ENTRY, EXIT, mdt_object::mot_write_count, and mdt_object::mot_write_lock.
Referenced by mdt_mfd_close(), and mdt_mfd_open().
static int mdt_write_deny (struct mdt_object * o) [static]
Definition at line 174 of file mdt_open.c.
References ENTRY, mdt_object::mot_write_count, mdt_object::mot_write_lock, and RETURN.
Referenced by mdt_mfd_open().
int mdt_write_get (struct mdt_object * o)
Definition at line 151 of file mdt_open.c.
References ENTRY, mdt_object::mot_write_count, mdt_object::mot_write_lock, and RETURN.
Referenced by mdt_mfd_open().
void mdt_write_put (struct mdt_object * o)
Definition at line 165 of file mdt_open.c.
References ENTRY, EXIT, mdt_object::mot_write_count, and mdt_object::mot_write_lock.
Referenced by mdt_mfd_close(), and mdt_mfd_open().
int mdt_write_read (struct mdt_object * o)
Definition at line 141 of file mdt_open.c.
References ENTRY, mdt_object::mot_write_count, mdt_object::mot_write_lock, and RETURN.
Referenced by mdt_reint_setattr().
Variable Documentation
struct portals_handle_ops mfd_handle_ops [static]
Initial value:
 {
        .hop_addref = mdt_mfd_get,
        .hop_free   = NULL,
}
Definition at line 55 of file mdt_open.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.