Lustre: lustre/mdt/mdt_idmap.c File Reference
lustre/mdt/mdt_idmap.c File Reference
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/mm.h>
#include <linux/kmod.h>
#include <linux/user_namespace.h>
#include <linux/string.h>
#include <linux/stat.h>
#include <linux/errno.h>
#include <linux/version.h>
#include <linux/unistd.h>
#include <asm/uaccess.h>
#include <linux/fs.h>
#include <linux/slab.h>
#include <libcfs/libcfs.h>
#include <obd.h>
#include <obd_class.h>
#include <obd_support.h>
#include <lustre_net.h>
#include <lustre_import.h>
#include <lustre_dlm.h>
#include <lustre_sec.h>
#include <lustre_lib.h>
#include "mdt_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_MDS
Functions
int mdt_init_idmap (struct tgt_session_info *tsi)
void mdt_cleanup_idmap (struct mdt_export_data *med)
static void mdt_revoke_export_locks (struct obd_export *exp)
int mdt_handle_idmap (struct tgt_session_info *tsi)
int ptlrpc_user_desc_do_idmap (struct ptlrpc_request *req, struct ptlrpc_user_desc *pud)
void mdt_body_reverse_idmap (struct mdt_thread_info *info, struct mdt_body *body)
int mdt_fix_attr_ucred (struct mdt_thread_info *info, __u32 op)
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 42 of file mdt_idmap.c.
Function Documentation
void mdt_body_reverse_idmap (struct mdt_thread_info * info, struct mdt_body * body)
Definition at line 275 of file mdt_idmap.c.
References CFS_IDMAP_NOTFOUND, exp_connect_rmtclient(), lustre_idmap_lookup_gid(), lustre_idmap_lookup_uid(), mdt_body::mbo_gid, mdt_body::mbo_mode, mdt_body::mbo_uid, mdt_body::mbo_valid, mdt_info_req(), mdt_req2med(), mdt_ucred(), mdt_export_data::med_idmap, mdt_thread_info::mti_exp, NOBODY_GID, NOBODY_UID, OBD_MD_FLGID, OBD_MD_FLMODE, and OBD_MD_FLUID.
Referenced by mdt_pack_attr2body().
void mdt_cleanup_idmap (struct mdt_export_data * med)
Definition at line 116 of file mdt_idmap.c.
References lustre_idmap_fini(), mdt_export_data::med_idmap, and mdt_export_data::med_idmap_mutex.
Referenced by mdt_destroy_export().
int mdt_fix_attr_ucred (struct mdt_thread_info * info, __u32 op)
Definition at line 317 of file mdt_idmap.c.
References CDEBUG, CFS_IDMAP_NOTFOUND, D_SEC, exp_connect_rmtclient(), lu_attr::la_gid, LA_GID, lu_attr::la_uid, LA_UID, lu_attr::la_valid, lustre_idmap_lookup_gid(), lustre_idmap_lookup_uid(), md_attr::ma_attr, mdt_info_req(), mdt_req2med(), mdt_ucred_check(), mdt_export_data::med_idmap, mdt_thread_info::mti_attr, mdt_thread_info::mti_exp, REINT_SETATTR, lu_ucred::uc_fsgid, and lu_ucred::uc_fsuid.
Referenced by mdt_reint_internal().
int mdt_handle_idmap (struct tgt_session_info * tsi)
Definition at line 135 of file mdt_idmap.c.
References CDEBUG, D_SEC, ENTRY, exp_connect_rmtclient(), is_identity_get_disabled(), LASSERT, lustre_idmap_add(), lustre_idmap_del(), lustre_msg_get_opc(), make_kuid(), MDS_CONNECT, mdt_exp2dev(), mdt_device::mdt_identity_cache, mdt_identity_get(), mdt_identity_put(), mdt_req2med(), mdt_revoke_export_locks(), mdt_export_data::med_idmap, md_identity::mi_gid, md_identity::mi_uid, ptlrpc_user_desc::pud_gid, ptlrpc_user_desc::pud_uid, RETURN, ptlrpc_request::rq_export, ptlrpc_request::rq_reqmsg, SEC_CTX_FINI, SEC_CTX_INIT, SEC_CTX_INIT_CONT, tgt_ses_req(), uid_valid(), and unlikely.
Referenced by mdt_init_idmap(), and mdt_sec_ctx_handle().
int mdt_init_idmap (struct tgt_session_info * tsi)
Definition at line 75 of file mdt_idmap.c.
References CDEBUG, CERROR, D_SEC, ENTRY, exp_connect_rmtclient(), libcfs_nid2str(), lustre_idmap_init(), mdt_handle_idmap(), mdt_req2med(), mdt_export_data::med_idmap, mdt_export_data::med_idmap_mutex, lnet_process_id_t::nid, RETURN, ptlrpc_request::rq_export, ptlrpc_request::rq_peer, tgt_name(), tgt_ses_req(), and tgt_session_info::tsi_tgt.
Referenced by mdt_tgt_connect().
static void mdt_revoke_export_locks (struct obd_export * exp) [inline, static]
Definition at line 126 of file mdt_idmap.c.
References obd_export::exp_obd, and obd_device::obd_recovering.
Referenced by mdt_handle_idmap().
int ptlrpc_user_desc_do_idmap (struct ptlrpc_request * req, struct ptlrpc_user_desc * pud)
Definition at line 218 of file mdt_idmap.c.
References CDEBUG, CFS_IDMAP_NOTFOUND, D_SEC, exp_connect_rmtclient(), lustre_idmap_lookup_gid(), lustre_idmap_lookup_uid(), mdt_req2med(), mdt_export_data::med_idmap, ptlrpc_user_desc::pud_fsgid, ptlrpc_user_desc::pud_fsuid, ptlrpc_user_desc::pud_gid, ptlrpc_user_desc::pud_uid, and ptlrpc_request::rq_export.
Referenced by mdt_check_ucred(), and new_init_ucred().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.