Lustre: lustre/mdt/mdt_lib.c File Reference
lustre/mdt/mdt_lib.c File Reference
#include <linux/user_namespace.h>
#include "mdt_internal.h"
#include <lnet/nidstr.h>
#include <lustre_nodemap.h>
Defines
#define DEBUG_SUBSYSTEM S_MDS
Typedefs
typedef enum ucred_init_type ucred_init_type_t
typedef int(* reint_unpacker)(struct mdt_thread_info *info)
Enumerations
enum ucred_init_type { NONE_INIT = 0, BODY_INIT = 1, REC_INIT = 2 }
Functions
void mdt_exit_ucred (struct mdt_thread_info *info)
static int match_nosquash_list (struct rw_semaphore *sem, struct list_head *nidlist, lnet_nid_t peernid)
static int mdt_root_squash (struct mdt_thread_info *info, lnet_nid_t peernid)
static void ucred_set_jobid (struct mdt_thread_info *info, struct lu_ucred *uc)
static int new_init_ucred (struct mdt_thread_info *info, ucred_init_type_t type, void *buf, bool drop_fs_cap)
bool allow_client_chgrp (struct mdt_thread_info *info, struct lu_ucred *uc)
Check whether allow the client to set supplementary group IDs or not.
int mdt_check_ucred (struct mdt_thread_info *info)
static int old_init_ucred_common (struct mdt_thread_info *info, bool drop_fs_cap)
static int old_init_ucred (struct mdt_thread_info *info, struct mdt_body *body, bool drop_fs_cap)
static int old_init_ucred_reint (struct mdt_thread_info *info)
static int __mdt_init_ucred (struct mdt_thread_info *info, struct mdt_body *body, bool drop_fs_cap)
int mdt_init_ucred (struct mdt_thread_info *info, struct mdt_body *body)
int mdt_init_ucred_intent_getattr (struct mdt_thread_info *info, struct mdt_body *body)
int mdt_init_ucred_reint (struct mdt_thread_info *info)
void mdt_dump_lmm (int level, const struct lov_mds_md *lmm, __u64 valid)
void mdt_dump_lmv (unsigned int level, const union lmv_mds_md *lmv)
int mdt_fix_reply (struct mdt_thread_info *info)
int mdt_handle_last_unlink (struct mdt_thread_info *info, struct mdt_object *mo, const struct md_attr *ma)
static __u64 mdt_attr_valid_xlate (__u64 in, struct mdt_reint_record *rr, struct md_attr *ma)
int mdt_name_unpack (struct req_capsule *pill, const struct req_msg_field *field, struct lu_name *ln, enum mdt_name_flags flags)
static int mdt_setattr_unpack_rec (struct mdt_thread_info *info)
static int mdt_close_handle_unpack (struct mdt_thread_info *info)
static int mdt_dlmreq_unpack (struct mdt_thread_info *info)
static int mdt_setattr_unpack (struct mdt_thread_info *info)
static int mdt_intent_close_unpack (struct mdt_thread_info *info)
int mdt_close_unpack (struct mdt_thread_info *info)
static int mdt_create_unpack (struct mdt_thread_info *info)
static int mdt_link_unpack (struct mdt_thread_info *info)
static int mdt_unlink_unpack (struct mdt_thread_info *info)
static int mdt_rmentry_unpack (struct mdt_thread_info *info)
static int mdt_rename_unpack (struct mdt_thread_info *info)
static void mdt_fix_lov_magic (struct mdt_thread_info *info)
static int mdt_open_unpack (struct mdt_thread_info *info)
static int mdt_setxattr_unpack (struct mdt_thread_info *info)
int mdt_reint_unpack (struct mdt_thread_info *info, __u32 op)
Variables
static reint_unpacker mdt_reint_unpackers [REINT_MAX]
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 49 of file mdt_lib.c.
Typedef Documentation
typedef int(* reint_unpacker)(struct mdt_thread_info *info)
Definition at line 1450 of file mdt_lib.c.
typedef enum ucred_init_type ucred_init_type_t
Enumeration Type Documentation
enum ucred_init_type
Enumerator:
NONE_INIT
BODY_INIT
REC_INIT
Definition at line 59 of file mdt_lib.c.
Function Documentation
static int __mdt_init_ucred (struct mdt_thread_info * info, struct mdt_body * body, bool drop_fs_cap) [inline, static]
Definition at line 577 of file mdt_lib.c.
References BODY_INIT, LASSERT, mdt_exit_ucred(), mdt_info_req(), mdt_ucred(), new_init_ucred(), old_init_ucred(), ptlrpc_request::rq_auth_gss, ptlrpc_request::rq_auth_usr_mdt, lu_ucred::uc_valid, UCRED_NEW, and UCRED_OLD.
Referenced by mdt_init_ucred(), and mdt_init_ucred_intent_getattr().
bool allow_client_chgrp (struct mdt_thread_info * info, struct lu_ucred * uc)
Check whether allow the client to set supplementary group IDs or not.
Parameters:
[in] info pointer to the thread context
[in] uc pointer to the RPC user descriptor
Return values:
true if allow to set supplementary group IDs
false for other cases
Definition at line 334 of file mdt_lib.c.
References CFS_SETGRP_PERM, exp_connect_rmtclient(), is_identity_get_disabled(), mdt_device::mdt_identity_cache, mdt_identity_get_perm(), mdt_info_req(), mdt_thread_info::mti_exp, mdt_thread_info::mti_mdt, and lu_ucred::uc_identity.
Referenced by mdt_mfd_open().
static int match_nosquash_list (struct rw_semaphore * sem, struct list_head * nidlist, lnet_nid_t peernid) [static]
Definition at line 86 of file mdt_lib.c.
References cfs_match_nid(), ENTRY, and RETURN.
Referenced by mdt_root_squash().
static __u64 mdt_attr_valid_xlate (__u64 in, struct mdt_reint_record * rr, struct md_attr * ma) [static]
Definition at line 833 of file mdt_lib.c.
References __u64, CERROR, LA_ATIME, LA_BLOCKS, LA_CTIME, LA_FLAGS, LA_GID, LA_KILL_SGID, LA_KILL_SUID, LA_MODE, LA_MTIME, LA_SIZE, LA_UID, LPX64, md_attr::ma_attr_flags, MDS_ATTR_ATIME, MDS_ATTR_ATIME_SET, MDS_ATTR_ATTR_FLAG, MDS_ATTR_BLOCKS, MDS_ATTR_CTIME, MDS_ATTR_CTIME_SET, MDS_ATTR_FORCE, MDS_ATTR_FROM_OPEN, MDS_ATTR_GID, MDS_ATTR_KILL_SGID, MDS_ATTR_KILL_SUID, MDS_ATTR_MODE, MDS_ATTR_MTIME, MDS_ATTR_MTIME_SET, MDS_ATTR_SIZE, MDS_ATTR_UID, MDS_OPEN_OWNEROVERRIDE, MDS_OWNEROVERRIDE, MDS_PERM_BYPASS, MRF_OPEN_TRUNC, and mdt_reint_record::rr_flags.
Referenced by mdt_setattr_unpack_rec().
int mdt_check_ucred (struct mdt_thread_info * info)
Definition at line 362 of file mdt_lib.c.
References CDEBUG, CFS_SETGID_PERM, CFS_SETUID_PERM, D_SEC, ENTRY, EXIT, exp_connect_rmtclient(), GOTO, is_identity_get_disabled(), LASSERT, libcfs_nid2str(), make_kuid(), mdt_device::mdt_identity_cache, mdt_identity_get(), mdt_identity_get_perm(), mdt_identity_put(), mdt_info_req(), mdt_ucred(), md_identity::mi_gid, mdt_thread_info::mti_exp, mdt_thread_info::mti_mdt, lnet_process_id_t::nid, ptlrpc_user_desc_do_idmap(), ptlrpc_user_desc::pud_fsgid, ptlrpc_user_desc::pud_fsuid, ptlrpc_user_desc::pud_gid, ptlrpc_user_desc::pud_uid, RETURN, ptlrpc_request::rq_auth_gss, ptlrpc_request::rq_auth_usr_mdt, ptlrpc_request::rq_peer, lu_ucred::uc_valid, UCRED_NEW, UCRED_OLD, uid_valid(), and unlikely.
Referenced by mdt_get_root(), mdt_getattr(), and mdt_statfs().
static int mdt_close_handle_unpack (struct mdt_thread_info * info) [static]
Definition at line 966 of file mdt_lib.c.
References ENTRY, mdt_ioepoch::mio_handle, mdt_thread_info::mti_close_handle, mdt_thread_info::mti_pill, RCL_CLIENT, req_capsule_client_get(), req_capsule_get_size(), RETURN, and RMF_MDT_EPOCH.
Referenced by mdt_close_unpack(), and mdt_rename_unpack().
int mdt_close_unpack (struct mdt_thread_info * info)
Definition at line 1053 of file mdt_lib.c.
References ENTRY, mdt_close_handle_unpack(), mdt_init_ucred_reint(), mdt_intent_close_unpack(), mdt_setattr_unpack_rec(), and RETURN.
Referenced by mdt_close().
static int mdt_create_unpack (struct mdt_thread_info * info) [static]
Definition at line 1073 of file mdt_lib.c.
References CLASSERT, mdt_rec_create::cr_cap, mdt_rec_create::cr_fid1, mdt_rec_create::cr_fid2, mdt_rec_create::cr_fsgid, mdt_rec_create::cr_fsuid, mdt_rec_create::cr_mode, mdt_rec_create::cr_rdev, mdt_rec_create::cr_suppgid1, mdt_rec_create::cr_time, mdt_rec_create::cr_umask, ENTRY, get_mrc_cr_flags(), LA_ATIME, lu_attr::la_atime, LA_CTIME, lu_attr::la_ctime, LA_GID, lu_attr::la_gid, LA_MODE, lu_attr::la_mode, LA_MTIME, lu_attr::la_mtime, LA_RDEV, lu_attr::la_rdev, LA_TYPE, LA_UID, lu_attr::la_uid, lu_attr::la_valid, md_attr::ma_attr, MDS_OPEN_HAS_EA, mdt_dlmreq_unpack(), mdt_name_unpack(), mdt_ucred(), mdt_thread_info::mti_attr, mdt_thread_info::mti_pill, mdt_thread_info::mti_rr, mdt_thread_info::mti_spec, RCL_CLIENT, req_capsule_client_get(), req_capsule_extend(), req_capsule_get_size(), RETURN, RMF_EADATA, RMF_NAME, RMF_REC_REINT, RMF_SYMTGT, RQF_MDS_REINT_CREATE_RMT_ACL, RQF_MDS_REINT_CREATE_SYM, mdt_reint_record::rr_fid1, mdt_reint_record::rr_fid2, mdt_reint_record::rr_name, md_op_spec::sp_cr_flags, md_op_spec::sp_ea, md_op_spec::sp_symname, md_op_spec::u, lu_ucred::uc_cap, lu_ucred::uc_fsgid, lu_ucred::uc_fsuid, lu_ucred::uc_suppgids, and lu_ucred::uc_umask.
static int mdt_dlmreq_unpack (struct mdt_thread_info * info) [inline, static]
Definition at line 985 of file mdt_lib.c.
References mdt_thread_info::mti_dlm_req, mdt_thread_info::mti_pill, RCL_CLIENT, req_capsule_client_get(), req_capsule_get_size(), RETURN, and RMF_DLM_REQ.
Referenced by mdt_create_unpack(), mdt_link_unpack(), mdt_rename_unpack(), mdt_setattr_unpack(), mdt_setxattr_unpack(), and mdt_unlink_unpack().
void mdt_dump_lmm (int level, const struct lov_mds_md * lmm, __u64 valid)
Definition at line 630 of file mdt_lib.c.
References CDEBUG, cfs_cdebug_show(), DEBUG_SUBSYSTEM, DOSTID, lov_ost_data_v1::l_ost_idx, lov_ost_data_v1::l_ost_oi, LASSERT, le16_to_cpu, le32_to_cpu, likely, LOV_MAX_STRIPE_COUNT, LOV_PATTERN_F_RELEASED, lov_user_md, OBD_MD_FLDIREA, ostid_le_to_cpu(), and POSTID.
Referenced by mdt_getattr_internal().
void mdt_dump_lmv (unsigned int level, const union lmv_mds_md * lmv)
Definition at line 663 of file mdt_lib.c.
References CDEBUG, cfs_cdebug_show(), DEBUG_SUBSYSTEM, DFID, fid_le_to_cpu(), le32_to_cpu, likely, lmv_mds_md_v1::lmv_magic, LMV_MAGIC_STRIPE, lmv_mds_md_v1::lmv_master_mdt_index, lmv_mds_md::lmv_md_v1, lmv_mds_md_v1::lmv_stripe_count, lmv_mds_md_v1::lmv_stripe_fids, and PFID.
Referenced by mdt_getattr_internal().
void mdt_exit_ucred (struct mdt_thread_info * info)
Definition at line 65 of file mdt_lib.c.
References LASSERT, mdt_device::mdt_identity_cache, mdt_identity_put(), mdt_ucred(), mdt_thread_info::mti_mdt, lu_ucred::uc_ginfo, lu_ucred::uc_identity, lu_ucred::uc_suppgids, lu_ucred::uc_valid, and UCRED_INIT.
Referenced by __mdt_init_ucred(), mdt_close(), mdt_getattr(), mdt_getattr_name(), mdt_getxattr(), mdt_hsm_action(), mdt_hsm_is_admin(), mdt_hsm_request(), mdt_hsm_state_get(), mdt_hsm_state_set(), mdt_init_ucred_reint(), mdt_intent_getattr(), mdt_reint_internal(), and mdt_reint_setxattr().
static void mdt_fix_lov_magic (struct mdt_thread_info * info) [static]
Definition at line 1299 of file mdt_lib.c.
References __swab32, LASSERT, lov_user_md_v1::lmm_magic, LOV_MAGIC_V1_DEF, LOV_MAGIC_V3_DEF, LOV_USER_MAGIC_V1, LOV_USER_MAGIC_V3, mdt_info_req(), mdt_thread_info::mti_rr, req_is_replay(), mdt_reint_record::rr_eadata, and unlikely.
Referenced by mdt_open_unpack().
int mdt_fix_reply (struct mdt_thread_info * info)
Definition at line 689 of file mdt_lib.c.
References CDEBUG, D_INFO, ENTRY, LASSERT, lustre_msg_set_transno(), md_attr::ma_lmm, md_attr::ma_lmm_size, md_attr::ma_lmv, MA_LMV, md_attr::ma_lmv_size, MA_LOV, md_attr::ma_valid, mdt_body::mbo_aclsize, mdt_body::mbo_eadatasize, mdt_body::mbo_valid, mdt_device::mdt_max_mdsize, mdt_thread_info::mti_attr, mdt_thread_info::mti_big_lmm_used, mdt_thread_info::mti_mdt, mdt_thread_info::mti_pill, mdt_thread_info::mti_spec, md_op_spec::no_create, OBD_MD_FLDIREA, OBD_MD_FLEASIZE, OBD_MD_FLMDSCAPA, OBD_MD_FLOSSCAPA, OBD_MD_LINKNAME, req_capsule::rc_req, RCL_SERVER, req_capsule_get_size(), req_capsule_has_field(), req_capsule_server_get(), req_capsule_server_grow(), req_capsule_shrink(), RETURN, RMF_ACL, RMF_CAPA1, RMF_CAPA2, RMF_LOGCOOKIES, RMF_MDT_BODY, RMF_MDT_MD, and ptlrpc_request::rq_repmsg.
Referenced by mdt_close(), mdt_getattr(), mdt_getattr_name(), mdt_intent_getattr(), mdt_reint_internal(), and mdt_reint_setattr().
int mdt_handle_last_unlink (struct mdt_thread_info * info, struct mdt_object * mo, const struct md_attr * ma)
Definition at line 811 of file mdt_lib.c.
References CERROR, ENTRY, LASSERT, md_attr::ma_attr, MA_INODE, MA_LOV, md_attr::ma_valid, mdt_body::mbo_eadatasize, mdt_object_fid(), mdt_pack_attr2body(), mdt_thread_info::mti_pill, req_capsule_server_get(), RETURN, and RMF_MDT_BODY.
Referenced by mdt_close_internal(), mdt_reint_rename_internal(), and mdt_reint_unlink().
int mdt_init_ucred (struct mdt_thread_info * info, struct mdt_body * body)
Definition at line 596 of file mdt_lib.c.
References __mdt_init_ucred().
Referenced by mdt_getattr(), mdt_getxattr(), mdt_hsm_action(), mdt_hsm_is_admin(), mdt_hsm_request(), mdt_hsm_state_get(), and mdt_hsm_state_set().
int mdt_init_ucred_intent_getattr (struct mdt_thread_info * info, struct mdt_body * body)
Definition at line 606 of file mdt_lib.c.
References __mdt_init_ucred().
Referenced by mdt_getattr_name(), and mdt_intent_getattr().
int mdt_init_ucred_reint (struct mdt_thread_info * info)
Definition at line 612 of file mdt_lib.c.
References LASSERT, mdt_exit_ucred(), mdt_info_req(), mdt_ucred(), new_init_ucred(), old_init_ucred_reint(), REC_INIT, ptlrpc_request::rq_auth_gss, ptlrpc_request::rq_auth_usr_mdt, lu_ucred::uc_valid, UCRED_NEW, and UCRED_OLD.
Referenced by mdt_close_unpack(), mdt_reint_internal(), and mdt_reint_setxattr().
static int mdt_intent_close_unpack (struct mdt_thread_info * info) [static]
Definition at line 1035 of file mdt_lib.c.
References ENTRY, md_attr::ma_attr_flags, MDS_CLOSE_LAYOUT_SWAP, MDS_HSM_RELEASE, mdt_thread_info::mti_attr, mdt_thread_info::mti_pill, RCL_CLIENT, req_capsule_extend(), req_capsule_field_present(), req_capsule_has_field(), RETURN, RMF_CLOSE_DATA, and RQF_MDS_INTENT_CLOSE.
Referenced by mdt_close_unpack().
static int mdt_link_unpack (struct mdt_thread_info * info) [static]
Definition at line 1142 of file mdt_lib.c.
References CLASSERT, ENTRY, LA_CTIME, lu_attr::la_ctime, LA_GID, lu_attr::la_gid, LA_MTIME, lu_attr::la_mtime, LA_UID, lu_attr::la_uid, lu_attr::la_valid, mdt_rec_link::lk_cap, mdt_rec_link::lk_fid1, mdt_rec_link::lk_fid2, mdt_rec_link::lk_fsgid, mdt_rec_link::lk_fsuid, mdt_rec_link::lk_suppgid1, mdt_rec_link::lk_suppgid2, mdt_rec_link::lk_time, md_attr::ma_attr, mdt_dlmreq_unpack(), mdt_name_unpack(), mdt_ucred(), mdt_thread_info::mti_attr, mdt_thread_info::mti_pill, mdt_thread_info::mti_rr, req_capsule_client_get(), RETURN, RMF_NAME, RMF_REC_REINT, mdt_reint_record::rr_fid1, mdt_reint_record::rr_fid2, mdt_reint_record::rr_name, lu_ucred::uc_cap, lu_ucred::uc_fsgid, lu_ucred::uc_fsuid, and lu_ucred::uc_suppgids.
int mdt_name_unpack (struct req_capsule * pill, const struct req_msg_field * field, struct lu_name * ln, enum mdt_name_flags flags)
Definition at line 882 of file mdt_lib.c.
References lu_name::ln_name, lu_name::ln_namelen, lu_name_is_valid(), MNF_FIX_ANON, RCL_CLIENT, req_capsule_client_get(), and req_capsule_get_size().
Referenced by mdt_create_unpack(), mdt_getattr_name_lock(), mdt_link_unpack(), mdt_open_unpack(), mdt_rename_unpack(), mdt_setxattr_unpack(), and mdt_unlink_unpack().
static int mdt_open_unpack (struct mdt_thread_info * info) [static]
Definition at line 1320 of file mdt_lib.c.
References CLASSERT, mdt_rec_create::cr_bias, mdt_rec_create::cr_cap, mdt_rec_create::cr_fid1, mdt_rec_create::cr_fid2, mdt_rec_create::cr_fsgid, mdt_rec_create::cr_fsuid, mdt_rec_create::cr_mode, mdt_rec_create::cr_old_handle, mdt_rec_create::cr_rdev, mdt_rec_create::cr_suppgid1, mdt_rec_create::cr_suppgid2, mdt_rec_create::cr_time, mdt_rec_create::cr_umask, ENTRY, get_mrc_cr_flags(), LA_ATIME, lu_attr::la_atime, LA_CTIME, lu_attr::la_ctime, LA_GID, lu_attr::la_gid, LA_MODE, lu_attr::la_mode, LA_MTIME, lu_attr::la_mtime, LA_RDEV, lu_attr::la_rdev, LA_UID, lu_attr::la_uid, lu_attr::la_valid, md_attr::ma_attr, MDS_CROSS_REF, MDS_OPEN_DELAY_CREATE, mdt_fix_lov_magic(), mdt_info_req(), mdt_name_unpack(), mdt_ucred(), MIN_MD_SIZE, MNF_FIX_ANON, mdt_thread_info::mti_attr, mdt_thread_info::mti_cross_ref, mdt_thread_info::mti_pill, mdt_thread_info::mti_rr, mdt_thread_info::mti_spec, md_op_spec::no_create, RCL_CLIENT, req_capsule_client_get(), req_capsule_field_present(), req_capsule_get_size(), req_is_replay(), RETURN, RMF_EADATA, RMF_NAME, RMF_REC_REINT, mdt_reint_record::rr_eadata, mdt_reint_record::rr_eadatalen, mdt_reint_record::rr_fid1, mdt_reint_record::rr_fid2, mdt_reint_record::rr_handle, mdt_reint_record::rr_name, md_op_spec::sp_cr_flags, md_op_spec::sp_ea, md_op_spec::u, lu_ucred::uc_cap, lu_ucred::uc_fsgid, lu_ucred::uc_fsuid, lu_ucred::uc_suppgids, lu_ucred::uc_umask, and unlikely.
int mdt_reint_unpack (struct mdt_thread_info * info, __u32 op)
Definition at line 1464 of file mdt_lib.c.
References CERROR, ENTRY, mdt_reint_unpackers, mdt_thread_info::mti_rr, REINT_MAX, RETURN, and mdt_reint_record::rr_opcode.
Referenced by mdt_reint_internal().
static int mdt_rename_unpack (struct mdt_thread_info * info) [static]
Definition at line 1234 of file mdt_lib.c.
References CLASSERT, ENTRY, LA_CTIME, lu_attr::la_ctime, LA_GID, lu_attr::la_gid, LA_MODE, lu_attr::la_mode, LA_MTIME, lu_attr::la_mtime, LA_UID, lu_attr::la_uid, lu_attr::la_valid, md_attr::ma_attr, md_attr::ma_attr_flags, MDS_RENAME_MIGRATE, MDS_VTX_BYPASS, mdt_close_handle_unpack(), mdt_dlmreq_unpack(), mdt_info_req(), mdt_name_unpack(), mdt_ucred(), mdt_thread_info::mti_attr, mdt_thread_info::mti_pill, mdt_thread_info::mti_rr, mdt_thread_info::mti_spec, md_op_spec::no_create, req_capsule_client_get(), req_capsule_extend(), req_is_replay(), RETURN, RMF_NAME, RMF_REC_REINT, RMF_SYMTGT, mdt_rec_rename::rn_bias, mdt_rec_rename::rn_cap, mdt_rec_rename::rn_fid1, mdt_rec_rename::rn_fid2, mdt_rec_rename::rn_fsgid, mdt_rec_rename::rn_fsuid, mdt_rec_rename::rn_mode, mdt_rec_rename::rn_suppgid1, mdt_rec_rename::rn_suppgid2, mdt_rec_rename::rn_time, RQF_MDS_REINT_MIGRATE, mdt_reint_record::rr_fid1, mdt_reint_record::rr_fid2, mdt_reint_record::rr_name, mdt_reint_record::rr_tgt_name, md_op_spec::sp_migrate_close, lu_ucred::uc_cap, lu_ucred::uc_fsgid, lu_ucred::uc_fsuid, and lu_ucred::uc_suppgids.
static int mdt_rmentry_unpack (struct mdt_thread_info * info) [static]
Definition at line 1228 of file mdt_lib.c.
References mdt_unlink_unpack(), mdt_thread_info::mti_spec, and md_op_spec::sp_rm_entry.
static int mdt_root_squash (struct mdt_thread_info * info, lnet_nid_t peernid) [static]
Definition at line 99 of file mdt_lib.c.
References CDEBUG, D_OTHER, ENTRY, LASSERT, libcfs_nid2str(), match_nosquash_list(), mdt_device::mdt_squash, mdt_ucred(), mdt_thread_info::mti_mdt, RETURN, root_squash_info::rsi_gid, root_squash_info::rsi_nosquash_nids, root_squash_info::rsi_sem, root_squash_info::rsi_uid, lu_ucred::uc_cap, lu_ucred::uc_fsgid, lu_ucred::uc_fsuid, and lu_ucred::uc_suppgids.
Referenced by new_init_ucred(), and old_init_ucred_common().
static int mdt_setattr_unpack (struct mdt_thread_info * info) [static]
Definition at line 997 of file mdt_lib.c.
References ENTRY, le32_to_cpu, LMV_USER_MAGIC, lmv_user_md, md_attr::ma_lmm, md_attr::ma_lmm_size, md_attr::ma_lmv, MA_LMV, md_attr::ma_lmv_size, MA_LOV, md_attr::ma_valid, mdt_dlmreq_unpack(), mdt_setattr_unpack_rec(), mdt_thread_info::mti_attr, mdt_thread_info::mti_pill, mdt_thread_info::mti_rr, RCL_CLIENT, req_capsule_client_get(), req_capsule_field_present(), req_capsule_get_size(), RETURN, RMF_EADATA, mdt_reint_record::rr_eadata, and mdt_reint_record::rr_eadatalen.
static int mdt_setattr_unpack_rec (struct mdt_thread_info * info) [static]
Definition at line 909 of file mdt_lib.c.
References CLASSERT, ENTRY, lu_attr::la_atime, lu_attr::la_blocks, lu_attr::la_ctime, lu_attr::la_flags, lu_attr::la_gid, lu_attr::la_mode, lu_attr::la_mtime, lu_attr::la_size, lu_attr::la_uid, lu_attr::la_valid, md_attr::ma_attr, md_attr::ma_attr_flags, MA_INODE, md_attr::ma_valid, MDS_CLOSE_LAYOUT_SWAP, MDS_DATA_MODIFIED, MDS_HSM_RELEASE, mdt_attr_valid_xlate(), mdt_ucred(), mdt_thread_info::mti_attr, mdt_thread_info::mti_exp, mdt_thread_info::mti_pill, mdt_thread_info::mti_rr, NODEMAP_CLIENT_TO_FS, NODEMAP_GID, nodemap_map_id(), NODEMAP_UID, req_capsule_client_get(), RETURN, RMF_REC_REINT, mdt_reint_record::rr_fid1, mdt_rec_setattr::sa_atime, mdt_rec_setattr::sa_attr_flags, mdt_rec_setattr::sa_bias, mdt_rec_setattr::sa_blocks, mdt_rec_setattr::sa_cap, mdt_rec_setattr::sa_ctime, mdt_rec_setattr::sa_fid, mdt_rec_setattr::sa_fsgid, mdt_rec_setattr::sa_fsuid, mdt_rec_setattr::sa_gid, mdt_rec_setattr::sa_mode, mdt_rec_setattr::sa_mtime, mdt_rec_setattr::sa_size, mdt_rec_setattr::sa_suppgid, mdt_rec_setattr::sa_uid, mdt_rec_setattr::sa_valid, lu_ucred::uc_cap, lu_ucred::uc_fsgid, lu_ucred::uc_fsuid, and lu_ucred::uc_suppgids.
Referenced by mdt_close_unpack(), and mdt_setattr_unpack().
static int mdt_setxattr_unpack (struct mdt_thread_info * info) [static]
Definition at line 1391 of file mdt_lib.c.
References CDEBUG, CLASSERT, D_INFO, ENTRY, lu_attr::la_ctime, lu_attr::la_flags, lu_attr::la_size, lu_attr::la_valid, md_attr::ma_attr, mdt_dlmreq_unpack(), mdt_name_unpack(), mdt_ucred(), mdt_thread_info::mti_attr, mdt_thread_info::mti_pill, mdt_thread_info::mti_rr, OBD_MD_FLXATTRRM, RCL_CLIENT, req_capsule_client_get(), req_capsule_field_present(), req_capsule_get_size(), RETURN, RMF_EADATA, RMF_NAME, RMF_REC_REINT, mdt_reint_record::rr_eadata, mdt_reint_record::rr_eadatalen, mdt_reint_record::rr_fid1, mdt_reint_record::rr_name, mdt_reint_record::rr_opcode, mdt_rec_setxattr::sx_cap, mdt_rec_setxattr::sx_fid, mdt_rec_setxattr::sx_flags, mdt_rec_setxattr::sx_fsgid, mdt_rec_setxattr::sx_fsuid, mdt_rec_setxattr::sx_opcode, mdt_rec_setxattr::sx_size, mdt_rec_setxattr::sx_suppgid1, mdt_rec_setxattr::sx_time, mdt_rec_setxattr::sx_valid, lu_ucred::uc_cap, lu_ucred::uc_fsgid, lu_ucred::uc_fsuid, and lu_ucred::uc_suppgids.
static int mdt_unlink_unpack (struct mdt_thread_info * info) [static]
Definition at line 1181 of file mdt_lib.c.
References CLASSERT, ENTRY, LA_CTIME, lu_attr::la_ctime, LA_GID, lu_attr::la_gid, LA_MODE, lu_attr::la_mode, LA_MTIME, lu_attr::la_mtime, LA_UID, lu_attr::la_uid, lu_attr::la_valid, md_attr::ma_attr, md_attr::ma_attr_flags, MDS_VTX_BYPASS, mdt_dlmreq_unpack(), mdt_info_req(), mdt_name_unpack(), mdt_ucred(), mdt_thread_info::mti_attr, mdt_thread_info::mti_pill, mdt_thread_info::mti_rr, mdt_thread_info::mti_spec, md_op_spec::no_create, req_capsule_client_get(), req_is_replay(), RETURN, RMF_NAME, RMF_REC_REINT, mdt_reint_record::rr_fid1, mdt_reint_record::rr_fid2, mdt_reint_record::rr_name, lu_ucred::uc_cap, lu_ucred::uc_fsgid, lu_ucred::uc_fsuid, lu_ucred::uc_suppgids, mdt_rec_unlink::ul_bias, mdt_rec_unlink::ul_cap, mdt_rec_unlink::ul_fid1, mdt_rec_unlink::ul_fid2, mdt_rec_unlink::ul_fsgid, mdt_rec_unlink::ul_fsuid, mdt_rec_unlink::ul_mode, mdt_rec_unlink::ul_suppgid1, and mdt_rec_unlink::ul_time.
Referenced by mdt_rmentry_unpack().
static int new_init_ucred (struct mdt_thread_info * info, ucred_init_type_t type, void * buf, bool drop_fs_cap) [static]
Definition at line 143 of file mdt_lib.c.
References BODY_INIT, CDEBUG, CERROR, CFS_CAP_CHOWN_MASK, CFS_CAP_FS_MASK, CFS_CAP_SYS_RESOURCE_MASK, CFS_RMTOWN_PERM, CFS_SETGID_PERM, CFS_SETGRP_PERM, CFS_SETUID_PERM, D_SEC, ENTRY, EXIT, exp_connect_rmtclient(), GOTO, is_identity_get_disabled(), LASSERT, libcfs_nid2str(), lustre_groups_from_list(), lustre_groups_sort(), make_kuid(), mdt_body::mbo_suppgid, mdt_device::mdt_identity_cache, mdt_identity_get(), mdt_identity_get_perm(), mdt_identity_put(), mdt_info_req(), mdt_root_squash(), mdt_ucred(), md_identity::mi_gid, mdt_thread_info::mti_exp, mdt_thread_info::mti_mdt, lnet_process_id_t::nid, ptlrpc_user_desc_do_idmap(), ptlrpc_user_desc::pud_cap, ptlrpc_user_desc::pud_fsgid, ptlrpc_user_desc::pud_fsuid, ptlrpc_user_desc::pud_gid, ptlrpc_user_desc::pud_groups, ptlrpc_user_desc::pud_ngroups, ptlrpc_user_desc::pud_uid, RETURN, ptlrpc_request::rq_auth_gss, ptlrpc_request::rq_auth_usr_mdt, ptlrpc_request::rq_peer, lu_ucred::uc_cap, lu_ucred::uc_fsgid, lu_ucred::uc_fsuid, lu_ucred::uc_gid, lu_ucred::uc_ginfo, lu_ucred::uc_identity, lu_ucred::uc_o_fsgid, lu_ucred::uc_o_fsuid, lu_ucred::uc_o_gid, lu_ucred::uc_o_uid, lu_ucred::uc_suppgids, lu_ucred::uc_uid, lu_ucred::uc_valid, UCRED_INVALID, UCRED_NEW, ucred_set_jobid(), uid_valid(), and unlikely.
Referenced by __mdt_init_ucred(), and mdt_init_ucred_reint().
static int old_init_ucred (struct mdt_thread_info * info, struct mdt_body * body, bool drop_fs_cap) [static]
Definition at line 518 of file mdt_lib.c.
References ENTRY, LASSERT, mdt_body::mbo_capability, mdt_body::mbo_fsgid, mdt_body::mbo_fsuid, mdt_body::mbo_gid, mdt_body::mbo_suppgid, mdt_body::mbo_uid, mdt_ucred(), mdt_thread_info::mti_exp, NODEMAP_CLIENT_TO_FS, NODEMAP_GID, nodemap_map_id(), NODEMAP_UID, old_init_ucred_common(), RETURN, lu_ucred::uc_cap, lu_ucred::uc_fsgid, lu_ucred::uc_fsuid, lu_ucred::uc_gid, lu_ucred::uc_ginfo, lu_ucred::uc_o_fsgid, lu_ucred::uc_o_fsuid, lu_ucred::uc_o_gid, lu_ucred::uc_o_uid, lu_ucred::uc_suppgids, lu_ucred::uc_uid, lu_ucred::uc_valid, and UCRED_INVALID.
Referenced by __mdt_init_ucred().
static int old_init_ucred_common (struct mdt_thread_info * info, bool drop_fs_cap) [static]
Definition at line 466 of file mdt_lib.c.
References CDEBUG, CFS_CAP_FS_MASK, D_SEC, obd_export::exp_client_uuid, is_identity_get_disabled(), mdt2obd_dev(), mdt_device::mdt_identity_cache, mdt_identity_get(), mdt_info_req(), mdt_root_squash(), mdt_ucred(), mdt_thread_info::mti_exp, mdt_thread_info::mti_mdt, lu_nodemap::nm_squash_gid, lu_nodemap::nm_squash_uid, RETURN, lu_ucred::uc_cap, lu_ucred::uc_fsgid, lu_ucred::uc_fsuid, lu_ucred::uc_identity, lu_ucred::uc_o_uid, lu_ucred::uc_suppgids, lu_ucred::uc_valid, UCRED_OLD, ucred_set_jobid(), unlikely, and obd_uuid::uuid.
Referenced by old_init_ucred(), and old_init_ucred_reint().
static int old_init_ucred_reint (struct mdt_thread_info * info) [static]
Definition at line 552 of file mdt_lib.c.
References ENTRY, LASSERT, mdt_ucred(), mdt_thread_info::mti_exp, NODEMAP_CLIENT_TO_FS, NODEMAP_GID, nodemap_map_id(), NODEMAP_UID, old_init_ucred_common(), RETURN, lu_ucred::uc_fsgid, lu_ucred::uc_fsuid, lu_ucred::uc_gid, lu_ucred::uc_ginfo, lu_ucred::uc_o_fsgid, lu_ucred::uc_o_fsuid, lu_ucred::uc_o_gid, lu_ucred::uc_o_uid, lu_ucred::uc_uid, lu_ucred::uc_valid, and UCRED_INVALID.
Referenced by mdt_init_ucred_reint().
static void ucred_set_jobid (struct mdt_thread_info * info, struct lu_ucred * uc) [static]
Definition at line 131 of file mdt_lib.c.
References mdt_info_req(), mdt_req_get_jobid(), strlcpy(), and lu_ucred::uc_jobid.
Referenced by new_init_ucred(), and old_init_ucred_common().
Variable Documentation
reint_unpacker mdt_reint_unpackers[REINT_MAX] [static]
Initial value:
 {
        [REINT_SETATTR]  = mdt_setattr_unpack,
        [REINT_CREATE]   = mdt_create_unpack,
        [REINT_LINK]     = mdt_link_unpack,
        [REINT_UNLINK]   = mdt_unlink_unpack,
        [REINT_RENAME]   = mdt_rename_unpack,
        [REINT_OPEN]     = mdt_open_unpack,
        [REINT_SETXATTR] = mdt_setxattr_unpack,
        [REINT_RMENTRY]  = mdt_rmentry_unpack,
        [REINT_MIGRATE]  = mdt_rename_unpack,
}
Definition at line 1452 of file mdt_lib.c.
Referenced by mdt_reint_unpack().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.