Lustre: lustre/mdt/mdt_hsm_cdt_requests.c File Reference
lustre/mdt/mdt_hsm_cdt_requests.c File Reference
#include <obd_support.h>
#include <lustre/lustre_user.h>
#include <lprocfs_status.h>
#include "mdt_internal.h"
Data Structures
struct req_interval_data
Defines
#define DEBUG_SUBSYSTEM S_MDS
#define NODE_VECTOR_SZ 256
Functions
void dump_requests (char *prefix, struct coordinator *cdt)
dump requests list
static enum interval_iter req_interval_cb (struct interval_node *node, void *args)
interval tree cb, used to go through all the tree of extent done
void mdt_cdt_get_work_done (struct cdt_agent_req *car, __u64 *done_sz)
scan the interval tree associated to a request to compute the amount of work done
static void mdt_cdt_free_request_tree (struct cdt_req_progress *crp)
free the interval tree associated to a request
static int hsm_update_work (struct cdt_req_progress *crp, const struct hsm_extent *extent)
update data moved information during a request
static void mdt_cdt_init_request_tree (struct cdt_req_progress *crp)
init the interval tree associated to a request
struct cdt_agent_req * mdt_cdt_alloc_request (__u64 compound_id, __u32 archive_id, __u64 flags, struct obd_uuid *uuid, struct hsm_action_item *hai)
Allocate/init an agent request and its sub-structures.
void mdt_cdt_free_request (struct cdt_agent_req *car)
Free an agent request and its sub-structures.
void mdt_cdt_get_request (struct cdt_agent_req *car)
inc refcount of a request
void mdt_cdt_put_request (struct cdt_agent_req *car)
dec refcount of a request free if no more refcount
static struct cdt_agent_req * cdt_find_request_nolock (struct coordinator *cdt, __u64 cookie, const struct lu_fid *fid)
find request in the list by cookie or by fid lock cdt_request_lock needs to be held by caller
int mdt_cdt_add_request (struct coordinator *cdt, struct cdt_agent_req *new_car)
add a request to the list
struct cdt_agent_req * mdt_cdt_find_request (struct coordinator *cdt, const __u64 cookie, const struct lu_fid *fid)
find request in the list by cookie or by fid
int mdt_cdt_remove_request (struct coordinator *cdt, __u64 cookie)
remove request from the list
struct cdt_agent_req * mdt_cdt_update_request (struct coordinator *cdt, const struct hsm_progress_kernel *pgs)
update a request in the list on success, add a ref to the request returned
static void * mdt_hsm_active_requests_proc_start (struct seq_file *s, loff_t *p)
seq_file method called to start access to /proc file
static void * mdt_hsm_active_requests_proc_next (struct seq_file *s, void *v, loff_t *p)
seq_file method called to get next item just returns NULL at eof
static int mdt_hsm_active_requests_proc_show (struct seq_file *s, void *v)
display request data
static void mdt_hsm_active_requests_proc_stop (struct seq_file *s, void *v)
seq_file method called to stop access to /proc file
static int lprocfs_open_hsm_active_requests (struct inode *inode, struct file *file)
public function called at open of /proc file to get list of agents
Variables
static struct seq_operations mdt_hsm_active_requests_proc_ops
struct file_operations mdt_hsm_active_requests_fops
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 37 of file mdt_hsm_cdt_requests.c.
#define NODE_VECTOR_SZ 256
Definition at line 113 of file mdt_hsm_cdt_requests.c.
Referenced by hsm_update_work(), and mdt_cdt_free_request_tree().
Function Documentation
static struct cdt_agent_req* cdt_find_request_nolock (struct coordinator * cdt, __u64 cookie, const struct lu_fid * fid) [static, read]
find request in the list by cookie or by fid lock cdt_request_lock needs to be held by caller
Parameters:
cdt [IN] coordinator
cookie [IN] request cookie
fid [IN] fid
Return values:
request pointer or NULL if not found
Definition at line 309 of file mdt_hsm_cdt_requests.c.
References cdt_agent_req::car_hai, cdt_agent_req::car_request_list, coordinator::cdt_requests, ENTRY, hsm_action_item::hai_cookie, hsm_action_item::hai_fid, list_for_each_entry, lu_fid_eq(), mdt_cdt_get_request(), and RETURN.
Referenced by mdt_cdt_add_request(), mdt_cdt_find_request(), and mdt_cdt_remove_request().
void dump_requests (char * prefix, struct coordinator * cdt)
dump requests list
Parameters:
cdt [IN] coordinator
Definition at line 48 of file mdt_hsm_cdt_requests.c.
References cdt_agent_req::car_archive_id, cdt_agent_req::car_canceled, cdt_agent_req::car_compound_id, cdt_agent_req::car_flags, cdt_agent_req::car_hai, cdt_agent_req::car_refcount, cdt_agent_req::car_request_list, CDEBUG, coordinator::cdt_request_lock, coordinator::cdt_requests, D_HSM, DFID, hsm_action_item::hai_action, hsm_action_item::hai_cookie, hsm_action_item::hai_dfid, hsm_action_item::hai_extent, hsm_action_item::hai_fid, hsm_action_item::hai_gid, hsm_copytool_action2name(), hsm_extent::length, list_for_each_entry, LPX64, hsm_extent::offset, and PFID.
Referenced by mdt_hsm_cdt_start().
static int hsm_update_work (struct cdt_req_progress * crp, const struct hsm_extent * extent) [static]
update data moved information during a request
Definition at line 154 of file mdt_hsm_cdt_requests.c.
References __u64, cdt_req_progress::crp_cnt, cdt_req_progress::crp_lock, cdt_req_progress::crp_max, cdt_req_progress::crp_node, cdt_req_progress::crp_root, end, ENTRY, GOTO, interval_insert(), interval_set(), hsm_extent::length, NODE_VECTOR_SZ, OBD_ALLOC, OBD_FREE, hsm_extent::offset, and RETURN.
Referenced by mdt_cdt_update_request().
static int lprocfs_open_hsm_active_requests (struct inode * inode, struct file * file) [static]
public function called at open of /proc file to get list of agents
Definition at line 571 of file mdt_hsm_cdt_requests.c.
References ENTRY, mdt_hsm_active_requests_proc_ops, and RETURN.
int mdt_cdt_add_request (struct coordinator * cdt, struct cdt_agent_req * new_car)
add a request to the list
Parameters:
cdt [IN] coordinator
car [IN] request
Return values:
0 success
-ve failure
Definition at line 336 of file mdt_hsm_cdt_requests.c.
References cdt_agent_req::car_hai, cdt_agent_req::car_request_list, cdt_agent_req::car_uuid, cdt_find_request_nolock(), coordinator::cdt_request_count, coordinator::cdt_request_lock, coordinator::cdt_requests, ENTRY, hsm_action_item::hai_action, hsm_action_item::hai_cookie, HSMA_CANCEL, LASSERT, list_add_tail(), mdt_cdt_put_request(), mdt_hsm_agent_update_statistics(), and RETURN.
Referenced by mdt_hsm_add_hal().
struct cdt_agent_req* mdt_cdt_alloc_request (__u64 compound_id, __u32 archive_id, __u64 flags, struct obd_uuid * uuid, struct hsm_action_item * hai) [read]
Allocate/init an agent request and its sub-structures.
Parameters:
compound_id [IN]
archive_id [IN]
flags [IN]
uuid [IN]
hai [IN]
Return values:
car [OUT] success valid structure
car [OUT]
Definition at line 238 of file mdt_hsm_cdt_requests.c.
References cdt_agent_req::car_archive_id, cdt_agent_req::car_canceled, cdt_agent_req::car_compound_id, cdt_agent_req::car_flags, cdt_agent_req::car_hai, cdt_agent_req::car_progress, cdt_agent_req::car_refcount, cdt_agent_req::car_req_start, cdt_agent_req::car_req_update, cdt_agent_req::car_uuid, cfs_time_current_sec(), ENTRY, hsm_action_item::hai_len, mdt_cdt_init_request_tree(), mdt_hsm_car_kmem, OBD_ALLOC, OBD_SLAB_ALLOC_PTR, OBD_SLAB_FREE_PTR, and RETURN.
Referenced by mdt_hsm_add_hal().
struct cdt_agent_req* mdt_cdt_find_request (struct coordinator * cdt, const __u64 cookie, const struct lu_fid * fid) [read]
find request in the list by cookie or by fid
Parameters:
cdt [IN] coordinator
cookie [IN] request cookie
fid [IN] fid
Return values:
request pointer or NULL if not found
Definition at line 369 of file mdt_hsm_cdt_requests.c.
References cdt_find_request_nolock(), coordinator::cdt_request_lock, ENTRY, and RETURN.
Referenced by mdt_cdt_update_request(), mdt_coordinator_cb(), mdt_hsm_add_hal(), mdt_hsm_get_actions(), and mdt_hsm_get_running().
void mdt_cdt_free_request (struct cdt_agent_req * car)
Free an agent request and its sub-structures.
Parameters:
car [IN] Request to be freed.
Definition at line 273 of file mdt_hsm_cdt_requests.c.
References cdt_agent_req::car_hai, cdt_agent_req::car_progress, hsm_action_item::hai_len, mdt_cdt_free_request_tree(), mdt_hsm_car_kmem, OBD_FREE, and OBD_SLAB_FREE_PTR.
Referenced by mdt_cdt_put_request(), mdt_hsm_add_hal(), and mdt_hsm_cdt_stop().
static void mdt_cdt_free_request_tree (struct cdt_req_progress * crp) [static]
free the interval tree associated to a request
Definition at line 117 of file mdt_hsm_cdt_requests.c.
References cdt_req_progress::crp_cnt, cdt_req_progress::crp_lock, cdt_req_progress::crp_max, cdt_req_progress::crp_node, cdt_req_progress::crp_root, ENTRY, EXIT, interval_erase(), NODE_VECTOR_SZ, and OBD_FREE.
Referenced by mdt_cdt_free_request().
void mdt_cdt_get_request (struct cdt_agent_req * car)
inc refcount of a request
Parameters:
car [IN] request
Definition at line 284 of file mdt_hsm_cdt_requests.c.
References cdt_agent_req::car_refcount.
Referenced by cdt_find_request_nolock(), and hsm_cancel_all_actions().
void mdt_cdt_get_work_done (struct cdt_agent_req * car, __u64 * done_sz)
scan the interval tree associated to a request to compute the amount of work done
Parameters:
car [IN] request
done_sz [OUT] will be set to the size of work done
Definition at line 98 of file mdt_hsm_cdt_requests.c.
References cdt_agent_req::car_progress, req_interval_data::crp, cdt_req_progress::crp_lock, cdt_req_progress::crp_root, req_interval_data::done_sz, interval_iterate(), and req_interval_cb().
Referenced by mdt_hsm_active_requests_proc_show(), and mdt_hsm_get_actions().
static void mdt_cdt_init_request_tree (struct cdt_req_progress * crp) [static]
init the interval tree associated to a request
Definition at line 220 of file mdt_hsm_cdt_requests.c.
References cdt_req_progress::crp_cnt, cdt_req_progress::crp_lock, cdt_req_progress::crp_max, and cdt_req_progress::crp_root.
Referenced by mdt_cdt_alloc_request().
void mdt_cdt_put_request (struct cdt_agent_req * car)
dec refcount of a request free if no more refcount
Parameters:
car [IN] request
Definition at line 294 of file mdt_hsm_cdt_requests.c.
References cdt_agent_req::car_refcount, LASSERT, and mdt_cdt_free_request().
Referenced by hsm_cancel_all_actions(), mdt_cdt_add_request(), mdt_cdt_remove_request(), mdt_cdt_update_request(), mdt_coordinator_cb(), mdt_hsm_add_hal(), mdt_hsm_get_actions(), mdt_hsm_get_running(), and mdt_hsm_update_request_state().
int mdt_cdt_remove_request (struct coordinator * cdt, __u64 cookie)
remove request from the list
Parameters:
cdt [IN] coordinator
cookie [IN] request cookie
Return values:
request pointer
Definition at line 389 of file mdt_hsm_cdt_requests.c.
References cdt_agent_req::car_request_list, cdt_find_request_nolock(), coordinator::cdt_request_count, coordinator::cdt_request_lock, ENTRY, LASSERT, list_del(), mdt_cdt_put_request(), and RETURN.
Referenced by mdt_hsm_agent_send(), and mdt_hsm_update_request_state().
struct cdt_agent_req* mdt_cdt_update_request (struct coordinator * cdt, const struct hsm_progress_kernel * pgs) [read]
update a request in the list on success, add a ref to the request returned
Parameters:
cdt [IN] coordinator
pgs [IN] progression (cookie + extent + err)
Return values:
request pointer
-ve failure
Definition at line 424 of file mdt_hsm_cdt_requests.c.
References cdt_agent_req::car_progress, cdt_agent_req::car_req_update, cdt_agent_req::car_uuid, cfs_time_current_sec(), ENTRY, HP_FLAG_COMPLETED, hsm_progress_kernel::hpk_cookie, hsm_progress_kernel::hpk_errval, hsm_progress_kernel::hpk_extent, hsm_progress_kernel::hpk_flags, hsm_update_work(), hsm_extent::length, mdt_cdt_find_request(), mdt_cdt_put_request(), mdt_hsm_agent_update_statistics(), and RETURN.
Referenced by mdt_hsm_update_request_state().
static void* mdt_hsm_active_requests_proc_next (struct seq_file * s, void * v, loff_t * p) [static]
seq_file method called to get next item just returns NULL at eof
Definition at line 489 of file mdt_hsm_cdt_requests.c.
References coordinator::cdt_requests, ENTRY, mdt_device::mdt_coordinator, list_head::next, and RETURN.
static int mdt_hsm_active_requests_proc_show (struct seq_file * s, void * v) [static]
display request data
Definition at line 512 of file mdt_hsm_cdt_requests.c.
References __u64, buf, cdt_agent_req::car_archive_id, cdt_agent_req::car_canceled, cdt_agent_req::car_compound_id, cdt_agent_req::car_flags, cdt_agent_req::car_hai, cdt_agent_req::car_request_list, cdt_agent_req::car_uuid, DFID, ENTRY, hsm_action_item::hai_action, hsm_action_item::hai_cookie, hsm_action_item::hai_dfid, hai_dump_data_field(), hsm_action_item::hai_extent, hsm_action_item::hai_fid, hsm_action_item::hai_gid, hsm_copytool_action2name(), hsm_extent::length, list_entry, LPU64, LPX64, mdt_cdt_get_work_done(), obd_uuid2str(), hsm_extent::offset, PFID, and RETURN.
static void* mdt_hsm_active_requests_proc_start (struct seq_file * s, loff_t * p) [static]
seq_file method called to start access to /proc file
Definition at line 460 of file mdt_hsm_cdt_requests.c.
References coordinator::cdt_request_lock, coordinator::cdt_requests, ENTRY, list_empty(), list_for_each, mdt_device::mdt_coordinator, and RETURN.
static void mdt_hsm_active_requests_proc_stop (struct seq_file * s, void * v) [static]
seq_file method called to stop access to /proc file
Definition at line 548 of file mdt_hsm_cdt_requests.c.
References coordinator::cdt_request_lock, ENTRY, EXIT, and mdt_device::mdt_coordinator.
static enum interval_iter req_interval_cb (struct interval_node * node, void * args) [static]
interval tree cb, used to go through all the tree of extent done
Definition at line 81 of file mdt_hsm_cdt_requests.c.
References req_interval_data::done_sz, interval_node::interval_node_extent::end, ENTRY, interval_node::in_extent, INTERVAL_ITER_CONT, RETURN, and interval_node::interval_node_extent::start.
Referenced by mdt_cdt_get_work_done().
Variable Documentation
struct file_operations mdt_hsm_active_requests_fops
Initial value:
 {
        .owner          = THIS_MODULE,
        .open           = lprocfs_open_hsm_active_requests,
        .read           = seq_read,
        .llseek         = seq_lseek,
        .release        = lprocfs_seq_release,
}
Definition at line 589 of file mdt_hsm_cdt_requests.c.
struct seq_operations mdt_hsm_active_requests_proc_ops [static]
Initial value:
 {
        .start          = mdt_hsm_active_requests_proc_start,
        .next           = mdt_hsm_active_requests_proc_next,
        .show           = mdt_hsm_active_requests_proc_show,
        .stop           = mdt_hsm_active_requests_proc_stop,
}
Definition at line 560 of file mdt_hsm_cdt_requests.c.
Referenced by lprocfs_open_hsm_active_requests().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.