Lustre: lustre/mgc/mgc_request.c File Reference
lustre/mgc/mgc_request.c File Reference
#include <linux/module.h>
#include <linux/kthread.h>
#include <dt_object.h>
#include <lprocfs_status.h>
#include <lustre_dlm.h>
#include <lustre_disk.h>
#include <lustre_log.h>
#include <lustre_swab.h>
#include <obd_class.h>
#include "mgc_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_MGC
#define D_MGC D_CONFIG
#define RQ_RUNNING 0x1
#define RQ_NOW 0x2
#define RQ_LATER 0x4
#define RQ_STOP 0x8
#define RQ_PRECLEANUP 0x10
#define MGC_TIMEOUT_MIN_SECONDS 5
#define MGC_TIMEOUT_RAND_CENTISEC 0x1ff
#define MGC_ENQUEUE_LIMIT
#define MGC_TARGET_REG_LIMIT 10
#define MGC_SEND_PARAM_LIMIT 10
Enumerations
enum { CONFIG_READ_NRPAGES_INIT = 1 << (20 - PAGE_CACHE_SHIFT), CONFIG_READ_NRPAGES = 4 }
Functions
static int mgc_name2resid (char *name, int len, struct ldlm_res_id *res_id, int type)
int mgc_fsname2resid (char *fsname, struct ldlm_res_id *res_id, int type)
static int mgc_logname2resid (char *logname, struct ldlm_res_id *res_id, int type)
static DEFINE_SPINLOCK (config_list_lock)
static int config_log_get (struct config_llog_data *cld)
static void config_log_put (struct config_llog_data *cld)
static struct config_llog_data * config_log_find (char *logname, struct config_llog_instance *cfg)
static struct config_llog_data * do_config_log_add (struct obd_device *obd, char *logname, int type, struct config_llog_instance *cfg, struct super_block *sb)
static struct config_llog_data * config_recover_log_add (struct obd_device *obd, char *fsname, struct config_llog_instance *cfg, struct super_block *sb)
static struct config_llog_data * config_params_log_add (struct obd_device *obd, struct config_llog_instance *cfg, struct super_block *sb)
static int config_log_add (struct obd_device *obd, char *logname, struct config_llog_instance *cfg, struct super_block *sb)
Add this log to the list of active logs watched by an MGC.
DEFINE_MUTEX (llog_process_lock)
static int config_log_end (char *logname, struct config_llog_instance *cfg)
Stop watching for updates on this log.
static DECLARE_COMPLETION (rq_exit)
static DECLARE_COMPLETION (rq_start)
static void do_requeue (struct config_llog_data *cld)
static int mgc_requeue_thread (void *data)
static void mgc_requeue_add (struct config_llog_data *cld)
static int mgc_local_llog_init (const struct lu_env *env, struct obd_device *obd, struct obd_device *disk)
static int mgc_local_llog_fini (const struct lu_env *env, struct obd_device *obd)
static int mgc_fs_setup (const struct lu_env *env, struct obd_device *obd, struct super_block *sb)
static int mgc_fs_cleanup (const struct lu_env *env, struct obd_device *obd)
static int mgc_llog_init (const struct lu_env *env, struct obd_device *obd)
static int mgc_llog_fini (const struct lu_env *env, struct obd_device *obd)
static int mgc_precleanup (struct obd_device *obd)
static int mgc_cleanup (struct obd_device *obd)
static int mgc_setup (struct obd_device *obd, struct lustre_cfg *lcfg)
static int mgc_blocking_ast (struct ldlm_lock *lock, struct ldlm_lock_desc *desc, void *data, int flag)
static int mgc_set_mgs_param (struct obd_export *exp, struct mgs_send_param *msp)
static int mgc_enqueue (struct obd_export *exp, enum ldlm_type type, union ldlm_policy_data *policy, enum ldlm_mode mode, __u64 *flags, void *bl_cb, void *cp_cb, void *gl_cb, void *data, __u32 lvb_len, void *lvb_swabber, struct lustre_handle *lockh)
static int mgc_cancel (struct obd_export *exp, enum ldlm_mode mode, struct lustre_handle *lockh)
static void mgc_notify_active (struct obd_device *unused)
static int mgc_target_register (struct obd_export *exp, struct mgs_target_info *mti)
static int mgc_set_info_async (const struct lu_env *env, struct obd_export *exp, u32 keylen, void *key, u32 vallen, void *val, struct ptlrpc_request_set *set)
static int mgc_get_info (const struct lu_env *env, struct obd_export *exp, __u32 keylen, void *key, __u32 *vallen, void *val)
static int mgc_import_event (struct obd_device *obd, struct obd_import *imp, enum obd_import_event event)
static int mgc_apply_recover_logs (struct obd_device *mgc, struct config_llog_data *cld, __u64 max_version, void *data, int datalen, bool mne_swab)
static int mgc_process_recover_log (struct obd_device *obd, struct config_llog_data *cld)
This function is called if this client was notified for target restarting by the MGS.
static int mgc_llog_local_copy (const struct lu_env *env, struct obd_device *obd, struct llog_ctxt *rctxt, struct llog_ctxt *lctxt, char *logname)
static int mgc_process_cfg_log (struct obd_device *mgc, struct config_llog_data *cld, int local_only)
static bool mgc_import_in_recovery (struct obd_import *imp)
int mgc_process_log (struct obd_device *mgc, struct config_llog_data *cld)
Get a configuration log from the MGS and process it.
static int mgc_process_config (struct obd_device *obd, size_t len, void *buf)
Called from lustre_process_log.
static int __init mgc_init (void)
static void __exit mgc_exit (void)
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Management Client")
MODULE_VERSION (LUSTRE_VERSION_STRING)
MODULE_LICENSE ("GPL")
module_init (mgc_init)
module_exit (mgc_exit)
Variables
static struct list_head config_llog_list = LIST_HEAD_INIT(config_llog_list)
static int rq_state = 0
static wait_queue_head_t rq_waitq
static atomic_t mgc_count = ATOMIC_INIT(0)
static struct obd_ops mgc_obd_ops
Define Documentation
#define D_MGC D_CONFIG
Definition at line 42 of file mgc_request.c.
Referenced by config_log_add(), config_log_end(), config_log_put(), do_config_log_add(), do_requeue(), mgc_blocking_ast(), mgc_enqueue(), mgc_import_event(), mgc_name2resid(), mgc_process_cfg_log(), mgc_process_config(), mgc_process_log(), mgc_requeue_thread(), mgc_set_info_async(), and mgc_target_register().
#define DEBUG_SUBSYSTEM S_MGC
Definition at line 41 of file mgc_request.c.
#define MGC_ENQUEUE_LIMIT
Value:
(INITIAL_CONNECT_TIMEOUT + (AT_OFF ? 0 : at_min) \
                                + PING_INTERVAL)
Definition at line 1006 of file mgc_request.c.
Referenced by mgc_enqueue().
#define MGC_SEND_PARAM_LIMIT 10
Definition at line 1009 of file mgc_request.c.
Referenced by mgc_set_mgs_param().
#define MGC_TARGET_REG_LIMIT 10
Definition at line 1008 of file mgc_request.c.
Referenced by mgc_target_register().
#define MGC_TIMEOUT_MIN_SECONDS 5
Definition at line 543 of file mgc_request.c.
Referenced by mgc_requeue_thread().
#define MGC_TIMEOUT_RAND_CENTISEC 0x1ff
Definition at line 544 of file mgc_request.c.
Referenced by mgc_requeue_thread().
#define RQ_LATER 0x4
Definition at line 506 of file mgc_request.c.
Referenced by mgc_requeue_thread().
#define RQ_NOW 0x2
Definition at line 505 of file mgc_request.c.
Referenced by mgc_notify_active(), mgc_precleanup(), mgc_requeue_add(), and mgc_requeue_thread().
#define RQ_PRECLEANUP 0x10
Definition at line 508 of file mgc_request.c.
Referenced by mgc_precleanup(), and mgc_requeue_thread().
#define RQ_RUNNING 0x1
Definition at line 504 of file mgc_request.c.
Referenced by mgc_precleanup(), and mgc_requeue_thread().
#define RQ_STOP 0x8
Definition at line 507 of file mgc_request.c.
Referenced by mgc_precleanup(), mgc_requeue_add(), and mgc_requeue_thread().
Enumeration Type Documentation
anonymous enum
Enumerator:
CONFIG_READ_NRPAGES_INIT
CONFIG_READ_NRPAGES
Definition at line 1324 of file mgc_request.c.
Function Documentation
static int config_log_add (struct obd_device * obd, char * logname, struct config_llog_instance * cfg, struct super_block * sb) [static]
Add this log to the list of active logs watched by an MGC.
Active means we're watching for updates. We have one active log per "mount" - client instance or servername. Each instance may be at a different point in the log.
Definition at line 310 of file mgc_request.c.
References CDEBUG, CERROR, config_llog_instance::cfg_instance, config_llog_data::cld_params, config_llog_data::cld_recover, config_llog_data::cld_sptlrpc, config_log_find(), config_log_put(), config_params_log_add(), config_recover_log_add(), CONFIG_T_CONFIG, CONFIG_T_SPTLRPC, D_MGC, do_config_log_add(), ENTRY, GOTO, LASSERT, LMD_FLG_NOIR, obd_device::obd_name, and RETURN.
Referenced by mgc_process_config().
static int config_log_end (char * logname, struct config_llog_instance * cfg) [static]
Stop watching for updates on this log.
Definition at line 402 of file mgc_request.c.
References CDEBUG, config_llog_data::cld_lock, config_llog_data::cld_params, config_llog_data::cld_recover, config_llog_data::cld_sptlrpc, config_llog_data::cld_stopping, config_log_find(), config_log_put(), D_MGC, ENTRY, RETURN, and unlikely.
Referenced by mgc_process_config().
static struct config_llog_data* config_log_find (char * logname, struct config_llog_instance * cfg) [static, read]
Definition at line 168 of file mgc_request.c.
References config_llog_instance::cfg_instance, config_llog_data::cld_cfg, cld_is_sptlrpc(), config_llog_data::cld_list_chain, config_llog_data::cld_logname, config_llog_data::cld_refcount, config_llog_data::cld_stopping, ENTRY, LASSERT, list_for_each_entry, and RETURN.
Referenced by config_log_add(), config_log_end(), and mgc_process_config().
static int config_log_get (struct config_llog_data * cld) [static]
Definition at line 124 of file mgc_request.c.
References CDEBUG, config_llog_data::cld_logname, config_llog_data::cld_refcount, D_INFO, ENTRY, and RETURN.
Referenced by mgc_process_log(), and mgc_requeue_add().
static void config_log_put (struct config_llog_data * cld) [static]
Definition at line 135 of file mgc_request.c.
References CDEBUG, class_export_put(), cld_is_sptlrpc(), config_llog_data::cld_list_chain, config_llog_data::cld_logname, config_llog_data::cld_mgcexp, config_llog_data::cld_params, config_llog_data::cld_recover, config_llog_data::cld_refcount, config_llog_data::cld_sptlrpc, D_INFO, D_MGC, ENTRY, EXIT, LASSERT, list_del(), OBD_FREE, and sptlrpc_conf_log_stop().
Referenced by config_log_add(), config_log_end(), do_config_log_add(), mgc_blocking_ast(), mgc_process_config(), mgc_requeue_add(), and mgc_requeue_thread().
static struct config_llog_data* config_params_log_add (struct obd_device * obd, struct config_llog_instance * cfg, struct super_block * sb) [static, read]
Definition at line 291 of file mgc_request.c.
References config_llog_instance::cfg_instance, CONFIG_T_PARAMS, do_config_log_add(), and PARAMS_FILENAME.
Referenced by config_log_add().
static struct config_llog_data* config_recover_log_add (struct obd_device * obd, char * fsname, struct config_llog_instance * cfg, struct super_block * sb) [static, read]
Definition at line 257 of file mgc_request.c.
References config_llog_instance::cfg_instance, CONFIG_T_RECOVER, do_config_log_add(), IS_MDT, IS_OST, IS_SERVER, and LASSERT.
Referenced by config_log_add().
static DECLARE_COMPLETION (rq_start) [static]
static DECLARE_COMPLETION (rq_exit) [static]
DEFINE_MUTEX (llog_process_lock)
static DEFINE_SPINLOCK (config_list_lock) [static]
static struct config_llog_data* do_config_log_add (struct obd_device * obd, char * logname, int type, struct config_llog_instance * cfg, struct super_block * sb) [static, read]
Definition at line 200 of file mgc_request.c.
References CDEBUG, CERROR, config_llog_instance::cfg_callback, config_llog_instance::cfg_flags, config_llog_instance::cfg_instance, config_llog_instance::cfg_last_idx, config_llog_instance::cfg_obdname, config_llog_instance::cfg_sb, class_config_llog_handler(), class_export_get(), config_llog_data::cld_cfg, cld_is_sptlrpc(), config_llog_data::cld_list_chain, config_llog_data::cld_lock, config_llog_data::cld_logname, config_llog_data::cld_mgcexp, config_llog_data::cld_refcount, config_llog_data::cld_resid, config_llog_data::cld_type, config_log_put(), D_MGC, ENTRY, list_add(), mgc_logname2resid(), mgc_process_log(), OBD_ALLOC, obd_device::obd_name, obd_device::obd_self_export, RETURN, and sptlrpc_conf_log_start().
Referenced by config_log_add(), config_params_log_add(), and config_recover_log_add().
static void do_requeue (struct config_llog_data * cld) [static]
Definition at line 514 of file mgc_request.c.
References CDEBUG, CERROR, client_obd::cl_conn_count, client_obd::cl_sem, config_llog_data::cld_logname, config_llog_data::cld_mgcexp, config_llog_data::cld_refcount, obd_device::cli, D_MGC, ENTRY, EXIT, obd_export::exp_obd, LASSERT, mgc_process_log(), and obd_device::u.
Referenced by mgc_requeue_thread().
static int mgc_apply_recover_logs (struct obd_device * mgc, struct config_llog_data * cld, __u64 max_version, void * data, int datalen, bool mne_swab) [static]
Definition at line 1329 of file mgc_request.c.
References buf, CDEBUG, CERROR, config_llog_instance::cfg_instance, config_llog_instance::cfg_sb, client_obd::cl_import, client_obd::cl_sem, class_name2obd(), class_process_config(), config_llog_data::cld_cfg, config_llog_data::cld_logname, obd_device::cli, client_import_find_conn(), D_INFO, ENTRY, IS_MDT, IS_SERVER, LASSERT, LCFG_PARAM, LDD_F_SV_TYPE_OST, libcfs_nid2str(), LPD64, lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), lustre_swab_mgs_nidtbl_entry(), mgs_nidtbl_entry::mne_index, mgs_nidtbl_entry::mne_instance, mgs_nidtbl_entry::mne_length, mgs_nidtbl_entry::mne_nid_count, mgs_nidtbl_entry::mne_nid_size, mgs_nidtbl_entry::mne_nid_type, mgs_nidtbl_entry::mne_type, mgs_nidtbl_entry::mne_version, mgs_nidtbl_entry::nids, OBD_ALLOC, OBD_FREE, obd_device::obd_name, RETURN, server_name2svname(), mgs_nidtbl_entry::u, obd_device::u, and uuid.
Referenced by mgc_process_recover_log().
static int mgc_blocking_ast (struct ldlm_lock * lock, struct ldlm_lock_desc * desc, void * data, int flag) [static]
Definition at line 945 of file mgc_request.c.
References CDEBUG, client_obd::cl_conn_count, config_llog_data::cld_logname, config_llog_data::cld_refcount, config_llog_data::cld_stopping, obd_device::cli, config_log_put(), D_INFO, D_MGC, DLDLMRES, ENTRY, obd_export::exp_obd, ldlm_lock::l_conn_export, ldlm_lock::l_resource, LASSERT, LBUG, LCF_ASYNC, LDLM_CB_BLOCKING, LDLM_CB_CANCELING, ldlm_cli_cancel(), LDLM_DEBUG, ldlm_lock2handle(), ldlm_resource::lr_name, mgc_requeue_add(), ldlm_res_id::name, PLDLMRES, RETURN, and obd_device::u.
Referenced by mgc_enqueue().
static int mgc_cancel (struct obd_export * exp, enum ldlm_mode mode, struct lustre_handle * lockh) [static]
Definition at line 1097 of file mgc_request.c.
References ENTRY, ldlm_lock_decref(), and RETURN.
Referenced by mgc_process_log().
static int mgc_cleanup (struct obd_device * obd) [static]
Definition at line 873 of file mgc_request.c.
References class_del_profiles(), client_obd_cleanup(), ENTRY, lprocfs_obd_cleanup(), obd_device::obd_type, ptlrpcd_decref(), RETURN, and obd_type::typ_refcnt.
static int mgc_enqueue (struct obd_export * exp, enum ldlm_type type, union ldlm_policy_data * policy, enum ldlm_mode mode, __u64 * flags, void * bl_cb, void * cp_cb, void * gl_cb, void * data, __u32 lvb_len, void * lvb_swabber, struct lustre_handle * lockh) [static]
Definition at line 1049 of file mgc_request.c.
References CDEBUG, config_llog_instance::cfg_sb, class_exp2cliimp(), config_llog_data::cld_cfg, cld_is_sptlrpc(), config_llog_data::cld_logname, config_llog_data::cld_resid, D_MGC, ldlm_enqueue_info::ei_type, ENTRY, IS_SERVER, ldlm_cli_enqueue(), ldlm_completion_ast(), LDLM_ENQUEUE, LPX64, LUSTRE_DLM_VERSION, LVB_T_NONE, mgc_blocking_ast(), MGC_ENQUEUE_LIMIT, ldlm_res_id::name, ptlrpc_req_finished(), ptlrpc_request_alloc_pack(), ptlrpc_request_set_replen(), RCL_SERVER, req_capsule_set_size(), RETURN, RMF_DLM_LVB, ptlrpc_request::rq_pill, and RQF_LDLM_ENQUEUE.
Referenced by mgc_process_log().
static void __exit mgc_exit (void) [static]
Definition at line 2118 of file mgc_request.c.
References class_unregister_type(), and LUSTRE_MGC_NAME.
static int mgc_fs_cleanup (const struct lu_env * env, struct obd_device * obd) [static]
Definition at line 783 of file mgc_request.c.
References client_obd::cl_mgc_configs_dir, client_obd::cl_mgc_los, client_obd::cl_mgc_mutex, class_decref(), obd_device::cli, dt_object::do_lu, ENTRY, LASSERT, local_oid_storage_fini(), lu_object_put_nocache(), mgc_local_llog_fini(), RETURN, and obd_device::u.
Referenced by mgc_set_info_async().
static int mgc_fs_setup (const struct lu_env * env, struct obd_device * obd, struct super_block * sb) [static]
Definition at line 714 of file mgc_request.c.
References client_obd::cl_mgc_configs_dir, client_obd::cl_mgc_los, client_obd::cl_mgc_mutex, class_incref(), obd_device::cli, dt_device::dd_lu_dev, dt_object::do_lu, dt_locate_at(), dt_root_get(), ENTRY, EXIT, lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, FID_SEQ_LOCAL_NAME, GOTO, LASSERT, local_file_find_or_create(), local_oid_storage_fini(), local_oid_storage_init(), local_oid_storage::los_dev, lu_object_put(), lu_object_put_nocache(), mgc_local_llog_init(), MOUNT_CONFIGS_DIR, RETURN, obd_device::u, and unlikely.
Referenced by mgc_set_info_async().
int mgc_fsname2resid (char * fsname, struct ldlm_res_id * res_id, int type)
Definition at line 94 of file mgc_request.c.
References mgc_name2resid().
Referenced by mgs_ir_notify(), and mgs_revoke_lock().
static int mgc_get_info (const struct lu_env * env, struct obd_export * exp, __u32 keylen, void * key, __u32 * vallen, void * val) [static]
Definition at line 1264 of file mgc_request.c.
References class_exp2cliimp(), obd_import::imp_connect_data, KEY_CONN_DATA, and KEY_IS.
static int mgc_import_event (struct obd_device * obd, struct obd_import * imp, enum obd_import_event event) [static]
Definition at line 1282 of file mgc_request.c.
References CDEBUG, CERROR, D_INFO, D_MGC, obd_import::imp_connect_data, IMP_EVENT_ACTIVATE, IMP_EVENT_ACTIVE, IMP_EVENT_DEACTIVATE, IMP_EVENT_DISCON, IMP_EVENT_INACTIVE, IMP_EVENT_INVALIDATE, IMP_EVENT_OCD, obd_import::imp_obd, LASSERT, LBUG, LDLM_FL_LOCAL_ONLY, ldlm_namespace_cleanup(), mgc_notify_active(), obd_device::obd_name, obd_device::obd_namespace, obd_device::obd_no_recov, OCD_HAS_FLAG, ptlrpc_pinger_ir_down(), ptlrpc_pinger_ir_up(), and RETURN.
static bool mgc_import_in_recovery (struct obd_import * imp) [static]
Definition at line 1837 of file mgc_request.c.
References obd_import::imp_lock, obd_import::imp_state, LUSTRE_IMP_CLOSED, and LUSTRE_IMP_FULL.
Referenced by mgc_process_log().
static int __init mgc_init (void) [static]
Definition at line 2112 of file mgc_request.c.
References class_register_type(), and LUSTRE_MGC_NAME.
static int mgc_llog_fini (const struct lu_env * env, struct obd_device * obd) [static]
Definition at line 827 of file mgc_request.c.
References ENTRY, llog_cleanup(), LLOG_CONFIG_REPL_CTXT, llog_get_context(), and RETURN.
Referenced by mgc_precleanup().
static int mgc_llog_init (const struct lu_env * env, struct obd_device * obd) [static]
Definition at line 804 of file mgc_request.c.
References ENTRY, LASSERT, llog_client_ops, LLOG_CONFIG_REPL_CTXT, llog_ctxt_put(), llog_get_context(), llog_initiator_connect(), llog_setup(), obd_device::obd_olg, and RETURN.
Referenced by mgc_setup().
static int mgc_llog_local_copy (const struct lu_env * env, struct obd_device * obd, struct llog_ctxt * rctxt, struct llog_ctxt * lctxt, char * logname) [static]
Definition at line 1685 of file mgc_request.c.
References CERROR, ENTRY, GOTO, llog_backup(), llog_erase(), OBD_ALLOC, OBD_FREE, obd_device::obd_name, and RETURN.
Referenced by mgc_process_cfg_log().
static int mgc_local_llog_fini (const struct lu_env * env, struct obd_device * obd) [static]
Definition at line 701 of file mgc_request.c.
References ENTRY, llog_cleanup(), LLOG_CONFIG_ORIG_CTXT, llog_get_context(), and RETURN.
Referenced by mgc_fs_cleanup().
static int mgc_local_llog_init (const struct lu_env * env, struct obd_device * obd, struct obd_device * disk) [static]
Definition at line 679 of file mgc_request.c.
References client_obd::cl_mgc_configs_dir, obd_device::cli, ENTRY, LASSERT, LLOG_CONFIG_ORIG_CTXT, llog_ctxt_put(), llog_get_context(), llog_osd_ops, llog_setup(), llog_ctxt::loc_dir, obd_device::obd_olg, RETURN, and obd_device::u.
Referenced by mgc_fs_setup().
static int mgc_logname2resid (char * logname, struct ldlm_res_id * res_id, int type) [static]
Definition at line 102 of file mgc_request.c.
References mgc_name2resid().
Referenced by do_config_log_add().
static int mgc_name2resid (char * name, int len, struct ldlm_res_id * res_id, int type) [static]
Definition at line 57 of file mgc_request.c.
References __u64, CDEBUG, CERROR, CONFIG_T_CONFIG, CONFIG_T_PARAMS, CONFIG_T_RECOVER, CONFIG_T_SPTLRPC, cpu_to_le64, D_MGC, LBUG, LPX64, and ldlm_res_id::name.
Referenced by mgc_fsname2resid(), and mgc_logname2resid().
static void mgc_notify_active (struct obd_device * unused) [static]
Definition at line 1107 of file mgc_request.c.
References RQ_NOW.
Referenced by mgc_import_event().
static int mgc_precleanup (struct obd_device * obd) [static]
Definition at line 842 of file mgc_request.c.
References CERROR, ENTRY, LASSERT, mgc_llog_fini(), obd_cleanup_client_import(), RETURN, RQ_NOW, RQ_PRECLEANUP, RQ_RUNNING, and RQ_STOP.
static int mgc_process_cfg_log (struct obd_device * mgc, struct config_llog_data * cld, int local_only) [static]
Definition at line 1728 of file mgc_request.c.
References __llog_ctxt_put(), CDEBUG, config_llog_instance::cfg_sb, client_obd::cl_mgc_configs_dir, class_config_parse_llog(), class_notify_sptlrpc_conf(), config_llog_data::cld_cfg, cld_is_sptlrpc(), config_llog_data::cld_lock, config_llog_data::cld_logname, obd_device::cli, D_MGC, dt_object::do_lu, ENTRY, EXIT, GOTO, IS_MGS, IS_SERVER, LASSERT, LCONSOLE_ERROR_MSG, LCT_MG_THREAD, LLOG_CONFIG_ORIG_CTXT, LLOG_CONFIG_REPL_CTXT, llog_ctxt_put(), llog_get_context(), llog_is_empty(), lu_object::lo_dev, lu2dt_dev(), lu_env_fini(), lu_env_init(), mgc_llog_local_copy(), OBD_ALLOC_PTR, OBD_FREE_PTR, PARAMS_FILENAME, RETURN, sptlrpc_conf_log_update_begin(), sptlrpc_conf_log_update_end(), and obd_device::u.
Referenced by mgc_process_log().
static int mgc_process_config (struct obd_device * obd, size_t len, void * buf) [static]
Called from lustre_process_log.
LCFG_LOG_START gets the config log from the MGS, processes it to start any services, and adds it to the list logs to watch (follow).
Definition at line 1990 of file mgc_request.c.
References CDEBUG, CERROR, CFG_F_COMPAT146, config_llog_instance::cfg_flags, config_llog_instance::cfg_last_idx, client_obd::cl_import, client_obd::cl_mgc_mgsexp, config_llog_data::cld_cfg, config_llog_data::cld_params, config_llog_data::cld_recover, obd_device::cli, config_log_add(), config_log_end(), config_log_find(), config_log_put(), D_MGC, ENTRY, GOTO, lustre_cfg::lcfg_bufcount, lustre_cfg::lcfg_command, LCFG_LOG_END, LCFG_LOG_START, LCFG_LOV_ADD_OBD, LCFG_LOV_DEL_OBD, LCFG_SPTLRPC_CONF, lustre_cfg_buf(), LUSTRE_CFG_BUFLEN, lustre_cfg_string(), mgc_process_log(), mgc_target_register(), mgs_target_info::mti_flags, mgs_target_info::mti_svname, obd_device::obd_name, OCD_HAS_FLAG, RETURN, sptlrpc_process_config(), and obd_device::u.
int mgc_process_log (struct obd_device * mgc, struct config_llog_data * cld)
Get a configuration log from the MGS and process it.
This function is called for both clients and servers to process the configuration log from the MGS. The MGC enqueues a DLM lock on the log from the MGS, and if the lock gets revoked the MGC will be notified by the lock cancellation callback that the config log has changed, and will enqueue another MGS lock on it, and then continue processing the new additions to the end of the log.
Since the MGC import is not replayable, if the import is being evicted (rcl == -ESHUTDOWN,
See also:
ptlrpc_import_delay_req()), retry to process the log until recovery is finished or the import is closed.
Make a local copy of the log before parsing it if appropriate (non-MGS server) so that the server can start even when the MGS is down.
There shouldn't be multiple processes running process_log at once -- sounds like badness. It actually might be fine, as long as they're not trying to update from the same log simultaneously, in which case we should use a per-log semaphore instead of cld_lock.
Parameters:
[in] mgc MGC device by which to fetch the configuration log
[in] cld log processing state (stored in lock callback data)
Return values:
0 on success
negative errno on failure
Definition at line 1878 of file mgc_request.c.
References __u64, CDEBUG, CERROR, config_llog_instance::cfg_instance, config_llog_instance::cfg_last_idx, cfs_time_seconds(), client_obd::cl_mgc_mgsexp, client_obd::cl_mgc_refcount, class_exp2cliimp(), config_llog_data::cld_cfg, cld_is_recover(), config_llog_data::cld_lock, config_llog_data::cld_logname, config_llog_data::cld_lostlock, config_llog_data::cld_stopping, obd_device::cli, config_log_get(), D_MGC, ENTRY, obd_import::imp_recovery_waitq, obd_import::imp_state, l_wait_event, LASSERT, LCK_CR, LDLM_FL_NO_LRU, ldlm_lock_set_data(), LDLM_PLAIN, LUSTRE_IMP_FULL, LWI_TIMEOUT, mgc_cancel(), mgc_enqueue(), mgc_import_in_recovery(), mgc_process_cfg_log(), mgc_process_recover_log(), OBD_FAIL_MGC_PAUSE_PROCESS_LOG, OBD_FAIL_TIMEOUT, obd_device::obd_name, obd_timeout, ptlrpc_pinger_force(), RETURN, and obd_device::u.
Referenced by do_config_log_add(), do_requeue(), and mgc_process_config().
static int mgc_process_recover_log (struct obd_device * obd, struct config_llog_data * cld) [static]
This function is called if this client was notified for target restarting by the MGS.
A CONFIG_READ RPC is going to send to fetch recovery logs.
Definition at line 1537 of file mgc_request.c.
References ptlrpc_bulk_frag_ops::add_kiov_frag, ptlrpc_bulk_desc::bd_frag_ops, CDEBUG, config_llog_instance::cfg_last_idx, class_exp2cliimp(), config_llog_data::cld_cfg, cld_is_recover(), config_llog_data::cld_lock, config_llog_data::cld_logname, config_llog_data::cld_mgcexp, config_llog_data::cld_type, CONFIG_READ_NRPAGES, CONFIG_READ_NRPAGES_INIT, CWARN, D_INFO, ENTRY, GOTO, LASSERT, LPD64, LUSTRE_MGS_VERSION, mgs_config_body::mcb_bits, mgs_config_body::mcb_name, mgs_config_body::mcb_offset, mgs_config_body::mcb_type, mgs_config_body::mcb_units, mgs_config_res::mcr_offset, mgs_config_res::mcr_size, mgc_apply_recover_logs(), MGS_BULK_PORTAL, MGS_CONFIG_READ, min_t, OBD_ALLOC, OBD_FREE, PTLRPC_BULK_BUF_KIOV, ptlrpc_bulk_kiov_pin_ops, PTLRPC_BULK_PUT_SINK, ptlrpc_prep_bulk_imp(), ptlrpc_queue_wait(), ptlrpc_rep_need_swab(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), req_capsule_client_get(), req_capsule_server_get(), RMF_MGS_CONFIG_BODY, RMF_MGS_CONFIG_RES, ptlrpc_request::rq_import, ptlrpc_request::rq_pill, RQF_MGS_CONFIG_READ, sptlrpc_cli_unwrap_bulk_read(), strlcpy(), and unlikely.
Referenced by mgc_process_log().
static void mgc_requeue_add (struct config_llog_data * cld) [static]
Definition at line 645 of file mgc_request.c.
References CDEBUG, config_llog_data::cld_lock, config_llog_data::cld_logname, config_llog_data::cld_lostlock, config_llog_data::cld_refcount, config_llog_data::cld_stopping, config_log_get(), config_log_put(), D_INFO, ENTRY, EXIT, LASSERT, RETURN_EXIT, RQ_NOW, and RQ_STOP.
Referenced by mgc_blocking_ast().
static int mgc_requeue_thread (void * data) [static]
Definition at line 546 of file mgc_request.c.
References CDEBUG, cfs_rand(), config_llog_data::cld_list_chain, config_llog_data::cld_lostlock, config_llog_data::cld_refcount, config_log_put(), D_MGC, do_requeue(), ENTRY, l_wait_event, LASSERT, likely, list_for_each_entry, LWI_TIMEOUT, MGC_TIMEOUT_MIN_SECONDS, MGC_TIMEOUT_RAND_CENTISEC, RETURN, RQ_LATER, RQ_NOW, RQ_PRECLEANUP, RQ_RUNNING, RQ_STOP, and unlikely.
Referenced by mgc_setup().
static int mgc_set_info_async (const struct lu_env * env, struct obd_export * exp, u32 keylen, void * key, u32 vallen, void * val, struct ptlrpc_request_set * set) [static]
Definition at line 1158 of file mgc_request.c.
References CDEBUG, CERROR, client_obd::cl_flvr_mgc, class_exp2cliimp(), obd_device::cli, D_MGC, ENTRY, obd_export::exp_obd, obd_import::imp_deactive, obd_import::imp_invalid, obd_import::imp_obd, obd_import::imp_replayable, obd_import::imp_state, KEY_CLEAR_FS, KEY_INIT_RECOV_BACKUP, KEY_IS, KEY_MGSSEC, KEY_REGISTER_TARGET, KEY_SET_FS, KEY_SET_INFO, LCONSOLE_ERROR, LUSTRE_IMP_FULL, LUSTRE_IMP_NEW, mgc_fs_cleanup(), mgc_fs_setup(), mgc_set_mgs_param(), mgc_target_register(), mgs_target_info::mti_flags, mgs_target_info::mti_svname, obd_device::obd_name, obd_device::obd_replayable, ptlrpc_import_state_name(), ptlrpc_reconnect_import(), RETURN, sptlrpc_flavor::sf_rpc, sptlrpc_flavor2name(), SPTLRPC_FLVR_INVALID, sptlrpc_parse_flavor(), and obd_device::u.
static int mgc_set_mgs_param (struct obd_export * exp, struct mgs_send_param * msp) [static]
Definition at line 1012 of file mgc_request.c.
References class_exp2cliimp(), ENTRY, LUSTRE_MGS_VERSION, MGC_SEND_PARAM_LIMIT, MGS_SET_INFO, ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc_pack(), ptlrpc_request_set_replen(), req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_MGS_SEND_PARAM, ptlrpc_request::rq_pill, and RQF_MGS_SET_INFO.
Referenced by mgc_set_info_async().
static int mgc_setup (struct obd_device * obd, struct lustre_cfg * lcfg) [static]
Definition at line 891 of file mgc_request.c.
References CERROR, client_obd_cleanup(), client_obd_setup(), ENTRY, GOTO, lprocfs_obd_setup(), mgc_llog_init(), mgc_requeue_thread(), obd_device::obd_name, obd_device::obd_vars, ptlrpcd_addref(), ptlrpcd_decref(), RETURN, and sptlrpc_lprocfs_cliobd_attach().
static int mgc_target_register (struct obd_export * exp, struct mgs_target_info * mti) [static]
Definition at line 1119 of file mgc_request.c.
References CDEBUG, class_exp2cliimp(), D_MGC, ENTRY, LUSTRE_MGS_VERSION, MGC_TARGET_REG_LIMIT, MGS_TARGET_REG, mgs_target_info::mti_stripe_index, mgs_target_info::mti_svname, ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc_pack(), ptlrpc_request_set_replen(), req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_MGS_TARGET_INFO, ptlrpc_request::rq_pill, and RQF_MGS_TARGET_REG.
Referenced by mgc_process_config(), and mgc_set_info_async().
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Management Client")
module_exit (mgc_exit)
module_init (mgc_init)
MODULE_LICENSE ("GPL")
MODULE_VERSION (LUSTRE_VERSION_STRING)
Variable Documentation
struct list_head config_llog_list = LIST_HEAD_INIT(config_llog_list) [static]
Definition at line 120 of file mgc_request.c.
atomic_t mgc_count = ATOMIC_INIT(0) [static]
Definition at line 841 of file mgc_request.c.
struct obd_ops mgc_obd_ops [static]
Initial value:
 {
        .o_owner        = THIS_MODULE,
        .o_setup        = mgc_setup,
        .o_precleanup   = mgc_precleanup,
        .o_cleanup      = mgc_cleanup,
        .o_add_conn     = client_import_add_conn,
        .o_del_conn     = client_import_del_conn,
        .o_connect      = client_connect_import,
        .o_disconnect   = client_disconnect_export,
        .o_set_info_async = mgc_set_info_async,
        .o_get_info       = mgc_get_info,
        .o_import_event = mgc_import_event,
        .o_process_config = mgc_process_config,
}
Definition at line 2097 of file mgc_request.c.
int rq_state = 0 [static]
Definition at line 509 of file mgc_request.c.
wait_queue_head_t rq_waitq [static]
Definition at line 510 of file mgc_request.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.