Lustre: lustre/mgc/mgc_internal.h File Reference
lustre/mgc/mgc_internal.h File Reference
#include <libcfs/libcfs.h>
#include <lustre/lustre_idl.h>
#include <lustre_lib.h>
#include <lustre_dlm.h>
#include <lustre_log.h>
#include <lustre_export.h>
Functions
int mgc_process_log (struct obd_device *mgc, struct config_llog_data *cld)
Get a configuration log from the MGS and process it.
static int cld_is_sptlrpc (struct config_llog_data *cld)
static int cld_is_recover (struct config_llog_data *cld)
Function Documentation
static int cld_is_recover (struct config_llog_data * cld) [inline, static]
Definition at line 59 of file mgc_internal.h.
References config_llog_data::cld_type, and CONFIG_T_RECOVER.
Referenced by mgc_process_log(), and mgc_process_recover_log().
static int cld_is_sptlrpc (struct config_llog_data * cld) [inline, static]
Definition at line 54 of file mgc_internal.h.
References config_llog_data::cld_type, and CONFIG_T_SPTLRPC.
Referenced by config_log_find(), config_log_put(), do_config_log_add(), mgc_enqueue(), and mgc_process_cfg_log().
int mgc_process_log (struct obd_device * mgc, struct config_llog_data * cld)
Get a configuration log from the MGS and process it.
This function is called for both clients and servers to process the configuration log from the MGS. The MGC enqueues a DLM lock on the log from the MGS, and if the lock gets revoked the MGC will be notified by the lock cancellation callback that the config log has changed, and will enqueue another MGS lock on it, and then continue processing the new additions to the end of the log.
Since the MGC import is not replayable, if the import is being evicted (rcl == -ESHUTDOWN,
See also:
ptlrpc_import_delay_req()), retry to process the log until recovery is finished or the import is closed.
Make a local copy of the log before parsing it if appropriate (non-MGS server) so that the server can start even when the MGS is down.
There shouldn't be multiple processes running process_log at once -- sounds like badness. It actually might be fine, as long as they're not trying to update from the same log simultaneously, in which case we should use a per-log semaphore instead of cld_lock.
Parameters:
[in] mgc MGC device by which to fetch the configuration log
[in] cld log processing state (stored in lock callback data)
Return values:
0 on success
negative errno on failure
Definition at line 1878 of file mgc_request.c.
References __u64, CDEBUG, CERROR, config_llog_instance::cfg_instance, config_llog_instance::cfg_last_idx, cfs_time_seconds(), client_obd::cl_mgc_mgsexp, client_obd::cl_mgc_refcount, class_exp2cliimp(), config_llog_data::cld_cfg, cld_is_recover(), config_llog_data::cld_lock, config_llog_data::cld_logname, config_llog_data::cld_lostlock, config_llog_data::cld_stopping, obd_device::cli, config_log_get(), D_MGC, ENTRY, obd_import::imp_recovery_waitq, obd_import::imp_state, l_wait_event, LASSERT, LCK_CR, LDLM_FL_NO_LRU, ldlm_lock_set_data(), LDLM_PLAIN, LUSTRE_IMP_FULL, LWI_TIMEOUT, mgc_cancel(), mgc_enqueue(), mgc_import_in_recovery(), mgc_process_cfg_log(), mgc_process_recover_log(), OBD_FAIL_MGC_PAUSE_PROCESS_LOG, OBD_FAIL_TIMEOUT, obd_device::obd_name, obd_timeout, ptlrpc_pinger_force(), RETURN, and obd_device::u.
Referenced by do_config_log_add(), do_requeue(), and mgc_process_config().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.