Lustre: lustre/mgs/mgs_fs.c File Reference
lustre/mgs/mgs_fs.c File Reference
#include <lustre_fid.h>
#include "mgs_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_MGS
Functions
int mgs_export_stats_init (struct obd_device *obd, struct obd_export *exp, void *localdata)
Initialize MGS per-export statistics.
int mgs_client_add (struct obd_device *obd, struct obd_export *exp, void *localdata)
Add client export data to the MGS.
int mgs_client_free (struct obd_export *exp)
int mgs_fs_setup (const struct lu_env *env, struct mgs_device *mgs)
int mgs_fs_cleanup (const struct lu_env *env, struct mgs_device *mgs)
Define Documentation
#define DEBUG_SUBSYSTEM S_MGS
Definition at line 44 of file mgs_fs.c.
Function Documentation
int mgs_client_add (struct obd_device * obd, struct obd_export * exp, void * localdata)
Add client export data to the MGS.
This data is currently NOT stored on disk in the last_rcvd file or anywhere else. In the event of a MGS crash all connections are treated as new connections.
Definition at line 104 of file mgs_fs.c.
int mgs_client_free (struct obd_export * exp)
Definition at line 111 of file mgs_fs.c.
Referenced by mgs_destroy_export().
int mgs_export_stats_init (struct obd_device * obd, struct obd_export * exp, void * localdata)
Initialize MGS per-export statistics.
This function sets up procfs entries for various MGS export counters. These counters are for per-client statistics tracked on the server.
Parameters:
[in] obd OBD device
[in] exp OBD export
[in] localdata NID of client
Return values:
0 if successful
negative value on error
Definition at line 62 of file mgs_fs.c.
References ENTRY, obd_export::exp_nid_stats, GOTO, LPROC_MGS_LAST, lprocfs_alloc_stats(), lprocfs_free_stats(), lprocfs_init_ops_stats(), lprocfs_nid_ldlm_stats_init(), lprocfs_register_stats(), LPROCFS_STATS_FLAG_NOPERCPU, mgs_stats_counter_init(), nid_stat::nid_proc, nid_stat::nid_stats, and RETURN.
Referenced by mgs_obd_connect(), and mgs_obd_reconnect().
int mgs_fs_cleanup (const struct lu_env * env, struct mgs_device * mgs)
Definition at line 225 of file mgs_fs.c.
References dt_object::do_lu, local_oid_storage_fini(), lu_object_put(), mgs_device::mgs_configs_dir, mgs_device::mgs_los, mgs_device::mgs_nidtbl_dir, mgs_device::mgs_obd, nm_config_file_deregister(), and obd_device::u.
Referenced by mgs_device_fini(), and mgs_init0().
int mgs_fs_setup (const struct lu_env * env, struct mgs_device * mgs)
Definition at line 116 of file mgs_fs.c.
References CERROR, dt_device::dd_lu_dev, dt_object::do_index_ops, dt_object_operations::do_index_try, dt_object::do_lu, dt_object::do_ops, lvfs_run_ctxt::dt, dt_locate_at(), dt_nodemap_features, dt_root_get(), dt_try_as_dir(), ENTRY, lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, FID_SEQ_LOCAL_NAME, GOTO, LASSERT, lu_device::ld_site, local_file_find_or_create(), local_index_find_or_create(), local_oid_storage_fini(), local_oid_storage_init(), lu_site::ls_top_dev, lu_object_put(), LUSTRE_NODEMAP_NAME, mgs_device::mgs_bottom, mgs_device::mgs_configs_dir, mgs_device::mgs_dt_dev, mgs_device::mgs_los, mgs_device::mgs_nidtbl_dir, MGS_NIDTBL_DIR, mgs_device::mgs_obd, MOUNT_CONFIGS_DIR, nm_config_file_deregister(), nm_config_file_register(), obd_device::obd_lvfs_ctxt, obd_device::obd_name, OBD_SET_CTXT_MAGIC(), obd_device::u, and unlikely.
Referenced by mgs_init0().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.