Lustre: lustre/mgs/mgs_llog.c File Reference
lustre/mgs/mgs_llog.c File Reference
#include <obd.h>
#include <lustre_ioctl.h>
#include <lustre_param.h>
#include <lustre_sec.h>
#include <lustre_quota.h>
#include "mgs_internal.h"
Data Structures
struct mgs_fsdb_handler_data
struct mgs_modify_lookup
struct mgs_replace_uuid_lookup
This structure is passed to mgs_replace_handler.
struct mgs_srpc_read_data
Defines
#define DEBUG_SUBSYSTEM S_MGS
#define D_MGS D_CONFIG
Functions
int class_dentry_readdir (const struct lu_env *env, struct mgs_device *mgs, struct list_head *log_list)
static int name_create (char **newname, char *prefix, char *suffix)
static void name_destroy (char **name)
static int mgs_fsdb_handler (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *rec, void *data)
static int mgs_get_fsdb_from_llog (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb)
static void mgs_free_fsdb_srpc (struct fs_db *fsdb)
struct fs_db * mgs_find_fsdb (struct mgs_device *mgs, char *fsname)
static struct fs_db * mgs_new_fsdb (const struct lu_env *env, struct mgs_device *mgs, char *fsname)
static void mgs_free_fsdb (struct mgs_device *mgs, struct fs_db *fsdb)
int mgs_init_fsdb_list (struct mgs_device *mgs)
int mgs_cleanup_fsdb_list (struct mgs_device *mgs)
int mgs_find_or_make_fsdb (const struct lu_env *env, struct mgs_device *mgs, char *name, struct fs_db **dbh)
int mgs_check_index (const struct lu_env *env, struct mgs_device *mgs, struct mgs_target_info *mti)
static __inline__ int next_index (void *index_map, int map_len)
static int mgs_set_index (const struct lu_env *env, struct mgs_device *mgs, struct mgs_target_info *mti)
static int mgs_modify_handler (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *rec, void *data)
static int mgs_modify (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb, struct mgs_target_info *mti, char *logname, char *devname, char *comment, int flags)
Modify an existing config log record (for CM_SKIP or CM_EXCLUDE) Return code: 0 - modified successfully, 1 - no modification was done negative - error.
static int check_markers (struct lustre_cfg *lcfg, struct mgs_replace_uuid_lookup *mrul)
Check: a) if block should be skipped b) is it target block.
static int record_base (const struct lu_env *env, struct llog_handle *llh, char *cfgname, lnet_nid_t nid, int cmd, char *s1, char *s2, char *s3, char *s4)
static int record_add_uuid (const struct lu_env *env, struct llog_handle *llh, uint64_t nid, char *uuid)
static int record_add_conn (const struct lu_env *env, struct llog_handle *llh, char *devname, char *uuid)
static int record_attach (const struct lu_env *env, struct llog_handle *llh, char *devname, char *type, char *uuid)
static int record_setup (const struct lu_env *env, struct llog_handle *llh, char *devname, char *s1, char *s2, char *s3, char *s4)
static int process_command (const struct lu_env *env, struct lustre_cfg *lcfg, struct mgs_replace_uuid_lookup *mrul)
static int mgs_replace_handler (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *rec, void *data)
Handler that called for every record in llog.
static int mgs_log_is_empty (const struct lu_env *env, struct mgs_device *mgs, char *name)
static int mgs_replace_nids_log (const struct lu_env *env, struct obd_device *mgs, struct fs_db *fsdb, char *logname, char *devname, char *nids)
static int mgs_parse_devname (char *devname, char *fsname, __u32 *index)
Parse device name and get file system name and/or device index.
static int only_mgs_is_running (struct obd_device *mgs_obd)
static int name_create_mdt (char **logname, char *fsname, int i)
int mgs_replace_nids (const struct lu_env *env, struct mgs_device *mgs, char *devname, char *nids)
Replace nids for device to nids values.
static int record_lov_setup (const struct lu_env *env, struct llog_handle *llh, char *devname, struct lov_desc *desc)
static int record_lmv_setup (const struct lu_env *env, struct llog_handle *llh, char *devname, struct lmv_desc *desc)
static int record_mdc_add (const struct lu_env *env, struct llog_handle *llh, char *logname, char *mdcuuid, char *mdtuuid, char *index, char *gen)
static int record_lov_add (const struct lu_env *env, struct llog_handle *llh, char *lov_name, char *ost_uuid, char *index, char *gen)
static int record_mount_opt (const struct lu_env *env, struct llog_handle *llh, char *profile, char *lov_name, char *mdc_name)
static int record_marker (const struct lu_env *env, struct llog_handle *llh, struct fs_db *fsdb, __u32 flags, char *tgtname, char *comment)
static int record_start_log (const struct lu_env *env, struct mgs_device *mgs, struct llog_handle **llh, char *name)
static int record_end_log (const struct lu_env *env, struct llog_handle **llh)
static int mgs_write_log_direct (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb, char *logname, struct llog_cfg_rec *lcr, char *devname, char *comment)
static int mgs_write_log_direct_all (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb, struct mgs_target_info *mti, struct llog_cfg_rec *lcr, char *devname, char *comment, int server_only)
static int mgs_write_log_osp_to_mdt (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb, struct mgs_target_info *mti, int index, char *logname)
static int mgs_write_log_osc_to_lov (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb, struct mgs_target_info *mti, char *logname, char *suffix, char *lovname, enum lustre_sec_part sec_part, int flags)
static int name_create_mdt_and_lov (char **logname, char **lovname, struct fs_db *fsdb, int i)
static int add_param (char *params, char *key, char *val)
static int mgs_steal_client_llog_handler (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *rec, void *data)
Walk through client config log record and convert the related records into the target.
static int mgs_steal_llog_for_mdt_from_client (const struct lu_env *env, struct mgs_device *mgs, char *client_name, struct temp_comp *comp)
static int mgs_write_log_lmv (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb, struct mgs_target_info *mti, char *logname, char *lmvname)
static int mgs_write_log_lov (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb, struct mgs_target_info *mti, char *logname, char *lovname)
static int mgs_write_log_failnids (const struct lu_env *env, struct mgs_target_info *mti, struct llog_handle *llh, char *cliname)
static int mgs_write_log_mdc_to_lmv (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb, struct mgs_target_info *mti, char *logname, char *lmvname)
static int name_create_lov (char **lovname, char *mdtname, struct fs_db *fsdb, int index)
static int name_create_mdt_osc (char **oscname, char *ostname, struct fs_db *fsdb, int i)
static int mgs_write_log_mdt0 (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb, struct mgs_target_info *mti)
static int mgs_write_log_mdt (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb, struct mgs_target_info *mti)
static int mgs_write_log_ost (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb, struct mgs_target_info *mti)
static __inline__ int mgs_param_empty (char *ptr)
static int mgs_write_log_failnid_internal (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb, struct mgs_target_info *mti, char *logname, char *cliname)
static int mgs_write_log_add_failnid (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb, struct mgs_target_info *mti)
static int mgs_wlp_lcfg (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb, struct mgs_target_info *mti, char *logname, struct lustre_cfg_bufs *bufs, char *tgtname, char *ptr)
static int mgs_write_log_param2 (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb, struct mgs_target_info *mti, char *ptr)
static int mgs_write_log_sys (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb, struct mgs_target_info *mti, char *sys, char *ptr)
static int mgs_write_log_quota (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb, struct mgs_target_info *mti, char *quota, char *ptr)
static int mgs_srpc_set_param_disk (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb, struct mgs_target_info *mti, char *param)
static int mgs_srpc_set_param_udesc_mem (struct fs_db *fsdb, char *param)
static int mgs_srpc_set_param_mem (struct fs_db *fsdb, const char *svname, char *param)
static int mgs_srpc_set_param (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb, struct mgs_target_info *mti, char *param)
static int mgs_srpc_read_handler (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *rec, void *data)
int mgs_get_fsdb_srpc_from_llog (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb)
static int mgs_write_log_param (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb, struct mgs_target_info *mti, char *ptr)
int mgs_check_failnid (const struct lu_env *env, struct mgs_device *mgs, struct mgs_target_info *mti)
int mgs_write_log_target (const struct lu_env *env, struct mgs_device *mgs, struct mgs_target_info *mti, struct fs_db *fsdb)
int mgs_erase_log (const struct lu_env *env, struct mgs_device *mgs, char *name)
int mgs_erase_logs (const struct lu_env *env, struct mgs_device *mgs, char *fsname)
int mgs_list_logs (const struct lu_env *env, struct mgs_device *mgs, struct obd_ioctl_data *data)
static void print_lustre_cfg (struct lustre_cfg *lcfg)
int mgs__mgs_fsdb_setup (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb)
int mgs_params_fsdb_setup (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb)
int mgs_params_fsdb_cleanup (const struct lu_env *env, struct mgs_device *mgs)
int mgs_setparam (const struct lu_env *env, struct mgs_device *mgs, struct lustre_cfg *lcfg, char *fsname)
static int mgs_write_log_pool (const struct lu_env *env, struct mgs_device *mgs, char *logname, struct fs_db *fsdb, char *tgtname, enum lcfg_command_type cmd, char *fsname, char *poolname, char *ostname, char *comment)
int mgs_nodemap_cmd (const struct lu_env *env, struct mgs_device *mgs, enum lcfg_command_type cmd, const char *nodemap_name, char *param)
int mgs_pool_cmd (const struct lu_env *env, struct mgs_device *mgs, enum lcfg_command_type cmd, char *fsname, char *poolname, char *ostname)
Define Documentation
#define D_MGS D_CONFIG
Definition at line 46 of file mgs_llog.c.
#define DEBUG_SUBSYSTEM S_MGS
Definition at line 45 of file mgs_llog.c.
Function Documentation
static int add_param (char * params, char * key, char * val) [static]
Definition at line 1519 of file mgs_llog.c.
References CERROR, end, and start.
Referenced by append_param(), mgs_steal_client_llog_handler(), parse_opts(), and zfs_get_prop_params().
static int check_markers (struct lustre_cfg * lcfg, struct mgs_replace_uuid_lookup * mrul) [static]
Check: a) if block should be skipped b) is it target block.
Parameters:
[in] lcfg
[in] mrul
Return values:
0 should not to be skipped
1 should to be skipped
Definition at line 750 of file mgs_llog.c.
References CM_END, CM_EXCLUDE, cfg_marker::cm_flags, CM_START, cfg_marker::cm_tgtname, mgs_replace_uuid_lookup::device_nids_added, mgs_replace_uuid_lookup::in_target_device, LASSERT, lustre_cfg::lcfg_command, LCFG_MARKER, lustre_cfg_buf(), mgs_target_info::mti_svname, mgs_replace_uuid_lookup::skip_it, and mgs_replace_uuid_lookup::target.
Referenced by mgs_replace_handler().
int class_dentry_readdir (const struct lu_env * env, struct mgs_device * mgs, struct list_head * log_list)
Definition at line 59 of file mgs_llog.c.
References CERROR, dt_index_operations::dio_it, dir, dt_object::do_index_ops, GOTO, dt_index_operations::dt_it_ops::init, INIT_LIST_HEAD, LASSERT, list_add(), LUDA_64BITHASH, mgs_direntry::mde_list, mgs_direntry::mde_name, mgs_device::mgs_configs_dir, mgs_direntry_alloc(), mgs_device::mgs_obd, MOUNT_CONFIGS_DIR, obd_device::obd_name, and RETURN.
Referenced by mgs_erase_logs(), mgs_list_logs(), and mgs_write_log_direct_all().
int mgs__mgs_fsdb_setup (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb)
Definition at line 3927 of file mgs_llog.c.
References ENTRY, mgs_find_or_make_fsdb(), MGSSELF_NAME, and RETURN.
Referenced by mgs_init0().
int mgs_check_failnid (const struct lu_env * env, struct mgs_device * mgs, struct mgs_target_info * mti)
Definition at line 3690 of file mgs_llog.c.
References buf, CDEBUG, D_MGS, ENTRY, fs_db::fsdb_mutex, mgs_find_or_make_fsdb(), mgs_log_is_empty(), mgs_write_log_add_failnid(), mgs_target_info::mti_svname, and RETURN.
Referenced by mgs_check_target().
int mgs_check_index (const struct lu_env * env, struct mgs_device * mgs, struct mgs_target_info * mti)
Definition at line 483 of file mgs_llog.c.
References CERROR, ENTRY, fs_db::fsdb_flags, FSDB_LOG_EMPTY, fs_db::fsdb_mdt_index_map, fs_db::fsdb_ost_index_map, LASSERT, LDD_F_NEED_INDEX, LDD_F_SV_TYPE_MDT, LDD_F_SV_TYPE_OST, mgs_find_or_make_fsdb(), mgs_target_info::mti_flags, mgs_target_info::mti_fsname, mgs_target_info::mti_stripe_index, and RETURN.
Referenced by mgs_check_target().
int mgs_cleanup_fsdb_list (struct mgs_device * mgs)
Definition at line 414 of file mgs_llog.c.
References list_entry, list_for_each_safe, mgs_free_fsdb(), mgs_device::mgs_fs_db_list, and mgs_device::mgs_mutex.
Referenced by mgs_device_fini().
int mgs_erase_log (const struct lu_env * env, struct mgs_device * mgs, char * name)
Definition at line 3801 of file mgs_llog.c.
References CERROR, LLOG_CONFIG_ORIG_CTXT, llog_ctxt_put(), llog_erase(), llog_get_context(), mgs_device::mgs_obd, and obd_device::obd_name.
Referenced by mgs_erase_logs(), and mgs_target_reg().
int mgs_erase_logs (const struct lu_env * env, struct mgs_device * mgs, char * fsname)
Definition at line 3827 of file mgs_llog.c.
References CDEBUG, class_dentry_readdir(), D_MGS, ENTRY, list_del_init(), list_for_each_entry_safe, mgs_direntry::mde_list, mgs_direntry::mde_name, mgs_direntry_free(), mgs_erase_log(), mgs_find_fsdb(), mgs_free_fsdb(), mgs_device::mgs_mutex, and RETURN.
Referenced by mgs_params_fsdb_cleanup(), and mgs_target_reg().
struct fs_db* mgs_find_fsdb (struct mgs_device * mgs, char * fsname) [read]
Definition at line 314 of file mgs_llog.c.
References fs_db::fsdb_name, list_entry, list_for_each, and mgs_device::mgs_fs_db_list.
Referenced by mgs_erase_logs(), and mgs_find_or_make_fsdb().
int mgs_find_or_make_fsdb (const struct lu_env * env, struct mgs_device * mgs, char * name, struct fs_db ** dbh)
Definition at line 428 of file mgs_llog.c.
References CDEBUG, CERROR, D_MGS, ENTRY, fs_db::fsdb_flags, FSDB_MGS_SELF, fs_db::fsdb_mutex, GOTO, mgs_find_fsdb(), mgs_free_fsdb(), mgs_get_fsdb_from_llog(), mgs_get_fsdb_srpc_from_llog(), mgs_device::mgs_mutex, mgs_new_fsdb(), and RETURN.
Referenced by mgs__mgs_fsdb_setup(), mgs_check_failnid(), mgs_check_index(), mgs_fsc_attach(), mgs_get_ir_logs(), mgs_ir_update(), mgs_params_fsdb_setup(), mgs_pool_cmd(), mgs_replace_nids(), mgs_set_index(), mgs_setparam(), and mgs_target_reg().
static void mgs_free_fsdb (struct mgs_device * mgs, struct fs_db * fsdb) [static]
Definition at line 387 of file mgs_llog.c.
References fs_db::fsdb_clilmv, fs_db::fsdb_clilov, fs_db::fsdb_list, fs_db::fsdb_mdt_index_map, fs_db::fsdb_mutex, fs_db::fsdb_ost_index_map, INDEX_MAP_SIZE, list_del(), lproc_mgs_del_live(), mgs_free_fsdb_srpc(), mgs_ir_fini_fs(), name_destroy(), OBD_FREE, and OBD_FREE_PTR.
Referenced by mgs_cleanup_fsdb_list(), mgs_erase_logs(), mgs_find_or_make_fsdb(), mgs_pool_cmd(), and mgs_setparam().
static void mgs_free_fsdb_srpc (struct fs_db * fsdb) [static]
Definition at line 294 of file mgs_llog.c.
References fs_db::fsdb_srpc_gen, fs_db::fsdb_srpc_tgt, LASSERT, mgs_tgt_srpc_conf::mtsc_next, mgs_tgt_srpc_conf::mtsc_rset, mgs_tgt_srpc_conf::mtsc_tgt, OBD_FREE, OBD_FREE_PTR, and sptlrpc_rule_set_free().
Referenced by mgs_free_fsdb().
static int mgs_fsdb_handler (const struct lu_env * env, struct llog_handle * llh, struct llog_rec_hdr * rec, void * data) [static]
figure out the old config. fsdb_gen = 0 means old log It is obsoleted and not supported anymore
Definition at line 161 of file mgs_llog.c.
References CDEBUG, CERROR, cfg_marker::cm_step, cfg_marker::cm_vers, CWARN, D_INFO, D_MGS, ENTRY, mgs_fsdb_handler_data::fsdb, fs_db::fsdb_flags, fs_db::fsdb_gen, fs_db::fsdb_mdt_count, fs_db::fsdb_mdt_index_map, FSDB_OSCNAME18, fs_db::fsdb_ost_index_map, LCFG_ATTACH, lustre_cfg::lcfg_command, LCFG_LOV_ADD_OBD, LCFG_LOV_DEL_OBD, LCFG_MARKER, LDD_F_SV_TYPE_MDT, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, lustre_cfg_buf(), lustre_cfg_sanity_check(), lustre_cfg_string(), LUSTRE_MDC_NAME, LUSTRE_OSC_NAME, max, OBD_CFG_REC, OBD_OCD_VERSION_MAJOR, OBD_OCD_VERSION_MINOR, RETURN, server_name2index(), and mgs_fsdb_handler_data::ver.
Referenced by mgs_get_fsdb_from_llog().
static int mgs_get_fsdb_from_llog (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb) [static]
Definition at line 254 of file mgs_llog.c.
References CDEBUG, D_INFO, ENTRY, fs_db::fsdb_flags, FSDB_LOG_EMPTY, fs_db::fsdb_name, GOTO, LASSERT, llog_close(), LLOG_CONFIG_ORIG_CTXT, llog_ctxt_put(), LLOG_F_IS_PLAIN, llog_get_context(), llog_get_size(), llog_init_handle(), llog_open_create(), llog_process(), mgs_fsdb_handler(), mgs_device::mgs_obd, name_create(), name_destroy(), and RETURN.
Referenced by mgs_find_or_make_fsdb().
int mgs_get_fsdb_srpc_from_llog (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb)
Definition at line 3199 of file mgs_llog.c.
References CERROR, ENTRY, fs_db::fsdb_name, GOTO, LASSERT, llog_close(), LLOG_CONFIG_ORIG_CTXT, llog_ctxt_put(), LLOG_F_IS_PLAIN, llog_get_context(), llog_get_size(), llog_init_handle(), llog_open(), LLOG_OPEN_EXISTS, llog_process(), mgs_log_is_empty(), mgs_device::mgs_obd, mgs_srpc_read_handler(), mgs_srpc_read_data::msrd_fsdb, mgs_srpc_read_data::msrd_skip, name_create(), name_destroy(), and RETURN.
Referenced by mgs_find_or_make_fsdb().
int mgs_init_fsdb_list (struct mgs_device * mgs)
Definition at line 408 of file mgs_llog.c.
References INIT_LIST_HEAD, and mgs_device::mgs_fs_db_list.
Referenced by mgs_init0().
int mgs_list_logs (const struct lu_env * env, struct mgs_device * mgs, struct obd_ioctl_data * data)
Definition at line 3868 of file mgs_llog.c.
References class_dentry_readdir(), ENTRY, obd_ioctl_data::ioc_bulk, obd_ioctl_data::ioc_inllen1, list_del_init(), list_for_each_entry_safe, mgs_direntry::mde_list, mgs_direntry::mde_name, mgs_direntry_free(), and RETURN.
Referenced by mgs_iocontrol().
static int mgs_log_is_empty (const struct lu_env * env, struct mgs_device * mgs, char * name) [static]
Definition at line 994 of file mgs_llog.c.
References LASSERT, LLOG_CONFIG_ORIG_CTXT, llog_ctxt_put(), llog_get_context(), llog_is_empty(), and mgs_device::mgs_obd.
Referenced by mgs_check_failnid(), mgs_get_fsdb_srpc_from_llog(), mgs_replace_nids_log(), mgs_srpc_set_param_disk(), mgs_write_log_add_failnid(), mgs_write_log_mdc_to_lmv(), mgs_write_log_mdt(), mgs_write_log_mdt0(), mgs_write_log_osc_to_lov(), mgs_write_log_osp_to_mdt(), mgs_write_log_ost(), and mgs_write_log_param().
static int mgs_modify (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb, struct mgs_target_info * mti, char * logname, char * devname, char * comment, int flags) [static]
Modify an existing config log record (for CM_SKIP or CM_EXCLUDE) Return code: 0 - modified successfully, 1 - no modification was done negative - error.
Definition at line 662 of file mgs_llog.c.
References CDEBUG, CERROR, cfs_time_current_sec(), cfg_marker::cm_canceltime, cfg_marker::cm_comment, cfg_marker::cm_flags, cfg_marker::cm_tgtname, D_MGS, ENTRY, fs_db::fsdb_mutex, GOTO, LASSERT, llog_close(), LLOG_CONFIG_ORIG_CTXT, llog_ctxt_put(), LLOG_F_IS_PLAIN, llog_get_context(), llog_get_size(), llog_init_handle(), llog_open(), LLOG_OPEN_EXISTS, llog_process(), mgs_modify_handler(), mgs_device::mgs_obd, mgs_modify_lookup::mml_marker, mgs_modify_lookup::mml_modified, mgs_target_info::mti_svname, OBD_ALLOC_PTR, OBD_FREE_PTR, obd_device::obd_name, RETURN, and strlcpy().
Referenced by mgs_pool_cmd(), mgs_srpc_set_param_disk(), mgs_wlp_lcfg(), mgs_write_log_direct_all(), mgs_write_log_failnid_internal(), and mgs_write_log_param().
static int mgs_modify_handler (const struct lu_env * env, struct llog_handle * llh, struct llog_rec_hdr * rec, void * data) [static]
Definition at line 608 of file mgs_llog.c.
References CDEBUG, CERROR, cfg_marker::cm_canceltime, cfg_marker::cm_comment, CM_EXCLUDE, cfg_marker::cm_flags, CM_SKIP, cfg_marker::cm_step, cfg_marker::cm_tgtname, D_MGS, ENTRY, lustre_cfg::lcfg_command, LCFG_MARKER, llog_write(), llog_rec_hdr::lrh_index, llog_rec_hdr::lrh_type, lustre_cfg_buf(), lustre_cfg_sanity_check(), mgs_modify_lookup::mml_marker, mgs_modify_lookup::mml_modified, OBD_CFG_REC, REC_DATA, REC_DATA_LEN, and RETURN.
Referenced by mgs_modify().
static struct fs_db* mgs_new_fsdb (const struct lu_env * env, struct mgs_device * mgs, char * fsname) [static, read]
Definition at line 328 of file mgs_llog.c.
References CERROR, ENTRY, fs_db::fsdb_clilmv, fs_db::fsdb_clilov, fs_db::fsdb_flags, fs_db::fsdb_gen, fs_db::fsdb_list, fs_db::fsdb_mdt_index_map, fs_db::fsdb_mgs, FSDB_MGS_SELF, fs_db::fsdb_mutex, fs_db::fsdb_name, fs_db::fsdb_ost_index_map, FSDB_UDESC, GOTO, INDEX_MAP_SIZE, list_add(), lproc_mgs_add_live(), mgs_device::mgs_fs_db_list, mgs_ir_init_fs(), MGSSELF_NAME, name_create(), name_destroy(), OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, and RETURN.
Referenced by mgs_find_or_make_fsdb().
int mgs_nodemap_cmd (const struct lu_env * env, struct mgs_device * mgs, enum lcfg_command_type cmd, const char * nodemap_name, char * param)
Definition at line 4102 of file mgs_llog.c.
References ENTRY, LCFG_NODEMAP_ADD, LCFG_NODEMAP_ADD_GIDMAP, LCFG_NODEMAP_ADD_RANGE, LCFG_NODEMAP_ADD_UIDMAP, LCFG_NODEMAP_ADMIN, LCFG_NODEMAP_DEL, LCFG_NODEMAP_DEL_GIDMAP, LCFG_NODEMAP_DEL_RANGE, LCFG_NODEMAP_DEL_UIDMAP, LCFG_NODEMAP_SQUASH_GID, LCFG_NODEMAP_SQUASH_UID, LCFG_NODEMAP_TRUSTED, nodemap_add(), nodemap_add_idmap(), nodemap_add_range(), nodemap_del(), nodemap_del_idmap(), nodemap_del_range(), NODEMAP_GID, nodemap_parse_idmap(), nodemap_parse_range(), nodemap_set_allow_root(), nodemap_set_squash_gid(), nodemap_set_squash_uid(), nodemap_set_trust_client_ids(), NODEMAP_UID, and RETURN.
Referenced by mgs_iocontrol_nodemap().
static __inline__ int mgs_param_empty (char * ptr) [static]
Definition at line 2588 of file mgs_llog.c.
Referenced by mgs_wlp_lcfg(), mgs_write_log_failnid_internal(), and mgs_write_log_sys().
int mgs_params_fsdb_cleanup (const struct lu_env * env, struct mgs_device * mgs)
Definition at line 3961 of file mgs_llog.c.
References mgs_erase_logs(), and PARAMS_FILENAME.
Referenced by mgs_device_fini(), and mgs_init0().
int mgs_params_fsdb_setup (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb)
Definition at line 3940 of file mgs_llog.c.
References ENTRY, fs_db::fsdb_mutex, mgs_find_or_make_fsdb(), PARAMS_FILENAME, record_end_log(), record_start_log(), and RETURN.
Referenced by mgs_init0().
static int mgs_parse_devname (char * devname, char * fsname, __u32 * index) [static]
Parse device name and get file system name and/or device index.
Parameters:
[in] devname device name (ex. lustre-MDT0000)
[out] fsname file system name(optional)
[out] index device index(optional)
Return values:
0 success
Definition at line 1128 of file mgs_llog.c.
References CDEBUG, D_MGS, ENTRY, RETURN, server_name2fsname(), and server_name2index().
Referenced by mgs_replace_nids(), and mgs_setparam().
int mgs_pool_cmd (const struct lu_env * env, struct mgs_device * mgs, enum lcfg_command_type cmd, char * fsname, char * poolname, char * ostname)
Definition at line 4179 of file mgs_llog.c.
References CERROR, CM_SKIP, CONFIG_T_CONFIG, ENTRY, EXIT, fs_db::fsdb_clilov, fs_db::fsdb_flags, FSDB_LOG_EMPTY, fs_db::fsdb_mdt_index_map, fs_db::fsdb_mutex, GOTO, INDEX_MAP_SIZE, LCFG_POOL_ADD, LCFG_POOL_DEL, LCFG_POOL_NEW, LCFG_POOL_REM, mgs_find_or_make_fsdb(), mgs_free_fsdb(), mgs_modify(), mgs_revoke_lock(), mgs_write_log_pool(), mgs_target_info::mti_svname, name_create(), name_create_mdt_and_lov(), name_destroy(), OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, and RETURN.
Referenced by mgs_iocontrol_pool().
static int mgs_replace_handler (const struct lu_env * env, struct llog_handle * llh, struct llog_rec_hdr * rec, void * data) [static]
Handler that called for every record in llog.
Records are processed in order they placed in llog.
Parameters:
[in] llh log to be processed
[in] rec current record
[in] data mgs_replace_uuid_lookup structure
Return values:
0 success
Definition at line 929 of file mgs_llog.c.
References CDEBUG, CERROR, check_markers(), D_MGS, mgs_replace_uuid_lookup::device_nids_added, ENTRY, GOTO, mgs_replace_uuid_lookup::in_target_device, LCFG_ADD_CONN, LCFG_ADD_UUID, lustre_cfg::lcfg_command, LLOG_NEXT_IDX, llog_write(), llog_rec_hdr::lrh_index, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, lustre_cfg_sanity_check(), lustre_cfg_string(), OBD_CFG_REC, process_command(), REC_DATA, REC_DATA_LEN, RETURN, mgs_replace_uuid_lookup::skip_it, and mgs_replace_uuid_lookup::temp_llh.
Referenced by mgs_replace_nids_log().
int mgs_replace_nids (const struct lu_env * env, struct mgs_device * mgs, char * devname, char * nids)
Replace nids for device to nids values.
Parameters:
obd MGS obd device
devname nids need to be replaced for this device (ex. lustre-OST0000)
nids nids list (ex. nid1,nid2,nid3)
Return values:
0 success
Definition at line 1205 of file mgs_llog.c.
References CERROR, ENTRY, fs_db::fsdb_mdt_index_map, GOTO, INDEX_MAP_SIZE, mgs_find_or_make_fsdb(), mgs_device::mgs_obd, mgs_parse_devname(), mgs_replace_nids_log(), MTI_NAME_MAXLEN, name_create(), name_create_mdt(), name_destroy(), obd_device::obd_dev_lock, obd_device::obd_no_conn, only_mgs_is_running(), and RETURN.
Referenced by mgs_iocontrol().
static int mgs_replace_nids_log (const struct lu_env * env, struct obd_device * mgs, struct fs_db * fsdb, char * logname, char * devname, char * nids) [static]
Definition at line 1008 of file mgs_llog.c.
References CDEBUG, CERROR, D_MGS, ENTRY, GOTO, LASSERT, llog_backup(), llog_close(), LLOG_CONFIG_ORIG_CTXT, llog_ctxt_put(), llog_erase(), LLOG_F_IS_PLAIN, llog_get_context(), llog_get_size(), llog_init_handle(), llog_open(), llog_open_create(), LLOG_OPEN_EXISTS, llog_process(), lu2mgs_dev(), mgs_log_is_empty(), mgs_replace_handler(), mgs_target_info::mti_params, mgs_target_info::mti_svname, OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, obd_device::obd_lu_dev, obd_device::obd_name, RETURN, strlcpy(), mgs_replace_uuid_lookup::target, mgs_replace_uuid_lookup::temp_llh, and obd_uuid::uuid.
Referenced by mgs_replace_nids().
static int mgs_set_index (const struct lu_env * env, struct mgs_device * mgs, struct mgs_target_info * mti) [static]
Definition at line 530 of file mgs_llog.c.
References CDEBUG, CERROR, D_MGS, ENTRY, fs_db::fsdb_flags, FSDB_LOG_EMPTY, fs_db::fsdb_mdt_count, fs_db::fsdb_mdt_index_map, fs_db::fsdb_mutex, fs_db::fsdb_ost_index_map, GOTO, INDEX_MAP_SIZE, LCONSOLE_ERROR_MSG, LDD_F_NEED_INDEX, LDD_F_SV_TYPE_MDT, LDD_F_SV_TYPE_OST, LDD_F_VIRGIN, LDD_F_WRITECONF, mgs_find_or_make_fsdb(), mgs_target_info::mti_flags, mgs_target_info::mti_fsname, mgs_target_info::mti_stripe_index, mgs_target_info::mti_svname, next_index(), RETURN, and server_make_name().
Referenced by mgs_write_log_target().
int mgs_setparam (const struct lu_env * env, struct mgs_device * mgs, struct lustre_cfg * lcfg, char * fsname)
Definition at line 3970 of file mgs_llog.c.
References CDEBUG, CERROR, CONFIG_T_CONFIG, CONFIG_T_PARAMS, D_MGS, devname, ENTRY, fs_db::fsdb_flags, FSDB_LOG_EMPTY, FSDB_MGS_SELF, fs_db::fsdb_mutex, GOTO, lustre_cfg::lcfg_command, LCFG_SET_PARAM, LCONSOLE_ERROR_MSG, LDD_F_PARAM, LDD_F_PARAM2, lustre_cfg_string(), mgs_find_or_make_fsdb(), mgs_free_fsdb(), mgs_parse_devname(), mgs_revoke_lock(), mgs_write_log_param(), mgs_write_log_param2(), mgs_target_info::mti_flags, mgs_target_info::mti_fsname, MTI_NAME_MAXLEN, mgs_target_info::mti_params, mgs_target_info::mti_stripe_index, mgs_target_info::mti_svname, OBD_ALLOC_PTR, OBD_FREE_PTR, PARAM_LLITE, PARAMS_FILENAME, print_lustre_cfg(), RETURN, server_make_name(), server_name2index(), and strlcpy().
Referenced by mgs_iocontrol(), and mgs_set_info().
static int mgs_srpc_read_handler (const struct lu_env * env, struct llog_handle * llh, struct llog_rec_hdr * rec, void * data) [static]
Definition at line 3136 of file mgs_llog.c.
References CERROR, CM_END, cfg_marker::cm_flags, CM_SKIP, CM_START, ENTRY, lustre_cfg::lcfg_command, LCFG_MARKER, LCFG_SPTLRPC_CONF, llog_rec_hdr::lrh_type, lustre_cfg_buf(), lustre_cfg_sanity_check(), lustre_cfg_string(), mgs_srpc_set_param_mem(), mgs_srpc_read_data::msrd_fsdb, mgs_srpc_read_data::msrd_skip, OBD_CFG_REC, REC_DATA, REC_DATA_LEN, and RETURN.
Referenced by mgs_get_fsdb_srpc_from_llog().
static int mgs_srpc_set_param (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb, struct mgs_target_info * mti, char * param) [static]
Definition at line 3087 of file mgs_llog.c.
References ENTRY, fs_db::fsdb_flags, FSDB_MGS_SELF, fs_db::fsdb_srpc_gen, fs_db::fsdb_srpc_tgt, LASSERT, mgs_device::mgs_obd, mgs_srpc_set_param_disk(), mgs_srpc_set_param_mem(), mgs_target_info::mti_svname, OBD_ALLOC, OBD_FREE, RETURN, and sptlrpc_target_update_exp_flavor().
Referenced by mgs_write_log_param().
static int mgs_srpc_set_param_disk (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb, struct mgs_target_info * mti, char * param) [static]
Definition at line 2899 of file mgs_llog.c.
References CERROR, CM_SKIP, ENTRY, GOTO, LASSERT, LCFG_SPTLRPC_CONF, lcr, lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_rec_free(), lustre_cfg_rec_new(), mgs_thread_info::mgi_bufs, mgs_env_info(), mgs_log_is_empty(), mgs_modify(), mgs_device::mgs_obd, mgs_write_log_direct(), mgs_target_info::mti_fsname, mgs_target_info::mti_svname, name_create(), name_destroy(), OBD_ALLOC, OBD_FREE, obd_device::obd_name, record_end_log(), record_start_log(), and RETURN.
Referenced by mgs_srpc_set_param().
static int mgs_srpc_set_param_mem (struct fs_db * fsdb, const char * svname, char * param) [static]
Definition at line 2999 of file mgs_llog.c.
References CERROR, ENTRY, fs_db::fsdb_flags, fs_db::fsdb_mgs, FSDB_MGS_SELF, fs_db::fsdb_srpc_gen, fs_db::fsdb_srpc_tgt, LUSTRE_SP_ANY, LUSTRE_SP_MGC, LUSTRE_SP_MGS, lu_target::lut_sptlrpc_rset, mgs_device::mgs_lut, mgs_srpc_set_param_udesc_mem(), MGSSELF_NAME, mgs_tgt_srpc_conf::mtsc_next, mgs_tgt_srpc_conf::mtsc_rset, mgs_tgt_srpc_conf::mtsc_tgt, OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE_PTR, PARAM_SRPC, PARAM_SRPC_FLVR, PARAM_SRPC_UDESC, RETURN, sptlrpc_parse_rule(), sptlrpc_rule_set_merge(), sptlrpc_rule::sr_from, and sptlrpc_rule::sr_to.
Referenced by mgs_srpc_read_handler(), and mgs_srpc_set_param().
static int mgs_srpc_set_param_udesc_mem (struct fs_db * fsdb, char * param) [static]
Definition at line 2964 of file mgs_llog.c.
References CERROR, CWARN, fs_db::fsdb_flags, FSDB_UDESC, and PARAM_SRPC_UDESC.
Referenced by mgs_srpc_set_param_mem().
static int mgs_steal_client_llog_handler (const struct lu_env * env, struct llog_handle * llh, struct llog_rec_hdr * rec, void * data) [static]
Walk through client config log record and convert the related records into the target.
Definition at line 1541 of file mgs_llog.c.
References __u64, add_param(), CERROR, cfg_marker::cm_comment, CM_END, cfg_marker::cm_flags, CM_SKIP, CM_START, cfg_marker::cm_step, cfg_marker::cm_tgtname, ENTRY, LASSERT, LCFG_ADD_MDC, LCFG_ADD_UUID, lustre_cfg::lcfg_command, LCFG_LOV_ADD_OBD, LCFG_MARKER, lustre_cfg::lcfg_nid, LCFG_SETUP, LCFG_SPTLRPC_CONF, libcfs_nid2str_r(), LNET_NIDSTR_SIZE, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, lu2mgs_dev(), lustre_cfg_buf(), lustre_cfg_sanity_check(), lustre_cfg_string(), LUSTRE_SP_MDT, mgs_write_log_osc_to_lov(), mgs_write_log_osp_to_mdt(), mgs_target_info::mti_fsname, mgs_target_info::mti_nid_count, mgs_target_info::mti_nids, mgs_target_info::mti_params, mgs_target_info::mti_stripe_index, mgs_target_info::mti_svname, mgs_target_info::mti_uuid, name_create_mdt_and_lov(), name_destroy(), OBD_CFG_REC, obd_device::obd_lu_dev, PARAM_FAILNODE, record_end_log(), record_marker(), record_start_log(), RETURN, and strlcpy().
Referenced by mgs_steal_llog_for_mdt_from_client().
static int mgs_steal_llog_for_mdt_from_client (const struct lu_env * env, struct mgs_device * mgs, char * client_name, struct temp_comp * comp) [static]
Definition at line 1725 of file mgs_llog.c.
References CDEBUG, temp_comp::comp_obd, temp_comp::comp_tmti, D_MGS, ENTRY, GOTO, LASSERT, llog_close(), LLOG_CONFIG_ORIG_CTXT, llog_ctxt_put(), LLOG_F_IS_PLAIN, llog_get_context(), llog_init_handle(), llog_open(), LLOG_OPEN_EXISTS, llog_process_or_fork(), mgs_device::mgs_obd, mgs_steal_client_llog_handler(), OBD_ALLOC_PTR, OBD_FREE_PTR, and RETURN.
Referenced by mgs_write_log_mdt().
static int mgs_wlp_lcfg (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb, struct mgs_target_info * mti, char * logname, struct lustre_cfg_bufs * bufs, char * tgtname, char * ptr) [static]
Definition at line 2709 of file mgs_llog.c.
References CM_SKIP, LCFG_PARAM, LCFG_SET_PARAM, LCONSOLE_INFO, lcr, LCTL_UPCALL, LDD_F_PARAM2, lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_rec_free(), lustre_cfg_rec_new(), mgs_modify(), mgs_param_empty(), mgs_write_log_direct(), mgs_target_info::mti_flags, and MTI_NAME_MAXLEN.
Referenced by mgs_write_log_param(), and mgs_write_log_param2().
static int mgs_write_log_add_failnid (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb, struct mgs_target_info * mti) [static]
Definition at line 2637 of file mgs_llog.c.
References ENTRY, fs_db::fsdb_mdt_index_map, INDEX_MAP_SIZE, LCONSOLE_ERROR_MSG, LDD_F_SV_TYPE_MDT, LDD_F_SV_TYPE_OST, mgs_log_is_empty(), mgs_write_log_failnid_internal(), mgs_target_info::mti_flags, mgs_target_info::mti_fsname, mgs_target_info::mti_svname, name_create(), name_create_mdt(), name_create_mdt_osc(), name_destroy(), and RETURN.
Referenced by mgs_check_failnid(), and mgs_write_log_param().
static int mgs_write_log_direct (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb, char * logname, struct llog_cfg_rec * lcr, char * devname, char * comment) [static]
Definition at line 1419 of file mgs_llog.c.
References CM_END, CM_START, ENTRY, GOTO, llog_cfg_rec::lcr_hdr, LLOG_NEXT_IDX, llog_write(), record_end_log(), record_marker(), record_start_log(), and RETURN.
Referenced by mgs_srpc_set_param_disk(), mgs_wlp_lcfg(), and mgs_write_log_direct_all().
static int mgs_write_log_direct_all (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb, struct mgs_target_info * mti, struct llog_cfg_rec * lcr, char * devname, char * comment, int server_only) [static]
Definition at line 1449 of file mgs_llog.c.
References CDEBUG, CERROR, class_dentry_readdir(), CM_SKIP, D_MGS, ENTRY, list_del_init(), list_for_each_entry_safe, mgs_direntry::mde_list, mgs_direntry::mde_name, mgs_direntry_free(), mgs_modify(), mgs_device::mgs_obd, mgs_write_log_direct(), mgs_target_info::mti_fsname, obd_device::obd_name, and RETURN.
Referenced by mgs_write_log_quota(), and mgs_write_log_sys().
static int mgs_write_log_failnid_internal (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb, struct mgs_target_info * mti, char * logname, char * cliname) [static]
Definition at line 2597 of file mgs_llog.c.
References CM_END, CM_SKIP, CM_START, mgs_modify(), mgs_param_empty(), mgs_write_log_failnids(), mgs_target_info::mti_params, mgs_target_info::mti_svname, record_end_log(), record_marker(), and record_start_log().
Referenced by mgs_write_log_add_failnid().
static int mgs_write_log_failnids (const struct lu_env * env, struct mgs_target_info * mti, struct llog_handle * llh, char * cliname) [static]
Definition at line 1879 of file mgs_llog.c.
References CDEBUG, class_find_param(), class_parse_nid(), D_MGS, libcfs_nid2str_r(), LNET_NIDSTR_SIZE, mgs_target_info::mti_params, name_create(), name_destroy(), PARAM_FAILNODE, record_add_conn(), and record_add_uuid().
Referenced by mgs_write_log_failnid_internal(), mgs_write_log_mdc_to_lmv(), mgs_write_log_osc_to_lov(), and mgs_write_log_osp_to_mdt().
static int mgs_write_log_lmv (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb, struct mgs_target_info * mti, char * logname, char * lmvname) [static]
Definition at line 1773 of file mgs_llog.c.
References CDEBUG, CM_END, CM_START, D_MGS, ENTRY, GOTO, lmv_desc::ld_active_tgt_count, lmv_desc::ld_tgt_count, lmv_desc::ld_uuid, OBD_ALLOC_PTR, OBD_FREE_PTR, record_attach(), record_end_log(), record_lmv_setup(), record_marker(), record_start_log(), RETURN, obd_uuid::uuid, and uuid.
Referenced by mgs_write_log_mdt(), and mgs_write_log_ost().
static int mgs_write_log_lov (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb, struct mgs_target_info * mti, char * logname, char * lovname) [static]
Definition at line 1818 of file mgs_llog.c.
References CDEBUG, CM_END, CM_START, D_MGS, ENTRY, EXIT, GOTO, lov_desc::ld_default_stripe_count, lov_desc::ld_default_stripe_offset, lov_desc::ld_default_stripe_size, lov_desc::ld_pattern, lov_desc::ld_qos_maxage, lov_desc::ld_tgt_count, lov_desc::ld_uuid, LOV_DESC_MAGIC, LOV_DESC_QOS_MAXAGE_DEFAULT, LOV_DESC_STRIPE_SIZE_DEFAULT, LOV_PATTERN_RAID0, OBD_ALLOC_PTR, OBD_FREE_PTR, record_attach(), record_end_log(), record_lov_setup(), record_marker(), record_start_log(), RETURN, obd_uuid::uuid, and uuid.
Referenced by mgs_write_log_mdt(), mgs_write_log_mdt0(), and mgs_write_log_ost().
static int mgs_write_log_mdc_to_lmv (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb, struct mgs_target_info * mti, char * logname, char * lmvname) [static]
Definition at line 1942 of file mgs_llog.c.
References CDEBUG, CERROR, CM_END, CM_START, D_MGS, ENTRY, GOTO, libcfs_nid2str_r(), LNET_NIDSTR_SIZE, LUSTRE_MDC_NAME, mgs_log_is_empty(), mgs_write_log_failnids(), mgs_target_info::mti_nid_count, mgs_target_info::mti_nids, mgs_target_info::mti_stripe_index, mgs_target_info::mti_svname, mgs_target_info::mti_uuid, name_create(), name_destroy(), record_add_uuid(), record_attach(), record_end_log(), record_marker(), record_mdc_add(), record_setup(), record_start_log(), and RETURN.
Referenced by mgs_write_log_mdt().
static int mgs_write_log_mdt (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb, struct mgs_target_info * mti) [static]
Definition at line 2247 of file mgs_llog.c.
References CDEBUG, CM_END, CM_START, temp_comp::comp_fsdb, temp_comp::comp_mti, D_MGS, ENTRY, fs_db::fsdb_clilmv, fs_db::fsdb_clilov, fs_db::fsdb_mdt_index_map, fs_db::fsdb_name, GOTO, INDEX_MAP_SIZE, mgs_thread_info::mgi_comp, mgs_env_info(), mgs_log_is_empty(), mgs_steal_llog_for_mdt_from_client(), mgs_write_log_lmv(), mgs_write_log_lov(), mgs_write_log_mdc_to_lmv(), mgs_write_log_mdt0(), mgs_write_log_osp_to_mdt(), mgs_target_info::mti_fsname, mgs_target_info::mti_stripe_index, mgs_target_info::mti_svname, mgs_target_info::mti_uuid, name_create(), name_create_mdt(), name_destroy(), record_end_log(), record_marker(), record_mount_opt(), record_start_log(), and RETURN.
Referenced by mgs_write_log_target().
static int mgs_write_log_mdt0 (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb, struct mgs_target_info * mti) [static]
Definition at line 2182 of file mgs_llog.c.
References class_find_param(), CM_END, CM_START, ENTRY, GOTO, LUSTRE_MDT_NAME, mgs_log_is_empty(), mgs_write_log_lov(), mgs_target_info::mti_params, mgs_target_info::mti_stripe_index, mgs_target_info::mti_svname, name_create(), name_destroy(), OBD_ALLOC, OBD_FREE, PARAM_FAILMODE, record_attach(), record_end_log(), record_marker(), record_mount_opt(), record_setup(), record_start_log(), RETURN, and uuid.
Referenced by mgs_write_log_mdt().
static int mgs_write_log_osc_to_lov (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb, struct mgs_target_info * mti, char * logname, char * suffix, char * lovname, enum lustre_sec_part sec_part, int flags) [static]
Definition at line 2353 of file mgs_llog.c.
References CDEBUG, CERROR, CM_END, CM_START, D_INFO, D_MGS, ENTRY, fs_db::fsdb_flags, FSDB_OSCNAME18, GOTO, libcfs_nid2str_r(), LNET_NIDSTR_SIZE, LUSTRE_OSC_NAME, mgs_log_is_empty(), mgs_write_log_failnids(), mgs_target_info::mti_nid_count, mgs_target_info::mti_nids, mgs_target_info::mti_stripe_index, mgs_target_info::mti_svname, mgs_target_info::mti_uuid, name_create(), name_destroy(), record_add_uuid(), record_attach(), record_end_log(), record_lov_add(), record_marker(), record_setup(), record_start_log(), and RETURN.
Referenced by mgs_steal_client_llog_handler(), and mgs_write_log_ost().
static int mgs_write_log_osp_to_mdt (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb, struct mgs_target_info * mti, int index, char * logname) [static]
Definition at line 2069 of file mgs_llog.c.
References CDEBUG, CERROR, CM_END, CM_START, D_MGS, ENTRY, fs_db::fsdb_name, GOTO, LCFG_ADD_MDC, libcfs_nid2str_r(), LNET_NIDSTR_SIZE, LUSTRE_OSP_NAME, mgs_log_is_empty(), mgs_write_log_failnids(), mgs_target_info::mti_nid_count, mgs_target_info::mti_nids, mgs_target_info::mti_stripe_index, mgs_target_info::mti_svname, mgs_target_info::mti_uuid, name_create(), name_create_lov(), name_create_mdt(), name_destroy(), record_add_uuid(), record_attach(), record_base(), record_end_log(), record_marker(), record_setup(), record_start_log(), and RETURN.
Referenced by mgs_steal_client_llog_handler(), and mgs_write_log_mdt().
static int mgs_write_log_ost (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb, struct mgs_target_info * mti) [static]
Definition at line 2469 of file mgs_llog.c.
References CDEBUG, class_find_param(), CM_END, CM_SKIP, CM_START, CM_UPGRADE146, D_MGS, ENTRY, fs_db::fsdb_clilmv, fs_db::fsdb_clilov, fs_db::fsdb_flags, fs_db::fsdb_mdt_index_map, FSDB_OLDLOG14, GOTO, INDEX_MAP_SIZE, LCONSOLE_ERROR_MSG, LCONSOLE_WARN, LDD_F_UPDATE, LUSTRE_SP_CLI, LUSTRE_SP_MDT, mgs_log_is_empty(), mgs_write_log_lmv(), mgs_write_log_lov(), mgs_write_log_osc_to_lov(), mgs_target_info::mti_flags, mgs_target_info::mti_fsname, mgs_target_info::mti_params, mgs_target_info::mti_svname, mgs_target_info::mti_uuid, name_create(), name_create_mdt_and_lov(), name_destroy(), PARAM_FAILMODE, record_attach(), record_end_log(), record_marker(), record_setup(), record_start_log(), and RETURN.
Referenced by mgs_write_log_target().
static int mgs_write_log_param (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb, struct mgs_target_info * mti, char * ptr) [static]
Definition at line 3258 of file mgs_llog.c.
References CDEBUG, CERROR, class_match_param(), CM_EXCLUDE, D_MGS, end, ENTRY, fs_db::fsdb_clilov, fs_db::fsdb_flags, fs_db::fsdb_mdt_index_map, FSDB_OLDLOG14, GOTO, INDEX_MAP_SIZE, LCONSOLE_ERROR, LCONSOLE_ERROR_MSG, LCONSOLE_WARN, LDD_F_PARAM, LDD_F_SV_ALL, LDD_F_SV_TYPE_MDT, LDD_F_SV_TYPE_OST, mgs_thread_info::mgi_bufs, mgs_env_info(), mgs_log_is_empty(), mgs_modify(), mgs_srpc_set_param(), mgs_wlp_lcfg(), mgs_write_log_add_failnid(), mgs_write_log_quota(), mgs_write_log_sys(), mgs_target_info::mti_flags, mgs_target_info::mti_fsname, MTI_NAME_MAXLEN, mgs_target_info::mti_stripe_index, mgs_target_info::mti_svname, name_create(), name_create_mdt(), name_create_mdt_and_lov(), name_create_mdt_osc(), name_destroy(), PARAM_ACTIVE, PARAM_FAILMODE, PARAM_FAILNODE, PARAM_LLITE, PARAM_LOV, PARAM_MDC, PARAM_MDD, PARAM_MDT, PARAM_MGSNODE, PARAM_NETWORK, PARAM_OSC, PARAM_OSD, PARAM_OSP, PARAM_OST, PARAM_QUOTA, PARAM_SRPC, PARAM_SYS, RETURN, and server_name2index().
Referenced by mgs_setparam(), and mgs_write_log_target().
static int mgs_write_log_param2 (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb, struct mgs_target_info * mti, char * ptr) [static]
Definition at line 2758 of file mgs_llog.c.
References CDEBUG, D_MGS, ENTRY, mgs_wlp_lcfg(), mgs_target_info::mti_svname, PARAMS_FILENAME, and RETURN.
Referenced by mgs_setparam().
static int mgs_write_log_pool (const struct lu_env * env, struct mgs_device * mgs, char * logname, struct fs_db * fsdb, char * tgtname, enum lcfg_command_type cmd, char * fsname, char * poolname, char * ostname, char * comment) [static]
Definition at line 4076 of file mgs_llog.c.
References CM_END, CM_START, record_base(), record_end_log(), record_marker(), and record_start_log().
Referenced by mgs_pool_cmd().
static int mgs_write_log_quota (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb, struct mgs_target_info * mti, char * quota, char * ptr) [static]
Definition at line 2846 of file mgs_llog.c.
References CDEBUG, CERROR, class_match_param(), cmd, D_MGS, LCFG_PARAM, lcr, lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_rec_free(), lustre_cfg_rec_new(), mgs_thread_info::mgi_bufs, mgs_env_info(), mgs_write_log_direct_all(), mgs_target_info::mti_fsname, QUOTA_DATAPOOL_NAME, and QUOTA_METAPOOL_NAME.
Referenced by mgs_write_log_param().
static int mgs_write_log_sys (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb, struct mgs_target_info * mti, char * sys, char * ptr) [static]
Definition at line 2775 of file mgs_llog.c.
References CDEBUG, class_match_param(), class_process_config(), cmd, D_MGS, lustre_cfg::lcfg_num, LCFG_PARAM, LCFG_SET_LDLM_TIMEOUT, LCFG_SET_TIMEOUT, lcr, llog_cfg_rec::lcr_cfg, ldlm_timeout, ldlm_timeout_set, lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_rec_free(), lustre_cfg_rec_new(), mgs_thread_info::mgi_bufs, mgs_env_info(), mgs_param_empty(), mgs_write_log_direct_all(), mgs_target_info::mti_fsname, obd_timeout, obd_timeout_set, PARAM_AT_EARLY_MARGIN, PARAM_AT_EXTRA, PARAM_AT_HISTORY, PARAM_AT_MAX, PARAM_AT_MIN, PARAM_JOBID_VAR, PARAM_LDLM_TIMEOUT, and PARAM_TIMEOUT.
Referenced by mgs_write_log_param().
int mgs_write_log_target (const struct lu_env * env, struct mgs_device * mgs, struct mgs_target_info * mti, struct fs_db * fsdb)
Definition at line 3723 of file mgs_llog.c.
References buf, CDEBUG, CERROR, class_get_next_param(), D_MGS, ENTRY, fs_db::fsdb_mutex, GOTO, LCONSOLE_WARN, LDD_F_PARAM, LDD_F_SV_TYPE_MDT, LDD_F_SV_TYPE_OST, LDD_F_UPDATE, LDD_F_UPGRADE14, LDD_F_VIRGIN, LDD_F_WRITECONF, mgs_set_index(), mgs_write_log_mdt(), mgs_write_log_ost(), mgs_write_log_param(), mgs_target_info::mti_flags, mgs_target_info::mti_params, mgs_target_info::mti_stripe_index, mgs_target_info::mti_svname, OBD_ALLOC, OBD_FREE, and RETURN.
Referenced by mgs_target_reg().
static int name_create (char ** newname, char * prefix, char * suffix) [inline, static]
Definition at line 131 of file mgs_llog.c.
References LASSERT, and OBD_ALLOC.
Referenced by mgs_get_fsdb_from_llog(), mgs_get_fsdb_srpc_from_llog(), mgs_new_fsdb(), mgs_pool_cmd(), mgs_replace_nids(), mgs_srpc_set_param_disk(), mgs_write_log_add_failnid(), mgs_write_log_failnids(), mgs_write_log_mdc_to_lmv(), mgs_write_log_mdt(), mgs_write_log_mdt0(), mgs_write_log_osc_to_lov(), mgs_write_log_osp_to_mdt(), mgs_write_log_ost(), mgs_write_log_param(), name_create_lov(), name_create_mdt(), name_create_mdt_and_lov(), and name_create_mdt_osc().
static int name_create_lov (char ** lovname, char * mdtname, struct fs_db * fsdb, int index) [inline, static]
Definition at line 2026 of file mgs_llog.c.
References fs_db::fsdb_flags, fs_db::fsdb_name, FSDB_OSCNAME18, and name_create().
Referenced by mgs_write_log_osp_to_mdt().
static int name_create_mdt (char ** logname, char * fsname, int i) [static]
Definition at line 1187 of file mgs_llog.c.
References name_create().
Referenced by mgs_replace_nids(), mgs_write_log_add_failnid(), mgs_write_log_mdt(), mgs_write_log_osp_to_mdt(), mgs_write_log_param(), and name_create_mdt_and_lov().
static int name_create_mdt_and_lov (char ** logname, char ** lovname, struct fs_db * fsdb, int i) [static]
Definition at line 2036 of file mgs_llog.c.
References fs_db::fsdb_flags, fs_db::fsdb_name, FSDB_OSCNAME18, name_create(), name_create_mdt(), and name_destroy().
Referenced by mgs_pool_cmd(), mgs_steal_client_llog_handler(), mgs_write_log_ost(), and mgs_write_log_param().
static int name_create_mdt_osc (char ** oscname, char * ostname, struct fs_db * fsdb, int i) [inline, static]
Definition at line 2056 of file mgs_llog.c.
References fs_db::fsdb_flags, FSDB_OSCNAME18, and name_create().
Referenced by mgs_write_log_add_failnid(), and mgs_write_log_param().
static void name_destroy (char ** name) [inline, static]
Definition at line 141 of file mgs_llog.c.
References OBD_FREE.
Referenced by mgs_free_fsdb(), mgs_get_fsdb_from_llog(), mgs_get_fsdb_srpc_from_llog(), mgs_new_fsdb(), mgs_pool_cmd(), mgs_replace_nids(), mgs_srpc_set_param_disk(), mgs_steal_client_llog_handler(), mgs_write_log_add_failnid(), mgs_write_log_failnids(), mgs_write_log_mdc_to_lmv(), mgs_write_log_mdt(), mgs_write_log_mdt0(), mgs_write_log_osc_to_lov(), mgs_write_log_osp_to_mdt(), mgs_write_log_ost(), mgs_write_log_param(), and name_create_mdt_and_lov().
static __inline__ int next_index (void * index_map, int map_len) [static]
Definition at line 515 of file mgs_llog.c.
References CERROR.
Referenced by mgs_set_index().
static int only_mgs_is_running (struct obd_device * mgs_obd) [static]
Definition at line 1156 of file mgs_llog.c.
References CERROR, exp_connect_flags(), obd_export::exp_nid_stats, obd_export::exp_obd_chain, get_devices_count(), libcfs_nid2str(), list_for_each_entry, nid_stat::nid, OBD_CONNECT_MDS_MDS, obd_device::obd_dev_lock, obd_device::obd_exports, obd_device::obd_name, and obd_device::obd_self_export.
Referenced by mgs_replace_nids().
static void print_lustre_cfg (struct lustre_cfg * lcfg) [static]
Definition at line 3902 of file mgs_llog.c.
References CDEBUG, D_MGS, ENTRY, EXIT, lustre_cfg::lcfg_bufcount, lustre_cfg::lcfg_buflens, lustre_cfg::lcfg_command, lustre_cfg::lcfg_flags, lustre_cfg::lcfg_nid, lustre_cfg::lcfg_num, lustre_cfg::lcfg_version, libcfs_nid2str(), LUSTRE_CFG_MAX_BUFCOUNT, and lustre_cfg_string().
Referenced by lustre_swab_lustre_cfg(), and mgs_setparam().
static int process_command (const struct lu_env * env, struct lustre_cfg * lcfg, struct mgs_replace_uuid_lookup * mrul) [static]
Return values:
<0 record processing error
n record is processed. No need copy original one.
0 record is not processed.
Definition at line 860 of file mgs_llog.c.
References CDEBUG, CERROR, class_parse_nid(), D_MGS, mgs_replace_uuid_lookup::device_nids_added, LCFG_ADD_UUID, lustre_cfg::lcfg_command, LCFG_SETUP, libcfs_nid2str(), lustre_cfg_string(), mgs_target_info::mti_params, mgs_target_info::mti_svname, record_add_uuid(), record_setup(), RETURN, mgs_replace_uuid_lookup::target, and mgs_replace_uuid_lookup::temp_llh.
Referenced by mgs_replace_handler().
static int record_add_conn (const struct lu_env * env, struct llog_handle * llh, char * devname, char * uuid) [inline, static]
Definition at line 832 of file mgs_llog.c.
References LCFG_ADD_CONN, and record_base().
Referenced by mgs_write_log_failnids().
static int record_add_uuid (const struct lu_env * env, struct llog_handle * llh, uint64_t nid, char * uuid) [inline, static]
Definition at line 824 of file mgs_llog.c.
References LCFG_ADD_UUID, and record_base().
Referenced by mgs_write_log_failnids(), mgs_write_log_mdc_to_lmv(), mgs_write_log_osc_to_lov(), mgs_write_log_osp_to_mdt(), and process_command().
static int record_attach (const struct lu_env * env, struct llog_handle * llh, char * devname, char * type, char * uuid) [inline, static]
Definition at line 840 of file mgs_llog.c.
References LCFG_ATTACH, and record_base().
Referenced by mgs_write_log_lmv(), mgs_write_log_lov(), mgs_write_log_mdc_to_lmv(), mgs_write_log_mdt0(), mgs_write_log_osc_to_lov(), mgs_write_log_osp_to_mdt(), and mgs_write_log_ost().
static int record_base (const struct lu_env * env, struct llog_handle * llh, char * cfgname, lnet_nid_t nid, int cmd, char * s1, char * s2, char * s3, char * s4) [static]
Definition at line 787 of file mgs_llog.c.
References CDEBUG, D_MGS, lustre_cfg::lcfg_nid, lcr, llog_cfg_rec::lcr_cfg, llog_cfg_rec::lcr_hdr, LLOG_NEXT_IDX, llog_write(), lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_rec_free(), lustre_cfg_rec_new(), mgs_thread_info::mgi_bufs, and mgs_env_info().
Referenced by mgs_write_log_osp_to_mdt(), mgs_write_log_pool(), record_add_conn(), record_add_uuid(), record_attach(), record_lov_add(), record_mdc_add(), record_mount_opt(), and record_setup().
static int record_end_log (const struct lu_env * env, struct llog_handle ** llh) [static]
Definition at line 1406 of file mgs_llog.c.
References llog_close().
Referenced by mgs_params_fsdb_setup(), mgs_srpc_set_param_disk(), mgs_steal_client_llog_handler(), mgs_write_log_direct(), mgs_write_log_failnid_internal(), mgs_write_log_lmv(), mgs_write_log_lov(), mgs_write_log_mdc_to_lmv(), mgs_write_log_mdt(), mgs_write_log_mdt0(), mgs_write_log_osc_to_lov(), mgs_write_log_osp_to_mdt(), mgs_write_log_ost(), and mgs_write_log_pool().
static int record_lmv_setup (const struct lu_env * env, struct llog_handle * llh, char * devname, struct lmv_desc * desc) [static]
Definition at line 1290 of file mgs_llog.c.
References LCFG_SETUP, lcr, llog_cfg_rec::lcr_hdr, LLOG_NEXT_IDX, llog_write(), lustre_cfg_bufs_reset(), lustre_cfg_bufs_set(), lustre_cfg_rec_free(), lustre_cfg_rec_new(), mgs_thread_info::mgi_bufs, and mgs_env_info().
Referenced by mgs_write_log_lmv().
static int record_lov_add (const struct lu_env * env, struct llog_handle * llh, char * lov_name, char * ost_uuid, char * index, char * gen) [inline, static]
Definition at line 1318 of file mgs_llog.c.
References LCFG_LOV_ADD_OBD, and record_base().
Referenced by mgs_write_log_osc_to_lov().
static int record_lov_setup (const struct lu_env * env, struct llog_handle * llh, char * devname, struct lov_desc * desc) [static]
Definition at line 1272 of file mgs_llog.c.
References LCFG_SETUP, lcr, llog_cfg_rec::lcr_hdr, LLOG_NEXT_IDX, llog_write(), lustre_cfg_bufs_reset(), lustre_cfg_bufs_set(), lustre_cfg_rec_free(), lustre_cfg_rec_new(), mgs_thread_info::mgi_bufs, and mgs_env_info().
Referenced by mgs_write_log_lov().
static int record_marker (const struct lu_env * env, struct llog_handle * llh, struct fs_db * fsdb, __u32 flags, char * tgtname, char * comment) [static]
Definition at line 1336 of file mgs_llog.c.
References cfs_time_current_sec(), cfg_marker::cm_canceltime, cfg_marker::cm_comment, cfg_marker::cm_createtime, cfg_marker::cm_flags, CM_START, cfg_marker::cm_step, cfg_marker::cm_tgtname, cfg_marker::cm_vers, fs_db::fsdb_gen, LCFG_MARKER, lcr, llog_cfg_rec::lcr_hdr, LLOG_NEXT_IDX, llog_write(), lustre_cfg_bufs_reset(), lustre_cfg_bufs_set(), lustre_cfg_rec_free(), lustre_cfg_rec_new(), LUSTRE_VERSION_CODE, mgs_thread_info::mgi_bufs, mgs_thread_info::mgi_marker, mgs_env_info(), and strlcpy().
Referenced by mgs_steal_client_llog_handler(), mgs_write_log_direct(), mgs_write_log_failnid_internal(), mgs_write_log_lmv(), mgs_write_log_lov(), mgs_write_log_mdc_to_lmv(), mgs_write_log_mdt(), mgs_write_log_mdt0(), mgs_write_log_osc_to_lov(), mgs_write_log_osp_to_mdt(), mgs_write_log_ost(), and mgs_write_log_pool().
static int record_mdc_add (const struct lu_env * env, struct llog_handle * llh, char * logname, char * mdcuuid, char * mdtuuid, char * index, char * gen) [inline, static]
Definition at line 1308 of file mgs_llog.c.
References LCFG_ADD_MDC, and record_base().
Referenced by mgs_write_log_mdc_to_lmv().
static int record_mount_opt (const struct lu_env * env, struct llog_handle * llh, char * profile, char * lov_name, char * mdc_name) [inline, static]
Definition at line 1327 of file mgs_llog.c.
References LCFG_MOUNTOPT, and record_base().
Referenced by mgs_write_log_mdt(), and mgs_write_log_mdt0().
static int record_setup (const struct lu_env * env, struct llog_handle * llh, char * devname, char * s1, char * s2, char * s3, char * s4) [inline, static]
Definition at line 848 of file mgs_llog.c.
References LCFG_SETUP, and record_base().
Referenced by mgs_write_log_mdc_to_lmv(), mgs_write_log_mdt0(), mgs_write_log_osc_to_lov(), mgs_write_log_osp_to_mdt(), mgs_write_log_ost(), and process_command().
static int record_start_log (const struct lu_env * env, struct mgs_device * mgs, struct llog_handle ** llh, char * name) [static]
Definition at line 1373 of file mgs_llog.c.
References CERROR, ENTRY, GOTO, LASSERT, llog_close(), LLOG_CONFIG_ORIG_CTXT, llog_ctxt_put(), LLOG_F_IS_PLAIN, llog_get_context(), llog_init_handle(), llog_open_create(), llog_ctxt::loc_obd, mgs_device::mgs_obd, obd_device::obd_name, RETURN, and obd_uuid::uuid.
Referenced by mgs_params_fsdb_setup(), mgs_srpc_set_param_disk(), mgs_steal_client_llog_handler(), mgs_write_log_direct(), mgs_write_log_failnid_internal(), mgs_write_log_lmv(), mgs_write_log_lov(), mgs_write_log_mdc_to_lmv(), mgs_write_log_mdt(), mgs_write_log_mdt0(), mgs_write_log_osc_to_lov(), mgs_write_log_osp_to_mdt(), mgs_write_log_ost(), and mgs_write_log_pool().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.