Lustre: lustre/mgs/mgs_handler.c File Reference
lustre/mgs/mgs_handler.c File Reference
#include <obd_class.h>
#include <lprocfs_status.h>
#include <lustre_ioctl.h>
#include <lustre_param.h>
#include "mgs_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_MGS
#define D_MGS D_CONFIG
Enumerations
enum ast_type { AST_CONFIG = 1, AST_PARAMS = 2, AST_IR = 3 }
Functions
static int mgs_connect (struct tgt_session_info *tsi)
static int mgs_disconnect (struct tgt_session_info *tsi)
static int mgs_exception (struct tgt_session_info *tsi)
static bool str_starts_with (const char *str, const char *prefix)
static int mgs_set_info (struct tgt_session_info *tsi)
static int mgs_completion_ast_generic (struct ldlm_lock *lock, __u64 flags, void *cbdata, enum ast_type type)
static int mgs_completion_ast_config (struct ldlm_lock *lock, __u64 flags, void *cbdata)
static int mgs_completion_ast_params (struct ldlm_lock *lock, __u64 flags, void *cbdata)
static int mgs_completion_ast_ir (struct ldlm_lock *lock, __u64 flags, void *cbdata)
void mgs_revoke_lock (struct mgs_device *mgs, struct fs_db *fsdb, int type)
static int mgs_check_target (const struct lu_env *env, struct mgs_device *mgs, struct mgs_target_info *mti)
static int mgs_check_failover_reg (struct mgs_target_info *mti)
static int mgs_target_reg (struct tgt_session_info *tsi)
static int mgs_target_del (struct tgt_session_info *tsi)
static int mgs_config_read (struct tgt_session_info *tsi)
static int mgs_llog_open (struct tgt_session_info *tsi)
static int mgs_init_export (struct obd_export *exp)
static int mgs_destroy_export (struct obd_export *exp)
static int mgs_extract_fs_pool (char *arg, char *fsname, char *poolname)
static int mgs_iocontrol_nodemap (const struct lu_env *env, struct mgs_device *mgs, struct obd_ioctl_data *data)
static int mgs_iocontrol_pool (const struct lu_env *env, struct mgs_device *mgs, struct obd_ioctl_data *data)
static int mgs_iocontrol (unsigned int cmd, struct obd_export *exp, int len, void *karg, void __user *uarg)
static int mgs_connect_to_osd (struct mgs_device *m, const char *nextdev)
static int mgs_init0 (const struct lu_env *env, struct mgs_device *mgs, struct lu_device_type *ldt, struct lustre_cfg *lcfg)
static struct lu_device * mgs_device_free (const struct lu_env *env, struct lu_device *lu)
static int mgs_process_config (const struct lu_env *env, struct lu_device *dev, struct lustre_cfg *lcfg)
static int mgs_object_init (const struct lu_env *env, struct lu_object *o, const struct lu_object_conf *unused)
static void mgs_object_free (const struct lu_env *env, struct lu_object *o)
static int mgs_object_print (const struct lu_env *env, void *cookie, lu_printer_t p, const struct lu_object *l)
static struct lu_object * mgs_object_alloc (const struct lu_env *env, const struct lu_object_header *hdr, struct lu_device *d)
static struct lu_device * mgs_device_alloc (const struct lu_env *env, struct lu_device_type *type, struct lustre_cfg *lcfg)
static struct lu_device * mgs_device_fini (const struct lu_env *env, struct lu_device *d)
LU_KEY_INIT_FINI (mgs, struct mgs_thread_info)
LU_TYPE_INIT_FINI (mgs,&mgs_thread_key)
LU_CONTEXT_KEY_DEFINE (mgs, LCT_MG_THREAD)
static int mgs_obd_connect (const struct lu_env *env, struct obd_export **exp, struct obd_device *obd, struct obd_uuid *cluuid, struct obd_connect_data *data, void *localdata)
static int mgs_obd_reconnect (const struct lu_env *env, struct obd_export *exp, struct obd_device *obd, struct obd_uuid *cluuid, struct obd_connect_data *data, void *localdata)
static int mgs_obd_disconnect (struct obd_export *exp)
static int mgs_health_check (const struct lu_env *env, struct obd_device *obd)
static int __init mgs_init (void)
static void __exit mgs_exit (void)
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Management Server (MGS)")
MODULE_VERSION (LUSTRE_VERSION_STRING)
MODULE_LICENSE ("GPL")
module_init (mgs_init)
module_exit (mgs_exit)
Variables
static struct tgt_handler mgs_mgs_handlers []
static struct tgt_handler mgs_obd_handlers []
static struct tgt_handler mgs_dlm_handlers []
static struct tgt_handler mgs_llog_handlers []
static struct tgt_opc_slice mgs_common_slice []
static struct lu_object_operations mgs_lu_obj_ops
struct lu_device_operations mgs_lu_ops
static struct
lu_device_type_operations mgs_device_type_ops
static struct lu_device_type mgs_device_type
static struct obd_ops mgs_obd_device_ops
Define Documentation
#define D_MGS D_CONFIG
Definition at line 44 of file mgs_handler.c.
Referenced by lprocfs_ir_set_state(), mgs_check_failnid(), mgs_erase_logs(), mgs_find_or_make_fsdb(), mgs_fsdb_handler(), mgs_get_ir_logs(), mgs_ir_notify(), mgs_ir_notify_complete(), mgs_ir_update(), mgs_modify(), mgs_modify_handler(), mgs_nidtbl_init_fs(), mgs_nidtbl_read(), mgs_parse_devname(), mgs_replace_handler(), mgs_replace_nids_log(), mgs_set_index(), mgs_setparam(), mgs_steal_llog_for_mdt_from_client(), mgs_target_reg(), mgs_write_log_direct_all(), mgs_write_log_failnids(), mgs_write_log_lmv(), mgs_write_log_lov(), mgs_write_log_mdc_to_lmv(), mgs_write_log_mdt(), mgs_write_log_osc_to_lov(), mgs_write_log_osp_to_mdt(), mgs_write_log_ost(), mgs_write_log_param(), mgs_write_log_param2(), mgs_write_log_quota(), mgs_write_log_sys(), mgs_write_log_target(), print_lustre_cfg(), process_command(), and record_base().
#define DEBUG_SUBSYSTEM S_MGS
Definition at line 43 of file mgs_handler.c.
Enumeration Type Documentation
enum ast_type
Enumerator:
AST_CONFIG
AST_PARAMS
AST_IR
Definition at line 160 of file mgs_handler.c.
Function Documentation
LU_CONTEXT_KEY_DEFINE (mgs , LCT_MG_THREAD)
LU_KEY_INIT_FINI (mgs , struct mgs_thread_info)
LU_TYPE_INIT_FINI (mgs , & mgs_thread_key)
static int mgs_check_failover_reg (struct mgs_target_info * mti) [static]
Definition at line 316 of file mgs_handler.c.
References class_find_param(), class_parse_nid_quiet(), LCONSOLE_WARN, libcfs_nid2str(), mgs_target_info::mti_nid_count, mgs_target_info::mti_nids, mgs_target_info::mti_params, and PARAM_FAILNODE.
Referenced by mgs_target_reg().
static int mgs_check_target (const struct lu_env * env, struct mgs_device * mgs, struct mgs_target_info * mti) [static]
Definition at line 285 of file mgs_handler.c.
References ENTRY, LCONSOLE_ERROR_MSG, LDD_F_WRITECONF, mgs_check_failnid(), mgs_check_index(), mgs_target_info::mti_flags, mgs_target_info::mti_fsname, mgs_target_info::mti_svname, and RETURN.
Referenced by mgs_target_reg().
static int mgs_completion_ast_config (struct ldlm_lock * lock, __u64 flags, void * cbdata) [static]
Definition at line 209 of file mgs_handler.c.
References AST_CONFIG, and mgs_completion_ast_generic().
Referenced by mgs_revoke_lock().
static int mgs_completion_ast_generic (struct ldlm_lock * lock, __u64 flags, void * cbdata, enum ast_type type) [static]
Definition at line 166 of file mgs_handler.c.
References AST_CONFIG, AST_IR, AST_PARAMS, ENTRY, fs_db::fsdb_flags, FSDB_REVOKING_LOCK, FSDB_REVOKING_PARAMS, ldlm_lock::l_ast_data, LBUG, LCK_EX, ldlm_completion_ast(), LDLM_FL_BLOCKED_MASK, ldlm_lock2handle(), ldlm_lock_decref_and_cancel(), lock_res_and_lock(), mgs_ir_notify_complete(), RETURN, and unlock_res_and_lock().
Referenced by mgs_completion_ast_config(), mgs_completion_ast_ir(), and mgs_completion_ast_params().
static int mgs_completion_ast_ir (struct ldlm_lock * lock, __u64 flags, void * cbdata) [static]
Definition at line 221 of file mgs_handler.c.
References AST_IR, and mgs_completion_ast_generic().
Referenced by mgs_revoke_lock().
static int mgs_completion_ast_params (struct ldlm_lock * lock, __u64 flags, void * cbdata) [static]
Definition at line 215 of file mgs_handler.c.
References AST_PARAMS, and mgs_completion_ast_generic().
Referenced by mgs_revoke_lock().
static int mgs_config_read (struct tgt_session_info * tsi) [static]
Definition at line 499 of file mgs_handler.c.
References CONFIG_T_CONFIG, CONFIG_T_RECOVER, D_HA, DEBUG_REQ, ENTRY, err_serious(), mgs_config_body::mcb_type, mgs_get_ir_logs(), req_capsule_client_get(), RETURN, RMF_MGS_CONFIG_BODY, tgt_ses_req(), and tgt_session_info::tsi_pill.
static int mgs_connect (struct tgt_session_info * tsi) [static]
Definition at line 56 of file mgs_handler.c.
References CFS_FAIL_TIMEOUT, cfs_fail_val, ENTRY, lustre_msg_add_op_flags(), lustre_msg_get_conn_cnt(), MSG_CONNECT_RECONNECT, OBD_FAIL_MGS_CONNECT_NET, RETURN, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_reqmsg, tgt_connect(), and tgt_ses_req().
static int mgs_connect_to_osd (struct mgs_device * m, const char * nextdev) [static]
Definition at line 986 of file mgs_handler.c.
References CERROR, class_name2obd(), dt_device::dd_lu_dev, ENTRY, obd_export::exp_obd, GOTO, LASSERT, lu_device::ld_site, lu2dt_dev(), LUSTRE_VERSION_CODE, mgs_device::mgs_bottom, mgs_device::mgs_bottom_exp, mgs_device::mgs_dt_dev, OBD_ALLOC_PTR, obd_connect(), OBD_FREE_PTR, obd_device::obd_lu_dev, obd_device::obd_uuid, obd_connect_data::ocd_version, and RETURN.
Referenced by mgs_init0().
static int mgs_destroy_export (struct obd_export * exp) [inline, static]
Definition at line 616 of file mgs_handler.c.
References ENTRY, obd_export::exp_client_uuid, obd_export::exp_obd, ldlm_destroy_export(), mgs_client_free(), obd_device::obd_uuid, obd_uuid_equals(), RETURN, and unlikely.
static struct lu_device* mgs_device_alloc (const struct lu_env * env, struct lu_device_type * type, struct lustre_cfg * lcfg) [static, read]
Definition at line 1358 of file mgs_handler.c.
References dt_device_init(), mgs2lu_dev(), mgs_device_free(), mgs_device::mgs_dt_dev, mgs_init0(), and OBD_ALLOC_PTR.
static struct lu_device* mgs_device_fini (const struct lu_env * env, struct lu_device * d) [static, read]
Definition at line 1382 of file mgs_handler.c.
References cfs_hash_is_empty(), class_disconnect_exports(), D_ERROR, ENTRY, LASSERT, lu_device::ld_site, ldlm_namespace_free_post(), ldlm_namespace_free_prior(), LIBCFS_DEBUG_MSG_DATA_DECL, llog_cleanup(), LLOG_CONFIG_ORIG_CTXT, llog_get_context(), llog_ctxt::loc_dir, lproc_mgs_cleanup(), lu_site::ls_obj_hash, lu2mgs_dev(), lu_cdebug_printer(), lu_site_print(), lu_site_purge(), mgs_device::mgs_bottom, mgs_device::mgs_bottom_exp, mgs_cleanup_fsdb_list(), mgs_fs_cleanup(), mgs_device::mgs_health_mutex, mgs_device::mgs_lut, mgs_device::mgs_obd, mgs_params_fsdb_cleanup(), mgs_device::mgs_service, obd_disconnect(), obd_exports_barrier(), obd_device::obd_name, obd_device::obd_namespace, obd_zombie_barrier(), ping_evictor_stop(), ptlrpc_unregister_service(), RETURN, server_put_mount(), and tgt_fini().
static struct lu_device* mgs_device_free (const struct lu_env * env, struct lu_device * lu) [static, read]
Definition at line 1259 of file mgs_handler.c.
References dt_device_fini(), ENTRY, lu2mgs_dev(), mgs_device::mgs_dt_dev, OBD_FREE_PTR, and RETURN.
Referenced by mgs_device_alloc().
static int mgs_disconnect (struct tgt_session_info * tsi) [static]
Definition at line 74 of file mgs_handler.c.
References ENTRY, err_serious(), LASSERT, RETURN, tgt_disconnect(), and tgt_session_info::tsi_exp.
static int mgs_exception (struct tgt_session_info * tsi) [static]
Definition at line 88 of file mgs_handler.c.
References ENTRY, LPROC_MGS_EXCEPTION, RETURN, tgt_counter_incr(), and tgt_session_info::tsi_exp.
static void __exit mgs_exit (void) [static]
Definition at line 1569 of file mgs_handler.c.
References class_unregister_type(), and LUSTRE_MGS_NAME.
static int mgs_extract_fs_pool (char * arg, char * fsname, char * poolname) [static]
Definition at line 632 of file mgs_handler.c.
References ENTRY, and RETURN.
Referenced by mgs_iocontrol_pool().
static int mgs_health_check (const struct lu_env * env, struct obd_device * obd) [static]
Definition at line 1539 of file mgs_handler.c.
References lu2mgs_dev(), mgs_device::mgs_health_mutex, mgs_device::mgs_service, obd_device::obd_lu_dev, and ptlrpc_service_health_check().
static int __init mgs_init (void) [static]
Definition at line 1563 of file mgs_handler.c.
References class_register_type(), and LUSTRE_MGS_NAME.
static int mgs_init0 (const struct lu_env * env, struct mgs_device * mgs, struct lu_device_type * ldt, struct lustre_cfg * lcfg) [static]
Definition at line 1094 of file mgs_handler.c.
References CDEBUG, CERROR, cfs_hash_is_empty(), cfs_time_current_sec(), class_name2obd(), D_ERROR, D_INFO, dt_device::dd_lu_dev, ENTRY, GOTO, LASSERT, LCT_MG_THREAD, lu_device::ld_ops, LDLM_CB_REPLY_PORTAL, LDLM_CB_REQUEST_PORTAL, ldlm_namespace_free(), LDLM_NAMESPACE_MODEST, ldlm_namespace_new(), LDLM_NAMESPACE_SERVER, LDLM_NS_TYPE_MGT, LIBCFS_DEBUG_MSG_DATA_DECL, llog_cleanup(), LLOG_CONFIG_ORIG_CTXT, llog_ctxt_put(), llog_get_context(), llog_osd_ops, llog_setup(), llog_ctxt::loc_dir, lproc_mgs_cleanup(), lproc_mgs_setup(), lu_cdebug_printer(), lu_site_print(), lu_site_purge(), lustre_cfg_string(), LUSTRE_MGS_NAME, MGC_REPLY_PORTAL, mgs2lu_dev(), mgs__mgs_fsdb_setup(), mgs_device::mgs_bottom, mgs_device::mgs_bottom_exp, MGS_BUFSIZE, mgs_device::mgs_configs_dir, mgs_connect_to_osd(), mgs_device::mgs_dt_dev, mgs_fs_cleanup(), mgs_fs_setup(), mgs_device::mgs_health_mutex, mgs_init_fsdb_list(), mgs_device::mgs_lock, mgs_lu_ops, mgs_device::mgs_lut, MGS_MAXREPSIZE, MGS_MAXREQSIZE, mgs_device::mgs_mutex, MGS_NBUFS, MGS_NTHRS_INIT, MGS_NTHRS_MAX, mgs_device::mgs_obd, mgs_params_fsdb_cleanup(), mgs_params_fsdb_setup(), MGS_REQUEST_PORTAL, mgs_device::mgs_service, MGS_SERVICE_WATCHDOG_FACTOR, mgs_device::mgs_start_time, obd_disconnect(), OBD_FAIL_MGS_ALL_REPLY_NET, OBD_FAIL_MGS_ALL_REQUEST_NET, obd_device::obd_ldlm_client, obd_device::obd_lu_dev, obd_device::obd_name, obd_device::obd_namespace, obd_device::obd_olg, obd_device::obd_proc_entry, obd_device::obd_replayable, OBT_MAGIC, PARAMS_FILENAME, ping_evictor_start(), ptlrpc_service_conf::psc_name, ptlrpc_init_client(), ptlrpc_register_service(), RETURN, server_get_mount(), server_put_mount(), target_print_req, tgt_fini(), tgt_init(), tgt_request_handle(), and obd_device::u.
Referenced by mgs_device_alloc().
static int mgs_init_export (struct obd_export * exp) [inline, static]
Definition at line 597 of file mgs_handler.c.
References obd_export::eu_mgs_data, obd_export::exp_client_uuid, obd_export::exp_connecting, obd_export::exp_lock, obd_export::exp_obd, INIT_LIST_HEAD, ldlm_init_export(), mgs_export_data::med_clients, mgs_export_data::med_lock, obd_device::obd_uuid, obd_uuid_equals(), obd_export::u, and unlikely.
static int mgs_iocontrol (unsigned int cmd, struct obd_export * exp, int len, void * karg, void __user * uarg) [static]
Definition at line 865 of file mgs_handler.c.
References CDEBUG, CERROR, D_IOCTL, ENTRY, exp2mgs_dev(), obd_export::exp_obd, GOTO, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf2, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, obd_ioctl_data::ioc_pbuf1, obd_ioctl_data::ioc_plen1, obd_ioctl_data::ioc_type, lustre_cfg::lcfg_bufcount, LCT_MG_THREAD, LLOG_CONFIG_ORIG_CTXT, llog_ctxt_put(), llog_get_context(), llog_ioctl(), lu_env_fini(), lu_env_init(), LUSTRE_CFG_TYPE, mgs_thread_info::mgi_fsname, mgs_env_info(), mgs_iocontrol_nodemap(), mgs_iocontrol_pool(), mgs_list_logs(), mgs_device::mgs_obd, mgs_replace_nids(), mgs_setparam(), MTI_NAME_MAXLEN, OBD_ALLOC, OBD_FREE, OBD_IOC_CATLOGLIST, OBD_IOC_LLOG_CANCEL, OBD_IOC_LLOG_CHECK, OBD_IOC_LLOG_INFO, OBD_IOC_LLOG_PRINT, OBD_IOC_LLOG_REMOVE, OBD_IOC_NODEMAP, OBD_IOC_PARAM, OBD_IOC_POOL, OBD_IOC_REPLACE_NIDS, obd_device::obd_name, and RETURN.
static int mgs_iocontrol_nodemap (const struct lu_env * env, struct mgs_device * mgs, struct obd_ioctl_data * data) [static]
Definition at line 650 of file mgs_handler.c.
References CERROR, cmd, ENTRY, GOTO, obd_ioctl_data::ioc_pbuf1, obd_ioctl_data::ioc_plen1, obd_ioctl_data::ioc_type, kstrtoul(), lustre_cfg::lcfg_bufcount, lustre_cfg::lcfg_command, LCFG_NODEMAP_ACTIVATE, LCFG_NODEMAP_ADD, LCFG_NODEMAP_ADD_GIDMAP, LCFG_NODEMAP_ADD_RANGE, LCFG_NODEMAP_ADD_UIDMAP, LCFG_NODEMAP_ADMIN, LCFG_NODEMAP_DEL, LCFG_NODEMAP_DEL_GIDMAP, LCFG_NODEMAP_DEL_RANGE, LCFG_NODEMAP_DEL_UIDMAP, LCFG_NODEMAP_SQUASH_GID, LCFG_NODEMAP_SQUASH_UID, LCFG_NODEMAP_TEST_ID, LCFG_NODEMAP_TEST_NID, LCFG_NODEMAP_TRUSTED, libcfs_str2nid(), lustre_cfg_string(), LUSTRE_CFG_TYPE, LUSTRE_NODEMAP_NAME_LENGTH, mgs_nodemap_cmd(), mgs_device::mgs_obd, MIN, nodemap_activate(), NODEMAP_GID, nodemap_test_id(), nodemap_test_nid(), NODEMAP_UID, OBD_ALLOC, OBD_FREE, obd_device::obd_name, and RETURN.
Referenced by mgs_iocontrol().
static int mgs_iocontrol_pool (const struct lu_env * env, struct mgs_device * mgs, struct obd_ioctl_data * data) [static]
Definition at line 783 of file mgs_handler.c.
References CERROR, ENTRY, GOTO, obd_ioctl_data::ioc_pbuf1, obd_ioctl_data::ioc_plen1, obd_ioctl_data::ioc_type, lustre_cfg::lcfg_bufcount, lustre_cfg::lcfg_command, LCFG_POOL_ADD, LCFG_POOL_DEL, LCFG_POOL_NEW, LCFG_POOL_REM, LOV_MAXPOOLNAME, lustre_cfg_string(), LUSTRE_CFG_TYPE, mgs_thread_info::mgi_fsname, mgs_env_info(), mgs_extract_fs_pool(), mgs_device::mgs_obd, mgs_pool_cmd(), OBD_ALLOC, OBD_FREE, obd_device::obd_name, poolname, and RETURN.
Referenced by mgs_iocontrol().
static int mgs_llog_open (struct tgt_session_info * tsi) [static]
Definition at line 528 of file mgs_handler.c.
References CERROR, ENTRY, LCONSOLE_WARN, libcfs_nid2str(), mgs_thread_info::mgi_fsname, mgs_env_info(), mgs_fsc_attach(), lnet_process_id_t::nid, PARAMS_FILENAME, req_capsule_client_get(), RETURN, RMF_NAME, ptlrpc_request::rq_peer, tgt_llog_open(), tgt_name(), tgt_ses_req(), tgt_session_info::tsi_env, tgt_session_info::tsi_exp, tgt_session_info::tsi_pill, and tgt_session_info::tsi_tgt.
static int mgs_obd_connect (const struct lu_env * env, struct obd_export ** exp, struct obd_device * obd, struct obd_uuid * cluuid, struct obd_connect_data * data, void * localdata) [static]
Definition at line 1463 of file mgs_handler.c.
References class_conn2export(), class_connect(), class_disconnect(), ENTRY, obd_export::exp_connect_data, LPROC_MGS_CONNECT, LUSTRE_VERSION_CODE, MGS_CONNECT_SUPPORTED, mgs_export_stats_init(), obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_version, RETURN, and tgt_counter_incr().
static int mgs_obd_disconnect (struct obd_export * exp) [static]
Definition at line 1521 of file mgs_handler.c.
References class_export_get(), class_export_put(), ENTRY, LASSERT, LPROC_MGS_DISCONNECT, mgs_fsc_cleanup(), RETURN, and tgt_counter_incr().
static int mgs_obd_reconnect (const struct lu_env * env, struct obd_export * exp, struct obd_device * obd, struct obd_uuid * cluuid, struct obd_connect_data * data, void * localdata) [static]
Definition at line 1501 of file mgs_handler.c.
References ENTRY, obd_export::exp_connect_data, LPROC_MGS_CONNECT, LUSTRE_VERSION_CODE, MGS_CONNECT_SUPPORTED, mgs_export_stats_init(), obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_version, RETURN, and tgt_counter_incr().
static struct lu_object* mgs_object_alloc (const struct lu_env * env, const struct lu_object_header * hdr, struct lu_device * d) [static, read]
Definition at line 1326 of file mgs_handler.c.
References dt_object::do_lu, dt_object_init(), LASSERT, lu_object::lo_ops, lu_object_add_top(), lu_object_header_init(), mgs_object::mgo_header, mgs_object::mgo_obj, and OBD_ALLOC_PTR.
static void mgs_object_free (const struct lu_env * env, struct lu_object * o) [static]
Definition at line 1302 of file mgs_handler.c.
References dt_object_fini(), lu_object::lo_header, lu2mgs_obj(), lu_object_header_fini(), mgs_object::mgo_obj, and OBD_FREE_PTR.
static int mgs_object_init (const struct lu_env * env, struct lu_object * o, const struct lu_object_conf * unused) [static]
Definition at line 1278 of file mgs_handler.c.
References CDEBUG, D_INFO, dt_device::dd_lu_dev, DFID, ENTRY, lu_device::ld_ops, lu_device_operations::ldo_object_alloc, lu_object::lo_dev, lu_object::lo_header, lu2mgs_dev(), lu_object_add(), lu_object_fid(), mgs_device::mgs_bottom, and PFID.
static int mgs_object_print (const struct lu_env * env, void * cookie, lu_printer_t p, const struct lu_object * l) [static]
Definition at line 1312 of file mgs_handler.c.
References lu2mgs_obj(), and LUSTRE_MGS_NAME.
static int mgs_process_config (const struct lu_env * env, struct lu_device * dev, struct lustre_cfg * lcfg) [static]
Definition at line 1270 of file mgs_handler.c.
References LBUG.
void mgs_revoke_lock (struct mgs_device * mgs, struct fs_db * fsdb, int type)
Definition at line 227 of file mgs_handler.c.
References __u64, CERROR, CONFIG_T_CONFIG, CONFIG_T_PARAMS, CONFIG_T_RECOVER, ELDLM_OK, ENTRY, fs_db::fsdb_flags, fs_db::fsdb_name, FSDB_REVOKING_LOCK, FSDB_REVOKING_PARAMS, LASSERT, LCK_EX, ldlm_blocking_ast(), ldlm_cli_enqueue_local(), LDLM_FL_ATOMIC_CB, LDLM_PLAIN, le64_to_cpu, LPX64, LVB_T_NONE, mgc_fsname2resid(), mgs_completion_ast_config(), mgs_completion_ast_ir(), mgs_completion_ast_params(), mgs_device::mgs_obd, ldlm_res_id::name, obd_device::obd_namespace, and RETURN_EXIT.
Referenced by mgs_ir_notify(), mgs_pool_cmd(), mgs_setparam(), and mgs_target_reg().
static int mgs_set_info (struct tgt_session_info * tsi) [static]
Definition at line 102 of file mgs_handler.c.
References ENTRY, err_serious(), EXIT, exp2mgs_dev(), GOTO, LCFG_PARAM, LCONSOLE_WARN, lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), mgs_thread_info::mgi_bufs, mgs_thread_info::mgi_fsname, mgs_env_info(), mgs_send_param::mgs_param, mgs_setparam(), req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_MGS_SEND_PARAM, str_starts_with(), strnlen, tgt_name(), tgt_session_info::tsi_env, tgt_session_info::tsi_exp, tgt_session_info::tsi_pill, and tgt_session_info::tsi_tgt.
static int mgs_target_del (struct tgt_session_info * tsi) [static]
Definition at line 490 of file mgs_handler.c.
References ENTRY, LPROC_MGS_TARGET_DEL, RETURN, tgt_counter_incr(), and tgt_session_info::tsi_exp.
static int mgs_target_reg (struct tgt_session_info * tsi) [static]
Definition at line 340 of file mgs_handler.c.
References CDEBUG, CERROR, CONFIG_T_CONFIG, D_HA, D_MGS, DEBUG_REQ, dt_sync(), ENTRY, err_serious(), exp2mgs_dev(), obd_export::exp_obd, GOTO, LASSERT, LCONSOLE_WARN, LDD_F_ERROR, LDD_F_IR_CAPABLE, LDD_F_NEED_INDEX, LDD_F_NO_PRIMNODE, LDD_F_OPC_MASK, LDD_F_OPC_READY, LDD_F_OPC_REG, LDD_F_REWRITE_LDD, LDD_F_SV_TYPE_MDT, LDD_F_SV_TYPE_OST, LDD_F_UPDATE, LDD_F_UPGRADE14, LDD_F_VIRGIN, LDD_F_WRITECONF, LPROC_MGS_TARGET_REG, lu_env_refill(), mgs_device::mgs_bottom, mgs_check_failover_reg(), mgs_check_target(), mgs_erase_log(), mgs_erase_logs(), mgs_find_or_make_fsdb(), mgs_ir_update(), mgs_revoke_lock(), mgs_write_log_target(), mgs_target_info::mti_flags, mgs_target_info::mti_fsname, mgs_target_info::mti_stripe_index, mgs_target_info::mti_svname, obd_export_nid2str(), OBD_FAIL_MGS_PAUSE_TARGET_REG, OBD_FAIL_TIMEOUT, obd_device::obd_name, OCD_HAS_FLAG, req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_MGS_TARGET_INFO, tgt_counter_incr(), tgt_ses_req(), tgt_session_info::tsi_env, tgt_session_info::tsi_exp, and tgt_session_info::tsi_pill.
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Management Server (MGS)")
module_exit (mgs_exit)
module_init (mgs_init)
MODULE_LICENSE ("GPL")
MODULE_VERSION (LUSTRE_VERSION_STRING)
static bool str_starts_with (const char * str, const char * prefix) [inline, static]
Definition at line 97 of file mgs_handler.c.
Referenced by mgs_set_info().
Variable Documentation
struct tgt_opc_slice mgs_common_slice[] [static]
Initial value:
 {
        {
                .tos_opc_start = MGS_FIRST_OPC,
                .tos_opc_end   = MGS_LAST_OPC,
                .tos_hs        = mgs_mgs_handlers
        },
        {
                .tos_opc_start = OBD_FIRST_OPC,
                .tos_opc_end   = OBD_LAST_OPC,
                .tos_hs        = mgs_obd_handlers
        },
        {
                .tos_opc_start = LDLM_FIRST_OPC,
                .tos_opc_end   = LDLM_LAST_OPC,
                .tos_hs        = mgs_dlm_handlers
        },
        {
                .tos_opc_start = LLOG_FIRST_OPC,
                .tos_opc_end   = LLOG_LAST_OPC,
                .tos_hs        = mgs_llog_handlers
        },
        {
                .tos_opc_start = SEC_FIRST_OPC,
                .tos_opc_end   = SEC_LAST_OPC,
                .tos_hs        = tgt_sec_ctx_handlers
        },
        {
                .tos_hs        = NULL
        }
}
Definition at line 1063 of file mgs_handler.c.
struct lu_device_type mgs_device_type [static]
Initial value:
 {
        .ldt_tags       = LU_DEVICE_DT,
        .ldt_name       = LUSTRE_MGS_NAME,
        .ldt_ops        = &mgs_device_type_ops,
        .ldt_ctx_tags   = LCT_MG_THREAD
}
Definition at line 1456 of file mgs_handler.c.
struct lu_device_type_operations mgs_device_type_ops [static]
Initial value:
 {
        .ldto_init              = mgs_type_init,
        .ldto_fini              = mgs_type_fini,
        .ldto_start             = mgs_type_start,
        .ldto_stop              = mgs_type_stop,
        .ldto_device_alloc      = mgs_device_alloc,
        .ldto_device_free       = mgs_device_free,
        .ldto_device_fini       = mgs_device_fini
}
Definition at line 1443 of file mgs_handler.c.
struct tgt_handler mgs_dlm_handlers[] [static]
Initial value:
 {
[LDLM_ENQUEUE - LDLM_FIRST_OPC] = {
        .th_name = "LDLM_ENQUEUE",
        .th_fail_id = 0,
        .th_opc = LDLM_ENQUEUE,
        .th_flags = HABEO_CLAVIS,
        .th_act = tgt_enqueue,
        .th_fmt = &RQF_LDLM_ENQUEUE,
        .th_version = LUSTRE_DLM_VERSION,
        },
}
Definition at line 1038 of file mgs_handler.c.
struct tgt_handler mgs_llog_handlers[] [static]
Initial value:
 {
TGT_LLOG_HDL    (0,     LLOG_ORIGIN_HANDLE_CREATE,      mgs_llog_open),
TGT_LLOG_HDL    (0,     LLOG_ORIGIN_HANDLE_NEXT_BLOCK,  tgt_llog_next_block),
TGT_LLOG_HDL    (0,     LLOG_ORIGIN_HANDLE_READ_HEADER, tgt_llog_read_header),
TGT_LLOG_HDL_VAR(0,     LLOG_ORIGIN_HANDLE_CLOSE,       tgt_llog_close),
TGT_LLOG_HDL    (0,     LLOG_ORIGIN_HANDLE_PREV_BLOCK,  tgt_llog_prev_block),
}
Definition at line 1055 of file mgs_handler.c.
struct lu_object_operations mgs_lu_obj_ops [static]
Initial value:
 {
        .loo_object_init        = mgs_object_init,
        .loo_object_free        = mgs_object_free,
        .loo_object_print       = mgs_object_print,
}
Definition at line 1320 of file mgs_handler.c.
struct lu_device_operations mgs_lu_ops
Initial value:
 {
        .ldo_object_alloc       = mgs_object_alloc,
        .ldo_process_config     = mgs_process_config,
}
Definition at line 1353 of file mgs_handler.c.
Referenced by lu_device_is_mgs(), and mgs_init0().
struct tgt_handler mgs_mgs_handlers[] [static]
Initial value:
 {
TGT_RPC_HANDLER(MGS_FIRST_OPC,
                0,                      MGS_CONNECT,     mgs_connect,
                &RQF_CONNECT, LUSTRE_OBD_VERSION),
TGT_RPC_HANDLER(MGS_FIRST_OPC,
                0,                      MGS_DISCONNECT,  mgs_disconnect,
                &RQF_MDS_DISCONNECT, LUSTRE_OBD_VERSION),
TGT_MGS_HDL_VAR(0,                      MGS_EXCEPTION,   mgs_exception),
TGT_MGS_HDL    (HABEO_REFERO | MUTABOR, MGS_SET_INFO,    mgs_set_info),
TGT_MGS_HDL    (HABEO_REFERO | MUTABOR, MGS_TARGET_REG,  mgs_target_reg),
TGT_MGS_HDL_VAR(0,                      MGS_TARGET_DEL,  mgs_target_del),
TGT_MGS_HDL    (HABEO_REFERO,           MGS_CONFIG_READ, mgs_config_read),
}
Definition at line 1020 of file mgs_handler.c.
struct obd_ops mgs_obd_device_ops [static]
Initial value:
 {
        .o_owner                = THIS_MODULE,
        .o_connect              = mgs_obd_connect,
        .o_reconnect            = mgs_obd_reconnect,
        .o_disconnect           = mgs_obd_disconnect,
        .o_init_export          = mgs_init_export,
        .o_destroy_export       = mgs_destroy_export,
        .o_iocontrol            = mgs_iocontrol,
        .o_health_check         = mgs_health_check,
}
Definition at line 1552 of file mgs_handler.c.
struct tgt_handler mgs_obd_handlers[] [static]
Initial value:
 {
TGT_OBD_HDL(0,  OBD_PING,       tgt_obd_ping),
}
Definition at line 1034 of file mgs_handler.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.