Lustre: lustre/mgs/mgs_nids.c File Reference
lustre/mgs/mgs_nids.c File Reference
#include <linux/kthread.h>
#include <linux/pagemap.h>
#include <obd.h>
#include <obd_class.h>
#include <lustre_disk.h>
#include "mgs_internal.h"
Data Structures
struct lproc_ir_cmd
Defines
#define DEBUG_SUBSYSTEM S_MGS
#define D_MGS D_CONFIG
#define MGS_NIDTBL_VERSION_INIT 2
Enumerations
enum { IR_CLIENT = 1, IR_MDT = 2 }
Functions
static int nidtbl_is_sane (struct mgs_nidtbl *tbl)
static int mgs_nidtbl_read (struct obd_export *exp, struct mgs_nidtbl *tbl, struct mgs_config_res *res, struct page **pages, int nrpages, int units_total, int unit_size)
Fetch nidtbl entries whose version are not less than.
static int nidtbl_update_version (const struct lu_env *env, struct mgs_device *mgs, struct mgs_nidtbl *tbl)
static int nidtbl_read_version (const struct lu_env *env, struct mgs_device *mgs, struct mgs_nidtbl *tbl, u64 *version)
static int mgs_nidtbl_write (const struct lu_env *env, struct fs_db *fsdb, struct mgs_target_info *mti)
static void mgs_nidtbl_fini_fs (struct fs_db *fsdb)
static int mgs_nidtbl_init_fs (const struct lu_env *env, struct fs_db *fsdb)
void mgs_ir_notify_complete (struct fs_db *fsdb)
static int mgs_ir_notify (void *arg)
int mgs_ir_init_fs (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb)
void mgs_ir_fini_fs (struct mgs_device *mgs, struct fs_db *fsdb)
static void ir_state_graduate (struct fs_db *fsdb)
int mgs_ir_update (const struct lu_env *env, struct mgs_device *mgs, struct mgs_target_info *mti)
static int delogname (char *logname, char *fsname, int *typ)
int mgs_get_ir_logs (struct ptlrpc_request *req)
static int lprocfs_ir_set_state (struct fs_db *fsdb, const char *buf)
static int lprocfs_ir_set_timeout (struct fs_db *fsdb, const char *buf)
static int lprocfs_ir_clear_stats (struct fs_db *fsdb, const char *buf)
int lprocfs_wr_ir_state (struct file *file, const char __user *buffer, size_t count, void *data)
int lprocfs_rd_ir_state (struct seq_file *seq, void *data)
int lprocfs_ir_timeout_seq_show (struct seq_file *m, void *data)
ssize_t lprocfs_ir_timeout_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
int mgs_fsc_attach (const struct lu_env *env, struct obd_export *exp, char *fsname)
void mgs_fsc_cleanup (struct obd_export *exp)
void mgs_fsc_cleanup_by_fsdb (struct fs_db *fsdb)
Variables
static unsigned int ir_timeout
static struct lproc_ir_cmd ir_cmds []
Define Documentation
#define D_MGS D_CONFIG
Definition at line 44 of file mgs_nids.c.
#define DEBUG_SUBSYSTEM S_MGS
Definition at line 43 of file mgs_nids.c.
#define MGS_NIDTBL_VERSION_INIT 2
Definition at line 258 of file mgs_nids.c.
Referenced by nidtbl_read_version().
Enumeration Type Documentation
anonymous enum
Enumerator:
IR_CLIENT
IR_MDT
Definition at line 562 of file mgs_nids.c.
Function Documentation
static int delogname (char * logname, char * fsname, int * typ) [static]
Definition at line 567 of file mgs_nids.c.
References IR_CLIENT, and IR_MDT.
Referenced by mgs_get_ir_logs().
static void ir_state_graduate (struct fs_db * fsdb) [inline, static]
Definition at line 504 of file mgs_nids.c.
References cfs_time_before(), cfs_time_current_sec(), fs_db::fsdb_ir_state, fs_db::fsdb_mgs, fs_db::fsdb_nonir_clients, IR_FULL, IR_PARTIAL, IR_STARTUP, ir_timeout, and mgs_device::mgs_start_time.
Referenced by lprocfs_rd_ir_state(), and mgs_ir_update().
static int lprocfs_ir_clear_stats (struct fs_db * fsdb, const char * buf) [static]
Definition at line 719 of file mgs_nids.c.
References fs_db::fsdb_notify_count, fs_db::fsdb_notify_max, and fs_db::fsdb_notify_total.
static int lprocfs_ir_set_state (struct fs_db * fsdb, const char * buf) [static]
Definition at line 688 of file mgs_nids.c.
References ARRAY_SIZE, CDEBUG, D_MGS, fs_db::fsdb_ir_state, fs_db::fsdb_mutex, fs_db::fsdb_name, fs_db::fsdb_nonir_clients, IR_FULL, IR_PARTIAL, IR_STRINGS, and state.
static int lprocfs_ir_set_timeout (struct fs_db * fsdb, const char * buf) [static]
Definition at line 714 of file mgs_nids.c.
int lprocfs_ir_timeout_seq_show (struct seq_file * m, void * data)
Definition at line 830 of file mgs_nids.c.
References ir_timeout.
ssize_t lprocfs_ir_timeout_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off)
Definition at line 835 of file mgs_nids.c.
References ir_timeout.
int lprocfs_rd_ir_state (struct seq_file * seq, void * data)
Definition at line 798 of file mgs_nids.c.
References cfs_duration_usec(), fs_db::fsdb_ir_state, fs_db::fsdb_nidtbl, fs_db::fsdb_nonir_clients, fs_db::fsdb_notify_count, fs_db::fsdb_notify_max, fs_db::fsdb_notify_total, ir_state_graduate(), IR_STRINGS, and mgs_nidtbl::mn_version.
int lprocfs_wr_ir_state (struct file * file, const char __user * buffer, size_t count, void * data)
Definition at line 740 of file mgs_nids.c.
References ARRAY_SIZE, CERROR, cmd, lproc_ir_cmd::handler, ir_cmds, lproc_ir_cmd::name, lproc_ir_cmd::namelen, OBD_ALLOC, and OBD_FREE.
int mgs_fsc_attach (const struct lu_env * env, struct obd_export * exp, char * fsname)
Definition at line 844 of file mgs_nids.c.
References class_export_get(), class_export_put(), ENTRY, obd_export::eu_mgs_data, exp2mgs_dev(), exp_connect_flags(), fs_db::fsdb_clients, fs_db::fsdb_ir_state, fs_db::fsdb_mutex, fs_db::fsdb_name, fs_db::fsdb_nonir_clients, INIT_LIST_HEAD, IR_FULL, IR_PARTIAL, list_add(), list_for_each_entry, mgs_export_data::med_clients, mgs_export_data::med_lock, mgs_fsc::mfc_export, mgs_fsc::mfc_export_list, mgs_fsc::mfc_fsdb, mgs_fsc::mfc_fsdb_list, mgs_fsc::mfc_ir_capable, mgs_find_or_make_fsdb(), OBD_ALLOC_PTR, OBD_CONNECT_IMP_RECOV, OBD_FREE_PTR, RETURN, and obd_export::u.
Referenced by mgs_llog_open().
void mgs_fsc_cleanup (struct obd_export * exp)
Definition at line 909 of file mgs_nids.c.
References class_export_put(), obd_export::eu_mgs_data, fs_db::fsdb_ir_state, fs_db::fsdb_mutex, fs_db::fsdb_nonir_clients, IR_FULL, IR_PARTIAL, LASSERT, list_del_init(), list_for_each_entry_safe, LIST_HEAD_INIT, list_splice_init(), mgs_export_data::med_clients, mgs_export_data::med_lock, mgs_fsc::mfc_export, mgs_fsc::mfc_export_list, mgs_fsc::mfc_fsdb, mgs_fsc::mfc_fsdb_list, mgs_fsc::mfc_ir_capable, OBD_FREE_PTR, and obd_export::u.
Referenced by mgs_obd_disconnect().
void mgs_fsc_cleanup_by_fsdb (struct fs_db * fsdb)
Definition at line 941 of file mgs_nids.c.
References class_export_put(), obd_export::eu_mgs_data, fs_db::fsdb_clients, fs_db::fsdb_ir_state, fs_db::fsdb_nonir_clients, IR_FULL, IR_PARTIAL, LASSERT, list_del_init(), list_for_each_entry_safe, mgs_export_data::med_lock, mgs_fsc::mfc_export, mgs_fsc::mfc_export_list, mgs_fsc::mfc_fsdb, mgs_fsc::mfc_fsdb_list, OBD_FREE_PTR, and obd_export::u.
Referenced by mgs_ir_fini_fs().
int mgs_get_ir_logs (struct ptlrpc_request * req)
Definition at line 598 of file mgs_nids.c.
References ptlrpc_bulk_frag_ops::add_kiov_frag, ptlrpc_bulk_desc::bd_frag_ops, bufsize, CDEBUG, CONFIG_T_RECOVER, D_MGS, delogname(), ENTRY, exp2mgs_dev(), fs_db::fsdb_nidtbl, GOTO, LASSERT, mgs_config_body::mcb_bits, mgs_config_body::mcb_name, mgs_config_body::mcb_offset, mgs_config_body::mcb_type, mgs_config_body::mcb_units, mgs_config_res::mcr_offset, MGS_BULK_PORTAL, mgs_find_or_make_fsdb(), mgs_nidtbl_read(), min_t, OBD_ALLOC, OBD_FREE, PTLRPC_BULK_BUF_KIOV, ptlrpc_bulk_kiov_pin_ops, PTLRPC_BULK_PUT_SOURCE, ptlrpc_free_bulk(), PTLRPC_MAX_BRW_PAGES, req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_MGS_CONFIG_BODY, RMF_MGS_CONFIG_RES, ptlrpc_request::rq_export, and ptlrpc_request::rq_pill.
Referenced by mgs_config_read().
void mgs_ir_fini_fs (struct mgs_device * mgs, struct fs_db * fsdb)
Definition at line 487 of file mgs_nids.c.
References fs_db::fsdb_clients, fs_db::fsdb_flags, FSDB_MGS_SELF, fs_db::fsdb_notify_comp, fs_db::fsdb_notify_stop, fs_db::fsdb_notify_waitq, LASSERT, list_empty(), mgs_fsc_cleanup_by_fsdb(), and mgs_nidtbl_fini_fs().
Referenced by mgs_free_fsdb().
int mgs_ir_init_fs (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb)
Definition at line 455 of file mgs_nids.c.
References CERROR, cfs_time_before(), cfs_time_current_sec(), fs_db::fsdb_clients, fs_db::fsdb_ir_state, fs_db::fsdb_mgs, fs_db::fsdb_name, fs_db::fsdb_nonir_clients, fs_db::fsdb_notify_comp, fs_db::fsdb_notify_phase, fs_db::fsdb_notify_waitq, INIT_LIST_HEAD, IR_FULL, IR_STARTUP, ir_timeout, mgs_ir_notify(), mgs_nidtbl_init_fs(), mgs_device::mgs_start_time, and OBD_IR_MGS_TIMEOUT.
Referenced by mgs_new_fsdb().
static int mgs_ir_notify (void * arg) [static]
Definition at line 419 of file mgs_nids.c.
References CDEBUG, cfs_time_current(), CONFIG_T_RECOVER, D_MGS, fs_db::fsdb_mgs, fs_db::fsdb_name, fs_db::fsdb_notify_comp, fs_db::fsdb_notify_phase, fs_db::fsdb_notify_start, fs_db::fsdb_notify_stop, fs_db::fsdb_notify_waitq, l_wait_event, LASSERTF, mgc_fsname2resid(), mgs_revoke_lock(), and name.
Referenced by mgs_ir_init_fs().
void mgs_ir_notify_complete (struct fs_db * fsdb)
Definition at line 400 of file mgs_nids.c.
References CDEBUG, cfs_duration_usec(), cfs_time_current(), cfs_time_sub(), D_MGS, fs_db::fsdb_name, fs_db::fsdb_notify_count, fs_db::fsdb_notify_max, fs_db::fsdb_notify_phase, fs_db::fsdb_notify_start, and fs_db::fsdb_notify_total.
Referenced by mgs_completion_ast_generic().
int mgs_ir_update (const struct lu_env * env, struct mgs_device * mgs, struct mgs_target_info * mti)
Definition at line 516 of file mgs_nids.c.
References CDEBUG, D_MGS, ergo, fs_db::fsdb_ir_state, fs_db::fsdb_mutex, fs_db::fsdb_name, fs_db::fsdb_notify_phase, fs_db::fsdb_notify_waitq, IR_DISABLED, IR_FULL, IR_PARTIAL, IR_STARTUP, ir_state_graduate(), LASSERT, LBUG, LDD_F_IR_CAPABLE, mgs_find_or_make_fsdb(), mgs_nidtbl_write(), mgs_target_info::mti_flags, mgs_target_info::mti_fsname, and mgs_target_info::mti_instance.
Referenced by mgs_target_reg().
static void mgs_nidtbl_fini_fs (struct fs_db * fsdb) [static]
Definition at line 359 of file mgs_nids.c.
References fs_db::fsdb_nidtbl, list_del(), list_empty(), list_entry, LIST_HEAD_INIT, list_splice_init(), mgs_nidtbl::mn_lock, mgs_nidtbl::mn_nr_targets, mgs_nidtbl::mn_targets, mgs_nidtbl_target::mnt_list, list_head::next, and OBD_FREE_PTR.
Referenced by mgs_ir_fini_fs().
static int mgs_nidtbl_init_fs (const struct lu_env * env, struct fs_db * fsdb) [static]
Definition at line 377 of file mgs_nids.c.
References CDEBUG, CERROR, D_MGS, fs_db::fsdb_mgs, fs_db::fsdb_nidtbl, INIT_LIST_HEAD, mgs_device::mgs_obd, mgs_nidtbl::mn_fsdb, mgs_nidtbl::mn_lock, mgs_nidtbl::mn_nr_targets, mgs_nidtbl::mn_targets, mgs_nidtbl::mn_version, nidtbl_read_version(), and obd_device::obd_name.
Referenced by mgs_ir_init_fs().
static int mgs_nidtbl_read (struct obd_export * exp, struct mgs_nidtbl * tbl, struct mgs_config_res * res, struct page ** pages, int nrpages, int units_total, int unit_size) [static]
Fetch nidtbl entries whose version are not less than.
Version:
nidtbl entries will be packed in by units - entries shouldn't cross unit boundaries.
Definition at line 80 of file mgs_nids.c.
References __u64, buf, CDEBUG, CWARN, D_MGS, ENTRY, ergo, fs_db::fsdb_name, GOTO, LASSERT, list_for_each_entry, mgs_config_res::mcr_offset, mgs_config_res::mcr_size, mgs_nidtbl::mn_fsdb, mgs_nidtbl::mn_lock, mgs_nidtbl::mn_targets, mgs_nidtbl::mn_version, mgs_nidtbl_entry::mne_index, mgs_nidtbl_entry::mne_instance, mgs_nidtbl_entry::mne_length, mgs_nidtbl_entry::mne_nid_count, mgs_nidtbl_entry::mne_nid_size, mgs_nidtbl_entry::mne_nid_type, mgs_nidtbl_entry::mne_type, mgs_nidtbl_entry::mne_version, mgs_nidtbl_target::mnt_mti, mgs_nidtbl_target::mnt_type, mgs_nidtbl_target::mnt_version, mgs_target_info::mti_instance, mgs_target_info::mti_nid_count, mgs_target_info::mti_nids, MTI_NIDS_MAX, mgs_target_info::mti_stripe_index, mgs_nidtbl_entry::nids, nidtbl_is_sane(), RETURN, mgs_nidtbl_entry::u, and version.
Referenced by mgs_get_ir_logs().
static int mgs_nidtbl_write (const struct lu_env * env, struct fs_db * fsdb, struct mgs_target_info * mti) [static]
Definition at line 306 of file mgs_nids.c.
References CERROR, ENTRY, EXIT, fs_db::fsdb_mgs, fs_db::fsdb_name, fs_db::fsdb_nidtbl, GOTO, INIT_LIST_HEAD, LASSERT, LDD_F_SV_TYPE_MASK, LDD_F_SV_TYPE_MGS, list_for_each_entry, list_move_tail(), mgs_nidtbl::mn_lock, mgs_nidtbl::mn_nr_targets, mgs_nidtbl::mn_targets, mgs_nidtbl::mn_version, mgs_nidtbl_target::mnt_fs, mgs_nidtbl_target::mnt_list, mgs_nidtbl_target::mnt_mti, mgs_nidtbl_target::mnt_type, mgs_nidtbl_target::mnt_version, mgs_target_info::mti_flags, mgs_target_info::mti_stripe_index, nidtbl_update_version(), and OBD_ALLOC_PTR.
Referenced by mgs_ir_update().
static int nidtbl_is_sane (struct mgs_nidtbl * tbl) [static]
Definition at line 57 of file mgs_nids.c.
References LASSERT, list_for_each_entry, mgs_nidtbl::mn_lock, mgs_nidtbl::mn_targets, mgs_nidtbl_target::mnt_list, mgs_nidtbl_target::mnt_version, and version.
Referenced by mgs_nidtbl_read().
static int nidtbl_read_version (const struct lu_env * env, struct mgs_device * mgs, struct mgs_nidtbl * tbl, u64 * version) [static]
Definition at line 260 of file mgs_nids.c.
References CERROR, dt_device::dd_lu_dev, dt_object::do_lu, dt_locate_at(), dt_lookup_dir(), dt_read(), ENTRY, fs_db::fsdb_name, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, le64_to_cpu, lu_object_put(), mgs_device::mgs_bottom, mgs_device::mgs_dt_dev, mgs_device::mgs_nidtbl_dir, MGS_NIDTBL_VERSION_INIT, mgs_device::mgs_obd, mgs_nidtbl::mn_fsdb, mgs_nidtbl::mn_lock, obd_device::obd_name, and RETURN.
Referenced by mgs_nidtbl_init_fs().
static int nidtbl_update_version (const struct lu_env * env, struct mgs_device * mgs, struct mgs_nidtbl * tbl) [static]
Definition at line 212 of file mgs_nids.c.
References cpu_to_le64, dt_object::do_lu, dt_declare_record_write(), dt_record_write(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), ENTRY, fs_db::fsdb_name, GOTO, LASSERT, lu_buf::lb_buf, local_file_find_or_create(), lu_object_put(), mgs_device::mgs_bottom, mgs_device::mgs_los, mgs_device::mgs_nidtbl_dir, mgs_nidtbl::mn_fsdb, mgs_nidtbl::mn_lock, mgs_nidtbl::mn_version, RETURN, thandle::th_sync, and version.
Referenced by mgs_nidtbl_write().
Variable Documentation
struct lproc_ir_cmd ir_cmds[] [static]
Referenced by lprocfs_wr_ir_state().
unsigned int ir_timeout [static]
Definition at line 55 of file mgs_nids.c.
Referenced by ir_state_graduate(), lprocfs_ir_timeout_seq_show(), lprocfs_ir_timeout_seq_write(), and mgs_ir_init_fs().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.