Lustre: lustre/mgs/mgs_internal.h File Reference
lustre/mgs/mgs_internal.h File Reference
#include <libcfs/libcfs.h>
#include <lustre_log.h>
#include <lustre_export.h>
#include <lustre_nodemap.h>
#include <dt_object.h>
Data Structures
struct mgs_nidtbl_target
struct mgs_fsc
maintain fs client nodes of mgs.
struct mgs_nidtbl
struct mgs_tgt_srpc_conf
struct fs_db
struct mgs_device
struct mgs_object
struct temp_comp
struct mgs_thread_info
struct mgs_direntry
Defines
#define MGSSELF_NAME "_mgs"
#define MGS_SERVICE_WATCHDOG_FACTOR 2
#define IR_STRINGS { "full", "startup", "disabled", "partial" }
#define INDEX_MAP_SIZE 8192
#define FSDB_LOG_EMPTY (0)
#define FSDB_OLDLOG14 (1)
#define FSDB_REVOKING_LOCK (2)
#define FSDB_MGS_SELF (3)
#define FSDB_OSCNAME18 (4)
#define FSDB_UDESC (5)
#define FSDB_REVOKING_PARAMS (6)
Enumerations
enum { IR_FULL = 0, IR_STARTUP, IR_DISABLED, IR_PARTIAL }
enum {
LPROC_MGS_CONNECT = 0, LPROC_MGS_DISCONNECT, LPROC_MGS_EXCEPTION, LPROC_MGS_TARGET_REG,
LPROC_MGS_TARGET_DEL, LPROC_MGS_LAST
}
Functions
int mgs_init_fsdb_list (struct mgs_device *mgs)
int mgs_cleanup_fsdb_list (struct mgs_device *mgs)
int mgs__mgs_fsdb_setup (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb)
int mgs_params_fsdb_setup (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb)
int mgs_params_fsdb_cleanup (const struct lu_env *env, struct mgs_device *mgs)
int mgs_find_or_make_fsdb (const struct lu_env *env, struct mgs_device *mgs, char *name, struct fs_db **dbh)
struct fs_db * mgs_find_fsdb (struct mgs_device *mgs, char *fsname)
int mgs_get_fsdb_srpc_from_llog (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb)
int mgs_check_index (const struct lu_env *env, struct mgs_device *mgs, struct mgs_target_info *mti)
int mgs_check_failnid (const struct lu_env *env, struct mgs_device *mgs, struct mgs_target_info *mti)
int mgs_write_log_target (const struct lu_env *env, struct mgs_device *mgs, struct mgs_target_info *mti, struct fs_db *fsdb)
int mgs_replace_nids (const struct lu_env *env, struct mgs_device *mgs, char *devname, char *nids)
Replace nids for device to nids values.
int mgs_erase_log (const struct lu_env *env, struct mgs_device *mgs, char *name)
int mgs_erase_logs (const struct lu_env *env, struct mgs_device *mgs, char *fsname)
int mgs_setparam (const struct lu_env *env, struct mgs_device *mgs, struct lustre_cfg *lcfg, char *fsname)
int mgs_list_logs (const struct lu_env *env, struct mgs_device *mgs, struct obd_ioctl_data *data)
int mgs_pool_cmd (const struct lu_env *env, struct mgs_device *mgs, enum lcfg_command_type cmd, char *poolname, char *fsname, char *ostname)
int mgs_nodemap_cmd (const struct lu_env *env, struct mgs_device *mgs, enum lcfg_command_type cmd, const char *nodemap_name, char *param)
int mgs_get_lock (struct obd_device *obd, struct ldlm_res_id *res, struct lustre_handle *lockh)
int mgs_put_lock (struct lustre_handle *lockh)
void mgs_revoke_lock (struct mgs_device *mgs, struct fs_db *fsdb, int type)
int mgs_ir_update (const struct lu_env *env, struct mgs_device *mgs, struct mgs_target_info *mti)
int mgs_ir_init_fs (const struct lu_env *env, struct mgs_device *mgs, struct fs_db *fsdb)
void mgs_ir_fini_fs (struct mgs_device *mgs, struct fs_db *fsdb)
void mgs_ir_notify_complete (struct fs_db *fsdb)
int mgs_get_ir_logs (struct ptlrpc_request *req)
int lprocfs_wr_ir_state (struct file *file, const char __user *buffer, size_t count, void *data)
int lprocfs_rd_ir_state (struct seq_file *seq, void *data)
ssize_t lprocfs_ir_timeout_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
int lprocfs_ir_timeout_seq_show (struct seq_file *seq, void *data)
void mgs_fsc_cleanup (struct obd_export *exp)
void mgs_fsc_cleanup_by_fsdb (struct fs_db *fsdb)
int mgs_fsc_attach (const struct lu_env *env, struct obd_export *exp, char *fsname)
int mgs_export_stats_init (struct obd_device *obd, struct obd_export *exp, void *localdata)
Initialize MGS per-export statistics.
int mgs_client_free (struct obd_export *exp)
int mgs_fs_setup (const struct lu_env *env, struct mgs_device *m)
int mgs_fs_cleanup (const struct lu_env *env, struct mgs_device *m)
static int lproc_mgs_setup (struct mgs_device *mgs, const char *osd_name)
static void lproc_mgs_cleanup (struct mgs_device *mgs)
static int lproc_mgs_add_live (struct mgs_device *mgs, struct fs_db *fsdb)
static int lproc_mgs_del_live (struct mgs_device *mgs, struct fs_db *fsdb)
void mgs_counter_incr (struct obd_export *exp, int opcode)
void mgs_stats_counter_init (struct lprocfs_stats *stats)
static struct mgs_thread_info * mgs_env_info (const struct lu_env *env)
static int lu_device_is_mgs (struct lu_device *d)
static struct mgs_device * lu2mgs_dev (struct lu_device *d)
static struct mgs_device * exp2mgs_dev (struct obd_export *exp)
static struct lu_device * mgs2lu_dev (struct mgs_device *d)
static struct mgs_device * dt2mgs_dev (struct dt_device *d)
static struct mgs_object * lu2mgs_obj (struct lu_object *o)
static struct lu_object * mgs2lu_obj (struct mgs_object *obj)
static struct mgs_object * mgs_obj (const struct lu_object *o)
static struct mgs_object * dt2mgs_obj (const struct dt_object *d)
static struct dt_object * mgs_object_child (struct mgs_object *o)
static void mgs_direntry_free (struct mgs_direntry *de)
static struct mgs_direntry * mgs_direntry_alloc (int len)
int class_dentry_readdir (const struct lu_env *env, struct mgs_device *mgs, struct list_head *list)
Variables
struct lu_context_key mgs_thread_key
struct lu_device_operations mgs_lu_ops
Define Documentation
#define FSDB_LOG_EMPTY (0)
Definition at line 115 of file mgs_internal.h.
Referenced by mgs_check_index(), mgs_get_fsdb_from_llog(), mgs_pool_cmd(), mgs_set_index(), and mgs_setparam().
#define FSDB_MGS_SELF (3)
Definition at line 118 of file mgs_internal.h.
Referenced by mgs_find_or_make_fsdb(), mgs_ir_fini_fs(), mgs_new_fsdb(), mgs_setparam(), mgs_srpc_set_param(), and mgs_srpc_set_param_mem().
#define FSDB_OLDLOG14 (1)
Definition at line 116 of file mgs_internal.h.
Referenced by mgs_write_log_ost(), and mgs_write_log_param().
#define FSDB_OSCNAME18 (4)
Definition at line 119 of file mgs_internal.h.
Referenced by mgs_fsdb_handler(), mgs_write_log_osc_to_lov(), name_create_lov(), name_create_mdt_and_lov(), and name_create_mdt_osc().
#define FSDB_REVOKING_LOCK (2)
Definition at line 117 of file mgs_internal.h.
Referenced by mgs_completion_ast_generic(), and mgs_revoke_lock().
#define FSDB_REVOKING_PARAMS (6)
Definition at line 121 of file mgs_internal.h.
Referenced by mgs_completion_ast_generic(), and mgs_revoke_lock().
#define FSDB_UDESC (5)
Definition at line 120 of file mgs_internal.h.
Referenced by mgs_new_fsdb(), and mgs_srpc_set_param_udesc_mem().
#define INDEX_MAP_SIZE 8192
Definition at line 113 of file mgs_internal.h.
Referenced by mgs_free_fsdb(), mgs_new_fsdb(), mgs_pool_cmd(), mgs_replace_nids(), mgs_set_index(), mgs_write_log_add_failnid(), mgs_write_log_mdt(), mgs_write_log_ost(), and mgs_write_log_param().
#define IR_STRINGS { "full", "startup", "disabled", "partial" }
Definition at line 71 of file mgs_internal.h.
Referenced by lprocfs_ir_set_state(), and lprocfs_rd_ir_state().
#define MGS_SERVICE_WATCHDOG_FACTOR 2
Definition at line 48 of file mgs_internal.h.
Referenced by mgs_init0().
#define MGSSELF_NAME "_mgs"
Definition at line 46 of file mgs_internal.h.
Referenced by mgs__mgs_fsdb_setup(), mgs_new_fsdb(), and mgs_srpc_set_param_mem().
Enumeration Type Documentation
anonymous enum
Enumerator:
IR_FULL
IR_STARTUP
IR_DISABLED
IR_PARTIAL
Definition at line 64 of file mgs_internal.h.
anonymous enum
Enumerator:
LPROC_MGS_CONNECT
LPROC_MGS_DISCONNECT
LPROC_MGS_EXCEPTION
LPROC_MGS_TARGET_REG
LPROC_MGS_TARGET_DEL
LPROC_MGS_LAST
Definition at line 275 of file mgs_internal.h.
Function Documentation
int class_dentry_readdir (const struct lu_env * env, struct mgs_device * mgs, struct list_head * list)
Definition at line 59 of file mgs_llog.c.
References CERROR, dt_index_operations::dio_it, dir, dt_object::do_index_ops, GOTO, dt_index_operations::dt_it_ops::init, INIT_LIST_HEAD, LASSERT, list_add(), LUDA_64BITHASH, mgs_direntry::mde_list, mgs_direntry::mde_name, mgs_device::mgs_configs_dir, mgs_direntry_alloc(), mgs_device::mgs_obd, MOUNT_CONFIGS_DIR, obd_device::obd_name, and RETURN.
Referenced by mgs_erase_logs(), mgs_list_logs(), and mgs_write_log_direct_all().
static struct mgs_device* dt2mgs_dev (struct dt_device * d) [static, read]
Definition at line 341 of file mgs_internal.h.
References dt_device::dd_lu_dev, LASSERT, lu_device_is_mgs(), and mgs_device::mgs_dt_dev.
static struct mgs_object* dt2mgs_obj (const struct dt_object * d) [static, read]
Definition at line 364 of file mgs_internal.h.
References dt_object::do_lu, and mgs_obj().
static struct mgs_device* exp2mgs_dev (struct obd_export * exp) [static, read]
Definition at line 331 of file mgs_internal.h.
References obd_export::exp_obd, lu2mgs_dev(), and obd_device::obd_lu_dev.
Referenced by mgs_fsc_attach(), mgs_get_ir_logs(), mgs_iocontrol(), mgs_set_info(), and mgs_target_reg().
static int lproc_mgs_add_live (struct mgs_device * mgs, struct fs_db * fsdb) [inline, static]
Definition at line 268 of file mgs_internal.h.
Referenced by mgs_new_fsdb().
static void lproc_mgs_cleanup (struct mgs_device * mgs) [inline, static]
Definition at line 266 of file mgs_internal.h.
Referenced by mgs_device_fini(), and mgs_init0().
static int lproc_mgs_del_live (struct mgs_device * mgs, struct fs_db * fsdb) [inline, static]
Definition at line 270 of file mgs_internal.h.
Referenced by mgs_free_fsdb().
static int lproc_mgs_setup (struct mgs_device * mgs, const char * osd_name) [inline, static]
Definition at line 264 of file mgs_internal.h.
Referenced by mgs_init0().
int lprocfs_ir_timeout_seq_show (struct seq_file * seq, void * data)
Definition at line 830 of file mgs_nids.c.
References ir_timeout.
ssize_t lprocfs_ir_timeout_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off)
Definition at line 835 of file mgs_nids.c.
References ir_timeout.
int lprocfs_rd_ir_state (struct seq_file * seq, void * data)
Definition at line 798 of file mgs_nids.c.
References cfs_duration_usec(), fs_db::fsdb_ir_state, fs_db::fsdb_nidtbl, fs_db::fsdb_nonir_clients, fs_db::fsdb_notify_count, fs_db::fsdb_notify_max, fs_db::fsdb_notify_total, ir_state_graduate(), IR_STRINGS, and mgs_nidtbl::mn_version.
int lprocfs_wr_ir_state (struct file * file, const char __user * buffer, size_t count, void * data)
Definition at line 740 of file mgs_nids.c.
References ARRAY_SIZE, CERROR, cmd, lproc_ir_cmd::handler, ir_cmds, lproc_ir_cmd::name, lproc_ir_cmd::namelen, OBD_ALLOC, and OBD_FREE.
static struct mgs_device* lu2mgs_dev (struct lu_device * d) [static, read]
Definition at line 325 of file mgs_internal.h.
References dt_device::dd_lu_dev, LASSERT, lu_device_is_mgs(), and mgs_device::mgs_dt_dev.
Referenced by exp2mgs_dev(), mgs_device_fini(), mgs_device_free(), mgs_health_check(), mgs_object_init(), mgs_replace_nids_log(), and mgs_steal_client_llog_handler().
static struct mgs_object* lu2mgs_obj (struct lu_object * o) [static, read]
Definition at line 347 of file mgs_internal.h.
References dt_object::do_lu, ergo, LASSERT, lu_object::lo_dev, lu_device_is_mgs(), and mgs_object::mgo_obj.
Referenced by mgs_object_free(), and mgs_object_print().
static int lu_device_is_mgs (struct lu_device * d) [inline, static]
Definition at line 320 of file mgs_internal.h.
References ergo, lu_device::ld_ops, and mgs_lu_ops.
Referenced by dt2mgs_dev(), lu2mgs_dev(), lu2mgs_obj(), and mgs_obj().
static struct lu_device* mgs2lu_dev (struct mgs_device * d) [static, read]
Definition at line 336 of file mgs_internal.h.
References dt_device::dd_lu_dev, and mgs_device::mgs_dt_dev.
Referenced by mgs_device_alloc(), and mgs_init0().
static struct lu_object* mgs2lu_obj (struct mgs_object * obj) [static, read]
Definition at line 353 of file mgs_internal.h.
References dt_object::do_lu, and mgs_object::mgo_obj.
Referenced by mgs_object_child().
int mgs__mgs_fsdb_setup (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb)
Definition at line 3927 of file mgs_llog.c.
References ENTRY, mgs_find_or_make_fsdb(), MGSSELF_NAME, and RETURN.
Referenced by mgs_init0().
int mgs_check_failnid (const struct lu_env * env, struct mgs_device * mgs, struct mgs_target_info * mti)
Definition at line 3690 of file mgs_llog.c.
References buf, CDEBUG, D_MGS, ENTRY, fs_db::fsdb_mutex, mgs_find_or_make_fsdb(), mgs_log_is_empty(), mgs_write_log_add_failnid(), mgs_target_info::mti_svname, and RETURN.
Referenced by mgs_check_target().
int mgs_check_index (const struct lu_env * env, struct mgs_device * mgs, struct mgs_target_info * mti)
Definition at line 483 of file mgs_llog.c.
References CERROR, ENTRY, fs_db::fsdb_flags, FSDB_LOG_EMPTY, fs_db::fsdb_mdt_index_map, fs_db::fsdb_ost_index_map, LASSERT, LDD_F_NEED_INDEX, LDD_F_SV_TYPE_MDT, LDD_F_SV_TYPE_OST, mgs_find_or_make_fsdb(), mgs_target_info::mti_flags, mgs_target_info::mti_fsname, mgs_target_info::mti_stripe_index, and RETURN.
Referenced by mgs_check_target().
int mgs_cleanup_fsdb_list (struct mgs_device * mgs)
Definition at line 414 of file mgs_llog.c.
References list_entry, list_for_each_safe, mgs_free_fsdb(), mgs_device::mgs_fs_db_list, and mgs_device::mgs_mutex.
Referenced by mgs_device_fini().
int mgs_client_free (struct obd_export * exp)
Definition at line 111 of file mgs_fs.c.
Referenced by mgs_destroy_export().
void mgs_counter_incr (struct obd_export * exp, int opcode)
static struct mgs_direntry* mgs_direntry_alloc (int len) [static, read]
Definition at line 391 of file mgs_internal.h.
References INIT_LIST_HEAD, mgs_direntry::mde_len, mgs_direntry::mde_list, mgs_direntry::mde_name, OBD_ALLOC, OBD_ALLOC_PTR, and OBD_FREE_PTR.
Referenced by class_dentry_readdir().
static void mgs_direntry_free (struct mgs_direntry * de) [inline, static]
Definition at line 381 of file mgs_internal.h.
References LASSERT, list_empty(), mgs_direntry::mde_len, mgs_direntry::mde_list, mgs_direntry::mde_name, OBD_FREE, and OBD_FREE_PTR.
Referenced by mgs_erase_logs(), mgs_list_logs(), and mgs_write_log_direct_all().
static struct mgs_thread_info* mgs_env_info (const struct lu_env * env) [static, read]
Definition at line 302 of file mgs_internal.h.
References LASSERT, lu_env::le_ctx, lu_context_key_get(), lu_env_refill(), and mgs_thread_key.
Referenced by mgs_iocontrol(), mgs_iocontrol_pool(), mgs_llog_open(), mgs_set_info(), mgs_srpc_set_param_disk(), mgs_write_log_mdt(), mgs_write_log_param(), mgs_write_log_quota(), mgs_write_log_sys(), record_base(), record_lmv_setup(), record_lov_setup(), and record_marker().
int mgs_erase_log (const struct lu_env * env, struct mgs_device * mgs, char * name)
Definition at line 3801 of file mgs_llog.c.
References CERROR, LLOG_CONFIG_ORIG_CTXT, llog_ctxt_put(), llog_erase(), llog_get_context(), mgs_device::mgs_obd, and obd_device::obd_name.
Referenced by mgs_erase_logs(), and mgs_target_reg().
int mgs_erase_logs (const struct lu_env * env, struct mgs_device * mgs, char * fsname)
Definition at line 3827 of file mgs_llog.c.
References CDEBUG, class_dentry_readdir(), D_MGS, ENTRY, list_del_init(), list_for_each_entry_safe, mgs_direntry::mde_list, mgs_direntry::mde_name, mgs_direntry_free(), mgs_erase_log(), mgs_find_fsdb(), mgs_free_fsdb(), mgs_device::mgs_mutex, and RETURN.
Referenced by mgs_params_fsdb_cleanup(), and mgs_target_reg().
int mgs_export_stats_init (struct obd_device * obd, struct obd_export * exp, void * localdata)
Initialize MGS per-export statistics.
This function sets up procfs entries for various MGS export counters. These counters are for per-client statistics tracked on the server.
Parameters:
[in] obd OBD device
[in] exp OBD export
[in] localdata NID of client
Return values:
0 if successful
negative value on error
Definition at line 62 of file mgs_fs.c.
References ENTRY, obd_export::exp_nid_stats, GOTO, LPROC_MGS_LAST, lprocfs_alloc_stats(), lprocfs_free_stats(), lprocfs_init_ops_stats(), lprocfs_nid_ldlm_stats_init(), lprocfs_register_stats(), LPROCFS_STATS_FLAG_NOPERCPU, mgs_stats_counter_init(), nid_stat::nid_proc, nid_stat::nid_stats, and RETURN.
Referenced by mgs_obd_connect(), and mgs_obd_reconnect().
struct fs_db* mgs_find_fsdb (struct mgs_device * mgs, char * fsname) [read]
Definition at line 314 of file mgs_llog.c.
References fs_db::fsdb_name, list_entry, list_for_each, and mgs_device::mgs_fs_db_list.
Referenced by mgs_erase_logs(), and mgs_find_or_make_fsdb().
int mgs_find_or_make_fsdb (const struct lu_env * env, struct mgs_device * mgs, char * name, struct fs_db ** dbh)
Definition at line 428 of file mgs_llog.c.
References CDEBUG, CERROR, D_MGS, ENTRY, fs_db::fsdb_flags, FSDB_MGS_SELF, fs_db::fsdb_mutex, GOTO, mgs_find_fsdb(), mgs_free_fsdb(), mgs_get_fsdb_from_llog(), mgs_get_fsdb_srpc_from_llog(), mgs_device::mgs_mutex, mgs_new_fsdb(), and RETURN.
Referenced by mgs__mgs_fsdb_setup(), mgs_check_failnid(), mgs_check_index(), mgs_fsc_attach(), mgs_get_ir_logs(), mgs_ir_update(), mgs_params_fsdb_setup(), mgs_pool_cmd(), mgs_replace_nids(), mgs_set_index(), mgs_setparam(), and mgs_target_reg().
int mgs_fs_cleanup (const struct lu_env * env, struct mgs_device * m)
Definition at line 225 of file mgs_fs.c.
References dt_object::do_lu, local_oid_storage_fini(), lu_object_put(), mgs_device::mgs_configs_dir, mgs_device::mgs_los, mgs_device::mgs_nidtbl_dir, mgs_device::mgs_obd, nm_config_file_deregister(), and obd_device::u.
Referenced by mgs_device_fini(), and mgs_init0().
int mgs_fs_setup (const struct lu_env * env, struct mgs_device * m)
Definition at line 116 of file mgs_fs.c.
References CERROR, dt_device::dd_lu_dev, dt_object::do_index_ops, dt_object_operations::do_index_try, dt_object::do_lu, dt_object::do_ops, lvfs_run_ctxt::dt, dt_locate_at(), dt_nodemap_features, dt_root_get(), dt_try_as_dir(), ENTRY, lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, FID_SEQ_LOCAL_NAME, GOTO, LASSERT, lu_device::ld_site, local_file_find_or_create(), local_index_find_or_create(), local_oid_storage_fini(), local_oid_storage_init(), lu_site::ls_top_dev, lu_object_put(), LUSTRE_NODEMAP_NAME, mgs_device::mgs_bottom, mgs_device::mgs_configs_dir, mgs_device::mgs_dt_dev, mgs_device::mgs_los, mgs_device::mgs_nidtbl_dir, MGS_NIDTBL_DIR, mgs_device::mgs_obd, MOUNT_CONFIGS_DIR, nm_config_file_deregister(), nm_config_file_register(), obd_device::obd_lvfs_ctxt, obd_device::obd_name, OBD_SET_CTXT_MAGIC(), obd_device::u, and unlikely.
Referenced by mgs_init0().
int mgs_fsc_attach (const struct lu_env * env, struct obd_export * exp, char * fsname)
Definition at line 844 of file mgs_nids.c.
References class_export_get(), class_export_put(), ENTRY, obd_export::eu_mgs_data, exp2mgs_dev(), exp_connect_flags(), fs_db::fsdb_clients, fs_db::fsdb_ir_state, fs_db::fsdb_mutex, fs_db::fsdb_name, fs_db::fsdb_nonir_clients, INIT_LIST_HEAD, IR_FULL, IR_PARTIAL, list_add(), list_for_each_entry, mgs_export_data::med_clients, mgs_export_data::med_lock, mgs_fsc::mfc_export, mgs_fsc::mfc_export_list, mgs_fsc::mfc_fsdb, mgs_fsc::mfc_fsdb_list, mgs_fsc::mfc_ir_capable, mgs_find_or_make_fsdb(), OBD_ALLOC_PTR, OBD_CONNECT_IMP_RECOV, OBD_FREE_PTR, RETURN, and obd_export::u.
Referenced by mgs_llog_open().
void mgs_fsc_cleanup (struct obd_export * exp)
Definition at line 909 of file mgs_nids.c.
References class_export_put(), obd_export::eu_mgs_data, fs_db::fsdb_ir_state, fs_db::fsdb_mutex, fs_db::fsdb_nonir_clients, IR_FULL, IR_PARTIAL, LASSERT, list_del_init(), list_for_each_entry_safe, LIST_HEAD_INIT, list_splice_init(), mgs_export_data::med_clients, mgs_export_data::med_lock, mgs_fsc::mfc_export, mgs_fsc::mfc_export_list, mgs_fsc::mfc_fsdb, mgs_fsc::mfc_fsdb_list, mgs_fsc::mfc_ir_capable, OBD_FREE_PTR, and obd_export::u.
Referenced by mgs_obd_disconnect().
void mgs_fsc_cleanup_by_fsdb (struct fs_db * fsdb)
Definition at line 941 of file mgs_nids.c.
References class_export_put(), obd_export::eu_mgs_data, fs_db::fsdb_clients, fs_db::fsdb_ir_state, fs_db::fsdb_nonir_clients, IR_FULL, IR_PARTIAL, LASSERT, list_del_init(), list_for_each_entry_safe, mgs_export_data::med_lock, mgs_fsc::mfc_export, mgs_fsc::mfc_export_list, mgs_fsc::mfc_fsdb, mgs_fsc::mfc_fsdb_list, OBD_FREE_PTR, and obd_export::u.
Referenced by mgs_ir_fini_fs().
int mgs_get_fsdb_srpc_from_llog (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb)
Definition at line 3199 of file mgs_llog.c.
References CERROR, ENTRY, fs_db::fsdb_name, GOTO, LASSERT, llog_close(), LLOG_CONFIG_ORIG_CTXT, llog_ctxt_put(), LLOG_F_IS_PLAIN, llog_get_context(), llog_get_size(), llog_init_handle(), llog_open(), LLOG_OPEN_EXISTS, llog_process(), mgs_log_is_empty(), mgs_device::mgs_obd, mgs_srpc_read_handler(), mgs_srpc_read_data::msrd_fsdb, mgs_srpc_read_data::msrd_skip, name_create(), name_destroy(), and RETURN.
Referenced by mgs_find_or_make_fsdb().
int mgs_get_ir_logs (struct ptlrpc_request * req)
Definition at line 598 of file mgs_nids.c.
References ptlrpc_bulk_frag_ops::add_kiov_frag, ptlrpc_bulk_desc::bd_frag_ops, bufsize, CDEBUG, CONFIG_T_RECOVER, D_MGS, delogname(), ENTRY, exp2mgs_dev(), fs_db::fsdb_nidtbl, GOTO, LASSERT, mgs_config_body::mcb_bits, mgs_config_body::mcb_name, mgs_config_body::mcb_offset, mgs_config_body::mcb_type, mgs_config_body::mcb_units, mgs_config_res::mcr_offset, MGS_BULK_PORTAL, mgs_find_or_make_fsdb(), mgs_nidtbl_read(), min_t, OBD_ALLOC, OBD_FREE, PTLRPC_BULK_BUF_KIOV, ptlrpc_bulk_kiov_pin_ops, PTLRPC_BULK_PUT_SOURCE, ptlrpc_free_bulk(), PTLRPC_MAX_BRW_PAGES, req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_MGS_CONFIG_BODY, RMF_MGS_CONFIG_RES, ptlrpc_request::rq_export, and ptlrpc_request::rq_pill.
Referenced by mgs_config_read().
int mgs_get_lock (struct obd_device * obd, struct ldlm_res_id * res, struct lustre_handle * lockh)
int mgs_init_fsdb_list (struct mgs_device * mgs)
Definition at line 408 of file mgs_llog.c.
References INIT_LIST_HEAD, and mgs_device::mgs_fs_db_list.
Referenced by mgs_init0().
void mgs_ir_fini_fs (struct mgs_device * mgs, struct fs_db * fsdb)
Definition at line 487 of file mgs_nids.c.
References fs_db::fsdb_clients, fs_db::fsdb_flags, FSDB_MGS_SELF, fs_db::fsdb_notify_comp, fs_db::fsdb_notify_stop, fs_db::fsdb_notify_waitq, LASSERT, list_empty(), mgs_fsc_cleanup_by_fsdb(), and mgs_nidtbl_fini_fs().
Referenced by mgs_free_fsdb().
int mgs_ir_init_fs (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb)
Definition at line 455 of file mgs_nids.c.
References CERROR, cfs_time_before(), cfs_time_current_sec(), fs_db::fsdb_clients, fs_db::fsdb_ir_state, fs_db::fsdb_mgs, fs_db::fsdb_name, fs_db::fsdb_nonir_clients, fs_db::fsdb_notify_comp, fs_db::fsdb_notify_phase, fs_db::fsdb_notify_waitq, INIT_LIST_HEAD, IR_FULL, IR_STARTUP, ir_timeout, mgs_ir_notify(), mgs_nidtbl_init_fs(), mgs_device::mgs_start_time, and OBD_IR_MGS_TIMEOUT.
Referenced by mgs_new_fsdb().
void mgs_ir_notify_complete (struct fs_db * fsdb)
Definition at line 400 of file mgs_nids.c.
References CDEBUG, cfs_duration_usec(), cfs_time_current(), cfs_time_sub(), D_MGS, fs_db::fsdb_name, fs_db::fsdb_notify_count, fs_db::fsdb_notify_max, fs_db::fsdb_notify_phase, fs_db::fsdb_notify_start, and fs_db::fsdb_notify_total.
Referenced by mgs_completion_ast_generic().
int mgs_ir_update (const struct lu_env * env, struct mgs_device * mgs, struct mgs_target_info * mti)
Definition at line 516 of file mgs_nids.c.
References CDEBUG, D_MGS, ergo, fs_db::fsdb_ir_state, fs_db::fsdb_mutex, fs_db::fsdb_name, fs_db::fsdb_notify_phase, fs_db::fsdb_notify_waitq, IR_DISABLED, IR_FULL, IR_PARTIAL, IR_STARTUP, ir_state_graduate(), LASSERT, LBUG, LDD_F_IR_CAPABLE, mgs_find_or_make_fsdb(), mgs_nidtbl_write(), mgs_target_info::mti_flags, mgs_target_info::mti_fsname, and mgs_target_info::mti_instance.
Referenced by mgs_target_reg().
int mgs_list_logs (const struct lu_env * env, struct mgs_device * mgs, struct obd_ioctl_data * data)
Definition at line 3868 of file mgs_llog.c.
References class_dentry_readdir(), ENTRY, obd_ioctl_data::ioc_bulk, obd_ioctl_data::ioc_inllen1, list_del_init(), list_for_each_entry_safe, mgs_direntry::mde_list, mgs_direntry::mde_name, mgs_direntry_free(), and RETURN.
Referenced by mgs_iocontrol().
int mgs_nodemap_cmd (const struct lu_env * env, struct mgs_device * mgs, enum lcfg_command_type cmd, const char * nodemap_name, char * param)
Definition at line 4102 of file mgs_llog.c.
References ENTRY, LCFG_NODEMAP_ADD, LCFG_NODEMAP_ADD_GIDMAP, LCFG_NODEMAP_ADD_RANGE, LCFG_NODEMAP_ADD_UIDMAP, LCFG_NODEMAP_ADMIN, LCFG_NODEMAP_DEL, LCFG_NODEMAP_DEL_GIDMAP, LCFG_NODEMAP_DEL_RANGE, LCFG_NODEMAP_DEL_UIDMAP, LCFG_NODEMAP_SQUASH_GID, LCFG_NODEMAP_SQUASH_UID, LCFG_NODEMAP_TRUSTED, nodemap_add(), nodemap_add_idmap(), nodemap_add_range(), nodemap_del(), nodemap_del_idmap(), nodemap_del_range(), NODEMAP_GID, nodemap_parse_idmap(), nodemap_parse_range(), nodemap_set_allow_root(), nodemap_set_squash_gid(), nodemap_set_squash_uid(), nodemap_set_trust_client_ids(), NODEMAP_UID, and RETURN.
Referenced by mgs_iocontrol_nodemap().
static struct mgs_object* mgs_obj (const struct lu_object * o) [static, read]
Definition at line 358 of file mgs_internal.h.
References dt_object::do_lu, LASSERT, lu_object::lo_dev, lu_device_is_mgs(), and mgs_object::mgo_obj.
Referenced by dt2mgs_obj().
static struct dt_object* mgs_object_child (struct mgs_object * o) [static, read]
Definition at line 369 of file mgs_internal.h.
References dt_object::do_lu, lu_object_next(), and mgs2lu_obj().
int mgs_params_fsdb_cleanup (const struct lu_env * env, struct mgs_device * mgs)
Definition at line 3961 of file mgs_llog.c.
References mgs_erase_logs(), and PARAMS_FILENAME.
Referenced by mgs_device_fini(), and mgs_init0().
int mgs_params_fsdb_setup (const struct lu_env * env, struct mgs_device * mgs, struct fs_db * fsdb)
Definition at line 3940 of file mgs_llog.c.
References ENTRY, fs_db::fsdb_mutex, mgs_find_or_make_fsdb(), PARAMS_FILENAME, record_end_log(), record_start_log(), and RETURN.
Referenced by mgs_init0().
int mgs_pool_cmd (const struct lu_env * env, struct mgs_device * mgs, enum lcfg_command_type cmd, char * poolname, char * fsname, char * ostname)
Definition at line 4179 of file mgs_llog.c.
References CERROR, CM_SKIP, CONFIG_T_CONFIG, ENTRY, EXIT, fs_db::fsdb_clilov, fs_db::fsdb_flags, FSDB_LOG_EMPTY, fs_db::fsdb_mdt_index_map, fs_db::fsdb_mutex, GOTO, INDEX_MAP_SIZE, LCFG_POOL_ADD, LCFG_POOL_DEL, LCFG_POOL_NEW, LCFG_POOL_REM, mgs_find_or_make_fsdb(), mgs_free_fsdb(), mgs_modify(), mgs_revoke_lock(), mgs_write_log_pool(), mgs_target_info::mti_svname, name_create(), name_create_mdt_and_lov(), name_destroy(), OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, and RETURN.
Referenced by mgs_iocontrol_pool().
int mgs_put_lock (struct lustre_handle * lockh)
int mgs_replace_nids (const struct lu_env * env, struct mgs_device * mgs, char * devname, char * nids)
Replace nids for device to nids values.
Parameters:
obd MGS obd device
devname nids need to be replaced for this device (ex. lustre-OST0000)
nids nids list (ex. nid1,nid2,nid3)
Return values:
0 success
Definition at line 1205 of file mgs_llog.c.
References CERROR, ENTRY, fs_db::fsdb_mdt_index_map, GOTO, INDEX_MAP_SIZE, mgs_find_or_make_fsdb(), mgs_device::mgs_obd, mgs_parse_devname(), mgs_replace_nids_log(), MTI_NAME_MAXLEN, name_create(), name_create_mdt(), name_destroy(), obd_device::obd_dev_lock, obd_device::obd_no_conn, only_mgs_is_running(), and RETURN.
Referenced by mgs_iocontrol().
void mgs_revoke_lock (struct mgs_device * mgs, struct fs_db * fsdb, int type)
Definition at line 227 of file mgs_handler.c.
References __u64, CERROR, CONFIG_T_CONFIG, CONFIG_T_PARAMS, CONFIG_T_RECOVER, ELDLM_OK, ENTRY, fs_db::fsdb_flags, fs_db::fsdb_name, FSDB_REVOKING_LOCK, FSDB_REVOKING_PARAMS, LASSERT, LCK_EX, ldlm_blocking_ast(), ldlm_cli_enqueue_local(), LDLM_FL_ATOMIC_CB, LDLM_PLAIN, le64_to_cpu, LPX64, LVB_T_NONE, mgc_fsname2resid(), mgs_completion_ast_config(), mgs_completion_ast_ir(), mgs_completion_ast_params(), mgs_device::mgs_obd, ldlm_res_id::name, obd_device::obd_namespace, and RETURN_EXIT.
Referenced by mgs_ir_notify(), mgs_pool_cmd(), mgs_setparam(), and mgs_target_reg().
int mgs_setparam (const struct lu_env * env, struct mgs_device * mgs, struct lustre_cfg * lcfg, char * fsname)
Definition at line 3970 of file mgs_llog.c.
References CDEBUG, CERROR, CONFIG_T_CONFIG, CONFIG_T_PARAMS, D_MGS, devname, ENTRY, fs_db::fsdb_flags, FSDB_LOG_EMPTY, FSDB_MGS_SELF, fs_db::fsdb_mutex, GOTO, lustre_cfg::lcfg_command, LCFG_SET_PARAM, LCONSOLE_ERROR_MSG, LDD_F_PARAM, LDD_F_PARAM2, lustre_cfg_string(), mgs_find_or_make_fsdb(), mgs_free_fsdb(), mgs_parse_devname(), mgs_revoke_lock(), mgs_write_log_param(), mgs_write_log_param2(), mgs_target_info::mti_flags, mgs_target_info::mti_fsname, MTI_NAME_MAXLEN, mgs_target_info::mti_params, mgs_target_info::mti_stripe_index, mgs_target_info::mti_svname, OBD_ALLOC_PTR, OBD_FREE_PTR, PARAM_LLITE, PARAMS_FILENAME, print_lustre_cfg(), RETURN, server_make_name(), server_name2index(), and strlcpy().
Referenced by mgs_iocontrol(), and mgs_set_info().
void mgs_stats_counter_init (struct lprocfs_stats * stats)
Referenced by mgs_export_stats_init().
int mgs_write_log_target (const struct lu_env * env, struct mgs_device * mgs, struct mgs_target_info * mti, struct fs_db * fsdb)
Definition at line 3723 of file mgs_llog.c.
References buf, CDEBUG, CERROR, class_get_next_param(), D_MGS, ENTRY, fs_db::fsdb_mutex, GOTO, LCONSOLE_WARN, LDD_F_PARAM, LDD_F_SV_TYPE_MDT, LDD_F_SV_TYPE_OST, LDD_F_UPDATE, LDD_F_UPGRADE14, LDD_F_VIRGIN, LDD_F_WRITECONF, mgs_set_index(), mgs_write_log_mdt(), mgs_write_log_ost(), mgs_write_log_param(), mgs_target_info::mti_flags, mgs_target_info::mti_params, mgs_target_info::mti_stripe_index, mgs_target_info::mti_svname, OBD_ALLOC, OBD_FREE, and RETURN.
Referenced by mgs_target_reg().
Variable Documentation
struct lu_device_operations mgs_lu_ops
Definition at line 1353 of file mgs_handler.c.
Referenced by lu_device_is_mgs(), and mgs_init0().
struct lu_context_key mgs_thread_key
Referenced by mgs_env_info().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.