Lustre: lustre/utils/mkfs_lustre.c File Reference
lustre/utils/mkfs_lustre.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <fcntl.h>
#include <stdarg.h>
#include <mntent.h>
#include <stdbool.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/mount.h>
#include <sys/utsname.h>
#include <string.h>
#include <getopt.h>
#include <limits.h>
#include <ctype.h>
#include <lnet/nidstr.h>
#include <lustre_disk.h>
#include <lustre_param.h>
#include <lnet/lnetctl.h>
#include <lustre_ver.h>
#include "mount_utils.h"
Defines
#define FSLIST_LDISKFS ""
#define FSLIST_ZFS ""
#define FSLIST FSLIST_LDISKFS FSLIST_ZFS
#define MAXNIDSTR 1024
Functions
void usage (FILE *out)
void print_ldd (char *str, struct lustre_disk_data *ldd)
void set_defaults (struct mkfs_opts *mop)
static void badopt (const char *opt, char *type)
static char * convert_hostnames (char *s1)
int parse_opts (int argc, char *const argv[], struct mkfs_opts *mop, char **mountopts)
int main (int argc, char *const argv[])
Variables
char * progname
int verbose = 1
int version
static int print_only = 0
Define Documentation
#define FSLIST FSLIST_LDISKFS FSLIST_ZFS
Definition at line 101 of file mkfs_lustre.c.
Referenced by usage().
#define FSLIST_LDISKFS ""
Definition at line 84 of file mkfs_lustre.c.
#define FSLIST_ZFS ""
Definition at line 94 of file mkfs_lustre.c.
#define MAXNIDSTR 1024
Definition at line 232 of file mkfs_lustre.c.
Referenced by convert_hostnames().
Function Documentation
static void badopt (const char * opt, char * type) [inline, static]
Definition at line 223 of file mkfs_lustre.c.
References progname, and usage.
Referenced by main(), and parse_opts().
static char* convert_hostnames (char * s1) [static]
Definition at line 233 of file mkfs_lustre.c.
References end, libcfs_nid2str(), libcfs_str2nid(), LNET_NID_ANY, MAXNIDSTR, and progname.
Referenced by parse_opts().
int main (int argc, char *const argv[])
Definition at line 601 of file mkfs_lustre.c.
References badopt(), check_mountfsoptions(), check_mtab_entry(), fatal(), INDEX_UNASSIGNED, IS_MDT, IS_MGS, IS_OST, LDD_F_NEED_INDEX, LDD_F_UPGRADE14, LDD_F_VIRGIN, LDD_F_WRITECONF, lustre_disk_data::ldd_flags, lustre_disk_data::ldd_fsname, lustre_disk_data::ldd_mount_opts, lustre_disk_data::ldd_mount_type, lustre_disk_data::ldd_params, lustre_disk_data::ldd_svindex, lustre_disk_data::ldd_svname, loop_cleanup(), loop_format(), loop_setup(), mkfs_opts::mo_device, mkfs_opts::mo_flags, MO_FORCEFORMAT, MO_IS_LOOP, mount_opts::mo_ldd, mkfs_opts::mo_ldd, mkfs_opts::mo_mgs_failnodes, MO_QUOTA, mount_opts::mo_source, osd_enable_quota(), osd_fini(), osd_fix_mountopts(), osd_init(), osd_is_lustre(), osd_label_lustre(), osd_make_lustre(), osd_prepare_lustre(), osd_read_ldd(), osd_write_ldd(), PARAM_MGSNODE, parse_opts(), print_ldd(), print_only, progname, ret, server_make_name(), set_defaults(), strscpy(), trim_mountfsoptions(), usage, verbose, verrprint, and version.
int parse_opts (int argc, char *const argv[], struct mkfs_opts * mop, char ** mountopts)
Definition at line 278 of file mkfs_lustre.c.
References add_param(), append_param(), badopt(), convert_hostnames(), fatal(), INDEX_UNASSIGNED, IS_MDT, IS_OST, LDD_F_NEED_INDEX, LDD_F_NO_PRIMNODE, LDD_F_SV_TYPE_MDT, LDD_F_SV_TYPE_MGS, LDD_F_SV_TYPE_OST, LDD_F_UPDATE, LDD_F_UPGRADE14, LDD_F_VIRGIN, LDD_F_WRITECONF, lustre_disk_data::ldd_flags, lustre_disk_data::ldd_fsname, lustre_disk_data::ldd_mount_type, LDD_MT_LAST, lustre_disk_data::ldd_params, lustre_disk_data::ldd_svindex, lustre_disk_data::ldd_userdata, lustre_is_fsname_valid(), LUSTRE_MAXFSNAME, mkfs_opts::mo_device, mkfs_opts::mo_device_kb, MO_FAILOVER, mkfs_opts::mo_flags, MO_FORCEFORMAT, mkfs_opts::mo_ldd, mkfs_opts::mo_mgs_failnodes, mkfs_opts::mo_mkfsopts, mkfs_opts::mo_mountopts, mkfs_opts::mo_pool_vdevs, MO_QUOTA, mkfs_opts::mo_stripe_count, mt_str(), name, opt, optarg, optind, PARAM_FAILNODE, PARAM_MGSNODE, PARAM_NETWORK, print_only, progname, strscpy(), usage, verbose, and version.
Referenced by main().
void print_ldd (char * str, struct lustre_disk_data * ldd)
Definition at line 177 of file mkfs_lustre.c.
References INDEX_UNASSIGNED, IS_MDT, IS_MGS, IS_OST, LDD_F_NEED_INDEX, LDD_F_NO_PRIMNODE, LDD_F_UPDATE, LDD_F_UPGRADE14, LDD_F_VIRGIN, LDD_F_WRITECONF, lustre_disk_data::ldd_flags, lustre_disk_data::ldd_fsname, lustre_disk_data::ldd_mount_opts, lustre_disk_data::ldd_params, lustre_disk_data::ldd_svindex, lustre_disk_data::ldd_svname, lustre_disk_data::ldd_userdata, lustre_disk_data::ldd_uuid, and MT_STR.
Referenced by main().
void set_defaults (struct mkfs_opts * mop)
Definition at line 207 of file mkfs_lustre.c.
References INDEX_UNASSIGNED, lustre_disk_data::ldd_config_ver, LDD_F_NEED_INDEX, LDD_F_UPDATE, LDD_F_VIRGIN, lustre_disk_data::ldd_flags, LDD_MAGIC, lustre_disk_data::ldd_magic, lustre_disk_data::ldd_mount_type, LDD_MT_LDISKFS, LDD_MT_ZFS, lustre_disk_data::ldd_svindex, mkfs_opts::mo_ldd, mkfs_opts::mo_mgs_failnodes, mkfs_opts::mo_pool_vdevs, and mkfs_opts::mo_stripe_count.
Referenced by main().
void usage (FILE * out)
Definition at line 103 of file mkfs_lustre.c.
References FSLIST, and progname.
Variable Documentation
int print_only = 0 [static]
Definition at line 78 of file mkfs_lustre.c.
Referenced by main(), and parse_opts().
char* progname
Definition at line 75 of file mkfs_lustre.c.
int verbose = 1
Definition at line 76 of file mkfs_lustre.c.
int version
Definition at line 77 of file mkfs_lustre.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.