Lustre: lustre/utils/mount_lustre.c File Reference
lustre/utils/mount_lustre.c File Reference
#include <getopt.h>
#include <mntent.h>
#include <stdbool.h>
#include <stdlib.h>
#include <stdio.h>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <string.h>
#include <sys/mount.h>
#include <lustre_ver.h>
#include <ctype.h>
#include <limits.h>
#include <lnet/nidstr.h>
#include <lustre/lustre_idl.h>
#include "obdctl.h"
#include "mount_utils.h"
#include <linux/fs.h>
Data Structures
struct opt_map
Defines
#define WITH_LIBMOUNT ""
#define MAXOPT 4096
#define MAX_RETRIES 99
#define MAXNIDSTR 1024
Functions
void usage (FILE *out)
static char * convert_hostnames (char *s1)
static int parse_one_option (const char *check, int *flagp)
static void append_option (char *options, const char *one)
int parse_options (struct mount_opts *mop, char *orig_options, int *flagp)
static int add_mgsnids (struct mount_opts *mop, char *options, const char *params)
static int clear_update_ondisk (char *source, struct lustre_disk_data *ldd)
static int parse_ldd (char *source, struct mount_opts *mop, char *options)
static void set_defaults (struct mount_opts *mop)
static int parse_opts (int argc, char *const argv[], struct mount_opts *mop)
int main (int argc, char *const argv[])
Variables
int verbose
int version
char * progname
static struct opt_map opt_map []
Define Documentation
#define MAX_RETRIES 99
Definition at line 85 of file mount_lustre.c.
Referenced by parse_options().
#define MAXNIDSTR 1024
Definition at line 124 of file mount_lustre.c.
#define MAXOPT 4096
Definition at line 84 of file mount_lustre.c.
Referenced by main().
#define WITH_LIBMOUNT ""
Definition at line 81 of file mount_lustre.c.
Referenced by parse_opts().
Function Documentation
static int add_mgsnids (struct mount_opts * mop, char * options, const char * params) [static]
Definition at line 309 of file mount_lustre.c.
References append_option(), mount_opts::mo_have_mgsnid, and PARAM_MGSNODE.
Referenced by parse_ldd().
static void append_option (char * options, const char * one) [static]
Definition at line 235 of file mount_lustre.c.
Referenced by add_mgsnids(), main(), parse_ldd(), and parse_options().
static int clear_update_ondisk (char * source, struct lustre_disk_data * ldd) [static]
Definition at line 334 of file mount_lustre.c.
References fatal(), LDD_F_UPDATE, lustre_disk_data::ldd_flags, loop_cleanup(), loop_setup(), mkfs_opts::mo_device, mkfs_opts::mo_flags, MO_IS_LOOP, mkfs_opts::mo_ldd, osd_prepare_lustre(), osd_write_ldd(), and ret.
Referenced by parse_ldd().
static char* convert_hostnames (char * s1) [static]
Definition at line 125 of file mount_lustre.c.
References libcfs_nid2str(), libcfs_str2nid(), LNET_NID_ANY, MAXNIDSTR, and progname.
Referenced by parse_opts().
int main (int argc, char *const argv[])
Definition at line 626 of file mount_lustre.c.
References append_option(), check_mtab_entry(), cmd, LDD_F_VIRGIN, LDD_F_WRITECONF, lustre_disk_data::ldd_flags, MAXOPT, mount_opts::mo_fake, mount_opts::mo_force, mount_opts::mo_ldd, mount_opts::mo_nomtab, mount_opts::mo_nosvc, mount_opts::mo_orig_options, mount_opts::mo_retry, mount_opts::mo_source, mount_opts::mo_target, mount_opts::mo_usource, osd_fini(), osd_init(), osd_label_lustre(), osd_tune_lustre(), parse_ldd(), parse_options(), parse_opts(), progname, ret, set_defaults(), update_mtab_entry(), update_utab_entry(), verbose, and version.
static int parse_ldd (char * source, struct mount_opts * mop, char * options) [static]
Definition at line 393 of file mount_lustre.c.
References add_mgsnids(), append_option(), clear_update_ondisk(), IS_MDT, IS_OST, LDD_F_NEED_INDEX, LDD_F_NO_PRIMNODE, LDD_F_SV_TYPE_MGS, LDD_F_UPDATE, LDD_F_UPGRADE14, LDD_F_VIRGIN, LDD_F_WRITECONF, lustre_disk_data::ldd_flags, lustre_disk_data::ldd_mount_opts, lustre_disk_data::ldd_mount_type, lustre_disk_data::ldd_params, lustre_disk_data::ldd_svname, mount_opts::mo_have_mgsnid, mount_opts::mo_ldd, mt_type(), osd_is_lustre(), osd_read_ldd(), progname, and start.
Referenced by main().
static int parse_one_option (const char * check, int * flagp) [static]
Definition at line 215 of file mount_lustre.c.
References opt_map::inv, opt_map::mask, opt_map::opt, and opt.
Referenced by parse_options().
int parse_options (struct mount_opts * mop, char * orig_options, int * flagp)
Definition at line 244 of file mount_lustre.c.
References append_option(), MAX_RETRIES, mount_opts::mo_force, mount_opts::mo_md_stripe_cache_size, mount_opts::mo_nosvc, mount_opts::mo_retry, opt, and parse_one_option().
Referenced by main().
static int parse_opts (int argc, char *const argv[], struct mount_opts * mop) [static]
Try to get the real path to the device, in case it is a symbolic link for instance
Definition at line 521 of file mount_lustre.c.
References convert_hostnames(), mount_opts::mo_fake, mount_opts::mo_force, mount_opts::mo_nomtab, mount_opts::mo_orig_options, mount_opts::mo_source, mount_opts::mo_target, mount_opts::mo_usource, name, opt, optarg, optind, path, progname, usage, verbose, version, and WITH_LIBMOUNT.
static void set_defaults (struct mount_opts * mop) [static]
Definition at line 506 of file mount_lustre.c.
References mount_opts::mo_fake, mount_opts::mo_force, mount_opts::mo_have_mgsnid, mount_opts::mo_md_stripe_cache_size, mount_opts::mo_nomtab, mount_opts::mo_nosvc, mount_opts::mo_orig_options, mount_opts::mo_retry, mount_opts::mo_source, and mount_opts::mo_usource.
void usage (FILE * out)
Definition at line 91 of file mount_lustre.c.
References progname.
Variable Documentation
struct opt_map opt_map[] [static]
Definition at line 174 of file mount_lustre.c.
char* progname
Definition at line 89 of file mount_lustre.c.
int verbose
Definition at line 87 of file mount_lustre.c.
int version
Definition at line 88 of file mount_lustre.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.