Lustre: lustre/utils/mount_utils_zfs.c File Reference
lustre/utils/mount_utils_zfs.c File Reference
#include "mount_utils.h"
#include <stddef.h>
#include <stdio.h>
#include <string.h>
#include <libzfs.h>
Data Structures
struct zfs_ldd_prop_bridge
Defines
#define LDD_PREFIX "lustre:"
#define LDD_VERSION_PROP LDD_PREFIX "version"
#define LDD_FLAGS_PROP LDD_PREFIX "flags"
#define LDD_INDEX_PROP LDD_PREFIX "index"
#define LDD_FSNAME_PROP LDD_PREFIX "fsname"
#define LDD_SVNAME_PROP LDD_PREFIX "svname"
#define LDD_UUID_PROP LDD_PREFIX "uuid"
#define LDD_USERDATA_PROP LDD_PREFIX "userdata"
#define LDD_MOUNTOPTS_PROP LDD_PREFIX "mountopts"
#define ZLB_INIT(name, field, type)
Functions
static int zfs_get_prop_int (zfs_handle_t *, char *, void *)
static int zfs_set_prop_int (zfs_handle_t *, char *, void *)
static int zfs_get_prop_str (zfs_handle_t *, char *, void *)
static int zfs_set_prop_str (zfs_handle_t *, char *, void *)
void zfs_fini (void)
static int zfs_set_prop_params (zfs_handle_t *zhp, char *params)
static int osd_check_zfs_setup (void)
int zfs_write_ldd (struct mkfs_opts *mop)
static int zfs_is_special_ldd_prop_param (char *name)
static int zfs_get_prop_params (zfs_handle_t *zhp, char *param, int len)
int zfs_read_ldd (char *ds, struct lustre_disk_data *ldd)
int zfs_is_lustre (char *ds, unsigned *mount_type)
static char * zfs_mkfs_opts (struct mkfs_opts *mop, char *str, int len)
static int zfs_create_vdev (struct mkfs_opts *mop, char *vdev)
int zfs_make_lustre (struct mkfs_opts *mop)
int zfs_enable_quota (struct mkfs_opts *mop)
int zfs_prepare_lustre (struct mkfs_opts *mop, char *wanted_mountopts, size_t len)
int zfs_tune_lustre (char *dev, struct mount_opts *mop)
int zfs_label_lustre (struct mount_opts *mop)
int zfs_init (void)
Variables
struct zfs_ldd_prop_bridge special_ldd_prop_params []
static int osd_zfs_setup = 0
static libzfs_handle_t * g_zfs
Define Documentation
#define LDD_FLAGS_PROP LDD_PREFIX "flags"
Definition at line 38 of file mount_utils_zfs.c.
#define LDD_FSNAME_PROP LDD_PREFIX "fsname"
Definition at line 40 of file mount_utils_zfs.c.
#define LDD_INDEX_PROP LDD_PREFIX "index"
Definition at line 39 of file mount_utils_zfs.c.
#define LDD_MOUNTOPTS_PROP LDD_PREFIX "mountopts"
Definition at line 44 of file mount_utils_zfs.c.
#define LDD_PREFIX "lustre:"
Definition at line 36 of file mount_utils_zfs.c.
Referenced by zfs_get_prop_params(), and zfs_set_prop_params().
#define LDD_SVNAME_PROP LDD_PREFIX "svname"
Definition at line 41 of file mount_utils_zfs.c.
Referenced by zfs_label_lustre().
#define LDD_USERDATA_PROP LDD_PREFIX "userdata"
Definition at line 43 of file mount_utils_zfs.c.
#define LDD_UUID_PROP LDD_PREFIX "uuid"
Definition at line 42 of file mount_utils_zfs.c.
#define LDD_VERSION_PROP LDD_PREFIX "version"
Definition at line 37 of file mount_utils_zfs.c.
#define ZLB_INIT (name, field, type)
Value:
{                                                       \
        name, offsetof(struct lustre_disk_data, field), \
        zfs_get_prop_ ## type, zfs_set_prop_ ## type    \
}
Definition at line 78 of file mount_utils_zfs.c.
Function Documentation
static int osd_check_zfs_setup (void) [static]
Definition at line 177 of file mount_utils_zfs.c.
References fatal(), and osd_zfs_setup.
Referenced by zfs_label_lustre(), zfs_make_lustre(), zfs_prepare_lustre(), zfs_read_ldd(), zfs_tune_lustre(), and zfs_write_ldd().
static int zfs_create_vdev (struct mkfs_opts * mop, char * vdev) [static]
Definition at line 381 of file mount_utils_zfs.c.
References fatal(), file_create(), mkfs_opts::mo_device_kb, and ret.
Referenced by zfs_make_lustre().
int zfs_enable_quota (struct mkfs_opts * mop)
Definition at line 560 of file mount_utils_zfs.c.
void zfs_fini (void)
Definition at line 629 of file mount_utils_zfs.c.
References g_zfs, and osd_zfs_setup.
static int zfs_get_prop_int (zfs_handle_t * zhp, char * prop, void * val) [static]
Definition at line 224 of file mount_utils_zfs.c.
References ret.
static int zfs_get_prop_params (zfs_handle_t * zhp, char * param, int len) [static]
Definition at line 276 of file mount_utils_zfs.c.
References add_param(), LDD_PREFIX, ret, zfs_get_prop_str(), and zfs_is_special_ldd_prop_param().
Referenced by zfs_read_ldd().
static int zfs_get_prop_str (zfs_handle_t * zhp, char * prop, void * val) [static]
Definition at line 246 of file mount_utils_zfs.c.
References ret.
Referenced by zfs_get_prop_params().
int zfs_init (void)
Definition at line 614 of file mount_utils_zfs.c.
References g_zfs, osd_zfs_setup, and ret.
int zfs_is_lustre (char * ds, unsigned * mount_type)
Definition at line 353 of file mount_utils_zfs.c.
References lustre_disk_data::ldd_config_ver, lustre_disk_data::ldd_mount_type, lustre_disk_data::ldd_svname, osd_zfs_setup, ret, and zfs_read_ldd().
static int zfs_is_special_ldd_prop_param (char * name) [static]
Definition at line 265 of file mount_utils_zfs.c.
References zfs_ldd_prop_bridge::zlpb_prop_name.
Referenced by zfs_get_prop_params().
int zfs_label_lustre (struct mount_opts * mop)
Definition at line 596 of file mount_utils_zfs.c.
References g_zfs, lustre_disk_data::ldd_svname, LDD_SVNAME_PROP, mount_opts::mo_ldd, mount_opts::mo_source, osd_check_zfs_setup(), ret, and zfs_set_prop_str().
int zfs_make_lustre (struct mkfs_opts * mop)
Definition at line 433 of file mount_utils_zfs.c.
References fatal(), g_zfs, LDD_F_NEED_INDEX, lustre_disk_data::ldd_flags, mkfs_opts::mo_device, mkfs_opts::mo_flags, MO_FORCEFORMAT, mkfs_opts::mo_ldd, mkfs_opts::mo_pool_vdevs, osd_check_zfs_setup(), ret, run_command(), strscat(), vprint, zfs_create_vdev(), and zfs_mkfs_opts().
static char* zfs_mkfs_opts (struct mkfs_opts * mop, char * str, int len) [static]
Definition at line 371 of file mount_utils_zfs.c.
References mkfs_opts::mo_mkfsopts.
Referenced by zfs_make_lustre().
int zfs_prepare_lustre (struct mkfs_opts * mop, char * wanted_mountopts, size_t len)
Definition at line 566 of file mount_utils_zfs.c.
References fatal(), mkfs_opts::mo_device, and osd_check_zfs_setup().
int zfs_read_ldd (char * ds, struct lustre_disk_data * ldd)
Definition at line 320 of file mount_utils_zfs.c.
References g_zfs, lustre_disk_data::ldd_mount_type, LDD_MT_ZFS, lustre_disk_data::ldd_params, osd_check_zfs_setup(), ret, zfs_get_prop_params(), zfs_ldd_prop_bridge::zlpb_get_prop_fn, zfs_ldd_prop_bridge::zlpb_ldd_offset, and zfs_ldd_prop_bridge::zlpb_prop_name.
Referenced by zfs_is_lustre().
static int zfs_set_prop_int (zfs_handle_t * zhp, char * prop, void * val) [static]
Definition at line 108 of file mount_utils_zfs.c.
References ret, and vprint.
static int zfs_set_prop_params (zfs_handle_t * zhp, char * params) [static]
Definition at line 141 of file mount_utils_zfs.c.
References LDD_PREFIX, ret, and vprint.
Referenced by zfs_write_ldd().
static int zfs_set_prop_str (zfs_handle_t * zhp, char * prop, void * val) [static]
Definition at line 124 of file mount_utils_zfs.c.
References ret, and vprint.
Referenced by zfs_label_lustre().
int zfs_tune_lustre (char * dev, struct mount_opts * mop)
Definition at line 588 of file mount_utils_zfs.c.
References osd_check_zfs_setup().
int zfs_write_ldd (struct mkfs_opts * mop)
Definition at line 189 of file mount_utils_zfs.c.
References g_zfs, lustre_disk_data::ldd_params, mkfs_opts::mo_device, mkfs_opts::mo_ldd, osd_check_zfs_setup(), ret, vprint, zfs_set_prop_params(), zfs_ldd_prop_bridge::zlpb_ldd_offset, zfs_ldd_prop_bridge::zlpb_prop_name, and zfs_ldd_prop_bridge::zlpb_set_prop_fn.
Variable Documentation
libzfs_handle_t* g_zfs [static]
Definition at line 104 of file mount_utils_zfs.c.
Referenced by zfs_fini(), zfs_init(), zfs_label_lustre(), zfs_make_lustre(), zfs_read_ldd(), and zfs_write_ldd().
int osd_zfs_setup = 0 [static]
Definition at line 102 of file mount_utils_zfs.c.
Referenced by osd_check_zfs_setup(), zfs_fini(), zfs_init(), and zfs_is_lustre().
struct zfs_ldd_prop_bridge special_ldd_prop_params[]
Initial value:
 {
        ZLB_INIT(LDD_VERSION_PROP,   ldd_config_ver, int),
        ZLB_INIT(LDD_FLAGS_PROP,     ldd_flags,      int),
        ZLB_INIT(LDD_INDEX_PROP,     ldd_svindex,    int),
        ZLB_INIT(LDD_FSNAME_PROP,    ldd_fsname,     str),
        ZLB_INIT(LDD_SVNAME_PROP,    ldd_svname,     str),
        ZLB_INIT(LDD_UUID_PROP,      ldd_uuid,       str),
        ZLB_INIT(LDD_USERDATA_PROP,  ldd_userdata,   str),
        ZLB_INIT(LDD_MOUNTOPTS_PROP, ldd_mount_opts, str),
        { NULL }
}
Definition at line 89 of file mount_utils_zfs.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.