Lustre: lustre/utils/mount_utils.c File Reference
lustre/utils/mount_utils.c File Reference
#include <inttypes.h>
#include <limits.h>
#include <mntent.h>
#include <stdio.h>
#include <errno.h>
#include <string.h>
#include <unistd.h>
#include <config.h>
#include <lustre_disk.h>
#include <lustre_ver.h>
#include <sys/mount.h>
#include <sys/stat.h>
#include <sys/utsname.h>
#include <linux/loop.h>
#include <dlfcn.h>
#include "mount_utils.h"
Defines
#define vprint(fmt, arg...) if (verbose > 0) printf(fmt, ##arg)
#define verrprint(fmt, arg...) if (verbose >= 0) fprintf(stderr, fmt, ##arg)
#define PROC_DIR "/proc/"
#define DLSYM(prefix, sym, func)
Functions
void fatal (void)
int run_command (char *cmd, int cmdsz)
int add_param (char *buf, char *key, char *val)
int get_param (char *buf, char *key, char **val)
int append_param (char *buf, char *key, char *val, char sep)
char * strscat (char *dst, char *src, int buflen)
char * strscpy (char *dst, char *src, int buflen)
int check_mtab_entry (char *spec1, char *spec2, char *mtpt, char *type)
static int mtab_is_proc (const char *mtab)
int update_utab_entry (struct mount_opts *mop)
int update_mtab_entry (char *spec, char *mtpt, char *type, char *opts, int flags, int freq, int pass)
static int in_mntlist (char *opt, char *mntlist)
int check_mountfsoptions (char *mountopts, char *wanted_mountopts)
void trim_mountfsoptions (char *s)
int loop_setup (struct mkfs_opts *mop)
int loop_cleanup (struct mkfs_opts *mop)
int loop_format (struct mkfs_opts *mop)
struct module_backfs_ops * load_backfs_module (enum ldd_mount_type mount_type)
Load plugin for a given mount_type from ${pkglibdir}/mount_osd_FSTYPE.so and return struct of function pointers (will be freed in unloack_backfs_module).
void unload_backfs_module (struct module_backfs_ops *ops)
Unload plugin and free backfs_ops structure.
int backfs_mount_type_okay (enum ldd_mount_type mount_type)
int osd_write_ldd (struct mkfs_opts *mop)
int osd_read_ldd (char *dev, struct lustre_disk_data *ldd)
int osd_is_lustre (char *dev, unsigned *mount_type)
int osd_make_lustre (struct mkfs_opts *mop)
int osd_prepare_lustre (struct mkfs_opts *mop, char *wanted_mountopts, size_t len)
int osd_fix_mountopts (struct mkfs_opts *mop, char *mountopts, size_t len)
int osd_tune_lustre (char *dev, struct mount_opts *mop)
int osd_label_lustre (struct mount_opts *mop)
int osd_enable_quota (struct mkfs_opts *mop)
int osd_init (void)
void osd_fini (void)
__u64 get_device_size (char *device)
int file_create (char *path, __u64 size)
Variables
char * progname
int verbose
static struct module_backfs_ops * backfs_ops [LDD_MT_LAST]
Define Documentation
#define DLSYM (prefix, sym, func)
Value:
do {                                                            \
                char _fname[64];                                        \
                snprintf(_fname, sizeof(_fname), "%s_%s", prefix, #func); \
                sym->func = (typeof(sym->func))dlsym(sym->dl_handle, _fname); \
        } while (0)
Definition at line 519 of file mount_utils.c.
Referenced by load_backfs_module().
#define PROC_DIR "/proc/"
Definition at line 231 of file mount_utils.c.
Referenced by mtab_is_proc().
#define verrprint (fmt, arg...) if (verbose >= 0) fprintf(stderr, fmt, ##arg)
Definition at line 63 of file mount_utils.c.
Referenced by ldiskfs_read_ldd(), and main().
#define vprint (fmt, arg...) if (verbose > 0) printf(fmt, ##arg)
Definition at line 62 of file mount_utils.c.
Referenced by get_device_size(), ldiskfs_enable_quota(), ldiskfs_make_lustre(), ldiskfs_read_ldd(), ldiskfs_write_ldd(), osd_is_lustre(), zfs_make_lustre(), zfs_set_prop_int(), zfs_set_prop_params(), zfs_set_prop_str(), and zfs_write_ldd().
Function Documentation
int add_param (char * buf, char * key, char * val)
Definition at line 114 of file mount_utils.c.
References end, progname, and start.
int append_param (char * buf, char * key, char * val, char sep)
Definition at line 154 of file mount_utils.c.
References add_param().
Referenced by parse_opts().
int backfs_mount_type_okay (enum ldd_mount_type mount_type)
Definition at line 619 of file mount_utils.c.
References fatal(), LDD_MT_LAST, mt_str(), and unlikely.
Referenced by osd_enable_quota(), osd_fix_mountopts(), osd_label_lustre(), osd_make_lustre(), osd_prepare_lustre(), osd_read_ldd(), osd_tune_lustre(), and osd_write_ldd().
int check_mountfsoptions (char * mountopts, char * wanted_mountopts)
Definition at line 350 of file mount_utils.c.
References errors, in_mntlist(), and progname.
Referenced by main().
int check_mtab_entry (char * spec1, char * spec2, char * mtpt, char * type)
Definition at line 208 of file mount_utils.c.
Referenced by main().
void fatal (void)
Definition at line 67 of file mount_utils.c.
References progname, and verbose.
int file_create (char * path, __u64 size)
Definition at line 832 of file mount_utils.c.
References __u64, _FILE_OFFSET_BITS, fatal(), progname, and ret.
Referenced by zfs_create_vdev().
__u64 get_device_size (char * device)
Definition at line 797 of file mount_utils.c.
References __u64, progname, ret, size, and vprint.
Referenced by ldiskfs_make_lustre().
int get_param (char * buf, char * key, char ** val)
Definition at line 132 of file mount_utils.c.
static int in_mntlist (char * opt, char * mntlist) [static]
Definition at line 328 of file mount_utils.c.
References progname.
Referenced by check_mountfsoptions().
struct module_backfs_ops* load_backfs_module (enum ldd_mount_type mount_type) [read]
Load plugin for a given mount_type from ${pkglibdir}/mount_osd_FSTYPE.so and return struct of function pointers (will be freed in unloack_backfs_module).
Parameters:
[in] mount_type Mount type to load module for.
Return values:
Value of backfs_ops struct
NULL if no module exists
Definition at line 534 of file mount_utils.c.
References module_backfs_ops::dl_handle, DLSYM, module_backfs_ops::enable_quota, error, fatal(), filename, module_backfs_ops::fini, module_backfs_ops::fix_mountopts, module_backfs_ops::init, module_backfs_ops::is_lustre, module_backfs_ops::label_lustre, module_backfs_ops::make_lustre, mt_type(), name, module_backfs_ops::prepare_lustre, module_backfs_ops::read_ldd, module_backfs_ops::tune_lustre, and module_backfs_ops::write_ldd.
Referenced by osd_init().
int loop_cleanup (struct mkfs_opts * mop)
Definition at line 465 of file mount_utils.c.
References cmd, mkfs_opts::mo_flags, MO_IS_LOOP, mkfs_opts::mo_loopdev, ret, and run_command().
Referenced by clear_update_ondisk(), and main().
int loop_format (struct mkfs_opts * mop)
Definition at line 488 of file mount_utils.c.
References fatal(), mkfs_opts::mo_device, mkfs_opts::mo_device_kb, and progname.
Referenced by main().
int loop_setup (struct mkfs_opts * mop)
Definition at line 395 of file mount_utils.c.
References cmd, MAX_LOOP_DEVICES, mkfs_opts::mo_device, mkfs_opts::mo_loopdev, progname, ret, run_command(), and strscpy().
Referenced by clear_update_ondisk(), and main().
static int mtab_is_proc (const char * mtab) [static]
Definition at line 232 of file mount_utils.c.
References path, and PROC_DIR.
Referenced by update_mtab_entry().
int osd_enable_quota (struct mkfs_opts * mop)
Definition at line 751 of file mount_utils.c.
References backfs_mount_type_okay(), module_backfs_ops::enable_quota, lustre_disk_data::ldd_mount_type, mkfs_opts::mo_ldd, and ret.
Referenced by main().
void osd_fini (void)
Definition at line 784 of file mount_utils.c.
References module_backfs_ops::fini, LDD_MT_LAST, and unload_backfs_module().
Referenced by main().
int osd_fix_mountopts (struct mkfs_opts * mop, char * mountopts, size_t len)
Definition at line 710 of file mount_utils.c.
References backfs_mount_type_okay(), module_backfs_ops::fix_mountopts, lustre_disk_data::ldd_mount_type, and mkfs_opts::mo_ldd.
Referenced by main().
int osd_init (void)
Definition at line 764 of file mount_utils.c.
References module_backfs_ops::fini, module_backfs_ops::init, LDD_MT_LAST, load_backfs_module(), ret, and unload_backfs_module().
int osd_is_lustre (char * dev, unsigned * mount_type)
Definition at line 663 of file mount_utils.c.
References LDD_MT_LAST, and vprint.
Referenced by main(), and parse_ldd().
int osd_label_lustre (struct mount_opts * mop)
Definition at line 737 of file mount_utils.c.
References backfs_mount_type_okay(), module_backfs_ops::label_lustre, lustre_disk_data::ldd_mount_type, mount_opts::mo_ldd, and ret.
Referenced by main().
int osd_make_lustre (struct mkfs_opts * mop)
Definition at line 682 of file mount_utils.c.
References backfs_mount_type_okay(), lustre_disk_data::ldd_mount_type, module_backfs_ops::make_lustre, mkfs_opts::mo_ldd, and ret.
Referenced by main().
int osd_prepare_lustre (struct mkfs_opts * mop, char * wanted_mountopts, size_t len)
Definition at line 695 of file mount_utils.c.
References backfs_mount_type_okay(), lustre_disk_data::ldd_mount_type, mkfs_opts::mo_ldd, module_backfs_ops::prepare_lustre, and ret.
Referenced by clear_update_ondisk(), and main().
int osd_read_ldd (char * dev, struct lustre_disk_data * ldd)
Definition at line 650 of file mount_utils.c.
References backfs_mount_type_okay(), lustre_disk_data::ldd_mount_type, module_backfs_ops::read_ldd, and ret.
Referenced by main(), and parse_ldd().
int osd_tune_lustre (char * dev, struct mount_opts * mop)
Definition at line 724 of file mount_utils.c.
References backfs_mount_type_okay(), lustre_disk_data::ldd_mount_type, mount_opts::mo_ldd, ret, and module_backfs_ops::tune_lustre.
Referenced by main().
int osd_write_ldd (struct mkfs_opts * mop)
Definition at line 636 of file mount_utils.c.
References backfs_mount_type_okay(), lustre_disk_data::ldd_mount_type, mkfs_opts::mo_ldd, ret, and module_backfs_ops::write_ldd.
Referenced by clear_update_ondisk(), and main().
int run_command (char * cmd, int cmdsz)
Definition at line 73 of file mount_utils.c.
References buf, fatal(), and verbose.
char* strscat (char * dst, char * src, int buflen)
Definition at line 191 of file mount_utils.c.
Referenced by append_unique(), enable_default_ext4_features(), ldiskfs_fix_mountopts(), ldiskfs_make_lustre(), ldiskfs_prepare_lustre(), strscpy(), and zfs_make_lustre().
char* strscpy (char * dst, char * src, int buflen)
Definition at line 202 of file mount_utils.c.
References strscat().
Referenced by loop_setup(), main(), and parse_opts().
void trim_mountfsoptions (char * s)
Definition at line 374 of file mount_utils.c.
Referenced by main().
void unload_backfs_module (struct module_backfs_ops * ops)
Unload plugin and free backfs_ops structure.
Must be called the same number of times as load_backfs_module is.
Definition at line 609 of file mount_utils.c.
References module_backfs_ops::dl_handle.
Referenced by osd_fini(), and osd_init().
int update_mtab_entry (char * spec, char * mtpt, char * type, char * opts, int flags, int freq, int pass)
Definition at line 291 of file mount_utils.c.
References mtab_is_proc(), and progname.
Referenced by main().
int update_utab_entry (struct mount_opts * mop)
Definition at line 285 of file mount_utils.c.
Referenced by main().
Variable Documentation
struct module_backfs_ops* backfs_ops[LDD_MT_LAST] [static]
Definition at line 65 of file mount_utils.c.
char* progname
Definition at line 69 of file lr_reader.c.
int verbose
Definition at line 57 of file lp_utils.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.