Lustre: lustre/utils/mount_utils_ldiskfs.c File Reference
lustre/utils/mount_utils_ldiskfs.c File Reference
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <inttypes.h>
#include <unistd.h>
#include <fcntl.h>
#include <mntent.h>
#include <glob.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/mount.h>
#include <sys/utsname.h>
#include <getopt.h>
#include <limits.h>
#include <ctype.h>
#include <linux/fs.h>
#include <linux/version.h>
#include <lustre_disk.h>
#include <lustre_param.h>
#include <lnet/lnetctl.h>
#include <lustre_ver.h>
#include "mount_utils.h"
Defines
#define MAX_HW_SECTORS_KB_PATH "queue/max_hw_sectors_kb"
#define MAX_SECTORS_KB_PATH "queue/max_sectors_kb"
#define SCHEDULER_PATH "queue/scheduler"
#define STRIPE_CACHE_SIZE "md/stripe_cache_size"
#define DEFAULT_SCHEDULER "deadline"
#define L_BLOCK_SIZE 4096
#define DUMMY_FILE_NAME_LEN 25
#define EXT3_DIRENT_SIZE DUMMY_FILE_NAME_LEN
Functions
static void append_unique (char *buf, char *prefix, char *key, char *val, size_t maxbuflen)
append_unique: append or = pair to only if does not exists : buffer to hold or = : prefix string before : key string : value string if it's a = pair
static char * absolute_path (char *devname)
static int is_block (char *devname)
static int is_feature_enabled (const char *feature, const char *devpath)
int ldiskfs_write_ldd (struct mkfs_opts *mop)
static int readcmd (char *cmd, char *buf, int len)
int ldiskfs_read_ldd (char *dev, struct lustre_disk_data *mo_ldd)
static void disp_old_e2fsprogs_msg (const char *feature, int make_backfs)
static int file_in_dev (char *file_name, char *dev_name)
int ldiskfs_is_lustre (char *dev, unsigned *mount_type)
static int is_e2fsprogs_feature_supp (const char *feature)
static int enable_default_ext4_features (struct mkfs_opts *mop, char *anchor, size_t maxbuflen, int user_spec)
static char * moveopts_to_end (char *start)
moveopts_to_end: find the option string, move remaining strings to where option string starts, and append the option string at the end : where the option string starts before the move RETURN: where the option string starts after the move
int ldiskfs_make_lustre (struct mkfs_opts *mop)
int ldiskfs_prepare_lustre (struct mkfs_opts *mop, char *wanted_mountopts, size_t len)
int ldiskfs_fix_mountopts (struct mkfs_opts *mop, char *mountopts, size_t len)
static int read_file (const char *path, char *buf, int size)
static int write_file (const char *path, const char *buf)
static int set_blockdev_scheduler (const char *path, const char *scheduler)
static int set_blockdev_tunables (char *source, struct mount_opts *mop)
int ldiskfs_tune_lustre (char *dev, struct mount_opts *mop)
int ldiskfs_label_lustre (struct mount_opts *mop)
int ldiskfs_enable_quota (struct mkfs_opts *mop)
int ldiskfs_init (void)
void ldiskfs_fini (void)
Variables
char * progname
Define Documentation
#define DEFAULT_SCHEDULER "deadline"
Definition at line 90 of file mount_utils_ldiskfs.c.
Referenced by set_blockdev_tunables().
#define DUMMY_FILE_NAME_LEN 25
Definition at line 96 of file mount_utils_ldiskfs.c.
#define EXT3_DIRENT_SIZE DUMMY_FILE_NAME_LEN
Definition at line 97 of file mount_utils_ldiskfs.c.
#define L_BLOCK_SIZE 4096
Definition at line 94 of file mount_utils_ldiskfs.c.
Referenced by enable_default_ext4_features(), and ldiskfs_make_lustre().
#define MAX_HW_SECTORS_KB_PATH "queue/max_hw_sectors_kb"
Definition at line 85 of file mount_utils_ldiskfs.c.
Referenced by set_blockdev_tunables().
#define MAX_SECTORS_KB_PATH "queue/max_sectors_kb"
Definition at line 86 of file mount_utils_ldiskfs.c.
Referenced by set_blockdev_tunables().
#define SCHEDULER_PATH "queue/scheduler"
Definition at line 87 of file mount_utils_ldiskfs.c.
Referenced by set_blockdev_tunables().
#define STRIPE_CACHE_SIZE "md/stripe_cache_size"
Definition at line 88 of file mount_utils_ldiskfs.c.
Referenced by set_blockdev_tunables().
Function Documentation
static char* absolute_path (char * devname) [static]
Definition at line 128 of file mount_utils_ldiskfs.c.
References buf, and path.
Referenced by is_block().
static void append_unique (char * buf, char * prefix, char * key, char * val, size_t maxbuflen) [static]
append_unique: append or = pair to only if does not exists : buffer to hold or = : prefix string before : key string : value string if it's a = pair
Definition at line 538 of file mount_utils_ldiskfs.c.
References end, and strscat().
Referenced by enable_default_ext4_features(), and ldiskfs_make_lustre().
static void disp_old_e2fsprogs_msg (const char * feature, int make_backfs) [static]
Definition at line 398 of file mount_utils_ldiskfs.c.
Referenced by enable_default_ext4_features(), and file_in_dev().
static int enable_default_ext4_features (struct mkfs_opts * mop, char * anchor, size_t maxbuflen, int user_spec) [static]
Definition at line 566 of file mount_utils_ldiskfs.c.
References append_unique(), disp_old_e2fsprogs_msg(), fatal(), is_e2fsprogs_feature_supp(), IS_MDT, IS_OST, L_BLOCK_SIZE, lustre_disk_data::ldd_mount_type, LDD_MT_EXT3, mkfs_opts::mo_device_kb, MO_FAILOVER, mkfs_opts::mo_flags, mkfs_opts::mo_ldd, mkfs_opts::mo_mkfsopts, strscat(), and tmp_buf.
Referenced by ldiskfs_make_lustre().
static int file_in_dev (char * file_name, char * dev_name) [static]
Definition at line 425 of file mount_utils_ldiskfs.c.
References disp_old_e2fsprogs_msg(), and progname.
Referenced by ldiskfs_is_lustre().
static int is_block (char * devname) [static]
Definition at line 178 of file mount_utils_ldiskfs.c.
References absolute_path(), progname, and ret.
Referenced by ldiskfs_prepare_lustre().
static int is_e2fsprogs_feature_supp (const char * feature) [static]
Definition at line 486 of file mount_utils_ldiskfs.c.
References cmd, progname, and ret.
Referenced by enable_default_ext4_features(), ldiskfs_enable_quota(), and ldiskfs_make_lustre().
static int is_feature_enabled (const char * feature, const char * devpath) [static]
Definition at line 215 of file mount_utils_ldiskfs.c.
References cmd, progname, and ret.
Referenced by ldiskfs_enable_quota().
int ldiskfs_enable_quota (struct mkfs_opts * mop)
Definition at line 1315 of file mount_utils_ldiskfs.c.
References cmd, is_e2fsprogs_feature_supp(), is_feature_enabled(), mkfs_opts::mo_device, mkfs_opts::mo_flags, MO_IS_LOOP, mkfs_opts::mo_loopdev, progname, ret, run_command(), and vprint.
void ldiskfs_fini (void)
Definition at line 1354 of file mount_utils_ldiskfs.c.
int ldiskfs_fix_mountopts (struct mkfs_opts * mop, char * mountopts, size_t len)
Definition at line 975 of file mount_utils_ldiskfs.c.
References strscat().
int ldiskfs_init (void)
Definition at line 1346 of file mount_utils_ldiskfs.c.
int ldiskfs_is_lustre (char * dev, unsigned * mount_type)
Definition at line 462 of file mount_utils_ldiskfs.c.
References file_in_dev(), LAST_RCVD, LDD_MT_LDISKFS, MOUNT_DATA_FILE, and ret.
int ldiskfs_label_lustre (struct mount_opts * mop)
Definition at line 1301 of file mount_utils_ldiskfs.c.
References lustre_disk_data::ldd_svname, mount_opts::mo_ldd, mount_opts::mo_source, and run_command().
int ldiskfs_make_lustre (struct mkfs_opts * mop)
Definition at line 683 of file mount_utils_ldiskfs.c.
References __u64, append_unique(), buf, enable_default_ext4_features(), fatal(), get_device_size(), is_e2fsprogs_feature_supp(), IS_MDT, IS_OST, L_BLOCK_SIZE, lustre_disk_data::ldd_mount_type, LDD_MT_EXT3, LDD_MT_LDISKFS, LDD_MT_LDISKFS2, lustre_disk_data::ldd_svname, mkfs_opts::mo_device, mkfs_opts::mo_device_kb, mkfs_opts::mo_flags, MO_IS_LOOP, mkfs_opts::mo_ldd, mkfs_opts::mo_loopdev, mkfs_opts::mo_mkfsopts, mkfs_opts::mo_stripe_count, moveopts_to_end(), MT_STR, progname, ret, run_command(), start, strscat(), verbose, and vprint.
int ldiskfs_prepare_lustre (struct mkfs_opts * mop, char * wanted_mountopts, size_t len)
Definition at line 955 of file mount_utils_ldiskfs.c.
References is_block(), IS_MDT, IS_MGS, mkfs_opts::mo_device, mkfs_opts::mo_flags, MO_IS_LOOP, mkfs_opts::mo_ldd, ret, and strscat().
int ldiskfs_read_ldd (char * dev, struct lustre_disk_data * mo_ldd)
Definition at line 341 of file mount_utils_ldiskfs.c.
References cmd, lustre_disk_data::ldd_svname, MOUNT_CONFIGS_DIR, MOUNT_DATA_FILE, progname, readcmd(), ret, run_command(), verrprint, and vprint.
int ldiskfs_tune_lustre (char * dev, struct mount_opts * mop)
Definition at line 1296 of file mount_utils_ldiskfs.c.
References set_blockdev_tunables().
int ldiskfs_write_ldd (struct mkfs_opts * mop)
Definition at line 243 of file mount_utils_ldiskfs.c.
References mkfs_opts::mo_device, mkfs_opts::mo_flags, MO_IS_LOOP, mkfs_opts::mo_ldd, mkfs_opts::mo_loopdev, mkfs_opts::mo_mountopts, MOUNT_CONFIGS_DIR, MOUNT_DATA_FILE, MT_STR, progname, ret, and vprint.
static char* moveopts_to_end (char * start) [static]
moveopts_to_end: find the option string, move remaining strings to where option string starts, and append the option string at the end : where the option string starts before the move RETURN: where the option string starts after the move
Definition at line 645 of file mount_utils_ldiskfs.c.
References end.
Referenced by ldiskfs_make_lustre().
static int read_file (const char * path, char * buf, int size) [static]
Definition at line 983 of file mount_utils_ldiskfs.c.
Referenced by set_blockdev_scheduler(), and set_blockdev_tunables().
static int readcmd (char * cmd, char * buf, int len) [static]
Definition at line 322 of file mount_utils_ldiskfs.c.
Referenced by ldiskfs_read_ldd().
static int set_blockdev_scheduler (const char * path, const char * scheduler) [static]
Definition at line 1020 of file mount_utils_ldiskfs.c.
References buf, progname, read_file(), verbose, and write_file().
Referenced by set_blockdev_tunables().
static int set_blockdev_tunables (char * source, struct mount_opts * mop) [static]
Definition at line 1074 of file mount_utils_ldiskfs.c.
References buf, DEFAULT_SCHEDULER, end, MAX_HW_SECTORS_KB_PATH, MAX_SECTORS_KB_PATH, mount_opts::mo_md_stripe_cache_size, path, progname, read_file(), SCHEDULER_PATH, set_blockdev_scheduler(), STRIPE_CACHE_SIZE, verbose, and write_file().
Referenced by ldiskfs_tune_lustre().
static int write_file (const char * path, const char * buf) [static]
Definition at line 1006 of file mount_utils_ldiskfs.c.
Referenced by set_blockdev_scheduler(), and set_blockdev_tunables().
Variable Documentation
char* progname
Definition at line 69 of file lr_reader.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.