Lustre: lustre/utils/mount_utils.h File Reference
lustre/utils/mount_utils.h File Reference
#include <ctype.h>
#include <errno.h>
#include <fcntl.h>
#include <limits.h>
#include <stdbool.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <lustre_disk.h>
#include <lustre_param.h>
Data Structures
struct mkfs_opts
struct mount_opts
struct module_backfs_ops
Defines
#define vprint(fmt, arg...) if (verbose > 0) printf(fmt, ##arg)
#define verrprint(fmt, arg...) if (verbose >= 0) fprintf(stderr, fmt, ##arg)
#define MO_IS_LOOP 0x01
#define MO_FORCEFORMAT 0x02
#define MO_FAILOVER 0x04
#define MO_DRYRUN 0x08
#define MO_QUOTA 0x10
#define MAX_LOOP_DEVICES 16
#define INDEX_UNASSIGNED 0xFFFF
#define MT_STR(data) mt_str((data)->ldd_mount_type)
#define IS_MDT(data) ((data)->ldd_flags & LDD_F_SV_TYPE_MDT)
#define IS_OST(data) ((data)->ldd_flags & LDD_F_SV_TYPE_OST)
#define IS_MGS(data) ((data)->ldd_flags & LDD_F_SV_TYPE_MGS)
Functions
int get_mountdata (char *, struct lustre_disk_data *)
void fatal (void)
int run_command_err (char *cmd, int cmdsz, char *error_msg)
int run_command (char *cmd, int cmdsz)
int add_param (char *buf, char *key, char *val)
int append_param (char *buf, char *key, char *val, char sep)
int get_param (char *buf, char *key, char **val)
char * strscat (char *dst, char *src, int buflen)
char * strscpy (char *dst, char *src, int buflen)
int check_mtab_entry (char *spec1, char *spec2, char *mntpt, char *type)
int update_mtab_entry (char *spec, char *mtpt, char *type, char *opts, int flags, int freq, int pass)
int update_utab_entry (struct mount_opts *mop)
int check_mountfsoptions (char *mountopts, char *wanted_mountopts)
void trim_mountfsoptions (char *s)
__u64 get_device_size (char *device)
int file_create (char *path, __u64 size)
int loop_format (struct mkfs_opts *mop)
int loop_setup (struct mkfs_opts *mop)
int loop_cleanup (struct mkfs_opts *mop)
int osd_write_ldd (struct mkfs_opts *mop)
int osd_read_ldd (char *dev, struct lustre_disk_data *ldd)
int osd_is_lustre (char *dev, unsigned *mount_type)
int osd_make_lustre (struct mkfs_opts *mop)
int osd_prepare_lustre (struct mkfs_opts *mop, char *wanted_mountopts, size_t len)
int osd_fix_mountopts (struct mkfs_opts *mop, char *mountopts, size_t len)
int osd_tune_lustre (char *dev, struct mount_opts *mop)
int osd_label_lustre (struct mount_opts *mop)
int osd_enable_quota (struct mkfs_opts *mop)
int osd_init (void)
void osd_fini (void)
struct module_backfs_ops * load_backfs_module (enum ldd_mount_type mount_type)
Load plugin for a given mount_type from ${pkglibdir}/mount_osd_FSTYPE.so and return struct of function pointers (will be freed in unloack_backfs_module).
void unload_backfs_ops (struct module_backfs_ops *ops)
Variables
char * progname
int verbose
int failover
Define Documentation
#define INDEX_UNASSIGNED 0xFFFF
Definition at line 79 of file mount_utils.h.
Referenced by main(), parse_opts(), print_ldd(), and set_defaults().
#define IS_MDT (data) ((data)->ldd_flags & LDD_F_SV_TYPE_MDT)
Definition at line 116 of file mount_utils.h.
#define IS_MGS (data) ((data)->ldd_flags & LDD_F_SV_TYPE_MGS)
Definition at line 120 of file mount_utils.h.
#define IS_OST (data) ((data)->ldd_flags & LDD_F_SV_TYPE_OST)
Definition at line 118 of file mount_utils.h.
#define MAX_LOOP_DEVICES 16
Definition at line 78 of file mount_utils.h.
Referenced by loop_setup().
#define MO_DRYRUN 0x08
Definition at line 75 of file mount_utils.h.
#define MO_FAILOVER 0x04
Definition at line 74 of file mount_utils.h.
Referenced by enable_default_ext4_features(), and parse_opts().
#define MO_FORCEFORMAT 0x02
Definition at line 73 of file mount_utils.h.
Referenced by main(), parse_opts(), and zfs_make_lustre().
#define MO_IS_LOOP 0x01
Definition at line 72 of file mount_utils.h.
Referenced by clear_update_ondisk(), ldiskfs_enable_quota(), ldiskfs_make_lustre(), ldiskfs_prepare_lustre(), ldiskfs_write_ldd(), loop_cleanup(), and main().
#define MO_QUOTA 0x10
Definition at line 76 of file mount_utils.h.
Referenced by main(), and parse_opts().
#define MT_STR (data) mt_str((data)->ldd_mount_type)
Definition at line 113 of file mount_utils.h.
#define verrprint (fmt, arg...) if (verbose >= 0) fprintf(stderr, fmt, ##arg)
Definition at line 69 of file mount_utils.h.
#define vprint (fmt, arg...) if (verbose > 0) printf(fmt, ##arg)
Definition at line 68 of file mount_utils.h.
Function Documentation
int add_param (char * buf, char * key, char * val)
Definition at line 114 of file mount_utils.c.
References end, progname, and start.
int append_param (char * buf, char * key, char * val, char sep)
Definition at line 154 of file mount_utils.c.
References add_param().
Referenced by parse_opts().
int check_mountfsoptions (char * mountopts, char * wanted_mountopts)
Definition at line 350 of file mount_utils.c.
References errors, in_mntlist(), and progname.
Referenced by main().
int check_mtab_entry (char * spec1, char * spec2, char * mntpt, char * type)
Definition at line 208 of file mount_utils.c.
Referenced by main().
void fatal (void)
Definition at line 67 of file mount_utils.c.
References progname, and verbose.
int file_create (char * path, __u64 size)
Definition at line 832 of file mount_utils.c.
References __u64, _FILE_OFFSET_BITS, fatal(), progname, and ret.
Referenced by zfs_create_vdev().
__u64 get_device_size (char * device)
Definition at line 797 of file mount_utils.c.
References __u64, progname, ret, size, and vprint.
Referenced by ldiskfs_make_lustre().
int get_mountdata (char * , struct lustre_disk_data *)
int get_param (char * buf, char * key, char ** val)
Definition at line 132 of file mount_utils.c.
struct module_backfs_ops* load_backfs_module (enum ldd_mount_type mount_type) [read]
Load plugin for a given mount_type from ${pkglibdir}/mount_osd_FSTYPE.so and return struct of function pointers (will be freed in unloack_backfs_module).
Parameters:
[in] mount_type Mount type to load module for.
Return values:
Value of backfs_ops struct
NULL if no module exists
Definition at line 534 of file mount_utils.c.
References module_backfs_ops::dl_handle, DLSYM, module_backfs_ops::enable_quota, error, fatal(), filename, module_backfs_ops::fini, module_backfs_ops::fix_mountopts, module_backfs_ops::init, module_backfs_ops::is_lustre, module_backfs_ops::label_lustre, module_backfs_ops::make_lustre, mt_type(), name, module_backfs_ops::prepare_lustre, module_backfs_ops::read_ldd, module_backfs_ops::tune_lustre, and module_backfs_ops::write_ldd.
Referenced by osd_init().
int loop_cleanup (struct mkfs_opts * mop)
Definition at line 465 of file mount_utils.c.
References cmd, mkfs_opts::mo_flags, MO_IS_LOOP, mkfs_opts::mo_loopdev, ret, and run_command().
Referenced by clear_update_ondisk(), and main().
int loop_format (struct mkfs_opts * mop)
Definition at line 488 of file mount_utils.c.
References fatal(), mkfs_opts::mo_device, mkfs_opts::mo_device_kb, and progname.
Referenced by main().
int loop_setup (struct mkfs_opts * mop)
Definition at line 395 of file mount_utils.c.
References cmd, MAX_LOOP_DEVICES, mkfs_opts::mo_device, mkfs_opts::mo_loopdev, progname, ret, run_command(), and strscpy().
Referenced by clear_update_ondisk(), and main().
int osd_enable_quota (struct mkfs_opts * mop)
Definition at line 751 of file mount_utils.c.
References backfs_mount_type_okay(), module_backfs_ops::enable_quota, lustre_disk_data::ldd_mount_type, mkfs_opts::mo_ldd, and ret.
Referenced by main().
void osd_fini (void)
Definition at line 784 of file mount_utils.c.
References module_backfs_ops::fini, LDD_MT_LAST, and unload_backfs_module().
Referenced by main().
int osd_fix_mountopts (struct mkfs_opts * mop, char * mountopts, size_t len)
Definition at line 710 of file mount_utils.c.
References backfs_mount_type_okay(), module_backfs_ops::fix_mountopts, lustre_disk_data::ldd_mount_type, and mkfs_opts::mo_ldd.
Referenced by main().
int osd_init (void)
Definition at line 764 of file mount_utils.c.
References module_backfs_ops::fini, module_backfs_ops::init, LDD_MT_LAST, load_backfs_module(), ret, and unload_backfs_module().
int osd_is_lustre (char * dev, unsigned * mount_type)
Definition at line 663 of file mount_utils.c.
References LDD_MT_LAST, and vprint.
Referenced by main(), and parse_ldd().
int osd_label_lustre (struct mount_opts * mop)
Definition at line 737 of file mount_utils.c.
References backfs_mount_type_okay(), module_backfs_ops::label_lustre, lustre_disk_data::ldd_mount_type, mount_opts::mo_ldd, and ret.
Referenced by main().
int osd_make_lustre (struct mkfs_opts * mop)
Definition at line 682 of file mount_utils.c.
References backfs_mount_type_okay(), lustre_disk_data::ldd_mount_type, module_backfs_ops::make_lustre, mkfs_opts::mo_ldd, and ret.
Referenced by main().
int osd_prepare_lustre (struct mkfs_opts * mop, char * wanted_mountopts, size_t len)
Definition at line 695 of file mount_utils.c.
References backfs_mount_type_okay(), lustre_disk_data::ldd_mount_type, mkfs_opts::mo_ldd, module_backfs_ops::prepare_lustre, and ret.
Referenced by clear_update_ondisk(), and main().
int osd_read_ldd (char * dev, struct lustre_disk_data * ldd)
Definition at line 650 of file mount_utils.c.
References backfs_mount_type_okay(), lustre_disk_data::ldd_mount_type, module_backfs_ops::read_ldd, and ret.
Referenced by main(), and parse_ldd().
int osd_tune_lustre (char * dev, struct mount_opts * mop)
Definition at line 724 of file mount_utils.c.
References backfs_mount_type_okay(), lustre_disk_data::ldd_mount_type, mount_opts::mo_ldd, ret, and module_backfs_ops::tune_lustre.
Referenced by main().
int osd_write_ldd (struct mkfs_opts * mop)
Definition at line 636 of file mount_utils.c.
References backfs_mount_type_okay(), lustre_disk_data::ldd_mount_type, mkfs_opts::mo_ldd, ret, and module_backfs_ops::write_ldd.
Referenced by clear_update_ondisk(), and main().
int run_command (char * cmd, int cmdsz)
Definition at line 73 of file mount_utils.c.
References buf, fatal(), and verbose.
int run_command_err (char * cmd, int cmdsz, char * error_msg)
char* strscat (char * dst, char * src, int buflen)
Definition at line 191 of file mount_utils.c.
Referenced by append_unique(), enable_default_ext4_features(), ldiskfs_fix_mountopts(), ldiskfs_make_lustre(), ldiskfs_prepare_lustre(), strscpy(), and zfs_make_lustre().
char* strscpy (char * dst, char * src, int buflen)
Definition at line 202 of file mount_utils.c.
References strscat().
Referenced by loop_setup(), main(), and parse_opts().
void trim_mountfsoptions (char * s)
Definition at line 374 of file mount_utils.c.
Referenced by main().
void unload_backfs_ops (struct module_backfs_ops * ops)
int update_mtab_entry (char * spec, char * mtpt, char * type, char * opts, int flags, int freq, int pass)
Definition at line 291 of file mount_utils.c.
References mtab_is_proc(), and progname.
Referenced by main().
int update_utab_entry (struct mount_opts * mop)
Definition at line 285 of file mount_utils.c.
Referenced by main().
Variable Documentation
int failover
Referenced by jt_obd_cleanup().
char* progname
Definition at line 69 of file lr_reader.c.
int verbose
Definition at line 57 of file lp_utils.c.
Referenced by begin(), dir_read(), dir_write(), end(), fatal(), get_verbose(), jt_lst_list_batch(), jt_lst_list_group(), jt_lst_query_batch(), ldiskfs_make_lustre(), lr_parse_line(), lr_print_status(), lr_replicate(), main(), parse_opts(), process_args(), read_chunks(), run_command(), set_blockdev_scheduler(), set_blockdev_tunables(), show_rate(), sizeof_dev(), and write_chunks().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.