Lustre: lustre/tests/mpi/lp_utils.h File Reference
lustre/tests/mpi/lp_utils.h File Reference
#include "lustre/lustre_user.h"
Defines
#define FAIL(msg)
#define FILEMODE S_IRUSR|S_IWUSR|S_IRGRP|S_IWGRP|S_IROTH
#define MAX_FILENAME_LEN 512
#define LP_STAT_FMT
#define LP_STAT_ARGS
Functions
char * timestamp ()
void begin (char *str)
void end (char *str)
void dump_diff (char *orig_buf, char *buf, int len, long off)
void lp_gethostname (void)
void create_file (char *name, long filesize, int fill)
void fill_file (char *name, long filesize)
void check_stat (char *filename, struct stat *state, struct stat *old_state)
void remove_file (char *name)
void remove_file_or_dir (char *name)
void fill_stride (char *buf, int buf_size, long long rank, long long _off)
Variables
int verbose
int debug
int rank
int size
char hostname []
char * testdir
Define Documentation
#define FAIL (msg)
Value:
\
do { \
        printf("%s: Process %d (%s)\n", timestamp(), rank, hostname); \
        if (debug) \
                printf("\tFAILED in %s:%d:%s()\n", __FILE__, __LINE__, __func__); \
        else \
                printf("\tFAILED in %s()\n", __func__); \
        printf("%s", msg); \
        fflush(stdout); \
        MPI_Abort(MPI_COMM_WORLD, 1); \
} while(0)
Definition at line 44 of file lp_utils.h.
#define FILEMODE S_IRUSR|S_IWUSR|S_IRGRP|S_IWGRP|S_IROTH
Definition at line 57 of file lp_utils.h.
#define LP_STAT_ARGS
Value:
\
(int)state->st_dev, (int)old_state->st_dev, \
(int)state->st_ino, (int)old_state->st_ino, \
state->st_mode & 07777, old_state->st_mode & 07777, \
(int)state->st_nlink, (int)old_state->st_nlink, \
state->st_uid, old_state->st_uid, \
state->st_gid, old_state->st_gid, \
(int)((state->st_rdev >> 8) & 0xff), (int)(state->st_rdev & 0xff), \
(int)((old_state->st_rdev >> 8) & 0xff), (int)(old_state->st_rdev & 0xff), \
(unsigned long)state->st_size, (unsigned long)old_state->st_size, \
(int)state->st_blksize, (int)old_state->st_blksize, \
(unsigned int)state->st_blocks, (unsigned int)old_state->st_blocks, \
(int)state->st_atime, (int)old_state->st_atime, \
(int)state->st_mtime, (int)old_state->st_mtime, \
(int)state->st_ctime, (int)old_state->st_ctime
Definition at line 97 of file lp_utils.h.
#define LP_STAT_FMT
Value:
\
"Stat error:\n \\tfields\t\tvalue\told value\n \\tst_dev\t\t%d\t%d\n \\tst_ino\t\t%d\t%d\n \\tst_mode\t\t%o\t%o\n \\tst_nlink\t%d\t%d\n \\tst_uid\t\t%d\t%d\n \\tst_gid\t\t%d\t%d\n \\tst_rdev\t\t%x.%x\t%x.%x\n \\tst_size\t\t%lu\t%lu\n \\tst_blksize\t%d\t%d\n \\tst_blocks\t%u\t%u\n \\tst_atime\t%d\t%d\n \\tst_mtime\t%d\t%d\n \\tst_ctime\t%d\t%d\n"
Definition at line 79 of file lp_utils.h.
#define MAX_FILENAME_LEN 512
Definition at line 58 of file lp_utils.h.
Function Documentation
void begin (char * str) [inline]
Definition at line 75 of file lp_utils.c.
References rank, t1(), timestamp(), and verbose.
void check_stat (char * filename, struct stat * state, struct stat * old_state)
Definition at line 236 of file lp_utils.c.
References errmsg, FAIL, LP_STAT_ARGS, LP_STAT_FMT, and MAX_FILENAME_LEN.
void create_file (char * name, long filesize, int fill)
Definition at line 181 of file lp_utils.c.
References buf, errmsg, FAIL, FILEMODE, filename, MAX_FILENAME_LEN, rank, remove_file_or_dir(), size, and testdir.
void dump_diff (char * orig_buf, char * buf, int len, long off)
Definition at line 103 of file lp_utils.c.
References end.
Referenced by rw_file().
void end (char * str) [inline]
Definition at line 83 of file lp_utils.c.
References rank, t1(), t2, timestamp(), and verbose.
void fill_file (char * name, long filesize)
void fill_stride (char * buf, int buf_size, long long rank, long long _off)
Definition at line 267 of file lp_utils.c.
Referenced by rw_file().
void lp_gethostname (void)
Definition at line 146 of file lp_utils.c.
References hostname.
Referenced by main().
void remove_file (char * name)
Definition at line 252 of file lp_utils.c.
References errmsg, FAIL, filename, MAX_FILENAME_LEN, rank, and testdir.
Referenced by cascading_rw().
void remove_file_or_dir (char * name)
Definition at line 158 of file lp_utils.c.
References errmsg, FAIL, and MAX_FILENAME_LEN.
Referenced by create_file(), and rw_file().
char* timestamp ()
Definition at line 64 of file lp_utils.c.
References timestamp().
Referenced by begin(), end(), kgnilnd_check_fma_rx(), kgnilnd_rdma(), kgnilnd_release_msg(), kgnilnd_sendmsg(), kgnilnd_sendmsg_trylock(), main(), and timestamp().
Variable Documentation
int debug
Definition at line 129 of file fsx.c.
Referenced by docloseopen(), domapread(), domapwrite(), doread(), dotruncate(), dowrite(), lr_debug(), lr_replicate(), main(), output_line(), process_args(), and test().
char hostname[]
Definition at line 60 of file lp_utils.c.
Referenced by lp_gethostname(), main(), process_args(), and rprintf().
int rank
Definition at line 60 of file cascading_rw.c.
int size
Definition at line 61 of file cascading_rw.c.
char* testdir
Definition at line 63 of file cascading_rw.c.
int verbose
Definition at line 57 of file lp_utils.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.