Lustre: lustre/llite/namei.c File Reference
lustre/llite/namei.c File Reference
#include <linux/fs.h>
#include <linux/sched.h>
#include <linux/mm.h>
#include <linux/quotaops.h>
#include <linux/highmem.h>
#include <linux/pagemap.h>
#include <linux/security.h>
#include <linux/user_namespace.h>
#include <obd_support.h>
#include <lustre_fid.h>
#include <lustre_dlm.h>
#include <lustre_ver.h>
#include "llite_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LLITE
Functions
static int ll_create_it (struct inode *dir, struct dentry *dentry, struct lookup_intent *it)
static int ll_test_inode (struct inode *inode, void *opaque)
static int ll_set_inode (struct inode *inode, void *opaque)
struct inode * ll_iget (struct super_block *sb, ino_t hash, struct lustre_md *md)
Get an inode by inode number(), which is already instantiated by the intent lookup).
static void ll_invalidate_negative_children (struct inode *dir)
int ll_test_inode_by_fid (struct inode *inode, void *opaque)
int ll_md_blocking_ast (struct ldlm_lock *lock, struct ldlm_lock_desc *desc, void *data, int flag)
__u32 ll_i2suppgid (struct inode *i)
void ll_i2gids (__u32 *suppgids, struct inode *i1, struct inode *i2)
static struct dentry * ll_find_alias (struct inode *inode, struct dentry *dentry)
struct dentry * ll_splice_alias (struct inode *inode, struct dentry *de)
static int ll_lookup_it_finish (struct ptlrpc_request *request, struct lookup_intent *it, struct inode *parent, struct dentry **de)
static struct dentry * ll_lookup_it (struct inode *parent, struct dentry *dentry, struct lookup_intent *it)
static struct lookup_intent * ll_convert_intent (struct open_intent *oit, int lookup_flags)
static struct dentry * ll_lookup_nd (struct inode *parent, struct dentry *dentry, struct nameidata *nd)
static struct inode * ll_create_node (struct inode *dir, struct lookup_intent *it)
void ll_update_times (struct ptlrpc_request *request, struct inode *inode)
static int ll_new_node (struct inode *dir, struct dentry *dchild, const char *tgt, umode_t mode, int rdev, __u32 opc)
static int ll_mknod (struct inode *dir, struct dentry *dchild, ll_umode_t mode, dev_t rdev)
static int ll_create_nd (struct inode *dir, struct dentry *dentry, ll_umode_t mode, struct nameidata *nd)
static int ll_symlink (struct inode *dir, struct dentry *dchild, const char *oldpath)
static int ll_link (struct dentry *old_dentry, struct inode *dir, struct dentry *new_dentry)
static int ll_mkdir (struct inode *dir, struct dentry *dchild, ll_umode_t mode)
static int ll_rmdir (struct inode *dir, struct dentry *dchild)
int ll_rmdir_entry (struct inode *dir, char *name, int namelen)
Remove dir entry.
static int ll_unlink (struct inode *dir, struct dentry *dchild)
static int ll_rename (struct inode *src, struct dentry *src_dchild, struct inode *tgt, struct dentry *tgt_dchild)
Variables
struct inode_operations ll_dir_inode_operations
struct inode_operations ll_special_inode_operations
Define Documentation
#define DEBUG_SUBSYSTEM S_LLITE
Definition at line 49 of file namei.c.
Function Documentation
static struct lookup_intent* ll_convert_intent (struct open_intent * oit, int lookup_flags) [static, read]
Definition at line 762 of file namei.c.
References IT_CREAT, lookup_intent::it_create_mode, lookup_intent::it_flags, IT_GETATTR, lookup_intent::it_op, IT_OPEN, ll_namei_to_lookup_intent_flag(), MDS_OPEN_FL_INTERNAL, and OBD_ALLOC_PTR.
Referenced by ll_lookup_nd().
static int ll_create_it (struct inode * dir, struct dentry * dentry, struct lookup_intent * it) [static]
Definition at line 899 of file namei.c.
References CDEBUG, D_VFSTRACE, DFID, DISP_OPEN_CREATE, ENTRY, it_open_error(), ll_create_node(), ll_init_security(), ll_inode2fid(), LL_IT2STR, PFID, and RETURN.
Referenced by ll_create_nd().
static int ll_create_nd (struct inode * dir, struct dentry * dentry, ll_umode_t mode, struct nameidata * nd) [static]
Definition at line 1090 of file namei.c.
References lookup_intent::it_status, ll_create_it(), ll_d2d, ll_i2sbi(), ll_intent_release(), ll_mknod(), ll_stats_ops_tally(), ll_dentry_data::lld_it, LPROC_LL_CREATE, and OBD_FREE.
static struct inode* ll_create_node (struct inode * dir, struct lookup_intent * it) [static, read]
Definition at line 854 of file namei.c.
References CDEBUG, D_DLMTRACE, DFID, DISP_ENQ_CREATE_REF, ENTRY, EXIT, GOTO, it_clear_disposition(), it_disposition(), lookup_intent::it_disposition, lookup_intent::it_request, LASSERT, ll_d_hlist_empty, ll_i2sbi(), ll_inode2fid(), ll_sb_info::ll_md_exp, ll_prep_inode(), ll_set_lock_data(), PFID, and ptlrpc_req_finished().
Referenced by ll_create_it().
static struct dentry* ll_find_alias (struct inode * inode, struct dentry * dentry) [static, read]
Definition at line 387 of file namei.c.
References DECLARE_LL_D_HLIST_NODE_PTR, LASSERT, ll_d_hlist_empty, ll_d_hlist_for_each_entry, ll_lock_dcache(), and ll_unlock_dcache().
Referenced by ll_splice_alias().
void ll_i2gids (__u32 * suppgids, struct inode * i1, struct inode * i2)
Definition at line 366 of file namei.c.
References LASSERT, and ll_i2suppgid().
Referenced by ll_prep_md_op_data().
__u32 ll_i2suppgid (struct inode * i)
Definition at line 354 of file namei.c.
References __kgid_val(), from_kgid(), and INVALID_GID.
Referenced by ll_i2gids(), ll_setxattr_common(), and lustre_check_remote_perm().
struct inode* ll_iget (struct super_block * sb, ino_t hash, struct lustre_md * md) [read]
Get an inode by inode number(), which is already instantiated by the intent lookup).
Definition at line 111 of file namei.c.
References lustre_md::body, CDEBUG, cl_file_inode_init(), D_VFSTRACE, DFID, ENTRY, LASSERT, ll_dir_clear_lsm_md(), ll_i2info(), ll_read_inode2(), ll_set_inode(), ll_test_inode(), ll_update_inode(), mdt_body::mbo_fid1, PFID, and RETURN.
Referenced by client_common_fill_super(), and ll_prep_inode().
static void ll_invalidate_negative_children (struct inode * dir) [static]
Definition at line 159 of file namei.c.
References d_child, d_lustre_invalidate(), DECLARE_LL_D_HLIST_NODE_PTR, list_empty(), list_for_each_entry_safe, ll_d_hlist_for_each_entry, ll_lock_dcache(), and ll_unlock_dcache().
Referenced by ll_md_blocking_ast().
static int ll_link (struct dentry * old_dentry, struct inode * dir, struct dentry * new_dentry) [static]
Definition at line 1152 of file namei.c.
References CDEBUG, D_VFSTRACE, DFID, ENTRY, EXIT, GOTO, ll_finish_md_op_data(), ll_i2sbi(), ll_inode2fid(), ll_sb_info::ll_md_exp, ll_prep_md_op_data(), ll_stats_ops_tally(), ll_update_times(), LPROC_LL_LINK, LUSTRE_OPC_ANY, md_link(), name, md_op_data::op_data, PFID, ptlrpc_req_finished(), and RETURN.
static struct dentry* ll_lookup_it (struct inode * parent, struct dentry * dentry, struct lookup_intent * it) [static, read]
Definition at line 551 of file namei.c.
References CDEBUG, CERROR, D_VFSTRACE, dentry_may_statahead(), DFID, DISP_OPEN_DENY, ENTRY, exp_connect_umask(), fid_zero(), FMODE_WRITE, GOTO, IT_CREAT, lookup_intent::it_create_mode, it_disposition(), lookup_intent::it_flags, IT_GETATTR, IT_GETXATTR, IT_LOOKUP, lookup_intent::it_op, IT_OPEN, LASSERT, ll_finish_md_op_data(), ll_i2mdexp(), ll_i2sbi(), ll_inode2fid(), ll_intent_release(), LL_IT2STR, ll_lookup_finish_locks(), ll_lookup_it_finish(), ll_md_blocking_ast(), ll_prep_md_op_data(), ll_release_openhandle(), ll_statahead(), LUSTRE_OPC_ANY, LUSTRE_OPC_CREATE, make_kgid(), mdt_body::mbo_gid, md_intent_lock(), md_op_data::op_data, PFID, ptlrpc_req_finished(), req_capsule_server_get(), RETURN, RMF_MDT_BODY, and ptlrpc_request::rq_pill.
Referenced by ll_lookup_nd().
static int ll_lookup_it_finish (struct ptlrpc_request * request, struct lookup_intent * it, struct inode * parent, struct dentry ** de) [static]
Definition at line 461 of file namei.c.
References __u64, CDEBUG, D_DENTRY, d_lustre_revalidate(), DISP_LOOKUP_NEG, DISP_OPEN_CREATE, ENTRY, GOTO, it_disposition(), lookup_intent::it_disposition, IT_GETATTR, lookup_intent::it_op, IT_OPEN, LASSERT, ll_i2info(), ll_i2mdexp(), ll_i2sbi(), ll_intent_release(), ll_open_cleanup(), ll_prep_inode(), ll_set_lock_data(), ll_splice_alias(), ll_inode_info::lli_fid, md_get_fid_from_lsm(), md_revalidate_lock(), MDS_INODELOCK_LOOKUP, RETURN, and unlikely.
Referenced by ll_lookup_it().
static struct dentry* ll_lookup_nd (struct inode * parent, struct dentry * dentry, struct nameidata * nd) [static, read]
Definition at line 784 of file namei.c.
References DISP_OPEN_CREATE, DISP_OPEN_OPEN, ENTRY, it_disposition(), ll_convert_intent(), ll_d2d, ll_intent_release(), ll_lookup_it(), LOOKUP_CONTINUE, OBD_FREE, and RETURN.
int ll_md_blocking_ast (struct ldlm_lock * lock, struct ldlm_lock_desc * desc, void * data, int flag)
Definition at line 187 of file namei.c.
References __u64, ldlm_inodebits::bits, CDEBUG, cl_fid_build_ino(), cl_object_conf::coc_opc, D_INODE, DFID, ENTRY, fid_is_zero(), fid_res_name_eq(), FMODE_EXEC, FMODE_READ, FMODE_WRITE, ldlm_lock::l_ast_data, ldlm_policy_data::l_inodebits, ldlm_lock::l_policy_data, ldlm_lock::l_req_mode, ldlm_lock::l_resource, LASSERT, LBUG, LCF_ASYNC, LCK_CR, LCK_CW, LCK_MINMODE, LCK_PR, LDLM_CB_BLOCKING, LDLM_CB_CANCELING, ldlm_cli_cancel(), LDLM_ERROR, ldlm_is_canceling, ldlm_lock2handle(), ll_have_md_lock(), ll_i2info(), ll_i2sbi(), ll_inode2fid(), ll_inode_from_resource_lock(), ll_invalidate_aliases(), ll_invalidate_negative_children(), ll_layout_conf(), ll_md_real_close(), ll_need_32bit_api(), ll_test_inode_by_fid(), ll_xattr_cache_destroy(), ll_inode_info::lli_def_stripe_offset, ll_inode_info::lli_pfid, ldlm_resource::lr_name, MDS_INODELOCK_LAYOUT, MDS_INODELOCK_LOOKUP, MDS_INODELOCK_OPEN, MDS_INODELOCK_PERM, MDS_INODELOCK_UPDATE, MDS_INODELOCK_XATTR, OBJECT_CONF_INVALIDATE, PFID, RETURN, and unlikely.
Referenced by __ll_inode_revalidate(), ll_get_dir_page(), ll_intent_file_open(), ll_layout_refresh_locked(), ll_lookup_it(), ll_merge_md_attr(), ll_update_lsm_md(), ll_xattr_find_get_lock(), and sa_prep_data().
static int ll_mkdir (struct inode * dir, struct dentry * dchild, ll_umode_t mode) [static]
Definition at line 1185 of file namei.c.
References CDEBUG, D_VFSTRACE, DFID, ENTRY, exp_connect_umask(), ll_i2mdexp(), ll_i2sbi(), ll_inode2fid(), ll_new_node(), ll_stats_ops_tally(), LPROC_LL_MKDIR, LUSTRE_OPC_MKDIR, name, PFID, and RETURN.
static int ll_mknod (struct inode * dir, struct dentry * dchild, ll_umode_t mode, dev_t rdev) [static]
Definition at line 1028 of file namei.c.
References CDEBUG, D_VFSTRACE, DFID, ENTRY, exp_connect_umask(), ll_i2mdexp(), ll_i2sbi(), ll_inode2fid(), ll_new_node(), ll_stats_ops_tally(), LPROC_LL_MKNOD, LUSTRE_OPC_MKNOD, name, PFID, and RETURN.
Referenced by ll_create_nd().
static int ll_new_node (struct inode * dir, struct dentry * dchild, const char * tgt, umode_t mode, int rdev, __u32 opc) [static]
Definition at line 946 of file namei.c.
References cfs_curproc_cap_pack(), ENTRY, EXIT, from_kgid(), from_kuid(), GOTO, ll_dir_getstripe(), ll_finish_md_op_data(), ll_i2info(), ll_i2sbi(), ll_init_security(), ll_sb_info::ll_md_exp, ll_prep_inode(), ll_prep_md_op_data(), ll_update_times(), ll_inode_info::lli_def_stripe_offset, lmv_user_md, md_create(), name, OBD_MD_DEFAULT_MEA, md_op_data::op_data, ptlrpc_req_finished(), and unlikely.
Referenced by ll_mkdir(), ll_mknod(), and ll_symlink().
static int ll_rename (struct inode * src, struct dentry * src_dchild, struct inode * tgt, struct dentry * tgt_dchild) [static]
Definition at line 1312 of file namei.c.
References CDEBUG, D_VFSTRACE, DFID, ENTRY, ll_finish_md_op_data(), ll_i2sbi(), ll_inode2fid(), ll_sb_info::ll_md_exp, ll_prep_md_op_data(), ll_stats_ops_tally(), ll_update_times(), LPROC_LL_RENAME, LUSTRE_OPC_ANY, md_rename(), md_op_data::op_data, md_op_data::op_fid3, md_op_data::op_fid4, PFID, ptlrpc_req_finished(), RETURN, tgt_name(), and unlikely.
static int ll_rmdir (struct inode * dir, struct dentry * dchild) [static]
Definition at line 1206 of file namei.c.
References CDEBUG, D_VFSTRACE, DFID, ENTRY, ll_finish_md_op_data(), ll_i2sbi(), ll_inode2fid(), ll_prep_md_op_data(), ll_stats_ops_tally(), ll_update_times(), LPROC_LL_RMDIR, LUSTRE_OPC_ANY, md_unlink(), name, md_op_data::op_data, md_op_data::op_fid2, md_op_data::op_fid3, PFID, ptlrpc_req_finished(), RETURN, and unlikely.
int ll_rmdir_entry (struct inode * dir, char * name, int namelen)
Remove dir entry.
Definition at line 1243 of file namei.c.
References CDEBUG, CLI_RM_ENTRY, D_VFSTRACE, DFID, ENTRY, ll_finish_md_op_data(), ll_i2sbi(), ll_inode2fid(), ll_prep_md_op_data(), ll_stats_ops_tally(), ll_update_times(), LPROC_LL_RMDIR, LUSTRE_OPC_ANY, md_unlink(), md_op_data::op_cli_flags, md_op_data::op_data, PFID, ptlrpc_req_finished(), and RETURN.
Referenced by ll_dir_ioctl().
static int ll_set_inode (struct inode * inode, void * opaque) [static]
Definition at line 77 of file namei.c.
References CERROR, DFID, ll_i2info(), ll_lli_init(), ll_inode_info::lli_fid, LPX64, mdt_body::mbo_fid1, mdt_body::mbo_mode, mdt_body::mbo_valid, OBD_MD_FLID, OBD_MD_FLTYPE, PFID, and unlikely.
Referenced by ll_iget().
struct dentry* ll_splice_alias (struct inode * inode, struct dentry * de) [read]
Definition at line 431 of file namei.c.
References CDEBUG, D_DENTRY, ll_d_count, ll_d_init(), and ll_find_alias().
Referenced by ll_lookup_it_finish(), and revalidate_statahead_dentry().
static int ll_symlink (struct inode * dir, struct dentry * dchild, const char * oldpath) [static]
Definition at line 1132 of file namei.c.
References CDEBUG, D_VFSTRACE, DFID, ENTRY, ll_i2sbi(), ll_inode2fid(), ll_new_node(), ll_stats_ops_tally(), LPROC_LL_SYMLINK, LUSTRE_OPC_SYMLINK, name, PFID, and RETURN.
static int ll_test_inode (struct inode * inode, void * opaque) [static]
Definition at line 61 of file namei.c.
References lustre_md::body, CERROR, ll_i2info(), ll_inode_info::lli_fid, lu_fid_eq(), mdt_body::mbo_fid1, mdt_body::mbo_valid, OBD_MD_FLID, and unlikely.
Referenced by ll_iget().
int ll_test_inode_by_fid (struct inode * inode, void * opaque)
Definition at line 182 of file namei.c.
References ll_i2info(), and lu_fid_eq().
Referenced by ll_md_blocking_ast(), and search_inode_for_lustre().
static int ll_unlink (struct inode * dir, struct dentry * dchild) [static]
Definition at line 1273 of file namei.c.
References CDEBUG, D_VFSTRACE, DFID, ENTRY, GOTO, ll_finish_md_op_data(), ll_i2sbi(), ll_inode2fid(), ll_prep_md_op_data(), ll_stats_ops_tally(), ll_update_times(), LPROC_LL_UNLINK, LUSTRE_OPC_ANY, md_unlink(), name, md_op_data::op_data, md_op_data::op_fid2, md_op_data::op_fid3, PFID, ptlrpc_req_finished(), RETURN, and unlikely.
void ll_update_times (struct ptlrpc_request * request, struct inode * inode)
Definition at line 927 of file namei.c.
References CDEBUG, D_INODE, DFID, LASSERT, ll_inode2fid(), LPU64, LTIME_S, mdt_body::mbo_ctime, mdt_body::mbo_mtime, mdt_body::mbo_valid, OBD_MD_FLCTIME, OBD_MD_FLMTIME, PFID, req_capsule_server_get(), RMF_MDT_BODY, and ptlrpc_request::rq_pill.
Referenced by ll_link(), ll_migrate(), ll_new_node(), ll_rename(), ll_rmdir(), ll_rmdir_entry(), and ll_unlink().
Variable Documentation
struct inode_operations ll_dir_inode_operations
Initial value:
 {
        .mknod              = ll_mknod,
        .lookup             = ll_lookup_nd,
        .create             = ll_create_nd,
        .unlink             = ll_unlink,
        .mkdir              = ll_mkdir,
        .rmdir              = ll_rmdir,
        .symlink            = ll_symlink,
        .link               = ll_link,
        .rename             = ll_rename,
        .setattr            = ll_setattr,
        .getattr            = ll_getattr,
        .permission         = ll_inode_permission,
        .setxattr           = ll_setxattr,
        .getxattr           = ll_getxattr,
        .listxattr          = ll_listxattr,
        .removexattr        = ll_removexattr,
}
Definition at line 1360 of file namei.c.
Referenced by ll_iget_anon_dir(), and ll_read_inode2().
struct inode_operations ll_special_inode_operations
Initial value:
 {
        .setattr        = ll_setattr,
        .getattr        = ll_getattr,
        .permission     = ll_inode_permission,
        .setxattr       = ll_setxattr,
        .getxattr       = ll_getxattr,
        .listxattr      = ll_listxattr,
        .removexattr    = ll_removexattr,
}
Definition at line 1386 of file namei.c.
Referenced by ll_read_inode2().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.