Lustre: lnet/lnet/net_fault.c File Reference
lnet/lnet/net_fault.c File Reference
#include <lnet/lib-lnet.h>
#include <lnet/lnetctl.h>
Data Structures
struct lnet_drop_rule
struct lnet_delay_rule
struct delay_daemon_data
Defines
#define DEBUG_SUBSYSTEM S_LNET
#define LNET_MSG_MASK
#define msg_delay_send msg_ev.hdr_data
LNet Delay Simulation.
Functions
static bool lnet_fault_nid_match (lnet_nid_t nid, lnet_nid_t msg_nid)
static bool lnet_fault_attr_match (struct lnet_fault_attr *attr, lnet_nid_t src, lnet_nid_t dst, unsigned int type, unsigned int portal)
static int lnet_fault_attr_validate (struct lnet_fault_attr *attr)
static void lnet_fault_stat_inc (struct lnet_fault_stat *stat, unsigned int type)
static int lnet_drop_rule_add (struct lnet_fault_attr *attr)
LNet message drop simulation.
static int lnet_drop_rule_del (lnet_nid_t src, lnet_nid_t dst)
Remove matched drop rules from lnet, all rules that can match src and dst will be removed.
static int lnet_drop_rule_list (int pos, struct lnet_fault_attr *attr, struct lnet_fault_stat *stat)
List drop rule at position of pos.
static void lnet_drop_rule_reset (void)
reset counters for all drop rules
static bool drop_rule_match (struct lnet_drop_rule *rule, lnet_nid_t src, lnet_nid_t dst, unsigned int type, unsigned int portal)
check source/destination NID, portal, message type and drop rate, decide whether should drop this message or not
bool lnet_drop_rule_match (lnet_hdr_t *hdr)
Check if message from src to dst can match any existed drop rule.
static cfs_time_t round_timeout (cfs_time_t timeout)
static void delay_rule_decref (struct lnet_delay_rule *rule)
static bool delay_rule_match (struct lnet_delay_rule *rule, lnet_nid_t src, lnet_nid_t dst, unsigned int type, unsigned int portal, struct lnet_msg *msg)
check source/destination NID, portal, message type and delay rate, decide whether should delay this message or not
bool lnet_delay_rule_match_locked (lnet_hdr_t *hdr, struct lnet_msg *msg)
check if msg can match any Delay Rule, receiving of this message will be delayed if there is a match.
static void delayed_msg_check (struct lnet_delay_rule *rule, bool all, struct list_head *msg_list)
check out delayed messages for send
static void delayed_msg_process (struct list_head *msg_list, bool drop)
void lnet_delay_rule_check (void)
Process delayed messages for scheduled rules This function can either be called by delay_rule_daemon, or by lnet_finalise.
static int lnet_delay_rule_daemon (void *arg)
deamon thread to handle delayed messages
static void delay_timer_cb (unsigned long arg)
int lnet_delay_rule_add (struct lnet_fault_attr *attr)
Add a new delay rule to LNet There is no check for duplicated delay rule, all rules will be checked for incoming message.
int lnet_delay_rule_del (lnet_nid_t src, lnet_nid_t dst, bool shutdown)
Remove matched Delay Rules from lnet, if shutdown is true or both src and dst are zero, all rules will be removed, otherwise only matched rules will be removed.
int lnet_delay_rule_list (int pos, struct lnet_fault_attr *attr, struct lnet_fault_stat *stat)
List Delay Rule at position of pos.
void lnet_delay_rule_reset (void)
reset counters for all Delay Rules
int lnet_fault_ctl (int opc, struct libcfs_ioctl_data *data)
int lnet_fault_init (void)
void lnet_fault_fini (void)
Variables
static struct delay_daemon_data delay_dd
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 37 of file net_fault.c.
#define LNET_MSG_MASK
Value:
(LNET_PUT_BIT | LNET_ACK_BIT | \
                                 LNET_GET_BIT | LNET_REPLY_BIT)
Definition at line 42 of file net_fault.c.
Referenced by lnet_fault_attr_validate().
#define msg_delay_send msg_ev.hdr_data
LNet Delay Simulation.
timestamp (second) to send delayed message
Definition at line 395 of file net_fault.c.
Function Documentation
static void delay_rule_decref (struct lnet_delay_rule * rule) [static]
Definition at line 456 of file net_fault.c.
References CFS_FREE_PTR, lnet_delay_rule::dl_link, lnet_delay_rule::dl_msg_list, lnet_delay_rule::dl_refcount, lnet_delay_rule::dl_sched_link, LASSERT, and list_empty().
Referenced by lnet_delay_rule_check(), and lnet_delay_rule_del().
static bool delay_rule_match (struct lnet_delay_rule * rule, lnet_nid_t src, lnet_nid_t dst, unsigned int type, unsigned int portal, struct lnet_msg * msg) [static]
check source/destination NID, portal, message type and delay rate, decide whether should delay this message or not
Definition at line 472 of file net_fault.c.
References __u64, CDEBUG, cfs_rand(), cfs_time_after(), cfs_time_aftereq(), cfs_time_current(), cfs_time_seconds(), cfs_time_shift(), CFS_TIME_T, D_NET, lnet_fault_stat::delay, lnet_fault_attr::delay, lnet_delay_rule::dl_attr, lnet_delay_rule::dl_delay_at, lnet_delay_rule::dl_delay_time, lnet_delay_rule::dl_lock, lnet_delay_rule::dl_msg_list, lnet_delay_rule::dl_msg_send, lnet_delay_rule::dl_stat, lnet_delay_rule::dl_time_base, lnet_delay_rule::dl_timer, lnet_fault_attr::fa_dst, lnet_fault_attr::fa_src, lnet_fault_stat::fs_count, lnet_fault_attr::la_interval, libcfs_nid2str(), list_add_tail(), lnet_fault_attr_match(), lnet_fault_stat_inc(), lnet_msg::msg_list, now(), round_timeout(), lnet_fault_stat::u, and lnet_fault_attr::u.
Referenced by lnet_delay_rule_match_locked().
static void delay_timer_cb (unsigned long arg) [static]
Definition at line 711 of file net_fault.c.
References delay_daemon_data::dd_lock, delay_daemon_data::dd_running, delay_daemon_data::dd_sched_rules, delay_daemon_data::dd_waitq, delay_dd, lnet_delay_rule::dl_refcount, lnet_delay_rule::dl_sched_link, list_add_tail(), and list_empty().
Referenced by lnet_delay_rule_add().
static void delayed_msg_check (struct lnet_delay_rule * rule, bool all, struct list_head * msg_list) [static]
check out delayed messages for send
Definition at line 574 of file net_fault.c.
References cfs_time_current(), lnet_delay_rule::dl_lock, lnet_delay_rule::dl_msg_list, lnet_delay_rule::dl_msg_send, lnet_delay_rule::dl_timer, list_empty(), list_entry, list_for_each_entry_safe, list_move_tail(), msg, lnet_msg::msg_list, list_head::next, and now().
Referenced by lnet_delay_rule_check(), and lnet_delay_rule_del().
static void delayed_msg_process (struct list_head * msg_list, bool drop) [static]
Definition at line 609 of file net_fault.c.
References LASSERT, list_del_init(), list_empty(), list_entry, LNET_CREDIT_OK, LNET_CREDIT_WAIT, lnet_drop_message(), lnet_finalize(), lnet_net_lock(), lnet_net_unlock(), lnet_ni_recv(), lnet_parse_forward_locked(), lnet_parse_local(), lnet_peer::lp_ni, msg, lnet_msg::msg_len, lnet_msg::msg_list, lnet_msg::msg_private, lnet_msg::msg_routing, lnet_msg::msg_rx_cpt, lnet_msg::msg_rxpeer, and list_head::next.
Referenced by lnet_delay_rule_check(), and lnet_delay_rule_del().
static bool drop_rule_match (struct lnet_drop_rule * rule, lnet_nid_t src, lnet_nid_t dst, unsigned int type, unsigned int portal) [static]
check source/destination NID, portal, message type and drop rate, decide whether should drop this message or not
Definition at line 303 of file net_fault.c.
References __u64, CDEBUG, cfs_rand(), cfs_time_after(), cfs_time_aftereq(), cfs_time_current(), cfs_time_seconds(), CFS_TIME_T, D_NET, lnet_fault_attr::da_interval, lnet_drop_rule::dr_attr, lnet_drop_rule::dr_drop_at, lnet_drop_rule::dr_drop_time, lnet_drop_rule::dr_lock, lnet_drop_rule::dr_stat, lnet_drop_rule::dr_time_base, lnet_fault_stat::drop, lnet_fault_attr::drop, lnet_fault_attr::fa_dst, lnet_fault_attr::fa_src, lnet_fault_stat::fs_count, libcfs_nid2str(), lnet_fault_attr_match(), lnet_fault_stat_inc(), now(), lnet_fault_stat::u, and lnet_fault_attr::u.
Referenced by lnet_drop_rule_match().
int lnet_delay_rule_add (struct lnet_fault_attr * attr)
Add a new delay rule to LNet There is no check for duplicated delay rule, all rules will be checked for incoming message.
Definition at line 730 of file net_fault.c.
References CDEBUG, CFS_ALLOC_PTR, CFS_FREE_PTR, cfs_rand(), cfs_time_shift(), D_NET, delay_daemon_data::dd_ctl_waitq, delay_daemon_data::dd_mutex, delay_daemon_data::dd_running, lnet_fault_attr::delay, delay_dd, delay_timer_cb(), lnet_delay_rule::dl_attr, lnet_delay_rule::dl_delay_at, lnet_delay_rule::dl_delay_time, lnet_delay_rule::dl_link, lnet_delay_rule::dl_lock, lnet_delay_rule::dl_msg_list, lnet_delay_rule::dl_msg_send, lnet_delay_rule::dl_refcount, lnet_delay_rule::dl_sched_link, lnet_delay_rule::dl_time_base, lnet_delay_rule::dl_timer, ENTRY, lnet_fault_attr::fa_src, GOTO, INIT_LIST_HEAD, libcfs_nid2str(), list_add(), lnet_t::ln_delay_rules, lnet_delay_rule_daemon(), lnet_fault_attr_validate(), LNET_LOCK_EX, lnet_net_lock(), lnet_net_unlock(), RETURN, the_lnet, and lnet_fault_attr::u.
Referenced by lnet_fault_ctl().
void lnet_delay_rule_check (void)
Process delayed messages for scheduled rules This function can either be called by delay_rule_daemon, or by lnet_finalise.
Definition at line 659 of file net_fault.c.
References delay_daemon_data::dd_lock, delay_daemon_data::dd_sched_rules, delay_dd, delay_rule_decref(), delayed_msg_check(), delayed_msg_process(), lnet_delay_rule::dl_sched_link, INIT_LIST_HEAD, list_del_init(), list_empty(), list_entry, and list_head::next.
Referenced by lnet_delay_rule_daemon(), and lnet_finalize().
static int lnet_delay_rule_daemon (void * arg) [static]
deamon thread to handle delayed messages
Definition at line 690 of file net_fault.c.
References delay_daemon_data::dd_ctl_waitq, delay_daemon_data::dd_running, delay_daemon_data::dd_sched_rules, delay_daemon_data::dd_stopped, delay_daemon_data::dd_waitq, delay_dd, list_empty(), and lnet_delay_rule_check().
Referenced by lnet_delay_rule_add().
int lnet_delay_rule_del (lnet_nid_t src, lnet_nid_t dst, bool shutdown)
Remove matched Delay Rules from lnet, if shutdown is true or both src and dst are zero, all rules will be removed, otherwise only matched rules will be removed.
If src is zero, then all rules have dst as destination will be remove If dst is zero, then all rules have src as source will be removed
When a delay rule is removed, all delayed messages of this rule will be processed immediately.
Definition at line 823 of file net_fault.c.
References CDEBUG, cleanup(), D_NET, delay_daemon_data::dd_ctl_waitq, delay_daemon_data::dd_mutex, delay_daemon_data::dd_running, delay_daemon_data::dd_stopped, delay_daemon_data::dd_waitq, lnet_fault_attr::delay, delay_dd, delay_rule_decref(), delayed_msg_check(), delayed_msg_process(), lnet_delay_rule::dl_attr, lnet_delay_rule::dl_link, lnet_delay_rule::dl_timer, ENTRY, lnet_fault_attr::fa_dst, lnet_fault_attr::fa_src, INIT_LIST_HEAD, LASSERT, libcfs_nid2str(), list_del_init(), list_empty(), list_for_each_entry_safe, list_move(), lnet_t::ln_delay_rules, LNET_LOCK_EX, lnet_net_lock(), lnet_net_unlock(), RETURN, the_lnet, and lnet_fault_attr::u.
Referenced by lnet_fault_ctl(), and lnet_fault_fini().
int lnet_delay_rule_list (int pos, struct lnet_fault_attr * attr, struct lnet_fault_stat * stat)
List Delay Rule at position of pos.
Definition at line 892 of file net_fault.c.
References lnet_delay_rule::dl_attr, lnet_delay_rule::dl_link, lnet_delay_rule::dl_lock, lnet_delay_rule::dl_stat, ENTRY, list_for_each_entry, lnet_t::ln_delay_rules, lnet_net_lock_current(), lnet_net_unlock(), RETURN, and the_lnet.
Referenced by lnet_fault_ctl().
bool lnet_delay_rule_match_locked (lnet_hdr_t * hdr, struct lnet_msg * msg)
check if msg can match any Delay Rule, receiving of this message will be delayed if there is a match.
Definition at line 547 of file net_fault.c.
References delay_rule_match(), lnet_delay_rule::dl_link, le32_to_cpu, le64_to_cpu, list_for_each_entry, lnet_t::ln_delay_rules, LNET_MSG_GET, LNET_MSG_PUT, and the_lnet.
Referenced by lnet_parse().
void lnet_delay_rule_reset (void)
reset counters for all Delay Rules
Definition at line 922 of file net_fault.c.
References cfs_rand(), cfs_time_shift(), lnet_fault_attr::delay, lnet_delay_rule::dl_attr, lnet_delay_rule::dl_delay_at, lnet_delay_rule::dl_delay_time, lnet_delay_rule::dl_link, lnet_delay_rule::dl_lock, lnet_delay_rule::dl_stat, lnet_delay_rule::dl_time_base, ENTRY, EXIT, lnet_fault_attr::la_interval, list_for_each_entry, lnet_t::ln_delay_rules, lnet_net_lock_current(), lnet_net_unlock(), the_lnet, and lnet_fault_attr::u.
Referenced by lnet_fault_ctl().
static int lnet_drop_rule_add (struct lnet_fault_attr * attr) [static]
LNet message drop simulation.
Add a new drop rule to LNet There is no check for duplicated drop rule, all rules will be checked for incoming message.
Definition at line 149 of file net_fault.c.
References CDEBUG, CFS_ALLOC_PTR, cfs_rand(), cfs_time_shift(), D_NET, lnet_drop_rule::dr_attr, lnet_drop_rule::dr_drop_at, lnet_drop_rule::dr_drop_time, lnet_drop_rule::dr_link, lnet_drop_rule::dr_lock, lnet_drop_rule::dr_time_base, lnet_fault_attr::drop, ENTRY, lnet_fault_attr::fa_src, libcfs_nid2str(), list_add(), lnet_t::ln_drop_rules, lnet_fault_attr_validate(), LNET_LOCK_EX, lnet_net_lock(), lnet_net_unlock(), RETURN, the_lnet, and lnet_fault_attr::u.
Referenced by lnet_fault_ctl().
static int lnet_drop_rule_del (lnet_nid_t src, lnet_nid_t dst) [static]
Remove matched drop rules from lnet, all rules that can match src and dst will be removed.
If src is zero, then all rules have dst as destination will be remove If dst is zero, then all rules have src as source will be removed If both of them are zero, all rules will be removed
Definition at line 198 of file net_fault.c.
References CDEBUG, CFS_FREE_PTR, D_NET, lnet_drop_rule::dr_attr, lnet_drop_rule::dr_link, lnet_fault_attr::drop, ENTRY, lnet_fault_attr::fa_dst, lnet_fault_attr::fa_src, INIT_LIST_HEAD, libcfs_nid2str(), list_del(), list_for_each_entry_safe, list_move(), lnet_t::ln_drop_rules, LNET_LOCK_EX, lnet_net_lock(), lnet_net_unlock(), RETURN, the_lnet, and lnet_fault_attr::u.
Referenced by lnet_fault_ctl(), and lnet_fault_fini().
static int lnet_drop_rule_list (int pos, struct lnet_fault_attr * attr, struct lnet_fault_stat * stat) [static]
List drop rule at position of pos.
Definition at line 239 of file net_fault.c.
References lnet_drop_rule::dr_attr, lnet_drop_rule::dr_link, lnet_drop_rule::dr_lock, lnet_drop_rule::dr_stat, ENTRY, list_for_each_entry, lnet_t::ln_drop_rules, lnet_net_lock_current(), lnet_net_unlock(), RETURN, and the_lnet.
Referenced by lnet_fault_ctl().
bool lnet_drop_rule_match (lnet_hdr_t * hdr)
Check if message from src to dst can match any existed drop rule.
Definition at line 363 of file net_fault.c.
References lnet_drop_rule::dr_link, drop_rule_match(), le32_to_cpu, le64_to_cpu, list_for_each_entry, lnet_t::ln_drop_rules, LNET_MSG_GET, LNET_MSG_PUT, lnet_net_lock_current(), lnet_net_unlock(), and the_lnet.
Referenced by lnet_parse().
static void lnet_drop_rule_reset (void) [static]
reset counters for all drop rules
Definition at line 269 of file net_fault.c.
References cfs_rand(), cfs_time_shift(), lnet_fault_attr::da_interval, lnet_drop_rule::dr_attr, lnet_drop_rule::dr_drop_at, lnet_drop_rule::dr_drop_time, lnet_drop_rule::dr_link, lnet_drop_rule::dr_lock, lnet_drop_rule::dr_stat, lnet_drop_rule::dr_time_base, lnet_fault_attr::drop, ENTRY, EXIT, list_for_each_entry, lnet_t::ln_drop_rules, lnet_net_lock_current(), lnet_net_unlock(), the_lnet, and lnet_fault_attr::u.
Referenced by lnet_fault_ctl().
static bool lnet_fault_attr_match (struct lnet_fault_attr * attr, lnet_nid_t src, lnet_nid_t dst, unsigned int type, unsigned int portal) [static]
Definition at line 81 of file net_fault.c.
References lnet_fault_attr::fa_dst, lnet_fault_attr::fa_msg_mask, lnet_fault_attr::fa_ptl_mask, lnet_fault_attr::fa_src, and lnet_fault_nid_match().
Referenced by delay_rule_match(), and drop_rule_match().
static int lnet_fault_attr_validate (struct lnet_fault_attr * attr) [static]
Definition at line 101 of file net_fault.c.
References CDEBUG, D_NET, lnet_fault_attr::fa_msg_mask, lnet_fault_attr::fa_ptl_mask, LNET_GET_BIT, LNET_MSG_MASK, and LNET_PUT_BIT.
Referenced by lnet_delay_rule_add(), and lnet_drop_rule_add().
int lnet_fault_ctl (int opc, struct libcfs_ioctl_data * data)
Definition at line 952 of file net_fault.c.
References lnet_fault_attr::fa_dst, lnet_fault_attr::fa_src, libcfs_ioctl_data::ioc_count, libcfs_ioctl_data::ioc_inlbuf1, libcfs_ioctl_data::ioc_inlbuf2, LNET_CTL_DELAY_ADD, LNET_CTL_DELAY_DEL, LNET_CTL_DELAY_LIST, LNET_CTL_DELAY_RESET, LNET_CTL_DROP_ADD, LNET_CTL_DROP_DEL, LNET_CTL_DROP_LIST, LNET_CTL_DROP_RESET, lnet_delay_rule_add(), lnet_delay_rule_del(), lnet_delay_rule_list(), lnet_delay_rule_reset(), lnet_drop_rule_add(), lnet_drop_rule_del(), lnet_drop_rule_list(), and lnet_drop_rule_reset().
Referenced by LNetCtl().
void lnet_fault_fini (void)
Definition at line 1033 of file net_fault.c.
References delay_daemon_data::dd_sched_rules, delay_dd, LASSERT, list_empty(), lnet_t::ln_delay_rules, lnet_t::ln_drop_rules, lnet_delay_rule_del(), lnet_drop_rule_del(), and the_lnet.
Referenced by LNetNIFini().
int lnet_fault_init (void)
Definition at line 1016 of file net_fault.c.
References CLASSERT, delay_daemon_data::dd_ctl_waitq, delay_daemon_data::dd_lock, delay_daemon_data::dd_mutex, delay_daemon_data::dd_sched_rules, delay_daemon_data::dd_waitq, delay_dd, INIT_LIST_HEAD, LNET_ACK_BIT, LNET_GET_BIT, LNET_MSG_ACK, LNET_MSG_GET, LNET_MSG_PUT, LNET_MSG_REPLY, LNET_PUT_BIT, and LNET_REPLY_BIT.
Referenced by LNetNIInit().
static bool lnet_fault_nid_match (lnet_nid_t nid, lnet_nid_t msg_nid) [static]
Definition at line 68 of file net_fault.c.
References LNET_NID_ANY, LNET_NIDADDR(), and LNET_NIDNET().
Referenced by lnet_fault_attr_match().
static void lnet_fault_stat_inc (struct lnet_fault_stat * stat, unsigned int type) [static]
Definition at line 120 of file net_fault.c.
References lnet_fault_stat::fs_ack, lnet_fault_stat::fs_get, lnet_fault_stat::fs_put, lnet_fault_stat::fs_reply, LNET_MSG_ACK, LNET_MSG_GET, LNET_MSG_PUT, and LNET_MSG_REPLY.
Referenced by delay_rule_match(), and drop_rule_match().
static cfs_time_t round_timeout (cfs_time_t timeout) [static]
Definition at line 449 of file net_fault.c.
References cfs_duration_sec(), cfs_time_seconds(), and cfs_time_sub().
Referenced by delay_rule_match().
Variable Documentation
struct delay_daemon_data delay_dd [static]
Definition at line 446 of file net_fault.c.
Referenced by delay_timer_cb(), lnet_delay_rule_add(), lnet_delay_rule_check(), lnet_delay_rule_daemon(), lnet_delay_rule_del(), lnet_fault_fini(), and lnet_fault_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.