Lustre: lnet/include/lnet/nidstr.h File Reference
lnet/include/lnet/nidstr.h File Reference
#include <lnet/types.h>
Data Structures
struct netstrfns
Defines
#define LNET_NIDSTR_COUNT 1024
#define LNET_NIDSTR_SIZE 32
Enumerations
enum {
QSWLND = 1, SOCKLND = 2, GMLND = 3, PTLLND = 4,
O2IBLND = 5, CIBLND = 6, OPENIBLND = 7, IIBLND = 8,
LOLND = 9, RALND = 10, VIBLND = 11, MXLND = 12,
GNILND = 13, GNIIPLND = 14
}
Lustre Network Driver types.
Functions
char * libcfs_next_nidstring (void)
int libcfs_isknown_lnd (__u32 lnd)
char * libcfs_lnd2modname (__u32 lnd)
char * libcfs_lnd2str_r (__u32 lnd, char *buf, size_t buf_size)
static char * libcfs_lnd2str (__u32 lnd)
int libcfs_str2lnd (const char *str)
char * libcfs_net2str_r (__u32 net, char *buf, size_t buf_size)
static char * libcfs_net2str (__u32 net)
char * libcfs_nid2str_r (lnet_nid_t nid, char *buf, size_t buf_size)
static char * libcfs_nid2str (lnet_nid_t nid)
__u32 libcfs_str2net (const char *str)
lnet_nid_t libcfs_str2nid (const char *str)
int libcfs_str2anynid (lnet_nid_t *nid, const char *str)
char * libcfs_id2str (lnet_process_id_t id)
void cfs_free_nidlist (struct list_head *list)
Frees nidrange strutures of list.
int cfs_parse_nidlist (char *str, int len, struct list_head *list)
Parses nid range list.
int cfs_print_nidlist (char *buffer, int count, struct list_head *list)
Print a list of nidranges (nidlist) into the specified buffer.
int cfs_match_nid (lnet_nid_t nid, struct list_head *list)
Matches a nid (nid) against the compiled list of nidranges (nidlist).
int cfs_ip_addr_parse (char *str, int len, struct list_head *list)
int cfs_ip_addr_match (__u32 addr, struct list_head *list)
Matches address (addr) against address set encoded in list.
bool cfs_nidrange_is_contiguous (struct list_head *nidlist)
Determines whether an expression list in an nidrange contains exactly one contiguous address range.
void cfs_nidrange_find_min_max (struct list_head *nidlist, char *min_nid, char *max_nid, size_t nidstr_length)
Takes a linked list of nidrange expressions, determines the minimum and maximum nid and creates appropriate nid structures.
Define Documentation
#define LNET_NIDSTR_COUNT 1024
Definition at line 56 of file nidstr.h.
#define LNET_NIDSTR_SIZE 32
Definition at line 57 of file nidstr.h.
Referenced by add_nidrange(), class_config_parse_rec(), class_config_yaml_output(), jt_nodemap_add_range(), jt_nodemap_del_range(), libcfs_id2str(), libcfs_lnd2str(), libcfs_net2str(), libcfs_nid2str(), lprocfs_add_nodemap_range_seq_write(), lprocfs_del_nodemap_range_seq_write(), lustre_start_mgc(), mgs_steal_client_llog_handler(), mgs_write_log_failnids(), mgs_write_log_mdc_to_lmv(), mgs_write_log_osc_to_lov(), mgs_write_log_osp_to_mdt(), nodemap_exports_show(), nodemap_parse_range(), nodemap_ranges_show(), parse_nids(), and rule2string().
Enumeration Type Documentation
anonymous enum
Lustre Network Driver types.
Enumerator:
QSWLND
SOCKLND
GMLND
PTLLND
O2IBLND
CIBLND
OPENIBLND
IIBLND
LOLND
RALND
VIBLND
MXLND
GNILND
GNIIPLND
Definition at line 35 of file nidstr.h.
Function Documentation
void cfs_free_nidlist (struct list_head * list)
Frees nidrange strutures of list.
For each struct nidrange structure found on list it frees addrrange list attached to it and frees the nidrange itself.
Return values:
none
Definition at line 305 of file nidstrings.c.
References free_addrranges(), LIBCFS_FREE, list_del(), list_entry, list_for_each_safe, list_head::next, nidrange::nr_addrranges, and nidrange::nr_link.
Referenced by cfs_parse_nidlist(), ll_free_sbi(), lmd_parse_nidlist(), mdt_fini(), and parse_nids().
int cfs_ip_addr_match (__u32 addr, struct list_head * list)
Matches address (addr) against address set encoded in list.
Return values:
1 if addr matches
0 otherwise
Definition at line 874 of file nidstrings.c.
Referenced by lnet_match_network_token().
int cfs_ip_addr_parse (char * str, int len, struct list_head * list)
Definition at line 815 of file nidstrings.c.
Referenced by lnet_match_network_token().
int cfs_match_nid (lnet_nid_t nid, struct list_head * nidlist)
Matches a nid (nid) against the compiled list of nidranges (nidlist).
See also:
cfs_parse_nidlist()
Return values:
1 on match
0 otherwises
Definition at line 366 of file nidstrings.c.
References addrrange::ar_link, addrrange::ar_numaddr_ranges, list_for_each_entry, LNET_NETNUM(), LNET_NETTYP(), LNET_NIDADDR(), LNET_NIDNET(), netstrfns::nf_match_addr, netstrfns::nf_type, nidrange::nr_addrranges, nidrange::nr_all, nidrange::nr_netnum, and nidrange::nr_netstrfns.
Referenced by ll_compute_rootsquash_state(), and match_nosquash_list().
void cfs_nidrange_find_min_max (struct list_head * nidlist, char * min_nid, char * max_nid, size_t nidstr_length)
Takes a linked list of nidrange expressions, determines the minimum and maximum nid and creates appropriate nid structures.
Parameters:
*nidlist
*min_nid
*max_nid
Definition at line 676 of file nidstrings.c.
References IPSTRING_LENGTH, list_for_each_entry, netstrfns::nf_addr2str, netstrfns::nf_min_max, netstrfns::nf_name, nidrange::nr_netnum, and nidrange::nr_netstrfns.
Referenced by jt_nodemap_add_range(), jt_nodemap_del_range(), and parse_nids().
bool cfs_nidrange_is_contiguous (struct list_head * nidlist)
Determines whether an expression list in an nidrange contains exactly one contiguous address range.
Calls the correct netstrfns for the LND
Parameters:
*nidlist
Return values:
true if contiguous
false if not contiguous
Definition at line 539 of file nidstrings.c.
References list_for_each_entry, netstrfns::nf_is_contiguous, netstrfns::nf_name, nidrange::nr_netnum, and nidrange::nr_netstrfns.
Referenced by jt_nodemap_add_range(), jt_nodemap_del_range(), and parse_nids().
int cfs_parse_nidlist (char * str, int len, struct list_head * nidlist)
Parses nid range list.
Parses with rigorous syntax and overflow checking str into <nidrange> [ ' ' <nidrange> ], compiles str into set of structures and links that structure to nidlist. The resulting list can be used to match a NID againts set of NIDS defined by str.
See also:
cfs_match_nid
Return values:
1 on success
0 otherwise
Definition at line 333 of file nidstrings.c.
References cfs_free_nidlist(), cfs_gettok(), INIT_LIST_HEAD, cfs_lstr::ls_len, cfs_lstr::ls_str, and parse_nidrange().
Referenced by jt_nodemap_add_range(), jt_nodemap_del_range(), lmd_parse_nidlist(), and parse_nids().
int cfs_print_nidlist (char * buffer, int count, struct list_head * nidlist)
Print a list of nidranges (nidlist) into the specified buffer.
At max count characters can be printed into buffer. Nidranges are separated by a space character.
Return values:
number of characters written
Definition at line 435 of file nidstrings.c.
References assert, cfs_print_addrranges(), cfs_print_network(), LASSERT, list_empty(), list_for_each_entry, nidrange::nr_addrranges, nidrange::nr_all, and nidrange::nr_link.
Referenced by mdt_nosquash_nids_seq_show().
char* libcfs_id2str (lnet_process_id_t id)
Definition at line 1236 of file nidstrings.c.
References libcfs_next_nidstring(), libcfs_nid2str(), LNET_NIDSTR_SIZE, LNET_PID_ANY, and LNET_PID_USERFLAG.
Referenced by brw_bulk_ready(), brw_client_done_rpc(), brw_server_rpc_done(), jt_lst_list_group(), jt_lst_ping(), jt_lst_show_error(), jt_ptl_ping(), jt_ptl_print_connections(), jt_ptl_print_peers(), kgnilnd_send(), kiblnd_send(), ksocknal_add_route_locked(), ksocknal_associate_route_conn_locked(), ksocknal_create_conn(), ksocknal_debug_peerhash(), ksocknal_destroy_conn(), ksocknal_destroy_peer(), ksocknal_find_peer_locked(), ksocknal_find_timed_out_conn(), ksocknal_launch_packet(), ksocknal_process_receive(), ksocknal_process_transmit(), ksocknal_queue_tx_locked(), ksocknal_queue_tx_zcack_v3(), ksocknal_recv_hello(), ksocknal_send(), ldlm_callback_errmsg(), lnet_create_reply_msg(), lnet_drop_delayed_msg_list(), lnet_finalize(), lnet_ni_eager_recv(), lnet_parse_ack(), lnet_parse_get(), lnet_parse_put(), lnet_parse_reply(), lnet_ping(), lnet_ping_router_locked(), lnet_post_send_locked(), lnet_print_hdr(), lnet_ptl_attach_md(), lnet_ptl_match_md(), lnet_recv_delayed_msg_list(), lnet_send(), lnet_try_match_md(), LNetGet(), LNetPut(), lst_list_tsb_nodes(), lst_print_transerr(), lst_print_tsb_verbose(), lstcon_nodes_stat(), nrs_fifo_req_get(), nrs_fifo_req_stop(), ping_client_done_rpc(), ping_server_handle(), ptl_send_buf(), ptlrpc_register_bulk(), ptlrpc_server_handle_req_in(), ptlrpc_server_handle_request(), ptlrpc_uuid_to_peer(), replay_lock_interpret(), request_in_callback(), sfw_add_test(), sfw_bulk_ready(), sfw_client_rpc_fini(), sfw_handle_server_rpc(), sfw_server_rpc_done(), sptlrpc_svc_unwrap_request(), srpc_abort_rpc(), srpc_client_rpc_done(), srpc_client_rpc_expired(), srpc_finish_service(), srpc_handle_rpc(), srpc_lnet_ev_handler(), srpc_post_active_rdma(), srpc_post_passive_rdma(), srpc_post_rpc(), srpc_send_rpc(), srpc_server_rpc_done(), tgt_brw_read(), tgt_brw_write(), tgt_request_handle(), and tgt_warn_on_cksum().
int libcfs_isknown_lnd (__u32 lnd)
Definition at line 1065 of file nidstrings.c.
References libcfs_lnd2netstrfns().
Referenced by lnet_register_lnd(), and lnet_startup_lndni().
char* libcfs_lnd2modname (__u32 lnd)
Definition at line 1072 of file nidstrings.c.
References libcfs_lnd2netstrfns(), and netstrfns::nf_modname.
Referenced by kgnilnd_proc_fini(), kgnilnd_proc_init(), and lnet_startup_lndni().
static char* libcfs_lnd2str (__u32 lnd) [inline, static]
Definition at line 64 of file nidstr.h.
References libcfs_lnd2str_r(), libcfs_next_nidstring(), and LNET_NIDSTR_SIZE.
Referenced by g_net_is_compatible(), jt_ptl_network(), lnet_register_lnd(), lnet_startup_lndni(), lnet_unregister_lnd(), lustre_lnet_config_route(), lustre_lnet_del_route(), and lustre_lnet_show_route().
char* libcfs_lnd2str_r (__u32 lnd, char * buf, size_t buf_size)
Definition at line 1093 of file nidstrings.c.
References libcfs_lnd2netstrfns(), and netstrfns::nf_name.
Referenced by libcfs_lnd2str().
static char* libcfs_net2str (__u32 net) [inline, static]
Definition at line 71 of file nidstr.h.
References libcfs_net2str_r(), libcfs_next_nidstring(), and LNET_NIDSTR_SIZE.
Referenced by jt_ptl_print_routes(), lnet_add_route(), lnet_check_routes(), lnet_del_route(), lnet_ni_alloc(), lnet_parse_networks(), lnet_parse_route(), lnet_startup_lndni(), lustre_lnet_show_net(), lustre_lnet_show_route(), parse_net(), and proc_lnet_routes().
char* libcfs_net2str_r (__u32 net, char * buf, size_t buf_size)
Definition at line 1108 of file nidstrings.c.
References libcfs_lnd2netstrfns(), LNET_NETNUM(), LNET_NETTYP(), and netstrfns::nf_name.
Referenced by libcfs_net2str(), and rule2string().
char* libcfs_next_nidstring (void)
Definition at line 71 of file nidstrings.c.
References ARRAY_SIZE, libcfs_nidstring_idx, and libcfs_nidstrings.
Referenced by libcfs_id2str(), libcfs_lnd2str(), libcfs_net2str(), and libcfs_nid2str().
static char* libcfs_nid2str (lnet_nid_t nid) [inline, static]
Definition at line 77 of file nidstr.h.
References libcfs_next_nidstring(), libcfs_nid2str_r(), and LNET_NIDSTR_SIZE.
Referenced by _debug_req(), _kgnilnd_debug_conn(), _kgnilnd_debug_tx(), _kgnilnd_match_reply(), _ldlm_lock_debug(), check_write_checksum(), class_add_uuid(), class_check_uuid(), class_config_llog_handler(), class_del_uuid(), class_disconnect_stale_exports(), class_process_config(), clean_path(), convert_hostnames(), delay_rule_match(), do_add_uuid(), drop_rule_match(), fault_simul_rule_add(), fault_simul_rule_del(), fault_simul_rule_list(), gss_pack_err_notify(), gss_svc_handle_data(), gss_svc_handle_destroy(), gss_svc_handle_init(), gss_svc_upcall_get_ctx(), gss_svc_upcall_handle_init(), import_select_connection(), jt_lst_ping(), jt_lst_show_session(), jt_ptl_del_route(), jt_ptl_list_nids(), jt_ptl_mynid(), jt_ptl_notify_router(), jt_ptl_ping(), jt_ptl_print_connections(), jt_ptl_print_peers(), jt_ptl_print_routes(), jt_ptl_which_nid(), kgnilnd_add_peer(), kgnilnd_add_peer_locked(), kgnilnd_add_purgatory_locked(), kgnilnd_add_purgatory_tx(), kgnilnd_can_unlink_peer_locked(), kgnilnd_cancel_dgram_locked(), kgnilnd_cancel_peer_connect_locked(), kgnilnd_cancel_wc_dgrams(), kgnilnd_check_conn_timeouts_locked(), kgnilnd_check_fma_rcv_cq(), kgnilnd_check_fma_rx(), kgnilnd_check_fma_send_cq(), kgnilnd_check_peer_timeouts_locked(), kgnilnd_check_purgatory_conn(), kgnilnd_close_conn_locked(), kgnilnd_close_stale_conns_locked(), kgnilnd_complete_closed_conn(), kgnilnd_complete_tx(), kgnilnd_conn_isdup_locked(), kgnilnd_conn_seq_show(), kgnilnd_create_peer_safe(), kgnilnd_ctl(), kgnilnd_del_conn_or_peer(), kgnilnd_destroy_conn(), kgnilnd_destroy_peer(), kgnilnd_detach_purgatory_locked(), kgnilnd_eager_recv(), kgnilnd_find_conn_locked(), kgnilnd_find_dgram_locked(), kgnilnd_find_or_create_conn_locked(), kgnilnd_find_peer_locked(), kgnilnd_finish_connect(), kgnilnd_get_conn_by_idx(), kgnilnd_get_peer_info(), kgnilnd_nak_rdma(), kgnilnd_nicaddr_to_nid(), kgnilnd_nid_to_nicaddrs(), kgnilnd_peer_increase_reconnect_locked(), kgnilnd_peer_notify(), kgnilnd_peer_seq_show(), kgnilnd_post_dgram(), kgnilnd_probe_and_process_dgram(), kgnilnd_probe_for_dgram(), kgnilnd_proc_peer_conns_seq_show(), kgnilnd_process_connreq(), kgnilnd_process_dgram(), kgnilnd_process_fmaq(), kgnilnd_process_nak(), kgnilnd_query(), kgnilnd_queue_tx(), kgnilnd_reaper_dgram_check(), kgnilnd_recv(), kgnilnd_release_dgram(), kgnilnd_send(), kgnilnd_send_nak(), kgnilnd_sendmsg_nolock(), kgnilnd_set_conn_params(), kgnilnd_start_connect(), kgnilnd_start_outbound_dgrams(), kgnilnd_startup(), kgnilnd_tx_done(), kgnilnd_tx_should_retry(), kgnilnd_unlink_peer_locked(), kgnilnd_unpack_connreq(), kgnilnd_validate_tx_ev_id(), kiblnd_active_connect(), kiblnd_check_connreply(), kiblnd_check_conns(), kiblnd_check_reconnect(), kiblnd_check_sends(), kiblnd_close_conn_locked(), kiblnd_close_peer_conns_locked(), kiblnd_close_stale_conns_locked(), kiblnd_cm_callback(), kiblnd_connect_peer(), kiblnd_connreq_done(), kiblnd_cq_event(), kiblnd_create_conn(), kiblnd_debug_conn(), kiblnd_find_peer_locked(), kiblnd_handle_completion(), kiblnd_handle_rx(), kiblnd_init_rdma(), kiblnd_launch_tx(), kiblnd_passive_connect(), kiblnd_peer_connect_failed(), kiblnd_post_rx(), kiblnd_post_tx_locked(), kiblnd_qp_event(), kiblnd_query(), kiblnd_reconnect_peer(), kiblnd_recv(), kiblnd_rejected(), kiblnd_reply(), kiblnd_rx_complete(), kiblnd_scheduler(), kiblnd_send(), kiblnd_send_completion(), kiblnd_shutdown(), kiblnd_tx_complete(), kiblnd_unpack_msg(), ksocknal_check_peer_timeouts(), ksocknal_connect(), ksocknal_ctl(), ksocknal_notify(), ksocknal_query(), ksocknal_txlist_done(), ldlm_cli_cancel_req(), libcfs_id2str(), lnet_accept(), lnet_add_route(), lnet_check_routes(), lnet_clear_zombies_nis_locked(), lnet_connect_console_error(), lnet_create_reply_msg(), lnet_debug_peer(), lnet_del_route(), lnet_delay_rule_add(), lnet_delay_rule_del(), lnet_drop_rule_add(), lnet_drop_rule_del(), lnet_finalize(), lnet_ni_eager_recv(), lnet_notify(), lnet_notify_locked(), lnet_parse(), lnet_parse_ack(), lnet_parse_get(), lnet_parse_rc_info(), lnet_parse_reply(), lnet_parse_route(), lnet_peer_alive_locked(), lnet_ping_router_locked(), lnet_send(), lnet_startup_lndni(), lnet_update_ni_status_locked(), lstcon_sesnew_stat_reply(), lustre_lnet_show_net(), lustre_lnet_show_peer_credits(), lustre_lnet_show_route(), mdt_check_ucred(), mdt_empty_transno(), mdt_init_idmap(), mdt_root_squash(), mdt_steal_ack_locks(), mgc_apply_recover_logs(), mgs_check_failover_reg(), mgs_llog_open(), new_init_ucred(), obd_export_evict_by_nid(), obd_export_nid2str(), only_mgs_is_running(), osc_brw_fini_request(), print_1_cfg(), print_lustre_cfg(), proc_lnet_nis(), proc_lnet_peers(), proc_lnet_routers(), proc_lnet_routes(), process_command(), ptlrpc_check_set(), ptlrpc_check_status(), ptlrpc_connection_addref(), ptlrpc_connection_get(), ptlrpc_connection_put(), ptlrpc_handle_rs(), ptlrpc_import_recovery_state_machine(), ptlrpc_send_new_req(), ptlrpc_set_import_discon(), server_register_target(), sfw_session_expired(), tgt_connect_check_sptlrpc(), tgt_init_sec_level(), and tgt_warn_on_cksum().
char* libcfs_nid2str_r (lnet_nid_t nid, char * buf, size_t buf_size)
Definition at line 1127 of file nidstrings.c.
References libcfs_lnd2netstrfns(), LNET_NETNUM(), LNET_NETTYP(), LNET_NID_ANY, LNET_NIDADDR(), LNET_NIDNET(), netstrfns::nf_addr2str, and netstrfns::nf_name.
Referenced by class_config_parse_rec(), class_config_yaml_output(), libcfs_nid2str(), lustre_start_mgc(), mgs_steal_client_llog_handler(), mgs_write_log_failnids(), mgs_write_log_mdc_to_lmv(), mgs_write_log_osc_to_lov(), mgs_write_log_osp_to_mdt(), nodemap_exports_show(), and nodemap_ranges_show().
int libcfs_str2anynid (lnet_nid_t * nid, const char * str)
Definition at line 1254 of file nidstrings.c.
References libcfs_str2nid(), and LNET_NID_ANY.
Referenced by fault_attr_nid_parse(), jt_ptl_del_peer(), jt_ptl_del_route(), jt_ptl_disconnect(), jt_ptl_fail_nid(), and jt_ptl_push_connection().
int libcfs_str2lnd (const char * str)
Definition at line 1081 of file nidstrings.c.
References libcfs_name2netstrfns(), and netstrfns::nf_type.
__u32 libcfs_str2net (const char * str)
Definition at line 1198 of file nidstrings.c.
References libcfs_str2net_internal(), LNET_NID_ANY, and LNET_NIDNET().
Referenced by fault_attr_nid_parse(), jt_ptl_network(), lnet_netspec2net(), lnet_parse_networks(), lnet_parse_route(), lustre_lnet_config_route(), lustre_lnet_del_net(), lustre_lnet_del_route(), lustre_lnet_show_net(), lustre_lnet_show_route(), parse_net(), and sptlrpc_parse_rule().
lnet_nid_t libcfs_str2nid (const char * str)
Definition at line 1210 of file nidstrings.c.
References assert, LASSERT, libcfs_lnd2netstrfns(), libcfs_str2net_internal(), LNET_MKNET(), LNET_MKNID(), LNET_NID_ANY, netstrfns::nf_str2addr, and SOCKLND.
Referenced by clean_path(), convert_hostnames(), jt_lcfg_add_uuid(), jt_ptl_add_peer(), jt_ptl_add_route(), jt_ptl_mynid(), jt_ptl_notify_router(), jt_ptl_ping(), jt_ptl_which_nid(), libcfs_str2anynid(), lnet_parse_nid(), lnet_parse_route(), lst_parse_nids(), lustre_lnet_config_route(), lustre_lnet_del_route(), lustre_lnet_show_route(), main(), mgs_iocontrol_nodemap(), nodemap_parse_range(), obd_export_evict_by_nid(), parse_nid(), parse_perm_line(), and read_mapping_db().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.