Lustre: lustre/ptlrpc/niobuf.c File Reference
lustre/ptlrpc/niobuf.c File Reference
#include <obd_support.h>
#include <lustre_net.h>
#include <lustre_lib.h>
#include <obd.h>
#include <obd_class.h>
#include "ptlrpc_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_RPC
Functions
static int ptl_send_buf (lnet_handle_md_t *mdh, void *base, int len, lnet_ack_req_t ack, struct ptlrpc_cb_id *cbid, struct ptlrpc_connection *conn, int portal, __u64 xid, unsigned int offset)
Helper function.
static void mdunlink_iterate_helper (lnet_handle_md_t *bd_mds, int count)
int ptlrpc_register_bulk (struct ptlrpc_request *req)
Register bulk at the sender for later transfer.
int ptlrpc_unregister_bulk (struct ptlrpc_request *req, int async)
Disconnect a bulk desc from the network.
static void ptlrpc_at_set_reply (struct ptlrpc_request *req, int flags)
int ptlrpc_send_reply (struct ptlrpc_request *req, int flags)
Send request reply from request req reply buffer.
int ptlrpc_reply (struct ptlrpc_request *req)
int ptlrpc_send_error (struct ptlrpc_request *req, int may_be_difficult)
For request req send an error reply back.
int ptlrpc_error (struct ptlrpc_request *req)
int ptl_send_rpc (struct ptlrpc_request *request, int noreply)
Send request request.
int ptlrpc_register_rqbd (struct ptlrpc_request_buffer_desc *rqbd)
Register request buffer descriptor for request receiving.
Define Documentation
#define DEBUG_SUBSYSTEM S_RPC
Definition at line 37 of file niobuf.c.
Function Documentation
static void mdunlink_iterate_helper (lnet_handle_md_t * bd_mds, int count) [static]
Definition at line 101 of file niobuf.c.
References LNetMDUnlink().
Referenced by ptlrpc_register_bulk(), and ptlrpc_unregister_bulk().
static int ptl_send_buf (lnet_handle_md_t * mdh, void * base, int len, lnet_ack_req_t ack, struct ptlrpc_cb_id * cbid, struct ptlrpc_connection * conn, int portal, __u64 xid, unsigned int offset) [static]
Helper function.
Sends len bytes from base at offset offset over conn connection to portal portal. Returns 0 on success or error code.
Definition at line 50 of file niobuf.c.
References ptlrpc_connection::c_peer, ptlrpc_connection::c_self, CDEBUG, CERROR, D_INFO, D_NET, ENTRY, lnet_md_t::eq_handle, LASSERT, LASSERTF, lnet_md_t::length, libcfs_id2str(), LNET_ACK_REQ, LNET_NOACK_REQ, LNET_UNLINK, LNetMDBind(), LNetMDUnlink(), LNetPut(), LPD64, OBD_FAIL_CHECK_ORSET, OBD_FAIL_ONCE, OBD_FAIL_PTLRPC_ACK, lnet_md_t::options, ptlrpc_eq_h, PTLRPC_MD_OPTIONS, RETURN, lnet_md_t::start, lnet_md_t::threshold, unlikely, and lnet_md_t::user_ptr.
Referenced by ptl_send_rpc(), and ptlrpc_send_reply().
static void ptlrpc_at_set_reply (struct ptlrpc_request * req, int flags) [static]
Definition at line 477 of file niobuf.c.
References at_get(), at_measured(), CDEBUG, cfs_time_current_sec(), D_ADAPTTO, DEBUG_REQ, obd_export::exp_obd, lustre_msg_get_flags(), lustre_msg_get_magic(), lustre_msg_set_service_time(), lustre_msg_set_timeout(), lustre_msghdr_get_flags(), MSG_LOCK_REPLAY_DONE, MSG_REPLAY, MSG_REQ_REPLAY_DONE, MSG_RESENT, MSGHDR_AT_SUPPORT, obd_device::obd_recovering, PTL_RPC_MSG_ERR, PTLRPC_REPLY_EARLY, ptlrpc_request::rq_export, ptlrpc_request::rq_replen, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_type, ptlrpc_service_part::scp_at_estimate, and ptlrpc_service::srv_name.
Referenced by ptlrpc_send_reply().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.