Lustre: lustre/ptlrpc/nodemap_range.c File Reference
lustre/ptlrpc/nodemap_range.c File Reference
#include <interval_tree.h>
#include <lustre_net.h>
#include "nodemap_internal.h"
Functions
static enum interval_iter range_cb (struct interval_node *n, void *data)
struct lu_nid_range * range_create (struct nodemap_range_tree *nm_range_tree, lnet_nid_t start_nid, lnet_nid_t end_nid, struct lu_nodemap *nodemap, unsigned range_id)
struct lu_nid_range * range_find (struct nodemap_range_tree *nm_range_tree, lnet_nid_t start_nid, lnet_nid_t end_nid)
void range_destroy (struct lu_nid_range *range)
int range_insert (struct nodemap_range_tree *nm_range_tree, struct lu_nid_range *range)
void range_delete (struct nodemap_range_tree *nm_range_tree, struct lu_nid_range *range)
struct lu_nid_range * range_search (struct nodemap_range_tree *nm_range_tree, lnet_nid_t nid)
Function Documentation
static enum interval_iter range_cb (struct interval_node * n, void * data) [static]
Definition at line 52 of file nodemap_range.c.
References INTERVAL_ITER_STOP, ret, and lu_nid_range::rn_node.
Referenced by range_search().
struct lu_nid_range* range_create (struct nodemap_range_tree * nm_range_tree, lnet_nid_t start_nid, lnet_nid_t end_nid, struct lu_nodemap * nodemap, unsigned range_id) [read]
Definition at line 72 of file nodemap_range.c.
References CERROR, INIT_LIST_HEAD, interval_set(), LNET_NIDADDR(), LNET_NIDNET(), nodemap_range_tree::nmrt_range_highest_id, OBD_ALLOC_PTR, lu_nid_range::rn_id, lu_nid_range::rn_list, lu_nid_range::rn_node, and lu_nid_range::rn_nodemap.
void range_delete (struct nodemap_range_tree * nm_range_tree, struct lu_nid_range * range)
Definition at line 174 of file nodemap_range.c.
References interval_erase(), interval_is_intree(), list_del(), nodemap_range_tree::nmrt_range_interval_root, range_destroy(), lu_nid_range::rn_list, and lu_nid_range::rn_node.
Referenced by nodemap_config_cleanup(), nodemap_del(), and nodemap_del_range().
void range_destroy (struct lu_nid_range * range)
Definition at line 134 of file nodemap_range.c.
References interval_is_intree(), LASSERT, list_empty(), OBD_FREE_PTR, lu_nid_range::rn_list, and lu_nid_range::rn_node.
Referenced by nodemap_add_range_helper(), and range_delete().
struct lu_nid_range* range_find (struct nodemap_range_tree * nm_range_tree, lnet_nid_t start_nid, lnet_nid_t end_nid) [read]
Definition at line 112 of file nodemap_range.c.
References interval_find(), and nodemap_range_tree::nmrt_range_interval_root.
Referenced by nodemap_del_range().
int range_insert (struct nodemap_range_tree * nm_range_tree, struct lu_nid_range * range)
Definition at line 152 of file nodemap_range.c.
References interval_node::in_extent, interval_insert(), interval_is_overlapped(), nodemap_range_tree::nmrt_range_interval_root, and lu_nid_range::rn_node.
Referenced by nodemap_add_range_helper().
struct lu_nid_range* range_search (struct nodemap_range_tree * nm_range_tree, lnet_nid_t nid) [read]
Definition at line 190 of file nodemap_range.c.
References interval_search(), nodemap_range_tree::nmrt_range_interval_root, range_cb(), and ret.
Referenced by nodemap_classify_nid().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.