Lustre: lustre/ptlrpc/nodemap_internal.h File Reference
lustre/ptlrpc/nodemap_internal.h File Reference
#include <lustre_nodemap.h>
#include <interval_tree.h>
Data Structures
struct lu_nid_range
struct lu_idmap
struct nodemap_range_tree
struct nodemap_config
struct nodemap_key
Defines
#define DEFAULT_NODEMAP "default"
#define NODEMAP_NOBODY_UID 99
#define NODEMAP_NOBODY_GID 99
#define NM_TYPE_MASK 0x0FFFFFFF
#define NM_TYPE_SHIFT 28
#define nm_rbtree_postorder_for_each_entry_safe(pos, n,root, field)
Enumerations
enum nodemap_idx_type {
NODEMAP_EMPTY_IDX = 0, NODEMAP_CLUSTER_IDX = 1, NODEMAP_RANGE_IDX = 2, NODEMAP_UIDMAP_IDX = 3,
NODEMAP_GIDMAP_IDX = 4, NODEMAP_GLOBAL_IDX = 15
}
Functions
static enum nodemap_idx_type nm_idx_get_type (unsigned int id)
static __u32 nm_idx_set_type (unsigned int id, enum nodemap_idx_type t)
struct nodemap_config * nodemap_config_alloc (void)
void nodemap_config_dealloc (struct nodemap_config *config)
void nodemap_config_set_active (struct nodemap_config *config)
struct lu_nodemap * nodemap_create (const char *name, struct nodemap_config *config, bool is_default)
Nodemap constructor.
void nodemap_putref (struct lu_nodemap *nodemap)
Destroy nodemap if last reference is put.
struct lu_nodemap * nodemap_lookup (const char *name)
Nodemap lookup.
int nodemap_procfs_init (void)
Initialize the nodemap procfs directory.
void nodemap_procfs_exit (void)
Cleanup nodemap proc entry data structures.
int lprocfs_nodemap_register (struct lu_nodemap *nodemap, bool is_default_nodemap)
Register the proc directory for a nodemap.
void lprocfs_nodemap_remove (struct nodemap_pde *nodemap_pde)
Remove a nodemap's procfs entry and related data.
struct lu_nid_range * nodemap_range_find (lnet_nid_t start_nid, lnet_nid_t end_nid)
struct lu_nid_range * range_create (struct nodemap_range_tree *nm_range_tree, lnet_nid_t start_nid, lnet_nid_t end_nid, struct lu_nodemap *nodemap, unsigned int range_id)
void range_destroy (struct lu_nid_range *range)
int range_insert (struct nodemap_range_tree *nm_range_tree, struct lu_nid_range *data)
void range_delete (struct nodemap_range_tree *nm_range_tree, struct lu_nid_range *data)
struct lu_nid_range * range_search (struct nodemap_range_tree *nm_range_tree, lnet_nid_t nid)
struct lu_nid_range * range_find (struct nodemap_range_tree *nm_range_tree, lnet_nid_t start_nid, lnet_nid_t end_nid)
int range_parse_nidstring (char *range_string, lnet_nid_t *start_nid, lnet_nid_t *end_nid)
void range_init_tree (void)
struct lu_idmap * idmap_create (__u32 client_id, __u32 fs_id)
Allocate the lu_idmap structure.
void idmap_insert (enum nodemap_id_type id_type, struct lu_idmap *idmap, struct lu_nodemap *nodemap)
Insert idmap into the proper trees.
void idmap_delete (enum nodemap_id_type id_type, struct lu_idmap *idmap, struct lu_nodemap *nodemap)
Delete idmap from the correct nodemap tree.
void idmap_delete_tree (struct lu_nodemap *nodemap)
struct lu_idmap * idmap_search (struct lu_nodemap *nodemap, enum nodemap_tree_type, enum nodemap_id_type id_type, __u32 id)
Search for an existing id in the nodemap trees.
int nm_member_add (struct lu_nodemap *nodemap, struct obd_export *exp)
Add a member export to a nodemap.
void nm_member_del (struct lu_nodemap *nodemap, struct obd_export *exp)
Delete a member from a member list.
void nm_member_delete_list (struct lu_nodemap *nodemap)
Delete a member list from a nodemap.
struct lu_nodemap * nodemap_classify_nid (lnet_nid_t nid)
Classify the nid into the proper nodemap.
void nm_member_reclassify_nodemap (struct lu_nodemap *nodemap)
Reclassify the members of a nodemap after range changes or activation.
void nm_member_revoke_locks (struct lu_nodemap *nodemap)
Revoke the locks for member exports.
void nm_member_revoke_all (void)
Revoke locks for all nodemaps.
int nodemap_add_idmap_helper (struct lu_nodemap *nodemap, enum nodemap_id_type id_type, const __u32 map[2])
add an idmap to the proper nodemap trees
int nodemap_add_range_helper (struct nodemap_config *config, struct lu_nodemap *nodemap, const lnet_nid_t nid[2], unsigned int range_id)
struct rb_node * nm_rb_next_postorder (const struct rb_node *node)
struct rb_node * nm_rb_first_postorder (const struct rb_root *root)
int nodemap_idx_nodemap_add (const struct lu_nodemap *nodemap)
int nodemap_idx_nodemap_update (const struct lu_nodemap *nodemap)
int nodemap_idx_nodemap_del (const struct lu_nodemap *nodemap)
int nodemap_idx_idmap_add (const struct lu_nodemap *nodemap, enum nodemap_id_type id_type, const __u32 map[2])
int nodemap_idx_idmap_del (const struct lu_nodemap *nodemap, enum nodemap_id_type id_type, const __u32 map[2])
int nodemap_idx_range_add (const struct lu_nid_range *range, const lnet_nid_t nid[2])
int nodemap_idx_range_del (const struct lu_nid_range *range)
int nodemap_idx_nodemap_activate (bool value)
Variables
struct proc_dir_entry * proc_lustre_nodemap_root
bool nodemap_active
struct mutex active_config_lock
struct nodemap_config * active_config
Define Documentation
#define DEFAULT_NODEMAP "default"
Definition at line 36 of file nodemap_internal.h.
#define nm_rbtree_postorder_for_each_entry_safe (pos, n, root, field)
Value:
for (pos = nm_rb_first_postorder(root) ?                        \
                rb_entry(nm_rb_first_postorder(root), typeof(*pos),     \
                field) : NULL,                                          \
                n = (pos && nm_rb_next_postorder(&pos->field)) ?        \
                rb_entry(nm_rb_next_postorder(&pos->field),             \
                typeof(*pos), field) : NULL;                            \
                pos != NULL;                                            \
                pos = n,                                                \
                n = (pos && nm_rb_next_postorder(&pos->field)) ?        \
                rb_entry(nm_rb_next_postorder(&pos->field),             \
                typeof(*pos), field) : NULL)
Definition at line 198 of file nodemap_internal.h.
Referenced by idmap_delete_tree(), and nodemap_idx_nodemap_del().
#define NM_TYPE_MASK 0x0FFFFFFF
Definition at line 122 of file nodemap_internal.h.
Referenced by nm_idx_set_type().
#define NM_TYPE_SHIFT 28
Definition at line 123 of file nodemap_internal.h.
Referenced by nm_idx_get_type(), and nm_idx_set_type().
#define NODEMAP_NOBODY_GID 99
Definition at line 41 of file nodemap_internal.h.
Referenced by nodemap_create().
#define NODEMAP_NOBODY_UID 99
Definition at line 40 of file nodemap_internal.h.
Referenced by nodemap_create().
Enumeration Type Documentation
enum nodemap_idx_type
Enumerator:
NODEMAP_EMPTY_IDX
NODEMAP_CLUSTER_IDX
NODEMAP_RANGE_IDX
NODEMAP_UIDMAP_IDX
NODEMAP_GIDMAP_IDX
NODEMAP_GLOBAL_IDX
Definition at line 113 of file nodemap_internal.h.
Function Documentation
struct lu_idmap* idmap_create (__u32 client_id, __u32 fs_id) [read]
Allocate the lu_idmap structure.
Parameters:
client_id client uid or gid
fs_id filesystem uid or gid
Return values:
alloated lu_idmap structure on success, NULL otherwise
Definition at line 39 of file nodemap_idmap.c.
References CERROR, lu_idmap::id_client, lu_idmap::id_client_to_fs, lu_idmap::id_fs, lu_idmap::id_fs_to_client, and OBD_ALLOC_PTR.
Referenced by nodemap_add_idmap_helper().
void idmap_delete (enum nodemap_id_type id_type, struct lu_idmap * idmap, struct lu_nodemap * nodemap)
Delete idmap from the correct nodemap tree.
Parameters:
node_type 0 for UID 1 for GID
idmap idmap to delete
nodemap assoicated idmap
Definition at line 164 of file nodemap_idmap.c.
References lu_idmap::id_client_to_fs, lu_idmap::id_fs_to_client, idmap_destroy(), lu_nodemap::nm_client_to_fs_gidmap, lu_nodemap::nm_client_to_fs_uidmap, lu_nodemap::nm_fs_to_client_gidmap, lu_nodemap::nm_fs_to_client_uidmap, and NODEMAP_UID.
Referenced by nodemap_del_idmap().
void idmap_delete_tree (struct lu_nodemap * nodemap)
Definition at line 251 of file nodemap_idmap.c.
References idmap_destroy(), lu_nodemap::nm_client_to_fs_gidmap, lu_nodemap::nm_fs_to_client_uidmap, and nm_rbtree_postorder_for_each_entry_safe.
Referenced by nodemap_destroy().
void idmap_insert (enum nodemap_id_type id_type, struct lu_idmap * idmap, struct lu_nodemap * nodemap)
Insert idmap into the proper trees.
Parameters:
node_type 0 for UID 1 for GID
idmap lu_idmap structure to insert
nodemap nodemap to associate with the map
Return values:
0 on success
if the mapping exists, this function will delete it and replace it with the new idmap structure
Definition at line 78 of file nodemap_idmap.c.
References lu_idmap::id_client, lu_idmap::id_client_to_fs, lu_idmap::id_fs, lu_idmap::id_fs_to_client, idmap_destroy(), lu_nodemap::nm_client_to_fs_gidmap, lu_nodemap::nm_client_to_fs_uidmap, lu_nodemap::nm_fs_to_client_gidmap, lu_nodemap::nm_fs_to_client_uidmap, and NODEMAP_UID.
Referenced by nodemap_add_idmap_helper().
struct lu_idmap* idmap_search (struct lu_nodemap * nodemap, enum nodemap_tree_type tree_type, enum nodemap_id_type id_type, const __u32 id) [read]
Search for an existing id in the nodemap trees.
Parameters:
nodemap nodemap trees to search
tree_type 0 for filesystem to client maps 1 for client to filesystem maps
id_type 0 for UID 1 for GID
id numeric id for which to search
Return values:
lu_idmap structure with the map on success
Definition at line 196 of file nodemap_idmap.c.
References lu_idmap::id_client, lu_idmap::id_client_to_fs, lu_idmap::id_fs, lu_idmap::id_fs_to_client, lu_nodemap::nm_client_to_fs_gidmap, lu_nodemap::nm_client_to_fs_uidmap, lu_nodemap::nm_fs_to_client_gidmap, lu_nodemap::nm_fs_to_client_uidmap, NODEMAP_CLIENT_TO_FS, NODEMAP_FS_TO_CLIENT, NODEMAP_GID, and NODEMAP_UID.
Referenced by nodemap_del_idmap(), and nodemap_map_id().
int lprocfs_nodemap_register (struct lu_nodemap * nodemap, bool is_default)
Register the proc directory for a nodemap.
Parameters:
nodemap nodemap to make the proc dir for
is_default,: 1 if default nodemap
Return values:
0 success
Definition at line 1165 of file nodemap_lproc.c.
References CERROR, GOTO, list_add(), lprocfs_add_vars(), lprocfs_remove(), lu_nodemap::nm_name, lu_nodemap::nm_pde_data, nodemap_pde::npe_list_member, nodemap_pde::npe_name, nodemap_pde::npe_proc_entry, OBD_ALLOC_PTR, OBD_FREE_PTR, and proc_lustre_nodemap_root.
Referenced by nodemap_add(), and nodemap_config_set_active().
void lprocfs_nodemap_remove (struct nodemap_pde * nodemap_pde)
Remove a nodemap's procfs entry and related data.
Definition at line 1151 of file nodemap_lproc.c.
References list_del(), lprocfs_remove(), nodemap_pde::npe_list_member, nodemap_pde::npe_proc_entry, and OBD_FREE_PTR.
Referenced by nodemap_del(), and nodemap_destroy().
static enum nodemap_idx_type nm_idx_get_type (unsigned int id) [inline, static]
Definition at line 125 of file nodemap_internal.h.
References NM_TYPE_SHIFT.
Referenced by nodemap_process_keyrec().
static __u32 nm_idx_set_type (unsigned int id, enum nodemap_idx_type t) [inline, static]
Definition at line 130 of file nodemap_internal.h.
References NM_TYPE_MASK, and NM_TYPE_SHIFT.
Referenced by nodemap_cluster_key_init(), nodemap_global_key_init(), nodemap_idmap_key_init(), nodemap_process_keyrec(), and nodemap_range_key_init().
int nm_member_add (struct lu_nodemap * nodemap, struct obd_export * exp)
Add a member export to a nodemap.
Parameters:
nodemap nodemap to add to
exp obd_export to add
Return values:
-EEXIST export is already part of a different nodemap
-EINVAL export is NULL
Definition at line 79 of file nodemap_member.c.
References class_export_get(), CWARN, obd_export::exp_client_uuid, list_add(), list_empty(), lu_nodemap::nm_member_list, lu_nodemap::nm_member_list_lock, lu_nodemap::nm_name, and obd_uuid::uuid.
Referenced by nodemap_add_member().
void nm_member_del (struct lu_nodemap * nodemap, struct obd_export * exp)
Delete a member from a member list.
Parameters:
nodemap nodemap containing list
exp export member to delete
Definition at line 41 of file nodemap_member.c.
References class_export_put(), list_del_init(), and lu_nodemap::nm_member_list_lock.
Referenced by nodemap_del_member().
void nm_member_delete_list (struct lu_nodemap * nodemap)
Delete a member list from a nodemap.
Parameters:
nodemap nodemap to remove the list from
Definition at line 56 of file nodemap_member.c.
References class_export_put(), exp_target_data, list_del_init(), list_for_each_entry_safe, lu_nodemap::nm_member_list, and lu_nodemap::nm_member_list_lock.
Referenced by nodemap_destroy().
void nm_member_reclassify_nodemap (struct lu_nodemap * nodemap)
Reclassify the members of a nodemap after range changes or activation.
This function reclassifies the members of a nodemap based on the member export's NID and the nodemap's new NID ranges. Exports that are no longer classified as being part of this nodemap are moved to the nodemap whose NID ranges contain the export's NID, and their locks are revoked.
Callers should hold the active_config_lock and active_config nmc_range_tree_lock.
Parameters:
nodemap nodemap with members to reclassify
Definition at line 141 of file nodemap_member.c.
References ptlrpc_connection::c_peer, obd_export::exp_connection, exp_target_data, list_add(), list_del_init(), list_for_each_entry_safe, lnet_process_id_t::nid, nm_member_exp_revoke(), lu_nodemap::nm_member_list, lu_nodemap::nm_member_list_lock, nodemap_classify_nid(), and nodemap_putref().
Referenced by nodemap_add_range_helper(), nodemap_del_range(), and nodemap_destroy().
void nm_member_revoke_all (void)
Revoke locks for all nodemaps.
Definition at line 1286 of file nodemap_handler.c.
References active_config_lock, cfs_hash_for_each_safe(), list_for_each_entry_safe, LIST_HEAD(), nm_hash_list_cb(), lu_nodemap::nm_list, nm_member_revoke_locks(), and nodemap_config::nmc_nodemap_hash.
Referenced by nodemap_activate(), and nodemap_config_set_active().
void nm_member_revoke_locks (struct lu_nodemap * nodemap)
Revoke the locks for member exports.
Changing the idmap is akin to deleting the security context. If the locks are not canceled, the client could cache permissions that are no longer correct with the map.
Parameters:
nodemap nodemap that has been altered
Definition at line 190 of file nodemap_member.c.
References exp_target_data, list_for_each_entry_safe, nm_member_exp_revoke(), lu_nodemap::nm_member_list, and lu_nodemap::nm_member_list_lock.
Referenced by nm_member_revoke_all(), nodemap_add_idmap_helper(), nodemap_add_range_helper(), nodemap_del_idmap(), nodemap_del_range(), nodemap_set_allow_root(), nodemap_set_squash_gid(), nodemap_set_squash_uid(), and nodemap_set_trust_client_ids().
struct rb_node* nm_rb_first_postorder (const struct rb_root * root) [read]
Definition at line 68 of file nodemap_rbtree.c.
References nm_rb_left_deepest_node().
struct rb_node* nm_rb_next_postorder (const struct rb_node * node) [read]
Definition at line 55 of file nodemap_rbtree.c.
References nm_rb_left_deepest_node().
int nodemap_add_idmap_helper (struct lu_nodemap * nodemap, enum nodemap_id_type id_type, const __u32 map[2])
add an idmap to the proper nodemap trees
Parameters:
name name of nodemap
id_type NODEMAP_UID or NODEMAP_GID
map array[2] __u32 containing the map values map[0] is client id map[1] is the filesystem id
Return values:
0 on success
Definition at line 396 of file nodemap_handler.c.
References GOTO, idmap_create(), idmap_insert(), lu_nodemap::nm_idmap_lock, and nm_member_revoke_locks().
Referenced by nodemap_add_idmap(), and nodemap_process_keyrec().
int nodemap_add_range_helper (struct nodemap_config * config, struct lu_nodemap * nodemap, const lnet_nid_t nid[2], unsigned int range_id)
Definition at line 644 of file nodemap_handler.c.
References CERROR, GOTO, list_add(), list_del(), nm_member_reclassify_nodemap(), nm_member_revoke_locks(), lu_nodemap::nm_name, lu_nodemap::nm_ranges, nodemap_config::nmc_default_nodemap, nodemap_config::nmc_range_tree, nodemap_config::nmc_range_tree_lock, nodemap_idx_range_add(), range_create(), range_destroy(), range_insert(), and lu_nid_range::rn_list.
Referenced by nodemap_add_range(), and nodemap_process_keyrec().
struct lu_nodemap* nodemap_classify_nid (lnet_nid_t nid) [read]
Classify the nid into the proper nodemap.
Caller must hold active config and nm_range_tree_lock, and call nodemap_putref when done with nodemap.
Parameters:
nid nid to classify
Return values:
nodemap nodemap containing the nid
default_nodemap default nodemap
Definition at line 247 of file nodemap_handler.c.
References nodemap_config::nmc_default_nodemap, nodemap_config::nmc_range_tree, nodemap_getref(), range_search(), and lu_nid_range::rn_nodemap.
Referenced by nm_member_reclassify_nodemap(), nodemap_add_member(), nodemap_test_id(), and nodemap_test_nid().
struct nodemap_config* nodemap_config_alloc (void) [read]
Definition at line 1153 of file nodemap_handler.c.
References nodemap_config::nmc_range_tree_lock, nodemap_init_hash(), OBD_ALLOC_PTR, and OBD_FREE_PTR.
Referenced by nodemap_load_entries(), and nodemap_mod_init().
void nodemap_config_dealloc (struct nodemap_config * config)
Definition at line 1173 of file nodemap_handler.c.
References nodemap_config_cleanup(), and OBD_FREE_PTR.
Referenced by nodemap_config_set_active(), nodemap_load_entries(), nodemap_mod_exit(), and nodemap_mod_init().
void nodemap_config_set_active (struct nodemap_config * config)
Definition at line 1190 of file nodemap_handler.c.
References active_config_lock, cfs_hash_for_each_safe(), cfs_hash_lookup(), ENTRY, EXIT, LASSERT, list_for_each_entry_safe, LIST_HEAD(), lprocfs_nodemap_register(), nm_hash_list_cb(), lu_nodemap::nm_list, nm_member_revoke_all(), lu_nodemap::nm_name, lu_nodemap::nm_pde_data, nodemap_config::nmc_default_nodemap, nodemap_config::nmc_nodemap_hash, nodemap_config::nmc_nodemap_is_active, nodemap_active, nodemap_config_dealloc(), and nodemap_putref().
Referenced by nodemap_load_entries(), and nodemap_mod_init().
struct lu_nodemap* nodemap_create (const char * name, struct nodemap_config * config, bool is_default) [read]
Nodemap constructor.
Creates an lu_nodemap structure and assigns sane default member values. If this is the default nodemap, the defaults are the most restictive in xterms of mapping behavior. Otherwise the default flags should be inherited from the default nodemap. The adds nodemap to nodemap_hash.
Requires that the caller take the active_config_lock
Parameters:
name name of nodemap
is_default true if default nodemap
Return values:
nodemap success
-EINVAL invalid nodemap name
-EEXIST nodemap already exists
-ENOMEM cannot allocate memory for nodemap
Definition at line 772 of file nodemap_handler.c.
References CERROR, cfs_hash_add_unique(), CWARN, GOTO, INIT_LIST_HEAD, LUSTRE_NODEMAP_DEFAULT_ID, lu_nodemap::nm_client_to_fs_gidmap, lu_nodemap::nm_client_to_fs_uidmap, lu_nodemap::nm_fs_to_client_gidmap, lu_nodemap::nm_fs_to_client_uidmap, lu_nodemap::nm_hash, lu_nodemap::nm_id, lu_nodemap::nm_idmap_lock, lu_nodemap::nm_list, lu_nodemap::nm_member_list, lu_nodemap::nm_member_list_lock, lu_nodemap::nm_name, lu_nodemap::nm_ranges, lu_nodemap::nm_refcount, lu_nodemap::nm_squash_gid, lu_nodemap::nm_squash_uid, nodemap_config::nmc_default_nodemap, nodemap_config::nmc_nodemap_hash, nodemap_config::nmc_nodemap_highest_id, lu_nodemap::nmf_allow_root_access, lu_nodemap::nmf_trust_client_ids, nodemap_name_is_valid(), NODEMAP_NOBODY_GID, NODEMAP_NOBODY_UID, OBD_ALLOC_PTR, and OBD_FREE_PTR.
Referenced by nodemap_add(), nodemap_load_entries(), nodemap_mod_init(), and nodemap_process_keyrec().
int nodemap_idx_idmap_add (const struct lu_nodemap * nodemap, enum nodemap_id_type id_type, const __u32 map[2])
Referenced by nodemap_add_idmap().
int nodemap_idx_idmap_del (const struct lu_nodemap * nodemap, enum nodemap_id_type id_type, const __u32 map[2])
Referenced by nodemap_del_idmap().
int nodemap_idx_nodemap_activate (bool value)
Definition at line 469 of file nodemap_storage.c.
References NM_UPDATE, and nodemap_idx_global_add_update().
Referenced by nodemap_activate().
int nodemap_idx_nodemap_add (const struct lu_nodemap * nodemap)
Definition at line 346 of file nodemap_storage.c.
References NM_ADD, and nodemap_idx_nodemap_add_update().
Referenced by nodemap_add().
int nodemap_idx_nodemap_del (const struct lu_nodemap * nodemap)
Definition at line 356 of file nodemap_storage.c.
References ENTRY, lu_idmap::id_client, list_for_each_entry_safe, lu_nodemap::nm_client_to_fs_gidmap, lu_nodemap::nm_fs_to_client_uidmap, lu_nodemap::nm_id, lu_nodemap::nm_ranges, nm_rbtree_postorder_for_each_entry_safe, nodemap_cluster_key_init(), NODEMAP_GID, nodemap_idmap_key_init(), nodemap_idx_action(), nodemap_idx_delete(), nodemap_range_key_init(), NODEMAP_UID, RETURN, and lu_nid_range::rn_id.
Referenced by nodemap_del().
int nodemap_idx_nodemap_update (const struct lu_nodemap * nodemap)
Definition at line 351 of file nodemap_storage.c.
References NM_UPDATE, and nodemap_idx_nodemap_add_update().
Referenced by nodemap_set_allow_root(), nodemap_set_squash_gid(), nodemap_set_squash_uid(), and nodemap_set_trust_client_ids().
int nodemap_idx_range_add (const struct lu_nid_range * range, const lnet_nid_t nid[2])
Definition at line 405 of file nodemap_storage.c.
References ENTRY, lu_nodemap::nm_id, nodemap_idx_action(), nodemap_idx_insert(), nodemap_range_key_init(), nodemap_range_rec_init(), RETURN, lu_nid_range::rn_id, and lu_nid_range::rn_nodemap.
Referenced by nodemap_add_range_helper().
int nodemap_idx_range_del (const struct lu_nid_range * range)
Definition at line 418 of file nodemap_storage.c.
References ENTRY, lu_nodemap::nm_id, nodemap_idx_action(), nodemap_idx_delete(), nodemap_range_key_init(), RETURN, lu_nid_range::rn_id, and lu_nid_range::rn_nodemap.
Referenced by nodemap_del(), and nodemap_del_range().
struct lu_nodemap* nodemap_lookup (const char * name) [read]
Nodemap lookup.
Look nodemap up in the active_config nodemap hash. Caller should hold the active_config_lock.
Parameters:
name name of nodemap
Return values:
nodemap pointer set to found nodemap
-EINVAL name is not valid
-ENOENT nodemap not found
Definition at line 225 of file nodemap_handler.c.
References cfs_hash_lookup(), nodemap_config::nmc_nodemap_hash, and nodemap_name_is_valid().
Referenced by nodemap_add_idmap(), nodemap_add_range(), nodemap_admin_seq_show(), nodemap_del_idmap(), nodemap_del_range(), nodemap_exports_show(), nodemap_id_seq_show(), nodemap_idmap_show(), nodemap_ranges_show(), nodemap_set_allow_root(), nodemap_set_squash_gid(), nodemap_set_squash_uid(), nodemap_set_trust_client_ids(), nodemap_squash_gid_seq_show(), nodemap_squash_uid_seq_show(), and nodemap_trusted_seq_show().
void nodemap_procfs_exit (void)
Cleanup nodemap proc entry data structures.
Definition at line 1135 of file nodemap_lproc.c.
References list_del(), list_for_each_entry_safe, lprocfs_remove(), nodemap_pde::npe_list_member, OBD_FREE_PTR, and proc_lustre_nodemap_root.
Referenced by nodemap_mod_exit(), and nodemap_mod_init().
int nodemap_procfs_init (void)
Initialize the nodemap procfs directory.
Return values:
0 success
Definition at line 1115 of file nodemap_lproc.c.
References CERROR, lprocfs_register(), LUSTRE_NODEMAP_NAME, proc_lustre_nodemap_root, and proc_lustre_root.
Referenced by nodemap_mod_init().
void nodemap_putref (struct lu_nodemap * nodemap)
Destroy nodemap if last reference is put.
Should be called outside active_config_lock
Definition at line 101 of file nodemap_handler.c.
References LASSERT, lu_nodemap::nm_refcount, and nodemap_destroy().
Referenced by nm_member_reclassify_nodemap(), nodemap_add(), nodemap_add_idmap(), nodemap_add_member(), nodemap_add_range(), nodemap_admin_seq_show(), nodemap_config_cleanup(), nodemap_config_set_active(), nodemap_del(), nodemap_del_idmap(), nodemap_del_range(), nodemap_exports_show(), nodemap_hs_put_locked(), nodemap_id_seq_show(), nodemap_idmap_show(), nodemap_load_entries(), nodemap_mod_init(), nodemap_process_keyrec(), nodemap_ranges_show(), nodemap_set_allow_root(), nodemap_set_squash_gid(), nodemap_set_squash_uid(), nodemap_set_trust_client_ids(), nodemap_squash_gid_seq_show(), nodemap_squash_uid_seq_show(), nodemap_test_id(), nodemap_test_nid(), and nodemap_trusted_seq_show().
struct lu_nid_range* nodemap_range_find (lnet_nid_t start_nid, lnet_nid_t end_nid) [read]
struct lu_nid_range* range_create (struct nodemap_range_tree * nm_range_tree, lnet_nid_t start_nid, lnet_nid_t end_nid, struct lu_nodemap * nodemap, unsigned int range_id) [read]
Referenced by nodemap_add_range_helper().
void range_delete (struct nodemap_range_tree * nm_range_tree, struct lu_nid_range * data)
Definition at line 174 of file nodemap_range.c.
References interval_erase(), interval_is_intree(), list_del(), nodemap_range_tree::nmrt_range_interval_root, range_destroy(), lu_nid_range::rn_list, and lu_nid_range::rn_node.
Referenced by nodemap_config_cleanup(), nodemap_del(), and nodemap_del_range().
void range_destroy (struct lu_nid_range * range)
Definition at line 134 of file nodemap_range.c.
References interval_is_intree(), LASSERT, list_empty(), OBD_FREE_PTR, lu_nid_range::rn_list, and lu_nid_range::rn_node.
Referenced by nodemap_add_range_helper(), and range_delete().
struct lu_nid_range* range_find (struct nodemap_range_tree * nm_range_tree, lnet_nid_t start_nid, lnet_nid_t end_nid) [read]
Definition at line 112 of file nodemap_range.c.
References interval_find(), and nodemap_range_tree::nmrt_range_interval_root.
Referenced by nodemap_del_range().
void range_init_tree (void)
int range_insert (struct nodemap_range_tree * nm_range_tree, struct lu_nid_range * data)
Definition at line 152 of file nodemap_range.c.
References interval_node::in_extent, interval_insert(), interval_is_overlapped(), nodemap_range_tree::nmrt_range_interval_root, and lu_nid_range::rn_node.
Referenced by nodemap_add_range_helper().
int range_parse_nidstring (char * range_string, lnet_nid_t * start_nid, lnet_nid_t * end_nid)
struct lu_nid_range* range_search (struct nodemap_range_tree * nm_range_tree, lnet_nid_t nid) [read]
Definition at line 190 of file nodemap_range.c.
References interval_search(), nodemap_range_tree::nmrt_range_interval_root, range_cb(), and ret.
Referenced by nodemap_classify_nid().
Variable Documentation
struct nodemap_config* active_config
Definition at line 55 of file nodemap_handler.c.
Referenced by nodemap_ranges_show().
struct mutex active_config_lock
Referenced by nm_member_revoke_all(), nodemap_activate(), nodemap_add(), nodemap_add_idmap(), nodemap_add_member(), nodemap_add_range(), nodemap_admin_seq_show(), nodemap_config_set_active(), nodemap_del(), nodemap_del_idmap(), nodemap_del_range(), nodemap_destroy(), nodemap_exports_show(), nodemap_id_seq_show(), nodemap_idmap_show(), nodemap_ranges_show(), nodemap_set_allow_root(), nodemap_set_squash_gid(), nodemap_set_squash_uid(), nodemap_set_trust_client_ids(), nodemap_squash_gid_seq_show(), nodemap_squash_uid_seq_show(), nodemap_test_id(), nodemap_test_nid(), and nodemap_trusted_seq_show().
bool nodemap_active
Definition at line 48 of file nodemap_handler.c.
Referenced by nodemap_activate(), nodemap_active_seq_show(), nodemap_can_setquota(), nodemap_config_set_active(), nodemap_map_acl(), and nodemap_map_id().
struct proc_dir_entry* proc_lustre_nodemap_root
Definition at line 45 of file nodemap_handler.c.
Referenced by lprocfs_nodemap_register(), nodemap_procfs_exit(), and nodemap_procfs_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.