Lustre: lustre/ptlrpc/nodemap_storage.c File Reference
lustre/ptlrpc/nodemap_storage.c File Reference
#include <libcfs/libcfs.h>
#include <linux/err.h>
#include <linux/kernel.h>
#include <linux/list.h>
#include <linux/mutex.h>
#include <linux/string.h>
#include <linux/types.h>
#include <lnet/types.h>
#include <lustre/lustre_idl.h>
#include <dt_object.h>
#include <lu_object.h>
#include <lustre_net.h>
#include <lustre_nodemap.h>
#include <obd_class.h>
#include <obd_support.h>
#include "nodemap_internal.h"
Typedefs
typedef int(* nm_idx_cb_t)(struct lu_env *env, struct dt_object *idx, const struct nodemap_key *nk, const union nodemap_rec *nr)
Enumerations
enum nm_flag_shifts { NM_FL_ALLOW_ROOT_ACCESS = 0x1, NM_FL_TRUST_CLIENT_IDS = 0x2 }
enum nm_add_update { NM_ADD = 0, NM_UPDATE = 1 }
Functions
static LIST_HEAD (ncf_list_head)
static DEFINE_MUTEX (ncf_list_lock)
static void nodemap_cluster_key_init (struct nodemap_key *nk, unsigned int nm_id)
static void nodemap_cluster_rec_init (union nodemap_rec *nr, const struct lu_nodemap *nodemap)
static void nodemap_idmap_key_init (struct nodemap_key *nk, unsigned int nm_id, enum nodemap_id_type id_type, u32 id_client)
static void nodemap_idmap_rec_init (union nodemap_rec *nr, u32 id_fs)
static void nodemap_range_key_init (struct nodemap_key *nk, unsigned int nm_id, unsigned int rn_id)
static void nodemap_range_rec_init (union nodemap_rec *nr, const lnet_nid_t nid[2])
static void nodemap_global_key_init (struct nodemap_key *nk)
static void nodemap_global_rec_init (union nodemap_rec *nr, bool active)
static void nodemap_inc_version (const struct lu_env *env, struct dt_object *nodemap_idx, struct thandle *th)
static int nodemap_idx_insert (struct lu_env *env, struct dt_object *idx, const struct nodemap_key *nk, const union nodemap_rec *nr)
static int nodemap_idx_update (struct lu_env *env, struct dt_object *idx, const struct nodemap_key *nk, const union nodemap_rec *nr)
static int nodemap_idx_delete (struct lu_env *env, struct dt_object *idx, const struct nodemap_key *nk, const union nodemap_rec *unused)
static int nodemap_idx_action (nm_idx_cb_t cb_f, struct nodemap_key *nk, union nodemap_rec *nr)
Iterates through all the registered nodemap_config_files and calls the given callback with the ncf as a parameter, as well as the given key and rec.
static int nodemap_idx_nodemap_add_update (const struct lu_nodemap *nodemap, enum nm_add_update update)
int nodemap_idx_nodemap_add (const struct lu_nodemap *nodemap)
int nodemap_idx_nodemap_update (const struct lu_nodemap *nodemap)
int nodemap_idx_nodemap_del (const struct lu_nodemap *nodemap)
int nodemap_idx_range_add (const struct lu_nid_range *range, const lnet_nid_t nid[2])
int nodemap_idx_range_del (const struct lu_nid_range *range)
int nodemap_idx_idmap_add (const struct lu_nodemap *nodemap, enum nodemap_id_type id_type, const u32 map[2])
int nodemap_idx_idmap_del (const struct lu_nodemap *nodemap, enum nodemap_id_type id_type, const u32 map[2])
static int nodemap_idx_global_add_update (bool value, enum nm_add_update update)
int nodemap_idx_nodemap_activate (bool value)
static int nodemap_process_keyrec (struct nodemap_config *config, const struct nodemap_key *key, const union nodemap_rec *rec, struct lu_nodemap **recent_nodemap)
Process a key/rec pair and modify the new configuration.
static int nodemap_load_entries (const struct lu_env *env, struct dt_object *nodemap_idx)
struct nm_config_file * nm_config_file_register (const struct lu_env *env, struct dt_object *obj)
Register a dt_object representing the config index file.
void nm_config_file_deregister (const struct lu_env *env, struct nm_config_file *ncf)
Deregister a nm_config_file.
Typedef Documentation
typedef int(* nm_idx_cb_t)(struct lu_env *env, struct dt_object *idx, const struct nodemap_key *nk, const union nodemap_rec *nr)
Definition at line 281 of file nodemap_storage.c.
Enumeration Type Documentation
enum nm_add_update
Enumerator:
NM_ADD
NM_UPDATE
Definition at line 321 of file nodemap_storage.c.
enum nm_flag_shifts
Enumerator:
NM_FL_ALLOW_ROOT_ACCESS
NM_FL_TRUST_CLIENT_IDS
Definition at line 68 of file nodemap_storage.c.
Function Documentation
static DEFINE_MUTEX (ncf_list_lock) [static]
static LIST_HEAD (ncf_list_head) [static]
void nm_config_file_deregister (const struct lu_env * env, struct nm_config_file * ncf)
Deregister a nm_config_file.
Should be called by targets during cleanup.
Parameters:
ncf config file to deregister
Definition at line 782 of file nodemap_storage.c.
References dt_object::do_lu, ENTRY, EXIT, list_del(), lu_object_put(), nm_config_file::ncf_list, nm_config_file::ncf_obj, and OBD_FREE_PTR.
Referenced by mgs_fs_cleanup(), and mgs_fs_setup().
struct nm_config_file* nm_config_file_register (const struct lu_env * env, struct dt_object * obj) [read]
Register a dt_object representing the config index file.
This should be called by targets in order to load the nodemap configuration from disk. The dt_object should be created with local_index_find_or_create and the index features should be enabled with do_index_try.
Parameters:
obj dt_object returned by local_index_find_or_create
Return values:
on success: nm_config_file handle for later deregistration
-ENOMEM memory allocation failure
-ENOENT error loading nodemap config
-EINVAL error loading nodemap config
Definition at line 740 of file nodemap_storage.c.
References ENTRY, list_add(), list_del(), list_empty(), nm_config_file::ncf_list, nm_config_file::ncf_obj, nodemap_load_entries(), OBD_ALLOC_PTR, OBD_FREE_PTR, and RETURN.
Referenced by mgs_fs_setup().
static void nodemap_cluster_key_init (struct nodemap_key * nk, unsigned int nm_id) [static]
Definition at line 73 of file nodemap_storage.c.
References cpu_to_le32, nodemap_key::nk_nodemap_id, nodemap_key::nk_unused, nm_idx_set_type(), and NODEMAP_CLUSTER_IDX.
Referenced by nodemap_idx_nodemap_add_update(), and nodemap_idx_nodemap_del().
static void nodemap_cluster_rec_init (union nodemap_rec * nr, const struct lu_nodemap * nodemap) [static]
Definition at line 80 of file nodemap_storage.c.
References CLASSERT, cpu_to_le32, nodemap_rec::ncr, nodemap_cluster_rec::ncr_flags, nodemap_cluster_rec::ncr_name, nodemap_cluster_rec::ncr_squash_gid, nodemap_cluster_rec::ncr_squash_uid, NM_FL_ALLOW_ROOT_ACCESS, NM_FL_TRUST_CLIENT_IDS, lu_nodemap::nm_name, lu_nodemap::nm_squash_gid, lu_nodemap::nm_squash_uid, lu_nodemap::nmf_allow_root_access, and lu_nodemap::nmf_trust_client_ids.
Referenced by nodemap_idx_nodemap_add_update().
static void nodemap_global_key_init (struct nodemap_key * nk) [static]
Definition at line 128 of file nodemap_storage.c.
References cpu_to_le32, nodemap_key::nk_nodemap_id, nodemap_key::nk_unused, nm_idx_set_type(), and NODEMAP_GLOBAL_IDX.
Referenced by nodemap_idx_global_add_update().
static void nodemap_global_rec_init (union nodemap_rec * nr, bool active) [static]
Definition at line 134 of file nodemap_storage.c.
References nodemap_rec::ngr, and nodemap_global_rec::ngr_is_active.
Referenced by nodemap_idx_global_add_update().
static void nodemap_idmap_key_init (struct nodemap_key * nk, unsigned int nm_id, enum nodemap_id_type id_type, u32 id_client) [static]
Definition at line 93 of file nodemap_storage.c.
References cpu_to_le32, nodemap_key::nk_id_client, nodemap_key::nk_nodemap_id, nm_idx_set_type(), NODEMAP_GIDMAP_IDX, NODEMAP_UID, and NODEMAP_UIDMAP_IDX.
Referenced by nodemap_idx_idmap_add(), nodemap_idx_idmap_del(), and nodemap_idx_nodemap_del().
static void nodemap_idmap_rec_init (union nodemap_rec * nr, u32 id_fs) [static]
Definition at line 108 of file nodemap_storage.c.
References cpu_to_le32, nodemap_rec::nir, and nodemap_id_rec::nir_id_fs.
Referenced by nodemap_idx_idmap_add().
static int nodemap_idx_action (nm_idx_cb_t cb_f, struct nodemap_key * nk, union nodemap_rec * nr) [static]
Iterates through all the registered nodemap_config_files and calls the given callback with the ncf as a parameter, as well as the given key and rec.
Parameters:
cb_f callback function to call
nk key of the record to act upon
nr record to act upon, NULL for the delete action
Definition at line 294 of file nodemap_storage.c.
References CWARN, dt_object::do_lu, LCT_LOCAL, lu_device::ld_obd, list_for_each_entry, lu_object::lo_dev, lu_env_fini(), lu_env_init(), nm_config_file::ncf_obj, and obd_device::obd_name.
Referenced by nodemap_idx_global_add_update(), nodemap_idx_idmap_add(), nodemap_idx_idmap_del(), nodemap_idx_nodemap_add_update(), nodemap_idx_nodemap_del(), nodemap_idx_range_add(), and nodemap_idx_range_del().
static int nodemap_idx_delete (struct lu_env * env, struct dt_object * idx, const struct nodemap_key * nk, const union nodemap_rec * unused) [static]
Definition at line 242 of file nodemap_storage.c.
References dt_object::do_lu, dt_declare_delete(), dt_declare_version_set(), dt_delete(), dt_key, dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), GOTO, lu_object::lo_dev, lu2dt_dev(), and nodemap_inc_version().
Referenced by nodemap_idx_idmap_del(), nodemap_idx_nodemap_del(), and nodemap_idx_range_del().
static int nodemap_idx_global_add_update (bool value, enum nm_add_update update) [static]
Definition at line 454 of file nodemap_storage.c.
References ENTRY, NM_UPDATE, nodemap_global_key_init(), nodemap_global_rec_init(), nodemap_idx_action(), nodemap_idx_insert(), nodemap_idx_update(), and RETURN.
Referenced by nodemap_idx_nodemap_activate(), and nodemap_load_entries().
int nodemap_idx_idmap_add (const struct lu_nodemap * nodemap, enum nodemap_id_type id_type, const u32 map[2])
Definition at line 428 of file nodemap_storage.c.
References ENTRY, lu_nodemap::nm_id, nodemap_idmap_key_init(), nodemap_idmap_rec_init(), nodemap_idx_action(), nodemap_idx_insert(), and RETURN.
int nodemap_idx_idmap_del (const struct lu_nodemap * nodemap, enum nodemap_id_type id_type, const u32 map[2])
Definition at line 442 of file nodemap_storage.c.
References ENTRY, lu_nodemap::nm_id, nodemap_idmap_key_init(), nodemap_idx_action(), nodemap_idx_delete(), and RETURN.
static int nodemap_idx_insert (struct lu_env * env, struct dt_object * idx, const struct nodemap_key * nk, const union nodemap_rec * nr) [static]
Definition at line 148 of file nodemap_storage.c.
References CLASSERT, dt_object::do_lu, dt_declare_insert(), dt_declare_version_set(), dt_insert(), dt_key, dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), GOTO, lu_object::lo_dev, lu2dt_dev(), and nodemap_inc_version().
Referenced by nodemap_idx_global_add_update(), nodemap_idx_idmap_add(), nodemap_idx_nodemap_add_update(), and nodemap_idx_range_add().
int nodemap_idx_nodemap_activate (bool value)
Definition at line 469 of file nodemap_storage.c.
References NM_UPDATE, and nodemap_idx_global_add_update().
Referenced by nodemap_activate().
int nodemap_idx_nodemap_add (const struct lu_nodemap * nodemap)
Definition at line 346 of file nodemap_storage.c.
References NM_ADD, and nodemap_idx_nodemap_add_update().
Referenced by nodemap_add().
static int nodemap_idx_nodemap_add_update (const struct lu_nodemap * nodemap, enum nm_add_update update) [static]
Definition at line 326 of file nodemap_storage.c.
References ENTRY, lu_nodemap::nm_id, NM_UPDATE, nodemap_cluster_key_init(), nodemap_cluster_rec_init(), nodemap_idx_action(), nodemap_idx_insert(), nodemap_idx_update(), and RETURN.
Referenced by nodemap_idx_nodemap_add(), nodemap_idx_nodemap_update(), and nodemap_load_entries().
int nodemap_idx_nodemap_del (const struct lu_nodemap * nodemap)
Definition at line 356 of file nodemap_storage.c.
References ENTRY, lu_idmap::id_client, list_for_each_entry_safe, lu_nodemap::nm_client_to_fs_gidmap, lu_nodemap::nm_fs_to_client_uidmap, lu_nodemap::nm_id, lu_nodemap::nm_ranges, nm_rbtree_postorder_for_each_entry_safe, nodemap_cluster_key_init(), NODEMAP_GID, nodemap_idmap_key_init(), nodemap_idx_action(), nodemap_idx_delete(), nodemap_range_key_init(), NODEMAP_UID, RETURN, and lu_nid_range::rn_id.
Referenced by nodemap_del().
int nodemap_idx_nodemap_update (const struct lu_nodemap * nodemap)
Definition at line 351 of file nodemap_storage.c.
References NM_UPDATE, and nodemap_idx_nodemap_add_update().
Referenced by nodemap_set_allow_root(), nodemap_set_squash_gid(), nodemap_set_squash_uid(), and nodemap_set_trust_client_ids().
int nodemap_idx_range_add (const struct lu_nid_range * range, const lnet_nid_t nid[2])
Definition at line 405 of file nodemap_storage.c.
References ENTRY, lu_nodemap::nm_id, nodemap_idx_action(), nodemap_idx_insert(), nodemap_range_key_init(), nodemap_range_rec_init(), RETURN, lu_nid_range::rn_id, and lu_nid_range::rn_nodemap.
Referenced by nodemap_add_range_helper().
int nodemap_idx_range_del (const struct lu_nid_range * range)
Definition at line 418 of file nodemap_storage.c.
References ENTRY, lu_nodemap::nm_id, nodemap_idx_action(), nodemap_idx_delete(), nodemap_range_key_init(), RETURN, lu_nid_range::rn_id, and lu_nid_range::rn_nodemap.
Referenced by nodemap_del(), and nodemap_del_range().
static int nodemap_idx_update (struct lu_env * env, struct dt_object * idx, const struct nodemap_key * nk, const union nodemap_rec * nr) [static]
Definition at line 191 of file nodemap_storage.c.
References dt_object::do_lu, dt_declare_delete(), dt_declare_insert(), dt_declare_version_set(), dt_delete(), dt_insert(), dt_key, dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), dt_write_lock(), dt_write_unlock(), GOTO, lu_object::lo_dev, lu2dt_dev(), and nodemap_inc_version().
Referenced by nodemap_idx_global_add_update(), and nodemap_idx_nodemap_add_update().
static void nodemap_inc_version (const struct lu_env * env, struct dt_object * nodemap_idx, struct thandle * th) [static]
Definition at line 140 of file nodemap_storage.c.
References dt_version_get(), and dt_version_set().
Referenced by nodemap_idx_delete(), nodemap_idx_insert(), and nodemap_idx_update().
static int nodemap_load_entries (const struct lu_env * env, struct dt_object * nodemap_idx) [static]
Definition at line 621 of file nodemap_storage.c.
References CWARN, DEFAULT_NODEMAP, dt_index_operations::dio_it, dt_object::do_index_ops, dt_object::do_lu, dt_read_lock(), dt_read_unlock(), ENTRY, GOTO, lu_device::ld_obd, lu_object::lo_dev, NM_ADD, nodemap_config::nmc_default_nodemap, nodemap_config_alloc(), nodemap_config_dealloc(), nodemap_config_set_active(), nodemap_create(), NODEMAP_GLOBAL_IDX, nodemap_idx_global_add_update(), nodemap_idx_nodemap_add_update(), nodemap_process_keyrec(), nodemap_putref(), obd_device::obd_name, and RETURN.
Referenced by nm_config_file_register().
static int nodemap_process_keyrec (struct nodemap_config * config, const struct nodemap_key * key, const union nodemap_rec * rec, struct lu_nodemap ** recent_nodemap) [static]
Process a key/rec pair and modify the new configuration.
Parameters:
config configuration to update with this key/rec data
key key of the record that was loaded
rec record that was loaded
recent_nodemap last referenced nodemap
Return values:
type of record processed, see enum nodemap_idx_type
-ENOENT range or map loaded before nodemap record
-EINVAL duplicate nodemap cluster records found with different IDs, or nodemap has invalid name
-ENOMEM
Definition at line 487 of file nodemap_storage.c.
References CERROR, cfs_hash_lookup(), CLASSERT, CWARN, GOTO, INIT_LIST_HEAD, le32_to_cpu, le64_to_cpu, list_add(), list_for_each_entry, LUSTRE_NODEMAP_DEFAULT_ID, nodemap_rec::ncr, nodemap_cluster_rec::ncr_flags, nodemap_cluster_rec::ncr_name, nodemap_cluster_rec::ncr_squash_gid, nodemap_cluster_rec::ncr_squash_uid, nodemap_rec::ngr, nodemap_global_rec::ngr_is_active, nodemap_rec::nir, nodemap_id_rec::nir_id_fs, nodemap_key::nk_id_client, nodemap_key::nk_nodemap_id, nodemap_key::nk_range_id, NM_FL_ALLOW_ROOT_ACCESS, NM_FL_TRUST_CLIENT_IDS, lu_nodemap::nm_id, nm_idx_get_type(), nm_idx_set_type(), lu_nodemap::nm_list, lu_nodemap::nm_squash_gid, lu_nodemap::nm_squash_uid, nodemap_config::nmc_default_nodemap, nodemap_config::nmc_nodemap_hash, nodemap_config::nmc_nodemap_highest_id, nodemap_config::nmc_nodemap_is_active, lu_nodemap::nmf_allow_root_access, lu_nodemap::nmf_trust_client_ids, nodemap_add_idmap_helper(), nodemap_add_range_helper(), NODEMAP_CLUSTER_IDX, nodemap_create(), NODEMAP_EMPTY_IDX, NODEMAP_GID, NODEMAP_GIDMAP_IDX, NODEMAP_GLOBAL_IDX, nodemap_putref(), NODEMAP_RANGE_IDX, NODEMAP_UID, NODEMAP_UIDMAP_IDX, nodemap_rec::nrr, nodemap_range_rec::nrr_end_nid, and nodemap_range_rec::nrr_start_nid.
Referenced by nodemap_load_entries().
static void nodemap_range_key_init (struct nodemap_key * nk, unsigned int nm_id, unsigned int rn_id) [static]
Definition at line 113 of file nodemap_storage.c.
References cpu_to_le32, nodemap_key::nk_nodemap_id, nodemap_key::nk_range_id, nm_idx_set_type(), and NODEMAP_RANGE_IDX.
Referenced by nodemap_idx_nodemap_del(), nodemap_idx_range_add(), and nodemap_idx_range_del().
static void nodemap_range_rec_init (union nodemap_rec * nr, const lnet_nid_t nid[2]) [static]
Definition at line 121 of file nodemap_storage.c.
References cpu_to_le64, nodemap_rec::nrr, nodemap_range_rec::nrr_end_nid, and nodemap_range_rec::nrr_start_nid.
Referenced by nodemap_idx_range_add().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.