Lustre: lustre/ptlrpc/nodemap_lproc.c File Reference
lustre/ptlrpc/nodemap_lproc.c File Reference
#include <lprocfs_status.h>
#include <lustre_net.h>
#include <lustre_export.h>
#include <obd_class.h>
#include <interval_tree.h>
#include "nodemap_internal.h"
Defines
#define NODEMAP_LPROC_ID_LEN 16
#define NODEMAP_LPROC_FLAG_LEN 2
#define NODEMAP_PROC_DEBUG 1
Functions
static LIST_HEAD (nodemap_pde_list)
static int nodemap_idmap_show (struct seq_file *m, void *data)
Reads and prints the idmap for the given nodemap.
static int nodemap_idmap_open (struct inode *inode, struct file *file)
Attaches nodemap_idmap_show to proc file.
static int nodemap_ranges_show (struct seq_file *m, void *data)
Reads and prints the NID ranges for the given nodemap.
static int nodemap_ranges_open (struct inode *inode, struct file *file)
Connects nodemap_idmap_show to proc file.
static int nodemap_exports_show (struct seq_file *m, void *data)
Reads and prints the exports attached to the given nodemap.
static int nodemap_exports_open (struct inode *inode, struct file *file)
Attaches nodemap_idmap_show to proc file.
static int nodemap_active_seq_show (struct seq_file *m, void *data)
Reads and prints the active flag for the given nodemap.
static ssize_t nodemap_active_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
Activate/deactivate nodemap.
LPROC_SEQ_FOPS (nodemap_active)
static int nodemap_id_seq_show (struct seq_file *m, void *data)
Reads and prints the nodemap ID for the given nodemap.
LPROC_SEQ_FOPS_RO (nodemap_id)
static int nodemap_squash_uid_seq_show (struct seq_file *m, void *data)
Reads and prints the root squash UID for the given nodemap.
static int nodemap_squash_gid_seq_show (struct seq_file *m, void *data)
Reads and prints the root squash GID for the given nodemap.
static int nodemap_trusted_seq_show (struct seq_file *m, void *data)
Reads and prints the trusted flag for the given nodemap.
static int nodemap_admin_seq_show (struct seq_file *m, void *data)
Reads and prints the admin flag for the given nodemap.
static int nodemap_proc_read_flag (const char __user *buffer, unsigned long count, unsigned int *flag_p)
Helper functions to set nodemap flags.
static ssize_t nodemap_squash_uid_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
Set the squash UID.
static ssize_t nodemap_squash_gid_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
Set the squash GID.
static ssize_t nodemap_trusted_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
Set/unset the trusted flag.
static ssize_t nodemap_admin_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
Set/unset the admin flag.
static ssize_t lprocfs_add_nodemap_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
Add a nodemap.
LPROC_SEQ_FOPS_WO_TYPE (nodemap, add_nodemap)
static ssize_t lprocfs_del_nodemap_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
Delete a nodemap.
LPROC_SEQ_FOPS_WO_TYPE (nodemap, del_nodemap)
static int parse_nids (char *rangestr, lnet_nid_t nids[2])
Helper function to parse a NID string.
static ssize_t lprocfs_add_nodemap_range_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
Add a NID range to nodemap.
LPROC_SEQ_FOPS_WO_TYPE (nodemap, add_nodemap_range)
static ssize_t lprocfs_del_nodemap_range_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
Delete a NID range from nodemap.
LPROC_SEQ_FOPS_WO_TYPE (nodemap, del_nodemap_range)
static ssize_t lprocfs_add_nodemap_idmap_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
Add an idmap to nodemap.
LPROC_SEQ_FOPS_WO_TYPE (nodemap, add_nodemap_idmap)
static ssize_t lprocfs_del_nodemap_idmap_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
Delete an idmap from nodemap.
LPROC_SEQ_FOPS_WO_TYPE (nodemap, del_nodemap_idmap)
LPROC_SEQ_FOPS (nodemap_trusted)
LPROC_SEQ_FOPS (nodemap_admin)
LPROC_SEQ_FOPS (nodemap_squash_uid)
LPROC_SEQ_FOPS (nodemap_squash_gid)
int nodemap_procfs_init (void)
Initialize the nodemap procfs directory.
void nodemap_procfs_exit (void)
Cleanup nodemap proc entry data structures.
void lprocfs_nodemap_remove (struct nodemap_pde *nm_pde)
Remove a nodemap's procfs entry and related data.
int lprocfs_nodemap_register (struct lu_nodemap *nodemap, bool is_default)
Register the proc directory for a nodemap.
Variables
static struct lprocfs_vars lprocfs_nm_module_vars []
struct file_operations nodemap_ranges_fops
struct file_operations nodemap_idmap_fops
struct file_operations nodemap_exports_fops
static struct lprocfs_vars lprocfs_nodemap_vars []
static struct lprocfs_vars lprocfs_default_nodemap_vars []
Define Documentation
#define NODEMAP_LPROC_FLAG_LEN 2
Definition at line 31 of file nodemap_lproc.c.
Referenced by nodemap_active_seq_write(), and nodemap_proc_read_flag().
#define NODEMAP_LPROC_ID_LEN 16
Definition at line 30 of file nodemap_lproc.c.
Referenced by nodemap_squash_gid_seq_write(), and nodemap_squash_uid_seq_write().
#define NODEMAP_PROC_DEBUG 1
Definition at line 44 of file nodemap_lproc.c.
Function Documentation
static LIST_HEAD (nodemap_pde_list) [static]
Referenced by kgnilnd_complete_closed_conn(), kgnilnd_del_conn_or_peer(), kgnilnd_report_node_state(), kgnilnd_reset_stack(), lu_cache_shrink_scan(), nm_member_revoke_all(), nodemap_config_cleanup(), nodemap_config_set_active(), osp_invalidate_request(), and tgt_cancel_slc_locks().
LPROC_SEQ_FOPS (nodemap_squash_gid)
LPROC_SEQ_FOPS (nodemap_squash_uid)
LPROC_SEQ_FOPS (nodemap_admin)
LPROC_SEQ_FOPS (nodemap_trusted)
LPROC_SEQ_FOPS (nodemap_active)
LPROC_SEQ_FOPS_RO (nodemap_id)
LPROC_SEQ_FOPS_WO_TYPE (nodemap , del_nodemap_idmap)
LPROC_SEQ_FOPS_WO_TYPE (nodemap , add_nodemap_idmap)
LPROC_SEQ_FOPS_WO_TYPE (nodemap , del_nodemap_range)
LPROC_SEQ_FOPS_WO_TYPE (nodemap , add_nodemap_range)
LPROC_SEQ_FOPS_WO_TYPE (nodemap , del_nodemap)
LPROC_SEQ_FOPS_WO_TYPE (nodemap , add_nodemap)
static ssize_t lprocfs_add_nodemap_idmap_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Add an idmap to nodemap.
Parameters:
[in] file proc file
[in] buffer string, "<nodemap name> <uid|gid> <idmap>"
[in] count buffer length
[in] off unused
Return values:
\a count on success
negative number on error
Definition at line 845 of file nodemap_lproc.c.
References GOTO, LUSTRE_NODEMAP_NAME_LENGTH, name, nodemap_add_idmap(), NODEMAP_GID, nodemap_parse_idmap(), and NODEMAP_UID.
static ssize_t lprocfs_add_nodemap_range_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Add a NID range to nodemap.
Parameters:
[in] file proc file
[in] buffer string, "<nodemap name> <nid range>"
[in] count buffer length
[in] off unused
Return values:
\a count on success
negative number on error
Definition at line 727 of file nodemap_lproc.c.
References GOTO, LNET_NIDSTR_SIZE, LUSTRE_NODEMAP_NAME_LENGTH, name, nodemap_add_range(), and parse_nids().
static ssize_t lprocfs_add_nodemap_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Add a nodemap.
Parameters:
[in] file proc file
[in] buffer string, name of the nodemap to add
[in] count buffer length
[in] off unused
Return values:
\a count on success
negative number on error
Definition at line 602 of file nodemap_lproc.c.
References LUSTRE_NODEMAP_NAME_LENGTH, and nodemap_add().
static ssize_t lprocfs_del_nodemap_idmap_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Delete an idmap from nodemap.
Parameters:
[in] file proc file
[in] buffer string, "<nodemap name> <uid|gid> <idmap>"
[in] count buffer length
[in] off unused
Return values:
\a count on success
negative number on error
Definition at line 914 of file nodemap_lproc.c.
References GOTO, LUSTRE_NODEMAP_NAME_LENGTH, name, nodemap_del_idmap(), NODEMAP_GID, nodemap_parse_idmap(), and NODEMAP_UID.
static ssize_t lprocfs_del_nodemap_range_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Delete a NID range from nodemap.
Parameters:
[in] file proc file
[in] buffer string, "<nodemap name> <nid range>"
[in] count buffer length
[in] off unused
Return values:
\a count on success
negative number on error
Definition at line 786 of file nodemap_lproc.c.
References GOTO, LNET_NIDSTR_SIZE, LUSTRE_NODEMAP_NAME_LENGTH, name, nodemap_del_range(), and parse_nids().
static ssize_t lprocfs_del_nodemap_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Delete a nodemap.
Parameters:
[in] file proc file
[in] buffer string, name of the nodemap to delete
[in] count buffer length
[in] off unused
Return values:
\a count on success
negative number on error
Definition at line 645 of file nodemap_lproc.c.
References LUSTRE_NODEMAP_NAME_LENGTH, and nodemap_del().
int lprocfs_nodemap_register (struct lu_nodemap * nodemap, bool is_default)
Register the proc directory for a nodemap.
Parameters:
nodemap nodemap to make the proc dir for
is_default,: 1 if default nodemap
Return values:
0 success
Definition at line 1165 of file nodemap_lproc.c.
References CERROR, GOTO, list_add(), lprocfs_add_vars(), lprocfs_remove(), lu_nodemap::nm_name, lu_nodemap::nm_pde_data, nodemap_pde::npe_list_member, nodemap_pde::npe_name, nodemap_pde::npe_proc_entry, OBD_ALLOC_PTR, OBD_FREE_PTR, and proc_lustre_nodemap_root.
Referenced by nodemap_add(), and nodemap_config_set_active().
void lprocfs_nodemap_remove (struct nodemap_pde * nm_pde)
Remove a nodemap's procfs entry and related data.
Definition at line 1151 of file nodemap_lproc.c.
References list_del(), lprocfs_remove(), nodemap_pde::npe_list_member, nodemap_pde::npe_proc_entry, and OBD_FREE_PTR.
Referenced by nodemap_del(), and nodemap_destroy().
static int nodemap_active_seq_show (struct seq_file * m, void * data) [static]
Reads and prints the active flag for the given nodemap.
Parameters:
m seq file in proc fs
data unused
Return values:
0 success
Definition at line 240 of file nodemap_lproc.c.
References nodemap_active.
static ssize_t nodemap_active_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Activate/deactivate nodemap.
Parameters:
[in] file proc file
[in] buffer string, "1" or "0" to activate/deactivate nodemap
[in] count buffer length
[in] off unused
Return values:
\a count on success
negative number on error
Definition at line 257 of file nodemap_lproc.c.
References kstrtoul(), nodemap_activate(), and NODEMAP_LPROC_FLAG_LEN.
static int nodemap_admin_seq_show (struct seq_file * m, void * data) [static]
Reads and prints the admin flag for the given nodemap.
Parameters:
m seq file in proc fs
data unused
Return values:
0 success
Definition at line 397 of file nodemap_lproc.c.
References active_config_lock, CERROR, lu_nodemap::nmf_allow_root_access, nodemap_lookup(), and nodemap_putref().
static ssize_t nodemap_admin_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Set/unset the admin flag.
Parameters:
[in] file proc file
[in] buffer string, "1" or "0"
[in] count buffer length
[in] off unused
Return values:
\a count on success
negative number on error
Definition at line 573 of file nodemap_lproc.c.
References nodemap_proc_read_flag(), and nodemap_set_allow_root().
static int nodemap_exports_open (struct inode * inode, struct file * file) [static]
Attaches nodemap_idmap_show to proc file.
Parameters:
inode inode of seq file in proc fs
file seq file
Return values:
0 success
Definition at line 228 of file nodemap_lproc.c.
References nodemap_exports_show().
static int nodemap_exports_show (struct seq_file * m, void * data) [static]
Reads and prints the exports attached to the given nodemap.
Parameters:
m seq file in proc fs, stores nodemap
data unused
Return values:
0 success
Definition at line 183 of file nodemap_lproc.c.
References active_config_lock, ptlrpc_connection::c_peer, CERROR, obd_export::exp_client_uuid, obd_export::exp_connection, exp_target_data, libcfs_nid2str_r(), list_for_each_entry, LNET_NIDSTR_SIZE, lnet_process_id_t::nid, lu_nodemap::nm_member_list, lu_nodemap::nm_member_list_lock, nodemap_lookup(), nodemap_putref(), and obd_uuid::uuid.
Referenced by nodemap_exports_open().
static int nodemap_id_seq_show (struct seq_file * m, void * data) [static]
Reads and prints the nodemap ID for the given nodemap.
Parameters:
m seq file in proc fs
data unused
Return values:
0 success
Definition at line 291 of file nodemap_lproc.c.
References active_config_lock, CERROR, lu_nodemap::nm_id, nodemap_lookup(), and nodemap_putref().
static int nodemap_idmap_open (struct inode * inode, struct file * file) [static]
Attaches nodemap_idmap_show to proc file.
Parameters:
inode inode of seq file in proc fs
file seq file
Return values:
0 success
Definition at line 111 of file nodemap_lproc.c.
References nodemap_idmap_show().
static int nodemap_idmap_show (struct seq_file * m, void * data) [static]
Reads and prints the idmap for the given nodemap.
Parameters:
m seq file in proc fs
data unused
Return values:
0 success
Definition at line 55 of file nodemap_lproc.c.
References active_config_lock, CERROR, lu_idmap::id_client, lu_idmap::id_fs, lu_nodemap::nm_client_to_fs_gidmap, lu_nodemap::nm_client_to_fs_uidmap, lu_nodemap::nm_idmap_lock, nodemap_lookup(), and nodemap_putref().
Referenced by nodemap_idmap_open().
static int nodemap_proc_read_flag (const char __user * buffer, unsigned long count, unsigned int * flag_p) [static]
Helper functions to set nodemap flags.
Parameters:
[in] buffer string, which is "1" or "0" to set/unset flag
[in] count buffer length
[out] flag_p where to store flag value
Return values:
\a count on success
negative number on error
Definition at line 427 of file nodemap_lproc.c.
References kstrtoul(), and NODEMAP_LPROC_FLAG_LEN.
Referenced by nodemap_admin_seq_write(), and nodemap_trusted_seq_write().
void nodemap_procfs_exit (void)
Cleanup nodemap proc entry data structures.
Definition at line 1135 of file nodemap_lproc.c.
References list_del(), list_for_each_entry_safe, lprocfs_remove(), nodemap_pde::npe_list_member, OBD_FREE_PTR, and proc_lustre_nodemap_root.
Referenced by nodemap_mod_exit(), and nodemap_mod_init().
int nodemap_procfs_init (void)
Initialize the nodemap procfs directory.
Return values:
0 success
Definition at line 1115 of file nodemap_lproc.c.
References CERROR, lprocfs_register(), LUSTRE_NODEMAP_NAME, proc_lustre_nodemap_root, and proc_lustre_root.
Referenced by nodemap_mod_init().
static int nodemap_ranges_open (struct inode * inode, struct file * file) [static]
Connects nodemap_idmap_show to proc file.
Parameters:
inode inode of seq file in proc fs
file seq file
Return values:
0 success
Definition at line 171 of file nodemap_lproc.c.
References nodemap_ranges_show().
static int nodemap_ranges_show (struct seq_file * m, void * data) [static]
Reads and prints the NID ranges for the given nodemap.
Parameters:
m seq file in proc fs
data unused
Return values:
0 success
Definition at line 123 of file nodemap_lproc.c.
References active_config, active_config_lock, CERROR, interval_node::in_extent, libcfs_nid2str_r(), list_for_each_entry, LNET_NIDSTR_SIZE, lu_nodemap::nm_ranges, nodemap_config::nmc_range_tree_lock, nodemap_lookup(), nodemap_putref(), lu_nid_range::rn_id, and lu_nid_range::rn_node.
Referenced by nodemap_ranges_open().
static int nodemap_squash_gid_seq_show (struct seq_file * m, void * data) [static]
Reads and prints the root squash GID for the given nodemap.
Parameters:
m seq file in proc fs
data unused
Return values:
0 success
Definition at line 344 of file nodemap_lproc.c.
References active_config_lock, CERROR, lu_nodemap::nm_squash_gid, nodemap_lookup(), and nodemap_putref().
static ssize_t nodemap_squash_gid_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Set the squash GID.
Parameters:
[in] file proc file
[in] buffer string representing squash GID to set
[in] count buffer length
[in] off unused
Return values:
\a count on success
negative number on error
Definition at line 504 of file nodemap_lproc.c.
References kstrtoul(), NODEMAP_LPROC_ID_LEN, and nodemap_set_squash_gid().
static int nodemap_squash_uid_seq_show (struct seq_file * m, void * data) [static]
Reads and prints the root squash UID for the given nodemap.
Parameters:
m seq file in proc fs
data unused
Return values:
0 success
Definition at line 318 of file nodemap_lproc.c.
References active_config_lock, CERROR, lu_nodemap::nm_squash_uid, nodemap_lookup(), and nodemap_putref().
static ssize_t nodemap_squash_uid_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Set the squash UID.
Parameters:
[in] file proc file
[in] buffer string representing squash UID to set
[in] count buffer length
[in] off unused
Return values:
\a count on success
negative number on error
Definition at line 464 of file nodemap_lproc.c.
References kstrtoul(), NODEMAP_LPROC_ID_LEN, and nodemap_set_squash_uid().
static int nodemap_trusted_seq_show (struct seq_file * m, void * data) [static]
Reads and prints the trusted flag for the given nodemap.
Parameters:
m seq file in proc fs
data unused
Return values:
0 success
Definition at line 370 of file nodemap_lproc.c.
References active_config_lock, CERROR, lu_nodemap::nmf_trust_client_ids, nodemap_lookup(), and nodemap_putref().
static ssize_t nodemap_trusted_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Set/unset the trusted flag.
Parameters:
[in] file proc file
[in] buffer string, "1" or "0"
[in] count buffer length
[in] off unused
Return values:
\a count on success
negative number on error
Definition at line 544 of file nodemap_lproc.c.
References nodemap_proc_read_flag(), and nodemap_set_trust_client_ids().
static int parse_nids (char * rangestr, lnet_nid_t nids[2]) [static]
Helper function to parse a NID string.
Parameters:
[in] rangestr string representation of NIDs, see libcfs_str2nid()
[out] nids array of two nids
Return values:
0 on success
negative number on error
Definition at line 686 of file nodemap_lproc.c.
References cfs_free_nidlist(), cfs_nidrange_find_min_max(), cfs_nidrange_is_contiguous(), cfs_parse_nidlist(), INIT_LIST_HEAD, LNET_NIDSTR_SIZE, and nodemap_parse_range().
Referenced by lprocfs_add_nodemap_range_seq_write(), and lprocfs_del_nodemap_range_seq_write().
Variable Documentation
struct lprocfs_vars lprocfs_default_nodemap_vars[] [static]
Initial value:
 {
        {
                .name           = "id",
                .fops           = &nodemap_id_fops,
        },
        {
                .name           = "trusted_nodemap",
                .fops           = &nodemap_trusted_fops,
        },
        {
                .name           = "admin_nodemap",
                .fops           = &nodemap_admin_fops,
        },
        {
                .name           = "squash_uid",
                .fops           = &nodemap_squash_uid_fops,
        },
        {
                .name           = "squash_gid",
                .fops           = &nodemap_squash_gid_fops,
        },
        {
                .name           = "exports",
                .fops           = &nodemap_exports_fops,
        },
        {
                NULL
        }
}
Definition at line 1080 of file nodemap_lproc.c.
struct lprocfs_vars lprocfs_nm_module_vars[] [static]
Definition at line 973 of file nodemap_lproc.c.
struct lprocfs_vars lprocfs_nodemap_vars[] [static]
Definition at line 1042 of file nodemap_lproc.c.
struct file_operations nodemap_exports_fops
Initial value:
 {
        .open                   = nodemap_exports_open,
        .read                   = seq_read,
        .llseek                 = seq_lseek,
        .release                = single_release
}
Definition at line 1035 of file nodemap_lproc.c.
struct file_operations nodemap_idmap_fops
Initial value:
 {
        .open                   = nodemap_idmap_open,
        .read                   = seq_read,
        .llseek                 = seq_lseek,
        .release                = single_release
}
Definition at line 1028 of file nodemap_lproc.c.
struct file_operations nodemap_ranges_fops
Initial value:
 {
        .open                   = nodemap_ranges_open,
        .read                   = seq_read,
        .llseek                 = seq_lseek,
        .release                = single_release
}
Definition at line 1021 of file nodemap_lproc.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.