Lustre: lustre/ptlrpc/nodemap_idmap.c File Reference
lustre/ptlrpc/nodemap_idmap.c File Reference
#include <linux/rbtree.h>
#include <lustre_net.h>
#include "nodemap_internal.h"
Functions
struct lu_idmap * idmap_create (__u32 client_id, __u32 fs_id)
Allocate the lu_idmap structure.
static void idmap_destroy (struct lu_idmap *idmap)
void idmap_insert (enum nodemap_id_type id_type, struct lu_idmap *idmap, struct lu_nodemap *nodemap)
Insert idmap into the proper trees.
void idmap_delete (enum nodemap_id_type id_type, struct lu_idmap *idmap, struct lu_nodemap *nodemap)
Delete idmap from the correct nodemap tree.
struct lu_idmap * idmap_search (struct lu_nodemap *nodemap, enum nodemap_tree_type tree_type, enum nodemap_id_type id_type, const __u32 id)
Search for an existing id in the nodemap trees.
void idmap_delete_tree (struct lu_nodemap *nodemap)
Function Documentation
struct lu_idmap* idmap_create (__u32 client_id, __u32 fs_id) [read]
Allocate the lu_idmap structure.
Parameters:
client_id client uid or gid
fs_id filesystem uid or gid
Return values:
alloated lu_idmap structure on success, NULL otherwise
Definition at line 39 of file nodemap_idmap.c.
References CERROR, lu_idmap::id_client, lu_idmap::id_client_to_fs, lu_idmap::id_fs, lu_idmap::id_fs_to_client, and OBD_ALLOC_PTR.
Referenced by nodemap_add_idmap_helper().
void idmap_delete (enum nodemap_id_type id_type, struct lu_idmap * idmap, struct lu_nodemap * nodemap)
Delete idmap from the correct nodemap tree.
Parameters:
node_type 0 for UID 1 for GID
idmap idmap to delete
nodemap assoicated idmap
Definition at line 164 of file nodemap_idmap.c.
References lu_idmap::id_client_to_fs, lu_idmap::id_fs_to_client, idmap_destroy(), lu_nodemap::nm_client_to_fs_gidmap, lu_nodemap::nm_client_to_fs_uidmap, lu_nodemap::nm_fs_to_client_gidmap, lu_nodemap::nm_fs_to_client_uidmap, and NODEMAP_UID.
Referenced by nodemap_del_idmap().
void idmap_delete_tree (struct lu_nodemap * nodemap)
Definition at line 251 of file nodemap_idmap.c.
References idmap_destroy(), lu_nodemap::nm_client_to_fs_gidmap, lu_nodemap::nm_fs_to_client_uidmap, and nm_rbtree_postorder_for_each_entry_safe.
Referenced by nodemap_destroy().
static void idmap_destroy (struct lu_idmap * idmap) [static]
Definition at line 57 of file nodemap_idmap.c.
References lu_idmap::id_client_to_fs, lu_idmap::id_fs_to_client, LASSERT, and OBD_FREE_PTR.
Referenced by idmap_delete(), idmap_delete_tree(), and idmap_insert().
void idmap_insert (enum nodemap_id_type id_type, struct lu_idmap * idmap, struct lu_nodemap * nodemap)
Insert idmap into the proper trees.
Parameters:
node_type 0 for UID 1 for GID
idmap lu_idmap structure to insert
nodemap nodemap to associate with the map
Return values:
0 on success
if the mapping exists, this function will delete it and replace it with the new idmap structure
Definition at line 78 of file nodemap_idmap.c.
References lu_idmap::id_client, lu_idmap::id_client_to_fs, lu_idmap::id_fs, lu_idmap::id_fs_to_client, idmap_destroy(), lu_nodemap::nm_client_to_fs_gidmap, lu_nodemap::nm_client_to_fs_uidmap, lu_nodemap::nm_fs_to_client_gidmap, lu_nodemap::nm_fs_to_client_uidmap, and NODEMAP_UID.
Referenced by nodemap_add_idmap_helper().
struct lu_idmap* idmap_search (struct lu_nodemap * nodemap, enum nodemap_tree_type tree_type, enum nodemap_id_type id_type, const __u32 id) [read]
Search for an existing id in the nodemap trees.
Parameters:
nodemap nodemap trees to search
tree_type 0 for filesystem to client maps 1 for client to filesystem maps
id_type 0 for UID 1 for GID
id numeric id for which to search
Return values:
lu_idmap structure with the map on success
Definition at line 196 of file nodemap_idmap.c.
References lu_idmap::id_client, lu_idmap::id_client_to_fs, lu_idmap::id_fs, lu_idmap::id_fs_to_client, lu_nodemap::nm_client_to_fs_gidmap, lu_nodemap::nm_client_to_fs_uidmap, lu_nodemap::nm_fs_to_client_gidmap, lu_nodemap::nm_fs_to_client_uidmap, NODEMAP_CLIENT_TO_FS, NODEMAP_FS_TO_CLIENT, NODEMAP_GID, and NODEMAP_UID.
Referenced by nodemap_del_idmap(), and nodemap_map_id().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.