Lustre: lustre/ptlrpc/nodemap_member.c File Reference
lustre/ptlrpc/nodemap_member.c File Reference
#include <linux/module.h>
#include <lustre_net.h>
#include <obd_class.h>
#include "nodemap_internal.h"
Defines
#define HASH_NODEMAP_MEMBER_BKT_BITS 3
#define HASH_NODEMAP_MEMBER_CUR_BITS 3
#define HASH_NODEMAP_MEMBER_MAX_BITS 7
Functions
void nm_member_del (struct lu_nodemap *nodemap, struct obd_export *exp)
Delete a member from a member list.
void nm_member_delete_list (struct lu_nodemap *nodemap)
Delete a member list from a nodemap.
int nm_member_add (struct lu_nodemap *nodemap, struct obd_export *exp)
Add a member export to a nodemap.
static void nm_member_exp_revoke (struct obd_export *exp)
Revokes the locks on an export if it is attached to an MDT and not in recovery.
void nm_member_reclassify_nodemap (struct lu_nodemap *nodemap)
Reclassify the members of a nodemap after range changes or activation.
void nm_member_revoke_locks (struct lu_nodemap *nodemap)
Revoke the locks for member exports.
Define Documentation
#define HASH_NODEMAP_MEMBER_BKT_BITS 3
Definition at line 31 of file nodemap_member.c.
#define HASH_NODEMAP_MEMBER_CUR_BITS 3
Definition at line 32 of file nodemap_member.c.
#define HASH_NODEMAP_MEMBER_MAX_BITS 7
Definition at line 33 of file nodemap_member.c.
Function Documentation
int nm_member_add (struct lu_nodemap * nodemap, struct obd_export * exp)
Add a member export to a nodemap.
Parameters:
nodemap nodemap to add to
exp obd_export to add
Return values:
-EEXIST export is already part of a different nodemap
-EINVAL export is NULL
Definition at line 79 of file nodemap_member.c.
References class_export_get(), CWARN, obd_export::exp_client_uuid, list_add(), list_empty(), lu_nodemap::nm_member_list, lu_nodemap::nm_member_list_lock, lu_nodemap::nm_name, and obd_uuid::uuid.
Referenced by nodemap_add_member().
void nm_member_del (struct lu_nodemap * nodemap, struct obd_export * exp)
Delete a member from a member list.
Parameters:
nodemap nodemap containing list
exp export member to delete
Definition at line 41 of file nodemap_member.c.
References class_export_put(), list_del_init(), and lu_nodemap::nm_member_list_lock.
Referenced by nodemap_del_member().
void nm_member_delete_list (struct lu_nodemap * nodemap)
Delete a member list from a nodemap.
Parameters:
nodemap nodemap to remove the list from
Definition at line 56 of file nodemap_member.c.
References class_export_put(), exp_target_data, list_del_init(), list_for_each_entry_safe, lu_nodemap::nm_member_list, and lu_nodemap::nm_member_list_lock.
Referenced by nodemap_destroy().
static void nm_member_exp_revoke (struct obd_export * exp) [static]
Revokes the locks on an export if it is attached to an MDT and not in recovery.
As a performance enhancement, the lock revoking process could revoke only the locks that cover files affected by the nodemap change.
Definition at line 118 of file nodemap_member.c.
References obd_export::exp_obd, LUSTRE_MDT_NAME, obd_device::obd_recovering, obd_device::obd_type, and obd_type::typ_name.
Referenced by nm_member_reclassify_nodemap(), and nm_member_revoke_locks().
void nm_member_reclassify_nodemap (struct lu_nodemap * nodemap)
Reclassify the members of a nodemap after range changes or activation.
This function reclassifies the members of a nodemap based on the member export's NID and the nodemap's new NID ranges. Exports that are no longer classified as being part of this nodemap are moved to the nodemap whose NID ranges contain the export's NID, and their locks are revoked.
Callers should hold the active_config_lock and active_config nmc_range_tree_lock.
Parameters:
nodemap nodemap with members to reclassify
Definition at line 141 of file nodemap_member.c.
References ptlrpc_connection::c_peer, obd_export::exp_connection, exp_target_data, list_add(), list_del_init(), list_for_each_entry_safe, lnet_process_id_t::nid, nm_member_exp_revoke(), lu_nodemap::nm_member_list, lu_nodemap::nm_member_list_lock, nodemap_classify_nid(), and nodemap_putref().
Referenced by nodemap_add_range_helper(), nodemap_del_range(), and nodemap_destroy().
void nm_member_revoke_locks (struct lu_nodemap * nodemap)
Revoke the locks for member exports.
Changing the idmap is akin to deleting the security context. If the locks are not canceled, the client could cache permissions that are no longer correct with the map.
Parameters:
nodemap nodemap that has been altered
Definition at line 190 of file nodemap_member.c.
References exp_target_data, list_for_each_entry_safe, nm_member_exp_revoke(), lu_nodemap::nm_member_list, and lu_nodemap::nm_member_list_lock.
Referenced by nm_member_revoke_all(), nodemap_add_idmap_helper(), nodemap_add_range_helper(), nodemap_del_idmap(), nodemap_del_range(), nodemap_set_allow_root(), nodemap_set_squash_gid(), nodemap_set_squash_uid(), and nodemap_set_trust_client_ids().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.