Lustre: lustre/ptlrpc/nodemap_handler.c File Reference
lustre/ptlrpc/nodemap_handler.c File Reference
#include <linux/module.h>
#include <linux/sort.h>
#include <lnet/nidstr.h>
#include <lustre_net.h>
#include <lustre_acl.h>
#include <lustre_eacl.h>
#include <obd_class.h>
#include "nodemap_internal.h"
Defines
#define HASH_NODEMAP_BKT_BITS 3
#define HASH_NODEMAP_CUR_BITS 3
#define HASH_NODEMAP_MAX_BITS 7
#define DEFAULT_NODEMAP "default"
Functions
DEFINE_MUTEX (active_config_lock)
static void nodemap_destroy (struct lu_nodemap *nodemap)
Nodemap destructor.
static void nodemap_getref (struct lu_nodemap *nodemap)
Functions used for the cfs_hash.
void nodemap_putref (struct lu_nodemap *nodemap)
Destroy nodemap if last reference is put.
static __u32 nodemap_hashfn (struct cfs_hash *hash_body, const void *key, unsigned mask)
static void * nodemap_hs_key (struct hlist_node *hnode)
static int nodemap_hs_keycmp (const void *key, struct hlist_node *compared_hnode)
static void * nodemap_hs_hashobject (struct hlist_node *hnode)
static void nodemap_hs_get (struct cfs_hash *hs, struct hlist_node *hnode)
static void nodemap_hs_put_locked (struct cfs_hash *hs, struct hlist_node *hnode)
static int nodemap_init_hash (struct nodemap_config *nmc)
Initialize nodemap_hash.
static bool nodemap_name_is_valid (const char *name)
Check for valid nodemap name.
struct lu_nodemap * nodemap_lookup (const char *name)
Nodemap lookup.
struct lu_nodemap * nodemap_classify_nid (lnet_nid_t nid)
Classify the nid into the proper nodemap.
static bool is_default_nodemap (const struct lu_nodemap *nodemap)
simple check for default nodemap
int nodemap_parse_range (const char *range_str, lnet_nid_t range[2])
parse a nodemap range string into two nids
int nodemap_parse_idmap (char *idmap_str, __u32 idmap[2])
parse a string containing an id map of form "client_id:filesystem_id" into an array of __u32 * for use in mapping functions
int nodemap_add_member (lnet_nid_t nid, struct obd_export *exp)
add a member to a nodemap
void nodemap_del_member (struct obd_export *exp)
delete a member from a nodemap
int nodemap_add_idmap_helper (struct lu_nodemap *nodemap, enum nodemap_id_type id_type, const __u32 map[2])
add an idmap to the proper nodemap trees
int nodemap_add_idmap (const char *name, enum nodemap_id_type id_type, const __u32 map[2])
int nodemap_del_idmap (const char *name, enum nodemap_id_type id_type, const __u32 map[2])
delete idmap from proper nodemap tree
__u32 nodemap_map_id (struct lu_nodemap *nodemap, enum nodemap_id_type id_type, enum nodemap_tree_type tree_type, __u32 id)
mapping function for nodemap idmaps
ssize_t nodemap_map_acl (struct lu_nodemap *nodemap, void *buf, size_t size, enum nodemap_tree_type tree_type)
Map posix ACL entries according to the nodemap membership.
int nodemap_add_range_helper (struct nodemap_config *config, struct lu_nodemap *nodemap, const lnet_nid_t nid[2], unsigned int range_id)
int nodemap_add_range (const char *name, const lnet_nid_t nid[2])
int nodemap_del_range (const char *name, const lnet_nid_t nid[2])
delete a range
struct lu_nodemap * nodemap_create (const char *name, struct nodemap_config *config, bool is_default)
Nodemap constructor.
int nodemap_set_allow_root (const char *name, bool allow_root)
update flag to turn on or off nodemap functions
int nodemap_set_trust_client_ids (const char *name, bool trust_client_ids)
updated trust_client_ids flag for nodemap
int nodemap_set_squash_uid (const char *name, uid_t uid)
update the squash_uid for a nodemap
int nodemap_set_squash_gid (const char *name, gid_t gid)
Update the squash_gid for a nodemap.
bool nodemap_can_setquota (const struct lu_nodemap *nodemap)
Returns true if this nodemap has root user access.
int nodemap_add (const char *nodemap_name)
Add a nodemap.
int nodemap_del (const char *nodemap_name)
Delete a nodemap.
void nodemap_activate (const bool value)
activate nodemap functions
static int nodemap_cleanup_iter_cb (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode, void *nodemap_list_head)
Helper iterator to convert nodemap hash to list.
void nodemap_config_cleanup (struct nodemap_config *config)
Walk the nodemap_hash and remove all nodemaps.
struct nodemap_config * nodemap_config_alloc (void)
void nodemap_config_dealloc (struct nodemap_config *config)
static int nm_hash_list_cb (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode, void *nodemap_list_head)
void nodemap_config_set_active (struct nodemap_config *config)
void nodemap_mod_exit (void)
Cleanup nodemap module on exit.
int nodemap_mod_init (void)
Initialize the nodemap module.
void nm_member_revoke_all (void)
Revoke locks for all nodemaps.
void nodemap_test_nid (lnet_nid_t nid, char *name_buf, size_t name_len)
Returns the nodemap classification for a given nid into an ioctl buffer.
__u32 nodemap_test_id (lnet_nid_t nid, enum nodemap_id_type idtype, __u32 client_id)
Returns the id mapping for a given nid/id pair.
Variables
struct proc_dir_entry * proc_lustre_nodemap_root
bool nodemap_active
struct nodemap_config * active_config
static struct cfs_hash_ops nodemap_hash_operations
Define Documentation
#define DEFAULT_NODEMAP "default"
Definition at line 42 of file nodemap_handler.c.
Referenced by nodemap_del(), nodemap_load_entries(), and nodemap_mod_init().
#define HASH_NODEMAP_BKT_BITS 3
Definition at line 38 of file nodemap_handler.c.
Referenced by nodemap_init_hash().
#define HASH_NODEMAP_CUR_BITS 3
Definition at line 39 of file nodemap_handler.c.
Referenced by nodemap_init_hash().
#define HASH_NODEMAP_MAX_BITS 7
Definition at line 40 of file nodemap_handler.c.
Referenced by nodemap_init_hash().
Function Documentation
DEFINE_MUTEX (active_config_lock)
static bool is_default_nodemap (const struct lu_nodemap * nodemap) [static]
simple check for default nodemap
Definition at line 266 of file nodemap_handler.c.
References lu_nodemap::nm_id.
Referenced by nodemap_add_idmap(), nodemap_add_range(), nodemap_del_idmap(), nodemap_del_range(), and nodemap_map_id().
static int nm_hash_list_cb (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode, void * nodemap_list_head) [static]
Definition at line 1179 of file nodemap_handler.c.
References hlist_entry, list_add(), lu_nodemap::nm_hash, and lu_nodemap::nm_list.
Referenced by nm_member_revoke_all(), and nodemap_config_set_active().
void nm_member_revoke_all (void)
Revoke locks for all nodemaps.
Definition at line 1286 of file nodemap_handler.c.
References active_config_lock, cfs_hash_for_each_safe(), list_for_each_entry_safe, LIST_HEAD(), nm_hash_list_cb(), lu_nodemap::nm_list, nm_member_revoke_locks(), and nodemap_config::nmc_nodemap_hash.
Referenced by nodemap_activate(), and nodemap_config_set_active().
void nodemap_activate (const bool value)
activate nodemap functions
Parameters:
value 1 for on, 0 for off
Definition at line 1088 of file nodemap_handler.c.
References active_config_lock, nm_member_revoke_all(), nodemap_config::nmc_nodemap_is_active, nodemap_active, and nodemap_idx_nodemap_activate().
Referenced by mgs_iocontrol_nodemap(), and nodemap_active_seq_write().
int nodemap_add (const char * nodemap_name)
Add a nodemap.
Parameters:
name name of nodemap
Return values:
0 success
-EINVAL invalid nodemap name
-EEXIST nodemap already exists
-ENOMEM cannot allocate memory for nodemap
Definition at line 1002 of file nodemap_handler.c.
References active_config_lock, lprocfs_nodemap_register(), nodemap_create(), nodemap_idx_nodemap_add(), and nodemap_putref().
Referenced by lprocfs_add_nodemap_seq_write(), and mgs_nodemap_cmd().
int nodemap_add_idmap (const char * name, enum nodemap_id_type id_type, const __u32 map[2])
Definition at line 416 of file nodemap_handler.c.
References active_config_lock, GOTO, is_default_nodemap(), nodemap_add_idmap_helper(), nodemap_idx_idmap_add(), nodemap_lookup(), and nodemap_putref().
Referenced by lprocfs_add_nodemap_idmap_seq_write(), and mgs_nodemap_cmd().
int nodemap_add_idmap_helper (struct lu_nodemap * nodemap, enum nodemap_id_type id_type, const __u32 map[2])
add an idmap to the proper nodemap trees
Parameters:
name name of nodemap
id_type NODEMAP_UID or NODEMAP_GID
map array[2] __u32 containing the map values map[0] is client id map[1] is the filesystem id
Return values:
0 on success
Definition at line 396 of file nodemap_handler.c.
References GOTO, idmap_create(), idmap_insert(), lu_nodemap::nm_idmap_lock, and nm_member_revoke_locks().
Referenced by nodemap_add_idmap(), and nodemap_process_keyrec().
int nodemap_add_member (lnet_nid_t nid, struct obd_export * exp)
add a member to a nodemap
Parameters:
nid nid to add to the members
exp obd_export structure for the connection that is being added
Return values:
-EINVAL export is NULL
-EEXIST export is already member of a nodemap
Definition at line 351 of file nodemap_handler.c.
References active_config_lock, nm_member_add(), nodemap_config::nmc_range_tree_lock, nodemap_classify_nid(), and nodemap_putref().
Referenced by mdt_obd_connect(), mdt_obd_reconnect(), ofd_obd_connect(), and ofd_obd_reconnect().
int nodemap_add_range (const char * name, const lnet_nid_t nid[2])
Definition at line 684 of file nodemap_handler.c.
References active_config_lock, GOTO, is_default_nodemap(), nodemap_add_range_helper(), nodemap_lookup(), and nodemap_putref().
Referenced by lprocfs_add_nodemap_range_seq_write(), and mgs_nodemap_cmd().
int nodemap_add_range_helper (struct nodemap_config * config, struct lu_nodemap * nodemap, const lnet_nid_t nid[2], unsigned int range_id)
Definition at line 644 of file nodemap_handler.c.
References CERROR, GOTO, list_add(), list_del(), nm_member_reclassify_nodemap(), nm_member_revoke_locks(), lu_nodemap::nm_name, lu_nodemap::nm_ranges, nodemap_config::nmc_default_nodemap, nodemap_config::nmc_range_tree, nodemap_config::nmc_range_tree_lock, nodemap_idx_range_add(), range_create(), range_destroy(), range_insert(), and lu_nid_range::rn_list.
Referenced by nodemap_add_range(), and nodemap_process_keyrec().
bool nodemap_can_setquota (const struct lu_nodemap * nodemap)
Returns true if this nodemap has root user access.
Always returns true if nodemaps are not active.
Parameters:
nodemap nodemap to check access for
Definition at line 987 of file nodemap_handler.c.
References lu_nodemap::nmf_allow_root_access, and nodemap_active.
Referenced by mdt_quotactl().
struct lu_nodemap* nodemap_classify_nid (lnet_nid_t nid) [read]
Classify the nid into the proper nodemap.
Caller must hold active config and nm_range_tree_lock, and call nodemap_putref when done with nodemap.
Parameters:
nid nid to classify
Return values:
nodemap nodemap containing the nid
default_nodemap default nodemap
Definition at line 247 of file nodemap_handler.c.
References nodemap_config::nmc_default_nodemap, nodemap_config::nmc_range_tree, nodemap_getref(), range_search(), and lu_nid_range::rn_nodemap.
Referenced by nm_member_reclassify_nodemap(), nodemap_add_member(), nodemap_test_id(), and nodemap_test_nid().
static int nodemap_cleanup_iter_cb (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode, void * nodemap_list_head) [static]
Helper iterator to convert nodemap hash to list.
Parameters:
hs hash structure
bd bucket descriptor
hnode hash node
nodemap_list_head list head for list of nodemaps in hash
Definition at line 1109 of file nodemap_handler.c.
References cfs_hash_bd_del_locked(), hlist_entry, list_add(), lu_nodemap::nm_hash, and lu_nodemap::nm_list.
Referenced by nodemap_config_cleanup().
struct nodemap_config* nodemap_config_alloc (void) [read]
Definition at line 1153 of file nodemap_handler.c.
References nodemap_config::nmc_range_tree_lock, nodemap_init_hash(), OBD_ALLOC_PTR, and OBD_FREE_PTR.
Referenced by nodemap_load_entries(), and nodemap_mod_init().
void nodemap_config_cleanup (struct nodemap_config * config)
Walk the nodemap_hash and remove all nodemaps.
Definition at line 1126 of file nodemap_handler.c.
References cfs_hash_for_each_safe(), cfs_hash_putref(), list_for_each_entry_safe, LIST_HEAD(), lu_nodemap::nm_ranges, nodemap_config::nmc_nodemap_hash, nodemap_config::nmc_range_tree, nodemap_config::nmc_range_tree_lock, nodemap_cleanup_iter_cb(), nodemap_putref(), range_delete(), and lu_nid_range::rn_list.
Referenced by nodemap_config_dealloc().
void nodemap_config_dealloc (struct nodemap_config * config)
Definition at line 1173 of file nodemap_handler.c.
References nodemap_config_cleanup(), and OBD_FREE_PTR.
Referenced by nodemap_config_set_active(), nodemap_load_entries(), nodemap_mod_exit(), and nodemap_mod_init().
void nodemap_config_set_active (struct nodemap_config * config)
Definition at line 1190 of file nodemap_handler.c.
References active_config_lock, cfs_hash_for_each_safe(), cfs_hash_lookup(), ENTRY, EXIT, LASSERT, list_for_each_entry_safe, LIST_HEAD(), lprocfs_nodemap_register(), nm_hash_list_cb(), lu_nodemap::nm_list, nm_member_revoke_all(), lu_nodemap::nm_name, lu_nodemap::nm_pde_data, nodemap_config::nmc_default_nodemap, nodemap_config::nmc_nodemap_hash, nodemap_config::nmc_nodemap_is_active, nodemap_active, nodemap_config_dealloc(), and nodemap_putref().
Referenced by nodemap_load_entries(), and nodemap_mod_init().
struct lu_nodemap* nodemap_create (const char * name, struct nodemap_config * config, bool is_default) [read]
Nodemap constructor.
Creates an lu_nodemap structure and assigns sane default member values. If this is the default nodemap, the defaults are the most restictive in xterms of mapping behavior. Otherwise the default flags should be inherited from the default nodemap. The adds nodemap to nodemap_hash.
Requires that the caller take the active_config_lock
Parameters:
name name of nodemap
is_default true if default nodemap
Return values:
nodemap success
-EINVAL invalid nodemap name
-EEXIST nodemap already exists
-ENOMEM cannot allocate memory for nodemap
Definition at line 772 of file nodemap_handler.c.
References CERROR, cfs_hash_add_unique(), CWARN, GOTO, INIT_LIST_HEAD, LUSTRE_NODEMAP_DEFAULT_ID, lu_nodemap::nm_client_to_fs_gidmap, lu_nodemap::nm_client_to_fs_uidmap, lu_nodemap::nm_fs_to_client_gidmap, lu_nodemap::nm_fs_to_client_uidmap, lu_nodemap::nm_hash, lu_nodemap::nm_id, lu_nodemap::nm_idmap_lock, lu_nodemap::nm_list, lu_nodemap::nm_member_list, lu_nodemap::nm_member_list_lock, lu_nodemap::nm_name, lu_nodemap::nm_ranges, lu_nodemap::nm_refcount, lu_nodemap::nm_squash_gid, lu_nodemap::nm_squash_uid, nodemap_config::nmc_default_nodemap, nodemap_config::nmc_nodemap_hash, nodemap_config::nmc_nodemap_highest_id, lu_nodemap::nmf_allow_root_access, lu_nodemap::nmf_trust_client_ids, nodemap_name_is_valid(), NODEMAP_NOBODY_GID, NODEMAP_NOBODY_UID, OBD_ALLOC_PTR, and OBD_FREE_PTR.
Referenced by nodemap_add(), nodemap_load_entries(), nodemap_mod_init(), and nodemap_process_keyrec().
int nodemap_del (const char * nodemap_name)
Delete a nodemap.
Parameters:
name name of nodemmap
Return values:
0 success
-EINVAL invalid input
-ENOENT no existing nodemap
Definition at line 1033 of file nodemap_handler.c.
References active_config_lock, cfs_hash_del_key(), DEFAULT_NODEMAP, GOTO, list_for_each_entry_safe, lprocfs_nodemap_remove(), lu_nodemap::nm_pde_data, lu_nodemap::nm_ranges, nodemap_config::nmc_nodemap_hash, nodemap_config::nmc_range_tree, nodemap_config::nmc_range_tree_lock, nodemap_idx_nodemap_del(), nodemap_idx_range_del(), nodemap_putref(), range_delete(), RETURN, and lu_nid_range::rn_list.
Referenced by lprocfs_del_nodemap_seq_write(), and mgs_nodemap_cmd().
int nodemap_del_idmap (const char * name, enum nodemap_id_type id_type, const __u32 map[2])
delete idmap from proper nodemap tree
Parameters:
name name of nodemap
id_type NODEMAP_UID or NODEMAP_GID
map array[2] __u32 containing the mapA values map[0] is client id map[1] is the filesystem id
Return values:
0 on success
Definition at line 455 of file nodemap_handler.c.
References active_config_lock, GOTO, idmap_delete(), idmap_search(), is_default_nodemap(), lu_nodemap::nm_idmap_lock, nm_member_revoke_locks(), NODEMAP_CLIENT_TO_FS, nodemap_idx_idmap_del(), nodemap_lookup(), and nodemap_putref().
Referenced by lprocfs_del_nodemap_idmap_seq_write(), and mgs_nodemap_cmd().
void nodemap_del_member (struct obd_export * exp)
delete a member from a nodemap
Parameters:
exp export to remove from a nodemap
Definition at line 376 of file nodemap_handler.c.
References nm_member_del().
Referenced by mdt_obd_connect(), mdt_obd_disconnect(), mdt_obd_reconnect(), ofd_obd_connect(), ofd_obd_disconnect(), and ofd_obd_reconnect().
int nodemap_del_range (const char * name, const lnet_nid_t nid[2])
delete a range
Parameters:
name nodemap name
range_str string containing range
Return values:
0 on success
Delete range from global range tree, and remove it from the list in the associated nodemap.
Definition at line 716 of file nodemap_handler.c.
References active_config_lock, GOTO, is_default_nodemap(), nm_member_reclassify_nodemap(), nm_member_revoke_locks(), nodemap_config::nmc_default_nodemap, nodemap_config::nmc_range_tree, nodemap_config::nmc_range_tree_lock, nodemap_idx_range_del(), nodemap_lookup(), nodemap_putref(), range_delete(), and range_find().
Referenced by lprocfs_del_nodemap_range_seq_write(), and mgs_nodemap_cmd().
static void nodemap_destroy (struct lu_nodemap * nodemap) [static]
Nodemap destructor.
Parameters:
nodemap nodemap to destroy
Definition at line 62 of file nodemap_handler.c.
References active_config_lock, CWARN, ENTRY, EXIT, idmap_delete_tree(), list_empty(), lprocfs_nodemap_remove(), lu_nodemap::nm_idmap_lock, nm_member_delete_list(), lu_nodemap::nm_member_list, nm_member_reclassify_nodemap(), lu_nodemap::nm_pde_data, nodemap_config::nmc_range_tree_lock, and OBD_FREE_PTR.
Referenced by nodemap_putref().
static void nodemap_getref (struct lu_nodemap * nodemap) [static]
Functions used for the cfs_hash.
Definition at line 92 of file nodemap_handler.c.
References lu_nodemap::nm_refcount.
Referenced by nodemap_classify_nid(), and nodemap_hs_get().
static __u32 nodemap_hashfn (struct cfs_hash * hash_body, const void * key, unsigned mask) [static]
Definition at line 110 of file nodemap_handler.c.
References cfs_hash_djb2_hash().
static void nodemap_hs_get (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 140 of file nodemap_handler.c.
References hlist_entry, lu_nodemap::nm_hash, and nodemap_getref().
static void* nodemap_hs_hashobject (struct hlist_node * hnode) [static]
Definition at line 135 of file nodemap_handler.c.
References hlist_entry, and lu_nodemap::nm_hash.
static void* nodemap_hs_key (struct hlist_node * hnode) [static]
Definition at line 116 of file nodemap_handler.c.
References hlist_entry, lu_nodemap::nm_hash, and lu_nodemap::nm_name.
Referenced by nodemap_hs_keycmp().
static int nodemap_hs_keycmp (const void * key, struct hlist_node * compared_hnode) [static]
Definition at line 125 of file nodemap_handler.c.
References nodemap_hs_key().
static void nodemap_hs_put_locked (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 148 of file nodemap_handler.c.
References hlist_entry, lu_nodemap::nm_hash, and nodemap_putref().
static int nodemap_init_hash (struct nodemap_config * nmc) [static]
Initialize nodemap_hash.
Return values:
0 success
-ENOMEM cannot create hash
Definition at line 174 of file nodemap_handler.c.
References CERROR, cfs_hash_create(), CFS_HASH_DEFAULT, CFS_HASH_MAX_THETA, CFS_HASH_MIN_THETA, HASH_NODEMAP_BKT_BITS, HASH_NODEMAP_CUR_BITS, HASH_NODEMAP_MAX_BITS, and nodemap_config::nmc_nodemap_hash.
Referenced by nodemap_config_alloc().
struct lu_nodemap* nodemap_lookup (const char * name) [read]
Nodemap lookup.
Look nodemap up in the active_config nodemap hash. Caller should hold the active_config_lock.
Parameters:
name name of nodemap
Return values:
nodemap pointer set to found nodemap
-EINVAL name is not valid
-ENOENT nodemap not found
Definition at line 225 of file nodemap_handler.c.
References cfs_hash_lookup(), nodemap_config::nmc_nodemap_hash, and nodemap_name_is_valid().
Referenced by nodemap_add_idmap(), nodemap_add_range(), nodemap_admin_seq_show(), nodemap_del_idmap(), nodemap_del_range(), nodemap_exports_show(), nodemap_id_seq_show(), nodemap_idmap_show(), nodemap_ranges_show(), nodemap_set_allow_root(), nodemap_set_squash_gid(), nodemap_set_squash_uid(), nodemap_set_trust_client_ids(), nodemap_squash_gid_seq_show(), nodemap_squash_uid_seq_show(), and nodemap_trusted_seq_show().
ssize_t nodemap_map_acl (struct lu_nodemap * nodemap, void * buf, size_t size, enum nodemap_tree_type tree_type)
Map posix ACL entries according to the nodemap membership.
Removes any squashed ACLs.
Parameters:
lu_nodemap nodemap
buf buffer containing xattr encoded ACLs
size size of ACLs in bytes
tree_type direction of mapping
Return values:
size new size of ACLs in bytes
-EINVAL bad size param, see posix_acl_xattr_count()
Definition at line 580 of file nodemap_handler.c.
References posix_acl_xattr_header::a_entries, cpu_to_le32, posix_acl_xattr_entry::e_id, posix_acl_xattr_entry::e_tag, end, header, le16_to_cpu, le32_to_cpu, lu_nodemap::nm_squash_gid, lu_nodemap::nm_squash_uid, nodemap_active, NODEMAP_GID, nodemap_map_id(), NODEMAP_UID, and unlikely.
Referenced by mdt_reint_setxattr().
__u32 nodemap_map_id (struct lu_nodemap * nodemap, enum nodemap_id_type id_type, enum nodemap_tree_type tree_type, __u32 id)
mapping function for nodemap idmaps
Parameters:
nodemap lu_nodemap structure defining nodemap
node_type NODEMAP_UID or NODEMAP_GID
tree_type NODEMAP_CLIENT_TO_FS or NODEMAP_FS_TO_CLIENT
id id to map
Return values:
mapped id according to the rules below.
if the nodemap_active is false, just return the passed id without mapping
if the id to be looked up is 0, check that root access is allowed and if it is, return 0. Otherwise, return the squash uid or gid.
if the nodemap is configured to trusted the ids from the client system, just return the passwd id without mapping.
if by this point, we haven't returned and the nodemap in question is the default nodemap, return the squash uid or gid.
after these checks, search the proper tree for the mapping, and if found return the mapped value, otherwise return the squash uid or gid.
Definition at line 519 of file nodemap_handler.c.
References lu_idmap::id_client, lu_idmap::id_fs, idmap_search(), is_default_nodemap(), lu_nodemap::nm_idmap_lock, lu_nodemap::nm_squash_gid, lu_nodemap::nm_squash_uid, lu_nodemap::nmf_allow_root_access, lu_nodemap::nmf_trust_client_ids, nodemap_active, NODEMAP_FS_TO_CLIENT, NODEMAP_UID, and unlikely.
Referenced by mdt_pack_attr2body(), mdt_quotactl(), mdt_setattr_unpack_rec(), nodemap_map_acl(), nodemap_test_id(), ofd_quotactl(), old_init_ucred(), old_init_ucred_reint(), and tgt_ost_body_unpack().
void nodemap_mod_exit (void)
Cleanup nodemap module on exit.
Definition at line 1244 of file nodemap_handler.c.
References nodemap_config_dealloc(), and nodemap_procfs_exit().
Referenced by ptlrpc_exit().
int nodemap_mod_init (void)
Initialize the nodemap module.
Definition at line 1253 of file nodemap_handler.c.
References DEFAULT_NODEMAP, GOTO, nodemap_config_alloc(), nodemap_config_dealloc(), nodemap_config_set_active(), nodemap_create(), nodemap_procfs_exit(), nodemap_procfs_init(), and nodemap_putref().
Referenced by ptlrpc_init().
static bool nodemap_name_is_valid (const char * name) [static]
Check for valid nodemap name.
Parameters:
name nodemap name
Return values:
true valid
false invalid
Definition at line 200 of file nodemap_handler.c.
References LUSTRE_NODEMAP_NAME_LENGTH.
Referenced by nodemap_create(), and nodemap_lookup().
int nodemap_parse_idmap (char * idmap_str, __u32 idmap[2])
parse a string containing an id map of form "client_id:filesystem_id" into an array of __u32 * for use in mapping functions
Parameters:
idmap_str map string
idmap array[2] of __u32
Return values:
0 on success
-EINVAL if idmap cannot be parsed
Definition at line 313 of file nodemap_handler.c.
References kstrtoul().
Referenced by lprocfs_add_nodemap_idmap_seq_write(), lprocfs_del_nodemap_idmap_seq_write(), and mgs_nodemap_cmd().
int nodemap_parse_range (const char * range_str, lnet_nid_t range[2])
parse a nodemap range string into two nids
Parameters:
range_str string to parse
range[2] array of two nids 0 on success
Definition at line 278 of file nodemap_handler.c.
References buf, GOTO, libcfs_str2nid(), and LNET_NIDSTR_SIZE.
Referenced by mgs_nodemap_cmd(), and parse_nids().
void nodemap_putref (struct lu_nodemap * nodemap)
Destroy nodemap if last reference is put.
Should be called outside active_config_lock
Definition at line 101 of file nodemap_handler.c.
References LASSERT, lu_nodemap::nm_refcount, and nodemap_destroy().
Referenced by nm_member_reclassify_nodemap(), nodemap_add(), nodemap_add_idmap(), nodemap_add_member(), nodemap_add_range(), nodemap_admin_seq_show(), nodemap_config_cleanup(), nodemap_config_set_active(), nodemap_del(), nodemap_del_idmap(), nodemap_del_range(), nodemap_exports_show(), nodemap_hs_put_locked(), nodemap_id_seq_show(), nodemap_idmap_show(), nodemap_load_entries(), nodemap_mod_init(), nodemap_process_keyrec(), nodemap_ranges_show(), nodemap_set_allow_root(), nodemap_set_squash_gid(), nodemap_set_squash_uid(), nodemap_set_trust_client_ids(), nodemap_squash_gid_seq_show(), nodemap_squash_uid_seq_show(), nodemap_test_id(), nodemap_test_nid(), and nodemap_trusted_seq_show().
int nodemap_set_allow_root (const char * name, bool allow_root)
update flag to turn on or off nodemap functions
Parameters:
name nodemap name
admin_string string containing updated value
Return values:
0 on success
Update admin flag to turn on or off nodemap functions.
Definition at line 864 of file nodemap_handler.c.
References active_config_lock, GOTO, nm_member_revoke_locks(), lu_nodemap::nmf_allow_root_access, nodemap_idx_nodemap_update(), nodemap_lookup(), and nodemap_putref().
Referenced by mgs_nodemap_cmd(), and nodemap_admin_seq_write().
int nodemap_set_squash_gid (const char * name, gid_t gid)
Update the squash_gid for a nodemap.
Parameters:
name nodemap name
gid_string string containing new squash_gid value
Return values:
0 on success
Update the squash_gid for a nodemap. The squash_uid is the gid that the all client gids are mapped to if nodemap is active, the trust_client_ids flag is not set, and the gid is not in the idmap tree.
Definition at line 960 of file nodemap_handler.c.
References active_config_lock, GOTO, nm_member_revoke_locks(), lu_nodemap::nm_squash_gid, nodemap_idx_nodemap_update(), nodemap_lookup(), and nodemap_putref().
Referenced by mgs_nodemap_cmd(), and nodemap_squash_gid_seq_write().
int nodemap_set_squash_uid (const char * name, uid_t uid)
update the squash_uid for a nodemap
Parameters:
name nodemap name
uid_string string containing new squash_uid value
Return values:
0 on success
Update the squash_uid for a nodemap. The squash_uid is the uid that the all client uids are mapped to if nodemap is active, the trust_client_ids flag is not set, and the uid is not in the idmap tree.
Definition at line 927 of file nodemap_handler.c.
References active_config_lock, GOTO, nm_member_revoke_locks(), lu_nodemap::nm_squash_uid, nodemap_idx_nodemap_update(), nodemap_lookup(), and nodemap_putref().
Referenced by mgs_nodemap_cmd(), and nodemap_squash_uid_seq_write().
int nodemap_set_trust_client_ids (const char * name, bool trust_client_ids)
updated trust_client_ids flag for nodemap
Parameters:
name nodemap name
trust_string new value for trust flag
Return values:
0 on success
Update the trust_client_ids flag for a nodemap.
Definition at line 894 of file nodemap_handler.c.
References active_config_lock, GOTO, nm_member_revoke_locks(), lu_nodemap::nmf_trust_client_ids, nodemap_idx_nodemap_update(), nodemap_lookup(), and nodemap_putref().
Referenced by mgs_nodemap_cmd(), and nodemap_trusted_seq_write().
__u32 nodemap_test_id (lnet_nid_t nid, enum nodemap_id_type idtype, __u32 client_id)
Returns the id mapping for a given nid/id pair.
Useful for testing the nodemap configuration to make sure it is working as expected.
Parameters:
nid nid to classify
idtype uid or gid
client_id id to map to fs
Return values:
the mapped fs_id of the given client_id
Definition at line 1339 of file nodemap_handler.c.
References active_config_lock, nodemap_config::nmc_range_tree_lock, nodemap_classify_nid(), NODEMAP_CLIENT_TO_FS, nodemap_map_id(), and nodemap_putref().
Referenced by mgs_iocontrol_nodemap().
void nodemap_test_nid (lnet_nid_t nid, char * name_buf, size_t name_len)
Returns the nodemap classification for a given nid into an ioctl buffer.
Useful for testing the nodemap configuration to make sure it is working as expected.
Parameters:
nid nid to classify
[out] name_buf buffer to write the nodemap name to
name_len length of buffer
Definition at line 1311 of file nodemap_handler.c.
References active_config_lock, lu_nodemap::nm_name, nodemap_config::nmc_range_tree_lock, nodemap_classify_nid(), and nodemap_putref().
Referenced by mgs_iocontrol_nodemap().
Variable Documentation
struct nodemap_config* active_config
Definition at line 55 of file nodemap_handler.c.
Referenced by nodemap_ranges_show().
bool nodemap_active
Definition at line 48 of file nodemap_handler.c.
Referenced by nodemap_activate(), nodemap_active_seq_show(), nodemap_can_setquota(), nodemap_config_set_active(), nodemap_map_acl(), and nodemap_map_id().
struct cfs_hash_ops nodemap_hash_operations [static]
Initial value:
 {
        .hs_hash        = nodemap_hashfn,
        .hs_key         = nodemap_hs_key,
        .hs_keycmp      = nodemap_hs_keycmp,
        .hs_object      = nodemap_hs_hashobject,
        .hs_get         = nodemap_hs_get,
        .hs_put_locked  = nodemap_hs_put_locked,
}
Definition at line 157 of file nodemap_handler.c.
struct proc_dir_entry* proc_lustre_nodemap_root
Definition at line 45 of file nodemap_handler.c.
Referenced by lprocfs_nodemap_register(), nodemap_procfs_exit(), and nodemap_procfs_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.