Lustre: lustre/ptlrpc/nodemap_rbtree.c File Reference
lustre/ptlrpc/nodemap_rbtree.c File Reference
#include <lustre_net.h>
#include <linux/rbtree.h>
#include "nodemap_internal.h"
Functions
static struct rb_node * nm_rb_left_deepest_node (const struct rb_node *node)
struct rb_node * nm_rb_next_postorder (const struct rb_node *node)
struct rb_node * nm_rb_first_postorder (const struct rb_root *root)
Function Documentation
struct rb_node* nm_rb_first_postorder (const struct rb_root * root) [read]
Definition at line 68 of file nodemap_rbtree.c.
References nm_rb_left_deepest_node().
static struct rb_node * nm_rb_left_deepest_node (const struct rb_node * node) [static, read]
Definition at line 43 of file nodemap_rbtree.c.
Referenced by nm_rb_first_postorder(), and nm_rb_next_postorder().
struct rb_node* nm_rb_next_postorder (const struct rb_node * node) [read]
Definition at line 55 of file nodemap_rbtree.c.
References nm_rb_left_deepest_node().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.