Lustre: lustre/ptlrpc/nrs_fifo.c File Reference
lustre/ptlrpc/nrs_fifo.c File Reference
#include <obd_support.h>
#include <obd_class.h>
#include <libcfs/libcfs.h>
#include "ptlrpc_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_RPC
nrs
fifo
The FIFO policy is a logical wrapper around previous, non-NRS functionality.
It schedules RPCs in the same order as they are queued from LNet.
#define NRS_POL_NAME_FIFO "fifo"
static struct ptlrpc_nrs_pol_ops nrs_fifo_ops
FIFO policy operations.
struct ptlrpc_nrs_pol_conf nrs_conf_fifo
FIFO policy configuration.
static int nrs_fifo_start (struct ptlrpc_nrs_policy *policy, char *arg)
Is called before the policy transitions into ptlrpc_nrs_pol_state::NRS_POL_STATE_STARTED; allocates and initializes a policy-specific private data structure.
static void nrs_fifo_stop (struct ptlrpc_nrs_policy *policy)
Is called before the policy transitions into ptlrpc_nrs_pol_state::NRS_POL_STATE_STOPPED; deallocates the policy-specific private data structure.
static int nrs_fifo_res_get (struct ptlrpc_nrs_policy *policy, struct ptlrpc_nrs_request *nrq, const struct ptlrpc_nrs_resource *parent, struct ptlrpc_nrs_resource **resp, bool moving_req)
Is called for obtaining a FIFO policy resource.
static struct ptlrpc_nrs_request * nrs_fifo_req_get (struct ptlrpc_nrs_policy *policy, bool peek, bool force)
Called when getting a request from the FIFO policy for handling, or just peeking; removes the request from the policy when it is to be handled.
static int nrs_fifo_req_add (struct ptlrpc_nrs_policy *policy, struct ptlrpc_nrs_request *nrq)
Adds request nrq to policy's list of queued requests.
static void nrs_fifo_req_del (struct ptlrpc_nrs_policy *policy, struct ptlrpc_nrs_request *nrq)
Removes request nrq from policy's list of queued requests.
static void nrs_fifo_req_stop (struct ptlrpc_nrs_policy *policy, struct ptlrpc_nrs_request *nrq)
Prints a debug statement right before the request nrq stops being handled.
Define Documentation
#define DEBUG_SUBSYSTEM S_RPC
nrs
Definition at line 49 of file nrs_fifo.c.
#define NRS_POL_NAME_FIFO "fifo"
Definition at line 64 of file nrs_fifo.c.
Function Documentation
static int nrs_fifo_req_add (struct ptlrpc_nrs_policy * policy, struct ptlrpc_nrs_request * nrq) [static]
Adds request nrq to policy's list of queued requests.
Parameters:
[in] policy The policy
[in] nrq The request to add
Return values:
0 success; nrs_request_enqueue() assumes this function will always succeed
Only used for debugging
Definition at line 194 of file nrs_fifo.c.
References nrs_fifo_head::fh_list, nrs_fifo_head::fh_res, nrs_fifo_head::fh_sequence, ptlrpc_nrs_request::fifo, nrs_fifo_req::fr_list, nrs_fifo_req::fr_sequence, head, list_add_tail(), ptlrpc_nrs_request::nr_u, and nrs_request_resource().
static void nrs_fifo_req_del (struct ptlrpc_nrs_policy * policy, struct ptlrpc_nrs_request * nrq) [static]
Removes request nrq from policy's list of queued requests.
Parameters:
[in] policy The policy
[in] nrq The request to remove
Definition at line 216 of file nrs_fifo.c.
References ptlrpc_nrs_request::fifo, nrs_fifo_req::fr_list, LASSERT, list_del_init(), list_empty(), and ptlrpc_nrs_request::nr_u.
static struct ptlrpc_nrs_request* nrs_fifo_req_get (struct ptlrpc_nrs_policy * policy, bool peek, bool force) [static, read]
Called when getting a request from the FIFO policy for handling, or just peeking; removes the request from the policy when it is to be handled.
Parameters:
[in] policy The policy
[in] peek When set, signifies that we just want to examine the request, and not handle it, so the request is not removed from the policy.
[in] force Force the policy to return a request; unused in this policy
Return values:
The request to be handled; this is the next request in the FIFO queue
See also:
ptlrpc_nrs_req_get_nolock()
nrs_request_get()
Definition at line 160 of file nrs_fifo.c.
References CDEBUG, D_RPCTRACE, nrs_fifo_head::fh_list, ptlrpc_nrs_request::fifo, nrs_fifo_req::fr_list, nrs_fifo_req::fr_sequence, head, libcfs_id2str(), likely, list_del_init(), list_empty(), list_entry, LPU64, list_head::next, ptlrpc_nrs_request::nr_u, ptlrpc_nrs_pol_desc::pd_name, ptlrpc_nrs_policy::pol_desc, ptlrpc_nrs_policy::pol_private, rq_nrq, ptlrpc_request::rq_peer, and unlikely.
static void nrs_fifo_req_stop (struct ptlrpc_nrs_policy * policy, struct ptlrpc_nrs_request * nrq) [static]
Prints a debug statement right before the request nrq stops being handled.
Parameters:
[in] policy The policy handling the request
[in] nrq The request being handled
See also:
ptlrpc_server_finish_request()
ptlrpc_nrs_req_stop_nolock()
Definition at line 233 of file nrs_fifo.c.
References CDEBUG, D_RPCTRACE, ptlrpc_nrs_request::fifo, nrs_fifo_req::fr_sequence, libcfs_id2str(), LPU64, ptlrpc_nrs_request::nr_u, ptlrpc_nrs_pol_desc::pd_name, ptlrpc_nrs_policy::pol_desc, rq_nrq, and ptlrpc_request::rq_peer.
static int nrs_fifo_res_get (struct ptlrpc_nrs_policy * policy, struct ptlrpc_nrs_request * nrq, const struct ptlrpc_nrs_resource * parent, struct ptlrpc_nrs_resource ** resp, bool moving_req) [static]
Is called for obtaining a FIFO policy resource.
Parameters:
[in] policy The policy on which the request is being asked for
[in] nrq The request for which resources are being taken
[in] parent Parent resource, unused in this policy
[out] resp Resources references are placed in this array
[in] moving_req Signifies limited caller context; unused in this policy
Return values:
1 The FIFO policy only has a one-level resource hierarchy, as since it implements a simple scheduling algorithm in which request priority is determined on the request arrival order, it does not need to maintain a set of resources that would otherwise be used to calculate a request's priority.
See also:
nrs_resource_get_safe()
Just return the resource embedded inside nrs_fifo_head, and end this resource hierarchy reference request.
Definition at line 129 of file nrs_fifo.c.
References ptlrpc_nrs_policy::pol_private.
static int nrs_fifo_start (struct ptlrpc_nrs_policy * policy, char * arg) [static]
Is called before the policy transitions into ptlrpc_nrs_pol_state::NRS_POL_STATE_STARTED; allocates and initializes a policy-specific private data structure.
Parameters:
[in] policy The policy to start
Return values:
-ENOMEM OOM error
0 success
See also:
nrs_policy_register()
nrs_policy_ctl()
Definition at line 79 of file nrs_fifo.c.
References nrs_fifo_head::fh_list, head, INIT_LIST_HEAD, nrs_pol2cptab(), nrs_pol2cptid(), OBD_CPT_ALLOC_PTR, and ptlrpc_nrs_policy::pol_private.
static void nrs_fifo_stop (struct ptlrpc_nrs_policy * policy) [static]
Is called before the policy transitions into ptlrpc_nrs_pol_state::NRS_POL_STATE_STOPPED; deallocates the policy-specific private data structure.
Parameters:
[in] policy The policy to stop
See also:
nrs_policy_stop0()
Definition at line 101 of file nrs_fifo.c.
References nrs_fifo_head::fh_list, head, LASSERT, list_empty(), OBD_FREE_PTR, and ptlrpc_nrs_policy::pol_private.
Variable Documentation
struct ptlrpc_nrs_pol_conf nrs_conf_fifo
Initial value:
 {
        .nc_name                = NRS_POL_NAME_FIFO,
        .nc_ops                 = &nrs_fifo_ops,
        .nc_compat              = nrs_policy_compat_all,
        .nc_flags               = PTLRPC_NRS_FL_FALLBACK |
                                  PTLRPC_NRS_FL_REG_START
}
FIFO policy configuration.
Definition at line 260 of file nrs_fifo.c.
Referenced by ptlrpc_nrs_init().
struct ptlrpc_nrs_pol_ops nrs_fifo_ops [static]
Initial value:
 {
        .op_policy_start        = nrs_fifo_start,
        .op_policy_stop         = nrs_fifo_stop,
        .op_res_get             = nrs_fifo_res_get,
        .op_req_get             = nrs_fifo_req_get,
        .op_req_enqueue         = nrs_fifo_req_add,
        .op_req_dequeue         = nrs_fifo_req_del,
        .op_req_stop            = nrs_fifo_req_stop,
}
FIFO policy operations.
Definition at line 247 of file nrs_fifo.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.