Lustre: lustre/ptlrpc/nrs.c File Reference
lustre/ptlrpc/nrs.c File Reference
#include <obd_support.h>
#include <obd_class.h>
#include <lustre_net.h>
#include <lprocfs_status.h>
#include <libcfs/libcfs.h>
#include "ptlrpc_internal.h"
#define DEBUG_SUBSYSTEM S_RPC
nrs
struct nrs_core nrs_core
NRS core object.
static int nrs_policy_init (struct ptlrpc_nrs_policy *policy)
static void nrs_policy_fini (struct ptlrpc_nrs_policy *policy)
static int nrs_policy_ctl_locked (struct ptlrpc_nrs_policy *policy, enum ptlrpc_nrs_ctl opc, void *arg)
static void nrs_policy_stop0 (struct ptlrpc_nrs_policy *policy)
static int nrs_policy_stop_locked (struct ptlrpc_nrs_policy *policy)
static void nrs_policy_stop_primary (struct ptlrpc_nrs *nrs)
Transitions the nrs NRS head's primary policy to ptlrpc_nrs_pol_state::NRS_POL_STATE_STOPPING and if the policy has no pending usage references, to ptlrpc_nrs_pol_state::NRS_POL_STATE_STOPPED.
static int nrs_policy_start_locked (struct ptlrpc_nrs_policy *policy, char *arg)
Transitions a policy across the ptlrpc_nrs_pol_state range of values, in response to an lprocfs command to start a policy.
static void nrs_policy_get_locked (struct ptlrpc_nrs_policy *policy)
Increases the policy's usage reference count.
static void nrs_policy_put_locked (struct ptlrpc_nrs_policy *policy)
Decreases the policy's usage reference count, and stops the policy in case it was already stopping and have no more outstanding usage references (which indicates it has no more queued or started requests, and can be safely stopped).
static void nrs_policy_put (struct ptlrpc_nrs_policy *policy)
static struct ptlrpc_nrs_policy * nrs_policy_find_locked (struct ptlrpc_nrs *nrs, char *name)
Find and return a policy by name.
static void nrs_resource_put (struct ptlrpc_nrs_resource *res)
Release references for the resource hierarchy moving upwards towards the policy instance resource.
static struct ptlrpc_nrs_resource * nrs_resource_get (struct ptlrpc_nrs_policy *policy, struct ptlrpc_nrs_request *nrq, bool moving_req)
Obtains references for each resource in the resource hierarchy for request nrq if it is to be handled by policy.
static void nrs_resource_get_safe (struct ptlrpc_nrs *nrs, struct ptlrpc_nrs_request *nrq, struct ptlrpc_nrs_resource **resp, bool moving_req)
Obtains resources for the resource hierarchies and policy references for the fallback and current primary policy (if any), that will later be used to handle request nrq.
static void nrs_resource_put_safe (struct ptlrpc_nrs_resource **resp)
Releases references to resource hierarchies and policies, because they are no longer required; used when request handling has been completed, or the request is moving to the high priority NRS head.
static struct ptlrpc_nrs_request * nrs_request_get (struct ptlrpc_nrs_policy *policy, bool peek, bool force)
Obtains an NRS request from policy for handling or examination; the request should be removed in the 'handling' case.
static void nrs_request_enqueue (struct ptlrpc_nrs_request *nrq)
Enqueues request nrq for later handling, via one one the policies for which resources where earlier obtained via nrs_resource_get_safe().
static void nrs_request_stop (struct ptlrpc_nrs_request *nrq)
Called when a request has been handled.
static int nrs_policy_ctl (struct ptlrpc_nrs *nrs, char *name, enum ptlrpc_nrs_ctl opc, void *arg)
Handler for operations that can be carried out on policies.
static int nrs_policy_unregister (struct ptlrpc_nrs *nrs, char *name)
Unregisters a policy by name.
static int nrs_policy_register (struct ptlrpc_nrs *nrs, struct ptlrpc_nrs_pol_desc *desc)
Register a policy from descriptor desc with NRS head nrs.
static void ptlrpc_nrs_req_add_nolock (struct ptlrpc_request *req)
Enqueue request req using one of the policies its resources are referring to.
static void ptlrpc_nrs_hpreq_add_nolock (struct ptlrpc_request *req)
Enqueue a request on the high priority NRS head.
static bool nrs_policy_compatible (const struct ptlrpc_service *svc, const struct ptlrpc_nrs_pol_desc *desc)
Returns a boolean predicate indicating whether the policy described by desc is adequate for use with service svc.
static int nrs_register_policies_locked (struct ptlrpc_nrs *nrs)
Registers all compatible policies in nrs_core.nrs_policies, for NRS head nrs.
static int nrs_svcpt_setup_locked0 (struct ptlrpc_nrs *nrs, struct ptlrpc_service_part *svcpt)
Initializes NRS head nrs of service partition svcpt, and registers all compatible policies in NRS core, with the NRS head.
static int nrs_svcpt_setup_locked (struct ptlrpc_service_part *svcpt)
Allocates a regular and optionally a high-priority NRS head (if the service handles high-priority RPCs), and then registers all available compatible policies on those NRS heads.
static void nrs_svcpt_cleanup_locked (struct ptlrpc_service_part *svcpt)
Unregisters all policies on all available NRS heads in a service partition; called at PTLRPC service unregistration time.
static struct ptlrpc_nrs_pol_desc * nrs_policy_find_desc_locked (const char *name)
Returns the descriptor for a policy as identified by by name.
static int nrs_policy_unregister_locked (struct ptlrpc_nrs_pol_desc *desc)
Removes the policy from all supported NRS heads of all partitions of all PTLRPC services.
int ptlrpc_nrs_policy_register (struct ptlrpc_nrs_pol_conf *conf)
Registers a new policy with NRS core.
int ptlrpc_nrs_policy_unregister (struct ptlrpc_nrs_pol_conf *conf)
Unregisters a previously registered policy with NRS core.
int ptlrpc_service_nrs_setup (struct ptlrpc_service *svc)
Setup NRS heads on all service partitions of service svc, and register all compatible policies on those NRS heads.
void ptlrpc_service_nrs_cleanup (struct ptlrpc_service *svc)
Unregisters all policies on all service partitions of service svc.
void ptlrpc_nrs_req_initialize (struct ptlrpc_service_part *svcpt, struct ptlrpc_request *req, bool hp)
Obtains NRS head resources for request req.
void ptlrpc_nrs_req_finalize (struct ptlrpc_request *req)
Releases resources for a request; is called after the request has been handled.
void ptlrpc_nrs_req_stop_nolock (struct ptlrpc_request *req)
void ptlrpc_nrs_req_add (struct ptlrpc_service_part *svcpt, struct ptlrpc_request *req, bool hp)
Enqueues request req on either the regular or high-priority NRS head of service partition svcpt.
static void nrs_request_removed (struct ptlrpc_nrs_policy *policy)
struct ptlrpc_request * ptlrpc_nrs_req_get_nolock0 (struct ptlrpc_service_part *svcpt, bool hp, bool peek, bool force)
Obtains a request for handling from an NRS head of service partition svcpt.
void ptlrpc_nrs_req_del_nolock (struct ptlrpc_request *req)
Dequeues request req from the policy it has been enqueued on.
bool ptlrpc_nrs_req_pending_nolock (struct ptlrpc_service_part *svcpt, bool hp)
Returns whether there are any requests currently enqueued on any of the policies of service partition's svcpt NRS head specified by hp.
bool ptlrpc_nrs_req_throttling_nolock (struct ptlrpc_service_part *svcpt, bool hp)
Returns whether NRS policy is throttling reqeust.
void ptlrpc_nrs_req_hp_move (struct ptlrpc_request *req)
Moves request req from the regular to the high-priority NRS head.
int ptlrpc_nrs_policy_control (const struct ptlrpc_service *svc, enum ptlrpc_nrs_queue_type queue, char *name, enum ptlrpc_nrs_ctl opc, bool single, void *arg)
Carries out a control operation opc on the policy identified by the human-readable name, on either all partitions, or only on the first partition of service svc.
int ptlrpc_nrs_init (void)
Adds all policies that ship with the ptlrpc module, to NRS core's list of policies nrs_core.nrs_policies.
void ptlrpc_nrs_fini (void)
Removes all policy descriptors from nrs_core::nrs_policies, and frees the policy descriptors.
Define Documentation
#define DEBUG_SUBSYSTEM S_RPC
nrs
Definition at line 42 of file nrs.c.
Function Documentation
static bool nrs_policy_compatible (const struct ptlrpc_service * svc, const struct ptlrpc_nrs_pol_desc * desc) [inline, static]
Returns a boolean predicate indicating whether the policy described by desc is adequate for use with service svc.
Parameters:
[in] svc the service
[in] desc the policy descriptor
Return values:
false the policy is not compatible with the service
true the policy is compatible with the service
Definition at line 885 of file nrs.c.
References ptlrpc_nrs_pol_desc::pd_compat.
Referenced by nrs_policy_unregister_locked(), nrs_register_policies_locked(), ptlrpc_nrs_policy_register(), ptlrpc_service_nrs_cleanup(), and ptlrpc_service_nrs_setup().
static int nrs_policy_ctl (struct ptlrpc_nrs * nrs, char * name, enum ptlrpc_nrs_ctl opc, void * arg) [static]
Handler for operations that can be carried out on policies.
Handles opcodes that are common to all policy types within NRS core, and passes any unknown opcodes to the policy-specific control function.
Parameters:
[in] nrs the NRS head this policy belongs to.
[in] name the human-readable policy name; should be the same as ptlrpc_nrs_pol_desc::pd_name.
[in] opc the opcode of the operation being carried out.
[in,out] arg can be used to pass information in and out between when carrying an operation; usually data that is private to the policy at some level, or generic policy status information.
Return values:
-ve error condition
0 operation was carried out successfully
Unknown opcode, pass it down to the policy-specific control function for handling.
Start policy
Definition at line 655 of file nrs.c.
References ENTRY, GOTO, ptlrpc_nrs::nrs_lock, NRS_POL_STATE_STARTED, NRS_POL_STATE_STOPPED, nrs_policy_ctl_locked(), nrs_policy_find_locked(), nrs_policy_put_locked(), nrs_policy_start_locked(), ptlrpc_nrs_policy::pol_state, PTLRPC_NRS_CTL_START, and RETURN.
Referenced by ptlrpc_nrs_policy_control().
static int nrs_policy_ctl_locked (struct ptlrpc_nrs_policy * policy, enum ptlrpc_nrs_ctl opc, void * arg) [static]
The policy may be stopped, but the lprocfs files and ptlrpc_nrs_policy instances remain present until unregistration time. Do not perform the ctl operation if the policy is stopped, as policy->pol_private will be NULL in such a case.
Definition at line 70 of file nrs.c.
References NRS_POL_STATE_STOPPED, ptlrpc_nrs_pol_ops::op_policy_ctl, ptlrpc_nrs_pol_desc::pd_ops, ptlrpc_nrs_policy::pol_desc, ptlrpc_nrs_policy::pol_state, and RETURN.
Referenced by nrs_policy_ctl().
static struct ptlrpc_nrs_pol_desc* nrs_policy_find_desc_locked (const char * name) [static, read]
Returns the descriptor for a policy as identified by by name.
Parameters:
[in] name the policy name
Return values:
the policy descriptor
NULL
Definition at line 1075 of file nrs.c.
References ENTRY, list_for_each_entry, NRS_POL_NAME_MAX, ptlrpc_nrs_pol_desc::pd_list, ptlrpc_nrs_pol_desc::pd_name, and RETURN.
Referenced by ptlrpc_nrs_policy_register(), and ptlrpc_nrs_policy_unregister().
static struct ptlrpc_nrs_policy* nrs_policy_find_locked (struct ptlrpc_nrs * nrs, char * name) [static, read]
Find and return a policy by name.
Definition at line 356 of file nrs.c.
References list_for_each_entry, NRS_POL_NAME_MAX, nrs_policy_get_locked(), ptlrpc_nrs::nrs_policy_list, ptlrpc_nrs_pol_desc::pd_name, ptlrpc_nrs_policy::pol_desc, and ptlrpc_nrs_policy::pol_list.
Referenced by nrs_policy_ctl(), nrs_policy_register(), and nrs_policy_unregister().
static void nrs_policy_fini (struct ptlrpc_nrs_policy * policy) [static]
Definition at line 61 of file nrs.c.
References LASSERT, ptlrpc_nrs_pol_ops::op_policy_fini, ptlrpc_nrs_pol_desc::pd_ops, ptlrpc_nrs_policy::pol_desc, ptlrpc_nrs_policy::pol_ref, and ptlrpc_nrs_policy::pol_req_queued.
Referenced by nrs_policy_register(), and nrs_policy_unregister().
static void nrs_policy_get_locked (struct ptlrpc_nrs_policy * policy) [inline, static]
Increases the policy's usage reference count.
Definition at line 325 of file nrs.c.
References ptlrpc_nrs_policy::pol_ref.
Referenced by nrs_policy_find_locked(), and nrs_resource_get_safe().
static int nrs_policy_init (struct ptlrpc_nrs_policy * policy) [static]
Definition at line 55 of file nrs.c.
References ptlrpc_nrs_pol_ops::op_policy_init, ptlrpc_nrs_pol_desc::pd_ops, and ptlrpc_nrs_policy::pol_desc.
Referenced by nrs_policy_register().
static void nrs_policy_put (struct ptlrpc_nrs_policy * policy) [static]
Definition at line 346 of file nrs.c.
References ptlrpc_nrs::nrs_lock, nrs_policy_put_locked(), and ptlrpc_nrs_policy::pol_nrs.
Referenced by nrs_resource_get_safe().
static void nrs_policy_put_locked (struct ptlrpc_nrs_policy * policy) [static]
Decreases the policy's usage reference count, and stops the policy in case it was already stopping and have no more outstanding usage references (which indicates it has no more queued or started requests, and can be safely stopped).
Definition at line 336 of file nrs.c.
References LASSERT, NRS_POL_STATE_STOPPING, nrs_policy_stop0(), ptlrpc_nrs_policy::pol_ref, ptlrpc_nrs_policy::pol_state, and unlikely.
Referenced by nrs_policy_ctl(), nrs_policy_put(), nrs_policy_register(), nrs_policy_unregister(), and nrs_resource_put_safe().
static int nrs_policy_register (struct ptlrpc_nrs * nrs, struct ptlrpc_nrs_pol_desc * desc) [static]
Register a policy from descriptor desc with NRS head nrs.
Parameters:
[in] nrs the NRS head on which the policy will be registered.
[in] desc the policy descriptor from which the information will be obtained to register the policy.
Return values:
-ve error
0 success
Definition at line 764 of file nrs.c.
References CERROR, ENTRY, INIT_LIST_HEAD, LASSERT, list_add_tail(), ptlrpc_nrs::nrs_lock, ptlrpc_nrs::nrs_num_pols, NRS_POL_STATE_STOPPED, nrs_policy_find_locked(), nrs_policy_fini(), nrs_policy_init(), ptlrpc_nrs::nrs_policy_list, nrs_policy_put_locked(), nrs_policy_start_locked(), nrs_policy_unregister(), ptlrpc_nrs::nrs_svcpt, OBD_CPT_ALLOC_GFP, OBD_FREE_PTR, ptlrpc_nrs_pol_ops::op_req_dequeue, ptlrpc_nrs_pol_ops::op_req_enqueue, ptlrpc_nrs_pol_ops::op_req_get, ptlrpc_nrs_pol_ops::op_res_get, ptlrpc_nrs_pol_desc::pd_compat, ptlrpc_nrs_pol_desc::pd_flags, ptlrpc_nrs_pol_desc::pd_name, ptlrpc_nrs_pol_desc::pd_ops, ptlrpc_nrs_policy::pol_desc, ptlrpc_nrs_policy::pol_flags, ptlrpc_nrs_policy::pol_list, ptlrpc_nrs_policy::pol_list_queued, ptlrpc_nrs_policy::pol_nrs, ptlrpc_nrs_policy::pol_state, PTLRPC_NRS_FL_REG_START, RETURN, and ptlrpc_service_part::scp_cpt.
Referenced by nrs_register_policies_locked(), and ptlrpc_nrs_policy_register().
static int nrs_policy_start_locked (struct ptlrpc_nrs_policy * policy, char * arg) [static]
Transitions a policy across the ptlrpc_nrs_pol_state range of values, in response to an lprocfs command to start a policy.
If a primary policy different to the current one is specified, this function will transition the new policy to the ptlrpc_nrs_pol_state::NRS_POL_STATE_STARTING and then to ptlrpc_nrs_pol_state::NRS_POL_STATE_STARTED, and will then transition the old primary policy (if there is one) to ptlrpc_nrs_pol_state::NRS_POL_STATE_STOPPING, and if there are no outstanding references on the policy to ptlrpc_nrs_pol_stae::NRS_POL_STATE_STOPPED.
If the fallback policy is specified, this is taken to indicate an instruction to stop the current primary policy, without substituting it with another primary policy, so the primary policy (if any) is transitioned to ptlrpc_nrs_pol_state::NRS_POL_STATE_STOPPING, and if there are no outstanding references on the policy to ptlrpc_nrs_pol_stae::NRS_POL_STATE_STOPPED. In this case, the fallback policy is only left active in the NRS head.
Don't allow multiple starting which is too complex, and has no real benefit.
This is for cases in which the user sets the policy to the fallback policy (currently fifo for all services); i.e. the user is resetting the policy to the default; so we stop the primary policy, if any.
If we reach here, we must be setting up the fallback policy at service startup time, and only a single policy with the nrs_policy_flags::PTLRPC_NRS_FL_FALLBACK flag set can register with NRS core.
Shouldn't start primary policy if w/o fallback policy.
If the policy argument now is different from the last time, stop the policy first and start it again with the new argument.
Increase the module usage count for policies registering from other modules.
Serialize policy starting across the NRS head
This path is only used at PTLRPC service setup time.
And set the newly-started policy as the primary one.
Definition at line 192 of file nrs.c.
References CERROR, ENTRY, GOTO, LASSERT, ptlrpc_nrs::nrs_lock, NRS_POL_ARG_MAX, NRS_POL_STATE_STARTED, NRS_POL_STATE_STARTING, NRS_POL_STATE_STOPPED, NRS_POL_STATE_STOPPING, ptlrpc_nrs::nrs_policy_fallback, ptlrpc_nrs::nrs_policy_primary, ptlrpc_nrs::nrs_policy_starting, nrs_policy_stop_locked(), nrs_policy_stop_primary(), ptlrpc_nrs_pol_ops::op_policy_start, ptlrpc_nrs_pol_desc::pd_name, ptlrpc_nrs_pol_desc::pd_ops, ptlrpc_nrs_pol_desc::pd_owner, ptlrpc_nrs_pol_desc::pd_refs, ptlrpc_nrs_policy::pol_arg, ptlrpc_nrs_policy::pol_desc, ptlrpc_nrs_policy::pol_flags, ptlrpc_nrs_policy::pol_nrs, ptlrpc_nrs_policy::pol_state, PTLRPC_NRS_FL_FALLBACK, and RETURN.
Referenced by nrs_policy_ctl(), and nrs_policy_register().
static void nrs_policy_stop0 (struct ptlrpc_nrs_policy * policy) [static]
Definition at line 87 of file nrs.c.
References ENTRY, EXIT, LASSERT, list_empty(), NRS_POL_STATE_STOPPED, ptlrpc_nrs_pol_ops::op_policy_stop, ptlrpc_nrs_pol_desc::pd_ops, ptlrpc_nrs_pol_desc::pd_owner, ptlrpc_nrs_pol_desc::pd_refs, ptlrpc_nrs_policy::pol_desc, ptlrpc_nrs_policy::pol_list_queued, ptlrpc_nrs_policy::pol_private, ptlrpc_nrs_policy::pol_req_queued, ptlrpc_nrs_policy::pol_req_started, and ptlrpc_nrs_policy::pol_state.
Referenced by nrs_policy_put_locked(), nrs_policy_stop_locked(), and nrs_policy_stop_primary().
static int nrs_policy_stop_locked (struct ptlrpc_nrs_policy * policy) [static]
Definition at line 108 of file nrs.c.
References ENTRY, LASSERT, NRS_POL_STATE_STARTED, NRS_POL_STATE_STARTING, NRS_POL_STATE_STOPPING, ptlrpc_nrs::nrs_policy_fallback, ptlrpc_nrs::nrs_policy_primary, nrs_policy_stop0(), ptlrpc_nrs::nrs_stopping, ptlrpc_nrs_policy::pol_nrs, ptlrpc_nrs_policy::pol_ref, ptlrpc_nrs_policy::pol_state, and RETURN.
Referenced by nrs_policy_start_locked(), and nrs_policy_unregister().
static void nrs_policy_stop_primary (struct ptlrpc_nrs * nrs) [static]
Transitions the nrs NRS head's primary policy to ptlrpc_nrs_pol_state::NRS_POL_STATE_STOPPING and if the policy has no pending usage references, to ptlrpc_nrs_pol_state::NRS_POL_STATE_STOPPED.
Parameters:
[in] nrs the NRS head to carry out this operation on
XXX: This should really be RETURN_EXIT, but the latter does not currently print anything out, and possibly should be fixed to do so.
Definition at line 148 of file nrs.c.
References ENTRY, EXIT, LASSERT, NRS_POL_STATE_STARTED, NRS_POL_STATE_STOPPING, ptlrpc_nrs::nrs_policy_primary, nrs_policy_stop0(), ptlrpc_nrs_policy::pol_ref, and ptlrpc_nrs_policy::pol_state.
Referenced by nrs_policy_start_locked().
static int nrs_policy_unregister (struct ptlrpc_nrs * nrs, char * name) [static]
Unregisters a policy by name.
Parameters:
[in] nrs the NRS head this policy belongs to.
[in] name the human-readable policy name; should be the same as ptlrpc_nrs_pol_desc::pd_name
Return values:
-ve error
0 success
Definition at line 707 of file nrs.c.
References CERROR, ENTRY, LASSERT, list_del(), ptlrpc_nrs::nrs_lock, ptlrpc_nrs::nrs_num_pols, NRS_POL_STATE_STOPPED, nrs_policy_find_locked(), nrs_policy_fini(), nrs_policy_put_locked(), nrs_policy_stop_locked(), OBD_FREE_PTR, ptlrpc_nrs_policy::pol_list, ptlrpc_nrs_policy::pol_private, ptlrpc_nrs_policy::pol_ref, ptlrpc_nrs_policy::pol_req_queued, ptlrpc_nrs_policy::pol_req_started, ptlrpc_nrs_policy::pol_state, and RETURN.
Referenced by nrs_policy_register(), nrs_policy_unregister_locked(), and nrs_svcpt_cleanup_locked().
static int nrs_policy_unregister_locked (struct ptlrpc_nrs_pol_desc * desc) [static]
Removes the policy from all supported NRS heads of all partitions of all PTLRPC services.
Parameters:
[in] desc the policy descriptor to unregister
Return values:
-ve error
0 successfully unregistered policy on all supported NRS heads
Precondition:
mutex_is_locked(&nrs_core.nrs_mutex)
mutex_is_locked(&ptlrpc_all_services_mutex)
Ignore -ENOENT as the policy may not have registered successfully on all service partitions.
Definition at line 1099 of file nrs.c.
References CERROR, ENTRY, LASSERT, list_for_each_entry, nrs_policy_compatible(), nrs_policy_unregister(), nrs_svc_has_hp(), nrs_svcpt2nrs(), ptlrpc_nrs_pol_ops::op_lprocfs_fini, ptlrpc_nrs_pol_desc::pd_name, ptlrpc_nrs_pol_desc::pd_ops, ptlrpc_all_services, ptlrpc_all_services_mutex, ptlrpc_service_for_each_part, RETURN, ptlrpc_service_part::scp_cpt, ptlrpc_service::srv_is_stopping, and unlikely.
Referenced by ptlrpc_nrs_policy_register(), and ptlrpc_nrs_policy_unregister().
static int nrs_register_policies_locked (struct ptlrpc_nrs * nrs) [static]
Registers all compatible policies in nrs_core.nrs_policies, for NRS head nrs.
Parameters:
[in] nrs the NRS head
Return values:
-ve error
0 success
Precondition:
mutex_is_locked(&nrs_core.nrs_mutex)
See also:
ptlrpc_service_nrs_setup()
Fail registration if any of the policies' registration fails.
Definition at line 904 of file nrs.c.
References CERROR, ENTRY, LASSERT, list_for_each_entry, nrs_policy_compatible(), nrs_policy_register(), ptlrpc_nrs::nrs_svcpt, ptlrpc_nrs_pol_desc::pd_name, RETURN, ptlrpc_service_part::scp_cpt, and ptlrpc_service::srv_name.
Referenced by nrs_svcpt_setup_locked0().
static void nrs_request_enqueue (struct ptlrpc_nrs_request * nrq) [inline, static]
Enqueues request nrq for later handling, via one one the policies for which resources where earlier obtained via nrs_resource_get_safe().
The function attempts to enqueue the request first on the primary policy (if any), since this is the preferred choice.
Parameters:
nrq the request being enqueued
See also:
nrs_resource_get_safe()
Try in descending order, because the primary policy (if any) is the preferred choice.
Should never get here, as at least the primary policy's ptlrpc_nrs_pol_ops::op_req_enqueue() implementation should always succeed.
Definition at line 583 of file nrs.c.
References LBUG, ptlrpc_nrs_request::nr_res_idx, ptlrpc_nrs_request::nr_res_ptrs, ptlrpc_nrs::nrs_req_queued, NRS_RES_MAX, ptlrpc_nrs_pol_ops::op_req_enqueue, ptlrpc_nrs_pol_desc::pd_ops, ptlrpc_nrs_policy::pol_desc, ptlrpc_nrs_policy::pol_nrs, ptlrpc_nrs_policy::pol_req_queued, and ptlrpc_nrs_resource::res_policy.
Referenced by ptlrpc_nrs_req_add_nolock().
static struct ptlrpc_nrs_request* nrs_request_get (struct ptlrpc_nrs_policy * policy, bool peek, bool force) [static, read]
Obtains an NRS request from policy for handling or examination; the request should be removed in the 'handling' case.
Calling into this function implies we already know the policy has a request waiting to be handled.
Parameters:
[in] policy the policy from which a request
[in] peek when set, signifies that we just want to examine the request, and not handle it, so the request is not removed from the policy.
[in] force when set, it will force a policy to return a request if it has one pending
Return values:
the NRS request to be handled
Definition at line 559 of file nrs.c.
References ergo, LASSERT, nrs_request_policy(), ptlrpc_nrs_pol_ops::op_req_get, ptlrpc_nrs_pol_desc::pd_ops, ptlrpc_nrs_policy::pol_desc, and ptlrpc_nrs_policy::pol_req_queued.
Referenced by ptlrpc_nrs_req_get_nolock0().
static void nrs_request_removed (struct ptlrpc_nrs_policy * policy) [static]
If the policy has no more requests queued, remove it from ptlrpc_nrs::nrs_policy_queued.
If there are other policies with queued requests, move the current policy to the end so that we can round robin over all policies and drain the requests.
Definition at line 1537 of file nrs.c.
References LASSERT, list_del_init(), list_move_tail(), ptlrpc_nrs::nrs_policy_queued, ptlrpc_nrs::nrs_req_queued, ptlrpc_nrs_policy::pol_list_queued, ptlrpc_nrs_policy::pol_nrs, ptlrpc_nrs_policy::pol_req_queued, and unlikely.
Referenced by ptlrpc_nrs_req_del_nolock(), and ptlrpc_nrs_req_get_nolock0().
static void nrs_request_stop (struct ptlrpc_nrs_request * nrq) [inline, static]
Called when a request has been handled.
Parameters:
[in] nrs the request that has been handled; can be used for job/resource control.
See also:
ptlrpc_nrs_req_stop_nolock()
Definition at line 623 of file nrs.c.
References LASSERT, ptlrpc_nrs::nrs_req_started, nrs_request_policy(), ptlrpc_nrs_pol_ops::op_req_stop, ptlrpc_nrs_pol_desc::pd_ops, ptlrpc_nrs_policy::pol_desc, ptlrpc_nrs_policy::pol_nrs, and ptlrpc_nrs_policy::pol_req_started.
Referenced by ptlrpc_nrs_req_stop_nolock().
static struct ptlrpc_nrs_resource* nrs_resource_get (struct ptlrpc_nrs_policy * policy, struct ptlrpc_nrs_request * nrq, bool moving_req) [static, read]
Obtains references for each resource in the resource hierarchy for request nrq if it is to be handled by policy.
Parameters:
[in] policy the policy
[in] nrq the request
[in] moving_req denotes whether this is a call to the function by ldlm_lock_reorder_req(), in order to move nrq to the high-priority NRS head; we should not sleep when set.
Return values:
NULL resource hierarchy references not obtained
valid-pointer the bottom level of the resource hierarchy
See also:
ptlrpc_nrs_pol_ops::op_res_get()
Set to NULL to traverse the resource hierarchy from the top.
Return once we have obtained a reference to the bottom level of the resource hierarchy.
Definition at line 406 of file nrs.c.
References LASSERT, nrs_resource_put(), ptlrpc_nrs_pol_ops::op_res_get, ptlrpc_nrs_pol_desc::pd_ops, ptlrpc_nrs_policy::pol_desc, ptlrpc_nrs_resource::res_parent, and ptlrpc_nrs_resource::res_policy.
Referenced by nrs_resource_get_safe().
static void nrs_resource_get_safe (struct ptlrpc_nrs * nrs, struct ptlrpc_nrs_request * nrq, struct ptlrpc_nrs_resource ** resp, bool moving_req) [static]
Obtains resources for the resource hierarchies and policy references for the fallback and current primary policy (if any), that will later be used to handle request nrq.
Parameters:
[in] nrs the NRS head instance that will be handling request nrq.
[in] nrq the request that is being handled.
[out] resp the array where references to the resource hierarchy are stored.
[in] moving_req is set when obtaining resources while moving a request from a policy on the regular NRS head to a policy on the HP NRS head (via ldlm_lock_reorder_req()). It signifies that allocations to get resources should be atomic; for a full explanation, see comment in ptlrpc_nrs_pol_ops::op_res_get().
Obtain policy references.
Obtain resource hierarchy references.
A primary policy may exist which may not wish to serve a particular request for different reasons; release the reference on the policy as it will not be used for this request.
Definition at line 457 of file nrs.c.
References LASSERT, ptlrpc_nrs::nrs_lock, ptlrpc_nrs::nrs_policy_fallback, nrs_policy_get_locked(), ptlrpc_nrs::nrs_policy_primary, nrs_policy_put(), NRS_RES_FALLBACK, NRS_RES_MAX, NRS_RES_PRIMARY, and nrs_resource_get().
Referenced by ptlrpc_nrs_req_hp_move(), and ptlrpc_nrs_req_initialize().
static void nrs_resource_put (struct ptlrpc_nrs_resource * res) [static]
Release references for the resource hierarchy moving upwards towards the policy instance resource.
Definition at line 375 of file nrs.c.
References ptlrpc_nrs_pol_ops::op_res_put, ptlrpc_nrs_pol_desc::pd_ops, ptlrpc_nrs_policy::pol_desc, ptlrpc_nrs_resource::res_parent, and ptlrpc_nrs_resource::res_policy.
Referenced by nrs_resource_get(), and nrs_resource_put_safe().
static void nrs_resource_put_safe (struct ptlrpc_nrs_resource ** resp) [static]
Releases references to resource hierarchies and policies, because they are no longer required; used when request handling has been completed, or the request is moving to the high priority NRS head.
Parameters:
resp the resource hierarchy that is being released
See also:
ptlrpcnrs_req_hp_move()
ptlrpc_nrs_req_finalize()
Definition at line 511 of file nrs.c.
References ptlrpc_nrs::nrs_lock, nrs_policy_put_locked(), NRS_RES_MAX, nrs_resource_put(), ptlrpc_nrs_policy::pol_nrs, and ptlrpc_nrs_resource::res_policy.
Referenced by ptlrpc_nrs_req_finalize(), and ptlrpc_nrs_req_hp_move().
static void nrs_svcpt_cleanup_locked (struct ptlrpc_service_part * svcpt) [static]
Unregisters all policies on all available NRS heads in a service partition; called at PTLRPC service unregistration time.
Parameters:
[in] svcpt the PTLRPC service partition
Precondition:
mutex_is_locked(&nrs_core.nrs_mutex)
If the service partition has an HP NRS head, clean that up as well.
Definition at line 1026 of file nrs.c.
References ENTRY, EXIT, LASSERT, list_for_each_entry_safe, ptlrpc_nrs::nrs_policy_list, nrs_policy_unregister(), ptlrpc_nrs::nrs_stopping, ptlrpc_nrs::nrs_svcpt, nrs_svcpt_has_hp(), OBD_FREE_PTR, ptlrpc_nrs_pol_desc::pd_name, ptlrpc_nrs_policy::pol_desc, ptlrpc_nrs_policy::pol_list, ptlrpc_service_part::scp_nrs_hp, and ptlrpc_service_part::scp_nrs_reg.
Referenced by ptlrpc_service_nrs_cleanup().
static int nrs_svcpt_setup_locked (struct ptlrpc_service_part * svcpt) [static]
Allocates a regular and optionally a high-priority NRS head (if the service handles high-priority RPCs), and then registers all available compatible policies on those NRS heads.
Parameters:
[in,out] svcpt the PTLRPC service partition to setup
Precondition:
mutex_is_locked(&nrs_core.nrs_mutex)
Initialize the regular NRS head.
Optionally allocate a high-priority NRS head.
Definition at line 983 of file nrs.c.
References ENTRY, GOTO, LASSERT, nrs_svcpt2nrs(), nrs_svcpt_setup_locked0(), OBD_CPT_ALLOC_PTR, RETURN, ptlrpc_service_part::scp_cpt, and ptlrpc_service_part::scp_nrs_hp.
Referenced by ptlrpc_service_nrs_setup().
static int nrs_svcpt_setup_locked0 (struct ptlrpc_nrs * nrs, struct ptlrpc_service_part * svcpt) [static]
Initializes NRS head nrs of service partition svcpt, and registers all compatible policies in NRS core, with the NRS head.
Parameters:
[in] nrs the NRS head
[in] svcpt the PTLRPC service partition to setup
Return values:
-ve error
0 success
Precondition:
mutex_is_locked(&nrs_core.nrs_mutex)
Definition at line 947 of file nrs.c.
References INIT_LIST_HEAD, LASSERT, LBUG, ptlrpc_nrs::nrs_lock, ptlrpc_nrs::nrs_policy_list, ptlrpc_nrs::nrs_policy_queued, ptlrpc_nrs::nrs_queue_type, nrs_register_policies_locked(), ptlrpc_nrs::nrs_svcpt, ptlrpc_nrs::nrs_throttling, PTLRPC_NRS_QUEUE_HP, PTLRPC_NRS_QUEUE_REG, RETURN, ptlrpc_service_part::scp_nrs_hp, and ptlrpc_service_part::scp_nrs_reg.
Referenced by nrs_svcpt_setup_locked().
void ptlrpc_nrs_fini (void)
Removes all policy descriptors from nrs_core::nrs_policies, and frees the policy descriptors.
Since all PTLRPC services are stopped at this point, there are no more instances of any policies, because each service will have stopped its policy instances in ptlrpc_service_nrs_cleanup(), so we just need to free the descriptors here.
Definition at line 1836 of file nrs.c.
References list_del_init(), list_for_each_entry_safe, OBD_FREE_PTR, and ptlrpc_nrs_pol_desc::pd_list.
Referenced by ptlrpc_exit(), ptlrpc_init(), and ptlrpc_nrs_init().
static void ptlrpc_nrs_hpreq_add_nolock (struct ptlrpc_request * req) [static]
Enqueue a request on the high priority NRS head.
Parameters:
req the request to enqueue.
Definition at line 861 of file nrs.c.
References D_NET, DEBUG_REQ, ENTRY, EXIT, lustre_msg_get_opc(), OBD_PING, ptlrpc_nrs_req_add_nolock(), ptlrpc_request::rq_hp, ptlrpc_request::rq_lock, and ptlrpc_request::rq_reqmsg.
Referenced by ptlrpc_nrs_req_add(), and ptlrpc_nrs_req_hp_move().
int ptlrpc_nrs_init (void)
Adds all policies that ship with the ptlrpc module, to NRS core's list of policies nrs_core.nrs_policies.
Return values:
0 all policies have been registered successfully
-ve error
Since no PTLRPC services have been started at this point, all we need to do for cleanup is to free the descriptors.
Definition at line 1787 of file nrs.c.
References ENTRY, GOTO, INIT_LIST_HEAD, nrs_conf_fifo, ptlrpc_nrs_fini(), ptlrpc_nrs_policy_register(), and RETURN.
Referenced by ptlrpc_init().
int ptlrpc_nrs_policy_control (const struct ptlrpc_service * svc, enum ptlrpc_nrs_queue_type queue, char * name, enum ptlrpc_nrs_ctl opc, bool single, void * arg)
Carries out a control operation opc on the policy identified by the human-readable name, on either all partitions, or only on the first partition of service svc.
Parameters:
[in] svc the service the policy belongs to.
[in] queue whether to carry out the command on the policy which belongs to the regular, high-priority, or both NRS heads of service partitions of svc.
[in] name the policy to act upon, by human-readable name
[in] opc the opcode of the operation to carry out
[in] single when set, the operation will only be carried out on the NRS heads of the first service partition of svc. This is useful for some policies which e.g. share identical values on the same parameters of different service partitions; when reading these parameters via lprocfs, these policies may just want to obtain and print out the values from the first service partition. Storing these values centrally elsewhere then could be another solution for this.
[in,out] arg can be used as a generic in/out buffer between control operations and the user environment.
Return values:
-ve error condition
0 operation was carried out successfully
XXX: We could optionally check for nrs_svc_has_hp(svc) here, and return an error if it is false. Right now we rely on the policies' lprocfs handlers that call the present function to make this check; if they fail to do so, they might hit the assertion inside nrs_svcpt2nrs() below.
Definition at line 1738 of file nrs.c.
References ENTRY, GOTO, LASSERT, nrs_policy_ctl(), nrs_svcpt2nrs(), PTLRPC_NRS_CTL_INVALID, PTLRPC_NRS_QUEUE_BOTH, PTLRPC_NRS_QUEUE_HP, PTLRPC_NRS_QUEUE_REG, ptlrpc_service_for_each_part, and RETURN.
void ptlrpc_nrs_req_add (struct ptlrpc_service_part * svcpt, struct ptlrpc_request * req, bool hp)
Enqueues request req on either the regular or high-priority NRS head of service partition svcpt.
Parameters:
[in] svcpt the service partition
[in] req the request to be enqueued
[in] hp whether to enqueue the request on the regular or high-priority NRS head.
Definition at line 1524 of file nrs.c.
References ptlrpc_nrs_hpreq_add_nolock(), and ptlrpc_nrs_req_add_nolock().
Referenced by ptlrpc_server_request_add().
static void ptlrpc_nrs_req_add_nolock (struct ptlrpc_request * req) [static]
Enqueue request req using one of the policies its resources are referring to.
Parameters:
[in] req the request to enqueue.
Add the policy to the NRS head's list of policies with enqueued requests, if it has not been added there.
Definition at line 836 of file nrs.c.
References LASSERT, list_add_tail(), list_empty(), ptlrpc_nrs::nrs_policy_queued, nrs_request_enqueue(), nrs_request_policy(), ptlrpc_nrs_policy::pol_list_queued, ptlrpc_nrs_policy::pol_nrs, and unlikely.
Referenced by ptlrpc_nrs_hpreq_add_nolock(), and ptlrpc_nrs_req_add().
void ptlrpc_nrs_req_del_nolock (struct ptlrpc_request * req)
Dequeues request req from the policy it has been enqueued on.
Parameters:
[in] req the request
Definition at line 1619 of file nrs.c.
References nrs_request_policy(), nrs_request_removed(), ptlrpc_nrs_pol_ops::op_req_dequeue, ptlrpc_nrs_pol_desc::pd_ops, and ptlrpc_nrs_policy::pol_desc.
Referenced by ptlrpc_nrs_req_hp_move().
void ptlrpc_nrs_req_finalize (struct ptlrpc_request * req)
Releases resources for a request; is called after the request has been handled.
Parameters:
[in] req the request
See also:
ptlrpc_server_finish_request()
Definition at line 1499 of file nrs.c.
References nrs_resource_put_safe().
Referenced by ptlrpc_server_finish_active_request(), and ptlrpc_server_request_add().
struct ptlrpc_request* ptlrpc_nrs_req_get_nolock0 (struct ptlrpc_service_part * svcpt, bool hp, bool peek, bool force) [read]
Obtains a request for handling from an NRS head of service partition svcpt.
Parameters:
[in] svcpt the service partition
[in] hp whether to obtain a request from the regular or high-priority NRS head.
[in] peek when set, signifies that we just want to examine the request, and not handle it, so the request is not removed from the policy.
[in] force when set, it will force a policy to return a request if it has one pending
Return values:
the request to be handled
NULL the head has no requests to serve
Always try to drain requests from all NRS polices even if they are inactive, because the user can change policy status at runtime.
Definition at line 1583 of file nrs.c.
References likely, list_for_each_entry, ptlrpc_nrs_request::nr_started, ptlrpc_nrs::nrs_policy_queued, ptlrpc_nrs::nrs_req_started, nrs_request_get(), nrs_request_removed(), nrs_svcpt2nrs(), ptlrpc_nrs_policy::pol_nrs, ptlrpc_nrs_policy::pol_req_started, and rq_nrq.
Referenced by ptlrpc_nrs_req_get_nolock(), and ptlrpc_nrs_req_peek_nolock().
void ptlrpc_nrs_req_initialize (struct ptlrpc_service_part * svcpt, struct ptlrpc_request * req, bool hp)
Obtains NRS head resources for request req.
These could be either on the regular or HP NRS head of svcpt; resources taken on the regular head can later be swapped for HP head resources by ldlm_lock_reorder_req().
Parameters:
[in] svcpt the service partition
[in] req the request
[in] hp which NRS head of svcpt to use
It is fine to access nr_initialized without locking as there is no contention at this early stage.
Definition at line 1475 of file nrs.c.
References nrs_resource_get_safe(), and nrs_svcpt2nrs().
Referenced by ptlrpc_server_request_add().
bool ptlrpc_nrs_req_pending_nolock (struct ptlrpc_service_part * svcpt, bool hp)
Returns whether there are any requests currently enqueued on any of the policies of service partition's svcpt NRS head specified by hp.
Should be called while holding ptlrpc_service_part::scp_req_lock to get a reliable result.
Parameters:
[in] svcpt the service partition to enquire.
[in] hp whether the regular or high-priority NRS head is to be enquired.
Return values:
false the indicated NRS head has no enqueued requests.
true the indicated NRS head has some enqueued requests.
Definition at line 1643 of file nrs.c.
References ptlrpc_nrs::nrs_req_queued, and nrs_svcpt2nrs().
Referenced by ptlrpc_server_allow_high(), ptlrpc_server_high_pending(), and ptlrpc_server_normal_pending().
void ptlrpc_nrs_req_stop_nolock (struct ptlrpc_request * req)
Definition at line 1509 of file nrs.c.
References nrs_request_stop().
Referenced by ptlrpc_server_finish_active_request().
bool ptlrpc_nrs_req_throttling_nolock (struct ptlrpc_service_part * svcpt, bool hp)
Returns whether NRS policy is throttling reqeust.
Parameters:
[in] svcpt the service partition to enquire.
[in] hp whether the regular or high-priority NRS head is to be enquired.
Return values:
false the indicated NRS head has no enqueued requests.
true the indicated NRS head has some enqueued requests.
Definition at line 1660 of file nrs.c.
References nrs_svcpt2nrs(), and ptlrpc_nrs::nrs_throttling.
Referenced by ptlrpc_server_allow_high(), and ptlrpc_server_allow_normal().
void ptlrpc_service_nrs_cleanup (struct ptlrpc_service * svc)
Unregisters all policies on all service partitions of service svc.
Parameters:
[in] svc the PTLRPC service to unregister
Clean up NRS heads on all service partitions
Clean up lprocfs interfaces for all supported policies for the service.
Definition at line 1435 of file nrs.c.
References list_for_each_entry, nrs_policy_compatible(), nrs_svcpt_cleanup_locked(), ptlrpc_nrs_pol_ops::op_lprocfs_fini, ptlrpc_nrs_pol_desc::pd_list, ptlrpc_nrs_pol_desc::pd_ops, and ptlrpc_service_for_each_part.
Referenced by ptlrpc_unregister_service().
int ptlrpc_service_nrs_setup (struct ptlrpc_service * svc)
Setup NRS heads on all service partitions of service svc, and register all compatible policies on those NRS heads.
To be called from withing ptl
Parameters:
[in] svc the service to setup
Return values:
-ve error, the calling logic should eventually call ptlrpc_service_nrs_cleanup() to undo any work performed by this function.
See also:
ptlrpc_register_service()
ptlrpc_service_nrs_cleanup()
Initialize NRS heads on all service CPTs.
Set up lprocfs interfaces for all supported policies for the service.
Definition at line 1390 of file nrs.c.
References GOTO, list_for_each_entry, nrs_policy_compatible(), nrs_svcpt_setup_locked(), ptlrpc_nrs_pol_ops::op_lprocfs_init, ptlrpc_nrs_pol_desc::pd_list, ptlrpc_nrs_pol_desc::pd_ops, ptlrpc_service_for_each_part, and RETURN.
Referenced by ptlrpc_register_service().
Variable Documentation
struct nrs_core nrs_core
NRS core object.
nrs
Definition at line 53 of file nrs.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.