Lustre: lnet/klnds/o2iblnd/o2iblnd.h File Reference
lnet/klnds/o2iblnd/o2iblnd.h File Reference
#include <linux/version.h>
#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/kthread.h>
#include <linux/mm.h>
#include <linux/string.h>
#include <linux/stat.h>
#include <linux/errno.h>
#include <linux/unistd.h>
#include <linux/uio.h>
#include <asm/uaccess.h>
#include <asm/io.h>
#include <linux/init.h>
#include <linux/fs.h>
#include <linux/file.h>
#include <linux/list.h>
#include <linux/kmod.h>
#include <linux/sysctl.h>
#include <linux/pci.h>
#include <net/sock.h>
#include <linux/in.h>
#include <rdma/rdma_cm.h>
#include <rdma/ib_cm.h>
#include <rdma/ib_verbs.h>
#include <rdma/ib_fmr_pool.h>
#include <libcfs/libcfs.h>
#include <lnet/lnet.h>
#include <lnet/lib-lnet.h>
Data Structures
struct kib_tunables_t
struct kib_dev_t
struct kib_hca_dev
struct kib_pages_t
struct kib_poolset
struct kib_pool
struct kib_tx_poolset_t
struct kib_tx_pool_t
struct kib_fmr_poolset_t
struct ib_rdma_wr
struct kib_fast_reg_descriptor
struct kib_fmr_pool_t
struct kib_fmr_t
struct kib_net
struct kib_sched_info
struct kib_data_t
struct kib_connparams
struct WIRE_ATTR
struct WIRE_ATTR
struct WIRE_ATTR
struct WIRE_ATTR
struct WIRE_ATTR
struct WIRE_ATTR
struct WIRE_ATTR
struct WIRE_ATTR
struct WIRE_ATTR
struct kib_rx
struct kib_tx
struct kib_connvars
struct kib_conn
struct kib_peer
Defines
#define DEBUG_SUBSYSTEM S_LND
#define IBLND_PEER_HASH_SIZE 101
#define IBLND_RESCHED 100
#define IBLND_N_SCHED 2
#define IBLND_N_SCHED_HIGH 4
#define IBLND_MSG_QUEUE_SIZE_V1 8
#define IBLND_CREDIT_HIGHWATER_V1 7
#define IBLND_CREDITS_DEFAULT 8
#define IBLND_CREDITS_MAX ((typeof(((kib_msg_t*) 0)->ibm_credits)) - 1)
#define IBLND_CREDITS_HIGHWATER(t, v)
#define kiblnd_rdma_create_id(cb, dev, ps, qpt) rdma_create_id(cb, dev, ps)
#define IBLND_OOB_CAPABLE(v) ((v) != IBLND_MSG_VERSION_1)
#define IBLND_OOB_MSGS(v) (IBLND_OOB_CAPABLE(v) ? 2 : 0)
#define IBLND_MSG_SIZE (4<<10)
#define IBLND_MAX_RDMA_FRAGS LNET_MAX_IOV
#define IBLND_TX_POOL 256
#define IBLND_FMR_POOL 256
#define IBLND_FMR_POOL_FLUSH 192
#define IBLND_RX_MSGS(c) ((c->ibc_queue_depth) * 2 + IBLND_OOB_MSGS(c->ibc_version))
#define IBLND_RX_MSG_BYTES(c) (IBLND_RX_MSGS(c) * IBLND_MSG_SIZE)
#define IBLND_RX_MSG_PAGES(c) ((IBLND_RX_MSG_BYTES(c) + PAGE_SIZE - 1) / PAGE_SIZE)
#define IBLND_RECV_WRS(c) IBLND_RX_MSGS(c)
#define IBLND_SEND_WRS(c)
#define IBLND_CQ_ENTRIES(c) (IBLND_RECV_WRS(c) + IBLND_SEND_WRS(c))
#define KIB_IFNAME_SIZE 256
#define IBLND_POOL_DEADLINE 300
# of seconds to keep pool alive
#define IBLND_POOL_RETRY 1
# of seconds to retry if allocation failed
#define IBLND_POOL_NAME_LEN 32
#define KIB_THREAD_SHIFT 16
#define KIB_THREAD_ID(cpt, tid) ((cpt) << KIB_THREAD_SHIFT | (tid))
#define KIB_THREAD_CPT(id) ((id) >> KIB_THREAD_SHIFT)
#define KIB_THREAD_TID(id) ((id) & ((1UL << KIB_THREAD_SHIFT) - 1))
#define IBLND_INIT_NOTHING 0
#define IBLND_INIT_DATA 1
#define IBLND_INIT_ALL 2
#define IBLND_MSG_MAGIC LNET_PROTO_IB_MAGIC
#define IBLND_MSG_VERSION_1 0x11
#define IBLND_MSG_VERSION_2 0x12
#define IBLND_MSG_VERSION IBLND_MSG_VERSION_2
#define IBLND_MSG_CONNREQ 0xc0
#define IBLND_MSG_CONNACK 0xc1
#define IBLND_MSG_NOOP 0xd0
#define IBLND_MSG_IMMEDIATE 0xd1
#define IBLND_MSG_PUT_REQ 0xd2
#define IBLND_MSG_PUT_NAK 0xd3
#define IBLND_MSG_PUT_ACK 0xd4
#define IBLND_MSG_PUT_DONE 0xd5
#define IBLND_MSG_GET_REQ 0xd6
#define IBLND_MSG_GET_DONE 0xd7
#define IBLND_REJECT_CONN_RACE 1
#define IBLND_REJECT_NO_RESOURCES 2
#define IBLND_REJECT_FATAL 3
#define IBLND_REJECT_CONN_UNCOMPAT 4
#define IBLND_REJECT_CONN_STALE 5
#define IBLND_REJECT_RDMA_FRAGS 6
#define IBLND_REJECT_MSG_QUEUE_SIZE 7
#define IBLND_POSTRX_DONT_POST 0
#define IBLND_POSTRX_NO_CREDIT 1
#define IBLND_POSTRX_PEER_CREDIT 2
#define IBLND_POSTRX_RSRVD_CREDIT 3
#define IBLND_CONN_INIT 0
#define IBLND_CONN_ACTIVE_CONNECT 1
#define IBLND_CONN_PASSIVE_WAIT 2
#define IBLND_CONN_ESTABLISHED 3
#define IBLND_CONN_CLOSING 4
#define IBLND_CONN_DISCONNECTED 5
#define kiblnd_conn_addref(conn)
#define kiblnd_conn_decref(conn)
#define kiblnd_peer_addref(peer)
#define kiblnd_peer_decref(peer)
#define IBLND_WID_INVAL 0
#define IBLND_WID_TX 1
#define IBLND_WID_RX 2
#define IBLND_WID_RDMA 3
#define IBLND_WID_MR 4
#define IBLND_WID_MASK 7UL
#define KIBLND_UNMAP_ADDR_SET(p, m, a) do {} while (0)
#define KIBLND_UNMAP_ADDR(p, m, a) (a)
#define KIBLND_CONN_PARAM(e) ((e)->param.conn.private_data)
#define KIBLND_CONN_PARAM_LEN(e) ((e)->param.conn.private_data_len)
Typedefs
typedef struct kib_hca_dev kib_hca_dev_t
typedef int(* kib_ps_pool_create_t)(struct kib_poolset *ps, int inc, struct kib_pool **pp_po)
typedef void(* kib_ps_pool_destroy_t)(struct kib_pool *po)
typedef void(* kib_ps_node_init_t)(struct kib_pool *po, struct list_head *node)
typedef void(* kib_ps_node_fini_t)(struct kib_pool *po, struct list_head *node)
typedef struct kib_poolset kib_poolset_t
typedef struct kib_pool kib_pool_t
typedef struct kib_net kib_net_t
typedef struct kib_connparams kib_connparams_t
typedef struct kib_rx kib_rx_t
typedef struct kib_tx kib_tx_t
typedef struct kib_connvars kib_connvars_t
typedef struct kib_conn kib_conn_t
typedef struct kib_peer kib_peer_t
Functions
static u32 ib_inc_rkey (u32 rkey)
ib_inc_rkey - increments the key portion of the given rkey.
void kiblnd_hdev_destroy (kib_hca_dev_t *hdev)
int kiblnd_msg_queue_size (int version, struct lnet_ni *ni)
static int kiblnd_cfg_rdma_frags (struct lnet_ni *ni)
static int kiblnd_rdma_frags (int version, struct lnet_ni *ni)
static int kiblnd_concurrent_sends (int version, struct lnet_ni *ni)
static void kiblnd_hdev_addref_locked (kib_hca_dev_t *hdev)
static void kiblnd_hdev_decref (kib_hca_dev_t *hdev)
static int kiblnd_dev_can_failover (kib_dev_t *dev)
static bool kiblnd_peer_connecting (kib_peer_t *peer)
static bool kiblnd_peer_idle (kib_peer_t *peer)
static struct list_head * kiblnd_nid2peerlist (lnet_nid_t nid)
static int kiblnd_peer_active (kib_peer_t *peer)
static kib_conn_t * kiblnd_get_conn_locked (kib_peer_t *peer)
static int kiblnd_send_keepalive (kib_conn_t *conn)
static int kiblnd_need_noop (kib_conn_t *conn)
static void kiblnd_abort_receives (kib_conn_t *conn)
static const char * kiblnd_queue2str (kib_conn_t *conn, struct list_head *q)
static __u64 kiblnd_ptr2wreqid (void *ptr, int type)
static void * kiblnd_wreqid2ptr (__u64 wreqid)
static int kiblnd_wreqid2type (__u64 wreqid)
static void kiblnd_set_conn_state (kib_conn_t *conn, int state)
static void kiblnd_init_msg (kib_msg_t *msg, int type, int body_nob)
static int kiblnd_rd_size (kib_rdma_desc_t *rd)
static __u64 kiblnd_rd_frag_addr (kib_rdma_desc_t *rd, int index)
static __u32 kiblnd_rd_frag_size (kib_rdma_desc_t *rd, int index)
static __u32 kiblnd_rd_frag_key (kib_rdma_desc_t *rd, int index)
static int kiblnd_rd_consume_frag (kib_rdma_desc_t *rd, int index, __u32 nob)
static int kiblnd_rd_msg_size (kib_rdma_desc_t *rd, int msgtype, int n)
static __u64 kiblnd_dma_mapping_error (struct ib_device *dev, u64 dma_addr)
static __u64 kiblnd_dma_map_single (struct ib_device *dev, void *msg, size_t size, enum dma_data_direction direction)
static void kiblnd_dma_unmap_single (struct ib_device *dev, __u64 addr, size_t size, enum dma_data_direction direction)
static int kiblnd_dma_map_sg (struct ib_device *dev, struct scatterlist *sg, int nents, enum dma_data_direction direction)
static void kiblnd_dma_unmap_sg (struct ib_device *dev, struct scatterlist *sg, int nents, enum dma_data_direction direction)
static __u64 kiblnd_sg_dma_address (struct ib_device *dev, struct scatterlist *sg)
static unsigned int kiblnd_sg_dma_len (struct ib_device *dev, struct scatterlist *sg)
struct ib_mr * kiblnd_find_rd_dma_mr (struct lnet_ni *ni, kib_rdma_desc_t *rd, int negotiated_nfrags)
void kiblnd_map_rx_descs (kib_conn_t *conn)
void kiblnd_unmap_rx_descs (kib_conn_t *conn)
void kiblnd_pool_free_node (kib_pool_t *pool, struct list_head *node)
struct list_head * kiblnd_pool_alloc_node (kib_poolset_t *ps)
int kiblnd_fmr_pool_map (kib_fmr_poolset_t *fps, kib_tx_t *tx, kib_rdma_desc_t *rd, __u32 nob, __u64 iov, kib_fmr_t *fmr)
void kiblnd_fmr_pool_unmap (kib_fmr_t *fmr, int status)
int kiblnd_tunables_setup (struct lnet_ni *ni)
int kiblnd_tunables_init (void)
int kiblnd_connd (void *arg)
int kiblnd_scheduler (void *arg)
int kiblnd_thread_start (int(*fn)(void *arg), void *arg, char *name)
int kiblnd_failover_thread (void *arg)
int kiblnd_alloc_pages (kib_pages_t **pp, int cpt, int npages)
int kiblnd_cm_callback (struct rdma_cm_id *cmid, struct rdma_cm_event *event)
int kiblnd_translate_mtu (int value)
int kiblnd_dev_failover (kib_dev_t *dev)
int kiblnd_create_peer (lnet_ni_t *ni, kib_peer_t **peerp, lnet_nid_t nid)
void kiblnd_destroy_peer (kib_peer_t *peer)
bool kiblnd_reconnect_peer (kib_peer_t *peer)
void kiblnd_destroy_dev (kib_dev_t *dev)
void kiblnd_unlink_peer_locked (kib_peer_t *peer)
kib_peer_t * kiblnd_find_peer_locked (lnet_nid_t nid)
int kiblnd_close_stale_conns_locked (kib_peer_t *peer, int version, __u64 incarnation)
int kiblnd_close_peer_conns_locked (kib_peer_t *peer, int why)
kib_conn_t * kiblnd_create_conn (kib_peer_t *peer, struct rdma_cm_id *cmid, int state, int version)
void kiblnd_destroy_conn (kib_conn_t *conn, bool free_conn)
void kiblnd_close_conn (kib_conn_t *conn, int error)
void kiblnd_close_conn_locked (kib_conn_t *conn, int error)
void kiblnd_launch_tx (lnet_ni_t *ni, kib_tx_t *tx, lnet_nid_t nid)
void kiblnd_txlist_done (lnet_ni_t *ni, struct list_head *txlist, int status)
void kiblnd_qp_event (struct ib_event *event, void *arg)
void kiblnd_cq_event (struct ib_event *event, void *arg)
void kiblnd_cq_completion (struct ib_cq *cq, void *arg)
void kiblnd_pack_msg (lnet_ni_t *ni, kib_msg_t *msg, int version, int credits, lnet_nid_t dstnid, __u64 dststamp)
int kiblnd_unpack_msg (kib_msg_t *msg, int nob)
int kiblnd_post_rx (kib_rx_t *rx, int credit)
int kiblnd_send (lnet_ni_t *ni, void *private, lnet_msg_t *lntmsg)
int kiblnd_recv (lnet_ni_t *ni, void *private, lnet_msg_t *lntmsg, int delayed, unsigned int niov, struct kvec *iov, lnet_kiov_t *kiov, unsigned int offset, unsigned int mlen, unsigned int rlen)
Variables
kib_tunables_t kiblnd_tunables
kib_data_t kiblnd_data
Define Documentation
#define DEBUG_SUBSYSTEM S_LND
Definition at line 79 of file o2iblnd.h.
#define IBLND_CONN_ACTIVE_CONNECT 1
Definition at line 719 of file o2iblnd.h.
Referenced by kiblnd_active_connect(), kiblnd_check_reconnect(), kiblnd_cm_callback(), kiblnd_connreq_done(), kiblnd_create_conn(), and kiblnd_rejected().
#define IBLND_CONN_CLOSING 4
Definition at line 722 of file o2iblnd.h.
Referenced by kiblnd_close_conn_locked(), and kiblnd_disconnect_conn().
#define IBLND_CONN_DISCONNECTED 5
Definition at line 723 of file o2iblnd.h.
Referenced by kiblnd_destroy_conn(), and kiblnd_finalise_conn().
#define IBLND_CONN_ESTABLISHED 3
Definition at line 721 of file o2iblnd.h.
Referenced by kiblnd_check_conns(), kiblnd_check_sends(), kiblnd_close_conn_locked(), kiblnd_cm_callback(), kiblnd_connreq_done(), kiblnd_handle_early_rxs(), kiblnd_handle_rx(), kiblnd_need_noop(), kiblnd_post_rx(), kiblnd_post_tx_locked(), kiblnd_queue_tx_locked(), kiblnd_rx_complete(), and kiblnd_tx_complete().
#define IBLND_CONN_INIT 0
Definition at line 718 of file o2iblnd.h.
Referenced by kiblnd_create_conn(), kiblnd_destroy_conn(), kiblnd_finalise_conn(), and kiblnd_post_rx().
#define IBLND_CONN_PASSIVE_WAIT 2
Definition at line 720 of file o2iblnd.h.
Referenced by kiblnd_cm_callback(), kiblnd_connreq_done(), kiblnd_create_conn(), and kiblnd_passive_connect().
#define IBLND_CQ_ENTRIES (c) (IBLND_RECV_WRS(c) + IBLND_SEND_WRS(c))
Definition at line 165 of file o2iblnd.h.
Referenced by kiblnd_create_conn().
#define IBLND_CREDIT_HIGHWATER_V1 7
Definition at line 115 of file o2iblnd.h.
#define IBLND_CREDITS_DEFAULT 8
Definition at line 117 of file o2iblnd.h.
Referenced by kiblnd_tunables_setup().
#define IBLND_CREDITS_HIGHWATER (t, v)
Value:
((v) == IBLND_MSG_VERSION_1 ? \
                                        IBLND_CREDIT_HIGHWATER_V1 : \
                                        t->lnd_peercredits_hiw)
Definition at line 121 of file o2iblnd.h.
Referenced by kiblnd_need_noop().
#define IBLND_CREDITS_MAX ((typeof(((kib_msg_t*) 0)->ibm_credits)) - 1)
Definition at line 118 of file o2iblnd.h.
Referenced by kiblnd_tunables_setup().
#define IBLND_FMR_POOL 256
Definition at line 150 of file o2iblnd.h.
Referenced by kiblnd_fmr_pool_size().
#define IBLND_FMR_POOL_FLUSH 192
Definition at line 151 of file o2iblnd.h.
Referenced by kiblnd_fmr_flush_trigger().
#define IBLND_INIT_ALL 2
Definition at line 436 of file o2iblnd.h.
Referenced by kiblnd_base_shutdown(), kiblnd_base_startup(), kiblnd_shutdown(), and kiblnd_startup().
#define IBLND_INIT_DATA 1
Definition at line 435 of file o2iblnd.h.
Referenced by kiblnd_base_shutdown(), and kiblnd_base_startup().
#define IBLND_INIT_NOTHING 0
Definition at line 434 of file o2iblnd.h.
Referenced by kiblnd_base_shutdown(), kiblnd_base_startup(), kiblnd_shutdown(), and kiblnd_startup().
#define IBLND_MAX_RDMA_FRAGS LNET_MAX_IOV
Definition at line 143 of file o2iblnd.h.
Referenced by kiblnd_cfg_rdma_frags(), kiblnd_create_tx_pool(), kiblnd_destroy_tx_pool(), kiblnd_init_tx_msg(), kiblnd_rdma_frags(), kiblnd_tunables_setup(), kiblnd_unpack_rd(), and ko2iblnd_init().
#define IBLND_MSG_CONNACK 0xc1
Definition at line 527 of file o2iblnd.h.
#define IBLND_MSG_CONNREQ 0xc0
Definition at line 526 of file o2iblnd.h.
#define IBLND_MSG_GET_DONE 0xd7
Definition at line 535 of file o2iblnd.h.
#define IBLND_MSG_GET_REQ 0xd6
Definition at line 534 of file o2iblnd.h.
#define IBLND_MSG_IMMEDIATE 0xd1
Definition at line 529 of file o2iblnd.h.
#define IBLND_MSG_MAGIC LNET_PROTO_IB_MAGIC
Definition at line 520 of file o2iblnd.h.
Referenced by kiblnd_pack_msg(), kiblnd_passive_connect(), kiblnd_rejected(), and kiblnd_unpack_msg().
#define IBLND_MSG_NOOP 0xd0
Definition at line 528 of file o2iblnd.h.
#define IBLND_MSG_PUT_ACK 0xd4
Definition at line 532 of file o2iblnd.h.
#define IBLND_MSG_PUT_DONE 0xd5
Definition at line 533 of file o2iblnd.h.
#define IBLND_MSG_PUT_NAK 0xd3
Definition at line 531 of file o2iblnd.h.
#define IBLND_MSG_PUT_REQ 0xd2
Definition at line 530 of file o2iblnd.h.
#define IBLND_MSG_QUEUE_SIZE_V1 8
Definition at line 114 of file o2iblnd.h.
Referenced by kiblnd_concurrent_sends(), and kiblnd_msg_queue_size().
#define IBLND_MSG_SIZE (4<<10)
Definition at line 142 of file o2iblnd.h.
Referenced by kiblnd_active_connect(), kiblnd_check_connreply(), kiblnd_check_reconnect(), kiblnd_create_tx_pool(), kiblnd_init_tx_msg(), kiblnd_map_rx_descs(), kiblnd_map_tx_pool(), kiblnd_passive_connect(), kiblnd_post_rx(), kiblnd_recv(), kiblnd_send(), kiblnd_unmap_rx_descs(), kiblnd_unmap_tx_pool(), and ko2iblnd_init().
#define IBLND_MSG_VERSION IBLND_MSG_VERSION_2
Definition at line 524 of file o2iblnd.h.
Referenced by kiblnd_active_connect(), kiblnd_check_reconnect(), kiblnd_passive_connect(), kiblnd_rejected(), and kiblnd_unpack_msg().
#define IBLND_MSG_VERSION_1 0x11
Definition at line 522 of file o2iblnd.h.
Referenced by kiblnd_concurrent_sends(), kiblnd_msg_queue_size(), kiblnd_passive_connect(), kiblnd_rdma_frags(), kiblnd_rejected(), and kiblnd_unpack_msg().
#define IBLND_MSG_VERSION_2 0x12
Definition at line 523 of file o2iblnd.h.
#define IBLND_N_SCHED 2
Definition at line 89 of file o2iblnd.h.
Referenced by kiblnd_base_startup(), and kiblnd_start_schedulers().
#define IBLND_N_SCHED_HIGH 4
Definition at line 90 of file o2iblnd.h.
Referenced by kiblnd_start_schedulers().
#define IBLND_OOB_CAPABLE (v) ((v) != IBLND_MSG_VERSION_1)
Definition at line 139 of file o2iblnd.h.
Referenced by kiblnd_check_sends(), kiblnd_handle_rx(), kiblnd_need_noop(), kiblnd_post_tx_locked(), and kiblnd_queue_tx_locked().
#define IBLND_OOB_MSGS (v) (IBLND_OOB_CAPABLE(v) ? 2 : 0)
Definition at line 140 of file o2iblnd.h.
Referenced by kiblnd_check_connreply(), kiblnd_check_sends(), kiblnd_passive_connect(), and kiblnd_post_tx_locked().
#define IBLND_PEER_HASH_SIZE 101
Definition at line 85 of file o2iblnd.h.
Referenced by kiblnd_base_startup().
#define IBLND_POOL_DEADLINE 300
# of seconds to keep pool alive
Definition at line 212 of file o2iblnd.h.
Referenced by kiblnd_create_fmr_pool(), kiblnd_fmr_pool_map(), kiblnd_init_pool(), and kiblnd_pool_alloc_node().
#define IBLND_POOL_NAME_LEN 32
Definition at line 233 of file o2iblnd.h.
#define IBLND_POOL_RETRY 1
# of seconds to retry if allocation failed
Definition at line 214 of file o2iblnd.h.
Referenced by kiblnd_fmr_pool_map(), and kiblnd_pool_alloc_node().
#define IBLND_POSTRX_DONT_POST 0
Definition at line 583 of file o2iblnd.h.
Referenced by kiblnd_handle_rx().
#define IBLND_POSTRX_NO_CREDIT 1
Definition at line 584 of file o2iblnd.h.
Referenced by kiblnd_create_conn(), kiblnd_handle_rx(), kiblnd_post_rx(), and kiblnd_recv().
#define IBLND_POSTRX_PEER_CREDIT 2
Definition at line 585 of file o2iblnd.h.
Referenced by kiblnd_handle_rx(), kiblnd_post_rx(), and kiblnd_recv().
#define IBLND_POSTRX_RSRVD_CREDIT 3
Definition at line 586 of file o2iblnd.h.
Referenced by kiblnd_handle_rx(), and kiblnd_post_rx().
#define IBLND_RECV_WRS (c) IBLND_RX_MSGS(c)
Definition at line 161 of file o2iblnd.h.
Referenced by kiblnd_create_conn().
#define IBLND_REJECT_CONN_RACE 1
Definition at line 547 of file o2iblnd.h.
Referenced by kiblnd_check_reconnect(), kiblnd_passive_connect(), and kiblnd_rejected().
#define IBLND_REJECT_CONN_STALE 5
Definition at line 552 of file o2iblnd.h.
Referenced by kiblnd_check_reconnect(), kiblnd_passive_connect(), and kiblnd_rejected().
#define IBLND_REJECT_CONN_UNCOMPAT 4
Definition at line 551 of file o2iblnd.h.
Referenced by kiblnd_check_reconnect(), and kiblnd_rejected().
#define IBLND_REJECT_FATAL 3
Definition at line 549 of file o2iblnd.h.
Referenced by kiblnd_passive_connect(), and kiblnd_rejected().
#define IBLND_REJECT_MSG_QUEUE_SIZE 7
Definition at line 557 of file o2iblnd.h.
Referenced by kiblnd_check_reconnect(), kiblnd_passive_connect(), and kiblnd_rejected().
#define IBLND_REJECT_NO_RESOURCES 2
Definition at line 548 of file o2iblnd.h.
Referenced by kiblnd_passive_connect(), and kiblnd_rejected().
#define IBLND_REJECT_RDMA_FRAGS 6
Definition at line 555 of file o2iblnd.h.
Referenced by kiblnd_check_reconnect(), kiblnd_passive_connect(), and kiblnd_rejected().
#define IBLND_RESCHED 100
Definition at line 87 of file o2iblnd.h.
Referenced by kiblnd_scheduler().
#define IBLND_RX_MSG_BYTES (c) (IBLND_RX_MSGS(c) * IBLND_MSG_SIZE)
Definition at line 156 of file o2iblnd.h.
#define IBLND_RX_MSG_PAGES (c) ((IBLND_RX_MSG_BYTES(c) + PAGE_SIZE - 1) / PAGE_SIZE)
Definition at line 157 of file o2iblnd.h.
Referenced by kiblnd_create_conn(), and kiblnd_map_rx_descs().
#define IBLND_RX_MSGS (c) ((c->ibc_queue_depth) * 2 + IBLND_OOB_MSGS(c->ibc_version))
Definition at line 154 of file o2iblnd.h.
Referenced by kiblnd_check_connreply(), kiblnd_create_conn(), kiblnd_debug_conn(), kiblnd_destroy_conn(), kiblnd_map_rx_descs(), kiblnd_passive_connect(), and kiblnd_unmap_rx_descs().
#define IBLND_SEND_WRS (c)
Value:
((c->ibc_max_frags + 1) * kiblnd_concurrent_sends(c->ibc_version, \
                                                          c->ibc_peer->ibp_ni))
Definition at line 162 of file o2iblnd.h.
Referenced by kiblnd_create_conn().
#define IBLND_TX_POOL 256
Definition at line 149 of file o2iblnd.h.
Referenced by kiblnd_tx_pool_size().
#define IBLND_WID_INVAL 0
Definition at line 1004 of file o2iblnd.h.
Referenced by kiblnd_scheduler().
#define IBLND_WID_MASK 7UL
Definition at line 1009 of file o2iblnd.h.
Referenced by kiblnd_ptr2wreqid(), kiblnd_wreqid2ptr(), and kiblnd_wreqid2type().
#define IBLND_WID_MR 4
Definition at line 1008 of file o2iblnd.h.
Referenced by kiblnd_complete(), and kiblnd_fmr_pool_map().
#define IBLND_WID_RDMA 3
Definition at line 1007 of file o2iblnd.h.
Referenced by kiblnd_complete(), and kiblnd_init_rdma().
#define IBLND_WID_RX 2
Definition at line 1006 of file o2iblnd.h.
Referenced by kiblnd_complete(), and kiblnd_post_rx().
#define IBLND_WID_TX 1
Definition at line 1005 of file o2iblnd.h.
Referenced by kiblnd_complete(), kiblnd_init_tx_msg(), and kiblnd_post_tx_locked().
#define KIB_IFNAME_SIZE 256
Definition at line 173 of file o2iblnd.h.
#define KIB_THREAD_CPT (id) ((id) >> KIB_THREAD_SHIFT)
Definition at line 378 of file o2iblnd.h.
Referenced by kiblnd_scheduler(), and kiblnd_start_schedulers().
#define KIB_THREAD_ID (cpt, tid) ((cpt) << KIB_THREAD_SHIFT | (tid))
Definition at line 377 of file o2iblnd.h.
Referenced by kiblnd_start_schedulers().
#define KIB_THREAD_SHIFT 16
Definition at line 376 of file o2iblnd.h.
#define KIB_THREAD_TID (id) ((id) & ((1UL << KIB_THREAD_SHIFT) - 1))
Definition at line 379 of file o2iblnd.h.
Referenced by kiblnd_start_schedulers().
#define kiblnd_conn_addref (conn)
Value:
do {                                                            \
        CDEBUG(D_NET, "conn[%p] (%d)++\n",                      \
               (conn), atomic_read(&(conn)->ibc_refcount)); \
        atomic_inc(&(conn)->ibc_refcount);                  \
} while (0)
Definition at line 850 of file o2iblnd.h.
Referenced by kiblnd_check_conns(), kiblnd_connreq_done(), kiblnd_cq_completion(), kiblnd_get_conn_by_idx(), kiblnd_launch_tx(), kiblnd_post_rx(), kiblnd_queue_tx_locked(), kiblnd_scheduler(), and kiblnd_tx_complete().
#define kiblnd_conn_decref (conn)
Value:
do {                                                                    \
        unsigned long flags;                                            \
                                                                        \
        CDEBUG(D_NET, "conn[%p] (%d)--\n",                              \
               (conn), atomic_read(&(conn)->ibc_refcount));             \
        LASSERT_ATOMIC_POS(&(conn)->ibc_refcount);                      \
        if (atomic_dec_and_test(&(conn)->ibc_refcount)) {               \
                spin_lock_irqsave(&kiblnd_data.kib_connd_lock, flags);  \
                list_add_tail(&(conn)->ibc_list,                        \
                                  &kiblnd_data.kib_connd_zombies);      \
                wake_up(&kiblnd_data.kib_connd_waitq);          \
                spin_unlock_irqrestore(&kiblnd_data.kib_connd_lock, flags);\
        }                                                               \
} while (0)
Definition at line 857 of file o2iblnd.h.
Referenced by kiblnd_active_connect(), kiblnd_check_conns(), kiblnd_cm_callback(), kiblnd_connd(), kiblnd_connreq_done(), kiblnd_create_conn(), kiblnd_ctl(), kiblnd_drop_rx(), kiblnd_launch_tx(), kiblnd_passive_connect(), kiblnd_post_rx(), kiblnd_scheduler(), kiblnd_tx_complete(), and kiblnd_tx_done().
#define KIBLND_CONN_PARAM (e) ((e)->param.conn.private_data)
Definition at line 1154 of file o2iblnd.h.
Referenced by kiblnd_cm_callback().
#define KIBLND_CONN_PARAM_LEN (e) ((e)->param.conn.private_data_len)
Definition at line 1155 of file o2iblnd.h.
Referenced by kiblnd_cm_callback().
#define kiblnd_peer_addref (peer)
Value:
do {                                                            \
        CDEBUG(D_NET, "peer[%p] -> %s (%d)++\n",                \
               (peer), libcfs_nid2str((peer)->ibp_nid),         \
               atomic_read (&(peer)->ibp_refcount));            \
        atomic_inc(&(peer)->ibp_refcount);                      \
} while (0)
Definition at line 873 of file o2iblnd.h.
Referenced by kiblnd_connd(), kiblnd_connect_peer(), kiblnd_launch_tx(), and kiblnd_passive_connect().
#define kiblnd_peer_decref (peer)
Value:
do {                                                            \
        CDEBUG(D_NET, "peer[%p] -> %s (%d)--\n",                \
               (peer), libcfs_nid2str((peer)->ibp_nid),         \
               atomic_read (&(peer)->ibp_refcount));            \
        LASSERT_ATOMIC_POS(&(peer)->ibp_refcount);              \
        if (atomic_dec_and_test(&(peer)->ibp_refcount))         \
                kiblnd_destroy_peer(peer);                      \
} while (0)
Definition at line 881 of file o2iblnd.h.
Referenced by kiblnd_active_connect(), kiblnd_cm_callback(), kiblnd_connd(), kiblnd_connect_peer(), kiblnd_destroy_conn(), kiblnd_launch_tx(), kiblnd_passive_connect(), and kiblnd_unlink_peer_locked().
#define kiblnd_rdma_create_id (cb, dev, ps, qpt) rdma_create_id(cb, dev, ps)
Definition at line 134 of file o2iblnd.h.
Referenced by kiblnd_connect_peer(), kiblnd_dev_failover(), and kiblnd_dev_need_failover().
#define KIBLND_UNMAP_ADDR (p, m, a) (a)
Definition at line 1122 of file o2iblnd.h.
Referenced by kiblnd_unmap_rx_descs(), and kiblnd_unmap_tx_pool().
#define KIBLND_UNMAP_ADDR_SET (p, m, a) do {} while (0)
Definition at line 1121 of file o2iblnd.h.
Referenced by kiblnd_map_rx_descs(), and kiblnd_map_tx_pool().
Typedef Documentation
typedef struct kib_conn kib_conn_t
typedef struct kib_connparams kib_connparams_t
typedef struct kib_connvars kib_connvars_t
typedef struct kib_hca_dev kib_hca_dev_t
typedef struct kib_net kib_net_t
typedef struct kib_peer kib_peer_t
typedef struct kib_pool kib_pool_t
typedef struct kib_poolset kib_poolset_t
typedef void(* kib_ps_node_fini_t)(struct kib_pool *po, struct list_head *node)
Definition at line 229 of file o2iblnd.h.
typedef void(* kib_ps_node_init_t)(struct kib_pool *po, struct list_head *node)
Definition at line 228 of file o2iblnd.h.
typedef int(* kib_ps_pool_create_t)(struct kib_poolset *ps, int inc, struct kib_pool **pp_po)
Definition at line 225 of file o2iblnd.h.
typedef void(* kib_ps_pool_destroy_t)(struct kib_pool *po)
Definition at line 227 of file o2iblnd.h.
typedef struct kib_rx kib_rx_t
typedef struct kib_tx kib_tx_t
Function Documentation
static u32 ib_inc_rkey (u32 rkey) [inline, static]
ib_inc_rkey - increments the key portion of the given rkey.
Can be used for calculating a new rkey for type 2 memory windows. - the rkey to increment.
Definition at line 767 of file o2iblnd.h.
Referenced by kiblnd_fmr_pool_map().
static void kiblnd_abort_receives (kib_conn_t * conn) [inline, static]
Definition at line 976 of file o2iblnd.h.
References kib_conn::ibc_cmid, and kib_data_t::kib_error_qpa.
Referenced by kiblnd_create_conn(), and kiblnd_finalise_conn().
int kiblnd_alloc_pages (kib_pages_t ** pp, int cpt, int npages)
Definition at line 1191 of file o2iblnd.c.
References CERROR, cfs_page_cpt_alloc(), kib_pages_t::ibp_npages, kib_pages_t::ibp_pages, kiblnd_free_pages(), LIBCFS_CPT_ALLOC, lnet_cpt_table, and offsetof.
Referenced by kiblnd_create_conn(), and kiblnd_create_tx_pool().
static int kiblnd_cfg_rdma_frags (struct lnet_ni * ni) [inline, static]
Definition at line 782 of file o2iblnd.h.
References IBLND_MAX_RDMA_FRAGS, lnet_ioctl_config_o2iblnd_tunables::lnd_map_on_demand, lnet_ioctl_config_lnd_tunables::lt_o2ib, lnet_ioctl_config_lnd_tunables::lt_tun_u, and lnet_ni::ni_lnd_tunables.
Referenced by kiblnd_create_peer(), and kiblnd_rdma_frags().
void kiblnd_close_conn (kib_conn_t * conn, int error)
Definition at line 1952 of file o2iblnd_cb.c.
References kib_data_t::kib_global_lock, kiblnd_close_conn_locked(), and kiblnd_data.
Referenced by kiblnd_check_conns(), kiblnd_cm_callback(), kiblnd_handle_completion(), kiblnd_handle_rx(), kiblnd_post_rx(), kiblnd_post_tx_locked(), kiblnd_rx_complete(), kiblnd_scheduler(), and kiblnd_tx_complete().
void kiblnd_close_conn_locked (kib_conn_t * conn, int error)
Definition at line 1882 of file o2iblnd_cb.c.
References CDEBUG, CNETERR, D_NET, kib_conn::ibc_active_txs, kib_conn::ibc_comms_error, kib_conn::ibc_list, kib_conn::ibc_peer, kib_conn::ibc_state, kib_conn::ibc_tx_noops, kib_conn::ibc_tx_queue, kib_conn::ibc_tx_queue_nocred, kib_conn::ibc_tx_queue_rsrvd, kib_dev_t::ibd_fail_list, IBLND_CONN_CLOSING, IBLND_CONN_ESTABLISHED, kib_peer::ibp_conns, kib_peer::ibp_error, kib_peer::ibp_ni, kib_peer::ibp_nid, kib_data_t::kib_connd_conns, kib_data_t::kib_connd_lock, kib_data_t::kib_connd_waitq, kib_data_t::kib_failed_devs, kib_data_t::kib_failover_waitq, kiblnd_data, kiblnd_dev_can_failover(), kiblnd_peer_active(), kiblnd_set_conn_state(), kiblnd_unlink_peer_locked(), LASSERT, libcfs_nid2str(), list_add_tail(), list_del(), list_empty(), and lnet_ni::ni_data.
Referenced by kiblnd_close_conn(), kiblnd_close_peer_conns_locked(), kiblnd_close_stale_conns_locked(), kiblnd_connreq_done(), and kiblnd_del_peer_locked().
int kiblnd_close_peer_conns_locked (kib_peer_t * peer, int why)
Definition at line 994 of file o2iblnd.c.
References CDEBUG, D_NET, kib_conn::ibc_version, kib_peer::ibp_conns, kib_peer::ibp_nid, kiblnd_close_conn_locked(), libcfs_nid2str(), list_entry, and list_for_each_safe.
Referenced by kiblnd_close_matching_conns(), and kiblnd_passive_connect().
int kiblnd_close_stale_conns_locked (kib_peer_t * peer, int version, __u64 incarnation)
Definition at line 1017 of file o2iblnd.c.
References CDEBUG, D_NET, kib_conn::ibc_incarnation, kib_conn::ibc_version, kib_peer::ibp_conns, kib_peer::ibp_nid, kiblnd_close_conn_locked(), libcfs_nid2str(), list_entry, list_for_each_safe, and LPX64.
Referenced by kiblnd_connreq_done().
int kiblnd_cm_callback (struct rdma_cm_id * cmid, struct rdma_cm_event * event)
Definition at line 2931 of file o2iblnd_cb.c.
References CDEBUG, CERROR, CNETERR, D_NET, kib_conn::ibc_peer, kib_conn::ibc_state, IBLND_CONN_ACTIVE_CONNECT, IBLND_CONN_ESTABLISHED, IBLND_CONN_PASSIVE_WAIT, kib_peer::ibp_nid, kib_tunables_t::kib_timeout, kiblnd_active_connect(), kiblnd_check_connreply(), kiblnd_close_conn(), kiblnd_conn_decref, KIBLND_CONN_PARAM, KIBLND_CONN_PARAM_LEN, kiblnd_connreq_done(), kiblnd_passive_connect(), kiblnd_peer_connect_failed(), kiblnd_peer_decref, kiblnd_rejected(), kiblnd_tunables, LASSERT, LBUG, LCONSOLE_ERROR_MSG, LCONSOLE_INFO, and libcfs_nid2str().
Referenced by kiblnd_connect_peer(), and kiblnd_dev_failover().
static int kiblnd_concurrent_sends (int version, struct lnet_ni * ni) [inline, static]
Definition at line 801 of file o2iblnd.h.
References concurrent_sends, IBLND_MSG_QUEUE_SIZE_V1, IBLND_MSG_VERSION_1, lnet_ioctl_config_o2iblnd_tunables::lnd_concurrent_sends, lnet_ioctl_config_lnd_tunables::lt_o2ib, lnet_ioctl_config_lnd_tunables::lt_tun_u, and lnet_ni::ni_lnd_tunables.
Referenced by kiblnd_check_sends(), and kiblnd_post_tx_locked().
int kiblnd_connd (void * arg)
Definition at line 3244 of file o2iblnd_cb.c.
References cfs_block_allsigs(), kib_conn::ibc_list, kib_conn::ibc_peer, kib_conn::ibc_reconnect, kib_peer::ibp_reconnected, kib_data_t::kib_connd, kib_data_t::kib_connd_conns, kib_data_t::kib_connd_lock, kib_data_t::kib_connd_waitq, kib_data_t::kib_connd_zombies, kib_data_t::kib_peer_hash_size, KIB_RECONN_BREAK, KIB_RECONN_HIGH_RACE, kib_data_t::kib_reconn_list, kib_data_t::kib_reconn_sec, kib_data_t::kib_reconn_wait, kib_data_t::kib_shutdown, kib_tunables_t::kib_timeout, kiblnd_check_conns(), kiblnd_conn_decref, kiblnd_data, kiblnd_destroy_conn(), kiblnd_disconnect_conn(), kiblnd_peer_addref, kiblnd_peer_decref, kiblnd_reconnect_peer(), kiblnd_thread_fini(), kiblnd_tunables, LIBCFS_FREE, list_add_tail(), list_del(), list_empty(), list_entry, list_splice_init(), list_head::next, and timeout.
Referenced by kiblnd_base_startup().
void kiblnd_cq_completion (struct ib_cq * cq, void * arg)
Definition at line 3444 of file o2iblnd_cb.c.
References kib_conn::ibc_cq, kib_conn::ibc_nrx, kib_conn::ibc_nsends_posted, kib_conn::ibc_ready, kib_conn::ibc_sched, kib_conn::ibc_sched_list, kib_conn::ibc_scheduled, kib_sched_info::ibs_conns, kib_sched_info::ibs_lock, kib_sched_info::ibs_waitq, kiblnd_conn_addref, LASSERT, and list_add_tail().
Referenced by kiblnd_create_conn().
void kiblnd_cq_event (struct ib_event * event, void * arg)
Definition at line 3476 of file o2iblnd_cb.c.
References CERROR, kib_conn::ibc_peer, kib_peer::ibp_nid, and libcfs_nid2str().
Referenced by kiblnd_create_conn().
kib_conn_t* kiblnd_create_conn (kib_peer_t * peer, struct rdma_cm_id * cmid, int state, int version)
Definition at line 699 of file o2iblnd.c.
References CDEBUG, CERROR, D_NET, kib_conn::ibc_active_txs, kib_conn::ibc_cmid, kib_conn::ibc_connvars, kib_conn::ibc_cq, kib_conn::ibc_early_rxs, kib_conn::ibc_hdev, kib_conn::ibc_lock, kib_conn::ibc_max_frags, kib_conn::ibc_nrx, kib_conn::ibc_peer, kib_conn::ibc_queue_depth, kib_conn::ibc_refcount, kib_conn::ibc_rx_pages, kib_conn::ibc_rxs, kib_conn::ibc_sched, kib_conn::ibc_state, kib_conn::ibc_tx_noops, kib_conn::ibc_tx_queue, kib_conn::ibc_tx_queue_nocred, kib_conn::ibc_tx_queue_rsrvd, kib_conn::ibc_version, kib_dev_t::ibd_fail_list, kib_dev_t::ibd_failover, kib_dev_t::ibd_hdev, kib_dev_t::ibd_ifname, kib_hca_dev::ibh_ibdev, kib_hca_dev::ibh_pd, IBLND_CONN_ACTIVE_CONNECT, IBLND_CONN_INIT, IBLND_CONN_PASSIVE_WAIT, IBLND_CQ_ENTRIES, IBLND_POSTRX_NO_CREDIT, IBLND_RECV_WRS, IBLND_RX_MSG_PAGES, IBLND_RX_MSGS, IBLND_SEND_WRS, kib_net::ibn_dev, kib_net::ibn_nconns, kib_peer::ibp_max_frags, kib_peer::ibp_ni, kib_peer::ibp_nid, kib_peer::ibp_queue_depth, kib_sched_info::ibs_lock, kib_sched_info::ibs_nthreads, INIT_LIST_HEAD, kib_data_t::kib_failed_devs, kib_data_t::kib_failover_waitq, kib_data_t::kib_global_lock, kib_data_t::kib_scheds, kiblnd_abort_receives(), kiblnd_alloc_pages(), kiblnd_conn_decref, kiblnd_cq_completion(), kiblnd_cq_event(), kiblnd_destroy_conn(), kiblnd_dev_can_failover(), kiblnd_get_completion_vector(), kiblnd_hdev_addref_locked(), kiblnd_map_rx_descs(), kiblnd_post_rx(), kiblnd_qp_event(), kiblnd_setup_mtu_locked(), LASSERT, LIBCFS_CPT_ALLOC, LIBCFS_FREE, libcfs_nid2str(), list_add_tail(), lnet_cpt_of_nid(), lnet_cpt_table, and lnet_ni::ni_data.
Referenced by kiblnd_active_connect(), and kiblnd_passive_connect().
int kiblnd_create_peer (lnet_ni_t * ni, kib_peer_t ** peerp, lnet_nid_t nid)
Definition at line 320 of file o2iblnd.c.
References CERROR, kib_net::ibn_npeers, kib_net::ibn_shutdown, kib_peer::ibp_conns, kib_peer::ibp_error, kib_peer::ibp_last_alive, kib_peer::ibp_list, kib_peer::ibp_max_frags, kib_peer::ibp_ni, kib_peer::ibp_nid, kib_peer::ibp_queue_depth, kib_peer::ibp_refcount, kib_peer::ibp_tx_queue, INIT_LIST_HEAD, kib_data_t::kib_global_lock, kiblnd_cfg_rdma_frags(), LASSERT, LIBCFS_CPT_ALLOC, lnet_cpt_of_nid(), lnet_cpt_table, LNET_NID_ANY, lnet_ni::ni_data, and lnet_ni::ni_peertxcredits.
Referenced by kiblnd_launch_tx(), and kiblnd_passive_connect().
void kiblnd_destroy_conn (kib_conn_t * conn, bool free_conn)
Definition at line 925 of file o2iblnd.c.
References CWARN, kib_conn::ibc_active_txs, kib_conn::ibc_cmid, kib_conn::ibc_connvars, kib_conn::ibc_cq, kib_conn::ibc_early_rxs, kib_conn::ibc_hdev, kib_conn::ibc_noops_posted, kib_conn::ibc_nsends_posted, kib_conn::ibc_peer, kib_conn::ibc_refcount, kib_conn::ibc_rx_pages, kib_conn::ibc_rxs, kib_conn::ibc_state, kib_conn::ibc_tx_noops, kib_conn::ibc_tx_queue, kib_conn::ibc_tx_queue_nocred, kib_conn::ibc_tx_queue_rsrvd, IBLND_CONN_DISCONNECTED, IBLND_CONN_INIT, IBLND_RX_MSGS, kib_net::ibn_nconns, kib_peer::ibp_ni, kiblnd_hdev_decref(), kiblnd_peer_decref, kiblnd_unmap_rx_descs(), LASSERT, LBUG, LIBCFS_FREE, list_empty(), and lnet_ni::ni_data.
Referenced by kiblnd_connd(), and kiblnd_create_conn().
void kiblnd_destroy_dev (kib_dev_t * dev)
Definition at line 2742 of file o2iblnd.c.
References kib_dev_t::ibd_fail_list, kib_dev_t::ibd_hdev, kib_dev_t::ibd_list, kib_dev_t::ibd_nets, kib_dev_t::ibd_nnets, kiblnd_hdev_decref(), LASSERT, LIBCFS_FREE, list_del(), and list_empty().
Referenced by kiblnd_shutdown(), and kiblnd_startup().
void kiblnd_destroy_peer (kib_peer_t * peer)
Definition at line 363 of file o2iblnd.c.
References kib_net::ibn_npeers, kib_peer::ibp_ni, kib_peer::ibp_refcount, kib_peer::ibp_tx_queue, kiblnd_peer_active(), kiblnd_peer_idle(), LASSERT, LIBCFS_FREE, list_empty(), and lnet_ni::ni_data.
static int kiblnd_dev_can_failover (kib_dev_t * dev) [inline, static]
Definition at line 836 of file o2iblnd.h.
References kib_dev_t::ibd_can_failover, kib_dev_t::ibd_fail_list, kib_tunables_t::kib_dev_failover, and list_empty().
Referenced by kiblnd_close_conn_locked(), kiblnd_create_conn(), and kiblnd_failover_thread().
int kiblnd_dev_failover (kib_dev_t * dev)
Definition at line 2608 of file o2iblnd.c.
References CERROR, cfs_cpt_for_each, kib_dev_t::ibd_can_failover, kib_dev_t::ibd_failed_failover, kib_dev_t::ibd_hdev, kib_dev_t::ibd_ifip, kib_dev_t::ibd_ifname, kib_dev_t::ibd_nets, kib_hca_dev::ibh_cmid, kib_hca_dev::ibh_dev, kib_hca_dev::ibh_ibdev, kib_hca_dev::ibh_pd, kib_hca_dev::ibh_ref, kib_net::ibn_fmr_ps, kib_net::ibn_tx_ps, kib_tunables_t::kib_dev_failover, kib_data_t::kib_global_lock, kib_tunables_t::kib_service, kiblnd_cm_callback(), kiblnd_destroy_fmr_pool_list(), kiblnd_destroy_pool_list(), kiblnd_dev_need_failover(), kiblnd_fail_fmr_poolset(), kiblnd_fail_poolset(), kiblnd_hdev_decref(), kiblnd_hdev_setup_mrs(), kiblnd_rdma_create_id, kiblnd_tunables, LASSERT, LIBCFS_ALLOC, list_empty(), list_for_each_entry, LIST_HEAD_INIT, lnet_cpt_table, and kib_tx_poolset_t::tps_poolset.
Referenced by kiblnd_create_dev(), and kiblnd_failover_thread().
static int kiblnd_dma_map_sg (struct ib_device * dev, struct scatterlist * sg, int nents, enum dma_data_direction direction) [inline, static]
Definition at line 1124 of file o2iblnd.h.
Referenced by kiblnd_map_tx().
static __u64 kiblnd_dma_map_single (struct ib_device * dev, void * msg, size_t size, enum dma_data_direction direction) [inline, static]
Definition at line 1107 of file o2iblnd.h.
Referenced by kiblnd_map_rx_descs(), and kiblnd_map_tx_pool().
static __u64 kiblnd_dma_mapping_error (struct ib_device * dev, u64 dma_addr) [inline, static]
Definition at line 1102 of file o2iblnd.h.
Referenced by kiblnd_map_rx_descs(), and kiblnd_map_tx_pool().
static void kiblnd_dma_unmap_sg (struct ib_device * dev, struct scatterlist * sg, int nents, enum dma_data_direction direction) [inline, static]
Definition at line 1131 of file o2iblnd.h.
Referenced by kiblnd_unmap_tx().
static void kiblnd_dma_unmap_single (struct ib_device * dev, __u64 addr, size_t size, enum dma_data_direction direction) [inline, static]
Definition at line 1114 of file o2iblnd.h.
Referenced by kiblnd_unmap_rx_descs(), and kiblnd_unmap_tx_pool().
int kiblnd_failover_thread (void * arg)
Definition at line 3628 of file o2iblnd_cb.c.
References cfs_block_allsigs(), cfs_time_before(), cfs_time_current(), cfs_time_seconds(), cfs_time_shift(), kib_dev_t::ibd_fail_list, kib_dev_t::ibd_failed_failover, kib_dev_t::ibd_failover, kib_dev_t::ibd_next_failover, kib_tunables_t::kib_dev_failover, kib_data_t::kib_devs, kib_data_t::kib_failed_devs, kib_data_t::kib_failover_waitq, kib_data_t::kib_global_lock, kib_data_t::kib_shutdown, kiblnd_data, kiblnd_dev_can_failover(), kiblnd_dev_failover(), kiblnd_thread_fini(), kiblnd_tunables, LASSERT, list_add_tail(), list_del_init(), list_empty(), and list_for_each_entry.
Referenced by kiblnd_base_startup().
kib_peer_t* kiblnd_find_peer_locked (lnet_nid_t nid)
Definition at line 383 of file o2iblnd.c.
References CDEBUG, D_NET, kib_peer::ibp_nid, kib_peer::ibp_refcount, kib_peer::ibp_version, kiblnd_nid2peerlist(), kiblnd_peer_idle(), LASSERT, libcfs_nid2str(), list_entry, and list_for_each.
Referenced by kiblnd_launch_tx(), kiblnd_passive_connect(), and kiblnd_query().
struct ib_mr* kiblnd_find_rd_dma_mr (struct lnet_ni * ni, kib_rdma_desc_t * rd, int negotiated_nfrags) [read]
Definition at line 1389 of file o2iblnd.c.
References kib_dev_t::ibd_hdev, kib_hca_dev::ibh_mrs, kib_net::ibn_dev, LASSERT, lnet_ioctl_config_o2iblnd_tunables::lnd_map_on_demand, lnet_ioctl_config_lnd_tunables::lt_o2ib, lnet_ioctl_config_lnd_tunables::lt_tun_u, lnet_ni::ni_data, and lnet_ni::ni_lnd_tunables.
Referenced by kiblnd_map_tx().
int kiblnd_fmr_pool_map (kib_fmr_poolset_t * fps, kib_tx_t * tx, kib_rdma_desc_t * rd, __u32 nob, __u64 iov, kib_fmr_t * fmr)
Definition at line 1790 of file o2iblnd.c.
References __u64, CDEBUG, CERROR, cfs_time_before(), cfs_time_current(), cfs_time_shift(), D_NET, kib_fmr_pool_t::fast_reg, kib_fmr_pool_t::fmr, kib_fmr_t::fmr_frd, kib_fmr_t::fmr_key, kib_fmr_t::fmr_pfmr, kib_fmr_t::fmr_pool, kib_fmr_pool_t::fpo_deadline, kib_fmr_pool_t::fpo_is_fmr, kib_fmr_pool_t::fpo_list, kib_fmr_pool_t::fpo_map_count, kib_fmr_poolset_t::fps_increasing, kib_fmr_poolset_t::fps_lock, kib_fmr_poolset_t::fps_next_retry, kib_fmr_poolset_t::fps_pool_list, kib_fmr_poolset_t::fps_version, kib_fast_reg_descriptor::frd_fastreg_wr, kib_fast_reg_descriptor::frd_frpl, kib_fast_reg_descriptor::frd_inv_wr, kib_fast_reg_descriptor::frd_list, kib_fast_reg_descriptor::frd_mr, kib_fast_reg_descriptor::frd_valid, ib_inc_rkey(), IBLND_POOL_DEADLINE, IBLND_POOL_RETRY, IBLND_WID_MR, kiblnd_create_fmr_pool(), kiblnd_map_tx_pages(), LASSERT, likely, list_add_tail(), list_del(), list_empty(), list_for_each_entry, kib_tx::tx_frags, kib_tx::tx_nfrags, kib_tx::tx_pages, kib_tx::tx_rd, unlikely, version, and ib_rdma_wr::wr.
Referenced by kiblnd_fmr_map_tx().
void kiblnd_fmr_pool_unmap (kib_fmr_t * fmr, int status)
Definition at line 1733 of file o2iblnd.c.
References cfs_time_current(), kib_fmr_pool_t::fast_reg, kib_fmr_pool_t::fmr, kib_fmr_t::fmr_frd, kib_fmr_t::fmr_pfmr, kib_fmr_t::fmr_pool, kib_fmr_pool_t::fpo_is_fmr, kib_fmr_pool_t::fpo_list, kib_fmr_pool_t::fpo_map_count, kib_fmr_pool_t::fpo_owner, kib_fmr_poolset_t::fps_lock, kib_fmr_poolset_t::fps_pool_list, kib_fmr_poolset_t::fps_version, kib_fast_reg_descriptor::frd_list, kib_fast_reg_descriptor::frd_valid, kiblnd_destroy_fmr_pool_list(), kiblnd_fmr_pool_is_idle(), LASSERT, list_add_tail(), list_empty(), list_for_each_entry_safe, LIST_HEAD_INIT, list_move(), list_head::next, and now().
Referenced by kiblnd_unmap_tx().
static kib_conn_t* kiblnd_get_conn_locked (kib_peer_t * peer) [inline, static]
Definition at line 922 of file o2iblnd.h.
References kib_peer::ibp_conns, LASSERT, list_empty(), list_entry, and list_head::next.
Referenced by kiblnd_launch_tx().
static void kiblnd_hdev_addref_locked (kib_hca_dev_t * hdev) [inline, static]
Definition at line 821 of file o2iblnd.h.
References kib_hca_dev::ibh_ref, and LASSERT.
Referenced by kiblnd_create_conn(), and kiblnd_current_hdev().
static void kiblnd_hdev_decref (kib_hca_dev_t * hdev) [inline, static]
Definition at line 828 of file o2iblnd.h.
References kib_hca_dev::ibh_ref, kiblnd_hdev_destroy(), and LASSERT.
Referenced by kiblnd_create_fmr_pool(), kiblnd_destroy_conn(), kiblnd_destroy_dev(), kiblnd_destroy_fmr_pool(), kiblnd_dev_failover(), and kiblnd_unmap_tx_pool().
void kiblnd_hdev_destroy (kib_hca_dev_t * hdev)
Definition at line 2512 of file o2iblnd.c.
References kib_hca_dev::ibh_cmid, kib_hca_dev::ibh_pd, kiblnd_hdev_cleanup_mrs(), and LIBCFS_FREE.
Referenced by kiblnd_hdev_decref().
static void kiblnd_init_msg (kib_msg_t * msg, int type, int body_nob) [inline, static]
Definition at line 1041 of file o2iblnd.h.
References offsetof.
Referenced by kiblnd_active_connect(), kiblnd_init_tx_msg(), and kiblnd_passive_connect().
void kiblnd_launch_tx (lnet_ni_t * ni, kib_tx_t * tx, lnet_nid_t nid)
Definition at line 1367 of file o2iblnd_cb.c.
References CERROR, kib_peer::ibp_connecting, kib_peer::ibp_conns, kib_peer::ibp_list, kib_peer::ibp_tx_queue, kib_data_t::kib_global_lock, kiblnd_conn_addref, kiblnd_conn_decref, kiblnd_connect_peer(), kiblnd_create_peer(), kiblnd_data, kiblnd_find_peer_locked(), kiblnd_get_conn_locked(), kiblnd_nid2peerlist(), kiblnd_peer_addref, kiblnd_peer_connecting(), kiblnd_peer_decref, kiblnd_queue_tx(), kiblnd_tx_done(), LASSERT, libcfs_nid2str(), list_add_tail(), list_empty(), lnet_ni::ni_data, kib_tx::tx_conn, kib_tx::tx_list, kib_tx::tx_nwrq, kib_tx::tx_status, and kib_tx::tx_waiting.
Referenced by kiblnd_query(), and kiblnd_send().
void kiblnd_map_rx_descs (kib_conn_t * conn)
Definition at line 1246 of file o2iblnd.c.
References __u64, CDEBUG, D_NET, kib_conn::ibc_hdev, kib_conn::ibc_rx_pages, kib_conn::ibc_rxs, kib_hca_dev::ibh_ibdev, IBLND_MSG_SIZE, IBLND_RX_MSG_PAGES, IBLND_RX_MSGS, kib_pages_t::ibp_pages, kiblnd_dma_map_single(), kiblnd_dma_mapping_error(), KIBLND_UNMAP_ADDR_SET, LASSERT, LPX64, kib_rx::rx_conn, kib_rx::rx_msg, and kib_rx::rx_msgaddr.
Referenced by kiblnd_create_conn().
int kiblnd_msg_queue_size (int version, struct lnet_ni * ni)
Definition at line 166 of file o2iblnd_modparams.c.
References IBLND_MSG_QUEUE_SIZE_V1, IBLND_MSG_VERSION_1, lnet_ni::ni_peertxcredits, and peer_credits.
Referenced by kiblnd_passive_connect().
static int kiblnd_need_noop (kib_conn_t * conn) [inline, static]
Definition at line 940 of file o2iblnd.h.
References kib_conn::ibc_credits, kib_conn::ibc_outstanding_credits, kib_conn::ibc_peer, kib_conn::ibc_state, kib_conn::ibc_tx_noops, kib_conn::ibc_tx_queue, kib_conn::ibc_tx_queue_nocred, kib_conn::ibc_version, IBLND_CONN_ESTABLISHED, IBLND_CREDITS_HIGHWATER, IBLND_OOB_CAPABLE, kib_peer::ibp_ni, kiblnd_send_keepalive(), LASSERT, list_empty(), lnet_ioctl_config_lnd_tunables::lt_o2ib, lnet_ioctl_config_lnd_tunables::lt_tun_u, and lnet_ni::ni_lnd_tunables.
Referenced by kiblnd_check_conns(), kiblnd_check_sends(), and kiblnd_post_tx_locked().
static struct list_head* kiblnd_nid2peerlist (lnet_nid_t nid) [static, read]
Definition at line 906 of file o2iblnd.h.
References kib_data_t::kib_peer_hash_size, and kib_data_t::kib_peers.
Referenced by kiblnd_close_matching_conns(), kiblnd_del_peer(), kiblnd_find_peer_locked(), kiblnd_launch_tx(), and kiblnd_passive_connect().
void kiblnd_pack_msg (lnet_ni_t * ni, kib_msg_t * msg, int version, int credits, lnet_nid_t dstnid, __u64 dststamp)
Definition at line 183 of file o2iblnd.c.
References IBLND_MSG_MAGIC, kib_net::ibn_incarnation, kib_tunables_t::kib_cksum, kiblnd_cksum(), kiblnd_tunables, lnet_ni::ni_data, and lnet_ni::ni_nid.
Referenced by kiblnd_active_connect(), kiblnd_passive_connect(), and kiblnd_post_tx_locked().
static int kiblnd_peer_active (kib_peer_t * peer) [inline, static]
Definition at line 915 of file o2iblnd.h.
References kib_peer::ibp_list, and list_empty().
Referenced by kiblnd_close_conn_locked(), kiblnd_connreq_done(), kiblnd_destroy_peer(), kiblnd_passive_connect(), kiblnd_peer_connect_failed(), kiblnd_reconnect_peer(), and kiblnd_unlink_peer_locked().
static bool kiblnd_peer_connecting (kib_peer_t * peer) [inline, static]
Definition at line 892 of file o2iblnd.h.
References kib_peer::ibp_accepting, kib_peer::ibp_connecting, and kib_peer::ibp_reconnecting.
Referenced by kiblnd_launch_tx(), kiblnd_peer_connect_failed(), and kiblnd_peer_idle().
static bool kiblnd_peer_idle (kib_peer_t * peer) [inline, static]
Definition at line 900 of file o2iblnd.h.
References kib_peer::ibp_conns, kiblnd_peer_connecting(), and list_empty().
Referenced by kiblnd_close_matching_conns(), kiblnd_del_peer(), kiblnd_destroy_peer(), kiblnd_find_peer_locked(), kiblnd_get_conn_by_idx(), kiblnd_get_peer_info(), and kiblnd_peer_notify().
struct list_head* kiblnd_pool_alloc_node (kib_poolset_t * ps) [read]
Definition at line 2118 of file o2iblnd.c.
References CDEBUG, CERROR, cfs_time_before(), cfs_time_current(), cfs_time_seconds(), cfs_time_shift(), D_NET, IBLND_POOL_DEADLINE, IBLND_POOL_RETRY, list_add_tail(), list_del(), list_empty(), list_for_each_entry, list_head::next, kib_pool::po_allocated, kib_pool::po_deadline, kib_pool::po_free_list, kib_pool::po_list, kib_poolset::ps_increasing, kib_poolset::ps_lock, kib_poolset::ps_name, kib_poolset::ps_next_retry, kib_poolset::ps_node_init, kib_poolset::ps_pool_create, kib_poolset::ps_pool_list, and kib_poolset::ps_pool_size.
Referenced by kiblnd_get_idle_tx().
void kiblnd_pool_free_node (kib_pool_t * pool, struct list_head * node)
Definition at line 2087 of file o2iblnd.c.
References cfs_time_current(), kiblnd_destroy_pool_list(), kiblnd_pool_is_idle(), LASSERT, list_add(), list_empty(), list_for_each_entry_safe, LIST_HEAD_INIT, list_move(), list_head::next, now(), kib_pool::po_allocated, kib_pool::po_free_list, kib_pool::po_list, kib_pool::po_owner, kib_poolset::ps_lock, kib_poolset::ps_node_fini, and kib_poolset::ps_pool_list.
Referenced by kiblnd_tx_done().
int kiblnd_post_rx (kib_rx_t * rx, int credit)
Definition at line 156 of file o2iblnd_cb.c.
References CERROR, kib_conn::ibc_cmid, kib_conn::ibc_hdev, kib_conn::ibc_lock, kib_conn::ibc_outstanding_credits, kib_conn::ibc_peer, kib_conn::ibc_reserved_credits, kib_conn::ibc_state, kib_hca_dev::ibh_mrs, IBLND_CONN_ESTABLISHED, IBLND_CONN_INIT, IBLND_MSG_SIZE, IBLND_POSTRX_NO_CREDIT, IBLND_POSTRX_PEER_CREDIT, IBLND_POSTRX_RSRVD_CREDIT, IBLND_WID_RX, kib_peer::ibp_ni, kib_peer::ibp_nid, kiblnd_check_sends(), kiblnd_close_conn(), kiblnd_conn_addref, kiblnd_conn_decref, kiblnd_drop_rx(), kiblnd_ptr2wreqid(), LASSERT, libcfs_nid2str(), lnet_ni::ni_data, kib_rx::rx_conn, kib_rx::rx_msgaddr, kib_rx::rx_nob, kib_rx::rx_sge, kib_rx::rx_wrq, and unlikely.
Referenced by kiblnd_create_conn(), kiblnd_handle_rx(), and kiblnd_recv().
static __u64 kiblnd_ptr2wreqid (void * ptr, int type) [inline, static]
Definition at line 1012 of file o2iblnd.h.
References __u64, IBLND_WID_MASK, and LASSERT.
Referenced by kiblnd_init_rdma(), kiblnd_init_tx_msg(), kiblnd_post_rx(), and kiblnd_post_tx_locked().
void kiblnd_qp_event (struct ib_event * event, void * arg)
Definition at line 3391 of file o2iblnd_cb.c.
References CDEBUG, CERROR, D_NET, kib_conn::ibc_peer, kib_peer::ibp_nid, and libcfs_nid2str().
Referenced by kiblnd_create_conn().
static const char* kiblnd_queue2str (kib_conn_t * conn, struct list_head * q) [inline, static]
Definition at line 983 of file o2iblnd.h.
References kib_conn::ibc_active_txs, kib_conn::ibc_tx_queue, kib_conn::ibc_tx_queue_nocred, kib_conn::ibc_tx_queue_rsrvd, and LBUG.
Referenced by kiblnd_check_txs_locked().
static int kiblnd_rd_consume_frag (kib_rdma_desc_t * rd, int index, __u32 nob) [inline, static]
Definition at line 1078 of file o2iblnd.h.
Referenced by kiblnd_init_rdma().
static __u64 kiblnd_rd_frag_addr (kib_rdma_desc_t * rd, int index) [inline, static]
Definition at line 1060 of file o2iblnd.h.
Referenced by kiblnd_init_rdma().
static __u32 kiblnd_rd_frag_key (kib_rdma_desc_t * rd, int index) [inline, static]
Definition at line 1072 of file o2iblnd.h.
Referenced by kiblnd_init_rdma().
static __u32 kiblnd_rd_frag_size (kib_rdma_desc_t * rd, int index) [inline, static]
Definition at line 1066 of file o2iblnd.h.
Referenced by kiblnd_init_rdma().
static int kiblnd_rd_msg_size (kib_rdma_desc_t * rd, int msgtype, int n) [inline, static]
Definition at line 1091 of file o2iblnd.h.
References IBLND_MSG_GET_REQ, IBLND_MSG_PUT_ACK, LASSERT, offsetof, and WIRE_ATTR::rd_frags.
Referenced by kiblnd_unpack_rd().
static int kiblnd_rd_size (kib_rdma_desc_t * rd) [inline, static]
Definition at line 1048 of file o2iblnd.h.
References size.
Referenced by kiblnd_handle_rx().
static int kiblnd_rdma_frags (int version, struct lnet_ni * ni) [inline, static]
Definition at line 793 of file o2iblnd.h.
References IBLND_MAX_RDMA_FRAGS, IBLND_MSG_VERSION_1, and kiblnd_cfg_rdma_frags().
Referenced by kiblnd_passive_connect().
bool kiblnd_reconnect_peer (kib_peer_t * peer)
Definition at line 1317 of file o2iblnd_cb.c.
References CWARN, kib_peer::ibp_accepting, kib_peer::ibp_connecting, kib_peer::ibp_conns, kib_peer::ibp_ni, kib_peer::ibp_nid, kib_peer::ibp_reconnected, kib_peer::ibp_reconnecting, kib_peer::ibp_tx_queue, INIT_LIST_HEAD, kib_data_t::kib_global_lock, kiblnd_connect_peer(), kiblnd_data, kiblnd_peer_active(), kiblnd_txlist_done(), LASSERT, libcfs_nid2str(), list_empty(), and list_splice_init().
Referenced by kiblnd_connd().
int kiblnd_recv (lnet_ni_t * ni, void * private, lnet_msg_t * lntmsg, int delayed, unsigned int niov, struct kvec * iov, lnet_kiov_t * kiov, unsigned int offset, unsigned int mlen, unsigned int rlen)
Definition at line 1718 of file o2iblnd_cb.c.
References CERROR, kib_conn::ibc_peer, IBLND_MSG_GET_DONE, IBLND_MSG_GET_REQ, IBLND_MSG_IMMEDIATE, IBLND_MSG_PUT_ACK, IBLND_MSG_PUT_NAK, IBLND_MSG_PUT_REQ, IBLND_MSG_SIZE, IBLND_POSTRX_NO_CREDIT, IBLND_POSTRX_PEER_CREDIT, kib_peer::ibp_nid, kiblnd_get_idle_tx(), kiblnd_init_tx_msg(), kiblnd_post_rx(), kiblnd_queue_tx(), kiblnd_reply(), kiblnd_send_completion(), kiblnd_setup_rd_iov(), kiblnd_setup_rd_kiov(), kiblnd_tx_done(), LASSERT, LBUG, libcfs_nid2str(), lnet_copy_flat2iov(), lnet_copy_flat2kiov(), lnet_finalize(), offsetof, kib_rx::rx_conn, kib_rx::rx_msg, kib_rx::rx_nob, kib_tx::tx_cookie, kib_tx::tx_lntmsg, kib_tx::tx_msg, and kib_tx::tx_waiting.
int kiblnd_scheduler (void * arg)
Definition at line 3485 of file o2iblnd_cb.c.
References cfs_block_allsigs(), cfs_cpt_bind(), CWARN, kib_conn::ibc_cq, kib_conn::ibc_peer, kib_conn::ibc_ready, kib_conn::ibc_sched_list, kib_conn::ibc_scheduled, kib_conn::ibc_state, IBLND_RESCHED, IBLND_WID_INVAL, kib_peer::ibp_nid, kib_sched_info::ibs_conns, kib_sched_info::ibs_cpt, kib_sched_info::ibs_lock, kib_sched_info::ibs_waitq, kib_data_t::kib_scheds, kib_data_t::kib_shutdown, KIB_THREAD_CPT, kiblnd_close_conn(), kiblnd_complete(), kiblnd_conn_addref, kiblnd_conn_decref, kiblnd_data, kiblnd_thread_fini(), LASSERT, LCONSOLE_ERROR, libcfs_nid2str(), list_add_tail(), list_del(), list_empty(), list_entry, lnet_cpt_table, list_head::next, and unlikely.
Referenced by kiblnd_start_schedulers().
int kiblnd_send (lnet_ni_t * ni, void * private, lnet_msg_t * lntmsg)
Definition at line 1486 of file o2iblnd_cb.c.
References CDEBUG, CERROR, D_NET, IBLND_MSG_GET_REQ, IBLND_MSG_IMMEDIATE, IBLND_MSG_PUT_REQ, IBLND_MSG_SIZE, lnet_libmd::iov, kiblnd_get_idle_tx(), kiblnd_init_tx_msg(), kiblnd_launch_tx(), kiblnd_setup_rd_iov(), kiblnd_setup_rd_kiov(), kiblnd_tx_done(), lnet_libmd::kiov, LASSERT, LBUG, libcfs_id2str(), libcfs_nid2str(), lnet_copy_iov2flat(), lnet_copy_kiov2flat(), lnet_create_reply_msg(), LNET_MAX_IOV, LNET_MD_KIOV, LNET_MSG_ACK, LNET_MSG_GET, LNET_MSG_PUT, LNET_MSG_REPLY, lnet_libmd::md_iov, lnet_libmd::md_length, lnet_libmd::md_niov, lnet_libmd::md_options, lnet_msg::msg_hdr, lnet_msg::msg_iov, lnet_msg::msg_kiov, lnet_msg::msg_len, lnet_msg::msg_md, lnet_msg::msg_niov, lnet_msg::msg_offset, lnet_msg::msg_routing, lnet_msg::msg_target, lnet_msg::msg_target_is_router, lnet_msg::msg_type, lnet_process_id_t::nid, offsetof, kib_tx::tx_cookie, kib_tx::tx_lntmsg, kib_tx::tx_msg, kib_tx::tx_rd, and kib_tx::tx_waiting.
static int kiblnd_send_keepalive (kib_conn_t * conn) [inline, static]
Definition at line 931 of file o2iblnd.h.
References cfs_time_after(), kib_conn::ibc_last_send, and kib_tunables_t::kib_keepalive.
Referenced by kiblnd_need_noop().
static void kiblnd_set_conn_state (kib_conn_t * conn, int state) [inline, static]
Definition at line 1034 of file o2iblnd.h.
References kib_conn::ibc_state.
Referenced by kiblnd_close_conn_locked(), kiblnd_connreq_done(), and kiblnd_finalise_conn().
static __u64 kiblnd_sg_dma_address (struct ib_device * dev, struct scatterlist * sg) [inline, static]
Definition at line 1138 of file o2iblnd.h.
Referenced by kiblnd_map_tx().
static unsigned int kiblnd_sg_dma_len (struct ib_device * dev, struct scatterlist * sg) [inline, static]
Definition at line 1144 of file o2iblnd.h.
Referenced by kiblnd_map_tx().
int kiblnd_thread_start (int(*)(void *arg) fn, void * arg, char * name)
Definition at line 1833 of file o2iblnd_cb.c.
References kib_data_t::kib_nthreads, and kiblnd_data.
Referenced by kiblnd_base_startup(), and kiblnd_start_schedulers().
int kiblnd_translate_mtu (int value)
Definition at line 636 of file o2iblnd.c.
Referenced by kiblnd_setup_mtu_locked(), and kiblnd_tunables_setup().
int kiblnd_tunables_init (void)
Definition at line 279 of file o2iblnd_modparams.c.
References concurrent_sends, default_tunables, fmr_cache, fmr_flush_trigger, fmr_pool_size, lnet_ioctl_config_o2iblnd_tunables::lnd_concurrent_sends, lnet_ioctl_config_o2iblnd_tunables::lnd_fmr_cache, lnet_ioctl_config_o2iblnd_tunables::lnd_fmr_flush_trigger, lnet_ioctl_config_o2iblnd_tunables::lnd_fmr_pool_size, lnet_ioctl_config_o2iblnd_tunables::lnd_map_on_demand, lnet_ioctl_config_o2iblnd_tunables::lnd_peercredits_hiw, lnet_ioctl_config_o2iblnd_tunables::lnd_version, map_on_demand, and peer_credits_hiw.
Referenced by ko2iblnd_init().
int kiblnd_tunables_setup (struct lnet_ni * ni)
Definition at line 177 of file o2iblnd_modparams.c.
References CERROR, credits, CWARN, default_tunables, fmr_cache, fmr_flush_trigger, fmr_pool_size, IBLND_CREDITS_DEFAULT, IBLND_CREDITS_MAX, IBLND_MAX_RDMA_FRAGS, kib_tunables_t::kib_ib_mtu, kiblnd_translate_mtu(), LIBCFS_ALLOC, lnet_ioctl_config_o2iblnd_tunables::lnd_concurrent_sends, lnet_ioctl_config_o2iblnd_tunables::lnd_fmr_cache, lnet_ioctl_config_o2iblnd_tunables::lnd_fmr_flush_trigger, lnet_ioctl_config_o2iblnd_tunables::lnd_fmr_pool_size, lnet_ioctl_config_o2iblnd_tunables::lnd_map_on_demand, lnet_ioctl_config_o2iblnd_tunables::lnd_peercredits_hiw, lnet_ioctl_config_o2iblnd_tunables::lnd_version, lnet_ioctl_config_lnd_tunables::lt_o2ib, lnet_ioctl_config_lnd_tunables::lt_tun_u, lnet_ni::ni_lnd_tunables, lnet_ni::ni_maxtxcredits, lnet_ni::ni_peerrtrcredits, lnet_ni::ni_peertimeout, lnet_ni::ni_peertxcredits, peer_buffer_credits, peer_credits, peer_credits_hiw, and peer_timeout.
Referenced by kiblnd_startup().
void kiblnd_txlist_done (lnet_ni_t * ni, struct list_head * txlist, int status)
Definition at line 98 of file o2iblnd_cb.c.
References kiblnd_tx_done(), list_del(), list_empty(), list_entry, list_head::next, kib_tx::tx_list, kib_tx::tx_status, and kib_tx::tx_waiting.
Referenced by kiblnd_abort_txs(), kiblnd_connreq_done(), kiblnd_del_peer(), kiblnd_peer_connect_failed(), and kiblnd_reconnect_peer().
void kiblnd_unlink_peer_locked (kib_peer_t * peer)
Definition at line 409 of file o2iblnd.c.
References kib_peer::ibp_conns, kib_peer::ibp_list, kiblnd_peer_active(), kiblnd_peer_decref, LASSERT, list_del_init(), and list_empty().
Referenced by kiblnd_close_conn_locked(), kiblnd_del_peer_locked(), and kiblnd_peer_connect_failed().
void kiblnd_unmap_rx_descs (kib_conn_t * conn)
Definition at line 1221 of file o2iblnd.c.
References kib_conn::ibc_hdev, kib_conn::ibc_rx_pages, kib_conn::ibc_rxs, kib_hca_dev::ibh_ibdev, IBLND_MSG_SIZE, IBLND_RX_MSGS, kiblnd_dma_unmap_single(), kiblnd_free_pages(), KIBLND_UNMAP_ADDR, LASSERT, kib_rx::rx_msgaddr, and kib_rx::rx_nob.
Referenced by kiblnd_destroy_conn().
int kiblnd_unpack_msg (kib_msg_t * msg, int nob)
Definition at line 208 of file o2iblnd.c.
References __swab16, __swab16s, __swab32, __swab32s, __swab64s, CERROR, CLASSERT, IBLND_MSG_CONNACK, IBLND_MSG_CONNREQ, IBLND_MSG_GET_DONE, IBLND_MSG_GET_REQ, IBLND_MSG_IMMEDIATE, IBLND_MSG_MAGIC, IBLND_MSG_NOOP, IBLND_MSG_PUT_ACK, IBLND_MSG_PUT_DONE, IBLND_MSG_PUT_NAK, IBLND_MSG_PUT_REQ, IBLND_MSG_VERSION, IBLND_MSG_VERSION_1, kiblnd_cksum(), kiblnd_msgtype2size(), kiblnd_msgtype2str(), kiblnd_unpack_rd(), libcfs_nid2str(), LNET_NID_ANY, offsetof, and version.
Referenced by kiblnd_check_connreply(), kiblnd_passive_connect(), and kiblnd_rx_complete().
static void* kiblnd_wreqid2ptr (__u64 wreqid) [inline, static]
Definition at line 1022 of file o2iblnd.h.
References IBLND_WID_MASK.
Referenced by kiblnd_complete().
static int kiblnd_wreqid2type (__u64 wreqid) [inline, static]
Definition at line 1028 of file o2iblnd.h.
References IBLND_WID_MASK.
Referenced by kiblnd_complete().
Variable Documentation
kib_data_t kiblnd_data
Definition at line 46 of file o2iblnd.c.
Referenced by kiblnd_active_connect(), kiblnd_check_connreply(), kiblnd_check_conns(), kiblnd_check_reconnect(), kiblnd_close_conn(), kiblnd_close_conn_locked(), kiblnd_connd(), kiblnd_connreq_done(), kiblnd_disconnect_conn(), kiblnd_failover_thread(), kiblnd_handle_early_rxs(), kiblnd_launch_tx(), kiblnd_passive_connect(), kiblnd_peer_connect_failed(), kiblnd_peer_notify(), kiblnd_reconnect_peer(), kiblnd_rx_complete(), kiblnd_scheduler(), kiblnd_thread_fini(), and kiblnd_thread_start().
kib_tunables_t kiblnd_tunables
Definition at line 146 of file o2iblnd_modparams.c.
Referenced by kiblnd_active_connect(), kiblnd_base_startup(), kiblnd_cm_callback(), kiblnd_connd(), kiblnd_connect_peer(), kiblnd_dev_failover(), kiblnd_dev_need_failover(), kiblnd_failover_thread(), kiblnd_net_init_pools(), kiblnd_pack_msg(), kiblnd_passive_connect(), kiblnd_queue_tx_locked(), kiblnd_rejected(), kiblnd_setup_mtu_locked(), kiblnd_start_schedulers(), kiblnd_startup(), and kiblnd_tx_pool_size().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.