Lustre: lnet/klnds/o2iblnd/o2iblnd_cb.c File Reference
lnet/klnds/o2iblnd/o2iblnd_cb.c File Reference
#include "o2iblnd.h"
Defines
#define KIB_RECONN_HIGH_RACE 10
#define KIB_RECONN_BREAK 100
Functions
static void kiblnd_peer_alive (kib_peer_t *peer)
static void kiblnd_peer_connect_failed (kib_peer_t *peer, int active, int error)
static void kiblnd_check_sends (kib_conn_t *conn)
static void kiblnd_init_tx_msg (lnet_ni_t *ni, kib_tx_t *tx, int type, int body_nob)
static int kiblnd_init_rdma (kib_conn_t *conn, kib_tx_t *tx, int type, int resid, kib_rdma_desc_t *dstrd, __u64 dstcookie)
static void kiblnd_queue_tx_locked (kib_tx_t *tx, kib_conn_t *conn)
static void kiblnd_queue_tx (kib_tx_t *tx, kib_conn_t *conn)
static void kiblnd_unmap_tx (lnet_ni_t *ni, kib_tx_t *tx)
static void kiblnd_tx_done (lnet_ni_t *ni, kib_tx_t *tx)
void kiblnd_txlist_done (lnet_ni_t *ni, struct list_head *txlist, int status)
static kib_tx_t * kiblnd_get_idle_tx (lnet_ni_t *ni, lnet_nid_t target)
static void kiblnd_drop_rx (kib_rx_t *rx)
int kiblnd_post_rx (kib_rx_t *rx, int credit)
static kib_tx_t * kiblnd_find_waiting_tx_locked (kib_conn_t *conn, int txtype, __u64 cookie)
static void kiblnd_handle_completion (kib_conn_t *conn, int txtype, int status, __u64 cookie)
static void kiblnd_send_completion (kib_conn_t *conn, int type, int status, __u64 cookie)
static void kiblnd_handle_rx (kib_rx_t *rx)
static void kiblnd_rx_complete (kib_rx_t *rx, int status, int nob)
static struct page * kiblnd_kvaddr_to_page (unsigned long vaddr)
static int kiblnd_fmr_map_tx (kib_net_t *net, kib_tx_t *tx, kib_rdma_desc_t *rd, __u32 nob)
static int kiblnd_map_tx (lnet_ni_t *ni, kib_tx_t *tx, kib_rdma_desc_t *rd, int nfrags)
static int kiblnd_setup_rd_iov (lnet_ni_t *ni, kib_tx_t *tx, kib_rdma_desc_t *rd, unsigned int niov, struct kvec *iov, int offset, int nob)
static int kiblnd_setup_rd_kiov (lnet_ni_t *ni, kib_tx_t *tx, kib_rdma_desc_t *rd, int nkiov, lnet_kiov_t *kiov, int offset, int nob)
static int kiblnd_post_tx_locked (kib_conn_t *conn, kib_tx_t *tx, int credit) __must_hold(&conn->ibc_lock)
static void kiblnd_tx_complete (kib_tx_t *tx, int status)
static int kiblnd_resolve_addr (struct rdma_cm_id *cmid, struct sockaddr_in *srcaddr, struct sockaddr_in *dstaddr, int timeout_ms)
static void kiblnd_connect_peer (kib_peer_t *peer)
bool kiblnd_reconnect_peer (kib_peer_t *peer)
void kiblnd_launch_tx (lnet_ni_t *ni, kib_tx_t *tx, lnet_nid_t nid)
int kiblnd_send (lnet_ni_t *ni, void *private, lnet_msg_t *lntmsg)
static void kiblnd_reply (lnet_ni_t *ni, kib_rx_t *rx, lnet_msg_t *lntmsg)
int kiblnd_recv (lnet_ni_t *ni, void *private, lnet_msg_t *lntmsg, int delayed, unsigned int niov, struct kvec *iov, lnet_kiov_t *kiov, unsigned int offset, unsigned int mlen, unsigned int rlen)
int kiblnd_thread_start (int(*fn)(void *arg), void *arg, char *name)
static void kiblnd_thread_fini (void)
static void kiblnd_peer_notify (kib_peer_t *peer)
void kiblnd_close_conn_locked (kib_conn_t *conn, int error)
void kiblnd_close_conn (kib_conn_t *conn, int error)
static void kiblnd_handle_early_rxs (kib_conn_t *conn)
static void kiblnd_abort_txs (kib_conn_t *conn, struct list_head *txs)
static void kiblnd_finalise_conn (kib_conn_t *conn)
static void kiblnd_connreq_done (kib_conn_t *conn, int status)
static void kiblnd_reject (struct rdma_cm_id *cmid, kib_rej_t *rej)
static int kiblnd_passive_connect (struct rdma_cm_id *cmid, void *priv, int priv_nob)
static void kiblnd_check_reconnect (kib_conn_t *conn, int version, __u64 incarnation, int why, kib_connparams_t *cp)
static void kiblnd_rejected (kib_conn_t *conn, int reason, void *priv, int priv_nob)
static void kiblnd_check_connreply (kib_conn_t *conn, void *priv, int priv_nob)
static int kiblnd_active_connect (struct rdma_cm_id *cmid)
int kiblnd_cm_callback (struct rdma_cm_id *cmid, struct rdma_cm_event *event)
static int kiblnd_check_txs_locked (kib_conn_t *conn, struct list_head *txs)
static int kiblnd_conn_timed_out_locked (kib_conn_t *conn)
static void kiblnd_check_conns (int idx)
static void kiblnd_disconnect_conn (kib_conn_t *conn)
int kiblnd_connd (void *arg)
void kiblnd_qp_event (struct ib_event *event, void *arg)
static void kiblnd_complete (struct ib_wc *wc)
void kiblnd_cq_completion (struct ib_cq *cq, void *arg)
void kiblnd_cq_event (struct ib_event *event, void *arg)
int kiblnd_scheduler (void *arg)
int kiblnd_failover_thread (void *arg)
Define Documentation
#define KIB_RECONN_BREAK 100
Definition at line 3241 of file o2iblnd_cb.c.
Referenced by kiblnd_connd().
#define KIB_RECONN_HIGH_RACE 10
Definition at line 3236 of file o2iblnd_cb.c.
Referenced by kiblnd_connd().
Function Documentation
static void kiblnd_abort_txs (kib_conn_t * conn, struct list_head * txs) [static]
Definition at line 1987 of file o2iblnd_cb.c.
References kib_conn::ibc_active_txs, kib_conn::ibc_lock, kib_conn::ibc_peer, kib_peer::ibp_ni, kiblnd_txlist_done(), LASSERT, list_add(), list_del(), list_entry, list_for_each_safe, LIST_HEAD_INIT, kib_tx::tx_list, kib_tx::tx_queued, kib_tx::tx_sending, kib_tx::tx_status, and kib_tx::tx_waiting.
Referenced by kiblnd_finalise_conn().
static int kiblnd_active_connect (struct rdma_cm_id * cmid) [static]
Definition at line 2865 of file o2iblnd_cb.c.
References __u64, CERROR, IBLND_CONN_ACTIVE_CONNECT, IBLND_MSG_CONNREQ, IBLND_MSG_SIZE, IBLND_MSG_VERSION, kib_peer::ibp_incarnation, kib_peer::ibp_ni, kib_peer::ibp_nid, kib_peer::ibp_version, kib_data_t::kib_global_lock, kib_tunables_t::kib_retry_count, kib_tunables_t::kib_rnr_retry_count, kiblnd_conn_decref, kiblnd_connreq_done(), kiblnd_create_conn(), kiblnd_data, kiblnd_init_msg(), kiblnd_pack_msg(), kiblnd_peer_connect_failed(), kiblnd_peer_decref, kiblnd_tunables, LASSERT, libcfs_nid2str(), msg, and version.
Referenced by kiblnd_cm_callback().
static void kiblnd_check_connreply (kib_conn_t * conn, void * priv, int priv_nob) [static]
Definition at line 2764 of file o2iblnd_cb.c.
References CERROR, kib_conn::ibc_comms_error, kib_conn::ibc_credits, kib_conn::ibc_incarnation, kib_conn::ibc_max_frags, kib_conn::ibc_peer, kib_conn::ibc_queue_depth, kib_conn::ibc_reserved_credits, kib_conn::ibc_version, IBLND_MSG_CONNACK, IBLND_MSG_SIZE, IBLND_OOB_MSGS, IBLND_RX_MSGS, kib_net::ibn_incarnation, kib_peer::ibp_ni, kib_peer::ibp_nid, kib_data_t::kib_global_lock, kiblnd_connreq_done(), kiblnd_data, kiblnd_unpack_msg(), LASSERT, libcfs_nid2str(), msg, lnet_ni::ni_data, and lnet_ni::ni_nid.
Referenced by kiblnd_cm_callback().
static void kiblnd_check_conns (int idx) [static]
Definition at line 3138 of file o2iblnd_cb.c.
References CERROR, cfs_duration_sec(), cfs_time_current(), kib_conn::ibc_connd_list, kib_conn::ibc_credits, kib_conn::ibc_lock, kib_conn::ibc_outstanding_credits, kib_conn::ibc_reserved_credits, kib_conn::ibc_state, IBLND_CONN_ESTABLISHED, kib_peer::ibp_conns, kib_peer::ibp_last_alive, kib_peer::ibp_nid, kib_data_t::kib_global_lock, kib_data_t::kib_peers, kiblnd_check_sends(), kiblnd_close_conn(), kiblnd_conn_addref, kiblnd_conn_decref, kiblnd_conn_timed_out_locked(), kiblnd_data, kiblnd_need_noop(), LASSERT, libcfs_nid2str(), list_add(), list_del(), list_empty(), list_entry, list_for_each, LIST_HEAD_INIT, and list_head::next.
Referenced by kiblnd_connd().
static void kiblnd_check_reconnect (kib_conn_t * conn, int version, __u64 incarnation, int why, kib_connparams_t * cp) [static]
Definition at line 2528 of file o2iblnd_cb.c.
References CNETERR, kib_conn::ibc_max_frags, kib_conn::ibc_peer, kib_conn::ibc_queue_depth, kib_conn::ibc_reconnect, kib_conn::ibc_state, kib_connparams::ibcp_max_frags, kib_connparams::ibcp_max_msg_size, kib_connparams::ibcp_queue_depth, IBLND_CONN_ACTIVE_CONNECT, IBLND_MSG_SIZE, IBLND_MSG_VERSION, IBLND_REJECT_CONN_RACE, IBLND_REJECT_CONN_STALE, IBLND_REJECT_CONN_UNCOMPAT, IBLND_REJECT_MSG_QUEUE_SIZE, IBLND_REJECT_RDMA_FRAGS, kib_peer::ibp_accepting, kib_peer::ibp_connecting, kib_peer::ibp_incarnation, kib_peer::ibp_max_frags, kib_peer::ibp_ni, kib_peer::ibp_nid, kib_peer::ibp_queue_depth, kib_peer::ibp_reconnecting, kib_peer::ibp_tx_queue, kib_peer::ibp_version, kib_data_t::kib_global_lock, kiblnd_data, LASSERT, libcfs_nid2str(), list_empty(), lnet_ioctl_config_o2iblnd_tunables::lnd_map_on_demand, lnet_ioctl_config_lnd_tunables::lt_o2ib, lnet_ioctl_config_lnd_tunables::lt_tun_u, and lnet_ni::ni_lnd_tunables.
Referenced by kiblnd_rejected().
static void kiblnd_check_sends (kib_conn_t * conn) [static]
Definition at line 900 of file o2iblnd_cb.c.
References CDEBUG, D_NET, kib_conn::ibc_lock, kib_conn::ibc_noops_posted, kib_conn::ibc_nsends_posted, kib_conn::ibc_peer, kib_conn::ibc_reserved_credits, kib_conn::ibc_state, kib_conn::ibc_tx_noops, kib_conn::ibc_tx_queue, kib_conn::ibc_tx_queue_nocred, kib_conn::ibc_tx_queue_rsrvd, kib_conn::ibc_version, IBLND_CONN_ESTABLISHED, IBLND_MSG_NOOP, IBLND_OOB_CAPABLE, IBLND_OOB_MSGS, kib_peer::ibp_ni, kib_peer::ibp_nid, kiblnd_concurrent_sends(), kiblnd_get_idle_tx(), kiblnd_init_tx_msg(), kiblnd_need_noop(), kiblnd_post_tx_locked(), kiblnd_queue_tx_locked(), LASSERT, libcfs_nid2str(), list_add_tail(), list_del(), list_empty(), list_entry, list_head::next, and kib_tx::tx_list.
Referenced by kiblnd_check_conns(), kiblnd_connreq_done(), kiblnd_handle_rx(), kiblnd_post_rx(), kiblnd_queue_tx(), and kiblnd_tx_complete().
static int kiblnd_check_txs_locked (kib_conn_t * conn, struct list_head * txs) [static]
Definition at line 3101 of file o2iblnd_cb.c.
References CERROR, cfs_duration_sec(), cfs_time_aftereq(), kib_conn::ibc_active_txs, kiblnd_queue2str(), LASSERT, list_entry, list_for_each, kib_tx::tx_deadline, kib_tx::tx_queued, kib_tx::tx_sending, and kib_tx::tx_waiting.
Referenced by kiblnd_conn_timed_out_locked().
void kiblnd_close_conn (kib_conn_t * conn, int error)
Definition at line 1952 of file o2iblnd_cb.c.
References kib_data_t::kib_global_lock, kiblnd_close_conn_locked(), and kiblnd_data.
Referenced by kiblnd_check_conns(), kiblnd_cm_callback(), kiblnd_handle_completion(), kiblnd_handle_rx(), kiblnd_post_rx(), kiblnd_post_tx_locked(), kiblnd_rx_complete(), kiblnd_scheduler(), and kiblnd_tx_complete().
void kiblnd_close_conn_locked (kib_conn_t * conn, int error)
Definition at line 1882 of file o2iblnd_cb.c.
References CDEBUG, CNETERR, D_NET, kib_conn::ibc_active_txs, kib_conn::ibc_comms_error, kib_conn::ibc_list, kib_conn::ibc_peer, kib_conn::ibc_state, kib_conn::ibc_tx_noops, kib_conn::ibc_tx_queue, kib_conn::ibc_tx_queue_nocred, kib_conn::ibc_tx_queue_rsrvd, kib_dev_t::ibd_fail_list, IBLND_CONN_CLOSING, IBLND_CONN_ESTABLISHED, kib_peer::ibp_conns, kib_peer::ibp_error, kib_peer::ibp_ni, kib_peer::ibp_nid, kib_data_t::kib_connd_conns, kib_data_t::kib_connd_lock, kib_data_t::kib_connd_waitq, kib_data_t::kib_failed_devs, kib_data_t::kib_failover_waitq, kiblnd_data, kiblnd_dev_can_failover(), kiblnd_peer_active(), kiblnd_set_conn_state(), kiblnd_unlink_peer_locked(), LASSERT, libcfs_nid2str(), list_add_tail(), list_del(), list_empty(), and lnet_ni::ni_data.
Referenced by kiblnd_close_conn(), kiblnd_close_peer_conns_locked(), kiblnd_close_stale_conns_locked(), kiblnd_connreq_done(), and kiblnd_del_peer_locked().
int kiblnd_cm_callback (struct rdma_cm_id * cmid, struct rdma_cm_event * event)
Definition at line 2931 of file o2iblnd_cb.c.
References CDEBUG, CERROR, CNETERR, D_NET, kib_conn::ibc_peer, kib_conn::ibc_state, IBLND_CONN_ACTIVE_CONNECT, IBLND_CONN_ESTABLISHED, IBLND_CONN_PASSIVE_WAIT, kib_peer::ibp_nid, kib_tunables_t::kib_timeout, kiblnd_active_connect(), kiblnd_check_connreply(), kiblnd_close_conn(), kiblnd_conn_decref, KIBLND_CONN_PARAM, KIBLND_CONN_PARAM_LEN, kiblnd_connreq_done(), kiblnd_passive_connect(), kiblnd_peer_connect_failed(), kiblnd_peer_decref, kiblnd_rejected(), kiblnd_tunables, LASSERT, LBUG, LCONSOLE_ERROR_MSG, LCONSOLE_INFO, and libcfs_nid2str().
Referenced by kiblnd_connect_peer(), and kiblnd_dev_failover().
static void kiblnd_complete (struct ib_wc * wc) [static]
Definition at line 3409 of file o2iblnd_cb.c.
References CNETERR, IBLND_WID_MR, IBLND_WID_RDMA, IBLND_WID_RX, IBLND_WID_TX, kiblnd_rx_complete(), kiblnd_tx_complete(), kiblnd_wreqid2ptr(), kiblnd_wreqid2type(), and LBUG.
Referenced by kiblnd_scheduler().
static int kiblnd_conn_timed_out_locked (kib_conn_t * conn) [static]
Definition at line 3128 of file o2iblnd_cb.c.
References kib_conn::ibc_active_txs, kib_conn::ibc_tx_noops, kib_conn::ibc_tx_queue, kib_conn::ibc_tx_queue_nocred, kib_conn::ibc_tx_queue_rsrvd, and kiblnd_check_txs_locked().
Referenced by kiblnd_check_conns().
int kiblnd_connd (void * arg)
Definition at line 3244 of file o2iblnd_cb.c.
References cfs_block_allsigs(), kib_conn::ibc_list, kib_conn::ibc_peer, kib_conn::ibc_reconnect, kib_peer::ibp_reconnected, kib_data_t::kib_connd, kib_data_t::kib_connd_conns, kib_data_t::kib_connd_lock, kib_data_t::kib_connd_waitq, kib_data_t::kib_connd_zombies, kib_data_t::kib_peer_hash_size, KIB_RECONN_BREAK, KIB_RECONN_HIGH_RACE, kib_data_t::kib_reconn_list, kib_data_t::kib_reconn_sec, kib_data_t::kib_reconn_wait, kib_data_t::kib_shutdown, kib_tunables_t::kib_timeout, kiblnd_check_conns(), kiblnd_conn_decref, kiblnd_data, kiblnd_destroy_conn(), kiblnd_disconnect_conn(), kiblnd_peer_addref, kiblnd_peer_decref, kiblnd_reconnect_peer(), kiblnd_thread_fini(), kiblnd_tunables, LIBCFS_FREE, list_add_tail(), list_del(), list_empty(), list_entry, list_splice_init(), list_head::next, and timeout.
Referenced by kiblnd_base_startup().
static void kiblnd_connect_peer (kib_peer_t * peer) [static]
Definition at line 1249 of file o2iblnd_cb.c.
References CDEBUG, CERROR, D_NET, kib_dev_t::ibd_ifip, kib_dev_t::ibd_ifname, kib_net::ibn_dev, kib_peer::ibp_connecting, kib_peer::ibp_ni, kib_peer::ibp_nid, kib_peer::ibp_reconnecting, kib_tunables_t::kib_service, kib_tunables_t::kib_timeout, kib_tunables_t::kib_use_priv_port, kiblnd_cm_callback(), kiblnd_peer_addref, kiblnd_peer_connect_failed(), kiblnd_peer_decref, kiblnd_rdma_create_id, kiblnd_resolve_addr(), kiblnd_tunables, LASSERT, libcfs_nid2str(), LNET_NIDADDR(), and lnet_ni::ni_data.
Referenced by kiblnd_launch_tx(), and kiblnd_reconnect_peer().
static void kiblnd_connreq_done (kib_conn_t * conn, int status) [static]
Definition at line 2102 of file o2iblnd_cb.c.
References CDEBUG, D_NET, kib_conn::ibc_comms_error, kib_conn::ibc_connvars, kib_conn::ibc_incarnation, kib_conn::ibc_last_send, kib_conn::ibc_list, kib_conn::ibc_lock, kib_conn::ibc_peer, kib_conn::ibc_state, kib_conn::ibc_version, IBLND_CONN_ACTIVE_CONNECT, IBLND_CONN_ESTABLISHED, IBLND_CONN_PASSIVE_WAIT, kib_peer::ibp_accepting, kib_peer::ibp_connecting, kib_peer::ibp_conns, kib_peer::ibp_incarnation, kib_peer::ibp_ni, kib_peer::ibp_nid, kib_peer::ibp_reconnected, kib_peer::ibp_tx_queue, kib_peer::ibp_version, kib_data_t::kib_global_lock, kiblnd_check_sends(), kiblnd_close_conn_locked(), kiblnd_close_stale_conns_locked(), kiblnd_conn_addref, kiblnd_conn_decref, kiblnd_data, kiblnd_finalise_conn(), kiblnd_handle_early_rxs(), kiblnd_peer_active(), kiblnd_peer_alive(), kiblnd_peer_connect_failed(), kiblnd_queue_tx_locked(), kiblnd_set_conn_state(), kiblnd_txlist_done(), LASSERT, LIBCFS_FREE, libcfs_nid2str(), list_add(), list_del(), list_del_init(), list_empty(), list_entry, list_head::next, and kib_tx::tx_list.
Referenced by kiblnd_active_connect(), kiblnd_check_connreply(), kiblnd_cm_callback(), kiblnd_passive_connect(), and kiblnd_rejected().
void kiblnd_cq_completion (struct ib_cq * cq, void * arg)
Definition at line 3444 of file o2iblnd_cb.c.
References kib_conn::ibc_cq, kib_conn::ibc_nrx, kib_conn::ibc_nsends_posted, kib_conn::ibc_ready, kib_conn::ibc_sched, kib_conn::ibc_sched_list, kib_conn::ibc_scheduled, kib_sched_info::ibs_conns, kib_sched_info::ibs_lock, kib_sched_info::ibs_waitq, kiblnd_conn_addref, LASSERT, and list_add_tail().
Referenced by kiblnd_create_conn().
void kiblnd_cq_event (struct ib_event * event, void * arg)
Definition at line 3476 of file o2iblnd_cb.c.
References CERROR, kib_conn::ibc_peer, kib_peer::ibp_nid, and libcfs_nid2str().
Referenced by kiblnd_create_conn().
static void kiblnd_disconnect_conn (kib_conn_t * conn) [static]
Definition at line 3220 of file o2iblnd_cb.c.
References kib_conn::ibc_cmid, kib_conn::ibc_peer, kib_conn::ibc_state, IBLND_CONN_CLOSING, kib_data_t::kib_connd, kiblnd_data, kiblnd_finalise_conn(), kiblnd_peer_notify(), and LASSERT.
Referenced by kiblnd_connd().
static void kiblnd_drop_rx (kib_rx_t * rx) [static]
Definition at line 141 of file o2iblnd_cb.c.
References kib_conn::ibc_nrx, kib_conn::ibc_sched, kib_sched_info::ibs_lock, kiblnd_conn_decref, LASSERT, and kib_rx::rx_conn.
Referenced by kiblnd_post_rx(), and kiblnd_rx_complete().
int kiblnd_failover_thread (void * arg)
Definition at line 3628 of file o2iblnd_cb.c.
References cfs_block_allsigs(), cfs_time_before(), cfs_time_current(), cfs_time_seconds(), cfs_time_shift(), kib_dev_t::ibd_fail_list, kib_dev_t::ibd_failed_failover, kib_dev_t::ibd_failover, kib_dev_t::ibd_next_failover, kib_tunables_t::kib_dev_failover, kib_data_t::kib_devs, kib_data_t::kib_failed_devs, kib_data_t::kib_failover_waitq, kib_data_t::kib_global_lock, kib_data_t::kib_shutdown, kiblnd_data, kiblnd_dev_can_failover(), kiblnd_dev_failover(), kiblnd_thread_fini(), kiblnd_tunables, LASSERT, list_add_tail(), list_del_init(), list_empty(), and list_for_each_entry.
Referenced by kiblnd_base_startup().
static void kiblnd_finalise_conn (kib_conn_t * conn) [static]
Definition at line 2023 of file o2iblnd_cb.c.
References kib_conn::ibc_active_txs, kib_conn::ibc_state, kib_conn::ibc_tx_noops, kib_conn::ibc_tx_queue, kib_conn::ibc_tx_queue_nocred, kib_conn::ibc_tx_queue_rsrvd, IBLND_CONN_DISCONNECTED, IBLND_CONN_INIT, kiblnd_abort_receives(), kiblnd_abort_txs(), kiblnd_handle_early_rxs(), kiblnd_set_conn_state(), and LASSERT.
Referenced by kiblnd_connreq_done(), and kiblnd_disconnect_conn().
static kib_tx_t* kiblnd_find_waiting_tx_locked (kib_conn_t * conn, int txtype, __u64 cookie) [static]
Definition at line 227 of file o2iblnd_cb.c.
References CWARN, kib_conn::ibc_active_txs, LASSERT, list_entry, list_for_each, kib_tx::tx_cookie, kib_tx::tx_msg, kib_tx::tx_queued, kib_tx::tx_sending, and kib_tx::tx_waiting.
Referenced by kiblnd_handle_completion(), and kiblnd_handle_rx().
static int kiblnd_fmr_map_tx (kib_net_t * net, kib_tx_t * tx, kib_rdma_desc_t * rd, __u32 nob) [static]
Definition at line 565 of file o2iblnd_cb.c.
References CERROR, kib_tx::fmr, kib_fmr_t::fmr_key, kib_hca_dev::ibh_page_mask, kib_net::ibn_fmr_ps, kiblnd_fmr_pool_map(), LASSERT, kib_pool::po_owner, kib_poolset::ps_cpt, kib_tx_pool_t::tpo_hdev, kib_tx_pool_t::tpo_pool, and kib_tx::tx_pool.
Referenced by kiblnd_map_tx().
static kib_tx_t* kiblnd_get_idle_tx (lnet_ni_t * ni, lnet_nid_t target) [static]
Definition at line 114 of file o2iblnd_cb.c.
References kib_net::ibn_tx_ps, kiblnd_pool_alloc_node(), LASSERT, lnet_cpt_of_nid(), and lnet_ni::ni_data.
Referenced by kiblnd_check_sends(), kiblnd_recv(), kiblnd_reply(), kiblnd_send(), and kiblnd_send_completion().
static void kiblnd_handle_completion (kib_conn_t * conn, int txtype, int status, __u64 cookie) [static]
Definition at line 252 of file o2iblnd_cb.c.
References CWARN, kib_conn::ibc_lock, kib_conn::ibc_peer, IBLND_MSG_GET_REQ, kib_peer::ibp_ni, kib_peer::ibp_nid, kiblnd_close_conn(), kiblnd_find_waiting_tx_locked(), kiblnd_tx_done(), libcfs_nid2str(), list_del(), lnet_set_reply_msg_len(), LPX64, kib_tx::tx_list, kib_tx::tx_lntmsg, kib_tx::tx_queued, kib_tx::tx_sending, kib_tx::tx_status, and kib_tx::tx_waiting.
Referenced by kiblnd_handle_rx().
static void kiblnd_handle_early_rxs (kib_conn_t * conn) [static]
Definition at line 1964 of file o2iblnd_cb.c.
References kib_conn::ibc_early_rxs, kib_conn::ibc_state, IBLND_CONN_ESTABLISHED, kib_data_t::kib_global_lock, kiblnd_data, kiblnd_handle_rx(), LASSERT, list_del(), list_empty(), list_entry, list_head::next, and kib_rx::rx_list.
Referenced by kiblnd_connreq_done(), and kiblnd_finalise_conn().
static void kiblnd_handle_rx (kib_rx_t * rx) [static]
Definition at line 310 of file o2iblnd_cb.c.
References CDEBUG, CERROR, credits, CWARN, D_NET, kib_conn::ibc_credits, kib_conn::ibc_lock, kib_conn::ibc_outstanding_credits, kib_conn::ibc_peer, kib_conn::ibc_queue_depth, kib_conn::ibc_state, kib_conn::ibc_version, IBLND_CONN_ESTABLISHED, IBLND_MSG_GET_DONE, IBLND_MSG_GET_REQ, IBLND_MSG_IMMEDIATE, IBLND_MSG_NOOP, IBLND_MSG_PUT_ACK, IBLND_MSG_PUT_DONE, IBLND_MSG_PUT_NAK, IBLND_MSG_PUT_REQ, IBLND_OOB_CAPABLE, IBLND_POSTRX_DONT_POST, IBLND_POSTRX_NO_CREDIT, IBLND_POSTRX_PEER_CREDIT, IBLND_POSTRX_RSRVD_CREDIT, kib_peer::ibp_ni, kib_peer::ibp_nid, kiblnd_check_sends(), kiblnd_close_conn(), kiblnd_find_waiting_tx_locked(), kiblnd_handle_completion(), kiblnd_init_rdma(), kiblnd_post_rx(), kiblnd_queue_tx_locked(), kiblnd_rd_size(), LASSERT, libcfs_nid2str(), list_del(), lnet_parse(), msg, kib_rx::rx_conn, kib_rx::rx_msg, kib_tx::tx_list, kib_tx::tx_nwrq, and kib_tx::tx_waiting.
Referenced by kiblnd_handle_early_rxs(), and kiblnd_rx_complete().
static int kiblnd_init_rdma (kib_conn_t * conn, kib_tx_t * tx, int type, int resid, kib_rdma_desc_t * dstrd, __u64 dstcookie) [static]
Definition at line 1057 of file o2iblnd_cb.c.
References CERROR, kib_conn::ibc_max_frags, kib_conn::ibc_peer, IBLND_MSG_GET_DONE, IBLND_MSG_PUT_DONE, IBLND_WID_RDMA, kib_peer::ibp_ni, kib_peer::ibp_nid, kiblnd_init_tx_msg(), kiblnd_ptr2wreqid(), kiblnd_rd_consume_frag(), kiblnd_rd_frag_addr(), kiblnd_rd_frag_key(), kiblnd_rd_frag_size(), LASSERT, libcfs_nid2str(), MIN, kib_tx::tx_msg, kib_tx::tx_nwrq, kib_tx::tx_rd, kib_tx::tx_sge, kib_tx::tx_wrq, and ib_rdma_wr::wr.
Referenced by kiblnd_handle_rx(), and kiblnd_reply().
static void kiblnd_init_tx_msg (lnet_ni_t * ni, kib_tx_t * tx, int type, int body_nob) [static]
Definition at line 1024 of file o2iblnd_cb.c.
References kib_hca_dev::ibh_mrs, IBLND_MAX_RDMA_FRAGS, IBLND_MSG_SIZE, IBLND_WID_TX, kiblnd_init_msg(), kiblnd_ptr2wreqid(), LASSERT, offsetof, kib_tx_pool_t::tpo_hdev, kib_tx::tx_msg, kib_tx::tx_msgaddr, kib_tx::tx_nwrq, kib_tx::tx_pool, kib_tx::tx_sge, kib_tx::tx_wrq, and ib_rdma_wr::wr.
Referenced by kiblnd_check_sends(), kiblnd_init_rdma(), kiblnd_recv(), kiblnd_send(), and kiblnd_send_completion().
static struct page* kiblnd_kvaddr_to_page (unsigned long vaddr) [static, read]
Definition at line 542 of file o2iblnd_cb.c.
References CERROR, LASSERT, and LBUG.
Referenced by kiblnd_setup_rd_iov().
void kiblnd_launch_tx (lnet_ni_t * ni, kib_tx_t * tx, lnet_nid_t nid)
Definition at line 1367 of file o2iblnd_cb.c.
References CERROR, kib_peer::ibp_connecting, kib_peer::ibp_conns, kib_peer::ibp_list, kib_peer::ibp_tx_queue, kib_data_t::kib_global_lock, kiblnd_conn_addref, kiblnd_conn_decref, kiblnd_connect_peer(), kiblnd_create_peer(), kiblnd_data, kiblnd_find_peer_locked(), kiblnd_get_conn_locked(), kiblnd_nid2peerlist(), kiblnd_peer_addref, kiblnd_peer_connecting(), kiblnd_peer_decref, kiblnd_queue_tx(), kiblnd_tx_done(), LASSERT, libcfs_nid2str(), list_add_tail(), list_empty(), lnet_ni::ni_data, kib_tx::tx_conn, kib_tx::tx_list, kib_tx::tx_nwrq, kib_tx::tx_status, and kib_tx::tx_waiting.
Referenced by kiblnd_query(), and kiblnd_send().
static int kiblnd_map_tx (lnet_ni_t * ni, kib_tx_t * tx, kib_rdma_desc_t * rd, int nfrags) [static]
Definition at line 613 of file o2iblnd_cb.c.
References kib_conn::ibc_max_frags, kib_dev_t::ibd_hdev, kib_hca_dev::ibh_ibdev, kib_net::ibn_dev, kib_net::ibn_fmr_ps, kiblnd_dma_map_sg(), kiblnd_find_rd_dma_mr(), kiblnd_fmr_map_tx(), kiblnd_sg_dma_address(), kiblnd_sg_dma_len(), lnet_ni::ni_data, kib_tx::tx_conn, kib_tx::tx_dmadir, kib_tx::tx_frags, kib_tx::tx_nfrags, and kib_tx::tx_rd.
Referenced by kiblnd_setup_rd_iov(), and kiblnd_setup_rd_kiov().
static int kiblnd_passive_connect (struct rdma_cm_id * cmid, void * priv, int priv_nob) [static]
Definition at line 2220 of file o2iblnd_cb.c.
References __swab16, __swab32, CDEBUG, CERROR, kib_connvars::cv_msg, CWARN, D_NET, kib_conn::ibc_connvars, kib_conn::ibc_credits, kib_conn::ibc_incarnation, kib_conn::ibc_max_frags, kib_conn::ibc_queue_depth, kib_conn::ibc_reserved_credits, kib_dev_t::ibd_ifip, kib_dev_t::ibd_ifname, kib_dev_t::ibd_nnets, IBLND_CONN_PASSIVE_WAIT, IBLND_MSG_CONNACK, IBLND_MSG_CONNREQ, IBLND_MSG_MAGIC, IBLND_MSG_SIZE, IBLND_MSG_VERSION, IBLND_MSG_VERSION_1, IBLND_OOB_MSGS, IBLND_REJECT_CONN_RACE, IBLND_REJECT_CONN_STALE, IBLND_REJECT_FATAL, IBLND_REJECT_MSG_QUEUE_SIZE, IBLND_REJECT_NO_RESOURCES, IBLND_REJECT_RDMA_FRAGS, IBLND_RX_MSGS, kib_net::ibn_dev, kib_net::ibn_fmr_ps, kib_net::ibn_incarnation, kib_net::ibn_shutdown, kib_peer::ibp_accepting, kib_peer::ibp_connecting, kib_peer::ibp_incarnation, kib_peer::ibp_list, kib_peer::ibp_max_frags, kib_peer::ibp_nid, kib_peer::ibp_queue_depth, kib_peer::ibp_reconnecting, kib_peer::ibp_version, kib_data_t::kib_global_lock, kib_tunables_t::kib_require_priv_port, kib_tunables_t::kib_retry_count, kib_tunables_t::kib_rnr_retry_count, kiblnd_close_peer_conns_locked(), kiblnd_conn_decref, kiblnd_connreq_done(), kiblnd_create_conn(), kiblnd_create_peer(), kiblnd_data, kiblnd_find_peer_locked(), kiblnd_init_msg(), kiblnd_msg_queue_size(), kiblnd_nid2peerlist(), kiblnd_pack_msg(), kiblnd_peer_active(), kiblnd_peer_addref, kiblnd_peer_connect_failed(), kiblnd_peer_decref, kiblnd_rdma_frags(), kiblnd_reject(), kiblnd_tunables, kiblnd_unpack_msg(), LASSERT, libcfs_nid2str(), list_add_tail(), lnet_net2ni(), lnet_ni_decref(), LNET_NIDNET(), LNET_PROTO_MAGIC, LPU64, lnet_ni::ni_data, lnet_ni::ni_nid, offsetof, and version.
Referenced by kiblnd_cm_callback().
static void kiblnd_peer_alive (kib_peer_t * peer) [static]
Definition at line 1851 of file o2iblnd_cb.c.
References cfs_time_current(), and kib_peer::ibp_last_alive.
Referenced by kiblnd_connreq_done(), kiblnd_rx_complete(), and kiblnd_tx_complete().
static void kiblnd_peer_connect_failed (kib_peer_t * peer, int active, int error) [static]
Definition at line 2048 of file o2iblnd_cb.c.
References CNETERR, kib_peer::ibp_accepting, kib_peer::ibp_connecting, kib_peer::ibp_conns, kib_peer::ibp_error, kib_peer::ibp_ni, kib_peer::ibp_nid, kib_peer::ibp_reconnected, kib_peer::ibp_tx_queue, kib_data_t::kib_global_lock, kiblnd_data, kiblnd_peer_active(), kiblnd_peer_connecting(), kiblnd_peer_notify(), kiblnd_txlist_done(), kiblnd_unlink_peer_locked(), LASSERT, libcfs_nid2str(), list_add(), list_del_init(), list_empty(), and LIST_HEAD_INIT.
Referenced by kiblnd_active_connect(), kiblnd_cm_callback(), kiblnd_connect_peer(), kiblnd_connreq_done(), and kiblnd_passive_connect().
static void kiblnd_peer_notify (kib_peer_t * peer) [static]
Definition at line 1859 of file o2iblnd_cb.c.
References error, kib_peer::ibp_error, kib_peer::ibp_last_alive, kib_peer::ibp_ni, kib_peer::ibp_nid, kib_data_t::kib_global_lock, kiblnd_data, kiblnd_peer_idle(), and lnet_notify().
Referenced by kiblnd_disconnect_conn(), and kiblnd_peer_connect_failed().
int kiblnd_post_rx (kib_rx_t * rx, int credit)
Definition at line 156 of file o2iblnd_cb.c.
References CERROR, kib_conn::ibc_cmid, kib_conn::ibc_hdev, kib_conn::ibc_lock, kib_conn::ibc_outstanding_credits, kib_conn::ibc_peer, kib_conn::ibc_reserved_credits, kib_conn::ibc_state, kib_hca_dev::ibh_mrs, IBLND_CONN_ESTABLISHED, IBLND_CONN_INIT, IBLND_MSG_SIZE, IBLND_POSTRX_NO_CREDIT, IBLND_POSTRX_PEER_CREDIT, IBLND_POSTRX_RSRVD_CREDIT, IBLND_WID_RX, kib_peer::ibp_ni, kib_peer::ibp_nid, kiblnd_check_sends(), kiblnd_close_conn(), kiblnd_conn_addref, kiblnd_conn_decref, kiblnd_drop_rx(), kiblnd_ptr2wreqid(), LASSERT, libcfs_nid2str(), lnet_ni::ni_data, kib_rx::rx_conn, kib_rx::rx_msgaddr, kib_rx::rx_nob, kib_rx::rx_sge, kib_rx::rx_wrq, and unlikely.
Referenced by kiblnd_create_conn(), kiblnd_handle_rx(), and kiblnd_recv().
static int kiblnd_post_tx_locked (kib_conn_t * conn, kib_tx_t * tx, int credit) [static]
Definition at line 747 of file o2iblnd_cb.c.
References CDEBUG, CERROR, D_NET, done, kib_fast_reg_descriptor::frd_fastreg_wr, kib_fast_reg_descriptor::frd_inv_wr, kib_fast_reg_descriptor::frd_valid, IBLND_CONN_ESTABLISHED, IBLND_MSG_NOOP, IBLND_OOB_CAPABLE, IBLND_OOB_MSGS, IBLND_WID_TX, kib_peer::ibp_ni, kib_peer::ibp_nid, kiblnd_close_conn(), kiblnd_concurrent_sends(), kiblnd_need_noop(), kiblnd_pack_msg(), kiblnd_ptr2wreqid(), kiblnd_tx_done(), LASSERT, LASSERTF, libcfs_nid2str(), list_add(), list_del(), LPX64, msg, and ib_rdma_wr::wr.
Referenced by kiblnd_check_sends().
void kiblnd_qp_event (struct ib_event * event, void * arg)
Definition at line 3391 of file o2iblnd_cb.c.
References CDEBUG, CERROR, D_NET, kib_conn::ibc_peer, kib_peer::ibp_nid, and libcfs_nid2str().
Referenced by kiblnd_create_conn().
static void kiblnd_queue_tx (kib_tx_t * tx, kib_conn_t * conn) [static]
Definition at line 1202 of file o2iblnd_cb.c.
References kib_conn::ibc_lock, kiblnd_check_sends(), and kiblnd_queue_tx_locked().
Referenced by kiblnd_launch_tx(), kiblnd_recv(), kiblnd_reply(), and kiblnd_send_completion().
static void kiblnd_queue_tx_locked (kib_tx_t * tx, kib_conn_t * conn) [static]
Definition at line 1147 of file o2iblnd_cb.c.
References kib_conn::ibc_state, kib_conn::ibc_tx_noops, kib_conn::ibc_tx_queue, kib_conn::ibc_tx_queue_nocred, kib_conn::ibc_tx_queue_rsrvd, kib_conn::ibc_version, IBLND_CONN_ESTABLISHED, IBLND_MSG_GET_DONE, IBLND_MSG_GET_REQ, IBLND_MSG_IMMEDIATE, IBLND_MSG_NOOP, IBLND_MSG_PUT_ACK, IBLND_MSG_PUT_DONE, IBLND_MSG_PUT_NAK, IBLND_MSG_PUT_REQ, IBLND_OOB_CAPABLE, kib_tunables_t::kib_timeout, kiblnd_conn_addref, kiblnd_tunables, LASSERT, LBUG, list_add_tail(), kib_tx::tx_conn, kib_tx::tx_deadline, kib_tx::tx_list, kib_tx::tx_msg, kib_tx::tx_nwrq, and kib_tx::tx_queued.
Referenced by kiblnd_check_sends(), kiblnd_connreq_done(), kiblnd_handle_rx(), and kiblnd_queue_tx().
bool kiblnd_reconnect_peer (kib_peer_t * peer)
Definition at line 1317 of file o2iblnd_cb.c.
References CWARN, kib_peer::ibp_accepting, kib_peer::ibp_connecting, kib_peer::ibp_conns, kib_peer::ibp_ni, kib_peer::ibp_nid, kib_peer::ibp_reconnected, kib_peer::ibp_reconnecting, kib_peer::ibp_tx_queue, INIT_LIST_HEAD, kib_data_t::kib_global_lock, kiblnd_connect_peer(), kiblnd_data, kiblnd_peer_active(), kiblnd_txlist_done(), LASSERT, libcfs_nid2str(), list_empty(), and list_splice_init().
Referenced by kiblnd_connd().
int kiblnd_recv (lnet_ni_t * ni, void * private, lnet_msg_t * lntmsg, int delayed, unsigned int niov, struct kvec * iov, lnet_kiov_t * kiov, unsigned int offset, unsigned int mlen, unsigned int rlen)
Definition at line 1718 of file o2iblnd_cb.c.
References CERROR, kib_conn::ibc_peer, IBLND_MSG_GET_DONE, IBLND_MSG_GET_REQ, IBLND_MSG_IMMEDIATE, IBLND_MSG_PUT_ACK, IBLND_MSG_PUT_NAK, IBLND_MSG_PUT_REQ, IBLND_MSG_SIZE, IBLND_POSTRX_NO_CREDIT, IBLND_POSTRX_PEER_CREDIT, kib_peer::ibp_nid, kiblnd_get_idle_tx(), kiblnd_init_tx_msg(), kiblnd_post_rx(), kiblnd_queue_tx(), kiblnd_reply(), kiblnd_send_completion(), kiblnd_setup_rd_iov(), kiblnd_setup_rd_kiov(), kiblnd_tx_done(), LASSERT, LBUG, libcfs_nid2str(), lnet_copy_flat2iov(), lnet_copy_flat2kiov(), lnet_finalize(), offsetof, kib_rx::rx_conn, kib_rx::rx_msg, kib_rx::rx_nob, kib_tx::tx_cookie, kib_tx::tx_lntmsg, kib_tx::tx_msg, and kib_tx::tx_waiting.
static void kiblnd_reject (struct rdma_cm_id * cmid, kib_rej_t * rej) [static]
Definition at line 2209 of file o2iblnd_cb.c.
References CWARN.
Referenced by kiblnd_passive_connect().
static void kiblnd_rejected (kib_conn_t * conn, int reason, void * priv, int priv_nob) [static]
Definition at line 2639 of file o2iblnd_cb.c.
References __swab16s, __swab32, __swab32s, __swab64s, __u64, CDEBUG, CERROR, CNETERR, D_NET, kib_conn::ibc_peer, kib_conn::ibc_state, kib_conn::ibc_version, kib_connparams::ibcp_max_frags, kib_connparams::ibcp_max_msg_size, kib_connparams::ibcp_queue_depth, IBLND_CONN_ACTIVE_CONNECT, IBLND_MSG_MAGIC, IBLND_MSG_VERSION, IBLND_MSG_VERSION_1, IBLND_REJECT_CONN_RACE, IBLND_REJECT_CONN_STALE, IBLND_REJECT_CONN_UNCOMPAT, IBLND_REJECT_FATAL, IBLND_REJECT_MSG_QUEUE_SIZE, IBLND_REJECT_NO_RESOURCES, IBLND_REJECT_RDMA_FRAGS, kib_peer::ibp_nid, kib_tunables_t::kib_service, kiblnd_check_reconnect(), kiblnd_connreq_done(), kiblnd_tunables, LASSERT, libcfs_nid2str(), LNET_PROTO_MAGIC, and offsetof.
Referenced by kiblnd_cm_callback().
static void kiblnd_reply (lnet_ni_t * ni, kib_rx_t * rx, lnet_msg_t * lntmsg) [static]
Definition at line 1656 of file o2iblnd_cb.c.
References CERROR, kib_conn::ibc_peer, IBLND_MSG_GET_DONE, kib_peer::ibp_nid, kiblnd_get_idle_tx(), kiblnd_init_rdma(), kiblnd_queue_tx(), kiblnd_setup_rd_iov(), kiblnd_setup_rd_kiov(), kiblnd_tx_done(), libcfs_nid2str(), lnet_finalize(), lnet_msg::msg_iov, lnet_msg::msg_kiov, lnet_msg::msg_len, lnet_msg::msg_niov, lnet_msg::msg_offset, lnet_msg::msg_target, lnet_process_id_t::nid, kib_rx::rx_conn, kib_rx::rx_msg, kib_tx::tx_lntmsg, and kib_tx::tx_rd.
Referenced by kiblnd_recv().
static int kiblnd_resolve_addr (struct rdma_cm_id * cmid, struct sockaddr_in * srcaddr, struct sockaddr_in * dstaddr, int timeout_ms) [static]
Definition at line 1211 of file o2iblnd_cb.c.
References CDEBUG, CERROR, and D_NET.
Referenced by kiblnd_connect_peer().
static void kiblnd_rx_complete (kib_rx_t * rx, int status, int nob) [static]
Definition at line 471 of file o2iblnd_cb.c.
References CDEBUG, CERROR, CNETERR, D_NET, kib_conn::ibc_early_rxs, kib_conn::ibc_incarnation, kib_conn::ibc_peer, kib_conn::ibc_state, IBLND_CONN_ESTABLISHED, kib_net::ibn_incarnation, kib_peer::ibp_ni, kib_peer::ibp_nid, ignore, kib_data_t::kib_global_lock, kiblnd_close_conn(), kiblnd_data, kiblnd_drop_rx(), kiblnd_handle_rx(), kiblnd_peer_alive(), kiblnd_unpack_msg(), LASSERT, libcfs_nid2str(), list_add_tail(), msg, lnet_ni::ni_data, lnet_ni::ni_nid, kib_rx::rx_conn, kib_rx::rx_list, kib_rx::rx_msg, and kib_rx::rx_nob.
Referenced by kiblnd_complete().
int kiblnd_scheduler (void * arg)
Definition at line 3485 of file o2iblnd_cb.c.
References cfs_block_allsigs(), cfs_cpt_bind(), CWARN, kib_conn::ibc_cq, kib_conn::ibc_peer, kib_conn::ibc_ready, kib_conn::ibc_sched_list, kib_conn::ibc_scheduled, kib_conn::ibc_state, IBLND_RESCHED, IBLND_WID_INVAL, kib_peer::ibp_nid, kib_sched_info::ibs_conns, kib_sched_info::ibs_cpt, kib_sched_info::ibs_lock, kib_sched_info::ibs_waitq, kib_data_t::kib_scheds, kib_data_t::kib_shutdown, KIB_THREAD_CPT, kiblnd_close_conn(), kiblnd_complete(), kiblnd_conn_addref, kiblnd_conn_decref, kiblnd_data, kiblnd_thread_fini(), LASSERT, LCONSOLE_ERROR, libcfs_nid2str(), list_add_tail(), list_del(), list_empty(), list_entry, lnet_cpt_table, list_head::next, and unlikely.
Referenced by kiblnd_start_schedulers().
int kiblnd_send (lnet_ni_t * ni, void * private, lnet_msg_t * lntmsg)
Definition at line 1486 of file o2iblnd_cb.c.
References CDEBUG, CERROR, D_NET, IBLND_MSG_GET_REQ, IBLND_MSG_IMMEDIATE, IBLND_MSG_PUT_REQ, IBLND_MSG_SIZE, lnet_libmd::iov, kiblnd_get_idle_tx(), kiblnd_init_tx_msg(), kiblnd_launch_tx(), kiblnd_setup_rd_iov(), kiblnd_setup_rd_kiov(), kiblnd_tx_done(), lnet_libmd::kiov, LASSERT, LBUG, libcfs_id2str(), libcfs_nid2str(), lnet_copy_iov2flat(), lnet_copy_kiov2flat(), lnet_create_reply_msg(), LNET_MAX_IOV, LNET_MD_KIOV, LNET_MSG_ACK, LNET_MSG_GET, LNET_MSG_PUT, LNET_MSG_REPLY, lnet_libmd::md_iov, lnet_libmd::md_length, lnet_libmd::md_niov, lnet_libmd::md_options, lnet_msg::msg_hdr, lnet_msg::msg_iov, lnet_msg::msg_kiov, lnet_msg::msg_len, lnet_msg::msg_md, lnet_msg::msg_niov, lnet_msg::msg_offset, lnet_msg::msg_routing, lnet_msg::msg_target, lnet_msg::msg_target_is_router, lnet_msg::msg_type, lnet_process_id_t::nid, offsetof, kib_tx::tx_cookie, kib_tx::tx_lntmsg, kib_tx::tx_msg, kib_tx::tx_rd, and kib_tx::tx_waiting.
static void kiblnd_send_completion (kib_conn_t * conn, int type, int status, __u64 cookie) [static]
Definition at line 291 of file o2iblnd_cb.c.
References CERROR, kib_conn::ibc_peer, kib_peer::ibp_ni, kib_peer::ibp_nid, kiblnd_get_idle_tx(), kiblnd_init_tx_msg(), kiblnd_queue_tx(), libcfs_nid2str(), and kib_tx::tx_msg.
Referenced by kiblnd_recv().
static int kiblnd_setup_rd_iov (lnet_ni_t * ni, kib_tx_t * tx, kib_rdma_desc_t * rd, unsigned int niov, struct kvec * iov, int offset, int nob) [static]
Definition at line 654 of file o2iblnd_cb.c.
References CERROR, kiblnd_kvaddr_to_page(), kiblnd_map_tx(), LASSERT, lnet_ni::ni_data, and kib_tx::tx_frags.
Referenced by kiblnd_recv(), kiblnd_reply(), and kiblnd_send().
static int kiblnd_setup_rd_kiov (lnet_ni_t * ni, kib_tx_t * tx, kib_rdma_desc_t * rd, int nkiov, lnet_kiov_t * kiov, int offset, int nob) [static]
Definition at line 707 of file o2iblnd_cb.c.
References CDEBUG, D_NET, kiblnd_map_tx(), lnet_kiov_t::kiov_len, lnet_kiov_t::kiov_offset, lnet_kiov_t::kiov_page, LASSERT, lnet_ni::ni_data, and kib_tx::tx_frags.
Referenced by kiblnd_recv(), kiblnd_reply(), and kiblnd_send().
static void kiblnd_thread_fini (void) [static]
Definition at line 1845 of file o2iblnd_cb.c.
References kib_data_t::kib_nthreads, and kiblnd_data.
Referenced by kiblnd_connd(), kiblnd_failover_thread(), and kiblnd_scheduler().
int kiblnd_thread_start (int(*)(void *arg) fn, void * arg, char * name)
Definition at line 1833 of file o2iblnd_cb.c.
References kib_data_t::kib_nthreads, and kiblnd_data.
Referenced by kiblnd_base_startup(), and kiblnd_start_schedulers().
static void kiblnd_tx_complete (kib_tx_t * tx, int status) [static]
Definition at line 969 of file o2iblnd_cb.c.
References CNETERR, kib_conn::ibc_lock, kib_conn::ibc_noops_posted, kib_conn::ibc_nsends_posted, kib_conn::ibc_peer, kib_conn::ibc_state, IBLND_CONN_ESTABLISHED, IBLND_MSG_NOOP, kib_peer::ibp_ni, kib_peer::ibp_nid, kiblnd_check_sends(), kiblnd_close_conn(), kiblnd_conn_addref, kiblnd_conn_decref, kiblnd_peer_alive(), kiblnd_tx_done(), LASSERT, libcfs_nid2str(), list_del(), LPX64, kib_tx::tx_conn, kib_tx::tx_cookie, kib_tx::tx_list, kib_tx::tx_msg, kib_tx::tx_queued, kib_tx::tx_sending, kib_tx::tx_status, and kib_tx::tx_waiting.
Referenced by kiblnd_complete().
static void kiblnd_tx_done (lnet_ni_t * ni, kib_tx_t * tx) [static]
Definition at line 55 of file o2iblnd_cb.c.
References kib_conn::ibc_peer, kib_peer::ibp_ni, kiblnd_conn_decref, kiblnd_pool_free_node(), kiblnd_unmap_tx(), LASSERT, lnet_finalize(), lnet_ni::ni_data, kib_tx_pool_t::tpo_pool, kib_tx::tx_conn, kib_tx::tx_list, kib_tx::tx_lntmsg, kib_tx::tx_nwrq, kib_tx::tx_pool, kib_tx::tx_queued, kib_tx::tx_sending, kib_tx::tx_status, and kib_tx::tx_waiting.
Referenced by kiblnd_handle_completion(), kiblnd_launch_tx(), kiblnd_post_tx_locked(), kiblnd_recv(), kiblnd_reply(), kiblnd_send(), kiblnd_tx_complete(), and kiblnd_txlist_done().
void kiblnd_txlist_done (lnet_ni_t * ni, struct list_head * txlist, int status)
Definition at line 98 of file o2iblnd_cb.c.
References kiblnd_tx_done(), list_del(), list_empty(), list_entry, list_head::next, kib_tx::tx_list, kib_tx::tx_status, and kib_tx::tx_waiting.
Referenced by kiblnd_abort_txs(), kiblnd_connreq_done(), kiblnd_del_peer(), kiblnd_peer_connect_failed(), and kiblnd_reconnect_peer().
static void kiblnd_unmap_tx (lnet_ni_t * ni, kib_tx_t * tx) [static]
Definition at line 596 of file o2iblnd_cb.c.
References kib_tx::fmr, kib_hca_dev::ibh_ibdev, kib_net::ibn_fmr_ps, kiblnd_dma_unmap_sg(), kiblnd_fmr_pool_unmap(), LASSERT, lnet_ni::ni_data, kib_tx_pool_t::tpo_hdev, kib_tx::tx_dmadir, kib_tx::tx_frags, kib_tx::tx_nfrags, kib_tx::tx_pool, and kib_tx::tx_status.
Referenced by kiblnd_tx_done().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.