Lustre: lnet/klnds/o2iblnd/o2iblnd.c File Reference
lnet/klnds/o2iblnd/o2iblnd.c File Reference
#include <asm/page.h>
#include "o2iblnd.h"
Functions
static __u32 kiblnd_cksum (void *ptr, int nob)
static char * kiblnd_msgtype2str (int type)
static int kiblnd_msgtype2size (int type)
static int kiblnd_unpack_rd (kib_msg_t *msg, int flip)
void kiblnd_pack_msg (lnet_ni_t *ni, kib_msg_t *msg, int version, int credits, lnet_nid_t dstnid, __u64 dststamp)
int kiblnd_unpack_msg (kib_msg_t *msg, int nob)
int kiblnd_create_peer (lnet_ni_t *ni, kib_peer_t **peerp, lnet_nid_t nid)
void kiblnd_destroy_peer (kib_peer_t *peer)
kib_peer_t * kiblnd_find_peer_locked (lnet_nid_t nid)
void kiblnd_unlink_peer_locked (kib_peer_t *peer)
static int kiblnd_get_peer_info (lnet_ni_t *ni, int index, lnet_nid_t *nidp, int *count)
static void kiblnd_del_peer_locked (kib_peer_t *peer)
static int kiblnd_del_peer (lnet_ni_t *ni, lnet_nid_t nid)
static kib_conn_t * kiblnd_get_conn_by_idx (lnet_ni_t *ni, int index)
static void kiblnd_debug_rx (kib_rx_t *rx)
static void kiblnd_debug_tx (kib_tx_t *tx)
void kiblnd_debug_conn (kib_conn_t *conn)
int kiblnd_translate_mtu (int value)
static void kiblnd_setup_mtu_locked (struct rdma_cm_id *cmid)
static int kiblnd_get_completion_vector (kib_conn_t *conn, int cpt)
kib_conn_t * kiblnd_create_conn (kib_peer_t *peer, struct rdma_cm_id *cmid, int state, int version)
void kiblnd_destroy_conn (kib_conn_t *conn, bool free_conn)
int kiblnd_close_peer_conns_locked (kib_peer_t *peer, int why)
int kiblnd_close_stale_conns_locked (kib_peer_t *peer, int version, __u64 incarnation)
static int kiblnd_close_matching_conns (lnet_ni_t *ni, lnet_nid_t nid)
static int kiblnd_ctl (lnet_ni_t *ni, unsigned int cmd, void *arg)
static void kiblnd_query (lnet_ni_t *ni, lnet_nid_t nid, cfs_time_t *when)
static void kiblnd_free_pages (kib_pages_t *p)
int kiblnd_alloc_pages (kib_pages_t **pp, int cpt, int npages)
void kiblnd_unmap_rx_descs (kib_conn_t *conn)
void kiblnd_map_rx_descs (kib_conn_t *conn)
static void kiblnd_unmap_tx_pool (kib_tx_pool_t *tpo)
static kib_hca_dev_t * kiblnd_current_hdev (kib_dev_t *dev)
static void kiblnd_map_tx_pool (kib_tx_pool_t *tpo)
struct ib_mr * kiblnd_find_rd_dma_mr (struct lnet_ni *ni, kib_rdma_desc_t *rd, int negotiated_nfrags)
static void kiblnd_destroy_fmr_pool (kib_fmr_pool_t *fpo)
static void kiblnd_destroy_fmr_pool_list (struct list_head *head)
static int kiblnd_fmr_pool_size (struct lnet_ioctl_config_o2iblnd_tunables *tunables, int ncpts)
static int kiblnd_fmr_flush_trigger (struct lnet_ioctl_config_o2iblnd_tunables *tunables, int ncpts)
static int kiblnd_alloc_fmr_pool (kib_fmr_poolset_t *fps, kib_fmr_pool_t *fpo)
static int kiblnd_alloc_freg_pool (kib_fmr_poolset_t *fps, kib_fmr_pool_t *fpo)
static int kiblnd_create_fmr_pool (kib_fmr_poolset_t *fps, kib_fmr_pool_t **pp_fpo)
static void kiblnd_fail_fmr_poolset (kib_fmr_poolset_t *fps, struct list_head *zombies)
static void kiblnd_fini_fmr_poolset (kib_fmr_poolset_t *fps)
static int kiblnd_init_fmr_poolset (kib_fmr_poolset_t *fps, int cpt, int ncpts, kib_net_t *net, struct lnet_ioctl_config_o2iblnd_tunables *tunables)
static int kiblnd_fmr_pool_is_idle (kib_fmr_pool_t *fpo, cfs_time_t now)
static int kiblnd_map_tx_pages (kib_tx_t *tx, kib_rdma_desc_t *rd)
void kiblnd_fmr_pool_unmap (kib_fmr_t *fmr, int status)
int kiblnd_fmr_pool_map (kib_fmr_poolset_t *fps, kib_tx_t *tx, kib_rdma_desc_t *rd, __u32 nob, __u64 iov, kib_fmr_t *fmr)
static void kiblnd_fini_pool (kib_pool_t *pool)
static void kiblnd_init_pool (kib_poolset_t *ps, kib_pool_t *pool, int size)
static void kiblnd_destroy_pool_list (struct list_head *head)
static void kiblnd_fail_poolset (kib_poolset_t *ps, struct list_head *zombies)
static void kiblnd_fini_poolset (kib_poolset_t *ps)
static int kiblnd_init_poolset (kib_poolset_t *ps, int cpt, kib_net_t *net, char *name, int size, kib_ps_pool_create_t po_create, kib_ps_pool_destroy_t po_destroy, kib_ps_node_init_t nd_init, kib_ps_node_fini_t nd_fini)
static int kiblnd_pool_is_idle (kib_pool_t *pool, cfs_time_t now)
void kiblnd_pool_free_node (kib_pool_t *pool, struct list_head *node)
struct list_head * kiblnd_pool_alloc_node (kib_poolset_t *ps)
static void kiblnd_destroy_tx_pool (kib_pool_t *pool)
static int kiblnd_tx_pool_size (int ncpts)
static int kiblnd_create_tx_pool (kib_poolset_t *ps, int size, kib_pool_t **pp_po)
static void kiblnd_tx_init (kib_pool_t *pool, struct list_head *node)
static void kiblnd_net_fini_pools (kib_net_t *net)
static int kiblnd_net_init_pools (kib_net_t *net, lnet_ni_t *ni, __u32 *cpts, int ncpts)
static int kiblnd_hdev_get_attr (kib_hca_dev_t *hdev)
static void kiblnd_hdev_cleanup_mrs (kib_hca_dev_t *hdev)
void kiblnd_hdev_destroy (kib_hca_dev_t *hdev)
static int kiblnd_hdev_setup_mrs (kib_hca_dev_t *hdev)
static int kiblnd_dummy_callback (struct rdma_cm_id *cmid, struct rdma_cm_event *event)
static int kiblnd_dev_need_failover (kib_dev_t *dev)
int kiblnd_dev_failover (kib_dev_t *dev)
void kiblnd_destroy_dev (kib_dev_t *dev)
static kib_dev_t * kiblnd_create_dev (char *ifname)
static void kiblnd_base_shutdown (void)
static void kiblnd_shutdown (lnet_ni_t *ni)
static int kiblnd_base_startup (void)
static int kiblnd_start_schedulers (struct kib_sched_info *sched)
static int kiblnd_dev_start_threads (kib_dev_t *dev, int newdev, __u32 *cpts, int ncpts)
static kib_dev_t * kiblnd_dev_search (char *ifname)
static int kiblnd_startup (lnet_ni_t *ni)
static void __exit ko2iblnd_exit (void)
static int __init ko2iblnd_init (void)
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("OpenIB gen2 LNet Network Driver")
MODULE_VERSION ("2.8.0")
MODULE_LICENSE ("GPL")
module_init (ko2iblnd_init)
module_exit (ko2iblnd_exit)
Variables
static lnd_t the_o2iblnd
kib_data_t kiblnd_data
Function Documentation
static int kiblnd_alloc_fmr_pool (kib_fmr_poolset_t * fps, kib_fmr_pool_t * fpo) [static]
Definition at line 1472 of file o2iblnd.c.
References CERROR, kib_fmr_pool_t::fmr, kib_fmr_pool_t::fpo_hdev, kib_fmr_poolset_t::fps_cache, kib_fmr_poolset_t::fps_flush_trigger, kib_fmr_poolset_t::fps_pool_size, kib_hca_dev::ibh_pd, and LNET_MAX_PAYLOAD.
Referenced by kiblnd_create_fmr_pool().
static int kiblnd_alloc_freg_pool (kib_fmr_poolset_t * fps, kib_fmr_pool_t * fpo) [static]
Definition at line 1499 of file o2iblnd.c.
References CERROR, kib_fmr_pool_t::fast_reg, kib_fmr_pool_t::fpo_hdev, kib_fmr_poolset_t::fps_cpt, kib_fmr_poolset_t::fps_pool_size, kib_fast_reg_descriptor::frd_frpl, kib_fast_reg_descriptor::frd_list, kib_fast_reg_descriptor::frd_mr, kib_fast_reg_descriptor::frd_valid, kib_hca_dev::ibh_ibdev, kib_hca_dev::ibh_pd, INIT_LIST_HEAD, LIBCFS_CPT_ALLOC, LIBCFS_FREE, list_add_tail(), list_del(), list_for_each_entry_safe, lnet_cpt_table, and LNET_MAX_PAYLOAD.
Referenced by kiblnd_create_fmr_pool().
int kiblnd_alloc_pages (kib_pages_t ** pp, int cpt, int npages)
Definition at line 1191 of file o2iblnd.c.
References CERROR, cfs_page_cpt_alloc(), kib_pages_t::ibp_npages, kib_pages_t::ibp_pages, kiblnd_free_pages(), LIBCFS_CPT_ALLOC, lnet_cpt_table, and offsetof.
Referenced by kiblnd_create_conn(), and kiblnd_create_tx_pool().
static void kiblnd_base_shutdown (void) [static]
Definition at line 2810 of file o2iblnd.c.
References CDEBUG, cfs_percpt_for_each, cfs_percpt_free(), cfs_time_seconds(), D_MALLOC, D_NET, D_WARNING, IBLND_INIT_ALL, IBLND_INIT_DATA, IBLND_INIT_NOTHING, kib_sched_info::ibs_waitq, kib_data_t::kib_connd_conns, kib_data_t::kib_connd_waitq, kib_data_t::kib_connd_zombies, kib_data_t::kib_devs, kib_data_t::kib_failover_waitq, kib_data_t::kib_init, kib_data_t::kib_nthreads, kib_data_t::kib_peer_hash_size, kib_data_t::kib_peers, kib_data_t::kib_reconn_list, kib_data_t::kib_reconn_wait, kib_data_t::kib_scheds, kib_data_t::kib_shutdown, LASSERT, LBUG, LIBCFS_FREE, libcfs_kmemory, and list_empty().
Referenced by kiblnd_base_startup(), and kiblnd_shutdown().
static int kiblnd_base_startup (void) [static]
Definition at line 2956 of file o2iblnd.c.
References CERROR, cfs_cpt_weight(), cfs_percpt_alloc(), cfs_percpt_for_each, IBLND_INIT_ALL, IBLND_INIT_DATA, IBLND_INIT_NOTHING, IBLND_N_SCHED, IBLND_PEER_HASH_SIZE, kib_sched_info::ibs_conns, kib_sched_info::ibs_cpt, kib_sched_info::ibs_lock, kib_sched_info::ibs_nthreads_max, kib_sched_info::ibs_waitq, INIT_LIST_HEAD, kib_data_t::kib_connd_conns, kib_data_t::kib_connd_lock, kib_data_t::kib_connd_waitq, kib_data_t::kib_connd_zombies, kib_tunables_t::kib_dev_failover, kib_data_t::kib_devs, kib_data_t::kib_error_qpa, kib_data_t::kib_failed_devs, kib_data_t::kib_failover_waitq, kib_data_t::kib_global_lock, kib_data_t::kib_init, kib_tunables_t::kib_nscheds, kib_data_t::kib_peer_hash_size, kib_data_t::kib_peers, kib_data_t::kib_reconn_list, kib_data_t::kib_reconn_wait, kib_data_t::kib_scheds, kiblnd_base_shutdown(), kiblnd_connd(), kiblnd_failover_thread(), kiblnd_thread_start(), kiblnd_tunables, LASSERT, LIBCFS_ALLOC, lnet_cpt_table, and max.
Referenced by kiblnd_startup().
static __u32 kiblnd_cksum (void * ptr, int nob) [static]
Definition at line 49 of file o2iblnd.c.
Referenced by kiblnd_pack_msg(), and kiblnd_unpack_msg().
static int kiblnd_close_matching_conns (lnet_ni_t * ni, lnet_nid_t nid) [static]
Definition at line 1046 of file o2iblnd.c.
References kib_peer::ibp_ni, kib_peer::ibp_nid, kib_data_t::kib_global_lock, kib_data_t::kib_peer_hash_size, kib_data_t::kib_peers, kiblnd_close_peer_conns_locked(), kiblnd_nid2peerlist(), kiblnd_peer_idle(), LASSERT, list_entry, list_for_each_safe, and LNET_NID_ANY.
Referenced by kiblnd_ctl().
int kiblnd_close_peer_conns_locked (kib_peer_t * peer, int why)
Definition at line 994 of file o2iblnd.c.
References CDEBUG, D_NET, kib_conn::ibc_version, kib_peer::ibp_conns, kib_peer::ibp_nid, kiblnd_close_conn_locked(), libcfs_nid2str(), list_entry, and list_for_each_safe.
Referenced by kiblnd_close_matching_conns(), and kiblnd_passive_connect().
int kiblnd_close_stale_conns_locked (kib_peer_t * peer, int version, __u64 incarnation)
Definition at line 1017 of file o2iblnd.c.
References CDEBUG, D_NET, kib_conn::ibc_incarnation, kib_conn::ibc_version, kib_peer::ibp_conns, kib_peer::ibp_nid, kiblnd_close_conn_locked(), libcfs_nid2str(), list_entry, list_for_each_safe, and LPX64.
Referenced by kiblnd_connreq_done().
kib_conn_t* kiblnd_create_conn (kib_peer_t * peer, struct rdma_cm_id * cmid, int state, int version)
Definition at line 699 of file o2iblnd.c.
References CDEBUG, CERROR, D_NET, kib_conn::ibc_active_txs, kib_conn::ibc_cmid, kib_conn::ibc_connvars, kib_conn::ibc_cq, kib_conn::ibc_early_rxs, kib_conn::ibc_hdev, kib_conn::ibc_lock, kib_conn::ibc_max_frags, kib_conn::ibc_nrx, kib_conn::ibc_peer, kib_conn::ibc_queue_depth, kib_conn::ibc_refcount, kib_conn::ibc_rx_pages, kib_conn::ibc_rxs, kib_conn::ibc_sched, kib_conn::ibc_state, kib_conn::ibc_tx_noops, kib_conn::ibc_tx_queue, kib_conn::ibc_tx_queue_nocred, kib_conn::ibc_tx_queue_rsrvd, kib_conn::ibc_version, kib_dev_t::ibd_fail_list, kib_dev_t::ibd_failover, kib_dev_t::ibd_hdev, kib_dev_t::ibd_ifname, kib_hca_dev::ibh_ibdev, kib_hca_dev::ibh_pd, IBLND_CONN_ACTIVE_CONNECT, IBLND_CONN_INIT, IBLND_CONN_PASSIVE_WAIT, IBLND_CQ_ENTRIES, IBLND_POSTRX_NO_CREDIT, IBLND_RECV_WRS, IBLND_RX_MSG_PAGES, IBLND_RX_MSGS, IBLND_SEND_WRS, kib_net::ibn_dev, kib_net::ibn_nconns, kib_peer::ibp_max_frags, kib_peer::ibp_ni, kib_peer::ibp_nid, kib_peer::ibp_queue_depth, kib_sched_info::ibs_lock, kib_sched_info::ibs_nthreads, INIT_LIST_HEAD, kib_data_t::kib_failed_devs, kib_data_t::kib_failover_waitq, kib_data_t::kib_global_lock, kib_data_t::kib_scheds, kiblnd_abort_receives(), kiblnd_alloc_pages(), kiblnd_conn_decref, kiblnd_cq_completion(), kiblnd_cq_event(), kiblnd_destroy_conn(), kiblnd_dev_can_failover(), kiblnd_get_completion_vector(), kiblnd_hdev_addref_locked(), kiblnd_map_rx_descs(), kiblnd_post_rx(), kiblnd_qp_event(), kiblnd_setup_mtu_locked(), LASSERT, LIBCFS_CPT_ALLOC, LIBCFS_FREE, libcfs_nid2str(), list_add_tail(), lnet_cpt_of_nid(), lnet_cpt_table, and lnet_ni::ni_data.
Referenced by kiblnd_active_connect(), and kiblnd_passive_connect().
static kib_dev_t* kiblnd_create_dev (char * ifname) [static]
Definition at line 2757 of file o2iblnd.c.
References CERROR, kib_dev_t::ibd_can_failover, kib_dev_t::ibd_fail_list, kib_dev_t::ibd_ifip, kib_dev_t::ibd_ifname, kib_dev_t::ibd_list, kib_dev_t::ibd_nets, INIT_LIST_HEAD, kib_data_t::kib_devs, kiblnd_dev_failover(), LIBCFS_ALLOC, LIBCFS_FREE, list_add_tail(), and lnet_ipif_query().
Referenced by kiblnd_startup().
static int kiblnd_create_fmr_pool (kib_fmr_poolset_t * fps, kib_fmr_pool_t ** pp_fpo) [static]
Definition at line 1575 of file o2iblnd.c.
References CERROR, cfs_time_shift(), kib_fmr_pool_t::fpo_deadline, kib_fmr_pool_t::fpo_hdev, kib_fmr_pool_t::fpo_is_fmr, kib_fmr_pool_t::fpo_owner, kib_fmr_poolset_t::fps_cpt, kib_fmr_poolset_t::fps_net, kib_hca_dev::ibh_ibdev, IBLND_POOL_DEADLINE, kib_net::ibn_dev, kiblnd_alloc_fmr_pool(), kiblnd_alloc_freg_pool(), kiblnd_current_hdev(), kiblnd_hdev_decref(), LCONSOLE_ERROR_MSG, LCONSOLE_INFO, LIBCFS_CPT_ALLOC, LIBCFS_FREE, and lnet_cpt_table.
Referenced by kiblnd_fmr_pool_map(), and kiblnd_init_fmr_poolset().
int kiblnd_create_peer (lnet_ni_t * ni, kib_peer_t ** peerp, lnet_nid_t nid)
Definition at line 320 of file o2iblnd.c.
References CERROR, kib_net::ibn_npeers, kib_net::ibn_shutdown, kib_peer::ibp_conns, kib_peer::ibp_error, kib_peer::ibp_last_alive, kib_peer::ibp_list, kib_peer::ibp_max_frags, kib_peer::ibp_ni, kib_peer::ibp_nid, kib_peer::ibp_queue_depth, kib_peer::ibp_refcount, kib_peer::ibp_tx_queue, INIT_LIST_HEAD, kib_data_t::kib_global_lock, kiblnd_cfg_rdma_frags(), LASSERT, LIBCFS_CPT_ALLOC, lnet_cpt_of_nid(), lnet_cpt_table, LNET_NID_ANY, lnet_ni::ni_data, and lnet_ni::ni_peertxcredits.
Referenced by kiblnd_launch_tx(), and kiblnd_passive_connect().
static int kiblnd_create_tx_pool (kib_poolset_t * ps, int size, kib_pool_t ** pp_po) [static]
Definition at line 2250 of file o2iblnd.c.
References CERROR, IBLND_MAX_RDMA_FRAGS, IBLND_MSG_SIZE, kib_net::ibn_fmr_ps, kiblnd_alloc_pages(), kiblnd_init_pool(), kiblnd_map_tx_pool(), LIBCFS_CPT_ALLOC, LIBCFS_FREE, lnet_cpt_table, LNET_MAX_IOV, offsetof, kib_poolset::ps_cpt, kib_poolset::ps_net, kib_poolset::ps_pool_destroy, kib_tx_pool_t::tpo_pool, kib_tx_pool_t::tpo_tx_descs, kib_tx_pool_t::tpo_tx_pages, kib_tx::tx_frags, kib_tx::tx_pages, kib_tx::tx_pool, kib_tx::tx_rd, kib_tx::tx_sge, and kib_tx::tx_wrq.
Referenced by kiblnd_net_init_pools().
static int kiblnd_ctl (lnet_ni_t * ni, unsigned int cmd, void * arg) [static]
Definition at line 1092 of file o2iblnd.c.
References kib_conn::ibc_cmid, kib_conn::ibc_peer, kib_peer::ibp_nid, libcfs_ioctl_data::ioc_count, IOC_LIBCFS_CLOSE_CONNECTION, IOC_LIBCFS_DEL_PEER, IOC_LIBCFS_GET_CONN, IOC_LIBCFS_GET_PEER, libcfs_ioctl_data::ioc_nid, libcfs_ioctl_data::ioc_u32, kiblnd_close_matching_conns(), kiblnd_conn_decref, kiblnd_del_peer(), kiblnd_get_conn_by_idx(), kiblnd_get_peer_info(), and LASSERT.
static kib_hca_dev_t* kiblnd_current_hdev (kib_dev_t * dev) [static]
Definition at line 1309 of file o2iblnd.c.
References CDEBUG, cfs_time_seconds(), D_NET, kib_dev_t::ibd_failover, kib_dev_t::ibd_hdev, kib_dev_t::ibd_ifname, kib_data_t::kib_global_lock, and kiblnd_hdev_addref_locked().
Referenced by kiblnd_create_fmr_pool(), and kiblnd_map_tx_pool().
void kiblnd_debug_conn (kib_conn_t * conn)
Definition at line 588 of file o2iblnd.c.
References CDEBUG, D_CONSOLE, kib_conn::ibc_active_txs, kib_conn::ibc_comms_error, kib_conn::ibc_credits, kib_conn::ibc_early_rxs, kib_conn::ibc_lock, kib_conn::ibc_noops_posted, kib_conn::ibc_nsends_posted, kib_conn::ibc_outstanding_credits, kib_conn::ibc_peer, kib_conn::ibc_refcount, kib_conn::ibc_reserved_credits, kib_conn::ibc_rxs, kib_conn::ibc_state, kib_conn::ibc_tx_noops, kib_conn::ibc_tx_queue, kib_conn::ibc_tx_queue_nocred, kib_conn::ibc_tx_queue_rsrvd, kib_conn::ibc_version, IBLND_RX_MSGS, kib_peer::ibp_nid, kiblnd_debug_rx(), kiblnd_debug_tx(), libcfs_nid2str(), list_entry, and list_for_each.
static void kiblnd_debug_rx (kib_rx_t * rx) [static]
Definition at line 568 of file o2iblnd.c.
References CDEBUG, D_CONSOLE, kib_rx::rx_msg, and kib_rx::rx_status.
Referenced by kiblnd_debug_conn().
static void kiblnd_debug_tx (kib_tx_t * tx) [static]
Definition at line 576 of file o2iblnd.c.
References CDEBUG, D_CONSOLE, LPX64, kib_tx::tx_cookie, kib_tx::tx_deadline, kib_tx::tx_lntmsg, kib_tx::tx_msg, kib_tx::tx_queued, kib_tx::tx_sending, kib_tx::tx_status, and kib_tx::tx_waiting.
Referenced by kiblnd_debug_conn().
static int kiblnd_del_peer (lnet_ni_t * ni, lnet_nid_t nid) [static]
Definition at line 478 of file o2iblnd.c.
References kib_peer::ibp_conns, kib_peer::ibp_ni, kib_peer::ibp_nid, kib_peer::ibp_tx_queue, kib_data_t::kib_global_lock, kib_data_t::kib_peer_hash_size, kib_data_t::kib_peers, kiblnd_del_peer_locked(), kiblnd_nid2peerlist(), kiblnd_peer_idle(), kiblnd_txlist_done(), LASSERT, list_empty(), list_entry, list_for_each_safe, LIST_HEAD_INIT, list_splice_init(), and LNET_NID_ANY.
Referenced by kiblnd_ctl(), and kiblnd_shutdown().
static void kiblnd_del_peer_locked (kib_peer_t * peer) [static]
Definition at line 457 of file o2iblnd.c.
References kib_peer::ibp_conns, kiblnd_close_conn_locked(), kiblnd_unlink_peer_locked(), list_empty(), list_entry, and list_for_each_safe.
Referenced by kiblnd_del_peer().
void kiblnd_destroy_conn (kib_conn_t * conn, bool free_conn)
Definition at line 925 of file o2iblnd.c.
References CWARN, kib_conn::ibc_active_txs, kib_conn::ibc_cmid, kib_conn::ibc_connvars, kib_conn::ibc_cq, kib_conn::ibc_early_rxs, kib_conn::ibc_hdev, kib_conn::ibc_noops_posted, kib_conn::ibc_nsends_posted, kib_conn::ibc_peer, kib_conn::ibc_refcount, kib_conn::ibc_rx_pages, kib_conn::ibc_rxs, kib_conn::ibc_state, kib_conn::ibc_tx_noops, kib_conn::ibc_tx_queue, kib_conn::ibc_tx_queue_nocred, kib_conn::ibc_tx_queue_rsrvd, IBLND_CONN_DISCONNECTED, IBLND_CONN_INIT, IBLND_RX_MSGS, kib_net::ibn_nconns, kib_peer::ibp_ni, kiblnd_hdev_decref(), kiblnd_peer_decref, kiblnd_unmap_rx_descs(), LASSERT, LBUG, LIBCFS_FREE, list_empty(), and lnet_ni::ni_data.
Referenced by kiblnd_connd(), and kiblnd_create_conn().
void kiblnd_destroy_dev (kib_dev_t * dev)
Definition at line 2742 of file o2iblnd.c.
References kib_dev_t::ibd_fail_list, kib_dev_t::ibd_hdev, kib_dev_t::ibd_list, kib_dev_t::ibd_nets, kib_dev_t::ibd_nnets, kiblnd_hdev_decref(), LASSERT, LIBCFS_FREE, list_del(), and list_empty().
Referenced by kiblnd_shutdown(), and kiblnd_startup().
static void kiblnd_destroy_fmr_pool (kib_fmr_pool_t * fpo) [static]
Definition at line 1411 of file o2iblnd.c.
References CERROR, kib_fmr_pool_t::fast_reg, kib_fmr_pool_t::fmr, kib_fmr_pool_t::fpo_hdev, kib_fmr_pool_t::fpo_is_fmr, kib_fmr_pool_t::fpo_map_count, kib_fast_reg_descriptor::frd_frpl, kib_fast_reg_descriptor::frd_list, kib_fast_reg_descriptor::frd_mr, kiblnd_hdev_decref(), LASSERT, LIBCFS_FREE, list_del(), and list_for_each_entry_safe.
Referenced by kiblnd_destroy_fmr_pool_list().
static void kiblnd_destroy_fmr_pool_list (struct list_head * head) [static]
Definition at line 1444 of file o2iblnd.c.
References kib_fmr_pool_t::fpo_list, kiblnd_destroy_fmr_pool(), list_del(), and list_for_each_entry_safe.
Referenced by kiblnd_dev_failover(), kiblnd_fini_fmr_poolset(), and kiblnd_fmr_pool_unmap().
void kiblnd_destroy_peer (kib_peer_t * peer)
Definition at line 363 of file o2iblnd.c.
References kib_net::ibn_npeers, kib_peer::ibp_ni, kib_peer::ibp_refcount, kib_peer::ibp_tx_queue, kiblnd_peer_active(), kiblnd_peer_idle(), LASSERT, LIBCFS_FREE, list_empty(), and lnet_ni::ni_data.
static void kiblnd_destroy_pool_list (struct list_head * head) [static]
Definition at line 1998 of file o2iblnd.c.
References LASSERT, list_del(), list_empty(), list_entry, list_head::next, kib_pool::po_list, kib_pool::po_owner, and kib_poolset::ps_pool_destroy.
Referenced by kiblnd_dev_failover(), kiblnd_fini_poolset(), and kiblnd_pool_free_node().
static void kiblnd_destroy_tx_pool (kib_pool_t * pool) [static]
Definition at line 2194 of file o2iblnd.c.
References IBLND_MAX_RDMA_FRAGS, kiblnd_fini_pool(), kiblnd_free_pages(), kiblnd_unmap_tx_pool(), LASSERT, LIBCFS_FREE, list_del(), LNET_MAX_IOV, offsetof, kib_pool::po_allocated, kib_pool::po_size, kib_tx_pool_t::tpo_tx_descs, kib_tx_pool_t::tpo_tx_pages, kib_tx::tx_frags, kib_tx::tx_list, kib_tx::tx_pages, kib_tx::tx_rd, kib_tx::tx_sge, and kib_tx::tx_wrq.
Referenced by kiblnd_net_init_pools().
int kiblnd_dev_failover (kib_dev_t * dev)
Definition at line 2608 of file o2iblnd.c.
References CERROR, cfs_cpt_for_each, kib_dev_t::ibd_can_failover, kib_dev_t::ibd_failed_failover, kib_dev_t::ibd_hdev, kib_dev_t::ibd_ifip, kib_dev_t::ibd_ifname, kib_dev_t::ibd_nets, kib_hca_dev::ibh_cmid, kib_hca_dev::ibh_dev, kib_hca_dev::ibh_ibdev, kib_hca_dev::ibh_pd, kib_hca_dev::ibh_ref, kib_net::ibn_fmr_ps, kib_net::ibn_tx_ps, kib_tunables_t::kib_dev_failover, kib_data_t::kib_global_lock, kib_tunables_t::kib_service, kiblnd_cm_callback(), kiblnd_destroy_fmr_pool_list(), kiblnd_destroy_pool_list(), kiblnd_dev_need_failover(), kiblnd_fail_fmr_poolset(), kiblnd_fail_poolset(), kiblnd_hdev_decref(), kiblnd_hdev_setup_mrs(), kiblnd_rdma_create_id, kiblnd_tunables, LASSERT, LIBCFS_ALLOC, list_empty(), list_for_each_entry, LIST_HEAD_INIT, lnet_cpt_table, and kib_tx_poolset_t::tps_poolset.
Referenced by kiblnd_create_dev(), and kiblnd_failover_thread().
static int kiblnd_dev_need_failover (kib_dev_t * dev) [static]
Definition at line 2556 of file o2iblnd.c.
References CERROR, kib_dev_t::ibd_hdev, kib_dev_t::ibd_ifip, kib_dev_t::ibd_ifname, kib_hca_dev::ibh_cmid, kib_hca_dev::ibh_ibdev, kib_tunables_t::kib_dev_failover, kiblnd_dummy_callback(), kiblnd_rdma_create_id, and kiblnd_tunables.
Referenced by kiblnd_dev_failover().
static kib_dev_t* kiblnd_dev_search (char * ifname) [static]
Definition at line 3116 of file o2iblnd.c.
References kib_dev_t::ibd_ifname, kib_data_t::kib_devs, and list_for_each_entry.
Referenced by kiblnd_startup().
static int kiblnd_dev_start_threads (kib_dev_t * dev, int newdev, __u32 * cpts, int ncpts) [static]
Definition at line 3090 of file o2iblnd.c.
References CERROR, kib_dev_t::ibd_ifname, kib_sched_info::ibs_nthreads, kib_data_t::kib_scheds, and kiblnd_start_schedulers().
Referenced by kiblnd_startup().
static int kiblnd_dummy_callback (struct rdma_cm_id * cmid, struct rdma_cm_event * event) [static]
Definition at line 2550 of file o2iblnd.c.
Referenced by kiblnd_dev_need_failover().
static void kiblnd_fail_fmr_poolset (kib_fmr_poolset_t * fps, struct list_head * zombies) [static]
Definition at line 1642 of file o2iblnd.c.
References kib_fmr_pool_t::fpo_failed, kib_fmr_pool_t::fpo_list, kib_fmr_pool_t::fpo_map_count, kib_fmr_poolset_t::fps_failed_pool_list, kib_fmr_poolset_t::fps_lock, kib_fmr_poolset_t::fps_net, kib_fmr_poolset_t::fps_pool_list, list_add(), list_del(), list_empty(), list_entry, and list_head::next.
Referenced by kiblnd_dev_failover().
static void kiblnd_fail_poolset (kib_poolset_t * ps, struct list_head * zombies) [static]
Definition at line 2012 of file o2iblnd.c.
References list_add(), list_del(), list_empty(), list_entry, list_head::next, kib_pool::po_allocated, kib_pool::po_failed, kib_pool::po_list, kib_poolset::ps_failed_pool_list, kib_poolset::ps_lock, kib_poolset::ps_net, and kib_poolset::ps_pool_list.
Referenced by kiblnd_dev_failover().
kib_peer_t* kiblnd_find_peer_locked (lnet_nid_t nid)
Definition at line 383 of file o2iblnd.c.
References CDEBUG, D_NET, kib_peer::ibp_nid, kib_peer::ibp_refcount, kib_peer::ibp_version, kiblnd_nid2peerlist(), kiblnd_peer_idle(), LASSERT, libcfs_nid2str(), list_entry, and list_for_each.
Referenced by kiblnd_launch_tx(), kiblnd_passive_connect(), and kiblnd_query().
struct ib_mr* kiblnd_find_rd_dma_mr (struct lnet_ni * ni, kib_rdma_desc_t * rd, int negotiated_nfrags) [read]
Definition at line 1389 of file o2iblnd.c.
References kib_dev_t::ibd_hdev, kib_hca_dev::ibh_mrs, kib_net::ibn_dev, LASSERT, lnet_ioctl_config_o2iblnd_tunables::lnd_map_on_demand, lnet_ioctl_config_lnd_tunables::lt_o2ib, lnet_ioctl_config_lnd_tunables::lt_tun_u, lnet_ni::ni_data, and lnet_ni::ni_lnd_tunables.
Referenced by kiblnd_map_tx().
static void kiblnd_fini_fmr_poolset (kib_fmr_poolset_t * fps) [static]
Definition at line 1664 of file o2iblnd.c.
References kib_fmr_poolset_t::fps_failed_pool_list, kib_fmr_poolset_t::fps_net, kib_fmr_poolset_t::fps_pool_list, and kiblnd_destroy_fmr_pool_list().
Referenced by kiblnd_net_fini_pools().
static void kiblnd_fini_pool (kib_pool_t * pool) [static]
Definition at line 1977 of file o2iblnd.c.
References CDEBUG, D_NET, LASSERT, list_empty(), kib_pool::po_allocated, kib_pool::po_free_list, kib_pool::po_owner, and kib_poolset::ps_name.
Referenced by kiblnd_destroy_tx_pool().
static void kiblnd_fini_poolset (kib_poolset_t * ps) [static]
Definition at line 2032 of file o2iblnd.c.
References kiblnd_destroy_pool_list(), kib_poolset::ps_failed_pool_list, kib_poolset::ps_net, and kib_poolset::ps_pool_list.
Referenced by kiblnd_net_fini_pools().
static int kiblnd_fmr_flush_trigger (struct lnet_ioctl_config_o2iblnd_tunables * tunables, int ncpts) [static]
Definition at line 1464 of file o2iblnd.c.
References IBLND_FMR_POOL_FLUSH, lnet_ioctl_config_o2iblnd_tunables::lnd_fmr_flush_trigger, max, and size.
Referenced by kiblnd_init_fmr_poolset().
static int kiblnd_fmr_pool_is_idle (kib_fmr_pool_t * fpo, cfs_time_t now) [static]
Definition at line 1701 of file o2iblnd.c.
References cfs_time_aftereq(), kib_fmr_pool_t::fpo_deadline, kib_fmr_pool_t::fpo_failed, and kib_fmr_pool_t::fpo_map_count.
Referenced by kiblnd_fmr_pool_unmap().
int kiblnd_fmr_pool_map (kib_fmr_poolset_t * fps, kib_tx_t * tx, kib_rdma_desc_t * rd, __u32 nob, __u64 iov, kib_fmr_t * fmr)
Definition at line 1790 of file o2iblnd.c.
References __u64, CDEBUG, CERROR, cfs_time_before(), cfs_time_current(), cfs_time_shift(), D_NET, kib_fmr_pool_t::fast_reg, kib_fmr_pool_t::fmr, kib_fmr_t::fmr_frd, kib_fmr_t::fmr_key, kib_fmr_t::fmr_pfmr, kib_fmr_t::fmr_pool, kib_fmr_pool_t::fpo_deadline, kib_fmr_pool_t::fpo_is_fmr, kib_fmr_pool_t::fpo_list, kib_fmr_pool_t::fpo_map_count, kib_fmr_poolset_t::fps_increasing, kib_fmr_poolset_t::fps_lock, kib_fmr_poolset_t::fps_next_retry, kib_fmr_poolset_t::fps_pool_list, kib_fmr_poolset_t::fps_version, kib_fast_reg_descriptor::frd_fastreg_wr, kib_fast_reg_descriptor::frd_frpl, kib_fast_reg_descriptor::frd_inv_wr, kib_fast_reg_descriptor::frd_list, kib_fast_reg_descriptor::frd_mr, kib_fast_reg_descriptor::frd_valid, ib_inc_rkey(), IBLND_POOL_DEADLINE, IBLND_POOL_RETRY, IBLND_WID_MR, kiblnd_create_fmr_pool(), kiblnd_map_tx_pages(), LASSERT, likely, list_add_tail(), list_del(), list_empty(), list_for_each_entry, kib_tx::tx_frags, kib_tx::tx_nfrags, kib_tx::tx_pages, kib_tx::tx_rd, unlikely, version, and ib_rdma_wr::wr.
Referenced by kiblnd_fmr_map_tx().
static int kiblnd_fmr_pool_size (struct lnet_ioctl_config_o2iblnd_tunables * tunables, int ncpts) [static]
Definition at line 1455 of file o2iblnd.c.
References IBLND_FMR_POOL, lnet_ioctl_config_o2iblnd_tunables::lnd_fmr_pool_size, max, and size.
Referenced by kiblnd_init_fmr_poolset().
void kiblnd_fmr_pool_unmap (kib_fmr_t * fmr, int status)
Definition at line 1733 of file o2iblnd.c.
References cfs_time_current(), kib_fmr_pool_t::fast_reg, kib_fmr_pool_t::fmr, kib_fmr_t::fmr_frd, kib_fmr_t::fmr_pfmr, kib_fmr_t::fmr_pool, kib_fmr_pool_t::fpo_is_fmr, kib_fmr_pool_t::fpo_list, kib_fmr_pool_t::fpo_map_count, kib_fmr_pool_t::fpo_owner, kib_fmr_poolset_t::fps_lock, kib_fmr_poolset_t::fps_pool_list, kib_fmr_poolset_t::fps_version, kib_fast_reg_descriptor::frd_list, kib_fast_reg_descriptor::frd_valid, kiblnd_destroy_fmr_pool_list(), kiblnd_fmr_pool_is_idle(), LASSERT, list_add_tail(), list_empty(), list_for_each_entry_safe, LIST_HEAD_INIT, list_move(), list_head::next, and now().
Referenced by kiblnd_unmap_tx().
static void kiblnd_free_pages (kib_pages_t * p) [static]
Definition at line 1177 of file o2iblnd.c.
References kib_pages_t::ibp_npages, kib_pages_t::ibp_pages, LIBCFS_FREE, and offsetof.
Referenced by kiblnd_alloc_pages(), kiblnd_destroy_tx_pool(), and kiblnd_unmap_rx_descs().
static int kiblnd_get_completion_vector (kib_conn_t * conn, int cpt) [static]
Definition at line 672 of file o2iblnd.c.
References cfs_cpt_cpumask(), kib_conn::ibc_cmid, kib_conn::ibc_peer, kib_peer::ibp_nid, LBUG, and lnet_cpt_table.
Referenced by kiblnd_create_conn().
static kib_conn_t* kiblnd_get_conn_by_idx (lnet_ni_t * ni, int index) [static]
Definition at line 530 of file o2iblnd.c.
References kib_peer::ibp_conns, kib_peer::ibp_ni, kib_data_t::kib_global_lock, kib_data_t::kib_peer_hash_size, kib_data_t::kib_peers, kiblnd_conn_addref, kiblnd_peer_idle(), LASSERT, list_entry, and list_for_each.
Referenced by kiblnd_ctl().
static int kiblnd_get_peer_info (lnet_ni_t * ni, int index, lnet_nid_t * nidp, int * count) [static]
Definition at line 420 of file o2iblnd.c.
References kib_peer::ibp_ni, kib_peer::ibp_nid, kib_peer::ibp_refcount, kib_data_t::kib_global_lock, kib_data_t::kib_peer_hash_size, kib_data_t::kib_peers, kiblnd_peer_idle(), LASSERT, list_entry, and list_for_each.
Referenced by kiblnd_ctl().
static void kiblnd_hdev_cleanup_mrs (kib_hca_dev_t * hdev) [static]
Definition at line 2501 of file o2iblnd.c.
References kib_hca_dev::ibh_mrs.
Referenced by kiblnd_hdev_destroy(), and kiblnd_hdev_setup_mrs().
void kiblnd_hdev_destroy (kib_hca_dev_t * hdev)
Definition at line 2512 of file o2iblnd.c.
References kib_hca_dev::ibh_cmid, kib_hca_dev::ibh_pd, kiblnd_hdev_cleanup_mrs(), and LIBCFS_FREE.
Referenced by kiblnd_hdev_decref().
static int kiblnd_hdev_get_attr (kib_hca_dev_t * hdev) [static]
Definition at line 2463 of file o2iblnd.c.
References __u64, CERROR, kib_hca_dev::ibh_ibdev, kib_hca_dev::ibh_mr_shift, kib_hca_dev::ibh_mr_size, kib_hca_dev::ibh_page_mask, kib_hca_dev::ibh_page_shift, kib_hca_dev::ibh_page_size, LIBCFS_ALLOC, LIBCFS_FREE, and LPX64.
Referenced by kiblnd_hdev_setup_mrs().
static int kiblnd_hdev_setup_mrs (kib_hca_dev_t * hdev) [static]
Definition at line 2526 of file o2iblnd.c.
References CERROR, kib_hca_dev::ibh_mrs, kib_hca_dev::ibh_pd, kiblnd_hdev_cleanup_mrs(), and kiblnd_hdev_get_attr().
Referenced by kiblnd_dev_failover().
static int kiblnd_init_fmr_poolset (kib_fmr_poolset_t * fps, int cpt, int ncpts, kib_net_t * net, struct lnet_ioctl_config_o2iblnd_tunables * tunables) [static]
Definition at line 1673 of file o2iblnd.c.
References kib_fmr_pool_t::fpo_list, kib_fmr_poolset_t::fps_cache, kib_fmr_poolset_t::fps_cpt, kib_fmr_poolset_t::fps_failed_pool_list, kib_fmr_poolset_t::fps_flush_trigger, kib_fmr_poolset_t::fps_lock, kib_fmr_poolset_t::fps_net, kib_fmr_poolset_t::fps_pool_list, kib_fmr_poolset_t::fps_pool_size, INIT_LIST_HEAD, kiblnd_create_fmr_pool(), kiblnd_fmr_flush_trigger(), kiblnd_fmr_pool_size(), list_add_tail(), and lnet_ioctl_config_o2iblnd_tunables::lnd_fmr_cache.
Referenced by kiblnd_net_init_pools().
static void kiblnd_init_pool (kib_poolset_t * ps, kib_pool_t * pool, int size) [static]
Definition at line 1986 of file o2iblnd.c.
References CDEBUG, cfs_time_shift(), D_NET, IBLND_POOL_DEADLINE, INIT_LIST_HEAD, kib_pool::po_deadline, kib_pool::po_free_list, kib_pool::po_owner, kib_pool::po_size, and kib_poolset::ps_name.
Referenced by kiblnd_create_tx_pool().
static int kiblnd_init_poolset (kib_poolset_t * ps, int cpt, kib_net_t * net, char * name, int size, kib_ps_pool_create_t po_create, kib_ps_pool_destroy_t po_destroy, kib_ps_node_init_t nd_init, kib_ps_node_fini_t nd_fini) [static]
Definition at line 2041 of file o2iblnd.c.
References CERROR, INIT_LIST_HEAD, list_add(), kib_pool::po_list, kib_poolset::ps_cpt, kib_poolset::ps_failed_pool_list, kib_poolset::ps_lock, kib_poolset::ps_name, kib_poolset::ps_net, kib_poolset::ps_node_fini, kib_poolset::ps_node_init, kib_poolset::ps_pool_create, kib_poolset::ps_pool_destroy, kib_poolset::ps_pool_list, kib_poolset::ps_pool_size, and strlcpy().
Referenced by kiblnd_net_init_pools().
void kiblnd_map_rx_descs (kib_conn_t * conn)
Definition at line 1246 of file o2iblnd.c.
References __u64, CDEBUG, D_NET, kib_conn::ibc_hdev, kib_conn::ibc_rx_pages, kib_conn::ibc_rxs, kib_hca_dev::ibh_ibdev, IBLND_MSG_SIZE, IBLND_RX_MSG_PAGES, IBLND_RX_MSGS, kib_pages_t::ibp_pages, kiblnd_dma_map_single(), kiblnd_dma_mapping_error(), KIBLND_UNMAP_ADDR_SET, LASSERT, LPX64, kib_rx::rx_conn, kib_rx::rx_msg, and kib_rx::rx_msgaddr.
Referenced by kiblnd_create_conn().
static int kiblnd_map_tx_pages (kib_tx_t * tx, kib_rdma_desc_t * rd) [static]
Definition at line 1711 of file o2iblnd.c.
References __u64, kib_hca_dev::ibh_page_mask, kib_hca_dev::ibh_page_size, size, kib_tx_pool_t::tpo_hdev, kib_tx::tx_pages, and kib_tx::tx_pool.
Referenced by kiblnd_fmr_pool_map().
static void kiblnd_map_tx_pool (kib_tx_pool_t * tpo) [static]
Definition at line 1336 of file o2iblnd.c.
References CLASSERT, kib_hca_dev::ibh_ibdev, IBLND_MSG_SIZE, kib_net::ibn_dev, kib_pages_t::ibp_pages, kiblnd_current_hdev(), kiblnd_dma_map_single(), kiblnd_dma_mapping_error(), KIBLND_UNMAP_ADDR_SET, LASSERT, list_add(), kib_pool::po_free_list, kib_pool::po_owner, kib_pool::po_size, kib_poolset::ps_net, kib_tx_pool_t::tpo_hdev, kib_tx_pool_t::tpo_pool, kib_tx_pool_t::tpo_tx_descs, kib_tx_pool_t::tpo_tx_pages, kib_tx::tx_list, kib_tx::tx_msg, and kib_tx::tx_msgaddr.
Referenced by kiblnd_create_tx_pool().
static int kiblnd_msgtype2size (int type) [static]
Definition at line 101 of file o2iblnd.c.
References IBLND_MSG_CONNACK, IBLND_MSG_CONNREQ, IBLND_MSG_GET_DONE, IBLND_MSG_GET_REQ, IBLND_MSG_IMMEDIATE, IBLND_MSG_NOOP, IBLND_MSG_PUT_ACK, IBLND_MSG_PUT_DONE, IBLND_MSG_PUT_NAK, IBLND_MSG_PUT_REQ, and offsetof.
Referenced by kiblnd_unpack_msg().
static char* kiblnd_msgtype2str (int type) [static]
Definition at line 62 of file o2iblnd.c.
References IBLND_MSG_CONNACK, IBLND_MSG_CONNREQ, IBLND_MSG_GET_DONE, IBLND_MSG_GET_REQ, IBLND_MSG_IMMEDIATE, IBLND_MSG_NOOP, IBLND_MSG_PUT_ACK, IBLND_MSG_PUT_DONE, IBLND_MSG_PUT_NAK, and IBLND_MSG_PUT_REQ.
Referenced by kiblnd_unpack_msg(), and kiblnd_unpack_rd().
static void kiblnd_net_fini_pools (kib_net_t * net) [static]
Definition at line 2344 of file o2iblnd.c.
References cfs_cpt_for_each, cfs_percpt_free(), kib_net::ibn_fmr_ps, kib_net::ibn_tx_ps, kiblnd_fini_fmr_poolset(), kiblnd_fini_poolset(), lnet_cpt_table, and kib_tx_poolset_t::tps_poolset.
Referenced by kiblnd_net_init_pools(), and kiblnd_shutdown().
static int kiblnd_net_init_pools (kib_net_t * net, lnet_ni_t * ni, __u32 * cpts, int ncpts) [static]
Definition at line 2375 of file o2iblnd.c.
References CERROR, cfs_percpt_alloc(), kib_net::ibn_fmr_ps, kib_net::ibn_tx_ps, kib_data_t::kib_global_lock, kib_tunables_t::kib_ntx, kiblnd_create_tx_pool(), kiblnd_destroy_tx_pool(), kiblnd_init_fmr_poolset(), kiblnd_init_poolset(), kiblnd_net_fini_pools(), kiblnd_tunables, kiblnd_tx_init(), kiblnd_tx_pool_size(), LASSERT, lnet_ioctl_config_o2iblnd_tunables::lnd_fmr_pool_size, lnet_ioctl_config_o2iblnd_tunables::lnd_map_on_demand, lnet_cpt_table, lnet_ioctl_config_lnd_tunables::lt_o2ib, lnet_ioctl_config_lnd_tunables::lt_tun_u, lnet_ni::ni_lnd_tunables, and kib_tx_poolset_t::tps_poolset.
Referenced by kiblnd_startup().
void kiblnd_pack_msg (lnet_ni_t * ni, kib_msg_t * msg, int version, int credits, lnet_nid_t dstnid, __u64 dststamp)
Definition at line 183 of file o2iblnd.c.
References IBLND_MSG_MAGIC, kib_net::ibn_incarnation, kib_tunables_t::kib_cksum, kiblnd_cksum(), kiblnd_tunables, lnet_ni::ni_data, and lnet_ni::ni_nid.
Referenced by kiblnd_active_connect(), kiblnd_passive_connect(), and kiblnd_post_tx_locked().
struct list_head* kiblnd_pool_alloc_node (kib_poolset_t * ps) [read]
Definition at line 2118 of file o2iblnd.c.
References CDEBUG, CERROR, cfs_time_before(), cfs_time_current(), cfs_time_seconds(), cfs_time_shift(), D_NET, IBLND_POOL_DEADLINE, IBLND_POOL_RETRY, list_add_tail(), list_del(), list_empty(), list_for_each_entry, list_head::next, kib_pool::po_allocated, kib_pool::po_deadline, kib_pool::po_free_list, kib_pool::po_list, kib_poolset::ps_increasing, kib_poolset::ps_lock, kib_poolset::ps_name, kib_poolset::ps_next_retry, kib_poolset::ps_node_init, kib_poolset::ps_pool_create, kib_poolset::ps_pool_list, and kib_poolset::ps_pool_size.
Referenced by kiblnd_get_idle_tx().
void kiblnd_pool_free_node (kib_pool_t * pool, struct list_head * node)
Definition at line 2087 of file o2iblnd.c.
References cfs_time_current(), kiblnd_destroy_pool_list(), kiblnd_pool_is_idle(), LASSERT, list_add(), list_empty(), list_for_each_entry_safe, LIST_HEAD_INIT, list_move(), list_head::next, now(), kib_pool::po_allocated, kib_pool::po_free_list, kib_pool::po_list, kib_pool::po_owner, kib_poolset::ps_lock, kib_poolset::ps_node_fini, and kib_poolset::ps_pool_list.
Referenced by kiblnd_tx_done().
static int kiblnd_pool_is_idle (kib_pool_t * pool, cfs_time_t now) [static]
Definition at line 2077 of file o2iblnd.c.
References cfs_time_aftereq(), kib_pool::po_allocated, kib_pool::po_deadline, and kib_pool::po_failed.
Referenced by kiblnd_pool_free_node().
static void kiblnd_query (lnet_ni_t * ni, lnet_nid_t nid, cfs_time_t * when) [static]
Definition at line 1146 of file o2iblnd.c.
References CDEBUG, cfs_duration_sec(), cfs_time_current(), D_NET, kib_peer::ibp_last_alive, kib_data_t::kib_global_lock, kiblnd_find_peer_locked(), kiblnd_launch_tx(), libcfs_nid2str(), and now().
static void kiblnd_setup_mtu_locked (struct rdma_cm_id * cmid) [static]
Definition at line 657 of file o2iblnd.c.
References kib_tunables_t::kib_ib_mtu, kiblnd_translate_mtu(), kiblnd_tunables, and LASSERT.
Referenced by kiblnd_create_conn().
static void kiblnd_shutdown (lnet_ni_t * ni) [static]
Definition at line 2881 of file o2iblnd.c.
References CDEBUG, cfs_time_seconds(), D_MALLOC, D_NET, D_WARNING, kib_dev_t::ibd_nnets, IBLND_INIT_ALL, IBLND_INIT_NOTHING, kib_net::ibn_dev, kib_net::ibn_init, kib_net::ibn_list, kib_net::ibn_nconns, kib_net::ibn_npeers, kib_net::ibn_shutdown, kib_data_t::kib_devs, kib_data_t::kib_global_lock, kib_data_t::kib_init, kiblnd_base_shutdown(), kiblnd_del_peer(), kiblnd_destroy_dev(), kiblnd_net_fini_pools(), LASSERT, LBUG, LIBCFS_FREE, libcfs_kmemory, libcfs_nid2str(), list_del(), list_empty(), LNET_NID_ANY, lnet_ni::ni_data, and lnet_ni::ni_nid.
Referenced by kiblnd_startup().
static int kiblnd_start_schedulers (struct kib_sched_info * sched) [static]
Definition at line 3049 of file o2iblnd.c.
References CERROR, cfs_cpt_weight(), IBLND_N_SCHED, IBLND_N_SCHED_HIGH, kib_sched_info::ibs_cpt, kib_sched_info::ibs_nthreads, kib_sched_info::ibs_nthreads_max, kib_tunables_t::kib_nscheds, KIB_THREAD_CPT, KIB_THREAD_ID, KIB_THREAD_TID, kiblnd_scheduler(), kiblnd_thread_start(), kiblnd_tunables, LASSERT, lnet_cpt_table, max, and name.
Referenced by kiblnd_dev_start_threads().
static int kiblnd_startup (lnet_ni_t * ni) [static]
Definition at line 3149 of file o2iblnd.c.
References __u64, CDEBUG, CERROR, CLASSERT, D_NET, kib_dev_t::ibd_ifip, kib_dev_t::ibd_ifname, kib_dev_t::ibd_nets, kib_dev_t::ibd_nnets, IBLND_INIT_ALL, IBLND_INIT_NOTHING, kib_net::ibn_dev, kib_net::ibn_incarnation, kib_net::ibn_init, kib_net::ibn_list, kib_tunables_t::kib_default_ipif, kib_data_t::kib_global_lock, kib_data_t::kib_init, kiblnd_base_startup(), kiblnd_create_dev(), kiblnd_destroy_dev(), kiblnd_dev_search(), kiblnd_dev_start_threads(), kiblnd_net_init_pools(), kiblnd_shutdown(), kiblnd_tunables, kiblnd_tunables_setup(), LASSERT, LIBCFS_ALLOC, list_add_tail(), LNET_MAX_INTERFACES, LNET_MKNID(), LNET_NIDNET(), lnet_ni::ni_cpts, lnet_ni::ni_data, lnet_ni::ni_interfaces, lnet_ni::ni_lnd, lnet_ni::ni_ncpts, and lnet_ni::ni_nid.
int kiblnd_translate_mtu (int value)
Definition at line 636 of file o2iblnd.c.
Referenced by kiblnd_setup_mtu_locked(), and kiblnd_tunables_setup().
static void kiblnd_tx_init (kib_pool_t * pool, struct list_head * node) [static]
Definition at line 2334 of file o2iblnd.c.
References list_entry, kib_pool::po_owner, kib_tx_poolset_t::tps_next_tx_cookie, and kib_tx::tx_cookie.
Referenced by kiblnd_net_init_pools().
static int kiblnd_tx_pool_size (int ncpts) [static]
Definition at line 2242 of file o2iblnd.c.
References IBLND_TX_POOL, kib_tunables_t::kib_ntx, kiblnd_tunables, max, and ntx.
Referenced by kiblnd_net_init_pools().
void kiblnd_unlink_peer_locked (kib_peer_t * peer)
Definition at line 409 of file o2iblnd.c.
References kib_peer::ibp_conns, kib_peer::ibp_list, kiblnd_peer_active(), kiblnd_peer_decref, LASSERT, list_del_init(), and list_empty().
Referenced by kiblnd_close_conn_locked(), kiblnd_del_peer_locked(), and kiblnd_peer_connect_failed().
void kiblnd_unmap_rx_descs (kib_conn_t * conn)
Definition at line 1221 of file o2iblnd.c.
References kib_conn::ibc_hdev, kib_conn::ibc_rx_pages, kib_conn::ibc_rxs, kib_hca_dev::ibh_ibdev, IBLND_MSG_SIZE, IBLND_RX_MSGS, kiblnd_dma_unmap_single(), kiblnd_free_pages(), KIBLND_UNMAP_ADDR, LASSERT, kib_rx::rx_msgaddr, and kib_rx::rx_nob.
Referenced by kiblnd_destroy_conn().
static void kiblnd_unmap_tx_pool (kib_tx_pool_t * tpo) [static]
Definition at line 1285 of file o2iblnd.c.
References kib_hca_dev::ibh_ibdev, IBLND_MSG_SIZE, kiblnd_dma_unmap_single(), kiblnd_hdev_decref(), KIBLND_UNMAP_ADDR, LASSERT, kib_pool::po_allocated, kib_pool::po_size, kib_tx_pool_t::tpo_hdev, kib_tx_pool_t::tpo_pool, kib_tx_pool_t::tpo_tx_descs, and kib_tx::tx_msgaddr.
Referenced by kiblnd_destroy_tx_pool().
int kiblnd_unpack_msg (kib_msg_t * msg, int nob)
Definition at line 208 of file o2iblnd.c.
References __swab16, __swab16s, __swab32, __swab32s, __swab64s, CERROR, CLASSERT, IBLND_MSG_CONNACK, IBLND_MSG_CONNREQ, IBLND_MSG_GET_DONE, IBLND_MSG_GET_REQ, IBLND_MSG_IMMEDIATE, IBLND_MSG_MAGIC, IBLND_MSG_NOOP, IBLND_MSG_PUT_ACK, IBLND_MSG_PUT_DONE, IBLND_MSG_PUT_NAK, IBLND_MSG_PUT_REQ, IBLND_MSG_VERSION, IBLND_MSG_VERSION_1, kiblnd_cksum(), kiblnd_msgtype2size(), kiblnd_msgtype2str(), kiblnd_unpack_rd(), libcfs_nid2str(), LNET_NID_ANY, offsetof, and version.
Referenced by kiblnd_check_connreply(), kiblnd_passive_connect(), and kiblnd_rx_complete().
static int kiblnd_unpack_rd (kib_msg_t * msg, int flip) [static]
Definition at line 135 of file o2iblnd.c.
References __swab32s, __swab64s, CERROR, IBLND_MAX_RDMA_FRAGS, IBLND_MSG_GET_REQ, IBLND_MSG_PUT_ACK, kiblnd_msgtype2str(), kiblnd_rd_msg_size(), LASSERT, and offsetof.
Referenced by kiblnd_unpack_msg().
static void __exit ko2iblnd_exit (void) [static]
Definition at line 3249 of file o2iblnd.c.
References lnet_unregister_lnd().
static int __init ko2iblnd_init (void) [static]
Definition at line 3254 of file o2iblnd.c.
References CLASSERT, IBLND_MAX_RDMA_FRAGS, IBLND_MSG_SIZE, kiblnd_tunables_init(), lnet_register_lnd(), and offsetof.
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("OpenIB gen2 LNet Network Driver")
module_exit (ko2iblnd_exit)
module_init (ko2iblnd_init)
MODULE_LICENSE ("GPL")
MODULE_VERSION ("2.8.0")
Variable Documentation
kib_data_t kiblnd_data
Definition at line 46 of file o2iblnd.c.
Referenced by kiblnd_active_connect(), kiblnd_check_connreply(), kiblnd_check_conns(), kiblnd_check_reconnect(), kiblnd_close_conn(), kiblnd_close_conn_locked(), kiblnd_connd(), kiblnd_connreq_done(), kiblnd_disconnect_conn(), kiblnd_failover_thread(), kiblnd_handle_early_rxs(), kiblnd_launch_tx(), kiblnd_passive_connect(), kiblnd_peer_connect_failed(), kiblnd_peer_notify(), kiblnd_reconnect_peer(), kiblnd_rx_complete(), kiblnd_scheduler(), kiblnd_thread_fini(), and kiblnd_thread_start().
static lnd_t the_o2iblnd [static]
Initial value:
 {
        .lnd_type       = O2IBLND,
        .lnd_startup    = kiblnd_startup,
        .lnd_shutdown   = kiblnd_shutdown,
        .lnd_ctl        = kiblnd_ctl,
        .lnd_query      = kiblnd_query,
        .lnd_send       = kiblnd_send,
        .lnd_recv       = kiblnd_recv,
}
Definition at line 44 of file o2iblnd.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.