Lustre: lustre/include/obd_class.h File Reference
lustre/include/obd_class.h File Reference
#include <obd_support.h>
#include <lustre_import.h>
#include <lustre_net.h>
#include <obd.h>
#include <lustre_lib.h>
#include <lustre/lustre_idl.h>
#include <lprocfs_status.h>
Data Structures
struct config_llog_instance
struct config_llog_data
struct lustre_profile
struct lwp_register_item
struct root_squash_info
Defines
#define OBD_STATFS_NODELAY 0x0001
#define OBD_STATFS_FROM_CACHE 0x0002
#define OBD_STATFS_PTLRPCD 0x0004
#define OBD_STATFS_FOR_MDT0 0x0008
#define CFG_F_START 0x01
#define CFG_F_MARKER 0x02
#define CFG_F_SKIP 0x04
#define CFG_F_COMPAT146 0x08
#define CFG_F_EXCLUDE 0x10
#define PARAMS_FILENAME "params"
#define LCTL_UPCALL "lctl"
#define __class_export_add_lock_ref(exp, lock) do {} while(0)
#define __class_export_del_lock_ref(exp, lock) do {} while(0)
#define class_export_rpc_inc(exp)
#define class_export_rpc_dec(exp)
#define class_export_lock_get(exp, lock)
#define class_export_lock_put(exp, lock)
#define class_export_cb_get(exp)
#define class_export_cb_put(exp)
#define OBT(dev) (dev)->obd_type
#define OBP(dev, op) (dev)->obd_type->typ_dt_ops->o_ ## op
#define MDP(dev, op) (dev)->obd_type->typ_md_ops->m_ ## op
#define CTXTP(ctxt, op) (ctxt)->loc_logops->lop_##op
#define OBD_CHECK_DEV(obd)
#define OBD_CHECK_DEV_ACTIVE(obd)
#define OBD_COUNTER_OFFSET(op)
#define OBD_COUNTER_INCREMENT(obd, op)
#define EXP_COUNTER_INCREMENT(exp, op)
#define EXP_MD_COUNTER_INCREMENT(exp, op)
#define EXP_CHECK_MD_OP(exp, op)
#define OBD_CHECK_DT_OP(obd, op, err)
#define EXP_CHECK_DT_OP(exp, op)
#define CTXT_CHECK_OP(ctxt, op, err)
#define DECLARE_LU_VARS(ldt, d)
#define OBDO_ALLOC(ptr)
#define OBDO_FREE(ptr)
#define ll_generate_random_uuid(uuid_out) cfs_get_random_bytes(uuid_out, sizeof(class_uuid_t))
Typedefs
typedef int(* llog_cb_t)(const struct lu_env *, struct llog_handle *, struct llog_rec_hdr *, void *)
typedef int(* register_lwp_cb)(void *data)
typedef __u8 class_uuid_t [16]
Enumerations
enum {
CONFIG_T_CONFIG = 0, CONFIG_T_SPTLRPC = 1, CONFIG_T_RECOVER = 2, CONFIG_T_PARAMS = 3,
CONFIG_T_MAX = 4
}
Functions
struct obd_device * class_conn2obd (struct lustre_handle *)
struct obd_device * class_exp2obd (struct obd_export *)
int class_handle_ioctl (unsigned int cmd, unsigned long arg)
int lustre_get_jobid (char *jobid)
struct obd_export * class_conn2export (struct lustre_handle *)
int class_register_type (struct obd_ops *, struct md_ops *, bool enable_proc, struct lprocfs_vars *module_vars, const char *nm, struct lu_device_type *ldt)
int class_unregister_type (const char *nm)
struct obd_device * class_newdev (const char *type_name, const char *name)
Create a new obd device.
void class_release_dev (struct obd_device *obd)
int class_name2dev (const char *name)
struct obd_device * class_name2obd (const char *name)
int class_uuid2dev (struct obd_uuid *uuid)
struct obd_device * class_uuid2obd (struct obd_uuid *uuid)
void class_obd_list (void)
struct obd_device * class_find_client_obd (struct obd_uuid *tgt_uuid, const char *typ_name, struct obd_uuid *grp_uuid)
struct obd_device * class_devices_in_group (struct obd_uuid *grp_uuid, int *next)
struct obd_device * class_num2obd (int num)
Get obd device from obd_devs[].
int get_devices_count (void)
Get obd devices count.
int class_notify_sptlrpc_conf (const char *fsname, int namelen)
to notify sptlrpc log for fsname has changed, let every relevant OBD adjust sptlrpc settings accordingly.
char * obd_export_nid2str (struct obd_export *exp)
int obd_export_evict_by_nid (struct obd_device *obd, const char *nid)
int obd_export_evict_by_uuid (struct obd_device *obd, const char *uuid)
int obd_connect_flags2str (char *page, int count, __u64 flags, char *sep)
int obd_zombie_impexp_init (void)
start destroy zombie import/export thread
void obd_zombie_impexp_stop (void)
stop destroy zombie import/export thread
void obd_zombie_impexp_cull (void)
kill zombie imports and exports
void obd_zombie_barrier (void)
wait when obd_zombie import/export queues become empty
void obd_exports_barrier (struct obd_device *obd)
int kuc_len (int payload_len)
struct kuc_hdr * kuc_ptr (void *p)
void * kuc_alloc (int payload_len, int transport, int type)
void kuc_free (void *p, int payload_len)
int obd_get_request_slot (struct client_obd *cli)
void obd_put_request_slot (struct client_obd *cli)
__u32 obd_get_max_rpcs_in_flight (struct client_obd *cli)
int obd_set_max_rpcs_in_flight (struct client_obd *cli, __u32 max)
__u16 obd_get_max_mod_rpcs_in_flight (struct client_obd *cli)
int obd_set_max_mod_rpcs_in_flight (struct client_obd *cli, __u16 max)
int obd_mod_rpc_stats_seq_show (struct client_obd *cli, struct seq_file *seq)
__u16 obd_get_mod_rpc_slot (struct client_obd *cli, __u32 opc, struct lookup_intent *it)
void obd_put_mod_rpc_slot (struct client_obd *cli, __u32 opc, struct lookup_intent *it, __u16 tag)
struct obd_export * obd_stale_export_get (void)
void obd_stale_export_put (struct obd_export *exp)
void obd_stale_export_adjust (struct obd_export *exp)
Adjust the position of the export in the stale list, i.e.
struct lustre_cfg * lustre_cfg_rename (struct lustre_cfg *cfg, const char *new_name)
Rename the proc parameter in cfg with a new name new_name.
int class_process_config (struct lustre_cfg *lcfg)
Process configuration commands given in lustre_cfg form.
int class_process_proc_param (char *prefix, struct lprocfs_vars *lvars, struct lustre_cfg *lcfg, void *data)
int class_attach (struct lustre_cfg *lcfg)
Create a new obd device and set the type, name and uuid.
int class_setup (struct obd_device *obd, struct lustre_cfg *lcfg)
Create hashes, self-export, and call type-specific setup.
int class_cleanup (struct obd_device *obd, struct lustre_cfg *lcfg)
Start shutting down the obd.
int class_detach (struct obd_device *obd, struct lustre_cfg *lcfg)
We have finished using this obd and are ready to destroy it.
struct obd_device * class_incref (struct obd_device *obd, const char *scope, const void *source)
void class_decref (struct obd_device *obd, const char *scope, const void *source)
void dump_exports (struct obd_device *obd, int locks)
int class_config_llog_handler (const struct lu_env *env, struct llog_handle *handle, struct llog_rec_hdr *rec, void *data)
Parse a configuration llog, doing various manipulations on them for various reasons, (modifications for compatibility, skip obsolete records, change uuids, etc), then class_process_config() resulting net records.
int class_add_conn (struct obd_device *obd, struct lustre_cfg *lcfg)
Add a failover nid location.
int class_add_uuid (const char *uuid, __u64 nid)
int class_config_parse_llog (const struct lu_env *env, struct llog_ctxt *ctxt, char *name, struct config_llog_instance *cfg)
struct lustre_profile * class_get_profile (const char *prof)
void class_del_profile (const char *prof)
void class_put_profile (struct lustre_profile *lprof)
void class_del_profiles (void)
struct obd_export * class_export_get (struct obd_export *exp)
void class_export_put (struct obd_export *exp)
struct obd_export * class_new_export (struct obd_device *obddev, struct obd_uuid *cluuid)
void class_unlink_export (struct obd_export *exp)
struct obd_import * class_import_get (struct obd_import *)
void class_import_put (struct obd_import *)
struct obd_import * class_new_import (struct obd_device *obd)
void class_destroy_import (struct obd_import *exp)
struct obd_type * class_search_type (const char *name)
struct obd_type * class_get_type (const char *name)
void class_put_type (struct obd_type *type)
int class_connect (struct lustre_handle *conn, struct obd_device *obd, struct obd_uuid *cluuid)
int class_disconnect (struct obd_export *exp)
void class_fail_export (struct obd_export *exp)
int class_connected_export (struct obd_export *exp)
void class_disconnect_exports (struct obd_device *obddev)
int class_manual_cleanup (struct obd_device *obd)
Call class_cleanup and class_detach.
void class_disconnect_stale_exports (struct obd_device *, int(*test_export)(struct obd_export *))
static enum obd_option exp_flags_from_obd (struct obd_device *obd)
void obdo_from_la (struct obdo *dst, const struct lu_attr *la, u64 valid)
void la_from_obdo (struct lu_attr *la, const struct obdo *dst, u64 valid)
void obdo_cpy_md (struct obdo *dst, const struct obdo *src, u64 valid)
void obdo_to_ioobj (const struct obdo *oa, struct obd_ioobj *ioobj)
static int lprocfs_nid_ldlm_stats_init (struct nid_stat *tmp)
static int class_devno_max (void)
static int obd_get_info (const struct lu_env *env, struct obd_export *exp, __u32 keylen, void *key, __u32 *vallen, void *val)
static int obd_set_info_async (const struct lu_env *env, struct obd_export *exp, __u32 keylen, void *key, __u32 vallen, void *val, struct ptlrpc_request_set *set)
static int obd_setup (struct obd_device *obd, struct lustre_cfg *cfg)
static int obd_precleanup (struct obd_device *obd)
static int obd_cleanup (struct obd_device *obd)
static void obd_cleanup_client_import (struct obd_device *obd)
static int obd_process_config (struct obd_device *obd, int datalen, void *data)
static int obd_create (const struct lu_env *env, struct obd_export *exp, struct obdo *obdo)
static int obd_destroy (const struct lu_env *env, struct obd_export *exp, struct obdo *obdo)
static int obd_getattr (const struct lu_env *env, struct obd_export *exp, struct obdo *oa)
static int obd_setattr (const struct lu_env *env, struct obd_export *exp, struct obdo *oa)
static int obd_add_conn (struct obd_import *imp, struct obd_uuid *uuid, int priority)
static int obd_del_conn (struct obd_import *imp, struct obd_uuid *uuid)
static struct obd_uuid * obd_get_uuid (struct obd_export *exp)
static int obd_connect (const struct lu_env *env, struct obd_export **exp, struct obd_device *obd, struct obd_uuid *cluuid, struct obd_connect_data *data, void *localdata)
Create a new /a exp on device /a obd for the uuid /a cluuid.
static int obd_reconnect (const struct lu_env *env, struct obd_export *exp, struct obd_device *obd, struct obd_uuid *cluuid, struct obd_connect_data *d, void *localdata)
static int obd_disconnect (struct obd_export *exp)
static int obd_fid_init (struct obd_device *obd, struct obd_export *exp, enum lu_cli_type type)
static int obd_fid_fini (struct obd_device *obd)
static int obd_fid_alloc (const struct lu_env *env, struct obd_export *exp, struct lu_fid *fid, struct md_op_data *op_data)
static int obd_ping (const struct lu_env *env, struct obd_export *exp)
static int obd_pool_new (struct obd_device *obd, char *poolname)
static int obd_pool_del (struct obd_device *obd, char *poolname)
static int obd_pool_add (struct obd_device *obd, char *poolname, char *ostname)
static int obd_pool_rem (struct obd_device *obd, char *poolname, char *ostname)
static void obd_getref (struct obd_device *obd)
static void obd_putref (struct obd_device *obd)
static int obd_init_export (struct obd_export *exp)
static int obd_destroy_export (struct obd_export *exp)
static int obd_statfs_async (struct obd_export *exp, struct obd_info *oinfo, __u64 max_age, struct ptlrpc_request_set *rqset)
static int obd_statfs_rqset (struct obd_export *exp, struct obd_statfs *osfs, __u64 max_age, __u32 flags)
static int obd_statfs (const struct lu_env *env, struct obd_export *exp, struct obd_statfs *osfs, __u64 max_age, __u32 flags)
static int obd_preprw (const struct lu_env *env, int cmd, struct obd_export *exp, struct obdo *oa, int objcount, struct obd_ioobj *obj, struct niobuf_remote *remote, int *pages, struct niobuf_local *local)
static int obd_commitrw (const struct lu_env *env, int cmd, struct obd_export *exp, struct obdo *oa, int objcount, struct obd_ioobj *obj, struct niobuf_remote *rnb, int pages, struct niobuf_local *local, int rc)
static int obd_iocontrol (unsigned int cmd, struct obd_export *exp, int len, void *karg, void __user *uarg)
static void obd_import_event (struct obd_device *obd, struct obd_import *imp, enum obd_import_event event)
static int obd_notify (struct obd_device *obd, struct obd_device *watched, enum obd_notify_event ev, void *data)
static int obd_notify_observer (struct obd_device *observer, struct obd_device *observed, enum obd_notify_event ev, void *data)
static int obd_quotactl (struct obd_export *exp, struct obd_quotactl *oqctl)
static int obd_health_check (const struct lu_env *env, struct obd_device *obd)
static int obd_register_observer (struct obd_device *obd, struct obd_device *observer)
static int md_get_root (struct obd_export *exp, const char *fileset, struct lu_fid *fid)
static int md_getattr (struct obd_export *exp, struct md_op_data *op_data, struct ptlrpc_request **request)
static int md_null_inode (struct obd_export *exp, const struct lu_fid *fid)
static int md_close (struct obd_export *exp, struct md_op_data *op_data, struct md_open_data *mod, struct ptlrpc_request **request)
static int md_create (struct obd_export *exp, struct md_op_data *op_data, const void *data, size_t datalen, umode_t mode, uid_t uid, gid_t gid, cfs_cap_t cap_effective, __u64 rdev, struct ptlrpc_request **request)
static int md_enqueue (struct obd_export *exp, struct ldlm_enqueue_info *einfo, const union ldlm_policy_data *policy, struct lookup_intent *it, struct md_op_data *op_data, struct lustre_handle *lockh, __u64 extra_lock_flags)
static int md_getattr_name (struct obd_export *exp, struct md_op_data *op_data, struct ptlrpc_request **request)
static int md_intent_lock (struct obd_export *exp, struct md_op_data *op_data, struct lookup_intent *it, struct ptlrpc_request **reqp, ldlm_blocking_callback cb_blocking, __u64 extra_lock_flags)
static int md_link (struct obd_export *exp, struct md_op_data *op_data, struct ptlrpc_request **request)
static int md_rename (struct obd_export *exp, struct md_op_data *op_data, const char *old, size_t oldlen, const char *new, size_t newlen, struct ptlrpc_request **request)
static int md_setattr (struct obd_export *exp, struct md_op_data *op_data, void *ea, size_t ealen, struct ptlrpc_request **request)
static int md_fsync (struct obd_export *exp, const struct lu_fid *fid, struct ptlrpc_request **request)
static int md_read_page (struct obd_export *exp, struct md_op_data *op_data, struct md_callback *cb_op, __u64 hash_offset, struct page **ppage)
static int md_unlink (struct obd_export *exp, struct md_op_data *op_data, struct ptlrpc_request **request)
static int md_get_lustre_md (struct obd_export *exp, struct ptlrpc_request *req, struct obd_export *dt_exp, struct obd_export *md_exp, struct lustre_md *md)
static int md_free_lustre_md (struct obd_export *exp, struct lustre_md *md)
static int md_merge_attr (struct obd_export *exp, const struct lmv_stripe_md *lsm, struct cl_attr *attr, ldlm_blocking_callback cb)
static int md_setxattr (struct obd_export *exp, const struct lu_fid *fid, u64 valid, const char *name, const char *input, int input_size, int output_size, int flags, __u32 suppgid, struct ptlrpc_request **request)
static int md_getxattr (struct obd_export *exp, const struct lu_fid *fid, u64 valid, const char *name, const char *input, int input_size, int output_size, int flags, struct ptlrpc_request **request)
static int md_set_open_replay_data (struct obd_export *exp, struct obd_client_handle *och, struct lookup_intent *it)
static int md_clear_open_replay_data (struct obd_export *exp, struct obd_client_handle *och)
static int md_set_lock_data (struct obd_export *exp, __u64 *lockh, void *data, __u64 *bits)
static int md_cancel_unused (struct obd_export *exp, const struct lu_fid *fid, union ldlm_policy_data *policy, enum ldlm_mode mode, enum ldlm_cancel_flags cancel_flags, void *opaque)
static enum ldlm_mode md_lock_match (struct obd_export *exp, __u64 flags, const struct lu_fid *fid, enum ldlm_type type, union ldlm_policy_data *policy, enum ldlm_mode mode, struct lustre_handle *lockh)
static int md_init_ea_size (struct obd_export *exp, __u32 ea_size, __u32 def_ea_size)
static int md_get_remote_perm (struct obd_export *exp, const struct lu_fid *fid, u32 suppgid, struct ptlrpc_request **request)
static int md_intent_getattr_async (struct obd_export *exp, struct md_enqueue_info *minfo)
static int md_revalidate_lock (struct obd_export *exp, struct lookup_intent *it, struct lu_fid *fid, __u64 *bits)
static int md_get_fid_from_lsm (struct obd_export *exp, const struct lmv_stripe_md *lsm, const char *name, int namelen, struct lu_fid *fid)
static int md_unpackmd (struct obd_export *exp, struct lmv_stripe_md **plsm, const union lmv_mds_md *lmm, size_t lmm_size)
int obd_init_caches (void)
void obd_cleanup_caches (void)
int lustre_register_fs (void)
int lustre_unregister_fs (void)
int lustre_check_exclusion (struct super_block *sb, char *svname)
void obd_sysctl_init (void)
void obd_sysctl_clean (void)
void class_uuid_unparse (class_uuid_t in, struct obd_uuid *out)
int lustre_uuid_to_peer (const char *uuid, lnet_nid_t *peer_nid, int index)
int class_del_uuid (const char *uuid)
int class_check_uuid (struct obd_uuid *uuid, __u64 nid)
void class_init_uuidlist (void)
void class_exit_uuidlist (void)
void statfs_pack (struct obd_statfs *osfs, struct kstatfs *sfs)
void statfs_unpack (struct kstatfs *sfs, struct obd_statfs *osfs)
int server_name2index (const char *svname, __u32 *idx, const char **endptr)
int class_procfs_init (void)
int class_procfs_clean (void)
Variables
struct obd_device * obd_devs [MAX_OBD_DEVICES]
struct list_head obd_types
spinlock_t obd_types_lock
rwlock_t obd_dev_lock
atomic_t obd_stale_export_num
struct list_head obd_stale_exports
spinlock_t obd_stale_export_lock
struct kmem_cache * obdo_cachep
int(* ptlrpc_put_connection_superhack)(struct ptlrpc_connection *c)
char obd_jobid_node []
struct miscdevice obd_psdev
Define Documentation
#define __class_export_add_lock_ref (exp, lock) do {} while(0)
Definition at line 234 of file obd_class.h.
#define __class_export_del_lock_ref (exp, lock) do {} while(0)
Definition at line 235 of file obd_class.h.
#define CFG_F_COMPAT146 0x08
Definition at line 165 of file obd_class.h.
Referenced by class_config_llog_handler(), and mgc_process_config().
#define CFG_F_EXCLUDE 0x10
Definition at line 166 of file obd_class.h.
Referenced by class_config_llog_handler().
#define CFG_F_MARKER 0x02
Definition at line 163 of file obd_class.h.
Referenced by class_config_llog_handler(), and client_lwp_config_process().
#define CFG_F_SKIP 0x04
Definition at line 164 of file obd_class.h.
Referenced by class_config_llog_handler(), and client_lwp_config_process().
#define CFG_F_START 0x01
Definition at line 162 of file obd_class.h.
#define class_export_cb_get (exp)
Value:
({                                                                      \
        atomic_inc(&(exp)->exp_cb_count);                               \
        CDEBUG(D_INFO, "callback GETting export %p : new cb_count %d\n",\
               (exp), atomic_read(&(exp)->exp_cb_count));               \
        class_export_get(exp);                                          \
})
Definition at line 273 of file obd_class.h.
Referenced by ofd_grant_commit_cb_add(), ofd_soft_sync_cb_add(), tgt_last_commit_cb_add(), and tgt_new_client_cb_add().
#define class_export_cb_put (exp)
Value:
({                                                                      \
        LASSERT_ATOMIC_POS(&exp->exp_cb_count);                         \
        atomic_dec(&(exp)->exp_cb_count);                               \
        CDEBUG(D_INFO, "callback PUTting export %p : new cb_count %d\n",\
               (exp), atomic_read(&(exp)->exp_cb_count));               \
        class_export_put(exp);                                          \
})
Definition at line 281 of file obd_class.h.
Referenced by ofd_cb_soft_sync(), ofd_grant_commit_cb(), ofd_grant_commit_cb_add(), ofd_soft_sync_cb_add(), tgt_cb_last_committed(), tgt_cb_new_client(), tgt_last_commit_cb_add(), and tgt_new_client_cb_add().
#define class_export_lock_get (exp, lock)
Value:
({                                                                      \
        atomic_inc(&(exp)->exp_locks_count);                            \
        __class_export_add_lock_ref(exp, lock);                         \
        CDEBUG(D_INFO, "lock GETting export %p : new locks_count %d\n", \
               (exp), atomic_read(&(exp)->exp_locks_count));            \
        class_export_get(exp);                                          \
})
Definition at line 254 of file obd_class.h.
Referenced by ldlm_process_flock_lock(), and mdt_intent_lock_replace().
#define class_export_lock_put (exp, lock)
Value:
({                                                                      \
        LASSERT_ATOMIC_POS(&exp->exp_locks_count);                      \
        atomic_dec(&(exp)->exp_locks_count);                            \
        __class_export_del_lock_ref(exp, lock);                         \
        CDEBUG(D_INFO, "lock PUTting export %p : new locks_count %d\n", \
               (exp), atomic_read(&(exp)->exp_locks_count));            \
        class_export_put(exp);                                          \
})
Definition at line 263 of file obd_class.h.
Referenced by ldlm_lock_put().
#define class_export_rpc_dec (exp)
Value:
({                                                                      \
        LASSERT_ATOMIC_POS(&exp->exp_rpc_count);                        \
        atomic_dec(&(exp)->exp_rpc_count);                              \
        CDEBUG(D_INFO, "RPC PUTting export %p : new rpc_count %d\n",    \
               (exp), atomic_read(&(exp)->exp_rpc_count));              \
})
Definition at line 246 of file obd_class.h.
Referenced by ptlrpc_at_send_early_reply(), ptlrpc_request_change_export(), and ptlrpc_server_finish_active_request().
#define class_export_rpc_inc (exp)
Value:
({                                                                      \
        atomic_inc(&(exp)->exp_rpc_count);                              \
        CDEBUG(D_INFO, "RPC GETting export %p : new rpc_count %d\n",    \
               (exp), atomic_read(&(exp)->exp_rpc_count));              \
})
Definition at line 239 of file obd_class.h.
Referenced by ptlrpc_at_send_early_reply(), ptlrpc_request_change_export(), and ptlrpc_server_request_get().
#define CTXT_CHECK_OP (ctxt, op, err)
Value:
do {                                                                 \
        if (!OBT(ctxt->loc_obd) || !CTXTP((ctxt), op)) {             \
                if (err)                                             \
                        CERROR("lop_" #op ": dev %d no operation\n", \
                               ctxt->loc_obd->obd_minor);            \
                RETURN(err);                                         \
        }                                                            \
} while (0)
Definition at line 490 of file obd_class.h.
Referenced by llog_cancel().
#define CTXTP (ctxt, op) (ctxt)->loc_logops->lop_##op
Definition at line 351 of file obd_class.h.
Referenced by __llog_ctxt_put(), llog_cancel(), and llog_sync().
#define DECLARE_LU_VARS (ldt, d)
Value:
struct lu_device_type *ldt;       \
        struct lu_device *d
Definition at line 554 of file obd_class.h.
Referenced by obd_cleanup(), obd_precleanup(), obd_process_config(), and obd_setup().
#define EXP_CHECK_DT_OP (exp, op)
Value:
do {                                                            \
        if ((exp) == NULL) {                                    \
                CERROR("obd_" #op ": NULL export\n");           \
                RETURN(-ENODEV);                                \
        }                                                       \
        if ((exp)->exp_obd == NULL || !OBT((exp)->exp_obd)) {   \
                CERROR("obd_" #op ": cleaned up obd\n");        \
                RETURN(-EOPNOTSUPP);                            \
        }                                                       \
        if (!OBT((exp)->exp_obd) || !OBP((exp)->exp_obd, op)) { \
                CERROR("obd_" #op ": dev %d no operation\n",    \
                       (exp)->exp_obd->obd_minor);              \
                RETURN(-EOPNOTSUPP);                            \
        }                                                       \
} while (0)
Definition at line 473 of file obd_class.h.
Referenced by obd_commitrw(), obd_create(), obd_destroy(), obd_disconnect(), obd_fid_alloc(), obd_get_info(), obd_getattr(), obd_iocontrol(), obd_preprw(), obd_quotactl(), obd_set_info_async(), and obd_setattr().
#define EXP_CHECK_MD_OP (exp, op)
Value:
do {                                                            \
        if ((exp) == NULL) {                                    \
                CERROR("obd_" #op ": NULL export\n");           \
                RETURN(-ENODEV);                                \
        }                                                       \
        if ((exp)->exp_obd == NULL || !OBT((exp)->exp_obd)) {   \
                CERROR("obd_" #op ": cleaned up obd\n");        \
                RETURN(-EOPNOTSUPP);                            \
        }                                                       \
        if (!OBT((exp)->exp_obd) || !MDP((exp)->exp_obd, op)) { \
                CERROR("obd_" #op ": dev %s/%d no operation\n", \
                       (exp)->exp_obd->obd_name,                \
                       (exp)->exp_obd->obd_minor);              \
                RETURN(-EOPNOTSUPP);                            \
        }                                                       \
} while (0)
Definition at line 444 of file obd_class.h.
Referenced by md_cancel_unused(), md_clear_open_replay_data(), md_close(), md_create(), md_enqueue(), md_free_lustre_md(), md_fsync(), md_get_fid_from_lsm(), md_get_lustre_md(), md_get_remote_perm(), md_get_root(), md_getattr(), md_getattr_name(), md_getxattr(), md_init_ea_size(), md_intent_getattr_async(), md_intent_lock(), md_link(), md_lock_match(), md_merge_attr(), md_null_inode(), md_read_page(), md_rename(), md_revalidate_lock(), md_set_lock_data(), md_set_open_replay_data(), md_setattr(), md_setxattr(), md_unlink(), and md_unpackmd().
#define EXP_COUNTER_INCREMENT (exp, op)
Definition at line 426 of file obd_class.h.
Referenced by obd_commitrw(), obd_create(), obd_destroy(), obd_disconnect(), obd_fid_alloc(), obd_get_info(), obd_get_uuid(), obd_getattr(), obd_iocontrol(), obd_ping(), obd_preprw(), obd_quotactl(), obd_set_info_async(), and obd_setattr().
#define EXP_MD_COUNTER_INCREMENT (exp, op)
Definition at line 427 of file obd_class.h.
Referenced by md_cancel_unused(), md_clear_open_replay_data(), md_close(), md_create(), md_enqueue(), md_free_lustre_md(), md_fsync(), md_get_fid_from_lsm(), md_get_lustre_md(), md_get_remote_perm(), md_get_root(), md_getattr(), md_getattr_name(), md_getxattr(), md_init_ea_size(), md_intent_getattr_async(), md_intent_lock(), md_link(), md_lock_match(), md_merge_attr(), md_null_inode(), md_read_page(), md_rename(), md_revalidate_lock(), md_set_lock_data(), md_set_open_replay_data(), md_setattr(), md_setxattr(), md_unlink(), and md_unpackmd().
#define LCTL_UPCALL "lctl"
Definition at line 191 of file obd_class.h.
Referenced by mgs_wlp_lcfg(), and process_param2_config().
#define ll_generate_random_uuid (uuid_out) cfs_get_random_bytes(uuid_out, sizeof(class_uuid_t))
Definition at line 1712 of file obd_class.h.
Referenced by ll_init_sbi(), lustre_start_mgc(), lwp_setup(), and osp_init0().
#define MDP (dev, op) (dev)->obd_type->typ_md_ops->m_ ## op
Definition at line 350 of file obd_class.h.
Referenced by md_cancel_unused(), md_clear_open_replay_data(), md_close(), md_create(), md_enqueue(), md_free_lustre_md(), md_fsync(), md_get_fid_from_lsm(), md_get_lustre_md(), md_get_remote_perm(), md_get_root(), md_getattr(), md_getattr_name(), md_getxattr(), md_init_ea_size(), md_intent_getattr_async(), md_intent_lock(), md_link(), md_lock_match(), md_merge_attr(), md_null_inode(), md_read_page(), md_rename(), md_revalidate_lock(), md_set_lock_data(), md_set_open_replay_data(), md_setattr(), md_setxattr(), md_unlink(), and md_unpackmd().
#define OBD_CHECK_DEV (obd)
Value:
do {                                                            \
        if (!(obd)) {                                           \
                CERROR("NULL device\n");                        \
                RETURN(-ENODEV);                                \
        }                                                       \
} while (0)
Definition at line 355 of file obd_class.h.
Referenced by obd_cleanup(), obd_notify(), obd_precleanup(), obd_process_config(), and obd_register_observer().
#define OBD_CHECK_DEV_ACTIVE (obd)
Value:
do {                                                            \
        OBD_CHECK_DEV(obd);                                     \
        if (!(obd)->obd_set_up || (obd)->obd_stopping) {        \
                CERROR("Device %d not setup\n",                 \
                       (obd)->obd_minor);                       \
                RETURN(-ENODEV);                                \
        }                                                       \
} while (0)
Definition at line 364 of file obd_class.h.
Referenced by obd_add_conn(), obd_connect(), obd_del_conn(), and obd_reconnect().
#define OBD_CHECK_DT_OP (obd, op, err)
Value:
do {                                                            \
        if (!OBT(obd) || !OBP((obd), op)) {                     \
                if (err)                                        \
                        CERROR("obd_" #op ": dev %d no operation\n",    \
                               obd->obd_minor);                 \
                RETURN(err);                                    \
        }                                                       \
} while (0)
Definition at line 463 of file obd_class.h.
Referenced by obd_add_conn(), obd_cleanup(), obd_connect(), obd_del_conn(), obd_fid_fini(), obd_fid_init(), obd_get_uuid(), obd_ping(), obd_pool_add(), obd_pool_del(), obd_pool_new(), obd_pool_rem(), obd_precleanup(), obd_process_config(), obd_reconnect(), obd_setup(), obd_statfs(), and obd_statfs_async().
#define OBD_COUNTER_INCREMENT (obd, op)
Definition at line 425 of file obd_class.h.
Referenced by obd_add_conn(), obd_cleanup(), obd_connect(), obd_del_conn(), obd_fid_fini(), obd_fid_init(), obd_getref(), obd_import_event(), obd_notify(), obd_pool_add(), obd_pool_del(), obd_pool_new(), obd_pool_rem(), obd_precleanup(), obd_process_config(), obd_putref(), obd_reconnect(), obd_setup(), obd_statfs(), and obd_statfs_async().
#define OBD_COUNTER_OFFSET (op)
Definition at line 424 of file obd_class.h.
#define OBD_STATFS_FOR_MDT0 0x0008
Definition at line 58 of file obd_class.h.
Referenced by client_common_fill_super(), and lmv_statfs().
#define OBD_STATFS_FROM_CACHE 0x0002
Definition at line 50 of file obd_class.h.
Referenced by cb_statfs_update(), and obd_statfs_async().
#define OBD_STATFS_NODELAY 0x0001
Definition at line 48 of file obd_class.h.
Referenced by ll_statfs_internal(), lov_iocontrol(), lov_prep_statfs_set(), mdc_statfs(), osc_statfs(), osc_statfs_async(), osc_statfs_interpret(), and osp_obd_statfs().
#define OBD_STATFS_PTLRPCD 0x0004
Definition at line 52 of file obd_class.h.
Referenced by cb_statfs_update().
#define OBDO_ALLOC (ptr)
Value:
do {                                                                          \
        OBD_SLAB_ALLOC_PTR_GFP((ptr), obdo_cachep, GFP_NOFS);             \
} while(0)
Definition at line 1651 of file obd_class.h.
Referenced by osc_build_rpc(), and osc_set_info_async().
#define OBDO_FREE (ptr)
Value:
do {                                                                          \
        OBD_SLAB_FREE_PTR((ptr), obdo_cachep);                                \
} while(0)
Definition at line 1656 of file obd_class.h.
Referenced by brw_interpret(), osc_build_rpc(), and osc_shrink_grant_interpret().
#define OBP (dev, op) (dev)->obd_type->typ_dt_ops->o_ ## op
Definition at line 349 of file obd_class.h.
Referenced by class_cleanup(), obd_add_conn(), obd_cleanup(), obd_commitrw(), obd_connect(), obd_create(), obd_del_conn(), obd_destroy(), obd_destroy_export(), obd_disconnect(), obd_fid_alloc(), obd_fid_fini(), obd_fid_init(), obd_get_info(), obd_get_uuid(), obd_getattr(), obd_getref(), obd_health_check(), obd_import_event(), obd_init_export(), obd_iocontrol(), obd_notify(), obd_ping(), obd_pool_add(), obd_pool_del(), obd_pool_new(), obd_pool_rem(), obd_precleanup(), obd_preprw(), obd_process_config(), obd_putref(), obd_quotactl(), obd_reconnect(), obd_set_info_async(), obd_setattr(), obd_setup(), obd_statfs(), obd_statfs_async(), and server_start_targets().
#define OBT (dev) (dev)->obd_type
Definition at line 348 of file obd_class.h.
Referenced by obd_destroy_export(), obd_getref(), obd_health_check(), obd_init_export(), and obd_putref().
#define PARAMS_FILENAME "params"
Definition at line 190 of file obd_class.h.
Referenced by config_params_log_add(), ll_put_super(), mgc_process_cfg_log(), mgs_init0(), mgs_llog_open(), mgs_params_fsdb_cleanup(), mgs_params_fsdb_setup(), mgs_setparam(), and mgs_write_log_param2().
Typedef Documentation
typedef __u8 class_uuid_t[16]
Definition at line 1697 of file obd_class.h.
typedef int(* llog_cb_t)(const struct lu_env *, struct llog_handle *, struct llog_rec_hdr *, void *)
Definition at line 130 of file obd_class.h.
typedef int(* register_lwp_cb)(void *data)
Definition at line 1662 of file obd_class.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
CONFIG_T_CONFIG
CONFIG_T_SPTLRPC
CONFIG_T_RECOVER
CONFIG_T_PARAMS
CONFIG_T_MAX
Definition at line 182 of file obd_class.h.
Function Documentation
int class_add_conn (struct obd_device * obd, struct lustre_cfg * lcfg)
Add a failover nid location.
Client obd types contact server obd types using this nid list.
Definition at line 775 of file obd_config.c.
References CERROR, client_obd::cl_import, obd_device::cli, ENTRY, lustre_cfg::lcfg_num, LUSTRE_CFG_BUFLEN, lustre_cfg_string(), LUSTRE_LWP_NAME, LUSTRE_MDC_NAME, LUSTRE_MGC_NAME, LUSTRE_OSC_NAME, LUSTRE_OSP_NAME, obd_add_conn(), obd_str2uuid(), obd_device::obd_type, RETURN, obd_type::typ_name, and obd_device::u.
Referenced by class_process_config(), and lustre_lwp_add_conn().
int class_add_uuid (const char * uuid, __u64 nid)
Definition at line 97 of file lustre_peer.c.
References CDEBUG, D_INFO, g_uuid_list, g_uuid_lock, LASSERT, libcfs_nid2str(), list_add(), list_for_each_entry, NIDS_MAX, OBD_ALLOC_PTR, OBD_FREE, obd_str2uuid(), obd_uuid_equals(), uuid_nid_data::un_list, uuid_nid_data::un_nid_count, uuid_nid_data::un_nids, uuid_nid_data::un_uuid, and UUID_MAX.
Referenced by class_process_config(), client_lwp_config_process(), and lustre_lwp_setup().
int class_attach (struct lustre_cfg * lcfg)
Create a new obd device and set the type, name and uuid.
If successful, the new device can be accessed by either name or uuid.
Definition at line 336 of file obd_config.c.
References CDEBUG, CERROR, cfs_init_timer(), cfs_time_shift_64(), class_newdev(), class_release_dev(), D_IOCTL, ENTRY, GOTO, INIT_LIST_HEAD, LASSERTF, llog_group_init(), lu_ref_add(), lu_ref_init(), LUSTRE_CFG_BUFLEN, lustre_cfg_string(), MKSTR, name, obd_device::obd_attached, obd_device::obd_conn_inprogress, obd_device::obd_delayed_exports, obd_device::obd_dev_lock, obd_device::obd_dev_mutex, OBD_DEVICE_MAGIC, obd_device::obd_evict_inprogress_waitq, obd_device::obd_evict_list, obd_device::obd_exports, obd_device::obd_exports_timed, obd_device::obd_final_req_queue, obd_device::obd_lock_replay_queue, obd_device::obd_lwp_list, obd_device::obd_magic, obd_device::obd_minor, obd_device::obd_name, obd_device::obd_next_transno_waitq, obd_device::obd_nid_lock, obd_device::obd_nid_stats, obd_device::obd_observer_link_sem, obd_device::obd_olg, obd_device::obd_osfs_age, obd_device::obd_osfs_lock, obd_device::obd_pool_limit, obd_device::obd_pool_lock, obd_device::obd_pool_slv, obd_device::obd_recovery_task_lock, obd_device::obd_recovery_timer, obd_device::obd_refcount, obd_device::obd_reference, obd_device::obd_req_replay_queue, obd_device::obd_unlinked_exports, obd_device::obd_uuid, RETURN, obd_uuid::uuid, and uuid.
Referenced by class_process_config(), mdt_quota_init(), and mdt_stack_init().
int class_check_uuid (struct obd_uuid * uuid, __u64 nid)
Definition at line 190 of file lustre_peer.c.
References CDEBUG, D_INFO, ENTRY, g_uuid_list, g_uuid_lock, libcfs_nid2str(), list_for_each_entry, obd_uuid2str(), obd_uuid_equals(), RETURN, uuid_nid_data::un_list, uuid_nid_data::un_nid_count, uuid_nid_data::un_nids, and uuid_nid_data::un_uuid.
Referenced by client_import_find_conn().
int class_cleanup (struct obd_device * obd, struct lustre_cfg * lcfg)
Start shutting down the obd.
There may be in-progess ops when this is called. We tell them to start shutting down with a call to class_disconnect_exports().
Definition at line 616 of file obd_config.c.
References CDEBUG, CERROR, cfs_hash_putref(), class_decref(), class_disconnect_exports(), D_IOCTL, dump_exports(), ENTRY, LASSERT, lustre_cfg::lcfg_bufcount, LCONSOLE_WARN, LUSTRE_CFG_BUFLEN, lustre_cfg_string(), obd_device::obd_conn_inprogress, obd_device::obd_dev_lock, obd_device::obd_fail, OBD_FAIL_LDLM_RECOV_CLIENTS, obd_device::obd_force, obd_device::obd_gen_hash, OBD_IOC_SYNC, obd_iocontrol(), obd_device::obd_minor, obd_device::obd_name, obd_device::obd_nid_hash, obd_device::obd_nid_stats_hash, obd_device::obd_no_recov, obd_device::obd_no_transno, obd_precleanup(), OBD_RACE, obd_device::obd_refcount, obd_device::obd_self_export, obd_device::obd_set_up, obd_device::obd_stopping, obd_device::obd_uuid_hash, OBP, and RETURN.
Referenced by class_process_config(), and mdt_quota_init().
int class_config_llog_handler (const struct lu_env * env, struct llog_handle * handle, struct llog_rec_hdr * rec, void * data)
Parse a configuration llog, doing various manipulations on them for various reasons, (modifications for compatibility, skip obsolete records, change uuids, etc), then class_process_config() resulting net records.
Definition at line 1451 of file obd_config.c.
References __swab32, CDEBUG, CERROR, CFG_F_COMPAT146, CFG_F_EXCLUDE, CFG_F_MARKER, CFG_F_SKIP, config_llog_instance::cfg_flags, config_llog_instance::cfg_instance, config_llog_instance::cfg_lwp_idx, config_llog_instance::cfg_obdname, config_llog_instance::cfg_sb, config_llog_instance::cfg_uuid, class_config_dump_handler(), class_process_config(), CM_END, CM_EXCLUDE, cfg_marker::cm_flags, CM_SKIP, CM_START, cfg_marker::cm_step, cfg_marker::cm_tgtname, CWARN, D_CONFIG, D_INFO, ENTRY, GOTO, IS_MDT, LCFG_ATTACH, lustre_cfg_bufs::lcfg_buf, lustre_cfg_bufs::lcfg_buflen, lustre_cfg::lcfg_command, lustre_cfg::lcfg_flags, LCFG_LOV_ADD_INA, LCFG_LOV_ADD_OBD, LCFG_MARKER, lustre_cfg::lcfg_nal, lustre_cfg::lcfg_nid, lustre_cfg::lcfg_num, LCFG_SETUP, LCFG_SPTLRPC_CONF, lustre_cfg::lcfg_version, llog_handle::lgh_ctxt, libcfs_nid2str(), LNET_MKNET(), LNET_MKNID(), llog_ctxt::loc_obd, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, lustre_cfg_buf(), LUSTRE_CFG_BUFLEN, lustre_cfg_bufs_init(), lustre_cfg_bufs_set(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), lustre_cfg_sanity_check(), lustre_cfg_string(), LUSTRE_CFG_VERSION, lustre_check_exclusion(), LUSTRE_LOD_NAME, LUSTRE_LOV_NAME, LUSTRE_OSC_NAME, LUSTRE_OSP_NAME, lustre_swab_cfg_marker(), lustre_swab_lustre_cfg(), OBD_ALLOC, OBD_CFG_REC, OBD_FREE, obd_device::obd_name, RETURN, server_name2index(), and obd_uuid::uuid.
Referenced by class_config_parse_llog(), do_config_log_add(), ll_fill_super(), and server_start_targets().
int class_config_parse_llog (const struct lu_env * env, struct llog_ctxt * ctxt, char * name, struct config_llog_instance * cfg)
Definition at line 1673 of file obd_config.c.
References CDEBUG, config_llog_instance::cfg_callback, config_llog_instance::cfg_last_idx, class_config_llog_handler(), D_CONFIG, D_INFO, ENTRY, GOTO, LASSERT, llog_close(), LLOG_F_IS_PLAIN, llog_init_handle(), llog_open(), LLOG_OPEN_EXISTS, llog_process(), llog_process_cat_data::lpcd_first_idx, llog_process_cat_data::lpcd_last_idx, and RETURN.
Referenced by mgc_process_cfg_log().
int class_connect (struct lustre_handle * conn, struct obd_device * obd, struct obd_uuid * cluuid)
Definition at line 1150 of file genops.c.
References CDEBUG, class_export_put(), class_new_export(), lustre_handle::cookie, D_IOCTL, ENTRY, obd_export::exp_handle, portals_handle::h_cookie, LASSERT, LPX64, RETURN, and obd_uuid::uuid.
Referenced by client_connect_import(), echo_client_connect(), echo_connect(), lmv_connect(), lod_obd_connect(), lov_connect(), lwp_obd_connect(), mdd_obd_connect(), mdt_obd_connect(), mgs_obd_connect(), ofd_obd_connect(), osd_obd_connect(), osp_obd_connect(), and qmt_device_obd_connect().
int class_connected_export (struct obd_export * exp)
Definition at line 1260 of file genops.c.
References obd_export::exp_conn_cnt, obd_export::exp_failed, and obd_export::exp_lock.
Referenced by tgt_request_handle().
void class_decref (struct obd_device * obd, const char * scope, const void * source)
Definition at line 729 of file obd_config.c.
References CDEBUG, CERROR, class_release_dev(), class_unlink_export(), D_CONFIG, D_INFO, obd_export::exp_flags, exp_flags_from_obd(), obd_export::exp_lock, LASSERT, lu_ref_del(), obd_device::obd_attached, obd_cleanup(), obd_device::obd_dev_lock, obd_device::obd_name, obd_device::obd_refcount, obd_device::obd_reference, obd_device::obd_self_export, obd_device::obd_stopping, obd_device::obd_uuid, and obd_uuid::uuid.
Referenced by class_cleanup(), class_detach(), class_export_destroy(), class_import_destroy(), class_notify_sptlrpc_conf(), lprocfs_mds_evict_client_seq_write(), mgc_fs_cleanup(), and ping_evictor_main().
void class_del_profile (const char * prof)
Definition at line 919 of file obd_config.c.
References CDEBUG, class_get_profile(), class_put_profile(), D_CONFIG, ENTRY, EXIT, list_del(), lustre_profile::lp_list, lustre_profile::lp_list_deleted, and lustre_profile::lp_refs.
Referenced by class_process_config(), and ll_put_super().
void class_del_profiles (void)
Definition at line 966 of file obd_config.c.
References class_put_profile(), ENTRY, EXIT, list_del(), list_for_each_entry_safe, lustre_profile::lp_list, and lustre_profile::lp_list_deleted.
Referenced by mgc_cleanup().
int class_del_uuid (const char * uuid)
Definition at line 147 of file lustre_peer.c.
References CDEBUG, D_INFO, g_uuid_list, g_uuid_lock, INIT_LIST_HEAD, libcfs_nid2str(), list_del(), list_empty(), list_entry, list_for_each_entry, list_move(), list_splice_init(), list_head::next, OBD_FREE, obd_str2uuid(), obd_uuid2str(), obd_uuid_equals(), uuid_nid_data::un_list, uuid_nid_data::un_nid_count, uuid_nid_data::un_nids, and uuid_nid_data::un_uuid.
Referenced by class_exit_uuidlist(), and class_process_config().
void class_destroy_import (struct obd_import * exp)
Definition at line 1091 of file genops.c.
References class_handle_unhash(), class_import_put(), and LASSERT.
Referenced by client_destroy_import(), and client_obd_setup().
int class_detach (struct obd_device * obd, struct lustre_cfg * lcfg)
We have finished using this obd and are ready to destroy it.
There can be no more references to this obd.
Definition at line 586 of file obd_config.c.
References CDEBUG, CERROR, class_decref(), D_IOCTL, ENTRY, obd_device::obd_attached, obd_device::obd_dev_lock, obd_device::obd_minor, obd_device::obd_name, obd_device::obd_set_up, obd_device::obd_uuid, RETURN, and obd_uuid::uuid.
Referenced by class_process_config(), mdt_quota_init(), and mdt_stack_init().
struct obd_device* class_devices_in_group (struct obd_uuid * grp_uuid, int * next) [read]
Definition at line 580 of file genops.c.
References class_devno_max(), class_num2obd(), obd_device::obd_dev_lock, obd_device::obd_uuid, and obd_uuid_equals().
Referenced by ll_put_super().
static int class_devno_max (void) [inline, static]
Definition at line 500 of file obd_class.h.
References MAX_OBD_DEVICES.
Referenced by class_devices_in_group(), class_find_client_obd(), class_handle_ioctl(), class_name2dev(), class_name2obd(), class_newdev(), class_notify_sptlrpc_conf(), class_num2obd(), class_obd_list(), class_uuid2dev(), get_devices_count(), obd_device_list_seq_next(), obd_device_list_seq_start(), and obdclass_init().
int class_disconnect (struct obd_export * exp)
Definition at line 1220 of file genops.c.
References ptlrpc_connection::c_peer, CDEBUG, cfs_hash_del(), class_export_put(), class_export_recovery_cleanup(), class_unlink_export(), CWARN, D_IOCTL, ENTRY, obd_export::exp_connection, obd_export::exp_disconnected, obd_export::exp_handle, obd_export::exp_lock, obd_export::exp_nid_hash, obd_export::exp_obd, GOTO, portals_handle::h_cookie, hlist_unhashed(), LASSERT, LPX64, lnet_process_id_t::nid, obd_device::obd_nid_hash, and RETURN.
Referenced by client_connect_import(), client_disconnect_export(), echo_client_disconnect(), lmv_check_connect(), lmv_disconnect(), lod_obd_disconnect(), lov_disconnect(), lwp_device_fini(), lwp_obd_connect(), lwp_obd_disconnect(), mdd_obd_disconnect(), mdt_obd_connect(), mgs_obd_connect(), ofd_obd_connect(), osd_obd_disconnect(), osp_obd_disconnect(), and qmt_device_obd_disconnect().
void class_disconnect_exports (struct obd_device * obddev)
Definition at line 1319 of file genops.c.
References CDEBUG, class_disconnect_export_list(), D_HA, ENTRY, EXIT, exp_flags_from_obd(), INIT_LIST_HEAD, list_empty(), list_splice_init(), obd_device::obd_delayed_exports, obd_device::obd_dev_lock, obd_device::obd_exports, and obd_device::obd_minor.
Referenced by class_cleanup(), mgs_device_fini(), and tgt_server_data_init().
void class_disconnect_stale_exports (struct obd_device * , int(*)(struct obd_export *) test_export)
Definition at line 1345 of file genops.c.
References ptlrpc_connection::c_peer, CDEBUG, class_disconnect_export_list(), D_HA, ENTRY, EXIT, obd_export::exp_client_uuid, obd_export::exp_connection, obd_export::exp_failed, exp_flags_from_obd(), obd_export::exp_lock, obd_export::exp_obd, obd_export::exp_obd_chain, INIT_LIST_HEAD, LCONSOLE_WARN, libcfs_nid2str(), list_for_each_entry_safe, list_move(), lnet_process_id_t::nid, obd_device::obd_dev_lock, obd_device::obd_exports, obd_device::obd_name, OBD_OPT_ABORT_RECOV, obd_device::obd_uuid, obd_uuid_equals(), print_export_data(), and obd_uuid::uuid.
void class_exit_uuidlist (void)
Definition at line 66 of file lustre_peer.c.
References class_del_uuid().
Referenced by obdclass_exit().
struct obd_device* class_exp2obd (struct obd_export *) [read]
Definition at line 729 of file genops.c.
References obd_export::exp_obd.
Referenced by __lov_del_obd(), cb_statfs_update(), client_disconnect_export(), echo_client_brw_ioctl(), echo_create(), echo_destroy(), echo_getattr(), echo_setattr(), ldlm_completion_ast(), ldlm_flock_completion_ast(), ll_close_inode_openhandle(), ll_get_obd_name(), ll_put_super(), ll_umount_begin(), lmv_disconnect(), lmv_disconnect_mdc(), lmv_fid2path(), lmv_fid_alloc(), lmv_get_info(), lmv_hsm_ct_register(), lmv_iocontrol(), lmv_quotactl(), lmv_set_info_async(), lmv_set_mdc_active(), lmv_statfs(), lod_obd_set_info_async(), lov_disconnect(), lov_disconnect_obd(), lov_get_info(), lov_iocontrol(), lov_set_info_async(), lov_statfs_async(), mdc_cancel_unused(), mdc_close(), mdc_enqueue(), mdc_intent_getattr_async(), mdc_intent_getattr_async_interpret(), mdc_intent_getattr_pack(), mdc_intent_layout_pack(), mdc_intent_open_pack(), mdc_intent_unlink_pack(), mdc_lock_match(), mdc_null_inode(), mdc_statfs(), mdc_unlink(), ofd_statfs(), osc_disconnect(), osc_statfs(), osc_statfs_async(), ping_evictor_wake(), qsd_conn_callback(), tgt_blocking_ast(), tgt_client_data_update(), tgt_client_del(), tgt_handler_find_check(), tgt_init_sec_level(), and tgt_request_handle().
struct obd_export* class_export_get (struct obd_export * exp) [read]
Definition at line 803 of file genops.c.
References CDEBUG, D_INFO, and obd_export::exp_refcount.
Referenced by class_disconnect_export_list(), class_fail_export(), do_config_log_add(), export_handle_addref(), fld_client_add_target(), gen_export_get(), ldlm_export_flock_get(), ldlm_flock_deadlock(), ldlm_flock_lookup_cb(), llog_setup(), lmv_connect(), lustre_find_lwp_by_index(), lustre_lwp_connect(), lustre_notify_lwp_list(), mdt_obd_disconnect(), mdt_tgt_connect(), mgs_fsc_attach(), mgs_obd_disconnect(), nid_export_get(), nm_member_add(), ofd_create_hdl(), ofd_obd_disconnect(), osp_obd_connect(), ping_evictor_main(), ptlrpc_request_change_export(), qmt_lvbo_update(), seq_client_init(), target_send_reply(), tgt_connect(), and uuid_export_get().
void class_export_put (struct obd_export * exp)
Definition at line 812 of file genops.c.
References CDEBUG, D_INFO, D_IOCTL, obd_export::exp_client_uuid, obd_export::exp_obd_chain, obd_export::exp_refcount, obd_export::exp_stale_list, LASSERT, LASSERT_ATOMIC_GT_LT, list_empty(), lprocfs_exp_cleanup(), obd_zombie_export_add(), and obd_uuid::uuid.
Referenced by class_conn2obd(), class_connect(), class_disconnect(), class_disconnect_export_list(), class_fail_export(), class_setup(), config_log_put(), distribute_txn_replay_handle(), fld_client_del_target(), fld_client_fini(), gen_export_put_locked(), import_select_connection(), ldlm_export_flock_put(), ldlm_flock_deadlock(), ldlm_lock_destroy_internal(), lfsck_layout_slave_async_interpret(), lfsck_layout_slave_check_pairs(), lfsck_layout_slave_notify_master(), lfsck_layout_slave_query_master(), llog_ctxt_destroy(), lmv_check_connect(), lmv_disconnect(), lustre_disconnect_lwp(), lustre_lwp_connect(), lustre_put_lwp_item(), mdt_hsm_agent_send(), mdt_obd_disconnect(), mgs_fsc_attach(), mgs_fsc_cleanup(), mgs_fsc_cleanup_by_fsdb(), mgs_obd_disconnect(), nid_export_put_locked(), nm_member_del(), nm_member_delete_list(), obd_export_evict_by_nid(), obd_export_evict_by_uuid(), obd_stale_export_put(), ofd_obd_disconnect(), osp_precreate_thread(), ping_evictor_main(), ptlrpc_at_send_early_reply(), ptlrpc_connect_interpret(), ptlrpc_free_bulk(), ptlrpc_handle_rs(), ptlrpc_request_change_export(), ptlrpc_server_drop_request(), qmt_lvbo_update(), seq_client_fini(), tgt_clients_data_init(), tgt_reply_data_init(), and uuid_export_put_locked().
void class_fail_export (struct obd_export * exp)
Definition at line 1395 of file genops.c.
References CDEBUG, CERROR, class_export_get(), class_export_put(), D_HA, obd_export::exp_client_uuid, obd_export::exp_failed, obd_export::exp_lock, libcfs_debug_dumplog(), obd_disconnect(), obd_dump_on_timeout, and obd_uuid::uuid.
Referenced by mdt_export_evict(), obd_export_evict_by_nid(), obd_export_evict_by_uuid(), ping_evictor_main(), and ptlrpc_check_req().
struct obd_device* class_find_client_obd (struct obd_uuid * tgt_uuid, const char * typ_name, struct obd_uuid * grp_uuid) [read]
Definition at line 547 of file genops.c.
References client_obd::cl_target_uuid, class_devno_max(), class_num2obd(), obd_device::cli, obd_device::obd_dev_lock, obd_device::obd_type, obd_device::obd_uuid, obd_uuid_equals(), obd_type::typ_name, and obd_device::u.
Referenced by llog_test_6(), lmv_add_target(), lmv_connect_mdc(), lod_add_device(), lod_del_device(), and lov_add_target().
struct lustre_profile* class_get_profile (const char * prof) [read]
Definition at line 844 of file obd_config.c.
References ENTRY, list_for_each_entry, lustre_profile::lp_list, lustre_profile::lp_profile, lustre_profile::lp_refs, and RETURN.
Referenced by class_del_profile(), ll_fill_super(), mdt_quota_init(), mdt_stack_init(), and server_put_super().
struct obd_type* class_get_type (const char * name) [read]
Definition at line 121 of file genops.c.
References CDEBUG, class_search_type(), D_INFO, LCONSOLE_ERROR_MSG, LUSTRE_LWP_NAME, LUSTRE_MDS_NAME, LUSTRE_MDT_NAME, LUSTRE_OSP_NAME, obd_ops::o_owner, obd_type::obd_type_lock, obd_type::typ_dt_ops, and obd_type::typ_refcnt.
Referenced by class_newdev().
int class_handle_ioctl (unsigned int cmd, unsigned long arg)
Definition at line 212 of file class_obd.c.
References __user, buf, CDEBUG, CERROR, class_devno_max(), class_name2obd(), class_num2obd(), class_process_config(), class_resolve_dev_name(), class_uuid2dev(), D_HA, D_IOCTL, libcfs_debug_ioctl_data::debug, ENTRY, GOTO, obd_ioctl_data::ioc_bulk, obd_ioctl_data::ioc_count, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf4, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen4, obd_ioctl_data::ioc_pbuf1, obd_ioctl_data::ioc_plen1, LASSERT, libcfs_debug, LIBCFS_IOC_DEBUG_MASK, libcfs_subsystem_debug, lustre_cfg_sanity_check(), MAX_OBD_NAME, OBD_ALLOC, obd_device::obd_attached, OBD_DEV_BY_DEVNAME, OBD_DEVICE_MAGIC, OBD_FREE, OBD_GET_VERSION, OBD_IOC_GETDEVICE, OBD_IOC_NAME2DEV, OBD_IOC_NO_TRANSNO, OBD_IOC_PROCESS_CFG, OBD_IOC_UUID2DEV, obd_iocontrol(), obd_ioctl_getdata(), obd_ioctl_popdata(), obd_device::obd_magic, obd_device::obd_minor, obd_device::obd_name, obd_device::obd_no_transno, obd_device::obd_refcount, obd_device::obd_self_export, obd_device::obd_set_up, obd_device::obd_stopping, obd_str2uuid(), obd_device::obd_type, obd_device::obd_uuid, RETURN, status, strnlen, libcfs_debug_ioctl_data::subs, obd_type::typ_name, and obd_uuid::uuid.
Referenced by obd_class_ioctl().
struct obd_import* class_import_get (struct obd_import *) [read]
Definition at line 1005 of file genops.c.
References CDEBUG, and D_INFO.
Referenced by __ptlrpc_request_alloc(), client_destroy_import(), gss_do_ctx_init_rpc(), gss_sec_create_common(), import_handle_addref(), llog_initiator_connect(), mdc_statfs(), osc_statfs(), osp_obd_statfs(), plain_create_sec(), ptlrpc_import_recovery_state_machine(), ptlrpc_pinger_add_import(), ptlrpc_prep_bulk_imp(), and ptlrpcd_alloc_work().
void class_import_put (struct obd_import *)
Definition at line 1015 of file genops.c.
References CDEBUG, D_INFO, ENTRY, EXIT, obd_import::imp_obd, obd_import::imp_refcount, obd_import::imp_zombie_chain, LASSERT, LASSERT_ATOMIC_GE_LT, LASSERT_ATOMIC_GT_LT, list_empty(), obd_device::obd_name, and obd_zombie_import_add().
Referenced by __ptlrpc_free_req(), class_destroy_import(), client_destroy_import(), client_obd_setup(), gss_do_ctx_init_rpc(), gss_sec_destroy_common(), llog_ctxt_destroy(), llog_initiator_connect(), mdc_statfs(), osc_statfs(), osp_obd_statfs(), plain_destroy_sec(), ptlrpc_free_bulk(), ptlrpc_import_recovery_state_machine(), ptlrpc_invalidate_import_thread(), ptlrpc_pinger_del_import(), and ptlrpc_request_bufs_pack().
struct obd_device* class_incref (struct obd_device * obd, const char * scope, const void * source) [read]
Definition at line 717 of file obd_config.c.
References CDEBUG, D_INFO, lu_ref_add_atomic(), obd_device::obd_name, obd_device::obd_refcount, and obd_device::obd_reference.
Referenced by class_new_export(), class_new_import(), class_notify_sptlrpc_conf(), class_setup(), lprocfs_mds_evict_client_seq_write(), mgc_fs_setup(), and ping_evictor_wake().
void class_init_uuidlist (void)
Definition at line 60 of file lustre_peer.c.
References g_uuid_list, g_uuid_lock, and INIT_LIST_HEAD.
Referenced by obdclass_init().
int class_manual_cleanup (struct obd_device * obd)
Call class_cleanup and class_detach.
"Manual" only in the sense that we're faking lcfg commands.
Definition at line 1909 of file obd_config.c.
References CDEBUG, CERROR, class_process_config(), D_CONFIG, ENTRY, GOTO, LCFG_CLEANUP, lustre_cfg::lcfg_command, LCFG_DETACH, lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), obd_device::obd_fail, obd_device::obd_force, obd_device::obd_name, and RETURN.
Referenced by __lov_del_obd(), ll_put_super(), lod_obd_disconnect(), lustre_stop_lwp(), lustre_stop_mgc(), mdd_obd_disconnect(), mdt_quota_init(), osd_obd_disconnect(), osd_start(), osp_obd_disconnect(), qmt_device_obd_disconnect(), server_put_super(), server_stop_mgs(), and server_stop_servers().
int class_name2dev (const char * name)
Definition at line 402 of file genops.c.
References class_devno_max(), class_num2obd(), LASSERT, obd_device::obd_attached, obd_device::obd_dev_lock, obd_dev_lock, OBD_DEVICE_MAGIC, obd_device::obd_magic, and obd_device::obd_name.
Referenced by class_name2obd(), and class_resolve_dev_name().
struct obd_device* class_name2obd (const char * name) [read]
Definition at line 429 of file genops.c.
References class_devno_max(), class_name2dev(), and class_num2obd().
Referenced by class_handle_ioctl(), class_process_config(), client_common_fill_super(), echo_client_setup(), echo_device_alloc(), gss_do_ctx_init_rpc(), llog_test_setup(), lod_connect_to_osd(), lod_init0(), lod_pools_init(), lod_process_config(), lov_device_alloc(), lustre_find_lwp(), lustre_lwp_setup(), lustre_register_lwp_item(), lustre_start_mgc(), lwp_init0(), mdd_connect_to_next(), mdd_init0(), mds_device_alloc(), mdt_connect_to_next(), mdt_init0(), mdt_quota_init(), mdt_stack_init(), mgc_apply_recover_logs(), mgs_connect_to_osd(), mgs_init0(), ofd_connect_to_next(), ofd_init0(), osc_device_alloc(), osd_start(), osp_connect_to_osd(), osp_init0(), qmt_connect_to_osd(), qmt_device_init0(), server_fill_super(), server_put_super(), server_start_targets(), server_stop_mgs(), and server_stop_servers().
struct obd_export* class_new_export (struct obd_device * obddev, struct obd_uuid * cluuid) [read]
Definition at line 836 of file genops.c.
References at_init(), cfs_hash_add_unique(), cfs_hash_del(), cfs_hash_getref(), cfs_hash_putref(), cfs_time_current_sec(), class_handle_hash(), class_handle_unhash(), class_incref(), ENTRY, obd_export::exp_bl_list, obd_export::exp_bl_list_lock, obd_export::exp_bl_lock_at, obd_export::exp_cb_count, obd_export::exp_client_uuid, obd_export::exp_conn_cnt, obd_export::exp_flock_hash, obd_export::exp_flvr, obd_export::exp_gen_hash, obd_export::exp_handle, obd_export::exp_hp_rpcs, obd_export::exp_last_request_time, obd_export::exp_lock, obd_export::exp_lock_hash, obd_export::exp_locks_count, obd_export::exp_nid_hash, obd_export::exp_obd, obd_export::exp_obd_chain, obd_export::exp_obd_chain_timed, obd_export::exp_outstanding_replies, obd_export::exp_refcount, obd_export::exp_reg_rpcs, obd_export::exp_replay_count, obd_export::exp_req_replay_queue, obd_export::exp_rpc_count, obd_export::exp_rpc_lock, obd_export::exp_sp_peer, obd_export::exp_stale_list, obd_export::exp_uncommitted_replies, obd_export::exp_uncommitted_replies_lock, obd_export::exp_uuid_hash, GOTO, portals_handle::h_link, hlist_unhashed(), INIT_HLIST_NODE, INIT_LIST_HEAD, LASSERT, LCONSOLE_WARN, list_add(), list_add_tail(), LUSTRE_SP_ANY, OBD_ALLOC_PTR, obd_destroy_export(), obd_device::obd_dev_lock, obd_device::obd_exports, obd_device::obd_exports_timed, OBD_FREE_PTR, obd_init_export(), obd_device::obd_name, obd_device::obd_num_exports, obd_device::obd_stopping, obd_timeout, obd_device::obd_uuid, obd_uuid_equals(), obd_device::obd_uuid_hash, RETURN, sptlrpc_flavor::sf_rpc, SPTLRPC_FLVR_INVALID, and obd_uuid::uuid.
Referenced by class_connect(), class_setup(), and tgt_clients_data_init().
struct obd_import* class_new_import (struct obd_device * obd) [read]
Definition at line 1049 of file genops.c.
References class_handle_hash(), class_incref(), portals_handle::h_link, obd_import::imp_at, obd_import::imp_committed_list, obd_import::imp_conn_list, obd_import::imp_delayed_list, obd_import::imp_handle, obd_import::imp_inflight, obd_import::imp_inval_count, obd_import::imp_known_replied_xid, obd_import::imp_last_success_conn, obd_import::imp_lock, obd_import::imp_msg_magic, obd_import::imp_obd, obd_import::imp_pinger_chain, obd_import::imp_recovery_waitq, obd_import::imp_refcount, obd_import::imp_replay_cursor, obd_import::imp_replay_inflight, obd_import::imp_replay_list, obd_import::imp_sec_mutex, obd_import::imp_sending_list, obd_import::imp_state, obd_import::imp_unregistering, obd_import::imp_unreplied_list, obd_import::imp_zombie_chain, init_imp_at(), INIT_LIST_HEAD, LUSTRE_IMP_NEW, LUSTRE_MSG_MAGIC_V2, and OBD_ALLOC.
Referenced by client_obd_setup().
struct obd_device* class_newdev (const char * type_name, const char * name) [read]
Create a new obd device.
Find an empty slot in obd_devs[], create a new obd device in it.
Parameters:
[in] type_name obd device type string.
[in] name obd device name.
Return values:
NULL if create fails, otherwise return the obd device pointer created.
Definition at line 302 of file genops.c.
References CDEBUG, CERROR, class_devno_max(), class_get_type(), class_num2obd(), class_put_type(), D_IOCTL, ENTRY, GOTO, LASSERT, LASSERTF, MAX_OBD_NAME, obd_device::obd_dev_lock, obd_dev_lock, obd_device_alloc(), obd_device_free(), OBD_DEVICE_MAGIC, obd_devs, obd_device::obd_magic, obd_device::obd_minor, obd_device::obd_name, obd_device::obd_type, and RETURN.
Referenced by class_attach().
int class_notify_sptlrpc_conf (const char * fsname, int namelen)
to notify sptlrpc log for fsname has changed, let every relevant OBD adjust sptlrpc settings accordingly.
Definition at line 614 of file genops.c.
References class_decref(), class_devno_max(), class_incref(), class_num2obd(), KEY_SPTLRPC_CONF, LASSERT, LUSTRE_LWP_NAME, LUSTRE_MDC_NAME, LUSTRE_MDT_NAME, LUSTRE_OSC_NAME, LUSTRE_OSP_NAME, LUSTRE_OST_NAME, obd_device::obd_dev_lock, obd_device::obd_name, obd_device::obd_self_export, obd_set_info_async(), obd_device::obd_set_up, obd_device::obd_stopping, obd_device::obd_type, and obd_type::typ_name.
Referenced by mgc_process_cfg_log().
struct obd_device* class_num2obd (int num) [read]
Get obd device from obd_devs[].
Parameters:
num [in] array index
Return values:
NULL if obd_devs[num] does not contains an obd device otherwise return the obd device there.
Definition at line 475 of file genops.c.
References class_devno_max(), LASSERTF, OBD_DEVICE_MAGIC, obd_devs, obd_device::obd_magic, and obd_device::obd_minor.
Referenced by class_devices_in_group(), class_find_client_obd(), class_handle_ioctl(), class_name2dev(), class_name2obd(), class_newdev(), class_notify_sptlrpc_conf(), class_obd_list(), class_setup(), class_uuid2dev(), class_uuid2obd(), get_devices_count(), and obd_device_list_seq_show().
void class_obd_list (void)
Definition at line 516 of file genops.c.
References class_devno_max(), class_num2obd(), D_CONFIG, LCONSOLE, obd_device::obd_attached, obd_device::obd_dev_lock, obd_device::obd_name, obd_device::obd_refcount, obd_device::obd_set_up, obd_device::obd_stopping, obd_device::obd_type, obd_device::obd_uuid, status, obd_type::typ_name, and obd_uuid::uuid.
int class_process_config (struct lustre_cfg * lcfg)
Process configuration commands given in lustre_cfg form.
These may come from direct calls (e.g. class_manual_cleanup) or processing the config llog, or ioctl from lctl.
Definition at line 1142 of file obd_config.c.
References CDEBUG, CERROR, class_add_conn(), class_add_profile(), class_add_uuid(), class_attach(), class_cleanup(), class_del_conn(), class_del_profile(), class_del_uuid(), class_detach(), class_match_param(), class_name2obd(), class_set_global(), class_setup(), client_process_config, cfg_marker::cm_comment, cfg_marker::cm_flags, cfg_marker::cm_step, cfg_marker::cm_tgtname, CWARN, D_IOCTL, GOTO, LASSERT, LCFG_ADD_CONN, LCFG_ADD_UUID, LCFG_ATTACH, lustre_cfg::lcfg_bufcount, LCFG_CLEANUP, lustre_cfg::lcfg_command, LCFG_DEL_CONN, LCFG_DEL_MOUNTOPT, LCFG_DEL_UUID, LCFG_DETACH, LCFG_MARKER, LCFG_MOUNTOPT, lustre_cfg::lcfg_nid, lustre_cfg::lcfg_num, LCFG_PARAM, LCFG_POOL_ADD, LCFG_POOL_DEL, LCFG_POOL_NEW, LCFG_POOL_REM, LCFG_REQUIRED, LCFG_SET_LDLM_TIMEOUT, LCFG_SET_PARAM, LCFG_SET_TIMEOUT, LCFG_SET_UPCALL, LCFG_SETUP, LCONSOLE_ERROR_MSG, ldlm_timeout, ldlm_timeout_set, libcfs_nid2str(), LPX64, lustre_cfg_buf(), LUSTRE_CFG_BUFLEN, lustre_cfg_string(), max, obd_pool_add(), obd_pool_del(), obd_pool_new(), obd_pool_rem(), obd_process_config(), obd_timeout, obd_timeout_set, PARAM_LLITE, PARAM_QUOTA, PARAM_SYS, process_param2_config(), and quota_process_config.
Referenced by class_config_llog_handler(), class_handle_ioctl(), class_manual_cleanup(), do_lcfg(), mgc_apply_recover_logs(), and mgs_write_log_sys().
int class_process_proc_param (char * prefix, struct lprocfs_vars * lvars, struct lustre_cfg * lcfg, void * data)
Definition at line 1322 of file obd_config.c.
References CDEBUG, CERROR, class_match_param(), D_CONFIG, ENTRY, lprocfs_vars::fops, lustre_cfg::lcfg_bufcount, lustre_cfg::lcfg_command, LCFG_PARAM, lustre_cfg_buf(), lustre_cfg_string(), lprocfs_vars::name, name, and RETURN.
Referenced by ll_process_config(), lod_process_config(), lov_process_config_base(), mdc_process_config(), mdd_process_config(), mdt_process_config(), ofd_process_config(), osc_process_config_base(), osd_process_config(), and osp_process_config().
int class_procfs_clean (void)
Definition at line 477 of file linux-module.c.
References ENTRY, lprocfs_remove(), and RETURN.
Referenced by obdclass_exit().
int class_procfs_init (void)
Definition at line 444 of file linux-module.c.
References CERROR, ENTRY, GOTO, lprocfs_register(), lprocfs_remove(), obd_sysctl_init(), and RETURN.
Referenced by obdclass_init().
void class_put_profile (struct lustre_profile * lprof)
Definition at line 941 of file obd_config.c.
References LASSERT, lustre_profile::lp_dt, lustre_profile::lp_list_deleted, lustre_profile::lp_md, lustre_profile::lp_profile, lustre_profile::lp_refs, and OBD_FREE.
Referenced by class_del_profile(), class_del_profiles(), ll_fill_super(), mdt_quota_init(), mdt_stack_init(), and server_put_super().
void class_put_type (struct obd_type * type)
Definition at line 156 of file genops.c.
References LASSERT, obd_ops::o_owner, obd_type::obd_type_lock, obd_type::typ_dt_ops, and obd_type::typ_refcnt.
Referenced by class_newdev(), class_release_dev(), and lu_stack_fini().
int class_register_type (struct obd_ops * , struct md_ops * , bool enable_proc, struct lprocfs_vars * module_vars, const char * nm, struct lu_device_type * ldt)
Definition at line 167 of file genops.c.
References CDEBUG, CLASS_MAX_NAME, class_search_type(), D_IOCTL, ENTRY, GOTO, LASSERT, list_add(), lprocfs_register(), lu_device_type_init(), OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, obd_type::obd_type_lock, obd_types, obd_types_lock, proc_lustre_root, RETURN, strnlen, obd_type::typ_chain, obd_type::typ_dt_ops, obd_type::typ_lu, obd_type::typ_md_ops, obd_type::typ_name, and obd_type::typ_procroot.
Referenced by llog_test_init(), lmv_init(), lod_init(), lov_init(), mdc_init(), mdd_init(), mds_mod_init(), mdt_init(), mgc_init(), mgs_init(), obdecho_init(), ofd_init(), osc_init(), osd_init(), osp_init(), ost_init(), and qmt_glb_init().
void class_release_dev (struct obd_device * obd)
Definition at line 381 of file genops.c.
References CDEBUG, class_put_type(), D_INFO, LASSERT, LASSERTF, obd_dev_lock, obd_device_free(), OBD_DEVICE_MAGIC, obd_devs, obd_device::obd_magic, obd_device::obd_minor, obd_device::obd_name, obd_device::obd_type, and obd_type::typ_name.
Referenced by class_attach(), and class_decref().
struct obd_type* class_search_type (const char * name) [read]
Definition at line 103 of file genops.c.
References list_entry, list_for_each, obd_types, obd_types_lock, obd_type::typ_chain, and obd_type::typ_name.
Referenced by class_get_type(), class_register_type(), class_unregister_type(), lod_init(), lov_init(), lov_setup(), mdd_procfs_init(), osc_init(), osc_setup(), osp_init(), qmt_device_init0(), and server_stop_servers().
int class_setup (struct obd_device * obd, struct lustre_cfg * lcfg)
Create hashes, self-export, and call type-specific setup.
Setup is effectively the "start this obd" call.
Definition at line 445 of file obd_config.c.
References CDEBUG, CERROR, cfs_hash_create(), CFS_HASH_DEFAULT, CFS_HASH_MAX_THETA, CFS_HASH_MIN_THETA, cfs_hash_putref(), class_export_put(), class_incref(), class_new_export(), class_num2obd(), class_unlink_export(), D_IOCTL, ENTRY, obd_export::exp_obd_chain_timed, gen_hash_ops, GOTO, HASH_GEN_BKT_BITS, HASH_GEN_CUR_BITS, HASH_GEN_MAX_BITS, HASH_NID_BKT_BITS, HASH_NID_CUR_BITS, HASH_NID_MAX_BITS, HASH_NID_STATS_BKT_BITS, HASH_NID_STATS_CUR_BITS, HASH_NID_STATS_MAX_BITS, HASH_UUID_BKT_BITS, HASH_UUID_CUR_BITS, HASH_UUID_MAX_BITS, LASSERT, LASSERTF, list_del_init(), nid_hash_ops, nid_stat_hash_ops, obd_device::obd_attached, obd_device::obd_dev_lock, OBD_DEVICE_MAGIC, obd_device::obd_gen_hash, obd_device::obd_magic, obd_device::obd_minor, obd_device::obd_name, obd_device::obd_nid_hash, obd_device::obd_nid_stats_hash, obd_device::obd_self_export, obd_device::obd_set_up, obd_setup(), obd_device::obd_starting, obd_device::obd_type, obd_device::obd_uuid, obd_device::obd_uuid_hash, RETURN, obd_type::typ_name, obd_uuid::uuid, and uuid_hash_ops.
Referenced by class_process_config(), mdt_quota_init(), and mdt_stack_init().
void class_unlink_export (struct obd_export * exp)
Definition at line 932 of file genops.c.
References cfs_hash_del(), cfs_hash_getref(), cfs_hash_putref(), class_handle_unhash(), obd_export::exp_client_uuid, obd_export::exp_gen_hash, obd_export::exp_handle, obd_export::exp_obd, obd_export::exp_obd_chain, obd_export::exp_obd_chain_timed, obd_export::exp_uuid_hash, hlist_unhashed(), LASSERT, lsd_client_data::lcd_generation, list_del_init(), list_move(), obd_device::obd_dev_lock, obd_device::obd_gen_hash, obd_device::obd_num_exports, obd_stale_export_num, obd_stale_export_put(), obd_device::obd_unlinked_exports, obd_device::obd_uuid_hash, and tg_export_data::ted_lcd.
Referenced by class_decref(), class_disconnect(), class_setup(), and tgt_clients_data_init().
int class_unregister_type (const char * nm)
Definition at line 246 of file genops.c.
References CERROR, class_search_type(), ENTRY, list_del(), lprocfs_remove(), lu_device_type_fini(), OBD_FREE, OBD_FREE_PTR, obd_types_lock, proc_lustre_root, RETURN, obd_type::typ_chain, obd_type::typ_dt_ops, obd_type::typ_lu, obd_type::typ_md_ops, obd_type::typ_name, obd_type::typ_procroot, obd_type::typ_procsym, and obd_type::typ_refcnt.
Referenced by llog_test_exit(), lmv_exit(), lod_exit(), lov_exit(), mdc_exit(), mdd_exit(), mds_mod_exit(), mdt_exit(), mgc_exit(), mgs_exit(), obdecho_exit(), obdecho_init(), ofd_exit(), osc_exit(), osc_init(), osd_exit(), osp_exit(), osp_init(), ost_exit(), and qmt_glb_fini().
int class_uuid2dev (struct obd_uuid * uuid)
Definition at line 439 of file genops.c.
References class_devno_max(), class_num2obd(), LASSERT, obd_device::obd_dev_lock, OBD_DEVICE_MAGIC, obd_device::obd_magic, obd_device::obd_uuid, and obd_uuid_equals().
Referenced by class_handle_ioctl(), and class_uuid2obd().
struct obd_device* class_uuid2obd (struct obd_uuid * uuid) [read]
Definition at line 458 of file genops.c.
References class_num2obd(), and class_uuid2dev().
Referenced by gss_svc_handle_init().
void class_uuid_unparse (class_uuid_t in, struct obd_uuid * out)
Definition at line 70 of file uuid.c.
References ARRAY_SIZE, CLASSERT, obd_uuid::uuid, uuid, and uuid_unpack().
Referenced by ll_init_sbi(), lustre_start_mgc(), lwp_setup(), osd_scrub_setup(), and osp_init0().
void dump_exports (struct obd_device * obd, int locks)
Definition at line 1565 of file genops.c.
References obd_export::exp_obd_chain, list_for_each_entry, obd_device::obd_delayed_exports, obd_device::obd_dev_lock, obd_device::obd_exports, obd_device::obd_unlinked_exports, obd_zombie_exports, obd_zombie_impexp_lock, and print_export_data().
Referenced by class_cleanup(), and obd_exports_barrier().
static enum obd_option exp_flags_from_obd (struct obd_device * obd) [inline, static]
Definition at line 314 of file obd_class.h.
References obd_device::obd_abort_recovery, obd_device::obd_fail, obd_device::obd_force, OBD_OPT_ABORT_RECOV, OBD_OPT_FAILOVER, and OBD_OPT_FORCE.
Referenced by class_decref(), class_disconnect_exports(), and class_disconnect_stale_exports().
int get_devices_count (void)
Get obd devices count.
Device in any state are counted
Return values:
obd device count
Definition at line 500 of file genops.c.
References class_devno_max(), class_num2obd(), and obd_device::obd_dev_lock.
Referenced by only_mgs_is_running().
void* kuc_alloc (int payload_len, int transport, int type)
Definition at line 1914 of file genops.c.
References kuc_len(), KUC_MAGIC, kuc_hdr::kuc_magic, kuc_hdr::kuc_msglen, kuc_hdr::kuc_msgtype, kuc_hdr::kuc_transport, and OBD_ALLOC.
Referenced by mdt_hsm_agent_send().
void kuc_free (void * p, int payload_len) [inline]
Definition at line 1933 of file genops.c.
References kuc_len(), kuc_ptr(), and OBD_FREE.
Referenced by mdt_hsm_agent_send().
int kuc_len (int payload_len)
Definition at line 1893 of file genops.c.
Referenced by kuc_alloc(), kuc_free(), and mdt_hsm_agent_send().
struct kuc_hdr* kuc_ptr (void * p) [read]
Definition at line 1903 of file genops.c.
References KUC_MAGIC, kuc_hdr::kuc_magic, and LASSERT.
Referenced by kuc_free(), and mdt_hsm_agent_send().
void la_from_obdo (struct lu_attr * la, const struct obdo * dst, u64 valid)
Definition at line 103 of file linux-obdo.c.
References LA_ATIME, lu_attr::la_atime, LA_BLOCKS, lu_attr::la_blocks, LA_CTIME, lu_attr::la_ctime, LA_FLAGS, lu_attr::la_flags, LA_GID, lu_attr::la_gid, LA_MODE, lu_attr::la_mode, LA_MTIME, lu_attr::la_mtime, LA_SIZE, lu_attr::la_size, LA_TYPE, LA_UID, lu_attr::la_uid, lu_attr::la_valid, obdo::o_atime, obdo::o_blocks, obdo::o_ctime, obdo::o_flags, obdo::o_gid, obdo::o_mode, obdo::o_mtime, obdo::o_size, obdo::o_uid, obdo::o_valid, OBD_MD_FLATIME, OBD_MD_FLBLOCKS, OBD_MD_FLCTIME, OBD_MD_FLFLAGS, OBD_MD_FLGID, OBD_MD_FLMODE, OBD_MD_FLMTIME, OBD_MD_FLSIZE, OBD_MD_FLTYPE, and OBD_MD_FLUID.
Referenced by ofd_commitrw(), ofd_echo_setattr(), ofd_preprw(), ofd_punch_hdl(), ofd_setattr_hdl(), osp_get_attr_from_reply(), out_attr_set(), out_create(), update_recovery_attr_set(), and update_recovery_create().
static int lprocfs_nid_ldlm_stats_init (struct nid_stat * tmp) [inline, static]
Definition at line 430 of file obd_class.h.
References LDLM_FIRST_OPC, LDLM_LAST_OPC, lprocfs_alloc_stats(), lprocfs_init_ldlm_stats(), lprocfs_register_stats(), LPROCFS_STATS_FLAG_NOPERCPU, nid_stat::nid_ldlm_stats, and nid_stat::nid_proc.
Referenced by mdt_export_stats_init(), mgs_export_stats_init(), and ofd_export_stats_init().
struct lustre_cfg* lustre_cfg_rename (struct lustre_cfg * cfg, const char * new_name) [read]
Rename the proc parameter in cfg with a new name new_name.
Parameters:
cfg config structure which contains the proc parameter
new_name new name of the proc parameter
Return values:
valid-pointer pointer to the newly-allocated config structure which contains the renamed proc parameter
ERR_PTR(-EINVAL) if cfg or new_name is NULL, or cfg does not contain a proc parameter
ERR_PTR(-ENOMEM) if memory allocation failure occurs
Definition at line 1033 of file obd_config.c.
References ENTRY, lustre_cfg::lcfg_command, lustre_cfg::lcfg_flags, lustre_cfg::lcfg_nal, lustre_cfg::lcfg_nid, lustre_cfg::lcfg_num, LUSTRE_CFG_BUFLEN, lustre_cfg_bufs_init(), lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_new(), lustre_cfg_string(), OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, and RETURN.
Referenced by mdt_process_config(), and ofd_process_config().
int lustre_check_exclusion (struct super_block * sb, char * svname)
Definition at line 870 of file obd_mount.c.
References CDEBUG, CWARN, D_MOUNT, ENTRY, LDD_F_SV_TYPE_OST, lustre_mount_data::lmd_dev, lustre_mount_data::lmd_exclude, lustre_mount_data::lmd_exclude_count, RETURN, and server_name2index().
Referenced by class_config_llog_handler().
int lustre_get_jobid (char * jobid)
Definition at line 130 of file class_obd.c.
References CDEBUG, cfs_get_environ(), current_comm, D_ERROR, D_INFO, ENTRY, from_kuid(), JOBSTATS_DISABLE, JOBSTATS_NODELOCAL, JOBSTATS_PROCNAME_UID, LCONSOLE_ERROR_MSG, LUSTRE_JOBID_SIZE, obd_jobid_node, obd_jobid_var, RETURN, and unlikely.
Referenced by lustre_msg_set_jobid(), and vvp_io_init().
int lustre_register_fs (void)
Definition at line 1519 of file obd_mount.c.
Referenced by obdclass_init().
int lustre_unregister_fs (void)
Definition at line 1524 of file obd_mount.c.
Referenced by obdclass_exit().
int lustre_uuid_to_peer (const char * uuid, lnet_nid_t * peer_nid, int index)
Definition at line 72 of file lustre_peer.c.
References g_uuid_list, g_uuid_lock, list_for_each_entry, obd_str2uuid(), obd_uuid_equals(), uuid_nid_data::un_nid_count, uuid_nid_data::un_nids, and uuid_nid_data::un_uuid.
Referenced by ptlrpc_uuid_to_peer().
static int md_cancel_unused (struct obd_export * exp, const struct lu_fid * fid, union ldlm_policy_data * policy, enum ldlm_mode mode, enum ldlm_cancel_flags cancel_flags, void * opaque) [inline, static]
Definition at line 1539 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by lmv_cancel_unused(), and lmv_early_cancel().
static int md_clear_open_replay_data (struct obd_export * exp, struct obd_client_handle * och) [inline, static]
Definition at line 1520 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by ll_close_inode_openhandle(), ll_migrate(), and lmv_clear_open_replay_data().
static int md_close (struct obd_export * exp, struct md_op_data * op_data, struct md_open_data * mod, struct ptlrpc_request ** request) [inline, static]
Definition at line 1304 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by ll_close_inode_openhandle(), ll_open_cleanup(), and lmv_close().
static int md_create (struct obd_export * exp, struct md_op_data * op_data, const void * data, size_t datalen, umode_t mode, uid_t uid, gid_t gid, cfs_cap_t cap_effective, __u64 rdev, struct ptlrpc_request ** request) [inline, static]
Definition at line 1316 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by ll_dir_setdirstripe(), ll_new_node(), and lmv_create().
static int md_enqueue (struct obd_export * exp, struct ldlm_enqueue_info * einfo, const union ldlm_policy_data * policy, struct lookup_intent * it, struct md_op_data * op_data, struct lustre_handle * lockh, __u64 extra_lock_flags) [inline, static]
Definition at line 1330 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by ll_file_flock(), ll_layout_refresh_locked(), ll_xattr_find_get_lock(), and lmv_enqueue().
static int md_free_lustre_md (struct obd_export * exp, struct lustre_md * md) [inline, static]
Definition at line 1462 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by client_common_fill_super(), ll_prep_inode(), and lmv_free_lustre_md().
static int md_fsync (struct obd_export * exp, const struct lu_fid * fid, struct ptlrpc_request ** request) [inline, static]
Definition at line 1411 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by ll_fsync(), and lmv_fsync().
static int md_get_fid_from_lsm (struct obd_export * exp, const struct lmv_stripe_md * lsm, const char * name, int namelen, struct lu_fid * fid) [inline, static]
Definition at line 1611 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by ll_lookup_it_finish().
static int md_get_lustre_md (struct obd_export * exp, struct ptlrpc_request * req, struct obd_export * dt_exp, struct obd_export * md_exp, struct lustre_md * md) [inline, static]
Definition at line 1450 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by client_common_fill_super(), ll_md_setattr(), ll_prep_inode(), and lmv_get_lustre_md().
static int md_get_remote_perm (struct obd_export * exp, const struct lu_fid * fid, u32 suppgid, struct ptlrpc_request ** request) [inline, static]
Definition at line 1577 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by lmv_get_remote_perm(), and lustre_check_remote_perm().
static int md_get_root (struct obd_export * exp, const char * fileset, struct lu_fid * fid) [inline, static]
Definition at line 1269 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by client_common_fill_super(), and lmv_get_root().
static int md_getattr (struct obd_export * exp, struct md_op_data * op_data, struct ptlrpc_request ** request) [inline, static]
Definition at line 1282 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by __ll_inode_revalidate(), client_common_fill_super(), ll_dir_getstripe(), ll_get_mdt_idx_by_fid(), ll_iocontrol(), ll_readlink_internal(), lmv_getattr(), and search_inode_for_lustre().
static int md_getattr_name (struct obd_export * exp, struct md_op_data * op_data, struct ptlrpc_request ** request) [inline, static]
Definition at line 1347 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by ll_dir_get_parent_fid(), ll_get_fid_by_name(), ll_lov_getstripe_ea_info(), and lmv_getattr_name().
static int md_getxattr (struct obd_export * exp, const struct lu_fid * fid, u64 valid, const char * name, const char * input, int input_size, int output_size, int flags, struct ptlrpc_request ** request) [inline, static]
Definition at line 1496 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by ll_getxattr_common(), ll_layout_fetch(), and lmv_getxattr().
static int md_init_ea_size (struct obd_export * exp, __u32 ea_size, __u32 def_ea_size) [inline, static]
Definition at line 1568 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by cl_init_ea_size(), lmv_connect_mdc(), and lmv_init_ea_size().
static int md_intent_getattr_async (struct obd_export * exp, struct md_enqueue_info * minfo) [inline, static]
Definition at line 1588 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by lmv_intent_getattr_async(), sa_lookup(), and sa_revalidate().
static int md_intent_lock (struct obd_export * exp, struct md_op_data * op_data, struct lookup_intent * it, struct ptlrpc_request ** reqp, ldlm_blocking_callback cb_blocking, __u64 extra_lock_flags) [inline, static]
Definition at line 1359 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by __ll_inode_revalidate(), ll_intent_file_open(), ll_lease_open(), ll_lookup_it(), lmv_intent_lookup(), lmv_intent_open(), lmv_intent_remote(), and lmv_revalidate_slaves().
static int md_link (struct obd_export * exp, struct md_op_data * op_data, struct ptlrpc_request ** request) [inline, static]
Definition at line 1375 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by ll_link(), and lmv_link().
static enum ldlm_mode md_lock_match (struct obd_export * exp, __u64 flags, const struct lu_fid * fid, enum ldlm_type type, union ldlm_policy_data * policy, enum ldlm_mode mode, struct lustre_handle * lockh) [inline, static]
Definition at line 1554 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by ll_have_md_lock(), ll_md_close(), ll_take_md_lock(), and lmv_lock_match().
static int md_merge_attr (struct obd_export * exp, const struct lmv_stripe_md * lsm, struct cl_attr * attr, ldlm_blocking_callback cb) [inline, static]
Definition at line 1471 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by ll_merge_md_attr(), and ll_update_lsm_md().
static int md_null_inode (struct obd_export * exp, const struct lu_fid * fid) [inline, static]
Definition at line 1293 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by ll_clear_inode(), and lmv_null_inode().
static int md_read_page (struct obd_export * exp, struct md_op_data * op_data, struct md_callback * cb_op, __u64 hash_offset, struct page ** ppage) [inline, static]
Definition at line 1424 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by ll_get_dir_page(), lmv_get_min_striped_entry(), and lmv_read_page().
static int md_rename (struct obd_export * exp, struct md_op_data * op_data, const char * old, size_t oldlen, const char * new, size_t newlen, struct ptlrpc_request ** request) [inline, static]
Definition at line 1386 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by ll_migrate(), ll_rename(), and lmv_rename().
static int md_revalidate_lock (struct obd_export * exp, struct lookup_intent * it, struct lu_fid * fid, __u64 * bits) [inline, static]
Definition at line 1599 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by ll_lookup_it_finish(), lmv_revalidate_lock(), revalidate_statahead_dentry(), sa_instantiate(), and sa_revalidate().
static int md_set_lock_data (struct obd_export * exp, __u64 * lockh, void * data, __u64 * bits) [inline, static]
Definition at line 1529 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by ll_layout_lock_set(), ll_set_lock_data(), lmv_revalidate_slaves(), and lmv_set_lock_data().
static int md_set_open_replay_data (struct obd_export * exp, struct obd_client_handle * och, struct lookup_intent * it) [inline, static]
Definition at line 1510 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by ll_och_fill(), and lmv_set_open_replay_data().
static int md_setattr (struct obd_export * exp, struct md_op_data * op_data, void * ea, size_t ealen, struct ptlrpc_request ** request) [inline, static]
Definition at line 1399 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by ll_dir_setstripe(), ll_iocontrol(), ll_md_setattr(), and lmv_setattr().
static int md_setxattr (struct obd_export * exp, const struct lu_fid * fid, u64 valid, const char * name, const char * input, int input_size, int output_size, int flags, __u32 suppgid, struct ptlrpc_request ** request) [inline, static]
Definition at line 1482 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by ll_setxattr_common(), and lmv_setxattr().
static int md_unlink (struct obd_export * exp, struct md_op_data * op_data, struct ptlrpc_request ** request) [inline, static]
Definition at line 1439 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by ll_rmdir(), ll_rmdir_entry(), ll_unlink(), and lmv_unlink().
static int md_unpackmd (struct obd_export * exp, struct lmv_stripe_md ** plsm, const union lmv_mds_md * lmm, size_t lmm_size) [inline, static]
Definition at line 1631 of file obd_class.h.
References ENTRY, EXP_CHECK_MD_OP, EXP_MD_COUNTER_INCREMENT, obd_export::exp_obd, MDP, and RETURN.
Referenced by mdc_get_lustre_md().
static int obd_add_conn (struct obd_import * imp, struct obd_uuid * uuid, int priority) [inline, static]
Definition at line 750 of file obd_class.h.
References ENTRY, obd_import::imp_obd, OBD_CHECK_DEV_ACTIVE, OBD_CHECK_DT_OP, OBD_COUNTER_INCREMENT, OBP, and RETURN.
Referenced by class_add_conn().
static int obd_cleanup (struct obd_device * obd) [inline, static]
Definition at line 620 of file obd_class.h.
References cleanup(), DECLARE_LU_VARS, ENTRY, lu_env_fini(), lu_env_init(), OBD_CHECK_DEV, OBD_CHECK_DT_OP, OBD_COUNTER_INCREMENT, obd_device::obd_lu_dev, obd_device::obd_type, OBP, RETURN, and obd_type::typ_lu.
Referenced by class_decref(), and ofd_procfs_init().
void obd_cleanup_caches (void)
Definition at line 657 of file genops.c.
References ENTRY, EXIT, import_cachep, obd_device_cachep, and obdo_cachep.
Referenced by obd_init_caches(), and obdclass_exit().
static void obd_cleanup_client_import (struct obd_device * obd) [inline, static]
Definition at line 647 of file obd_class.h.
References CDEBUG, client_obd::cl_import, client_obd::cl_sem, obd_device::cli, client_destroy_import(), D_CONFIG, ENTRY, EXIT, obd_device::obd_name, ptlrpc_invalidate_import(), and obd_device::u.
Referenced by client_obd_cleanup(), mdc_precleanup(), mgc_precleanup(), and osc_precleanup().
static int obd_commitrw (const struct lu_env * env, int cmd, struct obd_export * exp, struct obdo * oa, int objcount, struct obd_ioobj * obj, struct niobuf_remote * rnb, int pages, struct niobuf_local * local, int rc) [inline, static]
Definition at line 1116 of file obd_class.h.
References ENTRY, EXP_CHECK_DT_OP, EXP_COUNTER_INCREMENT, obd_export::exp_obd, OBP, and RETURN.
Referenced by echo_client_prep_commit(), tgt_brw_read(), and tgt_brw_write().
static int obd_connect (const struct lu_env * env, struct obd_export ** exp, struct obd_device * obd, struct obd_uuid * cluuid, struct obd_connect_data * data, void * localdata) [inline, static]
Create a new /a exp on device /a obd for the uuid /a cluuid.
Parameters:
exp New export handle
d Connect data, supported flags are set, flags also understood by obd are returned.
Definition at line 796 of file obd_class.h.
References __u64, ENTRY, ergo, LASSERT, OBD_CHECK_DEV_ACTIVE, OBD_CHECK_DT_OP, OBD_COUNTER_INCREMENT, OBP, obd_connect_data::ocd_connect_flags, and RETURN.
Referenced by client_common_fill_super(), echo_client_setup(), llog_test_6(), lmv_connect_mdc(), lod_add_device(), lod_connect_to_osd(), lov_connect_obd(), lov_set_osc_active(), lustre_lwp_connect(), lustre_start_mgc(), mdd_connect_to_next(), mdt_connect_to_next(), mdt_quota_init(), mgs_connect_to_osd(), ofd_connect_to_next(), osd_start(), osp_connect_to_osd(), and qmt_connect_to_osd().
int obd_connect_flags2str (char * page, int count, __u64 flags, char * sep)
Referenced by client_common_fill_super().
static int obd_create (const struct lu_env * env, struct obd_export * exp, struct obdo * obdo) [inline, static]
Definition at line 698 of file obd_class.h.
References ENTRY, EXP_CHECK_DT_OP, EXP_COUNTER_INCREMENT, obd_export::exp_obd, OBP, and RETURN.
Referenced by echo_create_object().
static int obd_del_conn (struct obd_import * imp, struct obd_uuid * uuid) [inline, static]
Definition at line 765 of file obd_class.h.
References ENTRY, obd_import::imp_obd, OBD_CHECK_DEV_ACTIVE, OBD_CHECK_DT_OP, OBD_COUNTER_INCREMENT, OBP, and RETURN.
Referenced by class_del_conn().
static int obd_destroy (const struct lu_env * env, struct obd_export * exp, struct obdo * obdo) [inline, static]
Definition at line 711 of file obd_class.h.
References ENTRY, EXP_CHECK_DT_OP, EXP_COUNTER_INCREMENT, obd_export::exp_obd, OBP, and RETURN.
Referenced by echo_client_iocontrol(), and echo_create_object().
static int obd_destroy_export (struct obd_export * exp) [inline, static]
Definition at line 985 of file obd_class.h.
References ENTRY, obd_export::exp_obd, OBP, OBT, and RETURN.
Referenced by class_export_destroy(), and class_new_export().
static int obd_disconnect (struct obd_export * exp) [inline, static]
Definition at line 842 of file obd_class.h.
References ENTRY, EXP_CHECK_DT_OP, EXP_COUNTER_INCREMENT, obd_export::exp_obd, OBP, and RETURN.
Referenced by class_disconnect_export_list(), class_fail_export(), client_common_fill_super(), client_common_put_super(), echo_client_cleanup(), llog_test_6(), lmv_check_connect(), lmv_connect_mdc(), lmv_disconnect_mdc(), lod_add_device(), lod_init0(), lod_process_config(), lod_putref(), lov_disconnect_obd(), lustre_put_lsi(), lustre_stop_mgc(), mdd_device_shutdown(), mdd_init0(), mdt_quota_fini(), mdt_stack_fini(), mdt_tgt_connect(), mgs_device_fini(), mgs_init0(), ofd_stack_fini(), osp_device_fini(), osp_init0(), qmt_device_fini(), and tgt_connect().
int obd_export_evict_by_nid (struct obd_device * obd, const char * nid)
Definition at line 1442 of file genops.c.
References ptlrpc_connection::c_peer, CDEBUG, cfs_hash_getref(), cfs_hash_lookup(), cfs_hash_putref(), class_export_put(), class_fail_export(), D_HA, obd_export::exp_client_uuid, obd_export::exp_connection, LASSERTF, LCONSOLE_WARN, libcfs_nid2str(), libcfs_str2nid(), lnet_process_id_t::nid, nid_hash(), nid_key(), obd_device::obd_dev_lock, obd_export_nid2str(), obd_device::obd_name, obd_device::obd_nid_hash, obd_device::obd_self_export, obd_device::obd_stopping, and obd_uuid2str().
Referenced by lprocfs_mds_evict_client_seq_write(), mdt_set_info(), and ofd_set_info_hdl().
int obd_export_evict_by_uuid (struct obd_device * obd, const char * uuid)
Definition at line 1490 of file genops.c.
References CERROR, cfs_hash_getref(), cfs_hash_lookup(), cfs_hash_putref(), class_export_put(), class_fail_export(), CWARN, obd_export::exp_client_uuid, obd_device::obd_dev_lock, obd_device::obd_name, obd_device::obd_stopping, obd_str2uuid(), obd_device::obd_uuid, obd_uuid_equals(), obd_device::obd_uuid_hash, obd_uuid::uuid, and uuid_hash().
char* obd_export_nid2str (struct obd_export * exp)
Definition at line 1433 of file genops.c.
References ptlrpc_connection::c_peer, obd_export::exp_connection, libcfs_nid2str(), and lnet_process_id_t::nid.
Referenced by class_disconnect_export_list(), mdt_reconstruct_create(), mdt_reconstruct_open(), mdt_reconstruct_setattr(), mgs_target_reg(), obd_export_evict_by_nid(), ofd_echo_setattr(), ofd_parse_connect_data(), ofd_setattr_hdl(), ping_evictor_main(), print_export_data(), ptlrpc_update_export_timer(), tgt_brw_read(), tgt_brw_write(), tgt_io_data_unpack(), and tgt_validate_obdo().
void obd_exports_barrier (struct obd_device * obd)
Definition at line 1583 of file genops.c.
References cfs_time_seconds(), dump_exports(), LASSERT, LCONSOLE_WARN, list_empty(), obd_device::obd_dev_lock, obd_device::obd_exports, obd_device::obd_name, obd_device::obd_refcount, and obd_device::obd_unlinked_exports.
Referenced by mdt_fini(), mgs_device_fini(), and ofd_fini().
static int obd_fid_alloc (const struct lu_env * env, struct obd_export * exp, struct lu_fid * fid, struct md_op_data * op_data) [inline, static]
Definition at line 879 of file obd_class.h.
References ENTRY, EXP_CHECK_DT_OP, EXP_COUNTER_INCREMENT, obd_export::exp_obd, OBP, and RETURN.
Referenced by __lmv_fid_alloc(), llog_osd_open(), and lod_prep_md_striped_create().
static int obd_fid_fini (struct obd_device * obd) [inline, static]
Definition at line 867 of file obd_class.h.
References ENTRY, OBD_CHECK_DT_OP, OBD_COUNTER_INCREMENT, OBP, and RETURN.
Referenced by client_common_fill_super(), client_common_put_super(), lmv_disconnect_mdc(), osp_init0(), and osp_shutdown().
static int obd_fid_init (struct obd_device * obd, struct obd_export * exp, enum lu_cli_type type) [inline, static]
Definition at line 854 of file obd_class.h.
References ENTRY, fid_init(), OBD_CHECK_DT_OP, OBD_COUNTER_INCREMENT, OBP, and RETURN.
Referenced by client_common_fill_super(), lmv_connect_mdc(), and osp_init0().
static int obd_get_info (const struct lu_env * env, struct obd_export * exp, __u32 keylen, void * key, __u32 * vallen, void * val) [inline, static]
Definition at line 505 of file obd_class.h.
References ENTRY, EXP_CHECK_DT_OP, EXP_COUNTER_INCREMENT, obd_export::exp_obd, OBP, and RETURN.
Referenced by cl_init_ea_size(), client_common_fill_super(), ll_dir_ioctl(), ll_get_default_mdsize(), ll_get_max_mdsize(), lmv_get_info(), lod_obd_get_info(), lustre_start_mgc(), mdc_ioc_fid2path(), mdd_obd_get_info(), and mdt_obd_connect().
__u16 obd_get_max_mod_rpcs_in_flight (struct client_obd * cli)
Definition at line 2090 of file genops.c.
References client_obd::cl_max_mod_rpcs_in_flight.
__u32 obd_get_max_rpcs_in_flight (struct client_obd * cli)
Definition at line 2032 of file genops.c.
References client_obd::cl_max_rpcs_in_flight.
__u16 obd_get_mod_rpc_slot (struct client_obd * cli, __u32 opc, struct lookup_intent * it)
Definition at line 2229 of file genops.c.
References CDEBUG, client_obd::cl_close_rpcs_in_flight, client_obd::cl_import, client_obd::cl_max_mod_rpcs_in_flight, client_obd::cl_mod_rpcs_hist, client_obd::cl_mod_rpcs_in_flight, client_obd::cl_mod_rpcs_lock, client_obd::cl_mod_rpcs_waitq, client_obd::cl_mod_tag_bitmap, D_RPCTRACE, obd_import::imp_obd, IT_GETATTR, IT_LAYOUT, IT_LOOKUP, lookup_intent::it_op, IT_READDIR, l_wait_event, LASSERT, lprocfs_oh_tally(), LWI_INTR, max, MDS_CLOSE, OBD_MAX_RIF_MAX, obd_mod_rpc_slot_avail(), obd_mod_rpc_slot_avail_locked(), and obd_device::obd_name.
Referenced by mdc_get_mod_rpc_slot().
int obd_get_request_slot (struct client_obd * cli)
Definition at line 1965 of file genops.c.
References client_obd::cl_loi_list_lock, client_obd::cl_loi_read_list, client_obd::cl_max_rpcs_in_flight, client_obd::cl_r_in_flight, l_wait_event, LASSERT, list_add_tail(), list_del(), list_empty(), LWI_INTR, LWI_ON_SIGNAL_NOOP, obd_request_slot_avail(), obd_request_slot_waiter::orsw_entry, obd_request_slot_waiter::orsw_signaled, and obd_request_slot_waiter::orsw_waitq.
Referenced by fld_client_rpc(), mdc_enqueue(), mdc_intent_getattr_async(), mdc_queue_wait(), and osp_send_update_req().
static struct obd_uuid* obd_get_uuid (struct obd_export * exp) [static, read]
Definition at line 779 of file obd_class.h.
References ENTRY, EXP_COUNTER_INCREMENT, obd_export::exp_obd, OBD_CHECK_DT_OP, OBP, RETURN, and uuid.
Referenced by client_common_fill_super(), and lmv_get_uuid().
static int obd_getattr (const struct lu_env * env, struct obd_export * exp, struct obdo * oa) [inline, static]
Definition at line 724 of file obd_class.h.
References ENTRY, EXP_CHECK_DT_OP, EXP_COUNTER_INCREMENT, obd_export::exp_obd, OBP, and RETURN.
Referenced by echo_client_iocontrol().
static void obd_getref (struct obd_device * obd) [inline, static]
Definition at line 954 of file obd_class.h.
References ENTRY, EXIT, OBD_COUNTER_INCREMENT, OBP, and OBT.
Referenced by cb_statfs_update(), lov_add_target(), lov_cl_add_target(), lov_cleanup(), lov_connect(), lov_del_target(), lov_disconnect(), lov_get_info(), lov_notify(), lov_pool_add(), lov_pool_remove(), lov_process_config(), lov_quotactl(), lov_set_info_async(), and lov_set_osc_active().
static int obd_health_check (const struct lu_env * env, struct obd_device * obd) [inline, static]
Definition at line 1226 of file obd_class.h.
References CERROR, ENTRY, obd_device::obd_set_up, obd_device::obd_stopping, OBP, OBT, and RETURN.
static void obd_import_event (struct obd_device * obd, struct obd_import * imp, enum obd_import_event event) [inline, static]
Definition at line 1145 of file obd_class.h.
References CERROR, ENTRY, EXIT, OBD_COUNTER_INCREMENT, obd_device::obd_set_up, and OBP.
int obd_init_caches (void)
Definition at line 676 of file genops.c.
References ENTRY, GOTO, import_cachep, LASSERT, obd_cleanup_caches(), obd_device_cachep, obdo_cachep, and RETURN.
Referenced by obdclass_init().
static int obd_init_export (struct obd_export * exp) [inline, static]
Definition at line 974 of file obd_class.h.
References ENTRY, obd_export::exp_obd, OBP, OBT, and RETURN.
Referenced by class_new_export().
static int obd_iocontrol (unsigned int cmd, struct obd_export * exp, int len, void * karg, void __user * uarg) [inline, static]
Definition at line 1132 of file obd_class.h.
References ENTRY, EXP_CHECK_DT_OP, EXP_COUNTER_INCREMENT, obd_export::exp_obd, OBP, and RETURN.
Referenced by class_cleanup(), class_handle_ioctl(), copy_and_ioctl(), get_hsm_state(), ll_dir_ioctl(), ll_fid2path(), ll_file_ioctl(), ll_hsm_state_set(), ll_ioc_copy_end(), ll_ioc_copy_start(), ll_layout_restore(), ll_obd_statfs(), ll_swap_layouts(), ll_umount_begin(), lmv_fid2path(), lmv_hsm_ct_register(), lmv_hsm_ct_unregister(), lmv_iocontrol(), lov_iocontrol(), quotactl_ioctl(), and server_start_targets().
int obd_mod_rpc_stats_seq_show (struct client_obd * cli, struct seq_file * seq)
Definition at line 2146 of file genops.c.
References client_obd::cl_mod_rpcs_hist, client_obd::cl_mod_rpcs_in_flight, client_obd::cl_mod_rpcs_lock, lprocfs_oh_sum(), OBD_HIST_MAX, obd_histogram::oh_buckets, and pct.
static int obd_notify (struct obd_device * obd, struct obd_device * watched, enum obd_notify_event ev, void * data) [inline, static]
Definition at line 1162 of file obd_class.h.
References CDEBUG, D_HA, ENTRY, OBD_CHECK_DEV, OBD_COUNTER_INCREMENT, obd_device::obd_name, obd_device::obd_set_up, OBP, and RETURN.
Referenced by lmv_connect_mdc(), lmv_notify(), lov_add_target(), obd_notify_observer(), and server_start_targets().
static int obd_notify_observer (struct obd_device * observer, struct obd_device * observed, enum obd_notify_event ev, void * data) [inline, static]
Definition at line 1186 of file obd_class.h.
References obd_notify(), obd_device::obd_observer, obd_device::obd_upcall, obd_notify_upcall::onu_owner, and obd_notify_upcall::onu_upcall.
Referenced by lov_notify(), mdc_import_event(), and osc_import_event().
static int obd_ping (const struct lu_env * env, struct obd_export * exp) [inline, static]
Definition at line 894 of file obd_class.h.
References ENTRY, EXP_COUNTER_INCREMENT, obd_export::exp_obd, OBD_CHECK_DT_OP, OBP, and RETURN.
static int obd_pool_add (struct obd_device * obd, char * poolname, char * ostname) [inline, static]
Definition at line 930 of file obd_class.h.
References ENTRY, OBD_CHECK_DT_OP, OBD_COUNTER_INCREMENT, OBP, and RETURN.
Referenced by class_process_config().
static int obd_pool_del (struct obd_device * obd, char * poolname) [inline, static]
Definition at line 918 of file obd_class.h.
References ENTRY, OBD_CHECK_DT_OP, OBD_COUNTER_INCREMENT, OBP, and RETURN.
Referenced by class_process_config().
static int obd_pool_new (struct obd_device * obd, char * poolname) [inline, static]
Definition at line 906 of file obd_class.h.
References ENTRY, OBD_CHECK_DT_OP, OBD_COUNTER_INCREMENT, OBP, and RETURN.
Referenced by class_process_config().
static int obd_pool_rem (struct obd_device * obd, char * poolname, char * ostname) [inline, static]
Definition at line 942 of file obd_class.h.
References ENTRY, OBD_CHECK_DT_OP, OBD_COUNTER_INCREMENT, OBP, and RETURN.
Referenced by class_process_config().
static int obd_precleanup (struct obd_device * obd) [inline, static]
Definition at line 595 of file obd_class.h.
References DECLARE_LU_VARS, ENTRY, lu_env_fini(), lu_env_init(), OBD_CHECK_DEV, OBD_CHECK_DT_OP, OBD_COUNTER_INCREMENT, obd_device::obd_lu_dev, obd_device::obd_type, OBP, RETURN, and obd_type::typ_lu.
Referenced by class_cleanup().
static int obd_preprw (const struct lu_env * env, int cmd, struct obd_export * exp, struct obdo * oa, int objcount, struct obd_ioobj * obj, struct niobuf_remote * remote, int * pages, struct niobuf_local * local) [inline, static]
Definition at line 1099 of file obd_class.h.
References ENTRY, EXP_CHECK_DT_OP, EXP_COUNTER_INCREMENT, obd_export::exp_obd, OBP, and RETURN.
Referenced by echo_client_prep_commit(), tgt_brw_read(), and tgt_brw_write().
static int obd_process_config (struct obd_device * obd, int datalen, void * data) [inline, static]
Definition at line 669 of file obd_class.h.
References DECLARE_LU_VARS, ENTRY, lu_env_fini(), lu_env_init(), OBD_CHECK_DEV, OBD_CHECK_DT_OP, OBD_COUNTER_INCREMENT, obd_device::obd_lu_dev, obd_device::obd_process_conf, obd_device::obd_type, OBP, RETURN, and obd_type::typ_lu.
Referenced by class_process_config(), lustre_end_log(), and lustre_process_log().
void obd_put_mod_rpc_slot (struct client_obd * cli, __u32 opc, struct lookup_intent * it, __u16 tag)
Definition at line 2281 of file genops.c.
References client_obd::cl_close_rpcs_in_flight, client_obd::cl_mod_rpcs_in_flight, client_obd::cl_mod_rpcs_lock, client_obd::cl_mod_rpcs_waitq, client_obd::cl_mod_tag_bitmap, IT_GETATTR, IT_LAYOUT, IT_LOOKUP, lookup_intent::it_op, IT_READDIR, LASSERT, MDS_CLOSE, and OBD_MAX_RIF_MAX.
Referenced by mdc_put_mod_rpc_slot().
void obd_put_request_slot (struct client_obd * cli)
Definition at line 2012 of file genops.c.
References client_obd::cl_loi_list_lock, client_obd::cl_loi_read_list, client_obd::cl_max_rpcs_in_flight, client_obd::cl_r_in_flight, likely, list_del_init(), list_empty(), list_entry, list_head::next, obd_request_slot_waiter::orsw_entry, and obd_request_slot_waiter::orsw_waitq.
Referenced by fld_client_rpc(), mdc_enqueue(), mdc_intent_getattr_async(), mdc_intent_getattr_async_interpret(), mdc_queue_wait(), and osp_update_interpret().
static void obd_putref (struct obd_device * obd) [inline, static]
Definition at line 964 of file obd_class.h.
References ENTRY, EXIT, OBD_COUNTER_INCREMENT, OBP, and OBT.
Referenced by cb_statfs_update(), lov_add_target(), lov_cl_add_target(), lov_cleanup(), lov_connect(), lov_del_target(), lov_disconnect(), lov_get_info(), lov_notify(), lov_pool_add(), lov_pool_remove(), lov_process_config(), lov_quotactl(), lov_set_info_async(), and lov_set_osc_active().
static int obd_quotactl (struct obd_export * exp, struct obd_quotactl * oqctl) [inline, static]
Definition at line 1213 of file obd_class.h.
References ENTRY, EXP_CHECK_DT_OP, EXP_COUNTER_INCREMENT, obd_export::exp_obd, OBP, and RETURN.
Referenced by lmv_iocontrol(), lmv_quotactl(), lov_iocontrol(), lov_quotactl(), mdc_iocontrol(), and quotactl_ioctl().
static int obd_reconnect (const struct lu_env * env, struct obd_export * exp, struct obd_device * obd, struct obd_uuid * cluuid, struct obd_connect_data * d, void * localdata) [inline, static]
Definition at line 818 of file obd_class.h.
References __u64, ENTRY, ergo, LASSERT, OBD_CHECK_DEV_ACTIVE, OBD_CHECK_DT_OP, OBD_COUNTER_INCREMENT, OBP, obd_connect_data::ocd_connect_flags, and RETURN.
Referenced by ptlrpc_connect_import().
static int obd_register_observer (struct obd_device * obd, struct obd_device * observer) [inline, static]
Definition at line 1253 of file obd_class.h.
References ENTRY, OBD_CHECK_DEV, obd_device::obd_observer, obd_device::obd_observer_link_sem, and RETURN.
Referenced by lmv_connect_mdc(), lmv_disconnect_mdc(), lov_connect_obd(), and lov_disconnect_obd().
static int obd_set_info_async (const struct lu_env * env, struct obd_export * exp, __u32 keylen, void * key, __u32 vallen, void * val, struct ptlrpc_request_set * set) [inline, static]
Definition at line 519 of file obd_class.h.
References ENTRY, EXP_CHECK_DT_OP, EXP_COUNTER_INCREMENT, obd_export::exp_obd, OBP, and RETURN.
Referenced by class_notify_sptlrpc_conf(), client_common_fill_super(), ldlm_handle_setinfo(), ll_flush_ctx(), ll_remount_fs(), ll_send_mgc_param(), ll_set_default_mdsize(), lmv_set_info_async(), lod_obd_set_info_async(), lov_add_target(), lov_set_info_async(), lprocfs_mds_evict_client_seq_write(), lustre_start_mgc(), mdc_iocontrol(), mdd_obd_set_info_async(), server_mgc_clear_fs(), server_mgc_set_fs(), server_notify_target(), and server_register_target().
int obd_set_max_mod_rpcs_in_flight (struct client_obd * cli, __u16 max)
Definition at line 2096 of file genops.c.
References CERROR, client_obd::cl_import, client_obd::cl_max_mod_rpcs_in_flight, client_obd::cl_max_rpcs_in_flight, client_obd::cl_mod_rpcs_lock, client_obd::cl_mod_rpcs_waitq, obd_import::imp_connect_data, obd_import::imp_obd, OBD_CONNECT_MULTIMODRPCS, OBD_MAX_RIF_MAX, obd_device::obd_name, obd_connect_data::ocd_connect_flags, and obd_connect_data::ocd_maxmodrpcs.
Referenced by obd_set_max_rpcs_in_flight().
int obd_set_max_rpcs_in_flight (struct client_obd * cli, __u32 max)
Definition at line 2038 of file genops.c.
References CERROR, client_obd::cl_import, client_obd::cl_loi_list_lock, client_obd::cl_loi_read_list, client_obd::cl_max_rpcs_in_flight, client_obd::cl_r_in_flight, obd_import::imp_obd, list_del_init(), list_empty(), list_entry, LUSTRE_MDC_NAME, list_head::next, OBD_MAX_RIF_MAX, obd_device::obd_name, obd_set_max_mod_rpcs_in_flight(), obd_device::obd_type, obd_request_slot_waiter::orsw_entry, obd_request_slot_waiter::orsw_waitq, and obd_type::typ_name.
static int obd_setattr (const struct lu_env * env, struct obd_export * exp, struct obdo * oa) [inline, static]
Definition at line 737 of file obd_class.h.
References ENTRY, EXP_CHECK_DT_OP, EXP_COUNTER_INCREMENT, obd_export::exp_obd, OBP, and RETURN.
Referenced by echo_client_iocontrol().
static int obd_setup (struct obd_device * obd, struct lustre_cfg * cfg) [inline, static]
Definition at line 558 of file obd_class.h.
References DECLARE_LU_VARS, ENTRY, lu_context::lc_thread, LCT_SERVER_SESSION, LCT_SESSION, lu_device::ld_obd, lu_env::le_ses, lu_context_enter(), lu_context_exit(), lu_context_fini(), lu_context_init(), lu_env_fini(), lu_env_init(), OBD_CHECK_DT_OP, OBD_COUNTER_INCREMENT, obd_device::obd_lu_dev, obd_device::obd_type, OBP, RETURN, and obd_type::typ_lu.
Referenced by class_setup().
void obd_stale_export_adjust (struct obd_export * exp)
Adjust the position of the export in the stale list, i.e.
move to the head of the list if is needed.
Definition at line 1812 of file genops.c.
References obd_export::exp_bl_list, obd_export::exp_bl_list_lock, obd_export::exp_stale_list, LASSERT, list_empty(), list_move(), obd_stale_export_lock, and obd_stale_exports.
struct obd_export* obd_stale_export_get (void) [read]
Definition at line 1757 of file genops.c.
References CDEBUG, D_DLMTRACE, ENTRY, obd_export::exp_stale_list, list_del_init(), list_empty(), list_entry, list_head::next, obd_stale_export_lock, obd_stale_export_num, obd_stale_exports, and RETURN.
Referenced by ldlm_bl_get_work().
void obd_stale_export_put (struct obd_export * exp)
Definition at line 1778 of file genops.c.
References CDEBUG, class_export_put(), D_DLMTRACE, ENTRY, EXIT, obd_export::exp_bl_list, obd_export::exp_bl_list_lock, obd_export::exp_lock_hash, obd_export::exp_stale_list, cfs_hash::hs_count, LASSERT, list_add(), list_add_tail(), list_empty(), obd_stale_export_lock, obd_stale_export_num, and obd_stale_exports.
Referenced by class_unlink_export(), ldlm_bl_get_work(), and ldlm_bl_thread_exports().
static int obd_statfs (const struct lu_env * env, struct obd_export * exp, struct obd_statfs * osfs, __u64 max_age, __u32 flags) [inline, static]
Definition at line 1062 of file obd_class.h.
References CDEBUG, cfs_time_before_64(), cfs_time_current_64, D_SUPER, ENTRY, obd_export::exp_obd, LPU64, OBD_CHECK_DT_OP, OBD_COUNTER_INCREMENT, obd_device::obd_name, obd_device::obd_osfs, obd_device::obd_osfs_age, obd_device::obd_osfs_lock, OBP, obd_statfs::os_bavail, obd_statfs::os_blocks, obd_statfs::os_ffree, obd_statfs::os_files, and RETURN.
Referenced by client_common_fill_super(), ll_statfs_internal(), lmv_iocontrol(), lmv_statfs(), and lov_iocontrol().
static int obd_statfs_async (struct obd_export * exp, struct obd_info * oinfo, __u64 max_age, struct ptlrpc_request_set * rqset) [inline, static]
Definition at line 997 of file obd_class.h.
References CDEBUG, cfs_time_before_64(), D_SUPER, ENTRY, obd_export::exp_obd, LPU64, OBD_CHECK_DT_OP, OBD_COUNTER_INCREMENT, obd_device::obd_name, obd_device::obd_osfs, obd_device::obd_osfs_age, obd_device::obd_osfs_lock, OBD_STATFS_FROM_CACHE, OBP, obd_info::oi_cb_up, obd_info::oi_flags, obd_info::oi_osfs, obd_statfs::os_bavail, obd_statfs::os_blocks, obd_statfs::os_ffree, obd_statfs::os_files, and RETURN.
Referenced by lov_statfs_async(), and obd_statfs_rqset().
static int obd_statfs_rqset (struct obd_export * exp, struct obd_statfs * osfs, __u64 max_age, __u32 flags) [inline, static]
Definition at line 1033 of file obd_class.h.
References ENTRY, obd_statfs_async(), obd_info::oi_osfs, ptlrpc_prep_set(), ptlrpc_set_destroy(), ptlrpc_set_wait(), and RETURN.
Referenced by ll_statfs_internal().
void obd_sysctl_clean (void)
Definition at line 313 of file linux-sysctl.c.
Referenced by obdclass_exit().
void obd_sysctl_init (void)
Definition at line 305 of file linux-sysctl.c.
Referenced by class_procfs_init().
void obd_zombie_barrier (void)
wait when obd_zombie import/export queues become empty
Definition at line 1745 of file genops.c.
References current_pid, l_wait_event, and obd_zombie_is_idle().
Referenced by lustre_fill_super(), lustre_put_lsi(), mdt_fini(), mgs_device_fini(), ofd_fini(), osc_precleanup(), and server_put_super().
void obd_zombie_impexp_cull (void)
kill zombie imports and exports
Definition at line 1613 of file genops.c.
References class_export_destroy(), class_import_destroy(), ENTRY, EXIT, obd_export::exp_obd_chain, list_del_init(), list_empty(), list_entry, list_head::next, obd_zombie_exports, obd_zombie_impexp_lock, and obd_zombie_imports.
Referenced by obd_zombie_impexp_thread().
int obd_zombie_impexp_init (void)
start destroy zombie import/export thread
Definition at line 1860 of file genops.c.
References INIT_LIST_HEAD, obd_zombie_exports, obd_zombie_impexp_lock, obd_zombie_impexp_thread(), obd_zombie_imports, obd_zombie_start, obd_zombie_stop, and RETURN.
Referenced by obdclass_init().
void obd_zombie_impexp_stop (void)
stop destroy zombie import/export thread
Definition at line 1883 of file genops.c.
References obd_zombie_impexp_notify(), obd_zombie_stop, and OBD_ZOMBIE_STOP.
Referenced by obdclass_exit().
void obdo_cpy_md (struct obdo * dst, const struct obdo * src, u64 valid)
Definition at line 122 of file obdo.c.
References CDEBUG, D_INODE, DOSTID, LPX64, obdo::o_atime, obdo::o_blksize, obdo::o_blocks, obdo::o_ctime, obdo::o_flags, obdo::o_gid, obdo::o_handle, obdo::o_mode, obdo::o_mtime, obdo::o_oi, obdo::o_parent_oid, obdo::o_parent_seq, obdo::o_parent_ver, obdo::o_size, obdo::o_uid, obdo::o_valid, OBD_MD_FLATIME, OBD_MD_FLBLKSZ, OBD_MD_FLBLOCKS, OBD_MD_FLCTIME, OBD_MD_FLFID, OBD_MD_FLFLAGS, OBD_MD_FLGENER, OBD_MD_FLGID, OBD_MD_FLHANDLE, OBD_MD_FLMODE, OBD_MD_FLMTIME, OBD_MD_FLSIZE, OBD_MD_FLTYPE, OBD_MD_FLUID, and POSTID.
Referenced by echo_getattr().
void obdo_from_la (struct obdo * dst, const struct lu_attr * la, u64 valid)
Definition at line 52 of file linux-obdo.c.
References lu_attr::la_atime, LA_ATIME, lu_attr::la_blocks, LA_BLOCKS, lu_attr::la_ctime, LA_CTIME, lu_attr::la_flags, LA_FLAGS, lu_attr::la_gid, LA_GID, LA_MODE, lu_attr::la_mode, lu_attr::la_mtime, LA_MTIME, lu_attr::la_size, LA_SIZE, LA_TYPE, lu_attr::la_uid, LA_UID, obdo::o_atime, obdo::o_blocks, obdo::o_ctime, obdo::o_flags, obdo::o_gid, obdo::o_mode, obdo::o_mtime, obdo::o_size, obdo::o_uid, obdo::o_valid, OBD_MD_FLATIME, OBD_MD_FLBLOCKS, OBD_MD_FLCTIME, OBD_MD_FLFLAGS, OBD_MD_FLGID, OBD_MD_FLMODE, OBD_MD_FLMTIME, OBD_MD_FLSIZE, OBD_MD_FLTYPE, and OBD_MD_FLUID.
Referenced by ofd_commitrw(), ofd_echo_getattr(), ofd_getattr_hdl(), ofd_preprw(), ofd_setattr_hdl(), ofd_sync_hdl(), out_attr_get(), out_attr_set_pack(), out_create_pack(), update_records_attr_set_pack(), and update_records_create_pack().
void obdo_to_ioobj (const struct obdo * oa, struct obd_ioobj * ioobj)
Definition at line 161 of file obdo.c.
References obd_ioobj::ioo_max_brw, obd_ioobj::ioo_oid, obdo::o_oi, obdo::o_valid, OBD_MD_FLGROUP, ostid_set_seq_mdt0(), and unlikely.
Referenced by echo_client_prep_commit(), and osc_brw_prep_request().
int server_name2index (const char * svname, __u32 * idx, const char ** endptr)
Definition at line 790 of file obd_mount.c.
References LUSTRE_MDC_NAME, server_name2fsname(), and target_name2index().
Referenced by class_config_llog_handler(), lmd_make_exclusion(), lsi_prepare(), lustre_check_exclusion(), mgs_fsdb_handler(), mgs_parse_devname(), mgs_setparam(), mgs_write_log_param(), osd_device_init0(), qsd_init(), server_lsi2mti(), tgt_is_mdt(), and tgt_server_data_init().
void statfs_pack (struct obd_statfs * osfs, struct kstatfs * sfs)
Definition at line 51 of file statfs_pack.c.
References obd_statfs::os_bavail, obd_statfs::os_bfree, obd_statfs::os_blocks, obd_statfs::os_bsize, obd_statfs::os_ffree, obd_statfs::os_files, obd_statfs::os_namelen, and obd_statfs::os_type.
Referenced by osd_statfs().
void statfs_unpack (struct kstatfs * sfs, struct obd_statfs * osfs)
Definition at line 65 of file statfs_pack.c.
References obd_statfs::os_bavail, obd_statfs::os_bfree, obd_statfs::os_blocks, obd_statfs::os_bsize, obd_statfs::os_ffree, obd_statfs::os_files, obd_statfs::os_namelen, and obd_statfs::os_type.
Referenced by ll_statfs(), and server_statfs().
Variable Documentation
rwlock_t obd_dev_lock
Referenced by class_name2dev(), class_newdev(), and class_release_dev().
struct obd_device* obd_devs[MAX_OBD_DEVICES]
Definition at line 60 of file class_obd.c.
Referenced by class_newdev(), class_num2obd(), and class_release_dev().
char obd_jobid_node[]
Definition at line 116 of file class_obd.c.
Referenced by lustre_get_jobid().
struct miscdevice obd_psdev
Definition at line 207 of file linux-module.c.
Referenced by obdclass_exit(), and obdclass_init().
spinlock_t obd_stale_export_lock
Definition at line 68 of file genops.c.
Referenced by obd_stale_export_adjust(), obd_stale_export_get(), obd_stale_export_put(), and obdclass_init().
atomic_t obd_stale_export_num
Definition at line 69 of file genops.c.
Referenced by class_unlink_export(), obd_stale_export_get(), obd_stale_export_put(), obd_zombie_export_add(), and obdclass_init().
struct list_head obd_stale_exports
Definition at line 67 of file genops.c.
Referenced by obd_stale_export_adjust(), obd_stale_export_get(), obd_stale_export_put(), obdclass_exit(), and obdclass_init().
struct list_head obd_types
Definition at line 61 of file class_obd.c.
Referenced by class_register_type(), class_search_type(), lfs_check(), and obdclass_init().
spinlock_t obd_types_lock
Definition at line 50 of file genops.c.
Referenced by class_register_type(), class_search_type(), class_unregister_type(), lu_device_type_fini(), lu_device_type_init(), and obdclass_init().
struct kmem_cache* obdo_cachep
Definition at line 53 of file genops.c.
Referenced by obd_cleanup_caches(), and obd_init_caches().
int(* ptlrpc_put_connection_superhack)(struct ptlrpc_connection *c)
Referenced by class_export_destroy(), class_import_destroy(), and ptlrpc_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.