Lustre: lustre/obdclass/obd_mount_server.c File Reference
lustre/obdclass/obd_mount_server.c File Reference
#include <linux/types.h>
#include <linux/selinux.h>
#include <linux/statfs.h>
#include <linux/version.h>
#include <lustre/lustre_idl.h>
#include <lustre/lustre_user.h>
#include <llog_swab.h>
#include <lustre_disk.h>
#include <lustre_ioctl.h>
#include <lustre_log.h>
#include <lustre_param.h>
#include <obd.h>
#include <obd_class.h>
Defines
#define DEBUG_SUBSYSTEM S_CLASS
#define D_MOUNT (D_SUPER | D_CONFIG /* | D_WARNING */)
#define PRINT_CMD CDEBUG
#define PRINT_MASK (D_SUPER | D_CONFIG)
Functions
static DEFINE_MUTEX (lustre_mount_info_lock)
static struct lustre_mount_info * server_find_mount (const char *name)
static int server_register_mount (const char *name, struct super_block *sb)
static int server_deregister_mount (const char *name)
struct lustre_mount_info * server_get_mount (const char *name)
Variables
static struct list_head server_mount_info_list
: obd name
server_put_mount: to be called from obd_cleanup methods
: 0 or 1 depending on whether the mount is to be deregistered or not
The caller decides whether server_deregister_mount() needs to be called or not. Calling of server_deregister_mount() does not depend on refcounting on lsi because we could have say the mgs and mds on the same node and we unmount the mds, then the ref on the lsi would still be non-zero but we would still want to deregister the mds mount.
#define log2(n) ffz(~(n))
#define LUSTRE_SUPER_MAGIC 0x0BD00BD1
static struct list_head lwp_register_list
static struct super_operations server_ops
The operations we support directly on the superblock: mount, umount, and df.
static struct inode_operations server_inode_operations
int server_put_mount (const char *name, bool dereg_mnt)
static int server_start_mgs (struct super_block *sb)
static int server_stop_mgs (struct super_block *sb)
static int server_mgc_set_fs (const struct lu_env *env, struct obd_device *mgc, struct super_block *sb)
static int server_mgc_clear_fs (const struct lu_env *env, struct obd_device *mgc)
static bool is_mdc_device (const char *devname)
static bool tgt_is_mdt (const char *tgtname, __u32 *idx)
int tgt_name2lwp_name (const char *tgt_name, char *lwp_name, int len, __u32 idx)
Convert OST/MDT name(fsname-{MDT,OST}xxxx) to a lwp name with the :yyyy (fsname-MDTyyyy-lwp-{MDT,OST}xxxx).
static DEFINE_SPINLOCK (lwp_register_list_lock)
static void lustre_put_lwp_item (struct lwp_register_item *lri)
int lustre_register_lwp_item (const char *lwpname, struct obd_export **exp, register_lwp_cb cb_func, void *cb_data)
void lustre_deregister_lwp_item (struct obd_export **exp)
struct obd_export * lustre_find_lwp_by_index (const char *dev, __u32 idx)
void lustre_notify_lwp_list (struct obd_export *exp)
static int lustre_lwp_connect (struct obd_device *lwp)
static int lustre_lwp_setup (struct lustre_cfg *lcfg, struct lustre_sb_info *lsi, __u32 idx)
lwp is used by slaves (Non-MDT0 targets) to manage the connection to MDT0, or from the OSTx to MDTy.
static struct obd_device * lustre_find_lwp (struct lustre_sb_info *lsi, char **lwpname, __u32 idx)
static int lustre_lwp_add_conn (struct lustre_cfg *cfg, struct lustre_sb_info *lsi, __u32 idx)
static int client_lwp_config_process (const struct lu_env *env, struct llog_handle *handle, struct llog_rec_hdr *rec, void *data)
Retrieve MDT nids from the client log, then start the lwp device.
static int lustre_disconnect_lwp (struct super_block *sb)
static int lustre_stop_lwp (struct super_block *sb)
Stop the lwp for an OST/MDT target.
static int lustre_start_lwp (struct super_block *sb)
Start the lwp(fsname-MDTyyyy-lwp-{MDT,OST}xxxx) for a MDT/OST or MDT target.
static DEFINE_MUTEX (server_start_lock)
static int server_stop_servers (int lsiflags)
int server_mti_print (const char *title, struct mgs_target_info *mti)
static int server_lsi2mti (struct lustre_sb_info *lsi, struct mgs_target_info *mti)
static int server_register_target (struct lustre_sb_info *lsi)
static int server_notify_target (struct super_block *sb, struct obd_device *obd)
Notify the MGS that this target is ready.
static int server_start_targets (struct super_block *sb)
Start server targets: MDTs and OSTs.
static int lsi_prepare (struct lustre_sb_info *lsi)
static void server_put_super (struct super_block *sb)
Start the shutdown of servers at umount.
static void server_umount_begin (struct super_block *sb)
Called only for 'umount -f'.
static int server_statfs (struct dentry *dentry, struct kstatfs *buf)
static ssize_t lustre_getxattr (struct dentry *dentry, const char *name, void *buffer, size_t size)
static int lustre_setxattr (struct dentry *dentry, const char *name, const void *value, size_t size, int flags)
static ssize_t lustre_listxattr (struct dentry *d_entry, char *name, size_t size)
static int server_fill_super_common (struct super_block *sb)
static int osd_start (struct lustre_sb_info *lsi, unsigned long mflags)
int server_fill_super (struct super_block *sb)
Fill in the superblock info for a Lustre server.
void server_calc_timeout (struct lustre_sb_info *lsi, struct obd_device *obd)
Define Documentation
#define D_MOUNT (D_SUPER | D_CONFIG /* | D_WARNING */)
Definition at line 45 of file obd_mount_server.c.
#define DEBUG_SUBSYSTEM S_CLASS
Definition at line 44 of file obd_mount_server.c.
#define log2 (n) ffz(~(n))
Definition at line 1686 of file obd_mount_server.c.
#define LUSTRE_SUPER_MAGIC 0x0BD00BD1
Definition at line 1687 of file obd_mount_server.c.
Referenced by server_fill_super_common().
#define PRINT_CMD CDEBUG
Definition at line 46 of file obd_mount_server.c.
#define PRINT_MASK (D_SUPER | D_CONFIG)
Definition at line 47 of file obd_mount_server.c.
Referenced by server_mti_print().
Function Documentation
static int client_lwp_config_process (const struct lu_env * env, struct llog_handle * handle, struct llog_rec_hdr * rec, void * data) [static]
Retrieve MDT nids from the client log, then start the lwp device.
there are only two scenarios which would include mdt nid. 1. marker 5 (flags=0x01, v2.1.54.0) lustre-MDTyyyy 'add mdc' xxx- add_uuid nid=192.168.122.162(0x20000c0a87aa2) 0: 1:192.168.122.162 attach 0:lustre-MDTyyyy-mdc 1:mdc 2:lustre-clilmv_UUID setup 0:lustre-MDTyyyy-mdc 1:lustre-MDTyyyy_UUID 2:192.168.122.162 add_uuid nid=192.168.172.1(0x20000c0a8ac01) 0: 1:192.168.172.1 add_conn 0:lustre-MDTyyyy-mdc 1:192.168.172.1 modify_mdc_tgts add 0:lustre-clilmv 1:lustre-MDTyyyy_UUID xxxx marker 5 (flags=0x02, v2.1.54.0) lustre-MDTyyyy 'add mdc' xxxx- 2. marker 7 (flags=0x01, v2.1.54.0) lustre-MDTyyyy 'add failnid' xxxx- add_uuid nid=192.168.122.2(0x20000c0a87a02) 0: 1:192.168.122.2 add_conn 0:lustre-MDTyyyy-mdc 1:192.168.122.2 marker 7 (flags=0x02, v2.1.54.0) lustre-MDTyyyy 'add failnid' xxxx-
Definition at line 780 of file obd_mount_server.c.
References __swab32, CERROR, CFG_F_MARKER, CFG_F_SKIP, config_llog_instance::cfg_flags, config_llog_instance::cfg_lwp_idx, config_llog_instance::cfg_sb, class_add_uuid(), cfg_marker::cm_comment, CM_END, CM_EXCLUDE, cfg_marker::cm_flags, CM_SKIP, CM_START, cfg_marker::cm_tgtname, devname, ENTRY, GOTO, is_mdc_device(), IS_MDT, LASSERT, LCFG_ADD_CONN, LCFG_ADD_UUID, lustre_cfg::lcfg_command, LCFG_MARKER, lustre_cfg::lcfg_nid, lustre_cfg::lcfg_version, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, lustre_cfg_buf(), LUSTRE_CFG_BUFLEN, lustre_cfg_sanity_check(), lustre_cfg_string(), LUSTRE_CFG_VERSION, lustre_lwp_add_conn(), lustre_lwp_setup(), lustre_swab_cfg_marker(), lustre_swab_lustre_cfg(), OBD_CFG_REC, RETURN, and tgt_is_mdt().
Referenced by lustre_start_lwp().
static DEFINE_MUTEX (server_start_lock) [static]
static DEFINE_MUTEX (lustre_mount_info_lock) [static]
static DEFINE_SPINLOCK (lwp_register_list_lock) [static]
static bool is_mdc_device (const char * devname) [inline, static]
Definition at line 328 of file obd_mount_server.c.
Referenced by client_lwp_config_process().
static int lsi_prepare (struct lustre_sb_info * lsi) [static]
Definition at line 1423 of file obd_mount_server.c.
References ENTRY, LASSERT, LCONSOLE_ERROR, LDD_F_NO_PRIMNODE, LDD_F_SV_TYPE_MGS, LDD_F_UPDATE, LDD_F_VIRGIN, LDD_F_WRITECONF, LMD_FLG_MGS, LMD_FLG_NO_PRIMNODE, LMD_FLG_NOSVC, LMD_FLG_UPDATE, LMD_FLG_VIRGIN, LMD_FLG_WRITECONF, LUSTRE_OSD_LDISKFS_NAME, RETURN, server_name2index(), and strlcpy().
Referenced by server_fill_super().
void lustre_deregister_lwp_item (struct obd_export ** exp)
Definition at line 458 of file obd_mount_server.c.
References list_del_init(), list_for_each_entry, lwp_register_item::lri_exp, lwp_register_item::lri_list, and lustre_put_lwp_item().
Referenced by mdt_deregister_seq_exp(), mdt_register_seq_exp(), ofd_deregister_seq_exp(), ofd_register_seq_exp(), and qsd_fini().
static int lustre_disconnect_lwp (struct super_block * sb) [static]
Definition at line 890 of file obd_mount_server.c.
References CERROR, config_llog_instance::cfg_instance, class_export_put(), ENTRY, GOTO, LCFG_CLEANUP, lu_device::ld_ops, lu_device_operations::ldo_process_config, likely, list_for_each_entry, lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), lustre_end_log(), MTI_NAME_MAXLEN, OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, obd_device::obd_lu_dev, obd_device::obd_lwp_export, obd_device::obd_name, RETURN, and server_name2fsname().
Referenced by server_put_super().
static struct obd_device* lustre_find_lwp (struct lustre_sb_info * lsi, char ** lwpname, __u32 idx) [static, read]
Definition at line 684 of file obd_mount_server.c.
References CERROR, class_name2obd(), ENTRY, GOTO, IS_MDT, IS_OST, LASSERT, MTI_NAME_MAXLEN, OBD_ALLOC, OBD_FREE, RETURN, and tgt_name2lwp_name().
Referenced by lustre_lwp_add_conn().
struct obd_export* lustre_find_lwp_by_index (const char * dev, __u32 idx) [read]
Definition at line 476 of file obd_mount_server.c.
References CERROR, class_export_get(), list_for_each_entry, lustre_mount_info::lmi_sb, obd_device::obd_lwp_export, obd_device::obd_name, server_get_mount(), server_name2fsname(), and server_put_mount().
Referenced by lfsck_layout_slave_check_pairs(), lfsck_layout_slave_notify_master(), and lfsck_layout_slave_query_master().
static ssize_t lustre_getxattr (struct dentry * dentry, const char * name, void * buffer, size_t size) [static]
Definition at line 1660 of file obd_mount_server.c.
static ssize_t lustre_listxattr (struct dentry * d_entry, char * name, size_t size) [static]
Definition at line 1674 of file obd_mount_server.c.
static int lustre_lwp_add_conn (struct lustre_cfg * cfg, struct lustre_sb_info * lsi, __u32 idx) [static]
Definition at line 719 of file obd_mount_server.c.
References CERROR, class_add_conn(), ENTRY, GOTO, LASSERT, LCFG_ADD_CONN, lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), lustre_cfg_string(), lustre_find_lwp(), MTI_NAME_MAXLEN, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, and RETURN.
Referenced by client_lwp_config_process().
static int lustre_lwp_connect (struct obd_device * lwp) [static]
Definition at line 548 of file obd_mount_server.c.
References CERROR, class_export_get(), class_export_put(), ENTRY, GOTO, lu_context::lc_thread, LCT_SERVER_SESSION, lu_device::ld_type, lu_device_type::ldt_ctx_tags, lu_env::le_ses, lu_context_enter(), lu_context_exit(), lu_context_fini(), lu_context_init(), lu_env_fini(), lu_env_init(), LUSTRE_VERSION_CODE, OBD_ALLOC_PTR, obd_connect(), OBD_CONNECT_AT, OBD_CONNECT_BULK_MBITS, OBD_CONNECT_FID, OBD_CONNECT_FULL20, OBD_CONNECT_INDEX, OBD_CONNECT_LFSCK, OBD_CONNECT_LIGHTWEIGHT, OBD_CONNECT_LRU_RESIZE, OBD_CONNECT_LVB_TYPE, OBD_CONNECT_MDS_MDS, OBD_CONNECT_VERSION, OBD_FREE_PTR, obd_device::obd_lu_dev, obd_device::obd_lwp_export, obd_device::obd_name, obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_version, RETURN, unlikely, obd_uuid::uuid, and uuid.
Referenced by lustre_lwp_setup().
static int lustre_lwp_setup (struct lustre_cfg * lcfg, struct lustre_sb_info * lsi, __u32 idx) [static]
lwp is used by slaves (Non-MDT0 targets) to manage the connection to MDT0, or from the OSTx to MDTy.
Definition at line 619 of file obd_mount_server.c.
References CERROR, client_obd::cl_max_mds_easize, class_add_uuid(), class_name2obd(), obd_device::cli, ENTRY, GOTO, LASSERT, lustre_cfg::lcfg_nid, list_add_tail(), lustre_cfg_string(), lustre_lwp_connect(), LUSTRE_LWP_NAME, lustre_start_simple(), MAX_MD_SIZE, MTI_NAME_MAXLEN, OBD_ALLOC, OBD_FREE, obd_device::obd_lwp_list, RETURN, tgt_name2lwp_name(), and obd_device::u.
Referenced by client_lwp_config_process().
void lustre_notify_lwp_list (struct obd_export * exp)
Definition at line 517 of file obd_mount_server.c.
References class_export_get(), obd_export::exp_obd, LASSERT, list_for_each_entry, lwp_register_item::lri_cb_data, lwp_register_item::lri_cb_func, lwp_register_item::lri_exp, lwp_register_item::lri_list, lwp_register_item::lri_name, lwp_register_item::lri_ref, lustre_put_lwp_item(), and obd_device::obd_name.
Referenced by lwp_notify_main().
static void lustre_put_lwp_item (struct lwp_register_item * lri) [static]
Definition at line 394 of file obd_mount_server.c.
References class_export_put(), LASSERT, list_empty(), lwp_register_item::lri_exp, lwp_register_item::lri_list, lwp_register_item::lri_ref, and OBD_FREE_PTR.
Referenced by lustre_deregister_lwp_item(), lustre_notify_lwp_list(), and lustre_register_lwp_item().
int lustre_register_lwp_item (const char * lwpname, struct obd_export ** exp, register_lwp_cb cb_func, void * cb_data)
Definition at line 405 of file obd_mount_server.c.
References cfs_hash_lookup(), class_name2obd(), ENTRY, INIT_LIST_HEAD, LASSERT, LASSERTF, list_add(), lwp_register_item::lri_cb_data, lwp_register_item::lri_cb_func, lwp_register_item::lri_exp, lwp_register_item::lri_list, lwp_register_item::lri_name, lwp_register_item::lri_ref, lustre_put_lwp_item(), MTI_NAME_MAXLEN, OBD_ALLOC_PTR, OBD_FREE_PTR, obd_device::obd_set_up, obd_device::obd_uuid_hash, RETURN, obd_uuid::uuid, and uuid.
Referenced by mdt_register_seq_exp(), ofd_register_seq_exp(), and qsd_prepare().
static int lustre_setxattr (struct dentry * dentry, const char * name, const void * value, size_t size, int flags) [static]
Definition at line 1668 of file obd_mount_server.c.
static int lustre_start_lwp (struct super_block * sb) [static]
Start the lwp(fsname-MDTyyyy-lwp-{MDT,OST}xxxx) for a MDT/OST or MDT target.
Definition at line 1000 of file obd_mount_server.c.
References CERROR, config_llog_instance::cfg_callback, config_llog_instance::cfg_instance, client_lwp_config_process(), ENTRY, GOTO, lustre_process_log(), MTI_NAME_MAXLEN, OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, RETURN, server_name2fsname(), and unlikely.
Referenced by server_start_targets().
static int lustre_stop_lwp (struct super_block * sb) [static]
Stop the lwp for an OST/MDT target.
Definition at line 973 of file obd_mount_server.c.
References CERROR, class_manual_cleanup(), ENTRY, list_del_init(), list_empty(), list_entry, obd_device::obd_force, obd_device::obd_lwp_list, obd_device::obd_name, and RETURN.
Referenced by server_put_super().
static int osd_start (struct lustre_sb_info * lsi, unsigned long mflags) [static]
Definition at line 1723 of file obd_mount_server.c.
References CDEBUG, class_manual_cleanup(), class_name2obd(), D_MOUNT, lvfs_run_ctxt::dt, dt_conf_get(), ENTRY, GOTO, IS_MDT, IS_MGS, LASSERT, lustre_mount_data::lmd_dev, lustre_mount_data::lmd_flags, LMD_FLG_NOMGS, LMD_FLG_NOSVC, lu2dt_dev(), lu_device_get(), lustre_start_simple(), obd_connect(), obd_device::obd_force, obd_device::obd_lu_dev, obd_device::obd_lvfs_ctxt, OBD_SET_CTXT_MAGIC(), obd_device::obd_uuid, and RETURN.
Referenced by server_fill_super().
void server_calc_timeout (struct lustre_sb_info * lsi, struct obd_device * obd)
Definition at line 1875 of file obd_mount_server.c.
References IS_SERVER, LASSERT, LCONSOLE_INFO, LDD_F_IR_CAPABLE, lustre_mount_data::lmd_flags, LMD_FLG_NOIR, lustre_mount_data::lmd_recovery_time_hard, lustre_mount_data::lmd_recovery_time_soft, max, OBD_IR_FACTOR_DEFAULT, OBD_IR_FACTOR_MAX, obd_device::obd_name, obd_device::obd_no_ir, obd_device::obd_recovery_ir_factor, obd_device::obd_recovery_time_hard, OBD_RECOVERY_TIME_HARD, OBD_RECOVERY_TIME_MIN, OBD_RECOVERY_TIME_SOFT, and obd_device::obd_recovery_timeout.
Referenced by server_start_targets().
static int server_deregister_mount (const char * name) [static]
Definition at line 131 of file obd_mount_server.c.
References CDEBUG, CERROR, D_MOUNT, ENTRY, list_del(), lustre_mount_info::lmi_list_chain, lustre_mount_info::lmi_name, lustre_mount_info::lmi_sb, OBD_FREE, RETURN, and server_find_mount().
Referenced by server_put_mount(), server_put_super(), and server_start_mgs().
int server_fill_super (struct super_block * sb)
Fill in the superblock info for a Lustre server.
Mount the device with the correct options. Read the on-disk config file. Start the services.
Definition at line 1792 of file obd_mount_server.c.
References CDEBUG, CERROR, class_name2obd(), D_MOUNT, ENTRY, GOTO, IS_MDT, IS_MGS, IS_OST, LCONSOLE_ERROR_MSG, LMD_FLG_NOMGS, LMD_FLG_NOSVC, lsi_prepare(), lustre_put_lsi(), lustre_start_mgc(), OBD_FAIL_TGT_MOUNT_RACE, OBD_RACE, osd_start(), RETURN, server_fill_super_common(), server_put_super(), server_start_mgs(), and server_start_targets().
Referenced by lustre_fill_super().
static int server_fill_super_common (struct super_block * sb) [static]
Definition at line 1689 of file obd_mount_server.c.
References CDEBUG, CERROR, d_make_root(), D_MOUNT, ENTRY, log2, LUSTRE_SUPER_MAGIC, RETURN, server_inode_operations, and server_ops.
Referenced by server_fill_super().
static struct lustre_mount_info* server_find_mount (const char * name) [static, read]
Definition at line 74 of file obd_mount_server.c.
References ENTRY, list_entry, list_for_each, lustre_mount_info::lmi_list_chain, lustre_mount_info::lmi_name, and RETURN.
Referenced by server_deregister_mount(), server_get_mount(), server_put_mount(), server_register_mount(), server_start_mgs(), and server_stop_mgs().
struct lustre_mount_info* server_get_mount (const char * name) [read]
Definition at line 157 of file obd_mount_server.c.
References CDEBUG, CERROR, D_MOUNT, ENTRY, lustre_mount_info::lmi_sb, RETURN, and server_find_mount().
Referenced by lustre_find_lwp_by_index(), mdt_init0(), mgs_init0(), and ofd_stack_init().
static int server_lsi2mti (struct lustre_sb_info * lsi, struct mgs_target_info * mti) [static]
Definition at line 1093 of file obd_mount_server.c.
References CERROR, class_match_net(), class_match_nid(), CWARN, ENTRY, IS_SERVER, LASSERT, LDD_F_MASK, LDD_F_NEED_INDEX, LDD_F_UPDATE, LDD_F_VIRGIN, LDD_F_WRITECONF, LMD_FLG_NO_PRIMNODE, LNET_NETTYP(), LNET_NIDNET(), LNetGetId(), LOLND, LUSTRE_VERSION_CODE, mgs_target_info::mti_config_ver, mgs_target_info::mti_flags, mgs_target_info::mti_fsname, mgs_target_info::mti_lustre_ver, mgs_target_info::mti_nid_count, mgs_target_info::mti_nids, MTI_NIDS_MAX, mgs_target_info::mti_params, mgs_target_info::mti_stripe_index, mgs_target_info::mti_svname, PARAM_FAILNODE, PARAM_NETWORK, RETURN, server_name2fsname(), server_name2index(), and strlcpy().
Referenced by server_notify_target(), and server_register_target().
static int server_mgc_clear_fs (const struct lu_env * env, struct obd_device * mgc) [static]
Definition at line 314 of file obd_mount_server.c.
References CDEBUG, D_MOUNT, ENTRY, KEY_CLEAR_FS, obd_device::obd_self_export, obd_set_info_async(), and RETURN.
Referenced by server_start_targets().
static int server_mgc_set_fs (const struct lu_env * env, struct obd_device * mgc, struct super_block * sb) [static]
Definition at line 295 of file obd_mount_server.c.
References CDEBUG, CERROR, D_MOUNT, ENTRY, KEY_SET_FS, obd_device::obd_self_export, obd_set_info_async(), and RETURN.
Referenced by server_start_targets().
int server_mti_print (const char * title, struct mgs_target_info * mti)
Definition at line 1081 of file obd_mount_server.c.
References mgs_target_info::mti_config_ver, mgs_target_info::mti_flags, mgs_target_info::mti_fsname, mgs_target_info::mti_svname, mgs_target_info::mti_uuid, PRINT_CMD, and PRINT_MASK.
static int server_notify_target (struct super_block * sb, struct obd_device * obd) [static]
Notify the MGS that this target is ready.
Used by IR - if the MGS receives this message, it will notify clients.
Definition at line 1232 of file obd_mount_server.c.
References client_obd::cl_mgc_mgsexp, obd_device::cli, ENTRY, GOTO, IS_SERVER, KEY_REGISTER_TARGET, LASSERT, LDD_F_ERROR, LDD_F_IR_CAPABLE, LDD_F_OPC_READY, mgs_target_info::mti_flags, mgs_target_info::mti_instance, OBD_ALLOC_PTR, OBD_FREE_PTR, obd_set_info_async(), RETURN, server_lsi2mti(), and obd_device::u.
Referenced by server_start_targets().
int server_put_mount (const char * name, bool dereg_mnt)
Definition at line 193 of file obd_mount_server.c.
References CDEBUG, CERROR, D_MOUNT, ENTRY, lustre_mount_info::lmi_sb, lustre_put_lsi(), RETURN, server_deregister_mount(), and server_find_mount().
Referenced by lustre_find_lwp_by_index(), mdt_fini(), mdt_init0(), mgs_device_fini(), mgs_init0(), and ofd_fini().
static void server_put_super (struct super_block * sb) [static]
Start the shutdown of servers at umount.
Definition at line 1497 of file obd_mount_server.c.
References CDEBUG, CERROR, class_get_profile(), class_manual_cleanup(), class_name2obd(), class_put_profile(), CWARN, D_MOUNT, ENTRY, EXIT, IS_MDT, IS_MGS, IS_OST, IS_SERVER, LASSERT, LCONSOLE_WARN, LMD_FLG_NOMGS, LMD_FLG_NOSVC, lustre_profile::lp_dt, lustre_common_put_super(), lustre_disconnect_lwp(), lustre_end_log(), lustre_stop_lwp(), OBD_ALLOC, obd_device::obd_fail, obd_device::obd_force, OBD_FREE, obd_device::obd_name, obd_zombie_barrier(), server_deregister_mount(), server_stop_mgs(), and server_stop_servers().
Referenced by server_fill_super().
static int server_register_mount (const char * name, struct super_block * sb) [static]
Definition at line 92 of file obd_mount_server.c.
References CDEBUG, CERROR, D_MOUNT, ENTRY, LASSERT, list_add(), lustre_mount_info::lmi_list_chain, lustre_mount_info::lmi_name, lustre_mount_info::lmi_sb, OBD_ALLOC, OBD_FREE, RETURN, and server_find_mount().
Referenced by server_start_mgs(), and server_start_targets().
static int server_register_target (struct lustre_sb_info * lsi) [static]
Definition at line 1166 of file obd_mount_server.c.
References CDEBUG, client_obd::cl_mgc_mgsexp, obd_device::cli, D_HA, D_MOUNT, ENTRY, GOTO, IS_SERVER, KEY_REGISTER_TARGET, LASSERT, LCONSOLE_ERROR_MSG, LDD_F_ERROR, LDD_F_NEED_INDEX, LDD_F_OPC_REG, LDD_F_UPDATE, libcfs_nid2str(), mgs_target_info::mti_flags, mgs_target_info::mti_fsname, mgs_target_info::mti_nids, mgs_target_info::mti_stripe_index, mgs_target_info::mti_svname, OBD_ALLOC_PTR, OBD_FREE_PTR, obd_set_info_async(), RETURN, server_lsi2mti(), and obd_device::u.
Referenced by server_start_targets().
static int server_start_mgs (struct super_block * sb) [static]
Definition at line 224 of file obd_mount_server.c.
References CDEBUG, D_CONFIG, ENTRY, LCONSOLE_ERROR_MSG, lustre_mount_info::lmi_sb, LUSTRE_MGS_NAME, LUSTRE_MGS_OBDNAME, lustre_start_simple(), RETURN, server_deregister_mount(), server_find_mount(), and server_register_mount().
Referenced by server_fill_super().
static int server_start_targets (struct super_block * sb) [static]
Start server targets: MDTs and OSTs.
Definition at line 1275 of file obd_mount_server.c.
References CDEBUG, CERROR, config_llog_instance::cfg_callback, class_config_llog_handler(), class_name2obd(), CONFIG_LOG, D_MOUNT, ENTRY, GOTO, IS_MDT, IS_OST, lu_context::lc_thread, LCT_MG_THREAD, LCT_SERVER_SESSION, lu_device::ld_ops, lu_device::ld_type, lu_device_operations::ldo_prepare, lu_device_type::ldt_ctx_tags, lu_env::le_ses, LMD_FLG_ABORT_RECOV, lu_context_enter(), lu_context_exit(), lu_context_fini(), lu_context_init(), lu_env_fini(), lu_env_init(), LUSTRE_MDS_NAME, LUSTRE_MDS_OBDNAME, LUSTRE_OSS_NAME, LUSTRE_OSS_OBDNAME, lustre_process_log(), lustre_start_lwp(), lustre_start_simple(), OBD_IOC_ABORT_RECOVERY, obd_iocontrol(), obd_device::obd_lu_dev, obd_notify(), OBD_NOTIFY_CONFIG, obd_device::obd_self_export, OBP, RETURN, server_calc_timeout(), server_mgc_clear_fs(), server_mgc_set_fs(), server_notify_target(), server_register_mount(), server_register_target(), and server_stop_servers().
Referenced by server_fill_super().
static int server_statfs (struct dentry * dentry, struct kstatfs * buf) [static]
Definition at line 1619 of file obd_mount_server.c.
References dt_statfs(), ENTRY, RETURN, and statfs_unpack().
static int server_stop_mgs (struct super_block * sb) [static]
Definition at line 266 of file obd_mount_server.c.
References CDEBUG, class_manual_cleanup(), class_name2obd(), D_CONFIG, D_MOUNT, ENTRY, lustre_mount_info::lmi_sb, LUSTRE_MGS_OBDNAME, obd_device::obd_force, RETURN, and server_find_mount().
Referenced by server_put_super().
static int server_stop_servers (int lsiflags) [static]
Definition at line 1046 of file obd_mount_server.c.
References class_manual_cleanup(), class_name2obd(), class_search_type(), ENTRY, LDD_F_SV_TYPE_MDT, LDD_F_SV_TYPE_OST, LUSTRE_MDS_OBDNAME, LUSTRE_MDT_NAME, LUSTRE_OSS_OBDNAME, LUSTRE_OST_NAME, obd_device::obd_force, RETURN, and obd_type::typ_refcnt.
Referenced by server_put_super(), and server_start_targets().
static void server_umount_begin (struct super_block * sb) [static]
Called only for 'umount -f'.
Definition at line 1606 of file obd_mount_server.c.
References CDEBUG, D_MOUNT, ENTRY, and EXIT.
static bool tgt_is_mdt (const char * tgtname, __u32 * idx) [inline, static]
Definition at line 336 of file obd_mount_server.c.
References LDD_F_SV_TYPE_MDT, and server_name2index().
Referenced by client_lwp_config_process().
int tgt_name2lwp_name (const char * tgt_name, char * lwp_name, int len, __u32 idx)
Convert OST/MDT name(fsname-{MDT,OST}xxxx) to a lwp name with the :yyyy (fsname-MDTyyyy-lwp-{MDT,OST}xxxx).
Definition at line 349 of file obd_mount_server.c.
References CERROR, cleanup(), ENTRY, GOTO, LUSTRE_LWP_NAME, MTI_NAME_MAXLEN, OBD_ALLOC, OBD_FREE, RETURN, and server_name2fsname().
Referenced by lustre_find_lwp(), lustre_lwp_setup(), mdt_register_seq_exp(), ofd_register_seq_exp(), and qsd_prepare().
Variable Documentation
struct list_head lwp_register_list [static]
Initial value:
        LIST_HEAD_INIT(lwp_register_list)
Definition at line 390 of file obd_mount_server.c.
struct inode_operations server_inode_operations [static]
Initial value:
 {
        .setxattr       = lustre_setxattr,
        .getxattr       = lustre_getxattr,
        .listxattr      = lustre_listxattr,
}
Definition at line 1680 of file obd_mount_server.c.
Referenced by server_fill_super_common().
struct list_head server_mount_info_list [static]
Initial value:
        LIST_HEAD_INIT(server_mount_info_list)
Definition at line 71 of file obd_mount_server.c.
struct super_operations server_ops [static]
Initial value:
 {
        .put_super      = server_put_super,
        .umount_begin   = server_umount_begin,
        .statfs         = server_statfs,
}
The operations we support directly on the superblock: mount, umount, and df.
Definition at line 1651 of file obd_mount_server.c.
Referenced by server_fill_super_common().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.