Lustre: lustre/include/obd_cksum.h File Reference
lustre/include/obd_cksum.h File Reference
#include <libcfs/libcfs.h>
#include <libcfs/libcfs_crypto.h>
#include <lustre/lustre_idl.h>
Defines
#define DECLARE_CKSUM_NAME char *cksum_name[] = {"crc32", "adler", "crc32c"}
Functions
static unsigned char cksum_obd2cfs (cksum_type_t cksum_type)
static u32 cksum_type_pack (cksum_type_t cksum_type)
static cksum_type_t cksum_type_unpack (u32 o_flags)
static cksum_type_t cksum_types_supported_client (void)
static cksum_type_t cksum_types_supported_server (void)
static cksum_type_t cksum_type_select (cksum_type_t cksum_types)
Define Documentation
#define DECLARE_CKSUM_NAME char *cksum_name[] = {"crc32", "adler", "crc32c"}
Definition at line 177 of file obd_cksum.h.
Function Documentation
static unsigned char cksum_obd2cfs (cksum_type_t cksum_type) [inline, static]
Definition at line 43 of file obd_cksum.h.
References CERROR, CFS_HASH_ALG_ADLER32, CFS_HASH_ALG_CRC32, CFS_HASH_ALG_CRC32C, LBUG, OBD_CKSUM_ADLER, OBD_CKSUM_CRC32, and OBD_CKSUM_CRC32C.
Referenced by cksum_type_pack(), cksum_types_supported_client(), cksum_types_supported_server(), osc_checksum_bulk(), and tgt_checksum_bulk().
static u32 cksum_type_pack (cksum_type_t cksum_type) [inline, static]
Definition at line 70 of file obd_cksum.h.
References cfs_crypto_hash_speed(), cksum_obd2cfs(), CWARN, OBD_CKSUM_ADLER, OBD_CKSUM_CRC32, OBD_CKSUM_CRC32C, OBD_FL_CKSUM_ADLER, OBD_FL_CKSUM_CRC32, OBD_FL_CKSUM_CRC32C, and unlikely.
Referenced by cksum_type_select(), osc_brw_prep_request(), tgt_brw_read(), and tgt_brw_write().
static cksum_type_t cksum_type_select (cksum_type_t cksum_types) [inline, static]
Definition at line 170 of file obd_cksum.h.
References cksum_type_pack(), and cksum_type_unpack().
Referenced by ptlrpc_connect_set_flags().
static cksum_type_t cksum_type_unpack (u32 o_flags) [inline, static]
Definition at line 104 of file obd_cksum.h.
References OBD_CKSUM_ADLER, OBD_CKSUM_CRC32, OBD_CKSUM_CRC32C, OBD_FL_CKSUM_ALL, OBD_FL_CKSUM_CRC32, and OBD_FL_CKSUM_CRC32C.
Referenced by check_write_checksum(), cksum_type_select(), osc_brw_fini_request(), tgt_brw_read(), and tgt_brw_write().
static cksum_type_t cksum_types_supported_client (void) [inline, static]
Definition at line 122 of file obd_cksum.h.
References CDEBUG, cfs_crypto_hash_speed(), cksum_obd2cfs(), D_INFO, OBD_CKSUM_ADLER, OBD_CKSUM_CRC32, OBD_CKSUM_CRC32C, and ret.
Referenced by client_common_fill_super(), and ptlrpc_connect_set_flags().
static cksum_type_t cksum_types_supported_server (void) [inline, static]
Definition at line 140 of file obd_cksum.h.
References CDEBUG, cfs_crypto_hash_speed(), cksum_obd2cfs(), D_INFO, OBD_CKSUM_ADLER, OBD_CKSUM_CRC32, OBD_CKSUM_CRC32C, and ret.
Referenced by ofd_parse_connect_data().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.