Lustre: lustre/obdclass/obd_config.c File Reference
lustre/obdclass/obd_config.c File Reference
#include <linux/string.h>
#include <llog_swab.h>
#include <lprocfs_status.h>
#include <lustre_disk.h>
#include <lustre_ioctl.h>
#include <lustre_log.h>
#include <lustre_param.h>
#include <obd_class.h>
#include "llog_internal.h"
Data Structures
struct lcfg_type_data
Defines
#define DEBUG_SUBSYSTEM S_CLASS
Enumerations
enum { CLASS_PARSE_NID = 1, CLASS_PARSE_NET }
Functions
int class_find_param (char *buf, char *key, char **valp)
struct cfg_interop_param * class_find_old_param (const char *param, struct cfg_interop_param *ptr)
Check whether the proc parameter param is an old parameter or not from the array ptr which contains the mapping from old parameters to new ones.
int class_get_next_param (char **params, char *copy)
Finds a parameter in params and copies it to copy.
int class_match_param (char *buf, const char *key, char **valp)
static int parse_nid (char *buf, void *value, int quiet)
static int parse_net (char *buf, void *value)
static int class_parse_value (char *buf, int opc, void *value, char **endh, int quiet)
int class_parse_nid (char *buf, lnet_nid_t *nid, char **endh)
int class_parse_nid_quiet (char *buf, lnet_nid_t *nid, char **endh)
int class_parse_net (char *buf, __u32 *net, char **endh)
int class_match_nid (char *buf, char *key, lnet_nid_t nid)
int class_match_net (char *buf, char *key, __u32 net)
int class_attach (struct lustre_cfg *lcfg)
Create a new obd device and set the type, name and uuid.
int class_setup (struct obd_device *obd, struct lustre_cfg *lcfg)
Create hashes, self-export, and call type-specific setup.
int class_detach (struct obd_device *obd, struct lustre_cfg *lcfg)
We have finished using this obd and are ready to destroy it.
int class_cleanup (struct obd_device *obd, struct lustre_cfg *lcfg)
Start shutting down the obd.
struct obd_device * class_incref (struct obd_device *obd, const char *scope, const void *source)
void class_decref (struct obd_device *obd, const char *scope, const void *source)
int class_add_conn (struct obd_device *obd, struct lustre_cfg *lcfg)
Add a failover nid location.
static int class_del_conn (struct obd_device *obd, struct lustre_cfg *lcfg)
Remove a failover nid location.
static DEFINE_SPINLOCK (lustre_profile_list_lock)
struct lustre_profile * class_get_profile (const char *prof)
static int class_add_profile (int proflen, char *prof, int osclen, char *osc, int mdclen, char *mdc)
Create a named "profile".
void class_del_profile (const char *prof)
void class_put_profile (struct lustre_profile *lprof)
void class_del_profiles (void)
static int class_set_global (char *ptr, int val, struct lustre_cfg *lcfg)
void lustre_register_client_process_config (int(*cpc)(struct lustre_cfg *lcfg))
struct lustre_cfg * lustre_cfg_rename (struct lustre_cfg *cfg, const char *new_name)
Rename the proc parameter in cfg with a new name new_name.
static int process_param2_config (struct lustre_cfg *lcfg)
void lustre_register_quota_process_config (int(*qpc)(struct lustre_cfg *lcfg))
int class_process_config (struct lustre_cfg *lcfg)
Process configuration commands given in lustre_cfg form.
int class_process_proc_param (char *prefix, struct lprocfs_vars *lvars, struct lustre_cfg *lcfg, void *data)
struct llog_cfg_rec * lustre_cfg_rec_new (int cmd, struct lustre_cfg_bufs *bufs)
void lustre_cfg_rec_free (struct llog_cfg_rec *lcr)
int class_config_llog_handler (const struct lu_env *env, struct llog_handle *handle, struct llog_rec_hdr *rec, void *data)
Parse a configuration llog, doing various manipulations on them for various reasons, (modifications for compatibility, skip obsolete records, change uuids, etc), then class_process_config() resulting net records.
int class_config_parse_llog (const struct lu_env *env, struct llog_ctxt *ctxt, char *name, struct config_llog_instance *cfg)
static struct lcfg_type_data * lcfg_cmd2data (__u32 cmd)
int class_config_yaml_output (struct llog_rec_hdr *rec, char *buf, int size)
parse config record and output dump in supplied buffer.
static int class_config_parse_rec (struct llog_rec_hdr *rec, char *buf, int size)
parse config record and output dump in supplied buffer.
int class_config_dump_handler (const struct lu_env *env, struct llog_handle *handle, struct llog_rec_hdr *rec, void *data)
int class_manual_cleanup (struct obd_device *obd)
Call class_cleanup and class_detach.
static unsigned uuid_hash (struct cfs_hash *hs, const void *key, unsigned mask)
static void * uuid_key (struct hlist_node *hnode)
static int uuid_keycmp (const void *key, struct hlist_node *hnode)
static void * uuid_export_object (struct hlist_node *hnode)
static void uuid_export_get (struct cfs_hash *hs, struct hlist_node *hnode)
static void uuid_export_put_locked (struct cfs_hash *hs, struct hlist_node *hnode)
static unsigned nid_hash (struct cfs_hash *hs, const void *key, unsigned mask)
static void * nid_key (struct hlist_node *hnode)
static int nid_kepcmp (const void *key, struct hlist_node *hnode)
static void * nid_export_object (struct hlist_node *hnode)
static void nid_export_get (struct cfs_hash *hs, struct hlist_node *hnode)
static void nid_export_put_locked (struct cfs_hash *hs, struct hlist_node *hnode)
static void * nidstats_key (struct hlist_node *hnode)
static int nidstats_keycmp (const void *key, struct hlist_node *hnode)
static void * nidstats_object (struct hlist_node *hnode)
static void nidstats_get (struct cfs_hash *hs, struct hlist_node *hnode)
static void nidstats_put_locked (struct cfs_hash *hs, struct hlist_node *hnode)
static unsigned gen_hash (struct cfs_hash *hs, const void *key, unsigned mask)
static void * gen_key (struct hlist_node *hnode)
static int gen_kepcmp (const void *key, struct hlist_node *hnode)
static void * gen_export_object (struct hlist_node *hnode)
static void gen_export_get (struct cfs_hash *hs, struct hlist_node *hnode)
static void gen_export_put_locked (struct cfs_hash *hs, struct hlist_node *hnode)
Variables
static struct cfs_hash_ops uuid_hash_ops
static struct cfs_hash_ops nid_hash_ops
static struct cfs_hash_ops nid_stat_hash_ops
static struct cfs_hash_ops gen_hash_ops
static struct list_head lustre_profile_list
static int(* client_process_config)(struct lustre_cfg *lcfg) = NULL
static int(* quota_process_config)(struct lustre_cfg *lcfg) = NULL
static struct lcfg_type_data lcfg_data_table []
Define Documentation
#define DEBUG_SUBSYSTEM S_CLASS
Definition at line 41 of file obd_config.c.
Enumeration Type Documentation
anonymous enum
Enumerator:
CLASS_PARSE_NID
CLASS_PARSE_NET
Definition at line 227 of file obd_config.c.
Function Documentation
int class_add_conn (struct obd_device * obd, struct lustre_cfg * lcfg)
Add a failover nid location.
Client obd types contact server obd types using this nid list.
Definition at line 775 of file obd_config.c.
References CERROR, client_obd::cl_import, obd_device::cli, ENTRY, lustre_cfg::lcfg_num, LUSTRE_CFG_BUFLEN, lustre_cfg_string(), LUSTRE_LWP_NAME, LUSTRE_MDC_NAME, LUSTRE_MGC_NAME, LUSTRE_OSC_NAME, LUSTRE_OSP_NAME, obd_add_conn(), obd_str2uuid(), obd_device::obd_type, RETURN, obd_type::typ_name, and obd_device::u.
Referenced by class_process_config(), and lustre_lwp_add_conn().
static int class_add_profile (int proflen, char * prof, int osclen, char * osc, int mdclen, char * mdc) [static]
Create a named "profile".
This defines the mdc and osc names to use for a client. This also is used to define the lov to be used by a mdt.
Definition at line 866 of file obd_config.c.
References CDEBUG, D_CONFIG, ENTRY, GOTO, INIT_LIST_HEAD, LASSERT, list_add(), lustre_profile::lp_dt, lustre_profile::lp_list, lustre_profile::lp_list_deleted, lustre_profile::lp_md, lustre_profile::lp_profile, lustre_profile::lp_refs, OBD_ALLOC, OBD_FREE, and RETURN.
Referenced by class_process_config().
int class_attach (struct lustre_cfg * lcfg)
Create a new obd device and set the type, name and uuid.
If successful, the new device can be accessed by either name or uuid.
Definition at line 336 of file obd_config.c.
References CDEBUG, CERROR, cfs_init_timer(), cfs_time_shift_64(), class_newdev(), class_release_dev(), D_IOCTL, ENTRY, GOTO, INIT_LIST_HEAD, LASSERTF, llog_group_init(), lu_ref_add(), lu_ref_init(), LUSTRE_CFG_BUFLEN, lustre_cfg_string(), MKSTR, name, obd_device::obd_attached, obd_device::obd_conn_inprogress, obd_device::obd_delayed_exports, obd_device::obd_dev_lock, obd_device::obd_dev_mutex, OBD_DEVICE_MAGIC, obd_device::obd_evict_inprogress_waitq, obd_device::obd_evict_list, obd_device::obd_exports, obd_device::obd_exports_timed, obd_device::obd_final_req_queue, obd_device::obd_lock_replay_queue, obd_device::obd_lwp_list, obd_device::obd_magic, obd_device::obd_minor, obd_device::obd_name, obd_device::obd_next_transno_waitq, obd_device::obd_nid_lock, obd_device::obd_nid_stats, obd_device::obd_observer_link_sem, obd_device::obd_olg, obd_device::obd_osfs_age, obd_device::obd_osfs_lock, obd_device::obd_pool_limit, obd_device::obd_pool_lock, obd_device::obd_pool_slv, obd_device::obd_recovery_task_lock, obd_device::obd_recovery_timer, obd_device::obd_refcount, obd_device::obd_reference, obd_device::obd_req_replay_queue, obd_device::obd_unlinked_exports, obd_device::obd_uuid, RETURN, obd_uuid::uuid, and uuid.
Referenced by class_process_config(), mdt_quota_init(), and mdt_stack_init().
int class_cleanup (struct obd_device * obd, struct lustre_cfg * lcfg)
Start shutting down the obd.
There may be in-progess ops when this is called. We tell them to start shutting down with a call to class_disconnect_exports().
Definition at line 616 of file obd_config.c.
References CDEBUG, CERROR, cfs_hash_putref(), class_decref(), class_disconnect_exports(), D_IOCTL, dump_exports(), ENTRY, LASSERT, lustre_cfg::lcfg_bufcount, LCONSOLE_WARN, LUSTRE_CFG_BUFLEN, lustre_cfg_string(), obd_device::obd_conn_inprogress, obd_device::obd_dev_lock, obd_device::obd_fail, OBD_FAIL_LDLM_RECOV_CLIENTS, obd_device::obd_force, obd_device::obd_gen_hash, OBD_IOC_SYNC, obd_iocontrol(), obd_device::obd_minor, obd_device::obd_name, obd_device::obd_nid_hash, obd_device::obd_nid_stats_hash, obd_device::obd_no_recov, obd_device::obd_no_transno, obd_precleanup(), OBD_RACE, obd_device::obd_refcount, obd_device::obd_self_export, obd_device::obd_set_up, obd_device::obd_stopping, obd_device::obd_uuid_hash, OBP, and RETURN.
Referenced by class_process_config(), and mdt_quota_init().
int class_config_dump_handler (const struct lu_env * env, struct llog_handle * handle, struct llog_rec_hdr * rec, void * data)
Definition at line 1881 of file obd_config.c.
References class_config_parse_rec(), D_WARNING, ENTRY, LCONSOLE, llog_rec_hdr::lrh_type, OBD_ALLOC, OBD_CFG_REC, OBD_FREE, and RETURN.
Referenced by class_config_llog_handler().
int class_config_llog_handler (const struct lu_env * env, struct llog_handle * handle, struct llog_rec_hdr * rec, void * data)
Parse a configuration llog, doing various manipulations on them for various reasons, (modifications for compatibility, skip obsolete records, change uuids, etc), then class_process_config() resulting net records.
Definition at line 1451 of file obd_config.c.
References __swab32, CDEBUG, CERROR, CFG_F_COMPAT146, CFG_F_EXCLUDE, CFG_F_MARKER, CFG_F_SKIP, config_llog_instance::cfg_flags, config_llog_instance::cfg_instance, config_llog_instance::cfg_lwp_idx, config_llog_instance::cfg_obdname, config_llog_instance::cfg_sb, config_llog_instance::cfg_uuid, class_config_dump_handler(), class_process_config(), CM_END, CM_EXCLUDE, cfg_marker::cm_flags, CM_SKIP, CM_START, cfg_marker::cm_step, cfg_marker::cm_tgtname, CWARN, D_CONFIG, D_INFO, ENTRY, GOTO, IS_MDT, LCFG_ATTACH, lustre_cfg_bufs::lcfg_buf, lustre_cfg_bufs::lcfg_buflen, lustre_cfg::lcfg_command, lustre_cfg::lcfg_flags, LCFG_LOV_ADD_INA, LCFG_LOV_ADD_OBD, LCFG_MARKER, lustre_cfg::lcfg_nal, lustre_cfg::lcfg_nid, lustre_cfg::lcfg_num, LCFG_SETUP, LCFG_SPTLRPC_CONF, lustre_cfg::lcfg_version, llog_handle::lgh_ctxt, libcfs_nid2str(), LNET_MKNET(), LNET_MKNID(), llog_ctxt::loc_obd, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, lustre_cfg_buf(), LUSTRE_CFG_BUFLEN, lustre_cfg_bufs_init(), lustre_cfg_bufs_set(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), lustre_cfg_sanity_check(), lustre_cfg_string(), LUSTRE_CFG_VERSION, lustre_check_exclusion(), LUSTRE_LOD_NAME, LUSTRE_LOV_NAME, LUSTRE_OSC_NAME, LUSTRE_OSP_NAME, lustre_swab_cfg_marker(), lustre_swab_lustre_cfg(), OBD_ALLOC, OBD_CFG_REC, OBD_FREE, obd_device::obd_name, RETURN, server_name2index(), and obd_uuid::uuid.
Referenced by class_config_parse_llog(), do_config_log_add(), ll_fill_super(), and server_start_targets().
int class_config_parse_llog (const struct lu_env * env, struct llog_ctxt * ctxt, char * name, struct config_llog_instance * cfg)
Definition at line 1673 of file obd_config.c.
References CDEBUG, config_llog_instance::cfg_callback, config_llog_instance::cfg_last_idx, class_config_llog_handler(), D_CONFIG, D_INFO, ENTRY, GOTO, LASSERT, llog_close(), LLOG_F_IS_PLAIN, llog_init_handle(), llog_open(), LLOG_OPEN_EXISTS, llog_process(), llog_process_cat_data::lpcd_first_idx, llog_process_cat_data::lpcd_last_idx, and RETURN.
Referenced by mgc_process_cfg_log().
static int class_config_parse_rec (struct llog_rec_hdr * rec, char * buf, int size) [static]
parse config record and output dump in supplied buffer.
This is separated from class_config_dump_handler() to use for ioctl needs as well
Definition at line 1831 of file obd_config.c.
References cfg_marker::cm_comment, cfg_marker::cm_flags, cfg_marker::cm_step, cfg_marker::cm_tgtname, end, ENTRY, LASSERT, lustre_cfg::lcfg_bufcount, lustre_cfg::lcfg_command, lustre_cfg::lcfg_flags, LCFG_MARKER, lustre_cfg::lcfg_nid, lustre_cfg::lcfg_num, libcfs_nid2str_r(), LNET_NIDSTR_SIZE, LPX64, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, lustre_cfg_buf(), lustre_cfg_sanity_check(), lustre_cfg_string(), OBD_CFG_REC, and RETURN.
Referenced by class_config_dump_handler().
int class_config_yaml_output (struct llog_rec_hdr * rec, char * buf, int size)
parse config record and output dump in supplied buffer.
This is separated from class_config_dump_handler() to use for ioctl needs as well
Sample Output:
{ event: attach, device: lustrewt-clilov, type: lov, UUID: lustrewt-clilov_UUID }
Definition at line 1772 of file obd_config.c.
References end, LASSERT, lustre_cfg::lcfg_bufcount, lcfg_cmd2data(), lustre_cfg::lcfg_command, lustre_cfg::lcfg_flags, LCFG_MARKER, lustre_cfg::lcfg_nid, lustre_cfg::lcfg_num, libcfs_nid2str_r(), LNET_NIDSTR_SIZE, LPX64, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, lcfg_type_data::ltd_bufs, lcfg_type_data::ltd_name, LUSTRE_CFG_BUFLEN, lustre_cfg_sanity_check(), lustre_cfg_string(), and OBD_CFG_REC.
Referenced by llog_print_cb().
void class_decref (struct obd_device * obd, const char * scope, const void * source)
Definition at line 729 of file obd_config.c.
References CDEBUG, CERROR, class_release_dev(), class_unlink_export(), D_CONFIG, D_INFO, obd_export::exp_flags, exp_flags_from_obd(), obd_export::exp_lock, LASSERT, lu_ref_del(), obd_device::obd_attached, obd_cleanup(), obd_device::obd_dev_lock, obd_device::obd_name, obd_device::obd_refcount, obd_device::obd_reference, obd_device::obd_self_export, obd_device::obd_stopping, obd_device::obd_uuid, and obd_uuid::uuid.
Referenced by class_cleanup(), class_detach(), class_export_destroy(), class_import_destroy(), class_notify_sptlrpc_conf(), lprocfs_mds_evict_client_seq_write(), mgc_fs_cleanup(), and ping_evictor_main().
static int class_del_conn (struct obd_device * obd, struct lustre_cfg * lcfg) [static]
Remove a failover nid location.
Definition at line 810 of file obd_config.c.
References CERROR, client_obd::cl_import, obd_device::cli, ENTRY, LUSTRE_CFG_BUFLEN, lustre_cfg_string(), LUSTRE_MDC_NAME, LUSTRE_OSC_NAME, obd_del_conn(), obd_str2uuid(), obd_device::obd_type, RETURN, obd_type::typ_name, and obd_device::u.
Referenced by class_process_config().
void class_del_profile (const char * prof)
Definition at line 919 of file obd_config.c.
References CDEBUG, class_get_profile(), class_put_profile(), D_CONFIG, ENTRY, EXIT, list_del(), lustre_profile::lp_list, lustre_profile::lp_list_deleted, and lustre_profile::lp_refs.
Referenced by class_process_config(), and ll_put_super().
void class_del_profiles (void)
Definition at line 966 of file obd_config.c.
References class_put_profile(), ENTRY, EXIT, list_del(), list_for_each_entry_safe, lustre_profile::lp_list, and lustre_profile::lp_list_deleted.
Referenced by mgc_cleanup().
int class_detach (struct obd_device * obd, struct lustre_cfg * lcfg)
We have finished using this obd and are ready to destroy it.
There can be no more references to this obd.
Definition at line 586 of file obd_config.c.
References CDEBUG, CERROR, class_decref(), D_IOCTL, ENTRY, obd_device::obd_attached, obd_device::obd_dev_lock, obd_device::obd_minor, obd_device::obd_name, obd_device::obd_set_up, obd_device::obd_uuid, RETURN, and obd_uuid::uuid.
Referenced by class_process_config(), mdt_quota_init(), and mdt_stack_init().
struct lustre_profile* class_get_profile (const char * prof) [read]
Definition at line 844 of file obd_config.c.
References ENTRY, list_for_each_entry, lustre_profile::lp_list, lustre_profile::lp_profile, lustre_profile::lp_refs, and RETURN.
Referenced by class_del_profile(), ll_fill_super(), mdt_quota_init(), mdt_stack_init(), and server_put_super().
struct obd_device* class_incref (struct obd_device * obd, const char * scope, const void * source) [read]
Definition at line 717 of file obd_config.c.
References CDEBUG, D_INFO, lu_ref_add_atomic(), obd_device::obd_name, obd_device::obd_refcount, and obd_device::obd_reference.
Referenced by class_new_export(), class_new_import(), class_notify_sptlrpc_conf(), class_setup(), lprocfs_mds_evict_client_seq_write(), mgc_fs_setup(), and ping_evictor_wake().
int class_manual_cleanup (struct obd_device * obd)
Call class_cleanup and class_detach.
"Manual" only in the sense that we're faking lcfg commands.
Definition at line 1909 of file obd_config.c.
References CDEBUG, CERROR, class_process_config(), D_CONFIG, ENTRY, GOTO, LCFG_CLEANUP, lustre_cfg::lcfg_command, LCFG_DETACH, lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), obd_device::obd_fail, obd_device::obd_force, obd_device::obd_name, and RETURN.
Referenced by __lov_del_obd(), ll_put_super(), lod_obd_disconnect(), lustre_stop_lwp(), lustre_stop_mgc(), mdd_obd_disconnect(), mdt_quota_init(), osd_obd_disconnect(), osd_start(), osp_obd_disconnect(), qmt_device_obd_disconnect(), server_put_super(), server_stop_mgs(), and server_stop_servers().
static int class_parse_value (char * buf, int opc, void * value, char ** endh, int quiet) [static]
Definition at line 236 of file obd_config.c.
References CLASS_PARSE_NET, CLASS_PARSE_NID, LBUG, parse_net(), and parse_nid().
Referenced by class_parse_net(), class_parse_nid(), and class_parse_nid_quiet().
int class_process_config (struct lustre_cfg * lcfg)
Process configuration commands given in lustre_cfg form.
These may come from direct calls (e.g. class_manual_cleanup) or processing the config llog, or ioctl from lctl.
Definition at line 1142 of file obd_config.c.
References CDEBUG, CERROR, class_add_conn(), class_add_profile(), class_add_uuid(), class_attach(), class_cleanup(), class_del_conn(), class_del_profile(), class_del_uuid(), class_detach(), class_match_param(), class_name2obd(), class_set_global(), class_setup(), client_process_config, cfg_marker::cm_comment, cfg_marker::cm_flags, cfg_marker::cm_step, cfg_marker::cm_tgtname, CWARN, D_IOCTL, GOTO, LASSERT, LCFG_ADD_CONN, LCFG_ADD_UUID, LCFG_ATTACH, lustre_cfg::lcfg_bufcount, LCFG_CLEANUP, lustre_cfg::lcfg_command, LCFG_DEL_CONN, LCFG_DEL_MOUNTOPT, LCFG_DEL_UUID, LCFG_DETACH, LCFG_MARKER, LCFG_MOUNTOPT, lustre_cfg::lcfg_nid, lustre_cfg::lcfg_num, LCFG_PARAM, LCFG_POOL_ADD, LCFG_POOL_DEL, LCFG_POOL_NEW, LCFG_POOL_REM, LCFG_REQUIRED, LCFG_SET_LDLM_TIMEOUT, LCFG_SET_PARAM, LCFG_SET_TIMEOUT, LCFG_SET_UPCALL, LCFG_SETUP, LCONSOLE_ERROR_MSG, ldlm_timeout, ldlm_timeout_set, libcfs_nid2str(), LPX64, lustre_cfg_buf(), LUSTRE_CFG_BUFLEN, lustre_cfg_string(), max, obd_pool_add(), obd_pool_del(), obd_pool_new(), obd_pool_rem(), obd_process_config(), obd_timeout, obd_timeout_set, PARAM_LLITE, PARAM_QUOTA, PARAM_SYS, process_param2_config(), and quota_process_config.
Referenced by class_config_llog_handler(), class_handle_ioctl(), class_manual_cleanup(), do_lcfg(), mgc_apply_recover_logs(), and mgs_write_log_sys().
int class_process_proc_param (char * prefix, struct lprocfs_vars * lvars, struct lustre_cfg * lcfg, void * data)
Definition at line 1322 of file obd_config.c.
References CDEBUG, CERROR, class_match_param(), D_CONFIG, ENTRY, lprocfs_vars::fops, lustre_cfg::lcfg_bufcount, lustre_cfg::lcfg_command, LCFG_PARAM, lustre_cfg_buf(), lustre_cfg_string(), lprocfs_vars::name, name, and RETURN.
Referenced by ll_process_config(), lod_process_config(), lov_process_config_base(), mdc_process_config(), mdd_process_config(), mdt_process_config(), ofd_process_config(), osc_process_config_base(), osd_process_config(), and osp_process_config().
void class_put_profile (struct lustre_profile * lprof)
Definition at line 941 of file obd_config.c.
References LASSERT, lustre_profile::lp_dt, lustre_profile::lp_list_deleted, lustre_profile::lp_md, lustre_profile::lp_profile, lustre_profile::lp_refs, and OBD_FREE.
Referenced by class_del_profile(), class_del_profiles(), ll_fill_super(), mdt_quota_init(), mdt_stack_init(), and server_put_super().
static int class_set_global (char * ptr, int val, struct lustre_cfg * lcfg) [static]
Definition at line 986 of file obd_config.c.
References at_early_margin, at_extra, at_history, at_max, at_min, CDEBUG, class_match_param(), D_IOCTL, ENTRY, JOBSTATS_JOBID_VAR_MAX_LEN, lustre_cfg_string(), obd_jobid_var, PARAM_AT_EARLY_MARGIN, PARAM_AT_EXTRA, PARAM_AT_HISTORY, PARAM_AT_MAX, PARAM_AT_MIN, PARAM_JOBID_VAR, RETURN, and strlcpy().
Referenced by class_process_config().
int class_setup (struct obd_device * obd, struct lustre_cfg * lcfg)
Create hashes, self-export, and call type-specific setup.
Setup is effectively the "start this obd" call.
Definition at line 445 of file obd_config.c.
References CDEBUG, CERROR, cfs_hash_create(), CFS_HASH_DEFAULT, CFS_HASH_MAX_THETA, CFS_HASH_MIN_THETA, cfs_hash_putref(), class_export_put(), class_incref(), class_new_export(), class_num2obd(), class_unlink_export(), D_IOCTL, ENTRY, obd_export::exp_obd_chain_timed, gen_hash_ops, GOTO, HASH_GEN_BKT_BITS, HASH_GEN_CUR_BITS, HASH_GEN_MAX_BITS, HASH_NID_BKT_BITS, HASH_NID_CUR_BITS, HASH_NID_MAX_BITS, HASH_NID_STATS_BKT_BITS, HASH_NID_STATS_CUR_BITS, HASH_NID_STATS_MAX_BITS, HASH_UUID_BKT_BITS, HASH_UUID_CUR_BITS, HASH_UUID_MAX_BITS, LASSERT, LASSERTF, list_del_init(), nid_hash_ops, nid_stat_hash_ops, obd_device::obd_attached, obd_device::obd_dev_lock, OBD_DEVICE_MAGIC, obd_device::obd_gen_hash, obd_device::obd_magic, obd_device::obd_minor, obd_device::obd_name, obd_device::obd_nid_hash, obd_device::obd_nid_stats_hash, obd_device::obd_self_export, obd_device::obd_set_up, obd_setup(), obd_device::obd_starting, obd_device::obd_type, obd_device::obd_uuid, obd_device::obd_uuid_hash, RETURN, obd_type::typ_name, obd_uuid::uuid, and uuid_hash_ops.
Referenced by class_process_config(), mdt_quota_init(), and mdt_stack_init().
static DEFINE_SPINLOCK (lustre_profile_list_lock) [static]
static void gen_export_get (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 2191 of file obd_config.c.
References class_export_get(), obd_export::exp_gen_hash, and hlist_entry.
static void* gen_export_object (struct hlist_node * hnode) [static]
Definition at line 2185 of file obd_config.c.
References obd_export::exp_gen_hash, and hlist_entry.
static void gen_export_put_locked (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 2200 of file obd_config.c.
References class_export_put(), obd_export::exp_gen_hash, and hlist_entry.
static unsigned gen_hash (struct cfs_hash * hs, const void * key, unsigned mask) [static]
Definition at line 2153 of file obd_config.c.
References cfs_hash_djb2_hash().
static int gen_kepcmp (const void * key, struct hlist_node * hnode) [static]
Definition at line 2173 of file obd_config.c.
References obd_export::exp_failed, obd_export::exp_gen_hash, hlist_entry, LASSERT, and RETURN.
static void* gen_key (struct hlist_node * hnode) [static]
Definition at line 2159 of file obd_config.c.
References obd_export::exp_gen_hash, hlist_entry, and RETURN.
static struct lcfg_type_data* lcfg_cmd2data (__u32 cmd) [static, read]
Definition at line 1751 of file obd_config.c.
References lcfg_data_table, and lcfg_type_data::ltd_type.
Referenced by class_config_yaml_output().
struct lustre_cfg* lustre_cfg_rename (struct lustre_cfg * cfg, const char * new_name) [read]
Rename the proc parameter in cfg with a new name new_name.
Parameters:
cfg config structure which contains the proc parameter
new_name new name of the proc parameter
Return values:
valid-pointer pointer to the newly-allocated config structure which contains the renamed proc parameter
ERR_PTR(-EINVAL) if cfg or new_name is NULL, or cfg does not contain a proc parameter
ERR_PTR(-ENOMEM) if memory allocation failure occurs
Definition at line 1033 of file obd_config.c.
References ENTRY, lustre_cfg::lcfg_command, lustre_cfg::lcfg_flags, lustre_cfg::lcfg_nal, lustre_cfg::lcfg_nid, lustre_cfg::lcfg_num, LUSTRE_CFG_BUFLEN, lustre_cfg_bufs_init(), lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_new(), lustre_cfg_string(), OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, and RETURN.
Referenced by mdt_process_config(), and ofd_process_config().
void lustre_register_client_process_config (int(*)(struct lustre_cfg *lcfg) cpc)
Definition at line 1015 of file obd_config.c.
References client_process_config.
Referenced by lustre_exit(), and lustre_init().
void lustre_register_quota_process_config (int(*)(struct lustre_cfg *lcfg) qpc)
Definition at line 1132 of file obd_config.c.
References quota_process_config.
Referenced by qsd_glb_fini(), and qsd_glb_init().
static void nid_export_get (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 2067 of file obd_config.c.
References class_export_get(), obd_export::exp_nid_hash, and hlist_entry.
static void* nid_export_object (struct hlist_node * hnode) [static]
Definition at line 2061 of file obd_config.c.
References obd_export::exp_nid_hash, and hlist_entry.
static void nid_export_put_locked (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 2076 of file obd_config.c.
References class_export_put(), obd_export::exp_nid_hash, and hlist_entry.
static unsigned nid_hash (struct cfs_hash * hs, const void * key, unsigned mask) [static]
Definition at line 2029 of file obd_config.c.
References cfs_hash_djb2_hash().
Referenced by nidstats_get(), nidstats_key(), nidstats_object(), nidstats_put_locked(), and obd_export_evict_by_nid().
static int nid_kepcmp (const void * key, struct hlist_node * hnode) [static]
Definition at line 2049 of file obd_config.c.
References ptlrpc_connection::c_peer, obd_export::exp_connection, obd_export::exp_failed, obd_export::exp_nid_hash, hlist_entry, LASSERT, lnet_process_id_t::nid, and RETURN.
static void* nid_key (struct hlist_node * hnode) [static]
Definition at line 2035 of file obd_config.c.
References ptlrpc_connection::c_peer, obd_export::exp_connection, obd_export::exp_nid_hash, hlist_entry, lnet_process_id_t::nid, and RETURN.
Referenced by obd_export_evict_by_nid().
static void nidstats_get (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 2121 of file obd_config.c.
References hlist_entry, nid_hash(), and nidstat_getref.
static void* nidstats_key (struct hlist_node * hnode) [static]
Definition at line 2099 of file obd_config.c.
References hlist_entry, nid_stat::nid, and nid_hash().
Referenced by nidstats_keycmp().
static int nidstats_keycmp (const void * key, struct hlist_node * hnode) [static]
Definition at line 2109 of file obd_config.c.
References nidstats_key().
static void* nidstats_object (struct hlist_node * hnode) [static]
Definition at line 2115 of file obd_config.c.
References hlist_entry, and nid_hash().
static void nidstats_put_locked (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 2130 of file obd_config.c.
References hlist_entry, nid_hash(), and nidstat_putref.
static int parse_net (char * buf, void * value) [static]
Definition at line 218 of file obd_config.c.
References CDEBUG, D_INFO, libcfs_net2str(), and libcfs_str2net().
Referenced by class_parse_value().
static int parse_nid (char * buf, void * value, int quiet) [static]
Definition at line 205 of file obd_config.c.
References LCONSOLE_ERROR_MSG, libcfs_str2nid(), and LNET_NID_ANY.
Referenced by class_parse_value().
static int process_param2_config (struct lustre_cfg * lcfg) [static]
Definition at line 1093 of file obd_config.c.
References CDEBUG, CERROR, cfs_timeval_sub(), D_HA, ENTRY, LCTL_UPCALL, lustre_cfg_string(), and RETURN.
Referenced by class_process_config().
static void uuid_export_get (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 1997 of file obd_config.c.
References class_export_get(), obd_export::exp_uuid_hash, and hlist_entry.
static void* uuid_export_object (struct hlist_node * hnode) [static]
Definition at line 1991 of file obd_config.c.
References obd_export::exp_uuid_hash, and hlist_entry.
static void uuid_export_put_locked (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 2006 of file obd_config.c.
References class_export_put(), obd_export::exp_uuid_hash, and hlist_entry.
static unsigned uuid_hash (struct cfs_hash * hs, const void * key, unsigned mask) [static]
Definition at line 1958 of file obd_config.c.
References cfs_hash_djb2_hash(), and uuid.
Referenced by obd_export_evict_by_uuid().
static void* uuid_key (struct hlist_node * hnode) [static]
Definition at line 1965 of file obd_config.c.
References obd_export::exp_client_uuid, obd_export::exp_uuid_hash, and hlist_entry.
static int uuid_keycmp (const void * key, struct hlist_node * hnode) [static]
Definition at line 1979 of file obd_config.c.
References obd_export::exp_client_uuid, obd_export::exp_failed, obd_export::exp_uuid_hash, hlist_entry, LASSERT, and obd_uuid_equals().
Variable Documentation
int(* client_process_config)(struct lustre_cfg *lcfg) = NULL [static]
Referenced by class_process_config(), and lustre_register_client_process_config().
static struct cfs_hash_ops gen_hash_ops [static, read]
Initial value:
 {
        .hs_hash        = gen_hash,
        .hs_key         = gen_key,
        .hs_keycmp      = gen_kepcmp,
        .hs_object      = gen_export_object,
        .hs_get         = gen_export_get,
        .hs_put_locked  = gen_export_put_locked,
}
Definition at line 58 of file obd_config.c.
Referenced by class_setup().
struct lcfg_type_data lcfg_data_table[] [static]
Referenced by lcfg_cmd2data().
struct list_head lustre_profile_list [static]
Initial value:
        LIST_HEAD_INIT(lustre_profile_list)
Definition at line 840 of file obd_config.c.
static struct cfs_hash_ops nid_hash_ops [static, read]
Initial value:
 {
        .hs_hash        = nid_hash,
        .hs_key         = nid_key,
        .hs_keycmp      = nid_kepcmp,
        .hs_object      = nid_export_object,
        .hs_get         = nid_export_get,
        .hs_put_locked  = nid_export_put_locked,
}
Definition at line 56 of file obd_config.c.
Referenced by class_setup().
static struct cfs_hash_ops nid_stat_hash_ops [static, read]
Initial value:
 {
        .hs_hash        = nid_hash,
        .hs_key         = nidstats_key,
        .hs_keycmp      = nidstats_keycmp,
        .hs_object      = nidstats_object,
        .hs_get         = nidstats_get,
        .hs_put_locked  = nidstats_put_locked,
}
Definition at line 57 of file obd_config.c.
Referenced by class_setup().
int(* quota_process_config)(struct lustre_cfg *lcfg) = NULL [static]
Referenced by class_process_config(), and lustre_register_quota_process_config().
static struct cfs_hash_ops uuid_hash_ops [static, read]
Initial value:
 {
        .hs_hash        = uuid_hash,
        .hs_key         = uuid_key,
        .hs_keycmp      = uuid_keycmp,
        .hs_object      = uuid_export_object,
        .hs_get         = uuid_export_get,
        .hs_put_locked  = uuid_export_put_locked,
}
Definition at line 55 of file obd_config.c.
Referenced by class_setup().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.