Lustre: lustre/utils/obd.c File Reference
lustre/utils/obd.c File Reference
#include <sys/ioctl.h>
#include <sys/socket.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/types.h>
#include <sys/un.h>
#include <sys/wait.h>
#include <ctype.h>
#include <errno.h>
#include <fcntl.h>
#include <getopt.h>
#include <signal.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include <limits.h>
#include "obdctl.h"
#include <libcfs/util/ioctl.h>
#include <libcfs/util/param.h>
#include <libcfs/util/parser.h>
#include <lnet/nidstr.h>
#include <lustre/lustre_idl.h>
#include <lustre_cfg.h>
#include <lustre_ioctl.h>
#include <lustre_ver.h>
#include <lnet/lnetctl.h>
#include <lustre/lustreapi.h>
#include <lustre_param.h>
Data Structures
struct jt_fid_space
Defines
#define MAX_STRING_SIZE 128
#define BAD_VERBOSE (-999999999)
#define N2D_OFF 0x100
#define difftime(a, b)
#define MD_STEP_COUNT 1000
Functions
static int l2_ioctl (int dev_id, int opc, void *buf)
int lcfg_ioctl (char *func, int dev_id, struct lustre_cfg *lcfg)
static int do_device (char *func, char *devname)
static int get_mgs_device ()
int lcfg_mgs_ioctl (char *func, int dev_id, struct lustre_cfg *lcfg)
char * obdo_print (struct obdo *obd)
static int do_name2dev (char *func, char *name)
int parse_devname (char *func, char *name)
char * jt_cmdname (char *func)
static int be_verbose (int verbose, struct timeval *next_time, __u64 num, __u64 *next_num, int num_total)
static int get_verbose (char *func, const char *arg)
int do_disconnect (char *func, int verbose)
static int shmem_setup (void)
static void shmem_reset (int total_threads)
static void shmem_bump (__u32 counters)
static void shmem_lock ()
static void shmem_unlock ()
static void shmem_cleanup (void)
static int shmem_running (void)
int jt_obd_get_device ()
int jt_obd_device (int argc, char **argv)
int jt_opt_device (int argc, char **argv)
int jt_opt_threads (int argc, char **argv)
int jt_opt_net (int argc, char **argv)
int jt_obd_no_transno (int argc, char **argv)
int jt_obd_set_readonly (int argc, char **argv)
int jt_obd_abort_recovery (int argc, char **argv)
int jt_get_version (int argc, char **argv)
static void print_obd_line (char *s)
int jt_obd_list_ioctl (int argc, char **argv)
int jt_obd_list (int argc, char **argv)
int jt_obd_alloc_fids (struct jt_fid_space *space, struct lu_fid *fid, __u64 *count)
int jt_obd_md_common (int argc, char **argv, int cmd)
int jt_obd_test_create (int argc, char **argv)
int jt_obd_test_mkdir (int argc, char **argv)
int jt_obd_test_destroy (int argc, char **argv)
int jt_obd_test_rmdir (int argc, char **argv)
int jt_obd_test_lookup (int argc, char **argv)
int jt_obd_test_setxattr (int argc, char **argv)
int jt_obd_test_md_getattr (int argc, char **argv)
int jt_obd_create (int argc, char **argv)
int jt_obd_setattr (int argc, char **argv)
int jt_obd_test_setattr (int argc, char **argv)
int jt_obd_destroy (int argc, char **argv)
int jt_obd_getattr (int argc, char **argv)
int jt_obd_test_getattr (int argc, char **argv)
int jt_obd_test_brw (int argc, char **argv)
int jt_obd_lov_getconfig (int argc, char **argv)
static int do_activate (int argc, char **argv, int flag)
int jt_replace_nids (int argc, char **argv)
Replace nids for given device.
int jt_obd_deactivate (int argc, char **argv)
int jt_obd_activate (int argc, char **argv)
int jt_obd_recover (int argc, char **argv)
int jt_obd_mdc_lookup (int argc, char **argv)
int jt_llog_catlist (int argc, char **argv)
int jt_llog_info (int argc, char **argv)
int jt_llog_print (int argc, char **argv)
static int llog_cancel_parse_optional (int argc, char **argv, struct obd_ioctl_data *data)
int jt_llog_cancel (int argc, char **argv)
int jt_llog_check (int argc, char **argv)
int jt_llog_remove (int argc, char **argv)
static int jt_blockdev_run_process (const char *file, char *argv[])
static int jt_blockdev_find_module (const char *module)
static int jt_blockdev_probe_module (const char *module)
int jt_blockdev_attach (int argc, char **argv)
int jt_blockdev_detach (int argc, char **argv)
int jt_blockdev_info (int argc, char **argv)
static void signal_server (int sig)
int obd_initialize (int argc, char **argv)
void obd_finalize (int argc, char **argv)
static int check_pool_cmd (enum lcfg_command_type cmd, char *fsname, char *poolname, char *ostname)
static int check_pool_cmd_result (enum lcfg_command_type cmd, char *fsname, char *poolname, char *ostname)
static int check_and_complete_ostname (char *fsname, char *ostname)
static int pool_cmd (enum lcfg_command_type cmd, char *cmdname, char *fullpoolname, char *fsname, char *poolname, char *ostname)
static int nodemap_cmd (enum lcfg_command_type cmd, void *ret_data, unsigned int ret_size,...)
Format and send the ioctl to the MGS.
int jt_nodemap_activate (int argc, char **argv)
activate nodemap functions
int jt_nodemap_add (int argc, char **argv)
add a nodemap
int jt_nodemap_del (int argc, char **argv)
delete a nodemap
int jt_nodemap_test_nid (int argc, char **argv)
test a nid for nodemap membership
int jt_nodemap_test_id (int argc, char **argv)
test a nodemap id pair for mapping
int jt_nodemap_add_range (int argc, char **argv)
add an nid range to a nodemap
int jt_nodemap_del_range (int argc, char **argv)
delete an nid range to a nodemap
int jt_nodemap_modify (int argc, char **argv)
modify a nodemap's behavior
int jt_nodemap_add_idmap (int argc, char **argv)
int jt_nodemap_del_idmap (int argc, char **argv)
static int get_array_idx (char *rule, char *format, int **array)
static int extract_fsname_poolname (const char *arg, char *fsname, char *poolname)
int jt_pool_cmd (int argc, char **argv)
int jt_get_obj_version (int argc, char **argv)
int jt_changelog_register (int argc, char **argv)
int jt_changelog_deregister (int argc, char **argv)
Variables
const int thread = 0
const int nthreads = 1
static int cur_device = -1
command_t cmdlist []
Define Documentation
#define BAD_VERBOSE (-999999999)
Definition at line 223 of file obd.c.
Referenced by get_verbose(), jt_obd_create(), jt_obd_destroy(), jt_obd_test_brw(), jt_obd_test_getattr(), and jt_obd_test_setattr().
#define difftime (a, b)
Value:
((a)->tv_sec - (b)->tv_sec +                    \
         ((a)->tv_usec - (b)->tv_usec) / 1000000.0)
Definition at line 298 of file obd.c.
#define MAX_STRING_SIZE 128
Definition at line 82 of file obd.c.
#define MD_STEP_COUNT 1000
Definition at line 1129 of file obd.c.
Referenced by jt_obd_md_common().
#define N2D_OFF 0x100
Definition at line 225 of file obd.c.
Referenced by do_name2dev(), and parse_devname().
Function Documentation
static int be_verbose (int verbose, struct timeval * next_time, __u64 num, __u64 * next_num, int num_total) [static]
Definition at line 302 of file obd.c.
References difftime.
Referenced by jt_obd_create(), jt_obd_destroy(), jt_obd_test_brw(), jt_obd_test_getattr(), and jt_obd_test_setattr().
static int check_and_complete_ostname (char * fsname, char * ostname) [static]
Definition at line 3127 of file obd.c.
References MAX_OBD_NAME.
Referenced by jt_pool_cmd().
static int check_pool_cmd (enum lcfg_command_type cmd, char * fsname, char * poolname, char * ostname) [static]
Definition at line 2971 of file obd.c.
References LASSERT, LCFG_POOL_ADD, LCFG_POOL_DEL, LCFG_POOL_NEW, LCFG_POOL_REM, and llapi_search_ost().
Referenced by pool_cmd().
static int check_pool_cmd_result (enum lcfg_command_type cmd, char * fsname, char * poolname, char * ostname) [static]
Definition at line 3037 of file obd.c.
References LCFG_POOL_ADD, LCFG_POOL_DEL, LCFG_POOL_NEW, LCFG_POOL_REM, and llapi_search_ost().
Referenced by jt_pool_cmd().
static int do_activate (int argc, char ** argv, int flag) [static]
Definition at line 2249 of file obd.c.
References buf, CMD_HELP, cur_device, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_offset, IOC_OSC_SET_ACTIVE, jt_cmdname(), l2_ioctl(), MAX_IOC_BUFLEN, OBD_DEV_ID, obd_ioctl_pack(), and rawbuf.
Referenced by jt_obd_activate(), and jt_obd_deactivate().
static int do_device (char * func, char * devname) [static]
Definition at line 620 of file obd.c.
References cur_device, lcfg_set_devname(), and parse_devname().
Referenced by get_mgs_device(), jt_obd_device(), and jt_opt_device().
int do_disconnect (char * func, int verbose)
Definition at line 363 of file obd.c.
References cur_device, and lcfg_set_devname().
Referenced by get_mgs_device(), jt_opt_device(), obd_finalize(), and signal_server().
static int do_name2dev (char * func, char * name) [static]
Definition at line 227 of file obd.c.
References buf, cur_device, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inllen1, jt_cmdname(), l2_ioctl(), MAX_IOC_BUFLEN, N2D_OFF, OBD_DEV_ID, OBD_IOC_NAME2DEV, obd_ioctl_pack(), obd_ioctl_unpack(), and rawbuf.
Referenced by parse_devname().
static int extract_fsname_poolname (const char * arg, char * fsname, char * poolname) [static]
Definition at line 4004 of file obd.c.
References LOV_MAXPOOLNAME, lustre_is_fsname_valid(), lustre_is_poolname_valid(), LUSTRE_MAXFSNAME, and strlcpy().
Referenced by jt_pool_cmd().
static int get_array_idx (char * rule, char * format, int ** array) [static]
Definition at line 3924 of file obd.c.
References start.
Referenced by jt_pool_cmd().
static int get_mgs_device () [static]
Definition at line 152 of file obd.c.
References cur_device, do_device(), and do_disconnect().
Referenced by jt_replace_nids(), lcfg_mgs_ioctl(), nodemap_cmd(), and pool_cmd().
static int get_verbose (char * func, const char * arg) [static]
Definition at line 335 of file obd.c.
References BAD_VERBOSE, end, jt_cmdname(), and verbose.
Referenced by jt_obd_create(), jt_obd_destroy(), jt_obd_mdc_lookup(), jt_obd_test_brw(), jt_obd_test_getattr(), and jt_obd_test_setattr().
int jt_blockdev_attach (int argc, char ** argv)
Definition at line 2818 of file obd.c.
References CMD_HELP, devname, filename, jt_blockdev_probe_module(), LL_IOC_LLOOP_ATTACH, and LL_IOC_LLOOP_DETACH_BYDEV.
int jt_blockdev_detach (int argc, char ** argv)
Definition at line 2875 of file obd.c.
References CMD_HELP, filename, and LL_IOC_LLOOP_DETACH.
static int jt_blockdev_find_module (const char * module) [static]
Definition at line 2764 of file obd.c.
References buf.
Referenced by jt_blockdev_probe_module().
int jt_blockdev_info (int argc, char ** argv)
Definition at line 2903 of file obd.c.
References CMD_HELP, DFID, fid_is_zero(), filename, LL_IOC_LLOOP_INFO, and PFID.
static int jt_blockdev_probe_module (const char * module) [static]
Definition at line 2789 of file obd.c.
References buf, jt_blockdev_find_module(), and jt_blockdev_run_process().
Referenced by jt_blockdev_attach().
static int jt_blockdev_run_process (const char * file, char * argv[]) [static]
Definition at line 2740 of file obd.c.
Referenced by jt_blockdev_probe_module().
int jt_changelog_deregister (int argc, char ** argv)
Definition at line 4329 of file obd.c.
References buf, CHANGELOG_USER_PREFIX, CMD_HELP, cur_device, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_u32_1, jt_cmdname(), l2_ioctl(), lcfg_get_devname(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_CHANGELOG_DEREG, obd_ioctl_pack(), obd_ioctl_unpack(), and rawbuf.
int jt_changelog_register (int argc, char ** argv)
Definition at line 4269 of file obd.c.
References buf, CHANGELOG_USER_PREFIX, CMD_HELP, cur_device, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_u32_1, jt_cmdname(), l2_ioctl(), lcfg_get_devname(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_CHANGELOG_REG, obd_ioctl_pack(), obd_ioctl_unpack(), and rawbuf.
char* jt_cmdname (char * func)
Definition at line 286 of file obd.c.
References buf, and thread.
Referenced by do_activate(), do_name2dev(), get_verbose(), jt_changelog_deregister(), jt_changelog_register(), jt_get_obj_version(), jt_get_version(), jt_lcfg_add_conn(), jt_lcfg_attach(), jt_lcfg_del_conn(), jt_lcfg_del_mount_option(), jt_lcfg_getparam(), jt_lcfg_listparam(), jt_lcfg_mgsparam(), jt_lcfg_mgsparam2(), jt_lcfg_param(), jt_lcfg_set_timeout(), jt_lcfg_setparam(), jt_lcfg_setup(), jt_llog_cancel(), jt_llog_catlist(), jt_llog_check(), jt_llog_info(), jt_llog_print(), jt_llog_remove(), jt_nodemap_add_range(), jt_nodemap_del_range(), jt_nodemap_modify(), jt_obd_abort_recovery(), jt_obd_cleanup(), jt_obd_create(), jt_obd_destroy(), jt_obd_detach(), jt_obd_getattr(), jt_obd_list(), jt_obd_lov_getconfig(), jt_obd_md_common(), jt_obd_mdc_lookup(), jt_obd_no_transno(), jt_obd_recover(), jt_obd_set_readonly(), jt_obd_setattr(), jt_obd_test_brw(), jt_obd_test_getattr(), jt_obd_test_setattr(), jt_opt_threads(), jt_replace_nids(), lcfg_ioctl(), lcfg_mgs_ioctl(), pool_cmd(), and signal_server().
int jt_get_obj_version (int argc, char ** argv)
Definition at line 4202 of file obd.c.
References __u64, buf, CMD_HELP, cur_device, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf2, obd_ioctl_data::ioc_inlbuf3, obd_ioctl_data::ioc_inlbuf4, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, obd_ioctl_data::ioc_inllen3, obd_ioctl_data::ioc_inllen4, jt_cmdname(), l2_ioctl(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_GET_OBJ_VERSION, obd_ioctl_pack(), obd_ioctl_unpack(), optarg, optind, rawbuf, RFID, SFID, and version.
int jt_get_version (int argc, char ** argv)
Definition at line 928 of file obd.c.
References CMD_HELP, jt_cmdname(), llapi_get_version(), MAX_IOC_BUFLEN, rawbuf, and version.
int jt_llog_cancel (int argc, char ** argv)
Definition at line 2588 of file obd.c.
References buf, CMD_HELP, cur_device, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf2, obd_ioctl_data::ioc_inlbuf3, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, obd_ioctl_data::ioc_inllen3, jt_cmdname(), l_ioctl(), llog_cancel_parse_optional(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_LLOG_CANCEL, obd_ioctl_pack(), and rawbuf.
int jt_llog_catlist (int argc, char ** argv)
Definition at line 2428 of file obd.c.
References buf, cfs_size_round(), CMD_HELP, cur_device, obd_ioctl_data::ioc_bulk, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_inllen1, jt_cmdname(), l_ioctl(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_CATLOGLIST, obd_ioctl_pack(), and rawbuf.
int jt_llog_check (int argc, char ** argv)
Definition at line 2649 of file obd.c.
References buf, cfs_size_round(), CMD_HELP, cur_device, obd_ioctl_data::ioc_bulk, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf2, obd_ioctl_data::ioc_inlbuf3, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, obd_ioctl_data::ioc_inllen3, obd_ioctl_data::ioc_inllen4, jt_cmdname(), l_ioctl(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_LLOG_CHECK, obd_ioctl_pack(), and rawbuf.
int jt_llog_info (int argc, char ** argv)
Definition at line 2457 of file obd.c.
References buf, cfs_size_round(), CMD_HELP, cur_device, obd_ioctl_data::ioc_bulk, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, jt_cmdname(), l_ioctl(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_LLOG_INFO, obd_ioctl_pack(), and rawbuf.
int jt_llog_print (int argc, char ** argv)
Definition at line 2490 of file obd.c.
References buf, cfs_size_round(), CMD_HELP, cur_device, obd_ioctl_data::ioc_bulk, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf2, obd_ioctl_data::ioc_inlbuf3, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, obd_ioctl_data::ioc_inllen3, obd_ioctl_data::ioc_inllen4, jt_cmdname(), l_ioctl(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_LLOG_PRINT, obd_ioctl_pack(), and rawbuf.
int jt_llog_remove (int argc, char ** argv)
Definition at line 2695 of file obd.c.
References buf, CMD_HELP, cur_device, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf2, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, jt_cmdname(), l_ioctl(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_LLOG_REMOVE, obd_ioctl_pack(), and rawbuf.
int jt_nodemap_activate (int argc, char ** argv)
activate nodemap functions
Parameters:
argc number of args
argv[] variable string arguments
argv[0] 1 for activate or 0 for deactivate
Return values:
0 on success
Definition at line 3324 of file obd.c.
References LCFG_NODEMAP_ACTIVATE, and nodemap_cmd().
int jt_nodemap_add (int argc, char ** argv)
add a nodemap
Parameters:
argc number of args
argv[] variable string arguments
argv[0] nodemap name
Return values:
0 on success
Definition at line 3349 of file obd.c.
References LCFG_NODEMAP_ADD, llapi_nodemap_exists(), and nodemap_cmd().
int jt_nodemap_add_idmap (int argc, char ** argv)
Definition at line 3771 of file obd.c.
References cmd, LCFG_NODEMAP_ADD_GIDMAP, LCFG_NODEMAP_ADD_UIDMAP, nodemap_cmd(), and optarg.
int jt_nodemap_add_range (int argc, char ** argv)
add an nid range to a nodemap
Parameters:
argc number of args
argv[] variable string arguments
--name nodemap name --range properly formatted nid range
Return values:
0 on success
Definition at line 3508 of file obd.c.
References cfs_nidrange_find_min_max(), cfs_nidrange_is_contiguous(), cfs_parse_nidlist(), INIT_LIST_HEAD, jt_cmdname(), LCFG_NODEMAP_ADD_RANGE, LNET_NIDSTR_SIZE, nodemap_cmd(), and optarg.
int jt_nodemap_del (int argc, char ** argv)
delete a nodemap
Parameters:
argc number of args
argv[] variable string arguments
argv[0] nodemap name
Return values:
0 on success
Definition at line 3379 of file obd.c.
References LCFG_NODEMAP_DEL, llapi_nodemap_exists(), and nodemap_cmd().
int jt_nodemap_del_idmap (int argc, char ** argv)
Definition at line 3845 of file obd.c.
References cmd, LCFG_NODEMAP_DEL_GIDMAP, LCFG_NODEMAP_DEL_UIDMAP, nodemap_cmd(), and optarg.
int jt_nodemap_del_range (int argc, char ** argv)
delete an nid range to a nodemap
Parameters:
argc number of args
argv[] variable string arguments
--name nodemap name --range properly formatted nid range
Return values:
0 on success
Definition at line 3597 of file obd.c.
References cfs_nidrange_find_min_max(), cfs_nidrange_is_contiguous(), cfs_parse_nidlist(), INIT_LIST_HEAD, jt_cmdname(), LCFG_NODEMAP_DEL_RANGE, LNET_NIDSTR_SIZE, nodemap_cmd(), and optarg.
int jt_nodemap_modify (int argc, char ** argv)
modify a nodemap's behavior
Parameters:
argc number of args
argv[] variable string arguments
--name nodemap name --property nodemap property to change admin, trusted, squash_uid, squash_gid) --value value to set property
Return values:
0 on success
Definition at line 3688 of file obd.c.
References cmd, jt_cmdname(), LCFG_NODEMAP_ADMIN, LCFG_NODEMAP_SQUASH_GID, LCFG_NODEMAP_SQUASH_UID, LCFG_NODEMAP_TRUSTED, nodemap_cmd(), and optarg.
int jt_nodemap_test_id (int argc, char ** argv)
test a nodemap id pair for mapping
Parameters:
argc number of args
argv[[] variable string arguments
Return values:
0 on success
The argv array should contain the nodemap name, the id to checking the mapping on, and the id type (UID or GID)
Definition at line 3435 of file obd.c.
References LCFG_NODEMAP_TEST_ID, MAX_IOC_BUFLEN, nodemap_cmd(), optarg, and rawbuf.
int jt_nodemap_test_nid (int argc, char ** argv)
test a nid for nodemap membership
Parameters:
argc number of args
argv[] variable string arguments
argv[0] properly formatted nid
Return values:
0 on success
Definition at line 3409 of file obd.c.
References LCFG_NODEMAP_TEST_NID, MAX_IOC_BUFLEN, nodemap_cmd(), and rawbuf.
int jt_obd_abort_recovery (int argc, char ** argv)
Definition at line 901 of file obd.c.
References buf, CMD_HELP, cur_device, obd_ioctl_data::ioc_dev, jt_cmdname(), l2_ioctl(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_ABORT_RECOVERY, obd_ioctl_pack(), and rawbuf.
int jt_obd_activate (int argc, char ** argv)
Definition at line 2333 of file obd.c.
References do_activate().
int jt_obd_alloc_fids (struct jt_fid_space * space, struct lu_fid * fid, __u64 * count)
Definition at line 1079 of file obd.c.
References __u64, buf, cur_device, lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_pbuf1, obd_ioctl_data::ioc_pbuf2, obd_ioctl_data::ioc_plen1, obd_ioctl_data::ioc_plen2, jt_fid_space::jt_id, jt_fid_space::jt_seq, jt_fid_space::jt_width, l2_ioctl(), max_count, MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_ECHO_ALLOC_SEQ, obd_ioctl_pack(), and rawbuf.
Referenced by jt_obd_md_common().
int jt_obd_create (int argc, char ** argv)
Definition at line 1456 of file obd.c.
References __u64, BAD_VERBOSE, be_verbose(), buf, CMD_HELP, cur_device, get_verbose(), obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_obdo1, jt_cmdname(), l2_ioctl(), MAX_IOC_BUFLEN, mode, obdo::o_gid, obdo::o_mode, obdo::o_oi, obdo::o_uid, obdo::o_valid, OBD_DEV_ID, OBD_IOC_CREATE, obd_ioctl_pack(), obd_ioctl_unpack(), OBD_MD_FLGID, OBD_MD_FLGROUP, OBD_MD_FLID, OBD_MD_FLMODE, OBD_MD_FLTYPE, OBD_MD_FLUID, ostid_id(), ostid_set_id(), ostid_set_seq_echo(), rawbuf, shmem_bump(), and shmem_running().
int jt_obd_deactivate (int argc, char ** argv)
Definition at line 2328 of file obd.c.
References do_activate().
int jt_obd_destroy (int argc, char ** argv)
Definition at line 1676 of file obd.c.
References __u64, BAD_VERBOSE, be_verbose(), buf, CMD_HELP, cur_device, get_verbose(), obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_obdo1, jt_cmdname(), l2_ioctl(), MAX_IOC_BUFLEN, obdo::o_mode, obdo::o_oi, obdo::o_valid, OBD_DEV_ID, OBD_IOC_DESTROY, obd_ioctl_pack(), obd_ioctl_unpack(), OBD_MD_FLID, OBD_MD_FLMODE, ostid_set_id(), ostid_set_seq_echo(), rawbuf, shmem_bump(), and shmem_running().
int jt_obd_device (int argc, char ** argv)
Definition at line 638 of file obd.c.
References CMD_HELP, cur_device, do_device(), and lcfg_get_devname().
Referenced by jt_lcfg_device().
int jt_obd_get_device ()
Definition at line 633 of file obd.c.
References cur_device.
int jt_obd_getattr (int argc, char ** argv)
Definition at line 1749 of file obd.c.
References buf, CMD_HELP, cur_device, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_obdo1, jt_cmdname(), l2_ioctl(), MAX_IOC_BUFLEN, obdo::o_mode, obdo::o_oi, obdo::o_valid, OBD_DEV_ID, OBD_IOC_GETATTR, obd_ioctl_pack(), obd_ioctl_unpack(), ostid_id(), ostid_set_id(), ostid_set_seq_echo(), and rawbuf.
int jt_obd_list (int argc, char ** argv)
Definition at line 1035 of file obd.c.
References buf, cfs_free_param_data(), cfs_get_param_paths(), CMD_HELP, jt_cmdname(), jt_obd_list_ioctl(), MAX_STRING_SIZE, path, and print_obd_line().
int jt_obd_list_ioctl (int argc, char ** argv)
Definition at line 998 of file obd.c.
References buf, cfs_size_round(), CMD_HELP, obd_ioctl_data::ioc_bulk, obd_ioctl_data::ioc_count, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_len, obd_ioctl_data::ioc_version, l2_ioctl(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_GETDEVICE, obd_ioctl_packlen(), OBD_IOCTL_VERSION, and rawbuf.
Referenced by jt_obd_list().
int jt_obd_lov_getconfig (int argc, char ** argv)
Definition at line 2145 of file obd.c.
References buf, CMD_HELP, cur_device, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf2, obd_ioctl_data::ioc_inlbuf3, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, obd_ioctl_data::ioc_inllen3, jt_cmdname(), lov_desc::ld_default_stripe_count, lov_desc::ld_default_stripe_offset, lov_desc::ld_default_stripe_size, lov_desc::ld_pattern, lov_desc::ld_tgt_count, lov_desc::ld_uuid, MAX_IOC_BUFLEN, OBD_IOC_LOV_GET_CONFIG, obd_ioctl_pack(), obd_ioctl_unpack(), OBD_MAX_IOCTL_BUFFER, obd_str2uuid(), path, and rawbuf.
int jt_obd_md_common (int argc, char ** argv, int cmd)
Definition at line 1130 of file obd.c.
References __u64, buf, CMD_HELP, cur_device, difftime, ECHO_MD_CREATE, ECHO_MD_MKDIR, ECHO_MD_RMDIR, fid_to_ostid(), obd_ioctl_data::ioc_command, obd_ioctl_data::ioc_count, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_obdo1, obd_ioctl_data::ioc_obdo2, obd_ioctl_data::ioc_pbuf1, obd_ioctl_data::ioc_pbuf2, obd_ioctl_data::ioc_plen1, obd_ioctl_data::ioc_plen2, jt_cmdname(), jt_obd_alloc_fids(), l2_ioctl(), MAX_IOC_BUFLEN, MD_STEP_COUNT, mode, name, nthreads, obdo::o_misc, obdo::o_mode, obdo::o_oi, obdo::o_stripe_idx, obdo::o_valid, OBD_DEV_ID, OBD_IOC_ECHO_MD, obd_ioctl_pack(), OBD_MD_FLFLAGS, OBD_MD_FLGROUP, OBD_MD_FLID, OBD_MD_FLMODE, OBD_MD_FLTYPE, ost_id::oi, optarg, optind, rawbuf, seconds, shmem_bump(), shmem_lock(), shmem_running(), shmem_unlock(), thread, and version.
Referenced by jt_obd_test_create(), jt_obd_test_destroy(), jt_obd_test_lookup(), jt_obd_test_md_getattr(), jt_obd_test_mkdir(), jt_obd_test_rmdir(), and jt_obd_test_setxattr().
int jt_obd_mdc_lookup (int argc, char ** argv)
Definition at line 2370 of file obd.c.
References buf, CMD_HELP, cur_device, get_verbose(), obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inllen1, IOC_MDC_LOOKUP, obd_ioctl_data::ioc_obdo1, jt_cmdname(), MAX_IOC_BUFLEN, obdo::o_gid, obdo::o_mode, obdo::o_uid, obd_ioctl_pack(), obd_ioctl_unpack(), and rawbuf.
int jt_obd_no_transno (int argc, char ** argv)
Definition at line 847 of file obd.c.
References buf, CMD_HELP, cur_device, obd_ioctl_data::ioc_dev, jt_cmdname(), l2_ioctl(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_NO_TRANSNO, obd_ioctl_pack(), and rawbuf.
int jt_obd_recover (int argc, char ** argv)
Definition at line 2338 of file obd.c.
References buf, CMD_HELP, cur_device, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inllen1, jt_cmdname(), l2_ioctl(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_CLIENT_RECOVER, obd_ioctl_pack(), and rawbuf.
int jt_obd_set_readonly (int argc, char ** argv)
Definition at line 874 of file obd.c.
References buf, CMD_HELP, cur_device, obd_ioctl_data::ioc_dev, jt_cmdname(), l2_ioctl(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_SET_READONLY, obd_ioctl_pack(), and rawbuf.
int jt_obd_setattr (int argc, char ** argv)
Definition at line 1539 of file obd.c.
References buf, CMD_HELP, cur_device, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_obdo1, jt_cmdname(), l2_ioctl(), MAX_IOC_BUFLEN, obdo::o_mode, obdo::o_oi, obdo::o_valid, OBD_DEV_ID, OBD_IOC_SETATTR, obd_ioctl_pack(), OBD_MD_FLID, OBD_MD_FLMODE, OBD_MD_FLTYPE, ostid_set_id(), ostid_set_seq_echo(), and rawbuf.
int jt_obd_test_brw (int argc, char ** argv)
Definition at line 1895 of file obd.c.
References __u64, BAD_VERBOSE, be_verbose(), buf, cmd, CMD_HELP, cur_device, difftime, get_verbose(), obd_ioctl_data::ioc_count, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_obdo1, obd_ioctl_data::ioc_offset, obd_ioctl_data::ioc_pbuf1, obd_ioctl_data::ioc_plen1, jt_cmdname(), l2_ioctl(), MAX_IOC_BUFLEN, obdo::o_flags, obdo::o_mode, obdo::o_oi, obdo::o_valid, OBD_DEV_ID, OBD_FL_DEBUG_CHECK, OBD_IOC_BRW_READ, OBD_IOC_BRW_WRITE, obd_ioctl_pack(), OBD_MD_FLBLOCKS, OBD_MD_FLFLAGS, OBD_MD_FLGRANT, OBD_MD_FLGROUP, OBD_MD_FLID, OBD_MD_FLMODE, OBD_MD_FLTYPE, ostid_id(), ostid_set_id(), ostid_set_seq_echo(), rawbuf, shmem_bump(), shmem_lock(), shmem_running(), shmem_unlock(), and thread.
int jt_obd_test_create (int argc, char ** argv)
Definition at line 1421 of file obd.c.
References ECHO_MD_CREATE, and jt_obd_md_common().
int jt_obd_test_destroy (int argc, char ** argv)
Definition at line 1431 of file obd.c.
References ECHO_MD_DESTROY, and jt_obd_md_common().
int jt_obd_test_getattr (int argc, char ** argv)
Definition at line 1794 of file obd.c.
References __u64, BAD_VERBOSE, be_verbose(), buf, CMD_HELP, cur_device, difftime, get_verbose(), obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_obdo1, jt_cmdname(), l2_ioctl(), MAX_IOC_BUFLEN, obdo::o_mode, obdo::o_oi, obdo::o_valid, OBD_DEV_ID, OBD_IOC_GETATTR, obd_ioctl_pack(), ostid_set_id(), ostid_set_seq_echo(), rawbuf, shmem_bump(), shmem_running(), and thread.
int jt_obd_test_lookup (int argc, char ** argv)
Definition at line 1441 of file obd.c.
References ECHO_MD_LOOKUP, and jt_obd_md_common().
int jt_obd_test_md_getattr (int argc, char ** argv)
Definition at line 1451 of file obd.c.
References ECHO_MD_GETATTR, and jt_obd_md_common().
int jt_obd_test_mkdir (int argc, char ** argv)
Definition at line 1426 of file obd.c.
References ECHO_MD_MKDIR, and jt_obd_md_common().
int jt_obd_test_rmdir (int argc, char ** argv)
Definition at line 1436 of file obd.c.
References ECHO_MD_RMDIR, and jt_obd_md_common().
int jt_obd_test_setattr (int argc, char ** argv)
Definition at line 1581 of file obd.c.
References __u64, BAD_VERBOSE, be_verbose(), buf, CMD_HELP, cur_device, difftime, get_verbose(), obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_obdo1, jt_cmdname(), l2_ioctl(), MAX_IOC_BUFLEN, obdo::o_mode, obdo::o_oi, obdo::o_valid, OBD_DEV_ID, OBD_IOC_SETATTR, obd_ioctl_pack(), OBD_MD_FLID, OBD_MD_FLMODE, OBD_MD_FLTYPE, ostid_set_id(), ostid_set_seq_echo(), rawbuf, shmem_bump(), shmem_running(), and thread.
int jt_obd_test_setxattr (int argc, char ** argv)
Definition at line 1446 of file obd.c.
References ECHO_MD_SETATTR, and jt_obd_md_common().
int jt_opt_device (int argc, char ** argv)
Definition at line 654 of file obd.c.
References CMD_HELP, do_device(), do_disconnect(), Parser_execarg(), and ret.
int jt_opt_net (int argc, char ** argv)
Definition at line 828 of file obd.c.
References CMD_HELP, jt_ptl_network(), and Parser_execarg().
int jt_opt_threads (int argc, char ** argv)
Definition at line 820 of file obd.c.
References CMD_HELP, and jt_cmdname().
int jt_pool_cmd (int argc, char ** argv)
Definition at line 4067 of file obd.c.
References check_and_complete_ostname(), check_pool_cmd_result(), cmd, CMD_HELP, extract_fsname_poolname(), get_array_idx(), LCFG_POOL_ADD, LCFG_POOL_DEL, LCFG_POOL_NEW, LCFG_POOL_REM, llapi_poollist(), LOV_MAXPOOLNAME, MAX_OBD_NAME, pool_cmd(), and poolname.
int jt_replace_nids (int argc, char ** argv)
Replace nids for given device.
lctl replace_nids <devicename> <nid1>[,nid2,nid3] Command should be started on MGS server. Only MGS server should be started (command execution returns error in another cases). Command mount -t lustre <MDT partition>=""> -o nosvc <mount point>=""> can be used for that.
llogs for MDTs and clients are processed. All records copied as is except add_uuid and setup. This records are skipped and recorded with new nids and uuid.
See also:
mgs_replace_nids
mgs_replace_nids_log
mgs_replace_handler
Definition at line 2295 of file obd.c.
References buf, CMD_HELP, get_mgs_device(), obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf2, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, jt_cmdname(), l2_ioctl(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_REPLACE_NIDS, obd_ioctl_pack(), and rawbuf.
static int l2_ioctl (int dev_id, int opc, void * buf) [static]
Definition at line 120 of file obd.c.
References l_ioctl().
Referenced by do_activate(), do_name2dev(), jt_changelog_deregister(), jt_changelog_register(), jt_get_obj_version(), jt_obd_abort_recovery(), jt_obd_alloc_fids(), jt_obd_create(), jt_obd_destroy(), jt_obd_getattr(), jt_obd_list_ioctl(), jt_obd_md_common(), jt_obd_no_transno(), jt_obd_recover(), jt_obd_set_readonly(), jt_obd_setattr(), jt_obd_test_brw(), jt_obd_test_getattr(), jt_obd_test_setattr(), and jt_replace_nids().
int lcfg_ioctl (char * func, int dev_id, struct lustre_cfg * lcfg)
Definition at line 125 of file obd.c.
References buf, cur_device, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_pbuf1, obd_ioctl_data::ioc_plen1, obd_ioctl_data::ioc_type, jt_cmdname(), l_ioctl(), lustre_cfg::lcfg_bufcount, lustre_cfg::lcfg_buflens, lustre_cfg_len(), LUSTRE_CFG_TYPE, MAX_IOC_BUFLEN, OBD_IOC_PROCESS_CFG, obd_ioctl_pack(), and rawbuf.
Referenced by do_add_uuid(), jt_lcfg_add_conn(), jt_lcfg_attach(), jt_lcfg_del_conn(), jt_lcfg_del_mount_option(), jt_lcfg_del_uuid(), jt_lcfg_param(), jt_lcfg_set_timeout(), jt_lcfg_setup(), jt_obd_cleanup(), and jt_obd_detach().
int lcfg_mgs_ioctl (char * func, int dev_id, struct lustre_cfg * lcfg)
Definition at line 173 of file obd.c.
References buf, get_mgs_device(), obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_pbuf1, obd_ioctl_data::ioc_plen1, obd_ioctl_data::ioc_type, jt_cmdname(), l_ioctl(), lustre_cfg::lcfg_bufcount, lustre_cfg::lcfg_buflens, lustre_cfg_len(), LUSTRE_CFG_TYPE, MAX_IOC_BUFLEN, OBD_IOC_PARAM, obd_ioctl_pack(), and rawbuf.
Referenced by jt_lcfg_mgsparam(), and jt_lcfg_mgsparam2().
static int llog_cancel_parse_optional (int argc, char ** argv, struct obd_ioctl_data * data) [static]
Definition at line 2537 of file obd.c.
References obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf2, obd_ioctl_data::ioc_inlbuf3, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, obd_ioctl_data::ioc_inllen3, and optarg.
Referenced by jt_llog_cancel().
static int nodemap_cmd (enum lcfg_command_type cmd, void * ret_data, unsigned int ret_size, ...) [static]
Format and send the ioctl to the MGS.
Parameters:
cmd IOCTL to send
ret_data void pointer to return anything from ioctl
num_args number of arguments to pack into the ioctl buffer
argv[] variable number of string arguments
Return values:
0 on success
Definition at line 3245 of file obd.c.
References buf, get_mgs_device(), obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_pbuf1, obd_ioctl_data::ioc_plen1, obd_ioctl_data::ioc_type, l_ioctl(), lustre_cfg::lcfg_bufcount, lustre_cfg::lcfg_buflens, lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_len(), lustre_cfg_new(), LUSTRE_CFG_TYPE, MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_NODEMAP, obd_ioctl_pack(), obd_ioctl_unpack(), and rawbuf.
Referenced by jt_nodemap_activate(), jt_nodemap_add(), jt_nodemap_add_idmap(), jt_nodemap_add_range(), jt_nodemap_del(), jt_nodemap_del_idmap(), jt_nodemap_del_range(), jt_nodemap_modify(), jt_nodemap_test_id(), and jt_nodemap_test_nid().
void obd_finalize (int argc, char ** argv)
Definition at line 2956 of file obd.c.
References do_disconnect(), shmem_cleanup(), and signal_server().
Referenced by lctl_main().
int obd_initialize (int argc, char ** argv)
Definition at line 2945 of file obd.c.
References OBD_DEV_ID, OBD_DEV_MAJOR, OBD_DEV_MINOR, OBD_DEV_PATH, register_ioc_dev(), and shmem_setup().
Referenced by lctl_main(), and main().
char* obdo_print (struct obdo * obd)
Definition at line 204 of file obd.c.
References buf, obdo::o_atime, obdo::o_blksize, obdo::o_blocks, obdo::o_ctime, obdo::o_flags, obdo::o_gid, obdo::o_misc, obdo::o_mode, obdo::o_mtime, obdo::o_nlink, obdo::o_oi, obdo::o_size, obdo::o_uid, obdo::o_valid, ostid_id(), and ostid_seq().
int parse_devname (char * func, char * name)
Definition at line 262 of file obd.c.
References do_name2dev(), N2D_OFF, and ret.
Referenced by do_device().
static int pool_cmd (enum lcfg_command_type cmd, char * cmdname, char * fullpoolname, char * fsname, char * poolname, char * ostname) [static]
Definition at line 3180 of file obd.c.
References buf, check_pool_cmd(), get_mgs_device(), obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_pbuf1, obd_ioctl_data::ioc_plen1, obd_ioctl_data::ioc_type, jt_cmdname(), l_ioctl(), lustre_cfg::lcfg_bufcount, lustre_cfg::lcfg_buflens, lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_len(), lustre_cfg_new(), LUSTRE_CFG_TYPE, MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_POOL, obd_ioctl_pack(), and rawbuf.
Referenced by jt_pool_cmd().
static void print_obd_line (char * s) [static]
Definition at line 947 of file obd.c.
References buf, cfs_free_param_data(), cfs_get_param_paths(), MAX_OBD_NAME, MAX_STRING_SIZE, and path.
Referenced by jt_obd_list().
static void shmem_bump (__u32 counters) [inline, static]
Definition at line 596 of file obd.c.
Referenced by jt_obd_create(), jt_obd_destroy(), jt_obd_md_common(), jt_obd_test_brw(), jt_obd_test_getattr(), and jt_obd_test_setattr().
static void shmem_cleanup (void) [static]
Definition at line 608 of file obd.c.
Referenced by obd_finalize().
static void shmem_lock () [static]
Definition at line 600 of file obd.c.
Referenced by jt_obd_md_common(), and jt_obd_test_brw().
static void shmem_reset (int total_threads) [inline, static]
Definition at line 592 of file obd.c.
static int shmem_running (void) [static]
Definition at line 612 of file obd.c.
Referenced by jt_obd_create(), jt_obd_destroy(), jt_obd_md_common(), jt_obd_test_brw(), jt_obd_test_getattr(), and jt_obd_test_setattr().
static int shmem_setup (void) [static]
Definition at line 587 of file obd.c.
Referenced by obd_initialize().
static void shmem_unlock () [static]
Definition at line 604 of file obd.c.
Referenced by jt_obd_md_common(), and jt_obd_test_brw().
static void signal_server (int sig) [static]
Definition at line 2936 of file obd.c.
References do_disconnect(), and jt_cmdname().
Referenced by obd_finalize().
Variable Documentation
command_t cmdlist[]
Definition at line 62 of file lctl.c.
Referenced by lloop_init().
int cur_device = -1 [static]
Definition at line 118 of file obd.c.
Referenced by do_activate(), do_device(), do_disconnect(), do_name2dev(), get_mgs_device(), jt_changelog_deregister(), jt_changelog_register(), jt_get_obj_version(), jt_llog_cancel(), jt_llog_catlist(), jt_llog_check(), jt_llog_info(), jt_llog_print(), jt_llog_remove(), jt_obd_abort_recovery(), jt_obd_alloc_fids(), jt_obd_create(), jt_obd_destroy(), jt_obd_device(), jt_obd_get_device(), jt_obd_getattr(), jt_obd_lov_getconfig(), jt_obd_md_common(), jt_obd_mdc_lookup(), jt_obd_no_transno(), jt_obd_recover(), jt_obd_set_readonly(), jt_obd_setattr(), jt_obd_test_brw(), jt_obd_test_getattr(), jt_obd_test_setattr(), and lcfg_ioctl().
const int nthreads = 1
Definition at line 115 of file obd.c.
const int thread = 0
Definition at line 114 of file obd.c.
Referenced by __lod_del_device(), __mdd_orphan_cleanup(), ct_process_item_async(), distribute_txn_commit_thread(), do_osd_scrub_start(), do_osd_scrub_stop(), jt_cmdname(), jt_obd_md_common(), jt_obd_test_brw(), jt_obd_test_getattr(), jt_obd_test_setattr(), lfsck_control_speed(), lfsck_control_speed_by_self(), lfsck_instance_cleanup(), lfsck_layout_lastid_load(), lfsck_layout_slave_double_scan(), lfsck_layout_slave_exec_oit(), lfsck_master_dir_engine(), lfsck_master_engine(), lfsck_master_oit_engine(), lfsck_namespace_double_scan_one_trace_file(), lfsck_namespace_rescan_striped_dir(), lfsck_namespace_scan_local_lpf(), lfsck_namespace_scan_shard(), lfsck_start(), lfsck_stop(), ll_agl_thread(), ll_start_agl(), lod_add_device(), lod_sub_init_llog(), lod_sub_recovery_thread(), lod_sub_stop_recovery_threads(), lwp_device_fini(), lwp_notify_main(), lwp_notify_users(), ofd_inconsistency_verification_main(), ofd_start_inconsistency_verification_thread(), ofd_stop_inconsistency_verification_thread(), osd_inode_iteration(), osd_oii_insert(), osd_otable_it_next(), osd_preload_next(), osd_scrub_exec(), osd_scrub_join(), osd_scrub_main(), osd_scrub_next(), osd_scrub_prep(), osp_precreate_fini(), osp_precreate_thread(), osp_send_update_thread(), osp_sync_fini(), osp_sync_thread(), ptlrpc_main(), ptlrpc_pinger_main(), ptlrpc_start_thread(), ptlrpc_svcpt_stop_threads(), qmt_reba_thread(), qmt_start_reba_thread(), qmt_stop_reba_thread(), qsd_reint_main(), qsd_start_reint_thread(), qsd_start_upd_thread(), qsd_stop_reint_thread(), qsd_stop_upd_thread(), qsd_upd_thread(), sec_gc_main(), and start_statahead_thread().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.