Lustre: lustre/obdclass/obd_mount.c File Reference
lustre/obdclass/obd_mount.c File Reference
#include <obd.h>
#include <obd_class.h>
#include <lustre/lustre_user.h>
#include <linux/version.h>
#include <lustre_log.h>
#include <lustre_disk.h>
#include <lustre_param.h>
Data Structures
struct lustre_mount_data2
Defines
#define DEBUG_SUBSYSTEM S_CLASS
#define D_MOUNT (D_SUPER|D_CONFIG/*|D_WARNING */)
#define PRINT_CMD CDEBUG
Functions
int lustre_process_log (struct super_block *sb, char *logname, struct config_llog_instance *cfg)
Get a config log from the MGS and process it.
int lustre_end_log (struct super_block *sb, char *logname, struct config_llog_instance *cfg)
int do_lcfg (char *cfgname, lnet_nid_t nid, int cmd, char *s1, char *s2, char *s3, char *s4)
lustre_cfg_bufs are a holdover from 1.4; we can still set these up from lctl (and do for echo cli/srv.
int lustre_start_simple (char *obdname, char *type, char *uuid, char *s1, char *s2, char *s3, char *s4)
Call class_attach and class_setup.
static DEFINE_MUTEX (mgc_start_lock)
int lustre_start_mgc (struct super_block *sb)
Set up a mgc obd to process startup logs.
static int lustre_stop_mgc (struct super_block *sb)
static struct lustre_sb_info * lustre_init_lsi (struct super_block *sb)
static int lustre_free_lsi (struct super_block *sb)
int lustre_put_lsi (struct super_block *sb)
int server_name2fsname (const char *svname, char *fsname, const char **endptr)
Get the fsname ("lustre") from the server name ("lustre-OST003F").
int server_name2svname (const char *label, char *svname, const char **endptr, size_t svsize)
Get service name (svname) from string rc < 0 on error if endptr isn't NULL it is set to end of fsname *.
int server_name_is_ost (const char *svname)
check server name is OST.
int target_name2index (const char *tgtname, __u32 *idx, const char **endptr)
Get the index from the target name MDTXXXX/OSTXXXX rc = server type, or rc < 0 on error.
int server_name2index (const char *svname, __u32 *idx, const char **endptr)
int lustre_common_put_super (struct super_block *sb)
static void lmd_print (struct lustre_mount_data *lmd)
int lustre_check_exclusion (struct super_block *sb, char *svname)
static int lmd_make_exclusion (struct lustre_mount_data *lmd, const char *ptr)
static int lmd_parse_mgssec (struct lustre_mount_data *lmd, char *ptr)
static int lmd_parse_string (char **handle, char *ptr)
static int lmd_parse_mgs (struct lustre_mount_data *lmd, char **ptr)
static int lmd_find_comma (char *buf, char **endh)
Find the first comma delimiter from the specified buf and make *endh point to the string starting with the comma.
static int lmd_parse_nidlist (char *buf, char **endh)
Find the first valid string delimited by comma from the specified buf # and parse it to see whether it's a valid nid list.
static int lmd_parse (char *options, struct lustre_mount_data *lmd)
Parse mount line options e.g.
static int lustre_fill_super (struct super_block *sb, void *data, int silent)
This is the entry point for the mount call into Lustre.
void lustre_register_client_fill_super (int(*cfs)(struct super_block *sb, struct vfsmount *mnt))
void lustre_register_kill_super_cb (void(*cfs)(struct super_block *sb))
static int lustre_get_sb (struct file_system_type *fs_type, int flags, const char *devname, void *data, struct vfsmount *mnt)
static void lustre_kill_super (struct super_block *sb)
MODULE_ALIAS_FS ("lustre")
int lustre_register_fs (void)
int lustre_unregister_fs (void)
Variables
static int(* client_fill_super)(struct super_block *sb, struct vfsmount *mnt)
static void(* kill_super_cb)(struct super_block *sb)
static struct file_system_type lustre_fs_type
Register the "lustre" fs type.
Define Documentation
#define D_MOUNT (D_SUPER|D_CONFIG/*|D_WARNING */)
Definition at line 45 of file obd_mount.c.
Referenced by lmd_make_exclusion(), lmd_print(), lustre_check_exclusion(), lustre_common_put_super(), lustre_fill_super(), lustre_free_lsi(), lustre_put_lsi(), lustre_start_mgc(), lustre_start_simple(), lustre_stop_mgc(), osd_start(), server_deregister_mount(), server_fill_super(), server_fill_super_common(), server_get_mount(), server_mgc_clear_fs(), server_mgc_set_fs(), server_put_mount(), server_put_super(), server_register_mount(), server_register_target(), server_start_targets(), server_stop_mgs(), and server_umount_begin().
#define DEBUG_SUBSYSTEM S_CLASS
Definition at line 44 of file obd_mount.c.
#define PRINT_CMD CDEBUG
Definition at line 46 of file obd_mount.c.
Referenced by lmd_print(), and server_mti_print().
Function Documentation
static DEFINE_MUTEX (mgc_start_lock) [static]
static int lmd_find_comma (char * buf, char ** endh) [static]
Find the first comma delimiter from the specified buf and make *endh point to the string starting with the comma.
The commas in expression list [...] will be skipped.
Parameters:
[in] buf a comma-separated string
[in] endh a pointer to a pointer that will point to the string starting with the comma
Return values:
0 if comma delimiter is found
1 if comma delimiter is not found
Definition at line 1057 of file obd_mount.c.
Referenced by lmd_parse(), and lmd_parse_nidlist().
static int lmd_make_exclusion (struct lustre_mount_data * lmd, const char * ptr) [static]
Definition at line 896 of file obd_mount.c.
References CDEBUG, CERROR, D_MOUNT, ENTRY, LDD_F_SV_TYPE_OST, lustre_mount_data::lmd_exclude, lustre_mount_data::lmd_exclude_count, OBD_ALLOC, OBD_FREE, RETURN, and server_name2index().
Referenced by lmd_parse().
static int lmd_parse (char * options, struct lustre_mount_data * lmd) [static]
Parse mount line options e.g.
mount -v -t lustre -o abort_recov uml1:uml2:/lustre-client /mnt/lustre dev is passed as device=uml1:/lustre by mount.lustre
Definition at line 1132 of file obd_mount.c.
References CERROR, devname, ENTRY, LASSERT, LCONSOLE_ERROR_MSG, lustre_mount_data::lmd_dev, lustre_mount_data::lmd_fileset, lmd_find_comma(), lustre_mount_data::lmd_flags, LMD_FLG_ABORT_RECOV, LMD_FLG_CLIENT, LMD_FLG_MGS, LMD_FLG_NO_PRIMNODE, LMD_FLG_NOIR, LMD_FLG_NOMGS, LMD_FLG_NOSCRUB, LMD_FLG_NOSVC, LMD_FLG_SKIP_LFSCK, LMD_FLG_UPDATE, LMD_FLG_VIRGIN, LMD_FLG_WRITECONF, LMD_MAGIC, lustre_mount_data::lmd_magic, lmd_make_exclusion(), lustre_mount_data::lmd_opts, lustre_mount_data::lmd_osd_type, lustre_mount_data::lmd_params, LMD_PARAMS_MAXLEN, lmd_parse_mgs(), lmd_parse_mgssec(), lmd_parse_nidlist(), lmd_parse_string(), lmd_print(), lustre_mount_data::lmd_profile, lustre_mount_data::lmd_recovery_time_hard, lustre_mount_data::lmd_recovery_time_soft, OBD_ALLOC, OBD_FREE, OBD_RECOVERY_TIME_MIN, PARAM_MGSNODE, RETURN, and strlcat().
Referenced by lustre_fill_super().
static int lmd_parse_mgs (struct lustre_mount_data * lmd, char ** ptr) [static]
Definition at line 1008 of file obd_mount.c.
References class_parse_nid_quiet(), LCONSOLE_ERROR_MSG, lustre_mount_data::lmd_mgs, OBD_ALLOC, and OBD_FREE.
Referenced by lmd_parse().
static int lmd_parse_mgssec (struct lustre_mount_data * lmd, char * ptr) [static]
Definition at line 953 of file obd_mount.c.
References lustre_mount_data::lmd_mgssec, OBD_ALLOC, and OBD_FREE.
Referenced by lmd_parse().
static int lmd_parse_nidlist (char * buf, char ** endh) [static]
Find the first valid string delimited by comma from the specified buf # and parse it to see whether it's a valid nid list.
If yes, *endh will point to the next string starting with the comma.
Parameters:
[in] buf a comma-separated string
[in] endh a pointer to a pointer that will point to the string starting with the comma
Return values:
0 if the string is a valid nid list
1 if the string is not a valid nid list
Definition at line 1095 of file obd_mount.c.
References cfs_free_nidlist(), cfs_parse_nidlist(), INIT_LIST_HEAD, and lmd_find_comma().
Referenced by lmd_parse().
static int lmd_parse_string (char ** handle, char * ptr) [static]
Definition at line 978 of file obd_mount.c.
References OBD_ALLOC, and OBD_FREE.
Referenced by lmd_parse().
static void lmd_print (struct lustre_mount_data * lmd) [static]
Definition at line 842 of file obd_mount.c.
References D_MOUNT, lustre_mount_data::lmd_dev, lustre_mount_data::lmd_exclude, lustre_mount_data::lmd_exclude_count, lustre_mount_data::lmd_flags, lmd_is_client, lustre_mount_data::lmd_opts, lustre_mount_data::lmd_profile, lustre_mount_data::lmd_recovery_time_hard, lustre_mount_data::lmd_recovery_time_soft, and PRINT_CMD.
Referenced by lmd_parse().
int lustre_check_exclusion (struct super_block * sb, char * svname)
Definition at line 870 of file obd_mount.c.
References CDEBUG, CWARN, D_MOUNT, ENTRY, LDD_F_SV_TYPE_OST, lustre_mount_data::lmd_dev, lustre_mount_data::lmd_exclude, lustre_mount_data::lmd_exclude_count, RETURN, and server_name2index().
Referenced by class_config_llog_handler().
int lustre_common_put_super (struct super_block * sb)
Definition at line 817 of file obd_mount.c.
References CDEBUG, CERROR, D_MOUNT, ENTRY, lustre_put_lsi(), lustre_stop_mgc(), and RETURN.
Referenced by ll_put_super(), and server_put_super().
static int lustre_fill_super (struct super_block * sb, void * data, int silent) [static]
This is the entry point for the mount call into Lustre.
This is called when a server or client is mounted, and this is where we start setting things up.
Parameters:
data Mount options (e.g. -o flock,abort_recov)
Definition at line 1376 of file obd_mount.c.
References CDEBUG, CERROR, client_fill_super, D_MOUNT, D_SUPER, D_VFSTRACE, ENTRY, GOTO, LCONSOLE_ERROR_MSG, lustre_mount_data2::lmd2_data, lustre_mount_data2::lmd2_mnt, lustre_mount_data::lmd_dev, lmd_is_client, lmd_parse(), lustre_mount_data::lmd_profile, lustre_init_lsi(), lustre_put_lsi(), lustre_start_mgc(), obd_zombie_barrier(), RETURN, and server_fill_super().
Referenced by lustre_get_sb().
static int lustre_free_lsi (struct super_block * sb) [static]
Definition at line 594 of file obd_mount.c.
References CDEBUG, D_MOUNT, ENTRY, LASSERT, OBD_FREE, OBD_FREE_PTR, and RETURN.
Referenced by lustre_put_lsi().
static int lustre_get_sb (struct file_system_type * fs_type, int flags, const char * devname, void * data, struct vfsmount * mnt) [static]
Definition at line 1485 of file obd_mount.c.
References lustre_fill_super().
static struct lustre_sb_info* lustre_init_lsi (struct super_block * sb) [static, read]
Definition at line 565 of file obd_mount.c.
References ENTRY, INIT_LIST_HEAD, OBD_ALLOC_PTR, OBD_FREE_PTR, and RETURN.
Referenced by lustre_fill_super().
static void lustre_kill_super (struct super_block * sb) [static]
Definition at line 1494 of file obd_mount.c.
References IS_SERVER, and kill_super_cb.
int lustre_put_lsi (struct super_block * sb)
Definition at line 646 of file obd_mount.c.
References CDEBUG, D_MOUNT, ENTRY, IS_SERVER, LASSERT, lu_device_put(), lustre_free_lsi(), obd_disconnect(), obd_zombie_barrier(), and RETURN.
Referenced by lustre_common_put_super(), lustre_fill_super(), server_fill_super(), and server_put_mount().
void lustre_register_client_fill_super (int(*)(struct super_block *sb, struct vfsmount *mnt) cfs)
Definition at line 1462 of file obd_mount.c.
References client_fill_super.
Referenced by lustre_exit(), and lustre_init().
int lustre_register_fs (void)
Definition at line 1519 of file obd_mount.c.
Referenced by obdclass_init().
void lustre_register_kill_super_cb (void(*)(struct super_block *sb) cfs)
Definition at line 1469 of file obd_mount.c.
References kill_super_cb.
Referenced by lustre_exit(), and lustre_init().
int lustre_start_mgc (struct super_block * sb)
Set up a mgc obd to process startup logs.
Parameters:
sb [in] super block of the mgc obd
Return values:
0 success, otherwise error code
Definition at line 217 of file obd_mount.c.
References CDEBUG, CERROR, client_obd::cl_mgc_mgsexp, client_obd::cl_mgc_refcount, class_find_param(), class_name2obd(), class_parse_nid(), class_parse_nid_quiet(), class_uuid_unparse(), obd_device::cli, D_MOUNT, do_lcfg(), ENTRY, GOTO, IS_MGS, IS_SERVER, KEY_CONN_DATA, KEY_INIT_RECOV_BACKUP, KEY_MGSSEC, LASSERT, LCFG_ADD_CONN, LCFG_ADD_UUID, LCONSOLE_WARN, libcfs_nid2str_r(), ll_generate_random_uuid, LMD_FLG_NOIR, lmd_is_client, LNET_NETTYP(), LNET_NIDNET(), LNET_NIDSTR_SIZE, LNetGetId(), LOLND, LUSTRE_MGC_NAME, LUSTRE_MGC_OBDNAME, LUSTRE_MGS_OBDNAME, lustre_start_simple(), LUSTRE_VERSION_CODE, OBD_ALLOC, OBD_ALLOC_PTR, obd_connect(), OBD_CONNECT_AT, OBD_CONNECT_BULK_MBITS, OBD_CONNECT_FULL20, OBD_CONNECT_IMP_RECOV, OBD_CONNECT_LVB_TYPE, OBD_CONNECT_MNE_SWAB, OBD_CONNECT_VERSION, OBD_FREE, OBD_FREE_PTR, obd_get_info(), obd_device::obd_self_export, obd_set_info_async(), obd_device::obd_stopping, obd_device::obd_uuid, obd_connect_data::ocd_connect_flags, OCD_HAS_FLAG, obd_connect_data::ocd_version, PARAM_MGSNODE, RETURN, obd_device::u, obd_uuid::uuid, and uuid.
Referenced by lustre_fill_super(), and server_fill_super().
int lustre_start_simple (char * obdname, char * type, char * uuid, char * s1, char * s2, char * s3, char * s4)
Call class_attach and class_setup.
These methods in turn call obd type-specific methods.
Definition at line 190 of file obd_mount.c.
References CDEBUG, CERROR, D_MOUNT, do_lcfg(), LCFG_ATTACH, LCFG_DETACH, and LCFG_SETUP.
Referenced by lustre_lwp_setup(), lustre_start_mgc(), osd_start(), server_start_mgs(), and server_start_targets().
static int lustre_stop_mgc (struct super_block * sb) [static]
Definition at line 492 of file obd_mount.c.
References CDEBUG, CERROR, client_obd::cl_mgc_mgsexp, client_obd::cl_mgc_refcount, class_manual_cleanup(), obd_device::cli, D_MOUNT, do_lcfg(), ENTRY, GOTO, LASSERT, LCFG_DEL_UUID, LUSTRE_MGC_OBDNAME, OBD_ALLOC, obd_disconnect(), OBD_FREE, obd_device::obd_name, obd_device::obd_no_recov, RETURN, and obd_device::u.
Referenced by lustre_common_put_super().
int lustre_unregister_fs (void)
Definition at line 1524 of file obd_mount.c.
Referenced by obdclass_exit().
MODULE_ALIAS_FS ("lustre")
int server_name2fsname (const char * svname, char * fsname, const char ** endptr)
Get the fsname ("lustre") from the server name ("lustre-OST003F").
Parameters:
[in] svname server name including type and index
[out] fsname Buffer to copy filesystem name prefix into. Must have at least 'strlen(fsname) + 1' chars.
[out] endptr if endptr isn't NULL it is set to end of fsname rc < 0 on error
Definition at line 685 of file obd_mount.c.
References strnlen.
Referenced by lustre_disconnect_lwp(), lustre_find_lwp_by_index(), lustre_start_lwp(), mgs_parse_devname(), qsd_init(), server_lsi2mti(), server_name2index(), server_name2svname(), server_name_is_ost(), and tgt_name2lwp_name().
int server_name2index (const char * svname, __u32 * idx, const char ** endptr)
Definition at line 790 of file obd_mount.c.
References LUSTRE_MDC_NAME, server_name2fsname(), and target_name2index().
Referenced by class_config_llog_handler(), lmd_make_exclusion(), lsi_prepare(), lustre_check_exclusion(), mgs_fsdb_handler(), mgs_parse_devname(), mgs_setparam(), mgs_write_log_param(), osd_device_init0(), qsd_init(), server_lsi2mti(), tgt_is_mdt(), and tgt_server_data_init().
int server_name2svname (const char * label, char * svname, const char ** endptr, size_t svsize)
Get service name (svname) from string rc < 0 on error if endptr isn't NULL it is set to end of fsname *.
Definition at line 712 of file obd_mount.c.
References server_name2fsname(), and strlcpy().
Referenced by mgc_apply_recover_logs().
int server_name_is_ost (const char * svname)
check server name is OST.
Definition at line 736 of file obd_mount.c.
References server_name2fsname().
Referenced by osd_mount().
int target_name2index (const char * tgtname, __u32 * idx, const char ** endptr)
Get the index from the target name MDTXXXX/OSTXXXX rc = server type, or rc < 0 on error.
Definition at line 758 of file obd_mount.c.
References LDD_F_SV_ALL, LDD_F_SV_TYPE_MDT, and LDD_F_SV_TYPE_OST.
Referenced by fld_name_to_index(), and server_name2index().
Variable Documentation
int(* client_fill_super)(struct super_block *sb, struct vfsmount *mnt) [static]
Referenced by lustre_fill_super(), and lustre_register_client_fill_super().
void(* kill_super_cb)(struct super_block *sb) [static]
Referenced by lustre_kill_super(), and lustre_register_kill_super_cb().
struct file_system_type lustre_fs_type [static]
Initial value:
 {
        .owner        = THIS_MODULE,
        .name         = "lustre",
        .get_sb       = lustre_get_sb,
        .kill_sb      = lustre_kill_super,
        .fs_flags     = FS_REQUIRES_DEV | FS_HAS_FIEMAP | FS_RENAME_DOES_D_MOVE,
}
Register the "lustre" fs type.
Definition at line 1506 of file obd_mount.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.