Lustre: lustre/utils/obdctl.h File Reference
lustre/utils/obdctl.h File Reference
Defines
#define MAX_IOC_BUFLEN 8192
Functions
int ptl_initialize (int argc, char **argv)
int jt_ptl_network (int argc, char **argv)
int jt_ptl_list_nids (int argc, char **argv)
int jt_ptl_which_nid (int argc, char **argv)
int jt_ptl_print_interfaces (int argc, char **argv)
int jt_ptl_add_interface (int argc, char **argv)
int jt_ptl_del_interface (int argc, char **argv)
int jt_ptl_print_peers (int argc, char **argv)
int jt_ptl_add_peer (int argc, char **argv)
int jt_ptl_del_peer (int argc, char **argv)
int jt_ptl_print_connections (int argc, char **argv)
int jt_ptl_disconnect (int argc, char **argv)
int jt_ptl_push_connection (int argc, char **argv)
int jt_ptl_ping (int argc, char **argv)
int jt_ptl_mynid (int argc, char **argv)
int jt_ptl_add_uuid (int argc, char **argv)
int jt_ptl_add_uuid_old (int argc, char **argv)
int jt_ptl_close_uuid (int argc, char **argv)
int jt_ptl_del_uuid (int argc, char **argv)
int jt_ptl_add_route (int argc, char **argv)
int jt_ptl_del_route (int argc, char **argv)
int jt_ptl_notify_router (int argc, char **argv)
int jt_ptl_print_routes (int argc, char **argv)
int jt_ptl_fail_nid (int argc, char **argv)
int jt_ptl_testprotocompat (int argc, char **argv)
int jt_ptl_drop_add (int argc, char **argv)
int jt_ptl_drop_del (int argc, char **argv)
int jt_ptl_drop_reset (int argc, char **argv)
int jt_ptl_drop_list (int argc, char **argv)
int jt_ptl_delay_add (int argc, char **argv)
int jt_ptl_delay_del (int argc, char **argv)
int jt_ptl_delay_reset (int argc, char **argv)
int jt_ptl_delay_list (int argc, char **argv)
int dbg_initialize (int argc, char **argv)
int jt_dbg_filter (int argc, char **argv)
int jt_dbg_show (int argc, char **argv)
int jt_dbg_list (int argc, char **argv)
int jt_dbg_debug_kernel (int argc, char **argv)
int jt_dbg_debug_daemon (int argc, char **argv)
int jt_dbg_debug_file (int argc, char **argv)
int jt_dbg_clear_debug_buf (int argc, char **argv)
int jt_dbg_mark_debug_buf (int argc, char **argv)
int jt_dbg_modules (int argc, char **argv)
int do_disconnect (char *func, int verbose)
int obd_initialize (int argc, char **argv)
void obd_finalize (int argc, char **argv)
int jt_opt_device (int argc, char **argv)
int jt_opt_threads (int argc, char **argv)
int jt_opt_net (int argc, char **argv)
int jt_obd_get_device ()
int jt_obd_device (int argc, char **argv)
int jt_obd_detach (int argc, char **argv)
int jt_obd_cleanup (int argc, char **argv)
int jt_obd_no_transno (int argc, char **argv)
int jt_obd_set_readonly (int argc, char **argv)
int jt_obd_abort_recovery (int argc, char **argv)
int jt_obd_list (int argc, char **argv)
int jt_obd_create (int argc, char **argv)
int jt_obd_test_create (int argc, char **argv)
int jt_obd_test_mkdir (int argc, char **argv)
int jt_obd_test_destroy (int argc, char **argv)
int jt_obd_test_rmdir (int argc, char **argv)
int jt_obd_test_lookup (int argc, char **argv)
int jt_obd_test_setxattr (int argc, char **argv)
int jt_obd_test_md_getattr (int argc, char **argv)
int jt_obd_setattr (int argc, char **argv)
int jt_obd_test_setattr (int argc, char **argv)
int jt_obd_destroy (int argc, char **argv)
int jt_obd_getattr (int argc, char **argv)
int jt_obd_test_getattr (int argc, char **argv)
int jt_obd_test_brw (int argc, char **argv)
int jt_obd_lov_getconfig (int argc, char **argv)
int jt_obd_test_ldlm (int argc, char **argv)
int jt_obd_ldlm_regress_start (int argc, char **argv)
int jt_obd_ldlm_regress_stop (int argc, char **argv)
int jt_replace_nids (int arc, char **argv)
Replace nids for given device.
int jt_obd_activate (int argc, char **argv)
int jt_obd_deactivate (int argc, char **argv)
int jt_obd_recover (int argc, char **argv)
int jt_obd_mdc_lookup (int argc, char **argv)
int jt_get_version (int argc, char **argv)
int jt_get_obj_version (int argc, char **argv)
int jt_llog_catlist (int argc, char **argv)
int jt_llog_info (int argc, char **argv)
int jt_llog_print (int argc, char **argv)
int jt_llog_cancel (int argc, char **argv)
int jt_llog_remove (int argc, char **argv)
int jt_llog_check (int argc, char **argv)
int lcfg_ioctl (char *func, int dev_id, struct lustre_cfg *lcfg)
int lcfg_mgs_ioctl (char *func, int dev_id, struct lustre_cfg *lcfg)
int parse_devname (char *func, char *name)
char * jt_cmdname (char *func)
int lcfg_set_devname (char *name)
char * lcfg_get_devname (void)
int jt_lcfg_device (int argc, char **argv)
int jt_lcfg_newdev (int argc, char **argv)
int jt_lcfg_attach (int argc, char **argv)
int jt_lcfg_setup (int argc, char **argv)
int jt_lcfg_add_uuid (int argc, char **argv)
int jt_lcfg_del_uuid (int argc, char **argv)
int jt_lcfg_del_mount_option (int argc, char **argv)
int jt_lcfg_set_timeout (int argc, char **argv)
int jt_lcfg_add_conn (int argc, char **argv)
int jt_lcfg_del_conn (int argc, char **argv)
int jt_lcfg_param (int argc, char **argv)
int jt_lcfg_mgsparam (int argc, char **argv)
int jt_lcfg_getparam (int argc, char **argv)
int jt_lcfg_setparam (int argc, char **argv)
int jt_lcfg_listparam (int argc, char **argv)
int jt_blockdev_attach (int argc, char **argv)
int jt_blockdev_detach (int argc, char **argv)
int jt_blockdev_info (int argc, char **argv)
int jt_pool_cmd (int argc, char **argv)
int jt_nodemap_activate (int argc, char **argv)
activate nodemap functions
int jt_nodemap_add (int argc, char **argv)
add a nodemap
int jt_nodemap_del (int argc, char **argv)
delete a nodemap
int jt_nodemap_modify (int argc, char **argv)
modify a nodemap's behavior
int jt_nodemap_add_range (int argc, char **argv)
add an nid range to a nodemap
int jt_nodemap_test_nid (int argc, char **argv)
test a nid for nodemap membership
int jt_nodemap_del_range (int argc, char **argv)
delete an nid range to a nodemap
int jt_nodemap_add_idmap (int argc, char **argv)
int jt_nodemap_del_idmap (int argc, char **argv)
int jt_nodemap_test_id (int argc, char **argv)
test a nodemap id pair for mapping
int jt_nodemap_info (int argc, char **argv)
Output information about nodemaps.
int jt_changelog_register (int argc, char **argv)
int jt_changelog_deregister (int argc, char **argv)
int jt_lfsck_start (int argc, char **argv)
int jt_lfsck_stop (int argc, char **argv)
int jt_lfsck_query (int argc, char **argv)
Define Documentation
#define MAX_IOC_BUFLEN 8192
Definition at line 40 of file obdctl.h.
Referenced by do_activate(), do_name2dev(), jt_changelog_deregister(), jt_changelog_register(), jt_get_obj_version(), jt_get_version(), jt_lfsck_query(), jt_lfsck_start(), jt_lfsck_stop(), jt_llog_cancel(), jt_llog_catlist(), jt_llog_check(), jt_llog_info(), jt_llog_print(), jt_llog_remove(), jt_nodemap_test_id(), jt_nodemap_test_nid(), jt_obd_abort_recovery(), jt_obd_alloc_fids(), jt_obd_create(), jt_obd_destroy(), jt_obd_getattr(), jt_obd_list_ioctl(), jt_obd_lov_getconfig(), jt_obd_md_common(), jt_obd_mdc_lookup(), jt_obd_no_transno(), jt_obd_recover(), jt_obd_set_readonly(), jt_obd_setattr(), jt_obd_test_brw(), jt_obd_test_getattr(), jt_obd_test_setattr(), jt_replace_nids(), lcfg_ioctl(), lcfg_mgs_ioctl(), nodemap_cmd(), and pool_cmd().
Function Documentation
int dbg_initialize (int argc, char ** argv)
Definition at line 159 of file debug.c.
Referenced by lctl_main().
int do_disconnect (char * func, int verbose)
Definition at line 363 of file obd.c.
References cur_device, and lcfg_set_devname().
Referenced by get_mgs_device(), jt_opt_device(), obd_finalize(), and signal_server().
int jt_blockdev_attach (int argc, char ** argv)
Definition at line 2818 of file obd.c.
References CMD_HELP, devname, filename, jt_blockdev_probe_module(), LL_IOC_LLOOP_ATTACH, and LL_IOC_LLOOP_DETACH_BYDEV.
int jt_blockdev_detach (int argc, char ** argv)
Definition at line 2875 of file obd.c.
References CMD_HELP, filename, and LL_IOC_LLOOP_DETACH.
int jt_blockdev_info (int argc, char ** argv)
Definition at line 2903 of file obd.c.
References CMD_HELP, DFID, fid_is_zero(), filename, LL_IOC_LLOOP_INFO, and PFID.
int jt_changelog_deregister (int argc, char ** argv)
Definition at line 4329 of file obd.c.
References buf, CHANGELOG_USER_PREFIX, CMD_HELP, cur_device, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_u32_1, jt_cmdname(), l2_ioctl(), lcfg_get_devname(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_CHANGELOG_DEREG, obd_ioctl_pack(), obd_ioctl_unpack(), and rawbuf.
int jt_changelog_register (int argc, char ** argv)
Definition at line 4269 of file obd.c.
References buf, CHANGELOG_USER_PREFIX, CMD_HELP, cur_device, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_u32_1, jt_cmdname(), l2_ioctl(), lcfg_get_devname(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_CHANGELOG_REG, obd_ioctl_pack(), obd_ioctl_unpack(), and rawbuf.
char* jt_cmdname (char * func)
Definition at line 286 of file obd.c.
References buf, and thread.
Referenced by do_activate(), do_name2dev(), get_verbose(), jt_changelog_deregister(), jt_changelog_register(), jt_get_obj_version(), jt_get_version(), jt_lcfg_add_conn(), jt_lcfg_attach(), jt_lcfg_del_conn(), jt_lcfg_del_mount_option(), jt_lcfg_getparam(), jt_lcfg_listparam(), jt_lcfg_mgsparam(), jt_lcfg_mgsparam2(), jt_lcfg_param(), jt_lcfg_set_timeout(), jt_lcfg_setparam(), jt_lcfg_setup(), jt_llog_cancel(), jt_llog_catlist(), jt_llog_check(), jt_llog_info(), jt_llog_print(), jt_llog_remove(), jt_nodemap_add_range(), jt_nodemap_del_range(), jt_nodemap_modify(), jt_obd_abort_recovery(), jt_obd_cleanup(), jt_obd_create(), jt_obd_destroy(), jt_obd_detach(), jt_obd_getattr(), jt_obd_list(), jt_obd_lov_getconfig(), jt_obd_md_common(), jt_obd_mdc_lookup(), jt_obd_no_transno(), jt_obd_recover(), jt_obd_set_readonly(), jt_obd_setattr(), jt_obd_test_brw(), jt_obd_test_getattr(), jt_obd_test_setattr(), jt_opt_threads(), jt_replace_nids(), lcfg_ioctl(), lcfg_mgs_ioctl(), pool_cmd(), and signal_server().
int jt_dbg_clear_debug_buf (int argc, char ** argv)
Definition at line 724 of file debug.c.
References buf, IOC_LIBCFS_CLEAR_DEBUG, l_ioctl(), libcfs_ioctl_pack(), LNET_DEV_ID, and max.
int jt_dbg_debug_daemon (int argc, char ** argv)
Definition at line 649 of file debug.c.
References buf, DAEMON_CTL_NAME, dbg_close_ctlhandle(), dbg_open_ctlhandle(), dbg_write_cmd(), debug_daemon_usage, end, and size.
int jt_dbg_debug_file (int argc, char ** argv)
Definition at line 607 of file debug.c.
References parse_buffer().
int jt_dbg_debug_kernel (int argc, char ** argv)
Definition at line 505 of file debug.c.
References dbg_close_ctlhandle(), dbg_open_ctlhandle(), dbg_write_cmd(), DUMP_KERNEL_CTL_NAME, filename, LIBCFS_DEBUG_FILE_PATH_DEFAULT, parse_buffer(), and save_errno.
int jt_dbg_filter (int argc, char ** argv)
Definition at line 164 of file debug.c.
References do_debug_mask().
int jt_dbg_list (int argc, char ** argv)
Definition at line 228 of file debug.c.
References applymask_all(), debug_mask, libcfs_debug_masks, libcfs_debug_subsystems, and subsystem_mask.
int jt_dbg_mark_debug_buf (int argc, char ** argv)
Definition at line 749 of file debug.c.
References buf, libcfs_ioctl_data::ioc_inlbuf1, libcfs_ioctl_data::ioc_inllen1, IOC_LIBCFS_MARK_DEBUG, l_ioctl(), libcfs_ioctl_pack(), LNET_DEV_ID, max, MAX_MARK_SIZE, and now().
int jt_dbg_modules (int argc, char ** argv)
Definition at line 834 of file debug.c.
References buf, mod_paths::name, mod_paths::path, and path.
int jt_dbg_show (int argc, char ** argv)
Definition at line 181 of file debug.c.
References do_debug_mask().
int jt_get_obj_version (int argc, char ** argv)
Definition at line 4202 of file obd.c.
References __u64, buf, CMD_HELP, cur_device, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf2, obd_ioctl_data::ioc_inlbuf3, obd_ioctl_data::ioc_inlbuf4, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, obd_ioctl_data::ioc_inllen3, obd_ioctl_data::ioc_inllen4, jt_cmdname(), l2_ioctl(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_GET_OBJ_VERSION, obd_ioctl_pack(), obd_ioctl_unpack(), optarg, optind, rawbuf, RFID, SFID, and version.
int jt_get_version (int argc, char ** argv)
Definition at line 928 of file obd.c.
References CMD_HELP, jt_cmdname(), llapi_get_version(), MAX_IOC_BUFLEN, rawbuf, and version.
int jt_lcfg_add_conn (int argc, char ** argv)
Definition at line 415 of file lustre_cfg.c.
References CMD_HELP, jt_cmdname(), LCFG_ADD_CONN, lcfg_devname, lcfg_ioctl(), lustre_cfg::lcfg_num, lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), and OBD_DEV_ID.
int jt_lcfg_add_uuid (int argc, char ** argv)
Definition at line 308 of file lustre_cfg.c.
References CMD_HELP, do_add_uuid(), libcfs_str2nid(), and LNET_NID_ANY.
int jt_lcfg_attach (int argc, char ** argv)
Definition at line 121 of file lustre_cfg.c.
References CMD_HELP, jt_cmdname(), LCFG_ATTACH, lcfg_ioctl(), lcfg_set_devname(), lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), and OBD_DEV_ID.
int jt_lcfg_del_conn (int argc, char ** argv)
Definition at line 457 of file lustre_cfg.c.
References CMD_HELP, jt_cmdname(), LCFG_DEL_MOUNTOPT, lcfg_devname, lcfg_ioctl(), lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), and OBD_DEV_ID.
int jt_lcfg_del_mount_option (int argc, char ** argv)
Definition at line 355 of file lustre_cfg.c.
References CMD_HELP, jt_cmdname(), LCFG_DEL_MOUNTOPT, lcfg_devname, lcfg_ioctl(), lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), and OBD_DEV_ID.
int jt_lcfg_del_uuid (int argc, char ** argv)
Definition at line 325 of file lustre_cfg.c.
References LCFG_DEL_UUID, lcfg_devname, lcfg_ioctl(), lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), and OBD_DEV_ID.
int jt_lcfg_device (int argc, char ** argv)
Definition at line 116 of file lustre_cfg.c.
References jt_obd_device().
int jt_lcfg_getparam (int argc, char ** argv)
Definition at line 1291 of file lustre_cfg.c.
References clean_path(), CMD_HELP, GET_PARAM, getparam_cmdline(), jt_cmdname(), LIST_PARAM, param_display(), path, and param_opts::po_only_path.
int jt_lcfg_listparam (int argc, char ** argv)
Definition at line 1225 of file lustre_cfg.c.
References clean_path(), CMD_HELP, jt_cmdname(), LIST_PARAM, listparam_cmdline(), param_display(), and path.
int jt_lcfg_mgsparam (int argc, char ** argv)
Definition at line 612 of file lustre_cfg.c.
References buf, CMD_HELP, jt_cmdname(), lcfg_mgs_ioctl(), LCFG_PARAM, lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), OBD_DEV_ID, and optind.
int jt_lcfg_newdev (int argc, char ** argv)
int jt_lcfg_param (int argc, char ** argv)
Definition at line 494 of file lustre_cfg.c.
References CMD_HELP, jt_cmdname(), lcfg_ioctl(), LCFG_PARAM, lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), LUSTRE_CFG_MAX_BUFCOUNT, lustre_cfg_new(), and OBD_DEV_ID.
int jt_lcfg_set_timeout (int argc, char ** argv)
Definition at line 383 of file lustre_cfg.c.
References CMD_HELP, jt_cmdname(), lcfg_devname, lcfg_ioctl(), lustre_cfg::lcfg_num, LCFG_SET_TIMEOUT, lustre_cfg_bufs_reset(), lustre_cfg_free(), lustre_cfg_new(), and OBD_DEV_ID.
int jt_lcfg_setparam (int argc, char ** argv)
Definition at line 1401 of file lustre_cfg.c.
References clean_path(), CMD_HELP, jt_cmdname(), jt_lcfg_mgsparam2(), param_display(), path, param_opts::po_params2, SET_PARAM, and setparam_cmdline().
int jt_lcfg_setup (int argc, char ** argv)
Definition at line 153 of file lustre_cfg.c.
References CMD_HELP, jt_cmdname(), lcfg_devname, lcfg_ioctl(), LCFG_SETUP, lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), and OBD_DEV_ID.
int jt_lfsck_query (int argc, char ** argv)
Definition at line 441 of file lustre_lfsck.c.
References buf, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf4, obd_ioctl_data::ioc_inllen1, l_ioctl(), lcfg_get_devname(), lfsck_name2type(), lfsck_pack_dev(), lfsck_status2name(), lfsck_type2name(), LFSCK_TYPE_BITS, LFSCK_TYPES_ALL, long_opt_query, LPF_WAIT, LS_MAX, lfsck_type_name::ltn_name, lfsck_query::lu_flags, lfsck_query::lu_mdts_count, lfsck_query::lu_osts_count, lfsck_query::lu_repaired, lfsck_query::lu_types, MAX_IOC_BUFLEN, MAX_OBD_NAME, name, OBD_DEV_ID, OBD_IOC_QUERY_LFSCK, obd_ioctl_pack(), obd_ioctl_unpack(), opt, optarg, rawbuf, and usage_query().
int jt_lfsck_start (int argc, char ** argv)
Definition at line 192 of file lustre_lfsck.c.
References buf, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf4, obd_ioctl_data::ioc_inllen1, l_ioctl(), lcfg_get_devname(), LFSCK_ASYNC_WIN_MAX, lfsck_name2type(), lfsck_pack_dev(), LFSCK_TYPES_ALL, LFSCK_TYPES_DEF, LFSCK_VERSION_V1, long_opt_start, LPF_ALL_TGT, LPF_BROADCAST, LPF_CREATE_MDTOBJ, LPF_CREATE_OSTOBJ, LPF_DRYRUN, LPF_FAILOUT, LPF_OST_ORPHAN, LPF_RESET, lfsck_start::ls_active, lfsck_start::ls_async_windows, lfsck_start::ls_flags, lfsck_start::ls_speed_limit, lfsck_start::ls_valid, lfsck_start::ls_version, LSV_ASYNC_WINDOWS, LSV_CREATE_MDTOBJ, LSV_CREATE_OSTOBJ, LSV_DRYRUN, LSV_ERROR_HANDLE, LSV_SPEED_LIMIT, lfsck_type_name::ltn_name, lfsck_type_name::ltn_type, MAX_IOC_BUFLEN, MAX_OBD_NAME, OBD_DEV_ID, OBD_IOC_START_LFSCK, obd_ioctl_pack(), obd_ioctl_unpack(), opt, optarg, optind, rawbuf, and usage_start().
int jt_lfsck_stop (int argc, char ** argv)
Definition at line 374 of file lustre_lfsck.c.
References buf, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf4, obd_ioctl_data::ioc_inllen1, l_ioctl(), lcfg_get_devname(), lfsck_pack_dev(), long_opt_stop, LPF_ALL_TGT, LPF_BROADCAST, lfsck_stop::ls_flags, MAX_IOC_BUFLEN, MAX_OBD_NAME, OBD_DEV_ID, OBD_IOC_STOP_LFSCK, obd_ioctl_pack(), opt, optarg, optind, rawbuf, and usage_stop().
int jt_llog_cancel (int argc, char ** argv)
Definition at line 2588 of file obd.c.
References buf, CMD_HELP, cur_device, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf2, obd_ioctl_data::ioc_inlbuf3, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, obd_ioctl_data::ioc_inllen3, jt_cmdname(), l_ioctl(), llog_cancel_parse_optional(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_LLOG_CANCEL, obd_ioctl_pack(), and rawbuf.
int jt_llog_catlist (int argc, char ** argv)
Definition at line 2428 of file obd.c.
References buf, cfs_size_round(), CMD_HELP, cur_device, obd_ioctl_data::ioc_bulk, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_inllen1, jt_cmdname(), l_ioctl(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_CATLOGLIST, obd_ioctl_pack(), and rawbuf.
int jt_llog_check (int argc, char ** argv)
Definition at line 2649 of file obd.c.
References buf, cfs_size_round(), CMD_HELP, cur_device, obd_ioctl_data::ioc_bulk, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf2, obd_ioctl_data::ioc_inlbuf3, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, obd_ioctl_data::ioc_inllen3, obd_ioctl_data::ioc_inllen4, jt_cmdname(), l_ioctl(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_LLOG_CHECK, obd_ioctl_pack(), and rawbuf.
int jt_llog_info (int argc, char ** argv)
Definition at line 2457 of file obd.c.
References buf, cfs_size_round(), CMD_HELP, cur_device, obd_ioctl_data::ioc_bulk, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, jt_cmdname(), l_ioctl(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_LLOG_INFO, obd_ioctl_pack(), and rawbuf.
int jt_llog_print (int argc, char ** argv)
Definition at line 2490 of file obd.c.
References buf, cfs_size_round(), CMD_HELP, cur_device, obd_ioctl_data::ioc_bulk, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf2, obd_ioctl_data::ioc_inlbuf3, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, obd_ioctl_data::ioc_inllen3, obd_ioctl_data::ioc_inllen4, jt_cmdname(), l_ioctl(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_LLOG_PRINT, obd_ioctl_pack(), and rawbuf.
int jt_llog_remove (int argc, char ** argv)
Definition at line 2695 of file obd.c.
References buf, CMD_HELP, cur_device, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf2, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, jt_cmdname(), l_ioctl(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_LLOG_REMOVE, obd_ioctl_pack(), and rawbuf.
int jt_nodemap_activate (int argc, char ** argv)
activate nodemap functions
Parameters:
argc number of args
argv[] variable string arguments
argv[0] 1 for activate or 0 for deactivate
Return values:
0 on success
Definition at line 3324 of file obd.c.
References LCFG_NODEMAP_ACTIVATE, and nodemap_cmd().
int jt_nodemap_add (int argc, char ** argv)
add a nodemap
Parameters:
argc number of args
argv[] variable string arguments
argv[0] nodemap name
Return values:
0 on success
Definition at line 3349 of file obd.c.
References LCFG_NODEMAP_ADD, llapi_nodemap_exists(), and nodemap_cmd().
int jt_nodemap_add_idmap (int argc, char ** argv)
Definition at line 3771 of file obd.c.
References cmd, LCFG_NODEMAP_ADD_GIDMAP, LCFG_NODEMAP_ADD_UIDMAP, nodemap_cmd(), and optarg.
int jt_nodemap_add_range (int argc, char ** argv)
add an nid range to a nodemap
Parameters:
argc number of args
argv[] variable string arguments
--name nodemap name --range properly formatted nid range
Return values:
0 on success
Definition at line 3508 of file obd.c.
References cfs_nidrange_find_min_max(), cfs_nidrange_is_contiguous(), cfs_parse_nidlist(), INIT_LIST_HEAD, jt_cmdname(), LCFG_NODEMAP_ADD_RANGE, LNET_NIDSTR_SIZE, nodemap_cmd(), and optarg.
int jt_nodemap_del (int argc, char ** argv)
delete a nodemap
Parameters:
argc number of args
argv[] variable string arguments
argv[0] nodemap name
Return values:
0 on success
Definition at line 3379 of file obd.c.
References LCFG_NODEMAP_DEL, llapi_nodemap_exists(), and nodemap_cmd().
int jt_nodemap_del_idmap (int argc, char ** argv)
Definition at line 3845 of file obd.c.
References cmd, LCFG_NODEMAP_DEL_GIDMAP, LCFG_NODEMAP_DEL_UIDMAP, nodemap_cmd(), and optarg.
int jt_nodemap_del_range (int argc, char ** argv)
delete an nid range to a nodemap
Parameters:
argc number of args
argv[] variable string arguments
--name nodemap name --range properly formatted nid range
Return values:
0 on success
Definition at line 3597 of file obd.c.
References cfs_nidrange_find_min_max(), cfs_nidrange_is_contiguous(), cfs_parse_nidlist(), INIT_LIST_HEAD, jt_cmdname(), LCFG_NODEMAP_DEL_RANGE, LNET_NIDSTR_SIZE, nodemap_cmd(), and optarg.
int jt_nodemap_info (int argc, char ** argv)
Output information about nodemaps.
Parameters:
argc number of args
argv[] variable string arguments
[list|nodemap_name|all] list will list all nodemaps (default). Specifying a nodemap_name will display info about that specific nodemap. all will display info for all nodemaps.
Return values:
0 on success
Definition at line 1339 of file lustre_cfg.c.
References LIST_PARAM, param_display(), param_opts::po_only_dir, param_opts::po_only_path, and param_opts::po_show_path.
int jt_nodemap_modify (int argc, char ** argv)
modify a nodemap's behavior
Parameters:
argc number of args
argv[] variable string arguments
--name nodemap name --property nodemap property to change admin, trusted, squash_uid, squash_gid) --value value to set property
Return values:
0 on success
Definition at line 3688 of file obd.c.
References cmd, jt_cmdname(), LCFG_NODEMAP_ADMIN, LCFG_NODEMAP_SQUASH_GID, LCFG_NODEMAP_SQUASH_UID, LCFG_NODEMAP_TRUSTED, nodemap_cmd(), and optarg.
int jt_nodemap_test_id (int argc, char ** argv)
test a nodemap id pair for mapping
Parameters:
argc number of args
argv[[] variable string arguments
Return values:
0 on success
The argv array should contain the nodemap name, the id to checking the mapping on, and the id type (UID or GID)
Definition at line 3435 of file obd.c.
References LCFG_NODEMAP_TEST_ID, MAX_IOC_BUFLEN, nodemap_cmd(), optarg, and rawbuf.
int jt_nodemap_test_nid (int argc, char ** argv)
test a nid for nodemap membership
Parameters:
argc number of args
argv[] variable string arguments
argv[0] properly formatted nid
Return values:
0 on success
Definition at line 3409 of file obd.c.
References LCFG_NODEMAP_TEST_NID, MAX_IOC_BUFLEN, nodemap_cmd(), and rawbuf.
int jt_obd_abort_recovery (int argc, char ** argv)
Definition at line 901 of file obd.c.
References buf, CMD_HELP, cur_device, obd_ioctl_data::ioc_dev, jt_cmdname(), l2_ioctl(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_ABORT_RECOVERY, obd_ioctl_pack(), and rawbuf.
int jt_obd_activate (int argc, char ** argv)
Definition at line 2333 of file obd.c.
References do_activate().
int jt_obd_cleanup (int argc, char ** argv)
Definition at line 222 of file lustre_cfg.c.
References CMD_HELP, failover, jt_cmdname(), LCFG_CLEANUP, lcfg_devname, lcfg_ioctl(), lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), and OBD_DEV_ID.
int jt_obd_create (int argc, char ** argv)
Definition at line 1456 of file obd.c.
References __u64, BAD_VERBOSE, be_verbose(), buf, CMD_HELP, cur_device, get_verbose(), obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_obdo1, jt_cmdname(), l2_ioctl(), MAX_IOC_BUFLEN, mode, obdo::o_gid, obdo::o_mode, obdo::o_oi, obdo::o_uid, obdo::o_valid, OBD_DEV_ID, OBD_IOC_CREATE, obd_ioctl_pack(), obd_ioctl_unpack(), OBD_MD_FLGID, OBD_MD_FLGROUP, OBD_MD_FLID, OBD_MD_FLMODE, OBD_MD_FLTYPE, OBD_MD_FLUID, ostid_id(), ostid_set_id(), ostid_set_seq_echo(), rawbuf, shmem_bump(), and shmem_running().
int jt_obd_deactivate (int argc, char ** argv)
Definition at line 2328 of file obd.c.
References do_activate().
int jt_obd_destroy (int argc, char ** argv)
Definition at line 1676 of file obd.c.
References __u64, BAD_VERBOSE, be_verbose(), buf, CMD_HELP, cur_device, get_verbose(), obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_obdo1, jt_cmdname(), l2_ioctl(), MAX_IOC_BUFLEN, obdo::o_mode, obdo::o_oi, obdo::o_valid, OBD_DEV_ID, OBD_IOC_DESTROY, obd_ioctl_pack(), obd_ioctl_unpack(), OBD_MD_FLID, OBD_MD_FLMODE, ostid_set_id(), ostid_set_seq_echo(), rawbuf, shmem_bump(), and shmem_running().
int jt_obd_detach (int argc, char ** argv)
Definition at line 190 of file lustre_cfg.c.
References CMD_HELP, jt_cmdname(), LCFG_DETACH, lcfg_devname, lcfg_ioctl(), lustre_cfg_bufs_reset(), lustre_cfg_free(), lustre_cfg_new(), and OBD_DEV_ID.
int jt_obd_device (int argc, char ** argv)
Definition at line 638 of file obd.c.
References CMD_HELP, cur_device, do_device(), and lcfg_get_devname().
Referenced by jt_lcfg_device().
int jt_obd_get_device ()
Definition at line 633 of file obd.c.
References cur_device.
int jt_obd_getattr (int argc, char ** argv)
Definition at line 1749 of file obd.c.
References buf, CMD_HELP, cur_device, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_obdo1, jt_cmdname(), l2_ioctl(), MAX_IOC_BUFLEN, obdo::o_mode, obdo::o_oi, obdo::o_valid, OBD_DEV_ID, OBD_IOC_GETATTR, obd_ioctl_pack(), obd_ioctl_unpack(), ostid_id(), ostid_set_id(), ostid_set_seq_echo(), and rawbuf.
int jt_obd_ldlm_regress_start (int argc, char ** argv)
int jt_obd_ldlm_regress_stop (int argc, char ** argv)
int jt_obd_list (int argc, char ** argv)
Definition at line 1035 of file obd.c.
References buf, cfs_free_param_data(), cfs_get_param_paths(), CMD_HELP, jt_cmdname(), jt_obd_list_ioctl(), MAX_STRING_SIZE, path, and print_obd_line().
int jt_obd_lov_getconfig (int argc, char ** argv)
Definition at line 2145 of file obd.c.
References buf, CMD_HELP, cur_device, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf2, obd_ioctl_data::ioc_inlbuf3, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, obd_ioctl_data::ioc_inllen3, jt_cmdname(), lov_desc::ld_default_stripe_count, lov_desc::ld_default_stripe_offset, lov_desc::ld_default_stripe_size, lov_desc::ld_pattern, lov_desc::ld_tgt_count, lov_desc::ld_uuid, MAX_IOC_BUFLEN, OBD_IOC_LOV_GET_CONFIG, obd_ioctl_pack(), obd_ioctl_unpack(), OBD_MAX_IOCTL_BUFFER, obd_str2uuid(), path, and rawbuf.
int jt_obd_mdc_lookup (int argc, char ** argv)
Definition at line 2370 of file obd.c.
References buf, CMD_HELP, cur_device, get_verbose(), obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inllen1, IOC_MDC_LOOKUP, obd_ioctl_data::ioc_obdo1, jt_cmdname(), MAX_IOC_BUFLEN, obdo::o_gid, obdo::o_mode, obdo::o_uid, obd_ioctl_pack(), obd_ioctl_unpack(), and rawbuf.
int jt_obd_no_transno (int argc, char ** argv)
Definition at line 847 of file obd.c.
References buf, CMD_HELP, cur_device, obd_ioctl_data::ioc_dev, jt_cmdname(), l2_ioctl(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_NO_TRANSNO, obd_ioctl_pack(), and rawbuf.
int jt_obd_recover (int argc, char ** argv)
Definition at line 2338 of file obd.c.
References buf, CMD_HELP, cur_device, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inllen1, jt_cmdname(), l2_ioctl(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_CLIENT_RECOVER, obd_ioctl_pack(), and rawbuf.
int jt_obd_set_readonly (int argc, char ** argv)
Definition at line 874 of file obd.c.
References buf, CMD_HELP, cur_device, obd_ioctl_data::ioc_dev, jt_cmdname(), l2_ioctl(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_SET_READONLY, obd_ioctl_pack(), and rawbuf.
int jt_obd_setattr (int argc, char ** argv)
Definition at line 1539 of file obd.c.
References buf, CMD_HELP, cur_device, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_obdo1, jt_cmdname(), l2_ioctl(), MAX_IOC_BUFLEN, obdo::o_mode, obdo::o_oi, obdo::o_valid, OBD_DEV_ID, OBD_IOC_SETATTR, obd_ioctl_pack(), OBD_MD_FLID, OBD_MD_FLMODE, OBD_MD_FLTYPE, ostid_set_id(), ostid_set_seq_echo(), and rawbuf.
int jt_obd_test_brw (int argc, char ** argv)
Definition at line 1895 of file obd.c.
References __u64, BAD_VERBOSE, be_verbose(), buf, cmd, CMD_HELP, cur_device, difftime, get_verbose(), obd_ioctl_data::ioc_count, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_obdo1, obd_ioctl_data::ioc_offset, obd_ioctl_data::ioc_pbuf1, obd_ioctl_data::ioc_plen1, jt_cmdname(), l2_ioctl(), MAX_IOC_BUFLEN, obdo::o_flags, obdo::o_mode, obdo::o_oi, obdo::o_valid, OBD_DEV_ID, OBD_FL_DEBUG_CHECK, OBD_IOC_BRW_READ, OBD_IOC_BRW_WRITE, obd_ioctl_pack(), OBD_MD_FLBLOCKS, OBD_MD_FLFLAGS, OBD_MD_FLGRANT, OBD_MD_FLGROUP, OBD_MD_FLID, OBD_MD_FLMODE, OBD_MD_FLTYPE, ostid_id(), ostid_set_id(), ostid_set_seq_echo(), rawbuf, shmem_bump(), shmem_lock(), shmem_running(), shmem_unlock(), and thread.
int jt_obd_test_create (int argc, char ** argv)
Definition at line 1421 of file obd.c.
References ECHO_MD_CREATE, and jt_obd_md_common().
int jt_obd_test_destroy (int argc, char ** argv)
Definition at line 1431 of file obd.c.
References ECHO_MD_DESTROY, and jt_obd_md_common().
int jt_obd_test_getattr (int argc, char ** argv)
Definition at line 1794 of file obd.c.
References __u64, BAD_VERBOSE, be_verbose(), buf, CMD_HELP, cur_device, difftime, get_verbose(), obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_obdo1, jt_cmdname(), l2_ioctl(), MAX_IOC_BUFLEN, obdo::o_mode, obdo::o_oi, obdo::o_valid, OBD_DEV_ID, OBD_IOC_GETATTR, obd_ioctl_pack(), ostid_set_id(), ostid_set_seq_echo(), rawbuf, shmem_bump(), shmem_running(), and thread.
int jt_obd_test_ldlm (int argc, char ** argv)
int jt_obd_test_lookup (int argc, char ** argv)
Definition at line 1441 of file obd.c.
References ECHO_MD_LOOKUP, and jt_obd_md_common().
int jt_obd_test_md_getattr (int argc, char ** argv)
Definition at line 1451 of file obd.c.
References ECHO_MD_GETATTR, and jt_obd_md_common().
int jt_obd_test_mkdir (int argc, char ** argv)
Definition at line 1426 of file obd.c.
References ECHO_MD_MKDIR, and jt_obd_md_common().
int jt_obd_test_rmdir (int argc, char ** argv)
Definition at line 1436 of file obd.c.
References ECHO_MD_RMDIR, and jt_obd_md_common().
int jt_obd_test_setattr (int argc, char ** argv)
Definition at line 1581 of file obd.c.
References __u64, BAD_VERBOSE, be_verbose(), buf, CMD_HELP, cur_device, difftime, get_verbose(), obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_obdo1, jt_cmdname(), l2_ioctl(), MAX_IOC_BUFLEN, obdo::o_mode, obdo::o_oi, obdo::o_valid, OBD_DEV_ID, OBD_IOC_SETATTR, obd_ioctl_pack(), OBD_MD_FLID, OBD_MD_FLMODE, OBD_MD_FLTYPE, ostid_set_id(), ostid_set_seq_echo(), rawbuf, shmem_bump(), shmem_running(), and thread.
int jt_obd_test_setxattr (int argc, char ** argv)
Definition at line 1446 of file obd.c.
References ECHO_MD_SETATTR, and jt_obd_md_common().
int jt_opt_device (int argc, char ** argv)
Definition at line 654 of file obd.c.
References CMD_HELP, do_device(), do_disconnect(), Parser_execarg(), and ret.
int jt_opt_net (int argc, char ** argv)
Definition at line 828 of file obd.c.
References CMD_HELP, jt_ptl_network(), and Parser_execarg().
int jt_opt_threads (int argc, char ** argv)
Definition at line 820 of file obd.c.
References CMD_HELP, and jt_cmdname().
int jt_pool_cmd (int argc, char ** argv)
Definition at line 4067 of file obd.c.
References check_and_complete_ostname(), check_pool_cmd_result(), cmd, CMD_HELP, extract_fsname_poolname(), get_array_idx(), LCFG_POOL_ADD, LCFG_POOL_DEL, LCFG_POOL_NEW, LCFG_POOL_REM, llapi_poollist(), LOV_MAXPOOLNAME, MAX_OBD_NAME, pool_cmd(), and poolname.
int jt_ptl_add_interface (int argc, char ** argv)
Definition at line 509 of file portals.c.
References end, g_net, g_net_is_compatible(), IOC_LIBCFS_ADD_INTERFACE, libcfs_ioctl_data::ioc_net, libcfs_ioctl_data::ioc_u32, l_ioctl(), LIBCFS_IOC_INIT, LNET_DEV_ID, lnet_parse_ipaddr(), lnet_parse_ipquad(), and SOCKLND.
int jt_ptl_add_peer (int argc, char ** argv)
Definition at line 665 of file portals.c.
References g_net, g_net_is_compatible(), GNILND, IOC_LIBCFS_ADD_PEER, libcfs_ioctl_data::ioc_net, libcfs_ioctl_data::ioc_nid, libcfs_ioctl_data::ioc_u32, l_ioctl(), LIBCFS_IOC_INIT, libcfs_str2nid(), LNET_DEV_ID, LNET_NID_ANY, lnet_parse_ipaddr(), lnet_parse_port(), and SOCKLND.
int jt_ptl_add_route (int argc, char ** argv)
Definition at line 1060 of file portals.c.
References lnet_ioctl_config_data::cfg_config_u, lnet_ioctl_config_data::cfg_hdr, lnet_ioctl_config_data::cfg_net, lnet_ioctl_config_data::cfg_nid, lnet_ioctl_config_data::cfg_route, end, g_net, g_net_is_set(), IOC_LIBCFS_ADD_ROUTE, l_ioctl(), LIBCFS_IOC_INIT_V2, libcfs_str2nid(), LNET_DEV_ID, LNET_NID_ANY, and LNET_UNDEFINED_HOPS.
int jt_ptl_add_uuid (int argc, char ** argv)
int jt_ptl_add_uuid_old (int argc, char ** argv)
int jt_ptl_close_uuid (int argc, char ** argv)
int jt_ptl_del_interface (int argc, char ** argv)
Definition at line 560 of file portals.c.
References g_net, g_net_is_compatible(), IOC_LIBCFS_DEL_INTERFACE, libcfs_ioctl_data::ioc_net, libcfs_ioctl_data::ioc_u32, l_ioctl(), LIBCFS_IOC_INIT, LNET_DEV_ID, lnet_parse_ipaddr(), and SOCKLND.
int jt_ptl_del_peer (int argc, char ** argv)
Definition at line 715 of file portals.c.
References g_net, g_net_is_compatible(), GNILND, IOC_LIBCFS_DEL_PEER, libcfs_ioctl_data::ioc_net, libcfs_ioctl_data::ioc_nid, libcfs_ioctl_data::ioc_u32, l_ioctl(), LIBCFS_IOC_INIT, libcfs_str2anynid(), LNET_DEV_ID, LNET_NID_ANY, lnet_parse_ipaddr(), LNET_PID_ANY, O2IBLND, and SOCKLND.
int jt_ptl_del_route (int argc, char ** argv)
Definition at line 1120 of file portals.c.
References lnet_ioctl_config_data::cfg_hdr, lnet_ioctl_config_data::cfg_net, lnet_ioctl_config_data::cfg_nid, g_net, g_net_set, IOC_LIBCFS_DEL_ROUTE, l_ioctl(), LIBCFS_IOC_INIT_V2, libcfs_nid2str(), libcfs_str2anynid(), LNET_DEV_ID, LNET_NID_ANY, and LNET_NIDNET().
int jt_ptl_del_uuid (int argc, char ** argv)
int jt_ptl_delay_add (int argc, char ** argv)
Definition at line 1463 of file portals.c.
References fault_simul_rule_add(), and LNET_CTL_DELAY_ADD.
int jt_ptl_delay_del (int argc, char ** argv)
Definition at line 1552 of file portals.c.
References fault_simul_rule_del(), and LNET_CTL_DELAY_DEL.
int jt_ptl_delay_list (int argc, char ** argv)
Definition at line 1664 of file portals.c.
References fault_simul_rule_list(), and LNET_CTL_DELAY_LIST.
int jt_ptl_delay_reset (int argc, char ** argv)
Definition at line 1582 of file portals.c.
References fault_simul_rule_reset(), and LNET_CTL_DELAY_RESET.
int jt_ptl_disconnect (int argc, char ** argv)
Definition at line 834 of file portals.c.
References g_net, g_net_is_compatible(), GNILND, IOC_LIBCFS_CLOSE_CONNECTION, libcfs_ioctl_data::ioc_net, libcfs_ioctl_data::ioc_nid, libcfs_ioctl_data::ioc_u32, l_ioctl(), LIBCFS_IOC_INIT, libcfs_str2anynid(), LNET_DEV_ID, LNET_NID_ANY, lnet_parse_ipaddr(), O2IBLND, and SOCKLND.
int jt_ptl_drop_add (int argc, char ** argv)
Definition at line 1457 of file portals.c.
References fault_simul_rule_add(), and LNET_CTL_DROP_ADD.
int jt_ptl_drop_del (int argc, char ** argv)
Definition at line 1546 of file portals.c.
References fault_simul_rule_del(), and LNET_CTL_DROP_DEL.
int jt_ptl_drop_list (int argc, char ** argv)
Definition at line 1658 of file portals.c.
References fault_simul_rule_list(), and LNET_CTL_DROP_LIST.
int jt_ptl_drop_reset (int argc, char ** argv)
Definition at line 1576 of file portals.c.
References fault_simul_rule_reset(), and LNET_CTL_DROP_RESET.
int jt_ptl_fail_nid (int argc, char ** argv)
Definition at line 1019 of file portals.c.
References libcfs_ioctl_data::ioc_count, IOC_LIBCFS_FAIL_NID, libcfs_ioctl_data::ioc_nid, l_ioctl(), LIBCFS_IOC_INIT, libcfs_str2anynid(), LNET_DEV_ID, and LNET_MD_THRESH_INF.
int jt_ptl_list_nids (int argc, char ** argv)
Definition at line 356 of file portals.c.
References __u64, libcfs_ioctl_data::ioc_count, IOC_LIBCFS_GET_NI, libcfs_ioctl_data::ioc_nid, l_ioctl(), LIBCFS_IOC_INIT, libcfs_nid2str(), LNET_DEV_ID, LNET_NETTYP(), LNET_NIDNET(), and LOLND.
int jt_ptl_mynid (int argc, char ** argv)
Definition at line 987 of file portals.c.
References IOC_LIBCFS_REGISTER_MYNID, libcfs_ioctl_data::ioc_net, libcfs_ioctl_data::ioc_nid, l_ioctl(), LIBCFS_IOC_INIT, libcfs_nid2str(), libcfs_str2nid(), LNET_DEV_ID, LNET_NID_ANY, and LNET_NIDNET().
int jt_ptl_network (int argc, char ** argv)
Definition at line 295 of file portals.c.
References CIBLND, g_net, g_net_set, GMLND, IIBLND, IOC_LIBCFS_CONFIGURE, IOC_LIBCFS_UNCONFIGURE, l_ioctl(), LIBCFS_IOC_INIT, libcfs_lnd2str(), libcfs_str2net(), LNET_DEV_ID, LNET_NETTYP(), LNET_NID_ANY, LNET_NIDNET(), MXLND, OPENIBLND, PTLLND, QSWLND, RALND, and VIBLND.
Referenced by jt_opt_net().
int jt_ptl_notify_router (int argc, char ** argv)
Definition at line 1152 of file portals.c.
References __u64, libcfs_ioctl_data::ioc_flags, IOC_LIBCFS_NOTIFY_ROUTER, libcfs_ioctl_data::ioc_nid, libcfs_ioctl_data::ioc_u64, l_ioctl(), LIBCFS_IOC_INIT, libcfs_nid2str(), libcfs_str2nid(), LNET_DEV_ID, LNET_NID_ANY, lnet_parse_bool(), and lnet_parse_time().
int jt_ptl_ping (int argc, char ** argv)
Definition at line 911 of file portals.c.
References end, libcfs_ioctl_data::ioc_count, IOC_LIBCFS_PING, libcfs_ioctl_data::ioc_nid, libcfs_ioctl_data::ioc_pbuf1, libcfs_ioctl_data::ioc_plen1, libcfs_ioctl_data::ioc_u32, l_ioctl(), libcfs_id2str(), LIBCFS_IOC_INIT, libcfs_nid2str(), libcfs_str2nid(), LNET_DEV_ID, LNET_NID_ANY, lnet_parse_nid(), LNET_PID_ANY, LNET_PID_USERFLAG, and timeout.
int jt_ptl_print_connections (int argc, char ** argv)
Definition at line 769 of file portals.c.
References g_net, g_net_is_compatible(), GNILND, libcfs_ioctl_data::ioc_count, libcfs_ioctl_data::ioc_flags, IOC_LIBCFS_GET_CONN, libcfs_ioctl_data::ioc_net, libcfs_ioctl_data::ioc_nid, libcfs_ioctl_data::ioc_u32, l_ioctl(), libcfs_id2str(), LIBCFS_IOC_INIT, libcfs_nid2str(), LNET_DEV_ID, O2IBLND, ptl_ipaddr_2_str(), SOCKLND, SOCKLND_CONN_ANY, SOCKLND_CONN_BULK_IN, SOCKLND_CONN_BULK_OUT, and SOCKLND_CONN_CONTROL.
int jt_ptl_print_interfaces (int argc, char ** argv)
Definition at line 466 of file portals.c.
References g_net, g_net_is_compatible(), libcfs_ioctl_data::ioc_count, IOC_LIBCFS_GET_INTERFACE, libcfs_ioctl_data::ioc_net, libcfs_ioctl_data::ioc_u32, l_ioctl(), LIBCFS_IOC_INIT, LNET_DEV_ID, ptl_ipaddr_2_str(), and SOCKLND.
int jt_ptl_print_peers (int argc, char ** argv)
Definition at line 595 of file portals.c.
References g_net, g_net_is_compatible(), GNILND, libcfs_ioctl_data::ioc_count, libcfs_ioctl_data::ioc_flags, IOC_LIBCFS_GET_PEER, libcfs_ioctl_data::ioc_net, libcfs_ioctl_data::ioc_nid, libcfs_ioctl_data::ioc_u32, libcfs_ioctl_data::ioc_u64, l_ioctl(), libcfs_id2str(), LIBCFS_IOC_INIT, libcfs_nid2str(), LNET_DEV_ID, O2IBLND, ptl_ipaddr_2_str(), SOCKLND, and state.
int jt_ptl_print_routes (int argc, char ** argv)
Definition at line 1211 of file portals.c.
References lnet_ioctl_config_data::cfg_config_u, lnet_ioctl_config_data::cfg_count, lnet_ioctl_config_data::cfg_hdr, lnet_ioctl_config_data::cfg_net, lnet_ioctl_config_data::cfg_nid, lnet_ioctl_config_data::cfg_route, IOC_LIBCFS_GET_ROUTE, l_ioctl(), LIBCFS_IOC_INIT_V2, libcfs_net2str(), libcfs_nid2str(), and LNET_DEV_ID.
int jt_ptl_push_connection (int argc, char ** argv)
Definition at line 877 of file portals.c.
References g_net, g_net_is_compatible(), GNILND, IOC_LIBCFS_PUSH_CONNECTION, libcfs_ioctl_data::ioc_net, libcfs_ioctl_data::ioc_nid, l_ioctl(), LIBCFS_IOC_INIT, libcfs_str2anynid(), LNET_DEV_ID, LNET_NID_ANY, and SOCKLND.
int jt_ptl_testprotocompat (int argc, char ** argv)
Definition at line 1689 of file portals.c.
References end, libcfs_ioctl_data::ioc_flags, IOC_LIBCFS_TESTPROTOCOMPAT, l_ioctl(), LIBCFS_IOC_INIT, and LNET_DEV_ID.
int jt_ptl_which_nid (int argc, char ** argv)
Definition at line 399 of file portals.c.
References IOC_LIBCFS_LNET_DIST, libcfs_ioctl_data::ioc_nid, libcfs_ioctl_data::ioc_u32, l_ioctl(), LIBCFS_IOC_INIT, libcfs_nid2str(), libcfs_str2nid(), LNET_DEV_ID, LNET_NID_ANY, and order.
int jt_replace_nids (int argc, char ** argv)
Replace nids for given device.
lctl replace_nids <devicename> <nid1>[,nid2,nid3] Command should be started on MGS server. Only MGS server should be started (command execution returns error in another cases). Command mount -t lustre <MDT partition>=""> -o nosvc <mount point>=""> can be used for that.
llogs for MDTs and clients are processed. All records copied as is except add_uuid and setup. This records are skipped and recorded with new nids and uuid.
See also:
mgs_replace_nids
mgs_replace_nids_log
mgs_replace_handler
Definition at line 2295 of file obd.c.
References buf, CMD_HELP, get_mgs_device(), obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf2, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, jt_cmdname(), l2_ioctl(), MAX_IOC_BUFLEN, OBD_DEV_ID, OBD_IOC_REPLACE_NIDS, obd_ioctl_pack(), and rawbuf.
char* lcfg_get_devname (void)
Definition at line 111 of file lustre_cfg.c.
References lcfg_devname.
Referenced by jt_changelog_deregister(), jt_changelog_register(), jt_lfsck_query(), jt_lfsck_start(), jt_lfsck_stop(), and jt_obd_device().
int lcfg_ioctl (char * func, int dev_id, struct lustre_cfg * lcfg)
Definition at line 125 of file obd.c.
References buf, cur_device, obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_pbuf1, obd_ioctl_data::ioc_plen1, obd_ioctl_data::ioc_type, jt_cmdname(), l_ioctl(), lustre_cfg::lcfg_bufcount, lustre_cfg::lcfg_buflens, lustre_cfg_len(), LUSTRE_CFG_TYPE, MAX_IOC_BUFLEN, OBD_IOC_PROCESS_CFG, obd_ioctl_pack(), and rawbuf.
Referenced by do_add_uuid(), jt_lcfg_add_conn(), jt_lcfg_attach(), jt_lcfg_del_conn(), jt_lcfg_del_mount_option(), jt_lcfg_del_uuid(), jt_lcfg_param(), jt_lcfg_set_timeout(), jt_lcfg_setup(), jt_obd_cleanup(), and jt_obd_detach().
int lcfg_mgs_ioctl (char * func, int dev_id, struct lustre_cfg * lcfg)
Definition at line 173 of file obd.c.
References buf, get_mgs_device(), obd_ioctl_data::ioc_dev, obd_ioctl_data::ioc_pbuf1, obd_ioctl_data::ioc_plen1, obd_ioctl_data::ioc_type, jt_cmdname(), l_ioctl(), lustre_cfg::lcfg_bufcount, lustre_cfg::lcfg_buflens, lustre_cfg_len(), LUSTRE_CFG_TYPE, MAX_IOC_BUFLEN, OBD_IOC_PARAM, obd_ioctl_pack(), and rawbuf.
Referenced by jt_lcfg_mgsparam(), and jt_lcfg_mgsparam2().
int lcfg_set_devname (char * name)
Definition at line 78 of file lustre_cfg.c.
References lcfg_devname.
Referenced by do_device(), do_disconnect(), and jt_lcfg_attach().
void obd_finalize (int argc, char ** argv)
Definition at line 2956 of file obd.c.
References do_disconnect(), shmem_cleanup(), and signal_server().
Referenced by lctl_main().
int obd_initialize (int argc, char ** argv)
Definition at line 2945 of file obd.c.
References OBD_DEV_ID, OBD_DEV_MAJOR, OBD_DEV_MINOR, OBD_DEV_PATH, register_ioc_dev(), and shmem_setup().
int parse_devname (char * func, char * name)
Definition at line 262 of file obd.c.
References do_name2dev(), N2D_OFF, and ret.
Referenced by do_device().
int ptl_initialize (int argc, char ** argv)
Definition at line 284 of file portals.c.
References g_net_interactive, LNET_DEV_ID, LNET_DEV_MAJOR, LNET_DEV_MINOR, LNET_DEV_PATH, and register_ioc_dev().
Referenced by lctl_main(), and main().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.