Lustre: lustre/obdclass/obdo.c File Reference
lustre/obdclass/obdo.c File Reference
#include <linux/user_namespace.h>
#include <obd_class.h>
#include <lustre/lustre_idl.h>
Defines
#define DEBUG_SUBSYSTEM S_CLASS
Functions
void obdo_set_parent_fid (struct obdo *dst, const struct lu_fid *parent)
void obdo_from_inode (struct obdo *dst, struct inode *src, u64 valid)
void obdo_cpy_md (struct obdo *dst, const struct obdo *src, u64 valid)
void obdo_to_ioobj (const struct obdo *oa, struct obd_ioobj *ioobj)
Define Documentation
#define DEBUG_SUBSYSTEM S_CLASS
Definition at line 43 of file obdo.c.
Function Documentation
void obdo_cpy_md (struct obdo * dst, const struct obdo * src, u64 valid)
Definition at line 122 of file obdo.c.
References CDEBUG, D_INODE, DOSTID, LPX64, obdo::o_atime, obdo::o_blksize, obdo::o_blocks, obdo::o_ctime, obdo::o_flags, obdo::o_gid, obdo::o_handle, obdo::o_mode, obdo::o_mtime, obdo::o_oi, obdo::o_parent_oid, obdo::o_parent_seq, obdo::o_parent_ver, obdo::o_size, obdo::o_uid, obdo::o_valid, OBD_MD_FLATIME, OBD_MD_FLBLKSZ, OBD_MD_FLBLOCKS, OBD_MD_FLCTIME, OBD_MD_FLFID, OBD_MD_FLFLAGS, OBD_MD_FLGENER, OBD_MD_FLGID, OBD_MD_FLHANDLE, OBD_MD_FLMODE, OBD_MD_FLMTIME, OBD_MD_FLSIZE, OBD_MD_FLTYPE, OBD_MD_FLUID, and POSTID.
Referenced by echo_getattr().
void obdo_from_inode (struct obdo * dst, struct inode * src, u64 valid)
Definition at line 63 of file obdo.c.
References CDEBUG, D_INODE, from_kgid(), from_kuid(), LPX64, LTIME_S, obdo::o_atime, obdo::o_blksize, obdo::o_blocks, obdo::o_ctime, obdo::o_flags, obdo::o_gid, obdo::o_mode, obdo::o_mtime, obdo::o_size, obdo::o_uid, obdo::o_valid, OBD_MD_FLATIME, OBD_MD_FLBLKSZ, OBD_MD_FLBLOCKS, OBD_MD_FLCTIME, OBD_MD_FLFLAGS, OBD_MD_FLGID, OBD_MD_FLMODE, OBD_MD_FLMTIME, OBD_MD_FLSIZE, OBD_MD_FLTYPE, and OBD_MD_FLUID.
Referenced by ll_do_fiemap(), and vvp_req_attr_set().
void obdo_set_parent_fid (struct obdo * dst, const struct lu_fid * parent)
Definition at line 52 of file obdo.c.
References fid_oid(), fid_ver(), obdo::o_parent_oid, obdo::o_parent_seq, obdo::o_parent_ver, obdo::o_valid, OBD_MD_FLFID, and OBD_MD_FLGENER.
Referenced by ll_do_fiemap(), osc_fsync_ost(), osc_io_ladvise_start(), osc_io_setattr_start(), and vvp_req_attr_set().
void obdo_to_ioobj (const struct obdo * oa, struct obd_ioobj * ioobj)
Definition at line 161 of file obdo.c.
References obd_ioobj::ioo_max_brw, obd_ioobj::ioo_oid, obdo::o_oi, obdo::o_valid, OBD_MD_FLGROUP, ostid_set_seq_mdt0(), and unlikely.
Referenced by echo_client_prep_commit(), and osc_brw_prep_request().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.