Lustre: lustre/ofd/ofd_dev.c File Reference
lustre/ofd/ofd_dev.c File Reference
#include <obd_class.h>
#include <lustre_param.h>
#include <lustre_fid.h>
#include <lustre_lfsck.h>
#include <lustre/lustre_idl.h>
#include <lustre_dlm.h>
#include <lustre_quota.h>
#include <lustre_nodemap.h>
#include "ofd_internal.h"
Data Structures
struct locked_region
Defines
#define DEBUG_SUBSYSTEM S_FILTER
#define OBD_FAIL_OST_READ_NET OBD_FAIL_OST_BRW_NET
#define OBD_FAIL_OST_WRITE_NET OBD_FAIL_OST_BRW_NET
#define OST_BRW_READ OST_READ
#define OST_BRW_WRITE OST_WRITE
Functions
static int ofd_connect_to_next (const struct lu_env *env, struct ofd_device *m, const char *next, struct obd_export **exp)
Connect OFD to the next device in the stack.
static int ofd_stack_init (const struct lu_env *env, struct ofd_device *m, struct lustre_cfg *cfg)
Initialize stack of devices.
static void ofd_stack_fini (const struct lu_env *env, struct ofd_device *m, struct lu_device *top)
Finalize the device stack OFD-OSD.
static bool match_symlink_param (char *param)
Check if parameters are symlinks to the OSD.
static int ofd_process_config (const struct lu_env *env, struct lu_device *d, struct lustre_cfg *cfg)
Process various configuration parameters.
static int ofd_object_init (const struct lu_env *env, struct lu_object *o, const struct lu_object_conf *conf)
Implementation of lu_object_operations::loo_object_init for OFD.
static void ofd_object_free (const struct lu_env *env, struct lu_object *o)
Implementation of lu_object_operations::loo_object_free.
static int ofd_object_print (const struct lu_env *env, void *cookie, lu_printer_t p, const struct lu_object *o)
Implementation of lu_object_operations::loo_object_print.
static struct lu_object * ofd_object_alloc (const struct lu_env *env, const struct lu_object_header *hdr, struct lu_device *d)
Implementation of lu_device_operations::lod_object_alloc.
static int ofd_lfsck_out_notify (const struct lu_env *env, void *data, enum lfsck_events event)
Return the result of LFSCK run to the OFD.
static int ofd_prepare (const struct lu_env *env, struct lu_device *pdev, struct lu_device *dev)
Implementation of lu_device_operations::ldo_prepare.
static int ofd_recovery_complete (const struct lu_env *env, struct lu_device *dev)
Implementation of lu_device_operations::ldo_recovery_complete.
LPROC_SEQ_FOPS (lprocfs_nid_stats_clear)
static int ofd_procfs_init (struct ofd_device *ofd)
Initialize all needed procfs entries for OFD device.
static void ofd_procfs_add_brw_stats_symlink (struct ofd_device *ofd)
Expose OSD statistics to OFD layer.
static void ofd_procfs_fini (struct ofd_device *ofd)
Cleanup all procfs entries in OFD.
int ofd_fid_fini (const struct lu_env *env, struct ofd_device *ofd)
Stop SEQ/FID server on OFD.
int ofd_fid_init (const struct lu_env *env, struct ofd_device *ofd)
Start SEQ/FID server on OFD.
static int ofd_set_info_hdl (struct tgt_session_info *tsi)
OFD request handler for OST_SET_INFO RPC.
int ofd_fiemap_get (const struct lu_env *env, struct ofd_device *ofd, struct lu_fid *fid, struct fiemap *fiemap)
Get FIEMAP (FIle Extent MAPping) for object with the given FID.
static int lock_region (struct ldlm_namespace *ns, struct ldlm_res_id *res_id, unsigned long long begin, unsigned long long end, struct list_head *locked)
Lock single extent and save lock handle in the list.
static int lock_zero_regions (struct ldlm_namespace *ns, struct ldlm_res_id *res_id, struct fiemap *fiemap, struct list_head *locked)
Lock the sparse areas of given resource.
static void unlock_zero_regions (struct ldlm_namespace *ns, struct list_head *locked)
Unlock all previously locked sparse areas for given resource.
static int ofd_get_info_hdl (struct tgt_session_info *tsi)
OFD request handler for OST_GET_INFO RPC.
static int ofd_getattr_hdl (struct tgt_session_info *tsi)
OFD request handler for OST_GETATTR RPC.
static int ofd_setattr_hdl (struct tgt_session_info *tsi)
OFD request handler for OST_SETATTR RPC.
static int ofd_orphans_destroy (const struct lu_env *env, struct obd_export *exp, struct ofd_device *ofd, struct obdo *oa)
Destroy OST orphans.
static int ofd_create_hdl (struct tgt_session_info *tsi)
OFD request handler for OST_CREATE RPC.
static int ofd_destroy_hdl (struct tgt_session_info *tsi)
OFD request handler for OST_DESTROY RPC.
static int ofd_statfs_hdl (struct tgt_session_info *tsi)
OFD request handler for OST_STATFS RPC.
static int ofd_sync_hdl (struct tgt_session_info *tsi)
OFD request handler for OST_SYNC RPC.
static int ofd_punch_hdl (struct tgt_session_info *tsi)
OFD request handler for OST_PUNCH RPC.
static int ofd_ladvise_hdl (struct tgt_session_info *tsi)
OFD request handler for OST_LADVISE RPC.
static int ofd_quotactl (struct tgt_session_info *tsi)
OFD request handler for OST_QUOTACTL RPC.
static int prolong_timeout (struct ptlrpc_request *req, struct ldlm_lock *lock)
Calculate the amount of time for lock prolongation.
static int ofd_prolong_one_lock (struct tgt_session_info *tsi, struct ldlm_lock *lock, struct ldlm_extent *extent)
Prolong single lock timeout.
static int ofd_prolong_extent_locks (struct tgt_session_info *tsi, __u64 start, __u64 end)
Prolong lock timeout for the given extent.
static int ofd_rw_hpreq_lock_match (struct ptlrpc_request *req, struct ldlm_lock *lock)
Implementation of ptlrpc_hpreq_ops::hpreq_lock_match for OFD RW requests.
static int ofd_rw_hpreq_check (struct ptlrpc_request *req)
Implementation of ptlrpc_hpreq_ops::hpreq_lock_check for OFD RW requests.
static void ofd_rw_hpreq_fini (struct ptlrpc_request *req)
Implementation of ptlrpc_hpreq_ops::hpreq_lock_fini for OFD RW requests.
static int ofd_punch_hpreq_lock_match (struct ptlrpc_request *req, struct ldlm_lock *lock)
Implementation of ptlrpc_hpreq_ops::hpreq_lock_match for OST_PUNCH request.
static int ofd_punch_hpreq_check (struct ptlrpc_request *req)
Implementation of ptlrpc_hpreq_ops::hpreq_lock_check for OST_PUNCH request.
static void ofd_punch_hpreq_fini (struct ptlrpc_request *req)
Implementation of ptlrpc_hpreq_ops::hpreq_lock_fini for OST_PUNCH request.
static void ofd_hp_brw (struct tgt_session_info *tsi)
Assign high priority operations to an IO request.
static void ofd_hp_punch (struct tgt_session_info *tsi)
Assign high priority operations to an punch request.
LU_KEY_INIT_FINI (ofd, struct ofd_thread_info)
static void ofd_key_exit (const struct lu_context *ctx, struct lu_context_key *key, void *data)
Implementation of lu_context_key::lct_key_exit.
static int ofd_init0 (const struct lu_env *env, struct ofd_device *m, struct lu_device_type *ldt, struct lustre_cfg *cfg)
Initialize OFD device according to parameters in the config log cfg.
static void ofd_fini (const struct lu_env *env, struct ofd_device *m)
Stop the OFD device.
static struct lu_device * ofd_device_fini (const struct lu_env *env, struct lu_device *d)
Implementation of lu_device_type_operations::ldto_device_fini.
static struct lu_device * ofd_device_free (const struct lu_env *env, struct lu_device *d)
Implementation of lu_device_type_operations::ldto_device_free.
static struct lu_device * ofd_device_alloc (const struct lu_env *env, struct lu_device_type *t, struct lustre_cfg *cfg)
Implementation of lu_device_type_operations::ldto_device_alloc.
LU_TYPE_INIT_FINI (ofd,&ofd_thread_key)
static int __init ofd_init (void)
Initialize OFD module.
static void __exit ofd_exit (void)
Stop OFD module.
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Object Filtering Device")
MODULE_VERSION (LUSTRE_VERSION_STRING)
MODULE_LICENSE ("GPL")
module_init (ofd_init)
module_exit (ofd_exit)
Variables
static struct kmem_cache * ofd_object_kmem
static struct lu_kmem_descr ofd_caches []
static struct cfg_interop_param ofd_interop_param []
static struct lu_object_operations ofd_obj_ops
static struct lu_device_operations ofd_lu_ops
lu_device_operations matrix for OFD device.
static struct ptlrpc_hpreq_ops ofd_hpreq_rw
static struct ptlrpc_hpreq_ops ofd_hpreq_punch
static struct tgt_handler ofd_tgt_handlers []
Table of OFD-specific request handlers.
static struct tgt_opc_slice ofd_common_slice []
struct lu_context_key ofd_thread_key
static struct
lu_device_type_operations ofd_device_type_ops
static struct lu_device_type ofd_device_type
Define Documentation
#define DEBUG_SUBSYSTEM S_FILTER
Definition at line 69 of file ofd_dev.c.
#define OBD_FAIL_OST_READ_NET OBD_FAIL_OST_BRW_NET
Definition at line 2675 of file ofd_dev.c.
#define OBD_FAIL_OST_WRITE_NET OBD_FAIL_OST_BRW_NET
Definition at line 2676 of file ofd_dev.c.
#define OST_BRW_READ OST_READ
Definition at line 2677 of file ofd_dev.c.
#define OST_BRW_WRITE OST_WRITE
Definition at line 2678 of file ofd_dev.c.
Function Documentation
static int lock_region (struct ldlm_namespace * ns, struct ldlm_res_id * res_id, unsigned long long begin, unsigned long long end, struct list_head * locked) [static]
Lock single extent and save lock handle in the list.
This is supplemental function for lock_zero_regions(). It allocates new locked_region structure and locks it with extent lock, then adds it to the list of all such regions.
Parameters:
[in] ns LDLM namespace
[in] res_id resource ID
[in] begin start of region
[in] end end of region
[in] locked list head of regions list
Return values:
0 if successful locking
negative value on error
Definition at line 1017 of file ofd_dev.c.
References __u64, CDEBUG, D_OTHER, LASSERT, LCK_PR, locked_region::lh, locked_region::list, list_add(), OBD_ALLOC_PTR, and tgt_extent_lock().
Referenced by lock_zero_regions().
static int lock_zero_regions (struct ldlm_namespace * ns, struct ldlm_res_id * res_id, struct fiemap * fiemap, struct list_head * locked) [static]
Lock the sparse areas of given resource.
The locking of sparse areas will cause dirty data to be flushed back from clients. This is used when getting the FIEMAP of an object to make sure there is no unaccounted cached data on clients.
This function goes through fiemap list of extents and locks only sparse areas between extents.
Parameters:
[in] ns LDLM namespace
[in] res_id resource ID
[in] fiemap file extents mapping on disk
[in] locked list head of regions list
Return values:
0 if successful
negative value on error
Definition at line 1060 of file ofd_dev.c.
References __u64, begin, CDEBUG, D_OTHER, ENTRY, lock_region(), and RETURN.
Referenced by ofd_get_info_hdl().
LPROC_SEQ_FOPS (lprocfs_nid_stats_clear)
LU_KEY_INIT_FINI (ofd , struct ofd_thread_info)
LU_TYPE_INIT_FINI (ofd , & ofd_thread_key)
static bool match_symlink_param (char * param) [static]
Check if parameters are symlinks to the OSD.
Some parameters were moved from ofd to osd and only their symlinks were kept in ofd by LU-3106. They are: -writehthrough_cache_enable -readcache_max_filesize -read_cache_enable -brw_stats
Since they are not included by the static lprocfs var list, a pre-check is added for them to avoid "unknown param" errors. If they are matched in this check, they will be passed to the OSD directly.
Parameters:
[in] param parameters to check
Return values:
true if param is symlink to OSD param false otherwise
Definition at line 283 of file ofd_dev.c.
References class_match_param(), and PARAM_OST.
Referenced by ofd_process_config().
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Object Filtering Device")
module_exit (ofd_exit)
module_init (ofd_init)
MODULE_LICENSE ("GPL")
MODULE_VERSION (LUSTRE_VERSION_STRING)
static int ofd_connect_to_next (const struct lu_env * env, struct ofd_device * m, const char * next, struct obd_export ** exp) [static]
Connect OFD to the next device in the stack.
This function is used for device stack configuration and links OFD device with bottom OSD device.
Parameters:
[in] env execution environment
[in] m OFD device
[in] next name of next device in the stack
[out] exp export to return
Return values:
0 and export in exp if successful
negative value on error
Definition at line 110 of file ofd_dev.c.
References CERROR, class_name2obd(), dt_device::dd_lu_dev, ENTRY, obd_export::exp_obd, GOTO, LASSERT, lu_device::ld_site, lu_site::ls_top_dev, lu2dt_dev(), LUSTRE_VERSION_CODE, OBD_ALLOC_PTR, obd_connect(), OBD_CONNECT_VERSION, OBD_FREE_PTR, obd_device::obd_lu_dev, obd_device::obd_uuid, obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_version, ofd_device::ofd_dt_dev, ofd_name(), ofd_device::ofd_osd, ofd_device::ofd_osd_exp, and RETURN.
Referenced by ofd_stack_init().
static int ofd_create_hdl (struct tgt_session_info * tsi) [static]
OFD request handler for OST_CREATE RPC.
This is OFD-specific part of request handling. Its main purpose is to create new data objects on OST, but it also used to destroy orphans.
Parameters:
[in] tsi target session environment for this request
Return values:
0 if successful
negative value on error
Definition at line 1553 of file ofd_dev.c.
References CDEBUG, CERROR, cfs_time_after(), cfs_time_shift(), class_export_get(), D_HA, D_INFO, DISK_TIMEOUT, DOSTID, ENTRY, EXIT, obd_export::exp_conn_cnt, fid_seq_is_idif(), fid_seq_is_mdt(), fid_seq_is_mdt0(), fid_seq_is_norm(), FID_SEQ_OST_MDT0, fid_to_ostid(), ofd_thread_info::fti_fid, GOTO, IDIF_MAX_OID, LASSERT, LCONSOLE_WARN, LPROC_OFD_STATS_CREATE, LPU64, LPX64, LUSTRE_DATA_SEQ_MAX_WIDTH, lustre_msg_get_conn_cnt(), lustre_msg_get_flags(), MSG_REPLAY, obdo::o_flags, obdo::o_oi, obdo::o_valid, ost_body::oa, OBD_FAIL_CHECK, OBD_FAIL_OST_EROFS, OBD_FL_DELORPHAN, OBD_FL_RECREATE_OBJS, OBD_MD_FLFLAGS, OBD_MD_FLGROUP, OBD_MD_FLID, ofd_counter_incr(), ofd_exp(), ofd_grant_commit(), ofd_grant_create(), ofd_info(), ofd_device::ofd_lastid_gen, ofd_device::ofd_lastid_rebuilding, ofd_device::ofd_lastid_rwsem, ofd_name(), ofd_obd(), ofd_obd_disconnect(), ofd_orphans_destroy(), ofd_precreate_batch(), ofd_precreate_objects(), ofd_seq_last_oid(), ofd_seq_last_oid_set(), ofd_seq_load(), ofd_seq_put(), ost_id::oi_fid, ofd_seq::os_create_lock, ofd_seq::os_destroys_in_progress, ofd_seq::os_oi, OST_MAX_PRECREATE, ostid_id(), ostid_seq(), ostid_set_id(), POSTID, req_capsule_server_get(), RETURN, RMF_OST_BODY, ptlrpc_request::rq_reqmsg, tgt_ses_req(), tgt_session_info::tsi_env, tgt_session_info::tsi_exp, tgt_session_info::tsi_jobid, tgt_session_info::tsi_ost_body, tgt_session_info::tsi_pill, and unlikely.
static int ofd_destroy_hdl (struct tgt_session_info * tsi) [static]
OFD request handler for OST_DESTROY RPC.
This is OFD-specific part of request handling. It destroys data objects related to destroyed object on MDT.
Parameters:
[in] tsi target session environment for this request
Return values:
0 if successful
negative value on error
Definition at line 1825 of file ofd_dev.c.
References CDEBUG, CERROR, D_HA, D_INODE, DFID, DOSTID, ENTRY, fid_set_id(), fid_to_ostid(), ofd_thread_info::fti_fid, GOTO, LASSERT, LATF_SKIP, LPROC_OFD_STATS_DESTROY, obdo::o_misc, obdo::o_oi, obdo::o_valid, ost_body::oa, OBD_FAIL_CHECK, OBD_FAIL_OST_EROFS, OBD_MD_FLOBJCOUNT, ofd_counter_incr(), ofd_destroy_by_fid(), ofd_exp(), ofd_name(), ost_id::oi_fid, ostid_id(), PFID, POSTID, RCL_CLIENT, req_capsule_client_get(), req_capsule_field_present(), req_capsule_server_get(), RETURN, RMF_DLM_REQ, RMF_OST_BODY, tgt_ses_req(), tsi2ofd_info(), tgt_session_info::tsi_env, tgt_session_info::tsi_exp, tgt_session_info::tsi_jobid, tgt_session_info::tsi_ost_body, tgt_session_info::tsi_pill, and unlikely.
static struct lu_device* ofd_device_alloc (const struct lu_env * env, struct lu_device_type * t, struct lustre_cfg * cfg) [static, read]
Implementation of lu_device_type_operations::ldto_device_alloc.
This function allocates the new OFD device. It is called from obd_setup() if OBD device had lu_device_type defined.
Parameters:
[in] env execution environment
[in] t lu_device_type of OFD device
[in] cfg configuration log
Return values:
pointer to the lu_device of just allocated OFD
ERR_PTR of return value on error
Definition at line 3069 of file ofd_dev.c.
References dt_device::dd_lu_dev, dt_device_init(), OBD_ALLOC_PTR, ofd_device_free(), ofd_device::ofd_dt_dev, and ofd_init0().
static struct lu_device* ofd_device_fini (const struct lu_env * env, struct lu_device * d) [static, read]
Implementation of lu_device_type_operations::ldto_device_fini.
Finalize device. Dual to ofd_device_init(). It is called from obd_precleanup() and stops the current device.
Parameters:
[in] env execution environment
[in] d LU device of OFD
Return values:
NULL
Definition at line 3028 of file ofd_dev.c.
References ENTRY, ofd_dev(), ofd_fini(), and RETURN.
static struct lu_device* ofd_device_free (const struct lu_env * env, struct lu_device * d) [static, read]
Implementation of lu_device_type_operations::ldto_device_free.
Free OFD device. Dual to ofd_device_alloc().
Parameters:
[in] env execution environment
[in] d LU device of OFD
Return values:
NULL
Definition at line 3046 of file ofd_dev.c.
References dt_device_fini(), OBD_FREE_PTR, ofd_dev(), ofd_device::ofd_dt_dev, and RETURN.
Referenced by ofd_device_alloc().
static void __exit ofd_exit (void) [static]
Stop OFD module.
This function is called upon OFD module unloading. It frees all related structures and unregisters OFD device type.
Definition at line 3148 of file ofd_dev.c.
References class_unregister_type(), lu_kmem_fini(), LUSTRE_OST_NAME, and ofd_fmd_exit().
int ofd_fid_fini (const struct lu_env * env, struct ofd_device * ofd)
Stop SEQ/FID server on OFD.
Parameters:
[in] env execution environment
[in] ofd OFD device
Return values:
0 if successful
negative value on error
Definition at line 802 of file ofd_dev.c.
References ofd_device::ofd_seq_site, and seq_site_fini().
Referenced by ofd_seqs_fini(), and ofd_seqs_init().
int ofd_fid_init (const struct lu_env * env, struct ofd_device * ofd)
Start SEQ/FID server on OFD.
The SEQ/FID server on OFD is needed to allocate FIDs for new objects. It also connects to the master server to get own FID sequence (SEQ) range to this particular OFD. Typically that happens when the OST is first formatted or in the rare case that it exhausts the local sequence range.
The sequence range is allocated out to the MDTs for OST object allocations, and not directly to the clients.
Parameters:
[in] env execution environment
[in] ofd OFD device
Return values:
0 if successful
negative value on error
Definition at line 824 of file ofd_dev.c.
References CERROR, dt_device::dd_lu_dev, GOTO, lu_site::ld_seq_site, lu_device::ld_site, lr_server_data::lsd_osd_index, lu_seq_range::lsr_index, lu_server_seq::lss_space, LUSTRE_SEQ_DATA, LUSTRE_SEQ_SERVER, lu_target::lut_lsd, name, OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, ofd_device::ofd_dt_dev, ofd_device::ofd_lut, ofd_name(), ofd_device::ofd_osd, ofd_device::ofd_seq_site, seq_client_fini(), seq_client_init(), seq_server_fini(), seq_server_init(), seq_server_set_cli(), seq_server_site::ss_client_seq, seq_server_site::ss_lu, seq_server_site::ss_node_id, and seq_server_site::ss_server_seq.
Referenced by ofd_seqs_init().
int ofd_fiemap_get (const struct lu_env * env, struct ofd_device * ofd, struct lu_fid * fid, struct fiemap * fiemap)
Get FIEMAP (FIle Extent MAPping) for object with the given FID.
This function returns a list of extents which describes how a file's blocks are laid out on the disk.
Parameters:
[in] env execution environment
[in] ofd OFD device
[in] fid FID of object
[in] fiemap fiemap structure to fill with data
Return values:
0 if fiemap is filled with data successfully
negative value on error
Definition at line 973 of file ofd_dev.c.
References CERROR, DFID, dt_fiemap_get(), ofd_name(), ofd_object_child(), ofd_object_exists(), ofd_object_find(), ofd_object_put(), ofd_read_lock(), ofd_read_unlock(), and PFID.
Referenced by ofd_get_info(), and ofd_get_info_hdl().
static void ofd_fini (const struct lu_env * env, struct ofd_device * m) [static]
Stop the OFD device.
This function stops the OFD device and all its subsystems. This is the end of OFD lifecycle.
Parameters:
[in] env execution environment
[in] m OFD device
Definition at line 2983 of file ofd_dev.c.
References dt_device::dd_lu_dev, EXIT, LASSERT, lu_device::ld_obd, lu_device::ld_ref, ldlm_namespace_free_post(), ldlm_namespace_free_prior(), lfsck_degister(), lfsck_stop(), lfsck_stop::ls_flags, LS_PAUSED, lfsck_stop::ls_status, obd_exports_barrier(), obd_device::obd_force, obd_device::obd_name, obd_device::obd_namespace, obd_zombie_barrier(), ofd_device::ofd_dt_dev, ofd_fs_cleanup(), ofd_device::ofd_lut, ofd_device::ofd_namespace, ofd_obd(), ofd_device::ofd_osd, ofd_procfs_fini(), ofd_stack_fini(), ofd_stop_inconsistency_verification_thread(), server_put_mount(), target_recovery_fini(), and tgt_fini().
Referenced by ofd_device_fini().
static int ofd_get_info_hdl (struct tgt_session_info * tsi) [static]
OFD request handler for OST_GET_INFO RPC.
This is OFD-specific part of request handling. The OFD-specific keys are:
KEY_LAST_ID (obsolete)
KEY_FIEMAP
KEY_LAST_FID
This function reads needed data from storage and fills reply with it.
Note: the KEY_LAST_ID is obsolete, replaced by KEY_LAST_FID on newer MDTs, and is kept for compatibility.
Parameters:
[in] tsi target session environment for this request
Return values:
0 if successful
negative value on error
Definition at line 1136 of file ofd_dev.c.
References CDEBUG, CERROR, D_HA, D_INODE, DEBUG_REQ, DFID, ENTRY, err_serious(), fid_le_to_cpu(), fiemap_count_to_size(), ofd_thread_info::fti_ostid, ofd_thread_info::fti_resid, GOTO, INIT_LIST_HEAD, KEY_FIEMAP, KEY_IS, KEY_LAST_FID, KEY_LAST_ID, ll_fiemap_info_key::lfik_fiemap, ll_fiemap_info_key::lfik_oa, list_empty(), lock_zero_regions(), LPROC_OFD_STATS_GET_INFO, lr_server_data::lsd_osd_index, lu_target::lut_lsd, obdo::o_flags, obdo::o_oi, obdo::o_valid, OBD_FL_SRVLOCK, OBD_MD_FLFLAGS, ofd_counter_incr(), ofd_exp(), ofd_fiemap_get(), ofd_device::ofd_lut, ofd_name(), ofd_device::ofd_namespace, ofd_seq_last_oid(), ofd_seq_load(), ofd_seq_put(), ost_id::oi_fid, ofd_seq::os_oi, ost_fid_build_resid(), ostid_seq(), ostid_to_fid(), PFID, RCL_CLIENT, RCL_SERVER, req_capsule_client_get(), req_capsule_extend(), req_capsule_get_size(), req_capsule_server_get(), req_capsule_server_pack(), req_capsule_set_size(), RETURN, RMF_FID, RMF_FIEMAP_KEY, RMF_FIEMAP_VAL, RMF_GETINFO_KEY, RMF_OBD_ID, RQF_OST_GET_INFO_FIEMAP, RQF_OST_GET_INFO_LAST_FID, RQF_OST_GET_INFO_LAST_ID, tgt_name(), tgt_ses_req(), tgt_validate_obdo(), tsi2ofd_info(), tgt_session_info::tsi_env, tgt_session_info::tsi_exp, tgt_session_info::tsi_jobid, tgt_session_info::tsi_pill, tgt_session_info::tsi_tgt, and unlock_zero_regions().
static int ofd_getattr_hdl (struct tgt_session_info * tsi) [static]
OFD request handler for OST_GETATTR RPC.
This is OFD-specific part of request handling. It finds the OFD object by its FID, gets attributes from storage and packs result to the reply.
Parameters:
[in] tsi target session environment for this request
Return values:
0 if successful
negative value on error
Definition at line 1281 of file ofd_dev.c.
References __u64, dt_version_get(), ENTRY, ofd_thread_info::fti_attr, GOTO, LA_GID, LA_UID, LASSERT, LCK_PR, LCK_PW, LPROC_OFD_STATS_GETATTR, lu_target::lut_obd, obdo::o_data_version, obdo::o_flags, obdo::o_oi, obdo::o_valid, ost_body::oa, OBD_FL_FLUSH, OBD_FL_SRVLOCK, OBD_MD_FLDATAVERSION, OBD_MD_FLFLAGS, OBD_MD_FLGROUP, OBD_MD_FLID, obd_device::obd_namespace, OBD_OBJECT_EOF, obdo_from_la(), ofd_attr_get(), ofd_counter_incr(), ofd_exp(), ofd_object_child(), ofd_object_find_exists(), ofd_object_put(), OFD_VALID_FLAGS, req_capsule_server_get(), RETURN, RMF_OST_BODY, tgt_drop_id(), tgt_extent_lock(), tgt_extent_unlock(), tsi2ofd_info(), tgt_session_info::tsi_env, tgt_session_info::tsi_exp, tgt_session_info::tsi_fid, tgt_session_info::tsi_jobid, tgt_session_info::tsi_ost_body, tgt_session_info::tsi_pill, tgt_session_info::tsi_resid, tgt_session_info::tsi_tgt, and unlikely.
static void ofd_hp_brw (struct tgt_session_info * tsi) [static]
Assign high priority operations to an IO request.
Check if the incoming request is a candidate for high-priority processing. If it is, assign it a high priority operations table.
Parameters:
[in] tsi target session environment for this request
Definition at line 2636 of file ofd_dev.c.
References ENTRY, obd_ioobj::ioo_bufcnt, LASSERT, OBD_BRW_SRVLOCK, req_capsule_client_get(), RMF_NIOBUF_REMOTE, RMF_OBD_IOOBJ, niobuf_remote::rnb_flags, tgt_ses_req(), and tgt_session_info::tsi_pill.
static void ofd_hp_punch (struct tgt_session_info * tsi) [static]
Assign high priority operations to an punch request.
Check if the incoming request is a candidate for high-priority processing. If it is, assign it a high priority operations table.
Parameters:
[in] tsi target session environment for this request
Definition at line 2665 of file ofd_dev.c.
References LASSERT, obdo::o_flags, obdo::o_valid, ost_body::oa, OBD_FL_SRVLOCK, OBD_MD_FLFLAGS, tgt_ses_req(), and tgt_session_info::tsi_ost_body.
static int __init ofd_init (void) [static]
Initialize OFD module.
This function is called upon module loading. It registers OFD device type and prepares all in-memory structures used by all OFD devices.
Return values:
0 if successful
negative value on error
Definition at line 3123 of file ofd_dev.c.
References class_register_type(), lu_kmem_fini(), lu_kmem_init(), LUSTRE_OST_NAME, ofd_fmd_init(), and ofd_obd_ops.
static int ofd_init0 (const struct lu_env * env, struct ofd_device * m, struct lu_device_type * ldt, struct lustre_cfg * cfg) [static]
Initialize OFD device according to parameters in the config log cfg.
This is the main starting point of OFD initialization. It fills all OFD parameters with their initial values and calls other initializing functions to set up all OFD subsystems.
Parameters:
[in] env execution environment
[in] m OFD device
[in] ldt LU device type of OFD
[in] cfg configuration log
Return values:
0 if successful
negative value on error
Definition at line 2814 of file ofd_dev.c.
References CERROR, cfs_time_shift_64(), class_name2obd(), CWARN, dt_device::dd_lu_dev, dt_conf_get(), ENTRY, ofd_thread_info::fti_u, GOTO, INIT_LIST_HEAD, lustre_cfg::lcfg_bufcount, lu_device::ld_obd, lu_device::ld_ops, LDLM_CB_REPLY_PORTAL, LDLM_CB_REQUEST_PORTAL, ldlm_namespace_free(), LDLM_NAMESPACE_GREEDY, ldlm_namespace_new(), LDLM_NAMESPACE_SERVER, LDLM_NS_TYPE_OST, ldlm_register_intent(), lu_env_refill(), LUSTRE_CFG_BUFLEN, lustre_cfg_string(), ofd_thread_info::name, ldlm_namespace::ns_lvbo, ldlm_namespace::ns_lvbp, obd_device::obd_dev_lock, OBD_FAIL_OST_ALL_REPLY_NET, OBD_FAIL_OST_ALL_REQUEST_NET, obd_device::obd_force, obd_device::obd_ldlm_client, obd_device::obd_lu_dev, obd_device::obd_name, obd_device::obd_namespace, obd_device::obd_no_conn, obd_device::obd_replayable, obd_device::obd_uuid, OBT_MAGIC, ofd_device::ofd_batch_lock, ofd_device::ofd_blockbits, ofd_device::ofd_brw_size, ofd_device::ofd_dt_conf, ofd_device::ofd_dt_dev, ofd_device::ofd_flags_lock, ofd_device::ofd_fmd_max_age, OFD_FMD_MAX_AGE_DEFAULT, ofd_device::ofd_fmd_max_num, OFD_FMD_MAX_NUM_DEFAULT, ofd_fs_cleanup(), ofd_fs_setup(), ofd_device::ofd_grant_compat_disable, ofd_device::ofd_grant_lock, ofd_device::ofd_inconsistency_list, ofd_device::ofd_inconsistency_lock, ofd_device::ofd_inconsistency_thread, ofd_info(), ofd_info_init(), ofd_intent_policy(), ofd_device::ofd_lastid_rwsem, ofd_device::ofd_lut, ofd_lvbo, ofd_device::ofd_namespace, ofd_device::ofd_osd, ofd_device::ofd_osfs_age, ofd_device::ofd_osfs_inflight, ofd_device::ofd_osfs_lock, ofd_device::ofd_osfs_unstable, ofd_device::ofd_precreate_batch, OFD_PRECREATE_BATCH_DEFAULT, OFD_PRECREATE_BATCH_SMALL, OFD_PRECREATE_SMALL_FS, ofd_procfs_add_brw_stats_symlink(), ofd_procfs_fini(), ofd_procfs_init(), ofd_device::ofd_raid_degraded, ofd_device::ofd_seq_count, ofd_slc_set(), ofd_device::ofd_soft_sync_limit, OFD_SOFT_SYNC_LIMIT_DEFAULT, ofd_stack_fini(), ofd_stack_init(), ofd_start_inconsistency_verification_thread(), ofd_device::ofd_statfs_inflight, ofd_statfs_internal(), ofd_device::ofd_syncjournal, ofd_device::ofd_tot_dirty, ofd_device::ofd_tot_granted, ofd_device::ofd_tot_pending, ONE_MB_BRW_SIZE, obd_statfs::os_blocks, obd_statfs::os_bsize, ofd_thread_info::osfs, ptlrpc_init_client(), RETURN, ptlrpc_thread::t_ctl_waitq, tgt_adapt_sptlrpc_conf(), tgt_fini(), tgt_init(), obd_device::u, and obd_uuid::uuid.
Referenced by ofd_device_alloc().
static void ofd_key_exit (const struct lu_context * ctx, struct lu_context_key * key, void * data) [static]
Implementation of lu_context_key::lct_key_exit.
Optional method called on lu_context_exit() for all allocated keys. It is used in OFD to sanitize context values which may be re-used during another request processing by the same thread.
Parameters:
[in] ctx execution context
[in] key context key
[in] data ofd_thread_info
Definition at line 2777 of file ofd_dev.c.
References ofd_thread_info::fti_attr, ofd_thread_info::fti_env, ofd_thread_info::fti_exp, ofd_thread_info::fti_pre_version, ofd_thread_info::fti_used, and ofd_thread_info::fti_xid.
static int ofd_ladvise_hdl (struct tgt_session_info * tsi) [static]
OFD request handler for OST_LADVISE RPC.
Tune cache or perfetch policies according to advices.
Parameters:
[in] tsi target session environment for this request
Return values:
0 if successful
negative errno on error
Definition at line 2118 of file ofd_dev.c.
References ENTRY, err_serious(), ofd_thread_info::fti_fid, LADVISE_MAGIC, ladvise_hdr::lah_count, ladvise_hdr::lah_flags, ladvise_hdr::lah_magic, LASSERT, LF_MASK, lu_ladvise::lla_advice, lu_ladvise::lla_end, lu_ladvise::lla_start, lr_server_data::lsd_osd_index, lu_target::lut_lsd, obdo::o_oi, obdo::o_valid, ost_body::oa, OBD_MD_FLID, ofd_exp(), ofd_info_init(), ofd_device::ofd_lut, ofd_object_find(), ofd_object_put(), ostid_to_fid(), RCL_CLIENT, req_capsule_client_get(), req_capsule_get_size(), req_capsule_server_get(), RETURN, RMF_OST_BODY, RMF_OST_LADVISE, RMF_OST_LADVISE_HDR, ptlrpc_request::rq_pill, ptlrpc_request::rq_status, tgt_ses_req(), tgt_session_info::tsi_exp, tgt_session_info::tsi_ost_body, and tgt_session_info::tsi_pill.
static int ofd_lfsck_out_notify (const struct lu_env * env, void * data, enum lfsck_events event) [static]
Return the result of LFSCK run to the OFD.
Notify OFD about result of LFSCK run. That may block the new object creation until problem is fixed by LFSCK.
Parameters:
[in] env execution environment
[in] data pointer to the OFD device
[in] event LFSCK event type
Return values:
0 if successful
negative value on unknown event
Definition at line 528 of file ofd_dev.c.
References CERROR, CWARN, LE_LASTID_REBUILDING, LE_LASTID_REBUILT, obd_device::obd_name, ofd_device::ofd_lastid_gen, ofd_device::ofd_lastid_rebuilding, ofd_device::ofd_lastid_rwsem, ofd_name(), ofd_obd(), and ofd_seqs_free().
Referenced by ofd_prepare().
static struct lu_object* ofd_object_alloc (const struct lu_env * env, const struct lu_object_header * hdr, struct lu_device * d) [static, read]
Implementation of lu_device_operations::lod_object_alloc.
This function allocates OFD part of compound OFD-OSD object and initializes its header, because OFD is the top device in stack
Parameters:
[in] env execution environment
[in] hdr object header, NULL for OFD
[in] d lu_device
Return values:
allocated object if successful
NULL value on failed allocation
Definition at line 490 of file ofd_dev.c.
References dt_object::do_lu, ENTRY, lu_object::lo_ops, lu_object_add_top(), lu_object_header_init(), lu_object_init(), OBD_SLAB_ALLOC_PTR_GFP, ofd_object_kmem, ofd_object::ofo_header, ofd_object::ofo_obj, and RETURN.
static void ofd_object_free (const struct lu_env * env, struct lu_object * o) [static]
Implementation of lu_object_operations::loo_object_free.
Finish OFD object lifecycle and free its memory.
Parameters:
[in] env execution environment
[in] o LU object of OFD object
Definition at line 434 of file ofd_dev.c.
References CDEBUG, D_INFO, DFID, ENTRY, EXIT, lu_object::lo_header, lu_object_fid(), lu_object_fini(), lu_object_header_fini(), OBD_SLAB_FREE_PTR, ofd_obj(), ofd_object_kmem, and PFID.
static int ofd_object_init (const struct lu_env * env, struct lu_object * o, const struct lu_object_conf * conf) [static]
Implementation of lu_object_operations::loo_object_init for OFD.
Allocate just the next object (OSD) in stack.
Parameters:
[in] env execution environment
[in] o lu_object of OFD object
[in] conf additional configuration parameters, not used here
Return values:
0 if successful
negative value on error
Definition at line 403 of file ofd_dev.c.
References CDEBUG, D_INFO, dt_device::dd_lu_dev, DFID, ENTRY, lu_device::ld_ops, lu_device_operations::ldo_object_alloc, lu_object::lo_dev, lu_object::lo_header, lu_object_add(), lu_object_fid(), ofd_dev(), ofd_device::ofd_osd, PFID, and RETURN.
static int ofd_object_print (const struct lu_env * env, void * cookie, lu_printer_t p, const struct lu_object * o) [static]
Implementation of lu_object_operations::loo_object_print.
Print OFD part of compound OFD-OSD object. See lu_object_print() and LU_OBJECT_DEBUG() for more details about the compound object printing.
Parameters:
[in] env execution environment
[in] cookie opaque data passed to the printer function
[in] p printer function to use
[in] o LU object of OFD object
Return values:
0 if successful
negative value on error
Definition at line 465 of file ofd_dev.c.
References LUSTRE_OST_NAME.
static int ofd_orphans_destroy (const struct lu_env * env, struct obd_export * exp, struct ofd_device * ofd, struct obdo * oa) [static]
Destroy OST orphans.
This is part of OST_CREATE RPC handling. If there is flag OBD_FL_DELORPHAN set then we must destroy possible orphaned objects.
Parameters:
[in] env execution environment
[in] exp OBD export
[in] ofd OFD device
[in] oa obdo structure for reply
Return values:
0 if successful
negative value on error
Definition at line 1461 of file ofd_dev.c.
References CDEBUG, CEMERG, CERROR, D_HA, D_INFO, DFID, done, DOSTID, ENTRY, exp_connect_flags(), fid_set_id(), ofd_thread_info::fti_fid, GOTO, LASSERT, LCONSOLE, likely, obdo::o_oi, OBD_CONNECT_SKIP_ORPHAN, OBD_FAIL_CHECK, OBD_FAIL_OST_NODESTROY, ofd_destroy_by_fid(), ofd_info(), ofd_name(), ofd_seq_get(), ofd_seq_last_oid(), ofd_seq_last_oid_set(), ofd_seq_last_oid_write(), ofd_seq_put(), ost_id::oi, ost_id::oi_fid, ostid_id(), ostid_seq(), ostid_set_id(), PFID, POSTID, RETURN, and unlikely.
Referenced by ofd_create_hdl().
static int ofd_prepare (const struct lu_env * env, struct lu_device * pdev, struct lu_device * dev) [static]
Implementation of lu_device_operations::ldo_prepare.
This method is called after layer has been initialized and before it starts serving user requests. In OFD it starts lfsk check routines and initializes recovery.
Parameters:
[in] env execution environment
[in] pdev higher device in stack, NULL for OFD
[in] dev lu_device of OFD device
Return values:
0 if successful
negative value on error
Definition at line 576 of file ofd_dev.c.
References CERROR, dt_device::dd_lu_dev, ENTRY, LASSERT, LASSERTF, lu_device::ld_ops, lu_device_operations::ldo_prepare, lfsck_register(), lfsck_register_namespace(), obd_device::obd_dev_lock, obd_device::obd_name, obd_device::obd_no_conn, obd_device::obd_recovering, ofd_dev(), ofd_info_init(), ofd_lfsck_out_notify(), ofd_device::ofd_lut, ofd_device::ofd_namespace, ofd_obd(), ofd_device::ofd_osd, ofd_postrecov(), RETURN, target_recovery_init(), and tgt_request_handle().
static int ofd_process_config (const struct lu_env * env, struct lu_device * d, struct lustre_cfg * cfg) [static]
Process various configuration parameters.
This function is used by MGS to process specific configurations and pass them through to the next device in server stack, i.e. the OSD.
Parameters:
[in] env execution environment
[in] d LU device of OFD
[in] cfg parameters to process
Return values:
0 if successful
negative value on error
Definition at line 319 of file ofd_dev.c.
References CDEBUG, CERROR, class_find_old_param(), class_process_proc_param(), CWARN, D_CONFIG, dt_device::dd_lu_dev, ENTRY, lustre_cfg::lcfg_command, LCFG_PARAM, LCFG_SPTLRPC_CONF, lu_device::ld_obd, lu_device::ld_ops, lu_device_operations::ldo_process_config, lustre_cfg_rename(), lustre_cfg_string(), match_symlink_param(), cfg_interop_param::new_param, obd_device::obd_vars, ofd_dev(), ofd_obd(), ofd_device::ofd_osd, cfg_interop_param::old_param, PARAM_OST, and RETURN.
static void ofd_procfs_add_brw_stats_symlink (struct ofd_device * ofd) [static]
Expose OSD statistics to OFD layer.
The osd interfaces to the backend file system exposes useful data such as brw_stats and read or write cache states. This same data needs to be exposed into the obdfilter (ofd) layer to maintain backwards compatibility. This function creates the symlinks in the proc layer to enable this.
Parameters:
[in] ofd OFD device
Definition at line 751 of file ofd_dev.c.
References obd_export::exp_obd, lprocfs_add_symlink(), obd_device::obd_name, obd_device::obd_proc_entry, obd_device::obd_type, ofd_obd(), ofd_device::ofd_osd_exp, and obd_type::typ_name.
Referenced by ofd_init0().
static void ofd_procfs_fini (struct ofd_device * ofd) [static]
Cleanup all procfs entries in OFD.
Parameters:
[in] ofd OFD device
Definition at line 783 of file ofd_dev.c.
References lprocfs_free_obd_stats(), lprocfs_free_per_client_stats(), lprocfs_job_stats_fini(), lprocfs_obd_cleanup(), and ofd_obd().
Referenced by ofd_fini(), and ofd_init0().
static int ofd_procfs_init (struct ofd_device * ofd) [static]
Initialize all needed procfs entries for OFD device.
Parameters:
[in] ofd OFD device
Return values:
0 if successful
negative value on error
Definition at line 681 of file ofd_dev.c.
References CERROR, ENTRY, GOTO, LPROC_OFD_STATS_LAST, lprocfs_add_simple(), lprocfs_alloc_obd_stats(), lprocfs_free_obd_stats(), lprocfs_job_stats_init(), lprocfs_obd_cleanup(), lprocfs_obd_setup(), lprocfs_register(), obd_cleanup(), obd_device::obd_name, obd_device::obd_proc_entry, obd_device::obd_proc_exports_entry, obd_device::obd_stats, obd_device::obd_uses_nid_stats, obd_device::obd_vars, ofd_obd(), ofd_stats_counter_init(), and RETURN.
Referenced by ofd_init0().
static int ofd_prolong_extent_locks (struct tgt_session_info * tsi, __u64 start, __u64 end) [static]
Prolong lock timeout for the given extent.
This function finds all locks related with incoming request and prolongs their timeout.
If a client is holding a lock for a long time while it sends read or write RPCs to the OST for the object under this lock, then we don't want the OST to evict the client. Otherwise, if the network or disk is very busy then the client may not be able to make any progress to clear out dirty pages under the lock and the application will fail.
Every time a Bulk Read/Write (BRW) request arrives for the object covered by the lock, extend the timeout on that lock. The RPC should contain a lock handle for the lock it is using, but this isn't handled correctly by all client versions, and the request may cover multiple locks.
Parameters:
[in] tsi target session environment for this request
[in] start start of extent
[in] end end of extent
Return values:
number of prolonged locks
Definition at line 2344 of file ofd_dev.c.
References cfs_time_current(), ENTRY, obd_export::exp_bl_list, obd_export::exp_bl_list_lock, ldlm_lock::l_exp_list, ldlm_lock::l_export, ldlm_policy_data::l_extent, ldlm_lock::l_flags, ldlm_lock::l_granted_mode, ldlm_lock::l_last_used, ldlm_lock::l_policy_data, ldlm_lock::l_req_mode, ldlm_lock::l_resource, LASSERT, LCK_PW, LDLM_EXTENT, ldlm_extent_contain(), ldlm_extent_overlap(), LDLM_FL_AST_SENT, ldlm_handle2lock(), LDLM_LOCK_PUT, ldlm_res_eq(), list_for_each_entry, ldlm_resource::lr_name, ldlm_resource::lr_type, obdo::o_handle, obdo::o_valid, ost_body::oa, OBD_MD_FLHANDLE, ofd_prolong_one_lock(), RETURN, ldlm_extent::start, tgt_session_info::tsi_exp, tgt_session_info::tsi_ost_body, and tgt_session_info::tsi_resid.
Referenced by ofd_punch_hpreq_check(), and ofd_rw_hpreq_check().
static int ofd_prolong_one_lock (struct tgt_session_info * tsi, struct ldlm_lock * lock, struct ldlm_extent * extent) [static]
Prolong single lock timeout.
This is supplemental function to the ofd_prolong_locks(). It prolongs a single lock.
Parameters:
[in] tsi target session environment for this request
[in] lock LDLM lock to prolong
[in] extent related extent
[in] timeout timeout value to add
Return values:
0 if lock is not suitable for prolongation
1 if lock was prolonged successfully
Definition at line 2292 of file ofd_dev.c.
References ldlm_extent::end, ldlm_lock::l_flags, LDLM_DEBUG, LDLM_FL_AST_SENT, LDLM_FL_DESTROYED, ldlm_refresh_waiting_lock(), LPU64, prolong_timeout(), ldlm_extent::start, tgt_ses_req(), and timeout.
Referenced by ofd_prolong_extent_locks().
static int ofd_punch_hdl (struct tgt_session_info * tsi) [static]
OFD request handler for OST_PUNCH RPC.
This is part of request processing. Validate request fields, punch (truncate) the given OFD object and pack reply.
Parameters:
[in] tsi target session environment for this request
Return values:
0 if successful
negative value on error
Definition at line 2007 of file ofd_dev.c.
References __u64, CDEBUG, CLASSERT, D_INODE, DFID, end, ENTRY, err_serious(), EXIT, ofd_thread_info::fti_attr, ofd_thread_info::fti_mds_fid, GOTO, la_from_obdo(), LA_SIZE, lu_attr::la_size, lu_attr::la_valid, LCK_PW, LDLM_EXTENT, LDLM_FL_AST_DISCARD_DATA, ldlm_res_lvbo_update(), ldlm_resource_get(), ldlm_resource_putref(), LPD64, LPROC_OFD_STATS_PUNCH, LPX64, lu_target::lut_obd, obdo::o_blocks, obdo::o_flags, obdo::o_oi, obdo::o_size, obdo::o_valid, ost_body::oa, OBD_CONNECT_TRUNCLOCK, OBD_FL_SRVLOCK, OBD_MD_FLATIME, OBD_MD_FLBLOCKS, OBD_MD_FLCTIME, OBD_MD_FLFID, OBD_MD_FLFLAGS, OBD_MD_FLID, OBD_MD_FLMTIME, OBD_MD_FLSIZE, obd_device::obd_namespace, OBD_OBJECT_EOF, ofd_counter_incr(), ofd_exp(), ofd_object_find_exists(), ofd_object_punch(), ofd_object_put(), ofd_prepare_fidea(), OST_CONNECT_SUPPORTED, PFID, req_capsule_server_get(), RETURN, RMF_OST_BODY, start, tgt_extent_lock(), tgt_extent_unlock(), tsi2ofd_info(), tgt_session_info::tsi_env, tgt_session_info::tsi_exp, tgt_session_info::tsi_fid, tgt_session_info::tsi_jobid, tgt_session_info::tsi_ost_body, tgt_session_info::tsi_pill, tgt_session_info::tsi_resid, and tgt_session_info::tsi_tgt.
static int ofd_punch_hpreq_check (struct ptlrpc_request * req) [static]
Implementation of ptlrpc_hpreq_ops::hpreq_lock_check for OST_PUNCH request.
High-priority queue request check for whether the given punch request (req) is blocking an LDLM lock cancel.
Parameters:
[in] req the incoming request
Return values:
1 if req is blocking an LDLM lock cancel
0 if it is not
Definition at line 2572 of file ofd_dev.c.
References CDEBUG, D_DLMTRACE, ENTRY, LASSERT, LPU64, lu_context_key_get(), ldlm_res_id::name, obdo::o_blocks, obdo::o_flags, obdo::o_size, obdo::o_valid, ost_body::oa, OBD_FL_SRVLOCK, OBD_MD_FLFLAGS, ofd_prolong_extent_locks(), RETURN, tgt_name(), tgt_session_key, tgt_session_info::tsi_ost_body, tgt_session_info::tsi_resid, and tgt_session_info::tsi_tgt.
Referenced by ofd_punch_hpreq_fini().
static void ofd_punch_hpreq_fini (struct ptlrpc_request * req) [static]
Implementation of ptlrpc_hpreq_ops::hpreq_lock_fini for OST_PUNCH request.
Called after the request has been handled. It refreshes lock timeout again so that client has more time to send lock cancel RPC.
Parameters:
[in] req request which is being processed.
Definition at line 2610 of file ofd_dev.c.
References ofd_punch_hpreq_check().
static int ofd_punch_hpreq_lock_match (struct ptlrpc_request * req, struct ldlm_lock * lock) [static]
Implementation of ptlrpc_hpreq_ops::hpreq_lock_match for OST_PUNCH request.
This function checks if the given lock is the same by its resname, mode and extent as one taken from the request. It is used to give priority to punch/truncate RPCs that might lead to the fastest release of that lock when a lock is contended.
Parameters:
[in] req ptlrpc_request being processed
[in] lock contended lock to match
Return values:
1 if lock is matched
0 otherwise
Definition at line 2540 of file ofd_dev.c.
References lustre_handle::cookie, portals_handle::h_cookie, ldlm_lock::l_handle, LASSERT, lu_context_key_get(), obdo::o_handle, obdo::o_valid, ost_body::oa, OBD_MD_FLHANDLE, tgt_session_key, and tgt_session_info::tsi_ost_body.
static int ofd_quotactl (struct tgt_session_info * tsi) [static]
OFD request handler for OST_QUOTACTL RPC.
This is part of request processing to validate incoming request fields, get the requested data from OSD and pack reply.
Parameters:
[in] tsi target session environment for this request
Return values:
0 if successful
negative value on error
Definition at line 2210 of file ofd_dev.c.
References ENTRY, err_serious(), LPROC_OFD_STATS_QUOTACTL, lquotactl_slv(), lu_target::lut_bottom, NODEMAP_CLIENT_TO_FS, NODEMAP_GID, nodemap_map_id(), NODEMAP_UID, ofd_counter_incr(), obd_quotactl::qc_id, obd_quotactl::qc_type, req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_OBD_QUOTACTL, swap, tgt_session_info::tsi_env, tgt_session_info::tsi_exp, tgt_session_info::tsi_jobid, tgt_session_info::tsi_pill, and tgt_session_info::tsi_tgt.
static int ofd_recovery_complete (const struct lu_env * env, struct lu_device * dev) [static]
Implementation of lu_device_operations::ldo_recovery_complete.
This method notifies all layers about 'recovery complete' event. That means device is in full state and consistent. An OFD calculates available grant space upon this event.
Parameters:
[in] env execution environment
[in] dev lu_device of OFD device
Return values:
0 if successful
negative value on error
Definition at line 634 of file ofd_dev.c.
References dt_device::dd_lu_dev, dt_device_param::ddp_inodespace, ENTRY, ofd_thread_info::fti_ocd, lu_device::ld_obd, lu_device::ld_ops, lu_device_operations::ldo_recovery_complete, OBD_CONNECT_GRANT, OBD_CONNECT_GRANT_PARAM, obd_device::obd_self_export, obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_grant, ofd_dev(), ofd_device::ofd_dt_conf, ofd_grant_connect(), ofd_info(), ofd_device::ofd_osd, OST_MAX_PRECREATE, and RETURN.
static int ofd_rw_hpreq_check (struct ptlrpc_request * req) [static]
Implementation of ptlrpc_hpreq_ops::hpreq_lock_check for OFD RW requests.
Check for whether the given PTLRPC request (req) is blocking an LDLM lock cancel.
Parameters:
[in] req the incoming request
Return values:
1 if req is blocking an LDLM lock cancel
0 if it is not
Definition at line 2471 of file ofd_dev.c.
References __u64, CDEBUG, D_DLMTRACE, D_RPCTRACE, DEBUG_REQ, DFID, end, ENTRY, obd_ioobj::ioo_bufcnt, LASSERT, LPU64, lu_context_key_get(), OBD_BRW_SRVLOCK, ofd_prolong_extent_locks(), PFID, req_capsule_client_get(), RETURN, RMF_NIOBUF_REMOTE, RMF_OBD_IOOBJ, niobuf_remote::rnb_flags, niobuf_remote::rnb_len, niobuf_remote::rnb_offset, ptlrpc_request::rq_pill, start, tgt_name(), tgt_session_key, tgt_session_info::tsi_fid, and tgt_session_info::tsi_tgt.
Referenced by ofd_rw_hpreq_fini().
static void ofd_rw_hpreq_fini (struct ptlrpc_request * req) [static]
Implementation of ptlrpc_hpreq_ops::hpreq_lock_fini for OFD RW requests.
Called after the request has been handled. It refreshes lock timeout again so that client has more time to send lock cancel RPC.
Parameters:
[in] req request which is being processed.
Definition at line 2521 of file ofd_dev.c.
References ofd_rw_hpreq_check().
static int ofd_rw_hpreq_lock_match (struct ptlrpc_request * req, struct ldlm_lock * lock) [static]
Implementation of ptlrpc_hpreq_ops::hpreq_lock_match for OFD RW requests.
Determine if lock and the lock from request req are equivalent by comparing their resource names, modes, and extents.
It is used to give priority to read and write RPCs being done under this lock so that the client can drop the contended lock more quickly and let other clients use it. This improves overall performance in the case where the first client gets a very large lock extent that prevents other clients from submitting their writes.
Parameters:
[in] req ptlrpc_request being processed
[in] lock contended lock to match
Return values:
1 if lock is matched
0 otherwise
Definition at line 2422 of file ofd_dev.c.
References ldlm_extent::end, ENTRY, obd_ioobj::ioo_bufcnt, obd_ioobj::ioo_oid, ldlm_policy_data::l_extent, ldlm_lock::l_granted_mode, ldlm_lock::l_policy_data, ldlm_lock::l_resource, LASSERT, LCK_PR, LCK_PW, ldlm_extent_overlap(), ldlm_resource::lr_name, lustre_msg_get_opc(), mode, OST_READ, ostid_res_name_eq(), req_capsule_client_get(), RETURN, RMF_NIOBUF_REMOTE, RMF_OBD_IOOBJ, niobuf_remote::rnb_len, niobuf_remote::rnb_offset, ptlrpc_request::rq_pill, ptlrpc_request::rq_reqmsg, and ldlm_extent::start.
static int ofd_set_info_hdl (struct tgt_session_info * tsi) [static]
OFD request handler for OST_SET_INFO RPC.
This is OFD-specific part of request handling
Parameters:
[in] tsi target session environment for this request
Return values:
0 if successful
negative value on error
handle grant shrink, similar to a read request
Definition at line 897 of file ofd_dev.c.
References CERROR, D_HA, DEBUG_REQ, ENTRY, err_serious(), obd_export::exp_obd, KEY_EVICT_BY_NID, KEY_GRANT_SHRINK, KEY_IS, KEY_SPTLRPC_CONF, LPROC_OFD_STATS_SET_INFO, obd_export_evict_by_nid(), ofd_counter_incr(), ofd_grant_prepare_read(), RCL_CLIENT, req_capsule_client_get(), req_capsule_extend(), req_capsule_get_size(), req_capsule_server_get(), req_capsule_server_pack(), RETURN, RMF_OST_BODY, RMF_SETINFO_KEY, RMF_SETINFO_VAL, RQF_OST_SET_GRANT_INFO, tgt_adapt_sptlrpc_conf(), tgt_name(), tgt_ses_req(), tgt_session_info::tsi_env, tgt_session_info::tsi_exp, tgt_session_info::tsi_jobid, tgt_session_info::tsi_pill, and tgt_session_info::tsi_tgt.
static int ofd_setattr_hdl (struct tgt_session_info * tsi) [static]
OFD request handler for OST_SETATTR RPC.
This is OFD-specific part of request handling. It finds the OFD object by its FID, sets attributes from request and packs result to the reply.
Parameters:
[in] tsi target session environment for this request
Return values:
0 if successful
negative value on error
Definition at line 1363 of file ofd_dev.c.
References CERROR, DFID, ENTRY, EXIT, ofd_thread_info::fti_attr, ofd_thread_info::fti_mds_fid, GOTO, la_from_obdo(), LA_GID, LA_TYPE, LA_UID, lu_attr::la_valid, LASSERT, LDLM_EXTENT, ldlm_res_lvbo_update(), ldlm_resource_get(), ldlm_resource_putref(), LPROC_OFD_STATS_SETATTR, obdo::o_oi, obdo::o_parent_oid, obdo::o_parent_seq, obdo::o_size, obdo::o_valid, ost_body::oa, obd_export_nid2str(), OBD_MD_FLFID, OBD_MD_FLGROUP, OBD_MD_FLID, OBD_MD_FLSIZE, OBD_OBJECT_EOF, obdo_from_la(), ofd_attr_set(), ofd_counter_incr(), ofd_exp(), ofd_name(), ofd_device::ofd_namespace, ofd_object_find_exists(), ofd_object_put(), ofd_prepare_fidea(), OFD_VALID_FLAGS, PFID, req_capsule_server_get(), RETURN, RMF_OST_BODY, tgt_drop_id(), tsi2ofd_info(), tgt_session_info::tsi_env, tgt_session_info::tsi_exp, tgt_session_info::tsi_fid, tgt_session_info::tsi_jobid, tgt_session_info::tsi_ost_body, tgt_session_info::tsi_pill, and tgt_session_info::tsi_resid.
static void ofd_stack_fini (const struct lu_env * env, struct ofd_device * m, struct lu_device * top) [static]
Finalize the device stack OFD-OSD.
This function cleans OFD-OSD device stack and disconnects OFD from the OSD.
Parameters:
[in] env execution environment
[in] m OFD device
[in] top top device of stack
Return values:
0 if successful
negative value on error
Definition at line 220 of file ofd_dev.c.
References cfs_hash_is_empty(), D_ERROR, ENTRY, EXIT, LASSERT, LCFG_CLEANUP, lu_device::ld_ops, lu_device::ld_site, lu_device_operations::ldo_process_config, LIBCFS_DEBUG_MSG_DATA_DECL, lu_site::ls_obj_hash, lu_cdebug_printer(), lu_site_print(), lu_site_purge(), lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_free(), lustre_cfg_new(), obd_disconnect(), obd_device::obd_fail, obd_device::obd_force, obd_device::obd_name, ofd_obd(), ofd_device::ofd_osd_exp, and RETURN_EXIT.
Referenced by ofd_fini(), and ofd_init0().
static int ofd_stack_init (const struct lu_env * env, struct ofd_device * m, struct lustre_cfg * cfg) [static]
Initialize stack of devices.
This function initializes OFD-OSD device stack to serve OST requests
Parameters:
[in] env execution environment
[in] m OFD device
[in] cfg Lustre config for this server
Return values:
0 if successful
negative value on error
Definition at line 163 of file ofd_dev.c.
References CERROR, ENTRY, obd_export::exp_obd, ofd_thread_info::fti_u, LASSERT, lustre_mount_data::lmd_flags, LMD_FLG_SKIP_LFSCK, lustre_mount_info::lmi_sb, lu2dt_dev(), lustre_cfg_string(), MTI_NAME_MAXLEN, ofd_thread_info::name, OBD_ALLOC, OBD_FREE, obd_device::obd_lu_dev, ofd_connect_to_next(), ofd_info(), ofd_device::ofd_osd, ofd_device::ofd_osd_exp, ofd_device::ofd_skip_lfsck, RETURN, and server_get_mount().
Referenced by ofd_init0().
static int ofd_statfs_hdl (struct tgt_session_info * tsi) [static]
OFD request handler for OST_STATFS RPC.
This function gets statfs data from storage as part of request processing.
Parameters:
[in] tsi target session environment for this request
Return values:
0 if successful
negative value on error
Definition at line 1913 of file ofd_dev.c.
References CERROR, cfs_time_shift_64(), ENTRY, LPROC_OFD_STATS_STATFS, OBD_FAIL_CHECK, OBD_FAIL_OST_STATFS_EINPROGRESS, OBD_STATFS_CACHE_SECONDS, ofd_counter_incr(), ofd_statfs(), req_capsule_server_get(), RETURN, RMF_OBD_STATFS, tgt_name(), tgt_session_info::tsi_env, tgt_session_info::tsi_exp, tgt_session_info::tsi_jobid, tgt_session_info::tsi_pill, and tgt_session_info::tsi_tgt.
static int ofd_sync_hdl (struct tgt_session_info * tsi) [static]
OFD request handler for OST_SYNC RPC.
Sync object data or all filesystem data to the disk and pack the result in reply.
Parameters:
[in] tsi target session environment for this request
Return values:
0 if successful
negative value on error
Definition at line 1948 of file ofd_dev.c.
References ENTRY, EXIT, fid_is_zero(), ofd_thread_info::fti_attr, GOTO, LPROC_OFD_STATS_SYNC, obdo::o_blocks, obdo::o_oi, obdo::o_size, obdo::o_valid, ost_body::oa, OBD_MD_FLGROUP, OBD_MD_FLID, obdo_from_la(), ofd_attr_get(), ofd_counter_incr(), ofd_exp(), ofd_object_child(), ofd_object_find_exists(), ofd_object_put(), OFD_VALID_FLAGS, req_capsule_server_get(), RETURN, RMF_OST_BODY, tgt_sync(), tsi2ofd_info(), tgt_session_info::tsi_env, tgt_session_info::tsi_exp, tgt_session_info::tsi_fid, tgt_session_info::tsi_jobid, tgt_session_info::tsi_ost_body, tgt_session_info::tsi_pill, and tgt_session_info::tsi_tgt.
static int prolong_timeout (struct ptlrpc_request * req, struct ldlm_lock * lock) [inline, static]
Calculate the amount of time for lock prolongation.
This is helper for ofd_prolong_extent_locks() function to get the timeout extra time.
Parameters:
[in] req current request
Return values:
amount of time to extend the timeout with
Definition at line 2264 of file ofd_dev.c.
References at_est2timeout(), at_get(), AT_OFF, obd_timeout, and ptlrpc_service_part::scp_at_estimate.
Referenced by ofd_prolong_one_lock().
static void unlock_zero_regions (struct ldlm_namespace * ns, struct list_head * locked) [static]
Unlock all previously locked sparse areas for given resource.
This function goes through list of locked regions, unlocking and freeing them one-by-one.
Parameters:
[in] ns LDLM namespace
[in] locked list head of regions list
Definition at line 1106 of file ofd_dev.c.
References CDEBUG, D_OTHER, LCK_PR, locked_region::lh, locked_region::list, list, list_del(), list_for_each_entry_safe, OBD_FREE_PTR, and tgt_extent_unlock().
Referenced by ofd_get_info_hdl().
Variable Documentation
struct lu_kmem_descr ofd_caches[] [static]
Initial value:
 {
        {
                .ckd_cache = &ofd_object_kmem,
                .ckd_name  = "ofd_obj",
                .ckd_size  = sizeof(struct ofd_object)
        },
        {
                .ckd_cache = NULL
        }
}
Definition at line 85 of file ofd_dev.c.
struct tgt_opc_slice ofd_common_slice[] [static]
Definition at line 2721 of file ofd_dev.c.
struct lu_device_type ofd_device_type [static]
Initial value:
 {
        .ldt_tags       = LU_DEVICE_DT,
        .ldt_name       = LUSTRE_OST_NAME,
        .ldt_ops        = &ofd_device_type_ops,
        .ldt_ctx_tags   = LCT_DT_THREAD
}
Definition at line 3107 of file ofd_dev.c.
struct lu_device_type_operations ofd_device_type_ops [static]
Initial value:
 {
        .ldto_init              = ofd_type_init,
        .ldto_fini              = ofd_type_fini,
        .ldto_start             = ofd_type_start,
        .ldto_stop              = ofd_type_stop,
        .ldto_device_alloc      = ofd_device_alloc,
        .ldto_device_free       = ofd_device_free,
        .ldto_device_fini       = ofd_device_fini
}
Definition at line 3095 of file ofd_dev.c.
struct ptlrpc_hpreq_ops ofd_hpreq_punch [static]
Initial value:
 {
        .hpreq_lock_match       = ofd_punch_hpreq_lock_match,
        .hpreq_check            = ofd_punch_hpreq_check,
        .hpreq_fini             = ofd_punch_hpreq_fini
}
Definition at line 2621 of file ofd_dev.c.
struct ptlrpc_hpreq_ops ofd_hpreq_rw [static]
Initial value:
 {
        .hpreq_lock_match       = ofd_rw_hpreq_lock_match,
        .hpreq_check            = ofd_rw_hpreq_check,
        .hpreq_fini             = ofd_rw_hpreq_fini
}
Definition at line 2615 of file ofd_dev.c.
struct cfg_interop_param ofd_interop_param[] [static]
Initial value:
 {
        { "ost.quota_type",     NULL },
        { NULL }
}
Definition at line 259 of file ofd_dev.c.
struct lu_device_operations ofd_lu_ops [static]
Initial value:
 {
        .ldo_object_alloc       = ofd_object_alloc,
        .ldo_process_config     = ofd_process_config,
        .ldo_recovery_complete  = ofd_recovery_complete,
        .ldo_prepare            = ofd_prepare,
}
lu_device_operations matrix for OFD device.
Definition at line 664 of file ofd_dev.c.
struct lu_object_operations ofd_obj_ops [static]
Initial value:
 {
        .loo_object_init        = ofd_object_init,
        .loo_object_free        = ofd_object_free,
        .loo_object_print       = ofd_object_print
}
Definition at line 471 of file ofd_dev.c.
struct kmem_cache* ofd_object_kmem [static]
Definition at line 83 of file ofd_dev.c.
Referenced by ofd_object_alloc(), and ofd_object_free().
struct tgt_handler ofd_tgt_handlers[] [static]
Table of OFD-specific request handlers.
This table contains all opcodes accepted by OFD and specifies handlers for them. The tgt_request_handler() uses such table from each target to process incoming requests.
Definition at line 2688 of file ofd_dev.c.
struct lu_context_key ofd_thread_key
Initial value:
 {
        .lct_tags = LCT_DT_THREAD,
        .lct_init = ofd_key_init,
        .lct_fini = ofd_key_fini,
        .lct_exit = ofd_key_exit
}
Definition at line 2792 of file ofd_dev.c.
Referenced by ofd_info().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.