Lustre: lustre/ofd/ofd_fmd.c File Reference
lustre/ofd/ofd_fmd.c File Reference
#include "ofd_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_FILTER
Functions
static void ofd_fmd_put_nolock (struct obd_export *exp, struct ofd_mod_data *fmd)
Drop FMD reference and free it if reference drops to zero.
void ofd_fmd_put (struct obd_export *exp, struct ofd_mod_data *fmd)
Wrapper to drop FMD reference with fed_lock held.
static void ofd_fmd_expire_nolock (struct obd_export *exp, struct ofd_mod_data *keep)
Expire FMD entries.
void ofd_fmd_expire (struct obd_export *exp)
Expire FMD entries.
static struct ofd_mod_data * ofd_fmd_find_nolock (struct obd_export *exp, const struct lu_fid *fid)
Find FMD by specified FID.
struct ofd_mod_data * ofd_fmd_find (struct obd_export *exp, const struct lu_fid *fid)
Find FMD by specified FID with locking.
struct ofd_mod_data * ofd_fmd_get (struct obd_export *exp, const struct lu_fid *fid)
Find FMD by FID or create a new one if none is found.
void ofd_fmd_cleanup (struct obd_export *exp)
Remove all entries from FMD list.
int ofd_fmd_init (void)
Initialize FMD subsystem.
void ofd_fmd_exit (void)
Stop FMD subsystem.
Variables
static struct kmem_cache * ll_fmd_cachep
Define Documentation
#define DEBUG_SUBSYSTEM S_FILTER
Definition at line 49 of file ofd_fmd.c.
Function Documentation
void ofd_fmd_cleanup (struct obd_export * exp)
Remove all entries from FMD list.
Cleanup function to free all FMD enries on the given export.
Parameters:
[in] exp OBD export
Definition at line 300 of file ofd_fmd.c.
References CDEBUG, D_INFO, filter_export_data::fed_lock, filter_export_data::fed_mod_list, ofd_mod_data::fmd_list, ofd_mod_data::fmd_refcount, list_del_init(), list_for_each_entry_safe, and ofd_fmd_put_nolock().
Referenced by ofd_destroy_export().
void ofd_fmd_exit (void)
Stop FMD subsystem.
This function is called upon OFD cleanup and destroy memory used by FMD entries.
Definition at line 340 of file ofd_fmd.c.
References ll_fmd_cachep.
Referenced by ofd_exit().
void ofd_fmd_expire (struct obd_export * exp)
Expire FMD entries.
This is a wrapper to call ofd_fmd_expire_nolock() with the required lock.
Parameters:
[in] exp OBD export
Definition at line 140 of file ofd_fmd.c.
References filter_export_data::fed_lock, and ofd_fmd_expire_nolock().
Referenced by ofd_ping().
static void ofd_fmd_expire_nolock (struct obd_export * exp, struct ofd_mod_data * keep) [static]
Expire FMD entries.
Expire entries from the FMD list if there are too many of them or they are too old.
This function must be called with fed_lock held.
The keep FMD is not to be expired in any case. This parameter is used by ofd_fmd_find_nolock() to prohibit a FMD that was just found from expiring.
Parameters:
[in] exp OBD export
[in] keep FMD to keep always
Definition at line 111 of file ofd_fmd.c.
References cfs_time_before(), cfs_time_current(), filter_export_data::fed_mod_count, filter_export_data::fed_mod_list, ofd_mod_data::fmd_expire, ofd_mod_data::fmd_list, list_del_init(), list_for_each_entry_safe, now(), ofd_exp(), ofd_device::ofd_fmd_max_num, and ofd_fmd_put_nolock().
Referenced by ofd_fmd_expire(), and ofd_fmd_find_nolock().
struct ofd_mod_data* ofd_fmd_find (struct obd_export * exp, const struct lu_fid * fid) [read]
Find FMD by specified FID with locking.
Wrapper to the ofd_fmd_find_nolock() with correct locks.
Parameters:
[in] exp OBD export
[in] fid FID of FMD to find
Return values:
struct ofd_mod_data found by FID
NULL indicates FMD is not found
Definition at line 199 of file ofd_fmd.c.
References filter_export_data::fed_lock, ofd_mod_data::fmd_refcount, and ofd_fmd_find_nolock().
Referenced by ofd_commitrw().
static struct ofd_mod_data* ofd_fmd_find_nolock (struct obd_export * exp, const struct lu_fid * fid) [static, read]
Find FMD by specified FID.
Function finds FMD entry by FID in the filter_export_data::fed_fmd_list.
Caller must hold filter_export_data::fed_lock and take FMD reference.
Parameters:
[in] exp OBD export
[in] fid FID of FMD to find
Return values:
struct ofd_mod_data found by FID
NULL is FMD is not found
Definition at line 162 of file ofd_fmd.c.
References cfs_time_add(), cfs_time_current(), filter_export_data::fed_lock, filter_export_data::fed_mod_list, list_add_tail(), list_del(), list_for_each_entry_reverse, lu_fid_eq(), now(), ofd_exp(), ofd_fmd_expire_nolock(), and ofd_device::ofd_fmd_max_age.
Referenced by ofd_fmd_find(), and ofd_fmd_get().
struct ofd_mod_data* ofd_fmd_get (struct obd_export * exp, const struct lu_fid * fid) [read]
Find FMD by FID or create a new one if none is found.
It is possible for this function to return NULL under memory pressure, or if the passed FID is zero (which will only cause old entries to expire). Currently this is not fatal because any FMD state is transient and may also be freed when it gets sufficiently old.
Parameters:
[in] exp OBD export
[in] fid FID of FMD to find
Return values:
struct ofd_mod_data found by FID
NULL indicates FMD is not found
Definition at line 228 of file ofd_fmd.c.
References cfs_time_add(), cfs_time_current(), filter_export_data::fed_lock, filter_export_data::fed_mod_count, filter_export_data::fed_mod_list, ofd_mod_data::fmd_expire, ofd_mod_data::fmd_refcount, list_add_tail(), ll_fmd_cachep, now(), OBD_SLAB_ALLOC_PTR, OBD_SLAB_FREE_PTR, ofd_exp(), ofd_fmd_find_nolock(), and ofd_device::ofd_fmd_max_age.
Referenced by ofd_attr_set(), and ofd_object_punch().
int ofd_fmd_init (void)
Initialize FMD subsystem.
This function is called upon OFD setup and initialize memory to be used by FMD entries.
Definition at line 323 of file ofd_fmd.c.
References ll_fmd_cachep.
Referenced by ofd_init().
void ofd_fmd_put (struct obd_export * exp, struct ofd_mod_data * fmd)
Wrapper to drop FMD reference with fed_lock held.
Parameters:
[in] exp OBD export
[in] fmd FMD to put
Definition at line 84 of file ofd_fmd.c.
References filter_export_data::fed_lock, and ofd_fmd_put_nolock().
Referenced by ofd_attr_set(), ofd_commitrw(), and ofd_object_punch().
static void ofd_fmd_put_nolock (struct obd_export * exp, struct ofd_mod_data * fmd) [inline, static]
Drop FMD reference and free it if reference drops to zero.
Must be called with fed_lock held.
Parameters:
[in] exp OBD export
[in] fmd FMD to put
Definition at line 63 of file ofd_fmd.c.
References filter_export_data::fed_lock, filter_export_data::fed_mod_count, ofd_mod_data::fmd_list, ofd_mod_data::fmd_refcount, list_del(), ll_fmd_cachep, and OBD_SLAB_FREE.
Referenced by ofd_fmd_cleanup(), ofd_fmd_expire_nolock(), and ofd_fmd_put().
Variable Documentation
struct kmem_cache* ll_fmd_cachep [static]
Definition at line 53 of file ofd_fmd.c.
Referenced by ofd_fmd_exit(), ofd_fmd_get(), ofd_fmd_init(), and ofd_fmd_put_nolock().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.