Lustre: lustre/ofd/ofd_trans.c File Reference
lustre/ofd/ofd_trans.c File Reference
#include "ofd_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_FILTER
Functions
struct thandle * ofd_trans_create (const struct lu_env *env, struct ofd_device *ofd)
Create new transaction in OFD.
int ofd_trans_start (const struct lu_env *env, struct ofd_device *ofd, struct ofd_object *obj, struct thandle *th)
Start transaction in OFD.
void ofd_trans_stop (const struct lu_env *env, struct ofd_device *ofd, struct thandle *th, int rc)
Stop transaction in OFD.
Define Documentation
#define DEBUG_SUBSYSTEM S_FILTER
Definition at line 41 of file ofd_trans.c.
Function Documentation
struct thandle* ofd_trans_create (const struct lu_env * env, struct ofd_device * ofd) [read]
Create new transaction in OFD.
This function creates a transaction with dt_trans_create() and makes it synchronous if required by the export state.
Parameters:
[in] env execution environment
[in] ofd OFD device
Return values:
struct thandle if transaction was created successfully
ERR_PTR on negative value in case of error
Definition at line 57 of file ofd_trans.c.
References dt_trans_create(), obd_export::exp_need_sync, ofd_thread_info::fti_exp, LASSERT, ofd_info(), ofd_device::ofd_osd, and thandle::th_sync.
Referenced by ofd_attr_set(), ofd_commitrw_write(), ofd_object_destroy(), ofd_object_punch(), ofd_precreate_objects(), and ofd_write_attr_set().
int ofd_trans_start (const struct lu_env * env, struct ofd_device * ofd, struct ofd_object * obj, struct thandle * th)
Start transaction in OFD.
This function updates the given obj object version and calls dt_trans_start().
Parameters:
[in] env execution environment
[in] ofd OFD device
[in] obj OFD object affected by this transaction
[in] th transaction handle
Return values:
0 if successful
negative value in case of error
Definition at line 89 of file ofd_trans.c.
References dt_trans_start(), ofd_object_child(), ofd_device::ofd_osd, and tgt_vbr_obj_set().
Referenced by ofd_attr_set(), ofd_commitrw_write(), ofd_object_destroy(), and ofd_object_punch().
void ofd_trans_stop (const struct lu_env * env, struct ofd_device * ofd, struct thandle * th, int rc)
Stop transaction in OFD.
This function fills thandle::th_result with result of whole operation and calls dt_trans_stop().
Parameters:
[in] env execution environment
[in] ofd OFD device
[in] th transaction handle
[in] rc result code of whole operation
Definition at line 110 of file ofd_trans.c.
References dt_trans_stop(), ofd_device::ofd_osd, and thandle::th_result.
Referenced by ofd_attr_set(), ofd_commitrw_write(), ofd_object_destroy(), ofd_object_punch(), and ofd_precreate_objects().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.