Lustre: lustre/ofd/ofd_dlm.c File Reference
lustre/ofd/ofd_dlm.c File Reference
#include "ofd_internal.h"
Data Structures
struct ofd_intent_args
Defines
#define DEBUG_SUBSYSTEM S_FILTER
Functions
static enum interval_iter ofd_intent_cb (struct interval_node *n, void *args)
OFD interval callback.
int ofd_intent_policy (struct ldlm_namespace *ns, struct ldlm_lock **lockp, void *req_cookie, enum ldlm_mode mode, __u64 flags, void *data)
OFD lock intent policy.
Define Documentation
#define DEBUG_SUBSYSTEM S_FILTER
Definition at line 43 of file ofd_dlm.c.
Function Documentation
static enum interval_iter ofd_intent_cb (struct interval_node * n, void * args) [static]
OFD interval callback.
The interval_callback_t is part of interval_iterate_reverse() and is called for each interval in tree. The OFD interval callback searches for locks covering extents beyond the given args->size. This is used to decide if LVB data is outdated.
Parameters:
[in] n interval node
[in] args intent arguments
Return values:
INTERVAL_ITER_STOP if the interval is lower than file size, caller stops execution
INTERVAL_ITER_CONT if callback finished successfully and caller may continue execution
Definition at line 69 of file ofd_dlm.c.
References __u64, obd_export::exp_libclient, interval_high(), INTERVAL_ITER_CONT, INTERVAL_ITER_STOP, ldlm_lock::l_export, ldlm_policy_data::l_extent, ldlm_lock::l_policy_data, ldlm_lock::l_sl_policy, LDLM_LOCK_GET, LDLM_LOCK_RELEASE, ldlm_interval::li_group, ofd_intent_args::liblustre, list_for_each_entry, ofd_intent_args::size, size, ldlm_extent::start, and ofd_intent_args::victim.
Referenced by ofd_intent_policy().
int ofd_intent_policy (struct ldlm_namespace * ns, struct ldlm_lock ** lockp, void * req_cookie, enum ldlm_mode mode, __u64 flags, void * data)
OFD lock intent policy.
This defines ldlm_namespace::ns_policy interface for OFD. Intent policy is called when lock has an intent, for OFD that means glimpse lock and policy fills Lock Value Block (LVB).
If already granted lock is found it will be placed in lockp and returned back to caller function.
Parameters:
[in] ns namespace
[in,out] lockp pointer to the lock
[in] req_cookie incoming request
[in] mode LDLM mode
[in] flags LDLM flags
[in] data opaque data, not used in OFD policy
Return values:
ELDLM_LOCK_REPLACED if already granted lock was found and placed in lockp
ELDLM_LOCK_ABORTED in other cases except error
negative value on error
Definition at line 129 of file ofd_dlm.c.
References __u64, check_res_locked(), DLM_LOCKREPLY_OFF, DLM_REPLY_REC_OFF, ELDLM_LOCK_ABORTED, ELDLM_LOCK_REPLACED, ENTRY, obd_export::exp_libclient, ldlm_glimpse_work::gl_desc, ldlm_glimpse_work::gl_flags, ldlm_glimpse_work::gl_list, ldlm_glimpse_work::gl_lock, INIT_LIST_HEAD, interval_iterate_reverse(), ldlm_lock::l_export, ldlm_lock::l_lvb_type, ldlm_lock::l_resource, LASSERT, LCK_MODE_NUM, LCK_PR, LDLM_FL_BLOCK_NOWAIT, LDLM_FL_RESENT, LDLM_GL_WORK_NOFREE, LDLM_ITER_CONTINUE, LDLM_LOCK_GET, LDLM_LOCK_RELEASE, ldlm_res_lvbo_update(), ldlm_res_to_ns(), ldlm_resource_unlink_lock(), ofd_intent_args::liblustre, list_add_tail(), list_empty(), ldlm_interval_tree::lit_mode, ldlm_interval_tree::lit_root, ldlm_reply::lock_policy_res1, lock_res(), ldlm_resource::lr_itree, ldlm_resource::lr_lvb_data, lustre_msg_buf(), lustre_pack_reply(), ost_lvb::lvb_size, LVB_T_OST, MSG_PTLRPC_BODY_OFF, OBD_FAIL_CHECK, OBD_FAIL_LDLM_AGL_DELAY, OBD_FAIL_LDLM_AGL_NOLOCK, OBD_FAIL_LDLM_GLIMPSE, OBD_FAIL_TIMEOUT, ofd_intent_cb(), ptlrpc_body, ptlrpc_status_hton(), RETURN, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_status, ofd_intent_args::size, unlock_res(), and ofd_intent_args::victim.
Referenced by ofd_init0().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.