Lustre: lustre/ofd/ofd_obd.c File Reference
lustre/ofd/ofd_obd.c File Reference
#include <lustre/lustre_idl.h>
#include "ofd_internal.h"
#include <obd_cksum.h>
#include <lustre_ioctl.h>
#include <lustre_quota.h>
#include <lustre_lfsck.h>
#include <lustre_nodemap.h>
Defines
#define DEBUG_SUBSYSTEM S_FILTER
Functions
static int ofd_export_stats_init (struct ofd_device *ofd, struct obd_export *exp, lnet_nid_t *client_nid)
Initialize OFD per-export statistics.
static int ofd_parse_connect_data (const struct lu_env *env, struct obd_export *exp, struct obd_connect_data *data, bool new_connection)
Match client and OST server connection feature flags.
static int ofd_obd_reconnect (const struct lu_env *env, struct obd_export *exp, struct obd_device *obd, struct obd_uuid *cluuid, struct obd_connect_data *data, void *client_nid)
Re-initialize export upon client reconnection.
static int ofd_obd_connect (const struct lu_env *env, struct obd_export **_exp, struct obd_device *obd, struct obd_uuid *cluuid, struct obd_connect_data *data, void *localdata)
Initialize new client connection.
int ofd_obd_disconnect (struct obd_export *exp)
Disconnect a connected client.
static int ofd_init_export (struct obd_export *exp)
Implementation of obd_ops::o_init_export.
static int ofd_destroy_export (struct obd_export *exp)
Implementation of obd_ops::o_destroy_export.
int ofd_postrecov (const struct lu_env *env, struct ofd_device *ofd)
Notify all devices in server stack about recovery completion.
static int ofd_obd_postrecov (struct obd_device *obd)
Implementation of obd_ops::o_postrecov.
static int ofd_set_info_async (const struct lu_env *env, struct obd_export *exp, __u32 keylen, void *key, __u32 vallen, void *val, struct ptlrpc_request_set *set)
Implementation of obd_ops::o_set_info_async.
static int ofd_get_info (const struct lu_env *env, struct obd_export *exp, __u32 keylen, void *key, __u32 *vallen, void *val)
Implementation of obd_ops::o_get_info.
int ofd_statfs_internal (const struct lu_env *env, struct ofd_device *ofd, struct obd_statfs *osfs, __u64 max_age, int *from_cache)
Get file system statistics of OST server.
int ofd_statfs (const struct lu_env *env, struct obd_export *exp, struct obd_statfs *osfs, __u64 max_age, __u32 flags)
Implementation of obd_ops::o_statfs.
static int ofd_echo_setattr (const struct lu_env *env, struct obd_export *exp, struct obdo *oa)
Implementation of obd_ops::o_setattr.
int ofd_destroy_by_fid (const struct lu_env *env, struct ofd_device *ofd, const struct lu_fid *fid, int orphan)
Destroy OFD object by its FID.
static int ofd_echo_destroy (const struct lu_env *env, struct obd_export *exp, struct obdo *oa)
Implementation of obd_ops::o_destroy.
static int ofd_echo_create (const struct lu_env *env, struct obd_export *exp, struct obdo *oa)
Implementation of obd_ops::o_create.
static int ofd_echo_getattr (const struct lu_env *env, struct obd_export *exp, struct obdo *oa)
Implementation of obd_ops::o_getattr.
static int ofd_ioc_get_obj_version (const struct lu_env *env, struct ofd_device *ofd, void *karg)
Get object version for OBD_IOC_GET_OBJ_VERSION ioctl.
static int ofd_iocontrol (unsigned int cmd, struct obd_export *exp, int len, void *karg, void __user *uarg)
Implementation of obd_ops::o_iocontrol.
static int ofd_precleanup (struct obd_device *obd)
Implementation of obd_ops::o_precleanup.
static int ofd_ping (const struct lu_env *env, struct obd_export *exp)
Implementation of obd_ops::o_ping.
static int ofd_health_check (const struct lu_env *nul, struct obd_device *obd)
Implementation of obd_ops::o_health_check.
Variables
struct obd_ops ofd_obd_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_FILTER
Definition at line 44 of file ofd_obd.c.
Function Documentation
int ofd_destroy_by_fid (const struct lu_env * env, struct ofd_device * ofd, const struct lu_fid * fid, int orphan)
Destroy OFD object by its FID.
Supplemental function to destroy object by FID, it is used by request handler and by ofd_echo_destroy() below to find object by FID, lock it and call ofd_object_destroy() finally.
Parameters:
[in] env execution environment
[in] ofd OFD device
[in] fid FID of object
[in] orphan set if object being destroyed is an orphan
Return values:
0 if successful
negative value on error
Definition at line 984 of file ofd_obd.c.
References __u64, ELDLM_OK, ENTRY, EXIT, ofd_thread_info::fti_resid, ldlm_policy_data::l_extent, LASSERT, LCK_PW, ldlm_blocking_ast(), ldlm_cli_enqueue_local(), ldlm_completion_ast(), LDLM_EXTENT, LDLM_FL_AST_DISCARD_DATA, ldlm_lock_decref(), LVB_T_NONE, OBD_OBJECT_EOF, ofd_info(), ofd_device::ofd_namespace, ofd_object_destroy(), ofd_object_find_exists(), ofd_object_put(), ost_fid_build_resid(), and RETURN.
Referenced by ofd_destroy_hdl(), ofd_echo_destroy(), and ofd_orphans_destroy().
static int ofd_destroy_export (struct obd_export * exp) [static]
Implementation of obd_ops::o_destroy_export.
This function is called from class_export_destroy() to cleanup the OFD-specific data for export being destroyed.
Parameters:
[in] exp OBD export
Return values:
0 if successful
negative value on error
Definition at line 492 of file ofd_obd.c.
References CERROR, obd_export::exp_client_uuid, exp_connect_flags(), obd_export::exp_flags, obd_export::exp_obd, LASSERT, ldlm_destroy_export(), list_empty(), OBD_CONNECT_GRANT, obd_device::obd_name, OBD_OPT_FORCE, obd_device::obd_uuid, obd_uuid_equals(), ofd_exp(), ofd_fmd_cleanup(), ofd_grant_discard(), ofd_grant_sanity_check(), ofd_device::ofd_tot_granted_clients, tgt_client_free(), unlikely, and obd_uuid::uuid.
static int ofd_echo_create (const struct lu_env * env, struct obd_export * exp, struct obdo * oa) [static]
Implementation of obd_ops::o_create.
This function is only used by ECHO client when it is run on top of OFD and just creates an object.
See also:
ofd_create_hdl() for request handler function.
Parameters:
[in] env execution environment
[in] exp OBD export of OFD device
[in] oa obdo structure with FID sequence to use
Note: this is OBD API method which is common API for server OBDs and client OBDs. Thus some parameters used in client OBDs may not be used on server OBDs and vice versa.
Return values:
0 if successful
negative value on error
Definition at line 1084 of file ofd_obd.c.
References CDEBUG, CERROR, D_HA, D_INFO, DOSTID, ENTRY, FID_SEQ_ECHO, GOTO, LASSERT, LPX64, obdo::o_oi, obdo::o_valid, OBD_MD_FLGROUP, OBD_MD_FLID, ofd_exp(), ofd_grant_commit(), ofd_grant_create(), ofd_info_init(), ofd_device::ofd_lastid_rebuilding, ofd_device::ofd_lastid_rwsem, ofd_name(), ofd_obd(), ofd_precreate_batch(), ofd_precreate_objects(), ofd_seq_last_oid(), ofd_seq_load(), ofd_seq_put(), ofd_seq::os_create_lock, ostid_seq(), ostid_set_id(), POSTID, RETURN, and unlikely.
static int ofd_echo_destroy (const struct lu_env * env, struct obd_export * exp, struct obdo * oa) [static]
Implementation of obd_ops::o_destroy.
This function is only used by ECHO client when it is run on top of OFD,
See also:
ofd_destroy_hdl() for request handler function.
Parameters:
[in] env execution environment
[in] exp OBD export of OFD device
[in] oa obdo structure with FID
Note: this is OBD API method which is common API for server OBDs and client OBDs. Thus some parameters used in client OBDs may not be used on server OBDs and vice versa.
Return values:
0 if successful
negative value on error
Definition at line 1038 of file ofd_obd.c.
References CDEBUG, CERROR, D_HA, D_INODE, DFID, ENTRY, EXIT, GOTO, obdo::o_oi, ofd_destroy_by_fid(), ofd_exp(), ofd_info_init(), ofd_name(), ost_id::oi_fid, and PFID.
static int ofd_echo_getattr (const struct lu_env * env, struct obd_export * exp, struct obdo * oa) [static]
Implementation of obd_ops::o_getattr.
This function is only used by ECHO client when it is run on top of OFD and returns attributes of object.
See also:
ofd_getattr_hdl() for request handler function.
Parameters:
[in] env execution environment
[in] exp OBD export of OFD device
[in,out] oa contains FID of object to get attributes from and is used to return attributes back
Return values:
0 if successful
negative value on error
Definition at line 1168 of file ofd_obd.c.
References __u64, dt_version_get(), ENTRY, ofd_thread_info::fti_attr, GOTO, LA_GID, LA_UID, LASSERT, obdo::o_data_version, obdo::o_oi, obdo::o_valid, OBD_MD_FLDATAVERSION, OBD_MD_FLID, obdo_from_la(), ofd_attr_get(), ofd_exp(), ofd_info_init(), ofd_object_child(), ofd_object_find_exists(), ofd_object_put(), OFD_VALID_FLAGS, ost_id::oi_fid, and RETURN.
static int ofd_echo_setattr (const struct lu_env * env, struct obd_export * exp, struct obdo * oa) [static]
Implementation of obd_ops::o_setattr.
This function is only used by ECHO client when it is run on top of OFD,
See also:
ofd_setattr_hdl() for request handler function.
Parameters:
[in] env execution environment
[in] exp OBD export of OFD device
[in] oa setattr parameters
Return values:
0 if successful
negative value on error
Definition at line 892 of file ofd_obd.c.
References CERROR, DFID, ENTRY, EXIT, ofd_thread_info::fti_attr, ofd_thread_info::fti_mds_fid, ofd_thread_info::fti_resid, GOTO, la_from_obdo(), LA_TYPE, lu_attr::la_valid, LDLM_EXTENT, ldlm_res_lvbo_update(), ldlm_resource_get(), ldlm_resource_putref(), LPROC_OFD_STATS_SETATTR, obdo::o_oi, obdo::o_parent_oid, obdo::o_parent_seq, obdo::o_valid, obd_export_nid2str(), OBD_MD_FLFID, OBD_MD_FLSIZE, ofd_attr_set(), ofd_counter_incr(), ofd_exp(), ofd_info_init(), ofd_name(), ofd_device::ofd_namespace, ofd_object_find_exists(), ofd_object_put(), ofd_prepare_fidea(), ost_id::oi_fid, ost_fid_build_resid(), and PFID.
static int ofd_export_stats_init (struct ofd_device * ofd, struct obd_export * exp, lnet_nid_t * client_nid) [static]
Initialize OFD per-export statistics.
This function sets up procfs entries for various OFD export counters. These counters are for per-client statistics tracked on the server.
Parameters:
[in] ofd OFD device
[in] exp OBD export
[in] client_nid NID of client
Return values:
0 if successful
negative value on error
Definition at line 67 of file ofd_obd.c.
References ENTRY, obd_export::exp_client_uuid, obd_export::exp_nid_stats, GOTO, LASSERT, LPROC_OFD_STATS_LAST, lprocfs_alloc_stats(), lprocfs_free_stats(), lprocfs_init_ops_stats(), lprocfs_nid_ldlm_stats_init(), lprocfs_register_stats(), LPROCFS_STATS_FLAG_NOPERCPU, nid_stat::nid_proc, nid_stat::nid_stats, obd_device::obd_uses_nid_stats, obd_device::obd_uuid, obd_uuid_equals(), ofd_obd(), ofd_stats_counter_init(), and RETURN.
Referenced by ofd_obd_connect(), and ofd_obd_reconnect().
static int ofd_get_info (const struct lu_env * env, struct obd_export * exp, __u32 keylen, void * key, __u32 * vallen, void * val) [static]
Implementation of obd_ops::o_get_info.
This function is not called from request handler, it is only used by direct call from nrs_orr_range_fill_physical() in ptlrpc, see LU-3239.
See also:
ofd_get_info_hdl() for request handler function.
Parameters:
[in] env execution environment
[in] exp OBD export of OFD device
[in] keylen length of key
[in] key key name
[out] vallen length of key value
[out] val the key value to return
Return values:
0 if successful
negative value on error
Definition at line 651 of file ofd_obd.c.
References CDEBUG, CERROR, D_IOCTL, ENTRY, obd_export::exp_obd, ofd_thread_info::fti_fid, KEY_FIEMAP, KEY_IS, ll_fiemap_info_key::lfik_oa, lr_server_data::lsd_osd_index, lu_target::lut_lsd, obdo::o_oi, ofd_exp(), ofd_fiemap_get(), ofd_info_init(), ofd_device::ofd_lut, ofd_name(), ostid_to_fid(), and RETURN.
static int ofd_health_check (const struct lu_env * nul, struct obd_device * obd) [static]
Implementation of obd_ops::o_health_check.
This function checks the OFD device health - ability to respond on incoming requests. There are two health_check methods:
get statfs from the OSD. It checks just responsiveness of bottom device
do write attempt on bottom device to check it is fully operational and is not stuck. This is expensive method and requires special configuration option --enable-health-write while building Lustre, it is turned off by default.
Parameters:
[in] nul not used
[in] obd OBD device of OFD
Return values:
0 if successful
negative value in case of error
Definition at line 1420 of file ofd_obd.c.
References CDEBUG, D_INFO, dt_declare_record_write(), dt_record_write(), dt_statfs(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), ofd_thread_info::fti_buf, ofd_thread_info::fti_off, ofd_thread_info::fti_u, GOTO, lu_buf::lb_buf, lu_buf::lb_len, LCT_DT_THREAD, lu_env_fini(), lu_env_init(), OBD_ALLOC, OBD_FREE, obd_device::obd_lu_dev, ofd_dev(), ofd_device::ofd_health_check_file, ofd_info_init(), ofd_device::ofd_osd, obd_statfs::os_state, OS_STATE_READONLY, ofd_thread_info::osfs, RETURN, thandle::th_sync, and unlikely.
static int ofd_init_export (struct obd_export * exp) [static]
Implementation of obd_ops::o_init_export.
This function is called from class_new_export() and initializes the OFD-specific data for new export.
Parameters:
[in] exp OBD export
Return values:
0 if successful
negative value on error
Definition at line 456 of file ofd_obd.c.
References CERROR, obd_export::exp_client_uuid, obd_export::exp_connecting, obd_export::exp_lock, obd_export::exp_obd, INIT_LIST_HEAD, ldlm_init_export(), obd_device::obd_name, obd_device::obd_uuid, obd_uuid_equals(), tgt_client_alloc(), and unlikely.
static int ofd_ioc_get_obj_version (const struct lu_env * env, struct ofd_device * ofd, void * karg) [static]
Get object version for OBD_IOC_GET_OBJ_VERSION ioctl.
This is supplemental function for ofd_iocontrol() to return object version for lctl tool.
Parameters:
[in] env execution environment
[in] ofd OFD device
[out] karg ioctl data
Return values:
0 if successful
negative value on error
Definition at line 1220 of file ofd_obd.c.
References __u64, dt_object::do_lu, dt_version_get(), ENTRY, EXIT, fid_is_sane(), GOTO, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_inlbuf2, obd_ioctl_data::ioc_inlbuf3, obd_ioctl_data::ioc_inlbuf4, obd_ioctl_data::ioc_inllen1, obd_ioctl_data::ioc_inllen2, obd_ioctl_data::ioc_inllen3, obd_ioctl_data::ioc_inllen4, lr_server_data::lsd_osd_index, lu_object_remote, lu_target::lut_lsd, ofd_device::ofd_lut, ofd_object_child(), ofd_object_exists(), ofd_object_find(), ofd_object_put(), ofd_object::ofo_obj, ostid_set_id(), ostid_set_seq(), ostid_to_fid(), and version.
Referenced by ofd_iocontrol().
static int ofd_iocontrol (unsigned int cmd, struct obd_export * exp, int len, void * karg, void __user * uarg) [static]
Implementation of obd_ops::o_iocontrol.
This is OFD ioctl handling function which is primary interface for Lustre tools like lfs, lctl and lfsck.
Parameters:
[in] cmd ioctl command
[in] exp OBD export of OFD
[in] len not used
[in,out] karg buffer with data
[in] uarg not used
Return values:
0 if successful
negative value on error
Definition at line 1293 of file ofd_obd.c.
References CDEBUG, CERROR, D_IOCTL, D_RPCTRACE, dt_ro(), dt_sync(), ENTRY, obd_ioctl_data::ioc_inlbuf1, LCT_DT_THREAD, lfsck_start(), lfsck_stop(), lfsck_stop::ls_flags, lfsck_stop::ls_status, LS_STOPPED, lfsck_start_param::lsp_index_valid, lfsck_start_param::lsp_start, lu_env_fini(), lu_env_init(), obd_device::obd_abort_recovery, OBD_IOC_ABORT_RECOVERY, OBD_IOC_GET_OBJ_VERSION, OBD_IOC_SET_READONLY, OBD_IOC_START_LFSCK, OBD_IOC_STOP_LFSCK, OBD_IOC_SYNC, obd_device::obd_name, ofd_exp(), ofd_ioc_get_obj_version(), ofd_obd(), ofd_device::ofd_osd, RETURN, and unlikely.
static int ofd_obd_connect (const struct lu_env * env, struct obd_export ** _exp, struct obd_device * obd, struct obd_uuid * cluuid, struct obd_connect_data * data, void * localdata) [static]
Initialize new client connection.
This function handles new connection to the OFD. The new export is created (in context of class_connect()) and persistent client data is initialized on storage.
Parameters:
[in] env execution environment
[out] _exp stores pointer to new export
[in] obd OFD device
[in] cluuid client UUID
[in] data connection data from request
[in] localdata client NID
Return values:
0 if successful
negative value on error
Definition at line 340 of file ofd_obd.c.
References CDEBUG, class_conn2export(), class_connect(), class_disconnect(), D_HA, ENTRY, GOTO, LASSERT, lsd_client_data::lcd_uuid, nodemap_add_member(), nodemap_del_member(), obd_device::obd_lu_dev, obd_device::obd_name, obd_device::obd_replayable, obd_connect_data::ocd_group, ofd_dev(), ofd_export_stats_init(), ofd_parse_connect_data(), RETURN, tg_export_data::ted_lcd, tgt_client_new(), and obd_uuid::uuid.
int ofd_obd_disconnect (struct obd_export * exp)
Disconnect a connected client.
This function terminates the client connection. The client export is disconnected (cleaned up) and client data on persistent storage is removed.
Parameters:
[in] exp OBD export
Return values:
0 if successful
negative value on error
Definition at line 411 of file ofd_obd.c.
References class_export_get(), class_export_put(), ENTRY, obd_export::exp_failed, obd_export::exp_flags, obd_export::exp_obd, GOTO, LASSERT, LCT_DT_THREAD, lu_env_fini(), lu_env_init(), nodemap_del_member(), obd_device::obd_fail, OBD_OPT_FORCE, obd_device::obd_replayable, ofd_exp(), ofd_grant_discard(), ofd_grant_sanity_check(), ofd_obd(), RETURN, and tgt_client_del().
Referenced by ofd_create_hdl().
static int ofd_obd_postrecov (struct obd_device * obd) [static]
Implementation of obd_ops::o_postrecov.
This function is called from target_finish_recovery() upon recovery completion.
Parameters:
[in] obd OBD device of OFD
Return values:
0 if successful
negative value on error
Definition at line 573 of file ofd_obd.c.
References ENTRY, LCT_DT_THREAD, lu_env_fini(), lu_env_init(), obd_device::obd_lu_dev, obd_device::obd_self_export, ofd_dev(), ofd_info_init(), ofd_postrecov(), and RETURN.
static int ofd_obd_reconnect (const struct lu_env * env, struct obd_export * exp, struct obd_device * obd, struct obd_uuid * cluuid, struct obd_connect_data * data, void * client_nid) [static]
Re-initialize export upon client reconnection.
This function parses connection data from reconnect and resets export statistics.
Parameters:
[in] env execution environment
[in] exp OBD export
[in] obd OFD device
[in] cluuid NID of client
[in] data connection data from request
[in] localdata client NID
Return values:
0 if successful
negative value on error
Definition at line 295 of file ofd_obd.c.
References ENTRY, nodemap_add_member(), nodemap_del_member(), obd_device::obd_lu_dev, ofd_dev(), ofd_export_stats_init(), ofd_parse_connect_data(), and RETURN.
static int ofd_parse_connect_data (const struct lu_env * env, struct obd_export * exp, struct obd_connect_data * data, bool new_connection) [static]
Match client and OST server connection feature flags.
Compute the compatibility flags for a connection request based on features mutually supported by client and server.
The obd_export::exp_connect_data.ocd_connect_flags field in exp must not be updated here, otherwise a partially initialized value may be exposed. After the connection request is successfully processed, the top-level tgt_connect() request handler atomically updates the export connect flags from the obd_connect_data::ocd_connect_flags field of the reply.
See also:
tgt_connect().
Parameters:
[in] env execution environment
[in] exp the obd_export associated with this client/target pair
[in] data stores data for this connect request
[in] new_connection is this connection new or not
Return values:
0 if success
-EPROTO client and server feature requirements are incompatible
-EBADF OST index in connect request doesn't match real OST index
Definition at line 137 of file ofd_obd.c.
References CDEBUG, CERROR, cksum_types_supported_server(), CWARN, D_HA, D_RPCTRACE, dt_device_param::ddp_extent_tax, dt_device_param::ddp_inodespace, dt_device_param::ddp_max_extent_blks, dt_device_param::ddp_maxbytes, obd_export::exp_client_uuid, obd_export::exp_connect_data, obd_export::exp_obd, obd_export::exp_obd_chain_timed, filter_export_data::fed_group, LCONSOLE_ERROR_MSG, list_del_init(), LPX64, lr_server_data::lsd_feature_compat, lr_server_data::lsd_osd_index, LUSTRE_VERSION_CODE, lu_target::lut_lsd, OBD_COMPAT_OST, OBD_CONNECT_CKSUM, OBD_CONNECT_INDEX, OBD_CONNECT_MAXBYTES, OBD_CONNECT_MDS, OBD_CONNECT_PINGLESS, OBD_CONNECT_SKIP_ORPHAN, obd_device::obd_dev_lock, obd_export_nid2str(), OBD_FAIL_CHECK, OBD_FAIL_OST_BRW_SIZE, obd_device::obd_name, obd_connect_data::ocd_brw_size, obd_connect_data::ocd_cksum_types, obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_grant, obd_connect_data::ocd_grant_blkbits, obd_connect_data::ocd_grant_inobits, obd_connect_data::ocd_grant_max_blks, obd_connect_data::ocd_grant_tax_kb, obd_connect_data::ocd_group, OCD_HAS_FLAG, obd_connect_data::ocd_index, obd_connect_data::ocd_maxbytes, obd_connect_data::ocd_version, ofd_device::ofd_blockbits, ofd_device::ofd_brw_size, ofd_device::ofd_dt_conf, ofd_exp(), ofd_grant_connect(), ofd_device::ofd_lut, OST_CONNECT_SUPPORTED, ptlrpc_pinger_suppress_pings(), RETURN, tgt_server_data_update(), unlikely, and obd_uuid::uuid.
Referenced by ofd_obd_connect(), and ofd_obd_reconnect().
static int ofd_ping (const struct lu_env * env, struct obd_export * exp) [static]
Implementation of obd_ops::o_ping.
This is OFD-specific part of OBD_PING request handling. It controls Filter Modification Data (FMD) expiration each time PING is received.
See also:
ofd_fmd_expire() and ofd_fmd.c for details
Parameters:
[in] env execution environment
[in] exp OBD export of client
Return values:
0
Definition at line 1396 of file ofd_obd.c.
References ofd_fmd_expire().
int ofd_postrecov (const struct lu_env * env, struct ofd_device * ofd)
Notify all devices in server stack about recovery completion.
This function calls ldo_recovery_complete() for all lower devices in the server stack so they will be prepared for normal operations.
Parameters:
[in] env execution environment
[in] ofd OFD device
Return values:
0 if successful
negative value on error
Definition at line 541 of file ofd_obd.c.
References CDEBUG, CWARN, D_HA, dt_device::dd_lu_dev, lu_device::ld_ops, lu_device_operations::ldo_recovery_complete, lfsck_start(), lfsck_start_param::lsp_index_valid, lfsck_start_param::lsp_start, ofd_device::ofd_dt_dev, ofd_name(), ofd_device::ofd_osd, and ofd_device::ofd_skip_lfsck.
Referenced by ofd_obd_postrecov(), and ofd_prepare().
static int ofd_precleanup (struct obd_device * obd) [static]
Implementation of obd_ops::o_precleanup.
This function stops device activity before shutting it down. It is called from a cleanup function upon forceful device cleanup. For OFD there are no special actions, it just invokes target_recovery_cleanup().
Parameters:
[in] obd OBD device of OFD
Return values:
0
Definition at line 1375 of file ofd_obd.c.
References ENTRY, and RETURN.
static int ofd_set_info_async (const struct lu_env * env, struct obd_export * exp, __u32 keylen, void * key, __u32 vallen, void * val, struct ptlrpc_request_set * set) [static]
Implementation of obd_ops::o_set_info_async.
This function is not called from request handler, it is only used by class_notify_sptlrpc_conf() locally by direct obd_set_info_async() call.
See also:
ofd_set_info_hdl() for request handler function.
Parameters:
[in] env execution environment
[in] exp OBD export of OFD device
[in] keylen length of key
[in] key key name
[in] vallen length of val
[in] val the key value
[in] set not used in OFD
Return values:
0 if successful
negative value on error
Definition at line 610 of file ofd_obd.c.
References CDEBUG, CERROR, D_IOCTL, ENTRY, obd_export::exp_obd, KEY_IS, KEY_SPTLRPC_CONF, obd_device::obd_name, RETURN, and tgt_adapt_sptlrpc_conf().
int ofd_statfs (const struct lu_env * env, struct obd_export * exp, struct obd_statfs * osfs, __u64 max_age, __u32 flags)
Implementation of obd_ops::o_statfs.
This function returns information about a storage file system. It is called from several places by using the OBD API as well as by direct call, e.g. from request handler.
See also:
ofd_statfs_hdl() for request handler function.
Report also the state of the OST to the caller in osfs->os_state (OS_STATE_READONLY, OS_STATE_DEGRADED).
Parameters:
[in] env execution environment
[in] exp OBD export of OFD device
[out] osfs statistic data to return
[in] max_age maximum age for cached data
[in] flags not used in OFD
Return values:
0 if successful
negative value on error
Definition at line 806 of file ofd_obd.c.
References CDEBUG, class_exp2obd(), COMPAT_BSIZE_SHIFT, D_CACHE, D_SUPER, ENTRY, EXIT, exp_connect_flags(), filter_export_data::fed_grant, GOTO, LPU64, lr_server_data::lsd_osd_index, lu_target::lut_lsd, min_t, OBD_CONNECT_MDS, OBD_FAIL_CHECK_VALUE, OBD_FAIL_OST_ENOINO, OBD_FAIL_OST_ENOSPC, obd_device::obd_self_export, ofd_device::ofd_blockbits, ofd_exp(), ofd_grant_param_supp(), ofd_grant_sanity_check(), ofd_device::ofd_lut, ofd_device::ofd_raid_degraded, ofd_statfs_internal(), ofd_device::ofd_tot_dirty, ofd_device::ofd_tot_granted, ofd_device::ofd_tot_pending, obd_statfs::os_bavail, obd_statfs::os_bfree, obd_statfs::os_blocks, obd_statfs::os_bsize, obd_statfs::os_ffree, obd_statfs::os_files, obd_statfs::os_state, OS_STATE_DEGRADED, and unlikely.
Referenced by ofd_statfs_hdl().
int ofd_statfs_internal (const struct lu_env * env, struct ofd_device * ofd, struct obd_statfs * osfs, __u64 max_age, int * from_cache)
Get file system statistics of OST server.
Helper function for ofd_statfs(), also used by grant code. Implements caching for statistics to avoid calling OSD device each time.
Parameters:
[in] env execution environment
[in] ofd OFD device
[out] osfs statistic data to return
[in] max_age maximum age for cached data
[in] from_cache show that data was get from cache or not
Return values:
0 if successful
negative value on error
Definition at line 701 of file ofd_obd.c.
References cfs_time_before_64(), cfs_time_current_64, dt_statfs(), ENTRY, GOTO, min_t, ofd_device::ofd_blockbits, ofd_device::ofd_grant_lock, ofd_device::ofd_osd, ofd_device::ofd_osfs, ofd_device::ofd_osfs_age, ofd_device::ofd_osfs_inflight, ofd_device::ofd_osfs_lock, ofd_device::ofd_osfs_unstable, ofd_device::ofd_statfs_inflight, ofd_device::ofd_tot_pending, obd_statfs::os_bavail, and unlikely.
Referenced by ofd_grant_statfs(), ofd_init0(), and ofd_statfs().
Variable Documentation
struct obd_ops ofd_obd_ops
Initial value:
 {
        .o_owner                = THIS_MODULE,
        .o_connect              = ofd_obd_connect,
        .o_reconnect            = ofd_obd_reconnect,
        .o_disconnect           = ofd_obd_disconnect,
        .o_create               = ofd_echo_create,
        .o_statfs               = ofd_statfs,
        .o_setattr              = ofd_echo_setattr,
        .o_preprw               = ofd_preprw,
        .o_commitrw             = ofd_commitrw,
        .o_destroy              = ofd_echo_destroy,
        .o_init_export          = ofd_init_export,
        .o_destroy_export       = ofd_destroy_export,
        .o_postrecov            = ofd_obd_postrecov,
        .o_getattr              = ofd_echo_getattr,
        .o_iocontrol            = ofd_iocontrol,
        .o_precleanup           = ofd_precleanup,
        .o_ping                 = ofd_ping,
        .o_health_check         = ofd_health_check,
        .o_set_info_async       = ofd_set_info_async,
        .o_get_info             = ofd_get_info,
}
Definition at line 1476 of file ofd_obd.c.
Referenced by ofd_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.