Lustre: lustre/ofd/ofd_grant.c File Reference
lustre/ofd/ofd_grant.c File Reference
#include "ofd_internal.h"
Data Structures
struct ofd_grant_cb
Defines
#define DEBUG_SUBSYSTEM S_FILTER
#define OFD_GRANT_SHRINK_LIMIT(exp) (2ULL * 8 * exp_max_brw_size(exp))
Functions
static u64 ofd_grant_inflate (struct ofd_device *ofd, u64 val)
static u64 ofd_grant_deflate (struct ofd_device *ofd, u64 val)
static u64 ofd_grant_chunk (struct obd_export *exp, struct ofd_device *ofd, struct obd_connect_data *data)
void ofd_grant_sanity_check (struct obd_device *obd, const char *func)
Perform extra sanity checks for grant accounting.
static void ofd_grant_statfs (const struct lu_env *env, struct obd_export *exp, int force, int *from_cache)
Update cached statfs information from the OSD layer.
static u64 ofd_grant_space_left (struct obd_export *exp)
Figure out how much space is available on the backend filesystem after removing grant space already booked by clients.
static void ofd_grant_incoming (const struct lu_env *env, struct obd_export *exp, struct obdo *oa, long chunk)
Process grant information from obdo structure packed in incoming BRW and inflate grant counters if required.
static void ofd_grant_shrink (struct obd_export *exp, struct obdo *oa, u64 left_space)
Grant shrink request handler.
static u64 ofd_grant_rnb_size (struct obd_export *exp, struct ofd_device *ofd, struct niobuf_remote *rnb)
Calculate how much space is required to write a given network buffer.
static void ofd_grant_check (const struct lu_env *env, struct obd_export *exp, struct obdo *oa, struct niobuf_remote *rnb, int niocount, u64 *left)
Validate grant accounting for each incoming remote network buffer.
static long ofd_grant_alloc (struct obd_export *exp, u64 curgrant, u64 want, u64 left, long chunk, bool conservative)
Allocate additional grant space to a client.
void ofd_grant_connect (const struct lu_env *env, struct obd_export *exp, struct obd_connect_data *data, bool new_conn)
Handle grant space allocation on client connection & reconnection.
void ofd_grant_discard (struct obd_export *exp)
Release all grant space attached to a given export.
void ofd_grant_prepare_read (const struct lu_env *env, struct obd_export *exp, struct obdo *oa)
Process grant information from incoming bulk read request.
void ofd_grant_prepare_write (const struct lu_env *env, struct obd_export *exp, struct obdo *oa, struct niobuf_remote *rnb, int niocount)
Process grant information from incoming bulk write request.
long ofd_grant_create (const struct lu_env *env, struct obd_export *exp, int *nr)
Consume grant space reserved for object creation.
void ofd_grant_commit (struct obd_export *exp, unsigned long pending, int rc)
Release grant space added to the pending counter by ofd_grant_prepare_write().
static void ofd_grant_commit_cb (struct lu_env *env, struct thandle *th, struct dt_txn_commit_cb *cb, int err)
Callback function for grant releasing.
int ofd_grant_commit_cb_add (struct thandle *th, struct obd_export *exp, unsigned long granted)
Add callback for grant releasing.
Define Documentation
#define DEBUG_SUBSYSTEM S_FILTER
Definition at line 73 of file ofd_grant.c.
#define OFD_GRANT_SHRINK_LIMIT (exp) (2ULL * 8 * exp_max_brw_size(exp))
Definition at line 78 of file ofd_grant.c.
Referenced by ofd_grant_shrink().
Function Documentation
static long ofd_grant_alloc (struct obd_export * exp, u64 curgrant, u64 want, u64 left, long chunk, bool conservative) [static]
Allocate additional grant space to a client.
Calculate how much grant space to return to client, based on how much space is currently free and how much of that is already granted. Caller must hold ofd_grant_lock spinlock.
Parameters:
[in] exp export of the client which sent the request
[in] curgrant current grant claimed by the client
[in] want how much grant space the client would like to have
[in] left remaining free space with granted space taken out
[in] conservative if set to true, the server should be cautious and limit how much space is granted back to the client. Otherwise, the server should try hard to satisfy the client request.
Return values:
amount of grant space allocated
Definition at line 778 of file ofd_grant.c.
References CDEBUG, CERROR, D_CACHE, ENTRY, obd_export::exp_client_uuid, obd_export::exp_failed, obd_export::exp_obd, filter_export_data::fed_grant, LBUG, LPU64, obd_device::obd_name, obd_device::obd_num_exports, obd_device::obd_recovering, ofd_device::ofd_blockbits, ofd_exp(), ofd_device::ofd_grant_lock, ofd_grant_prohibit(), ofd_device::ofd_tot_dirty, ofd_device::ofd_tot_granted, RETURN, and obd_uuid::uuid.
Referenced by ofd_grant_connect(), ofd_grant_create(), and ofd_grant_prepare_write().
static void ofd_grant_check (const struct lu_env * env, struct obd_export * exp, struct obdo * oa, struct niobuf_remote * rnb, int niocount, u64 * left) [static]
Validate grant accounting for each incoming remote network buffer.
When clients have dirtied as much space as they've been granted they fall through to sync writes. These sync writes haven't been expressed in grants and need to error with ENOSPC when there isn't room in the filesystem for them after grants are taken into account. However, writeback of the dirty data that was already granted space can write right on through. The OBD_BRW_GRANTED flag will be set in the rnb_flags of each network buffer which has been granted enough space to proceed. Buffers without this flag will fail to be written with -ENOSPC (see ofd_preprw_write(). Caller must hold ofd_grant_lock spinlock.
Parameters:
[in] env LU environment passed by the caller
[in] exp export identifying the client which sent the RPC
[in] oa incoming obdo in which we should return the pack the additional grant
[in,out] rnb the list of network buffers
[in] niocount the number of network buffers in the list
[in] left the remaining free space with space already granted taken out
Definition at line 591 of file ofd_grant.c.
References CDEBUG, CERROR, CWARN, D_CACHE, ENTRY, EXIT, obd_export::exp_client_uuid, obd_export::exp_obd, filter_export_data::fed_dirty, filter_export_data::fed_grant, filter_export_data::fed_pending, ofd_thread_info::fti_used, LBUG, obdo::o_flags, obdo::o_valid, OBD_BRW_FROM_GRANT, OBD_BRW_GRANTED, OBD_FL_RECOV_RESEND, OBD_MD_FLFLAGS, OBD_MD_FLGRANT, obd_device::obd_name, obd_device::obd_recovering, ofd_exp(), ofd_device::ofd_grant_lock, ofd_grant_param_supp(), ofd_grant_rnb_size(), ofd_info(), ofd_device::ofd_tot_dirty, ofd_device::ofd_tot_granted, ofd_device::ofd_tot_pending, RETURN_EXIT, niobuf_remote::rnb_flags, and obd_uuid::uuid.
Referenced by ofd_grant_prepare_write().
static u64 ofd_grant_chunk (struct obd_export * exp, struct ofd_device * ofd, struct obd_connect_data * data) [inline, static]
Definition at line 106 of file ofd_grant.c.
References dt_device_param::ddp_extent_tax, dt_device_param::ddp_inodespace, dt_device_param::ddp_max_extent_blks, exp_max_brw_size(), OCD_HAS_FLAG, ofd_device::ofd_blockbits, ofd_device::ofd_dt_conf, ofd_grant_inflate(), ofd_grant_param_supp(), ofd_obd(), and OST_MAX_PRECREATE.
Referenced by ofd_grant_connect(), ofd_grant_create(), ofd_grant_prepare_read(), and ofd_grant_prepare_write().
void ofd_grant_commit (struct obd_export * exp, unsigned long pending, int rc)
Release grant space added to the pending counter by ofd_grant_prepare_write().
Update pending grant counter once buffers have been written to the disk.
Parameters:
[in] exp export of the client which sent the request
[in] pending amount of reserved space to be released
[in] rc return code of pre-commit operations
Definition at line 1264 of file ofd_grant.c.
References CERROR, ENTRY, EXIT, obd_export::exp_client_uuid, obd_export::exp_obd, LBUG, LPU64, min_t, obd_device::obd_name, ofd_device::ofd_blockbits, ofd_exp(), ofd_device::ofd_grant_lock, ofd_device::ofd_osfs, ofd_device::ofd_osfs_inflight, ofd_device::ofd_osfs_lock, ofd_device::ofd_statfs_inflight, ofd_device::ofd_tot_granted, ofd_device::ofd_tot_pending, obd_statfs::os_bavail, RETURN_EXIT, and obd_uuid::uuid.
Referenced by ofd_commitrw_write(), ofd_create_hdl(), ofd_echo_create(), ofd_grant_commit_cb(), and ofd_preprw_write().
static void ofd_grant_commit_cb (struct lu_env * env, struct thandle * th, struct dt_txn_commit_cb * cb, int err) [static]
Callback function for grant releasing.
Release grant space reserved by the client node.
Parameters:
[in] env execution environment
[in] th transaction handle
[in] cb callback data
[in] err error code
Definition at line 1345 of file ofd_grant.c.
References class_export_cb_put, OBD_FREE_PTR, ofd_grant_commit(), ofd_grant_cb::ogc_cb, ofd_grant_cb::ogc_exp, and ofd_grant_cb::ogc_granted.
Referenced by ofd_grant_commit_cb_add().
int ofd_grant_commit_cb_add (struct thandle * th, struct obd_export * exp, unsigned long granted)
Add callback for grant releasing.
Register a commit callback to release grant space.
Parameters:
[in] th transaction handle
[in] exp OBD export of client
[in] granted amount of grant space to be released upon commit
Return values:
0 on successful callback adding
negative value on error
Definition at line 1369 of file ofd_grant.c.
References class_export_cb_get, class_export_cb_put, dt_txn_commit_cb::dcb_func, dt_txn_commit_cb::dcb_linkage, dt_txn_commit_cb::dcb_name, dt_trans_cb_add(), ENTRY, INIT_LIST_HEAD, OBD_ALLOC_PTR, OBD_FREE_PTR, ofd_grant_commit_cb(), ofd_grant_cb::ogc_cb, ofd_grant_cb::ogc_exp, ofd_grant_cb::ogc_granted, RETURN, and strlcpy().
Referenced by ofd_commitrw_write().
void ofd_grant_connect (const struct lu_env * env, struct obd_export * exp, struct obd_connect_data * data, bool new_conn)
Handle grant space allocation on client connection & reconnection.
A new non-readonly connection gets an initial grant allocation equals to ofd_grant_chunk() (i.e. twice the max BRW size in most of the cases). On reconnection, grant counters between client & OST are resynchronized and additional space might be granted back if possible.
Parameters:
[in] env LU environment provided by the caller
[in] exp client's export which is (re)connecting
[in,out] data obd_connect_data structure sent by the client in the connect request
[in] new_conn must set to true if this is a new connection and false for a reconnection
Definition at line 868 of file ofd_grant.c.
References CDEBUG, D_CACHE, EXIT, obd_export::exp_client_uuid, obd_export::exp_obd, filter_export_data::fed_dirty, filter_export_data::fed_grant, LPU64, OBD_CONNECT_GRANT, OBD_CONNECT_GRANT_PARAM, obd_device::obd_name, obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_grant, OCD_HAS_FLAG, ofd_exp(), ofd_grant_alloc(), ofd_grant_chunk(), ofd_device::ofd_grant_compat_disable, ofd_grant_deflate(), ofd_grant_inflate(), ofd_device::ofd_grant_lock, ofd_grant_space_left(), ofd_grant_statfs(), ofd_device::ofd_tot_dirty, ofd_device::ofd_tot_granted_clients, RETURN_EXIT, and obd_uuid::uuid.
Referenced by ofd_parse_connect_data(), and ofd_recovery_complete().
long ofd_grant_create (const struct lu_env * env, struct obd_export * exp, int * nr)
Consume grant space reserved for object creation.
Grant space is allocated to the local self export for object precreation. This is required to prevent object precreation from consuming grant space allocated to client nodes for the data writeback cache. This function consumes enough space to create nr objects and allocates more grant space to the self export for future precreation requests, if possible.
Parameters:
[in] env LU environment provided by the caller
[in] exp export holding the grant space for precreation (= self export currently)
[in] nr number of objects to be created
Return values:
>= 0 amount of grant space allocated to the precreate request
-ENOSPC on failure
Definition at line 1172 of file ofd_grant.c.
References CDEBUG, D_RPCTRACE, dt_device_param::ddp_inodespace, ENTRY, obd_export::exp_obd, filter_export_data::fed_grant, filter_export_data::fed_pending, LASSERT, LPU64, obd_device::obd_recovering, ofd_device::ofd_blockbits, ofd_device::ofd_dt_conf, ofd_exp(), ofd_grant_alloc(), ofd_grant_chunk(), ofd_device::ofd_grant_lock, ofd_grant_space_left(), ofd_grant_statfs(), ofd_name(), ofd_device::ofd_osfs, ofd_device::ofd_tot_granted, ofd_device::ofd_tot_pending, obd_statfs::os_bavail, obd_statfs::os_blocks, OST_MAX_PRECREATE, and RETURN.
Referenced by ofd_create_hdl(), and ofd_echo_create().
static u64 ofd_grant_deflate (struct ofd_device * ofd, u64 val) [inline, static]
Definition at line 95 of file ofd_grant.c.
References COMPAT_BSIZE_SHIFT, and ofd_device::ofd_blockbits.
Referenced by ofd_grant_connect(), ofd_grant_prepare_read(), and ofd_grant_prepare_write().
void ofd_grant_discard (struct obd_export * exp)
Release all grant space attached to a given export.
Remove a client from the grant accounting totals. We also remove the export from the obd device under the osfs and dev locks to ensure that the ofd_grant_sanity_check() calculations are always valid. The client should do something similar when it invalidates its import.
Parameters:
[in] exp client's export to remove from grant accounting
Definition at line 947 of file ofd_grant.c.
References obd_export::exp_client_uuid, obd_export::exp_obd, filter_export_data::fed_dirty, filter_export_data::fed_grant, filter_export_data::fed_pending, LASSERTF, LPU64, obd_device::obd_name, ofd_exp(), ofd_device::ofd_grant_lock, ofd_device::ofd_tot_dirty, ofd_device::ofd_tot_granted, ofd_device::ofd_tot_pending, and obd_uuid::uuid.
Referenced by ofd_destroy_export(), and ofd_obd_disconnect().
static void ofd_grant_incoming (const struct lu_env * env, struct obd_export * exp, struct obdo * oa, long chunk) [static]
Process grant information from obdo structure packed in incoming BRW and inflate grant counters if required.
Grab the dirty and seen grant announcements from the incoming obdo and inflate all grant counters passed in the request if the client does not support the grant parameters. We will later calculate the client's new grant and return it. Caller must hold ofd_grant_lock spinlock.
Parameters:
[in] env LU environment supplying osfs storage
[in] exp export for which we received the request
[in,out] oa incoming obdo sent by the client
Definition at line 393 of file ofd_grant.c.
References CDEBUG, CERROR, D_CACHE, ENTRY, EXIT, obd_export::exp_client_uuid, obd_export::exp_obd, filter_export_data::fed_dirty, filter_export_data::fed_grant, filter_export_data::fed_pending, LBUG, LPU64, obdo::o_grant, obdo::o_valid, OBD_MD_FLBLOCKS, OBD_MD_FLGRANT, obd_device::obd_name, ofd_exp(), ofd_grant_inflate(), ofd_device::ofd_grant_lock, ofd_grant_param_supp(), ofd_device::ofd_tot_dirty, ofd_device::ofd_tot_granted, RETURN_EXIT, and obd_uuid::uuid.
Referenced by ofd_grant_prepare_read(), and ofd_grant_prepare_write().
static u64 ofd_grant_inflate (struct ofd_device * ofd, u64 val) [inline, static]
Definition at line 82 of file ofd_grant.c.
References COMPAT_BSIZE_SHIFT, and ofd_device::ofd_blockbits.
Referenced by ofd_grant_chunk(), ofd_grant_connect(), ofd_grant_incoming(), and ofd_grant_rnb_size().
void ofd_grant_prepare_read (const struct lu_env * env, struct obd_export * exp, struct obdo * oa)
Process grant information from incoming bulk read request.
Extract grant information packed in obdo structure (OBD_MD_FLGRANT set in o_valid). Bulk reads usually comes with grant announcements (number of dirty blocks, remaining amount of grant space, ...) and could also include a grant shrink request. Unlike bulk write, no additional grant space is returned on bulk read request.
Parameters:
[in] env is the lu environment provided by the caller
[in] exp is the export of the client which sent the request
[in,out] oa is the incoming obdo sent by the client
Definition at line 988 of file ofd_grant.c.
References ENTRY, EXIT, obdo::o_flags, obdo::o_grant, obdo::o_valid, OBD_FL_SHRINK_GRANT, OBD_MD_FLFLAGS, OBD_MD_FLGRANT, ofd_exp(), ofd_grant_chunk(), ofd_grant_deflate(), ofd_grant_incoming(), ofd_device::ofd_grant_lock, ofd_grant_param_supp(), ofd_grant_shrink(), ofd_grant_space_left(), ofd_grant_statfs(), and RETURN_EXIT.
Referenced by ofd_preprw(), ofd_preprw_write(), and ofd_set_info_hdl().
void ofd_grant_prepare_write (const struct lu_env * env, struct obd_export * exp, struct obdo * oa, struct niobuf_remote * rnb, int niocount)
Process grant information from incoming bulk write request.
This function extracts client's grant announcements from incoming bulk write request and attempts to allocate grant space for network buffers that need it (i.e. OBD_BRW_FROM_GRANT not set in rnb_fags). Network buffers which aren't granted the OBD_BRW_GRANTED flag should not proceed further and should fail with -ENOSPC. Whenever possible, additional grant space will be returned to the client in the bulk write reply. ofd_grant_prepare_write() must be called before writting any buffers to the backend storage. This function works in pair with ofd_grant_commit() which must be invoked once all buffers have been written to disk in order to release space from the pending grant counter.
Parameters:
[in] env LU environment provided by the caller
[in] exp export of the client which sent the request
[in] oa incoming obdo sent by the client
[in] rnb list of network buffers
[in] niocount number of network buffers in the list
Definition at line 1068 of file ofd_grant.c.
References CDEBUG, D_CACHE, dt_sync(), ENTRY, EXIT, obd_export::exp_obd, obdo::o_flags, obdo::o_grant, obdo::o_valid, OBD_BRW_FROM_GRANT, OBD_FL_SHRINK_GRANT, OBD_MD_FLFLAGS, OBD_MD_FLGRANT, obd_device::obd_name, obd_device::obd_recovering, ofd_exp(), ofd_grant_alloc(), ofd_grant_check(), ofd_grant_chunk(), ofd_grant_deflate(), ofd_grant_incoming(), ofd_device::ofd_grant_lock, ofd_grant_param_supp(), ofd_grant_shrink(), ofd_grant_space_left(), ofd_grant_statfs(), ofd_device::ofd_osd, and RETURN_EXIT.
Referenced by ofd_preprw_write().
static u64 ofd_grant_rnb_size (struct obd_export * exp, struct ofd_device * ofd, struct niobuf_remote * rnb) [inline, static]
Calculate how much space is required to write a given network buffer.
This function takes block alignment into account to estimate how much on-disk space will be required to successfully write the whole niobuf. Estimated space is inflated if the export does not support OBD_CONNECT_GRANT_PARAM and if the backend filesystem has a block size larger than the minimal supported page size (i.e. 4KB).
Parameters:
[in] exp export associated which the write request if NULL, then size estimate is done for server-side grant allocation.
[in] ofd ofd device handling the request
[in] rnb network buffer to estimate size of
Return values:
space (in bytes) that will be consumed to write the network buffer
Definition at line 529 of file ofd_grant.c.
References COMPAT_BSIZE_SHIFT, dt_device_param::ddp_extent_tax, dt_device_param::ddp_max_extent_blks, end, ofd_device::ofd_blockbits, ofd_device::ofd_dt_conf, ofd_grant_inflate(), ofd_grant_param_supp(), niobuf_remote::rnb_len, and niobuf_remote::rnb_offset.
Referenced by ofd_grant_check().
void ofd_grant_sanity_check (struct obd_device * obd, const char * func)
Perform extra sanity checks for grant accounting.
This function scans the export list, sanity checks per-export grant counters and verifies accuracy of global grant accounting. If an inconsistency is found, a CERROR is printed with the function name that was passed as argument. LBUG is only called in case of serious counter corruption (i.e. value larger than the device size). Those sanity checks can be pretty expensive and are disabled if the OBD device has more than 100 connected exports.
Parameters:
[in] obd OBD device for which grant accounting should be verified
[in] func caller's function name
Definition at line 147 of file ofd_grant.c.
References CDEBUG, CDEBUG_LIMIT, CERROR, D_CACHE, D_ERROR, error, obd_export::exp_client_uuid, obd_export::exp_obd_chain, filter_export_data::fed_dirty, filter_export_data::fed_grant, filter_export_data::fed_pending, LBUG, list_empty(), list_for_each_entry, LPU64, obd_device::obd_dev_lock, obd_device::obd_exports, obd_device::obd_lu_dev, obd_device::obd_name, obd_device::obd_num_exports, obd_device::obd_self_export, obd_device::obd_unlinked_exports, ofd_device::ofd_blockbits, ofd_dev(), ofd_device::ofd_grant_lock, ofd_device::ofd_osfs, ofd_device::ofd_tot_dirty, ofd_device::ofd_tot_granted, ofd_device::ofd_tot_pending, obd_statfs::os_blocks, and obd_uuid::uuid.
Referenced by ofd_destroy_export(), ofd_obd_disconnect(), and ofd_statfs().
static void ofd_grant_shrink (struct obd_export * exp, struct obdo * oa, u64 left_space) [static]
Grant shrink request handler.
Client nodes can explicitly release grant space (i.e. process called grant shrinking). This function proceeds with the shrink request when there is less ungranted space remaining than the amount all of the connected clients would consume if they used their full grant. Caller must hold ofd_grant_lock spinlock.
Parameters:
[in] exp export releasing grant space
[in,out] oa incoming obdo sent by the client
[in] left_space remaining free space with space already granted taken out
Definition at line 483 of file ofd_grant.c.
References CDEBUG, D_CACHE, obd_export::exp_client_uuid, obd_export::exp_obd, filter_export_data::fed_grant, LASSERT, LPU64, obdo::o_grant, obd_device::obd_name, ofd_exp(), ofd_device::ofd_grant_lock, OFD_GRANT_SHRINK_LIMIT, ofd_device::ofd_tot_granted, ofd_device::ofd_tot_granted_clients, and obd_uuid::uuid.
Referenced by ofd_grant_prepare_read(), and ofd_grant_prepare_write().
static u64 ofd_grant_space_left (struct obd_export * exp) [static]
Figure out how much space is available on the backend filesystem after removing grant space already booked by clients.
This is done by accessing cached statfs data previously populated by ofd_grant_statfs(), from which we withdraw the space already granted to clients and the reserved space. Caller must hold ofd_grant_lock spinlock.
Parameters:
[in] exp export associated with the device for which the amount of available space is requested
Return values:
amount of non-allocated space, in bytes
Definition at line 330 of file ofd_grant.c.
References CDEBUG, CDEBUG_LIMIT, D_CACHE, D_ERROR, ENTRY, obd_export::exp_client_uuid, obd_export::exp_obd, LPU64, obd_device::obd_name, ofd_device::ofd_blockbits, ofd_exp(), ofd_device::ofd_grant_lock, ofd_device::ofd_osfs, ofd_device::ofd_osfs_lock, ofd_device::ofd_osfs_unstable, ofd_device::ofd_tot_dirty, ofd_device::ofd_tot_granted, ofd_device::ofd_tot_pending, obd_statfs::os_bavail, RETURN, and obd_uuid::uuid.
Referenced by ofd_grant_connect(), ofd_grant_create(), ofd_grant_prepare_read(), and ofd_grant_prepare_write().
static void ofd_grant_statfs (const struct lu_env * env, struct obd_export * exp, int force, int * from_cache) [static]
Update cached statfs information from the OSD layer.
Refresh statfs information cached in ofd::ofd_osfs if the cache is older than 1s or if force is set. The OSD layer is in charge of estimating data & metadata overhead. This function can sleep so it should not be called with any spinlock held.
Parameters:
[in] env LU environment passed by the caller
[in] exp export used to print client info in debug messages
[in] force force a refresh of statfs information
[out] from_cache returns whether the statfs information are taken from cache
Definition at line 290 of file ofd_grant.c.
References __u64, CDEBUG, cfs_time_shift_64(), D_CACHE, obd_export::exp_client_uuid, obd_export::exp_obd, ofd_thread_info::fti_u, LPU64, obd_device::obd_name, OBD_STATFS_CACHE_SECONDS, ofd_device::ofd_blockbits, ofd_exp(), ofd_info(), ofd_statfs_internal(), obd_statfs::os_bavail, obd_statfs::os_bfree, ofd_thread_info::osfs, unlikely, and obd_uuid::uuid.
Referenced by ofd_grant_connect(), ofd_grant_create(), ofd_grant_prepare_read(), and ofd_grant_prepare_write().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.