Lustre: lustre/ofd/ofd_internal.h File Reference
lustre/ofd/ofd_internal.h File Reference
#include <obd.h>
#include <obd_class.h>
#include <dt_object.h>
#include <md_object.h>
#include <lustre_fid.h>
Data Structures
struct ofd_mod_data
struct ofd_seq
struct ofd_device
struct ofd_object
struct ofd_thread_info
Defines
#define OFD_INIT_OBJID 0
#define OFD_PRECREATE_BATCH_DEFAULT (OBJ_SUBDIR_COUNT * 4)
#define OFD_PRECREATE_SMALL_FS (1024ULL * 1024 * 1024)
#define OFD_PRECREATE_BATCH_SMALL 8
#define OFD_VALID_FLAGS
#define OFD_FMD_MAX_NUM_DEFAULT 128
#define OFD_FMD_MAX_AGE_DEFAULT msecs_to_jiffies((obd_timeout+10)*MSEC_PER_SEC)
#define OFD_SOFT_SYNC_LIMIT_DEFAULT 16
#define COMPAT_BSIZE_SHIFT 12
#define ofd_fmd_drop(exp, fid) do {} while (0)
Enumerations
enum {
LPROC_OFD_STATS_READ = 0, LPROC_OFD_STATS_WRITE, LPROC_OFD_STATS_GETATTR, LPROC_OFD_STATS_SETATTR,
LPROC_OFD_STATS_PUNCH, LPROC_OFD_STATS_SYNC, LPROC_OFD_STATS_DESTROY, LPROC_OFD_STATS_CREATE,
LPROC_OFD_STATS_STATFS, LPROC_OFD_STATS_GET_INFO, LPROC_OFD_STATS_SET_INFO, LPROC_OFD_STATS_QUOTACTL,
LPROC_OFD_STATS_LAST
}
Functions
static void ofd_counter_incr (struct obd_export *exp, int opcode, char *jobid, long amount)
static struct ofd_device * ofd_dev (struct lu_device *d)
static struct obd_device * ofd_obd (struct ofd_device *ofd)
static struct ofd_device * ofd_exp (struct obd_export *exp)
static char * ofd_name (struct ofd_device *ofd)
static struct ofd_object * ofd_obj (struct lu_object *o)
static int ofd_object_exists (struct ofd_object *obj)
static struct dt_object * fo2dt (struct ofd_object *obj)
static struct dt_object * ofd_object_child (struct ofd_object *_obj)
static struct ofd_device * ofd_obj2dev (const struct ofd_object *fo)
static void ofd_read_lock (const struct lu_env *env, struct ofd_object *fo)
static void ofd_read_unlock (const struct lu_env *env, struct ofd_object *fo)
static void ofd_write_lock (const struct lu_env *env, struct ofd_object *fo)
static void ofd_write_unlock (const struct lu_env *env, struct ofd_object *fo)
void target_recovery_fini (struct obd_device *obd)
void target_recovery_init (struct lu_target *lut, svc_handler_t handler)
int ofd_postrecov (const struct lu_env *env, struct ofd_device *ofd)
Notify all devices in server stack about recovery completion.
int ofd_fiemap_get (const struct lu_env *env, struct ofd_device *ofd, struct lu_fid *fid, struct fiemap *fiemap)
Get FIEMAP (FIle Extent MAPping) for object with the given FID.
int ofd_statfs_internal (const struct lu_env *env, struct ofd_device *ofd, struct obd_statfs *osfs, __u64 max_age, int *from_cache)
Get file system statistics of OST server.
int ofd_destroy_by_fid (const struct lu_env *env, struct ofd_device *ofd, const struct lu_fid *fid, int orphan)
Destroy OFD object by its FID.
int ofd_statfs (const struct lu_env *env, struct obd_export *exp, struct obd_statfs *osfs, __u64 max_age, __u32 flags)
Implementation of obd_ops::o_statfs.
int ofd_obd_disconnect (struct obd_export *exp)
Disconnect a connected client.
u64 ofd_seq_last_oid (struct ofd_seq *oseq)
Get last object ID for the given sequence.
void ofd_seq_last_oid_set (struct ofd_seq *oseq, u64 id)
Set new last object ID for the given sequence.
int ofd_seq_last_oid_write (const struct lu_env *env, struct ofd_device *ofd, struct ofd_seq *oseq)
Update last used OID on disk for the given sequence.
int ofd_seqs_init (const struct lu_env *env, struct ofd_device *ofd)
Initialize SEQ and FLD service on OFD.
struct ofd_seq * ofd_seq_get (struct ofd_device *ofd, u64 seq)
Get ofd_seq for seq.
void ofd_seq_put (const struct lu_env *env, struct ofd_seq *oseq)
Drop a reference to ofd_seq.
int ofd_fs_setup (const struct lu_env *env, struct ofd_device *ofd, struct obd_device *obd)
Initialize storage for the OFD.
void ofd_fs_cleanup (const struct lu_env *env, struct ofd_device *ofd)
Cleanup service files on OFD.
int ofd_precreate_batch (struct ofd_device *ofd, int batch)
Restrict precreate batch count by its upper limit.
struct ofd_seq * ofd_seq_load (const struct lu_env *env, struct ofd_device *ofd, u64 seq)
Return ofd_seq structure filled with valid data.
void ofd_seqs_fini (const struct lu_env *env, struct ofd_device *ofd)
Stop FLDB and SEQ services on OFD.
void ofd_seqs_free (const struct lu_env *env, struct ofd_device *ofd)
Free sequence structures on OFD.
int ofd_start_inconsistency_verification_thread (struct ofd_device *ofd)
Start parent FID verification thread.
int ofd_stop_inconsistency_verification_thread (struct ofd_device *ofd)
Stop parent FID verification thread.
int ofd_verify_ff (const struct lu_env *env, struct ofd_object *fo, struct obdo *oa)
Verify parent FID of an object.
int ofd_preprw (const struct lu_env *env, int cmd, struct obd_export *exp, struct obdo *oa, int objcount, struct obd_ioobj *obj, struct niobuf_remote *rnb, int *nr_local, struct niobuf_local *lnb)
Prepare bulk IO requests for processing.
int ofd_commitrw (const struct lu_env *env, int cmd, struct obd_export *exp, struct obdo *oa, int objcount, struct obd_ioobj *obj, struct niobuf_remote *rnb, int npages, struct niobuf_local *lnb, int old_rc)
Commit bulk IO to the storage.
struct thandle * ofd_trans_create (const struct lu_env *env, struct ofd_device *ofd)
Create new transaction in OFD.
int ofd_trans_start (const struct lu_env *env, struct ofd_device *ofd, struct ofd_object *fo, struct thandle *th)
Start transaction in OFD.
void ofd_trans_stop (const struct lu_env *env, struct ofd_device *ofd, struct thandle *th, int rc)
Stop transaction in OFD.
int ofd_txn_stop_cb (const struct lu_env *env, struct thandle *txn, void *cookie)
static void ofd_stats_counter_init (struct lprocfs_stats *stats)
struct ofd_object * ofd_object_find (const struct lu_env *env, struct ofd_device *ofd, const struct lu_fid *fid)
Get OFD object by FID.
int ofd_object_ff_load (const struct lu_env *env, struct ofd_object *fo)
Get FID of parent MDT object.
int ofd_precreate_objects (const struct lu_env *env, struct ofd_device *ofd, u64 id, struct ofd_seq *oseq, int nr, int sync)
Precreate the given number nr of objects in the given sequence oseq.
void ofd_object_put (const struct lu_env *env, struct ofd_object *fo)
Put OFD object reference.
int ofd_attr_set (const struct lu_env *env, struct ofd_object *fo, struct lu_attr *la, struct filter_fid *ff)
Set OFD object attributes.
int ofd_object_punch (const struct lu_env *env, struct ofd_object *fo, __u64 start, __u64 end, struct lu_attr *la, struct filter_fid *ff, struct obdo *oa)
Truncate/punch OFD object.
int ofd_object_destroy (const struct lu_env *, struct ofd_object *, int)
Destroy OFD object.
int ofd_attr_get (const struct lu_env *env, struct ofd_object *fo, struct lu_attr *la)
Get OFD object attributes.
int ofd_attr_handle_ugid (const struct lu_env *env, struct ofd_object *fo, struct lu_attr *la, int is_setattr)
Fix the OFD object ownership.
static struct ofd_object * ofd_object_find_exists (const struct lu_env *env, struct ofd_device *ofd, const struct lu_fid *fid)
static int ofd_grant_param_supp (struct obd_export *exp)
static int ofd_grant_prohibit (struct obd_export *exp, struct ofd_device *ofd)
void ofd_grant_sanity_check (struct obd_device *obd, const char *func)
Perform extra sanity checks for grant accounting.
void ofd_grant_connect (const struct lu_env *env, struct obd_export *exp, struct obd_connect_data *data, bool new_conn)
Handle grant space allocation on client connection & reconnection.
void ofd_grant_discard (struct obd_export *exp)
Release all grant space attached to a given export.
void ofd_grant_prepare_read (const struct lu_env *env, struct obd_export *exp, struct obdo *oa)
Process grant information from incoming bulk read request.
void ofd_grant_prepare_write (const struct lu_env *env, struct obd_export *exp, struct obdo *oa, struct niobuf_remote *rnb, int niocount)
Process grant information from incoming bulk write request.
void ofd_grant_commit (struct obd_export *exp, unsigned long grant_used, int rc)
Release grant space added to the pending counter by ofd_grant_prepare_write().
int ofd_grant_commit_cb_add (struct thandle *th, struct obd_export *exp, unsigned long grant)
Add callback for grant releasing.
long ofd_grant_create (const struct lu_env *env, struct obd_export *exp, int *nr)
Consume grant space reserved for object creation.
int ofd_fmd_init (void)
Initialize FMD subsystem.
void ofd_fmd_exit (void)
Stop FMD subsystem.
struct ofd_mod_data * ofd_fmd_find (struct obd_export *exp, const struct lu_fid *fid)
Find FMD by specified FID with locking.
struct ofd_mod_data * ofd_fmd_get (struct obd_export *exp, const struct lu_fid *fid)
Find FMD by FID or create a new one if none is found.
void ofd_fmd_put (struct obd_export *exp, struct ofd_mod_data *fmd)
Wrapper to drop FMD reference with fed_lock held.
void ofd_fmd_expire (struct obd_export *exp)
Expire FMD entries.
void ofd_fmd_cleanup (struct obd_export *exp)
Remove all entries from FMD list.
int ofd_fid_set_index (const struct lu_env *env, struct ofd_device *ofd, int index)
int ofd_fid_init (const struct lu_env *env, struct ofd_device *ofd)
Start SEQ/FID server on OFD.
int ofd_fid_fini (const struct lu_env *env, struct ofd_device *ofd)
Stop SEQ/FID server on OFD.
int ofd_intent_policy (struct ldlm_namespace *ns, struct ldlm_lock **lockp, void *req_cookie, enum ldlm_mode mode, __u64 flags, void *data)
OFD lock intent policy.
static struct ofd_thread_info * ofd_info (const struct lu_env *env)
static struct ofd_thread_info * ofd_info_init (const struct lu_env *env, struct obd_export *exp)
static struct ofd_thread_info * tsi2ofd_info (struct tgt_session_info *tsi)
static void ofd_slc_set (struct ofd_device *ofd)
static void ofd_prepare_fidea (struct filter_fid *ff, const struct obdo *oa)
Variables
struct lu_context_key ofd_thread_key
struct obd_ops ofd_obd_ops
struct ldlm_valblock_ops ofd_lvbo
Define Documentation
#define COMPAT_BSIZE_SHIFT 12
Definition at line 443 of file ofd_internal.h.
Referenced by ofd_grant_deflate(), ofd_grant_inflate(), ofd_grant_rnb_size(), and ofd_statfs().
#define ofd_fmd_drop (exp, fid) do {} while (0)
Definition at line 484 of file ofd_internal.h.
Referenced by ofd_object_destroy().
#define OFD_FMD_MAX_AGE_DEFAULT msecs_to_jiffies((obd_timeout+10)*MSEC_PER_SEC)
Definition at line 68 of file ofd_internal.h.
Referenced by ofd_init0().
#define OFD_FMD_MAX_NUM_DEFAULT 128
Definition at line 67 of file ofd_internal.h.
Referenced by ofd_init0().
#define OFD_INIT_OBJID 0
Definition at line 46 of file ofd_internal.h.
Referenced by ofd_seq_load().
#define OFD_PRECREATE_BATCH_DEFAULT (OBJ_SUBDIR_COUNT * 4)
Definition at line 47 of file ofd_internal.h.
Referenced by ofd_init0().
#define OFD_PRECREATE_BATCH_SMALL 8
Definition at line 52 of file ofd_internal.h.
Referenced by ofd_init0().
#define OFD_PRECREATE_SMALL_FS (1024ULL * 1024 * 1024)
Definition at line 51 of file ofd_internal.h.
Referenced by ofd_init0().
#define OFD_SOFT_SYNC_LIMIT_DEFAULT 16
Definition at line 70 of file ofd_internal.h.
Referenced by ofd_init0().
#define OFD_VALID_FLAGS
Value:
(LA_TYPE | LA_MODE | LA_SIZE | LA_BLOCKS | \
                         LA_BLKSIZE | LA_ATIME | LA_MTIME | LA_CTIME)
Definition at line 55 of file ofd_internal.h.
Referenced by ofd_commitrw(), ofd_echo_getattr(), ofd_getattr_hdl(), ofd_setattr_hdl(), and ofd_sync_hdl().
Enumeration Type Documentation
anonymous enum
Enumerator:
LPROC_OFD_STATS_READ
LPROC_OFD_STATS_WRITE
LPROC_OFD_STATS_GETATTR
LPROC_OFD_STATS_SETATTR
LPROC_OFD_STATS_PUNCH
LPROC_OFD_STATS_SYNC
LPROC_OFD_STATS_DESTROY
LPROC_OFD_STATS_CREATE
LPROC_OFD_STATS_STATFS
LPROC_OFD_STATS_GET_INFO
LPROC_OFD_STATS_SET_INFO
LPROC_OFD_STATS_QUOTACTL
LPROC_OFD_STATS_LAST
Definition at line 73 of file ofd_internal.h.
Function Documentation
static struct dt_object* fo2dt (struct ofd_object * obj) [static, read]
Definition at line 238 of file ofd_internal.h.
References ofd_object::ofo_obj.
int ofd_attr_get (const struct lu_env * env, struct ofd_object * fo, struct lu_attr * la)
Get OFD object attributes.
This function gets OFD object regular attributes. It is used to serve incoming request as well as for local OFD purposes.
Parameters:
[in] env execution environment
[in] fo OFD object
[in] la object attributes
Return values:
0 if successful
negative value on error
Definition at line 778 of file ofd_objects.c.
References dt_attr_get(), ENTRY, ofd_object_child(), ofd_object_exists(), and RETURN.
Referenced by ofd_echo_getattr(), ofd_getattr_hdl(), ofd_lvbo_init(), ofd_lvbo_update(), and ofd_sync_hdl().
int ofd_attr_handle_ugid (const struct lu_env * env, struct ofd_object * fo, struct lu_attr * la, int is_setattr)
Fix the OFD object ownership.
If the object still has SUID+SGID bits set, meaning that it was precreated by the MDT before it was assigned to any file, (see ofd_precreate_objects()) then we will accept the UID+GID if sent by the client for initializing the ownership of this object. We only allow this to happen once (so clear these bits) and later only allow setattr.
Parameters:
[in] env execution environment
[in] fo OFD object
[in] la object attributes
[in] is_setattr was this function called from setattr or not
Return values:
0 if successful
negative value on error
Definition at line 434 of file ofd_objects.c.
References dt_attr_get(), ENTRY, ofd_thread_info::fti_attr2, LA_GID, lu_attr::la_mode, LA_MODE, LA_UID, lu_attr::la_valid, LASSERT, ofd_info(), ofd_object_child(), and RETURN.
Referenced by ofd_attr_set(), ofd_object_punch(), and ofd_write_attr_set().
int ofd_attr_set (const struct lu_env * env, struct ofd_object * fo, struct lu_attr * la, struct filter_fid * ff)
Set OFD object attributes.
This function sets OFD object attributes taken from incoming request. It sets not only regular attributes but also XATTR_NAME_FID extended attribute if needed. The "fid" xattr allows the object's MDT parent inode to be found and verified by LFSCK and other tools in case of inconsistency.
Parameters:
[in] env execution environment
[in] fo OFD object
[in] la object attributes
[in] ff filter_fid structure, contains additional attributes
Return values:
0 if successful
negative value on error
Definition at line 491 of file ofd_objects.c.
References dt_attr_set(), dt_declare_attr_set(), dt_declare_xattr_set(), dt_xattr_set(), ENTRY, lu_fid::f_oid, lu_fid::f_seq, filter_fid::ff_parent, ofd_mod_data::fmd_mactime_xid, ofd_thread_info::fti_buf, ofd_thread_info::fti_exp, ofd_thread_info::fti_xid, GOTO, LA_ATIME, LA_CTIME, LA_MTIME, LA_SIZE, lu_attr::la_valid, lu_buf::lb_buf, lu_buf::lb_len, le32_to_cpu, le64_to_cpu, lu_object_header::loh_fid, ofd_attr_handle_ugid(), ofd_fmd_get(), ofd_fmd_put(), ofd_info(), ofd_obj2dev(), ofd_object_child(), ofd_object_exists(), ofd_object_ff_load(), ofd_trans_create(), ofd_trans_start(), ofd_trans_stop(), ofd_version_get_check(), ofd_write_lock(), ofd_write_unlock(), ofd_object::ofo_header, ofd_object::ofo_pfid, stop, and XATTR_NAME_FID.
Referenced by ofd_echo_setattr(), and ofd_setattr_hdl().
int ofd_commitrw (const struct lu_env * env, int cmd, struct obd_export * exp, struct obdo * oa, int objcount, struct obd_ioobj * obj, struct niobuf_remote * rnb, int npages, struct niobuf_local * lnb, int old_rc)
Commit bulk IO to the storage.
This is companion function to the ofd_preprw(). It finishes bulk IO request processing by committing buffers to the storage (WRITE) and/or freeing those buffers (read/write). See ofd_commitrw_read() and ofd_commitrw_write() for details about each type of IO.
Parameters:
[in] env execution environment
[in] cmd IO type (READ/WRITE)
[in] exp OBD export of client
[in] oa OBDO structure from client
[in] objcount always 1
[in] obj object data
[in] rnb remote buffers
[in] npages number of local buffers
[in] lnb local buffers
[in] old_rc result of processing at this point
Return values:
0 on successful commit
negative value on error
Definition at line 1163 of file ofd_io.c.
References __u64, ofd_mod_data::fmd_mactime_xid, ofd_thread_info::fti_attr, ofd_thread_info::fti_mds_fid, ofd_thread_info::fti_resid, ofd_thread_info::fti_xid, la_from_obdo(), LA_GID, LA_UID, LASSERT, LBUG, LDLM_EXTENT, ldlm_res_lvbo_update(), ldlm_resource_get(), ldlm_resource_putref(), ldlm_valblock_ops::lvbo_update, ldlm_namespace::ns_lvbo, obdo::o_flags, obdo::o_oi, obdo::o_valid, OBD_BRW_OVER_GRPQUOTA, OBD_BRW_OVER_USRQUOTA, OBD_BRW_READ, OBD_BRW_WRITE, OBD_FL_NO_GRPQUOTA, OBD_FL_NO_USRQUOTA, OBD_MD_FLATIME, OBD_MD_FLCTIME, OBD_MD_FLFID, OBD_MD_FLFLAGS, OBD_MD_FLGID, OBD_MD_FLGRPQUOTA, OBD_MD_FLMTIME, OBD_MD_FLUID, OBD_MD_FLUSRQUOTA, obdo_from_la(), ofd_commitrw_read(), ofd_commitrw_write(), ofd_exp(), ofd_fmd_find(), ofd_fmd_put(), ofd_info(), ofd_device::ofd_namespace, ofd_prepare_fidea(), OFD_VALID_FLAGS, ost_id::oi_fid, ost_fid_build_resid(), and RETURN.
static void ofd_counter_incr (struct obd_export * exp, int opcode, char * jobid, long amount) [inline, static]
Definition at line 89 of file ofd_internal.h.
References exp_connect_flags(), obd_export::exp_nid_stats, obd_export::exp_obd, lprocfs_counter_add(), lprocfs_job_stats_log(), nid_stat::nid_stats, OBD_CONNECT_JOBSTATS, obd_device::obd_stats, and obd_device::u.
Referenced by ofd_create_hdl(), ofd_destroy_hdl(), ofd_echo_setattr(), ofd_get_info_hdl(), ofd_getattr_hdl(), ofd_preprw_read(), ofd_preprw_write(), ofd_punch_hdl(), ofd_quotactl(), ofd_set_info_hdl(), ofd_setattr_hdl(), ofd_statfs_hdl(), and ofd_sync_hdl().
int ofd_destroy_by_fid (const struct lu_env * env, struct ofd_device * ofd, const struct lu_fid * fid, int orphan)
Destroy OFD object by its FID.
Supplemental function to destroy object by FID, it is used by request handler and by ofd_echo_destroy() below to find object by FID, lock it and call ofd_object_destroy() finally.
Parameters:
[in] env execution environment
[in] ofd OFD device
[in] fid FID of object
[in] orphan set if object being destroyed is an orphan
Return values:
0 if successful
negative value on error
Definition at line 984 of file ofd_obd.c.
References __u64, ELDLM_OK, ENTRY, EXIT, ofd_thread_info::fti_resid, ldlm_policy_data::l_extent, LASSERT, LCK_PW, ldlm_blocking_ast(), ldlm_cli_enqueue_local(), ldlm_completion_ast(), LDLM_EXTENT, LDLM_FL_AST_DISCARD_DATA, ldlm_lock_decref(), LVB_T_NONE, OBD_OBJECT_EOF, ofd_info(), ofd_device::ofd_namespace, ofd_object_destroy(), ofd_object_find_exists(), ofd_object_put(), ost_fid_build_resid(), and RETURN.
Referenced by ofd_destroy_hdl(), ofd_echo_destroy(), and ofd_orphans_destroy().
static struct ofd_device* ofd_dev (struct lu_device * d) [static, read]
Definition at line 197 of file ofd_internal.h.
References dt_device::dd_lu_dev, and ofd_device::ofd_dt_dev.
Referenced by ofd_device_fini(), ofd_device_free(), ofd_exp(), ofd_grant_sanity_check(), ofd_health_check(), ofd_obd_connect(), ofd_obd_postrecov(), ofd_obd_reconnect(), ofd_obj2dev(), ofd_object_init(), ofd_prepare(), ofd_process_config(), and ofd_recovery_complete().
static struct ofd_device* ofd_exp (struct obd_export * exp) [static, read]
Definition at line 207 of file ofd_internal.h.
References obd_export::exp_obd, obd_device::obd_lu_dev, and ofd_dev().
Referenced by ofd_commitrw(), ofd_create_hdl(), ofd_destroy_export(), ofd_destroy_hdl(), ofd_echo_create(), ofd_echo_destroy(), ofd_echo_getattr(), ofd_echo_setattr(), ofd_fmd_expire_nolock(), ofd_fmd_find_nolock(), ofd_fmd_get(), ofd_get_info(), ofd_get_info_hdl(), ofd_getattr_hdl(), ofd_grant_alloc(), ofd_grant_check(), ofd_grant_commit(), ofd_grant_connect(), ofd_grant_create(), ofd_grant_discard(), ofd_grant_incoming(), ofd_grant_prepare_read(), ofd_grant_prepare_write(), ofd_grant_shrink(), ofd_grant_space_left(), ofd_grant_statfs(), ofd_iocontrol(), ofd_ladvise_hdl(), ofd_obd_disconnect(), ofd_parse_connect_data(), ofd_preprw(), ofd_punch_hdl(), ofd_setattr_hdl(), ofd_statfs(), and ofd_sync_hdl().
int ofd_fid_fini (const struct lu_env * env, struct ofd_device * ofd)
Stop SEQ/FID server on OFD.
Parameters:
[in] env execution environment
[in] ofd OFD device
Return values:
0 if successful
negative value on error
Definition at line 802 of file ofd_dev.c.
References ofd_device::ofd_seq_site, and seq_site_fini().
Referenced by ofd_seqs_fini(), and ofd_seqs_init().
int ofd_fid_init (const struct lu_env * env, struct ofd_device * ofd)
Start SEQ/FID server on OFD.
The SEQ/FID server on OFD is needed to allocate FIDs for new objects. It also connects to the master server to get own FID sequence (SEQ) range to this particular OFD. Typically that happens when the OST is first formatted or in the rare case that it exhausts the local sequence range.
The sequence range is allocated out to the MDTs for OST object allocations, and not directly to the clients.
Parameters:
[in] env execution environment
[in] ofd OFD device
Return values:
0 if successful
negative value on error
Definition at line 824 of file ofd_dev.c.
References CERROR, dt_device::dd_lu_dev, GOTO, lu_site::ld_seq_site, lu_device::ld_site, lr_server_data::lsd_osd_index, lu_seq_range::lsr_index, lu_server_seq::lss_space, LUSTRE_SEQ_DATA, LUSTRE_SEQ_SERVER, lu_target::lut_lsd, name, OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, ofd_device::ofd_dt_dev, ofd_device::ofd_lut, ofd_name(), ofd_device::ofd_osd, ofd_device::ofd_seq_site, seq_client_fini(), seq_client_init(), seq_server_fini(), seq_server_init(), seq_server_set_cli(), seq_server_site::ss_client_seq, seq_server_site::ss_lu, seq_server_site::ss_node_id, and seq_server_site::ss_server_seq.
Referenced by ofd_seqs_init().
int ofd_fid_set_index (const struct lu_env * env, struct ofd_device * ofd, int index)
int ofd_fiemap_get (const struct lu_env * env, struct ofd_device * ofd, struct lu_fid * fid, struct fiemap * fiemap)
Get FIEMAP (FIle Extent MAPping) for object with the given FID.
This function returns a list of extents which describes how a file's blocks are laid out on the disk.
Parameters:
[in] env execution environment
[in] ofd OFD device
[in] fid FID of object
[in] fiemap fiemap structure to fill with data
Return values:
0 if fiemap is filled with data successfully
negative value on error
Definition at line 973 of file ofd_dev.c.
References CERROR, DFID, dt_fiemap_get(), ofd_name(), ofd_object_child(), ofd_object_exists(), ofd_object_find(), ofd_object_put(), ofd_read_lock(), ofd_read_unlock(), and PFID.
Referenced by ofd_get_info(), and ofd_get_info_hdl().
void ofd_fmd_cleanup (struct obd_export * exp)
Remove all entries from FMD list.
Cleanup function to free all FMD enries on the given export.
Parameters:
[in] exp OBD export
Definition at line 300 of file ofd_fmd.c.
References CDEBUG, D_INFO, filter_export_data::fed_lock, filter_export_data::fed_mod_list, ofd_mod_data::fmd_list, ofd_mod_data::fmd_refcount, list_del_init(), list_for_each_entry_safe, and ofd_fmd_put_nolock().
Referenced by ofd_destroy_export().
void ofd_fmd_exit (void)
Stop FMD subsystem.
This function is called upon OFD cleanup and destroy memory used by FMD entries.
Definition at line 340 of file ofd_fmd.c.
References ll_fmd_cachep.
Referenced by ofd_exit().
void ofd_fmd_expire (struct obd_export * exp)
Expire FMD entries.
This is a wrapper to call ofd_fmd_expire_nolock() with the required lock.
Parameters:
[in] exp OBD export
Definition at line 140 of file ofd_fmd.c.
References filter_export_data::fed_lock, and ofd_fmd_expire_nolock().
Referenced by ofd_ping().
struct ofd_mod_data* ofd_fmd_find (struct obd_export * exp, const struct lu_fid * fid) [read]
Find FMD by specified FID with locking.
Wrapper to the ofd_fmd_find_nolock() with correct locks.
Parameters:
[in] exp OBD export
[in] fid FID of FMD to find
Return values:
struct ofd_mod_data found by FID
NULL indicates FMD is not found
Definition at line 199 of file ofd_fmd.c.
References filter_export_data::fed_lock, ofd_mod_data::fmd_refcount, and ofd_fmd_find_nolock().
Referenced by ofd_commitrw().
struct ofd_mod_data* ofd_fmd_get (struct obd_export * exp, const struct lu_fid * fid) [read]
Find FMD by FID or create a new one if none is found.
It is possible for this function to return NULL under memory pressure, or if the passed FID is zero (which will only cause old entries to expire). Currently this is not fatal because any FMD state is transient and may also be freed when it gets sufficiently old.
Parameters:
[in] exp OBD export
[in] fid FID of FMD to find
Return values:
struct ofd_mod_data found by FID
NULL indicates FMD is not found
Definition at line 228 of file ofd_fmd.c.
References cfs_time_add(), cfs_time_current(), filter_export_data::fed_lock, filter_export_data::fed_mod_count, filter_export_data::fed_mod_list, ofd_mod_data::fmd_expire, ofd_mod_data::fmd_refcount, list_add_tail(), ll_fmd_cachep, now(), OBD_SLAB_ALLOC_PTR, OBD_SLAB_FREE_PTR, ofd_exp(), ofd_fmd_find_nolock(), and ofd_device::ofd_fmd_max_age.
Referenced by ofd_attr_set(), and ofd_object_punch().
int ofd_fmd_init (void)
Initialize FMD subsystem.
This function is called upon OFD setup and initialize memory to be used by FMD entries.
Definition at line 323 of file ofd_fmd.c.
References ll_fmd_cachep.
Referenced by ofd_init().
void ofd_fmd_put (struct obd_export * exp, struct ofd_mod_data * fmd)
Wrapper to drop FMD reference with fed_lock held.
Parameters:
[in] exp OBD export
[in] fmd FMD to put
Definition at line 84 of file ofd_fmd.c.
References filter_export_data::fed_lock, and ofd_fmd_put_nolock().
Referenced by ofd_attr_set(), ofd_commitrw(), and ofd_object_punch().
void ofd_fs_cleanup (const struct lu_env * env, struct ofd_device * ofd)
Cleanup service files on OFD.
This function syncs whole OFD device and close "health check" file.
Parameters:
[in] env execution environment
[in] ofd OFD device
Definition at line 666 of file ofd_fs.c.
References CWARN, dt_object::do_lu, dt_sync(), ENTRY, EXIT, lu_object_put(), ofd_device::ofd_health_check_file, ofd_name(), ofd_device::ofd_osd, and ofd_seqs_fini().
Referenced by ofd_fini(), and ofd_init0().
int ofd_fs_setup (const struct lu_env * env, struct ofd_device * ofd, struct obd_device * obd)
Initialize storage for the OFD.
This function sets up service files for OFD. Currently, the only service file is "health_check".
Parameters:
[in] env execution environment
[in] ofd OFD device
[in] obd OBD device (unused now)
Return values:
0 on successful setup
negative value on error
Definition at line 621 of file ofd_fs.c.
References dt_object_format::dof_type, dt_find_or_create(), dt_mode_to_dft(), ENTRY, ofd_thread_info::fti_attr, ofd_thread_info::fti_dof, ofd_thread_info::fti_fid, GOTO, lu_attr::la_mode, LA_MODE, lu_attr::la_valid, lu_local_obj_fid(), OBD_FAIL_CHECK, OBD_FAIL_MDS_FS_SETUP, ofd_device::ofd_health_check_file, OFD_HEALTH_CHECK_OID, ofd_info(), ofd_device::ofd_osd, ofd_seqs_fini(), ofd_seqs_init(), and RETURN.
Referenced by ofd_init0().
void ofd_grant_commit (struct obd_export * exp, unsigned long pending, int rc)
Release grant space added to the pending counter by ofd_grant_prepare_write().
Update pending grant counter once buffers have been written to the disk.
Parameters:
[in] exp export of the client which sent the request
[in] pending amount of reserved space to be released
[in] rc return code of pre-commit operations
Definition at line 1264 of file ofd_grant.c.
References CERROR, ENTRY, EXIT, obd_export::exp_client_uuid, obd_export::exp_obd, LBUG, LPU64, min_t, obd_device::obd_name, ofd_device::ofd_blockbits, ofd_exp(), ofd_device::ofd_grant_lock, ofd_device::ofd_osfs, ofd_device::ofd_osfs_inflight, ofd_device::ofd_osfs_lock, ofd_device::ofd_statfs_inflight, ofd_device::ofd_tot_granted, ofd_device::ofd_tot_pending, obd_statfs::os_bavail, RETURN_EXIT, and obd_uuid::uuid.
Referenced by ofd_commitrw_write(), ofd_create_hdl(), ofd_echo_create(), ofd_grant_commit_cb(), and ofd_preprw_write().
int ofd_grant_commit_cb_add (struct thandle * th, struct obd_export * exp, unsigned long granted)
Add callback for grant releasing.
Register a commit callback to release grant space.
Parameters:
[in] th transaction handle
[in] exp OBD export of client
[in] granted amount of grant space to be released upon commit
Return values:
0 on successful callback adding
negative value on error
Definition at line 1369 of file ofd_grant.c.
References class_export_cb_get, class_export_cb_put, dt_txn_commit_cb::dcb_func, dt_txn_commit_cb::dcb_linkage, dt_txn_commit_cb::dcb_name, dt_trans_cb_add(), ENTRY, INIT_LIST_HEAD, OBD_ALLOC_PTR, OBD_FREE_PTR, ofd_grant_commit_cb(), ofd_grant_cb::ogc_cb, ofd_grant_cb::ogc_exp, ofd_grant_cb::ogc_granted, RETURN, and strlcpy().
Referenced by ofd_commitrw_write().
void ofd_grant_connect (const struct lu_env * env, struct obd_export * exp, struct obd_connect_data * data, bool new_conn)
Handle grant space allocation on client connection & reconnection.
A new non-readonly connection gets an initial grant allocation equals to ofd_grant_chunk() (i.e. twice the max BRW size in most of the cases). On reconnection, grant counters between client & OST are resynchronized and additional space might be granted back if possible.
Parameters:
[in] env LU environment provided by the caller
[in] exp client's export which is (re)connecting
[in,out] data obd_connect_data structure sent by the client in the connect request
[in] new_conn must set to true if this is a new connection and false for a reconnection
Definition at line 868 of file ofd_grant.c.
References CDEBUG, D_CACHE, EXIT, obd_export::exp_client_uuid, obd_export::exp_obd, filter_export_data::fed_dirty, filter_export_data::fed_grant, LPU64, OBD_CONNECT_GRANT, OBD_CONNECT_GRANT_PARAM, obd_device::obd_name, obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_grant, OCD_HAS_FLAG, ofd_exp(), ofd_grant_alloc(), ofd_grant_chunk(), ofd_device::ofd_grant_compat_disable, ofd_grant_deflate(), ofd_grant_inflate(), ofd_device::ofd_grant_lock, ofd_grant_space_left(), ofd_grant_statfs(), ofd_device::ofd_tot_dirty, ofd_device::ofd_tot_granted_clients, RETURN_EXIT, and obd_uuid::uuid.
Referenced by ofd_parse_connect_data(), and ofd_recovery_complete().
long ofd_grant_create (const struct lu_env * env, struct obd_export * exp, int * nr)
Consume grant space reserved for object creation.
Grant space is allocated to the local self export for object precreation. This is required to prevent object precreation from consuming grant space allocated to client nodes for the data writeback cache. This function consumes enough space to create nr objects and allocates more grant space to the self export for future precreation requests, if possible.
Parameters:
[in] env LU environment provided by the caller
[in] exp export holding the grant space for precreation (= self export currently)
[in] nr number of objects to be created
Return values:
>= 0 amount of grant space allocated to the precreate request
-ENOSPC on failure
Definition at line 1172 of file ofd_grant.c.
References CDEBUG, D_RPCTRACE, dt_device_param::ddp_inodespace, ENTRY, obd_export::exp_obd, filter_export_data::fed_grant, filter_export_data::fed_pending, LASSERT, LPU64, obd_device::obd_recovering, ofd_device::ofd_blockbits, ofd_device::ofd_dt_conf, ofd_exp(), ofd_grant_alloc(), ofd_grant_chunk(), ofd_device::ofd_grant_lock, ofd_grant_space_left(), ofd_grant_statfs(), ofd_name(), ofd_device::ofd_osfs, ofd_device::ofd_tot_granted, ofd_device::ofd_tot_pending, obd_statfs::os_bavail, obd_statfs::os_blocks, OST_MAX_PRECREATE, and RETURN.
Referenced by ofd_create_hdl(), and ofd_echo_create().
void ofd_grant_discard (struct obd_export * exp)
Release all grant space attached to a given export.
Remove a client from the grant accounting totals. We also remove the export from the obd device under the osfs and dev locks to ensure that the ofd_grant_sanity_check() calculations are always valid. The client should do something similar when it invalidates its import.
Parameters:
[in] exp client's export to remove from grant accounting
Definition at line 947 of file ofd_grant.c.
References obd_export::exp_client_uuid, obd_export::exp_obd, filter_export_data::fed_dirty, filter_export_data::fed_grant, filter_export_data::fed_pending, LASSERTF, LPU64, obd_device::obd_name, ofd_exp(), ofd_device::ofd_grant_lock, ofd_device::ofd_tot_dirty, ofd_device::ofd_tot_granted, ofd_device::ofd_tot_pending, and obd_uuid::uuid.
Referenced by ofd_destroy_export(), and ofd_obd_disconnect().
static int ofd_grant_param_supp (struct obd_export * exp) [inline, static]
Definition at line 435 of file ofd_internal.h.
References exp_connect_flags(), and OBD_CONNECT_GRANT_PARAM.
Referenced by ofd_grant_check(), ofd_grant_chunk(), ofd_grant_incoming(), ofd_grant_prepare_read(), ofd_grant_prepare_write(), ofd_grant_prohibit(), ofd_grant_rnb_size(), and ofd_statfs().
void ofd_grant_prepare_read (const struct lu_env * env, struct obd_export * exp, struct obdo * oa)
Process grant information from incoming bulk read request.
Extract grant information packed in obdo structure (OBD_MD_FLGRANT set in o_valid). Bulk reads usually comes with grant announcements (number of dirty blocks, remaining amount of grant space, ...) and could also include a grant shrink request. Unlike bulk write, no additional grant space is returned on bulk read request.
Parameters:
[in] env is the lu environment provided by the caller
[in] exp is the export of the client which sent the request
[in,out] oa is the incoming obdo sent by the client
Definition at line 988 of file ofd_grant.c.
References ENTRY, EXIT, obdo::o_flags, obdo::o_grant, obdo::o_valid, OBD_FL_SHRINK_GRANT, OBD_MD_FLFLAGS, OBD_MD_FLGRANT, ofd_exp(), ofd_grant_chunk(), ofd_grant_deflate(), ofd_grant_incoming(), ofd_device::ofd_grant_lock, ofd_grant_param_supp(), ofd_grant_shrink(), ofd_grant_space_left(), ofd_grant_statfs(), and RETURN_EXIT.
Referenced by ofd_preprw(), ofd_preprw_write(), and ofd_set_info_hdl().
void ofd_grant_prepare_write (const struct lu_env * env, struct obd_export * exp, struct obdo * oa, struct niobuf_remote * rnb, int niocount)
Process grant information from incoming bulk write request.
This function extracts client's grant announcements from incoming bulk write request and attempts to allocate grant space for network buffers that need it (i.e. OBD_BRW_FROM_GRANT not set in rnb_fags). Network buffers which aren't granted the OBD_BRW_GRANTED flag should not proceed further and should fail with -ENOSPC. Whenever possible, additional grant space will be returned to the client in the bulk write reply. ofd_grant_prepare_write() must be called before writting any buffers to the backend storage. This function works in pair with ofd_grant_commit() which must be invoked once all buffers have been written to disk in order to release space from the pending grant counter.
Parameters:
[in] env LU environment provided by the caller
[in] exp export of the client which sent the request
[in] oa incoming obdo sent by the client
[in] rnb list of network buffers
[in] niocount number of network buffers in the list
Definition at line 1068 of file ofd_grant.c.
References CDEBUG, D_CACHE, dt_sync(), ENTRY, EXIT, obd_export::exp_obd, obdo::o_flags, obdo::o_grant, obdo::o_valid, OBD_BRW_FROM_GRANT, OBD_FL_SHRINK_GRANT, OBD_MD_FLFLAGS, OBD_MD_FLGRANT, obd_device::obd_name, obd_device::obd_recovering, ofd_exp(), ofd_grant_alloc(), ofd_grant_check(), ofd_grant_chunk(), ofd_grant_deflate(), ofd_grant_incoming(), ofd_device::ofd_grant_lock, ofd_grant_param_supp(), ofd_grant_shrink(), ofd_grant_space_left(), ofd_grant_statfs(), ofd_device::ofd_osd, and RETURN_EXIT.
Referenced by ofd_preprw_write().
static int ofd_grant_prohibit (struct obd_export * exp, struct ofd_device * ofd) [inline, static]
Definition at line 445 of file ofd_internal.h.
References obd_device::obd_self_export, ofd_device::ofd_grant_compat_disable, ofd_grant_param_supp(), and ofd_obd().
Referenced by ofd_grant_alloc().
void ofd_grant_sanity_check (struct obd_device * obd, const char * func)
Perform extra sanity checks for grant accounting.
This function scans the export list, sanity checks per-export grant counters and verifies accuracy of global grant accounting. If an inconsistency is found, a CERROR is printed with the function name that was passed as argument. LBUG is only called in case of serious counter corruption (i.e. value larger than the device size). Those sanity checks can be pretty expensive and are disabled if the OBD device has more than 100 connected exports.
Parameters:
[in] obd OBD device for which grant accounting should be verified
[in] func caller's function name
Definition at line 147 of file ofd_grant.c.
References CDEBUG, CDEBUG_LIMIT, CERROR, D_CACHE, D_ERROR, error, obd_export::exp_client_uuid, obd_export::exp_obd_chain, filter_export_data::fed_dirty, filter_export_data::fed_grant, filter_export_data::fed_pending, LBUG, list_empty(), list_for_each_entry, LPU64, obd_device::obd_dev_lock, obd_device::obd_exports, obd_device::obd_lu_dev, obd_device::obd_name, obd_device::obd_num_exports, obd_device::obd_self_export, obd_device::obd_unlinked_exports, ofd_device::ofd_blockbits, ofd_dev(), ofd_device::ofd_grant_lock, ofd_device::ofd_osfs, ofd_device::ofd_tot_dirty, ofd_device::ofd_tot_granted, ofd_device::ofd_tot_pending, obd_statfs::os_blocks, and obd_uuid::uuid.
Referenced by ofd_destroy_export(), ofd_obd_disconnect(), and ofd_statfs().
static struct ofd_thread_info* ofd_info (const struct lu_env * env) [static, read]
Definition at line 501 of file ofd_internal.h.
References LASSERT, lu_context_key_get(), lu_env_refill(), and ofd_thread_key.
Referenced by ofd_attr_handle_ugid(), ofd_attr_set(), ofd_commitrw(), ofd_create_hdl(), ofd_destroy_by_fid(), ofd_fs_setup(), ofd_grant_check(), ofd_grant_statfs(), ofd_info_init(), ofd_init0(), ofd_object_destroy(), ofd_object_ff_load(), ofd_object_punch(), ofd_orphans_destroy(), ofd_precreate_objects(), ofd_recovery_complete(), ofd_seq_last_oid_write(), ofd_seq_load(), ofd_stack_init(), ofd_trans_create(), ofd_write_attr_set(), and tsi2ofd_info().
static struct ofd_thread_info* ofd_info_init (const struct lu_env * env, struct obd_export * exp) [static, read]
Definition at line 511 of file ofd_internal.h.
References ofd_thread_info::fti_attr, ofd_thread_info::fti_env, ofd_thread_info::fti_exp, ofd_thread_info::fti_pre_version, lu_attr::la_valid, LASSERT, and ofd_info().
Referenced by ofd_echo_create(), ofd_echo_destroy(), ofd_echo_getattr(), ofd_echo_setattr(), ofd_get_info(), ofd_health_check(), ofd_init0(), ofd_ladvise_hdl(), ofd_lvbo_init(), ofd_lvbo_update(), ofd_obd_postrecov(), ofd_prepare(), and ofd_preprw().
int ofd_intent_policy (struct ldlm_namespace * ns, struct ldlm_lock ** lockp, void * req_cookie, enum ldlm_mode mode, __u64 flags, void * data)
OFD lock intent policy.
This defines ldlm_namespace::ns_policy interface for OFD. Intent policy is called when lock has an intent, for OFD that means glimpse lock and policy fills Lock Value Block (LVB).
If already granted lock is found it will be placed in lockp and returned back to caller function.
Parameters:
[in] ns namespace
[in,out] lockp pointer to the lock
[in] req_cookie incoming request
[in] mode LDLM mode
[in] flags LDLM flags
[in] data opaque data, not used in OFD policy
Return values:
ELDLM_LOCK_REPLACED if already granted lock was found and placed in lockp
ELDLM_LOCK_ABORTED in other cases except error
negative value on error
Definition at line 129 of file ofd_dlm.c.
References __u64, check_res_locked(), DLM_LOCKREPLY_OFF, DLM_REPLY_REC_OFF, ELDLM_LOCK_ABORTED, ELDLM_LOCK_REPLACED, ENTRY, obd_export::exp_libclient, ldlm_glimpse_work::gl_desc, ldlm_glimpse_work::gl_flags, ldlm_glimpse_work::gl_list, ldlm_glimpse_work::gl_lock, INIT_LIST_HEAD, interval_iterate_reverse(), ldlm_lock::l_export, ldlm_lock::l_lvb_type, ldlm_lock::l_resource, LASSERT, LCK_MODE_NUM, LCK_PR, LDLM_FL_BLOCK_NOWAIT, LDLM_FL_RESENT, LDLM_GL_WORK_NOFREE, LDLM_ITER_CONTINUE, LDLM_LOCK_GET, LDLM_LOCK_RELEASE, ldlm_res_lvbo_update(), ldlm_res_to_ns(), ldlm_resource_unlink_lock(), ofd_intent_args::liblustre, list_add_tail(), list_empty(), ldlm_interval_tree::lit_mode, ldlm_interval_tree::lit_root, ldlm_reply::lock_policy_res1, lock_res(), ldlm_resource::lr_itree, ldlm_resource::lr_lvb_data, lustre_msg_buf(), lustre_pack_reply(), ost_lvb::lvb_size, LVB_T_OST, MSG_PTLRPC_BODY_OFF, OBD_FAIL_CHECK, OBD_FAIL_LDLM_AGL_DELAY, OBD_FAIL_LDLM_AGL_NOLOCK, OBD_FAIL_LDLM_GLIMPSE, OBD_FAIL_TIMEOUT, ofd_intent_cb(), ptlrpc_body, ptlrpc_status_hton(), RETURN, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_status, ofd_intent_args::size, unlock_res(), and ofd_intent_args::victim.
Referenced by ofd_init0().
static char* ofd_name (struct ofd_device * ofd) [inline, static]
Definition at line 212 of file ofd_internal.h.
References dt_device::dd_lu_dev, lu_device::ld_obd, obd_device::obd_name, and ofd_device::ofd_dt_dev.
Referenced by ofd_connect_to_next(), ofd_create_hdl(), ofd_destroy_hdl(), ofd_echo_create(), ofd_echo_destroy(), ofd_echo_setattr(), ofd_fid_init(), ofd_fiemap_get(), ofd_fs_cleanup(), ofd_get_info(), ofd_get_info_hdl(), ofd_grant_create(), ofd_inconsistency_verify_one(), ofd_lfsck_out_notify(), ofd_lvbo_update(), ofd_orphans_destroy(), ofd_postrecov(), ofd_precreate_objects(), ofd_preprw(), ofd_preprw_write(), ofd_register_lwp_callback(), ofd_register_seq_exp(), ofd_seq_last_oid_write(), ofd_seq_load(), ofd_seqs_fini(), ofd_seqs_init(), ofd_setattr_hdl(), and ofd_start_inconsistency_verification_thread().
static struct obd_device* ofd_obd (struct ofd_device * ofd) [static, read]
Definition at line 202 of file ofd_internal.h.
References dt_device::dd_lu_dev, lu_device::ld_obd, and ofd_device::ofd_dt_dev.
Referenced by ofd_create_hdl(), ofd_echo_create(), ofd_export_stats_init(), ofd_fini(), ofd_grant_chunk(), ofd_grant_prohibit(), ofd_iocontrol(), ofd_lfsck_out_notify(), ofd_obd_disconnect(), ofd_prepare(), ofd_process_config(), ofd_procfs_add_brw_stats_symlink(), ofd_procfs_fini(), ofd_procfs_init(), and ofd_stack_fini().
int ofd_obd_disconnect (struct obd_export * exp)
Disconnect a connected client.
This function terminates the client connection. The client export is disconnected (cleaned up) and client data on persistent storage is removed.
Parameters:
[in] exp OBD export
Return values:
0 if successful
negative value on error
Definition at line 411 of file ofd_obd.c.
References class_export_get(), class_export_put(), ENTRY, obd_export::exp_failed, obd_export::exp_flags, obd_export::exp_obd, GOTO, LASSERT, LCT_DT_THREAD, lu_env_fini(), lu_env_init(), nodemap_del_member(), obd_device::obd_fail, OBD_OPT_FORCE, obd_device::obd_replayable, ofd_exp(), ofd_grant_discard(), ofd_grant_sanity_check(), ofd_obd(), RETURN, and tgt_client_del().
Referenced by ofd_create_hdl().
static struct ofd_object* ofd_obj (struct lu_object * o) [static, read]
Definition at line 225 of file ofd_internal.h.
References dt_object::do_lu, and ofd_object::ofo_obj.
Referenced by ofd_object_find(), and ofd_object_free().
static struct ofd_device* ofd_obj2dev (const struct ofd_object * fo) [static, read]
Definition at line 250 of file ofd_internal.h.
References dt_object::do_lu, lu_object::lo_dev, ofd_dev(), and ofd_object::ofo_obj.
Referenced by ofd_add_inconsistency_item(), ofd_attr_set(), ofd_object_destroy(), and ofd_object_punch().
static struct dt_object* ofd_object_child (struct ofd_object * _obj) [static, read]
Definition at line 243 of file ofd_internal.h.
References dt_object::do_lu, and lu_object_next().
Referenced by ofd_attr_get(), ofd_attr_handle_ugid(), ofd_attr_set(), ofd_commitrw_read(), ofd_commitrw_write(), ofd_echo_getattr(), ofd_fiemap_get(), ofd_getattr_hdl(), ofd_ioc_get_obj_version(), ofd_object_destroy(), ofd_object_ff_load(), ofd_object_punch(), ofd_precreate_objects(), ofd_preprw_read(), ofd_preprw_write(), ofd_read_lock(), ofd_read_unlock(), ofd_sync_hdl(), ofd_trans_start(), ofd_version_get_check(), ofd_write_attr_set(), ofd_write_lock(), and ofd_write_unlock().
int ofd_object_destroy (const struct lu_env * env, struct ofd_object * fo, int orphan)
Destroy OFD object.
This function destroys OFD object. If object wasn't used at all (orphan) then local transaction is used, which means the transaction data is not returned back in reply.
Parameters:
[in] env execution environment
[in] fo OFD object
[in] orphan flag to indicate that object is orphaned
Return values:
0 if successful
negative value on error
Definition at line 722 of file ofd_objects.c.
References dt_declare_destroy(), dt_declare_ref_del(), dt_destroy(), dt_ref_del(), dt_trans_start_local(), ENTRY, GOTO, lu_object_header::loh_fid, ofd_fmd_drop, ofd_info(), ofd_obj2dev(), ofd_object_child(), ofd_object_exists(), ofd_device::ofd_osd, ofd_trans_create(), ofd_trans_start(), ofd_trans_stop(), ofd_write_lock(), ofd_write_unlock(), ofd_object::ofo_header, RETURN, and stop.
Referenced by ofd_destroy_by_fid().
static int ofd_object_exists (struct ofd_object * obj) [inline, static]
Definition at line 230 of file ofd_internal.h.
References dt_object::do_lu, LASSERT, lu_object::lo_header, lu_object_exists, lu_object_is_dying(), and ofd_object::ofo_obj.
Referenced by ofd_attr_get(), ofd_attr_set(), ofd_commitrw_read(), ofd_commitrw_write(), ofd_fiemap_get(), ofd_ioc_get_obj_version(), ofd_object_destroy(), ofd_object_find_exists(), ofd_object_punch(), ofd_precreate_objects(), ofd_preprw_read(), ofd_preprw_write(), and ofd_version_get_check().
int ofd_object_ff_load (const struct lu_env * env, struct ofd_object * fo)
Get FID of parent MDT object.
This function reads extended attribute XATTR_NAME_FID of OFD object which contains the MDT parent object FID and saves it in ofd_object::ofo_pfid.
The filter_fid::ff_parent::f_ver field currently holds the OST-object index in the parent MDT-object's layout EA, not the actual FID::f_ver of the parent. We therefore access it via the macro f_stripe_idx.
Parameters:
[in] env execution environment
[in] fo OFD object
Return values:
0 if successful
-ENODATA if there is no such xattr
negative value on error
Definition at line 138 of file ofd_objects.c.
References buf, dt_xattr_get(), lu_fid::f_oid, lu_fid::f_seq, filter_fid_old::ff_parent, fid_is_sane(), fid_zero(), ofd_thread_info::fti_buf, ofd_thread_info::fti_mds_fid_old, lu_buf::lb_buf, lu_buf::lb_len, le32_to_cpu, le64_to_cpu, ofd_info(), ofd_object_child(), ofd_object::ofo_pfid, and XATTR_NAME_FID.
Referenced by ofd_attr_set(), ofd_object_punch(), ofd_verify_ff(), and ofd_write_attr_set().
struct ofd_object* ofd_object_find (const struct lu_env * env, struct ofd_device * ofd, const struct lu_fid * fid) [read]
Get OFD object by FID.
This function finds OFD slice of compound object with the given FID.
Parameters:
[in] env execution environment
[in] ofd OFD device
[in] fid FID of the object
Return values:
pointer to the found ofd_object
ERR_PTR(errno) in case of error
Definition at line 102 of file ofd_objects.c.
References dt_device::dd_lu_dev, ENTRY, likely, lu_object_find(), ofd_device::ofd_dt_dev, ofd_obj(), and RETURN.
Referenced by ofd_commitrw_read(), ofd_commitrw_write(), ofd_fiemap_get(), ofd_ioc_get_obj_version(), ofd_ladvise_hdl(), ofd_lvbo_init(), ofd_lvbo_update(), ofd_object_find_exists(), ofd_precreate_objects(), ofd_preprw_read(), and ofd_preprw_write().
static struct ofd_object* ofd_object_find_exists (const struct lu_env * env, struct ofd_device * ofd, const struct lu_fid * fid) [static, read]
Definition at line 420 of file ofd_internal.h.
References ofd_object_exists(), ofd_object_find(), and ofd_object_put().
Referenced by ofd_destroy_by_fid(), ofd_echo_getattr(), ofd_echo_setattr(), ofd_getattr_hdl(), ofd_punch_hdl(), ofd_setattr_hdl(), and ofd_sync_hdl().
int ofd_object_punch (const struct lu_env * env, struct ofd_object * fo, __u64 start, __u64 end, struct lu_attr * la, struct filter_fid * ff, struct obdo * oa)
Truncate/punch OFD object.
This function frees all of the allocated object's space from the start offset to the end offset. For truncate() operations the end offset is OBD_OBJECT_EOF. The functionality to punch holes in an object via fallocate(FALLOC_FL_PUNCH_HOLE) is not yet implemented (see LU-3606).
Parameters:
[in] env execution environment
[in] fo OFD object
[in] start start offset to punch from
[in] end end of punch
[in] la object attributes
[in] ff filter_fid structure
[in] oa obdo struct from incoming request
Return values:
0 if successful
negative value on error
Definition at line 600 of file ofd_objects.c.
References dt_attr_set(), dt_declare_attr_set(), dt_declare_punch(), dt_declare_xattr_set(), dt_punch(), dt_xattr_set(), ENTRY, lu_fid::f_oid, lu_fid::f_seq, filter_fid::ff_parent, ofd_mod_data::fmd_mactime_xid, ofd_thread_info::fti_buf, ofd_thread_info::fti_exp, ofd_thread_info::fti_xid, GOTO, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, le32_to_cpu, le64_to_cpu, lu_object_header::loh_fid, obdo::o_valid, OBD_MD_FLFID, OBD_OBJECT_EOF, ofd_attr_handle_ugid(), ofd_fmd_get(), ofd_fmd_put(), ofd_info(), ofd_device::ofd_lfsck_verify_pfid, ofd_obj2dev(), ofd_object_child(), ofd_object_exists(), ofd_object_ff_load(), ofd_trans_create(), ofd_trans_start(), ofd_trans_stop(), ofd_verify_ff(), ofd_version_get_check(), ofd_write_lock(), ofd_write_unlock(), ofd_object::ofo_header, ofd_object::ofo_pfid, stop, and XATTR_NAME_FID.
Referenced by ofd_punch_hdl().
void ofd_object_put (const struct lu_env * env, struct ofd_object * fo)
Put OFD object reference.
Parameters:
[in] env execution environment
[in] fo OFD object
Definition at line 174 of file ofd_objects.c.
References dt_object::do_lu, lu_object_put(), and ofd_object::ofo_obj.
Referenced by ofd_commitrw_read(), ofd_commitrw_write(), ofd_destroy_by_fid(), ofd_echo_getattr(), ofd_echo_setattr(), ofd_fiemap_get(), ofd_getattr_hdl(), ofd_ioc_get_obj_version(), ofd_ladvise_hdl(), ofd_lvbo_init(), ofd_lvbo_update(), ofd_object_find_exists(), ofd_precreate_objects(), ofd_preprw_read(), ofd_preprw_write(), ofd_punch_hdl(), ofd_setattr_hdl(), and ofd_sync_hdl().
int ofd_postrecov (const struct lu_env * env, struct ofd_device * ofd)
Notify all devices in server stack about recovery completion.
This function calls ldo_recovery_complete() for all lower devices in the server stack so they will be prepared for normal operations.
Parameters:
[in] env execution environment
[in] ofd OFD device
Return values:
0 if successful
negative value on error
Definition at line 541 of file ofd_obd.c.
References CDEBUG, CWARN, D_HA, dt_device::dd_lu_dev, lu_device::ld_ops, lu_device_operations::ldo_recovery_complete, lfsck_start(), lfsck_start_param::lsp_index_valid, lfsck_start_param::lsp_start, ofd_device::ofd_dt_dev, ofd_name(), ofd_device::ofd_osd, and ofd_device::ofd_skip_lfsck.
Referenced by ofd_obd_postrecov(), and ofd_prepare().
int ofd_precreate_batch (struct ofd_device * ofd, int batch)
Restrict precreate batch count by its upper limit.
The precreate batch count is a number of precreates to do in single transaction. It has upper limit - ofd_device::ofd_precreate_batch value which shouldn't be exceeded.
Parameters:
[in] ofd OFD device
[in] batch number of updates in the batch
Return values:
\a batch limited by ofd_device::ofd_precreate_batch
Definition at line 61 of file ofd_fs.c.
References ofd_device::ofd_batch_lock, and ofd_device::ofd_precreate_batch.
Referenced by ofd_create_hdl(), ofd_echo_create(), and ofd_preprw_write().
int ofd_precreate_objects (const struct lu_env * env, struct ofd_device * ofd, u64 id, struct ofd_seq * oseq, int nr, int sync)
Precreate the given number nr of objects in the given sequence oseq.
This function precreates new OST objects in the given sequence. The precreation starts from id and creates nr objects sequentially.
Notes: This function may create fewer objects than requested.
We mark object SUID+SGID to flag it for accepting UID+GID from client on first write. Currently the permission bits on the OST are never used, so this is OK.
Initialize a/c/m time so any client timestamp will always be newer and update the inode. The ctime = 0 case is also handled specially in osd_inode_setattr(). See LU-221, LU-1042 for details.
Parameters:
[in] env execution environment
[in] ofd OFD device
[in] id object ID to start precreation from
[in] oseq object sequence
[in] nr number of objects to precreate
[in] sync synchronous precreation flag
Return values:
0 if successful
negative value on error
Definition at line 206 of file ofd_objects.c.
References CDEBUG, CERROR, cpu_to_le64, D_ERROR, D_INODE, D_OTHER, dt_device::dd_record_fid_accessed, DFID, dt_object::do_lu, dt_object_format::dof_type, DOSTID, dt_create(), dt_declare_create(), dt_declare_record_write(), dt_mode_to_dft(), dt_record_write(), dt_trans_start_local(), dt_write_lock(), dt_write_unlock(), ENTRY, ergo, fid_seq_is_mdt0(), fid_set_id(), ofd_thread_info::fti_attr, ofd_thread_info::fti_buf, ofd_thread_info::fti_dof, ofd_thread_info::fti_fid, ofd_thread_info::fti_lr, ofd_thread_info::fti_off, GOTO, IDIF_MAX_OID, lu_attr::la_atime, LA_ATIME, lu_attr::la_ctime, LA_CTIME, lu_attr::la_mode, LA_MODE, lu_attr::la_mtime, LA_MTIME, LA_TYPE, lu_attr::la_valid, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, LE_FID_ACCESSED, lfsck_in_notify(), lfsck_pack_rfa(), LFSCK_TYPE_LAYOUT, likely, LPU64, LPX64, lu_object_fid(), OBD_ALLOC, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_DANGLING, OBD_FAIL_LFSCK_SKIP_LASTID, OBD_FREE, OBIF_MAX_OID, ofd_info(), ofd_name(), ofd_object_child(), ofd_object_exists(), ofd_object_find(), ofd_object_put(), ofd_device::ofd_osd, ofd_seq_last_oid(), ofd_seq_last_oid_set(), ofd_trans_create(), ofd_trans_stop(), ofd_write_lock(), ofd_write_unlock(), ofd_object::ofo_obj, ofd_seq::os_lastid_obj, ofd_seq::os_oi, ostid_seq(), PFID, RETURN, thandle::th_sync, and unlikely.
Referenced by ofd_create_hdl(), ofd_echo_create(), and ofd_preprw_write().
static void ofd_prepare_fidea (struct filter_fid * ff, const struct obdo * oa) [inline, static]
Definition at line 562 of file ofd_internal.h.
References cpu_to_le32, cpu_to_le64, lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, filter_fid::ff_parent, obdo::o_parent_oid, obdo::o_parent_seq, and obdo::o_stripe_idx.
Referenced by ofd_commitrw(), ofd_echo_setattr(), ofd_punch_hdl(), and ofd_setattr_hdl().
int ofd_preprw (const struct lu_env * env, int cmd, struct obd_export * exp, struct obdo * oa, int objcount, struct obd_ioobj * obj, struct niobuf_remote * rnb, int * nr_local, struct niobuf_local * lnb)
Prepare bulk IO requests for processing.
This function does initial checks of IO and calls corresponding functions for read/write processing.
Parameters:
[in] env execution environment
[in] cmd IO type (read/write)
[in] exp OBD export of client
[in] oa OBDO structure from request
[in] objcount always 1
[in] obj object data
[in] rnb remote buffers
[in] nr_local number of local buffers
[in] lnb local buffers
Return values:
0 on successful prepare
negative value on error
Definition at line 685 of file ofd_io.c.
References CERROR, DOSTID, obd_export::exp_obd, ofd_thread_info::fti_attr, obd_ioobj::ioo_bufcnt, LA_ATIME, la_from_obdo(), LASSERT, obdo::o_oi, OBD_BRW_READ, OBD_BRW_WRITE, OBD_FAIL_CHECK, OBD_FAIL_SRV_ENOENT, OBD_MD_FLGETATTR, obd_device::obd_name, obdo_from_la(), ofd_exp(), ofd_grant_prepare_read(), ofd_info_init(), ofd_name(), ofd_preprw_read(), ofd_preprw_write(), ofd_seq_load(), ofd_seq_put(), ost_id::oi_fid, ofd_seq::os_destroys_in_progress, ostid_seq(), POSTID, PTLRPC_MAX_BRW_PAGES, RETURN, tgt_ses_info(), tgt_ses_req(), tsi2ofd_info(), and tgt_session_info::tsi_jobid.
static void ofd_read_lock (const struct lu_env * env, struct ofd_object * fo) [inline, static]
Definition at line 255 of file ofd_internal.h.
References dt_object::do_ops, dt_object_operations::do_read_lock, and ofd_object_child().
Referenced by ofd_fiemap_get(), ofd_preprw_read(), and ofd_preprw_write().
static void ofd_read_unlock (const struct lu_env * env, struct ofd_object * fo) [inline, static]
Definition at line 263 of file ofd_internal.h.
References dt_object::do_ops, dt_object_operations::do_read_unlock, and ofd_object_child().
Referenced by ofd_commitrw_read(), ofd_commitrw_write(), ofd_fiemap_get(), ofd_preprw_read(), and ofd_preprw_write().
struct ofd_seq* ofd_seq_get (struct ofd_device * ofd, u64 seq) [read]
Get ofd_seq for seq.
Function finds appropriate structure by seq number and increases the reference counter of that structure.
Parameters:
[in] ofd OFD device
[in] seq sequence number, FID sequence number usually
Return values:
pointer to the requested ofd_seq structure
NULL if ofd_seq is not found
Definition at line 84 of file ofd_fs.c.
References list_for_each_entry, ofd_device::ofd_seq_list, ofd_device::ofd_seq_list_lock, ofd_seq::os_list, ofd_seq::os_oi, ofd_seq::os_refc, and ostid_seq().
Referenced by ofd_orphans_destroy(), and ofd_seq_load().
u64 ofd_seq_last_oid (struct ofd_seq * oseq)
Get last object ID for the given sequence.
Parameters:
[in] oseq OFD sequence structure
Return values:
the last object ID for this sequence
Definition at line 164 of file ofd_fs.c.
References ofd_seq::os_last_oid_lock, ofd_seq::os_oi, and ostid_id().
Referenced by ofd_create_hdl(), ofd_echo_create(), ofd_get_info_hdl(), ofd_orphans_destroy(), ofd_precreate_objects(), ofd_preprw_write(), and ofd_seq_last_oid_write().
void ofd_seq_last_oid_set (struct ofd_seq * oseq, u64 id)
Set new last object ID for the given sequence.
Parameters:
[in] oseq OFD sequence
[in] id the new OID to set
Definition at line 181 of file ofd_fs.c.
References likely, ofd_seq::os_last_oid_lock, ofd_seq::os_oi, ostid_id(), and ostid_set_id().
Referenced by ofd_create_hdl(), ofd_orphans_destroy(), ofd_precreate_objects(), and ofd_seq_load().
int ofd_seq_last_oid_write (const struct lu_env * env, struct ofd_device * ofd, struct ofd_seq * oseq)
Update last used OID on disk for the given sequence.
The last used object ID is stored persistently on disk and must be written when updated. This function writes the sequence data. The format is just an object ID of the latest used object FID. Each ID is stored in per-sequence file.
Parameters:
[in] env execution environment
[in] ofd OFD device
[in] oseq ofd_seq structure with data to write
Return values:
0 on successful write of data from oseq
negative value on error
Definition at line 204 of file ofd_fs.c.
References CDEBUG, cpu_to_le64, D_INODE, DOSTID, dt_declare_record_write(), dt_record_write(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), ENTRY, EXIT, ofd_thread_info::fti_buf, ofd_thread_info::fti_off, GOTO, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, ofd_info(), ofd_name(), ofd_device::ofd_osd, ofd_seq_last_oid(), ofd_seq::os_lastid_obj, ofd_seq::os_oi, POSTID, and RETURN.
Referenced by ofd_orphans_destroy(), and ofd_seq_load().
struct ofd_seq* ofd_seq_load (const struct lu_env * env, struct ofd_device * ofd, u64 seq) [read]
Return ofd_seq structure filled with valid data.
This function gets the ofd_seq by sequence number and read corresponding data from disk.
Parameters:
[in] env execution environment
[in] ofd OFD device
[in] seq sequence number
Return values:
ofd_seq structure filled with data
ERR_PTR pointer on error
Definition at line 362 of file ofd_fs.c.
References __u64, CERROR, cleanup(), dt_object_format::dof_type, dt_attr_get(), dt_find_or_create(), dt_mode_to_dft(), dt_record_read(), ENTRY, ofd_thread_info::fti_attr, ofd_thread_info::fti_buf, ofd_thread_info::fti_dof, ofd_thread_info::fti_fid, ofd_thread_info::fti_off, GOTO, INIT_LIST_HEAD, lu_attr::la_mode, LA_MODE, lu_attr::la_size, lu_attr::la_valid, lu_buf::lb_buf, lu_buf::lb_len, le64_to_cpu, LPU64, LPX64, lr_server_data::lsd_osd_index, lu_last_id_fid(), lu_target::lut_lsd, OBD_ALLOC_PTR, OBD_FREE_PTR, ofd_info(), OFD_INIT_OBJID, ofd_device::ofd_lut, ofd_name(), ofd_device::ofd_osd, ofd_seq_add(), ofd_seq_get(), ofd_seq_last_oid_set(), ofd_seq_last_oid_write(), ofd_seq_put(), ofd_seq::os_create_lock, ofd_seq::os_last_oid_lock, ofd_seq::os_lastid_obj, ofd_seq::os_list, ofd_seq::os_oi, ofd_seq::os_refc, ostid_set_seq(), and RETURN.
Referenced by ofd_create_hdl(), ofd_echo_create(), ofd_get_info_hdl(), ofd_preprw(), and ofd_preprw_write().
void ofd_seq_put (const struct lu_env * env, struct ofd_seq * oseq)
Drop a reference to ofd_seq.
The paired function to the ofd_seq_get(). It decrease the reference counter of the ofd_seq structure and free it if that reference was last one.
Parameters:
[in] env execution environment
[in] oseq ofd_seq structure to put
Definition at line 109 of file ofd_fs.c.
References dt_object::do_lu, LASSERT, list_empty(), lu_object_put(), OBD_FREE_PTR, ofd_seq::os_lastid_obj, ofd_seq::os_list, and ofd_seq::os_refc.
Referenced by ofd_create_hdl(), ofd_echo_create(), ofd_get_info_hdl(), ofd_orphans_destroy(), ofd_preprw(), ofd_preprw_write(), ofd_seq_add(), ofd_seq_load(), and ofd_seqs_free().
void ofd_seqs_fini (const struct lu_env * env, struct ofd_device * ofd)
Stop FLDB and SEQ services on OFD.
This function is part of OFD cleanup process.
Parameters:
[in] env execution environment
[in] ofd OFD device
Definition at line 332 of file ofd_fs.c.
References CERROR, LASSERT, list_empty(), ofd_deregister_seq_exp(), ofd_fid_fini(), ofd_fld_fini(), ofd_name(), ofd_device::ofd_seq_list, and ofd_seqs_free().
Referenced by ofd_fs_cleanup(), and ofd_fs_setup().
void ofd_seqs_free (const struct lu_env * env, struct ofd_device * ofd)
Free sequence structures on OFD.
This function is part of OFD cleanup process, it goes through the list of ofd_seq structures stored in ofd_device structure and frees them.
Parameters:
[in] env execution environment
[in] ofd OFD device
Definition at line 304 of file ofd_fs.c.
References INIT_LIST_HEAD, list_del_init(), list_empty(), list_for_each_entry_safe, list_move(), list_head::next, ofd_device::ofd_seq_list, ofd_device::ofd_seq_list_lock, ofd_seq_put(), and ofd_seq::os_list.
Referenced by ofd_lfsck_out_notify(), and ofd_seqs_fini().
int ofd_seqs_init (const struct lu_env * env, struct ofd_device * ofd)
Initialize SEQ and FLD service on OFD.
This is part of OFD setup process.
Parameters:
[in] env execution environment
[in] ofd OFD device
Return values:
0 on successful services initialization
negative value on error
Definition at line 572 of file ofd_fs.c.
References CERROR, GOTO, INIT_LIST_HEAD, ofd_fid_fini(), ofd_fid_init(), ofd_fld_fini(), ofd_fld_init(), ofd_name(), ofd_register_seq_exp(), ofd_device::ofd_seq_count, ofd_device::ofd_seq_list, ofd_device::ofd_seq_list_lock, and RETURN.
Referenced by ofd_fs_setup().
static void ofd_slc_set (struct ofd_device * ofd) [inline, static]
Definition at line 554 of file ofd_internal.h.
References ALWAYS_SYNC_ON_CANCEL, lu_target::lut_sync_lock_cancel, NEVER_SYNC_ON_CANCEL, ofd_device::ofd_lut, and ofd_device::ofd_syncjournal.
Referenced by ofd_init0().
int ofd_start_inconsistency_verification_thread (struct ofd_device * ofd)
Start parent FID verification thread.
See ofd_inconsistency_verification_main().
Parameters:
[in] ofd OFD device
Return values:
0 on successful start of thread
negative value on error
Definition at line 247 of file ofd_io.c.
References CERROR, l_wait_event, ofd_device::ofd_inconsistency_lock, ofd_device::ofd_inconsistency_thread, ofd_inconsistency_verification_main(), ofd_name(), ptlrpc_thread::t_ctl_waitq, thread, thread_is_running(), thread_is_stopped(), thread_set_flags(), and unlikely.
Referenced by ofd_init0().
int ofd_statfs (const struct lu_env * env, struct obd_export * exp, struct obd_statfs * osfs, __u64 max_age, __u32 flags)
Implementation of obd_ops::o_statfs.
This function returns information about a storage file system. It is called from several places by using the OBD API as well as by direct call, e.g. from request handler.
See also:
ofd_statfs_hdl() for request handler function.
Report also the state of the OST to the caller in osfs->os_state (OS_STATE_READONLY, OS_STATE_DEGRADED).
Parameters:
[in] env execution environment
[in] exp OBD export of OFD device
[out] osfs statistic data to return
[in] max_age maximum age for cached data
[in] flags not used in OFD
Return values:
0 if successful
negative value on error
Definition at line 806 of file ofd_obd.c.
References CDEBUG, class_exp2obd(), COMPAT_BSIZE_SHIFT, D_CACHE, D_SUPER, ENTRY, EXIT, exp_connect_flags(), filter_export_data::fed_grant, GOTO, LPU64, lr_server_data::lsd_osd_index, lu_target::lut_lsd, min_t, OBD_CONNECT_MDS, OBD_FAIL_CHECK_VALUE, OBD_FAIL_OST_ENOINO, OBD_FAIL_OST_ENOSPC, obd_device::obd_self_export, ofd_device::ofd_blockbits, ofd_exp(), ofd_grant_param_supp(), ofd_grant_sanity_check(), ofd_device::ofd_lut, ofd_device::ofd_raid_degraded, ofd_statfs_internal(), ofd_device::ofd_tot_dirty, ofd_device::ofd_tot_granted, ofd_device::ofd_tot_pending, obd_statfs::os_bavail, obd_statfs::os_bfree, obd_statfs::os_blocks, obd_statfs::os_bsize, obd_statfs::os_ffree, obd_statfs::os_files, obd_statfs::os_state, OS_STATE_DEGRADED, and unlikely.
Referenced by ofd_statfs_hdl().
int ofd_statfs_internal (const struct lu_env * env, struct ofd_device * ofd, struct obd_statfs * osfs, __u64 max_age, int * from_cache)
Get file system statistics of OST server.
Helper function for ofd_statfs(), also used by grant code. Implements caching for statistics to avoid calling OSD device each time.
Parameters:
[in] env execution environment
[in] ofd OFD device
[out] osfs statistic data to return
[in] max_age maximum age for cached data
[in] from_cache show that data was get from cache or not
Return values:
0 if successful
negative value on error
Definition at line 701 of file ofd_obd.c.
References cfs_time_before_64(), cfs_time_current_64, dt_statfs(), ENTRY, GOTO, min_t, ofd_device::ofd_blockbits, ofd_device::ofd_grant_lock, ofd_device::ofd_osd, ofd_device::ofd_osfs, ofd_device::ofd_osfs_age, ofd_device::ofd_osfs_inflight, ofd_device::ofd_osfs_lock, ofd_device::ofd_osfs_unstable, ofd_device::ofd_statfs_inflight, ofd_device::ofd_tot_pending, obd_statfs::os_bavail, and unlikely.
Referenced by ofd_grant_statfs(), ofd_init0(), and ofd_statfs().
static void ofd_stats_counter_init (struct lprocfs_stats * stats) [inline, static]
Definition at line 396 of file ofd_internal.h.
Referenced by ofd_export_stats_init(), and ofd_procfs_init().
int ofd_stop_inconsistency_verification_thread (struct ofd_device * ofd)
Stop parent FID verification thread.
Parameters:
[in] ofd OFD device
Return values:
0 on successful start of thread
-EALREADY if thread is already stopped
Definition at line 288 of file ofd_io.c.
References l_wait_event, ofd_device::ofd_inconsistency_lock, ofd_device::ofd_inconsistency_thread, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, thread, thread_is_init(), thread_is_stopped(), and thread_set_flags().
Referenced by ofd_fini().
struct thandle* ofd_trans_create (const struct lu_env * env, struct ofd_device * ofd) [read]
Create new transaction in OFD.
This function creates a transaction with dt_trans_create() and makes it synchronous if required by the export state.
Parameters:
[in] env execution environment
[in] ofd OFD device
Return values:
struct thandle if transaction was created successfully
ERR_PTR on negative value in case of error
Definition at line 57 of file ofd_trans.c.
References dt_trans_create(), obd_export::exp_need_sync, ofd_thread_info::fti_exp, LASSERT, ofd_info(), ofd_device::ofd_osd, and thandle::th_sync.
Referenced by ofd_attr_set(), ofd_commitrw_write(), ofd_object_destroy(), ofd_object_punch(), ofd_precreate_objects(), and ofd_write_attr_set().
int ofd_trans_start (const struct lu_env * env, struct ofd_device * ofd, struct ofd_object * obj, struct thandle * th)
Start transaction in OFD.
This function updates the given obj object version and calls dt_trans_start().
Parameters:
[in] env execution environment
[in] ofd OFD device
[in] obj OFD object affected by this transaction
[in] th transaction handle
Return values:
0 if successful
negative value in case of error
Definition at line 89 of file ofd_trans.c.
References dt_trans_start(), ofd_object_child(), ofd_device::ofd_osd, and tgt_vbr_obj_set().
Referenced by ofd_attr_set(), ofd_commitrw_write(), ofd_object_destroy(), and ofd_object_punch().
void ofd_trans_stop (const struct lu_env * env, struct ofd_device * ofd, struct thandle * th, int rc)
Stop transaction in OFD.
This function fills thandle::th_result with result of whole operation and calls dt_trans_stop().
Parameters:
[in] env execution environment
[in] ofd OFD device
[in] th transaction handle
[in] rc result code of whole operation
Definition at line 110 of file ofd_trans.c.
References dt_trans_stop(), ofd_device::ofd_osd, and thandle::th_result.
Referenced by ofd_attr_set(), ofd_commitrw_write(), ofd_object_destroy(), ofd_object_punch(), and ofd_precreate_objects().
int ofd_txn_stop_cb (const struct lu_env * env, struct thandle * txn, void * cookie)
int ofd_verify_ff (const struct lu_env * env, struct ofd_object * fo, struct obdo * oa)
Verify parent FID of an object.
Check the parent FID is sane and start extended verification procedure otherwise.
Parameters:
[in] env execution environment
[in] fo OFD object
[in] oa OBDO structure with PFID
Return values:
0 on successful verification
-EINPROGRESS if PFID is being repaired
-EPERM if PFID was verified but still insane
Definition at line 378 of file ofd_io.c.
References ENTRY, lu_fid::f_oid, lu_fid::f_seq, fid_is_sane(), likely, obdo::o_parent_oid, obdo::o_parent_seq, obdo::o_stripe_idx, ofd_add_inconsistency_item(), ofd_object_ff_load(), ofd_object::ofo_pfid, ofd_object::ofo_pfid_checking, ofd_object::ofo_pfid_verified, and RETURN.
Referenced by ofd_object_punch(), ofd_preprw_read(), and ofd_preprw_write().
static void ofd_write_lock (const struct lu_env * env, struct ofd_object * fo) [inline, static]
Definition at line 271 of file ofd_internal.h.
References dt_object::do_ops, dt_object_operations::do_write_lock, and ofd_object_child().
Referenced by ofd_attr_set(), ofd_inconsistency_verification_main(), ofd_inconsistency_verify_one(), ofd_object_destroy(), ofd_object_punch(), and ofd_precreate_objects().
static void ofd_write_unlock (const struct lu_env * env, struct ofd_object * fo) [inline, static]
Definition at line 279 of file ofd_internal.h.
References dt_object::do_ops, dt_object_operations::do_write_unlock, and ofd_object_child().
Referenced by ofd_attr_set(), ofd_inconsistency_verification_main(), ofd_inconsistency_verify_one(), ofd_object_destroy(), ofd_object_punch(), and ofd_precreate_objects().
void target_recovery_fini (struct obd_device * obd)
void target_recovery_init (struct lu_target * lut, svc_handler_t handler)
static struct ofd_thread_info* tsi2ofd_info (struct tgt_session_info * tsi) [static, read]
VBR: take versions from request
Definition at line 527 of file ofd_internal.h.
References __u64, ofd_thread_info::fti_attr, ofd_thread_info::fti_env, ofd_thread_info::fti_exp, ofd_thread_info::fti_pre_version, ofd_thread_info::fti_xid, lu_attr::la_valid, LASSERT, lustre_msg_get_flags(), lustre_msg_get_versions(), MSG_REPLAY, ofd_info(), ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_xid, tgt_ses_req(), tgt_session_info::tsi_env, and tgt_session_info::tsi_exp.
Referenced by ofd_destroy_hdl(), ofd_get_info_hdl(), ofd_getattr_hdl(), ofd_preprw(), ofd_punch_hdl(), ofd_setattr_hdl(), and ofd_sync_hdl().
Variable Documentation
struct ldlm_valblock_ops ofd_lvbo
Definition at line 383 of file ofd_lvb.c.
Referenced by ofd_init0().
struct obd_ops ofd_obd_ops
Definition at line 1476 of file ofd_obd.c.
Referenced by ofd_init().
struct lu_context_key ofd_thread_key
Definition at line 2792 of file ofd_dev.c.
Referenced by ofd_info().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.