Lustre: lustre/ofd/ofd_lvb.c File Reference
lustre/ofd/ofd_lvb.c File Reference
#include <lustre_swab.h>
#include "ofd_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_FILTER
Functions
static int ofd_lvbo_free (struct ldlm_resource *res)
Implementation of ldlm_valblock_ops::lvbo_free for OFD.
static int ofd_lvbo_init (struct ldlm_resource *res)
Implementation of ldlm_valblock_ops::lvbo_init for OFD.
static int ofd_lvbo_update (struct ldlm_resource *res, struct ptlrpc_request *req, int increase_only)
Implementation of ldlm_valblock_ops::lvbo_update for OFD.
static int ofd_lvbo_size (struct ldlm_lock *lock)
Implementation of ldlm_valblock_ops::lvbo_size for OFD.
static int ofd_lvbo_fill (struct ldlm_lock *lock, void *buf, int buflen)
Implementation of ldlm_valblock_ops::lvbo_fill for OFD.
Variables
struct ldlm_valblock_ops ofd_lvbo
Define Documentation
#define DEBUG_SUBSYSTEM S_FILTER
Definition at line 46 of file ofd_lvb.c.
Function Documentation
static int ofd_lvbo_fill (struct ldlm_lock * lock, void * buf, int buflen) [static]
Implementation of ldlm_valblock_ops::lvbo_fill for OFD.
This function is called to fill the given RPC buffer buf with LVB data
Parameters:
[in] lock LDLM lock
[in] buf RPC buffer to fill
[in] buflen buffer length
Return values:
size of LVB data written into buf buffer
Definition at line 361 of file ofd_lvb.c.
References ldlm_lock::l_resource, LASSERT, lock_res(), ldlm_resource::lr_lvb_data, ldlm_resource::lr_lvb_len, ofd_lvbo_size(), unlikely, and unlock_res().
static int ofd_lvbo_free (struct ldlm_resource * res) [static]
Implementation of ldlm_valblock_ops::lvbo_free for OFD.
This function frees allocated LVB data if it associated with the given LDLM resource.
Parameters:
[in] res LDLM resource
Return values:
0 on successful setup
negative value on error
Definition at line 62 of file ofd_lvb.c.
References ldlm_resource::lr_lvb_data, ldlm_resource::lr_lvb_len, and OBD_FREE.
static int ofd_lvbo_init (struct ldlm_resource * res) [static]
Implementation of ldlm_valblock_ops::lvbo_init for OFD.
This function allocates and initializes new LVB data for the given LDLM resource if it is not allocated yet. New LVB is filled with attributes of the object associated with that resource. Function does nothing if LVB for the given LDLM resource is allocated already.
Called with res->lr_lvb_sem held.
Parameters:
[in] res LDLM resource
Return values:
0 on successful setup
negative value on error
Definition at line 85 of file ofd_lvb.c.
References CDEBUG, D_DLMTRACE, DFID, ENTRY, EXIT, ofd_thread_info::fti_attr, ofd_thread_info::fti_fid, GOTO, lu_attr::la_atime, lu_attr::la_blocks, lu_attr::la_ctime, lu_attr::la_mtime, lu_attr::la_size, LASSERT, LCT_DT_THREAD, ldlm_res_to_ns(), LPU64, LPX64, ldlm_resource::lr_lvb_data, ldlm_resource::lr_lvb_len, ldlm_resource::lr_lvb_mutex, ldlm_resource::lr_name, lr_server_data::lsd_osd_index, lu_env_fini(), lu_env_init(), lu_target::lut_lsd, ost_lvb::lvb_atime, ost_lvb::lvb_blocks, ost_lvb::lvb_ctime, ost_lvb::lvb_mtime, ost_lvb::lvb_size, ldlm_namespace::ns_lvbp, OBD_ALLOC_PTR, OBD_FAIL_CHECK, OBD_FAIL_LDLM_OST_LVB, ofd_attr_get(), ofd_info_init(), ofd_device::ofd_lut, ofd_object_find(), ofd_object_put(), ost_fid_from_resid(), OST_LVB_SET_ERR, PFID, and RETURN.
static int ofd_lvbo_size (struct ldlm_lock * lock) [static]
Implementation of ldlm_valblock_ops::lvbo_size for OFD.
This function returns size of LVB data so appropriate RPC size will be reserved. This is used for compatibility needs between server and client of different Lustre versions.
Parameters:
[in] lock LDLM lock
Return values:
size of LVB data
Definition at line 342 of file ofd_lvb.c.
References exp_connect_lvb_type(), and ldlm_lock::l_export.
Referenced by ofd_lvbo_fill().
static int ofd_lvbo_update (struct ldlm_resource * res, struct ptlrpc_request * req, int increase_only) [static]
Implementation of ldlm_valblock_ops::lvbo_update for OFD.
When a client generates a glimpse enqueue, it wants to get the current file size and updated attributes for a stat() type operation, but these attributes may be writeback cached on another client. The client with the DLM extent lock at the highest offset is asked for its current attributes via a glimpse callback on its extent lock, on the assumption that it has the highest file size and the newest timestamps. The timestamps are guaranteed to be correct if there is only a single writer on the file, but may be slightly inaccurate if there are multiple concurrent writers on the same object. In order to avoid race conditions between the glimpse AST and the client cancelling the lock, ofd_lvbo_update() also updates the attributes from the local object. If the last client hasn't done any writes yet, or has already written its data and cancelled its lock before it processed the glimpse, then the local inode will have more uptodate information.
This is called in two ways: req != NULL : called by the DLM itself after a glimpse callback req == NULL : called by the OFD after a disk write
Parameters:
[in] res LDLM resource
[in] req PTLRPC request
[in] increase_only don't allow LVB values to decrease
Return values:
0 on successful setup
negative value on error
Definition at line 182 of file ofd_lvb.c.
References CDEBUG, CERROR, D_DLMTRACE, DFID, ENTRY, exp_connect_lvb_type(), fid_extract_from_res_name(), ofd_thread_info::fti_attr, ofd_thread_info::fti_fid, ofd_thread_info::fti_lvb, GOTO, imp_connect_lvb_type(), lu_attr::la_atime, lu_attr::la_blocks, lu_attr::la_ctime, lu_attr::la_mtime, lu_attr::la_size, LASSERT, LCT_DT_THREAD, ldlm_res_to_ns(), lock_res(), LPU64, ldlm_resource::lr_lvb_data, ldlm_resource::lr_name, lr_server_data::lsd_osd_index, lu_env_fini(), lu_env_init(), lustre_swab_ost_lvb, lustre_swab_ost_lvb_v1, lu_target::lut_lsd, ost_lvb::lvb_atime, ost_lvb::lvb_atime_ns, ost_lvb::lvb_blocks, ost_lvb::lvb_ctime, ost_lvb::lvb_ctime_ns, ost_lvb::lvb_mtime, ost_lvb::lvb_mtime_ns, ost_lvb::lvb_size, ldlm_namespace::ns_lvbp, ofd_attr_get(), ofd_info_init(), ofd_device::ofd_lut, ofd_name(), ofd_object_find(), ofd_object_put(), ost_fid_from_resid(), PFID, req_capsule_server_swab_get(), RETURN, RMF_DLM_LVB, ptlrpc_request::rq_export, ptlrpc_request::rq_import, ptlrpc_request::rq_pill, and unlock_res().
Variable Documentation
struct ldlm_valblock_ops ofd_lvbo
Initial value:
 {
        .lvbo_init      = ofd_lvbo_init,
        .lvbo_update    = ofd_lvbo_update,
        .lvbo_free      = ofd_lvbo_free,
        .lvbo_size      = ofd_lvbo_size,
        .lvbo_fill      = ofd_lvbo_fill
}
Definition at line 383 of file ofd_lvb.c.
Referenced by ofd_init0().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.