Lustre: lustre/ofd/ofd_fs.c File Reference
lustre/ofd/ofd_fs.c File Reference
#include "ofd_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_FILTER
Functions
int ofd_precreate_batch (struct ofd_device *ofd, int batch)
Restrict precreate batch count by its upper limit.
struct ofd_seq * ofd_seq_get (struct ofd_device *ofd, u64 seq)
Get ofd_seq for seq.
void ofd_seq_put (const struct lu_env *env, struct ofd_seq *oseq)
Drop a reference to ofd_seq.
static struct ofd_seq * ofd_seq_add (const struct lu_env *env, struct ofd_device *ofd, struct ofd_seq *new_seq)
Add a new ofd_seq to the given OFD device.
u64 ofd_seq_last_oid (struct ofd_seq *oseq)
Get last object ID for the given sequence.
void ofd_seq_last_oid_set (struct ofd_seq *oseq, u64 id)
Set new last object ID for the given sequence.
int ofd_seq_last_oid_write (const struct lu_env *env, struct ofd_device *ofd, struct ofd_seq *oseq)
Update last used OID on disk for the given sequence.
static void ofd_deregister_seq_exp (struct ofd_device *ofd)
Deregister LWP items for FLDB and SEQ client on OFD.
static void ofd_fld_fini (const struct lu_env *env, struct ofd_device *ofd)
Stop FLDB server on OFD.
void ofd_seqs_free (const struct lu_env *env, struct ofd_device *ofd)
Free sequence structures on OFD.
void ofd_seqs_fini (const struct lu_env *env, struct ofd_device *ofd)
Stop FLDB and SEQ services on OFD.
struct ofd_seq * ofd_seq_load (const struct lu_env *env, struct ofd_device *ofd, u64 seq)
Return ofd_seq structure filled with valid data.
static int ofd_fld_init (const struct lu_env *env, const char *uuid, struct ofd_device *ofd)
initialize local FLDB server.
static int ofd_register_lwp_callback (void *data)
Update local FLDB copy from master server.
static int ofd_register_seq_exp (struct ofd_device *ofd)
Get LWP exports from LWP connection for local FLDB server and SEQ client.
int ofd_seqs_init (const struct lu_env *env, struct ofd_device *ofd)
Initialize SEQ and FLD service on OFD.
int ofd_fs_setup (const struct lu_env *env, struct ofd_device *ofd, struct obd_device *obd)
Initialize storage for the OFD.
void ofd_fs_cleanup (const struct lu_env *env, struct ofd_device *ofd)
Cleanup service files on OFD.
Define Documentation
#define DEBUG_SUBSYSTEM S_FILTER
Definition at line 45 of file ofd_fs.c.
Function Documentation
static void ofd_deregister_seq_exp (struct ofd_device * ofd) [static]
Deregister LWP items for FLDB and SEQ client on OFD.
LWP is lightweight proxy - simplified connection between servers. It is used for FID Location Database (FLDB) and sequence (SEQ) client-server interactions.
This function is used during server cleanup process to free LWP items that were previously set up upon OFD start.
Parameters:
[in] ofd OFD device
Definition at line 259 of file ofd_fs.c.
References lu_client_seq::lcs_exp, lu_server_fld::lsf_control_exp, lustre_deregister_lwp_item(), ofd_device::ofd_seq_site, seq_server_site::ss_client_seq, and seq_server_site::ss_server_fld.
Referenced by ofd_seqs_fini().
static void ofd_fld_fini (const struct lu_env * env, struct ofd_device * ofd) [static]
Stop FLDB server on OFD.
This function is part of OFD cleanup process.
Parameters:
[in] env execution environment
[in] ofd OFD device
Definition at line 283 of file ofd_fs.c.
References fld_server_fini(), OBD_FREE_PTR, ofd_device::ofd_seq_site, and seq_server_site::ss_server_fld.
Referenced by ofd_seqs_fini(), and ofd_seqs_init().
static int ofd_fld_init (const struct lu_env * env, const char * uuid, struct ofd_device * ofd) [static]
initialize local FLDB server.
Parameters:
[in] env execution environment
[in] uuid unique name for this FLDS server
[in] ofd OFD device
Return values:
0 on successful initialization
negative value on error
Definition at line 449 of file ofd_fs.c.
References ENTRY, fld_server_init(), LU_SEQ_RANGE_OST, OBD_ALLOC_PTR, OBD_FREE_PTR, ofd_device::ofd_osd, ofd_device::ofd_seq_site, RETURN, and seq_server_site::ss_server_fld.
Referenced by ofd_seqs_init().
void ofd_fs_cleanup (const struct lu_env * env, struct ofd_device * ofd)
Cleanup service files on OFD.
This function syncs whole OFD device and close "health check" file.
Parameters:
[in] env execution environment
[in] ofd OFD device
Definition at line 666 of file ofd_fs.c.
References CWARN, dt_object::do_lu, dt_sync(), ENTRY, EXIT, lu_object_put(), ofd_device::ofd_health_check_file, ofd_name(), ofd_device::ofd_osd, and ofd_seqs_fini().
Referenced by ofd_fini(), and ofd_init0().
int ofd_fs_setup (const struct lu_env * env, struct ofd_device * ofd, struct obd_device * obd)
Initialize storage for the OFD.
This function sets up service files for OFD. Currently, the only service file is "health_check".
Parameters:
[in] env execution environment
[in] ofd OFD device
[in] obd OBD device (unused now)
Return values:
0 on successful setup
negative value on error
Definition at line 621 of file ofd_fs.c.
References dt_object_format::dof_type, dt_find_or_create(), dt_mode_to_dft(), ENTRY, ofd_thread_info::fti_attr, ofd_thread_info::fti_dof, ofd_thread_info::fti_fid, GOTO, lu_attr::la_mode, LA_MODE, lu_attr::la_valid, lu_local_obj_fid(), OBD_FAIL_CHECK, OBD_FAIL_MDS_FS_SETUP, ofd_device::ofd_health_check_file, OFD_HEALTH_CHECK_OID, ofd_info(), ofd_device::ofd_osd, ofd_seqs_fini(), ofd_seqs_init(), and RETURN.
Referenced by ofd_init0().
int ofd_precreate_batch (struct ofd_device * ofd, int batch)
Restrict precreate batch count by its upper limit.
The precreate batch count is a number of precreates to do in single transaction. It has upper limit - ofd_device::ofd_precreate_batch value which shouldn't be exceeded.
Parameters:
[in] ofd OFD device
[in] batch number of updates in the batch
Return values:
\a batch limited by ofd_device::ofd_precreate_batch
Definition at line 61 of file ofd_fs.c.
References ofd_device::ofd_batch_lock, and ofd_device::ofd_precreate_batch.
Referenced by ofd_create_hdl(), ofd_echo_create(), and ofd_preprw_write().
static int ofd_register_lwp_callback (void * data) [static]
Update local FLDB copy from master server.
This callback is called when LWP is connected to the server. It retrieves its FLDB entries from MDT0, and it only happens when upgrading the existing file system to 2.6.
Parameters:
[in] data OFD device
Return values:
0 on successful FLDB update
negative value in case if failure
Definition at line 483 of file ofd_fs.c.
References CERROR, ENTRY, EXIT, fld_update_from_controller(), GOTO, LCT_DT_THREAD, likely, lu_server_fld::lsf_new, lu_env_fini(), lu_env_init(), OBD_ALLOC_PTR, OBD_FREE_PTR, ofd_name(), ofd_device::ofd_seq_site, RETURN, and seq_server_site::ss_server_fld.
Referenced by ofd_register_seq_exp().
static int ofd_register_seq_exp (struct ofd_device * ofd) [static]
Get LWP exports from LWP connection for local FLDB server and SEQ client.
This function is part of setup process and initialize FLDB server and SEQ client, so they may work with remote servers.
Parameters:
[in] ofd OFD device
Return values:
0 on successful export get
negative value on error
Definition at line 527 of file ofd_fs.c.
References GOTO, lu_client_seq::lcs_exp, lu_server_fld::lsf_control_exp, lustre_deregister_lwp_item(), lustre_register_lwp_item(), MAX_OBD_NAME, OBD_ALLOC, OBD_FREE, ofd_name(), ofd_register_lwp_callback(), ofd_device::ofd_seq_site, seq_server_site::ss_client_seq, seq_server_site::ss_server_fld, and tgt_name2lwp_name().
Referenced by ofd_seqs_init().
static struct ofd_seq* ofd_seq_add (const struct lu_env * env, struct ofd_device * ofd, struct ofd_seq * new_seq) [static, read]
Add a new ofd_seq to the given OFD device.
First it checks if there is already existent ofd_seq with the same sequence number as used by new_seq. If such ofd_seq is not found then the new_seq is added to the list of all ofd_seq structures else the new_seq is dropped and the found ofd_seq is returned back.
Parameters:
[in] env execution environment
[in] ofd OFD device
[in] new_seq new ofd_seq to be added
Return values:
ofd_seq structure
Definition at line 134 of file ofd_fs.c.
References list_add_tail(), list_for_each_entry, ofd_device::ofd_seq_count, ofd_device::ofd_seq_list, ofd_device::ofd_seq_list_lock, ofd_seq_put(), ofd_seq::os_list, ofd_seq::os_oi, ofd_seq::os_refc, and ostid_seq().
Referenced by ofd_seq_load().
struct ofd_seq* ofd_seq_get (struct ofd_device * ofd, u64 seq) [read]
Get ofd_seq for seq.
Function finds appropriate structure by seq number and increases the reference counter of that structure.
Parameters:
[in] ofd OFD device
[in] seq sequence number, FID sequence number usually
Return values:
pointer to the requested ofd_seq structure
NULL if ofd_seq is not found
Definition at line 84 of file ofd_fs.c.
References list_for_each_entry, ofd_device::ofd_seq_list, ofd_device::ofd_seq_list_lock, ofd_seq::os_list, ofd_seq::os_oi, ofd_seq::os_refc, and ostid_seq().
Referenced by ofd_orphans_destroy(), and ofd_seq_load().
u64 ofd_seq_last_oid (struct ofd_seq * oseq)
Get last object ID for the given sequence.
Parameters:
[in] oseq OFD sequence structure
Return values:
the last object ID for this sequence
Definition at line 164 of file ofd_fs.c.
References ofd_seq::os_last_oid_lock, ofd_seq::os_oi, and ostid_id().
Referenced by ofd_create_hdl(), ofd_echo_create(), ofd_get_info_hdl(), ofd_orphans_destroy(), ofd_precreate_objects(), ofd_preprw_write(), and ofd_seq_last_oid_write().
void ofd_seq_last_oid_set (struct ofd_seq * oseq, u64 id)
Set new last object ID for the given sequence.
Parameters:
[in] oseq OFD sequence
[in] id the new OID to set
Definition at line 181 of file ofd_fs.c.
References likely, ofd_seq::os_last_oid_lock, ofd_seq::os_oi, ostid_id(), and ostid_set_id().
Referenced by ofd_create_hdl(), ofd_orphans_destroy(), ofd_precreate_objects(), and ofd_seq_load().
int ofd_seq_last_oid_write (const struct lu_env * env, struct ofd_device * ofd, struct ofd_seq * oseq)
Update last used OID on disk for the given sequence.
The last used object ID is stored persistently on disk and must be written when updated. This function writes the sequence data. The format is just an object ID of the latest used object FID. Each ID is stored in per-sequence file.
Parameters:
[in] env execution environment
[in] ofd OFD device
[in] oseq ofd_seq structure with data to write
Return values:
0 on successful write of data from oseq
negative value on error
Definition at line 204 of file ofd_fs.c.
References CDEBUG, cpu_to_le64, D_INODE, DOSTID, dt_declare_record_write(), dt_record_write(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), ENTRY, EXIT, ofd_thread_info::fti_buf, ofd_thread_info::fti_off, GOTO, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, ofd_info(), ofd_name(), ofd_device::ofd_osd, ofd_seq_last_oid(), ofd_seq::os_lastid_obj, ofd_seq::os_oi, POSTID, and RETURN.
Referenced by ofd_orphans_destroy(), and ofd_seq_load().
struct ofd_seq* ofd_seq_load (const struct lu_env * env, struct ofd_device * ofd, u64 seq) [read]
Return ofd_seq structure filled with valid data.
This function gets the ofd_seq by sequence number and read corresponding data from disk.
Parameters:
[in] env execution environment
[in] ofd OFD device
[in] seq sequence number
Return values:
ofd_seq structure filled with data
ERR_PTR pointer on error
Definition at line 362 of file ofd_fs.c.
References __u64, CERROR, cleanup(), dt_object_format::dof_type, dt_attr_get(), dt_find_or_create(), dt_mode_to_dft(), dt_record_read(), ENTRY, ofd_thread_info::fti_attr, ofd_thread_info::fti_buf, ofd_thread_info::fti_dof, ofd_thread_info::fti_fid, ofd_thread_info::fti_off, GOTO, INIT_LIST_HEAD, lu_attr::la_mode, LA_MODE, lu_attr::la_size, lu_attr::la_valid, lu_buf::lb_buf, lu_buf::lb_len, le64_to_cpu, LPU64, LPX64, lr_server_data::lsd_osd_index, lu_last_id_fid(), lu_target::lut_lsd, OBD_ALLOC_PTR, OBD_FREE_PTR, ofd_info(), OFD_INIT_OBJID, ofd_device::ofd_lut, ofd_name(), ofd_device::ofd_osd, ofd_seq_add(), ofd_seq_get(), ofd_seq_last_oid_set(), ofd_seq_last_oid_write(), ofd_seq_put(), ofd_seq::os_create_lock, ofd_seq::os_last_oid_lock, ofd_seq::os_lastid_obj, ofd_seq::os_list, ofd_seq::os_oi, ofd_seq::os_refc, ostid_set_seq(), and RETURN.
Referenced by ofd_create_hdl(), ofd_echo_create(), ofd_get_info_hdl(), ofd_preprw(), and ofd_preprw_write().
void ofd_seq_put (const struct lu_env * env, struct ofd_seq * oseq)
Drop a reference to ofd_seq.
The paired function to the ofd_seq_get(). It decrease the reference counter of the ofd_seq structure and free it if that reference was last one.
Parameters:
[in] env execution environment
[in] oseq ofd_seq structure to put
Definition at line 109 of file ofd_fs.c.
References dt_object::do_lu, LASSERT, list_empty(), lu_object_put(), OBD_FREE_PTR, ofd_seq::os_lastid_obj, ofd_seq::os_list, and ofd_seq::os_refc.
Referenced by ofd_create_hdl(), ofd_echo_create(), ofd_get_info_hdl(), ofd_orphans_destroy(), ofd_preprw(), ofd_preprw_write(), ofd_seq_add(), ofd_seq_load(), and ofd_seqs_free().
void ofd_seqs_fini (const struct lu_env * env, struct ofd_device * ofd)
Stop FLDB and SEQ services on OFD.
This function is part of OFD cleanup process.
Parameters:
[in] env execution environment
[in] ofd OFD device
Definition at line 332 of file ofd_fs.c.
References CERROR, LASSERT, list_empty(), ofd_deregister_seq_exp(), ofd_fid_fini(), ofd_fld_fini(), ofd_name(), ofd_device::ofd_seq_list, and ofd_seqs_free().
Referenced by ofd_fs_cleanup(), and ofd_fs_setup().
void ofd_seqs_free (const struct lu_env * env, struct ofd_device * ofd)
Free sequence structures on OFD.
This function is part of OFD cleanup process, it goes through the list of ofd_seq structures stored in ofd_device structure and frees them.
Parameters:
[in] env execution environment
[in] ofd OFD device
Definition at line 304 of file ofd_fs.c.
References INIT_LIST_HEAD, list_del_init(), list_empty(), list_for_each_entry_safe, list_move(), list_head::next, ofd_device::ofd_seq_list, ofd_device::ofd_seq_list_lock, ofd_seq_put(), and ofd_seq::os_list.
Referenced by ofd_lfsck_out_notify(), and ofd_seqs_fini().
int ofd_seqs_init (const struct lu_env * env, struct ofd_device * ofd)
Initialize SEQ and FLD service on OFD.
This is part of OFD setup process.
Parameters:
[in] env execution environment
[in] ofd OFD device
Return values:
0 on successful services initialization
negative value on error
Definition at line 572 of file ofd_fs.c.
References CERROR, GOTO, INIT_LIST_HEAD, ofd_fid_fini(), ofd_fid_init(), ofd_fld_fini(), ofd_fld_init(), ofd_name(), ofd_register_seq_exp(), ofd_device::ofd_seq_count, ofd_device::ofd_seq_list, ofd_device::ofd_seq_list_lock, and RETURN.
Referenced by ofd_fs_setup().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.