Lustre: lustre/ofd/ofd_objects.c File Reference
lustre/ofd/ofd_objects.c File Reference
#include <dt_object.h>
#include <lustre/lustre_idl.h>
#include <lustre_lfsck.h>
#include "ofd_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_FILTER
Functions
static int ofd_version_get_check (struct ofd_thread_info *info, struct ofd_object *fo)
Get object version from disk and check it.
struct ofd_object * ofd_object_find (const struct lu_env *env, struct ofd_device *ofd, const struct lu_fid *fid)
Get OFD object by FID.
int ofd_object_ff_load (const struct lu_env *env, struct ofd_object *fo)
Get FID of parent MDT object.
void ofd_object_put (const struct lu_env *env, struct ofd_object *fo)
Put OFD object reference.
int ofd_precreate_objects (const struct lu_env *env, struct ofd_device *ofd, u64 id, struct ofd_seq *oseq, int nr, int sync)
Precreate the given number nr of objects in the given sequence oseq.
int ofd_attr_handle_ugid (const struct lu_env *env, struct ofd_object *fo, struct lu_attr *la, int is_setattr)
Fix the OFD object ownership.
int ofd_attr_set (const struct lu_env *env, struct ofd_object *fo, struct lu_attr *la, struct filter_fid *ff)
Set OFD object attributes.
int ofd_object_punch (const struct lu_env *env, struct ofd_object *fo, __u64 start, __u64 end, struct lu_attr *la, struct filter_fid *ff, struct obdo *oa)
Truncate/punch OFD object.
int ofd_object_destroy (const struct lu_env *env, struct ofd_object *fo, int orphan)
Destroy OFD object.
int ofd_attr_get (const struct lu_env *env, struct ofd_object *fo, struct lu_attr *la)
Get OFD object attributes.
Define Documentation
#define DEBUG_SUBSYSTEM S_FILTER
Definition at line 41 of file ofd_objects.c.
Function Documentation
int ofd_attr_get (const struct lu_env * env, struct ofd_object * fo, struct lu_attr * la)
Get OFD object attributes.
This function gets OFD object regular attributes. It is used to serve incoming request as well as for local OFD purposes.
Parameters:
[in] env execution environment
[in] fo OFD object
[in] la object attributes
Return values:
0 if successful
negative value on error
Definition at line 778 of file ofd_objects.c.
References dt_attr_get(), ENTRY, ofd_object_child(), ofd_object_exists(), and RETURN.
Referenced by ofd_echo_getattr(), ofd_getattr_hdl(), ofd_lvbo_init(), ofd_lvbo_update(), and ofd_sync_hdl().
int ofd_attr_handle_ugid (const struct lu_env * env, struct ofd_object * fo, struct lu_attr * la, int is_setattr)
Fix the OFD object ownership.
If the object still has SUID+SGID bits set, meaning that it was precreated by the MDT before it was assigned to any file, (see ofd_precreate_objects()) then we will accept the UID+GID if sent by the client for initializing the ownership of this object. We only allow this to happen once (so clear these bits) and later only allow setattr.
Parameters:
[in] env execution environment
[in] fo OFD object
[in] la object attributes
[in] is_setattr was this function called from setattr or not
Return values:
0 if successful
negative value on error
Definition at line 434 of file ofd_objects.c.
References dt_attr_get(), ENTRY, ofd_thread_info::fti_attr2, LA_GID, lu_attr::la_mode, LA_MODE, LA_UID, lu_attr::la_valid, LASSERT, ofd_info(), ofd_object_child(), and RETURN.
Referenced by ofd_attr_set(), ofd_object_punch(), and ofd_write_attr_set().
int ofd_attr_set (const struct lu_env * env, struct ofd_object * fo, struct lu_attr * la, struct filter_fid * ff)
Set OFD object attributes.
This function sets OFD object attributes taken from incoming request. It sets not only regular attributes but also XATTR_NAME_FID extended attribute if needed. The "fid" xattr allows the object's MDT parent inode to be found and verified by LFSCK and other tools in case of inconsistency.
Parameters:
[in] env execution environment
[in] fo OFD object
[in] la object attributes
[in] ff filter_fid structure, contains additional attributes
Return values:
0 if successful
negative value on error
Definition at line 491 of file ofd_objects.c.
References dt_attr_set(), dt_declare_attr_set(), dt_declare_xattr_set(), dt_xattr_set(), ENTRY, lu_fid::f_oid, lu_fid::f_seq, filter_fid::ff_parent, ofd_mod_data::fmd_mactime_xid, ofd_thread_info::fti_buf, ofd_thread_info::fti_exp, ofd_thread_info::fti_xid, GOTO, LA_ATIME, LA_CTIME, LA_MTIME, LA_SIZE, lu_attr::la_valid, lu_buf::lb_buf, lu_buf::lb_len, le32_to_cpu, le64_to_cpu, lu_object_header::loh_fid, ofd_attr_handle_ugid(), ofd_fmd_get(), ofd_fmd_put(), ofd_info(), ofd_obj2dev(), ofd_object_child(), ofd_object_exists(), ofd_object_ff_load(), ofd_trans_create(), ofd_trans_start(), ofd_trans_stop(), ofd_version_get_check(), ofd_write_lock(), ofd_write_unlock(), ofd_object::ofo_header, ofd_object::ofo_pfid, stop, and XATTR_NAME_FID.
Referenced by ofd_echo_setattr(), and ofd_setattr_hdl().
int ofd_object_destroy (const struct lu_env * env, struct ofd_object * fo, int orphan)
Destroy OFD object.
This function destroys OFD object. If object wasn't used at all (orphan) then local transaction is used, which means the transaction data is not returned back in reply.
Parameters:
[in] env execution environment
[in] fo OFD object
[in] orphan flag to indicate that object is orphaned
Return values:
0 if successful
negative value on error
Definition at line 722 of file ofd_objects.c.
References dt_declare_destroy(), dt_declare_ref_del(), dt_destroy(), dt_ref_del(), dt_trans_start_local(), ENTRY, GOTO, lu_object_header::loh_fid, ofd_fmd_drop, ofd_info(), ofd_obj2dev(), ofd_object_child(), ofd_object_exists(), ofd_device::ofd_osd, ofd_trans_create(), ofd_trans_start(), ofd_trans_stop(), ofd_write_lock(), ofd_write_unlock(), ofd_object::ofo_header, RETURN, and stop.
Referenced by ofd_destroy_by_fid().
int ofd_object_ff_load (const struct lu_env * env, struct ofd_object * fo)
Get FID of parent MDT object.
This function reads extended attribute XATTR_NAME_FID of OFD object which contains the MDT parent object FID and saves it in ofd_object::ofo_pfid.
The filter_fid::ff_parent::f_ver field currently holds the OST-object index in the parent MDT-object's layout EA, not the actual FID::f_ver of the parent. We therefore access it via the macro f_stripe_idx.
Parameters:
[in] env execution environment
[in] fo OFD object
Return values:
0 if successful
-ENODATA if there is no such xattr
negative value on error
Definition at line 138 of file ofd_objects.c.
References buf, dt_xattr_get(), lu_fid::f_oid, lu_fid::f_seq, filter_fid_old::ff_parent, fid_is_sane(), fid_zero(), ofd_thread_info::fti_buf, ofd_thread_info::fti_mds_fid_old, lu_buf::lb_buf, lu_buf::lb_len, le32_to_cpu, le64_to_cpu, ofd_info(), ofd_object_child(), ofd_object::ofo_pfid, and XATTR_NAME_FID.
Referenced by ofd_attr_set(), ofd_object_punch(), ofd_verify_ff(), and ofd_write_attr_set().
struct ofd_object* ofd_object_find (const struct lu_env * env, struct ofd_device * ofd, const struct lu_fid * fid) [read]
Get OFD object by FID.
This function finds OFD slice of compound object with the given FID.
Parameters:
[in] env execution environment
[in] ofd OFD device
[in] fid FID of the object
Return values:
pointer to the found ofd_object
ERR_PTR(errno) in case of error
Definition at line 102 of file ofd_objects.c.
References dt_device::dd_lu_dev, ENTRY, likely, lu_object_find(), ofd_device::ofd_dt_dev, ofd_obj(), and RETURN.
Referenced by ofd_commitrw_read(), ofd_commitrw_write(), ofd_fiemap_get(), ofd_ioc_get_obj_version(), ofd_ladvise_hdl(), ofd_lvbo_init(), ofd_lvbo_update(), ofd_object_find_exists(), ofd_precreate_objects(), ofd_preprw_read(), and ofd_preprw_write().
int ofd_object_punch (const struct lu_env * env, struct ofd_object * fo, __u64 start, __u64 end, struct lu_attr * la, struct filter_fid * ff, struct obdo * oa)
Truncate/punch OFD object.
This function frees all of the allocated object's space from the start offset to the end offset. For truncate() operations the end offset is OBD_OBJECT_EOF. The functionality to punch holes in an object via fallocate(FALLOC_FL_PUNCH_HOLE) is not yet implemented (see LU-3606).
Parameters:
[in] env execution environment
[in] fo OFD object
[in] start start offset to punch from
[in] end end of punch
[in] la object attributes
[in] ff filter_fid structure
[in] oa obdo struct from incoming request
Return values:
0 if successful
negative value on error
Definition at line 600 of file ofd_objects.c.
References dt_attr_set(), dt_declare_attr_set(), dt_declare_punch(), dt_declare_xattr_set(), dt_punch(), dt_xattr_set(), ENTRY, lu_fid::f_oid, lu_fid::f_seq, filter_fid::ff_parent, ofd_mod_data::fmd_mactime_xid, ofd_thread_info::fti_buf, ofd_thread_info::fti_exp, ofd_thread_info::fti_xid, GOTO, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, le32_to_cpu, le64_to_cpu, lu_object_header::loh_fid, obdo::o_valid, OBD_MD_FLFID, OBD_OBJECT_EOF, ofd_attr_handle_ugid(), ofd_fmd_get(), ofd_fmd_put(), ofd_info(), ofd_device::ofd_lfsck_verify_pfid, ofd_obj2dev(), ofd_object_child(), ofd_object_exists(), ofd_object_ff_load(), ofd_trans_create(), ofd_trans_start(), ofd_trans_stop(), ofd_verify_ff(), ofd_version_get_check(), ofd_write_lock(), ofd_write_unlock(), ofd_object::ofo_header, ofd_object::ofo_pfid, stop, and XATTR_NAME_FID.
Referenced by ofd_punch_hdl().
void ofd_object_put (const struct lu_env * env, struct ofd_object * fo)
Put OFD object reference.
Parameters:
[in] env execution environment
[in] fo OFD object
Definition at line 174 of file ofd_objects.c.
References dt_object::do_lu, lu_object_put(), and ofd_object::ofo_obj.
Referenced by ofd_commitrw_read(), ofd_commitrw_write(), ofd_destroy_by_fid(), ofd_echo_getattr(), ofd_echo_setattr(), ofd_fiemap_get(), ofd_getattr_hdl(), ofd_ioc_get_obj_version(), ofd_ladvise_hdl(), ofd_lvbo_init(), ofd_lvbo_update(), ofd_object_find_exists(), ofd_precreate_objects(), ofd_preprw_read(), ofd_preprw_write(), ofd_punch_hdl(), ofd_setattr_hdl(), and ofd_sync_hdl().
int ofd_precreate_objects (const struct lu_env * env, struct ofd_device * ofd, u64 id, struct ofd_seq * oseq, int nr, int sync)
Precreate the given number nr of objects in the given sequence oseq.
This function precreates new OST objects in the given sequence. The precreation starts from id and creates nr objects sequentially.
Notes: This function may create fewer objects than requested.
We mark object SUID+SGID to flag it for accepting UID+GID from client on first write. Currently the permission bits on the OST are never used, so this is OK.
Initialize a/c/m time so any client timestamp will always be newer and update the inode. The ctime = 0 case is also handled specially in osd_inode_setattr(). See LU-221, LU-1042 for details.
Parameters:
[in] env execution environment
[in] ofd OFD device
[in] id object ID to start precreation from
[in] oseq object sequence
[in] nr number of objects to precreate
[in] sync synchronous precreation flag
Return values:
0 if successful
negative value on error
Definition at line 206 of file ofd_objects.c.
References CDEBUG, CERROR, cpu_to_le64, D_ERROR, D_INODE, D_OTHER, dt_device::dd_record_fid_accessed, DFID, dt_object::do_lu, dt_object_format::dof_type, DOSTID, dt_create(), dt_declare_create(), dt_declare_record_write(), dt_mode_to_dft(), dt_record_write(), dt_trans_start_local(), dt_write_lock(), dt_write_unlock(), ENTRY, ergo, fid_seq_is_mdt0(), fid_set_id(), ofd_thread_info::fti_attr, ofd_thread_info::fti_buf, ofd_thread_info::fti_dof, ofd_thread_info::fti_fid, ofd_thread_info::fti_lr, ofd_thread_info::fti_off, GOTO, IDIF_MAX_OID, lu_attr::la_atime, LA_ATIME, lu_attr::la_ctime, LA_CTIME, lu_attr::la_mode, LA_MODE, lu_attr::la_mtime, LA_MTIME, LA_TYPE, lu_attr::la_valid, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, LE_FID_ACCESSED, lfsck_in_notify(), lfsck_pack_rfa(), LFSCK_TYPE_LAYOUT, likely, LPU64, LPX64, lu_object_fid(), OBD_ALLOC, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_DANGLING, OBD_FAIL_LFSCK_SKIP_LASTID, OBD_FREE, OBIF_MAX_OID, ofd_info(), ofd_name(), ofd_object_child(), ofd_object_exists(), ofd_object_find(), ofd_object_put(), ofd_device::ofd_osd, ofd_seq_last_oid(), ofd_seq_last_oid_set(), ofd_trans_create(), ofd_trans_stop(), ofd_write_lock(), ofd_write_unlock(), ofd_object::ofo_obj, ofd_seq::os_lastid_obj, ofd_seq::os_oi, ostid_seq(), PFID, RETURN, thandle::th_sync, and unlikely.
Referenced by ofd_create_hdl(), ofd_echo_create(), and ofd_preprw_write().
static int ofd_version_get_check (struct ofd_thread_info * info, struct ofd_object * fo) [static]
Get object version from disk and check it.
This function checks object version from disk with ofd_thread_info::fti_pre_version filled from incoming RPC. This is part of VBR (Version-Based Recovery) and ensures that object has the same version upon replay as it has during original modification.
Parameters:
[in] info execution thread OFD private data
[in] fo OFD object
Return values:
0 if version matches
-EOVERFLOW on version mismatch
Definition at line 63 of file ofd_objects.c.
References CDEBUG, D_INODE, dt_version_get(), obd_export::exp_lock, obd_export::exp_vbr_failed, ofd_thread_info::fti_env, ofd_thread_info::fti_exp, ofd_thread_info::fti_pre_version, LASSERT, LPX64, ofd_object_child(), ofd_object_exists(), and RETURN.
Referenced by ofd_attr_set(), and ofd_object_punch().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.