Lustre: lustre/ofd/ofd_io.c File Reference
lustre/ofd/ofd_io.c File Reference
#include <linux/kthread.h>
#include "ofd_internal.h"
Data Structures
struct ofd_inconsistency_item
struct ofd_soft_sync_callback
Defines
#define DEBUG_SUBSYSTEM S_FILTER
Functions
static void ofd_inconsistency_verify_one (const struct lu_env *env, struct ofd_device *ofd, struct ofd_inconsistency_item *oii, struct lfsck_request *lr)
Verify single object for parent FID consistency.
static int ofd_inconsistency_verification_main (void *args)
Verification thread to check parent FID consistency.
int ofd_start_inconsistency_verification_thread (struct ofd_device *ofd)
Start parent FID verification thread.
int ofd_stop_inconsistency_verification_thread (struct ofd_device *ofd)
Stop parent FID verification thread.
static void ofd_add_inconsistency_item (const struct lu_env *env, struct ofd_object *fo, struct obdo *oa)
Add new item for parent FID verification.
int ofd_verify_ff (const struct lu_env *env, struct ofd_object *fo, struct obdo *oa)
Verify parent FID of an object.
static int ofd_preprw_read (const struct lu_env *env, struct obd_export *exp, struct ofd_device *ofd, const struct lu_fid *fid, struct lu_attr *la, struct obdo *oa, int niocount, struct niobuf_remote *rnb, int *nr_local, struct niobuf_local *lnb, char *jobid)
Prepare buffers for read request processing.
static int ofd_preprw_write (const struct lu_env *env, struct obd_export *exp, struct ofd_device *ofd, const struct lu_fid *fid, struct lu_attr *la, struct obdo *oa, int objcount, struct obd_ioobj *obj, struct niobuf_remote *rnb, int *nr_local, struct niobuf_local *lnb, char *jobid)
Prepare buffers for write request processing.
int ofd_preprw (const struct lu_env *env, int cmd, struct obd_export *exp, struct obdo *oa, int objcount, struct obd_ioobj *obj, struct niobuf_remote *rnb, int *nr_local, struct niobuf_local *lnb)
Prepare bulk IO requests for processing.
static int ofd_commitrw_read (const struct lu_env *env, struct ofd_device *ofd, const struct lu_fid *fid, int objcount, int niocount, struct niobuf_local *lnb)
Drop reference on local buffers for read bulk IO.
static int ofd_write_attr_set (const struct lu_env *env, struct ofd_device *ofd, struct ofd_object *ofd_obj, struct lu_attr *la, struct filter_fid *ff)
Set attributes of object during write bulk IO processing.
static void ofd_cb_soft_sync (struct lu_env *env, struct thandle *th, struct dt_txn_commit_cb *cb, int err)
Callback function for "soft sync" update.
static int ofd_soft_sync_cb_add (struct thandle *th, struct obd_export *exp)
Add callback for "soft sync" processing.
static int ofd_commitrw_write (const struct lu_env *env, struct obd_export *exp, struct ofd_device *ofd, const struct lu_fid *fid, struct lu_attr *la, struct filter_fid *ff, int objcount, int niocount, struct niobuf_local *lnb, unsigned long granted, int old_rc)
Commit bulk IO buffers to the storage.
int ofd_commitrw (const struct lu_env *env, int cmd, struct obd_export *exp, struct obdo *oa, int objcount, struct obd_ioobj *obj, struct niobuf_remote *rnb, int npages, struct niobuf_local *lnb, int old_rc)
Commit bulk IO to the storage.
Define Documentation
#define DEBUG_SUBSYSTEM S_FILTER
Definition at line 41 of file ofd_io.c.
Function Documentation
static void ofd_add_inconsistency_item (const struct lu_env * env, struct ofd_object * fo, struct obdo * oa) [static]
Add new item for parent FID verification.
Prepare new verification item and pass it to the dedicated verification thread for further processing.
Parameters:
[in] env execution environment
[in] fo OFD object
[in] oa OBDO structure with PFID
Definition at line 320 of file ofd_io.c.
References dt_object::do_lu, lu_fid::f_oid, lu_fid::f_seq, INIT_LIST_HEAD, list_add_tail(), list_empty(), lu_object_get(), obdo::o_parent_oid, obdo::o_parent_seq, obdo::o_stripe_idx, OBD_ALLOC_PTR, OBD_FREE_PTR, ofd_device::ofd_inconsistency_list, ofd_device::ofd_inconsistency_lock, ofd_device::ofd_inconsistency_thread, ofd_obj2dev(), ofd_object::ofo_obj, ofd_object::ofo_pfid_checking, ofd_object::ofo_pfid_verified, ofd_inconsistency_item::oii_list, ofd_inconsistency_item::oii_obj, ofd_inconsistency_item::oii_pfid, and ptlrpc_thread::t_ctl_waitq.
Referenced by ofd_verify_ff().
static void ofd_cb_soft_sync (struct lu_env * env, struct thandle * th, struct dt_txn_commit_cb * cb, int err) [static]
Callback function for "soft sync" update.
Reset fed_soft_sync_count upon committing the "soft_sync" update. See ofd_soft_sync_cb_add() below for more details on soft sync.
Parameters:
[in] env execution environment
[in] th transaction handle
[in] cb callback data
[in] err error code
Definition at line 931 of file ofd_io.c.
References CDEBUG, class_export_cb_put, D_INODE, OBD_FREE_PTR, ofd_soft_sync_callback::ossc_cb, and ofd_soft_sync_callback::ossc_exp.
Referenced by ofd_soft_sync_cb_add().
int ofd_commitrw (const struct lu_env * env, int cmd, struct obd_export * exp, struct obdo * oa, int objcount, struct obd_ioobj * obj, struct niobuf_remote * rnb, int npages, struct niobuf_local * lnb, int old_rc)
Commit bulk IO to the storage.
This is companion function to the ofd_preprw(). It finishes bulk IO request processing by committing buffers to the storage (WRITE) and/or freeing those buffers (read/write). See ofd_commitrw_read() and ofd_commitrw_write() for details about each type of IO.
Parameters:
[in] env execution environment
[in] cmd IO type (READ/WRITE)
[in] exp OBD export of client
[in] oa OBDO structure from client
[in] objcount always 1
[in] obj object data
[in] rnb remote buffers
[in] npages number of local buffers
[in] lnb local buffers
[in] old_rc result of processing at this point
Return values:
0 on successful commit
negative value on error
Definition at line 1163 of file ofd_io.c.
References __u64, ofd_mod_data::fmd_mactime_xid, ofd_thread_info::fti_attr, ofd_thread_info::fti_mds_fid, ofd_thread_info::fti_resid, ofd_thread_info::fti_xid, la_from_obdo(), LA_GID, LA_UID, LASSERT, LBUG, LDLM_EXTENT, ldlm_res_lvbo_update(), ldlm_resource_get(), ldlm_resource_putref(), ldlm_valblock_ops::lvbo_update, ldlm_namespace::ns_lvbo, obdo::o_flags, obdo::o_oi, obdo::o_valid, OBD_BRW_OVER_GRPQUOTA, OBD_BRW_OVER_USRQUOTA, OBD_BRW_READ, OBD_BRW_WRITE, OBD_FL_NO_GRPQUOTA, OBD_FL_NO_USRQUOTA, OBD_MD_FLATIME, OBD_MD_FLCTIME, OBD_MD_FLFID, OBD_MD_FLFLAGS, OBD_MD_FLGID, OBD_MD_FLGRPQUOTA, OBD_MD_FLMTIME, OBD_MD_FLUID, OBD_MD_FLUSRQUOTA, obdo_from_la(), ofd_commitrw_read(), ofd_commitrw_write(), ofd_exp(), ofd_fmd_find(), ofd_fmd_put(), ofd_info(), ofd_device::ofd_namespace, ofd_prepare_fidea(), OFD_VALID_FLAGS, ost_id::oi_fid, ost_fid_build_resid(), and RETURN.
static int ofd_commitrw_read (const struct lu_env * env, struct ofd_device * ofd, const struct lu_fid * fid, int objcount, int niocount, struct niobuf_local * lnb) [static]
Drop reference on local buffers for read bulk IO.
This will free all local buffers use by this read request.
Parameters:
[in] env execution environment
[in] ofd OFD device
[in] fid object FID
[in] objcount always 1
[in] niocount number of local buffers
[in] lnb local buffers
Return values:
0 on successful execution
negative value on error
Definition at line 772 of file ofd_io.c.
References dt_bufs_put(), ENTRY, LASSERT, ofd_object_child(), ofd_object_exists(), ofd_object_find(), ofd_object_put(), ofd_read_unlock(), and RETURN.
Referenced by ofd_commitrw().
static int ofd_commitrw_write (const struct lu_env * env, struct obd_export * exp, struct ofd_device * ofd, const struct lu_fid * fid, struct lu_attr * la, struct filter_fid * ff, int objcount, int niocount, struct niobuf_local * lnb, unsigned long granted, int old_rc) [static]
Commit bulk IO buffers to the storage.
This function finalizes write IO processing by writing data to the disk. That write can be synchronous or asynchronous depending on buffers flags.
Parameters:
[in] env execution environment
[in] exp OBD export of client
[in] ofd OFD device
[in] fid FID of object
[in] la object attributes
[in] ff parent FID of object
[in] objcount always 1
[in] niocount number of local buffers
[in] lnb local buffers
[in] granted grant space consumed for the bulk I/O
[in] old_rc result of processing at this point
Return values:
0 on successful commit
negative value on error
Definition at line 1009 of file ofd_io.c.
References CDEBUG, D_INODE, dt_attr_get(), dt_attr_set(), dt_bufs_put(), dt_commit_async(), dt_declare_attr_set(), dt_declare_write_commit(), dt_write_commit(), ENTRY, filter_export_data::fed_soft_sync_count, GOTO, LA_ATIME, LA_CTIME, LA_MTIME, lu_attr::la_valid, LASSERT, OBD_BRW_ASYNC, OBD_BRW_SOFT_SYNC, OBD_FAIL_CHECK, OBD_FAIL_OST_DQACQ_NET, ofd_grant_commit(), ofd_grant_commit_cb_add(), ofd_object_child(), ofd_object_exists(), ofd_object_find(), ofd_object_put(), ofd_device::ofd_osd, ofd_read_unlock(), ofd_soft_sync_cb_add(), ofd_device::ofd_soft_sync_limit, ofd_device::ofd_syncjournal, ofd_trans_create(), ofd_trans_start(), ofd_trans_stop(), ofd_write_attr_set(), RETURN, and thandle::th_sync.
Referenced by ofd_commitrw().
static int ofd_inconsistency_verification_main (void * args) [static]
Verification thread to check parent FID consistency.
Kernel thread to check consistency of parent FID for any new item added for checking by ofd_add_inconsistency_item().
Parameters:
[in] args OFD device
Return values:
0 on successful thread termination
negative value if thread can't start
Definition at line 154 of file ofd_io.c.
References dt_object::do_lu, ENTRY, GOTO, l_wait_event, LCT_DT_THREAD, LE_PAIRS_VERIFY, LFSCK_TYPE_LAYOUT, list_del_init(), list_empty(), list_entry, lfsck_request::lr_active, lfsck_request::lr_event, lu_env_fini(), lu_env_init(), lu_object_put(), list_head::next, OBD_ALLOC_PTR, OBD_FREE_PTR, ofd_device::ofd_inconsistency_list, ofd_device::ofd_inconsistency_lock, ofd_device::ofd_inconsistency_thread, ofd_inconsistency_verify_one(), ofd_write_lock(), ofd_write_unlock(), ofd_object::ofo_obj, ofd_object::ofo_pfid_checking, ofd_inconsistency_item::oii_list, ofd_inconsistency_item::oii_obj, RETURN, SVC_RUNNING, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, thread, thread_is_running(), thread_set_flags(), and unlikely.
Referenced by ofd_start_inconsistency_verification_thread().
static void ofd_inconsistency_verify_one (const struct lu_env * env, struct ofd_device * ofd, struct ofd_inconsistency_item * oii, struct lfsck_request * lr) [static]
Verify single object for parent FID consistency.
Part of LFSCK processing which checks single object PFID stored in extended attribute (XATTR) against real FID of MDT parent object received by LFSCK. This verifies that the OST object is being referenced by only a single MDT object.
Parameters:
[in] env execution environment
[in] ofd OFD device
[in] oii object-related local data
[in] lr LFSCK request data
Definition at line 65 of file ofd_io.c.
References CDEBUG, D_LFSCK, DFID, dt_object::do_lu, LASSERT, lfsck_in_notify(), lu_object_header::loh_fid, LPVS_INCONSISTENT, LPVS_INCONSISTENT_TOFIX, LPVS_INIT, lfsck_request::lr_fid, lfsck_request::lr_fid2, lfsck_request::lr_fid3, lfsck_request::lr_status, lu_object_put(), OBD_FREE_PTR, ofd_device::ofd_inconsistency_self_detected, ofd_device::ofd_inconsistency_self_repaired, ofd_name(), ofd_device::ofd_osd, ofd_write_lock(), ofd_write_unlock(), ofd_object::ofo_header, ofd_object::ofo_obj, ofd_object::ofo_pfid, ofd_object::ofo_pfid_checking, ofd_object::ofo_pfid_verified, ofd_inconsistency_item::oii_obj, ofd_inconsistency_item::oii_pfid, and PFID.
Referenced by ofd_inconsistency_verification_main().
int ofd_preprw (const struct lu_env * env, int cmd, struct obd_export * exp, struct obdo * oa, int objcount, struct obd_ioobj * obj, struct niobuf_remote * rnb, int * nr_local, struct niobuf_local * lnb)
Prepare bulk IO requests for processing.
This function does initial checks of IO and calls corresponding functions for read/write processing.
Parameters:
[in] env execution environment
[in] cmd IO type (read/write)
[in] exp OBD export of client
[in] oa OBDO structure from request
[in] objcount always 1
[in] obj object data
[in] rnb remote buffers
[in] nr_local number of local buffers
[in] lnb local buffers
Return values:
0 on successful prepare
negative value on error
Definition at line 685 of file ofd_io.c.
References CERROR, DOSTID, obd_export::exp_obd, ofd_thread_info::fti_attr, obd_ioobj::ioo_bufcnt, LA_ATIME, la_from_obdo(), LASSERT, obdo::o_oi, OBD_BRW_READ, OBD_BRW_WRITE, OBD_FAIL_CHECK, OBD_FAIL_SRV_ENOENT, OBD_MD_FLGETATTR, obd_device::obd_name, obdo_from_la(), ofd_exp(), ofd_grant_prepare_read(), ofd_info_init(), ofd_name(), ofd_preprw_read(), ofd_preprw_write(), ofd_seq_load(), ofd_seq_put(), ost_id::oi_fid, ofd_seq::os_destroys_in_progress, ostid_seq(), POSTID, PTLRPC_MAX_BRW_PAGES, RETURN, tgt_ses_info(), tgt_ses_req(), tsi2ofd_info(), and tgt_session_info::tsi_jobid.
static int ofd_preprw_read (const struct lu_env * env, struct obd_export * exp, struct ofd_device * ofd, const struct lu_fid * fid, struct lu_attr * la, struct obdo * oa, int niocount, struct niobuf_remote * rnb, int * nr_local, struct niobuf_local * lnb, char * jobid) [static]
Prepare buffers for read request processing.
This function converts remote buffers from client to local buffers and prepares the latter.
Parameters:
[in] env execution environment
[in] exp OBD export of client
[in] ofd OFD device
[in] fid FID of object
[in] la object attributes
[in] oa OBDO structure from client
[in] niocount number of remote buffers
[in] rnb remote buffers
[in] nr_local number of local buffers
[in] lnb local buffers
[in] jobid job ID name
Return values:
0 on successful prepare
negative value on error
Definition at line 440 of file ofd_io.c.
References dt_attr_get(), dt_bufs_get(), dt_bufs_put(), dt_read_prep(), ENTRY, GOTO, LASSERT, LPROC_OFD_STATS_READ, obdo::o_valid, OBD_MD_FLFID, ofd_counter_incr(), ofd_device::ofd_lfsck_verify_pfid, ofd_object_child(), ofd_object_exists(), ofd_object_find(), ofd_object_put(), ofd_read_lock(), ofd_read_unlock(), ofd_verify_ff(), PTLRPC_MAX_BRW_PAGES, RETURN, niobuf_remote::rnb_len, and unlikely.
Referenced by ofd_preprw().
static int ofd_preprw_write (const struct lu_env * env, struct obd_export * exp, struct ofd_device * ofd, const struct lu_fid * fid, struct lu_attr * la, struct obdo * oa, int objcount, struct obd_ioobj * obj, struct niobuf_remote * rnb, int * nr_local, struct niobuf_local * lnb, char * jobid) [static]
Prepare buffers for write request processing.
This function converts remote buffers from client to local buffers and prepares the latter. If there is recovery in progress and required object is missing then it can be re-created before write.
Parameters:
[in] env execution environment
[in] exp OBD export of client
[in] ofd OFD device
[in] fid FID of object
[in] la object attributes
[in] oa OBDO structure from client
[in] objcount always 1
[in] obj object data
[in] rnb remote buffers
[in] nr_local number of local buffers
[in] lnb local buffers
[in] jobid job ID name
Return values:
0 on successful prepare
negative value on error
Definition at line 524 of file ofd_io.c.
References CERROR, DOSTID, dt_bufs_get(), dt_bufs_put(), dt_write_prep(), ENTRY, exp_connect_rmtclient(), obd_export::exp_obd, fid_oid(), fid_seq_is_idif(), fid_seq_is_mdt0(), fid_seq_is_norm(), GOTO, IDIF_MAX_OID, obd_ioobj::ioo_bufcnt, obd_ioobj::ioo_oid, LASSERT, niobuf_local::lnb_flags, niobuf_local::lnb_rc, LPROC_OFD_STATS_WRITE, LPX64, LUSTRE_DATA_SEQ_MAX_WIDTH, obdo::o_oi, obdo::o_valid, OBD_BRW_GRANTED, OBD_BRW_NOQUOTA, OBD_MD_FLFID, obd_device::obd_name, obd_device::obd_recovering, ofd_counter_incr(), ofd_grant_commit(), ofd_grant_prepare_read(), ofd_grant_prepare_write(), ofd_device::ofd_lfsck_verify_pfid, ofd_name(), ofd_object_child(), ofd_object_exists(), ofd_object_find(), ofd_object_put(), ofd_precreate_batch(), ofd_precreate_objects(), ofd_read_lock(), ofd_read_unlock(), ofd_seq_last_oid(), ofd_seq_load(), ofd_seq_put(), ofd_verify_ff(), ofd_seq::os_create_lock, POSTID, PTLRPC_MAX_BRW_PAGES, RETURN, niobuf_remote::rnb_flags, niobuf_remote::rnb_len, and unlikely.
Referenced by ofd_preprw().
static int ofd_soft_sync_cb_add (struct thandle * th, struct obd_export * exp) [static]
Add callback for "soft sync" processing.
The "soft sync" mechanism does asynchronous commit when OBD_BRW_SOFT_SYNC flag is set in client buffers. The intention is for this operation to commit pages belonging to a client which has "too many" outstanding unstable pages in its cache. See LU-2139 for details.
This function adds callback to be called when commit is done.
Parameters:
[in] th transaction handle
[in] exp OBD export of client
Return values:
0 on successful callback adding
negative value on error
Definition at line 961 of file ofd_io.c.
References class_export_cb_get, class_export_cb_put, dt_txn_commit_cb::dcb_func, dt_txn_commit_cb::dcb_linkage, dt_txn_commit_cb::dcb_name, dt_trans_cb_add(), INIT_LIST_HEAD, OBD_ALLOC_PTR, OBD_FREE_PTR, ofd_cb_soft_sync(), ofd_soft_sync_callback::ossc_cb, ofd_soft_sync_callback::ossc_exp, and strlcpy().
Referenced by ofd_commitrw_write().
int ofd_start_inconsistency_verification_thread (struct ofd_device * ofd)
Start parent FID verification thread.
See ofd_inconsistency_verification_main().
Parameters:
[in] ofd OFD device
Return values:
0 on successful start of thread
negative value on error
Definition at line 247 of file ofd_io.c.
References CERROR, l_wait_event, ofd_device::ofd_inconsistency_lock, ofd_device::ofd_inconsistency_thread, ofd_inconsistency_verification_main(), ofd_name(), ptlrpc_thread::t_ctl_waitq, thread, thread_is_running(), thread_is_stopped(), thread_set_flags(), and unlikely.
Referenced by ofd_init0().
int ofd_stop_inconsistency_verification_thread (struct ofd_device * ofd)
Stop parent FID verification thread.
Parameters:
[in] ofd OFD device
Return values:
0 on successful start of thread
-EALREADY if thread is already stopped
Definition at line 288 of file ofd_io.c.
References l_wait_event, ofd_device::ofd_inconsistency_lock, ofd_device::ofd_inconsistency_thread, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, thread, thread_is_init(), thread_is_stopped(), and thread_set_flags().
Referenced by ofd_fini().
int ofd_verify_ff (const struct lu_env * env, struct ofd_object * fo, struct obdo * oa)
Verify parent FID of an object.
Check the parent FID is sane and start extended verification procedure otherwise.
Parameters:
[in] env execution environment
[in] fo OFD object
[in] oa OBDO structure with PFID
Return values:
0 on successful verification
-EINPROGRESS if PFID is being repaired
-EPERM if PFID was verified but still insane
Definition at line 378 of file ofd_io.c.
References ENTRY, lu_fid::f_oid, lu_fid::f_seq, fid_is_sane(), likely, obdo::o_parent_oid, obdo::o_parent_seq, obdo::o_stripe_idx, ofd_add_inconsistency_item(), ofd_object_ff_load(), ofd_object::ofo_pfid, ofd_object::ofo_pfid_checking, ofd_object::ofo_pfid_verified, and RETURN.
Referenced by ofd_object_punch(), ofd_preprw_read(), and ofd_preprw_write().
static int ofd_write_attr_set (const struct lu_env * env, struct ofd_device * ofd, struct ofd_object * ofd_obj, struct lu_attr * la, struct filter_fid * ff) [static]
Set attributes of object during write bulk IO processing.
Change object attributes and write parent FID into extended attributes when needed.
Parameters:
[in] env execution environment
[in] ofd OFD device
[in] ofd_obj OFD object
[in] la object attributes
[in] ff parent FID
Return values:
0 on successful attributes update
negative value on error
Definition at line 813 of file ofd_io.c.
References __u64, cpu_to_le32, dt_attr_set(), dt_declare_attr_set(), dt_declare_xattr_set(), dt_trans_start_local(), dt_trans_stop(), dt_xattr_set(), ENTRY, lu_fid::f_oid, lu_fid::f_seq, filter_fid::ff_parent, ofd_thread_info::fti_buf, GOTO, LA_GID, LA_UID, lu_attr::la_valid, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, le32_to_cpu, le64_to_cpu, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_NOPFID, OBD_FAIL_LFSCK_UNMATCHED_PAIR1, OBD_FAIL_LFSCK_UNMATCHED_PAIR2, ofd_attr_handle_ugid(), ofd_info(), ofd_object_child(), ofd_object_ff_load(), ofd_device::ofd_osd, ofd_trans_create(), ofd_object::ofo_pfid, and XATTR_NAME_FID.
Referenced by ofd_commitrw_write().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.