Lustre: lustre/osc/osc_quota.c File Reference
lustre/osc/osc_quota.c File Reference
#include <obd.h>
#include "osc_internal.h"
Defines
#define MD_QUOTA_FLAG(type)
#define FL_QUOTA_FLAG(type)
#define HASH_QUOTA_BKT_BITS 5
#define HASH_QUOTA_CUR_BITS 5
#define HASH_QUOTA_MAX_BITS 15
Functions
static struct osc_quota_info * osc_oqi_alloc (u32 id)
int osc_quota_chkdq (struct client_obd *cli, const unsigned int qid[])
int osc_quota_setdq (struct client_obd *cli, const unsigned int qid[], u64 valid, u32 flags)
static unsigned oqi_hashfn (struct cfs_hash *hs, const void *key, unsigned mask)
static int oqi_keycmp (const void *key, struct hlist_node *hnode)
static void * oqi_key (struct hlist_node *hnode)
static void * oqi_object (struct hlist_node *hnode)
static void oqi_get (struct cfs_hash *hs, struct hlist_node *hnode)
static void oqi_put_locked (struct cfs_hash *hs, struct hlist_node *hnode)
static void oqi_exit (struct cfs_hash *hs, struct hlist_node *hnode)
int osc_quota_setup (struct obd_device *obd)
int osc_quota_cleanup (struct obd_device *obd)
int osc_quotactl (struct obd_device *unused, struct obd_export *exp, struct obd_quotactl *oqctl)
Variables
static struct cfs_hash_ops quota_hash_ops
Define Documentation
#define FL_QUOTA_FLAG (type)
Value:
((type == USRQUOTA) ? OBD_FL_NO_USRQUOTA \
                                                : OBD_FL_NO_GRPQUOTA)
Definition at line 71 of file osc_quota.c.
Referenced by osc_quota_setdq().
#define HASH_QUOTA_BKT_BITS 5
Definition at line 193 of file osc_quota.c.
Referenced by osc_quota_setup().
#define HASH_QUOTA_CUR_BITS 5
Definition at line 194 of file osc_quota.c.
Referenced by osc_quota_setup().
#define HASH_QUOTA_MAX_BITS 15
Definition at line 195 of file osc_quota.c.
Referenced by osc_quota_setup().
#define MD_QUOTA_FLAG (type)
Value:
((type == USRQUOTA) ? OBD_MD_FLUSRQUOTA \
                                                : OBD_MD_FLGRPQUOTA)
Definition at line 69 of file osc_quota.c.
Referenced by osc_quota_setdq().
Function Documentation
static void oqi_exit (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 184 of file osc_quota.c.
References hlist_entry, OBD_SLAB_FREE_PTR, osc_quota_info::oqi_hash, and osc_quota_kmem.
static void oqi_get (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 174 of file osc_quota.c.
static unsigned oqi_hashfn (struct cfs_hash * hs, const void * key, unsigned mask) [static]
Definition at line 141 of file osc_quota.c.
References cfs_hash_u32_hash().
static void* oqi_key (struct hlist_node * hnode) [static]
Definition at line 160 of file osc_quota.c.
References hlist_entry, osc_quota_info::oqi_hash, and osc_quota_info::oqi_id.
static int oqi_keycmp (const void * key, struct hlist_node * hnode) [static]
Definition at line 147 of file osc_quota.c.
References hlist_entry, LASSERT, osc_quota_info::oqi_hash, and osc_quota_info::oqi_id.
static void* oqi_object (struct hlist_node * hnode) [static]
Definition at line 168 of file osc_quota.c.
References hlist_entry, and osc_quota_info::oqi_hash.
static void oqi_put_locked (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 179 of file osc_quota.c.
static struct osc_quota_info* osc_oqi_alloc (u32 id) [static, read]
Definition at line 34 of file osc_quota.c.
References OBD_SLAB_ALLOC_PTR, osc_quota_info::oqi_id, and osc_quota_kmem.
Referenced by osc_quota_setdq().
int osc_quota_chkdq (struct client_obd * cli, const unsigned int qid[])
Definition at line 45 of file osc_quota.c.
References CDEBUG, cfs_hash_lookup(), client_obd::cl_quota_hash, D_QUOTA, ENTRY, NO_QUOTA, QUOTA_OK, and RETURN.
int osc_quota_cleanup (struct obd_device * obd)
Definition at line 236 of file osc_quota.c.
References cfs_hash_putref(), client_obd::cl_quota_hash, obd_device::cli, ENTRY, RETURN, and obd_device::u.
Referenced by osc_cleanup().
int osc_quota_setdq (struct client_obd * cli, const unsigned int qid[], u64 valid, u32 flags)
Definition at line 74 of file osc_quota.c.
References CDEBUG, cfs_hash_add_unique(), cfs_hash_del_key(), cfs_hash_lookup(), client_obd::cl_quota_hash, cli_name(), D_QUOTA, ENTRY, FL_QUOTA_FLAG, MD_QUOTA_FLAG, OBD_MD_FLGRPQUOTA, OBD_MD_FLUSRQUOTA, OBD_SLAB_FREE_PTR, osc_quota_info::oqi_hash, osc_oqi_alloc(), osc_quota_kmem, and RETURN.
Referenced by osc_brw_fini_request().
int osc_quota_setup (struct obd_device * obd)
Definition at line 207 of file osc_quota.c.
References cfs_hash_create(), CFS_HASH_DEFAULT, CFS_HASH_MAX_THETA, CFS_HASH_MIN_THETA, cfs_hash_putref(), client_obd::cl_quota_hash, obd_device::cli, ENTRY, HASH_QUOTA_BKT_BITS, HASH_QUOTA_CUR_BITS, HASH_QUOTA_MAX_BITS, RETURN, and obd_device::u.
Referenced by osc_setup().
int osc_quotactl (struct obd_device * unused, struct obd_export * exp, struct obd_quotactl * oqctl)
Definition at line 248 of file osc_quota.c.
References CERROR, class_exp2cliimp(), ENTRY, LUSTRE_OST_VERSION, OST_QUOTACTL, ptlrpc_at_set_req_timeout(), ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc_pack(), ptlrpc_request_set_replen(), req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_OBD_QUOTACTL, ptlrpc_request::rq_no_resend, ptlrpc_request::rq_pill, ptlrpc_request::rq_repmsg, and RQF_OST_QUOTACTL.
Variable Documentation
struct cfs_hash_ops quota_hash_ops [static]
Initial value:
 {
        .hs_hash        = oqi_hashfn,
        .hs_keycmp      = oqi_keycmp,
        .hs_key         = oqi_key,
        .hs_object      = oqi_object,
        .hs_get         = oqi_get,
        .hs_put_locked  = oqi_put_locked,
        .hs_exit        = oqi_exit,
}
Definition at line 197 of file osc_quota.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.