Lustre: lustre/osc/osc_request.c File Reference
lustre/osc/osc_request.c File Reference
#include <libcfs/libcfs.h>
#include <lustre/lustre_user.h>
#include <lprocfs_status.h>
#include <lustre_debug.h>
#include <lustre_dlm.h>
#include <lustre_fid.h>
#include <lustre_ha.h>
#include <lustre_ioctl.h>
#include <lustre_net.h>
#include <lustre_obdo.h>
#include <lustre_param.h>
#include <obd.h>
#include <obd_cksum.h>
#include <obd_class.h>
#include "osc_cl_internal.h"
#include "osc_internal.h"
Data Structures
struct osc_brw_async_args
struct osc_setattr_args
struct osc_fsync_args
struct osc_ladvise_args
struct osc_enqueue_args
Defines
#define DEBUG_SUBSYSTEM S_OSC
#define osc_grant_args osc_brw_async_args
Functions
module_param (osc_reqpool_mem_max, uint, 0444)
static void osc_release_ppga (struct brw_page **ppga, size_t count)
static int brw_interpret (const struct lu_env *env, struct ptlrpc_request *req, void *data, int rc)
void osc_pack_req_body (struct ptlrpc_request *req, struct obdo *oa)
static int osc_getattr (const struct lu_env *env, struct obd_export *exp, struct obdo *oa)
static int osc_setattr (const struct lu_env *env, struct obd_export *exp, struct obdo *oa)
static int osc_setattr_interpret (const struct lu_env *env, struct ptlrpc_request *req, struct osc_setattr_args *sa, int rc)
int osc_setattr_async (struct obd_export *exp, struct obdo *oa, obd_enqueue_update_f upcall, void *cookie, struct ptlrpc_request_set *rqset)
static int osc_ladvise_interpret (const struct lu_env *env, struct ptlrpc_request *req, void *arg, int rc)
int osc_ladvise_base (struct obd_export *exp, struct obdo *oa, struct ladvise_hdr *ladvise_hdr, obd_enqueue_update_f upcall, void *cookie, struct ptlrpc_request_set *rqset)
If rqset is NULL, do not wait for response.
static int osc_create (const struct lu_env *env, struct obd_export *exp, struct obdo *oa)
int osc_punch_base (struct obd_export *exp, struct obdo *oa, obd_enqueue_update_f upcall, void *cookie, struct ptlrpc_request_set *rqset)
static int osc_sync_interpret (const struct lu_env *env, struct ptlrpc_request *req, void *arg, int rc)
int osc_sync_base (struct osc_object *obj, struct obdo *oa, obd_enqueue_update_f upcall, void *cookie, struct ptlrpc_request_set *rqset)
static int osc_resource_get_unused (struct obd_export *exp, struct obdo *oa, struct list_head *cancels, enum ldlm_mode mode, __u64 lock_flags)
static int osc_destroy_interpret (const struct lu_env *env, struct ptlrpc_request *req, void *data, int rc)
static int osc_can_send_destroy (struct client_obd *cli)
static int osc_destroy (const struct lu_env *env, struct obd_export *exp, struct obdo *oa)
static void osc_announce_cached (struct client_obd *cli, struct obdo *oa, long writing_bytes)
void osc_update_next_shrink (struct client_obd *cli)
static void __osc_update_grant (struct client_obd *cli, u64 grant)
static void osc_update_grant (struct client_obd *cli, struct ost_body *body)
static int osc_set_info_async (const struct lu_env *env, struct obd_export *exp, u32 keylen, void *key, u32 vallen, void *val, struct ptlrpc_request_set *set)
static int osc_shrink_grant_interpret (const struct lu_env *env, struct ptlrpc_request *req, void *aa, int rc)
static void osc_shrink_grant_local (struct client_obd *cli, struct obdo *oa)
static int osc_shrink_grant (struct client_obd *cli)
int osc_shrink_grant_to_target (struct client_obd *cli, __u64 target_bytes)
static int osc_should_shrink_grant (struct client_obd *client)
static int osc_grant_shrink_grant_cb (struct timeout_item *item, void *data)
static int osc_add_shrink_grant (struct client_obd *client)
static int osc_del_shrink_grant (struct client_obd *client)
static void osc_init_grant (struct client_obd *cli, struct obd_connect_data *ocd)
static void handle_short_read (int nob_read, size_t page_count, struct brw_page **pga)
static int check_write_rcs (struct ptlrpc_request *req, int requested_nob, int niocount, size_t page_count, struct brw_page **pga)
static int can_merge_pages (struct brw_page *p1, struct brw_page *p2)
static u32 osc_checksum_bulk (int nob, size_t pg_count, struct brw_page **pga, int opc, cksum_type_t cksum_type)
static int osc_brw_prep_request (int cmd, struct client_obd *cli, struct obdo *oa, u32 page_count, struct brw_page **pga, struct ptlrpc_request **reqp, int resend)
static int check_write_checksum (struct obdo *oa, const lnet_process_id_t *peer, __u32 client_cksum, __u32 server_cksum, int nob, size_t page_count, struct brw_page **pga, cksum_type_t client_cksum_type)
static int osc_brw_fini_request (struct ptlrpc_request *req, int rc)
static int osc_brw_redo_request (struct ptlrpc_request *request, struct osc_brw_async_args *aa, int rc)
static void sort_brw_pages (struct brw_page **array, int num)
static void brw_commit (struct ptlrpc_request *req)
int osc_build_rpc (const struct lu_env *env, struct client_obd *cli, struct list_head *ext_list, int cmd)
Build an RPC by the list of extent .
static int osc_set_lock_data (struct ldlm_lock *lock, void *data)
static int osc_enqueue_fini (struct ptlrpc_request *req, osc_enqueue_upcall_f upcall, void *cookie, struct lustre_handle *lockh, enum ldlm_mode mode, __u64 *flags, int agl, int errcode)
static int osc_enqueue_interpret (const struct lu_env *env, struct ptlrpc_request *req, struct osc_enqueue_args *aa, int rc)
int osc_enqueue_base (struct obd_export *exp, struct ldlm_res_id *res_id, __u64 *flags, union ldlm_policy_data *policy, struct ost_lvb *lvb, int kms_valid, osc_enqueue_upcall_f upcall, void *cookie, struct ldlm_enqueue_info *einfo, struct ptlrpc_request_set *rqset, int async, int agl)
int osc_match_base (struct obd_export *exp, struct ldlm_res_id *res_id, enum ldlm_type type, union ldlm_policy_data *policy, enum ldlm_mode mode, __u64 *flags, void *data, struct lustre_handle *lockh, int unref)
static int osc_statfs_interpret (const struct lu_env *env, struct ptlrpc_request *req, struct osc_async_args *aa, int rc)
static int osc_statfs_async (struct obd_export *exp, struct obd_info *oinfo, __u64 max_age, struct ptlrpc_request_set *rqset)
static int osc_statfs (const struct lu_env *env, struct obd_export *exp, struct obd_statfs *osfs, __u64 max_age, __u32 flags)
static int osc_iocontrol (unsigned int cmd, struct obd_export *exp, int len, void *karg, void __user *uarg)
static int osc_reconnect (const struct lu_env *env, struct obd_export *exp, struct obd_device *obd, struct obd_uuid *cluuid, struct obd_connect_data *data, void *localdata)
static int osc_disconnect (struct obd_export *exp)
static int osc_ldlm_resource_invalidate (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode, void *arg)
static int osc_import_event (struct obd_device *obd, struct obd_import *imp, enum obd_import_event event)
static int osc_cancel_weight (struct ldlm_lock *lock)
Determine whether the lock can be canceled before replaying the lock during recovery, see bug16774 for detailed information.
static int brw_queue_work (const struct lu_env *env, void *data)
int osc_setup (struct obd_device *obd, struct lustre_cfg *lcfg)
static int osc_precleanup (struct obd_device *obd)
int osc_cleanup (struct obd_device *obd)
int osc_process_config_base (struct obd_device *obd, struct lustre_cfg *lcfg)
static int osc_process_config (struct obd_device *obd, size_t len, void *buf)
DEFINE_SPINLOCK (osc_shrink_lock)
static int osc_cache_shrink (SHRINKER_ARGS(sc, nr_to_scan, gfp_mask))
static int __init osc_init (void)
static void __exit osc_exit (void)
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Object Storage Client (OSC)")
MODULE_VERSION (LUSTRE_VERSION_STRING)
MODULE_LICENSE ("GPL")
module_init (osc_init)
module_exit (osc_exit)
Variables
atomic_t osc_pool_req_count
unsigned int osc_reqpool_maxreqcount
struct ptlrpc_request_pool * osc_rq_pool
static unsigned int osc_reqpool_mem_max = 5
struct ptlrpc_request_set * PTLRPCD_SET = (void *)1
static struct obd_ops osc_obd_ops
static struct shrinker * osc_cache_shrinker
struct list_head osc_shrink_list = LIST_HEAD_INIT(osc_shrink_list)
osc shrink list to link all osc client obd
Define Documentation
#define DEBUG_SUBSYSTEM S_OSC
Definition at line 37 of file osc_request.c.
#define osc_grant_args osc_brw_async_args
Definition at line 79 of file osc_request.c.
Referenced by osc_set_info_async(), and osc_shrink_grant_interpret().
Function Documentation
static void __osc_update_grant (struct client_obd * cli, u64 grant) [static]
Definition at line 732 of file osc_request.c.
References client_obd::cl_avail_grant, and client_obd::cl_loi_list_lock.
Referenced by osc_shrink_grant_interpret(), osc_shrink_grant_to_target(), and osc_update_grant().
static void brw_commit (struct ptlrpc_request * req) [static]
Definition at line 1741 of file osc_request.c.
References likely, osc_dec_unstable_pages(), ptlrpc_request::rq_committed, ptlrpc_request::rq_lock, and ptlrpc_request::rq_unstable.
Referenced by osc_build_rpc().
static int brw_interpret (const struct lu_env * env, struct ptlrpc_request * req, void * data, int rc) [static]
Definition at line 1624 of file osc_request.c.
References osc_brw_async_args::aa_cli, osc_brw_async_args::aa_exts, osc_brw_async_args::aa_oa, osc_brw_async_args::aa_oaps, osc_brw_async_args::aa_page_count, osc_brw_async_args::aa_ppga, osc_brw_async_args::aa_resends, brw_page2oap(), CAT_ATIME, cl_attr::cat_atime, CAT_BLOCKS, cl_attr::cat_blocks, CAT_CTIME, cl_attr::cat_ctime, CAT_KMS, cl_attr::cat_kms, CAT_MTIME, cl_attr::cat_mtime, CAT_SIZE, cl_attr::cat_size, CDEBUG, CERROR, cl2osc(), client_obd::cl_loi_list_lock, cl_object_attr_lock(), cl_object_attr_unlock(), cl_object_attr_update(), client_obd::cl_r_in_flight, client_obd::cl_w_in_flight, client_should_resend(), D_HA, D_INODE, DOSTID, ENTRY, obd_import::imp_generation, obd_import::imp_obd, LASSERT, list_del_init(), list_empty(), list_for_each_entry_safe, lov_oinfo::loi_kms, lov_oinfo::loi_lvb, LPU64, lustre_msg_get_opc(), ost_lvb::lvb_size, obdo::o_atime, obdo::o_blocks, obdo::o_ctime, obdo::o_mtime, obdo::o_oi, obdo::o_valid, oap2osc_page(), osc_async_page::oap_obj, osc_async_page::oap_obj_off, osc_async_page::oap_page_off, OBD_MD_FLATIME, OBD_MD_FLBLOCKS, OBD_MD_FLCTIME, OBD_MD_FLMTIME, obd_device::obd_name, OBDO_FREE, osc_extent::oe_link, osc_object::oo_oinfo, osc2cl(), osc_brw_fini_request(), osc_brw_redo_request(), osc_env_info(), osc_extent_finish(), osc_inc_unstable_pages(), osc_io_unplug(), osc_recoverable_error(), osc_release_ppga(), osc_wake_cache_waiters(), OST_WRITE, osc_thread_info::oti_attr, POSTID, ptlrpc_lprocfs_brw(), RETURN, ptlrpc_request::rq_import, and ptlrpc_request::rq_reqmsg.
Referenced by osc_build_rpc().
static int brw_queue_work (const struct lu_env * env, void * data) [static]
Definition at line 2728 of file osc_request.c.
References CDEBUG, D_CACHE, osc_io_unplug(), and RETURN.
Referenced by osc_setup().
static int can_merge_pages (struct brw_page * p1, struct brw_page * p2) [inline, static]
Definition at line 1044 of file osc_request.c.
References brw_page::count, CWARN, brw_page::flag, OBD_BRW_ASYNC, OBD_BRW_FROM_GRANT, OBD_BRW_NOCACHE, OBD_BRW_NOQUOTA, OBD_BRW_SOFT_SYNC, OBD_BRW_SYNC, brw_page::off, and unlikely.
Referenced by osc_brw_prep_request().
static int check_write_checksum (struct obdo * oa, const lnet_process_id_t * peer, __u32 client_cksum, __u32 server_cksum, int nob, size_t page_count, struct brw_page ** pga, cksum_type_t client_cksum_type) [static]
Definition at line 1323 of file osc_request.c.
References __u64, CDEBUG, CERROR, cksum_type_unpack(), brw_page::count, D_PAGE, DFID, DOSTID, LCONSOLE_ERROR_MSG, libcfs_nid2str(), LPU64, msg, lnet_process_id_t::nid, obdo::o_flags, obdo::o_oi, obdo::o_parent_oid, obdo::o_parent_seq, obdo::o_parent_ver, obdo::o_valid, OBD_MD_FLFID, OBD_MD_FLFLAGS, brw_page::off, osc_checksum_bulk(), OST_WRITE, and POSTID.
Referenced by osc_brw_fini_request().
static int check_write_rcs (struct ptlrpc_request * req, int requested_nob, int niocount, size_t page_count, struct brw_page ** pga) [static]
Definition at line 1008 of file osc_request.c.
References CDEBUG, CERROR, D_INFO, req_capsule_server_sized_get(), RMF_RCS, and ptlrpc_request::rq_pill.
Referenced by osc_brw_fini_request().
DEFINE_SPINLOCK (osc_shrink_lock)
static void handle_short_read (int nob_read, size_t page_count, struct brw_page ** pga) [static]
Definition at line 973 of file osc_request.c.
References brw_page::count, LASSERT, and brw_page::off.
Referenced by osc_brw_fini_request().
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Object Storage Client (OSC)")
module_exit (osc_exit)
module_init (osc_init)
MODULE_LICENSE ("GPL")
module_param (osc_reqpool_mem_max , uint , 0444)
MODULE_VERSION (LUSTRE_VERSION_STRING)
static int osc_add_shrink_grant (struct client_obd * client) [static]
Definition at line 884 of file osc_request.c.
References CDEBUG, CERROR, client_obd::cl_grant_shrink_interval, client_obd::cl_grant_shrink_list, cli_name(), D_CACHE, osc_grant_shrink_grant_cb(), osc_update_next_shrink(), ptlrpc_add_timeout_client(), and TIMEOUT_GRANT.
Referenced by osc_init_grant().
static void osc_announce_cached (struct client_obd * cli, struct obdo * oa, long writing_bytes) [static]
Definition at line 663 of file osc_request.c.
References CDEBUG, CERROR, client_obd::cl_avail_grant, client_obd::cl_dirty_grant, client_obd::cl_dirty_max_pages, client_obd::cl_dirty_pages, client_obd::cl_dirty_transit, client_obd::cl_grant_extent_tax, client_obd::cl_import, client_obd::cl_loi_list_lock, client_obd::cl_lost_grant, client_obd::cl_max_extent_pages, client_obd::cl_max_pages_per_rpc, client_obd::cl_max_rpcs_in_flight, client_obd::cl_reserved_grant, cli_name(), D_CACHE, obd_import::imp_connect_data, LASSERT, LPU64, max, obdo::o_grant, obdo::o_valid, obd_dirty_pages, obd_dirty_transit_pages, obd_max_dirty_pages, OBD_MD_FLBLOCKS, OBD_MD_FLGRANT, OCD_HAS_FLAG, and unlikely.
Referenced by osc_brw_prep_request(), and osc_shrink_grant_to_target().
static int osc_brw_fini_request (struct ptlrpc_request * req, int rc) [static]
Definition at line 1369 of file osc_request.c.
References __u64, osc_brw_async_args::aa_cli, osc_brw_async_args::aa_nio_count, osc_brw_async_args::aa_oa, osc_brw_async_args::aa_page_count, osc_brw_async_args::aa_ppga, osc_brw_async_args::aa_requested_nob, ptlrpc_connection::c_peer, CDEBUG, CERROR, check_write_checksum(), check_write_rcs(), cksum_type_unpack(), brw_page::count, D_INFO, D_PAGE, D_QUOTA, DEBUG_REQ, DFID, DOSTID, ENTRY, GOTO, handle_short_read(), obd_import::imp_connect_data, obd_import::imp_connection, obd_import::imp_obd, LASSERT, LASSERTF, LCONSOLE_ERROR_MSG, libcfs_nid2str(), LPU64, LPX64, lustre_get_wire_obdo(), lustre_msg_get_opc(), obdo::o_flags, obdo::o_valid, OBD_MD_FLCKSUM, OBD_MD_FLFID, OBD_MD_FLFLAGS, OBD_MD_FLGRPQUOTA, OBD_MD_FLUSRQUOTA, obd_device::obd_name, brw_page::off, osc_checksum_bulk(), osc_quota_setdq(), osc_update_grant(), OST_READ, OST_WRITE, POSTID, req_capsule_server_get(), RETURN, RMF_OST_BODY, ptlrpc_request::rq_import, ptlrpc_request::rq_pill, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_reqmsg, sptlrpc_cli_unwrap_bulk_read(), sptlrpc_cli_unwrap_bulk_write(), and unlikely.
Referenced by brw_interpret().
static int osc_brw_prep_request (int cmd, struct client_obd * cli, struct obdo * oa, u32 page_count, struct brw_page ** pga, struct ptlrpc_request ** reqp, int resend) [static]
Definition at line 1120 of file osc_request.c.
References osc_brw_async_args::aa_cli, osc_brw_async_args::aa_nio_count, osc_brw_async_args::aa_oa, osc_brw_async_args::aa_oaps, osc_brw_async_args::aa_page_count, osc_brw_async_args::aa_ppga, osc_brw_async_args::aa_requested_nob, osc_brw_async_args::aa_resends, ptlrpc_bulk_frag_ops::add_kiov_frag, ptlrpc_bulk_desc::bd_frag_ops, ptlrpc_bulk_desc::bd_md_max_brw, can_merge_pages(), CDEBUG, cksum_type_pack(), client_obd::cl_checksum, client_obd::cl_cksum_type, client_obd::cl_import, CLASSERT, brw_page::count, D_PAGE, D_RPCTRACE, DOSTID, ENTRY, ergo, brw_page::flag, GOTO, obd_import::imp_connect_data, INIT_LIST_HEAD, obd_ioobj::ioo_bufcnt, ioobj_max_brw_set, LASSERT, LASSERTF, LNET_MTU_BITS, LPU64, LUSTRE_OST_VERSION, lustre_set_wire_obdo(), obdo::o_flags, obdo::o_oi, obdo::o_valid, ost_body::oa, OBD_BRW_SRVLOCK, OBD_BRW_WRITE, OBD_FAIL_CHECK, OBD_FAIL_OSC_BRW_PREP_REQ, OBD_FAIL_OSC_BRW_PREP_REQ2, OBD_FL_LOCAL_MASK, OBD_FL_RECOV_RESEND, OBD_MD_FLCKSUM, OBD_MD_FLFLAGS, obdo_to_ioobj(), obd_connect_data::ocd_brw_size, brw_page::off, osc_announce_cached(), osc_checksum_bulk(), osc_should_shrink_grant(), osc_shrink_grant_local(), OST_BULK_PORTAL, OST_IO_PORTAL, OST_READ, OST_WRITE, brw_page::pg, POSTID, ptlrpc_at_set_req_timeout(), PTLRPC_BULK_BUF_KIOV, PTLRPC_BULK_GET_SOURCE, ptlrpc_bulk_kiov_pin_ops, PTLRPC_BULK_PUT_SINK, ptlrpc_prep_bulk_imp(), ptlrpc_req_async_args, ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_alloc_pool(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), RCL_CLIENT, RCL_SERVER, req_capsule_client_get(), req_capsule_set_size(), RETURN, RMF_NIOBUF_REMOTE, RMF_OBD_IOOBJ, RMF_OST_BODY, RMF_RCS, niobuf_remote::rnb_flags, niobuf_remote::rnb_len, niobuf_remote::rnb_offset, ptlrpc_request::rq_flvr, ptlrpc_request::rq_import, ptlrpc_request::rq_no_retry_einprogress, ptlrpc_request::rq_pill, RQF_OST_BRW_READ, RQF_OST_BRW_WRITE, and sptlrpc_flavor_has_bulk().
Referenced by osc_brw_redo_request(), and osc_build_rpc().
static int osc_brw_redo_request (struct ptlrpc_request * request, struct osc_brw_async_args * aa, int rc) [static]
Definition at line 1518 of file osc_request.c.
References osc_brw_async_args::aa_cli, osc_brw_async_args::aa_exts, osc_brw_async_args::aa_oa, osc_brw_async_args::aa_oaps, osc_brw_async_args::aa_page_count, osc_brw_async_args::aa_ppga, osc_brw_async_args::aa_resends, cfs_time_current_sec(), D_ERROR, D_INFO, D_RPCTRACE, DEBUG_REQ, ENTRY, INIT_LIST_HEAD, LASSERTF, list_for_each_entry, list_splice_init(), lustre_msg_get_opc(), osc_async_page::oap_interrupted, osc_async_page::oap_request, osc_async_page::oap_rpc_item, OBD_BRW_READ, OBD_BRW_WRITE, osc_brw_prep_request(), OST_WRITE, ptlrpc_req_async_args, ptlrpc_req_finished(), ptlrpc_request_addref(), ptlrpcd_add_req(), RETURN, ptlrpc_request::rq_generation_set, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_sent, and ptlrpc_request::rq_timeout.
Referenced by brw_interpret().
int osc_build_rpc (const struct lu_env * env, struct client_obd * cli, struct list_head * ext_list, int cmd)
Build an RPC by the list of extent .
The caller must ensure that the total pages in this list are NOT over max pages per RPC. Extents in the list must be in OES_RPC state.
Definition at line 1764 of file osc_request.c.
References osc_brw_async_args::aa_exts, osc_brw_async_args::aa_oaps, brw_commit(), brw_interpret(), CERROR, cfs_memory_pressure_get_and_set(), cfs_memory_pressure_restore(), client_obd::cl_loi_list_lock, client_obd::cl_r_in_flight, client_obd::cl_read_offset_hist, client_obd::cl_read_page_hist, client_obd::cl_read_rpc_hist, cl_req_attr_set(), client_obd::cl_w_in_flight, client_obd::cl_write_offset_hist, client_obd::cl_write_page_hist, client_obd::cl_write_rpc_hist, CLASSERT, cl_req_attr::cra_flags, cl_req_attr::cra_jobid, cl_req_attr::cra_oa, cl_req_attr::cra_page, cl_req_attr::cra_type, CRT_READ, CRT_WRITE, D_INODE, DEBUG_REQ, ENTRY, EXIT, GOTO, INIT_LIST_HEAD, LASSERT, list_add_tail(), list_del_init(), list_empty(), list_entry, list_for_each_entry, LIST_HEAD_INIT, list_splice_init(), lprocfs_oh_tally(), lprocfs_oh_tally_log2(), lustre_msg_set_jobid(), list_head::next, ost_body::oa, oap2cl_page(), osc_async_page::oap_brw_page, osc_async_page::oap_interrupted, osc_async_page::oap_obj_off, osc_async_page::oap_page_off, osc_async_page::oap_request, osc_async_page::oap_rpc_item, OBD_ALLOC, OBD_BRW_MEMALLOC, OBD_BRW_READ, OBD_BRW_SOFT_SYNC, OBD_BRW_WRITE, OBD_FREE, OBD_MD_FLATIME, OBD_MD_FLCTIME, OBD_MD_FLMTIME, OBD_OBJECT_EOF, OBDO_ALLOC, OBDO_FREE, osc_extent::oe_grants, osc_extent::oe_link, osc_extent::oe_memalloc, osc_extent::oe_nr_pages, osc_extent::oe_obj, osc_extent::oe_pages, osc_extent::oe_state, OES_RPC, brw_page::off, osc2cl(), osc_brw_prep_request(), osc_env_info(), osc_extent_finish(), osc_over_unstable_soft_limit(), osc_thread_info::oti_req_attr, ptlrpc_mark_interrupted(), ptlrpc_req_async_args, ptlrpc_request_addref(), ptlrpcd_add_req(), req_capsule_client_get(), RETURN, RMF_OST_BODY, ptlrpc_request::rq_intr, ptlrpc_request::rq_memalloc, ptlrpc_request::rq_pill, ptlrpc_request::rq_reqmsg, and sort_brw_pages().
Referenced by osc_send_read_rpc(), and osc_send_write_rpc().
static int osc_cache_shrink (SHRINKER_ARGS(sc, nr_to_scan, gfp_mask)) [static]
Definition at line 2944 of file osc_request.c.
References shrink_control::gfp_mask, shrink_control::nr_to_scan, osc_cache_shrink_count(), osc_cache_shrink_scan(), and shrink_param.
Referenced by osc_init().
static int osc_can_send_destroy (struct client_obd * cli) [static]
Definition at line 588 of file osc_request.c.
References client_obd::cl_destroy_in_flight, client_obd::cl_destroy_waitq, and client_obd::cl_max_rpcs_in_flight.
Referenced by osc_destroy().
static int osc_cancel_weight (struct ldlm_lock * lock) [static]
Determine whether the lock can be canceled before replaying the lock during recovery, see bug16774 for detailed information.
Return values:
zero the lock can't be canceled
other ok to cancel
Definition at line 2715 of file osc_request.c.
References ldlm_lock::l_granted_mode, ldlm_lock::l_req_mode, ldlm_lock::l_resource, LDLM_EXTENT, ldlm_resource::lr_type, osc_ldlm_weigh_ast(), and RETURN.
Referenced by osc_setup().
static u32 osc_checksum_bulk (int nob, size_t pg_count, struct brw_page ** pga, int opc, cksum_type_t cksum_type) [static]
Definition at line 1064 of file osc_request.c.
References bufsize, CERROR, cfs_crypto_hash_final(), cfs_crypto_hash_init(), cfs_crypto_hash_name(), cfs_crypto_hash_update_page(), cksum, cksum_obd2cfs(), brw_page::count, D_PAGE, LASSERT, LL_CDEBUG_PAGE, min_t, OBD_FAIL_CHECK, OBD_FAIL_OSC_CHECKSUM_RECEIVE, OBD_FAIL_OSC_CHECKSUM_SEND, brw_page::off, OST_READ, and OST_WRITE.
Referenced by check_write_checksum(), osc_brw_fini_request(), and osc_brw_prep_request().
int osc_cleanup (struct obd_device * obd)
Definition at line 2874 of file osc_request.c.
References cl_client_cache::ccc_lru_lock, cl_client_cache::ccc_users, client_obd::cl_cache, cl_cache_decref(), client_obd::cl_lru_left, client_obd::cl_lru_osc, client_obd::cl_shrink_list, obd_device::cli, client_obd_cleanup(), ENTRY, LASSERT, list_del(), list_del_init(), osc_quota_cleanup(), osc_shrink_lock, ptlrpcd_decref(), RETURN, and obd_device::u.
static int osc_create (const struct lu_env * env, struct obd_export * exp, struct obdo * oa) [static]
Definition at line 366 of file osc_request.c.
References CDEBUG, class_exp2cliimp(), cli_brw_size(), D_HA, D_INFO, ENTRY, obd_export::exp_obd, fid_seq_is_echo(), GOTO, obd_import::imp_connect_data, LASSERT, LPD64, lustre_get_wire_obdo(), lustre_msg_get_transno(), LUSTRE_OST_VERSION, lustre_set_wire_obdo(), obdo::o_blksize, obdo::o_flags, obdo::o_oi, obdo::o_valid, ost_body::oa, OBD_MD_FLBLKSZ, OBD_MD_FLGROUP, OST_CREATE, ostid_seq(), ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_OST_BODY, ptlrpc_request::rq_import, ptlrpc_request::rq_pill, ptlrpc_request::rq_repmsg, and RQF_OST_CREATE.
static int osc_del_shrink_grant (struct client_obd * client) [static]
Definition at line 901 of file osc_request.c.
References client_obd::cl_grant_shrink_list, ptlrpc_del_timeout_client(), and TIMEOUT_GRANT.
Referenced by osc_disconnect().
static int osc_destroy (const struct lu_env * env, struct obd_export * exp, struct obdo * oa) [static]
Definition at line 606 of file osc_request.c.
References CDEBUG, client_obd::cl_destroy_waitq, class_exp2cliimp(), obd_device::cli, D_INFO, ENTRY, obd_export::exp_obd, obd_import::imp_connect_data, l_wait_event_exclusive, LASSERT, LCK_PW, LDLM_FL_DISCARD_DATA, ldlm_lock_list_put, ldlm_prep_elc_req(), LIST_HEAD_INIT, LUSTRE_OST_VERSION, lustre_set_wire_obdo(), LWI_INTR, LWI_ON_SIGNAL_NOOP, ost_body::oa, osc_can_send_destroy(), osc_destroy_interpret(), osc_resource_get_unused(), OST_DESTROY, OST_IO_PORTAL, ptlrpc_at_set_req_timeout(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_set_replen(), ptlrpcd_add_req(), req_capsule_client_get(), RETURN, RMF_OST_BODY, ptlrpc_request::rq_import, ptlrpc_request::rq_pill, RQF_OST_DESTROY, and obd_device::u.
static int osc_destroy_interpret (const struct lu_env * env, struct ptlrpc_request * req, void * data, int rc) [static]
Definition at line 577 of file osc_request.c.
References client_obd::cl_destroy_in_flight, client_obd::cl_destroy_waitq, obd_device::cli, obd_import::imp_obd, ptlrpc_request::rq_import, and obd_device::u.
Referenced by osc_destroy().
static int osc_disconnect (struct obd_export * exp) [static]
Initially we put del_shrink_grant before disconnect_export, but it causes the following problem if setup (connect) and cleanup (disconnect) are tangled together. connect p1 disconnect p2 ptlrpc_connect_import ............... class_manual_cleanup osc_disconnect del_shrink_grant ptlrpc_connect_interrupt init_grant_shrink add this client to shrink list cleanup_osc Bang! pinger trigger the shrink. So the osc should be disconnected from the shrink list, after we are sure the import has been destroyed. BUG18662
Definition at line 2573 of file osc_request.c.
References client_obd::cl_import, class_exp2obd(), obd_device::cli, client_disconnect_export(), osc_del_shrink_grant(), and obd_device::u.
int osc_enqueue_base (struct obd_export * exp, struct ldlm_res_id * res_id, __u64 * flags, union ldlm_policy_data * policy, struct ost_lvb * lvb, int kms_valid, osc_enqueue_upcall_f upcall, void * cookie, struct ldlm_enqueue_info * einfo, struct ptlrpc_request_set * rqset, int async, int agl)
Definition at line 2052 of file osc_request.c.
References __u64, class_exp2cliimp(), CLASSERT, ldlm_enqueue_info::ei_cbdata, ldlm_enqueue_info::ei_mode, ldlm_enqueue_info::ei_type, ELDLM_LOCK_MATCHED, ELDLM_OK, ldlm_extent::end, ENTRY, obd_export::exp_obd, ldlm_policy_data::l_extent, LCK_PR, LCK_PW, ldlm_cli_enqueue(), LDLM_FL_BLOCK_GRANTED, LDLM_FL_HAS_INTENT, LDLM_FL_LVB_READY, LDLM_FL_MATCH_LOCK, LDLM_FL_TEST_LOCK, ldlm_handle2lock(), ldlm_lock_decref(), ldlm_lock_match(), LDLM_LOCK_PUT, ldlm_prep_enqueue_req(), lustre_handle_copy(), LVB_T_OST, mode, osc_enqueue_args::oa_agl, osc_enqueue_args::oa_cookie, osc_enqueue_args::oa_exp, osc_enqueue_args::oa_flags, osc_enqueue_args::oa_lockh, osc_enqueue_args::oa_lvb, osc_enqueue_args::oa_mode, osc_enqueue_args::oa_type, osc_enqueue_args::oa_upcall, obd_device::obd_namespace, osc_enqueue_fini(), osc_enqueue_interpret(), osc_set_lock_data(), ptlrpc_req_async_args, ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_set_replen(), ptlrpc_set_add_req(), ptlrpcd_add_req(), RCL_SERVER, req_capsule_set_size(), RETURN, RMF_DLM_LVB, ptlrpc_request::rq_pill, RQF_LDLM_ENQUEUE_LVB, and ldlm_extent::start.
Referenced by osc_lock_enqueue().
static int osc_enqueue_fini (struct ptlrpc_request * req, osc_enqueue_upcall_f upcall, void * cookie, struct lustre_handle * lockh, enum ldlm_mode mode, __u64 * flags, int agl, int errcode) [static]
Definition at line 1952 of file osc_request.c.
References ELDLM_LOCK_ABORTED, ELDLM_LOCK_MATCHED, ELDLM_OK, ENTRY, LASSERT, LDLM_FL_HAS_INTENT, LDLM_FL_LVB_READY, ldlm_lock_decref(), ldlm_reply::lock_policy_res1, lustre_handle_is_used(), ptlrpc_status_ntoh(), req_capsule_server_get(), RETURN, RMF_DLM_REP, and ptlrpc_request::rq_pill.
Referenced by osc_enqueue_base(), and osc_enqueue_interpret().
static int osc_enqueue_interpret (const struct lu_env * env, struct ptlrpc_request * req, struct osc_enqueue_args * aa, int rc) [static]
Definition at line 1990 of file osc_request.c.
References __u64, lustre_handle::cookie, ENTRY, LASSERT, LASSERTF, ldlm_cli_enqueue_fini(), ldlm_handle2lock(), ldlm_lock_addref(), ldlm_lock_decref(), LDLM_LOCK_PUT, LPX64, mode, osc_enqueue_args::oa_agl, osc_enqueue_args::oa_cookie, osc_enqueue_args::oa_exp, osc_enqueue_args::oa_flags, osc_enqueue_args::oa_lockh, osc_enqueue_args::oa_lvb, osc_enqueue_args::oa_mode, osc_enqueue_args::oa_type, osc_enqueue_args::oa_upcall, OBD_FAIL_LDLM_ENQUEUE_HANG, OBD_FAIL_OSC_CP_CANCEL_RACE, OBD_FAIL_OSC_CP_ENQ_RACE, OBD_FAIL_TIMEOUT, osc_enqueue_fini(), and RETURN.
Referenced by osc_enqueue_base().
static void __exit osc_exit (void) [static]
Definition at line 3024 of file osc_request.c.
References class_unregister_type(), lu_kmem_fini(), LUSTRE_OSC_NAME, osc_cache_shrinker, osc_caches, ptlrpc_free_rq_pool(), and remove_shrinker().
static int osc_getattr (const struct lu_env * env, struct obd_export * exp, struct obdo * oa) [static]
Definition at line 126 of file osc_request.c.
References CDEBUG, class_exp2cliimp(), cli_brw_size(), D_INODE, ENTRY, EXIT, obd_export::exp_obd, GOTO, obd_import::imp_connect_data, lustre_get_wire_obdo(), LUSTRE_OST_VERSION, obdo::o_blksize, obdo::o_mode, obdo::o_valid, ost_body::oa, OBD_MD_FLBLKSZ, osc_pack_req_body(), OST_GETATTR, ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), req_capsule_server_get(), RETURN, RMF_OST_BODY, ptlrpc_request::rq_import, ptlrpc_request::rq_pill, and RQF_OST_GETATTR.
static int osc_grant_shrink_grant_cb (struct timeout_item * item, void * data) [static]
Definition at line 873 of file osc_request.c.
References client_obd::cl_grant_shrink_list, list_for_each_entry, osc_should_shrink_grant(), osc_shrink_grant(), and timeout_item::ti_obd_list.
Referenced by osc_add_shrink_grant().
static int osc_import_event (struct obd_device * obd, struct obd_import * imp, enum obd_import_event event) [static]
Definition at line 2632 of file osc_request.c.
References CERROR, cfs_hash_for_each_nolock(), client_obd::cl_avail_grant, cl_env_get(), cl_env_put(), client_obd::cl_loi_list_lock, client_obd::cl_lost_grant, obd_device::cli, ptlrpc_client::cli_request_portal, ENTRY, obd_import::imp_client, obd_import::imp_connect_data, IMP_EVENT_ACTIVATE, IMP_EVENT_ACTIVE, IMP_EVENT_DEACTIVATE, IMP_EVENT_DISCON, IMP_EVENT_INACTIVE, IMP_EVENT_INVALIDATE, IMP_EVENT_OCD, obd_import::imp_obd, LASSERT, LBUG, LDLM_FL_LOCAL_ONLY, ldlm_namespace_cleanup(), ldlm_namespace::ns_rs_hash, OBD_CONNECT_GRANT, OBD_CONNECT_REQPORTAL, obd_device::obd_namespace, OBD_NOTIFY_ACTIVATE, OBD_NOTIFY_ACTIVE, OBD_NOTIFY_DEACTIVATE, OBD_NOTIFY_INACTIVE, obd_notify_observer(), OBD_NOTIFY_OCD, obd_connect_data::ocd_connect_flags, osc_init_grant(), osc_io_unplug(), osc_ldlm_resource_invalidate(), OST_REQUEST_PORTAL, RETURN, and obd_device::u.
static int __init osc_init (void) [static]
Definition at line 2960 of file osc_request.c.
References CDEBUG, class_register_type(), class_search_type(), class_unregister_type(), D_INFO, DEF_SHRINKER_VAR, ENTRY, GOTO, lu_kmem_fini(), lu_kmem_init(), LUSTRE_OSC_NAME, LUSTRE_OSP_NAME, osc_cache_shrink(), osc_cache_shrink_count(), osc_cache_shrink_scan(), osc_cache_shrinker, osc_caches, osc_device_type, osc_pool_req_count, osc_reqpool_maxreqcount, osc_reqpool_mem_max, OST_IO_MAXREQSIZE, ptlrpc_add_rqs_to_pool(), ptlrpc_init_rq_pool(), RETURN, set_shrinker(), and obd_type::typ_procsym.
static void osc_init_grant (struct client_obd * cli, struct obd_connect_data * ocd) [static]
Definition at line 907 of file osc_request.c.
References CDEBUG, client_obd::cl_avail_grant, client_obd::cl_chunkbits, client_obd::cl_dirty_grant, client_obd::cl_dirty_pages, client_obd::cl_grant_extent_tax, client_obd::cl_grant_shrink_list, client_obd::cl_import, client_obd::cl_loi_list_lock, client_obd::cl_lost_grant, client_obd::cl_max_extent_pages, client_obd::cl_reserved_grant, cli_name(), CWARN, D_CACHE, DT_MAX_BRW_PAGES, obd_import::imp_state, list_empty(), LUSTRE_IMP_EVICTED, OBD_CONNECT_GRANT_SHRINK, obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_grant, obd_connect_data::ocd_grant_blkbits, obd_connect_data::ocd_grant_max_blks, obd_connect_data::ocd_grant_tax_kb, OCD_HAS_FLAG, osc_add_shrink_grant(), and size.
Referenced by osc_import_event().
static int osc_iocontrol (unsigned int cmd, struct obd_export * exp, int len, void * karg, void __user * uarg) [static]
Definition at line 2385 of file osc_request.c.
References CDEBUG, CERROR, client_obd::cl_import, obd_device::cli, current_comm, D_INODE, ENTRY, obd_export::exp_obd, GOTO, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_offset, IOC_OSC_SET_ACTIVE, OBD_IOC_CLIENT_RECOVER, OBD_IOC_PING_TARGET, obd_device::obd_name, ptlrpc_obd_ping(), ptlrpc_recover_import(), ptlrpc_set_import_active(), and obd_device::u.
int osc_ladvise_base (struct obd_export * exp, struct obdo * oa, struct ladvise_hdr * ladvise_hdr, obd_enqueue_update_f upcall, void * cookie, struct ptlrpc_request_set * rqset)
If rqset is NULL, do not wait for response.
Upcall and cookie could also be NULL in this case
Definition at line 303 of file osc_request.c.
References class_exp2cliimp(), CLASSERT, ENTRY, obd_import::imp_connect_data, osc_ladvise_args::la_cookie, osc_ladvise_args::la_oa, osc_ladvise_args::la_upcall, ladvise_hdr::lah_advise, ladvise_hdr::lah_count, LASSERT, LUSTRE_OST_VERSION, lustre_set_wire_obdo(), ost_body::oa, osc_ladvise_interpret(), OST_IO_PORTAL, OST_LADVISE, ptlrpc_at_set_req_timeout(), ptlrpc_req_async_args, ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), ptlrpc_set_add_req(), ptlrpcd_add_req(), PTLRPCD_SET, RCL_CLIENT, req_capsule_client_get(), req_capsule_set_size(), RETURN, RMF_OST_BODY, RMF_OST_LADVISE, RMF_OST_LADVISE_HDR, ptlrpc_request::rq_import, ptlrpc_request::rq_pill, and RQF_OST_LADVISE.
Referenced by osc_io_ladvise_start().
static int osc_ladvise_interpret (const struct lu_env * env, struct ptlrpc_request * req, void * arg, int rc) [static]
Definition at line 278 of file osc_request.c.
References ENTRY, GOTO, osc_ladvise_args::la_cookie, osc_ladvise_args::la_oa, osc_ladvise_args::la_upcall, ost_body::oa, req_capsule_server_get(), RETURN, RMF_OST_BODY, and ptlrpc_request::rq_pill.
Referenced by osc_ladvise_base().
static int osc_ldlm_resource_invalidate (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode, void * arg) [static]
Definition at line 2601 of file osc_request.c.
References cfs_hash_object(), cl_object_get(), cl_object_put(), ENTRY, ldlm_lock::l_ast_data, ldlm_clear_cleaned, list_for_each_entry, lock_res(), ldlm_resource::lr_granted, osc2cl(), osc_object_invalidate(), RETURN, and unlock_res().
Referenced by osc_import_event().
int osc_match_base (struct obd_export * exp, struct ldlm_res_id * res_id, enum ldlm_type type, union ldlm_policy_data * policy, enum ldlm_mode mode, __u64 * flags, void * data, struct lustre_handle * lockh, int unref)
Definition at line 2201 of file osc_request.c.
References __u64, ldlm_extent::end, ENTRY, obd_export::exp_obd, ldlm_policy_data::l_extent, LASSERT, LCK_PR, LCK_PW, LDLM_FL_TEST_LOCK, ldlm_handle2lock(), ldlm_lock_decref(), ldlm_lock_match(), LDLM_LOCK_PUT, OBD_FAIL_CHECK, OBD_FAIL_OSC_MATCH, obd_device::obd_namespace, osc_set_lock_data(), RETURN, and ldlm_extent::start.
void osc_pack_req_body (struct ptlrpc_request * req, struct obdo * oa)
Definition at line 116 of file osc_request.c.
References obd_import::imp_connect_data, LASSERT, lustre_set_wire_obdo(), ost_body::oa, req_capsule_client_get(), RMF_OST_BODY, ptlrpc_request::rq_import, and ptlrpc_request::rq_pill.
Referenced by osc_getattr(), osc_setattr(), and osc_setattr_async().
static int osc_precleanup (struct obd_device * obd) [static]
Definition at line 2843 of file osc_request.c.
References client_obd::cl_lru_work, client_obd::cl_writeback_work, obd_device::cli, ENTRY, lprocfs_obd_cleanup(), obd_cleanup_client_import(), obd_zombie_barrier(), ptlrpc_lprocfs_unregister_obd(), ptlrpcd_destroy_work(), RETURN, and obd_device::u.
static int osc_process_config (struct obd_device * obd, size_t len, void * buf) [static]
Definition at line 2911 of file osc_request.c.
References osc_process_config_base().
int osc_process_config_base (struct obd_device * obd, struct lustre_cfg * lcfg)
Definition at line 2905 of file osc_request.c.
References class_process_proc_param(), obd_device::obd_vars, and PARAM_OSC.
Referenced by osc_cl_process_config(), and osc_process_config().
int osc_punch_base (struct obd_export * exp, struct obdo * oa, obd_enqueue_update_f upcall, void * cookie, struct ptlrpc_request_set * rqset)
Definition at line 417 of file osc_request.c.
References class_exp2cliimp(), CLASSERT, ENTRY, obd_import::imp_connect_data, LASSERT, LUSTRE_OST_VERSION, lustre_set_wire_obdo(), ost_body::oa, osc_setattr_interpret(), OST_IO_PORTAL, OST_PUNCH, ptlrpc_at_set_req_timeout(), ptlrpc_req_async_args, ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), ptlrpc_set_add_req(), ptlrpcd_add_req(), PTLRPCD_SET, req_capsule_client_get(), RETURN, RMF_OST_BODY, ptlrpc_request::rq_import, ptlrpc_request::rq_pill, RQF_OST_PUNCH, osc_setattr_args::sa_cookie, osc_setattr_args::sa_oa, and osc_setattr_args::sa_upcall.
Referenced by osc_io_setattr_start().
static int osc_reconnect (const struct lu_env * env, struct obd_export * exp, struct obd_device * obd, struct obd_uuid * cluuid, struct obd_connect_data * data, void * localdata) [static]
Definition at line 2542 of file osc_request.c.
References CDEBUG, client_obd::cl_avail_grant, client_obd::cl_dirty_grant, client_obd::cl_dirty_pages, client_obd::cl_loi_list_lock, client_obd::cl_lost_grant, client_obd::cl_reserved_grant, obd_device::cli, cli_brw_size(), D_RPCTRACE, LPX64, OBD_CONNECT_GRANT, OBD_CONNECT_GRANT_PARAM, obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_grant, obd_connect_data::ocd_version, RETURN, and obd_device::u.
static void osc_release_ppga (struct brw_page ** ppga, size_t count) [static]
Definition at line 1618 of file osc_request.c.
References LASSERT, and OBD_FREE.
Referenced by brw_interpret().
static int osc_resource_get_unused (struct obd_export * exp, struct obdo * oa, struct list_head * cancels, enum ldlm_mode mode, __u64 lock_flags) [static]
Definition at line 545 of file osc_request.c.
References ENTRY, exp_connect_cancelset(), obd_export::exp_obd, ldlm_cancel_resource_local(), LDLM_RESOURCE_ADDREF, LDLM_RESOURCE_DELREF, ldlm_resource_get(), ldlm_resource_putref(), ns_connect_cancelset(), obdo::o_oi, obd_device::obd_namespace, ostid_build_res_name(), and RETURN.
Referenced by osc_destroy().
static int osc_set_info_async (const struct lu_env * env, struct obd_export * exp, u32 keylen, void * key, u32 vallen, void * val, struct ptlrpc_request_set * set) [static]
Definition at line 2422 of file osc_request.c.
References cl_client_cache::ccc_lru, cl_client_cache::ccc_lru_left, cl_client_cache::ccc_lru_lock, client_obd::cl_cache, cl_cache_incref(), client_obd::cl_checksum, client_obd::cl_lru_in_list, client_obd::cl_lru_left, client_obd::cl_lru_osc, class_exp2cliimp(), CLASSERT, obd_device::cli, ENTRY, obd_export::exp_obd, KEY_CACHE_LRU_SHRINK, KEY_CACHE_SET, KEY_CHECKSUM, KEY_FLUSH_CTX, KEY_GRANT_SHRINK, KEY_IS, KEY_SPTLRPC_CONF, LASSERT, list_add(), list_empty(), LUSTRE_OST_VERSION, OBD_FAIL_OSC_SHUTDOWN, OBD_FAIL_TIMEOUT, OBDO_ALLOC, osc_grant_args, osc_lru_shrink(), osc_shrink_grant_interpret(), OST_SET_INFO, ptlrpc_check_set(), ptlrpc_req_async_args, ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), ptlrpc_set_add_req(), ptlrpcd_add_req(), RCL_CLIENT, req_capsule_client_get(), req_capsule_set_size(), RETURN, RMF_OST_BODY, RMF_SETINFO_KEY, RMF_SETINFO_VAL, ptlrpc_request::rq_pill, RQF_OBD_SET_INFO, RQF_OST_SET_GRANT_INFO, sptlrpc_conf_client_adapt(), sptlrpc_import_flush_my_ctx(), and obd_device::u.
Referenced by osc_shrink_grant_to_target().
static int osc_set_lock_data (struct ldlm_lock * lock, void * data) [static]
Definition at line 1934 of file osc_request.c.
References ldlm_lock::l_ast_data, LASSERT, lock_res_and_lock(), and unlock_res_and_lock().
Referenced by osc_enqueue_base(), and osc_match_base().
static int osc_setattr (const struct lu_env * env, struct obd_export * exp, struct obdo * oa) [static]
Definition at line 169 of file osc_request.c.
References class_exp2cliimp(), ENTRY, EXIT, GOTO, obd_import::imp_connect_data, LASSERT, lustre_get_wire_obdo(), LUSTRE_OST_VERSION, obdo::o_valid, ost_body::oa, OBD_MD_FLGROUP, osc_pack_req_body(), OST_SETATTR, ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), req_capsule_server_get(), RETURN, RMF_OST_BODY, ptlrpc_request::rq_import, ptlrpc_request::rq_pill, and RQF_OST_SETATTR.
int osc_setattr_async (struct obd_export * exp, struct obdo * oa, obd_enqueue_update_f upcall, void * cookie, struct ptlrpc_request_set * rqset)
Definition at line 231 of file osc_request.c.
References class_exp2cliimp(), CLASSERT, ENTRY, LUSTRE_OST_VERSION, osc_pack_req_body(), osc_setattr_interpret(), OST_SETATTR, ptlrpc_req_async_args, ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), ptlrpc_set_add_req(), ptlrpcd_add_req(), PTLRPCD_SET, RETURN, RQF_OST_SETATTR, osc_setattr_args::sa_cookie, osc_setattr_args::sa_oa, and osc_setattr_args::sa_upcall.
Referenced by osc_io_setattr_start().
static int osc_setattr_interpret (const struct lu_env * env, struct ptlrpc_request * req, struct osc_setattr_args * sa, int rc) [static]
Definition at line 210 of file osc_request.c.
References ENTRY, GOTO, obd_import::imp_connect_data, lustre_get_wire_obdo(), ost_body::oa, req_capsule_server_get(), RETURN, RMF_OST_BODY, ptlrpc_request::rq_import, ptlrpc_request::rq_pill, osc_setattr_args::sa_cookie, osc_setattr_args::sa_oa, and osc_setattr_args::sa_upcall.
Referenced by osc_punch_base(), and osc_setattr_async().
int osc_setup (struct obd_device * obd, struct lustre_cfg * lcfg)
Definition at line 2738 of file osc_request.c.
References brw_queue_work(), CERROR, client_obd::cl_grant_shrink_interval, client_obd::cl_grant_shrink_list, client_obd::cl_import, client_obd::cl_lru_work, client_obd::cl_max_rpcs_in_flight, client_obd::cl_shrink_list, client_obd::cl_writeback_work, class_search_type(), obd_device::cli, client_obd_cleanup(), client_obd_setup(), ENTRY, GOTO, GRANT_SHRINK_INTERVAL, handler(), INIT_LIST_HEAD, list_add_tail(), lproc_osc_attach_seqstat(), lprocfs_obd_setup(), lprocfs_register(), lru_queue_work(), LUSTRE_OSP_NAME, ns_register_cancel(), obd_device::obd_name, obd_device::obd_namespace, obd_device::obd_proc_entry, obd_device::obd_vars, osc_cancel_weight(), osc_pool_req_count, osc_quota_setup(), osc_reqpool_maxreqcount, osc_shrink_list, osc_shrink_lock, ptlrpc_add_rqs_to_pool(), ptlrpc_lprocfs_register_obd(), ptlrpcd_addref(), ptlrpcd_alloc_work(), ptlrpcd_decref(), ptlrpcd_destroy_work(), RETURN, sptlrpc_lprocfs_cliobd_attach(), obd_type::typ_procsym, and obd_device::u.
Referenced by osc_device_alloc().
static int osc_should_shrink_grant (struct client_obd * client) [static]
Definition at line 849 of file osc_request.c.
References CFS_TICK, cfs_time_aftereq(), cfs_time_current(), client_obd::cl_avail_grant, client_obd::cl_import, client_obd::cl_max_pages_per_rpc, client_obd::cl_next_shrink_grant, obd_import::imp_connect_data, obd_import::imp_state, LUSTRE_IMP_FULL, OBD_CONNECT_GRANT_SHRINK, obd_connect_data::ocd_connect_flags, and osc_update_next_shrink().
Referenced by osc_brw_prep_request(), and osc_grant_shrink_grant_cb().
static int osc_shrink_grant (struct client_obd * cli) [static]
Definition at line 791 of file osc_request.c.
References __u64, client_obd::cl_avail_grant, client_obd::cl_loi_list_lock, client_obd::cl_max_pages_per_rpc, client_obd::cl_max_rpcs_in_flight, and osc_shrink_grant_to_target().
Referenced by osc_grant_shrink_grant_cb().
static int osc_shrink_grant_interpret (const struct lu_env * env, struct ptlrpc_request * req, void * aa, int rc) [static]
Definition at line 752 of file osc_request.c.
References __osc_update_grant(), obd_device::cli, GOTO, obd_import::imp_obd, LASSERT, obdo::o_grant, OBDO_FREE, osc_grant_args, osc_update_grant(), req_capsule_server_get(), RMF_OST_BODY, ptlrpc_request::rq_import, ptlrpc_request::rq_pill, and obd_device::u.
Referenced by osc_set_info_async().
static void osc_shrink_grant_local (struct client_obd * cli, struct obdo * oa) [static]
Definition at line 773 of file osc_request.c.
References client_obd::cl_avail_grant, client_obd::cl_loi_list_lock, obdo::o_flags, obdo::o_grant, obdo::o_valid, OBD_FL_SHRINK_GRANT, OBD_MD_FLFLAGS, and osc_update_next_shrink().
Referenced by osc_brw_prep_request().
int osc_shrink_grant_to_target (struct client_obd * cli, __u64 target_bytes)
Definition at line 804 of file osc_request.c.
References __osc_update_grant(), client_obd::cl_avail_grant, client_obd::cl_import, client_obd::cl_loi_list_lock, client_obd::cl_max_pages_per_rpc, ENTRY, obd_import::imp_obd, KEY_GRANT_SHRINK, obdo::o_flags, obdo::o_grant, obdo::o_valid, ost_body::oa, OBD_ALLOC_PTR, OBD_FL_SHRINK_GRANT, OBD_FREE_PTR, OBD_MD_FLFLAGS, obd_device::obd_self_export, osc_announce_cached(), osc_set_info_async(), osc_update_next_shrink(), and RETURN.
Referenced by osc_shrink_grant().
static int osc_statfs (const struct lu_env * env, struct obd_export * exp, struct obd_statfs * osfs, __u64 max_age, __u32 flags) [static]
Definition at line 2321 of file osc_request.c.
References client_obd::cl_import, client_obd::cl_sem, class_exp2obd(), class_import_get(), class_import_put(), obd_device::cli, ENTRY, EXIT, GOTO, LUSTRE_OST_VERSION, OBD_STATFS_NODELAY, OST_CREATE_PORTAL, OST_STATFS, ptlrpc_at_set_req_timeout(), ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), req_capsule_server_get(), RETURN, RMF_OBD_STATFS, ptlrpc_request::rq_no_delay, ptlrpc_request::rq_no_resend, ptlrpc_request::rq_pill, RQF_OST_STATFS, and obd_device::u.
static int osc_statfs_async (struct obd_export * exp, struct obd_info * oinfo, __u64 max_age, struct ptlrpc_request_set * rqset) [static]
Definition at line 2277 of file osc_request.c.
References osc_async_args::aa_oi, client_obd::cl_import, class_exp2obd(), CLASSERT, obd_device::cli, ENTRY, LUSTRE_OST_VERSION, OBD_STATFS_NODELAY, obd_info::oi_flags, osc_statfs_interpret(), OST_CREATE_PORTAL, OST_STATFS, ptlrpc_at_set_req_timeout(), ptlrpc_req_async_args, ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), ptlrpc_set_add_req(), RETURN, ptlrpc_request::rq_no_delay, ptlrpc_request::rq_no_resend, RQF_OST_STATFS, and obd_device::u.
static int osc_statfs_interpret (const struct lu_env * env, struct ptlrpc_request * req, struct osc_async_args * aa, int rc) [static]
Definition at line 2244 of file osc_request.c.
References osc_async_args::aa_oi, ENTRY, GOTO, OBD_STATFS_NODELAY, obd_info::oi_cb_up, obd_info::oi_flags, obd_info::oi_osfs, req_capsule_server_get(), RETURN, RMF_OBD_STATFS, and ptlrpc_request::rq_pill.
Referenced by osc_statfs_async().
int osc_sync_base (struct osc_object * obj, struct obdo * oa, obd_enqueue_update_f upcall, void * cookie, struct ptlrpc_request_set * rqset)
Definition at line 498 of file osc_request.c.
References class_exp2cliimp(), CLASSERT, ENTRY, osc_fsync_args::fa_cookie, osc_fsync_args::fa_oa, osc_fsync_args::fa_obj, osc_fsync_args::fa_upcall, obd_import::imp_connect_data, LASSERT, LUSTRE_OST_VERSION, lustre_set_wire_obdo(), ost_body::oa, osc_export(), osc_sync_interpret(), OST_SYNC, ptlrpc_req_async_args, ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), ptlrpc_set_add_req(), ptlrpcd_add_req(), PTLRPCD_SET, req_capsule_client_get(), RETURN, RMF_OST_BODY, ptlrpc_request::rq_import, ptlrpc_request::rq_pill, and RQF_OST_SYNC.
Referenced by osc_fsync_ost().
static int osc_sync_interpret (const struct lu_env * env, struct ptlrpc_request * req, void * arg, int rc) [static]
Definition at line 459 of file osc_request.c.
References CAT_BLOCKS, cl_attr::cat_blocks, CERROR, cl_object_attr_lock(), cl_object_attr_unlock(), cl_object_attr_update(), ENTRY, osc_fsync_args::fa_cookie, osc_fsync_args::fa_oa, osc_fsync_args::fa_obj, osc_fsync_args::fa_upcall, GOTO, obdo::o_blocks, obdo::o_valid, ost_body::oa, OBD_MD_FLBLOCKS, osc2cl(), osc_env_info(), osc_thread_info::oti_attr, req_capsule_server_get(), RETURN, RMF_OST_BODY, and ptlrpc_request::rq_pill.
Referenced by osc_sync_base().
static void osc_update_grant (struct client_obd * cli, struct ost_body * body) [static]
Definition at line 739 of file osc_request.c.
References __osc_update_grant(), CDEBUG, D_CACHE, LPU64, obdo::o_grant, obdo::o_valid, ost_body::oa, and OBD_MD_FLGRANT.
Referenced by osc_brw_fini_request(), and osc_shrink_grant_interpret().
void osc_update_next_shrink (struct client_obd * cli)
Definition at line 724 of file osc_request.c.
References CDEBUG, cfs_time_shift(), client_obd::cl_grant_shrink_interval, client_obd::cl_next_shrink_grant, and D_CACHE.
Referenced by osc_add_shrink_grant(), osc_consume_write_grant(), osc_should_shrink_grant(), osc_shrink_grant_local(), and osc_shrink_grant_to_target().
static void sort_brw_pages (struct brw_page ** array, int num) [static]
Definition at line 1594 of file osc_request.c.
References brw_page::off.
Referenced by osc_build_rpc().
Variable Documentation
struct shrinker* osc_cache_shrinker [static]
Definition at line 2939 of file osc_request.c.
Referenced by osc_exit(), and osc_init().
struct obd_ops osc_obd_ops [static]
Initial value:
 {
        .o_owner                = THIS_MODULE,
        .o_setup                = osc_setup,
        .o_precleanup           = osc_precleanup,
        .o_cleanup              = osc_cleanup,
        .o_add_conn             = client_import_add_conn,
        .o_del_conn             = client_import_del_conn,
        .o_connect              = client_connect_import,
        .o_reconnect            = osc_reconnect,
        .o_disconnect           = osc_disconnect,
        .o_statfs               = osc_statfs,
        .o_statfs_async         = osc_statfs_async,
        .o_create               = osc_create,
        .o_destroy              = osc_destroy,
        .o_getattr              = osc_getattr,
        .o_setattr              = osc_setattr,
        .o_iocontrol            = osc_iocontrol,
        .o_set_info_async       = osc_set_info_async,
        .o_import_event         = osc_import_event,
        .o_process_config       = osc_process_config,
        .o_quotactl             = osc_quotactl,
}
Definition at line 2916 of file osc_request.c.
atomic_t osc_pool_req_count
Definition at line 59 of file osc_request.c.
Referenced by osc_init(), and osc_setup().
unsigned int osc_reqpool_maxreqcount
Definition at line 60 of file osc_request.c.
Referenced by osc_init(), and osc_setup().
unsigned int osc_reqpool_mem_max = 5 [static]
Definition at line 64 of file osc_request.c.
Referenced by osc_init().
struct ptlrpc_request_pool* osc_rq_pool
Definition at line 61 of file osc_request.c.
struct list_head osc_shrink_list = LIST_HEAD_INIT(osc_shrink_list)
osc shrink list to link all osc client obd
Definition at line 2940 of file osc_request.c.
Referenced by osc_cache_shrink_count(), osc_cache_shrink_scan(), and osc_setup().
struct ptlrpc_request_set* PTLRPCD_SET = (void *)1
Definition at line 2043 of file osc_request.c.
Referenced by osc_fsync_ost(), osc_io_ladvise_start(), osc_io_setattr_start(), osc_ladvise_base(), osc_lock_enqueue(), osc_punch_base(), osc_setattr_async(), and osc_sync_base().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.