Lustre: lustre/osc/osc_internal.h File Reference
lustre/osc/osc_internal.h File Reference
#include <cl_object.h>
Data Structures
struct osc_async_page
struct osc_cache_waiter
struct osc_device
struct osc_device::osc_stats
struct osc_quota_info
struct osc_async_args
Defines
#define OAP_MAGIC 8675309
#define oap_page oap_brw_page.pg
#define oap_count oap_brw_page.count
#define oap_brw_flags oap_brw_page.flag
#define min_t(type, x, y) ({ type __x = (x); type __y = (y); __x < __y ? __x: __y; })
Typedefs
typedef int(* osc_enqueue_upcall_f)(void *cookie, struct lustre_handle *lockh, int rc)
Enumerations
enum async_flags { ASYNC_READY = 0x1, ASYNC_URGENT = 0x2, ASYNC_COUNT_STABLE = 0x4, ASYNC_HP = 0x10 }
enum osc_dap_flags { OSC_DAP_FL_TEST_LOCK = 1 << 0, OSC_DAP_FL_CANCELING = 1 << 1 }
Bit flags for osc_dlm_lock_at_pageoff().
Functions
static struct osc_async_page * brw_page2oap (struct brw_page *pga)
void osc_wake_cache_waiters (struct client_obd *cli)
int osc_shrink_grant_to_target (struct client_obd *cli, __u64 target_bytes)
void osc_update_next_shrink (struct client_obd *cli)
int osc_enqueue_base (struct obd_export *exp, struct ldlm_res_id *res_id, __u64 *flags, union ldlm_policy_data *policy, struct ost_lvb *lvb, int kms_valid, osc_enqueue_upcall_f upcall, void *cookie, struct ldlm_enqueue_info *einfo, struct ptlrpc_request_set *rqset, int async, int agl)
int osc_match_base (struct obd_export *exp, struct ldlm_res_id *res_id, __u32 type, union ldlm_policy_data *policy, __u32 mode, __u64 *flags, void *data, struct lustre_handle *lockh, int unref)
int osc_setattr_async (struct obd_export *exp, struct obdo *oa, obd_enqueue_update_f upcall, void *cookie, struct ptlrpc_request_set *rqset)
int osc_punch_base (struct obd_export *exp, struct obdo *oa, obd_enqueue_update_f upcall, void *cookie, struct ptlrpc_request_set *rqset)
int osc_sync_base (struct osc_object *obj, struct obdo *oa, obd_enqueue_update_f upcall, void *cookie, struct ptlrpc_request_set *rqset)
int osc_ladvise_base (struct obd_export *exp, struct obdo *oa, struct ladvise_hdr *ladvise_hdr, obd_enqueue_update_f upcall, void *cookie, struct ptlrpc_request_set *rqset)
If rqset is NULL, do not wait for response.
int osc_process_config_base (struct obd_device *obd, struct lustre_cfg *cfg)
int osc_build_rpc (const struct lu_env *env, struct client_obd *cli, struct list_head *ext_list, int cmd)
Build an RPC by the list of extent .
long osc_lru_shrink (const struct lu_env *env, struct client_obd *cli, long target, bool force)
Drop of pages from LRU at most.
unsigned long osc_lru_reserve (struct client_obd *cli, unsigned long npages)
osc_lru_reserve() is called to reserve enough LRU slots for I/O.
void osc_lru_unreserve (struct client_obd *cli, unsigned long npages)
osc_lru_unreserve() is called to unreserve LRU slots.
unsigned long osc_ldlm_weigh_ast (struct ldlm_lock *dlmlock)
Get the weight of dlm lock for early cancellation.
int osc_cleanup (struct obd_device *obd)
int osc_setup (struct obd_device *obd, struct lustre_cfg *lcfg)
static int lproc_osc_attach_seqstat (struct obd_device *dev)
static int osc_recoverable_error (int rc)
static unsigned long rpcs_in_flight (struct client_obd *cli)
static char * cli_name (struct client_obd *cli)
static struct osc_device * obd2osc_dev (const struct obd_device *d)
int osc_quota_setup (struct obd_device *obd)
int osc_quota_cleanup (struct obd_device *obd)
int osc_quota_setdq (struct client_obd *cli, const unsigned int qid[], u64 valid, u32 flags)
int osc_quota_chkdq (struct client_obd *cli, const unsigned int qid[])
int osc_quotactl (struct obd_device *unused, struct obd_export *exp, struct obd_quotactl *oqctl)
void osc_inc_unstable_pages (struct ptlrpc_request *req)
"unstable" page accounting.
void osc_dec_unstable_pages (struct ptlrpc_request *req)
Performs "unstable" page accounting.
bool osc_over_unstable_soft_limit (struct client_obd *cli)
Check if it piggybacks SOFT_SYNC flag to OST from this OSC.
struct ldlm_lock * osc_dlmlock_at_pgoff (const struct lu_env *env, struct osc_object *obj, pgoff_t index, enum osc_dap_flags flags)
Finds an existing lock covering given index and optionally different from a given except lock.
void osc_pack_req_body (struct ptlrpc_request *req, struct obdo *oa)
int osc_object_invalidate (const struct lu_env *env, struct osc_object *osc)
unsigned long osc_cache_shrink_count (struct shrinker *sk, struct shrink_control *sc)
Return how many LRU pages in the cache of all OSC devices.
unsigned long osc_cache_shrink_scan (struct shrinker *sk, struct shrink_control *sc)
Scan and try to reclaim sc->nr_to_scan cached LRU pages.
Variables
atomic_t osc_pool_req_count
unsigned int osc_reqpool_maxreqcount
struct ptlrpc_request_pool * osc_rq_pool
struct ptlrpc_request_set * PTLRPCD_SET
struct lu_kmem_descr osc_caches []
struct lu_device_type osc_device_type
struct kmem_cache * osc_quota_kmem
struct list_head osc_shrink_list
osc shrink list to link all osc client obd
spinlock_t osc_shrink_lock
spin lock to protect osc_shrink_list
Define Documentation
#define min_t (type, x, y) ({ type __x = (x); type __y = (y); __x < __y ? __x: __y; })
Definition at line 177 of file osc_internal.h.
Referenced by __proc_lnet_buffers(), __proc_lnet_portal_rotor(), __proc_lnet_stats(), cfs_get_environ(), cl_object_maxbytes(), client_obd_setup(), dt_index_walk(), enc_pools_shrink_scan(), ldlm_req_handles_avail(), ldlm_setup(), ll_file_maxbytes(), ll_ra_count_get(), ll_readlink_internal(), lod_qos_dev_is_full(), lov_get_info(), lov_io_read_ahead(), lov_io_rw_iter_init(), lov_iocontrol(), lprocfs_mds_evict_client_seq_write(), lsm_unpackmd_common(), lstcon_testrpc_prep(), mdc_update_max_ea_from_body(), mdd_readpage(), mdd_statfs(), mdt_getattr_internal(), mdt_readpage(), mgc_process_recover_log(), mgs_get_ir_logs(), ofd_grant_commit(), ofd_statfs(), ofd_statfs_internal(), osc_checksum_bulk(), osc_extent_find(), osd_bufs_get_read(), osd_bufs_get_write(), osd_statfs(), osp_it_fetch(), osp_pre_update_status(), ptlrpc_disconnect_import(), ptlrpc_fill_bulk_md(), qmt_alloc_expand(), qsd_reint_index(), qsd_wait_timeout(), tgt_obd_idx_read(), and tgt_sendpage().
#define oap_brw_flags oap_brw_page.flag
Definition at line 81 of file osc_internal.h.
#define oap_count oap_brw_page.count
Definition at line 80 of file osc_internal.h.
#define OAP_MAGIC 8675309
Definition at line 40 of file osc_internal.h.
Referenced by osc_page_submit().
#define oap_page oap_brw_page.pg
Definition at line 79 of file osc_internal.h.
Typedef Documentation
typedef int(* osc_enqueue_upcall_f)(void *cookie, struct lustre_handle *lockh, int rc)
Definition at line 108 of file osc_internal.h.
Enumeration Type Documentation
enum async_flags
Enumerator:
ASYNC_READY
ASYNC_URGENT
ASYNC_COUNT_STABLE
ASYNC_HP
Definition at line 48 of file osc_internal.h.
enum osc_dap_flags
Bit flags for osc_dlm_lock_at_pageoff().
Enumerator:
OSC_DAP_FL_TEST_LOCK
Just check if the desired lock exists, it won't hold reference count on lock.
OSC_DAP_FL_CANCELING
Return the lock even if it is being canceled.
Definition at line 226 of file osc_internal.h.
Function Documentation
static struct osc_async_page* brw_page2oap (struct brw_page * pga) [static, read]
Definition at line 83 of file osc_internal.h.
References osc_async_page::oap_brw_page.
Referenced by brw_interpret().
static char* cli_name (struct client_obd * cli) [inline, static]
Definition at line 171 of file osc_internal.h.
References client_obd::cl_import, obd_import::imp_obd, and obd_device::obd_name.
Referenced by client_obd_setup(), lru_queue_work(), osc_add_shrink_grant(), osc_announce_cached(), osc_enter_cache(), osc_extent_wait(), osc_init_grant(), osc_lru_del(), osc_lru_reclaim(), osc_lru_reserve(), osc_lru_shrink(), osc_over_unstable_soft_limit(), and osc_quota_setdq().
static int lproc_osc_attach_seqstat (struct obd_device * dev) [inline, static]
Definition at line 155 of file osc_internal.h.
Referenced by osc_setup().
static struct osc_device* obd2osc_dev (const struct obd_device * d) [static, read]
Definition at line 197 of file osc_internal.h.
References cl_device::cd_lu_dev, obd_device::obd_lu_dev, and osc_device::od_cl.
int osc_build_rpc (const struct lu_env * env, struct client_obd * cli, struct list_head * ext_list, int cmd)
Build an RPC by the list of extent .
The caller must ensure that the total pages in this list are NOT over max pages per RPC. Extents in the list must be in OES_RPC state.
Definition at line 1764 of file osc_request.c.
References osc_brw_async_args::aa_exts, osc_brw_async_args::aa_oaps, brw_commit(), brw_interpret(), CERROR, cfs_memory_pressure_get_and_set(), cfs_memory_pressure_restore(), client_obd::cl_loi_list_lock, client_obd::cl_r_in_flight, client_obd::cl_read_offset_hist, client_obd::cl_read_page_hist, client_obd::cl_read_rpc_hist, cl_req_attr_set(), client_obd::cl_w_in_flight, client_obd::cl_write_offset_hist, client_obd::cl_write_page_hist, client_obd::cl_write_rpc_hist, CLASSERT, cl_req_attr::cra_flags, cl_req_attr::cra_jobid, cl_req_attr::cra_oa, cl_req_attr::cra_page, cl_req_attr::cra_type, CRT_READ, CRT_WRITE, D_INODE, DEBUG_REQ, ENTRY, EXIT, GOTO, INIT_LIST_HEAD, LASSERT, list_add_tail(), list_del_init(), list_empty(), list_entry, list_for_each_entry, LIST_HEAD_INIT, list_splice_init(), lprocfs_oh_tally(), lprocfs_oh_tally_log2(), lustre_msg_set_jobid(), list_head::next, ost_body::oa, oap2cl_page(), osc_async_page::oap_brw_page, osc_async_page::oap_interrupted, osc_async_page::oap_obj_off, osc_async_page::oap_page_off, osc_async_page::oap_request, osc_async_page::oap_rpc_item, OBD_ALLOC, OBD_BRW_MEMALLOC, OBD_BRW_READ, OBD_BRW_SOFT_SYNC, OBD_BRW_WRITE, OBD_FREE, OBD_MD_FLATIME, OBD_MD_FLCTIME, OBD_MD_FLMTIME, OBD_OBJECT_EOF, OBDO_ALLOC, OBDO_FREE, osc_extent::oe_grants, osc_extent::oe_link, osc_extent::oe_memalloc, osc_extent::oe_nr_pages, osc_extent::oe_obj, osc_extent::oe_pages, osc_extent::oe_state, OES_RPC, brw_page::off, osc2cl(), osc_brw_prep_request(), osc_env_info(), osc_extent_finish(), osc_over_unstable_soft_limit(), osc_thread_info::oti_req_attr, ptlrpc_mark_interrupted(), ptlrpc_req_async_args, ptlrpc_request_addref(), ptlrpcd_add_req(), req_capsule_client_get(), RETURN, RMF_OST_BODY, ptlrpc_request::rq_intr, ptlrpc_request::rq_memalloc, ptlrpc_request::rq_pill, ptlrpc_request::rq_reqmsg, and sort_brw_pages().
Referenced by osc_send_read_rpc(), and osc_send_write_rpc().
int osc_cleanup (struct obd_device * obd)
Definition at line 2874 of file osc_request.c.
References cl_client_cache::ccc_lru_lock, cl_client_cache::ccc_users, client_obd::cl_cache, cl_cache_decref(), client_obd::cl_lru_left, client_obd::cl_lru_osc, client_obd::cl_shrink_list, obd_device::cli, client_obd_cleanup(), ENTRY, LASSERT, list_del(), list_del_init(), osc_quota_cleanup(), osc_shrink_lock, ptlrpcd_decref(), RETURN, and obd_device::u.
int osc_enqueue_base (struct obd_export * exp, struct ldlm_res_id * res_id, __u64 * flags, union ldlm_policy_data * policy, struct ost_lvb * lvb, int kms_valid, osc_enqueue_upcall_f upcall, void * cookie, struct ldlm_enqueue_info * einfo, struct ptlrpc_request_set * rqset, int async, int agl)
Definition at line 2052 of file osc_request.c.
References __u64, class_exp2cliimp(), CLASSERT, ldlm_enqueue_info::ei_cbdata, ldlm_enqueue_info::ei_mode, ldlm_enqueue_info::ei_type, ELDLM_LOCK_MATCHED, ELDLM_OK, ldlm_extent::end, ENTRY, obd_export::exp_obd, ldlm_policy_data::l_extent, LCK_PR, LCK_PW, ldlm_cli_enqueue(), LDLM_FL_BLOCK_GRANTED, LDLM_FL_HAS_INTENT, LDLM_FL_LVB_READY, LDLM_FL_MATCH_LOCK, LDLM_FL_TEST_LOCK, ldlm_handle2lock(), ldlm_lock_decref(), ldlm_lock_match(), LDLM_LOCK_PUT, ldlm_prep_enqueue_req(), lustre_handle_copy(), LVB_T_OST, mode, osc_enqueue_args::oa_agl, osc_enqueue_args::oa_cookie, osc_enqueue_args::oa_exp, osc_enqueue_args::oa_flags, osc_enqueue_args::oa_lockh, osc_enqueue_args::oa_lvb, osc_enqueue_args::oa_mode, osc_enqueue_args::oa_type, osc_enqueue_args::oa_upcall, obd_device::obd_namespace, osc_enqueue_fini(), osc_enqueue_interpret(), osc_set_lock_data(), ptlrpc_req_async_args, ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_set_replen(), ptlrpc_set_add_req(), ptlrpcd_add_req(), RCL_SERVER, req_capsule_set_size(), RETURN, RMF_DLM_LVB, ptlrpc_request::rq_pill, RQF_LDLM_ENQUEUE_LVB, and ldlm_extent::start.
Referenced by osc_lock_enqueue().
int osc_ladvise_base (struct obd_export * exp, struct obdo * oa, struct ladvise_hdr * ladvise_hdr, obd_enqueue_update_f upcall, void * cookie, struct ptlrpc_request_set * rqset)
If rqset is NULL, do not wait for response.
Upcall and cookie could also be NULL in this case
Definition at line 303 of file osc_request.c.
References class_exp2cliimp(), CLASSERT, ENTRY, obd_import::imp_connect_data, osc_ladvise_args::la_cookie, osc_ladvise_args::la_oa, osc_ladvise_args::la_upcall, ladvise_hdr::lah_advise, ladvise_hdr::lah_count, LASSERT, LUSTRE_OST_VERSION, lustre_set_wire_obdo(), ost_body::oa, osc_ladvise_interpret(), OST_IO_PORTAL, OST_LADVISE, ptlrpc_at_set_req_timeout(), ptlrpc_req_async_args, ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), ptlrpc_set_add_req(), ptlrpcd_add_req(), PTLRPCD_SET, RCL_CLIENT, req_capsule_client_get(), req_capsule_set_size(), RETURN, RMF_OST_BODY, RMF_OST_LADVISE, RMF_OST_LADVISE_HDR, ptlrpc_request::rq_import, ptlrpc_request::rq_pill, and RQF_OST_LADVISE.
Referenced by osc_io_ladvise_start().
int osc_match_base (struct obd_export * exp, struct ldlm_res_id * res_id, __u32 type, union ldlm_policy_data * policy, __u32 mode, __u64 * flags, void * data, struct lustre_handle * lockh, int unref)
Referenced by osc_dlmlock_at_pgoff().
void osc_pack_req_body (struct ptlrpc_request * req, struct obdo * oa)
Definition at line 116 of file osc_request.c.
References obd_import::imp_connect_data, LASSERT, lustre_set_wire_obdo(), ost_body::oa, req_capsule_client_get(), RMF_OST_BODY, ptlrpc_request::rq_import, and ptlrpc_request::rq_pill.
Referenced by osc_getattr(), osc_setattr(), and osc_setattr_async().
int osc_process_config_base (struct obd_device * obd, struct lustre_cfg * cfg)
Definition at line 2905 of file osc_request.c.
References class_process_proc_param(), obd_device::obd_vars, and PARAM_OSC.
Referenced by osc_cl_process_config(), and osc_process_config().
int osc_punch_base (struct obd_export * exp, struct obdo * oa, obd_enqueue_update_f upcall, void * cookie, struct ptlrpc_request_set * rqset)
Definition at line 417 of file osc_request.c.
References class_exp2cliimp(), CLASSERT, ENTRY, obd_import::imp_connect_data, LASSERT, LUSTRE_OST_VERSION, lustre_set_wire_obdo(), ost_body::oa, osc_setattr_interpret(), OST_IO_PORTAL, OST_PUNCH, ptlrpc_at_set_req_timeout(), ptlrpc_req_async_args, ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), ptlrpc_set_add_req(), ptlrpcd_add_req(), PTLRPCD_SET, req_capsule_client_get(), RETURN, RMF_OST_BODY, ptlrpc_request::rq_import, ptlrpc_request::rq_pill, RQF_OST_PUNCH, osc_setattr_args::sa_cookie, osc_setattr_args::sa_oa, and osc_setattr_args::sa_upcall.
Referenced by osc_io_setattr_start().
int osc_quota_chkdq (struct client_obd * cli, const unsigned int qid[])
Definition at line 45 of file osc_quota.c.
References CDEBUG, cfs_hash_lookup(), client_obd::cl_quota_hash, D_QUOTA, ENTRY, NO_QUOTA, QUOTA_OK, and RETURN.
int osc_quota_cleanup (struct obd_device * obd)
Definition at line 236 of file osc_quota.c.
References cfs_hash_putref(), client_obd::cl_quota_hash, obd_device::cli, ENTRY, RETURN, and obd_device::u.
Referenced by osc_cleanup().
int osc_quota_setdq (struct client_obd * cli, const unsigned int qid[], u64 valid, u32 flags)
Definition at line 74 of file osc_quota.c.
References CDEBUG, cfs_hash_add_unique(), cfs_hash_del_key(), cfs_hash_lookup(), client_obd::cl_quota_hash, cli_name(), D_QUOTA, ENTRY, FL_QUOTA_FLAG, MD_QUOTA_FLAG, OBD_MD_FLGRPQUOTA, OBD_MD_FLUSRQUOTA, OBD_SLAB_FREE_PTR, osc_quota_info::oqi_hash, osc_oqi_alloc(), osc_quota_kmem, and RETURN.
Referenced by osc_brw_fini_request().
int osc_quota_setup (struct obd_device * obd)
Definition at line 207 of file osc_quota.c.
References cfs_hash_create(), CFS_HASH_DEFAULT, CFS_HASH_MAX_THETA, CFS_HASH_MIN_THETA, cfs_hash_putref(), client_obd::cl_quota_hash, obd_device::cli, ENTRY, HASH_QUOTA_BKT_BITS, HASH_QUOTA_CUR_BITS, HASH_QUOTA_MAX_BITS, RETURN, and obd_device::u.
Referenced by osc_setup().
int osc_quotactl (struct obd_device * unused, struct obd_export * exp, struct obd_quotactl * oqctl)
Definition at line 248 of file osc_quota.c.
References CERROR, class_exp2cliimp(), ENTRY, LUSTRE_OST_VERSION, OST_QUOTACTL, ptlrpc_at_set_req_timeout(), ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc_pack(), ptlrpc_request_set_replen(), req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_OBD_QUOTACTL, ptlrpc_request::rq_no_resend, ptlrpc_request::rq_pill, ptlrpc_request::rq_repmsg, and RQF_OST_QUOTACTL.
static int osc_recoverable_error (int rc) [inline, static]
Definition at line 160 of file osc_internal.h.
Referenced by brw_interpret().
int osc_setattr_async (struct obd_export * exp, struct obdo * oa, obd_enqueue_update_f upcall, void * cookie, struct ptlrpc_request_set * rqset)
Definition at line 231 of file osc_request.c.
References class_exp2cliimp(), CLASSERT, ENTRY, LUSTRE_OST_VERSION, osc_pack_req_body(), osc_setattr_interpret(), OST_SETATTR, ptlrpc_req_async_args, ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), ptlrpc_set_add_req(), ptlrpcd_add_req(), PTLRPCD_SET, RETURN, RQF_OST_SETATTR, osc_setattr_args::sa_cookie, osc_setattr_args::sa_oa, and osc_setattr_args::sa_upcall.
Referenced by osc_io_setattr_start().
int osc_setup (struct obd_device * obd, struct lustre_cfg * lcfg)
Definition at line 2738 of file osc_request.c.
References brw_queue_work(), CERROR, client_obd::cl_grant_shrink_interval, client_obd::cl_grant_shrink_list, client_obd::cl_import, client_obd::cl_lru_work, client_obd::cl_max_rpcs_in_flight, client_obd::cl_shrink_list, client_obd::cl_writeback_work, class_search_type(), obd_device::cli, client_obd_cleanup(), client_obd_setup(), ENTRY, GOTO, GRANT_SHRINK_INTERVAL, handler(), INIT_LIST_HEAD, list_add_tail(), lproc_osc_attach_seqstat(), lprocfs_obd_setup(), lprocfs_register(), lru_queue_work(), LUSTRE_OSP_NAME, ns_register_cancel(), obd_device::obd_name, obd_device::obd_namespace, obd_device::obd_proc_entry, obd_device::obd_vars, osc_cancel_weight(), osc_pool_req_count, osc_quota_setup(), osc_reqpool_maxreqcount, osc_shrink_list, osc_shrink_lock, ptlrpc_add_rqs_to_pool(), ptlrpc_lprocfs_register_obd(), ptlrpcd_addref(), ptlrpcd_alloc_work(), ptlrpcd_decref(), ptlrpcd_destroy_work(), RETURN, sptlrpc_lprocfs_cliobd_attach(), obd_type::typ_procsym, and obd_device::u.
Referenced by osc_device_alloc().
int osc_shrink_grant_to_target (struct client_obd * cli, __u64 target_bytes)
Definition at line 804 of file osc_request.c.
References __osc_update_grant(), client_obd::cl_avail_grant, client_obd::cl_import, client_obd::cl_loi_list_lock, client_obd::cl_max_pages_per_rpc, ENTRY, obd_import::imp_obd, KEY_GRANT_SHRINK, obdo::o_flags, obdo::o_grant, obdo::o_valid, ost_body::oa, OBD_ALLOC_PTR, OBD_FL_SHRINK_GRANT, OBD_FREE_PTR, OBD_MD_FLFLAGS, obd_device::obd_self_export, osc_announce_cached(), osc_set_info_async(), osc_update_next_shrink(), and RETURN.
Referenced by osc_shrink_grant().
int osc_sync_base (struct osc_object * obj, struct obdo * oa, obd_enqueue_update_f upcall, void * cookie, struct ptlrpc_request_set * rqset)
Definition at line 498 of file osc_request.c.
References class_exp2cliimp(), CLASSERT, ENTRY, osc_fsync_args::fa_cookie, osc_fsync_args::fa_oa, osc_fsync_args::fa_obj, osc_fsync_args::fa_upcall, obd_import::imp_connect_data, LASSERT, LUSTRE_OST_VERSION, lustre_set_wire_obdo(), ost_body::oa, osc_export(), osc_sync_interpret(), OST_SYNC, ptlrpc_req_async_args, ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), ptlrpc_set_add_req(), ptlrpcd_add_req(), PTLRPCD_SET, req_capsule_client_get(), RETURN, RMF_OST_BODY, ptlrpc_request::rq_import, ptlrpc_request::rq_pill, and RQF_OST_SYNC.
Referenced by osc_fsync_ost().
void osc_update_next_shrink (struct client_obd * cli)
Definition at line 724 of file osc_request.c.
References CDEBUG, cfs_time_shift(), client_obd::cl_grant_shrink_interval, client_obd::cl_next_shrink_grant, and D_CACHE.
Referenced by osc_add_shrink_grant(), osc_consume_write_grant(), osc_should_shrink_grant(), osc_shrink_grant_local(), and osc_shrink_grant_to_target().
static unsigned long rpcs_in_flight (struct client_obd * cli) [inline, static]
Definition at line 166 of file osc_internal.h.
References client_obd::cl_r_in_flight, and client_obd::cl_w_in_flight.
Referenced by osc_check_rpcs(), and osc_max_rpc_in_flight().
Variable Documentation
atomic_t osc_pool_req_count
Definition at line 59 of file osc_request.c.
Referenced by osc_init(), and osc_setup().
unsigned int osc_reqpool_maxreqcount
Definition at line 60 of file osc_request.c.
Referenced by osc_init(), and osc_setup().
struct ptlrpc_request_pool* osc_rq_pool
Definition at line 61 of file osc_request.c.
struct list_head osc_shrink_list
osc shrink list to link all osc client obd
Definition at line 2940 of file osc_request.c.
Referenced by osc_cache_shrink_count(), osc_cache_shrink_scan(), and osc_setup().
spinlock_t osc_shrink_lock
spin lock to protect osc_shrink_list
Referenced by osc_cache_shrink_count(), osc_cache_shrink_scan(), osc_cleanup(), and osc_setup().
struct ptlrpc_request_set* PTLRPCD_SET
Definition at line 2043 of file osc_request.c.
Referenced by osc_fsync_ost(), osc_io_ladvise_start(), osc_io_setattr_start(), osc_ladvise_base(), osc_lock_enqueue(), osc_punch_base(), osc_setattr_async(), and osc_sync_base().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.