Lustre: lustre/osd-zfs/osd_internal.h File Reference
lustre/osd-zfs/osd_internal.h File Reference
#include <dt_object.h>
#include <md_object.h>
#include <lustre_quota.h>
#include <sys/arc.h>
#include <sys/nvpair.h>
#include <sys/zfs_znode.h>
#include <sys/zap.h>
#include <sys/dbuf.h>
Data Structures
struct osd_it_quota
Iterator's in-memory data structure for quota file.
struct osd_zap_it
Iterator's in-memory data structure for ZAPs.
struct zpl_direntry
struct luz_direntry
struct osa_attr
struct osd_thread_info
struct osd_thandle
struct osd_oi
struct osd_seq
struct osd_seq_list
struct osd_device
struct osd_object
Defines
#define LUSTRE_ROOT_FID_SEQ 0
By design including kmem.h overrides the Linux slab interfaces to provide the Illumos kmem cache interfaces.
#define DMU_OSD_SVNAME "svname"
#define DMU_OSD_OI_NAME_BASE "oi"
#define OSD_GFP_IO (GFP_NOFS | __GFP_HIGHMEM)
#define OSD_STATFS_RESERVED_SIZE (16ULL << 20)
#define OSD_STATFS_RESERVED_SHIFT (7)
#define OSD_DNODE_MIN_BLKSHIFT (DNODES_PER_BLOCK_SHIFT)
#define OSD_DNODE_EST_BLKSHIFT (DNODES_PER_BLOCK_SHIFT >> 1)
#define OSD_DNODE_EST_COUNT 1024
#define OSD_GRANT_FOR_LOCAL_OIDS (2ULL << 20)
#define DT_IT2DT(it) (&((struct osd_zap_it *)it)->ozi_obj->oo_dt)
#define OSD_OI_NAME_SIZE 16
#define OSD_OST_MAP_SIZE 32
#define osd_spa_maxblocksize(spa) SPA_MAXBLOCKSIZE
#define osd_spa_maxblockshift(spa) SPA_MAXBLOCKSHIFT
#define SPA_OLD_MAXBLOCKSIZE SPA_MAXBLOCKSIZE
#define osd_zio_buf_alloc(size) zio_buf_alloc(size)
#define osd_zio_buf_free(buf, size) zio_buf_free(buf, size)
Enumerations
enum osd_destroy_type { OSD_DESTROY_NONE = 0, OSD_DESTROY_SYNC = 1, OSD_DESTROY_ASYNC = 2 }
Functions
static struct osd_thread_info * osd_oti_get (const struct lu_env *env)
int osd_statfs (const struct lu_env *, struct dt_device *, struct obd_statfs *)
uint64_t osd_quota_fid2dmu (const struct lu_fid *fid)
Helper function to retrieve DMU object id from fid for accounting object.
int osd_declare_quota (const struct lu_env *env, struct osd_device *osd, qid_t uid, qid_t gid, long long space, struct osd_thandle *oh, bool is_blk, int *flags, bool force)
Quota Enforcement Management.
uint64_t osd_objs_count_estimate (uint64_t refdbytes, uint64_t usedobjs, uint64_t nrblocks, uint64_t est_maxblockshift)
static int lu_device_is_osd (const struct lu_device *d)
static struct osd_object * osd_obj (const struct lu_object *o)
static struct osd_device * osd_dt_dev (const struct dt_device *d)
static struct osd_device * osd_dev (const struct lu_device *d)
static struct osd_object * osd_dt_obj (const struct dt_object *d)
static struct osd_device * osd_obj2dev (const struct osd_object *o)
static struct lu_device * osd2lu_dev (struct osd_device *osd)
static struct objset * osd_dtobj2objset (struct dt_object *o)
static int osd_invariant (const struct osd_object *obj)
static int osd_object_invariant (const struct lu_object *l)
static struct seq_server_site * osd_seq_site (struct osd_device *osd)
static char * osd_name (struct osd_device *osd)
static void dsl_pool_config_enter (dsl_pool_t *dp, char *name)
static void dsl_pool_config_exit (dsl_pool_t *dp, char *name)
Variables
struct zpl_direntry packed
struct lu_context_key osd_key
struct dt_index_operations osd_acct_index_ops
Index and Iterator operations for accounting objects.
struct lu_device_operations osd_lu_ops
struct dt_index_operations osd_dir_ops
Define Documentation
#define DMU_OSD_OI_NAME_BASE "oi"
Definition at line 82 of file osd_internal.h.
Referenced by osd_oi_init(), osd_oi_open_table(), and osd_oi_probe().
#define DMU_OSD_SVNAME "svname"
Definition at line 81 of file osd_internal.h.
#define DT_IT2DT (it) (&((struct osd_zap_it *)it)->ozi_obj->oo_dt)
Definition at line 133 of file osd_internal.h.
#define LUSTRE_ROOT_FID_SEQ 0
By design including kmem.h overrides the Linux slab interfaces to provide the Illumos kmem cache interfaces.
To override this and gain access to the Linux interfaces these preprocessor macros must be undefined.
Definition at line 80 of file osd_internal.h.
#define OSD_DNODE_EST_BLKSHIFT (DNODES_PER_BLOCK_SHIFT >> 1)
Definition at line 92 of file osd_internal.h.
Referenced by osd_objs_count_estimate().
#define OSD_DNODE_EST_COUNT 1024
Definition at line 93 of file osd_internal.h.
Referenced by osd_conf_get(), and osd_objs_count_estimate().
#define OSD_DNODE_MIN_BLKSHIFT (DNODES_PER_BLOCK_SHIFT)
Definition at line 91 of file osd_internal.h.
Referenced by osd_objs_count_estimate().
#define OSD_GFP_IO (GFP_NOFS | __GFP_HIGHMEM)
Definition at line 84 of file osd_internal.h.
Referenced by osd_bufs_get_write().
#define OSD_GRANT_FOR_LOCAL_OIDS (2ULL << 20)
Definition at line 95 of file osd_internal.h.
Referenced by osd_statfs().
#define OSD_OI_NAME_SIZE 16
Definition at line 217 of file osd_internal.h.
#define OSD_OST_MAP_SIZE 32
Definition at line 241 of file osd_internal.h.
Referenced by osd_find_or_add_seq(), and osd_get_idx_for_ost_obj().
#define osd_spa_maxblockshift (spa) SPA_MAXBLOCKSHIFT
Definition at line 577 of file osd_internal.h.
Referenced by osd_blk_insert_cost().
#define osd_spa_maxblocksize (spa) SPA_MAXBLOCKSIZE
Definition at line 576 of file osd_internal.h.
Referenced by osd_attr_get(), and osd_recordsize_changed_cb().
#define OSD_STATFS_RESERVED_SHIFT (7)
Definition at line 88 of file osd_internal.h.
#define OSD_STATFS_RESERVED_SIZE (16ULL << 20)
Definition at line 87 of file osd_internal.h.
Referenced by osd_objset_statfs().
#define osd_zio_buf_alloc (size) zio_buf_alloc(size)
Definition at line 594 of file osd_internal.h.
Referenced by __osd_sa_xattr_update(), and __osd_xattr_load().
#define osd_zio_buf_free (buf, size) zio_buf_free(buf, size)
Definition at line 595 of file osd_internal.h.
Referenced by __osd_sa_xattr_update(), and __osd_xattr_load().
#define SPA_OLD_MAXBLOCKSIZE SPA_MAXBLOCKSIZE
Definition at line 578 of file osd_internal.h.
Referenced by osd_mount().
Enumeration Type Documentation
enum osd_destroy_type
Enumerator:
OSD_DESTROY_NONE
OSD_DESTROY_SYNC
OSD_DESTROY_ASYNC
Definition at line 304 of file osd_internal.h.
Function Documentation
static void dsl_pool_config_enter (dsl_pool_t * dp, char * name) [inline, static]
Definition at line 563 of file osd_internal.h.
Referenced by osd_objset_register_callbacks().
static void dsl_pool_config_exit (dsl_pool_t * dp, char * name) [inline, static]
Definition at line 567 of file osd_internal.h.
Referenced by osd_objset_register_callbacks().
static int lu_device_is_osd (const struct lu_device * d) [inline, static]
Definition at line 367 of file osd_internal.h.
References ergo, lu_device::ld_ops, and osd_lu_ops.
Referenced by osd_dev(), osd_dt_dev(), and osd_obj().
static struct lu_device* osd2lu_dev (struct osd_device * osd) [static, read]
Definition at line 400 of file osd_internal.h.
References dt_device::dd_lu_dev, and osd_device::od_dt_dev.
int osd_declare_quota (const struct lu_env * env, struct osd_device * osd, qid_t uid, qid_t gid, long long space, struct osd_thandle * oh, bool is_blk, int * flags, bool force)
Quota Enforcement Management.
Definition at line 482 of file osd_quota.c.
References ENTRY, lquota_id_info::lqi_id, lquota_id_info::lqi_is_blk, lquota_id_info::lqi_space, lquota_id_info::lqi_type, osd_device::od_quota_slave, osd_oti_get(), osd_thandle::ot_quota_trans, osd_thread_info::oti_qi, lquota_id::qid_gid, lquota_id::qid_uid, qsd_op_begin(), RETURN, and unlikely.
Referenced by osd_declare_object_create(), osd_declare_object_destroy(), osd_declare_punch(), osd_declare_write(), and osd_declare_write_commit().
static struct osd_device* osd_dev (const struct lu_device * d) [static, read]
Definition at line 384 of file osd_internal.h.
References LASSERT, lu_device_is_osd(), and osd_dt_dev().
Referenced by osd_dtobj2objset(), and osd_obj2dev().
static struct osd_device* osd_dt_dev (const struct dt_device * d) [static, read]
Definition at line 378 of file osd_internal.h.
References dt_device::dd_lu_dev, LASSERT, lu_device_is_osd(), and osd_device::od_dt_dev.
Referenced by osd_dev().
static struct osd_object* osd_dt_obj (const struct dt_object * d) [static, read]
Definition at line 390 of file osd_internal.h.
References dt_object::do_lu, and osd_obj().
static struct objset* osd_dtobj2objset (struct dt_object * o) [static, read]
Definition at line 405 of file osd_internal.h.
References dt_object::do_lu, lu_object::lo_dev, osd_device::od_os, and osd_dev().
static int osd_invariant (const struct osd_object * obj) [inline, static]
Definition at line 410 of file osd_internal.h.
static char* osd_name (struct osd_device * osd) [inline, static]
Definition at line 425 of file osd_internal.h.
References dt_device::dd_lu_dev, lu_device::ld_obd, obd_device::obd_name, and osd_device::od_dt_dev.
static struct osd_object* osd_obj (const struct lu_object * o) [static, read]
Definition at line 372 of file osd_internal.h.
References dt_object::do_lu, LASSERT, lu_object::lo_dev, lu_device_is_osd(), and osd_object::oo_dt.
Referenced by osd_dt_obj(), and osd_object_invariant().
static struct osd_device* osd_obj2dev (const struct osd_object * o) [static, read]
Definition at line 395 of file osd_internal.h.
References dt_object::do_lu, lu_object::lo_dev, osd_object::oo_dt, and osd_dev().
static int osd_object_invariant (const struct lu_object * l) [inline, static]
Definition at line 415 of file osd_internal.h.
References osd_invariant, and osd_obj().
uint64_t osd_objs_count_estimate (uint64_t refdbytes, uint64_t usedobjs, uint64_t nrblocks, uint64_t est_maxblockshift)
Definition at line 368 of file osd_handler.c.
References CLASSERT, OSD_DNODE_EST_BLKSHIFT, OSD_DNODE_EST_COUNT, and OSD_DNODE_MIN_BLKSHIFT.
Referenced by osd_objset_statfs(), and osd_objset_user_iused().
static struct osd_thread_info* osd_oti_get (const struct lu_env * env) [static, read]
Definition at line 199 of file osd_internal.h.
References lu_env::le_ctx, lu_context_key_get(), and osd_key.
uint64_t osd_quota_fid2dmu (const struct lu_fid * fid)
Helper function to retrieve DMU object id from fid for accounting object.
Definition at line 37 of file osd_quota.c.
References ACCT_GROUP_OID, fid_is_acct(), fid_oid(), and LASSERT.
Referenced by osd_acct_index_lookup(), and osd_it_acct_init().
static struct seq_server_site* osd_seq_site (struct osd_device * osd) [static, read]
Definition at line 420 of file osd_internal.h.
References dt_device::dd_lu_dev, lu_site::ld_seq_site, lu_device::ld_site, and osd_device::od_dt_dev.
int osd_statfs (const struct lu_env * , struct dt_device * , struct obd_statfs *)
Definition at line 1586 of file osd_handler.c.
References __u64, CLASSERT, ENTRY, likely, min_t, OBD_ALLOC_PTR, OBD_FREE_PTR, osd_device::od_mnt, obd_statfs::os_bavail, obd_statfs::os_bfree, obd_statfs::os_blocks, obd_statfs::os_bsize, obd_statfs::os_maxbytes, obd_statfs::os_state, OS_STATE_READONLY, osd_dt_dev(), OSD_GRANT_FOR_LOCAL_OIDS, osd_objset_statfs(), osd_oti_get(), osd_sb(), OSD_STATFS_RESERVED, OSD_STATFS_RESERVED_SHIFT, osd_thread_info::oti_ksfs, RETURN, statfs_pack(), and unlikely.
Variable Documentation
struct dt_index_operations osd_acct_index_ops
Index and Iterator operations for accounting objects.
Quota/Accounting handling.
Definition at line 420 of file osd_quota.c.
struct dt_index_operations osd_dir_ops
Definition at line 1134 of file osd_index.c.
Referenced by osd_declare_object_create().
struct lu_context_key osd_key [read]
Definition at line 6122 of file osd_handler.c.
Referenced by osd_oti_get(), osd_type_fini(), and osd_type_init().
struct lu_device_operations osd_lu_ops
Definition at line 6701 of file osd_handler.c.
Referenced by lu_device_is_osd(), and osd_device_init0().
struct luz_direntry packed
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.