Lustre: lustre/osd-ldiskfs/osd_quota.c File Reference
lustre/osd-ldiskfs/osd_quota.c File Reference
#include <lustre_quota.h>
#include "osd_internal.h"
Defines
#define QUOTA_IT_READ_ERROR(it, rc)
Functions
static int fid2type (const struct lu_fid *fid)
Helpers function to find out the quota type (USRQUOTA/GRPQUOTA) of a given object.
static int obj2type (struct dt_object *obj)
int osd_acct_obj_lookup (struct osd_thread_info *info, struct osd_device *osd, const struct lu_fid *fid, struct osd_inode_id *id)
Space Accounting Management.
static int osd_acct_index_lookup (const struct lu_env *env, struct dt_object *dtobj, struct dt_rec *dtrec, const struct dt_key *dtkey)
Return space usage (blocks & inodes) consumed by a given uid or gid.
static struct dt_it * osd_it_acct_init (const struct lu_env *env, struct dt_object *dt, __u32 attr)
Initialize osd Iterator for given osd index object.
static void osd_it_acct_fini (const struct lu_env *env, struct dt_it *di)
Free given iterator.
static int osd_it_acct_get (const struct lu_env *env, struct dt_it *di, const struct dt_key *key)
Move Iterator to record specified by key, if the key isn't found, move to the first valid record.
static void osd_it_acct_put (const struct lu_env *env, struct dt_it *di)
Release Iterator.
static int osd_it_add_processed (struct osd_it_quota *it, int depth)
static int osd_it_acct_next (const struct lu_env *env, struct dt_it *di)
Move on to the next valid entry.
static struct dt_key * osd_it_acct_key (const struct lu_env *env, const struct dt_it *di)
Return pointer to the key under iterator.
static int osd_it_acct_key_size (const struct lu_env *env, const struct dt_it *di)
Return size of key under iterator (in bytes).
static int osd_it_acct_rec (const struct lu_env *env, const struct dt_it *di, struct dt_rec *dtrec, __u32 attr)
Return pointer to the record under iterator.
static __u64 osd_it_acct_store (const struct lu_env *env, const struct dt_it *di)
Returns cookie for current Iterator position.
static int osd_it_acct_load (const struct lu_env *env, const struct dt_it *di, __u64 hash)
Restore iterator from cookie.
static void osd_quota_swab (char *ptr, size_t size)
struct dt_rec * osd_quota_pack (struct osd_object *obj, const struct dt_rec *rec, union lquota_rec *quota_rec)
void osd_quota_unpack (struct osd_object *obj, const struct dt_rec *rec)
static int osd_qid_type (struct osd_thandle *oh, int i)
static void osd_qid_set_type (struct osd_thandle *oh, int i, int type)
int osd_declare_qid (const struct lu_env *env, struct osd_thandle *oh, struct lquota_id_info *qi, struct osd_object *obj, bool enforce, int *flags)
Reserve journal credits for quota files update first, then call ->op_begin() to perform quota enforcement.
int osd_declare_inode_qid (const struct lu_env *env, qid_t uid, qid_t gid, long long space, struct osd_thandle *oh, struct osd_object *obj, bool is_blk, int *flags, bool force)
Wrapper for osd_declare_qid().
int osd_quota_migration (const struct lu_env *env, struct dt_object *dt)
Variables
struct dt_index_operations osd_acct_index_ops
Index and Iterator operations for accounting objects.
Define Documentation
#define QUOTA_IT_READ_ERROR (it, rc)
Value:
CERROR("%s: Error while trying to read quota information, "    \
               "failed with %d\n",                                     \
               osd_dev(it->oiq_obj->oo_dt.do_lu.lo_dev)->od_svname, rc); \
Definition at line 139 of file osd_quota.c.
Referenced by osd_it_acct_get(), and osd_it_acct_next().
Function Documentation
static int fid2type (const struct lu_fid * fid) [inline, static]
Helpers function to find out the quota type (USRQUOTA/GRPQUOTA) of a given object.
Definition at line 38 of file osd_quota.c.
References ACCT_GROUP_OID, fid_is_acct(), fid_oid(), and LASSERT.
Referenced by obj2type(), osd_acct_obj_lookup(), osd_it_acct_get(), and osd_it_acct_next().
static int obj2type (struct dt_object * obj) [inline, static]
Definition at line 46 of file osd_quota.c.
References dt_object::do_lu, fid2type(), and lu_object_fid().
Referenced by osd_acct_index_lookup().
static int osd_acct_index_lookup (const struct lu_env * env, struct dt_object * dtobj, struct dt_rec * dtrec, const struct dt_key * dtkey) [static]
Return space usage (blocks & inodes) consumed by a given uid or gid.
Parameters:
env - is the environment passed by the caller
dtobj - is the accounting object
dtrec - is the record to fill with space usage information
dtkey - is the id of the user or group for which we would like to access disk usage.
Return values:
+ve - success : exact match
-ve - failure
Definition at line 99 of file osd_quota.c.
References __u64, lquota_acct_rec::bspace, ENTRY, lquota_acct_rec::ispace, obj2type(), osd_dt_obj(), osd_obj2dev(), osd_oti_get(), osd_sb(), osd_thread_info::oti_dqblk, and RETURN.
Referenced by osd_it_acct_rec().
int osd_acct_obj_lookup (struct osd_thread_info * info, struct osd_device * osd, const struct lu_fid * fid, struct osd_inode_id * id)
Space Accounting Management.
Look up an accounting object based on its fid.
Parameters:
info - is the osd thread info passed by the caller
osd - is the osd device
fid - is the fid of the accounting object we want to look up
id - is the osd_inode_id struct to fill with the inode number of the quota file if the lookup is successful
Definition at line 64 of file osd_quota.c.
References ENTRY, fid2type(), fid_is_acct(), LASSERT, le32_to_cpu, osd_inode_id::oii_ino, OSD_OII_NOGEN, osd_sb(), and RETURN.
Referenced by osd_oi_lookup().
int osd_declare_inode_qid (const struct lu_env * env, qid_t uid, qid_t gid, long long space, struct osd_thandle * oh, struct osd_object * obj, bool is_blk, int * flags, bool force)
Wrapper for osd_declare_qid().
Parameters:
env - the environment passed by the caller
uid - user id of the inode
gid - group id of the inode
space - how many blocks/inodes will be consumed/released
oh - osd transaction handle
obj - osd object, could be NULL when it's under create
is_blk - block quota or inode quota?
flags - if the operation is write, return no user quota, no group quota, or sync commit flags to the caller
force - set to 1 when changes are performed by root user and thus can't failed with EDQUOT
Return values:
0 - success
-ve - failure
Definition at line 590 of file osd_quota.c.
References ENTRY, lquota_id_info::lqi_id, lquota_id_info::lqi_is_blk, lquota_id_info::lqi_space, lquota_id_info::lqi_type, osd_declare_qid(), osd_oti_get(), osd_thread_info::oti_qi, lquota_id::qid_gid, lquota_id::qid_uid, and RETURN.
Referenced by osd_declare_object_create(), osd_declare_object_destroy(), osd_declare_punch(), osd_declare_write(), osd_declare_write_commit(), osd_index_declare_ea_delete(), and osd_index_declare_ea_insert().
int osd_declare_qid (const struct lu_env * env, struct osd_thandle * oh, struct lquota_id_info * qi, struct osd_object * obj, bool enforce, int * flags)
Reserve journal credits for quota files update first, then call ->op_begin() to perform quota enforcement.
Parameters:
env - the environment passed by the caller
oh - osd transaction handle
qi - quota id & space required for this operation
obj - osd object, could be NULL when it's under create
enforce - whether to perform quota enforcement
flags - if the operation is write, return no user quota, no group quota, or sync commit flags to the caller
Return values:
0 - success
-ve - failure
Definition at line 504 of file osd_quota.c.
References CERROR, ENTRY, LASSERT, LASSERTF, lquota_id_info::lqi_id, lquota_id_info::lqi_space, lquota_id_info::lqi_type, osd_device::od_quota_slave, osd_object::oo_inode, osd_dt_dev(), OSD_MAX_UGID_CNT, OSD_OT_QUOTA, osd_qid_set_type(), osd_qid_type(), osd_sb(), osd_trans_declare_op(), osd_thandle::ot_id_array, osd_thandle::ot_id_cnt, osd_thandle::ot_quota_trans, osd_thandle::ot_super, lquota_id::qid_uid, qsd_op_begin(), RETURN, thandle::th_dev, and unlikely.
Referenced by osd_declare_attr_set(), and osd_declare_inode_qid().
static void osd_it_acct_fini (const struct lu_env * env, struct dt_it * di) [static]
Free given iterator.
Parameters:
di - osd iterator
Definition at line 184 of file osd_quota.c.
References dt_object::do_lu, ENTRY, EXIT, list_del_init(), list_for_each_entry_safe, lu_object_put(), OBD_FREE_PTR, osd_it_quota::oiq_list, osd_it_quota::oiq_obj, osd_object::oo_dt, and osd_quota_leaf::oql_link.
static int osd_it_acct_get (const struct lu_env * env, struct dt_it * di, const struct dt_key * key) [static]
Move Iterator to record specified by key, if the key isn't found, move to the first valid record.
Parameters:
di - osd iterator
key - uid or gid
Return values:
+ve - di points to the first valid record
+1 - di points to exact matched key
-ve - failure
Definition at line 213 of file osd_quota.c.
References dt_object::do_lu, ENTRY, fid2type(), find_tree_dqentry(), lu_object_fid(), LUSTRE_DQTREEOFF, osd_it_quota::oiq_blk, osd_it_quota::oiq_obj, osd_object::oo_dt, QUOTA_IT_READ_ERROR, RETURN, and walk_tree_dqentry().
Referenced by osd_it_acct_load().
static struct dt_it* osd_it_acct_init (const struct lu_env * env, struct dt_object * dt, __u32 attr) [static, read]
Initialize osd Iterator for given osd index object.
Parameters:
dt - osd index object
attr - not used
Definition at line 150 of file osd_quota.c.
References dt_object::do_lu, ENTRY, INIT_LIST_HEAD, LASSERT, lu_object_exists, lu_object_get(), LUSTRE_DQTREEOFF, OBD_ALLOC_PTR, osd_it_quota::oiq_blk, osd_it_quota::oiq_list, osd_it_quota::oiq_obj, osd_dt_obj(), and RETURN.
static struct dt_key* osd_it_acct_key (const struct lu_env * env, const struct dt_it * di) [static, read]
Return pointer to the key under iterator.
Parameters:
di - osd iterator
Definition at line 341 of file osd_quota.c.
References dt_key, ENTRY, osd_it_quota::oiq_id, and RETURN.
Referenced by osd_it_acct_rec().
static int osd_it_acct_key_size (const struct lu_env * env, const struct dt_it * di) [static]
Return size of key under iterator (in bytes).
Parameters:
di - osd iterator
Definition at line 355 of file osd_quota.c.
References ENTRY, osd_it_quota::oiq_id, and RETURN.
static int osd_it_acct_load (const struct lu_env * env, const struct dt_it * di, __u64 hash) [static]
Restore iterator from cookie.
if the hash isn't found, restore the first valid record.
Parameters:
di - osd iterator
hash - iterator location cookie
Return values:
+ve - di points to the first valid record
+1 - di points to exact matched hash
-ve - failure
Definition at line 409 of file osd_quota.c.
References dt_key, ENTRY, osd_it_acct_get(), and RETURN.
static int osd_it_acct_next (const struct lu_env * env, struct dt_it * di) [static]
Move on to the next valid entry.
Parameters:
di - osd iterator
Return values:
+ve - iterator reached the end
0 - iterator has not reached the end yet
-ve - unexpected failure
Definition at line 278 of file osd_quota.c.
References dt_object::do_lu, ENTRY, fid2type(), lu_object_fid(), LUSTRE_DQSTRINBLK, LUSTRE_DQTREEDEPTH, osd_it_quota::oiq_blk, osd_it_quota::oiq_index, osd_it_quota::oiq_obj, osd_object::oo_dt, osd_it_add_processed(), QUOTA_IT_READ_ERROR, RETURN, walk_block_dqentry(), and walk_tree_dqentry().
static void osd_it_acct_put (const struct lu_env * env, struct dt_it * di) [static]
Release Iterator.
Parameters:
di - osd iterator
Definition at line 251 of file osd_quota.c.
static int osd_it_acct_rec (const struct lu_env * env, const struct dt_it * di, struct dt_rec * dtrec, __u32 attr) [static]
Return pointer to the record under iterator.
Parameters:
di - osd iterator
attr - not used
Definition at line 370 of file osd_quota.c.
References dt_key, ENTRY, osd_it_quota::oiq_obj, osd_object::oo_dt, osd_acct_index_lookup(), osd_it_acct_key(), and RETURN.
static __u64 osd_it_acct_store (const struct lu_env * env, const struct dt_it * di) [static]
Returns cookie for current Iterator position.
Parameters:
di - osd iterator
Definition at line 389 of file osd_quota.c.
References ENTRY, osd_it_quota::oiq_id, and RETURN.
static int osd_it_add_processed (struct osd_it_quota * it, int depth) [static]
Definition at line 256 of file osd_quota.c.
References INIT_LIST_HEAD, list_add_tail(), OBD_ALLOC_PTR, osd_it_quota::oiq_blk, osd_it_quota::oiq_list, osd_quota_leaf::oql_blk, osd_quota_leaf::oql_link, and RETURN.
Referenced by osd_it_acct_next().
static void osd_qid_set_type (struct osd_thandle * oh, int i, int type) [inline, static]
Definition at line 484 of file osd_quota.c.
References osd_thandle::ot_id_type.
Referenced by osd_declare_qid().
static int osd_qid_type (struct osd_thandle * oh, int i) [inline, static]
Definition at line 479 of file osd_quota.c.
References osd_thandle::ot_id_type.
Referenced by osd_declare_qid().
int osd_quota_migration (const struct lu_env * env, struct dt_object * dt)
Definition at line 630 of file osd_quota.c.
References ADMIN_GRP, ADMIN_USR, CERROR, DFID, dt_object::do_lu, dt_locate(), dt_lookup_dir(), dt_object_exists(), dt_root_get(), dt_version_get(), ENTRY, fname, GOTO, LCONSOLE_WARN, lu_object_put(), OBJECTS, osd_device::od_dt_dev, osd_device::od_svname, osd_dt_obj(), osd_obj2dev(), osd_oti_get(), osd_thread_info::oti_fid, PFID, RETURN, and version.
Referenced by osd_index_try().
struct dt_rec* osd_quota_pack (struct osd_object * obj, const struct dt_rec * rec, union lquota_rec * quota_rec) [read]
Definition at line 446 of file osd_quota.c.
References iam_container::ic_descr, iam_descr::id_rec_size, LASSERT, osd_directory::od_container, osd_object::oo_dir, and osd_quota_swab().
Referenced by osd_index_iam_insert().
static void osd_quota_swab (char * ptr, size_t size) [inline, static]
Definition at line 436 of file osd_quota.c.
References __swab64s, __u64, and LASSERT.
Referenced by osd_quota_pack(), and osd_quota_unpack().
void osd_quota_unpack (struct osd_object * obj, const struct dt_rec * rec)
Definition at line 465 of file osd_quota.c.
References iam_container::ic_descr, iam_descr::id_rec_size, LASSERT, osd_directory::od_container, osd_object::oo_dir, and osd_quota_swab().
Referenced by osd_index_iam_lookup(), and osd_it_iam_rec().
Variable Documentation
struct dt_index_operations osd_acct_index_ops
Initial value:
 {
        .dio_lookup     = osd_acct_index_lookup,
        .dio_it         = {
                .init           = osd_it_acct_init,
                .fini           = osd_it_acct_fini,
                .get            = osd_it_acct_get,
                .put            = osd_it_acct_put,
                .next           = osd_it_acct_next,
                .key            = osd_it_acct_key,
                .key_size       = osd_it_acct_key_size,
                .rec            = osd_it_acct_rec,
                .store          = osd_it_acct_store,
                .load           = osd_it_acct_load
        }
}
Index and Iterator operations for accounting objects.
Quota/Accounting handling.
Definition at line 420 of file osd_quota.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.