Lustre: lustre/osd-ldiskfs/osd_io.c File Reference
lustre/osd-ldiskfs/osd_io.c File Reference
#include <lustre_ver.h>
#include <linux/types.h>
#include <linux/fs.h>
#include <obd_support.h>
#include "osd_internal.h"
#include <ldiskfs/ldiskfs_extents.h>
Data Structures
struct bpointers
struct osd_fextent
Defines
#define osd_init_iobuf(dev, iobuf, rw, pages) __osd_init_iobuf(dev, iobuf, rw, __LINE__, pages)
#define __REQ_WRITE BIO_RW
#define FIEMAP_MAX_EXTENTS (UINT_MAX / sizeof(struct fiemap_extent))
Functions
static int __osd_init_iobuf (struct osd_device *d, struct osd_iobuf *iobuf, int rw, int line, int pages)
static void osd_iobuf_add_page (struct osd_iobuf *iobuf, struct page *page)
void osd_fini_iobuf (struct osd_device *d, struct osd_iobuf *iobuf)
static void dio_complete_routine (struct bio *bio, int error)
static void record_start_io (struct osd_iobuf *iobuf, int size)
static void osd_submit_bio (int rw, struct bio *bio)
static int can_be_merged (struct bio *bio, sector_t sector)
static int osd_do_bio (struct osd_device *osd, struct inode *inode, struct osd_iobuf *iobuf)
static int osd_map_remote_to_local (loff_t offset, ssize_t len, int *nrpages, struct niobuf_local *lnb)
static struct page * osd_get_page (struct dt_object *dt, loff_t offset, int rw)
static int osd_bufs_put (const struct lu_env *env, struct dt_object *dt, struct niobuf_local *lnb, int npages)
Unlock and release pages loaded by osd_bufs_get().
static int osd_bufs_get (const struct lu_env *env, struct dt_object *dt, loff_t pos, ssize_t len, struct niobuf_local *lnb, int rw)
Load and lock pages undergoing IO.
static long ldiskfs_ext_find_goal (struct inode *inode, struct ldiskfs_ext_path *path, unsigned long block, int *aflags)
static unsigned long new_blocks (handle_t *handle, struct inode *inode, struct ldiskfs_ext_path *path, unsigned long block, unsigned long *count, int *err)
static int ldiskfs_ext_new_extent_cb (struct inode *inode, struct ldiskfs_ext_path *path, struct ldiskfs_ext_cache *cex, void *cbdata)
static int osd_ldiskfs_map_nblocks (struct inode *inode, unsigned long index, int clen, sector_t *blocks, int create)
static int osd_ldiskfs_map_bm_inode_pages (struct inode *inode, struct page **page, int pages, sector_t *blocks, int create)
static int osd_ldiskfs_map_ext_inode_pages (struct inode *inode, struct page **page, int pages, sector_t *blocks, int create)
static int osd_ldiskfs_map_inode_pages (struct inode *inode, struct page **page, int pages, sector_t *blocks, int create)
static int osd_write_prep (const struct lu_env *env, struct dt_object *dt, struct niobuf_local *lnb, int npages)
static int osd_is_mapped (struct dt_object *dt, __u64 offset, struct osd_fextent *cached_extent)
static int osd_declare_write_commit (const struct lu_env *env, struct dt_object *dt, struct niobuf_local *lnb, int npages, struct thandle *handle)
static int osd_write_commit (const struct lu_env *env, struct dt_object *dt, struct niobuf_local *lnb, int npages, struct thandle *thandle)
static int osd_read_prep (const struct lu_env *env, struct dt_object *dt, struct niobuf_local *lnb, int npages)
static int osd_ldiskfs_readlink (struct inode *inode, char *buffer, int buflen)
int osd_ldiskfs_read (struct inode *inode, void *buf, int size, loff_t *offs)
static ssize_t osd_read (const struct lu_env *env, struct dt_object *dt, struct lu_buf *buf, loff_t *pos)
static int osd_extents_enabled (struct super_block *sb, struct inode *inode)
int osd_calc_bkmap_credits (struct super_block *sb, struct inode *inode, const loff_t size, const loff_t pos, const int blocks)
static ssize_t osd_declare_write (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, loff_t _pos, struct thandle *handle)
static int osd_ldiskfs_writelink (struct inode *inode, char *buffer, int buflen)
int osd_ldiskfs_write_record (struct inode *inode, void *buf, int bufsize, int write_NUL, loff_t *offs, handle_t *handle)
static ssize_t osd_write (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, loff_t *pos, struct thandle *handle, int ignore_quota)
static int osd_declare_punch (const struct lu_env *env, struct dt_object *dt, __u64 start, __u64 end, struct thandle *th)
static int osd_punch (const struct lu_env *env, struct dt_object *dt, __u64 start, __u64 end, struct thandle *th)
static int fiemap_check_ranges (struct inode *inode, u64 start, u64 len, u64 *new_len)
static int osd_fiemap_get (const struct lu_env *env, struct dt_object *dt, struct fiemap *fm)
static int osd_ladvise (const struct lu_env *env, struct dt_object *dt, __u64 start, __u64 end, enum lu_ladvise_type advice)
Variables
struct dt_body_operations osd_body_ops_new
struct dt_body_operations osd_body_ops
Define Documentation
#define __REQ_WRITE BIO_RW
Definition at line 145 of file osd_io.c.
Referenced by dio_complete_routine().
#define FIEMAP_MAX_EXTENTS (UINT_MAX / sizeof(struct fiemap_extent))
Definition at line 1886 of file osd_io.c.
Referenced by osd_fiemap_get().
#define osd_init_iobuf (dev, iobuf, rw, pages) __osd_init_iobuf(dev, iobuf, rw, __LINE__, pages)
Definition at line 119 of file osd_io.c.
Referenced by osd_read_prep(), osd_write_commit(), and osd_write_prep().
Function Documentation
static int __osd_init_iobuf (struct osd_device * d, struct osd_iobuf * iobuf, int rw, int line, int pages) [static]
Definition at line 63 of file osd_io.c.
References CDEBUG, D_OTHER, osd_iobuf::dr_bl_buf, osd_iobuf::dr_blocks, osd_iobuf::dr_dev, osd_iobuf::dr_elapsed, osd_iobuf::dr_elapsed_valid, osd_iobuf::dr_error, osd_iobuf::dr_frags, osd_iobuf::dr_init_at, osd_iobuf::dr_max_pages, osd_iobuf::dr_npages, osd_iobuf::dr_numreqs, osd_iobuf::dr_pages, osd_iobuf::dr_pg_buf, osd_iobuf::dr_rw, osd_iobuf::dr_wait, LASSERT, LASSERTF, lu_buf::lb_buf, lu_buf::lb_len, lu_buf_realloc(), osd_sb(), PTLRPC_MAX_BRW_PAGES, and unlikely.
static int can_be_merged (struct bio * bio, sector_t sector) [static]
Definition at line 250 of file osd_io.c.
References bio_end_sector.
Referenced by osd_do_bio().
static void dio_complete_routine (struct bio * bio, int error) [static]
Definition at line 148 of file osd_io.c.
References __REQ_WRITE, bio_idx, bio_sectors, bvl_to_page, CERROR, osd_iobuf::dr_dev, osd_iobuf::dr_elapsed, osd_iobuf::dr_elapsed_valid, osd_iobuf::dr_error, osd_iobuf::dr_numreqs, osd_iobuf::dr_start_time, osd_iobuf::dr_wait, LASSERT, likely, osd_device::od_r_in_flight, osd_device::od_w_in_flight, and unlikely.
Referenced by osd_do_bio().
static int fiemap_check_ranges (struct inode * inode, u64 start, u64 len, u64 * new_len) [static]
Definition at line 1858 of file osd_io.c.
Referenced by osd_fiemap_get().
static long ldiskfs_ext_find_goal (struct inode * inode, struct ldiskfs_ext_path * path, unsigned long block, int * aflags) [static]
Definition at line 550 of file osd_io.c.
References le32_to_cpu.
Referenced by new_blocks().
static int ldiskfs_ext_new_extent_cb (struct inode * inode, struct ldiskfs_ext_path * path, struct ldiskfs_ext_cache * cex, void * cbdata) [static]
Definition at line 612 of file osd_io.c.
References bpointers::blocks, CERROR, cpu_to_le16, cpu_to_le32, bpointers::create, bpointers::init_num, LDISKFS_HT_MISC, le16_to_cpu, le32_to_cpu, new_blocks(), bpointers::num, osd_journal_start, and bpointers::start.
Referenced by osd_ldiskfs_map_nblocks().
static unsigned long new_blocks (handle_t * handle, struct inode * inode, struct ldiskfs_ext_path * path, unsigned long block, unsigned long * count, int * err) [static]
Definition at line 582 of file osd_io.c.
References ldiskfs_ext_find_goal().
Referenced by ldiskfs_ext_new_extent_cb().
static int osd_bufs_get (const struct lu_env * env, struct dt_object * dt, loff_t pos, ssize_t len, struct niobuf_local * lnb, int rw) [static]
Load and lock pages undergoing IO.
Pages as described in the lnb array are fetched (from disk or cache) and locked for IO by the caller.
DLM locking protects us from write and truncate competing for same region, but partial-page truncate can leave dirty pages in the cache for ldiskfs. It's possible the writeout on a such a page is in progress when we access it. It's also possible that during this writeout we put new (partial) data into the page, but won't be able to proceed in filter_commitrw_write(). Therefore, just wait for writeout completion as it should be rare enough.
Parameters:
env thread execution environment
dt dt object undergoing IO (OSD object + methods)
pos byte offset of IO start
len number of bytes of IO
lnb array of extents undergoing IO
rw read or write operation?
capa capabilities
Return values:
pages (zero or more) loaded successfully
-ENOMEM on memory/page allocation error
Definition at line 506 of file osd_io.c.
References cleanup(), dt_object::do_lu, GOTO, LASSERT, niobuf_local::lnb_file_offset, niobuf_local::lnb_page, lu_object_get(), osd_object::oo_inode, osd_bufs_put(), osd_dt_obj(), osd_get_page(), osd_map_remote_to_local(), and RETURN.
static int osd_bufs_put (const struct lu_env * env, struct dt_object * dt, struct niobuf_local * lnb, int npages) [static]
Unlock and release pages loaded by osd_bufs_get().
Unlock npages pages from lnb and drop the refcount on them.
Parameters:
env thread execution environment
dt dt object undergoing IO (OSD object + methods)
lnb array of pages undergoing IO
npages number of pages in lnb
Return values:
0 always
Definition at line 464 of file osd_io.c.
References dt_object::do_lu, LASSERT, niobuf_local::lnb_page, lu_object_put(), and RETURN.
Referenced by osd_bufs_get().
int osd_calc_bkmap_credits (struct super_block * sb, struct inode * inode, const loff_t size, const loff_t pos, const int blocks)
Definition at line 1491 of file osd_io.c.
References credits, and LASSERT.
Referenced by osd_declare_write(), and osd_declare_xattr_set().
static int osd_declare_punch (const struct lu_env * env, struct dt_object * dt, __u64 start, __u64 end, struct thandle * th) [static]
Definition at line 1764 of file osd_io.c.
References DTO_ATTR_SET_BASE, ENTRY, i_gid_read(), i_uid_read(), LASSERT, osd_object::oo_inode, osd_declare_inode_qid(), osd_dt_obj(), osd_dto_credits_noquota, OSD_OT_PUNCH, osd_trans_declare_op(), and RETURN.
static ssize_t osd_declare_write (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, loff_t _pos, struct thandle * handle) [static]
Definition at line 1539 of file osd_io.c.
References credits, ENTRY, i_gid_read(), i_uid_read(), LASSERT, lu_buf::lb_len, max, osd_object::oo_inode, osd_calc_bkmap_credits(), osd_declare_inode_qid(), osd_dt_obj(), osd_extents_enabled(), osd_obj2dev(), OSD_OT_WRITE, osd_sb(), osd_trans_declare_op(), osd_thandle::ot_handle, osd_thandle::ot_super, RETURN, and size.
static int osd_declare_write_commit (const struct lu_env * env, struct dt_object * dt, struct niobuf_local * lnb, int npages, struct thandle * handle) [static]
Definition at line 1095 of file osd_io.c.
References credits, ENTRY, i_gid_read(), i_uid_read(), LASSERT, LDISKFS_EXTENTS_FL, niobuf_local::lnb_flags, max, OBD_BRW_FROM_GRANT, OBD_BRW_NOQUOTA, OBD_BRW_OVER_GRPQUOTA, OBD_BRW_OVER_USRQUOTA, OBD_BRW_SYNC, osd_object::oo_inode, osd_declare_inode_qid(), osd_dt_obj(), osd_is_mapped(), osd_obj2dev(), OSD_OT_WRITE, osd_sb(), osd_trans_declare_op(), osd_thandle::ot_handle, QUOTA_FL_OVER_GRPQUOTA, QUOTA_FL_OVER_USRQUOTA, RETURN, and toqb.
static int osd_do_bio (struct osd_device * osd, struct inode * inode, struct osd_iobuf * iobuf) [static]
Definition at line 258 of file osd_io.c.
References bio_sectors, bio_set_sector, blocksize(), can_be_merged(), CDEBUG, CERROR, cfs_time_current(), D_INODE, dio_complete_routine(), osd_iobuf::dr_blocks, osd_iobuf::dr_error, osd_iobuf::dr_npages, osd_iobuf::dr_numreqs, osd_iobuf::dr_pages, osd_iobuf::dr_rw, osd_iobuf::dr_start_time, osd_iobuf::dr_wait, ENTRY, LASSERT, LASSERTF, osd_fini_iobuf(), osd_submit_bio(), READ, record_start_io(), RETURN, and WRITE.
Referenced by osd_read_prep(), osd_write_commit(), and osd_write_prep().
static int osd_extents_enabled (struct super_block * sb, struct inode * inode) [inline, static]
Definition at line 1478 of file osd_io.c.
References LDISKFS_EXTENTS_FL.
Referenced by osd_declare_write().
static int osd_fiemap_get (const struct lu_env * env, struct dt_object * dt, struct fiemap * fm) [static]
Definition at line 1888 of file osd_io.c.
References fiemap_check_ranges(), FIEMAP_MAX_EXTENTS, LASSERT, osd_object::oo_inode, and osd_dt_obj().
void osd_fini_iobuf (struct osd_device * d, struct osd_iobuf * iobuf)
Definition at line 128 of file osd_io.c.
References BRW_R_DIO_FRAGS, BRW_R_IO_TIME, osd_iobuf::dr_dev, osd_iobuf::dr_elapsed, osd_iobuf::dr_elapsed_valid, osd_iobuf::dr_frags, osd_iobuf::dr_rw, brw_stats::hist, LASSERT, lprocfs_oh_tally(), lprocfs_oh_tally_log2(), and osd_device::od_brw_stats.
Referenced by osd_do_bio(), osd_trans_stop(), osd_write_commit(), and osd_write_prep().
static struct page* osd_get_page (struct dt_object * dt, loff_t offset, int rw) [static, read]
Definition at line 417 of file osd_io.c.
References LASSERT, lprocfs_counter_add(), osd_device::od_stats, osd_object::oo_inode, osd_dt_obj(), osd_obj2dev(), and unlikely.
Referenced by osd_bufs_get().
static void osd_iobuf_add_page (struct osd_iobuf * iobuf, struct page * page) [static]
Definition at line 122 of file osd_io.c.
References osd_iobuf::dr_max_pages, osd_iobuf::dr_npages, osd_iobuf::dr_pages, and LASSERT.
Referenced by osd_read_prep(), osd_write_commit(), and osd_write_prep().
static int osd_is_mapped (struct dt_object * dt, __u64 offset, struct osd_fextent * cached_extent) [static]
Definition at line 1048 of file osd_io.c.
References osd_fextent::end, end, osd_fextent::mapped, osd_object::oo_inode, osd_dt_obj(), osd_fextent::start, and start.
Referenced by osd_declare_write_commit(), and osd_write_commit().
static int osd_ladvise (const struct lu_env * env, struct dt_object * dt, __u64 start, __u64 end, enum lu_ladvise_type advice) [static]
Definition at line 1922 of file osd_io.c.
References ENTRY, and RETURN.
static int osd_ldiskfs_map_bm_inode_pages (struct inode * inode, struct page ** page, int pages, sector_t * blocks, int create) [static]
Definition at line 787 of file osd_io.c.
References CERROR.
Referenced by osd_ldiskfs_map_inode_pages().
static int osd_ldiskfs_map_ext_inode_pages (struct inode * inode, struct page ** page, int pages, sector_t * blocks, int create) [static]
Definition at line 815 of file osd_io.c.
References CDEBUG, cleanup(), D_OTHER, GOTO, and osd_ldiskfs_map_nblocks().
Referenced by osd_ldiskfs_map_inode_pages().
static int osd_ldiskfs_map_inode_pages (struct inode * inode, struct page ** page, int pages, sector_t * blocks, int create) [static]
Definition at line 862 of file osd_io.c.
References LDISKFS_EXTENTS_FL, osd_ldiskfs_map_bm_inode_pages(), and osd_ldiskfs_map_ext_inode_pages().
Referenced by osd_read_prep(), osd_write_commit(), and osd_write_prep().
static int osd_ldiskfs_map_nblocks (struct inode * inode, unsigned long index, int clen, sector_t * blocks, int create) [static]
Definition at line 762 of file osd_io.c.
References bpointers::blocks, CDEBUG, bpointers::create, D_OTHER, bpointers::init_num, ldiskfs_ext_new_extent_cb(), bpointers::num, and bpointers::start.
Referenced by osd_ldiskfs_map_ext_inode_pages().
int osd_ldiskfs_read (struct inode * inode, void * buf, int size, loff_t * offs)
Definition at line 1402 of file osd_io.c.
References blocksize(), CDEBUG, CERROR, and D_EXT2.
Referenced by osd_last_rcvd_subdir_count(), osd_read(), and osd_scrub_file_load().
static int osd_ldiskfs_readlink (struct inode * inode, char * buffer, int buflen) [static]
Definition at line 1393 of file osd_io.c.
Referenced by osd_read().
int osd_ldiskfs_write_record (struct inode * inode, void * buf, int bufsize, int write_NUL, loff_t * offs, handle_t * handle)
Definition at line 1640 of file osd_io.c.
References blocksize(), CERROR, LASSERTF, ll_dirty_inode, and size.
Referenced by osd_scrub_file_store(), and osd_write().
static int osd_ldiskfs_writelink (struct inode * inode, char * buffer, int buflen) [static]
Definition at line 1627 of file osd_io.c.
References ll_dirty_inode.
Referenced by osd_write().
static int osd_map_remote_to_local (loff_t offset, ssize_t len, int * nrpages, struct niobuf_local * lnb) [static]
Definition at line 385 of file osd_io.c.
References ENTRY, LASSERTF, niobuf_local::lnb_file_offset, niobuf_local::lnb_flags, niobuf_local::lnb_len, niobuf_local::lnb_page, niobuf_local::lnb_page_offset, niobuf_local::lnb_rc, and RETURN.
Referenced by osd_bufs_get().
static int osd_punch (const struct lu_env * env, struct dt_object * dt, __u64 start, __u64 end, struct thandle * th) [static]
Definition at line 1794 of file osd_io.c.
References credits, dt_object_exists(), ENTRY, LASSERT, ll_truncate_pagecache, ll_vfs_dq_init, OBD_OBJECT_EOF, osd_object::oo_inode, osd_dt_obj(), osd_invariant, OSD_OT_PUNCH, osd_trans_exec_op(), osd_thandle::ot_credits, osd_thandle::ot_handle, and RETURN.
static ssize_t osd_read (const struct lu_env * env, struct dt_object * dt, struct lu_buf * buf, loff_t * pos) [static]
Definition at line 1460 of file osd_io.c.
References dt_object::do_lu, lu_buf::lb_buf, lu_buf::lb_len, lu_object::lo_header, lu_object_header::loh_attr, osd_object::oo_inode, osd_dt_obj(), osd_ldiskfs_read(), and osd_ldiskfs_readlink().
static int osd_read_prep (const struct lu_env * env, struct dt_object * dt, struct niobuf_local * lnb, int npages) [static]
Definition at line 1307 of file osd_io.c.
References cfs_timeval_sub(), osd_iobuf::dr_blocks, osd_iobuf::dr_npages, osd_iobuf::dr_pages, LASSERT, niobuf_local::lnb_file_offset, niobuf_local::lnb_len, niobuf_local::lnb_page, niobuf_local::lnb_rc, lprocfs_counter_add(), osd_device::od_read_cache, osd_device::od_readcache_max_filesize, osd_device::od_stats, osd_object::oo_inode, osd_do_bio(), osd_dt_obj(), osd_init_iobuf, osd_iobuf_add_page(), osd_ldiskfs_map_inode_pages(), osd_obj2dev(), osd_oti_get(), osd_thread_info::oti_iobuf, RETURN, and unlikely.
static void osd_submit_bio (int rw, struct bio * bio) [static]
Definition at line 241 of file osd_io.c.
References LASSERTF, READ, and WRITE.
Referenced by osd_do_bio().
static ssize_t osd_write (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, loff_t * pos, struct thandle * handle, int ignore_quota) [static]
Definition at line 1722 of file osd_io.c.
References dt_object::do_lu, dt_object_exists(), LASSERT, lu_buf::lb_buf, lu_buf::lb_len, ll_vfs_dq_init, lu_object::lo_header, lu_object_header::loh_attr, osd_object::oo_inode, osd_dt_obj(), osd_ldiskfs_write_record(), osd_ldiskfs_writelink(), OSD_OT_WRITE, osd_trans_exec_check(), osd_trans_exec_op(), osd_thandle::ot_handle, and osd_thandle::ot_super.
static int osd_write_commit (const struct lu_env * env, struct dt_object * dt, struct niobuf_local * lnb, int npages, struct thandle * thandle) [static]
Definition at line 1208 of file osd_io.c.
References CDEBUG, D_INODE, osd_iobuf::dr_blocks, osd_iobuf::dr_npages, osd_iobuf::dr_pages, LASSERT, likely, ll_dirty_inode, ll_vfs_dq_init, niobuf_local::lnb_file_offset, niobuf_local::lnb_len, niobuf_local::lnb_page, niobuf_local::lnb_rc, OBD_FAIL_CHECK, OBD_FAIL_OST_MAPBLK_ENOSPC, osd_object::oo_inode, osd_do_bio(), osd_dt_obj(), osd_fini_iobuf(), osd_init_iobuf, osd_iobuf_add_page(), osd_is_mapped(), osd_ldiskfs_map_inode_pages(), osd_obj2dev(), OSD_OT_WRITE, osd_oti_get(), osd_trans_exec_check(), osd_trans_exec_op(), osd_thread_info::oti_iobuf, RETURN, thandle::th_local, and unlikely.
static int osd_write_prep (const struct lu_env * env, struct dt_object * dt, struct niobuf_local * lnb, int npages) [static]
Definition at line 962 of file osd_io.c.
References cfs_timeval_sub(), osd_iobuf::dr_blocks, osd_iobuf::dr_npages, osd_iobuf::dr_pages, LASSERT, likely, niobuf_local::lnb_len, niobuf_local::lnb_page, niobuf_local::lnb_page_offset, lprocfs_counter_add(), osd_device::od_readcache_max_filesize, osd_device::od_stats, osd_device::od_writethrough_cache, osd_object::oo_inode, osd_do_bio(), osd_dt_obj(), osd_fini_iobuf(), osd_init_iobuf, osd_iobuf_add_page(), osd_ldiskfs_map_inode_pages(), osd_obj2dev(), osd_oti_get(), osd_thread_info::oti_iobuf, RETURN, and unlikely.
static void record_start_io (struct osd_iobuf * iobuf, int size) [static]
Definition at line 218 of file osd_io.c.
References BRW_R_DISK_IOSIZE, BRW_R_RPC_HIST, BRW_W_DISK_IOSIZE, BRW_W_RPC_HIST, osd_iobuf::dr_dev, osd_iobuf::dr_frags, osd_iobuf::dr_numreqs, osd_iobuf::dr_rw, brw_stats::hist, LBUG, lprocfs_oh_tally(), lprocfs_oh_tally_log2(), osd_device::od_brw_stats, osd_device::od_r_in_flight, and osd_device::od_w_in_flight.
Referenced by osd_do_bio().
Variable Documentation
struct dt_body_operations osd_body_ops
Initial value:
 {
        .dbo_read                       = osd_read,
        .dbo_declare_write              = osd_declare_write,
        .dbo_write                      = osd_write,
        .dbo_bufs_get                   = osd_bufs_get,
        .dbo_bufs_put                   = osd_bufs_put,
        .dbo_write_prep                 = osd_write_prep,
        .dbo_declare_write_commit       = osd_declare_write_commit,
        .dbo_write_commit               = osd_write_commit,
        .dbo_read_prep                  = osd_read_prep,
        .dbo_declare_punch              = osd_declare_punch,
        .dbo_punch                      = osd_punch,
        .dbo_fiemap_get                 = osd_fiemap_get,
        .dbo_ladvise                    = osd_ladvise,
}
Definition at line 1945 of file osd_io.c.
struct dt_body_operations osd_body_ops_new
Initial value:
 {
        .dbo_declare_write = osd_declare_write,
}
Definition at line 1941 of file osd_io.c.
Referenced by osd_object_create(), osd_object_ea_create(), and osd_object_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.