Lustre: lustre/osd-zfs/osd_handler.c File Reference
lustre/osd-zfs/osd_handler.c File Reference
#include <lustre_ver.h>
#include <libcfs/libcfs.h>
#include <obd_support.h>
#include <lustre_net.h>
#include <obd.h>
#include <obd_class.h>
#include <lustre_disk.h>
#include <lustre_fid.h>
#include <lustre_param.h>
#include <md_object.h>
#include "osd_internal.h"
#include <sys/dnode.h>
#include <sys/dbuf.h>
#include <sys/spa.h>
#include <sys/stat.h>
#include <sys/zap.h>
#include <sys/spa_impl.h>
#include <sys/zfs_znode.h>
#include <sys/dmu_tx.h>
#include <sys/dmu_objset.h>
#include <sys/dsl_prop.h>
#include <sys/sa_impl.h>
#include <sys/txg.h>
Defines
#define DEBUG_SUBSYSTEM S_OSD
Functions
static void arc_prune_func (int64_t bytes, void *private)
static int osd_root_get (const struct lu_env *env, struct dt_device *dev, struct lu_fid *f)
static void osd_trans_commit_cb (void *cb_data, int error)
static int osd_trans_cb_add (struct thandle *th, struct dt_txn_commit_cb *dcb)
static int osd_trans_start (const struct lu_env *env, struct dt_device *d, struct thandle *th)
static int osd_unlinked_object_free (struct osd_device *osd, uint64_t oid)
static void osd_unlinked_list_emptify (struct osd_device *osd, struct list_head *list, bool free)
static void osd_trans_stop_cb (struct osd_thandle *oth, int result)
static int osd_trans_stop (const struct lu_env *env, struct dt_device *dt, struct thandle *th)
static struct thandle * osd_trans_create (const struct lu_env *env, struct dt_device *dt)
uint64_t osd_objs_count_estimate (uint64_t refdbytes, uint64_t usedobjs, uint64_t nrblocks, uint64_t est_maxblockshift)
static int osd_objset_statfs (struct osd_device *osd, struct obd_statfs *osfs)
int osd_statfs (const struct lu_env *env, struct dt_device *d, struct obd_statfs *osfs)
static int osd_blk_insert_cost (struct osd_device *osd)
static void osd_conf_get (const struct lu_env *env, const struct dt_device *dev, struct dt_device_param *param)
static int osd_sync (const struct lu_env *env, struct dt_device *d)
static int osd_commit_async (const struct lu_env *env, struct dt_device *dev)
static int osd_ro (const struct lu_env *env, struct dt_device *d)
static int osd_type_init (struct lu_device_type *t)
static void osd_type_fini (struct lu_device_type *t)
static void * osd_key_init (const struct lu_context *ctx, struct lu_context_key *key)
static void osd_key_fini (const struct lu_context *ctx, struct lu_context_key *key, void *data)
static void osd_key_exit (const struct lu_context *ctx, struct lu_context_key *key, void *data)
static void osd_fid_fini (const struct lu_env *env, struct osd_device *osd)
static int osd_shutdown (const struct lu_env *env, struct osd_device *o)
static void osd_xattr_changed_cb (void *arg, uint64_t newval)
static void osd_recordsize_changed_cb (void *arg, uint64_t newval)
static void osd_readonly_changed_cb (void *arg, uint64_t newval)
static void osd_objset_unregister_callbacks (struct osd_device *o)
static int osd_objset_register_callbacks (struct osd_device *o)
static int osd_objset_open (struct osd_device *o)
static void osd_unlinked_drain (const struct lu_env *env, struct osd_device *osd)
static int osd_mount (const struct lu_env *env, struct osd_device *o, struct lustre_cfg *cfg)
static void osd_umount (const struct lu_env *env, struct osd_device *o)
static int osd_device_init0 (const struct lu_env *env, struct osd_device *o, struct lustre_cfg *cfg)
static struct lu_device * osd_device_fini (const struct lu_env *env, struct lu_device *dev)
static struct lu_device * osd_device_alloc (const struct lu_env *env, struct lu_device_type *type, struct lustre_cfg *cfg)
static struct lu_device * osd_device_free (const struct lu_env *env, struct lu_device *d)
static int osd_device_init (const struct lu_env *env, struct lu_device *d, const char *name, struct lu_device *next)
static int osd_process_config (const struct lu_env *env, struct lu_device *d, struct lustre_cfg *cfg)
static int osd_recovery_complete (const struct lu_env *env, struct lu_device *d)
static int osd_obd_connect (const struct lu_env *env, struct obd_export **exp, struct obd_device *obd, struct obd_uuid *cluuid, struct obd_connect_data *data, void *localdata)
static int osd_obd_disconnect (struct obd_export *exp)
static int osd_fid_init (const struct lu_env *env, struct osd_device *osd)
static int osd_prepare (const struct lu_env *env, struct lu_device *pdev, struct lu_device *dev)
static void osd_type_start (struct lu_device_type *t)
static void osd_type_stop (struct lu_device_type *t)
int osd_fid_alloc (const struct lu_env *env, struct obd_export *exp, struct lu_fid *fid, struct md_op_data *op_data)
static int __init osd_init (void)
static void __exit osd_exit (void)
module_param (osd_oi_count, int, 0444)
MODULE_PARM_DESC (osd_oi_count,"Number of Object Index containers to be created, it's only valid for new filesystem.")
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Object Storage Device ("LUSTRE_OSD_ZFS_NAME")")
MODULE_VERSION (LUSTRE_VERSION_STRING)
MODULE_LICENSE ("GPL")
module_init (osd_init)
module_exit (osd_exit)
Variables
struct lu_context_key osd_key
struct kmem_cache * osd_object_kmem
struct kmem_cache * osd_zapit_cachep
static struct lu_kmem_descr osd_caches []
static struct dt_device_operations osd_dt_ops
struct lu_device_operations osd_lu_ops
static struct
lu_device_type_operations osd_device_type_ops
static struct lu_device_type osd_device_type
static struct obd_ops osd_obd_device_ops
unsigned int osd_oi_count
Define Documentation
#define DEBUG_SUBSYSTEM S_OSD
Definition at line 44 of file osd_handler.c.
Function Documentation
static void arc_prune_func (int64_t bytes, void * private) [static]
Definition at line 96 of file osd_handler.c.
References CERROR, LCT_SHRINKER, lu_env_fini(), lu_env_init(), lu_site_purge(), osd_device::od_site, and osd_device::od_svname.
Referenced by osd_objset_register_callbacks().
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Object Storage Device ("LUSTRE_OSD_ZFS_NAME")")
module_exit (osd_exit)
module_init (osd_init)
MODULE_LICENSE ("GPL")
module_param (osd_oi_count , int , 0444)
MODULE_PARM_DESC (osd_oi_count , "Number of Object Index containers to be created, it's only valid for new filesystem.")
MODULE_VERSION (LUSTRE_VERSION_STRING)
static int osd_blk_insert_cost (struct osd_device * osd) [static]
Definition at line 529 of file osd_handler.c.
References CLASSERT, osd_device::od_os, and osd_spa_maxblockshift.
Referenced by osd_conf_get().
static int osd_commit_async (const struct lu_env * env, struct dt_device * dev) [static]
Definition at line 605 of file osd_handler.c.
References osd_device::od_os, and osd_dt_dev().
static void osd_conf_get (const struct lu_env * env, const struct dt_device * dev, struct dt_device_param * param) [static]
Definition at line 553 of file osd_handler.c.
References dt_device_param::ddp_extent_tax, dt_device_param::ddp_inodespace, dt_device_param::ddp_max_ea_size, dt_device_param::ddp_max_extent_blks, dt_device_param::ddp_max_name_len, dt_device_param::ddp_max_nlink, dt_device_param::ddp_maxbytes, dt_device_param::ddp_mntopts, dt_device_param::ddp_mount_type, dt_device_param::ddp_symlink_max, LDD_MT_ZFS, MNTOPT_ACL, MNTOPT_USERXATTR, osd_device::od_posix_acl, osd_blk_insert_cost(), OSD_DNODE_EST_COUNT, and osd_dt_dev().
static struct lu_device* osd_device_alloc (const struct lu_env * env, struct lu_device_type * type, struct lustre_cfg * cfg) [static, read]
Definition at line 1088 of file osd_handler.c.
References dt_device_fini(), dt_device_init(), OBD_ALLOC_PTR, OBD_FREE_PTR, osd_device::od_dt_dev, osd2lu_dev(), osd_device_fini(), osd_device_init0(), osd_mount(), and unlikely.
static struct lu_device * osd_device_fini (const struct lu_env * env, struct lu_device * dev) [static, read]
Definition at line 1137 of file osd_handler.c.
References CERROR, ENTRY, lu2dt_dev(), osd_device::od_os, osd_dev(), osd_objset_unregister_callbacks(), osd_oi_fini(), osd_shutdown(), osd_sync(), osd_umount(), and RETURN.
Referenced by osd_device_alloc().
static struct lu_device* osd_device_free (const struct lu_env * env, struct lu_device * d) [static, read]
Definition at line 1117 of file osd_handler.c.
References cfs_hash_is_empty(), D_ERROR, dt_device_fini(), ENTRY, lu_device::ld_site, LIBCFS_DEBUG_MSG_DATA_DECL, lu_site::ls_obj_hash, lu_site::ls_top_dev, lu_cdebug_printer(), lu_site_fini(), lu_site_print(), lu_site_purge(), OBD_FREE_PTR, osd_device::od_dt_dev, osd_device::od_site, osd_dev(), and RETURN.
static int osd_device_init (const struct lu_env * env, struct lu_device * d, const char * name, struct lu_device * next) [static]
Definition at line 1166 of file osd_handler.c.
static int osd_device_init0 (const struct lu_env * env, struct osd_device * o, struct lustre_cfg * cfg) [static]
Definition at line 1066 of file osd_handler.c.
References dt_device::dd_ops, GOTO, lu_device::ld_ops, lu_env_refill(), osd_device::od_dt_dev, osd2lu_dev(), osd_lu_ops, and RETURN.
Referenced by osd_device_alloc().
static void __exit osd_exit (void) [static]
Definition at line 1391 of file osd_handler.c.
References class_unregister_type(), lu_kmem_fini(), and LUSTRE_OSD_ZFS_NAME.
int osd_fid_alloc (const struct lu_env * env, struct obd_export * exp, struct lu_fid * fid, struct md_op_data * op_data)
Definition at line 1335 of file osd_handler.c.
References obd_export::exp_obd, obd_device::obd_lu_dev, osd_device::od_cl_seq, osd_dev(), and seq_client_alloc_fid().
static void osd_fid_fini (const struct lu_env * env, struct osd_device * osd) [static]
Definition at line 701 of file osd_handler.c.
References OBD_FREE_PTR, osd_device::od_cl_seq, and seq_client_fini().
Referenced by osd_shutdown().
static int osd_fid_init (const struct lu_env * env, struct osd_device * osd) [static]
Definition at line 1274 of file osd_handler.c.
References ENTRY, LUSTRE_SEQ_METADATA, OBD_ALLOC_PTR, OBD_FREE_PTR, osd_device::od_cl_seq, osd_device::od_is_ost, osd_device::od_svname, osd_seq_site(), RETURN, seq_client_init(), seq_server_site::ss_server_seq, and unlikely.
Referenced by osd_prepare().
static int __init osd_init (void) [static]
Definition at line 1372 of file osd_handler.c.
References class_register_type(), lu_kmem_fini(), lu_kmem_init(), LUSTRE_OSD_ZFS_NAME, and osd_options_init().
static void osd_key_exit (const struct lu_context * ctx, struct lu_context_key * key, void * data) [static]
Definition at line 686 of file osd_handler.c.
static void osd_key_fini (const struct lu_context * ctx, struct lu_context_key * key, void * data) [static]
Definition at line 678 of file osd_handler.c.
References OBD_FREE_PTR.
static void* osd_key_init (const struct lu_context * ctx, struct lu_context_key * key) [static]
Definition at line 665 of file osd_handler.c.
References OBD_ALLOC_PTR, and osd_thread_info::oti_env.
static int osd_mount (const struct lu_env * env, struct osd_device * o, struct lustre_cfg * cfg) [static]
Definition at line 947 of file osd_handler.c.
References __osd_obj2dbuf(), ENTRY, GOTO, lu_site::ls_bottom_dev, lu_site_init(), lu_site_init_finish(), lustre_cfg_string(), osd_device::od_dt_dev, osd_device::od_is_ost, osd_device::od_max_blksz, osd_device::od_mntdev, osd_device::od_os, osd_device::od_posix_acl, osd_device::od_proc_entry, osd_device::od_quota_iused_est, osd_device::od_quota_slave, osd_device::od_root, osd_device::od_rootid, osd_device::od_site, osd_device::od_svname, osd_device::od_xattr_in_sa, osd2lu_dev(), osd_obj_tag, osd_objset_open(), osd_objset_register_callbacks(), osd_oi_init(), osd_unlinked_drain(), qsd_init(), RETURN, server_name_is_ost(), SPA_OLD_MAXBLOCKSIZE, and strlcpy().
Referenced by osd_device_alloc(), and osd_process_config().
static int osd_obd_connect (const struct lu_env * env, struct obd_export ** exp, struct obd_device * obd, struct obd_uuid * cluuid, struct obd_connect_data * data, void * localdata) [static]
Definition at line 1225 of file osd_handler.c.
References CDEBUG, class_conn2export(), class_connect(), D_CONFIG, ENTRY, obd_device::obd_dev_lock, obd_device::obd_lu_dev, osd_device::od_connects, osd_dev(), and RETURN.
static int osd_obd_disconnect (struct obd_export * exp) [static]
Definition at line 1253 of file osd_handler.c.
References class_disconnect(), class_manual_cleanup(), ENTRY, obd_export::exp_obd, obd_device::obd_dev_lock, obd_device::obd_lu_dev, osd_device::od_connects, osd_dev(), and RETURN.
uint64_t osd_objs_count_estimate (uint64_t refdbytes, uint64_t usedobjs, uint64_t nrblocks, uint64_t est_maxblockshift)
Definition at line 368 of file osd_handler.c.
References CLASSERT, OSD_DNODE_EST_BLKSHIFT, OSD_DNODE_EST_COUNT, and OSD_DNODE_MIN_BLKSHIFT.
Referenced by osd_objset_statfs(), and osd_objset_user_iused().
static int osd_objset_open (struct osd_device * o) [static]
Definition at line 811 of file osd_handler.c.
References CERROR, ENTRY, GOTO, osd_device::od_mntdev, osd_device::od_os, osd_device::od_rootid, osd_device::od_svname, osd_device::od_unlinkedid, RETURN, version, and osd_device::z_attr_table.
Referenced by osd_mount().
static int osd_objset_register_callbacks (struct osd_device * o) [static]
Definition at line 777 of file osd_handler.c.
References osd_device::arc_prune_cb, arc_prune_func(), dsl_pool_config_enter(), dsl_pool_config_exit(), GOTO, LASSERT, osd_device::od_os, osd_objset_unregister_callbacks(), osd_readonly_changed_cb(), osd_recordsize_changed_cb(), osd_xattr_changed_cb(), and RETURN.
Referenced by osd_mount().
static int osd_objset_statfs (struct osd_device * osd, struct obd_statfs * osfs) [static]
Definition at line 433 of file osd_handler.c.
References CLASSERT, likely, OBD_OBJECT_EOF, osd_device::od_dev_set_rdonly, osd_device::od_max_blksz, osd_device::od_os, osd_device::od_prop_rdonly, obd_statfs::os_bavail, obd_statfs::os_bfree, obd_statfs::os_blocks, obd_statfs::os_bsize, obd_statfs::os_ffree, obd_statfs::os_files, obd_statfs::os_maxbytes, obd_statfs::os_namelen, obd_statfs::os_state, OS_STATE_READONLY, obd_statfs::os_type, osd_objs_count_estimate(), OSD_STATFS_RESERVED_SHIFT, and OSD_STATFS_RESERVED_SIZE.
Referenced by osd_statfs().
static void osd_objset_unregister_callbacks (struct osd_device * o) [static]
Definition at line 756 of file osd_handler.c.
References osd_device::arc_prune_cb, osd_device::od_os, osd_readonly_changed_cb(), osd_recordsize_changed_cb(), and osd_xattr_changed_cb().
Referenced by osd_device_fini(), and osd_objset_register_callbacks().
static int osd_prepare (const struct lu_env * env, struct lu_device * pdev, struct lu_device * dev) [static]
Definition at line 1301 of file osd_handler.c.
References ENTRY, osd_device::od_quota_slave, osd_dev(), osd_fid_init(), qsd_prepare(), and RETURN.
static int osd_process_config (const struct lu_env * env, struct lu_device * d, struct lustre_cfg * cfg) [static]
Definition at line 1176 of file osd_handler.c.
References class_process_proc_param(), ENTRY, LASSERT, LCFG_CLEANUP, lustre_cfg::lcfg_command, LCFG_PARAM, LCFG_SETUP, osd_device::od_dt_dev, osd_dev(), osd_mount(), osd_shutdown(), PARAM_OSD, PARAM_OST, and RETURN.
static void osd_readonly_changed_cb (void * arg, uint64_t newval) [static]
Definition at line 744 of file osd_handler.c.
References osd_device::od_prop_rdonly.
Referenced by osd_objset_register_callbacks(), and osd_objset_unregister_callbacks().
static void osd_recordsize_changed_cb (void * arg, uint64_t newval) [static]
Definition at line 733 of file osd_handler.c.
References LASSERT, osd_device::od_max_blksz, osd_device::od_os, and osd_spa_maxblocksize.
Referenced by osd_objset_register_callbacks(), and osd_objset_unregister_callbacks().
static int osd_recovery_complete (const struct lu_env * env, struct lu_device * d) [static]
Definition at line 1207 of file osd_handler.c.
References ENTRY, osd_device::od_quota_slave, osd_dev(), qsd_start(), and RETURN.
static int osd_ro (const struct lu_env * env, struct dt_device * d) [static]
Definition at line 625 of file osd_handler.c.
References CERROR, ENTRY, LUSTRE_OSD_ZFS_NAME, osd_device::od_dev_set_rdonly, osd_device::od_os, osd_device::od_svname, osd_dt_dev(), and RETURN.
static int osd_root_get (const struct lu_env * env, struct dt_device * dev, struct lu_fid * f) [static]
Definition at line 118 of file osd_handler.c.
References lu_local_obj_fid(), and OSD_FS_ROOT_OID.
static int osd_shutdown (const struct lu_env * env, struct osd_device * o) [static]
Definition at line 711 of file osd_handler.c.
References ENTRY, osd_device::od_quota_slave, osd_fid_fini(), qsd_fini(), and RETURN.
Referenced by osd_device_fini(), and osd_process_config().
int osd_statfs (const struct lu_env * env, struct dt_device * d, struct obd_statfs * osfs)
Definition at line 513 of file osd_handler.c.
References __u64, CLASSERT, ENTRY, likely, min_t, OBD_ALLOC_PTR, OBD_FREE_PTR, osd_device::od_mnt, obd_statfs::os_bavail, obd_statfs::os_bfree, obd_statfs::os_blocks, obd_statfs::os_bsize, obd_statfs::os_maxbytes, obd_statfs::os_state, OS_STATE_READONLY, osd_dt_dev(), OSD_GRANT_FOR_LOCAL_OIDS, osd_objset_statfs(), osd_oti_get(), osd_sb(), OSD_STATFS_RESERVED, OSD_STATFS_RESERVED_SHIFT, osd_thread_info::oti_ksfs, RETURN, statfs_pack(), and unlikely.
static int osd_sync (const struct lu_env * env, struct dt_device * d) [static]
Definition at line 596 of file osd_handler.c.
References CDEBUG, D_CACHE, LUSTRE_OSD_ZFS_NAME, osd_device::od_os, and osd_dt_dev().
Referenced by osd_device_fini().
static int osd_trans_cb_add (struct thandle * th, struct dt_txn_commit_cb * dcb) [static]
Definition at line 174 of file osd_handler.c.
References dt_txn_commit_cb::dcb_flags, dt_txn_commit_cb::dcb_func, dt_txn_commit_cb::dcb_linkage, dt_txn_commit_cb::dcb_magic, DCB_TRANS_STOP, LASSERT, list_add(), osd_thandle::ot_dcb_list, osd_thandle::ot_stop_dcb_list, osd_thandle::ot_super, and TRANS_COMMIT_CB_MAGIC.
static void osd_trans_commit_cb (void * cb_data, int error) [static]
Definition at line 132 of file osd_handler.c.
References CERROR, CWARN, dt_txn_commit_cb::dcb_func, dt_txn_commit_cb::dcb_linkage, dt_device::dd_lu_dev, dt_txn_hook_commit(), ENTRY, EXIT, list_for_each_entry_safe, lu_context_exit(), lu_context_fini(), lu_device_put(), OBD_FREE_PTR, osd_device::od_quota_slave, osd_device::od_svname, osd_dt_dev(), osd_thandle::ot_dcb_list, osd_thandle::ot_quota_trans, osd_thandle::ot_super, qsd_op_end(), thandle::th_ctx, and thandle::th_dev.
Referenced by osd_trans_start().
static struct thandle* osd_trans_create (const struct lu_env * env, struct dt_device * dt) [static, read]
Definition at line 333 of file osd_handler.c.
References ENTRY, INIT_LIST_HEAD, LCT_TX_HANDLE, OBD_ALLOC_PTR, osd_device::od_os, osd_dt_dev(), osd_thandle::ot_dcb_list, osd_thandle::ot_quota_trans, osd_thandle::ot_sa_list, osd_thandle::ot_sa_lock, osd_thandle::ot_stop_dcb_list, osd_thandle::ot_super, osd_thandle::ot_tx, osd_thandle::ot_unlinked_list, RETURN, thandle::th_dev, thandle::th_result, and thandle::th_tags.
static int osd_trans_start (const struct lu_env * env, struct dt_device * d, struct thandle * th) [static]
Definition at line 192 of file osd_handler.c.
References CERROR, dt_device::dd_lu_dev, dt_txn_hook_start(), ENTRY, LASSERT, lu_context_enter(), lu_context_init(), lu_device_get(), lu_device_is_md(), OBD_FAIL_CHECK, OBD_FAIL_OST_MAPBLK_ENOSPC, osd_device::od_svname, osd_dt_dev(), osd_trans_commit_cb(), osd_thandle::ot_assigned, osd_thandle::ot_super, osd_thandle::ot_tx, osd_thandle::ot_write_commit, RETURN, thandle::th_ctx, thandle::th_tags, and unlikely.
static int osd_trans_stop (const struct lu_env * env, struct dt_device * dt, struct thandle * th) [static]
Definition at line 273 of file osd_handler.c.
References CDEBUG, D_OTHER, dt_txn_hook_stop(), ENTRY, INIT_LIST_HEAD, LASSERT, list_splice_init(), lquota_id_info::lqi_is_blk, lquota_trans::lqt_id_cnt, lquota_trans::lqt_ids, OBD_FREE_PTR, osd_device::od_os, osd_device::od_quota_iused_est, osd_device::od_quota_slave, osd_device::od_svname, osd_dt_dev(), osd_object_sa_dirty_rele(), osd_trans_stop_cb(), osd_unlinked_list_emptify(), osd_thandle::ot_assigned, osd_thandle::ot_quota_trans, osd_thandle::ot_tx, osd_thandle::ot_unlinked_list, qsd_op_end(), RETURN, thandle::th_dev, and thandle::th_sync.
static void osd_trans_stop_cb (struct osd_thandle * oth, int result) [static]
Definition at line 254 of file osd_handler.c.
References dt_txn_commit_cb::dcb_func, dt_txn_commit_cb::dcb_linkage, dt_txn_commit_cb::dcb_magic, dt_txn_commit_cb::dcb_name, LASSERTF, list_del_init(), list_for_each_entry_safe, osd_thandle::ot_stop_dcb_list, osd_thandle::ot_super, and TRANS_COMMIT_CB_MAGIC.
Referenced by osd_trans_stop().
static void osd_type_fini (struct lu_device_type * t) [static]
Definition at line 660 of file osd_handler.c.
References lu_context_key_degister(), and osd_key.
static int osd_type_init (struct lu_device_type * t) [static]
Definition at line 654 of file osd_handler.c.
References LU_CONTEXT_KEY_INIT, lu_context_key_register(), and osd_key.
static void osd_type_start (struct lu_device_type * t) [static]
Definition at line 1327 of file osd_handler.c.
static void osd_type_stop (struct lu_device_type * t) [static]
Definition at line 1331 of file osd_handler.c.
static void osd_umount (const struct lu_env * env, struct osd_device * o) [static]
Definition at line 1039 of file osd_handler.c.
References CERROR, ENTRY, EXIT, osd_device::od_os, osd_device::od_svname, osd_device::od_zerocopy_alloc, osd_device::od_zerocopy_loan, and osd_device::od_zerocopy_pin.
Referenced by osd_device_fini().
static void osd_unlinked_drain (const struct lu_env * env, struct osd_device * osd) [static]
Definition at line 928 of file osd_handler.c.
References osd_device::od_os, osd_device::od_unlinkedid, osd_oti_get(), osd_unlinked_object_free(), and osd_thread_info::oti_za.
Referenced by osd_mount().
static void osd_unlinked_list_emptify (struct osd_device * osd, struct list_head * list, bool free) [static]
Definition at line 236 of file osd_handler.c.
References LASSERT, list_del_init(), list_empty(), list_entry, list_head::next, osd_object::oo_db, osd_object::oo_unlinked_linkage, and osd_unlinked_object_free().
Referenced by osd_trans_stop().
static int osd_unlinked_object_free (struct osd_device * osd, uint64_t oid) [static]
Definition at line 881 of file osd_handler.c.
References CWARN, LASSERT, LPU64, osd_device::od_os, osd_device::od_svname, and osd_device::od_unlinkedid.
Referenced by osd_unlinked_drain(), and osd_unlinked_list_emptify().
static void osd_xattr_changed_cb (void * arg, uint64_t newval) [static]
Definition at line 726 of file osd_handler.c.
References osd_device::od_xattr_in_sa.
Referenced by osd_objset_register_callbacks(), and osd_objset_unregister_callbacks().
Variable Documentation
struct lu_kmem_descr osd_caches[] [static]
Initial value:
 {
        {
                .ckd_cache = &osd_object_kmem,
                .ckd_name  = "zfs_osd_obj",
                .ckd_size  = sizeof(struct osd_object)
        },
        {
                .ckd_cache = &osd_zapit_cachep,
                .ckd_name  = "osd_zapit_cache",
                .ckd_size  = sizeof(struct osd_zap_it)
        },
        {
                .ckd_cache = NULL
        }
}
Definition at line 80 of file osd_handler.c.
struct lu_device_type osd_device_type [static]
Initial value:
 {
        .ldt_tags     = LU_DEVICE_DT,
        .ldt_name     = LUSTRE_OSD_ZFS_NAME,
        .ldt_ops      = &osd_device_type_ops,
        .ldt_ctx_tags = LCT_LOCAL
}
Definition at line 1357 of file osd_handler.c.
struct lu_device_type_operations osd_device_type_ops [static]
Initial value:
 {
        .ldto_init              = osd_type_init,
        .ldto_fini              = osd_type_fini,
        .ldto_start             = osd_type_start,
        .ldto_stop              = osd_type_stop,
        .ldto_device_alloc      = osd_device_alloc,
        .ldto_device_free       = osd_device_free,
        .ldto_device_init       = osd_device_init,
        .ldto_device_fini       = osd_device_fini
}
Definition at line 1343 of file osd_handler.c.
struct dt_device_operations osd_dt_ops [static]
Initial value:
 {
        .dt_root_get            = osd_root_get,
        .dt_statfs              = osd_statfs,
        .dt_trans_create        = osd_trans_create,
        .dt_trans_start         = osd_trans_start,
        .dt_trans_stop          = osd_trans_stop,
        .dt_trans_cb_add        = osd_trans_cb_add,
        .dt_conf_get            = osd_conf_get,
        .dt_sync                = osd_sync,
        .dt_commit_async        = osd_commit_async,
        .dt_ro                  = osd_ro,
}
Definition at line 638 of file osd_handler.c.
struct lu_context_key osd_key [read]
Initial value:
 {
        .lct_tags = LCT_DT_THREAD | LCT_MD_THREAD | LCT_MG_THREAD | LCT_LOCAL,
        .lct_init = osd_key_init,
        .lct_fini = osd_key_fini,
        .lct_exit = osd_key_exit
}
Definition at line 72 of file osd_handler.c.
struct lu_device_operations osd_lu_ops
Initial value:
 {
        .ldo_object_alloc       = osd_object_alloc,
        .ldo_process_config     = osd_process_config,
        .ldo_recovery_complete  = osd_recovery_complete,
        .ldo_prepare            = osd_prepare,
}
Definition at line 1320 of file osd_handler.c.
struct obd_ops osd_obd_device_ops [static]
Initial value:
 {
        .o_owner       = THIS_MODULE,
        .o_connect      = osd_obd_connect,
        .o_disconnect   = osd_obd_disconnect,
        .o_fid_alloc    = osd_fid_alloc
}
Definition at line 1365 of file osd_handler.c.
struct kmem_cache* osd_object_kmem
Definition at line 75 of file osd_handler.c.
Referenced by osd_object_alloc(), and osd_object_free().
unsigned int osd_oi_count
Definition at line 72 of file osd_oi.c.
struct kmem_cache* osd_zapit_cachep
Definition at line 78 of file osd_handler.c.
Referenced by osd_index_it_fini(), and osd_index_it_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.