Lustre: lustre/osd-zfs/osd_io.c File Reference
lustre/osd-zfs/osd_io.c File Reference
#include <lustre_ver.h>
#include <libcfs/libcfs.h>
#include <obd_support.h>
#include <lustre_net.h>
#include <obd.h>
#include <obd_class.h>
#include <lustre_disk.h>
#include <lustre_fid.h>
#include <lustre/lustre_idl.h>
#include "osd_internal.h"
#include <sys/dnode.h>
#include <sys/dbuf.h>
#include <sys/spa.h>
#include <sys/stat.h>
#include <sys/zap.h>
#include <sys/spa_impl.h>
#include <sys/zfs_znode.h>
#include <sys/dmu_tx.h>
#include <sys/dmu_objset.h>
#include <sys/dsl_prop.h>
#include <sys/sa_impl.h>
#include <sys/txg.h>
Defines
#define DEBUG_SUBSYSTEM S_OSD
Functions
static void record_start_io (struct osd_device *osd, int rw, int discont_pages)
static void record_end_io (struct osd_device *osd, int rw, unsigned long elapsed, int disksize, int npages)
static ssize_t osd_read (const struct lu_env *env, struct dt_object *dt, struct lu_buf *buf, loff_t *pos)
static ssize_t osd_declare_write (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, loff_t pos, struct thandle *th)
static ssize_t osd_write (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, loff_t *pos, struct thandle *th, int ignore_quota)
static int osd_bufs_put (const struct lu_env *env, struct dt_object *dt, struct niobuf_local *lnb, int npages)
static struct page * kmem_to_page (void *addr)
static int osd_bufs_get_read (const struct lu_env *env, struct osd_object *obj, loff_t off, ssize_t len, struct niobuf_local *lnb)
Prepare buffers for read.
static int osd_bufs_get_write (const struct lu_env *env, struct osd_object *obj, loff_t off, ssize_t len, struct niobuf_local *lnb)
static int osd_bufs_get (const struct lu_env *env, struct dt_object *dt, loff_t offset, ssize_t len, struct niobuf_local *lnb, int rw)
static int osd_write_prep (const struct lu_env *env, struct dt_object *dt, struct niobuf_local *lnb, int npages)
static uint32_t osd_get_blocksz (struct osd_object *obj)
static uint64_t osd_roundup2blocksz (uint64_t size, uint64_t offset, uint32_t blksz)
static int osd_declare_write_commit (const struct lu_env *env, struct dt_object *dt, struct niobuf_local *lnb, int npages, struct thandle *th)
static int osd_write_commit (const struct lu_env *env, struct dt_object *dt, struct niobuf_local *lnb, int npages, struct thandle *th)
static int osd_read_prep (const struct lu_env *env, struct dt_object *dt, struct niobuf_local *lnb, int npages)
static int __osd_object_punch (objset_t *os, dmu_buf_t *db, dmu_tx_t *tx, uint64_t size, uint64_t off, uint64_t len)
static int osd_punch (const struct lu_env *env, struct dt_object *dt, __u64 start, __u64 end, struct thandle *th)
static int osd_declare_punch (const struct lu_env *env, struct dt_object *dt, __u64 start, __u64 end, struct thandle *handle)
static int osd_ladvise (const struct lu_env *env, struct dt_object *dt, __u64 start, __u64 end, enum lu_ladvise_type advice)
Variables
static char * osd_zerocopy_tag = "zerocopy"
struct dt_body_operations osd_body_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_OSD
Definition at line 42 of file osd_io.c.
Function Documentation
static int __osd_object_punch (objset_t * os, dmu_buf_t * db, dmu_tx_t * tx, uint64_t size, uint64_t off, uint64_t len) [static]
Definition at line 819 of file osd_io.c.
References LASSERT.
Referenced by osd_punch().
static struct page* kmem_to_page (void * addr) [static, read]
Definition at line 295 of file osd_io.c.
Referenced by osd_bufs_get_read(), and osd_bufs_get_write().
static int osd_bufs_get (const struct lu_env * env, struct dt_object * dt, loff_t offset, ssize_t len, struct niobuf_local * lnb, int rw) [static]
Definition at line 511 of file osd_io.c.
References dt_object_exists(), LASSERT, osd_object::oo_db, osd_bufs_get_read(), osd_bufs_get_write(), and osd_dt_obj().
static int osd_bufs_get_read (const struct lu_env * env, struct osd_object * obj, loff_t off, ssize_t len, struct niobuf_local * lnb) [static]
Prepare buffers for read.
The function maps the range described by off and len to lnb array. dmu_buf_hold_array_by_bonus() finds/creates appropriate ARC buffers, then we fill lnb array with the pages storing ARC buffers. Notice the current implementationt passes TRUE to dmu_buf_hold_array_by_bonus() to fill ARC buffers with actual data, I/O is done in the conext of osd_bufs_get_read(). A better implementation would just return the buffers (potentially unfilled) and subsequent osd_read_prep() would do I/O for many ranges concurrently.
Parameters:
[in] env environment
[in] obj object
[in] off offset in bytes
[in] len the number of bytes to access
[out] lnb array of local niobufs pointing to the buffers with data
Return values:
0 for success
negative error number of failure
Definition at line 323 of file osd_io.c.
References cfs_time_current(), ENTRY, GOTO, kmem_to_page(), LASSERT, niobuf_local::lnb_data, niobuf_local::lnb_file_offset, niobuf_local::lnb_len, niobuf_local::lnb_page, niobuf_local::lnb_page_offset, niobuf_local::lnb_rc, min_t, osd_device::od_zerocopy_pin, osd_object::oo_db, osd_object::oo_dt, osd_bufs_put(), osd_obj2dev(), osd_zerocopy_tag, READ, record_end_io(), record_start_io(), RETURN, start, and unlikely.
Referenced by osd_bufs_get().
static int osd_bufs_get_write (const struct lu_env * env, struct osd_object * obj, loff_t off, ssize_t len, struct niobuf_local * lnb) [static]
Definition at line 407 of file osd_io.c.
References ENTRY, GOTO, kmem_to_page(), lu_attr::la_size, LASSERT, niobuf_local::lnb_data, niobuf_local::lnb_file_offset, niobuf_local::lnb_len, niobuf_local::lnb_page, niobuf_local::lnb_page_offset, niobuf_local::lnb_rc, lprocfs_counter_add(), min_t, osd_device::od_stats, osd_device::od_zerocopy_alloc, osd_device::od_zerocopy_loan, osd_object::oo_attr, osd_object::oo_db, osd_object::oo_dt, osd_bufs_put(), OSD_GFP_IO, osd_obj2dev(), PTLRPC_MAX_BRW_PAGES, RETURN, and unlikely.
Referenced by osd_bufs_get().
static int osd_bufs_put (const struct lu_env * env, struct dt_object * dt, struct niobuf_local * lnb, int npages) [static]
Definition at line 257 of file osd_io.c.
References dt_object_exists(), LASSERT, niobuf_local::lnb_data, niobuf_local::lnb_page, osd_device::od_zerocopy_alloc, osd_device::od_zerocopy_loan, osd_device::od_zerocopy_pin, osd_object::oo_db, osd_dt_obj(), osd_obj2dev(), and osd_zerocopy_tag.
Referenced by osd_bufs_get_read(), and osd_bufs_get_write().
static int osd_declare_punch (const struct lu_env * env, struct dt_object * dt, __u64 start, __u64 end, struct thandle * handle) [static]
Definition at line 876 of file osd_io.c.
References __u64, ENTRY, lu_attr::la_gid, lu_attr::la_size, lu_attr::la_uid, OBD_OBJECT_EOF, osd_object::oo_attr, osd_object::oo_attr_lock, osd_object::oo_db, osd_object::oo_sa_hdl, osd_declare_quota(), osd_dt_obj(), osd_obj2dev(), osd_thandle::ot_super, osd_thandle::ot_tx, and RETURN.
static ssize_t osd_declare_write (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, loff_t pos, struct thandle * th) [static]
Definition at line 154 of file osd_io.c.
References dt_object_exists(), ENTRY, lu_attr::la_gid, lu_attr::la_size, lu_attr::la_uid, LASSERT, lu_buf::lb_len, LLOG_MIN_CHUNK_SIZE, osd_object::oo_attr, osd_object::oo_db, osd_object::oo_sa_hdl, osd_declare_quota(), osd_dt_obj(), osd_obj2dev(), osd_thandle::ot_super, osd_thandle::ot_tx, and RETURN.
static int osd_declare_write_commit (const struct lu_env * env, struct dt_object * dt, struct niobuf_local * lnb, int npages, struct thandle * th) [static]
Definition at line 567 of file osd_io.c.
References CDEBUG, D_QUOTA, dt_object_exists(), dt_sync(), ENTRY, lu_attr::la_gid, lu_attr::la_uid, LASSERT, niobuf_local::lnb_file_offset, niobuf_local::lnb_flags, niobuf_local::lnb_len, niobuf_local::lnb_page, LPD64, OBD_BRW_FROM_GRANT, OBD_BRW_NOQUOTA, OBD_BRW_OVER_GRPQUOTA, OBD_BRW_OVER_USRQUOTA, OBD_BRW_SYNC, osd_device::od_os, osd_object::oo_attr, osd_object::oo_db, osd_object::oo_sa_hdl, osd_declare_quota(), osd_dt_obj(), osd_get_blocksz(), osd_obj2dev(), osd_roundup2blocksz(), osd_thandle::ot_tx, osd_thandle::ot_write_commit, QUOTA_FL_OVER_GRPQUOTA, QUOTA_FL_OVER_USRQUOTA, QUOTA_FL_SYNC, record_start_io(), RETURN, size, thandle::th_dev, toqb, and WRITE.
static uint32_t osd_get_blocksz (struct osd_object * obj) [inline, static]
Definition at line 540 of file osd_io.c.
References LASSERT, and osd_object::oo_db.
Referenced by osd_declare_write_commit().
static int osd_ladvise (const struct lu_env * env, struct dt_object * dt, __u64 start, __u64 end, enum lu_ladvise_type advice) [static]
Definition at line 909 of file osd_io.c.
References ENTRY, and RETURN.
static int osd_punch (const struct lu_env * env, struct dt_object * dt, __u64 start, __u64 end, struct thandle * th) [static]
Definition at line 839 of file osd_io.c.
References __osd_object_punch(), __u64, dt_object_exists(), ENTRY, lu_attr::la_size, LASSERT, OBD_OBJECT_EOF, osd_device::od_os, osd_object::oo_attr, osd_object::oo_attr_lock, osd_object::oo_db, osd_dt_obj(), osd_invariant, osd_obj2dev(), osd_object_sa_update(), osd_thandle::ot_super, osd_thandle::ot_tx, and RETURN.
static ssize_t osd_read (const struct lu_env * env, struct dt_object * dt, struct lu_buf * buf, loff_t * pos) [static]
Definition at line 114 of file osd_io.c.
References cfs_time_current(), dt_object_exists(), lu_attr::la_size, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, osd_device::od_os, osd_object::oo_attr, osd_object::oo_attr_lock, osd_object::oo_db, osd_dt_obj(), osd_obj2dev(), READ, record_end_io(), record_start_io(), size, and start.
static int osd_read_prep (const struct lu_env * env, struct dt_object * dt, struct niobuf_local * lnb, int npages) [static]
Definition at line 769 of file osd_io.c.
References dt_object_exists(), lu_attr::la_size, LASSERT, niobuf_local::lnb_file_offset, niobuf_local::lnb_len, niobuf_local::lnb_rc, osd_object::oo_attr, osd_object::oo_attr_lock, osd_object::oo_db, osd_dt_obj(), and unlikely.
static uint64_t osd_roundup2blocksz (uint64_t size, uint64_t offset, uint32_t blksz) [inline, static]
Definition at line 551 of file osd_io.c.
References LASSERT, and likely.
Referenced by osd_declare_write_commit().
static ssize_t osd_write (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, loff_t * pos, struct thandle * th, int ignore_quota) [static]
Definition at line 200 of file osd_io.c.
References dt_object_exists(), ENTRY, GOTO, lu_attr::la_size, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, osd_device::od_os, osd_object::oo_attr, osd_object::oo_attr_lock, osd_object::oo_db, osd_dt_obj(), osd_obj2dev(), osd_object_sa_update(), osd_thandle::ot_super, osd_thandle::ot_tx, record_end_io(), record_start_io(), RETURN, unlikely, and WRITE.
static int osd_write_commit (const struct lu_env * env, struct dt_object * dt, struct niobuf_local * lnb, int npages, struct thandle * th) [static]
Definition at line 685 of file osd_io.c.
References CDEBUG, D_INODE, DFID, dt_object::do_lu, dt_object_exists(), ENTRY, lu_attr::la_size, LASSERT, niobuf_local::lnb_data, niobuf_local::lnb_file_offset, niobuf_local::lnb_len, niobuf_local::lnb_rc, lu_object_fid(), osd_device::od_os, osd_device::od_zerocopy_loan, osd_object::oo_attr, osd_object::oo_attr_lock, osd_object::oo_db, osd_dt_obj(), osd_obj2dev(), osd_object_sa_update(), osd_thandle::ot_super, osd_thandle::ot_tx, PFID, record_end_io(), RETURN, thandle::th_local, unlikely, and WRITE.
static int osd_write_prep (const struct lu_env * env, struct dt_object * dt, struct niobuf_local * lnb, int npages) [static]
Definition at line 529 of file osd_io.c.
References dt_object_exists(), LASSERT, osd_object::oo_db, and osd_dt_obj().
static void record_end_io (struct osd_device * osd, int rw, unsigned long elapsed, int disksize, int npages) [static]
Definition at line 91 of file osd_io.c.
References BRW_R_DISK_IOSIZE, BRW_R_IO_TIME, BRW_R_PAGES, BRW_W_DISK_IOSIZE, BRW_W_IO_TIME, BRW_W_PAGES, brw_stats::hist, lprocfs_oh_tally_log2(), osd_device::od_brw_stats, osd_device::od_r_in_flight, osd_device::od_w_in_flight, and READ.
Referenced by osd_bufs_get_read(), osd_read(), osd_write(), and osd_write_commit().
static void record_start_io (struct osd_device * osd, int rw, int discont_pages) [static]
Definition at line 72 of file osd_io.c.
References BRW_R_DISCONT_PAGES, BRW_R_RPC_HIST, BRW_W_DISCONT_PAGES, BRW_W_RPC_HIST, brw_stats::hist, lprocfs_oh_tally(), osd_device::od_brw_stats, osd_device::od_r_in_flight, osd_device::od_w_in_flight, and READ.
Referenced by osd_bufs_get_read(), osd_declare_write_commit(), osd_read(), and osd_write().
Variable Documentation
struct dt_body_operations osd_body_ops
Initial value:
 {
        .dbo_read                       = osd_read,
        .dbo_declare_write              = osd_declare_write,
        .dbo_write                      = osd_write,
        .dbo_bufs_get                   = osd_bufs_get,
        .dbo_bufs_put                   = osd_bufs_put,
        .dbo_write_prep                 = osd_write_prep,
        .dbo_declare_write_commit       = osd_declare_write_commit,
        .dbo_write_commit               = osd_write_commit,
        .dbo_read_prep                  = osd_read_prep,
        .dbo_declare_punch              = osd_declare_punch,
        .dbo_punch                      = osd_punch,
        .dbo_ladvise                    = osd_ladvise,
}
Definition at line 924 of file osd_io.c.
Referenced by osd_declare_object_create(), osd_object_create(), osd_object_ea_create(), and osd_object_init0().
char* osd_zerocopy_tag = "zerocopy" [static]
Definition at line 69 of file osd_io.c.
Referenced by osd_bufs_get_read(), and osd_bufs_put().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.