Lustre: lustre/osd-zfs/osd_quota.c File Reference
lustre/osd-zfs/osd_quota.c File Reference
#include <lustre_quota.h>
#include <obd.h>
#include "osd_internal.h"
Functions
uint64_t osd_quota_fid2dmu (const struct lu_fid *fid)
Helper function to retrieve DMU object id from fid for accounting object.
static uint64_t osd_objset_user_iused (struct osd_device *osd, uint64_t uidbytes)
Helper function to estimate the number of inodes in use for a give uid/gid from the block usage.
static int osd_acct_index_lookup (const struct lu_env *env, struct dt_object *dtobj, struct dt_rec *dtrec, const struct dt_key *dtkey)
Space Accounting Management.
static struct dt_it * osd_it_acct_init (const struct lu_env *env, struct dt_object *dt, __u32 attr)
Initialize osd Iterator for given osd index object.
static void osd_it_acct_fini (const struct lu_env *env, struct dt_it *di)
Free given iterator.
static int osd_it_acct_next (const struct lu_env *env, struct dt_it *di)
Move on to the next valid entry.
static struct dt_key * osd_it_acct_key (const struct lu_env *env, const struct dt_it *di)
Return pointer to the key under iterator.
static int osd_it_acct_key_size (const struct lu_env *env, const struct dt_it *di)
Return size of key under iterator (in bytes).
static int osd_zap_cursor_retrieve_value (const struct lu_env *env, zap_cursor_t *zc, char *buf, int buf_size, int *bytes_read)
static int osd_it_acct_rec (const struct lu_env *env, const struct dt_it *di, struct dt_rec *dtrec, __u32 attr)
Return pointer to the record under iterator.
static __u64 osd_it_acct_store (const struct lu_env *env, const struct dt_it *di)
Returns cookie for current Iterator position.
static int osd_it_acct_load (const struct lu_env *env, const struct dt_it *di, __u64 hash)
Restore iterator from cookie.
static int osd_it_acct_get (const struct lu_env *env, struct dt_it *di, const struct dt_key *key)
Move Iterator to record specified by key, if the key isn't found, move to the first valid record.
static void osd_it_acct_put (const struct lu_env *env, struct dt_it *di)
Release Iterator.
int osd_declare_quota (const struct lu_env *env, struct osd_device *osd, qid_t uid, qid_t gid, long long space, struct osd_thandle *oh, bool is_blk, int *flags, bool force)
Quota Enforcement Management.
Variables
struct dt_index_operations osd_acct_index_ops
Index and Iterator operations for accounting objects.
Function Documentation
static int osd_acct_index_lookup (const struct lu_env * env, struct dt_object * dtobj, struct dt_rec * dtrec, const struct dt_key * dtkey) [static]
Space Accounting Management.
Return space usage consumed by a given uid or gid. Block usage is accurrate since it is maintained by DMU itself. However, DMU does not provide inode accounting, so the inodes in use is estimated from the block usage and statfs information.
Parameters:
env - is the environment passed by the caller
dtobj - is the accounting object
dtrec - is the record to fill with space usage information
dtkey - is the id the of the user or group for which we would like to access disk usage.
Return values:
+ve - success : exact match
-ve - failure
Definition at line 88 of file osd_quota.c.
References __u64, lquota_acct_rec::bspace, buf, CDEBUG, D_QUOTA, dt_object::do_lu, ENTRY, lquota_acct_rec::ispace, lu_object_fid(), osd_device::od_os, osd_device::od_quota_iused_est, osd_device::od_svname, osd_object::oo_db, osd_dt_obj(), osd_obj2dev(), osd_objset_user_iused(), osd_oti_get(), osd_quota_fid2dmu(), osd_thread_info::oti_buf, and RETURN.
int osd_declare_quota (const struct lu_env * env, struct osd_device * osd, qid_t uid, qid_t gid, long long space, struct osd_thandle * oh, bool is_blk, int * flags, bool force)
Quota Enforcement Management.
Definition at line 482 of file osd_quota.c.
References ENTRY, lquota_id_info::lqi_id, lquota_id_info::lqi_is_blk, lquota_id_info::lqi_space, lquota_id_info::lqi_type, osd_device::od_quota_slave, osd_oti_get(), osd_thandle::ot_quota_trans, osd_thread_info::oti_qi, lquota_id::qid_gid, lquota_id::qid_uid, qsd_op_begin(), RETURN, and unlikely.
Referenced by osd_declare_object_create(), osd_declare_object_destroy(), osd_declare_punch(), osd_declare_write(), and osd_declare_write_commit().
static void osd_it_acct_fini (const struct lu_env * env, struct dt_it * di) [static]
Free given iterator.
Parameters:
di - osd iterator
Definition at line 194 of file osd_quota.c.
References dt_object::do_lu, ENTRY, EXIT, lu_object_put(), OBD_FREE_PTR, osd_it_quota::oiq_obj, osd_it_quota::oiq_zc, osd_object::oo_dt, and osd_zap_cursor_fini().
static int osd_it_acct_get (const struct lu_env * env, struct dt_it * di, const struct dt_key * key) [static]
Move Iterator to record specified by key, if the key isn't found, move to the first valid record.
Parameters:
di - osd iterator
key - uid or gid
Return values:
+ve - di points to exact matched key
0 - di points to the first valid record
-ve - failure
Definition at line 421 of file osd_quota.c.
References __u64, ENTRY, LASSERT, osd_it_acct_load(), and RETURN.
static struct dt_it* osd_it_acct_init (const struct lu_env * env, struct dt_object * dt, __u32 attr) [static, read]
Initialize osd Iterator for given osd index object.
Parameters:
dt - osd index object
attr - not used
Definition at line 151 of file osd_quota.c.
References dt_object::do_lu, ENTRY, LASSERT, lu_object::lo_dev, lu_object_exists, lu_object_fid(), lu_object_get(), OBD_ALLOC_PTR, OBD_FREE_PTR, osd_device::od_os, osd_it_quota::oiq_obj, osd_it_quota::oiq_oid, osd_it_quota::oiq_reset, osd_it_quota::oiq_zc, osd_dev(), osd_dt_obj(), osd_oti_get(), osd_quota_fid2dmu(), osd_zap_cursor_init(), and RETURN.
static struct dt_key* osd_it_acct_key (const struct lu_env * env, const struct dt_it * di) [static, read]
Return pointer to the key under iterator.
Parameters:
di - osd iterator
Definition at line 236 of file osd_quota.c.
References dt_key, ENTRY, osd_it_quota::oiq_id, osd_it_quota::oiq_reset, osd_it_quota::oiq_zc, osd_oti_get(), osd_thread_info::oti_za, and RETURN.
static int osd_it_acct_key_size (const struct lu_env * env, const struct dt_it * di) [static]
Return size of key under iterator (in bytes).
Parameters:
di - osd iterator
Definition at line 258 of file osd_quota.c.
References ENTRY, and RETURN.
static int osd_it_acct_load (const struct lu_env * env, const struct dt_it * di, __u64 hash) [static]
Restore iterator from cookie.
if the hash isn't found, restore the first valid record.
Parameters:
di - osd iterator
hash - iterator location cookie
Return values:
+ve - di points to exact matched key
0 - di points to the first valid record
-ve - failure
Definition at line 383 of file osd_quota.c.
References ENTRY, osd_device::od_os, osd_it_quota::oiq_obj, osd_it_quota::oiq_oid, osd_it_quota::oiq_reset, osd_it_quota::oiq_zc, osd_obj2dev(), osd_oti_get(), osd_zap_cursor_fini(), osd_zap_cursor_init(), osd_thread_info::oti_za, and RETURN.
Referenced by osd_it_acct_get().
static int osd_it_acct_next (const struct lu_env * env, struct dt_it * di) [static]
Move on to the next valid entry.
Parameters:
di - osd iterator
Return values:
+ve - iterator reached the end
0 - iterator has not reached the end yet
-ve - unexpected failure
Definition at line 215 of file osd_quota.c.
References ENTRY, osd_it_quota::oiq_reset, osd_it_quota::oiq_zc, osd_oti_get(), osd_thread_info::oti_za, and RETURN.
static void osd_it_acct_put (const struct lu_env * env, struct dt_it * di) [static]
Release Iterator.
Parameters:
di - osd iterator
Definition at line 437 of file osd_quota.c.
static int osd_it_acct_rec (const struct lu_env * env, const struct dt_it * di, struct dt_rec * dtrec, __u32 attr) [static]
Return pointer to the record under iterator.
Parameters:
di - osd iterator
attr - not used
Definition at line 308 of file osd_quota.c.
References lquota_acct_rec::bspace, CDEBUG, D_QUOTA, ENTRY, lquota_acct_rec::ispace, osd_device::od_os, osd_device::od_quota_iused_est, osd_device::od_svname, osd_it_quota::oiq_obj, osd_it_quota::oiq_reset, osd_it_quota::oiq_zc, osd_object::oo_db, osd_obj2dev(), osd_objset_user_iused(), osd_oti_get(), osd_zap_cursor_retrieve_value(), osd_thread_info::oti_za, RETURN, and unlikely.
static __u64 osd_it_acct_store (const struct lu_env * env, const struct dt_it * di) [static]
Returns cookie for current Iterator position.
Parameters:
di - osd iterator
Definition at line 363 of file osd_quota.c.
References ENTRY, osd_it_quota::oiq_reset, osd_it_quota::oiq_zc, osd_zap_cursor_serialize(), and RETURN.
static uint64_t osd_objset_user_iused (struct osd_device * osd, uint64_t uidbytes) [static]
Helper function to estimate the number of inodes in use for a give uid/gid from the block usage.
Definition at line 49 of file osd_quota.c.
References osd_device::od_max_blksz, osd_device::od_os, and osd_objs_count_estimate().
Referenced by osd_acct_index_lookup(), and osd_it_acct_rec().
uint64_t osd_quota_fid2dmu (const struct lu_fid * fid)
Helper function to retrieve DMU object id from fid for accounting object.
Definition at line 37 of file osd_quota.c.
References ACCT_GROUP_OID, fid_is_acct(), fid_oid(), and LASSERT.
Referenced by osd_acct_index_lookup(), and osd_it_acct_init().
static int osd_zap_cursor_retrieve_value (const struct lu_env * env, zap_cursor_t * zc, char * buf, int buf_size, int * bytes_read) [static]
Definition at line 269 of file osd_quota.c.
References likely, osd_oti_get(), osd_thread_info::oti_za, and unlikely.
Referenced by osd_it_acct_rec().
Variable Documentation
struct dt_index_operations osd_acct_index_ops
Initial value:
 {
        .dio_lookup = osd_acct_index_lookup,
        .dio_it     = {
                .init           = osd_it_acct_init,
                .fini           = osd_it_acct_fini,
                .get            = osd_it_acct_get,
                .put            = osd_it_acct_put,
                .next           = osd_it_acct_next,
                .key            = osd_it_acct_key,
                .key_size       = osd_it_acct_key_size,
                .rec            = osd_it_acct_rec,
                .store          = osd_it_acct_store,
                .load           = osd_it_acct_load
        }
}
Index and Iterator operations for accounting objects.
Quota/Accounting handling.
Definition at line 444 of file osd_quota.c.
Referenced by osd_index_try().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.