Lustre: lustre/osd-ldiskfs/osd_handler.c File Reference
lustre/osd-ldiskfs/osd_handler.c File Reference
#include <linux/module.h>
#include <linux/user_namespace.h>
#include <lustre_ver.h>
#include <linux/types.h>
#include <linux/fs.h>
#include <linux/xattr.h>
#include <ldiskfs/ldiskfs.h>
#include <ldiskfs/xattr.h>
#include <ldiskfs/ldiskfs_extents.h>
#include <obd_support.h>
#include <lustre_net.h>
#include <lustre_fid.h>
#include <lustre_param.h>
#include "osd_internal.h"
#include "osd_dynlocks.h"
#include <md_object.h>
#include <lustre_quota.h>
#include <lustre_linkea.h>
Data Structures
struct osd_filldir_cbs
Defines
#define DEBUG_SUBSYSTEM S_OSD
#define osd_th_alloced(h) do {} while(0)
#define osd_th_started(h) do {} while(0)
#define OSD_CHECK_SLOW_TH(oth, dev, expr) expr
#define PER_OBJ_USAGE LDISKFS_DIR_REC_LEN(20)
Estimate space needed for file creations.
Typedefs
typedef int(* osd_obj_type_f)(struct osd_thread_info *, struct osd_object *, struct lu_attr *, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *)
Enumerations
enum { OSD_TXN_OI_DELETE_CREDITS = 20, OSD_TXN_INODE_DELETE_CREDITS = 20 }
enum { OSD_NAME_LEN = 255 }
Functions
module_param (ldiskfs_pdo, int, 0644)
MODULE_PARM_DESC (ldiskfs_pdo,"ldiskfs with parallel directory operations")
module_param (ldiskfs_track_declares_assert, int, 0644)
MODULE_PARM_DESC (ldiskfs_track_declares_assert,"LBUG during tracking of declares")
static int osd_remote_fid (const struct lu_env *env, struct osd_device *osd, const struct lu_fid *fid)
static int osd_process_scheduled_agent_removals (const struct lu_env *env, struct osd_device *osd)
static int osd_has_index (const struct osd_object *obj)
static int osd_object_invariant (const struct lu_object *l)
static int osd_write_locked (const struct lu_env *env, struct osd_object *o)
static int osd_root_get (const struct lu_env *env, struct dt_device *dev, struct lu_fid *f)
static struct osd_idmap_cache * osd_idc_find (const struct lu_env *env, struct osd_device *osd, const struct lu_fid *fid)
static struct osd_idmap_cache * osd_idc_add (const struct lu_env *env, struct osd_device *osd, const struct lu_fid *fid)
static struct osd_idmap_cache * osd_idc_find_or_init (const struct lu_env *env, struct osd_device *osd, const struct lu_fid *fid)
static int osd_idc_find_and_init (const struct lu_env *env, struct osd_device *osd, struct osd_object *obj)
static struct lu_object * osd_object_alloc (const struct lu_env *env, const struct lu_object_header *hdr, struct lu_device *d)
int osd_get_lma (struct osd_thread_info *info, struct inode *inode, struct dentry *dentry, struct lustre_mdt_attrs *lma)
struct inode * osd_iget (struct osd_thread_info *info, struct osd_device *dev, struct osd_inode_id *id)
int osd_ldiskfs_add_entry (struct osd_thread_info *info, handle_t *handle, struct dentry *child, struct inode *inode, struct htree_lock *hlock)
static struct inode * osd_iget_fid (struct osd_thread_info *info, struct osd_device *dev, struct osd_inode_id *id, struct lu_fid *fid)
static struct inode * osd_iget_check (struct osd_thread_info *info, struct osd_device *dev, const struct lu_fid *fid, struct osd_inode_id *id, bool cached)
int osd_get_idif (struct osd_thread_info *info, struct inode *inode, struct dentry *dentry, struct lu_fid *fid)
static int osd_lma_self_repair (struct osd_thread_info *info, struct osd_device *osd, struct inode *inode, const struct lu_fid *fid, __u32 compat)
static int osd_check_lma (const struct lu_env *env, struct osd_object *obj)
static int osd_fid_lookup (const struct lu_env *env, struct osd_object *obj, const struct lu_fid *fid, const struct lu_object_conf *conf)
static void osd_object_init0 (struct osd_object *obj)
static int osd_object_init (const struct lu_env *env, struct lu_object *l, const struct lu_object_conf *conf)
static void osd_object_free (const struct lu_env *env, struct lu_object *l)
static void osd_index_fini (struct osd_object *o)
static int osd_inode_unlinked (const struct inode *inode)
static int osd_param_is_not_sane (const struct osd_device *dev, const struct thandle *th)
static void osd_trans_commit_cb (struct super_block *sb, struct ldiskfs_journal_cb_entry *jcb, int error)
static struct thandle * osd_trans_create (const struct lu_env *env, struct dt_device *d)
void osd_trans_dump_creds (const struct lu_env *env, struct thandle *th)
static int osd_trans_start (const struct lu_env *env, struct dt_device *d, struct thandle *th)
static int osd_seq_exists (const struct lu_env *env, struct osd_device *osd, u64 seq)
static void osd_trans_stop_cb (struct osd_thandle *oth, int result)
static int osd_trans_stop (const struct lu_env *env, struct dt_device *dt, struct thandle *th)
static int osd_trans_cb_add (struct thandle *th, struct dt_txn_commit_cb *dcb)
static void osd_object_delete (const struct lu_env *env, struct lu_object *l)
static void osd_object_release (const struct lu_env *env, struct lu_object *l)
static int osd_object_print (const struct lu_env *env, void *cookie, lu_printer_t p, const struct lu_object *l)
int osd_statfs (const struct lu_env *env, struct dt_device *d, struct obd_statfs *sfs)
static void osd_conf_get (const struct lu_env *env, const struct dt_device *dev, struct dt_device_param *param)
static int osd_sync (const struct lu_env *env, struct dt_device *d)
static int osd_commit_async (const struct lu_env *env, struct dt_device *d)
Start commit for OSD device.
static int osd_ro (const struct lu_env *env, struct dt_device *d)
static void osd_object_read_lock (const struct lu_env *env, struct dt_object *dt, unsigned role)
static void osd_object_write_lock (const struct lu_env *env, struct dt_object *dt, unsigned role)
static void osd_object_read_unlock (const struct lu_env *env, struct dt_object *dt)
static void osd_object_write_unlock (const struct lu_env *env, struct dt_object *dt)
static int osd_object_write_locked (const struct lu_env *env, struct dt_object *dt)
static struct timespec * osd_inode_time (const struct lu_env *env, struct inode *inode, __u64 seconds)
static void osd_inode_getattr (const struct lu_env *env, struct inode *inode, struct lu_attr *attr)
static int osd_attr_get (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr)
static int osd_declare_attr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_attr *attr, struct thandle *handle)
static int osd_inode_setattr (const struct lu_env *env, struct inode *inode, const struct lu_attr *attr)
static int osd_quota_transfer (struct inode *inode, const struct lu_attr *attr)
static int osd_attr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_attr *attr, struct thandle *handle)
static struct dentry * osd_child_dentry_get (const struct lu_env *env, struct osd_object *obj, const char *name, const int namelen)
static int osd_mkfile (struct osd_thread_info *info, struct osd_object *obj, umode_t mode, struct dt_allocation_hint *hint, struct thandle *th)
static int osd_mkdir (struct osd_thread_info *info, struct osd_object *obj, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *th)
static int osd_mk_index (struct osd_thread_info *info, struct osd_object *obj, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *th)
static int osd_mkreg (struct osd_thread_info *info, struct osd_object *obj, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *th)
static int osd_mksym (struct osd_thread_info *info, struct osd_object *obj, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *th)
static int osd_mknod (struct osd_thread_info *info, struct osd_object *obj, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *th)
static osd_obj_type_f osd_create_type_f (enum dt_format_type type)
static void osd_ah_init (const struct lu_env *env, struct dt_allocation_hint *ah, struct dt_object *parent, struct dt_object *child, umode_t child_mode)
static void osd_attr_init (struct osd_thread_info *info, struct osd_object *obj, struct lu_attr *attr, struct dt_object_format *dof)
static int __osd_object_create (struct osd_thread_info *info, struct osd_object *obj, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *th)
Helper function for osd_object_create().
static int __osd_oi_insert (const struct lu_env *env, struct osd_object *obj, const struct lu_fid *fid, struct thandle *th)
Helper function for osd_object_create().
int osd_fld_lookup (const struct lu_env *env, struct osd_device *osd, u64 seq, struct lu_seq_range *range)
static int osd_declare_object_create (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *handle)
static int osd_object_create (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *th)
static int osd_declare_object_destroy (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Called to destroy on-disk representation of the object.
static int osd_object_destroy (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
int osd_ea_fid_set (struct osd_thread_info *info, struct inode *inode, const struct lu_fid *fid, __u32 compat, __u32 incompat)
Put the fid into lustre_mdt_attrs, and then place the structure inode's ea.
static void osd_get_ldiskfs_dirent_param (struct ldiskfs_dentry_param *param, const struct lu_fid *fid)
ldiskfs supports fid in dirent, it is passed in dentry->d_fsdata.
static int osd_ea_fid_get (const struct lu_env *env, struct osd_object *obj, __u32 ino, struct lu_fid *fid, struct osd_inode_id *id)
Try to read the fid from inode ea into dt_rec.
static int osd_add_dot_dotdot_internal (struct osd_thread_info *info, struct inode *dir, struct inode *parent_dir, const struct lu_fid *dot_fid, const struct lu_fid *dot_dot_fid, struct osd_thandle *oth)
static struct inode * osd_create_local_agent_inode (const struct lu_env *env, struct osd_device *osd, struct osd_object *pobj, const struct lu_fid *fid, __u32 type, struct thandle *th)
Create an local agent inode for remote entry.
static int osd_schedule_agent_inode_removal (const struct lu_env *env, struct osd_thandle *oh, __u32 ino)
when direntry is deleted, we have to take care of possible agent inode referenced by that.
static int osd_object_ea_create (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *th)
OSD layer object create function for interoperability mode (b11826).
static int osd_declare_object_ref_add (const struct lu_env *env, struct dt_object *dt, struct thandle *handle)
static int osd_object_ref_add (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
static int osd_declare_object_ref_del (const struct lu_env *env, struct dt_object *dt, struct thandle *handle)
static int osd_object_ref_del (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
static int osd_object_version_get (const struct lu_env *env, struct dt_object *dt, dt_obj_version_t *ver)
static int osd_xattr_get (const struct lu_env *env, struct dt_object *dt, struct lu_buf *buf, const char *name)
static int osd_declare_xattr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, const char *name, int fl, struct thandle *handle)
static void osd_object_version_set (const struct lu_env *env, struct dt_object *dt, dt_obj_version_t *new_version)
static int osd_xattr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, const char *name, int fl, struct thandle *handle)
static int osd_xattr_list (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf)
static int osd_declare_xattr_del (const struct lu_env *env, struct dt_object *dt, const char *name, struct thandle *handle)
static int osd_xattr_del (const struct lu_env *env, struct dt_object *dt, const char *name, struct thandle *handle)
static int osd_object_sync (const struct lu_env *env, struct dt_object *dt, __u64 start, __u64 end)
static int osd_iam_index_probe (const struct lu_env *env, struct osd_object *o, const struct dt_index_features *feat)
static int osd_iam_container_init (const struct lu_env *env, struct osd_object *obj, struct osd_directory *dir)
static int osd_index_try (const struct lu_env *env, struct dt_object *dt, const struct dt_index_features *feat)
static int osd_otable_it_attr_get (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr)
static int osd_index_declare_iam_delete (const struct lu_env *env, struct dt_object *dt, const struct dt_key *key, struct thandle *handle)
static int osd_index_iam_delete (const struct lu_env *env, struct dt_object *dt, const struct dt_key *key, struct thandle *handle)
delete a (key, value) pair from index dt specified by key
static int osd_index_declare_ea_delete (const struct lu_env *env, struct dt_object *dt, const struct dt_key *key, struct thandle *handle)
static int osd_get_fid_from_dentry (struct ldiskfs_dir_entry_2 *de, struct dt_rec *fid)
static int osd_index_ea_delete (const struct lu_env *env, struct dt_object *dt, const struct dt_key *key, struct thandle *handle)
Index delete function for interoperability mode (b11826).
static int osd_index_iam_lookup (const struct lu_env *env, struct dt_object *dt, struct dt_rec *rec, const struct dt_key *key)
Lookup index for key and copy record to rec.
static int osd_index_declare_iam_insert (const struct lu_env *env, struct dt_object *dt, const struct dt_rec *rec, const struct dt_key *key, struct thandle *handle)
static int osd_index_iam_insert (const struct lu_env *env, struct dt_object *dt, const struct dt_rec *rec, const struct dt_key *key, struct thandle *th, int ignore_quota)
Inserts (key, value) pair in dt index object.
static int __osd_ea_add_rec (struct osd_thread_info *info, struct osd_object *pobj, struct inode *cinode, const char *name, const struct lu_fid *fid, struct htree_lock *hlock, struct thandle *th)
Calls ldiskfs_add_entry() to add directory entry into the directory.
static int osd_add_dot_dotdot (struct osd_thread_info *info, struct osd_object *dir, struct inode *parent_dir, const char *name, const struct lu_fid *dot_fid, const struct lu_fid *dot_dot_fid, struct thandle *th)
Calls ldiskfs_add_dot_dotdot() to add dot and dotdot entries into the directory.Also sets flags into osd object to indicate dot and dotdot are created.
static int osd_ea_add_rec (const struct lu_env *env, struct osd_object *pobj, struct inode *cinode, const char *name, const struct lu_fid *fid, struct thandle *th)
It will call the appropriate osd_add* function and return the value, return by respective functions.
static int osd_consistency_check (struct osd_thread_info *oti, struct osd_device *dev, struct osd_idmap_cache *oic)
static int osd_fail_fid_lookup (struct osd_thread_info *oti, struct osd_device *dev, struct osd_idmap_cache *oic, struct lu_fid *fid, __u32 ino)
void osd_add_oi_cache (struct osd_thread_info *info, struct osd_device *osd, struct osd_inode_id *id, const struct lu_fid *fid)
static int osd_get_pfid_from_linkea (const struct lu_env *env, struct osd_object *obj, struct lu_fid *fid)
Get parent FID from the linkEA.
static int osd_ea_lookup_rec (const struct lu_env *env, struct osd_object *obj, struct dt_rec *rec, const struct dt_key *key)
Calls ->lookup() to find dentry.
static void osd_object_put (const struct lu_env *env, struct osd_object *obj)
Put the osd object once done with it.
static int osd_index_declare_ea_insert (const struct lu_env *env, struct dt_object *dt, const struct dt_rec *rec, const struct dt_key *key, struct thandle *handle)
static int osd_index_ea_insert (const struct lu_env *env, struct dt_object *dt, const struct dt_rec *rec, const struct dt_key *key, struct thandle *th, int ignore_quota)
Index add function for interoperability mode (b11826).
static struct dt_it * osd_it_iam_init (const struct lu_env *env, struct dt_object *dt, __u32 unused)
Initialize osd Iterator for given osd index object.
static void osd_it_iam_fini (const struct lu_env *env, struct dt_it *di)
free given Iterator.
static int osd_it_iam_get (const struct lu_env *env, struct dt_it *di, const struct dt_key *key)
Move Iterator to record specified by key.
static void osd_it_iam_put (const struct lu_env *env, struct dt_it *di)
Release Iterator.
static int osd_it_iam_next (const struct lu_env *env, struct dt_it *di)
Move iterator by one record.
static struct dt_key * osd_it_iam_key (const struct lu_env *env, const struct dt_it *di)
Return pointer to the key under iterator.
static int osd_it_iam_key_size (const struct lu_env *env, const struct dt_it *di)
Return size of key under iterator (in bytes).
static void osd_it_append_attrs (struct lu_dirent *ent, int len, __u16 type)
static void osd_it_pack_dirent (struct lu_dirent *ent, struct lu_fid *fid, __u64 offset, char *name, __u16 namelen, __u16 type, __u32 attr)
build lu direct from backend fs dirent.
static int osd_it_iam_rec (const struct lu_env *env, const struct dt_it *di, struct dt_rec *dtrec, __u32 attr)
Return pointer to the record under iterator.
static __u64 osd_it_iam_store (const struct lu_env *env, const struct dt_it *di)
Returns cookie for current Iterator position.
static int osd_it_iam_load (const struct lu_env *env, const struct dt_it *di, __u64 hash)
Restore iterator from cookie.
static struct dt_it * osd_it_ea_init (const struct lu_env *env, struct dt_object *dt, __u32 attr)
Creates or initializes iterator context.
static void osd_it_ea_fini (const struct lu_env *env, struct dt_it *di)
Destroy or finishes iterator context.
static int osd_it_ea_get (const struct lu_env *env, struct dt_it *di, const struct dt_key *key)
It position the iterator at given key, so that next lookup continues from that key Or it is similar to dio_it->load() but based on a key, rather than file position.
static void osd_it_ea_put (const struct lu_env *env, struct dt_it *di)
Does nothing.
static int osd_ldiskfs_filldir (void *buf, const char *name, int namelen, loff_t offset, __u64 ino, unsigned d_type)
It is called internally by ->readdir().
static int osd_ldiskfs_it_fill (const struct lu_env *env, const struct dt_it *di)
Calls ->readdir() to load a directory entry at a time and stored it in iterator's in-memory data structure.
static int osd_it_ea_next (const struct lu_env *env, struct dt_it *di)
It calls osd_ldiskfs_it_fill() which will use ->readdir() to load a directory entry at a time and stored it in iterator's in-memory data structure.
static struct dt_key * osd_it_ea_key (const struct lu_env *env, const struct dt_it *di)
Returns the key at current position from iterator's in memory structure.
static int osd_it_ea_key_size (const struct lu_env *env, const struct dt_it *di)
Returns the key's size at current position from iterator's in memory structure.
static bool osd_dot_dotdot_has_space (struct ldiskfs_dir_entry_2 *de, int dot_dotdot)
static bool osd_dirent_has_space (struct ldiskfs_dir_entry_2 *de, __u16 namelen, unsigned blocksize, int dot_dotdot)
static int osd_dirent_reinsert (const struct lu_env *env, handle_t *jh, struct dentry *dentry, const struct lu_fid *fid, struct buffer_head *bh, struct ldiskfs_dir_entry_2 *de, struct htree_lock *hlock, int dot_dotdot)
static int osd_dirent_check_repair (const struct lu_env *env, struct osd_object *obj, struct osd_it_ea *it, struct lu_fid *fid, struct osd_inode_id *id, __u32 *attr)
static int osd_it_ea_rec (const struct lu_env *env, const struct dt_it *di, struct dt_rec *dtrec, __u32 attr)
Returns the value at current position from iterator's in memory structure.
static int osd_it_ea_rec_size (const struct lu_env *env, const struct dt_it *di, __u32 attr)
Returns the record size size at current position.
static __u64 osd_it_ea_store (const struct lu_env *env, const struct dt_it *di)
Returns a cookie for current position of the iterator head, so that user can use this cookie to load/start the iterator next time.
static int osd_it_ea_load (const struct lu_env *env, const struct dt_it *di, __u64 hash)
It calls osd_ldiskfs_it_fill() which will use ->readdir() to load a directory entry at a time and stored it i inn, in iterator's in-memory data structure.
static int osd_index_ea_lookup (const struct lu_env *env, struct dt_object *dt, struct dt_rec *rec, const struct dt_key *key)
Index lookup function for interoperability mode (b11826).
static void * osd_key_init (const struct lu_context *ctx, struct lu_context_key *key)
static void osd_key_fini (const struct lu_context *ctx, struct lu_context_key *key, void *data)
static void osd_key_exit (const struct lu_context *ctx, struct lu_context_key *key, void *data)
LU_TYPE_INIT_FINI (osd,&osd_key)
static int osd_device_init (const struct lu_env *env, struct lu_device *d, const char *name, struct lu_device *next)
static int osd_fid_init (const struct lu_env *env, struct osd_device *osd)
static void osd_fid_fini (const struct lu_env *env, struct osd_device *osd)
static int osd_shutdown (const struct lu_env *env, struct osd_device *o)
static void osd_umount (const struct lu_env *env, struct osd_device *o)
static int osd_mount (const struct lu_env *env, struct osd_device *o, struct lustre_cfg *cfg)
static struct lu_device * osd_device_fini (const struct lu_env *env, struct lu_device *d)
static int osd_device_init0 (const struct lu_env *env, struct osd_device *o, struct lustre_cfg *cfg)
static struct lu_device * osd_device_alloc (const struct lu_env *env, struct lu_device_type *t, struct lustre_cfg *cfg)
static struct lu_device * osd_device_free (const struct lu_env *env, struct lu_device *d)
static int osd_process_config (const struct lu_env *env, struct lu_device *d, struct lustre_cfg *cfg)
static int osd_recovery_complete (const struct lu_env *env, struct lu_device *d)
static int osd_obd_connect (const struct lu_env *env, struct obd_export **exp, struct obd_device *obd, struct obd_uuid *cluuid, struct obd_connect_data *data, void *localdata)
static int osd_obd_disconnect (struct obd_export *exp)
static int osd_prepare (const struct lu_env *env, struct lu_device *pdev, struct lu_device *dev)
static int osd_fid_alloc (const struct lu_env *env, struct obd_export *exp, struct lu_fid *fid, struct md_op_data *op_data)
static int osd_health_check (const struct lu_env *env, struct obd_device *obd)
static int __init osd_init (void)
static void __exit osd_exit (void)
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Object Storage Device ("LUSTRE_OSD_LDISKFS_NAME")")
MODULE_VERSION (LUSTRE_VERSION_STRING)
MODULE_LICENSE ("GPL")
module_init (osd_init)
module_exit (osd_exit)
Variables
int ldiskfs_pdo = 1
int ldiskfs_track_declares_assert
struct kmem_cache * dynlock_cachep
struct kmem_cache * osd_itea_cachep
static struct lu_kmem_descr ldiskfs_caches []
static const char dot [] = "."
static const char dotdot [] = ".."
static const char remote_obj_dir [] = "REM_OBJ_DIR"
static struct lu_object_operations osd_lu_obj_ops
static struct dt_object_operations osd_obj_ops
static struct dt_object_operations osd_obj_ea_ops
dt_object_operations for interoperability mode (i.e.
static struct dt_object_operations osd_obj_otable_it_ops
static struct dt_index_operations osd_index_iam_ops
static struct dt_index_operations osd_index_ea_ops
Index and Iterator operations for interoperability mode (i.e.
int osd_trans_declare_op2rb []
const int osd_dto_credits_noquota [DTO_NR]
Note: we do not count into QUOTA here.
static struct dt_device_operations osd_dt_ops
struct lu_context_key osd_key
struct lu_device_operations osd_lu_ops
static struct
lu_device_type_operations osd_device_type_ops
static struct lu_device_type osd_device_type
static struct obd_ops osd_obd_device_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_OSD
Definition at line 44 of file osd_handler.c.
#define OSD_CHECK_SLOW_TH (oth, dev, expr) expr
Definition at line 1164 of file osd_handler.c.
Referenced by osd_trans_stop().
#define osd_th_alloced (h) do {} while(0)
Definition at line 1162 of file osd_handler.c.
Referenced by osd_trans_create().
#define osd_th_started (h) do {} while(0)
Definition at line 1163 of file osd_handler.c.
Referenced by osd_trans_start().
#define PER_OBJ_USAGE LDISKFS_DIR_REC_LEN(20)
Estimate space needed for file creations.
We assume the largest filename which is 2^64 - 1, hence a filename of 20 chars. This is 28 bytes per object which is 28MB for 1M objects ... no so bad.
Definition at line 1651 of file osd_handler.c.
Referenced by osd_conf_get().
Typedef Documentation
typedef int(* osd_obj_type_f)(struct osd_thread_info *, struct osd_object *, struct lu_attr *, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *)
Definition at line 2460 of file osd_handler.c.
Enumeration Type Documentation
anonymous enum
Enumerator:
OSD_TXN_OI_DELETE_CREDITS
OSD_TXN_INODE_DELETE_CREDITS
Definition at line 1083 of file osd_handler.c.
anonymous enum
Enumerator:
OSD_NAME_LEN
Definition at line 2350 of file osd_handler.c.
Function Documentation
static int __osd_ea_add_rec (struct osd_thread_info * info, struct osd_object * pobj, struct inode * cinode, const char * name, const struct lu_fid * fid, struct htree_lock * hlock, struct thandle * th) [static]
Calls ldiskfs_add_entry() to add directory entry into the directory.
This is required for interoperability mode (b11826)
Return values:
0,on success
-ve,on error
Definition at line 4240 of file osd_handler.c.
References LASSERT, ll_vfs_dq_init, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_BAD_TYPE, osd_object::oo_inode, osd_child_dentry_get(), osd_get_ldiskfs_dirent_param(), osd_ldiskfs_add_entry(), osd_ldiskfs_find_entry, osd_obj2dev(), osd_sb(), osd_thandle::ot_handle, osd_thandle::ot_super, osd_thread_info::oti_env, osd_thread_info::oti_ldp, RETURN, and unlikely.
Referenced by osd_add_dot_dotdot(), and osd_ea_add_rec().
static int __osd_object_create (struct osd_thread_info * info, struct osd_object * obj, struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof, struct thandle * th) [static]
Helper function for osd_object_create().
Return values:
0,on success
Definition at line 2554 of file osd_handler.c.
References dt_object_format::dof_type, LASSERT, likely, osd_attr_init(), osd_create_type_f(), osd_object_init0(), OSD_OT_CREATE, osd_trans_exec_check(), osd_trans_exec_op(), and osd_thread_info::oti_env.
Referenced by osd_object_create(), and osd_object_ea_create().
static int __osd_oi_insert (const struct lu_env * env, struct osd_object * obj, const struct lu_fid * fid, struct thandle * th) [static]
Helper function for osd_object_create().
Return values:
0,on success
Definition at line 2597 of file osd_handler.c.
References LASSERT, OI_CHECK_FLD, osd_object::oo_inode, osd_id_gen(), osd_obj2dev(), osd_oi_insert(), OSD_OT_INSERT, osd_oti_get(), osd_trans_exec_check(), osd_trans_exec_op(), osd_thandle::ot_handle, osd_thandle::ot_super, and osd_thread_info::oti_id.
Referenced by osd_object_create(), and osd_object_ea_create().
LU_TYPE_INIT_FINI (osd , & osd_key)
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Object Storage Device ("LUSTRE_OSD_LDISKFS_NAME")")
module_exit (osd_exit)
module_init (osd_init)
MODULE_LICENSE ("GPL")
module_param (ldiskfs_track_declares_assert , int , 0644)
module_param (ldiskfs_pdo , int , 0644)
MODULE_PARM_DESC (ldiskfs_track_declares_assert , "LBUG during tracking of declares")
MODULE_PARM_DESC (ldiskfs_pdo , "ldiskfs with parallel directory operations")
MODULE_VERSION (LUSTRE_VERSION_STRING)
static int osd_add_dot_dotdot (struct osd_thread_info * info, struct osd_object * dir, struct inode * parent_dir, const char * name, const struct lu_fid * dot_fid, const struct lu_fid * dot_dot_fid, struct thandle * th) [static]
Calls ldiskfs_add_dot_dotdot() to add dot and dotdot entries into the directory.Also sets flags into osd object to indicate dot and dotdot are created.
This is required for interoperability mode (b11826)
Parameters:
dir directory for dot and dotdot fixup.
obj child object for linking
Return values:
0,on success
-ve,on error
Definition at line 4305 of file osd_handler.c.
References __osd_ea_add_rec(), lu_fid::f_oid, LASSERT, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_BAD_PARENT, osd_object::oo_compat_dot_created, osd_object::oo_compat_dotdot_created, osd_object::oo_inode, osd_add_dot_dotdot_internal(), osd_thandle::ot_handle, and osd_thandle::ot_super.
Referenced by osd_ea_add_rec().
static int osd_add_dot_dotdot_internal (struct osd_thread_info * info, struct inode * dir, struct inode * parent_dir, const struct lu_fid * dot_fid, const struct lu_fid * dot_dot_fid, struct osd_thandle * oth) [static]
Definition at line 2927 of file osd_handler.c.
References osd_get_ldiskfs_dirent_param(), osd_thandle::ot_handle, osd_thread_info::oti_ldp, osd_thread_info::oti_ldp2, and set_nlink().
Referenced by osd_add_dot_dotdot(), and osd_create_local_agent_inode().
void osd_add_oi_cache (struct osd_thread_info * info, struct osd_device * osd, struct osd_inode_id * id, const struct lu_fid * fid)
Definition at line 4508 of file osd_handler.c.
References CDEBUG, D_INODE, DFID, osd_idmap_cache::oic_dev, osd_idmap_cache::oic_fid, osd_idmap_cache::oic_lid, osd_inode_id::oii_gen, osd_inode_id::oii_ino, osd_thread_info::oti_cache, and PFID.
Referenced by osd_ea_lookup_rec(), osd_it_ea_rec(), and osd_lookup_in_remote_parent().
static void osd_ah_init (const struct lu_env * env, struct dt_allocation_hint * ah, struct dt_object * parent, struct dt_object * child, umode_t child_mode) [static]
Definition at line 2495 of file osd_handler.c.
References dt_allocation_hint::dah_mode, dt_allocation_hint::dah_parent, dt_object_remote(), LASSERT, osd_dt_obj(), osd_idc_find_and_init(), and osd_obj2dev().
static int osd_attr_get (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr) [static]
Definition at line 1953 of file osd_handler.c.
References dt_object_exists(), dt_object_remote(), lu_attr::la_flags, LASSERT, LINVRNT, LUSTRE_ORPHAN_FL, osd_object::oo_destroyed, osd_object::oo_guard, osd_object::oo_inode, osd_object::oo_lma_flags, osd_dt_obj(), osd_inode_getattr(), osd_invariant, and unlikely.
static void osd_attr_init (struct osd_thread_info * info, struct osd_object * obj, struct lu_attr * attr, struct dt_object_format * dof) [static]
Definition at line 2511 of file osd_handler.c.
References __u64, DFT_NODE, dt_object_format::dof_type, lu_attr::la_atime, LA_ATIME, lu_attr::la_ctime, LA_CTIME, LA_MODE, lu_attr::la_mtime, LA_MTIME, LA_RDEV, LA_TYPE, lu_attr::la_valid, LASSERTF, ll_dirty_inode, LTIME_S, osd_object::oo_inode, osd_inode_setattr(), osd_quota_transfer(), and osd_thread_info::oti_env.
Referenced by __osd_object_create().
static int osd_attr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_attr * attr, struct thandle * handle) [static]
Definition at line 2199 of file osd_handler.c.
References __osd_xattr_set(), CWARN, DFID, dt_object::do_lu, dt_object_exists(), dt_object_remote(), fid_cpu_to_be(), GOTO, iam_update(), lu_attr::la_flags, LA_FLAGS, lu_attr::la_valid, LASSERT, ll_dirty_inode, lustre_mdt_attrs::lma_incompat, lu_object::lo_dev, lu_object_fid(), LUSTRE_LMA_FL_MASKS, lustre_lma_swab(), lustre_to_lma_flags(), OBD_FAIL_CHECK, OBD_FAIL_OSD_FID_MAPPING, osd_directory::od_container, osd_oi::oi_dir, osd_object::oo_guard, osd_object::oo_inode, osd_object::oo_lma_flags, osd_dev(), osd_dt_obj(), osd_fid2oi(), osd_get_lma(), osd_idx_ipd_get(), osd_inode_setattr(), osd_invariant, osd_ipd_put(), osd_name(), osd_obj2dev(), OSD_OT_ATTR_SET, OSD_OT_XATTR_SET, osd_oti_get(), osd_quota_transfer(), osd_trans_exec_check(), osd_trans_exec_op(), osd_thandle::ot_handle, osd_thandle::ot_super, osd_thread_info::oti_fid, osd_thread_info::oti_id, osd_thread_info::oti_mdt_attrs, osd_thread_info::oti_obj_dentry, PFID, RETURN, unlikely, and XATTR_NAME_LMA.
static int osd_check_lma (const struct lu_env * env, struct osd_object * obj) [static]
Definition at line 691 of file osd_handler.c.
References __osd_xattr_get(), CFS_FAIL_CHECK, CLASSERT, CWARN, DFID, dt_object::do_lu, ENTRY, fid_idif_ost_idx(), fid_is_idif(), fid_is_igif(), fid_to_ostid(), lustre_mdt_attrs::lma_incompat, LMA_INCOMPAT_SUPP, LMA_OLD_SIZE, lustre_mdt_attrs::lma_self_fid, LMAC_FID_ON_OST, lu_fid_eq(), lu_object_fid(), lustre_lma_swab(), OBD_FAIL_OSD_LMA_INCOMPAT, osd_device::od_check_ff, osd_device::od_index_in_idif, ost_id::oi, osd_object::oo_dt, osd_object::oo_inode, osd_get_idif(), osd_lma_self_repair(), osd_name(), osd_obj2dev(), osd_oti_get(), ostid_to_fid(), osd_thread_info::oti_fid3, osd_thread_info::oti_mdt_attrs, osd_thread_info::oti_mdt_attrs_old, osd_thread_info::oti_obj_dentry, osd_thread_info::oti_ostid, PFID, RETURN, unlikely, and XATTR_NAME_LMA.
Referenced by osd_fid_lookup().
static struct dentry* osd_child_dentry_get (const struct lu_env * env, struct osd_object * obj, const char * name, const int namelen) [static, read]
Definition at line 2291 of file osd_handler.c.
References osd_object::oo_inode, and osd_child_dentry_by_inode().
Referenced by __osd_ea_add_rec(), osd_ea_lookup_rec(), and osd_index_ea_delete().
static int osd_commit_async (const struct lu_env * env, struct dt_device * d) [static]
Start commit for OSD device.
An implementation of dt_commit_async method for OSD device. Asychronously starts underlayng fs sync and thereby a transaction commit.
Parameters:
env environment
d dt device
See also:
dt_device_operations
Definition at line 1735 of file osd_handler.c.
References CDEBUG, D_HA, ENTRY, LUSTRE_OSD_LDISKFS_NAME, osd_dt_dev(), osd_sb(), and RETURN.
static void osd_conf_get (const struct lu_env * env, const struct dt_device * dev, struct dt_device_param * param) [static]
Definition at line 1657 of file osd_handler.c.
References dt_device_param::ddp_extent_tax, dt_device_param::ddp_inodespace, dt_device_param::ddp_max_ea_size, dt_device_param::ddp_max_extent_blks, dt_device_param::ddp_max_name_len, dt_device_param::ddp_max_nlink, dt_device_param::ddp_maxbytes, dt_device_param::ddp_mntopts, dt_device_param::ddp_mount_type, dt_device_param::ddp_symlink_max, LDD_MT_LDISKFS, MNTOPT_ACL, MNTOPT_USERXATTR, osd_dt_dev(), osd_sb(), and PER_OBJ_USAGE.
static int osd_consistency_check (struct osd_thread_info * oti, struct osd_device * dev, struct osd_idmap_cache * oic) [static]
Definition at line 4413 of file osd_handler.c.
References CDEBUG, D_CONSOLE, D_LFSCK, DFID, ENTRY, fid_is_igif(), fid_is_norm(), osd_device::od_noscrub, osd_device::od_scrub, osd_idmap_cache::oic_fid, osd_idmap_cache::oic_lid, osd_inode_id::oii_gen, osd_inode_id::oii_ino, osd_scrub::os_pos_current, osd_scrub::os_thread, osd_id_eq(), osd_iget(), osd_oi_lookup(), osd_oii_insert(), OSD_OII_NOGEN, osd_sb(), osd_scrub_start(), osd_thread_info::oti_id, PFID, RETURN, SS_AUTO_PARTIAL, SS_CLEAR_DRYRUN, SS_CLEAR_FAILOUT, thread_is_running(), and unlikely.
Referenced by osd_ea_lookup_rec().
static struct inode* osd_create_local_agent_inode (const struct lu_env * env, struct osd_device * osd, struct osd_object * pobj, const struct lu_fid * fid, __u32 type, struct thandle * th) [static, read]
Create an local agent inode for remote entry.
Definition at line 2967 of file osd_handler.c.
References CERROR, DFID, dt_object::do_lu, ENTRY, LASSERT, LDISKFS_STATE_LUSTRE_NOSCRUB, LMAI_AGENT, lu_object_fid(), osd_object::oo_dt, osd_object::oo_inode, osd_add_dot_dotdot_internal(), osd_ea_fid_set(), osd_name(), osd_oti_get(), osd_thandle::ot_handle, osd_thandle::ot_super, PFID, and RETURN.
Referenced by osd_index_ea_insert().
static osd_obj_type_f osd_create_type_f (enum dt_format_type type) [static]
Definition at line 2466 of file osd_handler.c.
References DFT_DIR, DFT_INDEX, DFT_NODE, DFT_REGULAR, DFT_SYM, LBUG, osd_mk_index(), osd_mkdir(), osd_mknod(), osd_mkreg(), and osd_mksym().
Referenced by __osd_object_create().
static int osd_declare_attr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_attr * attr, struct thandle * handle) [static]
Definition at line 1976 of file osd_handler.c.
References DTO_ATTR_SET_BASE, DTO_XATTR_SET, ENTRY, i_gid_read(), i_uid_read(), lu_attr::la_gid, LA_GID, lu_attr::la_uid, LA_UID, lu_attr::la_valid, LASSERT, lquota_id_info::lqi_id, lquota_id_info::lqi_is_blk, lquota_id_info::lqi_space, lquota_id_info::lqi_type, osd_object::oo_inode, osd_declare_qid(), osd_dt_obj(), osd_invariant, OSD_OT_ATTR_SET, OSD_OT_XATTR_SET, osd_oti_get(), osd_trans_declare_op(), osd_thandle::ot_handle, osd_thread_info::oti_qi, lquota_id::qid_gid, lquota_id::qid_uid, RETURN, and toqb.
static int osd_declare_object_create (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof, struct thandle * handle) [static]
Definition at line 2648 of file osd_handler.c.
References DFT_INDEX, dt_object_format::dof_type, DTO_INDEX_INSERT, DTO_OBJECT_CREATE, ENTRY, lu_attr::la_gid, lu_attr::la_uid, LASSERT, osd_declare_inode_qid(), osd_dt_obj(), osd_idc_find_and_init(), osd_obj2dev(), OSD_OT_CREATE, OSD_OT_INSERT, osd_trans_declare_op(), osd_thandle::ot_handle, osd_thandle::ot_super, and RETURN.
static int osd_declare_object_destroy (const struct lu_env * env, struct dt_object * dt, struct thandle * th) [static]
Called to destroy on-disk representation of the object.
Concurrency: must be locked
Definition at line 2733 of file osd_handler.c.
References DTO_INDEX_DELETE, DTO_OBJECT_DELETE, ENTRY, i_gid_read(), i_uid_read(), LASSERT, osd_object::oo_inode, osd_declare_inode_qid(), osd_dt_obj(), osd_idc_find_and_init(), osd_obj2dev(), OSD_OT_DELETE, OSD_OT_DESTROY, osd_trans_declare_op(), osd_thandle::ot_handle, osd_thandle::ot_super, and RETURN.
static int osd_declare_object_ref_add (const struct lu_env * env, struct dt_object * dt, struct thandle * handle) [static]
Definition at line 3175 of file osd_handler.c.
References DTO_ATTR_SET_BASE, LASSERT, OSD_OT_REF_ADD, osd_trans_declare_op(), osd_thandle::ot_handle, and osd_thandle::ot_super.
static int osd_declare_object_ref_del (const struct lu_env * env, struct dt_object * dt, struct thandle * handle) [static]
Definition at line 3249 of file osd_handler.c.
References dt_object_exists(), dt_object_remote(), DTO_ATTR_SET_BASE, LASSERT, OSD_OT_REF_DEL, osd_trans_declare_op(), osd_thandle::ot_handle, and osd_thandle::ot_super.
static int osd_declare_xattr_del (const struct lu_env * env, struct dt_object * dt, const char * name, struct thandle * handle) [static]
Definition at line 3540 of file osd_handler.c.
References dt_object::do_lu, dt_object_remote(), DTO_XATTR_SET, LASSERT, lu_object::lo_dev, osd_dev(), OSD_OT_XATTR_SET, osd_sb(), osd_trans_declare_op(), osd_thandle::ot_credits, and osd_thandle::ot_handle.
static int osd_declare_xattr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, const char * name, int fl, struct thandle * handle) [static]
Definition at line 3372 of file osd_handler.c.
References __osd_xattr_get(), credits, dt_object::do_lu, dt_object_exists(), DTO_XATTR_SET, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lu_object::lo_dev, LU_XATTR_REPLACE, osd_calc_bkmap_credits(), osd_dev(), osd_dt_obj(), OSD_OT_XATTR_SET, osd_oti_get(), osd_sb(), osd_trans_declare_op(), osd_thandle::ot_handle, XATTR_NAME_LMA, and XATTR_NAME_VERSION.
static struct lu_device* osd_device_alloc (const struct lu_env * env, struct lu_device_type * t, struct lustre_cfg * cfg) [static, read]
Definition at line 6503 of file osd_handler.c.
References dt_device_fini(), dt_device_init(), lu_env_refill(), OBD_ALLOC_PTR, OBD_FREE_PTR, osd_device::od_dt_dev, osd2lu_dev(), osd_device_init0(), and unlikely.
static struct lu_device* osd_device_fini (const struct lu_env * env, struct lu_device * d) [static, read]
Definition at line 6389 of file osd_handler.c.
References ENTRY, osd_dev(), osd_obj_map_fini(), osd_scrub_cleanup(), osd_shutdown(), osd_umount(), and RETURN.
static struct lu_device* osd_device_free (const struct lu_env * env, struct lu_device * d) [static, read]
Definition at line 6530 of file osd_handler.c.
References cfs_hash_is_empty(), D_ERROR, dt_device_fini(), ENTRY, lu_device::ld_site, LIBCFS_DEBUG_MSG_DATA_DECL, lu_site::ls_obj_hash, lu_site::ls_top_dev, lu_cdebug_printer(), lu_site_fini(), lu_site_print(), lu_site_purge(), OBD_FREE_PTR, osd_device::od_dt_dev, osd_device::od_site, osd_dev(), and RETURN.
static int osd_device_init (const struct lu_env * env, struct lu_device * d, const char * name, struct lu_device * next) [static]
Definition at line 6130 of file osd_handler.c.
References osd_device::od_svname, osd_dev(), and strlcpy().
static int osd_device_init0 (const struct lu_env * env, struct osd_device * o, struct lustre_cfg * cfg) [static]
Definition at line 6404 of file osd_handler.c.
References CERROR, dt_device::dd_ops, FULL_SCRUB_THRESHOLD_RATE_DEFAULT, GOTO, INIT_LIST_HEAD, LASSERT, lu_device::ld_ops, lu_device::ld_site, LDD_F_SV_TYPE_OST, lu_site::ls_bottom_dev, lu_site::ls_linkage, lu_env_refill(), lu_site_fini(), lu_site_init(), lu_site_init_finish(), lustre_cfg_string(), list_head::next, osd_device::od_dt_dev, osd_device::od_full_scrub_ratio, osd_device::od_full_scrub_threshold_rate, osd_device::od_index, osd_device::od_ios_list, osd_device::od_is_ost, osd_device::od_orphan_list, osd_device::od_osfs_lock, osd_device::od_otable_mutex, osd_device::od_proc_entry, osd_device::od_quota_slave, osd_device::od_read_cache, osd_device::od_readcache_max_filesize, osd_device::od_site, osd_device::od_svname, osd_device::od_writethrough_cache, OFSR_DEFAULT, osd2lu_dev(), osd_lu_ops, OSD_MAX_CACHE_SIZE, osd_mount(), osd_obj_map_fini(), osd_obj_map_init(), osd_oti_get(), osd_scrub_cleanup(), osd_scrub_setup(), osd_umount(), list_head::prev, qsd_init(), RETURN, server_name2index(), and strlcpy().
Referenced by osd_device_alloc().
static int osd_dirent_check_repair (const struct lu_env * env, struct osd_object * obj, struct osd_it_ea * it, struct lu_fid * fid, struct osd_inode_id * id, __u32 * attr) [static]
Definition at line 5548 of file osd_handler.c.
References CDEBUG, credits, D_LFSCK, devname, DFID, dir, DTO_INDEX_DELETE, DTO_INDEX_INSERT, ENTRY, fid_is_sane(), fid_oid(), FID_SEQ_LOCAL_FILE, GOTO, LDISKFS_HT_MISC, le32_to_cpu, lustre_mdt_attrs::lma_compat, lustre_mdt_attrs::lma_self_fid, LMAC_NOT_IN_OI, lu_fid_eq(), lu_igif_build(), LUDA_IGNORE, LUDA_REPAIR, LUDA_UNKNOWN, LUDA_UPGRADE, LUDA_VERIFY_DRYRUN, osd_device::od_dirent_journal, osd_it_ea::oie_dirent, osd_it_ea_dirent::oied_ino, osd_it_ea_dirent::oied_name, osd_it_ea_dirent::oied_namelen, osd_object::oo_ext_idx_sem, osd_object::oo_hl_head, osd_object::oo_inode, osd_child_dentry_by_inode(), osd_dirent_reinsert(), osd_dot_dotdot_has_space(), osd_ea_fid_set(), osd_get_lma(), osd_id_gen(), osd_iget(), osd_journal_start_sb, osd_ldiskfs_find_entry, osd_obj2dev(), OSD_OII_NOGEN, osd_oti_get(), osd_sb(), osd_thread_info::oti_hlock, osd_thread_info::oti_mdt_attrs, PFID, REMOTE_PARENT_DIR_OID, RETURN, and unlikely.
Referenced by osd_it_ea_rec().
static bool osd_dirent_has_space (struct ldiskfs_dir_entry_2 * de, __u16 namelen, unsigned blocksize, int dot_dotdot) [inline, static]
Definition at line 5475 of file osd_handler.c.
References osd_dot_dotdot_has_space().
Referenced by osd_dirent_reinsert().
static int osd_dirent_reinsert (const struct lu_env * env, handle_t * jh, struct dentry * dentry, const struct lu_fid * fid, struct buffer_head * bh, struct ldiskfs_dir_entry_2 * de, struct htree_lock * hlock, int dot_dotdot) [static]
Definition at line 5489 of file osd_handler.c.
References CDEBUG, D_LFSCK, DFID, dir, ENTRY, fid_cpu_to_be(), osd_fid_pack::fp_area, osd_fid_pack::fp_len, LASSERTF, ll_vfs_dq_init, osd_dirent_has_space(), osd_get_ldiskfs_dirent_param(), osd_ldiskfs_add_entry(), osd_oti_get(), osd_thread_info::oti_ldp, PFID, and RETURN.
Referenced by osd_dirent_check_repair().
static bool osd_dot_dotdot_has_space (struct ldiskfs_dir_entry_2 * de, int dot_dotdot) [inline, static]
Definition at line 5462 of file osd_handler.c.
References LASSERTF.
Referenced by osd_dirent_check_repair(), and osd_dirent_has_space().
static int osd_ea_add_rec (const struct lu_env * env, struct osd_object * pobj, struct inode * cinode, const char * name, const struct lu_fid * fid, struct thandle * th) [static]
It will call the appropriate osd_add* function and return the value, return by respective functions.
Definition at line 4362 of file osd_handler.c.
References __osd_ea_add_rec(), dt_object::do_lu, lu_fid::f_ver, lu_object_fid(), OBD_FAIL_CHECK, OBD_FAIL_FID_INDIR, osd_object::oo_dt, osd_object::oo_ext_idx_sem, osd_object::oo_hl_head, osd_object::oo_inode, osd_add_dot_dotdot(), osd_oti_get(), osd_thread_info::oti_fid, and osd_thread_info::oti_hlock.
Referenced by osd_index_ea_insert().
static int osd_ea_fid_get (const struct lu_env * env, struct osd_object * obj, __u32 ino, struct lu_fid * fid, struct osd_inode_id * id) [static]
Try to read the fid from inode ea into dt_rec.
Parameters:
fid object fid.
Return values:
0 on success
Definition at line 2910 of file osd_handler.c.
References ENTRY, osd_id_gen(), osd_iget_fid(), osd_obj2dev(), OSD_OII_NOGEN, osd_oti_get(), and RETURN.
Referenced by osd_ea_lookup_rec(), and osd_it_ea_rec().
int osd_ea_fid_set (struct osd_thread_info * info, struct inode * inode, const struct lu_fid * fid, __u32 compat, __u32 incompat)
Put the fid into lustre_mdt_attrs, and then place the structure inode's ea.
This fid should not be altered during the life time of the inode.
Return values:
+ve,on success
-ve,on error
FIXME: It is good to have/use ldiskfs_xattr_set_handle() here
Definition at line 2836 of file osd_handler.c.
References __osd_xattr_get(), __osd_xattr_set(), ENTRY, lustre_mdt_attrs::lma_compat, lustre_mdt_attrs::lma_incompat, LMA_OLD_SIZE, lustre_lma_init(), lustre_lma_swab(), OBD_FAIL_CHECK, OBD_FAIL_FID_INLMA, OBD_FAIL_OSD_OST_EA_FID_SET, osd_thread_info::oti_mdt_attrs, osd_thread_info::oti_mdt_attrs_old, osd_thread_info::oti_obj_dentry, RETURN, unlikely, and XATTR_NAME_LMA.
Referenced by osd_create_local_agent_inode(), osd_dirent_check_repair(), osd_ios_scan_one(), osd_lma_self_repair(), osd_mdt_init(), osd_mount(), osd_object_ea_create(), osd_oi_open(), osd_ost_init(), osd_scrub_check_update(), osd_scrub_convert_ff(), osd_scrub_setup(), and osd_seq_load_locked().
static int osd_ea_lookup_rec (const struct lu_env * env, struct osd_object * obj, struct dt_rec * rec, const struct dt_key * key) [static]
Calls ->lookup() to find dentry.
From dentry get inode and read inode's ea to get fid. This is required for interoperability mode (b11826)
Return values:
0,on success
-ve,on error
Definition at line 4603 of file osd_handler.c.
References dir, ENTRY, fid_zero(), GOTO, LASSERT, le32_to_cpu, likely, name, OBD_FAIL_CHECK, OBD_FAIL_FID_LOOKUP, osd_idmap_cache::oic_fid, osd_object::oo_ext_idx_sem, osd_object::oo_hl_head, osd_object::oo_inode, osd_add_oi_cache(), osd_child_dentry_get(), osd_consistency_check(), osd_ea_fid_get(), osd_fail_fid_lookup(), osd_get_fid_from_dentry(), osd_get_pfid_from_linkea(), osd_id_gen(), osd_ldiskfs_find_entry, osd_obj2dev(), OSD_OII_NOGEN, osd_oti_get(), osd_remote_fid(), osd_remote_parent_ino(), osd_thread_info::oti_cache, osd_thread_info::oti_hlock, osd_thread_info::oti_id, and unlikely.
Referenced by osd_index_ea_lookup().
static void __exit osd_exit (void) [static]
Definition at line 6772 of file osd_handler.c.
References class_unregister_type(), lu_kmem_fini(), and LUSTRE_OSD_LDISKFS_NAME.
static int osd_fail_fid_lookup (struct osd_thread_info * oti, struct osd_device * dev, struct osd_idmap_cache * oic, struct lu_fid * fid, __u32 ino) [static]
Definition at line 4483 of file osd_handler.c.
References fid_zero(), lustre_mdt_attrs::lma_self_fid, osd_idmap_cache::oic_fid, osd_idmap_cache::oic_lid, osd_get_lma(), osd_id_gen(), osd_iget(), OSD_OII_NOGEN, osd_thread_info::oti_mdt_attrs, and osd_thread_info::oti_obj_dentry.
Referenced by osd_ea_lookup_rec().
static int osd_fid_alloc (const struct lu_env * env, struct obd_export * exp, struct lu_fid * fid, struct md_op_data * op_data) [static]
Definition at line 6684 of file osd_handler.c.
References obd_export::exp_obd, obd_device::obd_lu_dev, osd_device::od_cl_seq, osd_dev(), and seq_client_alloc_fid().
static void osd_fid_fini (const struct lu_env * env, struct osd_device * osd) [static]
Definition at line 6176 of file osd_handler.c.
References OBD_FREE_PTR, osd_device::od_cl_seq, and seq_client_fini().
Referenced by osd_shutdown().
static int osd_fid_init (const struct lu_env * env, struct osd_device * osd) [static]
Definition at line 6141 of file osd_handler.c.
References ENTRY, lu_client_seq::lcs_space, lu_client_seq::lcs_srv, LUSTRE_SEQ_METADATA, OBD_ALLOC_PTR, OBD_FREE_PTR, osd_device::od_cl_seq, osd_device::od_is_ost, osd_device::od_svname, osd_seq_site(), RETURN, seq_client_init(), seq_server_alloc_meta(), seq_server_site::ss_node_id, seq_server_site::ss_server_seq, and unlikely.
Referenced by osd_prepare().
static int osd_fid_lookup (const struct lu_env * env, struct osd_object * obj, const struct lu_fid * fid, const struct lu_object_conf * conf) [static]
Definition at line 769 of file osd_handler.c.
References DFID, dt_object::do_lu, ENTRY, fid_is_idif(), fid_is_igif(), fid_is_norm(), fid_is_on_ost(), fid_is_sane(), fid_zero(), GOTO, LASSERT, LASSERTF, LCONSOLE_WARN, ldiskfs_pdo, likely, LINVRNT, list_empty(), lu_object::lo_dev, LOC_F_NEW, lu_object_conf::loc_flags, lu_fid_eq(), OBD_FAIL_CHECK, OBD_FAIL_SRV_ENOENT, osd_device::od_noscrub, osd_device::od_scrub, OI_CHECK_FLD, osd_idmap_cache::oic_dev, osd_idmap_cache::oic_fid, osd_idmap_cache::oic_lid, osd_object::oo_compat_dot_created, osd_object::oo_compat_dotdot_created, osd_object::oo_dt, osd_object::oo_hl_head, osd_object::oo_inode, osd_scrub::os_file, osd_scrub::os_inconsistent_items, osd_scrub::os_thread, osd_check_lma(), osd_dev(), osd_iget_check(), osd_invariant, osd_lookup_in_remote_parent(), osd_name(), osd_oi_fid2idx(), osd_oi_lookup(), osd_oii_lookup(), osd_oti_get(), osd_sb(), osd_scrub_start(), osd_thread_info::oti_cache, osd_thread_info::oti_id, PFID, RETURN, scrub_file::sf_oi_bitmap, SS_AUTO_FULL, SS_CLEAR_DRYRUN, SS_CLEAR_FAILOUT, thread_is_running(), and unlikely.
Referenced by osd_object_init().
int osd_fld_lookup (const struct lu_env * env, struct osd_device * osd, u64 seq, struct lu_seq_range * range)
Definition at line 2619 of file osd_handler.c.
Referenced by fid_is_on_ost(), and osd_seq_exists().
static int osd_get_fid_from_dentry (struct ldiskfs_dir_entry_2 * de, struct dt_rec * fid) [inline, static]
Definition at line 3925 of file osd_handler.c.
References fid_is_sane(), osd_fid_unpack(), and unlikely.
Referenced by osd_ea_lookup_rec(), and osd_index_ea_delete().
int osd_get_idif (struct osd_thread_info * info, struct inode * inode, struct dentry * dentry, struct lu_fid * fid)
Return values:
+v,: new filter_fid, does not contain self-fid
0,: filter_fid_old, contains self-fid
-v,: other failure cases
Definition at line 641 of file osd_handler.c.
References __osd_xattr_get(), filter_fid_old::ff_objid, filter_fid_old::ff_seq, le64_to_cpu, ostid_set_id(), ostid_set_seq(), ostid_to_fid(), osd_thread_info::oti_ff, osd_thread_info::oti_ostid, and XATTR_NAME_FID.
Referenced by osd_check_lma(), osd_obj_update_entry(), and osd_scrub_get_fid().
static void osd_get_ldiskfs_dirent_param (struct ldiskfs_dentry_param * param, const struct lu_fid * fid) [static]
ldiskfs supports fid in dirent, it is passed in dentry->d_fsdata.
lustre 1.8 also uses d_fsdata for passing other info to ldiskfs. To have compatilibility with 1.8 ldiskfs driver we need to have magic number at start of fid data. is used only to pass fid from osd to ldiskfs. its inmemory API.
Definition at line 2889 of file osd_handler.c.
References fid_cpu_to_be(), fid_is_namespace_visible(), OBD_FAIL_CHECK, and OBD_FAIL_FID_IGIF.
Referenced by __osd_ea_add_rec(), osd_add_dot_dotdot_internal(), and osd_dirent_reinsert().
int osd_get_lma (struct osd_thread_info * info, struct inode * inode, struct dentry * dentry, struct lustre_mdt_attrs * lma)
Definition at line 356 of file osd_handler.c.
References __osd_xattr_get(), CLASSERT, CWARN, DFID, lustre_mdt_attrs::lma_incompat, LMA_INCOMPAT_SUPP, LMA_OLD_SIZE, lustre_mdt_attrs::lma_self_fid, lustre_lma_swab(), osd_thread_info::oti_mdt_attrs_old, PFID, and XATTR_NAME_LMA.
Referenced by osd_add_to_remote_parent(), osd_attr_set(), osd_delete_from_remote_parent(), osd_dirent_check_repair(), osd_fail_fid_lookup(), osd_iget_fid(), osd_ios_scan_one(), osd_ldiskfs_add_entry(), osd_obj_update_entry(), osd_object_init(), osd_oi_insert(), osd_scrub_get_fid(), and osd_xattr_set().
static int osd_get_pfid_from_linkea (const struct lu_env * env, struct osd_object * obj, struct lu_fid * fid) [static]
Get parent FID from the linkEA.
For a directory which parent resides on remote MDT, to satisfy the local e2fsck, we insert it into the /REMOTE_PARENT_DIR locally. On the other hand, to make the lookup(..) on the directory can return the real parent FID, we append the real parent FID after its ".." name entry in the /REMOTE_PARENT_DIR.
Unfortunately, such PFID-in-dirent cannot be preserved via file-level backup. So after the restore, we cannot get the right parent FID from its ".." name entry in the /REMOTE_PARENT_DIR. Under such case, since we have stored the real parent FID in the directory object's linkEA, we can parse the linkEA for the real parent FID.
Parameters:
[in] env pointer to the thread context
[in] obj pointer to the object to be handled
[out] pointer to the buffer to hold the parent FID
Return values:
0 for getting the real parent FID successfully
negative error number on failure
Definition at line 4540 of file osd_handler.c.
References __osd_xattr_get(), buf, ENTRY, fid_zero(), lu_buf::lb_buf, lu_buf::lb_len, linkea_data::ld_buf, linkea_data::ld_lee, linkea_data::ld_reclen, linkea_entry_unpack(), linkea_first_entry(), linkea_init(), lu_buf_realloc(), osd_object::oo_inode, osd_oti_get(), osd_thread_info::oti_big_buf, osd_thread_info::oti_obj_dentry, RETURN, unlikely, and XATTR_NAME_LINK.
Referenced by osd_ea_lookup_rec(), and osd_it_ea_rec().
static int osd_has_index (const struct osd_object * obj) [static]
Definition at line 145 of file osd_handler.c.
References dt_object::do_index_ops, and osd_object::oo_dt.
Referenced by osd_index_try().
static int osd_health_check (const struct lu_env * env, struct obd_device * obd) [static]
Definition at line 6729 of file osd_handler.c.
References obd_device::obd_lu_dev, osd_device::od_mnt, osd_dev(), and osd_sb().
static int osd_iam_container_init (const struct lu_env * env, struct osd_object * obj, struct osd_directory * dir) [static]
Definition at line 3652 of file osd_handler.c.
References dt_object::do_index_ops, iam_container_fini(), iam_container_init(), iam_container_setup(), osd_directory::od_container, osd_directory::od_descr, osd_object::oo_dt, osd_object::oo_inode, and osd_index_iam_ops.
Referenced by osd_index_try().
static int osd_iam_index_probe (const struct lu_env * env, struct osd_object * o, const struct dt_index_features * feat) [static]
Definition at line 3622 of file osd_handler.c.
References dt_index_features::dif_flags, dt_index_features::dif_keysize_max, dt_index_features::dif_keysize_min, dt_index_features::dif_recsize_max, dt_index_features::dif_recsize_min, dt_directory_features, DT_IND_NONUNQ, DT_IND_UPDATE, DT_IND_VARKEY, DT_IND_VARREC, ergo, iam_container::ic_descr, iam_descr::id_key_size, iam_descr::id_rec_size, LASSERT, osd_directory::od_container, osd_object::oo_dir, and osd_object_is_root().
Referenced by osd_index_try().
static struct osd_idmap_cache* osd_idc_add (const struct lu_env * env, struct osd_device * osd, const struct lu_fid * fid) [static, read]
Definition at line 209 of file osd_handler.c.
References OBD_ALLOC, OBD_FREE, osd_idmap_cache::oic_dev, osd_idmap_cache::oic_fid, osd_idmap_cache::oic_lid, osd_idmap_cache::oic_remote, osd_inode_id::oii_gen, osd_inode_id::oii_ino, OSD_INS_CACHE_SIZE, osd_oti_get(), osd_thread_info::oti_ins_cache, osd_thread_info::oti_ins_cache_size, osd_thread_info::oti_ins_cache_used, and unlikely.
Referenced by osd_idc_find_and_init(), and osd_idc_find_or_init().
static struct osd_idmap_cache* osd_idc_find (const struct lu_env * env, struct osd_device * osd, const struct lu_fid * fid) [static, read]
Definition at line 190 of file osd_handler.c.
References lu_fid_eq(), osd_idmap_cache::oic_dev, osd_idmap_cache::oic_fid, osd_oti_get(), osd_thread_info::oti_ins_cache, and osd_thread_info::oti_ins_cache_used.
Referenced by osd_idc_find_and_init(), osd_idc_find_or_init(), and osd_index_ea_insert().
static int osd_idc_find_and_init (const struct lu_env * env, struct osd_device * osd, struct osd_object * obj) [static]
Definition at line 293 of file osd_handler.c.
References dt_object::do_lu, LASSERT, lu_object_fid(), osd_idmap_cache::oic_lid, osd_inode_id::oii_gen, osd_inode_id::oii_ino, osd_object::oo_dt, osd_object::oo_inode, osd_idc_add(), and osd_idc_find().
Referenced by osd_ah_init(), osd_declare_object_create(), osd_declare_object_destroy(), and osd_object_ea_create().
static struct osd_idmap_cache* osd_idc_find_or_init (const struct lu_env * env, struct osd_device * osd, const struct lu_fid * fid) [static, read]
Definition at line 251 of file osd_handler.c.
References CERROR, LASSERT, osd_idmap_cache::oic_lid, osd_idmap_cache::oic_remote, osd_idc_add(), osd_idc_find(), osd_oi_lookup(), osd_oti_get(), osd_remote_fid(), and unlikely.
Referenced by osd_index_declare_ea_insert(), and osd_index_ea_insert().
struct inode* osd_iget (struct osd_thread_info * info, struct osd_device * dev, struct osd_inode_id * id) [read]
Definition at line 388 of file osd_handler.c.
References CDEBUG, CWARN, D_INODE, LDISKFS_STATE_LUSTRE_DESTROY, osd_inode_id::oii_gen, osd_inode_id::oii_ino, osd_id_gen(), OSD_OII_NOGEN, and osd_sb().
Referenced by osd_consistency_check(), osd_dirent_check_repair(), osd_fail_fid_lookup(), osd_iget_fid(), osd_iit_iget(), osd_obj_map_lookup(), osd_obj_update_entry(), osd_oi_index_create_one(), osd_oi_insert(), and osd_scrub_check_update().
static struct inode* osd_iget_check (struct osd_thread_info * info, struct osd_device * dev, const struct lu_fid * fid, struct osd_inode_id * id, bool cached) [static, read]
Definition at line 510 of file osd_handler.c.
References CDEBUG, D_INODE, ENTRY, GOTO, LASSERTF, LDISKFS_STATE_LUSTRE_DESTROY, OI_CHECK_FLD, osd_inode_id::oii_gen, osd_inode_id::oii_ino, osd_id_gen(), osd_oi_lookup(), OSD_OII_NOGEN, and osd_sb().
Referenced by osd_fid_lookup().
static struct inode* osd_iget_fid (struct osd_thread_info * info, struct osd_device * dev, struct osd_inode_id * id, struct lu_fid * fid) [static, read]
Definition at line 484 of file osd_handler.c.
References lustre_mdt_attrs::lma_self_fid, lu_igif_build(), lu_local_obj_fid(), OSD_FS_ROOT_OID, osd_get_lma(), osd_iget(), osd_sb(), osd_thread_info::oti_mdt_attrs, osd_thread_info::oti_obj_dentry, and unlikely.
Referenced by osd_ea_fid_get(), and osd_process_scheduled_agent_removals().
static int osd_index_declare_ea_delete (const struct lu_env * env, struct dt_object * dt, const struct dt_key * key, struct thandle * handle) [static]
Definition at line 3895 of file osd_handler.c.
References dt_object_remote(), DTO_INDEX_DELETE, DTO_OBJECT_DELETE, ENTRY, i_gid_read(), i_uid_read(), LASSERT, osd_object::oo_inode, osd_declare_inode_qid(), osd_dt_obj(), OSD_OT_DELETE, osd_trans_declare_op(), osd_thandle::ot_handle, and RETURN.
static int osd_index_declare_ea_insert (const struct lu_env * env, struct dt_object * dt, const struct dt_rec * rec, const struct dt_key * key, struct thandle * handle) [static]
Definition at line 4701 of file osd_handler.c.
References credits, dt_object::do_lu, dt_object_remote(), DTO_INDEX_INSERT, DTO_OBJECT_CREATE, ENTRY, i_gid_read(), i_uid_read(), LASSERT, lu_object::lo_dev, osd_idmap_cache::oic_remote, osd_object::oo_inode, osd_declare_inode_qid(), osd_dev(), osd_dt_obj(), osd_idc_find_or_init(), OSD_OT_INSERT, osd_trans_declare_op(), osd_thandle::ot_handle, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, and RETURN.
static int osd_index_declare_iam_delete (const struct lu_env * env, struct dt_object * dt, const struct dt_key * key, struct thandle * handle) [static]
Definition at line 3824 of file osd_handler.c.
References DTO_INDEX_DELETE, LASSERT, OSD_OT_DELETE, osd_trans_declare_op(), osd_thandle::ot_handle, and osd_thandle::ot_super.
static int osd_index_declare_iam_insert (const struct lu_env * env, struct dt_object * dt, const struct dt_rec * rec, const struct dt_key * key, struct thandle * handle) [static]
Definition at line 4147 of file osd_handler.c.
References DTO_INDEX_INSERT, LASSERT, OSD_OT_INSERT, osd_trans_declare_op(), osd_thandle::ot_handle, and osd_thandle::ot_super.
static int osd_index_ea_delete (const struct lu_env * env, struct dt_object * dt, const struct dt_key * key, struct thandle * handle) [static]
Index delete function for interoperability mode (b11826).
It will remove the directory entry added by osd_index_ea_insert(). This entry is needed to maintain name->fid mapping.
Parameters:
key,key i.e. file entry to be deleted
Return values:
0,on success
-ve,on error
Definition at line 3973 of file osd_handler.c.
References CERROR, DFID, dir, dt_object::do_lu, dt_object_exists(), dt_object_remote(), ENTRY, GOTO, LASSERT, le32_to_cpu, LINVRNT, ll_vfs_dq_init, lu_object::lo_dev, osd_object::oo_ext_idx_sem, osd_object::oo_hl_head, osd_object::oo_inode, osd_child_dentry_get(), osd_delete_from_remote_parent(), osd_dev(), osd_dt_obj(), osd_get_fid_from_dentry(), osd_invariant, osd_ldiskfs_find_entry, osd_name(), osd_obj2dev(), OSD_OT_DELETE, osd_oti_get(), osd_remote_fid(), osd_schedule_agent_inode_removal(), osd_trans_exec_check(), osd_trans_exec_op(), osd_thandle::ot_handle, osd_thread_info::oti_fid, osd_thread_info::oti_hlock, PFID, RETURN, and unlikely.
static int osd_index_ea_insert (const struct lu_env * env, struct dt_object * dt, const struct dt_rec * rec, const struct dt_key * key, struct thandle * th, int ignore_quota) [static]
Index add function for interoperability mode (b11826).
It will add the directory entry.This entry is needed to maintain name->fid mapping.
Parameters:
key it is key i.e. file entry to be inserted
rec it is value of given key i.e. fid
Return values:
0,on success
-ve,on error
Definition at line 4766 of file osd_handler.c.
References CDEBUG, CERROR, D_INODE, DFID, dt_object::do_lu, dt_object_exists(), dt_object_remote(), ENTRY, fid_is_sane(), LASSERT, LASSERTF, lu_object::lo_dev, lu_object_fid(), name, OBD_ALLOC_PTR, osd_device::od_mdt_map, osd_idmap_cache::oic_lid, osd_idmap_cache::oic_remote, osd_inode_id::oii_ino, osd_mdobj_map::omm_remote_parent, osd_object::oo_inode, osd_add_to_remote_parent(), osd_create_local_agent_inode(), osd_dev(), osd_dt_obj(), osd_ea_add_rec(), osd_idc_find(), osd_idc_find_or_init(), osd_invariant, osd_name(), OSD_OT_INSERT, osd_oti_get(), osd_sb(), osd_trans_exec_check(), osd_trans_exec_op(), osd_thandle::ot_super, osd_thread_info::oti_inode, PFID, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, RETURN, and unlikely.
static int osd_index_ea_lookup (const struct lu_env * env, struct dt_object * dt, struct dt_rec * rec, const struct dt_key * key) [static]
Index lookup function for interoperability mode (b11826).
Parameters:
key,key i.e. file name to be searched
Return values:
+ve,on success
-ve,on error
Definition at line 6015 of file osd_handler.c.
References ENTRY, LASSERT, LINVRNT, osd_object::oo_inode, osd_dt_obj(), osd_ea_lookup_rec(), osd_invariant, and RETURN.
static void osd_index_fini (struct osd_object * o) [static]
Definition at line 1058 of file osd_handler.c.
References iam_container_fini(), iam_container::ic_object, OBD_FREE_PTR, osd_directory::od_container, osd_object::oo_dir, and osd_object::oo_inode.
Referenced by osd_object_delete().
static int osd_index_iam_delete (const struct lu_env * env, struct dt_object * dt, const struct dt_key * key, struct thandle * handle) [static]
delete a (key, value) pair from index dt specified by key
Parameters:
dt osd index object
key key for index
rec record reference
handle transaction handler
Return values:
0 success
-ve failure
Definition at line 3852 of file osd_handler.c.
References __u64, cpu_to_le64, dt_object::do_lu, dt_key, dt_object_exists(), dt_object_remote(), ENTRY, fid_is_quota(), iam_delete(), iam_container::ic_object, LASSERT, LINVRNT, lu_object_fid(), osd_directory::od_container, osd_object::oo_dir, osd_object::oo_inode, osd_dt_obj(), osd_idx_ipd_get(), osd_invariant, osd_ipd_put(), OSD_OT_DELETE, osd_oti_get(), osd_trans_exec_check(), osd_trans_exec_op(), osd_thandle::ot_handle, osd_thread_info::oti_quota_id, RETURN, and unlikely.
static int osd_index_iam_insert (const struct lu_env * env, struct dt_object * dt, const struct dt_rec * rec, const struct dt_key * key, struct thandle * th, int ignore_quota) [static]
Inserts (key, value) pair in dt index object.
Parameters:
dt osd index object
key key for index
rec record reference
th transaction handler
Return values:
0 success
-ve failure
Definition at line 4177 of file osd_handler.c.
References __u64, cpu_to_le64, dt_object::do_lu, dt_key, dt_object_exists(), dt_object_remote(), ENTRY, fid_is_quota(), iam_insert(), iam_container::ic_object, LASSERT, LINVRNT, lu_object_fid(), osd_directory::od_container, osd_object::oo_dir, osd_object::oo_inode, osd_dt_obj(), osd_idx_ipd_get(), osd_invariant, osd_ipd_put(), OSD_OT_INSERT, osd_oti_get(), osd_quota_pack(), osd_trans_exec_check(), osd_trans_exec_op(), osd_thandle::ot_handle, osd_thread_info::oti_fid, osd_thread_info::oti_ldp, osd_thread_info::oti_quota_id, osd_thread_info::oti_quota_rec, RETURN, and unlikely.
static int osd_index_iam_lookup (const struct lu_env * env, struct dt_object * dt, struct dt_rec * rec, const struct dt_key * key) [static]
Lookup index for key and copy record to rec.
Parameters:
dt osd index object
key key for index
rec record reference
Return values:
+ve success : exact mach
0 return record with key not greater than key
-ve failure
Definition at line 4090 of file osd_handler.c.
References __u64, cpu_to_le64, dt_object::do_lu, dt_key, dt_object_exists(), dt_object_remote(), ENTRY, fid_is_quota(), iam_it_fini(), iam_it_get(), iam_it_init(), iam_it_put(), iam_reccpy(), iam_container::ic_object, iam_iterator::ii_path, iam_path::ip_leaf, LASSERT, LINVRNT, lu_object_fid(), osd_directory::od_container, osd_object::oo_dir, osd_object::oo_inode, osd_dt_obj(), osd_fid_unpack(), osd_idx_ipd_get(), osd_invariant, osd_ipd_put(), osd_oti_get(), osd_quota_unpack(), osd_thread_info::oti_idx_it, osd_thread_info::oti_ldp, osd_thread_info::oti_quota_id, and RETURN.
static int osd_index_try (const struct lu_env * env, struct dt_object * dt, const struct dt_index_features * feat) [static]
Definition at line 3676 of file osd_handler.c.
References dir, dt_object::do_index_ops, dt_object::do_lu, dt_acct_features, dt_directory_features, dt_otable_features, dt_quota_glb_features, FID_SEQ_QUOTA_GLB, LINVRNT, lu_object_fid(), OBD_ALLOC_PTR, OBD_FREE_PTR, osd_object::oo_dir, osd_object::oo_ext_idx_sem, osd_object::oo_guard, osd_object::oo_inode, osd_acct_index_ops, osd_dt_obj(), osd_has_index(), osd_iam_container_init(), osd_iam_index_probe(), osd_index_ea_ops, osd_invariant, osd_object_is_root(), osd_otable_ops, osd_quota_migration(), and unlikely.
static int __init osd_init (void) [static]
Definition at line 6748 of file osd_handler.c.
References BH_DXLock, class_register_type(), CLASSERT, LASSERT, lu_kmem_fini(), lu_kmem_init(), LUSTRE_OSD_LDISKFS_NAME, and osd_oi_mod_init().
Referenced by main().
static void osd_inode_getattr (const struct lu_env * env, struct inode * inode, struct lu_attr * attr) [static]
Definition at line 1930 of file osd_handler.c.
References i_gid_read(), i_uid_read(), lu_attr::la_atime, LA_ATIME, lu_attr::la_blkbits, lu_attr::la_blksize, LA_BLKSIZE, lu_attr::la_blocks, LA_BLOCKS, lu_attr::la_ctime, LA_CTIME, lu_attr::la_flags, LA_FLAGS, lu_attr::la_gid, LA_GID, lu_attr::la_mode, LA_MODE, lu_attr::la_mtime, LA_MTIME, lu_attr::la_nlink, LA_NLINK, lu_attr::la_rdev, LA_RDEV, lu_attr::la_size, LA_SIZE, LA_TYPE, lu_attr::la_uid, LA_UID, lu_attr::la_valid, and LTIME_S.
Referenced by osd_attr_get().
static int osd_inode_setattr (const struct lu_env * env, struct inode * inode, const struct lu_attr * attr) [static]
Definition at line 2123 of file osd_handler.c.
References __u64, i_gid_write(), i_uid_write(), lu_attr::la_atime, LA_ATIME, lu_attr::la_blocks, LA_BLOCKS, lu_attr::la_ctime, LA_CTIME, lu_attr::la_flags, LA_FLAGS, lu_attr::la_gid, LA_GID, lu_attr::la_mode, LA_MODE, lu_attr::la_mtime, LA_MTIME, lu_attr::la_nlink, LA_NLINK, lu_attr::la_rdev, LA_RDEV, lu_attr::la_size, LA_SIZE, lu_attr::la_uid, LA_UID, lu_attr::la_valid, osd_inode_time(), and set_nlink().
Referenced by osd_attr_init(), and osd_attr_set().
static struct timespec* osd_inode_time (const struct lu_env * env, struct inode * inode, __u64 seconds) [static, read]
Definition at line 1918 of file osd_handler.c.
References osd_oti_get(), and osd_thread_info::oti_time.
Referenced by osd_inode_setattr().
static int osd_inode_unlinked (const struct inode * inode) [static]
Definition at line 1078 of file osd_handler.c.
Referenced by osd_object_destroy().
static void osd_it_append_attrs (struct lu_dirent * ent, int len, __u16 type) [inline, static]
Definition at line 5006 of file osd_handler.c.
References cpu_to_le16, cpu_to_le32, DTTOIF, lu_dirent::lde_attrs, lu_dirent::lde_name, luda_type::lt_type, and LUDA_TYPE.
Referenced by osd_it_pack_dirent().
static void osd_it_ea_fini (const struct lu_env * env, struct dt_it * di) [static]
Destroy or finishes iterator context.
Parameters:
di iterator structure to be destroyed
Definition at line 5208 of file osd_handler.c.
References dt_object::do_lu, ENTRY, EXIT, lu_object_put(), OBD_FREE, OBD_SLAB_FREE_PTR, osd_it_ea::oie_buf, osd_it_ea::oie_file, osd_it_ea::oie_obj, osd_object::oo_dt, osd_object::oo_inode, OSD_IT_EA_BUFSIZE, osd_itea_cachep, osd_oti_get(), osd_thread_info::oti_it_ea_buf, osd_thread_info::oti_it_ea_buf_used, and unlikely.
static int osd_it_ea_get (const struct lu_env * env, struct dt_it * di, const struct dt_key * key) [static]
It position the iterator at given key, so that next lookup continues from that key Or it is similar to dio_it->load() but based on a key, rather than file position.
As a special convention, osd_it_ea_get(env, di, "") has to rewind iterator to the beginning.
TODO: Presently return +1 considering it is only used by mdd_dir_is_empty().
Definition at line 5236 of file osd_handler.c.
References ENTRY, LASSERT, osd_it_ea::oie_dirent, osd_it_ea::oie_file, osd_it_ea::oie_it_dirent, osd_it_ea::oie_rd_dirent, and RETURN.
static struct dt_it* osd_it_ea_init (const struct lu_env * env, struct dt_object * dt, __u32 attr) [static, read]
Creates or initializes iterator context.
Return values:
struct osd_it_ea, iterator structure on success
Definition at line 5150 of file osd_handler.c.
References dt_object::do_lu, dt_object_exists(), ENTRY, lu_object_get(), LUDA_64BITHASH, OBD_ALLOC, OBD_SLAB_ALLOC_PTR_GFP, osd_it_ea::oie_buf, osd_it_ea::oie_dentry, osd_it_ea::oie_dirent, osd_it_ea::oie_file, osd_it_ea::oie_it_dirent, osd_it_ea::oie_obj, osd_it_ea::oie_rd_dirent, osd_object::oo_destroyed, osd_object::oo_inode, osd_dt_obj(), OSD_IT_EA_BUFSIZE, osd_itea_cachep, osd_obj2dev(), osd_oti_get(), osd_sb(), osd_thread_info::oti_it_ea_buf, osd_thread_info::oti_it_ea_buf_used, RETURN, set_file_inode, and unlikely.
static struct dt_key* osd_it_ea_key (const struct lu_env * env, const struct dt_it * di) [static, read]
Returns the key at current position from iterator's in memory structure.
Parameters:
di iterator's in memory structure
Return values:
key i.e. struct dt_key on success
Definition at line 5439 of file osd_handler.c.
References dt_key, osd_it_ea::oie_dirent, and osd_it_ea_dirent::oied_name.
static int osd_it_ea_key_size (const struct lu_env * env, const struct dt_it * di) [static]
Returns the key's size at current position from iterator's in memory structure.
Parameters:
di iterator's in memory structure
Return values:
key_size i.e. struct dt_key on success
Definition at line 5454 of file osd_handler.c.
References osd_it_ea::oie_dirent, and osd_it_ea_dirent::oied_namelen.
static int osd_it_ea_load (const struct lu_env * env, const struct dt_it * di, __u64 hash) [static]
It calls osd_ldiskfs_it_fill() which will use ->readdir() to load a directory entry at a time and stored it i inn, in iterator's in-memory data structure.
Parameters:
di struct osd_it_ea, iterator's in memory structure
Return values:
+ve on success
-ve on error
Definition at line 5988 of file osd_handler.c.
References ENTRY, osd_it_ea::oie_file, osd_ldiskfs_it_fill(), and RETURN.
static int osd_it_ea_next (const struct lu_env * env, struct dt_it * di) [static]
It calls osd_ldiskfs_it_fill() which will use ->readdir() to load a directory entry at a time and stored it in iterator's in-memory data structure.
Parameters:
di iterator's in memory structure
Return values:
+ve iterator reached to end
0 iterator not reached to end
-ve on error
Definition at line 5408 of file osd_handler.c.
References cfs_size_round(), ENTRY, ldiskfs_get_htree_eof(), osd_it_ea::oie_dirent, osd_it_ea::oie_file, osd_it_ea::oie_it_dirent, osd_it_ea::oie_rd_dirent, osd_it_ea_dirent::oied_namelen, osd_ldiskfs_it_fill(), and RETURN.
static void osd_it_ea_put (const struct lu_env * env, struct dt_it * di) [static]
Does nothing.
Definition at line 5254 of file osd_handler.c.
static int osd_it_ea_rec (const struct lu_env * env, const struct dt_it * di, struct dt_rec * dtrec, __u32 attr) [inline, static]
Returns the value at current position from iterator's in memory structure.
Parameters:
di struct osd_it_ea, iterator's in memory structure
attr attr requested for dirent.
lde lustre dirent
Return values:
0 no error and
Parameters:
lde has correct lustre dirent.
Return values:
-ve on error
Definition at line 5862 of file osd_handler.c.
References ENTRY, fid_is_sane(), LASSERT, likely, LU_DIRENT_ATTRS_MASK, LUDA_IGNORE, LUDA_UNKNOWN, LUDA_VERIFY, OBD_FAIL_CHECK, OBD_FAIL_FID_LOOKUP, osd_device::od_mdt_map, osd_it_ea::oie_dirent, osd_it_ea::oie_obj, osd_it_ea_dirent::oied_fid, osd_it_ea_dirent::oied_ino, osd_it_ea_dirent::oied_name, osd_it_ea_dirent::oied_namelen, osd_it_ea_dirent::oied_off, osd_it_ea_dirent::oied_type, osd_mdobj_map::omm_remote_parent, osd_object::oo_inode, osd_add_oi_cache(), osd_dirent_check_repair(), osd_ea_fid_get(), osd_get_pfid_from_linkea(), osd_id_gen(), osd_it_pack_dirent(), osd_obj2dev(), OSD_OII_NOGEN, osd_oti_get(), osd_remote_fid(), osd_remote_parent_ino(), osd_thread_info::oti_id, RETURN, and unlikely.
static int osd_it_ea_rec_size (const struct lu_env * env, const struct dt_it * di, __u32 attr) [static]
Returns the record size size at current position.
This function will return record(lu_dirent) size in bytes.
Parameters:
[in] env execution environment
[in] di iterator's in memory structure
[in] attr attribute of the entry, only requires LUDA_TYPE to calculate the lu_dirent size.
Return values:
record size(in bytes & in memory) of the current lu_dirent entry.
Definition at line 5955 of file osd_handler.c.
References lu_dirent_calc_size(), osd_it_ea::oie_dirent, and osd_it_ea_dirent::oied_namelen.
static __u64 osd_it_ea_store (const struct lu_env * env, const struct dt_it * di) [static]
Returns a cookie for current position of the iterator head, so that user can use this cookie to load/start the iterator next time.
Parameters:
di iterator's in memory structure
Return values:
cookie for current position, on success
Definition at line 5971 of file osd_handler.c.
References osd_it_ea::oie_dirent, and osd_it_ea_dirent::oied_off.
static void osd_it_iam_fini (const struct lu_env * env, struct dt_it * di) [static]
free given Iterator.
Definition at line 4905 of file osd_handler.c.
References dt_object::do_lu, iam_it_fini(), lu_object_put(), OBD_FREE_PTR, osd_directory::od_container, osd_it_iam::oi_ipd, osd_it_iam::oi_it, osd_it_iam::oi_obj, osd_object::oo_dir, osd_object::oo_dt, and osd_ipd_put().
static int osd_it_iam_get (const struct lu_env * env, struct dt_it * di, const struct dt_key * key) [static]
Move Iterator to record specified by key.
Parameters:
di osd iterator
key key for index
Return values:
+ve di points to record with least key not larger than key
0 di points to exact matched key
-ve failure
Definition at line 4927 of file osd_handler.c.
References __u64, cpu_to_le64, dt_object::do_lu, dt_key, fid_is_quota(), iam_it_get(), lu_object_fid(), osd_it_iam::oi_it, osd_it_iam::oi_obj, osd_object::oo_dt, osd_oti_get(), and osd_thread_info::oti_quota_id.
static struct dt_it* osd_it_iam_init (const struct lu_env * env, struct dt_object * dt, __u32 unused) [static, read]
Initialize osd Iterator for given osd index object.
Parameters:
dt osd index object
Definition at line 4871 of file osd_handler.c.
References dt_object::do_lu, dt_object_exists(), iam_it_init(), IAM_IT_MOVE, likely, lu_object_get(), OBD_ALLOC_PTR, OBD_FREE_PTR, osd_directory::od_container, osd_it_iam::oi_ipd, osd_it_iam::oi_it, osd_it_iam::oi_obj, osd_object::oo_dir, osd_dt_obj(), and osd_it_ipd_get().
static struct dt_key* osd_it_iam_key (const struct lu_env * env, const struct dt_it * di) [static, read]
Return pointer to the key under iterator.
Definition at line 4975 of file osd_handler.c.
References __u64, dt_object::do_lu, dt_key, fid_is_quota(), iam_it_key_get(), le64_to_cpu, lu_object_fid(), osd_it_iam::oi_it, osd_it_iam::oi_obj, osd_object::oo_dt, osd_oti_get(), and osd_thread_info::oti_quota_id.
static int osd_it_iam_key_size (const struct lu_env * env, const struct dt_it * di) [static]
Return size of key under iterator (in bytes).
Definition at line 4998 of file osd_handler.c.
References iam_it_key_size(), and osd_it_iam::oi_it.
static int osd_it_iam_load (const struct lu_env * env, const struct dt_it * di, __u64 hash) [static]
Restore iterator from cookie.
Parameters:
di osd iterator
hash Iterator location cookie
Return values:
+ve di points to record with least key not larger than key.
0 di points to exact matched key
-ve failure
Definition at line 5115 of file osd_handler.c.
References iam_it_load(), and osd_it_iam::oi_it.
static int osd_it_iam_next (const struct lu_env * env, struct dt_it * di) [static]
Move iterator by one record.
Parameters:
di osd iterator
Return values:
+1 end of container reached
0 success
-ve failure
Definition at line 4964 of file osd_handler.c.
References iam_it_next(), and osd_it_iam::oi_it.
static void osd_it_iam_put (const struct lu_env * env, struct dt_it * di) [static]
Release Iterator.
Parameters:
di osd iterator
Definition at line 4947 of file osd_handler.c.
References iam_it_put(), and osd_it_iam::oi_it.
static int osd_it_iam_rec (const struct lu_env * env, const struct dt_it * di, struct dt_rec * dtrec, __u32 attr) [static]
Return pointer to the record under iterator.
Definition at line 5046 of file osd_handler.c.
References __u64, dt_object::do_lu, ENTRY, fid_is_quota(), iam_it_key_get(), iam_it_key_size(), iam_it_rec_get(), iam_it_store(), iam_reccpy(), iam_iterator::ii_path, iam_path::ip_leaf, lu_object_fid(), LUDA_FID, name, osd_it_iam::oi_it, osd_it_iam::oi_obj, osd_object::oo_dt, osd_object::oo_inode, osd_fid_unpack(), osd_it_pack_dirent(), osd_oti_get(), osd_quota_unpack(), osd_thread_info::oti_fid, and RETURN.
static __u64 osd_it_iam_store (const struct lu_env * env, const struct dt_it * di) [static]
Returns cookie for current Iterator position.
Definition at line 5097 of file osd_handler.c.
References iam_it_store(), and osd_it_iam::oi_it.
static void osd_it_pack_dirent (struct lu_dirent * ent, struct lu_fid * fid, __u64 offset, char * name, __u16 namelen, __u16 type, __u32 attr) [inline, static]
build lu direct from backend fs dirent.
Definition at line 5026 of file osd_handler.c.
References cpu_to_le16, cpu_to_le64, fid_cpu_to_le(), lu_dirent::lde_attrs, lu_dirent::lde_fid, lu_dirent::lde_hash, lu_dirent::lde_name, lu_dirent::lde_namelen, lu_dirent::lde_reclen, lu_dirent_calc_size(), LUDA_FID, and osd_it_append_attrs().
Referenced by osd_it_ea_rec(), and osd_it_iam_rec().
static void osd_key_exit (const struct lu_context * ctx, struct lu_context_key * key, void * data) [static]
Definition at line 6109 of file osd_handler.c.
References LASSERT, osd_thread_info::oti_r_locks, osd_thread_info::oti_txns, and osd_thread_info::oti_w_locks.
static void osd_key_fini (const struct lu_context * ctx, struct lu_context_key * key, void * data) [static]
Definition at line 6085 of file osd_handler.c.
References osd_iobuf::dr_bl_buf, osd_iobuf::dr_pg_buf, LASSERT, lu_buf_free(), OBD_FREE, OBD_FREE_PTR, OSD_IT_EA_BUFSIZE, osd_thread_info::oti_big_buf, osd_thread_info::oti_hlock, osd_thread_info::oti_inode, osd_thread_info::oti_ins_cache, osd_thread_info::oti_ins_cache_size, osd_thread_info::oti_iobuf, and osd_thread_info::oti_it_ea_buf.
static void* osd_key_init (const struct lu_context * ctx, struct lu_context_key * key) [static]
Definition at line 6057 of file osd_handler.c.
References OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, OSD_IT_EA_BUFSIZE, osd_thread_info::oti_env, osd_thread_info::oti_hlock, and osd_thread_info::oti_it_ea_buf.
int osd_ldiskfs_add_entry (struct osd_thread_info * info, handle_t * handle, struct dentry * child, struct inode * inode, struct htree_lock * hlock)
Definition at line 436 of file osd_handler.c.
References CWARN, DFID, FID_LEN, fid_seq_is_mdt0(), lustre_mdt_attrs::lma_self_fid, lu_igif_build(), lu_local_obj_fid(), osd_device::od_is_ost, OSD_FS_ROOT_OID, osd_get_lma(), osd_thread_info::oti_dev, PFID, and unlikely.
Referenced by __osd_ea_add_rec(), osd_add_to_remote_parent(), osd_dirent_reinsert(), osd_obj_add_entry(), osd_obj_map_recover(), and osd_oi_index_create_one().
static int osd_ldiskfs_filldir (void * buf, const char * name, int namelen, loff_t offset, __u64 ino, unsigned d_type) [static]
It is called internally by ->readdir().
It fills the iterator's in-memory data structure with required information i.e. name, namelen, rec_size etc.
Parameters:
buf in which information to be filled in.
name name of the file in given dir
Return values:
0 on success
1 on buffer full
Definition at line 5279 of file osd_handler.c.
References CERROR, cfs_size_round(), dt_object::do_lu, ENTRY, fid_zero(), lu_object::lo_header, lu_object_header::loh_fid, osd_it_ea::oie_buf, osd_it_ea::oie_dirent, osd_it_ea::oie_obj, osd_it_ea::oie_rd_dirent, osd_it_ea_dirent::oied_fid, osd_it_ea_dirent::oied_ino, osd_it_ea_dirent::oied_name, osd_it_ea_dirent::oied_namelen, osd_it_ea_dirent::oied_off, osd_it_ea_dirent::oied_type, osd_object::oo_dt, osd_object::oo_inode, osd_fid_unpack(), OSD_IT_EA_BUFSIZE, osd_obj2dev(), osd_sb(), RETURN, and unlikely.
Referenced by osd_ldiskfs_it_fill().
static int osd_ldiskfs_it_fill (const struct lu_env * env, const struct dt_it * di) [static]
Calls ->readdir() to load a directory entry at a time and stored it in iterator's in-memory data structure.
Parameters:
di iterator's in memory structure
Return values:
0 on success
-ve on error
+1 reach the end of entry
Definition at line 5342 of file osd_handler.c.
References ENTRY, ldiskfs_get_htree_eof(), osd_it_ea::oie_buf, osd_it_ea::oie_dirent, osd_it_ea::oie_file, osd_it_ea::oie_it_dirent, osd_it_ea::oie_obj, osd_it_ea::oie_rd_dirent, osd_object::oo_ext_idx_sem, osd_object::oo_hl_head, osd_object::oo_inode, osd_ldiskfs_filldir(), osd_oti_get(), osd_thread_info::oti_hlock, and RETURN.
Referenced by osd_it_ea_load(), and osd_it_ea_next().
static int osd_lma_self_repair (struct osd_thread_info * info, struct osd_device * osd, struct inode * inode, const struct lu_fid * fid, __u32 compat) [static]
Definition at line 665 of file osd_handler.c.
References CWARN, DTO_XATTR_SET, LASSERT, LDISKFS_HT_MISC, osd_dto_credits_noquota, osd_ea_fid_set(), osd_journal_start_sb, osd_name(), and osd_sb().
Referenced by osd_check_lma().
static int osd_mk_index (struct osd_thread_info * info, struct osd_object * obj, struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof, struct thandle * th) [static]
Definition at line 2373 of file osd_handler.c.
References dt_index_features::dif_flags, dt_index_features::dif_keysize_max, dt_index_features::dif_ptrsize, dt_index_features::dif_recsize_max, dt_object_format::dof_idx, DT_IND_VARKEY, iam_lfix_create(), iam_lvar_create(), lu_attr::la_mode, LASSERT, mode, osd_object::oo_inode, osd_mkfile(), osd_thandle::ot_handle, and dt_object_format::u.
Referenced by osd_create_type_f().
static int osd_mkdir (struct osd_thread_info * info, struct osd_object * obj, struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof, struct thandle * th) [static]
Definition at line 2354 of file osd_handler.c.
References lu_attr::la_mode, LASSERT, mode, osd_mkfile(), osd_thandle::ot_handle, and osd_thandle::ot_super.
Referenced by osd_create_type_f().
static int osd_mkfile (struct osd_thread_info * info, struct osd_object * obj, umode_t mode, struct dt_allocation_hint * hint, struct thandle * th) [static]
Definition at line 2298 of file osd_handler.c.
References dt_allocation_hint::dah_parent, dt_object_remote(), LASSERT, ldiskfs_pdo, LDISKFS_STATE_LUSTRE_NOSCRUB, LINVRNT, osd_object::oo_hl_head, osd_object::oo_inode, osd_dt_obj(), osd_invariant, osd_obj2dev(), osd_sb(), and osd_thandle::ot_handle.
Referenced by osd_mk_index(), osd_mkdir(), osd_mknod(), osd_mkreg(), and osd_mksym().
static int osd_mknod (struct osd_thread_info * info, struct osd_object * obj, struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof, struct thandle * th) [static]
Definition at line 2432 of file osd_handler.c.
References lu_attr::la_mode, lu_attr::la_rdev, LASSERT, LINVRNT, mode, osd_object::oo_inode, osd_invariant, and osd_mkfile().
Referenced by osd_create_type_f().
static int osd_mkreg (struct osd_thread_info * info, struct osd_object * obj, struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof, struct thandle * th) [static]
Definition at line 2410 of file osd_handler.c.
References lu_attr::la_mode, LASSERT, and osd_mkfile().
Referenced by osd_create_type_f().
static int osd_mksym (struct osd_thread_info * info, struct osd_object * obj, struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof, struct thandle * th) [static]
Definition at line 2421 of file osd_handler.c.
References lu_attr::la_mode, LASSERT, and osd_mkfile().
Referenced by osd_create_type_f().
static int osd_mount (const struct lu_env * env, struct osd_device * o, struct lustre_cfg * cfg) [static]
Definition at line 6216 of file osd_handler.c.
References CERROR, CWARN, ENTRY, GOTO, LMAC_NOT_IN_OI, LMD_FLG_NOSCRUB, lu_local_obj_fid(), lustre_cfg_string(), osd_device::od_is_ost, osd_device::od_mnt, osd_device::od_mntdev, osd_device::od_noscrub, osd_ea_fid_set(), OSD_FS_ROOT_OID, osd_oti_get(), osd_sb(), osd_thread_info::oti_fid, RETURN, and strlcat().
Referenced by osd_device_init0(), and osd_process_config().
static int osd_obd_connect (const struct lu_env * env, struct obd_export ** exp, struct obd_device * obd, struct obd_uuid * cluuid, struct obd_connect_data * data, void * localdata) [static]
Definition at line 6599 of file osd_handler.c.
References CDEBUG, class_conn2export(), class_connect(), D_CONFIG, ENTRY, obd_device::obd_lu_dev, osd_device::od_connects, osd_device::od_osfs_lock, osd_dev(), and RETURN.
static int osd_obd_disconnect (struct obd_export * exp) [static]
Definition at line 6627 of file osd_handler.c.
References class_disconnect(), class_manual_cleanup(), ENTRY, obd_export::exp_obd, obd_device::obd_lu_dev, osd_device::od_connects, osd_device::od_osfs_lock, osd_dev(), and RETURN.
static struct lu_object* osd_object_alloc (const struct lu_env * env, const struct lu_object_header * hdr, struct lu_device * d) [static, read]
Definition at line 333 of file osd_handler.c.
References dt_object::do_lu, dt_object::do_ops, dt_object_init(), lu_object::lo_ops, OBD_ALLOC_PTR, osd_object::oo_dt, osd_object::oo_ext_idx_sem, osd_object::oo_guard, osd_object::oo_sem, osd_lu_obj_ops, and osd_obj_ea_ops.
static int osd_object_create (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof, struct thandle * th) [static]
Definition at line 2691 of file osd_handler.c.
References __osd_object_create(), __osd_oi_insert(), dt_object::do_body_ops, dt_object::do_lu, dt_object_exists(), dt_object_remote(), ENTRY, ergo, fid_is_acct(), LASSERT, LINVRNT, lu_object_fid(), osd_object::oo_dt, osd_body_ops, osd_body_ops_new, osd_dt_obj(), osd_invariant, osd_oti_get(), osd_write_locked(), RETURN, and unlikely.
static void osd_object_delete (const struct lu_env * env, struct lu_object * l) [static]
Definition at line 1514 of file osd_handler.c.
References i_gid_read(), i_uid_read(), LINVRNT, lquota_id_info::lqi_id, osd_device::od_quota_slave, osd_object::oo_inode, osd_index_fini(), osd_invariant, osd_obj(), osd_obj2dev(), osd_oti_get(), osd_thread_info::oti_qi, lquota_id::qid_uid, and qsd_op_adjust().
static int osd_object_destroy (const struct lu_env * env, struct dt_object * dt, struct thandle * th) [static]
Definition at line 2773 of file osd_handler.c.
References CERROR, DFID, dt_object::do_lu, ENTRY, fid_is_acct(), LASSERT, LDISKFS_STATE_LUSTRE_DESTROY, ll_dirty_inode, lu_object::lo_header, lu_object_header::loh_flags, lu_object_fid(), LU_OBJECT_HEARD_BANSHEE, lu_object_is_dying(), OI_CHECK_FLD, osd_object::oo_destroyed, osd_object::oo_guard, osd_object::oo_inode, osd_delete_from_remote_parent(), osd_dt_obj(), osd_inode_unlinked(), osd_name(), osd_obj2dev(), osd_oi_delete(), OSD_OT_DESTROY, osd_oti_get(), osd_trans_exec_check(), osd_trans_exec_op(), osd_thandle::ot_handle, osd_thandle::ot_super, PFID, RETURN, and unlikely.
static int osd_object_ea_create (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof, struct thandle * th) [static]
OSD layer object create function for interoperability mode (b11826).
This is mostly similar to osd_object_create(). Only difference being, fid is inserted into inode ea here.
Return values:
0,on success
-ve,on error
Definition at line 3108 of file osd_handler.c.
References __osd_object_create(), __osd_oi_insert(), dt_object::do_body_ops, dt_object::do_lu, dt_object_exists(), dt_object_remote(), ENTRY, ergo, fid_is_acct(), fid_is_idif(), fid_is_on_ost(), fid_to_ostid(), LASSERT, LINVRNT, LMAC_FID_ON_OST, lu_object::lo_dev, lu_object_fid(), osd_device::od_index_in_idif, ost_id::oi, OI_CHECK_FLD, osd_object::oo_dt, osd_object::oo_inode, osd_body_ops, osd_body_ops_new, osd_dev(), osd_dt_obj(), osd_ea_fid_set(), osd_idc_find_and_init(), osd_invariant, osd_obj2dev(), osd_oti_get(), osd_write_locked(), ostid_to_fid(), osd_thread_info::oti_fid, osd_thread_info::oti_ostid, RETURN, and unlikely.
static void osd_object_free (const struct lu_env * env, struct lu_object * l) [static]
Definition at line 1042 of file osd_handler.c.
References dt_object_fini(), LINVRNT, OBD_FREE_PTR, osd_object::oo_dt, osd_object::oo_hl_head, osd_invariant, and osd_obj().
static int osd_object_init (const struct lu_env * env, struct lu_object * l, const struct lu_object_conf * conf) [static]
Definition at line 1001 of file osd_handler.c.
References dt_object::do_body_ops, dt_object::do_ops, fid_is_otable_it(), LINVRNT, lustre_mdt_attrs::lma_incompat, lma_to_lustre_flags(), lu_object::lo_header, lu_object_header::loh_attr, lu_object_header::loh_fid, LOHA_EXISTS, lu_object_fid(), osd_object::oo_dt, osd_object::oo_inode, osd_object::oo_lma_flags, osd_body_ops_new, osd_fid_lookup(), osd_get_lma(), osd_invariant, osd_obj(), osd_obj_otable_it_ops, osd_object_init0(), osd_oti_get(), osd_thread_info::oti_mdt_attrs, and osd_thread_info::oti_obj_dentry.
static void osd_object_init0 (struct osd_object * obj) [static]
Definition at line 989 of file osd_handler.c.
References dt_object::do_body_ops, dt_object::do_lu, LASSERT, lu_object::lo_header, lu_object_header::loh_attr, LOHA_EXISTS, osd_object::oo_dt, osd_object::oo_inode, and osd_body_ops.
Referenced by __osd_object_create(), and osd_object_init().
static int osd_object_invariant (const struct lu_object * l) [static]
Definition at line 150 of file osd_handler.c.
References osd_invariant, and osd_obj().
static int osd_object_print (const struct lu_env * env, void * cookie, lu_printer_t p, const struct lu_object * l) [static]
Definition at line 1565 of file osd_handler.c.
References iam_container::ic_descr, iam_operations::id_name, iam_descr::id_ops, LUSTRE_OSD_LDISKFS_NAME, osd_directory::od_container, osd_object::oo_dir, osd_object::oo_inode, and osd_obj().
static void osd_object_put (const struct lu_env * env, struct osd_object * obj) [inline, static]
Put the osd object once done with it.
Parameters:
obj osd object that needs to be put
Definition at line 4695 of file osd_handler.c.
References dt_object::do_lu, lu_object_put(), and osd_object::oo_dt.
static void osd_object_read_lock (const struct lu_env * env, struct dt_object * dt, unsigned role) [static]
Definition at line 1849 of file osd_handler.c.
References LASSERT, LINVRNT, osd_object::oo_owner, osd_object::oo_sem, osd_dt_obj(), osd_invariant, osd_oti_get(), and osd_thread_info::oti_r_locks.
static void osd_object_read_unlock (const struct lu_env * env, struct dt_object * dt) [static]
Definition at line 1880 of file osd_handler.c.
References LASSERT, LINVRNT, osd_object::oo_sem, osd_dt_obj(), osd_invariant, osd_oti_get(), and osd_thread_info::oti_r_locks.
static int osd_object_ref_add (const struct lu_env * env, struct dt_object * dt, struct thandle * th) [static]
Definition at line 3196 of file osd_handler.c.
References CDEBUG, D_INODE, DFID, dt_object::do_lu, dt_object_exists(), dt_object_remote(), LASSERT, ldiskfs_inc_count(), LINVRNT, ll_dirty_inode, lu_object_fid(), osd_object::oo_destroyed, osd_object::oo_guard, osd_object::oo_inode, osd_dt_obj(), osd_invariant, OSD_OT_REF_ADD, osd_trans_exec_check(), osd_trans_exec_op(), osd_write_locked(), osd_thandle::ot_handle, osd_thandle::ot_super, PFID, set_nlink(), and unlikely.
static int osd_object_ref_del (const struct lu_env * env, struct dt_object * dt, struct thandle * th) [static]
Definition at line 3273 of file osd_handler.c.
References CDEBUG, CDEBUG_LIMIT, D_ERROR, D_INODE, DFID, dt_object::do_lu, dt_object_exists(), dt_object_remote(), fid_is_norm(), LASSERT, ldiskfs_dec_count(), LINVRNT, ll_dirty_inode, lu_object::lo_dev, lu_object_fid(), osd_object::oo_guard, osd_object::oo_inode, osd_dev(), osd_dt_obj(), osd_invariant, osd_name(), OSD_OT_REF_DEL, osd_trans_exec_check(), osd_trans_exec_op(), osd_write_locked(), osd_thandle::ot_handle, osd_thandle::ot_super, and PFID.
static void osd_object_release (const struct lu_env * env, struct lu_object * l) [static]
Definition at line 1551 of file osd_handler.c.
References LBUG, osd_object::oo_destroyed, osd_object::oo_inode, osd_obj(), and unlikely.
static int osd_object_sync (const struct lu_env * env, struct dt_object * dt, __u64 start, __u64 end) [static]
Definition at line 3594 of file osd_handler.c.
References ENTRY, ll_vfs_fsync_range, osd_object::oo_inode, osd_dt_obj(), osd_oti_get(), osd_thread_info::oti_file, osd_thread_info::oti_obj_dentry, RETURN, and set_file_inode.
static int osd_object_version_get (const struct lu_env * env, struct dt_object * dt, dt_obj_version_t * ver) [static]
Definition at line 3324 of file osd_handler.c.
References CDEBUG, D_INODE, LPX64, osd_object::oo_inode, and osd_dt_obj().
Referenced by osd_xattr_get().
static void osd_object_version_set (const struct lu_env * env, struct dt_object * dt, dt_obj_version_t * new_version) [static]
Version is set after all inode operations are finished, so we should mark it dirty here
Definition at line 3440 of file osd_handler.c.
References CDEBUG, D_INODE, ll_dirty_inode, LPX64, osd_object::oo_inode, and osd_dt_obj().
Referenced by osd_xattr_set().
static void osd_object_write_lock (const struct lu_env * env, struct dt_object * dt, unsigned role) [static]
Definition at line 1864 of file osd_handler.c.
References LASSERT, LINVRNT, osd_object::oo_owner, osd_object::oo_sem, osd_dt_obj(), osd_invariant, osd_oti_get(), and osd_thread_info::oti_w_locks.
static int osd_object_write_locked (const struct lu_env * env, struct dt_object * dt) [static]
Definition at line 1908 of file osd_handler.c.
References LINVRNT, osd_object::oo_owner, osd_dt_obj(), and osd_invariant.
static void osd_object_write_unlock (const struct lu_env * env, struct dt_object * dt) [static]
Definition at line 1893 of file osd_handler.c.
References LASSERT, LINVRNT, osd_object::oo_owner, osd_object::oo_sem, osd_dt_obj(), osd_invariant, osd_oti_get(), and osd_thread_info::oti_w_locks.
static int osd_otable_it_attr_get (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr) [static]
Definition at line 3751 of file osd_handler.c.
References lu_attr::la_valid.
static int osd_param_is_not_sane (const struct osd_device * dev, const struct thandle * th) [static]
Definition at line 1171 of file osd_handler.c.
References osd_transaction_size, osd_thandle::ot_credits, and osd_thandle::ot_super.
Referenced by osd_trans_start().
static int osd_prepare (const struct lu_env * env, struct lu_device * pdev, struct lu_device * dev) [static]
Definition at line 6648 of file osd_handler.c.
References dt_device::dd_lu_dev, ENTRY, lu_device::ld_site, lu_site::ls_tgt, lr_server_data::lsd_feature_incompat, lr_server_data::lsd_feature_rocompat, lu_target::lut_lsd, OBD_COMPAT_OST, OBD_ROCOMPAT_IDX_IN_IDIF, osd_device::od_dt_dev, osd_device::od_index_in_idif, osd_device::od_quota_slave, osd_dev(), osd_fid_init(), qsd_prepare(), and RETURN.
static int osd_process_config (const struct lu_env * env, struct lu_device * d, struct lustre_cfg * cfg) [static]
Definition at line 6549 of file osd_handler.c.
References class_process_proc_param(), ENTRY, LASSERT, LCFG_CLEANUP, lustre_cfg::lcfg_command, LCFG_PARAM, LCFG_SETUP, lu_device::ld_site, lu_dev_del_linkage(), osd_device::od_dt_dev, osd_dev(), osd_mount(), osd_shutdown(), PARAM_OSD, PARAM_OST, and RETURN.
static int osd_process_scheduled_agent_removals (const struct lu_env * env, struct osd_device * osd) [static]
Definition at line 3050 of file osd_handler.c.
References INIT_LIST_HEAD, LDISKFS_HT_MISC, list_add(), list_del(), list_for_each_entry_safe, OBD_FREE_PTR, osd_device::od_orphan_list, osd_device::od_osfs_lock, osd_obj_orphan::oor_env, osd_obj_orphan::oor_ino, osd_obj_orphan::oor_list, osd_id_gen(), osd_iget_fid(), osd_journal_start_sb, OSD_OII_NOGEN, osd_oti_get(), osd_remote_fid(), and osd_sb().
Referenced by osd_trans_stop().
static int osd_quota_transfer (struct inode * inode, const struct lu_attr * attr) [static]
Definition at line 2172 of file osd_handler.c.
References CERROR, i_gid_read(), i_uid_read(), lu_attr::la_gid, LA_GID, lu_attr::la_uid, LA_UID, lu_attr::la_valid, ll_vfs_dq_init, ll_vfs_dq_transfer, make_kgid(), and make_kuid().
Referenced by osd_attr_init(), and osd_attr_set().
static int osd_recovery_complete (const struct lu_env * env, struct lu_device * d) [static]
Definition at line 6580 of file osd_handler.c.
References ENTRY, osd_device::od_quota_slave, osd_dev(), qsd_start(), and RETURN.
static int osd_remote_fid (const struct lu_env * env, struct osd_device * osd, const struct lu_fid * fid) [static]
Definition at line 3940 of file osd_handler.c.
References ENTRY, fid_seq_in_fldb(), osd_seq_exists(), osd_seq_site(), RETURN, seq_server_site::ss_server_fld, and unlikely.
Referenced by osd_ea_lookup_rec(), osd_idc_find_or_init(), osd_index_ea_delete(), osd_it_ea_rec(), and osd_process_scheduled_agent_removals().
static int osd_ro (const struct lu_env * env, struct dt_device * d) [static]
Definition at line 1749 of file osd_handler.c.
References CDEBUG, CERROR, D_HA, D_IOCTL, ENTRY, osd_dt_dev(), osd_sb(), and RETURN.
static int osd_root_get (const struct lu_env * env, struct dt_device * dev, struct lu_fid * f) [static]
Definition at line 171 of file osd_handler.c.
References lu_local_obj_fid(), and OSD_FS_ROOT_OID.
static int osd_schedule_agent_inode_removal (const struct lu_env * env, struct osd_thandle * oh, __u32 ino) [static]
when direntry is deleted, we have to take care of possible agent inode referenced by that.
unfortunately we can't do this at that point: iget() within a running transaction leads to deadlock and we better do not call that every delete declaration to save performance. so we put a potention agent inode on a list and process that once the transaction is over. Notice it's not any worse in terms of real orphans as regular object destroy doesn't put inodes on the on-disk orphan list. this should be addressed separately
Definition at line 3027 of file osd_handler.c.
References list_add(), OBD_ALLOC_PTR, osd_device::od_orphan_list, osd_device::od_osfs_lock, osd_obj_orphan::oor_env, osd_obj_orphan::oor_ino, osd_obj_orphan::oor_list, osd_dt_dev(), osd_thandle::ot_remove_agents, osd_thandle::ot_super, and thandle::th_dev.
Referenced by osd_index_ea_delete().
static int osd_seq_exists (const struct lu_env * env, struct osd_device * osd, u64 seq) [static]
Definition at line 1372 of file osd_handler.c.
References CERROR, ENTRY, LASSERT, LPX64, lu_seq_range::lsr_index, osd_fld_lookup(), osd_name(), osd_oti_get(), osd_seq_site(), osd_thread_info::oti_seq_range, RETURN, seq_server_site::ss_node_id, and seq_server_site::ss_server_fld.
Referenced by osd_remote_fid().
static int osd_shutdown (const struct lu_env * env, struct osd_device * o) [static]
Definition at line 6186 of file osd_handler.c.
References ENTRY, osd_device::od_quota_slave, osd_fid_fini(), qsd_fini(), and RETURN.
Referenced by osd_device_fini(), and osd_process_config().
int osd_statfs (const struct lu_env * env, struct dt_device * d, struct obd_statfs * sfs)
Definition at line 1586 of file osd_handler.c.
static int osd_sync (const struct lu_env * env, struct dt_device * d) [static]
Definition at line 1709 of file osd_handler.c.
References CDEBUG, D_CACHE, LUSTRE_OSD_LDISKFS_NAME, osd_dt_dev(), and osd_sb().
Referenced by osd_umount().
static int osd_trans_cb_add (struct thandle * th, struct dt_txn_commit_cb * dcb) [static]
Definition at line 1492 of file osd_handler.c.
References dt_txn_commit_cb::dcb_flags, dt_txn_commit_cb::dcb_func, dt_txn_commit_cb::dcb_linkage, dt_txn_commit_cb::dcb_magic, DCB_TRANS_STOP, LASSERT, list_add(), osd_thandle::ot_commit_dcb_list, osd_thandle::ot_stop_dcb_list, osd_thandle::ot_super, and TRANS_COMMIT_CB_MAGIC.
static void osd_trans_commit_cb (struct super_block * sb, struct ldiskfs_journal_cb_entry * jcb, int error) [static]
Definition at line 1182 of file osd_handler.c.
References CERROR, dt_txn_commit_cb::dcb_func, dt_txn_commit_cb::dcb_linkage, dt_txn_commit_cb::dcb_magic, dt_txn_commit_cb::dcb_name, dt_device::dd_lu_dev, dt_txn_hook_commit(), LASSERT, LASSERTF, lu_device::ld_reference, list_del_init(), list_for_each_entry_safe, lu_context_exit(), lu_context_fini(), lu_device_put(), lu_ref_del_at(), OBD_FREE_PTR, osd_thandle::ot_commit_dcb_list, osd_thandle::ot_dev_link, osd_thandle::ot_handle, osd_thandle::ot_jcb, osd_thandle::ot_super, thandle::th_ctx, thandle::th_dev, and TRANS_COMMIT_CB_MAGIC.
Referenced by osd_trans_stop().
static struct thandle* osd_trans_create (const struct lu_env * env, struct dt_device * d) [static, read]
Definition at line 1216 of file osd_handler.c.
References osd_iobuf::dr_numreqs, ENTRY, INIT_LIST_HEAD, LASSERT, LCT_TX_HANDLE, OBD_ALLOC_GFP, osd_oti_get(), osd_th_alloced, osd_thandle::ot_commit_dcb_list, osd_thandle::ot_credits, osd_thandle::ot_quota_trans, osd_thandle::ot_stop_dcb_list, osd_thandle::ot_super, osd_thread_info::oti_declare_ops, osd_thread_info::oti_declare_ops_cred, osd_thread_info::oti_declare_ops_used, osd_thread_info::oti_iobuf, osd_thread_info::oti_quota_trans, RETURN, thandle::th_dev, thandle::th_result, and thandle::th_tags.
void osd_trans_dump_creds (const struct lu_env * env, struct thandle * th)
Definition at line 1252 of file osd_handler.c.
References CWARN, LASSERT, OSD_OT_ATTR_SET, OSD_OT_CREATE, OSD_OT_DELETE, OSD_OT_DESTROY, OSD_OT_INSERT, OSD_OT_PUNCH, OSD_OT_QUOTA, OSD_OT_REF_ADD, OSD_OT_REF_DEL, OSD_OT_WRITE, OSD_OT_XATTR_SET, osd_oti_get(), osd_thandle::ot_super, osd_thread_info::oti_declare_ops, osd_thread_info::oti_declare_ops_cred, and osd_thread_info::oti_declare_ops_used.
Referenced by osd_trans_exec_check(), osd_trans_exec_op(), and osd_trans_start().
static int osd_trans_start (const struct lu_env * env, struct dt_device * d, struct thandle * th) [static]
Definition at line 1303 of file osd_handler.c.
References dt_device::dd_lu_dev, dt_txn_hook_start(), ENTRY, GOTO, LASSERT, lu_device::ld_reference, LDISKFS_HT_MISC, libcfs_debug_dumpstack, lu_context_enter(), lu_context_init(), lu_device_get(), lu_ref_add_at(), osd_dt_dev(), osd_journal_start_sb, osd_oti_get(), osd_param_is_not_sane(), osd_sb(), osd_th_started, osd_trans_dump_creds(), osd_transaction_size, osd_thandle::ot_credits, osd_thandle::ot_dev_link, osd_thandle::ot_handle, osd_thandle::ot_super, osd_thread_info::oti_txns, RETURN, thandle::th_ctx, thandle::th_tags, and unlikely.
static int osd_trans_stop (const struct lu_env * env, struct dt_device * dt, struct thandle * th) [static]
Definition at line 1413 of file osd_handler.c.
References CERROR, osd_iobuf::dr_error, osd_iobuf::dr_numreqs, osd_iobuf::dr_wait, dt_txn_hook_stop(), ENTRY, LASSERT, OBD_FREE_PTR, osd_device::od_quota_slave, OSD_CHECK_SLOW_TH, osd_dt_dev(), osd_fini_iobuf(), osd_name(), osd_oti_get(), osd_process_scheduled_agent_removals(), osd_trans_commit_cb(), osd_trans_stop_cb(), osd_thandle::ot_handle, osd_thandle::ot_jcb, osd_thandle::ot_quota_trans, osd_thandle::ot_remove_agents, osd_thread_info::oti_ins_cache_used, osd_thread_info::oti_iobuf, osd_thread_info::oti_txns, qsd_op_end(), RETURN, thandle::th_dev, thandle::th_result, thandle::th_sync, and unlikely.
static void osd_trans_stop_cb (struct osd_thandle * oth, int result) [static]
Definition at line 1394 of file osd_handler.c.
References dt_txn_commit_cb::dcb_func, dt_txn_commit_cb::dcb_linkage, dt_txn_commit_cb::dcb_magic, dt_txn_commit_cb::dcb_name, LASSERTF, list_del_init(), list_for_each_entry_safe, osd_thandle::ot_stop_dcb_list, osd_thandle::ot_super, and TRANS_COMMIT_CB_MAGIC.
Referenced by osd_trans_stop().
static void osd_umount (const struct lu_env * env, struct osd_device * o) [static]
Definition at line 6201 of file osd_handler.c.
References ENTRY, EXIT, osd_device::od_dt_dev, osd_device::od_mnt, osd_sb(), and osd_sync().
Referenced by osd_device_fini(), and osd_device_init0().
static int osd_write_locked (const struct lu_env * env, struct osd_object * o) [static]
Definition at line 162 of file osd_handler.c.
References osd_object::oo_owner, osd_oti_get(), and osd_thread_info::oti_w_locks.
Referenced by osd_object_create(), osd_object_ea_create(), osd_object_ref_add(), and osd_object_ref_del().
static int osd_xattr_del (const struct lu_env * env, struct dt_object * dt, const char * name, struct thandle * handle) [static]
Definition at line 3567 of file osd_handler.c.
References dt_object_exists(), dt_object_remote(), LASSERT, ll_vfs_dq_init, osd_object::oo_inode, osd_dt_obj(), OSD_OT_XATTR_SET, osd_oti_get(), osd_trans_exec_check(), osd_trans_exec_op(), and osd_thread_info::oti_obj_dentry.
static int osd_xattr_get (const struct lu_env * env, struct dt_object * dt, struct lu_buf * buf, const char * name) [static]
Definition at line 3338 of file osd_handler.c.
References __osd_xattr_get(), dt_object_exists(), dt_object_remote(), LASSERT, lu_buf::lb_buf, lu_buf::lb_len, osd_object::oo_inode, osd_dt_obj(), osd_object_version_get(), osd_oti_get(), osd_thread_info::oti_obj_dentry, and XATTR_NAME_VERSION.
static int osd_xattr_list (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf) [static]
Definition at line 3520 of file osd_handler.c.
References dt_object_exists(), dt_object_remote(), LASSERT, lu_buf::lb_buf, lu_buf::lb_len, osd_object::oo_inode, osd_dt_obj(), osd_oti_get(), and osd_thread_info::oti_obj_dentry.
static int osd_xattr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, const char * name, int fl, struct thandle * handle) [static]
Definition at line 3458 of file osd_handler.c.
References __osd_xattr_set(), CDEBUG, D_INODE, DFID, dt_object::do_lu, ENTRY, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lustre_mdt_attrs::lma_incompat, LMAI_STRIPED, lu_object_fid(), LU_XATTR_CREATE, LU_XATTR_REPLACE, lustre_lma_swab(), OBD_FAIL_CHECK, OBD_FAIL_LFSCK_LINKEA_OVERFLOW, osd_object::oo_inode, osd_dt_obj(), osd_get_lma(), osd_object_version_set(), OSD_OT_XATTR_SET, osd_oti_get(), osd_trans_exec_check(), osd_trans_exec_op(), osd_thread_info::oti_mdt_attrs, osd_thread_info::oti_obj_dentry, PFID, RETURN, XATTR_NAME_LINK, XATTR_NAME_LMA, XATTR_NAME_LMV, and XATTR_NAME_VERSION.
Variable Documentation
const char dot[] = "." [static]
Definition at line 115 of file osd_handler.c.
const char dotdot[] = ".." [static]
Definition at line 116 of file osd_handler.c.
struct kmem_cache* dynlock_cachep
Definition at line 94 of file osd_handler.c.
Referenced by dynlock_lock(), and dynlock_unlock().
struct lu_kmem_descr ldiskfs_caches[] [static]
Initial value:
 {
        {
                .ckd_cache = &dynlock_cachep,
                .ckd_name  = "dynlock_cache",
                .ckd_size  = sizeof(struct dynlock_handle)
        },
        {
                .ckd_cache = &osd_itea_cachep,
                .ckd_name  = "osd_itea_cache",
                .ckd_size  = sizeof(struct osd_it_ea)
        },
        {
                .ckd_cache = NULL
        }
}
Definition at line 99 of file osd_handler.c.
int ldiskfs_pdo = 1
Definition at line 85 of file osd_handler.c.
Referenced by osd_fid_lookup(), and osd_mkfile().
int ldiskfs_track_declares_assert
Definition at line 89 of file osd_handler.c.
struct lu_device_type osd_device_type [static]
Initial value:
 {
        .ldt_tags     = LU_DEVICE_DT,
        .ldt_name     = LUSTRE_OSD_LDISKFS_NAME,
        .ldt_ops      = &osd_device_type_ops,
        .ldt_ctx_tags = LCT_LOCAL,
}
Definition at line 6722 of file osd_handler.c.
struct lu_device_type_operations osd_device_type_ops [static]
Initial value:
 {
        .ldto_init = osd_type_init,
        .ldto_fini = osd_type_fini,
        .ldto_start = osd_type_start,
        .ldto_stop  = osd_type_stop,
        .ldto_device_alloc = osd_device_alloc,
        .ldto_device_free  = osd_device_free,
        .ldto_device_init    = osd_device_init,
        .ldto_device_fini    = osd_device_fini
}
Definition at line 6708 of file osd_handler.c.
struct dt_device_operations osd_dt_ops [static]
Initial value:
 {
        .dt_root_get       = osd_root_get,
        .dt_statfs         = osd_statfs,
        .dt_trans_create   = osd_trans_create,
        .dt_trans_start    = osd_trans_start,
        .dt_trans_stop     = osd_trans_stop,
        .dt_trans_cb_add   = osd_trans_cb_add,
        .dt_conf_get       = osd_conf_get,
        .dt_sync           = osd_sync,
        .dt_ro             = osd_ro,
        .dt_commit_async   = osd_commit_async,
}
Definition at line 1836 of file osd_handler.c.
const int osd_dto_credits_noquota[DTO_NR]
Initial value:
 {
        [DTO_INDEX_INSERT]  = 16,
        [DTO_INDEX_DELETE]  = 1,
        [DTO_INDEX_UPDATE]  = 16,
        [DTO_OBJECT_CREATE] = 4,
        [DTO_OBJECT_DELETE] = 4,
        [DTO_ATTR_SET_BASE] = 1,
        [DTO_XATTR_SET]     = 14,
        [DTO_WRITE_BASE]    = 3,
        [DTO_WRITE_BLOCK]   = 14,
        [DTO_ATTR_SET_CHOWN] = 0
}
Note: we do not count into QUOTA here.
If we mount with --data_journal we may need more.
Definition at line 1782 of file osd_handler.c.
Referenced by osd_declare_punch(), osd_lma_self_repair(), osd_obj_map_recover(), osd_scrub_convert_ff(), osd_scrub_file_store(), and osd_scrub_refresh_mapping().
static struct dt_index_operations osd_index_ea_ops [static, read]
Initial value:
 {
        .dio_lookup         = osd_index_ea_lookup,
        .dio_declare_insert = osd_index_declare_ea_insert,
        .dio_insert         = osd_index_ea_insert,
        .dio_declare_delete = osd_index_declare_ea_delete,
        .dio_delete         = osd_index_ea_delete,
        .dio_it     = {
                .init     = osd_it_ea_init,
                .fini     = osd_it_ea_fini,
                .get      = osd_it_ea_get,
                .put      = osd_it_ea_put,
                .next     = osd_it_ea_next,
                .key      = osd_it_ea_key,
                .key_size = osd_it_ea_key_size,
                .rec      = osd_it_ea_rec,
                .rec_size = osd_it_ea_rec_size,
                .store    = osd_it_ea_store,
                .load     = osd_it_ea_load
        }
}
Index and Iterator operations for interoperability mode (i.e.
to run 2.0 mds on 1.8 disk) (b11826)
Definition at line 124 of file osd_handler.c.
Referenced by osd_index_try().
static struct dt_index_operations osd_index_iam_ops [static, read]
Initial value:
 {
        .dio_lookup         = osd_index_iam_lookup,
        .dio_declare_insert = osd_index_declare_iam_insert,
        .dio_insert         = osd_index_iam_insert,
        .dio_declare_delete = osd_index_declare_iam_delete,
        .dio_delete         = osd_index_iam_delete,
        .dio_it     = {
                .init     = osd_it_iam_init,
                .fini     = osd_it_iam_fini,
                .get      = osd_it_iam_get,
                .put      = osd_it_iam_put,
                .next     = osd_it_iam_next,
                .key      = osd_it_iam_key,
                .key_size = osd_it_iam_key_size,
                .rec      = osd_it_iam_rec,
                .store    = osd_it_iam_store,
                .load     = osd_it_iam_load
        }
}
Definition at line 123 of file osd_handler.c.
Referenced by osd_iam_container_init().
struct kmem_cache* osd_itea_cachep
Definition at line 97 of file osd_handler.c.
Referenced by osd_it_ea_fini(), and osd_it_ea_init().
struct lu_context_key osd_key [read]
Initial value:
 {
        .lct_tags = LCT_DT_THREAD | LCT_MD_THREAD | LCT_MG_THREAD | LCT_LOCAL,
        .lct_init = osd_key_init,
        .lct_fini = osd_key_fini,
        .lct_exit = osd_key_exit
}
Definition at line 6122 of file osd_handler.c.
Referenced by osd_oti_get(), osd_type_fini(), and osd_type_init().
static struct lu_object_operations osd_lu_obj_ops [static, read]
Initial value:
 {
        .loo_object_init      = osd_object_init,
        .loo_object_delete    = osd_object_delete,
        .loo_object_release   = osd_object_release,
        .loo_object_free      = osd_object_free,
        .loo_object_print     = osd_object_print,
        .loo_object_invariant = osd_object_invariant
}
Definition at line 119 of file osd_handler.c.
Referenced by osd_object_alloc().
struct lu_device_operations osd_lu_ops
Initial value:
 {
        .ldo_object_alloc      = osd_object_alloc,
        .ldo_process_config    = osd_process_config,
        .ldo_recovery_complete = osd_recovery_complete,
        .ldo_prepare           = osd_prepare,
}
Definition at line 6701 of file osd_handler.c.
Referenced by lu_device_is_osd(), and osd_device_init0().
struct obd_ops osd_obd_device_ops [static]
Initial value:
 {
        .o_owner = THIS_MODULE,
        .o_connect      = osd_obd_connect,
        .o_disconnect   = osd_obd_disconnect,
        .o_fid_alloc    = osd_fid_alloc,
        .o_health_check = osd_health_check,
}
Definition at line 6740 of file osd_handler.c.
static struct dt_object_operations osd_obj_ea_ops [static, read]
Initial value:
 {
        .do_read_lock         = osd_object_read_lock,
        .do_write_lock        = osd_object_write_lock,
        .do_read_unlock       = osd_object_read_unlock,
        .do_write_unlock      = osd_object_write_unlock,
        .do_write_locked      = osd_object_write_locked,
        .do_attr_get          = osd_attr_get,
        .do_declare_attr_set  = osd_declare_attr_set,
        .do_attr_set          = osd_attr_set,
        .do_ah_init           = osd_ah_init,
        .do_declare_create    = osd_declare_object_create,
        .do_create            = osd_object_ea_create,
        .do_declare_destroy   = osd_declare_object_destroy,
        .do_destroy           = osd_object_destroy,
        .do_index_try         = osd_index_try,
        .do_declare_ref_add   = osd_declare_object_ref_add,
        .do_ref_add           = osd_object_ref_add,
        .do_declare_ref_del   = osd_declare_object_ref_del,
        .do_ref_del           = osd_object_ref_del,
        .do_xattr_get         = osd_xattr_get,
        .do_declare_xattr_set = osd_declare_xattr_set,
        .do_xattr_set         = osd_xattr_set,
        .do_declare_xattr_del = osd_declare_xattr_del,
        .do_xattr_del         = osd_xattr_del,
        .do_xattr_list        = osd_xattr_list,
        .do_object_sync       = osd_object_sync,
}
dt_object_operations for interoperability mode (i.e.
to run 2.0 mds on 1.8 disk) (b11826)
Definition at line 121 of file osd_handler.c.
Referenced by osd_object_alloc().
static struct dt_object_operations osd_obj_ops [static, read]
Initial value:
 {
        .do_read_lock         = osd_object_read_lock,
        .do_write_lock        = osd_object_write_lock,
        .do_read_unlock       = osd_object_read_unlock,
        .do_write_unlock      = osd_object_write_unlock,
        .do_write_locked      = osd_object_write_locked,
        .do_attr_get          = osd_attr_get,
        .do_declare_attr_set  = osd_declare_attr_set,
        .do_attr_set          = osd_attr_set,
        .do_ah_init           = osd_ah_init,
        .do_declare_create    = osd_declare_object_create,
        .do_create            = osd_object_create,
        .do_declare_destroy   = osd_declare_object_destroy,
        .do_destroy           = osd_object_destroy,
        .do_index_try         = osd_index_try,
        .do_declare_ref_add   = osd_declare_object_ref_add,
        .do_ref_add           = osd_object_ref_add,
        .do_declare_ref_del   = osd_declare_object_ref_del,
        .do_ref_del           = osd_object_ref_del,
        .do_xattr_get         = osd_xattr_get,
        .do_declare_xattr_set = osd_declare_xattr_set,
        .do_xattr_set         = osd_xattr_set,
        .do_declare_xattr_del = osd_declare_xattr_del,
        .do_xattr_del         = osd_xattr_del,
        .do_xattr_list        = osd_xattr_list,
        .do_object_sync       = osd_object_sync,
}
Definition at line 120 of file osd_handler.c.
static struct dt_object_operations osd_obj_otable_it_ops [static, read]
Initial value:
 {
        .do_attr_get    = osd_otable_it_attr_get,
        .do_index_try   = osd_index_try,
}
Definition at line 122 of file osd_handler.c.
Referenced by osd_object_init().
int osd_trans_declare_op2rb[]
Initial value:
 {
        [OSD_OT_ATTR_SET]       = OSD_OT_ATTR_SET,
        [OSD_OT_PUNCH]          = OSD_OT_MAX,
        [OSD_OT_XATTR_SET]      = OSD_OT_XATTR_SET,
        [OSD_OT_CREATE]         = OSD_OT_DESTROY,
        [OSD_OT_DESTROY]        = OSD_OT_CREATE,
        [OSD_OT_REF_ADD]        = OSD_OT_REF_DEL,
        [OSD_OT_REF_DEL]        = OSD_OT_REF_ADD,
        [OSD_OT_WRITE]          = OSD_OT_WRITE,
        [OSD_OT_INSERT]         = OSD_OT_DELETE,
        [OSD_OT_DELETE]         = OSD_OT_INSERT,
        [OSD_OT_QUOTA]          = OSD_OT_MAX,
}
Definition at line 131 of file osd_handler.c.
const char remote_obj_dir[] = "REM_OBJ_DIR" [static]
Definition at line 117 of file osd_handler.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.