Lustre: lustre/osd-ldiskfs/osd_internal.h File Reference
lustre/osd-ldiskfs/osd_internal.h File Reference
#include <linux/mutex.h>
#include <linux/rwsem.h>
#include <linux/dcache.h>
#include <linux/dirent.h>
#include <linux/statfs.h>
#include <ldiskfs/ldiskfs.h>
#include <ldiskfs/ldiskfs_jbd2.h>
#include <obd.h>
#include <obd_class.h>
#include <lustre_disk.h>
#include <dt_object.h>
#include <lustre_quota.h>
#include "osd_oi.h"
#include "osd_iam.h"
#include "osd_scrub.h"
#include "osd_quota_fmt.h"
Data Structures
struct osd_directory
struct osd_oi
struct osd_object
struct osd_obj_seq
struct osd_obj_map
struct osd_mdobj
struct osd_mdobj_map
struct osd_inconsistent_item
struct osd_otable_cache
struct osd_otable_it
struct osd_obj_orphan
struct osd_device
struct osd_thandle
struct osd_fid_pack
Storage representation for fids.
struct osd_it_ea_dirent
struct osd_it_ea
This is iterator's in-memory data structure in interoperability mode (i.e.
struct osd_it_iam
Iterator's in-memory data structure for IAM mode.
struct osd_quota_leaf
struct osd_it_quota
Iterator's in-memory data structure for quota file.
struct osd_iobuf
struct osd_thread_info
Defines
#define OSD_COUNTERS (0)
#define LDISKFS_STATE_LUSTRE_NOSCRUB 31
#define LDISKFS_STATE_LUSTRE_DESTROY 30
#define OSD_THANDLE_STATS (0)
Enable thandle usage statistics.
#define MAX_OBJID_GROUP (FID_SEQ_ECHO + 1)
#define OBJECTS "OBJECTS"
#define ADMIN_USR "admin_quotafile_v2.usr"
#define ADMIN_GRP "admin_quotafile_v2.grp"
#define OSD_STATFS_RESERVED (1ULL << 23)
#define OSD_STATFS_RESERVED_SHIFT (7)
#define OSD_OTABLE_IT_CACHE_SIZE 64
#define OSD_OTABLE_IT_CACHE_MASK (~(OSD_OTABLE_IT_CACHE_SIZE - 1))
#define FULL_SCRUB_THRESHOLD_RATE_DEFAULT 60
#define OSD_MAX_UGID_CNT 10
#define OSD_IT_EA_BUFSIZE (PAGE_CACHE_SIZE + PAGE_CACHE_SIZE/4)
as osd_it_ea_dirent (in memory dirent struct for osd) is greater than lu_dirent struct.
#define MAX_BLOCKS_PER_PAGE (PAGE_CACHE_SIZE / 512)
#define OSD_INS_CACHE_SIZE 8
#define OSD_FID_REC_SZ 32
#define LDISKFS_HT_MISC 0
#define osd_journal_start_sb(sb, type, nblock) ldiskfs_journal_start_sb(sb, nblock)
#define osd_ldiskfs_find_entry(dir, name, de, inlined, lock) __ldiskfs_find_entry(dir, name, de, lock)
#define osd_journal_start(inode, type, nblocks) ldiskfs_journal_start(inode, nblocks)
#define osd_transaction_size(dev) (osd_journal(dev)->j_max_transaction_buffers)
#define OSD_INVARIANT_CHECKS (0)
#define osd_invariant(obj) (1)
#define OSD_MAX_CACHE_SIZE OBD_OBJECT_EOF
Enumerations
enum osd_full_scrub_ratio { OFSR_DIRECTLY = 0, OFSR_NEVER = 1, OFSR_DEFAULT = 10000 }
enum {
OSD_OT_ATTR_SET = 0, OSD_OT_PUNCH = 1, OSD_OT_XATTR_SET = 2, OSD_OT_CREATE = 3,
OSD_OT_DESTROY = 4, OSD_OT_REF_ADD = 5, OSD_OT_REF_DEL = 6, OSD_OT_WRITE = 7,
OSD_OT_INSERT = 8, OSD_OT_DELETE = 9, OSD_OT_QUOTA = 10, OSD_OT_MAX = 11
}
enum dt_txn_op {
DTO_INDEX_INSERT, DTO_INDEX_DELETE, DTO_INDEX_UPDATE, DTO_OBJECT_CREATE,
DTO_OBJECT_DELETE, DTO_ATTR_SET_BASE, DTO_XATTR_SET, DTO_WRITE_BASE,
DTO_WRITE_BLOCK, DTO_ATTR_SET_CHOWN, DTO_NR
}
Basic transaction credit op.
Functions
int osd_ldiskfs_add_entry (struct osd_thread_info *info, handle_t *handle, struct dentry *child, struct inode *inode, struct htree_lock *hlock)
static int __osd_xattr_get (struct inode *inode, struct dentry *dentry, const char *name, void *buf, int len)
static int __osd_xattr_set (struct osd_thread_info *info, struct inode *inode, const char *name, const void *buf, int buflen, int fl)
int osd_statfs (const struct lu_env *env, struct dt_device *dev, struct obd_statfs *sfs)
struct inode * osd_iget (struct osd_thread_info *info, struct osd_device *dev, struct osd_inode_id *id)
int osd_ea_fid_set (struct osd_thread_info *info, struct inode *inode, const struct lu_fid *fid, __u32 compat, __u32 incompat)
Put the fid into lustre_mdt_attrs, and then place the structure inode's ea.
int osd_get_lma (struct osd_thread_info *info, struct inode *inode, struct dentry *dentry, struct lustre_mdt_attrs *lma)
void osd_add_oi_cache (struct osd_thread_info *info, struct osd_device *osd, struct osd_inode_id *id, const struct lu_fid *fid)
int osd_get_idif (struct osd_thread_info *info, struct inode *inode, struct dentry *dentry, struct lu_fid *fid)
int osd_obj_map_init (const struct lu_env *env, struct osd_device *osd)
void osd_obj_map_fini (struct osd_device *dev)
int osd_obj_map_lookup (struct osd_thread_info *info, struct osd_device *osd, const struct lu_fid *fid, struct osd_inode_id *id)
int osd_obj_map_insert (struct osd_thread_info *info, struct osd_device *osd, const struct lu_fid *fid, const struct osd_inode_id *id, handle_t *th)
int osd_obj_map_delete (struct osd_thread_info *info, struct osd_device *osd, const struct lu_fid *fid, handle_t *th)
int osd_obj_map_update (struct osd_thread_info *info, struct osd_device *osd, const struct lu_fid *fid, const struct osd_inode_id *id, handle_t *th)
int osd_obj_map_recover (struct osd_thread_info *info, struct osd_device *osd, struct inode *src_parent, struct dentry *src_child, const struct lu_fid *fid)
int osd_obj_spec_lookup (struct osd_thread_info *info, struct osd_device *osd, const struct lu_fid *fid, struct osd_inode_id *id)
int osd_obj_spec_insert (struct osd_thread_info *info, struct osd_device *osd, const struct lu_fid *fid, const struct osd_inode_id *id, handle_t *th)
int osd_obj_spec_update (struct osd_thread_info *info, struct osd_device *osd, const struct lu_fid *fid, const struct osd_inode_id *id, handle_t *th)
void osd_scrub_file_reset (struct osd_scrub *scrub, __u8 *uuid, __u64 flags)
int osd_scrub_file_store (struct osd_scrub *scrub)
char * osd_lf_fid2name (const struct lu_fid *fid)
int osd_scrub_start (struct osd_device *dev, __u32 flags)
int osd_scrub_setup (const struct lu_env *env, struct osd_device *dev)
void osd_scrub_cleanup (const struct lu_env *env, struct osd_device *dev)
int osd_oii_insert (struct osd_device *dev, struct osd_idmap_cache *oic, int insert)
int osd_oii_lookup (struct osd_device *dev, const struct lu_fid *fid, struct osd_inode_id *id)
int osd_scrub_dump (struct seq_file *m, struct osd_device *dev)
int osd_fld_lookup (const struct lu_env *env, struct osd_device *osd, u64 seq, struct lu_seq_range *range)
Lookup the target index/flags of the fid, so it will know where the object is located (tgt index) and it is MDT or OST object.
int osd_delete_from_remote_parent (const struct lu_env *env, struct osd_device *osd, struct osd_object *obj, struct osd_thandle *oh)
int osd_add_to_remote_parent (const struct lu_env *env, struct osd_device *osd, struct osd_object *obj, struct osd_thandle *oh)
int osd_lookup_in_remote_parent (struct osd_thread_info *oti, struct osd_device *osd, const struct lu_fid *fid, struct osd_inode_id *id)
int osd_ost_seq_exists (struct osd_thread_info *info, struct osd_device *osd, __u64 seq)
int walk_tree_dqentry (const struct lu_env *env, struct osd_object *obj, int type, uint blk, int depth, uint index, struct osd_it_quota *it)
Search from index within the tree block blk, and fill the it with the first valid entry.
int walk_block_dqentry (const struct lu_env *env, struct osd_object *obj, int type, uint blk, uint index, struct osd_it_quota *it)
Search from index within the leaf block blk, and fill the it with the first valid entry.
loff_t find_tree_dqentry (const struct lu_env *env, struct osd_object *obj, int type, qid_t dqid, uint blk, int depth, struct osd_it_quota *it)
Find entry for given dqid in the tree block blk.
int osd_declare_qid (const struct lu_env *env, struct osd_thandle *oh, struct lquota_id_info *qi, struct osd_object *obj, bool enforce, int *flags)
Reserve journal credits for quota files update first, then call ->op_begin() to perform quota enforcement.
int osd_declare_inode_qid (const struct lu_env *env, qid_t uid, qid_t gid, long long space, struct osd_thandle *oh, struct osd_object *obj, bool is_blk, int *flags, bool force)
Wrapper for osd_declare_qid().
struct dt_rec * osd_quota_pack (struct osd_object *obj, const struct dt_rec *rec, union lquota_rec *quota_rec)
void osd_quota_unpack (struct osd_object *obj, const struct dt_rec *rec)
int osd_quota_migration (const struct lu_env *env, struct dt_object *dt)
static uid_t i_uid_read (const struct inode *inode)
static gid_t i_gid_read (const struct inode *inode)
static void i_uid_write (struct inode *inode, uid_t uid)
static void i_gid_write (struct inode *inode, gid_t gid)
static struct buffer_head * osd_ldiskfs_append (handle_t *handle, struct inode *inode, ldiskfs_lblk_t *nblock)
static int osd_oi_fid2idx (struct osd_device *dev, const struct lu_fid *fid)
static struct osd_oi * osd_fid2oi (struct osd_device *osd, const struct lu_fid *fid)
static int lu_device_is_osd (const struct lu_device *d)
static struct osd_device * osd_dt_dev (const struct dt_device *d)
static struct osd_device * osd_dev (const struct lu_device *d)
static struct osd_device * osd_obj2dev (const struct osd_object *o)
static struct super_block * osd_sb (const struct osd_device *dev)
static int osd_object_is_root (const struct osd_object *obj)
static struct osd_object * osd_obj (const struct lu_object *o)
static struct osd_object * osd_dt_obj (const struct dt_object *d)
static struct lu_device * osd2lu_dev (struct osd_device *osd)
static journal_t * osd_journal (const struct osd_device *dev)
static struct seq_server_site * osd_seq_site (struct osd_device *osd)
static char * osd_name (struct osd_device *osd)
static bool osd_is_ea_inode (struct inode *inode)
static struct osd_thread_info * osd_oti_get (const struct lu_env *env)
static struct iam_path_descr * osd_it_ipd_get (const struct lu_env *env, const struct iam_container *bag)
IAM Iterator.
static struct iam_path_descr * osd_idx_ipd_get (const struct lu_env *env, const struct iam_container *bag)
static void osd_ipd_put (const struct lu_env *env, const struct iam_container *bag, struct iam_path_descr *ipd)
int osd_calc_bkmap_credits (struct super_block *sb, struct inode *inode, const loff_t size, const loff_t pos, const int blocks)
int osd_ldiskfs_read (struct inode *inode, void *buf, int size, loff_t *offs)
int osd_ldiskfs_write_record (struct inode *inode, void *buf, int bufsize, int write_NUL, loff_t *offs, handle_t *handle)
static struct dentry * osd_child_dentry_by_inode (const struct lu_env *env, struct inode *inode, const char *name, const int namelen)
void osd_trans_dump_creds (const struct lu_env *env, struct thandle *th)
static void osd_trans_declare_op (const struct lu_env *env, struct osd_thandle *oh, unsigned int op, int credits)
static void osd_trans_exec_op (const struct lu_env *env, struct thandle *th, unsigned int op)
static void osd_trans_exec_check (const struct lu_env *env, struct thandle *th, unsigned int op)
static void osd_fid_pack (struct osd_fid_pack *pack, const struct dt_rec *fid, struct lu_fid *befider)
Helper function to pack the fid, ldiskfs stores fid in packed format.
static int osd_fid_unpack (struct lu_fid *fid, const struct osd_fid_pack *pack)
int osd_acct_obj_lookup (struct osd_thread_info *info, struct osd_device *osd, const struct lu_fid *fid, struct osd_inode_id *id)
Space Accounting Management.
static int is_32bit_api (void)
static loff_t ldiskfs_get_htree_eof (struct file *filp)
static int fid_is_internal (const struct lu_fid *fid)
static unsigned long osd_remote_parent_ino (struct osd_device *dev)
void ldiskfs_inc_count (handle_t *handle, struct inode *inode)
void ldiskfs_dec_count (handle_t *handle, struct inode *inode)
void osd_fini_iobuf (struct osd_device *d, struct osd_iobuf *iobuf)
Variables
struct kmem_cache * dynlock_cachep
const int osd_dto_credits_noquota []
Note: we do not count into QUOTA here.
struct osd_it_ea_dirent packed
int ldiskfs_pdo
struct dt_index_operations osd_otable_ops
struct lu_device_operations osd_lu_ops
struct dt_body_operations osd_body_ops
struct lu_context_key osd_key
struct dt_body_operations osd_body_ops_new
int osd_trans_declare_op2rb []
int ldiskfs_track_declares_assert
struct dt_index_operations osd_acct_index_ops
Quota/Accounting handling.
Define Documentation
#define ADMIN_GRP "admin_quotafile_v2.grp"
Definition at line 91 of file osd_internal.h.
Referenced by osd_ios_OBJECTS_scan(), and osd_quota_migration().
#define ADMIN_USR "admin_quotafile_v2.usr"
Definition at line 90 of file osd_internal.h.
Referenced by osd_ios_OBJECTS_scan(), and osd_quota_migration().
#define FULL_SCRUB_THRESHOLD_RATE_DEFAULT 60
Definition at line 319 of file osd_internal.h.
Referenced by osd_device_init0().
#define LDISKFS_HT_MISC 0
Definition at line 791 of file osd_internal.h.
Referenced by ldiskfs_ext_new_extent_cb(), osd_dirent_check_repair(), osd_lma_self_repair(), osd_obj_map_recover(), osd_oi_index_create_one(), osd_process_scheduled_agent_removals(), osd_scrub_convert_ff(), osd_scrub_file_store(), osd_scrub_refresh_mapping(), and osd_trans_start().
#define LDISKFS_STATE_LUSTRE_DESTROY 30
Definition at line 82 of file osd_internal.h.
Referenced by osd_iget(), osd_iget_check(), osd_object_destroy(), and osd_scrub_check_update().
#define LDISKFS_STATE_LUSTRE_NOSCRUB 31
Definition at line 81 of file osd_internal.h.
Referenced by osd_create_local_agent_inode(), osd_iit_iget(), osd_mkfile(), and osd_oi_index_create_one().
#define MAX_BLOCKS_PER_PAGE (PAGE_CACHE_SIZE / 512)
Definition at line 491 of file osd_internal.h.
#define MAX_OBJID_GROUP (FID_SEQ_ECHO + 1)
Definition at line 87 of file osd_internal.h.
#define OBJECTS "OBJECTS"
Definition at line 89 of file osd_internal.h.
Referenced by osd_quota_migration().
#define OSD_COUNTERS (0)
Definition at line 75 of file osd_internal.h.
#define OSD_FID_REC_SZ 32
Definition at line 602 of file osd_internal.h.
#define OSD_INS_CACHE_SIZE 8
Definition at line 513 of file osd_internal.h.
Referenced by osd_idc_add().
#define osd_invariant (obj) (1)
Definition at line 840 of file osd_internal.h.
Referenced by osd_attr_get(), osd_attr_set(), osd_declare_attr_set(), osd_declare_dir_delete(), osd_declare_index_delete(), osd_declare_xattr_del(), osd_dir_insert(), osd_fid_lookup(), osd_index_ea_delete(), osd_index_ea_insert(), osd_index_ea_lookup(), osd_index_iam_delete(), osd_index_iam_insert(), osd_index_iam_lookup(), osd_index_insert(), osd_index_try(), osd_mkfile(), osd_mknod(), osd_object_create(), osd_object_delete(), osd_object_ea_create(), osd_object_free(), osd_object_init(), osd_object_invariant(), osd_object_read_lock(), osd_object_read_unlock(), osd_object_ref_add(), osd_object_ref_del(), osd_object_write_lock(), osd_object_write_locked(), osd_object_write_unlock(), osd_oi_iam_delete(), osd_oi_iam_lookup(), osd_oi_iam_refresh(), osd_punch(), osd_xattr_del(), osd_xattr_get(), osd_xattr_list(), and osd_xattr_set().
#define OSD_INVARIANT_CHECKS (0)
Definition at line 825 of file osd_internal.h.
#define OSD_IT_EA_BUFSIZE (PAGE_CACHE_SIZE + PAGE_CACHE_SIZE/4)
as osd_it_ea_dirent (in memory dirent struct for osd) is greater than lu_dirent struct.
osd readdir reads less number of dirent than required for mdd dir page. so buffer size need to be increased so that there would be one ext3 readdir for every mdd readdir page.
Definition at line 439 of file osd_internal.h.
Referenced by osd_it_ea_fini(), osd_it_ea_init(), osd_key_fini(), osd_key_init(), and osd_ldiskfs_filldir().
#define osd_journal_start (inode, type, nblocks) ldiskfs_journal_start(inode, nblocks)
Definition at line 811 of file osd_internal.h.
Referenced by ldiskfs_ext_new_extent_cb().
#define osd_journal_start_sb (sb, type, nblock) ldiskfs_journal_start_sb(sb, nblock)
Definition at line 792 of file osd_internal.h.
Referenced by osd_dirent_check_repair(), osd_lma_self_repair(), osd_obj_map_recover(), osd_oi_index_create_one(), osd_process_scheduled_agent_removals(), osd_scrub_convert_ff(), osd_scrub_file_store(), osd_scrub_refresh_mapping(), and osd_trans_start().
#define osd_ldiskfs_find_entry (dir, name, de, inlined, lock) __ldiskfs_find_entry(dir, name, de, lock)
Definition at line 809 of file osd_internal.h.
Referenced by __osd_ea_add_rec(), osd_delete_from_remote_parent(), osd_dirent_check_repair(), osd_ea_lookup_rec(), osd_index_ea_delete(), osd_lookup_in_remote_parent(), osd_obj_del_entry(), osd_obj_map_lookup(), osd_obj_map_recover(), osd_obj_update_entry(), and osd_oi_index_create_one().
#define OSD_MAX_CACHE_SIZE OBD_OBJECT_EOF
Definition at line 843 of file osd_internal.h.
Referenced by osd_device_init0().
#define OSD_MAX_UGID_CNT 10
Definition at line 332 of file osd_internal.h.
Referenced by osd_declare_qid().
#define OSD_OTABLE_IT_CACHE_MASK (~(OSD_OTABLE_IT_CACHE_SIZE - 1))
Definition at line 184 of file osd_internal.h.
Referenced by osd_otable_it_next(), and osd_preload_exec().
#define OSD_OTABLE_IT_CACHE_SIZE 64
Definition at line 183 of file osd_internal.h.
Referenced by osd_otable_it_preload().
#define OSD_STATFS_RESERVED (1ULL << 23)
Definition at line 94 of file osd_internal.h.
Referenced by osd_statfs().
#define OSD_STATFS_RESERVED_SHIFT (7)
Definition at line 95 of file osd_internal.h.
Referenced by osd_objset_statfs(), and osd_statfs().
#define OSD_THANDLE_STATS (0)
Enable thandle usage statistics.
Definition at line 85 of file osd_internal.h.
#define osd_transaction_size (dev) (osd_journal(dev)->j_max_transaction_buffers)
Definition at line 813 of file osd_internal.h.
Referenced by osd_param_is_not_sane(), osd_trans_exec_op(), and osd_trans_start().
Enumeration Type Documentation
anonymous enum
Enumerator:
OSD_OT_ATTR_SET
OSD_OT_PUNCH
OSD_OT_XATTR_SET
OSD_OT_CREATE
OSD_OT_DESTROY
OSD_OT_REF_ADD
OSD_OT_REF_DEL
OSD_OT_WRITE
OSD_OT_INSERT
OSD_OT_DELETE
OSD_OT_QUOTA
OSD_OT_MAX
Definition at line 334 of file osd_internal.h.
enum dt_txn_op
Basic transaction credit op.
Enumerator:
DTO_INDEX_INSERT
DTO_INDEX_DELETE
DTO_INDEX_UPDATE
DTO_OBJECT_CREATE
DTO_OBJECT_DELETE
DTO_ATTR_SET_BASE
DTO_XATTR_SET
DTO_WRITE_BASE
DTO_WRITE_BLOCK
DTO_ATTR_SET_CHOWN
DTO_NR
Definition at line 375 of file osd_internal.h.
enum osd_full_scrub_ratio
Enumerator:
OFSR_DIRECTLY
OFSR_NEVER
OFSR_DEFAULT
Definition at line 307 of file osd_internal.h.
Function Documentation
static int __osd_xattr_get (struct inode * inode, struct dentry * dentry, const char * name, void * buf, int len) [inline, static]
Definition at line 632 of file osd_internal.h.
static int __osd_xattr_set (struct osd_thread_info * info, struct inode * inode, const char * name, const void * buf, int buflen, int fl) [inline, static]
Definition at line 643 of file osd_internal.h.
References ll_vfs_dq_init, and osd_thread_info::oti_child_dentry.
static int fid_is_internal (const struct lu_fid * fid) [inline, static]
Definition at line 1197 of file osd_internal.h.
References fid_is_idif(), and fid_is_namespace_visible().
Referenced by osd_scrub_get_fid().
loff_t find_tree_dqentry (const struct lu_env * env, struct osd_object * obj, int type, qid_t dqid, uint blk, int depth, struct osd_it_quota * it)
Find entry for given dqid in the tree block blk.
Return values:
+ve,the offset of the entry in file
0,entry not found
-ve,unexpected failure
Definition at line 149 of file osd_quota_fmt.c.
References buf, CERROR, ENTRY, find_block_dqentry(), find_tree_dqentry(), freedqbuf(), getdqbuf(), GETIDINDEX, GOTO, le32_to_cpu, LUSTRE_DQTREEDEPTH, osd_it_quota::oiq_blk, osd_it_quota::oiq_index, quota_read_blk(), ret, and RETURN.
Referenced by find_tree_dqentry(), and osd_it_acct_get().
static gid_t i_gid_read (const struct inode * inode) [inline, static]
Definition at line 763 of file osd_internal.h.
Referenced by osd_declare_attr_set(), osd_declare_object_destroy(), osd_declare_punch(), osd_declare_write(), osd_declare_write_commit(), osd_index_declare_ea_delete(), osd_index_declare_ea_insert(), osd_inode_getattr(), osd_object_delete(), and osd_quota_transfer().
static void i_gid_write (struct inode * inode, gid_t gid) [inline, static]
Definition at line 773 of file osd_internal.h.
Referenced by osd_inode_setattr().
static uid_t i_uid_read (const struct inode * inode) [inline, static]
Definition at line 758 of file osd_internal.h.
Referenced by osd_declare_attr_set(), osd_declare_object_destroy(), osd_declare_punch(), osd_declare_write(), osd_declare_write_commit(), osd_index_declare_ea_delete(), osd_index_declare_ea_insert(), osd_inode_getattr(), osd_object_delete(), and osd_quota_transfer().
static void i_uid_write (struct inode * inode, uid_t uid) [inline, static]
Definition at line 768 of file osd_internal.h.
Referenced by osd_inode_setattr().
static int is_32bit_api (void) [inline, static]
Definition at line 1179 of file osd_internal.h.
Referenced by ldiskfs_get_htree_eof().
void ldiskfs_dec_count (handle_t * handle, struct inode * inode)
Referenced by osd_delete_from_remote_parent(), and osd_object_ref_del().
static loff_t ldiskfs_get_htree_eof (struct file * filp) [inline, static]
Definition at line 1188 of file osd_internal.h.
References is_32bit_api().
Referenced by osd_it_ea_next(), and osd_ldiskfs_it_fill().
void ldiskfs_inc_count (handle_t * handle, struct inode * inode)
Referenced by osd_add_to_remote_parent(), and osd_object_ref_add().
static int lu_device_is_osd (const struct lu_device * d) [inline, static]
Definition at line 867 of file osd_internal.h.
References ergo, lu_device::ld_ops, and osd_lu_ops.
Referenced by osd_dev(), osd_dt_dev(), and osd_obj().
static struct lu_device* osd2lu_dev (struct osd_device * osd) [static, read]
Definition at line 910 of file osd_internal.h.
References dt_device::dd_lu_dev, and osd_device::od_dt_dev.
Referenced by osd_device_alloc(), osd_device_init0(), osd_mkreg(), and osd_mount().
int osd_acct_obj_lookup (struct osd_thread_info * info, struct osd_device * osd, const struct lu_fid * fid, struct osd_inode_id * id)
Space Accounting Management.
Look up an accounting object based on its fid.
Parameters:
info - is the osd thread info passed by the caller
osd - is the osd device
fid - is the fid of the accounting object we want to look up
id - is the osd_inode_id struct to fill with the inode number of the quota file if the lookup is successful
Definition at line 64 of file osd_quota.c.
References ENTRY, fid2type(), fid_is_acct(), LASSERT, le32_to_cpu, osd_inode_id::oii_ino, OSD_OII_NOGEN, osd_sb(), and RETURN.
Referenced by osd_oi_lookup().
void osd_add_oi_cache (struct osd_thread_info * info, struct osd_device * osd, struct osd_inode_id * id, const struct lu_fid * fid)
Definition at line 4508 of file osd_handler.c.
References CDEBUG, D_INODE, DFID, osd_idmap_cache::oic_dev, osd_idmap_cache::oic_fid, osd_idmap_cache::oic_lid, osd_inode_id::oii_gen, osd_inode_id::oii_ino, osd_thread_info::oti_cache, and PFID.
Referenced by osd_ea_lookup_rec(), osd_it_ea_rec(), and osd_lookup_in_remote_parent().
int osd_add_to_remote_parent (const struct lu_env * env, struct osd_device * osd, struct osd_object * obj, struct osd_thandle * oh)
Definition at line 221 of file osd_compat.c.
References __osd_xattr_set(), CDEBUG, D_INODE, DFID_NOBRACE, dt_object::do_lu, ldiskfs_inc_count(), lustre_mdt_attrs::lma_incompat, LMAI_REMOTE_PARENT, lu_object_fid(), lustre_lma_swab(), name, osd_device::od_mdt_map, osd_mdobj_map::omm_remote_parent, osd_object::oo_dt, osd_object::oo_inode, osd_child_dentry_by_inode(), osd_get_lma(), osd_ldiskfs_add_entry(), osd_name(), osd_oti_get(), osd_thandle::ot_handle, osd_thread_info::oti_mdt_attrs, osd_thread_info::oti_name, osd_thread_info::oti_obj_dentry, PFID, RETURN, and XATTR_NAME_LMA.
Referenced by osd_index_ea_insert().
int osd_calc_bkmap_credits (struct super_block * sb, struct inode * inode, const loff_t size, const loff_t pos, const int blocks)
Definition at line 1491 of file osd_io.c.
References credits, and LASSERT.
Referenced by osd_declare_write(), and osd_declare_xattr_set().
static struct dentry* osd_child_dentry_by_inode (const struct lu_env * env, struct inode * inode, const char * name, const int namelen) [static, read]
Definition at line 980 of file osd_internal.h.
References osd_oti_get(), osd_thread_info::oti_child_dentry, and osd_thread_info::oti_obj_dentry.
Referenced by osd_add_to_remote_parent(), osd_child_dentry_get(), osd_delete_from_remote_parent(), osd_dirent_check_repair(), osd_lookup_in_remote_parent(), and osd_oi_index_create_one().
int osd_declare_inode_qid (const struct lu_env * env, qid_t uid, qid_t gid, long long space, struct osd_thandle * oh, struct osd_object * obj, bool is_blk, int * flags, bool force)
Wrapper for osd_declare_qid().
Parameters:
env - the environment passed by the caller
uid - user id of the inode
gid - group id of the inode
space - how many blocks/inodes will be consumed/released
oh - osd transaction handle
obj - osd object, could be NULL when it's under create
is_blk - block quota or inode quota?
flags - if the operation is write, return no user quota, no group quota, or sync commit flags to the caller
force - set to 1 when changes are performed by root user and thus can't failed with EDQUOT
Return values:
0 - success
-ve - failure
Definition at line 590 of file osd_quota.c.
References ENTRY, lquota_id_info::lqi_id, lquota_id_info::lqi_is_blk, lquota_id_info::lqi_space, lquota_id_info::lqi_type, osd_declare_qid(), osd_oti_get(), osd_thread_info::oti_qi, lquota_id::qid_gid, lquota_id::qid_uid, and RETURN.
Referenced by osd_declare_object_create(), osd_declare_object_destroy(), osd_declare_punch(), osd_declare_write(), osd_declare_write_commit(), osd_index_declare_ea_delete(), and osd_index_declare_ea_insert().
int osd_declare_qid (const struct lu_env * env, struct osd_thandle * oh, struct lquota_id_info * qi, struct osd_object * obj, bool enforce, int * flags)
Reserve journal credits for quota files update first, then call ->op_begin() to perform quota enforcement.
Parameters:
env - the environment passed by the caller
oh - osd transaction handle
qi - quota id & space required for this operation
obj - osd object, could be NULL when it's under create
enforce - whether to perform quota enforcement
flags - if the operation is write, return no user quota, no group quota, or sync commit flags to the caller
Return values:
0 - success
-ve - failure
Definition at line 504 of file osd_quota.c.
References CERROR, ENTRY, LASSERT, LASSERTF, lquota_id_info::lqi_id, lquota_id_info::lqi_space, lquota_id_info::lqi_type, osd_device::od_quota_slave, osd_object::oo_inode, osd_dt_dev(), OSD_MAX_UGID_CNT, OSD_OT_QUOTA, osd_qid_set_type(), osd_qid_type(), osd_sb(), osd_trans_declare_op(), osd_thandle::ot_id_array, osd_thandle::ot_id_cnt, osd_thandle::ot_quota_trans, osd_thandle::ot_super, lquota_id::qid_uid, qsd_op_begin(), RETURN, thandle::th_dev, and unlikely.
Referenced by osd_declare_attr_set(), and osd_declare_inode_qid().
int osd_delete_from_remote_parent (const struct lu_env * env, struct osd_device * osd, struct osd_object * obj, struct osd_thandle * oh)
Definition at line 261 of file osd_compat.c.
References __osd_xattr_set(), CDEBUG, D_INODE, DFID_NOBRACE, dt_object::do_lu, ldiskfs_dec_count(), likely, lustre_mdt_attrs::lma_incompat, LMAI_REMOTE_PARENT, lu_object_fid(), lustre_lma_swab(), name, osd_device::od_mdt_map, osd_mdobj_map::omm_remote_parent, osd_object::oo_dt, osd_object::oo_inode, osd_child_dentry_by_inode(), osd_get_lma(), osd_ldiskfs_find_entry, osd_name(), osd_oti_get(), osd_thandle::ot_handle, osd_thread_info::oti_mdt_attrs, osd_thread_info::oti_name, osd_thread_info::oti_obj_dentry, PFID, RETURN, and XATTR_NAME_LMA.
Referenced by osd_index_ea_delete(), and osd_object_destroy().
static struct osd_device* osd_dev (const struct lu_device * d) [static, read]
Definition at line 878 of file osd_internal.h.
References LASSERT, lu_device_is_osd(), and osd_dt_dev().
Referenced by osd_attr_set(), osd_declare_xattr_del(), osd_declare_xattr_set(), osd_device_fini(), osd_device_free(), osd_device_init(), osd_fid_alloc(), osd_fid_lookup(), osd_health_check(), osd_index_declare_ea_insert(), osd_index_ea_delete(), osd_index_ea_insert(), osd_it_acct_init(), osd_obd_connect(), osd_obd_disconnect(), osd_obj2dev(), osd_object_ea_create(), osd_object_find(), osd_object_ref_del(), osd_otable_it_init(), osd_prepare(), osd_process_config(), osd_recovery_complete(), and osd_zfs_otable_it_init().
static struct osd_device* osd_dt_dev (const struct dt_device * d) [static, read]
Definition at line 872 of file osd_internal.h.
References dt_device::dd_lu_dev, LASSERT, lu_device_is_osd(), and osd_device::od_dt_dev.
Referenced by osd_commit_async(), osd_conf_get(), osd_declare_qid(), osd_dev(), osd_ro(), osd_schedule_agent_inode_removal(), osd_statfs(), osd_sync(), osd_trans_commit_cb(), osd_trans_create(), osd_trans_declare_op(), osd_trans_exec_op(), osd_trans_start(), and osd_trans_stop().
static struct osd_object* osd_dt_obj (const struct dt_object * d) [static, read]
Definition at line 905 of file osd_internal.h.
References dt_object::do_lu, and osd_obj().
Referenced by osd_acct_index_lookup(), osd_ah_init(), osd_attr_get(), osd_attr_set(), osd_bufs_get(), osd_bufs_put(), osd_declare_attr_set(), osd_declare_dir_delete(), osd_declare_dir_insert(), osd_declare_index_delete(), osd_declare_index_insert(), osd_declare_object_create(), osd_declare_object_destroy(), osd_declare_punch(), osd_declare_write(), osd_declare_write_commit(), osd_declare_xattr_del(), osd_declare_xattr_set(), osd_dir_delete(), osd_dir_insert(), osd_dir_lookup(), osd_fiemap_get(), osd_find_parent_by_dnode(), osd_get_page(), osd_index_declare_ea_delete(), osd_index_declare_ea_insert(), osd_index_delete(), osd_index_ea_delete(), osd_index_ea_insert(), osd_index_ea_lookup(), osd_index_iam_delete(), osd_index_iam_insert(), osd_index_iam_lookup(), osd_index_insert(), osd_index_it_init(), osd_index_lookup(), osd_index_try(), osd_is_mapped(), osd_it_acct_init(), osd_it_ea_init(), osd_it_iam_init(), osd_mkfile(), osd_object_create(), osd_object_destroy(), osd_object_ea_create(), osd_object_read_lock(), osd_object_read_unlock(), osd_object_ref_add(), osd_object_ref_del(), osd_object_sync(), osd_object_version_get(), osd_object_version_set(), osd_object_write_lock(), osd_object_write_locked(), osd_object_write_unlock(), osd_punch(), osd_quota_migration(), osd_read(), osd_read_prep(), osd_write(), osd_write_commit(), osd_write_prep(), osd_xattr_del(), osd_xattr_get(), osd_xattr_list(), and osd_xattr_set().
int osd_ea_fid_set (struct osd_thread_info * info, struct inode * inode, const struct lu_fid * fid, __u32 compat, __u32 incompat)
Put the fid into lustre_mdt_attrs, and then place the structure inode's ea.
This fid should not be altered during the life time of the inode.
Return values:
+ve,on success
-ve,on error
FIXME: It is good to have/use ldiskfs_xattr_set_handle() here
Definition at line 2836 of file osd_handler.c.
References __osd_xattr_get(), __osd_xattr_set(), ENTRY, lustre_mdt_attrs::lma_compat, lustre_mdt_attrs::lma_incompat, LMA_OLD_SIZE, lustre_lma_init(), lustre_lma_swab(), OBD_FAIL_CHECK, OBD_FAIL_FID_INLMA, OBD_FAIL_OSD_OST_EA_FID_SET, osd_thread_info::oti_mdt_attrs, osd_thread_info::oti_mdt_attrs_old, osd_thread_info::oti_obj_dentry, RETURN, unlikely, and XATTR_NAME_LMA.
Referenced by osd_create_local_agent_inode(), osd_dirent_check_repair(), osd_ios_scan_one(), osd_lma_self_repair(), osd_mdt_init(), osd_mount(), osd_object_ea_create(), osd_oi_open(), osd_ost_init(), osd_scrub_check_update(), osd_scrub_convert_ff(), osd_scrub_setup(), and osd_seq_load_locked().
static struct osd_oi* osd_fid2oi (struct osd_device * osd, const struct lu_fid * fid) [static, read]
Definition at line 853 of file osd_internal.h.
References DFID, fid_is_idif(), fid_is_last_id(), LASSERTF, osd_device::od_oi_count, osd_device::od_oi_table, osd_oi_fid2idx(), and PFID.
Referenced by __osd_oi_lookup(), osd_attr_set(), osd_oi_delete(), osd_oi_insert(), and osd_oi_update().
static void osd_fid_pack (struct osd_fid_pack * pack, const struct dt_rec * fid, struct lu_fid * befider) [inline, static]
Helper function to pack the fid, ldiskfs stores fid in packed format.
Definition at line 1145 of file osd_internal.h.
References fid_cpu_to_be(), osd_fid_pack::fp_area, and osd_fid_pack::fp_len.
static int osd_fid_unpack (struct lu_fid * fid, const struct osd_fid_pack * pack) [inline, static]
Definition at line 1154 of file osd_internal.h.
References CERROR, fid_be_to_cpu(), osd_fid_pack::fp_area, and osd_fid_pack::fp_len.
Referenced by osd_get_fid_from_dentry(), osd_index_iam_lookup(), osd_it_iam_rec(), and osd_ldiskfs_filldir().
void osd_fini_iobuf (struct osd_device * d, struct osd_iobuf * iobuf)
Definition at line 128 of file osd_io.c.
References BRW_R_DIO_FRAGS, BRW_R_IO_TIME, osd_iobuf::dr_dev, osd_iobuf::dr_elapsed, osd_iobuf::dr_elapsed_valid, osd_iobuf::dr_frags, osd_iobuf::dr_rw, brw_stats::hist, LASSERT, lprocfs_oh_tally(), lprocfs_oh_tally_log2(), and osd_device::od_brw_stats.
Referenced by osd_do_bio(), osd_trans_stop(), osd_write_commit(), and osd_write_prep().
int osd_fld_lookup (const struct lu_env * env, struct osd_device * osd, u64 seq, struct lu_seq_range * range)
Lookup the target index/flags of the fid, so it will know where the object is located (tgt index) and it is MDT or OST object.
Definition at line 2619 of file osd_handler.c.
References fid_seq_in_fldb(), fid_seq_is_idif(), fld_local_lookup(), fld_range_set_any(), fld_range_set_mdt(), fld_range_set_ost(), idif_ost_idx(), LASSERT, lu_seq_range::lsr_index, osd_seq_site(), seq_server_site::ss_node_id, and seq_server_site::ss_server_fld.
Referenced by fid_is_on_ost(), and osd_seq_exists().
int osd_get_idif (struct osd_thread_info * info, struct inode * inode, struct dentry * dentry, struct lu_fid * fid)
Return values:
+v,: new filter_fid, does not contain self-fid
0,: filter_fid_old, contains self-fid
-v,: other failure cases
Definition at line 641 of file osd_handler.c.
References __osd_xattr_get(), filter_fid_old::ff_objid, filter_fid_old::ff_seq, le64_to_cpu, ostid_set_id(), ostid_set_seq(), ostid_to_fid(), osd_thread_info::oti_ff, osd_thread_info::oti_ostid, and XATTR_NAME_FID.
Referenced by osd_check_lma(), osd_obj_update_entry(), and osd_scrub_get_fid().
int osd_get_lma (struct osd_thread_info * info, struct inode * inode, struct dentry * dentry, struct lustre_mdt_attrs * lma)
Definition at line 356 of file osd_handler.c.
References __osd_xattr_get(), CLASSERT, CWARN, DFID, lustre_mdt_attrs::lma_incompat, LMA_INCOMPAT_SUPP, LMA_OLD_SIZE, lustre_mdt_attrs::lma_self_fid, lustre_lma_swab(), osd_thread_info::oti_mdt_attrs_old, PFID, and XATTR_NAME_LMA.
Referenced by osd_add_to_remote_parent(), osd_attr_set(), osd_delete_from_remote_parent(), osd_dirent_check_repair(), osd_fail_fid_lookup(), osd_iget_fid(), osd_ios_scan_one(), osd_ldiskfs_add_entry(), osd_obj_update_entry(), osd_object_init(), osd_oi_insert(), osd_scrub_get_fid(), and osd_xattr_set().
static struct iam_path_descr* osd_idx_ipd_get (const struct lu_env * env, const struct iam_container * bag) [static, read]
Definition at line 957 of file osd_internal.h.
References iam_container::ic_descr, iam_operations::id_ipd_alloc, iam_descr::id_ops, and osd_oti_get().
Referenced by osd_attr_set(), osd_index_iam_delete(), osd_index_iam_insert(), osd_index_iam_lookup(), osd_oi_iam_delete(), osd_oi_iam_lookup(), and osd_oi_iam_refresh().
struct inode* osd_iget (struct osd_thread_info * info, struct osd_device * dev, struct osd_inode_id * id) [read]
Definition at line 388 of file osd_handler.c.
References CDEBUG, CWARN, D_INODE, LDISKFS_STATE_LUSTRE_DESTROY, osd_inode_id::oii_gen, osd_inode_id::oii_ino, osd_id_gen(), OSD_OII_NOGEN, and osd_sb().
Referenced by osd_consistency_check(), osd_dirent_check_repair(), osd_fail_fid_lookup(), osd_iget_fid(), osd_iit_iget(), osd_obj_map_lookup(), osd_obj_update_entry(), osd_oi_index_create_one(), osd_oi_insert(), and osd_scrub_check_update().
static void osd_ipd_put (const struct lu_env * env, const struct iam_container * bag, struct iam_path_descr * ipd) [inline, static]
Definition at line 964 of file osd_internal.h.
References iam_container::ic_descr, iam_operations::id_ipd_free, and iam_descr::id_ops.
Referenced by osd_attr_set(), osd_index_iam_delete(), osd_index_iam_insert(), osd_index_iam_lookup(), osd_it_iam_fini(), osd_oi_iam_delete(), osd_oi_iam_lookup(), and osd_oi_iam_refresh().
static bool osd_is_ea_inode (struct inode * inode) [inline, static]
Definition at line 930 of file osd_internal.h.
Referenced by osd_iit_iget(), osd_obj_update_entry(), osd_oi_insert(), and osd_scrub_check_update().
static struct iam_path_descr* osd_it_ipd_get (const struct lu_env * env, const struct iam_container * bag) [static, read]
IAM Iterator.
Definition at line 949 of file osd_internal.h.
References iam_container::ic_descr, iam_operations::id_ipd_alloc, iam_descr::id_ops, and osd_oti_get().
Referenced by osd_it_iam_init().
static journal_t* osd_journal (const struct osd_device * dev) [inline, static]
Definition at line 915 of file osd_internal.h.
References osd_sb().
int osd_ldiskfs_add_entry (struct osd_thread_info * info, handle_t * handle, struct dentry * child, struct inode * inode, struct htree_lock * hlock)
Definition at line 436 of file osd_handler.c.
References CWARN, DFID, FID_LEN, fid_seq_is_mdt0(), lustre_mdt_attrs::lma_self_fid, lu_igif_build(), lu_local_obj_fid(), osd_device::od_is_ost, OSD_FS_ROOT_OID, osd_get_lma(), osd_thread_info::oti_dev, PFID, and unlikely.
Referenced by __osd_ea_add_rec(), osd_add_to_remote_parent(), osd_dirent_reinsert(), osd_obj_add_entry(), osd_obj_map_recover(), and osd_oi_index_create_one().
static struct buffer_head* osd_ldiskfs_append (handle_t * handle, struct inode * inode, ldiskfs_lblk_t * nblock) [static, read]
Definition at line 795 of file osd_internal.h.
Referenced by iam_lfix_create(), iam_lvar_create(), and iam_new_node().
int osd_ldiskfs_read (struct inode * inode, void * buf, int size, loff_t * offs)
Definition at line 1402 of file osd_io.c.
References blocksize(), CDEBUG, CERROR, and D_EXT2.
Referenced by osd_last_rcvd_subdir_count(), osd_read(), and osd_scrub_file_load().
int osd_ldiskfs_write_record (struct inode * inode, void * buf, int bufsize, int write_NUL, loff_t * offs, handle_t * handle)
Definition at line 1640 of file osd_io.c.
References blocksize(), CERROR, LASSERTF, ll_dirty_inode, and size.
Referenced by osd_scrub_file_store(), and osd_write().
char* osd_lf_fid2name (const struct lu_fid * fid)
Definition at line 2356 of file osd_scrub.c.
References lu_fid_eq(), OLF_SHOW_NAME, osd_lf_map::olm_fid, osd_lf_map::olm_flags, and osd_lf_map::olm_name.
Referenced by osd_obj_spec_lookup(), and osd_object_spec_find().
int osd_lookup_in_remote_parent (struct osd_thread_info * oti, struct osd_device * osd, const struct lu_fid * fid, struct osd_inode_id * id)
Definition at line 311 of file osd_compat.c.
References DFID_NOBRACE, ENTRY, le32_to_cpu, name, osd_device::od_mdt_map, osd_mdobj_map::omm_remote_parent, osd_add_oi_cache(), osd_child_dentry_by_inode(), osd_id_gen(), osd_ldiskfs_find_entry, OSD_OII_NOGEN, osd_thread_info::oti_env, osd_thread_info::oti_name, PFID, and RETURN.
Referenced by osd_fid_lookup().
static char* osd_name (struct osd_device * osd) [inline, static]
Definition at line 925 of file osd_internal.h.
References dt_device::dd_lu_dev, lu_device::ld_obd, obd_device::obd_name, and osd_device::od_dt_dev.
Referenced by fid_is_on_ost(), osd_add_to_remote_parent(), osd_attr_set(), osd_check_lma(), osd_create_local_agent_inode(), osd_delete_from_remote_parent(), osd_fid_lookup(), osd_find_or_add_seq(), osd_get_idx_for_ost_obj(), osd_index_ea_delete(), osd_index_ea_insert(), osd_ios_lf_fill(), osd_ios_scan_one(), osd_lma_self_repair(), osd_obj_update_entry(), osd_object_destroy(), osd_object_ref_del(), osd_scrub_convert_ff(), osd_scrub_refresh_mapping(), osd_seq_exists(), osd_trans_declare_op(), osd_trans_exec_op(), and osd_trans_stop().
static struct osd_object* osd_obj (const struct lu_object * o) [static, read]
Definition at line 899 of file osd_internal.h.
References dt_object::do_lu, LASSERT, lu_object::lo_dev, lu_device_is_osd(), and osd_object::oo_dt.
Referenced by osd_dt_obj(), osd_object_delete(), osd_object_find(), osd_object_free(), osd_object_init(), osd_object_invariant(), osd_object_print(), and osd_object_release().
static struct osd_device* osd_obj2dev (const struct osd_object * o) [static, read]
Definition at line 884 of file osd_internal.h.
References dt_object::do_lu, lu_object::lo_dev, osd_object::oo_dt, and osd_dev().
Referenced by __osd_ea_add_rec(), __osd_object_create(), __osd_oi_insert(), __osd_sa_xattr_set(), __osd_sa_xattr_update(), __osd_xattr_cache(), __osd_xattr_declare_del(), __osd_xattr_declare_set(), __osd_xattr_del(), __osd_xattr_get(), __osd_xattr_set(), osd_acct_index_lookup(), osd_ah_init(), osd_attr_get(), osd_attr_set(), osd_bufs_get_read(), osd_bufs_get_write(), osd_bufs_put(), osd_check_lma(), osd_declare_attr_set(), osd_declare_object_create(), osd_declare_object_destroy(), osd_declare_punch(), osd_declare_write(), osd_declare_write_commit(), osd_declare_xattrs_destroy(), osd_dir_delete(), osd_dir_insert(), osd_dir_it_rec(), osd_dir_it_rec_size(), osd_dir_lookup(), osd_dirent_check_repair(), osd_ea_fid_get(), osd_ea_lookup_rec(), osd_find_parent_by_dnode(), osd_get_page(), osd_index_delete(), osd_index_ea_delete(), osd_index_insert(), osd_index_it_get(), osd_index_it_load(), osd_index_it_rec(), osd_index_lookup(), osd_it_acct_load(), osd_it_acct_rec(), osd_it_ea_init(), osd_it_ea_rec(), osd_ldiskfs_filldir(), osd_mkdir(), osd_mkfile(), osd_mkidx(), osd_mkreg(), osd_obj_cursor_init(), osd_obj_cursor_init_serialized(), osd_object_create(), osd_object_delete(), osd_object_destroy(), osd_object_ea_create(), osd_object_init(), osd_object_init0(), osd_object_is_root(), osd_object_ref_add(), osd_object_ref_del(), osd_object_sync(), osd_punch(), osd_quota_migration(), osd_read(), osd_read_prep(), osd_sa_xattr_list(), osd_write(), osd_write_commit(), osd_write_prep(), osd_xattr_del(), osd_xattr_get(), osd_xattr_list(), osd_xattr_set(), and osd_xattrs_destroy().
int osd_obj_map_delete (struct osd_thread_info * info, struct osd_device * osd, const struct lu_fid * fid, handle_t * th)
Definition at line 1019 of file osd_compat.c.
References cleanup(), ENTRY, fid_to_ostid(), GOTO, LASSERT, name, osd_device::od_ost_map, osd_obj_seq::oos_dirs, osd_obj_seq::oos_subdir_count, osd_obj_del_entry(), osd_oid_name(), osd_seq_load(), ostid_id(), ostid_seq(), osd_thread_info::oti_ostid, and RETURN.
Referenced by osd_oi_delete().
void osd_obj_map_fini (struct osd_device * dev)
Definition at line 508 of file osd_compat.c.
References osd_mdt_fini(), and osd_ost_fini().
Referenced by osd_device_fini(), and osd_device_init0().
int osd_obj_map_init (const struct lu_env * env, struct osd_device * osd)
Definition at line 469 of file osd_compat.c.
References ENTRY, osd_mdt_init(), osd_ost_fini(), osd_ost_init(), and RETURN.
Referenced by osd_device_init0().
int osd_obj_map_insert (struct osd_thread_info * info, struct osd_device * osd, const struct lu_fid * fid, const struct osd_inode_id * id, handle_t * th)
Definition at line 973 of file osd_compat.c.
References ENTRY, fid_to_ostid(), LASSERT, name, osd_device::od_ost_map, osd_obj_seq::oos_dirs, osd_obj_seq::oos_subdir_count, osd_obj_add_entry(), osd_obj_update_entry(), osd_oid_name(), osd_seq_load(), ostid_id(), ostid_seq(), osd_thread_info::oti_ostid, RETURN, and unlikely.
Referenced by osd_oi_insert().
int osd_obj_map_lookup (struct osd_thread_info * info, struct osd_device * osd, const struct lu_fid * fid, struct osd_inode_id * id)
Definition at line 911 of file osd_compat.c.
References dir, ENTRY, fid_to_ostid(), LASSERT, le32_to_cpu, name, osd_device::od_ost_map, osd_obj_map::om_root, osd_obj_seq::oos_dirs, osd_obj_seq::oos_subdir_count, osd_id_gen(), osd_iget(), osd_ldiskfs_find_entry, osd_oid_name(), OSD_OII_NOGEN, osd_seq_load(), ostid_id(), ostid_seq(), osd_thread_info::oti_child_dentry, osd_thread_info::oti_ostid, and RETURN.
Referenced by osd_oi_lookup().
int osd_obj_map_recover (struct osd_thread_info * info, struct osd_device * osd, struct inode * src_parent, struct dentry * src_child, const struct lu_fid * fid)
Definition at line 1078 of file osd_compat.c.
References dir, DTO_INDEX_DELETE, DTO_INDEX_INSERT, DTO_OBJECT_DELETE, ENTRY, fid_is_last_id(), fid_to_ostid(), GOTO, LASSERT, LDISKFS_HT_MISC, ll_vfs_dq_init, ll_vfs_unlink, name, osd_obj_seq::oos_dirs, osd_obj_seq::oos_root, osd_obj_seq::oos_subdir_count, osd_dto_credits_noquota, osd_journal_start_sb, osd_ldiskfs_add_entry(), osd_ldiskfs_find_entry, osd_oid_name(), osd_sb(), osd_seq_load(), ostid_id(), ostid_seq(), osd_thread_info::oti_child_dentry, osd_thread_info::oti_ostid, RETURN, and unlikely.
Referenced by osd_ios_lf_fill().
int osd_obj_map_update (struct osd_thread_info * info, struct osd_device * osd, const struct lu_fid * fid, const struct osd_inode_id * id, handle_t * th)
Definition at line 1050 of file osd_compat.c.
References ENTRY, fid_to_ostid(), LASSERT, name, osd_obj_seq::oos_dirs, osd_obj_seq::oos_subdir_count, osd_obj_update_entry(), osd_oid_name(), osd_seq_load(), ostid_id(), ostid_seq(), osd_thread_info::oti_ostid, and RETURN.
Referenced by osd_oi_update().
int osd_obj_spec_insert (struct osd_thread_info * info, struct osd_device * osd, const struct lu_fid * fid, const struct osd_inode_id * id, handle_t * th)
Definition at line 1242 of file osd_compat.c.
References ENTRY, name, osd_obj_add_entry(), osd_object_spec_find(), and RETURN.
Referenced by osd_oi_insert().
int osd_obj_spec_lookup (struct osd_thread_info * info, struct osd_device * osd, const struct lu_fid * fid, struct osd_inode_id * id)
Definition at line 1263 of file osd_compat.c.
References ENTRY, fid_is_last_id(), ll_lookup_one_len(), name, osd_obj_seq::oos_root, osd_id_gen(), osd_lf_fid2name(), osd_sb(), osd_seq_load(), and RETURN.
Referenced by osd_oi_lookup().
int osd_obj_spec_update (struct osd_thread_info * info, struct osd_device * osd, const struct lu_fid * fid, const struct osd_inode_id * id, handle_t * th)
Definition at line 1221 of file osd_compat.c.
References ENTRY, name, osd_obj_update_entry(), osd_object_spec_find(), and RETURN.
Referenced by osd_oi_update().
static int osd_object_is_root (const struct osd_object * obj) [inline, static]
Definition at line 894 of file osd_internal.h.
References osd_object::oo_inode, osd_obj2dev(), and osd_sb().
Referenced by osd_iam_index_probe(), and osd_index_try().
static int osd_oi_fid2idx (struct osd_device * dev, const struct lu_fid * fid) [inline, static]
Definition at line 847 of file osd_internal.h.
References lu_fid::f_seq, and osd_device::od_oi_count.
Referenced by osd_fid2oi(), osd_fid_lookup(), and osd_scrub_check_update().
int osd_oii_insert (struct osd_device * dev, struct osd_idmap_cache * oic, int insert)
Definition at line 2935 of file osd_scrub.c.
References __u64, cfs_time_current_sec(), ENTRY, INIT_LIST_HEAD, list_add_tail(), list_empty(), now(), OBD_ALLOC_PTR, OBD_FREE_PTR, osd_device::od_full_scrub_threshold_rate, osd_device::od_scrub, osd_inconsistent_item::oii_cache, osd_inconsistent_item::oii_insert, osd_inconsistent_item::oii_list, osd_scrub::os_bad_oimap_count, osd_scrub::os_bad_oimap_time, osd_scrub::os_full_scrub, osd_scrub::os_inconsistent_items, osd_scrub::os_lock, osd_scrub::os_partial_scan, osd_scrub::os_thread, RETURN, SCRUB_BAD_OIMAP_DECAY_INTERVAL, ptlrpc_thread::t_ctl_waitq, thread, thread_is_running(), and unlikely.
Referenced by osd_consistency_check().
int osd_oii_lookup (struct osd_device * dev, const struct lu_fid * fid, struct osd_inode_id * id)
Definition at line 2990 of file osd_scrub.c.
References ENTRY, list_for_each_entry, lu_fid_eq(), osd_device::od_scrub, osd_idmap_cache::oic_fid, osd_idmap_cache::oic_lid, osd_inconsistent_item::oii_cache, osd_inconsistent_item::oii_list, osd_scrub::os_inconsistent_items, osd_scrub::os_lock, and RETURN.
Referenced by osd_fid_lookup().
int osd_ost_seq_exists (struct osd_thread_info * info, struct osd_device * osd, __u64 seq)
static struct osd_thread_info* osd_oti_get (const struct lu_env * env) [static, read]
Definition at line 938 of file osd_internal.h.
References lu_env::le_ctx, lu_context_key_get(), and osd_key.
Referenced by __osd_attr_init(), __osd_obj2dbuf(), __osd_object_attr_get(), __osd_oi_insert(), __osd_xattr_set(), fid_is_on_ost(), osd_acct_index_lookup(), osd_add_to_remote_parent(), osd_attr_set(), osd_check_lma(), osd_child_dentry_by_inode(), osd_create_local_agent_inode(), osd_declare_attr_set(), osd_declare_inode_qid(), osd_declare_object_create(), osd_declare_object_destroy(), osd_declare_quota(), osd_declare_xattr_set(), osd_declare_xattrs_destroy(), osd_delete_from_remote_parent(), osd_device_init0(), osd_dir_insert(), osd_dir_it_key(), osd_dir_it_key_size(), osd_dir_it_load(), osd_dir_it_next(), osd_dir_it_rec(), osd_dir_it_rec_size(), osd_dir_lookup(), osd_dirent_check_repair(), osd_dirent_reinsert(), osd_ea_add_rec(), osd_ea_fid_get(), osd_ea_lookup_rec(), osd_fid_lookup(), osd_find_or_add_seq(), osd_find_parent_fid(), osd_get_fid_by_oid(), osd_get_idx_for_ost_obj(), osd_get_pfid_from_linkea(), osd_idc_add(), osd_idc_find(), osd_idc_find_or_init(), osd_idx_ipd_get(), osd_index_delete(), osd_index_ea_delete(), osd_index_ea_insert(), osd_index_iam_delete(), osd_index_iam_insert(), osd_index_iam_lookup(), osd_index_insert(), osd_index_it_init(), osd_index_it_key(), osd_index_it_load(), osd_index_it_next(), osd_index_it_rec(), osd_index_lookup(), osd_init_lma(), osd_inode_time(), osd_it_acct_init(), osd_it_acct_key(), osd_it_acct_load(), osd_it_acct_next(), osd_it_acct_rec(), osd_it_ea_fini(), osd_it_ea_init(), osd_it_ea_rec(), osd_it_iam_get(), osd_it_iam_key(), osd_it_iam_rec(), osd_it_ipd_get(), osd_ldiskfs_it_fill(), osd_mdt_init(), osd_mount(), osd_object_create(), osd_object_delete(), osd_object_destroy(), osd_object_ea_create(), osd_object_init(), osd_object_read_lock(), osd_object_read_unlock(), osd_object_sync(), osd_object_write_lock(), osd_object_write_unlock(), osd_oi_create(), osd_oi_init(), osd_oi_lookup(), osd_ost_init(), osd_otable_it_preload(), osd_process_scheduled_agent_removals(), osd_quota_migration(), osd_read_prep(), osd_scrub_cleanup(), osd_scrub_main(), osd_scrub_setup(), osd_seq_exists(), osd_statfs(), osd_trans_create(), osd_trans_declare_op(), osd_trans_dump_creds(), osd_trans_exec_check(), osd_trans_exec_op(), osd_trans_start(), osd_trans_stop(), osd_unlinked_drain(), osd_write_commit(), osd_write_locked(), osd_write_prep(), osd_xattr_del(), osd_xattr_get(), osd_xattr_list(), osd_xattr_set(), osd_xattrs_destroy(), and osd_zap_cursor_retrieve_value().
int osd_quota_migration (const struct lu_env * env, struct dt_object * dt)
Definition at line 630 of file osd_quota.c.
References ADMIN_GRP, ADMIN_USR, CERROR, DFID, dt_object::do_lu, dt_locate(), dt_lookup_dir(), dt_object_exists(), dt_root_get(), dt_version_get(), ENTRY, fname, GOTO, LCONSOLE_WARN, lu_object_put(), OBJECTS, osd_device::od_dt_dev, osd_device::od_svname, osd_dt_obj(), osd_obj2dev(), osd_oti_get(), osd_thread_info::oti_fid, PFID, RETURN, and version.
Referenced by osd_index_try().
struct dt_rec* osd_quota_pack (struct osd_object * obj, const struct dt_rec * rec, union lquota_rec * quota_rec) [read]
Definition at line 446 of file osd_quota.c.
References iam_container::ic_descr, iam_descr::id_rec_size, LASSERT, osd_directory::od_container, osd_object::oo_dir, and osd_quota_swab().
Referenced by osd_index_iam_insert().
void osd_quota_unpack (struct osd_object * obj, const struct dt_rec * rec)
Definition at line 465 of file osd_quota.c.
References iam_container::ic_descr, iam_descr::id_rec_size, LASSERT, osd_directory::od_container, osd_object::oo_dir, and osd_quota_swab().
Referenced by osd_index_iam_lookup(), and osd_it_iam_rec().
static unsigned long osd_remote_parent_ino (struct osd_device * dev) [inline, static]
Definition at line 1202 of file osd_internal.h.
References osd_device::od_mdt_map, and osd_mdobj_map::omm_remote_parent.
Referenced by osd_ea_lookup_rec(), osd_iit_iget(), and osd_it_ea_rec().
static struct super_block* osd_sb (const struct osd_device * dev) [static, read]
Definition at line 889 of file osd_internal.h.
References osd_device::od_mnt.
Referenced by __osd_ea_add_rec(), __osd_init_iobuf(), osd_acct_index_lookup(), osd_acct_obj_lookup(), osd_commit_async(), osd_conf_get(), osd_consistency_check(), osd_declare_qid(), osd_declare_write(), osd_declare_write_commit(), osd_declare_xattr_del(), osd_declare_xattr_set(), osd_dirent_check_repair(), osd_fid_lookup(), osd_health_check(), osd_iget(), osd_iget_check(), osd_iget_fid(), osd_iit_iget(), osd_index_ea_insert(), osd_initial_OI_scrub(), osd_inode_iteration(), osd_ios_ROOT_scan(), osd_ios_scan_one(), osd_it_ea_init(), osd_journal(), osd_last_rcvd_subdir_count(), osd_ldiskfs_filldir(), osd_lma_self_repair(), osd_mdt_init(), osd_mkfile(), osd_mount(), osd_obj_add_entry(), osd_obj_map_recover(), osd_obj_spec_lookup(), osd_object_is_root(), osd_object_spec_find(), osd_oi_index_create_one(), osd_oi_index_open(), osd_oi_init(), osd_oi_insert(), osd_oi_lookup(), osd_oi_table_open(), osd_ost_init(), osd_otable_it_load(), osd_process_scheduled_agent_removals(), osd_remove_ois(), osd_ro(), osd_scrub2sb(), osd_scrub_convert_ff(), osd_scrub_file_store(), osd_scrub_join(), osd_scrub_prep(), osd_scrub_refresh_mapping(), osd_scrub_setup(), osd_statfs(), osd_sync(), osd_trans_start(), and osd_umount().
void osd_scrub_cleanup (const struct lu_env * env, struct osd_device * dev)
Definition at line 2662 of file osd_scrub.c.
References LASSERT, osd_device::od_oi_table, osd_device::od_otable_it, osd_device::od_scrub, osd_scrub::os_inode, osd_oi_fini(), osd_oti_get(), and osd_scrub_stop().
Referenced by osd_device_fini(), and osd_device_init0().
int osd_scrub_dump (struct seq_file * m, struct osd_device * dev)
Definition at line 3071 of file osd_scrub.c.
References __u64, cfs_duration_sec(), cfs_time_current(), HALF_SEC, LPU64, osd_device::od_scrub, osd_scrub::os_file, osd_scrub::os_lf_failed, osd_scrub::os_lf_repaired, osd_scrub::os_lf_scanned, osd_scrub::os_new_checked, osd_scrub::os_pos_current, osd_scrub::os_rwsem, osd_scrub::os_thread, osd_scrub::os_time_last_checkpoint, scrub_bits_dump(), scrub_pos_dump(), scrub_time_dump(), scrub_file::sf_flags, scrub_file::sf_items_checked, scrub_file::sf_items_failed, scrub_file::sf_items_igif, scrub_file::sf_items_noscrub, scrub_file::sf_items_updated, scrub_file::sf_items_updated_prior, scrub_file::sf_magic, scrub_file::sf_oi_count, scrub_file::sf_param, scrub_file::sf_pos_first_inconsistent, scrub_file::sf_pos_last_checkpoint, scrub_file::sf_pos_latest_start, scrub_file::sf_run_time, scrub_file::sf_status, scrub_file::sf_success_count, scrub_file::sf_time_last_checkpoint, scrub_file::sf_time_last_complete, scrub_file::sf_time_latest_start, and thread_is_running().
void osd_scrub_file_reset (struct osd_scrub * scrub, __u8 * uuid, __u64 flags)
Definition at line 272 of file osd_scrub.c.
References CDEBUG, D_LFSCK, LPX64, osd_scrub::os_file, osd_scrub::os_in_join, osd_scrub2name(), SF_AUTO, scrub_file::sf_flags, scrub_file::sf_items_checked, scrub_file::sf_items_failed, scrub_file::sf_items_igif, scrub_file::sf_items_noscrub, scrub_file::sf_items_updated, scrub_file::sf_items_updated_prior, scrub_file::sf_pos_first_inconsistent, scrub_file::sf_pos_last_checkpoint, scrub_file::sf_pos_latest_start, scrub_file::sf_run_time, scrub_file::sf_status, scrub_file::sf_time_last_checkpoint, scrub_file::sf_time_latest_start, scrub_file::sf_uuid, and SS_INIT.
Referenced by osd_ios_ROOT_scan(), osd_ios_scan_one(), osd_oi_init(), osd_scrub_join(), osd_scrub_prep(), and osd_scrub_setup().
int osd_scrub_file_store (struct osd_scrub * scrub)
Definition at line 334 of file osd_scrub.c.
References CDEBUG, cfs_time_current(), cfs_time_seconds(), credits, D_LFSCK, DTO_WRITE_BASE, DTO_WRITE_BLOCK, LDISKFS_HT_MISC, osd_device::od_scrub, osd_scrub::os_file, osd_scrub::os_file_disk, osd_scrub::os_inode, osd_scrub::os_time_last_checkpoint, osd_scrub::os_time_next_checkpoint, osd_dto_credits_noquota, osd_journal_start_sb, osd_ldiskfs_write_record(), osd_sb(), osd_scrub2name(), osd_scrub_file_to_le(), and SCRUB_CHECKPOINT_INTERVAL.
Referenced by osd_ios_OBJECTS_scan(), osd_ios_ROOT_scan(), osd_ios_scan_one(), osd_oi_init(), osd_scrub_checkpoint(), osd_scrub_join(), osd_scrub_post(), osd_scrub_prep(), and osd_scrub_setup().
int osd_scrub_setup (const struct lu_env * env, struct osd_device * dev)
Definition at line 2489 of file osd_scrub.c.
References CERROR, class_uuid_unparse(), ENTRY, lvfs_run_ctxt::fs, GOTO, INIT_LIST_HEAD, LMAC_NOT_IN_OI, lu_igif_build(), OBD_ALLOC_PTR, OBD_FREE_PTR, OBD_SET_CTXT_MAGIC(), osd_device::od_check_ff, osd_device::od_igif_inoi, osd_device::od_is_ost, osd_device::od_maybe_new, osd_device::od_mnt, osd_device::od_noscrub, osd_device::od_scrub, osd_scrub::os_ctxt, osd_scrub::os_file, osd_scrub::os_inconsistent_items, osd_scrub::os_inode, osd_scrub::os_lock, osd_scrub::os_pos_current, osd_scrub::os_rwsem, osd_scrub::os_thread, osd_ea_fid_set(), osd_initial_OI_scrub(), osd_oi_fini(), osd_oi_init(), osd_oti_get(), osd_sb(), osd_scrub_file_init(), osd_scrub_file_load(), osd_scrub_file_reset(), osd_scrub_file_store(), osd_scrub_start(), osd_thread_info::oti_fid, pop_ctxt(), push_ctxt(), lvfs_run_ctxt::pwd, lvfs_run_ctxt::pwdmnt, RETURN, SF_AUTO, scrub_file::sf_flags, SF_INCONSISTENT, scrub_file::sf_internal_flags, scrub_file::sf_pos_last_checkpoint, SF_RECREATED, scrub_file::sf_status, scrub_file::sf_success_count, SF_UPGRADE, scrub_file::sf_uuid, SIF_NO_HANDLE_OLD_FID, SS_AUTO_FULL, SS_CRASHED, SS_INIT, SS_PAUSED, SS_SCANNING, ptlrpc_thread::t_ctl_waitq, and obd_uuid::uuid.
Referenced by osd_device_init0().
int osd_scrub_start (struct osd_device * dev, __u32 flags)
Definition at line 2442 of file osd_scrub.c.
References do_osd_scrub_start(), ENTRY, osd_device::od_otable_mutex, and RETURN.
Referenced by osd_consistency_check(), osd_fid_lookup(), and osd_scrub_setup().
static struct seq_server_site* osd_seq_site (struct osd_device * osd) [static, read]
Definition at line 920 of file osd_internal.h.
References dt_device::dd_lu_dev, lu_site::ld_seq_site, lu_device::ld_site, and osd_device::od_dt_dev.
Referenced by fid_is_on_ost(), osd_fid_init(), osd_fld_lookup(), osd_remote_fid(), and osd_seq_exists().
int osd_statfs (const struct lu_env * env, struct dt_device * dev, struct obd_statfs * sfs)
Definition at line 1586 of file osd_handler.c.
static void osd_trans_declare_op (const struct lu_env * env, struct osd_thandle * oh, unsigned int op, int credits) [inline, static]
Definition at line 1003 of file osd_internal.h.
References CWARN, LASSERT, libcfs_debug_dumpstack, osd_dt_dev(), osd_name(), OSD_OT_MAX, osd_oti_get(), osd_thandle::ot_credits, osd_thandle::ot_handle, osd_thandle::ot_super, osd_thread_info::oti_declare_ops, osd_thread_info::oti_declare_ops_cred, thandle::th_dev, and unlikely.
Referenced by osd_declare_attr_set(), osd_declare_object_create(), osd_declare_object_destroy(), osd_declare_object_ref_add(), osd_declare_object_ref_del(), osd_declare_punch(), osd_declare_qid(), osd_declare_write(), osd_declare_write_commit(), osd_declare_xattr_del(), osd_declare_xattr_set(), osd_index_declare_ea_delete(), osd_index_declare_ea_insert(), osd_index_declare_iam_delete(), and osd_index_declare_iam_insert().
void osd_trans_dump_creds (const struct lu_env * env, struct thandle * th)
Definition at line 1252 of file osd_handler.c.
References CWARN, LASSERT, OSD_OT_ATTR_SET, OSD_OT_CREATE, OSD_OT_DELETE, OSD_OT_DESTROY, OSD_OT_INSERT, OSD_OT_PUNCH, OSD_OT_QUOTA, OSD_OT_REF_ADD, OSD_OT_REF_DEL, OSD_OT_WRITE, OSD_OT_XATTR_SET, osd_oti_get(), osd_thandle::ot_super, osd_thread_info::oti_declare_ops, osd_thread_info::oti_declare_ops_cred, and osd_thread_info::oti_declare_ops_used.
Referenced by osd_trans_exec_check(), osd_trans_exec_op(), and osd_trans_start().
static void osd_trans_exec_check (const struct lu_env * env, struct thandle * th, unsigned int op) [inline, static]
Definition at line 1090 of file osd_internal.h.
References CWARN, LBUG, OSD_OT_QUOTA, osd_oti_get(), osd_trans_dump_creds(), osd_thandle::ot_handle, osd_thandle::ot_super, osd_thread_info::oti_credits_before, osd_thread_info::oti_declare_ops_cred, osd_thread_info::oti_declare_ops_used, and unlikely.
Referenced by __osd_object_create(), __osd_oi_insert(), osd_attr_set(), osd_index_ea_delete(), osd_index_ea_insert(), osd_index_iam_delete(), osd_index_iam_insert(), osd_object_destroy(), osd_object_ref_add(), osd_object_ref_del(), osd_write(), osd_write_commit(), osd_xattr_del(), and osd_xattr_set().
static void osd_trans_exec_op (const struct lu_env * env, struct thandle * th, unsigned int op) [inline, static]
Definition at line 1025 of file osd_internal.h.
References CERROR, CWARN, LASSERT, LBUG, libcfs_debug_dumpstack, osd_dt_dev(), osd_name(), OSD_OT_CREATE, OSD_OT_DESTROY, OSD_OT_MAX, OSD_OT_REF_ADD, OSD_OT_REF_DEL, osd_oti_get(), osd_trans_dump_creds(), osd_transaction_size, osd_thandle::ot_credits, osd_thandle::ot_handle, osd_thandle::ot_super, osd_thread_info::oti_credits_before, osd_thread_info::oti_declare_ops_cred, osd_thread_info::oti_declare_ops_used, thandle::th_dev, and unlikely.
Referenced by __osd_object_create(), __osd_oi_insert(), osd_attr_set(), osd_index_ea_delete(), osd_index_ea_insert(), osd_index_iam_delete(), osd_index_iam_insert(), osd_object_destroy(), osd_object_ref_add(), osd_object_ref_del(), osd_punch(), osd_write(), osd_write_commit(), osd_xattr_del(), and osd_xattr_set().
int walk_block_dqentry (const struct lu_env * env, struct osd_object * obj, int type, uint blk, uint index, struct osd_it_quota * it)
Search from index within the leaf block blk, and fill the it with the first valid entry.
Return values:
+ve,no valid entry found
0,entry found
-ve,unexpected failure
Definition at line 196 of file osd_quota_fmt.c.
References buf, CERROR, lustre_disk_dqblk_v2::dqb_id, lustre_disk_dqdbheader::dqdh_entries, emptydquot, ENTRY, freedqbuf(), getdqbuf(), GETENTRIES, GOTO, LASSERT, le16_to_cpu, le32_to_cpu, list_for_each_entry, LUSTRE_DQBLKSIZE_BITS, LUSTRE_DQSTRINBLK, LUSTRE_DQTREEDEPTH, osd_it_quota::oiq_blk, osd_it_quota::oiq_id, osd_it_quota::oiq_index, osd_it_quota::oiq_list, osd_it_quota::oiq_offset, osd_quota_leaf::oql_blk, osd_quota_leaf::oql_link, quota_read_blk(), ret, and RETURN.
Referenced by osd_it_acct_next(), and walk_tree_dqentry().
int walk_tree_dqentry (const struct lu_env * env, struct osd_object * obj, int type, uint blk, int depth, uint index, struct osd_it_quota * it)
Search from index within the tree block blk, and fill the it with the first valid entry.
Return values:
+ve,no valid entry found
0,entry found
-ve,unexpected failure
Definition at line 260 of file osd_quota_fmt.c.
References buf, CERROR, ENTRY, freedqbuf(), getdqbuf(), le32_to_cpu, LUSTRE_DQTREEDEPTH, osd_it_quota::oiq_blk, osd_it_quota::oiq_index, quota_read_blk(), ret, RETURN, walk_block_dqentry(), and walk_tree_dqentry().
Referenced by osd_it_acct_get(), osd_it_acct_next(), and walk_tree_dqentry().
Variable Documentation
struct kmem_cache* dynlock_cachep
Definition at line 94 of file osd_handler.c.
Referenced by dynlock_lock(), and dynlock_unlock().
int ldiskfs_pdo
Definition at line 85 of file osd_handler.c.
Referenced by osd_fid_lookup(), and osd_mkfile().
int ldiskfs_track_declares_assert
Definition at line 89 of file osd_handler.c.
struct dt_index_operations osd_acct_index_ops
Quota/Accounting handling.
Definition at line 420 of file osd_quota.c.
Referenced by osd_index_try().
struct dt_body_operations osd_body_ops
Definition at line 1945 of file osd_io.c.
Referenced by osd_declare_object_create(), osd_object_create(), osd_object_ea_create(), and osd_object_init0().
struct dt_body_operations osd_body_ops_new
Definition at line 1941 of file osd_io.c.
Referenced by osd_object_create(), osd_object_ea_create(), and osd_object_init().
const int osd_dto_credits_noquota[]
Note: we do not count into QUOTA here.
If we mount with --data_journal we may need more.
Definition at line 1782 of file osd_handler.c.
Referenced by osd_declare_punch(), osd_lma_self_repair(), osd_obj_map_recover(), osd_scrub_convert_ff(), osd_scrub_file_store(), and osd_scrub_refresh_mapping().
struct lu_context_key osd_key [read]
Definition at line 6122 of file osd_handler.c.
struct lu_device_operations osd_lu_ops
Definition at line 6701 of file osd_handler.c.
struct dt_index_operations osd_otable_ops
Definition at line 2915 of file osd_scrub.c.
Referenced by osd_index_try().
int osd_trans_declare_op2rb[]
Definition at line 131 of file osd_handler.c.
struct osd_it_ea_dirent packed
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.