Lustre: lustre/osd-ldiskfs/osd_oi.c File Reference
lustre/osd-ldiskfs/osd_oi.c File Reference
#include <linux/module.h>
#include <lustre_ver.h>
#include <obd.h>
#include <obd_support.h>
#include <lustre_fid.h>
#include <dt_object.h>
#include "osd_oi.h"
#include "osd_internal.h"
#include "osd_scrub.h"
Defines
#define DEBUG_SUBSYSTEM S_OSD
#define OSD_OI_NAME_BASE "oi.16"
Functions
module_param (osd_oi_count, int, 0444)
MODULE_PARM_DESC (osd_oi_count,"Number of Object Index containers to be created, it's only valid for new filesystem.")
static void osd_oi_table_put (struct osd_thread_info *info, struct osd_oi **oi_table, unsigned oi_count)
static int osd_oi_index_create_one (struct osd_thread_info *info, struct osd_device *osd, const char *name, struct dt_index_features *feat)
static struct inode * osd_oi_index_open (struct osd_thread_info *info, struct osd_device *osd, const char *name, struct dt_index_features *f, bool create)
static int osd_oi_open (struct osd_thread_info *info, struct osd_device *osd, char *name, struct osd_oi **oi_slot, bool create)
Open an OI(Ojbect Index) container.
static int osd_oi_table_open (struct osd_thread_info *info, struct osd_device *osd, struct osd_oi **oi_table, unsigned oi_count, bool create)
Open OI(Object Index) table.
static int osd_remove_oi_one (struct dentry *parent, const char *name, int namelen)
static int osd_remove_ois (struct osd_thread_info *info, struct osd_device *osd)
int osd_oi_init (struct osd_thread_info *info, struct osd_device *osd, bool restored)
void osd_oi_fini (struct osd_thread_info *info, struct osd_device *osd)
static int fid_is_fs_root (const struct lu_fid *fid)
static int osd_oi_iam_lookup (struct osd_thread_info *oti, struct osd_oi *oi, struct dt_rec *rec, const struct dt_key *key)
int fid_is_on_ost (struct osd_thread_info *info, struct osd_device *osd, const struct lu_fid *fid, enum oi_check_flags flags)
static int __osd_oi_lookup (struct osd_thread_info *info, struct osd_device *osd, const struct lu_fid *fid, struct osd_inode_id *id)
int osd_oi_lookup (struct osd_thread_info *info, struct osd_device *osd, const struct lu_fid *fid, struct osd_inode_id *id, enum oi_check_flags flags)
static int osd_oi_iam_refresh (struct osd_thread_info *oti, struct osd_oi *oi, const struct dt_rec *rec, const struct dt_key *key, handle_t *th, bool insert)
int osd_oi_insert (struct osd_thread_info *info, struct osd_device *osd, const struct lu_fid *fid, const struct osd_inode_id *id, handle_t *th, enum oi_check_flags flags)
static int osd_oi_iam_delete (struct osd_thread_info *oti, struct osd_oi *oi, const struct dt_key *key, handle_t *th)
int osd_oi_delete (struct osd_thread_info *info, struct osd_device *osd, const struct lu_fid *fid, handle_t *th, enum oi_check_flags flags)
int osd_oi_update (struct osd_thread_info *info, struct osd_device *osd, const struct lu_fid *fid, const struct osd_inode_id *id, handle_t *th, enum oi_check_flags flags)
int osd_oi_mod_init (void)
Variables
static unsigned int osd_oi_count = OSD_OI_FID_NR
static struct mutex oi_init_lock
to serialize concurrent OI index initialization
static struct dt_index_features oi_feat
Define Documentation
#define DEBUG_SUBSYSTEM S_OSD
Definition at line 43 of file osd_oi.c.
#define OSD_OI_NAME_BASE "oi.16"
Definition at line 79 of file osd_oi.c.
Referenced by osd_oi_init(), osd_oi_table_open(), and osd_remove_ois().
Function Documentation
static int __osd_oi_lookup (struct osd_thread_info * info, struct osd_device * osd, const struct lu_fid * fid, struct osd_inode_id * id) [static]
Definition at line 586 of file osd_oi.c.
References dt_key, fid_cpu_to_be(), osd_fid2oi(), osd_id_unpack(), osd_oi_iam_lookup(), and osd_thread_info::oti_fid2.
Referenced by osd_oi_lookup().
static int fid_is_fs_root (const struct lu_fid * fid) [inline, static]
Definition at line 508 of file osd_oi.c.
References fid_oid(), FID_SEQ_LOCAL_FILE, OSD_FS_ROOT_OID, and unlikely.
Referenced by osd_oi_lookup().
int fid_is_on_ost (struct osd_thread_info * info, struct osd_device * osd, const struct lu_fid * fid, enum oi_check_flags flags)
Definition at line 548 of file osd_oi.c.
References CERROR, DFID, ENTRY, fid_is_idif(), fid_is_igif(), fid_is_last_id(), fid_is_llog(), fid_is_local_file(), fid_is_name_llog(), fid_is_quota(), fld_range_is_ost(), OI_CHECK_FLD, OI_KNOWN_ON_OST, osd_fld_lookup(), osd_name(), osd_seq_site(), osd_thread_info::oti_env, osd_thread_info::oti_seq_range, PFID, RETURN, and unlikely.
Referenced by osd_fid_lookup(), osd_get_name_n_idx(), osd_object_ea_create(), osd_oi_delete(), osd_oi_insert(), osd_oi_lookup(), and osd_oi_update().
module_param (osd_oi_count , int , 0444)
MODULE_PARM_DESC (osd_oi_count , "Number of Object Index containers to be created, it's only valid for new filesystem.")
int osd_oi_delete (struct osd_thread_info * info, struct osd_device * osd, const struct lu_fid * fid, handle_t * th, enum oi_check_flags flags)
Definition at line 778 of file osd_oi.c.
References dt_key, fid_cpu_to_be(), fid_is_last_id(), fid_is_llog(), fid_is_on_ost(), fid_zero(), lu_fid_eq(), osd_idmap_cache::oic_fid, osd_fid2oi(), osd_obj_map_delete(), osd_oi_iam_delete(), osd_thread_info::oti_cache, and osd_thread_info::oti_fid2.
Referenced by osd_object_destroy(), and osd_scrub_refresh_mapping().
void osd_oi_fini (struct osd_thread_info * info, struct osd_device * osd)
Definition at line 496 of file osd_oi.c.
References OBD_FREE, osd_device::od_oi_count, osd_device::od_oi_table, OSD_OI_FID_NR_MAX, osd_oi_table_put(), and unlikely.
Referenced by osd_device_fini(), osd_scrub_cleanup(), and osd_scrub_setup().
static int osd_oi_iam_delete (struct osd_thread_info * oti, struct osd_oi * oi, const struct dt_key * key, handle_t * th) [static]
Definition at line 752 of file osd_oi.c.
References ENTRY, iam_delete(), LASSERT, LINVRNT, ll_vfs_dq_init, osd_directory::od_container, osd_oi::oi_dir, osd_oi::oi_inode, osd_idx_ipd_get(), osd_invariant, osd_ipd_put(), osd_thread_info::oti_env, RETURN, and unlikely.
Referenced by osd_oi_delete().
static int osd_oi_iam_lookup (struct osd_thread_info * oti, struct osd_oi * oi, struct dt_rec * rec, const struct dt_key * key) [static]
Definition at line 515 of file osd_oi.c.
References ENTRY, iam_it_fini(), iam_it_get(), iam_it_init(), iam_it_put(), iam_reccpy(), iam_iterator::ii_path, iam_path::ip_leaf, LASSERT, LINVRNT, osd_directory::od_container, osd_oi::oi_dir, osd_oi::oi_inode, osd_idx_ipd_get(), osd_invariant, osd_ipd_put(), osd_thread_info::oti_env, osd_thread_info::oti_idx_it, and RETURN.
Referenced by __osd_oi_lookup().
static int osd_oi_iam_refresh (struct osd_thread_info * oti, struct osd_oi * oi, const struct dt_rec * rec, const struct dt_key * key, handle_t * th, bool insert) [static]
Definition at line 640 of file osd_oi.c.
References ENTRY, iam_insert(), iam_update(), LASSERT, LINVRNT, ll_vfs_dq_init, osd_directory::od_container, osd_oi::oi_dir, osd_oi::oi_inode, osd_idx_ipd_get(), osd_invariant, osd_ipd_put(), osd_thread_info::oti_env, RETURN, and unlikely.
Referenced by osd_oi_insert(), and osd_oi_update().
static int osd_oi_index_create_one (struct osd_thread_info * info, struct osd_device * osd, const char * name, struct dt_index_features * feat) [static]
Definition at line 103 of file osd_oi.c.
References dt_index_features::dif_flags, dt_index_features::dif_keysize_max, dt_index_features::dif_ptrsize, dt_index_features::dif_recsize_max, dir, DT_IND_VARKEY, iam_lfix_create(), iam_lvar_create(), LDISKFS_HT_MISC, LDISKFS_STATE_LUSTRE_NOSCRUB, le32_to_cpu, osd_child_dentry_by_inode(), osd_id_gen(), osd_iget(), osd_journal_start_sb, osd_ldiskfs_add_entry(), osd_ldiskfs_find_entry, OSD_OII_NOGEN, osd_sb(), osd_thread_info::oti_env, and osd_thread_info::oti_id.
Referenced by osd_oi_index_open().
static struct inode* osd_oi_index_open (struct osd_thread_info * info, struct osd_device * osd, const char * name, struct dt_index_features * f, bool create) [static, read]
Definition at line 159 of file osd_oi.c.
References LASSERT, ll_lookup_one_len(), osd_oi_index_create_one(), and osd_sb().
Referenced by osd_oi_open().
int osd_oi_init (struct osd_thread_info * info, struct osd_device * osd, bool restored)
Definition at line 386 of file osd_oi.c.
References CERROR, ENTRY, ergo, GOTO, LASSERT, OBD_ALLOC, OBD_FREE, osd_device::od_oi_count, osd_device::od_oi_table, osd_device::od_scrub, oi_init_lock, osd_scrub::os_file, osd_oi_count, OSD_OI_FID_NR_MAX, OSD_OI_NAME_BASE, osd_oi_open(), osd_oi_table_open(), osd_oi_table_put(), osd_remove_ois(), osd_sb(), osd_scrub_file_reset(), osd_scrub_file_store(), RETURN, SCRUB_OI_BITMAP_SIZE, scrub_file::sf_oi_bitmap, scrub_file::sf_oi_count, SF_RECREATED, scrub_file::sf_success_count, and SF_UPGRADE.
Referenced by osd_mount(), and osd_scrub_setup().
int osd_oi_insert (struct osd_thread_info * info, struct osd_device * osd, const struct lu_fid * fid, const struct osd_inode_id * id, handle_t * th, enum oi_check_flags flags)
Definition at line 671 of file osd_oi.c.
References CERROR, DFID, dt_key, fid_cpu_to_be(), fid_is_last_id(), fid_is_llog(), fid_is_on_ost(), FID_SEQ_LOCAL_FILE, lustre_mdt_attrs::lma_compat, lustre_mdt_attrs::lma_self_fid, LMAC_NOT_IN_OI, lu_fid_eq(), osd_inode_id::oii_gen, osd_inode_id::oii_ino, osd_fid2oi(), osd_get_lma(), osd_id_eq(), osd_id_pack(), osd_iget(), osd_is_ea_inode(), osd_obj_map_insert(), osd_obj_spec_insert(), osd_oi_iam_refresh(), osd_oi_lookup(), osd_sb(), osd_thread_info::oti_fid2, osd_thread_info::oti_id2, osd_thread_info::oti_mdt_attrs, osd_thread_info::oti_obj_dentry, PFID, and unlikely.
Referenced by __osd_oi_insert(), and osd_scrub_refresh_mapping().
int osd_oi_lookup (struct osd_thread_info * info, struct osd_device * osd, const struct lu_fid * fid, struct osd_inode_id * id, enum oi_check_flags flags)
Definition at line 604 of file osd_oi.c.
References __osd_oi_lookup(), fid_is_acct(), fid_is_fs_root(), fid_is_igif(), fid_is_last_id(), fid_is_llog(), fid_is_on_ost(), FID_SEQ_LOCAL_FILE, lu_igif_gen(), lu_igif_ino(), osd_device::od_igif_inoi, osd_acct_obj_lookup(), osd_id_gen(), osd_obj_map_lookup(), osd_obj_spec_lookup(), osd_sb(), and unlikely.
Referenced by osd_consistency_check(), osd_fid_lookup(), osd_idc_find_or_init(), osd_iget_check(), osd_ios_scan_one(), osd_oi_add_table(), osd_oi_find_or_create(), osd_oi_insert(), osd_oi_probe(), and osd_scrub_check_update().
int osd_oi_mod_init (void)
Definition at line 826 of file osd_oi.c.
References LCONSOLE_WARN, oi_init_lock, osd_oi_count, OSD_OI_FID_NR, OSD_OI_FID_NR_MAX, and size_roundup_power2().
Referenced by osd_init().
static int osd_oi_open (struct osd_thread_info * info, struct osd_device * osd, char * name, struct osd_oi ** oi_slot, bool create) [static]
Open an OI(Ojbect Index) container.
Parameters:
name Name of OI container
objp Pointer of returned OI
Return values:
0 success
-ve failure
Definition at line 215 of file osd_oi.c.
References dt_index_features::dif_keysize_max, dt_index_features::dif_keysize_min, dir, ENTRY, GOTO, iam_container_fini(), iam_container_init(), iam_container_setup(), LMAC_NOT_IN_OI, lu_igif_build(), OBD_ALLOC_PTR, OBD_FREE_PTR, osd_directory::od_container, osd_directory::od_descr, osd_oi::oi_dir, osd_oi::oi_inode, osd_ea_fid_set(), osd_oi_index_open(), osd_thread_info::oti_fid, and RETURN.
Referenced by osd_oi_init(), and osd_oi_table_open().
static int osd_oi_table_open (struct osd_thread_info * info, struct osd_device * osd, struct osd_oi ** oi_table, unsigned oi_count, bool create) [static]
Open OI(Object Index) table.
If oi_count is zero, which means caller doesn't know how many OIs there will be, this function can either return 0 for new filesystem, or number of OIs on existed filesystem.
If oi_count is non-zero, which means caller does know number of OIs on filesystem, this function should return the exactly same number on success, or error code in failure.
Parameters:
oi_count Number of expected OI containers
create Create OIs if doesn't exist
Return values:
+ve number of opened OI containers
0 no OI containers found
-ve failure
Definition at line 286 of file osd_oi.c.
References CERROR, ENTRY, LASSERT, name, osd_device::od_scrub, osd_scrub::os_file, OSD_OI_FID_NR_MAX, OSD_OI_NAME_BASE, osd_oi_open(), osd_oi_table_put(), osd_sb(), RETURN, and scrub_file::sf_oi_bitmap.
Referenced by osd_oi_init().
static void osd_oi_table_put (struct osd_thread_info * info, struct osd_oi ** oi_table, unsigned oi_count) [static]
Definition at line 81 of file osd_oi.c.
References iam_container_fini(), iam_container::ic_object, LASSERT, OBD_FREE_PTR, osd_directory::od_container, osd_oi::oi_dir, and osd_oi::oi_inode.
Referenced by osd_oi_fini(), osd_oi_init(), and osd_oi_table_open().
int osd_oi_update (struct osd_thread_info * info, struct osd_device * osd, const struct lu_fid * fid, const struct osd_inode_id * id, handle_t * th, enum oi_check_flags flags)
Definition at line 799 of file osd_oi.c.
References dt_key, fid_cpu_to_be(), fid_is_last_id(), fid_is_llog(), fid_is_on_ost(), FID_SEQ_LOCAL_FILE, osd_fid2oi(), osd_id_pack(), osd_obj_map_update(), osd_obj_spec_update(), osd_oi_iam_refresh(), osd_thread_info::oti_fid2, osd_thread_info::oti_id2, and unlikely.
Referenced by osd_scrub_refresh_mapping().
static int osd_remove_oi_one (struct dentry * parent, const char * name, int namelen) [static]
Definition at line 340 of file osd_oi.c.
References ll_lookup_one_len(), and ll_vfs_unlink.
Referenced by osd_remove_ois().
static int osd_remove_ois (struct osd_thread_info * info, struct osd_device * osd) [static]
Definition at line 357 of file osd_oi.c.
References CERROR, name, osd_device::od_scrub, osd_scrub::os_file, OSD_OI_NAME_BASE, osd_remove_oi_one(), osd_sb(), and scrub_file::sf_oi_count.
Referenced by osd_oi_init().
Variable Documentation
struct dt_index_features oi_feat [static]
Initial value:
 {
        .dif_flags       = DT_IND_UPDATE,
        .dif_recsize_min = sizeof(struct osd_inode_id),
        .dif_recsize_max = sizeof(struct osd_inode_id),
        .dif_ptrsize     = 4
}
Definition at line 72 of file osd_oi.c.
struct mutex oi_init_lock [static]
to serialize concurrent OI index initialization
Definition at line 70 of file osd_oi.c.
Referenced by osd_oi_init(), and osd_oi_mod_init().
unsigned int osd_oi_count = OSD_OI_FID_NR [static]
Definition at line 65 of file osd_oi.c.
Referenced by osd_oi_init(), osd_oi_mod_init(), and osd_options_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.