Lustre: lustre/osd-zfs/osd_oi.c File Reference
lustre/osd-zfs/osd_oi.c File Reference
#include <lustre_ver.h>
#include <libcfs/libcfs.h>
#include <obd_support.h>
#include <lustre_net.h>
#include <obd.h>
#include <obd_class.h>
#include <lustre_disk.h>
#include <lustre_fid.h>
#include "osd_internal.h"
#include <sys/dnode.h>
#include <sys/dbuf.h>
#include <sys/spa.h>
#include <sys/stat.h>
#include <sys/zap.h>
#include <sys/spa_impl.h>
#include <sys/zfs_znode.h>
#include <sys/dmu_tx.h>
#include <sys/dmu_objset.h>
#include <sys/dsl_prop.h>
#include <sys/sa_impl.h>
#include <sys/txg.h>
Data Structures
struct named_oid
Defines
#define DEBUG_SUBSYSTEM S_OSD
#define OSD_OI_FID_NR (1UL << 7)
#define OSD_OI_FID_NR_MAX (1UL << OSD_OI_FID_OID_BITS_MAX)
Functions
static char * oid2name (const unsigned long oid)
static int osd_oi_lookup (const struct lu_env *env, struct osd_device *o, uint64_t parent, const char *name, struct osd_oi *oi)
Lookup an existing OI by the given name.
static int osd_oi_create (const struct lu_env *env, struct osd_device *o, uint64_t parent, const char *name, uint64_t *child)
Create a new OI with the given name.
static int osd_oi_find_or_create (const struct lu_env *env, struct osd_device *o, uint64_t parent, const char *name, uint64_t *child)
int osd_fld_lookup (const struct lu_env *env, struct osd_device *osd, u64 seq, struct lu_seq_range *range)
Lookup the target index/flags of the fid, so it will know where the object is located (tgt index) and it is MDT or OST object.
int fid_is_on_ost (const struct lu_env *env, struct osd_device *osd, const struct lu_fid *fid)
static struct osd_seq * osd_seq_find_locked (struct osd_seq_list *seq_list, u64 seq)
static struct osd_seq * osd_seq_find (struct osd_seq_list *seq_list, u64 seq)
static struct osd_seq * osd_find_or_add_seq (const struct lu_env *env, struct osd_device *osd, u64 seq)
static uint64_t osd_get_idx_for_ost_obj (const struct lu_env *env, struct osd_device *osd, const struct lu_fid *fid, char *buf)
static void osd_fid2str (char *buf, const struct lu_fid *fid)
static uint64_t osd_get_idx_for_fid (struct osd_device *osd, const struct lu_fid *fid, char *buf)
uint64_t osd_get_name_n_idx (const struct lu_env *env, struct osd_device *osd, const struct lu_fid *fid, char *buf)
static int fid_is_fs_root (const struct lu_fid *fid)
int osd_fid_lookup (const struct lu_env *env, struct osd_device *dev, const struct lu_fid *fid, uint64_t *oid)
static void osd_oi_remove_table (const struct lu_env *env, struct osd_device *o, int key)
Close an entry in a specific slot.
static int osd_oi_add_table (const struct lu_env *env, struct osd_device *o, char *name, int key)
Allocate and open a new entry in the specified unused slot.
static void osd_oi_close_table (const struct lu_env *env, struct osd_device *o)
Depopulate the OI table.
static int osd_oi_open_table (const struct lu_env *env, struct osd_device *o, int count)
Populate the OI table based.
static int osd_oi_probe (const struct lu_env *env, struct osd_device *o, int *count)
Determine if the type and number of OIs used by this file system.
static void osd_ost_seq_init (const struct lu_env *env, struct osd_device *osd)
static void osd_ost_seq_fini (const struct lu_env *env, struct osd_device *osd)
static int osd_oi_init_compat (const struct lu_env *env, struct osd_device *o)
Create /O subdirectory to map legacy OST objects for compatibility.
int osd_oi_init (const struct lu_env *env, struct osd_device *o)
Initialize the OIs by either opening or creating them as needed.
void osd_oi_fini (const struct lu_env *env, struct osd_device *o)
int osd_options_init (void)
Variables
unsigned int osd_oi_count = OSD_OI_FID_NR
static struct named_oid oids []
Define Documentation
#define DEBUG_SUBSYSTEM S_OSD
Definition at line 44 of file osd_oi.c.
#define OSD_OI_FID_NR (1UL << 7)
Definition at line 70 of file osd_oi.c.
#define OSD_OI_FID_NR_MAX (1UL << OSD_OI_FID_OID_BITS_MAX)
Definition at line 71 of file osd_oi.c.
Function Documentation
static int fid_is_fs_root (const struct lu_fid * fid) [inline, static]
Definition at line 453 of file osd_oi.c.
References fid_oid(), FID_SEQ_LOCAL_FILE, and OSD_FS_ROOT_OID.
Referenced by osd_fid_lookup().
int fid_is_on_ost (const struct lu_env * env, struct osd_device * osd, const struct lu_fid * fid)
Definition at line 236 of file osd_oi.c.
References CERROR, DFID, ENTRY, fid_is_idif(), fid_is_llog(), fid_is_local_file(), fid_is_name_llog(), fid_is_quota(), fld_range_is_ost(), osd_fld_lookup(), osd_name(), osd_oti_get(), osd_thread_info::oti_seq_range, PFID, RETURN, and unlikely.
static char* oid2name (const unsigned long oid) [static]
Definition at line 101 of file osd_oi.c.
References named_oid::name.
Referenced by osd_get_name_n_idx(), and osd_oi_init_compat().
static void osd_fid2str (char * buf, const struct lu_fid * fid) [static]
Definition at line 400 of file osd_oi.c.
References DFID_NOBRACE, and PFID.
Referenced by osd_get_idx_for_fid().
int osd_fid_lookup (const struct lu_env * env, struct osd_device * dev, const struct lu_fid * fid, uint64_t * oid)
Definition at line 460 of file osd_oi.c.
References ACCT_USER_OID, buf, ENTRY, fid_is_acct(), fid_is_fs_root(), fid_oid(), luz_direntry::lzd_reg, OBD_FAIL_CHECK, OBD_FAIL_SRV_ENOENT, osd_device::od_igrp_oid, osd_device::od_iusr_oid, osd_device::od_os, osd_device::od_root, osd_get_name_n_idx(), osd_oti_get(), osd_thread_info::oti_buf, osd_thread_info::oti_zde, RETURN, unlikely, and zpl_direntry::zde_dnode.
Referenced by osd_object_init().
static struct osd_seq* osd_find_or_add_seq (const struct lu_env * env, struct osd_device * osd, u64 seq) [static, read]
Definition at line 287 of file osd_oi.c.
References CERROR, ENTRY, fid_seq_is_idif(), fid_seq_is_mdt0(), fid_seq_is_rsvd(), GOTO, INIT_LIST_HEAD, list_add(), LPU64, LPX64i, OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, osd_device::od_O_id, osd_device::od_seq_list, osd_oi::oi_zapid, osd_seq::os_compat_dirs, osd_seq::os_seq, osd_seq::os_seq_list, osd_seq::os_subdir_count, osd_name(), osd_oi_find_or_create(), OSD_OST_MAP_SIZE, osd_oti_get(), osd_seq_find(), osd_seq_list::osl_seq_init_sem, osd_seq_list::osl_seq_list, osd_seq_list::osl_seq_list_lock, osd_thread_info::oti_buf, osd_thread_info::oti_str, and RETURN.
Referenced by osd_get_idx_for_ost_obj().
int osd_fld_lookup (const struct lu_env * env, struct osd_device * osd, u64 seq, struct lu_seq_range * range)
Lookup the target index/flags of the fid, so it will know where the object is located (tgt index) and it is MDT or OST object.
Definition at line 210 of file osd_oi.c.
References fid_seq_in_fldb(), fid_seq_is_idif(), fld_local_lookup(), fld_range_set_any(), fld_range_set_mdt(), fld_range_set_ost(), idif_ost_idx(), LASSERT, lu_seq_range::lsr_index, osd_seq_site(), seq_server_site::ss_node_id, and seq_server_site::ss_server_fld.
static uint64_t osd_get_idx_for_fid (struct osd_device * osd, const struct lu_fid * fid, char * buf) [static]
Definition at line 412 of file osd_oi.c.
References LASSERT, osd_device::od_oi_count, osd_device::od_oi_table, osd_oi::oi_zapid, and osd_fid2str().
Referenced by osd_get_name_n_idx().
static uint64_t osd_get_idx_for_ost_obj (const struct lu_env * env, struct osd_device * osd, const struct lu_fid * fid, char * buf) [static]
Definition at line 368 of file osd_oi.c.
References CERROR, DFID, fid_is_last_id(), fid_to_ostid(), LASSERT, LPU64, osd_seq::os_compat_dirs, osd_find_or_add_seq(), osd_name(), OSD_OST_MAP_SIZE, osd_oti_get(), ostid_id(), and PFID.
Referenced by osd_get_name_n_idx().
uint64_t osd_get_name_n_idx (const struct lu_env * env, struct osd_device * osd, const struct lu_fid * fid, char * buf)
Definition at line 424 of file osd_oi.c.
References fid_is_acct(), fid_is_on_ost(), fid_oid(), FID_SEQ_ECHO, FID_SEQ_LOCAL_FILE, LASSERT, name, osd_device::od_root, oid2name(), osd_get_idx_for_fid(), osd_get_idx_for_ost_obj(), and unlikely.
Referenced by osd_declare_object_create(), osd_declare_object_destroy(), osd_fid_lookup(), osd_object_create(), and osd_object_destroy().
static int osd_oi_add_table (const struct lu_env * env, struct osd_device * o, char * name, int key) [static]
Allocate and open a new entry in the specified unused slot.
Definition at line 518 of file osd_oi.c.
References __osd_obj2dbuf(), LASSERT, OBD_ALLOC_PTR, OBD_FREE_PTR, osd_device::od_oi_table, osd_device::od_os, osd_device::od_root, osd_oi::oi_db, osd_oi::oi_zapid, and osd_oi_lookup().
Referenced by osd_oi_open_table().
static void osd_oi_close_table (const struct lu_env * env, struct osd_device * o) [static]
Depopulate the OI table.
Definition at line 547 of file osd_oi.c.
References osd_device::od_oi_count, and osd_oi_remove_table().
Referenced by osd_oi_fini(), and osd_oi_open_table().
static int osd_oi_create (const struct lu_env * env, struct osd_device * o, uint64_t parent, const char * name, uint64_t * child) [static]
Create a new OI with the given name.
Definition at line 140 of file osd_oi.c.
References __osd_zap_create(), IFTODT, lu_attr::la_gid, LA_GID, lu_attr::la_mode, LA_MODE, lu_attr::la_uid, LA_UID, lu_attr::la_valid, LASSERT, luz_direntry::lzd_reg, osd_device::od_os, osd_obj_tag, osd_oti_get(), osd_thread_info::oti_la, and osd_thread_info::oti_zde.
Referenced by osd_oi_find_or_create().
static int osd_oi_find_or_create (const struct lu_env * env, struct osd_device * o, uint64_t parent, const char * name, uint64_t * child) [static]
Definition at line 191 of file osd_oi.c.
References osd_oi::oi_zapid, osd_oi_create(), and osd_oi_lookup().
Referenced by osd_find_or_add_seq(), osd_oi_init(), and osd_oi_init_compat().
void osd_oi_fini (const struct lu_env * env, struct osd_device * o)
Definition at line 731 of file osd_oi.c.
References ENTRY, EXIT, OBD_FREE, osd_device::od_oi_count, osd_device::od_oi_table, osd_oi_close_table(), and osd_ost_seq_fini().
int osd_oi_init (const struct lu_env * env, struct osd_device * o)
Initialize the OIs by either opening or creating them as needed.
Definition at line 688 of file osd_oi.c.
References DMU_OSD_OI_NAME_BASE, ENTRY, LASSERT, OBD_ALLOC, OBD_FREE, osd_device::od_oi_count, osd_device::od_oi_table, osd_device::od_root, osd_oi_count, osd_oi_find_or_create(), osd_oi_init_compat(), osd_oi_open_table(), osd_oi_probe(), osd_oti_get(), osd_thread_info::oti_buf, and RETURN.
static int osd_oi_init_compat (const struct lu_env * env, struct osd_device * o) [static]
Create /O subdirectory to map legacy OST objects for compatibility.
Definition at line 653 of file osd_oi.c.
References ACCT_GROUP_OID, ACCT_USER_OID, ENTRY, osd_device::od_igrp_oid, osd_device::od_iusr_oid, osd_device::od_O_id, osd_device::od_root, oid2name(), osd_oi_find_or_create(), osd_ost_seq_init(), and RETURN.
Referenced by osd_oi_init().
static int osd_oi_lookup (const struct lu_env * env, struct osd_device * o, uint64_t parent, const char * name, struct osd_oi * oi) [static]
Lookup an existing OI by the given name.
Definition at line 117 of file osd_oi.c.
References luz_direntry::lzd_reg, osd_device::od_os, osd_oi::oi_name, osd_oi::oi_zapid, osd_oti_get(), osd_thread_info::oti_zde, and strlcpy().
static int osd_oi_open_table (const struct lu_env * env, struct osd_device * o, int count) [static]
Populate the OI table based.
Definition at line 559 of file osd_oi.c.
References DMU_OSD_OI_NAME_BASE, ENTRY, name, osd_oi_add_table(), osd_oi_close_table(), and RETURN.
Referenced by osd_oi_init().
static int osd_oi_probe (const struct lu_env * env, struct osd_device * o, int * count) [static]
Determine if the type and number of OIs used by this file system.
Definition at line 581 of file osd_oi.c.
References DMU_OSD_OI_NAME_BASE, ENTRY, name, osd_device::od_root, OSD_OI_FID_NR_MAX, osd_oi_lookup(), and RETURN.
Referenced by osd_oi_init().
static void osd_oi_remove_table (const struct lu_env * env, struct osd_device * o, int key) [static]
Close an entry in a specific slot.
Definition at line 499 of file osd_oi.c.
References LASSERT, OBD_FREE_PTR, osd_device::od_oi_table, osd_oi::oi_db, and osd_obj_tag.
Referenced by osd_oi_close_table().
int osd_options_init (void)
Definition at line 748 of file osd_oi.c.
References LCONSOLE_WARN, osd_oi_count, OSD_OI_FID_NR, OSD_OI_FID_NR_MAX, and size_roundup_power2().
Referenced by osd_init().
static void osd_ost_seq_fini (const struct lu_env * env, struct osd_device * osd) [static]
Definition at line 631 of file osd_oi.c.
References list_del(), list_for_each_entry_safe, OBD_FREE, osd_device::od_seq_list, osd_seq::os_compat_dirs, osd_seq::os_seq_list, osd_seq::os_subdir_count, osd_seq_list::osl_seq_list, and osd_seq_list::osl_seq_list_lock.
Referenced by osd_oi_fini().
static void osd_ost_seq_init (const struct lu_env * env, struct osd_device * osd) [static]
Definition at line 622 of file osd_oi.c.
References INIT_LIST_HEAD, osd_device::od_seq_list, osd_seq_list::osl_seq_init_sem, osd_seq_list::osl_seq_list, and osd_seq_list::osl_seq_list_lock.
Referenced by osd_oi_init_compat().
static struct osd_seq* osd_seq_find (struct osd_seq_list * seq_list, u64 seq) [static, read]
Definition at line 276 of file osd_oi.c.
References osd_seq_find_locked(), and osd_seq_list::osl_seq_list_lock.
Referenced by osd_find_or_add_seq().
static struct osd_seq* osd_seq_find_locked (struct osd_seq_list * seq_list, u64 seq) [static, read]
Definition at line 264 of file osd_oi.c.
References list_for_each_entry, osd_seq::os_seq, osd_seq::os_seq_list, and osd_seq_list::osl_seq_list.
Referenced by osd_seq_find().
Variable Documentation
struct named_oid oids[] [static]
Initial value:
 {
        { LAST_RECV_OID,                LAST_RCVD },
        { OFD_LAST_GROUP_OID,           "LAST_GROUP" },
        { LLOG_CATALOGS_OID,            "CATALOGS" },
        { MGS_CONFIGS_OID,              NULL  },
        { FID_SEQ_SRV_OID,              "seq_srv" },
        { FID_SEQ_CTL_OID,              "seq_ctl" },
        { FLD_INDEX_OID,                "fld" },
        { MDD_LOV_OBJ_OID,              LOV_OBJID },
        { OFD_HEALTH_CHECK_OID,         HEALTH_CHECK },
        { ACCT_USER_OID,                "acct_usr_inode" },
        { ACCT_GROUP_OID,               "acct_grp_inode" },
        { REPLY_DATA_OID,               REPLY_DATA },
        { 0,                            NULL }
}
Definition at line 85 of file osd_oi.c.
unsigned int osd_oi_count = OSD_OI_FID_NR
Definition at line 72 of file osd_oi.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.