Lustre: lustre/osd-ldiskfs/osd_iam_lfix.c File Reference
lustre/osd-ldiskfs/osd_iam_lfix.c File Reference
#include <linux/types.h>
#include "osd_internal.h"
Data Structures
struct iam_leaf_head
struct iam_lfix_root
struct lfix_root
struct lfix_index
struct lfix_leaf
Defines
#define KEYSIZE (8)
#define RECSIZE (8)
#define PTRSIZE (4)
#define LFIX_ROOT_RECNO ((4096 - sizeof(struct iam_lfix_root)) / (KEYSIZE + PTRSIZE))
#define LFIX_INDEX_RECNO (4096 / (KEYSIZE + PTRSIZE))
#define LFIX_LEAF_RECNO ((4096 - sizeof(struct iam_leaf_head)) / (KEYSIZE + RECSIZE))
#define STORE_UNALIGNED(val, dst)
Enumerations
enum { IAM_LEAF_HEADER_MAGIC = 0x1976 }
enum { IAM_LFIX_ROOT_MAGIC = 0xbedabb1edULL }
Functions
static int iam_lfix_entry_size (const struct iam_leaf *l)
static struct iam_lentry * iam_lfix_shift (const struct iam_leaf *l, struct iam_lentry *entry, int shift)
static struct iam_key * iam_leaf_key_at (struct iam_lentry *entry)
static int lfix_keycmp (const struct iam_container *c, const struct iam_key *k1, const struct iam_key *k2)
static struct iam_leaf_head * iam_get_head (const struct iam_leaf *l)
static struct iam_lentry * iam_entries (const struct buffer_head *bh)
static struct iam_lentry * iam_get_lentries (const struct iam_leaf *l)
static int leaf_count_limit (const struct iam_leaf *leaf)
static int lentry_count_get (const struct iam_leaf *leaf)
static void lentry_count_set (struct iam_leaf *leaf, unsigned count)
static struct iam_lentry * iam_lfix_get_end (const struct iam_leaf *l)
static struct iam_ikey * iam_lfix_ikey (const struct iam_leaf *l, struct iam_ikey *key)
static struct iam_key * iam_lfix_key (const struct iam_leaf *l)
static int iam_lfix_key_size (const struct iam_leaf *l)
static void iam_lfix_start (struct iam_leaf *l)
static ptrdiff_t iam_lfix_diff (const struct iam_leaf *l, const struct iam_lentry *e1, const struct iam_lentry *e2)
static int iam_lfix_init (struct iam_leaf *l)
static void iam_lfix_fini (struct iam_leaf *l)
static struct iam_rec * iam_lfix_rec (const struct iam_leaf *l)
static void iam_lfix_next (struct iam_leaf *l)
static char hdigit (char ch)
static char * hex (char ch, char *area)
static void l_print (struct iam_leaf *leaf, struct iam_lentry *entry)
static void lfix_print (struct iam_leaf *leaf)
static int iam_lfix_lookup (struct iam_leaf *l, const struct iam_key *k)
static int iam_lfix_ilookup (struct iam_leaf *l, const struct iam_ikey *ik)
static void iam_lfix_key_set (struct iam_leaf *l, const struct iam_key *k)
static int iam_lfix_key_cmp (const struct iam_leaf *l, const struct iam_key *k)
static int iam_lfix_key_eq (const struct iam_leaf *l, const struct iam_key *k)
static void iam_lfix_rec_set (struct iam_leaf *l, const struct iam_rec *r)
static int lfix_reccmp (const struct iam_container *c, const struct iam_rec *r1, const struct iam_rec *r2)
static int iam_lfix_rec_eq (const struct iam_leaf *l, const struct iam_rec *r)
static void iam_lfix_rec_get (const struct iam_leaf *l, struct iam_rec *r)
static void iam_lfix_rec_add (struct iam_leaf *leaf, const struct iam_key *k, const struct iam_rec *r)
static void iam_lfix_rec_del (struct iam_leaf *leaf, int shift)
static int iam_lfix_can_add (const struct iam_leaf *l, const struct iam_key *k, const struct iam_rec *r)
static int iam_lfix_at_end (const struct iam_leaf *folio)
static void iam_lfix_init_new (struct iam_container *c, struct buffer_head *bh)
static void iam_lfix_split (struct iam_leaf *l, struct buffer_head **bh, iam_ptr_t new_blknr)
static int iam_lfix_leaf_empty (struct iam_leaf *leaf)
static __u32 iam_lfix_root_ptr (struct iam_container *c)
static int iam_lfix_node_init (struct iam_container *c, struct buffer_head *bh, int root)
static struct iam_entry * iam_lfix_root_inc (struct iam_container *c, struct iam_path *path, struct iam_frame *frame)
static int iam_lfix_node_check (struct iam_path *path, struct iam_frame *frame)
static int iam_lfix_node_load (struct iam_path *path, struct iam_frame *frame)
static int iam_lfix_ikeycmp (const struct iam_container *c, const struct iam_ikey *k1, const struct iam_ikey *k2)
static struct iam_path_descr * iam_lfix_ipd_alloc (const struct iam_container *c, void *area)
static int iam_lfix_guess (struct iam_container *c)
void iam_lfix_format_init (void)
static void lfix_root (void *buf, int blocksize, int keysize, int ptrsize, int recsize)
static void lfix_leaf (void *buf, int blocksize, int keysize, int ptrsize, int recsize)
int iam_lfix_create (struct inode *obj, int keysize, int ptrsize, int recsize, handle_t *handle)
Variables
int lfix_dump = 0
static struct iam_leaf_operations iam_lfix_leaf_ops
static struct iam_operations iam_lfix_ops
static struct iam_format iam_lfix_format
Define Documentation
#define KEYSIZE (8)
Definition at line 725 of file osd_iam_lfix.c.
#define LFIX_INDEX_RECNO (4096 / (KEYSIZE + PTRSIZE))
Definition at line 732 of file osd_iam_lfix.c.
#define LFIX_LEAF_RECNO ((4096 - sizeof(struct iam_leaf_head)) / (KEYSIZE + RECSIZE))
Definition at line 734 of file osd_iam_lfix.c.
#define LFIX_ROOT_RECNO ((4096 - sizeof(struct iam_lfix_root)) / (KEYSIZE + PTRSIZE))
Definition at line 729 of file osd_iam_lfix.c.
#define PTRSIZE (4)
Definition at line 727 of file osd_iam_lfix.c.
#define RECSIZE (8)
Definition at line 726 of file osd_iam_lfix.c.
#define STORE_UNALIGNED (val, dst)
Value:
({                                                      \
        typeof(val) __val = (val);                      \
        CLASSERT(sizeof(val) == sizeof(*(dst)));        \
        memcpy(dst, &__val, sizeof(*(dst)));            \
})
Definition at line 762 of file osd_iam_lfix.c.
Referenced by lfix_root(), and lvar_root().
Enumeration Type Documentation
anonymous enum
Enumerator:
IAM_LEAF_HEADER_MAGIC
Definition at line 50 of file osd_iam_lfix.c.
anonymous enum
Enumerator:
IAM_LFIX_ROOT_MAGIC
Definition at line 547 of file osd_iam_lfix.c.
Function Documentation
static char hdigit (char ch) [static]
Definition at line 227 of file osd_iam_lfix.c.
Referenced by hex().
static char* hex (char ch, char * area) [static]
Definition at line 233 of file osd_iam_lfix.c.
References hdigit().
Referenced by l_print().
static struct iam_lentry* iam_entries (const struct buffer_head * bh) [static, read]
Definition at line 89 of file osd_iam_lfix.c.
Referenced by iam_get_lentries(), and iam_lfix_split().
static struct iam_leaf_head* iam_get_head (const struct iam_leaf * l) [static, read]
Definition at line 84 of file osd_iam_lfix.c.
References iam_leaf::il_bh.
Referenced by iam_lfix_init(), lentry_count_get(), and lentry_count_set().
static struct iam_lentry* iam_get_lentries (const struct iam_leaf * l) [static, read]
Definition at line 94 of file osd_iam_lfix.c.
References iam_entries(), and iam_leaf::il_bh.
Referenced by iam_lfix_init(), iam_lfix_split(), and iam_lfix_start().
static struct iam_key* iam_leaf_key_at (struct iam_lentry * entry) [static, read]
Definition at line 72 of file osd_iam_lfix.c.
Referenced by iam_lfix_key_cmp(), iam_lfix_key_eq(), iam_lfix_key_set(), iam_lfix_lookup(), iam_lfix_rec_add(), and iam_lfix_split().
static int iam_lfix_at_end (const struct iam_leaf * folio) [static]
Definition at line 443 of file osd_iam_lfix.c.
References iam_lfix_get_end(), and iam_leaf::il_at.
static int iam_lfix_can_add (const struct iam_leaf * l, const struct iam_key * k, const struct iam_rec * r) [static]
Definition at line 437 of file osd_iam_lfix.c.
References leaf_count_limit(), and lentry_count_get().
int iam_lfix_create (struct inode * obj, int keysize, int ptrsize, int recsize, handle_t * handle)
Definition at line 850 of file osd_iam_lfix.c.
References assert_corr, GOTO, lfix_leaf(), lfix_root(), and osd_ldiskfs_append().
Referenced by osd_mk_index(), and osd_oi_index_create_one().
static ptrdiff_t iam_lfix_diff (const struct iam_leaf * l, const struct iam_lentry * e1, const struct iam_lentry * e2) [inline, static]
Definition at line 155 of file osd_iam_lfix.c.
References assert_corr, and iam_lfix_entry_size().
Referenced by iam_lfix_lookup(), and iam_lfix_split().
static int iam_lfix_entry_size (const struct iam_leaf * l) [inline, static]
Definition at line 61 of file osd_iam_lfix.c.
References iam_leaf_descr(), iam_descr::id_key_size, and iam_descr::id_rec_size.
Referenced by iam_lfix_diff(), iam_lfix_shift(), and leaf_count_limit().
static void iam_lfix_fini (struct iam_leaf * l) [static]
Definition at line 196 of file osd_iam_lfix.c.
References iam_leaf::il_at, and iam_leaf::il_entries.
void iam_lfix_format_init (void)
Definition at line 716 of file osd_iam_lfix.c.
References iam_format_register().
Referenced by iam_format_guess().
static struct iam_lentry * iam_lfix_get_end (const struct iam_leaf * l) [static, read]
Definition at line 201 of file osd_iam_lfix.c.
References iam_lfix_shift(), iam_leaf::il_entries, and lentry_count_get().
Referenced by iam_lfix_at_end(), iam_lfix_rec_add(), and iam_lfix_rec_del().
static int iam_lfix_guess (struct iam_container * c) [static]
Definition at line 679 of file osd_iam_lfix.c.
References assert_corr, IAM_LFIX_ROOT_MAGIC, iam_lfix_root_ptr(), iam_node_read(), iam_container::ic_descr, iam_container::ic_object, iam_container::ic_root_bh, iam_descr::id_ikey_size, iam_descr::id_key_size, iam_descr::id_leaf_ops, iam_descr::id_node_gap, iam_descr::id_ops, iam_descr::id_ptr_size, iam_descr::id_rec_size, iam_descr::id_root_gap, iam_lfix_root::ilr_keysize, iam_lfix_root::ilr_magic, iam_lfix_root::ilr_ptrsize, iam_lfix_root::ilr_recsize, le16_to_cpu, and le64_to_cpu.
static struct iam_ikey* iam_lfix_ikey (const struct iam_leaf * l, struct iam_ikey * key) [static, read]
Definition at line 130 of file osd_iam_lfix.c.
References assert_corr, and iam_leaf::il_at.
static int iam_lfix_ikeycmp (const struct iam_container * c, const struct iam_ikey * k1, const struct iam_ikey * k2) [static]
Definition at line 653 of file osd_iam_lfix.c.
References iam_container::ic_descr, and iam_descr::id_ikey_size.
static int iam_lfix_ilookup (struct iam_leaf * l, const struct iam_ikey * ik) [static]
Definition at line 331 of file osd_iam_lfix.c.
References iam_lfix_lookup().
static int iam_lfix_init (struct iam_leaf * l) [static]
Definition at line 168 of file osd_iam_lfix.c.
References assert_corr, CERROR, iam_get_head(), iam_get_lentries(), iam_leaf_container(), IAM_LEAF_HEADER_MAGIC, iam_container::ic_object, iam_leaf::il_at, iam_leaf::il_bh, iam_leaf::il_entries, iam_leaf_head::ill_count, iam_leaf_head::ill_magic, le16_to_cpu, and leaf_count_limit().
Referenced by iam_lfix_split().
static void iam_lfix_init_new (struct iam_container * c, struct buffer_head * bh) [static]
Definition at line 448 of file osd_iam_lfix.c.
References cpu_to_le16, IAM_LEAF_HEADER_MAGIC, iam_leaf_head::ill_count, and iam_leaf_head::ill_magic.
static struct iam_path_descr* iam_lfix_ipd_alloc (const struct iam_container * c, void * area) [static, read]
Definition at line 660 of file osd_iam_lfix.c.
References iam_ipd_alloc(), iam_container::ic_descr, and iam_descr::id_ikey_size.
static struct iam_key* iam_lfix_key (const struct iam_leaf * l) [static, read]
Definition at line 138 of file osd_iam_lfix.c.
References assert_corr, and iam_leaf::il_at.
static int iam_lfix_key_cmp (const struct iam_leaf * l, const struct iam_key * k) [static]
Definition at line 342 of file osd_iam_lfix.c.
References iam_leaf_container(), iam_leaf_key_at(), iam_leaf::il_at, and lfix_keycmp().
static int iam_lfix_key_eq (const struct iam_leaf * l, const struct iam_key * k) [static]
Definition at line 347 of file osd_iam_lfix.c.
References iam_leaf_container(), iam_leaf_key_at(), iam_leaf::il_at, and lfix_keycmp().
static void iam_lfix_key_set (struct iam_leaf * l, const struct iam_key * k) [static]
Definition at line 336 of file osd_iam_lfix.c.
References assert_corr, iam_leaf_descr(), iam_leaf_key_at(), and iam_leaf::il_at.
Referenced by iam_lfix_rec_add().
static int iam_lfix_key_size (const struct iam_leaf * l) [static]
Definition at line 145 of file osd_iam_lfix.c.
References iam_leaf_descr(), and iam_descr::id_key_size.
Referenced by l_print().
static int iam_lfix_leaf_empty (struct iam_leaf * leaf) [static]
Definition at line 512 of file osd_iam_lfix.c.
References lentry_count_get().
static int iam_lfix_lookup (struct iam_leaf * l, const struct iam_key * k) [static]
Definition at line 270 of file osd_iam_lfix.c.
References assert_corr, iam_leaf_container(), iam_leaf_key_at(), iam_lfix_diff(), iam_lfix_shift(), IAM_LOOKUP_BEFORE, IAM_LOOKUP_EMPTY, IAM_LOOKUP_EXACT, IAM_LOOKUP_OK, iam_leaf::il_at, iam_leaf::il_entries, lentry_count_get(), lfix_dump, lfix_keycmp(), and lfix_print().
Referenced by iam_lfix_ilookup().
static void iam_lfix_next (struct iam_leaf * l) [static]
Definition at line 216 of file osd_iam_lfix.c.
References assert_corr, iam_lfix_shift(), and iam_leaf::il_at.
Referenced by iam_lfix_rec_add().
static int iam_lfix_node_check (struct iam_path * path, struct iam_frame * frame) [static]
Definition at line 602 of file osd_iam_lfix.c.
References iam_frame::bh, dx_get_count(), dx_get_limit(), dx_node_get_entries(), dx_node_limit(), dx_root_limit(), IAM_LFIX_ROOT_MAGIC, iam_lfix_root::ilr_magic, iam_path::ip_frames, and le64_to_cpu.
static int iam_lfix_node_init (struct iam_container * c, struct buffer_head * bh, int root) [static]
Definition at line 575 of file osd_iam_lfix.c.
static int iam_lfix_node_load (struct iam_path * path, struct iam_frame * frame) [static]
Definition at line 632 of file osd_iam_lfix.c.
References iam_frame::at, iam_frame::bh, dx_node_get_entries(), iam_frame::entries, iam_lfix_root::ilr_indirect_levels, iam_path::ip_frames, iam_path::ip_ikey_target, iam_path::ip_indirect, and iam_path::ip_key_target.
static struct iam_rec* iam_lfix_rec (const struct iam_leaf * l) [static, read]
Definition at line 209 of file osd_iam_lfix.c.
References assert_corr, iam_leaf_descr(), iam_descr::id_key_size, and iam_leaf::il_at.
Referenced by iam_lfix_rec_eq(), iam_lfix_rec_get(), and iam_lfix_rec_set().
static void iam_lfix_rec_add (struct iam_leaf * leaf, const struct iam_key * k, const struct iam_rec * r) [static]
Definition at line 377 of file osd_iam_lfix.c.
References assert_corr, end, iam_leaf_at_end(), iam_leaf_can_add(), iam_leaf_container(), iam_leaf_key_at(), iam_lfix_get_end(), iam_lfix_key_set(), iam_lfix_next(), iam_lfix_rec_set(), iam_lfix_shift(), iam_leaf::il_at, iam_leaf::il_entries, lentry_count_get(), lentry_count_set(), lfix_keycmp(), and start.
static void iam_lfix_rec_del (struct iam_leaf * leaf, int shift) [static]
Definition at line 420 of file osd_iam_lfix.c.
References assert_corr, end, iam_lfix_get_end(), iam_lfix_shift(), iam_leaf::il_at, lentry_count_get(), and lentry_count_set().
static int iam_lfix_rec_eq (const struct iam_leaf * l, const struct iam_rec * r) [static]
Definition at line 366 of file osd_iam_lfix.c.
References iam_leaf_container(), iam_lfix_rec(), and lfix_reccmp().
static void iam_lfix_rec_get (const struct iam_leaf * l, struct iam_rec * r) [static]
Definition at line 371 of file osd_iam_lfix.c.
References assert_corr, iam_leaf_descr(), and iam_lfix_rec().
static void iam_lfix_rec_set (struct iam_leaf * l, const struct iam_rec * r) [static]
Definition at line 353 of file osd_iam_lfix.c.
References assert_corr, iam_leaf_descr(), and iam_lfix_rec().
Referenced by iam_lfix_rec_add().
static struct iam_entry* iam_lfix_root_inc (struct iam_container * c, struct iam_path * path, struct iam_frame * frame) [static, read]
Definition at line 581 of file osd_iam_lfix.c.
References assert_corr, iam_frame::at, iam_frame::bh, dx_get_limit(), dx_root_limit(), dx_set_count(), iam_frame::entries, iam_entry_shift(), iam_ikey_at(), IAM_LFIX_ROOT_MAGIC, iam_path_descr(), iam_lfix_root::ilr_indirect_levels, iam_lfix_root::ilr_magic, and le64_to_cpu.
static __u32 iam_lfix_root_ptr (struct iam_container * c) [static]
Definition at line 570 of file osd_iam_lfix.c.
Referenced by iam_lfix_guess().
static struct iam_lentry* iam_lfix_shift (const struct iam_leaf * l, struct iam_lentry * entry, int shift) [static, read]
Definition at line 67 of file osd_iam_lfix.c.
References iam_lfix_entry_size().
Referenced by iam_lfix_get_end(), iam_lfix_lookup(), iam_lfix_next(), iam_lfix_rec_add(), iam_lfix_rec_del(), iam_lfix_split(), and lfix_print().
static void iam_lfix_split (struct iam_leaf * l, struct buffer_head ** bh, iam_ptr_t new_blknr) [static]
Definition at line 457 of file osd_iam_lfix.c.
References assert_corr, cpu_to_le16, iam_entries(), iam_get_lentries(), iam_insert_key_lock(), iam_leaf_key_at(), iam_leaf_path(), iam_lfix_diff(), iam_lfix_init(), iam_lfix_shift(), iam_leaf::il_at, iam_leaf::il_bh, iam_leaf::il_curidx, iam_leaf_head::ill_count, iam_path::ip_frame, lentry_count_get(), lentry_count_set(), path, and start.
static void iam_lfix_start (struct iam_leaf * l) [static]
Definition at line 150 of file osd_iam_lfix.c.
References iam_get_lentries(), and iam_leaf::il_at.
static void l_print (struct iam_leaf * leaf, struct iam_lentry * entry) [static]
Definition at line 241 of file osd_iam_lfix.c.
References hex(), iam_leaf_descr(), iam_lfix_key_size(), and printk.
Referenced by lfix_print().
static int leaf_count_limit (const struct iam_leaf * leaf) [static]
Definition at line 99 of file osd_iam_lfix.c.
References iam_leaf_container(), iam_lfix_entry_size(), and iam_container::ic_object.
Referenced by iam_lfix_can_add(), iam_lfix_init(), and lentry_count_set().
static int lentry_count_get (const struct iam_leaf * leaf) [static]
Definition at line 108 of file osd_iam_lfix.c.
References iam_get_head(), iam_leaf_head::ill_count, and le16_to_cpu.
Referenced by iam_lfix_can_add(), iam_lfix_get_end(), iam_lfix_leaf_empty(), iam_lfix_lookup(), iam_lfix_rec_add(), iam_lfix_rec_del(), iam_lfix_split(), and lfix_print().
static void lentry_count_set (struct iam_leaf * leaf, unsigned count) [static]
Definition at line 113 of file osd_iam_lfix.c.
References assert_corr, cpu_to_le16, iam_get_head(), iam_leaf_head::ill_count, and leaf_count_limit().
Referenced by iam_lfix_rec_add(), iam_lfix_rec_del(), and iam_lfix_split().
static int lfix_keycmp (const struct iam_container * c, const struct iam_key * k1, const struct iam_key * k2) [inline, static]
Definition at line 77 of file osd_iam_lfix.c.
References iam_container::ic_descr, and iam_descr::id_key_size.
Referenced by iam_lfix_key_cmp(), iam_lfix_key_eq(), iam_lfix_lookup(), and iam_lfix_rec_add().
static void lfix_leaf (void * buf, int blocksize, int keysize, int ptrsize, int recsize) [static]
Definition at line 829 of file osd_iam_lfix.c.
References cpu_to_le16, head, IAM_LEAF_HEADER_MAGIC, and iam_leaf_head::ill_magic.
Referenced by iam_lfix_create().
static void lfix_print (struct iam_leaf * leaf) [static]
Definition at line 257 of file osd_iam_lfix.c.
References iam_lfix_shift(), iam_leaf::il_at, iam_leaf::il_entries, l_print(), lentry_count_get(), and printk.
Referenced by iam_lfix_lookup().
static int lfix_reccmp (const struct iam_container * c, const struct iam_rec * r1, const struct iam_rec * r2) [inline, static]
Definition at line 359 of file osd_iam_lfix.c.
References iam_container::ic_descr, and iam_descr::id_rec_size.
Referenced by iam_lfix_rec_eq().
static void lfix_root (void * buf, int blocksize, int keysize, int ptrsize, int recsize) [static]
Definition at line 769 of file osd_iam_lfix.c.
References dx_countlimit::count, cpu_to_le16, cpu_to_le32, cpu_to_le64, IAM_LFIX_ROOT_MAGIC, iam_root_limit(), iam_lfix_root::ilr_magic, LASSERT, dx_countlimit::limit, and STORE_UNALIGNED.
Referenced by iam_lfix_create().
Variable Documentation
struct iam_format iam_lfix_format [static]
Initial value:
 {
        .if_guess = iam_lfix_guess
}
Definition at line 712 of file osd_iam_lfix.c.
struct iam_leaf_operations iam_lfix_leaf_ops [static]
Initial value:
 {
        .init           = iam_lfix_init,
        .init_new       = iam_lfix_init_new,
        .fini           = iam_lfix_fini,
        .start          = iam_lfix_start,
        .next           = iam_lfix_next,
        .key            = iam_lfix_key,
        .ikey           = iam_lfix_ikey,
        .rec            = iam_lfix_rec,
        .key_set        = iam_lfix_key_set,
        .key_cmp        = iam_lfix_key_cmp,
        .key_eq         = iam_lfix_key_eq,
        .key_size       = iam_lfix_key_size,
        .rec_set        = iam_lfix_rec_set,
        .rec_eq         = iam_lfix_rec_eq,
        .rec_get        = iam_lfix_rec_get,
        .lookup         = iam_lfix_lookup,
        .ilookup        = iam_lfix_ilookup,
        .at_end         = iam_lfix_at_end,
        .rec_add        = iam_lfix_rec_add,
        .rec_del        = iam_lfix_rec_del,
        .can_add        = iam_lfix_can_add,
        .split          = iam_lfix_split,
        .leaf_empty     = iam_lfix_leaf_empty,
}
Definition at line 517 of file osd_iam_lfix.c.
struct iam_operations iam_lfix_ops [static]
Initial value:
 {
        .id_root_ptr    = iam_lfix_root_ptr,
        .id_node_read   = iam_node_read,
        .id_node_init   = iam_lfix_node_init,
        .id_node_check  = iam_lfix_node_check,
        .id_node_load   = iam_lfix_node_load,
        .id_ikeycmp     = iam_lfix_ikeycmp,
        .id_root_inc    = iam_lfix_root_inc,
        .id_ipd_alloc   = iam_lfix_ipd_alloc,
        .id_ipd_free    = iam_ipd_free,
        .id_name        = "lfix"
}
Definition at line 666 of file osd_iam_lfix.c.
int lfix_dump = 0
Definition at line 225 of file osd_iam_lfix.c.
Referenced by iam_lfix_lookup().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.