Lustre: lustre/osd-zfs/osd_object.c File Reference
lustre/osd-zfs/osd_object.c File Reference
#include <lustre_ver.h>
#include <libcfs/libcfs.h>
#include <obd_support.h>
#include <lustre_net.h>
#include <obd.h>
#include <obd_class.h>
#include <lustre_disk.h>
#include <lustre_fid.h>
#include "osd_internal.h"
#include <sys/dnode.h>
#include <sys/dbuf.h>
#include <sys/spa.h>
#include <sys/stat.h>
#include <sys/zap.h>
#include <sys/spa_impl.h>
#include <sys/zfs_znode.h>
#include <sys/dmu_tx.h>
#include <sys/dmu_objset.h>
#include <sys/dsl_prop.h>
#include <sys/sa_impl.h>
#include <sys/txg.h>
Defines
#define DEBUG_SUBSYSTEM S_OSD
Typedefs
typedef dmu_buf_t *(* osd_obj_type_f)(const struct lu_env *env, struct osd_object *obj, struct lu_attr *la, uint64_t parent, struct osd_thandle *oh)
Functions
static void osd_object_sa_fini (struct osd_object *obj)
static int osd_object_sa_init (struct osd_object *obj, struct osd_device *o)
static void osd_object_sa_dirty_add (struct osd_object *obj, struct osd_thandle *oh)
void osd_object_sa_dirty_rele (struct osd_thandle *oh)
int osd_object_sa_update (struct osd_object *obj, sa_attr_type_t type, void *buf, uint32_t buflen, struct osd_thandle *oh)
static int osd_object_sa_bulk_update (struct osd_object *obj, sa_bulk_attr_t *attrs, int count, struct osd_thandle *oh)
int __osd_object_attr_get (const struct lu_env *env, struct osd_device *o, struct osd_object *obj, struct lu_attr *la)
int __osd_obj2dbuf (const struct lu_env *env, objset_t *os, uint64_t oid, dmu_buf_t **dbp)
struct lu_object * osd_object_alloc (const struct lu_env *env, const struct lu_object_header *hdr, struct lu_device *d)
int osd_object_init0 (const struct lu_env *env, struct osd_object *obj)
static int osd_check_lma (const struct lu_env *env, struct osd_object *obj)
static int osd_object_init (const struct lu_env *env, struct lu_object *l, const struct lu_object_conf *conf)
static void osd_object_free (const struct lu_env *env, struct lu_object *l)
static int osd_object_unlinked_add (struct osd_object *obj, struct osd_thandle *oh)
module_param (osd_sync_destroy_max_size, ulong, 0444)
MODULE_PARM_DESC (osd_sync_destroy_max_size,"Maximum object size to use synchronous destroy.")
static void osd_object_set_destroy_type (struct osd_object *obj)
static int osd_declare_object_destroy (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
static int osd_object_destroy (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
static void osd_object_delete (const struct lu_env *env, struct lu_object *l)
static void osd_object_release (const struct lu_env *env, struct lu_object *l)
static int osd_object_print (const struct lu_env *env, void *cookie, lu_printer_t p, const struct lu_object *l)
static void osd_object_read_lock (const struct lu_env *env, struct dt_object *dt, unsigned role)
static void osd_object_write_lock (const struct lu_env *env, struct dt_object *dt, unsigned role)
static void osd_object_read_unlock (const struct lu_env *env, struct dt_object *dt)
static void osd_object_write_unlock (const struct lu_env *env, struct dt_object *dt)
static int osd_object_write_locked (const struct lu_env *env, struct dt_object *dt)
static int osd_attr_get (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr)
static int qsd_transfer (const struct lu_env *env, struct qsd_instance *qsd, struct lquota_trans *trans, int qtype, __u64 orig_id, __u64 new_id, __u64 bspace, struct lquota_id_info *qi)
static int osd_declare_attr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_attr *attr, struct thandle *handle)
static int osd_attr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_attr *la, struct thandle *handle)
static void osd_ah_init (const struct lu_env *env, struct dt_allocation_hint *ah, struct dt_object *parent, struct dt_object *child, umode_t child_mode)
static int osd_declare_object_create (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *handle)
int __osd_attr_init (const struct lu_env *env, struct osd_device *osd, uint64_t oid, dmu_tx_t *tx, struct lu_attr *la, uint64_t parent)
int __osd_object_create (const struct lu_env *env, struct osd_object *obj, dmu_buf_t **dbp, dmu_tx_t *tx, struct lu_attr *la, uint64_t parent)
int __osd_zap_create (const struct lu_env *env, struct osd_device *osd, dmu_buf_t **zap_dbp, dmu_tx_t *tx, struct lu_attr *la, uint64_t parent, zap_flags_t flags)
static dmu_buf_t * osd_mkidx (const struct lu_env *env, struct osd_object *obj, struct lu_attr *la, uint64_t parent, struct osd_thandle *oh)
static dmu_buf_t * osd_mkdir (const struct lu_env *env, struct osd_object *obj, struct lu_attr *la, uint64_t parent, struct osd_thandle *oh)
static dmu_buf_t * osd_mkreg (const struct lu_env *env, struct osd_object *obj, struct lu_attr *la, uint64_t parent, struct osd_thandle *oh)
static dmu_buf_t * osd_mksym (const struct lu_env *env, struct osd_object *obj, struct lu_attr *la, uint64_t parent, struct osd_thandle *oh)
static dmu_buf_t * osd_mknod (const struct lu_env *env, struct osd_object *obj, struct lu_attr *la, uint64_t parent, struct osd_thandle *oh)
static osd_obj_type_f osd_create_type_f (enum dt_format_type type)
static int osd_init_lma (const struct lu_env *env, struct osd_object *obj, const struct lu_fid *fid, struct osd_thandle *oh)
static int osd_object_create (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *th)
static int osd_declare_object_ref_add (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
static int osd_object_ref_add (const struct lu_env *env, struct dt_object *dt, struct thandle *handle)
static int osd_declare_object_ref_del (const struct lu_env *env, struct dt_object *dt, struct thandle *handle)
static int osd_object_ref_del (const struct lu_env *env, struct dt_object *dt, struct thandle *handle)
static int osd_object_sync (const struct lu_env *env, struct dt_object *dt, __u64 start, __u64 end)
static int osd_otable_it_attr_get (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr)
Variables
char * osd_obj_tag = "osd_object"
static struct dt_object_operations osd_obj_ops
static struct lu_object_operations osd_lu_obj_ops
struct dt_body_operations osd_body_ops
static struct dt_object_operations osd_obj_otable_it_ops
struct kmem_cache * osd_object_kmem
static unsigned long osd_sync_destroy_max_size
Define Documentation
#define DEBUG_SUBSYSTEM S_OSD
Definition at line 43 of file osd_object.c.
Typedef Documentation
typedef dmu_buf_t*(* osd_obj_type_f)(const struct lu_env *env, struct osd_object *obj, struct lu_attr *la, uint64_t parent, struct osd_thandle *oh)
Definition at line 1453 of file osd_object.c.
Function Documentation
int __osd_attr_init (const struct lu_env * env, struct osd_device * osd, uint64_t oid, dmu_tx_t * tx, struct lu_attr * la, uint64_t parent)
Definition at line 1199 of file osd_object.c.
References osa_attr::atime, osa_attr::ctime, osa_attr::flags, osa_attr::gid, lu_attr::la_atime, lu_attr::la_ctime, lu_attr::la_flags, lu_attr::la_gid, lu_attr::la_mode, lu_attr::la_mtime, lu_attr::la_nlink, lu_attr::la_rdev, lu_attr::la_size, lu_attr::la_uid, osa_attr::mode, osa_attr::mtime, osa_attr::nlink, now(), OBD_ALLOC, OBD_FREE, osd_device::od_os, osd_oti_get(), osd_thread_info::oti_osa, osa_attr::rdev, osa_attr::size, and osa_attr::uid.
Referenced by __osd_object_create(), and __osd_zap_create().
int __osd_obj2dbuf (const struct lu_env * env, objset_t * os, uint64_t oid, dmu_buf_t ** dbp)
Definition at line 271 of file osd_object.c.
References LASSERT, osd_obj_tag, osd_oti_get(), osd_thread_info::oti_doi, and unlikely.
Referenced by __osd_xattr_get_large(), __osd_xattr_set(), osd_mount(), osd_object_init(), and osd_oi_add_table().
int __osd_object_attr_get (const struct lu_env * env, struct osd_device * o, struct osd_object * obj, struct lu_attr * la)
Definition at line 186 of file osd_object.c.
References osa_attr::atime, osa_attr::ctime, dt_object_exists(), ENTRY, osa_attr::flags, osa_attr::gid, GOTO, lu_attr::la_atime, LA_ATIME, lu_attr::la_ctime, LA_CTIME, lu_attr::la_flags, LA_FLAGS, lu_attr::la_gid, LA_GID, lu_attr::la_mode, LA_MODE, lu_attr::la_mtime, LA_MTIME, lu_attr::la_nlink, LA_NLINK, LA_RDEV, lu_attr::la_rdev, lu_attr::la_size, LA_SIZE, LA_TYPE, lu_attr::la_uid, LA_UID, lu_attr::la_valid, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, le32_to_cpu, lma_to_lustre_flags(), osa_attr::mode, osa_attr::mtime, osa_attr::nlink, OBD_ALLOC, OBD_FREE, osd_device::od_os, osd_object::oo_db, osd_object::oo_dt, osd_object::oo_lma_flags, osd_oti_get(), osd_xattr_get(), osd_thread_info::oti_buf, osd_thread_info::oti_osa, osa_attr::rdev, RETURN, sa_lookup(), osa_attr::size, osa_attr::uid, and XATTR_NAME_LMA.
Referenced by osd_object_init0().
int __osd_object_create (const struct lu_env * env, struct osd_object * obj, dmu_buf_t ** dbp, dmu_tx_t * tx, struct lu_attr * la, uint64_t parent)
Definition at line 1276 of file osd_object.c.
References __osd_attr_init(), dt_object::do_lu, fid_seq_is_local_file(), LA_MODE, lu_attr::la_mode, lu_attr::la_nlink, lu_attr::la_size, lu_attr::la_valid, LASSERT, LASSERTF, LPU64, lu_object_fid(), osd_device::od_os, osd_object::oo_dt, osd_obj2dev(), osd_obj_tag, and unlikely.
Referenced by __osd_xattr_set(), osd_mknod(), osd_mkreg(), and osd_mksym().
int __osd_zap_create (const struct lu_env * env, struct osd_device * osd, dmu_buf_t ** zap_dbp, dmu_tx_t * tx, struct lu_attr * la, uint64_t parent, zap_flags_t flags)
Definition at line 1327 of file osd_object.c.
References __osd_attr_init(), LA_MODE, lu_attr::la_nlink, lu_attr::la_size, lu_attr::la_valid, LASSERT, osd_device::od_os, and osd_obj_tag.
Referenced by __osd_xattr_set(), osd_mkdir(), osd_mkidx(), and osd_oi_create().
module_param (osd_sync_destroy_max_size , ulong , 0444)
MODULE_PARM_DESC (osd_sync_destroy_max_size , "Maximum object size to use synchronous destroy.")
static void osd_ah_init (const struct lu_env * env, struct dt_allocation_hint * ah, struct dt_object * parent, struct dt_object * child, umode_t child_mode) [static]
Definition at line 1116 of file osd_object.c.
References dt_allocation_hint::dah_mode, dt_allocation_hint::dah_parent, and LASSERT.
static int osd_attr_get (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr) [static]
Definition at line 742 of file osd_object.c.
References dt_object_exists(), GOTO, LA_BLKSIZE, lu_attr::la_blksize, LA_BLOCKS, lu_attr::la_blocks, lu_attr::la_flags, lu_attr::la_mode, lu_attr::la_size, lu_attr::la_valid, LASSERT, LUSTRE_ORPHAN_FL, osd_object::oo_attr, osd_object::oo_attr_lock, osd_object::oo_db, osd_object::oo_destroyed, osd_object::oo_guard, osd_object::oo_lma_flags, osd_object::oo_sa_hdl, osd_dt_obj(), osd_invariant, osd_obj2dev(), osd_spa_maxblocksize, and unlikely.
static int osd_attr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_attr * la, struct thandle * handle) [static]
Definition at line 928 of file osd_object.c.
References __u64, osa_attr::atime, CERROR, CLASSERT, cpu_to_le32, osa_attr::ctime, CWARN, dt_object::do_lu, dt_object_exists(), ENTRY, osa_attr::flags, osa_attr::gid, GOTO, lu_attr::la_atime, LA_ATIME, LA_BLOCKS, lu_attr::la_ctime, LA_CTIME, lu_attr::la_flags, LA_FLAGS, lu_attr::la_gid, LA_GID, lu_attr::la_mode, LA_MODE, lu_attr::la_mtime, LA_MTIME, lu_attr::la_nlink, LA_NLINK, lu_attr::la_rdev, LA_RDEV, lu_attr::la_size, LA_SIZE, lu_attr::la_uid, LA_UID, lu_attr::la_valid, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, le32_to_cpu, lustre_mdt_attrs::lma_incompat, lu_object::lo_header, lu_object_header::loh_attr, LU_XATTR_REPLACE, LUSTRE_LMA_FL_MASKS, lustre_to_lma_flags(), osa_attr::mode, osa_attr::mtime, osa_attr::nlink, OBD_ALLOC, OBD_FREE, osd_device::od_igrp_oid, osd_device::od_iusr_oid, osd_device::od_os, osd_device::od_svname, osd_object::oo_attr, osd_object::oo_attr_lock, osd_object::oo_destroyed, osd_object::oo_dt, osd_object::oo_guard, osd_object::oo_sa_hdl, osd_dt_obj(), osd_invariant, osd_obj2dev(), osd_object_sa_bulk_update(), osd_oti_get(), osd_xattr_get(), osd_thandle::ot_tx, osd_thread_info::oti_buf, osd_thread_info::oti_osa, osa_attr::rdev, RETURN, osa_attr::size, osa_attr::uid, unlikely, and XATTR_NAME_LMA.
static int osd_check_lma (const struct lu_env * env, struct osd_object * obj) [static]
Definition at line 366 of file osd_object.c.
References CFS_FAIL_CHECK, CLASSERT, CWARN, DFID, dt_object::do_lu, ENTRY, lu_buf::lb_buf, lu_buf::lb_len, lustre_mdt_attrs::lma_incompat, LMA_INCOMPAT_SUPP, lu_object_fid(), lustre_lma_swab(), OBD_FAIL_OSD_LMA_INCOMPAT, osd_object::oo_dt, osd_obj2dev(), osd_oti_get(), osd_xattr_get(), osd_thread_info::oti_buf, PFID, RETURN, unlikely, and XATTR_NAME_LMA.
Referenced by osd_object_init().
static osd_obj_type_f osd_create_type_f (enum dt_format_type type) [static]
Definition at line 1459 of file osd_object.c.
References DFT_DIR, DFT_INDEX, DFT_NODE, DFT_REGULAR, DFT_SYM, LBUG, osd_mkdir(), osd_mkidx(), osd_mknod(), osd_mkreg(), and osd_mksym().
Referenced by osd_object_create().
static int osd_declare_attr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_attr * attr, struct thandle * handle) [static]
Definition at line 848 of file osd_object.c.
References __osd_xattr_declare_set(), buf, dt_object_exists(), ENTRY, GOTO, lu_attr::la_gid, LA_GID, lu_attr::la_uid, LA_UID, lu_attr::la_valid, LASSERT, osd_device::od_igrp_oid, osd_device::od_iusr_oid, osd_device::od_quota_slave, osd_object::oo_attr, osd_object::oo_destroyed, osd_object::oo_guard, osd_object::oo_sa_hdl, osd_dt_obj(), osd_invariant, osd_obj2dev(), osd_oti_get(), osd_thandle::ot_quota_trans, osd_thandle::ot_super, osd_thandle::ot_tx, osd_thread_info::oti_qi, osd_thread_info::oti_str, qsd_transfer(), RETURN, toqb, unlikely, and XATTR_NAME_LMA.
Referenced by osd_declare_object_ref_add(), and osd_declare_object_ref_del().
static int osd_declare_object_create (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof, struct thandle * handle) [static]
Definition at line 1126 of file osd_object.c.
References __osd_xattr_declare_set(), buf, DFT_DIR, DFT_INDEX, DFT_NODE, DFT_REGULAR, DFT_SYM, dt_object::do_body_ops, dt_object::do_index_ops, dt_object::do_lu, dt_object_format::dof_type, ENTRY, lu_attr::la_gid, lu_attr::la_uid, LASSERT, LBUG, lu_object_fid(), osd_device::od_igrp_oid, osd_device::od_iusr_oid, osd_object::oo_dt, osd_body_ops, osd_declare_quota(), osd_dir_ops, osd_dt_obj(), osd_get_name_n_idx(), osd_obj2dev(), osd_oti_get(), osd_thandle::ot_super, osd_thandle::ot_tx, osd_thread_info::oti_str, RETURN, and XATTR_NAME_LMA.
static int osd_declare_object_destroy (const struct lu_env * env, struct dt_object * dt, struct thandle * th) [static]
Definition at line 508 of file osd_object.c.
References buf, dt_object::do_lu, dt_object_exists(), ENTRY, lu_attr::la_gid, lu_attr::la_uid, LASSERT, lu_object_fid(), osd_device::od_igrp_oid, osd_device::od_iusr_oid, osd_device::od_unlinkedid, osd_object::oo_attr, osd_object::oo_db, osd_object::oo_destroy, osd_declare_quota(), osd_declare_xattrs_destroy(), OSD_DESTROY_SYNC, osd_dt_obj(), osd_get_name_n_idx(), osd_obj2dev(), osd_object_set_destroy_type(), osd_oti_get(), osd_thandle::ot_super, osd_thandle::ot_tx, osd_thread_info::oti_str, and RETURN.
static int osd_declare_object_ref_add (const struct lu_env * env, struct dt_object * dt, struct thandle * th) [static]
Definition at line 1601 of file osd_object.c.
References osd_declare_attr_set().
static int osd_declare_object_ref_del (const struct lu_env * env, struct dt_object * dt, struct thandle * handle) [static]
Definition at line 1643 of file osd_object.c.
References osd_declare_attr_set().
static int osd_init_lma (const struct lu_env * env, struct osd_object * obj, const struct lu_fid * fid, struct osd_thandle * oh) [inline, static]
Definition at line 1489 of file osd_object.c.
References lu_buf::lb_buf, lu_buf::lb_len, LU_XATTR_CREATE, lustre_lma_init(), lustre_lma_swab(), osd_oti_get(), osd_thread_info::oti_mdt_attrs, and XATTR_NAME_LMA.
Referenced by osd_object_create().
static dmu_buf_t* osd_mkdir (const struct lu_env * env, struct osd_object * obj, struct lu_attr * la, uint64_t parent, struct osd_thandle * oh) [static]
Definition at line 1374 of file osd_object.c.
References __osd_zap_create(), lu_attr::la_mode, LASSERT, osd_obj2dev(), and osd_thandle::ot_tx.
Referenced by osd_create_type_f().
static dmu_buf_t* osd_mkidx (const struct lu_env * env, struct osd_object * obj, struct lu_attr * la, uint64_t parent, struct osd_thandle * oh) [static]
Definition at line 1355 of file osd_object.c.
References __osd_zap_create(), lu_attr::la_mode, LASSERT, osd_obj2dev(), and osd_thandle::ot_tx.
Referenced by osd_create_type_f().
static dmu_buf_t* osd_mknod (const struct lu_env * env, struct osd_object * obj, struct lu_attr * la, uint64_t parent, struct osd_thandle * oh) [static]
Definition at line 1436 of file osd_object.c.
References __osd_object_create(), lu_attr::la_mode, LA_MODE, LA_RDEV, lu_attr::la_valid, and osd_thandle::ot_tx.
Referenced by osd_create_type_f().
static dmu_buf_t* osd_mkreg (const struct lu_env * env, struct osd_object * obj, struct lu_attr * la, uint64_t parent, struct osd_thandle * oh) [static]
Definition at line 1389 of file osd_object.c.
References __osd_object_create(), CERROR, lu_attr::la_mode, LASSERT, lu_device_is_md(), osd_device::od_max_blksz, osd_device::od_os, osd_device::od_svname, osd2lu_dev(), osd_obj2dev(), osd_thandle::ot_tx, and unlikely.
Referenced by osd_create_type_f().
static dmu_buf_t* osd_mksym (const struct lu_env * env, struct osd_object * obj, struct lu_attr * la, uint64_t parent, struct osd_thandle * oh) [static]
Definition at line 1422 of file osd_object.c.
References __osd_object_create(), lu_attr::la_mode, LASSERT, and osd_thandle::ot_tx.
Referenced by osd_create_type_f().
struct lu_object* osd_object_alloc (const struct lu_env * env, const struct lu_object_header * hdr, struct lu_device * d) [read]
Definition at line 301 of file osd_object.c.
References dt_object::do_lu, dt_object::do_ops, dt_object_init(), INIT_LIST_HEAD, lu_object::lo_ops, OBD_SLAB_ALLOC_PTR_GFP, osd_object::oo_attr_lock, osd_object::oo_destroy, osd_object::oo_dt, osd_object::oo_guard, osd_object::oo_sa_linkage, osd_object::oo_sem, osd_object::oo_unlinked_linkage, OSD_DESTROY_NONE, osd_lu_obj_ops, osd_obj_ops, and osd_object_kmem.
static int osd_object_create (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof, struct thandle * th) [static]
Definition at line 1511 of file osd_object.c.
References buf, CERROR, dt_allocation_hint::dah_parent, DFID, dt_object::do_lu, dt_object_format::dof_type, dt_object_exists(), dt_object_remote(), ENTRY, ergo, GOTO, IFTODT, LA_GID, LA_UID, LASSERT, lu_object_fid(), luz_direntry::lzd_reg, osd_device::od_igrp_oid, osd_device::od_iusr_oid, osd_device::od_os, osd_device::od_svname, osd_object::oo_db, osd_object::oo_guard, osd_create_type_f(), osd_dt_obj(), osd_get_name_n_idx(), osd_init_lma(), osd_invariant, osd_obj2dev(), osd_object_init0(), osd_oti_get(), osd_thandle::ot_super, osd_thandle::ot_tx, osd_thread_info::oti_str, osd_thread_info::oti_zde, PFID, RETURN, unlikely, zpl_direntry::zde_dnode, zpl_direntry::zde_pad, and zpl_direntry::zde_type.
static void osd_object_delete (const struct lu_env * env, struct lu_object * l) [static]
Definition at line 654 of file osd_object.c.
References list_del(), osd_object::oo_db, osd_object::oo_sa_linkage, osd_object::oo_sa_xattr, osd_obj(), osd_obj_tag, and osd_object_sa_fini().
static int osd_object_destroy (const struct lu_env * env, struct dt_object * dt, struct thandle * th) [static]
Definition at line 562 of file osd_object.c.
References buf, CERROR, DFID, dt_object::do_lu, dt_object_exists(), ENTRY, GOTO, lu_attr::la_gid, lu_attr::la_size, lu_attr::la_uid, LASSERT, lu_object::lo_header, lu_object_header::loh_flags, LPU64, lu_object_fid(), LU_OBJECT_HEARD_BANSHEE, osd_device::od_igrp_oid, osd_device::od_iusr_oid, osd_device::od_os, osd_device::od_svname, osd_device::od_unlinkedid, osd_object::oo_attr, osd_object::oo_db, osd_object::oo_destroy, osd_object::oo_destroyed, osd_object::oo_guard, OSD_DESTROY_NONE, OSD_DESTROY_SYNC, osd_dt_obj(), osd_get_name_n_idx(), osd_obj2dev(), osd_object_unlinked_add(), osd_oti_get(), osd_sync_destroy_max_size, osd_xattrs_destroy(), osd_thandle::ot_super, osd_thandle::ot_tx, osd_thread_info::oti_str, PFID, RETURN, and unlikely.
static void osd_object_free (const struct lu_env * env, struct lu_object * l) [static]
Definition at line 457 of file osd_object.c.
References dt_object_fini(), LASSERT, OBD_SLAB_FREE_PTR, osd_object::oo_dt, osd_invariant, osd_obj(), and osd_object_kmem.
static int osd_object_init (const struct lu_env * env, struct lu_object * l, const struct lu_object_conf * conf) [static]
Definition at line 403 of file osd_object.c.
References __osd_obj2dbuf(), CERROR, DFID, dt_object::do_ops, ENTRY, fid_is_otable_it(), GOTO, LASSERT, lu_object::lo_header, LOC_F_NEW, lu_object_conf::loc_flags, lu_object_header::loh_attr, lu_object_header::loh_fid, LOHA_EXISTS, LPX64, lu_object_fid(), osd_device::od_os, osd_device::od_svname, osd_object::oo_db, osd_object::oo_dt, osd_check_lma(), osd_fid_lookup(), osd_invariant, osd_obj(), osd_obj2dev(), osd_obj_otable_it_ops, osd_object_init0(), PFID, and RETURN.
int osd_object_init0 (const struct lu_env * env, struct osd_object * obj)
Definition at line 330 of file osd_object.c.
References __osd_object_attr_get(), dt_object::do_body_ops, dt_object::do_lu, ENTRY, fid_is_acct(), lu_attr::la_mode, likely, lu_object::lo_header, lu_object_header::loh_attr, LOHA_EXISTS, lu_object_fid(), osd_object::oo_attr, osd_object::oo_db, osd_object::oo_dt, osd_body_ops, osd_obj2dev(), osd_object_sa_init(), and RETURN.
Referenced by osd_object_create(), and osd_object_init().
static int osd_object_print (const struct lu_env * env, void * cookie, lu_printer_t p, const struct lu_object * l) [static]
Definition at line 681 of file osd_object.c.
References LUSTRE_OSD_ZFS_NAME, and osd_obj().
static void osd_object_read_lock (const struct lu_env * env, struct dt_object * dt, unsigned role) [static]
Definition at line 689 of file osd_object.c.
References LASSERT, osd_object::oo_sem, osd_dt_obj(), and osd_invariant.
static void osd_object_read_unlock (const struct lu_env * env, struct dt_object * dt) [static]
Definition at line 709 of file osd_object.c.
References LASSERT, osd_object::oo_sem, osd_dt_obj(), and osd_invariant.
static int osd_object_ref_add (const struct lu_env * env, struct dt_object * dt, struct thandle * handle) [static]
Definition at line 1611 of file osd_object.c.
References dt_object_exists(), ENTRY, GOTO, lu_attr::la_nlink, LASSERT, osd_object::oo_attr, osd_object::oo_attr_lock, osd_object::oo_destroyed, osd_object::oo_guard, osd_object::oo_sa_hdl, osd_dt_obj(), osd_invariant, osd_obj2dev(), osd_object_sa_update(), RETURN, and unlikely.
static int osd_object_ref_del (const struct lu_env * env, struct dt_object * dt, struct thandle * handle) [static]
Definition at line 1653 of file osd_object.c.
References dt_object::do_lu, dt_object_exists(), ENTRY, GOTO, lu_attr::la_nlink, LASSERT, lu_object::lo_header, lu_object_is_dying(), osd_object::oo_attr, osd_object::oo_attr_lock, osd_object::oo_destroyed, osd_object::oo_guard, osd_object::oo_sa_hdl, osd_dt_obj(), osd_invariant, osd_obj2dev(), osd_object_sa_update(), RETURN, and unlikely.
static void osd_object_release (const struct lu_env * env, struct lu_object * l) [static]
Definition at line 673 of file osd_object.c.
static int osd_object_sa_bulk_update (struct osd_object * obj, sa_bulk_attr_t * attrs, int count, struct osd_thandle * oh) [static]
Definition at line 169 of file osd_object.c.
References LASSERT, osd_object::oo_sa_hdl, osd_object_sa_dirty_add(), and osd_thandle::ot_tx.
Referenced by osd_attr_set().
static void osd_object_sa_dirty_add (struct osd_object * obj, struct osd_thandle * oh) [static]
Definition at line 116 of file osd_object.c.
References likely, list_add(), list_empty(), osd_object::oo_attr_lock, osd_object::oo_sa_linkage, osd_thandle::ot_sa_list, and osd_thandle::ot_sa_lock.
Referenced by osd_object_sa_bulk_update(), and osd_object_sa_update().
void osd_object_sa_dirty_rele (struct osd_thandle * oh)
Definition at line 132 of file osd_object.c.
References list_del_init(), list_empty(), list_entry, list_head::next, osd_object::oo_attr_lock, osd_object::oo_sa_hdl, osd_object::oo_sa_linkage, osd_thandle::ot_sa_list, and osd_thandle::ot_sa_lock.
Referenced by osd_trans_stop().
static void osd_object_sa_fini (struct osd_object * obj) [static]
Definition at line 79 of file osd_object.c.
References osd_object::oo_sa_hdl.
Referenced by osd_object_delete(), and osd_object_sa_init().
static int osd_object_sa_init (struct osd_object * obj, struct osd_device * o) [static]
Definition at line 88 of file osd_object.c.
References LASSERT, osd_device::od_os, osd_object::oo_db, osd_object::oo_sa_hdl, osd_object::oo_xattr, osd_object_sa_fini(), and sa_lookup().
Referenced by osd_object_init0().
int osd_object_sa_update (struct osd_object * obj, sa_attr_type_t type, void * buf, uint32_t buflen, struct osd_thandle * oh)
Definition at line 151 of file osd_object.c.
References LASSERT, osd_object::oo_sa_hdl, osd_object_sa_dirty_add(), and osd_thandle::ot_tx.
Referenced by __osd_sa_xattr_update(), __osd_xattr_set(), osd_dir_insert(), osd_object_ref_add(), osd_object_ref_del(), osd_punch(), osd_write(), and osd_write_commit().
static void osd_object_set_destroy_type (struct osd_object * obj) [inline, static]
Definition at line 492 of file osd_object.c.
References lu_attr::la_size, osd_object::oo_attr, osd_object::oo_destroy, osd_object::oo_guard, OSD_DESTROY_ASYNC, OSD_DESTROY_NONE, OSD_DESTROY_SYNC, and osd_sync_destroy_max_size.
Referenced by osd_declare_object_destroy().
static int osd_object_sync (const struct lu_env * env, struct dt_object * dt, __u64 start, __u64 end) [static]
Definition at line 1687 of file osd_object.c.
References ENTRY, osd_device::od_os, osd_dt_obj(), osd_obj2dev(), and RETURN.
static int osd_object_unlinked_add (struct osd_object * obj, struct osd_thandle * oh) [static]
Definition at line 468 of file osd_object.c.
References LASSERT, likely, list_add(), list_empty(), osd_object::oo_destroy, osd_object::oo_unlinked_linkage, OSD_DESTROY_ASYNC, and osd_thandle::ot_unlinked_list.
Referenced by osd_object_destroy().
static void osd_object_write_lock (const struct lu_env * env, struct dt_object * dt, unsigned role) [static]
Definition at line 699 of file osd_object.c.
References LASSERT, osd_object::oo_sem, osd_dt_obj(), and osd_invariant.
static int osd_object_write_locked (const struct lu_env * env, struct dt_object * dt) [static]
Definition at line 727 of file osd_object.c.
References LASSERT, osd_object::oo_sem, osd_dt_obj(), and osd_invariant.
static void osd_object_write_unlock (const struct lu_env * env, struct dt_object * dt) [static]
Definition at line 718 of file osd_object.c.
References LASSERT, osd_object::oo_sem, osd_dt_obj(), and osd_invariant.
static int osd_otable_it_attr_get (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr) [static]
Definition at line 1739 of file osd_object.c.
References lu_attr::la_valid.
static int qsd_transfer (const struct lu_env * env, struct qsd_instance * qsd, struct lquota_trans * trans, int qtype, __u64 orig_id, __u64 new_id, __u64 bspace, struct lquota_id_info * qi) [inline, static]
Definition at line 790 of file osd_object.c.
References LASSERT, lquota_id_info::lqi_id, lquota_id_info::lqi_is_blk, lquota_id_info::lqi_space, lquota_id_info::lqi_type, lquota_id::qid_uid, qsd_op_begin(), and unlikely.
Referenced by osd_declare_attr_set().
Variable Documentation
struct dt_body_operations osd_body_ops
Definition at line 1945 of file osd_io.c.
static struct lu_object_operations osd_lu_obj_ops [static, read]
Initial value:
 {
        .loo_object_init        = osd_object_init,
        .loo_object_delete      = osd_object_delete,
        .loo_object_release     = osd_object_release,
        .loo_object_free        = osd_object_free,
        .loo_object_print       = osd_object_print,
        .loo_object_invariant   = osd_object_invariant,
}
Definition at line 72 of file osd_object.c.
Referenced by osd_object_alloc().
static struct dt_object_operations osd_obj_ops [static, read]
Initial value:
 {
        .do_read_lock           = osd_object_read_lock,
        .do_write_lock          = osd_object_write_lock,
        .do_read_unlock         = osd_object_read_unlock,
        .do_write_unlock        = osd_object_write_unlock,
        .do_write_locked        = osd_object_write_locked,
        .do_attr_get            = osd_attr_get,
        .do_declare_attr_set    = osd_declare_attr_set,
        .do_attr_set            = osd_attr_set,
        .do_ah_init             = osd_ah_init,
        .do_declare_create      = osd_declare_object_create,
        .do_create              = osd_object_create,
        .do_declare_destroy     = osd_declare_object_destroy,
        .do_destroy             = osd_object_destroy,
        .do_index_try           = osd_index_try,
        .do_declare_ref_add     = osd_declare_object_ref_add,
        .do_ref_add             = osd_object_ref_add,
        .do_declare_ref_del     = osd_declare_object_ref_del,
        .do_ref_del             = osd_object_ref_del,
        .do_xattr_get           = osd_xattr_get,
        .do_declare_xattr_set   = osd_declare_xattr_set,
        .do_xattr_set           = osd_xattr_set,
        .do_declare_xattr_del   = osd_declare_xattr_del,
        .do_xattr_del           = osd_xattr_del,
        .do_xattr_list          = osd_xattr_list,
        .do_object_sync         = osd_object_sync,
}
Definition at line 71 of file osd_object.c.
Referenced by osd_object_alloc().
static struct dt_object_operations osd_obj_otable_it_ops [static, read]
Initial value:
 {
        .do_attr_get    = osd_otable_it_attr_get,
        .do_index_try   = osd_index_try,
}
Definition at line 74 of file osd_object.c.
Referenced by osd_object_init().
char* osd_obj_tag = "osd_object"
Definition at line 69 of file osd_object.c.
Referenced by __osd_obj2dbuf(), __osd_object_create(), __osd_zap_create(), osd_mount(), osd_object_delete(), osd_oi_create(), and osd_oi_remove_table().
struct kmem_cache* osd_object_kmem
Definition at line 75 of file osd_handler.c.
Referenced by osd_object_alloc(), and osd_object_free().
unsigned long osd_sync_destroy_max_size [static]
Initial value:
        1UL << (DN_MAX_INDBLKSHIFT - SPA_BLKPTRSHIFT + SPA_MAXBLOCKSHIFT)
Definition at line 486 of file osd_object.c.
Referenced by osd_object_destroy(), and osd_object_set_destroy_type().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.