Lustre: lustre/osd-ldiskfs/osd_dynlocks.c File Reference
lustre/osd-ldiskfs/osd_dynlocks.c File Reference
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/sched.h>
#include <libcfs/libcfs.h>
#include <obd_support.h>
#include "osd_dynlocks.h"
#include "osd_internal.h"
Defines
#define DYNLOCK_HANDLE_MAGIC 0xd19a10c
#define DYNLOCK_HANDLE_DEAD 0xd1956ee
#define DYNLOCK_LIST_MAGIC 0x11ee91e6
Functions
void dynlock_init (struct dynlock *dl)
struct dynlock_handle * dynlock_lock (struct dynlock *dl, unsigned long value, enum dynlock_type lt, gfp_t gfp)
void dynlock_unlock (struct dynlock *dl, struct dynlock_handle *hl)
int dynlock_is_locked (struct dynlock *dl, unsigned long value)
Define Documentation
#define DYNLOCK_HANDLE_DEAD 0xd1956ee
Definition at line 41 of file osd_dynlocks.c.
Referenced by dynlock_unlock().
#define DYNLOCK_HANDLE_MAGIC 0xd19a10c
Definition at line 40 of file osd_dynlocks.c.
Referenced by dynlock_is_locked(), dynlock_lock(), and dynlock_unlock().
#define DYNLOCK_LIST_MAGIC 0x11ee91e6
Definition at line 42 of file osd_dynlocks.c.
Referenced by dynlock_init(), dynlock_lock(), and dynlock_unlock().
Function Documentation
void dynlock_init (struct dynlock * dl)
Definition at line 50 of file osd_dynlocks.c.
References dynlock::dl_list, dynlock::dl_list_lock, dynlock::dl_magic, DYNLOCK_LIST_MAGIC, and INIT_LIST_HEAD.
Referenced by iam_container_init().
int dynlock_is_locked (struct dynlock * dl, unsigned long value)
Definition at line 198 of file osd_dynlocks.c.
References dynlock_handle::dh_list, dynlock_handle::dh_magic, dynlock_handle::dh_pid, dynlock_handle::dh_value, dynlock::dl_list, dynlock::dl_list_lock, DYNLOCK_HANDLE_MAGIC, list_for_each_entry, list_head::next, and list_head::prev.
Referenced by iam_frame_is_locked(), and iam_leaf_is_locked().
struct dynlock_handle* dynlock_lock (struct dynlock * dl, unsigned long value, enum dynlock_type lt, gfp_t gfp) [read]
Definition at line 67 of file osd_dynlocks.c.
References dynlock_handle::dh_list, dynlock_handle::dh_magic, dynlock_handle::dh_pid, dynlock_handle::dh_readers, dynlock_handle::dh_refcount, dynlock_handle::dh_value, dynlock_handle::dh_wait, dynlock_handle::dh_writers, dynlock::dl_list, dynlock::dl_list_lock, dynlock::dl_magic, DLT_WRITE, dynlock_cachep, DYNLOCK_HANDLE_MAGIC, DYNLOCK_LIST_MAGIC, list_add(), list_for_each_entry, list_head::next, OBD_SLAB_ALLOC_GFP, OBD_SLAB_FREE, and list_head::prev.
Referenced by iam_lock_htree().
void dynlock_unlock (struct dynlock * dl, struct dynlock_handle * hl)
Definition at line 159 of file osd_dynlocks.c.
References dynlock_handle::dh_list, dynlock_handle::dh_magic, dynlock_handle::dh_pid, dynlock_handle::dh_readers, dynlock_handle::dh_refcount, dynlock_handle::dh_wait, dynlock_handle::dh_writers, dynlock::dl_list_lock, dynlock::dl_magic, dynlock_cachep, DYNLOCK_HANDLE_DEAD, DYNLOCK_HANDLE_MAGIC, DYNLOCK_LIST_MAGIC, list_del(), OBD_SLAB_FREE, and printk.
Referenced by iam_unlock_htree().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.