Lustre: lustre/osd-zfs/osd_xattr.c File Reference
lustre/osd-zfs/osd_xattr.c File Reference
#include <lustre_ver.h>
#include <libcfs/libcfs.h>
#include <obd_support.h>
#include <lustre_net.h>
#include <obd.h>
#include <obd_class.h>
#include <lustre_disk.h>
#include <lustre_fid.h>
#include "osd_internal.h"
#include <sys/dnode.h>
#include <sys/dbuf.h>
#include <sys/spa.h>
#include <sys/stat.h>
#include <sys/zap.h>
#include <sys/spa_impl.h>
#include <sys/zfs_znode.h>
#include <sys/dmu_tx.h>
#include <sys/dmu_objset.h>
#include <sys/dsl_prop.h>
#include <sys/sa_impl.h>
#include <sys/txg.h>
#include <linux/posix_acl_xattr.h>
Defines
#define DEBUG_SUBSYSTEM S_OSD
Functions
int __osd_xattr_load (struct osd_device *osd, uint64_t dnode, nvlist_t **sa)
static int __osd_xattr_cache (const struct lu_env *env, struct osd_object *obj)
static int __osd_sa_xattr_get (const struct lu_env *env, struct osd_object *obj, const struct lu_buf *buf, const char *name, int *sizep)
int __osd_xattr_get_large (const struct lu_env *env, struct osd_device *osd, uint64_t xattr, struct lu_buf *buf, const char *name, int *sizep)
int __osd_xattr_get (const struct lu_env *env, struct osd_object *obj, struct lu_buf *buf, const char *name, int *sizep)
Copy an extended attribute into the buffer provided, or compute the required buffer size if buf is NULL.
int osd_xattr_get (const struct lu_env *env, struct dt_object *dt, struct lu_buf *buf, const char *name)
void __osd_xattr_declare_set (const struct lu_env *env, struct osd_object *obj, int vallen, const char *name, struct osd_thandle *oh)
int osd_declare_xattr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, const char *name, int fl, struct thandle *handle)
static int __osd_sa_xattr_update (const struct lu_env *env, struct osd_object *obj, struct osd_thandle *oh)
int __osd_sa_xattr_set (const struct lu_env *env, struct osd_object *obj, const struct lu_buf *buf, const char *name, int fl, struct osd_thandle *oh)
int __osd_xattr_set (const struct lu_env *env, struct osd_object *obj, const struct lu_buf *buf, const char *name, int fl, struct osd_thandle *oh)
int osd_xattr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, const char *name, int fl, struct thandle *handle)
static void __osd_xattr_declare_del (const struct lu_env *env, struct osd_object *obj, const char *name, struct osd_thandle *oh)
int osd_declare_xattr_del (const struct lu_env *env, struct dt_object *dt, const char *name, struct thandle *handle)
static int __osd_sa_xattr_del (const struct lu_env *env, struct osd_object *obj, const char *name, struct osd_thandle *oh)
static int __osd_xattr_del (const struct lu_env *env, struct osd_object *obj, const char *name, struct osd_thandle *oh)
int osd_xattr_del (const struct lu_env *env, struct dt_object *dt, const char *name, struct thandle *handle)
void osd_declare_xattrs_destroy (const struct lu_env *env, struct osd_object *obj, struct osd_thandle *oh)
int osd_xattrs_destroy (const struct lu_env *env, struct osd_object *obj, struct osd_thandle *oh)
static int osd_sa_xattr_list (const struct lu_env *env, struct osd_object *obj, const struct lu_buf *lb)
int osd_xattr_list (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *lb)
Define Documentation
#define DEBUG_SUBSYSTEM S_OSD
Definition at line 43 of file osd_xattr.c.
Function Documentation
static int __osd_sa_xattr_del (const struct lu_env * env, struct osd_object * obj, const char * name, struct osd_thandle * oh) [static]
Definition at line 680 of file osd_xattr.c.
References __osd_sa_xattr_update(), __osd_xattr_cache(), and osd_object::oo_sa_xattr.
Referenced by __osd_xattr_del().
static int __osd_sa_xattr_get (const struct lu_env * env, struct osd_object * obj, const struct lu_buf * buf, const char * name, int * sizep) [static]
Definition at line 118 of file osd_xattr.c.
References __osd_xattr_cache(), LASSERT, lu_buf::lb_buf, lu_buf::lb_len, osd_object::oo_sa_hdl, and osd_object::oo_sa_xattr.
Referenced by __osd_xattr_get().
int __osd_sa_xattr_set (const struct lu_env * env, struct osd_object * obj, const struct lu_buf * buf, const char * name, int fl, struct osd_thandle * oh)
Definition at line 397 of file osd_xattr.c.
References __osd_sa_xattr_update(), __osd_xattr_cache(), LASSERT, lu_buf::lb_buf, lu_buf::lb_len, LU_XATTR_CREATE, LU_XATTR_REPLACE, osd_device::od_os, osd_object::oo_sa_hdl, osd_object::oo_sa_xattr, osd_object::oo_xattr, osd_obj2dev(), osd_thandle::ot_tx, and size.
static int __osd_sa_xattr_update (const struct lu_env * env, struct osd_object * obj, struct osd_thandle * oh) [static]
Definition at line 365 of file osd_xattr.c.
References ENTRY, GOTO, LASSERT, osd_object::oo_sa_hdl, osd_object::oo_sa_xattr, osd_obj2dev(), osd_object_sa_update(), osd_zio_buf_alloc, osd_zio_buf_free, and RETURN.
Referenced by __osd_sa_xattr_del(), and __osd_sa_xattr_set().
static int __osd_xattr_cache (const struct lu_env * env, struct osd_object * obj) [inline, static]
Definition at line 107 of file osd_xattr.c.
References __osd_xattr_load(), LASSERT, osd_object::oo_db, osd_object::oo_sa_xattr, and osd_obj2dev().
Referenced by __osd_sa_xattr_del(), __osd_sa_xattr_get(), __osd_sa_xattr_set(), and osd_sa_xattr_list().
static void __osd_xattr_declare_del (const struct lu_env * env, struct osd_object * obj, const char * name, struct osd_thandle * oh) [static]
Definition at line 623 of file osd_xattr.c.
References osd_device::od_os, osd_object::oo_sa_hdl, osd_object::oo_xattr, osd_obj2dev(), and osd_thandle::ot_tx.
Referenced by osd_declare_xattr_del().
void __osd_xattr_declare_set (const struct lu_env * env, struct osd_object * obj, int vallen, const char * name, struct osd_thandle * oh)
Definition at line 270 of file osd_xattr.c.
References dt_object_exists(), LASSERT, osd_device::od_os, osd_object::oo_db, osd_object::oo_destroyed, osd_object::oo_dt, osd_object::oo_sa_hdl, osd_object::oo_xattr, osd_obj2dev(), osd_thandle::ot_tx, and unlikely.
Referenced by osd_declare_attr_set(), osd_declare_object_create(), and osd_declare_xattr_set().
static int __osd_xattr_del (const struct lu_env * env, struct osd_object * obj, const char * name, struct osd_thandle * oh) [static]
Definition at line 697 of file osd_xattr.c.
References __osd_sa_xattr_del(), dt_object_exists(), osd_device::od_os, osd_object::oo_destroyed, osd_object::oo_dt, osd_object::oo_xattr, osd_obj2dev(), osd_thandle::ot_tx, and unlikely.
Referenced by osd_xattr_del().
int __osd_xattr_get (const struct lu_env * env, struct osd_object * obj, struct lu_buf * buf, const char * name, int * sizep)
Copy an extended attribute into the buffer provided, or compute the required buffer size if buf is NULL.
On success, the number of bytes used or required is stored in sizep.
Note that no locking is done here.
Parameters:
[in] env execution environment
[in] obj object for which to retrieve xattr
[out] buf buffer to store xattr value in
[in] name name of xattr to copy
[out] sizep bytes used or required to store xattr
Return values:
0 on success
negative negated errno on failure
Definition at line 227 of file osd_xattr.c.
References __osd_sa_xattr_get(), __osd_xattr_get_large(), dt_object_exists(), osd_object::oo_destroyed, osd_object::oo_dt, osd_object::oo_xattr, osd_obj2dev(), and unlikely.
Referenced by osd_check_lma(), osd_declare_xattr_set(), osd_ea_fid_set(), osd_get_idif(), osd_get_lma(), osd_get_pfid_from_linkea(), osd_scrub_convert_ff(), and osd_xattr_get().
int __osd_xattr_get_large (const struct lu_env * env, struct osd_device * osd, uint64_t xattr, struct lu_buf * buf, const char * name, int * sizep)
Definition at line 150 of file osd_xattr.c.
References __osd_obj2dbuf(), lu_buf::lb_buf, lu_buf::lb_len, osd_device::od_os, sa_lookup(), and size.
Referenced by __osd_xattr_get(), and osd_get_fid_by_oid().
int __osd_xattr_load (struct osd_device * osd, uint64_t dnode, nvlist_t ** sa)
Definition at line 72 of file osd_xattr.c.
References buf, osd_device::od_os, osd_zio_buf_alloc, osd_zio_buf_free, sa_lookup(), size, and unlikely.
Referenced by __osd_xattr_cache(), osd_get_fid_by_oid(), and osd_zfs_otable_it_next().
int __osd_xattr_set (const struct lu_env * env, struct osd_object * obj, const struct lu_buf * buf, const char * name, int fl, struct osd_thandle * oh)
Definition at line 477 of file osd_xattr.c.
References __osd_obj2dbuf(), __osd_object_create(), __osd_zap_create(), lu_attr::la_mode, LA_MODE, lu_attr::la_valid, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, LU_XATTR_CREATE, LU_XATTR_REPLACE, osd_device::od_os, osd_object::oo_db, osd_object::oo_sa_hdl, osd_object::oo_xattr, osd_obj2dev(), osd_object_sa_update(), osd_oti_get(), osd_thandle::ot_tx, osd_thread_info::oti_la, sa_lookup(), and size.
Referenced by osd_add_to_remote_parent(), osd_attr_set(), osd_delete_from_remote_parent(), osd_ea_fid_set(), osd_scrub_convert_ff(), and osd_xattr_set().
int osd_declare_xattr_del (const struct lu_env * env, struct dt_object * dt, const char * name, struct thandle * handle)
Definition at line 658 of file osd_xattr.c.
References __osd_xattr_declare_del(), dt_object_exists(), ENTRY, LASSERT, likely, osd_object::oo_db, osd_object::oo_destroyed, osd_object::oo_dt, osd_object::oo_guard, osd_dt_obj(), osd_invariant, osd_thandle::ot_super, osd_thandle::ot_tx, and RETURN.
int osd_declare_xattr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, const char * name, int fl, struct thandle * handle)
Definition at line 338 of file osd_xattr.c.
References __osd_xattr_declare_set(), ENTRY, LASSERT, lu_buf::lb_len, osd_object::oo_guard, osd_dt_obj(), osd_thandle::ot_super, and RETURN.
void osd_declare_xattrs_destroy (const struct lu_env * env, struct osd_object * obj, struct osd_thandle * oh)
Definition at line 761 of file osd_xattr.c.
References CERROR, LASSERT, osd_device::od_os, osd_device::od_svname, osd_object::oo_xattr, osd_obj2dev(), osd_oti_get(), osd_zap_cursor_fini(), osd_zap_cursor_init(), osd_thandle::ot_tx, and osd_thread_info::oti_za.
Referenced by osd_declare_object_destroy().
static int osd_sa_xattr_list (const struct lu_env * env, struct osd_object * obj, const struct lu_buf * lb) [static]
Definition at line 852 of file osd_xattr.c.
References __osd_xattr_cache(), LASSERT, lu_buf::lb_buf, lu_buf::lb_len, name, osd_device::od_posix_acl, osd_object::oo_sa_xattr, and osd_obj2dev().
Referenced by osd_xattr_list().
int osd_xattr_del (const struct lu_env * env, struct dt_object * dt, const char * name, struct thandle * handle)
Definition at line 734 of file osd_xattr.c.
References __osd_xattr_del(), dt_object_exists(), ENTRY, LASSERT, osd_object::oo_db, osd_object::oo_guard, osd_dt_obj(), osd_invariant, osd_obj2dev(), osd_thandle::ot_super, osd_thandle::ot_tx, and RETURN.
int osd_xattr_get (const struct lu_env * env, struct dt_object * dt, struct lu_buf * buf, const char * name)
Definition at line 244 of file osd_xattr.c.
References __osd_xattr_get(), ENTRY, LASSERT, osd_object::oo_db, osd_object::oo_guard, osd_dt_obj(), osd_invariant, osd_obj2dev(), RETURN, and size.
Referenced by __osd_object_attr_get(), osd_attr_set(), osd_check_lma(), and osd_find_parent_fid().
int osd_xattr_list (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * lb)
Definition at line 887 of file osd_xattr.c.
References dt_object_exists(), ENTRY, GOTO, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, osd_device::od_os, osd_device::od_posix_acl, osd_object::oo_db, osd_object::oo_guard, osd_object::oo_xattr, osd_dt_obj(), osd_invariant, osd_obj2dev(), osd_oti_get(), osd_sa_xattr_list(), osd_zap_cursor_fini(), osd_zap_cursor_init(), osd_thread_info::oti_za, RETURN, and unlikely.
int osd_xattr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, const char * name, int fl, struct thandle * handle)
Definition at line 590 of file osd_xattr.c.
References CDEBUG, D_INODE, ENTRY, LASSERT, lu_buf::lb_len, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_LINKEA_OVERFLOW, osd_object::oo_guard, osd_dt_obj(), osd_invariant, osd_obj2dev(), osd_thandle::ot_super, RETURN, and XATTR_NAME_LINK.
int osd_xattrs_destroy (const struct lu_env * env, struct osd_object * obj, struct osd_thandle * oh)
Definition at line 803 of file osd_xattr.c.
References CERROR, LASSERT, LPU64, osd_device::od_os, osd_device::od_svname, osd_object::oo_xattr, osd_obj2dev(), osd_oti_get(), osd_zap_cursor_fini(), osd_zap_cursor_init(), osd_thandle::ot_tx, and osd_thread_info::oti_za.
Referenced by osd_object_destroy().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.