Lustre: lustre/osd-ldiskfs/osd_quota_fmt.c File Reference
lustre/osd-ldiskfs/osd_quota_fmt.c File Reference
#include "osd_internal.h"
#include "osd_quota_fmt.h"
Typedefs
typedef char * dqbuf_t
Functions
static dqbuf_t getdqbuf (void)
static void freedqbuf (dqbuf_t buf)
static ssize_t quota_read_blk (const struct lu_env *env, struct osd_object *obj, int type, uint blk, dqbuf_t buf)
Read the blk into buf.
static loff_t find_block_dqentry (const struct lu_env *env, struct osd_object *obj, int type, qid_t dqid, uint blk, struct osd_it_quota *it)
Find entry in block by given dqid in the leaf block blk.
loff_t find_tree_dqentry (const struct lu_env *env, struct osd_object *obj, int type, qid_t dqid, uint blk, int depth, struct osd_it_quota *it)
Find entry for given dqid in the tree block blk.
int walk_block_dqentry (const struct lu_env *env, struct osd_object *obj, int type, uint blk, uint index, struct osd_it_quota *it)
Search from index within the leaf block blk, and fill the it with the first valid entry.
int walk_tree_dqentry (const struct lu_env *env, struct osd_object *obj, int type, uint blk, int depth, uint index, struct osd_it_quota *it)
Search from index within the tree block blk, and fill the it with the first valid entry.
Variables
union {
struct lustre_disk_dqblk_v2 r1
} emptydquot
Typedef Documentation
typedef char* dqbuf_t
Definition at line 34 of file osd_quota_fmt.c.
Function Documentation
static loff_t find_block_dqentry (const struct lu_env * env, struct osd_object * obj, int type, qid_t dqid, uint blk, struct osd_it_quota * it) [static]
Find entry in block by given dqid in the leaf block blk.
Return values:
+ve,the offset of the entry in file
0,entry not found
-ve,unexpected failure
Definition at line 86 of file osd_quota_fmt.c.
References buf, CDEBUG, CERROR, D_QUOTA, lustre_disk_dqblk_v2::dqb_id, emptydquot, ENTRY, freedqbuf(), getdqbuf(), GETENTRIES, GOTO, le32_to_cpu, LUSTRE_DQBLKSIZE_BITS, LUSTRE_DQSTRINBLK, LUSTRE_DQTREEDEPTH, osd_it_quota::oiq_blk, osd_it_quota::oiq_id, osd_it_quota::oiq_index, osd_it_quota::oiq_offset, quota_read_blk(), ret, and RETURN.
Referenced by find_tree_dqentry().
loff_t find_tree_dqentry (const struct lu_env * env, struct osd_object * obj, int type, qid_t dqid, uint blk, int depth, struct osd_it_quota * it)
Find entry for given dqid in the tree block blk.
Return values:
+ve,the offset of the entry in file
0,entry not found
-ve,unexpected failure
Definition at line 149 of file osd_quota_fmt.c.
References buf, CERROR, ENTRY, find_block_dqentry(), find_tree_dqentry(), freedqbuf(), getdqbuf(), GETIDINDEX, GOTO, le32_to_cpu, LUSTRE_DQTREEDEPTH, osd_it_quota::oiq_blk, osd_it_quota::oiq_index, quota_read_blk(), ret, and RETURN.
Referenced by find_tree_dqentry(), and osd_it_acct_get().
static void freedqbuf (dqbuf_t buf) [inline, static]
Definition at line 49 of file osd_quota_fmt.c.
Referenced by find_block_dqentry(), find_tree_dqentry(), walk_block_dqentry(), and walk_tree_dqentry().
static dqbuf_t getdqbuf (void) [inline, static]
Definition at line 41 of file osd_quota_fmt.c.
References buf, CWARN, and LUSTRE_DQBLKSIZE.
Referenced by find_block_dqentry(), find_tree_dqentry(), walk_block_dqentry(), and walk_tree_dqentry().
static ssize_t quota_read_blk (const struct lu_env * env, struct osd_object * obj, int type, uint blk, dqbuf_t buf) [static]
Read the blk into buf.
Definition at line 57 of file osd_quota_fmt.c.
References ENTRY, LASSERTF, LUSTRE_DQBLKSIZE, LUSTRE_DQBLKSIZE_BITS, osd_object::oo_inode, ret, and RETURN.
Referenced by find_block_dqentry(), find_tree_dqentry(), walk_block_dqentry(), and walk_tree_dqentry().
int walk_block_dqentry (const struct lu_env * env, struct osd_object * obj, int type, uint blk, uint index, struct osd_it_quota * it)
Search from index within the leaf block blk, and fill the it with the first valid entry.
Return values:
+ve,no valid entry found
0,entry found
-ve,unexpected failure
Definition at line 196 of file osd_quota_fmt.c.
References buf, CERROR, lustre_disk_dqblk_v2::dqb_id, lustre_disk_dqdbheader::dqdh_entries, emptydquot, ENTRY, freedqbuf(), getdqbuf(), GETENTRIES, GOTO, LASSERT, le16_to_cpu, le32_to_cpu, list_for_each_entry, LUSTRE_DQBLKSIZE_BITS, LUSTRE_DQSTRINBLK, LUSTRE_DQTREEDEPTH, osd_it_quota::oiq_blk, osd_it_quota::oiq_id, osd_it_quota::oiq_index, osd_it_quota::oiq_list, osd_it_quota::oiq_offset, osd_quota_leaf::oql_blk, osd_quota_leaf::oql_link, quota_read_blk(), ret, and RETURN.
Referenced by osd_it_acct_next(), and walk_tree_dqentry().
int walk_tree_dqentry (const struct lu_env * env, struct osd_object * obj, int type, uint blk, int depth, uint index, struct osd_it_quota * it)
Search from index within the tree block blk, and fill the it with the first valid entry.
Return values:
+ve,no valid entry found
0,entry found
-ve,unexpected failure
Definition at line 260 of file osd_quota_fmt.c.
References buf, CERROR, ENTRY, freedqbuf(), getdqbuf(), le32_to_cpu, LUSTRE_DQTREEDEPTH, osd_it_quota::oiq_blk, osd_it_quota::oiq_index, quota_read_blk(), ret, RETURN, walk_block_dqentry(), and walk_tree_dqentry().
Referenced by osd_it_acct_get(), osd_it_acct_next(), and walk_tree_dqentry().
Variable Documentation
union { ... } emptydquot [static]
Referenced by find_block_dqentry(), and walk_block_dqentry().
struct lustre_disk_dqblk_v2 r1
Definition at line 38 of file osd_quota_fmt.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.