Lustre: lustre/osd-ldiskfs/osd_iam.h File Reference
lustre/osd-ldiskfs/osd_iam.h File Reference
#include <linux/module.h>
#include <asm/unaligned.h>
#include "osd_dynlocks.h"
Data Structures
struct iam_entry_compat
struct iam_frame
struct iam_leaf
struct iam_operations
struct iam_leaf_operations
struct iam_descr
struct iam_idle_head
struct iam_container
struct iam_path_descr
struct iam_path
struct iam_path_compat
struct iam_iterator
struct dx_map_entry
struct fake_dirent
struct dx_countlimit
struct dx_root
struct dx_root::dx_root_info
struct dx_node
struct iam_format
struct iam_uapi_info
struct iam_uapi_op
struct iam_uapi_it
Defines
#define CLASSERT(cond) do {switch(42) {case (cond): case 0: break;}} while (0)
#define ergo(a, b) (!(a) || (b))
#define equi(a, b) (!!(a) == !!(b))
#define LDISKFS_ASSERT_ON (0)
#define LDISKFS_CORRECTNESS_ON (0)
#define LDISKFS_INVARIANT_ON (0)
#define assert(test) ((void)(test))
#define assert_corr(test) do {;} while (0)
#define do_corr(exp) do {;} while (0)
#define assert_inv(test) do {;} while (0)
#define const_max(p, q) ((p > q) ? p : q)
#define swap(x, y) do { typeof(x) z = x; x = y; y = z; } while (0)
#define dxtrace(command)
#define BH_DXLock (BH_BITMAP_UPTODATE + 1)
#define DX_DEBUG (0)
#define DX_DEVAL(x)
Typedefs
typedef __u32 iam_ptr_t
typedef __u64 iam_pos_t
Enumerations
enum { DX_MAX_TREE_HEIGHT = 5, DX_SCRATCH_KEYS = 5, DX_FMT_NAME_LEN = 16 }
enum iam_lookup_t {
IAM_LOOKUP_EXACT = 0, IAM_LOOKUP_OK = 1, IAM_LOOKUP_EMPTY = 2, IAM_LOOKUP_BEFORE = 3,
IAM_LOOKUP_LAST = 0x100
}
enum { IAM_IDLE_HEADER_MAGIC = 0x7903 }
enum { DX_MAX_IKEY_SIZE = 32, DX_IPD_MAX_SIZE }
enum iam_it_state { IAM_IT_DETACHED, IAM_IT_ATTACHED, IAM_IT_SKEWED }
enum iam_it_flags { IAM_IT_MOVE = (1 << 0), IAM_IT_WRITE = (1 << 1) }
enum iam_ioctl_cmd {
IAM_IOC_INIT = _IOW('i', 1, struct iam_uapi_info), IAM_IOC_GETINFO = _IOR('i', 2, struct iam_uapi_info), IAM_IOC_INSERT = _IOR('i', 3, struct iam_uapi_op), IAM_IOC_LOOKUP = _IOWR('i', 4, struct iam_uapi_op),
IAM_IOC_DELETE = _IOR('i', 5, struct iam_uapi_op), IAM_IOC_IT_START = _IOR('i', 6, struct iam_uapi_it), IAM_IOC_IT_NEXT = _IOW('i', 7, struct iam_uapi_it), IAM_IOC_IT_STOP = _IOR('i', 8, struct iam_uapi_it),
IAM_IOC_POLYMORPH = _IOR('i', 9, unsigned long), IAM_IOC_INIT = _IOW('i', 1, struct iam_uapi_info), IAM_IOC_GETINFO = _IOR('i', 2, struct iam_uapi_info), IAM_IOC_INSERT = _IOR('i', 3, struct iam_uapi_op),
IAM_IOC_LOOKUP = _IOWR('i', 4, struct iam_uapi_op), IAM_IOC_DELETE = _IOR('i', 5, struct iam_uapi_op), IAM_IOC_IT_START = _IOR('i', 6, struct iam_uapi_it), IAM_IOC_IT_NEXT = _IOW('i', 7, struct iam_uapi_it),
IAM_IOC_IT_STOP = _IOR('i', 8, struct iam_uapi_it), IAM_IOC_POLYMORPH = _IOR('i', 9, unsigned long), IAM_IOC_INIT = _IOW('i', 1, struct iam_uapi_info), IAM_IOC_GETINFO = _IOR('i', 2, struct iam_uapi_info),
IAM_IOC_INSERT = _IOR('i', 3, struct iam_uapi_op), IAM_IOC_LOOKUP = _IOWR('i', 4, struct iam_uapi_op), IAM_IOC_DELETE = _IOR('i', 5, struct iam_uapi_op), IAM_IOC_IT_START = _IOR('i', 6, struct iam_uapi_it),
IAM_IOC_IT_NEXT = _IOW('i', 7, struct iam_uapi_it), IAM_IOC_IT_STOP = _IOR('i', 8, struct iam_uapi_it), IAM_IOC_POLYMORPH = _IOR('i', 9, unsigned long)
}
Functions
void iam_path_init (struct iam_path *path, struct iam_container *c, struct iam_path_descr *pd)
void iam_path_fini (struct iam_path *path)
void iam_path_release (struct iam_path *path)
void iam_path_compat_init (struct iam_path_compat *path, struct inode *inode)
void iam_path_compat_fini (struct iam_path_compat *path)
struct iam_path_descr * iam_ipd_alloc (void *area, int keysize)
void iam_ipd_free (struct iam_path_descr *ipd)
int iam_it_init (struct iam_iterator *it, struct iam_container *c, __u32 flags, struct iam_path_descr *pd)
void iam_it_fini (struct iam_iterator *it)
int iam_it_get (struct iam_iterator *it, const struct iam_key *k)
int iam_it_get_at (struct iam_iterator *it, const struct iam_key *k)
void iam_it_dup (struct iam_iterator *dst, const struct iam_iterator *src)
void iam_it_put (struct iam_iterator *it)
int iam_it_next (struct iam_iterator *it)
struct iam_rec * iam_it_rec_get (const struct iam_iterator *it)
int iam_it_rec_set (handle_t *h, struct iam_iterator *it, const struct iam_rec *r)
struct iam_key * iam_it_key_get (const struct iam_iterator *it)
int iam_it_key_size (const struct iam_iterator *it)
int iam_it_rec_insert (handle_t *h, struct iam_iterator *it, const struct iam_key *k, const struct iam_rec *r)
int iam_it_rec_delete (handle_t *h, struct iam_iterator *it)
iam_pos_t iam_it_store (const struct iam_iterator *it)
int iam_it_load (struct iam_iterator *it, iam_pos_t pos)
int iam_lookup (struct iam_container *c, const struct iam_key *k, struct iam_rec *r, struct iam_path_descr *pd)
int iam_delete (handle_t *h, struct iam_container *c, const struct iam_key *k, struct iam_path_descr *pd)
int iam_update (handle_t *h, struct iam_container *c, const struct iam_key *k, const struct iam_rec *r, struct iam_path_descr *pd)
int iam_insert (handle_t *handle, struct iam_container *c, const struct iam_key *k, const struct iam_rec *r, struct iam_path_descr *pd)
int iam_container_init (struct iam_container *c, struct iam_descr *descr, struct inode *inode)
void iam_container_fini (struct iam_container *c)
int iam_container_setup (struct iam_container *c)
static struct iam_descr * iam_container_descr (struct iam_container *c)
static struct iam_descr * iam_path_descr (const struct iam_path *p)
static struct inode * iam_path_obj (struct iam_path *p)
static void iam_ikeycpy (const struct iam_container *c, struct iam_ikey *k1, const struct iam_ikey *k2)
static size_t iam_entry_size (struct iam_path *p)
static struct iam_entry * iam_entry_shift (struct iam_path *p, struct iam_entry *entry, int shift)
static struct iam_ikey * dx_get_ikey (struct iam_path *p, struct iam_entry *entry, struct iam_ikey *key)
static struct iam_ikey * iam_ikey_at (struct iam_path *p, struct iam_entry *entry)
static ptrdiff_t iam_entry_diff (struct iam_path *p, struct iam_entry *e1, struct iam_entry *e2)
static void iam_ikeycpy0 (const struct iam_container *c, struct iam_ikey *k1, const struct iam_ikey *k2)
static int iam_ikeycmp (const struct iam_container *c, const struct iam_ikey *k1, const struct iam_ikey *k2)
static void * iam_entry_off (struct iam_entry *entry, size_t off)
static struct iam_path * iam_leaf_path (const struct iam_leaf *leaf)
static struct iam_container * iam_leaf_container (const struct iam_leaf *leaf)
static struct iam_descr * iam_leaf_descr (const struct iam_leaf *leaf)
static struct iam_leaf_operations * iam_leaf_ops (const struct iam_leaf *leaf)
static void iam_reccpy (const struct iam_leaf *leaf, struct iam_rec *rec_dst)
static unsigned dx_get_block (struct iam_path *p, struct iam_entry *entry)
static void dx_set_block (struct iam_path *p, struct iam_entry *entry, unsigned value)
static void dx_set_ikey (struct iam_path *p, struct iam_entry *entry, const struct iam_ikey *key)
static unsigned dx_get_count (struct iam_entry *entries)
static unsigned dx_get_limit (struct iam_entry *entries)
static void dx_set_count (struct iam_entry *entries, unsigned value)
static unsigned dx_node_limit (struct iam_path *p)
static unsigned dx_root_limit (struct iam_path *p)
static struct iam_entry * dx_get_entries (struct iam_path *path, void *data, int root)
static struct iam_entry * dx_node_get_entries (struct iam_path *path, struct iam_frame *frame)
static struct iam_ikey * iam_path_ikey (const struct iam_path *path, int nr)
static int iam_leaf_is_locked (const struct iam_leaf *leaf)
static int iam_frame_is_locked (struct iam_path *path, const struct iam_frame *frame)
int dx_lookup_lock (struct iam_path *path, struct dynlock_handle **dl, enum dynlock_type lt)
void dx_insert_block (struct iam_path *path, struct iam_frame *frame, u32 hash, u32 block)
int dx_index_is_compat (struct iam_path *path)
int ldiskfs_htree_next_block (struct inode *dir, __u32 hash, struct iam_path *path, __u32 *start_hash)
int split_index_node (handle_t *handle, struct iam_path *path, struct dynlock_handle **lh)
struct ldiskfs_dir_entry_2 * split_entry (struct inode *dir, struct ldiskfs_dir_entry_2 *de, unsigned long ino, mode_t mode, const char *name, int namelen)
struct ldiskfs_dir_entry_2 * find_insertion_point (struct inode *dir, struct buffer_head *bh, const char *name, int namelen)
struct ldiskfs_dir_entry_2 * move_entries (struct inode *dir, struct ldiskfs_dx_hash_info *hinfo, struct buffer_head **bh1, struct buffer_head **bh2, __u32 *delim_hash)
struct dynlock_handle * dx_lock_htree (struct inode *dir, unsigned long value, enum dynlock_type lt)
void dx_unlock_htree (struct inode *dir, struct dynlock_handle *lh)
void iam_container_write_lock (struct iam_container *c)
void iam_container_write_unlock (struct iam_container *c)
void iam_container_read_lock (struct iam_container *c)
void iam_container_read_unlock (struct iam_container *c)
int iam_index_next (struct iam_container *c, struct iam_path *p)
int iam_read_leaf (struct iam_path *p)
int iam_node_read (struct iam_container *c, iam_ptr_t ptr, handle_t *handle, struct buffer_head **bh)
int iam_lvar_create (struct inode *obj, int keysize, int ptrsize, int recsize, handle_t *handle)
static void iam_lock_bh (struct buffer_head volatile *bh)
static void iam_unlock_bh (struct buffer_head *bh)
void iam_insert_key (struct iam_path *path, struct iam_frame *frame, const struct iam_ikey *key, iam_ptr_t ptr)
void iam_insert_key_lock (struct iam_path *path, struct iam_frame *frame, const struct iam_ikey *key, iam_ptr_t ptr)
int iam_leaf_at_end (const struct iam_leaf *l)
void iam_leaf_next (struct iam_leaf *folio)
int iam_leaf_can_add (const struct iam_leaf *l, const struct iam_key *k, const struct iam_rec *r)
void iam_format_register (struct iam_format *fmt)
int iam_root_limit (int rootgap, int blocksize, int size)
void iam_lfix_format_init (void)
void iam_lvar_format_init (void)
void iam_htree_format_init (void)
int iam_lfix_create (struct inode *obj, int keysize, int ptrsize, int recsize, handle_t *handle)
void ldiskfs_iam_release (struct file *filp, struct inode *inode)
int iam_uapi_ioctl (struct inode *inode, struct file *filp, unsigned int cmd, unsigned long arg)
Variables
struct iam_descr iam_htree_compat_param
Define Documentation
#define assert (test) ((void)(test))
Definition at line 154 of file osd_iam.h.
Referenced by __iam_it_get(), __iam_path_lookup(), cfs_print_nidlist(), doit(), get_ids(), gssd_exit_unique(), gssd_init_unique(), iam_it_collision(), libcfs_ip_addr_range_print(), libcfs_num_addr_range_print(), libcfs_num_match(), libcfs_str2nid(), Parser_getbool(), Parser_getint(), and Parser_getstr().
#define assert_corr (test) do {;} while (0)
Definition at line 162 of file osd_iam.h.
Referenced by __iam_it_get(), h_used_adj(), iam_add_rec(), iam_entry_diff(), iam_find_position(), iam_htree_advance(), iam_index_next(), iam_insert_key(), iam_it_dup(), iam_it_fini(), iam_it_get(), iam_it_get_at(), iam_it_iget(), iam_it_ikey_get(), iam_it_key_get(), iam_it_key_size(), iam_it_load(), iam_it_next(), iam_it_rec_delete(), iam_it_rec_get(), iam_it_rec_insert(), iam_it_rec_set(), iam_it_store(), iam_lfix_create(), iam_lfix_diff(), iam_lfix_guess(), iam_lfix_ikey(), iam_lfix_init(), iam_lfix_key(), iam_lfix_key_set(), iam_lfix_lookup(), iam_lfix_next(), iam_lfix_rec(), iam_lfix_rec_add(), iam_lfix_rec_del(), iam_lfix_rec_get(), iam_lfix_rec_set(), iam_lfix_root_inc(), iam_lfix_split(), iam_lvar_create(), lentry_count_set(), lvar_at_end(), lvar_can_add(), lvar_guess(), lvar_ikey(), lvar_init(), lvar_key_set(), lvar_lookup(), lvar_next(), lvar_rec(), lvar_rec_add(), lvar_rec_del(), lvar_rec_get(), lvar_rec_set(), lvar_root_inc(), lvar_split(), and split_index_node().
#define assert_inv (test) do {;} while (0)
Definition at line 169 of file osd_iam.h.
Referenced by iam_add_rec(), iam_htree_advance(), iam_insert_key(), iam_it_rec_delete(), iam_leaf_fini(), iam_leaf_load(), iam_lookup_try(), iam_new_leaf(), iam_path_lookup(), lvar_ilookup(), lvar_key_set(), lvar_lookup(), lvar_rec_add(), lvar_rec_del(), lvar_rec_get(), lvar_rec_set(), lvar_split(), and split_index_node().
#define BH_DXLock (BH_BITMAP_UPTODATE + 1)
Definition at line 1023 of file osd_iam.h.
Referenced by iam_lock_bh(), iam_unlock_bh(), and osd_init().
#define CLASSERT (cond) do {switch(42) {case (cond): case 0: break;}} while (0)
Definition at line 54 of file osd_iam.h.
Referenced by cfs_hash_create(), cl_env_peek(), cl_lock_mode_name(), class_uuid_unparse(), getsize(), kgnilnd_create_conn(), kgnilnd_pack_connreq(), kgnilnd_unmap_buffer(), kiblnd_map_tx_pool(), kiblnd_startup(), kiblnd_unpack_msg(), ko2iblnd_init(), ksocklnd_init(), ksocknal_parse_proto_version(), ksocknal_send_hello_v1(), ldlm_resource_dump(), lnet_assert_wire_constants(), lnet_connect(), lnet_fault_init(), lnet_fill_ni_info(), lnet_ipif_query(), lnet_selftest_structure_assertion(), LNetCtl(), lod_xattr_get(), lov_getstripe(), lov_lsm_pack(), lustre_assert_wire_constants(), lustre_init(), lustre_swab_connect(), lustre_swab_gl_desc(), lustre_swab_ladvise(), lustre_swab_ladvise_hdr(), lustre_swab_ldlm_reply(), lustre_swab_ldlm_resource_desc(), lustre_swab_lfsck_reply(), lustre_swab_lfsck_request(), lustre_swab_lmv_user_md(), lustre_swab_lustre_capa_key(), lustre_swab_mdt_body(), lustre_swab_mdt_ioepoch(), lustre_swab_mdt_rec_reint(), lustre_swab_mgs_nidtbl_entry(), lustre_swab_mgs_target_info(), lustre_swab_obd_dqblk(), lustre_swab_obd_statfs(), lustre_swab_obdo(), lustre_swab_ptlrpc_body(), lustre_unpack_msg_v2(), mdc_create_pack(), mdc_intent_getattr_async(), mdc_link_pack(), mdc_open_pack(), mdc_rename_pack(), mdc_setattr_pack(), mdc_unlink_pack(), mdc_xattr_common(), mdd_attr_set_changelog(), mdd_hsm_update_locked(), mdd_swap_layouts(), mdt_attr_get_complex(), mdt_create_unpack(), mdt_hsm_attr_set(), mdt_hsm_cdt_start(), mdt_hsm_release(), mdt_init(), mdt_link_unpack(), mdt_open_unpack(), mdt_rename_unpack(), mdt_setattr_unpack_rec(), mdt_setxattr_unpack(), mdt_unlink_unpack(), nodemap_cluster_rec_init(), nodemap_idx_insert(), nodemap_process_keyrec(), ofd_punch_hdl(), osc_brw_prep_request(), osc_build_rpc(), osc_enqueue_base(), osc_io_data_version_start(), osc_ladvise_base(), osc_punch_base(), osc_set_info_async(), osc_setattr_async(), osc_statfs_async(), osc_sync_base(), osd_attr_set(), osd_blk_insert_cost(), osd_check_lma(), osd_dir_insert(), osd_dir_it_next(), osd_get_lma(), osd_init(), osd_objs_count_estimate(), osd_objset_statfs(), osd_statfs(), proc_lnet_peers(), proc_lnet_routes(), ptlrpc_connect_import(), ptlrpc_fill_bulk_md(), ptlrpc_init_xid(), ptlrpcd_alloc_work(), qsd_intent_lock(), qsd_send_dqacq(), replay_one_lock(), seq_server_init(), tgt_clients_data_init(), tgt_server_data_init(), and vvp_pgcache_id_unpack().
#define const_max (p, q) ((p > q) ? p : q)
Definition at line 558 of file osd_iam.h.
#define do_corr (exp) do {;} while (0)
Definition at line 163 of file osd_iam.h.
Referenced by __iam_path_lookup(), iam_add_rec(), iam_check_full_path(), iam_htree_advance(), iam_index_lock(), iam_index_next(), iam_it_collision(), iam_it_next(), iam_leaf_unlock(), iam_lookup_lock(), iam_lookup_try(), iam_new_leaf(), iam_path_lookup(), and split_index_node().
#define DX_DEBUG (0)
Definition at line 1024 of file osd_iam.h.
#define DX_DEVAL (x)
Definition at line 1034 of file osd_iam.h.
Referenced by iam_check_full_path(), iam_check_path(), and iam_lock_bh().
#define dxtrace (command)
Definition at line 1020 of file osd_iam.h.
Referenced by iam_shift_entries(), and split_index_node().
#define equi (a, b) (!!(a) == !!(b))
Definition at line 59 of file osd_iam.h.
Referenced by cl_env_cache_purge(), cl_env_obtain(), cl_page_prep(), cl_page_state_set0(), gss_cli_ctx_unseal(), gss_cli_ctx_verify(), iam_it_invariant(), lock_matches(), osc_completion(), osc_lock_enqueue(), osc_send_write_rpc(), plain_ctx_verify(), and rawobj_empty().
#define ergo (a, b) (!(a) || (b))
Definition at line 57 of file osd_iam.h.
Referenced by cfs_hash_create(), cl_env_fetch(), cl_env_put(), cl_io_fini(), cl_io_invariant(), cl_io_submit_rw(), cl_page_own0(), cl_page_prep(), discard_cb(), iam_it_collision(), iam_it_dup(), iam_it_get(), iam_it_get_at(), iam_it_invariant(), iam_it_next(), iam_it_rec_insert(), iam_leaf_fini(), iam_leaf_load(), iam_path_lookup(), ldlm_cli_enqueue_fini(), ll_page_mkwrite0(), llog_osd_write_rec(), lov_init_raid0(), lov_io_commit_async(), lov_lock_sub_init(), lov_sub_find(), lu2dt_obj(), lu2lod_obj(), lu2mdd_obj(), lu2mgs_obj(), lu2osp_obj(), lu_device_is_dt(), lu_device_is_lod(), lu_device_is_md(), lu_device_is_mdd(), lu_device_is_mgs(), lu_device_is_osd(), lu_device_is_osp(), mdt_getattr_name_lock(), mdt_intent_policy(), mdt_reconstruct_open(), mdt_reint_open(), mgs_ir_update(), mgs_nidtbl_read(), nrs_request_get(), nrs_svcpt2nrs(), obd_connect(), obd_reconnect(), ofd_precreate_objects(), osc_brw_prep_request(), osc_extent_truncate(), osc_lock_enqueue(), osc_lock_invariant(), osc_lock_to_lockless(), osc_page_cancel(), osc_page_delete(), osd_iam_index_probe(), osd_object_create(), osd_object_ea_create(), osd_oi_init(), ptlrpc_nrs_policy_register(), tgt_last_rcvd_update(), tgt_last_rcvd_update_echo(), tgt_request_preprocess(), vvp_io_write_commit(), and vvp_page_completion_write().
#define LDISKFS_ASSERT_ON (0)
Definition at line 135 of file osd_iam.h.
#define LDISKFS_CORRECTNESS_ON (0)
Definition at line 141 of file osd_iam.h.
#define LDISKFS_INVARIANT_ON (0)
Definition at line 147 of file osd_iam.h.
Referenced by iam_lookup_try().
#define swap (x, y) do { typeof(x) z = x; x = y; y = z; } while (0)
Definition at line 1014 of file osd_iam.h.
Referenced by ll_swap_layouts(), mdd_swap_layouts(), mdt_close_swap_layouts(), mdt_quotactl(), mdt_swap_layouts(), ofd_quotactl(), qmt_adjust_qunit(), and split_index_node().
Typedef Documentation
typedef __u64 iam_pos_t
Definition at line 671 of file osd_iam.h.
typedef __u32 iam_ptr_t
Definition at line 201 of file osd_iam.h.
Enumeration Type Documentation
anonymous enum
Enumerator:
DX_MAX_TREE_HEIGHT
DX_SCRATCH_KEYS
DX_FMT_NAME_LEN
Definition at line 61 of file osd_iam.h.
anonymous enum
Enumerator:
IAM_IDLE_HEADER_MAGIC
Definition at line 451 of file osd_iam.h.
anonymous enum
Enumerator:
DX_MAX_IKEY_SIZE
DX_IPD_MAX_SIZE
Definition at line 560 of file osd_iam.h.
enum iam_ioctl_cmd
Enumerator:
IAM_IOC_INIT
IAM_IOC_GETINFO
IAM_IOC_INSERT
IAM_IOC_LOOKUP
IAM_IOC_DELETE
IAM_IOC_IT_START
IAM_IOC_IT_NEXT
IAM_IOC_IT_STOP
IAM_IOC_POLYMORPH
IAM_IOC_INIT
IAM_IOC_GETINFO
IAM_IOC_INSERT
IAM_IOC_LOOKUP
IAM_IOC_DELETE
IAM_IOC_IT_START
IAM_IOC_IT_NEXT
IAM_IOC_IT_STOP
IAM_IOC_POLYMORPH
IAM_IOC_INIT
IAM_IOC_GETINFO
IAM_IOC_INSERT
IAM_IOC_LOOKUP
IAM_IOC_DELETE
IAM_IOC_IT_START
IAM_IOC_IT_NEXT
IAM_IOC_IT_STOP
IAM_IOC_POLYMORPH
Definition at line 1156 of file osd_iam.h.
enum iam_it_flags
Enumerator:
IAM_IT_MOVE
IAM_IT_WRITE
Definition at line 589 of file osd_iam.h.
enum iam_it_state
Enumerator:
IAM_IT_DETACHED
IAM_IT_ATTACHED
IAM_IT_SKEWED
Definition at line 577 of file osd_iam.h.
enum iam_lookup_t
Enumerator:
IAM_LOOKUP_EXACT
IAM_LOOKUP_OK
IAM_LOOKUP_EMPTY
IAM_LOOKUP_BEFORE
IAM_LOOKUP_LAST
Definition at line 253 of file osd_iam.h.
Function Documentation
static unsigned dx_get_block (struct iam_path * p, struct iam_entry * entry) [inline, static]
Definition at line 814 of file osd_iam.h.
References iam_entry_off(), iam_path_descr(), and le32_to_cpu.
Referenced by iam_check_fast(), iam_check_full_path(), iam_find_ptr(), iam_htree_advance(), iam_index_shrink(), and iam_lookup_try().
static unsigned dx_get_count (struct iam_entry * entries) [inline, static]
Definition at line 885 of file osd_iam.h.
References le16_to_cpu.
Referenced by iam_check_fast(), iam_check_full_path(), iam_find_position(), iam_htree_advance(), iam_index_shrink(), iam_insert_key(), iam_leaf_load(), iam_lfix_node_check(), lvar_node_check(), and split_index_node().
static struct iam_entry* dx_get_entries (struct iam_path * path, void * data, int root) [static, read]
Definition at line 920 of file osd_iam.h.
References iam_path_descr(), iam_descr::id_node_gap, and iam_descr::id_root_gap.
Referenced by dx_node_get_entries(), and split_index_node().
static struct iam_ikey* dx_get_ikey (struct iam_path * p, struct iam_entry * entry, struct iam_ikey * key) [static, read]
Definition at line 734 of file osd_iam.h.
References iam_path_descr().
Referenced by iam_htree_advance(), and iam_shift_entries().
static unsigned dx_get_limit (struct iam_entry * entries) [inline, static]
Definition at line 890 of file osd_iam.h.
References le16_to_cpu.
Referenced by iam_find_position(), iam_insert_key(), iam_lfix_node_check(), iam_lfix_root_inc(), lvar_node_check(), lvar_root_inc(), and split_index_node().
int dx_index_is_compat (struct iam_path * path)
Definition at line 798 of file osd_iam.c.
References iam_path_descr().
Referenced by iam_find_position(), iam_shift_entries(), and split_index_node().
void dx_insert_block (struct iam_path * path, struct iam_frame * frame, u32 hash, u32 block)
struct dynlock_handle* dx_lock_htree (struct inode * dir, unsigned long value, enum dynlock_type lt) [read]
int dx_lookup_lock (struct iam_path * path, struct dynlock_handle ** dl, enum dynlock_type lt)
static struct iam_entry* dx_node_get_entries (struct iam_path * path, struct iam_frame * frame) [static, read]
Definition at line 928 of file osd_iam.h.
References iam_frame::bh, dx_get_entries(), and iam_path::ip_frames.
Referenced by iam_htree_advance(), iam_leaf_load(), iam_lfix_node_check(), iam_lfix_node_load(), lvar_node_check(), and lvar_node_load().
static unsigned dx_node_limit (struct iam_path * p) [inline, static]
Definition at line 900 of file osd_iam.h.
References iam_path_descr(), iam_path_obj(), iam_descr::id_ikey_size, iam_descr::id_node_gap, and iam_descr::id_ptr_size.
Referenced by dx_root_limit(), iam_lfix_node_check(), iam_shift_entries(), lvar_node_check(), and split_index_node().
static unsigned dx_root_limit (struct iam_path * p) [inline, static]
Definition at line 908 of file osd_iam.h.
References dx_node_limit(), iam_path_descr(), iam_path_obj(), iam_descr::id_ikey_size, iam_descr::id_ptr_size, and iam_descr::id_root_gap.
Referenced by iam_lfix_node_check(), iam_lfix_root_inc(), lvar_node_check(), lvar_root_inc(), and split_index_node().
static void dx_set_block (struct iam_path * p, struct iam_entry * entry, unsigned value) [inline, static]
Definition at line 822 of file osd_iam.h.
References cpu_to_le32, iam_entry_off(), and iam_path_descr().
Referenced by iam_insert_key(), and split_index_node().
static void dx_set_count (struct iam_entry * entries, unsigned value) [inline, static]
Definition at line 895 of file osd_iam.h.
References cpu_to_le16.
Referenced by iam_index_shrink(), iam_insert_key(), iam_lfix_root_inc(), iam_shift_entries(), and lvar_root_inc().
static void dx_set_ikey (struct iam_path * p, struct iam_entry * entry, const struct iam_ikey * key) [inline, static]
Definition at line 831 of file osd_iam.h.
References iam_entry_off(), iam_ikeycpy(), and iam_path::ip_container.
Referenced by iam_insert_key().
void dx_unlock_htree (struct inode * dir, struct dynlock_handle * lh)
struct ldiskfs_dir_entry_2* find_insertion_point (struct inode * dir, struct buffer_head * bh, const char * name, int namelen) [read]
static struct iam_descr* iam_container_descr (struct iam_container * c) [static, read]
Definition at line 700 of file osd_iam.h.
References iam_container::ic_descr.
void iam_container_fini (struct iam_container * c)
Definition at line 282 of file osd_iam.c.
References iam_container::ic_idle_bh, and iam_container::ic_root_bh.
Referenced by osd_iam_container_init(), osd_index_fini(), osd_oi_open(), and osd_oi_table_put().
int iam_container_init (struct iam_container * c, struct iam_descr * descr, struct inode * inode)
Definition at line 259 of file osd_iam.c.
References dynlock_init(), iam_container::ic_descr, iam_container::ic_idle_mutex, iam_container::ic_object, iam_container::ic_sem, and iam_container::ic_tree_lock.
Referenced by osd_iam_container_init(), and osd_oi_open().
void iam_container_read_lock (struct iam_container * c)
Definition at line 703 of file osd_iam.c.
References iam_container::ic_sem.
void iam_container_read_unlock (struct iam_container * c)
Definition at line 708 of file osd_iam.c.
References iam_container::ic_sem.
int iam_container_setup (struct iam_container * c)
Definition at line 274 of file osd_iam.c.
References iam_format_guess().
Referenced by osd_iam_container_init(), and osd_oi_open().
void iam_container_write_lock (struct iam_container * c)
Definition at line 693 of file osd_iam.c.
References iam_container::ic_sem.
void iam_container_write_unlock (struct iam_container * c)
Definition at line 698 of file osd_iam.c.
References iam_container::ic_sem.
int iam_delete (handle_t * h, struct iam_container * c, const struct iam_key * k, struct iam_path_descr * pd)
Definition at line 2664 of file osd_iam.c.
References iam_it_fini(), iam_it_get_exact(), iam_it_init(), iam_it_put(), iam_it_rec_delete(), and IAM_IT_WRITE.
static ptrdiff_t iam_entry_diff (struct iam_path * p, struct iam_entry * e1, struct iam_entry * e2) [inline, static]
Definition at line 747 of file osd_iam.h.
References assert_corr, and iam_entry_size().
Referenced by iam_find_position(), and split_index_node().
static void* iam_entry_off (struct iam_entry * entry, size_t off) [inline, static]
Definition at line 776 of file osd_iam.h.
Referenced by dx_get_block(), dx_set_block(), and dx_set_ikey().
static struct iam_entry* iam_entry_shift (struct iam_path * p, struct iam_entry * entry, int shift) [static, read]
Definition at line 726 of file osd_iam.h.
References iam_entry_size().
Referenced by iam_check_fast(), iam_check_full_path(), iam_find_position(), iam_htree_advance(), iam_index_shrink(), iam_insert_key(), iam_lfix_root_inc(), iam_shift_entries(), lvar_root_inc(), and split_index_node().
static size_t iam_entry_size (struct iam_path * p) [inline, static]
Definition at line 721 of file osd_iam.h.
References iam_path_descr(), iam_descr::id_ikey_size, and iam_descr::id_ptr_size.
Referenced by iam_entry_diff(), iam_entry_shift(), iam_shift_entries(), and split_index_node().
void iam_format_register (struct iam_format * fmt)
Definition at line 166 of file osd_iam.c.
References iam_format::if_linkage, and list_add().
Referenced by iam_lfix_format_init(), and iam_lvar_format_init().
static int iam_frame_is_locked (struct iam_path * path, const struct iam_frame * frame) [inline, static]
Definition at line 953 of file osd_iam.h.
References iam_frame::curidx, dynlock_is_locked(), iam_container::ic_tree_lock, and iam_path::ip_container.
Referenced by iam_insert_key(), lvar_root_inc(), and split_index_node().
void iam_htree_format_init (void)
static struct iam_ikey* iam_ikey_at (struct iam_path * p, struct iam_entry * entry) [static, read]
Definition at line 741 of file osd_iam.h.
Referenced by iam_check_fast(), iam_find_position(), iam_lfix_root_inc(), and lvar_root_inc().
static int iam_ikeycmp (const struct iam_container * c, const struct iam_ikey * k1, const struct iam_ikey * k2) [inline, static]
Definition at line 769 of file osd_iam.h.
References iam_container::ic_descr, iam_operations::id_ikeycmp, and iam_descr::id_ops.
Referenced by iam_check_fast(), iam_find_position(), and it_ikeycmp().
static void iam_ikeycpy (const struct iam_container * c, struct iam_ikey * k1, const struct iam_ikey * k2) [inline, static]
Definition at line 715 of file osd_iam.h.
References iam_container::ic_descr, and iam_descr::id_ikey_size.
Referenced by dx_set_ikey(), and iam_ikeycpy0().
static void iam_ikeycpy0 (const struct iam_container * c, struct iam_ikey * k1, const struct iam_ikey * k2) [inline, static]
Definition at line 762 of file osd_iam.h.
References iam_ikeycpy().
int iam_index_next (struct iam_container * c, struct iam_path * p)
Definition at line 1406 of file osd_iam.c.
References __iam_path_lookup(), assert_corr, CERROR, do_corr, DX_MAX_TREE_HEIGHT, iam_check_full_path(), iam_index_advance(), iam_index_lock(), iam_path_release(), iam_unlock_array(), iam_container::ic_object, iam_path::ip_frame, and iam_frame::leaf.
Referenced by iam_it_next().
int iam_insert (handle_t * handle, struct iam_container * c, const struct iam_key * k, const struct iam_rec * r, struct iam_path_descr * pd)
Definition at line 2608 of file osd_iam.c.
References iam_it_fini(), iam_it_get_exact(), iam_it_init(), iam_it_put(), iam_it_rec_insert(), and IAM_IT_WRITE.
void iam_insert_key (struct iam_path * path, struct iam_frame * frame, const struct iam_ikey * key, iam_ptr_t ptr)
Definition at line 841 of file osd_iam.c.
References assert_corr, assert_inv, iam_frame::at, dx_get_count(), dx_get_limit(), dx_set_block(), dx_set_count(), dx_set_ikey(), iam_frame::entries, iam_entry_shift(), and iam_frame_is_locked().
Referenced by iam_insert_key_lock().
void iam_insert_key_lock (struct iam_path * path, struct iam_frame * frame, const struct iam_ikey * key, iam_ptr_t ptr)
Definition at line 865 of file osd_iam.c.
References iam_frame::bh, iam_insert_key(), iam_lock_bh(), and iam_unlock_bh().
Referenced by iam_lfix_split(), iam_shift_entries(), and lvar_split().
struct iam_path_descr* iam_ipd_alloc (void * area, int keysize) [read]
Definition at line 342 of file osd_iam.c.
References ARRAY_SIZE, and iam_path_descr::ipd_key_scratch.
Referenced by iam_lfix_ipd_alloc(), and lvar_ipd_alloc().
void iam_ipd_free (struct iam_path_descr * ipd)
Definition at line 355 of file osd_iam.c.
void iam_it_dup (struct iam_iterator * dst, const struct iam_iterator * src)
Definition at line 1245 of file osd_iam.c.
References assert_corr, ergo, IAM_IT_ATTACHED, iam_it_container(), iam_it_key_get(), iam_it_rec_get(), iam_iterator::ii_flags, iam_iterator::ii_state, and it_state().
void iam_it_fini (struct iam_iterator * it)
Definition at line 733 of file osd_iam.c.
References assert_corr, IAM_IT_DETACHED, iam_path_fini(), iam_iterator::ii_path, and it_state().
Referenced by iam_delete(), iam_insert(), iam_it_get(), iam_lookup(), iam_update(), osd_index_iam_lookup(), osd_it_iam_fini(), and osd_oi_iam_lookup().
int iam_it_get (struct iam_iterator * it, const struct iam_key * k)
Definition at line 1169 of file osd_iam.c.
References __iam_it_get(), assert_corr, ergo, IAM_IT_ATTACHED, iam_it_collision(), IAM_IT_DETACHED, iam_it_fini(), iam_it_put(), IAM_LOOKUP_LAST, iam_iterator::ii_path, iam_path::ip_ikey_target, iam_path::ip_key_target, it_keycmp(), and it_state().
Referenced by iam_it_get_at(), iam_it_get_exact(), osd_index_iam_lookup(), osd_it_iam_get(), and osd_oi_iam_lookup().
int iam_it_get_at (struct iam_iterator * it, const struct iam_key * k)
Definition at line 1219 of file osd_iam.c.
References assert_corr, ergo, IAM_IT_ATTACHED, IAM_IT_DETACHED, iam_it_get(), iam_it_next(), IAM_IT_SKEWED, IAM_IT_WRITE, iam_iterator::ii_flags, and it_state().
int iam_it_init (struct iam_iterator * it, struct iam_container * c, __u32 flags, struct iam_path_descr * pd)
Definition at line 718 of file osd_iam.c.
References IAM_IT_DETACHED, iam_path_init(), iam_iterator::ii_flags, iam_iterator::ii_path, and iam_iterator::ii_state.
Referenced by iam_delete(), iam_insert(), iam_lookup(), iam_update(), osd_index_iam_lookup(), osd_it_iam_init(), and osd_oi_iam_lookup().
struct iam_key* iam_it_key_get (const struct iam_iterator * it) [read]
Definition at line 1623 of file osd_iam.c.
References assert_corr, IAM_IT_ATTACHED, IAM_IT_SKEWED, iam_leaf_key(), iam_iterator::ii_path, iam_path::ip_leaf, it_at_rec(), and it_state().
Referenced by iam_it_dup(), osd_it_iam_key(), and osd_it_iam_rec().
int iam_it_key_size (const struct iam_iterator * it)
Definition at line 1637 of file osd_iam.c.
References assert_corr, IAM_IT_ATTACHED, IAM_IT_SKEWED, iam_leaf_key_size(), iam_iterator::ii_path, iam_path::ip_leaf, it_at_rec(), and it_state().
Referenced by osd_it_iam_key_size(), and osd_it_iam_rec().
int iam_it_load (struct iam_iterator * it, iam_pos_t pos)
Definition at line 2505 of file osd_iam.c.
References assert_corr, iam_it_container(), IAM_IT_DETACHED, iam_it_iget(), IAM_IT_MOVE, iam_iterator::ii_flags, and it_state().
Referenced by osd_it_iam_load().
int iam_it_next (struct iam_iterator * it)
Definition at line 1489 of file osd_iam.c.
References assert_corr, DLT_WRITE, do_corr, ergo, iam_index_next(), IAM_IT_ATTACHED, iam_it_container(), IAM_IT_DETACHED, iam_it_ikey_get(), iam_it_put(), IAM_IT_SKEWED, iam_leaf_at_end(), iam_leaf_fini(), iam_leaf_is_locked(), iam_leaf_load(), iam_leaf_next(), iam_leaf_start(), iam_lock_htree(), iam_path_ikey(), iam_iterator::ii_path, iam_iterator::ii_state, iam_leaf::il_lock, iam_path::ip_frame, iam_path::ip_leaf, it_at_rec(), it_before(), it_ikeycmp(), it_state(), and iam_frame::leaf.
void iam_it_put (struct iam_iterator * it)
Definition at line 1267 of file osd_iam.c.
References IAM_IT_DETACHED, iam_leaf_fini(), iam_iterator::ii_path, iam_iterator::ii_state, and iam_path::ip_leaf.
Referenced by iam_delete(), iam_insert(), iam_it_get(), iam_it_next(), iam_lookup(), iam_update(), osd_index_iam_lookup(), osd_it_iam_put(), and osd_oi_iam_lookup().
int iam_it_rec_delete (handle_t * h, struct iam_iterator * it)
Definition at line 2430 of file osd_iam.c.
References assert_corr, assert_inv, iam_index_shrink(), IAM_IT_ATTACHED, IAM_IT_DETACHED, IAM_IT_MOVE, iam_it_next(), IAM_IT_WRITE, iam_leaf_at_end(), iam_rec_del(), iam_recycle_leaf(), iam_txn_add(), iam_txn_dirty(), iam_iterator::ii_flags, iam_iterator::ii_path, iam_leaf::il_bh, iam_path::ip_leaf, it_at_rec(), and it_state().
Referenced by iam_delete().
struct iam_rec* iam_it_rec_get (const struct iam_iterator * it) [read]
Definition at line 1558 of file osd_iam.c.
References assert_corr, IAM_IT_ATTACHED, iam_leaf_rec(), iam_iterator::ii_path, iam_path::ip_leaf, it_at_rec(), and it_state().
Referenced by iam_it_dup(), and osd_it_iam_rec().
int iam_it_rec_insert (handle_t * h, struct iam_iterator * it, const struct iam_key * k, const struct iam_rec * r)
Definition at line 2220 of file osd_iam.c.
References assert_corr, ergo, iam_add_rec(), IAM_IT_ATTACHED, IAM_IT_SKEWED, IAM_IT_WRITE, iam_iterator::ii_flags, iam_iterator::ii_path, iam_iterator::ii_state, it_before(), it_keycmp(), and it_state().
Referenced by iam_insert().
int iam_it_rec_set (handle_t * h, struct iam_iterator * it, const struct iam_rec * r)
Definition at line 1581 of file osd_iam.c.
References assert_corr, IAM_IT_ATTACHED, iam_it_reccpy(), IAM_IT_WRITE, iam_txn_add(), iam_txn_dirty(), iam_iterator::ii_flags, iam_iterator::ii_path, iam_leaf::il_bh, iam_path::ip_leaf, it_at_rec(), and it_state().
Referenced by iam_update().
iam_pos_t iam_it_store (const struct iam_iterator * it)
Definition at line 2484 of file osd_iam.c.
References assert_corr, IAM_IT_ATTACHED, iam_it_container(), iam_it_ikey_get(), it_at_rec(), and it_state().
Referenced by osd_it_iam_rec(), and osd_it_iam_store().
int iam_leaf_at_end (const struct iam_leaf * l)
Definition at line 540 of file osd_iam.c.
References iam_leaf_operations::at_end, and iam_leaf_ops().
Referenced by iam_it_next(), iam_it_rec_delete(), iam_lfix_rec_add(), and it_at_rec().
int iam_leaf_can_add (const struct iam_leaf * l, const struct iam_key * k, const struct iam_rec * r)
Definition at line 556 of file osd_iam.c.
References iam_leaf_operations::can_add, and iam_leaf_ops().
Referenced by iam_add_rec(), and iam_lfix_rec_add().
struct iam_container * iam_leaf_container (const struct iam_leaf * leaf) [static, read]
Referenced by blocksize(), iam_leaf_is_locked(), iam_leaf_unlock(), iam_lfix_init(), iam_lfix_key_cmp(), iam_lfix_key_eq(), iam_lfix_lookup(), iam_lfix_rec_add(), iam_lfix_rec_eq(), iam_new_leaf(), leaf_count_limit(), lvar_init(), lvar_key_cmp(), lvar_lookup(), and lvar_rec_add().
struct iam_descr * iam_leaf_descr (const struct iam_leaf * leaf) [static, read]
Referenced by iam_lfix_entry_size(), iam_lfix_key_set(), iam_lfix_key_size(), iam_lfix_rec(), iam_lfix_rec_get(), iam_lfix_rec_set(), and l_print().
static int iam_leaf_is_locked (const struct iam_leaf * leaf) [inline, static]
Definition at line 942 of file osd_iam.h.
References dynlock_is_locked(), iam_leaf_container(), and iam_leaf::il_curidx.
Referenced by iam_it_next(), lvar_at_end(), lvar_can_add(), lvar_key_set(), lvar_next(), lvar_rec_add(), lvar_rec_del(), lvar_rec_get(), lvar_rec_set(), and lvar_split().
void iam_leaf_next (struct iam_leaf * folio)
Definition at line 524 of file osd_iam.c.
References iam_leaf_ops(), and iam_leaf_operations::next.
Referenced by iam_it_next().
struct iam_leaf_operations * iam_leaf_ops (const struct iam_leaf * leaf) [static, read]
Referenced by iam_it_reccpy(), iam_leaf_at_end(), iam_leaf_can_add(), iam_leaf_empty(), iam_leaf_fini(), iam_leaf_ikey(), iam_leaf_key(), iam_leaf_key_size(), iam_leaf_keycmp(), iam_leaf_keyeq(), iam_leaf_load(), iam_leaf_next(), iam_leaf_rec(), iam_leaf_rec_add(), iam_leaf_split(), iam_leaf_start(), iam_new_leaf(), iam_path_lookup(), iam_rec_del(), iam_reccpy(), and iam_update().
struct iam_path * iam_leaf_path (const struct iam_leaf * leaf) [static, read]
Referenced by iam_lfix_split(), iam_new_leaf(), and lvar_split().
int iam_lfix_create (struct inode * obj, int keysize, int ptrsize, int recsize, handle_t * handle)
Definition at line 850 of file osd_iam_lfix.c.
References assert_corr, GOTO, lfix_leaf(), lfix_root(), and osd_ldiskfs_append().
Referenced by osd_mk_index(), and osd_oi_index_create_one().
void iam_lfix_format_init (void)
Definition at line 716 of file osd_iam_lfix.c.
References iam_format_register().
Referenced by iam_format_guess().
static void iam_lock_bh (struct buffer_head volatile * bh) [inline, static]
Definition at line 1037 of file osd_iam.h.
References BH_DXLock, and DX_DEVAL.
Referenced by iam_check_full_path(), iam_check_path(), iam_htree_advance(), iam_index_shrink(), iam_insert_key_lock(), iam_install_idle_blocks(), iam_lookup_try(), iam_new_node(), iam_shift_entries(), and split_index_node().
int iam_lookup (struct iam_container * c, const struct iam_key * k, struct iam_rec * r, struct iam_path_descr * pd)
Definition at line 2579 of file osd_iam.c.
References iam_it_fini(), iam_it_get_exact(), iam_it_init(), iam_it_put(), iam_reccpy(), iam_iterator::ii_path, and iam_path::ip_leaf.
int iam_lvar_create (struct inode * obj, int keysize, int ptrsize, int recsize, handle_t * handle)
Definition at line 1005 of file osd_iam_lvar.c.
References assert_corr, GOTO, lvar_leaf(), lvar_root(), and osd_ldiskfs_append().
Referenced by osd_mk_index(), and osd_oi_index_create_one().
void iam_lvar_format_init (void)
Definition at line 1097 of file osd_iam_lvar.c.
References iam_format_register().
Referenced by iam_format_guess().
int iam_node_read (struct iam_container * c, iam_ptr_t ptr, handle_t * handle, struct buffer_head ** bh)
Definition at line 359 of file osd_iam.c.
References iam_container::ic_descr, iam_container::ic_object, iam_container::ic_root_bh, iam_descr::id_ops, and iam_operations::id_root_ptr.
Referenced by iam_lfix_guess(), and lvar_guess().
void iam_path_compat_fini (struct iam_path_compat * path)
Definition at line 334 of file osd_iam.c.
References iam_path_fini(), and iam_path_compat::ipc_path.
void iam_path_compat_init (struct iam_path_compat * path, struct inode * inode)
Definition at line 322 of file osd_iam.c.
References ARRAY_SIZE, iam_path_init(), iam_path_compat::ipc_container, iam_path_compat::ipc_descr, iam_path_compat::ipc_hinfo, iam_path_compat::ipc_hinfo_area, iam_path_compat::ipc_path, iam_path_compat::ipc_scratch, and iam_path_descr::ipd_key_scratch.
static struct iam_descr* iam_path_descr (const struct iam_path * p) [static, read]
Definition at line 705 of file osd_iam.h.
References iam_container::ic_descr, and iam_path::ip_container.
Referenced by dx_get_block(), dx_get_entries(), dx_get_ikey(), dx_index_is_compat(), dx_node_limit(), dx_root_limit(), dx_set_block(), iam_entry_size(), iam_htree_advance(), iam_leaf_load(), iam_lfix_root_inc(), iam_lookup_try(), lvar_root_inc(), and split_index_node().
void iam_path_fini (struct iam_path * path)
Definition at line 315 of file osd_iam.c.
References iam_leaf_fini(), iam_path_release(), and iam_path::ip_leaf.
Referenced by __iam_path_lookup(), iam_add_rec(), iam_it_fini(), iam_lookup_lock(), and iam_path_compat_fini().
static struct iam_ikey* iam_path_ikey (const struct iam_path * path, int nr) [static, read]
Definition at line 935 of file osd_iam.h.
References ARRAY_SIZE, iam_path::ip_data, iam_path_descr::ipd_key_scratch, and LASSERT.
Referenced by iam_it_next(), iam_shift_entries(), it_ikeycmp(), and lvar_node_load().
void iam_path_init (struct iam_path * path, struct iam_container * c, struct iam_path_descr * pd)
Definition at line 290 of file osd_iam.c.
References iam_leaf::il_path, iam_path::ip_container, iam_path::ip_data, iam_path::ip_frame, iam_path::ip_frames, and iam_path::ip_leaf.
Referenced by iam_it_init(), and iam_path_compat_init().
static struct inode* iam_path_obj (struct iam_path * p) [static, read]
Definition at line 710 of file osd_iam.h.
References iam_container::ic_object, and iam_path::ip_container.
Referenced by dx_node_limit(), dx_root_limit(), iam_index_advance(), iam_txn_add(), iam_txn_dirty(), and split_index_node().
void iam_path_release (struct iam_path * path)
Definition at line 302 of file osd_iam.c.
References ARRAY_SIZE, iam_frame::at_shifted, iam_frame::bh, and iam_path::ip_frames.
Referenced by iam_index_next(), and iam_path_fini().
int iam_read_leaf (struct iam_path * p)
static void iam_reccpy (const struct iam_leaf * leaf, struct iam_rec * rec_dst) [inline, static]
Definition at line 807 of file osd_iam.h.
References iam_leaf_ops(), and iam_leaf_operations::rec_get.
Referenced by iam_lookup(), osd_index_iam_lookup(), osd_it_iam_rec(), and osd_oi_iam_lookup().
int iam_root_limit (int rootgap, int blocksize, int size)
Definition at line 2680 of file osd_iam.c.
Referenced by lfix_root(), and lvar_root().
int iam_uapi_ioctl (struct inode * inode, struct file * filp, unsigned int cmd, unsigned long arg)
static void iam_unlock_bh (struct buffer_head * bh) [inline, static]
Definition at line 1049 of file osd_iam.h.
References BH_DXLock.
Referenced by iam_check_full_path(), iam_check_path(), iam_htree_advance(), iam_index_shrink(), iam_insert_key_lock(), iam_install_idle_blocks(), iam_lookup_try(), iam_new_node(), iam_shift_entries(), and split_index_node().
int iam_update (handle_t * h, struct iam_container * c, const struct iam_key * k, const struct iam_rec * r, struct iam_path_descr * pd)
Definition at line 2633 of file osd_iam.c.
References iam_it_fini(), iam_it_get_exact(), iam_it_init(), iam_it_put(), iam_it_rec_set(), IAM_IT_WRITE, iam_leaf_ops(), iam_iterator::ii_path, iam_path::ip_leaf, and iam_leaf_operations::rec_eq.
Referenced by osd_attr_set(), and osd_oi_iam_refresh().
int ldiskfs_htree_next_block (struct inode * dir, __u32 hash, struct iam_path * path, __u32 * start_hash)
void ldiskfs_iam_release (struct file * filp, struct inode * inode)
struct ldiskfs_dir_entry_2* move_entries (struct inode * dir, struct ldiskfs_dx_hash_info * hinfo, struct buffer_head ** bh1, struct buffer_head ** bh2, __u32 * delim_hash) [read]
struct ldiskfs_dir_entry_2* split_entry (struct inode * dir, struct ldiskfs_dir_entry_2 * de, unsigned long ino, mode_t mode, const char * name, int namelen) [read]
int split_index_node (handle_t * handle, struct iam_path * path, struct dynlock_handle ** lh)
Definition at line 1886 of file osd_iam.c.
References ARRAY_SIZE, assert_corr, assert_inv, iam_frame::at, iam_frame::bh, cleanup(), iam_frame::curidx, dir, DLT_WRITE, do_corr, dx_get_count(), dx_get_entries(), dx_get_limit(), dx_index_is_compat(), DX_MAX_TREE_HEIGHT, dx_node_limit(), dx_root_limit(), dx_set_block(), dx_set_limit(), dxtrace, iam_frame::entries, iam_check_full_path(), iam_entry_diff(), iam_entry_shift(), iam_entry_size(), iam_frame_is_locked(), iam_lock_bh(), iam_lock_htree(), iam_new_node(), iam_path_descr(), iam_path_obj(), iam_shift_entries(), iam_unlock_array(), iam_unlock_bh(), iam_operations::id_node_init, iam_descr::id_ops, iam_operations::id_root_inc, iam_path::ip_container, iam_path::ip_frame, iam_path::ip_frames, printk, and swap.
Referenced by iam_add_rec().
Variable Documentation
struct iam_descr iam_htree_compat_param
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.