Lustre: lustre/osd-ldiskfs/osd_iam.c File Reference
lustre/osd-ldiskfs/osd_iam.c File Reference
#include <linux/module.h>
#include <linux/fs.h>
#include <linux/pagemap.h>
#include <linux/time.h>
#include <linux/fcntl.h>
#include <linux/stat.h>
#include <linux/string.h>
#include <linux/quotaops.h>
#include <linux/buffer_head.h>
#include <ldiskfs/ldiskfs.h>
#include <ldiskfs/xattr.h>
#include "osd_internal.h"
#include <ldiskfs/acl.h>
Functions
void iam_format_register (struct iam_format *fmt)
static struct buffer_head * iam_load_idle_blocks (struct iam_container *c, iam_ptr_t blk)
static int iam_format_guess (struct iam_container *c)
int iam_container_init (struct iam_container *c, struct iam_descr *descr, struct inode *inode)
int iam_container_setup (struct iam_container *c)
void iam_container_fini (struct iam_container *c)
void iam_path_init (struct iam_path *path, struct iam_container *c, struct iam_path_descr *pd)
static void iam_leaf_fini (struct iam_leaf *leaf)
void iam_path_release (struct iam_path *path)
void iam_path_fini (struct iam_path *path)
void iam_path_compat_init (struct iam_path_compat *path, struct inode *inode)
void iam_path_compat_fini (struct iam_path_compat *path)
struct iam_path_descr * iam_ipd_alloc (void *area, int keysize)
void iam_ipd_free (struct iam_path_descr *ipd)
int iam_node_read (struct iam_container *c, iam_ptr_t ptr, handle_t *h, struct buffer_head **bh)
static struct iam_rec * iam_leaf_rec (const struct iam_leaf *leaf)
static struct iam_key * iam_leaf_key (const struct iam_leaf *leaf)
static int iam_leaf_key_size (const struct iam_leaf *leaf)
static struct iam_ikey * iam_leaf_ikey (const struct iam_leaf *leaf, struct iam_ikey *key)
static int iam_leaf_keycmp (const struct iam_leaf *leaf, const struct iam_key *key)
static int iam_leaf_keyeq (const struct iam_leaf *leaf, const struct iam_key *key)
static int iam_leaf_load (struct iam_path *path)
static void iam_unlock_htree (struct iam_container *ic, struct dynlock_handle *lh)
static void iam_leaf_unlock (struct iam_leaf *leaf)
static void iam_leaf_start (struct iam_leaf *folio)
void iam_leaf_next (struct iam_leaf *folio)
static void iam_leaf_rec_add (struct iam_leaf *leaf, const struct iam_key *key, const struct iam_rec *rec)
static void iam_rec_del (struct iam_leaf *leaf, int shift)
int iam_leaf_at_end (const struct iam_leaf *leaf)
static void iam_leaf_split (struct iam_leaf *l, struct buffer_head **bh, iam_ptr_t nr)
static int iam_leaf_empty (struct iam_leaf *l)
int iam_leaf_can_add (const struct iam_leaf *l, const struct iam_key *k, const struct iam_rec *r)
static int iam_txn_dirty (handle_t *handle, struct iam_path *path, struct buffer_head *bh)
static int iam_txn_add (handle_t *handle, struct iam_path *path, struct buffer_head *bh)
static enum iam_it_state it_state (const struct iam_iterator *it)
static struct iam_container * iam_it_container (const struct iam_iterator *it)
static int it_keycmp (const struct iam_iterator *it, const struct iam_key *k)
static int it_keyeq (const struct iam_iterator *it, const struct iam_key *k)
static int it_ikeycmp (const struct iam_iterator *it, const struct iam_ikey *ik)
static int it_at_rec (const struct iam_iterator *it)
static int it_before (const struct iam_iterator *it)
static int iam_it_get_exact (struct iam_iterator *it, const struct iam_key *k)
void iam_container_write_lock (struct iam_container *ic)
void iam_container_write_unlock (struct iam_container *ic)
void iam_container_read_lock (struct iam_container *ic)
void iam_container_read_unlock (struct iam_container *ic)
int iam_it_init (struct iam_iterator *it, struct iam_container *c, __u32 flags, struct iam_path_descr *pd)
void iam_it_fini (struct iam_iterator *it)
static struct dynlock_handle * iam_lock_htree (struct iam_container *ic, unsigned long value, enum dynlock_type lt)
static int iam_index_lock (struct iam_path *path, struct dynlock_handle **lh)
static int iam_check_fast (struct iam_path *path, struct iam_frame *frame)
int dx_index_is_compat (struct iam_path *path)
static struct iam_entry * iam_find_position (struct iam_path *path, struct iam_frame *frame)
static iam_ptr_t iam_find_ptr (struct iam_path *path, struct iam_frame *frame)
void iam_insert_key (struct iam_path *path, struct iam_frame *frame, const struct iam_ikey *key, iam_ptr_t ptr)
void iam_insert_key_lock (struct iam_path *path, struct iam_frame *frame, const struct iam_ikey *key, iam_ptr_t ptr)
static int iam_check_path (struct iam_path *path, struct iam_frame *frame)
static int iam_lookup_try (struct iam_path *path)
static int __iam_path_lookup (struct iam_path *path)
static int iam_check_full_path (struct iam_path *path, int search)
static int iam_lookup_lock (struct iam_path *path, struct dynlock_handle **dl, enum dynlock_type lt)
static int iam_path_lookup (struct iam_path *path, int index)
static int __iam_it_get (struct iam_iterator *it, int index)
static int iam_it_collision (struct iam_iterator *it)
int iam_it_get (struct iam_iterator *it, const struct iam_key *k)
static int iam_it_iget (struct iam_iterator *it, const struct iam_ikey *k)
int iam_it_get_at (struct iam_iterator *it, const struct iam_key *k)
void iam_it_dup (struct iam_iterator *dst, const struct iam_iterator *src)
void iam_it_put (struct iam_iterator *it)
static struct iam_ikey * iam_it_ikey_get (const struct iam_iterator *it, struct iam_ikey *ikey)
static int iam_htree_advance (struct inode *dir, __u32 hash, struct iam_path *path, __u32 *start_hash, int compat)
static int iam_index_advance (struct iam_path *path)
static void iam_unlock_array (struct iam_container *ic, struct dynlock_handle **lh)
int iam_index_next (struct iam_container *c, struct iam_path *path)
int iam_it_next (struct iam_iterator *it)
struct iam_rec * iam_it_rec_get (const struct iam_iterator *it)
static void iam_it_reccpy (struct iam_iterator *it, const struct iam_rec *r)
int iam_it_rec_set (handle_t *h, struct iam_iterator *it, const struct iam_rec *r)
struct iam_key * iam_it_key_get (const struct iam_iterator *it)
int iam_it_key_size (const struct iam_iterator *it)
static struct buffer_head * iam_new_node (handle_t *h, struct iam_container *c, iam_ptr_t *b, int *e)
static int iam_new_leaf (handle_t *handle, struct iam_leaf *leaf)
static void dx_set_limit (struct iam_entry *entries, unsigned value)
static int iam_shift_entries (struct iam_path *path, struct iam_frame *frame, unsigned count, struct iam_entry *entries, struct iam_entry *entries2, u32 newblock)
int split_index_node (handle_t *handle, struct iam_path *path, struct dynlock_handle **lh)
static int iam_add_rec (handle_t *handle, struct iam_iterator *it, struct iam_path *path, const struct iam_key *k, const struct iam_rec *r)
int iam_it_rec_insert (handle_t *h, struct iam_iterator *it, const struct iam_key *k, const struct iam_rec *r)
static int iam_idle_blocks_limit (struct inode *inode)
static iam_ptr_t iam_index_shrink (handle_t *h, struct iam_path *p, struct iam_leaf *l, struct buffer_head **bh)
static int iam_install_idle_blocks (handle_t *h, struct iam_path *p, struct buffer_head *bh, __u32 *idle_blocks, iam_ptr_t blk)
static void iam_recycle_leaf (handle_t *h, struct iam_path *p, struct buffer_head *bh, iam_ptr_t blk)
int iam_it_rec_delete (handle_t *h, struct iam_iterator *it)
iam_pos_t iam_it_store (const struct iam_iterator *it)
int iam_it_load (struct iam_iterator *it, iam_pos_t pos)
static int ptr_inside (void *base, size_t size, void *ptr)
static int iam_frame_invariant (struct iam_frame *f)
static int iam_leaf_invariant (struct iam_leaf *l)
static int iam_path_invariant (struct iam_path *p)
int iam_it_invariant (struct iam_iterator *it)
int iam_lookup (struct iam_container *c, const struct iam_key *k, struct iam_rec *r, struct iam_path_descr *pd)
int iam_insert (handle_t *h, struct iam_container *c, const struct iam_key *k, const struct iam_rec *r, struct iam_path_descr *pd)
int iam_update (handle_t *h, struct iam_container *c, const struct iam_key *k, const struct iam_rec *r, struct iam_path_descr *pd)
int iam_delete (handle_t *h, struct iam_container *c, const struct iam_key *k, struct iam_path_descr *pd)
int iam_root_limit (int rootgap, int blocksize, int size)
Variables
static struct list_head iam_formats = LIST_HEAD_INIT(iam_formats)
Function Documentation
static int __iam_it_get (struct iam_iterator * it, int index) [static]
Definition at line 1101 of file osd_iam.c.
References assert, assert_corr, IAM_IT_ATTACHED, IAM_IT_DETACHED, IAM_IT_SKEWED, IAM_LOOKUP_BEFORE, IAM_LOOKUP_EMPTY, IAM_LOOKUP_EXACT, IAM_LOOKUP_LAST, IAM_LOOKUP_OK, iam_path_lookup(), iam_iterator::ii_path, iam_iterator::ii_state, and it_state().
Referenced by iam_it_get(), and iam_it_iget().
static int __iam_path_lookup (struct iam_path * path) [static]
Definition at line 953 of file osd_iam.c.
References assert, iam_frame::bh, do_corr, DX_MAX_TREE_HEIGHT, iam_lookup_try(), iam_path_fini(), and iam_path::ip_frames.
Referenced by iam_index_next(), and iam_lookup_lock().
int dx_index_is_compat (struct iam_path * path)
Definition at line 798 of file osd_iam.c.
References iam_path_descr().
Referenced by iam_find_position(), iam_shift_entries(), and split_index_node().
static void dx_set_limit (struct iam_entry * entries, unsigned value) [inline, static]
Definition at line 1827 of file osd_iam.c.
References cpu_to_le16.
Referenced by iam_shift_entries(), and split_index_node().
static int iam_add_rec (handle_t * handle, struct iam_iterator * it, struct iam_path * path, const struct iam_key * k, const struct iam_rec * r) [static]
Definition at line 2148 of file osd_iam.c.
References assert_corr, assert_inv, iam_frame::bh, do_corr, IAM_IT_DETACHED, iam_it_get_exact(), iam_leaf_can_add(), iam_leaf_rec_add(), iam_new_leaf(), iam_path_fini(), iam_txn_add(), iam_txn_dirty(), iam_unlock_htree(), iam_iterator::ii_state, iam_leaf::il_bh, iam_path::ip_container, iam_path::ip_frame, iam_path::ip_leaf, and split_index_node().
Referenced by iam_it_rec_insert().
static int iam_check_fast (struct iam_path * path, struct iam_frame * frame) [static]
Definition at line 766 of file osd_iam.c.
References iam_frame::at, dx_get_block(), dx_get_count(), iam_frame::entries, iam_entry_shift(), iam_ikey_at(), iam_ikeycmp(), iam_path::ip_container, iam_path::ip_ikey_target, iam_frame::leaf, and unlikely.
Referenced by iam_check_full_path(), and iam_check_path().
static int iam_check_full_path (struct iam_path * path, int search) [static]
Definition at line 974 of file osd_iam.c.
References iam_frame::at, iam_frame::bh, do_corr, DX_DEVAL, dx_get_block(), dx_get_count(), iam_frame::entries, iam_check_fast(), iam_entry_shift(), iam_find_position(), iam_lock_bh(), iam_unlock_bh(), iam_path::ip_frames, and iam_frame::leaf.
Referenced by iam_index_next(), iam_lookup_lock(), and split_index_node().
static int iam_check_path (struct iam_path * path, struct iam_frame * frame) [static]
Definition at line 875 of file osd_iam.c.
References iam_frame::bh, DX_DEVAL, iam_check_fast(), iam_find_ptr(), iam_lock_bh(), iam_unlock_bh(), and iam_frame::leaf.
Referenced by iam_lookup_try().
void iam_container_fini (struct iam_container * c)
Definition at line 282 of file osd_iam.c.
References iam_container::ic_idle_bh, and iam_container::ic_root_bh.
Referenced by osd_iam_container_init(), osd_index_fini(), osd_oi_open(), and osd_oi_table_put().
int iam_container_init (struct iam_container * c, struct iam_descr * descr, struct inode * inode)
Definition at line 259 of file osd_iam.c.
References dynlock_init(), iam_container::ic_descr, iam_container::ic_idle_mutex, iam_container::ic_object, iam_container::ic_sem, and iam_container::ic_tree_lock.
Referenced by osd_iam_container_init(), and osd_oi_open().
void iam_container_read_lock (struct iam_container * ic)
Definition at line 703 of file osd_iam.c.
References iam_container::ic_sem.
void iam_container_read_unlock (struct iam_container * ic)
Definition at line 708 of file osd_iam.c.
References iam_container::ic_sem.
int iam_container_setup (struct iam_container * c)
Definition at line 274 of file osd_iam.c.
References iam_format_guess().
Referenced by osd_iam_container_init(), and osd_oi_open().
void iam_container_write_lock (struct iam_container * ic)
Definition at line 693 of file osd_iam.c.
References iam_container::ic_sem.
void iam_container_write_unlock (struct iam_container * ic)
Definition at line 698 of file osd_iam.c.
References iam_container::ic_sem.
int iam_delete (handle_t * h, struct iam_container * c, const struct iam_key * k, struct iam_path_descr * pd)
Definition at line 2664 of file osd_iam.c.
References iam_it_fini(), iam_it_get_exact(), iam_it_init(), iam_it_put(), iam_it_rec_delete(), and IAM_IT_WRITE.
static struct iam_entry* iam_find_position (struct iam_path * path, struct iam_frame * frame) [static, read]
Definition at line 810 of file osd_iam.c.
References assert_corr, dx_get_count(), dx_get_limit(), dx_index_is_compat(), iam_frame::entries, iam_entry_diff(), iam_entry_shift(), iam_ikey_at(), iam_ikeycmp(), iam_path::ip_container, and iam_path::ip_ikey_target.
Referenced by iam_check_full_path(), iam_find_ptr(), iam_index_shrink(), and iam_lookup_try().
static iam_ptr_t iam_find_ptr (struct iam_path * path, struct iam_frame * frame) [static]
Definition at line 836 of file osd_iam.c.
References dx_get_block(), and iam_find_position().
Referenced by iam_check_path().
static int iam_format_guess (struct iam_container * c) [static]
Definition at line 210 of file osd_iam.c.
References iam_lfix_format_init(), iam_load_idle_blocks(), iam_lvar_format_init(), iam_container::ic_descr, iam_container::ic_idle_bh, iam_container::ic_idle_mutex, iam_container::ic_root_bh, iam_descr::id_root_gap, iam_format::if_guess, iam_format::if_linkage, LASSERT, le32_to_cpu, and list_for_each_entry.
Referenced by iam_container_setup().
void iam_format_register (struct iam_format * fmt)
Definition at line 166 of file osd_iam.c.
References iam_format::if_linkage, and list_add().
Referenced by iam_lfix_format_init(), and iam_lvar_format_init().
static int iam_frame_invariant (struct iam_frame * f) [static]
Definition at line 2522 of file osd_iam.c.
References iam_frame::at, iam_frame::bh, iam_frame::entries, and ptr_inside().
Referenced by iam_path_invariant().
static int iam_htree_advance (struct inode * dir, __u32 hash, struct iam_path * path, __u32 * start_hash, int compat) [static]
Definition at line 1296 of file osd_iam.c.
References assert_corr, assert_inv, iam_frame::at, iam_frame::at_shifted, iam_frame::bh, iam_frame::curidx, do_corr, dx_get_block(), dx_get_count(), dx_get_ikey(), dx_node_get_entries(), iam_frame::entries, iam_entry_shift(), iam_lock_bh(), iam_path_descr(), iam_unlock_bh(), iam_descr::id_ops, iam_path::ip_container, iam_path::ip_frame, iam_path::ip_frames, and iam_frame::leaf.
Referenced by iam_index_advance().
static int iam_idle_blocks_limit (struct inode * inode) [inline, static]
Definition at line 2243 of file osd_iam.c.
Referenced by iam_recycle_leaf().
static int iam_index_advance (struct iam_path * path) [inline, static]
Definition at line 1385 of file osd_iam.c.
References iam_htree_advance(), and iam_path_obj().
Referenced by iam_index_next().
static int iam_index_lock (struct iam_path * path, struct dynlock_handle ** lh) [static]
Definition at line 750 of file osd_iam.c.
References iam_frame::curidx, DLT_READ, do_corr, iam_lock_htree(), iam_path::ip_container, iam_path::ip_frame, and iam_path::ip_frames.
Referenced by iam_index_next().
int iam_index_next (struct iam_container * c, struct iam_path * path)
Definition at line 1406 of file osd_iam.c.
References __iam_path_lookup(), assert_corr, CERROR, do_corr, DX_MAX_TREE_HEIGHT, iam_check_full_path(), iam_index_advance(), iam_index_lock(), iam_path_release(), iam_unlock_array(), iam_container::ic_object, iam_path::ip_frame, and iam_frame::leaf.
Referenced by iam_it_next().
static iam_ptr_t iam_index_shrink (handle_t * h, struct iam_path * p, struct iam_leaf * l, struct buffer_head ** bh) [static]
Definition at line 2252 of file osd_iam.c.
References iam_frame::at, iam_frame::at_shifted, iam_frame::bh, iam_frame::curidx, CWARN, DLT_WRITE, dx_get_block(), dx_get_count(), dx_set_count(), iam_frame::entries, iam_entry_shift(), iam_find_position(), iam_leaf_empty(), iam_lock_bh(), iam_lock_htree(), iam_txn_add(), iam_txn_dirty(), iam_unlock_bh(), iam_unlock_htree(), iam_container::ic_idle_failed, iam_container::ic_object, iam_leaf::il_bh, iam_path::ip_container, iam_path::ip_frame, iam_frame::leaf, and unlikely.
Referenced by iam_it_rec_delete().
int iam_insert (handle_t * h, struct iam_container * c, const struct iam_key * k, const struct iam_rec * r, struct iam_path_descr * pd)
Definition at line 2608 of file osd_iam.c.
References iam_it_fini(), iam_it_get_exact(), iam_it_init(), iam_it_put(), iam_it_rec_insert(), and IAM_IT_WRITE.
void iam_insert_key (struct iam_path * path, struct iam_frame * frame, const struct iam_ikey * key, iam_ptr_t ptr)
Definition at line 841 of file osd_iam.c.
References assert_corr, assert_inv, iam_frame::at, dx_get_count(), dx_get_limit(), dx_set_block(), dx_set_count(), dx_set_ikey(), iam_frame::entries, iam_entry_shift(), and iam_frame_is_locked().
Referenced by iam_insert_key_lock().
void iam_insert_key_lock (struct iam_path * path, struct iam_frame * frame, const struct iam_ikey * key, iam_ptr_t ptr)
Definition at line 865 of file osd_iam.c.
References iam_frame::bh, iam_insert_key(), iam_lock_bh(), and iam_unlock_bh().
Referenced by iam_lfix_split(), iam_shift_entries(), and lvar_split().
static int iam_install_idle_blocks (handle_t * h, struct iam_path * p, struct buffer_head * bh, __u32 * idle_blocks, iam_ptr_t blk) [static]
Definition at line 2330 of file osd_iam.c.
References cpu_to_le16, cpu_to_le32, head, IAM_IDLE_HEADER_MAGIC, iam_lock_bh(), iam_txn_add(), iam_txn_dirty(), iam_unlock_bh(), iam_container::ic_idle_bh, iam_container::ic_root_bh, iam_idle_head::iih_count, iam_idle_head::iih_magic, iam_idle_head::iih_next, and iam_path::ip_container.
Referenced by iam_recycle_leaf().
struct iam_path_descr* iam_ipd_alloc (void * area, int keysize) [read]
Definition at line 342 of file osd_iam.c.
References ARRAY_SIZE, and iam_path_descr::ipd_key_scratch.
Referenced by iam_lfix_ipd_alloc(), and lvar_ipd_alloc().
void iam_ipd_free (struct iam_path_descr * ipd)
Definition at line 355 of file osd_iam.c.
static int iam_it_collision (struct iam_iterator * it) [static]
Definition at line 1141 of file osd_iam.c.
References assert, do_corr, ergo, iam_it_next(), iam_iterator::ii_path, iam_path::ip_ikey_target, iam_path::ip_key_target, it_at_rec(), it_ikeycmp(), and it_keyeq().
Referenced by iam_it_get().
static struct iam_container* iam_it_container (const struct iam_iterator * it) [static, read]
Definition at line 636 of file osd_iam.c.
References iam_iterator::ii_path, and iam_path::ip_container.
Referenced by iam_it_dup(), iam_it_load(), iam_it_next(), and iam_it_store().
void iam_it_dup (struct iam_iterator * dst, const struct iam_iterator * src)
Definition at line 1245 of file osd_iam.c.
References assert_corr, ergo, IAM_IT_ATTACHED, iam_it_container(), iam_it_key_get(), iam_it_rec_get(), iam_iterator::ii_flags, iam_iterator::ii_state, and it_state().
void iam_it_fini (struct iam_iterator * it)
Definition at line 733 of file osd_iam.c.
References assert_corr, IAM_IT_DETACHED, iam_path_fini(), iam_iterator::ii_path, and it_state().
Referenced by iam_delete(), iam_insert(), iam_it_get(), iam_lookup(), iam_update(), osd_index_iam_lookup(), osd_it_iam_fini(), and osd_oi_iam_lookup().
int iam_it_get (struct iam_iterator * it, const struct iam_key * k)
Definition at line 1169 of file osd_iam.c.
References __iam_it_get(), assert_corr, ergo, IAM_IT_ATTACHED, iam_it_collision(), IAM_IT_DETACHED, iam_it_fini(), iam_it_put(), IAM_LOOKUP_LAST, iam_iterator::ii_path, iam_path::ip_ikey_target, iam_path::ip_key_target, it_keycmp(), and it_state().
Referenced by iam_it_get_at(), iam_it_get_exact(), osd_index_iam_lookup(), osd_it_iam_get(), and osd_oi_iam_lookup().
int iam_it_get_at (struct iam_iterator * it, const struct iam_key * k)
Definition at line 1219 of file osd_iam.c.
References assert_corr, ergo, IAM_IT_ATTACHED, IAM_IT_DETACHED, iam_it_get(), iam_it_next(), IAM_IT_SKEWED, IAM_IT_WRITE, iam_iterator::ii_flags, and it_state().
static int iam_it_get_exact (struct iam_iterator * it, const struct iam_key * k) [static]
Definition at line 674 of file osd_iam.c.
References iam_it_get().
Referenced by iam_add_rec(), iam_delete(), iam_insert(), iam_lookup(), and iam_update().
static int iam_it_iget (struct iam_iterator * it, const struct iam_ikey * k) [static]
Definition at line 1200 of file osd_iam.c.
References __iam_it_get(), assert_corr, IAM_IT_DETACHED, IAM_LOOKUP_LAST, iam_iterator::ii_path, iam_path::ip_ikey_target, and it_state().
Referenced by iam_it_load().
static struct iam_ikey * iam_it_ikey_get (const struct iam_iterator * it, struct iam_ikey * ikey) [static, read]
Definition at line 1608 of file osd_iam.c.
References assert_corr, IAM_IT_ATTACHED, IAM_IT_SKEWED, iam_leaf_ikey(), iam_iterator::ii_path, iam_path::ip_leaf, it_at_rec(), and it_state().
Referenced by iam_it_next(), and iam_it_store().
int iam_it_init (struct iam_iterator * it, struct iam_container * c, __u32 flags, struct iam_path_descr * pd)
Definition at line 718 of file osd_iam.c.
References IAM_IT_DETACHED, iam_path_init(), iam_iterator::ii_flags, iam_iterator::ii_path, and iam_iterator::ii_state.
Referenced by iam_delete(), iam_insert(), iam_lookup(), iam_update(), osd_index_iam_lookup(), osd_it_iam_init(), and osd_oi_iam_lookup().
int iam_it_invariant (struct iam_iterator * it)
Definition at line 2560 of file osd_iam.c.
References equi, ergo, IAM_IT_ATTACHED, IAM_IT_DETACHED, IAM_IT_MOVE, IAM_IT_SKEWED, IAM_IT_WRITE, iam_path_invariant(), iam_iterator::ii_flags, iam_iterator::ii_path, iam_iterator::ii_state, and it_at_rec().
struct iam_key* iam_it_key_get (const struct iam_iterator * it) [read]
Definition at line 1623 of file osd_iam.c.
References assert_corr, IAM_IT_ATTACHED, IAM_IT_SKEWED, iam_leaf_key(), iam_iterator::ii_path, iam_path::ip_leaf, it_at_rec(), and it_state().
Referenced by iam_it_dup(), osd_it_iam_key(), and osd_it_iam_rec().
int iam_it_key_size (const struct iam_iterator * it)
Definition at line 1637 of file osd_iam.c.
References assert_corr, IAM_IT_ATTACHED, IAM_IT_SKEWED, iam_leaf_key_size(), iam_iterator::ii_path, iam_path::ip_leaf, it_at_rec(), and it_state().
Referenced by osd_it_iam_key_size(), and osd_it_iam_rec().
int iam_it_load (struct iam_iterator * it, iam_pos_t pos)
Definition at line 2505 of file osd_iam.c.
References assert_corr, iam_it_container(), IAM_IT_DETACHED, iam_it_iget(), IAM_IT_MOVE, iam_iterator::ii_flags, and it_state().
Referenced by osd_it_iam_load().
int iam_it_next (struct iam_iterator * it)
Definition at line 1489 of file osd_iam.c.
References assert_corr, DLT_WRITE, do_corr, ergo, iam_index_next(), IAM_IT_ATTACHED, iam_it_container(), IAM_IT_DETACHED, iam_it_ikey_get(), iam_it_put(), IAM_IT_SKEWED, iam_leaf_at_end(), iam_leaf_fini(), iam_leaf_is_locked(), iam_leaf_load(), iam_leaf_next(), iam_leaf_start(), iam_lock_htree(), iam_path_ikey(), iam_iterator::ii_path, iam_iterator::ii_state, iam_leaf::il_lock, iam_path::ip_frame, iam_path::ip_leaf, it_at_rec(), it_before(), it_ikeycmp(), it_state(), and iam_frame::leaf.
void iam_it_put (struct iam_iterator * it)
Definition at line 1267 of file osd_iam.c.
References IAM_IT_DETACHED, iam_leaf_fini(), iam_iterator::ii_path, iam_iterator::ii_state, and iam_path::ip_leaf.
Referenced by iam_delete(), iam_insert(), iam_it_get(), iam_it_next(), iam_lookup(), iam_update(), osd_index_iam_lookup(), osd_it_iam_put(), and osd_oi_iam_lookup().
int iam_it_rec_delete (handle_t * h, struct iam_iterator * it)
Definition at line 2430 of file osd_iam.c.
References assert_corr, assert_inv, iam_index_shrink(), IAM_IT_ATTACHED, IAM_IT_DETACHED, IAM_IT_MOVE, iam_it_next(), IAM_IT_WRITE, iam_leaf_at_end(), iam_rec_del(), iam_recycle_leaf(), iam_txn_add(), iam_txn_dirty(), iam_iterator::ii_flags, iam_iterator::ii_path, iam_leaf::il_bh, iam_path::ip_leaf, it_at_rec(), and it_state().
Referenced by iam_delete().
struct iam_rec* iam_it_rec_get (const struct iam_iterator * it) [read]
Definition at line 1558 of file osd_iam.c.
References assert_corr, IAM_IT_ATTACHED, iam_leaf_rec(), iam_iterator::ii_path, iam_path::ip_leaf, it_at_rec(), and it_state().
Referenced by iam_it_dup(), and osd_it_iam_rec().
int iam_it_rec_insert (handle_t * h, struct iam_iterator * it, const struct iam_key * k, const struct iam_rec * r)
Definition at line 2220 of file osd_iam.c.
References assert_corr, ergo, iam_add_rec(), IAM_IT_ATTACHED, IAM_IT_SKEWED, IAM_IT_WRITE, iam_iterator::ii_flags, iam_iterator::ii_path, iam_iterator::ii_state, it_before(), it_keycmp(), and it_state().
Referenced by iam_insert().
int iam_it_rec_set (handle_t * h, struct iam_iterator * it, const struct iam_rec * r)
Definition at line 1581 of file osd_iam.c.
References assert_corr, IAM_IT_ATTACHED, iam_it_reccpy(), IAM_IT_WRITE, iam_txn_add(), iam_txn_dirty(), iam_iterator::ii_flags, iam_iterator::ii_path, iam_leaf::il_bh, iam_path::ip_leaf, it_at_rec(), and it_state().
Referenced by iam_update().
static void iam_it_reccpy (struct iam_iterator * it, const struct iam_rec * r) [static]
Definition at line 1565 of file osd_iam.c.
References iam_leaf_ops(), iam_iterator::ii_path, iam_path::ip_leaf, and iam_leaf_operations::rec_set.
Referenced by iam_it_rec_set().
iam_pos_t iam_it_store (const struct iam_iterator * it)
Definition at line 2484 of file osd_iam.c.
References assert_corr, IAM_IT_ATTACHED, iam_it_container(), iam_it_ikey_get(), it_at_rec(), and it_state().
Referenced by osd_it_iam_rec(), and osd_it_iam_store().
int iam_leaf_at_end (const struct iam_leaf * leaf)
Definition at line 540 of file osd_iam.c.
References iam_leaf_operations::at_end, and iam_leaf_ops().
Referenced by iam_it_next(), iam_it_rec_delete(), iam_lfix_rec_add(), and it_at_rec().
int iam_leaf_can_add (const struct iam_leaf * l, const struct iam_key * k, const struct iam_rec * r)
Definition at line 556 of file osd_iam.c.
References iam_leaf_operations::can_add, and iam_leaf_ops().
Referenced by iam_add_rec(), and iam_lfix_rec_add().
static int iam_leaf_empty (struct iam_leaf * l) [inline, static]
Definition at line 551 of file osd_iam.c.
References iam_leaf_ops(), and iam_leaf_operations::leaf_empty.
Referenced by iam_index_shrink().
static void iam_leaf_fini (struct iam_leaf * leaf) [static]
Definition at line 505 of file osd_iam.c.
References assert_inv, ergo, iam_leaf_operations::fini, iam_leaf_ops(), iam_leaf_unlock(), iam_leaf::il_bh, iam_leaf::il_curidx, and iam_leaf::il_path.
Referenced by iam_it_next(), iam_it_put(), and iam_path_fini().
static struct iam_ikey* iam_leaf_ikey (const struct iam_leaf * leaf, struct iam_ikey * key) [static, read]
Definition at line 408 of file osd_iam.c.
References iam_leaf_ops(), and iam_leaf_operations::ikey.
Referenced by iam_it_ikey_get(), and it_ikeycmp().
static int iam_leaf_invariant (struct iam_leaf * l) [static]
Definition at line 2532 of file osd_iam.c.
References iam_leaf::il_at, iam_leaf::il_bh, iam_leaf::il_entries, and ptr_inside().
Referenced by iam_path_invariant().
static struct iam_key* iam_leaf_key (const struct iam_leaf * leaf) [static, read]
Definition at line 398 of file osd_iam.c.
References iam_leaf_ops(), and iam_leaf_operations::key.
Referenced by iam_it_key_get().
static int iam_leaf_key_size (const struct iam_leaf * leaf) [static]
Definition at line 403 of file osd_iam.c.
References iam_leaf_ops(), and iam_leaf_operations::key_size.
Referenced by iam_it_key_size().
static int iam_leaf_keycmp (const struct iam_leaf * leaf, const struct iam_key * key) [static]
Definition at line 414 of file osd_iam.c.
References iam_leaf_ops(), and iam_leaf_operations::key_cmp.
Referenced by it_keycmp().
static int iam_leaf_keyeq (const struct iam_leaf * leaf, const struct iam_key * key) [static]
Definition at line 420 of file osd_iam.c.
References iam_leaf_ops(), and iam_leaf_operations::key_eq.
Referenced by it_keyeq().
static int iam_leaf_load (struct iam_path * path) [static]
Definition at line 456 of file osd_iam.c.
References assert_inv, iam_frame::bh, dx_get_count(), dx_node_get_entries(), ergo, iam_leaf_ops(), iam_path_descr(), iam_operations::id_node_read, iam_descr::id_ops, iam_leaf::il_bh, iam_leaf::il_curidx, iam_leaf_operations::init, iam_path::ip_container, iam_path::ip_frame, iam_path::ip_frames, iam_path::ip_leaf, iam_frame::leaf, and printk.
Referenced by iam_it_next(), and iam_path_lookup().
void iam_leaf_next (struct iam_leaf * folio)
Definition at line 524 of file osd_iam.c.
References iam_leaf_ops(), and iam_leaf_operations::next.
Referenced by iam_it_next().
static struct iam_rec* iam_leaf_rec (const struct iam_leaf * leaf) [static, read]
Definition at line 386 of file osd_iam.c.
References iam_leaf_ops(), and iam_leaf_operations::rec.
Referenced by iam_it_rec_get().
static void iam_leaf_rec_add (struct iam_leaf * leaf, const struct iam_key * key, const struct iam_rec * rec) [static]
Definition at line 529 of file osd_iam.c.
References iam_leaf_ops(), and iam_leaf_operations::rec_add.
Referenced by iam_add_rec().
static void iam_leaf_split (struct iam_leaf * l, struct buffer_head ** bh, iam_ptr_t nr) [static]
Definition at line 545 of file osd_iam.c.
References iam_leaf_ops(), and iam_leaf_operations::split.
Referenced by iam_new_leaf().
static void iam_leaf_start (struct iam_leaf * folio) [static]
Definition at line 519 of file osd_iam.c.
References iam_leaf_ops(), and iam_leaf_operations::start.
Referenced by iam_it_next().
static void iam_leaf_unlock (struct iam_leaf * leaf) [static]
Definition at line 495 of file osd_iam.c.
References do_corr, iam_leaf_container(), iam_unlock_htree(), and iam_leaf::il_lock.
Referenced by iam_leaf_fini(), iam_new_leaf(), and iam_path_lookup().
static struct buffer_head* iam_load_idle_blocks (struct iam_container * c, iam_ptr_t blk) [static, read]
Definition at line 172 of file osd_iam.c.
References CERROR, head, IAM_IDLE_HEADER_MAGIC, iam_container::ic_idle_failed, iam_container::ic_idle_mutex, iam_container::ic_object, iam_idle_head::iih_magic, LASSERT, and le16_to_cpu.
Referenced by iam_format_guess(), and iam_new_node().
static struct dynlock_handle* iam_lock_htree (struct iam_container * ic, unsigned long value, enum dynlock_type lt) [static, read]
Definition at line 743 of file osd_iam.c.
References dynlock_lock(), and iam_container::ic_tree_lock.
Referenced by iam_index_lock(), iam_index_shrink(), iam_it_next(), iam_lookup_lock(), iam_new_leaf(), and split_index_node().
int iam_lookup (struct iam_container * c, const struct iam_key * k, struct iam_rec * r, struct iam_path_descr * pd)
Definition at line 2579 of file osd_iam.c.
References iam_it_fini(), iam_it_get_exact(), iam_it_init(), iam_it_put(), iam_reccpy(), iam_iterator::ii_path, and iam_path::ip_leaf.
static int iam_lookup_lock (struct iam_path * path, struct dynlock_handle ** dl, enum dynlock_type lt) [static]
Definition at line 1037 of file osd_iam.c.
References __iam_path_lookup(), do_corr, iam_check_full_path(), iam_lock_htree(), iam_path_fini(), iam_unlock_htree(), iam_path::ip_container, iam_path::ip_frame, and iam_frame::leaf.
Referenced by iam_path_lookup().
static int iam_lookup_try (struct iam_path * path) [static]
Definition at line 888 of file osd_iam.c.
References assert_inv, iam_frame::at, iam_frame::bh, iam_frame::curidx, do_corr, dx_get_block(), iam_check_path(), iam_find_position(), iam_lock_bh(), iam_path_descr(), iam_unlock_bh(), iam_operations::id_node_check, iam_operations::id_node_load, iam_operations::id_node_read, iam_descr::id_ops, iam_operations::id_root_ptr, iam_path::ip_container, iam_path::ip_frame, iam_path::ip_frames, LDISKFS_INVARIANT_ON, and iam_frame::leaf.
Referenced by __iam_path_lookup().
static int iam_new_leaf (handle_t * handle, struct iam_leaf * leaf) [static]
Definition at line 1775 of file osd_iam.c.
References assert_inv, DLT_WRITE, do_corr, iam_leaf_container(), iam_leaf_ops(), iam_leaf_path(), iam_leaf_split(), iam_leaf_unlock(), iam_lock_htree(), iam_new_node(), iam_txn_dirty(), iam_unlock_htree(), iam_container::ic_object, iam_leaf::il_bh, iam_leaf::il_lock, iam_leaf::il_path, iam_leaf_operations::init_new, iam_path::ip_container, iam_path::ip_frame, and iam_frame::leaf.
Referenced by iam_add_rec().
static struct buffer_head* iam_new_node (handle_t * h, struct iam_container * c, iam_ptr_t * b, int * e) [static, read]
Definition at line 1646 of file osd_iam.c.
References cpu_to_le16, cpu_to_le32, head, iam_load_idle_blocks(), iam_lock_bh(), iam_unlock_bh(), iam_container::ic_descr, iam_container::ic_idle_bh, iam_container::ic_idle_mutex, iam_container::ic_object, iam_container::ic_root_bh, iam_descr::id_root_gap, iam_idle_head::iih_blks, iam_idle_head::iih_count, iam_idle_head::iih_next, le16_to_cpu, le32_to_cpu, osd_ldiskfs_append(), and unlikely.
Referenced by iam_new_leaf(), and split_index_node().
int iam_node_read (struct iam_container * c, iam_ptr_t ptr, handle_t * h, struct buffer_head ** bh)
Definition at line 359 of file osd_iam.c.
References iam_container::ic_descr, iam_container::ic_object, iam_container::ic_root_bh, iam_descr::id_ops, and iam_operations::id_root_ptr.
Referenced by iam_lfix_guess(), and lvar_guess().
void iam_path_compat_fini (struct iam_path_compat * path)
Definition at line 334 of file osd_iam.c.
References iam_path_fini(), and iam_path_compat::ipc_path.
void iam_path_compat_init (struct iam_path_compat * path, struct inode * inode)
Definition at line 322 of file osd_iam.c.
References ARRAY_SIZE, iam_path_init(), iam_path_compat::ipc_container, iam_path_compat::ipc_descr, iam_path_compat::ipc_hinfo, iam_path_compat::ipc_hinfo_area, iam_path_compat::ipc_path, iam_path_compat::ipc_scratch, and iam_path_descr::ipd_key_scratch.
void iam_path_fini (struct iam_path * path)
Definition at line 315 of file osd_iam.c.
References iam_leaf_fini(), iam_path_release(), and iam_path::ip_leaf.
Referenced by __iam_path_lookup(), iam_add_rec(), iam_it_fini(), iam_lookup_lock(), and iam_path_compat_fini().
void iam_path_init (struct iam_path * path, struct iam_container * c, struct iam_path_descr * pd)
Definition at line 290 of file osd_iam.c.
References iam_leaf::il_path, iam_path::ip_container, iam_path::ip_data, iam_path::ip_frame, iam_path::ip_frames, and iam_path::ip_leaf.
Referenced by iam_it_init(), and iam_path_compat_init().
static int iam_path_invariant (struct iam_path * p) [static]
Definition at line 2542 of file osd_iam.c.
References ARRAY_SIZE, DX_MAX_TREE_HEIGHT, iam_frame_invariant(), iam_leaf_invariant(), iam_path::ip_container, iam_path::ip_frame, iam_path::ip_frames, iam_path::ip_indirect, and iam_path::ip_leaf.
Referenced by iam_it_invariant().
static int iam_path_lookup (struct iam_path * path, int index) [static]
Definition at line 1068 of file osd_iam.c.
References assert_inv, DLT_WRITE, do_corr, ergo, iam_leaf_load(), iam_leaf_ops(), iam_leaf_unlock(), iam_lookup_lock(), iam_leaf::il_lock, iam_path::ip_container, iam_path::ip_ikey_target, iam_path::ip_key_target, iam_path::ip_leaf, and lookup().
Referenced by __iam_it_get().
void iam_path_release (struct iam_path * path)
Definition at line 302 of file osd_iam.c.
References ARRAY_SIZE, iam_frame::at_shifted, iam_frame::bh, and iam_path::ip_frames.
Referenced by iam_index_next(), and iam_path_fini().
static void iam_rec_del (struct iam_leaf * leaf, int shift) [static]
Definition at line 535 of file osd_iam.c.
References iam_leaf_ops(), and iam_leaf_operations::rec_del.
Referenced by iam_it_rec_delete().
static void iam_recycle_leaf (handle_t * h, struct iam_path * p, struct buffer_head * bh, iam_ptr_t blk) [static]
Definition at line 2372 of file osd_iam.c.
References cpu_to_le16, cpu_to_le32, CWARN, head, iam_idle_blocks_limit(), iam_install_idle_blocks(), iam_txn_add(), iam_txn_dirty(), iam_container::ic_descr, iam_container::ic_idle_bh, iam_container::ic_idle_failed, iam_container::ic_idle_mutex, iam_container::ic_object, iam_container::ic_root_bh, iam_descr::id_root_gap, iam_idle_head::iih_blks, iam_idle_head::iih_count, iam_path::ip_container, le16_to_cpu, and unlikely.
Referenced by iam_it_rec_delete().
int iam_root_limit (int rootgap, int blocksize, int size)
Definition at line 2680 of file osd_iam.c.
Referenced by lfix_root(), and lvar_root().
static int iam_shift_entries (struct iam_path * path, struct iam_frame * frame, unsigned count, struct iam_entry * entries, struct iam_entry * entries2, u32 newblock) [static]
Definition at line 1832 of file osd_iam.c.
References iam_frame::bh, dx_get_ikey(), dx_index_is_compat(), dx_node_limit(), dx_set_count(), dx_set_limit(), dxtrace, iam_entry_shift(), iam_entry_size(), iam_insert_key_lock(), iam_lock_bh(), iam_path_ikey(), iam_unlock_bh(), and printk.
Referenced by split_index_node().
static int iam_txn_add (handle_t * handle, struct iam_path * path, struct buffer_head * bh) [static]
Definition at line 613 of file osd_iam.c.
References iam_path_obj().
Referenced by iam_add_rec(), iam_index_shrink(), iam_install_idle_blocks(), iam_it_rec_delete(), iam_it_rec_set(), and iam_recycle_leaf().
static int iam_txn_dirty (handle_t * handle, struct iam_path * path, struct buffer_head * bh) [static]
Definition at line 602 of file osd_iam.c.
References iam_path_obj().
Referenced by iam_add_rec(), iam_index_shrink(), iam_install_idle_blocks(), iam_it_rec_delete(), iam_it_rec_set(), iam_new_leaf(), and iam_recycle_leaf().
static void iam_unlock_array (struct iam_container * ic, struct dynlock_handle ** lh) [static]
Definition at line 1390 of file osd_iam.c.
References DX_MAX_TREE_HEIGHT, and iam_unlock_htree().
Referenced by iam_index_next(), and split_index_node().
static void iam_unlock_htree (struct iam_container * ic, struct dynlock_handle * lh) [static]
Definition at line 487 of file osd_iam.c.
References dynlock_unlock(), and iam_container::ic_tree_lock.
Referenced by iam_add_rec(), iam_index_shrink(), iam_leaf_unlock(), iam_lookup_lock(), iam_new_leaf(), and iam_unlock_array().
int iam_update (handle_t * h, struct iam_container * c, const struct iam_key * k, const struct iam_rec * r, struct iam_path_descr * pd)
Definition at line 2633 of file osd_iam.c.
References iam_it_fini(), iam_it_get_exact(), iam_it_init(), iam_it_put(), iam_it_rec_set(), IAM_IT_WRITE, iam_leaf_ops(), iam_iterator::ii_path, iam_path::ip_leaf, and iam_leaf_operations::rec_eq.
Referenced by osd_attr_set(), and osd_oi_iam_refresh().
static int it_at_rec (const struct iam_iterator * it) [inline, static]
Definition at line 660 of file osd_iam.c.
References iam_leaf_at_end(), iam_iterator::ii_path, and iam_path::ip_leaf.
Referenced by iam_it_collision(), iam_it_ikey_get(), iam_it_invariant(), iam_it_key_get(), iam_it_key_size(), iam_it_next(), iam_it_rec_delete(), iam_it_rec_get(), iam_it_rec_set(), iam_it_store(), and it_before().
static int it_before (const struct iam_iterator * it) [inline, static]
Definition at line 665 of file osd_iam.c.
References IAM_IT_SKEWED, it_at_rec(), and it_state().
Referenced by iam_it_next(), and iam_it_rec_insert().
static int it_ikeycmp (const struct iam_iterator * it, const struct iam_ikey * ik) [static]
Definition at line 653 of file osd_iam.c.
References iam_ikeycmp(), iam_leaf_ikey(), iam_path_ikey(), iam_iterator::ii_path, iam_path::ip_container, and iam_path::ip_leaf.
Referenced by iam_it_collision(), and iam_it_next().
static int it_keycmp (const struct iam_iterator * it, const struct iam_key * k) [inline, static]
Definition at line 641 of file osd_iam.c.
References iam_leaf_keycmp(), iam_iterator::ii_path, and iam_path::ip_leaf.
Referenced by iam_it_get(), and iam_it_rec_insert().
static int it_keyeq (const struct iam_iterator * it, const struct iam_key * k) [inline, static]
Definition at line 647 of file osd_iam.c.
References iam_leaf_keyeq(), iam_iterator::ii_path, and iam_path::ip_leaf.
Referenced by iam_it_collision().
static enum iam_it_state it_state (const struct iam_iterator * it) [static]
Definition at line 628 of file osd_iam.c.
References iam_iterator::ii_state.
Referenced by __iam_it_get(), iam_it_dup(), iam_it_fini(), iam_it_get(), iam_it_get_at(), iam_it_iget(), iam_it_ikey_get(), iam_it_key_get(), iam_it_key_size(), iam_it_load(), iam_it_next(), iam_it_rec_delete(), iam_it_rec_get(), iam_it_rec_insert(), iam_it_rec_set(), iam_it_store(), and it_before().
static int ptr_inside (void * base, size_t size, void * ptr) [inline, static]
Definition at line 2517 of file osd_iam.c.
Referenced by iam_frame_invariant(), and iam_leaf_invariant().
int split_index_node (handle_t * handle, struct iam_path * path, struct dynlock_handle ** lh)
Definition at line 1886 of file osd_iam.c.
References ARRAY_SIZE, assert_corr, assert_inv, iam_frame::at, iam_frame::bh, cleanup(), iam_frame::curidx, dir, DLT_WRITE, do_corr, dx_get_count(), dx_get_entries(), dx_get_limit(), dx_index_is_compat(), DX_MAX_TREE_HEIGHT, dx_node_limit(), dx_root_limit(), dx_set_block(), dx_set_limit(), dxtrace, iam_frame::entries, iam_check_full_path(), iam_entry_diff(), iam_entry_shift(), iam_entry_size(), iam_frame_is_locked(), iam_lock_bh(), iam_lock_htree(), iam_new_node(), iam_path_descr(), iam_path_obj(), iam_shift_entries(), iam_unlock_array(), iam_unlock_bh(), iam_operations::id_node_init, iam_descr::id_ops, iam_operations::id_root_inc, iam_path::ip_container, iam_path::ip_frame, iam_path::ip_frames, printk, and swap.
Referenced by iam_add_rec().
Variable Documentation
struct list_head iam_formats = LIST_HEAD_INIT(iam_formats) [static]
Definition at line 164 of file osd_iam.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.