Lustre: lustre/osd-ldiskfs/osd_oi.h File Reference
lustre/osd-ldiskfs/osd_oi.h File Reference
#include <linux/rwsem.h>
#include <linux/jbd2.h>
#include <lustre_fid.h>
#include <lu_object.h>
#include <md_object.h>
Data Structures
struct osd_inode_id
struct osd_idmap_cache
Defines
#define OSD_OI_FID_NR (1UL << OSD_OI_FID_OID_BITS)
#define OSD_OI_FID_NR_MAX (1UL << OSD_OI_FID_OID_BITS_MAX)
#define OSD_OII_NOGEN (0)
Enumerations
enum oi_check_flags { OI_CHECK_FLD = 0x00000001, OI_KNOWN_ON_OST = 0x00000002 }
Functions
static void osd_id_pack (struct osd_inode_id *tgt, const struct osd_inode_id *src)
static void osd_id_unpack (struct osd_inode_id *tgt, struct osd_inode_id *src)
static void osd_id_gen (struct osd_inode_id *id, __u32 ino, __u32 gen)
static void osd_id_to_inode (struct inode *inode, const struct osd_inode_id *id)
static int osd_id_eq (const struct osd_inode_id *id0, const struct osd_inode_id *id1)
static int osd_id_eq_strict (const struct osd_inode_id *id0, const struct osd_inode_id *id1)
int osd_oi_mod_init (void)
int osd_oi_init (struct osd_thread_info *info, struct osd_device *osd, bool restored)
void osd_oi_fini (struct osd_thread_info *info, struct osd_device *osd)
int osd_oi_lookup (struct osd_thread_info *info, struct osd_device *osd, const struct lu_fid *fid, struct osd_inode_id *id, enum oi_check_flags flags)
int osd_oi_insert (struct osd_thread_info *info, struct osd_device *osd, const struct lu_fid *fid, const struct osd_inode_id *id, handle_t *th, enum oi_check_flags flags)
int osd_oi_delete (struct osd_thread_info *info, struct osd_device *osd, const struct lu_fid *fid, handle_t *th, enum oi_check_flags flags)
int osd_oi_update (struct osd_thread_info *info, struct osd_device *osd, const struct lu_fid *fid, const struct osd_inode_id *id, handle_t *th, enum oi_check_flags flags)
int fid_is_on_ost (struct osd_thread_info *info, struct osd_device *osd, const struct lu_fid *fid, enum oi_check_flags flags)
Define Documentation
#define OSD_OI_FID_NR (1UL << OSD_OI_FID_OID_BITS)
Definition at line 60 of file osd_oi.h.
Referenced by osd_oi_mod_init(), osd_options_init(), and print_log_path().
#define OSD_OI_FID_NR_MAX (1UL << OSD_OI_FID_OID_BITS_MAX)
Definition at line 61 of file osd_oi.h.
Referenced by osd_oi_fini(), osd_oi_init(), osd_oi_mod_init(), osd_oi_probe(), osd_oi_table_open(), and osd_options_init().
#define OSD_OII_NOGEN (0)
Definition at line 63 of file osd_oi.h.
Referenced by osd_acct_obj_lookup(), osd_consistency_check(), osd_dirent_check_repair(), osd_ea_fid_get(), osd_ea_lookup_rec(), osd_fail_fid_lookup(), osd_id_eq(), osd_iget(), osd_iget_check(), osd_iit_iget(), osd_it_ea_rec(), osd_lookup_in_remote_parent(), osd_obj_map_lookup(), osd_obj_update_entry(), osd_oi_index_create_one(), and osd_process_scheduled_agent_removals().
Enumeration Type Documentation
enum oi_check_flags
Enumerator:
OI_CHECK_FLD
OI_KNOWN_ON_OST
Definition at line 136 of file osd_oi.h.
Function Documentation
int fid_is_on_ost (struct osd_thread_info * info, struct osd_device * osd, const struct lu_fid * fid, enum oi_check_flags flags)
Definition at line 548 of file osd_oi.c.
References CERROR, DFID, ENTRY, fid_is_idif(), fid_is_igif(), fid_is_last_id(), fid_is_llog(), fid_is_local_file(), fid_is_name_llog(), fid_is_quota(), fld_range_is_ost(), OI_CHECK_FLD, OI_KNOWN_ON_OST, osd_fld_lookup(), osd_name(), osd_seq_site(), osd_thread_info::oti_env, osd_thread_info::oti_seq_range, PFID, RETURN, and unlikely.
Referenced by osd_fid_lookup(), osd_get_name_n_idx(), osd_object_ea_create(), osd_oi_delete(), osd_oi_insert(), osd_oi_lookup(), and osd_oi_update().
static int osd_id_eq (const struct osd_inode_id * id0, const struct osd_inode_id * id1) [inline, static]
Definition at line 121 of file osd_oi.h.
References osd_inode_id::oii_gen, osd_inode_id::oii_ino, and OSD_OII_NOGEN.
Referenced by osd_consistency_check(), osd_oi_insert(), and osd_scrub_check_update().
static int osd_id_eq_strict (const struct osd_inode_id * id0, const struct osd_inode_id * id1) [inline, static]
Definition at line 130 of file osd_oi.h.
References osd_inode_id::oii_gen, and osd_inode_id::oii_ino.
Referenced by osd_ios_scan_one().
static void osd_id_gen (struct osd_inode_id * id, __u32 ino, __u32 gen) [inline, static]
Definition at line 108 of file osd_oi.h.
Referenced by __osd_oi_insert(), osd_dirent_check_repair(), osd_ea_fid_get(), osd_ea_lookup_rec(), osd_fail_fid_lookup(), osd_iget(), osd_iget_check(), osd_iit_iget(), osd_ios_scan_one(), osd_it_ea_rec(), osd_lookup_in_remote_parent(), osd_obj_map_lookup(), osd_obj_spec_lookup(), osd_obj_update_entry(), osd_oi_index_create_one(), osd_oi_lookup(), and osd_process_scheduled_agent_removals().
static void osd_id_pack (struct osd_inode_id * tgt, const struct osd_inode_id * src) [inline, static]
Definition at line 94 of file osd_oi.h.
References cpu_to_be32, osd_inode_id::oii_gen, and osd_inode_id::oii_ino.
Referenced by osd_oi_insert(), and osd_oi_update().
static void osd_id_to_inode (struct inode * inode, const struct osd_inode_id * id) [inline, static]
Definition at line 114 of file osd_oi.h.
Referenced by osd_obj_add_entry().
static void osd_id_unpack (struct osd_inode_id * tgt, struct osd_inode_id * src) [inline, static]
Definition at line 101 of file osd_oi.h.
References be32_to_cpu, osd_inode_id::oii_gen, and osd_inode_id::oii_ino.
Referenced by __osd_oi_lookup().
int osd_oi_delete (struct osd_thread_info * info, struct osd_device * osd, const struct lu_fid * fid, handle_t * th, enum oi_check_flags flags)
Definition at line 778 of file osd_oi.c.
References dt_key, fid_cpu_to_be(), fid_is_last_id(), fid_is_llog(), fid_is_on_ost(), fid_zero(), lu_fid_eq(), osd_idmap_cache::oic_fid, osd_fid2oi(), osd_obj_map_delete(), osd_oi_iam_delete(), osd_thread_info::oti_cache, and osd_thread_info::oti_fid2.
Referenced by osd_object_destroy(), and osd_scrub_refresh_mapping().
void osd_oi_fini (struct osd_thread_info * info, struct osd_device * osd)
Definition at line 496 of file osd_oi.c.
References OBD_FREE, osd_device::od_oi_count, osd_device::od_oi_table, OSD_OI_FID_NR_MAX, osd_oi_table_put(), and unlikely.
Referenced by osd_device_fini(), osd_scrub_cleanup(), and osd_scrub_setup().
int osd_oi_init (struct osd_thread_info * info, struct osd_device * osd, bool restored)
Definition at line 386 of file osd_oi.c.
References CERROR, ENTRY, ergo, GOTO, LASSERT, OBD_ALLOC, OBD_FREE, osd_device::od_oi_count, osd_device::od_oi_table, osd_device::od_scrub, oi_init_lock, osd_scrub::os_file, osd_oi_count, OSD_OI_FID_NR_MAX, OSD_OI_NAME_BASE, osd_oi_open(), osd_oi_table_open(), osd_oi_table_put(), osd_remove_ois(), osd_sb(), osd_scrub_file_reset(), osd_scrub_file_store(), RETURN, SCRUB_OI_BITMAP_SIZE, scrub_file::sf_oi_bitmap, scrub_file::sf_oi_count, SF_RECREATED, scrub_file::sf_success_count, and SF_UPGRADE.
Referenced by osd_mount(), and osd_scrub_setup().
int osd_oi_insert (struct osd_thread_info * info, struct osd_device * osd, const struct lu_fid * fid, const struct osd_inode_id * id, handle_t * th, enum oi_check_flags flags)
Definition at line 671 of file osd_oi.c.
References CERROR, DFID, dt_key, fid_cpu_to_be(), fid_is_last_id(), fid_is_llog(), fid_is_on_ost(), FID_SEQ_LOCAL_FILE, lustre_mdt_attrs::lma_compat, lustre_mdt_attrs::lma_self_fid, LMAC_NOT_IN_OI, lu_fid_eq(), osd_inode_id::oii_gen, osd_inode_id::oii_ino, osd_fid2oi(), osd_get_lma(), osd_id_eq(), osd_id_pack(), osd_iget(), osd_is_ea_inode(), osd_obj_map_insert(), osd_obj_spec_insert(), osd_oi_iam_refresh(), osd_oi_lookup(), osd_sb(), osd_thread_info::oti_fid2, osd_thread_info::oti_id2, osd_thread_info::oti_mdt_attrs, osd_thread_info::oti_obj_dentry, PFID, and unlikely.
Referenced by __osd_oi_insert(), and osd_scrub_refresh_mapping().
int osd_oi_lookup (struct osd_thread_info * info, struct osd_device * osd, const struct lu_fid * fid, struct osd_inode_id * id, enum oi_check_flags flags)
Definition at line 604 of file osd_oi.c.
References __osd_oi_lookup(), fid_is_acct(), fid_is_fs_root(), fid_is_igif(), fid_is_last_id(), fid_is_llog(), fid_is_on_ost(), FID_SEQ_LOCAL_FILE, lu_igif_gen(), lu_igif_ino(), osd_device::od_igif_inoi, osd_acct_obj_lookup(), osd_id_gen(), osd_obj_map_lookup(), osd_obj_spec_lookup(), osd_sb(), and unlikely.
Referenced by osd_consistency_check(), osd_fid_lookup(), osd_idc_find_or_init(), osd_iget_check(), osd_ios_scan_one(), osd_oi_add_table(), osd_oi_find_or_create(), osd_oi_insert(), osd_oi_probe(), and osd_scrub_check_update().
int osd_oi_mod_init (void)
Definition at line 826 of file osd_oi.c.
References LCONSOLE_WARN, oi_init_lock, osd_oi_count, OSD_OI_FID_NR, OSD_OI_FID_NR_MAX, and size_roundup_power2().
Referenced by osd_init().
int osd_oi_update (struct osd_thread_info * info, struct osd_device * osd, const struct lu_fid * fid, const struct osd_inode_id * id, handle_t * th, enum oi_check_flags flags)
Definition at line 799 of file osd_oi.c.
References dt_key, fid_cpu_to_be(), fid_is_last_id(), fid_is_llog(), fid_is_on_ost(), FID_SEQ_LOCAL_FILE, osd_fid2oi(), osd_id_pack(), osd_obj_map_update(), osd_obj_spec_update(), osd_oi_iam_refresh(), osd_thread_info::oti_fid2, osd_thread_info::oti_id2, and unlikely.
Referenced by osd_scrub_refresh_mapping().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.