Lustre: lustre/osd-ldiskfs/osd_iam_lvar.c File Reference
lustre/osd-ldiskfs/osd_iam_lvar.c File Reference
#include <linux/types.h>
#include "osd_internal.h"
Data Structures
struct lvar_leaf_header
struct lvar_leaf_entry
struct lvar_root
Defines
#define PDIFF(ptr0, ptr1) (((char *)(ptr0)) - ((char *)(ptr1)))
#define LVAR_HASH_SANDWICH (0)
#define LVAR_HASH_TEA (1)
#define LVAR_HASH_R5 (0)
#define LVAR_HASH_PREFIX (0)
Typedefs
typedef __u32 lvar_hash_t
Enumerations
enum { IAM_LVAR_LEAF_MAGIC = 0x1973 }
enum { LVAR_PAD = 4, LVAR_ROUND = LVAR_PAD - 1 }
enum { HASH_GRAY_AREA = 1024, HASH_MAX_SIZE = 0x7fffffffUL }
enum { IAM_LVAR_ROOT_MAGIC = 0xb01dface }
Functions
static int blocksize (const struct iam_leaf *leaf)
static const char * kchar (const struct iam_key *key)
static struct iam_lentry * lvar_lentry (const struct lvar_leaf_entry *ent)
static struct lvar_leaf_entry * lentry_lvar (const struct iam_lentry *lent)
static int e_keysize (const struct lvar_leaf_entry *ent)
static int getsize (const struct iam_leaf *leaf, int namelen, int recsize)
static int rec_size (const struct iam_rec *rec)
static struct iam_rec * e_rec (const struct lvar_leaf_entry *ent)
static int e_size (const struct iam_leaf *leaf, const struct lvar_leaf_entry *ent)
static char * e_char (const struct lvar_leaf_entry *ent)
static struct iam_key * e_key (const struct lvar_leaf_entry *ent)
static lvar_hash_t e_hash (const struct lvar_leaf_entry *ent)
static void e_print (const struct lvar_leaf_entry *ent)
static struct lvar_leaf_entry * e_next (const struct iam_leaf *leaf, const struct lvar_leaf_entry *ent)
static __u32 hash_build0 (const char *name, int namelen)
static __u32 hash_build (const char *name, int namelen)
static lvar_hash_t get_hash (const struct iam_container *bag, const char *name, int namelen)
static int e_eq (const struct lvar_leaf_entry *ent, const char *name, int namelen)
static int e_cmp (const struct iam_leaf *leaf, const struct lvar_leaf_entry *ent, lvar_hash_t hash)
static struct lvar_leaf_header * n_head (const struct iam_leaf *l)
static int h_used (const struct lvar_leaf_header *hdr)
static void h_used_adj (const struct iam_leaf *leaf, struct lvar_leaf_header *hdr, int adj)
static struct lvar_leaf_entry * n_start (const struct iam_leaf *leaf)
static struct lvar_leaf_entry * n_end (const struct iam_leaf *l)
static struct lvar_leaf_entry * n_cur (const struct iam_leaf *l)
void n_print (const struct iam_leaf *l)
static struct iam_ikey * lvar_ikey (const struct iam_leaf *l, struct iam_ikey *key)
static struct iam_key * lvar_key (const struct iam_leaf *l)
static int lvar_key_size (const struct iam_leaf *l)
static void lvar_start (struct iam_leaf *l)
static int lvar_init (struct iam_leaf *l)
static void lvar_fini (struct iam_leaf *l)
static struct iam_rec * lvar_rec (const struct iam_leaf *l)
static void lvar_next (struct iam_leaf *l)
static int lvar_lookup (struct iam_leaf *leaf, const struct iam_key *k)
static int lvar_ilookup (struct iam_leaf *leaf, const struct iam_ikey *ik)
static void __lvar_key_set (struct iam_leaf *l, const struct iam_key *k)
static void lvar_key_set (struct iam_leaf *l, const struct iam_key *k)
static int lvar_key_cmp (const struct iam_leaf *l, const struct iam_key *k)
static int lvar_key_eq (const struct iam_leaf *l, const struct iam_key *k)
static void __lvar_rec_set (struct iam_leaf *l, const struct iam_rec *r)
static void lvar_rec_set (struct iam_leaf *l, const struct iam_rec *r)
static int lvar_rec_eq (const struct iam_leaf *l, const struct iam_rec *r)
static void lvar_rec_get (const struct iam_leaf *l, struct iam_rec *r)
static int lvar_can_add (const struct iam_leaf *l, const struct iam_key *k, const struct iam_rec *r)
static int lvar_at_end (const struct iam_leaf *folio)
static void lvar_rec_add (struct iam_leaf *leaf, const struct iam_key *k, const struct iam_rec *r)
static void lvar_rec_del (struct iam_leaf *leaf, int shift)
static void lvar_init_new (struct iam_container *c, struct buffer_head *bh)
static struct lvar_leaf_entry * find_pivot (const struct iam_leaf *leaf, struct lvar_leaf_entry **prev)
static void lvar_split (struct iam_leaf *leaf, struct buffer_head **bh, iam_ptr_t new_blknr)
static int lvar_leaf_empty (struct iam_leaf *leaf)
static __u32 lvar_root_ptr (struct iam_container *c)
static int lvar_node_init (struct iam_container *c, struct buffer_head *bh, int root)
static struct iam_entry * lvar_root_inc (struct iam_container *c, struct iam_path *path, struct iam_frame *frame)
static int lvar_node_check (struct iam_path *path, struct iam_frame *frame)
static int lvar_node_load (struct iam_path *path, struct iam_frame *frame)
static int lvar_ikeycmp (const struct iam_container *c, const struct iam_ikey *k1, const struct iam_ikey *k2)
static struct iam_path_descr * lvar_ipd_alloc (const struct iam_container *c, void *area)
static void lvar_root (void *buf, int blocksize, int keysize, int ptrsize, int recsize)
static int lvar_esize (int namelen, int recsize)
static void lvar_leaf (void *buf, int blocksize, int keysize, int ptrsize, int recsize)
int iam_lvar_create (struct inode *obj, int keysize, int ptrsize, int recsize, handle_t *handle)
static int lvar_guess (struct iam_container *c)
void iam_lvar_format_init (void)
Variables
static struct iam_leaf_operations lvar_leaf_ops
static struct iam_operations lvar_ops
static struct iam_format lvar_format
Define Documentation
#define LVAR_HASH_PREFIX (0)
Definition at line 182 of file osd_iam_lvar.c.
Referenced by hash_build0().
#define LVAR_HASH_R5 (0)
Definition at line 181 of file osd_iam_lvar.c.
#define LVAR_HASH_SANDWICH (0)
Definition at line 179 of file osd_iam_lvar.c.
Referenced by hash_build0().
#define LVAR_HASH_TEA (1)
Definition at line 180 of file osd_iam_lvar.c.
#define PDIFF (ptr0, ptr1) (((char *)(ptr0)) - ((char *)(ptr1)))
Definition at line 81 of file osd_iam_lvar.c.
Referenced by lvar_rec_add(), and lvar_split().
Typedef Documentation
typedef __u32 lvar_hash_t
Definition at line 72 of file osd_iam_lvar.c.
Enumeration Type Documentation
anonymous enum
Enumerator:
IAM_LVAR_LEAF_MAGIC
Definition at line 50 of file osd_iam_lvar.c.
anonymous enum
Enumerator:
LVAR_PAD
LVAR_ROUND
Definition at line 111 of file osd_iam_lvar.c.
anonymous enum
Enumerator:
HASH_GRAY_AREA
HASH_MAX_SIZE
Definition at line 219 of file osd_iam_lvar.c.
anonymous enum
Enumerator:
IAM_LVAR_ROOT_MAGIC
Definition at line 803 of file osd_iam_lvar.c.
Function Documentation
static void __lvar_key_set (struct iam_leaf * l, const struct iam_key * k) [static]
Definition at line 530 of file osd_iam_lvar.c.
References e_key(), e_keysize(), and n_cur().
Referenced by lvar_key_set(), and lvar_rec_add().
static void __lvar_rec_set (struct iam_leaf * l, const struct iam_rec * r) [static]
Definition at line 563 of file osd_iam_lvar.c.
References e_rec(), n_cur(), and rec_size().
Referenced by lvar_rec_add(), and lvar_rec_set().
static int blocksize (const struct iam_leaf * leaf) [inline, static]
Definition at line 84 of file osd_iam_lvar.c.
References iam_leaf_container(), and iam_container::ic_object.
Referenced by find_pivot(), gss_prep_bulk_kerberos(), gss_unwrap_bulk_kerberos(), gss_unwrap_kerberos(), gss_wrap_bulk_kerberos(), gss_wrap_kerberos(), h_used_adj(), krb5_decrypt_bulk(), krb5_encrypt_bulk(), lvar_can_add(), lvar_init(), osd_do_bio(), osd_ldiskfs_read(), and osd_ldiskfs_write_record().
static char* e_char (const struct lvar_leaf_entry * ent) [inline, static]
Definition at line 141 of file osd_iam_lvar.c.
References lvar_leaf_entry::vle_key.
Referenced by e_eq(), e_key(), and e_print().
static int e_cmp (const struct iam_leaf * leaf, const struct lvar_leaf_entry * ent, lvar_hash_t hash) [inline, static]
Definition at line 246 of file osd_iam_lvar.c.
References e_hash().
Referenced by lvar_key_cmp().
static int e_eq (const struct lvar_leaf_entry * ent, const char * name, int namelen) [inline, static]
Definition at line 240 of file osd_iam_lvar.c.
References e_char(), and e_keysize().
Referenced by lvar_key_eq(), and lvar_lookup().
static lvar_hash_t e_hash (const struct lvar_leaf_entry * ent) [inline, static]
Definition at line 151 of file osd_iam_lvar.c.
References le32_to_cpu, and lvar_leaf_entry::vle_hash.
Referenced by e_cmp(), e_print(), lvar_ikey(), lvar_ilookup(), lvar_lookup(), and lvar_split().
static struct iam_key* e_key (const struct lvar_leaf_entry * ent) [static, read]
Definition at line 146 of file osd_iam_lvar.c.
References e_char().
Referenced by __lvar_key_set(), and lvar_key().
static int e_keysize (const struct lvar_leaf_entry * ent) [inline, static]
Definition at line 105 of file osd_iam_lvar.c.
References le16_to_cpu, and lvar_leaf_entry::vle_keysize.
Referenced by __lvar_key_set(), e_eq(), e_print(), e_rec(), e_size(), lvar_key_set(), and lvar_key_size().
static struct lvar_leaf_entry* e_next (const struct iam_leaf * leaf, const struct lvar_leaf_entry * ent) [static, read]
Definition at line 173 of file osd_iam_lvar.c.
References e_size().
Referenced by find_pivot(), lvar_ilookup(), lvar_lookup(), lvar_next(), lvar_rec_del(), lvar_split(), and n_print().
static void e_print (const struct lvar_leaf_entry * ent) [static]
Definition at line 156 of file osd_iam_lvar.c.
References e_char(), e_hash(), e_keysize(), and printk.
Referenced by n_print().
static struct iam_rec* e_rec (const struct lvar_leaf_entry * ent) [static, read]
Definition at line 129 of file osd_iam_lvar.c.
References e_keysize(), and offsetof.
Referenced by __lvar_rec_set(), e_size(), lvar_leaf(), lvar_rec(), lvar_rec_eq(), and lvar_rec_get().
static int e_size (const struct iam_leaf * leaf, const struct lvar_leaf_entry * ent) [inline, static]
Definition at line 135 of file osd_iam_lvar.c.
References e_keysize(), e_rec(), getsize(), and rec_size().
Referenced by e_next(), and lvar_rec_del().
static struct lvar_leaf_entry* find_pivot (const struct iam_leaf * leaf, struct lvar_leaf_entry ** prev) [static, read]
Definition at line 683 of file osd_iam_lvar.c.
References blocksize(), e_next(), n_start(), and start.
Referenced by lvar_split().
static lvar_hash_t get_hash (const struct iam_container * bag, const char * name, int namelen) [inline, static]
Definition at line 234 of file osd_iam_lvar.c.
References hash_build().
Referenced by lvar_key_cmp(), lvar_lookup(), lvar_node_load(), and lvar_rec_add().
static int getsize (const struct iam_leaf * leaf, int namelen, int recsize) [inline, static]
Definition at line 116 of file osd_iam_lvar.c.
References CLASSERT, LVAR_PAD, LVAR_ROUND, offsetof, and lvar_leaf_entry::vle_key.
Referenced by e_size(), lvar_can_add(), and lvar_rec_add().
static int h_used (const struct lvar_leaf_header * hdr) [static]
Definition at line 260 of file osd_iam_lvar.c.
References le16_to_cpu, and lvar_leaf_header::vlh_used.
Referenced by h_used_adj(), lvar_can_add(), lvar_init(), lvar_leaf_empty(), n_end(), and n_print().
static void h_used_adj (const struct iam_leaf * leaf, struct lvar_leaf_header * hdr, int adj) [static]
Definition at line 265 of file osd_iam_lvar.c.
References assert_corr, blocksize(), cpu_to_le16, h_used(), and lvar_leaf_header::vlh_used.
Referenced by lvar_rec_add(), lvar_rec_del(), and lvar_split().
static __u32 hash_build (const char * name, int namelen) [static]
Definition at line 224 of file osd_iam_lvar.c.
References hash_build0(), HASH_GRAY_AREA, and HASH_MAX_SIZE.
Referenced by get_hash().
static __u32 hash_build0 (const char * name, int namelen) [static]
Definition at line 184 of file osd_iam_lvar.c.
References LVAR_HASH_PREFIX, and LVAR_HASH_SANDWICH.
Referenced by hash_build().
int iam_lvar_create (struct inode * obj, int keysize, int ptrsize, int recsize, handle_t * handle)
Definition at line 1005 of file osd_iam_lvar.c.
References assert_corr, GOTO, lvar_leaf(), lvar_root(), and osd_ldiskfs_append().
Referenced by osd_mk_index(), and osd_oi_index_create_one().
void iam_lvar_format_init (void)
Definition at line 1097 of file osd_iam_lvar.c.
References iam_format_register().
Referenced by iam_format_guess().
static const char* kchar (const struct iam_key * key) [inline, static]
Definition at line 89 of file osd_iam_lvar.c.
Referenced by lvar_can_add(), lvar_key_cmp(), lvar_key_eq(), lvar_key_set(), lvar_lookup(), lvar_node_load(), and lvar_rec_add().
static struct lvar_leaf_entry* lentry_lvar (const struct iam_lentry * lent) [static, read]
Definition at line 99 of file osd_iam_lvar.c.
Referenced by n_cur().
static int lvar_at_end (const struct iam_leaf * folio) [static]
Definition at line 605 of file osd_iam_lvar.c.
References assert_corr, iam_leaf_is_locked(), n_cur(), and n_end().
Referenced by lvar_rec_add().
static int lvar_can_add (const struct iam_leaf * l, const struct iam_key * k, const struct iam_rec * r) [static]
Definition at line 596 of file osd_iam_lvar.c.
References assert_corr, blocksize(), getsize(), h_used(), iam_leaf_is_locked(), kchar(), n_head(), and rec_size().
Referenced by lvar_rec_add().
static int lvar_esize (int namelen, int recsize) [static]
Definition at line 978 of file osd_iam_lvar.c.
References LVAR_ROUND, and offsetof.
Referenced by lvar_leaf().
static void lvar_fini (struct iam_leaf * l) [static]
Definition at line 420 of file osd_iam_lvar.c.
References iam_leaf::il_at, and iam_leaf::il_entries.
static int lvar_guess (struct iam_container * c) [static]
Definition at line 1060 of file osd_iam_lvar.c.
References assert_corr, IAM_LVAR_ROOT_MAGIC, iam_node_read(), iam_container::ic_descr, iam_container::ic_object, iam_container::ic_root_bh, iam_descr::id_ikey_size, iam_descr::id_key_size, iam_descr::id_leaf_ops, iam_descr::id_node_gap, iam_descr::id_ops, iam_descr::id_ptr_size, iam_descr::id_rec_size, iam_descr::id_root_gap, le16_to_cpu, le32_to_cpu, lvar_root_ptr(), lvar_root::vr_magic, lvar_root::vr_ptrsize, and lvar_root::vr_recsize.
static struct iam_ikey* lvar_ikey (const struct iam_leaf * l, struct iam_ikey * key) [static, read]
Definition at line 365 of file osd_iam_lvar.c.
References assert_corr, e_hash(), and n_cur().
static int lvar_ikeycmp (const struct iam_container * c, const struct iam_ikey * k1, const struct iam_ikey * k2) [static]
Definition at line 905 of file osd_iam_lvar.c.
References le32_to_cpu.
static int lvar_ilookup (struct iam_leaf * leaf, const struct iam_ikey * ik) [static]
Definition at line 500 of file osd_iam_lvar.c.
References assert_inv, e_hash(), e_next(), IAM_LOOKUP_BEFORE, IAM_LOOKUP_EXACT, IAM_LOOKUP_OK, iam_leaf::il_at, lvar_lentry(), lvar_start(), n_end(), and n_start().
static int lvar_init (struct iam_leaf * l) [static]
Definition at line 392 of file osd_iam_lvar.c.
References assert_corr, blocksize(), CERROR, h_used(), head, iam_leaf_container(), IAM_LVAR_LEAF_MAGIC, iam_container::ic_object, iam_leaf::il_at, iam_leaf::il_bh, iam_leaf::il_entries, le16_to_cpu, lvar_lentry(), n_head(), n_start(), and lvar_leaf_header::vlh_magic.
Referenced by lvar_split().
static void lvar_init_new (struct iam_container * c, struct buffer_head * bh) [static]
Definition at line 674 of file osd_iam_lvar.c.
References cpu_to_le16, IAM_LVAR_LEAF_MAGIC, lvar_leaf_header::vlh_magic, and lvar_leaf_header::vlh_used.
static struct iam_path_descr* lvar_ipd_alloc (const struct iam_container * c, void * area) [static, read]
Definition at line 914 of file osd_iam_lvar.c.
References iam_ipd_alloc(), iam_container::ic_descr, and iam_descr::id_ikey_size.
static struct iam_key* lvar_key (const struct iam_leaf * l) [static, read]
Definition at line 377 of file osd_iam_lvar.c.
References e_key(), and n_cur().
static int lvar_key_cmp (const struct iam_leaf * l, const struct iam_key * k) [static]
Definition at line 544 of file osd_iam_lvar.c.
References e_cmp(), get_hash(), iam_leaf_container(), kchar(), n_cur(), and name.
Referenced by lvar_rec_add().
static int lvar_key_eq (const struct iam_leaf * l, const struct iam_key * k) [static]
Definition at line 555 of file osd_iam_lvar.c.
References e_eq(), kchar(), n_cur(), and name.
static void lvar_key_set (struct iam_leaf * l, const struct iam_key * k) [static]
Definition at line 535 of file osd_iam_lvar.c.
References __lvar_key_set(), assert_corr, assert_inv, e_keysize(), iam_leaf_is_locked(), kchar(), and n_cur().
static int lvar_key_size (const struct iam_leaf * l) [static]
Definition at line 382 of file osd_iam_lvar.c.
References e_keysize(), and n_cur().
static void lvar_leaf (void * buf, int blocksize, int keysize, int ptrsize, int recsize) [static]
Definition at line 984 of file osd_iam_lvar.c.
References cpu_to_le16, e_rec(), head, IAM_LVAR_LEAF_MAGIC, lvar_esize(), lvar_leaf_entry::vle_hash, and lvar_leaf_header::vlh_magic.
Referenced by iam_lvar_create().
static int lvar_leaf_empty (struct iam_leaf * leaf) [static]
Definition at line 768 of file osd_iam_lvar.c.
References h_used(), and n_head().
static struct iam_lentry* lvar_lentry (const struct lvar_leaf_entry * ent) [static, read]
Definition at line 94 of file osd_iam_lvar.c.
Referenced by lvar_ilookup(), lvar_init(), lvar_lookup(), lvar_next(), and lvar_start().
static int lvar_lookup (struct iam_leaf * leaf, const struct iam_key * k) [static]
Definition at line 438 of file osd_iam_lvar.c.
References assert_corr, assert_inv, e_eq(), e_hash(), e_next(), get_hash(), iam_leaf_container(), IAM_LOOKUP_BEFORE, IAM_LOOKUP_EXACT, IAM_LOOKUP_LAST, IAM_LOOKUP_OK, iam_leaf::il_at, kchar(), lvar_lentry(), lvar_start(), n_end(), n_start(), and name.
static void lvar_next (struct iam_leaf * l) [static]
Definition at line 431 of file osd_iam_lvar.c.
References assert_corr, e_next(), iam_leaf_is_locked(), iam_leaf::il_at, lvar_lentry(), and n_cur().
Referenced by lvar_rec_add().
static int lvar_node_check (struct iam_path * path, struct iam_frame * frame) [static]
Definition at line 852 of file osd_iam_lvar.c.
References iam_frame::bh, dx_get_count(), dx_get_limit(), dx_node_get_entries(), dx_node_limit(), dx_root_limit(), IAM_LVAR_ROOT_MAGIC, iam_path::ip_frames, le32_to_cpu, and lvar_root::vr_magic.
static int lvar_node_init (struct iam_container * c, struct buffer_head * bh, int root) [static]
Definition at line 824 of file osd_iam_lvar.c.
static int lvar_node_load (struct iam_path * path, struct iam_frame * frame) [static]
Definition at line 879 of file osd_iam_lvar.c.
References iam_frame::at, iam_frame::bh, dx_node_get_entries(), iam_frame::entries, get_hash(), iam_path_ikey(), iam_path::ip_container, iam_path::ip_frames, iam_path::ip_ikey_target, iam_path::ip_indirect, iam_path::ip_key_target, kchar(), name, and lvar_root::vr_indirect_levels.
static struct iam_rec* lvar_rec (const struct iam_leaf * l) [static, read]
Definition at line 425 of file osd_iam_lvar.c.
References assert_corr, e_rec(), and n_cur().
static void lvar_rec_add (struct iam_leaf * leaf, const struct iam_key * k, const struct iam_rec * r) [static]
Definition at line 611 of file osd_iam_lvar.c.
References __lvar_key_set(), __lvar_rec_set(), assert_corr, assert_inv, cpu_to_le16, cpu_to_le32, get_hash(), getsize(), h_used_adj(), iam_leaf_container(), iam_leaf_is_locked(), iam_leaf::il_at, iam_leaf::il_entries, kchar(), lvar_at_end(), lvar_can_add(), lvar_key_cmp(), lvar_next(), n_cur(), n_end(), n_head(), PDIFF, rec_size(), start, lvar_leaf_entry::vle_hash, and lvar_leaf_entry::vle_keysize.
static void lvar_rec_del (struct iam_leaf * leaf, int shift) [static]
Definition at line 656 of file osd_iam_lvar.c.
References assert_corr, assert_inv, e_next(), e_size(), h_used_adj(), iam_leaf_is_locked(), iam_leaf::il_at, n_cur(), n_end(), and n_head().
static int lvar_rec_eq (const struct iam_leaf * l, const struct iam_rec * r) [static]
Definition at line 576 of file osd_iam_lvar.c.
References e_rec(), n_cur(), and rec_size().
static void lvar_rec_get (const struct iam_leaf * l, struct iam_rec * r) [static]
Definition at line 585 of file osd_iam_lvar.c.
References assert_corr, assert_inv, e_rec(), iam_leaf_is_locked(), n_cur(), and rec_size().
static void lvar_rec_set (struct iam_leaf * l, const struct iam_rec * r) [static]
Definition at line 568 of file osd_iam_lvar.c.
References __lvar_rec_set(), assert_corr, assert_inv, and iam_leaf_is_locked().
static void lvar_root (void * buf, int blocksize, int keysize, int ptrsize, int recsize) [static]
Definition at line 920 of file osd_iam_lvar.c.
References dx_countlimit::count, cpu_to_le16, cpu_to_le32, cpu_to_le64, IAM_LVAR_ROOT_MAGIC, iam_root_limit(), LASSERT, dx_countlimit::limit, and lvar_root::vr_magic.
Referenced by iam_lvar_create().
static struct iam_entry* lvar_root_inc (struct iam_container * c, struct iam_path * path, struct iam_frame * frame) [static, read]
Definition at line 830 of file osd_iam_lvar.c.
References assert_corr, iam_frame::at, iam_frame::bh, dx_get_limit(), dx_root_limit(), dx_set_count(), iam_frame::entries, iam_entry_shift(), iam_frame_is_locked(), iam_ikey_at(), IAM_LVAR_ROOT_MAGIC, iam_path_descr(), le64_to_cpu, lvar_root::vr_indirect_levels, and lvar_root::vr_magic.
static __u32 lvar_root_ptr (struct iam_container * c) [static]
Definition at line 819 of file osd_iam_lvar.c.
Referenced by lvar_guess().
static void lvar_split (struct iam_leaf * leaf, struct buffer_head ** bh, iam_ptr_t new_blknr) [static]
Definition at line 699 of file osd_iam_lvar.c.
References assert_corr, assert_inv, e_hash(), e_next(), find_pivot(), h_used_adj(), iam_insert_key_lock(), iam_leaf_is_locked(), iam_leaf_path(), iam_leaf::il_at, iam_leaf::il_bh, iam_leaf::il_curidx, iam_path::ip_frame, lvar_init(), n_cur(), n_end(), n_head(), and PDIFF.
static void lvar_start (struct iam_leaf * l) [static]
Definition at line 387 of file osd_iam_lvar.c.
References iam_leaf::il_at, lvar_lentry(), and n_start().
Referenced by lvar_ilookup(), and lvar_lookup().
static struct lvar_leaf_entry* n_cur (const struct iam_leaf * l) [static, read]
Definition at line 285 of file osd_iam_lvar.c.
References iam_leaf::il_at, and lentry_lvar().
Referenced by __lvar_key_set(), __lvar_rec_set(), lvar_at_end(), lvar_ikey(), lvar_key(), lvar_key_cmp(), lvar_key_eq(), lvar_key_set(), lvar_key_size(), lvar_next(), lvar_rec(), lvar_rec_add(), lvar_rec_del(), lvar_rec_eq(), lvar_rec_get(), and lvar_split().
static struct lvar_leaf_entry* n_end (const struct iam_leaf * l) [static, read]
Definition at line 280 of file osd_iam_lvar.c.
References h_used(), iam_leaf::il_bh, and n_head().
Referenced by lvar_at_end(), lvar_ilookup(), lvar_lookup(), lvar_rec_add(), lvar_rec_del(), lvar_split(), and n_print().
static struct lvar_leaf_header* n_head (const struct iam_leaf * l) [static, read]
Definition at line 255 of file osd_iam_lvar.c.
References iam_leaf::il_bh.
Referenced by lvar_can_add(), lvar_init(), lvar_leaf_empty(), lvar_rec_add(), lvar_rec_del(), lvar_split(), n_end(), and n_print().
void n_print (const struct iam_leaf * l)
Definition at line 290 of file osd_iam_lvar.c.
References e_next(), e_print(), h_used(), n_end(), n_head(), n_start(), and printk.
static struct lvar_leaf_entry* n_start (const struct iam_leaf * leaf) [static, read]
Definition at line 275 of file osd_iam_lvar.c.
References iam_leaf::il_bh.
Referenced by find_pivot(), lvar_ilookup(), lvar_init(), lvar_lookup(), lvar_start(), and n_print().
static int rec_size (const struct iam_rec * rec) [inline, static]
Definition at line 124 of file osd_iam_lvar.c.
Referenced by __lvar_rec_set(), e_size(), lvar_can_add(), lvar_rec_add(), lvar_rec_eq(), and lvar_rec_get().
Variable Documentation
struct iam_format lvar_format [static]
Initial value:
 {
        .if_guess = lvar_guess
}
Definition at line 1093 of file osd_iam_lvar.c.
struct iam_leaf_operations lvar_leaf_ops [static]
Initial value:
 {
        .init           = lvar_init,
        .init_new       = lvar_init_new,
        .fini           = lvar_fini,
        .start          = lvar_start,
        .next           = lvar_next,
        .key            = lvar_key,
        .ikey           = lvar_ikey,
        .rec            = lvar_rec,
        .key_set        = lvar_key_set,
        .key_cmp        = lvar_key_cmp,
        .key_eq         = lvar_key_eq,
        .key_size       = lvar_key_size,
        .rec_set        = lvar_rec_set,
        .rec_eq         = lvar_rec_eq,
        .rec_get        = lvar_rec_get,
        .lookup         = lvar_lookup,
        .ilookup        = lvar_ilookup,
        .at_end         = lvar_at_end,
        .rec_add        = lvar_rec_add,
        .rec_del        = lvar_rec_del,
        .can_add        = lvar_can_add,
        .split          = lvar_split,
        .leaf_empty     = lvar_leaf_empty,
}
Definition at line 773 of file osd_iam_lvar.c.
struct iam_operations lvar_ops [static]
Initial value:
 {
        .id_root_ptr    = lvar_root_ptr,
        .id_node_read   = iam_node_read,
        .id_node_init   = lvar_node_init,
        .id_node_check  = lvar_node_check,
        .id_node_load   = lvar_node_load,
        .id_ikeycmp     = lvar_ikeycmp,
        .id_root_inc    = lvar_root_inc,
        .id_ipd_alloc   = lvar_ipd_alloc,
        .id_ipd_free    = iam_ipd_free,
        .id_name        = "lvar"
}
Definition at line 1047 of file osd_iam_lvar.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.