Lustre: lustre/osd-zfs/osd_index.c File Reference
lustre/osd-zfs/osd_index.c File Reference
#include <lustre_ver.h>
#include <libcfs/libcfs.h>
#include <obd_support.h>
#include <lustre_net.h>
#include <obd.h>
#include <obd_class.h>
#include <lustre_disk.h>
#include <lustre_fid.h>
#include "osd_internal.h"
#include <sys/dnode.h>
#include <sys/dbuf.h>
#include <sys/spa.h>
#include <sys/stat.h>
#include <sys/zap.h>
#include <sys/spa_impl.h>
#include <sys/zfs_znode.h>
#include <sys/dmu_tx.h>
#include <sys/dmu_objset.h>
#include <sys/dsl_prop.h>
#include <sys/sa_impl.h>
#include <sys/txg.h>
Data Structures
struct osd_metadnode_it
Defines
#define DEBUG_SUBSYSTEM S_OSD
#define zap_hashbits(zc) 48
#define OTABLE_PREFETCH 256
Functions
static int osd_object_is_zap (dmu_buf_t *db)
uint64_t osd_zap_cursor_serialize (zap_cursor_t *zc)
void osd_zap_cursor_init_serialized (zap_cursor_t *zc, struct objset *os, uint64_t id, uint64_t dirhash)
int osd_zap_cursor_init (zap_cursor_t **zc, struct objset *os, uint64_t id, uint64_t dirhash)
void osd_zap_cursor_fini (zap_cursor_t *zc)
static void osd_obj_cursor_init_serialized (zap_cursor_t *zc, struct osd_object *o, uint64_t dirhash)
static int osd_obj_cursor_init (zap_cursor_t **zc, struct osd_object *o, uint64_t dirhash)
static struct dt_it * osd_index_it_init (const struct lu_env *env, struct dt_object *dt, __u32 unused)
static void osd_index_it_fini (const struct lu_env *env, struct dt_it *di)
static void osd_index_it_put (const struct lu_env *env, struct dt_it *di)
static void osd_it_append_attrs (struct lu_dirent *ent, __u32 attr, int len, __u16 type)
static int osd_get_fid_by_oid (const struct lu_env *env, struct osd_device *osd, uint64_t oid, struct lu_fid *fid)
Get the object's FID from its LMA EA.
static int osd_find_parent_by_dnode (const struct lu_env *env, struct dt_object *o, struct lu_fid *fid)
static int osd_find_parent_fid (const struct lu_env *env, struct dt_object *o, struct lu_fid *fid)
static int osd_dir_lookup (const struct lu_env *env, struct dt_object *dt, struct dt_rec *rec, const struct dt_key *key)
static int osd_declare_dir_insert (const struct lu_env *env, struct dt_object *dt, const struct dt_rec *rec, const struct dt_key *key, struct thandle *th)
struct osd_object * osd_object_find (const struct lu_env *env, struct dt_object *dt, const struct lu_fid *fid)
Find the osd object for given fid.
static void osd_object_put (const struct lu_env *env, struct osd_object *obj)
Put the osd object once done with it.
static int osd_seq_exists (const struct lu_env *env, struct osd_device *osd, u64 seq)
static int osd_remote_fid (const struct lu_env *env, struct osd_device *osd, const struct lu_fid *fid)
static int osd_dir_insert (const struct lu_env *env, struct dt_object *dt, const struct dt_rec *rec, const struct dt_key *key, struct thandle *th, int ignore_quota)
Inserts (key, value) pair in directory object.
static int osd_declare_dir_delete (const struct lu_env *env, struct dt_object *dt, const struct dt_key *key, struct thandle *th)
static int osd_dir_delete (const struct lu_env *env, struct dt_object *dt, const struct dt_key *key, struct thandle *th)
static struct dt_it * osd_dir_it_init (const struct lu_env *env, struct dt_object *dt, __u32 unused)
static int osd_dir_it_get (const struct lu_env *env, struct dt_it *di, const struct dt_key *key)
Move Iterator to record specified by key.
static void osd_dir_it_put (const struct lu_env *env, struct dt_it *di)
static int osd_index_retrieve_skip_dots (struct osd_zap_it *it, zap_attribute_t *za)
static int osd_dir_it_next (const struct lu_env *env, struct dt_it *di)
to load a directory entry at a time and stored it in iterator's in-memory data structure.
static struct dt_key * osd_dir_it_key (const struct lu_env *env, const struct dt_it *di)
static int osd_dir_it_key_size (const struct lu_env *env, const struct dt_it *di)
static int osd_dir_it_rec (const struct lu_env *env, const struct dt_it *di, struct dt_rec *dtrec, __u32 attr)
static int osd_dir_it_rec_size (const struct lu_env *env, const struct dt_it *di, __u32 attr)
static __u64 osd_dir_it_store (const struct lu_env *env, const struct dt_it *di)
static int osd_dir_it_load (const struct lu_env *env, const struct dt_it *di, __u64 hash)
static int osd_prepare_key_uint64 (struct osd_object *o, __u64 *dst, const struct dt_key *src)
static int osd_index_lookup (const struct lu_env *env, struct dt_object *dt, struct dt_rec *rec, const struct dt_key *key)
static int osd_declare_index_insert (const struct lu_env *env, struct dt_object *dt, const struct dt_rec *rec, const struct dt_key *key, struct thandle *th)
static int osd_index_insert (const struct lu_env *env, struct dt_object *dt, const struct dt_rec *rec, const struct dt_key *key, struct thandle *th, int ignore_quota)
static int osd_declare_index_delete (const struct lu_env *env, struct dt_object *dt, const struct dt_key *key, struct thandle *th)
static int osd_index_delete (const struct lu_env *env, struct dt_object *dt, const struct dt_key *key, struct thandle *th)
static int osd_index_it_get (const struct lu_env *env, struct dt_it *di, const struct dt_key *key)
static int osd_index_it_next (const struct lu_env *env, struct dt_it *di)
static struct dt_key * osd_index_it_key (const struct lu_env *env, const struct dt_it *di)
static int osd_index_it_key_size (const struct lu_env *env, const struct dt_it *di)
static int osd_index_it_rec (const struct lu_env *env, const struct dt_it *di, struct dt_rec *rec, __u32 attr)
static __u64 osd_index_it_store (const struct lu_env *env, const struct dt_it *di)
static int osd_index_it_load (const struct lu_env *env, const struct dt_it *di, __u64 hash)
static struct dt_it * osd_zfs_otable_it_init (const struct lu_env *env, struct dt_object *dt, __u32 attr)
static void osd_zfs_otable_it_fini (const struct lu_env *env, struct dt_it *di)
static int osd_zfs_otable_it_get (const struct lu_env *env, struct dt_it *di, const struct dt_key *key)
static void osd_zfs_otable_it_put (const struct lu_env *env, struct dt_it *di)
static void osd_zfs_otable_prefetch (const struct lu_env *env, struct osd_metadnode_it *it)
static int osd_zfs_otable_it_next (const struct lu_env *env, struct dt_it *di)
static struct dt_key * osd_zfs_otable_it_key (const struct lu_env *env, const struct dt_it *di)
static int osd_zfs_otable_it_key_size (const struct lu_env *env, const struct dt_it *di)
static int osd_zfs_otable_it_rec (const struct lu_env *env, const struct dt_it *di, struct dt_rec *rec, __u32 attr)
static __u64 osd_zfs_otable_it_store (const struct lu_env *env, const struct dt_it *di)
static int osd_zfs_otable_it_load (const struct lu_env *env, const struct dt_it *di, __u64 hash)
static int osd_zfs_otable_it_key_rec (const struct lu_env *env, const struct dt_it *di, void *key_rec)
int osd_index_try (const struct lu_env *env, struct dt_object *dt, const struct dt_index_features *feat)
Variables
struct dt_index_operations osd_dir_ops
static struct dt_index_operations osd_index_ops
struct dt_index_operations osd_zfs_otable_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_OSD
Definition at line 42 of file osd_index.c.
#define OTABLE_PREFETCH 256
Definition at line 1493 of file osd_index.c.
Referenced by osd_zfs_otable_prefetch().
#define zap_hashbits (zc) 48
Definition at line 86 of file osd_index.c.
Referenced by osd_zap_cursor_init_serialized(), and osd_zap_cursor_serialize().
Function Documentation
static int osd_declare_dir_delete (const struct lu_env * env, struct dt_object * dt, const struct dt_key * key, struct thandle * th) [static]
Definition at line 711 of file osd_index.c.
References dt_object_exists(), ENTRY, LASSERT, osd_object::oo_db, osd_dt_obj(), osd_invariant, osd_object_is_zap(), osd_thandle::ot_super, osd_thandle::ot_tx, and RETURN.
static int osd_declare_dir_insert (const struct lu_env * env, struct dt_object * dt, const struct dt_rec * rec, const struct dt_key * key, struct thandle * th) [static]
Definition at line 459 of file osd_index.c.
References ENTRY, LASSERT, osd_object::oo_db, osd_dt_obj(), osd_thandle::ot_super, osd_thandle::ot_tx, and RETURN.
static int osd_declare_index_delete (const struct lu_env * env, struct dt_object * dt, const struct dt_key * key, struct thandle * th) [static]
Definition at line 1250 of file osd_index.c.
References dt_object_exists(), ENTRY, LASSERT, osd_object::oo_db, osd_dt_obj(), osd_invariant, osd_thandle::ot_super, osd_thandle::ot_tx, and RETURN.
static int osd_declare_index_insert (const struct lu_env * env, struct dt_object * dt, const struct dt_rec * rec, const struct dt_key * key, struct thandle * th) [static]
Definition at line 1198 of file osd_index.c.
References ENTRY, LASSERT, osd_object::oo_db, osd_dt_obj(), osd_thandle::ot_super, osd_thandle::ot_tx, and RETURN.
static int osd_dir_delete (const struct lu_env * env, struct dt_object * dt, const struct dt_key * key, struct thandle * th) [static]
Definition at line 739 of file osd_index.c.
References CERROR, ENTRY, LASSERT, name, osd_device::od_os, osd_device::od_svname, osd_object::oo_db, osd_dt_obj(), osd_obj2dev(), osd_object_is_zap(), osd_thandle::ot_super, osd_thandle::ot_tx, RETURN, and unlikely.
static int osd_dir_insert (const struct lu_env * env, struct dt_object * dt, const struct dt_rec * rec, const struct dt_key * key, struct thandle * th, int ignore_quota) [static]
Inserts (key, value) pair in directory object.
Parameters:
dt osd index object
key key for index
rec record reference
th transaction handler
ignore_quota update should not affect quota
Return values:
0 success
-ve failure
Definition at line 610 of file osd_index.c.
References CERROR, CLASSERT, DFID, dt_object::do_lu, dt_object_exists(), ENTRY, lu_fid::f_oid, GOTO, IFTODT, LASSERT, lu_object::lo_header, lu_object_header::loh_attr, luz_direntry::lzd_fid, luz_direntry::lzd_reg, name, OBD_FAIL_CHECK, OBD_FAIL_LFSCK_BAD_PARENT, osd_device::od_os, osd_device::od_svname, osd_object::oo_db, osd_object::oo_dt, osd_dt_obj(), osd_invariant, osd_obj2dev(), osd_object_find(), osd_object_is_zap(), osd_object_put(), osd_object_sa_update(), osd_oti_get(), osd_remote_fid(), osd_thandle::ot_tx, osd_thread_info::oti_zde, PFID, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, RETURN, unlikely, zpl_direntry::zde_dnode, and zpl_direntry::zde_type.
static int osd_dir_it_get (const struct lu_env * env, struct dt_it * di, const struct dt_key * key) [static]
Move Iterator to record specified by key.
Parameters:
di osd iterator
key key for index
Return values:
+ve di points to record with least key not larger than key
0 di points to exact matched key
-ve failure
Definition at line 801 of file osd_index.c.
References ENTRY, GOTO, LASSERT, name, osd_obj_cursor_init_serialized(), osd_zap_it::ozi_obj, osd_zap_it::ozi_pos, osd_zap_it::ozi_zc, and RETURN.
static struct dt_it* osd_dir_it_init (const struct lu_env * env, struct dt_object * dt, __u32 unused) [static, read]
Definition at line 778 of file osd_index.c.
References osd_index_it_init(), osd_zap_it::ozi_pos, and RETURN.
static struct dt_key* osd_dir_it_key (const struct lu_env * env, const struct dt_it * di) [static, read]
Definition at line 927 of file osd_index.c.
References dt_key, ENTRY, osd_oti_get(), osd_thread_info::oti_za, osd_zap_it::ozi_name, osd_zap_it::ozi_pos, osd_zap_it::ozi_zc, and RETURN.
static int osd_dir_it_key_size (const struct lu_env * env, const struct dt_it * di) [static]
Definition at line 950 of file osd_index.c.
References ENTRY, osd_oti_get(), osd_thread_info::oti_za, osd_zap_it::ozi_pos, osd_zap_it::ozi_zc, and RETURN.
static int osd_dir_it_load (const struct lu_env * env, const struct dt_it * di, __u64 hash) [static]
Definition at line 1105 of file osd_index.c.
References ENTRY, osd_index_retrieve_skip_dots(), osd_obj_cursor_init_serialized(), osd_oti_get(), osd_thread_info::oti_za, osd_zap_it::ozi_obj, osd_zap_it::ozi_pos, osd_zap_it::ozi_zc, and RETURN.
static int osd_dir_it_next (const struct lu_env * env, struct dt_it * di) [static]
to load a directory entry at a time and stored it in iterator's in-memory data structure.
Parameters:
di,struct osd_it_ea, iterator's in memory structure
Return values:
+ve,iterator reached to end
0,iterator not reached to end
-ve,on error
Definition at line 888 of file osd_index.c.
References CLASSERT, ENTRY, osd_index_retrieve_skip_dots(), osd_oti_get(), osd_thread_info::oti_za, osd_zap_it::ozi_name, osd_zap_it::ozi_pos, osd_zap_it::ozi_zc, and RETURN.
static void osd_dir_it_put (const struct lu_env * env, struct dt_it * di) [static]
Definition at line 843 of file osd_index.c.
static int osd_dir_it_rec (const struct lu_env * env, const struct dt_it * di, struct dt_rec * dtrec, __u32 attr) [static]
Definition at line 970 of file osd_index.c.
References CERROR, cpu_to_le16, cpu_to_le64, dt_object::do_lu, ENTRY, GOTO, IFTODT, LASSERT, lu_dirent::lde_attrs, lu_dirent::lde_fid, lu_dirent::lde_hash, lu_dirent::lde_name, lu_dirent::lde_namelen, lu_dirent::lde_reclen, lu_dirent_calc_size(), lu_object_fid(), LUDA_FID, luz_direntry::lzd_fid, luz_direntry::lzd_reg, osd_device::od_svname, osd_object::oo_dt, osd_find_parent_fid(), osd_it_append_attrs(), osd_obj2dev(), osd_oti_get(), osd_zap_cursor_serialize(), osd_thread_info::oti_za, osd_thread_info::oti_zde, osd_zap_it::ozi_obj, osd_zap_it::ozi_pos, osd_zap_it::ozi_zc, RETURN, unlikely, and zpl_direntry::zde_type.
static int osd_dir_it_rec_size (const struct lu_env * env, const struct dt_it * di, __u32 attr) [static]
Definition at line 1046 of file osd_index.c.
References CERROR, ENTRY, lu_dirent_calc_size(), osd_device::od_svname, osd_obj2dev(), osd_oti_get(), osd_thread_info::oti_za, osd_zap_it::ozi_obj, osd_zap_it::ozi_pos, osd_zap_it::ozi_zc, RETURN, and unlikely.
static __u64 osd_dir_it_store (const struct lu_env * env, const struct dt_it * di) [static]
Definition at line 1085 of file osd_index.c.
References __u64, ENTRY, osd_zap_cursor_serialize(), osd_zap_it::ozi_pos, osd_zap_it::ozi_zc, and RETURN.
static int osd_dir_lookup (const struct lu_env * env, struct dt_object * dt, struct dt_rec * rec, const struct dt_key * key) [static]
Definition at line 418 of file osd_index.c.
References dt_object::do_lu, ENTRY, fid_is_sane(), LASSERT, likely, lu_object_fid(), luz_direntry::lzd_fid, luz_direntry::lzd_reg, name, osd_device::od_os, osd_object::oo_db, osd_dt_obj(), osd_find_parent_fid(), osd_get_fid_by_oid(), osd_obj2dev(), osd_object_is_zap(), osd_oti_get(), osd_thread_info::oti_zde, RETURN, and zpl_direntry::zde_dnode.
static int osd_find_parent_by_dnode (const struct lu_env * env, struct dt_object * o, struct lu_fid * fid) [static]
Definition at line 324 of file osd_index.c.
References ENTRY, LASSERT, osd_device::od_os, osd_dt_obj(), osd_get_fid_by_oid(), osd_obj2dev(), RETURN, and sa_lookup().
Referenced by osd_find_parent_fid().
static int osd_find_parent_fid (const struct lu_env * env, struct dt_object * o, struct lu_fid * fid) [static]
Definition at line 349 of file osd_index.c.
References __swab32, __swab64, CERROR, DFID, ENTRY, fid_be_to_cpu(), GOTO, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, link_ea_entry::lee_parent_fid, link_ea_header::leh_len, link_ea_header::leh_magic, link_ea_header::leh_reccount, LINK_EA_MAGIC, LU_BUF_NULL, lu_fid_eq(), OBD_ALLOC, OBD_FREE, osd_find_parent_by_dnode(), osd_oti_get(), osd_xattr_get(), osd_thread_info::oti_buf, PFID, RETURN, unlikely, and XATTR_NAME_LINK.
Referenced by osd_dir_it_rec(), and osd_dir_lookup().
static int osd_get_fid_by_oid (const struct lu_env * env, struct osd_device * osd, uint64_t oid, struct lu_fid * fid) [static]
Get the object's FID from its LMA EA.
Parameters:
[in] env pointer to the thread context
[in] osd pointer to the OSD device
[in] oid the object's local identifier
[out] fid the buffer to hold the object's FID
Return values:
0 for success
negative error number on failure
Definition at line 242 of file osd_index.c.
References __osd_xattr_get_large(), __osd_xattr_load(), buf, CFS_FAIL_CHECK, CWARN, ENTRY, GOTO, lustre_mdt_attrs::lma_incompat, LMA_INCOMPAT_SUPP, lustre_mdt_attrs::lma_self_fid, LPX64, lustre_lma_swab(), OBD_FAIL_OSD_LMA_INCOMPAT, osd_device::od_os, osd_device::od_svname, osd_oti_get(), osd_thread_info::oti_buf, sa_lookup(), size, unlikely, and XATTR_NAME_LMA.
Referenced by osd_dir_lookup(), and osd_find_parent_by_dnode().
static int osd_index_delete (const struct lu_env * env, struct dt_object * dt, const struct dt_key * key, struct thandle * th) [static]
Definition at line 1270 of file osd_index.c.
References __u64, ENTRY, LASSERT, osd_device::od_os, osd_object::oo_db, osd_dt_obj(), osd_obj2dev(), osd_oti_get(), osd_prepare_key_uint64(), osd_thandle::ot_super, osd_thandle::ot_tx, osd_thread_info::oti_key64, and RETURN.
static int osd_index_insert (const struct lu_env * env, struct dt_object * dt, const struct dt_rec * rec, const struct dt_key * key, struct thandle * th, int ignore_quota) [static]
Definition at line 1223 of file osd_index.c.
References __u64, dt_object_exists(), ENTRY, LASSERT, osd_device::od_os, osd_object::oo_db, osd_object::oo_recsize, osd_object::oo_recusize, osd_dt_obj(), osd_invariant, osd_obj2dev(), osd_oti_get(), osd_prepare_key_uint64(), osd_thandle::ot_super, osd_thandle::ot_tx, osd_thread_info::oti_key64, and RETURN.
static void osd_index_it_fini (const struct lu_env * env, struct dt_it * di) [static]
Definition at line 188 of file osd_index.c.
References dt_object::do_lu, ENTRY, EXIT, LASSERT, lu_object_put(), OBD_SLAB_FREE_PTR, osd_object::oo_dt, osd_zap_cursor_fini(), osd_zapit_cachep, osd_zap_it::ozi_obj, and osd_zap_it::ozi_zc.
static int osd_index_it_get (const struct lu_env * env, struct dt_it * di, const struct dt_key * key) [static]
Definition at line 1292 of file osd_index.c.
References __u64, CERROR, ENTRY, LASSERT, LPX64, osd_device::od_os, osd_object::oo_db, osd_obj2dev(), osd_zap_it::ozi_obj, osd_zap_it::ozi_reset, osd_zap_it::ozi_zc, and RETURN.
static struct dt_it* osd_index_it_init (const struct lu_env * env, struct dt_object * dt, __u32 unused) [static, read]
Definition at line 152 of file osd_index.c.
References dt_object::do_lu, ENTRY, LASSERT, lu_object_exists, lu_object_get(), OBD_SLAB_ALLOC_PTR_GFP, OBD_SLAB_FREE_PTR, osd_object::oo_db, osd_object::oo_destroyed, osd_dt_obj(), osd_obj_cursor_init(), osd_object_is_zap(), osd_oti_get(), osd_zapit_cachep, osd_zap_it::ozi_obj, osd_zap_it::ozi_reset, osd_zap_it::ozi_zc, and RETURN.
Referenced by osd_dir_it_init().
static struct dt_key* osd_index_it_key (const struct lu_env * env, const struct dt_it * di) [static, read]
Definition at line 1341 of file osd_index.c.
References dt_key, ENTRY, osd_object::oo_keysize, osd_oti_get(), osd_thread_info::oti_za, osd_zap_it::ozi_key, osd_zap_it::ozi_obj, osd_zap_it::ozi_reset, osd_zap_it::ozi_zc, and RETURN.
static int osd_index_it_key_size (const struct lu_env * env, const struct dt_it * di) [static]
Definition at line 1361 of file osd_index.c.
References osd_object::oo_keysize, osd_zap_it::ozi_obj, and RETURN.
static int osd_index_it_load (const struct lu_env * env, const struct dt_it * di, __u64 hash) [static]
Definition at line 1402 of file osd_index.c.
References ENTRY, osd_device::od_os, osd_object::oo_db, osd_obj2dev(), osd_oti_get(), osd_thread_info::oti_za, osd_zap_it::ozi_obj, osd_zap_it::ozi_reset, osd_zap_it::ozi_zc, and RETURN.
static int osd_index_it_next (const struct lu_env * env, struct dt_it * di) [static]
Definition at line 1317 of file osd_index.c.
References ENTRY, osd_oti_get(), osd_thread_info::oti_za, osd_zap_it::ozi_reset, osd_zap_it::ozi_zc, and RETURN.
static void osd_index_it_put (const struct lu_env * env, struct dt_it * di) [static]
Definition at line 207 of file osd_index.c.
static int osd_index_it_rec (const struct lu_env * env, const struct dt_it * di, struct dt_rec * rec, __u32 attr) [static]
Definition at line 1369 of file osd_index.c.
References __u64, dt_key, ENTRY, osd_device::od_os, osd_object::oo_db, osd_object::oo_recsize, osd_object::oo_recusize, osd_obj2dev(), osd_oti_get(), osd_prepare_key_uint64(), osd_thread_info::oti_key64, osd_thread_info::oti_za, osd_zap_it::ozi_obj, osd_zap_it::ozi_reset, osd_zap_it::ozi_zc, and RETURN.
static __u64 osd_index_it_store (const struct lu_env * env, const struct dt_it * di) [static]
Definition at line 1393 of file osd_index.c.
References __u64, osd_zap_it::ozi_reset, osd_zap_it::ozi_zc, and RETURN.
static int osd_index_lookup (const struct lu_env * env, struct dt_object * dt, struct dt_rec * rec, const struct dt_key * key) [static]
Definition at line 1181 of file osd_index.c.
References __u64, ENTRY, osd_device::od_os, osd_object::oo_db, osd_object::oo_recsize, osd_object::oo_recusize, osd_dt_obj(), osd_obj2dev(), osd_oti_get(), osd_prepare_key_uint64(), osd_thread_info::oti_key64, and RETURN.
static int osd_index_retrieve_skip_dots (struct osd_zap_it * it, zap_attribute_t * za) [static]
Definition at line 854 of file osd_index.c.
References osd_zap_it::ozi_zc, and unlikely.
Referenced by osd_dir_it_load(), and osd_dir_it_next().
int osd_index_try (const struct lu_env * env, struct dt_object * dt, const struct dt_index_features * feat)
Definition at line 1654 of file osd_index.c.
References dt_index_features::dif_flags, dt_index_features::dif_keysize_max, dt_index_features::dif_keysize_min, dt_index_features::dif_recsize_max, dt_index_features::dif_recsize_min, dt_object::do_index_ops, dt_object::do_lu, dt_acct_features, dt_directory_features, DT_IND_RANGE, DT_IND_UPDATE, dt_object_exists(), dt_otable_features, ENTRY, fid_is_acct(), GOTO, LASSERT, likely, lu_object_fid(), osd_object::oo_db, osd_object::oo_guard, osd_object::oo_keysize, osd_object::oo_recsize, osd_object::oo_recusize, osd_acct_index_ops, osd_dt_obj(), osd_object_is_zap(), RETURN, and unlikely.
static void osd_it_append_attrs (struct lu_dirent * ent, __u32 attr, int len, __u16 type) [inline, static]
Definition at line 213 of file osd_index.c.
References cpu_to_le16, cpu_to_le32, DTTOIF, lu_dirent::lde_attrs, lu_dirent::lde_name, luda_type::lt_type, and LUDA_TYPE.
Referenced by osd_dir_it_rec().
static int osd_obj_cursor_init (zap_cursor_t ** zc, struct osd_object * o, uint64_t dirhash) [inline, static]
Definition at line 145 of file osd_index.c.
References osd_device::od_os, osd_object::oo_db, osd_obj2dev(), and osd_zap_cursor_init().
Referenced by osd_index_it_init().
static void osd_obj_cursor_init_serialized (zap_cursor_t * zc, struct osd_object * o, uint64_t dirhash) [inline, static]
Definition at line 136 of file osd_index.c.
References osd_device::od_os, osd_object::oo_db, osd_obj2dev(), and osd_zap_cursor_init_serialized().
Referenced by osd_dir_it_get(), and osd_dir_it_load().
struct osd_object* osd_object_find (const struct lu_env * env, struct dt_object * dt, const struct lu_fid * fid) [read]
Find the osd object for given fid.
Parameters:
fid need to find the osd object having this fid
Return values:
osd_object on success
-ve on error
Definition at line 493 of file osd_index.c.
References CERROR, D_ERROR, DFID, dt_object::do_lu, lu_device::ld_type, lu_object::lo_dev, lu_object::lo_header, LU_OBJECT_DEBUG, lu_object_exists, lu_object_find_at(), lu_object_locate(), lu_object_put(), osd_dev(), osd_obj(), and PFID.
Referenced by osd_dir_insert().
static int osd_object_is_zap (dmu_buf_t * db) [inline, static]
Definition at line 68 of file osd_index.c.
Referenced by osd_declare_dir_delete(), osd_dir_delete(), osd_dir_insert(), osd_dir_lookup(), osd_index_it_init(), and osd_index_try().
static void osd_object_put (const struct lu_env * env, struct osd_object * obj) [inline, static]
Put the osd object once done with it.
Parameters:
obj osd object that needs to be put
Definition at line 547 of file osd_index.c.
References dt_object::do_lu, lu_object_put(), and osd_object::oo_dt.
Referenced by osd_dir_insert().
static int osd_prepare_key_uint64 (struct osd_object * o, __u64 * dst, const struct dt_key * src) [static]
Definition at line 1160 of file osd_index.c.
References __u64, LASSERT, osd_object::oo_keysize, size, and unlikely.
Referenced by osd_index_delete(), osd_index_insert(), osd_index_it_rec(), and osd_index_lookup().
static int osd_remote_fid (const struct lu_env * env, struct osd_device * osd, const struct lu_fid * fid) [static]
Definition at line 575 of file osd_index.c.
References ENTRY, fid_seq_in_fldb(), osd_seq_exists(), osd_seq_site(), RETURN, seq_server_site::ss_server_fld, and unlikely.
Referenced by osd_dir_insert().
static int osd_seq_exists (const struct lu_env * env, struct osd_device * osd, u64 seq) [static]
Definition at line 553 of file osd_index.c.
References CERROR, ENTRY, LASSERT, LPX64, lu_seq_range::lsr_index, osd_fld_lookup(), osd_name(), osd_oti_get(), osd_seq_site(), osd_thread_info::oti_seq_range, RETURN, seq_server_site::ss_node_id, and seq_server_site::ss_server_fld.
Referenced by osd_remote_fid().
void osd_zap_cursor_fini (zap_cursor_t * zc)
Definition at line 130 of file osd_index.c.
References OBD_FREE_PTR.
Referenced by osd_declare_xattrs_destroy(), osd_index_it_fini(), osd_it_acct_fini(), osd_it_acct_load(), osd_xattr_list(), and osd_xattrs_destroy().
int osd_zap_cursor_init (zap_cursor_t ** zc, struct objset * os, uint64_t id, uint64_t dirhash)
Definition at line 115 of file osd_index.c.
References OBD_ALLOC_PTR, osd_zap_cursor_init_serialized(), and unlikely.
Referenced by osd_declare_xattrs_destroy(), osd_it_acct_init(), osd_it_acct_load(), osd_obj_cursor_init(), osd_xattr_list(), and osd_xattrs_destroy().
void osd_zap_cursor_init_serialized (zap_cursor_t * zc, struct objset * os, uint64_t id, uint64_t dirhash)
Definition at line 106 of file osd_index.c.
References zap_hashbits.
Referenced by osd_obj_cursor_init_serialized(), and osd_zap_cursor_init().
uint64_t osd_zap_cursor_serialize (zap_cursor_t * zc)
Definition at line 98 of file osd_index.c.
References zap_hashbits.
Referenced by osd_dir_it_rec(), osd_dir_it_store(), and osd_it_acct_store().
static void osd_zfs_otable_it_fini (const struct lu_env * env, struct dt_it * di) [static]
Definition at line 1476 of file osd_index.c.
References OBD_FREE_PTR.
static int osd_zfs_otable_it_get (const struct lu_env * env, struct dt_it * di, const struct dt_key * key) [static]
Definition at line 1483 of file osd_index.c.
static struct dt_it* osd_zfs_otable_it_init (const struct lu_env * env, struct dt_object * dt, __u32 attr) [static, read]
Definition at line 1455 of file osd_index.c.
References dt_object::do_lu, ENTRY, lu_object::lo_dev, osd_metadnode_it::mit_dev, OBD_ALLOC_PTR, osd_device::od_os, osd_dev(), RETURN, and unlikely.
static struct dt_key* osd_zfs_otable_it_key (const struct lu_env * env, const struct dt_it * di) [static, read]
Definition at line 1586 of file osd_index.c.
static int osd_zfs_otable_it_key_rec (const struct lu_env * env, const struct dt_it * di, void * key_rec) [static]
Definition at line 1632 of file osd_index.c.
static int osd_zfs_otable_it_key_size (const struct lu_env * env, const struct dt_it * di) [static]
Definition at line 1592 of file osd_index.c.
References __u64.
static int osd_zfs_otable_it_load (const struct lu_env * env, const struct dt_it * di, __u64 hash) [static]
Definition at line 1620 of file osd_index.c.
References osd_metadnode_it::mit_pos, osd_metadnode_it::mit_prefetched, osd_metadnode_it::mit_prefetched_dnode, and osd_zfs_otable_it_next().
static int osd_zfs_otable_it_next (const struct lu_env * env, struct dt_it * di) [static]
Definition at line 1527 of file osd_index.c.
References __osd_xattr_load(), __u64, CDEBUG, D_OTHER, DFID, GOTO, LASSERT, likely, lustre_mdt_attrs::lma_self_fid, lustre_lma_swab(), osd_metadnode_it::mit_dev, osd_metadnode_it::mit_fid, osd_metadnode_it::mit_pos, osd_metadnode_it::mit_prefetched, osd_device::od_os, osd_zfs_otable_prefetch(), PFID, unlikely, and XATTR_NAME_LMA.
Referenced by osd_zfs_otable_it_load().
static void osd_zfs_otable_it_put (const struct lu_env * env, struct dt_it * di) [static]
Definition at line 1489 of file osd_index.c.
static int osd_zfs_otable_it_rec (const struct lu_env * env, const struct dt_it * di, struct dt_rec * rec, __u32 attr) [static]
Definition at line 1598 of file osd_index.c.
References ENTRY, osd_metadnode_it::mit_fid, and RETURN.
static __u64 osd_zfs_otable_it_store (const struct lu_env * env, const struct dt_it * di) [static]
Definition at line 1612 of file osd_index.c.
References osd_metadnode_it::mit_pos.
static void osd_zfs_otable_prefetch (const struct lu_env * env, struct osd_metadnode_it * it) [static]
Definition at line 1495 of file osd_index.c.
References osd_metadnode_it::mit_dev, osd_metadnode_it::mit_pos, osd_metadnode_it::mit_prefetched, osd_metadnode_it::mit_prefetched_dnode, osd_device::od_os, OTABLE_PREFETCH, and unlikely.
Referenced by osd_zfs_otable_it_next().
Variable Documentation
struct dt_index_operations osd_dir_ops
Initial value:
 {
        .dio_lookup         = osd_dir_lookup,
        .dio_declare_insert = osd_declare_dir_insert,
        .dio_insert         = osd_dir_insert,
        .dio_declare_delete = osd_declare_dir_delete,
        .dio_delete         = osd_dir_delete,
        .dio_it     = {
                .init     = osd_dir_it_init,
                .fini     = osd_index_it_fini,
                .get      = osd_dir_it_get,
                .put      = osd_dir_it_put,
                .next     = osd_dir_it_next,
                .key      = osd_dir_it_key,
                .key_size = osd_dir_it_key_size,
                .rec      = osd_dir_it_rec,
                .rec_size = osd_dir_it_rec_size,
                .store    = osd_dir_it_store,
                .load     = osd_dir_it_load
        }
}
Definition at line 1134 of file osd_index.c.
Referenced by osd_declare_object_create().
struct dt_index_operations osd_index_ops [static]
Initial value:
 {
        .dio_lookup             = osd_index_lookup,
        .dio_declare_insert     = osd_declare_index_insert,
        .dio_insert             = osd_index_insert,
        .dio_declare_delete     = osd_declare_index_delete,
        .dio_delete             = osd_index_delete,
        .dio_it = {
                .init           = osd_index_it_init,
                .fini           = osd_index_it_fini,
                .get            = osd_index_it_get,
                .put            = osd_index_it_put,
                .next           = osd_index_it_next,
                .key            = osd_index_it_key,
                .key_size       = osd_index_it_key_size,
                .rec            = osd_index_it_rec,
                .store          = osd_index_it_store,
                .load           = osd_index_it_load
        }
}
Definition at line 1427 of file osd_index.c.
struct dt_index_operations osd_zfs_otable_ops
Initial value:
 {
        .dio_it = {
                .init     = osd_zfs_otable_it_init,
                .fini     = osd_zfs_otable_it_fini,
                .get      = osd_zfs_otable_it_get,
                .put      = osd_zfs_otable_it_put,
                .next     = osd_zfs_otable_it_next,
                .key      = osd_zfs_otable_it_key,
                .key_size = osd_zfs_otable_it_key_size,
                .rec      = osd_zfs_otable_it_rec,
                .store    = osd_zfs_otable_it_store,
                .load     = osd_zfs_otable_it_load,
                .key_rec  = osd_zfs_otable_it_key_rec,
        }
}
Definition at line 1638 of file osd_index.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.