Lustre: lustre/osd-ldiskfs/osd_scrub.c File Reference
lustre/osd-ldiskfs/osd_scrub.c File Reference
#include <linux/kthread.h>
#include <lustre/lustre_idl.h>
#include <lustre_disk.h>
#include <dt_object.h>
#include <linux/xattr.h>
#include "osd_internal.h"
#include "osd_oi.h"
#include "osd_scrub.h"
Data Structures
struct osd_iit_param
struct osd_lf_map
struct osd_ios_item
struct osd_ios_filldir_buf
Defines
#define DEBUG_SUBSYSTEM S_LFSCK
#define HALF_SEC msecs_to_jiffies(MSEC_PER_SEC >> 1)
#define OSD_OTABLE_MAX_HASH 0x00000000ffffffffULL
#define SCRUB_NEXT_BREAK 1
#define SCRUB_NEXT_CONTINUE 2
#define SCRUB_NEXT_EXIT 3
#define SCRUB_NEXT_WAIT 4
#define SCRUB_NEXT_CRASH 5
#define SCRUB_NEXT_FATAL 6
#define SCRUB_NEXT_NOSCRUB 7
#define SCRUB_NEXT_NOLMA 8
#define SCRUB_NEXT_OSTOBJ 9
#define SCRUB_NEXT_OSTOBJ_OLD 10
#define SCRUB_IT_ALL 1
#define SCRUB_IT_CRASH 2
#define SCRUB_BAD_OIMAP_DECAY_INTERVAL 60
Typedefs
typedef int(* osd_iit_next_policy)(struct osd_thread_info *info, struct osd_device *dev, struct osd_iit_param *param, struct osd_idmap_cache **oic, const bool noslot)
typedef int(* osd_iit_exec_policy)(struct osd_thread_info *info, struct osd_device *dev, struct osd_iit_param *param, struct osd_idmap_cache *oic, bool *noslot, int rc)
typedef int(* scandir_t)(struct osd_thread_info *, struct osd_device *, struct dentry *, filldir_t filldir)
Enumerations
enum osd_lf_flags {
OLF_SCAN_SUBITEMS = 0x0001, OLF_HIDE_FID = 0x0002, OLF_SHOW_NAME = 0x0004, OLF_NO_OI = 0x0008,
OLF_IDX_IN_FID = 0x0010
}
Functions
static struct osd_device * osd_scrub2dev (struct osd_scrub *scrub)
static struct super_block * osd_scrub2sb (struct osd_scrub *scrub)
static int osd_scrub_has_window (struct osd_scrub *scrub, struct osd_otable_cache *ooc)
static const char * osd_scrub2name (struct osd_scrub *scrub)
static int osd_scrub_refresh_mapping (struct osd_thread_info *info, struct osd_device *dev, const struct lu_fid *fid, const struct osd_inode_id *id, int ops, bool force, enum oi_check_flags flags)
update/insert/delete the specified OI mapping () according to the ops
static void osd_scrub_file_to_cpu (struct scrub_file *des, struct scrub_file *src)
static void osd_scrub_file_to_le (struct scrub_file *des, struct scrub_file *src)
static void osd_scrub_file_init (struct osd_scrub *scrub, __u8 *uuid)
void osd_scrub_file_reset (struct osd_scrub *scrub, __u8 *uuid, __u64 flags)
static int osd_scrub_file_load (struct osd_scrub *scrub)
int osd_scrub_file_store (struct osd_scrub *scrub)
static int osd_scrub_convert_ff (struct osd_thread_info *info, struct osd_device *dev, struct inode *inode, const struct lu_fid *fid)
static int osd_scrub_check_update (struct osd_thread_info *info, struct osd_device *dev, struct osd_idmap_cache *oic, int val)
static int osd_scrub_prep (struct osd_device *dev)
static int osd_scrub_checkpoint (struct osd_scrub *scrub)
static int osd_scrub_post (struct osd_scrub *scrub, int result)
static int osd_iit_next (struct osd_iit_param *param, __u32 *pos)
static int osd_scrub_check_local_fldb (struct osd_thread_info *info, struct osd_device *dev, struct lu_fid *fid)
static int osd_scrub_get_fid (struct osd_thread_info *info, struct osd_device *dev, struct inode *inode, struct lu_fid *fid, bool scrub)
static int osd_iit_iget (struct osd_thread_info *info, struct osd_device *dev, struct lu_fid *fid, struct osd_inode_id *lid, __u32 pos, struct super_block *sb, bool scrub)
static int osd_scrub_next (struct osd_thread_info *info, struct osd_device *dev, struct osd_iit_param *param, struct osd_idmap_cache **oic, const bool noslot)
static int osd_preload_next (struct osd_thread_info *info, struct osd_device *dev, struct osd_iit_param *param, struct osd_idmap_cache **oic, const bool noslot)
static int osd_scrub_wakeup (struct osd_scrub *scrub, struct osd_otable_it *it)
static int osd_scrub_exec (struct osd_thread_info *info, struct osd_device *dev, struct osd_iit_param *param, struct osd_idmap_cache *oic, bool *noslot, int rc)
static int osd_preload_exec (struct osd_thread_info *info, struct osd_device *dev, struct osd_iit_param *param, struct osd_idmap_cache *oic, bool *noslot, int rc)
static void osd_scrub_join (struct osd_device *dev, __u32 flags, bool inconsistent)
static int osd_inode_iteration (struct osd_thread_info *info, struct osd_device *dev, __u32 max, bool preload)
static int osd_otable_it_preload (const struct lu_env *env, struct osd_otable_it *it)
static int osd_scrub_main (void *args)
static int osd_ios_varfid_fill (void *buf, const char *name, int namelen, loff_t offset, __u64 ino, unsigned d_type)
static int osd_ios_lf_fill (void *buf, const char *name, int namelen, loff_t offset, __u64 ino, unsigned d_type)
It scans the /lost+found, and for the OST-object (with filter_fid or filter_fid_old), move them back to its proper /O/<seq>/d<x>.
static int osd_ios_dl_fill (void *buf, const char *name, int namelen, loff_t offset, __u64 ino, unsigned d_type)
static int osd_ios_uld_fill (void *buf, const char *name, int namelen, loff_t offset, __u64 ino, unsigned d_type)
static int osd_ios_general_scan (struct osd_thread_info *info, struct osd_device *dev, struct dentry *dentry, filldir_t filldir)
static int osd_ios_ROOT_scan (struct osd_thread_info *info, struct osd_device *dev, struct dentry *dentry, filldir_t filldir)
static int osd_ios_OBJECTS_scan (struct osd_thread_info *info, struct osd_device *dev, struct dentry *dentry, filldir_t filldir)
static struct dentry * osd_ios_lookup_one_len (const char *name, struct dentry *parent, int namelen)
static int osd_ios_new_item (struct osd_device *dev, struct dentry *dentry, scandir_t scandir, filldir_t filldir)
static int osd_ios_scan_one (struct osd_thread_info *info, struct osd_device *dev, struct inode *inode, const struct lu_fid *fid, int flags)
osd_ios_scan_one() - check/fix LMA FID and OI entry for one inode
static int osd_ios_root_fill (void *buf, const char *name, int namelen, loff_t offset, __u64 ino, unsigned d_type)
static int osd_initial_OI_scrub (struct osd_thread_info *info, struct osd_device *dev)
char * osd_lf_fid2name (const struct lu_fid *fid)
static int do_osd_scrub_start (struct osd_device *dev, __u32 flags)
int osd_scrub_start (struct osd_device *dev, __u32 flags)
static void do_osd_scrub_stop (struct osd_scrub *scrub)
static void osd_scrub_stop (struct osd_device *dev)
int osd_scrub_setup (const struct lu_env *env, struct osd_device *dev)
void osd_scrub_cleanup (const struct lu_env *env, struct osd_device *dev)
static struct dt_it * osd_otable_it_init (const struct lu_env *env, struct dt_object *dt, __u32 attr)
static void osd_otable_it_fini (const struct lu_env *env, struct dt_it *di)
static int osd_otable_it_get (const struct lu_env *env, struct dt_it *di, const struct dt_key *key)
static void osd_otable_it_put (const struct lu_env *env, struct dt_it *di)
static int osd_otable_it_wakeup (struct osd_scrub *scrub, struct osd_otable_it *it)
static int osd_otable_it_next (const struct lu_env *env, struct dt_it *di)
static struct dt_key * osd_otable_it_key (const struct lu_env *env, const struct dt_it *di)
static int osd_otable_it_key_size (const struct lu_env *env, const struct dt_it *di)
static int osd_otable_it_rec (const struct lu_env *env, const struct dt_it *di, struct dt_rec *rec, __u32 attr)
static __u64 osd_otable_it_store (const struct lu_env *env, const struct dt_it *di)
static int osd_otable_it_load (const struct lu_env *env, const struct dt_it *di, __u64 hash)
Set the OSD layer iteration start position as the specified hash.
static int osd_otable_it_key_rec (const struct lu_env *env, const struct dt_it *di, void *key_rec)
int osd_oii_insert (struct osd_device *dev, struct osd_idmap_cache *oic, int insert)
int osd_oii_lookup (struct osd_device *dev, const struct lu_fid *fid, struct osd_inode_id *id)
static void scrub_bits_dump (struct seq_file *m, int bits, const char *names[], const char *prefix)
static void scrub_time_dump (struct seq_file *m, __u64 time, const char *prefix)
static void scrub_pos_dump (struct seq_file *m, __u64 pos, const char *prefix)
int osd_scrub_dump (struct seq_file *m, struct osd_device *dev)
Variables
static struct osd_lf_map osd_lf_maps []
static struct osd_lf_map osd_dl_maps []
static const char osd_scrub_name [] = "OI_scrub"
struct dt_index_operations osd_otable_ops
static const char * scrub_status_names []
static const char * scrub_flags_names []
static const char * scrub_param_names []
Define Documentation
#define DEBUG_SUBSYSTEM S_LFSCK
Definition at line 38 of file osd_scrub.c.
#define HALF_SEC msecs_to_jiffies(MSEC_PER_SEC >> 1)
Definition at line 50 of file osd_scrub.c.
#define OSD_OTABLE_MAX_HASH 0x00000000ffffffffULL
Definition at line 52 of file osd_scrub.c.
Referenced by osd_otable_it_load().
#define SCRUB_BAD_OIMAP_DECAY_INTERVAL 60
Definition at line 2933 of file osd_scrub.c.
Referenced by osd_oii_insert().
#define SCRUB_IT_ALL 1
Definition at line 1188 of file osd_scrub.c.
Referenced by osd_inode_iteration(), and osd_otable_it_preload().
#define SCRUB_IT_CRASH 2
Definition at line 1189 of file osd_scrub.c.
Referenced by osd_inode_iteration(), and osd_scrub_main().
#define SCRUB_NEXT_BREAK 1
Definition at line 54 of file osd_scrub.c.
Referenced by osd_iit_next(), and osd_inode_iteration().
#define SCRUB_NEXT_CONTINUE 2
Definition at line 55 of file osd_scrub.c.
Referenced by osd_iit_iget(), osd_scrub_exec(), and osd_scrub_get_fid().
#define SCRUB_NEXT_CRASH 5
Definition at line 58 of file osd_scrub.c.
Referenced by osd_inode_iteration(), and osd_scrub_next().
#define SCRUB_NEXT_EXIT 3
Definition at line 56 of file osd_scrub.c.
Referenced by osd_inode_iteration(), osd_preload_next(), and osd_scrub_next().
#define SCRUB_NEXT_FATAL 6
Definition at line 59 of file osd_scrub.c.
Referenced by osd_inode_iteration(), and osd_scrub_next().
#define SCRUB_NEXT_NOLMA 8
Definition at line 61 of file osd_scrub.c.
Referenced by osd_scrub_check_update(), and osd_scrub_get_fid().
#define SCRUB_NEXT_NOSCRUB 7
Definition at line 60 of file osd_scrub.c.
Referenced by osd_iit_iget(), and osd_scrub_exec().
#define SCRUB_NEXT_OSTOBJ 9
Definition at line 62 of file osd_scrub.c.
Referenced by osd_ios_lf_fill(), osd_scrub_check_update(), and osd_scrub_get_fid().
#define SCRUB_NEXT_OSTOBJ_OLD 10
Definition at line 63 of file osd_scrub.c.
Referenced by osd_ios_lf_fill(), osd_scrub_check_local_fldb(), osd_scrub_check_update(), and osd_scrub_get_fid().
#define SCRUB_NEXT_WAIT 4
Definition at line 57 of file osd_scrub.c.
Referenced by osd_inode_iteration(), osd_scrub_exec(), and osd_scrub_next().
Typedef Documentation
typedef int(* osd_iit_exec_policy)(struct osd_thread_info *info, struct osd_device *dev, struct osd_iit_param *param, struct osd_idmap_cache *oic, bool *noslot, int rc)
Definition at line 816 of file osd_scrub.c.
typedef int(* osd_iit_next_policy)(struct osd_thread_info *info, struct osd_device *dev, struct osd_iit_param *param, struct osd_idmap_cache **oic, const bool noslot)
Definition at line 810 of file osd_scrub.c.
typedef int(* scandir_t)(struct osd_thread_info *, struct osd_device *, struct dentry *, filldir_t filldir)
Definition at line 1543 of file osd_scrub.c.
Enumeration Type Documentation
enum osd_lf_flags
Enumerator:
OLF_SCAN_SUBITEMS
OLF_HIDE_FID
OLF_SHOW_NAME
OLF_NO_OI
OLF_IDX_IN_FID
Definition at line 1581 of file osd_scrub.c.
Function Documentation
static int do_osd_scrub_start (struct osd_device * dev, __u32 flags) [static]
Definition at line 2377 of file osd_scrub.c.
References CERROR, ENTRY, l_wait_event, osd_device::od_scrub, osd_scrub::os_file, osd_scrub::os_lock, osd_scrub::os_start_flags, osd_scrub::os_thread, osd_scrub2name(), osd_scrub_join(), osd_scrub_main(), RETURN, SF_AUTO, scrub_file::sf_flags, scrub_file::sf_status, SS_AUTO_FULL, SS_AUTO_PARTIAL, SS_CLEAR_DRYRUN, SS_CLEAR_FAILOUT, SS_COMPLETED, SS_RESET, SS_SET_DRYRUN, SS_SET_FAILOUT, ptlrpc_thread::t_ctl_waitq, thread, thread_is_running(), thread_is_stopped(), thread_is_stopping(), thread_set_flags(), and unlikely.
Referenced by osd_otable_it_init(), and osd_scrub_start().
static void do_osd_scrub_stop (struct osd_scrub * scrub) [static]
Definition at line 2455 of file osd_scrub.c.
References l_wait_event, osd_scrub::os_lock, osd_scrub::os_thread, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, thread, thread_is_init(), thread_is_stopped(), and thread_set_flags().
Referenced by osd_otable_it_fini(), and osd_scrub_stop().
static int osd_iit_iget (struct osd_thread_info * info, struct osd_device * dev, struct lu_fid * fid, struct osd_inode_id * lid, __u32 pos, struct super_block * sb, bool scrub) [static]
Definition at line 940 of file osd_scrub.c.
References CDEBUG, D_LFSCK, ENTRY, GOTO, LDISKFS_STATE_LUSTRE_NOSCRUB, osd_id_gen(), osd_iget(), osd_is_ea_inode(), OSD_OII_NOGEN, osd_remote_parent_ino(), osd_sb(), osd_scrub_get_fid(), RETURN, SCRUB_NEXT_CONTINUE, SCRUB_NEXT_NOSCRUB, and unlikely.
Referenced by osd_preload_next(), and osd_scrub_next().
static int osd_iit_next (struct osd_iit_param * param, __u32 * pos) [static]
Definition at line 822 of file osd_scrub.c.
References osd_iit_param::bg, osd_iit_param::bitmap, osd_iit_param::gbase, osd_iit_param::offset, osd_iit_param::sb, and SCRUB_NEXT_BREAK.
Referenced by osd_preload_next(), and osd_scrub_next().
static int osd_initial_OI_scrub (struct osd_thread_info * info, struct osd_device * dev) [static]
Definition at line 2282 of file osd_scrub.c.
References DTO_INDEX_DELETE, ENTRY, fid_is_zero(), LASSERT, list_del_init(), list_empty(), list_entry, list_head::next, OBD_FREE_PTR, osd_device::od_igif_inoi, osd_device::od_ios_list, osd_ios_item::oii_dentry, osd_ios_item::oii_filldir, osd_ios_item::oii_list, osd_ios_item::oii_scandir, osd_lf_map::olm_fid, osd_lf_map::olm_name, osd_lf_map::olm_namelen, osd_ios_general_scan(), osd_ios_lookup_one_len(), osd_ios_root_fill(), osd_sb(), osd_scrub_refresh_mapping(), and RETURN.
Referenced by osd_scrub_setup().
static int osd_inode_iteration (struct osd_thread_info * info, struct osd_device * dev, __u32 max, bool preload) [static]
Definition at line 1259 of file osd_scrub.c.
References __u64, osd_iit_param::bg, osd_iit_param::bitmap, CDEBUG, cfs_fail_val, cpu_to_le16, D_LFSCK, ENTRY, full, osd_iit_param::gbase, l_wait_event, LASSERTF, le32_to_cpu, list_empty(), OBD_FAIL_CHECK, OBD_FAIL_OSD_SCRUB_DELAY, osd_device::od_full_scrub_ratio, osd_device::od_otable_it, osd_device::od_scrub, osd_iit_param::offset, OFSR_DIRECTLY, OFSR_NEVER, osd_otable_cache::ooc_cached_items, osd_otable_cache::ooc_pos_preload, osd_otable_it::ooi_cache, osd_scrub::os_file, osd_scrub::os_full_scrub, osd_scrub::os_in_join, osd_scrub::os_inconsistent_items, osd_scrub::os_new_checked, osd_scrub::os_partial_scan, osd_scrub::os_pos_current, osd_scrub::os_thread, osd_preload_exec(), osd_preload_next(), osd_sb(), osd_scrub2name(), osd_scrub_exec(), osd_scrub_join(), osd_scrub_next(), osd_thread_info::oti_ksfs, RETURN, osd_iit_param::sb, SCRUB_IT_ALL, SCRUB_IT_CRASH, SCRUB_NEXT_BREAK, SCRUB_NEXT_CRASH, SCRUB_NEXT_EXIT, SCRUB_NEXT_FATAL, SCRUB_NEXT_WAIT, SF_AUTO, scrub_file::sf_flags, SF_INCONSISTENT, scrub_file::sf_items_updated_prior, SF_RECREATED, scrub_file::sf_status, SF_UPGRADE, SS_AUTO_FULL, SS_COMPLETED, SS_RESET, SS_SCANNING, ptlrpc_thread::t_ctl_waitq, thread, thread_is_running(), and unlikely.
Referenced by osd_otable_it_preload(), and osd_scrub_main().
static int osd_ios_dl_fill (void * buf, const char * name, int namelen, loff_t offset, __u64 ino, unsigned d_type) [static]
Definition at line 2007 of file osd_scrub.c.
References ENTRY, osd_ios_filldir_buf::oifb_dentry, osd_ios_filldir_buf::oifb_dev, osd_ios_filldir_buf::oifb_info, osd_lf_map::olm_fid, osd_lf_map::olm_flags, osd_lf_map::olm_name, osd_lf_map::olm_namelen, osd_ios_lookup_one_len(), osd_ios_scan_one(), and RETURN.
Referenced by osd_ios_ROOT_scan().
static int osd_ios_general_scan (struct osd_thread_info * info, struct osd_device * dev, struct dentry * dentry, filldir_t filldir) [static]
Definition at line 2127 of file osd_scrub.c.
References ENTRY, LASSERT, osd_ios_filldir_buf::oifb_info, osd_thread_info::oti_file, RETURN, and set_file_inode.
Referenced by osd_initial_OI_scrub(), osd_ios_lf_fill(), osd_ios_ROOT_scan(), and osd_ios_varfid_fill().
static int osd_ios_lf_fill (void * buf, const char * name, int namelen, loff_t offset, __u64 ino, unsigned d_type) [static]
It scans the /lost+found, and for the OST-object (with filter_fid or filter_fid_old), move them back to its proper /O/<seq>/d<x>.
Definition at line 1900 of file osd_scrub.c.
References CDEBUG, D_LFSCK, DFID, dir, ENTRY, GOTO, osd_device::od_scrub, osd_ios_filldir_buf::oifb_dentry, osd_ios_filldir_buf::oifb_dev, osd_ios_filldir_buf::oifb_info, osd_scrub::os_lf_failed, osd_scrub::os_lf_repaired, osd_scrub::os_lf_scanned, osd_ios_general_scan(), osd_ios_lookup_one_len(), osd_ios_new_item(), osd_name(), osd_obj_map_recover(), osd_scrub_get_fid(), osd_thread_info::oti_fid, PFID, RETURN, SCRUB_NEXT_OSTOBJ, and SCRUB_NEXT_OSTOBJ_OLD.
static struct dentry* osd_ios_lookup_one_len (const char * name, struct dentry * parent, int namelen) [static, read]
Definition at line 1760 of file osd_scrub.c.
References CERROR, and ll_lookup_one_len().
Referenced by osd_initial_OI_scrub(), osd_ios_dl_fill(), osd_ios_lf_fill(), osd_ios_OBJECTS_scan(), osd_ios_root_fill(), osd_ios_ROOT_scan(), osd_ios_uld_fill(), and osd_ios_varfid_fill().
static int osd_ios_new_item (struct osd_device * dev, struct dentry * dentry, scandir_t scandir, filldir_t filldir) [static]
Definition at line 1786 of file osd_scrub.c.
References ENTRY, INIT_LIST_HEAD, list_add_tail(), OBD_ALLOC_PTR, osd_device::od_ios_list, osd_ios_item::oii_dentry, osd_ios_item::oii_filldir, osd_ios_item::oii_list, osd_ios_item::oii_scandir, and RETURN.
Referenced by osd_ios_lf_fill(), osd_ios_root_fill(), osd_ios_ROOT_scan(), and osd_ios_varfid_fill().
static int osd_ios_OBJECTS_scan (struct osd_thread_info * info, struct osd_device * dev, struct dentry * dentry, filldir_t filldir) [static]
Definition at line 2241 of file osd_scrub.c.
References ADMIN_GRP, ADMIN_USR, ENTRY, osd_device::od_scrub, osd_scrub::os_file, osd_ios_lookup_one_len(), osd_ios_scan_one(), osd_scrub_file_store(), RETURN, scrub_file::sf_internal_flags, SIF_NO_HANDLE_OLD_FID, and unlikely.
static int osd_ios_root_fill (void * buf, const char * name, int namelen, loff_t offset, __u64 ino, unsigned d_type) [static]
Definition at line 2084 of file osd_scrub.c.
References ENTRY, osd_ios_filldir_buf::oifb_dentry, osd_ios_filldir_buf::oifb_dev, osd_ios_filldir_buf::oifb_info, OLF_NO_OI, OLF_SCAN_SUBITEMS, osd_lf_map::olm_fid, osd_lf_map::olm_filldir, osd_lf_map::olm_flags, osd_lf_map::olm_name, osd_lf_map::olm_namelen, osd_lf_map::olm_scandir, osd_ios_lookup_one_len(), osd_ios_new_item(), osd_ios_scan_one(), and RETURN.
Referenced by osd_initial_OI_scrub().
static int osd_ios_ROOT_scan (struct osd_thread_info * info, struct osd_device * dev, struct dentry * dentry, filldir_t filldir) [static]
Definition at line 2166 of file osd_scrub.c.
References dot_lustre_name, ENTRY, LU_DOT_LUSTRE_FID, osd_device::od_scrub, osd_scrub::os_convert_igif, osd_scrub::os_file, osd_ios_dl_fill(), osd_ios_general_scan(), osd_ios_lookup_one_len(), osd_ios_new_item(), osd_ios_scan_one(), osd_sb(), osd_scrub_file_reset(), osd_scrub_file_store(), RETURN, scrub_file::sf_flags, scrub_file::sf_internal_flags, SF_UPGRADE, and SIF_NO_HANDLE_OLD_FID.
static int osd_ios_scan_one (struct osd_thread_info * info, struct osd_device * dev, struct inode * inode, const struct lu_fid * fid, int flags) [static]
osd_ios_scan_one() - check/fix LMA FID and OI entry for one inode
The passed inode's fid is verified against the LMA FID. If the fid is NULL or is empty the IGIF FID is used. The FID is verified in the OI to reference the inode, or fixed if it is missing or references another inode.
Definition at line 1813 of file osd_scrub.c.
References CDEBUG, D_LFSCK, DTO_INDEX_INSERT, DTO_INDEX_UPDATE, ENTRY, lu_fid::f_oid, fid_is_zero(), LASSERT, lustre_mdt_attrs::lma_compat, lustre_mdt_attrs::lma_self_fid, LMAC_NOT_IN_OI, lu_igif_build(), osd_device::od_index, osd_device::od_scrub, OLF_HIDE_FID, OLF_IDX_IN_FID, osd_scrub::os_file, osd_ea_fid_set(), osd_get_lma(), osd_id_eq_strict(), osd_id_gen(), osd_name(), osd_oi_lookup(), osd_sb(), osd_scrub_file_reset(), osd_scrub_file_store(), osd_scrub_refresh_mapping(), osd_thread_info::oti_id, osd_thread_info::oti_id2, osd_thread_info::oti_mdt_attrs, osd_thread_info::oti_obj_dentry, RETURN, scrub_file::sf_flags, and SF_INCONSISTENT.
Referenced by osd_ios_dl_fill(), osd_ios_OBJECTS_scan(), osd_ios_root_fill(), osd_ios_ROOT_scan(), osd_ios_uld_fill(), and osd_ios_varfid_fill().
static int osd_ios_uld_fill (void * buf, const char * name, int namelen, loff_t offset, __u64 ino, unsigned d_type) [static]
Definition at line 2049 of file osd_scrub.c.
References ENTRY, fid_is_sane(), osd_ios_filldir_buf::oifb_dentry, osd_ios_filldir_buf::oifb_dev, osd_ios_filldir_buf::oifb_info, osd_ios_lookup_one_len(), osd_ios_scan_one(), RETURN, RFID, and SFID.
static int osd_ios_varfid_fill (void * buf, const char * name, int namelen, loff_t offset, __u64 ino, unsigned d_type) [static]
Definition at line 1974 of file osd_scrub.c.
References ENTRY, osd_ios_filldir_buf::oifb_dentry, osd_ios_filldir_buf::oifb_dev, osd_ios_filldir_buf::oifb_info, osd_ios_general_scan(), osd_ios_lookup_one_len(), osd_ios_new_item(), osd_ios_scan_one(), and RETURN.
char* osd_lf_fid2name (const struct lu_fid * fid)
Definition at line 2356 of file osd_scrub.c.
References lu_fid_eq(), OLF_SHOW_NAME, osd_lf_map::olm_fid, osd_lf_map::olm_flags, and osd_lf_map::olm_name.
Referenced by osd_obj_spec_lookup(), and osd_object_spec_find().
int osd_oii_insert (struct osd_device * dev, struct osd_idmap_cache * oic, int insert)
Definition at line 2935 of file osd_scrub.c.
References __u64, cfs_time_current_sec(), ENTRY, INIT_LIST_HEAD, list_add_tail(), list_empty(), now(), OBD_ALLOC_PTR, OBD_FREE_PTR, osd_device::od_full_scrub_threshold_rate, osd_device::od_scrub, osd_inconsistent_item::oii_cache, osd_inconsistent_item::oii_insert, osd_inconsistent_item::oii_list, osd_scrub::os_bad_oimap_count, osd_scrub::os_bad_oimap_time, osd_scrub::os_full_scrub, osd_scrub::os_inconsistent_items, osd_scrub::os_lock, osd_scrub::os_partial_scan, osd_scrub::os_thread, RETURN, SCRUB_BAD_OIMAP_DECAY_INTERVAL, ptlrpc_thread::t_ctl_waitq, thread, thread_is_running(), and unlikely.
Referenced by osd_consistency_check().
int osd_oii_lookup (struct osd_device * dev, const struct lu_fid * fid, struct osd_inode_id * id)
Definition at line 2990 of file osd_scrub.c.
References ENTRY, list_for_each_entry, lu_fid_eq(), osd_device::od_scrub, osd_idmap_cache::oic_fid, osd_idmap_cache::oic_lid, osd_inconsistent_item::oii_cache, osd_inconsistent_item::oii_list, osd_scrub::os_inconsistent_items, osd_scrub::os_lock, and RETURN.
Referenced by osd_fid_lookup().
static void osd_otable_it_fini (const struct lu_env * env, struct dt_it * di) [static]
Definition at line 2739 of file osd_scrub.c.
References do_osd_scrub_stop(), LASSERT, OBD_FREE_PTR, osd_device::od_otable_it, osd_device::od_otable_mutex, osd_device::od_scrub, and osd_otable_it::ooi_dev.
static int osd_otable_it_get (const struct lu_env * env, struct dt_it * di, const struct dt_key * key) [static]
Definition at line 2754 of file osd_scrub.c.
static struct dt_it* osd_otable_it_init (const struct lu_env * env, struct dt_object * dt, __u32 attr) [static, read]
Definition at line 2679 of file osd_scrub.c.
References dt_object::do_lu, do_osd_scrub_start(), DOIF_DRYRUN, DOIF_FAILOUT, DOIF_OUTUSED, DOIF_RESET, DOIV_DRYRUN, DOIV_ERROR_HANDLE, DT_OTABLE_IT_FLAGS_MASK, DT_OTABLE_IT_FLAGS_SHIFT, ENTRY, GOTO, lu_object::lo_dev, OBD_ALLOC_PTR, OBD_FREE_PTR, osd_device::od_otable_it, osd_device::od_otable_mutex, osd_device::od_scrub, osd_otable_cache::ooc_consumer_idx, osd_otable_cache::ooc_pos_preload, osd_otable_it::ooi_cache, osd_otable_it::ooi_dev, osd_otable_it::ooi_used_outside, osd_scrub::os_pos_current, osd_dev(), SS_AUTO_PARTIAL, SS_CLEAR_DRYRUN, SS_CLEAR_FAILOUT, SS_RESET, SS_SET_DRYRUN, SS_SET_FAILOUT, and start.
static struct dt_key* osd_otable_it_key (const struct lu_env * env, const struct dt_it * di) [static, read]
Definition at line 2832 of file osd_scrub.c.
static int osd_otable_it_key_rec (const struct lu_env * env, const struct dt_it * di, void * key_rec) [static]
Definition at line 2909 of file osd_scrub.c.
static int osd_otable_it_key_size (const struct lu_env * env, const struct dt_it * di) [static]
Definition at line 2838 of file osd_scrub.c.
References __u64.
static int osd_otable_it_load (const struct lu_env * env, const struct dt_it * di, __u64 hash) [static]
Set the OSD layer iteration start position as the specified hash.
Definition at line 2878 of file osd_scrub.c.
References ENTRY, osd_device::od_scrub, osd_otable_cache::ooc_pos_preload, osd_otable_it::ooi_cache, osd_otable_it::ooi_dev, osd_otable_it::ooi_user_ready, osd_scrub::os_full_speed, osd_scrub::os_thread, osd_otable_it_next(), OSD_OTABLE_MAX_HASH, osd_sb(), RETURN, and ptlrpc_thread::t_ctl_waitq.
static int osd_otable_it_next (const struct lu_env * env, struct dt_it * di) [static]
Definition at line 2779 of file osd_scrub.c.
References ENTRY, l_wait_event, LASSERT, osd_device::od_scrub, osd_otable_cache::ooc_cached_items, osd_otable_cache::ooc_consumer_idx, osd_otable_cache::ooc_pos_preload, osd_otable_it::ooi_all_cached, osd_otable_it::ooi_cache, osd_otable_it::ooi_dev, osd_otable_it::ooi_used_outside, osd_otable_it::ooi_user_ready, osd_scrub::os_lock, osd_scrub::os_pos_current, osd_scrub::os_thread, osd_scrub::os_waiting, OSD_OTABLE_IT_CACHE_MASK, osd_otable_it_preload(), osd_otable_it_wakeup(), osd_scrub_has_window(), RETURN, ptlrpc_thread::t_ctl_waitq, thread, and thread_is_running().
Referenced by osd_otable_it_load().
static int osd_otable_it_preload (const struct lu_env * env, struct osd_otable_it * it) [static]
Definition at line 1447 of file osd_scrub.c.
References ENTRY, osd_device::od_scrub, osd_otable_cache::ooc_cached_items, osd_otable_it::ooi_all_cached, osd_otable_it::ooi_cache, osd_otable_it::ooi_dev, osd_scrub::os_lock, osd_scrub::os_thread, osd_scrub::os_waiting, osd_inode_iteration(), OSD_OTABLE_IT_CACHE_SIZE, osd_oti_get(), osd_scrub_has_window(), RETURN, SCRUB_IT_ALL, and ptlrpc_thread::t_ctl_waitq.
Referenced by osd_otable_it_next().
static void osd_otable_it_put (const struct lu_env * env, struct dt_it * di) [static]
Definition at line 2760 of file osd_scrub.c.
static int osd_otable_it_rec (const struct lu_env * env, const struct dt_it * di, struct dt_rec * rec, __u32 attr) [static]
Definition at line 2844 of file osd_scrub.c.
References DFID, fid_is_sane(), LASSERTF, osd_idmap_cache::oic_fid, osd_otable_cache::ooc_cache, osd_otable_cache::ooc_consumer_idx, osd_otable_cache::ooc_producer_idx, osd_otable_it::ooi_cache, and PFID.
static __u64 osd_otable_it_store (const struct lu_env * env, const struct dt_it * di) [static]
Definition at line 2861 of file osd_scrub.c.
References __u64, osd_idmap_cache::oic_lid, osd_inode_id::oii_ino, osd_otable_cache::ooc_cache, osd_otable_cache::ooc_consumer_idx, osd_otable_cache::ooc_pos_preload, osd_otable_it::ooi_cache, and osd_otable_it::ooi_user_ready.
static int osd_otable_it_wakeup (struct osd_scrub * scrub, struct osd_otable_it * it) [inline, static]
Definition at line 2765 of file osd_scrub.c.
References osd_otable_cache::ooc_pos_preload, osd_otable_it::ooi_cache, osd_otable_it::ooi_waiting, osd_scrub::os_lock, osd_scrub::os_pos_current, osd_scrub::os_thread, osd_scrub::os_waiting, and thread_is_running().
Referenced by osd_otable_it_next().
static int osd_preload_exec (struct osd_thread_info * info, struct osd_device * dev, struct osd_iit_param * param, struct osd_idmap_cache * oic, bool * noslot, int rc) [static]
Definition at line 1174 of file osd_scrub.c.
References osd_device::od_otable_it, osd_otable_cache::ooc_cached_items, osd_otable_cache::ooc_producer_idx, osd_otable_it::ooi_cache, and OSD_OTABLE_IT_CACHE_MASK.
Referenced by osd_inode_iteration().
static int osd_preload_next (struct osd_thread_info * info, struct osd_device * dev, struct osd_iit_param * param, struct osd_idmap_cache ** oic, const bool noslot) [static]
Definition at line 1056 of file osd_scrub.c.
References osd_iit_param::gbase, osd_device::od_otable_it, osd_device::od_scrub, osd_iit_param::offset, osd_idmap_cache::oic_fid, osd_idmap_cache::oic_lid, osd_otable_cache::ooc_cache, osd_otable_cache::ooc_pos_preload, osd_otable_cache::ooc_producer_idx, osd_otable_it::ooi_cache, osd_scrub::os_pos_current, osd_scrub::os_thread, osd_iit_iget(), osd_iit_next(), osd_iit_param::sb, SCRUB_NEXT_EXIT, thread, and thread_is_running().
Referenced by osd_inode_iteration().
static struct osd_device* osd_scrub2dev (struct osd_scrub * scrub) [static, read]
Definition at line 68 of file osd_scrub.c.
References osd_device::od_scrub.
Referenced by osd_scrub2sb().
static const char* osd_scrub2name (struct osd_scrub * scrub) [inline, static]
Definition at line 84 of file osd_scrub.c.
References osd_scrub2sb().
Referenced by do_osd_scrub_start(), osd_inode_iteration(), osd_scrub_exec(), osd_scrub_file_load(), osd_scrub_file_reset(), osd_scrub_file_store(), osd_scrub_join(), osd_scrub_main(), osd_scrub_post(), and osd_scrub_prep().
static struct super_block* osd_scrub2sb (struct osd_scrub * scrub) [static, read]
Definition at line 73 of file osd_scrub.c.
References osd_sb(), and osd_scrub2dev().
Referenced by osd_scrub2name().
static int osd_scrub_check_local_fldb (struct osd_thread_info * info, struct osd_device * dev, struct lu_fid * fid) [static]
Return values:
SCRUB_NEXT_OSTOBJ_OLD,: FID-on-OST
0,: FID-on-MDT
Definition at line 839 of file osd_scrub.c.
References osd_device::od_is_ost, and SCRUB_NEXT_OSTOBJ_OLD.
Referenced by osd_scrub_get_fid().
static int osd_scrub_check_update (struct osd_thread_info * info, struct osd_device * dev, struct osd_idmap_cache * oic, int val) [static]
Definition at line 459 of file osd_scrub.c.
References DTO_INDEX_DELETE, DTO_INDEX_INSERT, DTO_INDEX_UPDATE, ENTRY, fid_is_igif(), GOTO, LASSERT, LDISKFS_STATE_LUSTRE_DESTROY, list_empty(), list_entry, OBD_FAIL_CHECK, OBD_FAIL_FID_NOLMA, OBD_FREE_PTR, osd_device::od_check_ff, osd_device::od_igif_inoi, osd_device::od_scrub, OI_KNOWN_ON_OST, osd_idmap_cache::oic_fid, osd_idmap_cache::oic_lid, osd_inode_id::oii_ino, osd_inconsistent_item::oii_insert, osd_inconsistent_item::oii_list, osd_scrub::os_convert_igif, osd_scrub::os_file, osd_scrub::os_full_speed, osd_scrub::os_in_prior, osd_scrub::os_new_checked, osd_scrub::os_partial_scan, osd_scrub::os_rwsem, osd_ea_fid_set(), osd_id_eq(), osd_iget(), osd_is_ea_inode(), osd_oi_fid2idx(), osd_oi_lookup(), osd_scrub_convert_ff(), osd_scrub_refresh_mapping(), osd_thread_info::oti_id, RETURN, SCRUB_NEXT_NOLMA, SCRUB_NEXT_OSTOBJ, SCRUB_NEXT_OSTOBJ_OLD, scrub_file::sf_flags, SF_INCONSISTENT, scrub_file::sf_internal_flags, scrub_file::sf_items_failed, scrub_file::sf_items_igif, scrub_file::sf_items_updated, scrub_file::sf_items_updated_prior, scrub_file::sf_oi_bitmap, scrub_file::sf_param, scrub_file::sf_pos_first_inconsistent, scrub_file::sf_pos_latest_start, SF_RECREATED, SF_UPGRADE, SIF_NO_HANDLE_OLD_FID, SP_DRYRUN, SP_FAILOUT, and unlikely.
Referenced by osd_scrub_exec().
static int osd_scrub_checkpoint (struct osd_scrub * scrub) [static]
Definition at line 728 of file osd_scrub.c.
References cfs_duration_sec(), cfs_time_before(), cfs_time_current(), cfs_time_current_sec(), HALF_SEC, likely, osd_scrub::os_file, osd_scrub::os_new_checked, osd_scrub::os_pos_current, osd_scrub::os_rwsem, osd_scrub::os_time_last_checkpoint, osd_scrub::os_time_next_checkpoint, osd_scrub_file_store(), scrub_file::sf_items_checked, scrub_file::sf_pos_last_checkpoint, scrub_file::sf_run_time, and scrub_file::sf_time_last_checkpoint.
Referenced by osd_scrub_exec().
void osd_scrub_cleanup (const struct lu_env * env, struct osd_device * dev)
Definition at line 2662 of file osd_scrub.c.
References LASSERT, osd_device::od_oi_table, osd_device::od_otable_it, osd_device::od_scrub, osd_scrub::os_inode, osd_oi_fini(), osd_oti_get(), and osd_scrub_stop().
Referenced by osd_device_fini(), and osd_device_init0().
static int osd_scrub_convert_ff (struct osd_thread_info * info, struct osd_device * dev, struct inode * inode, const struct lu_fid * fid) [static]
Definition at line 370 of file osd_scrub.c.
References __osd_xattr_get(), __osd_xattr_set(), CDEBUG, D_LFSCK, DFID, DTO_XATTR_SET, ENTRY, fid_is_idif(), fid_to_ostid(), GOTO, LDISKFS_HT_MISC, ll_vfs_dq_init, LMAC_FID_ON_OST, osd_device::od_index_in_idif, osd_device::od_scrub, ost_id::oi, osd_scrub::os_file, osd_dto_credits_noquota, osd_ea_fid_set(), osd_journal_start_sb, osd_name(), osd_sb(), ostid_to_fid(), osd_thread_info::oti_ff, osd_thread_info::oti_fid, osd_thread_info::oti_obj_dentry, osd_thread_info::oti_ostid, PFID, RETURN, scrub_file::sf_param, size, SP_DRYRUN, stop, unlikely, and XATTR_NAME_FID.
Referenced by osd_scrub_check_update().
int osd_scrub_dump (struct seq_file * m, struct osd_device * dev)
Definition at line 3071 of file osd_scrub.c.
References __u64, cfs_duration_sec(), cfs_time_current(), HALF_SEC, LPU64, osd_device::od_scrub, osd_scrub::os_file, osd_scrub::os_lf_failed, osd_scrub::os_lf_repaired, osd_scrub::os_lf_scanned, osd_scrub::os_new_checked, osd_scrub::os_pos_current, osd_scrub::os_rwsem, osd_scrub::os_thread, osd_scrub::os_time_last_checkpoint, scrub_bits_dump(), scrub_pos_dump(), scrub_time_dump(), scrub_file::sf_flags, scrub_file::sf_items_checked, scrub_file::sf_items_failed, scrub_file::sf_items_igif, scrub_file::sf_items_noscrub, scrub_file::sf_items_updated, scrub_file::sf_items_updated_prior, scrub_file::sf_magic, scrub_file::sf_oi_count, scrub_file::sf_param, scrub_file::sf_pos_first_inconsistent, scrub_file::sf_pos_last_checkpoint, scrub_file::sf_pos_latest_start, scrub_file::sf_run_time, scrub_file::sf_status, scrub_file::sf_success_count, scrub_file::sf_time_last_checkpoint, scrub_file::sf_time_last_complete, scrub_file::sf_time_latest_start, and thread_is_running().
static int osd_scrub_exec (struct osd_thread_info * info, struct osd_device * dev, struct osd_iit_param * param, struct osd_idmap_cache * oic, bool * noslot, int rc) [static]
Definition at line 1100 of file osd_scrub.c.
References CDEBUG, D_LFSCK, osd_iit_param::gbase, l_wait_event, osd_device::od_otable_it, osd_device::od_scrub, osd_iit_param::offset, osd_otable_cache::ooc_pos_preload, osd_otable_it::ooi_cache, osd_otable_it::ooi_waiting, osd_scrub::os_file, osd_scrub::os_full_speed, osd_scrub::os_in_prior, osd_scrub::os_lock, osd_scrub::os_new_checked, osd_scrub::os_pos_current, osd_scrub::os_rwsem, osd_scrub::os_thread, osd_scrub2name(), osd_scrub_check_update(), osd_scrub_checkpoint(), osd_scrub_has_window(), osd_scrub_wakeup(), SCRUB_NEXT_CONTINUE, SCRUB_NEXT_NOSCRUB, SCRUB_NEXT_WAIT, scrub_file::sf_items_noscrub, ptlrpc_thread::t_ctl_waitq, and thread.
Referenced by osd_inode_iteration().
static void osd_scrub_file_init (struct osd_scrub * scrub, __u8 * uuid) [static]
Definition at line 262 of file osd_scrub.c.
References osd_scrub::os_file, SCRUB_MAGIC_V1, scrub_file::sf_magic, scrub_file::sf_status, scrub_file::sf_uuid, and SS_INIT.
Referenced by osd_scrub_setup().
static int osd_scrub_file_load (struct osd_scrub * scrub) [static]
Definition at line 300 of file osd_scrub.c.
References CDEBUG, D_LFSCK, osd_scrub::os_file, osd_scrub::os_file_disk, osd_scrub::os_inode, osd_ldiskfs_read(), osd_scrub2name(), osd_scrub_file_to_cpu(), SCRUB_MAGIC_V1, and scrub_file::sf_magic.
Referenced by osd_scrub_setup().
void osd_scrub_file_reset (struct osd_scrub * scrub, __u8 * uuid, __u64 flags)
Definition at line 272 of file osd_scrub.c.
References CDEBUG, D_LFSCK, LPX64, osd_scrub::os_file, osd_scrub::os_in_join, osd_scrub2name(), SF_AUTO, scrub_file::sf_flags, scrub_file::sf_items_checked, scrub_file::sf_items_failed, scrub_file::sf_items_igif, scrub_file::sf_items_noscrub, scrub_file::sf_items_updated, scrub_file::sf_items_updated_prior, scrub_file::sf_pos_first_inconsistent, scrub_file::sf_pos_last_checkpoint, scrub_file::sf_pos_latest_start, scrub_file::sf_run_time, scrub_file::sf_status, scrub_file::sf_time_last_checkpoint, scrub_file::sf_time_latest_start, scrub_file::sf_uuid, and SS_INIT.
Referenced by osd_ios_ROOT_scan(), osd_ios_scan_one(), osd_oi_init(), osd_scrub_join(), osd_scrub_prep(), and osd_scrub_setup().
int osd_scrub_file_store (struct osd_scrub * scrub)
Definition at line 334 of file osd_scrub.c.
References CDEBUG, cfs_time_current(), cfs_time_seconds(), credits, D_LFSCK, DTO_WRITE_BASE, DTO_WRITE_BLOCK, LDISKFS_HT_MISC, osd_device::od_scrub, osd_scrub::os_file, osd_scrub::os_file_disk, osd_scrub::os_inode, osd_scrub::os_time_last_checkpoint, osd_scrub::os_time_next_checkpoint, osd_dto_credits_noquota, osd_journal_start_sb, osd_ldiskfs_write_record(), osd_sb(), osd_scrub2name(), osd_scrub_file_to_le(), and SCRUB_CHECKPOINT_INTERVAL.
Referenced by osd_ios_OBJECTS_scan(), osd_ios_ROOT_scan(), osd_ios_scan_one(), osd_oi_init(), osd_scrub_checkpoint(), osd_scrub_join(), osd_scrub_post(), osd_scrub_prep(), and osd_scrub_setup().
static void osd_scrub_file_to_cpu (struct scrub_file * des, struct scrub_file * src) [static]
Definition at line 192 of file osd_scrub.c.
References le16_to_cpu, le32_to_cpu, le64_to_cpu, SCRUB_OI_BITMAP_SIZE, scrub_file::sf_flags, scrub_file::sf_internal_flags, scrub_file::sf_items_checked, scrub_file::sf_items_failed, scrub_file::sf_items_updated, scrub_file::sf_items_updated_prior, scrub_file::sf_magic, scrub_file::sf_oi_bitmap, scrub_file::sf_oi_count, scrub_file::sf_param, scrub_file::sf_pos_first_inconsistent, scrub_file::sf_pos_last_checkpoint, scrub_file::sf_pos_latest_start, scrub_file::sf_run_time, scrub_file::sf_status, scrub_file::sf_success_count, scrub_file::sf_time_last_checkpoint, scrub_file::sf_time_last_complete, scrub_file::sf_time_latest_start, and scrub_file::sf_uuid.
Referenced by osd_scrub_file_load().
static void osd_scrub_file_to_le (struct scrub_file * des, struct scrub_file * src) [static]
Definition at line 227 of file osd_scrub.c.
References cpu_to_le16, cpu_to_le32, cpu_to_le64, SCRUB_OI_BITMAP_SIZE, scrub_file::sf_flags, scrub_file::sf_internal_flags, scrub_file::sf_items_checked, scrub_file::sf_items_failed, scrub_file::sf_items_updated, scrub_file::sf_items_updated_prior, scrub_file::sf_magic, scrub_file::sf_oi_bitmap, scrub_file::sf_oi_count, scrub_file::sf_param, scrub_file::sf_pos_first_inconsistent, scrub_file::sf_pos_last_checkpoint, scrub_file::sf_pos_latest_start, scrub_file::sf_run_time, scrub_file::sf_status, scrub_file::sf_success_count, scrub_file::sf_time_last_checkpoint, scrub_file::sf_time_last_complete, scrub_file::sf_time_latest_start, and scrub_file::sf_uuid.
Referenced by osd_scrub_file_store().
static int osd_scrub_get_fid (struct osd_thread_info * info, struct osd_device * dev, struct inode * inode, struct lu_fid * fid, bool scrub) [static]
Definition at line 853 of file osd_scrub.c.
References fid_is_idif(), fid_is_internal(), fid_is_namespace_visible(), fid_is_norm(), lustre_mdt_attrs::lma_compat, lustre_mdt_attrs::lma_incompat, lustre_mdt_attrs::lma_self_fid, LMAC_FID_ON_OST, LMAC_NOT_IN_OI, LMAI_AGENT, lu_igif_build(), osd_device::od_scrub, osd_scrub::os_convert_igif, osd_get_idif(), osd_get_lma(), osd_scrub_check_local_fldb(), osd_thread_info::oti_mdt_attrs, osd_thread_info::oti_obj_dentry, SCRUB_NEXT_CONTINUE, SCRUB_NEXT_NOLMA, SCRUB_NEXT_OSTOBJ, and SCRUB_NEXT_OSTOBJ_OLD.
Referenced by osd_iit_iget(), and osd_ios_lf_fill().
static int osd_scrub_has_window (struct osd_scrub * scrub, struct osd_otable_cache * ooc) [inline, static]
Definition at line 78 of file osd_scrub.c.
References osd_otable_cache::ooc_pos_preload, osd_scrub::os_pos_current, and SCRUB_WINDOW_SIZE.
Referenced by osd_otable_it_next(), osd_otable_it_preload(), osd_scrub_exec(), and osd_scrub_wakeup().
static void osd_scrub_join (struct osd_device * dev, __u32 flags, bool inconsistent) [static]
Definition at line 1191 of file osd_scrub.c.
References CDEBUG, cfs_time_current_sec(), D_LFSCK, ENTRY, EXIT, LASSERT, osd_device::od_scrub, osd_scrub::os_file, osd_scrub::os_full_scrub, osd_scrub::os_full_speed, osd_scrub::os_in_join, osd_scrub::os_lock, osd_scrub::os_new_checked, osd_scrub::os_partial_scan, osd_scrub::os_paused, osd_scrub::os_pos_current, osd_scrub::os_rwsem, osd_scrub::os_thread, osd_scrub::os_waiting, osd_sb(), osd_scrub2name(), osd_scrub_file_reset(), osd_scrub_file_store(), SF_AUTO, scrub_file::sf_flags, SF_INCONSISTENT, scrub_file::sf_param, scrub_file::sf_pos_last_checkpoint, scrub_file::sf_pos_latest_start, SF_RECREATED, scrub_file::sf_status, scrub_file::sf_time_last_checkpoint, scrub_file::sf_time_latest_start, SF_UPGRADE, SP_DRYRUN, SP_FAILOUT, SS_AUTO_FULL, SS_AUTO_PARTIAL, SS_CLEAR_DRYRUN, SS_CLEAR_FAILOUT, SS_RESET, SS_SCANNING, SS_SET_DRYRUN, SS_SET_FAILOUT, ptlrpc_thread::t_ctl_waitq, and thread.
Referenced by do_osd_scrub_start(), and osd_inode_iteration().
static int osd_scrub_main (void * args) [static]
Definition at line 1471 of file osd_scrub.c.
References CDEBUG, D_LFSCK, ENTRY, GOTO, l_wait_event, LCT_LOCAL, list_del_init(), list_empty(), list_entry, lu_env_fini(), lu_env_init(), list_head::next, OBD_FREE_PTR, osd_device::od_otable_it, osd_device::od_scrub, osd_inconsistent_item::oii_list, osd_otable_cache::ooc_pos_preload, osd_otable_it::ooi_cache, osd_otable_it::ooi_user_ready, osd_scrub::os_full_speed, osd_scrub::os_inconsistent_items, osd_scrub::os_lock, osd_scrub::os_partial_scan, osd_scrub::os_pos_current, osd_scrub::os_start_flags, osd_scrub::os_thread, osd_inode_iteration(), osd_oti_get(), osd_scrub2name(), osd_scrub_post(), osd_scrub_prep(), SCRUB_IT_CRASH, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, thread, thread_is_running(), thread_set_flags(), and unlikely.
Referenced by do_osd_scrub_start().
static int osd_scrub_next (struct osd_thread_info * info, struct osd_device * dev, struct osd_iit_param * param, struct osd_idmap_cache ** oic, const bool noslot) [static]
Definition at line 989 of file osd_scrub.c.
References cfs_fail_val, cfs_time_seconds(), l_wait_event, likely, list_del_init(), list_empty(), list_entry, LWI_TIMEOUT, list_head::next, OBD_FAIL_CHECK, OBD_FAIL_OSD_SCRUB_CRASH, OBD_FAIL_OSD_SCRUB_DELAY, OBD_FAIL_OSD_SCRUB_FATAL, osd_device::od_scrub, osd_inconsistent_item::oii_cache, osd_inconsistent_item::oii_list, osd_scrub::os_in_prior, osd_scrub::os_inconsistent_items, osd_scrub::os_lock, osd_scrub::os_oic, osd_scrub::os_pos_current, osd_scrub::os_thread, osd_iit_iget(), osd_iit_next(), osd_iit_param::sb, SCRUB_NEXT_CRASH, SCRUB_NEXT_EXIT, SCRUB_NEXT_FATAL, SCRUB_NEXT_WAIT, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, thread, thread_is_running(), thread_set_flags(), and unlikely.
Referenced by osd_inode_iteration().
static int osd_scrub_post (struct osd_scrub * scrub, int result) [static]
Definition at line 751 of file osd_scrub.c.
References CDEBUG, cfs_duration_sec(), cfs_time_current(), cfs_time_current_sec(), D_LFSCK, ENTRY, HALF_SEC, osd_device::od_check_ff, osd_device::od_igif_inoi, osd_device::od_scrub, osd_scrub::os_file, osd_scrub::os_lock, osd_scrub::os_new_checked, osd_scrub::os_paused, osd_scrub::os_pos_current, osd_scrub::os_rwsem, osd_scrub::os_thread, osd_scrub::os_time_last_checkpoint, osd_scrub2name(), osd_scrub_file_store(), RETURN, SCRUB_OI_BITMAP_SIZE, SF_AUTO, scrub_file::sf_flags, SF_INCONSISTENT, scrub_file::sf_items_checked, scrub_file::sf_oi_bitmap, scrub_file::sf_param, scrub_file::sf_pos_last_checkpoint, SF_RECREATED, scrub_file::sf_run_time, scrub_file::sf_status, scrub_file::sf_success_count, scrub_file::sf_time_last_checkpoint, scrub_file::sf_time_last_complete, SF_UPGRADE, SP_DRYRUN, SS_COMPLETED, SS_FAILED, SS_PAUSED, SS_STOPPED, SVC_STOPPING, and thread_set_flags().
Referenced by osd_scrub_main().
static int osd_scrub_prep (struct osd_device * dev) [static]
Definition at line 649 of file osd_scrub.c.
References CDEBUG, cfs_time_current_sec(), D_LFSCK, ENTRY, osd_device::od_scrub, osd_scrub::os_file, osd_scrub::os_full_scrub, osd_scrub::os_full_speed, osd_scrub::os_in_join, osd_scrub::os_in_prior, osd_scrub::os_lock, osd_scrub::os_new_checked, osd_scrub::os_partial_scan, osd_scrub::os_paused, osd_scrub::os_pos_current, osd_scrub::os_rwsem, osd_scrub::os_start_flags, osd_scrub::os_thread, osd_scrub::os_waiting, osd_sb(), osd_scrub2name(), osd_scrub_file_reset(), osd_scrub_file_store(), RETURN, SF_AUTO, scrub_file::sf_flags, SF_INCONSISTENT, scrub_file::sf_param, scrub_file::sf_pos_first_inconsistent, scrub_file::sf_pos_last_checkpoint, scrub_file::sf_pos_latest_start, SF_RECREATED, scrub_file::sf_status, scrub_file::sf_time_last_checkpoint, scrub_file::sf_time_latest_start, SF_UPGRADE, SP_DRYRUN, SP_FAILOUT, SS_AUTO_FULL, SS_AUTO_PARTIAL, SS_CLEAR_DRYRUN, SS_CLEAR_FAILOUT, SS_RESET, SS_SCANNING, SS_SET_DRYRUN, SS_SET_FAILOUT, SVC_RUNNING, ptlrpc_thread::t_ctl_waitq, thread, and thread_set_flags().
Referenced by osd_scrub_main().
static int osd_scrub_refresh_mapping (struct osd_thread_info * info, struct osd_device * dev, const struct lu_fid * fid, const struct osd_inode_id * id, int ops, bool force, enum oi_check_flags flags) [static]
update/insert/delete the specified OI mapping () according to the ops
Return values:
1,changed nothing
0,changed successfully
-ve,on error
Definition at line 96 of file osd_scrub.c.
References CDEBUG, D_LFSCK, DFID, DTO_INDEX_DELETE, DTO_INDEX_INSERT, DTO_INDEX_UPDATE, ENTRY, LASSERTF, LDISKFS_HT_MISC, osd_device::od_scrub, osd_inode_id::oii_gen, osd_inode_id::oii_ino, osd_scrub::os_file, osd_dto_credits_noquota, osd_journal_start_sb, osd_name(), osd_oi_delete(), osd_oi_insert(), osd_oi_update(), osd_sb(), PFID, RETURN, scrub_file::sf_param, SP_DRYRUN, and unlikely.
Referenced by osd_initial_OI_scrub(), osd_ios_scan_one(), and osd_scrub_check_update().
int osd_scrub_setup (const struct lu_env * env, struct osd_device * dev)
Definition at line 2489 of file osd_scrub.c.
References CERROR, class_uuid_unparse(), ENTRY, lvfs_run_ctxt::fs, GOTO, INIT_LIST_HEAD, LMAC_NOT_IN_OI, lu_igif_build(), OBD_ALLOC_PTR, OBD_FREE_PTR, OBD_SET_CTXT_MAGIC(), osd_device::od_check_ff, osd_device::od_igif_inoi, osd_device::od_is_ost, osd_device::od_maybe_new, osd_device::od_mnt, osd_device::od_noscrub, osd_device::od_scrub, osd_scrub::os_ctxt, osd_scrub::os_file, osd_scrub::os_inconsistent_items, osd_scrub::os_inode, osd_scrub::os_lock, osd_scrub::os_pos_current, osd_scrub::os_rwsem, osd_scrub::os_thread, osd_ea_fid_set(), osd_initial_OI_scrub(), osd_oi_fini(), osd_oi_init(), osd_oti_get(), osd_sb(), osd_scrub_file_init(), osd_scrub_file_load(), osd_scrub_file_reset(), osd_scrub_file_store(), osd_scrub_start(), osd_thread_info::oti_fid, pop_ctxt(), push_ctxt(), lvfs_run_ctxt::pwd, lvfs_run_ctxt::pwdmnt, RETURN, SF_AUTO, scrub_file::sf_flags, SF_INCONSISTENT, scrub_file::sf_internal_flags, scrub_file::sf_pos_last_checkpoint, SF_RECREATED, scrub_file::sf_status, scrub_file::sf_success_count, SF_UPGRADE, scrub_file::sf_uuid, SIF_NO_HANDLE_OLD_FID, SS_AUTO_FULL, SS_CRASHED, SS_INIT, SS_PAUSED, SS_SCANNING, ptlrpc_thread::t_ctl_waitq, and obd_uuid::uuid.
Referenced by osd_device_init0().
int osd_scrub_start (struct osd_device * dev, __u32 flags)
Definition at line 2442 of file osd_scrub.c.
References do_osd_scrub_start(), ENTRY, osd_device::od_otable_mutex, and RETURN.
Referenced by osd_consistency_check(), osd_fid_lookup(), and osd_scrub_setup().
static void osd_scrub_stop (struct osd_device * dev) [static]
Definition at line 2476 of file osd_scrub.c.
References do_osd_scrub_stop(), osd_device::od_otable_mutex, osd_device::od_scrub, and osd_scrub::os_paused.
Referenced by osd_scrub_cleanup().
static int osd_scrub_wakeup (struct osd_scrub * scrub, struct osd_otable_it * it) [inline, static]
Definition at line 1086 of file osd_scrub.c.
References list_empty(), osd_otable_it::ooi_cache, osd_otable_it::ooi_waiting, osd_scrub::os_inconsistent_items, osd_scrub::os_lock, osd_scrub::os_thread, osd_scrub::os_waiting, osd_scrub_has_window(), and thread_is_running().
Referenced by osd_scrub_exec().
static void scrub_bits_dump (struct seq_file * m, int bits, const char * names[], const char * prefix) [static]
Definition at line 3037 of file osd_scrub.c.
Referenced by osd_scrub_dump().
static void scrub_pos_dump (struct seq_file * m, __u64 pos, const char * prefix) [static]
Definition at line 3063 of file osd_scrub.c.
References LPU64.
Referenced by osd_scrub_dump().
static void scrub_time_dump (struct seq_file * m, __u64 time, const char * prefix) [static]
Definition at line 3054 of file osd_scrub.c.
References cfs_time_current_sec(), and LPU64.
Referenced by osd_scrub_dump().
Variable Documentation
struct osd_lf_map osd_dl_maps[] [static]
Initial value:
 {
        { "fid", { FID_SEQ_DOT_LUSTRE, FID_OID_DOT_LUSTRE_OBF, 0 }, 0,
                sizeof("fid") - 1, NULL, NULL },
        { "lost+found", { FID_SEQ_DOT_LUSTRE, FID_OID_DOT_LUSTRE_LPF, 0 }, 0,
                sizeof("lost+found") - 1, NULL, NULL },
        { NULL, { 0, 0, 0 }, 0, 0, NULL, NULL }
}
Definition at line 1730 of file osd_scrub.c.
struct osd_lf_map osd_lf_maps[] [static]
Definition at line 1599 of file osd_scrub.c.
struct dt_index_operations osd_otable_ops
Initial value:
 {
        .dio_it = {
                .init     = osd_otable_it_init,
                .fini     = osd_otable_it_fini,
                .get      = osd_otable_it_get,
                .put      = osd_otable_it_put,
                .next     = osd_otable_it_next,
                .key      = osd_otable_it_key,
                .key_size = osd_otable_it_key_size,
                .rec      = osd_otable_it_rec,
                .store    = osd_otable_it_store,
                .load     = osd_otable_it_load,
                .key_rec  = osd_otable_it_key_rec,
        }
}
Definition at line 2915 of file osd_scrub.c.
Referenced by osd_index_try().
const char osd_scrub_name[] = "OI_scrub" [static]
Definition at line 2487 of file osd_scrub.c.
const char* scrub_flags_names[] [static]
Initial value:
 {
        "recreated",
        "inconsistent",
        "auto",
        "upgrade",
        NULL
}
Definition at line 3023 of file osd_scrub.c.
const char* scrub_param_names[] [static]
Initial value:
 {
        "failout",
        "dryrun",
        NULL
}
Definition at line 3031 of file osd_scrub.c.
const char* scrub_status_names[] [static]
Initial value:
 {
        "init",
        "scanning",
        "completed",
        "failed",
        "stopped",
        "paused",
        "crashed",
        NULL
}
Definition at line 3012 of file osd_scrub.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.