Lustre: lustre/osd-ldiskfs/osd_compat.c File Reference
lustre/osd-ldiskfs/osd_compat.c File Reference
#include <lustre_ver.h>
#include <linux/types.h>
#include <linux/fs.h>
#include <linux/xattr.h>
#include <obd_support.h>
#include "osd_internal.h"
#include "osd_oi.h"
Functions
static void osd_push_ctxt (const struct osd_device *dev, struct lvfs_run_ctxt *newctxt, struct lvfs_run_ctxt *save)
static struct dentry * simple_mkdir (struct dentry *dir, struct vfsmount *mnt, const char *name, int mode, int fix)
static int osd_last_rcvd_subdir_count (struct osd_device *osd)
static int osd_mdt_init (const struct lu_env *env, struct osd_device *dev)
static void osd_mdt_fini (struct osd_device *osd)
int osd_add_to_remote_parent (const struct lu_env *env, struct osd_device *osd, struct osd_object *obj, struct osd_thandle *oh)
int osd_delete_from_remote_parent (const struct lu_env *env, struct osd_device *osd, struct osd_object *obj, struct osd_thandle *oh)
int osd_lookup_in_remote_parent (struct osd_thread_info *oti, struct osd_device *osd, const struct lu_fid *fid, struct osd_inode_id *id)
static int osd_ost_init (const struct lu_env *env, struct osd_device *dev)
static void osd_seq_free (struct osd_obj_seq *osd_seq)
static void osd_ost_fini (struct osd_device *osd)
int osd_obj_map_init (const struct lu_env *env, struct osd_device *dev)
static struct osd_obj_seq * osd_seq_find_locked (struct osd_obj_map *map, u64 seq)
static struct osd_obj_seq * osd_seq_find (struct osd_obj_map *map, u64 seq)
void osd_obj_map_fini (struct osd_device *dev)
static int osd_obj_update_entry (struct osd_thread_info *info, struct osd_device *osd, struct dentry *dir, const char *name, const struct lu_fid *fid, const struct osd_inode_id *id, handle_t *th)
Update the specified OI mapping.
static int osd_obj_del_entry (struct osd_thread_info *info, struct osd_device *osd, struct dentry *dird, char *name, handle_t *th)
static int osd_obj_add_entry (struct osd_thread_info *info, struct osd_device *osd, struct dentry *dir, char *name, const struct osd_inode_id *id, handle_t *th)
static void osd_seq_name (char *seq_name, size_t name_size, u64 seq)
Use LPU64 for legacy OST sequences, but use LPX64i for new sequences names, so that the O/{seq}/dN/{oid} more closely follows the DFID/PFID format.
static void osd_oid_name (char *name, size_t name_size, const struct lu_fid *fid, u64 id)
static int osd_seq_load_locked (struct osd_thread_info *info, struct osd_device *osd, struct osd_obj_seq *osd_seq)
static struct osd_obj_seq * osd_seq_load (struct osd_thread_info *info, struct osd_device *osd, u64 seq)
int osd_obj_map_lookup (struct osd_thread_info *info, struct osd_device *dev, const struct lu_fid *fid, struct osd_inode_id *id)
int osd_obj_map_insert (struct osd_thread_info *info, struct osd_device *osd, const struct lu_fid *fid, const struct osd_inode_id *id, handle_t *th)
int osd_obj_map_delete (struct osd_thread_info *info, struct osd_device *osd, const struct lu_fid *fid, handle_t *th)
int osd_obj_map_update (struct osd_thread_info *info, struct osd_device *osd, const struct lu_fid *fid, const struct osd_inode_id *id, handle_t *th)
int osd_obj_map_recover (struct osd_thread_info *info, struct osd_device *osd, struct inode *src_parent, struct dentry *src_child, const struct lu_fid *fid)
static struct dentry * osd_object_spec_find (struct osd_thread_info *info, struct osd_device *osd, const struct lu_fid *fid, char **name)
int osd_obj_spec_update (struct osd_thread_info *info, struct osd_device *osd, const struct lu_fid *fid, const struct osd_inode_id *id, handle_t *th)
int osd_obj_spec_insert (struct osd_thread_info *info, struct osd_device *osd, const struct lu_fid *fid, const struct osd_inode_id *id, handle_t *th)
int osd_obj_spec_lookup (struct osd_thread_info *info, struct osd_device *osd, const struct lu_fid *fid, struct osd_inode_id *id)
Variables
static const char remote_parent_dir [] = "REMOTE_PARENT_DIR"
Function Documentation
int osd_add_to_remote_parent (const struct lu_env * env, struct osd_device * osd, struct osd_object * obj, struct osd_thandle * oh)
Definition at line 221 of file osd_compat.c.
References __osd_xattr_set(), CDEBUG, D_INODE, DFID_NOBRACE, dt_object::do_lu, ldiskfs_inc_count(), lustre_mdt_attrs::lma_incompat, LMAI_REMOTE_PARENT, lu_object_fid(), lustre_lma_swab(), name, osd_device::od_mdt_map, osd_mdobj_map::omm_remote_parent, osd_object::oo_dt, osd_object::oo_inode, osd_child_dentry_by_inode(), osd_get_lma(), osd_ldiskfs_add_entry(), osd_name(), osd_oti_get(), osd_thandle::ot_handle, osd_thread_info::oti_mdt_attrs, osd_thread_info::oti_name, osd_thread_info::oti_obj_dentry, PFID, RETURN, and XATTR_NAME_LMA.
Referenced by osd_index_ea_insert().
int osd_delete_from_remote_parent (const struct lu_env * env, struct osd_device * osd, struct osd_object * obj, struct osd_thandle * oh)
Definition at line 261 of file osd_compat.c.
References __osd_xattr_set(), CDEBUG, D_INODE, DFID_NOBRACE, dt_object::do_lu, ldiskfs_dec_count(), likely, lustre_mdt_attrs::lma_incompat, LMAI_REMOTE_PARENT, lu_object_fid(), lustre_lma_swab(), name, osd_device::od_mdt_map, osd_mdobj_map::omm_remote_parent, osd_object::oo_dt, osd_object::oo_inode, osd_child_dentry_by_inode(), osd_get_lma(), osd_ldiskfs_find_entry, osd_name(), osd_oti_get(), osd_thandle::ot_handle, osd_thread_info::oti_mdt_attrs, osd_thread_info::oti_name, osd_thread_info::oti_obj_dentry, PFID, RETURN, and XATTR_NAME_LMA.
Referenced by osd_index_ea_delete(), and osd_object_destroy().
static int osd_last_rcvd_subdir_count (struct osd_device * osd) [static]
Definition at line 123 of file osd_compat.c.
References CDEBUG, CERROR, D_INFO, ENTRY, LASSERT, LAST_RCVD, le16_to_cpu, ll_lookup_one_len(), lr_server_data::lsd_subdir_count, lr_server_data::lsd_uuid, OBJ_SUBDIR_COUNT, osd_ldiskfs_read(), and osd_sb().
Referenced by osd_ost_init().
int osd_lookup_in_remote_parent (struct osd_thread_info * oti, struct osd_device * osd, const struct lu_fid * fid, struct osd_inode_id * id)
Definition at line 311 of file osd_compat.c.
References DFID_NOBRACE, ENTRY, le32_to_cpu, name, osd_device::od_mdt_map, osd_mdobj_map::omm_remote_parent, osd_add_oi_cache(), osd_child_dentry_by_inode(), osd_id_gen(), osd_ldiskfs_find_entry, OSD_OII_NOGEN, osd_thread_info::oti_env, osd_thread_info::oti_name, PFID, and RETURN.
Referenced by osd_fid_lookup().
static void osd_mdt_fini (struct osd_device * osd) [static]
Definition at line 207 of file osd_compat.c.
References OBD_FREE_PTR, osd_device::od_mdt_map, osd_device::od_ost_map, and osd_mdobj_map::omm_remote_parent.
Referenced by osd_obj_map_fini().
static int osd_mdt_init (const struct lu_env * env, struct osd_device * dev) [static]
Definition at line 162 of file osd_compat.c.
References cleanup(), ENTRY, GOTO, LMAC_NOT_IN_OI, lu_local_obj_fid(), OBD_ALLOC_PTR, OBD_FREE_PTR, osd_device::od_mdt_map, osd_device::od_mnt, osd_mdobj_map::omm_remote_parent, osd_ea_fid_set(), osd_oti_get(), osd_push_ctxt(), osd_sb(), osd_thread_info::oti_fid3, pop_ctxt(), remote_parent_dir, REMOTE_PARENT_DIR_OID, RETURN, and simple_mkdir().
Referenced by osd_obj_map_init().
static int osd_obj_add_entry (struct osd_thread_info * info, struct osd_device * osd, struct dentry * dir, char * name, const struct osd_inode_id * id, handle_t * th) [static]
Definition at line 696 of file osd_compat.c.
References ENTRY, LASSERT, ll_vfs_dq_init, OBD_ALLOC_PTR, OBD_FAIL_CHECK, OBD_FAIL_OSD_COMPAT_INVALID_ENTRY, OBD_FAIL_OSD_COMPAT_NO_ENTRY, osd_id_to_inode(), osd_ldiskfs_add_entry(), osd_sb(), osd_thread_info::oti_child_dentry, osd_thread_info::oti_inode, RETURN, and unlikely.
Referenced by osd_obj_map_insert(), and osd_obj_spec_insert().
static int osd_obj_del_entry (struct osd_thread_info * info, struct osd_device * osd, struct dentry * dird, char * name, handle_t * th) [static]
Definition at line 660 of file osd_compat.c.
References dir, ENTRY, LASSERT, ll_vfs_dq_init, osd_ldiskfs_find_entry, osd_thread_info::oti_child_dentry, and RETURN.
Referenced by osd_obj_map_delete().
int osd_obj_map_delete (struct osd_thread_info * info, struct osd_device * osd, const struct lu_fid * fid, handle_t * th)
Definition at line 1019 of file osd_compat.c.
References cleanup(), ENTRY, fid_to_ostid(), GOTO, LASSERT, name, osd_device::od_ost_map, osd_obj_seq::oos_dirs, osd_obj_seq::oos_subdir_count, osd_obj_del_entry(), osd_oid_name(), osd_seq_load(), ostid_id(), ostid_seq(), osd_thread_info::oti_ostid, and RETURN.
Referenced by osd_oi_delete().
void osd_obj_map_fini (struct osd_device * dev)
Definition at line 508 of file osd_compat.c.
References osd_mdt_fini(), and osd_ost_fini().
Referenced by osd_device_fini(), and osd_device_init0().
int osd_obj_map_init (const struct lu_env * env, struct osd_device * dev)
Definition at line 469 of file osd_compat.c.
References ENTRY, osd_mdt_init(), osd_ost_fini(), osd_ost_init(), and RETURN.
Referenced by osd_device_init0().
int osd_obj_map_insert (struct osd_thread_info * info, struct osd_device * osd, const struct lu_fid * fid, const struct osd_inode_id * id, handle_t * th)
Definition at line 973 of file osd_compat.c.
References ENTRY, fid_to_ostid(), LASSERT, name, osd_device::od_ost_map, osd_obj_seq::oos_dirs, osd_obj_seq::oos_subdir_count, osd_obj_add_entry(), osd_obj_update_entry(), osd_oid_name(), osd_seq_load(), ostid_id(), ostid_seq(), osd_thread_info::oti_ostid, RETURN, and unlikely.
Referenced by osd_oi_insert().
int osd_obj_map_lookup (struct osd_thread_info * info, struct osd_device * dev, const struct lu_fid * fid, struct osd_inode_id * id)
Definition at line 911 of file osd_compat.c.
References dir, ENTRY, fid_to_ostid(), LASSERT, le32_to_cpu, name, osd_device::od_ost_map, osd_obj_map::om_root, osd_obj_seq::oos_dirs, osd_obj_seq::oos_subdir_count, osd_id_gen(), osd_iget(), osd_ldiskfs_find_entry, osd_oid_name(), OSD_OII_NOGEN, osd_seq_load(), ostid_id(), ostid_seq(), osd_thread_info::oti_child_dentry, osd_thread_info::oti_ostid, and RETURN.
Referenced by osd_oi_lookup().
int osd_obj_map_recover (struct osd_thread_info * info, struct osd_device * osd, struct inode * src_parent, struct dentry * src_child, const struct lu_fid * fid)
Definition at line 1078 of file osd_compat.c.
References dir, DTO_INDEX_DELETE, DTO_INDEX_INSERT, DTO_OBJECT_DELETE, ENTRY, fid_is_last_id(), fid_to_ostid(), GOTO, LASSERT, LDISKFS_HT_MISC, ll_vfs_dq_init, ll_vfs_unlink, name, osd_obj_seq::oos_dirs, osd_obj_seq::oos_root, osd_obj_seq::oos_subdir_count, osd_dto_credits_noquota, osd_journal_start_sb, osd_ldiskfs_add_entry(), osd_ldiskfs_find_entry, osd_oid_name(), osd_sb(), osd_seq_load(), ostid_id(), ostid_seq(), osd_thread_info::oti_child_dentry, osd_thread_info::oti_ostid, RETURN, and unlikely.
Referenced by osd_ios_lf_fill().
int osd_obj_map_update (struct osd_thread_info * info, struct osd_device * osd, const struct lu_fid * fid, const struct osd_inode_id * id, handle_t * th)
Definition at line 1050 of file osd_compat.c.
References ENTRY, fid_to_ostid(), LASSERT, name, osd_obj_seq::oos_dirs, osd_obj_seq::oos_subdir_count, osd_obj_update_entry(), osd_oid_name(), osd_seq_load(), ostid_id(), ostid_seq(), osd_thread_info::oti_ostid, and RETURN.
Referenced by osd_oi_update().
int osd_obj_spec_insert (struct osd_thread_info * info, struct osd_device * osd, const struct lu_fid * fid, const struct osd_inode_id * id, handle_t * th)
Definition at line 1242 of file osd_compat.c.
References ENTRY, name, osd_obj_add_entry(), osd_object_spec_find(), and RETURN.
Referenced by osd_oi_insert().
int osd_obj_spec_lookup (struct osd_thread_info * info, struct osd_device * osd, const struct lu_fid * fid, struct osd_inode_id * id)
Definition at line 1263 of file osd_compat.c.
References ENTRY, fid_is_last_id(), ll_lookup_one_len(), name, osd_obj_seq::oos_root, osd_id_gen(), osd_lf_fid2name(), osd_sb(), osd_seq_load(), and RETURN.
Referenced by osd_oi_lookup().
int osd_obj_spec_update (struct osd_thread_info * info, struct osd_device * osd, const struct lu_fid * fid, const struct osd_inode_id * id, handle_t * th)
Definition at line 1221 of file osd_compat.c.
References ENTRY, name, osd_obj_update_entry(), osd_object_spec_find(), and RETURN.
Referenced by osd_oi_update().
static int osd_obj_update_entry (struct osd_thread_info * info, struct osd_device * osd, struct dentry * dir, const char * name, const struct lu_fid * fid, const struct osd_inode_id * id, handle_t * th) [static]
Update the specified OI mapping.
Return values:
1,changed nothing
0,changed successfully
-ve,on error
Definition at line 521 of file osd_compat.c.
References CERROR, cpu_to_le32, DFID, ENTRY, fid_idif_ost_idx(), fid_is_idif(), fid_to_ostid(), GOTO, LASSERT, LASSERTF, le32_to_cpu, ll_vfs_dq_init, lustre_mdt_attrs::lma_self_fid, lu_fid_eq(), osd_device::od_index, osd_inode_id::oii_gen, osd_inode_id::oii_ino, osd_get_idif(), osd_get_lma(), osd_id_gen(), osd_iget(), osd_is_ea_inode(), osd_ldiskfs_find_entry, osd_name(), OSD_OII_NOGEN, ostid_to_fid(), osd_thread_info::oti_child_dentry, osd_thread_info::oti_fid3, osd_thread_info::oti_id3, osd_thread_info::oti_mdt_attrs, osd_thread_info::oti_obj_dentry, osd_thread_info::oti_ostid, PFID, and unlikely.
Referenced by osd_obj_map_insert(), osd_obj_map_update(), and osd_obj_spec_update().
static struct dentry* osd_object_spec_find (struct osd_thread_info * info, struct osd_device * osd, const struct lu_fid * fid, char ** name) [static, read]
Definition at line 1195 of file osd_compat.c.
References CWARN, DFID, fid_is_last_id(), osd_lf_fid2name(), osd_sb(), osd_seq_load(), PFID, and RETURN.
Referenced by osd_obj_spec_insert(), and osd_obj_spec_update().
static void osd_oid_name (char * name, size_t name_size, const struct lu_fid * fid, u64 id) [inline, static]
Definition at line 760 of file osd_compat.c.
References fid_seq_is_idif(), fid_seq_is_mdt0(), fid_seq_is_rsvd(), LPU64, and LPX64i.
Referenced by osd_obj_map_delete(), osd_obj_map_insert(), osd_obj_map_lookup(), osd_obj_map_recover(), and osd_obj_map_update().
static void osd_ost_fini (struct osd_device * osd) [static]
Definition at line 443 of file osd_compat.c.
References ENTRY, EXIT, list_del_init(), list_for_each_entry_safe, OBD_FREE_PTR, osd_device::od_ost_map, osd_obj_map::om_root, osd_obj_map::om_seq_list, osd_obj_map::om_seq_list_lock, osd_obj_seq::oos_seq_list, and osd_seq_free().
Referenced by osd_obj_map_fini(), and osd_obj_map_init().
static int osd_ost_init (const struct lu_env * env, struct osd_device * dev) [static]
Definition at line 355 of file osd_compat.c.
References ENTRY, GOTO, INIT_LIST_HEAD, ll_lookup_one_len(), LMAC_FID_ON_OST, LMAC_NOT_IN_OI, lu_igif_build(), OBD_ALLOC_PTR, OBD_FREE_PTR, osd_device::od_maybe_new, osd_device::od_mnt, osd_device::od_ost_map, osd_obj_map::om_dir_init_mutex, osd_obj_map::om_root, osd_obj_map::om_seq_list, osd_obj_map::om_seq_list_lock, osd_obj_map::om_subdir_count, osd_ea_fid_set(), osd_last_rcvd_subdir_count(), osd_oti_get(), osd_push_ctxt(), osd_sb(), osd_thread_info::oti_fid3, pop_ctxt(), RETURN, and simple_mkdir().
Referenced by osd_obj_map_init().
static void osd_push_ctxt (const struct osd_device * dev, struct lvfs_run_ctxt * newctxt, struct lvfs_run_ctxt * save) [static]
Definition at line 61 of file osd_compat.c.
References lvfs_run_ctxt::dt, lvfs_run_ctxt::fs, OBD_SET_CTXT_MAGIC(), osd_device::od_mnt, push_ctxt(), lvfs_run_ctxt::pwd, lvfs_run_ctxt::pwdmnt, and lvfs_run_ctxt::umask.
Referenced by osd_mdt_init(), and osd_ost_init().
static struct osd_obj_seq* osd_seq_find (struct osd_obj_map * map, u64 seq) [static, read]
Definition at line 498 of file osd_compat.c.
References osd_obj_map::om_seq_list_lock, and osd_seq_find_locked().
Referenced by osd_seq_load().
static struct osd_obj_seq* osd_seq_find_locked (struct osd_obj_map * map, u64 seq) [static, read]
Definition at line 487 of file osd_compat.c.
References list_for_each_entry, osd_obj_map::om_seq_list, osd_obj_seq::oos_seq, and osd_obj_seq::oos_seq_list.
Referenced by osd_seq_find(), and osd_seq_load().
static void osd_seq_free (struct osd_obj_seq * osd_seq) [static]
Definition at line 424 of file osd_compat.c.
References OBD_FREE, OBD_FREE_PTR, osd_obj_seq::oos_dirs, osd_obj_seq::oos_root, and osd_obj_seq::oos_subdir_count.
Referenced by osd_ost_fini().
static struct osd_obj_seq* osd_seq_load (struct osd_thread_info * info, struct osd_device * osd, u64 seq) [static, read]
Definition at line 855 of file osd_compat.c.
References cleanup(), ENTRY, GOTO, INIT_LIST_HEAD, LASSERT, likely, list_add(), OBD_ALLOC_PTR, OBD_FREE_PTR, osd_device::od_ost_map, osd_obj_map::om_dir_init_mutex, osd_obj_map::om_root, osd_obj_map::om_seq_list, osd_obj_map::om_seq_list_lock, osd_obj_map::om_subdir_count, osd_obj_seq::oos_seq, osd_obj_seq::oos_seq_list, osd_obj_seq::oos_subdir_count, osd_seq_find(), osd_seq_find_locked(), osd_seq_load_locked(), and RETURN.
Referenced by osd_obj_map_delete(), osd_obj_map_insert(), osd_obj_map_lookup(), osd_obj_map_recover(), osd_obj_map_update(), osd_obj_spec_lookup(), and osd_object_spec_find().
static int osd_seq_load_locked (struct osd_thread_info * info, struct osd_device * osd, struct osd_obj_seq * osd_seq) [static]
Definition at line 770 of file osd_compat.c.
References dir, ENTRY, GOTO, LASSERT, LMAC_FID_ON_OST, LMAC_NOT_IN_OI, lu_igif_build(), OBD_ALLOC, OBD_FREE, osd_device::od_mnt, osd_device::od_ost_map, osd_obj_map::om_root, osd_obj_seq::oos_dirs, osd_obj_seq::oos_root, osd_obj_seq::oos_seq, osd_obj_seq::oos_subdir_count, osd_ea_fid_set(), osd_seq_name(), osd_thread_info::oti_fid3, RETURN, and simple_mkdir().
Referenced by osd_seq_load().
static void osd_seq_name (char * seq_name, size_t name_size, u64 seq) [inline, static]
Use LPU64 for legacy OST sequences, but use LPX64i for new sequences names, so that the O/{seq}/dN/{oid} more closely follows the DFID/PFID format.
This makes it easier to map from debug messages to objects in the future, and the legacy space of FID_SEQ_OST_MDT0 will be unused in the future.
Definition at line 752 of file osd_compat.c.
References fid_seq_is_idif(), fid_seq_is_mdt0(), fid_seq_is_rsvd(), LPU64, and LPX64i.
Referenced by osd_seq_load_locked().
static struct dentry* simple_mkdir (struct dentry * dir, struct vfsmount * mnt, const char * name, int mode, int fix) [static, read]
Definition at line 76 of file osd_compat.c.
References CDEBUG, CERROR, D_CONFIG, D_INODE, ENTRY, GOTO, ll_lookup_one_len(), and RETURN.
Referenced by osd_mdt_init(), osd_ost_init(), and osd_seq_load_locked().
Variable Documentation
const char remote_parent_dir[] = "REMOTE_PARENT_DIR" [static]
Definition at line 161 of file osd_compat.c.
Referenced by osd_mdt_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.