Lustre: lustre/osp/osp_md_object.c File Reference
lustre/osp/osp_md_object.c File Reference
#include <llog_swab.h>
#include <lustre_log.h>
#include "osp_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_MDS
#define OUT_UPDATE_BUFFER_SIZE_ADD 4096
#define OUT_UPDATE_BUFFER_SIZE_MAX (256 * 4096)
Functions
static int osp_object_create_interpreter (const struct lu_env *env, struct object_update_reply *reply, struct ptlrpc_request *req, struct osp_object *obj, void *data, int index, int rc)
Interpreter call for object creation.
int osp_md_declare_object_create (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *th)
Implementation of dt_object_operations::do_declare_create.
struct object_update * update_buffer_get_update (struct object_update_request *request, unsigned int index)
int osp_md_object_create (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *th)
Implementation of dt_object_operations::do_create.
static int osp_md_declare_ref_del (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Implementation of dt_object_operations::do_declare_ref_del.
static int osp_md_ref_del (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Implementation of dt_object_operations::do_ref_del.
static int osp_md_declare_ref_add (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Implementation of dt_object_operations::do_declare_ref_del.
static int osp_md_ref_add (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Implementation of dt_object_operations::do_ref_add.
static void osp_md_ah_init (const struct lu_env *env, struct dt_allocation_hint *ah, struct dt_object *parent, struct dt_object *child, umode_t child_mode)
Implementation of dt_object_operations::do_ah_init.
int osp_md_declare_attr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_attr *attr, struct thandle *th)
Implementation of dt_object_operations::do_declare_attr_get.
int osp_md_attr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_attr *attr, struct thandle *th)
Implementation of dt_object_operations::do_attr_set.
static void osp_md_object_read_lock (const struct lu_env *env, struct dt_object *dt, unsigned role)
Implementation of dt_object_operations::do_read_lock.
static void osp_md_object_write_lock (const struct lu_env *env, struct dt_object *dt, unsigned role)
Implementation of dt_object_operations::do_write_lock.
static void osp_md_object_read_unlock (const struct lu_env *env, struct dt_object *dt)
Implementation of dt_object_operations::do_read_unlock.
static void osp_md_object_write_unlock (const struct lu_env *env, struct dt_object *dt)
Implementation of dt_object_operations::do_write_unlock.
static int osp_md_object_write_locked (const struct lu_env *env, struct dt_object *dt)
Implementation of dt_object_operations::do_write_locked.
static int osp_md_index_lookup (const struct lu_env *env, struct dt_object *dt, struct dt_rec *rec, const struct dt_key *key)
Implementation of dt_index_operations::dio_lookup.
static int osp_md_declare_index_insert (const struct lu_env *env, struct dt_object *dt, const struct dt_rec *rec, const struct dt_key *key, struct thandle *th)
Implementation of dt_index_operations::dio_declare_insert.
static int osp_md_index_insert (const struct lu_env *env, struct dt_object *dt, const struct dt_rec *rec, const struct dt_key *key, struct thandle *th, int ignore_quota)
Implementation of dt_index_operations::dio_insert.
static int osp_md_declare_index_delete (const struct lu_env *env, struct dt_object *dt, const struct dt_key *key, struct thandle *th)
Implementation of dt_index_operations::dio_declare_delete.
static int osp_md_index_delete (const struct lu_env *env, struct dt_object *dt, const struct dt_key *key, struct thandle *th)
Implementation of dt_index_operations::dio_delete.
static int osp_md_index_it_next (const struct lu_env *env, struct dt_it *di)
Implementation of dt_index_operations::dio_it.next.
static struct dt_key * osp_it_key (const struct lu_env *env, const struct dt_it *di)
Implementation of dt_index_operations::dio_it.key.
static int osp_it_key_size (const struct lu_env *env, const struct dt_it *di)
Implementation of dt_index_operations::dio_it.key_size.
static int osp_md_index_it_rec (const struct lu_env *env, const struct dt_it *di, struct dt_rec *rec, __u32 attr)
Implementation of dt_index_operations::dio_it.rec.
static int osp_it_load (const struct lu_env *env, const struct dt_it *di, __u64 hash)
Implementation of dt_index_operations::dio_it.load.
static int osp_md_index_try (const struct lu_env *env, struct dt_object *dt, const struct dt_index_features *feat)
Implementation of dt_object_operations::do_index_try.
static int osp_md_object_lock (const struct lu_env *env, struct dt_object *dt, struct lustre_handle *lh, struct ldlm_enqueue_info *einfo, union ldlm_policy_data *policy)
Implementation of dt_object_operations::do_object_lock.
static int osp_md_object_unlock (const struct lu_env *env, struct dt_object *dt, struct ldlm_enqueue_info *einfo, union ldlm_policy_data *policy)
Implementation of dt_object_operations::do_object_unlock.
int osp_md_declare_object_destroy (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Implement OSP layer dt_object_operations::do_declare_destroy() interface.
int osp_md_object_destroy (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Implement OSP layer dt_object_operations::do_destroy() interface.
static ssize_t osp_md_declare_write (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, loff_t pos, struct thandle *th)
Implementation of dt_body_operations::dbo_declare_write.
static ssize_t osp_md_write (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, loff_t *pos, struct thandle *th, int ignore_quota)
Implementation of dt_body_operations::dbo_write.
static ssize_t osp_md_read (const struct lu_env *env, struct dt_object *dt, struct lu_buf *rbuf, loff_t *pos)
Variables
struct dt_index_operations osp_md_index_ops
struct dt_object_operations osp_md_obj_ops
struct dt_body_operations osp_md_body_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 54 of file osp_md_object.c.
#define OUT_UPDATE_BUFFER_SIZE_ADD 4096
Definition at line 60 of file osp_md_object.c.
#define OUT_UPDATE_BUFFER_SIZE_MAX (256 * 4096)
Definition at line 61 of file osp_md_object.c.
Function Documentation
static struct dt_key* osp_it_key (const struct lu_env * env, const struct dt_it * di) [static, read]
Implementation of dt_index_operations::dio_it.key.
Get the key at current iterator poisiton. These iteration methods (dio_it) will only be used for iterating the remote directory, so the key is the name of the directory entry.
Parameters:
[in] env execution environment
[in] di iterator of this iteration
Return values:
name of the current entry
Definition at line 732 of file osp_md_object.c.
References dt_key, lu_dirent::lde_name, and osp_it::ooi_ent.
static int osp_it_key_size (const struct lu_env * env, const struct dt_it * di) [static]
Implementation of dt_index_operations::dio_it.key_size.
Get the key size at current iterator poisiton. These iteration methods (dio_it) will only be used for iterating the remote directory, so the key size is the name size of the directory entry.
Parameters:
[in] env execution environment
[in] di iterator of this iteration
Return values:
name size of the current entry
Definition at line 754 of file osp_md_object.c.
References lu_dirent::lde_namelen, le16_to_cpu, and osp_it::ooi_ent.
static int osp_it_load (const struct lu_env * env, const struct dt_it * di, __u64 hash) [static]
Implementation of dt_index_operations::dio_it.load.
Locate the iteration cursor to the specified position (cookie).
Parameters:
[in] env pointer to the thread context
[in] di pointer to the iteration structure
[in] hash the specified position
Return values:
positive number for locating to the exactly position or the next
0 for arriving at the end of the iteration
negative error number on failure
Definition at line 803 of file osp_md_object.c.
References osp_it::ooi_next, and osp_md_index_it_next().
static void osp_md_ah_init (const struct lu_env * env, struct dt_allocation_hint * ah, struct dt_object * parent, struct dt_object * child, umode_t child_mode) [static]
Implementation of dt_object_operations::do_ah_init.
Initialize the allocation hint for object creation, which is usually called before the creation, and these hints (parent and child mode) will be sent to the remote Object Update Target (OUT) and used in the object create process, same as OSD object creation.
Parameters:
[in] env execution environment
[in] ah the hint to be initialized
[in] parent the parent of the object
[in] child the object to be created
[in] child_mode the mode of the created object
Definition at line 311 of file osp_md_object.c.
References dt_allocation_hint::dah_mode, dt_allocation_hint::dah_parent, and LASSERT.
int osp_md_attr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_attr * attr, struct thandle * th)
Implementation of dt_object_operations::do_attr_set.
Set attributes to the specified remote object.
Add the OUT_ATTR_SET sub-request into the OUT RPC that will be flushed when the transaction stop.
Parameters:
[in] env execution environment
[in] dt object to set attributes
[in] attr attributes to be set
[in] th the transaction handle
Return values:
0 if packing attr_set succeeds.
negative errno if packing fails.
Definition at line 359 of file osp_md_object.c.
References dt_object::do_lu, LASSERT, lu_object_fid(), osp_update_rpc_pack, OUT_ATTR_SET, and thandle_to_osp_update_request().
Referenced by osp_attr_set().
int osp_md_declare_attr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_attr * attr, struct thandle * th)
Implementation of dt_object_operations::do_declare_attr_get.
Create the osp_update_request to track the update for this OSP in the transaction.
Parameters:
[in] env execution environment
[in] dt object on which to set attributes
[in] attr attributes to be set
[in] th the transaction handle
Return values:
0 if preparation succeeds.
negative errno if preparation fails.
Definition at line 337 of file osp_md_object.c.
References osp_trans_update_request_create().
Referenced by osp_declare_attr_set().
static int osp_md_declare_index_delete (const struct lu_env * env, struct dt_object * dt, const struct dt_key * key, struct thandle * th) [static]
Implementation of dt_index_operations::dio_declare_delete.
Create the osp_update_request to track the update for this OSP in the transaction.
Parameters:
[in] env execution environment
[in] dt object for which to delete index
[in] key key of the index
[in] th the transaction handle
Return values:
0 if preparation succeeds.
negative errno if preparation fails.
Definition at line 630 of file osp_md_object.c.
References osp_trans_update_request_create().
static int osp_md_declare_index_insert (const struct lu_env * env, struct dt_object * dt, const struct dt_rec * rec, const struct dt_key * key, struct thandle * th) [static]
Implementation of dt_index_operations::dio_declare_insert.
Create the osp_update_request to track the update for this OSP in the transaction.
Parameters:
[in] env execution environment
[in] dt object for which to insert index
[in] rec record of the index which will be inserted
[in] key key of the index which will be inserted
[in] th the transaction handle
Return values:
0 if preparation succeeds.
negative errno if preparation fails.
Definition at line 573 of file osp_md_object.c.
References osp_trans_update_request_create().
int osp_md_declare_object_create (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof, struct thandle * th)
Implementation of dt_object_operations::do_declare_create.
Create the osp_update_request to track the update for this OSP in the transaction.
Parameters:
[in] env execution environment
[in] dt remote object to be created
[in] attr attribute of the created object
[in] hint creation hint
[in] dof creation format information
[in] th the transaction handle
Return values:
0 if preparation succeeds.
negative errno if preparation fails.
Definition at line 121 of file osp_md_object.c.
References dt2osp_obj(), osp_object::opo_ooa, osp_oac_init(), and osp_trans_update_request_create().
Referenced by osp_declare_object_create().
int osp_md_declare_object_destroy (const struct lu_env * env, struct dt_object * dt, struct thandle * th)
Implement OSP layer dt_object_operations::do_declare_destroy() interface.
Create the dt_update_request to track the update for this OSP in the transaction.
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the OSP layer dt_object to be destroyed
[in] th pointer to the transaction handler
Return values:
0 for success
negative error number on failure
Definition at line 962 of file osp_md_object.c.
References osp_trans_update_request_create().
static int osp_md_declare_ref_add (const struct lu_env * env, struct dt_object * dt, struct thandle * th) [static]
Implementation of dt_object_operations::do_declare_ref_del.
Create the osp_update_request to track the update for this OSP in the transaction.
Parameters:
[in] env execution environment
[in] dt object on which to increase the reference count.
[in] th the transaction handle.
Return values:
0 if preparation succeeds.
negative errno if preparation fails.
Definition at line 264 of file osp_md_object.c.
References osp_trans_update_request_create().
static int osp_md_declare_ref_del (const struct lu_env * env, struct dt_object * dt, struct thandle * th) [static]
Implementation of dt_object_operations::do_declare_ref_del.
Create the osp_update_request to track the update for this OSP in the transaction.
Parameters:
[in] env execution environment
[in] dt object to decrease the reference count.
[in] th the transaction handle of refcount decrease.
Return values:
0 if preparation succeeds.
negative errno if preparation fails.
Definition at line 218 of file osp_md_object.c.
References osp_trans_update_request_create().
static ssize_t osp_md_declare_write (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, loff_t pos, struct thandle * th) [static]
Implementation of dt_body_operations::dbo_declare_write.
Create the osp_update_request to track the update for this OSP in the transaction.
Parameters:
[in] env execution environment
[in] dt object to be written
[in] buf buffer to write which includes an embedded size field
[in] pos offet in the object to start writing at
[in] th transaction handle
Return values:
0 if preparation succeeds.
negative errno if preparation fails.
Definition at line 1053 of file osp_md_object.c.
References dt2osp_dev(), dt2osp_obj(), osp_device::opd_update, osp_trans_update_request_create(), and thandle::th_dev.
static int osp_md_index_delete (const struct lu_env * env, struct dt_object * dt, const struct dt_key * key, struct thandle * th) [static]
Implementation of dt_index_operations::dio_delete.
Add an OUT_INDEX_DELETE sub-request into the OUT RPC that will be flushed when the transaction stop.
Parameters:
[in] env execution environment
[in] dt object for which to delete index
[in] key key of the index which will be deleted
[in] th the transaction handle
Return values:
0 if packing index delete succeeds.
negative errno if packing fails.
Definition at line 652 of file osp_md_object.c.
References dt_object::do_lu, LASSERT, lu_object_fid(), osp_update_rpc_pack, OUT_INDEX_DELETE, and thandle_to_osp_update_request().
static int osp_md_index_insert (const struct lu_env * env, struct dt_object * dt, const struct dt_rec * rec, const struct dt_key * key, struct thandle * th, int ignore_quota) [static]
Implementation of dt_index_operations::dio_insert.
Add an OUT_INDEX_INSERT sub-request into the OUT RPC that will be flushed when the transaction stop.
Parameters:
[in] env execution environment
[in] dt object for which to insert index
[in] rec record of the index to be inserted
[in] key key of the index to be inserted
[in] th the transaction handle
[in] ignore_quota quota enforcement for insert
Return values:
0 if packing index insert succeeds.
negative errno if packing fails.
Definition at line 598 of file osp_md_object.c.
References dt_object::do_lu, LASSERT, lu_object_fid(), osp_update_rpc_pack, OUT_INDEX_INSERT, and thandle_to_osp_update_request().
static int osp_md_index_it_next (const struct lu_env * env, struct dt_it * di) [static]
Implementation of dt_index_operations::dio_it.next.
Advance the pointer of the iterator to the next entry. It shares a similar internal implementation with osp_orphan_it_next(), which is being used for remote orphan index object. This method will be used for remote directory.
Parameters:
[in] env execution environment
[in] di iterator of this iteration
Return values:
0 if the pointer is advanced successfully.
1 if it reaches to the end of the index object.
negative errno if the pointer cannot be advanced.
Definition at line 683 of file osp_md_object.c.
References ENTRY, lu_dirent::lde_reclen, le16_to_cpu, lu_idxpage::lip_entries, lu_idxpage::lip_nr, osp_it::ooi_cur_idxpage, osp_it::ooi_ent, osp_it::ooi_pos_ent, osp_it_next_page(), and RETURN.
Referenced by osp_it_load().
static int osp_md_index_it_rec (const struct lu_env * env, const struct dt_it * di, struct dt_rec * rec, __u32 attr) [static]
Implementation of dt_index_operations::dio_it.rec.
Get the record at current iterator position. These iteration methods (dio_it) will only be used for iterating the remote directory, so it uses lu_dirent_calc_size() to calculate the record size.
Parameters:
[in] env execution environment
[in] di iterator of this iteration
[out] rec the record to be returned
[in] attr attributes of the index object, so it knows how to pack the entry.
Return values:
only return 0 for now
Definition at line 777 of file osp_md_object.c.
References lu_dirent::lde_namelen, le16_to_cpu, lu_dirent_calc_size(), and osp_it::ooi_ent.
static int osp_md_index_lookup (const struct lu_env * env, struct dt_object * dt, struct dt_rec * rec, const struct dt_key * key) [static]
Implementation of dt_index_operations::dio_lookup.
Look up record by key under a remote index object. It packs lookup update into RPC, sends to the remote OUT and waits for the lookup result.
Parameters:
[in] env execution environment
[in] dt index object to lookup
[out] rec record in which to return lookup result
[in] key key of index which will be looked up
Return values:
1 if the lookup succeeds.
negative errno if the lookup fails.
Definition at line 480 of file osp_md_object.c.
References CERROR, dt_device::dd_lu_dev, DFID, dt_object::do_lu, ENTRY, fid_is_sane(), GOTO, lu_buf::lb_buf, lu_buf::lb_len, lu_device::ld_obd, lu_object::lo_dev, lu2osp_dev(), lu_object_fid(), lustre_swab_lu_fid, obd_device::obd_name, object_update_result_data_get(), osp_device::opd_dt_dev, osp_thread_info::osi_lb2, osp_env_info(), osp_remote_sync(), osp_update_request_create(), osp_update_request_destroy(), osp_update_rpc_pack, object_update_reply::ourp_magic, OUT_INDEX_LOOKUP, OUT_UPDATE_REPLY_SIZE, PFID, ptlrpc_rep_need_swab(), ptlrpc_req_finished(), req_capsule_server_sized_get(), RETURN, RMF_OUT_UPDATE_REPLY, ptlrpc_request::rq_pill, and UPDATE_REPLY_MAGIC.
static int osp_md_index_try (const struct lu_env * env, struct dt_object * dt, const struct dt_index_features * feat) [static]
Implementation of dt_object_operations::do_index_try.
Try to initialize the index API pointer for the given object. This is the entry point of the index API, i.e. we must call this method to initialize the index object before calling other index methods.
Parameters:
[in] env execution environment
[in] dt index object to be initialized
[in] feat the index feature of the object
Return values:
0 if the initialization succeeds.
negative errno if the initialization fails.
Definition at line 855 of file osp_md_object.c.
References dt_object::do_index_ops.
int osp_md_object_create (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof, struct thandle * th)
Implementation of dt_object_operations::do_create.
It adds an OUT_CREATE sub-request into the OUT RPC that will be flushed when the transaction stop, and sets necessary flags for created object.
Parameters:
[in] env execution environment
[in] dt object to be created
[in] attr attribute of the created object
[in] hint creation hint
[in] dof creation format information
[in] th the transaction handle
Return values:
0 if packing creation succeeds.
negative errno if packing creation fails.
Definition at line 173 of file osp_md_object.c.
References dt_object::do_lu, dt2osp_obj(), GOTO, lu_attr::la_mode, LA_TYPE, lu_attr::la_valid, LASSERT, lu_object::lo_header, lu_object_header::loh_attr, LOHA_EXISTS, lu_object_fid(), osp_object_attr::ooa_attr, osp_object::opo_non_exist, osp_object::opo_ooa, osp_insert_update_callback(), osp_object_create_interpreter(), osp_update_rpc_pack, OUT_CREATE, and thandle_to_osp_update_request().
Referenced by osp_object_create().
int osp_md_object_destroy (const struct lu_env * env, struct dt_object * dt, struct thandle * th)
Implement OSP layer dt_object_operations::do_destroy() interface.
Pack the destroy update into the RPC buffer, which will be sent to the remote MDT during transaction stop.
It also marks the object as non-cached.
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the OSP layer dt_object to be destroyed
[in] th pointer to the transaction handler
Return values:
0 for success
negative error number on failure
Definition at line 983 of file osp_md_object.c.
References dt_object::do_lu, dt2osp_obj(), ENTRY, LASSERT, lu_object::lo_dev, lu_object::lo_header, lu_object_header::loh_flags, lu2osp_dev(), lu_object_fid(), LU_OBJECT_HEARD_BANSHEE, osp_device::opd_connect_mdt, osp_object::opo_non_exist, osp_insert_update_callback(), osp_update_rpc_pack, OUT_DESTROY, RETURN, and thandle_to_osp_update_request().
static int osp_md_object_lock (const struct lu_env * env, struct dt_object * dt, struct lustre_handle * lh, struct ldlm_enqueue_info * einfo, union ldlm_policy_data * policy) [static]
Implementation of dt_object_operations::do_object_lock.
Enqueue a lock (by ldlm_cli_enqueue()) of remote object on the remote MDT, which will lock the object in the global namespace. And because the cross-MDT locks are relatively rare compared with normal local MDT operation, let's release it right away, instead of putting it into the LRU list.
Parameters:
[in] env execution environment
[in] dt object to be locked
[out] lh lock handle
[in] einfo enqueue information
[in] policy lock policy
Return values:
ELDLM_OK if locking the object succeeds.
negative errno if locking fails.
Definition at line 880 of file osp_md_object.c.
References __u64, dt_device::dd_lu_dev, dt_object::do_lu, dt2osp_dev(), ldlm_enqueue_info::ei_mode, ldlm_enqueue_info::ei_nonblock, ELDLM_OK, LASSERT, LCK_EX, LCK_PW, lu_device::ld_obd, lu_device::ld_site, ldlm_cli_enqueue(), ldlm_enqueue_pack(), LDLM_FL_BLOCK_NOWAIT, LDLM_FL_COS_INCOMPAT, LDLM_FL_NO_LRU, lu_object::lo_dev, lu_site::ls_top_dev, lu2dt_dev(), LVB_T_NONE, obd_device::obd_recovering, osp_device::opd_exp, ptlrpc_req_finished(), RETURN, and ptlrpc_request::rq_allow_replay.
static void osp_md_object_read_lock (const struct lu_env * env, struct dt_object * dt, unsigned role) [static]
Implementation of dt_object_operations::do_read_lock.
osp_md_object_{read,write}_lock() will only lock the remote object in the local cache, which uses the semaphore (opo_sem) inside the osp_object to lock the object. Note: it will not lock the object in the whole cluster, which relies on the LDLM lock.
Parameters:
[in] env execution environment
[in] dt object to be locked
[in] role lock role from MDD layer, see mdd_object_role().
Definition at line 385 of file osp_md_object.c.
References dt2osp_obj(), LASSERT, osp_object::opo_owner, and osp_object::opo_sem.
static void osp_md_object_read_unlock (const struct lu_env * env, struct dt_object * dt) [static]
Implementation of dt_object_operations::do_read_unlock.
Unlock the read lock of remote object.
Parameters:
[in] env execution environment
[in] dt object to be unlocked
Definition at line 424 of file osp_md_object.c.
References dt2osp_obj(), and osp_object::opo_sem.
static int osp_md_object_unlock (const struct lu_env * env, struct dt_object * dt, struct ldlm_enqueue_info * einfo, union ldlm_policy_data * policy) [static]
Implementation of dt_object_operations::do_object_unlock.
Cancel a lock of a remote object.
Parameters:
[in] env execution environment
[in] dt object to be unlocked
[in] einfo lock enqueue information
[in] policy lock policy
Return values:
Only return 0 for now.
Definition at line 936 of file osp_md_object.c.
References ldlm_enqueue_info::ei_cbdata, ldlm_enqueue_info::ei_mode, and ldlm_lock_decref().
static void osp_md_object_write_lock (const struct lu_env * env, struct dt_object * dt, unsigned role) [static]
Implementation of dt_object_operations::do_write_lock.
Lock the remote object in write mode.
Parameters:
[in] env execution environment
[in] dt object to be locked
[in] role lock role from MDD layer, see mdd_object_role().
Definition at line 405 of file osp_md_object.c.
References dt2osp_obj(), LASSERT, osp_object::opo_owner, and osp_object::opo_sem.
static int osp_md_object_write_locked (const struct lu_env * env, struct dt_object * dt) [static]
Implementation of dt_object_operations::do_write_locked.
Test if the object is locked in write mode.
Parameters:
[in] env execution environment
[in] dt object to be tested
Definition at line 458 of file osp_md_object.c.
References dt2osp_obj(), and osp_object::opo_owner.
static void osp_md_object_write_unlock (const struct lu_env * env, struct dt_object * dt) [static]
Implementation of dt_object_operations::do_write_unlock.
Unlock the write lock of remote object.
Parameters:
[in] env execution environment
[in] dt object to be unlocked
Definition at line 440 of file osp_md_object.c.
References dt2osp_obj(), LASSERT, osp_object::opo_owner, and osp_object::opo_sem.
static ssize_t osp_md_read (const struct lu_env * env, struct dt_object * dt, struct lu_buf * rbuf, loff_t * pos) [static]
Definition at line 1126 of file osp_md_object.c.
References ptlrpc_bulk_frag_ops::add_iov_frag, ptlrpc_bulk_desc::bd_frag_ops, CDEBUG, CERROR, client_obd::cl_import, obd_device::cli, D_INFO, dt_device::dd_lu_dev, DFID, dt_object::do_lu, ENTRY, GOTO, lu_buf::lb_buf, lu_buf::lb_len, lu_device::ld_obd, lu_object::lo_dev, lu2osp_dev(), lu_object_fid(), MDS_BULK_PORTAL, obd_device::obd_name, object_update_result_data_get(), osp_device::opd_dt_dev, osp_device::opd_obd, orr_le_to_cpu(), out_read_reply::orr_offset, out_read_reply::orr_size, osp_thread_info::osi_lb2, osp_env_info(), osp_prep_update_req(), osp_update_request_create(), osp_update_request_destroy(), osp_update_rpc_pack, object_update_reply::ourp_magic, OUT_BULK_BUFFER_SIZE, OUT_READ, OUT_UPDATE_REPLY_SIZE, PFID, PTLRPC_BULK_BUF_KVEC, ptlrpc_bulk_kvec_ops, PTLRPC_BULK_PUT_SINK, ptlrpc_prep_bulk_imp(), ptlrpc_queue_wait(), ptlrpc_req_finished(), req_capsule_server_sized_get(), RETURN, RMF_OUT_UPDATE_REPLY, ptlrpc_request::rq_allow_replay, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_pill, sptlrpc_cli_unwrap_bulk_read(), obd_device::u, and UPDATE_REPLY_MAGIC.
static int osp_md_ref_add (const struct lu_env * env, struct dt_object * dt, struct thandle * th) [static]
Implementation of dt_object_operations::do_ref_add.
Add an OUT_REF_ADD sub-request into the OUT RPC that will be flushed when the transaction stop.
Parameters:
[in] env execution environment
[in] dt object on which to increase the reference count
[in] th the transaction handle
Return values:
0 if packing ref_add succeeds.
negative errno if packing fails.
Definition at line 283 of file osp_md_object.c.
References dt_object::do_lu, LASSERT, lu_object_fid(), osp_update_rpc_pack, OUT_REF_ADD, and thandle_to_osp_update_request().
static int osp_md_ref_del (const struct lu_env * env, struct dt_object * dt, struct thandle * th) [static]
Implementation of dt_object_operations::do_ref_del.
Add an OUT_REF_DEL sub-request into the OUT RPC that will be flushed when the transaction stop.
Parameters:
[in] env execution environment
[in] dt object to decrease the reference count
[in] th the transaction handle
Return values:
0 if packing ref_del succeeds.
negative errno if packing fails.
Definition at line 237 of file osp_md_object.c.
References dt_object::do_lu, LASSERT, lu_object_fid(), osp_update_rpc_pack, OUT_REF_DEL, and thandle_to_osp_update_request().
static ssize_t osp_md_write (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, loff_t * pos, struct thandle * th, int ignore_quota) [static]
Implementation of dt_body_operations::dbo_write.
Pack the write object update into the RPC buffer, which will be sent to the remote MDT during transaction stop.
Parameters:
[in] env execution environment
[in] dt object to be written
[in] buf buffer to write which includes an embedded size field
[in] pos offet in the object to start writing at
[in] th transaction handle
[in] ignore_quota quota enforcement for this write
Return values:
the buffer size in bytes if packing succeeds.
negative errno if packing fails.
Definition at line 1090 of file osp_md_object.c.
References CDEBUG, D_INFO, DFID, dt_object::do_lu, dt2osp_obj(), ENTRY, lu_attr::la_size, LA_SIZE, lu_attr::la_valid, LASSERT, lu_buf::lb_len, LPU64, lu_object_fid(), osp_object_attr::ooa_attr, osp_object::opo_ooa, osp_check_and_set_rpc_version(), osp_update_rpc_pack, OUT_WRITE, PFID, RETURN, thandle_to_osp_thandle(), and thandle_to_osp_update_request().
static int osp_object_create_interpreter (const struct lu_env * env, struct object_update_reply * reply, struct ptlrpc_request * req, struct osp_object * obj, void * data, int index, int rc) [static]
Interpreter call for object creation.
Object creation interpreter, which will be called after creating the remote object to set flags and status.
Parameters:
[in] env execution environment
[in] reply update reply
[in] req ptlrpc update request for creating object
[in] obj object to be created
[in] data data used in this function.
[in] index index(position) of create update in the whole updates
[in] rc update result on the remote MDT.
Return values:
only return 0 for now
Definition at line 80 of file osp_md_object.c.
References dt_object::do_lu, lu_attr::la_valid, lu_object::lo_header, lu_object_header::loh_attr, LOHA_EXISTS, osp_object_attr::ooa_attr, osp_object::opo_lock, osp_object::opo_non_exist, osp_object::opo_obj, and osp_object::opo_ooa.
Referenced by osp_md_object_create().
struct object_update* update_buffer_get_update (struct object_update_request * request, unsigned int index) [read]
Definition at line 141 of file osp_md_object.c.
References object_update_size(), object_update_request::ourq_count, and object_update_request::ourq_updates.
Referenced by osp_insert_async_request().
Variable Documentation
struct dt_body_operations osp_md_body_ops
Initial value:
 {
        .dbo_declare_write      = osp_md_declare_write,
        .dbo_write              = osp_md_write,
        .dbo_read               = osp_md_read,
}
Definition at line 1236 of file osp_md_object.c.
Referenced by osp_object_init().
struct dt_index_operations osp_md_index_ops
Initial value:
 {
        .dio_lookup         = osp_md_index_lookup,
        .dio_declare_insert = osp_md_declare_index_insert,
        .dio_insert         = osp_md_index_insert,
        .dio_declare_delete = osp_md_declare_index_delete,
        .dio_delete         = osp_md_index_delete,
        .dio_it     = {
                .init     = osp_it_init,
                .fini     = osp_it_fini,
                .get      = osp_it_get,
                .put      = osp_it_put,
                .next     = osp_md_index_it_next,
                .key      = osp_it_key,
                .key_size = osp_it_key_size,
                .rec      = osp_md_index_it_rec,
                .store    = osp_it_store,
                .load     = osp_it_load,
                .key_rec  = osp_it_key_rec,
        }
}
Definition at line 820 of file osp_md_object.c.
Referenced by osp_index_try().
struct dt_object_operations osp_md_obj_ops
Initial value:
 {
        .do_read_lock         = osp_md_object_read_lock,
        .do_write_lock        = osp_md_object_write_lock,
        .do_read_unlock       = osp_md_object_read_unlock,
        .do_write_unlock      = osp_md_object_write_unlock,
        .do_write_locked      = osp_md_object_write_locked,
        .do_declare_create    = osp_md_declare_object_create,
        .do_create            = osp_md_object_create,
        .do_declare_ref_add   = osp_md_declare_ref_add,
        .do_ref_add           = osp_md_ref_add,
        .do_declare_ref_del   = osp_md_declare_ref_del,
        .do_ref_del           = osp_md_ref_del,
        .do_declare_destroy   = osp_md_declare_object_destroy,
        .do_destroy           = osp_md_object_destroy,
        .do_ah_init           = osp_md_ah_init,
        .do_attr_get          = osp_attr_get,
        .do_declare_attr_set  = osp_md_declare_attr_set,
        .do_attr_set          = osp_md_attr_set,
        .do_xattr_get         = osp_xattr_get,
        .do_declare_xattr_set = osp_declare_xattr_set,
        .do_xattr_set         = osp_xattr_set,
        .do_declare_xattr_del = osp_declare_xattr_del,
        .do_xattr_del         = osp_xattr_del,
        .do_index_try         = osp_md_index_try,
        .do_object_lock       = osp_md_object_lock,
        .do_object_unlock     = osp_md_object_unlock,
}
Definition at line 1010 of file osp_md_object.c.
Referenced by osp_object_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.