Lustre: lustre/osp/osp_internal.h File Reference
lustre/osp/osp_internal.h File Reference
#include <obd.h>
#include <obd_class.h>
#include <dt_object.h>
#include <md_object.h>
#include <lustre_fid.h>
#include <lustre_update.h>
#include <lu_target.h>
#include <lustre_mdc.h>
Data Structures
struct osp_id_tracker
struct osp_precreate
struct osp_update_request_sub
struct osp_update_request
struct osp_updates
struct osp_device
struct osp_xattr_entry
struct osp_object_attr
struct osp_object
struct osp_thread_info
struct osp_it
struct osp_thandle
struct osp_txn_info
Defines
#define opd_pre_lock opd_pre->osp_pre_lock
#define opd_pre_used_fid opd_pre->osp_pre_used_fid
#define opd_pre_last_created_fid opd_pre->osp_pre_last_created_fid
#define opd_pre_reserved opd_pre->osp_pre_reserved
#define opd_pre_user_waitq opd_pre->osp_pre_user_waitq
#define opd_pre_status opd_pre->osp_pre_status
#define opd_pre_create_count opd_pre->osp_pre_create_count
#define opd_pre_min_create_count opd_pre->osp_pre_min_create_count
#define opd_pre_max_create_count opd_pre->osp_pre_max_create_count
#define opd_pre_create_slow opd_pre->osp_pre_create_slow
#define opd_pre_recovering opd_pre->osp_pre_recovering
#define OSP_THANDLE_MAGIC 0x20141214
#define osp_init_rpc_lock(lck) mdc_init_rpc_lock(lck)
#define osp_update_rpc_pack(env, name, our, op,...)
Typedefs
typedef int(* osp_update_interpreter_t)(const struct lu_env *env, struct object_update_reply *rep, struct ptlrpc_request *req, struct osp_object *obj, void *data, int index, int rc)
Functions
static struct osp_thandle * thandle_to_osp_thandle (struct thandle *th)
static struct osp_update_request * thandle_to_osp_update_request (struct thandle *th)
static bool is_only_remote_trans (struct thandle *th)
static void osp_objid_buf_prep (struct lu_buf *buf, loff_t *off, __u32 *id, int index)
static void osp_objseq_buf_prep (struct lu_buf *buf, loff_t *off, __u64 *seq, int index)
static void osp_buf_prep (struct lu_buf *lb, void *buf, int buf_len)
static struct osp_thread_info * osp_env_info (const struct lu_env *env)
static struct osp_txn_info * osp_txn_info (struct lu_context *ctx)
static int lu_device_is_osp (struct lu_device *d)
static struct osp_device * lu2osp_dev (struct lu_device *d)
static struct lu_device * osp2lu_dev (struct osp_device *d)
static struct osp_device * dt2osp_dev (struct dt_device *d)
static struct osp_object * lu2osp_obj (struct lu_object *o)
static struct lu_object * osp2lu_obj (struct osp_object *obj)
static struct osp_object * osp_obj (const struct lu_object *o)
static struct osp_object * dt2osp_obj (const struct dt_object *d)
static struct dt_object * osp_object_child (struct osp_object *o)
static struct seq_server_site * osp_seq_site (struct osp_device *osp)
static void osp_get_rpc_lock (struct osp_device *osp)
static void osp_put_rpc_lock (struct osp_device *osp)
static int osp_fid_diff (const struct lu_fid *fid1, const struct lu_fid *fid2)
static void osp_update_last_fid (struct osp_device *d, struct lu_fid *fid)
static int osp_fid_end_seq (const struct lu_env *env, struct lu_fid *fid)
static int osp_precreate_end_seq_nolock (const struct lu_env *env, struct osp_device *osp)
static int osp_precreate_end_seq (const struct lu_env *env, struct osp_device *osp)
static int osp_is_fid_client (struct osp_device *osp)
struct object_update * update_buffer_get_update (struct object_update_request *request, unsigned int index)
int osp_extend_update_buffer (const struct lu_env *env, struct osp_update_request *our)
struct osp_update_request_sub * osp_current_object_update_request (struct osp_update_request *our)
Get current update request.
int osp_object_update_request_create (struct osp_update_request *our, size_t size)
Allocate new update request.
static bool osp_send_update_thread_running (struct osp_device *osp)
static bool osp_send_update_thread_stopped (struct osp_device *osp)
void osp_update_last_id (struct osp_device *d, u64 objid)
int osp_insert_async_request (const struct lu_env *env, enum update_type op, struct osp_object *obj, int count, __u16 *lens, const void **bufs, void *data, __u32 repsize, osp_update_interpreter_t interpreter)
Insert an asynchronous idempotent request to the shared request queue that is attached to the osp_device.
int osp_unplug_async_request (const struct lu_env *env, struct osp_device *osp, struct osp_update_request *update)
Pack all the requests in the shared asynchronous idempotent request queue into a single OUT RPC that will be given to the background ptlrpcd daemon.
int osp_trans_update_request_create (struct thandle *th)
struct thandle * osp_trans_create (const struct lu_env *env, struct dt_device *d)
The OSP layer dt_device_operations::dt_trans_create() interface to create a transaction.
int osp_trans_start (const struct lu_env *env, struct dt_device *dt, struct thandle *th)
The OSP layer dt_device_operations::dt_trans_start() interface to start the transaction.
int osp_insert_update_callback (const struct lu_env *env, struct osp_update_request *update, struct osp_object *obj, void *data, osp_update_interpreter_t interpreter)
Insert an osp_update_callback into the osp_update_request.
struct osp_update_request * osp_update_request_create (struct dt_device *dt)
Allocate and initialize osp_update_request.
void osp_update_request_destroy (struct osp_update_request *update)
int osp_send_update_thread (void *arg)
Sending update thread.
int osp_check_and_set_rpc_version (struct osp_thandle *oth, struct osp_object *obj)
Set version for the transaction.
void osp_thandle_destroy (struct osp_thandle *oth)
static void osp_thandle_get (struct osp_thandle *oth)
static void osp_thandle_put (struct osp_thandle *oth)
int osp_prep_update_req (const struct lu_env *env, struct obd_import *imp, struct osp_update_request *our, struct ptlrpc_request **reqp)
Prepare update request.
int osp_remote_sync (const struct lu_env *env, struct osp_device *osp, struct osp_update_request *update, struct ptlrpc_request **reqp)
Send update RPC.
struct thandle * osp_get_storage_thandle (const struct lu_env *env, struct thandle *th, struct osp_device *osp)
Get local thandle for osp_thandle.
void osp_trans_callback (const struct lu_env *env, struct osp_thandle *oth, int rc)
callback of osp transaction
void osp_invalidate_request (struct osp_device *osp)
Invalidate update request.
int osp_attr_get (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr)
Implement OSP layer dt_object_operations::do_attr_get() interface.
int osp_xattr_get (const struct lu_env *env, struct dt_object *dt, struct lu_buf *buf, const char *name)
Implement OSP layer dt_object_operations::do_xattr_get() interface.
int osp_declare_xattr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, const char *name, int flag, struct thandle *th)
Implement OSP layer dt_object_operations::do_declare_xattr_set() interface.
int osp_xattr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, const char *name, int fl, struct thandle *th)
Implement OSP layer dt_object_operations::do_xattr_set() interface.
int osp_declare_xattr_del (const struct lu_env *env, struct dt_object *dt, const char *name, struct thandle *th)
Implement OSP layer dt_object_operations::do_declare_xattr_del() interface.
int osp_xattr_del (const struct lu_env *env, struct dt_object *dt, const char *name, struct thandle *th)
Implement OSP layer dt_object_operations::do_xattr_del() interface.
int osp_trans_stop (const struct lu_env *env, struct dt_device *dt, struct thandle *th)
The OSP layer dt_device_operations::dt_trans_stop() interface to stop the transaction.
int osp_trans_cb_add (struct thandle *th, struct dt_txn_commit_cb *dcb)
Add commit callback to transaction.
struct dt_it * osp_it_init (const struct lu_env *env, struct dt_object *dt, __u32 attr)
Initialize the OSP layer index iteration.
void osp_it_fini (const struct lu_env *env, struct dt_it *di)
Finalize the OSP layer index iteration.
int osp_it_get (const struct lu_env *env, struct dt_it *di, const struct dt_key *key)
void osp_it_put (const struct lu_env *env, struct dt_it *di)
__u64 osp_it_store (const struct lu_env *env, const struct dt_it *di)
int osp_it_key_rec (const struct lu_env *env, const struct dt_it *di, void *key_rec)
int osp_it_next_page (const struct lu_env *env, struct dt_it *di)
Move the iteration cursor to the next lu_page.
int osp_oac_init (struct osp_object *obj)
Initialize the OSP object attributes cache.
int osp_md_declare_object_create (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *th)
Implementation of dt_object_operations::do_declare_create.
int osp_md_object_create (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *th)
Implementation of dt_object_operations::do_create.
int osp_md_declare_attr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_attr *attr, struct thandle *th)
Implementation of dt_object_operations::do_declare_attr_get.
int osp_md_attr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_attr *attr, struct thandle *th)
Implementation of dt_object_operations::do_attr_set.
int osp_init_precreate (struct osp_device *d)
Initialize precreation functionality of OSP.
int osp_precreate_reserve (const struct lu_env *env, struct osp_device *d)
Reserve object in precreate pool.
__u64 osp_precreate_get_id (struct osp_device *d)
int osp_precreate_get_fid (const struct lu_env *env, struct osp_device *d, struct lu_fid *fid)
Get a FID from precreation pool.
void osp_precreate_fini (struct osp_device *d)
Finish precreate functionality of OSP.
int osp_object_truncate (const struct lu_env *env, struct dt_object *dt, __u64)
void osp_pre_update_status (struct osp_device *d, int rc)
Update precreate status using statfs data.
void osp_statfs_need_now (struct osp_device *d)
Schedule an immediate update for statfs data.
int osp_reset_last_used (const struct lu_env *env, struct osp_device *osp)
int osp_write_last_oid_seq_files (struct lu_env *env, struct osp_device *osp, struct lu_fid *fid, int sync)
Write FID into into last_oid/last_seq file.
int osp_init_pre_fid (struct osp_device *osp)
Initialize FID for precreation.
void osp_lprocfs_init (struct osp_device *osp)
int osp_sync_declare_add (const struct lu_env *env, struct osp_object *o, llog_op_type type, struct thandle *th)
Declare intention to add a new change.
int osp_sync_add (const struct lu_env *env, struct osp_object *o, llog_op_type type, struct thandle *th, const struct lu_attr *attr)
int osp_sync_init (const struct lu_env *env, struct osp_device *d)
Initialization of the sync component of OSP.
int osp_sync_fini (struct osp_device *d)
Stop the syncing thread.
void __osp_sync_check_for_work (struct osp_device *d)
Variables
struct kmem_cache * osp_object_kmem
struct lu_object_operations osp_lu_obj_ops
struct dt_device_operations osp_dt_ops
struct dt_object_operations osp_md_obj_ops
struct dt_body_operations osp_md_body_ops
struct lu_context_key osp_thread_key
struct lu_context_key osp_txn_key
struct lu_device_operations osp_lu_ops
struct llog_operations osp_mds_ost_orig_logops
struct dt_index_operations osp_md_index_ops
struct obd_ops lwp_obd_device_ops
struct lu_device_type lwp_device_type
Define Documentation
#define opd_pre_create_count opd_pre->osp_pre_create_count
Definition at line 261 of file osp_internal.h.
#define opd_pre_create_slow opd_pre->osp_pre_create_slow
Definition at line 264 of file osp_internal.h.
#define opd_pre_last_created_fid opd_pre->osp_pre_last_created_fid
Definition at line 257 of file osp_internal.h.
#define opd_pre_lock opd_pre->osp_pre_lock
Definition at line 255 of file osp_internal.h.
#define opd_pre_max_create_count opd_pre->osp_pre_max_create_count
Definition at line 263 of file osp_internal.h.
#define opd_pre_min_create_count opd_pre->osp_pre_min_create_count
Definition at line 262 of file osp_internal.h.
#define opd_pre_recovering opd_pre->osp_pre_recovering
Definition at line 265 of file osp_internal.h.
#define opd_pre_reserved opd_pre->osp_pre_reserved
Definition at line 258 of file osp_internal.h.
#define opd_pre_status opd_pre->osp_pre_status
Definition at line 260 of file osp_internal.h.
#define opd_pre_used_fid opd_pre->osp_pre_used_fid
Definition at line 256 of file osp_internal.h.
#define opd_pre_user_waitq opd_pre->osp_pre_user_waitq
Definition at line 259 of file osp_internal.h.
#define osp_init_rpc_lock (lck) mdc_init_rpc_lock(lck)
Definition at line 493 of file osp_internal.h.
Referenced by osp_init0().
#define OSP_THANDLE_MAGIC 0x20141214
Definition at line 348 of file osp_internal.h.
Referenced by osp_thandle_destroy(), and osp_trans_create().
#define osp_update_rpc_pack (env, name, our, op, ...)
Definition at line 605 of file osp_internal.h.
Referenced by osp_attr_get(), osp_md_attr_set(), osp_md_index_delete(), osp_md_index_insert(), osp_md_index_lookup(), osp_md_object_create(), osp_md_object_destroy(), osp_md_read(), osp_md_ref_add(), osp_md_ref_del(), osp_md_write(), osp_xattr_del(), osp_xattr_get(), and osp_xattr_set().
Typedef Documentation
typedef int(* osp_update_interpreter_t)(const struct lu_env *env, struct object_update_reply *rep, struct ptlrpc_request *req, struct osp_object *obj, void *data, int index, int rc)
Definition at line 660 of file osp_internal.h.
Function Documentation
void __osp_sync_check_for_work (struct osp_device * d)
Definition at line 236 of file osp_sync.c.
References osp_sync_check_for_work.
Referenced by osp_import_event(), and osp_sync().
static struct osp_device* dt2osp_dev (struct dt_device * d) [static, read]
Definition at line 454 of file osp_internal.h.
References dt_device::dd_lu_dev, LASSERT, lu_device_is_osp(), and osp_device::opd_dt_dev.
Referenced by osp_check_and_set_rpc_version(), osp_md_declare_write(), osp_md_object_lock(), osp_statfs(), osp_sync(), osp_trans_stop(), and osp_update_interpret().
static struct osp_object* dt2osp_obj (const struct dt_object * d) [static, read]
Definition at line 477 of file osp_internal.h.
References dt_object::do_lu, and osp_obj().
Referenced by osp_attr_get(), osp_attr_set(), osp_declare_attr_get(), osp_declare_attr_set(), osp_declare_object_create(), osp_declare_object_destroy(), osp_declare_xattr_get(), osp_md_declare_object_create(), osp_md_declare_write(), osp_md_object_create(), osp_md_object_destroy(), osp_md_object_read_lock(), osp_md_object_read_unlock(), osp_md_object_write_lock(), osp_md_object_write_locked(), osp_md_object_write_unlock(), osp_md_write(), osp_object_create(), osp_object_destroy(), osp_xattr_del(), osp_xattr_get(), and osp_xattr_set().
static bool is_only_remote_trans (struct thandle * th) [inline, static]
Definition at line 378 of file osp_internal.h.
References thandle::th_top.
Referenced by osp_attr_set(), osp_declare_attr_set(), osp_declare_object_create(), osp_object_create(), and osp_trans_start().
static struct osp_device* lu2osp_dev (struct lu_device * d) [static, read]
Definition at line 443 of file osp_internal.h.
References dt_device::dd_lu_dev, LASSERT, lu_device_is_osp(), and osp_device::opd_dt_dev.
Referenced by is_ost_obj(), osp_attr_get(), osp_declare_attr_get(), osp_declare_attr_set(), osp_declare_object_create(), osp_declare_object_destroy(), osp_declare_xattr_get(), osp_device_fini(), osp_device_free(), osp_fid_alloc(), osp_import_event(), osp_insert_async_request(), osp_iocontrol(), osp_it_fetch(), osp_it_next_page(), osp_md_index_lookup(), osp_md_object_destroy(), osp_md_read(), osp_obd_connect(), osp_obd_disconnect(), osp_obd_get_info(), osp_obd_set_info_async(), osp_object_create(), osp_object_destroy(), osp_object_release(), osp_object_truncate(), osp_process_config(), osp_recovery_complete(), osp_sync_add(), osp_sync_declare_add(), osp_xattr_get(), and osp_xattr_set().
static struct osp_object* lu2osp_obj (struct lu_object * o) [static, read]
Definition at line 460 of file osp_internal.h.
References dt_object::do_lu, ergo, LASSERT, lu_object::lo_dev, lu_device_is_osp(), and osp_object::opo_obj.
Referenced by osp_object_free(), osp_object_init(), osp_object_print(), osp_object_release(), and osp_thandle_invalidate_object().
static int lu_device_is_osp (struct lu_device * d) [inline, static]
Definition at line 438 of file osp_internal.h.
References ergo, lu_device::ld_ops, and osp_lu_ops.
Referenced by dt2osp_dev(), lu2osp_dev(), lu2osp_obj(), and osp_obj().
static struct lu_device* osp2lu_dev (struct osp_device * d) [static, read]
Definition at line 449 of file osp_internal.h.
References dt_device::dd_lu_dev, and osp_device::opd_dt_dev.
Referenced by osp_device_alloc().
static struct lu_object* osp2lu_obj (struct osp_object * obj) [static, read]
Definition at line 466 of file osp_internal.h.
References dt_object::do_lu, and osp_object::opo_obj.
Referenced by osp_attr_get(), osp_attr_get_interpterer(), osp_insert_async_request(), osp_object_child(), osp_update_callback_fini(), and osp_update_callback_init().
int osp_attr_get (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr)
Implement OSP layer dt_object_operations::do_attr_get() interface.
Get attribute from the specified MDT/OST object.
If the attribute is in the OSP object attributes cache, then return the cached attribute directly. Otherwise it will trigger an OUT RPC to the peer to get the attribute synchronously, if successful, add it to the OSP attributes cache. (
See also:
lustre/osp/osp_trans.c for OUT RPC.)
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the OSP layer dt_object
[out] attr pointer to the buffer to hold the output attribute
Return values:
0 for success
negative error number on failure
Definition at line 542 of file osp_object.c.
References CERROR, dt_device::dd_lu_dev, DFID, dt_object::do_lu, dt2osp_obj(), ENTRY, GOTO, is_ost_obj(), lu_attr::la_valid, lu_device::ld_obd, lu_object::lo_dev, lu_object::lo_header, lu_object_header::loh_attr, LOHA_EXISTS, lu2osp_dev(), lu_object_fid(), obd_device::obd_name, osp_object_attr::ooa_attr, osp_device::opd_dt_dev, osp_object::opo_lock, osp_object::opo_non_exist, osp_object::opo_ooa, osp_object::opo_stale, osp2lu_obj(), osp_get_attr_from_reply(), osp_remote_sync(), osp_update_request_create(), osp_update_request_destroy(), osp_update_rpc_pack, object_update_reply::ourp_magic, OUT_ATTR_GET, OUT_UPDATE_REPLY_SIZE, PFID, ptlrpc_req_finished(), req_capsule_server_sized_get(), RETURN, RMF_OUT_UPDATE_REPLY, ptlrpc_request::rq_pill, and UPDATE_REPLY_MAGIC.
static void osp_buf_prep (struct lu_buf * lb, void * buf, int buf_len) [inline, static]
Definition at line 401 of file osp_internal.h.
References lu_buf::lb_buf, and lu_buf::lb_len.
int osp_check_and_set_rpc_version (struct osp_thandle * oth, struct osp_object * obj)
Set version for the transaction.
Set the version for the transaction and add the request to the sending list, then after transaction stop, the request will be picked in the order of version, by sending thread.
Parameters:
[in] oth osp thandle to be set version.
Return values:
0 if set version succeeds negative errno if set version fails.
Definition at line 1264 of file osp_trans.c.
References CDEBUG, D_INFO, dt2osp_dev(), LASSERT, list_add_tail(), LPU64, obd_device::obd_name, osp_device::opd_obd, osp_device::opd_update, osp_object::opo_stale, osp_thandle_get(), osp_thandle::ot_our, osp_thandle::ot_super, osp_updates::ou_list, osp_updates::ou_lock, osp_updates::ou_version, osp_update_request::our_list, osp_update_request::our_list_lock, osp_update_request::our_req_ready, osp_update_request::our_version, thandle::th_dev, and thandle::th_wait_submit.
Referenced by osp_md_write().
struct osp_update_request_sub* osp_current_object_update_request (struct osp_update_request * our) [read]
Get current update request.
Get current object update request from our_req_list in osp_update_request, because we always insert the new update request in the last position, so the last update request in the list will be the current update req.
Parameters:
[in] our osp update request where to get the current object update.
Return values:
the current object update.
Definition at line 166 of file osp_trans.c.
References list_empty(), list_entry, osp_update_request::our_req_list, osp_update_request_sub::ours_list, and list_head::prev.
Referenced by osp_declare_xattr_get(), and osp_insert_async_request().
int osp_declare_xattr_del (const struct lu_env * env, struct dt_object * dt, const char * name, struct thandle * th)
Implement OSP layer dt_object_operations::do_declare_xattr_del() interface.
Declare that the caller will delete extended attribute on the specified MDT/OST object.
If it is non-remote transaction, it will add an OUT_XATTR_DEL sub-request to the OUT RPC that will be flushed when the transaction start. And if the name extended attribute entry exists in the OSP attributes cache, then remove it from the cache.
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the OSP layer dt_object
[in] name the name of the extended attribute to be set
[in] th pointer to the transaction handler
Return values:
0 for success
negative error number on failure
Definition at line 1236 of file osp_object.c.
References osp_trans_update_request_create().
int osp_declare_xattr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, const char * name, int flag, struct thandle * th)
Implement OSP layer dt_object_operations::do_declare_xattr_set() interface.
Declare that the caller will set extended attribute to the specified MDT/OST object.
If it is non-remote transaction, it will add an OUT_XATTR_SET sub-request to the OUT RPC that will be flushed when the transaction start. And if the OSP attributes cache is initialized, then check whether the name extended attribute entry exists in the cache or not. If yes, replace it; otherwise, add the extended attribute to the cache.
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the OSP layer dt_object
[in] buf pointer to the lu_buf to hold the extended attribute
[in] name the name of the extended attribute to be set
[in] flag to indicate the detailed set operation: LU_XATTR_CREATE or LU_XATTR_REPLACE or others
[in] th pointer to the transaction handler
Return values:
0 for success
negative error number on failure
Definition at line 1125 of file osp_object.c.
References osp_trans_update_request_create().
static struct osp_thread_info* osp_env_info (const struct lu_env * env) [static, read]
Definition at line 409 of file osp_internal.h.
References LASSERT, lu_env::le_ctx, lu_context_key_get(), lu_env_refill(), and osp_thread_key.
Referenced by osp_declare_object_create(), osp_fid_end_seq(), osp_find_or_create_local_file(), osp_get_attr_from_reply(), osp_init_last_objid(), osp_init_last_seq(), osp_init_pre_fid(), osp_last_used_init(), osp_md_index_lookup(), osp_md_read(), osp_object_assign_fid(), osp_object_create(), osp_object_init(), osp_precreate_cleanup_orphans(), osp_precreate_fids(), osp_precreate_rollover_new_seq(), osp_precreate_send(), osp_sync_add_rec(), osp_sync_declare_add(), osp_sync_llog_init(), osp_write_last_oid_seq_files(), osp_xattr_get(), and osp_xattr_get_interpterer().
int osp_extend_update_buffer (const struct lu_env * env, struct osp_update_request * our)
static int osp_fid_diff (const struct lu_fid * fid1, const struct lu_fid * fid2) [inline, static]
Definition at line 509 of file osp_internal.h.
References DFID, lu_fid::f_oid, lu_fid::f_seq, fid_idif_id(), fid_idif_ost_idx(), fid_is_idif(), fid_oid(), LASSERTF, and PFID.
Referenced by osp_objs_precreated(), osp_precreate_cleanup_orphans(), osp_precreate_get_fid(), osp_precreate_send(), and osp_update_last_fid().
static int osp_fid_end_seq (const struct lu_env * env, struct lu_fid * fid) [static]
Definition at line 553 of file osp_internal.h.
References fid_is_idif(), fid_oid(), fid_to_ostid(), IDIF_MAX_OID, LUSTRE_DATA_SEQ_MAX_WIDTH, ost_id::oi, osp_thread_info::osi_oi, osp_env_info(), and ostid_id().
Referenced by osp_create_end_seq(), and osp_precreate_end_seq_nolock().
static void osp_get_rpc_lock (struct osp_device * osp) [inline, static]
Definition at line 495 of file osp_internal.h.
References client_obd::cl_rpc_lock, obd_device::cli, mdc_get_rpc_lock(), osp_device::opd_obd, and obd_device::u.
Referenced by osp_send_update_req().
struct thandle* osp_get_storage_thandle (const struct lu_env * env, struct thandle * th, struct osp_device * osp) [read]
Get local thandle for osp_thandle.
Get the local OSD thandle from the OSP thandle. Currently, there are a few OSP API (osp_object_create() and osp_sync_add()) needs to update the object on local OSD device.
If the osp_thandle comes from normal stack (MDD->LOD->OSP), then we will get local thandle by thandle_get_sub_by_dt.
If the osp_thandle is remote thandle (th_top == NULL, only used by LFSCK), then it will create a local thandle, and stop it in osp_trans_stop(). And this only happens on OSP for OST.
These are temporary solution, once OSP accessing OSD object is being fixed properly, this function should be removed. XXX
Parameters:
[in] env pointer to the thread context
[in] th pointer to the transaction handler
[in] dt pointer to the OSP device
Return values:
pointer to the local thandle
ERR_PTR(errno) if it fails.
Definition at line 1227 of file osp_trans.c.
References dt_trans_create(), LASSERT, osp_device::opd_connect_mdt, osp_device::opd_storage, osp_thandle::ot_storage_th, thandle::th_top, thandle_get_sub_by_dt(), and thandle_to_osp_thandle().
Referenced by osp_declare_object_create(), and osp_object_create().
int osp_init_pre_fid (struct osp_device * osp)
Initialize FID for precreation.
For a just created new target, a new sequence should be taken. The function checks there is no IDIF in use (if the target was added with the older version of Lustre), then requests a new sequence from FLDB using the regular protocol. Then this new sequence is stored on a persisten storage synchronously to prevent possible object leakage (for the detail see the description for osp_precreate_rollover_new_seq()).
Parameters:
[in] osp OSP device
Return values:
0 on success
negative negated errno on error
Definition at line 1008 of file osp_precreate.c.
References CERROR, client_obd::cl_seq, obd_device::cli, dt_device::dd_lu_dev, ENTRY, lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, fid_idif_seq(), fid_is_zero(), fid_zero(), GOTO, LASSERT, lu_device::ld_type, lu_device_type::ldt_ctx_tags, lu_env_fini(), lu_env_init(), obd_device::obd_name, osp_device::opd_dt_dev, osp_device::opd_group, osp_device::opd_index, osp_device::opd_last_used_fid, osp_device::opd_obd, osp_device::opd_pre, osp_thread_info::osi_fid, osp_env_info(), osp_is_fid_client(), osp_write_last_oid_seq_files(), RETURN, seq_client_get_seq(), and obd_device::u.
Referenced by osp_precreate_thread().
int osp_init_precreate (struct osp_device * d)
Initialize precreation functionality of OSP.
Prepares all the internal structures and starts the precreate thread
Parameters:
[in] d OSP device
Return values:
0 on success
negative negated errno on error
Definition at line 1531 of file osp_precreate.c.
References CDEBUG, CERROR, cfs_time_current(), cfs_time_shift(), cfs_timer_init(), D_OTHER, ENTRY, fid_zero(), l_wait_event, OBD_ALLOC_PTR, osp_device::opd_got_disconnected, osp_device::opd_group, osp_device::opd_index, osp_device::opd_pre, osp_device::opd_pre_thread, osp_device::opd_pre_waitq, osp_device::opd_statfs_fresh_till, osp_device::opd_statfs_maxage, osp_device::opd_statfs_timer, osp_precreate_running(), osp_precreate_stopped(), osp_precreate_thread(), osp_statfs_timer_cb(), OST_MAX_PRECREATE, OST_MIN_PRECREATE, RETURN, and ptlrpc_thread::t_ctl_waitq.
Referenced by osp_init0().
int osp_insert_async_request (const struct lu_env * env, enum update_type op, struct osp_object * obj, int count, __u16 * lens, const void ** bufs, void * data, __u32 repsize, osp_update_interpreter_t interpreter)
Insert an asynchronous idempotent request to the shared request queue that is attached to the osp_device.
This function generates a new osp_async_request with the given parameters, then tries to insert the request into the osp_device-based shared request queue. If the queue is full, then triggers the packaged OUT RPC to purge the shared queue firstly, and then re-tries.
NOTE: must hold the osp::opd_async_requests_mutex to serialize concurrent osp_insert_async_request call from others.
Parameters:
[in] env pointer to the thread context
[in] op operation type, see 'enum update_type'
[in] obj pointer to the operation target
[in] count array size of the subsequent lens and bufs
[in] lens buffer length array for the subsequent bufs
[in] bufs the buffers to compose the request
[in] data pointer to the data used by the interpreter
[in] repsize how many bytes the caller allocated for data
[in] interpreter pointer to the interpreter function
Return values:
0 for success
negative error number on failure
Definition at line 840 of file osp_trans.c.
References ENTRY, lu2osp_dev(), lu_object_fid(), object_update_request_size(), osp_device::opd_async_requests, osp_device::opd_async_requests_mutex, osp2lu_obj(), osp_current_object_update_request(), osp_find_or_create_async_update_request(), osp_insert_update_callback(), osp_unplug_async_request(), osp_update_request::our_update_nr, object_update_request::ourq_count, osp_update_request_sub::ours_req, osp_update_request_sub::ours_req_size, out_update_pack(), RETURN, and update_buffer_get_update().
Referenced by osp_declare_attr_get(), and osp_declare_xattr_get().
int osp_insert_update_callback (const struct lu_env * env, struct osp_update_request * our, struct osp_object * obj, void * data, osp_update_interpreter_t interpreter)
Insert an osp_update_callback into the osp_update_request.
Insert an osp_update_callback to the osp_update_request. Usually each update in the osp_update_request will have one correspondent callback, and these callbacks will be called in rq_interpret_reply.
Parameters:
[in] env pointer to the thread context
[in] obj pointer to the operation target object
[in] data pointer to the data used by the interpreter
[in] interpreter pointer to the interpreter function
Return values:
0 for success
negative error number on failure
Definition at line 799 of file osp_trans.c.
References list_add_tail(), osp_update_callback_init(), osp_update_callback::ouc_list, osp_update_request::our_cb_items, and RETURN.
Referenced by osp_insert_async_request(), osp_md_object_create(), and osp_md_object_destroy().
void osp_invalidate_request (struct osp_device * osp)
Invalidate update request.
Invalidate update request in the OSP sending list, so all of requests in the sending list will return error, which happens when it finds one update (with writing llog) requests fails or the OSP is evicted by remote target. see osp_send_update_thread().
Parameters:
[in] osp OSP device whose update requests will be invalidated.
Definition at line 1354 of file osp_trans.c.
References CDEBUG, CERROR, D_HA, dt_device::dd_lu_dev, ENTRY, INIT_LIST_HEAD, lu_device::ld_type, lu_device_type::ldt_ctx_tags, list, list_del_init(), list_for_each_entry_safe, LIST_HEAD(), list_move(), lu_env_fini(), lu_env_init(), obd_device::obd_name, osp_device::opd_dt_dev, osp_device::opd_obd, osp_device::opd_update, osp_thandle_put(), osp_trans_callback(), osp_thandle::ot_super, osp_updates::ou_list, osp_updates::ou_lock, osp_updates::ou_rpc_version, osp_update_request::our_list, osp_update_request::our_list_lock, osp_update_request::our_req_ready, osp_update_request::our_th, osp_update_request::our_version, and thandle::th_result.
Referenced by osp_import_event(), and osp_send_update_thread().
static int osp_is_fid_client (struct osp_device * osp) [inline, static]
Definition at line 585 of file osp_internal.h.
References client_obd::cl_import, obd_device::cli, obd_import::imp_connect_data, OBD_CONNECT_FID, obd_connect_data::ocd_connect_flags, osp_device::opd_obd, and obd_device::u.
Referenced by osp_init_pre_fid(), osp_object_create(), and osp_precreate_send().
void osp_it_fini (const struct lu_env * env, struct dt_it * di)
Finalize the OSP layer index iteration.
Parameters:
[in] env pointer to the thread context
[in] di pointer to the iteration structure
Definition at line 1661 of file osp_object.c.
References OBD_FREE, OBD_FREE_PTR, osp_it::ooi_cur_page, osp_it::ooi_pages, and osp_it::ooi_total_npages.
int osp_it_get (const struct lu_env * env, struct dt_it * di, const struct dt_key * key)
Definition at line 1963 of file osp_object.c.
struct dt_it* osp_it_init (const struct lu_env * env, struct dt_object * dt, __u32 attr) [read]
Initialize the OSP layer index iteration.
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the index object to be iterated
[in] attr unused
Return values:
pointer to the iteration structure
negative error number on failure
Definition at line 1639 of file osp_object.c.
References OBD_ALLOC_PTR, osp_it::ooi_attr, osp_it::ooi_obj, and osp_it::ooi_pos_ent.
int osp_it_key_rec (const struct lu_env * env, const struct dt_it * di, void * key_rec)
Definition at line 2041 of file osp_object.c.
int osp_it_next_page (const struct lu_env * env, struct dt_it * di)
Move the iteration cursor to the next lu_page.
One system page (PAGE_SIZE) may contain multiple lu_page (4KB), that depends on the LU_PAGE_COUNT. If it is not the last lu_page in current system page, then move the iteration cursor to the next lu_page in current system page. Otherwise, if there are more system pages in the cache, then move the iteration cursor to the next system page. If all the cached records (pages) have been iterated, then fetch more records via osp_it_fetch().
Parameters:
[in] env pointer to the thread context
[in] di pointer to the iteration structure
Return values:
positive for end of the directory
0 for success
negative error number on failure
Definition at line 1833 of file osp_object.c.
References CDEBUG, CERROR, D_INFO, dt_object::do_lu, ENTRY, II_END_OFF, LIP_MAGIC, lu_idxpage::lip_magic, lu_idxpage::lip_nr, lu_object::lo_dev, lu2osp_dev(), LU_PAGE_COUNT, LU_PAGE_SIZE, lustre_swab_lip_header(), OBD_FREE, obd_device::obd_name, osp_it::ooi_cur_idxpage, osp_it::ooi_cur_page, osp_it::ooi_ent, osp_it::ooi_next, osp_it::ooi_obj, osp_it::ooi_pages, osp_it::ooi_pos_ent, osp_it::ooi_pos_lu_page, osp_it::ooi_pos_page, osp_it::ooi_swab, osp_it::ooi_total_npages, osp_it::ooi_valid_npages, osp_device::opd_obd, osp_it_fetch(), and RETURN.
Referenced by osp_md_index_it_next(), and osp_orphan_it_next().
void osp_it_put (const struct lu_env * env, struct dt_it * di)
Definition at line 1969 of file osp_object.c.
__u64 osp_it_store (const struct lu_env * env, const struct dt_it * di)
Definition at line 2005 of file osp_object.c.
References osp_it::ooi_next.
void osp_lprocfs_init (struct osp_device * osp)
Referenced by osp_init0().
int osp_md_attr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_attr * attr, struct thandle * th)
Implementation of dt_object_operations::do_attr_set.
Set attributes to the specified remote object.
Add the OUT_ATTR_SET sub-request into the OUT RPC that will be flushed when the transaction stop.
Parameters:
[in] env execution environment
[in] dt object to set attributes
[in] attr attributes to be set
[in] th the transaction handle
Return values:
0 if packing attr_set succeeds.
negative errno if packing fails.
Definition at line 359 of file osp_md_object.c.
References dt_object::do_lu, LASSERT, lu_object_fid(), osp_update_rpc_pack, OUT_ATTR_SET, and thandle_to_osp_update_request().
Referenced by osp_attr_set().
int osp_md_declare_attr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_attr * attr, struct thandle * th)
Implementation of dt_object_operations::do_declare_attr_get.
Create the osp_update_request to track the update for this OSP in the transaction.
Parameters:
[in] env execution environment
[in] dt object on which to set attributes
[in] attr attributes to be set
[in] th the transaction handle
Return values:
0 if preparation succeeds.
negative errno if preparation fails.
Definition at line 337 of file osp_md_object.c.
References osp_trans_update_request_create().
Referenced by osp_declare_attr_set().
int osp_md_declare_object_create (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof, struct thandle * th)
Implementation of dt_object_operations::do_declare_create.
Create the osp_update_request to track the update for this OSP in the transaction.
Parameters:
[in] env execution environment
[in] dt remote object to be created
[in] attr attribute of the created object
[in] hint creation hint
[in] dof creation format information
[in] th the transaction handle
Return values:
0 if preparation succeeds.
negative errno if preparation fails.
Definition at line 121 of file osp_md_object.c.
References dt2osp_obj(), osp_object::opo_ooa, osp_oac_init(), and osp_trans_update_request_create().
Referenced by osp_declare_object_create().
int osp_md_object_create (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof, struct thandle * th)
Implementation of dt_object_operations::do_create.
It adds an OUT_CREATE sub-request into the OUT RPC that will be flushed when the transaction stop, and sets necessary flags for created object.
Parameters:
[in] env execution environment
[in] dt object to be created
[in] attr attribute of the created object
[in] hint creation hint
[in] dof creation format information
[in] th the transaction handle
Return values:
0 if packing creation succeeds.
negative errno if packing creation fails.
Definition at line 173 of file osp_md_object.c.
References dt_object::do_lu, dt2osp_obj(), GOTO, lu_attr::la_mode, LA_TYPE, lu_attr::la_valid, LASSERT, lu_object::lo_header, lu_object_header::loh_attr, LOHA_EXISTS, lu_object_fid(), osp_object_attr::ooa_attr, osp_object::opo_non_exist, osp_object::opo_ooa, osp_insert_update_callback(), osp_object_create_interpreter(), osp_update_rpc_pack, OUT_CREATE, and thandle_to_osp_update_request().
Referenced by osp_object_create().
int osp_oac_init (struct osp_object * obj)
Initialize the OSP object attributes cache.
Parameters:
[in] obj pointer to the OSP object
Return values:
0 for success
negative error number on failure
Definition at line 174 of file osp_object.c.
References INIT_LIST_HEAD, likely, OBD_ALLOC_PTR, OBD_FREE_PTR, osp_object_attr::ooa_xattr_list, osp_object::opo_lock, and osp_object::opo_ooa.
Referenced by osp_declare_attr_get(), osp_declare_xattr_get(), and osp_md_declare_object_create().
static struct osp_object* osp_obj (const struct lu_object * o) [static, read]
Definition at line 471 of file osp_internal.h.
References dt_object::do_lu, LASSERT, lu_object::lo_dev, lu_device_is_osp(), and osp_object::opo_obj.
Referenced by dt2osp_obj(), and osp_thandle_invalidate_object().
static struct dt_object* osp_object_child (struct osp_object * o) [static, read]
Definition at line 482 of file osp_internal.h.
References dt_object::do_lu, lu_object_next(), and osp2lu_obj().
int osp_object_truncate (const struct lu_env * env, struct dt_object * dt, __u64)
Definition at line 1454 of file osp_precreate.c.
References CERROR, client_obd::cl_import, obd_device::cli, dt_object::do_lu, ENTRY, fid_to_ostid(), GOTO, obd_import::imp_connect_data, LASSERT, lu_object::lo_dev, lu2osp_dev(), lu_object_fid(), LUSTRE_OST_VERSION, lustre_set_wire_obdo(), obdo::o_blocks, obdo::o_oi, obdo::o_size, obdo::o_valid, ost_body::oa, OBD_ALLOC_PTR, OBD_FREE_PTR, OBD_MD_FLBLOCKS, OBD_MD_FLGROUP, OBD_MD_FLID, OBD_MD_FLSIZE, OBD_OBJECT_EOF, osp_device::opd_obd, OST_IO_PORTAL, OST_PUNCH, ptlrpc_at_set_req_timeout(), ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), req_capsule_client_get(), RETURN, RMF_OST_BODY, ptlrpc_request::rq_import, ptlrpc_request::rq_no_delay, ptlrpc_request::rq_no_resend, ptlrpc_request::rq_pill, RQF_OST_PUNCH, and obd_device::u.
Referenced by osp_declare_attr_set().
int osp_object_update_request_create (struct osp_update_request * our, size_t size)
Allocate new update request.
Allocate new update request and insert it to the req_update_list.
Parameters:
[in] our osp_udate_request where to create a new update request
Return values:
0 if creation succeeds.
negative errno if creation fails.
Definition at line 125 of file osp_trans.c.
References INIT_LIST_HEAD, list_add_tail(), OBD_ALLOC_PTR, OBD_FREE_PTR, object_update_request_alloc(), osp_update_request::our_req_list, osp_update_request::our_req_nr, osp_update_request_sub::ours_list, osp_update_request_sub::ours_req, osp_update_request_sub::ours_req_size, and OUT_UPDATE_INIT_BUFFER_SIZE.
Referenced by osp_update_request_create().
static void osp_objid_buf_prep (struct lu_buf * buf, loff_t * off, __u32 * id, int index) [inline, static]
Definition at line 383 of file osp_internal.h.
References lu_buf::lb_buf, and lu_buf::lb_len.
Referenced by osp_init_last_objid(), and osp_object_create().
static void osp_objseq_buf_prep (struct lu_buf * buf, loff_t * off, __u64 * seq, int index) [inline, static]
Definition at line 393 of file osp_internal.h.
References lu_buf::lb_buf, and lu_buf::lb_len.
Referenced by osp_init_last_seq(), and osp_last_used_init().
void osp_pre_update_status (struct osp_device * d, int rc)
Update precreate status using statfs data.
The function decides whether this OSP should be used for new objects. IOW, whether this OST is used up or has some free space. Cached statfs data is used to make this decision. If the latest result of statfs request (rc argument) is not success, then just mark OSP unavailable right away.
Add a bit of hysteresis so this flag isn't continually flapping, and ensure that new files don't get extremely fragmented due to only a small amount of available space in the filesystem. We want to set the NOSPC flag when there is less than ~0.1% free and clear it when there is at least ~0.2% free space, so: avail < ~0.1% max max = avail + used 1025 * avail < avail + used used = blocks - free 1024 * avail < used 1024 * avail < blocks - free avail < ((blocks - free) >> 10)
On very large disk, say 16TB 0.1% will be 16 GB. We don't want to lose that amount of space so in those cases we report no space left if their is less than 1 GB left. the function updates current precreation status used: functional or not
Parameters:
[in] d OSP device
[in] rc new precreate status for device d
Return values:
0 on success
negative negated errno on error
Definition at line 948 of file osp_precreate.c.
References __u64, CDEBUG, D_INFO, likely, LPU64, min_t, obd_device::obd_name, osp_device::opd_obd, osp_device::opd_pre_waitq, osp_device::opd_statfs, osp_device::opd_syn_changes, osp_device::opd_syn_rpc_in_progress, obd_statfs::os_bavail, obd_statfs::os_bfree, obd_statfs::os_blocks, obd_statfs::os_ffree, obd_statfs::os_type, and OST_MIN_PRECREATE.
Referenced by osp_import_event(), osp_precreate_cleanup_orphans(), osp_precreate_send(), and osp_statfs_interpret().
static int osp_precreate_end_seq (const struct lu_env * env, struct osp_device * osp) [inline, static]
Definition at line 574 of file osp_internal.h.
References osp_precreate_end_seq_nolock().
Referenced by osp_object_create(), and osp_precreate_thread().
static int osp_precreate_end_seq_nolock (const struct lu_env * env, struct osp_device * osp) [inline, static]
Definition at line 566 of file osp_internal.h.
References osp_fid_end_seq().
Referenced by osp_precreate_end_seq(), and osp_precreate_reserve().
void osp_precreate_fini (struct osp_device * d)
Finish precreate functionality of OSP.
Asks all the activity (the thread, update timer) to stop, then wait till that is done.
Parameters:
[in] d OSP device
Definition at line 1596 of file osp_precreate.c.
References cfs_timer_disarm(), ENTRY, EXIT, OBD_FREE_PTR, osp_device::opd_pre, osp_device::opd_pre_thread, osp_device::opd_pre_waitq, osp_device::opd_statfs_timer, RETURN_EXIT, SVC_STOPPED, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, ptlrpc_thread::t_flags, and thread.
Referenced by osp_init0(), and osp_shutdown().
int osp_precreate_get_fid (const struct lu_env * env, struct osp_device * d, struct lu_fid * fid)
Get a FID from precreation pool.
The function is a companion for osp_precreate_reserve() - it assigns a specific FID from the precreate. The function should be called only if the call to osp_precreate_reserve() was successful. The function updates a local storage to remember the highest object ID referenced by the node in the given sequence.
A very importan details: this is supposed to be called once the transaction is started, so on-disk update will be atomic with the data (like LOVEA) refering this object. Then the object won't be leaked: either it's referenced by the committed transaction or it's a subject to the orphan cleanup procedure.
Parameters:
[in] env LU environment provided by the caller
[in] d OSP device
[out] fid generated FID
Return values:
0 on success
negative negated errno on error
Definition at line 1405 of file osp_precreate.c.
References DFID, LASSERTF, osp_device::opd_pre_waitq, osp_fid_diff(), osp_update_last_fid(), PFID, and unlikely.
Referenced by osp_object_assign_fid().
__u64 osp_precreate_get_id (struct osp_device * d)
int osp_precreate_reserve (const struct lu_env * env, struct osp_device * d)
Reserve object in precreate pool.
When the caller wants to create a new object on this target (target represented by the given OSP), it should declare this intention using a regular ->dt_declare_create() OSD API method. Then OSP will be trying to reserve an object in the existing precreated pool or wait up to obd_timeout for the available object to appear in the pool (a dedicated thread will be doing real precreation in background). The object can be consumed later with osp_precreate_get_fid() or be released with call to lu_object_put(). Notice the function doesn't reserve a specific ID, just some ID. The actual ID assignment happen in osp_precreate_get_fid(). If the space on the target is short and there is a pending object destroy, then the function forces local commit to speedup space release (see osp_sync.c for the details).
Parameters:
[in] env LU environment provided by the caller
[in] d OSP device
Return values:
0 on success
-ENOSPC when no space on OST
-EAGAIN try later, slow precreation in progress
-EIO when no access to OST
Definition at line 1292 of file osp_precreate.c.
References cfs_time_aftereq(), cfs_time_current(), cfs_time_shift(), DFID, dt_commit_async(), ENTRY, l_wait_event, LASSERTF, LWI_TIMEOUT, obd_timeout, osp_device::opd_pre_waitq, osp_device::opd_storage, osp_device::opd_syn_changes, osp_device::opd_syn_rpc_in_progress, osp_objs_precreated(), osp_precreate_end_seq_nolock(), osp_precreate_near_empty_nolock(), osp_precreate_ready_condition(), osp_precreate_timeout_condition(), PFID, RETURN, and unlikely.
Referenced by osp_declare_object_create().
int osp_prep_update_req (const struct lu_env * env, struct obd_import * imp, struct osp_update_request * our, struct ptlrpc_request ** reqp)
Prepare update request.
Prepare OUT update ptlrpc request, and the request usually includes all of updates (stored in
Parameters:
ureq) from one operation.
[in] env execution environment
[in] imp import on which ptlrpc request will be sent
[in] ureq hold all of updates which will be packed into the req
[in] reqp request to be created
Return values:
0 if preparation succeeds.
negative errno if preparation fails.
Definition at line 314 of file osp_trans.c.
References ptlrpc_bulk_frag_ops::add_iov_frag, ptlrpc_bulk_desc::bd_frag_ops, CDEBUG, D_INFO, D_OTHER, ENTRY, GOTO, LASSERT, list_entry, list_for_each_entry, LNET_MTU_BITS, LUSTRE_MDS_VERSION, MD_MAX_BRW_SIZE, MDS_BULK_PORTAL, list_head::next, object_update_request_dump(), object_update_request_get(), object_update_request_size(), OSC_REPLY_PORTAL, osp_prep_inline_update_req(), object_update::ou_result_size, out_update_buffer::oub_size, out_update_header::ouh_count, out_update_header::ouh_inline_length, out_update_header::ouh_magic, out_update_header::ouh_reply_size, osp_update_request::our_req_list, osp_update_request::our_update_nr, object_update_reply::ourp_lens, object_update_request::ourq_count, osp_update_request_sub::ours_req, osp_update_request_sub::ours_req_size, OUT_PORTAL, OUT_UPDATE, OUT_UPDATE_HEADER_MAGIC, OUT_UPDATE_MAX_INLINE_SIZE, OUT_UPDATE_REPLY_SIZE, PTLRPC_BULK_BUF_KVEC, PTLRPC_BULK_GET_SOURCE, ptlrpc_bulk_kvec_ops, ptlrpc_prep_bulk_imp(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), RCL_CLIENT, RCL_SERVER, req_capsule_client_get(), req_capsule_set_size(), RETURN, RMF_OUT_UPDATE_BUF, RMF_OUT_UPDATE_HEADER, RMF_OUT_UPDATE_REPLY, ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_pill, RQF_OUT_UPDATE, and size.
Referenced by osp_md_read(), osp_remote_sync(), osp_send_update_req(), and osp_unplug_async_request().
static void osp_put_rpc_lock (struct osp_device * osp) [inline, static]
Definition at line 502 of file osp_internal.h.
References client_obd::cl_rpc_lock, obd_device::cli, mdc_put_rpc_lock(), osp_device::opd_obd, and obd_device::u.
Referenced by osp_send_update_req().
int osp_remote_sync (const struct lu_env * env, struct osp_device * osp, struct osp_update_request * our, struct ptlrpc_request ** reqp)
Send update RPC.
Send update request to the remote MDT synchronously.
Parameters:
[in] env execution environment
[in] imp import on which ptlrpc request will be sent
[in] our hold all of updates which will be packed into the req
[in] reqp request to be created
Return values:
0 if RPC succeeds.
negative errno if RPC fails.
Definition at line 442 of file osp_trans.c.
References client_obd::cl_import, obd_device::cli, ENTRY, osp_device::opd_obd, osp_prep_update_req(), osp_update_request::our_rc, ptlrpc_queue_wait(), ptlrpc_req_finished(), RETURN, ptlrpc_request::rq_allow_intr, ptlrpc_request::rq_allow_replay, and obd_device::u.
Referenced by osp_attr_get(), osp_md_index_lookup(), and osp_xattr_get().
int osp_reset_last_used (const struct lu_env * env, struct osp_device * osp)
int osp_send_update_thread (void * arg)
Sending update thread.
Create thread to send update request to other MDTs, this thread will pull out update request from the list in OSP by version number, i.e. it will make sure the update request with lower version number will be sent first.
Parameters:
[in] arg hold the OSP device.
Return values:
0 if the thread is created successfully. negative error if the thread is not created successfully.
Definition at line 1423 of file osp_trans.c.
References CERROR, dt_device::dd_lu_dev, ENTRY, l_wait_event, LASSERT, lu_device::ld_type, lu_device_type::ldt_ctx_tags, lu_env_fini(), lu_env_init(), OBD_FAIL_CHECK, OBD_FAIL_INVALIDATE_UPDATE, obd_device::obd_name, osp_device::opd_dt_dev, osp_device::opd_obd, osp_device::opd_update, osp_device::opd_update_thread, osp_get_next_request(), osp_invalidate_request(), osp_send_update_req(), osp_send_update_thread_running(), osp_thandle_put(), osp_trans_callback(), osp_thandle::ot_super, osp_updates::ou_lock, osp_updates::ou_rpc_version, osp_updates::ou_waitq, osp_update_request::our_th, osp_update_request::our_version, RETURN, SVC_RUNNING, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, ptlrpc_thread::t_flags, thandle::th_result, and thread.
Referenced by osp_update_init().
static bool osp_send_update_thread_running (struct osp_device * osp) [inline, static]
Definition at line 650 of file osp_internal.h.
References osp_device::opd_update_thread, SVC_RUNNING, and ptlrpc_thread::t_flags.
Referenced by osp_send_update_thread(), osp_trans_stop(), and osp_update_init().
static bool osp_send_update_thread_stopped (struct osp_device * osp) [inline, static]
Definition at line 655 of file osp_internal.h.
References osp_device::opd_update_thread, SVC_STOPPED, and ptlrpc_thread::t_flags.
Referenced by osp_update_init().
static struct seq_server_site* osp_seq_site (struct osp_device * osp) [static, read]
Definition at line 488 of file osp_internal.h.
References dt_device::dd_lu_dev, lu_site::ld_seq_site, lu_device::ld_site, and osp_device::opd_dt_dev.
void osp_statfs_need_now (struct osp_device * d)
Schedule an immediate update for statfs data.
If cached statfs data claim no free space, but OSP has got a request to destroy an object (so release some space probably), then we may need to refresh cached statfs data sooner than planned. The function checks there is no statfs update going and schedules immediate update if so. XXX: there might be a case where removed object(s) do not add free space (empty object). If the number of such deletions is high, then we can start to update statfs too often causing a RPC storm. some throttling is needed...
Parameters:
[in] d OSP device where statfs data needs to be refreshed
Definition at line 231 of file osp_precreate.c.
References cfs_time_shift(), cfs_timer_disarm(), osp_device::opd_pre_waitq, osp_device::opd_statfs_fresh_till, osp_device::opd_statfs_timer, and osp_device::opd_statfs_update_in_progress.
Referenced by osp_sync_interpret(), and osp_sync_process_committed().
int osp_sync_add (const struct lu_env * env, struct osp_object * o, llog_op_type type, struct thandle * th, const struct lu_attr * attr)
Definition at line 429 of file osp_sync.c.
References dt_object::do_lu, lu_object::lo_dev, lu2osp_dev(), lu_object_fid(), osp_object::opo_obj, and osp_sync_add_rec().
Referenced by osp_attr_set(), and osp_object_destroy().
int osp_sync_declare_add (const struct lu_env * env, struct osp_object * o, llog_op_type type, struct thandle * th)
Declare intention to add a new change.
With regard to OSD API, we have to declare any changes ahead. In this case we declare an intention to add a llog record representing the change on the local storage.
Parameters:
[in] env LU environment provided by the caller
[in] o OSP object
[in] type type of change: MDS_UNLINK64_REC or MDS_SETATTR64_REC
[in] th transaction handle (local)
Return values:
0 on success
negative negated errno on error
Definition at line 294 of file osp_sync.c.
References dt_object::do_lu, ENTRY, LASSERT, LBUG, LCT_OSP_THREAD, llog_ctxt_put(), llog_declare_add(), llog_get_context(), LLOG_MDS_OST_ORIG_CTXT, lu_object::lo_dev, llog_ctxt::loc_handle, llog_rec_hdr::lrh_len, lu2osp_dev(), MDS_SETATTR64_REC, MDS_UNLINK64_REC, osp_device::opd_obd, osp_device::opd_storage, osp_object::opo_obj, osp_thread_info::osi_hdr, osp_env_info(), RETURN, thandle::th_tags, thandle::th_top, and thandle_get_sub_by_dt().
Referenced by osp_declare_attr_set(), and osp_declare_object_destroy().
int osp_sync_fini (struct osp_device * d)
Stop the syncing thread.
Asks the syncing thread to stop and wait until it's stopped.
Parameters:
[in] d OSP device
Return values:
0
Definition at line 1444 of file osp_sync.c.
References ENTRY, osp_device::opd_syn_thread, osp_device::opd_syn_waitq, osp_sync_id_traction_fini(), RETURN, SVC_STOPPED, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, ptlrpc_thread::t_flags, and thread.
Referenced by osp_init0(), and osp_shutdown().
int osp_sync_init (const struct lu_env * env, struct osp_device * d)
Initialization of the sync component of OSP.
Initializes the llog and starts a new thread to handle the changes to the remote target (OST or MDT).
Parameters:
[in] env LU environment provided by the caller
[in] d OSP device
Return values:
0 on success
negative negated errno on error
Definition at line 1381 of file osp_sync.c.
References CERROR, ENTRY, GOTO, INIT_LIST_HEAD, l_wait_event, obd_device::obd_name, osp_device::opd_group, osp_device::opd_index, osp_device::opd_obd, osp_device::opd_syn_barrier_waitq, osp_device::opd_syn_committed_there, osp_device::opd_syn_inflight_list, osp_device::opd_syn_lock, osp_device::opd_syn_max_rpc_in_flight, osp_device::opd_syn_max_rpc_in_progress, osp_device::opd_syn_thread, osp_device::opd_syn_waitq, OSP_MAX_IN_FLIGHT, OSP_MAX_IN_PROGRESS, osp_sync_id_traction_fini(), osp_sync_id_traction_init(), osp_sync_llog_fini(), osp_sync_llog_init(), osp_sync_running(), osp_sync_stopped(), osp_sync_thread(), RETURN, and ptlrpc_thread::t_ctl_waitq.
Referenced by osp_init0().
void osp_thandle_destroy (struct osp_thandle * oth)
Definition at line 919 of file osp_trans.c.
References LASSERT, list_empty(), OBD_FREE_PTR, OSP_THANDLE_MAGIC, osp_update_request_destroy(), osp_thandle::ot_commit_dcb_list, osp_thandle::ot_magic, osp_thandle::ot_our, and osp_thandle::ot_stop_dcb_list.
Referenced by osp_thandle_put().
static void osp_thandle_get (struct osp_thandle * oth) [inline, static]
Definition at line 697 of file osp_internal.h.
References osp_thandle::ot_refcount.
Referenced by osp_check_and_set_rpc_version(), and osp_send_update_req().
static void osp_thandle_put (struct osp_thandle * oth) [inline, static]
Definition at line 702 of file osp_internal.h.
References osp_thandle_destroy(), and osp_thandle::ot_refcount.
Referenced by osp_invalidate_request(), osp_request_commit_cb(), osp_send_update_req(), osp_send_update_thread(), osp_trans_stop(), osp_update_fini(), and osp_update_interpret().
void osp_trans_callback (const struct lu_env * env, struct osp_thandle * oth, int rc)
callback of osp transaction
Call all of callbacks for this osp thandle. This will only be called in error handler path. In the normal processing path, these callback will be called in osp_request_commit_cb() and osp_update_interpret().
Parameters:
[in] env execution environment
[in] oth osp thandle
[in] rc result of the osp thandle
Definition at line 1067 of file osp_trans.c.
References list_del_init(), list_for_each_entry_safe, osp_trans_commit_cb(), osp_trans_stop_cb(), osp_update_callback_fini(), osp_thandle::ot_our, osp_update_callback::ouc_data, osp_update_callback::ouc_interpreter, osp_update_callback::ouc_list, osp_update_callback::ouc_obj, and osp_update_request::our_cb_items.
Referenced by osp_invalidate_request(), osp_send_update_req(), osp_send_update_thread(), osp_trans_stop(), and osp_update_fini().
int osp_trans_cb_add (struct thandle * th, struct dt_txn_commit_cb * dcb)
Add commit callback to transaction.
Add commit callback to the osp thandle, which will be called when the thandle is committed remotely.
Parameters:
[in] th the thandle
[in] dcb commit callback structure
Return values:
only return 0 for now.
Definition at line 989 of file osp_trans.c.
References dt_txn_commit_cb::dcb_flags, dt_txn_commit_cb::dcb_func, dt_txn_commit_cb::dcb_linkage, dt_txn_commit_cb::dcb_magic, DCB_TRANS_STOP, LASSERT, list_add(), osp_thandle::ot_commit_dcb_list, osp_thandle::ot_stop_dcb_list, thandle_to_osp_thandle(), and TRANS_COMMIT_CB_MAGIC.
struct thandle* osp_trans_create (const struct lu_env * env, struct dt_device * d) [read]
The OSP layer dt_device_operations::dt_trans_create() interface to create a transaction.
There are two kinds of transactions that will involve OSP:
1) If the transaction only contains the updates on remote server (MDT or OST), such as re-generating the lost OST-object for LFSCK, then it is a remote transaction. For remote transaction, the upper layer caller (such as the LFSCK engine) will call the dt_trans_create() (with the OSP dt_device as the parameter), then the call will be directed to the osp_trans_create() that creates the transaction handler and returns it to the caller.
2) If the transcation contains both local and remote updates, such as cross MDTs create under DNE mode, then the upper layer caller will not trigger osp_trans_create(). Instead, it will call dt_trans_create() on other dt_device, such as LOD that will generate the transaction handler. Such handler will be used by the whole transaction in subsequent sub-operations.
Parameters:
[in] env pointer to the thread context
[in] d pointer to the OSP dt_device
Return values:
pointer to the transaction handler
negative error number on failure
Definition at line 956 of file osp_trans.c.
References ENTRY, INIT_LIST_HEAD, LCT_TX_HANDLE, OBD_ALLOC_PTR, OSP_THANDLE_MAGIC, osp_thandle::ot_commit_dcb_list, osp_thandle::ot_magic, osp_thandle::ot_refcount, osp_thandle::ot_stop_dcb_list, osp_thandle::ot_super, RETURN, thandle::th_dev, thandle::th_tags, and unlikely.
int osp_trans_start (const struct lu_env * env, struct dt_device * dt, struct thandle * th)
The OSP layer dt_device_operations::dt_trans_start() interface to start the transaction.
If the transaction is a remote transaction, then related remote updates will be triggered in the osp_trans_stop(). Please refer to osp_trans_create() for transaction type.
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the OSP dt_device
[in] th pointer to the transaction handler
Return values:
0 for success
negative error number on failure
Definition at line 1509 of file osp_trans.c.
References dt_trans_start(), is_only_remote_trans(), osp_thandle::ot_our, osp_thandle::ot_storage_th, osp_thandle::ot_super, osp_update_request::our_flags, thandle::th_dev, thandle::th_sync, thandle_to_osp_thandle(), and UPDATE_FL_SYNC.
int osp_trans_stop (const struct lu_env * env, struct dt_device * dt, struct thandle * th)
The OSP layer dt_device_operations::dt_trans_stop() interface to stop the transaction.
If the transaction is a remote transaction, related remote updates will be triggered at the end of this function.
For synchronous mode update or any failed update, the request will be destroyed explicitly when the osp_trans_stop().
Please refer to osp_trans_create() for transaction type.
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the OSP dt_device
[in] th pointer to the transaction handler
Return values:
0 for success
negative error number on failure
Definition at line 1542 of file osp_trans.c.
References CDEBUG, D_HA, dt2osp_dev(), dt_trans_stop(), ENTRY, GOTO, LASSERT, likely, list_empty(), LPU64, obd_device::obd_name, osp_device::opd_connect_mdt, osp_device::opd_obd, osp_device::opd_update, osp_send_update_req(), osp_send_update_thread_running(), osp_thandle_put(), osp_trans_callback(), osp_thandle::ot_our, osp_thandle::ot_storage_th, osp_updates::ou_waitq, osp_update_request::our_list, osp_update_request::our_list_lock, osp_update_request::our_req_list, osp_update_request::our_req_ready, osp_update_request::our_version, RETURN, thandle::th_dev, thandle::th_result, thandle::th_top, and thandle_to_osp_thandle().
int osp_trans_update_request_create (struct thandle * th)
Definition at line 899 of file osp_trans.c.
References osp_update_request_create(), osp_thandle::ot_our, osp_update_request::our_th, thandle::th_dev, thandle::th_result, and thandle_to_osp_thandle().
Referenced by osp_declare_xattr_del(), osp_declare_xattr_set(), osp_md_declare_attr_set(), osp_md_declare_index_delete(), osp_md_declare_index_insert(), osp_md_declare_object_create(), osp_md_declare_object_destroy(), osp_md_declare_ref_add(), osp_md_declare_ref_del(), and osp_md_declare_write().
static struct osp_txn_info* osp_txn_info (struct lu_context * ctx) [static, read]
Definition at line 428 of file osp_internal.h.
References lu_context_key_get(), and osp_txn_key.
Referenced by osp_sync_add_rec(), and osp_sync_tracker_commit_cb().
int osp_unplug_async_request (const struct lu_env * env, struct osp_device * osp, struct osp_update_request * our)
Pack all the requests in the shared asynchronous idempotent request queue into a single OUT RPC that will be given to the background ptlrpcd daemon.
Parameters:
[in] env pointer to the thread context
[in] osp pointer to the OSP device
[in] our pointer to the shared queue
Return values:
0 for success
negative error number on failure
Definition at line 714 of file osp_trans.c.
References client_obd::cl_import, obd_device::cli, list_del_init(), list_for_each_entry_safe, osp_update_args::oaua_count, osp_update_args::oaua_flow_control, osp_update_args::oaua_update, osp_update_args::oaua_update_env, osp_update_args::oaua_waitq, osp_device::opd_obd, osp_prep_update_req(), osp_update_callback_fini(), osp_update_interpret(), osp_update_request_destroy(), osp_update_callback::ouc_data, osp_update_callback::ouc_interpreter, osp_update_callback::ouc_list, osp_update_callback::ouc_obj, osp_update_request::our_cb_items, ptlrpc_req_async_args, ptlrpcd_add_req(), and obd_device::u.
Referenced by osp_declare_xattr_get(), and osp_insert_async_request().
static void osp_update_last_fid (struct osp_device * d, struct lu_fid * fid) [inline, static]
Definition at line 534 of file osp_internal.h.
References CDEBUG, D_HA, DFID, lu_fid::f_oid, osp_device::opd_gap_count, osp_device::opd_gap_start_fid, osp_device::opd_last_used_fid, osp_fid_diff(), and PFID.
Referenced by osp_object_create(), and osp_precreate_get_fid().
void osp_update_last_id (struct osp_device * d, u64 objid)
struct osp_update_request* osp_update_request_create (struct dt_device * dt) [read]
Allocate and initialize osp_update_request.
osp_update_request is being used to track updates being executed on this dt_device(OSD or OSP). The update buffer will be 4k initially, and increased if needed.
Parameters:
[in] dt dt device
Return values:
osp_update_request being allocated if succeed
ERR_PTR(errno) if failed
Definition at line 187 of file osp_trans.c.
References INIT_LIST_HEAD, OBD_ALLOC_PTR, osp_object_update_request_create(), osp_update_request::our_cb_items, osp_update_request::our_list, osp_update_request::our_list_lock, osp_update_request::our_req_list, and OUT_UPDATE_INIT_BUFFER_SIZE.
Referenced by osp_attr_get(), osp_find_or_create_async_update_request(), osp_md_index_lookup(), osp_md_read(), osp_trans_update_request_create(), and osp_xattr_get().
void osp_update_request_destroy (struct osp_update_request * update)
Definition at line 204 of file osp_trans.c.
References list_del(), list_for_each_entry_safe, OBD_FREE_LARGE, OBD_FREE_PTR, osp_update_request::our_req_list, osp_update_request_sub::ours_list, osp_update_request_sub::ours_req, and osp_update_request_sub::ours_req_size.
Referenced by osp_attr_get(), osp_device_fini(), osp_md_index_lookup(), osp_md_read(), osp_thandle_destroy(), osp_unplug_async_request(), osp_update_interpret(), and osp_xattr_get().
int osp_write_last_oid_seq_files (struct lu_env * env, struct osp_device * osp, struct lu_fid * fid, int sync)
Write FID into into last_oid/last_seq file.
The function stores the sequence and the in-sequence id into two dedicated files. The sync argument can be used to request synchronous commit, so the function won't return until the updates are committed.
Parameters:
[in] env LU environment provided by the caller
[in] osp OSP device
[in] fid fid where sequence/id is taken
[in] sync update mode: 0 - asynchronously, 1 - synchronously
Return values:
0 on success
negative negated errno on error
Definition at line 349 of file osp_precreate.c.
References CERROR, dt_declare_record_write(), dt_record_write(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), ENTRY, lu_fid::f_oid, lu_fid::f_seq, GOTO, lu_buf::lb_buf, lu_buf::lb_len, obd_device::obd_name, osp_device::opd_index, osp_device::opd_last_used_oid_file, osp_device::opd_last_used_seq_file, osp_device::opd_obd, osp_device::opd_storage, osp_thread_info::osi_lb, osp_thread_info::osi_lb2, osp_env_info(), RETURN, and thandle::th_sync.
Referenced by osp_init_pre_fid(), and osp_precreate_rollover_new_seq().
int osp_xattr_del (const struct lu_env * env, struct dt_object * dt, const char * name, struct thandle * th)
Implement OSP layer dt_object_operations::do_xattr_del() interface.
Delete extended attribute on the specified MDT/OST object.
If it is remote transaction, it will add an OUT_XATTR_DEL sub-request into the OUT RPC that will be flushed when the transaction stop. And if the name extended attribute entry exists in the OSP attributes cache, then remove it from the cache.
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the OSP layer dt_object
[in] name the name of the extended attribute to be set
[in] th pointer to the transaction handler
Return values:
0 for success
negative error number on failure
Definition at line 1260 of file osp_object.c.
References dt_object::do_lu, dt2osp_obj(), LASSERT, lu_object_fid(), osp_object::opo_ooa, osp_oac_xattr_find(), osp_oac_xattr_put(), osp_update_rpc_pack, OUT_XATTR_DEL, and thandle_to_osp_update_request().
int osp_xattr_get (const struct lu_env * env, struct dt_object * dt, struct lu_buf * buf, const char * name)
Implement OSP layer dt_object_operations::do_xattr_get() interface.
Get extended attribute from the specified MDT/OST object.
If the extended attribute is in the OSP object attributes cache, then return the cached extended attribute directly. Otherwise it will get the extended attribute synchronously, if successful, add it to the OSP attributes cache. (
See also:
lustre/osp/osp_trans.c for OUT RPC.)
There is a race condition: some other thread has added the named extended attributed entry to the OSP object attributes cache during the current OUT_XATTR_GET handling. If such case happens, the OSP will replace the (just) existing extended attribute entry with the new replied one.
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the OSP layer dt_object
[out] buf pointer to the lu_buf to hold the extended attribute
[in] name the name for the expected extended attribute
Return values:
0 for success
negative error number on failure
Definition at line 916 of file osp_object.c.
References CERROR, cfs_fail_val, CWARN, DFID, dt_object::do_lu, dt2osp_obj(), ENTRY, GOTO, is_ost_obj(), LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lu_device::ld_obd, lu_object::lo_dev, lu_object::lo_header, lu_object_header::loh_attr, LOHA_EXISTS, lu2osp_dev(), lu_object_fid(), OBD_FAIL_CHECK, OBD_FAIL_LFSCK_BAD_NETWORK, obd_device::obd_name, object_update_result_data_get(), osp_device::opd_connect_mdt, osp_device::opd_dt_dev, osp_device::opd_index, osp_object::opo_lock, osp_object::opo_non_exist, osp_object::opo_ooa, osp_thread_info::osi_lb2, osp_dev2node(), osp_env_info(), osp_oac_xattr_find(), osp_oac_xattr_find_or_add(), osp_oac_xattr_put(), osp_oac_xattr_replace(), osp_remote_sync(), osp_update_request_create(), osp_update_request_destroy(), osp_update_rpc_pack, object_update_reply::ourp_magic, OUT_UPDATE_REPLY_SIZE, OUT_XATTR_GET, osp_xattr_entry::oxe_buflen, osp_xattr_entry::oxe_exist, osp_xattr_entry::oxe_namelen, osp_xattr_entry::oxe_ready, osp_xattr_entry::oxe_vallen, osp_xattr_entry::oxe_value, PFID, ptlrpc_req_finished(), req_capsule_server_sized_get(), RETURN, RMF_OUT_UPDATE_REPLY, ptlrpc_request::rq_pill, unlikely, UPDATE_REPLY_MAGIC, and XATTR_NAME_LINK.
int osp_xattr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, const char * name, int fl, struct thandle * th)
Implement OSP layer dt_object_operations::do_xattr_set() interface.
Set extended attribute to the specified MDT/OST object.
Add an OUT_XATTR_SET sub-request into the OUT RPC that will be flushed in the transaction stop. And if the OSP attributes cache is initialized, then check whether the name extended attribute entry exists in the cache or not. If yes, replace it; otherwise, add the extended attribute to the cache.
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the OSP layer dt_object
[in] buf pointer to the lu_buf to hold the extended attribute
[in] name the name of the extended attribute to be set
[in] fl to indicate the detailed set operation: LU_XATTR_CREATE or LU_XATTR_REPLACE or others
[in] th pointer to the transaction handler
Return values:
0 for success
negative error number on failure
Definition at line 1153 of file osp_object.c.
References CDEBUG, CWARN, D_INODE, DFID, dt_object::do_lu, dt2osp_obj(), ENTRY, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lu_device::ld_obd, lu_object::lo_dev, lu2osp_dev(), lu_object_fid(), obd_device::obd_name, osp_device::opd_connect_mdt, osp_object::opo_lock, osp_object::opo_ooa, osp_oac_xattr_find_or_add(), osp_oac_xattr_put(), osp_oac_xattr_replace(), osp_update_rpc_pack, OUT_XATTR_SET, osp_xattr_entry::oxe_buflen, osp_xattr_entry::oxe_exist, osp_xattr_entry::oxe_namelen, osp_xattr_entry::oxe_ready, osp_xattr_entry::oxe_vallen, osp_xattr_entry::oxe_value, PFID, RETURN, and thandle_to_osp_update_request().
static struct osp_thandle* thandle_to_osp_thandle (struct thandle * th) [static, read]
Definition at line 362 of file osp_internal.h.
References osp_thandle::ot_super.
Referenced by osp_get_storage_thandle(), osp_md_write(), osp_request_commit_cb(), osp_trans_cb_add(), osp_trans_start(), osp_trans_stop(), osp_trans_update_request_create(), and thandle_to_osp_update_request().
static struct osp_update_request* thandle_to_osp_update_request (struct thandle * th) [static, read]
Definition at line 368 of file osp_internal.h.
References osp_thandle::ot_our, and thandle_to_osp_thandle().
Referenced by osp_md_attr_set(), osp_md_index_delete(), osp_md_index_insert(), osp_md_object_create(), osp_md_object_destroy(), osp_md_ref_add(), osp_md_ref_del(), osp_md_write(), osp_xattr_del(), and osp_xattr_set().
struct object_update* update_buffer_get_update (struct object_update_request * request, unsigned int index) [read]
Definition at line 141 of file osp_md_object.c.
References object_update_size(), object_update_request::ourq_count, and object_update_request::ourq_updates.
Referenced by osp_insert_async_request().
Variable Documentation
struct lu_device_type lwp_device_type
Definition at line 395 of file lwp_dev.c.
Referenced by osp_init().
struct obd_ops lwp_obd_device_ops
Definition at line 621 of file lwp_dev.c.
Referenced by osp_init().
struct dt_device_operations osp_dt_ops
Definition at line 886 of file osp_dev.c.
struct lu_object_operations osp_lu_obj_ops
Definition at line 2257 of file osp_object.c.
Referenced by osp_object_alloc().
struct lu_device_operations osp_lu_ops
Definition at line 697 of file osp_dev.c.
Referenced by lu_device_is_osp().
struct dt_body_operations osp_md_body_ops
Definition at line 1236 of file osp_md_object.c.
Referenced by osp_object_init().
struct dt_index_operations osp_md_index_ops
Definition at line 820 of file osp_md_object.c.
Referenced by osp_index_try().
struct dt_object_operations osp_md_obj_ops
Definition at line 1010 of file osp_md_object.c.
Referenced by osp_object_init().
struct llog_operations osp_mds_ost_orig_logops
Definition at line 1900 of file osp_dev.c.
Referenced by osp_init(), and osp_sync_llog_init().
struct kmem_cache* osp_object_kmem
Definition at line 88 of file osp_dev.c.
Referenced by osp_object_alloc(), and osp_object_free().
struct lu_context_key osp_thread_key
Definition at line 1846 of file osp_dev.c.
Referenced by osp_env_info().
struct lu_context_key osp_txn_key
Definition at line 1856 of file osp_dev.c.
Referenced by osp_txn_info().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.