Lustre: lustre/osp/osp_precreate.c File Reference
lustre/osp/osp_precreate.c File Reference
#include <linux/kthread.h>
#include <lustre_obdo.h>
#include "osp_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_MDS
Functions
static int osp_statfs_need_update (struct osp_device *d)
static bool osp_precreate_running (struct osp_device *d)
static bool osp_precreate_stopped (struct osp_device *d)
static void osp_statfs_timer_cb (unsigned long _d)
static int osp_statfs_interpret (const struct lu_env *env, struct ptlrpc_request *req, union ptlrpc_async_args *aa, int rc)
RPC interpret callback for OST_STATFS RPC.
static int osp_statfs_update (struct osp_device *d)
Send OST_STATFS RPC.
void osp_statfs_need_now (struct osp_device *d)
Schedule an immediate update for statfs data.
static int osp_objs_precreated (const struct lu_env *env, struct osp_device *osp)
Return number of precreated objects.
static int osp_precreate_near_empty_nolock (const struct lu_env *env, struct osp_device *d)
Check pool of precreated objects is nearly empty.
static int osp_precreate_near_empty (const struct lu_env *env, struct osp_device *d)
Check pool of precreated objects.
static int osp_create_end_seq (const struct lu_env *env, struct osp_device *osp)
Check given sequence is empty.
int osp_write_last_oid_seq_files (struct lu_env *env, struct osp_device *osp, struct lu_fid *fid, int sync)
Write FID into into last_oid/last_seq file.
static int osp_precreate_rollover_new_seq (struct lu_env *env, struct osp_device *osp)
Switch to another sequence.
static int osp_precreate_fids (const struct lu_env *env, struct osp_device *osp, struct lu_fid *fid, int *grow)
Find IDs available in current sequence.
static int osp_precreate_send (const struct lu_env *env, struct osp_device *d)
Prepare and send precreate RPC.
static int osp_get_lastfid_from_ost (const struct lu_env *env, struct osp_device *d)
Get last precreated object from target (OST).
static int osp_precreate_cleanup_orphans (struct lu_env *env, struct osp_device *d)
Cleanup orphans on OST.
void osp_pre_update_status (struct osp_device *d, int rc)
Update precreate status using statfs data.
int osp_init_pre_fid (struct osp_device *osp)
Initialize FID for precreation.
static int osp_precreate_thread (void *_arg)
The core of precreate functionality.
static int osp_precreate_ready_condition (const struct lu_env *env, struct osp_device *d)
Check when to stop to wait for precreate objects.
static int osp_precreate_timeout_condition (void *data)
int osp_precreate_reserve (const struct lu_env *env, struct osp_device *d)
Reserve object in precreate pool.
int osp_precreate_get_fid (const struct lu_env *env, struct osp_device *d, struct lu_fid *fid)
Get a FID from precreation pool.
int osp_object_truncate (const struct lu_env *env, struct dt_object *dt, __u64 size)
int osp_init_precreate (struct osp_device *d)
Initialize precreation functionality of OSP.
void osp_precreate_fini (struct osp_device *d)
Finish precreate functionality of OSP.
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 45 of file osp_precreate.c.
Function Documentation
static int osp_create_end_seq (const struct lu_env * env, struct osp_device * osp) [inline, static]
Check given sequence is empty.
Returns a binary result whether the given sequence has some IDs left or not. Find the details in osp_fid_end_seq(). This is a lock protected version of that function.
Parameters:
[in] env LU environment provided by the caller
[in] osp OSP device
Return values:
0 - current sequence has no IDs, 1 - otherwise
Definition at line 322 of file osp_precreate.c.
References osp_fid_end_seq().
Referenced by osp_precreate_thread().
static int osp_get_lastfid_from_ost (const struct lu_env * env, struct osp_device * d) [static]
Get last precreated object from target (OST).
Sends synchronous RPC to the target (OST) to learn the last precreated object. This later is used to remove all unused objects (cleanup orphan procedure). Also, the next object after one we got will be used as a starting point for the new precreates.
Parameters:
[in] env LU environment provided by the caller
[in] d OSP device
Return values:
0 on success
negative negated errno on error
Definition at line 680 of file osp_precreate.c.
References CDEBUG, CERROR, client_obd::cl_import, obd_device::cli, D_HA, DFID, ENTRY, fid_cpu_to_le(), fid_is_sane(), fid_oid(), GOTO, KEY_LAST_FID, LASSERT, LUSTRE_OST_VERSION, obd_device::obd_name, osp_device::opd_last_used_fid, osp_device::opd_obd, OST_GET_INFO, PFID, ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), ptlrpc_set_import_active(), RCL_CLIENT, req_capsule_client_get(), req_capsule_server_get(), req_capsule_set_size(), RETURN, RMF_FID, RMF_GETINFO_KEY, ptlrpc_request::rq_no_delay, ptlrpc_request::rq_no_resend, ptlrpc_request::rq_pill, RQF_OST_GET_INFO_LAST_FID, and obd_device::u.
Referenced by osp_precreate_cleanup_orphans().
int osp_init_pre_fid (struct osp_device * osp)
Initialize FID for precreation.
For a just created new target, a new sequence should be taken. The function checks there is no IDIF in use (if the target was added with the older version of Lustre), then requests a new sequence from FLDB using the regular protocol. Then this new sequence is stored on a persisten storage synchronously to prevent possible object leakage (for the detail see the description for osp_precreate_rollover_new_seq()).
Parameters:
[in] osp OSP device
Return values:
0 on success
negative negated errno on error
Definition at line 1008 of file osp_precreate.c.
References CERROR, client_obd::cl_seq, obd_device::cli, dt_device::dd_lu_dev, ENTRY, lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, fid_idif_seq(), fid_is_zero(), fid_zero(), GOTO, LASSERT, lu_device::ld_type, lu_device_type::ldt_ctx_tags, lu_env_fini(), lu_env_init(), obd_device::obd_name, osp_device::opd_dt_dev, osp_device::opd_group, osp_device::opd_index, osp_device::opd_last_used_fid, osp_device::opd_obd, osp_device::opd_pre, osp_thread_info::osi_fid, osp_env_info(), osp_is_fid_client(), osp_write_last_oid_seq_files(), RETURN, seq_client_get_seq(), and obd_device::u.
Referenced by osp_precreate_thread().
int osp_init_precreate (struct osp_device * d)
Initialize precreation functionality of OSP.
Prepares all the internal structures and starts the precreate thread
Parameters:
[in] d OSP device
Return values:
0 on success
negative negated errno on error
Definition at line 1531 of file osp_precreate.c.
References CDEBUG, CERROR, cfs_time_current(), cfs_time_shift(), cfs_timer_init(), D_OTHER, ENTRY, fid_zero(), l_wait_event, OBD_ALLOC_PTR, osp_device::opd_got_disconnected, osp_device::opd_group, osp_device::opd_index, osp_device::opd_pre, osp_device::opd_pre_thread, osp_device::opd_pre_waitq, osp_device::opd_statfs_fresh_till, osp_device::opd_statfs_maxage, osp_device::opd_statfs_timer, osp_precreate_running(), osp_precreate_stopped(), osp_precreate_thread(), osp_statfs_timer_cb(), OST_MAX_PRECREATE, OST_MIN_PRECREATE, RETURN, and ptlrpc_thread::t_ctl_waitq.
Referenced by osp_init0().
int osp_object_truncate (const struct lu_env * env, struct dt_object * dt, __u64 size)
Definition at line 1454 of file osp_precreate.c.
References CERROR, client_obd::cl_import, obd_device::cli, dt_object::do_lu, ENTRY, fid_to_ostid(), GOTO, obd_import::imp_connect_data, LASSERT, lu_object::lo_dev, lu2osp_dev(), lu_object_fid(), LUSTRE_OST_VERSION, lustre_set_wire_obdo(), obdo::o_blocks, obdo::o_oi, obdo::o_size, obdo::o_valid, ost_body::oa, OBD_ALLOC_PTR, OBD_FREE_PTR, OBD_MD_FLBLOCKS, OBD_MD_FLGROUP, OBD_MD_FLID, OBD_MD_FLSIZE, OBD_OBJECT_EOF, osp_device::opd_obd, OST_IO_PORTAL, OST_PUNCH, ptlrpc_at_set_req_timeout(), ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), req_capsule_client_get(), RETURN, RMF_OST_BODY, ptlrpc_request::rq_import, ptlrpc_request::rq_no_delay, ptlrpc_request::rq_no_resend, ptlrpc_request::rq_pill, RQF_OST_PUNCH, and obd_device::u.
Referenced by osp_declare_attr_set().
static int osp_objs_precreated (const struct lu_env * env, struct osp_device * osp) [inline, static]
Return number of precreated objects.
A simple helper to calculate the number of precreated objects on the device.
Parameters:
[in] env LU environment provided by the caller
[in] osp OSP device
Return values:
the number of the precreated objects
Definition at line 255 of file osp_precreate.c.
References osp_fid_diff().
Referenced by osp_precreate_near_empty_nolock(), osp_precreate_ready_condition(), and osp_precreate_reserve().
void osp_pre_update_status (struct osp_device * d, int rc)
Update precreate status using statfs data.
The function decides whether this OSP should be used for new objects. IOW, whether this OST is used up or has some free space. Cached statfs data is used to make this decision. If the latest result of statfs request (rc argument) is not success, then just mark OSP unavailable right away.
Add a bit of hysteresis so this flag isn't continually flapping, and ensure that new files don't get extremely fragmented due to only a small amount of available space in the filesystem. We want to set the NOSPC flag when there is less than ~0.1% free and clear it when there is at least ~0.2% free space, so: avail < ~0.1% max max = avail + used 1025 * avail < avail + used used = blocks - free 1024 * avail < used 1024 * avail < blocks - free avail < ((blocks - free) >> 10)
On very large disk, say 16TB 0.1% will be 16 GB. We don't want to lose that amount of space so in those cases we report no space left if their is less than 1 GB left. the function updates current precreation status used: functional or not
Parameters:
[in] d OSP device
[in] rc new precreate status for device d
Return values:
0 on success
negative negated errno on error
Definition at line 948 of file osp_precreate.c.
References __u64, CDEBUG, D_INFO, likely, LPU64, min_t, obd_device::obd_name, osp_device::opd_obd, osp_device::opd_pre_waitq, osp_device::opd_statfs, osp_device::opd_syn_changes, osp_device::opd_syn_rpc_in_progress, obd_statfs::os_bavail, obd_statfs::os_bfree, obd_statfs::os_blocks, obd_statfs::os_ffree, obd_statfs::os_type, and OST_MIN_PRECREATE.
Referenced by osp_import_event(), osp_precreate_cleanup_orphans(), osp_precreate_send(), and osp_statfs_interpret().
static int osp_precreate_cleanup_orphans (struct lu_env * env, struct osp_device * d) [static]
Cleanup orphans on OST.
This function is called in a contex of a dedicated thread handling all the precreation suff. The function waits till local recovery is complete, then identify all the unreferenced objects (orphans) using the highest ID referenced by a local and the highest object precreated by the target. The found range is a subject to removal using specially flagged RPC. During this process OSP is marked unavailable for new objects.
Parameters:
[in] env LU environment provided by the caller
[in] d OSP device
Return values:
0 on success
negative negated errno on error
Definition at line 768 of file osp_precreate.c.
References CDEBUG, CERROR, client_obd::cl_import, obd_device::cli, D_HA, DFID, ENTRY, fid_is_zero(), fid_oid(), fid_to_ostid(), GOTO, l_wait_event, LASSERT, LUSTRE_DATA_SEQ_MAX_WIDTH, LUSTRE_OST_VERSION, obdo::o_flags, obdo::o_oi, obdo::o_valid, ost_body::oa, OBD_FL_DELORPHAN, OBD_MD_FLFLAGS, OBD_MD_FLGROUP, obd_device::obd_name, osp_device::opd_got_disconnected, osp_device::opd_index, osp_device::opd_last_used_fid, osp_device::opd_obd, osp_device::opd_pre_waitq, osp_device::opd_recovery_completed, osp_thread_info::osi_fid, osp_env_info(), osp_fid_diff(), osp_get_lastfid_from_ost(), osp_pre_update_status(), osp_precreate_running(), OST_CREATE, OST_MIN_PRECREATE, ostid_to_fid(), PFID, ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_OST_BODY, ptlrpc_request::rq_no_delay, ptlrpc_request::rq_no_resend, ptlrpc_request::rq_pill, RQF_OST_CREATE, and obd_device::u.
Referenced by osp_precreate_thread().
static int osp_precreate_fids (const struct lu_env * env, struct osp_device * osp, struct lu_fid * fid, int * grow) [static]
Find IDs available in current sequence.
The function calculates the highest possible ID and the number of IDs available in the current sequence OSP is using. The number is limited artifically by the caller (grow param) and the number of IDs available in the sequence by nature. The function doesn't require an external locking.
Parameters:
[in] env LU environment provided by the caller
[in] osp OSP device
[in] fid FID the caller wants to start with
[in] grow how many the caller wants
[out] fid the highest calculated FID
[out] grow the number of available IDs calculated
Return values:
0 on success, 1 - the sequence is empty
Definition at line 488 of file osp_precreate.c.
References __u64, CDEBUG, D_INFO, DFID, end, lu_fid::f_oid, fid_is_idif(), fid_to_ostid(), IDIF_MAX_OID, LUSTRE_DATA_SEQ_MAX_WIDTH, ost_id::oi, osp_device::opd_index, osp_thread_info::osi_oi, osp_env_info(), ostid_id(), ostid_set_id(), ostid_to_fid(), and PFID.
Referenced by osp_precreate_send().
void osp_precreate_fini (struct osp_device * d)
Finish precreate functionality of OSP.
Asks all the activity (the thread, update timer) to stop, then wait till that is done.
Parameters:
[in] d OSP device
Definition at line 1596 of file osp_precreate.c.
References cfs_timer_disarm(), ENTRY, EXIT, OBD_FREE_PTR, osp_device::opd_pre, osp_device::opd_pre_thread, osp_device::opd_pre_waitq, osp_device::opd_statfs_timer, RETURN_EXIT, SVC_STOPPED, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, ptlrpc_thread::t_flags, and thread.
Referenced by osp_init0(), and osp_shutdown().
int osp_precreate_get_fid (const struct lu_env * env, struct osp_device * d, struct lu_fid * fid)
Get a FID from precreation pool.
The function is a companion for osp_precreate_reserve() - it assigns a specific FID from the precreate. The function should be called only if the call to osp_precreate_reserve() was successful. The function updates a local storage to remember the highest object ID referenced by the node in the given sequence.
A very importan details: this is supposed to be called once the transaction is started, so on-disk update will be atomic with the data (like LOVEA) refering this object. Then the object won't be leaked: either it's referenced by the committed transaction or it's a subject to the orphan cleanup procedure.
Parameters:
[in] env LU environment provided by the caller
[in] d OSP device
[out] fid generated FID
Return values:
0 on success
negative negated errno on error
Definition at line 1405 of file osp_precreate.c.
References DFID, LASSERTF, osp_device::opd_pre_waitq, osp_fid_diff(), osp_update_last_fid(), PFID, and unlikely.
Referenced by osp_object_assign_fid().
static int osp_precreate_near_empty (const struct lu_env * env, struct osp_device * d) [inline, static]
Check pool of precreated objects.
This is protected version of osp_precreate_near_empty_nolock(), check that for the details.
Parameters:
[in] env LU environment provided by the caller
[in] d OSP device
Return values:
0 - current pool is good enough, 1 - time to precreate
Definition at line 298 of file osp_precreate.c.
References osp_precreate_near_empty_nolock().
Referenced by osp_precreate_thread().
static int osp_precreate_near_empty_nolock (const struct lu_env * env, struct osp_device * d) [inline, static]
Check pool of precreated objects is nearly empty.
We should not wait till the pool of the precreated objects is exhausted, because then there will be a long period of OSP being unavailable for the new creations due to lenghty precreate RPC. Instead we ask for another precreation ahead and hopefully have it ready before the current pool is empty. Notice this function relies on an external locking.
Parameters:
[in] env LU environment provided by the caller
[in] d OSP device
Return values:
0 - current pool is good enough, 1 - time to precreate
Definition at line 276 of file osp_precreate.c.
References osp_objs_precreated().
Referenced by osp_precreate_near_empty(), and osp_precreate_reserve().
static int osp_precreate_ready_condition (const struct lu_env * env, struct osp_device * d) [static]
Check when to stop to wait for precreate objects.
The caller wanting a new OST object can't wait undefinitely. The function checks for few conditions including available new OST objects, disconnected OST, lack of space with no pending destroys, etc. IOW, it checks whether the current OSP state is good to keep waiting or it's better to give up.
Parameters:
[in] env LU environment provided by the caller
[in] d OSP device
Return values:
0 - keep waiting, 1 - no luck
Definition at line 1222 of file osp_precreate.c.
References CERROR, obd_device::obd_name, osp_device::opd_obd, osp_device::opd_syn_changes, osp_device::opd_syn_rpc_in_progress, and osp_objs_precreated().
Referenced by osp_precreate_reserve().
int osp_precreate_reserve (const struct lu_env * env, struct osp_device * d)
Reserve object in precreate pool.
When the caller wants to create a new object on this target (target represented by the given OSP), it should declare this intention using a regular ->dt_declare_create() OSD API method. Then OSP will be trying to reserve an object in the existing precreated pool or wait up to obd_timeout for the available object to appear in the pool (a dedicated thread will be doing real precreation in background). The object can be consumed later with osp_precreate_get_fid() or be released with call to lu_object_put(). Notice the function doesn't reserve a specific ID, just some ID. The actual ID assignment happen in osp_precreate_get_fid(). If the space on the target is short and there is a pending object destroy, then the function forces local commit to speedup space release (see osp_sync.c for the details).
Parameters:
[in] env LU environment provided by the caller
[in] d OSP device
Return values:
0 on success
-ENOSPC when no space on OST
-EAGAIN try later, slow precreation in progress
-EIO when no access to OST
Definition at line 1292 of file osp_precreate.c.
References cfs_time_aftereq(), cfs_time_current(), cfs_time_shift(), DFID, dt_commit_async(), ENTRY, l_wait_event, LASSERTF, LWI_TIMEOUT, obd_timeout, osp_device::opd_pre_waitq, osp_device::opd_storage, osp_device::opd_syn_changes, osp_device::opd_syn_rpc_in_progress, osp_objs_precreated(), osp_precreate_end_seq_nolock(), osp_precreate_near_empty_nolock(), osp_precreate_ready_condition(), osp_precreate_timeout_condition(), PFID, RETURN, and unlikely.
Referenced by osp_declare_object_create().
static int osp_precreate_rollover_new_seq (struct lu_env * env, struct osp_device * osp) [static]
Switch to another sequence.
When a current sequence has no available IDs left, OSP has to switch to another new sequence. OSP requests it using the regular FLDB protocol and stores synchronously before that is used in precreated. This is needed to basically have the sequences referenced (not orphaned), otherwise it's possible that OST has some objects precreated and the clients have data written to it, but after MDT failover nobody refers those objects and OSP has no idea that the sequence need cleanup to be done. While this is very expensive operation, it's supposed to happen very very infrequently because sequence has 2^32 or 2^48 objects (depending on type)
Parameters:
[in] env LU environment provided by the caller
[in] osp OSP device
Return values:
0 on success
negative negated errno on error
Definition at line 428 of file osp_precreate.c.
References CERROR, client_obd::cl_seq, obd_device::cli, DFID, ENTRY, lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, LASSERTF, LCONSOLE_INFO, LPX64, obd_device::obd_name, osp_device::opd_gap_start_fid, osp_device::opd_last_used_fid, osp_device::opd_obd, osp_thread_info::osi_fid, osp_env_info(), osp_write_last_oid_seq_files(), PFID, RETURN, seq_client_get_seq(), and obd_device::u.
Referenced by osp_precreate_thread().
static bool osp_precreate_running (struct osp_device * d) [inline, static]
Definition at line 86 of file osp_precreate.c.
References osp_device::opd_pre_thread, SVC_RUNNING, and ptlrpc_thread::t_flags.
Referenced by osp_init_precreate(), osp_precreate_cleanup_orphans(), osp_precreate_thread(), osp_statfs_interpret(), and osp_statfs_timer_cb().
static int osp_precreate_send (const struct lu_env * env, struct osp_device * d) [static]
Prepare and send precreate RPC.
The function finds how many objects should be precreated. Then allocates, prepares and schedules precreate RPC synchronously. Upon reply the function wake ups the threads waiting for the new objects on this target. If the target wasn't able to create all the objects requested, then the next precreate will be asking less objects (i.e. slow precreate down).
Parameters:
[in] env LU environment provided by the caller
[in] d OSP device
Return values:
0 on success
negative negated errno on error
Definition at line 543 of file osp_precreate.c.
References CDEBUG, CERROR, client_obd::cl_import, obd_device::cli, D_HA, D_INFO, DFID, ENTRY, lu_fid::f_seq, fid_is_idif(), fid_to_ostid(), GOTO, LASSERT, LASSERTF, LUSTRE_OST_VERSION, max, obdo::o_oi, obdo::o_valid, ost_body::oa, OBD_MD_FLGROUP, obd_device::obd_name, osp_device::opd_index, osp_device::opd_obd, osp_device::opd_pre_waitq, osp_thread_info::osi_fid, osp_env_info(), osp_fid_diff(), osp_is_fid_client(), osp_pre_update_status(), osp_precreate_fids(), OST_CREATE, OST_CREATE_PORTAL, OST_MIN_PRECREATE, ostid_to_fid(), PFID, ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_OST_BODY, ptlrpc_request::rq_no_delay, ptlrpc_request::rq_no_resend, ptlrpc_request::rq_pill, ptlrpc_request::rq_transno, RQF_OST_CREATE, obd_device::u, and unlikely.
Referenced by osp_precreate_thread().
static bool osp_precreate_stopped (struct osp_device * d) [inline, static]
Definition at line 91 of file osp_precreate.c.
References osp_device::opd_pre_thread, SVC_STOPPED, and ptlrpc_thread::t_flags.
Referenced by osp_init_precreate().
static int osp_precreate_thread (void * _arg) [static]
The core of precreate functionality.
The function implements the main precreation loop. Basically it involves connecting to the target, precerate FID initialization, identifying and removing orphans, then serving precreation. As part of the latter, the thread is responsible for statfs data updates. The precreation is mostly driven by another threads asking for new OST objects - those askers wake the thread when the number of precreated objects reach low watermark. After a disconnect, the sequence above repeats. This is keep going until the thread is requested to stop.
Parameters:
[in] _arg private data the thread (OSP device to handle)
Return values:
0 on success
negative negated errno on error
Definition at line 1082 of file osp_precreate.c.
References CERROR, client_obd::cl_seq, class_export_put(), obd_device::cli, dt_device::dd_lu_dev, ENTRY, l_wait_event, LASSERT, LCONSOLE_INFO, lu_client_seq::lcs_exp, lu_device::ld_type, lu_device_type::ldt_ctx_tags, LPX64, lu_env_fini(), lu_env_init(), obd_device::obd_name, osp_device::opd_dt_dev, osp_device::opd_exp, osp_device::opd_got_disconnected, osp_device::opd_new_connection, osp_device::opd_obd, osp_device::opd_pre_thread, osp_device::opd_pre_waitq, osp_create_end_seq(), osp_init_pre_fid(), osp_precreate_cleanup_orphans(), osp_precreate_end_seq(), osp_precreate_near_empty(), osp_precreate_rollover_new_seq(), osp_precreate_running(), osp_precreate_send(), osp_statfs_need_update(), osp_statfs_update(), RETURN, SVC_RUNNING, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, ptlrpc_thread::t_flags, thread, obd_device::u, and unlikely.
Referenced by osp_init_precreate().
static int osp_precreate_timeout_condition (void * data) [static]
Definition at line 1253 of file osp_precreate.c.
References CDEBUG, D_HA, DFID, LPU64, obd_device::obd_name, osp_device::opd_obd, osp_device::opd_syn_changes, osp_device::opd_syn_rpc_in_progress, and PFID.
Referenced by osp_precreate_reserve().
static int osp_statfs_interpret (const struct lu_env * env, struct ptlrpc_request * req, union ptlrpc_async_args * aa, int rc) [static]
RPC interpret callback for OST_STATFS RPC.
An interpretation callback called by ptlrpc for OST_STATFS RPC when it is replied by the target. It's used to maintain statfs cache for the target. The function fills data from the reply if successful and schedules another update.
Parameters:
[in] env LU environment provided by the caller
[in] req RPC replied
[in] aa callback data
[in] rc RPC result
Return values:
0 on success
negative negated errno on error
Definition at line 121 of file osp_precreate.c.
References CDEBUG, cfs_time_shift(), cfs_timer_arm(), D_CACHE, ENTRY, GOTO, obd_import::imp_generation, LASSERT, obd_device::obd_name, osp_device::opd_obd, osp_device::opd_pre, osp_device::opd_pre_waitq, osp_device::opd_statfs, osp_device::opd_statfs_fresh_till, osp_device::opd_statfs_maxage, osp_device::opd_statfs_timer, osp_device::opd_statfs_update_in_progress, osp_pre_update_status(), osp_precreate_running(), ptlrpc_async_args::pointer_arg, ptlrpc_req_async_args, req_capsule_server_get(), RETURN, RMF_OBD_STATFS, ptlrpc_request::rq_import, and ptlrpc_request::rq_pill.
Referenced by osp_statfs_update().
void osp_statfs_need_now (struct osp_device * d)
Schedule an immediate update for statfs data.
If cached statfs data claim no free space, but OSP has got a request to destroy an object (so release some space probably), then we may need to refresh cached statfs data sooner than planned. The function checks there is no statfs update going and schedules immediate update if so. XXX: there might be a case where removed object(s) do not add free space (empty object). If the number of such deletions is high, then we can start to update statfs too often causing a RPC storm. some throttling is needed...
Parameters:
[in] d OSP device where statfs data needs to be refreshed
Definition at line 231 of file osp_precreate.c.
References cfs_time_shift(), cfs_timer_disarm(), osp_device::opd_pre_waitq, osp_device::opd_statfs_fresh_till, osp_device::opd_statfs_timer, and osp_device::opd_statfs_update_in_progress.
Referenced by osp_sync_interpret(), and osp_sync_process_committed().
static int osp_statfs_need_update (struct osp_device * d) [inline, static]
Definition at line 74 of file osp_precreate.c.
References cfs_time_before(), cfs_time_current(), and osp_device::opd_statfs_fresh_till.
Referenced by osp_precreate_thread().
static void osp_statfs_timer_cb (unsigned long _d) [static]
Definition at line 96 of file osp_precreate.c.
References LASSERT, osp_device::opd_pre, osp_device::opd_pre_waitq, and osp_precreate_running().
Referenced by osp_init_precreate().
static int osp_statfs_update (struct osp_device * d) [static]
Send OST_STATFS RPC.
Sends OST_STATFS RPC to refresh cached statfs data for the target. Also disables scheduled updates as times OSP may need to refresh statfs data before expiration. The function doesn't block, instead an interpretation callback osp_statfs_interpret() is used.
Parameters:
[in] d OSP device
Definition at line 175 of file osp_precreate.c.
References CDEBUG, cfs_time_shift(), cfs_timer_disarm(), client_obd::cl_import, obd_device::cli, D_CACHE, ENTRY, LASSERT, LUSTRE_OST_VERSION, obd_timeout, osp_device::opd_obd, osp_device::opd_statfs_fresh_till, osp_device::opd_statfs_timer, osp_device::opd_statfs_update_in_progress, osp_statfs_interpret(), OST_CREATE_PORTAL, OST_STATFS, ptlrpc_async_args::pointer_arg, ptlrpc_at_set_req_timeout(), ptlrpc_req_async_args, ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), ptlrpcd_add_req(), RETURN, RQF_OST_STATFS, and obd_device::u.
Referenced by osp_precreate_thread().
int osp_write_last_oid_seq_files (struct lu_env * env, struct osp_device * osp, struct lu_fid * fid, int sync)
Write FID into into last_oid/last_seq file.
The function stores the sequence and the in-sequence id into two dedicated files. The sync argument can be used to request synchronous commit, so the function won't return until the updates are committed.
Parameters:
[in] env LU environment provided by the caller
[in] osp OSP device
[in] fid fid where sequence/id is taken
[in] sync update mode: 0 - asynchronously, 1 - synchronously
Return values:
0 on success
negative negated errno on error
Definition at line 349 of file osp_precreate.c.
References CERROR, dt_declare_record_write(), dt_record_write(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), ENTRY, lu_fid::f_oid, lu_fid::f_seq, GOTO, lu_buf::lb_buf, lu_buf::lb_len, obd_device::obd_name, osp_device::opd_index, osp_device::opd_last_used_oid_file, osp_device::opd_last_used_seq_file, osp_device::opd_obd, osp_device::opd_storage, osp_thread_info::osi_lb, osp_thread_info::osi_lb2, osp_env_info(), RETURN, and thandle::th_sync.
Referenced by osp_init_pre_fid(), and osp_precreate_rollover_new_seq().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.