Lustre: lustre/osp/osp_sync.c File Reference
lustre/osp/osp_sync.c File Reference
#include <linux/kthread.h>
#include <lustre_log.h>
#include <lustre_update.h>
#include "osp_internal.h"
Data Structures
struct osp_job_req_args
Defines
#define DEBUG_SUBSYSTEM S_MDS
#define OSP_SYN_THRESHOLD 10
#define OSP_MAX_IN_FLIGHT 8
#define OSP_MAX_IN_PROGRESS 4096
#define OSP_JOB_MAGIC 0x26112005
#define osp_sync_check_for_work(d)
Functions
static int osp_sync_id_traction_init (struct osp_device *d)
Initialize commit tracking mechanism.
static void osp_sync_id_traction_fini (struct osp_device *d)
Release commit tracker.
static __u32 osp_sync_id_get (struct osp_device *d, __u32 id)
Generate a new ID on a tracker.
static void osp_sync_remove_from_tracker (struct osp_device *d)
Stop to propagate commit status to OSP.
static int osp_sync_running (struct osp_device *d)
static int osp_sync_stopped (struct osp_device *d)
Check status: whether OSP thread has stopped.
static int osp_sync_has_new_job (struct osp_device *d)
static int osp_sync_inflight_conflict (struct osp_device *d, struct llog_rec_hdr *h)
static int osp_sync_low_in_progress (struct osp_device *d)
static int osp_sync_low_in_flight (struct osp_device *d)
Check for room in the network pipe to OST.
static int osp_sync_has_work (struct osp_device *d)
Wake up check for the main sync thread.
void __osp_sync_check_for_work (struct osp_device *d)
static int osp_sync_can_process_new (struct osp_device *d, struct llog_rec_hdr *rec)
Check and return ready-for-new status.
int osp_sync_declare_add (const struct lu_env *env, struct osp_object *o, llog_op_type type, struct thandle *th)
Declare intention to add a new change.
static int osp_sync_add_rec (const struct lu_env *env, struct osp_device *d, const struct lu_fid *fid, llog_op_type type, int count, struct thandle *th, const struct lu_attr *attr)
Generate a llog record for a given change.
int osp_sync_add (const struct lu_env *env, struct osp_object *o, llog_op_type type, struct thandle *th, const struct lu_attr *attr)
int osp_sync_gap (const struct lu_env *env, struct osp_device *d, struct lu_fid *fid, int lost, struct thandle *th)
static void osp_sync_request_commit_cb (struct ptlrpc_request *req)
ptlrpc commit callback.
static int osp_sync_interpret (const struct lu_env *env, struct ptlrpc_request *req, void *aa, int rc)
RPC interpretation callback.
static void osp_sync_send_new_rpc (struct osp_device *d, struct ptlrpc_request *req)
static struct ptlrpc_request * osp_sync_new_job (struct osp_device *d, struct llog_handle *llh, struct llog_rec_hdr *h, ost_cmd_t op, const struct req_format *format)
Allocate and prepare RPC for a new change.
static int osp_sync_new_setattr_job (struct osp_device *d, struct llog_handle *llh, struct llog_rec_hdr *h)
Generate a request for setattr change.
static int osp_sync_new_unlink_job (struct osp_device *d, struct llog_handle *llh, struct llog_rec_hdr *h)
Generate a request for unlink change.
static int osp_sync_new_unlink64_job (struct osp_device *d, struct llog_handle *llh, struct llog_rec_hdr *h)
Generate a request for unlink change.
static void osp_sync_process_record (const struct lu_env *env, struct osp_device *d, struct llog_handle *llh, struct llog_rec_hdr *rec)
Process llog records.
static void osp_sync_process_committed (const struct lu_env *env, struct osp_device *d)
Cancel llog records for the committed changes.
static int osp_sync_process_queues (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *rec, void *data)
The core of the syncing mechanism.
static int osp_sync_thread (void *_arg)
OSP sync thread.
static int osp_sync_llog_init (const struct lu_env *env, struct osp_device *d)
Initialize llog.
static void osp_sync_llog_fini (const struct lu_env *env, struct osp_device *d)
Cleanup llog used for syncing.
int osp_sync_init (const struct lu_env *env, struct osp_device *d)
Initialization of the sync component of OSP.
int osp_sync_fini (struct osp_device *d)
Stop the syncing thread.
static DEFINE_MUTEX (osp_id_tracker_sem)
static void osp_sync_tracker_commit_cb (struct thandle *th, void *cookie)
OSD commit callback.
Variables
static struct list_head osp_id_tracker_list
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 44 of file osp_sync.c.
#define OSP_JOB_MAGIC 0x26112005
Definition at line 96 of file osp_sync.c.
Referenced by osp_sync_inflight_conflict(), osp_sync_interpret(), osp_sync_process_committed(), osp_sync_request_commit_cb(), and osp_sync_send_new_rpc().
#define OSP_MAX_IN_FLIGHT 8
Definition at line 93 of file osp_sync.c.
Referenced by osp_sync_init().
#define OSP_MAX_IN_PROGRESS 4096
Definition at line 94 of file osp_sync.c.
Referenced by osp_sync_init().
#define OSP_SYN_THRESHOLD 10
Definition at line 92 of file osp_sync.c.
#define osp_sync_check_for_work (d)
Value:
{                                                       \
        if (osp_sync_has_work(d)) {                     \
                wake_up(&d->opd_syn_waitq);    \
        }                                               \
}
Definition at line 229 of file osp_sync.c.
Referenced by __osp_sync_check_for_work(), osp_sync_interpret(), and osp_sync_process_committed().
Function Documentation
void __osp_sync_check_for_work (struct osp_device * d)
Definition at line 236 of file osp_sync.c.
References osp_sync_check_for_work.
Referenced by osp_import_event(), and osp_sync().
static DEFINE_MUTEX (osp_id_tracker_sem) [static]
int osp_sync_add (const struct lu_env * env, struct osp_object * o, llog_op_type type, struct thandle * th, const struct lu_attr * attr)
Definition at line 429 of file osp_sync.c.
References dt_object::do_lu, lu_object::lo_dev, lu2osp_dev(), lu_object_fid(), osp_object::opo_obj, and osp_sync_add_rec().
Referenced by osp_attr_set(), and osp_object_destroy().
static int osp_sync_add_rec (const struct lu_env * env, struct osp_device * d, const struct lu_fid * fid, llog_op_type type, int count, struct thandle * th, const struct lu_attr * attr) [static]
Generate a llog record for a given change.
Generates a llog record for the change passed. The change can be of two types: unlink and setattr. The record gets an ID which later will be used to track commit status of the change. For unlink changes, the caller can supply a starting FID and the count of the objects to destroy. For setattr the caller should apply attributes to apply.
Parameters:
[in] env LU environment provided by the caller
[in] d OSP device
[in] fid fid of the object the change should be applied to
[in] type type of change: MDS_UNLINK64_REC or MDS_SETATTR64_REC
[in] count count of objects to destroy
[in] th transaction handle (local)
[in] attr attributes for setattr
Return values:
0 on success
negative negated errno on error
Definition at line 357 of file osp_sync.c.
References CDEBUG, D_OTHER, DOSTID, ENTRY, fid_to_ostid(), LA_GID, lu_attr::la_gid, LA_UID, lu_attr::la_uid, lu_attr::la_valid, LASSERT, LBUG, llog_cookie::lgc_index, llog_cookie::lgc_lgl, llog_logid::lgl_ogen, llog_logid::lgl_oi, likely, llog_add(), llog_ctxt_put(), llog_get_context(), LLOG_MDS_OST_ORIG_CTXT, llog_ctxt::loc_handle, llog_rec_hdr::lrh_id, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, llog_setattr64_rec::lsr_gid, llog_setattr64_rec::lsr_oi, llog_setattr64_rec::lsr_uid, llog_setattr64_rec::lsr_valid, llog_unlink64_rec::lur_count, llog_unlink64_rec::lur_fid, MDS_SETATTR64_REC, MDS_UNLINK64_REC, OBD_MD_FLGID, OBD_MD_FLUID, obd_device::obd_name, osp_device::opd_obd, osp_device::opd_storage, osp_device::opd_syn_changes, osp_device::opd_syn_lock, osp_thread_info::osi_cookie, osp_thread_info::osi_hdr, osp_thread_info::osi_oi, osp_thread_info::osi_setattr, osp_thread_info::osi_unlink, osp_env_info(), osp_sync_id_get(), osp_txn_info(), osp_txn_info::oti_current_id, POSTID, RETURN, thandle::th_ctx, thandle::th_top, and thandle_get_sub_by_dt().
Referenced by osp_sync_add(), and osp_sync_gap().
static int osp_sync_can_process_new (struct osp_device * d, struct llog_rec_hdr * rec) [inline, static]
Check and return ready-for-new status.
The thread processing llog record uses this function to check whether it's time to take another record and process it. The number of conditions must be met: the connection should be ready, RPCs in flight not exceeding the limit, the record is committed locally, etc (see the lines below).
Parameters:
[in] d OSP device
[in] rec next llog record to process
Return values:
0 not ready
1 ready
Definition at line 255 of file osp_sync.c.
References LASSERT, llog_rec_hdr::lrh_id, osp_device::opd_imp_connected, osp_device::opd_syn_barrier, osp_device::opd_syn_changes, osp_device::opd_syn_last_committed_id, osp_device::opd_syn_prev_done, osp_sync_inflight_conflict(), osp_sync_low_in_flight(), osp_sync_low_in_progress(), and unlikely.
Referenced by osp_sync_process_queues().
int osp_sync_declare_add (const struct lu_env * env, struct osp_object * o, llog_op_type type, struct thandle * th)
Declare intention to add a new change.
With regard to OSD API, we have to declare any changes ahead. In this case we declare an intention to add a llog record representing the change on the local storage.
Parameters:
[in] env LU environment provided by the caller
[in] o OSP object
[in] type type of change: MDS_UNLINK64_REC or MDS_SETATTR64_REC
[in] th transaction handle (local)
Return values:
0 on success
negative negated errno on error
Definition at line 294 of file osp_sync.c.
References dt_object::do_lu, ENTRY, LASSERT, LBUG, LCT_OSP_THREAD, llog_ctxt_put(), llog_declare_add(), llog_get_context(), LLOG_MDS_OST_ORIG_CTXT, lu_object::lo_dev, llog_ctxt::loc_handle, llog_rec_hdr::lrh_len, lu2osp_dev(), MDS_SETATTR64_REC, MDS_UNLINK64_REC, osp_device::opd_obd, osp_device::opd_storage, osp_object::opo_obj, osp_thread_info::osi_hdr, osp_env_info(), RETURN, thandle::th_tags, thandle::th_top, and thandle_get_sub_by_dt().
Referenced by osp_declare_attr_set(), and osp_declare_object_destroy().
int osp_sync_fini (struct osp_device * d)
Stop the syncing thread.
Asks the syncing thread to stop and wait until it's stopped.
Parameters:
[in] d OSP device
Return values:
0
Definition at line 1444 of file osp_sync.c.
References ENTRY, osp_device::opd_syn_thread, osp_device::opd_syn_waitq, osp_sync_id_traction_fini(), RETURN, SVC_STOPPED, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, ptlrpc_thread::t_flags, and thread.
Referenced by osp_init0(), and osp_shutdown().
int osp_sync_gap (const struct lu_env * env, struct osp_device * d, struct lu_fid * fid, int lost, struct thandle * th)
Definition at line 438 of file osp_sync.c.
References MDS_UNLINK64_REC, and osp_sync_add_rec().
static int osp_sync_has_new_job (struct osp_device * d) [inline, static]
Definition at line 132 of file osp_sync.c.
References osp_device::opd_syn_last_committed_id, osp_device::opd_syn_last_processed_id, osp_device::opd_syn_last_used_id, and osp_device::opd_syn_prev_done.
Referenced by osp_sync_has_work().
static int osp_sync_has_work (struct osp_device * d) [inline, static]
Wake up check for the main sync thread.
Parameters:
[in] d OSP device
Return values:
1 time to wake up
0 no need to wake up
Definition at line 215 of file osp_sync.c.
References list_empty(), osp_device::opd_imp_connected, osp_device::opd_syn_committed_there, osp_sync_has_new_job(), osp_sync_low_in_flight(), and osp_sync_low_in_progress().
static __u32 osp_sync_id_get (struct osp_device * d, __u32 id) [static]
Generate a new ID on a tracker.
Generates a new ID using the tracker associated with the given OSP device d, if the given ID id is non-zero. Unconditially adds OSP device to the wakeup list, so OSP won't miss when a transaction using the ID is committed. Notice ID is 32bit, but llog doesn't support >2^32 records anyway.
Parameters:
[in] d OSP device
[in] id 0 or ID generated previously
Return values:
ID the caller should use
Definition at line 1617 of file osp_sync.c.
References CDEBUG, CERROR, D_OTHER, LASSERT, LBUG, list_add(), list_empty(), obd_device::obd_name, osp_device::opd_obd, osp_device::opd_syn_last_used_id, osp_device::opd_syn_ontrack, osp_device::opd_syn_tracker, osp_id_tracker::otr_lock, osp_id_tracker::otr_next_id, osp_id_tracker::otr_wakeup_list, and unlikely.
Referenced by osp_sync_add_rec().
static void osp_sync_id_traction_fini (struct osp_device * d) [static]
Release commit tracker.
Decrease a refcounter on the tracker used by the given OSP device d. If no more users left, then the tracker is released.
Parameters:
[in] d OSP device
Definition at line 1576 of file osp_sync.c.
References dt_txn_callback_del(), ENTRY, EXIT, LASSERT, list_del(), list_empty(), OBD_FREE_PTR, osp_device::opd_storage, osp_device::opd_syn_tracker, osp_sync_remove_from_tracker(), osp_id_tracker::otr_list, osp_id_tracker::otr_refcount, osp_id_tracker::otr_tx_cb, and osp_id_tracker::otr_wakeup_list.
Referenced by osp_sync_fini(), and osp_sync_init().
static int osp_sync_id_traction_init (struct osp_device * d) [static]
Initialize commit tracking mechanism.
Some setups may have thousands of OSTs and each will be represented by OSP. Meaning order of magnitute many more changes to apply every second. In order to keep the number of commit callbacks low this mechanism was introduced. The mechanism is very similar to transno used by MDT service: it's an single ID stream which can be assigned by any OSP to its llog records. The tricky part is that ID is stored in per-transaction data and re-used by all the OSPs involved in that transaction. Then all these OSPs are woken up utilizing a single OSD commit callback.
The function initializes the data used by the tracker described above. A singler tracker per OSD device is created.
Parameters:
[in] d OSP device
Return values:
0 on success
negative negated errno on error
Definition at line 1522 of file osp_sync.c.
References dt_txn_callback_add(), dt_txn_callback::dtc_cookie, dt_txn_callback::dtc_tag, dt_txn_callback::dtc_txn_commit, INIT_LIST_HEAD, LASSERT, LCT_MD_THREAD, list_add(), list_for_each_entry, OBD_ALLOC_PTR, osp_device::opd_storage, osp_device::opd_syn_ontrack, osp_device::opd_syn_tracker, osp_sync_tracker_commit_cb(), osp_id_tracker::otr_committed_id, osp_id_tracker::otr_dev, osp_id_tracker::otr_list, osp_id_tracker::otr_lock, osp_id_tracker::otr_next_id, osp_id_tracker::otr_refcount, osp_id_tracker::otr_tx_cb, and osp_id_tracker::otr_wakeup_list.
Referenced by osp_sync_init().
static int osp_sync_inflight_conflict (struct osp_device * d, struct llog_rec_hdr * h) [inline, static]
Definition at line 139 of file osp_sync.c.
References fid_to_ostid(), osp_job_req_args::jra_magic, LASSERT, LBUG, list_empty(), list_for_each_entry, LLOG_GEN_REC, llog_rec_hdr::lrh_type, MDS_SETATTR64_REC, MDS_UNLINK64_REC, MDS_UNLINK_REC, obdo::o_oi, ost_body::oa, osp_device::opd_syn_inflight_list, osp_device::opd_syn_lock, OSP_JOB_MAGIC, ostid_set_id(), ostid_set_seq(), req_capsule_client_get(), RMF_OST_BODY, rq_async_args, and ptlrpc_request::rq_pill.
Referenced by osp_sync_can_process_new().
int osp_sync_init (const struct lu_env * env, struct osp_device * d)
Initialization of the sync component of OSP.
Initializes the llog and starts a new thread to handle the changes to the remote target (OST or MDT).
Parameters:
[in] env LU environment provided by the caller
[in] d OSP device
Return values:
0 on success
negative negated errno on error
Definition at line 1381 of file osp_sync.c.
References CERROR, ENTRY, GOTO, INIT_LIST_HEAD, l_wait_event, obd_device::obd_name, osp_device::opd_group, osp_device::opd_index, osp_device::opd_obd, osp_device::opd_syn_barrier_waitq, osp_device::opd_syn_committed_there, osp_device::opd_syn_inflight_list, osp_device::opd_syn_lock, osp_device::opd_syn_max_rpc_in_flight, osp_device::opd_syn_max_rpc_in_progress, osp_device::opd_syn_thread, osp_device::opd_syn_waitq, OSP_MAX_IN_FLIGHT, OSP_MAX_IN_PROGRESS, osp_sync_id_traction_fini(), osp_sync_id_traction_init(), osp_sync_llog_fini(), osp_sync_llog_init(), osp_sync_running(), osp_sync_stopped(), osp_sync_thread(), RETURN, and ptlrpc_thread::t_ctl_waitq.
Referenced by osp_init0().
static int osp_sync_interpret (const struct lu_env * env, struct ptlrpc_request * req, void * aa, int rc) [static]
RPC interpretation callback.
The callback is called by ptlrpc when RPC is replied. Now we have to decide whether we should:
put request on a special list to wait until it's committed by the target, if the request is successful
schedule llog record cancel if no target object is found
try later (essentially after reboot) in case of unexpected error
Parameters:
[in] env LU environment provided by the caller
[in] req request replied
[in] aa callback data
[in] rc result of RPC
Return values:
0 always
Definition at line 515 of file osp_sync.c.
References CDEBUG, D_ERROR, D_HA, D_OTHER, DEBUG_REQ, obd_import::imp_generation, osp_job_req_args::jra_committed_link, osp_job_req_args::jra_inflight_link, osp_job_req_args::jra_magic, LASSERT, LASSERTF, LBUG, list_add(), list_del_init(), list_empty(), LPU64, obd_device::obd_name, osp_device::opd_obd, osp_device::opd_pre, osp_device::opd_syn_barrier, osp_device::opd_syn_barrier_waitq, osp_device::opd_syn_committed_there, osp_device::opd_syn_lock, osp_device::opd_syn_rpc_in_flight, osp_device::opd_syn_rpc_in_progress, osp_device::opd_syn_waitq, OSP_JOB_MAGIC, osp_statfs_need_now(), osp_sync_check_for_work, ptlrpc_request_addref(), ptlrpc_request::rq_import, ptlrpc_request::rq_refcount, ptlrpc_request::rq_transno, and unlikely.
Referenced by osp_sync_new_job().
static void osp_sync_llog_fini (const struct lu_env * env, struct osp_device * d) [static]
Cleanup llog used for syncing.
Closes and cleanups the llog. The function is called when the device is shutting down.
Parameters:
[in] env LU environment provided by the caller
[in] d OSP device
Definition at line 1359 of file osp_sync.c.
References llog_cat_close(), llog_cleanup(), llog_get_context(), LLOG_MDS_OST_ORIG_CTXT, llog_ctxt::loc_handle, and osp_device::opd_obd.
Referenced by osp_sync_init().
static int osp_sync_llog_init (const struct lu_env * env, struct osp_device * d) [static]
Initialize llog.
Initializes the llog. Specific llog to be used depends on the type of the target OSP represents (OST or MDT). The function adds appends a new llog record to mark the place where the records associated with this boot start.
Parameters:
[in] env LU environment provided by the caller
[in] d OSP device
Return values:
0 on success
negative negated errno on error
Definition at line 1244 of file osp_sync.c.
References CDEBUG, CERROR, cfs_time_current(), llog_gen::conn_cnt, D_INFO, dt_device::dd_lu_dev, DOSTID, lvfs_run_ctxt::dt, ENTRY, GOTO, LASSERT, llog_catid::lci_logid, lu_device::ld_obd, llog_handle::lgh_id, llog_logid::lgl_ogen, llog_logid::lgl_oi, llog_gen_rec::lgr_gen, llog_gen_rec::lgr_hdr, likely, llog_cat_add(), llog_cat_close(), LLOG_CATALOGS_OID, llog_cleanup(), llog_ctxt_put(), LLOG_F_IS_CAT, LLOG_GEN_REC, llog_get_context(), llog_init_handle(), LLOG_MDS_OST_ORIG_CTXT, llog_open(), llog_open_create(), LLOG_OPEN_EXISTS, llog_osd_get_cat_list(), llog_osd_put_cat_list(), llog_setup(), llog_ctxt::loc_handle, logid_id(), logid_set_id(), llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, lu_local_obj_fid(), llog_gen::mnt_cnt, obd_device::obd_lvfs_ctxt, obd_device::obd_name, obd_device::obd_olg, OBD_SET_CTXT_MAGIC(), osp_device::opd_index, osp_device::opd_obd, osp_device::opd_storage, osp_device::opd_syn_generation, osp_thread_info::osi_cid, osp_thread_info::osi_cookie, osp_thread_info::osi_fid, osp_thread_info::osi_gen, osp_thread_info::osi_hdr, osp_env_info(), osp_mds_ost_orig_logops, POSTID, RETURN, and unlikely.
Referenced by osp_sync_init().
static int osp_sync_low_in_flight (struct osp_device * d) [inline, static]
Check for room in the network pipe to OST.
Parameters:
[in] d OSP device
Return values:
1 there is room
0 no room, the pipe is full
Definition at line 202 of file osp_sync.c.
References osp_device::opd_syn_max_rpc_in_flight, and osp_device::opd_syn_rpc_in_flight.
Referenced by osp_sync_can_process_new(), and osp_sync_has_work().
static int osp_sync_low_in_progress (struct osp_device * d) [inline, static]
Definition at line 189 of file osp_sync.c.
References osp_device::opd_syn_max_rpc_in_progress, and osp_device::opd_syn_rpc_in_progress.
Referenced by osp_sync_can_process_new(), and osp_sync_has_work().
static struct ptlrpc_request* osp_sync_new_job (struct osp_device * d, struct llog_handle * llh, struct llog_rec_hdr * h, ost_cmd_t op, const struct req_format * format) [static, read]
Allocate and prepare RPC for a new change.
The function allocates and initializes an RPC which will be sent soon to apply the change to the target OST. The request is initialized from the llog record passed. Notice only the fields common to all type of changes are initialized.
Parameters:
[in] d OSP device
[in] llh llog handle where the record is stored
[in] h llog record
[in] op type of the change
[in] format request format to be used
Return values:
pointer new request on success
ERR_PTR(errno) on error
Definition at line 637 of file osp_sync.c.
References client_obd::cl_import, obd_device::cli, LASSERT, llog_cookie::lgc_index, llog_cookie::lgc_lgl, llog_cookie::lgc_subsys, llog_handle::lgh_id, LLOG_MDS_OST_ORIG_CTXT, llog_rec_hdr::lrh_index, LUSTRE_OST_VERSION, obdo::o_lcookie, ost_body::oa, OBD_FAIL_CHECK, OBD_FAIL_OSP_CHECK_ENOMEM, osp_device::opd_obd, osp_sync_interpret(), osp_sync_request_commit_cb(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), req_capsule_client_get(), RETURN, RMF_OST_BODY, ptlrpc_request::rq_pill, and obd_device::u.
Referenced by osp_sync_new_setattr_job(), osp_sync_new_unlink64_job(), and osp_sync_new_unlink_job().
static int osp_sync_new_setattr_job (struct osp_device * d, struct llog_handle * llh, struct llog_rec_hdr * h) [static]
Generate a request for setattr change.
The function prepares a new RPC, initializes it with setattr specific bits and send the RPC.
Parameters:
[in] d OSP device
[in] llh llog handle where the record is stored
[in] h llog record
Return values:
0 on success
1 on invalid record
negative negated errno on error
Definition at line 700 of file osp_sync.c.
References CERROR, ENTRY, LASSERT, LPU64, llog_rec_hdr::lrh_type, llog_setattr64_rec::lsr_gid, llog_setattr64_rec::lsr_oi, llog_setattr64_rec::lsr_uid, llog_setattr64_rec::lsr_valid, MDS_SETATTR64_REC, obdo::o_gid, obdo::o_oi, obdo::o_uid, obdo::o_valid, ost_body::oa, OBD_FAIL_CHECK, OBD_FAIL_OSP_CHECK_INVALID_REC, OBD_MD_FLGID, OBD_MD_FLGROUP, OBD_MD_FLID, OBD_MD_FLUID, obd_device::obd_name, osp_device::opd_obd, osp_sync_new_job(), osp_sync_send_new_rpc(), OST_SETATTR, req_capsule_client_get(), RETURN, RMF_OST_BODY, ptlrpc_request::rq_pill, and RQF_OST_SETATTR.
Referenced by osp_sync_process_record().
static int osp_sync_new_unlink64_job (struct osp_device * d, struct llog_handle * llh, struct llog_rec_hdr * h) [static]
Generate a request for unlink change.
The function prepares a new RPC, initializes it with unlink(destroy) specific bits and sends the RPC. Depending on the target (MDT or OST) two different protocols are used. For MDT we use OUT (basically OSD API updates transferred via a network). For OST we still use the old protocol (OBD?), originally for compatibility. Later we can start to use OUT for OST as well, this will allow batching and better code unification.
Parameters:
[in] d OSP device
[in] llh llog handle where the record is stored
[in] h llog record
Return values:
0 on success
negative negated errno on error
Definition at line 804 of file osp_sync.c.
References ENTRY, fid_to_ostid(), LASSERT, llog_rec_hdr::lrh_type, llog_unlink64_rec::lur_count, llog_unlink64_rec::lur_fid, MDS_UNLINK64_REC, obdo::o_misc, obdo::o_oi, obdo::o_valid, ost_body::oa, OBD_MD_FLGROUP, OBD_MD_FLID, OBD_MD_FLOBJCOUNT, osp_sync_new_job(), osp_sync_send_new_rpc(), OST_DESTROY, req_capsule_client_get(), RETURN, RMF_OST_BODY, ptlrpc_request::rq_pill, and RQF_OST_DESTROY.
Referenced by osp_sync_process_record().
static int osp_sync_new_unlink_job (struct osp_device * d, struct llog_handle * llh, struct llog_rec_hdr * h) [static]
Generate a request for unlink change.
The function prepares a new RPC, initializes it with unlink(destroy) specific bits and sends the RPC. The function is used to handle llog_unlink_rec which were used in the older versions of Lustre. Current version uses llog_unlink_rec64.
Parameters:
[in] d OSP device
[in] llh llog handle where the record is stored
[in] h llog record
Return values:
0 on success
negative negated errno on error
Definition at line 758 of file osp_sync.c.
References ENTRY, LASSERT, llog_rec_hdr::lrh_type, llog_unlink_rec::lur_count, llog_unlink_rec::lur_oid, llog_unlink_rec::lur_oseq, MDS_UNLINK_REC, obdo::o_misc, obdo::o_oi, obdo::o_valid, ost_body::oa, OBD_MD_FLGROUP, OBD_MD_FLID, OBD_MD_FLOBJCOUNT, osp_sync_new_job(), osp_sync_send_new_rpc(), OST_DESTROY, ostid_set_id(), ostid_set_seq(), req_capsule_client_get(), RETURN, RMF_OST_BODY, ptlrpc_request::rq_pill, and RQF_OST_DESTROY.
Referenced by osp_sync_process_record().
static void osp_sync_process_committed (const struct lu_env * env, struct osp_device * d) [static]
Cancel llog records for the committed changes.
The function walks through the list of the committed RPCs and cancels corresponding llog records. see osp_sync_request_commit_cb() for the details.
Parameters:
[in] env LU environment provided by the caller
[in] d OSP device
Definition at line 966 of file osp_sync.c.
References CDEBUG, CERROR, client_obd::cl_import, obd_device::cli, D_OTHER, DEBUG_REQ, done, ENTRY, EXIT, obd_import::imp_generation, obd_import::imp_peer_committed_transno, INIT_LIST_HEAD, osp_job_req_args::jra_committed_link, osp_job_req_args::jra_magic, LASSERT, list_del_init(), list_empty(), list_entry, list_splice(), llog_cat_cancel_records(), llog_ctxt_put(), llog_get_context(), LLOG_MDS_OST_ORIG_CTXT, llog_ctxt::loc_handle, LPU64, list_head::next, obdo::o_lcookie, ost_body::oa, obd_device::obd_name, osp_device::opd_obd, osp_device::opd_pre, osp_device::opd_syn_committed_there, osp_device::opd_syn_lock, osp_device::opd_syn_rpc_in_flight, osp_device::opd_syn_rpc_in_progress, osp_device::opd_syn_waitq, OSP_JOB_MAGIC, osp_statfs_need_now(), osp_sync_check_for_work, osp_sync_running(), ptlrpc_req_finished(), req_capsule_client_get(), RMF_OST_BODY, rq_async_args, ptlrpc_request::rq_pill, obd_device::u, and unlikely.
Referenced by osp_sync_process_queues(), and osp_sync_thread().
static int osp_sync_process_queues (const struct lu_env * env, struct llog_handle * llh, struct llog_rec_hdr * rec, void * data) [static]
The core of the syncing mechanism.
This is a callback called by the llog processing function. Essentially it suspends llog processing until there is a record to process (it's supposed to be committed locally). The function handles RPCs committed by the target and cancels corresponding llog records.
Parameters:
[in] env LU environment provided by the caller
[in] llh llog handle we're processing
[in] rec current llog record
[in] data callback data containing a pointer to the device
Return values:
0 to ask the caller (llog_process()) to continue
LLOG_PROC_BREAK to ask the caller to break
Definition at line 1076 of file osp_sync.c.
References CDEBUG, D_HA, l_wait_event, list_empty(), LLOG_PROC_BREAK, osp_device::opd_syn_changes, osp_device::opd_syn_committed_there, osp_device::opd_syn_last_processed_id, osp_device::opd_syn_last_used_id, osp_device::opd_syn_rpc_in_flight, osp_device::opd_syn_rpc_in_progress, osp_device::opd_syn_waitq, osp_sync_can_process_new(), osp_sync_process_committed(), osp_sync_process_record(), osp_sync_remove_from_tracker(), and osp_sync_running().
Referenced by osp_sync_thread().
static void osp_sync_process_record (const struct lu_env * env, struct osp_device * d, struct llog_handle * llh, struct llog_rec_hdr * rec) [static]
Process llog records.
This function is called to process the llog records committed locally. In the recovery model used by OSP we can apply a change to a remote target once corresponding transaction (like posix unlink) is committed locally so can't revert. Depending on the llog record type, a given handler is called that is responsible for preparing and sending the RPC to apply the change. Special record type LLOG_GEN_REC marking a reboot is cancelled right away.
Parameters:
[in] env LU environment provided by the caller
[in] d OSP device
[in] llh llog handle where the record is stored
[in] rec llog record
Definition at line 849 of file osp_sync.c.
References CDEBUG, CERROR, D_HA, D_OTHER, DFID, dt_object::do_lu, ENTRY, LASSERT, llog_cookie::lgc_index, llog_cookie::lgc_lgl, llog_cookie::lgc_subsys, llog_handle::lgh_id, llog_handle::lgh_obj, llog_gen_rec::lgr_gen, llog_cat_cancel_records(), LLOG_GEN_REC, LLOG_MDS_OST_ORIG_CTXT, llog_rec_hdr::lrh_id, llog_rec_hdr::lrh_index, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, lu_object_fid(), MDS_SETATTR64_REC, MDS_UNLINK64_REC, MDS_UNLINK_REC, obd_device::obd_name, osp_device::opd_obd, osp_device::opd_syn_barrier_waitq, osp_device::opd_syn_changes, osp_device::opd_syn_generation, osp_device::opd_syn_last_committed_id, osp_device::opd_syn_last_processed_id, osp_device::opd_syn_lock, osp_device::opd_syn_prev_done, osp_device::opd_syn_rpc_in_flight, osp_device::opd_syn_rpc_in_progress, osp_sync_new_setattr_job(), osp_sync_new_unlink64_job(), osp_sync_new_unlink_job(), PFID, llog_handle::phd, plain_handle_data::phd_cat_handle, RETURN_EXIT, llog_handle::u, and unlikely.
Referenced by osp_sync_process_queues().
static void osp_sync_remove_from_tracker (struct osp_device * d) [static]
Stop to propagate commit status to OSP.
If the OSP does not have any llog records she's waiting to commit, then it is possible to unsubscribe from wakeups from the tracking using this method.
Parameters:
[in] d OSP device not willing to wakeup
Definition at line 1655 of file osp_sync.c.
References LASSERT, list_del_init(), list_empty(), osp_device::opd_syn_ontrack, osp_device::opd_syn_tracker, and osp_id_tracker::otr_lock.
Referenced by osp_sync_id_traction_fini(), and osp_sync_process_queues().
static void osp_sync_request_commit_cb (struct ptlrpc_request * req) [static]
ptlrpc commit callback.
The callback is called by PTLRPC when a RPC is reported committed by the target (OST). We register the callback for the every RPC applying a change from the llog. This way we know then the llog records can be cancelled. Notice the callback can be called when OSP is finishing. We can detect this checking that actual transno in the request is less or equal of known committed transno (see osp_sync_process_committed() for the details). XXX: this is pretty expensive and can be improved later using batching.
Parameters:
[in] req request
Definition at line 470 of file osp_sync.c.
References CDEBUG, D_HA, osp_job_req_args::jra_committed_link, osp_job_req_args::jra_magic, LASSERT, list_add(), list_empty(), LPU64, osp_device::opd_syn_committed_there, osp_device::opd_syn_lock, osp_device::opd_syn_waitq, OSP_JOB_MAGIC, ptlrpc_req_async_args, ptlrpc_request_addref(), ptlrpc_request::rq_transno, and unlikely.
Referenced by osp_sync_new_job().
static int osp_sync_running (struct osp_device * d) [inline, static]
Definition at line 106 of file osp_sync.c.
References osp_device::opd_syn_thread, SVC_RUNNING, and ptlrpc_thread::t_flags.
Referenced by osp_sync_init(), osp_sync_process_committed(), and osp_sync_process_queues().
static void osp_sync_send_new_rpc (struct osp_device * d, struct ptlrpc_request * req) [static]
Definition at line 602 of file osp_sync.c.
References INIT_LIST_HEAD, osp_job_req_args::jra_committed_link, osp_job_req_args::jra_inflight_link, osp_job_req_args::jra_magic, LASSERT, list_add_tail(), osp_device::opd_syn_inflight_list, osp_device::opd_syn_lock, osp_device::opd_syn_max_rpc_in_flight, osp_device::opd_syn_rpc_in_flight, OSP_JOB_MAGIC, ptlrpc_req_async_args, and ptlrpcd_add_req().
Referenced by osp_sync_new_setattr_job(), osp_sync_new_unlink64_job(), and osp_sync_new_unlink_job().
static int osp_sync_stopped (struct osp_device * d) [inline, static]
Check status: whether OSP thread has stopped.
Parameters:
[in] d OSP device
Return values:
0 still running
1 stopped
Definition at line 119 of file osp_sync.c.
References osp_device::opd_syn_thread, SVC_STOPPED, and ptlrpc_thread::t_flags.
Referenced by osp_sync_init().
static int osp_sync_thread (void * _arg) [static]
OSP sync thread.
This thread runs llog_cat_process() scanner calling our callback to process llog records. in the callback we implement tricky state machine as we don't want to start scanning of the llog again and again, also we don't want to process too many records and send too many RPCs a time. so, depending on current load (num of changes being synced to OST) the callback can suspend awaiting for some new conditions, like syncs completed.
In order to process llog records left by previous boots and to allow llog_process_thread() to find something (otherwise it'd just exit immediately) we add a special GENERATATION record on each boot.
Parameters:
[in] _arg a pointer to thread's arguments
Return values:
0 on success
negative negated errno on error
Definition at line 1142 of file osp_sync.c.
References CERROR, cfs_time_seconds(), ENTRY, GOTO, l_wait_event, LASSERTF, LCT_LOCAL, list_empty(), llog_cat_close(), llog_cat_process(), llog_cleanup(), llog_ctxt_put(), llog_get_context(), LLOG_MDS_OST_ORIG_CTXT, LLOG_PROC_BREAK, llog_ctxt::loc_handle, lu_env_fini(), lu_env_init(), LWI_TIMEOUT, obd_device::obd_name, osp_device::opd_obd, osp_device::opd_syn_changes, osp_device::opd_syn_committed_there, osp_device::opd_syn_lock, osp_device::opd_syn_rpc_in_flight, osp_device::opd_syn_rpc_in_progress, osp_device::opd_syn_thread, osp_device::opd_syn_waitq, osp_sync_process_committed(), osp_sync_process_queues(), RETURN, SVC_RUNNING, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, ptlrpc_thread::t_flags, and thread.
Referenced by osp_sync_init().
static void osp_sync_tracker_commit_cb (struct thandle * th, void * cookie) [static]
OSD commit callback.
The function is used as a local OSD commit callback to track the highest committed llog record id. see osp_sync_id_traction_init() for the details.
Parameters:
[in] th local transaction handle committed
[in] cookie commit callback data (our private structure)
Definition at line 1476 of file osp_sync.c.
References CDEBUG, D_OTHER, LASSERT, likely, list_for_each_entry, osp_device::opd_syn_last_committed_id, osp_device::opd_syn_waitq, osp_txn_info(), osp_txn_info::oti_current_id, osp_id_tracker::otr_committed_id, osp_id_tracker::otr_lock, osp_id_tracker::otr_wakeup_list, and thandle::th_ctx.
Referenced by osp_sync_id_traction_init().
Variable Documentation
struct list_head osp_id_tracker_list [static]
Initial value:
                LIST_HEAD_INIT(osp_id_tracker_list)
Definition at line 1464 of file osp_sync.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.