Lustre: lustre/osp/osp_dev.c File Reference
lustre/osp/osp_dev.c File Reference
#include <linux/kthread.h>
#include <lustre_ioctl.h>
#include <lustre_log.h>
#include <lustre_obdo.h>
#include <lustre_param.h>
#include <obd_class.h>
#include "osp_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_MDS
Functions
static struct lu_object * osp_object_alloc (const struct lu_env *env, const struct lu_object_header *hdr, struct lu_device *d)
Implementation of lu_device_operations::ldo_object_alloc.
static struct dt_object * osp_find_or_create_local_file (const struct lu_env *env, struct osp_device *osp, struct lu_attr *attr, __u32 reg_id)
Find or create the local object.
static int osp_write_local_file (const struct lu_env *env, struct osp_device *osp, struct dt_object *dt_obj, struct lu_buf *buf, loff_t offset)
Write data buffer to a local file object.
static int osp_init_last_objid (const struct lu_env *env, struct osp_device *osp)
Initialize last ID object.
static int osp_init_last_seq (const struct lu_env *env, struct osp_device *osp)
Initialize last sequence object.
static int osp_last_used_init (const struct lu_env *env, struct osp_device *osp)
Initialize last OID and sequence object.
static void osp_last_used_fini (const struct lu_env *env, struct osp_device *osp)
Release the last sequence and OID file objects in OSP device.
static int osp_disconnect (struct osp_device *d)
Disconnects the connection between OSP and its correspondent MDT or OST, and the import will be marked as inactive.
static int osp_update_init (struct osp_device *osp)
Initialize the osp_update structure in OSP device.
static void osp_update_fini (const struct lu_env *env, struct osp_device *osp)
Finialize osp_update structure in OSP device.
static int osp_shutdown (const struct lu_env *env, struct osp_device *d)
Cleanup OSP, which includes disconnect import, cleanup unlink log, stop precreate threads etc.
static int osp_process_config (const struct lu_env *env, struct lu_device *dev, struct lustre_cfg *lcfg)
Implementation of osp_lu_ops::ldo_process_config.
static int osp_recovery_complete (const struct lu_env *env, struct lu_device *dev)
Implementation of osp_lu_ops::ldo_recovery_complete.
static int osp_statfs (const struct lu_env *env, struct dt_device *dev, struct obd_statfs *sfs)
Implementation of dt_device_operations::dt_statfs.
static int osp_sync_timeout (void *data)
static int osp_sync (const struct lu_env *env, struct dt_device *dev)
Implementation of dt_device_operations::dt_sync.
static int osp_connect_to_osd (const struct lu_env *env, struct osp_device *osp, const char *nextdev)
Connect OSP to local OSD.
static int osp_cancel_weight (struct ldlm_lock *lock)
Determine if the lock needs to be cancelled.
static int osp_init0 (const struct lu_env *env, struct osp_device *osp, struct lu_device_type *ldt, struct lustre_cfg *cfg)
Initialize OSP device according to the parameters in the configuration log cfg.
static struct lu_device * osp_device_free (const struct lu_env *env, struct lu_device *lu)
Implementation of lu_device_type_operations::ldto_device_free.
static struct lu_device * osp_device_alloc (const struct lu_env *env, struct lu_device_type *type, struct lustre_cfg *lcfg)
Implementation of lu_device_type_operations::ldto_device_alloc.
static struct lu_device * osp_device_fini (const struct lu_env *env, struct lu_device *ld)
Implementation of lu_device_type_operations::ldto_device_fini.
static int osp_reconnect (const struct lu_env *env, struct obd_export *exp, struct obd_device *obd, struct obd_uuid *cluuid, struct obd_connect_data *data, void *localdata)
Implementation of obd_ops::o_reconnect.
static int osp_obd_connect (const struct lu_env *env, struct obd_export **exp, struct obd_device *obd, struct obd_uuid *cluuid, struct obd_connect_data *data, void *localdata)
static int osp_obd_disconnect (struct obd_export *exp)
Implementation of obd_ops::o_disconnect.
static int osp_obd_statfs (const struct lu_env *env, struct obd_export *exp, struct obd_statfs *osfs, __u64 unused, __u32 flags)
Implementation of obd_ops::o_statfs.
static int osp_import_event (struct obd_device *obd, struct obd_import *imp, enum obd_import_event event)
Implementation of obd_ops::o_import_event.
static int osp_iocontrol (unsigned int cmd, struct obd_export *exp, int len, void *karg, void __user *uarg)
Implementation of obd_ops: o_iocontrol.
static int osp_obd_get_info (const struct lu_env *env, struct obd_export *exp, __u32 keylen, void *key, __u32 *vallen, void *val)
Implementation of obd_ops::o_get_info.
static int osp_obd_set_info_async (const struct lu_env *env, struct obd_export *exp, u32 keylen, void *key, u32 vallen, void *val, struct ptlrpc_request_set *set)
static int osp_fid_alloc (const struct lu_env *env, struct obd_export *exp, struct lu_fid *fid, struct md_op_data *unused)
Implementation of obd_ops: o_fid_alloc.
LU_KEY_INIT_FINI (osp, struct osp_thread_info)
static void osp_key_exit (const struct lu_context *ctx, struct lu_context_key *key, void *data)
LU_KEY_INIT_FINI (osp_txn, struct osp_txn_info)
LU_TYPE_INIT_FINI (osp,&osp_thread_key,&osp_txn_key)
static int __init osp_init (void)
Initialize OSP module.
static void __exit osp_exit (void)
Finalize OSP module.
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre OSD Storage Proxy ("LUSTRE_OSP_NAME")")
MODULE_VERSION (LUSTRE_VERSION_STRING)
MODULE_LICENSE ("GPL")
module_init (osp_init)
module_exit (osp_exit)
Variables
struct kmem_cache * osp_object_kmem
static struct lu_kmem_descr osp_caches []
struct lu_device_operations osp_lu_ops
struct dt_device_operations osp_dt_ops
struct lu_context_key osp_thread_key
struct lu_context_key osp_txn_key
static struct
lu_device_type_operations osp_device_type_ops
static struct lu_device_type osp_device_type
static struct obd_ops osp_obd_device_ops
struct llog_operations osp_mds_ost_orig_logops
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 75 of file osp_dev.c.
Function Documentation
LU_KEY_INIT_FINI (osp_txn , struct osp_txn_info)
LU_KEY_INIT_FINI (osp , struct osp_thread_info)
LU_TYPE_INIT_FINI (osp , & osp_thread_key, & osp_txn_key)
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre OSD Storage Proxy ("LUSTRE_OSP_NAME")")
module_exit (osp_exit)
module_init (osp_init)
MODULE_LICENSE ("GPL")
MODULE_VERSION (LUSTRE_VERSION_STRING)
static int osp_cancel_weight (struct ldlm_lock * lock) [static]
Determine if the lock needs to be cancelled.
Determine if the unused lock should be cancelled before replay, see (ldlm_cancel_no_wait_policy()). Currently, only inode bits lock exists between MDTs.
Parameters:
[in] lock lock to be checked.
Return values:
1 if the lock needs to be cancelled before replay.
0 if the lock does not need to be cancelled before replay.
Definition at line 963 of file osp_dev.c.
References ldlm_lock::l_resource, LDLM_IBITS, ldlm_resource::lr_type, and RETURN.
Referenced by osp_init0().
static int osp_connect_to_osd (const struct lu_env * env, struct osp_device * osp, const char * nextdev) [static]
Connect OSP to local OSD.
Locate the local OSD referenced by nextdev and connect to it. Sometimes, OSP needs to access the local OSD to store some information. For example, during precreate, it needs to update last used OID and sequence file (LAST_SEQ) in local OSD.
Parameters:
[in] env execution environment
[in] osp OSP device
[in] nextdev the name of local OSD
Return values:
0 0 connection succeeded
negative negative errno connection failed
Definition at line 910 of file osp_dev.c.
References CERROR, class_name2obd(), dt_device::dd_lu_dev, ENTRY, obd_export::exp_obd, GOTO, LASSERT, lu_device::ld_site, lu2dt_dev(), OBD_ALLOC_PTR, obd_connect(), OBD_FREE_PTR, obd_device::obd_lu_dev, obd_device::obd_name, obd_device::obd_uuid, osp_device::opd_dt_dev, osp_device::opd_obd, osp_device::opd_storage, osp_device::opd_storage_exp, and RETURN.
Referenced by osp_init0().
static struct lu_device* osp_device_alloc (const struct lu_env * env, struct lu_device_type * type, struct lustre_cfg * lcfg) [static, read]
Implementation of lu_device_type_operations::ldto_device_alloc.
This function allocates and initializes OSP device in memory according to the config log.
Parameters:
[in] env execution environment
[in] type device type of OSP
[in] lcfg config log
Return values:
pointer the pointer of allocated OSP if succeed.
ERR_PTR(errno) ERR_PTR(errno) if failed.
Definition at line 1283 of file osp_dev.c.
References dt_device_init(), OBD_ALLOC_PTR, osp_device::opd_dt_dev, osp2lu_dev(), osp_device_free(), and osp_init0().
static struct lu_device* osp_device_fini (const struct lu_env * env, struct lu_device * ld) [static, read]
Implementation of lu_device_type_operations::ldto_device_fini.
This function cleans up the OSP device, i.e. release and free those attached items in osp_device.
Parameters:
[in] env execution environment
[in] ld lu_device of OSP
Return values:
NULL NULL if cleanup succeeded.
ERR_PTR(errno) ERR_PTR(errno) if cleanup failed.
Definition at line 1319 of file osp_dev.c.
References client_obd::cl_import, client_obd::cl_rpc_lock, obd_device::cli, client_obd_cleanup(), ENTRY, LASSERT, lprocfs_obd_cleanup(), lprocfs_remove(), lu2osp_dev(), obd_disconnect(), OBD_FREE_PTR, osp_device::opd_async_requests, osp_device::opd_connect_mdt, osp_device::opd_obd, osp_device::opd_storage_exp, osp_device::opd_symlink, osp_update_request_destroy(), ptlrpc_lprocfs_unregister_obd(), ptlrpcd_decref(), RETURN, and obd_device::u.
static struct lu_device* osp_device_free (const struct lu_env * env, struct lu_device * lu) [static, read]
Implementation of lu_device_type_operations::ldto_device_free.
Free the OSP device in memory. No return value is needed for now, so always return NULL to comply with the interface.
Parameters:
[in] env execution environment
[in] lu lu_device of OSP
Return values:
NULL NULL unconditionally
Definition at line 1255 of file osp_dev.c.
References D_ERROR, dt_device_fini(), lu_device::ld_ref, lu_device::ld_site, LIBCFS_DEBUG_MSG_DATA_DECL, lu2osp_dev(), lu_cdebug_printer(), lu_site_print(), OBD_FREE_PTR, and osp_device::opd_dt_dev.
Referenced by osp_device_alloc().
static int osp_disconnect (struct osp_device * d) [static]
Disconnects the connection between OSP and its correspondent MDT or OST, and the import will be marked as inactive.
It will only be called during OSP cleanup process.
Parameters:
[in] d OSP device being disconnected
Return values:
0 0 if disconnection succeed
negative negative errno if disconnection failed
Definition at line 456 of file osp_dev.c.
References CERROR, client_obd::cl_import, obd_device::cli, obd_import::imp_deactive, obd_import::imp_lock, LASSERT, obd_device::obd_name, osp_device::opd_obd, ptlrpc_deactivate_import(), ptlrpc_disconnect_import(), ptlrpc_invalidate_import(), ptlrpc_pinger_del_import(), RETURN, and obd_device::u.
Referenced by osp_process_config(), and osp_shutdown().
static void __exit osp_exit (void) [static]
Finalize OSP module.
This callback is called when kernel unloads OSP module from memory, and it will deregister OSP and LWP device type from obd_types (
See also:
class_obd.c).
Definition at line 1966 of file osp_dev.c.
References class_unregister_type(), lu_kmem_fini(), LUSTRE_LWP_NAME, and LUSTRE_OSP_NAME.
static int osp_fid_alloc (const struct lu_env * env, struct obd_export * exp, struct lu_fid * fid, struct md_op_data * unused) [static]
Implementation of obd_ops: o_fid_alloc.
Allocate a FID. There are two cases in which OSP performs FID allocation.
1. FID precreation for data objects, which is done in osp_precreate_fids() instead of this function. 2. FID allocation for each sub-stripe of a striped directory. Similar to other FID clients, OSP requests the sequence from its corresponding remote MDT, which in turn requests sequences from the sequence controller (MDT0).
Parameters:
[in] env execution environment
[in] exp export of the OSP
[out] fid FID being allocated
[in] unused necessary for the interface but unused.
Return values:
0 0 FID allocated successfully.
1 1 FID allocated successfully and new sequence requested from seq meta server
negative negative errno if FID allocation failed.
Definition at line 1821 of file osp_dev.c.
References client_obd::cl_seq, obd_device::cli, ENTRY, obd_export::exp_obd, LASSERT, lu_client_seq::lcs_exp, lu2osp_dev(), obd_device::obd_lu_dev, osp_device::opd_obd, RETURN, seq_client_alloc_fid(), and obd_device::u.
static struct dt_object* osp_find_or_create_local_file (const struct lu_env * env, struct osp_device * osp, struct lu_attr * attr, __u32 reg_id) [static, read]
Find or create the local object.
Finds or creates the local file referenced by reg_id and return the attributes of the local file.
Parameters:
[in] env execution environment
[in] osp OSP device
[out] attr attributes of the object
[in] reg_id the local object ID of the file. It will be used to compose a local FID{FID_SEQ_LOCAL_FILE, reg_id, 0} to identify the object.
Return values:
object object(dt_object) found or created
ERR_PTR(errno) ERR_PTR(errno) if not get the object.
Definition at line 166 of file osp_dev.c.
References CERROR, DFT_REGULAR, dt_object::do_lu, dt_object_format::dof_type, dt_attr_get(), dt_find_or_create(), ENTRY, lu_attr::la_mode, LA_MODE, lu_attr::la_valid, lu_local_obj_fid(), lu_object_put(), obd_device::obd_name, osp_device::opd_obd, osp_device::opd_storage, osp_thread_info::osi_fid, osp_env_info(), and RETURN.
Referenced by osp_init_last_objid(), and osp_init_last_seq().
static int osp_import_event (struct obd_device * obd, struct obd_import * imp, enum obd_import_event event) [static]
Implementation of obd_ops::o_import_event.
This function is called when some related import event happens. It will mark the necessary flags according to the event and notify the necessary threads (mainly precreate thread).
Parameters:
[in] obd OSP OBD device
[in] imp import attached from OSP to remote (OST/MDT) service
[in] event event related to remote service (IMP_EVENT_*)
Return values:
0 0 if the event handling succeeded.
negative negative errno if the event handling failed.
Definition at line 1574 of file osp_dev.c.
References __osp_sync_check_for_work(), CDEBUG, CERROR, D_HA, IMP_EVENT_ACTIVATE, IMP_EVENT_ACTIVE, IMP_EVENT_DEACTIVATE, IMP_EVENT_DISCON, IMP_EVENT_INACTIVE, IMP_EVENT_INVALIDATE, IMP_EVENT_OCD, LDLM_FL_LOCAL_ONLY, ldlm_namespace_cleanup(), lu2osp_dev(), obd_device::obd_inactive, obd_device::obd_lu_dev, obd_device::obd_name, obd_device::obd_namespace, osp_device::opd_connect_mdt, osp_device::opd_got_disconnected, osp_device::opd_imp_active, osp_device::opd_imp_connected, osp_device::opd_imp_seen_connected, osp_device::opd_new_connection, osp_device::opd_obd, osp_device::opd_pre, osp_device::opd_pre_waitq, osp_invalidate_request(), and osp_pre_update_status().
static int __init osp_init (void) [static]
Initialize OSP module.
Register device types OSP and Light Weight Proxy (LWP) (
See also:
lwp_dev.c) in obd_types (
class_obd.c). Initialize procfs for the the OSP device. Note: OSP was called OSC before Lustre 2.4, so for compatibility it still uses the name "osc" in procfs. This is called at module load time.
Return values:
0 0 if initialization succeeds.
negative negative errno if initialization failed.
Definition at line 1914 of file osp_dev.c.
References CERROR, class_register_type(), class_search_type(), class_unregister_type(), llog_cat_add_rec(), llog_cat_declare_add_rec(), llog_osd_ops, llog_operations::lop_add, llog_operations::lop_declare_add, lprocfs_register(), lu_kmem_fini(), lu_kmem_init(), LUSTRE_LWP_NAME, LUSTRE_OSC_NAME, LUSTRE_OSP_NAME, lwp_device_type, lwp_obd_device_ops, osp_mds_ost_orig_logops, proc_lustre_root, obd_type::typ_procroot, and obd_type::typ_procsym.
static int osp_init0 (const struct lu_env * env, struct osp_device * osp, struct lu_device_type * ldt, struct lustre_cfg * cfg) [static]
Initialize OSP device according to the parameters in the configuration log cfg.
Reconstruct the local device name from the configuration profile, and initialize necessary threads and structures according to the OSP type (MDT or OST).
Since there is no record in the MDT configuration for the local disk device, we have to extract this from elsewhere in the profile. The only information we get at setup is from the OSC records: setup 0:{fsname}-OSTxxxx-osc[-MDTxxxx] 1:lustre-OST0000_UUID 2:NID
Note: configs generated by Lustre 1.8 are missing the -MDTxxxx part, so, we need to reconstruct the name of the underlying OSD from this: {fsname}-{svname}-osd, for example "lustre-MDT0000-osd".
Parameters:
[in] env execution environment
[in] osp OSP device
[in] ldt lu device type of OSP
[in] cfg configuration log
Return values:
0 0 if OSP initialization succeeded.
negative negative errno if OSP initialization failed.
Definition at line 996 of file osp_dev.c.
References CDEBUG, CERROR, client_obd::cl_import, client_obd::cl_rpc_lock, class_name2obd(), class_uuid_unparse(), obd_device::cli, client_obd_cleanup(), client_obd_setup(), D_HA, dt_device::dd_lu_dev, dt_device::dd_ops, ENTRY, GOTO, INIT_LIST_HEAD, lu_device::ld_ops, ll_generate_random_uuid, lprocfs_obd_cleanup(), lprocfs_remove(), lustre_cfg_string(), LUSTRE_SEQ_DATA, LUSTRE_SEQ_METADATA, MAX_OBD_NAME, MTI_NAME_MAXLEN, ns_register_cancel(), OBD_ALLOC, obd_disconnect(), obd_fid_fini(), obd_fid_init(), OBD_FREE, OBD_FREE_PTR, obd_device::obd_lu_dev, obd_device::obd_name, obd_device::obd_namespace, osp_device::opd_async_requests_mutex, osp_device::opd_async_updates, osp_device::opd_async_updates_count, osp_device::opd_async_updates_rwsem, osp_device::opd_cluuid, osp_device::opd_connect_mdt, osp_device::opd_dt_dev, osp_device::opd_group, osp_device::opd_index, osp_device::opd_obd, osp_device::opd_storage_exp, osp_device::opd_symlink, osp_cancel_weight(), osp_connect_to_osd(), osp_init_precreate(), osp_init_rpc_lock, osp_last_used_fini(), osp_last_used_init(), osp_lprocfs_init(), osp_precreate_fini(), osp_sync_fini(), osp_sync_init(), osp_update_fini(), osp_update_init(), ptlrpc_init_import(), ptlrpc_lprocfs_unregister_obd(), ptlrpcd_addref(), ptlrpcd_decref(), RETURN, obd_device::u, and uuid.
Referenced by osp_device_alloc().
static int osp_init_last_objid (const struct lu_env * env, struct osp_device * osp) [static]
Initialize last ID object.
This function initializes the LAST_ID file, which stores the current last used id of data objects. The MDT will use the last used id and the last_seq (
See also:
osp_init_last_seq()) to synchronize the precreate object cache with OSTs.
Parameters:
[in] env execution environment
[in] osp OSP device
Return values:
0 0 if initialization succeed
negative negative errno if initialization failed
Definition at line 249 of file osp_dev.c.
References CERROR, dt_object::do_lu, dt_record_read(), ENTRY, lu_fid::f_oid, GOTO, lu_attr::la_size, lu_object_put(), MDD_LOV_OBJ_OID, obd_device::obd_name, osp_device::opd_index, osp_device::opd_last_used_fid, osp_device::opd_last_used_oid_file, osp_device::opd_obd, osp_thread_info::osi_attr, osp_thread_info::osi_id, osp_thread_info::osi_lb, osp_thread_info::osi_off, osp_env_info(), osp_find_or_create_local_file(), osp_objid_buf_prep(), osp_write_local_file(), and RETURN.
Referenced by osp_last_used_init().
static int osp_init_last_seq (const struct lu_env * env, struct osp_device * osp) [static]
Initialize last sequence object.
This function initializes the LAST_SEQ file in the local OSD, which stores the current last used sequence of data objects. The MDT will use the last sequence and last id (
See also:
osp_init_last_objid()) to synchronize the precreate object cache with OSTs.
Parameters:
[in] env execution environment
[in] osp OSP device
Return values:
0 0 if initialization succeed
negative negative errno if initialization failed
Definition at line 306 of file osp_dev.c.
References CERROR, dt_object::do_lu, dt_record_read(), ENTRY, lu_fid::f_seq, GOTO, lu_attr::la_size, lu_object_put(), MDD_LOV_OBJ_OSEQ, obd_device::obd_name, osp_device::opd_index, osp_device::opd_last_used_fid, osp_device::opd_last_used_seq_file, osp_device::opd_obd, osp_thread_info::osi_attr, osp_thread_info::osi_id, osp_thread_info::osi_lb, osp_thread_info::osi_off, osp_env_info(), osp_find_or_create_local_file(), osp_objseq_buf_prep(), osp_write_local_file(), and RETURN.
Referenced by osp_last_used_init().
static int osp_iocontrol (unsigned int cmd, struct obd_export * exp, int len, void * karg, void __user * uarg) [static]
Implementation of obd_ops: o_iocontrol.
This function is the ioctl handler for OSP. Note: lctl will access the OSP directly by ioctl, instead of through the MDS stack.
param[in] cmd ioctl command. param[in] exp export of this OSP. param[in] len data length of karg. param[in] karg input argument which is packed as obd_ioctl_data param[out] uarg pointer to userspace buffer (must access by copy_to_user()).
Return values:
0 0 if the ioctl handling succeeded.
negative negative errno if the ioctl handling failed.
Definition at line 1660 of file osp_dev.c.
References CERROR, client_obd::cl_import, obd_device::cli, current_comm, dt_device::dd_ops, ENTRY, obd_export::exp_obd, obd_ioctl_data::ioc_inlbuf1, obd_ioctl_data::ioc_offset, IOC_OSC_SET_ACTIVE, LASSERT, lu2osp_dev(), OBD_IOC_CLIENT_RECOVER, OBD_IOC_PING_TARGET, obd_device::obd_lu_dev, obd_device::obd_name, osp_device::opd_dt_dev, ptlrpc_obd_ping(), ptlrpc_recover_import(), ptlrpc_set_import_active(), and obd_device::u.
static void osp_key_exit (const struct lu_context * ctx, struct lu_context_key * key, void * data) [static]
Definition at line 1838 of file osp_dev.c.
References lu_attr::la_valid, and osp_thread_info::osi_attr.
static void osp_last_used_fini (const struct lu_env * env, struct osp_device * osp) [static]
Release the last sequence and OID file objects in OSP device.
Parameters:
[in] env execution environment
[in] osp OSP device
Definition at line 432 of file osp_dev.c.
References dt_object::do_lu, lu_object_put(), osp_device::opd_last_used_oid_file, and osp_device::opd_last_used_seq_file.
Referenced by osp_init0(), and osp_shutdown().
static int osp_last_used_init (const struct lu_env * env, struct osp_device * osp) [static]
Initialize last OID and sequence object.
If the MDT is just upgraded to 2.4 from the lower version, where the LAST_SEQ file does not exist, the file will be created and IDIF sequence will be written into the file.
Parameters:
[in] env execution environment
[in] osp OSP device
Return values:
0 0 if initialization succeed
negative negative error if initialization failed
Definition at line 362 of file osp_dev.c.
References CDEBUG, CERROR, D_INFO, DFID, dt_object::do_lu, ENTRY, lu_fid::f_seq, fid_idif_seq(), fid_is_sane(), fid_is_zero(), fid_oid(), fid_zero(), GOTO, lu_object_put(), obd_device::obd_name, osp_device::opd_index, osp_device::opd_last_used_fid, osp_device::opd_last_used_oid_file, osp_device::opd_last_used_seq_file, osp_device::opd_obd, osp_thread_info::osi_lb, osp_thread_info::osi_off, osp_env_info(), osp_init_last_objid(), osp_init_last_seq(), osp_objseq_buf_prep(), osp_write_local_file(), PFID, and RETURN.
Referenced by osp_init0().
static int osp_obd_connect (const struct lu_env * env, struct obd_export ** exp, struct obd_device * obd, struct obd_uuid * cluuid, struct obd_connect_data * data, void * localdata) [static]
Definition at line 1398 of file osp_dev.c.
References CDEBUG, CERROR, client_obd::cl_import, client_obd::cl_seq, class_conn2export(), class_connect(), class_export_get(), obd_device::cli, D_CONFIG, ENTRY, GOTO, obd_import::imp_connect_data, obd_import::imp_connect_flags_orig, obd_import::imp_dlm_handle, LASSERT, lu_client_seq::lcs_exp, lu2osp_dev(), LUSTRE_VERSION_CODE, OBD_CONNECT_INDEX, obd_device::obd_lu_dev, obd_device::obd_name, obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_index, obd_connect_data::ocd_version, osp_device::opd_connects, osp_device::opd_exp, osp_device::opd_obd, ptlrpc_connect_import(), ptlrpc_pinger_add_import(), RETURN, and obd_device::u.
static int osp_obd_disconnect (struct obd_export * exp) [static]
Implementation of obd_ops::o_disconnect.
Disconnect the export for the OSP. This is called by LOD to release the OSP during cleanup (
See also:
lod_del_device()). The OSP will be released after the export is released.
Parameters:
[in] exp export to be disconnected.
Return values:
0 0 if disconnection succeed
negative negative errno if disconnection failed
Definition at line 1463 of file osp_dev.c.
References CERROR, class_disconnect(), class_manual_cleanup(), ENTRY, obd_export::exp_obd, LASSERT, lu2osp_dev(), obd_device::obd_lu_dev, obd_device::obd_name, osp_device::opd_connects, and RETURN.
static int osp_obd_get_info (const struct lu_env * env, struct obd_export * exp, __u32 keylen, void * key, __u32 * vallen, void * val) [static]
Implementation of obd_ops::o_get_info.
Retrieve information by key. Retrieval starts from the top layer (MDT) of the MDS stack and traverses the stack by calling the obd_get_info() method of the next sub-layer.
Parameters:
[in] env execution environment
[in] exp export of this OSP
[in] keylen length of key
[in] key the key
[out] vallen length of val
[out] val holds the value returned by the key
Return values:
0 0 if getting information succeeded.
negative negative errno if getting information failed.
Definition at line 1721 of file osp_dev.c.
References obd_export::exp_obd, KEY_IS, KEY_OSP_CONNECTED, LASSERT, lu2osp_dev(), obd_device::obd_lu_dev, obd_device::obd_set_up, obd_device::obd_stopping, osp_device::opd_imp_seen_connected, and RETURN.
static int osp_obd_set_info_async (const struct lu_env * env, struct obd_export * exp, u32 keylen, void * key, u32 vallen, void * val, struct ptlrpc_request_set * set) [static]
Definition at line 1746 of file osp_dev.c.
References client_obd::cl_import, obd_device::cli, obd_export::exp_obd, KEY_IS, KEY_SPTLRPC_CONF, LASSERT, lu2osp_dev(), LUSTRE_MDS_VERSION, LUSTRE_OST_VERSION, MDS_SET_INFO, obd_device::obd_lu_dev, obd_device::obd_set_up, obd_device::obd_stopping, osp_device::opd_connect_mdt, OST_SET_INFO, ptlrpc_check_set(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), ptlrpc_set_add_req(), RCL_CLIENT, req_capsule_client_get(), req_capsule_set_size(), RETURN, RMF_SETINFO_KEY, RMF_SETINFO_VAL, ptlrpc_request::rq_pill, RQF_OBD_SET_INFO, sptlrpc_conf_client_adapt(), and obd_device::u.
static int osp_obd_statfs (const struct lu_env * env, struct obd_export * exp, struct obd_statfs * osfs, __u64 unused, __u32 flags) [static]
Implementation of obd_ops::o_statfs.
Send a RPC to the remote target to get statfs status. This is only used in lprocfs helpers by obd_statfs.
Parameters:
[in] env execution environment
[in] exp connection state from this OSP to the parent (LOD) device
[out] osfs hold the statfs result
[in] unused Not used in this function for now
[in] flags flags to indicate how OSP will issue the RPC
Return values:
0 0 if statfs succeeded.
negative negative errno if statfs failed.
Definition at line 1503 of file osp_dev.c.
References client_obd::cl_import, client_obd::cl_sem, class_import_get(), class_import_put(), obd_device::cli, ENTRY, EXIT, obd_export::exp_obd, GOTO, LUSTRE_OST_VERSION, OBD_STATFS_NODELAY, OST_CREATE_PORTAL, OST_STATFS, ptlrpc_at_set_req_timeout(), ptlrpc_queue_wait(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), req_capsule_server_get(), RETURN, RMF_OBD_STATFS, ptlrpc_request::rq_no_delay, ptlrpc_request::rq_no_resend, ptlrpc_request::rq_pill, RQF_OST_STATFS, and obd_device::u.
static struct lu_object* osp_object_alloc (const struct lu_env * env, const struct lu_object_header * hdr, struct lu_device * d) [static, read]
Implementation of lu_device_operations::ldo_object_alloc.
Allocates an OSP object in memory, whose FID is on the remote target.
Parameters:
[in] env execution environment
[in] hdr The header of the object stack. If it is NULL, it means the object is not built from top device, i.e. it is a sub-stripe object of striped directory or an OST object.
[in] d OSP device
Return values:
object object being created if the creation succeed.
NULL NULL if the creation failed.
Definition at line 116 of file osp_dev.c.
References dt_object::do_lu, dt_object_init(), lu_object::lo_ops, lu_object_add_top(), lu_object_header_init(), OBD_SLAB_ALLOC_PTR_GFP, osp_object::opo_header, osp_object::opo_obj, osp_lu_obj_ops, and osp_object_kmem.
static int osp_process_config (const struct lu_env * env, struct lu_device * dev, struct lustre_cfg * lcfg) [static]
Implementation of osp_lu_ops::ldo_process_config.
This function processes config log records in OSP layer. It is usually called from the top layer of MDT stack, and goes through the stack by calling ldo_process_config of next layer.
Parameters:
[in] env execution environment
[in] dev lu_device of OSP
[in] lcfg config log
Return values:
0 0 if the config log record is executed correctly.
negative negative errno if the record execution fails.
Definition at line 626 of file osp_dev.c.
References CERROR, class_process_proc_param(), ENTRY, LASSERT, LCFG_CLEANUP, lustre_cfg::lcfg_command, LCFG_PARAM, LCFG_PRE_CLEANUP, lu_device::ld_site, lu2osp_dev(), lu_dev_del_linkage(), lustre_cfg_string(), obd_device::obd_vars, osp_device::opd_connect_mdt, osp_device::opd_obd, osp_disconnect(), osp_shutdown(), osp_update_fini(), PARAM_OSC, PARAM_OSP, and RETURN.
static int osp_reconnect (const struct lu_env * env, struct obd_export * exp, struct obd_device * obd, struct obd_uuid * cluuid, struct obd_connect_data * data, void * localdata) [static]
Implementation of obd_ops::o_reconnect.
This function is empty and does not need to do anything for now.
Definition at line 1369 of file osp_dev.c.
static int osp_recovery_complete (const struct lu_env * env, struct lu_device * dev) [static]
Implementation of osp_lu_ops::ldo_recovery_complete.
This function is called after recovery is finished, and OSP layer will wake up precreate thread here.
Parameters:
[in] env execution environment
[in] dev lu_device of OSP
Return values:
0 0 unconditionally
Definition at line 683 of file osp_dev.c.
References ENTRY, lu2osp_dev(), osp_device::opd_connect_mdt, osp_device::opd_pre, osp_device::opd_pre_waitq, osp_device::opd_recovery_completed, and RETURN.
static int osp_shutdown (const struct lu_env * env, struct osp_device * d) [static]
Cleanup OSP, which includes disconnect import, cleanup unlink log, stop precreate threads etc.
Parameters:
[in] env execution environment.
[in] d OSP device being disconnected.
Return values:
0 0 if cleanup succeed
negative negative errno if cleanup failed
Definition at line 587 of file osp_dev.c.
References ENTRY, LASSERT, obd_fid_fini(), osp_device::opd_connect_mdt, osp_device::opd_obd, osp_disconnect(), osp_last_used_fini(), osp_precreate_fini(), osp_sync_fini(), and RETURN.
Referenced by osp_process_config().
static int osp_statfs (const struct lu_env * env, struct dt_device * dev, struct obd_statfs * sfs) [static]
Implementation of dt_device_operations::dt_statfs.
This function provides statfs status (for precreation) from corresponding OST. Note: this function only retrieves the status from the OSP device, and the real statfs RPC happens inside precreate thread (
See also:
osp_statfs_update). Note: OSP for MDT does not need to retrieve statfs data for now.
Parameters:
[in] env execution environment.
[in] dev dt_device of OSP.
[out] sfs holds the retrieved statfs data.
Return values:
0 0 statfs data was retrieved successfully or retrieval was not needed
negative negative errno if get statfs failed.
Definition at line 720 of file osp_dev.c.
References CDEBUG, client_obd::cl_import, obd_device::cli, D_OTHER, DFID, dt2osp_dev(), ENTRY, fid_oid(), obd_import::imp_state, LASSERT, LASSERTF, LPU64, LUSTRE_IMP_CLOSED, obd_device::obd_name, osp_device::opd_imp_active, osp_device::opd_obd, osp_device::opd_pre, osp_device::opd_statfs, obd_statfs::os_bavail, obd_statfs::os_bfree, obd_statfs::os_blocks, obd_statfs::os_ffree, obd_statfs::os_files, obd_statfs::os_fprecreated, OST_MAX_PRECREATE, PFID, RETURN, obd_device::u, and unlikely.
static int osp_sync (const struct lu_env * env, struct dt_device * dev) [static]
Implementation of dt_device_operations::dt_sync.
This function synchronizes the OSP cache to the remote target. It wakes up unlink log threads and sends out unlink records to the remote OST.
Parameters:
[in] env execution environment
[in] dev dt_device of OSP
Return values:
0 0 if synchronization succeeds
negative negative errno if synchronization fails
Definition at line 781 of file osp_dev.c.
References __osp_sync_check_for_work(), CDEBUG, cfs_time_current(), cfs_time_shift(), D_CACHE, D_OTHER, dt2osp_dev(), ENTRY, GOTO, l_wait_event, LWI_TIMEOUT, obd_device::obd_name, obd_timeout, osp_device::opd_async_updates_count, osp_device::opd_async_updates_rwsem, osp_device::opd_connect_mdt, osp_device::opd_imp_active, osp_device::opd_obd, osp_device::opd_syn_barrier, osp_device::opd_syn_barrier_waitq, osp_device::opd_syn_last_processed_id, osp_device::opd_syn_last_used_id, osp_device::opd_syn_rpc_in_flight, osp_sync_timeout(), RETURN, start, and unlikely.
static int osp_sync_timeout (void * data) [static]
Definition at line 764 of file osp_dev.c.
Referenced by osp_sync().
static void osp_update_fini (const struct lu_env * env, struct osp_device * osp) [static]
Finialize osp_update structure in OSP device.
Stop the OSP update sending thread, then delete the left osp thandle in the sending list.
Parameters:
[in] osp OSP device.
Definition at line 546 of file osp_dev.c.
References LASSERT, list_del_init(), list_for_each_entry_safe, OBD_FREE_PTR, osp_device::opd_update, osp_device::opd_update_thread, osp_thandle_put(), osp_trans_callback(), osp_updates::ou_list, osp_updates::ou_lock, osp_updates::ou_waitq, osp_update_request::our_list, osp_update_request::our_th, SVC_STOPPED, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, and ptlrpc_thread::t_flags.
Referenced by osp_init0(), and osp_process_config().
static int osp_update_init (struct osp_device * osp) [static]
Initialize the osp_update structure in OSP device.
Allocate osp update structure and start update thread.
Parameters:
[in] osp OSP device
Return values:
0 if initialization succeeds.
negative errno if initialization fails.
Definition at line 498 of file osp_dev.c.
References CERROR, ENTRY, INIT_LIST_HEAD, l_wait_event, LASSERT, OBD_ALLOC_PTR, OBD_FREE_PTR, obd_device::obd_name, osp_device::opd_connect_mdt, osp_device::opd_group, osp_device::opd_index, osp_device::opd_obd, osp_device::opd_update, osp_device::opd_update_thread, osp_send_update_thread(), osp_send_update_thread_running(), osp_send_update_thread_stopped(), osp_updates::ou_list, osp_updates::ou_lock, osp_updates::ou_rpc_version, osp_updates::ou_version, osp_updates::ou_waitq, RETURN, and ptlrpc_thread::t_ctl_waitq.
Referenced by osp_init0().
static int osp_write_local_file (const struct lu_env * env, struct osp_device * osp, struct dt_object * dt_obj, struct lu_buf * buf, loff_t offset) [static]
Write data buffer to a local file object.
Parameters:
[in] env execution environment
[in] osp OSP device
[in] dt_obj object written to
[in] buf buffer containing byte array and length
[in] offset write offset in the object in bytes
Return values:
0 0 if write succeed
-EFAULT -EFAULT if only part of buffer is written.
negative other negative errno if write failed.
Definition at line 209 of file osp_dev.c.
References dt_declare_record_write(), dt_record_write(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), GOTO, osp_device::opd_storage, and RETURN.
Referenced by osp_init_last_objid(), osp_init_last_seq(), and osp_last_used_init().
Variable Documentation
struct lu_kmem_descr osp_caches[] [static]
Initial value:
 {
        {
                .ckd_cache = &osp_object_kmem,
                .ckd_name  = "osp_obj",
                .ckd_size  = sizeof(struct osp_object)
        },
        {
                .ckd_cache = NULL
        }
}
Definition at line 90 of file osp_dev.c.
struct lu_device_type osp_device_type [static]
Initial value:
 {
        .ldt_tags     = LU_DEVICE_DT,
        .ldt_name     = LUSTRE_OSP_NAME,
        .ldt_ops      = &osp_device_type_ops,
        .ldt_ctx_tags = LCT_MD_THREAD | LCT_DT_THREAD,
}
Definition at line 1876 of file osp_dev.c.
struct lu_device_type_operations osp_device_type_ops [static]
Initial value:
 {
        .ldto_init           = osp_type_init,
        .ldto_fini           = osp_type_fini,
        .ldto_start          = osp_type_start,
        .ldto_stop           = osp_type_stop,
        .ldto_device_alloc   = osp_device_alloc,
        .ldto_device_free    = osp_device_free,
        .ldto_device_fini    = osp_device_fini
}
Definition at line 1863 of file osp_dev.c.
struct dt_device_operations osp_dt_ops
Initial value:
 {
        .dt_statfs       = osp_statfs,
        .dt_sync         = osp_sync,
        .dt_trans_create = osp_trans_create,
        .dt_trans_start  = osp_trans_start,
        .dt_trans_stop   = osp_trans_stop,
        .dt_trans_cb_add   = osp_trans_cb_add,
}
Definition at line 886 of file osp_dev.c.
struct lu_device_operations osp_lu_ops
Initial value:
 {
        .ldo_object_alloc       = osp_object_alloc,
        .ldo_process_config     = osp_process_config,
        .ldo_recovery_complete  = osp_recovery_complete,
}
Definition at line 697 of file osp_dev.c.
Referenced by lu_device_is_osp().
struct llog_operations osp_mds_ost_orig_logops
Definition at line 1900 of file osp_dev.c.
Referenced by osp_init(), and osp_sync_llog_init().
struct obd_ops osp_obd_device_ops [static]
Initial value:
 {
        .o_owner        = THIS_MODULE,
        .o_add_conn     = client_import_add_conn,
        .o_del_conn     = client_import_del_conn,
        .o_reconnect    = osp_reconnect,
        .o_connect      = osp_obd_connect,
        .o_disconnect   = osp_obd_disconnect,
        .o_get_info     = osp_obd_get_info,
        .o_set_info_async = osp_obd_set_info_async,
        .o_import_event = osp_import_event,
        .o_iocontrol    = osp_iocontrol,
        .o_statfs       = osp_obd_statfs,
        .o_fid_init     = client_fid_init,
        .o_fid_fini     = client_fid_fini,
        .o_fid_alloc    = osp_fid_alloc,
}
Definition at line 1883 of file osp_dev.c.
struct kmem_cache* osp_object_kmem
Definition at line 88 of file osp_dev.c.
Referenced by osp_object_alloc(), and osp_object_free().
struct lu_context_key osp_thread_key
Initial value:
 {
        .lct_tags = LCT_MD_THREAD,
        .lct_init = osp_key_init,
        .lct_fini = osp_key_fini,
        .lct_exit = osp_key_exit
}
Definition at line 1846 of file osp_dev.c.
Referenced by osp_env_info().
struct lu_context_key osp_txn_key
Initial value:
 {
        .lct_tags = LCT_OSP_THREAD | LCT_TX_HANDLE,
        .lct_init = osp_txn_key_init,
        .lct_fini = osp_txn_key_fini
}
Definition at line 1856 of file osp_dev.c.
Referenced by osp_txn_info().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.