Lustre: lustre/osp/osp_object.c File Reference
lustre/osp/osp_object.c File Reference
#include <lustre_obdo.h>
#include <lustre_swab.h>
#include "osp_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_MDS
Functions
static __u32 osp_dev2node (struct osp_device *osp)
static bool is_ost_obj (struct lu_object *lo)
static void osp_object_assign_fid (const struct lu_env *env, struct osp_device *d, struct osp_object *o)
Assign FID to the OST object.
int osp_oac_init (struct osp_object *obj)
Initialize the OSP object attributes cache.
static struct osp_xattr_entry * osp_oac_xattr_find_locked (struct osp_object_attr *ooa, const char *name, size_t namelen)
Find the named extended attribute in the OSP object attributes cache.
static struct osp_xattr_entry * osp_oac_xattr_find (struct osp_object *obj, const char *name, bool unlink)
Find the named extended attribute in the OSP object attributes cache.
static struct osp_xattr_entry * osp_oac_xattr_find_or_add (struct osp_object *obj, const char *name, size_t len)
Find the named extended attribute in the OSP object attributes cache.
static struct osp_xattr_entry * osp_oac_xattr_replace (struct osp_object *obj, struct osp_xattr_entry **poxe, size_t len)
Add the given extended attribute to the OSP object attributes cache.
static void osp_oac_xattr_put (struct osp_xattr_entry *oxe)
Release reference from the OSP object extended attribute entry.
static int osp_get_attr_from_reply (const struct lu_env *env, struct object_update_reply *reply, struct ptlrpc_request *req, struct lu_attr *attr, struct osp_object *obj, int index)
Parse the OSP object attribute from the RPC reply.
static int osp_attr_get_interpterer (const struct lu_env *env, struct object_update_reply *reply, struct ptlrpc_request *req, struct osp_object *obj, void *data, int index, int rc)
Interpreter function for getting OSP object attribute asynchronously.
static int osp_declare_attr_get (const struct lu_env *env, struct dt_object *dt)
Implement OSP layer dt_object_operations::do_declare_attr_get() interface.
int osp_attr_get (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr)
Implement OSP layer dt_object_operations::do_attr_get() interface.
static int osp_declare_attr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_attr *attr, struct thandle *th)
Implement OSP layer dt_object_operations::do_declare_attr_set() interface.
static int osp_attr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_attr *attr, struct thandle *th)
Implement OSP layer dt_object_operations::do_attr_set() interface.
static int osp_xattr_get_interpterer (const struct lu_env *env, struct object_update_reply *reply, struct ptlrpc_request *req, struct osp_object *obj, void *data, int index, int rc)
Interpreter function for getting OSP object extended attribute asynchronously.
static int osp_declare_xattr_get (const struct lu_env *env, struct dt_object *dt, struct lu_buf *buf, const char *name)
Implement OSP dt_object_operations::do_declare_xattr_get() interface.
int osp_xattr_get (const struct lu_env *env, struct dt_object *dt, struct lu_buf *buf, const char *name)
Implement OSP layer dt_object_operations::do_xattr_get() interface.
int osp_declare_xattr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, const char *name, int flag, struct thandle *th)
Implement OSP layer dt_object_operations::do_declare_xattr_set() interface.
int osp_xattr_set (const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, const char *name, int fl, struct thandle *th)
Implement OSP layer dt_object_operations::do_xattr_set() interface.
int osp_declare_xattr_del (const struct lu_env *env, struct dt_object *dt, const char *name, struct thandle *th)
Implement OSP layer dt_object_operations::do_declare_xattr_del() interface.
int osp_xattr_del (const struct lu_env *env, struct dt_object *dt, const char *name, struct thandle *th)
Implement OSP layer dt_object_operations::do_xattr_del() interface.
static int osp_declare_object_create (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *th)
Implement OSP layer dt_object_operations::do_declare_create() interface.
static int osp_object_create (const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *th)
Implement OSP layer dt_object_operations::do_create() interface.
int osp_declare_object_destroy (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Implement OSP layer dt_object_operations::do_declare_destroy() interface.
static int osp_object_destroy (const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Implement OSP layer dt_object_operations::do_destroy() interface.
static int osp_orphan_index_lookup (const struct lu_env *env, struct dt_object *dt, struct dt_rec *rec, const struct dt_key *key)
static int osp_orphan_index_declare_insert (const struct lu_env *env, struct dt_object *dt, const struct dt_rec *rec, const struct dt_key *key, struct thandle *handle)
static int osp_orphan_index_insert (const struct lu_env *env, struct dt_object *dt, const struct dt_rec *rec, const struct dt_key *key, struct thandle *handle, int ignore_quota)
static int osp_orphan_index_declare_delete (const struct lu_env *env, struct dt_object *dt, const struct dt_key *key, struct thandle *handle)
static int osp_orphan_index_delete (const struct lu_env *env, struct dt_object *dt, const struct dt_key *key, struct thandle *handle)
struct dt_it * osp_it_init (const struct lu_env *env, struct dt_object *dt, __u32 attr)
Initialize the OSP layer index iteration.
void osp_it_fini (const struct lu_env *env, struct dt_it *di)
Finalize the OSP layer index iteration.
static int osp_it_fetch (const struct lu_env *env, struct osp_it *it)
Get more records for the iteration from peer.
int osp_it_next_page (const struct lu_env *env, struct dt_it *di)
Move the iteration cursor to the next lu_page.
static int osp_orphan_it_next (const struct lu_env *env, struct dt_it *di)
Move the iteration cursor to the next record.
int osp_it_get (const struct lu_env *env, struct dt_it *di, const struct dt_key *key)
void osp_it_put (const struct lu_env *env, struct dt_it *di)
static struct dt_key * osp_orphan_it_key (const struct lu_env *env, const struct dt_it *di)
static int osp_orphan_it_key_size (const struct lu_env *env, const struct dt_it *di)
static int osp_orphan_it_rec (const struct lu_env *env, const struct dt_it *di, struct dt_rec *rec, __u32 attr)
__u64 osp_it_store (const struct lu_env *env, const struct dt_it *di)
int osp_orphan_it_load (const struct lu_env *env, const struct dt_it *di, __u64 hash)
Locate the iteration cursor to the specified position (cookie).
int osp_it_key_rec (const struct lu_env *env, const struct dt_it *di, void *key_rec)
static int osp_index_try (const struct lu_env *env, struct dt_object *dt, const struct dt_index_features *feat)
Implement OSP layer dt_object_operations::do_index_try() interface.
static int osp_object_init (const struct lu_env *env, struct lu_object *o, const struct lu_object_conf *conf)
Implement OSP layer lu_object_operations::loo_object_init() interface.
static void osp_object_free (const struct lu_env *env, struct lu_object *o)
Implement OSP layer lu_object_operations::loo_object_free() interface.
static void osp_object_release (const struct lu_env *env, struct lu_object *o)
Implement OSP layer lu_object_operations::loo_object_release() interface.
static int osp_object_print (const struct lu_env *env, void *cookie, lu_printer_t p, const struct lu_object *l)
static int osp_object_invariant (const struct lu_object *o)
Variables
static struct dt_index_operations osp_orphan_index_ops
static struct dt_object_operations osp_obj_ops
struct lu_object_operations osp_lu_obj_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 125 of file osp_object.c.
Function Documentation
static bool is_ost_obj (struct lu_object * lo) [inline, static]
Definition at line 137 of file osp_object.c.
References lu_object::lo_dev, lu2osp_dev(), and osp_device::opd_connect_mdt.
Referenced by osp_attr_get(), osp_object_init(), osp_object_release(), and osp_xattr_get().
int osp_attr_get (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr)
Implement OSP layer dt_object_operations::do_attr_get() interface.
Get attribute from the specified MDT/OST object.
If the attribute is in the OSP object attributes cache, then return the cached attribute directly. Otherwise it will trigger an OUT RPC to the peer to get the attribute synchronously, if successful, add it to the OSP attributes cache. (
See also:
lustre/osp/osp_trans.c for OUT RPC.)
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the OSP layer dt_object
[out] attr pointer to the buffer to hold the output attribute
Return values:
0 for success
negative error number on failure
Definition at line 542 of file osp_object.c.
References CERROR, dt_device::dd_lu_dev, DFID, dt_object::do_lu, dt2osp_obj(), ENTRY, GOTO, is_ost_obj(), lu_attr::la_valid, lu_device::ld_obd, lu_object::lo_dev, lu_object::lo_header, lu_object_header::loh_attr, LOHA_EXISTS, lu2osp_dev(), lu_object_fid(), obd_device::obd_name, osp_object_attr::ooa_attr, osp_device::opd_dt_dev, osp_object::opo_lock, osp_object::opo_non_exist, osp_object::opo_ooa, osp_object::opo_stale, osp2lu_obj(), osp_get_attr_from_reply(), osp_remote_sync(), osp_update_request_create(), osp_update_request_destroy(), osp_update_rpc_pack, object_update_reply::ourp_magic, OUT_ATTR_GET, OUT_UPDATE_REPLY_SIZE, PFID, ptlrpc_req_finished(), req_capsule_server_sized_get(), RETURN, RMF_OUT_UPDATE_REPLY, ptlrpc_request::rq_pill, and UPDATE_REPLY_MAGIC.
static int osp_attr_get_interpterer (const struct lu_env * env, struct object_update_reply * reply, struct ptlrpc_request * req, struct osp_object * obj, void * data, int index, int rc) [static]
Interpreter function for getting OSP object attribute asynchronously.
Called to interpret the result of an async mode RPC for getting the OSP object attribute.
Parameters:
[in] env pointer to the thread context
[in] reply pointer to the RPC reply
[in] req pointer to the RPC request
[in] obj pointer to the OSP object
[out] data pointer to buffer to hold the output attribute
[in] index the index of the attribute buffer in the reply
[in] rc the result for handling the RPC
Return values:
0 for success
negative error number on failure
Definition at line 457 of file osp_object.c.
References lu_attr::la_valid, LASSERT, lu_object::lo_header, lu_object_header::loh_attr, LOHA_EXISTS, osp_object::opo_lock, osp_object::opo_non_exist, osp_object::opo_ooa, osp2lu_obj(), and osp_get_attr_from_reply().
Referenced by osp_declare_attr_get().
static int osp_attr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_attr * attr, struct thandle * th) [static]
Implement OSP layer dt_object_operations::do_attr_set() interface.
Set attribute to the specified OST object.
If the transaction is a remote one, then add OUT_ATTR_SET sub-request in the OUT RPC that will be flushed when the remote transaction stop. Otherwise, it will generate a MDS_SETATTR64_REC record in the llog that will be handled by a dedicated thread asynchronously.
If the attribute entry exists in the OSP object attributes cache, then update the cached attribute according to given attribute.
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the OSP layer dt_object
[in] attr pointer to the attribute to be set
[in] th pointer to the transaction handler
Return values:
0 for success
negative error number on failure
Definition at line 709 of file osp_object.c.
References CDEBUG, D_INFO, DFID, dt_object::do_lu, dt2osp_obj(), ENTRY, is_only_remote_trans(), lu_attr::la_gid, LA_GID, lu_attr::la_uid, LA_UID, lu_attr::la_valid, lu_object::lo_header, lu_object_header::loh_fid, MDS_SETATTR64_REC, osp_object_attr::ooa_attr, osp_object::opo_lock, osp_object::opo_ooa, osp_md_attr_set(), osp_sync_add(), PFID, and RETURN.
static int osp_declare_attr_get (const struct lu_env * env, struct dt_object * dt) [static]
Implement OSP layer dt_object_operations::do_declare_attr_get() interface.
Declare that the caller will get attribute from the specified OST object.
This function adds an Object Unified Target (OUT) sub-request to the per-OSP based shared asynchronous request queue. The osp_attr_get_interpterer() is registered as the interpreter function to handle the result of this sub-request.
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the OSP layer dt_object
Return values:
0 for success
negative error number on failure
Definition at line 503 of file osp_object.c.
References dt_object::do_lu, dt2osp_obj(), lu_object::lo_dev, lu2osp_dev(), osp_object_attr::ooa_attr, osp_device::opd_async_requests_mutex, osp_object::opo_ooa, osp_attr_get_interpterer(), osp_insert_async_request(), osp_oac_init(), and OUT_ATTR_GET.
static int osp_declare_attr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_attr * attr, struct thandle * th) [static]
Implement OSP layer dt_object_operations::do_declare_attr_set() interface.
If the transaction is not remote one, then declare the credits that will be used for the subsequent llog record for the object's attributes.
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the OSP layer dt_object
[in] attr pointer to the attribute to be set
[in] th pointer to the transaction handler
Return values:
0 for success
negative error number on failure
Definition at line 638 of file osp_object.c.
References dt_object::do_lu, dt2osp_obj(), dt_object_exists(), fid_is_zero(), is_only_remote_trans(), LA_GID, lu_attr::la_size, LA_SIZE, LA_UID, lu_attr::la_valid, LASSERT, lu_object::lo_dev, lu2osp_dev(), lu_object_fid(), MDS_SETATTR64_REC, osp_object::opo_obj, osp_md_declare_attr_set(), osp_object_assign_fid(), osp_object_truncate(), osp_sync_declare_add(), and RETURN.
static int osp_declare_object_create (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof, struct thandle * th) [static]
Implement OSP layer dt_object_operations::do_declare_create() interface.
Declare that the caller will create the OST object.
If the transaction is a remote transaction and the FID for the OST-object has been assigned already, then handle it as creating (remote) MDT object via osp_md_declare_object_create(). This function is usually used for LFSCK to re-create the lost OST object. Otherwise, if it is not replay case, the OSP will reserve pre-created object for the subsequent create operation; if the MDT side cached pre-created objects are less than some threshold, then it will wakeup the pre-create thread.
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the OSP layer dt_object
[in] attr the attribute for the object to be created
[in] hint pointer to the hint for creating the object, such as the parent object
[in] dof pointer to the dt_object_format for help the creation
[in] th pointer to the transaction handler
Return values:
0 for success
negative error number on failure
Definition at line 1309 of file osp_object.c.
References dt_object::do_lu, dt2osp_obj(), dt_declare_record_write(), ENTRY, fid_is_sane(), fid_is_zero(), is_only_remote_trans(), LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lu_object::lo_dev, lu_object::lo_header, lu_object_header::loh_flags, lu2osp_dev(), lu_object_fid(), LU_OBJECT_HEARD_BANSHEE, OBD_FAIL_CHECK, OBD_FAIL_MDS_OSC_CREATE_FAIL, osp_device::opd_index, osp_device::opd_last_used_oid_file, osp_object::opo_reserved, osp_thread_info::osi_id, osp_thread_info::osi_lb, osp_thread_info::osi_off, osp_env_info(), osp_get_storage_thandle(), osp_md_declare_object_create(), osp_precreate_reserve(), RETURN, and unlikely.
int osp_declare_object_destroy (const struct lu_env * env, struct dt_object * dt, struct thandle * th)
Implement OSP layer dt_object_operations::do_declare_destroy() interface.
Declare that the caller will destroy the specified OST object.
The OST object destroy will be handled via llog asynchronously. This function will declare the credits for generating MDS_UNLINK64_REC llog.
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the OSP layer dt_object to be destroyed
[in] th pointer to the transaction handler
Return values:
0 for success
negative error number on failure
Definition at line 1530 of file osp_object.c.
References dt_object::do_lu, dt2osp_obj(), ENTRY, LASSERT, lu_object::lo_dev, lu2osp_dev(), MDS_UNLINK64_REC, osp_device::opd_connect_mdt, osp_sync_declare_add(), and RETURN.
int osp_declare_xattr_del (const struct lu_env * env, struct dt_object * dt, const char * name, struct thandle * th)
Implement OSP layer dt_object_operations::do_declare_xattr_del() interface.
Declare that the caller will delete extended attribute on the specified MDT/OST object.
If it is non-remote transaction, it will add an OUT_XATTR_DEL sub-request to the OUT RPC that will be flushed when the transaction start. And if the name extended attribute entry exists in the OSP attributes cache, then remove it from the cache.
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the OSP layer dt_object
[in] name the name of the extended attribute to be set
[in] th pointer to the transaction handler
Return values:
0 for success
negative error number on failure
Definition at line 1236 of file osp_object.c.
References osp_trans_update_request_create().
static int osp_declare_xattr_get (const struct lu_env * env, struct dt_object * dt, struct lu_buf * buf, const char * name) [static]
Implement OSP dt_object_operations::do_declare_xattr_get() interface.
Declare that the caller will get extended attribute from the specified OST object.
This function will add an OUT_XATTR_GET sub-request to the per OSP based shared asynchronous request queue with the interpreter function: osp_xattr_get_interpterer().
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the OSP layer dt_object
[out] buf pointer to the lu_buf to hold the extended attribute
[in] name the name for the expected extended attribute
Return values:
0 for success
negative error number on failure
Definition at line 835 of file osp_object.c.
References dt_object::do_lu, dt2osp_obj(), LASSERT, lu_buf::lb_len, lu_object::lo_dev, lu2osp_dev(), osp_device::opd_async_requests, osp_device::opd_async_requests_mutex, osp_object::opo_ooa, osp_current_object_update_request(), osp_insert_async_request(), osp_oac_init(), osp_oac_xattr_find_or_add(), osp_oac_xattr_put(), osp_unplug_async_request(), osp_xattr_get_interpterer(), object_update_request::ourq_count, osp_update_request_sub::ours_req, OUT_XATTR_GET, and unlikely.
int osp_declare_xattr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, const char * name, int flag, struct thandle * th)
Implement OSP layer dt_object_operations::do_declare_xattr_set() interface.
Declare that the caller will set extended attribute to the specified MDT/OST object.
If it is non-remote transaction, it will add an OUT_XATTR_SET sub-request to the OUT RPC that will be flushed when the transaction start. And if the OSP attributes cache is initialized, then check whether the name extended attribute entry exists in the cache or not. If yes, replace it; otherwise, add the extended attribute to the cache.
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the OSP layer dt_object
[in] buf pointer to the lu_buf to hold the extended attribute
[in] name the name of the extended attribute to be set
[in] flag to indicate the detailed set operation: LU_XATTR_CREATE or LU_XATTR_REPLACE or others
[in] th pointer to the transaction handler
Return values:
0 for success
negative error number on failure
Definition at line 1125 of file osp_object.c.
References osp_trans_update_request_create().
static __u32 osp_dev2node (struct osp_device * osp) [inline, static]
Definition at line 132 of file osp_object.c.
References dt_device::dd_lu_dev, lu_site::ld_seq_site, lu_device::ld_site, osp_device::opd_storage, and seq_server_site::ss_node_id.
Referenced by osp_it_fetch(), and osp_xattr_get().
static int osp_get_attr_from_reply (const struct lu_env * env, struct object_update_reply * reply, struct ptlrpc_request * req, struct lu_attr * attr, struct osp_object * obj, int index) [static]
Parse the OSP object attribute from the RPC reply.
If the attribute is valid, then it will be added to the OSP object attributes cache.
Parameters:
[in] env pointer to the thread context
[in] reply pointer to the RPC reply
[in] req pointer to the RPC request
[out] attr pointer to buffer to hold the output attribute
[in] obj pointer to the OSP object
[in] index the index of the attribute buffer in the reply
Return values:
0 for success
negative error number on failure
Definition at line 400 of file osp_object.c.
References la_from_obdo(), LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lustre_get_wire_obdo(), lustre_swab_obdo(), obdo::o_valid, object_update_result_data_get(), osp_object_attr::ooa_attr, osp_object::opo_lock, osp_object::opo_ooa, osp_thread_info::osi_lb2, osp_thread_info::osi_obdo, osp_env_info(), and ptlrpc_req_need_swab().
Referenced by osp_attr_get(), and osp_attr_get_interpterer().
static int osp_index_try (const struct lu_env * env, struct dt_object * dt, const struct dt_index_features * feat) [static]
Implement OSP layer dt_object_operations::do_index_try() interface.
Negotiate the index type.
If the target index is an IDIF object, then use osp_orphan_index_ops. Otherwise, assign osp_md_index_ops to the dt_object::do_index_ops. (
See also:
lustre/include/lustre_fid.h for IDIF.)
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the OSP layer dt_object
[in] feat unused
Return values:
0 for success
Definition at line 2083 of file osp_object.c.
References dt_object::do_index_ops, dt_object::do_lu, fid_is_idif(), fid_is_last_id(), lu_object_fid(), and osp_md_index_ops.
static int osp_it_fetch (const struct lu_env * env, struct osp_it * it) [static]
Get more records for the iteration from peer.
The new records will be filled in an array of pages. The OSP side allows 1MB bulk data to be transferred.
Parameters:
[in] env pointer to the thread context
[in] it pointer to the iteration structure
Return values:
0 for success
negative error number on failure
Definition at line 1695 of file osp_object.c.
References ptlrpc_bulk_frag_ops::add_kiov_frag, ptlrpc_bulk_desc::bd_frag_ops, CERROR, client_obd::cl_import, obd_device::cli, dt_object::do_lu, ENTRY, lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, fid_is_last_id(), FID_SEQ_LAYOUT_RBTREE, GOTO, IDX_INFO_MAGIC, idx_info::ii_attrs, idx_info::ii_count, idx_info::ii_fid, II_FL_NOHASH, II_FL_NOKEY, II_FL_VARKEY, II_FL_VARREC, idx_info::ii_flags, idx_info::ii_hash_end, idx_info::ii_hash_start, idx_info::ii_magic, lu_device::ld_obd, lu_device::ld_site, lu_object::lo_dev, lu_site::ls_top_dev, lu2osp_dev(), lu_object_fid(), LU_PAGE_COUNT, LU_PAGE_SHIFT, LUSTRE_OBD_VERSION, MDS_BULK_PORTAL, min_t, OBD_ALLOC, OBD_IDX_READ, obd_device::obd_name, obd_device::obd_recovering, OFD_MAX_BRW_SIZE, osp_it::ooi_attr, osp_it::ooi_next, osp_it::ooi_obj, osp_it::ooi_pages, osp_it::ooi_swab, osp_it::ooi_total_npages, osp_it::ooi_valid_npages, osp_device::opd_index, osp_device::opd_obd, osp_dev2node(), OUT_PORTAL, ptlrpc_at_set_req_timeout(), PTLRPC_BULK_BUF_KIOV, ptlrpc_bulk_kiov_pin_ops, PTLRPC_BULK_PUT_SINK, ptlrpc_prep_bulk_imp(), ptlrpc_queue_wait(), ptlrpc_rep_need_swab(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_IDX_INFO, ptlrpc_request::rq_allow_replay, ptlrpc_request::rq_pill, RQF_OBD_IDX_READ, sptlrpc_cli_unwrap_bulk_read(), and obd_device::u.
Referenced by osp_it_next_page().
void osp_it_fini (const struct lu_env * env, struct dt_it * di)
Finalize the OSP layer index iteration.
Parameters:
[in] env pointer to the thread context
[in] di pointer to the iteration structure
Definition at line 1661 of file osp_object.c.
References OBD_FREE, OBD_FREE_PTR, osp_it::ooi_cur_page, osp_it::ooi_pages, and osp_it::ooi_total_npages.
int osp_it_get (const struct lu_env * env, struct dt_it * di, const struct dt_key * key)
Definition at line 1963 of file osp_object.c.
struct dt_it* osp_it_init (const struct lu_env * env, struct dt_object * dt, __u32 attr) [read]
Initialize the OSP layer index iteration.
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the index object to be iterated
[in] attr unused
Return values:
pointer to the iteration structure
negative error number on failure
Definition at line 1639 of file osp_object.c.
References OBD_ALLOC_PTR, osp_it::ooi_attr, osp_it::ooi_obj, and osp_it::ooi_pos_ent.
int osp_it_key_rec (const struct lu_env * env, const struct dt_it * di, void * key_rec)
Definition at line 2041 of file osp_object.c.
int osp_it_next_page (const struct lu_env * env, struct dt_it * di)
Move the iteration cursor to the next lu_page.
One system page (PAGE_SIZE) may contain multiple lu_page (4KB), that depends on the LU_PAGE_COUNT. If it is not the last lu_page in current system page, then move the iteration cursor to the next lu_page in current system page. Otherwise, if there are more system pages in the cache, then move the iteration cursor to the next system page. If all the cached records (pages) have been iterated, then fetch more records via osp_it_fetch().
Parameters:
[in] env pointer to the thread context
[in] di pointer to the iteration structure
Return values:
positive for end of the directory
0 for success
negative error number on failure
Definition at line 1833 of file osp_object.c.
References CDEBUG, CERROR, D_INFO, dt_object::do_lu, ENTRY, II_END_OFF, LIP_MAGIC, lu_idxpage::lip_magic, lu_idxpage::lip_nr, lu_object::lo_dev, lu2osp_dev(), LU_PAGE_COUNT, LU_PAGE_SIZE, lustre_swab_lip_header(), OBD_FREE, obd_device::obd_name, osp_it::ooi_cur_idxpage, osp_it::ooi_cur_page, osp_it::ooi_ent, osp_it::ooi_next, osp_it::ooi_obj, osp_it::ooi_pages, osp_it::ooi_pos_ent, osp_it::ooi_pos_lu_page, osp_it::ooi_pos_page, osp_it::ooi_swab, osp_it::ooi_total_npages, osp_it::ooi_valid_npages, osp_device::opd_obd, osp_it_fetch(), and RETURN.
Referenced by osp_md_index_it_next(), and osp_orphan_it_next().
void osp_it_put (const struct lu_env * env, struct dt_it * di)
Definition at line 1969 of file osp_object.c.
__u64 osp_it_store (const struct lu_env * env, const struct dt_it * di)
Definition at line 2005 of file osp_object.c.
References osp_it::ooi_next.
int osp_oac_init (struct osp_object * obj)
Initialize the OSP object attributes cache.
Parameters:
[in] obj pointer to the OSP object
Return values:
0 for success
negative error number on failure
Definition at line 174 of file osp_object.c.
References INIT_LIST_HEAD, likely, OBD_ALLOC_PTR, OBD_FREE_PTR, osp_object_attr::ooa_xattr_list, osp_object::opo_lock, and osp_object::opo_ooa.
Referenced by osp_declare_attr_get(), osp_declare_xattr_get(), and osp_md_declare_object_create().
static struct osp_xattr_entry* osp_oac_xattr_find (struct osp_object * obj, const char * name, bool unlink) [static, read]
Find the named extended attribute in the OSP object attributes cache.
Call osp_oac_xattr_find_locked() with the osp_object::opo_lock held.
Parameters:
[in] obj pointer to the OSP object
[in] name the name of the extended attribute
[in] unlink true if the extended attribute entry is to be removed from the cache
Return values:
pointer to the found extended attribute entry
NULL if the specified extended attribute is not in the cache
Definition at line 238 of file osp_object.c.
References list_del_init(), osp_object::opo_lock, osp_object::opo_ooa, osp_oac_xattr_find_locked(), osp_xattr_entry::oxe_list, and osp_xattr_entry::oxe_ref.
Referenced by osp_oac_xattr_find_or_add(), osp_xattr_del(), and osp_xattr_get().
static struct osp_xattr_entry* osp_oac_xattr_find_locked (struct osp_object_attr * ooa, const char * name, size_t namelen) [static, read]
Find the named extended attribute in the OSP object attributes cache.
The caller should take the osp_object::opo_lock before calling this function.
Parameters:
[in] ooa pointer to the OSP object attributes cache
[in] name the name of the extended attribute
[in] namelen the name length of the extended attribute
Return values:
pointer to the found extended attribute entry
NULL if the specified extended attribute is not in the cache
Definition at line 210 of file osp_object.c.
References list_for_each_entry, osp_object_attr::ooa_xattr_list, osp_xattr_entry::oxe_buf, osp_xattr_entry::oxe_list, and osp_xattr_entry::oxe_namelen.
Referenced by osp_oac_xattr_find(), osp_oac_xattr_find_or_add(), and osp_oac_xattr_replace().
static struct osp_xattr_entry* osp_oac_xattr_find_or_add (struct osp_object * obj, const char * name, size_t len) [static, read]
Find the named extended attribute in the OSP object attributes cache.
If it is not in the cache, then add an empty entry (that will be filled later) to cache with the given name.
Parameters:
[in] obj pointer to the OSP object
[in] name the name of the extended attribute
[in] len the length of the extended attribute value
Return values:
pointer to the found or new-created extended attribute entry
NULL if the specified extended attribute is not in the cache or fail to add new empty entry to the cache.
Definition at line 275 of file osp_object.c.
References INIT_LIST_HEAD, LASSERT, list_add_tail(), OBD_ALLOC, OBD_FREE, osp_object_attr::ooa_xattr_list, osp_object::opo_lock, osp_object::opo_ooa, osp_oac_xattr_find(), osp_oac_xattr_find_locked(), osp_xattr_entry::oxe_buf, osp_xattr_entry::oxe_buflen, osp_xattr_entry::oxe_list, osp_xattr_entry::oxe_namelen, osp_xattr_entry::oxe_ref, osp_xattr_entry::oxe_value, size, and unlikely.
Referenced by osp_declare_xattr_get(), osp_xattr_get(), and osp_xattr_set().
static void osp_oac_xattr_put (struct osp_xattr_entry * oxe) [inline, static]
Release reference from the OSP object extended attribute entry.
If it is the last reference, then free the entry.
Parameters:
[in] oxe pointer to the OSP object extended attribute entry.
Definition at line 375 of file osp_object.c.
References LASSERT, list_empty(), OBD_FREE, osp_xattr_entry::oxe_buflen, osp_xattr_entry::oxe_list, and osp_xattr_entry::oxe_ref.
Referenced by osp_declare_xattr_get(), osp_xattr_del(), osp_xattr_get(), osp_xattr_get_interpterer(), and osp_xattr_set().
static struct osp_xattr_entry* osp_oac_xattr_replace (struct osp_object * obj, struct osp_xattr_entry ** poxe, size_t len) [static, read]
Add the given extended attribute to the OSP object attributes cache.
If there is an old extended attributed entry with the same name, remove it from the cache and return it via the parameter poxe.
Parameters:
[in] obj pointer to the OSP object
[in,out] poxe double pointer to the OSP object extended attribute entry: the new extended attribute entry is transferred via such pointer target, and if old the extended attribute entry exists, then it will be returned back via such pointer target.
[in] len the length of the (new) extended attribute value
Return values:
pointer to the new extended attribute entry
NULL for failure cases.
Definition at line 335 of file osp_object.c.
References INIT_LIST_HEAD, LASSERT, list_add_tail(), list_del_init(), OBD_ALLOC, osp_object_attr::ooa_xattr_list, osp_object::opo_lock, osp_object::opo_ooa, osp_oac_xattr_find_locked(), osp_xattr_entry::oxe_buf, osp_xattr_entry::oxe_buflen, osp_xattr_entry::oxe_list, osp_xattr_entry::oxe_namelen, osp_xattr_entry::oxe_ref, osp_xattr_entry::oxe_value, size, and unlikely.
Referenced by osp_xattr_get(), and osp_xattr_set().
static void osp_object_assign_fid (const struct lu_env * env, struct osp_device * d, struct osp_object * o) [static]
Assign FID to the OST object.
This function will assign the FID to the OST object of a striped file.
Parameters:
[in] env pointer to the thread context
[in] d pointer to the OSP device
[in] o pointer to the OSP object that the FID will be assigned to
Definition at line 152 of file osp_object.c.
References dt_object::do_lu, fid_is_zero(), LASSERT, lu_object_assign_fid(), lu_object_fid(), osp_object::opo_obj, osp_object::opo_reserved, osp_thread_info::osi_fid, osp_env_info(), and osp_precreate_get_fid().
Referenced by osp_declare_attr_set(), and osp_object_create().
static int osp_object_create (const struct lu_env * env, struct dt_object * dt, struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof, struct thandle * th) [static]
Implement OSP layer dt_object_operations::do_create() interface.
Create the OST object.
If the transaction is a remote transaction and the FID for the OST-object has been assigned already, then handle it as handling MDT object via the osp_md_object_create(). For other cases, the OSP will assign FID to the object to be created, and update last_used Object ID (OID) file.
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the OSP layer dt_object
[in] attr the attribute for the object to be created
[in] hint pointer to the hint for creating the object, such as the parent object
[in] dof pointer to the dt_object_format for help the creation
[in] th pointer to the transaction handler
Return values:
0 for success
negative error number on failure
Definition at line 1417 of file osp_object.c.
References CDEBUG, D_HA, D_INODE, DFID, dt_object::do_lu, dt2osp_obj(), dt_record_write(), ENTRY, lu_fid::f_oid, fid_is_sane(), fid_is_zero(), fid_oid(), is_only_remote_trans(), LASSERT, LASSERTF, lu_object::lo_dev, lu2osp_dev(), lu_object_fid(), obd_device::obd_name, osp_device::opd_gap_count, osp_device::opd_gap_start_fid, osp_device::opd_index, osp_device::opd_last_used_fid, osp_device::opd_last_used_oid_file, osp_device::opd_obd, osp_device::opd_pre, osp_object::opo_non_exist, osp_object::opo_reserved, osp_thread_info::osi_fid, osp_thread_info::osi_lb, osp_thread_info::osi_off, osp_thread_info::osi_oi, osp_env_info(), osp_get_storage_thandle(), osp_is_fid_client(), osp_md_object_create(), osp_object_assign_fid(), osp_objid_buf_prep(), osp_precreate_end_seq(), osp_update_last_fid(), ostid_set_id(), PFID, RETURN, thandle::th_sync, and unlikely.
static int osp_object_destroy (const struct lu_env * env, struct dt_object * dt, struct thandle * th) [static]
Implement OSP layer dt_object_operations::do_destroy() interface.
Destroy the specified OST object.
The OSP generates a MDS_UNLINK64_REC record in the llog. There will be some dedicated thread to handle the llog asynchronously.
It also marks the object as non-cached.
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the OSP layer dt_object to be destroyed
[in] th pointer to the transaction handler
Return values:
0 for success
negative error number on failure
Definition at line 1562 of file osp_object.c.
References dt_object::do_lu, dt2osp_obj(), ENTRY, LASSERT, lu_object::lo_dev, lu_object::lo_header, lu_object_header::loh_flags, lu2osp_dev(), LU_OBJECT_HEARD_BANSHEE, MDS_UNLINK64_REC, osp_device::opd_connect_mdt, osp_object::opo_non_exist, osp_sync_add(), and RETURN.
static void osp_object_free (const struct lu_env * env, struct lu_object * o) [static]
Implement OSP layer lu_object_operations::loo_object_free() interface.
Finalize the object.
If the OSP object has attributes cache, then destroy the cache. Free the object finally.
Parameters:
[in] env pointer to the thread context
[in] o pointer to the OSP layer lu_object
Definition at line 2173 of file osp_object.c.
References dt_object_fini(), LASSERTF, list_del(), list_for_each_entry_safe, lu_object::lo_header, lu2osp_obj(), lu_object_header_fini(), OBD_FREE, OBD_FREE_PTR, OBD_SLAB_FREE_PTR, osp_object_attr::ooa_xattr_list, osp_object::opo_obj, osp_object::opo_ooa, osp_object_kmem, osp_xattr_entry::oxe_buf, osp_xattr_entry::oxe_buflen, osp_xattr_entry::oxe_list, osp_xattr_entry::oxe_namelen, and osp_xattr_entry::oxe_ref.
static int osp_object_init (const struct lu_env * env, struct lu_object * o, const struct lu_object_conf * conf) [static]
Implement OSP layer lu_object_operations::loo_object_init() interface.
Initialize the object.
If it is a remote MDT object, then call do_attr_get() to fetch the attribute from the peer.
Parameters:
[in] env pointer to the thread context
[in] o pointer to the OSP layer lu_object
[in] conf unused
Return values:
0 for success
negative error number on failure
Definition at line 2127 of file osp_object.c.
References dt_object_operations::do_attr_get, dt_object::do_body_ops, dt_object::do_ops, ENTRY, is_ost_obj(), lu_attr::la_mode, lu_object::lo_header, LOC_F_NEW, lu_object_conf::loc_flags, lu_object_header::loh_attr, LOHA_EXISTS, LOHA_REMOTE, lu2dt_obj(), lu2osp_obj(), osp_object::opo_lock, osp_object::opo_non_exist, osp_object::opo_obj, osp_object::opo_sem, osp_thread_info::osi_attr, osp_env_info(), osp_md_body_ops, osp_md_obj_ops, and RETURN.
static int osp_object_invariant (const struct lu_object * o) [static]
Definition at line 2252 of file osp_object.c.
References LBUG.
static int osp_object_print (const struct lu_env * env, void * cookie, lu_printer_t p, const struct lu_object * l) [static]
Definition at line 2244 of file osp_object.c.
References lu2osp_obj(), and LUSTRE_OSP_NAME.
static void osp_object_release (const struct lu_env * env, struct lu_object * o) [static]
Implement OSP layer lu_object_operations::loo_object_release() interface.
Cleanup (not free) the object.
If it is a reserved object but failed to be created, or it is an OST object, then mark the object as non-cached.
Parameters:
[in] env pointer to the thread context
[in] o pointer to the OSP layer lu_object
Definition at line 2212 of file osp_object.c.
References ENTRY, EXIT, is_ost_obj(), LASSERT, lu_object::lo_dev, lu_object::lo_header, lu_object_header::loh_flags, lu2osp_dev(), lu2osp_obj(), LU_OBJECT_HEARD_BANSHEE, osp_device::opd_pre, osp_object::opo_reserved, and unlikely.
static int osp_orphan_index_declare_delete (const struct lu_env * env, struct dt_object * dt, const struct dt_key * key, struct thandle * handle) [static]
Definition at line 1613 of file osp_object.c.
static int osp_orphan_index_declare_insert (const struct lu_env * env, struct dt_object * dt, const struct dt_rec * rec, const struct dt_key * key, struct thandle * handle) [static]
Definition at line 1594 of file osp_object.c.
static int osp_orphan_index_delete (const struct lu_env * env, struct dt_object * dt, const struct dt_key * key, struct thandle * handle) [static]
Definition at line 1621 of file osp_object.c.
static int osp_orphan_index_insert (const struct lu_env * env, struct dt_object * dt, const struct dt_rec * rec, const struct dt_key * key, struct thandle * handle, int ignore_quota) [static]
Definition at line 1603 of file osp_object.c.
static int osp_orphan_index_lookup (const struct lu_env * env, struct dt_object * dt, struct dt_rec * rec, const struct dt_key * key) [static]
Definition at line 1586 of file osp_object.c.
static struct dt_key* osp_orphan_it_key (const struct lu_env * env, const struct dt_it * di) [static, read]
Definition at line 1973 of file osp_object.c.
References dt_key, likely, lu_orphan_ent::loe_key, and osp_it::ooi_ent.
static int osp_orphan_it_key_size (const struct lu_env * env, const struct dt_it * di) [static]
Definition at line 1985 of file osp_object.c.
int osp_orphan_it_load (const struct lu_env * env, const struct dt_it * di, __u64 hash)
Locate the iteration cursor to the specified position (cookie).
Parameters:
[in] env pointer to the thread context
[in] di pointer to the iteration structure
[in] hash the specified position
Return values:
positive number for locating to the exactly position or the next
0 for arriving at the end of the iteration
negative error number on failure
Definition at line 2024 of file osp_object.c.
References osp_it::ooi_next, and osp_orphan_it_next().
static int osp_orphan_it_next (const struct lu_env * env, struct dt_it * di) [static]
Move the iteration cursor to the next record.
If there are more records in the lu_page, then move the iteration cursor to the next record directly. Otherwise, move the iteration cursor to the record in the next lu_page via osp_it_next_page()
Parameters:
[in] env pointer to the thread context
[in] di pointer to the iteration structure
Return values:
positive for end of the directory
0 for success
negative error number on failure
Definition at line 1932 of file osp_object.c.
References ENTRY, lu_idxpage::lip_entries, lu_idxpage::lip_nr, lustre_swab_orphan_ent(), osp_it::ooi_cur_idxpage, osp_it::ooi_ent, osp_it::ooi_pos_ent, osp_it::ooi_swab, osp_it_next_page(), and RETURN.
Referenced by osp_orphan_it_load().
static int osp_orphan_it_rec (const struct lu_env * env, const struct dt_it * di, struct dt_rec * rec, __u32 attr) [static]
Definition at line 1991 of file osp_object.c.
References likely, lu_orphan_ent::loe_rec, and osp_it::ooi_ent.
int osp_xattr_del (const struct lu_env * env, struct dt_object * dt, const char * name, struct thandle * th)
Implement OSP layer dt_object_operations::do_xattr_del() interface.
Delete extended attribute on the specified MDT/OST object.
If it is remote transaction, it will add an OUT_XATTR_DEL sub-request into the OUT RPC that will be flushed when the transaction stop. And if the name extended attribute entry exists in the OSP attributes cache, then remove it from the cache.
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the OSP layer dt_object
[in] name the name of the extended attribute to be set
[in] th pointer to the transaction handler
Return values:
0 for success
negative error number on failure
Definition at line 1260 of file osp_object.c.
References dt_object::do_lu, dt2osp_obj(), LASSERT, lu_object_fid(), osp_object::opo_ooa, osp_oac_xattr_find(), osp_oac_xattr_put(), osp_update_rpc_pack, OUT_XATTR_DEL, and thandle_to_osp_update_request().
int osp_xattr_get (const struct lu_env * env, struct dt_object * dt, struct lu_buf * buf, const char * name)
Implement OSP layer dt_object_operations::do_xattr_get() interface.
Get extended attribute from the specified MDT/OST object.
If the extended attribute is in the OSP object attributes cache, then return the cached extended attribute directly. Otherwise it will get the extended attribute synchronously, if successful, add it to the OSP attributes cache. (
See also:
lustre/osp/osp_trans.c for OUT RPC.)
There is a race condition: some other thread has added the named extended attributed entry to the OSP object attributes cache during the current OUT_XATTR_GET handling. If such case happens, the OSP will replace the (just) existing extended attribute entry with the new replied one.
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the OSP layer dt_object
[out] buf pointer to the lu_buf to hold the extended attribute
[in] name the name for the expected extended attribute
Return values:
0 for success
negative error number on failure
Definition at line 916 of file osp_object.c.
References CERROR, cfs_fail_val, CWARN, DFID, dt_object::do_lu, dt2osp_obj(), ENTRY, GOTO, is_ost_obj(), LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lu_device::ld_obd, lu_object::lo_dev, lu_object::lo_header, lu_object_header::loh_attr, LOHA_EXISTS, lu2osp_dev(), lu_object_fid(), OBD_FAIL_CHECK, OBD_FAIL_LFSCK_BAD_NETWORK, obd_device::obd_name, object_update_result_data_get(), osp_device::opd_connect_mdt, osp_device::opd_dt_dev, osp_device::opd_index, osp_object::opo_lock, osp_object::opo_non_exist, osp_object::opo_ooa, osp_thread_info::osi_lb2, osp_dev2node(), osp_env_info(), osp_oac_xattr_find(), osp_oac_xattr_find_or_add(), osp_oac_xattr_put(), osp_oac_xattr_replace(), osp_remote_sync(), osp_update_request_create(), osp_update_request_destroy(), osp_update_rpc_pack, object_update_reply::ourp_magic, OUT_UPDATE_REPLY_SIZE, OUT_XATTR_GET, osp_xattr_entry::oxe_buflen, osp_xattr_entry::oxe_exist, osp_xattr_entry::oxe_namelen, osp_xattr_entry::oxe_ready, osp_xattr_entry::oxe_vallen, osp_xattr_entry::oxe_value, PFID, ptlrpc_req_finished(), req_capsule_server_sized_get(), RETURN, RMF_OUT_UPDATE_REPLY, ptlrpc_request::rq_pill, unlikely, UPDATE_REPLY_MAGIC, and XATTR_NAME_LINK.
static int osp_xattr_get_interpterer (const struct lu_env * env, struct object_update_reply * reply, struct ptlrpc_request * req, struct osp_object * obj, void * data, int index, int rc) [static]
Interpreter function for getting OSP object extended attribute asynchronously.
Called to interpret the result of an async mode RPC for getting the OSP object extended attribute.
Parameters:
[in] env pointer to the thread context
[in] reply pointer to the RPC reply
[in] req pointer to the RPC request
[in] obj pointer to the OSP object
[out] data pointer to OSP object attributes cache
[in] index the index of the attribute buffer in the reply
[in] rc the result for handling the RPC
Return values:
0 for success
negative error number on failure
Definition at line 770 of file osp_object.c.
References LASSERT, lu_buf::lb_buf, lu_buf::lb_len, object_update_result_data_get(), osp_object::opo_lock, osp_object::opo_ooa, osp_thread_info::osi_lb2, osp_env_info(), osp_oac_xattr_put(), osp_xattr_entry::oxe_buflen, osp_xattr_entry::oxe_exist, osp_xattr_entry::oxe_namelen, osp_xattr_entry::oxe_ready, osp_xattr_entry::oxe_vallen, and osp_xattr_entry::oxe_value.
Referenced by osp_declare_xattr_get().
int osp_xattr_set (const struct lu_env * env, struct dt_object * dt, const struct lu_buf * buf, const char * name, int fl, struct thandle * th)
Implement OSP layer dt_object_operations::do_xattr_set() interface.
Set extended attribute to the specified MDT/OST object.
Add an OUT_XATTR_SET sub-request into the OUT RPC that will be flushed in the transaction stop. And if the OSP attributes cache is initialized, then check whether the name extended attribute entry exists in the cache or not. If yes, replace it; otherwise, add the extended attribute to the cache.
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the OSP layer dt_object
[in] buf pointer to the lu_buf to hold the extended attribute
[in] name the name of the extended attribute to be set
[in] fl to indicate the detailed set operation: LU_XATTR_CREATE or LU_XATTR_REPLACE or others
[in] th pointer to the transaction handler
Return values:
0 for success
negative error number on failure
Definition at line 1153 of file osp_object.c.
References CDEBUG, CWARN, D_INODE, DFID, dt_object::do_lu, dt2osp_obj(), ENTRY, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lu_device::ld_obd, lu_object::lo_dev, lu2osp_dev(), lu_object_fid(), obd_device::obd_name, osp_device::opd_connect_mdt, osp_object::opo_lock, osp_object::opo_ooa, osp_oac_xattr_find_or_add(), osp_oac_xattr_put(), osp_oac_xattr_replace(), osp_update_rpc_pack, OUT_XATTR_SET, osp_xattr_entry::oxe_buflen, osp_xattr_entry::oxe_exist, osp_xattr_entry::oxe_namelen, osp_xattr_entry::oxe_ready, osp_xattr_entry::oxe_vallen, osp_xattr_entry::oxe_value, PFID, RETURN, and thandle_to_osp_update_request().
Variable Documentation
struct lu_object_operations osp_lu_obj_ops
Initial value:
 {
        .loo_object_init        = osp_object_init,
        .loo_object_free        = osp_object_free,
        .loo_object_release     = osp_object_release,
        .loo_object_print       = osp_object_print,
        .loo_object_invariant   = osp_object_invariant
}
Definition at line 2257 of file osp_object.c.
Referenced by osp_object_alloc().
struct dt_object_operations osp_obj_ops [static]
Initial value:
 {
        .do_declare_attr_get    = osp_declare_attr_get,
        .do_attr_get            = osp_attr_get,
        .do_declare_attr_set    = osp_declare_attr_set,
        .do_attr_set            = osp_attr_set,
        .do_declare_xattr_get   = osp_declare_xattr_get,
        .do_xattr_get           = osp_xattr_get,
        .do_declare_xattr_set   = osp_declare_xattr_set,
        .do_xattr_set           = osp_xattr_set,
        .do_declare_create      = osp_declare_object_create,
        .do_create              = osp_object_create,
        .do_declare_destroy     = osp_declare_object_destroy,
        .do_destroy             = osp_object_destroy,
        .do_index_try           = osp_index_try,
}
Definition at line 2096 of file osp_object.c.
struct dt_index_operations osp_orphan_index_ops [static]
Initial value:
 {
        .dio_lookup             = osp_orphan_index_lookup,
        .dio_declare_insert     = osp_orphan_index_declare_insert,
        .dio_insert             = osp_orphan_index_insert,
        .dio_declare_delete     = osp_orphan_index_declare_delete,
        .dio_delete             = osp_orphan_index_delete,
        .dio_it = {
                .init           = osp_it_init,
                .fini           = osp_it_fini,
                .next           = osp_orphan_it_next,
                .get            = osp_it_get,
                .put            = osp_it_put,
                .key            = osp_orphan_it_key,
                .key_size       = osp_orphan_it_key_size,
                .rec            = osp_orphan_it_rec,
                .store          = osp_it_store,
                .load           = osp_orphan_it_load,
                .key_rec        = osp_it_key_rec,
        }
}
Definition at line 2047 of file osp_object.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.