Lustre: lustre/osp/osp_trans.c File Reference
lustre/osp/osp_trans.c File Reference
#include <lustre_net.h>
#include "osp_internal.h"
Data Structures
struct osp_update_args
The argument for the interpreter callback of osp request.
struct osp_update_callback
Call back for each update request.
Defines
#define DEBUG_SUBSYSTEM S_MDS
Functions
static struct
object_update_request * object_update_request_alloc (size_t size)
int osp_object_update_request_create (struct osp_update_request *our, size_t size)
Allocate new update request.
struct osp_update_request_sub * osp_current_object_update_request (struct osp_update_request *our)
Get current update request.
struct osp_update_request * osp_update_request_create (struct dt_device *dt)
Allocate and initialize osp_update_request.
void osp_update_request_destroy (struct osp_update_request *our)
static void object_update_request_dump (const struct object_update_request *ourq, unsigned int mask)
int osp_prep_inline_update_req (const struct lu_env *env, struct ptlrpc_request *req, struct osp_update_request *our, int repsize)
Prepare inline update request.
int osp_prep_update_req (const struct lu_env *env, struct obd_import *imp, struct osp_update_request *our, struct ptlrpc_request **reqp)
Prepare update request.
int osp_remote_sync (const struct lu_env *env, struct osp_device *osp, struct osp_update_request *our, struct ptlrpc_request **reqp)
Send update RPC.
static void osp_thandle_invalidate_object (const struct lu_env *env, struct osp_thandle *oth)
Invalidate all objects in the osp thandle.
static void osp_trans_stop_cb (const struct lu_env *env, struct osp_thandle *oth, int result)
static struct osp_update_callback * osp_update_callback_init (struct osp_object *obj, void *data, osp_update_interpreter_t interpreter)
Allocate an osp request and initialize it with the given parameters.
static void osp_update_callback_fini (const struct lu_env *env, struct osp_update_callback *ouc)
Destroy the osp_update_callback.
static int osp_update_interpret (const struct lu_env *env, struct ptlrpc_request *req, void *arg, int rc)
Interpret the packaged OUT RPC results.
int osp_unplug_async_request (const struct lu_env *env, struct osp_device *osp, struct osp_update_request *our)
Pack all the requests in the shared asynchronous idempotent request queue into a single OUT RPC that will be given to the background ptlrpcd daemon.
static struct osp_update_request * osp_find_or_create_async_update_request (struct osp_device *osp)
Find or create (if NOT exist or purged) the shared asynchronous idempotent request queue - osp_device::opd_async_requests.
int osp_insert_update_callback (const struct lu_env *env, struct osp_update_request *our, struct osp_object *obj, void *data, osp_update_interpreter_t interpreter)
Insert an osp_update_callback into the osp_update_request.
int osp_insert_async_request (const struct lu_env *env, enum update_type op, struct osp_object *obj, int count, __u16 *lens, const void **bufs, void *data, __u32 repsize, osp_update_interpreter_t interpreter)
Insert an asynchronous idempotent request to the shared request queue that is attached to the osp_device.
int osp_trans_update_request_create (struct thandle *th)
void osp_thandle_destroy (struct osp_thandle *oth)
struct thandle * osp_trans_create (const struct lu_env *env, struct dt_device *d)
The OSP layer dt_device_operations::dt_trans_create() interface to create a transaction.
int osp_trans_cb_add (struct thandle *th, struct dt_txn_commit_cb *dcb)
Add commit callback to transaction.
static void osp_trans_commit_cb (struct osp_thandle *oth, int result)
static void osp_request_commit_cb (struct ptlrpc_request *req)
void osp_trans_callback (const struct lu_env *env, struct osp_thandle *oth, int rc)
callback of osp transaction
static int osp_send_update_req (const struct lu_env *env, struct osp_device *osp, struct osp_update_request *our)
Send the request for remote updates.
struct thandle * osp_get_storage_thandle (const struct lu_env *env, struct thandle *th, struct osp_device *osp)
Get local thandle for osp_thandle.
int osp_check_and_set_rpc_version (struct osp_thandle *oth, struct osp_object *obj)
Set version for the transaction.
static bool osp_get_next_request (struct osp_updates *ou, struct osp_update_request **ourp)
Get next OSP update request in the sending list Get next OSP update request in the sending list by version number, next request will be 1.
void osp_invalidate_request (struct osp_device *osp)
Invalidate update request.
int osp_send_update_thread (void *arg)
Sending update thread.
int osp_trans_start (const struct lu_env *env, struct dt_device *dt, struct thandle *th)
The OSP layer dt_device_operations::dt_trans_start() interface to start the transaction.
int osp_trans_stop (const struct lu_env *env, struct dt_device *dt, struct thandle *th)
The OSP layer dt_device_operations::dt_trans_stop() interface to stop the transaction.
Define Documentation
#define DEBUG_SUBSYSTEM S_MDS
Definition at line 67 of file osp_trans.c.
Function Documentation
static struct object_update_request* object_update_request_alloc (size_t size) [static, read]
Definition at line 100 of file osp_trans.c.
References OBD_ALLOC_LARGE, object_update_request::ourq_count, object_update_request::ourq_magic, and UPDATE_REQUEST_MAGIC.
Referenced by osp_object_update_request_create().
static void object_update_request_dump (const struct object_update_request * ourq, unsigned int mask) [static]
Definition at line 222 of file osp_trans.c.
References CDEBUG, DFID, LASSERT, LPU64, object_update_request_get(), object_update::ou_batchid, object_update::ou_fid, object_update::ou_params_count, object_update::ou_result_size, object_update::ou_type, object_update_request::ourq_count, object_update_request::ourq_magic, PFID, size, and update_op_str().
Referenced by osp_prep_update_req().
int osp_check_and_set_rpc_version (struct osp_thandle * oth, struct osp_object * obj)
Set version for the transaction.
Set the version for the transaction and add the request to the sending list, then after transaction stop, the request will be picked in the order of version, by sending thread.
Parameters:
[in] oth osp thandle to be set version.
Return values:
0 if set version succeeds negative errno if set version fails.
Definition at line 1264 of file osp_trans.c.
References CDEBUG, D_INFO, dt2osp_dev(), LASSERT, list_add_tail(), LPU64, obd_device::obd_name, osp_device::opd_obd, osp_device::opd_update, osp_object::opo_stale, osp_thandle_get(), osp_thandle::ot_our, osp_thandle::ot_super, osp_updates::ou_list, osp_updates::ou_lock, osp_updates::ou_version, osp_update_request::our_list, osp_update_request::our_list_lock, osp_update_request::our_req_ready, osp_update_request::our_version, thandle::th_dev, and thandle::th_wait_submit.
Referenced by osp_md_write().
struct osp_update_request_sub* osp_current_object_update_request (struct osp_update_request * our) [read]
Get current update request.
Get current object update request from our_req_list in osp_update_request, because we always insert the new update request in the last position, so the last update request in the list will be the current update req.
Parameters:
[in] our osp update request where to get the current object update.
Return values:
the current object update.
Definition at line 166 of file osp_trans.c.
References list_empty(), list_entry, osp_update_request::our_req_list, osp_update_request_sub::ours_list, and list_head::prev.
Referenced by osp_declare_xattr_get(), and osp_insert_async_request().
static struct osp_update_request* osp_find_or_create_async_update_request (struct osp_device * osp) [static, read]
Find or create (if NOT exist or purged) the shared asynchronous idempotent request queue - osp_device::opd_async_requests.
If the osp_device::opd_async_requests is not NULL, then return it directly; otherwise create new osp_update_request and attach it to opd_async_requests.
Parameters:
[in] osp pointer to the OSP device
Return values:
pointer to the shared queue
negative error number on failure
Definition at line 768 of file osp_trans.c.
References osp_device::opd_async_requests, osp_device::opd_dt_dev, and osp_update_request_create().
Referenced by osp_insert_async_request().
static bool osp_get_next_request (struct osp_updates * ou, struct osp_update_request ** ourp) [static]
Get next OSP update request in the sending list Get next OSP update request in the sending list by version number, next request will be 1.
transaction which does not have a version number. 2. transaction whose version == opd_rpc_version.
Parameters:
[in] ou osp update structure.
[out] ourp the pointer holding the next update request.
Return values:
true if getting the next transaction.
false if not getting the next transaction.
Definition at line 1315 of file osp_trans.c.
References CDEBUG, D_HA, LASSERT, list_del_init(), list_for_each_entry_safe, LPU64, osp_updates::ou_list, osp_updates::ou_lock, osp_updates::ou_rpc_version, osp_update_request::our_list, osp_update_request::our_list_lock, osp_update_request::our_req_ready, osp_update_request::our_th, and osp_update_request::our_version.
Referenced by osp_send_update_thread().
struct thandle* osp_get_storage_thandle (const struct lu_env * env, struct thandle * th, struct osp_device * osp) [read]
Get local thandle for osp_thandle.
Get the local OSD thandle from the OSP thandle. Currently, there are a few OSP API (osp_object_create() and osp_sync_add()) needs to update the object on local OSD device.
If the osp_thandle comes from normal stack (MDD->LOD->OSP), then we will get local thandle by thandle_get_sub_by_dt.
If the osp_thandle is remote thandle (th_top == NULL, only used by LFSCK), then it will create a local thandle, and stop it in osp_trans_stop(). And this only happens on OSP for OST.
These are temporary solution, once OSP accessing OSD object is being fixed properly, this function should be removed. XXX
Parameters:
[in] env pointer to the thread context
[in] th pointer to the transaction handler
[in] dt pointer to the OSP device
Return values:
pointer to the local thandle
ERR_PTR(errno) if it fails.
Definition at line 1227 of file osp_trans.c.
References dt_trans_create(), LASSERT, osp_device::opd_connect_mdt, osp_device::opd_storage, osp_thandle::ot_storage_th, thandle::th_top, thandle_get_sub_by_dt(), and thandle_to_osp_thandle().
Referenced by osp_declare_object_create(), and osp_object_create().
int osp_insert_async_request (const struct lu_env * env, enum update_type op, struct osp_object * obj, int count, __u16 * lens, const void ** bufs, void * data, __u32 repsize, osp_update_interpreter_t interpreter)
Insert an asynchronous idempotent request to the shared request queue that is attached to the osp_device.
This function generates a new osp_async_request with the given parameters, then tries to insert the request into the osp_device-based shared request queue. If the queue is full, then triggers the packaged OUT RPC to purge the shared queue firstly, and then re-tries.
NOTE: must hold the osp::opd_async_requests_mutex to serialize concurrent osp_insert_async_request call from others.
Parameters:
[in] env pointer to the thread context
[in] op operation type, see 'enum update_type'
[in] obj pointer to the operation target
[in] count array size of the subsequent lens and bufs
[in] lens buffer length array for the subsequent bufs
[in] bufs the buffers to compose the request
[in] data pointer to the data used by the interpreter
[in] repsize how many bytes the caller allocated for data
[in] interpreter pointer to the interpreter function
Return values:
0 for success
negative error number on failure
Definition at line 840 of file osp_trans.c.
References ENTRY, lu2osp_dev(), lu_object_fid(), object_update_request_size(), osp_device::opd_async_requests, osp_device::opd_async_requests_mutex, osp2lu_obj(), osp_current_object_update_request(), osp_find_or_create_async_update_request(), osp_insert_update_callback(), osp_unplug_async_request(), osp_update_request::our_update_nr, object_update_request::ourq_count, osp_update_request_sub::ours_req, osp_update_request_sub::ours_req_size, out_update_pack(), RETURN, and update_buffer_get_update().
Referenced by osp_declare_attr_get(), and osp_declare_xattr_get().
int osp_insert_update_callback (const struct lu_env * env, struct osp_update_request * our, struct osp_object * obj, void * data, osp_update_interpreter_t interpreter)
Insert an osp_update_callback into the osp_update_request.
Insert an osp_update_callback to the osp_update_request. Usually each update in the osp_update_request will have one correspondent callback, and these callbacks will be called in rq_interpret_reply.
Parameters:
[in] env pointer to the thread context
[in] obj pointer to the operation target object
[in] data pointer to the data used by the interpreter
[in] interpreter pointer to the interpreter function
Return values:
0 for success
negative error number on failure
Definition at line 799 of file osp_trans.c.
References list_add_tail(), osp_update_callback_init(), osp_update_callback::ouc_list, osp_update_request::our_cb_items, and RETURN.
Referenced by osp_insert_async_request(), osp_md_object_create(), and osp_md_object_destroy().
void osp_invalidate_request (struct osp_device * osp)
Invalidate update request.
Invalidate update request in the OSP sending list, so all of requests in the sending list will return error, which happens when it finds one update (with writing llog) requests fails or the OSP is evicted by remote target. see osp_send_update_thread().
Parameters:
[in] osp OSP device whose update requests will be invalidated.
Definition at line 1354 of file osp_trans.c.
References CDEBUG, CERROR, D_HA, dt_device::dd_lu_dev, ENTRY, INIT_LIST_HEAD, lu_device::ld_type, lu_device_type::ldt_ctx_tags, list, list_del_init(), list_for_each_entry_safe, LIST_HEAD(), list_move(), lu_env_fini(), lu_env_init(), obd_device::obd_name, osp_device::opd_dt_dev, osp_device::opd_obd, osp_device::opd_update, osp_thandle_put(), osp_trans_callback(), osp_thandle::ot_super, osp_updates::ou_list, osp_updates::ou_lock, osp_updates::ou_rpc_version, osp_update_request::our_list, osp_update_request::our_list_lock, osp_update_request::our_req_ready, osp_update_request::our_th, osp_update_request::our_version, and thandle::th_result.
Referenced by osp_import_event(), and osp_send_update_thread().
int osp_object_update_request_create (struct osp_update_request * our, size_t size)
Allocate new update request.
Allocate new update request and insert it to the req_update_list.
Parameters:
[in] our osp_udate_request where to create a new update request
Return values:
0 if creation succeeds.
negative errno if creation fails.
Definition at line 125 of file osp_trans.c.
References INIT_LIST_HEAD, list_add_tail(), OBD_ALLOC_PTR, OBD_FREE_PTR, object_update_request_alloc(), osp_update_request::our_req_list, osp_update_request::our_req_nr, osp_update_request_sub::ours_list, osp_update_request_sub::ours_req, osp_update_request_sub::ours_req_size, and OUT_UPDATE_INIT_BUFFER_SIZE.
Referenced by osp_update_request_create().
int osp_prep_inline_update_req (const struct lu_env * env, struct ptlrpc_request * req, struct osp_update_request * our, int repsize)
Prepare inline update request.
Prepare OUT update ptlrpc inline request, and the request usually includes one update buffer, which does not need bulk transfer.
Parameters:
[in] env execution environment
[in] req ptlrpc request
[in] ours sub osp_update_request to be packed
Return values:
0 if packing succeeds
negative errno if packing fails
Definition at line 262 of file osp_trans.c.
References list_entry, LUSTRE_MDS_VERSION, list_head::next, object_update_request_size(), OSC_REPLY_PORTAL, out_update_header::ouh_count, out_update_header::ouh_inline_data, out_update_header::ouh_inline_length, out_update_header::ouh_magic, out_update_header::ouh_reply_size, osp_update_request::our_req_list, osp_update_request_sub::ours_req, OUT_PORTAL, OUT_UPDATE, OUT_UPDATE_HEADER_MAGIC, ptlrpc_request_pack(), ptlrpc_request_set_replen(), RCL_CLIENT, RCL_SERVER, req_capsule_client_get(), req_capsule_set_size(), RETURN, RMF_OUT_UPDATE_HEADER, RMF_OUT_UPDATE_REPLY, and ptlrpc_request::rq_pill.
Referenced by osp_prep_update_req().
int osp_prep_update_req (const struct lu_env * env, struct obd_import * imp, struct osp_update_request * our, struct ptlrpc_request ** reqp)
Prepare update request.
Prepare OUT update ptlrpc request, and the request usually includes all of updates (stored in
Parameters:
ureq) from one operation.
[in] env execution environment
[in] imp import on which ptlrpc request will be sent
[in] ureq hold all of updates which will be packed into the req
[in] reqp request to be created
Return values:
0 if preparation succeeds.
negative errno if preparation fails.
Definition at line 314 of file osp_trans.c.
References ptlrpc_bulk_frag_ops::add_iov_frag, ptlrpc_bulk_desc::bd_frag_ops, CDEBUG, D_INFO, D_OTHER, ENTRY, GOTO, LASSERT, list_entry, list_for_each_entry, LNET_MTU_BITS, LUSTRE_MDS_VERSION, MD_MAX_BRW_SIZE, MDS_BULK_PORTAL, list_head::next, object_update_request_dump(), object_update_request_get(), object_update_request_size(), OSC_REPLY_PORTAL, osp_prep_inline_update_req(), object_update::ou_result_size, out_update_buffer::oub_size, out_update_header::ouh_count, out_update_header::ouh_inline_length, out_update_header::ouh_magic, out_update_header::ouh_reply_size, osp_update_request::our_req_list, osp_update_request::our_update_nr, object_update_reply::ourp_lens, object_update_request::ourq_count, osp_update_request_sub::ours_req, osp_update_request_sub::ours_req_size, OUT_PORTAL, OUT_UPDATE, OUT_UPDATE_HEADER_MAGIC, OUT_UPDATE_MAX_INLINE_SIZE, OUT_UPDATE_REPLY_SIZE, PTLRPC_BULK_BUF_KVEC, PTLRPC_BULK_GET_SOURCE, ptlrpc_bulk_kvec_ops, ptlrpc_prep_bulk_imp(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), RCL_CLIENT, RCL_SERVER, req_capsule_client_get(), req_capsule_set_size(), RETURN, RMF_OUT_UPDATE_BUF, RMF_OUT_UPDATE_HEADER, RMF_OUT_UPDATE_REPLY, ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_pill, RQF_OUT_UPDATE, and size.
Referenced by osp_md_read(), osp_remote_sync(), osp_send_update_req(), and osp_unplug_async_request().
int osp_remote_sync (const struct lu_env * env, struct osp_device * osp, struct osp_update_request * our, struct ptlrpc_request ** reqp)
Send update RPC.
Send update request to the remote MDT synchronously.
Parameters:
[in] env execution environment
[in] imp import on which ptlrpc request will be sent
[in] our hold all of updates which will be packed into the req
[in] reqp request to be created
Return values:
0 if RPC succeeds.
negative errno if RPC fails.
Definition at line 442 of file osp_trans.c.
References client_obd::cl_import, obd_device::cli, ENTRY, osp_device::opd_obd, osp_prep_update_req(), osp_update_request::our_rc, ptlrpc_queue_wait(), ptlrpc_req_finished(), RETURN, ptlrpc_request::rq_allow_intr, ptlrpc_request::rq_allow_replay, and obd_device::u.
Referenced by osp_attr_get(), osp_md_index_lookup(), and osp_xattr_get().
static void osp_request_commit_cb (struct ptlrpc_request * req) [static]
Definition at line 1019 of file osp_trans.c.
References __u64, CDEBUG, D_HA, ENTRY, EXIT, obd_import::imp_peer_committed_transno, LPU64, lustre_msg_get_last_committed(), osp_thandle_put(), osp_trans_commit_cb(), RETURN_EXIT, ptlrpc_request::rq_committed, ptlrpc_request::rq_import, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_status, ptlrpc_request::rq_transno, and thandle_to_osp_thandle().
Referenced by osp_send_update_req().
static int osp_send_update_req (const struct lu_env * env, struct osp_device * osp, struct osp_update_request * our) [static]
Send the request for remote updates.
Send updates to the remote MDT. Prepare the request by osp_update_req and send them to remote MDT, for sync request, it will wait until the reply return, otherwise hand it to ptlrpcd.
Please refer to osp_trans_create() for transaction type.
Parameters:
[in] env pointer to the thread context
[in] osp pointer to the OSP device
[in] our pointer to the osp_update_request
Return values:
0 for success
negative error number on failure
Definition at line 1104 of file osp_trans.c.
References client_obd::cl_import, obd_device::cli, dt_device::dd_lu_dev, ENTRY, GOTO, LASSERT, lu_device::ld_obd, lu_device::ld_site, lu_site::ls_top_dev, osp_update_args::oaua_count, osp_update_args::oaua_flow_control, osp_update_args::oaua_update, osp_update_args::oaua_update_env, osp_update_args::oaua_waitq, obd_get_request_slot(), obd_device::obd_recovering, osp_device::opd_async_updates_count, osp_device::opd_async_updates_rwsem, osp_device::opd_connect_mdt, osp_device::opd_dt_dev, osp_device::opd_imp_active, osp_device::opd_imp_connected, osp_device::opd_obd, osp_device::opd_syn_barrier_waitq, osp_get_rpc_lock(), osp_prep_update_req(), osp_put_rpc_lock(), osp_request_commit_cb(), osp_thandle_get(), osp_thandle_put(), osp_trans_callback(), osp_update_interpret(), osp_thandle::ot_super, osp_update_request::our_th, ptlrpc_queue_wait(), ptlrpc_req_async_args, ptlrpc_req_finished(), ptlrpcd_add_req(), RETURN, ptlrpc_request::rq_allow_replay, ptlrpc_request::rq_committed, ptlrpc_request::rq_status, ptlrpc_request::rq_transno, thandle::th_sync, thandle::th_wait_submit, and obd_device::u.
Referenced by osp_send_update_thread(), and osp_trans_stop().
int osp_send_update_thread (void * arg)
Sending update thread.
Create thread to send update request to other MDTs, this thread will pull out update request from the list in OSP by version number, i.e. it will make sure the update request with lower version number will be sent first.
Parameters:
[in] arg hold the OSP device.
Return values:
0 if the thread is created successfully. negative error if the thread is not created successfully.
Definition at line 1423 of file osp_trans.c.
References CERROR, dt_device::dd_lu_dev, ENTRY, l_wait_event, LASSERT, lu_device::ld_type, lu_device_type::ldt_ctx_tags, lu_env_fini(), lu_env_init(), OBD_FAIL_CHECK, OBD_FAIL_INVALIDATE_UPDATE, obd_device::obd_name, osp_device::opd_dt_dev, osp_device::opd_obd, osp_device::opd_update, osp_device::opd_update_thread, osp_get_next_request(), osp_invalidate_request(), osp_send_update_req(), osp_send_update_thread_running(), osp_thandle_put(), osp_trans_callback(), osp_thandle::ot_super, osp_updates::ou_lock, osp_updates::ou_rpc_version, osp_updates::ou_waitq, osp_update_request::our_th, osp_update_request::our_version, RETURN, SVC_RUNNING, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, ptlrpc_thread::t_flags, thandle::th_result, and thread.
Referenced by osp_update_init().
void osp_thandle_destroy (struct osp_thandle * oth)
Definition at line 919 of file osp_trans.c.
References LASSERT, list_empty(), OBD_FREE_PTR, OSP_THANDLE_MAGIC, osp_update_request_destroy(), osp_thandle::ot_commit_dcb_list, osp_thandle::ot_magic, osp_thandle::ot_our, and osp_thandle::ot_stop_dcb_list.
Referenced by osp_thandle_put().
static void osp_thandle_invalidate_object (const struct lu_env * env, struct osp_thandle * oth) [static]
Invalidate all objects in the osp thandle.
invalidate all of objects in the update request, which will be called when the transaction is aborted.
Parameters:
[in] oth osp thandle.
Definition at line 481 of file osp_trans.c.
References dt_device::dd_lu_dev, fid_is_sane(), lu_attr::la_valid, list_for_each_entry, lu2osp_obj(), lu_object_find_slice(), lu_object_put(), object_update_request_get(), osp_object_attr::ooa_attr, osp_object::opo_lock, osp_object::opo_ooa, osp_object::opo_stale, osp_obj(), osp_thandle::ot_our, osp_thandle::ot_super, object_update::ou_fid, object_update::ou_type, osp_update_request::our_req_list, object_update_request::ourq_count, osp_update_request_sub::ours_list, osp_update_request_sub::ours_req, OUT_WRITE, and thandle::th_dev.
Referenced by osp_trans_stop_cb().
void osp_trans_callback (const struct lu_env * env, struct osp_thandle * oth, int rc)
callback of osp transaction
Call all of callbacks for this osp thandle. This will only be called in error handler path. In the normal processing path, these callback will be called in osp_request_commit_cb() and osp_update_interpret().
Parameters:
[in] env execution environment
[in] oth osp thandle
[in] rc result of the osp thandle
Definition at line 1067 of file osp_trans.c.
References list_del_init(), list_for_each_entry_safe, osp_trans_commit_cb(), osp_trans_stop_cb(), osp_update_callback_fini(), osp_thandle::ot_our, osp_update_callback::ouc_data, osp_update_callback::ouc_interpreter, osp_update_callback::ouc_list, osp_update_callback::ouc_obj, and osp_update_request::our_cb_items.
Referenced by osp_invalidate_request(), osp_send_update_req(), osp_send_update_thread(), osp_trans_stop(), and osp_update_fini().
int osp_trans_cb_add (struct thandle * th, struct dt_txn_commit_cb * dcb)
Add commit callback to transaction.
Add commit callback to the osp thandle, which will be called when the thandle is committed remotely.
Parameters:
[in] th the thandle
[in] dcb commit callback structure
Return values:
only return 0 for now.
Definition at line 989 of file osp_trans.c.
References dt_txn_commit_cb::dcb_flags, dt_txn_commit_cb::dcb_func, dt_txn_commit_cb::dcb_linkage, dt_txn_commit_cb::dcb_magic, DCB_TRANS_STOP, LASSERT, list_add(), osp_thandle::ot_commit_dcb_list, osp_thandle::ot_stop_dcb_list, thandle_to_osp_thandle(), and TRANS_COMMIT_CB_MAGIC.
static void osp_trans_commit_cb (struct osp_thandle * oth, int result) [static]
Definition at line 1002 of file osp_trans.c.
References dt_txn_commit_cb::dcb_func, dt_txn_commit_cb::dcb_linkage, dt_txn_commit_cb::dcb_magic, dt_txn_commit_cb::dcb_name, LASSERT, LASSERTF, list_del_init(), list_for_each_entry_safe, osp_thandle::ot_commit_dcb_list, osp_thandle::ot_refcount, osp_thandle::ot_super, and TRANS_COMMIT_CB_MAGIC.
Referenced by osp_request_commit_cb(), and osp_trans_callback().
struct thandle* osp_trans_create (const struct lu_env * env, struct dt_device * d) [read]
The OSP layer dt_device_operations::dt_trans_create() interface to create a transaction.
There are two kinds of transactions that will involve OSP:
1) If the transaction only contains the updates on remote server (MDT or OST), such as re-generating the lost OST-object for LFSCK, then it is a remote transaction. For remote transaction, the upper layer caller (such as the LFSCK engine) will call the dt_trans_create() (with the OSP dt_device as the parameter), then the call will be directed to the osp_trans_create() that creates the transaction handler and returns it to the caller.
2) If the transcation contains both local and remote updates, such as cross MDTs create under DNE mode, then the upper layer caller will not trigger osp_trans_create(). Instead, it will call dt_trans_create() on other dt_device, such as LOD that will generate the transaction handler. Such handler will be used by the whole transaction in subsequent sub-operations.
Parameters:
[in] env pointer to the thread context
[in] d pointer to the OSP dt_device
Return values:
pointer to the transaction handler
negative error number on failure
Definition at line 956 of file osp_trans.c.
References ENTRY, INIT_LIST_HEAD, LCT_TX_HANDLE, OBD_ALLOC_PTR, OSP_THANDLE_MAGIC, osp_thandle::ot_commit_dcb_list, osp_thandle::ot_magic, osp_thandle::ot_refcount, osp_thandle::ot_stop_dcb_list, osp_thandle::ot_super, RETURN, thandle::th_dev, thandle::th_tags, and unlikely.
int osp_trans_start (const struct lu_env * env, struct dt_device * dt, struct thandle * th)
The OSP layer dt_device_operations::dt_trans_start() interface to start the transaction.
If the transaction is a remote transaction, then related remote updates will be triggered in the osp_trans_stop(). Please refer to osp_trans_create() for transaction type.
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the OSP dt_device
[in] th pointer to the transaction handler
Return values:
0 for success
negative error number on failure
Definition at line 1509 of file osp_trans.c.
References dt_trans_start(), is_only_remote_trans(), osp_thandle::ot_our, osp_thandle::ot_storage_th, osp_thandle::ot_super, osp_update_request::our_flags, thandle::th_dev, thandle::th_sync, thandle_to_osp_thandle(), and UPDATE_FL_SYNC.
int osp_trans_stop (const struct lu_env * env, struct dt_device * dt, struct thandle * th)
The OSP layer dt_device_operations::dt_trans_stop() interface to stop the transaction.
If the transaction is a remote transaction, related remote updates will be triggered at the end of this function.
For synchronous mode update or any failed update, the request will be destroyed explicitly when the osp_trans_stop().
Please refer to osp_trans_create() for transaction type.
Parameters:
[in] env pointer to the thread context
[in] dt pointer to the OSP dt_device
[in] th pointer to the transaction handler
Return values:
0 for success
negative error number on failure
Definition at line 1542 of file osp_trans.c.
References CDEBUG, D_HA, dt2osp_dev(), dt_trans_stop(), ENTRY, GOTO, LASSERT, likely, list_empty(), LPU64, obd_device::obd_name, osp_device::opd_connect_mdt, osp_device::opd_obd, osp_device::opd_update, osp_send_update_req(), osp_send_update_thread_running(), osp_thandle_put(), osp_trans_callback(), osp_thandle::ot_our, osp_thandle::ot_storage_th, osp_updates::ou_waitq, osp_update_request::our_list, osp_update_request::our_list_lock, osp_update_request::our_req_list, osp_update_request::our_req_ready, osp_update_request::our_version, RETURN, thandle::th_dev, thandle::th_result, thandle::th_top, and thandle_to_osp_thandle().
static void osp_trans_stop_cb (const struct lu_env * env, struct osp_thandle * oth, int result) [static]
Definition at line 527 of file osp_trans.c.
References dt_txn_commit_cb::dcb_func, dt_txn_commit_cb::dcb_linkage, dt_txn_commit_cb::dcb_magic, dt_txn_commit_cb::dcb_name, LASSERTF, list_del_init(), list_for_each_entry_safe, osp_thandle_invalidate_object(), osp_thandle::ot_stop_dcb_list, osp_thandle::ot_super, and TRANS_COMMIT_CB_MAGIC.
Referenced by osp_trans_callback(), and osp_update_interpret().
int osp_trans_update_request_create (struct thandle * th)
Definition at line 899 of file osp_trans.c.
References osp_update_request_create(), osp_thandle::ot_our, osp_update_request::our_th, thandle::th_dev, thandle::th_result, and thandle_to_osp_thandle().
Referenced by osp_declare_xattr_del(), osp_declare_xattr_set(), osp_md_declare_attr_set(), osp_md_declare_index_delete(), osp_md_declare_index_insert(), osp_md_declare_object_create(), osp_md_declare_object_destroy(), osp_md_declare_ref_add(), osp_md_declare_ref_del(), and osp_md_declare_write().
int osp_unplug_async_request (const struct lu_env * env, struct osp_device * osp, struct osp_update_request * our)
Pack all the requests in the shared asynchronous idempotent request queue into a single OUT RPC that will be given to the background ptlrpcd daemon.
Parameters:
[in] env pointer to the thread context
[in] osp pointer to the OSP device
[in] our pointer to the shared queue
Return values:
0 for success
negative error number on failure
Definition at line 714 of file osp_trans.c.
References client_obd::cl_import, obd_device::cli, list_del_init(), list_for_each_entry_safe, osp_update_args::oaua_count, osp_update_args::oaua_flow_control, osp_update_args::oaua_update, osp_update_args::oaua_update_env, osp_update_args::oaua_waitq, osp_device::opd_obd, osp_prep_update_req(), osp_update_callback_fini(), osp_update_interpret(), osp_update_request_destroy(), osp_update_callback::ouc_data, osp_update_callback::ouc_interpreter, osp_update_callback::ouc_list, osp_update_callback::ouc_obj, osp_update_request::our_cb_items, ptlrpc_req_async_args, ptlrpcd_add_req(), and obd_device::u.
Referenced by osp_declare_xattr_get(), and osp_insert_async_request().
static void osp_update_callback_fini (const struct lu_env * env, struct osp_update_callback * ouc) [static]
Destroy the osp_update_callback.
Parameters:
[in] env pointer to the thread context
[in] ouc pointer to osp_update_callback
Definition at line 582 of file osp_trans.c.
References LASSERT, list_empty(), lu_object_put(), OBD_FREE_PTR, osp2lu_obj(), osp_update_callback::ouc_list, and osp_update_callback::ouc_obj.
Referenced by osp_trans_callback(), osp_unplug_async_request(), and osp_update_interpret().
static struct osp_update_callback* osp_update_callback_init (struct osp_object * obj, void * data, osp_update_interpreter_t interpreter) [static, read]
Allocate an osp request and initialize it with the given parameters.
Parameters:
[in] obj pointer to the operation target
[in] data pointer to the data used by the interpreter
[in] interpreter pointer to the interpreter function
Return values:
pointer to the asychronous request
NULL if the allocation failed
Definition at line 558 of file osp_trans.c.
References INIT_LIST_HEAD, lu_object_get(), OBD_ALLOC_PTR, osp2lu_obj(), osp_update_callback::ouc_data, osp_update_callback::ouc_interpreter, osp_update_callback::ouc_list, and osp_update_callback::ouc_obj.
Referenced by osp_insert_update_callback().
static int osp_update_interpret (const struct lu_env * env, struct ptlrpc_request * req, void * arg, int rc) [static]
Interpret the packaged OUT RPC results.
For every packaged sub-request, call its registered interpreter function. Then destroy the sub-request.
Parameters:
[in] env pointer to the thread context
[in] req pointer to the RPC
[in] arg pointer to data used by the interpreter
[in] rc the RPC return value
Return values:
0 for success
negative error number on failure
Definition at line 605 of file osp_trans.c.
References obd_device::cli, dt2osp_dev(), ENTRY, LASSERT, list_del_init(), list_for_each_entry_safe, osp_update_args::oaua_count, osp_update_args::oaua_flow_control, osp_update_args::oaua_update, osp_update_args::oaua_update_env, osp_update_args::oaua_waitq, obd_put_request_slot(), object_update_result_get(), osp_device::opd_obd, osp_thandle_put(), osp_trans_stop_cb(), osp_update_callback_fini(), osp_update_request_destroy(), osp_thandle::ot_super, osp_update_callback::ouc_data, osp_update_callback::ouc_interpreter, osp_update_callback::ouc_list, osp_update_callback::ouc_obj, osp_update_request::our_cb_items, object_update_result::our_rc, osp_update_request::our_th, object_update_reply::ourp_count, object_update_reply::ourp_magic, OUT_UPDATE_REPLY_SIZE, req_capsule_server_sized_get(), RETURN, RMF_OUT_UPDATE_REPLY, ptlrpc_request::rq_pill, ptlrpc_request::rq_replied, ptlrpc_request::rq_repmsg, thandle::th_dev, obd_device::u, and UPDATE_REPLY_MAGIC.
Referenced by osp_send_update_req(), and osp_unplug_async_request().
struct osp_update_request* osp_update_request_create (struct dt_device * dt) [read]
Allocate and initialize osp_update_request.
osp_update_request is being used to track updates being executed on this dt_device(OSD or OSP). The update buffer will be 4k initially, and increased if needed.
Parameters:
[in] dt dt device
Return values:
osp_update_request being allocated if succeed
ERR_PTR(errno) if failed
Definition at line 187 of file osp_trans.c.
References INIT_LIST_HEAD, OBD_ALLOC_PTR, osp_object_update_request_create(), osp_update_request::our_cb_items, osp_update_request::our_list, osp_update_request::our_list_lock, osp_update_request::our_req_list, and OUT_UPDATE_INIT_BUFFER_SIZE.
Referenced by osp_attr_get(), osp_find_or_create_async_update_request(), osp_md_index_lookup(), osp_md_read(), osp_trans_update_request_create(), and osp_xattr_get().
void osp_update_request_destroy (struct osp_update_request * our)
Definition at line 204 of file osp_trans.c.
References list_del(), list_for_each_entry_safe, OBD_FREE_LARGE, OBD_FREE_PTR, osp_update_request::our_req_list, osp_update_request_sub::ours_list, osp_update_request_sub::ours_req, and osp_update_request_sub::ours_req_size.
Referenced by osp_attr_get(), osp_device_fini(), osp_md_index_lookup(), osp_md_read(), osp_thandle_destroy(), osp_unplug_async_request(), osp_update_interpret(), and osp_xattr_get().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.