Lustre: lustre/ost/ost_handler.c File Reference
lustre/ost/ost_handler.c File Reference
#include <linux/module.h>
#include <lustre_dlm.h>
#include <lprocfs_status.h>
#include <obd_class.h>
#include "ost_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_OST
#define OST_WATCHDOG_TIMEOUT (obd_timeout * 1000)
Functions
module_param (oss_max_threads, int, 0444)
MODULE_PARM_DESC (oss_max_threads,"maximum number of OSS service threads")
module_param (oss_num_threads, int, 0444)
MODULE_PARM_DESC (oss_num_threads,"number of OSS service threads to start")
module_param (ost_num_threads, int, 0444)
MODULE_PARM_DESC (ost_num_threads,"number of OST service threads to start (deprecated)")
module_param (oss_num_create_threads, int, 0444)
MODULE_PARM_DESC (oss_num_create_threads,"number of OSS create threads to start")
module_param (oss_cpts, charp, 0444)
MODULE_PARM_DESC (oss_cpts,"CPU partitions OSS threads should run on")
module_param (oss_io_cpts, charp, 0444)
MODULE_PARM_DESC (oss_io_cpts,"CPU partitions OSS IO threads should run on")
static int ost_setup (struct obd_device *obd, struct lustre_cfg *lcfg)
static int ost_cleanup (struct obd_device *obd)
static int ost_health_check (const struct lu_env *env, struct obd_device *obd)
static int __init ost_init (void)
static void __exit ost_exit (void)
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Object Storage Target (OST)")
MODULE_VERSION (LUSTRE_VERSION_STRING)
MODULE_LICENSE ("GPL")
module_init (ost_init)
module_exit (ost_exit)
Variables
int oss_max_threads = 512
static int oss_num_threads
static int ost_num_threads
static int oss_num_create_threads
static char * oss_cpts
static char * oss_io_cpts
static struct cfs_cpt_table * ost_io_cptable
static struct obd_ops ost_obd_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_OST
Definition at line 42 of file ost_handler.c.
#define OST_WATCHDOG_TIMEOUT (obd_timeout * 1000)
Definition at line 74 of file ost_handler.c.
Function Documentation
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Object Storage Target (OST)")
module_exit (ost_exit)
module_init (ost_init)
MODULE_LICENSE ("GPL")
module_param (oss_io_cpts , charp , 0444)
module_param (oss_cpts , charp , 0444)
module_param (oss_num_create_threads , int , 0444)
module_param (ost_num_threads , int , 0444)
module_param (oss_num_threads , int , 0444)
module_param (oss_max_threads , int , 0444)
MODULE_PARM_DESC (oss_io_cpts , "CPU partitions OSS IO threads should run on")
MODULE_PARM_DESC (oss_cpts , "CPU partitions OSS threads should run on")
MODULE_PARM_DESC (oss_num_create_threads , "number of OSS create threads to start")
MODULE_PARM_DESC (ost_num_threads , "number of OST service threads to start (deprecated)")
MODULE_PARM_DESC (oss_num_threads , "number of OSS service threads to start")
MODULE_PARM_DESC (oss_max_threads , "maximum number of OSS service threads")
MODULE_VERSION (LUSTRE_VERSION_STRING)
static int ost_cleanup (struct obd_device * obd) [static]
Definition at line 356 of file ost_handler.c.
References cfs_cpt_table_free(), ENTRY, LASSERT, lprocfs_obd_cleanup(), obd_device::obd_recovering, ost_obd::ost_create_service, ost_obd::ost_health_mutex, ost_obd::ost_io_service, ost_obd::ost_out_service, ost_obd::ost_seq_service, ost_obd::ost_service, ping_evictor_stop(), ptlrpc_unregister_service(), RETURN, and obd_device::u.
static void __exit ost_exit (void) [static]
Definition at line 435 of file ost_handler.c.
References class_unregister_type(), and LUSTRE_OSS_NAME.
static int ost_health_check (const struct lu_env * env, struct obd_device * obd) [static]
Definition at line 392 of file ost_handler.c.
References ost_obd::ost_create_service, ost_obd::ost_health_mutex, ost_obd::ost_io_service, ost_obd::ost_seq_service, ost_obd::ost_service, ptlrpc_service_health_check(), and obd_device::u.
static int __init ost_init (void) [static]
Definition at line 416 of file ost_handler.c.
References class_register_type(), ENTRY, LCONSOLE_INFO, LUSTRE_OSS_NAME, oss_num_threads, ost_num_threads, and RETURN.
static int ost_setup (struct obd_device * obd, struct lustre_cfg * lcfg) [static]
Definition at line 89 of file ost_handler.c.
References CERROR, CFS_CPT_ANY, cfs_cpt_nodemask(), cfs_cpt_number(), cfs_cpt_set_node(), cfs_cpt_table_alloc(), cfs_cpt_table_free(), CWARN, ENTRY, GOTO, LCT_DT_THREAD, LCT_MD_THREAD, lprocfs_obd_cleanup(), lprocfs_obd_setup(), LUSTRE_OSS_NAME, obd_device::obd_proc_entry, obd_device::obd_vars, OSC_REPLY_PORTAL, oss_cpts, OSS_CR_NTHRS_BASE, OSS_CR_NTHRS_INIT, OSS_CR_NTHRS_MAX, OSS_CR_THR_FACTOR, oss_io_cpts, oss_max_threads, OSS_NTHRS_BASE, OSS_NTHRS_INIT, oss_num_create_threads, oss_num_threads, OSS_SERVICE_WATCHDOG_FACTOR, OSS_THR_FACTOR, OST_BUFSIZE, OST_CREATE_PORTAL, ost_obd::ost_create_service, ost_obd::ost_health_mutex, OST_IO_BUFSIZE, OST_IO_MAXREPSIZE, OST_IO_MAXREQSIZE, OST_IO_PORTAL, ost_obd::ost_io_service, OST_MAXREPSIZE, OST_MAXREQSIZE, OST_NBUFS, ost_obd::ost_out_service, OST_REQUEST_PORTAL, ost_obd::ost_seq_service, ost_obd::ost_service, OUT_BUFSIZE, out_create(), OUT_MAXREPSIZE, OUT_MAXREQSIZE, OUT_PORTAL, ping_evictor_start(), ptlrpc_service_conf::psc_name, ptlrpc_hpreq_handler(), ptlrpc_register_service(), ptlrpc_unregister_service(), RETURN, SEQ_DATA_PORTAL, target_print_req, tgt_hpreq_handler(), tgt_io_thread_done(), tgt_io_thread_init(), tgt_request_handle(), and obd_device::u.
Variable Documentation
char* oss_cpts [static]
Definition at line 66 of file ost_handler.c.
Referenced by ost_setup().
char* oss_io_cpts [static]
Definition at line 70 of file ost_handler.c.
Referenced by ost_setup().
int oss_max_threads = 512
Definition at line 50 of file ost_handler.c.
Referenced by ost_setup().
int oss_num_create_threads [static]
Definition at line 62 of file ost_handler.c.
Referenced by ost_setup().
int oss_num_threads [static]
Definition at line 54 of file ost_handler.c.
Referenced by ost_init(), and ost_setup().
struct cfs_cpt_table* ost_io_cptable [static]
Definition at line 76 of file ost_handler.c.
int ost_num_threads [static]
Definition at line 58 of file ost_handler.c.
Referenced by ost_init().
struct obd_ops ost_obd_ops [static]
Initial value:
 {
        .o_owner        = THIS_MODULE,
        .o_setup        = ost_setup,
        .o_cleanup      = ost_cleanup,
        .o_health_check = ost_health_check,
}
Definition at line 408 of file ost_handler.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.