Lustre: lustre/target/out_lib.c File Reference
lustre/target/out_lib.c File Reference
#include <lu_target.h>
#include <lustre_obdo.h>
#include <lustre_update.h>
#include <md_object.h>
#include <obd.h>
#include <obd_class.h>
#include "tgt_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_CLASS
#define TX_ALLOC_STEP 8
Functions
const char * update_op_str (__u16 opc)
int out_update_header_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, enum update_type update_op, const struct lu_fid *fid, unsigned int param_count, __u16 *param_sizes, __u32 reply_size)
Fill object update header.
int out_update_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, enum update_type op, const struct lu_fid *fid, unsigned int param_count, __u16 *param_sizes, const void **param_bufs, __u32 reply_size)
Packs one update into the update_buffer.
int out_create_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, const struct lu_fid *fid, const struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof)
Pack various updates into the update_buffer.
int out_ref_del_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, const struct lu_fid *fid)
int out_ref_add_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, const struct lu_fid *fid)
int out_attr_set_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, const struct lu_fid *fid, const struct lu_attr *attr)
int out_xattr_set_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, const struct lu_fid *fid, const struct lu_buf *buf, const char *name, __u32 flag)
int out_xattr_del_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, const struct lu_fid *fid, const char *name)
int out_index_insert_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, const struct lu_fid *fid, const struct dt_rec *rec, const struct dt_key *key)
int out_index_delete_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, const struct lu_fid *fid, const struct dt_key *key)
int out_object_destroy_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, const struct lu_fid *fid)
int out_write_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, const struct lu_fid *fid, const struct lu_buf *buf, __u64 pos)
int out_index_lookup_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, const struct lu_fid *fid, struct dt_rec *rec, const struct dt_key *key)
Pack various readonly updates into the update_buffer.
int out_attr_get_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, const struct lu_fid *fid)
int out_xattr_get_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, const struct lu_fid *fid, const char *name, const int bufsize)
int out_read_pack (const struct lu_env *env, struct object_update *update, size_t *max_update_size, const struct lu_fid *fid, size_t size, loff_t pos)
static int tx_extend_args (struct thandle_exec_args *ta, int new_alloc_ta)
struct tx_arg * tx_add_exec (struct thandle_exec_args *ta, tx_exec_func_t func, tx_exec_func_t undo, const char *file, int line)
static int out_obj_destroy (const struct lu_env *env, struct dt_object *dt_obj, struct thandle *th)
static int out_tx_create_undo (const struct lu_env *env, struct thandle *th, struct tx_arg *arg)
All of the xxx_undo will be used once execution failed, But because all of the required resource has been reserved in declare phase, i.e.
int out_tx_create_exec (const struct lu_env *env, struct thandle *th, struct tx_arg *arg)
int out_create_add_exec (const struct lu_env *env, struct dt_object *obj, struct lu_attr *attr, struct lu_fid *parent_fid, struct dt_object_format *dof, struct thandle_exec_args *ta, struct thandle *th, struct object_update_reply *reply, int index, const char *file, int line)
Add create update to thandle.
static int out_tx_attr_set_undo (const struct lu_env *env, struct thandle *th, struct tx_arg *arg)
static int out_tx_attr_set_exec (const struct lu_env *env, struct thandle *th, struct tx_arg *arg)
int out_attr_set_add_exec (const struct lu_env *env, struct dt_object *dt_obj, const struct lu_attr *attr, struct thandle_exec_args *ta, struct thandle *th, struct object_update_reply *reply, int index, const char *file, int line)
static int out_tx_write_exec (const struct lu_env *env, struct thandle *th, struct tx_arg *arg)
int out_write_add_exec (const struct lu_env *env, struct dt_object *dt_obj, const struct lu_buf *buf, loff_t pos, struct thandle_exec_args *ta, struct thandle *th, struct object_update_reply *reply, int index, const char *file, int line)
static int out_tx_xattr_set_exec (const struct lu_env *env, struct thandle *th, struct tx_arg *arg)
int out_xattr_set_add_exec (const struct lu_env *env, struct dt_object *dt_obj, const struct lu_buf *buf, const char *name, int flags, struct thandle_exec_args *ta, struct thandle *th, struct object_update_reply *reply, int index, const char *file, int line)
static int out_tx_xattr_del_exec (const struct lu_env *env, struct thandle *th, struct tx_arg *arg)
int out_xattr_del_add_exec (const struct lu_env *env, struct dt_object *dt_obj, const char *name, struct thandle_exec_args *ta, struct thandle *th, struct object_update_reply *reply, int index, const char *file, int line)
static int out_obj_ref_add (const struct lu_env *env, struct dt_object *dt_obj, struct thandle *th)
static int out_obj_ref_del (const struct lu_env *env, struct dt_object *dt_obj, struct thandle *th)
static int out_tx_ref_add_exec (const struct lu_env *env, struct thandle *th, struct tx_arg *arg)
static int out_tx_ref_add_undo (const struct lu_env *env, struct thandle *th, struct tx_arg *arg)
int out_ref_add_add_exec (const struct lu_env *env, struct dt_object *dt_obj, struct thandle_exec_args *ta, struct thandle *th, struct object_update_reply *reply, int index, const char *file, int line)
static int out_tx_ref_del_exec (const struct lu_env *env, struct thandle *th, struct tx_arg *arg)
static int out_tx_ref_del_undo (const struct lu_env *env, struct thandle *th, struct tx_arg *arg)
int out_ref_del_add_exec (const struct lu_env *env, struct dt_object *dt_obj, struct thandle_exec_args *ta, struct thandle *th, struct object_update_reply *reply, int index, const char *file, int line)
static int out_obj_index_insert (const struct lu_env *env, struct dt_object *dt_obj, const struct dt_rec *rec, const struct dt_key *key, struct thandle *th)
static int out_obj_index_delete (const struct lu_env *env, struct dt_object *dt_obj, const struct dt_key *key, struct thandle *th)
static int out_tx_index_insert_exec (const struct lu_env *env, struct thandle *th, struct tx_arg *arg)
static int out_tx_index_insert_undo (const struct lu_env *env, struct thandle *th, struct tx_arg *arg)
int out_index_insert_add_exec (const struct lu_env *env, struct dt_object *dt_obj, const struct dt_rec *rec, const struct dt_key *key, struct thandle_exec_args *ta, struct thandle *th, struct object_update_reply *reply, int index, const char *file, int line)
static int out_tx_index_delete_exec (const struct lu_env *env, struct thandle *th, struct tx_arg *arg)
static int out_tx_index_delete_undo (const struct lu_env *env, struct thandle *th, struct tx_arg *arg)
int out_index_delete_add_exec (const struct lu_env *env, struct dt_object *dt_obj, const struct dt_key *key, struct thandle_exec_args *ta, struct thandle *th, struct object_update_reply *reply, int index, const char *file, int line)
static int out_tx_destroy_exec (const struct lu_env *env, struct thandle *th, struct tx_arg *arg)
static int out_tx_destroy_undo (const struct lu_env *env, struct thandle *th, struct tx_arg *arg)
int out_destroy_add_exec (const struct lu_env *env, struct dt_object *dt_obj, struct thandle_exec_args *ta, struct thandle *th, struct object_update_reply *reply, int index, const char *file, int line)
Define Documentation
#define DEBUG_SUBSYSTEM S_CLASS
Definition at line 32 of file out_lib.c.
#define TX_ALLOC_STEP 8
Definition at line 467 of file out_lib.c.
Referenced by tx_add_exec().
Function Documentation
int out_attr_get_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, const struct lu_fid * fid)
Definition at line 387 of file out_lib.c.
References OUT_ATTR_GET, and out_update_pack().
int out_attr_set_add_exec (const struct lu_env * env, struct dt_object * dt_obj, const struct lu_attr * attr, struct thandle_exec_args * ta, struct thandle * th, struct object_update_reply * reply, int index, const char * file, int line)
Definition at line 649 of file out_lib.c.
References tx_arg::attr_set, dt_object::do_lu, dt_declare_attr_set(), tx_arg::index, lu_object_get(), tx_arg::object, out_tx_attr_set_exec(), out_tx_attr_set_undo(), tx_arg::reply, tx_add_exec(), and tx_arg::u.
int out_attr_set_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, const struct lu_fid * fid, const struct lu_attr * attr)
Definition at line 249 of file out_lib.c.
References ENTRY, lu_attr::la_valid, lustre_set_wire_obdo(), obdo::o_valid, obdo_from_la(), object_update_param_get(), OUT_ATTR_SET, out_update_header_pack(), RETURN, and size.
int out_create_add_exec (const struct lu_env * env, struct dt_object * obj, struct lu_attr * attr, struct lu_fid * parent_fid, struct dt_object_format * dof, struct thandle_exec_args * ta, struct thandle * th, struct object_update_reply * reply, int index, const char * file, int line)
Add create update to thandle.
Declare create updates and add the update to the thandle updates exec array.
Parameters:
[in] env execution environment
[in] obj object to be created
[in] attr attributes of the creation
[in] parent_fid the fid of the parent
[in] dof dt object format of the creation
[in] ta thandle execuation args where all of updates of the transaction are stored
[in] th thandle for this update
[in] reply reply of the updates
[in] index index of the reply
[in] file the file name where the function is called, which is only for debugging purpose.
[in] line the line number where the funtion is called, which is only for debugging purpose.
Return values:
0 if updates is added successfully.
negative errno if update adding fails.
Definition at line 582 of file out_lib.c.
References tx_arg::create, dt_object::do_lu, dt_declare_create(), tx_arg::index, lu_object_get(), tx_arg::object, out_tx_create_exec(), out_tx_create_undo(), tx_arg::reply, tx_add_exec(), and tx_arg::u.
int out_create_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, const struct lu_fid * fid, const struct lu_attr * attr, struct dt_allocation_hint * hint, struct dt_object_format * dof)
Pack various updates into the update_buffer.
The following functions pack different updates into the update_buffer So parameters of these API is basically same as its correspondent OSD/OSP API, for detail description of these parameters see osd_handler.c or osp_md_object.c.
Parameters:
[in] env execution environment
[in] ubuf update buffer
[in] fid fid of this object for the update
Return values:
0 if insertion succeeds.
negative errno if insertion fails.
Definition at line 188 of file out_lib.c.
References dt_allocation_hint::dah_parent, dt_object::do_lu, ENTRY, fid_cpu_to_le(), lu_attr::la_valid, lu_object_fid(), lustre_set_wire_obdo(), obdo::o_valid, obdo_from_la(), object_update_param_get(), OUT_CREATE, out_update_header_pack(), and RETURN.
int out_destroy_add_exec (const struct lu_env * env, struct dt_object * dt_obj, struct thandle_exec_args * ta, struct thandle * th, struct object_update_reply * reply, int index, const char * file, int line)
Definition at line 1201 of file out_lib.c.
References dt_object::do_lu, dt_declare_destroy(), tx_arg::index, lu_object_get(), tx_arg::object, out_tx_destroy_exec(), out_tx_destroy_undo(), tx_arg::reply, and tx_add_exec().
int out_index_delete_add_exec (const struct lu_env * env, struct dt_object * dt_obj, const struct dt_key * key, struct thandle_exec_args * ta, struct thandle * th, struct object_update_reply * reply, int index, const char * file, int line)
Definition at line 1141 of file out_lib.c.
References dt_object::do_lu, dt_declare_delete(), dt_try_as_dir(), tx_arg::index, tx_arg::insert, LASSERT, lu_object_get(), tx_arg::object, out_tx_index_delete_exec(), out_tx_index_delete_undo(), tx_arg::reply, thandle_exec_args::ta_handle, tx_add_exec(), and tx_arg::u.
int out_index_delete_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, const struct lu_fid * fid, const struct dt_key * key)
Definition at line 321 of file out_lib.c.
References OUT_INDEX_DELETE, out_update_pack(), and size.
int out_index_insert_add_exec (const struct lu_env * env, struct dt_object * dt_obj, const struct dt_rec * rec, const struct dt_key * key, struct thandle_exec_args * ta, struct thandle * th, struct object_update_reply * reply, int index, const char * file, int line)
Definition at line 1078 of file out_lib.c.
References dt_object::do_lu, dt_declare_insert(), dt_try_as_dir(), tx_arg::index, tx_arg::insert, lu_object_get(), tx_arg::object, out_tx_index_insert_exec(), out_tx_index_insert_undo(), tx_arg::reply, tx_add_exec(), and tx_arg::u.
int out_index_insert_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, const struct lu_fid * fid, const struct dt_rec * rec, const struct dt_key * key)
Definition at line 299 of file out_lib.c.
References ARRAY_SIZE, cpu_to_le32, fid_cpu_to_le(), OUT_INDEX_INSERT, out_index_insert_pack(), out_update_pack(), dt_insert_rec::rec_fid, and dt_insert_rec::rec_type.
Referenced by out_index_insert_pack().
int out_index_lookup_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, const struct lu_fid * fid, struct dt_rec * rec, const struct dt_key * key)
Pack various readonly updates into the update_buffer.
The following update funcs are only used by read-only ops, lookup, getattr etc, so it does not need transaction here. Currently they are only used by OSP.
Parameters:
[in] env execution environment
[in] fid fid of this object for the update
[in] ubuf update buffer
Return values:
= 0 pack succeed. < 0 pack failed.
Definition at line 373 of file out_lib.c.
References OUT_INDEX_LOOKUP, out_update_pack(), and size.
static int out_obj_destroy (const struct lu_env * env, struct dt_object * dt_obj, struct thandle * th) [static]
Definition at line 496 of file out_lib.c.
References CDEBUG, D_INFO, DFID, dt_object::do_lu, dt_destroy(), dt_obd_name(), dt_write_lock(), dt_write_unlock(), lu_object_fid(), MOR_TGT_CHILD, PFID, and thandle::th_dev.
Referenced by out_tx_create_undo(), and out_tx_destroy_exec().
static int out_obj_index_delete (const struct lu_env * env, struct dt_object * dt_obj, const struct dt_key * key, struct thandle * th) [static]
Definition at line 1029 of file out_lib.c.
References CDEBUG, D_INFO, DFID, dt_object::do_lu, dt_delete(), dt_obd_name(), dt_try_as_dir(), dt_write_lock(), dt_write_unlock(), lu_object_fid(), MOR_TGT_CHILD, PFID, and thandle::th_dev.
Referenced by out_tx_index_delete_exec(), and out_tx_index_insert_undo().
static int out_obj_index_insert (const struct lu_env * env, struct dt_object * dt_obj, const struct dt_rec * rec, const struct dt_key * key, struct thandle * th) [static]
Definition at line 1006 of file out_lib.c.
References CDEBUG, D_INFO, DFID, dt_object::do_lu, dt_insert(), dt_obd_name(), dt_try_as_dir(), dt_write_lock(), dt_write_unlock(), lu_object_fid(), MOR_TGT_CHILD, PFID, and thandle::th_dev.
Referenced by out_tx_index_insert_exec().
static int out_obj_ref_add (const struct lu_env * env, struct dt_object * dt_obj, struct thandle * th) [static]
Definition at line 883 of file out_lib.c.
References dt_ref_add(), dt_write_lock(), dt_write_unlock(), and MOR_TGT_CHILD.
Referenced by out_tx_ref_add_exec(), and out_tx_ref_del_undo().
static int out_obj_ref_del (const struct lu_env * env, struct dt_object * dt_obj, struct thandle * th) [static]
Definition at line 896 of file out_lib.c.
References dt_ref_del(), dt_write_lock(), dt_write_unlock(), and MOR_TGT_CHILD.
Referenced by out_tx_ref_add_undo(), and out_tx_ref_del_exec().
int out_object_destroy_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, const struct lu_fid * fid)
Definition at line 334 of file out_lib.c.
References OUT_DESTROY, and out_update_pack().
int out_read_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, const struct lu_fid * fid, size_t size, loff_t pos)
Definition at line 409 of file out_lib.c.
References ARRAY_SIZE, cpu_to_le64, LASSERT, OUT_READ, and out_update_pack().
int out_ref_add_add_exec (const struct lu_env * env, struct dt_object * dt_obj, struct thandle_exec_args * ta, struct thandle * th, struct object_update_reply * reply, int index, const char * file, int line)
Definition at line 932 of file out_lib.c.
References dt_object::do_lu, dt_declare_ref_add(), tx_arg::index, lu_object_get(), tx_arg::object, out_tx_ref_add_exec(), out_tx_ref_add_undo(), tx_arg::reply, and tx_add_exec().
int out_ref_add_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, const struct lu_fid * fid)
Definition at line 241 of file out_lib.c.
References OUT_REF_ADD, and out_update_pack().
int out_ref_del_add_exec (const struct lu_env * env, struct dt_object * dt_obj, struct thandle_exec_args * ta, struct thandle * th, struct object_update_reply * reply, int index, const char * file, int line)
Definition at line 981 of file out_lib.c.
References dt_object::do_lu, dt_declare_ref_del(), tx_arg::index, lu_object_get(), tx_arg::object, out_tx_ref_del_exec(), out_tx_ref_del_undo(), tx_arg::reply, and tx_add_exec().
int out_ref_del_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, const struct lu_fid * fid)
Definition at line 233 of file out_lib.c.
References OUT_REF_DEL, and out_update_pack().
static int out_tx_attr_set_exec (const struct lu_env * env, struct thandle * th, struct tx_arg * arg) [static]
Definition at line 626 of file out_lib.c.
References tx_arg::attr_set, CDEBUG, D_INFO, D_OTHER, DFID, dt_object::do_lu, dt_attr_set(), dt_obd_name(), dt_write_lock(), dt_write_unlock(), tx_arg::index, lu_object_fid(), MOR_TGT_CHILD, tx_arg::object, object_update_result_insert(), PFID, tx_arg::reply, thandle::th_dev, and tx_arg::u.
Referenced by out_attr_set_add_exec().
static int out_tx_attr_set_undo (const struct lu_env * env, struct thandle * th, struct tx_arg * arg) [static]
Definition at line 616 of file out_lib.c.
References CERROR, DFID, dt_object::do_lu, dt_obd_name(), lu_object_fid(), tx_arg::object, PFID, and thandle::th_dev.
Referenced by out_attr_set_add_exec().
int out_tx_create_exec (const struct lu_env * env, struct thandle * th, struct tx_arg * arg)
Definition at line 530 of file out_lib.c.
References CDEBUG, tx_arg::create, D_INFO, D_OTHER, DFID, dt_object::do_lu, dt_create(), dt_obd_name(), dt_write_lock(), dt_write_unlock(), tx_arg::index, lu_object_fid(), MOR_TGT_CHILD, tx_arg::object, object_update_result_insert(), PFID, tx_arg::reply, thandle::th_dev, and tx_arg::u.
Referenced by out_create_add_exec(), and out_trans_stop().
static int out_tx_create_undo (const struct lu_env * env, struct thandle * th, struct tx_arg * arg) [static]
All of the xxx_undo will be used once execution failed, But because all of the required resource has been reserved in declare phase, i.e.
if declare succeed, it should make sure the following executing phase succeed in anyway, so these undo should be useless for most of the time in Phase I
Definition at line 518 of file out_lib.c.
References CERROR, dt_obd_name(), tx_arg::object, out_obj_destroy(), and thandle::th_dev.
Referenced by out_create_add_exec().
static int out_tx_destroy_exec (const struct lu_env * env, struct thandle * th, struct tx_arg * arg) [static]
Definition at line 1175 of file out_lib.c.
References CDEBUG, D_INFO, dt_obd_name(), tx_arg::index, tx_arg::object, object_update_result_insert(), out_obj_destroy(), tx_arg::reply, RETURN, and thandle::th_dev.
Referenced by out_destroy_add_exec().
static int out_tx_destroy_undo (const struct lu_env * env, struct thandle * th, struct tx_arg * arg) [static]
Definition at line 1193 of file out_lib.c.
References CERROR, dt_obd_name(), and thandle::th_dev.
Referenced by out_destroy_add_exec().
static int out_tx_index_delete_exec (const struct lu_env * env, struct thandle * th, struct tx_arg * arg) [static]
Definition at line 1114 of file out_lib.c.
References CDEBUG, D_INFO, dt_obd_name(), tx_arg::index, tx_arg::insert, tx_arg::object, object_update_result_insert(), out_obj_index_delete(), tx_arg::reply, thandle::th_dev, and tx_arg::u.
Referenced by out_index_delete_add_exec().
static int out_tx_index_delete_undo (const struct lu_env * env, struct thandle * th, struct tx_arg * arg) [static]
Definition at line 1132 of file out_lib.c.
References CERROR, dt_obd_name(), and thandle::th_dev.
Referenced by out_index_delete_add_exec().
static int out_tx_index_insert_exec (const struct lu_env * env, struct thandle * th, struct tx_arg * arg) [static]
Definition at line 1050 of file out_lib.c.
References CDEBUG, D_INFO, dt_obd_name(), dt_object_exists(), tx_arg::index, tx_arg::insert, tx_arg::object, object_update_result_insert(), out_obj_index_insert(), tx_arg::reply, RETURN, thandle::th_dev, tx_arg::u, and unlikely.
Referenced by out_index_insert_add_exec().
static int out_tx_index_insert_undo (const struct lu_env * env, struct thandle * th, struct tx_arg * arg) [static]
Definition at line 1072 of file out_lib.c.
References tx_arg::insert, tx_arg::object, out_obj_index_delete(), and tx_arg::u.
Referenced by out_index_insert_add_exec().
static int out_tx_ref_add_exec (const struct lu_env * env, struct thandle * th, struct tx_arg * arg) [static]
Definition at line 909 of file out_lib.c.
References CDEBUG, D_INFO, dt_obd_name(), tx_arg::index, tx_arg::object, object_update_result_insert(), out_obj_ref_add(), tx_arg::reply, and thandle::th_dev.
Referenced by out_ref_add_add_exec().
static int out_tx_ref_add_undo (const struct lu_env * env, struct thandle * th, struct tx_arg * arg) [static]
Definition at line 926 of file out_lib.c.
References tx_arg::object, and out_obj_ref_del().
Referenced by out_ref_add_add_exec().
static int out_tx_ref_del_exec (const struct lu_env * env, struct thandle * th, struct tx_arg * arg) [static]
Definition at line 957 of file out_lib.c.
References CDEBUG, D_INFO, dt_obd_name(), tx_arg::index, tx_arg::object, object_update_result_insert(), out_obj_ref_del(), tx_arg::reply, and thandle::th_dev.
Referenced by out_ref_del_add_exec().
static int out_tx_ref_del_undo (const struct lu_env * env, struct thandle * th, struct tx_arg * arg) [static]
Definition at line 975 of file out_lib.c.
References tx_arg::object, and out_obj_ref_add().
Referenced by out_ref_del_add_exec().
static int out_tx_write_exec (const struct lu_env * env, struct thandle * th, struct tx_arg * arg) [static]
Definition at line 675 of file out_lib.c.
References CDEBUG, D_INFO, DFID, dt_object::do_lu, dt_record_write(), dt_write_lock(), dt_write_unlock(), tx_arg::index, LPU64, lu_object_fid(), MOR_TGT_CHILD, OBD_FAIL_CHECK, OBD_FAIL_OUT_ENOSPC, tx_arg::object, object_update_result_insert(), PFID, tx_arg::reply, tx_arg::u, and tx_arg::write.
Referenced by out_write_add_exec().
static int out_tx_xattr_del_exec (const struct lu_env * env, struct thandle * th, struct tx_arg * arg) [static]
Definition at line 830 of file out_lib.c.
References CDEBUG, D_INFO, DFID, dt_object::do_lu, dt_obd_name(), dt_write_lock(), dt_write_unlock(), dt_xattr_del(), GOTO, tx_arg::index, lu_object_exists, lu_object_fid(), MOR_TGT_CHILD, tx_arg::object, object_update_result_insert(), PFID, tx_arg::reply, thandle::th_dev, tx_arg::u, and tx_arg::xattr_set.
Referenced by out_xattr_del_add_exec().
static int out_tx_xattr_set_exec (const struct lu_env * env, struct thandle * th, struct tx_arg * arg) [static]
Ignore errors if this is LINK EA
Definition at line 730 of file out_lib.c.
References CDEBUG, D_INFO, dt_object::do_lu, dt_obd_name(), dt_write_lock(), dt_write_unlock(), dt_xattr_set(), GOTO, tx_arg::index, LE_SKIP_NLINK, lfsck_pack_rfa(), LFSCK_TYPE_NAMESPACE, lu_object_exists, lu_object_fid(), MOR_TGT_CHILD, tx_arg::object, object_update_result_insert(), tx_arg::reply, tgt_lfsck_in_notify, tgt_ses_info(), tgt_th_info(), thandle::th_dev, tgt_thread_info::tti_lr, tx_arg::u, unlikely, XATTR_NAME_LINK, and tx_arg::xattr_set.
Referenced by out_xattr_set_add_exec().
int out_update_header_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, enum update_type update_op, const struct lu_fid * fid, unsigned int param_count, __u16 * param_sizes, __u32 reply_size)
Fill object update header.
Only fill the object update header, and parameters will be filled later in other functions.
[in] env execution environment [in] update object update to be filled [in,out] max_update_size maximum object update size, if the current update length equals or exceeds the size, it will return -E2BIG. [in] update_op update type [in] fid object FID of the update [in] param_count the count of the update parameters [in] param_sizes the length of each parameters
Return values:
0 if packing succeeds.
-E2BIG if packing exceeds the maximum length.
Definition at line 91 of file out_lib.c.
References cfs_size_round(), object_update_param_size(), object_update::ou_fid, object_update::ou_params, object_update::ou_params_count, object_update::ou_result_size, object_update::ou_type, object_update_param::oup_len, and unlikely.
Referenced by out_attr_set_pack(), out_create_pack(), and out_update_pack().
int out_update_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, enum update_type op, const struct lu_fid * fid, unsigned int param_count, __u16 * param_sizes, const void ** param_bufs, __u32 reply_size)
Packs one update into the update_buffer.
Parameters:
[in] env execution environment
[in] update update to be packed
[in] max_update_size *maximum size of update
[in] op update operation (enum update_type)
[in] fid object FID for this update
[in] param_count number of parameters for this update
[in] param_sizes array of parameters length of this update
[in] param_bufs parameter buffers
Return values:
= 0 if updates packing succeeds
negative errno if updates packing fails
Definition at line 146 of file out_lib.c.
References ENTRY, object_update_param_size(), object_update::ou_params, object_update_param::oup_buf, out_update_header_pack(), and RETURN.
Referenced by osp_insert_async_request(), out_attr_get_pack(), out_index_delete_pack(), out_index_insert_pack(), out_index_lookup_pack(), out_object_destroy_pack(), out_read_pack(), out_ref_add_pack(), out_ref_del_pack(), out_write_pack(), out_xattr_del_pack(), out_xattr_get_pack(), and out_xattr_set_pack().
int out_write_add_exec (const struct lu_env * env, struct dt_object * dt_obj, const struct lu_buf * buf, loff_t pos, struct thandle_exec_args * ta, struct thandle * th, struct object_update_reply * reply, int index, const char * file, int line)
Definition at line 704 of file out_lib.c.
References dt_object::do_lu, dt_declare_record_write(), tx_arg::index, lu_object_get(), tx_arg::object, out_tx_write_exec(), tx_arg::reply, tx_add_exec(), tx_arg::u, and tx_arg::write.
int out_write_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, const struct lu_fid * fid, const struct lu_buf * buf, __u64 pos)
Definition at line 343 of file out_lib.c.
References ARRAY_SIZE, cpu_to_le64, lu_buf::lb_buf, lu_buf::lb_len, out_update_pack(), OUT_WRITE, and out_write_pack().
Referenced by out_write_pack().
int out_xattr_del_add_exec (const struct lu_env * env, struct dt_object * dt_obj, const char * name, struct thandle_exec_args * ta, struct thandle * th, struct object_update_reply * reply, int index, const char * file, int line)
Definition at line 858 of file out_lib.c.
References dt_object::do_lu, dt_declare_xattr_del(), tx_arg::index, lu_object_get(), tx_arg::object, out_tx_xattr_del_exec(), tx_arg::reply, tx_add_exec(), tx_arg::u, and tx_arg::xattr_set.
int out_xattr_del_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, const struct lu_fid * fid, const char * name)
Definition at line 288 of file out_lib.c.
References out_update_pack(), OUT_XATTR_DEL, and size.
int out_xattr_get_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, const struct lu_fid * fid, const char * name, const int bufsize)
Definition at line 395 of file out_lib.c.
References LASSERT, out_update_pack(), OUT_XATTR_GET, and size.
int out_xattr_set_add_exec (const struct lu_env * env, struct dt_object * dt_obj, const struct lu_buf * buf, const char * name, int flags, struct thandle_exec_args * ta, struct thandle * th, struct object_update_reply * reply, int index, const char * file, int line)
Definition at line 783 of file out_lib.c.
References dt_object::do_lu, dt_declare_xattr_set(), tx_arg::index, LE_SKIP_NLINK_DECLARE, lfsck_pack_rfa(), LFSCK_TYPE_NAMESPACE, lu_object_fid(), lu_object_get(), tx_arg::object, out_tx_xattr_set_exec(), tx_arg::reply, thandle_exec_args::ta_handle, tgt_lfsck_in_notify, tgt_ses_info(), tgt_th_info(), tgt_thread_info::tti_lr, tx_add_exec(), tx_arg::u, XATTR_NAME_LINK, and tx_arg::xattr_set.
int out_xattr_set_pack (const struct lu_env * env, struct object_update * update, size_t * max_update_size, const struct lu_fid * fid, const struct lu_buf * buf, const char * name, __u32 flag)
Definition at line 275 of file out_lib.c.
References ARRAY_SIZE, lu_buf::lb_buf, lu_buf::lb_len, out_update_pack(), OUT_XATTR_SET, and out_xattr_set_pack().
Referenced by out_xattr_set_pack().
struct tx_arg* tx_add_exec (struct thandle_exec_args * ta, tx_exec_func_t func, tx_exec_func_t undo, const char * file, int line) [read]
Definition at line 468 of file out_lib.c.
References tx_arg::exec_fn, tx_arg::file, LASSERT, tx_arg::line, thandle_exec_args::ta_alloc_args, thandle_exec_args::ta_argno, thandle_exec_args::ta_args, TX_ALLOC_STEP, tx_extend_args(), and tx_arg::undo_fn.
Referenced by out_attr_set_add_exec(), out_create_add_exec(), out_destroy_add_exec(), out_index_delete_add_exec(), out_index_insert_add_exec(), out_ref_add_add_exec(), out_ref_del_add_exec(), out_write_add_exec(), out_xattr_del_add_exec(), and out_xattr_set_add_exec().
static int tx_extend_args (struct thandle_exec_args * ta, int new_alloc_ta) [static]
Definition at line 425 of file out_lib.c.
References GOTO, OBD_ALLOC, OBD_ALLOC_PTR, OBD_FREE, OBD_FREE_PTR, thandle_exec_args::ta_alloc_args, and thandle_exec_args::ta_args.
Referenced by tx_add_exec().
const char* update_op_str (__u16 opc)
Definition at line 43 of file out_lib.c.
References ARRAY_SIZE, OUT_ATTR_GET, OUT_ATTR_SET, OUT_CREATE, OUT_DESTROY, OUT_INDEX_DELETE, OUT_INDEX_INSERT, OUT_INDEX_LOOKUP, OUT_NOOP, OUT_PUNCH, OUT_READ, OUT_REF_ADD, OUT_REF_DEL, OUT_START, OUT_WRITE, OUT_XATTR_DEL, OUT_XATTR_GET, and OUT_XATTR_SET.
Referenced by object_update_request_dump(), update_records_dump(), and update_records_update_pack().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.