Lustre: lustre/target/out_handler.c File Reference
lustre/target/out_handler.c File Reference
#include <llog_swab.h>
#include <lustre_obdo.h>
#include <lustre_swab.h>
#include <lustre_update.h>
#include <md_object.h>
#include <obd_class.h>
#include "tgt_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_CLASS
#define DEF_OUT_HNDL(opc, name, flags, fn)
Typedefs
typedef void(* out_reconstruct_t)(const struct lu_env *env, struct dt_device *dt, struct dt_object *obj, struct object_update_reply *reply, int index)
Functions
static void out_reconstruct (const struct lu_env *env, struct dt_device *dt, struct dt_object *obj, struct object_update_reply *reply, int index)
static int out_check_resent (const struct lu_env *env, struct dt_device *dt, struct dt_object *obj, struct ptlrpc_request *req, out_reconstruct_t reconstruct, struct object_update_reply *reply, int index)
static int out_create (struct tgt_session_info *tsi)
static int out_attr_set (struct tgt_session_info *tsi)
static int out_attr_get (struct tgt_session_info *tsi)
static int out_xattr_get (struct tgt_session_info *tsi)
static int out_index_lookup (struct tgt_session_info *tsi)
static int out_xattr_set (struct tgt_session_info *tsi)
static int out_xattr_del (struct tgt_session_info *tsi)
static int out_ref_add (struct tgt_session_info *tsi)
increase ref of the object
static int out_ref_del (struct tgt_session_info *tsi)
static int out_index_insert (struct tgt_session_info *tsi)
static int out_index_delete (struct tgt_session_info *tsi)
static int out_destroy (struct tgt_session_info *tsi)
static int out_write (struct tgt_session_info *tsi)
static int out_read (struct tgt_session_info *tsi)
static int out_noop (struct tgt_session_info *tsi)
static struct tgt_handler * out_handler_find (__u32 opc)
static int out_tx_start (const struct lu_env *env, struct dt_device *dt, struct thandle_exec_args *ta, struct obd_export *exp)
static int out_trans_start (const struct lu_env *env, struct thandle_exec_args *ta)
static int out_trans_stop (const struct lu_env *env, struct thandle_exec_args *ta, int err)
static int out_tx_end (const struct lu_env *env, struct thandle_exec_args *ta, int declare_ret)
int out_handle (struct tgt_session_info *tsi)
Object updates between Targets.
Variables
static struct tgt_handler out_update_ops []
struct tgt_handler tgt_out_handlers []
Define Documentation
#define DEBUG_SUBSYSTEM S_CLASS
Definition at line 32 of file out_handler.c.
#define DEF_OUT_HNDL (opc, name, flags, fn)
Value:
[opc - OUT_CREATE] = {                                  \
        .th_name    = name,                             \
        .th_fail_id = 0,                                \
        .th_opc     = opc,                              \
        .th_flags   = flags,                            \
        .th_act     = fn,                               \
        .th_fmt     = NULL,                             \
        .th_version = 0,                                \
}
Definition at line 709 of file out_handler.c.
Typedef Documentation
typedef void(* out_reconstruct_t)(const struct lu_env *env, struct dt_device *dt, struct dt_object *obj, struct object_update_reply *reply, int index)
Definition at line 54 of file out_handler.c.
Function Documentation
static int out_attr_get (struct tgt_session_info * tsi) [static]
Definition at line 187 of file out_handler.c.
References CDEBUG, D_INFO, dt_object::do_lu, dt_attr_get(), dt_read_lock(), dt_read_unlock(), ENTRY, GOTO, lu_attr::la_valid, lu_object::lo_header, lu_object_header::loh_flags, lu_object_exists, LU_OBJECT_HEARD_BANSHEE, lustre_set_wire_obdo(), MOR_TGT_CHILD, obdo::o_valid, obdo_from_la(), object_update_result_insert(), object_update::ou_result_size, RETURN, tgt_name(), tgt_th_info(), tgt_session_info::tsi_env, tgt_session_info::tsi_tgt, tgt_thread_info::tti_attr, tgt_thread_info::tti_u, unlikely, and tgt_thread_info::update.
static int out_attr_set (struct tgt_session_info * tsi) [static]
Definition at line 151 of file out_handler.c.
References CERROR, ENTRY, la_from_obdo(), lu_attr::la_valid, lustre_get_wire_obdo(), lustre_swab_obdo(), obdo::o_valid, object_update_param_get(), out_tx_attr_set, ptlrpc_req_need_swab(), req_capsule::rc_req, RETURN, size, thandle_exec_args::ta_handle, tgt_name(), tgt_th_info(), tgt_session_info::tsi_env, tgt_session_info::tsi_pill, tgt_session_info::tsi_tgt, tgt_thread_info::tti_attr, tgt_thread_info::tti_tea, tgt_thread_info::tti_u, and tgt_thread_info::update.
static int out_check_resent (const struct lu_env * env, struct dt_device * dt, struct dt_object * obj, struct ptlrpc_request * req, out_reconstruct_t reconstruct, struct object_update_reply * reply, int index) [inline, static]
Definition at line 60 of file out_handler.c.
References D_HA, D_RPCTRACE, DEBUG_REQ, lsd_client_data::lcd_last_result, lsd_client_data::lcd_last_transno, likely, LPD64, lustre_msg_get_flags(), lustre_msg_set_status(), lustre_msg_set_transno(), MSG_RESENT, req_xid_is_last(), ptlrpc_request::rq_export, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_status, and ptlrpc_request::rq_transno.
Referenced by out_handle().
static int out_create (struct tgt_session_info * tsi) [static]
Definition at line 96 of file out_handler.c.
References CERROR, DFID, dt_object::do_lu, dt_object_format::dof_type, dt_mode_to_dft(), ENTRY, fid_is_sane(), la_from_obdo(), lu_attr::la_mode, lu_object_exists, lustre_get_wire_obdo(), lustre_swab_lu_fid, lustre_swab_obdo(), obdo::o_valid, object_update_param_get(), object_update::ou_params_count, out_tx_create, PFID, ptlrpc_req_need_swab(), req_capsule::rc_req, RETURN, size, thandle_exec_args::ta_handle, tgt_name(), tgt_th_info(), tgt_session_info::tsi_env, tgt_session_info::tsi_pill, tgt_session_info::tsi_tgt, tgt_thread_info::tti_attr, tgt_thread_info::tti_tea, tgt_thread_info::tti_u, and tgt_thread_info::update.
Referenced by ost_setup().
static int out_destroy (struct tgt_session_info * tsi) [static]
Definition at line 533 of file out_handler.c.
References CERROR, DFID, dt_object::do_lu, ENTRY, fid_is_sane(), lu_object_exists, object_update::ou_fid, out_tx_destroy, PFID, RETURN, thandle_exec_args::ta_handle, tgt_name(), tgt_th_info(), tgt_session_info::tsi_env, tgt_session_info::tsi_tgt, tgt_thread_info::tti_tea, tgt_thread_info::tti_u, and tgt_thread_info::update.
Referenced by ll_xattr_cache_refill(), and llog_cat_new_log().
int out_handle (struct tgt_session_info * tsi)
Object updates between Targets.
Because all the updates has been dis-assemblied into object updates at sender side, so OUT will call OSD API directly to execute these updates.
In DNE phase I all of the updates in the request need to be executed in one transaction, and the transaction has to be synchronously.
Please refer to lustre/include/lustre/lustre_idl.h for req/reply format.
Definition at line 894 of file out_handler.c.
References ptlrpc_bulk_frag_ops::add_iov_frag, ptlrpc_bulk_desc::bd_frag_ops, CERROR, dt_device::dd_record_fid_accessed, DFID, dt_object::do_lu, dt_locate(), ENTRY, err_serious(), fid_is_sane(), GOTO, LE_FID_ACCESSED, lfsck_pack_rfa(), LFSCK_TYPE_LAYOUT, lu_object_fid(), lu_object_put(), lustre_swab_object_update, lustre_swab_object_update_request, lu_target::lut_bottom, MDS_BULK_PORTAL, MUTABOR, OBD_ALLOC, OBD_FREE, object_update_request_get(), object_update::ou_batchid, object_update::ou_fid, object_update::ou_flags, object_update::ou_result_size, object_update::ou_type, out_update_buffer::oub_size, out_update_header::ouh_count, out_update_header::ouh_inline_data, out_update_header::ouh_inline_length, out_update_header::ouh_magic, out_update_header::ouh_reply_size, object_update_reply::ourp_count, object_update_reply::ourp_lens, object_update_reply::ourp_magic, object_update_request::ourq_count, object_update_request::ourq_magic, out_check_resent(), out_handler_find(), OUT_MAXREQSIZE, out_reconstruct(), out_tx_end(), out_tx_start(), OUT_UPDATE_HEADER_MAGIC, PFID, PTLRPC_BULK_BUF_KVEC, PTLRPC_BULK_GET_SINK, ptlrpc_bulk_kvec_ops, PTLRPC_BULK_OPS_COUNT, ptlrpc_free_bulk(), ptlrpc_req_need_swab(), req_capsule::rc_req, RCL_CLIENT, RCL_SERVER, req_capsule_client_get(), req_capsule_get_size(), req_capsule_server_get(), req_capsule_server_pack(), req_capsule_set(), req_capsule_set_size(), req_is_replay(), RETURN, RMF_OUT_UPDATE_BUF, RMF_OUT_UPDATE_HEADER, RMF_OUT_UPDATE_REPLY, ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_export, RQF_OUT_UPDATE, thandle_exec_args::ta_handle, tgt_lfsck_in_notify, tgt_name(), tgt_ses_req(), tgt_th_info(), tgt_handler::th_act, tgt_handler::th_flags, thandle::th_sync, tgt_session_info::tsi_env, tgt_session_info::tsi_exp, tgt_session_info::tsi_pill, tgt_session_info::tsi_tgt, tgt_thread_info::tti_lr, tgt_thread_info::tti_mult_trans, tgt_thread_info::tti_tea, tgt_thread_info::tti_u, unlikely, tgt_thread_info::update, UPDATE_FL_SYNC, UPDATE_REPLY_MAGIC, and UPDATE_REQUEST_MAGIC.
Referenced by handle_nullreq().
static struct tgt_handler* out_handler_find (__u32 opc) [static, read]
Definition at line 750 of file out_handler.c.
References LASSERTF, OUT_CREATE, OUT_LAST, and tgt_handler::th_opc.
Referenced by out_handle().
static int out_index_delete (struct tgt_session_info * tsi) [static]
Definition at line 508 of file out_handler.c.
References CERROR, dt_object::do_lu, dt_key, lu_object_exists, name, object_update_param_get(), out_tx_index_delete, RETURN, thandle_exec_args::ta_handle, tgt_name(), tgt_th_info(), tgt_session_info::tsi_env, tgt_session_info::tsi_tgt, tgt_thread_info::tti_tea, tgt_thread_info::tti_u, and tgt_thread_info::update.
static int out_index_insert (struct tgt_session_info * tsi) [static]
Definition at line 451 of file out_handler.c.
References __swab32s, CERROR, DFID, dt_key, ENTRY, fid_is_sane(), lustre_swab_lu_fid, name, object_update_param_get(), out_tx_index_insert, PFID, ptlrpc_req_need_swab(), req_capsule::rc_req, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, RETURN, size, thandle_exec_args::ta_handle, tgt_name(), tgt_th_info(), tgt_session_info::tsi_env, tgt_session_info::tsi_pill, tgt_session_info::tsi_tgt, tgt_thread_info::tti_rec, tgt_thread_info::tti_tea, tgt_thread_info::tti_u, and tgt_thread_info::update.
static int out_index_lookup (struct tgt_session_info * tsi) [static]
Definition at line 290 of file out_handler.c.
References CDEBUG, CERROR, D_INFO, DFID, dt_object::do_lu, dt_key, dt_lookup(), dt_read_lock(), dt_read_unlock(), dt_try_as_dir(), ENTRY, GOTO, lu_object_exists, lu_object_fid(), MOR_TGT_CHILD, name, object_update_param_get(), object_update_result_insert(), object_update::ou_result_size, PFID, RETURN, tgt_name(), tgt_th_info(), tgt_session_info::tsi_env, tgt_session_info::tsi_tgt, tgt_thread_info::tti_fid1, tgt_thread_info::tti_u, unlikely, and tgt_thread_info::update.
static int out_noop (struct tgt_session_info * tsi) [static]
Definition at line 704 of file out_handler.c.
static int out_read (struct tgt_session_info * tsi) [static]
Definition at line 601 of file out_handler.c.
References __u64, CERROR, cfs_size_round(), dt_object::do_lu, dt_read(), dt_read_lock(), dt_read_unlock(), ENTRY, GOTO, LASSERT, lu_buf::lb_buf, lu_buf::lb_len, le64_to_cpu, lu_object_exists, MOR_TGT_CHILD, OBD_ALLOC, OBD_FREE, object_update_param_get(), object_update_result_get(), orr_cpu_to_le(), out_read_reply::orr_offset, out_read_reply::orr_size, object_update_result::our_data, object_update_result::our_datalen, object_update_result::our_rc, object_update_reply::ourp_lens, OUT_BULK_BUFFER_SIZE, ptlrpc_status_hton(), lu_rdbuf::rb_bufs, lu_rdbuf::rb_nbufs, RETURN, size, tgt_name(), tgt_send_buffer(), tgt_th_info(), tgt_session_info::tsi_env, tgt_session_info::tsi_tgt, tgt_thread_info::tti_u, and tgt_thread_info::update.
static void out_reconstruct (const struct lu_env * env, struct dt_device * dt, struct dt_object * obj, struct object_update_reply * reply, int index) [static]
Definition at line 42 of file out_handler.c.
References CDEBUG, D_INFO, dt_obd_name(), and object_update_result_insert().
Referenced by out_handle().
static int out_ref_add (struct tgt_session_info * tsi) [static]
increase ref of the object
Definition at line 418 of file out_handler.c.
References ENTRY, out_tx_ref_add, RETURN, thandle_exec_args::ta_handle, tgt_th_info(), tgt_session_info::tsi_env, tgt_thread_info::tti_tea, tgt_thread_info::tti_u, and tgt_thread_info::update.
static int out_ref_del (struct tgt_session_info * tsi) [static]
Definition at line 433 of file out_handler.c.
References dt_object::do_lu, ENTRY, lu_object_exists, out_tx_ref_del, RETURN, thandle_exec_args::ta_handle, tgt_th_info(), tgt_session_info::tsi_env, tgt_thread_info::tti_tea, tgt_thread_info::tti_u, and tgt_thread_info::update.
static int out_trans_start (const struct lu_env * env, struct thandle_exec_args * ta) [static]
Definition at line 785 of file out_handler.c.
References dt_trans_start(), thandle_exec_args::ta_handle, and thandle::th_dev.
Referenced by out_tx_end().
static int out_trans_stop (const struct lu_env * env, struct thandle_exec_args * ta, int err) [static]
Definition at line 791 of file out_handler.c.
References dt_object::do_lu, dt_trans_stop(), tx_arg::exec_fn, lu_object::lo_header, lu_object_header::loh_flags, LU_OBJECT_HEARD_BANSHEE, lu_object_put(), tx_arg::object, out_tx_create_exec(), thandle_exec_args::ta_argno, thandle_exec_args::ta_args, thandle_exec_args::ta_handle, thandle::th_dev, and thandle::th_result.
Referenced by out_tx_end().
static int out_tx_end (const struct lu_env * env, struct thandle_exec_args * ta, int declare_ret) [static]
Definition at line 821 of file out_handler.c.
References CDEBUG, CERROR, D_INFO, dt_obd_name(), ENTRY, tx_arg::exec_fn, tx_arg::file, GOTO, LASSERT, tx_arg::line, OBD_FAIL_OUT_UPDATE_NET_REP, out_trans_start(), out_trans_stop(), RETURN, stop, thandle_exec_args::ta_argno, thandle_exec_args::ta_args, thandle_exec_args::ta_handle, tgt_ses_info(), thandle::th_dev, tgt_session_info::tsi_reply_fail_id, tx_arg::undo_fn, and unlikely.
Referenced by out_handle().
static int out_tx_start (const struct lu_env * env, struct dt_device * dt, struct thandle_exec_args * ta, struct obd_export * exp) [static]
Definition at line 765 of file out_handler.c.
References CERROR, dt_obd_name(), dt_trans_create(), obd_export::exp_need_sync, thandle_exec_args::ta_argno, thandle_exec_args::ta_handle, and thandle::th_sync.
Referenced by out_handle().
static int out_write (struct tgt_session_info * tsi) [static]
Definition at line 560 of file out_handler.c.
References __swab64s, __u64, buf, CERROR, ENTRY, lu_buf::lb_buf, lu_buf::lb_len, object_update_param_get(), out_tx_write, ptlrpc_req_need_swab(), req_capsule::rc_req, RETURN, size, thandle_exec_args::ta_handle, tgt_name(), tgt_th_info(), tgt_session_info::tsi_env, tgt_session_info::tsi_pill, tgt_session_info::tsi_tgt, tgt_thread_info::tti_buf, tgt_thread_info::tti_tea, tgt_thread_info::tti_u, and tgt_thread_info::update.
Referenced by qmt_dqacq0().
static int out_xattr_del (struct tgt_session_info * tsi) [static]
Definition at line 392 of file out_handler.c.
References CERROR, ENTRY, name, object_update_param_get(), out_tx_xattr_del, RETURN, thandle_exec_args::ta_handle, tgt_name(), tgt_th_info(), tgt_session_info::tsi_env, tgt_session_info::tsi_tgt, tgt_thread_info::tti_tea, tgt_thread_info::tti_u, and tgt_thread_info::update.
static int out_xattr_get (struct tgt_session_info * tsi) [static]
Definition at line 235 of file out_handler.c.
References CDEBUG, CERROR, D_INFO, DFID, dt_object::do_lu, dt_read_lock(), dt_read_unlock(), dt_xattr_get(), ENTRY, GOTO, lu_buf::lb_buf, lu_buf::lb_len, lu_object::lo_header, lu_object_header::loh_flags, lu_object_exists, lu_object_fid(), LU_OBJECT_HEARD_BANSHEE, MOR_TGT_CHILD, name, object_update_param_get(), object_update_result_get(), object_update_result_insert(), object_update_result::our_data, PFID, RETURN, tgt_name(), tgt_th_info(), tgt_session_info::tsi_env, tgt_session_info::tsi_tgt, tgt_thread_info::tti_buf, tgt_thread_info::tti_u, and tgt_thread_info::update.
static int out_xattr_set (struct tgt_session_info * tsi) [static]
Definition at line 344 of file out_handler.c.
References __swab32s, buf, CERROR, ENTRY, lu_buf::lb_buf, lu_buf::lb_len, name, object_update_param_get(), out_tx_xattr_set, ptlrpc_req_need_swab(), req_capsule::rc_req, RETURN, size, thandle_exec_args::ta_handle, tgt_name(), tgt_th_info(), tgt_session_info::tsi_env, tgt_session_info::tsi_pill, tgt_session_info::tsi_tgt, tgt_thread_info::tti_buf, tgt_thread_info::tti_tea, tgt_thread_info::tti_u, and tgt_thread_info::update.
Variable Documentation
struct tgt_handler out_update_ops[] [static]
Initial value:
 {
        DEF_OUT_HNDL(OUT_CREATE, "out_create", MUTABOR | HABEO_REFERO,
                     out_create),
        DEF_OUT_HNDL(OUT_DESTROY, "out_create", MUTABOR | HABEO_REFERO,
                     out_destroy),
        DEF_OUT_HNDL(OUT_REF_ADD, "out_ref_add", MUTABOR | HABEO_REFERO,
                     out_ref_add),
        DEF_OUT_HNDL(OUT_REF_DEL, "out_ref_del", MUTABOR | HABEO_REFERO,
                     out_ref_del),
        DEF_OUT_HNDL(OUT_ATTR_SET, "out_attr_set",  MUTABOR | HABEO_REFERO,
                     out_attr_set),
        DEF_OUT_HNDL(OUT_ATTR_GET, "out_attr_get",  HABEO_REFERO,
                     out_attr_get),
        DEF_OUT_HNDL(OUT_XATTR_SET, "out_xattr_set", MUTABOR | HABEO_REFERO,
                     out_xattr_set),
        DEF_OUT_HNDL(OUT_XATTR_DEL, "out_xattr_del", MUTABOR | HABEO_REFERO,
                     out_xattr_del),
        DEF_OUT_HNDL(OUT_XATTR_GET, "out_xattr_get", HABEO_REFERO,
                     out_xattr_get),
        DEF_OUT_HNDL(OUT_INDEX_LOOKUP, "out_index_lookup", HABEO_REFERO,
                     out_index_lookup),
        DEF_OUT_HNDL(OUT_INDEX_INSERT, "out_index_insert",
                     MUTABOR | HABEO_REFERO, out_index_insert),
        DEF_OUT_HNDL(OUT_INDEX_DELETE, "out_index_delete",
                     MUTABOR | HABEO_REFERO, out_index_delete),
        DEF_OUT_HNDL(OUT_WRITE, "out_write", MUTABOR | HABEO_REFERO, out_write),
        DEF_OUT_HNDL(OUT_READ, "out_read", HABEO_REFERO, out_read),
        DEF_OUT_HNDL(OUT_NOOP, "out_noop", HABEO_REFERO, out_noop),
}
Definition at line 720 of file out_handler.c.
struct tgt_handler tgt_out_handlers[]
Initial value:
 {
TGT_UPDATE_HDL(MUTABOR, OUT_UPDATE,     out_handle),
}
Definition at line 1166 of file out_handler.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.