Lustre: lustre/ptlrpc/pack_generic.c File Reference
lustre/ptlrpc/pack_generic.c File Reference
#include <libcfs/libcfs.h>
#include <lustre/ll_fiemap.h>
#include <llog_swab.h>
#include <lustre_net.h>
#include <lustre_swab.h>
#include <obd_cksum.h>
#include <obd_class.h>
#include <obd_support.h>
#include "ptlrpc_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_RPC
#define LUSTRE_MSG_MAGIC_V1 0x0BD00BD0
#define PTLRPC_RS_DEBUG_LRU_ADD(rs) do {} while(0)
#define PTLRPC_RS_DEBUG_LRU_DEL(rs) do {} while(0)
Functions
static __u32 lustre_msg_hdr_size_v2 (__u32 count)
__u32 lustre_msg_hdr_size (__u32 magic, __u32 count)
void ptlrpc_buf_set_swabbed (struct ptlrpc_request *req, const int inout, __u32 index)
int ptlrpc_buf_need_swab (struct ptlrpc_request *req, const int inout, __u32 index)
ptlrpc msg buffer and swab interface
static int lustre_msg_check_version_v2 (struct lustre_msg_v2 *msg, __u32 version)
int lustre_msg_check_version (struct lustre_msg *msg, __u32 version)
__u32 lustre_msg_early_size ()
__u32 lustre_msg_size_v2 (int count, __u32 *lengths)
__u32 lustre_msg_size (__u32 magic, int count, __u32 *lens)
__u32 lustre_packed_msg_size (struct lustre_msg *msg)
void lustre_init_msg_v2 (struct lustre_msg_v2 *msg, int count, __u32 *lens, char **bufs)
static int lustre_pack_request_v2 (struct ptlrpc_request *req, int count, __u32 *lens, char **bufs)
int lustre_pack_request (struct ptlrpc_request *req, __u32 magic, int count, __u32 *lens, char **bufs)
struct ptlrpc_reply_state * lustre_get_emerg_rs (struct ptlrpc_service_part *svcpt)
void lustre_put_emerg_rs (struct ptlrpc_reply_state *rs)
int lustre_pack_reply_v2 (struct ptlrpc_request *req, int count, __u32 *lens, char **bufs, int flags)
int lustre_pack_reply_flags (struct ptlrpc_request *req, int count, __u32 *lens, char **bufs, int flags)
int lustre_pack_reply (struct ptlrpc_request *req, int count, __u32 *lens, char **bufs)
void * lustre_msg_buf_v2 (struct lustre_msg_v2 *m, __u32 n, __u32 min_size)
void * lustre_msg_buf (struct lustre_msg *m, __u32 n, __u32 min_size)
static int lustre_shrink_msg_v2 (struct lustre_msg_v2 *msg, __u32 segment, unsigned int newlen, int move_data)
int lustre_shrink_msg (struct lustre_msg *msg, int segment, unsigned int newlen, int move_data)
void lustre_free_reply_state (struct ptlrpc_reply_state *rs)
static int lustre_unpack_msg_v2 (struct lustre_msg_v2 *m, int len)
int __lustre_unpack_msg (struct lustre_msg *m, int len)
int ptlrpc_unpack_req_msg (struct ptlrpc_request *req, int len)
int ptlrpc_unpack_rep_msg (struct ptlrpc_request *req, int len)
static int lustre_unpack_ptlrpc_body_v2 (struct ptlrpc_request *req, const int inout, int offset)
int lustre_unpack_req_ptlrpc_body (struct ptlrpc_request *req, int offset)
int lustre_unpack_rep_ptlrpc_body (struct ptlrpc_request *req, int offset)
static __u32 lustre_msg_buflen_v2 (struct lustre_msg_v2 *m, __u32 n)
__u32 lustre_msg_buflen (struct lustre_msg *m, __u32 n)
lustre_msg_buflen - return the length of buffer n in message m
static void lustre_msg_set_buflen_v2 (struct lustre_msg_v2 *m, __u32 n, __u32 len)
void lustre_msg_set_buflen (struct lustre_msg *m, __u32 n, __u32 len)
__u32 lustre_msg_bufcount (struct lustre_msg *m)
char * lustre_msg_string (struct lustre_msg *m, __u32 index, __u32 max_len)
static void * __lustre_swab_buf (struct lustre_msg *msg, __u32 index, __u32 min_size, void *swabber)
static struct ptlrpc_body * lustre_msg_ptlrpc_body (struct lustre_msg *msg)
__u32 lustre_msghdr_get_flags (struct lustre_msg *msg)
void lustre_msghdr_set_flags (struct lustre_msg *msg, __u32 flags)
__u32 lustre_msg_get_flags (struct lustre_msg *msg)
void lustre_msg_add_flags (struct lustre_msg *msg, __u32 flags)
void lustre_msg_set_flags (struct lustre_msg *msg, __u32 flags)
void lustre_msg_clear_flags (struct lustre_msg *msg, __u32 flags)
__u32 lustre_msg_get_op_flags (struct lustre_msg *msg)
void lustre_msg_add_op_flags (struct lustre_msg *msg, __u32 flags)
struct lustre_handle * lustre_msg_get_handle (struct lustre_msg *msg)
__u32 lustre_msg_get_type (struct lustre_msg *msg)
__u32 lustre_msg_get_version (struct lustre_msg *msg)
void lustre_msg_add_version (struct lustre_msg *msg, __u32 version)
__u32 lustre_msg_get_opc (struct lustre_msg *msg)
__u64 lustre_msg_get_last_xid (struct lustre_msg *msg)
__u16 lustre_msg_get_tag (struct lustre_msg *msg)
__u64 lustre_msg_get_last_committed (struct lustre_msg *msg)
__u64 * lustre_msg_get_versions (struct lustre_msg *msg)
__u64 lustre_msg_get_transno (struct lustre_msg *msg)
int lustre_msg_get_status (struct lustre_msg *msg)
__u64 lustre_msg_get_slv (struct lustre_msg *msg)
void lustre_msg_set_slv (struct lustre_msg *msg, __u64 slv)
__u32 lustre_msg_get_limit (struct lustre_msg *msg)
void lustre_msg_set_limit (struct lustre_msg *msg, __u64 limit)
__u32 lustre_msg_get_conn_cnt (struct lustre_msg *msg)
__u32 lustre_msg_get_magic (struct lustre_msg *msg)
__u32 lustre_msg_get_timeout (struct lustre_msg *msg)
__u32 lustre_msg_get_service_time (struct lustre_msg *msg)
char * lustre_msg_get_jobid (struct lustre_msg *msg)
__u32 lustre_msg_get_cksum (struct lustre_msg *msg)
__u64 lustre_msg_get_mbits (struct lustre_msg *msg)
__u32 lustre_msg_calc_cksum (struct lustre_msg *msg)
void lustre_msg_set_handle (struct lustre_msg *msg, struct lustre_handle *handle)
void lustre_msg_set_type (struct lustre_msg *msg, __u32 type)
void lustre_msg_set_opc (struct lustre_msg *msg, __u32 opc)
void lustre_msg_set_last_xid (struct lustre_msg *msg, __u64 last_xid)
void lustre_msg_set_tag (struct lustre_msg *msg, __u16 tag)
void lustre_msg_set_last_committed (struct lustre_msg *msg, __u64 last_committed)
void lustre_msg_set_versions (struct lustre_msg *msg, __u64 *versions)
void lustre_msg_set_transno (struct lustre_msg *msg, __u64 transno)
void lustre_msg_set_status (struct lustre_msg *msg, __u32 status)
void lustre_msg_set_conn_cnt (struct lustre_msg *msg, __u32 conn_cnt)
void lustre_msg_set_timeout (struct lustre_msg *msg, __u32 timeout)
void lustre_msg_set_service_time (struct lustre_msg *msg, __u32 service_time)
void lustre_msg_set_jobid (struct lustre_msg *msg, char *jobid)
void lustre_msg_set_cksum (struct lustre_msg *msg, __u32 cksum)
void lustre_msg_set_mbits (struct lustre_msg *msg, __u64 mbits)
void ptlrpc_request_set_replen (struct ptlrpc_request *req)
void ptlrpc_req_set_repsize (struct ptlrpc_request *req, int count, __u32 *lens)
int do_set_info_async (struct obd_import *imp, int opcode, int version, size_t keylen, void *key, size_t vallen, void *val, struct ptlrpc_request_set *set)
Send a remote set_info_async.
void lustre_swab_ptlrpc_body (struct ptlrpc_body *b)
void lustre_swab_connect (struct obd_connect_data *ocd)
void lustre_swab_obdo (struct obdo *o)
void lustre_swab_obd_statfs (struct obd_statfs *os)
void lustre_swab_obd_ioobj (struct obd_ioobj *ioo)
void lustre_swab_niobuf_remote (struct niobuf_remote *nbr)
void lustre_swab_ost_body (struct ost_body *b)
void lustre_swab_ost_last_id (u64 *id)
void lustre_swab_generic_32s (__u32 *val)
void lustre_swab_gl_desc (union ldlm_gl_desc *desc)
void lustre_swab_ost_lvb_v1 (struct ost_lvb_v1 *lvb)
void lustre_swab_ost_lvb (struct ost_lvb *lvb)
void lustre_swab_lquota_lvb (struct lquota_lvb *lvb)
void lustre_swab_mdt_body (struct mdt_body *b)
void lustre_swab_mdt_ioepoch (struct mdt_ioepoch *b)
void lustre_swab_mgs_target_info (struct mgs_target_info *mti)
void lustre_swab_mgs_nidtbl_entry (struct mgs_nidtbl_entry *entry)
void lustre_swab_mgs_config_body (struct mgs_config_body *body)
void lustre_swab_mgs_config_res (struct mgs_config_res *body)
static void lustre_swab_obd_dqinfo (struct obd_dqinfo *i)
static void lustre_swab_obd_dqblk (struct obd_dqblk *b)
void lustre_swab_obd_quotactl (struct obd_quotactl *q)
void lustre_swab_mdt_remote_perm (struct mdt_remote_perm *p)
void lustre_swab_fid2path (struct getinfo_fid2path *gf)
static void lustre_swab_fiemap_extent (struct fiemap_extent *fm_extent)
void lustre_swab_fiemap (struct fiemap *fiemap)
void lustre_swab_idx_info (struct idx_info *ii)
void lustre_swab_lip_header (struct lu_idxpage *lip)
void lustre_swab_mdt_rec_reint (struct mdt_rec_reint *rr)
void lustre_swab_lov_desc (struct lov_desc *ld)
void lustre_swab_lmv_desc (struct lmv_desc *ld)
static void lustre_swab_lmv_mds_md_v1 (struct lmv_mds_md_v1 *lmm1)
void lustre_swab_lmv_mds_md (union lmv_mds_md *lmm)
void lustre_swab_lmv_user_md (struct lmv_user_md *lum)
void lustre_print_user_md (unsigned int lvl, struct lov_user_md *lum, const char *msg)
static void lustre_swab_lmm_oi (struct ost_id *oi)
static void lustre_swab_lov_user_md_common (struct lov_user_md_v1 *lum)
void lustre_swab_lov_user_md_v1 (struct lov_user_md_v1 *lum)
void lustre_swab_lov_user_md_v3 (struct lov_user_md_v3 *lum)
void lustre_swab_lov_mds_md (struct lov_mds_md *lmm)
void lustre_swab_lov_user_md_objects (struct lov_user_ost_data *lod, int stripe_count)
void lustre_swab_ldlm_res_id (struct ldlm_res_id *id)
void lustre_swab_ldlm_policy_data (union ldlm_wire_policy_data *d)
void lustre_swab_ldlm_intent (struct ldlm_intent *i)
void lustre_swab_ldlm_resource_desc (struct ldlm_resource_desc *r)
void lustre_swab_ldlm_lock_desc (struct ldlm_lock_desc *l)
void lustre_swab_ldlm_request (struct ldlm_request *rq)
void lustre_swab_ldlm_reply (struct ldlm_reply *r)
void lustre_swab_quota_body (struct quota_body *b)
void dump_ioo (struct obd_ioobj *ioo)
void dump_rniobuf (struct niobuf_remote *nb)
void dump_obdo (struct obdo *oa)
Dumper for struct obdo.
void dump_ost_body (struct ost_body *ob)
void dump_rcs (__u32 *rc)
static int req_ptlrpc_body_swabbed (struct ptlrpc_request *req)
static int rep_ptlrpc_body_swabbed (struct ptlrpc_request *req)
void _debug_req (struct ptlrpc_request *req, struct libcfs_debug_msg_data *msgdata, const char *fmt,...)
void lustre_swab_lustre_capa (struct lustre_capa *c)
void lustre_swab_lustre_capa_key (struct lustre_capa_key *k)
void lustre_swab_hsm_user_state (struct hsm_user_state *state)
void lustre_swab_hsm_state_set (struct hsm_state_set *hss)
static void lustre_swab_hsm_extent (struct hsm_extent *extent)
void lustre_swab_hsm_current_action (struct hsm_current_action *action)
void lustre_swab_hsm_user_item (struct hsm_user_item *hui)
void lustre_swab_layout_intent (struct layout_intent *li)
void lustre_swab_hsm_progress_kernel (struct hsm_progress_kernel *hpk)
void lustre_swab_hsm_request (struct hsm_request *hr)
void lustre_swab_object_update (struct object_update *ou)
void lustre_swab_object_update_request (struct object_update_request *our)
void lustre_swab_object_update_result (struct object_update_result *our)
void lustre_swab_object_update_reply (struct object_update_reply *our)
void lustre_swab_out_update_header (struct out_update_header *ouh)
void lustre_swab_out_update_buffer (struct out_update_buffer *oub)
void lustre_swab_swap_layouts (struct mdc_swap_layouts *msl)
void lustre_swab_close_data (struct close_data *cd)
void lustre_swab_lfsck_request (struct lfsck_request *lr)
void lustre_swab_lfsck_reply (struct lfsck_reply *lr)
void lustre_swab_orphan_ent (struct lu_orphan_ent *ent)
void lustre_swab_ladvise (struct lu_ladvise *ladvise)
void lustre_swab_ladvise_hdr (struct ladvise_hdr *ladvise_hdr)
Define Documentation
#define DEBUG_SUBSYSTEM S_RPC
Definition at line 45 of file pack_generic.c.
#define LUSTRE_MSG_MAGIC_V1 0x0BD00BD0
#define PTLRPC_RS_DEBUG_LRU_ADD (rs) do {} while(0)
Definition at line 278 of file pack_generic.c.
Referenced by lustre_pack_reply_v2().
#define PTLRPC_RS_DEBUG_LRU_DEL (rs) do {} while(0)
Definition at line 279 of file pack_generic.c.
Referenced by lustre_free_reply_state().
Function Documentation
static void* __lustre_swab_buf (struct lustre_msg * msg, __u32 index, __u32 min_size, void * swabber) [inline, static]
Definition at line 779 of file pack_generic.c.
References CERROR, LASSERT, lustre_msg_buf_v2(), and LUSTRE_MSG_MAGIC_V2.
void _debug_req (struct ptlrpc_request * req, struct libcfs_debug_msg_data * msgdata, const char * fmt, ...)
Definition at line 2392 of file pack_generic.c.
References ptlrpc_connection::c_peer, CFS_TIME_T, DEBUG_REQ_FLAGS, obd_export::exp_client_uuid, obd_export::exp_connection, obd_import::imp_connection, obd_import::imp_obd, libcfs_debug_vmsg2(), libcfs_nid2str(), LNET_NID_ANY, LPD64, LPU64, lustre_msg_get_flags(), lustre_msg_get_opc(), lustre_msg_get_status(), lustre_msg_get_transno(), lnet_process_id_t::nid, obd_device::obd_name, ptlrpc_req_need_swab(), rep_ptlrpc_body_swabbed(), REQ_FLAGS_FMT, req_ptlrpc_body_swabbed(), ptlrpc_request::rq_deadline, ptlrpc_request::rq_early_count, ptlrpc_request::rq_export, ptlrpc_request::rq_import, ptlrpc_request::rq_refcount, ptlrpc_request::rq_replen, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_reqlen, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_status, ptlrpc_request::rq_timedout, ptlrpc_request::rq_transno, ptlrpc_request::rq_xid, and obd_uuid::uuid.
void dump_obdo (struct obdo * oa)
Dumper for struct obdo.
Definition at line 2295 of file pack_generic.c.
References CDEBUG, lustre_handle::cookie, D_RPCTRACE, DOSTID, LPD64, LPX64, obdo::o_atime, obdo::o_blksize, obdo::o_blocks, obdo::o_ctime, obdo::o_flags, obdo::o_gid, obdo::o_gid_h, obdo::o_grant, obdo::o_handle, obdo::o_ioepoch, obdo::o_mode, obdo::o_mtime, obdo::o_nlink, obdo::o_oi, obdo::o_parent_oid, obdo::o_parent_seq, obdo::o_parent_ver, obdo::o_size, obdo::o_stripe_idx, obdo::o_uid, obdo::o_uid_h, obdo::o_valid, OBD_MD_FLATIME, OBD_MD_FLBLKSZ, OBD_MD_FLBLOCKS, OBD_MD_FLCKSUM, OBD_MD_FLCTIME, OBD_MD_FLEPOCH, OBD_MD_FLFID, OBD_MD_FLFLAGS, OBD_MD_FLGENER, OBD_MD_FLGID, OBD_MD_FLGRANT, OBD_MD_FLHANDLE, OBD_MD_FLID, OBD_MD_FLMODE, OBD_MD_FLMTIME, OBD_MD_FLNLINK, OBD_MD_FLSIZE, OBD_MD_FLTYPE, OBD_MD_FLUID, and POSTID.
struct ptlrpc_reply_state* lustre_get_emerg_rs (struct ptlrpc_service_part * svcpt) [read]
Definition at line 283 of file pack_generic.c.
References cfs_time_seconds(), l_wait_event, list_del(), list_empty(), list_entry, LWI_TIMEOUT, list_head::next, ptlrpc_reply_state::rs_list, ptlrpc_reply_state::rs_prealloc, ptlrpc_reply_state::rs_size, ptlrpc_reply_state::rs_svcpt, ptlrpc_service_part::scp_rep_idle, and ptlrpc_service_part::scp_rep_waitq.
Referenced by sptlrpc_svc_alloc_rs().
static __u32 lustre_msg_buflen_v2 (struct lustre_msg_v2 * m, __u32 n) [inline, static]
Definition at line 673 of file pack_generic.c.
References lustre_msg_v2::lm_bufcount, and lustre_msg_v2::lm_buflens.
Referenced by lustre_msg_buflen(), and lustre_msg_string().
static int lustre_msg_check_version_v2 (struct lustre_msg_v2 * msg, __u32 version) [inline, static]
Definition at line 97 of file pack_generic.c.
References lustre_msg_get_version(), and LUSTRE_VERSION_MASK.
Referenced by lustre_msg_check_version().
static __u32 lustre_msg_hdr_size_v2 (__u32 count) [inline, static]
Definition at line 60 of file pack_generic.c.
References cfs_size_round(), and offsetof.
Referenced by lustre_init_msg_v2(), lustre_msg_buf_v2(), lustre_msg_hdr_size(), lustre_msg_size_v2(), and lustre_unpack_msg_v2().
static struct ptlrpc_body* lustre_msg_ptlrpc_body (struct lustre_msg * msg) [static, read]
Definition at line 799 of file pack_generic.c.
References lustre_msg_buf_v2(), and MSG_PTLRPC_BODY_OFF.
Referenced by lustre_msg_add_flags(), lustre_msg_add_op_flags(), lustre_msg_add_version(), lustre_msg_calc_cksum(), lustre_msg_clear_flags(), lustre_msg_get_conn_cnt(), lustre_msg_get_flags(), lustre_msg_get_handle(), lustre_msg_get_last_committed(), lustre_msg_get_last_xid(), lustre_msg_get_limit(), lustre_msg_get_mbits(), lustre_msg_get_op_flags(), lustre_msg_get_opc(), lustre_msg_get_service_time(), lustre_msg_get_slv(), lustre_msg_get_status(), lustre_msg_get_tag(), lustre_msg_get_timeout(), lustre_msg_get_transno(), lustre_msg_get_type(), lustre_msg_get_version(), lustre_msg_get_versions(), lustre_msg_set_conn_cnt(), lustre_msg_set_flags(), lustre_msg_set_handle(), lustre_msg_set_last_committed(), lustre_msg_set_last_xid(), lustre_msg_set_limit(), lustre_msg_set_mbits(), lustre_msg_set_opc(), lustre_msg_set_service_time(), lustre_msg_set_slv(), lustre_msg_set_status(), lustre_msg_set_tag(), lustre_msg_set_timeout(), lustre_msg_set_transno(), lustre_msg_set_type(), and lustre_msg_set_versions().
static void lustre_msg_set_buflen_v2 (struct lustre_msg_v2 * m, __u32 n, __u32 len) [inline, static]
Definition at line 701 of file pack_generic.c.
References LBUG, lustre_msg_v2::lm_bufcount, and lustre_msg_v2::lm_buflens.
Referenced by lustre_msg_set_buflen().
static int lustre_pack_request_v2 (struct ptlrpc_request * req, int count, __u32 * lens, char ** bufs) [static]
Definition at line 216 of file pack_generic.c.
References lustre_init_msg_v2(), lustre_msg_add_version(), lustre_msg_size_v2(), PTLRPC_MSG_VERSION, ptlrpc_request::rq_reqlen, ptlrpc_request::rq_reqmsg, and sptlrpc_cli_alloc_reqbuf().
Referenced by lustre_pack_request().
void lustre_put_emerg_rs (struct ptlrpc_reply_state * rs)
Definition at line 319 of file pack_generic.c.
References list_add(), ptlrpc_reply_state::rs_list, ptlrpc_reply_state::rs_svcpt, ptlrpc_service_part::scp_rep_idle, and ptlrpc_service_part::scp_rep_waitq.
Referenced by sptlrpc_svc_alloc_rs(), and sptlrpc_svc_free_rs().
static int lustre_shrink_msg_v2 (struct lustre_msg_v2 * msg, __u32 segment, unsigned int newlen, int move_data) [static]
Definition at line 449 of file pack_generic.c.
References cfs_size_round(), LASSERT, lustre_msg_v2::lm_bufcount, lustre_msg_v2::lm_buflens, lustre_msg_buf_v2(), and lustre_msg_size_v2().
Referenced by lustre_shrink_msg().
void lustre_swab_close_data (struct close_data * cd)
Definition at line 2602 of file pack_generic.c.
References __swab64s, close_data::cd_data_version, close_data::cd_fid, and lustre_swab_lu_fid.
void lustre_swab_connect (struct obd_connect_data * ocd)
Definition at line 1656 of file pack_generic.c.
References __swab16s, __swab32s, __swab64s, CLASSERT, OBD_CONNECT_FLAGS2, OBD_CONNECT_MAX_EASIZE, OBD_CONNECT_MAXBYTES, OBD_CONNECT_MULTIMODRPCS, obd_connect_data::ocd_brw_size, obd_connect_data::ocd_cksum_types, obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_connect_flags2, obd_connect_data::ocd_grant, obd_connect_data::ocd_grant_max_blks, obd_connect_data::ocd_grant_tax_kb, obd_connect_data::ocd_group, obd_connect_data::ocd_ibits_known, obd_connect_data::ocd_index, obd_connect_data::ocd_instance, obd_connect_data::ocd_max_easize, obd_connect_data::ocd_maxbytes, obd_connect_data::ocd_maxmodrpcs, obd_connect_data::ocd_transno, obd_connect_data::ocd_version, and offsetof.
void lustre_swab_fid2path (struct getinfo_fid2path * gf)
Definition at line 1969 of file pack_generic.c.
References __swab32s, __swab64s, getinfo_fid2path::gf_fid, getinfo_fid2path::gf_linkno, getinfo_fid2path::gf_pathlen, getinfo_fid2path::gf_recno, and lustre_swab_lu_fid.
Referenced by mdc_get_info_rpc(), and mdt_rpc_fid2path().
void lustre_swab_fiemap (struct fiemap * fiemap)
Definition at line 1987 of file pack_generic.c.
References __swab32s, __swab64s, and lustre_swab_fiemap_extent().
static void lustre_swab_fiemap_extent (struct fiemap_extent * fm_extent) [static]
Definition at line 1978 of file pack_generic.c.
References __swab32s, and __swab64s.
Referenced by lustre_swab_fiemap().
void lustre_swab_generic_32s (__u32 * val)
Definition at line 1783 of file pack_generic.c.
References __swab32s.
void lustre_swab_gl_desc (union ldlm_gl_desc * desc)
Definition at line 1788 of file pack_generic.c.
References __swab64s, CLASSERT, ldlm_gl_lquota_desc::gl_flags, ldlm_gl_lquota_desc::gl_hardlimit, ldlm_gl_lquota_desc::gl_id, ldlm_gl_lquota_desc::gl_softlimit, ldlm_gl_lquota_desc::gl_time, ldlm_gl_lquota_desc::gl_ver, ldlm_gl_desc::lquota_desc, lustre_swab_lu_fid, offsetof, and lquota_id::qid_fid.
void lustre_swab_hsm_current_action (struct hsm_current_action * action)
Definition at line 2478 of file pack_generic.c.
References __swab32s, hsm_current_action::hca_action, hsm_current_action::hca_location, hsm_current_action::hca_state, and lustre_swab_hsm_extent().
static void lustre_swab_hsm_extent (struct hsm_extent * extent) [static]
Definition at line 2472 of file pack_generic.c.
References __swab64s, hsm_extent::length, and hsm_extent::offset.
Referenced by lustre_swab_hsm_current_action(), and lustre_swab_hsm_user_item().
void lustre_swab_hsm_progress_kernel (struct hsm_progress_kernel * hpk)
Definition at line 2499 of file pack_generic.c.
References __swab16s, __swab64s, hsm_progress_kernel::hpk_cookie, hsm_progress_kernel::hpk_errval, hsm_progress_kernel::hpk_extent, hsm_progress_kernel::hpk_fid, hsm_progress_kernel::hpk_flags, hsm_extent::length, lustre_swab_lu_fid, and hsm_extent::offset.
void lustre_swab_hsm_request (struct hsm_request * hr)
Definition at line 2509 of file pack_generic.c.
References __swab32s, __swab64s, hsm_request::hr_action, hsm_request::hr_archive_id, hsm_request::hr_data_len, hsm_request::hr_flags, and hsm_request::hr_itemcount.
void lustre_swab_hsm_state_set (struct hsm_state_set * hss)
Definition at line 2464 of file pack_generic.c.
References __swab32s, __swab64s, hsm_state_set::hss_archive_id, hsm_state_set::hss_clearmask, hsm_state_set::hss_setmask, and hsm_state_set::hss_valid.
void lustre_swab_hsm_user_item (struct hsm_user_item * hui)
Definition at line 2485 of file pack_generic.c.
References hsm_user_item::hui_extent, hsm_user_item::hui_fid, lustre_swab_hsm_extent(), and lustre_swab_lu_fid.
void lustre_swab_hsm_user_state (struct hsm_user_state * state)
Definition at line 2458 of file pack_generic.c.
References __swab32s, hsm_user_state::hus_archive_id, and hsm_user_state::hus_states.
void lustre_swab_idx_info (struct idx_info * ii)
Definition at line 2002 of file pack_generic.c.
References __swab16s, __swab32s, __swab64s, idx_info::ii_attrs, idx_info::ii_count, idx_info::ii_fid, idx_info::ii_flags, idx_info::ii_hash_end, idx_info::ii_hash_start, idx_info::ii_keysize, idx_info::ii_magic, idx_info::ii_recsize, idx_info::ii_version, and lustre_swab_lu_fid.
void lustre_swab_ladvise (struct lu_ladvise * ladvise)
Definition at line 2643 of file pack_generic.c.
References __swab64s, CLASSERT, lu_ladvise::lla_advice, lu_ladvise::lla_end, lu_ladvise::lla_start, and offsetof.
void lustre_swab_ladvise_hdr (struct ladvise_hdr * ladvise_hdr)
Definition at line 2652 of file pack_generic.c.
References __swab32s, __swab64s, CLASSERT, ladvise_hdr::lah_count, ladvise_hdr::lah_flags, ladvise_hdr::lah_magic, and offsetof.
void lustre_swab_layout_intent (struct layout_intent * li)
Definition at line 2491 of file pack_generic.c.
References __swab32s, __swab64s, layout_intent::li_end, layout_intent::li_flags, layout_intent::li_opc, and layout_intent::li_start.
void lustre_swab_ldlm_intent (struct ldlm_intent * i)
Definition at line 2232 of file pack_generic.c.
References __swab64s, and ldlm_intent::opc.
void lustre_swab_ldlm_lock_desc (struct ldlm_lock_desc * l)
Definition at line 2244 of file pack_generic.c.
References __swab32s, ldlm_lock_desc::l_granted_mode, ldlm_lock_desc::l_policy_data, ldlm_lock_desc::l_req_mode, ldlm_lock_desc::l_resource, lustre_swab_ldlm_policy_data(), and lustre_swab_ldlm_resource_desc().
Referenced by lustre_swab_ldlm_reply(), and lustre_swab_ldlm_request().
void lustre_swab_ldlm_policy_data (union ldlm_wire_policy_data * d)
Definition at line 2220 of file pack_generic.c.
References __swab32s, __swab64s, ldlm_extent::end, ldlm_extent::gid, ldlm_wire_policy_data::l_extent, ldlm_wire_policy_data::l_flock, ldlm_flock_wire::lfw_owner, ldlm_flock_wire::lfw_pid, and ldlm_extent::start.
Referenced by lustre_swab_ldlm_lock_desc().
void lustre_swab_ldlm_reply (struct ldlm_reply * r)
Definition at line 2260 of file pack_generic.c.
References __swab32s, __swab64s, CLASSERT, ldlm_reply::lock_desc, ldlm_reply::lock_flags, ldlm_reply::lock_policy_res1, ldlm_reply::lock_policy_res2, lustre_swab_ldlm_lock_desc(), and offsetof.
void lustre_swab_ldlm_request (struct ldlm_request * rq)
Definition at line 2252 of file pack_generic.c.
References __swab32s, ldlm_request::lock_count, ldlm_request::lock_desc, ldlm_request::lock_flags, and lustre_swab_ldlm_lock_desc().
void lustre_swab_ldlm_res_id (struct ldlm_res_id * id)
Definition at line 2212 of file pack_generic.c.
References __swab64s, ldlm_res_id::name, and RES_NAME_SIZE.
Referenced by lustre_swab_ldlm_resource_desc().
void lustre_swab_ldlm_resource_desc (struct ldlm_resource_desc * r)
Definition at line 2237 of file pack_generic.c.
References __swab32s, CLASSERT, ldlm_resource_desc::lr_name, ldlm_resource_desc::lr_type, lustre_swab_ldlm_res_id(), and offsetof.
Referenced by lustre_swab_ldlm_lock_desc().
void lustre_swab_lfsck_reply (struct lfsck_reply * lr)
Definition at line 2627 of file pack_generic.c.
References __swab32s, __swab64s, CLASSERT, lfsck_reply::lr_repaired, lfsck_reply::lr_status, and offsetof.
void lustre_swab_lfsck_request (struct lfsck_request * lr)
Definition at line 2608 of file pack_generic.c.
References __swab16s, __swab32s, CLASSERT, lfsck_request::lr_active, lfsck_request::lr_async_windows, lfsck_request::lr_event, lfsck_request::lr_fid, lfsck_request::lr_fid2, lfsck_request::lr_fid3, lfsck_request::lr_flags, lfsck_request::lr_index, lfsck_request::lr_param, lfsck_request::lr_speed, lfsck_request::lr_valid, lfsck_request::lr_version, lustre_swab_lu_fid, and offsetof.
void lustre_swab_lip_header (struct lu_idxpage * lip)
Definition at line 2016 of file pack_generic.c.
References __swab16s, __swab32s, lu_idxpage::lip_flags, lu_idxpage::lip_magic, and lu_idxpage::lip_nr.
Referenced by osp_it_next_page(), and qsd_reint_entries().
static void lustre_swab_lmm_oi (struct ost_id * oi) [static]
Definition at line 2147 of file pack_generic.c.
References __swab64s, and ost_id::oi.
Referenced by lustre_swab_lov_mds_md(), and lustre_swab_lov_user_md_common().
void lustre_swab_lmv_desc (struct lmv_desc * ld)
Definition at line 2066 of file pack_generic.c.
References __swab32s, __swab64s, lmv_desc::ld_active_tgt_count, lmv_desc::ld_default_hash_size, lmv_desc::ld_default_stripe_count, lmv_desc::ld_pattern, lmv_desc::ld_qos_maxage, and lmv_desc::ld_tgt_count.
void lustre_swab_lmv_mds_md (union lmv_mds_md * lmm)
Definition at line 2091 of file pack_generic.c.
References lmv_mds_md::lmv_magic, LMV_MAGIC_V1, lmv_mds_md::lmv_md_v1, and lustre_swab_lmv_mds_md_v1().
Referenced by ll_dir_getstripe().
static void lustre_swab_lmv_mds_md_v1 (struct lmv_mds_md_v1 * lmm1) [static]
Definition at line 2078 of file pack_generic.c.
References __swab32s, lmv_mds_md_v1::lmv_hash_type, lmv_mds_md_v1::lmv_layout_version, lmv_mds_md_v1::lmv_magic, lmv_mds_md_v1::lmv_master_mdt_index, lmv_mds_md_v1::lmv_stripe_count, lmv_mds_md_v1::lmv_stripe_fids, and lustre_swab_lu_fid.
Referenced by lustre_swab_lmv_mds_md().
void lustre_swab_lmv_user_md (struct lmv_user_md * lum)
Definition at line 2103 of file pack_generic.c.
References __swab32s, CLASSERT, and offsetof.
void lustre_swab_lov_desc (struct lov_desc * ld)
Definition at line 2053 of file pack_generic.c.
References __swab32s, __swab64s, lov_desc::ld_active_tgt_count, lov_desc::ld_default_stripe_count, lov_desc::ld_default_stripe_offset, lov_desc::ld_default_stripe_size, lov_desc::ld_pattern, lov_desc::ld_qos_maxage, and lov_desc::ld_tgt_count.
Referenced by lod_pools_init(), and lov_setup().
void lustre_swab_lov_mds_md (struct lov_mds_md * lmm)
Definition at line 2184 of file pack_generic.c.
References __swab16s, __swab32s, CDEBUG, D_IOCTL, ENTRY, EXIT, and lustre_swab_lmm_oi().
Referenced by lov_getstripe().
static void lustre_swab_lov_user_md_common (struct lov_user_md_v1 * lum) [static]
Definition at line 2153 of file pack_generic.c.
References __swab16s, __swab32s, ENTRY, EXIT, lov_user_md_v1::lmm_magic, lov_user_md_v1::lmm_oi, lov_user_md_v1::lmm_pattern, lov_user_md_v1::lmm_stripe_count, lov_user_md_v1::lmm_stripe_offset, lov_user_md_v1::lmm_stripe_size, and lustre_swab_lmm_oi().
Referenced by lustre_swab_lov_user_md_v1(), and lustre_swab_lov_user_md_v3().
void lustre_swab_lov_user_md_objects (struct lov_user_ost_data * lod, int stripe_count)
Definition at line 2198 of file pack_generic.c.
References __swab32s, ENTRY, EXIT, and lustre_swab_ost_id.
Referenced by ll_lov_getstripe_ea_info(), lod_qos_parse_config(), and lov_getstripe().
void lustre_swab_lov_user_md_v1 (struct lov_user_md_v1 * lum)
Definition at line 2165 of file pack_generic.c.
References CDEBUG, D_IOCTL, ENTRY, EXIT, and lustre_swab_lov_user_md_common().
Referenced by ll_dir_getstripe(), ll_dir_setstripe(), ll_lov_getstripe_ea_info(), lod_cache_parent_lov_striping(), and lod_qos_parse_config().
void lustre_swab_lov_user_md_v3 (struct lov_user_md_v3 * lum)
Definition at line 2174 of file pack_generic.c.
References CDEBUG, D_IOCTL, ENTRY, EXIT, and lustre_swab_lov_user_md_common().
Referenced by ll_dir_getstripe(), ll_dir_setstripe(), ll_lov_getstripe_ea_info(), lod_cache_parent_lov_striping(), and lod_qos_parse_config().
void lustre_swab_lquota_lvb (struct lquota_lvb * lvb)
Definition at line 1823 of file pack_generic.c.
References __swab64s, lquota_lvb::lvb_flags, lquota_lvb::lvb_id_may_rel, lquota_lvb::lvb_id_qunit, lquota_lvb::lvb_id_rel, and lquota_lvb::lvb_pad1.
Referenced by ldlm_fill_lvb(), and qmt_lvbo_update().
void lustre_swab_lustre_capa (struct lustre_capa * c)
Definition at line 2439 of file pack_generic.c.
References __swab32s, __swab64s, lustre_capa::lc_expiry, lustre_capa::lc_fid, lustre_capa::lc_flags, lustre_capa::lc_gid, lustre_capa::lc_keyid, lustre_capa::lc_opc, lustre_capa::lc_timeout, lustre_capa::lc_uid, and lustre_swab_lu_fid.
void lustre_swab_lustre_capa_key (struct lustre_capa_key * k)
Definition at line 2451 of file pack_generic.c.
References __swab32s, __swab64s, CLASSERT, lustre_capa_key::lk_keyid, lustre_capa_key::lk_seq, and offsetof.
void lustre_swab_mdt_body (struct mdt_body * b)
Definition at line 1833 of file pack_generic.c.
References __swab32s, __swab64s, CLASSERT, lustre_swab_lu_fid, mdt_body::mbo_aclsize, mdt_body::mbo_atime, mdt_body::mbo_blocks, mdt_body::mbo_capability, mdt_body::mbo_ctime, mdt_body::mbo_eadatasize, mdt_body::mbo_fid1, mdt_body::mbo_fid2, mdt_body::mbo_flags, mdt_body::mbo_fsgid, mdt_body::mbo_fsuid, mdt_body::mbo_gid, mdt_body::mbo_gid_h, mdt_body::mbo_ioepoch, mdt_body::mbo_max_mdsize, mdt_body::mbo_mode, mdt_body::mbo_mtime, mdt_body::mbo_nlink, mdt_body::mbo_rdev, mdt_body::mbo_size, mdt_body::mbo_suppgid, mdt_body::mbo_t_state, mdt_body::mbo_uid, mdt_body::mbo_uid_h, mdt_body::mbo_valid, and offsetof.
void lustre_swab_mdt_ioepoch (struct mdt_ioepoch * b)
Definition at line 1866 of file pack_generic.c.
References CLASSERT, and offsetof.
void lustre_swab_mdt_rec_reint (struct mdt_rec_reint * rr)
Definition at line 2025 of file pack_generic.c.
References __swab32s, __swab64s, CLASSERT, lustre_swab_lu_fid, offsetof, mdt_rec_reint::rr_atime, mdt_rec_reint::rr_bias, mdt_rec_reint::rr_blocks, mdt_rec_reint::rr_cap, mdt_rec_reint::rr_ctime, mdt_rec_reint::rr_fid1, mdt_rec_reint::rr_fid2, mdt_rec_reint::rr_flags, mdt_rec_reint::rr_flags_h, mdt_rec_reint::rr_fsgid, mdt_rec_reint::rr_fsuid, mdt_rec_reint::rr_mode, mdt_rec_reint::rr_mtime, mdt_rec_reint::rr_opcode, mdt_rec_reint::rr_size, mdt_rec_reint::rr_suppgid1, mdt_rec_reint::rr_suppgid2, and mdt_rec_reint::rr_umask.
void lustre_swab_mdt_remote_perm (struct mdt_remote_perm * p)
Definition at line 1956 of file pack_generic.c.
References __swab32s, mdt_remote_perm::rp_access_perm, mdt_remote_perm::rp_fsgid, mdt_remote_perm::rp_fsgid_h, mdt_remote_perm::rp_fsuid, mdt_remote_perm::rp_fsuid_h, mdt_remote_perm::rp_gid, mdt_remote_perm::rp_padding, and mdt_remote_perm::rp_uid.
Referenced by lustre_check_remote_perm(), mdc_finish_enqueue(), mdc_get_lustre_md(), and mdc_getattr_common().
void lustre_swab_mgs_config_body (struct mgs_config_body * body)
Definition at line 1911 of file pack_generic.c.
References __swab16s, __swab32s, __swab64s, mgs_config_body::mcb_offset, mgs_config_body::mcb_type, and mgs_config_body::mcb_units.
void lustre_swab_mgs_config_res (struct mgs_config_res * body)
Definition at line 1918 of file pack_generic.c.
References __swab64s, mgs_config_res::mcr_offset, and mgs_config_res::mcr_size.
void lustre_swab_mgs_nidtbl_entry (struct mgs_nidtbl_entry * entry)
Definition at line 1888 of file pack_generic.c.
References __swab32s, __swab64s, __u64, CLASSERT, LASSERT, mgs_nidtbl_entry::mne_index, mgs_nidtbl_entry::mne_instance, mgs_nidtbl_entry::mne_length, mgs_nidtbl_entry::mne_nid_count, mgs_nidtbl_entry::mne_nid_type, mgs_nidtbl_entry::mne_version, mgs_nidtbl_entry::nids, and mgs_nidtbl_entry::u.
Referenced by mgc_apply_recover_logs().
void lustre_swab_mgs_target_info (struct mgs_target_info * mti)
Definition at line 1874 of file pack_generic.c.
References __swab32s, __swab64s, __u64, CLASSERT, mgs_target_info::mti_config_ver, mgs_target_info::mti_flags, mgs_target_info::mti_instance, mgs_target_info::mti_lustre_ver, mgs_target_info::mti_nid_count, mgs_target_info::mti_nids, MTI_NIDS_MAX, and mgs_target_info::mti_stripe_index.
void lustre_swab_niobuf_remote (struct niobuf_remote * nbr)
Definition at line 1766 of file pack_generic.c.
References __swab32s, __swab64s, niobuf_remote::rnb_flags, niobuf_remote::rnb_len, and niobuf_remote::rnb_offset.
static void lustre_swab_obd_dqblk (struct obd_dqblk * b) [static]
Definition at line 1932 of file pack_generic.c.
References __swab32s, __swab64s, CLASSERT, obd_dqblk::dqb_bhardlimit, obd_dqblk::dqb_bsoftlimit, obd_dqblk::dqb_btime, obd_dqblk::dqb_curinodes, obd_dqblk::dqb_curspace, obd_dqblk::dqb_ihardlimit, obd_dqblk::dqb_isoftlimit, obd_dqblk::dqb_itime, obd_dqblk::dqb_valid, and offsetof.
Referenced by lustre_swab_obd_quotactl().
static void lustre_swab_obd_dqinfo (struct obd_dqinfo * i) [static]
Definition at line 1924 of file pack_generic.c.
References __swab32s, __swab64s, obd_dqinfo::dqi_bgrace, obd_dqinfo::dqi_flags, obd_dqinfo::dqi_igrace, and obd_dqinfo::dqi_valid.
Referenced by lustre_swab_obd_quotactl().
void lustre_swab_obd_ioobj (struct obd_ioobj * ioo)
Definition at line 1759 of file pack_generic.c.
References __swab32s, obd_ioobj::ioo_bufcnt, obd_ioobj::ioo_max_brw, obd_ioobj::ioo_oid, and lustre_swab_ost_id.
void lustre_swab_obd_quotactl (struct obd_quotactl * q)
Definition at line 1946 of file pack_generic.c.
References __swab32s, lustre_swab_obd_dqblk(), lustre_swab_obd_dqinfo(), obd_quotactl::qc_cmd, obd_quotactl::qc_dqblk, obd_quotactl::qc_dqinfo, obd_quotactl::qc_id, obd_quotactl::qc_stat, and obd_quotactl::qc_type.
void lustre_swab_obd_statfs (struct obd_statfs * os)
Definition at line 1735 of file pack_generic.c.
References __swab32s, __swab64s, CLASSERT, offsetof, obd_statfs::os_bavail, obd_statfs::os_bfree, obd_statfs::os_blocks, obd_statfs::os_bsize, obd_statfs::os_ffree, obd_statfs::os_files, obd_statfs::os_maxbytes, obd_statfs::os_namelen, obd_statfs::os_state, and obd_statfs::os_type.
void lustre_swab_obdo (struct obdo * o)
Definition at line 1701 of file pack_generic.c.
References __swab32s, __swab64s, CLASSERT, lustre_swab_ost_id, obdo::o_atime, obdo::o_blksize, obdo::o_blocks, obdo::o_ctime, obdo::o_data_version, obdo::o_flags, obdo::o_gid, obdo::o_gid_h, obdo::o_grant, obdo::o_ioepoch, obdo::o_misc, obdo::o_mode, obdo::o_mtime, obdo::o_nlink, obdo::o_oi, obdo::o_parent_oid, obdo::o_parent_seq, obdo::o_parent_ver, obdo::o_size, obdo::o_stripe_idx, obdo::o_uid, obdo::o_uid_h, obdo::o_valid, and offsetof.
Referenced by lustre_swab_ost_body(), osp_get_attr_from_reply(), out_attr_set(), out_create(), update_recovery_attr_set(), and update_recovery_create().
void lustre_swab_object_update (struct object_update * ou)
Definition at line 2518 of file pack_generic.c.
References __swab16s, __swab32s, __swab64s, lustre_swab_lu_fid, object_update_param_size(), object_update::ou_batchid, object_update::ou_fid, object_update::ou_flags, object_update::ou_padding1, object_update::ou_params, object_update::ou_params_count, object_update::ou_result_size, object_update::ou_type, object_update_param::oup_len, object_update_param::oup_padding, and object_update_param::oup_padding2.
void lustre_swab_object_update_reply (struct object_update_reply * our)
Definition at line 2563 of file pack_generic.c.
References __swab16s, __swab32s, lustre_swab_object_update_result, object_update_result_get(), object_update_reply::ourp_count, object_update_reply::ourp_lens, object_update_reply::ourp_magic, and object_update_reply::ourp_padding.
void lustre_swab_object_update_request (struct object_update_request * our)
Definition at line 2540 of file pack_generic.c.
References __swab16s, __swab32s, lustre_swab_object_update, object_update_request_get(), object_update_request::ourq_count, object_update_request::ourq_magic, and object_update_request::ourq_padding.
void lustre_swab_object_update_result (struct object_update_result * our)
Definition at line 2556 of file pack_generic.c.
References __swab16s, __swab32s, object_update_result::our_datalen, object_update_result::our_padding, and object_update_result::our_rc.
void lustre_swab_orphan_ent (struct lu_orphan_ent * ent)
Definition at line 2634 of file pack_generic.c.
References __swab32s, lu_orphan_ent::loe_key, lu_orphan_ent::loe_rec, lu_orphan_rec::lor_fid, lu_orphan_rec::lor_gid, lu_orphan_rec::lor_uid, and lustre_swab_lu_fid.
Referenced by osp_orphan_it_next().
void lustre_swab_ost_body (struct ost_body * b)
Definition at line 1773 of file pack_generic.c.
References lustre_swab_obdo(), and ost_body::oa.
void lustre_swab_ost_last_id (u64 * id)
Definition at line 1778 of file pack_generic.c.
References __swab64s.
void lustre_swab_ost_lvb (struct ost_lvb * lvb)
Definition at line 1809 of file pack_generic.c.
References __swab32s, __swab64s, ost_lvb::lvb_atime, ost_lvb::lvb_atime_ns, ost_lvb::lvb_blocks, ost_lvb::lvb_ctime, ost_lvb::lvb_ctime_ns, ost_lvb::lvb_mtime, ost_lvb::lvb_mtime_ns, ost_lvb::lvb_padding, and ost_lvb::lvb_size.
void lustre_swab_ost_lvb_v1 (struct ost_lvb_v1 * lvb)
Definition at line 1799 of file pack_generic.c.
References __swab64s, ost_lvb_v1::lvb_atime, ost_lvb_v1::lvb_blocks, ost_lvb_v1::lvb_ctime, ost_lvb_v1::lvb_mtime, and ost_lvb_v1::lvb_size.
void lustre_swab_out_update_buffer (struct out_update_buffer * oub)
Definition at line 2590 of file pack_generic.c.
References __swab32s, out_update_buffer::oub_padding, and out_update_buffer::oub_size.
void lustre_swab_out_update_header (struct out_update_header * ouh)
Definition at line 2581 of file pack_generic.c.
References __swab32s, out_update_header::ouh_count, out_update_header::ouh_inline_length, out_update_header::ouh_magic, and out_update_header::ouh_reply_size.
void lustre_swab_ptlrpc_body (struct ptlrpc_body * b)
Definition at line 1621 of file pack_generic.c.
References __swab16s, __swab32s, __swab64s, CLASSERT, and offsetof.
void lustre_swab_quota_body (struct quota_body * b)
Definition at line 2270 of file pack_generic.c.
References __swab32s, __swab64s, lustre_swab_lu_fid, quota_body::qb_count, quota_body::qb_fid, quota_body::qb_flags, quota_body::qb_id, quota_body::qb_slv_ver, and quota_body::qb_usage.
void lustre_swab_swap_layouts (struct mdc_swap_layouts * msl)
Definition at line 2597 of file pack_generic.c.
References __swab64s, and mdc_swap_layouts::msl_flags.
static int lustre_unpack_msg_v2 (struct lustre_msg_v2 * m, int len) [static]
Definition at line 524 of file pack_generic.c.
References __swab32s, CERROR, cfs_size_round(), CLASSERT, lustre_msg_v2::lm_bufcount, lustre_msg_v2::lm_buflens, lustre_msg_v2::lm_cksum, lustre_msg_v2::lm_flags, lustre_msg_v2::lm_magic, lustre_msg_v2::lm_repsize, lustre_msg_v2::lm_secflvr, lustre_msg_hdr_size_v2(), LUSTRE_MSG_MAGIC_V2_SWABBED, and offsetof.
Referenced by __lustre_unpack_msg().
static int lustre_unpack_ptlrpc_body_v2 (struct ptlrpc_request * req, const int inout, int offset) [inline, static]
Definition at line 622 of file pack_generic.c.
References CERROR, lustre_msg_buf_v2(), lustre_swab_ptlrpc_body, LUSTRE_VERSION_MASK, ptlrpc_body, ptlrpc_buf_need_swab(), ptlrpc_buf_set_swabbed(), PTLRPC_MSG_VERSION, ptlrpc_status_ntoh(), ptlrpc_request::rq_repmsg, and ptlrpc_request::rq_reqmsg.
Referenced by lustre_unpack_rep_ptlrpc_body(), and lustre_unpack_req_ptlrpc_body().
int lustre_unpack_rep_ptlrpc_body (struct ptlrpc_request * req, int offset)
Definition at line 661 of file pack_generic.c.
References CERROR, LUSTRE_MSG_MAGIC_V2, lustre_unpack_ptlrpc_body_v2(), and ptlrpc_request::rq_repmsg.
Referenced by unpack_reply().
int lustre_unpack_req_ptlrpc_body (struct ptlrpc_request * req, int offset)
Definition at line 649 of file pack_generic.c.
References CERROR, LUSTRE_MSG_MAGIC_V2, lustre_unpack_ptlrpc_body_v2(), and ptlrpc_request::rq_reqmsg.
Referenced by ptlrpc_server_handle_req_in().
static int rep_ptlrpc_body_swabbed (struct ptlrpc_request * req) [inline, static]
Definition at line 2379 of file pack_generic.c.
References LASSERT, LUSTRE_MSG_MAGIC_V2, lustre_rep_swabbed(), MSG_PTLRPC_BODY_OFF, and ptlrpc_request::rq_repmsg.
Referenced by _debug_req().
static int req_ptlrpc_body_swabbed (struct ptlrpc_request * req) [inline, static]
Definition at line 2365 of file pack_generic.c.
References CERROR, LASSERT, LUSTRE_MSG_MAGIC_V2, lustre_req_swabbed(), MSG_PTLRPC_BODY_OFF, and ptlrpc_request::rq_reqmsg.
Referenced by _debug_req().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.