Lustre: lustre/contrib/wireshark/packet-lustre.c File Reference
lustre/contrib/wireshark/packet-lustre.c File Reference
#include <glib.h>
#include <string.h>
#include <epan/packet.h>
#include <epan/dissectors/packet-windows-common.h>
#include "lustre_dlm_flags.h"
#include "lustre_dlm_flags_wshark.c"
Defines
#define LUSTRE_MAGIC_OFFSET 8
#define LUSTRE_MSG_MAGIC_V1 0x0BD00BD0
#define LUSTRE_MSG_MAGIC_V2 0x0BD00BD3
#define LUSTRE_BUFCOUNT_OFF ((tvb_get_letohl(tvb, LUSTRE_MAGIC_OFFSET)== LUSTRE_MSG_MAGIC_V2) ? 0 : 60)
#define LUSTRE_BUFCOUNT
#define LUSTRE_BUFLEN_OFF ((tvb_get_letohl(tvb, LUSTRE_MAGIC_OFFSET)== LUSTRE_MSG_MAGIC_V2) ? 32 : 60)
#define LUSTRE_BUFFER_LEN(_n)
#define LUSTRE_REQ_REC_OFF 1
#define LUSTRE_REPLY_REC_OFF 1
#define LUSTRE_DLM_INTENT_IT_OFF 2
#define LUSTRE_DLM_INTENT_REC_OFF 3
#define LUSTRE_DLM_LOCKREPLY_OFF 1
#define LUSTRE_DLM_REPLY_REC_OFF 2
#define LUSTRE_PTLRPC_MSG_VERSION 0x00000003
#define LUSTRE_VERSION_MASK 0xffff0000
#define LUSTRE_OBD_VERSION 0x00010000
#define LUSTRE_MDS_VERSION 0x00020000
#define LUSTRE_OST_VERSION 0x00030000
#define LUSTRE_DLM_VERSION 0x00040000
#define LUSTRE_LOG_VERSION 0x00050000
#define LUSTRE_MGS_VERSION 0x00060000
#define LOV_MAGIC_V1 0x0BD10BD0
#define LOV_MAGIC LOV_MAGIC_V1
#define LOV_MAGIC_JOIN_V1 0x0BD20BD0
#define OBD_FIRST_OPC OBD_PING
#define IT_OPEN 0x0001
#define IT_CREAT 0x0002
#define IT_READDIR 0x0004
#define IT_GETATTR 0x0008
#define IT_LOOKUP 0x0010
#define IT_UNLINK 0x0020
#define IT_GETXATTR 0x0040
#define IT_EXEC 0x0080
#define IT_PIN 0x0100
#define MDS_FIRST_OPC MDS_GETATTR
#define LDLM_FIRST_OPC LDLM_ENQUEUE
#define LDLM_FIRST_OPC LDLM_ENQUEUE
#define LDLM_ENQUEUE (101)
#define LDLM_CONVERT (102)
#define LDLM_CANCEL (103)
#define LDLM_BL_CALLBACK (104)
#define LDLM_CP_CALLBACK (105)
#define LDLM_GL_CALLBACK (106)
#define LCK_MINMODE (0)
#define LCK_EX (1)
#define LCK_PW (2)
#define LCK_PR (4)
#define LCK_CW (8)
#define LCK_CR (16)
#define LCK_NL (32)
#define LCK_GROUP (64)
#define LDLM_PLAIN (10)
#define LDLM_EXTENT (11)
#define LDLM_FLOCK (12)
#define LDLM_IBITS (13)
#define OBD_PING (400)
#define MGS_FIRST_OPC MGS_CONNECT
#define LLOG_FIRST_OPC LLOG_ORIGIN_HANDLE_CREATE
#define LLOG_OP_MAGIC 0x10600000
#define LLOG_OP_MASK 0xfff00000
#define LLOG_F_ZAP_WHEN_EMPTY 0x1
#define LLOG_F_IS_CAT 0x2
#define LLOG_F_IS_PLAIN 0x4
#define PTL_RPC_MSG_REQUEST 4711
#define PTL_RPC_MSG_ERR 4712
#define PTL_RPC_MSG_REPLY 4713
#define hf_lustre_ldlm_ast_discard_data hf_lustre_ldlm_fl_ast_discard_data
#define WSHARK_HEAD
#define WSHARK_INIT_DATA
Typedefs
typedef int(dissect_func)(tvbuff_t *tvb, gint offset, packet_info *pinfo _U_, proto_tree *tree, int hfindex)
Enumerations
enum portal_index_t {
CONNMGR_REQUEST_PORTAL = 1, CONNMGR_REPLY_PORTAL = 2, OSC_REQUEST_PORTAL = 3, OSC_REPLY_PORTAL = 4,
OSC_BULK_PORTAL = 5, OST_IO_PORTAL = 6, OST_CREATE_PORTAL = 7, OST_BULK_PORTAL = 8,
MDC_REQUEST_PORTAL = 9, MDC_REPLY_PORTAL = 10, MDC_BULK_PORTAL = 11, MDS_REQUEST_PORTAL = 12,
MDS_REPLY_PORTAL = 13, MDS_BULK_PORTAL = 14, LDLM_CB_REQUEST_PORTAL = 15, LDLM_CB_REPLY_PORTAL = 16,
LDLM_CANCEL_REQUEST_PORTAL = 17, LDLM_CANCEL_REPLY_PORTAL = 18, PTLBD_REQUEST_PORTAL = 19, PTLBD_REPLY_PORTAL = 20,
PTLBD_BULK_PORTAL = 21, MDS_SETATTR_PORTAL = 22, MDS_READPAGE_PORTAL = 23, MDS_MDS_PORTAL = 24,
MGC_REPLY_PORTAL = 25, MGS_REQUEST_PORTAL = 26, MGS_REPLY_PORTAL = 27, OST_REQUEST_PORTAL = 28,
FLD_REQUEST_PORTAL = 29, SEQ_METADATA_PORTAL = 30, SEQ_DATA_PORTAL = 31, SEQ_CONTROLLER_PORTAL = 32,
MGS_BULK_PORTAL = 33
}
enum ost_cmd_t {
OST_REPLY = 0, OST_GETATTR = 1, OST_SETATTR = 2, OST_READ = 3,
OST_WRITE = 4, OST_CREATE = 5, OST_DESTROY = 6, OST_GET_INFO = 7,
OST_CONNECT = 8, OST_DISCONNECT = 9, OST_PUNCH = 10, OST_OPEN = 11,
OST_CLOSE = 12, OST_STATFS = 13, OST_SYNC = 16, OST_SET_INFO = 17,
OST_QUOTACHECK = 18, OST_QUOTACTL = 19, OST_QUOTA_ADJUST_QUNIT = 20, OST_LADVISE = 21,
OST_LAST_OPC, OST_REPLY = 0, OST_GETATTR = 1, OST_SETATTR = 2,
OST_READ = 3, OST_WRITE = 4, OST_CREATE = 5, OST_DESTROY = 6,
OST_GET_INFO = 7, OST_CONNECT = 8, OST_DISCONNECT = 9, OST_PUNCH = 10,
OST_OPEN = 11, OST_CLOSE = 12, OST_STATFS = 13, OST_SYNC = 16,
OST_SET_INFO = 17, OST_QUOTACHECK = 18, OST_QUOTACTL = 19, OST_QUOTA_ADJUST_QUNIT = 20,
OST_LADVISE = 21, OST_LAST_OPC
}
enum obd_cmd_t {
OBD_PING = 400, OBD_LOG_CANCEL, OBD_QC_CALLBACK, OBD_LAST_OPC,
OBD_PING = 400, OBD_LOG_CANCEL, OBD_QC_CALLBACK, OBD_IDX_READ,
OBD_LAST_OPC
}
enum mds_cmd_t {
MDS_GETATTR = 33, MDS_GETATTR_NAME = 34, MDS_CLOSE = 35, MDS_REINT = 36,
MDS_READPAGE = 37, MDS_CONNECT = 38, MDS_DISCONNECT = 39, MDS_GET_ROOT = 40,
MDS_STATFS = 41, MDS_PIN = 42, MDS_UNPIN = 43, MDS_SYNC = 44,
MDS_DONE_WRITING = 45, MDS_SET_INFO = 46, MDS_QUOTACHECK = 47, MDS_QUOTACTL = 48,
MDS_GETXATTR = 49, MDS_SETXATTR = 50, MDS_WRITEPAGE = 51, MDS_IS_SUBDIR = 52,
MDS_GET_INFO = 53, MDS_HSM_STATE_GET = 54, MDS_HSM_STATE_SET = 55, MDS_HSM_ACTION = 56,
MDS_HSM_PROGRESS = 57, MDS_HSM_REQUEST = 58, MDS_HSM_CT_REGISTER = 59, MDS_HSM_CT_UNREGISTER = 60,
MDS_SWAP_LAYOUTS = 61, MDS_LAST_OPC, MDS_GETATTR = 33, MDS_GETATTR_NAME = 34,
MDS_CLOSE = 35, MDS_REINT = 36, MDS_READPAGE = 37, MDS_CONNECT = 38,
MDS_DISCONNECT = 39, MDS_GET_ROOT = 40, MDS_STATFS = 41, MDS_PIN = 42,
MDS_UNPIN = 43, MDS_SYNC = 44, MDS_DONE_WRITING = 45, MDS_SET_INFO = 46,
MDS_QUOTACHECK = 47, MDS_QUOTACTL = 48, MDS_GETXATTR = 49, MDS_SETXATTR = 50,
MDS_WRITEPAGE = 51, MDS_IS_SUBDIR = 52, MDS_GET_INFO = 53, MDS_HSM_STATE_GET = 54,
MDS_HSM_STATE_SET = 55, MDS_HSM_ACTION = 56, MDS_HSM_PROGRESS = 57, MDS_HSM_REQUEST = 58,
MDS_HSM_CT_REGISTER = 59, MDS_HSM_CT_UNREGISTER = 60, MDS_SWAP_LAYOUTS = 61, MDS_LAST_OPC
}
enum mds_reint_t {
REINT_SETATTR = 1, REINT_CREATE = 2, REINT_LINK = 3, REINT_UNLINK = 4,
REINT_RENAME = 5, REINT_OPEN = 6, REINT_SETXATTR = 7, REINT_MAX,
REINT_SETATTR = 1, REINT_CREATE = 2, REINT_LINK = 3, REINT_UNLINK = 4,
REINT_RENAME = 5, REINT_OPEN = 6, REINT_SETXATTR = 7, REINT_RMENTRY = 8,
REINT_MIGRATE = 9, REINT_MAX
}
enum ldlm_cmd {
LDLM_ENQUEUE = 101, LDLM_CONVERT = 102, LDLM_CANCEL = 103, LDLM_BL_CALLBACK = 104,
LDLM_CP_CALLBACK = 105, LDLM_GL_CALLBACK = 106, LDLM_LAST_OPC
}
enum seq_rpc_opc {
SEQ_QUERY = 700, SEQ_LAST_OPC, SEQ_FIRST_OPC = SEQ_QUERY, SEQ_QUERY = 700,
SEQ_LAST_OPC, SEQ_FIRST_OPC = SEQ_QUERY
}
enum fld_rpc_opc {
FLD_QUERY = 900, FLD_LAST_OPC, FLD_FIRST_OPC = FLD_QUERY, FLD_QUERY = 900,
FLD_READ = 901, FLD_LAST_OPC, FLD_FIRST_OPC = FLD_QUERY
}
enum mgs_cmd_t {
MGS_CONNECT = 250, MGS_DISCONNECT, MGS_EXCEPTION, MGS_TARGET_REG,
MGS_TARGET_DEL, MGS_SET_INFO, MGS_CONFIG_READ, MGS_LAST_OPC,
MGS_CONNECT = 250, MGS_DISCONNECT, MGS_EXCEPTION, MGS_TARGET_REG,
MGS_TARGET_DEL, MGS_SET_INFO, MGS_CONFIG_READ, MGS_LAST_OPC
}
enum llog_cmd_t {
LLOG_ORIGIN_HANDLE_CREATE = 501, LLOG_ORIGIN_HANDLE_NEXT_BLOCK = 502, LLOG_ORIGIN_HANDLE_READ_HEADER = 503, LLOG_ORIGIN_HANDLE_WRITE_REC = 504,
LLOG_ORIGIN_HANDLE_CLOSE = 505, LLOG_ORIGIN_CONNECT = 506, LLOG_CATINFO = 507, LLOG_ORIGIN_HANDLE_PREV_BLOCK = 508,
LLOG_ORIGIN_HANDLE_DESTROY = 509, LLOG_LAST_OPC
}
enum llog_op_type {
LLOG_PAD_MAGIC = LLOG_OP_MAGIC | 0x00000, OST_SZ_REC = LLOG_OP_MAGIC | 0x00f00, OST_RAID1_REC = LLOG_OP_MAGIC | 0x01000, MDS_UNLINK_REC = LLOG_OP_MAGIC | 0x10000 | (MDS_REINT << 8) | REINT_UNLINK,
MDS_SETATTR_REC = LLOG_OP_MAGIC | 0x10000 | (MDS_REINT << 8) | REINT_SETATTR, OBD_CFG_REC = LLOG_OP_MAGIC | 0x20000, PTL_CFG_REC = LLOG_OP_MAGIC | 0x30000, LLOG_GEN_REC = LLOG_OP_MAGIC | 0x40000,
LLOG_JOIN_REC = LLOG_OP_MAGIC | 0x50000, LLOG_HDR_MAGIC = LLOG_OP_MAGIC | 0x45539, LLOG_LOGID_MAGIC = LLOG_OP_MAGIC | 0x4553b, LLOG_PAD_MAGIC = LLOG_OP_MAGIC | 0x00000,
OST_SZ_REC = LLOG_OP_MAGIC | 0x00f00, MDS_UNLINK_REC, MDS_UNLINK64_REC, MDS_SETATTR64_REC,
OBD_CFG_REC = LLOG_OP_MAGIC | 0x20000, LLOG_GEN_REC = LLOG_OP_MAGIC | 0x40000, CHANGELOG_REC = LLOG_OP_MAGIC | 0x60000, CHANGELOG_USER_REC = LLOG_OP_MAGIC | 0x70000,
HSM_AGENT_REC = LLOG_OP_MAGIC | 0x80000, UPDATE_REC = LLOG_OP_MAGIC | 0xa0000, LLOG_HDR_MAGIC = LLOG_OP_MAGIC | 0x45539, LLOG_LOGID_MAGIC = LLOG_OP_MAGIC | 0x4553b
}
Functions
static int ldlm_opcode_process (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, guint64 intent_opc _U_)
static int add_extra_padding (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
void plugin_register (void)
void plugin_reg_handoff (void)
static void display_info_str (proto_item *pi, column_info *cinfo, gint col, const gchar *str)
static void display_info_fstr (proto_item *pi, column_info *cinfo, gint col, const char *format, const gchar *str)
static int dissect_uint64 (tvbuff_t *tvb, gint offset, packet_info *pinfo _U_, proto_tree *tree, int hfindex)
static int dissect_uint32 (tvbuff_t *tvb, gint offset, packet_info *pinfo _U_, proto_tree *tree, int hfindex)
static int dissect_uint16 (tvbuff_t *tvb, gint offset, packet_info *pinfo _U_, proto_tree *tree, int hfindex)
static int dissect_uint8 (tvbuff_t *tvb, gint offset, packet_info *pinfo _U_, proto_tree *tree, int hfindex)
static int lustre_dissect_element_data (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_, guint32 buf_num)
int lustre_dissect_struct_hmac (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_, int max_length)
static int lustre_dissect_element_handle_cookie (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_handle_cookie (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_obd_connect_data_ocd_connect_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_connect_data_ocd_version (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_connect_data_ocd_grant (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_connect_data_ocd_index (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_connect_data_ocd_brw_size (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_connect_data_ocd_ibits_known (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_connect_data_ocd_nllu (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_connect_data_ocd_nllg (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_connect_data_ocd_transno (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_connect_data_ocd_group (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_connect_data_ocd_cksum_types (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_connect_data_padding1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_connect_data_padding2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_struct_obd_connect_data (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_lov_ost_data_v1_l_object_id (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_lov_ost_data_v1_l_object_seq (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_lov_ost_data_v1_l_ost_gen (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_lov_ost_data_v1_l_ost_idx (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_lov_ost_data_v1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_lov_mds_md_v1_lmm_magic (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_lov_mds_md_v1_lmm_pattern (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_lov_mds_md_v1_lmm_object_id (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_lov_mds_md_v1_lmm_object_seq (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_lov_mds_md_v1_lmm_stripe_size (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_lov_mds_md_v1_lmm_stripe_count (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_lov_mds_md_v1_lmm_objects_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_lov_mds_md_v1_lmm_objects (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, int num)
int lustre_dissect_struct_lov_mds_md_v1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
int lustre_dissect_struct_lov_mds_md (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_, int buff_num _U_)
static int lustre_dissect_element_obd_statfs_os_type (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_statfs_os_blocks (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_statfs_os_bfree (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_statfs_os_bavail (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_statfs_os_files (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_statfs_os_ffree (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_statfs_os_fsid_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_statfs_os_fsid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_statfs_os_bsize (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_statfs_os_namelen (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_statfs_os_maxbytes (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_statfs_os_state (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_statfs_os_spare1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_statfs_os_spare2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_statfs_os_spare3 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_statfs_os_spare4 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_statfs_os_spare5 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_statfs_os_spare6 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_statfs_os_spare7 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_statfs_os_spare8 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_statfs_os_spare9 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_obd_statfs (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_obd_ioobj_ioo_id (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_ioobj_ioo_seq (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_ioobj_ioo_max_brw (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_ioobj_ioo_bufcnt (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_obd_ioobj (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_niobuf_remote_offset (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_niobuf_remote_len (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_niobuf_remote_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_niobuf_remote (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_ost_lvb_lvb_size (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ost_lvb_lvb_mtime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ost_lvb_lvb_atime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ost_lvb_lvb_ctime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ost_lvb_lvb_blocks (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_ost_lvb (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_ll_fid_id (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ll_fid_generation (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ll_fid_f_type (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_lu_fid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_obd_dqinfo_dqi_bgrace (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_dqinfo_dqi_igrace (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_dqinfo_dqi_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_dqinfo_dqi_valid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_obd_dqinfo (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_obd_dqblk_dqb_bhardlimit (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_dqblk_dqb_bsoftlimit (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_dqblk_dqb_curspace (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_dqblk_dqb_ihardlimit (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_dqblk_dqb_isoftlimit (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_dqblk_dqb_curinodes (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_dqblk_dqb_btime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_dqblk_dqb_itime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_dqblk_dqb_valid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_dqblk_padding (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_obd_dqblk (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_obd_quotactl_qc_cmd (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_quotactl_qc_type (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_quotactl_qc_id (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_quotactl_qc_stat (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_quotactl_qc_dqblk (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obd_quotactl_qc_dqinfo (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_obd_quotactl (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_quota_adjust_qunit_qaq_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_quota_adjust_qunit_qaq_id (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_quota_adjust_qunit_qaq_bunit_sz (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_quota_adjust_qunit_qaq_iunit_sz (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_quota_adjust_qunit_padding1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_quota_adjust_qunit (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_mdt_body_fid1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_fid2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_handle (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_valid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_size (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_mtime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_atime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_ctime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_blocks (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_ioepoch (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_ino (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_fsuid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_fsgid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_capability (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_mode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_uid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_gid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_rdev (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_nlink (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_generation (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_suppgid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_eadatasize (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_aclsize (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_max_mdsize (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_max_cookiesize (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_uid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_gid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_padding_5 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_padding_6 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_padding_7 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_padding_8 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_padding_9 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_body_padding_10 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_mdt_body (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_mdt_rec_setattr_sa_opcode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setattr_sa_cap (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setattr_sa_fsuid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setattr_sa_fsuid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setattr_sa_fsgid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setattr_sa_fsgid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setattr_sa_suppgid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setattr_sa_suppgid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setattr_sa_padding_1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setattr_sa_padding_1_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setattr_sa_fid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setattr_sa_valid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setattr_sa_uid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setattr_sa_gid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setattr_sa_size (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setattr_sa_blocks (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setattr_sa_mtime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setattr_sa_atime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setattr_sa_ctime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setattr_sa_attr_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setattr_sa_mode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setattr_sa_padding_2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setattr_sa_padding_3 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setattr_sa_padding_4 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setattr_sa_padding_5 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_mdt_rec_setattr (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_mdt_rec_create_cr_opcode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_create_cr_cap (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_create_cr_fsuid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_create_cr_fsuid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_create_cr_fsgid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_create_cr_fsgid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_create_cr_suppgid1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_create_cr_suppgid1_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_create_cr_suppgid2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_create_cr_suppgid2_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_create_cr_fid1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_create_cr_fid2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_create_cr_old_handle (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_create_cr_time (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_create_cr_rdev (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_create_cr_ioepoch (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_create_cr_padding_1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_create_cr_mode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_create_cr_bias (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_create_cr_flags_l (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_create_cr_flags_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_create_cr_umask (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_create_cr_padding_4 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_mdt_rec_create (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_mdt_rec_link_lk_opcode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_link_lk_cap (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_link_lk_fsuid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_link_lk_fsuid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_link_lk_fsgid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_link_lk_fsgid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_link_lk_suppgid1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_link_lk_suppgid1_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_link_lk_suppgid2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_link_lk_suppgid2_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_link_lk_fid1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_link_lk_fid2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_link_lk_time (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_link_lk_padding_1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_link_lk_padding_2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_link_lk_padding_3 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_link_lk_padding_4 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_link_lk_bias (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_link_lk_padding_5 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_link_lk_padding_6 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_link_lk_padding_7 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_link_lk_padding_8 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_link_lk_padding_9 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_mdt_rec_link (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_mdt_rec_unlink_ul_opcode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_unlink_ul_cap (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_unlink_ul_fsuid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_unlink_ul_fsuid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_unlink_ul_fsgid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_unlink_ul_fsgid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_unlink_ul_suppgid1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_unlink_ul_suppgid1_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_unlink_ul_suppgid2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_unlink_ul_suppgid2_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_unlink_ul_fid1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_unlink_ul_fid2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_unlink_ul_time (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_unlink_ul_padding_2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_unlink_ul_padding_3 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_unlink_ul_padding_4 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_unlink_ul_padding_5 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_unlink_ul_bias (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_unlink_ul_mode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_unlink_ul_padding_6 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_unlink_ul_padding_7 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_unlink_ul_padding_8 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_unlink_ul_padding_9 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_mdt_rec_unlink (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_mdt_rec_rename_rn_opcode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_rename_rn_cap (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_rename_rn_fsuid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_rename_rn_fsuid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_rename_rn_fsgid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_rename_rn_fsgid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_rename_rn_suppgid1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_rename_rn_suppgid1_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_rename_rn_suppgid2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_rename_rn_suppgid2_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_rename_rn_fid1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_rename_rn_fid2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_rename_rn_time (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_rename_rn_padding_1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_rename_rn_padding_2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_rename_rn_padding_3 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_rename_rn_padding_4 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_rename_rn_bias (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_rename_rn_mode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_rename_rn_padding_5 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_rename_rn_padding_6 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_rename_rn_padding_7 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_rename_rn_padding_8 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_mdt_rec_rename (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_mdt_rec_setxattr_sx_opcode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setxattr_sx_cap (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setxattr_sx_fsuid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setxattr_sx_fsuid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setxattr_sx_fsgid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setxattr_sx_fsgid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setxattr_sx_suppgid1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setxattr_sx_suppgid1_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setxattr_sx_suppgid2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setxattr_sx_suppgid2_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setxattr_sx_fid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setxattr_sx_padding_1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setxattr_sx_padding_2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setxattr_sx_padding_3 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setxattr_sx_valid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setxattr_sx_time (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setxattr_sx_padding_5 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setxattr_sx_padding_6 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setxattr_sx_padding_7 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setxattr_sx_size (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setxattr_sx_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setxattr_sx_padding_8 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setxattr_sx_padding_9 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setxattr_sx_padding_10 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mdt_rec_setxattr_sx_padding_11 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_mdt_rec_setxattr (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_lov_desc_ld_tgt_count (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_lov_desc_ld_active_tgt_count (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_lov_desc_ld_default_stripe_count (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_lov_desc_ld_pattern (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_lov_desc_ld_default_stripe_size (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_lov_desc_ld_default_stripe_offset (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_lov_desc_ld_padding_0 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_lov_desc_ld_qos_maxage (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_lov_desc_ld_padding_1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_lov_desc_ld_padding_2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_lov_desc_ld_uuid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_lov_desc (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_struct_obd_uuid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_ldlm_res_id_name_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ldlm_res_id_name (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_ldlm_res_id (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
int lustre_dissect_enum_ldlm_mode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, int hf_index _U_)
int lustre_dissect_enum_ldlm_type (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, int hf_index _U_)
static int lustre_dissect_element_ldlm_extent_start (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ldlm_extent_end (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ldlm_extent_gid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_ldlm_extent (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_ldlm_inodebits_bits (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_ldlm_inodebits (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_ldlm_flock_start (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ldlm_flock_end (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ldlm_flock_blocking_export (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ldlm_flock_blocking_pid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ldlm_flock_pid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_ldlm_flock (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_ldlm_intent_opc (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_ldlm_intent (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_ldlm_resource_desc_lr_type (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ldlm_resource_desc_lr_padding (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ldlm_resource_desc_lr_name (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_ldlm_resource_desc (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_ldlm_lock_desc_l_resource (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ldlm_lock_desc_l_req_mode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ldlm_lock_desc_l_granted_mode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ldlm_lock_desc_l_policy_data (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_ldlm_lock_desc (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_ldlm_request_lock_count (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ldlm_request_lock_desc (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ldlm_request_lock_handle_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ldlm_request_lock_handle (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, int num_locks _U_)
int lustre_dissect_struct_ldlm_request (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_ldlm_reply_lock_padding (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ldlm_reply_lock_desc (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ldlm_reply_lock_handle (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ldlm_reply_lock_policy_res1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ldlm_reply_lock_policy_res2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_ldlm_reply (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_, guint32 *ldlm_type _U_)
static int lustre_dissect_element_mgs_send_param_mgs_param_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mgs_send_param_mgs_param (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_mgs_send_param (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
int lustre_dissect_element_mgs_config_body_name (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
int lustre_dissect_struct_mgs_config_body (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
int lustre_dissect_struct_mgs_config_res (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_mgs_target_info_mti_lustre_ver (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mgs_target_info_mti_stripe_index (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mgs_target_info_mti_config_ver (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mgs_target_info_mti_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mgs_target_info_mti_nid_count (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mgs_target_info_padding (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mgs_target_info_mti_fsname_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mgs_target_info_mti_fsname (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mgs_target_info_mti_svname_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mgs_target_info_mti_svname (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mgs_target_info_mti_uuid_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mgs_target_info_mti_uuid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mgs_target_info_mti_nids_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mgs_target_info_mti_nids (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mgs_target_info_mti_params_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_mgs_target_info_mti_params (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_mgs_target_info (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_cfg_marker_cm_step (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_cfg_marker_cm_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_cfg_marker_cm_vers (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_cfg_marker_padding (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_cfg_marker_cm_createtime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_cfg_marker_cm_canceltime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_cfg_marker_cm_tgtname_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_cfg_marker_cm_tgtname (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_cfg_marker_cm_comment_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_cfg_marker_cm_comment (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_cfg_marker (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_llog_logid_lgl_oid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_logid_lgl_oseq (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_logid_lgl_ogen (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_llog_logid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_llog_catid_lci_logid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_catid_lci_padding1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_catid_lci_padding2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_catid_lci_padding3 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_llog_catid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_llog_rec_hdr_lrh_len (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_rec_hdr_lrh_index (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_rec_hdr_lrh_type (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_rec_hdr_padding (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_llog_rec_hdr (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_llog_rec_tail_lrt_len (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_rec_tail_lrt_index (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_llog_rec_tail (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_llog_logid_rec_lid_hdr (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_logid_rec_lid_id (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_logid_rec_padding1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_logid_rec_padding2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_logid_rec_padding3 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_logid_rec_padding4 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_logid_rec_padding5 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_logid_rec_lid_tail (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_llog_logid_rec (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_llog_unlink_rec_lur_hdr (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_unlink_rec_lur_oid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_unlink_rec_lur_ogen (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_unlink_rec_padding (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_unlink_rec_lur_tail (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_llog_unlink_rec (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_llog_setattr_rec_lsr_hdr (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_setattr_rec_lsr_oid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_setattr_rec_lsr_ogen (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_setattr_rec_lsr_uid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_setattr_rec_lsr_gid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_setattr_rec_padding (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_setattr_rec_lsr_tail (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_llog_setattr_rec (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_llog_size_change_rec_lsc_hdr (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_size_change_rec_lsc_fid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_size_change_rec_lsc_io_epoch (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_size_change_rec_padding (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_size_change_rec_lsc_tail (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_llog_size_change_rec (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_llog_gen_mnt_cnt (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_gen_conn_cnt (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_llog_gen (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_llog_gen_rec_lgr_hdr (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_gen_rec_lgr_gen (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_gen_rec_lgr_tail (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_llog_gen_rec (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_llog_log_hdr_llh_hdr (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_log_hdr_llh_timestamp (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_log_hdr_llh_count (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_log_hdr_llh_bitmap_offset (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_log_hdr_llh_size (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_log_llh_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_llog_log_hdr_llh_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_log_hdr_llh_cat_idx (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_log_hdr_llh_tgtuuid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_log_hdr_llh_reserved_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_log_hdr_llh_reserved (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_log_hdr_llh_bitmap_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_log_hdr_llh_bitmap (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_log_hdr_llh_tail (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_llog_log_hdr (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_llog_cookie_lgc_lgl (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_cookie_lgc_subsys (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_cookie_lgc_index (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llog_cookie_lgc_padding (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_llog_cookie (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_llogd_body_lgd_logid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llogd_body_lgd_ctxt_idx (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llogd_body_lgd_llh_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llogd_body_lgd_index (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llogd_body_lgd_saved_index (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llogd_body_lgd_len (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llogd_body_lgd_cur_offset (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_llogd_body (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_llogd_conn_body_lgdc_gen (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llogd_conn_body_lgdc_logid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_llogd_conn_body_lgdc_ctxt_idx (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_llogd_conn_body (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_obdo_o_valid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obdo_o_id (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obdo_o_seq (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obdo_o_parent_seq (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obdo_o_size (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obdo_o_mtime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obdo_o_atime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obdo_o_ctime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obdo_o_blocks (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obdo_o_grant (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obdo_o_blksize (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obdo_o_mode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obdo_o_uid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obdo_o_gid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obdo_o_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obdo_o_nlink (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obdo_o_parent_oid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obdo_o_misc (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obdo_o_ioepoch (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obdo_o_stripe_idx (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obdo_o_parent_ver (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obdo_o_handle (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obdo_o_lcookie (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obdo_o_uid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obdo_o_gid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obdo_o_padding_3 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obdo_o_padding_4 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obdo_o_padding_5 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_obdo_o_padding_6 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_obdo (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_ost_body_oa (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_ost_body (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_qunit_data_qd_id (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_qunit_data_qd_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_qunit_data_qd_count (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_qunit_data_qd_qunit (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_qunit_data_padding (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_qunit_data (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_qunit_data_old2_qd_id (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_qunit_data_old2_qd_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_qunit_data_old2_qd_count (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_qunit_data_old2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_qunit_data_old_qd_id (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_qunit_data_old_qd_type (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_qunit_data_old_qd_count (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_qunit_data_old_qd_isblk (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_qunit_data_old (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
int lustre_dissect_struct_seq (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
int lustre_dissect_struct_seq_range (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_)
int lustre_dissect_struct_fld_range (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_)
int lustre_dissect_struct_mdt_ioepoch (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
int lustre_dissect_element_capa_opc (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_)
lustre_capa::lc_opc
int lustre_dissect_element_capa_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_)
int lustre_dissect_struct_capa (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_, guint32 buf_num)
int lustre_dissect_struct_acl (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_, guint32 buf_num)
static int lustre_dissect_element_string (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_, guint32 buf_num)
static int reint_opcode_process (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_generic_connect (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_lu_ladvise (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_, guint32 buf_num)
static int lustre_ost_opcode_process (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, guint32 opc _U_, guint32 pb_type)
static int lustre_mds_opcode_process (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, guint32 opc _U_, guint32 pb_type)
static int lustre_ldlm_opcode_process (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, guint32 opc _U_, guint32 pb_type)
static int lustre_mgs_opcode_process (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, guint32 opc _U_, guint32 pb_type)
static int lustre_odb_opcode_process (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, guint32 opc _U_, guint32 pb_type)
static int lustre_llog_opcode_process (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, guint32 opc _U_, guint32 pb_type)
static int lustre_seq_opcode_process (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, guint32 opc _U_, guint32 pb_type)
static int lustre_fld_opcode_process (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, guint32 opc _U_, guint32 pb_type)
static int lustre_opcode_process (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, guint32 opc _U_, guint32 pb_type)
static void sanity_check (tvbuff_t *tvb, packet_info *pinfo, guint32 val_offset _U_)
static int lustre_dissect_element_msg_v1_lm_handle (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_msg_v1_lm_magic (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_msg_v1_lm_type (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_msg_v1_lm_version (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_msg_v1_lm_opc (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_msg_v1_lm_last_xid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_msg_v1_lm_last_committed (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_msg_v1_lm_transno (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_msg_v1_lm_status (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_msg_v1_lm_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_msg_v1_lm_conn_cnt (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_msg_v1_lm_bufcount (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_msg_v1_lm_buflens_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_msg_v1_lm_buflens (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_msg_v1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static int lustre_dissect_element_ptlrpc_body_pb_handle (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ptlrpc_body_pb_type (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ptlrpc_body_pb_version (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ptlrpc_body_pb_opc (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ptlrpc_body_pb_status (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ptlrpc_body_pb_last_xid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ptlrpc_body_pb_last_seen (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ptlrpc_body_pb_last_committed (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ptlrpc_body_pb_transno (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ptlrpc_body_pb_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ptlrpc_body_pb_op_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ptlrpc_body_pb_conn_cnt (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ptlrpc_body_pb_timeout (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ptlrpc_body_pb_service_time (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ptlrpc_body_pb_limit (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ptlrpc_body_pb_slv (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ptlrpc_body_pb_pre_version (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ptlrpc_body_pb_padding (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_ptlrpc_body_pb_jobid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_)
static int lustre_dissect_struct_ptlrpc_body (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_, guint32 buf_len _U_)
static int lustre_dissect_element_msg_v2_lm_bufcount (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_msg_v2_lm_secflvr (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_msg_v2_lm_magic (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_msg_v2_lm_repsize (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_msg_v2_lm_cksum (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_msg_v2_lm_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_msg_v2_lm_padding_2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_msg_v2_lm_padding_3 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
static int lustre_dissect_element_msg_v2_lm_buflens_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_)
int lustre_dissect_struct_msg_v2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
static void dissect_lustre (tvbuff_t *tvb, packet_info *pinfo, proto_tree *tree)
void proto_reg_handoff_lustre (void)
Variables
const true_false_string lnet_flags_set_truth = { "Set", "Unset" }
static const value_string portal_indices []
static gint ett_lustre_llog_log_llh_flags = -1
static gint ett_lustre = -1
static gint ett_lustre_lustre_handle_cookie = -1
static gint ett_lustre_lustre_msg_v1 = -1
static gint ett_lustre_lustre_handle_v1 = -1
static gint ett_lustre_lustre_msg_v2 = -1
static gint ett_lustre_ptlrpc_body = -1
static gint ett_lustre_lustre_handle_v2 = -1
static gint ett_lustre_obd_connect_data = -1
static gint ett_lustre_lov_mds_md_v1 = -1
static gint ett_lustre_lov_ost_data_v1 = -1
static gint ett_lustre_obd_statfs = -1
static gint ett_lustre_obd_ioobj = -1
static gint ett_lustre_niobuf_remote = -1
static gint ett_lustre_ost_lvb = -1
static gint ett_lustre_ll_fid = -1
static gint ett_lustre_mdt_body = -1
static gint ett_lustre_mdt_rec_setattr = -1
static gint ett_lustre_mdt_rec_create = -1
static gint ett_lustre_mdt_rec_link = -1
static gint ett_lustre_mdt_rec_unlink = -1
static gint ett_lustre_mdt_rec_rename = -1
static gint ett_lustre_mdt_rec_setxattr = -1
static gint ett_lustre_obd_quotactl = -1
static gint ett_lustre_obd_dqinfo = -1
static gint ett_lustre_obd_dqblk = -1
static gint ett_lustre_quota_adjust_qunit = -1
static gint ett_lustre_lov_desc = -1
static gint ett_lustre_obd_uuid = -1
static gint ett_lustre_ldlm_res_id = -1
static gint ett_lustre_ldlm_extent = -1
static gint ett_lustre_ldlm_inodebits = -1
static gint ett_lustre_ldlm_flock = -1
static gint ett_lustre_ldlm_intent_opc = -1
static gint ett_lustre_ldlm_resource_desc = -1
static gint ett_lustre_ldlm_lock_desc = -1
static gint ett_lustre_ldlm_request = -1
static gint ett_lustre_lustre_handle = -1
static gint ett_lustre_ldlm_reply = -1
static gint ett_lustre_mgs_send_param = -1
static gint ett_lustre_mgs_target_info = -1
static gint ett_lustre_mgs_config_body = -1
static gint ett_lustre_mgs_config_res = -1
static gint ett_lustre_cfg_marker = -1
static gint ett_lustre_llog_catid = -1
static gint ett_lustre_llog_rec_hdr = -1
static gint ett_lustre_llog_logid_rec = -1
static gint ett_lustre_llog_logid = -1
static gint ett_lustre_llog_rec_tail = -1
static gint ett_lustre_lov_mds_md = -1
static gint ett_lustre_llog_unlink_rec = -1
static gint ett_lustre_llog_setattr_rec = -1
static gint ett_lustre_llog_size_change_rec = -1
static gint ett_lustre_llog_gen_rec = -1
static gint ett_lustre_llog_log_hdr = -1
static gint ett_lustre_llog_cookie = -1
static gint ett_lustre_llogd_body = -1
static gint ett_lustre_llogd_conn_body = -1
static gint ett_lustre_llog_gen = -1
static gint ett_lustre_obdo = -1
static gint ett_lustre_ost_body = -1
static gint ett_lustre_qunit_data = -1
static gint ett_lustre_qunit_data_old2 = -1
static gint ett_lustre_qunit_data_old = -1
static gint ett_lustre_ldlm_lock_flags = -1
static gint ett_lustre_seq_range = -1
static gint ett_lustre_fld_range = -1
static gint ett_lustre_mdt_ioepoch = -1
static gint ett_lustre_capa = -1
static gint ett_lustre_acl = -1
static int hf_lustre_ptlrpc_body_pb = -1
static int hf_lustre_ost_body = -1
static int hf_lustre_obd_statfs = -1
static int hf_lustre_obd_quotactl = -1
static int hf_lustre_quota_adjust_qunit = -1
static int hf_lustre_extra_padding = -1
static int hf_lustre_ldlm_reply = -1
static int hf_lustre_ldlm_request = -1
static int hf_lustre_obd_uuid = -1
static int hf_lustre_obd_connect_data = -1
static int hf_lustre_ldlm_intent = -1
static int hf_lustre_obd_ioobj = -1
static int hf_lustre_niobuf_remote = -1
static int hf_lustre_ost_key = -1
static int hf_lustre_nio = -1
static int hf_lustre_ost_val = -1
static int hf_lustre_llogd_body = -1
static int hf_lustre_llogd_log_hdr = -1
static int hf_lustre_llog_logid_rec = -1
static int hf_lustre_llogd_chunk = -1
static int hf_lustre_llogd_keyword = -1
static int hf_lustre_llogd_client = -1
static int hf_lustre_llogd_name = -1
static int hf_lustre_mds_xattr_name = -1
static int hf_lustre_lov_mds_md_v1 = -1
static int hf_lustre_llog_cookie = -1
static int hf_lustre_mds_md_data = -1
static int hf_lustre_mds_reint_opcode = -1
static int hf_lustre_mds_xattr_eadata = -1
static int hf_lustre_reint_name = -1
static int hf_lustre_reint_old_name = -1
static int hf_lustre_reint_new_name = -1
static int hf_lustre_mgs_target_info = -1
static int hf_lustre_mgs_send_param = -1
static int hf_lustre_mgs_config_body = -1
static int hf_lustre_mgs_config_body_name = -1
static int hf_lustre_mgs_config_body_offset = -1
static int hf_lustre_mgs_config_body_type = -1
static int hf_lustre_mgs_config_body_reserved = -1
static int hf_lustre_mgs_config_body_bits = -1
static int hf_lustre_mgs_config_body_units = -1
static int hf_lustre_mgs_config_res = -1
static int hf_lustre_mgs_config_res_offset = -1
static int hf_lustre_mgs_config_res_size = -1
static int hf_lustre_ost_lvb = -1
static int hf_lustre_mdt_body = -1
static int hf_lustre_mdt_body_fid1 = -1
static int hf_lustre_mdt_body_fid2 = -1
static int hf_lustre_mdt_body_handle = -1
static int hf_lustre_mdt_body_valid = -1
static int hf_lustre_mdt_body_size = -1
static int hf_lustre_mdt_body_mtime = -1
static int hf_lustre_mdt_body_atime = -1
static int hf_lustre_mdt_body_ctime = -1
static int hf_lustre_mdt_body_blocks = -1
static int hf_lustre_mdt_body_ioepoch = -1
static int hf_lustre_mdt_body_ino = -1
static int hf_lustre_mdt_body_fsuid = -1
static int hf_lustre_mdt_body_fsgid = -1
static int hf_lustre_mdt_body_capability = -1
static int hf_lustre_mdt_body_mode = -1
static int hf_lustre_mdt_body_uid = -1
static int hf_lustre_mdt_body_gid = -1
static int hf_lustre_mdt_body_flags = -1
static int hf_lustre_mdt_body_rdev = -1
static int hf_lustre_mdt_body_nlink = -1
static int hf_lustre_mdt_body_generation = -1
static int hf_lustre_mdt_body_suppgid = -1
static int hf_lustre_mdt_body_eadatasize = -1
static int hf_lustre_mdt_body_aclsize = -1
static int hf_lustre_mdt_body_max_mdsize = -1
static int hf_lustre_mdt_body_max_cookiesize = -1
static int hf_lustre_mdt_body_uid_h = -1
static int hf_lustre_mdt_body_gid_h = -1
static int hf_lustre_mdt_body_padding_5 = -1
static int hf_lustre_mdt_body_padding_6 = -1
static int hf_lustre_mdt_body_padding_7 = -1
static int hf_lustre_mdt_body_padding_8 = -1
static int hf_lustre_mdt_body_padding_9 = -1
static int hf_lustre_mdt_body_padding_10 = -1
static int hf_lustre_mdt_rec_setattr = -1
static int hf_lustre_mdt_rec_setattr_sa_opcode = -1
static int hf_lustre_mdt_rec_setattr_sa_cap = -1
static int hf_lustre_mdt_rec_setattr_sa_fsuid = -1
static int hf_lustre_mdt_rec_setattr_sa_fsuid_h = -1
static int hf_lustre_mdt_rec_setattr_sa_fsgid = -1
static int hf_lustre_mdt_rec_setattr_sa_fsgid_h = -1
static int hf_lustre_mdt_rec_setattr_sa_suppgid = -1
static int hf_lustre_mdt_rec_setattr_sa_suppgid_h = -1
static int hf_lustre_mdt_rec_setattr_sa_padding_1 = -1
static int hf_lustre_mdt_rec_setattr_sa_padding_1_h = -1
static int hf_lustre_mdt_rec_setattr_sa_fid = -1
static int hf_lustre_mdt_rec_setattr_sa_valid = -1
static int hf_lustre_mdt_rec_setattr_sa_uid = -1
static int hf_lustre_mdt_rec_setattr_sa_gid = -1
static int hf_lustre_mdt_rec_setattr_sa_size = -1
static int hf_lustre_mdt_rec_setattr_sa_blocks = -1
static int hf_lustre_mdt_rec_setattr_sa_mtime = -1
static int hf_lustre_mdt_rec_setattr_sa_atime = -1
static int hf_lustre_mdt_rec_setattr_sa_ctime = -1
static int hf_lustre_mdt_rec_setattr_sa_attr_flags = -1
static int hf_lustre_mdt_rec_setattr_sa_mode = -1
static int hf_lustre_mdt_rec_setattr_sa_padding_2 = -1
static int hf_lustre_mdt_rec_setattr_sa_padding_3 = -1
static int hf_lustre_mdt_rec_setattr_sa_padding_4 = -1
static int hf_lustre_mdt_rec_setattr_sa_padding_5 = -1
static int hf_lustre_mdt_rec_create = -1
static int hf_lustre_mdt_rec_create_cr_opcode = -1
static int hf_lustre_mdt_rec_create_cr_cap = -1
static int hf_lustre_mdt_rec_create_cr_fsuid = -1
static int hf_lustre_mdt_rec_create_cr_fsuid_h = -1
static int hf_lustre_mdt_rec_create_cr_fsgid = -1
static int hf_lustre_mdt_rec_create_cr_fsgid_h = -1
static int hf_lustre_mdt_rec_create_cr_suppgid1 = -1
static int hf_lustre_mdt_rec_create_cr_suppgid1_h = -1
static int hf_lustre_mdt_rec_create_cr_suppgid2 = -1
static int hf_lustre_mdt_rec_create_cr_suppgid2_h = -1
static int hf_lustre_mdt_rec_create_cr_fid1 = -1
static int hf_lustre_mdt_rec_create_cr_fid2 = -1
static int hf_lustre_mdt_rec_create_cr_old_handle = -1
static int hf_lustre_mdt_rec_create_cr_time = -1
static int hf_lustre_mdt_rec_create_cr_rdev = -1
static int hf_lustre_mdt_rec_create_cr_ioepoch = -1
static int hf_lustre_mdt_rec_create_cr_padding_1 = -1
static int hf_lustre_mdt_rec_create_cr_mode = -1
static int hf_lustre_mdt_rec_create_cr_bias = -1
static int hf_lustre_mdt_rec_create_cr_flags_l = -1
static int hf_lustre_mdt_rec_create_cr_flags_h = -1
static int hf_lustre_mdt_rec_create_cr_umask = -1
static int hf_lustre_mdt_rec_create_cr_padding_4 = -1
static int hf_lustre_mdt_rec_link = -1
static int hf_lustre_mdt_rec_link_lk_opcode = -1
static int hf_lustre_mdt_rec_link_lk_cap = -1
static int hf_lustre_mdt_rec_link_lk_fsuid = -1
static int hf_lustre_mdt_rec_link_lk_fsuid_h = -1
static int hf_lustre_mdt_rec_link_lk_fsgid = -1
static int hf_lustre_mdt_rec_link_lk_fsgid_h = -1
static int hf_lustre_mdt_rec_link_lk_suppgid1 = -1
static int hf_lustre_mdt_rec_link_lk_suppgid1_h = -1
static int hf_lustre_mdt_rec_link_lk_suppgid2 = -1
static int hf_lustre_mdt_rec_link_lk_suppgid2_h = -1
static int hf_lustre_mdt_rec_link_lk_fid1 = -1
static int hf_lustre_mdt_rec_link_lk_fid2 = -1
static int hf_lustre_mdt_rec_link_lk_time = -1
static int hf_lustre_mdt_rec_link_lk_padding_1 = -1
static int hf_lustre_mdt_rec_link_lk_padding_2 = -1
static int hf_lustre_mdt_rec_link_lk_padding_3 = -1
static int hf_lustre_mdt_rec_link_lk_padding_4 = -1
static int hf_lustre_mdt_rec_link_lk_bias = -1
static int hf_lustre_mdt_rec_link_lk_padding_5 = -1
static int hf_lustre_mdt_rec_link_lk_padding_6 = -1
static int hf_lustre_mdt_rec_link_lk_padding_7 = -1
static int hf_lustre_mdt_rec_link_lk_padding_8 = -1
static int hf_lustre_mdt_rec_link_lk_padding_9 = -1
static int hf_lustre_mdt_rec_unlink = -1
static int hf_lustre_mdt_rec_unlink_ul_opcode = -1
static int hf_lustre_mdt_rec_unlink_ul_cap = -1
static int hf_lustre_mdt_rec_unlink_ul_fsuid = -1
static int hf_lustre_mdt_rec_unlink_ul_fsuid_h = -1
static int hf_lustre_mdt_rec_unlink_ul_fsgid = -1
static int hf_lustre_mdt_rec_unlink_ul_fsgid_h = -1
static int hf_lustre_mdt_rec_unlink_ul_suppgid1 = -1
static int hf_lustre_mdt_rec_unlink_ul_suppgid1_h = -1
static int hf_lustre_mdt_rec_unlink_ul_suppgid2 = -1
static int hf_lustre_mdt_rec_unlink_ul_suppgid2_h = -1
static int hf_lustre_mdt_rec_unlink_ul_fid1 = -1
static int hf_lustre_mdt_rec_unlink_ul_fid2 = -1
static int hf_lustre_mdt_rec_unlink_ul_time = -1
static int hf_lustre_mdt_rec_unlink_ul_padding_2 = -1
static int hf_lustre_mdt_rec_unlink_ul_padding_3 = -1
static int hf_lustre_mdt_rec_unlink_ul_padding_4 = -1
static int hf_lustre_mdt_rec_unlink_ul_padding_5 = -1
static int hf_lustre_mdt_rec_unlink_ul_bias = -1
static int hf_lustre_mdt_rec_unlink_ul_mode = -1
static int hf_lustre_mdt_rec_unlink_ul_padding_6 = -1
static int hf_lustre_mdt_rec_unlink_ul_padding_7 = -1
static int hf_lustre_mdt_rec_unlink_ul_padding_8 = -1
static int hf_lustre_mdt_rec_unlink_ul_padding_9 = -1
static int hf_lustre_mdt_rec_rename = -1
static int hf_lustre_mdt_rec_rename_rn_opcode = -1
static int hf_lustre_mdt_rec_rename_rn_cap = -1
static int hf_lustre_mdt_rec_rename_rn_fsuid = -1
static int hf_lustre_mdt_rec_rename_rn_fsuid_h = -1
static int hf_lustre_mdt_rec_rename_rn_fsgid = -1
static int hf_lustre_mdt_rec_rename_rn_fsgid_h = -1
static int hf_lustre_mdt_rec_rename_rn_suppgid1 = -1
static int hf_lustre_mdt_rec_rename_rn_suppgid1_h = -1
static int hf_lustre_mdt_rec_rename_rn_suppgid2 = -1
static int hf_lustre_mdt_rec_rename_rn_suppgid2_h = -1
static int hf_lustre_mdt_rec_rename_rn_fid1 = -1
static int hf_lustre_mdt_rec_rename_rn_fid2 = -1
static int hf_lustre_mdt_rec_rename_rn_time = -1
static int hf_lustre_mdt_rec_rename_rn_padding_1 = -1
static int hf_lustre_mdt_rec_rename_rn_padding_2 = -1
static int hf_lustre_mdt_rec_rename_rn_padding_3 = -1
static int hf_lustre_mdt_rec_rename_rn_padding_4 = -1
static int hf_lustre_mdt_rec_rename_rn_bias = -1
static int hf_lustre_mdt_rec_rename_rn_mode = -1
static int hf_lustre_mdt_rec_rename_rn_padding_5 = -1
static int hf_lustre_mdt_rec_rename_rn_padding_6 = -1
static int hf_lustre_mdt_rec_rename_rn_padding_7 = -1
static int hf_lustre_mdt_rec_rename_rn_padding_8 = -1
static int hf_lustre_mdt_rec_setxattr = -1
static int hf_lustre_mdt_rec_setxattr_sx_opcode = -1
static int hf_lustre_mdt_rec_setxattr_sx_cap = -1
static int hf_lustre_mdt_rec_setxattr_sx_fsuid = -1
static int hf_lustre_mdt_rec_setxattr_sx_fsuid_h = -1
static int hf_lustre_mdt_rec_setxattr_sx_fsgid = -1
static int hf_lustre_mdt_rec_setxattr_sx_fsgid_h = -1
static int hf_lustre_mdt_rec_setxattr_sx_suppgid1 = -1
static int hf_lustre_mdt_rec_setxattr_sx_suppgid1_h = -1
static int hf_lustre_mdt_rec_setxattr_sx_suppgid2 = -1
static int hf_lustre_mdt_rec_setxattr_sx_suppgid2_h = -1
static int hf_lustre_mdt_rec_setxattr_sx_fid = -1
static int hf_lustre_mdt_rec_setxattr_sx_padding_1 = -1
static int hf_lustre_mdt_rec_setxattr_sx_padding_2 = -1
static int hf_lustre_mdt_rec_setxattr_sx_padding_3 = -1
static int hf_lustre_mdt_rec_setxattr_sx_valid = -1
static int hf_lustre_mdt_rec_setxattr_sx_time = -1
static int hf_lustre_mdt_rec_setxattr_sx_padding_5 = -1
static int hf_lustre_mdt_rec_setxattr_sx_padding_6 = -1
static int hf_lustre_mdt_rec_setxattr_sx_padding_7 = -1
static int hf_lustre_mdt_rec_setxattr_sx_size = -1
static int hf_lustre_mdt_rec_setxattr_sx_flags = -1
static int hf_lustre_mdt_rec_setxattr_sx_padding_8 = -1
static int hf_lustre_mdt_rec_setxattr_sx_padding_9 = -1
static int hf_lustre_mdt_rec_setxattr_sx_padding_10 = -1
static int hf_lustre_mdt_rec_setxattr_sx_padding_11 = -1
static int hf_lustre_seq_opc = -1
static int hf_lustre_seq_range = -1
static int hf_lustre_seq_range_start = -1
static int hf_lustre_seq_range_end = -1
static int hf_lustre_seq_range_index = -1
static int hf_lustre_seq_range_flags = -1
static int hf_lustre_fld_opc = -1
static int hf_lustre_fld_range = -1
static int hf_lustre_fld_range_start = -1
static int hf_lustre_fld_range_end = -1
static int hf_lustre_fld_range_index = -1
static int hf_lustre_fld_range_flags = -1
static int hf_lustre_mdt_ioepoch = -1
static int hf_lustre_mdt_ioepoch_handle = -1
static int hf_lustre_mdt_ioepoch_ioepoch = -1
static int hf_lustre_mdt_ioepoch_flags = -1
static int hf_lustre_mdt_ioepoch_padding = -1
static int hf_lustre_capa = -1
static int hf_lustre_capa_fid = -1
static int hf_lustre_capa_opc = -1
static int hf_lustre_capa_uid = -1
static int hf_lustre_capa_gid = -1
static int hf_lustre_capa_flags = -1
static int hf_lustre_capa_keyid = -1
static int hf_lustre_capa_timeout = -1
static int hf_lustre_capa_expiry = -1
static int hf_lustre_capa_hmac = -1
static int hf_lustre_acl = -1
static int hf_lustre_lustre_handle_cookie = -1
static int hf_lustre_ptlrpc_body_pb_last_committed = -1
static int hf_lustre_ptlrpc_body_pb_version = -1
static int hf_lustre_lustre_msg_v1_lm_bufcount = -1
static int hf_lustre_obd_ioobj_ioo_id = -1
static int hf_lustre_ptlrpc_body_pb_slv = -1
static int hf_lustre_ptlrpc_body_pb_pre_version = -1
static int hf_lustre_ptlrpc_body_pb_padding = -1
static int hf_lustre_ptlrpc_body_pb_jobid = -1
static int hf_lustre_lustre_msg_v1_lm_handle = -1
static int hf_lustre_ost_lvb_lvb_atime = -1
static int hf_lustre_ptlrpc_body_pb_timeout = -1
static int hf_lustre_obd_statfs_os_bavail = -1
static int hf_lustre_obd_statfs_os_bsize = -1
static int hf_lustre_lustre_msg_v2_lm_repsize = -1
static int hf_lustre_lov_mds_md_v1_lmm_stripe_size = -1
static int hf_lustre_lustre_msg_v1_lm_last_xid = -1
static int hf_lustre_ll_fid_f_type = -1
static int hf_lustre_lustre_msg_v2_lm_cksum = -1
static int hf_lustre_lustre_msg_v2_lm_buflens = -1
static int hf_lustre_lustre_msg_v1_lm_status = -1
static int hf_lustre_lustre_msg_v1_lm_type = -1
static int hf_lustre_niobuf_remote_len = -1
static int hf_lustre_lov_mds_md_v1_lmm_magic = -1
static int hf_lustre_ptlrpc_body_pb_op_flags = -1
static int hf_lustre_ost_lvb_lvb_ctime = -1
static int hf_lustre_ptlrpc_body_pb_type = -1
static int hf_lustre_obd_connect_data_ocd_nllg = -1
static int hf_lustre_obd_connect_data_ocd_nllu = -1
static int hf_lustre_ll_fid_generation = -1
static int hf_lustre_ost_lvb_lvb_mtime = -1
static int hf_lustre_obd_connect_data_ocd_ibits_known = -1
static int hf_lustre_lustre_msg_v2_lm_padding_3 = -1
static int hf_lustre_ptlrpc_body_pb_flags = -1
static int hf_lustre_obd_statfs_os_spare4 = -1
static int hf_lustre_obd_connect_data_ocd_group = -1
static int hf_lustre_lov_ost_data_v1_l_object_seq = -1
static int hf_lustre_lov_mds_md_v1_lmm_object_seq = -1
static int hf_lustre_obd_connect_data_ocd_brw_size = -1
static int hf_lustre_ptlrpc_body_pb_limit = -1
static int hf_lustre_obd_statfs_os_maxbytes = -1
static int hf_lustre_obd_statfs_os_spare5 = -1
static int hf_lustre_lustre_msg_v2_lm_flags = -1
static int hf_lustre_obd_statfs_os_ffree = -1
static int hf_lustre_obd_statfs_os_files = -1
static int hf_lustre_lov_mds_md_v1_lmm_stripe_count = -1
static int hf_lustre_lustre_msg_v1_lm_flags = -1
static int hf_lustre_lustre_msg_v1_lm_last_committed = -1
static int hf_lustre_obd_statfs_os_spare9 = -1
static int hf_lustre_obd_connect_data_ocd_index = -1
static int hf_lustre_opnum = -1
static int hf_lustre_lustre_msg_v1_lm_buflens = -1
static int hf_lustre_obd_statfs_os_spare1 = -1
static int hf_lustre_obd_statfs_os_spare8 = -1
static int hf_lustre_lustre_msg_v1_lm_conn_cnt = -1
static int hf_lustre_ptlrpc_body_pb_transno = -1
static int hf_lustre_ptlrpc_body_pb_service_time = -1
static int hf_lustre_ptlrpc_body_pb_conn_cnt = -1
static int hf_lustre_ptlrpc_body_pb_opc = -1
static int hf_lustre_obd_connect_data_ocd_connect_flags = -1
static int hf_lustre_lov_ost_data_v1_l_object_id = -1
static int hf_lustre_lov_ost_data_v1_l_ost_gen = -1
static int hf_lustre_obd_statfs_os_bfree = -1
static int hf_lustre_obd_connect_data_ocd_version = -1
static int hf_lustre_lov_mds_md_v1_lmm_objects = -1
static int hf_lustre_obd_statfs_os_namelen = -1
static int hf_lustre_obd_statfs_os_blocks = -1
static int hf_lustre_lustre_msg_v2_lm_secflvr = -1
static int hf_lustre_lustre_msg_v1_lm_transno = -1
static int hf_lustre_lov_mds_md_v1_lmm_pattern = -1
static int hf_lustre_lustre_msg_v1_lm_opc = -1
static int hf_lustre_obd_connect_data_ocd_grant = -1
static int hf_lustre_obd_ioobj_ioo_bufcnt = -1
static int hf_lustre_lustre_msg_v1_lm_version = -1
static int hf_lustre_obd_statfs_os_spare7 = -1
static int hf_lustre_obd_statfs_os_fsid = -1
static int hf_lustre_obd_connect_data_ocd_cksum_types = -1
static int hf_lustre_ost_lvb_lvb_size = -1
static int hf_lustre_obd_statfs_os_type = -1
static int hf_lustre_obd_statfs_os_spare6 = -1
static int hf_lustre_obd_statfs_os_state = -1
static int hf_lustre_obd_statfs_os_spare3 = -1
static int hf_lustre_lustre_msg_v2_lm_magic = -1
static int hf_lustre_lov_mds_md_v1_lmm_object_id = -1
static int hf_lustre_ptlrpc_body_pb_last_seen = -1
static int hf_lustre_obd_ioobj_ioo_max_brw = -1
static int hf_lustre_ptlrpc_body_pb_last_xid = -1
static int hf_lustre_ptlrpc_body_pb_status = -1
static int hf_lustre_niobuf_remote_flags = -1
static int hf_lustre_ll_fid_id = -1
static int hf_lustre_ost_lvb_lvb_blocks = -1
static int hf_lustre_lustre_msg_v2_lm_padding_2 = -1
static int hf_lustre_obd_connect_data_padding1 = -1
static int hf_lustre_lov_ost_data_v1_l_ost_idx = -1
static int hf_lustre_obd_connect_data_padding2 = -1
static int hf_lustre_obd_ioobj_ioo_seq = -1
static int hf_lustre_niobuf_remote_offset = -1
static int hf_lustre_obd_statfs_os_spare2 = -1
static int hf_lustre_lustre_msg_v2_lm_bufcount = -1
static int hf_lustre_ptlrpc_body_pb_handle = -1
static int hf_lustre_obd_connect_data_ocd_transno = -1
static int hf_lustre_lustre_msg_v1_lm_magic = -1
static int hf_lustre_llog_unlink_rec_lur_tail = -1
static int hf_lustre_llog_size_change_rec_lsc_io_epoch = -1
static int hf_lustre_mgs_target_info_mti_flags = -1
static int hf_lustre_ldlm_reply_lock_policy_res1 = -1
static int hf_lustre_llogd_body_lgd_len = -1
static int hf_lustre_qunit_data_old_qd_id = -1
static int hf_lustre_llog_logid_rec_padding1 = -1
static int hf_lustre_quota_adjust_qunit_padding1 = -1
static int hf_lustre_llog_size_change_rec_lsc_fid = -1
static int hf_lustre_llog_rec_hdr_padding = -1
static int hf_lustre_obdo_o_nlink = -1
static int hf_lustre_ldlm_extent_gid = -1
static int hf_lustre_obdo_o_uid = -1
static int hf_lustre_obdo_o_valid = -1
static int hf_lustre_ldlm_reply_lock_flags = -1
static int hf_lustre_obdo_o_misc = -1
static int hf_lustre_ldlm_request_lock_handle = -1
static int hf_lustre_llog_logid_lgl_oid = -1
static int hf_lustre_ldlm_inodebits_bits = -1
static int hf_lustre_llog_log_hdr_llh_count = -1
static int hf_lustre_llog_gen_rec_lgr_tail = -1
static int hf_lustre_llog_catid_lci_padding3 = -1
static int hf_lustre_qunit_data_qd_qunit = -1
static int hf_lustre_llog_setattr_rec_padding = -1
static int hf_lustre_llog_cookie_lgc_lgl = -1
static int hf_lustre_obd_quotactl_qc_dqinfo = -1
static int hf_lustre_llog_log_hdr_llh_bitmap = -1
static int hf_lustre_obd_quotactl_qc_stat = -1
static int hf_lustre_qunit_data_old2_qd_id = -1
static int hf_lustre_llog_logid_rec_padding2 = -1
static int hf_lustre_llog_logid_rec_padding5 = -1
static int hf_lustre_ldlm_intent_opc = -1
static int hf_lustre_llog_rec_hdr_lrh_type = -1
static int hf_lustre_llog_rec_hdr_lrh_len = -1
static int hf_lustre_llog_setattr_rec_lsr_uid = -1
static int hf_lustre_lov_desc_ld_padding_1 = -1
static int hf_lustre_obdo_o_padding_4 = -1
static int hf_lustre_mgs_target_info_padding = -1
static int hf_lustre_obd_quotactl_qc_dqblk = -1
static int hf_lustre_llogd_conn_body_lgdc_gen = -1
static int hf_lustre_llog_log_hdr_llh_tail = -1
static int hf_lustre_obdo_o_size = -1
static int hf_lustre_ldlm_extent_start = -1
static int hf_lustre_llog_size_change_rec_lsc_hdr = -1
static int hf_lustre_llog_logid_lgl_oseq = -1
static int hf_lustre_llog_cookie_lgc_padding = -1
static int hf_lustre_qunit_data_old_qd_type = -1
static int hf_lustre_ldlm_flock_blocking_export = -1
static int hf_lustre_lov_desc_ld_pattern = -1
static int hf_lustre_qunit_data_qd_id = -1
static int hf_lustre_mgs_target_info_mti_fsname = -1
static int hf_lustre_ldlm_request_lock_flags = -1
static int hf_lustre_obdo_o_mode = -1
static int hf_lustre_mgs_target_info_mti_svname = -1
static int hf_lustre_llogd_body_lgd_logid = -1
static int hf_lustre_llog_log_hdr_llh_size = -1
static int hf_lustre_obdo_o_handle = -1
static int hf_lustre_obdo_o_atime = -1
static int hf_lustre_quota_adjust_qunit_qaq_id = -1
static int hf_lustre_ldlm_lock_desc_l_policy_data = -1
static int hf_lustre_obd_quotactl_qc_cmd = -1
static int hf_lustre_qunit_data_padding = -1
static int hf_lustre_quota_adjust_qunit_qaq_flags = -1
static int hf_lustre_ldlm_lock_desc_l_granted_mode = -1
static int hf_lustre_obdo_o_seq = -1
static int hf_lustre_obdo_o_gid = -1
static int hf_lustre_llog_catid_lci_logid = -1
static int hf_lustre_llog_rec_tail_lrt_index = -1
static int hf_lustre_lov_desc_ld_default_stripe_count = -1
static int hf_lustre_ldlm_resource_desc_lr_padding = -1
static int hf_lustre_cfg_marker_cm_vers = -1
static int hf_lustre_llog_unlink_rec_lur_hdr = -1
static int hf_lustre_llogd_body_lgd_index = -1
static int hf_lustre_cfg_marker_cm_tgtname = -1
static int hf_lustre_llog_setattr_rec_lsr_ogen = -1
static int hf_lustre_llog_logid_rec_lid_hdr = -1
static int hf_lustre_obdo_o_ioepoch = -1
static int hf_lustre_ost_body_oa = -1
static int hf_lustre_llog_logid_rec_padding3 = -1
static int hf_lustre_llog_log_hdr_llh_flags = -1
static int hf_lustre_llog_setattr_rec_lsr_oid = -1
static int hf_lustre_llog_size_change_rec_padding = -1
static int hf_lustre_mgs_target_info_mti_config_ver = -1
static int hf_lustre_cfg_marker_cm_createtime = -1
static int hf_lustre_qunit_data_old_qd_count = -1
static int hf_lustre_llog_catid_lci_padding1 = -1
static int hf_lustre_lov_desc_ld_active_tgt_count = -1
static int hf_lustre_obdo_o_lcookie = -1
static int hf_lustre_llog_gen_rec_lgr_gen = -1
static int hf_lustre_obdo_o_id = -1
static int hf_lustre_mgs_target_info_mti_uuid = -1
static int hf_lustre_llog_rec_hdr_lrh_index = -1
static int hf_lustre_llog_setattr_rec_lsr_hdr = -1
static int hf_lustre_mgs_target_info_mti_stripe_index = -1
static int hf_lustre_llog_gen_conn_cnt = -1
static int hf_lustre_obdo_o_padding_6 = -1
static int hf_lustre_llog_cookie_lgc_index = -1
static int hf_lustre_lov_desc_ld_uuid = -1
static int hf_lustre_ldlm_reply_lock_desc = -1
static int hf_lustre_lov_desc_ld_padding_0 = -1
static int hf_lustre_llog_unlink_rec_lur_ogen = -1
static int hf_lustre_cfg_marker_cm_flags = -1
static int hf_lustre_obdo_o_padding_3 = -1
static int hf_lustre_ldlm_request_lock_desc = -1
static int hf_lustre_obdo_o_flags = -1
static int hf_lustre_mgs_target_info_mti_params = -1
static int hf_lustre_llog_logid_lgl_ogen = -1
static int hf_lustre_cfg_marker_cm_comment = -1
static int hf_lustre_llog_unlink_rec_lur_oid = -1
static int hf_lustre_qunit_data_qd_count = -1
static int hf_lustre_obdo_o_mtime = -1
static int hf_lustre_obdo_o_blksize = -1
static int hf_lustre_ldlm_res_id_name = -1
static int hf_lustre_ldlm_reply_lock_handle = -1
static int hf_lustre_llogd_body_lgd_saved_index = -1
static int hf_lustre_qunit_data_old_qd_isblk = -1
static int hf_lustre_obdo_o_blocks = -1
static int hf_lustre_lov_desc_ld_padding_2 = -1
static int hf_lustre_llog_logid_rec_lid_tail = -1
static int hf_lustre_obdo_o_grant = -1
static int hf_lustre_obdo_o_uid_h = -1
static int hf_lustre_obdo_o_gid_h = -1
static int hf_lustre_quota_adjust_qunit_qaq_iunit_sz = -1
static int hf_lustre_llog_unlink_rec_padding = -1
static int hf_lustre_ldlm_lock_desc_l_req_mode = -1
static int hf_lustre_ldlm_extent_end = -1
static int hf_lustre_llog_gen_rec_lgr_hdr = -1
static int hf_lustre_llogd_body_lgd_llh_flags = -1
static int hf_lustre_llog_log_hdr_llh_cat_idx = -1
static int hf_lustre_llog_log_hdr_llh_bitmap_offset = -1
static int hf_lustre_ldlm_reply_lock_padding = -1
static int hf_lustre_obd_quotactl_qc_id = -1
static int hf_lustre_llog_logid_rec_padding4 = -1
static int hf_lustre_llog_setattr_rec_lsr_gid = -1
static int hf_lustre_obd_quotactl_qc_type = -1
static int hf_lustre_cfg_marker_padding = -1
static int hf_lustre_mgs_target_info_mti_nids = -1
static int hf_lustre_obdo_o_stripe_idx = -1
static int hf_lustre_llogd_conn_body_lgdc_logid = -1
static int hf_lustre_ldlm_flock_blocking_pid = -1
static int hf_lustre_lov_desc_ld_tgt_count = -1
static int hf_lustre_llogd_body_lgd_cur_offset = -1
static int hf_lustre_qunit_data_old2_qd_count = -1
static int hf_lustre_qunit_data_old2_qd_flags = -1
static int hf_lustre_ldlm_flock_start = -1
static int hf_lustre_quota_adjust_qunit_qaq_bunit_sz = -1
static int hf_lustre_ldlm_flock_pid = -1
static int hf_lustre_lov_desc_ld_default_stripe_size = -1
static int hf_lustre_llog_log_hdr_llh_tgtuuid = -1
static int hf_lustre_cfg_marker_cm_step = -1
static int hf_lustre_mgs_send_param_mgs_param = -1
static int hf_lustre_lov_desc_ld_default_stripe_offset = -1
static int hf_lustre_ldlm_resource_desc_lr_name = -1
static int hf_lustre_llog_rec_tail_lrt_len = -1
static int hf_lustre_llog_log_hdr_llh_timestamp = -1
static int hf_lustre_llog_catid_lci_padding2 = -1
static int hf_lustre_llogd_conn_body_lgdc_ctxt_idx = -1
static int hf_lustre_cfg_marker_cm_canceltime = -1
static int hf_lustre_mgs_target_info_mti_lustre_ver = -1
static int hf_lustre_obdo_o_parent_ver = -1
static int hf_lustre_qunit_data_qd_flags = -1
static int hf_lustre_llog_logid_rec_lid_id = -1
static int hf_lustre_obdo_o_parent_oid = -1
static int hf_lustre_llog_gen_mnt_cnt = -1
static int hf_lustre_llog_size_change_rec_lsc_tail = -1
static int hf_lustre_obdo_o_padding_5 = -1
static int hf_lustre_ldlm_lock_desc_l_resource = -1
static int hf_lustre_obdo_o_parent_seq = -1
static int hf_lustre_ldlm_request_lock_count = -1
static int hf_lustre_ldlm_flock_end = -1
static int hf_lustre_mgs_target_info_mti_nid_count = -1
static int hf_lustre_obdo_o_ctime = -1
static int hf_lustre_ldlm_reply_lock_policy_res2 = -1
static int hf_lustre_llogd_body_lgd_ctxt_idx = -1
static int hf_lustre_lov_desc_ld_qos_maxage = -1
static int hf_lustre_ldlm_resource_desc_lr_type = -1
static int hf_lustre_llog_setattr_rec_lsr_tail = -1
static int hf_lustre_llog_cookie_lgc_subsys = -1
static int hf_lustre_llog_log_hdr_llh_hdr = -1
static int hf_lustre_llog_log_hdr_llh_reserved = -1
static int hf_lustre_obd_dqinfo_dqi_valid = -1
static int hf_lustre_obd_dqblk_dqb_isoftlimit = -1
static int hf_lustre_obd_dqblk_dqb_bhardlimit = -1
static int hf_lustre_obd_dqblk_dqb_curspace = -1
static int hf_lustre_obd_dqblk_dqb_itime = -1
static int hf_lustre_obd_dqblk_dqb_valid = -1
static int hf_lustre_obd_dqinfo_dqi_igrace = -1
static int hf_lustre_obd_dqinfo_dqi_bgrace = -1
static int hf_lustre_obd_dqblk_padding = -1
static int hf_lustre_obd_dqblk_dqb_curinodes = -1
static int hf_lustre_obd_dqblk_dqb_bsoftlimit = -1
static int hf_lustre_obd_dqinfo_dqi_flags = -1
static int hf_lustre_obd_dqblk_dqb_btime = -1
static int hf_lustre_obd_dqblk_dqb_ihardlimit = -1
static int hf_lustre_ldlm_intent_opc_open = -1
static int hf_lustre_ldlm_intent_opc_creat = -1
static int hf_lustre_ldlm_intent_opc_readdir = -1
static int hf_lustre_ldlm_intent_opc_getattr = -1
static int hf_lustre_ldlm_intent_opc_lookup = -1
static int hf_lustre_ldlm_intent_opc_unlink = -1
static int hf_lustre_ldlm_intent_opc_getxattr = -1
static int hf_lustre_ldlm_intent_opc_exec = -1
static int hf_lustre_ldlm_intent_opc_pin = -1
static int hf_lustre_llog_hdr_llh_flag_zap_when_empty = -1
static int hf_lustre_llog_hdr_llh_flag_is_cat = -1
static int hf_lustre_llog_hdr_llh_flag_is_play = -1
static int hf_lustre_lu_ladvise = -1
static int hf_lustre_lu_ladvise_lla_start = -1
static int hf_lustre_lu_ladvise_lla_end = -1
static int hf_lustre_lu_ladvise_lla_advice = -1
static int hf_lustre_lu_ladvise_lla_padding = -1
static gint proto_lustre = -1
static dissect_func dissect_uint64
static dissect_func dissect_uint32
static dissect_func dissect_uint16
static dissect_func dissect_uint8
const value_string lustre_ldlm_opcode []
const value_string lustre_lov_magic []
const value_string lustre_llog_op_type []
const value_string lustre_llog_hdr_llh_flags []
const value_string lustre_mds_flags_vals []
const value_string lustre_mgs_config_body_types []
const value_string lustre_LMTypes []
const value_string lustre_mds_reint_t_vals []
const value_string lustre_op_codes []
const value_string lustre_ldlm_mode_vals []
const value_string lustre_ldlm_type_vals []
const value_string lustre_llog_cmd_t_vals []
const gchar version [] = VERSION
Define Documentation
#define hf_lustre_ldlm_ast_discard_data hf_lustre_ldlm_fl_ast_discard_data
Definition at line 490 of file packet-lustre.c.
#define IT_CREAT 0x0002
Definition at line 234 of file packet-lustre.c.
Referenced by check_ldlm_intent(), it_to_lock_mode(), ldlm_it2str(), ll_convert_intent(), ll_file_open(), ll_lookup_it(), lmv_intent_open(), lustre_assert_wire_constants(), lustre_dissect_element_ldlm_intent_opc(), mdc_finish_intent_lock(), mdc_intent_lock(), mdc_intent_open_pack(), and mdt_intent_code().
#define IT_EXEC 0x0080
Definition at line 240 of file packet-lustre.c.
Referenced by check_ldlm_intent(), lustre_assert_wire_constants(), and lustre_dissect_element_ldlm_intent_opc().
#define IT_GETATTR 0x0008
Definition at line 236 of file packet-lustre.c.
Referenced by __ll_inode_revalidate(), check_ldlm_intent(), it_to_lock_mode(), ldlm_it2str(), ldlm_opcode_process(), ll_convert_intent(), ll_lookup_finish_locks(), ll_lookup_it(), ll_lookup_it_finish(), lmv_intent_lock(), lmv_intent_remote(), lmv_revalidate_slaves(), lustre_assert_wire_constants(), lustre_dissect_element_ldlm_intent_opc(), mdc_enqueue(), mdc_finish_enqueue(), mdc_finish_intent_lock(), mdc_get_rpc_lock(), mdc_intent_lock(), mdc_put_rpc_lock(), mdc_revalidate_lock(), mdt_intent_code(), obd_get_mod_rpc_slot(), obd_put_mod_rpc_slot(), revalidate_statahead_dentry(), sa_prep_data(), and sa_revalidate().
#define IT_GETXATTR 0x0040
Definition at line 239 of file packet-lustre.c.
Referenced by check_ldlm_intent(), it_to_lock_mode(), ldlm_it2str(), ll_lookup_it(), ll_xattr_cache_get(), lustre_assert_wire_constants(), lustre_dissect_element_ldlm_intent_opc(), mdc_enqueue(), mdc_intent_getxattr_pack(), and mdt_intent_code().
#define IT_LOOKUP 0x0010
Definition at line 237 of file packet-lustre.c.
Referenced by __ll_inode_revalidate(), check_ldlm_intent(), it_to_lock_mode(), ldlm_it2str(), ldlm_opcode_process(), ll_lookup_finish_locks(), ll_lookup_it(), lmv_intent_lock(), lmv_intent_remote(), lustre_assert_wire_constants(), lustre_dissect_element_ldlm_intent_opc(), mdc_enqueue(), mdc_finish_enqueue(), mdc_finish_intent_lock(), mdc_get_rpc_lock(), mdc_intent_lock(), mdc_put_rpc_lock(), mdt_intent_code(), obd_get_mod_rpc_slot(), and obd_put_mod_rpc_slot().
#define IT_OPEN 0x0001
Definition at line 233 of file packet-lustre.c.
Referenced by check_ldlm_intent(), it_to_lock_mode(), ldlm_it2str(), ldlm_opcode_process(), ll_convert_intent(), ll_file_open(), ll_lease_open(), ll_lookup_it(), ll_lookup_it_finish(), ll_lov_setstripe_ea_info(), ll_prep_inode(), lmv_intent_lock(), lmv_intent_remote(), lustre_assert_wire_constants(), lustre_dissect_element_ldlm_intent_opc(), mdc_enqueue(), mdc_finish_enqueue(), mdc_finish_intent_lock(), and mdt_intent_code().
#define IT_PIN 0x0100
Definition at line 241 of file packet-lustre.c.
Referenced by check_ldlm_intent(), lustre_assert_wire_constants(), and lustre_dissect_element_ldlm_intent_opc().
#define IT_READDIR 0x0004
Definition at line 235 of file packet-lustre.c.
Referenced by check_ldlm_intent(), it_to_lock_mode(), ldlm_it2str(), lustre_assert_wire_constants(), lustre_dissect_element_ldlm_intent_opc(), mdc_enqueue(), mdc_finish_intent_lock(), mdc_get_rpc_lock(), mdc_intent_lock(), mdc_put_rpc_lock(), mdc_read_page(), mdc_revalidate_lock(), mdt_intent_code(), obd_get_mod_rpc_slot(), and obd_put_mod_rpc_slot().
#define IT_UNLINK 0x0020
Definition at line 238 of file packet-lustre.c.
Referenced by check_ldlm_intent(), ldlm_it2str(), ldlm_opcode_process(), lustre_assert_wire_constants(), lustre_dissect_element_ldlm_intent_opc(), mdc_enqueue(), mdc_finish_enqueue(), and mdt_intent_code().
#define LCK_CR (16)
Definition at line 295 of file packet-lustre.c.
Referenced by it_to_lock_mode(), ldlm_lock_addref_internal_nolock(), ldlm_lock_decref_internal_nolock(), lfsck_lock(), ll_have_md_lock(), ll_layout_refresh_locked(), ll_md_blocking_ast(), ll_md_close(), lustre_assert_wire_constants(), main(), mdc_intent_open_pack(), mdc_revalidate_lock(), mdt_ioc_version_get(), mdt_lock_pdo_mode(), mdt_object_open_lock(), mgc_process_log(), and qsd_intent_interpret().
#define LCK_CW (8)
Definition at line 294 of file packet-lustre.c.
Referenced by it_to_lock_mode(), ldlm_lock_addref_internal_nolock(), ldlm_lock_decref_internal_nolock(), lfsck_lock(), ll_have_md_lock(), ll_layout_refresh_locked(), ll_md_blocking_ast(), ll_md_close(), lustre_assert_wire_constants(), main(), mdc_intent_open_pack(), mdc_revalidate_lock(), mdt_lock_pdo_mode(), and mdt_object_open_lock().
#define LCK_EX (1)
Definition at line 291 of file packet-lustre.c.
Referenced by hsm_restore_cb(), hsm_swap_layouts(), ldlm_lock_addref_internal_nolock(), ldlm_lock_decref_internal_nolock(), ldlm_lock_downgrade(), ldlm_work_revoke_ast_lock(), lfsck_layout_check_parent(), lfsck_layout_conflict_create(), lfsck_layout_master_exec_oit(), lfsck_layout_recreate_lovea(), lfsck_layout_repair_dangling(), lfsck_layout_repair_multiple_references(), lfsck_layout_repair_unmatched_pair(), lfsck_layout_slave_conditional_destroy(), lfsck_lock(), lfsck_namespace_assistant_handler_p1(), lfsck_namespace_double_scan_dir(), lfsck_namespace_dsd_multiple(), lfsck_namespace_dsd_orphan(), lfsck_namespace_dsd_single(), lfsck_namespace_exec_oit(), lfsck_namespace_insert_orphan(), lfsck_namespace_replace_cond(), lfsck_namespace_set_lmv_master(), lfsck_namespace_shrink_linkea(), lfsck_namespace_striped_dir_rescan(), lfsck_namespace_update_lmv(), lfsck_remove_lmv(), lmv_link(), lmv_rename(), lmv_unlink(), lod_object_lock(), lustre_assert_wire_constants(), main(), mdc_create(), mdc_intent_open_pack(), mdc_ioc_swap_layouts(), mdc_link(), mdc_rename(), mdc_setattr(), mdc_unlink(), mdc_xattr_common(), mdt_blocking_ast(), mdt_close_swap_layouts(), mdt_hsm_add_actions(), mdt_hsm_release(), mdt_lock_pdo_mode(), mdt_object_local_lock(), mdt_object_lock_internal(), mdt_object_open_lock(), mdt_pdir_hash_lock(), mdt_reint_link(), mdt_reint_migrate_internal(), mdt_reint_object_lock(), mdt_reint_object_lock_try(), mdt_reint_rename_internal(), mdt_reint_setxattr(), mdt_reint_unlink(), mdt_rename_lock(), mdt_rename_unlock(), mdt_save_lock(), mdt_save_remote_lock(), mdt_swap_layouts(), mgs_completion_ast_generic(), mgs_revoke_lock(), osp_md_object_lock(), and tgt_blocking_ast().
#define LCK_GROUP (64)
Definition at line 297 of file packet-lustre.c.
Referenced by ldlm_lock_addref_internal_nolock(), ldlm_lock_decref_internal(), ldlm_lock_decref_internal_nolock(), lock_matches(), lustre_assert_wire_constants(), main(), osc_cl_lock2ldlm(), osc_dlm_blocking_ast0(), osc_dlmlock_at_pgoff(), osc_extent_sanity_check0(), osc_ldlm2cl_lock(), and tgt_blocking_ast().
#define LCK_MINMODE (0)
Definition at line 290 of file packet-lustre.c.
Referenced by __ll_inode_revalidate(), ldlm_cli_cancel_unused(), ldlm_cli_hash_cancel_unused(), ldlm_lock_cancel(), ll_have_md_lock(), ll_md_blocking_ast(), ll_readdir(), lockmode_verify(), lustre_assert_wire_constants(), main(), mdt_lock_handle_init(), mdt_lock_pdo_init(), mdt_lock_pdo_mode(), mdt_object_local_lock(), and osc_object_fiemap().
#define LCK_NL (32)
Definition at line 296 of file packet-lustre.c.
Referenced by echo_cleanup(), echo_setup(), ldlm_grant_lock(), ldlm_lock_addref_internal_nolock(), ldlm_lock_decref_internal_nolock(), ldlm_process_flock_lock(), ll_file_flock(), lustre_assert_wire_constants(), main(), mdc_enqueue(), mdc_finish_intent_lock(), and mdt_object_local_lock().
#define LCK_PR (4)
Definition at line 293 of file packet-lustre.c.
Referenced by cl_echo_object_brw(), it_to_lock_mode(), ldlm_flock_completion_ast(), ldlm_lock_addref_internal_nolock(), ldlm_lock_convert(), ldlm_lock_decref_internal_nolock(), lfsck_lock(), lfsck_namespace_repair_dangling(), lfsck_namespace_shrink_linkea_cond(), lfsck_verify_lpf_pairs(), ll_file_flock(), ll_have_md_lock(), ll_layout_refresh_locked(), ll_md_blocking_ast(), ll_md_close(), ll_xattr_find_get_lock(), lock_region(), lustre_assert_wire_constants(), main(), mdc_intent_open_pack(), mdc_revalidate_lock(), mdt_getattr_name_lock(), mdt_hsm_state_get(), mdt_lock_pdo_mode(), mdt_object_open_lock(), mdt_reint_open(), ofd_getattr_hdl(), ofd_intent_policy(), ofd_rw_hpreq_lock_match(), osc_cl_lock2ldlm(), osc_dlmlock_at_pgoff(), osc_enqueue_base(), osc_io_read_ahead(), osc_ldlm2cl_lock(), osc_match_base(), osc_object_fiemap(), osc_read_ahead_release(), tgt_brw_lock(), tgt_brw_read(), tgt_brw_unlock(), and unlock_zero_regions().
#define LCK_PW (2)
Definition at line 292 of file packet-lustre.c.
Referenced by cl_echo_enqueue0(), cl_echo_object_brw(), it_to_lock_mode(), ldlm_flock_completion_ast(), ldlm_handle_gl_callback(), ldlm_lock_addref_internal_nolock(), ldlm_lock_convert(), ldlm_lock_decref_internal_nolock(), ldlm_lock_downgrade(), lfsck_create_lpf(), lfsck_layout_recreate_parent(), lfsck_lock(), lfsck_lpf_remove_name_entry(), lfsck_namespace_create_orphan_dir(), lfsck_namespace_insert_normal(), lfsck_namespace_insert_orphan(), lfsck_namespace_repair_dirent(), lfsck_namespace_repair_nlink(), lfsck_namespace_replace_cond(), lfsck_update_name_entry(), ll_file_flock(), ll_have_md_lock(), ll_layout_refresh_locked(), lod_object_lock(), lustre_assert_wire_constants(), main(), mdc_revalidate_lock(), mdt_add_dirty_flag(), mdt_attr_set(), mdt_blocking_ast(), mdt_hsm_state_set(), mdt_lock_objects_in_linkea(), mdt_lock_pdo_mode(), mdt_md_create(), mdt_object_local_lock(), mdt_pdir_hash_lock(), mdt_reint_link(), mdt_reint_migrate_internal(), mdt_reint_object_lock(), mdt_reint_object_lock_try(), mdt_reint_open(), mdt_reint_rename_internal(), mdt_reint_setattr(), mdt_reint_unlink(), mdt_save_lock(), mdt_save_remote_lock(), ofd_destroy_by_fid(), ofd_getattr_hdl(), ofd_prolong_extent_locks(), ofd_punch_hdl(), ofd_rw_hpreq_lock_match(), osc_cl_lock2ldlm(), osc_destroy(), osc_dlm_blocking_ast0(), osc_dlmlock_at_pgoff(), osc_enqueue_base(), osc_extent_sanity_check0(), osc_ldlm2cl_lock(), osc_match_base(), osc_object_fiemap(), osp_md_object_lock(), tgt_blocking_ast(), tgt_brw_lock(), tgt_brw_unlock(), and tgt_brw_write().
#define LDLM_BL_CALLBACK (104)
Definition at line 287 of file packet-lustre.c.
Referenced by ldlm_callback_handler(), ldlm_run_ast_work(), lustre_assert_wire_constants(), lustre_ldlm_opcode_process(), lustre_msg_set_jobid(), main(), and ptlrpc_request_pack().
#define LDLM_CANCEL (103)
Definition at line 286 of file packet-lustre.c.
Referenced by ldlm_cli_cancel_req(), lustre_assert_wire_constants(), lustre_ldlm_opcode_process(), and main().
#define LDLM_CONVERT (102)
Definition at line 285 of file packet-lustre.c.
Referenced by ldlm_cli_convert(), lustre_assert_wire_constants(), lustre_ldlm_opcode_process(), and main().
#define LDLM_CP_CALLBACK (105)
Definition at line 288 of file packet-lustre.c.
Referenced by ldlm_callback_handler(), ldlm_run_ast_work(), lustre_assert_wire_constants(), lustre_ldlm_opcode_process(), lustre_msg_set_jobid(), main(), and ptlrpc_request_pack().
#define LDLM_ENQUEUE (101)
Definition at line 284 of file packet-lustre.c.
Referenced by ldlm_cli_enqueue(), ldlm_prep_elc_req(), ldlm_prep_enqueue_req(), lustre_assert_wire_constants(), lustre_ldlm_opcode_process(), main(), mgc_enqueue(), ptlrpc_server_handle_request(), replay_one_lock(), and tgt_filter_recovery_request().
#define LDLM_EXTENT (11)
Definition at line 299 of file packet-lustre.c.
Referenced by _ldlm_lock_debug(), ldlm_cancel_no_wait_policy(), ldlm_cli_enqueue(), ldlm_cli_enqueue_local(), ldlm_grant_lock(), ldlm_interval_alloc(), ldlm_interval_attach(), ldlm_lock_convert(), ldlm_lock_create(), ldlm_lock_enqueue(), ldlm_lock_match(), ldlm_resource_new(), ldlm_resource_unlink_lock(), lfsck_layout_slave_conditional_destroy(), lock_matches(), lustre_assert_wire_constants(), lustre_dissect_element_ldlm_lock_desc_l_policy_data(), lustre_ldlm_opcode_process(), main(), ofd_commitrw(), ofd_destroy_by_fid(), ofd_echo_setattr(), ofd_prolong_extent_locks(), ofd_punch_hdl(), ofd_setattr_hdl(), osc_cancel_weight(), osc_dlmlock_at_pgoff(), osc_ldlm_weigh_ast(), osc_lock_build_einfo(), osc_object_fiemap(), osc_req_attr_set(), tgt_blocking_ast(), and tgt_extent_lock().
#define LDLM_FIRST_OPC LDLM_ENQUEUE
Definition at line 270 of file packet-lustre.c.
#define LDLM_FIRST_OPC LDLM_ENQUEUE
Definition at line 270 of file packet-lustre.c.
Referenced by lprocfs_nid_ldlm_stats_init(), lustre_opcode_process(), and opcode_offset().
#define LDLM_FLOCK (12)
Definition at line 300 of file packet-lustre.c.
Referenced by _ldlm_lock_debug(), failed_lock_cleanup(), ldlm_cli_enqueue_fini(), ldlm_lock_add_to_lru_nolock(), ldlm_lock_remove_from_lru_nolock(), ldlm_process_flock_lock(), ll_file_flock(), lustre_assert_wire_constants(), lustre_dissect_element_ldlm_lock_desc_l_policy_data(), main(), and mdc_enqueue().
#define LDLM_GL_CALLBACK (106)
Definition at line 289 of file packet-lustre.c.
Referenced by ldlm_callback_handler(), ldlm_run_ast_work(), lustre_assert_wire_constants(), lustre_ldlm_opcode_process(), lustre_msg_set_jobid(), main(), osc_ldlm_glimpse_ast(), ptlrpc_request_pack(), and qsd_common_glimpse_ast().
#define LDLM_IBITS (13)
Definition at line 301 of file packet-lustre.c.
Referenced by __lfsck_ibits_lock(), _ldlm_lock_debug(), ldlm_cancel_no_wait_policy(), ldlm_cancel_resource_local(), ldlm_cli_enqueue_fini(), ldlm_grant_lock(), ldlm_has_layout(), ldlm_lock_convert(), ldlm_lock_match(), ldlm_resource_unlink_lock(), ldlm_unlink_lock_skiplist(), ll_have_md_lock(), ll_layout_refresh_locked(), ll_md_close(), ll_take_md_lock(), ll_xattr_find_get_lock(), lock_matches(), lod_object_lock(), lustre_assert_wire_constants(), lustre_dissect_element_ldlm_lock_desc_l_policy_data(), main(), mdc_cancel_weight(), mdc_enqueue(), mdc_finish_intent_lock(), mdc_intent_lock(), mdc_revalidate_lock(), mdt_fid_lock(), mdt_intent_policy(), mdt_lock_slaves(), mdt_remote_object_lock(), mdt_rename_lock(), osp_cancel_weight(), sa_prep_data(), search_granted_lock(), and tgt_request_preprocess().
#define LDLM_PLAIN (10)
Definition at line 298 of file packet-lustre.c.
Referenced by echo_setup(), ldlm_cli_enqueue_fini(), ldlm_grant_lock(), ldlm_handle_cp_callback(), ldlm_lock_convert(), ldlm_lock_match(), ldlm_resource_unlink_lock(), ldlm_unlink_lock_skiplist(), lustre_assert_wire_constants(), lustre_dissect_element_ldlm_lock_desc_l_policy_data(), main(), mgc_process_log(), mgs_revoke_lock(), qmt_glb_lock_notify(), qmt_id_lock_glimpse(), qmt_lvbo_fill(), qmt_lvbo_init(), qsd_intent_interpret(), and search_granted_lock().
#define LLOG_F_IS_CAT 0x2
Definition at line 356 of file packet-lustre.c.
Referenced by llog_cat_process_or_fork(), llog_cat_reverse_process(), llog_changelog_cancel(), llog_check_cb(), llog_free_handle(), llog_init_handle(), llog_ioctl(), llog_origin_close(), llog_osd_write_rec(), llog_print_cb(), llog_test_10(), llog_test_4(), llog_test_5(), llog_test_8(), lod_sub_prep_llog(), mdc_changelog_send_thread(), mdd_changelog_llog_init(), mdd_changelog_size_ctxt(), mdd_changelog_user_purge(), mdd_changelog_users_seq_show(), mdd_hsm_actions_llog_init(), osp_sync_llog_init(), and verify_handle().
#define LLOG_F_IS_PLAIN 0x4
Definition at line 357 of file packet-lustre.c.
Referenced by changelog_init_cb(), changelog_user_init_cb(), class_config_parse_llog(), llog_backup(), llog_cancel_rec_cb(), llog_cat_id2handle(), llog_cat_new_log(), llog_changelog_cancel_cb(), llog_client_destroy(), llog_erase(), llog_free_handle(), llog_init_handle(), llog_ioctl(), llog_is_empty(), llog_origin_handle_destroy(), llog_test_1(), llog_test_2(), llog_test_6(), llog_test_7_sub(), llog_test_9_sub(), lprocfs_changelog_users_cb(), mdd_changelog_user_purge_cb(), mgs_get_fsdb_from_llog(), mgs_get_fsdb_srpc_from_llog(), mgs_modify(), mgs_replace_nids_log(), mgs_steal_llog_for_mdt_from_client(), plain_print_cb(), record_start_log(), sptlrpc_target_local_copy_conf(), and sptlrpc_target_local_read_conf().
#define LLOG_F_ZAP_WHEN_EMPTY 0x1
Definition at line 355 of file packet-lustre.c.
Referenced by llog_cancel_rec(), llog_cat_close(), llog_cat_new_log(), llog_cat_process_cb(), llog_cat_reverse_process_cb(), llog_test_7_sub(), and llog_test_9_sub().
#define LLOG_FIRST_OPC LLOG_ORIGIN_HANDLE_CREATE
Definition at line 334 of file packet-lustre.c.
Referenced by check_llogd_body(), lustre_assert_wire_constants(), lustre_opcode_process(), and opcode_offset().
#define LLOG_OP_MAGIC 0x10600000
Definition at line 336 of file packet-lustre.c.
#define LLOG_OP_MASK 0xfff00000
Definition at line 337 of file packet-lustre.c.
#define LOV_MAGIC LOV_MAGIC_V1
Definition at line 86 of file packet-lustre.c.
Referenced by ll_dir_getstripe(), ll_lov_getstripe_ea_info(), lod_qos_prep_create(), lov_fini_statfs(), lov_getstripe(), and lov_r0().
#define LOV_MAGIC_JOIN_V1 0x0BD20BD0
Definition at line 87 of file packet-lustre.c.
#define LOV_MAGIC_V1 0x0BD10BD0
Definition at line 85 of file packet-lustre.c.
Referenced by check_lov_mds_md_v1(), lfsck_layout_check_parent(), lfsck_layout_extend_lovea(), lfsck_layout_master_check_pairs(), lfsck_layout_recreate_lovea(), lfsck_layout_recreate_parent(), lfsck_layout_refill_lovea(), lfsck_layout_repair_multiple_references(), lfsck_layout_scan_stripes(), lfsck_layout_verify_header(), ll_dir_getstripe(), ll_lov_getstripe_ea_info(), llapi_layout_get_by_fd(), llapi_layout_lum_truncated(), llapi_layout_objects_in_lum(), llapi_layout_swab_lov_user_md(), lod_attr_set(), lod_cache_parent_lov_striping(), lod_declare_striped_object(), lod_generate_and_set_lovea(), lod_parse_striping(), lod_use_defined_striping(), lov_dump_lmm(), lov_getstripe(), lov_init_raid0(), lov_mds_md_max_stripe_count(), lsm_lmm_verify_v1(), lsm_op_find(), lustre_assert_wire_constants(), lustre_dissect_struct_lov_mds_md(), mdd_swap_layouts(), and mdt_hsm_release().
#define LUSTRE_BUFCOUNT
Value:
((tvb_get_letohl(tvb, LUSTRE_MAGIC_OFFSET)== LUSTRE_MSG_MAGIC_V2) \
    ? (tvb_get_letohl(tvb, LUSTRE_BUFCOUNT_OFF)) : ((tvb_get_letohl(tvb, LUSTRE_BUFCOUNT_OFF))) )
Definition at line 51 of file packet-lustre.c.
Referenced by lustre_ldlm_opcode_process(), lustre_llog_opcode_process(), lustre_opcode_process(), lustre_ost_opcode_process(), reint_opcode_process(), and sanity_check().
#define LUSTRE_BUFCOUNT_OFF ((tvb_get_letohl(tvb, LUSTRE_MAGIC_OFFSET)== LUSTRE_MSG_MAGIC_V2) ? 0 : 60)
Definition at line 50 of file packet-lustre.c.
#define LUSTRE_BUFFER_LEN (_n)
Value:
(LUSTRE_BUFCOUNT <= (_n) ? 0 \
                               : tvb_get_letohl(tvb, LUSTRE_BUFLEN_OFF+\
                                                sizeof(guint32)*(_n)))
Definition at line 60 of file packet-lustre.c.
Referenced by lustre_dissect_element_data(), lustre_dissect_element_string(), lustre_dissect_struct_acl(), lustre_dissect_struct_capa(), lustre_dissect_struct_lov_mds_md(), lustre_dissect_struct_lu_ladvise(), lustre_ldlm_opcode_process(), lustre_mds_opcode_process(), lustre_ost_opcode_process(), and reint_opcode_process().
#define LUSTRE_BUFLEN_OFF ((tvb_get_letohl(tvb, LUSTRE_MAGIC_OFFSET)== LUSTRE_MSG_MAGIC_V2) ? 32 : 60)
Definition at line 57 of file packet-lustre.c.
Referenced by lustre_llog_opcode_process(), and sanity_check().
#define LUSTRE_DLM_INTENT_IT_OFF 2
Definition at line 67 of file packet-lustre.c.
#define LUSTRE_DLM_INTENT_REC_OFF 3
Definition at line 68 of file packet-lustre.c.
Referenced by ldlm_opcode_process(), and lustre_ldlm_opcode_process().
#define LUSTRE_DLM_LOCKREPLY_OFF 1
Definition at line 69 of file packet-lustre.c.
#define LUSTRE_DLM_REPLY_REC_OFF 2
Definition at line 70 of file packet-lustre.c.
Referenced by lustre_ldlm_opcode_process().
#define LUSTRE_DLM_VERSION 0x00040000
Definition at line 79 of file packet-lustre.c.
Referenced by check_ptlrpc_body(), ldlm_cli_cancel_req(), ldlm_cli_convert(), ldlm_cli_enqueue(), ldlm_prep_enqueue_req(), lustre_assert_wire_constants(), mgc_enqueue(), and replay_one_lock().
#define LUSTRE_LOG_VERSION 0x00050000
Definition at line 80 of file packet-lustre.c.
Referenced by check_ptlrpc_body(), llog_client_destroy(), llog_client_next_block(), llog_client_open(), llog_client_prev_block(), llog_client_read_header(), and lustre_assert_wire_constants().
#define LUSTRE_MAGIC_OFFSET 8
Definition at line 46 of file packet-lustre.c.
#define LUSTRE_MDS_VERSION 0x00020000
Definition at line 77 of file packet-lustre.c.
Referenced by check_ptlrpc_body(), fld_client_rpc(), lustre_assert_wire_constants(), mdc_close(), mdc_fsync(), mdc_get_info_rpc(), mdc_get_remote_perm(), mdc_get_root(), mdc_getattr(), mdc_getattr_name(), mdc_getpage(), mdc_ioc_hsm_ct_register(), mdc_ioc_hsm_ct_unregister(), mdc_ioc_hsm_current_action(), mdc_ioc_hsm_progress(), mdc_ioc_hsm_request(), mdc_ioc_hsm_state_get(), mdc_ioc_hsm_state_set(), mdc_prep_elc_req(), mdc_quotactl(), mdc_set_info_async(), mdc_statfs(), mdc_xattr_common(), osp_obd_set_info_async(), osp_prep_inline_update_req(), osp_prep_update_req(), qsd_send_dqacq(), and seq_client_rpc().
#define LUSTRE_MGS_VERSION 0x00060000
Definition at line 81 of file packet-lustre.c.
Referenced by check_ptlrpc_body(), lustre_assert_wire_constants(), mgc_process_recover_log(), mgc_set_mgs_param(), and mgc_target_register().
#define LUSTRE_MSG_MAGIC_V1 0x0BD00BD0
Definition at line 47 of file packet-lustre.c.
Referenced by dissect_lustre(), and lustre_msg_check_version().
#define LUSTRE_MSG_MAGIC_V2 0x0BD00BD3
Definition at line 48 of file packet-lustre.c.
Referenced by __lustre_swab_buf(), _sptlrpc_enlarge_msg_inplace(), check_lustre_msg_v2(), class_new_import(), dissect_lustre(), lustre_assert_wire_constants(), lustre_init_msg_v2(), lustre_msg_add_flags(), lustre_msg_add_op_flags(), lustre_msg_add_version(), lustre_msg_buf(), lustre_msg_bufcount(), lustre_msg_buflen(), lustre_msg_calc_cksum(), lustre_msg_check_version(), lustre_msg_clear_flags(), lustre_msg_early_size(), lustre_msg_get_cksum(), lustre_msg_get_conn_cnt(), lustre_msg_get_flags(), lustre_msg_get_handle(), lustre_msg_get_jobid(), lustre_msg_get_last_committed(), lustre_msg_get_last_xid(), lustre_msg_get_limit(), lustre_msg_get_magic(), lustre_msg_get_mbits(), lustre_msg_get_op_flags(), lustre_msg_get_opc(), lustre_msg_get_service_time(), lustre_msg_get_slv(), lustre_msg_get_status(), lustre_msg_get_tag(), lustre_msg_get_timeout(), lustre_msg_get_transno(), lustre_msg_get_type(), lustre_msg_get_version(), lustre_msg_get_versions(), lustre_msg_hdr_size(), lustre_msg_set_buflen(), lustre_msg_set_cksum(), lustre_msg_set_conn_cnt(), lustre_msg_set_flags(), lustre_msg_set_handle(), lustre_msg_set_jobid(), lustre_msg_set_last_committed(), lustre_msg_set_last_xid(), lustre_msg_set_limit(), lustre_msg_set_mbits(), lustre_msg_set_opc(), lustre_msg_set_service_time(), lustre_msg_set_slv(), lustre_msg_set_status(), lustre_msg_set_tag(), lustre_msg_set_timeout(), lustre_msg_set_transno(), lustre_msg_set_type(), lustre_msg_set_versions(), lustre_msg_size(), lustre_msg_string(), lustre_msghdr_get_flags(), lustre_msghdr_set_flags(), lustre_pack_reply_flags(), lustre_pack_request(), lustre_packed_msg_size(), lustre_shrink_msg(), lustre_unpack_rep_ptlrpc_body(), lustre_unpack_req_ptlrpc_body(), ptlrpc_req_get_repsize(), ptlrpc_req_set_repsize(), ptlrpc_request_set_replen(), rep_ptlrpc_body_swabbed(), and req_ptlrpc_body_swabbed().
#define LUSTRE_OBD_VERSION 0x00010000
Definition at line 76 of file packet-lustre.c.
Referenced by check_ptlrpc_body(), gss_do_ctx_fini_rpc(), gss_do_ctx_init_rpc(), lfsck_async_request(), lfsck_layout_async_notify(), lfsck_layout_async_query(), lfsck_layout_master_conditional_destroy(), lfsck_layout_slave_check_pairs(), lfsck_namespace_notify_lmv_remote(), lustre_assert_wire_constants(), mdt_hsm_agent_send(), osp_it_fetch(), ptlrpc_connect_import(), ptlrpc_disconnect_import(), ptlrpc_prep_ping(), qsd_fetch_index(), and signal_completed_replay().
#define LUSTRE_OST_VERSION 0x00030000
Definition at line 78 of file packet-lustre.c.
Referenced by check_ptlrpc_body(), lustre_assert_wire_constants(), osc_brw_prep_request(), osc_create(), osc_destroy(), osc_getattr(), osc_io_data_version_start(), osc_ladvise_base(), osc_object_fiemap(), osc_punch_base(), osc_quotactl(), osc_set_info_async(), osc_setattr(), osc_setattr_async(), osc_statfs(), osc_statfs_async(), osc_sync_base(), osp_get_lastfid_from_ost(), osp_obd_set_info_async(), osp_obd_statfs(), osp_object_truncate(), osp_precreate_cleanup_orphans(), osp_precreate_send(), osp_statfs_update(), and osp_sync_new_job().
#define LUSTRE_PTLRPC_MSG_VERSION 0x00000003
Definition at line 74 of file packet-lustre.c.
Referenced by lustre_dissect_struct_ptlrpc_body().
#define LUSTRE_REPLY_REC_OFF 1
Definition at line 65 of file packet-lustre.c.
Referenced by lustre_ldlm_opcode_process(), lustre_llog_opcode_process(), lustre_mds_opcode_process(), and lustre_ost_opcode_process().
#define LUSTRE_REQ_REC_OFF 1
Definition at line 64 of file packet-lustre.c.
Referenced by lustre_llog_opcode_process(), lustre_mds_opcode_process(), lustre_ost_opcode_process(), and reint_opcode_process().
#define LUSTRE_VERSION_MASK 0xffff0000
Definition at line 75 of file packet-lustre.c.
Referenced by check_ptlrpc_body(), lustre_assert_wire_constants(), lustre_dissect_struct_ptlrpc_body(), lustre_msg_check_version_v2(), and lustre_unpack_ptlrpc_body_v2().
#define MDS_FIRST_OPC MDS_GETATTR
Definition at line 245 of file packet-lustre.c.
Referenced by lustre_assert_wire_constants(), lustre_opcode_process(), main(), and opcode_offset().
#define MGS_FIRST_OPC MGS_CONNECT
Definition at line 318 of file packet-lustre.c.
Referenced by lustre_opcode_process(), and opcode_offset().
#define OBD_FIRST_OPC OBD_PING
Definition at line 195 of file packet-lustre.c.
Referenced by lustre_opcode_process(), and opcode_offset().
#define OBD_PING (400)
Definition at line 303 of file packet-lustre.c.
Referenced by after_reply(), lustre_assert_wire_constants(), lustre_odb_opcode_process(), main(), ptlrpc_hpreq_handler(), ptlrpc_import_delay_req(), ptlrpc_nrs_hpreq_add_nolock(), ptlrpc_prep_ping(), ptlrpc_server_handle_request(), signal_completed_replay(), and tgt_filter_recovery_request().
#define PTL_RPC_MSG_ERR 4712
Definition at line 360 of file packet-lustre.c.
Referenced by after_reply(), lustre_assert_wire_constants(), lustre_mds_opcode_process(), lustre_msg_get_type(), main(), mdc_close(), ptlrpc_at_set_reply(), ptlrpc_check_status(), ptlrpc_replay_interpret(), ptlrpc_send_error(), and ptlrpc_send_reply().
#define PTL_RPC_MSG_REPLY 4713
Definition at line 361 of file packet-lustre.c.
Referenced by after_reply(), lustre_assert_wire_constants(), lustre_ldlm_opcode_process(), lustre_llog_opcode_process(), lustre_mds_opcode_process(), lustre_mgs_opcode_process(), lustre_ost_opcode_process(), main(), and ptlrpc_send_reply().
#define PTL_RPC_MSG_REQUEST 4711
Definition at line 359 of file packet-lustre.c.
Referenced by lustre_assert_wire_constants(), lustre_fld_opcode_process(), lustre_ldlm_opcode_process(), lustre_llog_opcode_process(), lustre_mds_opcode_process(), lustre_mgs_opcode_process(), lustre_odb_opcode_process(), lustre_ost_opcode_process(), lustre_seq_opcode_process(), main(), ptl_send_rpc(), ptlrpc_request_bufs_pack(), ptlrpc_server_handle_req_in(), and ptlrpcd_alloc_work().
#define WSHARK_HEAD
Definition at line 1043 of file packet-lustre.c.
#define WSHARK_INIT_DATA
Typedef Documentation
typedef int(dissect_func)(tvbuff_t *tvb, gint offset, packet_info *pinfo _U_, proto_tree *tree, int hfindex)
Definition at line 1037 of file packet-lustre.c.
Enumeration Type Documentation
enum fld_rpc_opc
Enumerator:
FLD_QUERY
FLD_LAST_OPC
FLD_FIRST_OPC
FLD_QUERY
FLD_READ
FLD_LAST_OPC
FLD_FIRST_OPC
Definition at line 278 of file packet-lustre.c.
enum ldlm_cmd
Enumerator:
LDLM_ENQUEUE
LDLM_CONVERT
LDLM_CANCEL
LDLM_BL_CALLBACK
LDLM_CP_CALLBACK
LDLM_GL_CALLBACK
LDLM_LAST_OPC
Definition at line 261 of file packet-lustre.c.
enum llog_cmd_t
Enumerator:
LLOG_ORIGIN_HANDLE_CREATE
LLOG_ORIGIN_HANDLE_NEXT_BLOCK
LLOG_ORIGIN_HANDLE_READ_HEADER
LLOG_ORIGIN_HANDLE_WRITE_REC
LLOG_ORIGIN_HANDLE_CLOSE
LLOG_ORIGIN_CONNECT
LLOG_CATINFO
LLOG_ORIGIN_HANDLE_PREV_BLOCK
LLOG_ORIGIN_HANDLE_DESTROY
LLOG_LAST_OPC
Definition at line 321 of file packet-lustre.c.
enum llog_op_type
Enumerator:
LLOG_PAD_MAGIC
OST_SZ_REC
OST_RAID1_REC
MDS_UNLINK_REC
MDS_SETATTR_REC
OBD_CFG_REC
PTL_CFG_REC
LLOG_GEN_REC
LLOG_JOIN_REC
LLOG_HDR_MAGIC
LLOG_LOGID_MAGIC
LLOG_PAD_MAGIC
OST_SZ_REC
MDS_UNLINK_REC
MDS_UNLINK64_REC
MDS_SETATTR64_REC
OBD_CFG_REC
LLOG_GEN_REC
CHANGELOG_REC
CHANGELOG_USER_REC
HSM_AGENT_REC
UPDATE_REC
LLOG_HDR_MAGIC
LLOG_LOGID_MAGIC
Definition at line 339 of file packet-lustre.c.
enum mds_cmd_t
Enumerator:
MDS_GETATTR
MDS_GETATTR_NAME
MDS_CLOSE
MDS_REINT
MDS_READPAGE
MDS_CONNECT
MDS_DISCONNECT
MDS_GET_ROOT
MDS_STATFS
MDS_PIN
MDS_UNPIN
MDS_SYNC
MDS_DONE_WRITING
MDS_SET_INFO
MDS_QUOTACHECK
MDS_QUOTACTL
MDS_GETXATTR
MDS_SETXATTR
MDS_WRITEPAGE
MDS_IS_SUBDIR
MDS_GET_INFO
MDS_HSM_STATE_GET
MDS_HSM_STATE_SET
MDS_HSM_ACTION
MDS_HSM_PROGRESS
MDS_HSM_REQUEST
MDS_HSM_CT_REGISTER
MDS_HSM_CT_UNREGISTER
MDS_SWAP_LAYOUTS
MDS_LAST_OPC
MDS_GETATTR
MDS_GETATTR_NAME
MDS_CLOSE
MDS_REINT
MDS_READPAGE
MDS_CONNECT
MDS_DISCONNECT
MDS_GET_ROOT
MDS_STATFS
MDS_PIN
MDS_UNPIN
MDS_SYNC
MDS_DONE_WRITING
MDS_SET_INFO
MDS_QUOTACHECK
MDS_QUOTACTL
MDS_GETXATTR
MDS_SETXATTR
MDS_WRITEPAGE
MDS_IS_SUBDIR
MDS_GET_INFO
MDS_HSM_STATE_GET
MDS_HSM_STATE_SET
MDS_HSM_ACTION
MDS_HSM_PROGRESS
MDS_HSM_REQUEST
MDS_HSM_CT_REGISTER
MDS_HSM_CT_UNREGISTER
MDS_SWAP_LAYOUTS
MDS_LAST_OPC
Definition at line 200 of file packet-lustre.c.
enum mds_reint_t
Enumerator:
REINT_SETATTR
REINT_CREATE
REINT_LINK
REINT_UNLINK
REINT_RENAME
REINT_OPEN
REINT_SETXATTR
REINT_MAX
REINT_SETATTR
REINT_CREATE
REINT_LINK
REINT_UNLINK
REINT_RENAME
REINT_OPEN
REINT_SETXATTR
REINT_RMENTRY
REINT_MIGRATE
REINT_MAX
Definition at line 248 of file packet-lustre.c.
enum mgs_cmd_t
Enumerator:
MGS_CONNECT
MGS_DISCONNECT
MGS_EXCEPTION
MGS_TARGET_REG
MGS_TARGET_DEL
MGS_SET_INFO
MGS_CONFIG_READ
MGS_LAST_OPC
MGS_CONNECT
MGS_DISCONNECT
MGS_EXCEPTION
MGS_TARGET_REG
MGS_TARGET_DEL
MGS_SET_INFO
MGS_CONFIG_READ
MGS_LAST_OPC
Definition at line 308 of file packet-lustre.c.
enum obd_cmd_t
Enumerator:
OBD_PING
OBD_LOG_CANCEL
OBD_QC_CALLBACK
OBD_LAST_OPC
OBD_PING
OBD_LOG_CANCEL
OBD_QC_CALLBACK
OBD_IDX_READ
OBD_LAST_OPC
Definition at line 189 of file packet-lustre.c.
enum ost_cmd_t
Enumerator:
OST_REPLY
OST_GETATTR
OST_SETATTR
OST_READ
OST_WRITE
OST_CREATE
OST_DESTROY
OST_GET_INFO
OST_CONNECT
OST_DISCONNECT
OST_PUNCH
OST_OPEN
OST_CLOSE
OST_STATFS
OST_SYNC
OST_SET_INFO
OST_QUOTACHECK
OST_QUOTACTL
OST_QUOTA_ADJUST_QUNIT
OST_LADVISE
OST_LAST_OPC
OST_REPLY
OST_GETATTR
OST_SETATTR
OST_READ
OST_WRITE
OST_CREATE
OST_DESTROY
OST_GET_INFO
OST_CONNECT
OST_DISCONNECT
OST_PUNCH
OST_OPEN
OST_CLOSE
OST_STATFS
OST_SYNC
OST_SET_INFO
OST_QUOTACHECK
OST_QUOTACTL
OST_QUOTA_ADJUST_QUNIT
OST_LADVISE
OST_LAST_OPC
Definition at line 162 of file packet-lustre.c.
enum portal_index_t
Enumerator:
CONNMGR_REQUEST_PORTAL
CONNMGR_REPLY_PORTAL
OSC_REQUEST_PORTAL
OSC_REPLY_PORTAL
OSC_BULK_PORTAL
OST_IO_PORTAL
OST_CREATE_PORTAL
OST_BULK_PORTAL
MDC_REQUEST_PORTAL
MDC_REPLY_PORTAL
MDC_BULK_PORTAL
MDS_REQUEST_PORTAL
MDS_REPLY_PORTAL
MDS_BULK_PORTAL
LDLM_CB_REQUEST_PORTAL
LDLM_CB_REPLY_PORTAL
LDLM_CANCEL_REQUEST_PORTAL
LDLM_CANCEL_REPLY_PORTAL
PTLBD_REQUEST_PORTAL
PTLBD_REPLY_PORTAL
PTLBD_BULK_PORTAL
MDS_SETATTR_PORTAL
MDS_READPAGE_PORTAL
MDS_MDS_PORTAL
MGC_REPLY_PORTAL
MGS_REQUEST_PORTAL
MGS_REPLY_PORTAL
OST_REQUEST_PORTAL
FLD_REQUEST_PORTAL
SEQ_METADATA_PORTAL
SEQ_DATA_PORTAL
SEQ_CONTROLLER_PORTAL
MGS_BULK_PORTAL
Definition at line 90 of file packet-lustre.c.
enum seq_rpc_opc
Enumerator:
SEQ_QUERY
SEQ_LAST_OPC
SEQ_FIRST_OPC
SEQ_QUERY
SEQ_LAST_OPC
SEQ_FIRST_OPC
Definition at line 272 of file packet-lustre.c.
Function Documentation
static int add_extra_padding (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9063 of file packet-lustre.c.
Referenced by lustre_dissect_element_data(), lustre_dissect_element_string(), lustre_dissect_struct_acl(), lustre_dissect_struct_seq(), and lustre_ost_opcode_process().
static void display_info_fstr (proto_item * pi, column_info * cinfo, gint col, const char * format, const gchar * str) [static]
Definition at line 1317 of file packet-lustre.c.
Referenced by lustre_dissect_element_mgs_config_body_name(), lustre_dissect_element_string(), lustre_dissect_struct_ldlm_lock_desc(), lustre_dissect_struct_mdt_rec_create(), lustre_dissect_struct_mdt_rec_link(), lustre_dissect_struct_mdt_rec_rename(), lustre_dissect_struct_mdt_rec_setattr(), lustre_dissect_struct_mdt_rec_setxattr(), lustre_dissect_struct_mdt_rec_unlink(), lustre_dissect_struct_msg_v1(), and lustre_dissect_struct_ptlrpc_body().
static void display_info_str (proto_item * pi, column_info * cinfo, gint col, const gchar * str) [inline, static]
Definition at line 1304 of file packet-lustre.c.
Referenced by lustre_dissect_element_ldlm_intent_opc(), lustre_dissect_struct_msg_v1(), and lustre_dissect_struct_ptlrpc_body().
static void dissect_lustre (tvbuff_t * tvb, packet_info * pinfo, proto_tree * tree) [static]
Definition at line 9778 of file packet-lustre.c.
References lustre_dissect_struct_msg_v1(), lustre_dissect_struct_msg_v2(), LUSTRE_MSG_MAGIC_V1, and LUSTRE_MSG_MAGIC_V2.
Referenced by proto_reg_handoff_lustre().
static int dissect_uint16 (tvbuff_t * tvb, gint offset, packet_info *pinfo _U_, proto_tree * tree, int hfindex) [static]
Definition at line 1355 of file packet-lustre.c.
static int dissect_uint32 (tvbuff_t * tvb, gint offset, packet_info *pinfo _U_, proto_tree * tree, int hfindex) [static]
Definition at line 1347 of file packet-lustre.c.
static int dissect_uint64 (tvbuff_t * tvb, gint offset, packet_info *pinfo _U_, proto_tree * tree, int hfindex) [static]
Definition at line 1339 of file packet-lustre.c.
static int dissect_uint8 (tvbuff_t * tvb, gint offset, packet_info *pinfo _U_, proto_tree * tree, int hfindex) [static]
Definition at line 1363 of file packet-lustre.c.
static int ldlm_opcode_process (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, guint64 intent_opc _U_) [static]
Definition at line 9077 of file packet-lustre.c.
References IT_GETATTR, IT_LOOKUP, IT_OPEN, IT_UNLINK, lustre_dissect_element_data(), lustre_dissect_element_string(), lustre_dissect_struct_capa(), lustre_dissect_struct_mdt_body(), lustre_dissect_struct_mdt_rec_create(), lustre_dissect_struct_mdt_rec_unlink(), and LUSTRE_DLM_INTENT_REC_OFF.
Referenced by lustre_dissect_struct_ldlm_intent().
int lustre_dissect_element_capa_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_)
Definition at line 8146 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_capa().
int lustre_dissect_element_capa_opc (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_)
lustre_capa::lc_opc
Definition at line 8138 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_capa().
static int lustre_dissect_element_cfg_marker_cm_canceltime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6148 of file packet-lustre.c.
Referenced by lustre_dissect_struct_cfg_marker().
static int lustre_dissect_element_cfg_marker_cm_comment (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6187 of file packet-lustre.c.
References lustre_dissect_element_cfg_marker_cm_comment_().
Referenced by lustre_dissect_struct_cfg_marker().
static int lustre_dissect_element_cfg_marker_cm_comment_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6179 of file packet-lustre.c.
References dissect_uint8.
Referenced by lustre_dissect_element_cfg_marker_cm_comment().
static int lustre_dissect_element_cfg_marker_cm_createtime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6140 of file packet-lustre.c.
Referenced by lustre_dissect_struct_cfg_marker().
static int lustre_dissect_element_cfg_marker_cm_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6116 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_cfg_marker().
static int lustre_dissect_element_cfg_marker_cm_step (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6108 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_cfg_marker().
static int lustre_dissect_element_cfg_marker_cm_tgtname (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6167 of file packet-lustre.c.
References lustre_dissect_element_cfg_marker_cm_tgtname_().
Referenced by lustre_dissect_struct_cfg_marker().
static int lustre_dissect_element_cfg_marker_cm_tgtname_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6159 of file packet-lustre.c.
References dissect_uint8.
Referenced by lustre_dissect_element_cfg_marker_cm_tgtname().
static int lustre_dissect_element_cfg_marker_cm_vers (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6124 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_cfg_marker().
static int lustre_dissect_element_cfg_marker_padding (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6132 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_cfg_marker().
static int lustre_dissect_element_data (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_, guint32 buf_num) [static]
Definition at line 1372 of file packet-lustre.c.
References add_extra_padding(), and LUSTRE_BUFFER_LEN.
Referenced by ldlm_opcode_process(), lustre_dissect_struct_lov_mds_md(), lustre_llog_opcode_process(), lustre_mds_opcode_process(), and reint_opcode_process().
static int lustre_dissect_element_handle_cookie (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1424 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_handle_cookie().
static int lustre_dissect_element_ldlm_extent_end (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5199 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_ldlm_extent().
static int lustre_dissect_element_ldlm_extent_gid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5207 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_ldlm_extent().
static int lustre_dissect_element_ldlm_extent_start (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5191 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_ldlm_extent().
static int lustre_dissect_element_ldlm_flock_blocking_export (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5303 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_ldlm_flock().
static int lustre_dissect_element_ldlm_flock_blocking_pid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5311 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_ldlm_flock().
static int lustre_dissect_element_ldlm_flock_end (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5295 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_ldlm_flock().
static int lustre_dissect_element_ldlm_flock_pid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5319 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_ldlm_flock().
static int lustre_dissect_element_ldlm_flock_start (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5287 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_ldlm_flock().
static int lustre_dissect_element_ldlm_inodebits_bits (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5247 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_ldlm_inodebits().
static int lustre_dissect_element_ldlm_intent_opc (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5363 of file packet-lustre.c.
References display_info_str(), dissect_uint32, IT_CREAT, IT_EXEC, IT_GETATTR, IT_GETXATTR, IT_LOOKUP, IT_OPEN, IT_PIN, IT_READDIR, and IT_UNLINK.
Referenced by lustre_dissect_struct_ldlm_intent().
static int lustre_dissect_element_ldlm_lock_desc_l_granted_mode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5524 of file packet-lustre.c.
References lustre_dissect_enum_ldlm_mode().
Referenced by lustre_dissect_struct_ldlm_lock_desc().
static int lustre_dissect_element_ldlm_lock_desc_l_policy_data (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5532 of file packet-lustre.c.
References dissect_uint64, LDLM_EXTENT, LDLM_FLOCK, LDLM_IBITS, LDLM_PLAIN, lustre_dissect_struct_ldlm_extent(), lustre_dissect_struct_ldlm_flock(), and lustre_dissect_struct_ldlm_inodebits().
Referenced by lustre_dissect_struct_ldlm_lock_desc().
static int lustre_dissect_element_ldlm_lock_desc_l_req_mode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5516 of file packet-lustre.c.
References lustre_dissect_enum_ldlm_mode().
Referenced by lustre_dissect_struct_ldlm_lock_desc().
static int lustre_dissect_element_ldlm_lock_desc_l_resource (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5509 of file packet-lustre.c.
References lustre_dissect_struct_ldlm_resource_desc().
Referenced by lustre_dissect_struct_ldlm_lock_desc().
static int lustre_dissect_element_ldlm_reply_lock_desc (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5696 of file packet-lustre.c.
References lustre_dissect_struct_ldlm_lock_desc().
Referenced by lustre_dissect_struct_ldlm_reply().
static int lustre_dissect_element_ldlm_reply_lock_handle (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5703 of file packet-lustre.c.
References lustre_dissect_struct_handle_cookie().
Referenced by lustre_dissect_struct_ldlm_reply().
static int lustre_dissect_element_ldlm_reply_lock_padding (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5688 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_ldlm_reply().
static int lustre_dissect_element_ldlm_reply_lock_policy_res1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5713 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_ldlm_reply().
static int lustre_dissect_element_ldlm_reply_lock_policy_res2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5721 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_ldlm_reply().
static int lustre_dissect_element_ldlm_request_lock_count (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5615 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_ldlm_request().
static int lustre_dissect_element_ldlm_request_lock_desc (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5623 of file packet-lustre.c.
References lustre_dissect_struct_ldlm_lock_desc().
Referenced by lustre_dissect_struct_ldlm_request().
static int lustre_dissect_element_ldlm_request_lock_handle (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, int num_locks _U_) [static]
Definition at line 5642 of file packet-lustre.c.
References lustre_dissect_element_ldlm_request_lock_handle_().
Referenced by lustre_dissect_struct_ldlm_request().
static int lustre_dissect_element_ldlm_request_lock_handle_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5632 of file packet-lustre.c.
References lustre_dissect_struct_handle_cookie().
Referenced by lustre_dissect_element_ldlm_request_lock_handle().
static int lustre_dissect_element_ldlm_res_id_name (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5113 of file packet-lustre.c.
References lustre_dissect_element_ldlm_res_id_name_().
Referenced by lustre_dissect_struct_ldlm_res_id().
static int lustre_dissect_element_ldlm_res_id_name_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5105 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_element_ldlm_res_id_name().
static int lustre_dissect_element_ldlm_resource_desc_lr_name (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5465 of file packet-lustre.c.
References lustre_dissect_struct_ldlm_res_id().
Referenced by lustre_dissect_struct_ldlm_resource_desc().
static int lustre_dissect_element_ldlm_resource_desc_lr_padding (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5457 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_ldlm_resource_desc().
static int lustre_dissect_element_ldlm_resource_desc_lr_type (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5449 of file packet-lustre.c.
References lustre_dissect_enum_ldlm_type().
Referenced by lustre_dissect_struct_ldlm_resource_desc().
static int lustre_dissect_element_ll_fid_f_type (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2338 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_lu_fid().
static int lustre_dissect_element_ll_fid_generation (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2330 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_lu_fid().
static int lustre_dissect_element_ll_fid_id (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2322 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_lu_fid().
static int lustre_dissect_element_llog_catid_lci_logid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6304 of file packet-lustre.c.
Referenced by lustre_dissect_struct_llog_catid().
static int lustre_dissect_element_llog_catid_lci_padding1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6313 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_catid().
static int lustre_dissect_element_llog_catid_lci_padding2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6321 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_catid().
static int lustre_dissect_element_llog_catid_lci_padding3 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6329 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_catid().
static int lustre_dissect_element_llog_cookie_lgc_index (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7199 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_cookie().
static int lustre_dissect_element_llog_cookie_lgc_lgl (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7184 of file packet-lustre.c.
References lustre_dissect_struct_llog_logid().
Referenced by lustre_dissect_struct_llog_cookie().
static int lustre_dissect_element_llog_cookie_lgc_padding (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7207 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_cookie().
static int lustre_dissect_element_llog_cookie_lgc_subsys (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7191 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_cookie().
static int lustre_dissect_element_llog_gen_conn_cnt (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6883 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_llog_gen().
static int lustre_dissect_element_llog_gen_mnt_cnt (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6875 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_llog_gen().
static int lustre_dissect_element_llog_gen_rec_lgr_gen (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6934 of file packet-lustre.c.
Referenced by lustre_dissect_struct_llog_gen_rec().
static int lustre_dissect_element_llog_gen_rec_lgr_hdr (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6926 of file packet-lustre.c.
Referenced by lustre_dissect_struct_llog_gen_rec().
static int lustre_dissect_element_llog_gen_rec_lgr_tail (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6942 of file packet-lustre.c.
Referenced by lustre_dissect_struct_llog_gen_rec().
static int lustre_dissect_element_llog_log_hdr_llh_bitmap (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7110 of file packet-lustre.c.
References lustre_dissect_element_llog_log_hdr_llh_bitmap_().
Referenced by lustre_dissect_struct_llog_log_hdr().
static int lustre_dissect_element_llog_log_hdr_llh_bitmap_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7101 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_element_llog_log_hdr_llh_bitmap().
static int lustre_dissect_element_llog_log_hdr_llh_bitmap_offset (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7024 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_log_hdr().
static int lustre_dissect_element_llog_log_hdr_llh_cat_idx (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7068 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_log_hdr().
static int lustre_dissect_element_llog_log_hdr_llh_count (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7016 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_log_hdr().
static int lustre_dissect_element_llog_log_hdr_llh_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7060 of file packet-lustre.c.
References lustre_dissect_element_llog_log_llh_flags().
Referenced by lustre_dissect_struct_llog_log_hdr().
static int lustre_dissect_element_llog_log_hdr_llh_hdr (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6998 of file packet-lustre.c.
References lustre_dissect_struct_llog_rec_hdr().
Referenced by lustre_dissect_struct_llog_log_hdr().
static int lustre_dissect_element_llog_log_hdr_llh_reserved (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7091 of file packet-lustre.c.
References lustre_dissect_element_llog_log_hdr_llh_reserved_().
Referenced by lustre_dissect_struct_llog_log_hdr().
static int lustre_dissect_element_llog_log_hdr_llh_reserved_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7083 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_element_llog_log_hdr_llh_reserved().
static int lustre_dissect_element_llog_log_hdr_llh_size (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7032 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_log_hdr().
static int lustre_dissect_element_llog_log_hdr_llh_tail (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7122 of file packet-lustre.c.
References lustre_dissect_struct_llog_rec_tail().
Referenced by lustre_dissect_struct_llog_log_hdr().
static int lustre_dissect_element_llog_log_hdr_llh_tgtuuid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7076 of file packet-lustre.c.
References lustre_dissect_struct_obd_uuid().
Referenced by lustre_dissect_struct_llog_log_hdr().
static int lustre_dissect_element_llog_log_hdr_llh_timestamp (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7005 of file packet-lustre.c.
Referenced by lustre_dissect_struct_llog_log_hdr().
static int lustre_dissect_element_llog_log_llh_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_) [static]
Definition at line 7042 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_element_llog_log_hdr_llh_flags(), and lustre_dissect_element_llogd_body_lgd_llh_flags().
static int lustre_dissect_element_llog_logid_lgl_ogen (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6259 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_logid().
static int lustre_dissect_element_llog_logid_lgl_oid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6243 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_llog_logid().
static int lustre_dissect_element_llog_logid_lgl_oseq (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6251 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_llog_logid().
static int lustre_dissect_element_llog_logid_rec_lid_hdr (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6497 of file packet-lustre.c.
References lustre_dissect_struct_llog_rec_hdr().
Referenced by lustre_dissect_struct_llog_logid_rec().
static int lustre_dissect_element_llog_logid_rec_lid_id (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6504 of file packet-lustre.c.
References lustre_dissect_struct_llog_logid().
Referenced by lustre_dissect_struct_llog_logid_rec().
static int lustre_dissect_element_llog_logid_rec_lid_tail (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6551 of file packet-lustre.c.
References lustre_dissect_struct_llog_rec_tail().
Referenced by lustre_dissect_struct_llog_logid_rec().
static int lustre_dissect_element_llog_logid_rec_padding1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6511 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_logid_rec().
static int lustre_dissect_element_llog_logid_rec_padding2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6519 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_logid_rec().
static int lustre_dissect_element_llog_logid_rec_padding3 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6527 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_logid_rec().
static int lustre_dissect_element_llog_logid_rec_padding4 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6535 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_logid_rec().
static int lustre_dissect_element_llog_logid_rec_padding5 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6543 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_logid_rec().
static int lustre_dissect_element_llog_rec_hdr_lrh_index (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6382 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_rec_hdr().
static int lustre_dissect_element_llog_rec_hdr_lrh_len (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6374 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_rec_hdr().
static int lustre_dissect_element_llog_rec_hdr_lrh_type (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6390 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_rec_hdr().
static int lustre_dissect_element_llog_rec_hdr_padding (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6398 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_rec_hdr().
static int lustre_dissect_element_llog_rec_tail_lrt_index (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6449 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_rec_tail().
static int lustre_dissect_element_llog_rec_tail_lrt_len (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6441 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_rec_tail().
static int lustre_dissect_element_llog_setattr_rec_lsr_gid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6724 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_setattr_rec().
static int lustre_dissect_element_llog_setattr_rec_lsr_hdr (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6693 of file packet-lustre.c.
Referenced by lustre_dissect_struct_llog_setattr_rec().
static int lustre_dissect_element_llog_setattr_rec_lsr_ogen (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6708 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_setattr_rec().
static int lustre_dissect_element_llog_setattr_rec_lsr_oid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6700 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_llog_setattr_rec().
static int lustre_dissect_element_llog_setattr_rec_lsr_tail (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6740 of file packet-lustre.c.
Referenced by lustre_dissect_struct_llog_setattr_rec().
static int lustre_dissect_element_llog_setattr_rec_lsr_uid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6716 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_setattr_rec().
static int lustre_dissect_element_llog_setattr_rec_padding (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6732 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_setattr_rec().
static int lustre_dissect_element_llog_size_change_rec_lsc_fid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6804 of file packet-lustre.c.
Referenced by lustre_dissect_struct_llog_size_change_rec().
static int lustre_dissect_element_llog_size_change_rec_lsc_hdr (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6797 of file packet-lustre.c.
Referenced by lustre_dissect_struct_llog_size_change_rec().
static int lustre_dissect_element_llog_size_change_rec_lsc_io_epoch (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6811 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_size_change_rec().
static int lustre_dissect_element_llog_size_change_rec_lsc_tail (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6827 of file packet-lustre.c.
Referenced by lustre_dissect_struct_llog_size_change_rec().
static int lustre_dissect_element_llog_size_change_rec_padding (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6819 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_size_change_rec().
static int lustre_dissect_element_llog_unlink_rec_lur_hdr (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6609 of file packet-lustre.c.
Referenced by lustre_dissect_struct_llog_unlink_rec().
static int lustre_dissect_element_llog_unlink_rec_lur_ogen (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6624 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_unlink_rec().
static int lustre_dissect_element_llog_unlink_rec_lur_oid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6616 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_llog_unlink_rec().
static int lustre_dissect_element_llog_unlink_rec_lur_tail (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6640 of file packet-lustre.c.
Referenced by lustre_dissect_struct_llog_unlink_rec().
static int lustre_dissect_element_llog_unlink_rec_padding (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6632 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llog_unlink_rec().
static int lustre_dissect_element_llogd_body_lgd_ctxt_idx (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7265 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llogd_body().
static int lustre_dissect_element_llogd_body_lgd_cur_offset (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7307 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_llogd_body().
static int lustre_dissect_element_llogd_body_lgd_index (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7283 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llogd_body().
static int lustre_dissect_element_llogd_body_lgd_len (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7299 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llogd_body().
static int lustre_dissect_element_llogd_body_lgd_llh_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7273 of file packet-lustre.c.
References lustre_dissect_element_llog_log_llh_flags().
Referenced by lustre_dissect_struct_llogd_body().
static int lustre_dissect_element_llogd_body_lgd_logid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7258 of file packet-lustre.c.
References lustre_dissect_struct_llog_logid().
Referenced by lustre_dissect_struct_llogd_body().
static int lustre_dissect_element_llogd_body_lgd_saved_index (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7291 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llogd_body().
static int lustre_dissect_element_llogd_conn_body_lgdc_ctxt_idx (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7375 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_llogd_conn_body().
static int lustre_dissect_element_llogd_conn_body_lgdc_gen (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7361 of file packet-lustre.c.
Referenced by lustre_dissect_struct_llogd_conn_body().
static int lustre_dissect_element_llogd_conn_body_lgdc_logid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7368 of file packet-lustre.c.
Referenced by lustre_dissect_struct_llogd_conn_body().
static int lustre_dissect_element_lov_desc_ld_active_tgt_count (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4962 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_lov_desc().
static int lustre_dissect_element_lov_desc_ld_default_stripe_count (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4970 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_lov_desc().
static int lustre_dissect_element_lov_desc_ld_default_stripe_offset (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4994 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_lov_desc().
static int lustre_dissect_element_lov_desc_ld_default_stripe_size (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4986 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_lov_desc().
static int lustre_dissect_element_lov_desc_ld_padding_0 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5002 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_lov_desc().
static int lustre_dissect_element_lov_desc_ld_padding_1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5018 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_lov_desc().
static int lustre_dissect_element_lov_desc_ld_padding_2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5026 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_lov_desc().
static int lustre_dissect_element_lov_desc_ld_pattern (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4978 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_lov_desc().
static int lustre_dissect_element_lov_desc_ld_qos_maxage (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5010 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_lov_desc().
static int lustre_dissect_element_lov_desc_ld_tgt_count (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4954 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_lov_desc().
static int lustre_dissect_element_lov_desc_ld_uuid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5034 of file packet-lustre.c.
Referenced by lustre_dissect_struct_lov_desc().
static int lustre_dissect_element_lov_mds_md_v1_lmm_magic (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1703 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_lov_mds_md_v1().
static int lustre_dissect_element_lov_mds_md_v1_lmm_object_id (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1719 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_lov_mds_md_v1().
static int lustre_dissect_element_lov_mds_md_v1_lmm_object_seq (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1727 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_lov_mds_md_v1().
static int lustre_dissect_element_lov_mds_md_v1_lmm_objects (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, int num) [static]
Definition at line 1758 of file packet-lustre.c.
References lustre_dissect_element_lov_mds_md_v1_lmm_objects_().
Referenced by lustre_dissect_struct_lov_mds_md_v1().
static int lustre_dissect_element_lov_mds_md_v1_lmm_objects_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1751 of file packet-lustre.c.
References lustre_dissect_struct_lov_ost_data_v1().
Referenced by lustre_dissect_element_lov_mds_md_v1_lmm_objects().
static int lustre_dissect_element_lov_mds_md_v1_lmm_pattern (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1711 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_lov_mds_md_v1().
static int lustre_dissect_element_lov_mds_md_v1_lmm_stripe_count (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1743 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_lov_mds_md_v1().
static int lustre_dissect_element_lov_mds_md_v1_lmm_stripe_size (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1735 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_lov_mds_md_v1().
static int lustre_dissect_element_lov_ost_data_v1_l_object_id (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1630 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_lov_ost_data_v1().
static int lustre_dissect_element_lov_ost_data_v1_l_object_seq (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1638 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_lov_ost_data_v1().
static int lustre_dissect_element_lov_ost_data_v1_l_ost_gen (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1646 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_lov_ost_data_v1().
static int lustre_dissect_element_lov_ost_data_v1_l_ost_idx (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1654 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_lov_ost_data_v1().
static int lustre_dissect_element_mdt_body_aclsize (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2994 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_atime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2849 of file packet-lustre.c.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_blocks (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2874 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_capability (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2914 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_ctime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2862 of file packet-lustre.c.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_eadatasize (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2986 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_fid1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2799 of file packet-lustre.c.
References lustre_dissect_struct_lu_fid().
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_fid2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2806 of file packet-lustre.c.
References lustre_dissect_struct_lu_fid().
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2946 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_fsgid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2906 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_fsuid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2898 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_generation (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2970 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_gid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2938 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_gid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3026 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_handle (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2813 of file packet-lustre.c.
References lustre_dissect_struct_handle_cookie().
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_ino (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2890 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_ioepoch (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2882 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_max_cookiesize (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3010 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_max_mdsize (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3002 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_mode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2922 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_mtime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2837 of file packet-lustre.c.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_nlink (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2962 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_padding_10 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3074 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_padding_5 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3034 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_padding_6 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3042 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_padding_7 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3050 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_padding_8 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3058 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_padding_9 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3066 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_rdev (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2954 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_size (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2829 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_suppgid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2978 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_uid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2930 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_uid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3018 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_body_valid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2821 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_body().
static int lustre_dissect_element_mdt_rec_create_cr_bias (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3667 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_create().
static int lustre_dissect_element_mdt_rec_create_cr_cap (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3529 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_create().
static int lustre_dissect_element_mdt_rec_create_cr_fid1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3601 of file packet-lustre.c.
References lustre_dissect_struct_lu_fid().
Referenced by lustre_dissect_struct_mdt_rec_create().
static int lustre_dissect_element_mdt_rec_create_cr_fid2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3608 of file packet-lustre.c.
References lustre_dissect_struct_lu_fid().
Referenced by lustre_dissect_struct_mdt_rec_create().
static int lustre_dissect_element_mdt_rec_create_cr_flags_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3683 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_create().
static int lustre_dissect_element_mdt_rec_create_cr_flags_l (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3675 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_create().
static int lustre_dissect_element_mdt_rec_create_cr_fsgid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3553 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_create().
static int lustre_dissect_element_mdt_rec_create_cr_fsgid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3561 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_create().
static int lustre_dissect_element_mdt_rec_create_cr_fsuid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3537 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_create().
static int lustre_dissect_element_mdt_rec_create_cr_fsuid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3545 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_create().
static int lustre_dissect_element_mdt_rec_create_cr_ioepoch (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3643 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_rec_create().
static int lustre_dissect_element_mdt_rec_create_cr_mode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3659 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_create().
static int lustre_dissect_element_mdt_rec_create_cr_old_handle (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3615 of file packet-lustre.c.
References lustre_dissect_struct_handle_cookie().
Referenced by lustre_dissect_struct_mdt_rec_create().
static int lustre_dissect_element_mdt_rec_create_cr_opcode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3521 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_create().
static int lustre_dissect_element_mdt_rec_create_cr_padding_1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3651 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_rec_create().
static int lustre_dissect_element_mdt_rec_create_cr_padding_4 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3699 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_create().
static int lustre_dissect_element_mdt_rec_create_cr_rdev (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3635 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_rec_create().
static int lustre_dissect_element_mdt_rec_create_cr_suppgid1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3569 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_create().
static int lustre_dissect_element_mdt_rec_create_cr_suppgid1_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3577 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_create().
static int lustre_dissect_element_mdt_rec_create_cr_suppgid2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3585 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_create().
static int lustre_dissect_element_mdt_rec_create_cr_suppgid2_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3593 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_create().
static int lustre_dissect_element_mdt_rec_create_cr_time (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3622 of file packet-lustre.c.
Referenced by lustre_dissect_struct_mdt_rec_create().
static int lustre_dissect_element_mdt_rec_create_cr_umask (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3691 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_create().
static int lustre_dissect_element_mdt_rec_link_lk_bias (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3945 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_link().
static int lustre_dissect_element_mdt_rec_link_lk_cap (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3815 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_link().
static int lustre_dissect_element_mdt_rec_link_lk_fid1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3887 of file packet-lustre.c.
References lustre_dissect_struct_lu_fid().
Referenced by lustre_dissect_struct_mdt_rec_link().
static int lustre_dissect_element_mdt_rec_link_lk_fid2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3894 of file packet-lustre.c.
References lustre_dissect_struct_lu_fid().
Referenced by lustre_dissect_struct_mdt_rec_link().
static int lustre_dissect_element_mdt_rec_link_lk_fsgid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3839 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_link().
static int lustre_dissect_element_mdt_rec_link_lk_fsgid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3847 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_link().
static int lustre_dissect_element_mdt_rec_link_lk_fsuid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3823 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_link().
static int lustre_dissect_element_mdt_rec_link_lk_fsuid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3831 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_link().
static int lustre_dissect_element_mdt_rec_link_lk_opcode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3807 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_link().
static int lustre_dissect_element_mdt_rec_link_lk_padding_1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3913 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_rec_link().
static int lustre_dissect_element_mdt_rec_link_lk_padding_2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3921 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_rec_link().
static int lustre_dissect_element_mdt_rec_link_lk_padding_3 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3929 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_rec_link().
static int lustre_dissect_element_mdt_rec_link_lk_padding_4 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3937 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_rec_link().
static int lustre_dissect_element_mdt_rec_link_lk_padding_5 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3953 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_link().
static int lustre_dissect_element_mdt_rec_link_lk_padding_6 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3961 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_link().
static int lustre_dissect_element_mdt_rec_link_lk_padding_7 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3969 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_link().
static int lustre_dissect_element_mdt_rec_link_lk_padding_8 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3977 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_link().
static int lustre_dissect_element_mdt_rec_link_lk_padding_9 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3985 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_link().
static int lustre_dissect_element_mdt_rec_link_lk_suppgid1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3855 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_link().
static int lustre_dissect_element_mdt_rec_link_lk_suppgid1_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3863 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_link().
static int lustre_dissect_element_mdt_rec_link_lk_suppgid2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3871 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_link().
static int lustre_dissect_element_mdt_rec_link_lk_suppgid2_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3879 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_link().
static int lustre_dissect_element_mdt_rec_link_lk_time (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3901 of file packet-lustre.c.
Referenced by lustre_dissect_struct_mdt_rec_link().
static int lustre_dissect_element_mdt_rec_rename_rn_bias (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4506 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_rename().
static int lustre_dissect_element_mdt_rec_rename_rn_cap (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4376 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_rename().
static int lustre_dissect_element_mdt_rec_rename_rn_fid1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4448 of file packet-lustre.c.
References lustre_dissect_struct_lu_fid().
Referenced by lustre_dissect_struct_mdt_rec_rename().
static int lustre_dissect_element_mdt_rec_rename_rn_fid2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4455 of file packet-lustre.c.
References lustre_dissect_struct_lu_fid().
Referenced by lustre_dissect_struct_mdt_rec_rename().
static int lustre_dissect_element_mdt_rec_rename_rn_fsgid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4400 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_rename().
static int lustre_dissect_element_mdt_rec_rename_rn_fsgid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4408 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_rename().
static int lustre_dissect_element_mdt_rec_rename_rn_fsuid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4384 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_rename().
static int lustre_dissect_element_mdt_rec_rename_rn_fsuid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4392 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_rename().
static int lustre_dissect_element_mdt_rec_rename_rn_mode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4514 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_rename().
static int lustre_dissect_element_mdt_rec_rename_rn_opcode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4368 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_rename().
static int lustre_dissect_element_mdt_rec_rename_rn_padding_1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4474 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_rec_rename().
static int lustre_dissect_element_mdt_rec_rename_rn_padding_2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4482 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_rec_rename().
static int lustre_dissect_element_mdt_rec_rename_rn_padding_3 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4490 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_rec_rename().
static int lustre_dissect_element_mdt_rec_rename_rn_padding_4 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4498 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_rec_rename().
static int lustre_dissect_element_mdt_rec_rename_rn_padding_5 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4522 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_rename().
static int lustre_dissect_element_mdt_rec_rename_rn_padding_6 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4530 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_rename().
static int lustre_dissect_element_mdt_rec_rename_rn_padding_7 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4538 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_rename().
static int lustre_dissect_element_mdt_rec_rename_rn_padding_8 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4546 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_rename().
static int lustre_dissect_element_mdt_rec_rename_rn_suppgid1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4416 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_rename().
static int lustre_dissect_element_mdt_rec_rename_rn_suppgid1_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4424 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_rename().
static int lustre_dissect_element_mdt_rec_rename_rn_suppgid2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4432 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_rename().
static int lustre_dissect_element_mdt_rec_rename_rn_suppgid2_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4440 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_rename().
static int lustre_dissect_element_mdt_rec_rename_rn_time (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4462 of file packet-lustre.c.
Referenced by lustre_dissect_struct_mdt_rec_rename().
static int lustre_dissect_element_mdt_rec_setattr_sa_atime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3345 of file packet-lustre.c.
Referenced by lustre_dissect_struct_mdt_rec_setattr().
static int lustre_dissect_element_mdt_rec_setattr_sa_attr_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3369 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setattr().
static int lustre_dissect_element_mdt_rec_setattr_sa_blocks (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3324 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_rec_setattr().
static int lustre_dissect_element_mdt_rec_setattr_sa_cap (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3212 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setattr().
static int lustre_dissect_element_mdt_rec_setattr_sa_ctime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3357 of file packet-lustre.c.
Referenced by lustre_dissect_struct_mdt_rec_setattr().
static int lustre_dissect_element_mdt_rec_setattr_sa_fid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3284 of file packet-lustre.c.
References lustre_dissect_struct_lu_fid().
Referenced by lustre_dissect_struct_mdt_rec_setattr().
static int lustre_dissect_element_mdt_rec_setattr_sa_fsgid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3236 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setattr().
static int lustre_dissect_element_mdt_rec_setattr_sa_fsgid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3244 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setattr().
static int lustre_dissect_element_mdt_rec_setattr_sa_fsuid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3220 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setattr().
static int lustre_dissect_element_mdt_rec_setattr_sa_fsuid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3228 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setattr().
static int lustre_dissect_element_mdt_rec_setattr_sa_gid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3308 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setattr().
static int lustre_dissect_element_mdt_rec_setattr_sa_mode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3377 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setattr().
static int lustre_dissect_element_mdt_rec_setattr_sa_mtime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3332 of file packet-lustre.c.
Referenced by lustre_dissect_struct_mdt_rec_setattr().
static int lustre_dissect_element_mdt_rec_setattr_sa_opcode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3204 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setattr().
static int lustre_dissect_element_mdt_rec_setattr_sa_padding_1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3268 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setattr().
static int lustre_dissect_element_mdt_rec_setattr_sa_padding_1_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3276 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setattr().
static int lustre_dissect_element_mdt_rec_setattr_sa_padding_2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3385 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setattr().
static int lustre_dissect_element_mdt_rec_setattr_sa_padding_3 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3393 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setattr().
static int lustre_dissect_element_mdt_rec_setattr_sa_padding_4 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3401 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setattr().
static int lustre_dissect_element_mdt_rec_setattr_sa_padding_5 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3409 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setattr().
static int lustre_dissect_element_mdt_rec_setattr_sa_size (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3316 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_rec_setattr().
static int lustre_dissect_element_mdt_rec_setattr_sa_suppgid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3252 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setattr().
static int lustre_dissect_element_mdt_rec_setattr_sa_suppgid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3260 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setattr().
static int lustre_dissect_element_mdt_rec_setattr_sa_uid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3300 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setattr().
static int lustre_dissect_element_mdt_rec_setattr_sa_valid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 3292 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_rec_setattr().
static int lustre_dissect_element_mdt_rec_setxattr_sx_cap (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4664 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setxattr().
static int lustre_dissect_element_mdt_rec_setxattr_sx_fid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4736 of file packet-lustre.c.
References lustre_dissect_struct_lu_fid().
Referenced by lustre_dissect_struct_mdt_rec_setxattr().
static int lustre_dissect_element_mdt_rec_setxattr_sx_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4821 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setxattr().
static int lustre_dissect_element_mdt_rec_setxattr_sx_fsgid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4688 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setxattr().
static int lustre_dissect_element_mdt_rec_setxattr_sx_fsgid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4696 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setxattr().
static int lustre_dissect_element_mdt_rec_setxattr_sx_fsuid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4672 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setxattr().
static int lustre_dissect_element_mdt_rec_setxattr_sx_fsuid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4680 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setxattr().
static int lustre_dissect_element_mdt_rec_setxattr_sx_opcode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4656 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setxattr().
static int lustre_dissect_element_mdt_rec_setxattr_sx_padding_1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4744 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_rec_setxattr().
static int lustre_dissect_element_mdt_rec_setxattr_sx_padding_10 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4845 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setxattr().
static int lustre_dissect_element_mdt_rec_setxattr_sx_padding_11 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4853 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setxattr().
static int lustre_dissect_element_mdt_rec_setxattr_sx_padding_2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4752 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setxattr().
static int lustre_dissect_element_mdt_rec_setxattr_sx_padding_3 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4760 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setxattr().
static int lustre_dissect_element_mdt_rec_setxattr_sx_padding_5 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4789 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_rec_setxattr().
static int lustre_dissect_element_mdt_rec_setxattr_sx_padding_6 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4797 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_rec_setxattr().
static int lustre_dissect_element_mdt_rec_setxattr_sx_padding_7 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4805 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_rec_setxattr().
static int lustre_dissect_element_mdt_rec_setxattr_sx_padding_8 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4829 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setxattr().
static int lustre_dissect_element_mdt_rec_setxattr_sx_padding_9 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4837 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setxattr().
static int lustre_dissect_element_mdt_rec_setxattr_sx_size (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4813 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setxattr().
static int lustre_dissect_element_mdt_rec_setxattr_sx_suppgid1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4704 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setxattr().
static int lustre_dissect_element_mdt_rec_setxattr_sx_suppgid1_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4712 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setxattr().
static int lustre_dissect_element_mdt_rec_setxattr_sx_suppgid2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4720 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setxattr().
static int lustre_dissect_element_mdt_rec_setxattr_sx_suppgid2_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4728 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_setxattr().
static int lustre_dissect_element_mdt_rec_setxattr_sx_time (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4776 of file packet-lustre.c.
Referenced by lustre_dissect_struct_mdt_rec_setxattr().
static int lustre_dissect_element_mdt_rec_setxattr_sx_valid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4768 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_rec_setxattr().
static int lustre_dissect_element_mdt_rec_unlink_ul_bias (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4230 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_unlink().
static int lustre_dissect_element_mdt_rec_unlink_ul_cap (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4100 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_unlink().
static int lustre_dissect_element_mdt_rec_unlink_ul_fid1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4172 of file packet-lustre.c.
References lustre_dissect_struct_lu_fid().
Referenced by lustre_dissect_struct_mdt_rec_unlink().
static int lustre_dissect_element_mdt_rec_unlink_ul_fid2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4179 of file packet-lustre.c.
References lustre_dissect_struct_lu_fid().
Referenced by lustre_dissect_struct_mdt_rec_unlink().
static int lustre_dissect_element_mdt_rec_unlink_ul_fsgid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4124 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_unlink().
static int lustre_dissect_element_mdt_rec_unlink_ul_fsgid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4132 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_unlink().
static int lustre_dissect_element_mdt_rec_unlink_ul_fsuid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4108 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_unlink().
static int lustre_dissect_element_mdt_rec_unlink_ul_fsuid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4116 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_unlink().
static int lustre_dissect_element_mdt_rec_unlink_ul_mode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4238 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_unlink().
static int lustre_dissect_element_mdt_rec_unlink_ul_opcode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4092 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_unlink().
static int lustre_dissect_element_mdt_rec_unlink_ul_padding_2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4198 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_rec_unlink().
static int lustre_dissect_element_mdt_rec_unlink_ul_padding_3 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4206 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_rec_unlink().
static int lustre_dissect_element_mdt_rec_unlink_ul_padding_4 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4214 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_rec_unlink().
static int lustre_dissect_element_mdt_rec_unlink_ul_padding_5 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4222 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_mdt_rec_unlink().
static int lustre_dissect_element_mdt_rec_unlink_ul_padding_6 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4246 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_unlink().
static int lustre_dissect_element_mdt_rec_unlink_ul_padding_7 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4254 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_unlink().
static int lustre_dissect_element_mdt_rec_unlink_ul_padding_8 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4262 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_unlink().
static int lustre_dissect_element_mdt_rec_unlink_ul_padding_9 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4270 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_unlink().
static int lustre_dissect_element_mdt_rec_unlink_ul_suppgid1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4140 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_unlink().
static int lustre_dissect_element_mdt_rec_unlink_ul_suppgid1_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4148 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_unlink().
static int lustre_dissect_element_mdt_rec_unlink_ul_suppgid2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4156 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_unlink().
static int lustre_dissect_element_mdt_rec_unlink_ul_suppgid2_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4164 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mdt_rec_unlink().
static int lustre_dissect_element_mdt_rec_unlink_ul_time (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 4186 of file packet-lustre.c.
Referenced by lustre_dissect_struct_mdt_rec_unlink().
int lustre_dissect_element_mgs_config_body_name (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 5823 of file packet-lustre.c.
References display_info_fstr().
Referenced by lustre_dissect_struct_mgs_config_body().
static int lustre_dissect_element_mgs_send_param_mgs_param (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5781 of file packet-lustre.c.
References lustre_dissect_element_mgs_send_param_mgs_param_().
Referenced by lustre_dissect_struct_mgs_send_param().
static int lustre_dissect_element_mgs_send_param_mgs_param_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5773 of file packet-lustre.c.
References dissect_uint8.
Referenced by lustre_dissect_element_mgs_send_param_mgs_param().
static int lustre_dissect_element_mgs_target_info_mti_config_ver (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5921 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mgs_target_info().
static int lustre_dissect_element_mgs_target_info_mti_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5929 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mgs_target_info().
static int lustre_dissect_element_mgs_target_info_mti_fsname (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5961 of file packet-lustre.c.
References lustre_dissect_element_mgs_target_info_mti_fsname_().
Referenced by lustre_dissect_struct_mgs_target_info().
static int lustre_dissect_element_mgs_target_info_mti_fsname_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5953 of file packet-lustre.c.
References dissect_uint8.
Referenced by lustre_dissect_element_mgs_target_info_mti_fsname().
static int lustre_dissect_element_mgs_target_info_mti_lustre_ver (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5905 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mgs_target_info().
static int lustre_dissect_element_mgs_target_info_mti_nid_count (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5937 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mgs_target_info().
static int lustre_dissect_element_mgs_target_info_mti_nids (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6023 of file packet-lustre.c.
References lustre_dissect_element_mgs_target_info_mti_nids_().
Referenced by lustre_dissect_struct_mgs_target_info().
static int lustre_dissect_element_mgs_target_info_mti_nids_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6015 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_element_mgs_target_info_mti_nids().
static int lustre_dissect_element_mgs_target_info_mti_params (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6043 of file packet-lustre.c.
References lustre_dissect_element_mgs_target_info_mti_params_().
Referenced by lustre_dissect_struct_mgs_target_info().
static int lustre_dissect_element_mgs_target_info_mti_params_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6035 of file packet-lustre.c.
References dissect_uint8.
Referenced by lustre_dissect_element_mgs_target_info_mti_params().
static int lustre_dissect_element_mgs_target_info_mti_stripe_index (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5913 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mgs_target_info().
static int lustre_dissect_element_mgs_target_info_mti_svname (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5983 of file packet-lustre.c.
References lustre_dissect_element_mgs_target_info_mti_svname_().
Referenced by lustre_dissect_struct_mgs_target_info().
static int lustre_dissect_element_mgs_target_info_mti_svname_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5975 of file packet-lustre.c.
References dissect_uint8.
Referenced by lustre_dissect_element_mgs_target_info_mti_svname().
static int lustre_dissect_element_mgs_target_info_mti_uuid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 6001 of file packet-lustre.c.
References lustre_dissect_element_mgs_target_info_mti_uuid_().
Referenced by lustre_dissect_struct_mgs_target_info().
static int lustre_dissect_element_mgs_target_info_mti_uuid_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5993 of file packet-lustre.c.
References dissect_uint8.
Referenced by lustre_dissect_element_mgs_target_info_mti_uuid().
static int lustre_dissect_element_mgs_target_info_padding (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 5945 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_mgs_target_info().
static int lustre_dissect_element_msg_v1_lm_bufcount (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9264 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_msg_v1().
static int lustre_dissect_element_msg_v1_lm_buflens (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9280 of file packet-lustre.c.
References dissect_uint32, and lustre_dissect_element_msg_v1_lm_buflens_().
Referenced by lustre_dissect_struct_msg_v1().
static int lustre_dissect_element_msg_v1_lm_buflens_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9272 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_element_msg_v1_lm_buflens().
static int lustre_dissect_element_msg_v1_lm_conn_cnt (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9256 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_msg_v1().
static int lustre_dissect_element_msg_v1_lm_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9248 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_msg_v1().
static int lustre_dissect_element_msg_v1_lm_handle (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9176 of file packet-lustre.c.
References lustre_dissect_struct_handle_cookie().
Referenced by lustre_dissect_struct_msg_v1().
static int lustre_dissect_element_msg_v1_lm_last_committed (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9224 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_msg_v1().
static int lustre_dissect_element_msg_v1_lm_last_xid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9216 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_msg_v1().
static int lustre_dissect_element_msg_v1_lm_magic (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9184 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_msg_v1().
static int lustre_dissect_element_msg_v1_lm_opc (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9208 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_msg_v1().
static int lustre_dissect_element_msg_v1_lm_status (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9240 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_msg_v1().
static int lustre_dissect_element_msg_v1_lm_transno (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9232 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_msg_v1().
static int lustre_dissect_element_msg_v1_lm_type (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9192 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_msg_v1().
static int lustre_dissect_element_msg_v1_lm_version (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9200 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_msg_v1().
static int lustre_dissect_element_msg_v2_lm_bufcount (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9640 of file packet-lustre.c.
Referenced by lustre_dissect_struct_msg_v2().
static int lustre_dissect_element_msg_v2_lm_buflens_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9706 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_msg_v2().
static int lustre_dissect_element_msg_v2_lm_cksum (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9672 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_msg_v2().
static int lustre_dissect_element_msg_v2_lm_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9680 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_msg_v2().
static int lustre_dissect_element_msg_v2_lm_magic (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9656 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_msg_v2().
static int lustre_dissect_element_msg_v2_lm_padding_2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9688 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_msg_v2().
static int lustre_dissect_element_msg_v2_lm_padding_3 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9696 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_msg_v2().
static int lustre_dissect_element_msg_v2_lm_repsize (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9664 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_msg_v2().
static int lustre_dissect_element_msg_v2_lm_secflvr (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9648 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_msg_v2().
static int lustre_dissect_element_niobuf_remote_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2185 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_niobuf_remote().
static int lustre_dissect_element_niobuf_remote_len (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2177 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_niobuf_remote().
static int lustre_dissect_element_niobuf_remote_offset (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2169 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_niobuf_remote().
static int lustre_dissect_element_obd_connect_data_ocd_brw_size (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1502 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_connect_data().
static int lustre_dissect_element_obd_connect_data_ocd_cksum_types (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1550 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_connect_data().
static int lustre_dissect_element_obd_connect_data_ocd_connect_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1470 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obd_connect_data().
static int lustre_dissect_element_obd_connect_data_ocd_grant (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1486 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_connect_data().
static int lustre_dissect_element_obd_connect_data_ocd_group (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1542 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_connect_data().
static int lustre_dissect_element_obd_connect_data_ocd_ibits_known (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1510 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obd_connect_data().
static int lustre_dissect_element_obd_connect_data_ocd_index (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1494 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_connect_data().
static int lustre_dissect_element_obd_connect_data_ocd_nllg (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1526 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_connect_data().
static int lustre_dissect_element_obd_connect_data_ocd_nllu (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1518 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_connect_data().
static int lustre_dissect_element_obd_connect_data_ocd_transno (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1534 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obd_connect_data().
static int lustre_dissect_element_obd_connect_data_ocd_version (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1478 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_connect_data().
static int lustre_dissect_element_obd_connect_data_padding1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1558 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obd_connect_data().
static int lustre_dissect_element_obd_connect_data_padding2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1566 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obd_connect_data().
static int lustre_dissect_element_obd_dqblk_dqb_bhardlimit (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2454 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obd_dqblk().
static int lustre_dissect_element_obd_dqblk_dqb_bsoftlimit (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2462 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obd_dqblk().
static int lustre_dissect_element_obd_dqblk_dqb_btime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2502 of file packet-lustre.c.
Referenced by lustre_dissect_struct_obd_dqblk().
static int lustre_dissect_element_obd_dqblk_dqb_curinodes (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2494 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obd_dqblk().
static int lustre_dissect_element_obd_dqblk_dqb_curspace (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2470 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obd_dqblk().
static int lustre_dissect_element_obd_dqblk_dqb_ihardlimit (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2478 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obd_dqblk().
static int lustre_dissect_element_obd_dqblk_dqb_isoftlimit (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2486 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obd_dqblk().
static int lustre_dissect_element_obd_dqblk_dqb_itime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2515 of file packet-lustre.c.
Referenced by lustre_dissect_struct_obd_dqblk().
static int lustre_dissect_element_obd_dqblk_dqb_valid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2528 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_dqblk().
static int lustre_dissect_element_obd_dqblk_padding (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2536 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_dqblk().
static int lustre_dissect_element_obd_dqinfo_dqi_bgrace (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2379 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obd_dqinfo().
static int lustre_dissect_element_obd_dqinfo_dqi_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2395 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_dqinfo().
static int lustre_dissect_element_obd_dqinfo_dqi_igrace (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2387 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obd_dqinfo().
static int lustre_dissect_element_obd_dqinfo_dqi_valid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2403 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_dqinfo().
static int lustre_dissect_element_obd_ioobj_ioo_bufcnt (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2125 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_ioobj().
static int lustre_dissect_element_obd_ioobj_ioo_id (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2101 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obd_ioobj().
static int lustre_dissect_element_obd_ioobj_ioo_max_brw (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2117 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_ioobj().
static int lustre_dissect_element_obd_ioobj_ioo_seq (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2109 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obd_ioobj().
static int lustre_dissect_element_obd_quotactl_qc_cmd (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2598 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_quotactl().
static int lustre_dissect_element_obd_quotactl_qc_dqblk (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2632 of file packet-lustre.c.
References lustre_dissect_struct_obd_dqblk().
Referenced by lustre_dissect_struct_obd_quotactl().
static int lustre_dissect_element_obd_quotactl_qc_dqinfo (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2639 of file packet-lustre.c.
References lustre_dissect_struct_obd_dqinfo().
Referenced by lustre_dissect_struct_obd_quotactl().
static int lustre_dissect_element_obd_quotactl_qc_id (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2614 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_quotactl().
static int lustre_dissect_element_obd_quotactl_qc_stat (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2622 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_quotactl().
static int lustre_dissect_element_obd_quotactl_qc_type (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2606 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_quotactl().
static int lustre_dissect_element_obd_statfs_os_bavail (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1884 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obd_statfs().
static int lustre_dissect_element_obd_statfs_os_bfree (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1876 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obd_statfs().
static int lustre_dissect_element_obd_statfs_os_blocks (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1868 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obd_statfs().
static int lustre_dissect_element_obd_statfs_os_bsize (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1928 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_statfs().
static int lustre_dissect_element_obd_statfs_os_ffree (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1900 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obd_statfs().
static int lustre_dissect_element_obd_statfs_os_files (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1892 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obd_statfs().
static int lustre_dissect_element_obd_statfs_os_fsid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1916 of file packet-lustre.c.
References lustre_dissect_element_obd_statfs_os_fsid_().
Referenced by lustre_dissect_struct_obd_statfs().
static int lustre_dissect_element_obd_statfs_os_fsid_ (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1908 of file packet-lustre.c.
References dissect_uint8.
Referenced by lustre_dissect_element_obd_statfs_os_fsid().
static int lustre_dissect_element_obd_statfs_os_maxbytes (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1944 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obd_statfs().
static int lustre_dissect_element_obd_statfs_os_namelen (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1936 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_statfs().
static int lustre_dissect_element_obd_statfs_os_spare1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1960 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_statfs().
static int lustre_dissect_element_obd_statfs_os_spare2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1968 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_statfs().
static int lustre_dissect_element_obd_statfs_os_spare3 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1976 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_statfs().
static int lustre_dissect_element_obd_statfs_os_spare4 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1984 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_statfs().
static int lustre_dissect_element_obd_statfs_os_spare5 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1992 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_statfs().
static int lustre_dissect_element_obd_statfs_os_spare6 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2000 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_statfs().
static int lustre_dissect_element_obd_statfs_os_spare7 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2008 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_statfs().
static int lustre_dissect_element_obd_statfs_os_spare8 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2016 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_statfs().
static int lustre_dissect_element_obd_statfs_os_spare9 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2024 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_statfs().
static int lustre_dissect_element_obd_statfs_os_state (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1952 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obd_statfs().
static int lustre_dissect_element_obd_statfs_os_type (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 1860 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obd_statfs().
static int lustre_dissect_element_obdo_o_atime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7497 of file packet-lustre.c.
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_obdo_o_blksize (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7538 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_obdo_o_blocks (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7522 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_obdo_o_ctime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7510 of file packet-lustre.c.
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_obdo_o_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7570 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_obdo_o_gid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7562 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_obdo_o_gid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7661 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_obdo_o_grant (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7530 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_obdo_o_handle (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7639 of file packet-lustre.c.
References lustre_dissect_struct_handle_cookie().
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_obdo_o_id (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7453 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_obdo_o_ioepoch (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7615 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_obdo_o_lcookie (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7646 of file packet-lustre.c.
References lustre_dissect_struct_llog_cookie().
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_obdo_o_misc (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7607 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_obdo_o_mode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7546 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_obdo_o_mtime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7485 of file packet-lustre.c.
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_obdo_o_nlink (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7591 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_obdo_o_padding_3 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7669 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_obdo_o_padding_4 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7677 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_obdo_o_padding_5 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7685 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_obdo_o_padding_6 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7693 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_obdo_o_parent_oid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7599 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_obdo_o_parent_seq (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7469 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_obdo_o_parent_ver (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7631 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_obdo_o_seq (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7461 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_obdo_o_size (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7477 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_obdo_o_stripe_idx (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7623 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_obdo_o_uid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7554 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_obdo_o_uid_h (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7653 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_obdo_o_valid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7445 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_obdo().
static int lustre_dissect_element_ost_body_oa (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7787 of file packet-lustre.c.
References lustre_dissect_struct_obdo().
Referenced by lustre_dissect_struct_ost_body().
static int lustre_dissect_element_ost_lvb_lvb_atime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2249 of file packet-lustre.c.
Referenced by lustre_dissect_struct_ost_lvb().
static int lustre_dissect_element_ost_lvb_lvb_blocks (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2275 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_ost_lvb().
static int lustre_dissect_element_ost_lvb_lvb_ctime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2262 of file packet-lustre.c.
Referenced by lustre_dissect_struct_ost_lvb().
static int lustre_dissect_element_ost_lvb_lvb_mtime (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2237 of file packet-lustre.c.
Referenced by lustre_dissect_struct_ost_lvb().
static int lustre_dissect_element_ost_lvb_lvb_size (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2229 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_ost_lvb().
static int lustre_dissect_element_ptlrpc_body_pb_conn_cnt (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9472 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_ptlrpc_body().
static int lustre_dissect_element_ptlrpc_body_pb_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9456 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_ptlrpc_body().
static int lustre_dissect_element_ptlrpc_body_pb_handle (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9384 of file packet-lustre.c.
References lustre_dissect_struct_handle_cookie().
Referenced by lustre_dissect_struct_ptlrpc_body().
static int lustre_dissect_element_ptlrpc_body_pb_jobid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_) [static]
Definition at line 9528 of file packet-lustre.c.
Referenced by lustre_dissect_struct_ptlrpc_body().
static int lustre_dissect_element_ptlrpc_body_pb_last_committed (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9440 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_ptlrpc_body().
static int lustre_dissect_element_ptlrpc_body_pb_last_seen (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9432 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_ptlrpc_body().
static int lustre_dissect_element_ptlrpc_body_pb_last_xid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9424 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_ptlrpc_body().
static int lustre_dissect_element_ptlrpc_body_pb_limit (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9496 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_ptlrpc_body().
static int lustre_dissect_element_ptlrpc_body_pb_op_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9464 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_ptlrpc_body().
static int lustre_dissect_element_ptlrpc_body_pb_opc (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9408 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_ptlrpc_body().
static int lustre_dissect_element_ptlrpc_body_pb_padding (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9520 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_ptlrpc_body().
static int lustre_dissect_element_ptlrpc_body_pb_pre_version (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9512 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_ptlrpc_body().
static int lustre_dissect_element_ptlrpc_body_pb_service_time (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9488 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_ptlrpc_body().
static int lustre_dissect_element_ptlrpc_body_pb_slv (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9504 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_ptlrpc_body().
static int lustre_dissect_element_ptlrpc_body_pb_status (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9416 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_ptlrpc_body().
static int lustre_dissect_element_ptlrpc_body_pb_timeout (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9480 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_ptlrpc_body().
static int lustre_dissect_element_ptlrpc_body_pb_transno (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9448 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_ptlrpc_body().
static int lustre_dissect_element_ptlrpc_body_pb_type (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9392 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_ptlrpc_body().
static int lustre_dissect_element_ptlrpc_body_pb_version (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 9400 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_ptlrpc_body().
static int lustre_dissect_element_qunit_data_old2_qd_count (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7920 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_qunit_data_old2().
static int lustre_dissect_element_qunit_data_old2_qd_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7912 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_qunit_data_old2().
static int lustre_dissect_element_qunit_data_old2_qd_id (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7904 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_qunit_data_old2().
static int lustre_dissect_element_qunit_data_old_qd_count (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7980 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_qunit_data_old().
static int lustre_dissect_element_qunit_data_old_qd_id (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7964 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_qunit_data_old().
static int lustre_dissect_element_qunit_data_old_qd_isblk (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7988 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_qunit_data_old().
static int lustre_dissect_element_qunit_data_old_qd_type (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7972 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_qunit_data_old().
static int lustre_dissect_element_qunit_data_padding (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7857 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_qunit_data().
static int lustre_dissect_element_qunit_data_qd_count (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7841 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_qunit_data().
static int lustre_dissect_element_qunit_data_qd_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7833 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_qunit_data().
static int lustre_dissect_element_qunit_data_qd_id (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7825 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_qunit_data().
static int lustre_dissect_element_qunit_data_qd_qunit (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 7849 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_qunit_data().
static int lustre_dissect_element_quota_adjust_qunit_padding1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2719 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_quota_adjust_qunit().
static int lustre_dissect_element_quota_adjust_qunit_qaq_bunit_sz (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2703 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_quota_adjust_qunit().
static int lustre_dissect_element_quota_adjust_qunit_qaq_flags (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2687 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_quota_adjust_qunit().
static int lustre_dissect_element_quota_adjust_qunit_qaq_id (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2695 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_struct_quota_adjust_qunit().
static int lustre_dissect_element_quota_adjust_qunit_qaq_iunit_sz (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 2711 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_dissect_struct_quota_adjust_qunit().
static int lustre_dissect_element_string (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_, guint32 buf_num) [static]
Definition at line 8241 of file packet-lustre.c.
References add_extra_padding(), display_info_fstr(), and LUSTRE_BUFFER_LEN.
Referenced by ldlm_opcode_process(), lustre_llog_opcode_process(), lustre_mds_opcode_process(), lustre_ost_opcode_process(), and reint_opcode_process().
int lustre_dissect_enum_ldlm_mode (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, int hf_index _U_)
Definition at line 5162 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_element_ldlm_lock_desc_l_granted_mode(), and lustre_dissect_element_ldlm_lock_desc_l_req_mode().
int lustre_dissect_enum_ldlm_type (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, int hf_index _U_)
Definition at line 5178 of file packet-lustre.c.
References dissect_uint32.
Referenced by lustre_dissect_element_ldlm_resource_desc_lr_type().
static int lustre_dissect_generic_connect (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 8382 of file packet-lustre.c.
References lustre_dissect_struct_handle_cookie(), lustre_dissect_struct_obd_connect_data(), and lustre_dissect_struct_obd_uuid().
Referenced by lustre_mds_opcode_process(), lustre_mgs_opcode_process(), and lustre_ost_opcode_process().
int lustre_dissect_struct_acl (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_, guint32 buf_num)
Definition at line 8198 of file packet-lustre.c.
References add_extra_padding(), and LUSTRE_BUFFER_LEN.
Referenced by lustre_ldlm_opcode_process(), and lustre_mds_opcode_process().
int lustre_dissect_struct_capa (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_, guint32 buf_num)
Definition at line 8393 of file packet-lustre.c.
References dissect_uint32, dissect_uint64, LUSTRE_BUFFER_LEN, lustre_dissect_element_capa_flags(), lustre_dissect_element_capa_opc(), lustre_dissect_struct_hmac(), and lustre_dissect_struct_lu_fid().
Referenced by ldlm_opcode_process(), lustre_ldlm_opcode_process(), lustre_mds_opcode_process(), lustre_ost_opcode_process(), and reint_opcode_process().
int lustre_dissect_struct_cfg_marker (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 6197 of file packet-lustre.c.
References lustre_dissect_element_cfg_marker_cm_canceltime(), lustre_dissect_element_cfg_marker_cm_comment(), lustre_dissect_element_cfg_marker_cm_createtime(), lustre_dissect_element_cfg_marker_cm_flags(), lustre_dissect_element_cfg_marker_cm_step(), lustre_dissect_element_cfg_marker_cm_tgtname(), lustre_dissect_element_cfg_marker_cm_vers(), and lustre_dissect_element_cfg_marker_padding().
int lustre_dissect_struct_fld_range (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_)
Definition at line 8061 of file packet-lustre.c.
References dissect_uint32, and dissect_uint64.
int lustre_dissect_struct_handle_cookie (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 1432 of file packet-lustre.c.
References lustre_dissect_element_handle_cookie().
Referenced by lustre_dissect_element_ldlm_reply_lock_handle(), lustre_dissect_element_ldlm_request_lock_handle_(), lustre_dissect_element_mdt_body_handle(), lustre_dissect_element_mdt_rec_create_cr_old_handle(), lustre_dissect_element_msg_v1_lm_handle(), lustre_dissect_element_obdo_o_handle(), lustre_dissect_element_ptlrpc_body_pb_handle(), lustre_dissect_generic_connect(), and lustre_dissect_struct_mdt_ioepoch().
int lustre_dissect_struct_hmac (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_, int max_length)
Definition at line 1397 of file packet-lustre.c.
Referenced by lustre_dissect_struct_capa().
int lustre_dissect_struct_ldlm_extent (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 5215 of file packet-lustre.c.
References lustre_dissect_element_ldlm_extent_end(), lustre_dissect_element_ldlm_extent_gid(), and lustre_dissect_element_ldlm_extent_start().
Referenced by lustre_dissect_element_ldlm_lock_desc_l_policy_data().
int lustre_dissect_struct_ldlm_flock (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 5327 of file packet-lustre.c.
References lustre_dissect_element_ldlm_flock_blocking_export(), lustre_dissect_element_ldlm_flock_blocking_pid(), lustre_dissect_element_ldlm_flock_end(), lustre_dissect_element_ldlm_flock_pid(), and lustre_dissect_element_ldlm_flock_start().
Referenced by lustre_dissect_element_ldlm_lock_desc_l_policy_data().
int lustre_dissect_struct_ldlm_inodebits (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 5255 of file packet-lustre.c.
References lustre_dissect_element_ldlm_inodebits_bits().
Referenced by lustre_dissect_element_ldlm_lock_desc_l_policy_data().
int lustre_dissect_struct_ldlm_intent (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 5422 of file packet-lustre.c.
References ldlm_opcode_process(), and lustre_dissect_element_ldlm_intent_opc().
Referenced by lustre_ldlm_opcode_process().
int lustre_dissect_struct_ldlm_lock_desc (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 5568 of file packet-lustre.c.
References display_info_fstr(), lustre_dissect_element_ldlm_lock_desc_l_granted_mode(), lustre_dissect_element_ldlm_lock_desc_l_policy_data(), lustre_dissect_element_ldlm_lock_desc_l_req_mode(), and lustre_dissect_element_ldlm_lock_desc_l_resource().
Referenced by lustre_dissect_element_ldlm_reply_lock_desc(), and lustre_dissect_element_ldlm_request_lock_desc().
int lustre_dissect_struct_ldlm_reply (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_, guint32 *ldlm_type _U_)
Definition at line 5729 of file packet-lustre.c.
References lustre_dissect_element_ldlm_reply_lock_desc(), lustre_dissect_element_ldlm_reply_lock_handle(), lustre_dissect_element_ldlm_reply_lock_padding(), lustre_dissect_element_ldlm_reply_lock_policy_res1(), and lustre_dissect_element_ldlm_reply_lock_policy_res2().
Referenced by lustre_ldlm_opcode_process().
int lustre_dissect_struct_ldlm_request (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 5654 of file packet-lustre.c.
References lustre_dissect_element_ldlm_request_lock_count(), lustre_dissect_element_ldlm_request_lock_desc(), and lustre_dissect_element_ldlm_request_lock_handle().
Referenced by lustre_ldlm_opcode_process(), lustre_ost_opcode_process(), and reint_opcode_process().
int lustre_dissect_struct_ldlm_res_id (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 5125 of file packet-lustre.c.
References lustre_dissect_element_ldlm_res_id_name().
Referenced by lustre_dissect_element_ldlm_resource_desc_lr_name().
int lustre_dissect_struct_ldlm_resource_desc (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 5472 of file packet-lustre.c.
References lustre_dissect_element_ldlm_resource_desc_lr_name(), lustre_dissect_element_ldlm_resource_desc_lr_padding(), and lustre_dissect_element_ldlm_resource_desc_lr_type().
Referenced by lustre_dissect_element_ldlm_lock_desc_l_resource().
int lustre_dissect_struct_llog_catid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 6337 of file packet-lustre.c.
References lustre_dissect_element_llog_catid_lci_logid(), lustre_dissect_element_llog_catid_lci_padding1(), lustre_dissect_element_llog_catid_lci_padding2(), and lustre_dissect_element_llog_catid_lci_padding3().
int lustre_dissect_struct_llog_cookie (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 7215 of file packet-lustre.c.
References lustre_dissect_element_llog_cookie_lgc_index(), lustre_dissect_element_llog_cookie_lgc_lgl(), lustre_dissect_element_llog_cookie_lgc_padding(), and lustre_dissect_element_llog_cookie_lgc_subsys().
Referenced by lustre_dissect_element_obdo_o_lcookie(), lustre_mds_opcode_process(), and reint_opcode_process().
int lustre_dissect_struct_llog_gen (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 6891 of file packet-lustre.c.
References lustre_dissect_element_llog_gen_conn_cnt(), and lustre_dissect_element_llog_gen_mnt_cnt().
int lustre_dissect_struct_llog_gen_rec (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 6950 of file packet-lustre.c.
References lustre_dissect_element_llog_gen_rec_lgr_gen(), lustre_dissect_element_llog_gen_rec_lgr_hdr(), and lustre_dissect_element_llog_gen_rec_lgr_tail().
int lustre_dissect_struct_llog_log_hdr (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 7129 of file packet-lustre.c.
References lustre_dissect_element_llog_log_hdr_llh_bitmap(), lustre_dissect_element_llog_log_hdr_llh_bitmap_offset(), lustre_dissect_element_llog_log_hdr_llh_cat_idx(), lustre_dissect_element_llog_log_hdr_llh_count(), lustre_dissect_element_llog_log_hdr_llh_flags(), lustre_dissect_element_llog_log_hdr_llh_hdr(), lustre_dissect_element_llog_log_hdr_llh_reserved(), lustre_dissect_element_llog_log_hdr_llh_size(), lustre_dissect_element_llog_log_hdr_llh_tail(), lustre_dissect_element_llog_log_hdr_llh_tgtuuid(), and lustre_dissect_element_llog_log_hdr_llh_timestamp().
Referenced by lustre_llog_opcode_process().
int lustre_dissect_struct_llog_logid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 6267 of file packet-lustre.c.
References lustre_dissect_element_llog_logid_lgl_ogen(), lustre_dissect_element_llog_logid_lgl_oid(), and lustre_dissect_element_llog_logid_lgl_oseq().
Referenced by lustre_dissect_element_llog_cookie_lgc_lgl(), lustre_dissect_element_llog_logid_rec_lid_id(), and lustre_dissect_element_llogd_body_lgd_logid().
int lustre_dissect_struct_llog_logid_rec (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 6558 of file packet-lustre.c.
References lustre_dissect_element_llog_logid_rec_lid_hdr(), lustre_dissect_element_llog_logid_rec_lid_id(), lustre_dissect_element_llog_logid_rec_lid_tail(), lustre_dissect_element_llog_logid_rec_padding1(), lustre_dissect_element_llog_logid_rec_padding2(), lustre_dissect_element_llog_logid_rec_padding3(), lustre_dissect_element_llog_logid_rec_padding4(), and lustre_dissect_element_llog_logid_rec_padding5().
int lustre_dissect_struct_llog_rec_hdr (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 6406 of file packet-lustre.c.
References lustre_dissect_element_llog_rec_hdr_lrh_index(), lustre_dissect_element_llog_rec_hdr_lrh_len(), lustre_dissect_element_llog_rec_hdr_lrh_type(), and lustre_dissect_element_llog_rec_hdr_padding().
Referenced by lustre_dissect_element_llog_log_hdr_llh_hdr(), and lustre_dissect_element_llog_logid_rec_lid_hdr().
int lustre_dissect_struct_llog_rec_tail (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 6457 of file packet-lustre.c.
References lustre_dissect_element_llog_rec_tail_lrt_index(), and lustre_dissect_element_llog_rec_tail_lrt_len().
Referenced by lustre_dissect_element_llog_log_hdr_llh_tail(), and lustre_dissect_element_llog_logid_rec_lid_tail().
int lustre_dissect_struct_llog_setattr_rec (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 6747 of file packet-lustre.c.
References lustre_dissect_element_llog_setattr_rec_lsr_gid(), lustre_dissect_element_llog_setattr_rec_lsr_hdr(), lustre_dissect_element_llog_setattr_rec_lsr_ogen(), lustre_dissect_element_llog_setattr_rec_lsr_oid(), lustre_dissect_element_llog_setattr_rec_lsr_tail(), lustre_dissect_element_llog_setattr_rec_lsr_uid(), and lustre_dissect_element_llog_setattr_rec_padding().
int lustre_dissect_struct_llog_size_change_rec (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 6835 of file packet-lustre.c.
References lustre_dissect_element_llog_size_change_rec_lsc_fid(), lustre_dissect_element_llog_size_change_rec_lsc_hdr(), lustre_dissect_element_llog_size_change_rec_lsc_io_epoch(), lustre_dissect_element_llog_size_change_rec_lsc_tail(), and lustre_dissect_element_llog_size_change_rec_padding().
int lustre_dissect_struct_llog_unlink_rec (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 6647 of file packet-lustre.c.
References lustre_dissect_element_llog_unlink_rec_lur_hdr(), lustre_dissect_element_llog_unlink_rec_lur_ogen(), lustre_dissect_element_llog_unlink_rec_lur_oid(), lustre_dissect_element_llog_unlink_rec_lur_tail(), and lustre_dissect_element_llog_unlink_rec_padding().
int lustre_dissect_struct_llogd_body (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 7315 of file packet-lustre.c.
References lustre_dissect_element_llogd_body_lgd_ctxt_idx(), lustre_dissect_element_llogd_body_lgd_cur_offset(), lustre_dissect_element_llogd_body_lgd_index(), lustre_dissect_element_llogd_body_lgd_len(), lustre_dissect_element_llogd_body_lgd_llh_flags(), lustre_dissect_element_llogd_body_lgd_logid(), and lustre_dissect_element_llogd_body_lgd_saved_index().
Referenced by lustre_llog_opcode_process().
int lustre_dissect_struct_llogd_conn_body (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 7383 of file packet-lustre.c.
References lustre_dissect_element_llogd_conn_body_lgdc_ctxt_idx(), lustre_dissect_element_llogd_conn_body_lgdc_gen(), and lustre_dissect_element_llogd_conn_body_lgdc_logid().
int lustre_dissect_struct_lov_desc (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 5041 of file packet-lustre.c.
References lustre_dissect_element_lov_desc_ld_active_tgt_count(), lustre_dissect_element_lov_desc_ld_default_stripe_count(), lustre_dissect_element_lov_desc_ld_default_stripe_offset(), lustre_dissect_element_lov_desc_ld_default_stripe_size(), lustre_dissect_element_lov_desc_ld_padding_0(), lustre_dissect_element_lov_desc_ld_padding_1(), lustre_dissect_element_lov_desc_ld_padding_2(), lustre_dissect_element_lov_desc_ld_pattern(), lustre_dissect_element_lov_desc_ld_qos_maxage(), lustre_dissect_element_lov_desc_ld_tgt_count(), and lustre_dissect_element_lov_desc_ld_uuid().
int lustre_dissect_struct_lov_mds_md (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_, int buff_num _U_)
Definition at line 1810 of file packet-lustre.c.
References LOV_MAGIC_V1, LUSTRE_BUFFER_LEN, lustre_dissect_element_data(), and lustre_dissect_struct_lov_mds_md_v1().
Referenced by lustre_ldlm_opcode_process(), and lustre_mds_opcode_process().
int lustre_dissect_struct_lov_mds_md_v1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 1772 of file packet-lustre.c.
References lustre_dissect_element_lov_mds_md_v1_lmm_magic(), lustre_dissect_element_lov_mds_md_v1_lmm_object_id(), lustre_dissect_element_lov_mds_md_v1_lmm_object_seq(), lustre_dissect_element_lov_mds_md_v1_lmm_objects(), lustre_dissect_element_lov_mds_md_v1_lmm_pattern(), lustre_dissect_element_lov_mds_md_v1_lmm_stripe_count(), and lustre_dissect_element_lov_mds_md_v1_lmm_stripe_size().
Referenced by lustre_dissect_struct_lov_mds_md().
int lustre_dissect_struct_lov_ost_data_v1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 1662 of file packet-lustre.c.
References lustre_dissect_element_lov_ost_data_v1_l_object_id(), lustre_dissect_element_lov_ost_data_v1_l_object_seq(), lustre_dissect_element_lov_ost_data_v1_l_ost_gen(), and lustre_dissect_element_lov_ost_data_v1_l_ost_idx().
Referenced by lustre_dissect_element_lov_mds_md_v1_lmm_objects_().
int lustre_dissect_struct_lu_fid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 2346 of file packet-lustre.c.
References lustre_dissect_element_ll_fid_f_type(), lustre_dissect_element_ll_fid_generation(), and lustre_dissect_element_ll_fid_id().
Referenced by lustre_dissect_element_mdt_body_fid1(), lustre_dissect_element_mdt_body_fid2(), lustre_dissect_element_mdt_rec_create_cr_fid1(), lustre_dissect_element_mdt_rec_create_cr_fid2(), lustre_dissect_element_mdt_rec_link_lk_fid1(), lustre_dissect_element_mdt_rec_link_lk_fid2(), lustre_dissect_element_mdt_rec_rename_rn_fid1(), lustre_dissect_element_mdt_rec_rename_rn_fid2(), lustre_dissect_element_mdt_rec_setattr_sa_fid(), lustre_dissect_element_mdt_rec_setxattr_sx_fid(), lustre_dissect_element_mdt_rec_unlink_ul_fid1(), lustre_dissect_element_mdt_rec_unlink_ul_fid2(), and lustre_dissect_struct_capa().
int lustre_dissect_struct_lu_ladvise (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_, guint32 buf_num)
Definition at line 8437 of file packet-lustre.c.
References dissect_uint64, and LUSTRE_BUFFER_LEN.
Referenced by lustre_ost_opcode_process().
int lustre_dissect_struct_mdt_body (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 3082 of file packet-lustre.c.
References lustre_dissect_element_mdt_body_aclsize(), lustre_dissect_element_mdt_body_atime(), lustre_dissect_element_mdt_body_blocks(), lustre_dissect_element_mdt_body_capability(), lustre_dissect_element_mdt_body_ctime(), lustre_dissect_element_mdt_body_eadatasize(), lustre_dissect_element_mdt_body_fid1(), lustre_dissect_element_mdt_body_fid2(), lustre_dissect_element_mdt_body_flags(), lustre_dissect_element_mdt_body_fsgid(), lustre_dissect_element_mdt_body_fsuid(), lustre_dissect_element_mdt_body_generation(), lustre_dissect_element_mdt_body_gid(), lustre_dissect_element_mdt_body_gid_h(), lustre_dissect_element_mdt_body_handle(), lustre_dissect_element_mdt_body_ino(), lustre_dissect_element_mdt_body_ioepoch(), lustre_dissect_element_mdt_body_max_cookiesize(), lustre_dissect_element_mdt_body_max_mdsize(), lustre_dissect_element_mdt_body_mode(), lustre_dissect_element_mdt_body_mtime(), lustre_dissect_element_mdt_body_nlink(), lustre_dissect_element_mdt_body_padding_10(), lustre_dissect_element_mdt_body_padding_5(), lustre_dissect_element_mdt_body_padding_6(), lustre_dissect_element_mdt_body_padding_7(), lustre_dissect_element_mdt_body_padding_8(), lustre_dissect_element_mdt_body_padding_9(), lustre_dissect_element_mdt_body_rdev(), lustre_dissect_element_mdt_body_size(), lustre_dissect_element_mdt_body_suppgid(), lustre_dissect_element_mdt_body_uid(), lustre_dissect_element_mdt_body_uid_h(), and lustre_dissect_element_mdt_body_valid().
Referenced by ldlm_opcode_process(), lustre_ldlm_opcode_process(), and lustre_mds_opcode_process().
int lustre_dissect_struct_mdt_ioepoch (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 8086 of file packet-lustre.c.
References dissect_uint32, dissect_uint64, and lustre_dissect_struct_handle_cookie().
Referenced by lustre_mds_opcode_process(), and reint_opcode_process().
int lustre_dissect_struct_mdt_rec_create (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 3707 of file packet-lustre.c.
References display_info_fstr(), lustre_dissect_element_mdt_rec_create_cr_bias(), lustre_dissect_element_mdt_rec_create_cr_cap(), lustre_dissect_element_mdt_rec_create_cr_fid1(), lustre_dissect_element_mdt_rec_create_cr_fid2(), lustre_dissect_element_mdt_rec_create_cr_flags_h(), lustre_dissect_element_mdt_rec_create_cr_flags_l(), lustre_dissect_element_mdt_rec_create_cr_fsgid(), lustre_dissect_element_mdt_rec_create_cr_fsgid_h(), lustre_dissect_element_mdt_rec_create_cr_fsuid(), lustre_dissect_element_mdt_rec_create_cr_fsuid_h(), lustre_dissect_element_mdt_rec_create_cr_ioepoch(), lustre_dissect_element_mdt_rec_create_cr_mode(), lustre_dissect_element_mdt_rec_create_cr_old_handle(), lustre_dissect_element_mdt_rec_create_cr_opcode(), lustre_dissect_element_mdt_rec_create_cr_padding_1(), lustre_dissect_element_mdt_rec_create_cr_padding_4(), lustre_dissect_element_mdt_rec_create_cr_rdev(), lustre_dissect_element_mdt_rec_create_cr_suppgid1(), lustre_dissect_element_mdt_rec_create_cr_suppgid1_h(), lustre_dissect_element_mdt_rec_create_cr_suppgid2(), lustre_dissect_element_mdt_rec_create_cr_suppgid2_h(), lustre_dissect_element_mdt_rec_create_cr_time(), and lustre_dissect_element_mdt_rec_create_cr_umask().
Referenced by ldlm_opcode_process(), and reint_opcode_process().
int lustre_dissect_struct_mdt_rec_link (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 3993 of file packet-lustre.c.
References display_info_fstr(), lustre_dissect_element_mdt_rec_link_lk_bias(), lustre_dissect_element_mdt_rec_link_lk_cap(), lustre_dissect_element_mdt_rec_link_lk_fid1(), lustre_dissect_element_mdt_rec_link_lk_fid2(), lustre_dissect_element_mdt_rec_link_lk_fsgid(), lustre_dissect_element_mdt_rec_link_lk_fsgid_h(), lustre_dissect_element_mdt_rec_link_lk_fsuid(), lustre_dissect_element_mdt_rec_link_lk_fsuid_h(), lustre_dissect_element_mdt_rec_link_lk_opcode(), lustre_dissect_element_mdt_rec_link_lk_padding_1(), lustre_dissect_element_mdt_rec_link_lk_padding_2(), lustre_dissect_element_mdt_rec_link_lk_padding_3(), lustre_dissect_element_mdt_rec_link_lk_padding_4(), lustre_dissect_element_mdt_rec_link_lk_padding_5(), lustre_dissect_element_mdt_rec_link_lk_padding_6(), lustre_dissect_element_mdt_rec_link_lk_padding_7(), lustre_dissect_element_mdt_rec_link_lk_padding_8(), lustre_dissect_element_mdt_rec_link_lk_padding_9(), lustre_dissect_element_mdt_rec_link_lk_suppgid1(), lustre_dissect_element_mdt_rec_link_lk_suppgid1_h(), lustre_dissect_element_mdt_rec_link_lk_suppgid2(), lustre_dissect_element_mdt_rec_link_lk_suppgid2_h(), and lustre_dissect_element_mdt_rec_link_lk_time().
Referenced by reint_opcode_process().
int lustre_dissect_struct_mdt_rec_rename (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 4554 of file packet-lustre.c.
References display_info_fstr(), lustre_dissect_element_mdt_rec_rename_rn_bias(), lustre_dissect_element_mdt_rec_rename_rn_cap(), lustre_dissect_element_mdt_rec_rename_rn_fid1(), lustre_dissect_element_mdt_rec_rename_rn_fid2(), lustre_dissect_element_mdt_rec_rename_rn_fsgid(), lustre_dissect_element_mdt_rec_rename_rn_fsgid_h(), lustre_dissect_element_mdt_rec_rename_rn_fsuid(), lustre_dissect_element_mdt_rec_rename_rn_fsuid_h(), lustre_dissect_element_mdt_rec_rename_rn_mode(), lustre_dissect_element_mdt_rec_rename_rn_opcode(), lustre_dissect_element_mdt_rec_rename_rn_padding_1(), lustre_dissect_element_mdt_rec_rename_rn_padding_2(), lustre_dissect_element_mdt_rec_rename_rn_padding_3(), lustre_dissect_element_mdt_rec_rename_rn_padding_4(), lustre_dissect_element_mdt_rec_rename_rn_padding_5(), lustre_dissect_element_mdt_rec_rename_rn_padding_6(), lustre_dissect_element_mdt_rec_rename_rn_padding_7(), lustre_dissect_element_mdt_rec_rename_rn_padding_8(), lustre_dissect_element_mdt_rec_rename_rn_suppgid1(), lustre_dissect_element_mdt_rec_rename_rn_suppgid1_h(), lustre_dissect_element_mdt_rec_rename_rn_suppgid2(), lustre_dissect_element_mdt_rec_rename_rn_suppgid2_h(), and lustre_dissect_element_mdt_rec_rename_rn_time().
Referenced by reint_opcode_process().
int lustre_dissect_struct_mdt_rec_setattr (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 3417 of file packet-lustre.c.
References display_info_fstr(), lustre_dissect_element_mdt_rec_setattr_sa_atime(), lustre_dissect_element_mdt_rec_setattr_sa_attr_flags(), lustre_dissect_element_mdt_rec_setattr_sa_blocks(), lustre_dissect_element_mdt_rec_setattr_sa_cap(), lustre_dissect_element_mdt_rec_setattr_sa_ctime(), lustre_dissect_element_mdt_rec_setattr_sa_fid(), lustre_dissect_element_mdt_rec_setattr_sa_fsgid(), lustre_dissect_element_mdt_rec_setattr_sa_fsgid_h(), lustre_dissect_element_mdt_rec_setattr_sa_fsuid(), lustre_dissect_element_mdt_rec_setattr_sa_fsuid_h(), lustre_dissect_element_mdt_rec_setattr_sa_gid(), lustre_dissect_element_mdt_rec_setattr_sa_mode(), lustre_dissect_element_mdt_rec_setattr_sa_mtime(), lustre_dissect_element_mdt_rec_setattr_sa_opcode(), lustre_dissect_element_mdt_rec_setattr_sa_padding_1(), lustre_dissect_element_mdt_rec_setattr_sa_padding_1_h(), lustre_dissect_element_mdt_rec_setattr_sa_padding_2(), lustre_dissect_element_mdt_rec_setattr_sa_padding_3(), lustre_dissect_element_mdt_rec_setattr_sa_padding_4(), lustre_dissect_element_mdt_rec_setattr_sa_padding_5(), lustre_dissect_element_mdt_rec_setattr_sa_size(), lustre_dissect_element_mdt_rec_setattr_sa_suppgid(), lustre_dissect_element_mdt_rec_setattr_sa_suppgid_h(), lustre_dissect_element_mdt_rec_setattr_sa_uid(), and lustre_dissect_element_mdt_rec_setattr_sa_valid().
Referenced by lustre_mds_opcode_process(), and reint_opcode_process().
int lustre_dissect_struct_mdt_rec_setxattr (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 4861 of file packet-lustre.c.
References display_info_fstr(), lustre_dissect_element_mdt_rec_setxattr_sx_cap(), lustre_dissect_element_mdt_rec_setxattr_sx_fid(), lustre_dissect_element_mdt_rec_setxattr_sx_flags(), lustre_dissect_element_mdt_rec_setxattr_sx_fsgid(), lustre_dissect_element_mdt_rec_setxattr_sx_fsgid_h(), lustre_dissect_element_mdt_rec_setxattr_sx_fsuid(), lustre_dissect_element_mdt_rec_setxattr_sx_fsuid_h(), lustre_dissect_element_mdt_rec_setxattr_sx_opcode(), lustre_dissect_element_mdt_rec_setxattr_sx_padding_1(), lustre_dissect_element_mdt_rec_setxattr_sx_padding_10(), lustre_dissect_element_mdt_rec_setxattr_sx_padding_11(), lustre_dissect_element_mdt_rec_setxattr_sx_padding_2(), lustre_dissect_element_mdt_rec_setxattr_sx_padding_3(), lustre_dissect_element_mdt_rec_setxattr_sx_padding_5(), lustre_dissect_element_mdt_rec_setxattr_sx_padding_6(), lustre_dissect_element_mdt_rec_setxattr_sx_padding_7(), lustre_dissect_element_mdt_rec_setxattr_sx_padding_8(), lustre_dissect_element_mdt_rec_setxattr_sx_padding_9(), lustre_dissect_element_mdt_rec_setxattr_sx_size(), lustre_dissect_element_mdt_rec_setxattr_sx_suppgid1(), lustre_dissect_element_mdt_rec_setxattr_sx_suppgid1_h(), lustre_dissect_element_mdt_rec_setxattr_sx_suppgid2(), lustre_dissect_element_mdt_rec_setxattr_sx_suppgid2_h(), lustre_dissect_element_mdt_rec_setxattr_sx_time(), and lustre_dissect_element_mdt_rec_setxattr_sx_valid().
Referenced by reint_opcode_process().
int lustre_dissect_struct_mdt_rec_unlink (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 4278 of file packet-lustre.c.
References display_info_fstr(), lustre_dissect_element_mdt_rec_unlink_ul_bias(), lustre_dissect_element_mdt_rec_unlink_ul_cap(), lustre_dissect_element_mdt_rec_unlink_ul_fid1(), lustre_dissect_element_mdt_rec_unlink_ul_fid2(), lustre_dissect_element_mdt_rec_unlink_ul_fsgid(), lustre_dissect_element_mdt_rec_unlink_ul_fsgid_h(), lustre_dissect_element_mdt_rec_unlink_ul_fsuid(), lustre_dissect_element_mdt_rec_unlink_ul_fsuid_h(), lustre_dissect_element_mdt_rec_unlink_ul_mode(), lustre_dissect_element_mdt_rec_unlink_ul_opcode(), lustre_dissect_element_mdt_rec_unlink_ul_padding_2(), lustre_dissect_element_mdt_rec_unlink_ul_padding_3(), lustre_dissect_element_mdt_rec_unlink_ul_padding_4(), lustre_dissect_element_mdt_rec_unlink_ul_padding_5(), lustre_dissect_element_mdt_rec_unlink_ul_padding_6(), lustre_dissect_element_mdt_rec_unlink_ul_padding_7(), lustre_dissect_element_mdt_rec_unlink_ul_padding_8(), lustre_dissect_element_mdt_rec_unlink_ul_padding_9(), lustre_dissect_element_mdt_rec_unlink_ul_suppgid1(), lustre_dissect_element_mdt_rec_unlink_ul_suppgid1_h(), lustre_dissect_element_mdt_rec_unlink_ul_suppgid2(), lustre_dissect_element_mdt_rec_unlink_ul_suppgid2_h(), and lustre_dissect_element_mdt_rec_unlink_ul_time().
Referenced by ldlm_opcode_process(), and reint_opcode_process().
int lustre_dissect_struct_mgs_config_body (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 5835 of file packet-lustre.c.
References dissect_uint16, dissect_uint32, dissect_uint64, dissect_uint8, and lustre_dissect_element_mgs_config_body_name().
Referenced by lustre_mgs_opcode_process().
int lustre_dissect_struct_mgs_config_res (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 5868 of file packet-lustre.c.
References dissect_uint64.
Referenced by lustre_mgs_opcode_process().
int lustre_dissect_struct_mgs_send_param (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 5791 of file packet-lustre.c.
References lustre_dissect_element_mgs_send_param_mgs_param().
Referenced by lustre_mgs_opcode_process().
int lustre_dissect_struct_mgs_target_info (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 6053 of file packet-lustre.c.
References lustre_dissect_element_mgs_target_info_mti_config_ver(), lustre_dissect_element_mgs_target_info_mti_flags(), lustre_dissect_element_mgs_target_info_mti_fsname(), lustre_dissect_element_mgs_target_info_mti_lustre_ver(), lustre_dissect_element_mgs_target_info_mti_nid_count(), lustre_dissect_element_mgs_target_info_mti_nids(), lustre_dissect_element_mgs_target_info_mti_params(), lustre_dissect_element_mgs_target_info_mti_stripe_index(), lustre_dissect_element_mgs_target_info_mti_svname(), lustre_dissect_element_mgs_target_info_mti_uuid(), and lustre_dissect_element_mgs_target_info_padding().
Referenced by lustre_mgs_opcode_process().
int lustre_dissect_struct_msg_v1 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 9307 of file packet-lustre.c.
References display_info_fstr(), display_info_str(), lustre_dissect_element_msg_v1_lm_bufcount(), lustre_dissect_element_msg_v1_lm_buflens(), lustre_dissect_element_msg_v1_lm_conn_cnt(), lustre_dissect_element_msg_v1_lm_flags(), lustre_dissect_element_msg_v1_lm_handle(), lustre_dissect_element_msg_v1_lm_last_committed(), lustre_dissect_element_msg_v1_lm_last_xid(), lustre_dissect_element_msg_v1_lm_magic(), lustre_dissect_element_msg_v1_lm_opc(), lustre_dissect_element_msg_v1_lm_status(), lustre_dissect_element_msg_v1_lm_transno(), lustre_dissect_element_msg_v1_lm_type(), lustre_dissect_element_msg_v1_lm_version(), and lustre_opcode_process().
Referenced by dissect_lustre().
int lustre_dissect_struct_msg_v2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 9714 of file packet-lustre.c.
References dissect_uint32, lustre_dissect_element_msg_v2_lm_bufcount(), lustre_dissect_element_msg_v2_lm_buflens_(), lustre_dissect_element_msg_v2_lm_cksum(), lustre_dissect_element_msg_v2_lm_flags(), lustre_dissect_element_msg_v2_lm_magic(), lustre_dissect_element_msg_v2_lm_padding_2(), lustre_dissect_element_msg_v2_lm_padding_3(), lustre_dissect_element_msg_v2_lm_repsize(), lustre_dissect_element_msg_v2_lm_secflvr(), and lustre_dissect_struct_ptlrpc_body().
Referenced by dissect_lustre().
int lustre_dissect_struct_niobuf_remote (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 2193 of file packet-lustre.c.
References lustre_dissect_element_niobuf_remote_flags(), lustre_dissect_element_niobuf_remote_len(), and lustre_dissect_element_niobuf_remote_offset().
Referenced by lustre_ost_opcode_process().
static int lustre_dissect_struct_obd_connect_data (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_) [static]
Definition at line 1574 of file packet-lustre.c.
References lustre_dissect_element_obd_connect_data_ocd_brw_size(), lustre_dissect_element_obd_connect_data_ocd_cksum_types(), lustre_dissect_element_obd_connect_data_ocd_connect_flags(), lustre_dissect_element_obd_connect_data_ocd_grant(), lustre_dissect_element_obd_connect_data_ocd_group(), lustre_dissect_element_obd_connect_data_ocd_ibits_known(), lustre_dissect_element_obd_connect_data_ocd_index(), lustre_dissect_element_obd_connect_data_ocd_nllg(), lustre_dissect_element_obd_connect_data_ocd_nllu(), lustre_dissect_element_obd_connect_data_ocd_transno(), lustre_dissect_element_obd_connect_data_ocd_version(), lustre_dissect_element_obd_connect_data_padding1(), and lustre_dissect_element_obd_connect_data_padding2().
Referenced by lustre_dissect_generic_connect(), lustre_mds_opcode_process(), lustre_mgs_opcode_process(), and lustre_ost_opcode_process().
int lustre_dissect_struct_obd_dqblk (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 2544 of file packet-lustre.c.
References lustre_dissect_element_obd_dqblk_dqb_bhardlimit(), lustre_dissect_element_obd_dqblk_dqb_bsoftlimit(), lustre_dissect_element_obd_dqblk_dqb_btime(), lustre_dissect_element_obd_dqblk_dqb_curinodes(), lustre_dissect_element_obd_dqblk_dqb_curspace(), lustre_dissect_element_obd_dqblk_dqb_ihardlimit(), lustre_dissect_element_obd_dqblk_dqb_isoftlimit(), lustre_dissect_element_obd_dqblk_dqb_itime(), lustre_dissect_element_obd_dqblk_dqb_valid(), and lustre_dissect_element_obd_dqblk_padding().
Referenced by lustre_dissect_element_obd_quotactl_qc_dqblk().
int lustre_dissect_struct_obd_dqinfo (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 2411 of file packet-lustre.c.
References lustre_dissect_element_obd_dqinfo_dqi_bgrace(), lustre_dissect_element_obd_dqinfo_dqi_flags(), lustre_dissect_element_obd_dqinfo_dqi_igrace(), and lustre_dissect_element_obd_dqinfo_dqi_valid().
Referenced by lustre_dissect_element_obd_quotactl_qc_dqinfo().
int lustre_dissect_struct_obd_ioobj (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 2133 of file packet-lustre.c.
References lustre_dissect_element_obd_ioobj_ioo_bufcnt(), lustre_dissect_element_obd_ioobj_ioo_id(), lustre_dissect_element_obd_ioobj_ioo_max_brw(), and lustre_dissect_element_obd_ioobj_ioo_seq().
Referenced by lustre_ost_opcode_process().
int lustre_dissect_struct_obd_quotactl (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 2646 of file packet-lustre.c.
References lustre_dissect_element_obd_quotactl_qc_cmd(), lustre_dissect_element_obd_quotactl_qc_dqblk(), lustre_dissect_element_obd_quotactl_qc_dqinfo(), lustre_dissect_element_obd_quotactl_qc_id(), lustre_dissect_element_obd_quotactl_qc_stat(), and lustre_dissect_element_obd_quotactl_qc_type().
Referenced by lustre_mds_opcode_process(), lustre_odb_opcode_process(), lustre_ost_opcode_process(), and reint_opcode_process().
int lustre_dissect_struct_obd_statfs (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 2032 of file packet-lustre.c.
References lustre_dissect_element_obd_statfs_os_bavail(), lustre_dissect_element_obd_statfs_os_bfree(), lustre_dissect_element_obd_statfs_os_blocks(), lustre_dissect_element_obd_statfs_os_bsize(), lustre_dissect_element_obd_statfs_os_ffree(), lustre_dissect_element_obd_statfs_os_files(), lustre_dissect_element_obd_statfs_os_fsid(), lustre_dissect_element_obd_statfs_os_maxbytes(), lustre_dissect_element_obd_statfs_os_namelen(), lustre_dissect_element_obd_statfs_os_spare1(), lustre_dissect_element_obd_statfs_os_spare2(), lustre_dissect_element_obd_statfs_os_spare3(), lustre_dissect_element_obd_statfs_os_spare4(), lustre_dissect_element_obd_statfs_os_spare5(), lustre_dissect_element_obd_statfs_os_spare6(), lustre_dissect_element_obd_statfs_os_spare7(), lustre_dissect_element_obd_statfs_os_spare8(), lustre_dissect_element_obd_statfs_os_spare9(), lustre_dissect_element_obd_statfs_os_state(), and lustre_dissect_element_obd_statfs_os_type().
Referenced by lustre_mds_opcode_process(), and lustre_ost_opcode_process().
static int lustre_dissect_struct_obd_uuid (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_) [static]
Definition at line 5089 of file packet-lustre.c.
Referenced by lustre_dissect_element_llog_log_hdr_llh_tgtuuid(), and lustre_dissect_generic_connect().
int lustre_dissect_struct_obdo (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 7701 of file packet-lustre.c.
References lustre_dissect_element_obdo_o_atime(), lustre_dissect_element_obdo_o_blksize(), lustre_dissect_element_obdo_o_blocks(), lustre_dissect_element_obdo_o_ctime(), lustre_dissect_element_obdo_o_flags(), lustre_dissect_element_obdo_o_gid(), lustre_dissect_element_obdo_o_gid_h(), lustre_dissect_element_obdo_o_grant(), lustre_dissect_element_obdo_o_handle(), lustre_dissect_element_obdo_o_id(), lustre_dissect_element_obdo_o_ioepoch(), lustre_dissect_element_obdo_o_lcookie(), lustre_dissect_element_obdo_o_misc(), lustre_dissect_element_obdo_o_mode(), lustre_dissect_element_obdo_o_mtime(), lustre_dissect_element_obdo_o_nlink(), lustre_dissect_element_obdo_o_padding_3(), lustre_dissect_element_obdo_o_padding_4(), lustre_dissect_element_obdo_o_padding_5(), lustre_dissect_element_obdo_o_padding_6(), lustre_dissect_element_obdo_o_parent_oid(), lustre_dissect_element_obdo_o_parent_seq(), lustre_dissect_element_obdo_o_parent_ver(), lustre_dissect_element_obdo_o_seq(), lustre_dissect_element_obdo_o_size(), lustre_dissect_element_obdo_o_stripe_idx(), lustre_dissect_element_obdo_o_uid(), lustre_dissect_element_obdo_o_uid_h(), and lustre_dissect_element_obdo_o_valid().
Referenced by lustre_dissect_element_ost_body_oa().
int lustre_dissect_struct_ost_body (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 7794 of file packet-lustre.c.
References lustre_dissect_element_ost_body_oa().
Referenced by lustre_ost_opcode_process().
int lustre_dissect_struct_ost_lvb (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 2283 of file packet-lustre.c.
References lustre_dissect_element_ost_lvb_lvb_atime(), lustre_dissect_element_ost_lvb_lvb_blocks(), lustre_dissect_element_ost_lvb_lvb_ctime(), lustre_dissect_element_ost_lvb_lvb_mtime(), and lustre_dissect_element_ost_lvb_lvb_size().
Referenced by lustre_ldlm_opcode_process().
static int lustre_dissect_struct_ptlrpc_body (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_, guint32 buf_len _U_) [static]
Definition at line 9540 of file packet-lustre.c.
References display_info_fstr(), display_info_str(), lustre_dissect_element_ptlrpc_body_pb_conn_cnt(), lustre_dissect_element_ptlrpc_body_pb_flags(), lustre_dissect_element_ptlrpc_body_pb_handle(), lustre_dissect_element_ptlrpc_body_pb_jobid(), lustre_dissect_element_ptlrpc_body_pb_last_committed(), lustre_dissect_element_ptlrpc_body_pb_last_seen(), lustre_dissect_element_ptlrpc_body_pb_last_xid(), lustre_dissect_element_ptlrpc_body_pb_limit(), lustre_dissect_element_ptlrpc_body_pb_op_flags(), lustre_dissect_element_ptlrpc_body_pb_opc(), lustre_dissect_element_ptlrpc_body_pb_padding(), lustre_dissect_element_ptlrpc_body_pb_pre_version(), lustre_dissect_element_ptlrpc_body_pb_service_time(), lustre_dissect_element_ptlrpc_body_pb_slv(), lustre_dissect_element_ptlrpc_body_pb_status(), lustre_dissect_element_ptlrpc_body_pb_timeout(), lustre_dissect_element_ptlrpc_body_pb_transno(), lustre_dissect_element_ptlrpc_body_pb_type(), lustre_dissect_element_ptlrpc_body_pb_version(), lustre_opcode_process(), LUSTRE_PTLRPC_MSG_VERSION, LUSTRE_VERSION_MASK, and sanity_check.
Referenced by lustre_dissect_struct_msg_v2().
int lustre_dissect_struct_qunit_data (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 7865 of file packet-lustre.c.
References lustre_dissect_element_qunit_data_padding(), lustre_dissect_element_qunit_data_qd_count(), lustre_dissect_element_qunit_data_qd_flags(), lustre_dissect_element_qunit_data_qd_id(), and lustre_dissect_element_qunit_data_qd_qunit().
int lustre_dissect_struct_qunit_data_old (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 7996 of file packet-lustre.c.
References lustre_dissect_element_qunit_data_old_qd_count(), lustre_dissect_element_qunit_data_old_qd_id(), lustre_dissect_element_qunit_data_old_qd_isblk(), and lustre_dissect_element_qunit_data_old_qd_type().
int lustre_dissect_struct_qunit_data_old2 (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 7928 of file packet-lustre.c.
References lustre_dissect_element_qunit_data_old2_qd_count(), lustre_dissect_element_qunit_data_old2_qd_flags(), and lustre_dissect_element_qunit_data_old2_qd_id().
int lustre_dissect_struct_quota_adjust_qunit (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 2727 of file packet-lustre.c.
References lustre_dissect_element_quota_adjust_qunit_padding1(), lustre_dissect_element_quota_adjust_qunit_qaq_bunit_sz(), lustre_dissect_element_quota_adjust_qunit_qaq_flags(), lustre_dissect_element_quota_adjust_qunit_qaq_id(), and lustre_dissect_element_quota_adjust_qunit_qaq_iunit_sz().
Referenced by lustre_ost_opcode_process().
int lustre_dissect_struct_seq (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_, int hf_index _U_)
Definition at line 8026 of file packet-lustre.c.
References add_extra_padding(), and dissect_uint32.
Referenced by lustre_fld_opcode_process(), and lustre_seq_opcode_process().
int lustre_dissect_struct_seq_range (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *parent_tree _U_)
Definition at line 8036 of file packet-lustre.c.
References dissect_uint32, and dissect_uint64.
Referenced by lustre_fld_opcode_process(), and lustre_seq_opcode_process().
static int lustre_fld_opcode_process (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, guint32 opc _U_, guint32 pb_type) [static]
Definition at line 9003 of file packet-lustre.c.
References FLD_QUERY, lustre_dissect_struct_seq(), lustre_dissect_struct_seq_range(), and PTL_RPC_MSG_REQUEST.
Referenced by lustre_opcode_process().
static int lustre_ldlm_opcode_process (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, guint32 opc _U_, guint32 pb_type) [static]
Definition at line 8741 of file packet-lustre.c.
References LDLM_BL_CALLBACK, LDLM_CANCEL, LDLM_CONVERT, LDLM_CP_CALLBACK, LDLM_ENQUEUE, LDLM_EXTENT, LDLM_GL_CALLBACK, LUSTRE_BUFCOUNT, LUSTRE_BUFFER_LEN, lustre_dissect_struct_acl(), lustre_dissect_struct_capa(), lustre_dissect_struct_ldlm_intent(), lustre_dissect_struct_ldlm_reply(), lustre_dissect_struct_ldlm_request(), lustre_dissect_struct_lov_mds_md(), lustre_dissect_struct_mdt_body(), lustre_dissect_struct_ost_lvb(), LUSTRE_DLM_INTENT_REC_OFF, LUSTRE_DLM_REPLY_REC_OFF, LUSTRE_REPLY_REC_OFF, PTL_RPC_MSG_REPLY, and PTL_RPC_MSG_REQUEST.
Referenced by lustre_opcode_process().
static int lustre_llog_opcode_process (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, guint32 opc _U_, guint32 pb_type) [static]
Definition at line 8903 of file packet-lustre.c.
References LLOG_CATINFO, LLOG_ORIGIN_CONNECT, LLOG_ORIGIN_HANDLE_CLOSE, LLOG_ORIGIN_HANDLE_CREATE, LLOG_ORIGIN_HANDLE_DESTROY, LLOG_ORIGIN_HANDLE_NEXT_BLOCK, LLOG_ORIGIN_HANDLE_PREV_BLOCK, LLOG_ORIGIN_HANDLE_READ_HEADER, LLOG_ORIGIN_HANDLE_WRITE_REC, LUSTRE_BUFCOUNT, LUSTRE_BUFLEN_OFF, lustre_dissect_element_data(), lustre_dissect_element_string(), lustre_dissect_struct_llog_log_hdr(), lustre_dissect_struct_llogd_body(), LUSTRE_REPLY_REC_OFF, LUSTRE_REQ_REC_OFF, PTL_RPC_MSG_REPLY, and PTL_RPC_MSG_REQUEST.
Referenced by lustre_opcode_process().
static int lustre_mds_opcode_process (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, guint32 opc _U_, guint32 pb_type) [static]
Definition at line 8587 of file packet-lustre.c.
References LUSTRE_BUFFER_LEN, lustre_dissect_element_data(), lustre_dissect_element_string(), lustre_dissect_generic_connect(), lustre_dissect_struct_acl(), lustre_dissect_struct_capa(), lustre_dissect_struct_llog_cookie(), lustre_dissect_struct_lov_mds_md(), lustre_dissect_struct_mdt_body(), lustre_dissect_struct_mdt_ioepoch(), lustre_dissect_struct_mdt_rec_setattr(), lustre_dissect_struct_obd_connect_data(), lustre_dissect_struct_obd_quotactl(), lustre_dissect_struct_obd_statfs(), LUSTRE_REPLY_REC_OFF, LUSTRE_REQ_REC_OFF, MDS_CLOSE, MDS_CONNECT, MDS_DISCONNECT, MDS_DONE_WRITING, MDS_GET_ROOT, MDS_GETATTR, MDS_GETATTR_NAME, MDS_GETXATTR, MDS_PIN, MDS_QUOTACHECK, MDS_QUOTACTL, MDS_READPAGE, MDS_REINT, MDS_SET_INFO, MDS_SETXATTR, MDS_STATFS, MDS_SYNC, PTL_RPC_MSG_ERR, PTL_RPC_MSG_REPLY, PTL_RPC_MSG_REQUEST, and reint_opcode_process().
Referenced by lustre_opcode_process().
static int lustre_mgs_opcode_process (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, guint32 opc _U_, guint32 pb_type) [static]
Definition at line 8843 of file packet-lustre.c.
References lustre_dissect_generic_connect(), lustre_dissect_struct_mgs_config_body(), lustre_dissect_struct_mgs_config_res(), lustre_dissect_struct_mgs_send_param(), lustre_dissect_struct_mgs_target_info(), lustre_dissect_struct_obd_connect_data(), MGS_CONFIG_READ, MGS_CONNECT, MGS_DISCONNECT, MGS_EXCEPTION, MGS_SET_INFO, MGS_TARGET_DEL, MGS_TARGET_REG, PTL_RPC_MSG_REPLY, and PTL_RPC_MSG_REQUEST.
Referenced by lustre_opcode_process().
static int lustre_odb_opcode_process (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, guint32 opc _U_, guint32 pb_type) [static]
Definition at line 8882 of file packet-lustre.c.
References lustre_dissect_struct_obd_quotactl(), OBD_LOG_CANCEL, OBD_PING, OBD_QC_CALLBACK, and PTL_RPC_MSG_REQUEST.
Referenced by lustre_opcode_process().
static int lustre_opcode_process (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, guint32 opc _U_, guint32 pb_type) [static]
Definition at line 9027 of file packet-lustre.c.
References FLD_FIRST_OPC, FLD_LAST_OPC, LDLM_FIRST_OPC, LDLM_LAST_OPC, LLOG_FIRST_OPC, LLOG_LAST_OPC, LUSTRE_BUFCOUNT, lustre_fld_opcode_process(), lustre_ldlm_opcode_process(), lustre_llog_opcode_process(), lustre_mds_opcode_process(), lustre_mgs_opcode_process(), lustre_odb_opcode_process(), lustre_ost_opcode_process(), lustre_seq_opcode_process(), MDS_FIRST_OPC, MDS_LAST_OPC, MGS_FIRST_OPC, MGS_LAST_OPC, OBD_FIRST_OPC, OBD_LAST_OPC, OST_LAST_OPC, SEQ_FIRST_OPC, and SEQ_LAST_OPC.
Referenced by lustre_dissect_struct_msg_v1(), and lustre_dissect_struct_ptlrpc_body().
static int lustre_ost_opcode_process (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, guint32 opc _U_, guint32 pb_type) [static]
Definition at line 8470 of file packet-lustre.c.
References add_extra_padding(), dissect_uint32, LUSTRE_BUFCOUNT, LUSTRE_BUFFER_LEN, lustre_dissect_element_string(), lustre_dissect_generic_connect(), lustre_dissect_struct_capa(), lustre_dissect_struct_ldlm_request(), lustre_dissect_struct_lu_ladvise(), lustre_dissect_struct_niobuf_remote(), lustre_dissect_struct_obd_connect_data(), lustre_dissect_struct_obd_ioobj(), lustre_dissect_struct_obd_quotactl(), lustre_dissect_struct_obd_statfs(), lustre_dissect_struct_ost_body(), lustre_dissect_struct_quota_adjust_qunit(), LUSTRE_REPLY_REC_OFF, LUSTRE_REQ_REC_OFF, OST_CLOSE, OST_CONNECT, OST_CREATE, OST_DESTROY, OST_DISCONNECT, OST_GET_INFO, OST_GETATTR, OST_LADVISE, OST_OPEN, OST_PUNCH, OST_QUOTA_ADJUST_QUNIT, OST_QUOTACHECK, OST_QUOTACTL, OST_READ, OST_REPLY, OST_SET_INFO, OST_SETATTR, OST_STATFS, OST_SYNC, OST_WRITE, PTL_RPC_MSG_REPLY, and PTL_RPC_MSG_REQUEST.
Referenced by lustre_opcode_process().
static int lustre_seq_opcode_process (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_, guint32 opc _U_, guint32 pb_type) [static]
Definition at line 8982 of file packet-lustre.c.
References lustre_dissect_struct_seq(), lustre_dissect_struct_seq_range(), PTL_RPC_MSG_REQUEST, and SEQ_QUERY.
Referenced by lustre_opcode_process().
void plugin_reg_handoff (void)
Definition at line 1289 of file packet-lustre.c.
References proto_reg_handoff_lustre().
void plugin_register (void)
Definition at line 1281 of file packet-lustre.c.
void proto_reg_handoff_lustre (void)
Definition at line 11139 of file packet-lustre.c.
References CONNMGR_REPLY_PORTAL, CONNMGR_REQUEST_PORTAL, dissect_lustre(), FLD_REQUEST_PORTAL, LDLM_CANCEL_REPLY_PORTAL, LDLM_CANCEL_REQUEST_PORTAL, LDLM_CB_REPLY_PORTAL, LDLM_CB_REQUEST_PORTAL, MDC_REPLY_PORTAL, MDS_READPAGE_PORTAL, MDS_REQUEST_PORTAL, MDS_SETATTR_PORTAL, MGC_REPLY_PORTAL, MGS_REPLY_PORTAL, MGS_REQUEST_PORTAL, OSC_REPLY_PORTAL, OST_CREATE_PORTAL, OST_IO_PORTAL, OST_REQUEST_PORTAL, SEQ_CONTROLLER_PORTAL, SEQ_DATA_PORTAL, and SEQ_METADATA_PORTAL.
Referenced by plugin_reg_handoff().
static int reint_opcode_process (tvbuff_t *tvb _U_, int offset _U_, packet_info *pinfo _U_, proto_tree *tree _U_) [static]
Definition at line 8279 of file packet-lustre.c.
References LUSTRE_BUFCOUNT, LUSTRE_BUFFER_LEN, lustre_dissect_element_data(), lustre_dissect_element_string(), lustre_dissect_struct_capa(), lustre_dissect_struct_ldlm_request(), lustre_dissect_struct_llog_cookie(), lustre_dissect_struct_mdt_ioepoch(), lustre_dissect_struct_mdt_rec_create(), lustre_dissect_struct_mdt_rec_link(), lustre_dissect_struct_mdt_rec_rename(), lustre_dissect_struct_mdt_rec_setattr(), lustre_dissect_struct_mdt_rec_setxattr(), lustre_dissect_struct_mdt_rec_unlink(), lustre_dissect_struct_obd_quotactl(), LUSTRE_REQ_REC_OFF, REINT_CREATE, REINT_LINK, REINT_OPEN, REINT_RENAME, REINT_SETATTR, REINT_SETXATTR, and REINT_UNLINK.
Referenced by lustre_mds_opcode_process().
static void sanity_check (tvbuff_t * tvb, packet_info * pinfo, guint32 val_offset _U_) [static]
Definition at line 9130 of file packet-lustre.c.
References LUSTRE_BUFCOUNT, and LUSTRE_BUFLEN_OFF.
Variable Documentation
dissect_func dissect_uint16 [static]
Definition at line 1041 of file packet-lustre.c.
Referenced by lustre_dissect_struct_mgs_config_body().
dissect_func dissect_uint32 [static]
Definition at line 1041 of file packet-lustre.c.
Referenced by lustre_dissect_element_capa_flags(), lustre_dissect_element_cfg_marker_cm_flags(), lustre_dissect_element_cfg_marker_cm_step(), lustre_dissect_element_cfg_marker_cm_vers(), lustre_dissect_element_cfg_marker_padding(), lustre_dissect_element_ldlm_flock_blocking_pid(), lustre_dissect_element_ldlm_flock_pid(), lustre_dissect_element_ldlm_intent_opc(), lustre_dissect_element_ldlm_reply_lock_padding(), lustre_dissect_element_ldlm_request_lock_count(), lustre_dissect_element_ldlm_resource_desc_lr_padding(), lustre_dissect_element_ll_fid_f_type(), lustre_dissect_element_ll_fid_generation(), lustre_dissect_element_llog_catid_lci_padding1(), lustre_dissect_element_llog_catid_lci_padding2(), lustre_dissect_element_llog_catid_lci_padding3(), lustre_dissect_element_llog_cookie_lgc_index(), lustre_dissect_element_llog_cookie_lgc_padding(), lustre_dissect_element_llog_cookie_lgc_subsys(), lustre_dissect_element_llog_log_hdr_llh_bitmap_(), lustre_dissect_element_llog_log_hdr_llh_bitmap_offset(), lustre_dissect_element_llog_log_hdr_llh_cat_idx(), lustre_dissect_element_llog_log_hdr_llh_count(), lustre_dissect_element_llog_log_hdr_llh_reserved_(), lustre_dissect_element_llog_log_hdr_llh_size(), lustre_dissect_element_llog_log_llh_flags(), lustre_dissect_element_llog_logid_lgl_ogen(), lustre_dissect_element_llog_logid_rec_padding1(), lustre_dissect_element_llog_logid_rec_padding2(), lustre_dissect_element_llog_logid_rec_padding3(), lustre_dissect_element_llog_logid_rec_padding4(), lustre_dissect_element_llog_logid_rec_padding5(), lustre_dissect_element_llog_rec_hdr_lrh_index(), lustre_dissect_element_llog_rec_hdr_lrh_len(), lustre_dissect_element_llog_rec_hdr_lrh_type(), lustre_dissect_element_llog_rec_hdr_padding(), lustre_dissect_element_llog_rec_tail_lrt_index(), lustre_dissect_element_llog_rec_tail_lrt_len(), lustre_dissect_element_llog_setattr_rec_lsr_gid(), lustre_dissect_element_llog_setattr_rec_lsr_ogen(), lustre_dissect_element_llog_setattr_rec_lsr_uid(), lustre_dissect_element_llog_setattr_rec_padding(), lustre_dissect_element_llog_size_change_rec_lsc_io_epoch(), lustre_dissect_element_llog_size_change_rec_padding(), lustre_dissect_element_llog_unlink_rec_lur_ogen(), lustre_dissect_element_llog_unlink_rec_padding(), lustre_dissect_element_llogd_body_lgd_ctxt_idx(), lustre_dissect_element_llogd_body_lgd_index(), lustre_dissect_element_llogd_body_lgd_len(), lustre_dissect_element_llogd_body_lgd_saved_index(), lustre_dissect_element_llogd_conn_body_lgdc_ctxt_idx(), lustre_dissect_element_lov_desc_ld_active_tgt_count(), lustre_dissect_element_lov_desc_ld_default_stripe_count(), lustre_dissect_element_lov_desc_ld_padding_0(), lustre_dissect_element_lov_desc_ld_padding_1(), lustre_dissect_element_lov_desc_ld_padding_2(), lustre_dissect_element_lov_desc_ld_pattern(), lustre_dissect_element_lov_desc_ld_qos_maxage(), lustre_dissect_element_lov_desc_ld_tgt_count(), lustre_dissect_element_lov_mds_md_v1_lmm_magic(), lustre_dissect_element_lov_mds_md_v1_lmm_pattern(), lustre_dissect_element_lov_mds_md_v1_lmm_stripe_count(), lustre_dissect_element_lov_mds_md_v1_lmm_stripe_size(), lustre_dissect_element_lov_ost_data_v1_l_ost_gen(), lustre_dissect_element_lov_ost_data_v1_l_ost_idx(), lustre_dissect_element_mdt_body_aclsize(), lustre_dissect_element_mdt_body_capability(), lustre_dissect_element_mdt_body_eadatasize(), lustre_dissect_element_mdt_body_flags(), lustre_dissect_element_mdt_body_fsgid(), lustre_dissect_element_mdt_body_fsuid(), lustre_dissect_element_mdt_body_generation(), lustre_dissect_element_mdt_body_gid(), lustre_dissect_element_mdt_body_gid_h(), lustre_dissect_element_mdt_body_max_cookiesize(), lustre_dissect_element_mdt_body_max_mdsize(), lustre_dissect_element_mdt_body_mode(), lustre_dissect_element_mdt_body_nlink(), lustre_dissect_element_mdt_body_padding_5(), lustre_dissect_element_mdt_body_rdev(), lustre_dissect_element_mdt_body_suppgid(), lustre_dissect_element_mdt_body_uid(), lustre_dissect_element_mdt_body_uid_h(), lustre_dissect_element_mdt_rec_create_cr_bias(), lustre_dissect_element_mdt_rec_create_cr_cap(), lustre_dissect_element_mdt_rec_create_cr_flags_h(), lustre_dissect_element_mdt_rec_create_cr_flags_l(), lustre_dissect_element_mdt_rec_create_cr_fsgid(), lustre_dissect_element_mdt_rec_create_cr_fsgid_h(), lustre_dissect_element_mdt_rec_create_cr_fsuid(), lustre_dissect_element_mdt_rec_create_cr_fsuid_h(), lustre_dissect_element_mdt_rec_create_cr_mode(), lustre_dissect_element_mdt_rec_create_cr_opcode(), lustre_dissect_element_mdt_rec_create_cr_padding_4(), lustre_dissect_element_mdt_rec_create_cr_suppgid1(), lustre_dissect_element_mdt_rec_create_cr_suppgid1_h(), lustre_dissect_element_mdt_rec_create_cr_suppgid2(), lustre_dissect_element_mdt_rec_create_cr_suppgid2_h(), lustre_dissect_element_mdt_rec_create_cr_umask(), lustre_dissect_element_mdt_rec_link_lk_bias(), lustre_dissect_element_mdt_rec_link_lk_cap(), lustre_dissect_element_mdt_rec_link_lk_fsgid(), lustre_dissect_element_mdt_rec_link_lk_fsgid_h(), lustre_dissect_element_mdt_rec_link_lk_fsuid(), lustre_dissect_element_mdt_rec_link_lk_fsuid_h(), lustre_dissect_element_mdt_rec_link_lk_opcode(), lustre_dissect_element_mdt_rec_link_lk_padding_5(), lustre_dissect_element_mdt_rec_link_lk_padding_6(), lustre_dissect_element_mdt_rec_link_lk_padding_7(), lustre_dissect_element_mdt_rec_link_lk_padding_8(), lustre_dissect_element_mdt_rec_link_lk_padding_9(), lustre_dissect_element_mdt_rec_link_lk_suppgid1(), lustre_dissect_element_mdt_rec_link_lk_suppgid1_h(), lustre_dissect_element_mdt_rec_link_lk_suppgid2(), lustre_dissect_element_mdt_rec_link_lk_suppgid2_h(), lustre_dissect_element_mdt_rec_rename_rn_bias(), lustre_dissect_element_mdt_rec_rename_rn_cap(), lustre_dissect_element_mdt_rec_rename_rn_fsgid(), lustre_dissect_element_mdt_rec_rename_rn_fsgid_h(), lustre_dissect_element_mdt_rec_rename_rn_fsuid(), lustre_dissect_element_mdt_rec_rename_rn_fsuid_h(), lustre_dissect_element_mdt_rec_rename_rn_mode(), lustre_dissect_element_mdt_rec_rename_rn_opcode(), lustre_dissect_element_mdt_rec_rename_rn_padding_5(), lustre_dissect_element_mdt_rec_rename_rn_padding_6(), lustre_dissect_element_mdt_rec_rename_rn_padding_7(), lustre_dissect_element_mdt_rec_rename_rn_padding_8(), lustre_dissect_element_mdt_rec_rename_rn_suppgid1(), lustre_dissect_element_mdt_rec_rename_rn_suppgid1_h(), lustre_dissect_element_mdt_rec_rename_rn_suppgid2(), lustre_dissect_element_mdt_rec_rename_rn_suppgid2_h(), lustre_dissect_element_mdt_rec_setattr_sa_attr_flags(), lustre_dissect_element_mdt_rec_setattr_sa_cap(), lustre_dissect_element_mdt_rec_setattr_sa_fsgid(), lustre_dissect_element_mdt_rec_setattr_sa_fsgid_h(), lustre_dissect_element_mdt_rec_setattr_sa_fsuid(), lustre_dissect_element_mdt_rec_setattr_sa_fsuid_h(), lustre_dissect_element_mdt_rec_setattr_sa_gid(), lustre_dissect_element_mdt_rec_setattr_sa_mode(), lustre_dissect_element_mdt_rec_setattr_sa_opcode(), lustre_dissect_element_mdt_rec_setattr_sa_padding_1(), lustre_dissect_element_mdt_rec_setattr_sa_padding_1_h(), lustre_dissect_element_mdt_rec_setattr_sa_padding_2(), lustre_dissect_element_mdt_rec_setattr_sa_padding_3(), lustre_dissect_element_mdt_rec_setattr_sa_padding_4(), lustre_dissect_element_mdt_rec_setattr_sa_padding_5(), lustre_dissect_element_mdt_rec_setattr_sa_suppgid(), lustre_dissect_element_mdt_rec_setattr_sa_suppgid_h(), lustre_dissect_element_mdt_rec_setattr_sa_uid(), lustre_dissect_element_mdt_rec_setxattr_sx_cap(), lustre_dissect_element_mdt_rec_setxattr_sx_flags(), lustre_dissect_element_mdt_rec_setxattr_sx_fsgid(), lustre_dissect_element_mdt_rec_setxattr_sx_fsgid_h(), lustre_dissect_element_mdt_rec_setxattr_sx_fsuid(), lustre_dissect_element_mdt_rec_setxattr_sx_fsuid_h(), lustre_dissect_element_mdt_rec_setxattr_sx_opcode(), lustre_dissect_element_mdt_rec_setxattr_sx_padding_10(), lustre_dissect_element_mdt_rec_setxattr_sx_padding_11(), lustre_dissect_element_mdt_rec_setxattr_sx_padding_2(), lustre_dissect_element_mdt_rec_setxattr_sx_padding_3(), lustre_dissect_element_mdt_rec_setxattr_sx_padding_8(), lustre_dissect_element_mdt_rec_setxattr_sx_padding_9(), lustre_dissect_element_mdt_rec_setxattr_sx_size(), lustre_dissect_element_mdt_rec_setxattr_sx_suppgid1(), lustre_dissect_element_mdt_rec_setxattr_sx_suppgid1_h(), lustre_dissect_element_mdt_rec_setxattr_sx_suppgid2(), lustre_dissect_element_mdt_rec_setxattr_sx_suppgid2_h(), lustre_dissect_element_mdt_rec_unlink_ul_bias(), lustre_dissect_element_mdt_rec_unlink_ul_cap(), lustre_dissect_element_mdt_rec_unlink_ul_fsgid(), lustre_dissect_element_mdt_rec_unlink_ul_fsgid_h(), lustre_dissect_element_mdt_rec_unlink_ul_fsuid(), lustre_dissect_element_mdt_rec_unlink_ul_fsuid_h(), lustre_dissect_element_mdt_rec_unlink_ul_mode(), lustre_dissect_element_mdt_rec_unlink_ul_opcode(), lustre_dissect_element_mdt_rec_unlink_ul_padding_6(), lustre_dissect_element_mdt_rec_unlink_ul_padding_7(), lustre_dissect_element_mdt_rec_unlink_ul_padding_8(), lustre_dissect_element_mdt_rec_unlink_ul_padding_9(), lustre_dissect_element_mdt_rec_unlink_ul_suppgid1(), lustre_dissect_element_mdt_rec_unlink_ul_suppgid1_h(), lustre_dissect_element_mdt_rec_unlink_ul_suppgid2(), lustre_dissect_element_mdt_rec_unlink_ul_suppgid2_h(), lustre_dissect_element_mgs_target_info_mti_config_ver(), lustre_dissect_element_mgs_target_info_mti_flags(), lustre_dissect_element_mgs_target_info_mti_lustre_ver(), lustre_dissect_element_mgs_target_info_mti_nid_count(), lustre_dissect_element_mgs_target_info_mti_stripe_index(), lustre_dissect_element_mgs_target_info_padding(), lustre_dissect_element_msg_v1_lm_bufcount(), lustre_dissect_element_msg_v1_lm_buflens(), lustre_dissect_element_msg_v1_lm_buflens_(), lustre_dissect_element_msg_v1_lm_conn_cnt(), lustre_dissect_element_msg_v1_lm_flags(), lustre_dissect_element_msg_v1_lm_magic(), lustre_dissect_element_msg_v1_lm_opc(), lustre_dissect_element_msg_v1_lm_status(), lustre_dissect_element_msg_v1_lm_type(), lustre_dissect_element_msg_v1_lm_version(), lustre_dissect_element_msg_v2_lm_buflens_(), lustre_dissect_element_msg_v2_lm_cksum(), lustre_dissect_element_msg_v2_lm_flags(), lustre_dissect_element_msg_v2_lm_magic(), lustre_dissect_element_msg_v2_lm_padding_2(), lustre_dissect_element_msg_v2_lm_padding_3(), lustre_dissect_element_msg_v2_lm_repsize(), lustre_dissect_element_msg_v2_lm_secflvr(), lustre_dissect_element_niobuf_remote_flags(), lustre_dissect_element_niobuf_remote_len(), lustre_dissect_element_obd_connect_data_ocd_brw_size(), lustre_dissect_element_obd_connect_data_ocd_cksum_types(), lustre_dissect_element_obd_connect_data_ocd_grant(), lustre_dissect_element_obd_connect_data_ocd_group(), lustre_dissect_element_obd_connect_data_ocd_index(), lustre_dissect_element_obd_connect_data_ocd_nllg(), lustre_dissect_element_obd_connect_data_ocd_nllu(), lustre_dissect_element_obd_connect_data_ocd_version(), lustre_dissect_element_obd_dqblk_dqb_valid(), lustre_dissect_element_obd_dqblk_padding(), lustre_dissect_element_obd_dqinfo_dqi_flags(), lustre_dissect_element_obd_dqinfo_dqi_valid(), lustre_dissect_element_obd_ioobj_ioo_bufcnt(), lustre_dissect_element_obd_ioobj_ioo_max_brw(), lustre_dissect_element_obd_quotactl_qc_cmd(), lustre_dissect_element_obd_quotactl_qc_id(), lustre_dissect_element_obd_quotactl_qc_stat(), lustre_dissect_element_obd_quotactl_qc_type(), lustre_dissect_element_obd_statfs_os_bsize(), lustre_dissect_element_obd_statfs_os_namelen(), lustre_dissect_element_obd_statfs_os_spare1(), lustre_dissect_element_obd_statfs_os_spare2(), lustre_dissect_element_obd_statfs_os_spare3(), lustre_dissect_element_obd_statfs_os_spare4(), lustre_dissect_element_obd_statfs_os_spare5(), lustre_dissect_element_obd_statfs_os_spare6(), lustre_dissect_element_obd_statfs_os_spare7(), lustre_dissect_element_obd_statfs_os_spare8(), lustre_dissect_element_obd_statfs_os_spare9(), lustre_dissect_element_obd_statfs_os_state(), lustre_dissect_element_obdo_o_blksize(), lustre_dissect_element_obdo_o_flags(), lustre_dissect_element_obdo_o_gid(), lustre_dissect_element_obdo_o_gid_h(), lustre_dissect_element_obdo_o_misc(), lustre_dissect_element_obdo_o_mode(), lustre_dissect_element_obdo_o_nlink(), lustre_dissect_element_obdo_o_parent_oid(), lustre_dissect_element_obdo_o_parent_ver(), lustre_dissect_element_obdo_o_stripe_idx(), lustre_dissect_element_obdo_o_uid(), lustre_dissect_element_obdo_o_uid_h(), lustre_dissect_element_ptlrpc_body_pb_conn_cnt(), lustre_dissect_element_ptlrpc_body_pb_flags(), lustre_dissect_element_ptlrpc_body_pb_limit(), lustre_dissect_element_ptlrpc_body_pb_op_flags(), lustre_dissect_element_ptlrpc_body_pb_opc(), lustre_dissect_element_ptlrpc_body_pb_service_time(), lustre_dissect_element_ptlrpc_body_pb_status(), lustre_dissect_element_ptlrpc_body_pb_timeout(), lustre_dissect_element_ptlrpc_body_pb_type(), lustre_dissect_element_ptlrpc_body_pb_version(), lustre_dissect_element_qunit_data_old2_qd_flags(), lustre_dissect_element_qunit_data_old2_qd_id(), lustre_dissect_element_qunit_data_old_qd_count(), lustre_dissect_element_qunit_data_old_qd_id(), lustre_dissect_element_qunit_data_old_qd_isblk(), lustre_dissect_element_qunit_data_old_qd_type(), lustre_dissect_element_qunit_data_qd_flags(), lustre_dissect_element_qunit_data_qd_id(), lustre_dissect_element_quota_adjust_qunit_qaq_flags(), lustre_dissect_element_quota_adjust_qunit_qaq_id(), lustre_dissect_enum_ldlm_mode(), lustre_dissect_enum_ldlm_type(), lustre_dissect_struct_capa(), lustre_dissect_struct_fld_range(), lustre_dissect_struct_mdt_ioepoch(), lustre_dissect_struct_mgs_config_body(), lustre_dissect_struct_msg_v2(), lustre_dissect_struct_seq(), lustre_dissect_struct_seq_range(), and lustre_ost_opcode_process().
dissect_func dissect_uint64 [static]
Definition at line 1041 of file packet-lustre.c.
Referenced by lustre_dissect_element_capa_opc(), lustre_dissect_element_handle_cookie(), lustre_dissect_element_ldlm_extent_end(), lustre_dissect_element_ldlm_extent_gid(), lustre_dissect_element_ldlm_extent_start(), lustre_dissect_element_ldlm_flock_blocking_export(), lustre_dissect_element_ldlm_flock_end(), lustre_dissect_element_ldlm_flock_start(), lustre_dissect_element_ldlm_inodebits_bits(), lustre_dissect_element_ldlm_lock_desc_l_policy_data(), lustre_dissect_element_ldlm_reply_lock_policy_res1(), lustre_dissect_element_ldlm_reply_lock_policy_res2(), lustre_dissect_element_ldlm_res_id_name_(), lustre_dissect_element_ll_fid_id(), lustre_dissect_element_llog_gen_conn_cnt(), lustre_dissect_element_llog_gen_mnt_cnt(), lustre_dissect_element_llog_logid_lgl_oid(), lustre_dissect_element_llog_logid_lgl_oseq(), lustre_dissect_element_llog_setattr_rec_lsr_oid(), lustre_dissect_element_llog_unlink_rec_lur_oid(), lustre_dissect_element_llogd_body_lgd_cur_offset(), lustre_dissect_element_lov_desc_ld_default_stripe_offset(), lustre_dissect_element_lov_desc_ld_default_stripe_size(), lustre_dissect_element_lov_mds_md_v1_lmm_object_id(), lustre_dissect_element_lov_mds_md_v1_lmm_object_seq(), lustre_dissect_element_lov_ost_data_v1_l_object_id(), lustre_dissect_element_lov_ost_data_v1_l_object_seq(), lustre_dissect_element_mdt_body_blocks(), lustre_dissect_element_mdt_body_ino(), lustre_dissect_element_mdt_body_ioepoch(), lustre_dissect_element_mdt_body_padding_10(), lustre_dissect_element_mdt_body_padding_6(), lustre_dissect_element_mdt_body_padding_7(), lustre_dissect_element_mdt_body_padding_8(), lustre_dissect_element_mdt_body_padding_9(), lustre_dissect_element_mdt_body_size(), lustre_dissect_element_mdt_body_valid(), lustre_dissect_element_mdt_rec_create_cr_ioepoch(), lustre_dissect_element_mdt_rec_create_cr_padding_1(), lustre_dissect_element_mdt_rec_create_cr_rdev(), lustre_dissect_element_mdt_rec_link_lk_padding_1(), lustre_dissect_element_mdt_rec_link_lk_padding_2(), lustre_dissect_element_mdt_rec_link_lk_padding_3(), lustre_dissect_element_mdt_rec_link_lk_padding_4(), lustre_dissect_element_mdt_rec_rename_rn_padding_1(), lustre_dissect_element_mdt_rec_rename_rn_padding_2(), lustre_dissect_element_mdt_rec_rename_rn_padding_3(), lustre_dissect_element_mdt_rec_rename_rn_padding_4(), lustre_dissect_element_mdt_rec_setattr_sa_blocks(), lustre_dissect_element_mdt_rec_setattr_sa_size(), lustre_dissect_element_mdt_rec_setattr_sa_valid(), lustre_dissect_element_mdt_rec_setxattr_sx_padding_1(), lustre_dissect_element_mdt_rec_setxattr_sx_padding_5(), lustre_dissect_element_mdt_rec_setxattr_sx_padding_6(), lustre_dissect_element_mdt_rec_setxattr_sx_padding_7(), lustre_dissect_element_mdt_rec_setxattr_sx_valid(), lustre_dissect_element_mdt_rec_unlink_ul_padding_2(), lustre_dissect_element_mdt_rec_unlink_ul_padding_3(), lustre_dissect_element_mdt_rec_unlink_ul_padding_4(), lustre_dissect_element_mdt_rec_unlink_ul_padding_5(), lustre_dissect_element_mgs_target_info_mti_nids_(), lustre_dissect_element_msg_v1_lm_last_committed(), lustre_dissect_element_msg_v1_lm_last_xid(), lustre_dissect_element_msg_v1_lm_transno(), lustre_dissect_element_niobuf_remote_offset(), lustre_dissect_element_obd_connect_data_ocd_connect_flags(), lustre_dissect_element_obd_connect_data_ocd_ibits_known(), lustre_dissect_element_obd_connect_data_ocd_transno(), lustre_dissect_element_obd_connect_data_padding1(), lustre_dissect_element_obd_connect_data_padding2(), lustre_dissect_element_obd_dqblk_dqb_bhardlimit(), lustre_dissect_element_obd_dqblk_dqb_bsoftlimit(), lustre_dissect_element_obd_dqblk_dqb_curinodes(), lustre_dissect_element_obd_dqblk_dqb_curspace(), lustre_dissect_element_obd_dqblk_dqb_ihardlimit(), lustre_dissect_element_obd_dqblk_dqb_isoftlimit(), lustre_dissect_element_obd_dqinfo_dqi_bgrace(), lustre_dissect_element_obd_dqinfo_dqi_igrace(), lustre_dissect_element_obd_ioobj_ioo_id(), lustre_dissect_element_obd_ioobj_ioo_seq(), lustre_dissect_element_obd_statfs_os_bavail(), lustre_dissect_element_obd_statfs_os_bfree(), lustre_dissect_element_obd_statfs_os_blocks(), lustre_dissect_element_obd_statfs_os_ffree(), lustre_dissect_element_obd_statfs_os_files(), lustre_dissect_element_obd_statfs_os_maxbytes(), lustre_dissect_element_obd_statfs_os_type(), lustre_dissect_element_obdo_o_blocks(), lustre_dissect_element_obdo_o_grant(), lustre_dissect_element_obdo_o_id(), lustre_dissect_element_obdo_o_ioepoch(), lustre_dissect_element_obdo_o_padding_3(), lustre_dissect_element_obdo_o_padding_4(), lustre_dissect_element_obdo_o_padding_5(), lustre_dissect_element_obdo_o_padding_6(), lustre_dissect_element_obdo_o_parent_seq(), lustre_dissect_element_obdo_o_seq(), lustre_dissect_element_obdo_o_size(), lustre_dissect_element_obdo_o_valid(), lustre_dissect_element_ost_lvb_lvb_blocks(), lustre_dissect_element_ost_lvb_lvb_size(), lustre_dissect_element_ptlrpc_body_pb_last_committed(), lustre_dissect_element_ptlrpc_body_pb_last_seen(), lustre_dissect_element_ptlrpc_body_pb_last_xid(), lustre_dissect_element_ptlrpc_body_pb_padding(), lustre_dissect_element_ptlrpc_body_pb_pre_version(), lustre_dissect_element_ptlrpc_body_pb_slv(), lustre_dissect_element_ptlrpc_body_pb_transno(), lustre_dissect_element_qunit_data_old2_qd_count(), lustre_dissect_element_qunit_data_padding(), lustre_dissect_element_qunit_data_qd_count(), lustre_dissect_element_qunit_data_qd_qunit(), lustre_dissect_element_quota_adjust_qunit_padding1(), lustre_dissect_element_quota_adjust_qunit_qaq_bunit_sz(), lustre_dissect_element_quota_adjust_qunit_qaq_iunit_sz(), lustre_dissect_struct_capa(), lustre_dissect_struct_fld_range(), lustre_dissect_struct_lu_ladvise(), lustre_dissect_struct_mdt_ioepoch(), lustre_dissect_struct_mgs_config_body(), lustre_dissect_struct_mgs_config_res(), and lustre_dissect_struct_seq_range().
dissect_func dissect_uint8 [static]
Definition at line 1041 of file packet-lustre.c.
Referenced by lustre_dissect_element_cfg_marker_cm_comment_(), lustre_dissect_element_cfg_marker_cm_tgtname_(), lustre_dissect_element_mgs_send_param_mgs_param_(), lustre_dissect_element_mgs_target_info_mti_fsname_(), lustre_dissect_element_mgs_target_info_mti_params_(), lustre_dissect_element_mgs_target_info_mti_svname_(), lustre_dissect_element_mgs_target_info_mti_uuid_(), lustre_dissect_element_obd_statfs_os_fsid_(), and lustre_dissect_struct_mgs_config_body().
gint ett_lustre = -1 [static]
Definition at line 366 of file packet-lustre.c.
gint ett_lustre_acl = -1 [static]
Definition at line 434 of file packet-lustre.c.
gint ett_lustre_capa = -1 [static]
Definition at line 433 of file packet-lustre.c.
gint ett_lustre_cfg_marker = -1 [static]
Definition at line 408 of file packet-lustre.c.
gint ett_lustre_fld_range = -1 [static]
Definition at line 431 of file packet-lustre.c.
gint ett_lustre_ldlm_extent = -1 [static]
Definition at line 395 of file packet-lustre.c.
gint ett_lustre_ldlm_flock = -1 [static]
Definition at line 397 of file packet-lustre.c.
gint ett_lustre_ldlm_inodebits = -1 [static]
Definition at line 396 of file packet-lustre.c.
gint ett_lustre_ldlm_intent_opc = -1 [static]
Definition at line 398 of file packet-lustre.c.
gint ett_lustre_ldlm_lock_desc = -1 [static]
Definition at line 400 of file packet-lustre.c.
gint ett_lustre_ldlm_lock_flags = -1 [static]
Definition at line 429 of file packet-lustre.c.
gint ett_lustre_ldlm_reply = -1 [static]
Definition at line 403 of file packet-lustre.c.
gint ett_lustre_ldlm_request = -1 [static]
Definition at line 401 of file packet-lustre.c.
gint ett_lustre_ldlm_res_id = -1 [static]
Definition at line 394 of file packet-lustre.c.
gint ett_lustre_ldlm_resource_desc = -1 [static]
Definition at line 399 of file packet-lustre.c.
gint ett_lustre_ll_fid = -1 [static]
Definition at line 380 of file packet-lustre.c.
gint ett_lustre_llog_catid = -1 [static]
Definition at line 409 of file packet-lustre.c.
gint ett_lustre_llog_cookie = -1 [static]
Definition at line 420 of file packet-lustre.c.
gint ett_lustre_llog_gen = -1 [static]
Definition at line 423 of file packet-lustre.c.
gint ett_lustre_llog_gen_rec = -1 [static]
Definition at line 418 of file packet-lustre.c.
gint ett_lustre_llog_log_hdr = -1 [static]
Definition at line 419 of file packet-lustre.c.
gint ett_lustre_llog_log_llh_flags = -1 [static]
Definition at line 365 of file packet-lustre.c.
gint ett_lustre_llog_logid = -1 [static]
Definition at line 412 of file packet-lustre.c.
gint ett_lustre_llog_logid_rec = -1 [static]
Definition at line 411 of file packet-lustre.c.
gint ett_lustre_llog_rec_hdr = -1 [static]
Definition at line 410 of file packet-lustre.c.
gint ett_lustre_llog_rec_tail = -1 [static]
Definition at line 413 of file packet-lustre.c.
gint ett_lustre_llog_setattr_rec = -1 [static]
Definition at line 416 of file packet-lustre.c.
gint ett_lustre_llog_size_change_rec = -1 [static]
Definition at line 417 of file packet-lustre.c.
gint ett_lustre_llog_unlink_rec = -1 [static]
Definition at line 415 of file packet-lustre.c.
gint ett_lustre_llogd_body = -1 [static]
Definition at line 421 of file packet-lustre.c.
gint ett_lustre_llogd_conn_body = -1 [static]
Definition at line 422 of file packet-lustre.c.
gint ett_lustre_lov_desc = -1 [static]
Definition at line 392 of file packet-lustre.c.
gint ett_lustre_lov_mds_md = -1 [static]
Definition at line 414 of file packet-lustre.c.
gint ett_lustre_lov_mds_md_v1 = -1 [static]
Definition at line 374 of file packet-lustre.c.
gint ett_lustre_lov_ost_data_v1 = -1 [static]
Definition at line 375 of file packet-lustre.c.
gint ett_lustre_lustre_handle = -1 [static]
Definition at line 402 of file packet-lustre.c.
gint ett_lustre_lustre_handle_cookie = -1 [static]
Definition at line 367 of file packet-lustre.c.
gint ett_lustre_lustre_handle_v1 = -1 [static]
Definition at line 369 of file packet-lustre.c.
gint ett_lustre_lustre_handle_v2 = -1 [static]
Definition at line 372 of file packet-lustre.c.
gint ett_lustre_lustre_msg_v1 = -1 [static]
Definition at line 368 of file packet-lustre.c.
gint ett_lustre_lustre_msg_v2 = -1 [static]
Definition at line 370 of file packet-lustre.c.
gint ett_lustre_mdt_body = -1 [static]
Definition at line 381 of file packet-lustre.c.
gint ett_lustre_mdt_ioepoch = -1 [static]
Definition at line 432 of file packet-lustre.c.
gint ett_lustre_mdt_rec_create = -1 [static]
Definition at line 383 of file packet-lustre.c.
gint ett_lustre_mdt_rec_link = -1 [static]
Definition at line 384 of file packet-lustre.c.
gint ett_lustre_mdt_rec_rename = -1 [static]
Definition at line 386 of file packet-lustre.c.
gint ett_lustre_mdt_rec_setattr = -1 [static]
Definition at line 382 of file packet-lustre.c.
gint ett_lustre_mdt_rec_setxattr = -1 [static]
Definition at line 387 of file packet-lustre.c.
gint ett_lustre_mdt_rec_unlink = -1 [static]
Definition at line 385 of file packet-lustre.c.
gint ett_lustre_mgs_config_body = -1 [static]
Definition at line 406 of file packet-lustre.c.
gint ett_lustre_mgs_config_res = -1 [static]
Definition at line 407 of file packet-lustre.c.
gint ett_lustre_mgs_send_param = -1 [static]
Definition at line 404 of file packet-lustre.c.
gint ett_lustre_mgs_target_info = -1 [static]
Definition at line 405 of file packet-lustre.c.
gint ett_lustre_niobuf_remote = -1 [static]
Definition at line 378 of file packet-lustre.c.
gint ett_lustre_obd_connect_data = -1 [static]
Definition at line 373 of file packet-lustre.c.
gint ett_lustre_obd_dqblk = -1 [static]
Definition at line 390 of file packet-lustre.c.
gint ett_lustre_obd_dqinfo = -1 [static]
Definition at line 389 of file packet-lustre.c.
gint ett_lustre_obd_ioobj = -1 [static]
Definition at line 377 of file packet-lustre.c.
gint ett_lustre_obd_quotactl = -1 [static]
Definition at line 388 of file packet-lustre.c.
gint ett_lustre_obd_statfs = -1 [static]
Definition at line 376 of file packet-lustre.c.
gint ett_lustre_obd_uuid = -1 [static]
Definition at line 393 of file packet-lustre.c.
gint ett_lustre_obdo = -1 [static]
Definition at line 424 of file packet-lustre.c.
gint ett_lustre_ost_body = -1 [static]
Definition at line 425 of file packet-lustre.c.
gint ett_lustre_ost_lvb = -1 [static]
Definition at line 379 of file packet-lustre.c.
gint ett_lustre_ptlrpc_body = -1 [static]
Definition at line 371 of file packet-lustre.c.
gint ett_lustre_qunit_data = -1 [static]
Definition at line 426 of file packet-lustre.c.
gint ett_lustre_qunit_data_old = -1 [static]
Definition at line 428 of file packet-lustre.c.
gint ett_lustre_qunit_data_old2 = -1 [static]
Definition at line 427 of file packet-lustre.c.
gint ett_lustre_quota_adjust_qunit = -1 [static]
Definition at line 391 of file packet-lustre.c.
gint ett_lustre_seq_range = -1 [static]
Definition at line 430 of file packet-lustre.c.
int hf_lustre_acl = -1 [static]
Definition at line 713 of file packet-lustre.c.
int hf_lustre_capa = -1 [static]
Definition at line 702 of file packet-lustre.c.
int hf_lustre_capa_expiry = -1 [static]
Definition at line 710 of file packet-lustre.c.
int hf_lustre_capa_fid = -1 [static]
Definition at line 703 of file packet-lustre.c.
int hf_lustre_capa_flags = -1 [static]
Definition at line 707 of file packet-lustre.c.
int hf_lustre_capa_gid = -1 [static]
Definition at line 706 of file packet-lustre.c.
int hf_lustre_capa_hmac = -1 [static]
Definition at line 711 of file packet-lustre.c.
int hf_lustre_capa_keyid = -1 [static]
Definition at line 708 of file packet-lustre.c.
int hf_lustre_capa_opc = -1 [static]
Definition at line 704 of file packet-lustre.c.
int hf_lustre_capa_timeout = -1 [static]
Definition at line 709 of file packet-lustre.c.
int hf_lustre_capa_uid = -1 [static]
Definition at line 705 of file packet-lustre.c.
int hf_lustre_cfg_marker_cm_canceltime = -1 [static]
Definition at line 975 of file packet-lustre.c.
int hf_lustre_cfg_marker_cm_comment = -1 [static]
Definition at line 925 of file packet-lustre.c.
int hf_lustre_cfg_marker_cm_createtime = -1 [static]
Definition at line 901 of file packet-lustre.c.
int hf_lustre_cfg_marker_cm_flags = -1 [static]
Definition at line 919 of file packet-lustre.c.
int hf_lustre_cfg_marker_cm_step = -1 [static]
Definition at line 967 of file packet-lustre.c.
int hf_lustre_cfg_marker_cm_tgtname = -1 [static]
Definition at line 891 of file packet-lustre.c.
int hf_lustre_cfg_marker_cm_vers = -1 [static]
Definition at line 888 of file packet-lustre.c.
int hf_lustre_cfg_marker_padding = -1 [static]
Definition at line 953 of file packet-lustre.c.
int hf_lustre_extra_padding = -1 [static]
Definition at line 443 of file packet-lustre.c.
int hf_lustre_fld_opc = -1 [static]
Definition at line 689 of file packet-lustre.c.
int hf_lustre_fld_range = -1 [static]
Definition at line 690 of file packet-lustre.c.
int hf_lustre_fld_range_end = -1 [static]
Definition at line 692 of file packet-lustre.c.
int hf_lustre_fld_range_flags = -1 [static]
Definition at line 694 of file packet-lustre.c.
int hf_lustre_fld_range_index = -1 [static]
Definition at line 693 of file packet-lustre.c.
int hf_lustre_fld_range_start = -1 [static]
Definition at line 691 of file packet-lustre.c.
int hf_lustre_ldlm_extent_end = -1 [static]
Definition at line 943 of file packet-lustre.c.
int hf_lustre_ldlm_extent_gid = -1 [static]
Definition at line 828 of file packet-lustre.c.
int hf_lustre_ldlm_extent_start = -1 [static]
Definition at line 860 of file packet-lustre.c.
int hf_lustre_ldlm_flock_blocking_export = -1 [static]
Definition at line 865 of file packet-lustre.c.
int hf_lustre_ldlm_flock_blocking_pid = -1 [static]
Definition at line 957 of file packet-lustre.c.
int hf_lustre_ldlm_flock_end = -1 [static]
Definition at line 987 of file packet-lustre.c.
int hf_lustre_ldlm_flock_pid = -1 [static]
Definition at line 964 of file packet-lustre.c.
int hf_lustre_ldlm_flock_start = -1 [static]
Definition at line 962 of file packet-lustre.c.
int hf_lustre_ldlm_inodebits_bits = -1 [static]
Definition at line 836 of file packet-lustre.c.
int hf_lustre_ldlm_intent = -1 [static]
Definition at line 448 of file packet-lustre.c.
int hf_lustre_ldlm_intent_opc = -1 [static]
Definition at line 849 of file packet-lustre.c.
int hf_lustre_ldlm_intent_opc_creat = -1 [static]
Definition at line 1015 of file packet-lustre.c.
int hf_lustre_ldlm_intent_opc_exec = -1 [static]
Definition at line 1021 of file packet-lustre.c.
int hf_lustre_ldlm_intent_opc_getattr = -1 [static]
Definition at line 1017 of file packet-lustre.c.
int hf_lustre_ldlm_intent_opc_getxattr = -1 [static]
Definition at line 1020 of file packet-lustre.c.
int hf_lustre_ldlm_intent_opc_lookup = -1 [static]
Definition at line 1018 of file packet-lustre.c.
int hf_lustre_ldlm_intent_opc_open = -1 [static]
Definition at line 1014 of file packet-lustre.c.
int hf_lustre_ldlm_intent_opc_pin = -1 [static]
Definition at line 1022 of file packet-lustre.c.
int hf_lustre_ldlm_intent_opc_readdir = -1 [static]
Definition at line 1016 of file packet-lustre.c.
int hf_lustre_ldlm_intent_opc_unlink = -1 [static]
Definition at line 1019 of file packet-lustre.c.
int hf_lustre_ldlm_lock_desc_l_granted_mode = -1 [static]
Definition at line 881 of file packet-lustre.c.
int hf_lustre_ldlm_lock_desc_l_policy_data = -1 [static]
Definition at line 877 of file packet-lustre.c.
int hf_lustre_ldlm_lock_desc_l_req_mode = -1 [static]
Definition at line 942 of file packet-lustre.c.
int hf_lustre_ldlm_lock_desc_l_resource = -1 [static]
Definition at line 984 of file packet-lustre.c.
int hf_lustre_ldlm_reply = -1 [static]
Definition at line 444 of file packet-lustre.c.
int hf_lustre_ldlm_reply_lock_desc = -1 [static]
Definition at line 916 of file packet-lustre.c.
int hf_lustre_ldlm_reply_lock_flags = -1 [static]
Definition at line 831 of file packet-lustre.c.
int hf_lustre_ldlm_reply_lock_handle = -1 [static]
Definition at line 931 of file packet-lustre.c.
int hf_lustre_ldlm_reply_lock_padding = -1 [static]
Definition at line 948 of file packet-lustre.c.
int hf_lustre_ldlm_reply_lock_policy_res1 = -1 [static]
Definition at line 820 of file packet-lustre.c.
int hf_lustre_ldlm_reply_lock_policy_res2 = -1 [static]
Definition at line 990 of file packet-lustre.c.
int hf_lustre_ldlm_request = -1 [static]
Definition at line 445 of file packet-lustre.c.
int hf_lustre_ldlm_request_lock_count = -1 [static]
Definition at line 986 of file packet-lustre.c.
int hf_lustre_ldlm_request_lock_desc = -1 [static]
Definition at line 921 of file packet-lustre.c.
int hf_lustre_ldlm_request_lock_flags = -1 [static]
Definition at line 869 of file packet-lustre.c.
int hf_lustre_ldlm_request_lock_handle = -1 [static]
Definition at line 834 of file packet-lustre.c.
int hf_lustre_ldlm_res_id_name = -1 [static]
Definition at line 930 of file packet-lustre.c.
int hf_lustre_ldlm_resource_desc_lr_name = -1 [static]
Definition at line 970 of file packet-lustre.c.
int hf_lustre_ldlm_resource_desc_lr_padding = -1 [static]
Definition at line 887 of file packet-lustre.c.
int hf_lustre_ldlm_resource_desc_lr_type = -1 [static]
Definition at line 993 of file packet-lustre.c.
int hf_lustre_ll_fid_f_type = -1 [static]
Definition at line 732 of file packet-lustre.c.
int hf_lustre_ll_fid_generation = -1 [static]
Definition at line 744 of file packet-lustre.c.
int hf_lustre_ll_fid_id = -1 [static]
Definition at line 804 of file packet-lustre.c.
int hf_lustre_llog_catid_lci_logid = -1 [static]
Definition at line 884 of file packet-lustre.c.
int hf_lustre_llog_catid_lci_padding1 = -1 [static]
Definition at line 903 of file packet-lustre.c.
int hf_lustre_llog_catid_lci_padding2 = -1 [static]
Definition at line 973 of file packet-lustre.c.
int hf_lustre_llog_catid_lci_padding3 = -1 [static]
Definition at line 839 of file packet-lustre.c.
int hf_lustre_llog_cookie = -1 [static]
Definition at line 464 of file packet-lustre.c.
int hf_lustre_llog_cookie_lgc_index = -1 [static]
Definition at line 914 of file packet-lustre.c.
int hf_lustre_llog_cookie_lgc_lgl = -1 [static]
Definition at line 842 of file packet-lustre.c.
int hf_lustre_llog_cookie_lgc_padding = -1 [static]
Definition at line 863 of file packet-lustre.c.
int hf_lustre_llog_cookie_lgc_subsys = -1 [static]
Definition at line 995 of file packet-lustre.c.
int hf_lustre_llog_gen_conn_cnt = -1 [static]
Definition at line 912 of file packet-lustre.c.
int hf_lustre_llog_gen_mnt_cnt = -1 [static]
Definition at line 981 of file packet-lustre.c.
int hf_lustre_llog_gen_rec_lgr_gen = -1 [static]
Definition at line 906 of file packet-lustre.c.
int hf_lustre_llog_gen_rec_lgr_hdr = -1 [static]
Definition at line 944 of file packet-lustre.c.
int hf_lustre_llog_gen_rec_lgr_tail = -1 [static]
Definition at line 838 of file packet-lustre.c.
int hf_lustre_llog_hdr_llh_flag_is_cat = -1 [static]
Definition at line 1024 of file packet-lustre.c.
int hf_lustre_llog_hdr_llh_flag_is_play = -1 [static]
Definition at line 1025 of file packet-lustre.c.
int hf_lustre_llog_hdr_llh_flag_zap_when_empty = -1 [static]
Definition at line 1023 of file packet-lustre.c.
int hf_lustre_llog_log_hdr_llh_bitmap = -1 [static]
Definition at line 844 of file packet-lustre.c.
int hf_lustre_llog_log_hdr_llh_bitmap_offset = -1 [static]
Definition at line 947 of file packet-lustre.c.
int hf_lustre_llog_log_hdr_llh_cat_idx = -1 [static]
Definition at line 946 of file packet-lustre.c.
int hf_lustre_llog_log_hdr_llh_count = -1 [static]
Definition at line 837 of file packet-lustre.c.
int hf_lustre_llog_log_hdr_llh_flags = -1 [static]
Definition at line 897 of file packet-lustre.c.
int hf_lustre_llog_log_hdr_llh_hdr = -1 [static]
Definition at line 996 of file packet-lustre.c.
int hf_lustre_llog_log_hdr_llh_reserved = -1 [static]
Definition at line 997 of file packet-lustre.c.
int hf_lustre_llog_log_hdr_llh_size = -1 [static]
Definition at line 873 of file packet-lustre.c.
int hf_lustre_llog_log_hdr_llh_tail = -1 [static]
Definition at line 858 of file packet-lustre.c.
int hf_lustre_llog_log_hdr_llh_tgtuuid = -1 [static]
Definition at line 966 of file packet-lustre.c.
int hf_lustre_llog_log_hdr_llh_timestamp = -1 [static]
Definition at line 972 of file packet-lustre.c.
int hf_lustre_llog_logid_lgl_ogen = -1 [static]
Definition at line 924 of file packet-lustre.c.
int hf_lustre_llog_logid_lgl_oid = -1 [static]
Definition at line 835 of file packet-lustre.c.
int hf_lustre_llog_logid_lgl_oseq = -1 [static]
Definition at line 862 of file packet-lustre.c.
int hf_lustre_llog_logid_rec = -1 [static]
Definition at line 456 of file packet-lustre.c.
int hf_lustre_llog_logid_rec_lid_hdr = -1 [static]
Definition at line 893 of file packet-lustre.c.
int hf_lustre_llog_logid_rec_lid_id = -1 [static]
Definition at line 979 of file packet-lustre.c.
int hf_lustre_llog_logid_rec_lid_tail = -1 [static]
Definition at line 936 of file packet-lustre.c.
int hf_lustre_llog_logid_rec_padding1 = -1 [static]
Definition at line 823 of file packet-lustre.c.
int hf_lustre_llog_logid_rec_padding2 = -1 [static]
Definition at line 847 of file packet-lustre.c.
int hf_lustre_llog_logid_rec_padding3 = -1 [static]
Definition at line 896 of file packet-lustre.c.
int hf_lustre_llog_logid_rec_padding4 = -1 [static]
Definition at line 950 of file packet-lustre.c.
int hf_lustre_llog_logid_rec_padding5 = -1 [static]
Definition at line 848 of file packet-lustre.c.
int hf_lustre_llog_rec_hdr_lrh_index = -1 [static]
Definition at line 909 of file packet-lustre.c.
int hf_lustre_llog_rec_hdr_lrh_len = -1 [static]
Definition at line 851 of file packet-lustre.c.
int hf_lustre_llog_rec_hdr_lrh_type = -1 [static]
Definition at line 850 of file packet-lustre.c.
int hf_lustre_llog_rec_hdr_padding = -1 [static]
Definition at line 826 of file packet-lustre.c.
int hf_lustre_llog_rec_tail_lrt_index = -1 [static]
Definition at line 885 of file packet-lustre.c.
int hf_lustre_llog_rec_tail_lrt_len = -1 [static]
Definition at line 971 of file packet-lustre.c.
int hf_lustre_llog_setattr_rec_lsr_gid = -1 [static]
Definition at line 951 of file packet-lustre.c.
int hf_lustre_llog_setattr_rec_lsr_hdr = -1 [static]
Definition at line 910 of file packet-lustre.c.
int hf_lustre_llog_setattr_rec_lsr_ogen = -1 [static]
Definition at line 892 of file packet-lustre.c.
int hf_lustre_llog_setattr_rec_lsr_oid = -1 [static]
Definition at line 898 of file packet-lustre.c.
int hf_lustre_llog_setattr_rec_lsr_tail = -1 [static]
Definition at line 994 of file packet-lustre.c.
int hf_lustre_llog_setattr_rec_lsr_uid = -1 [static]
Definition at line 852 of file packet-lustre.c.
int hf_lustre_llog_setattr_rec_padding = -1 [static]
Definition at line 841 of file packet-lustre.c.
int hf_lustre_llog_size_change_rec_lsc_fid = -1 [static]
Definition at line 825 of file packet-lustre.c.
int hf_lustre_llog_size_change_rec_lsc_hdr = -1 [static]
Definition at line 861 of file packet-lustre.c.
int hf_lustre_llog_size_change_rec_lsc_io_epoch = -1 [static]
Definition at line 818 of file packet-lustre.c.
int hf_lustre_llog_size_change_rec_lsc_tail = -1 [static]
Definition at line 982 of file packet-lustre.c.
int hf_lustre_llog_size_change_rec_padding = -1 [static]
Definition at line 899 of file packet-lustre.c.
int hf_lustre_llog_unlink_rec_lur_hdr = -1 [static]
Definition at line 889 of file packet-lustre.c.
int hf_lustre_llog_unlink_rec_lur_ogen = -1 [static]
Definition at line 918 of file packet-lustre.c.
int hf_lustre_llog_unlink_rec_lur_oid = -1 [static]
Definition at line 926 of file packet-lustre.c.
int hf_lustre_llog_unlink_rec_lur_tail = -1 [static]
Definition at line 817 of file packet-lustre.c.
int hf_lustre_llog_unlink_rec_padding = -1 [static]
Definition at line 941 of file packet-lustre.c.
int hf_lustre_llogd_body = -1 [static]
Definition at line 454 of file packet-lustre.c.
int hf_lustre_llogd_body_lgd_ctxt_idx = -1 [static]
Definition at line 991 of file packet-lustre.c.
int hf_lustre_llogd_body_lgd_cur_offset = -1 [static]
Definition at line 959 of file packet-lustre.c.
int hf_lustre_llogd_body_lgd_index = -1 [static]
Definition at line 890 of file packet-lustre.c.
int hf_lustre_llogd_body_lgd_len = -1 [static]
Definition at line 821 of file packet-lustre.c.
int hf_lustre_llogd_body_lgd_llh_flags = -1 [static]
Definition at line 945 of file packet-lustre.c.
int hf_lustre_llogd_body_lgd_logid = -1 [static]
Definition at line 872 of file packet-lustre.c.
int hf_lustre_llogd_body_lgd_saved_index = -1 [static]
Definition at line 932 of file packet-lustre.c.
int hf_lustre_llogd_chunk = -1 [static]
Definition at line 457 of file packet-lustre.c.
int hf_lustre_llogd_client = -1 [static]
Definition at line 459 of file packet-lustre.c.
int hf_lustre_llogd_conn_body_lgdc_ctxt_idx = -1 [static]
Definition at line 974 of file packet-lustre.c.
int hf_lustre_llogd_conn_body_lgdc_gen = -1 [static]
Definition at line 857 of file packet-lustre.c.
int hf_lustre_llogd_conn_body_lgdc_logid = -1 [static]
Definition at line 956 of file packet-lustre.c.
int hf_lustre_llogd_keyword = -1 [static]
Definition at line 458 of file packet-lustre.c.
int hf_lustre_llogd_log_hdr = -1 [static]
Definition at line 455 of file packet-lustre.c.
int hf_lustre_llogd_name = -1 [static]
Definition at line 460 of file packet-lustre.c.
int hf_lustre_lov_desc_ld_active_tgt_count = -1 [static]
Definition at line 904 of file packet-lustre.c.
int hf_lustre_lov_desc_ld_default_stripe_count = -1 [static]
Definition at line 886 of file packet-lustre.c.
int hf_lustre_lov_desc_ld_default_stripe_offset = -1 [static]
Definition at line 969 of file packet-lustre.c.
int hf_lustre_lov_desc_ld_default_stripe_size = -1 [static]
Definition at line 965 of file packet-lustre.c.
int hf_lustre_lov_desc_ld_padding_0 = -1 [static]
Definition at line 917 of file packet-lustre.c.
int hf_lustre_lov_desc_ld_padding_1 = -1 [static]
Definition at line 853 of file packet-lustre.c.
int hf_lustre_lov_desc_ld_padding_2 = -1 [static]
Definition at line 935 of file packet-lustre.c.
int hf_lustre_lov_desc_ld_pattern = -1 [static]
Definition at line 866 of file packet-lustre.c.
int hf_lustre_lov_desc_ld_qos_maxage = -1 [static]
Definition at line 992 of file packet-lustre.c.
int hf_lustre_lov_desc_ld_tgt_count = -1 [static]
Definition at line 958 of file packet-lustre.c.
int hf_lustre_lov_desc_ld_uuid = -1 [static]
Definition at line 915 of file packet-lustre.c.
int hf_lustre_lov_mds_md_v1 = -1 [static]
Definition at line 463 of file packet-lustre.c.
int hf_lustre_lov_mds_md_v1_lmm_magic = -1 [static]
Definition at line 738 of file packet-lustre.c.
int hf_lustre_lov_mds_md_v1_lmm_object_id = -1 [static]
Definition at line 798 of file packet-lustre.c.
int hf_lustre_lov_mds_md_v1_lmm_object_seq = -1 [static]
Definition at line 752 of file packet-lustre.c.
int hf_lustre_lov_mds_md_v1_lmm_objects = -1 [static]
Definition at line 779 of file packet-lustre.c.
int hf_lustre_lov_mds_md_v1_lmm_pattern = -1 [static]
Definition at line 784 of file packet-lustre.c.
int hf_lustre_lov_mds_md_v1_lmm_stripe_count = -1 [static]
Definition at line 760 of file packet-lustre.c.
int hf_lustre_lov_mds_md_v1_lmm_stripe_size = -1 [static]
Definition at line 730 of file packet-lustre.c.
int hf_lustre_lov_ost_data_v1_l_object_id = -1 [static]
Definition at line 775 of file packet-lustre.c.
int hf_lustre_lov_ost_data_v1_l_object_seq = -1 [static]
Definition at line 751 of file packet-lustre.c.
int hf_lustre_lov_ost_data_v1_l_ost_gen = -1 [static]
Definition at line 776 of file packet-lustre.c.
int hf_lustre_lov_ost_data_v1_l_ost_idx = -1 [static]
Definition at line 808 of file packet-lustre.c.
int hf_lustre_lu_ladvise = -1 [static]
Definition at line 1026 of file packet-lustre.c.
int hf_lustre_lu_ladvise_lla_advice = -1 [static]
Definition at line 1029 of file packet-lustre.c.
int hf_lustre_lu_ladvise_lla_end = -1 [static]
Definition at line 1028 of file packet-lustre.c.
int hf_lustre_lu_ladvise_lla_padding = -1 [static]
Definition at line 1030 of file packet-lustre.c.
int hf_lustre_lu_ladvise_lla_start = -1 [static]
Definition at line 1027 of file packet-lustre.c.
int hf_lustre_lustre_handle_cookie = -1 [static]
Definition at line 715 of file packet-lustre.c.
int hf_lustre_lustre_msg_v1_lm_bufcount = -1 [static]
Definition at line 718 of file packet-lustre.c.
int hf_lustre_lustre_msg_v1_lm_buflens = -1 [static]
Definition at line 766 of file packet-lustre.c.
int hf_lustre_lustre_msg_v1_lm_conn_cnt = -1 [static]
Definition at line 769 of file packet-lustre.c.
int hf_lustre_lustre_msg_v1_lm_flags = -1 [static]
Definition at line 761 of file packet-lustre.c.
int hf_lustre_lustre_msg_v1_lm_handle = -1 [static]
Definition at line 724 of file packet-lustre.c.
int hf_lustre_lustre_msg_v1_lm_last_committed = -1 [static]
Definition at line 762 of file packet-lustre.c.
int hf_lustre_lustre_msg_v1_lm_last_xid = -1 [static]
Definition at line 731 of file packet-lustre.c.
int hf_lustre_lustre_msg_v1_lm_magic = -1 [static]
Definition at line 816 of file packet-lustre.c.
int hf_lustre_lustre_msg_v1_lm_opc = -1 [static]
Definition at line 785 of file packet-lustre.c.
int hf_lustre_lustre_msg_v1_lm_status = -1 [static]
Definition at line 735 of file packet-lustre.c.
int hf_lustre_lustre_msg_v1_lm_transno = -1 [static]
Definition at line 783 of file packet-lustre.c.
int hf_lustre_lustre_msg_v1_lm_type = -1 [static]
Definition at line 736 of file packet-lustre.c.
int hf_lustre_lustre_msg_v1_lm_version = -1 [static]
Definition at line 788 of file packet-lustre.c.
int hf_lustre_lustre_msg_v2_lm_bufcount = -1 [static]
Definition at line 813 of file packet-lustre.c.
int hf_lustre_lustre_msg_v2_lm_buflens = -1 [static]
Definition at line 734 of file packet-lustre.c.
int hf_lustre_lustre_msg_v2_lm_cksum = -1 [static]
Definition at line 733 of file packet-lustre.c.
int hf_lustre_lustre_msg_v2_lm_flags = -1 [static]
Definition at line 757 of file packet-lustre.c.
int hf_lustre_lustre_msg_v2_lm_magic = -1 [static]
Definition at line 797 of file packet-lustre.c.
int hf_lustre_lustre_msg_v2_lm_padding_2 = -1 [static]
Definition at line 806 of file packet-lustre.c.
int hf_lustre_lustre_msg_v2_lm_padding_3 = -1 [static]
Definition at line 747 of file packet-lustre.c.
int hf_lustre_lustre_msg_v2_lm_repsize = -1 [static]
Definition at line 729 of file packet-lustre.c.
int hf_lustre_lustre_msg_v2_lm_secflvr = -1 [static]
Definition at line 782 of file packet-lustre.c.
int hf_lustre_mds_md_data = -1 [static]
Definition at line 465 of file packet-lustre.c.
int hf_lustre_mds_reint_opcode = -1 [static]
Definition at line 466 of file packet-lustre.c.
int hf_lustre_mds_xattr_eadata = -1 [static]
Definition at line 467 of file packet-lustre.c.
int hf_lustre_mds_xattr_name = -1 [static]
Definition at line 462 of file packet-lustre.c.
int hf_lustre_mdt_body = -1 [static]
Definition at line 492 of file packet-lustre.c.
int hf_lustre_mdt_body_aclsize = -1 [static]
Definition at line 516 of file packet-lustre.c.
int hf_lustre_mdt_body_atime = -1 [static]
Definition at line 499 of file packet-lustre.c.
int hf_lustre_mdt_body_blocks = -1 [static]
Definition at line 501 of file packet-lustre.c.
int hf_lustre_mdt_body_capability = -1 [static]
Definition at line 506 of file packet-lustre.c.
int hf_lustre_mdt_body_ctime = -1 [static]
Definition at line 500 of file packet-lustre.c.
int hf_lustre_mdt_body_eadatasize = -1 [static]
Definition at line 515 of file packet-lustre.c.
int hf_lustre_mdt_body_fid1 = -1 [static]
Definition at line 493 of file packet-lustre.c.
int hf_lustre_mdt_body_fid2 = -1 [static]
Definition at line 494 of file packet-lustre.c.
int hf_lustre_mdt_body_flags = -1 [static]
Definition at line 510 of file packet-lustre.c.
int hf_lustre_mdt_body_fsgid = -1 [static]
Definition at line 505 of file packet-lustre.c.
int hf_lustre_mdt_body_fsuid = -1 [static]
Definition at line 504 of file packet-lustre.c.
int hf_lustre_mdt_body_generation = -1 [static]
Definition at line 513 of file packet-lustre.c.
int hf_lustre_mdt_body_gid = -1 [static]
Definition at line 509 of file packet-lustre.c.
int hf_lustre_mdt_body_gid_h = -1 [static]
Definition at line 520 of file packet-lustre.c.
int hf_lustre_mdt_body_handle = -1 [static]
Definition at line 495 of file packet-lustre.c.
int hf_lustre_mdt_body_ino = -1 [static]
Definition at line 503 of file packet-lustre.c.
int hf_lustre_mdt_body_ioepoch = -1 [static]
Definition at line 502 of file packet-lustre.c.
int hf_lustre_mdt_body_max_cookiesize = -1 [static]
Definition at line 518 of file packet-lustre.c.
int hf_lustre_mdt_body_max_mdsize = -1 [static]
Definition at line 517 of file packet-lustre.c.
int hf_lustre_mdt_body_mode = -1 [static]
Definition at line 507 of file packet-lustre.c.
int hf_lustre_mdt_body_mtime = -1 [static]
Definition at line 498 of file packet-lustre.c.
int hf_lustre_mdt_body_nlink = -1 [static]
Definition at line 512 of file packet-lustre.c.
int hf_lustre_mdt_body_padding_10 = -1 [static]
Definition at line 526 of file packet-lustre.c.
int hf_lustre_mdt_body_padding_5 = -1 [static]
Definition at line 521 of file packet-lustre.c.
int hf_lustre_mdt_body_padding_6 = -1 [static]
Definition at line 522 of file packet-lustre.c.
int hf_lustre_mdt_body_padding_7 = -1 [static]
Definition at line 523 of file packet-lustre.c.
int hf_lustre_mdt_body_padding_8 = -1 [static]
Definition at line 524 of file packet-lustre.c.
int hf_lustre_mdt_body_padding_9 = -1 [static]
Definition at line 525 of file packet-lustre.c.
int hf_lustre_mdt_body_rdev = -1 [static]
Definition at line 511 of file packet-lustre.c.
int hf_lustre_mdt_body_size = -1 [static]
Definition at line 497 of file packet-lustre.c.
int hf_lustre_mdt_body_suppgid = -1 [static]
Definition at line 514 of file packet-lustre.c.
int hf_lustre_mdt_body_uid = -1 [static]
Definition at line 508 of file packet-lustre.c.
int hf_lustre_mdt_body_uid_h = -1 [static]
Definition at line 519 of file packet-lustre.c.
int hf_lustre_mdt_body_valid = -1 [static]
Definition at line 496 of file packet-lustre.c.
int hf_lustre_mdt_ioepoch = -1 [static]
Definition at line 696 of file packet-lustre.c.
int hf_lustre_mdt_ioepoch_flags = -1 [static]
Definition at line 699 of file packet-lustre.c.
int hf_lustre_mdt_ioepoch_handle = -1 [static]
Definition at line 697 of file packet-lustre.c.
int hf_lustre_mdt_ioepoch_ioepoch = -1 [static]
Definition at line 698 of file packet-lustre.c.
int hf_lustre_mdt_ioepoch_padding = -1 [static]
Definition at line 700 of file packet-lustre.c.
int hf_lustre_mdt_rec_create = -1 [static]
Definition at line 555 of file packet-lustre.c.
int hf_lustre_mdt_rec_create_cr_bias = -1 [static]
Definition at line 574 of file packet-lustre.c.
int hf_lustre_mdt_rec_create_cr_cap = -1 [static]
Definition at line 557 of file packet-lustre.c.
int hf_lustre_mdt_rec_create_cr_fid1 = -1 [static]
Definition at line 566 of file packet-lustre.c.
int hf_lustre_mdt_rec_create_cr_fid2 = -1 [static]
Definition at line 567 of file packet-lustre.c.
int hf_lustre_mdt_rec_create_cr_flags_h = -1 [static]
Definition at line 576 of file packet-lustre.c.
int hf_lustre_mdt_rec_create_cr_flags_l = -1 [static]
Definition at line 575 of file packet-lustre.c.
int hf_lustre_mdt_rec_create_cr_fsgid = -1 [static]
Definition at line 560 of file packet-lustre.c.
int hf_lustre_mdt_rec_create_cr_fsgid_h = -1 [static]
Definition at line 561 of file packet-lustre.c.
int hf_lustre_mdt_rec_create_cr_fsuid = -1 [static]
Definition at line 558 of file packet-lustre.c.
int hf_lustre_mdt_rec_create_cr_fsuid_h = -1 [static]
Definition at line 559 of file packet-lustre.c.
int hf_lustre_mdt_rec_create_cr_ioepoch = -1 [static]
Definition at line 571 of file packet-lustre.c.
int hf_lustre_mdt_rec_create_cr_mode = -1 [static]
Definition at line 573 of file packet-lustre.c.
int hf_lustre_mdt_rec_create_cr_old_handle = -1 [static]
Definition at line 568 of file packet-lustre.c.
int hf_lustre_mdt_rec_create_cr_opcode = -1 [static]
Definition at line 556 of file packet-lustre.c.
int hf_lustre_mdt_rec_create_cr_padding_1 = -1 [static]
Definition at line 572 of file packet-lustre.c.
int hf_lustre_mdt_rec_create_cr_padding_4 = -1 [static]
Definition at line 578 of file packet-lustre.c.
int hf_lustre_mdt_rec_create_cr_rdev = -1 [static]
Definition at line 570 of file packet-lustre.c.
int hf_lustre_mdt_rec_create_cr_suppgid1 = -1 [static]
Definition at line 562 of file packet-lustre.c.
int hf_lustre_mdt_rec_create_cr_suppgid1_h = -1 [static]
Definition at line 563 of file packet-lustre.c.
int hf_lustre_mdt_rec_create_cr_suppgid2 = -1 [static]
Definition at line 564 of file packet-lustre.c.
int hf_lustre_mdt_rec_create_cr_suppgid2_h = -1 [static]
Definition at line 565 of file packet-lustre.c.
int hf_lustre_mdt_rec_create_cr_time = -1 [static]
Definition at line 569 of file packet-lustre.c.
int hf_lustre_mdt_rec_create_cr_umask = -1 [static]
Definition at line 577 of file packet-lustre.c.
int hf_lustre_mdt_rec_link = -1 [static]
Definition at line 580 of file packet-lustre.c.
int hf_lustre_mdt_rec_link_lk_bias = -1 [static]
Definition at line 598 of file packet-lustre.c.
int hf_lustre_mdt_rec_link_lk_cap = -1 [static]
Definition at line 582 of file packet-lustre.c.
int hf_lustre_mdt_rec_link_lk_fid1 = -1 [static]
Definition at line 591 of file packet-lustre.c.
int hf_lustre_mdt_rec_link_lk_fid2 = -1 [static]
Definition at line 592 of file packet-lustre.c.
int hf_lustre_mdt_rec_link_lk_fsgid = -1 [static]
Definition at line 585 of file packet-lustre.c.
int hf_lustre_mdt_rec_link_lk_fsgid_h = -1 [static]
Definition at line 586 of file packet-lustre.c.
int hf_lustre_mdt_rec_link_lk_fsuid = -1 [static]
Definition at line 583 of file packet-lustre.c.
int hf_lustre_mdt_rec_link_lk_fsuid_h = -1 [static]
Definition at line 584 of file packet-lustre.c.
int hf_lustre_mdt_rec_link_lk_opcode = -1 [static]
Definition at line 581 of file packet-lustre.c.
int hf_lustre_mdt_rec_link_lk_padding_1 = -1 [static]
Definition at line 594 of file packet-lustre.c.
int hf_lustre_mdt_rec_link_lk_padding_2 = -1 [static]
Definition at line 595 of file packet-lustre.c.
int hf_lustre_mdt_rec_link_lk_padding_3 = -1 [static]
Definition at line 596 of file packet-lustre.c.
int hf_lustre_mdt_rec_link_lk_padding_4 = -1 [static]
Definition at line 597 of file packet-lustre.c.
int hf_lustre_mdt_rec_link_lk_padding_5 = -1 [static]
Definition at line 599 of file packet-lustre.c.
int hf_lustre_mdt_rec_link_lk_padding_6 = -1 [static]
Definition at line 600 of file packet-lustre.c.
int hf_lustre_mdt_rec_link_lk_padding_7 = -1 [static]
Definition at line 601 of file packet-lustre.c.
int hf_lustre_mdt_rec_link_lk_padding_8 = -1 [static]
Definition at line 602 of file packet-lustre.c.
int hf_lustre_mdt_rec_link_lk_padding_9 = -1 [static]
Definition at line 603 of file packet-lustre.c.
int hf_lustre_mdt_rec_link_lk_suppgid1 = -1 [static]
Definition at line 587 of file packet-lustre.c.
int hf_lustre_mdt_rec_link_lk_suppgid1_h = -1 [static]
Definition at line 588 of file packet-lustre.c.
int hf_lustre_mdt_rec_link_lk_suppgid2 = -1 [static]
Definition at line 589 of file packet-lustre.c.
int hf_lustre_mdt_rec_link_lk_suppgid2_h = -1 [static]
Definition at line 590 of file packet-lustre.c.
int hf_lustre_mdt_rec_link_lk_time = -1 [static]
Definition at line 593 of file packet-lustre.c.
int hf_lustre_mdt_rec_rename = -1 [static]
Definition at line 630 of file packet-lustre.c.
int hf_lustre_mdt_rec_rename_rn_bias = -1 [static]
Definition at line 648 of file packet-lustre.c.
int hf_lustre_mdt_rec_rename_rn_cap = -1 [static]
Definition at line 632 of file packet-lustre.c.
int hf_lustre_mdt_rec_rename_rn_fid1 = -1 [static]
Definition at line 641 of file packet-lustre.c.
int hf_lustre_mdt_rec_rename_rn_fid2 = -1 [static]
Definition at line 642 of file packet-lustre.c.
int hf_lustre_mdt_rec_rename_rn_fsgid = -1 [static]
Definition at line 635 of file packet-lustre.c.
int hf_lustre_mdt_rec_rename_rn_fsgid_h = -1 [static]
Definition at line 636 of file packet-lustre.c.
int hf_lustre_mdt_rec_rename_rn_fsuid = -1 [static]
Definition at line 633 of file packet-lustre.c.
int hf_lustre_mdt_rec_rename_rn_fsuid_h = -1 [static]
Definition at line 634 of file packet-lustre.c.
int hf_lustre_mdt_rec_rename_rn_mode = -1 [static]
Definition at line 649 of file packet-lustre.c.
int hf_lustre_mdt_rec_rename_rn_opcode = -1 [static]
Definition at line 631 of file packet-lustre.c.
int hf_lustre_mdt_rec_rename_rn_padding_1 = -1 [static]
Definition at line 644 of file packet-lustre.c.
int hf_lustre_mdt_rec_rename_rn_padding_2 = -1 [static]
Definition at line 645 of file packet-lustre.c.
int hf_lustre_mdt_rec_rename_rn_padding_3 = -1 [static]
Definition at line 646 of file packet-lustre.c.
int hf_lustre_mdt_rec_rename_rn_padding_4 = -1 [static]
Definition at line 647 of file packet-lustre.c.
int hf_lustre_mdt_rec_rename_rn_padding_5 = -1 [static]
Definition at line 650 of file packet-lustre.c.
int hf_lustre_mdt_rec_rename_rn_padding_6 = -1 [static]
Definition at line 651 of file packet-lustre.c.
int hf_lustre_mdt_rec_rename_rn_padding_7 = -1 [static]
Definition at line 652 of file packet-lustre.c.
int hf_lustre_mdt_rec_rename_rn_padding_8 = -1 [static]
Definition at line 653 of file packet-lustre.c.
int hf_lustre_mdt_rec_rename_rn_suppgid1 = -1 [static]
Definition at line 637 of file packet-lustre.c.
int hf_lustre_mdt_rec_rename_rn_suppgid1_h = -1 [static]
Definition at line 638 of file packet-lustre.c.
int hf_lustre_mdt_rec_rename_rn_suppgid2 = -1 [static]
Definition at line 639 of file packet-lustre.c.
int hf_lustre_mdt_rec_rename_rn_suppgid2_h = -1 [static]
Definition at line 640 of file packet-lustre.c.
int hf_lustre_mdt_rec_rename_rn_time = -1 [static]
Definition at line 643 of file packet-lustre.c.
int hf_lustre_mdt_rec_setattr = -1 [static]
Definition at line 528 of file packet-lustre.c.
int hf_lustre_mdt_rec_setattr_sa_atime = -1 [static]
Definition at line 546 of file packet-lustre.c.
int hf_lustre_mdt_rec_setattr_sa_attr_flags = -1 [static]
Definition at line 548 of file packet-lustre.c.
int hf_lustre_mdt_rec_setattr_sa_blocks = -1 [static]
Definition at line 544 of file packet-lustre.c.
int hf_lustre_mdt_rec_setattr_sa_cap = -1 [static]
Definition at line 530 of file packet-lustre.c.
int hf_lustre_mdt_rec_setattr_sa_ctime = -1 [static]
Definition at line 547 of file packet-lustre.c.
int hf_lustre_mdt_rec_setattr_sa_fid = -1 [static]
Definition at line 539 of file packet-lustre.c.
int hf_lustre_mdt_rec_setattr_sa_fsgid = -1 [static]
Definition at line 533 of file packet-lustre.c.
int hf_lustre_mdt_rec_setattr_sa_fsgid_h = -1 [static]
Definition at line 534 of file packet-lustre.c.
int hf_lustre_mdt_rec_setattr_sa_fsuid = -1 [static]
Definition at line 531 of file packet-lustre.c.
int hf_lustre_mdt_rec_setattr_sa_fsuid_h = -1 [static]
Definition at line 532 of file packet-lustre.c.
int hf_lustre_mdt_rec_setattr_sa_gid = -1 [static]
Definition at line 542 of file packet-lustre.c.
int hf_lustre_mdt_rec_setattr_sa_mode = -1 [static]
Definition at line 549 of file packet-lustre.c.
int hf_lustre_mdt_rec_setattr_sa_mtime = -1 [static]
Definition at line 545 of file packet-lustre.c.
int hf_lustre_mdt_rec_setattr_sa_opcode = -1 [static]
Definition at line 529 of file packet-lustre.c.
int hf_lustre_mdt_rec_setattr_sa_padding_1 = -1 [static]
Definition at line 537 of file packet-lustre.c.
int hf_lustre_mdt_rec_setattr_sa_padding_1_h = -1 [static]
Definition at line 538 of file packet-lustre.c.
int hf_lustre_mdt_rec_setattr_sa_padding_2 = -1 [static]
Definition at line 550 of file packet-lustre.c.
int hf_lustre_mdt_rec_setattr_sa_padding_3 = -1 [static]
Definition at line 551 of file packet-lustre.c.
int hf_lustre_mdt_rec_setattr_sa_padding_4 = -1 [static]
Definition at line 552 of file packet-lustre.c.
int hf_lustre_mdt_rec_setattr_sa_padding_5 = -1 [static]
Definition at line 553 of file packet-lustre.c.
int hf_lustre_mdt_rec_setattr_sa_size = -1 [static]
Definition at line 543 of file packet-lustre.c.
int hf_lustre_mdt_rec_setattr_sa_suppgid = -1 [static]
Definition at line 535 of file packet-lustre.c.
int hf_lustre_mdt_rec_setattr_sa_suppgid_h = -1 [static]
Definition at line 536 of file packet-lustre.c.
int hf_lustre_mdt_rec_setattr_sa_uid = -1 [static]
Definition at line 541 of file packet-lustre.c.
int hf_lustre_mdt_rec_setattr_sa_valid = -1 [static]
Definition at line 540 of file packet-lustre.c.
int hf_lustre_mdt_rec_setxattr = -1 [static]
Definition at line 655 of file packet-lustre.c.
int hf_lustre_mdt_rec_setxattr_sx_cap = -1 [static]
Definition at line 657 of file packet-lustre.c.
int hf_lustre_mdt_rec_setxattr_sx_fid = -1 [static]
Definition at line 666 of file packet-lustre.c.
int hf_lustre_mdt_rec_setxattr_sx_flags = -1 [static]
Definition at line 676 of file packet-lustre.c.
int hf_lustre_mdt_rec_setxattr_sx_fsgid = -1 [static]
Definition at line 660 of file packet-lustre.c.
int hf_lustre_mdt_rec_setxattr_sx_fsgid_h = -1 [static]
Definition at line 661 of file packet-lustre.c.
int hf_lustre_mdt_rec_setxattr_sx_fsuid = -1 [static]
Definition at line 658 of file packet-lustre.c.
int hf_lustre_mdt_rec_setxattr_sx_fsuid_h = -1 [static]
Definition at line 659 of file packet-lustre.c.
int hf_lustre_mdt_rec_setxattr_sx_opcode = -1 [static]
Definition at line 656 of file packet-lustre.c.
int hf_lustre_mdt_rec_setxattr_sx_padding_1 = -1 [static]
Definition at line 667 of file packet-lustre.c.
int hf_lustre_mdt_rec_setxattr_sx_padding_10 = -1 [static]
Definition at line 679 of file packet-lustre.c.
int hf_lustre_mdt_rec_setxattr_sx_padding_11 = -1 [static]
Definition at line 680 of file packet-lustre.c.
int hf_lustre_mdt_rec_setxattr_sx_padding_2 = -1 [static]
Definition at line 668 of file packet-lustre.c.
int hf_lustre_mdt_rec_setxattr_sx_padding_3 = -1 [static]
Definition at line 669 of file packet-lustre.c.
int hf_lustre_mdt_rec_setxattr_sx_padding_5 = -1 [static]
Definition at line 672 of file packet-lustre.c.
int hf_lustre_mdt_rec_setxattr_sx_padding_6 = -1 [static]
Definition at line 673 of file packet-lustre.c.
int hf_lustre_mdt_rec_setxattr_sx_padding_7 = -1 [static]
Definition at line 674 of file packet-lustre.c.
int hf_lustre_mdt_rec_setxattr_sx_padding_8 = -1 [static]
Definition at line 677 of file packet-lustre.c.
int hf_lustre_mdt_rec_setxattr_sx_padding_9 = -1 [static]
Definition at line 678 of file packet-lustre.c.
int hf_lustre_mdt_rec_setxattr_sx_size = -1 [static]
Definition at line 675 of file packet-lustre.c.
int hf_lustre_mdt_rec_setxattr_sx_suppgid1 = -1 [static]
Definition at line 662 of file packet-lustre.c.
int hf_lustre_mdt_rec_setxattr_sx_suppgid1_h = -1 [static]
Definition at line 663 of file packet-lustre.c.
int hf_lustre_mdt_rec_setxattr_sx_suppgid2 = -1 [static]
Definition at line 664 of file packet-lustre.c.
int hf_lustre_mdt_rec_setxattr_sx_suppgid2_h = -1 [static]
Definition at line 665 of file packet-lustre.c.
int hf_lustre_mdt_rec_setxattr_sx_time = -1 [static]
Definition at line 671 of file packet-lustre.c.
int hf_lustre_mdt_rec_setxattr_sx_valid = -1 [static]
Definition at line 670 of file packet-lustre.c.
int hf_lustre_mdt_rec_unlink = -1 [static]
Definition at line 605 of file packet-lustre.c.
int hf_lustre_mdt_rec_unlink_ul_bias = -1 [static]
Definition at line 623 of file packet-lustre.c.
int hf_lustre_mdt_rec_unlink_ul_cap = -1 [static]
Definition at line 607 of file packet-lustre.c.
int hf_lustre_mdt_rec_unlink_ul_fid1 = -1 [static]
Definition at line 616 of file packet-lustre.c.
int hf_lustre_mdt_rec_unlink_ul_fid2 = -1 [static]
Definition at line 617 of file packet-lustre.c.
int hf_lustre_mdt_rec_unlink_ul_fsgid = -1 [static]
Definition at line 610 of file packet-lustre.c.
int hf_lustre_mdt_rec_unlink_ul_fsgid_h = -1 [static]
Definition at line 611 of file packet-lustre.c.
int hf_lustre_mdt_rec_unlink_ul_fsuid = -1 [static]
Definition at line 608 of file packet-lustre.c.
int hf_lustre_mdt_rec_unlink_ul_fsuid_h = -1 [static]
Definition at line 609 of file packet-lustre.c.
int hf_lustre_mdt_rec_unlink_ul_mode = -1 [static]
Definition at line 624 of file packet-lustre.c.
int hf_lustre_mdt_rec_unlink_ul_opcode = -1 [static]
Definition at line 606 of file packet-lustre.c.
int hf_lustre_mdt_rec_unlink_ul_padding_2 = -1 [static]
Definition at line 619 of file packet-lustre.c.
int hf_lustre_mdt_rec_unlink_ul_padding_3 = -1 [static]
Definition at line 620 of file packet-lustre.c.
int hf_lustre_mdt_rec_unlink_ul_padding_4 = -1 [static]
Definition at line 621 of file packet-lustre.c.
int hf_lustre_mdt_rec_unlink_ul_padding_5 = -1 [static]
Definition at line 622 of file packet-lustre.c.
int hf_lustre_mdt_rec_unlink_ul_padding_6 = -1 [static]
Definition at line 625 of file packet-lustre.c.
int hf_lustre_mdt_rec_unlink_ul_padding_7 = -1 [static]
Definition at line 626 of file packet-lustre.c.
int hf_lustre_mdt_rec_unlink_ul_padding_8 = -1 [static]
Definition at line 627 of file packet-lustre.c.
int hf_lustre_mdt_rec_unlink_ul_padding_9 = -1 [static]
Definition at line 628 of file packet-lustre.c.
int hf_lustre_mdt_rec_unlink_ul_suppgid1 = -1 [static]
Definition at line 612 of file packet-lustre.c.
int hf_lustre_mdt_rec_unlink_ul_suppgid1_h = -1 [static]
Definition at line 613 of file packet-lustre.c.
int hf_lustre_mdt_rec_unlink_ul_suppgid2 = -1 [static]
Definition at line 614 of file packet-lustre.c.
int hf_lustre_mdt_rec_unlink_ul_suppgid2_h = -1 [static]
Definition at line 615 of file packet-lustre.c.
int hf_lustre_mdt_rec_unlink_ul_time = -1 [static]
Definition at line 618 of file packet-lustre.c.
int hf_lustre_mgs_config_body = -1 [static]
Definition at line 476 of file packet-lustre.c.
int hf_lustre_mgs_config_body_bits = -1 [static]
Definition at line 481 of file packet-lustre.c.
int hf_lustre_mgs_config_body_name = -1 [static]
Definition at line 477 of file packet-lustre.c.
int hf_lustre_mgs_config_body_offset = -1 [static]
Definition at line 478 of file packet-lustre.c.
int hf_lustre_mgs_config_body_reserved = -1 [static]
Definition at line 480 of file packet-lustre.c.
int hf_lustre_mgs_config_body_type = -1 [static]
Definition at line 479 of file packet-lustre.c.
int hf_lustre_mgs_config_body_units = -1 [static]
Definition at line 482 of file packet-lustre.c.
int hf_lustre_mgs_config_res = -1 [static]
Definition at line 484 of file packet-lustre.c.
int hf_lustre_mgs_config_res_offset = -1 [static]
Definition at line 485 of file packet-lustre.c.
int hf_lustre_mgs_config_res_size = -1 [static]
Definition at line 486 of file packet-lustre.c.
int hf_lustre_mgs_send_param = -1 [static]
Definition at line 474 of file packet-lustre.c.
int hf_lustre_mgs_send_param_mgs_param = -1 [static]
Definition at line 968 of file packet-lustre.c.
int hf_lustre_mgs_target_info = -1 [static]
Definition at line 473 of file packet-lustre.c.
int hf_lustre_mgs_target_info_mti_config_ver = -1 [static]
Definition at line 900 of file packet-lustre.c.
int hf_lustre_mgs_target_info_mti_flags = -1 [static]
Definition at line 819 of file packet-lustre.c.
int hf_lustre_mgs_target_info_mti_fsname = -1 [static]
Definition at line 868 of file packet-lustre.c.
int hf_lustre_mgs_target_info_mti_lustre_ver = -1 [static]
Definition at line 976 of file packet-lustre.c.
int hf_lustre_mgs_target_info_mti_nid_count = -1 [static]
Definition at line 988 of file packet-lustre.c.
int hf_lustre_mgs_target_info_mti_nids = -1 [static]
Definition at line 954 of file packet-lustre.c.
int hf_lustre_mgs_target_info_mti_params = -1 [static]
Definition at line 923 of file packet-lustre.c.
int hf_lustre_mgs_target_info_mti_stripe_index = -1 [static]
Definition at line 911 of file packet-lustre.c.
int hf_lustre_mgs_target_info_mti_svname = -1 [static]
Definition at line 871 of file packet-lustre.c.
int hf_lustre_mgs_target_info_mti_uuid = -1 [static]
Definition at line 908 of file packet-lustre.c.
int hf_lustre_mgs_target_info_padding = -1 [static]
Definition at line 855 of file packet-lustre.c.
int hf_lustre_nio = -1 [static]
Definition at line 452 of file packet-lustre.c.
int hf_lustre_niobuf_remote = -1 [static]
Definition at line 450 of file packet-lustre.c.
int hf_lustre_niobuf_remote_flags = -1 [static]
Definition at line 803 of file packet-lustre.c.
int hf_lustre_niobuf_remote_len = -1 [static]
Definition at line 737 of file packet-lustre.c.
int hf_lustre_niobuf_remote_offset = -1 [static]
Definition at line 811 of file packet-lustre.c.
int hf_lustre_obd_connect_data = -1 [static]
Definition at line 447 of file packet-lustre.c.
int hf_lustre_obd_connect_data_ocd_brw_size = -1 [static]
Definition at line 753 of file packet-lustre.c.
int hf_lustre_obd_connect_data_ocd_cksum_types = -1 [static]
Definition at line 791 of file packet-lustre.c.
int hf_lustre_obd_connect_data_ocd_connect_flags = -1 [static]
Definition at line 774 of file packet-lustre.c.
int hf_lustre_obd_connect_data_ocd_grant = -1 [static]
Definition at line 786 of file packet-lustre.c.
int hf_lustre_obd_connect_data_ocd_group = -1 [static]
Definition at line 750 of file packet-lustre.c.
int hf_lustre_obd_connect_data_ocd_ibits_known = -1 [static]
Definition at line 746 of file packet-lustre.c.
int hf_lustre_obd_connect_data_ocd_index = -1 [static]
Definition at line 764 of file packet-lustre.c.
int hf_lustre_obd_connect_data_ocd_nllg = -1 [static]
Definition at line 742 of file packet-lustre.c.
int hf_lustre_obd_connect_data_ocd_nllu = -1 [static]
Definition at line 743 of file packet-lustre.c.
int hf_lustre_obd_connect_data_ocd_transno = -1 [static]
Definition at line 815 of file packet-lustre.c.
int hf_lustre_obd_connect_data_ocd_version = -1 [static]
Definition at line 778 of file packet-lustre.c.
int hf_lustre_obd_connect_data_padding1 = -1 [static]
Definition at line 807 of file packet-lustre.c.
int hf_lustre_obd_connect_data_padding2 = -1 [static]
Definition at line 809 of file packet-lustre.c.
int hf_lustre_obd_dqblk_dqb_bhardlimit = -1 [static]
Definition at line 1002 of file packet-lustre.c.
int hf_lustre_obd_dqblk_dqb_bsoftlimit = -1 [static]
Definition at line 1010 of file packet-lustre.c.
int hf_lustre_obd_dqblk_dqb_btime = -1 [static]
Definition at line 1012 of file packet-lustre.c.
int hf_lustre_obd_dqblk_dqb_curinodes = -1 [static]
Definition at line 1009 of file packet-lustre.c.
int hf_lustre_obd_dqblk_dqb_curspace = -1 [static]
Definition at line 1003 of file packet-lustre.c.
int hf_lustre_obd_dqblk_dqb_ihardlimit = -1 [static]
Definition at line 1013 of file packet-lustre.c.
int hf_lustre_obd_dqblk_dqb_isoftlimit = -1 [static]
Definition at line 1001 of file packet-lustre.c.
int hf_lustre_obd_dqblk_dqb_itime = -1 [static]
Definition at line 1004 of file packet-lustre.c.
int hf_lustre_obd_dqblk_dqb_valid = -1 [static]
Definition at line 1005 of file packet-lustre.c.
int hf_lustre_obd_dqblk_padding = -1 [static]
Definition at line 1008 of file packet-lustre.c.
int hf_lustre_obd_dqinfo_dqi_bgrace = -1 [static]
Definition at line 1007 of file packet-lustre.c.
int hf_lustre_obd_dqinfo_dqi_flags = -1 [static]
Definition at line 1011 of file packet-lustre.c.
int hf_lustre_obd_dqinfo_dqi_igrace = -1 [static]
Definition at line 1006 of file packet-lustre.c.
int hf_lustre_obd_dqinfo_dqi_valid = -1 [static]
Definition at line 1000 of file packet-lustre.c.
int hf_lustre_obd_ioobj = -1 [static]
Definition at line 449 of file packet-lustre.c.
int hf_lustre_obd_ioobj_ioo_bufcnt = -1 [static]
Definition at line 787 of file packet-lustre.c.
int hf_lustre_obd_ioobj_ioo_id = -1 [static]
Definition at line 719 of file packet-lustre.c.
int hf_lustre_obd_ioobj_ioo_max_brw = -1 [static]
Definition at line 800 of file packet-lustre.c.
int hf_lustre_obd_ioobj_ioo_seq = -1 [static]
Definition at line 810 of file packet-lustre.c.
int hf_lustre_obd_quotactl = -1 [static]
Definition at line 441 of file packet-lustre.c.
int hf_lustre_obd_quotactl_qc_cmd = -1 [static]
Definition at line 878 of file packet-lustre.c.
int hf_lustre_obd_quotactl_qc_dqblk = -1 [static]
Definition at line 856 of file packet-lustre.c.
int hf_lustre_obd_quotactl_qc_dqinfo = -1 [static]
Definition at line 843 of file packet-lustre.c.
int hf_lustre_obd_quotactl_qc_id = -1 [static]
Definition at line 949 of file packet-lustre.c.
int hf_lustre_obd_quotactl_qc_stat = -1 [static]
Definition at line 845 of file packet-lustre.c.
int hf_lustre_obd_quotactl_qc_type = -1 [static]
Definition at line 952 of file packet-lustre.c.
int hf_lustre_obd_statfs = -1 [static]
Definition at line 440 of file packet-lustre.c.
int hf_lustre_obd_statfs_os_bavail = -1 [static]
Definition at line 727 of file packet-lustre.c.
int hf_lustre_obd_statfs_os_bfree = -1 [static]
Definition at line 777 of file packet-lustre.c.
int hf_lustre_obd_statfs_os_blocks = -1 [static]
Definition at line 781 of file packet-lustre.c.
int hf_lustre_obd_statfs_os_bsize = -1 [static]
Definition at line 728 of file packet-lustre.c.
int hf_lustre_obd_statfs_os_ffree = -1 [static]
Definition at line 758 of file packet-lustre.c.
int hf_lustre_obd_statfs_os_files = -1 [static]
Definition at line 759 of file packet-lustre.c.
int hf_lustre_obd_statfs_os_fsid = -1 [static]
Definition at line 790 of file packet-lustre.c.
int hf_lustre_obd_statfs_os_maxbytes = -1 [static]
Definition at line 755 of file packet-lustre.c.
int hf_lustre_obd_statfs_os_namelen = -1 [static]
Definition at line 780 of file packet-lustre.c.
int hf_lustre_obd_statfs_os_spare1 = -1 [static]
Definition at line 767 of file packet-lustre.c.
int hf_lustre_obd_statfs_os_spare2 = -1 [static]
Definition at line 812 of file packet-lustre.c.
int hf_lustre_obd_statfs_os_spare3 = -1 [static]
Definition at line 796 of file packet-lustre.c.
int hf_lustre_obd_statfs_os_spare4 = -1 [static]
Definition at line 749 of file packet-lustre.c.
int hf_lustre_obd_statfs_os_spare5 = -1 [static]
Definition at line 756 of file packet-lustre.c.
int hf_lustre_obd_statfs_os_spare6 = -1 [static]
Definition at line 794 of file packet-lustre.c.
int hf_lustre_obd_statfs_os_spare7 = -1 [static]
Definition at line 789 of file packet-lustre.c.
int hf_lustre_obd_statfs_os_spare8 = -1 [static]
Definition at line 768 of file packet-lustre.c.
int hf_lustre_obd_statfs_os_spare9 = -1 [static]
Definition at line 763 of file packet-lustre.c.
int hf_lustre_obd_statfs_os_state = -1 [static]
Definition at line 795 of file packet-lustre.c.
int hf_lustre_obd_statfs_os_type = -1 [static]
Definition at line 793 of file packet-lustre.c.
int hf_lustre_obd_uuid = -1 [static]
Definition at line 446 of file packet-lustre.c.
int hf_lustre_obdo_o_atime = -1 [static]
Definition at line 875 of file packet-lustre.c.
int hf_lustre_obdo_o_blksize = -1 [static]
Definition at line 929 of file packet-lustre.c.
int hf_lustre_obdo_o_blocks = -1 [static]
Definition at line 934 of file packet-lustre.c.
int hf_lustre_obdo_o_ctime = -1 [static]
Definition at line 989 of file packet-lustre.c.
int hf_lustre_obdo_o_flags = -1 [static]
Definition at line 922 of file packet-lustre.c.
int hf_lustre_obdo_o_gid = -1 [static]
Definition at line 883 of file packet-lustre.c.
int hf_lustre_obdo_o_gid_h = -1 [static]
Definition at line 939 of file packet-lustre.c.
int hf_lustre_obdo_o_grant = -1 [static]
Definition at line 937 of file packet-lustre.c.
int hf_lustre_obdo_o_handle = -1 [static]
Definition at line 874 of file packet-lustre.c.
int hf_lustre_obdo_o_id = -1 [static]
Definition at line 907 of file packet-lustre.c.
int hf_lustre_obdo_o_ioepoch = -1 [static]
Definition at line 894 of file packet-lustre.c.
int hf_lustre_obdo_o_lcookie = -1 [static]
Definition at line 905 of file packet-lustre.c.
int hf_lustre_obdo_o_misc = -1 [static]
Definition at line 832 of file packet-lustre.c.
int hf_lustre_obdo_o_mode = -1 [static]
Definition at line 870 of file packet-lustre.c.
int hf_lustre_obdo_o_mtime = -1 [static]
Definition at line 928 of file packet-lustre.c.
int hf_lustre_obdo_o_nlink = -1 [static]
Definition at line 827 of file packet-lustre.c.
int hf_lustre_obdo_o_padding_3 = -1 [static]
Definition at line 920 of file packet-lustre.c.
int hf_lustre_obdo_o_padding_4 = -1 [static]
Definition at line 854 of file packet-lustre.c.
int hf_lustre_obdo_o_padding_5 = -1 [static]
Definition at line 983 of file packet-lustre.c.
int hf_lustre_obdo_o_padding_6 = -1 [static]
Definition at line 913 of file packet-lustre.c.
int hf_lustre_obdo_o_parent_oid = -1 [static]
Definition at line 980 of file packet-lustre.c.
int hf_lustre_obdo_o_parent_seq = -1 [static]
Definition at line 985 of file packet-lustre.c.
int hf_lustre_obdo_o_parent_ver = -1 [static]
Definition at line 977 of file packet-lustre.c.
int hf_lustre_obdo_o_seq = -1 [static]
Definition at line 882 of file packet-lustre.c.
int hf_lustre_obdo_o_size = -1 [static]
Definition at line 859 of file packet-lustre.c.
int hf_lustre_obdo_o_stripe_idx = -1 [static]
Definition at line 955 of file packet-lustre.c.
int hf_lustre_obdo_o_uid = -1 [static]
Definition at line 829 of file packet-lustre.c.
int hf_lustre_obdo_o_uid_h = -1 [static]
Definition at line 938 of file packet-lustre.c.
int hf_lustre_obdo_o_valid = -1 [static]
Definition at line 830 of file packet-lustre.c.
int hf_lustre_opnum = -1 [static]
Definition at line 765 of file packet-lustre.c.
int hf_lustre_ost_body = -1 [static]
Definition at line 439 of file packet-lustre.c.
int hf_lustre_ost_body_oa = -1 [static]
Definition at line 895 of file packet-lustre.c.
int hf_lustre_ost_key = -1 [static]
Definition at line 451 of file packet-lustre.c.
int hf_lustre_ost_lvb = -1 [static]
Definition at line 488 of file packet-lustre.c.
int hf_lustre_ost_lvb_lvb_atime = -1 [static]
Definition at line 725 of file packet-lustre.c.
int hf_lustre_ost_lvb_lvb_blocks = -1 [static]
Definition at line 805 of file packet-lustre.c.
int hf_lustre_ost_lvb_lvb_ctime = -1 [static]
Definition at line 740 of file packet-lustre.c.
int hf_lustre_ost_lvb_lvb_mtime = -1 [static]
Definition at line 745 of file packet-lustre.c.
int hf_lustre_ost_lvb_lvb_size = -1 [static]
Definition at line 792 of file packet-lustre.c.
int hf_lustre_ost_val = -1 [static]
Definition at line 453 of file packet-lustre.c.
int hf_lustre_ptlrpc_body_pb = -1 [static]
Definition at line 438 of file packet-lustre.c.
int hf_lustre_ptlrpc_body_pb_conn_cnt = -1 [static]
Definition at line 772 of file packet-lustre.c.
int hf_lustre_ptlrpc_body_pb_flags = -1 [static]
Definition at line 748 of file packet-lustre.c.
int hf_lustre_ptlrpc_body_pb_handle = -1 [static]
Definition at line 814 of file packet-lustre.c.
int hf_lustre_ptlrpc_body_pb_jobid = -1 [static]
Definition at line 723 of file packet-lustre.c.
int hf_lustre_ptlrpc_body_pb_last_committed = -1 [static]
Definition at line 716 of file packet-lustre.c.
int hf_lustre_ptlrpc_body_pb_last_seen = -1 [static]
Definition at line 799 of file packet-lustre.c.
int hf_lustre_ptlrpc_body_pb_last_xid = -1 [static]
Definition at line 801 of file packet-lustre.c.
int hf_lustre_ptlrpc_body_pb_limit = -1 [static]
Definition at line 754 of file packet-lustre.c.
int hf_lustre_ptlrpc_body_pb_op_flags = -1 [static]
Definition at line 739 of file packet-lustre.c.
int hf_lustre_ptlrpc_body_pb_opc = -1 [static]
Definition at line 773 of file packet-lustre.c.
int hf_lustre_ptlrpc_body_pb_padding = -1 [static]
Definition at line 722 of file packet-lustre.c.
int hf_lustre_ptlrpc_body_pb_pre_version = -1 [static]
Definition at line 721 of file packet-lustre.c.
int hf_lustre_ptlrpc_body_pb_service_time = -1 [static]
Definition at line 771 of file packet-lustre.c.
int hf_lustre_ptlrpc_body_pb_slv = -1 [static]
Definition at line 720 of file packet-lustre.c.
int hf_lustre_ptlrpc_body_pb_status = -1 [static]
Definition at line 802 of file packet-lustre.c.
int hf_lustre_ptlrpc_body_pb_timeout = -1 [static]
Definition at line 726 of file packet-lustre.c.
int hf_lustre_ptlrpc_body_pb_transno = -1 [static]
Definition at line 770 of file packet-lustre.c.
int hf_lustre_ptlrpc_body_pb_type = -1 [static]
Definition at line 741 of file packet-lustre.c.
int hf_lustre_ptlrpc_body_pb_version = -1 [static]
Definition at line 717 of file packet-lustre.c.
int hf_lustre_qunit_data_old2_qd_count = -1 [static]
Definition at line 960 of file packet-lustre.c.
int hf_lustre_qunit_data_old2_qd_flags = -1 [static]
Definition at line 961 of file packet-lustre.c.
int hf_lustre_qunit_data_old2_qd_id = -1 [static]
Definition at line 846 of file packet-lustre.c.
int hf_lustre_qunit_data_old_qd_count = -1 [static]
Definition at line 902 of file packet-lustre.c.
int hf_lustre_qunit_data_old_qd_id = -1 [static]
Definition at line 822 of file packet-lustre.c.
int hf_lustre_qunit_data_old_qd_isblk = -1 [static]
Definition at line 933 of file packet-lustre.c.
int hf_lustre_qunit_data_old_qd_type = -1 [static]
Definition at line 864 of file packet-lustre.c.
int hf_lustre_qunit_data_padding = -1 [static]
Definition at line 879 of file packet-lustre.c.
int hf_lustre_qunit_data_qd_count = -1 [static]
Definition at line 927 of file packet-lustre.c.
int hf_lustre_qunit_data_qd_flags = -1 [static]
Definition at line 978 of file packet-lustre.c.
int hf_lustre_qunit_data_qd_id = -1 [static]
Definition at line 867 of file packet-lustre.c.
int hf_lustre_qunit_data_qd_qunit = -1 [static]
Definition at line 840 of file packet-lustre.c.
int hf_lustre_quota_adjust_qunit = -1 [static]
Definition at line 442 of file packet-lustre.c.
int hf_lustre_quota_adjust_qunit_padding1 = -1 [static]
Definition at line 824 of file packet-lustre.c.
int hf_lustre_quota_adjust_qunit_qaq_bunit_sz = -1 [static]
Definition at line 963 of file packet-lustre.c.
int hf_lustre_quota_adjust_qunit_qaq_flags = -1 [static]
Definition at line 880 of file packet-lustre.c.
int hf_lustre_quota_adjust_qunit_qaq_id = -1 [static]
Definition at line 876 of file packet-lustre.c.
int hf_lustre_quota_adjust_qunit_qaq_iunit_sz = -1 [static]
Definition at line 940 of file packet-lustre.c.
int hf_lustre_reint_name = -1 [static]
Definition at line 469 of file packet-lustre.c.
int hf_lustre_reint_new_name = -1 [static]
Definition at line 471 of file packet-lustre.c.
int hf_lustre_reint_old_name = -1 [static]
Definition at line 470 of file packet-lustre.c.
int hf_lustre_seq_opc = -1 [static]
Definition at line 682 of file packet-lustre.c.
int hf_lustre_seq_range = -1 [static]
Definition at line 683 of file packet-lustre.c.
int hf_lustre_seq_range_end = -1 [static]
Definition at line 685 of file packet-lustre.c.
int hf_lustre_seq_range_flags = -1 [static]
Definition at line 687 of file packet-lustre.c.
int hf_lustre_seq_range_index = -1 [static]
Definition at line 686 of file packet-lustre.c.
int hf_lustre_seq_range_start = -1 [static]
Definition at line 684 of file packet-lustre.c.
const true_false_string lnet_flags_set_truth = { "Set", "Unset" }
Definition at line 42 of file packet-lustre.c.
const value_string lustre_ldlm_mode_vals[]
Initial value:
 {
  { LCK_MINMODE, "MINMODE" },
  { LCK_EX, "Exclusive" },
  { LCK_PW, "Protected Write" },
  { LCK_PR, "Protected Read" },
  { LCK_CW, "Concurrent Write" },
  { LCK_CR, "Concurrent Read" },
  { LCK_NL, "Null" },
  { LCK_GROUP, "GROUP" },
  { 0, NULL }
}
Definition at line 1241 of file packet-lustre.c.
const value_string lustre_ldlm_opcode[]
Initial value:
 {
  { IT_OPEN    ,   "IT_OPEN    "},
  { IT_CREAT   ,   "IT_CREAT   "},
  { IT_READDIR ,   "IT_READDIR "},
  { IT_GETATTR ,   "IT_GETATTR "},
  { IT_LOOKUP  ,   "IT_LOOKUP  "},
  { IT_UNLINK  ,   "IT_UNLINK  "},
  { IT_GETXATTR,   "IT_GETXATTR"},
  { IT_EXEC    ,   "IT_EXEC    "},
  { IT_PIN     ,   "IT_PIN     "},
  { 0, NULL }
}
Definition at line 1053 of file packet-lustre.c.
const value_string lustre_ldlm_type_vals[]
Initial value:
 {
  { LDLM_PLAIN, "LDLM_PLAIN" },
  { LDLM_EXTENT,"LDLM_EXTENT" },
  { LDLM_FLOCK, "LDLM_FLOCK" },
  { LDLM_IBITS, "LDLM_IBITS" },
  { 0, NULL }
}
Definition at line 1253 of file packet-lustre.c.
const value_string lustre_llog_cmd_t_vals[]
Initial value:
 {
  { LLOG_ORIGIN_HANDLE_CREATE, "LLOG_ORIGIN_HANDLE_CREATE" },
  { LLOG_ORIGIN_HANDLE_NEXT_BLOCK, "LLOG_ORIGIN_HANDLE_NEXT_BLOCK" },
  { LLOG_ORIGIN_HANDLE_READ_HEADER, "LLOG_ORIGIN_HANDLE_READ_HEADER" },
  { LLOG_ORIGIN_HANDLE_WRITE_REC, "LLOG_ORIGIN_HANDLE_WRITE_REC" },
  { LLOG_ORIGIN_HANDLE_CLOSE, "LLOG_ORIGIN_HANDLE_CLOSE" },
  { LLOG_ORIGIN_CONNECT, "LLOG_ORIGIN_CONNECT" },
  { LLOG_CATINFO, "LLOG_CATINFO" },
  { LLOG_ORIGIN_HANDLE_PREV_BLOCK, "LLOG_ORIGIN_HANDLE_PREV_BLOCK" },
  { LLOG_ORIGIN_HANDLE_DESTROY, "LLOG_ORIGIN_HANDLE_DESTROY" },
  { 0, NULL }
}
Definition at line 1262 of file packet-lustre.c.
const value_string lustre_llog_hdr_llh_flags[]
Initial value:
 {
  {LLOG_F_ZAP_WHEN_EMPTY , "LLOhdr_llh_G_F_ZAP_WHEN_EMPTY"},
  {LLOG_F_IS_CAT         , "LLOhdr_llh_G_F_IS_CAT"},
  {LLOG_F_IS_PLAIN       , "LLOG_F_IS_PLAIN"},
  { 0, NULL }
}
Definition at line 1086 of file packet-lustre.c.
const value_string lustre_llog_op_type[]
Initial value:
 {
  {LLOG_PAD_MAGIC   ,"LLOG_PAD_MAGIC  "},
  {OST_SZ_REC       ,"OST_SZ_REC      "},
  {OST_RAID1_REC    ,"OST_RAID1_REC   "},
  {MDS_UNLINK_REC   ,"MDS_UNLINK_REC  "},
  {MDS_SETATTR_REC  ,"MDS_SETATTR_REC "},
  {OBD_CFG_REC      ,"OBD_CFG_REC     "},
  {PTL_CFG_REC      ,"PTL_CFG_REC     "},
  {LLOG_GEN_REC     ,"LLOG_GEN_REC    "},
  {LLOG_JOIN_REC    ,"LLOG_JOIN_REC   "},
  {LLOG_HDR_MAGIC   ,"LLOG_HDR_MAGIC  "},
  {LLOG_LOGID_MAGIC ,"LLOG_LOGID_MAGIC"},
  { 0, NULL }
}
Definition at line 1071 of file packet-lustre.c.
const value_string lustre_LMTypes[]
Initial value:
 {
  { PTL_RPC_MSG_REQUEST, "request"},
  { PTL_RPC_MSG_ERR , "error"},
  { PTL_RPC_MSG_REPLY , "reply"},
  { 0, NULL }
}
Definition at line 1115 of file packet-lustre.c.
const value_string lustre_lov_magic[]
Initial value:
 {
  { LOV_MAGIC_V1,   "LOV_MAGIC_V1" },
  {0, NULL}
}
Definition at line 1066 of file packet-lustre.c.
const value_string lustre_mds_flags_vals[]
Initial value:
 {
  {0x00000008, "LUSTRE_SYNC_FL        "},
  {0x00000010, "LUSTRE_IMMUTABLE_FL   "},
  {0x00000020, "LUSTRE_APPEND_FL      "},
  {0x00000040, "LUSTRE_NODUMP_FL      "},
  {0x00000080, "LUSTRE_NOATIME_FL     "},
  {0x00001000, "LUSTRE_INDEX_FL       "},
  {0x00010000, "LUSTRE_DIRSYNC_FL     "},
  {0x00020000, "LUSTRE_TOPDIR_FL      "},
  {0x00100000, "LUSTRE_DIRECTIO_FL    "},
  {0x10000000, "LUSTRE_INLINE_DATA_FL "},
  { 0, NULL }
}
Definition at line 1093 of file packet-lustre.c.
const value_string lustre_mds_reint_t_vals[]
Initial value:
 {
  { REINT_SETATTR, "REINT_SETATTR" },
  { REINT_CREATE, "REINT_CREATE" },
  { REINT_LINK, "REINT_LINK" },
  { REINT_UNLINK, "REINT_UNLINK" },
  { REINT_RENAME, "REINT_RENAME" },
  { REINT_OPEN, "REINT_OPEN" },
  { REINT_SETXATTR, "REINT_SETXATTR" },
  { 0, NULL }
}
Definition at line 1122 of file packet-lustre.c.
const value_string lustre_mgs_config_body_types[]
Initial value:
 {
  { 0,  "CONFIG" },
  { 1,  "SPTLRPC" },
  { 2,  "RECOVER" },
  { 3,  "MAX" },
  { 0, NULL }
}
Definition at line 1107 of file packet-lustre.c.
const value_string lustre_op_codes[]
Definition at line 1132 of file packet-lustre.c.
const value_string portal_indices[] [static]
Definition at line 126 of file packet-lustre.c.
gint proto_lustre = -1 [static]
Definition at line 1035 of file packet-lustre.c.
const gchar version[] = VERSION
Definition at line 1276 of file packet-lustre.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.