Lustre: libcfs/include/libcfs/util/param.h File Reference
libcfs/include/libcfs/util/param.h File Reference
#include <glob.h>
#include <stdbool.h>
Functions
static void cfs_free_param_data (glob_t *paths)
int cfs_get_param_paths (glob_t *paths, const char *pattern,...) __attribute__((__format__(__printf__
Function Documentation
static void cfs_free_param_data (glob_t * paths) [inline, static]
Definition at line 32 of file param.h.
Referenced by cancel_lru_locks(), compare(), dbg_open_ctlhandle(), do_nego_rpc(), do_negotiation(), get_lustre_param_value(), jt_obd_list(), llapi_get_poollist(), llapi_get_poolmembers(), llapi_get_target_uuids(), llapi_nodemap_exists(), llapi_ping(), llapi_search_ost(), llapi_target_iterate(), main(), param_display(), print_obd_line(), set_log_level(), and setup_obd_uuid().
int cfs_get_param_paths (glob_t * paths, const char * pattern, ...)
Referenced by cancel_lru_locks(), compare(), dbg_open_ctlhandle(), do_nego_rpc(), do_negotiation(), get_lustre_param_path(), jt_obd_list(), llapi_nodemap_exists(), llapi_ping(), llapi_target_iterate(), main(), param_display(), print_obd_line(), and set_log_level().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.