Lustre: libcfs/libcfs/util/parser.c File Reference
libcfs/libcfs/util/parser.c File Reference
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <assert.h>
#include <ctype.h>
#include <errno.h>
#include <getopt.h>
#include <malloc.h>
#include <string.h>
#include <unistd.h>
#include <libcfs/util/parser.h>
#include <lustre_ver.h>
Defines
#define add_history(s)
Functions
static char * skipwhitespace (char *s)
static char * skiptowhitespace (char *s)
static command_t * find_cmd (char *name, command_t cmds[], char **next)
static int process (char *s, char **next, command_t *lookup, command_t **result, char **prev)
static void print_commands (char *str, command_t *table)
static int line2args (char *line, char **argv, int maxargs)
static command_t * Parser_findargcmd (char *name, command_t cmds[])
void Parser_ignore_errors (int ignore)
int Parser_execarg (int argc, char **argv, command_t cmds[])
int execute_line (char *line)
static int init_input (void)
char * readline (char *prompt)
int Parser_commands (void)
void Parser_init (char *prompt, command_t *cmds)
void Parser_exit (int argc, char *argv[])
int Parser_int (char *s, int *val)
void Parser_qhelp (int argc, char *argv[])
int Parser_help (int argc, char **argv)
void Parser_printhelp (char *cmd)
char * Parser_getstr (const char *prompt, const char *deft, char *res, size_t len)
int Parser_getint (const char *prompt, long min, long max, long deft, int base)
int Parser_getbool (const char *prompt, int deft)
long Parser_intarg (const char *inp, const char *prompt, int deft, int min, int max, int base)
char * Parser_strarg (char *inp, const char *prompt, const char *deft, char *answer, int len)
int Parser_arg2int (const char *inp, long *result, int base)
int Parser_size (int *sizep, char *str)
int Parser_bool (int *b, char *str)
int Parser_quit (int argc, char **argv)
int Parser_version (int argc, char **argv)
Variables
static command_t * top_level
static char * parser_prompt = NULL
static int done
static int ignore_errors
Define Documentation
#define add_history (s)
Definition at line 329 of file parser.c.
Referenced by Parser_commands().
Function Documentation
int execute_line (char * line)
Definition at line 259 of file parser.c.
References cmd, CMD_AMBIG, CMD_COMPLETE, CMD_HELP, CMD_INCOMPLETE, CMD_NONE, find_cmd(), line2args(), MAXARGS, optind, parser_cmd::pc_func, parser_cmd::pc_help, parser_cmd::pc_name, parser_cmd::pc_sub_cmd, and process().
Referenced by Parser_commands().
static command_t * find_cmd (char * name, command_t cmds[], char ** next) [static]
Definition at line 132 of file parser.c.
References parser_cmd::pc_name, skiptowhitespace(), and skipwhitespace().
Referenced by execute_line(), Parser_help(), and process().
static int init_input (void) [static]
Definition at line 309 of file parser.c.
References HISTORY.
Referenced by Parser_commands().
static int line2args (char * line, char ** argv, int maxargs) [static]
Definition at line 78 of file parser.c.
Referenced by execute_line().
int Parser_arg2int (const char * inp, long * result, int base)
Definition at line 701 of file parser.c.
Referenced by Parser_getint(), and Parser_intarg().
int Parser_bool (int * b, char * str)
Definition at line 754 of file parser.c.
int Parser_commands (void)
Definition at line 382 of file parser.c.
References add_history, done, execute_line(), ignore_errors, init_input(), parser_prompt, readline(), and skipwhitespace().
Referenced by lctl_main(), and main().
int Parser_execarg (int argc, char ** argv, command_t cmds[])
Definition at line 110 of file parser.c.
References cmd, CMD_HELP, Parser_findargcmd(), parser_cmd::pc_func, parser_cmd::pc_help, and parser_cmd::pc_name.
Referenced by jt_lnet(), jt_net(), jt_opt_device(), jt_opt_net(), jt_peer_credits(), jt_route(), jt_routing(), jt_set(), jt_stats(), lctl_main(), and main().
void Parser_exit (int argc, char * argv[])
Definition at line 427 of file parser.c.
References done, and parser_prompt.
static command_t* Parser_findargcmd (char * name, command_t cmds[]) [static]
Definition at line 94 of file parser.c.
References cmd, and parser_cmd::pc_name.
Referenced by Parser_execarg().
int Parser_getbool (const char * prompt, int deft)
Definition at line 624 of file parser.c.
References assert, readline(), and size.
int Parser_getint (const char * prompt, long min, long max, long deft, int base)
Definition at line 578 of file parser.c.
References assert, Parser_arg2int(), readline(), and size.
Referenced by Parser_intarg().
char* Parser_getstr (const char * prompt, const char * deft, char * res, size_t len)
Definition at line 547 of file parser.c.
References assert, readline(), and size.
Referenced by Parser_strarg().
int Parser_help (int argc, char ** argv)
Definition at line 460 of file parser.c.
References CMD_AMBIG, CMD_COMPLETE, CMD_INCOMPLETE, CMD_NONE, find_cmd(), Parser_qhelp(), parser_cmd::pc_help, parser_cmd::pc_name, parser_cmd::pc_sub_cmd, and process().
Referenced by Parser_printhelp().
void Parser_ignore_errors (int ignore)
Definition at line 105 of file parser.c.
References ignore_errors.
Referenced by jt_opt_ignore_errors().
void Parser_init (char * prompt, command_t * cmds)
Definition at line 418 of file parser.c.
References done, and parser_prompt.
Referenced by lctl_main(), and main().
int Parser_int (char * s, int * val)
Definition at line 435 of file parser.c.
References ret.
long Parser_intarg (const char * inp, const char * prompt, int deft, int min, int max, int base)
Definition at line 674 of file parser.c.
References Parser_arg2int(), and Parser_getint().
void Parser_printhelp (char * cmd)
Definition at line 517 of file parser.c.
References Parser_help().
Referenced by lst_print_usage().
void Parser_qhelp (int argc, char * argv[])
Definition at line 452 of file parser.c.
References print_commands().
int Parser_quit (int argc, char ** argv)
Definition at line 778 of file parser.c.
References done.
int Parser_size (int * sizep, char * str)
Definition at line 717 of file parser.c.
References size.
char* Parser_strarg (char * inp, const char * prompt, const char * deft, char * answer, int len)
Definition at line 690 of file parser.c.
References Parser_getstr().
int Parser_version (int argc, char ** argv)
Definition at line 786 of file parser.c.
static void print_commands (char * str, command_t * table) [static]
Definition at line 527 of file parser.c.
References buf, parser_cmd::pc_func, parser_cmd::pc_name, and parser_cmd::pc_sub_cmd.
Referenced by Parser_qhelp().
static int process (char * s, char ** next, command_t * lookup, command_t ** result, char ** prev) [static]
Definition at line 160 of file parser.c.
References CMD_AMBIG, CMD_COMPLETE, CMD_INCOMPLETE, CMD_NONE, find_cmd(), and parser_cmd::pc_name.
Referenced by execute_line(), and Parser_help().
char* readline (char * prompt)
Definition at line 330 of file parser.c.
References size.
static char * skiptowhitespace (char * s) [static]
Definition at line 70 of file parser.c.
Referenced by find_cmd().
static char * skipwhitespace (char * s) [static]
Definition at line 59 of file parser.c.
Referenced by find_cmd(), and Parser_commands().
Variable Documentation
int done [static]
Definition at line 44 of file parser.c.
Referenced by cl_io_locks_sort(), cYAML_build_tree(), kiblnd_post_tx_locked(), lfsck_layout_slave_async_interpret(), lfsck_layout_slave_double_scan(), lfsck_layout_slave_post(), ll_dir_read(), main(), ofd_orphans_destroy(), osp_sync_process_committed(), Parser_commands(), Parser_exit(), Parser_init(), Parser_quit(), qmt_adjust_qunit(), sfw_create_rpc(), and sfw_test_rpc_done().
int ignore_errors [static]
Definition at line 45 of file parser.c.
Referenced by Parser_commands(), and Parser_ignore_errors().
char* parser_prompt = NULL [static]
Definition at line 43 of file parser.c.
Referenced by Parser_commands(), Parser_exit(), and Parser_init().
command_t* top_level [static]
Definition at line 41 of file parser.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.