Lustre: lnet/lnet/peer.c File Reference
lnet/lnet/peer.c File Reference
#include <lnet/lib-lnet.h>
#include <lnet/lib-dlc.h>
Defines
#define DEBUG_SUBSYSTEM S_LNET
Functions
int lnet_peer_tables_create (void)
void lnet_peer_tables_destroy (void)
static void lnet_peer_table_cleanup_locked (lnet_ni_t *ni, struct lnet_peer_table *ptable)
static void lnet_peer_table_deathrow_wait_locked (struct lnet_peer_table *ptable, int cpt_locked)
static void lnet_peer_table_del_rtrs_locked (lnet_ni_t *ni, struct lnet_peer_table *ptable, int cpt_locked)
void lnet_peer_tables_cleanup (lnet_ni_t *ni)
void lnet_destroy_peer_locked (lnet_peer_t *lp)
lnet_peer_t * lnet_find_peer_locked (struct lnet_peer_table *ptable, lnet_nid_t nid)
int lnet_nid2peer_locked (lnet_peer_t **lpp, lnet_nid_t nid, int cpt)
void lnet_debug_peer (lnet_nid_t nid)
int lnet_get_peer_info (__u32 peer_index, __u64 *nid, char aliveness[LNET_MAX_STR_LEN], __u32 *cpt_iter, __u32 *refcount, __u32 *ni_peer_tx_credits, __u32 *peer_tx_credits, __u32 *peer_rtr_credits, __u32 *peer_min_rtr_credits, __u32 *peer_tx_qnob)
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 39 of file peer.c.
Function Documentation
void lnet_debug_peer (lnet_nid_t nid)
Definition at line 362 of file peer.c.
References CDEBUG, D_WARNING, libcfs_nid2str(), lnet_cpt_of_nid(), lnet_isrouter(), lnet_net_lock(), lnet_net_unlock(), lnet_nid2peer_locked(), lnet_peer_aliveness_enabled, lnet_peer_decref_locked(), lnet_peer::lp_alive, lnet_peer::lp_minrtrcredits, lnet_peer::lp_mintxcredits, lnet_peer::lp_ni, lnet_peer::lp_nid, lnet_peer::lp_refcount, lnet_peer::lp_rtrcredits, lnet_peer::lp_txcredits, lnet_peer::lp_txqnob, and lnet_ni::ni_peertxcredits.
Referenced by LNetDebugPeer().
void lnet_destroy_peer_locked (lnet_peer_t * lp)
Definition at line 217 of file peer.c.
References LASSERT, list_add(), list_empty(), lnet_t::ln_peer_tables, lnet_ni_decref_locked(), lnet_peer::lp_cpt, lnet_peer::lp_hashlist, lnet_peer::lp_ni, lnet_peer::lp_refcount, lnet_peer::lp_rtr_refcount, lnet_peer::lp_txq, lnet_peer::lp_txqnob, lnet_peer_table::pt_deathrow, lnet_peer_table::pt_number, lnet_peer_table::pt_zombies, and the_lnet.
Referenced by lnet_peer_decref_locked().
lnet_peer_t* lnet_find_peer_locked (struct lnet_peer_table * ptable, lnet_nid_t nid)
Definition at line 240 of file peer.c.
References LASSERT, list_for_each_entry, lnet_t::ln_shutdown, lnet_nid2peerhash(), lnet_peer_addref_locked(), lnet_peer::lp_nid, lnet_peer_table::pt_hash, and the_lnet.
Referenced by lnet_nid2peer_locked(), and lnet_notify().
int lnet_get_peer_info (__u32 peer_index, __u64 * nid, char aliveness[LNET_MAX_STR_LEN], __u32 * cpt_iter, __u32 * refcount, __u32 * ni_peer_tx_credits, __u32 * peer_tx_credits, __u32 * peer_rtr_credits, __u32 * peer_min_rtr_credits, __u32 * peer_tx_qnob)
Definition at line 393 of file peer.c.
References cfs_percpt_number(), list_for_each_entry, lnet_t::ln_peer_tables, lnet_isrouter(), lnet_net_lock(), lnet_net_unlock(), lnet_peer_aliveness_enabled, LNET_PEER_HASH_SIZE, lnet_peer::lp_alive, lnet_peer::lp_mintxcredits, lnet_peer::lp_ni, lnet_peer::lp_nid, lnet_peer::lp_refcount, lnet_peer::lp_rtrcredits, lnet_peer::lp_txcredits, lnet_peer::lp_txqnob, lnet_ni::ni_peertxcredits, lnet_peer_table::pt_hash, and the_lnet.
Referenced by LNetCtl().
int lnet_nid2peer_locked (lnet_peer_t ** lpp, lnet_nid_t nid, int cpt)
Definition at line 259 of file peer.c.
References cfs_time_current(), INIT_LIST_HEAD, LIBCFS_CPT_ALLOC, list_add(), list_add_tail(), list_del(), list_empty(), list_entry, lnet_t::ln_peer_tables, lnet_t::ln_shutdown, lnet_cpt_of_nid_locked(), lnet_cpt_table, lnet_find_peer_locked(), LNET_LOCK_EX, lnet_net2ni_locked(), lnet_net_lock(), lnet_net_unlock(), lnet_nid2peerhash(), LNET_NIDNET(), lnet_peer_buffer_credits(), lnet_peers_start_down(), LNET_PING_FEAT_INVAL, lnet_peer::lp_alive, lnet_peer::lp_alive_count, lnet_peer::lp_cpt, lnet_peer::lp_hashlist, lnet_peer::lp_last_alive, lnet_peer::lp_last_query, lnet_peer::lp_minrtrcredits, lnet_peer::lp_mintxcredits, lnet_peer::lp_ni, lnet_peer::lp_nid, lnet_peer::lp_notify, lnet_peer::lp_notifying, lnet_peer::lp_notifylnd, lnet_peer::lp_ping_feats, lnet_peer::lp_ping_timestamp, lnet_peer::lp_refcount, lnet_peer::lp_routes, lnet_peer::lp_rtr_refcount, lnet_peer::lp_rtrcredits, lnet_peer::lp_rtrq, lnet_peer::lp_timestamp, lnet_peer::lp_txcredits, lnet_peer::lp_txq, list_head::next, lnet_ni::ni_peertxcredits, lnet_peer_table::pt_deathrow, lnet_peer_table::pt_hash, lnet_peer_table::pt_number, lnet_peer_table::pt_version, and the_lnet.
Referenced by lnet_add_route(), lnet_debug_peer(), lnet_parse(), and lnet_send().
static void lnet_peer_table_cleanup_locked (lnet_ni_t * ni, struct lnet_peer_table * ptable) [static]
Definition at line 108 of file peer.c.
References list_del_init(), list_for_each_entry_safe, lnet_peer_decref_locked(), LNET_PEER_HASH_SIZE, lnet_peer::lp_hashlist, lnet_peer::lp_ni, lnet_peer_table::pt_hash, and lnet_peer_table::pt_zombies.
Referenced by lnet_peer_tables_cleanup().
static void lnet_peer_table_deathrow_wait_locked (struct lnet_peer_table * ptable, int cpt_locked) [static]
Definition at line 128 of file peer.c.
References CDEBUG, cfs_time_seconds(), D_WARNING, lnet_net_lock(), lnet_net_unlock(), and lnet_peer_table::pt_zombies.
Referenced by lnet_peer_tables_cleanup().
static void lnet_peer_table_del_rtrs_locked (lnet_ni_t * ni, struct lnet_peer_table * ptable, int cpt_locked) [static]
Definition at line 148 of file peer.c.
References list_for_each_entry_safe, lnet_del_route(), lnet_net_lock(), lnet_net_unlock(), LNET_NID_ANY, LNET_NIDNET(), LNET_PEER_HASH_SIZE, lnet_peer::lp_ni, lnet_peer::lp_nid, lnet_peer::lp_rtr_refcount, and lnet_peer_table::pt_hash.
Referenced by lnet_peer_tables_cleanup().
void lnet_peer_tables_cleanup (lnet_ni_t * ni)
Definition at line 175 of file peer.c.
References cfs_percpt_for_each, INIT_LIST_HEAD, LASSERT, LIBCFS_FREE, list_del(), list_empty(), list_entry, list_splice_init(), lnet_t::ln_peer_tables, lnet_t::ln_shutdown, lnet_net_lock(), lnet_net_unlock(), lnet_peer_table_cleanup_locked(), lnet_peer_table_deathrow_wait_locked(), lnet_peer_table_del_rtrs_locked(), lnet_peer::lp_hashlist, list_head::next, lnet_peer_table::pt_deathrow, and the_lnet.
Referenced by lnet_shutdown_lndni(), and lnet_shutdown_lndnis().
int lnet_peer_tables_create (void)
Definition at line 45 of file peer.c.
References CERROR, cfs_percpt_alloc(), cfs_percpt_for_each, INIT_LIST_HEAD, LIBCFS_CPT_ALLOC, lnet_t::ln_peer_tables, lnet_cpt_table, LNET_PEER_HASH_SIZE, lnet_peer_tables_destroy(), lnet_peer_table::pt_deathrow, lnet_peer_table::pt_hash, and the_lnet.
Referenced by lnet_prepare().
void lnet_peer_tables_destroy (void)
Definition at line 79 of file peer.c.
References cfs_percpt_for_each, cfs_percpt_free(), LASSERT, LIBCFS_FREE, list_empty(), lnet_t::ln_peer_tables, LNET_PEER_HASH_SIZE, lnet_peer_table::pt_deathrow, lnet_peer_table::pt_hash, and the_lnet.
Referenced by lnet_peer_tables_create(), and lnet_unprepare().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.