Lustre: lustre/ptlrpc/pers.c File Reference
lustre/ptlrpc/pers.c File Reference
#include <obd_support.h>
#include <obd_class.h>
#include <lustre_lib.h>
#include <lustre_ha.h>
#include <lustre_import.h>
#include "ptlrpc_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_RPC
Functions
void ptlrpc_fill_bulk_md (lnet_md_t *md, struct ptlrpc_bulk_desc *desc, int mdidx)
Define Documentation
#define DEBUG_SUBSYSTEM S_RPC
Definition at line 37 of file pers.c.
Function Documentation
void ptlrpc_fill_bulk_md (lnet_md_t * md, struct ptlrpc_bulk_desc * desc, int mdidx)
Definition at line 48 of file pers.c.
References BD_GET_ENC_KIOV, BD_GET_ENC_KVEC, BD_GET_KIOV, BD_GET_KVEC, ptlrpc_bulk_desc::bd_iov_count, ptlrpc_bulk_desc::bd_type, CLASSERT, GET_ENC_KIOV, GET_ENC_KVEC, LASSERT, lnet_md_t::length, LNET_MAX_IOV, LNET_MD_IOVEC, LNET_MD_KIOV, LNET_MD_PHYS, max, min_t, lnet_md_t::options, ptlrpc_is_bulk_desc_kiov(), ptlrpc_is_bulk_desc_kvec(), PTLRPC_MAX_BRW_PAGES, and lnet_md_t::start.
Referenced by ptlrpc_register_bulk().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.