Lustre: lustre/ptlrpc/pinger.c File Reference
lustre/ptlrpc/pinger.c File Reference
#include <linux/kthread.h>
#include <obd_support.h>
#include <obd_class.h>
#include "ptlrpc_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_RPC
#define PET_READY 1
#define PET_TERMINATE 2
Functions
module_param (suppress_pings, int, 0644)
MODULE_PARM_DESC (suppress_pings,"Suppress pings")
int ptlrpc_pinger_suppress_pings ()
struct ptlrpc_request * ptlrpc_prep_ping (struct obd_import *imp)
int ptlrpc_obd_ping (struct obd_device *obd)
static int ptlrpc_ping (struct obd_import *imp)
static void ptlrpc_update_next_ping (struct obd_import *imp, int soon)
void ptlrpc_ping_import_soon (struct obd_import *imp)
static int imp_is_deactive (struct obd_import *imp)
static int ptlrpc_next_reconnect (struct obd_import *imp)
static cfs_duration_t pinger_check_timeout (cfs_time_t time)
void ptlrpc_pinger_ir_up (void)
void ptlrpc_pinger_ir_down (void)
static void ptlrpc_pinger_process_import (struct obd_import *imp, unsigned long this_ping)
static int ptlrpc_pinger_main (void *arg)
int ptlrpc_start_pinger (void)
int ptlrpc_pinger_remove_timeouts (void)
int ptlrpc_stop_pinger (void)
void ptlrpc_pinger_sending_on_import (struct obd_import *imp)
void ptlrpc_pinger_commit_expected (struct obd_import *imp)
int ptlrpc_pinger_add_import (struct obd_import *imp)
int ptlrpc_pinger_del_import (struct obd_import *imp)
static struct timeout_item * ptlrpc_new_timeout (int time, enum timeout_event event, timeout_cb_t cb, void *data)
Register a timeout callback to the pinger list, and the callback will be called when timeout happens.
static struct timeout_item * ptlrpc_pinger_register_timeout (int time, enum timeout_event event, timeout_cb_t cb, void *data)
Register timeout event on the the pinger thread.
int ptlrpc_add_timeout_client (int time, enum timeout_event event, timeout_cb_t cb, void *data, struct list_head *obd_list)
int ptlrpc_del_timeout_client (struct list_head *obd_list, enum timeout_event event)
void ptlrpc_pinger_wake_up ()
static DEFINE_SPINLOCK (pet_lock)
int ping_evictor_wake (struct obd_export *exp)
static int ping_evictor_main (void *arg)
void ping_evictor_start (void)
void ping_evictor_stop (void)
Variables
static int suppress_pings
struct mutex pinger_mutex
static struct list_head pinger_imports
static struct list_head timeout_list
static bool ir_up
static struct ptlrpc_thread pinger_thread
static int pet_refcount = 0
static int pet_state
static wait_queue_head_t pet_waitq
static struct list_head pet_list
Define Documentation
#define DEBUG_SUBSYSTEM S_RPC
Definition at line 41 of file pinger.c.
#define PET_READY 1
Definition at line 574 of file pinger.c.
Referenced by ping_evictor_main(), and ping_evictor_wake().
#define PET_TERMINATE 2
Definition at line 575 of file pinger.c.
Referenced by ping_evictor_main(), and ping_evictor_stop().
Function Documentation
static DEFINE_SPINLOCK (pet_lock) [static]
static int imp_is_deactive (struct obd_import * imp) [inline, static]
Definition at line 137 of file pinger.c.
References obd_import::imp_deactive, OBD_FAIL_CHECK, and OBD_FAIL_PTLRPC_IMP_DEACTIVE.
Referenced by ptlrpc_pinger_process_import().
module_param (suppress_pings , int , 0644)
MODULE_PARM_DESC (suppress_pings , "Suppress pings")
static int ping_evictor_main (void * arg) [static]
Definition at line 605 of file pinger.c.
References CDEBUG, cfs_time_current_sec(), class_decref(), class_export_get(), class_export_put(), class_fail_export(), D_HA, ENTRY, obd_export::exp_client_uuid, obd_export::exp_last_request_time, l_wait_event, LCONSOLE_WARN, list_del_init(), list_empty(), list_entry, list_head::next, obd_device::obd_dev_lock, obd_device::obd_evict_list, obd_export_nid2str(), obd_device::obd_exports_timed, obd_device::obd_name, obd_uuid2str(), pet_list, PET_READY, pet_state, PET_TERMINATE, pet_waitq, PING_EVICT_TIMEOUT, and RETURN.
Referenced by ping_evictor_start().
int ping_evictor_wake (struct obd_export * exp)
Definition at line 583 of file pinger.c.
References class_exp2obd(), class_incref(), list_add(), list_empty(), obd_device::obd_evict_list, pet_list, PET_READY, pet_state, and pet_waitq.
Referenced by ptlrpc_update_export_timer().
static cfs_duration_t pinger_check_timeout (cfs_time_t time) [static]
Definition at line 151 of file pinger.c.
References cfs_time_add(), cfs_time_current(), cfs_time_seconds(), cfs_time_sub(), list_for_each_entry, PING_INTERVAL, pinger_mutex, timeout_item::ti_chain, timeout_item::ti_timeout, and timeout.
Referenced by ptlrpc_pinger_main().
static struct timeout_item* ptlrpc_new_timeout (int time, enum timeout_event event, timeout_cb_t cb, void * data) [static, read]
Register a timeout callback to the pinger list, and the callback will be called when timeout happens.
Definition at line 451 of file pinger.c.
References INIT_LIST_HEAD, OBD_ALLOC_PTR, timeout_item::ti_cb, timeout_item::ti_cb_data, timeout_item::ti_chain, timeout_item::ti_event, timeout_item::ti_obd_list, and timeout_item::ti_timeout.
Referenced by ptlrpc_pinger_register_timeout().
static int ptlrpc_next_reconnect (struct obd_import * imp) [inline, static]
Definition at line 143 of file pinger.c.
References cfs_time_shift(), obd_import::imp_server_timeout, and obd_timeout.
Referenced by ptlrpc_pinger_process_import().
static int ptlrpc_ping (struct obd_import * imp) [static]
Definition at line 98 of file pinger.c.
References CERROR, D_INFO, DEBUG_REQ, ENTRY, obd_import::imp_obd, obd2cli_tgt, obd_device::obd_uuid, ptlrpc_prep_ping(), ptlrpcd_add_req(), RETURN, and obd_uuid::uuid.
Referenced by ptlrpc_pinger_process_import().
void ptlrpc_ping_import_soon (struct obd_import * imp)
Definition at line 132 of file pinger.c.
References cfs_time_current(), and obd_import::imp_next_ping.
void ptlrpc_pinger_commit_expected (struct obd_import * imp)
Definition at line 390 of file pinger.c.
References obd_import::imp_connect_data, obd_import::imp_force_next_verify, obd_import::imp_lock, obd_import::imp_state, LUSTRE_IMP_FULL, OCD_HAS_FLAG, and ptlrpc_update_next_ping().
Referenced by after_reply().
static int ptlrpc_pinger_main (void * arg) [static]
Definition at line 245 of file pinger.c.
References CDEBUG, CFS_DURATION_T, cfs_time_add(), cfs_time_after(), cfs_time_current(), cfs_time_seconds(), CFS_TIME_T, current_pid, D_INFO, D_NET, ENTRY, EXIT, obd_import::imp_next_ping, obd_import::imp_pingable, obd_import::imp_pinger_chain, l_wait_event, list_entry, list_for_each, list_for_each_entry, LWI_TIMEOUT, obd_update_maxusage(), PING_INTERVAL, pinger_check_timeout(), pinger_mutex, ptlrpc_pinger_process_import(), ptlrpc_update_next_ping(), SVC_EVENT, SVC_RUNNING, SVC_STOPPED, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, thread, thread_is_event(), thread_is_stopping(), thread_set_flags(), thread_test_and_clear_flags(), timeout_item::ti_cb, and timeout_item::ti_cb_data.
Referenced by ptlrpc_start_pinger().
static void ptlrpc_pinger_process_import (struct obd_import * imp, unsigned long this_ping) [static]
Definition at line 187 of file pinger.c.
References CDEBUG, CFS_TICK, cfs_time_aftereq(), D_HA, D_INFO, obd_import::imp_connect_data, obd_import::imp_deactive, obd_import::imp_force_next_verify, obd_import::imp_force_verify, imp_is_deactive(), obd_import::imp_lock, obd_import::imp_next_ping, obd_import::imp_no_pinger_recover, obd_import::imp_obd, obd_import::imp_pingable, obd_import::imp_state, ir_up, LUSTRE_IMP_DISCON, LUSTRE_IMP_FULL, obd2cli_tgt, obd_device::obd_no_recov, obd_device::obd_uuid, OCD_HAS_FLAG, ptlrpc_import_state_name(), ptlrpc_initiate_recovery(), ptlrpc_next_reconnect(), ptlrpc_ping(), and obd_uuid::uuid.
Referenced by ptlrpc_pinger_main().
static struct timeout_item* ptlrpc_pinger_register_timeout (int time, enum timeout_event event, timeout_cb_t cb, void * data) [static, read]
Register timeout event on the the pinger thread.
Note: the timeout list is an sorted list with increased timeout value.
Definition at line 476 of file pinger.c.
References LASSERT, list_add(), list_for_each_entry, list_for_each_entry_reverse, pinger_mutex, ptlrpc_new_timeout(), timeout_item::ti_chain, timeout_item::ti_event, and timeout_item::ti_timeout.
Referenced by ptlrpc_add_timeout_client().
int ptlrpc_pinger_remove_timeouts (void)
Definition at line 551 of file pinger.c.
References LASSERT, list_del(), list_empty(), list_for_each_entry_safe, OBD_FREE_PTR, pinger_mutex, timeout_item::ti_chain, and timeout_item::ti_obd_list.
Referenced by ptlrpc_stop_pinger().
void ptlrpc_pinger_sending_on_import (struct obd_import * imp)
Definition at line 385 of file pinger.c.
References ptlrpc_update_next_ping().
Referenced by ptl_send_rpc().
void ptlrpc_pinger_wake_up (void)
Definition at line 565 of file pinger.c.
References pinger_thread, SVC_EVENT, ptlrpc_thread::t_ctl_waitq, and thread_add_flags().
Referenced by ptlrpc_maybe_ping_import_soon(), ptlrpc_pinger_add_import(), and ptlrpc_pinger_force().
int ptlrpc_start_pinger (void)
Definition at line 322 of file pinger.c.
References CERROR, CWARN, ENTRY, l_wait_event, pinger_thread, ptlrpc_pinger_main(), RETURN, suppress_pings, ptlrpc_thread::t_ctl_waitq, ptlrpc_thread::t_name, thread_is_init(), thread_is_running(), and thread_is_stopped().
Referenced by ptlrpc_init().
int ptlrpc_stop_pinger (void)
Definition at line 363 of file pinger.c.
References ENTRY, l_wait_event, pinger_thread, ptlrpc_pinger_remove_timeouts(), RETURN, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, thread_is_init(), thread_is_stopped(), and thread_set_flags().
Referenced by ptlrpc_exit(), and ptlrpc_init().
static void ptlrpc_update_next_ping (struct obd_import * imp, int soon) [static]
Definition at line 118 of file pinger.c.
References at_get(), AT_OFF, cfs_time_shift(), CONNECTION_SWITCH_MIN, imp_at::iat_net_latency, obd_import::imp_at, obd_import::imp_next_ping, obd_import::imp_state, LUSTRE_IMP_DISCON, PING_INTERVAL, and PING_INTERVAL_SHORT.
Referenced by ptlrpc_pinger_add_import(), ptlrpc_pinger_commit_expected(), ptlrpc_pinger_main(), and ptlrpc_pinger_sending_on_import().
Variable Documentation
bool ir_up [static]
Definition at line 171 of file pinger.c.
Referenced by ptlrpc_pinger_ir_down(), ptlrpc_pinger_ir_up(), and ptlrpc_pinger_process_import().
struct list_head pet_list [static]
Definition at line 580 of file pinger.c.
Referenced by ping_evictor_main(), ping_evictor_start(), and ping_evictor_wake().
int pet_refcount = 0 [static]
Definition at line 577 of file pinger.c.
Referenced by ping_evictor_start(), and ping_evictor_stop().
int pet_state [static]
Definition at line 578 of file pinger.c.
Referenced by ping_evictor_main(), ping_evictor_stop(), and ping_evictor_wake().
wait_queue_head_t pet_waitq [static]
Definition at line 579 of file pinger.c.
Referenced by ping_evictor_main(), ping_evictor_start(), ping_evictor_stop(), and ping_evictor_wake().
struct list_head pinger_imports [static]
Initial value:
                LIST_HEAD_INIT(pinger_imports)
Definition at line 53 of file pinger.c.
struct mutex pinger_mutex
Definition at line 52 of file pinger.c.
Referenced by pinger_check_timeout(), ptlrpc_add_timeout_client(), ptlrpc_del_timeout_client(), ptlrpc_init(), ptlrpc_pinger_add_import(), ptlrpc_pinger_del_import(), ptlrpc_pinger_main(), ptlrpc_pinger_register_timeout(), and ptlrpc_pinger_remove_timeouts().
struct ptlrpc_thread pinger_thread [static]
Definition at line 320 of file pinger.c.
Referenced by ptlrpc_pinger_wake_up(), ptlrpc_start_pinger(), and ptlrpc_stop_pinger().
int suppress_pings [static]
Definition at line 48 of file pinger.c.
Referenced by ptlrpc_pinger_suppress_pings(), and ptlrpc_start_pinger().
struct list_head timeout_list [static]
Initial value:
                LIST_HEAD_INIT(timeout_list)
Definition at line 55 of file pinger.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.