Lustre: lnet/selftest/ping_test.c File Reference
lnet/selftest/ping_test.c File Reference
#include "selftest.h"
Data Structures
struct lst_ping_data_t
Defines
#define LST_PING_TEST_MAGIC 0xbabeface
Functions
module_param (ping_srv_workitems, int, 0644)
MODULE_PARM_DESC (ping_srv_workitems,"# PING server workitems")
static int ping_client_init (sfw_test_instance_t *tsi)
static void ping_client_fini (sfw_test_instance_t *tsi)
static int ping_client_prep_rpc (sfw_test_unit_t *tsu, lnet_process_id_t dest, srpc_client_rpc_t **rpc)
static void ping_client_done_rpc (sfw_test_unit_t *tsu, srpc_client_rpc_t *rpc)
static int ping_server_handle (struct srpc_server_rpc *rpc)
void ping_init_test_client (void)
void ping_init_test_service (void)
Variables
static int ping_srv_workitems = SFW_TEST_WI_MAX
static lst_ping_data_t lst_ping_data
sfw_test_client_ops_t ping_test_client
srpc_service_t ping_test_service
Define Documentation
#define LST_PING_TEST_MAGIC 0xbabeface
Definition at line 45 of file ping_test.c.
Referenced by ping_client_done_rpc(), ping_client_prep_rpc(), and ping_server_handle().
Function Documentation
module_param (ping_srv_workitems , int , 0644)
MODULE_PARM_DESC (ping_srv_workitems , "# PING server workitems")
static void ping_client_done_rpc (sfw_test_unit_t * tsu, srpc_client_rpc_t * rpc) [static]
Definition at line 121 of file ping_test.c.
References __swab32s, sfw_batch_t::bat_session, CDEBUG, CERROR, cfs_fs_timeval(), srpc_client_rpc::crpc_dest, srpc_client_rpc::crpc_replymsg, srpc_client_rpc::crpc_reqstmsg, srpc_client_rpc::crpc_status, D_NET, LASSERT, libcfs_id2str(), LST_PING_TEST_MAGIC, srpc_msg::msg_body, srpc_msg::msg_magic, srpc_msg::ping_reply, srpc_msg::ping_reqst, sfw_session_t::sn_ping_errors, SRPC_MSG_MAGIC, sfw_test_instance::tsi_batch, sfw_test_instance::tsi_stopping, and sfw_test_unit::tsu_instance.
Referenced by ping_init_test_client().
static void ping_client_fini (sfw_test_instance_t * tsi) [static]
Definition at line 73 of file ping_test.c.
References sfw_batch_t::bat_session, CDEBUG, CWARN, D_NET, errors, LASSERT, sfw_session_t::sn_ping_errors, sfw_test_instance::tsi_batch, and sfw_test_instance::tsi_is_client.
Referenced by ping_init_test_client().
static int ping_client_init (sfw_test_instance_t * tsi) [static]
Definition at line 59 of file ping_test.c.
References sfw_batch_t::bat_session, LASSERT, LST_FEATS_MASK, lst_ping_data_t::pnd_counter, lst_ping_data_t::pnd_lock, sfw_session_t::sn_features, sfw_test_instance::tsi_batch, and sfw_test_instance::tsi_is_client.
Referenced by ping_init_test_client().
static int ping_client_prep_rpc (sfw_test_unit_t * tsu, lnet_process_id_t dest, srpc_client_rpc_t ** rpc) [static]
Definition at line 89 of file ping_test.c.
References sfw_batch_t::bat_session, cfs_fs_timeval(), LASSERT, LST_FEATS_MASK, LST_PING_TEST_MAGIC, lst_ping_data_t::pnd_counter, lst_ping_data_t::pnd_lock, sfw_create_test_rpc(), sfw_session_t::sn_features, sfw_test_instance::tsi_batch, and sfw_test_unit::tsu_instance.
Referenced by ping_init_test_client().
void ping_init_test_client (void)
Definition at line 215 of file ping_test.c.
References ping_client_done_rpc(), ping_client_fini(), ping_client_init(), ping_client_prep_rpc(), sfw_test_client_ops_t::tso_done_rpc, sfw_test_client_ops_t::tso_fini, sfw_test_client_ops_t::tso_init, and sfw_test_client_ops_t::tso_prep_rpc.
Referenced by sfw_startup().
void ping_init_test_service (void)
Definition at line 224 of file ping_test.c.
References ping_server_handle(), ping_srv_workitems, SRPC_SERVICE_PING, srpc_service::sv_handler, srpc_service::sv_id, srpc_service::sv_name, and srpc_service::sv_wi_total.
Referenced by sfw_startup().
static int ping_server_handle (struct srpc_server_rpc * rpc) [static]
Definition at line 172 of file ping_test.c.
References __swab32, __swab32s, __swab64s, srpc_buffer::buf_msg, CDEBUG, CERROR, D_NET, LASSERT, libcfs_id2str(), LST_FEATS_MASK, LST_PING_TEST_MAGIC, srpc_msg::msg_body, srpc_msg::msg_magic, srpc_msg::msg_ses_feats, srpc_msg::msg_type, srpc_msg::ping_reply, srpc_msg::ping_reqst, srpc_service_cd::scd_svc, SRPC_MSG_MAGIC, srpc_server_rpc::srpc_peer, srpc_server_rpc::srpc_replymsg, srpc_server_rpc::srpc_reqstbuf, srpc_server_rpc::srpc_scd, srpc_service2request(), SRPC_SERVICE_PING, and srpc_service::sv_id.
Referenced by ping_init_test_service().
Variable Documentation
lst_ping_data_t lst_ping_data [static]
Definition at line 56 of file ping_test.c.
int ping_srv_workitems = SFW_TEST_WI_MAX [static]
Definition at line 47 of file ping_test.c.
Referenced by ping_init_test_service().
sfw_test_client_ops_t ping_test_client
Definition at line 214 of file ping_test.c.
Referenced by sfw_startup().
srpc_service_t ping_test_service
Definition at line 223 of file ping_test.c.
Referenced by sfw_startup().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.