Lustre: lnet/utils/portals.c File Reference
lnet/utils/portals.c File Reference
#include <errno.h>
#include <getopt.h>
#include <inttypes.h>
#include <limits.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/ioctl.h>
#include <sys/time.h>
#include <time.h>
#include <linux/types.h>
#include <libcfs/util/ioctl.h>
#include <libcfs/libcfs_debug.h>
#include <lnet/lnetctl.h>
#include <lnet/socklnd.h>
#include <lnet/lnet.h>
Defines
#define IOC_BUF_SIZE 8192
Functions
int lnet_parse_bool (int *b, char *str)
int lnet_parse_port (int *port, char *str)
int lnet_parse_ipquad (__u32 *ipaddrp, char *str)
int lnet_parse_ipaddr (__u32 *ipaddrp, char *str)
char * ptl_ipaddr_2_str (__u32 ipaddr, char *str, size_t strsize, int lookup)
int lnet_parse_time (time_t *t, char *str)
int lnet_parse_nid (char *nid_str, lnet_process_id_t *id_ptr)
static int g_net_is_set (char *cmd)
static int g_net_is_compatible (char *cmd,...)
int ptl_initialize (int argc, char **argv)
int jt_ptl_network (int argc, char **argv)
int jt_ptl_list_nids (int argc, char **argv)
int jt_ptl_which_nid (int argc, char **argv)
int jt_ptl_print_interfaces (int argc, char **argv)
int jt_ptl_add_interface (int argc, char **argv)
int jt_ptl_del_interface (int argc, char **argv)
int jt_ptl_print_peers (int argc, char **argv)
int jt_ptl_add_peer (int argc, char **argv)
int jt_ptl_del_peer (int argc, char **argv)
int jt_ptl_print_connections (int argc, char **argv)
int jt_ptl_disconnect (int argc, char **argv)
int jt_ptl_push_connection (int argc, char **argv)
int jt_ptl_ping (int argc, char **argv)
int jt_ptl_mynid (int argc, char **argv)
int jt_ptl_fail_nid (int argc, char **argv)
int jt_ptl_add_route (int argc, char **argv)
int jt_ptl_del_route (int argc, char **argv)
int jt_ptl_notify_router (int argc, char **argv)
int jt_ptl_print_routes (int argc, char **argv)
static int fault_attr_nid_parse (char *str, lnet_nid_t *nid_p)
static int fault_attr_msg_parse (char *msg_str, __u32 *mask_p)
static int fault_attr_ptl_parse (char *ptl_str, __u64 *mask_p)
static int fault_simul_rule_add (__u32 opc, char *name, int argc, char **argv)
int jt_ptl_drop_add (int argc, char **argv)
int jt_ptl_delay_add (int argc, char **argv)
static int fault_simul_rule_del (__u32 opc, char *name, int argc, char **argv)
int jt_ptl_drop_del (int argc, char **argv)
int jt_ptl_delay_del (int argc, char **argv)
static int fault_simul_rule_reset (__u32 opc, char *name, int argc, char **argv)
int jt_ptl_drop_reset (int argc, char **argv)
int jt_ptl_delay_reset (int argc, char **argv)
static int fault_simul_rule_list (__u32 opc, char *name, int argc, char **argv)
int jt_ptl_drop_list (int argc, char **argv)
int jt_ptl_delay_list (int argc, char **argv)
double get_cycles_per_usec ()
int jt_ptl_testprotocompat (int argc, char **argv)
Variables
unsigned int libcfs_debug
unsigned int libcfs_printk = D_CANTMASK
static bool g_net_interactive
static bool g_net_set
static __u32 g_net
static char local_buf [IOC_BUF_SIZE]
static char * ioc_buf = local_buf
Define Documentation
#define IOC_BUF_SIZE 8192
Definition at line 52 of file portals.c.
Referenced by fault_simul_rule_add(), fault_simul_rule_del(), and fault_simul_rule_list().
Function Documentation
static int fault_attr_msg_parse (char * msg_str, __u32 * mask_p) [static]
Definition at line 1276 of file portals.c.
References LNET_ACK_BIT, LNET_GET_BIT, LNET_PUT_BIT, and LNET_REPLY_BIT.
Referenced by fault_simul_rule_add().
static int fault_attr_nid_parse (char * str, lnet_nid_t * nid_p) [static]
Definition at line 1249 of file portals.c.
References libcfs_str2anynid(), libcfs_str2net(), LNET_MKNID(), LNET_NID_ANY, LNET_NIDADDR(), and LNET_NIDNET().
Referenced by fault_simul_rule_add(), and fault_simul_rule_del().
static int fault_attr_ptl_parse (char * ptl_str, __u64 * mask_p) [static]
Definition at line 1300 of file portals.c.
References optarg.
Referenced by fault_simul_rule_add().
static int fault_simul_rule_add (__u32 opc, char * name, int argc, char ** argv) [static]
Definition at line 1314 of file portals.c.
References lnet_fault_attr::delay, lnet_fault_attr::drop, lnet_fault_attr::fa_dst, lnet_fault_attr::fa_msg_mask, lnet_fault_attr::fa_ptl_mask, lnet_fault_attr::fa_src, fault_attr_msg_parse(), fault_attr_nid_parse(), fault_attr_ptl_parse(), ioc_buf, IOC_BUF_SIZE, libcfs_ioctl_data::ioc_flags, libcfs_ioctl_data::ioc_inlbuf1, libcfs_ioctl_data::ioc_inllen1, IOC_LIBCFS_LNET_FAULT, l_ioctl(), libcfs_ioctl_pack(), libcfs_nid2str(), LNET_CTL_DELAY_ADD, LNET_CTL_DROP_ADD, LNET_DEV_ID, optarg, optind, and lnet_fault_attr::u.
Referenced by jt_ptl_delay_add(), and jt_ptl_drop_add().
static int fault_simul_rule_del (__u32 opc, char * name, int argc, char ** argv) [static]
Definition at line 1469 of file portals.c.
References lnet_fault_attr::fa_dst, lnet_fault_attr::fa_src, fault_attr_nid_parse(), ioc_buf, IOC_BUF_SIZE, libcfs_ioctl_data::ioc_count, libcfs_ioctl_data::ioc_flags, libcfs_ioctl_data::ioc_inlbuf1, libcfs_ioctl_data::ioc_inllen1, IOC_LIBCFS_LNET_FAULT, l_ioctl(), libcfs_ioctl_pack(), libcfs_ioctl_unpack(), libcfs_nid2str(), LNET_DEV_ID, optarg, and optind.
Referenced by jt_ptl_delay_del(), and jt_ptl_drop_del().
static int fault_simul_rule_list (__u32 opc, char * name, int argc, char ** argv) [static]
Definition at line 1589 of file portals.c.
References lnet_fault_stat::delay, lnet_fault_attr::delay, lnet_fault_stat::drop, lnet_fault_attr::drop, lnet_fault_attr::fa_dst, lnet_fault_attr::fa_msg_mask, lnet_fault_attr::fa_ptl_mask, lnet_fault_attr::fa_src, lnet_fault_stat::fs_ack, lnet_fault_stat::fs_count, lnet_fault_stat::fs_get, lnet_fault_stat::fs_put, lnet_fault_stat::fs_reply, ioc_buf, IOC_BUF_SIZE, libcfs_ioctl_data::ioc_count, libcfs_ioctl_data::ioc_flags, libcfs_ioctl_data::ioc_inlbuf1, libcfs_ioctl_data::ioc_inlbuf2, libcfs_ioctl_data::ioc_inllen1, libcfs_ioctl_data::ioc_inllen2, IOC_LIBCFS_LNET_FAULT, l_ioctl(), libcfs_ioctl_pack(), libcfs_ioctl_unpack(), libcfs_nid2str(), LNET_CTL_DELAY_LIST, LNET_CTL_DROP_LIST, LNET_DEV_ID, lnet_fault_stat::u, and lnet_fault_attr::u.
Referenced by jt_ptl_delay_list(), and jt_ptl_drop_list().
static int fault_simul_rule_reset (__u32 opc, char * name, int argc, char ** argv) [static]
Definition at line 1558 of file portals.c.
References libcfs_ioctl_data::ioc_flags, IOC_LIBCFS_LNET_FAULT, l_ioctl(), LIBCFS_IOC_INIT, and LNET_DEV_ID.
Referenced by jt_ptl_delay_reset(), and jt_ptl_drop_reset().
static int g_net_is_compatible (char * cmd, ...) [static]
Definition at line 255 of file portals.c.
References g_net, g_net_is_set(), libcfs_lnd2str(), and LNET_NETTYP().
Referenced by jt_ptl_add_interface(), jt_ptl_add_peer(), jt_ptl_del_interface(), jt_ptl_del_peer(), jt_ptl_disconnect(), jt_ptl_print_connections(), jt_ptl_print_interfaces(), jt_ptl_print_peers(), and jt_ptl_push_connection().
static int g_net_is_set (char * cmd) [static]
Definition at line 233 of file portals.c.
References g_net_interactive, and g_net_set.
Referenced by g_net_is_compatible(), and jt_ptl_add_route().
double get_cycles_per_usec ()
Definition at line 1670 of file portals.c.
int jt_ptl_add_interface (int argc, char ** argv)
Definition at line 509 of file portals.c.
References end, g_net, g_net_is_compatible(), IOC_LIBCFS_ADD_INTERFACE, libcfs_ioctl_data::ioc_net, libcfs_ioctl_data::ioc_u32, l_ioctl(), LIBCFS_IOC_INIT, LNET_DEV_ID, lnet_parse_ipaddr(), lnet_parse_ipquad(), and SOCKLND.
int jt_ptl_add_peer (int argc, char ** argv)
Definition at line 665 of file portals.c.
References g_net, g_net_is_compatible(), GNILND, IOC_LIBCFS_ADD_PEER, libcfs_ioctl_data::ioc_net, libcfs_ioctl_data::ioc_nid, libcfs_ioctl_data::ioc_u32, l_ioctl(), LIBCFS_IOC_INIT, libcfs_str2nid(), LNET_DEV_ID, LNET_NID_ANY, lnet_parse_ipaddr(), lnet_parse_port(), and SOCKLND.
int jt_ptl_add_route (int argc, char ** argv)
Definition at line 1060 of file portals.c.
References lnet_ioctl_config_data::cfg_config_u, lnet_ioctl_config_data::cfg_hdr, lnet_ioctl_config_data::cfg_net, lnet_ioctl_config_data::cfg_nid, lnet_ioctl_config_data::cfg_route, end, g_net, g_net_is_set(), IOC_LIBCFS_ADD_ROUTE, l_ioctl(), LIBCFS_IOC_INIT_V2, libcfs_str2nid(), LNET_DEV_ID, LNET_NID_ANY, and LNET_UNDEFINED_HOPS.
int jt_ptl_del_interface (int argc, char ** argv)
Definition at line 560 of file portals.c.
References g_net, g_net_is_compatible(), IOC_LIBCFS_DEL_INTERFACE, libcfs_ioctl_data::ioc_net, libcfs_ioctl_data::ioc_u32, l_ioctl(), LIBCFS_IOC_INIT, LNET_DEV_ID, lnet_parse_ipaddr(), and SOCKLND.
int jt_ptl_del_peer (int argc, char ** argv)
Definition at line 715 of file portals.c.
References g_net, g_net_is_compatible(), GNILND, IOC_LIBCFS_DEL_PEER, libcfs_ioctl_data::ioc_net, libcfs_ioctl_data::ioc_nid, libcfs_ioctl_data::ioc_u32, l_ioctl(), LIBCFS_IOC_INIT, libcfs_str2anynid(), LNET_DEV_ID, LNET_NID_ANY, lnet_parse_ipaddr(), LNET_PID_ANY, O2IBLND, and SOCKLND.
int jt_ptl_del_route (int argc, char ** argv)
Definition at line 1120 of file portals.c.
References lnet_ioctl_config_data::cfg_hdr, lnet_ioctl_config_data::cfg_net, lnet_ioctl_config_data::cfg_nid, g_net, g_net_set, IOC_LIBCFS_DEL_ROUTE, l_ioctl(), LIBCFS_IOC_INIT_V2, libcfs_nid2str(), libcfs_str2anynid(), LNET_DEV_ID, LNET_NID_ANY, and LNET_NIDNET().
int jt_ptl_delay_add (int argc, char ** argv)
Definition at line 1463 of file portals.c.
References fault_simul_rule_add(), and LNET_CTL_DELAY_ADD.
int jt_ptl_delay_del (int argc, char ** argv)
Definition at line 1552 of file portals.c.
References fault_simul_rule_del(), and LNET_CTL_DELAY_DEL.
int jt_ptl_delay_list (int argc, char ** argv)
Definition at line 1664 of file portals.c.
References fault_simul_rule_list(), and LNET_CTL_DELAY_LIST.
int jt_ptl_delay_reset (int argc, char ** argv)
Definition at line 1582 of file portals.c.
References fault_simul_rule_reset(), and LNET_CTL_DELAY_RESET.
int jt_ptl_disconnect (int argc, char ** argv)
Definition at line 834 of file portals.c.
References g_net, g_net_is_compatible(), GNILND, IOC_LIBCFS_CLOSE_CONNECTION, libcfs_ioctl_data::ioc_net, libcfs_ioctl_data::ioc_nid, libcfs_ioctl_data::ioc_u32, l_ioctl(), LIBCFS_IOC_INIT, libcfs_str2anynid(), LNET_DEV_ID, LNET_NID_ANY, lnet_parse_ipaddr(), O2IBLND, and SOCKLND.
int jt_ptl_drop_add (int argc, char ** argv)
Definition at line 1457 of file portals.c.
References fault_simul_rule_add(), and LNET_CTL_DROP_ADD.
int jt_ptl_drop_del (int argc, char ** argv)
Definition at line 1546 of file portals.c.
References fault_simul_rule_del(), and LNET_CTL_DROP_DEL.
int jt_ptl_drop_list (int argc, char ** argv)
Definition at line 1658 of file portals.c.
References fault_simul_rule_list(), and LNET_CTL_DROP_LIST.
int jt_ptl_drop_reset (int argc, char ** argv)
Definition at line 1576 of file portals.c.
References fault_simul_rule_reset(), and LNET_CTL_DROP_RESET.
int jt_ptl_fail_nid (int argc, char ** argv)
Definition at line 1019 of file portals.c.
References libcfs_ioctl_data::ioc_count, IOC_LIBCFS_FAIL_NID, libcfs_ioctl_data::ioc_nid, l_ioctl(), LIBCFS_IOC_INIT, libcfs_str2anynid(), LNET_DEV_ID, and LNET_MD_THRESH_INF.
int jt_ptl_list_nids (int argc, char ** argv)
Definition at line 356 of file portals.c.
References __u64, libcfs_ioctl_data::ioc_count, IOC_LIBCFS_GET_NI, libcfs_ioctl_data::ioc_nid, l_ioctl(), LIBCFS_IOC_INIT, libcfs_nid2str(), LNET_DEV_ID, LNET_NETTYP(), LNET_NIDNET(), and LOLND.
int jt_ptl_mynid (int argc, char ** argv)
Definition at line 987 of file portals.c.
References IOC_LIBCFS_REGISTER_MYNID, libcfs_ioctl_data::ioc_net, libcfs_ioctl_data::ioc_nid, l_ioctl(), LIBCFS_IOC_INIT, libcfs_nid2str(), libcfs_str2nid(), LNET_DEV_ID, LNET_NID_ANY, and LNET_NIDNET().
int jt_ptl_network (int argc, char ** argv)
Definition at line 295 of file portals.c.
References CIBLND, g_net, g_net_set, GMLND, IIBLND, IOC_LIBCFS_CONFIGURE, IOC_LIBCFS_UNCONFIGURE, l_ioctl(), LIBCFS_IOC_INIT, libcfs_lnd2str(), libcfs_str2net(), LNET_DEV_ID, LNET_NETTYP(), LNET_NID_ANY, LNET_NIDNET(), MXLND, OPENIBLND, PTLLND, QSWLND, RALND, and VIBLND.
Referenced by jt_opt_net().
int jt_ptl_notify_router (int argc, char ** argv)
Definition at line 1152 of file portals.c.
References __u64, libcfs_ioctl_data::ioc_flags, IOC_LIBCFS_NOTIFY_ROUTER, libcfs_ioctl_data::ioc_nid, libcfs_ioctl_data::ioc_u64, l_ioctl(), LIBCFS_IOC_INIT, libcfs_nid2str(), libcfs_str2nid(), LNET_DEV_ID, LNET_NID_ANY, lnet_parse_bool(), and lnet_parse_time().
int jt_ptl_ping (int argc, char ** argv)
Definition at line 911 of file portals.c.
References end, libcfs_ioctl_data::ioc_count, IOC_LIBCFS_PING, libcfs_ioctl_data::ioc_nid, libcfs_ioctl_data::ioc_pbuf1, libcfs_ioctl_data::ioc_plen1, libcfs_ioctl_data::ioc_u32, l_ioctl(), libcfs_id2str(), LIBCFS_IOC_INIT, libcfs_nid2str(), libcfs_str2nid(), LNET_DEV_ID, LNET_NID_ANY, lnet_parse_nid(), LNET_PID_ANY, LNET_PID_USERFLAG, and timeout.
int jt_ptl_print_connections (int argc, char ** argv)
Definition at line 769 of file portals.c.
References g_net, g_net_is_compatible(), GNILND, libcfs_ioctl_data::ioc_count, libcfs_ioctl_data::ioc_flags, IOC_LIBCFS_GET_CONN, libcfs_ioctl_data::ioc_net, libcfs_ioctl_data::ioc_nid, libcfs_ioctl_data::ioc_u32, l_ioctl(), libcfs_id2str(), LIBCFS_IOC_INIT, libcfs_nid2str(), LNET_DEV_ID, O2IBLND, ptl_ipaddr_2_str(), SOCKLND, SOCKLND_CONN_ANY, SOCKLND_CONN_BULK_IN, SOCKLND_CONN_BULK_OUT, and SOCKLND_CONN_CONTROL.
int jt_ptl_print_interfaces (int argc, char ** argv)
Definition at line 466 of file portals.c.
References g_net, g_net_is_compatible(), libcfs_ioctl_data::ioc_count, IOC_LIBCFS_GET_INTERFACE, libcfs_ioctl_data::ioc_net, libcfs_ioctl_data::ioc_u32, l_ioctl(), LIBCFS_IOC_INIT, LNET_DEV_ID, ptl_ipaddr_2_str(), and SOCKLND.
int jt_ptl_print_peers (int argc, char ** argv)
Definition at line 595 of file portals.c.
References g_net, g_net_is_compatible(), GNILND, libcfs_ioctl_data::ioc_count, libcfs_ioctl_data::ioc_flags, IOC_LIBCFS_GET_PEER, libcfs_ioctl_data::ioc_net, libcfs_ioctl_data::ioc_nid, libcfs_ioctl_data::ioc_u32, libcfs_ioctl_data::ioc_u64, l_ioctl(), libcfs_id2str(), LIBCFS_IOC_INIT, libcfs_nid2str(), LNET_DEV_ID, O2IBLND, ptl_ipaddr_2_str(), SOCKLND, and state.
int jt_ptl_print_routes (int argc, char ** argv)
Definition at line 1211 of file portals.c.
References lnet_ioctl_config_data::cfg_config_u, lnet_ioctl_config_data::cfg_count, lnet_ioctl_config_data::cfg_hdr, lnet_ioctl_config_data::cfg_net, lnet_ioctl_config_data::cfg_nid, lnet_ioctl_config_data::cfg_route, IOC_LIBCFS_GET_ROUTE, l_ioctl(), LIBCFS_IOC_INIT_V2, libcfs_net2str(), libcfs_nid2str(), and LNET_DEV_ID.
int jt_ptl_push_connection (int argc, char ** argv)
Definition at line 877 of file portals.c.
References g_net, g_net_is_compatible(), GNILND, IOC_LIBCFS_PUSH_CONNECTION, libcfs_ioctl_data::ioc_net, libcfs_ioctl_data::ioc_nid, l_ioctl(), LIBCFS_IOC_INIT, libcfs_str2anynid(), LNET_DEV_ID, LNET_NID_ANY, and SOCKLND.
int jt_ptl_testprotocompat (int argc, char ** argv)
Definition at line 1689 of file portals.c.
References end, libcfs_ioctl_data::ioc_flags, IOC_LIBCFS_TESTPROTOCOMPAT, l_ioctl(), LIBCFS_IOC_INIT, and LNET_DEV_ID.
int jt_ptl_which_nid (int argc, char ** argv)
Definition at line 399 of file portals.c.
References IOC_LIBCFS_LNET_DIST, libcfs_ioctl_data::ioc_nid, libcfs_ioctl_data::ioc_u32, l_ioctl(), LIBCFS_IOC_INIT, libcfs_nid2str(), libcfs_str2nid(), LNET_DEV_ID, LNET_NID_ANY, and order.
int lnet_parse_bool (int * b, char * str)
Definition at line 58 of file portals.c.
Referenced by jt_ptl_notify_router().
int lnet_parse_ipaddr (__u32 * ipaddrp, char * str)
Definition at line 140 of file portals.c.
References lnet_parse_ipquad().
Referenced by jt_ptl_add_interface(), jt_ptl_add_peer(), jt_ptl_del_interface(), jt_ptl_del_peer(), and jt_ptl_disconnect().
int lnet_parse_ipquad (__u32 * ipaddrp, char * str)
Definition at line 121 of file portals.c.
Referenced by jt_ptl_add_interface(), and lnet_parse_ipaddr().
int lnet_parse_nid (char * nid_str, lnet_process_id_t * id_ptr)
Definition at line 221 of file portals.c.
References libcfs_str2nid(), LNET_NID_ANY, LNET_PID_ANY, lnet_process_id_t::nid, and lnet_process_id_t::pid.
Referenced by jt_ptl_ping().
int lnet_parse_port (int * port, char * str)
Definition at line 84 of file portals.c.
References end.
Referenced by jt_ptl_add_peer().
int lnet_parse_time (time_t * t, char * str)
Definition at line 192 of file portals.c.
References end.
Referenced by jt_ptl_notify_router().
int ptl_initialize (int argc, char ** argv)
Definition at line 284 of file portals.c.
References g_net_interactive, LNET_DEV_ID, LNET_DEV_MAJOR, LNET_DEV_MINOR, LNET_DEV_PATH, and register_ioc_dev().
Referenced by lctl_main(), and main().
char* ptl_ipaddr_2_str (__u32 ipaddr, char * str, size_t strsize, int lookup)
Definition at line 169 of file portals.c.
References strlcpy().
Referenced by jt_ptl_print_connections(), jt_ptl_print_interfaces(), and jt_ptl_print_peers().
Variable Documentation
__u32 g_net [static]
Definition at line 50 of file portals.c.
Referenced by g_net_is_compatible(), jt_ptl_add_interface(), jt_ptl_add_peer(), jt_ptl_add_route(), jt_ptl_del_interface(), jt_ptl_del_peer(), jt_ptl_del_route(), jt_ptl_disconnect(), jt_ptl_network(), jt_ptl_print_connections(), jt_ptl_print_interfaces(), jt_ptl_print_peers(), and jt_ptl_push_connection().
bool g_net_interactive [static]
Definition at line 48 of file portals.c.
Referenced by g_net_is_set(), and ptl_initialize().
bool g_net_set [static]
Definition at line 49 of file portals.c.
Referenced by g_net_is_set(), jt_ptl_del_route(), and jt_ptl_network().
char* ioc_buf = local_buf [static]
Definition at line 54 of file portals.c.
Referenced by fault_simul_rule_add(), fault_simul_rule_del(), and fault_simul_rule_list().
unsigned int libcfs_debug
Definition at line 45 of file portals.c.
Referenced by class_handle_ioctl(), ldlm_dump_all_namespaces(), ldlm_lock_dump_handle(), ldlm_namespace_dump(), ldlm_resource_dump(), and print_lustre_cfg().
unsigned int libcfs_printk = D_CANTMASK
Definition at line 46 of file portals.c.
Referenced by __proc_dobitmasks(), cfs_print_to_console(), and libcfs_debug_vmsg2().
char local_buf[IOC_BUF_SIZE] [static]
Definition at line 53 of file portals.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.