Lustre: libcfs/libcfs/prng.c File Reference
libcfs/libcfs/prng.c File Reference
#include <linux/random.h>
#include <libcfs/libcfs.h>
Defines
#define RANDOM_CONST_A 18030
#define RANDOM_CONST_B 29013
Functions
unsigned int cfs_rand (void)
cfs_rand - creates new seeds
void cfs_srand (unsigned int seed1, unsigned int seed2)
cfs_srand - sets the inital seed : (seed_x) should have the most entropy in the low bits of the word : (seed_y) should have the most entropy in the high bits of the word
void cfs_get_random_bytes (void *buf, int size)
cfs_get_random_bytes - generate a bunch of random numbers : buffer to fill with random numbers : size of passed in buffer
Variables
static unsigned int seed_x = 521288629
static unsigned int seed_y = 362436069
Define Documentation
#define RANDOM_CONST_A 18030
Definition at line 64 of file prng.c.
Referenced by cfs_rand().
#define RANDOM_CONST_B 29013
Definition at line 65 of file prng.c.
Referenced by cfs_rand().
Function Documentation
void cfs_get_random_bytes (void * buf, int size)
cfs_get_random_bytes - generate a bunch of random numbers : buffer to fill with random numbers : size of passed in buffer
Fills a buffer with random bytes
Definition at line 111 of file prng.c.
References cfs_rand(), and LASSERT.
Referenced by class_handle_init(), gss_init_svc_upcall(), gss_wrap_bulk_kerberos(), gss_wrap_kerberos(), lnet_shuffle_seed(), lustre_init(), and ptlrpc_init_xid().
unsigned int cfs_rand (void)
cfs_rand - creates new seeds
First it creates new seeds from the previous seeds. Then it generates a new psuedo random number for use.
Returns a pseudo-random 32-bit integer
Definition at line 78 of file prng.c.
References RANDOM_CONST_A, RANDOM_CONST_B, seed_x, and seed_y.
Referenced by __cfs_fail_check_set(), cfs_get_random_bytes(), delay_rule_match(), drop_rule_match(), llog_test_setup(), lnet_add_route_to_rnet(), lnet_delay_rule_add(), lnet_delay_rule_reset(), lnet_drop_rule_add(), lnet_drop_rule_reset(), lod_alloc_qos(), lod_alloc_rr(), and mgc_requeue_thread().
void cfs_srand (unsigned int seed1, unsigned int seed2)
cfs_srand - sets the inital seed : (seed_x) should have the most entropy in the low bits of the word : (seed_y) should have the most entropy in the high bits of the word
Replaces the original seeds with new values. Used to generate a new pseudo random numbers.
Definition at line 95 of file prng.c.
References seed_x, and seed_y.
Referenced by class_handle_init(), lnet_shuffle_seed(), and lustre_init().
Variable Documentation
unsigned int seed_x = 521288629 [static]
Definition at line 67 of file prng.c.
Referenced by cfs_rand(), and cfs_srand().
unsigned int seed_y = 362436069 [static]
Definition at line 68 of file prng.c.
Referenced by cfs_rand(), and cfs_srand().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.