Lustre: lustre/ptlrpc/ptlrpc_internal.h File Reference
lustre/ptlrpc/ptlrpc_internal.h File Reference
#include "../ldlm/ldlm_internal.h"
Data Structures
struct nrs_core
NRS core object.
Variables
int test_req_buffer_pressure
struct list_head ptlrpc_all_services
Holds a list of all PTLRPC services.
struct mutex ptlrpc_all_services_mutex
Used to protect the ptlrpc_all_services list.
struct ptlrpc_nrs_pol_conf nrs_conf_fifo
FIFO policy configuration.
#define ptlrpc_lprocfs_register_service(params...) do{}while(0)
#define ptlrpc_lprocfs_unregister_service(params...) do{}while(0)
#define ptlrpc_lprocfs_rpc_sent(params...) do{}while(0)
#define ptlrpc_lprocfs_do_request_stat(params...) do{}while(0)
#define NRS_LPROCFS_QUANTUM_NAME_REG "reg_quantum:"
#define NRS_LPROCFS_QUANTUM_NAME_HP "hp_quantum:"
#define LPROCFS_NRS_QUANTUM_MAX 65535
the maximum size of nrs_crrn_client::cc_quantum and nrs_orr_data::od_quantum.
#define LPROCFS_NRS_WR_QUANTUM_MAX_CMD
Max valid command string is the size of the labels, plus "65535" twice, plus a separating space character.
struct nrs_core nrs_core
nrs
struct mutex ptlrpcd_mutex
struct mutex pinger_mutex
int ptlrpc_start_thread (struct ptlrpc_service_part *svcpt, int wait)
int ptlrpcd_start (struct ptlrpcd_ctl *pc)
void ptlrpc_at_adj_net_latency (struct ptlrpc_request *req, unsigned int service_time)
struct ptlrpc_bulk_desc * ptlrpc_new_bulk (unsigned npages, unsigned max_brw, enum ptlrpc_bulk_op_type type, unsigned portal, const struct ptlrpc_bulk_frag_ops *ops)
Allocate and initialize new bulk descriptor on the sender.
int ptlrpc_request_cache_init (void)
void ptlrpc_request_cache_fini (void)
struct ptlrpc_request * ptlrpc_request_cache_alloc (gfp_t flags)
void ptlrpc_request_cache_free (struct ptlrpc_request *req)
void ptlrpc_init_xid (void)
void ptlrpc_set_add_new_req (struct ptlrpcd_ctl *pc, struct ptlrpc_request *req)
Add a request to a request with dedicated server thread and wake the thread to make any necessary processing.
int ptlrpc_expired_set (void *data)
Time out all uncompleted requests in request set pointed by data Callback used when waiting on sets with l_wait_event.
int ptlrpc_set_next_timeout (struct ptlrpc_request_set *)
Get the smallest timeout in the set; this does NOT set a timeout.
void ptlrpc_resend_req (struct ptlrpc_request *request)
Schedule previously sent request for resend.
void ptlrpc_set_bulk_mbits (struct ptlrpc_request *req)
If request has a new allocated XID (new request or EINPROGRESS resend), use this XID as matchbits of bulk, otherwise allocate a new matchbits for request to ensure previous bulk fails and avoid problems with lost replies and therefore several transfers landing into the same buffer from different sending attempts.
void ptlrpc_assign_next_xid_nolock (struct ptlrpc_request *req)
__u64 ptlrpc_known_replied_xid (struct obd_import *imp)
void ptlrpc_add_unreplied (struct ptlrpc_request *req)
int ptlrpc_init_portals (void)
void ptlrpc_exit_portals (void)
void ptlrpc_request_handle_notconn (struct ptlrpc_request *)
void lustre_assert_wire_constants (void)
int ptlrpc_import_in_recovery (struct obd_import *imp)
int ptlrpc_set_import_discon (struct obd_import *imp, __u32 conn_cnt)
Returns true if import was FULL, false if import was already not connected.
void ptlrpc_handle_failed_import (struct obd_import *imp)
int ptlrpc_replay_next (struct obd_import *imp, int *inflight)
Identify what request from replay list needs to be replayed next (based on what we have already replayed) and send it to server.
void ptlrpc_initiate_recovery (struct obd_import *imp)
Start recovery on disconnected import.
int lustre_unpack_req_ptlrpc_body (struct ptlrpc_request *req, int offset)
int lustre_unpack_rep_ptlrpc_body (struct ptlrpc_request *req, int offset)
int ptlrpc_service_nrs_setup (struct ptlrpc_service *svc)
Setup NRS heads on all service partitions of service svc, and register all compatible policies on those NRS heads.
void ptlrpc_service_nrs_cleanup (struct ptlrpc_service *svc)
Unregisters all policies on all service partitions of service svc.
void ptlrpc_nrs_req_initialize (struct ptlrpc_service_part *svcpt, struct ptlrpc_request *req, bool hp)
Obtains NRS head resources for request req.
void ptlrpc_nrs_req_finalize (struct ptlrpc_request *req)
Releases resources for a request; is called after the request has been handled.
void ptlrpc_nrs_req_stop_nolock (struct ptlrpc_request *req)
void ptlrpc_nrs_req_add (struct ptlrpc_service_part *svcpt, struct ptlrpc_request *req, bool hp)
Enqueues request req on either the regular or high-priority NRS head of service partition svcpt.
struct ptlrpc_request * ptlrpc_nrs_req_get_nolock0 (struct ptlrpc_service_part *svcpt, bool hp, bool peek, bool force)
Obtains a request for handling from an NRS head of service partition svcpt.
static struct ptlrpc_request * ptlrpc_nrs_req_get_nolock (struct ptlrpc_service_part *svcpt, bool hp, bool force)
static struct ptlrpc_request * ptlrpc_nrs_req_peek_nolock (struct ptlrpc_service_part *svcpt, bool hp)
void ptlrpc_nrs_req_del_nolock (struct ptlrpc_request *req)
Dequeues request req from the policy it has been enqueued on.
bool ptlrpc_nrs_req_pending_nolock (struct ptlrpc_service_part *svcpt, bool hp)
Returns whether there are any requests currently enqueued on any of the policies of service partition's svcpt NRS head specified by hp.
bool ptlrpc_nrs_req_throttling_nolock (struct ptlrpc_service_part *svcpt, bool hp)
Returns whether NRS policy is throttling reqeust.
int ptlrpc_nrs_policy_control (const struct ptlrpc_service *svc, enum ptlrpc_nrs_queue_type queue, char *name, enum ptlrpc_nrs_ctl opc, bool single, void *arg)
Carries out a control operation opc on the policy identified by the human-readable name, on either all partitions, or only on the first partition of service svc.
int ptlrpc_nrs_init (void)
Adds all policies that ship with the ptlrpc module, to NRS core's list of policies nrs_core.nrs_policies.
void ptlrpc_nrs_fini (void)
Removes all policy descriptors from nrs_core::nrs_policies, and frees the policy descriptors.
static bool nrs_svcpt_has_hp (const struct ptlrpc_service_part *svcpt)
static bool nrs_svc_has_hp (const struct ptlrpc_service *svc)
static struct ptlrpc_nrs * nrs_svcpt2nrs (struct ptlrpc_service_part *svcpt, bool hp)
static int nrs_pol2cptid (const struct ptlrpc_nrs_policy *policy)
static struct ptlrpc_service * nrs_pol2svc (struct ptlrpc_nrs_policy *policy)
static struct ptlrpc_service_part * nrs_pol2svcpt (struct ptlrpc_nrs_policy *policy)
static struct cfs_cpt_table * nrs_pol2cptab (struct ptlrpc_nrs_policy *policy)
static struct ptlrpc_nrs_resource * nrs_request_resource (struct ptlrpc_nrs_request *nrq)
static struct ptlrpc_nrs_policy * nrs_request_policy (struct ptlrpc_nrs_request *nrq)
int ptlrpc_expire_one_request (struct ptlrpc_request *req, int async_unlink)
Time out request req.
void ptlrpc_fill_bulk_md (lnet_md_t *md, struct ptlrpc_bulk_desc *desc, int mdcnt)
struct ptlrpc_reply_state * lustre_get_emerg_rs (struct ptlrpc_service_part *svcpt)
void lustre_put_emerg_rs (struct ptlrpc_reply_state *rs)
int ptlrpc_start_pinger (void)
int ptlrpc_stop_pinger (void)
void ptlrpc_pinger_sending_on_import (struct obd_import *imp)
void ptlrpc_pinger_commit_expected (struct obd_import *imp)
void ptlrpc_pinger_wake_up (void)
void ptlrpc_ping_import_soon (struct obd_import *imp)
int ping_evictor_wake (struct obd_export *exp)
int sptlrpc_null_init (void)
void sptlrpc_null_fini (void)
int sptlrpc_plain_init (void)
void sptlrpc_plain_fini (void)
int sptlrpc_enc_pool_init (void)
void sptlrpc_enc_pool_fini (void)
int sptlrpc_proc_enc_pool_seq_show (struct seq_file *m, void *v)
int sptlrpc_lproc_init (void)
void sptlrpc_lproc_fini (void)
int sptlrpc_gc_init (void)
void sptlrpc_gc_fini (void)
void sptlrpc_conf_choose_flavor (enum lustre_sec_part from, enum lustre_sec_part to, struct obd_uuid *target, lnet_nid_t nid, struct sptlrpc_flavor *sf)
int sptlrpc_conf_init (void)
void sptlrpc_conf_fini (void)
int lustre_rename (struct dentry *dir, struct vfsmount *mnt, char *old_name, char *new_name)
int sptlrpc_init (void)
void sptlrpc_fini (void)
static bool ptlrpc_recoverable_error (int rc)
static int tgt_mod_init (void)
static void tgt_mod_exit (void)
static int nodemap_mod_init (void)
static void nodemap_mod_exit (void)
static void ptlrpc_reqset_put (struct ptlrpc_request_set *set)
static void ptlrpc_req_comm_init (struct ptlrpc_request *req)
initialise ptlrpc common fields
static void ptlrpc_cli_req_init (struct ptlrpc_request *req)
initialise client side ptlrpc request
static void ptlrpc_srv_req_init (struct ptlrpc_request *req)
initialise server side ptlrpc request
static bool ptlrpc_req_is_connect (struct ptlrpc_request *req)
static bool ptlrpc_req_is_disconnect (struct ptlrpc_request *req)
Define Documentation
#define LPROCFS_NRS_QUANTUM_MAX 65535
the maximum size of nrs_crrn_client::cc_quantum and nrs_orr_data::od_quantum.
Definition at line 249 of file ptlrpc_internal.h.
#define LPROCFS_NRS_WR_QUANTUM_MAX_CMD
Value:
sizeof(NRS_LPROCFS_QUANTUM_NAME_REG __stringify(LPROCFS_NRS_QUANTUM_MAX) " "  \
        NRS_LPROCFS_QUANTUM_NAME_HP __stringify(LPROCFS_NRS_QUANTUM_MAX))
Max valid command string is the size of the labels, plus "65535" twice, plus a separating space character.
Definition at line 255 of file ptlrpc_internal.h.
#define NRS_LPROCFS_QUANTUM_NAME_HP "hp_quantum:"
Definition at line 244 of file ptlrpc_internal.h.
#define NRS_LPROCFS_QUANTUM_NAME_REG "reg_quantum:"
Definition at line 243 of file ptlrpc_internal.h.
#define ptlrpc_lprocfs_do_request_stat (params...) do{}while(0)
Definition at line 122 of file ptlrpc_internal.h.
#define ptlrpc_lprocfs_register_service (params...) do{}while(0)
Definition at line 119 of file ptlrpc_internal.h.
Referenced by ptlrpc_register_service().
#define ptlrpc_lprocfs_rpc_sent (params...) do{}while(0)
Definition at line 121 of file ptlrpc_internal.h.
Referenced by after_reply().
#define ptlrpc_lprocfs_unregister_service (params...) do{}while(0)
Definition at line 120 of file ptlrpc_internal.h.
Referenced by ptlrpc_unregister_service().
Function Documentation
void lustre_assert_wire_constants (void)
Definition at line 64 of file wiretest.c.
Referenced by main(), and ptlrpc_init().
struct ptlrpc_reply_state* lustre_get_emerg_rs (struct ptlrpc_service_part * svcpt) [read]
Definition at line 283 of file pack_generic.c.
References cfs_time_seconds(), l_wait_event, list_del(), list_empty(), list_entry, LWI_TIMEOUT, list_head::next, ptlrpc_reply_state::rs_list, ptlrpc_reply_state::rs_prealloc, ptlrpc_reply_state::rs_size, ptlrpc_reply_state::rs_svcpt, ptlrpc_service_part::scp_rep_idle, and ptlrpc_service_part::scp_rep_waitq.
Referenced by sptlrpc_svc_alloc_rs().
void lustre_put_emerg_rs (struct ptlrpc_reply_state * rs)
Definition at line 319 of file pack_generic.c.
References list_add(), ptlrpc_reply_state::rs_list, ptlrpc_reply_state::rs_svcpt, ptlrpc_service_part::scp_rep_idle, and ptlrpc_service_part::scp_rep_waitq.
Referenced by sptlrpc_svc_alloc_rs(), and sptlrpc_svc_free_rs().
int lustre_rename (struct dentry * dir, struct vfsmount * mnt, char * old_name, char * new_name)
Definition at line 102 of file sec_ctx.c.
References ASSERT_KERNEL_CTXT, CDEBUG, D_INODE, ENTRY, GOTO, ll_lookup_one_len(), ll_vfs_rename, and RETURN.
Referenced by sptlrpc_target_local_copy_conf().
int lustre_unpack_rep_ptlrpc_body (struct ptlrpc_request * req, int offset)
Definition at line 661 of file pack_generic.c.
References CERROR, LUSTRE_MSG_MAGIC_V2, lustre_unpack_ptlrpc_body_v2(), and ptlrpc_request::rq_repmsg.
Referenced by unpack_reply().
int lustre_unpack_req_ptlrpc_body (struct ptlrpc_request * req, int offset)
Definition at line 649 of file pack_generic.c.
References CERROR, LUSTRE_MSG_MAGIC_V2, lustre_unpack_ptlrpc_body_v2(), and ptlrpc_request::rq_reqmsg.
Referenced by ptlrpc_server_handle_req_in().
static void nodemap_mod_exit (void) [inline, static]
Definition at line 346 of file ptlrpc_internal.h.
static int nodemap_mod_init (void) [inline, static]
Definition at line 341 of file ptlrpc_internal.h.
static struct cfs_cpt_table* nrs_pol2cptab (struct ptlrpc_nrs_policy * policy) [static, read]
Definition at line 223 of file ptlrpc_internal.h.
References nrs_pol2svc(), and ptlrpc_service::srv_cptable.
Referenced by nrs_fifo_start().
static int nrs_pol2cptid (const struct ptlrpc_nrs_policy * policy) [inline, static]
Definition at line 205 of file ptlrpc_internal.h.
References ptlrpc_nrs::nrs_svcpt, ptlrpc_nrs_policy::pol_nrs, and ptlrpc_service_part::scp_cpt.
Referenced by nrs_fifo_start().
static struct ptlrpc_service* nrs_pol2svc (struct ptlrpc_nrs_policy * policy) [static, read]
Definition at line 211 of file ptlrpc_internal.h.
References ptlrpc_nrs::nrs_svcpt, and ptlrpc_nrs_policy::pol_nrs.
Referenced by nrs_pol2cptab().
static struct ptlrpc_service_part* nrs_pol2svcpt (struct ptlrpc_nrs_policy * policy) [static, read]
Definition at line 217 of file ptlrpc_internal.h.
References ptlrpc_nrs::nrs_svcpt, and ptlrpc_nrs_policy::pol_nrs.
static struct ptlrpc_nrs_policy* nrs_request_policy (struct ptlrpc_nrs_request * nrq) [static, read]
Definition at line 238 of file ptlrpc_internal.h.
References nrs_request_resource(), and ptlrpc_nrs_resource::res_policy.
Referenced by nrs_request_get(), nrs_request_stop(), ptlrpc_nrs_req_add_nolock(), and ptlrpc_nrs_req_del_nolock().
static struct ptlrpc_nrs_resource* nrs_request_resource (struct ptlrpc_nrs_request * nrq) [static, read]
Definition at line 229 of file ptlrpc_internal.h.
References LASSERT, ptlrpc_nrs_request::nr_finalized, ptlrpc_nrs_request::nr_initialized, ptlrpc_nrs_request::nr_res_idx, and ptlrpc_nrs_request::nr_res_ptrs.
Referenced by nrs_fifo_req_add(), and nrs_request_policy().
static bool nrs_svc_has_hp (const struct ptlrpc_service * svc) [inline, static]
If the first service partition has an HP NRS head, all service partitions will.
Definition at line 189 of file ptlrpc_internal.h.
References nrs_svcpt_has_hp(), and ptlrpc_service::srv_parts.
Referenced by nrs_policy_unregister_locked(), and ptlrpc_nrs_policy_register().
static struct ptlrpc_nrs* nrs_svcpt2nrs (struct ptlrpc_service_part * svcpt, bool hp) [static, read]
Definition at line 199 of file ptlrpc_internal.h.
References ergo, LASSERT, nrs_svcpt_has_hp(), ptlrpc_service_part::scp_nrs_hp, and ptlrpc_service_part::scp_nrs_reg.
Referenced by nrs_policy_unregister_locked(), nrs_svcpt_setup_locked(), ptlrpc_nrs_policy_control(), ptlrpc_nrs_policy_register(), ptlrpc_nrs_req_get_nolock0(), ptlrpc_nrs_req_hp_move(), ptlrpc_nrs_req_initialize(), ptlrpc_nrs_req_pending_nolock(), and ptlrpc_nrs_req_throttling_nolock().
static bool nrs_svcpt_has_hp (const struct ptlrpc_service_part * svcpt) [inline, static]
Definition at line 184 of file ptlrpc_internal.h.
References ptlrpc_service_part::scp_nrs_hp.
Referenced by nrs_svc_has_hp(), nrs_svcpt2nrs(), nrs_svcpt_cleanup_locked(), ptlrpc_server_allow_high(), and ptlrpc_server_allow_normal().
int ping_evictor_wake (struct obd_export * exp)
Definition at line 583 of file pinger.c.
References class_exp2obd(), class_incref(), list_add(), list_empty(), obd_device::obd_evict_list, pet_list, PET_READY, pet_state, and pet_waitq.
Referenced by ptlrpc_update_export_timer().
void ptlrpc_add_unreplied (struct ptlrpc_request * req)
Definition at line 658 of file client.c.
References obd_import::imp_lock, obd_import::imp_unreplied_list, LASSERT, list_add(), list_empty(), list_entry, list_for_each_prev, ptlrpc_request::rq_import, rq_unreplied_list, and ptlrpc_request::rq_xid.
Referenced by ptlrpc_assign_next_xid_nolock(), ptlrpc_prepare_replay(), and ptlrpc_replay_next().
void ptlrpc_assign_next_xid_nolock (struct ptlrpc_request * req)
Definition at line 681 of file client.c.
References ptlrpc_add_unreplied(), ptlrpc_next_xid(), and ptlrpc_request::rq_xid.
Referenced by ptl_send_rpc(), and ptlrpc_assign_next_xid().
void ptlrpc_at_adj_net_latency (struct ptlrpc_request * req, unsigned int service_time)
Definition at line 357 of file client.c.
References at_get(), at_measured(), ptlrpc_connection::c_remote_uuid, CDEBUG, CFS_DURATION_T, cfs_time_current_sec(), cfs_time_sub(), D_ADAPTTO, D_WARNING, imp_at::iat_net_latency, obd_import::imp_at, obd_import::imp_connection, obd_import::imp_obd, LASSERT, lustre_msg_get_flags(), MSG_RESENT, now(), obd_device::obd_name, obd_uuid2str(), ptlrpc_request::rq_import, ptlrpc_request::rq_reqmsg, and ptlrpc_request::rq_sent.
Referenced by after_reply(), ptlrpc_at_recv_early_reply(), and ptlrpc_connect_interpret().
static void ptlrpc_cli_req_init (struct ptlrpc_request * req) [inline, static]
initialise client side ptlrpc request
Definition at line 368 of file ptlrpc_internal.h.
References ptlrpc_cli_req::cr_ctx_chain, ptlrpc_cli_req::cr_reply_waitq, ptlrpc_cli_req::cr_set_chain, ptlrpc_cli_req::cr_set_waitq, ptlrpc_cli_req::cr_unreplied_list, INIT_LIST_HEAD, ptlrpc_req_comm_init(), ptlrpc_request::rq_cli, ptlrpc_request::rq_receiving_reply, ptlrpc_request::rq_reply_unlinked, and ptlrpc_request::rq_req_unlinked.
Referenced by __ptlrpc_request_alloc(), ptlrpcd_alloc_work(), sptlrpc_cli_unwrap_early_reply(), and sptlrpc_import_check_ctx().
void ptlrpc_exit_portals (void)
Definition at line 632 of file events.c.
References ptlrpc_ni_fini(), and ptlrpcd_decref().
Referenced by ptlrpc_exit(), and ptlrpc_init().
int ptlrpc_expire_one_request (struct ptlrpc_request * req, int async_unlink)
Time out request req.
is async_unlink is set, that means do not wait until LNet actually confirms network buffer unlinking. Return 1 if we should give up further retrying attempts or 0 otherwise.
Definition at line 2050 of file client.c.
References ptlrpc_connection::c_peer, CFS_DURATION_T, cfs_time_aftereq(), cfs_time_before(), D_HA, D_RPCTRACE, D_WARNING, DEBUG_REQ, ENTRY, obd_import::imp_connection, obd_import::imp_dlm_fake, obd_import::imp_obd, obd_import::imp_state, obd_import::imp_timeouts, libcfs_debug_dumplog(), LNetDebugPeer(), LUSTRE_IMP_FULL, lustre_msg_get_conn_cnt(), obd_debug_peer_on_timeout, obd_dump_on_timeout, obd_device::obd_no_recov, ptlrpc_fail_import(), ptlrpc_import_state_name(), ptlrpc_no_resend(), ptlrpc_unregister_bulk(), ptlrpc_unregister_reply(), RETURN, ptlrpc_request::rq_ctx_fini, ptlrpc_request::rq_ctx_init, ptlrpc_request::rq_deadline, ptlrpc_request::rq_err, ptlrpc_request::rq_import, ptlrpc_request::rq_lock, ptlrpc_request::rq_net_err, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_sent, ptlrpc_request::rq_status, and ptlrpc_request::rq_timedout.
Referenced by ctx_refresh_timeout(), ptlrpc_check_set(), and ptlrpc_expired_set().
int ptlrpc_expired_set (void * data)
Time out all uncompleted requests in request set pointed by data Callback used when waiting on sets with l_wait_event.
Always returns 1.
Definition at line 2121 of file client.c.
References cfs_time_current_sec(), ENTRY, LASSERT, list_entry, list_for_each, now(), ptlrpc_expire_one_request(), RETURN, ptlrpc_request::rq_deadline, ptlrpc_request::rq_phase, RQ_PHASE_BULK, RQ_PHASE_RPC, ptlrpc_request::rq_resend, rq_set_chain, ptlrpc_request::rq_timedout, ptlrpc_request::rq_wait_ctx, and ptlrpc_request::rq_waiting.
Referenced by ptlrpc_set_wait(), and ptlrpcd().
void ptlrpc_fill_bulk_md (lnet_md_t * md, struct ptlrpc_bulk_desc * desc, int mdcnt)
Definition at line 48 of file pers.c.
References BD_GET_ENC_KIOV, BD_GET_ENC_KVEC, BD_GET_KIOV, BD_GET_KVEC, ptlrpc_bulk_desc::bd_iov_count, ptlrpc_bulk_desc::bd_type, CLASSERT, GET_ENC_KIOV, GET_ENC_KVEC, LASSERT, lnet_md_t::length, LNET_MAX_IOV, LNET_MD_IOVEC, LNET_MD_KIOV, LNET_MD_PHYS, max, min_t, lnet_md_t::options, ptlrpc_is_bulk_desc_kiov(), ptlrpc_is_bulk_desc_kvec(), PTLRPC_MAX_BRW_PAGES, and lnet_md_t::start.
Referenced by ptlrpc_register_bulk().
void ptlrpc_handle_failed_import (struct obd_import * imp)
int ptlrpc_import_in_recovery (struct obd_import * imp)
Definition at line 393 of file recover.c.
References obd_import::imp_lock, obd_import::imp_obd, obd_import::imp_state, LUSTRE_IMP_CLOSED, LUSTRE_IMP_DISCON, LUSTRE_IMP_FULL, and obd_device::obd_no_recov.
Referenced by ptlrpc_disconnect_import(), ptlrpc_reconnect_import(), and ptlrpc_recover_import().
int ptlrpc_init_portals (void)
Definition at line 615 of file events.c.
References CERROR, ptlrpc_ni_fini(), ptlrpc_ni_init(), and ptlrpcd_addref().
Referenced by ptlrpc_init().
void ptlrpc_init_xid (void)
Definition at line 3147 of file client.c.
References __u64, cfs_get_random_bytes(), cfs_time_current_sec(), CLASSERT, now(), PTLRPC_BULK_OPS_COUNT, PTLRPC_BULK_OPS_MASK, and YEAR_2004.
Referenced by ptlrpc_init().
void ptlrpc_initiate_recovery (struct obd_import * imp)
Start recovery on disconnected import.
This is done by just attempting a connect
Definition at line 58 of file recover.c.
References CDEBUG, D_HA, ENTRY, EXIT, obd_import::imp_obd, obd2cli_tgt, and ptlrpc_connect_import().
Referenced by ptlrpc_pinger_process_import().
__u64 ptlrpc_known_replied_xid (struct obd_import * imp)
Definition at line 1272 of file client.c.
References obd_import::imp_known_replied_xid, obd_import::imp_lock, obd_import::imp_unreplied_list, LASSERTF, list_empty(), list_entry, LPU64, list_head::next, rq_unreplied_list, and ptlrpc_request::rq_xid.
Referenced by ptl_send_rpc(), ptlrpc_prepare_replay(), and ptlrpc_send_new_req().
struct ptlrpc_bulk_desc* ptlrpc_new_bulk (unsigned nfrags, unsigned max_brw, enum ptlrpc_bulk_op_type type, unsigned portal, const struct ptlrpc_bulk_frag_ops * ops) [read]
Allocate and initialize new bulk descriptor on the sender.
Returns pointer to the descriptor or NULL on error.
Definition at line 117 of file client.c.
References ptlrpc_bulk_frag_ops::add_iov_frag, ptlrpc_bulk_frag_ops::add_kiov_frag, ptlrpc_bulk_desc::bd_frag_ops, ptlrpc_bulk_desc::bd_iov_count, ptlrpc_bulk_desc::bd_lock, ptlrpc_bulk_desc::bd_max_iov, ptlrpc_bulk_desc::bd_md_count, ptlrpc_bulk_desc::bd_md_max_brw, ptlrpc_bulk_desc::bd_mds, ptlrpc_bulk_desc::bd_portal, ptlrpc_bulk_desc::bd_type, ptlrpc_bulk_desc::bd_waitq, GET_KIOV, GET_KVEC, LASSERT, LNetInvalidateHandle(), OBD_ALLOC_LARGE, OBD_ALLOC_PTR, OBD_FREE_PTR, PTLRPC_BULK_BUF_KIOV, PTLRPC_BULK_OPS_COUNT, ptlrpc_is_bulk_desc_kiov(), and ptlrpc_is_bulk_desc_kvec().
Referenced by ptlrpc_prep_bulk_imp().
void ptlrpc_nrs_fini (void)
Removes all policy descriptors from nrs_core::nrs_policies, and frees the policy descriptors.
Since all PTLRPC services are stopped at this point, there are no more instances of any policies, because each service will have stopped its policy instances in ptlrpc_service_nrs_cleanup(), so we just need to free the descriptors here.
Definition at line 1836 of file nrs.c.
References list_del_init(), list_for_each_entry_safe, OBD_FREE_PTR, and ptlrpc_nrs_pol_desc::pd_list.
Referenced by ptlrpc_exit(), ptlrpc_init(), and ptlrpc_nrs_init().
int ptlrpc_nrs_init (void)
Adds all policies that ship with the ptlrpc module, to NRS core's list of policies nrs_core.nrs_policies.
Return values:
0 all policies have been registered successfully
-ve error
Since no PTLRPC services have been started at this point, all we need to do for cleanup is to free the descriptors.
Definition at line 1787 of file nrs.c.
References ENTRY, GOTO, INIT_LIST_HEAD, nrs_conf_fifo, ptlrpc_nrs_fini(), ptlrpc_nrs_policy_register(), and RETURN.
Referenced by ptlrpc_init().
int ptlrpc_nrs_policy_control (const struct ptlrpc_service * svc, enum ptlrpc_nrs_queue_type queue, char * name, enum ptlrpc_nrs_ctl opc, bool single, void * arg)
Carries out a control operation opc on the policy identified by the human-readable name, on either all partitions, or only on the first partition of service svc.
Parameters:
[in] svc the service the policy belongs to.
[in] queue whether to carry out the command on the policy which belongs to the regular, high-priority, or both NRS heads of service partitions of svc.
[in] name the policy to act upon, by human-readable name
[in] opc the opcode of the operation to carry out
[in] single when set, the operation will only be carried out on the NRS heads of the first service partition of svc. This is useful for some policies which e.g. share identical values on the same parameters of different service partitions; when reading these parameters via lprocfs, these policies may just want to obtain and print out the values from the first service partition. Storing these values centrally elsewhere then could be another solution for this.
[in,out] arg can be used as a generic in/out buffer between control operations and the user environment.
Return values:
-ve error condition
0 operation was carried out successfully
XXX: We could optionally check for nrs_svc_has_hp(svc) here, and return an error if it is false. Right now we rely on the policies' lprocfs handlers that call the present function to make this check; if they fail to do so, they might hit the assertion inside nrs_svcpt2nrs() below.
Definition at line 1738 of file nrs.c.
References ENTRY, GOTO, LASSERT, nrs_policy_ctl(), nrs_svcpt2nrs(), PTLRPC_NRS_CTL_INVALID, PTLRPC_NRS_QUEUE_BOTH, PTLRPC_NRS_QUEUE_HP, PTLRPC_NRS_QUEUE_REG, ptlrpc_service_for_each_part, and RETURN.
void ptlrpc_nrs_req_add (struct ptlrpc_service_part * svcpt, struct ptlrpc_request * req, bool hp)
Enqueues request req on either the regular or high-priority NRS head of service partition svcpt.
Parameters:
[in] svcpt the service partition
[in] req the request to be enqueued
[in] hp whether to enqueue the request on the regular or high-priority NRS head.
Definition at line 1524 of file nrs.c.
References ptlrpc_nrs_hpreq_add_nolock(), and ptlrpc_nrs_req_add_nolock().
Referenced by ptlrpc_server_request_add().
void ptlrpc_nrs_req_del_nolock (struct ptlrpc_request * req)
Dequeues request req from the policy it has been enqueued on.
Parameters:
[in] req the request
Definition at line 1619 of file nrs.c.
References nrs_request_policy(), nrs_request_removed(), ptlrpc_nrs_pol_ops::op_req_dequeue, ptlrpc_nrs_pol_desc::pd_ops, and ptlrpc_nrs_policy::pol_desc.
Referenced by ptlrpc_nrs_req_hp_move().
void ptlrpc_nrs_req_finalize (struct ptlrpc_request * req)
Releases resources for a request; is called after the request has been handled.
Parameters:
[in] req the request
See also:
ptlrpc_server_finish_request()
Definition at line 1499 of file nrs.c.
References nrs_resource_put_safe().
Referenced by ptlrpc_server_finish_active_request(), and ptlrpc_server_request_add().
static struct ptlrpc_request* ptlrpc_nrs_req_get_nolock (struct ptlrpc_service_part * svcpt, bool hp, bool force) [static, read]
Definition at line 160 of file ptlrpc_internal.h.
References ptlrpc_nrs_req_get_nolock0().
Referenced by ptlrpc_server_request_get().
struct ptlrpc_request* ptlrpc_nrs_req_get_nolock0 (struct ptlrpc_service_part * svcpt, bool hp, bool peek, bool force) [read]
Obtains a request for handling from an NRS head of service partition svcpt.
Parameters:
[in] svcpt the service partition
[in] hp whether to obtain a request from the regular or high-priority NRS head.
[in] peek when set, signifies that we just want to examine the request, and not handle it, so the request is not removed from the policy.
[in] force when set, it will force a policy to return a request if it has one pending
Return values:
the request to be handled
NULL the head has no requests to serve
Always try to drain requests from all NRS polices even if they are inactive, because the user can change policy status at runtime.
Definition at line 1583 of file nrs.c.
References likely, list_for_each_entry, ptlrpc_nrs_request::nr_started, ptlrpc_nrs::nrs_policy_queued, ptlrpc_nrs::nrs_req_started, nrs_request_get(), nrs_request_removed(), nrs_svcpt2nrs(), ptlrpc_nrs_policy::pol_nrs, ptlrpc_nrs_policy::pol_req_started, and rq_nrq.
Referenced by ptlrpc_nrs_req_get_nolock(), and ptlrpc_nrs_req_peek_nolock().
void ptlrpc_nrs_req_initialize (struct ptlrpc_service_part * svcpt, struct ptlrpc_request * req, bool hp)
Obtains NRS head resources for request req.
These could be either on the regular or HP NRS head of svcpt; resources taken on the regular head can later be swapped for HP head resources by ldlm_lock_reorder_req().
Parameters:
[in] svcpt the service partition
[in] req the request
[in] hp which NRS head of svcpt to use
It is fine to access nr_initialized without locking as there is no contention at this early stage.
Definition at line 1475 of file nrs.c.
References nrs_resource_get_safe(), and nrs_svcpt2nrs().
Referenced by ptlrpc_server_request_add().
static struct ptlrpc_request* ptlrpc_nrs_req_peek_nolock (struct ptlrpc_service_part * svcpt, bool hp) [static, read]
Definition at line 167 of file ptlrpc_internal.h.
References ptlrpc_nrs_req_get_nolock0().
Referenced by ptlrpc_svcpt_health_check().
bool ptlrpc_nrs_req_pending_nolock (struct ptlrpc_service_part * svcpt, bool hp)
Returns whether there are any requests currently enqueued on any of the policies of service partition's svcpt NRS head specified by hp.
Should be called while holding ptlrpc_service_part::scp_req_lock to get a reliable result.
Parameters:
[in] svcpt the service partition to enquire.
[in] hp whether the regular or high-priority NRS head is to be enquired.
Return values:
false the indicated NRS head has no enqueued requests.
true the indicated NRS head has some enqueued requests.
Definition at line 1643 of file nrs.c.
References ptlrpc_nrs::nrs_req_queued, and nrs_svcpt2nrs().
Referenced by ptlrpc_server_allow_high(), ptlrpc_server_high_pending(), and ptlrpc_server_normal_pending().
void ptlrpc_nrs_req_stop_nolock (struct ptlrpc_request * req)
Definition at line 1509 of file nrs.c.
References nrs_request_stop().
Referenced by ptlrpc_server_finish_active_request().
bool ptlrpc_nrs_req_throttling_nolock (struct ptlrpc_service_part * svcpt, bool hp)
Returns whether NRS policy is throttling reqeust.
Parameters:
[in] svcpt the service partition to enquire.
[in] hp whether the regular or high-priority NRS head is to be enquired.
Return values:
false the indicated NRS head has no enqueued requests.
true the indicated NRS head has some enqueued requests.
Definition at line 1660 of file nrs.c.
References nrs_svcpt2nrs(), and ptlrpc_nrs::nrs_throttling.
Referenced by ptlrpc_server_allow_high(), and ptlrpc_server_allow_normal().
void ptlrpc_ping_import_soon (struct obd_import * imp)
Definition at line 132 of file pinger.c.
References cfs_time_current(), and obd_import::imp_next_ping.
void ptlrpc_pinger_commit_expected (struct obd_import * imp)
Definition at line 390 of file pinger.c.
References obd_import::imp_connect_data, obd_import::imp_force_next_verify, obd_import::imp_lock, obd_import::imp_state, LUSTRE_IMP_FULL, OCD_HAS_FLAG, and ptlrpc_update_next_ping().
Referenced by after_reply().
void ptlrpc_pinger_sending_on_import (struct obd_import * imp)
Definition at line 385 of file pinger.c.
References ptlrpc_update_next_ping().
Referenced by ptl_send_rpc().
void ptlrpc_pinger_wake_up (void)
Definition at line 565 of file pinger.c.
References pinger_thread, SVC_EVENT, ptlrpc_thread::t_ctl_waitq, and thread_add_flags().
Referenced by ptlrpc_maybe_ping_import_soon(), ptlrpc_pinger_add_import(), and ptlrpc_pinger_force().
static bool ptlrpc_recoverable_error (int rc) [inline, static]
Definition at line 320 of file ptlrpc_internal.h.
Referenced by after_reply().
int ptlrpc_replay_next (struct obd_import * imp, int * inflight)
Identify what request from replay list needs to be replayed next (based on what we have already replayed) and send it to server.
Definition at line 72 of file recover.c.
References __u64, CDEBUG, CERROR, D_HA, ENTRY, obd_import::imp_committed_list, obd_import::imp_last_replay_transno, obd_import::imp_last_transno_checked, obd_import::imp_lock, obd_import::imp_obd, obd_import::imp_peer_committed_transno, obd_import::imp_replay_cursor, obd_import::imp_replay_list, obd_import::imp_resend_replay, LASSERT, list_empty(), list_entry, list_for_each_safe, LPU64, lustre_msg_add_flags(), MSG_RESENT, list_head::next, obd2cli_tgt, list_head::prev, ptlrpc_add_unreplied(), ptlrpc_free_committed(), ptlrpc_replay_req(), RETURN, ptlrpc_request::rq_replay_list, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_transno, and ptlrpc_request::rq_xid.
Referenced by ptlrpc_import_recovery_state_machine().
static void ptlrpc_req_comm_init (struct ptlrpc_request * req) [inline, static]
initialise ptlrpc common fields
Definition at line 359 of file ptlrpc_internal.h.
References INIT_LIST_HEAD, ptlrpc_request::rq_list, ptlrpc_request::rq_lock, ptlrpc_request::rq_refcount, and ptlrpc_request::rq_replay_list.
Referenced by ptlrpc_cli_req_init(), and ptlrpc_srv_req_init().
static bool ptlrpc_req_is_connect (struct ptlrpc_request * req) [inline, static]
Definition at line 396 of file ptlrpc_internal.h.
References lustre_msg_get_opc(), MDS_CONNECT, MGS_CONNECT, OST_CONNECT, and ptlrpc_request::rq_reqmsg.
Referenced by ptlrpc_send_new_req().
static bool ptlrpc_req_is_disconnect (struct ptlrpc_request * req) [inline, static]
Definition at line 406 of file ptlrpc_internal.h.
References lustre_msg_get_opc(), MDS_DISCONNECT, MGS_DISCONNECT, OST_DISCONNECT, and ptlrpc_request::rq_reqmsg.
Referenced by ptlrpc_send_new_req().
static void ptlrpc_reqset_put (struct ptlrpc_request_set * set) [inline, static]
Definition at line 352 of file ptlrpc_internal.h.
References OBD_FREE_PTR.
Referenced by ptlrpc_set_destroy(), and ptlrpcd_check().
struct ptlrpc_request* ptlrpc_request_cache_alloc (gfp_t flags) [read]
Definition at line 492 of file client.c.
References OBD_SLAB_ALLOC_PTR_GFP, and request_cache.
Referenced by __ptlrpc_request_alloc(), ptlrpc_add_rqs_to_pool(), ptlrpc_at_send_early_reply(), ptlrpcd_alloc_work(), request_in_callback(), sptlrpc_cli_unwrap_early_reply(), and sptlrpc_import_check_ctx().
void ptlrpc_request_cache_fini (void)
Definition at line 487 of file client.c.
References request_cache.
Referenced by ptlrpc_exit(), and ptlrpc_init().
void ptlrpc_request_cache_free (struct ptlrpc_request * req)
Definition at line 500 of file client.c.
References OBD_SLAB_FREE_PTR, and request_cache.
Referenced by __ptlrpc_free_req(), ptlrpc_add_rqs_to_pool(), ptlrpc_at_send_early_reply(), ptlrpc_free_rq_pool(), ptlrpc_request_free(), ptlrpc_server_free_request(), sptlrpc_cli_finish_early_reply(), sptlrpc_cli_unwrap_early_reply(), and sptlrpc_import_check_ctx().
int ptlrpc_request_cache_init (void)
Definition at line 479 of file client.c.
References request_cache.
Referenced by ptlrpc_init().
void ptlrpc_request_handle_notconn (struct ptlrpc_request *)
Definition at line 249 of file recover.c.
References ptlrpc_connection::c_remote_uuid, CDEBUG, D_HA, ENTRY, EXIT, obd_import::imp_connection, obd_import::imp_deactive, obd_import::imp_obd, obd_import::imp_replayable, lustre_msg_get_conn_cnt(), obd2cli_tgt, obd_device::obd_name, ptlrpc_connect_import(), ptlrpc_deactivate_import(), ptlrpc_set_import_discon(), ptlrpc_request::rq_import, ptlrpc_request::rq_lock, ptlrpc_request::rq_no_resend, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_resend, and obd_uuid::uuid.
Referenced by after_reply().
void ptlrpc_resend_req (struct ptlrpc_request * req)
Schedule previously sent request for resend.
For bulk requests we assign new xid (to avoid problems with lost replies and therefore several transfers landing into same buffer from different sending attempts).
Definition at line 2717 of file client.c.
References D_HA, DEBUG_REQ, lustre_msg_set_handle(), ptlrpc_client_replied(), ptlrpc_request::rq_lock, and ptlrpc_request::rq_reqmsg.
Referenced by ptlrpc_resend().
void ptlrpc_service_nrs_cleanup (struct ptlrpc_service * svc)
Unregisters all policies on all service partitions of service svc.
Parameters:
[in] svc the PTLRPC service to unregister
Clean up NRS heads on all service partitions
Clean up lprocfs interfaces for all supported policies for the service.
Definition at line 1435 of file nrs.c.
References list_for_each_entry, nrs_policy_compatible(), nrs_svcpt_cleanup_locked(), ptlrpc_nrs_pol_ops::op_lprocfs_fini, ptlrpc_nrs_pol_desc::pd_list, ptlrpc_nrs_pol_desc::pd_ops, and ptlrpc_service_for_each_part.
Referenced by ptlrpc_unregister_service().
int ptlrpc_service_nrs_setup (struct ptlrpc_service * svc)
Setup NRS heads on all service partitions of service svc, and register all compatible policies on those NRS heads.
To be called from withing ptl
Parameters:
[in] svc the service to setup
Return values:
-ve error, the calling logic should eventually call ptlrpc_service_nrs_cleanup() to undo any work performed by this function.
See also:
ptlrpc_register_service()
ptlrpc_service_nrs_cleanup()
Initialize NRS heads on all service CPTs.
Set up lprocfs interfaces for all supported policies for the service.
Definition at line 1390 of file nrs.c.
References GOTO, list_for_each_entry, nrs_policy_compatible(), nrs_svcpt_setup_locked(), ptlrpc_nrs_pol_ops::op_lprocfs_init, ptlrpc_nrs_pol_desc::pd_list, ptlrpc_nrs_pol_desc::pd_ops, ptlrpc_service_for_each_part, and RETURN.
Referenced by ptlrpc_register_service().
void ptlrpc_set_add_new_req (struct ptlrpcd_ctl * pc, struct ptlrpc_request * req)
Add a request to a request with dedicated server thread and wake the thread to make any necessary processing.
Currently only used for ptlrpcd.
Definition at line 1079 of file client.c.
References cfs_time_current(), LASSERT, LIOD_STOP, list_add_tail(), ptlrpcd_ctl::pc_flags, ptlrpcd_ctl::pc_npartners, ptlrpcd_ctl::pc_partners, ptlrpcd_ctl::pc_set, and ptlrpc_request_set::set_waitq.
Referenced by ptlrpcd_add_req().
void ptlrpc_set_bulk_mbits (struct ptlrpc_request * req)
If request has a new allocated XID (new request or EINPROGRESS resend), use this XID as matchbits of bulk, otherwise allocate a new matchbits for request to ensure previous bulk fails and avoid problems with lost replies and therefore several transfers landing into the same buffer from different sending attempts.
Definition at line 3196 of file client.c.
References __u64, ptlrpc_bulk_desc::bd_import, ptlrpc_bulk_desc::bd_iov_count, CDEBUG, D_HA, obd_import::imp_connect_data, LASSERT, LNET_MAX_IOV, LPU64, OBD_CONNECT_BULK_MBITS, obd_connect_data::ocd_connect_flags, ptlrpc_next_xid(), ptlrpc_request::rq_mbits, ptlrpc_request::rq_resend, and ptlrpc_request::rq_xid.
Referenced by ptl_send_rpc().
int ptlrpc_set_import_discon (struct obd_import * imp, __u32 conn_cnt)
Returns true if import was FULL, false if import was already not connected.
- import to be disconnected - connection count (epoch) of the request that timed out and caused the disconnection. In some cases, multiple inflight requests can fail to a single target (e.g. OST bulk requests) and if one has already caused a reconnection (increasing the import->conn_cnt) the older failure should not also cause a reconnection. If zero it forces a reconnect.
Definition at line 163 of file import.c.
References ptlrpc_connection::c_peer, CDEBUG, ptlrpc_client::cli_name, D_HA, deuuidify(), obd_import::imp_client, obd_import::imp_conn_cnt, obd_import::imp_connection, IMP_EVENT_DISCON, obd_import::imp_lock, obd_import::imp_obd, obd_import::imp_replayable, obd_import::imp_state, IMPORT_SET_STATE_NOLOCK, LCONSOLE_ERROR_MSG, LCONSOLE_WARN, libcfs_debug_dumplog(), libcfs_nid2str(), LUSTRE_IMP_DISCON, LUSTRE_IMP_FULL, lnet_process_id_t::nid, obd2cli_tgt, obd_dump_on_timeout, obd_device::obd_name, and ptlrpc_import_state_name().
Referenced by ptlrpc_fail_import(), ptlrpc_reconnect_import(), ptlrpc_recover_import(), and ptlrpc_request_handle_notconn().
int ptlrpc_set_next_timeout (struct ptlrpc_request_set *)
Get the smallest timeout in the set; this does NOT set a timeout.
Definition at line 2207 of file client.c.
References cfs_time_current_sec(), ENTRY, list_entry, list_for_each, now(), RETURN, ptlrpc_request::rq_phase, RQ_PHASE_BULK, RQ_PHASE_NEW, RQ_PHASE_RPC, ptlrpc_request::rq_resend, ptlrpc_request::rq_sent, rq_set_chain, ptlrpc_request::rq_timedout, ptlrpc_request::rq_timeout, ptlrpc_request::rq_wait_ctx, ptlrpc_request::rq_waiting, and timeout.
Referenced by ptlrpc_set_wait(), and ptlrpcd().
static void ptlrpc_srv_req_init (struct ptlrpc_request * req) [inline, static]
initialise server side ptlrpc request
Definition at line 385 of file ptlrpc_internal.h.
References INIT_LIST_HEAD, ptlrpc_req_comm_init(), ptlrpc_request::rq_srv, ptlrpc_request::rq_srv_req, ptlrpc_srv_req::sr_exp_list, ptlrpc_srv_req::sr_hist_list, and ptlrpc_srv_req::sr_timed_list.
Referenced by request_in_callback().
int ptlrpc_start_pinger (void)
Definition at line 322 of file pinger.c.
References CERROR, CWARN, ENTRY, l_wait_event, pinger_thread, ptlrpc_pinger_main(), RETURN, suppress_pings, ptlrpc_thread::t_ctl_waitq, ptlrpc_thread::t_name, thread_is_init(), thread_is_running(), and thread_is_stopped().
Referenced by ptlrpc_init().
int ptlrpc_start_thread (struct ptlrpc_service_part * svcpt, int wait)
Definition at line 2782 of file service.c.
References CDEBUG, CERROR, D_INFO, D_RPCTRACE, ENTRY, l_wait_event, LASSERT, list_add(), list_del(), OBD_CPT_ALLOC_PTR, OBD_FAIL_CHECK, OBD_FAIL_TGT_TOOMANY_THREADS, OBD_FREE_PTR, ptlrpc_main(), PTLRPC_THR_NAME_LEN, ptlrpc_threads_increasable(), RETURN, ptlrpc_service_part::scp_cpt, ptlrpc_service_part::scp_nthrs_running, ptlrpc_service_part::scp_nthrs_starting, ptlrpc_service_part::scp_thr_nextid, ptlrpc_service_part::scp_threads, ptlrpc_service::srv_cptable, ptlrpc_service::srv_is_stopping, ptlrpc_service::srv_name, ptlrpc_service::srv_nthrs_cpt_init, ptlrpc_service::srv_nthrs_cpt_limit, ptlrpc_service::srv_thread_name, SVC_STARTING, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, ptlrpc_thread::t_id, ptlrpc_thread::t_link, ptlrpc_thread::t_name, ptlrpc_thread::t_svcpt, thread, thread_add_flags(), thread_is_running(), thread_is_stopped(), thread_is_stopping(), and unlikely.
Referenced by ptlrpc_main(), and ptlrpc_start_threads().
int ptlrpc_stop_pinger (void)
Definition at line 363 of file pinger.c.
References ENTRY, l_wait_event, pinger_thread, ptlrpc_pinger_remove_timeouts(), RETURN, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, thread_is_init(), thread_is_stopped(), and thread_set_flags().
Referenced by ptlrpc_exit(), and ptlrpc_init().
void sptlrpc_conf_choose_flavor (enum lustre_sec_part from, enum lustre_sec_part to, struct obd_uuid * target, lnet_nid_t nid, struct sptlrpc_flavor * sf)
Definition at line 843 of file sec_config.c.
References flavor_set_flags(), get_default_flavor(), LASSERT, MTI_NAME_MAXLEN, name, sptlrpc_conf::sc_rset, sptlrpc_conf_tgt::sct_rset, sptlrpc_conf_get(), sptlrpc_conf_get_tgt(), sptlrpc_conf_lock, sptlrpc_rule_set_choose(), target2fsname(), and obd_uuid::uuid.
Referenced by sptlrpc_import_sec_adapt().
void sptlrpc_conf_fini (void)
Definition at line 1217 of file sec_config.c.
References LASSERT, list_empty(), list_for_each_entry_safe, sptlrpc_conf::sc_list, sptlrpc_conf_free(), sptlrpc_conf_lock, and sptlrpc_confs.
Referenced by sptlrpc_fini(), and sptlrpc_init().
int sptlrpc_conf_init (void)
Definition at line 1210 of file sec_config.c.
References INIT_LIST_HEAD, sptlrpc_conf_lock, and sptlrpc_confs.
Referenced by sptlrpc_init().
void sptlrpc_enc_pool_fini (void)
Definition at line 827 of file sec_bulk.c.
References CDEBUG, CFS_TIME_T, D_SEC, enc_pools_cleanup(), enc_pools_free(), ptlrpc_enc_page_pool::epp_free_pages, ptlrpc_enc_page_pool::epp_pools, ptlrpc_enc_page_pool::epp_st_access, ptlrpc_enc_page_pool::epp_st_grow_fails, ptlrpc_enc_page_pool::epp_st_grows, ptlrpc_enc_page_pool::epp_st_max_pages, ptlrpc_enc_page_pool::epp_st_max_wait, ptlrpc_enc_page_pool::epp_st_max_wqlen, ptlrpc_enc_page_pool::epp_st_missings, ptlrpc_enc_page_pool::epp_st_outofmem, ptlrpc_enc_page_pool::epp_st_shrinks, ptlrpc_enc_page_pool::epp_total_pages, LASSERT, npages_to_npools(), page_pools, pools_shrinker, and remove_shrinker().
Referenced by sptlrpc_fini(), and sptlrpc_init().
int sptlrpc_enc_pool_init (void)
Definition at line 777 of file sec_bulk.c.
References cfs_time_current_sec(), DEF_SHRINKER_VAR, enc_pool_max_memory_mb, enc_pools_alloc(), enc_pools_free(), enc_pools_shrink(), enc_pools_shrink_count(), enc_pools_shrink_scan(), ptlrpc_enc_page_pool::epp_free_pages, ptlrpc_enc_page_pool::epp_growing, ptlrpc_enc_page_pool::epp_idle_idx, ptlrpc_enc_page_pool::epp_last_access, ptlrpc_enc_page_pool::epp_last_shrink, ptlrpc_enc_page_pool::epp_lock, ptlrpc_enc_page_pool::epp_max_pages, ptlrpc_enc_page_pool::epp_max_pools, ptlrpc_enc_page_pool::epp_pages_short, ptlrpc_enc_page_pool::epp_pools, ptlrpc_enc_page_pool::epp_st_access, ptlrpc_enc_page_pool::epp_st_grow_fails, ptlrpc_enc_page_pool::epp_st_grows, ptlrpc_enc_page_pool::epp_st_lowfree, ptlrpc_enc_page_pool::epp_st_max_pages, ptlrpc_enc_page_pool::epp_st_max_wait, ptlrpc_enc_page_pool::epp_st_max_wqlen, ptlrpc_enc_page_pool::epp_st_missings, ptlrpc_enc_page_pool::epp_st_outofmem, ptlrpc_enc_page_pool::epp_st_shrinks, ptlrpc_enc_page_pool::epp_total_pages, ptlrpc_enc_page_pool::epp_waitq, ptlrpc_enc_page_pool::epp_waitqlen, mult, npages_to_npools(), page_pools, pools_shrinker, pools_shrinker_seeks, and set_shrinker().
Referenced by sptlrpc_init().
void sptlrpc_fini (void)
Definition at line 2590 of file sec.c.
References sptlrpc_conf_fini(), sptlrpc_enc_pool_fini(), sptlrpc_gc_fini(), sptlrpc_lproc_fini(), sptlrpc_null_fini(), and sptlrpc_plain_fini().
Referenced by ptlrpc_exit(), and ptlrpc_init().
void sptlrpc_gc_fini (void)
Definition at line 247 of file sec_gc.c.
References l_wait_event, sec_gc_thread, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, thread_is_stopped(), and thread_set_flags().
Referenced by sptlrpc_fini(), and sptlrpc_init().
int sptlrpc_gc_init (void)
Definition at line 220 of file sec_gc.c.
References CERROR, INIT_LIST_HEAD, l_wait_event, sec_gc_ctx_list, sec_gc_ctx_list_lock, sec_gc_list, sec_gc_list_lock, sec_gc_main(), sec_gc_mutex, sec_gc_thread, ptlrpc_thread::t_ctl_waitq, and thread_is_running().
Referenced by sptlrpc_init().
int sptlrpc_init (void)
Definition at line 2544 of file sec.c.
References policy_lock, sptlrpc_conf_fini(), sptlrpc_conf_init(), sptlrpc_enc_pool_fini(), sptlrpc_enc_pool_init(), sptlrpc_gc_fini(), sptlrpc_gc_init(), sptlrpc_lproc_init(), sptlrpc_null_fini(), sptlrpc_null_init(), sptlrpc_plain_fini(), and sptlrpc_plain_init().
Referenced by ptlrpc_init().
void sptlrpc_lproc_fini (void)
Definition at line 202 of file sec_lproc.c.
References lprocfs_remove(), and sptlrpc_proc_root.
Referenced by sptlrpc_fini().
int sptlrpc_lproc_init (void)
Definition at line 186 of file sec_lproc.c.
References LASSERT, lprocfs_register(), proc_lustre_root, and sptlrpc_proc_root.
Referenced by sptlrpc_init().
void sptlrpc_null_fini (void)
Definition at line 453 of file sec_null.c.
References CERROR, ptlrpc_sec_policy::sp_name, and sptlrpc_unregister_policy().
Referenced by sptlrpc_fini(), and sptlrpc_init().
int sptlrpc_null_init (void)
Definition at line 440 of file sec_null.c.
References CERROR, null_init_internal(), ptlrpc_sec_policy::sp_name, and sptlrpc_register_policy().
Referenced by sptlrpc_init().
void sptlrpc_plain_fini (void)
Definition at line 1032 of file sec_plain.c.
References CERROR, and sptlrpc_unregister_policy().
Referenced by sptlrpc_fini(), and sptlrpc_init().
int sptlrpc_plain_init (void)
Definition at line 1017 of file sec_plain.c.
References CERROR, lustre_msg_early_size(), lustre_msg_size_v2(), plain_at_offset, PLAIN_PACK_MSG_OFF, PLAIN_PACK_SEGMENTS, and sptlrpc_register_policy().
Referenced by sptlrpc_init().
int sptlrpc_proc_enc_pool_seq_show (struct seq_file * m, void * v)
Definition at line 139 of file sec_bulk.c.
References cfs_time_current_sec(), CFS_TIME_T, ptlrpc_enc_page_pool::epp_free_pages, ptlrpc_enc_page_pool::epp_idle_idx, ptlrpc_enc_page_pool::epp_last_access, ptlrpc_enc_page_pool::epp_last_shrink, ptlrpc_enc_page_pool::epp_lock, ptlrpc_enc_page_pool::epp_max_pages, ptlrpc_enc_page_pool::epp_max_pools, ptlrpc_enc_page_pool::epp_st_access, ptlrpc_enc_page_pool::epp_st_grow_fails, ptlrpc_enc_page_pool::epp_st_grows, ptlrpc_enc_page_pool::epp_st_lowfree, ptlrpc_enc_page_pool::epp_st_max_pages, ptlrpc_enc_page_pool::epp_st_max_wait, ptlrpc_enc_page_pool::epp_st_max_wqlen, ptlrpc_enc_page_pool::epp_st_missings, ptlrpc_enc_page_pool::epp_st_outofmem, ptlrpc_enc_page_pool::epp_st_shrinks, ptlrpc_enc_page_pool::epp_total_pages, page_pools, and PAGES_PER_POOL.
static void tgt_mod_exit (void) [inline, static]
Definition at line 336 of file ptlrpc_internal.h.
static int tgt_mod_init (void) [inline, static]
Definition at line 331 of file ptlrpc_internal.h.
Variable Documentation
struct ptlrpc_nrs_pol_conf nrs_conf_fifo
FIFO policy configuration.
Definition at line 260 of file nrs_fifo.c.
Referenced by ptlrpc_nrs_init().
struct nrs_core nrs_core
nrs
Definition at line 53 of file nrs.c.
struct mutex pinger_mutex
Definition at line 52 of file pinger.c.
Referenced by pinger_check_timeout(), ptlrpc_add_timeout_client(), ptlrpc_del_timeout_client(), ptlrpc_init(), ptlrpc_pinger_add_import(), ptlrpc_pinger_del_import(), ptlrpc_pinger_main(), ptlrpc_pinger_register_timeout(), and ptlrpc_pinger_remove_timeouts().
struct list_head ptlrpc_all_services
Holds a list of all PTLRPC services.
Definition at line 68 of file service.c.
Referenced by nrs_policy_unregister_locked(), ptlrpc_init(), ptlrpc_nrs_policy_register(), and ptlrpc_register_service().
struct mutex ptlrpc_all_services_mutex
Used to protect the ptlrpc_all_services list.
Definition at line 70 of file service.c.
Referenced by nrs_policy_unregister_locked(), ptlrpc_init(), ptlrpc_nrs_policy_register(), ptlrpc_nrs_policy_unregister(), ptlrpc_register_service(), and ptlrpc_unregister_service().
int test_req_buffer_pressure
Definition at line 47 of file service.c.
Referenced by ptlrpc_check_rqbd_pool(), ptlrpc_register_service(), and request_in_callback().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.