Lustre: lustre/ptlrpc/ptlrpc_module.c File Reference
lustre/ptlrpc/ptlrpc_module.c File Reference
#include <obd_support.h>
#include <obd_class.h>
#include <lustre_net.h>
#include <lustre_req_layout.h>
#include "ptlrpc_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_RPC
Functions
static __init int ptlrpc_init (void)
static void __exit ptlrpc_exit (void)
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Request Processor and Lock Management")
MODULE_VERSION (LUSTRE_VERSION_STRING)
MODULE_LICENSE ("GPL")
module_init (ptlrpc_init)
module_exit (ptlrpc_exit)
Variables
spinlock_t ptlrpc_last_xid_lock
Define Documentation
#define DEBUG_SUBSYSTEM S_RPC
Definition at line 37 of file ptlrpc_module.c.
Function Documentation
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Request Processor and Lock Management")
module_exit (ptlrpc_exit)
module_init (ptlrpc_init)
MODULE_LICENSE ("GPL")
MODULE_VERSION (LUSTRE_VERSION_STRING)
static void __exit ptlrpc_exit (void) [static]
Definition at line 138 of file ptlrpc_module.c.
References ldlm_exit(), nodemap_mod_exit(), ptlrpc_connection_fini(), ptlrpc_exit_portals(), ptlrpc_hr_fini(), ptlrpc_nrs_fini(), ptlrpc_request_cache_fini(), ptlrpc_stop_pinger(), req_layout_fini(), sptlrpc_fini(), and tgt_mod_exit().
static __init int ptlrpc_init (void) [static]
Definition at line 52 of file ptlrpc_module.c.
References ENTRY, GOTO, INIT_LIST_HEAD, ldlm_exit(), ldlm_init(), lustre_assert_wire_constants(), nodemap_mod_init(), pinger_mutex, ptlrpc_all_services, ptlrpc_all_services_mutex, ptlrpc_connection_fini(), ptlrpc_connection_init(), ptlrpc_connection_put(), ptlrpc_exit_portals(), ptlrpc_hr_fini(), ptlrpc_hr_init(), ptlrpc_init_portals(), ptlrpc_init_xid(), ptlrpc_nrs_fini(), ptlrpc_nrs_init(), ptlrpc_put_connection_superhack, ptlrpc_request_cache_fini(), ptlrpc_request_cache_init(), ptlrpc_start_pinger(), ptlrpc_stop_pinger(), ptlrpcd_mutex, req_layout_fini(), req_layout_init(), RETURN, sptlrpc_fini(), sptlrpc_init(), tgt_mod_exit(), and tgt_mod_init().
Variable Documentation
spinlock_t ptlrpc_last_xid_lock
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.