Lustre: lustre/quota/qmt_dev.c File Reference
lustre/quota/qmt_dev.c File Reference
#include <obd_class.h>
#include <lprocfs_status.h>
#include <lustre_disk.h>
#include "qmt_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LQUOTA
Functions
static struct lu_device * qmt_device_fini (const struct lu_env *env, struct lu_device *ld)
static int qmt_connect_to_osd (const struct lu_env *env, struct qmt_device *qmt, struct lustre_cfg *cfg)
static int qmt_device_init0 (const struct lu_env *env, struct qmt_device *qmt, struct lu_device_type *ldt, struct lustre_cfg *cfg)
static struct lu_device * qmt_device_free (const struct lu_env *env, struct lu_device *ld)
static struct lu_device * qmt_device_alloc (const struct lu_env *env, struct lu_device_type *ldt, struct lustre_cfg *cfg)
LU_KEY_INIT_FINI (qmt, struct qmt_thread_info)
LU_TYPE_INIT_FINI (qmt,&qmt_thread_key)
LU_CONTEXT_KEY_DEFINE (qmt, LCT_MD_THREAD)
static int qmt_device_obd_connect (const struct lu_env *env, struct obd_export **exp, struct obd_device *obd, struct obd_uuid *cluuid, struct obd_connect_data *data, void *localdata)
static int qmt_device_obd_disconnect (struct obd_export *exp)
static int qmt_device_prepare (const struct lu_env *env, struct lu_device *parent, struct lu_device *ld)
int qmt_glb_init (void)
void qmt_glb_fini (void)
Variables
static struct lu_device_operations qmt_lu_ops
static struct
lu_device_type_operations qmt_device_type_ops
static struct lu_device_type qmt_device_type
struct obd_ops qmt_obd_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_LQUOTA
Definition at line 69 of file qmt_dev.c.
Function Documentation
LU_CONTEXT_KEY_DEFINE (qmt , LCT_MD_THREAD)
LU_KEY_INIT_FINI (qmt , struct qmt_thread_info)
LU_TYPE_INIT_FINI (qmt , & qmt_thread_key)
static int qmt_connect_to_osd (const struct lu_env * env, struct qmt_device * qmt, struct lustre_cfg * cfg) [static]
Definition at line 136 of file qmt_dev.c.
References CERROR, class_name2obd(), ENTRY, EXIT, obd_export::exp_obd, GOTO, LASSERT, lu_device::ld_site, lu2dt_dev(), lustre_cfg_string(), LUSTRE_VERSION_CODE, OBD_ALLOC_PTR, obd_connect(), OBD_CONNECT_VERSION, OBD_FREE_PTR, obd_device::obd_lu_dev, obd_device::obd_name, obd_device::obd_uuid, obd_connect_data::ocd_connect_flags, obd_connect_data::ocd_version, qmt2lu_dev(), qmt_device::qmt_child, qmt_device::qmt_child_exp, and qmt_device::qmt_svname.
Referenced by qmt_device_init0().
static struct lu_device* qmt_device_alloc (const struct lu_env * env, struct lu_device_type * ldt, struct lustre_cfg * cfg) [static, read]
Definition at line 312 of file qmt_dev.c.
References dt_device_init(), ENTRY, lu_device::ld_ops, OBD_ALLOC_PTR, qmt2lu_dev(), qmt_device_free(), qmt_device_init0(), qmt_device::qmt_dt_dev, qmt_lu_ops, and RETURN.
static struct lu_device* qmt_device_fini (const struct lu_env * env, struct lu_device * ld) [static, read]
Definition at line 89 of file qmt_dev.c.
References CDEBUG, D_QUOTA, ENTRY, LASSERT, lu_device::ld_obd, lprocfs_remove(), lu2qmt_dev(), obd_disconnect(), obd_device::obd_namespace, qmt_device::qmt_child, qmt_device::qmt_child_exp, qmt_device::qmt_ns, qmt_pool_fini(), qmt_device::qmt_proc, qmt_stop_reba_thread(), qmt_device::qmt_stopping, qmt_device::qmt_svname, and RETURN.
Referenced by qmt_device_init0().
static struct lu_device* qmt_device_free (const struct lu_env * env, struct lu_device * ld) [static, read]
Definition at line 289 of file qmt_dev.c.
References ENTRY, LASSERT, lu2qmt_dev(), lu_device_fini(), OBD_FREE_PTR, and RETURN.
Referenced by qmt_device_alloc().
static int qmt_device_init0 (const struct lu_env * env, struct qmt_device * qmt, struct lu_device_type * ldt, struct lustre_cfg * cfg) [static]
Definition at line 199 of file qmt_dev.c.
References CERROR, class_name2obd(), class_search_type(), ENTRY, EXIT, GOTO, INIT_LIST_HEAD, LASSERT, lu_device::ld_obd, lprocfs_register(), lustre_cfg_string(), LUSTRE_QMT_NAME, obd_device::obd_lu_dev, obd_device::obd_namespace, qmt2lu_dev(), qmt_connect_to_osd(), qmt_device_fini(), qmt_device::qmt_ns, qmt_pool_init(), qmt_device::qmt_proc, qmt_device::qmt_reba_list, qmt_device::qmt_reba_lock, qmt_device::qmt_reba_thread, qmt_start_reba_thread(), qmt_device::qmt_svname, RETURN, strlcpy(), SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, thread_set_flags(), and obd_type::typ_procroot.
Referenced by qmt_device_alloc().
static int qmt_device_obd_connect (const struct lu_env * env, struct obd_export ** exp, struct obd_device * obd, struct obd_uuid * cluuid, struct obd_connect_data * data, void * localdata) [static]
Definition at line 375 of file qmt_dev.c.
References class_conn2export(), class_connect(), ENTRY, and RETURN.
static int qmt_device_obd_disconnect (struct obd_export * exp) [static]
Definition at line 399 of file qmt_dev.c.
References class_disconnect(), class_manual_cleanup(), ENTRY, obd_export::exp_obd, and RETURN.
static int qmt_device_prepare (const struct lu_env * env, struct lu_device * parent, struct lu_device * ld) [static]
Definition at line 432 of file qmt_dev.c.
References CERROR, dt_object::do_lu, ENTRY, lquota_disk_dir_find_create(), lu2qmt_dev(), lu_object_put(), qmt_device::qmt_child, QMT_DIR, qmt_pool_prepare(), qmt_device::qmt_svname, and RETURN.
void qmt_glb_fini (void)
Definition at line 480 of file qmt_dev.c.
References class_unregister_type(), and LUSTRE_QMT_NAME.
Referenced by lquota_exit(), and lquota_init().
int qmt_glb_init (void)
Definition at line 469 of file qmt_dev.c.
References class_register_type(), ENTRY, LUSTRE_QMT_NAME, and RETURN.
Referenced by lquota_init().
Variable Documentation
struct lu_device_type qmt_device_type [static]
Initial value:
 {
        .ldt_tags       = LU_DEVICE_DT,
        .ldt_name       = LUSTRE_QMT_NAME,
        .ldt_ops        = &qmt_device_type_ops,
        .ldt_ctx_tags   = LCT_MD_THREAD,
}
Definition at line 365 of file qmt_dev.c.
struct lu_device_type_operations qmt_device_type_ops [static]
Initial value:
 {
        .ldto_init              = qmt_type_init,
        .ldto_fini              = qmt_type_fini,
        .ldto_start             = qmt_type_start,
        .ldto_stop              = qmt_type_stop,
        .ldto_device_alloc      = qmt_device_alloc,
        .ldto_device_free       = qmt_device_free,
        .ldto_device_fini       = qmt_device_fini,
}
Definition at line 348 of file qmt_dev.c.
static struct lu_device_operations qmt_lu_ops [static, read]
Initial value:
 {
        .ldo_prepare            = qmt_device_prepare,
        .ldo_process_config     = NULL,
}
Definition at line 76 of file qmt_dev.c.
Referenced by qmt_device_alloc().
struct obd_ops qmt_obd_ops
Initial value:
 {
        .o_owner        = THIS_MODULE,
        .o_connect      = qmt_device_obd_connect,
        .o_disconnect   = qmt_device_obd_disconnect,
}
Definition at line 416 of file qmt_dev.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.