Lustre: lustre/quota/qmt_pool.c File Reference
lustre/quota/qmt_pool.c File Reference
#include <obd_class.h>
#include <lprocfs_status.h>
#include "qmt_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LQUOTA
Functions
static void qmt_pool_free (const struct lu_env *, struct qmt_pool_info *)
static void qpi_getref (struct qmt_pool_info *pool)
static void qpi_putref (const struct lu_env *env, struct qmt_pool_info *pool)
static void qpi_putref_locked (struct qmt_pool_info *pool)
static unsigned qpi_hash_hash (struct cfs_hash *hs, const void *key, unsigned mask)
static void * qpi_hash_key (struct hlist_node *hnode)
static int qpi_hash_keycmp (const void *key, struct hlist_node *hnode)
static void * qpi_hash_object (struct hlist_node *hnode)
static void qpi_hash_get (struct cfs_hash *hs, struct hlist_node *hnode)
static void qpi_hash_put_locked (struct cfs_hash *hs, struct hlist_node *hnode)
static void qpi_hash_exit (struct cfs_hash *hs, struct hlist_node *hnode)
static int qpi_state_seq_show (struct seq_file *m, void *data)
LPROC_SEQ_FOPS_RO (qpi_state)
static int qpi_soft_least_qunit_seq_show (struct seq_file *m, void *data)
static ssize_t qpi_soft_least_qunit_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
LPROC_SEQ_FOPS (qpi_soft_least_qunit)
static int qmt_pool_alloc (const struct lu_env *env, struct qmt_device *qmt, int pool_id, int pool_type)
static struct qmt_pool_info * qmt_pool_lookup (const struct lu_env *env, struct qmt_device *qmt, int pool_id, int pool_type)
void qmt_pool_fini (const struct lu_env *env, struct qmt_device *qmt)
int qmt_pool_init (const struct lu_env *env, struct qmt_device *qmt)
static int qmt_slv_cnt (const struct lu_env *env, struct lu_fid *glb_fid, char *slv_name, struct lu_fid *slv_fid, void *arg)
int qmt_pool_prepare (const struct lu_env *env, struct qmt_device *qmt, struct dt_object *qmt_root)
int qmt_pool_new_conn (const struct lu_env *env, struct qmt_device *qmt, struct lu_fid *glb_fid, struct lu_fid *slv_fid, __u64 *slv_ver, struct obd_uuid *uuid)
struct lquota_entry * qmt_pool_lqe_lookup (const struct lu_env *env, struct qmt_device *qmt, int pool_id, int pool_type, int qtype, union lquota_id *qid)
Variables
static struct cfs_hash_ops qpi_hash_ops
static struct lprocfs_vars lprocfs_quota_qpi_vars []
Define Documentation
#define DEBUG_SUBSYSTEM S_LQUOTA
Definition at line 51 of file qmt_pool.c.
Function Documentation
LPROC_SEQ_FOPS (qpi_soft_least_qunit)
LPROC_SEQ_FOPS_RO (qpi_state)
static int qmt_pool_alloc (const struct lu_env * env, struct qmt_device * qmt, int pool_id, int pool_type) [static]
Definition at line 235 of file qmt_pool.c.
References CERROR, cfs_hash_add_unique(), ENTRY, EXIT, GOTO, INIT_LIST_HEAD, list_add_tail(), lprocfs_register(), LQUOTA_LEAST_QUNIT, LQUOTA_RES_DT, lu_device_get(), lu_ref_add(), OBD_ALLOC_PTR, qmt2lu_dev(), qmt_info(), qmt_device::qmt_pool_hash, qmt_device::qmt_pool_list, qmt_device::qmt_proc, qmt_device::qmt_svname, qmt_pool_info::qpi_hash, qmt_pool_info::qpi_key, qmt_pool_info::qpi_least_qunit, qmt_pool_info::qpi_linkage, qmt_pool_info::qpi_proc, qpi_putref(), qmt_pool_info::qpi_qmt, qmt_pool_info::qpi_ref, qmt_pool_info::qpi_soft_least_qunit, qmt_thread_info::qti_buf, RES_NAME, and RETURN.
Referenced by qmt_pool_init().
void qmt_pool_fini (const struct lu_env * env, struct qmt_device * qmt)
Definition at line 393 of file qmt_pool.c.
References cfs_hash_del(), cfs_hash_putref(), ENTRY, EXIT, LASSERT, list_del_init(), list_empty(), list_entry, list_for_each_safe, qmt_device::qmt_pool_hash, qmt_device::qmt_pool_list, qmt_pool_info::qpi_hash, qmt_pool_info::qpi_key, qmt_pool_info::qpi_linkage, qpi_putref(), and RETURN_EXIT.
Referenced by qmt_device_fini(), and qmt_pool_init().
static void qmt_pool_free (const struct lu_env * env, struct qmt_pool_info * pool) [static]
Definition at line 304 of file qmt_pool.c.
References dt_object::do_lu, ENTRY, LASSERT, lu_device::ld_reference, list_empty(), lprocfs_remove(), lqe_putref(), lquota_site_free(), lu_device_put(), lu_object_put(), lu_ref_del(), OBD_FREE_PTR, qmt2lu_dev(), qmt_pool_info::qpi_glb_obj, qmt_pool_info::qpi_grace_lqe, qmt_pool_info::qpi_linkage, qmt_pool_info::qpi_proc, qmt_pool_info::qpi_qmt, qmt_pool_info::qpi_root, and qmt_pool_info::qpi_site.
Referenced by qpi_putref().
int qmt_pool_init (const struct lu_env * env, struct qmt_device * qmt)
Definition at line 434 of file qmt_pool.c.
References CERROR, cfs_hash_create(), CFS_HASH_DEFAULT, CFS_HASH_MAX_THETA, CFS_HASH_MIN_THETA, ENTRY, HASH_POOLS_BKT_BITS, HASH_POOLS_CUR_BITS, HASH_POOLS_MAX_BITS, INIT_LIST_HEAD, LQUOTA_FIRST_RES, LQUOTA_LAST_RES, qmt_pool_alloc(), qmt_pool_fini(), qmt_device::qmt_pool_hash, qmt_device::qmt_pool_list, qmt_device::qmt_svname, and RETURN.
Referenced by qmt_device_init0().
static struct qmt_pool_info* qmt_pool_lookup (const struct lu_env * env, struct qmt_device * qmt, int pool_id, int pool_type) [static, read]
Definition at line 358 of file qmt_pool.c.
References CERROR, cfs_hash_lookup(), ENTRY, LASSERT, qmt_device::qmt_pool_hash, qmt_device::qmt_svname, and RETURN.
Referenced by qmt_pool_lqe_lookup(), and qmt_pool_new_conn().
struct lquota_entry* qmt_pool_lqe_lookup (const struct lu_env * env, struct qmt_device * qmt, int pool_id, int pool_type, int qtype, union lquota_id * qid) [read]
Definition at line 710 of file qmt_pool.c.
References ENTRY, GOTO, lqe_getref(), lqe_locate(), lquota_id::qid_uid, qmt_pool_lookup(), qpi_putref(), and RETURN.
Referenced by qmt_dqacq(), qmt_get(), qmt_lvbo_init(), and qmt_set().
int qmt_pool_new_conn (const struct lu_env * env, struct qmt_device * qmt, struct lu_fid * glb_fid, struct lu_fid * slv_fid, __u64 * slv_ver, struct obd_uuid * uuid)
Definition at line 648 of file qmt_pool.c.
References CERROR, dt_object::do_lu, dt_version_get(), GOTO, lquota_disk_slv_find(), lquota_disk_slv_find_create(), lquota_extract_fid(), lu_object_fid(), lu_object_put(), obd_uuid2str(), qmt_device::qmt_child, qmt_pool_lookup(), qmt_device::qmt_svname, qpi_putref(), qmt_pool_info::qpi_root, qmt_pool_info::qpi_slv_nr, and RETURN.
Referenced by qmt_intent_policy().
int qmt_pool_prepare (const struct lu_env * env, struct qmt_device * qmt, struct dt_object * qmt_root)
Definition at line 494 of file qmt_pool.c.
References CERROR, CWARN, DFID, dt_version_get(), ENTRY, LASSERT, list_entry, list_for_each, lprocfs_quota_seq_fops, lqe_locate(), lquota_disk_dir_find_create(), lquota_disk_for_each_slv(), lquota_disk_glb_find_create(), lquota_disk_update_ver(), lquota_disk_write_glb(), lquota_generate_fid(), LQUOTA_RES_MD, lquota_site_alloc(), MAX_DQ_TIME, MAX_IQ_TIME, PFID, lquota_glb_rec::qbr_granted, lquota_glb_rec::qbr_hardlimit, lquota_glb_rec::qbr_softlimit, lquota_glb_rec::qbr_time, lquota_id::qid_uid, qmt_device::qmt_child, qmt_info(), qmt_lqe_ops, qmt_device::qmt_pool_hash, qmt_device::qmt_pool_list, qmt_slv_cnt(), qmt_device::qmt_svname, qmt_pool_info::qpi_glb_obj, qmt_pool_info::qpi_grace_lqe, qmt_pool_info::qpi_key, qmt_pool_info::qpi_proc, qmt_pool_info::qpi_qmt, qmt_pool_info::qpi_root, qmt_pool_info::qpi_site, qmt_pool_info::qpi_slv_nr, qmt_thread_info::qti_buf, qmt_thread_info::qti_fid, qmt_thread_info::qti_id, QTYPE_NAME, RES_NAME, RETURN, and version.
Referenced by qmt_device_prepare().
static int qmt_slv_cnt (const struct lu_env * env, struct lu_fid * glb_fid, char * slv_name, struct lu_fid * slv_fid, void * arg) [static]
Definition at line 473 of file qmt_pool.c.
Referenced by qmt_pool_prepare().
static void qpi_getref (struct qmt_pool_info * pool) [inline, static]
Definition at line 66 of file qmt_pool.c.
References qmt_pool_info::qpi_ref.
Referenced by qpi_hash_get().
static void qpi_hash_exit (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 128 of file qmt_pool.c.
References CERROR.
static void qpi_hash_get (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 114 of file qmt_pool.c.
References hlist_entry, qpi_getref(), and qmt_pool_info::qpi_hash.
static unsigned qpi_hash_hash (struct cfs_hash * hs, const void * key, unsigned mask) [static]
Definition at line 90 of file qmt_pool.c.
References cfs_hash_u32_hash().
static void* qpi_hash_key (struct hlist_node * hnode) [static]
Definition at line 95 of file qmt_pool.c.
References hlist_entry, qmt_pool_info::qpi_hash, and qmt_pool_info::qpi_key.
static int qpi_hash_keycmp (const void * key, struct hlist_node * hnode) [static]
Definition at line 102 of file qmt_pool.c.
References hlist_entry, qmt_pool_info::qpi_hash, and qmt_pool_info::qpi_key.
static void* qpi_hash_object (struct hlist_node * hnode) [static]
Definition at line 109 of file qmt_pool.c.
References hlist_entry, and qmt_pool_info::qpi_hash.
static void qpi_hash_put_locked (struct cfs_hash * hs, struct hlist_node * hnode) [static]
Definition at line 121 of file qmt_pool.c.
References hlist_entry, qmt_pool_info::qpi_hash, and qpi_putref_locked().
static void qpi_putref (const struct lu_env * env, struct qmt_pool_info * pool) [inline, static]
Definition at line 71 of file qmt_pool.c.
References LASSERT, qmt_pool_free(), and qmt_pool_info::qpi_ref.
Referenced by qmt_pool_alloc(), qmt_pool_fini(), qmt_pool_lqe_lookup(), and qmt_pool_new_conn().
static void qpi_putref_locked (struct qmt_pool_info * pool) [inline, static]
Definition at line 79 of file qmt_pool.c.
References LASSERT, and qmt_pool_info::qpi_ref.
Referenced by qpi_hash_put_locked().
static int qpi_soft_least_qunit_seq_show (struct seq_file * m, void * data) [static]
Definition at line 174 of file qmt_pool.c.
References LASSERT, and qmt_pool_info::qpi_soft_least_qunit.
static ssize_t qpi_soft_least_qunit_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Definition at line 183 of file qmt_pool.c.
References LASSERT, LQUOTA_RES_DT, qmt_pool_info::qpi_key, qmt_pool_info::qpi_least_qunit, and qmt_pool_info::qpi_soft_least_qunit.
static int qpi_state_seq_show (struct seq_file * m, void * data) [static]
Definition at line 145 of file qmt_pool.c.
References cfs_hash::hs_count, LASSERT, lquota_site::lqs_hash, qmt_pool_info::qpi_key, qmt_pool_info::qpi_least_qunit, qmt_pool_info::qpi_ref, qmt_pool_info::qpi_site, qmt_pool_info::qpi_slv_nr, QTYPE_NAME, and RES_NAME.
Variable Documentation
struct lprocfs_vars lprocfs_quota_qpi_vars[] [static]
Initial value:
 {
        { .name =       "info",
          .fops =       &qpi_state_fops },
        { .name =       "soft_least_qunit",
          .fops =       &qpi_soft_least_qunit_fops },
        { NULL }
}
Definition at line 215 of file qmt_pool.c.
struct cfs_hash_ops qpi_hash_ops [static]
Initial value:
 {
        .hs_hash        = qpi_hash_hash,
        .hs_key         = qpi_hash_key,
        .hs_keycmp      = qpi_hash_keycmp,
        .hs_object      = qpi_hash_object,
        .hs_get         = qpi_hash_get,
        .hs_put_locked  = qpi_hash_put_locked,
        .hs_exit        = qpi_hash_exit
}
Definition at line 134 of file qmt_pool.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.