Lustre: lustre/quota/qmt_entry.c File Reference
lustre/quota/qmt_entry.c File Reference
#include "qmt_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LQUOTA
Functions
static void qmt_lqe_init (struct lquota_entry *lqe, void *arg)
static int qmt_lqe_read (const struct lu_env *env, struct lquota_entry *lqe, void *arg)
static void qmt_lqe_debug (struct lquota_entry *lqe, void *arg, struct libcfs_debug_msg_data *msgdata, const char *fmt, va_list args)
struct thandle * qmt_trans_start_with_slv (const struct lu_env *env, struct lquota_entry *lqe, struct dt_object *slv_obj, struct qmt_lqe_restore *restore)
struct thandle * qmt_trans_start (const struct lu_env *env, struct lquota_entry *lqe, struct qmt_lqe_restore *restore)
int qmt_glb_write (const struct lu_env *env, struct thandle *th, struct lquota_entry *lqe, __u32 flags, __u64 *ver)
int qmt_slv_read (const struct lu_env *env, struct lquota_entry *lqe, struct dt_object *slv_obj, __u64 *granted)
int qmt_slv_write (const struct lu_env *env, struct thandle *th, struct lquota_entry *lqe, struct dt_object *slv_obj, __u32 flags, __u64 *ver, __u64 granted)
int qmt_validate_limits (struct lquota_entry *lqe, __u64 hard, __u64 soft)
void qmt_adjust_edquot (struct lquota_entry *lqe, __u64 now)
static __u64 qmt_calc_softlimit (struct lquota_entry *lqe, bool *oversoft)
__u64 qmt_alloc_expand (struct lquota_entry *lqe, __u64 granted, __u64 spare)
void qmt_adjust_qunit (const struct lu_env *env, struct lquota_entry *lqe)
void qmt_revalidate (const struct lu_env *env, struct lquota_entry *lqe)
Variables
struct lquota_entry_operations qmt_lqe_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_LQUOTA
Definition at line 31 of file qmt_entry.c.
Function Documentation
void qmt_adjust_edquot (struct lquota_entry * lqe, __u64 now)
Definition at line 410 of file qmt_entry.c.
References cfs_time_before_64(), cfs_time_shift_64(), ENTRY, EXIT, lqe2qpi(), lquota_entry::lqe_edquot, lquota_entry::lqe_enforced, lquota_entry::lqe_granted, lquota_entry::lqe_id, lquota_entry::lqe_qunit, LQUOTA_DEBUG, LQUOTA_RES_DT, lquota_id::qid_uid, qmt_hard_exhausted(), qmt_id_lock_notify(), QMT_REBA_TIMEOUT, qmt_space_exhausted(), qmt_pool_info::qpi_key, qmt_pool_info::qpi_least_qunit, qmt_pool_info::qpi_qmt, qmt_pool_info::qpi_soft_least_qunit, and RETURN_EXIT.
Referenced by qmt_dqacq0(), qmt_id_lock_glimpse(), qmt_revalidate(), and qmt_set().
void qmt_adjust_qunit (const struct lu_env * env, struct lquota_entry * lqe)
Definition at line 573 of file qmt_entry.c.
References __u64, cfs_time_current_64, done, ENTRY, EXIT, GOTO, LASSERT, LPU64, lqe2qpi(), lquota_entry::lqe_enforced, lquota_entry::lqe_granted, lquota_entry::lqe_id, lqe_is_locked(), lquota_entry::lqe_qunit, lquota_entry::lqe_site, lquota_site::lqs_qtype, LQUOTA_DEBUG, LQUOTA_ERROR, lquota_id::qid_uid, qmt_calc_softlimit(), qmt_id_lock_notify(), qmt_pool_info::qpi_least_qunit, qmt_pool_info::qpi_qmt, qmt_pool_info::qpi_slv_nr, qmt_pool_info::qpi_soft_least_qunit, RETURN_EXIT, and swap.
Referenced by qmt_dqacq0(), qmt_revalidate(), and qmt_set().
__u64 qmt_alloc_expand (struct lquota_entry * lqe, __u64 granted, __u64 spare)
Definition at line 514 of file qmt_entry.c.
References __u64, LASSERT, lqe2qpi(), lquota_entry::lqe_enforced, lquota_entry::lqe_granted, lquota_entry::lqe_qunit, lquota_entry::lqe_site, lquota_site::lqs_qtype, min_t, qmt_calc_softlimit(), qmt_pool_info::qpi_least_qunit, qmt_pool_info::qpi_slv_nr, qmt_pool_info::qpi_soft_least_qunit, and RETURN.
Referenced by qmt_dqacq0().
static __u64 qmt_calc_softlimit (struct lquota_entry * lqe, bool * oversoft) [static]
Definition at line 481 of file qmt_entry.c.
References LASSERT, lqe2qpi(), lquota_entry::lqe_granted, LQUOTA_RES_DT, qmt_pool_info::qpi_key, and qmt_pool_info::qpi_soft_least_qunit.
Referenced by qmt_adjust_qunit(), and qmt_alloc_expand().
int qmt_glb_write (const struct lu_env * env, struct thandle * th, struct lquota_entry * lqe, __u32 flags, __u64 * ver)
Definition at line 244 of file qmt_entry.c.
References ENTRY, LASSERT, LQE_GLB_OBJ, lquota_entry::lqe_granted, lquota_entry::lqe_id, lqe_is_locked(), lqe_is_master(), lquota_entry::lqe_uptodate, LQUOTA_BUMP_VER, LQUOTA_DEBUG, lquota_disk_write(), LQUOTA_ERROR, LQUOTA_SET_VER, lquota_glb_rec::qbr_granted, lquota_glb_rec::qbr_hardlimit, lquota_glb_rec::qbr_softlimit, lquota_glb_rec::qbr_time, qmt_info(), and RETURN.
Referenced by qmt_dqacq0(), and qmt_set().
static void qmt_lqe_debug (struct lquota_entry * lqe, void * arg, struct libcfs_debug_msg_data * msgdata, const char * fmt, va_list args) [static]
Definition at line 108 of file qmt_entry.c.
References libcfs_debug_vmsg2(), LPU64, lquota_entry::lqe_edquot, lquota_entry::lqe_enforced, lquota_entry::lqe_granted, lquota_entry::lqe_id, lquota_entry::lqe_qunit, lquota_id::qid_uid, qmt_device::qmt_svname, qmt_pool_info::qpi_key, qmt_pool_info::qpi_qmt, and RES_NAME.
static void qmt_lqe_init (struct lquota_entry * lqe, void * arg) [static]
Definition at line 41 of file qmt_entry.c.
References LASSERT, and lqe_is_master().
static int qmt_lqe_read (const struct lu_env * env, struct lquota_entry * lqe, void * arg) [static]
Definition at line 57 of file qmt_entry.c.
References ENTRY, LASSERT, lquota_entry::lqe_enforced, lquota_entry::lqe_granted, lquota_entry::lqe_id, lqe_is_master(), lquota_entry::lqe_site, lquota_site::lqs_qtype, LQUOTA_DEBUG, lquota_disk_read(), LQUOTA_ERROR, qmt_info(), qmt_pool_info::qpi_glb_obj, and RETURN.
void qmt_revalidate (const struct lu_env * env, struct lquota_entry * lqe)
Definition at line 686 of file qmt_entry.c.
References cfs_time_current_sec(), lquota_entry::lqe_qunit, qmt_adjust_edquot(), and qmt_adjust_qunit().
Referenced by qmt_dqacq0(), and qmt_set().
int qmt_slv_read (const struct lu_env * env, struct lquota_entry * lqe, struct dt_object * slv_obj, __u64 * granted)
Definition at line 298 of file qmt_entry.c.
References DFID, dt_object::do_lu, ENTRY, LASSERT, LPU64, lquota_entry::lqe_id, lqe_is_locked(), lqe_is_master(), LQUOTA_DEBUG, lquota_disk_read(), LQUOTA_ERROR, lu_object_fid(), PFID, qmt_info(), and RETURN.
Referenced by qmt_dqacq0().
int qmt_slv_write (const struct lu_env * env, struct thandle * th, struct lquota_entry * lqe, struct dt_object * slv_obj, __u32 flags, __u64 * ver, __u64 granted)
Definition at line 350 of file qmt_entry.c.
References DFID, dt_object::do_lu, ENTRY, LASSERT, LPU64, lquota_entry::lqe_id, lqe_is_locked(), lqe_is_master(), LQUOTA_DEBUG, lquota_disk_write(), LQUOTA_ERROR, lu_object_fid(), PFID, qmt_info(), lquota_slv_rec::qsr_granted, and RETURN.
Referenced by qmt_dqacq0().
struct thandle* qmt_trans_start (const struct lu_env * env, struct lquota_entry * lqe, struct qmt_lqe_restore * restore) [read]
Definition at line 220 of file qmt_entry.c.
References LQUOTA_DEBUG, and qmt_trans_start_with_slv().
Referenced by qmt_set().
struct thandle* qmt_trans_start_with_slv (const struct lu_env * env, struct lquota_entry * lqe, struct dt_object * slv_obj, struct qmt_lqe_restore * restore) [read]
Definition at line 148 of file qmt_entry.c.
References DFID, dt_object::do_lu, dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), ENTRY, EXIT, GOTO, LASSERT, lqe2qpi(), LQE_GLB_OBJ, lquota_entry::lqe_granted, lquota_entry::lqe_id, lqe_is_master(), lquota_entry::lqe_qunit, LQUOTA_DEBUG, lquota_disk_declare_write(), LQUOTA_ERROR, lu_object_fid(), PFID, qmt_lqe_restore::qlr_gracetime, qmt_lqe_restore::qlr_granted, qmt_lqe_restore::qlr_hardlimit, qmt_lqe_restore::qlr_qunit, qmt_lqe_restore::qlr_softlimit, qmt_device::qmt_child, qmt_pool_info::qpi_qmt, RETURN, and thandle::th_sync.
Referenced by qmt_dqacq0(), and qmt_trans_start().
int qmt_validate_limits (struct lquota_entry * lqe, __u64 hard, __u64 soft)
Definition at line 393 of file qmt_entry.c.
References ENTRY, and RETURN.
Referenced by qmt_set().
Variable Documentation
struct lquota_entry_operations qmt_lqe_ops
Initial value:
 {
        .lqe_init       = qmt_lqe_init,
        .lqe_read       = qmt_lqe_read,
        .lqe_debug      = qmt_lqe_debug,
}
Definition at line 131 of file qmt_entry.c.
Referenced by qmt_pool_prepare().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.