Lustre: lustre/quota/qmt_internal.h File Reference
lustre/quota/qmt_internal.h File Reference
#include "lquota_internal.h"
Data Structures
struct qmt_device
struct qmt_pool_info
struct qmt_lqe_restore
struct qmt_thread_info
Defines
#define LQE_ROOT(lqe) (lqe2qpi(lqe)->qpi_root)
#define LQE_GLB_OBJ(lqe) (lqe2qpi(lqe)->qpi_glb_obj[lqe->lqe_site->lqs_qtype])
#define QMT_GRANT(lqe, slv, cnt)
#define QMT_REL(lqe, slv, cnt)
#define QMT_REBA_TIMEOUT 2
Functions
static struct qmt_pool_info * lqe2qpi (struct lquota_entry *lqe)
static bool lqe_is_locked (struct lquota_entry *lqe)
static struct qmt_thread_info * qmt_info (const struct lu_env *env)
static struct qmt_device * lu2qmt_dev (struct lu_device *ld)
static struct lu_device * qmt2lu_dev (struct qmt_device *qmt)
static __u64 qmt_lqe_grace (struct lquota_entry *lqe)
static void qmt_restore (struct lquota_entry *lqe, struct qmt_lqe_restore *restore)
static bool qmt_hard_exhausted (struct lquota_entry *lqe)
static bool qmt_soft_exhausted (struct lquota_entry *lqe, __u64 now)
static bool qmt_space_exhausted (struct lquota_entry *lqe, __u64 now)
void qmt_pool_fini (const struct lu_env *, struct qmt_device *)
int qmt_pool_init (const struct lu_env *, struct qmt_device *)
int qmt_pool_prepare (const struct lu_env *, struct qmt_device *, struct dt_object *)
int qmt_pool_new_conn (const struct lu_env *, struct qmt_device *, struct lu_fid *, struct lu_fid *, __u64 *, struct obd_uuid *)
struct lquota_entry * qmt_pool_lqe_lookup (const struct lu_env *, struct qmt_device *, int, int, int, union lquota_id *)
struct thandle * qmt_trans_start_with_slv (const struct lu_env *, struct lquota_entry *, struct dt_object *, struct qmt_lqe_restore *)
struct thandle * qmt_trans_start (const struct lu_env *, struct lquota_entry *, struct qmt_lqe_restore *)
int qmt_glb_write (const struct lu_env *, struct thandle *, struct lquota_entry *, __u32, __u64 *)
int qmt_slv_write (const struct lu_env *, struct thandle *, struct lquota_entry *, struct dt_object *, __u32, __u64 *, __u64)
int qmt_slv_read (const struct lu_env *, struct lquota_entry *, struct dt_object *, __u64 *)
int qmt_validate_limits (struct lquota_entry *, __u64, __u64)
void qmt_adjust_qunit (const struct lu_env *, struct lquota_entry *)
void qmt_adjust_edquot (struct lquota_entry *, __u64)
void qmt_revalidate (const struct lu_env *, struct lquota_entry *)
__u64 qmt_alloc_expand (struct lquota_entry *, __u64, __u64)
int qmt_dqacq0 (const struct lu_env *, struct lquota_entry *, struct qmt_device *, struct obd_uuid *, __u32, __u64, __u64, struct quota_body *)
int qmt_intent_policy (const struct lu_env *, struct lu_device *, struct ptlrpc_request *, struct ldlm_lock **, int)
int qmt_lvbo_init (struct lu_device *, struct ldlm_resource *)
int qmt_lvbo_update (struct lu_device *, struct ldlm_resource *, struct ptlrpc_request *, int)
int qmt_lvbo_size (struct lu_device *, struct ldlm_lock *)
int qmt_lvbo_fill (struct lu_device *, struct ldlm_lock *, void *, int)
int qmt_lvbo_free (struct lu_device *, struct ldlm_resource *)
int qmt_start_reba_thread (struct qmt_device *)
void qmt_stop_reba_thread (struct qmt_device *)
void qmt_glb_lock_notify (const struct lu_env *, struct lquota_entry *, __u64)
void qmt_id_lock_notify (struct qmt_device *, struct lquota_entry *)
Variables
struct lu_context_key qmt_thread_key
struct lquota_entry_operations qmt_lqe_ops
Define Documentation
#define LQE_GLB_OBJ (lqe) (lqe2qpi(lqe)->qpi_glb_obj[lqe->lqe_site->lqs_qtype])
Definition at line 232 of file qmt_internal.h.
Referenced by qmt_dqacq0(), qmt_glb_write(), and qmt_trans_start_with_slv().
#define LQE_ROOT (lqe) (lqe2qpi(lqe)->qpi_root)
Definition at line 231 of file qmt_internal.h.
Referenced by qmt_dqacq0().
#define QMT_GRANT (lqe, slv, cnt)
Value:
do {                                 \
                (lqe)->lqe_granted += (cnt); \
                (slv) += (cnt);              \
        } while (0)
Definition at line 256 of file qmt_internal.h.
Referenced by qmt_dqacq0().
#define QMT_REBA_TIMEOUT 2
Definition at line 295 of file qmt_internal.h.
Referenced by qmt_adjust_edquot().
#define QMT_REL (lqe, slv, cnt)
Value:
do {                                 \
                (lqe)->lqe_granted -= (cnt); \
                (slv) -= (cnt);              \
        } while (0)
Definition at line 261 of file qmt_internal.h.
Referenced by qmt_dqacq0().
Function Documentation
static struct qmt_pool_info* lqe2qpi (struct lquota_entry * lqe) [static, read]
Definition at line 165 of file qmt_internal.h.
References LASSERT, lqe_is_master(), lquota_entry::lqe_site, and lquota_site::lqs_parent.
Referenced by qmt_adjust_edquot(), qmt_adjust_qunit(), qmt_alloc_expand(), qmt_calc_softlimit(), qmt_glb_lock_notify(), qmt_id_lock_glimpse(), qmt_lqe_grace(), and qmt_trans_start_with_slv().
static bool lqe_is_locked (struct lquota_entry * lqe) [inline, static]
Definition at line 172 of file qmt_internal.h.
References LASSERT, lqe_is_master(), and lqe_write_unlock().
Referenced by qmt_adjust_qunit(), qmt_glb_write(), qmt_slv_read(), and qmt_slv_write().
static struct qmt_device* lu2qmt_dev (struct lu_device * ld) [static, read]
Definition at line 220 of file qmt_internal.h.
References lu2dt_dev(), and qmt_device::qmt_dt_dev.
Referenced by qmt_device_fini(), qmt_device_free(), qmt_device_prepare(), qmt_dqacq(), qmt_intent_policy(), qmt_lvbo_init(), qmt_lvbo_update(), and qmt_quotactl().
static struct lu_device* qmt2lu_dev (struct qmt_device * qmt) [static, read]
Definition at line 226 of file qmt_internal.h.
References dt_device::dd_lu_dev, and qmt_device::qmt_dt_dev.
Referenced by qmt_connect_to_osd(), qmt_device_alloc(), qmt_device_init0(), qmt_pool_alloc(), and qmt_pool_free().
void qmt_adjust_edquot (struct lquota_entry * , __u64)
Definition at line 410 of file qmt_entry.c.
References cfs_time_before_64(), cfs_time_shift_64(), ENTRY, EXIT, lqe2qpi(), lquota_entry::lqe_edquot, lquota_entry::lqe_enforced, lquota_entry::lqe_granted, lquota_entry::lqe_id, lquota_entry::lqe_qunit, LQUOTA_DEBUG, LQUOTA_RES_DT, lquota_id::qid_uid, qmt_hard_exhausted(), qmt_id_lock_notify(), QMT_REBA_TIMEOUT, qmt_space_exhausted(), qmt_pool_info::qpi_key, qmt_pool_info::qpi_least_qunit, qmt_pool_info::qpi_qmt, qmt_pool_info::qpi_soft_least_qunit, and RETURN_EXIT.
Referenced by qmt_dqacq0(), qmt_id_lock_glimpse(), qmt_revalidate(), and qmt_set().
void qmt_adjust_qunit (const struct lu_env * , struct lquota_entry *)
Definition at line 573 of file qmt_entry.c.
References __u64, cfs_time_current_64, done, ENTRY, EXIT, GOTO, LASSERT, LPU64, lqe2qpi(), lquota_entry::lqe_enforced, lquota_entry::lqe_granted, lquota_entry::lqe_id, lqe_is_locked(), lquota_entry::lqe_qunit, lquota_entry::lqe_site, lquota_site::lqs_qtype, LQUOTA_DEBUG, LQUOTA_ERROR, lquota_id::qid_uid, qmt_calc_softlimit(), qmt_id_lock_notify(), qmt_pool_info::qpi_least_qunit, qmt_pool_info::qpi_qmt, qmt_pool_info::qpi_slv_nr, qmt_pool_info::qpi_soft_least_qunit, RETURN_EXIT, and swap.
Referenced by qmt_dqacq0(), qmt_revalidate(), and qmt_set().
__u64 qmt_alloc_expand (struct lquota_entry * , __u64 , __u64)
Definition at line 514 of file qmt_entry.c.
References __u64, LASSERT, lqe2qpi(), lquota_entry::lqe_enforced, lquota_entry::lqe_granted, lquota_entry::lqe_qunit, lquota_entry::lqe_site, lquota_site::lqs_qtype, min_t, qmt_calc_softlimit(), qmt_pool_info::qpi_least_qunit, qmt_pool_info::qpi_slv_nr, qmt_pool_info::qpi_soft_least_qunit, and RETURN.
Referenced by qmt_dqacq0().
int qmt_dqacq0 (const struct lu_env * , struct lquota_entry * , struct qmt_device * , struct obd_uuid * , __u32 , __u64 , __u64 , struct quota_body *)
Definition at line 342 of file qmt_handler.c.
References __u64, cfs_fail_val, cfs_time_current_sec(), dt_object::do_lu, dt_trans_stop(), ENTRY, GOTO, LASSERT, LBUG, LPU64, lquota_entry::lqe_edquot, lquota_entry::lqe_enforced, LQE_GLB_OBJ, lquota_entry::lqe_granted, lquota_entry::lqe_id, lquota_entry::lqe_qunit, LQE_ROOT, lqe_write_lock(), lqe_write_unlock(), LQUOTA_BUMP_VER, LQUOTA_DEBUG, lquota_disk_slv_find(), LQUOTA_ERROR, lu_object_fid(), lu_object_put(), now(), OBD_FAIL_CHECK, OBD_FAIL_QUOTA_EDQUOT, OBD_FAIL_QUOTA_RECOVERABLE_ERR, obd_uuid2str(), out_write(), quota_body::qb_count, quota_body::qb_id, quota_body::qb_slv_ver, qmt_adjust_edquot(), qmt_adjust_qunit(), qmt_alloc_expand(), qmt_device::qmt_child, qmt_glb_write(), QMT_GRANT, qmt_info(), qmt_lqe_grace(), QMT_REL, qmt_restore(), qmt_revalidate(), qmt_slv_read(), qmt_slv_write(), qmt_space_exhausted(), qmt_trans_start_with_slv(), qmt_thread_info::qti_restore, req_has_rep, req_is_acq, req_is_preacq, req_is_rel, ret, and RETURN.
Referenced by qmt_dqacq(), qmt_intent_policy(), and qmt_lvbo_update().
void qmt_glb_lock_notify (const struct lu_env * , struct lquota_entry * , __u64)
Definition at line 539 of file qmt_lock.c.
References DFID, ENTRY, EXIT, fid_build_reg_res_name(), ldlm_gl_lquota_desc::gl_flags, ldlm_gl_lquota_desc::gl_hardlimit, ldlm_gl_lquota_desc::gl_id, ldlm_gl_lquota_desc::gl_softlimit, ldlm_gl_lquota_desc::gl_time, ldlm_gl_lquota_desc::gl_ver, LDLM_PLAIN, ldlm_resource_get(), ldlm_resource_putref(), lqe2qpi(), lquota_entry::lqe_id, lquota_entry::lqe_site, lquota_site::lqs_qtype, LQUOTA_DEBUG, ldlm_gl_desc::lquota_desc, lquota_generate_fid(), PFID, qmt_glimpse_lock(), qmt_info(), qmt_device::qmt_ns, qmt_pool_info::qpi_key, qmt_pool_info::qpi_qmt, qmt_thread_info::qti_fid, qmt_thread_info::qti_gl_desc, qmt_thread_info::qti_resid, and RETURN_EXIT.
Referenced by qmt_set().
int qmt_glb_write (const struct lu_env * , struct thandle * , struct lquota_entry * , __u32 , __u64 *)
Definition at line 244 of file qmt_entry.c.
References ENTRY, LASSERT, LQE_GLB_OBJ, lquota_entry::lqe_granted, lquota_entry::lqe_id, lqe_is_locked(), lqe_is_master(), lquota_entry::lqe_uptodate, LQUOTA_BUMP_VER, LQUOTA_DEBUG, lquota_disk_write(), LQUOTA_ERROR, LQUOTA_SET_VER, lquota_glb_rec::qbr_granted, lquota_glb_rec::qbr_hardlimit, lquota_glb_rec::qbr_softlimit, lquota_glb_rec::qbr_time, qmt_info(), and RETURN.
Referenced by qmt_dqacq0(), and qmt_set().
static bool qmt_hard_exhausted (struct lquota_entry * lqe) [inline, static]
Definition at line 268 of file qmt_internal.h.
References lquota_entry::lqe_granted.
Referenced by qmt_adjust_edquot(), and qmt_space_exhausted().
void qmt_id_lock_notify (struct qmt_device * , struct lquota_entry *)
Definition at line 680 of file qmt_lock.c.
References ENTRY, EXIT, list_add_tail(), list_empty(), lqe_getref(), lquota_entry::lqe_link, lqe_putref(), qmt_device::qmt_reba_list, qmt_device::qmt_reba_lock, qmt_device::qmt_reba_thread, qmt_device::qmt_stopping, and ptlrpc_thread::t_ctl_waitq.
Referenced by qmt_adjust_edquot(), and qmt_adjust_qunit().
static struct qmt_thread_info* qmt_info (const struct lu_env * env) [static, read]
Definition at line 206 of file qmt_internal.h.
References LASSERT, lu_env::le_ctx, lu_context_key_get(), lu_env_refill(), and qmt_thread_key.
Referenced by qmt_dqacq0(), qmt_glb_lock_notify(), qmt_glb_write(), qmt_id_lock_glimpse(), qmt_lqe_read(), qmt_lvbo_init(), qmt_lvbo_update(), qmt_pool_alloc(), qmt_pool_prepare(), qmt_quotactl(), qmt_set(), qmt_slv_read(), and qmt_slv_write().
int qmt_intent_policy (const struct lu_env * , struct lu_device * , struct ptlrpc_request * , struct ldlm_lock ** , int)
Definition at line 43 of file qmt_lock.c.
References CERROR, ENTRY, err_serious(), EXIT, GOTO, IT_QUOTA_CONN, IT_QUOTA_DQACQ, LASSERT, ldlm_handle2lock(), LDLM_LOCK_PUT, ldlm_lvbo_fill(), ldlm_lvbo_size(), LPU64, lqe_getref(), lqe_putref(), ldlm_resource::lr_lvb_data, ldlm_resource::lr_name, lu2qmt_dev(), lustre_handle_is_used(), LUSTRE_RES_ID_QUOTA_SEQ_OFF, ldlm_res_id::name, ldlm_intent::opc, quota_body::qb_count, quota_body::qb_fid, quota_body::qb_flags, quota_body::qb_glb_lockh, quota_body::qb_slv_ver, quota_body::qb_usage, qmt_dqacq0(), qmt_pool_new_conn(), qmt_device::qmt_svname, RCL_SERVER, req_capsule_client_get(), req_capsule_extend(), req_capsule_server_get(), req_capsule_server_pack(), req_capsule_set_size(), req_capsule_shrink(), RETURN, RMF_DLM_LVB, RMF_LDLM_INTENT, RMF_QUOTA_BODY, ptlrpc_request::rq_pill, RQF_LDLM_INTENT_QUOTA, and uuid.
static __u64 qmt_lqe_grace (struct lquota_entry * lqe) [inline, static]
Definition at line 235 of file qmt_internal.h.
References LASSERT, lqe2qpi(), lquota_entry::lqe_site, lquota_site::lqs_qtype, and qmt_pool_info::qpi_grace_lqe.
Referenced by qmt_dqacq0(), and qmt_set().
int qmt_lvbo_fill (struct lu_device * , struct ldlm_lock * , void * , int)
Definition at line 346 of file qmt_lock.c.
References dt_version_get(), ENTRY, FID_SEQ_QUOTA_GLB, ldlm_lock::l_resource, LASSERT, LCT_LOCAL, LDLM_PLAIN, lquota_entry::lqe_edquot, lqe_getref(), lqe_putref(), lquota_entry::lqe_qunit, LQUOTA_FL_EDQUOT, ldlm_resource::lr_lvb_data, ldlm_resource::lr_name, ldlm_resource::lr_type, lu_env_fini(), lu_env_init(), LUSTRE_RES_ID_QUOTA_SEQ_OFF, LUSTRE_RES_ID_SEQ_OFF, lquota_lvb::lvb_flags, lquota_lvb::lvb_id_qunit, ldlm_res_id::name, OBD_ALLOC_PTR, OBD_FREE_PTR, and RETURN.
int qmt_lvbo_free (struct lu_device * , struct ldlm_resource *)
Definition at line 403 of file qmt_lock.c.
References dt_object::do_lu, ENTRY, LCT_LOCAL, lqe_putref(), ldlm_resource::lr_lvb_data, ldlm_resource::lr_lvb_len, ldlm_resource::lr_name, lu_env_fini(), lu_env_init(), lu_object_put(), LUSTRE_RES_ID_QUOTA_SEQ_OFF, ldlm_res_id::name, OBD_ALLOC_PTR, OBD_FREE_PTR, and RETURN.
int qmt_lvbo_init (struct lu_device * , struct ldlm_resource *)
Definition at line 152 of file qmt_lock.c.
References CDEBUG, CERROR, D_QUOTA, DFID, dt_object::do_lu, dt_locate(), dt_object_exists(), ENTRY, EXIT, fid_extract_from_quota_res(), FID_SEQ_QUOTA_GLB, GOTO, LASSERT, LCT_MD_THREAD, LDLM_PLAIN, LQUOTA_DEBUG, lquota_extract_fid(), ldlm_resource::lr_lvb_data, ldlm_resource::lr_lvb_len, ldlm_resource::lr_name, ldlm_resource::lr_type, lu2qmt_dev(), lu_env_fini(), lu_env_init(), lu_object_put(), LUSTRE_RES_ID_QUOTA_SEQ_OFF, LUSTRE_RES_ID_SEQ_OFF, ldlm_res_id::name, OBD_ALLOC_PTR, OBD_FREE_PTR, PFID, qmt_device::qmt_child, qmt_info(), qmt_pool_lqe_lookup(), qmt_thread_info::qti_fid, qmt_thread_info::qti_id, and RETURN.
int qmt_lvbo_size (struct lu_device * , struct ldlm_lock *)
Definition at line 338 of file qmt_lock.c.
int qmt_lvbo_update (struct lu_device * , struct ldlm_resource * , struct ptlrpc_request * , int)
Definition at line 236 of file qmt_lock.c.
References CERROR, class_export_get(), class_export_put(), ENTRY, EXIT, obd_export::exp_client_uuid, GOTO, ldlm_lock::l_export, LASSERT, LCT_MD_THREAD, ldlm_request_lock(), LPU64, lqe_getref(), lqe_putref(), LQUOTA_DEBUG, LQUOTA_ERROR, ldlm_resource::lr_lvb_data, ldlm_resource::lr_name, lu2qmt_dev(), lu_env_fini(), lu_env_init(), LUSTRE_RES_ID_QUOTA_SEQ_OFF, lustre_swab_lquota_lvb(), lquota_lvb::lvb_id_may_rel, lquota_lvb::lvb_id_rel, ldlm_res_id::name, OBD_ALLOC_PTR, OBD_FREE_PTR, quota_body::qb_count, qmt_dqacq0(), qmt_info(), qmt_device::qmt_svname, qmt_thread_info::qti_body, QUOTA_DQACQ_FL_REL, req_capsule_server_swab_get(), RETURN, RMF_DLM_LVB, and ptlrpc_request::rq_pill.
void qmt_pool_fini (const struct lu_env * , struct qmt_device *)
Definition at line 393 of file qmt_pool.c.
References cfs_hash_del(), cfs_hash_putref(), ENTRY, EXIT, LASSERT, list_del_init(), list_empty(), list_entry, list_for_each_safe, qmt_device::qmt_pool_hash, qmt_device::qmt_pool_list, qmt_pool_info::qpi_hash, qmt_pool_info::qpi_key, qmt_pool_info::qpi_linkage, qpi_putref(), and RETURN_EXIT.
Referenced by qmt_device_fini(), and qmt_pool_init().
int qmt_pool_init (const struct lu_env * , struct qmt_device *)
Definition at line 434 of file qmt_pool.c.
References CERROR, cfs_hash_create(), CFS_HASH_DEFAULT, CFS_HASH_MAX_THETA, CFS_HASH_MIN_THETA, ENTRY, HASH_POOLS_BKT_BITS, HASH_POOLS_CUR_BITS, HASH_POOLS_MAX_BITS, INIT_LIST_HEAD, LQUOTA_FIRST_RES, LQUOTA_LAST_RES, qmt_pool_alloc(), qmt_pool_fini(), qmt_device::qmt_pool_hash, qmt_device::qmt_pool_list, qmt_device::qmt_svname, and RETURN.
Referenced by qmt_device_init0().
struct lquota_entry* qmt_pool_lqe_lookup (const struct lu_env * , struct qmt_device * , int , int , int , union lquota_id *) [read]
Definition at line 710 of file qmt_pool.c.
References ENTRY, GOTO, lqe_getref(), lqe_locate(), lquota_id::qid_uid, qmt_pool_lookup(), qpi_putref(), and RETURN.
Referenced by qmt_dqacq(), qmt_get(), qmt_lvbo_init(), and qmt_set().
int qmt_pool_new_conn (const struct lu_env * , struct qmt_device * , struct lu_fid * , struct lu_fid * , __u64 * , struct obd_uuid *)
Definition at line 648 of file qmt_pool.c.
References CERROR, dt_object::do_lu, dt_version_get(), GOTO, lquota_disk_slv_find(), lquota_disk_slv_find_create(), lquota_extract_fid(), lu_object_fid(), lu_object_put(), obd_uuid2str(), qmt_device::qmt_child, qmt_pool_lookup(), qmt_device::qmt_svname, qpi_putref(), qmt_pool_info::qpi_root, qmt_pool_info::qpi_slv_nr, and RETURN.
Referenced by qmt_intent_policy().
int qmt_pool_prepare (const struct lu_env * , struct qmt_device * , struct dt_object *)
Definition at line 494 of file qmt_pool.c.
References CERROR, CWARN, DFID, dt_version_get(), ENTRY, LASSERT, list_entry, list_for_each, lprocfs_quota_seq_fops, lqe_locate(), lquota_disk_dir_find_create(), lquota_disk_for_each_slv(), lquota_disk_glb_find_create(), lquota_disk_update_ver(), lquota_disk_write_glb(), lquota_generate_fid(), LQUOTA_RES_MD, lquota_site_alloc(), MAX_DQ_TIME, MAX_IQ_TIME, PFID, lquota_glb_rec::qbr_granted, lquota_glb_rec::qbr_hardlimit, lquota_glb_rec::qbr_softlimit, lquota_glb_rec::qbr_time, lquota_id::qid_uid, qmt_device::qmt_child, qmt_info(), qmt_lqe_ops, qmt_device::qmt_pool_hash, qmt_device::qmt_pool_list, qmt_slv_cnt(), qmt_device::qmt_svname, qmt_pool_info::qpi_glb_obj, qmt_pool_info::qpi_grace_lqe, qmt_pool_info::qpi_key, qmt_pool_info::qpi_proc, qmt_pool_info::qpi_qmt, qmt_pool_info::qpi_root, qmt_pool_info::qpi_site, qmt_pool_info::qpi_slv_nr, qmt_thread_info::qti_buf, qmt_thread_info::qti_fid, qmt_thread_info::qti_id, QTYPE_NAME, RES_NAME, RETURN, and version.
Referenced by qmt_device_prepare().
static void qmt_restore (struct lquota_entry * lqe, struct qmt_lqe_restore * restore) [inline, static]
Definition at line 246 of file qmt_internal.h.
References lquota_entry::lqe_granted, lquota_entry::lqe_qunit, qmt_lqe_restore::qlr_gracetime, qmt_lqe_restore::qlr_granted, qmt_lqe_restore::qlr_hardlimit, qmt_lqe_restore::qlr_qunit, and qmt_lqe_restore::qlr_softlimit.
Referenced by qmt_dqacq0(), and qmt_set().
void qmt_revalidate (const struct lu_env * , struct lquota_entry *)
Definition at line 686 of file qmt_entry.c.
References cfs_time_current_sec(), lquota_entry::lqe_qunit, qmt_adjust_edquot(), and qmt_adjust_qunit().
Referenced by qmt_dqacq0(), and qmt_set().
int qmt_slv_read (const struct lu_env * , struct lquota_entry * , struct dt_object * , __u64 *)
Definition at line 298 of file qmt_entry.c.
References DFID, dt_object::do_lu, ENTRY, LASSERT, LPU64, lquota_entry::lqe_id, lqe_is_locked(), lqe_is_master(), LQUOTA_DEBUG, lquota_disk_read(), LQUOTA_ERROR, lu_object_fid(), PFID, qmt_info(), and RETURN.
Referenced by qmt_dqacq0().
int qmt_slv_write (const struct lu_env * , struct thandle * , struct lquota_entry * , struct dt_object * , __u32 , __u64 * , __u64)
Definition at line 350 of file qmt_entry.c.
References DFID, dt_object::do_lu, ENTRY, LASSERT, LPU64, lquota_entry::lqe_id, lqe_is_locked(), lqe_is_master(), LQUOTA_DEBUG, lquota_disk_write(), LQUOTA_ERROR, lu_object_fid(), PFID, qmt_info(), lquota_slv_rec::qsr_granted, and RETURN.
Referenced by qmt_dqacq0().
static bool qmt_soft_exhausted (struct lquota_entry * lqe, __u64 now) [inline, static]
Definition at line 276 of file qmt_internal.h.
References lquota_entry::lqe_granted.
Referenced by qmt_space_exhausted().
static bool qmt_space_exhausted (struct lquota_entry * lqe, __u64 now) [inline, static]
Definition at line 288 of file qmt_internal.h.
References qmt_hard_exhausted(), and qmt_soft_exhausted().
Referenced by qmt_adjust_edquot(), and qmt_dqacq0().
int qmt_start_reba_thread (struct qmt_device *)
Definition at line 766 of file qmt_lock.c.
References CERROR, ENTRY, l_wait_event, qmt_reba_thread(), qmt_device::qmt_reba_thread, qmt_device::qmt_svname, RETURN, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, thread, thread_is_running(), thread_is_stopped(), and thread_set_flags().
Referenced by qmt_device_init0().
void qmt_stop_reba_thread (struct qmt_device *)
Definition at line 792 of file qmt_lock.c.
References l_wait_event, LASSERT, list_empty(), qmt_device::qmt_reba_list, qmt_device::qmt_reba_thread, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, thread, thread_is_stopped(), and thread_set_flags().
Referenced by qmt_device_fini().
struct thandle* qmt_trans_start (const struct lu_env * , struct lquota_entry * , struct qmt_lqe_restore *) [read]
Definition at line 220 of file qmt_entry.c.
References LQUOTA_DEBUG, and qmt_trans_start_with_slv().
Referenced by qmt_set().
struct thandle* qmt_trans_start_with_slv (const struct lu_env * , struct lquota_entry * , struct dt_object * , struct qmt_lqe_restore *) [read]
Definition at line 148 of file qmt_entry.c.
References DFID, dt_object::do_lu, dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), ENTRY, EXIT, GOTO, LASSERT, lqe2qpi(), LQE_GLB_OBJ, lquota_entry::lqe_granted, lquota_entry::lqe_id, lqe_is_master(), lquota_entry::lqe_qunit, LQUOTA_DEBUG, lquota_disk_declare_write(), LQUOTA_ERROR, lu_object_fid(), PFID, qmt_lqe_restore::qlr_gracetime, qmt_lqe_restore::qlr_granted, qmt_lqe_restore::qlr_hardlimit, qmt_lqe_restore::qlr_qunit, qmt_lqe_restore::qlr_softlimit, qmt_device::qmt_child, qmt_pool_info::qpi_qmt, RETURN, and thandle::th_sync.
Referenced by qmt_dqacq0(), and qmt_trans_start().
int qmt_validate_limits (struct lquota_entry * , __u64 , __u64)
Definition at line 393 of file qmt_entry.c.
References ENTRY, and RETURN.
Referenced by qmt_set().
Variable Documentation
struct lquota_entry_operations qmt_lqe_ops
Definition at line 131 of file qmt_entry.c.
Referenced by qmt_pool_prepare().
struct lu_context_key qmt_thread_key
Referenced by qmt_info().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.