Lustre: lustre/quota/qmt_handler.c File Reference
lustre/quota/qmt_handler.c File Reference
#include <obd_class.h>
#include "qmt_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LQUOTA
Functions
static int qmt_get (const struct lu_env *env, struct qmt_device *qmt, __u16 pool_id, __u8 restype, __u8 qtype, union lquota_id *id, __u64 *hard, __u64 *soft, __u64 *time)
static int qmt_set (const struct lu_env *env, struct qmt_device *qmt, __u16 pool_id, __u8 restype, __u8 qtype, union lquota_id *id, __u64 hard, __u64 soft, __u64 time, __u32 valid)
static int qmt_quotactl (const struct lu_env *env, struct lu_device *ld, struct obd_quotactl *oqctl)
int qmt_dqacq0 (const struct lu_env *env, struct lquota_entry *lqe, struct qmt_device *qmt, struct obd_uuid *uuid, __u32 qb_flags, __u64 qb_count, __u64 qb_usage, struct quota_body *repbody)
static int qmt_dqacq (const struct lu_env *env, struct lu_device *ld, struct ptlrpc_request *req)
Variables
struct qmt_handlers qmt_hdls
Define Documentation
#define DEBUG_SUBSYSTEM S_LQUOTA
Definition at line 31 of file qmt_handler.c.
Function Documentation
static int qmt_dqacq (const struct lu_env * env, struct lu_device * ld, struct ptlrpc_request * req) [static]
Definition at line 580 of file qmt_handler.c.
References at_est2timeout(), at_get(), CERROR, ENTRY, err_serious(), obd_export::exp_client_uuid, ldlm_lock::l_export, LDLM_DEBUG, ldlm_handle2lock(), ldlm_is_ast_sent, LDLM_LOCK_PUT, ldlm_refresh_waiting_lock(), lqe_putref(), lquota_entry::lqe_qunit, lquota_extract_fid(), lu2qmt_dev(), lustre_handle_is_used(), obd_uuid2str(), obd_uuid_equals(), quota_body::qb_count, quota_body::qb_fid, quota_body::qb_flags, quota_body::qb_glb_lockh, quota_body::qb_id, quota_body::qb_lockh, quota_body::qb_usage, qmt_dqacq0(), qmt_pool_lqe_lookup(), qmt_device::qmt_svname, req_capsule_client_get(), req_capsule_server_get(), req_is_acq, req_is_preacq, req_is_rel, RETURN, RMF_QUOTA_BODY, ptlrpc_request::rq_export, ptlrpc_request::rq_pill, ptlrpc_service_part::scp_at_estimate, timeout, and uuid.
int qmt_dqacq0 (const struct lu_env * env, struct lquota_entry * lqe, struct qmt_device * qmt, struct obd_uuid * uuid, __u32 qb_flags, __u64 qb_count, __u64 qb_usage, struct quota_body * repbody)
Definition at line 342 of file qmt_handler.c.
References __u64, cfs_fail_val, cfs_time_current_sec(), dt_object::do_lu, dt_trans_stop(), ENTRY, GOTO, LASSERT, LBUG, LPU64, lquota_entry::lqe_edquot, lquota_entry::lqe_enforced, LQE_GLB_OBJ, lquota_entry::lqe_granted, lquota_entry::lqe_id, lquota_entry::lqe_qunit, LQE_ROOT, lqe_write_lock(), lqe_write_unlock(), LQUOTA_BUMP_VER, LQUOTA_DEBUG, lquota_disk_slv_find(), LQUOTA_ERROR, lu_object_fid(), lu_object_put(), now(), OBD_FAIL_CHECK, OBD_FAIL_QUOTA_EDQUOT, OBD_FAIL_QUOTA_RECOVERABLE_ERR, obd_uuid2str(), out_write(), quota_body::qb_count, quota_body::qb_id, quota_body::qb_slv_ver, qmt_adjust_edquot(), qmt_adjust_qunit(), qmt_alloc_expand(), qmt_device::qmt_child, qmt_glb_write(), QMT_GRANT, qmt_info(), qmt_lqe_grace(), QMT_REL, qmt_restore(), qmt_revalidate(), qmt_slv_read(), qmt_slv_write(), qmt_space_exhausted(), qmt_trans_start_with_slv(), qmt_thread_info::qti_restore, req_has_rep, req_is_acq, req_is_preacq, req_is_rel, ret, and RETURN.
Referenced by qmt_dqacq(), qmt_intent_policy(), and qmt_lvbo_update().
static int qmt_get (const struct lu_env * env, struct qmt_device * qmt, __u16 pool_id, __u8 restype, __u8 qtype, union lquota_id * id, __u64 * hard, __u64 * soft, __u64 * time) [static]
Definition at line 51 of file qmt_handler.c.
References ENTRY, lqe_putref(), lqe_read_lock(), lqe_read_unlock(), LQUOTA_DEBUG, qmt_pool_lqe_lookup(), and RETURN.
Referenced by qmt_quotactl().
static int qmt_quotactl (const struct lu_env * env, struct lu_device * ld, struct obd_quotactl * oqctl) [static]
Definition at line 200 of file qmt_handler.c.
References CERROR, obd_dqblk::dqb_bhardlimit, obd_dqblk::dqb_bsoftlimit, obd_dqblk::dqb_btime, obd_dqblk::dqb_curinodes, obd_dqblk::dqb_curspace, obd_dqblk::dqb_ihardlimit, obd_dqblk::dqb_isoftlimit, obd_dqblk::dqb_itime, obd_dqblk::dqb_valid, obd_dqinfo::dqi_bgrace, obd_dqinfo::dqi_igrace, ENTRY, LASSERT, LQUOTA_RES_DT, LQUOTA_RES_MD, lu2qmt_dev(), obd_quotactl::qc_cmd, obd_quotactl::qc_dqblk, obd_quotactl::qc_dqinfo, obd_quotactl::qc_id, obd_quotactl::qc_type, QIF_BFLAGS, QIF_BLIMITS, QIF_BTIME, QIF_IFLAGS, QIF_ILIMITS, QIF_ITIME, QIF_LIMITS, QIF_TIMES, qmt_get(), qmt_info(), qmt_set(), qmt_device::qmt_svname, qmt_thread_info::qti_id, and RETURN.
static int qmt_set (const struct lu_env * env, struct qmt_device * qmt, __u16 pool_id, __u8 restype, __u8 qtype, union lquota_id * id, __u64 hard, __u64 soft, __u64 time, __u32 valid) [static]
Definition at line 94 of file qmt_handler.c.
References __u64, cfs_time_current_sec(), dt_trans_stop(), ENTRY, EXIT, GOTO, LPU64, lquota_entry::lqe_enforced, lquota_entry::lqe_granted, lqe_putref(), lqe_write_lock(), lqe_write_unlock(), LQUOTA_BUMP_VER, LQUOTA_DEBUG, now(), QIF_LIMITS, QIF_TIMES, qmt_adjust_edquot(), qmt_adjust_qunit(), qmt_device::qmt_child, qmt_glb_lock_notify(), qmt_glb_write(), qmt_info(), qmt_lqe_grace(), qmt_pool_lqe_lookup(), qmt_restore(), qmt_revalidate(), qmt_trans_start(), qmt_validate_limits(), qmt_thread_info::qti_restore, and RETURN.
Referenced by qmt_quotactl().
Variable Documentation
struct qmt_handlers qmt_hdls
Initial value:
 {
        .qmth_quotactl          = qmt_quotactl,
        .qmth_dqacq             = qmt_dqacq,
        .qmth_intent_policy     = qmt_intent_policy,
        .qmth_lvbo_init         = qmt_lvbo_init,
        .qmth_lvbo_update       = qmt_lvbo_update,
        .qmth_lvbo_size         = qmt_lvbo_size,
        .qmth_lvbo_fill         = qmt_lvbo_fill,
        .qmth_lvbo_free         = qmt_lvbo_free,
}
Definition at line 680 of file qmt_handler.c.
Referenced by mdt_intent_opc(), mdt_lvbo_fill(), mdt_lvbo_free(), mdt_lvbo_init(), mdt_lvbo_size(), mdt_lvbo_update(), mdt_quota_dqacq(), and mdt_quotactl().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.