Lustre: lustre/quota/qmt_lock.c File Reference
lustre/quota/qmt_lock.c File Reference
#include <linux/kthread.h>
#include <lustre_dlm.h>
#include <lustre_swab.h>
#include <obd_class.h>
#include "qmt_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LQUOTA
Typedefs
typedef int(* qmt_glimpse_cb_t)(const struct lu_env *, struct qmt_device *, struct obd_uuid *, union ldlm_gl_desc *, void *)
Functions
int qmt_intent_policy (const struct lu_env *env, struct lu_device *ld, struct ptlrpc_request *req, struct ldlm_lock **lockp, int flags)
int qmt_lvbo_init (struct lu_device *ld, struct ldlm_resource *res)
int qmt_lvbo_update (struct lu_device *ld, struct ldlm_resource *res, struct ptlrpc_request *req, int increase_only)
int qmt_lvbo_size (struct lu_device *ld, struct ldlm_lock *lock)
int qmt_lvbo_fill (struct lu_device *ld, struct ldlm_lock *lock, void *lvb, int lvblen)
int qmt_lvbo_free (struct lu_device *ld, struct ldlm_resource *res)
static int qmt_glimpse_lock (const struct lu_env *env, struct qmt_device *qmt, struct ldlm_resource *res, union ldlm_gl_desc *desc, qmt_glimpse_cb_t cb, void *arg)
void qmt_glb_lock_notify (const struct lu_env *env, struct lquota_entry *lqe, __u64 ver)
static int qmt_id_lock_cb (const struct lu_env *env, struct qmt_device *qmt, struct obd_uuid *uuid, union ldlm_gl_desc *desc, void *arg)
static void qmt_id_lock_glimpse (const struct lu_env *env, struct qmt_device *qmt, struct lquota_entry *lqe, struct obd_uuid *uuid)
void qmt_id_lock_notify (struct qmt_device *qmt, struct lquota_entry *lqe)
static int qmt_reba_thread (void *arg)
int qmt_start_reba_thread (struct qmt_device *qmt)
void qmt_stop_reba_thread (struct qmt_device *qmt)
Define Documentation
#define DEBUG_SUBSYSTEM S_LQUOTA
Definition at line 31 of file qmt_lock.c.
Typedef Documentation
typedef int(* qmt_glimpse_cb_t)(const struct lu_env *, struct qmt_device *, struct obd_uuid *, union ldlm_gl_desc *, void *)
Definition at line 443 of file qmt_lock.c.
Function Documentation
void qmt_glb_lock_notify (const struct lu_env * env, struct lquota_entry * lqe, __u64 ver)
Definition at line 539 of file qmt_lock.c.
References DFID, ENTRY, EXIT, fid_build_reg_res_name(), ldlm_gl_lquota_desc::gl_flags, ldlm_gl_lquota_desc::gl_hardlimit, ldlm_gl_lquota_desc::gl_id, ldlm_gl_lquota_desc::gl_softlimit, ldlm_gl_lquota_desc::gl_time, ldlm_gl_lquota_desc::gl_ver, LDLM_PLAIN, ldlm_resource_get(), ldlm_resource_putref(), lqe2qpi(), lquota_entry::lqe_id, lquota_entry::lqe_site, lquota_site::lqs_qtype, LQUOTA_DEBUG, ldlm_gl_desc::lquota_desc, lquota_generate_fid(), PFID, qmt_glimpse_lock(), qmt_info(), qmt_device::qmt_ns, qmt_pool_info::qpi_key, qmt_pool_info::qpi_qmt, qmt_thread_info::qti_fid, qmt_thread_info::qti_gl_desc, qmt_thread_info::qti_resid, and RETURN_EXIT.
Referenced by qmt_set().
static int qmt_glimpse_lock (const struct lu_env * env, struct qmt_device * qmt, struct ldlm_resource * res, union ldlm_gl_desc * desc, qmt_glimpse_cb_t cb, void * arg) [static]
Definition at line 459 of file qmt_lock.c.
References cb(), CDEBUG, CERROR, D_QUOTA, ENTRY, obd_export::exp_client_uuid, ldlm_glimpse_work::gl_desc, ldlm_glimpse_work::gl_flags, ldlm_glimpse_work::gl_list, ldlm_glimpse_work::gl_lock, ldlm_lock::l_export, LASSERT, LDLM_LOCK_GET, LDLM_LOCK_RELEASE, list_add_tail(), list_del(), list_empty(), list_entry, list_for_each, list_for_each_safe, LIST_HEAD_INIT, lock_res(), ldlm_resource::lr_granted, OBD_ALLOC_PTR, OBD_FREE_PTR, obd_uuid2str(), qmt_device::qmt_svname, RETURN, unlock_res(), and uuid.
Referenced by qmt_glb_lock_notify(), and qmt_id_lock_glimpse().
static int qmt_id_lock_cb (const struct lu_env * env, struct qmt_device * qmt, struct obd_uuid * uuid, union ldlm_gl_desc * desc, void * arg) [static]
Definition at line 579 of file qmt_lock.c.
References obd_uuid_equals(), and RETURN.
Referenced by qmt_id_lock_glimpse().
static void qmt_id_lock_glimpse (const struct lu_env * env, struct qmt_device * qmt, struct lquota_entry * lqe, struct obd_uuid * uuid) [static]
Definition at line 598 of file qmt_lock.c.
References cfs_time_current_64, cfs_time_current_sec(), DFID, ENTRY, EXIT, fid_build_quota_res_name(), ldlm_gl_lquota_desc::gl_flags, LASSERT, LDLM_PLAIN, ldlm_resource_get(), ldlm_resource_putref(), lqe2qpi(), lquota_entry::lqe_edquot, lquota_entry::lqe_enforced, lquota_entry::lqe_gl, lquota_entry::lqe_id, lquota_entry::lqe_qunit, lquota_entry::lqe_site, lqe_write_lock(), lqe_write_unlock(), lquota_site::lqs_qtype, LQUOTA_DEBUG, ldlm_gl_desc::lquota_desc, LQUOTA_FL_EDQUOT, lquota_generate_fid(), PFID, qmt_adjust_edquot(), qmt_glimpse_lock(), qmt_id_lock_cb(), qmt_info(), qmt_device::qmt_ns, qmt_pool_info::qpi_key, qmt_pool_info::qpi_least_qunit, qmt_thread_info::qti_fid, qmt_thread_info::qti_gl_desc, qmt_thread_info::qti_resid, and RETURN_EXIT.
Referenced by qmt_reba_thread().
void qmt_id_lock_notify (struct qmt_device * qmt, struct lquota_entry * lqe)
Definition at line 680 of file qmt_lock.c.
References ENTRY, EXIT, list_add_tail(), list_empty(), lqe_getref(), lquota_entry::lqe_link, lqe_putref(), qmt_device::qmt_reba_list, qmt_device::qmt_reba_lock, qmt_device::qmt_reba_thread, qmt_device::qmt_stopping, and ptlrpc_thread::t_ctl_waitq.
Referenced by qmt_adjust_edquot(), and qmt_adjust_qunit().
int qmt_intent_policy (const struct lu_env * env, struct lu_device * ld, struct ptlrpc_request * req, struct ldlm_lock ** lockp, int flags)
Definition at line 43 of file qmt_lock.c.
References CERROR, ENTRY, err_serious(), EXIT, GOTO, IT_QUOTA_CONN, IT_QUOTA_DQACQ, LASSERT, ldlm_handle2lock(), LDLM_LOCK_PUT, ldlm_lvbo_fill(), ldlm_lvbo_size(), LPU64, lqe_getref(), lqe_putref(), ldlm_resource::lr_lvb_data, ldlm_resource::lr_name, lu2qmt_dev(), lustre_handle_is_used(), LUSTRE_RES_ID_QUOTA_SEQ_OFF, ldlm_res_id::name, ldlm_intent::opc, quota_body::qb_count, quota_body::qb_fid, quota_body::qb_flags, quota_body::qb_glb_lockh, quota_body::qb_slv_ver, quota_body::qb_usage, qmt_dqacq0(), qmt_pool_new_conn(), qmt_device::qmt_svname, RCL_SERVER, req_capsule_client_get(), req_capsule_extend(), req_capsule_server_get(), req_capsule_server_pack(), req_capsule_set_size(), req_capsule_shrink(), RETURN, RMF_DLM_LVB, RMF_LDLM_INTENT, RMF_QUOTA_BODY, ptlrpc_request::rq_pill, RQF_LDLM_INTENT_QUOTA, and uuid.
int qmt_lvbo_fill (struct lu_device * ld, struct ldlm_lock * lock, void * lvb, int lvblen)
Definition at line 346 of file qmt_lock.c.
References dt_version_get(), ENTRY, FID_SEQ_QUOTA_GLB, ldlm_lock::l_resource, LASSERT, LCT_LOCAL, LDLM_PLAIN, lquota_entry::lqe_edquot, lqe_getref(), lqe_putref(), lquota_entry::lqe_qunit, LQUOTA_FL_EDQUOT, ldlm_resource::lr_lvb_data, ldlm_resource::lr_name, ldlm_resource::lr_type, lu_env_fini(), lu_env_init(), LUSTRE_RES_ID_QUOTA_SEQ_OFF, LUSTRE_RES_ID_SEQ_OFF, lquota_lvb::lvb_flags, lquota_lvb::lvb_id_qunit, ldlm_res_id::name, OBD_ALLOC_PTR, OBD_FREE_PTR, and RETURN.
int qmt_lvbo_free (struct lu_device * ld, struct ldlm_resource * res)
Definition at line 403 of file qmt_lock.c.
References dt_object::do_lu, ENTRY, LCT_LOCAL, lqe_putref(), ldlm_resource::lr_lvb_data, ldlm_resource::lr_lvb_len, ldlm_resource::lr_name, lu_env_fini(), lu_env_init(), lu_object_put(), LUSTRE_RES_ID_QUOTA_SEQ_OFF, ldlm_res_id::name, OBD_ALLOC_PTR, OBD_FREE_PTR, and RETURN.
int qmt_lvbo_init (struct lu_device * ld, struct ldlm_resource * res)
Definition at line 152 of file qmt_lock.c.
References CDEBUG, CERROR, D_QUOTA, DFID, dt_object::do_lu, dt_locate(), dt_object_exists(), ENTRY, EXIT, fid_extract_from_quota_res(), FID_SEQ_QUOTA_GLB, GOTO, LASSERT, LCT_MD_THREAD, LDLM_PLAIN, LQUOTA_DEBUG, lquota_extract_fid(), ldlm_resource::lr_lvb_data, ldlm_resource::lr_lvb_len, ldlm_resource::lr_name, ldlm_resource::lr_type, lu2qmt_dev(), lu_env_fini(), lu_env_init(), lu_object_put(), LUSTRE_RES_ID_QUOTA_SEQ_OFF, LUSTRE_RES_ID_SEQ_OFF, ldlm_res_id::name, OBD_ALLOC_PTR, OBD_FREE_PTR, PFID, qmt_device::qmt_child, qmt_info(), qmt_pool_lqe_lookup(), qmt_thread_info::qti_fid, qmt_thread_info::qti_id, and RETURN.
int qmt_lvbo_size (struct lu_device * ld, struct ldlm_lock * lock)
Definition at line 338 of file qmt_lock.c.
int qmt_lvbo_update (struct lu_device * ld, struct ldlm_resource * res, struct ptlrpc_request * req, int increase_only)
Definition at line 236 of file qmt_lock.c.
References CERROR, class_export_get(), class_export_put(), ENTRY, EXIT, obd_export::exp_client_uuid, GOTO, ldlm_lock::l_export, LASSERT, LCT_MD_THREAD, ldlm_request_lock(), LPU64, lqe_getref(), lqe_putref(), LQUOTA_DEBUG, LQUOTA_ERROR, ldlm_resource::lr_lvb_data, ldlm_resource::lr_name, lu2qmt_dev(), lu_env_fini(), lu_env_init(), LUSTRE_RES_ID_QUOTA_SEQ_OFF, lustre_swab_lquota_lvb(), lquota_lvb::lvb_id_may_rel, lquota_lvb::lvb_id_rel, ldlm_res_id::name, OBD_ALLOC_PTR, OBD_FREE_PTR, quota_body::qb_count, qmt_dqacq0(), qmt_info(), qmt_device::qmt_svname, qmt_thread_info::qti_body, QUOTA_DQACQ_FL_REL, req_capsule_server_swab_get(), RETURN, RMF_DLM_LVB, and ptlrpc_request::rq_pill.
static int qmt_reba_thread (void * arg) [static]
Definition at line 710 of file qmt_lock.c.
References CERROR, ENTRY, l_wait_event, LCT_MD_THREAD, list_del_init(), list_empty(), list_for_each_entry_safe, lquota_entry::lqe_link, lqe_putref(), lu_env_fini(), lu_env_init(), OBD_ALLOC_PTR, OBD_FREE_PTR, qmt_id_lock_glimpse(), qmt_device::qmt_reba_list, qmt_device::qmt_reba_lock, qmt_device::qmt_reba_thread, qmt_device::qmt_svname, RETURN, SVC_RUNNING, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, thread, thread_is_running(), and thread_set_flags().
Referenced by qmt_start_reba_thread().
int qmt_start_reba_thread (struct qmt_device * qmt)
Definition at line 766 of file qmt_lock.c.
References CERROR, ENTRY, l_wait_event, qmt_reba_thread(), qmt_device::qmt_reba_thread, qmt_device::qmt_svname, RETURN, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, thread, thread_is_running(), thread_is_stopped(), and thread_set_flags().
Referenced by qmt_device_init0().
void qmt_stop_reba_thread (struct qmt_device * qmt)
Definition at line 792 of file qmt_lock.c.
References l_wait_event, LASSERT, list_empty(), qmt_device::qmt_reba_list, qmt_device::qmt_reba_thread, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, thread, thread_is_stopped(), and thread_set_flags().
Referenced by qmt_device_fini().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.