Lustre: lustre/quota/qsd_writeback.c File Reference
lustre/quota/qsd_writeback.c File Reference
#include <linux/kthread.h>
#include "qsd_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LQUOTA
Functions
static struct qsd_upd_rec * qsd_upd_alloc (struct qsd_qtype_info *qqi, struct lquota_entry *lqe, union lquota_id *qid, union lquota_rec *rec, __u64 ver, bool global)
static void qsd_upd_free (struct qsd_upd_rec *upd)
static void qsd_upd_add (struct qsd_instance *qsd, struct qsd_upd_rec *upd)
static void qsd_add_deferred (struct qsd_instance *qsd, struct list_head *list, struct qsd_upd_rec *upd)
static void qsd_kickoff_deferred (struct qsd_qtype_info *qqi, struct list_head *list, __u64 ver)
void qsd_bump_version (struct qsd_qtype_info *qqi, __u64 ver, bool global)
void qsd_upd_schedule (struct qsd_qtype_info *qqi, struct lquota_entry *lqe, union lquota_id *qid, union lquota_rec *rec, __u64 ver, bool global)
static int qsd_process_upd (const struct lu_env *env, struct qsd_upd_rec *upd)
void qsd_adjust_schedule (struct lquota_entry *lqe, bool defer, bool cancel)
static bool qsd_job_pending (struct qsd_instance *qsd, struct list_head *upd, bool *uptodate)
static int qsd_upd_thread (void *arg)
int qsd_start_upd_thread (struct qsd_instance *qsd)
static void qsd_cleanup_deferred (struct qsd_instance *qsd)
static void qsd_cleanup_adjust (struct qsd_instance *qsd)
void qsd_stop_upd_thread (struct qsd_instance *qsd)
Variables
struct kmem_cache * upd_kmem
Define Documentation
#define DEBUG_SUBSYSTEM S_LQUOTA
Definition at line 31 of file qsd_writeback.c.
Function Documentation
static void qsd_add_deferred (struct qsd_instance * qsd, struct list_head * list, struct qsd_upd_rec * upd) [static]
Definition at line 100 of file qsd_writeback.c.
References CWARN, LASSERT, list_add(), list_add_tail(), list_del_init(), LPU64, LQUOTA_ERROR, LQUOTA_WARN, qsd_instance::qsd_stopping, qsd_instance::qsd_svname, qsd_upd_free(), qsd_upd_rec::qur_link, qsd_upd_rec::qur_lqe, and qsd_upd_rec::qur_ver.
Referenced by qsd_upd_schedule().
void qsd_adjust_schedule (struct lquota_entry * lqe, bool defer, bool cancel)
Definition at line 312 of file qsd_writeback.c.
References cfs_time_current_64, cfs_time_shift_64(), list_add(), list_add_tail(), list_del_init(), list_empty(), lqe2qqi(), lqe_getref(), lquota_entry::lqe_link, lqe_putref(), qsd_qtype_info::qqi_qsd, qsd_instance::qsd_adjust_list, qsd_instance::qsd_adjust_lock, qsd_instance::qsd_lock, qsd_instance::qsd_stopping, qsd_instance::qsd_upd_thread, QSD_WB_INTERVAL, and ptlrpc_thread::t_ctl_waitq.
Referenced by qsd_adjust(), qsd_op_end0(), and qsd_req_completion().
void qsd_bump_version (struct qsd_qtype_info * qqi, __u64 ver, bool global)
Definition at line 189 of file qsd_writeback.c.
References __u64, list, qsd_qtype_info::qqi_deferred_glb, qsd_qtype_info::qqi_deferred_slv, qsd_qtype_info::qqi_glb_uptodate, qsd_qtype_info::qqi_glb_ver, qsd_qtype_info::qqi_qsd, qsd_qtype_info::qqi_slv_uptodate, qsd_qtype_info::qqi_slv_ver, qsd_kickoff_deferred(), and qsd_instance::qsd_lock.
Referenced by qsd_reint_main(), qsd_update_index(), and qsd_write_version().
static void qsd_cleanup_adjust (struct qsd_instance * qsd) [static]
Definition at line 549 of file qsd_writeback.c.
References list_del_init(), list_empty(), list_entry, lquota_entry::lqe_link, lqe_putref(), list_head::next, qsd_instance::qsd_adjust_list, and qsd_instance::qsd_adjust_lock.
Referenced by qsd_stop_upd_thread().
static void qsd_cleanup_deferred (struct qsd_instance * qsd) [static]
Definition at line 515 of file qsd_writeback.c.
References CWARN, list_del_init(), list_for_each_entry_safe, LPU64, lquota_id::qid_uid, qsd_qtype_info::qqi_deferred_glb, qsd_qtype_info::qqi_deferred_slv, qsd_qtype_info::qqi_glb_ver, qsd_qtype_info::qqi_slv_ver, qsd_instance::qsd_lock, qsd_instance::qsd_svname, qsd_instance::qsd_type_array, qsd_upd_free(), qsd_upd_rec::qur_link, qsd_upd_rec::qur_qid, and qsd_upd_rec::qur_ver.
Referenced by qsd_stop_upd_thread().
static bool qsd_job_pending (struct qsd_instance * qsd, struct list_head * upd, bool * uptodate) [static]
Definition at line 360 of file qsd_writeback.c.
References cfs_time_beforeq_64(), cfs_time_current_64, LASSERT, list_empty(), list_entry, list_splice_init(), lquota_entry::lqe_link, list_head::next, qsd_qtype_info::qqi_glb_uptodate, qsd_qtype_info::qqi_reint, qsd_qtype_info::qqi_slv_uptodate, qsd_instance::qsd_acct_failed, qsd_instance::qsd_adjust_list, qsd_instance::qsd_adjust_lock, qsd_instance::qsd_lock, qsd_instance::qsd_type_array, qsd_type_enabled(), and qsd_instance::qsd_upd_list.
Referenced by qsd_upd_thread().
static void qsd_kickoff_deferred (struct qsd_qtype_info * qqi, struct list_head * list, __u64 ver) [static]
Definition at line 140 of file qsd_writeback.c.
References CDEBUG, D_QUOTA, ENTRY, EXIT, LASSERTF, list_del_init(), list_empty(), list_for_each_entry_safe, LPU64, lquota_id::qid_uid, qsd_qtype_info::qqi_qsd, qsd_instance::qsd_svname, qsd_upd_add(), qsd_upd_free(), qsd_upd_rec::qur_global, qsd_upd_rec::qur_link, qsd_upd_rec::qur_qid, qsd_upd_rec::qur_ver, and RETURN_EXIT.
Referenced by qsd_bump_version().
static int qsd_process_upd (const struct lu_env * env, struct qsd_upd_rec * upd) [static]
Definition at line 275 of file qsd_writeback.c.
References ENTRY, GOTO, lqe_locate(), lqe_putref(), LQUOTA_ERROR, qsd_qtype_info::qqi_site, qsd_adjust(), qsd_refresh_usage(), qsd_update_index(), qsd_update_lqe(), qsd_upd_rec::qur_global, qsd_upd_rec::qur_lqe, qsd_upd_rec::qur_qid, qsd_upd_rec::qur_qqi, qsd_upd_rec::qur_rec, qsd_upd_rec::qur_ver, and RETURN.
Referenced by qsd_upd_thread().
int qsd_start_upd_thread (struct qsd_instance * qsd)
Definition at line 493 of file qsd_writeback.c.
References CERROR, ENTRY, l_wait_event, qsd_instance::qsd_svname, qsd_upd_thread(), qsd_instance::qsd_upd_thread, RETURN, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, thread, thread_is_running(), thread_is_stopped(), and thread_set_flags().
Referenced by qsd_prepare().
void qsd_stop_upd_thread (struct qsd_instance * qsd)
Definition at line 563 of file qsd_writeback.c.
References l_wait_event, qsd_cleanup_adjust(), qsd_cleanup_deferred(), qsd_instance::qsd_upd_thread, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, thread, thread_is_stopped(), and thread_set_flags().
Referenced by qsd_fini().
static void qsd_upd_add (struct qsd_instance * qsd, struct qsd_upd_rec * upd) [static]
Definition at line 85 of file qsd_writeback.c.
References CWARN, list_add_tail(), LQUOTA_WARN, qsd_instance::qsd_stopping, qsd_instance::qsd_svname, qsd_upd_free(), qsd_instance::qsd_upd_list, qsd_instance::qsd_upd_thread, qsd_upd_rec::qur_link, qsd_upd_rec::qur_lqe, and ptlrpc_thread::t_ctl_waitq.
Referenced by qsd_kickoff_deferred(), and qsd_upd_schedule().
static struct qsd_upd_rec* qsd_upd_alloc (struct qsd_qtype_info * qqi, struct lquota_entry * lqe, union lquota_id * qid, union lquota_rec * rec, __u64 ver, bool global) [static, read]
Definition at line 50 of file qsd_writeback.c.
References INIT_LIST_HEAD, lqe_getref(), OBD_SLAB_ALLOC_PTR_GFP, qsd_upd_rec::qur_global, qsd_upd_rec::qur_link, qsd_upd_rec::qur_lqe, qsd_upd_rec::qur_qid, qsd_upd_rec::qur_qqi, qsd_upd_rec::qur_rec, qsd_upd_rec::qur_ver, and upd_kmem.
Referenced by qsd_upd_schedule().
static void qsd_upd_free (struct qsd_upd_rec * upd) [static]
Definition at line 77 of file qsd_writeback.c.
References lqe_putref(), OBD_SLAB_FREE_PTR, qsd_upd_rec::qur_lqe, and upd_kmem.
Referenced by qsd_add_deferred(), qsd_cleanup_deferred(), qsd_kickoff_deferred(), qsd_upd_add(), qsd_upd_schedule(), and qsd_upd_thread().
void qsd_upd_schedule (struct qsd_qtype_info * qqi, struct lquota_entry * lqe, union lquota_id * qid, union lquota_rec * rec, __u64 ver, bool global)
Definition at line 217 of file qsd_writeback.c.
References __u64, CDEBUG, CERROR, D_QUOTA, ENTRY, EXIT, list, LPU64, qsd_qtype_info::qqi_deferred_glb, qsd_qtype_info::qqi_deferred_slv, qsd_qtype_info::qqi_glb_uptodate, qsd_qtype_info::qqi_glb_ver, qsd_qtype_info::qqi_qsd, qsd_qtype_info::qqi_slv_uptodate, qsd_qtype_info::qqi_slv_ver, qsd_add_deferred(), qsd_instance::qsd_lock, qsd_instance::qsd_svname, qsd_upd_add(), qsd_upd_alloc(), qsd_upd_free(), and RETURN_EXIT.
Referenced by qsd_glb_glimpse_ast(), qsd_id_glimpse_ast(), and qsd_req_completion().
static int qsd_upd_thread (void * arg) [static]
Definition at line 410 of file qsd_writeback.c.
References __u64, CERROR, cfs_time_beforeq_64(), cfs_time_current_64, cfs_time_seconds(), ENTRY, INIT_LIST_HEAD, l_wait_event, LCT_DT_THREAD, list_del_init(), list_empty(), list_entry, list_for_each_entry_safe, lquota_entry::lqe_link, lqe_putref(), lu_env_fini(), lu_env_init(), LWI_TIMEOUT, list_head::next, OBD_ALLOC_PTR, OBD_FREE_PTR, qsd_adjust(), qsd_instance::qsd_adjust_list, qsd_instance::qsd_adjust_lock, qsd_id_lock_cancel(), qsd_job_pending(), qsd_process_upd(), qsd_refresh_usage(), qsd_start_reint_thread(), qsd_instance::qsd_svname, qsd_instance::qsd_type_array, qsd_upd_free(), qsd_instance::qsd_upd_thread, QSD_WB_INTERVAL, qsd_upd_rec::qur_link, RETURN, SVC_RUNNING, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, thread, thread_is_running(), and thread_set_flags().
Referenced by qsd_start_upd_thread().
Variable Documentation
struct kmem_cache* upd_kmem
Definition at line 57 of file qsd_lib.c.
Referenced by qsd_upd_alloc(), and qsd_upd_free().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.