Lustre: lustre/quota/qsd_internal.h File Reference
lustre/quota/qsd_internal.h File Reference
#include "lquota_internal.h"
Data Structures
struct qsd_instance
struct qsd_qtype_info
struct qsd_fsinfo
struct qsd_upd_rec
struct qsd_thread_info
Defines
#define QSD_RES_TYPE(qsd) ((qsd)->qsd_is_md ? LQUOTA_RES_MD : LQUOTA_RES_DT)
#define QSD_WB_INTERVAL 60
Typedefs
typedef void(* qsd_req_completion_t)(const struct lu_env *, struct qsd_qtype_info *, struct quota_body *, struct quota_body *, struct lustre_handle *, struct lquota_lvb *, void *, int)
Functions
static struct qsd_qtype_info * lqe2qqi (struct lquota_entry *lqe)
static void qqi_getref (struct qsd_qtype_info *qqi)
static void qqi_putref (struct qsd_qtype_info *qqi)
static struct qsd_thread_info * qsd_info (const struct lu_env *env)
static int qsd_type_enabled (struct qsd_instance *qsd, int type)
static void qsd_set_qunit (struct lquota_entry *lqe, __u64 qunit)
static void qsd_set_edquot (struct lquota_entry *lqe, bool edquot)
static int qsd_wait_timeout (struct qsd_instance *qsd)
int qsd_refresh_usage (const struct lu_env *, struct lquota_entry *)
int qsd_update_index (const struct lu_env *, struct qsd_qtype_info *, union lquota_id *, bool, __u64, void *)
int qsd_update_lqe (const struct lu_env *, struct lquota_entry *, bool, void *)
int qsd_write_version (const struct lu_env *, struct qsd_qtype_info *, __u64, bool)
int qsd_id_lock_match (struct lustre_handle *, struct lustre_handle *)
Check whether a slave already own a ldlm lock for the quota identifier .
int qsd_id_lock_cancel (const struct lu_env *, struct lquota_entry *)
int qsd_start_reint_thread (struct qsd_qtype_info *)
void qsd_stop_reint_thread (struct qsd_qtype_info *)
int qsd_send_dqacq (const struct lu_env *, struct obd_export *, struct quota_body *, bool, qsd_req_completion_t, struct qsd_qtype_info *, struct lustre_handle *, struct lquota_entry *)
int qsd_intent_lock (const struct lu_env *, struct obd_export *, struct quota_body *, bool, int, qsd_req_completion_t, struct qsd_qtype_info *, struct lquota_lvb *, void *)
int qsd_fetch_index (const struct lu_env *, struct obd_export *, struct idx_info *, unsigned int, struct page **, bool *)
void qsd_bump_version (struct qsd_qtype_info *, __u64, bool)
void qsd_upd_schedule (struct qsd_qtype_info *, struct lquota_entry *, union lquota_id *, union lquota_rec *, __u64, bool)
struct qsd_fsinfo * qsd_get_fsinfo (char *, bool)
void qsd_put_fsinfo (struct qsd_fsinfo *)
int qsd_process_config (struct lustre_cfg *)
int qsd_adjust (const struct lu_env *, struct lquota_entry *)
Adjust quota space (by acquiring or releasing) hold by the quota slave.
int qsd_start_upd_thread (struct qsd_instance *)
void qsd_stop_upd_thread (struct qsd_instance *)
void qsd_adjust_schedule (struct lquota_entry *, bool, bool)
Variables
struct lu_context_key qsd_thread_key
struct lquota_entry_operations qsd_lqe_ops
struct ldlm_enqueue_info qsd_glb_einfo
struct ldlm_enqueue_info qsd_id_einfo
Define Documentation
#define QSD_RES_TYPE (qsd) ((qsd)->qsd_is_md ? LQUOTA_RES_MD : LQUOTA_RES_DT)
Definition at line 227 of file qsd_internal.h.
Referenced by qsd_qtype_init().
#define QSD_WB_INTERVAL 60
Definition at line 328 of file qsd_internal.h.
Referenced by qsd_adjust_schedule(), and qsd_upd_thread().
Typedef Documentation
typedef void(* qsd_req_completion_t)(const struct lu_env *, struct qsd_qtype_info *, struct quota_body *, struct quota_body *, struct lustre_handle *, struct lquota_lvb *, void *, int)
Definition at line 360 of file qsd_internal.h.
Function Documentation
static struct qsd_qtype_info* lqe2qqi (struct lquota_entry * lqe) [static, read]
Definition at line 209 of file qsd_internal.h.
References LASSERT, lqe_is_master(), lquota_entry::lqe_site, and lquota_site::lqs_parent.
Referenced by qsd_acquire(), qsd_acquire_remote(), qsd_adjust(), qsd_adjust_schedule(), qsd_id_glimpse_ast(), qsd_pending_updates(), qsd_ready(), and qsd_refresh_usage().
static void qqi_getref (struct qsd_qtype_info * qqi) [inline, static]
Definition at line 216 of file qsd_internal.h.
References qsd_qtype_info::qqi_ref.
Referenced by qsd_glb_ast_data_get(), qsd_intent_lock(), and qsd_reint_main().
static void qqi_putref (struct qsd_qtype_info * qqi) [inline, static]
Definition at line 221 of file qsd_internal.h.
References LASSERT, and qsd_qtype_info::qqi_ref.
Referenced by qsd_glb_ast_data_get(), qsd_glb_blocking_ast(), qsd_glb_glimpse_ast(), and qsd_reint_main().
int qsd_adjust (const struct lu_env * env, struct lquota_entry * lqe)
Adjust quota space (by acquiring or releasing) hold by the quota slave.
This function is called after each quota request completion and during reintegration in order to report usage or re-acquire quota locks. Space adjustment is aborted if there is already a quota request in flight for this ID.
Parameters:
env - the environment passed by the caller
lqe - is the qid entry to be processed
Return values:
0 on success, appropriate errors on failure
Definition at line 902 of file qsd_handler.c.
References ENTRY, GOTO, IT_QUOTA_DQACQ, lqe2qqi(), lqe_getref(), lquota_entry::lqe_id, lqe_write_lock(), lqe_write_unlock(), LQUOTA_DEBUG, lustre_handle_copy(), OBD_ALLOC_PTR, quota_body::qb_count, quota_body::qb_fid, quota_body::qb_flags, quota_body::qb_glb_lockh, quota_body::qb_id, quota_body::qb_lockh, qsd_qtype_info::qqi_fid, qsd_qtype_info::qqi_qsd, qsd_adjust_schedule(), qsd_calc_adjust(), qsd_instance::qsd_exp, qsd_id_lock_match(), qsd_info(), qsd_intent_lock(), qsd_ready(), qsd_req_completion(), qsd_request_enter(), qsd_send_dqacq(), qsd_thread_info::qti_body, qsd_thread_info::qti_lockh, QUOTA_DQACQ_FL_REPORT, req_has_rep, req_is_acq, req_is_preacq, req_is_rel, and RETURN.
Referenced by qsd_id_blocking_ast(), qsd_op_adjust(), qsd_op_end0(), qsd_process_upd(), qsd_reconciliation(), and qsd_upd_thread().
void qsd_adjust_schedule (struct lquota_entry * , bool , bool)
Definition at line 312 of file qsd_writeback.c.
References cfs_time_current_64, cfs_time_shift_64(), list_add(), list_add_tail(), list_del_init(), list_empty(), lqe2qqi(), lqe_getref(), lquota_entry::lqe_link, lqe_putref(), qsd_qtype_info::qqi_qsd, qsd_instance::qsd_adjust_list, qsd_instance::qsd_adjust_lock, qsd_instance::qsd_lock, qsd_instance::qsd_stopping, qsd_instance::qsd_upd_thread, QSD_WB_INTERVAL, and ptlrpc_thread::t_ctl_waitq.
Referenced by qsd_adjust(), qsd_op_end0(), and qsd_req_completion().
void qsd_bump_version (struct qsd_qtype_info * , __u64 , bool)
Definition at line 189 of file qsd_writeback.c.
References __u64, list, qsd_qtype_info::qqi_deferred_glb, qsd_qtype_info::qqi_deferred_slv, qsd_qtype_info::qqi_glb_uptodate, qsd_qtype_info::qqi_glb_ver, qsd_qtype_info::qqi_qsd, qsd_qtype_info::qqi_slv_uptodate, qsd_qtype_info::qqi_slv_ver, qsd_kickoff_deferred(), and qsd_instance::qsd_lock.
Referenced by qsd_reint_main(), qsd_update_index(), and qsd_write_version().
int qsd_fetch_index (const struct lu_env * , struct obd_export * , struct idx_info * , unsigned int, struct page ** , bool *)
Definition at line 351 of file qsd_request.c.
References ptlrpc_bulk_frag_ops::add_kiov_frag, ptlrpc_bulk_desc::bd_frag_ops, class_exp2cliimp(), ENTRY, EXIT, GOTO, LASSERT, LUSTRE_OBD_VERSION, MDS_BULK_PORTAL, MDS_READPAGE_PORTAL, OBD_IDX_READ, ptlrpc_at_set_req_timeout(), PTLRPC_BULK_BUF_KIOV, ptlrpc_bulk_kiov_pin_ops, PTLRPC_BULK_PUT_SINK, ptlrpc_prep_bulk_imp(), ptlrpc_queue_wait(), ptlrpc_rep_need_swab(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_IDX_INFO, ptlrpc_request::rq_pill, RQF_OBD_IDX_READ, and sptlrpc_cli_unwrap_bulk_read().
Referenced by qsd_reint_index().
struct qsd_fsinfo* qsd_get_fsinfo (char * , bool) [read]
Definition at line 74 of file qsd_config.c.
References ENTRY, INIT_LIST_HEAD, list_add_tail(), list_for_each_entry, MTI_NAME_MAXLEN, OBD_ALLOC_PTR, OBD_FREE_PTR, qsd_fsinfo::qfs_link, qsd_fsinfo::qfs_name, qsd_fsinfo::qfs_ref, and RETURN.
Referenced by qsd_init(), and qsd_process_config().
int qsd_id_lock_cancel (const struct lu_env * , struct lquota_entry *)
Definition at line 494 of file qsd_lock.c.
References ldlm_enqueue_info::ei_mode, ENTRY, ldlm_lock_decref_and_cancel(), lquota_entry::lqe_granted, lqe_write_lock(), lqe_write_unlock(), lustre_handle_copy(), lustre_handle_is_used(), qsd_id_lock_match(), qsd_info(), qsd_set_edquot(), qsd_set_qunit(), qsd_thread_info::qti_lockh, and RETURN.
Referenced by qsd_upd_thread().
int qsd_id_lock_match (struct lustre_handle * lockh, struct lustre_handle * rlockh)
Check whether a slave already own a ldlm lock for the quota identifier .
Parameters:
lockh - is the local lock handle from lquota entry.
rlockh - is the remote lock handle of the matched lock, if any.
Return values:
0 : on successful look up and contains the lock handle.
-ENOENT,: no lock found
Definition at line 462 of file qsd_lock.c.
References D_QUOTA, ldlm_enqueue_info::ei_mode, ENTRY, ldlm_lock::l_remote_handle, LASSERT, ldlm_handle2lock(), ldlm_lock_addref_try(), ldlm_lock_dump_handle(), LDLM_LOCK_PUT, lustre_handle_copy(), lustre_handle_is_used(), and RETURN.
Referenced by qsd_acquire_remote(), qsd_adjust(), and qsd_id_lock_cancel().
static struct qsd_thread_info* qsd_info (const struct lu_env * env) [static, read]
Definition at line 261 of file qsd_internal.h.
References LASSERT, lu_env::le_ctx, lu_context_key_get(), lu_env_refill(), and qsd_thread_key.
Referenced by qsd_acquire_remote(), qsd_adjust(), qsd_id_lock_cancel(), qsd_init(), qsd_intent_lock(), qsd_lqe_read(), qsd_prepare(), qsd_reconciliation(), qsd_refresh_usage(), qsd_reint_entries(), qsd_reint_index(), qsd_reint_main(), and qsd_req_completion().
int qsd_intent_lock (const struct lu_env * , struct obd_export * , struct quota_body * , bool , int , qsd_req_completion_t , struct qsd_qtype_info * , struct lquota_lvb * , void *)
Definition at line 205 of file qsd_request.c.
References __u64, qsd_async_args::aa_arg, qsd_async_args::aa_completion, qsd_async_args::aa_exp, qsd_async_args::aa_lockh, qsd_async_args::aa_lvb, qsd_async_args::aa_qqi, class_exp2cliimp(), CLASSERT, ldlm_enqueue_info::ei_cbdata, ENTRY, fid_build_quota_res_name(), fid_build_reg_res_name(), GOTO, IT_QUOTA_CONN, IT_QUOTA_DQACQ, LASSERT, LASSERTF, ldlm_cli_enqueue(), LDLM_FL_HAS_INTENT, LDLM_FL_NO_LRU, ldlm_handle2lock(), LDLM_LOCK_PUT, ldlm_prep_enqueue_req(), lqe_getref(), lu_ref_add(), lustre_handle_copy(), lustre_handle_is_used(), LVB_T_LQUOTA, MDS_READPAGE_PORTAL, ldlm_intent::opc, ptlrpc_queue_wait(), ptlrpc_req_async_args, ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_set_replen(), ptlrpcd_add_req(), quota_body::qb_fid, quota_body::qb_id, quota_body::qb_lockh, qqi_getref(), qsd_qtype_info::qqi_reference, qsd_glb_einfo, qsd_id_einfo, qsd_info(), qsd_intent_interpret(), qsd_thread_info::qti_einfo, qsd_thread_info::qti_lockh, qsd_thread_info::qti_resid, RCL_SERVER, req_capsule_client_get(), req_capsule_set_size(), RETURN, RMF_DLM_LVB, RMF_LDLM_INTENT, RMF_QUOTA_BODY, ptlrpc_request::rq_no_delay, ptlrpc_request::rq_no_resend, ptlrpc_request::rq_no_retry_einprogress, ptlrpc_request::rq_pill, and RQF_LDLM_INTENT_QUOTA.
Referenced by qsd_acquire_remote(), qsd_adjust(), and qsd_reint_main().
int qsd_process_config (struct lustre_cfg *)
Definition at line 128 of file qsd_config.c.
References CDEBUG, CERROR, class_match_param(), D_QUOTA, ENTRY, GOTO, LCONSOLE_ERROR, list_for_each_entry, LQUOTA_FIRST_RES, LQUOTA_RES_DT, LQUOTA_RES_MD, lustre_cfg_string(), PARAM_QUOTA, qsd_fsinfo::qfs_enabled, qsd_fsinfo::qfs_mutex, qsd_fsinfo::qfs_qsd_list, qsd_instance::qsd_acct_failed, qsd_get_fsinfo(), qsd_instance::qsd_lock, qsd_instance::qsd_prepared, qsd_put_fsinfo(), qsd_start_reint_thread(), qsd_instance::qsd_svname, qsd_instance::qsd_type_array, QUOTA_DATAPOOL_NAME, QUOTA_METAPOOL_NAME, and RETURN.
Referenced by qsd_glb_init().
void qsd_put_fsinfo (struct qsd_fsinfo *)
Definition at line 47 of file qsd_config.c.
References ENTRY, EXIT, LASSERT, list_del(), list_empty(), OBD_FREE_PTR, qsd_fsinfo::qfs_link, qsd_fsinfo::qfs_qsd_list, and qsd_fsinfo::qfs_ref.
Referenced by qsd_fini(), and qsd_process_config().
int qsd_refresh_usage (const struct lu_env * , struct lquota_entry *)
Definition at line 186 of file qsd_entry.c.
References ENTRY, LASSERT, LPU64, lqe2qqi(), lquota_entry::lqe_id, LQUOTA_DEBUG, lquota_disk_read(), LQUOTA_ERROR, qsd_qtype_info::qqi_acct_obj, qsd_qtype_info::qqi_qsd, qsd_info(), qsd_instance::qsd_is_md, RETURN, and toqb.
Referenced by qsd_acquire(), qsd_lqe_read(), qsd_op_adjust(), qsd_op_begin0(), qsd_op_end0(), qsd_process_upd(), qsd_reconciliation(), and qsd_upd_thread().
int qsd_send_dqacq (const struct lu_env * , struct obd_export * , struct quota_body * , bool , qsd_req_completion_t , struct qsd_qtype_info * , struct lustre_handle * , struct lquota_entry *)
Definition at line 91 of file qsd_request.c.
References qsd_async_args::aa_arg, qsd_async_args::aa_completion, qsd_async_args::aa_exp, qsd_async_args::aa_lockh, qsd_async_args::aa_qqi, class_exp2cliimp(), CLASSERT, ENTRY, GOTO, LASSERT, lustre_handle_copy(), LUSTRE_MDS_VERSION, MDS_READPAGE_PORTAL, ptlrpc_queue_wait(), ptlrpc_req_async_args, ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), ptlrpcd_add_req(), qsd_dqacq_interpret(), QUOTA_DQACQ, req_capsule_client_get(), RETURN, RMF_QUOTA_BODY, ptlrpc_request::rq_no_delay, ptlrpc_request::rq_no_resend, ptlrpc_request::rq_no_retry_einprogress, ptlrpc_request::rq_pill, and RQF_QUOTA_DQACQ.
Referenced by qsd_acquire_remote(), and qsd_adjust().
static void qsd_set_edquot (struct lquota_entry * lqe, bool edquot) [inline, static]
Definition at line 321 of file qsd_internal.h.
References cfs_time_current_64, and lquota_entry::lqe_edquot.
Referenced by qsd_id_blocking_ast(), qsd_id_glimpse_ast(), qsd_id_lock_cancel(), and qsd_req_completion().
static void qsd_set_qunit (struct lquota_entry * lqe, __u64 qunit) [inline, static]
Definition at line 292 of file qsd_internal.h.
References lquota_entry::lqe_nopreacq, lquota_entry::lqe_qunit, and LQUOTA_DEBUG.
Referenced by qsd_id_blocking_ast(), qsd_id_glimpse_ast(), qsd_id_lock_cancel(), qsd_lqe_read(), and qsd_req_completion().
int qsd_start_reint_thread (struct qsd_qtype_info *)
Definition at line 624 of file qsd_reint.c.
References ENTRY, l_wait_event, MTI_NAME_MAXLEN, name, OBD_ALLOC, OBD_FREE, qsd_qtype_info::qqi_glb_uptodate, qsd_qtype_info::qqi_qsd, qsd_qtype_info::qqi_qtype, qsd_qtype_info::qqi_reint, qsd_qtype_info::qqi_reint_thread, qsd_qtype_info::qqi_slv_uptodate, qsd_instance::qsd_acct_failed, qsd_instance::qsd_lock, qsd_pending_updates(), qsd_reint_main(), qsd_instance::qsd_stopping, qsd_instance::qsd_svname, qsd_type_enabled(), RETURN, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, thread, thread_is_running(), thread_is_stopped(), and thread_set_flags().
Referenced by lprocfs_force_reint_seq_write(), qsd_glb_blocking_ast(), qsd_prepare(), qsd_process_config(), qsd_ready(), and qsd_upd_thread().
int qsd_start_upd_thread (struct qsd_instance *)
Definition at line 493 of file qsd_writeback.c.
References CERROR, ENTRY, l_wait_event, qsd_instance::qsd_svname, qsd_upd_thread(), qsd_instance::qsd_upd_thread, RETURN, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, thread, thread_is_running(), thread_is_stopped(), and thread_set_flags().
Referenced by qsd_prepare().
void qsd_stop_reint_thread (struct qsd_qtype_info *)
Definition at line 544 of file qsd_reint.c.
References l_wait_event, qsd_qtype_info::qqi_reint_thread, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, thread, thread_is_stopped(), and thread_set_flags().
Referenced by qsd_fini().
void qsd_stop_upd_thread (struct qsd_instance *)
Definition at line 563 of file qsd_writeback.c.
References l_wait_event, qsd_cleanup_adjust(), qsd_cleanup_deferred(), qsd_instance::qsd_upd_thread, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, thread, thread_is_stopped(), and thread_set_flags().
Referenced by qsd_fini().
static int qsd_type_enabled (struct qsd_instance * qsd, int type) [inline, static]
Definition at line 275 of file qsd_internal.h.
References LASSERT, LQUOTA_FIRST_RES, LQUOTA_RES_DT, LQUOTA_RES_MD, qsd_fsinfo::qfs_enabled, qsd_instance::qsd_fsinfo, and qsd_instance::qsd_is_md.
Referenced by qsd_enabled_seq_show(), qsd_job_pending(), qsd_op_adjust(), qsd_op_begin(), qsd_prepare(), qsd_start_reint_thread(), and qsd_state_seq_show().
void qsd_upd_schedule (struct qsd_qtype_info * , struct lquota_entry * , union lquota_id * , union lquota_rec * , __u64 , bool)
Definition at line 217 of file qsd_writeback.c.
References __u64, CDEBUG, CERROR, D_QUOTA, ENTRY, EXIT, list, LPU64, qsd_qtype_info::qqi_deferred_glb, qsd_qtype_info::qqi_deferred_slv, qsd_qtype_info::qqi_glb_uptodate, qsd_qtype_info::qqi_glb_ver, qsd_qtype_info::qqi_qsd, qsd_qtype_info::qqi_slv_uptodate, qsd_qtype_info::qqi_slv_ver, qsd_add_deferred(), qsd_instance::qsd_lock, qsd_instance::qsd_svname, qsd_upd_add(), qsd_upd_alloc(), qsd_upd_free(), and RETURN_EXIT.
Referenced by qsd_glb_glimpse_ast(), qsd_id_glimpse_ast(), and qsd_req_completion().
int qsd_update_index (const struct lu_env * , struct qsd_qtype_info * , union lquota_id * , bool , __u64 , void *)
Definition at line 233 of file qsd_entry.c.
References __u64, CDEBUG, CERROR, D_QUOTA, dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), ENTRY, EXIT, GOTO, LPU64, lquota_disk_declare_write(), lquota_disk_write(), LQUOTA_SET_VER, lquota_glb_rec::qbr_hardlimit, lquota_glb_rec::qbr_softlimit, lquota_id::qid_uid, qsd_qtype_info::qqi_glb_obj, qsd_qtype_info::qqi_qsd, qsd_qtype_info::qqi_slv_obj, qsd_bump_version(), qsd_instance::qsd_dev, qsd_instance::qsd_svname, lquota_slv_rec::qsr_granted, and RETURN.
Referenced by qsd_process_upd(), and qsd_reint_qid().
int qsd_update_lqe (const struct lu_env * , struct lquota_entry * , bool , void *)
Definition at line 309 of file qsd_entry.c.
References ENTRY, LASSERT, LPU64, lquota_entry::lqe_enforced, lquota_entry::lqe_granted, lqe_is_master(), LQUOTA_DEBUG, lquota_glb_rec::qbr_hardlimit, lquota_glb_rec::qbr_softlimit, lquota_slv_rec::qsr_granted, and RETURN.
Referenced by qsd_process_upd(), and qsd_reint_qid().
static int qsd_wait_timeout (struct qsd_instance * qsd) [inline, static]
Definition at line 332 of file qsd_internal.h.
References at_max, min_t, obd_timeout, and qsd_instance::qsd_timeout.
Referenced by qsd_op_begin0(), and qsd_timeout_seq_show().
int qsd_write_version (const struct lu_env * , struct qsd_qtype_info * , __u64 , bool)
Definition at line 161 of file qsd_entry.c.
References ENTRY, lquota_disk_update_ver(), qsd_qtype_info::qqi_glb_obj, qsd_qtype_info::qqi_qsd, qsd_qtype_info::qqi_slv_obj, qsd_bump_version(), qsd_instance::qsd_dev, and RETURN.
Referenced by qsd_reint_index().
Variable Documentation
struct ldlm_enqueue_info qsd_glb_einfo
Definition at line 46 of file qsd_lock.c.
Referenced by qsd_intent_lock(), and qsd_reint_main().
struct ldlm_enqueue_info qsd_id_einfo
Definition at line 54 of file qsd_lock.c.
Referenced by qsd_intent_lock(), and qsd_req_completion().
struct lquota_entry_operations qsd_lqe_ops
Definition at line 155 of file qsd_entry.c.
Referenced by qsd_qtype_init().
struct lu_context_key qsd_thread_key
Referenced by qsd_glb_fini(), qsd_glb_init(), and qsd_info().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.