Lustre: lustre/quota/qsd_config.c File Reference
lustre/quota/qsd_config.c File Reference
#include <obd_class.h>
#include <lustre_param.h>
#include "qsd_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LQUOTA
Functions
static DEFINE_SPINLOCK (qfs_list_lock)
void qsd_put_fsinfo (struct qsd_fsinfo *qfs)
struct qsd_fsinfo * qsd_get_fsinfo (char *name, bool create)
int qsd_process_config (struct lustre_cfg *lcfg)
Variables
static struct list_head qfs_list = LIST_HEAD_INIT(qfs_list)
Define Documentation
#define DEBUG_SUBSYSTEM S_LQUOTA
Definition at line 31 of file qsd_config.c.
Function Documentation
static DEFINE_SPINLOCK (qfs_list_lock) [static]
struct qsd_fsinfo* qsd_get_fsinfo (char * name, bool create) [read]
Definition at line 74 of file qsd_config.c.
References ENTRY, INIT_LIST_HEAD, list_add_tail(), list_for_each_entry, MTI_NAME_MAXLEN, OBD_ALLOC_PTR, OBD_FREE_PTR, qsd_fsinfo::qfs_link, qsd_fsinfo::qfs_name, qsd_fsinfo::qfs_ref, and RETURN.
Referenced by qsd_init(), and qsd_process_config().
int qsd_process_config (struct lustre_cfg * lcfg)
Definition at line 128 of file qsd_config.c.
References CDEBUG, CERROR, class_match_param(), D_QUOTA, ENTRY, GOTO, LCONSOLE_ERROR, list_for_each_entry, LQUOTA_FIRST_RES, LQUOTA_RES_DT, LQUOTA_RES_MD, lustre_cfg_string(), PARAM_QUOTA, qsd_fsinfo::qfs_enabled, qsd_fsinfo::qfs_mutex, qsd_fsinfo::qfs_qsd_list, qsd_instance::qsd_acct_failed, qsd_get_fsinfo(), qsd_instance::qsd_lock, qsd_instance::qsd_prepared, qsd_put_fsinfo(), qsd_start_reint_thread(), qsd_instance::qsd_svname, qsd_instance::qsd_type_array, QUOTA_DATAPOOL_NAME, QUOTA_METAPOOL_NAME, and RETURN.
Referenced by qsd_glb_init().
void qsd_put_fsinfo (struct qsd_fsinfo * qfs)
Definition at line 47 of file qsd_config.c.
References ENTRY, EXIT, LASSERT, list_del(), list_empty(), OBD_FREE_PTR, qsd_fsinfo::qfs_link, qsd_fsinfo::qfs_qsd_list, and qsd_fsinfo::qfs_ref.
Referenced by qsd_fini(), and qsd_process_config().
Variable Documentation
struct list_head qfs_list = LIST_HEAD_INIT(qfs_list) [static]
Definition at line 38 of file qsd_config.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.