Lustre: lustre/quota/qsd_request.c File Reference
lustre/quota/qsd_request.c File Reference
#include <lustre_net.h>
#include <lustre_import.h>
#include <lustre_dlm.h>
#include <obd_class.h>
#include "qsd_internal.h"
Data Structures
struct qsd_async_args
Defines
#define DEBUG_SUBSYSTEM S_LQUOTA
Functions
static int qsd_dqacq_interpret (const struct lu_env *env, struct ptlrpc_request *req, void *arg, int rc)
int qsd_send_dqacq (const struct lu_env *env, struct obd_export *exp, struct quota_body *qbody, bool sync, qsd_req_completion_t completion, struct qsd_qtype_info *qqi, struct lustre_handle *lockh, struct lquota_entry *lqe)
static int qsd_intent_interpret (const struct lu_env *env, struct ptlrpc_request *req, void *arg, int rc)
int qsd_intent_lock (const struct lu_env *env, struct obd_export *exp, struct quota_body *qbody, bool sync, int it_op, qsd_req_completion_t completion, struct qsd_qtype_info *qqi, struct lquota_lvb *lvb, void *arg)
int qsd_fetch_index (const struct lu_env *env, struct obd_export *exp, struct idx_info *ii, unsigned int npages, struct page **pages, bool *need_swab)
Define Documentation
#define DEBUG_SUBSYSTEM S_LQUOTA
Definition at line 31 of file qsd_request.c.
Function Documentation
static int qsd_dqacq_interpret (const struct lu_env * env, struct ptlrpc_request * req, void * arg, int rc) [static]
Definition at line 60 of file qsd_request.c.
References qsd_async_args::aa_arg, qsd_async_args::aa_completion, qsd_async_args::aa_lockh, qsd_async_args::aa_qqi, ENTRY, req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_QUOTA_BODY, and ptlrpc_request::rq_pill.
Referenced by qsd_send_dqacq().
int qsd_fetch_index (const struct lu_env * env, struct obd_export * exp, struct idx_info * ii, unsigned int npages, struct page ** pages, bool * need_swab)
Definition at line 351 of file qsd_request.c.
References ptlrpc_bulk_frag_ops::add_kiov_frag, ptlrpc_bulk_desc::bd_frag_ops, class_exp2cliimp(), ENTRY, EXIT, GOTO, LASSERT, LUSTRE_OBD_VERSION, MDS_BULK_PORTAL, MDS_READPAGE_PORTAL, OBD_IDX_READ, ptlrpc_at_set_req_timeout(), PTLRPC_BULK_BUF_KIOV, ptlrpc_bulk_kiov_pin_ops, PTLRPC_BULK_PUT_SINK, ptlrpc_prep_bulk_imp(), ptlrpc_queue_wait(), ptlrpc_rep_need_swab(), ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_IDX_INFO, ptlrpc_request::rq_pill, RQF_OBD_IDX_READ, and sptlrpc_cli_unwrap_bulk_read().
Referenced by qsd_reint_index().
static int qsd_intent_interpret (const struct lu_env * env, struct ptlrpc_request * req, void * arg, int rc) [static]
Definition at line 156 of file qsd_request.c.
References __u64, qsd_async_args::aa_arg, qsd_async_args::aa_completion, qsd_async_args::aa_exp, qsd_async_args::aa_lockh, qsd_async_args::aa_lvb, qsd_async_args::aa_qqi, ENTRY, LASSERT, LCK_CR, ldlm_cli_enqueue_fini(), LDLM_FL_HAS_INTENT, LDLM_PLAIN, req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_LDLM_INTENT, RMF_QUOTA_BODY, and ptlrpc_request::rq_pill.
Referenced by qsd_intent_lock().
int qsd_intent_lock (const struct lu_env * env, struct obd_export * exp, struct quota_body * qbody, bool sync, int it_op, qsd_req_completion_t completion, struct qsd_qtype_info * qqi, struct lquota_lvb * lvb, void * arg)
Definition at line 205 of file qsd_request.c.
References __u64, qsd_async_args::aa_arg, qsd_async_args::aa_completion, qsd_async_args::aa_exp, qsd_async_args::aa_lockh, qsd_async_args::aa_lvb, qsd_async_args::aa_qqi, class_exp2cliimp(), CLASSERT, ldlm_enqueue_info::ei_cbdata, ENTRY, fid_build_quota_res_name(), fid_build_reg_res_name(), GOTO, IT_QUOTA_CONN, IT_QUOTA_DQACQ, LASSERT, LASSERTF, ldlm_cli_enqueue(), LDLM_FL_HAS_INTENT, LDLM_FL_NO_LRU, ldlm_handle2lock(), LDLM_LOCK_PUT, ldlm_prep_enqueue_req(), lqe_getref(), lu_ref_add(), lustre_handle_copy(), lustre_handle_is_used(), LVB_T_LQUOTA, MDS_READPAGE_PORTAL, ldlm_intent::opc, ptlrpc_queue_wait(), ptlrpc_req_async_args, ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_set_replen(), ptlrpcd_add_req(), quota_body::qb_fid, quota_body::qb_id, quota_body::qb_lockh, qqi_getref(), qsd_qtype_info::qqi_reference, qsd_glb_einfo, qsd_id_einfo, qsd_info(), qsd_intent_interpret(), qsd_thread_info::qti_einfo, qsd_thread_info::qti_lockh, qsd_thread_info::qti_resid, RCL_SERVER, req_capsule_client_get(), req_capsule_set_size(), RETURN, RMF_DLM_LVB, RMF_LDLM_INTENT, RMF_QUOTA_BODY, ptlrpc_request::rq_no_delay, ptlrpc_request::rq_no_resend, ptlrpc_request::rq_no_retry_einprogress, ptlrpc_request::rq_pill, and RQF_LDLM_INTENT_QUOTA.
Referenced by qsd_acquire_remote(), qsd_adjust(), and qsd_reint_main().
int qsd_send_dqacq (const struct lu_env * env, struct obd_export * exp, struct quota_body * qbody, bool sync, qsd_req_completion_t completion, struct qsd_qtype_info * qqi, struct lustre_handle * lockh, struct lquota_entry * lqe)
Definition at line 91 of file qsd_request.c.
References qsd_async_args::aa_arg, qsd_async_args::aa_completion, qsd_async_args::aa_exp, qsd_async_args::aa_lockh, qsd_async_args::aa_qqi, class_exp2cliimp(), CLASSERT, ENTRY, GOTO, LASSERT, lustre_handle_copy(), LUSTRE_MDS_VERSION, MDS_READPAGE_PORTAL, ptlrpc_queue_wait(), ptlrpc_req_async_args, ptlrpc_req_finished(), ptlrpc_request_alloc(), ptlrpc_request_free(), ptlrpc_request_pack(), ptlrpc_request_set_replen(), ptlrpcd_add_req(), qsd_dqacq_interpret(), QUOTA_DQACQ, req_capsule_client_get(), RETURN, RMF_QUOTA_BODY, ptlrpc_request::rq_no_delay, ptlrpc_request::rq_no_resend, ptlrpc_request::rq_no_retry_einprogress, ptlrpc_request::rq_pill, and RQF_QUOTA_DQACQ.
Referenced by qsd_acquire_remote(), and qsd_adjust().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.