Lustre: lustre/quota/qsd_handler.c File Reference
lustre/quota/qsd_handler.c File Reference
#include "qsd_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LQUOTA
Functions
static int qsd_request_enter (struct lquota_entry *lqe)
helper function bumping lqe_pending_req if there is no quota request in flight for the lquota entry lqe.
static void qsd_request_exit (struct lquota_entry *lqe)
Companion of qsd_request_enter() dropping lqe_pending_req to 0.
static int qsd_ready (struct lquota_entry *lqe, struct lustre_handle *lockh)
Check whether a qsd instance is all set to send quota request to master.
static bool qsd_calc_adjust (struct lquota_entry *lqe, struct quota_body *qbody)
Check whether any quota space adjustment (pre-acquire/release/report) is needed for a given quota ID.
static bool qsd_adjust_needed (struct lquota_entry *lqe)
Helper function returning true when quota space need to be adjusted (some unused space should be free or pre-acquire) and false otherwise.
static void qsd_req_completion (const struct lu_env *env, struct qsd_qtype_info *qqi, struct quota_body *reqbody, struct quota_body *repbody, struct lustre_handle *lockh, struct lquota_lvb *lvb, void *arg, int ret)
Callback function called when an acquire/release request sent to the master is completed.
static int qsd_acquire_local (struct lquota_entry *lqe, __u64 space)
Try to consume local quota space.
static bool qsd_calc_acquire (struct lquota_entry *lqe, struct quota_body *qbody)
Compute how much quota space should be acquire from the master based on how much is currently granted to this slave and pending/waiting operations.
static int qsd_acquire_remote (const struct lu_env *env, struct lquota_entry *lqe)
Acquire quota space from master.
static bool qsd_acquire (const struct lu_env *env, struct lquota_entry *lqe, long long space, int *ret)
Acquire space of quota space in order to complete an operation.
static int qsd_op_begin0 (const struct lu_env *env, struct qsd_qtype_info *qqi, struct lquota_id_info *qid, long long space, int *flags)
Quota enforcement handler.
static bool qid_equal (struct lquota_id_info *q1, struct lquota_id_info *q2)
helper function comparing two lquota_id_info structures
int qsd_op_begin (const struct lu_env *env, struct qsd_instance *qsd, struct lquota_trans *trans, struct lquota_id_info *qi, int *flags)
Enforce quota, it's called in the declaration of each operation.
int qsd_adjust (const struct lu_env *env, struct lquota_entry *lqe)
Adjust quota space (by acquiring or releasing) hold by the quota slave.
static void qsd_op_end0 (const struct lu_env *env, struct qsd_qtype_info *qqi, struct lquota_id_info *qid)
Post quota operation, pre-acquire/release quota from master.
void qsd_op_end (const struct lu_env *env, struct qsd_instance *qsd, struct lquota_trans *trans)
Post quota operation.
void qsd_op_adjust (const struct lu_env *env, struct qsd_instance *qsd, union lquota_id *qid, int qtype)
Trigger pre-acquire/release if necessary.
Define Documentation
#define DEBUG_SUBSYSTEM S_LQUOTA
Definition at line 31 of file qsd_handler.c.
Function Documentation
static bool qid_equal (struct lquota_id_info * q1, struct lquota_id_info * q2) [inline, static]
helper function comparing two lquota_id_info structures
Definition at line 799 of file qsd_handler.c.
References lquota_id_info::lqi_id, lquota_id_info::lqi_type, and lquota_id::qid_uid.
Referenced by qsd_op_begin().
static bool qsd_acquire (const struct lu_env * env, struct lquota_entry * lqe, long long space, int * ret) [static]
Acquire space of quota space in order to complete an operation.
Try to consume local quota space first and send acquire request to quota master if required.
Parameters:
env - the environment passed by the caller
lqe - is the qid entry to be processed
space - is the amount of quota required for the operation
ret - is the return code (-EDQUOT, -EINPROGRESS, ...)
Return values:
true - exit from l_wait_event and real return value in ret
false - continue waiting
Definition at line 630 of file qsd_handler.c.
References ENTRY, LPD64, lqe2qqi(), LQUOTA_DEBUG, qsd_acquire_local(), qsd_acquire_remote(), qsd_refresh_usage(), and RETURN.
Referenced by qsd_op_begin0().
static int qsd_acquire_local (struct lquota_entry * lqe, __u64 space) [static]
Try to consume local quota space.
Parameters:
lqe - is the qid entry to be processed
space - is the amount of quota space needed to complete the operation
Return values:
0 - success
-EDQUOT - out of quota
-EAGAIN - need to acquire space from master
Definition at line 440 of file qsd_handler.c.
References __u64, cfs_time_before_64(), cfs_time_shift_64(), ENTRY, lquota_entry::lqe_edquot, lquota_entry::lqe_enforced, lqe_write_lock(), lqe_write_unlock(), RETURN, and usage.
Referenced by qsd_acquire().
static int qsd_acquire_remote (const struct lu_env * env, struct lquota_entry * lqe) [static]
Acquire quota space from master.
There are at most 1 in-flight dqacq/dqrel.
Parameters:
env - the environment passed by the caller
lqe - is the qid entry to be processed
Return values:
0 - success
-EDQUOT - out of quota
-EINPROGRESS - inform client to retry write/create
-EBUSY - already a quota request in flight
-ve - other appropriate errors
Definition at line 530 of file qsd_handler.c.
References cfs_time_before_64(), cfs_time_shift_64(), ENTRY, IT_QUOTA_DQACQ, lqe2qqi(), lquota_entry::lqe_enforced, lqe_getref(), lquota_entry::lqe_id, lqe_write_lock(), lqe_write_unlock(), LQUOTA_DEBUG, lustre_handle_copy(), OBD_ALLOC_PTR, quota_body::qb_fid, quota_body::qb_glb_lockh, quota_body::qb_id, quota_body::qb_lockh, qsd_qtype_info::qqi_fid, qsd_qtype_info::qqi_qsd, qsd_calc_acquire(), qsd_instance::qsd_exp, qsd_id_lock_match(), qsd_info(), qsd_intent_lock(), qsd_ready(), qsd_req_completion(), qsd_request_enter(), qsd_send_dqacq(), qsd_thread_info::qti_body, qsd_thread_info::qti_lockh, and RETURN.
Referenced by qsd_acquire().
int qsd_adjust (const struct lu_env * env, struct lquota_entry * lqe)
Adjust quota space (by acquiring or releasing) hold by the quota slave.
This function is called after each quota request completion and during reintegration in order to report usage or re-acquire quota locks. Space adjustment is aborted if there is already a quota request in flight for this ID.
Parameters:
env - the environment passed by the caller
lqe - is the qid entry to be processed
Return values:
0 on success, appropriate errors on failure
Definition at line 902 of file qsd_handler.c.
References ENTRY, GOTO, IT_QUOTA_DQACQ, lqe2qqi(), lqe_getref(), lquota_entry::lqe_id, lqe_write_lock(), lqe_write_unlock(), LQUOTA_DEBUG, lustre_handle_copy(), OBD_ALLOC_PTR, quota_body::qb_count, quota_body::qb_fid, quota_body::qb_flags, quota_body::qb_glb_lockh, quota_body::qb_id, quota_body::qb_lockh, qsd_qtype_info::qqi_fid, qsd_qtype_info::qqi_qsd, qsd_adjust_schedule(), qsd_calc_adjust(), qsd_instance::qsd_exp, qsd_id_lock_match(), qsd_info(), qsd_intent_lock(), qsd_ready(), qsd_req_completion(), qsd_request_enter(), qsd_send_dqacq(), qsd_thread_info::qti_body, qsd_thread_info::qti_lockh, QUOTA_DQACQ_FL_REPORT, req_has_rep, req_is_acq, req_is_preacq, req_is_rel, and RETURN.
Referenced by qsd_id_blocking_ast(), qsd_op_adjust(), qsd_op_end0(), qsd_process_upd(), qsd_reconciliation(), and qsd_upd_thread().
static bool qsd_adjust_needed (struct lquota_entry * lqe) [inline, static]
Helper function returning true when quota space need to be adjusted (some unused space should be free or pre-acquire) and false otherwise.
Definition at line 293 of file qsd_handler.c.
References qsd_calc_adjust().
Referenced by qsd_op_adjust(), qsd_op_end0(), and qsd_req_completion().
static bool qsd_calc_acquire (struct lquota_entry * lqe, struct quota_body * qbody) [inline, static]
Compute how much quota space should be acquire from the master based on how much is currently granted to this slave and pending/waiting operations.
Parameters:
lqe - is the lquota entry for which we would like to adjust quota space.
qbody - is the quota body of the acquire request to fill
Return values:
true - space acquisition is needed and qbody is filled
false - no space acquisition required
Definition at line 489 of file qsd_handler.c.
References __u64, lquota_entry::lqe_granted, quota_body::qb_count, quota_body::qb_flags, quota_body::qb_usage, QUOTA_DQACQ_FL_ACQ, QUOTA_DQACQ_FL_REPORT, and usage.
Referenced by qsd_acquire_remote().
static bool qsd_calc_adjust (struct lquota_entry * lqe, struct quota_body * qbody) [static]
Check whether any quota space adjustment (pre-acquire/release/report) is needed for a given quota ID.
If a non-null qbody is passed, then the qbody structure (qb_count/flags/usage) is filled with appropriate data to be packed in the quota request.
Parameters:
lqe - is the lquota entry for which we would like to adjust quota space.
qbody - is the quota body to fill, if not NULL.
Return values:
true - space adjustment is required and qbody is filled, if not NULL
false - no space adjustment required
Definition at line 159 of file qsd_handler.c.
References __u64, ENTRY, lquota_entry::lqe_edquot, lquota_entry::lqe_enforced, lquota_entry::lqe_granted, lquota_entry::lqe_nopreacq, lqe_qtune, lquota_entry::lqe_qunit, LQUOTA_DEBUG, lustre_handle_is_used(), quota_body::qb_count, quota_body::qb_flags, quota_body::qb_usage, QUOTA_DQACQ_FL_ACQ, QUOTA_DQACQ_FL_PREACQ, QUOTA_DQACQ_FL_REL, QUOTA_DQACQ_FL_REPORT, RETURN, and usage.
Referenced by qsd_adjust(), and qsd_adjust_needed().
void qsd_op_adjust (const struct lu_env * env, struct qsd_instance * qsd, union lquota_id * qid, int qtype)
Trigger pre-acquire/release if necessary.
It's only used by ldiskfs osd so far. When unlink a file in ldiskfs, the quota accounting isn't updated when the transaction stopped. Instead, it'll be updated on the final iput, so qsd_op_adjust() will be called then (in osd_object_delete()) to trigger quota release if necessary.
Parameters:
env - the environment passed by the caller
qsd - is the qsd instance associated with the device in charge of the operation.
qid - is the lquota ID of the user/group for which to trigger quota space adjustment
qtype - is the quota type (USRQUOTA or GRPQUOTA)
Definition at line 1119 of file qsd_handler.c.
References CERROR, ENTRY, EXIT, LASSERT, LPU64, lqe_locate(), lqe_putref(), lqe_read_lock(), lqe_read_unlock(), lquota_id::qid_uid, qsd_qtype_info::qqi_acct_obj, qsd_qtype_info::qqi_site, qsd_adjust(), qsd_adjust_needed(), qsd_instance::qsd_lock, qsd_refresh_usage(), qsd_instance::qsd_started, qsd_instance::qsd_svname, qsd_instance::qsd_type_array, qsd_type_enabled(), RETURN_EXIT, and unlikely.
Referenced by osd_object_delete().
int qsd_op_begin (const struct lu_env * env, struct qsd_instance * qsd, struct lquota_trans * trans, struct lquota_id_info * qi, int * flags)
Enforce quota, it's called in the declaration of each operation.
qsd_op_end() will then be called later once all the operations have been completed in order to release/adjust the quota space.
Parameters:
env - the environment passed by the caller
qsd - is the qsd instance associated with the device in charge of the operation.
trans - is the quota transaction information
qi - qid & space required by current operation
flags - if the operation is write, return caller no user/group and sync commit flags
Return values:
0 - success
-EDQUOT - out of quota
-EINPROGRESS - inform client to retry write
-ve - other appropriate errors
Definition at line 825 of file qsd_handler.c.
References CERROR, ENTRY, LASSERT, LASSERTF, lquota_id_info::lqi_id, lquota_id_info::lqi_is_blk, lquota_id_info::lqi_space, lquota_id_info::lqi_type, lquota_trans::lqt_id_cnt, lquota_trans::lqt_ids, qid_equal(), lquota_id::qid_uid, qsd_instance::qsd_acct_failed, qsd_instance::qsd_is_md, qsd_instance::qsd_lock, qsd_op_begin0(), qsd_instance::qsd_started, qsd_instance::qsd_svname, qsd_instance::qsd_type_array, qsd_type_enabled(), QUOTA_MAX_TRANSIDS, RETURN, and unlikely.
Referenced by osd_declare_qid(), osd_declare_quota(), and qsd_transfer().
static int qsd_op_begin0 (const struct lu_env * env, struct qsd_qtype_info * qqi, struct lquota_id_info * qid, long long space, int * flags) [static]
Quota enforcement handler.
If local quota can satisfy this operation, return success, otherwise, acquire more quota from master. (for write operation, if master isn't available at this moment, return -EINPROGRESS to inform client to retry the write)
Parameters:
env - the environment passed by the caller
qsd - is the qsd instance associated with the device in charge of the operation.
qid - is the qid information attached in the transaction handle
space - is the space required by the operation
flags - if the operation is write, return caller no user/group and sync commit flags
Return values:
0 - success
-EDQUOT - out of quota
-EINPROGRESS - inform client to retry write
-ve - other appropriate errors
Definition at line 686 of file qsd_handler.c.
References __u64, cfs_time_seconds(), ENTRY, GOTO, l_wait_event, LASSERT, LPD64, lquota_entry::lqe_enforced, lquota_entry::lqe_granted, lqe_locate(), lqe_putref(), lqe_read_lock(), lqe_read_unlock(), lqe_write_lock(), lqe_write_unlock(), lquota_id_info::lqi_id, lquota_id_info::lqi_is_blk, lquota_id_info::lqi_qentry, lquota_id_info::lqi_space, LQUOTA_DEBUG, LQUOTA_ERROR, LQUOTA_OVER_FL, LWI_TIMEOUT, qsd_qtype_info::qqi_qsd, qsd_qtype_info::qqi_qtype, qsd_qtype_info::qqi_site, qsd_acquire(), qsd_refresh_usage(), qsd_instance::qsd_sync_threshold, qsd_wait_timeout(), QUOTA_FL_SYNC, ret, RETURN, and usage.
Referenced by qsd_op_begin().
void qsd_op_end (const struct lu_env * env, struct qsd_instance * qsd, struct lquota_trans * trans)
Post quota operation.
It's called after each operation transaction stopped.
Parameters:
env - the environment passed by the caller
qsd - is the qsd instance associated with device which is handling the operation.
qids - all qids information attached in the transaction handle
count - is the number of qid entries in the qids array.
Return values:
0 - success
-ve - failure
Definition at line 1069 of file qsd_handler.c.
References ENTRY, EXIT, LASSERT, lquota_id_info::lqi_qentry, lquota_id_info::lqi_type, lquota_trans::lqt_id_cnt, lquota_trans::lqt_ids, qsd_instance::qsd_lock, qsd_op_end0(), qsd_instance::qsd_started, qsd_instance::qsd_type_array, RETURN_EXIT, and unlikely.
Referenced by osd_trans_commit_cb(), and osd_trans_stop().
static void qsd_op_end0 (const struct lu_env * env, struct qsd_qtype_info * qqi, struct lquota_id_info * qid) [static]
Post quota operation, pre-acquire/release quota from master.
Parameters:
env - the environment passed by the caller
qsd - is the qsd instance attached to the OSD device which is handling the operation.
qqi - is the qsd_qtype_info structure associated with the quota ID subject to the operation
qid - stores information related to his ID for the operation which has just completed
Return values:
0 - success
-ve - failure
Definition at line 1019 of file qsd_handler.c.
References ENTRY, EXIT, lqe_putref(), lqe_write_lock(), lqe_write_unlock(), lquota_id_info::lqi_qentry, lquota_id_info::lqi_space, qsd_adjust(), qsd_adjust_needed(), qsd_adjust_schedule(), qsd_refresh_usage(), and RETURN_EXIT.
Referenced by qsd_op_end().
static int qsd_ready (struct lquota_entry * lqe, struct lustre_handle * lockh) [static]
Check whether a qsd instance is all set to send quota request to master.
This includes checking whether:
the connection to master is set up and usable,
the qsd isn't stopping
reintegration has been successfully completed and all indexes are up-to-date
Parameters:
lqe - is the lquota entry for which we would like to send an quota request
lockh - is the remote handle of the global lock returned on success
Return values:
0 on success, appropriate error on failure
Definition at line 85 of file qsd_handler.c.
References class_exp2cliimp(), ENTRY, obd_import::imp_invalid, ldlm_lock::l_remote_handle, ldlm_handle2lock(), LDLM_LOCK_PUT, lqe2qqi(), LQUOTA_DEBUG, lustre_handle_copy(), lustre_handle_is_used(), qsd_qtype_info::qqi_glb_uptodate, qsd_qtype_info::qqi_lockh, qsd_qtype_info::qqi_qsd, qsd_qtype_info::qqi_slv_uptodate, qsd_instance::qsd_exp, qsd_instance::qsd_exp_valid, qsd_instance::qsd_lock, qsd_start_reint_thread(), qsd_instance::qsd_stopping, and RETURN.
Referenced by qsd_acquire_remote(), and qsd_adjust().
static void qsd_req_completion (const struct lu_env * env, struct qsd_qtype_info * qqi, struct quota_body * reqbody, struct quota_body * repbody, struct lustre_handle * lockh, struct lquota_lvb * lvb, void * arg, int ret) [static]
Callback function called when an acquire/release request sent to the master is completed.
Definition at line 302 of file qsd_handler.c.
References cfs_time_current_64, ldlm_enqueue_info::ei_mode, ENTRY, EXIT, GOTO, LASSERT, LCT_DT_THREAD, ldlm_lock_decref(), LPU64, lquota_entry::lqe_granted, lquota_entry::lqe_id, lquota_entry::lqe_nopreacq, lqe_putref(), lqe_write_lock(), lqe_write_unlock(), lquota_rec::lqr_slv_rec, LQUOTA_DEBUG, LQUOTA_ERROR, LQUOTA_FL_EDQUOT, lu_env_refill_by_tags(), lustre_handle_copy(), lustre_handle_equal(), lustre_handle_is_used(), lquota_lvb::lvb_flags, lquota_lvb::lvb_id_qunit, OBD_FREE_PTR, quota_body::qb_count, quota_body::qb_flags, qsd_adjust_needed(), qsd_adjust_schedule(), qsd_id_einfo, qsd_info(), qsd_request_exit(), qsd_set_edquot(), qsd_set_qunit(), qsd_upd_schedule(), lquota_slv_rec::qsr_granted, qsd_thread_info::qti_rec, req_is_acq, req_is_preacq, and req_is_rel.
Referenced by qsd_acquire_remote(), and qsd_adjust().
static int qsd_request_enter (struct lquota_entry * lqe) [inline, static]
helper function bumping lqe_pending_req if there is no quota request in flight for the lquota entry lqe.
Otherwise, EBUSY is returned.
Definition at line 39 of file qsd_handler.c.
References LBUG, LPU64, LQUOTA_DEBUG, and LQUOTA_ERROR.
Referenced by qsd_acquire_remote(), and qsd_adjust().
static void qsd_request_exit (struct lquota_entry * lqe) [inline, static]
Companion of qsd_request_enter() dropping lqe_pending_req to 0.
Definition at line 60 of file qsd_handler.c.
References LBUG, and LQUOTA_ERROR.
Referenced by qsd_req_completion().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.