Lustre: lustre/quota/qsd_entry.c File Reference
lustre/quota/qsd_entry.c File Reference
#include "qsd_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LQUOTA
Functions
static void qsd_lqe_init (struct lquota_entry *lqe, void *arg)
static int qsd_lqe_read (const struct lu_env *env, struct lquota_entry *lqe, void *arg)
static void qsd_lqe_debug (struct lquota_entry *lqe, void *arg, struct libcfs_debug_msg_data *msgdata, const char *fmt, va_list args)
int qsd_write_version (const struct lu_env *env, struct qsd_qtype_info *qqi, __u64 ver, bool global)
int qsd_refresh_usage (const struct lu_env *env, struct lquota_entry *lqe)
int qsd_update_index (const struct lu_env *env, struct qsd_qtype_info *qqi, union lquota_id *qid, bool global, __u64 ver, void *rec)
int qsd_update_lqe (const struct lu_env *env, struct lquota_entry *lqe, bool global, void *rec)
Variables
struct lquota_entry_operations qsd_lqe_ops
Define Documentation
#define DEBUG_SUBSYSTEM S_LQUOTA
Definition at line 31 of file qsd_entry.c.
Function Documentation
static void qsd_lqe_debug (struct lquota_entry * lqe, void * arg, struct libcfs_debug_msg_data * msgdata, const char * fmt, va_list args) [static]
Definition at line 134 of file qsd_entry.c.
References libcfs_debug_vmsg2(), LPU64, lquota_entry::lqe_edquot, lquota_entry::lqe_enforced, lquota_entry::lqe_granted, lquota_entry::lqe_id, lquota_entry::lqe_qunit, lquota_id::qid_uid, qsd_qtype_info::qqi_qsd, qsd_qtype_info::qqi_qtype, qsd_instance::qsd_svname, and QTYPE_NAME.
static void qsd_lqe_init (struct lquota_entry * lqe, void * arg) [static]
Definition at line 41 of file qsd_entry.c.
References LASSERT, lqe_is_master(), and lquota_entry::lqe_nopreacq.
static int qsd_lqe_read (const struct lu_env * env, struct lquota_entry * lqe, void * arg) [static]
Definition at line 64 of file qsd_entry.c.
References LASSERT, lquota_entry::lqe_enforced, lquota_entry::lqe_granted, lquota_entry::lqe_id, lqe_is_master(), LQUOTA_DEBUG, lquota_disk_read(), LQUOTA_ERROR, qsd_qtype_info::qqi_glb_obj, qsd_qtype_info::qqi_slv_obj, qsd_info(), qsd_refresh_usage(), and qsd_set_qunit().
int qsd_refresh_usage (const struct lu_env * env, struct lquota_entry * lqe)
Definition at line 186 of file qsd_entry.c.
References ENTRY, LASSERT, LPU64, lqe2qqi(), lquota_entry::lqe_id, LQUOTA_DEBUG, lquota_disk_read(), LQUOTA_ERROR, qsd_qtype_info::qqi_acct_obj, qsd_qtype_info::qqi_qsd, qsd_info(), qsd_instance::qsd_is_md, RETURN, and toqb.
Referenced by qsd_acquire(), qsd_lqe_read(), qsd_op_adjust(), qsd_op_begin0(), qsd_op_end0(), qsd_process_upd(), qsd_reconciliation(), and qsd_upd_thread().
int qsd_update_index (const struct lu_env * env, struct qsd_qtype_info * qqi, union lquota_id * qid, bool global, __u64 ver, void * rec)
Definition at line 233 of file qsd_entry.c.
References __u64, CDEBUG, CERROR, D_QUOTA, dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), ENTRY, EXIT, GOTO, LPU64, lquota_disk_declare_write(), lquota_disk_write(), LQUOTA_SET_VER, lquota_glb_rec::qbr_hardlimit, lquota_glb_rec::qbr_softlimit, lquota_id::qid_uid, qsd_qtype_info::qqi_glb_obj, qsd_qtype_info::qqi_qsd, qsd_qtype_info::qqi_slv_obj, qsd_bump_version(), qsd_instance::qsd_dev, qsd_instance::qsd_svname, lquota_slv_rec::qsr_granted, and RETURN.
Referenced by qsd_process_upd(), and qsd_reint_qid().
int qsd_update_lqe (const struct lu_env * env, struct lquota_entry * lqe, bool global, void * rec)
Definition at line 309 of file qsd_entry.c.
References ENTRY, LASSERT, LPU64, lquota_entry::lqe_enforced, lquota_entry::lqe_granted, lqe_is_master(), LQUOTA_DEBUG, lquota_glb_rec::qbr_hardlimit, lquota_glb_rec::qbr_softlimit, lquota_slv_rec::qsr_granted, and RETURN.
Referenced by qsd_process_upd(), and qsd_reint_qid().
int qsd_write_version (const struct lu_env * env, struct qsd_qtype_info * qqi, __u64 ver, bool global)
Definition at line 161 of file qsd_entry.c.
References ENTRY, lquota_disk_update_ver(), qsd_qtype_info::qqi_glb_obj, qsd_qtype_info::qqi_qsd, qsd_qtype_info::qqi_slv_obj, qsd_bump_version(), qsd_instance::qsd_dev, and RETURN.
Referenced by qsd_reint_index().
Variable Documentation
struct lquota_entry_operations qsd_lqe_ops
Initial value:
 {
        .lqe_init               = qsd_lqe_init,
        .lqe_read               = qsd_lqe_read,
        .lqe_debug              = qsd_lqe_debug,
}
Definition at line 155 of file qsd_entry.c.
Referenced by qsd_qtype_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.