Lustre: lustre/quota/qsd_lock.c File Reference
lustre/quota/qsd_lock.c File Reference
#include <lustre_dlm.h>
#include <obd_class.h>
#include "qsd_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LQUOTA
Typedefs
typedef int(enqi_bl_cb_t)(struct ldlm_lock *lock, struct ldlm_lock_desc *desc, void *data, int flag)
typedef int(enqi_gl_cb_t)(struct ldlm_lock *lock, void *data)
Functions
static struct qsd_qtype_info * qsd_glb_ast_data_get (struct ldlm_lock *lock, bool reset)
static struct lquota_entry * qsd_id_ast_data_get (struct ldlm_lock *lock, bool reset)
static int qsd_common_glimpse_ast (struct ptlrpc_request *req, struct ldlm_gl_lquota_desc **desc, void **lvb)
static int qsd_glb_blocking_ast (struct ldlm_lock *lock, struct ldlm_lock_desc *desc, void *data, int flag)
static int qsd_glb_glimpse_ast (struct ldlm_lock *lock, void *data)
static int qsd_id_blocking_ast (struct ldlm_lock *lock, struct ldlm_lock_desc *desc, void *data, int flag)
Blocking callback handler for per-ID lock.
static int qsd_id_glimpse_ast (struct ldlm_lock *lock, void *data)
int qsd_id_lock_match (struct lustre_handle *lockh, struct lustre_handle *rlockh)
Check whether a slave already own a ldlm lock for the quota identifier .
int qsd_id_lock_cancel (const struct lu_env *env, struct lquota_entry *lqe)
Variables
static enqi_bl_cb_t qsd_glb_blocking_ast
static enqi_bl_cb_t qsd_id_blocking_ast
static enqi_gl_cb_t qsd_glb_glimpse_ast
static enqi_gl_cb_t qsd_id_glimpse_ast
struct ldlm_enqueue_info qsd_glb_einfo
struct ldlm_enqueue_info qsd_id_einfo
Define Documentation
#define DEBUG_SUBSYSTEM S_LQUOTA
Definition at line 31 of file qsd_lock.c.
Typedef Documentation
typedef int(enqi_bl_cb_t)(struct ldlm_lock *lock, struct ldlm_lock_desc *desc, void *data, int flag)
Definition at line 38 of file qsd_lock.c.
typedef int(enqi_gl_cb_t)(struct ldlm_lock *lock, void *data)
Definition at line 43 of file qsd_lock.c.
Function Documentation
static int qsd_common_glimpse_ast (struct ptlrpc_request * req, struct ldlm_gl_lquota_desc ** desc, void ** lvb) [static]
Definition at line 135 of file qsd_lock.c.
References CERROR, ENTRY, LASSERT, LDLM_GL_CALLBACK, lustre_msg_get_opc(), RCL_SERVER, req_capsule_client_get(), req_capsule_extend(), req_capsule_server_get(), req_capsule_server_pack(), req_capsule_set_size(), RETURN, RMF_DLM_GL_DESC, RMF_DLM_LVB, ptlrpc_request::rq_pill, ptlrpc_request::rq_reqmsg, and RQF_LDLM_GL_DESC_CALLBACK.
Referenced by qsd_glb_glimpse_ast(), and qsd_id_glimpse_ast().
static struct qsd_qtype_info* qsd_glb_ast_data_get (struct ldlm_lock * lock, bool reset) [static, read]
Definition at line 68 of file qsd_lock.c.
References ENTRY, ldlm_lock::l_ast_data, lock_res_and_lock(), lu_ref_add(), lu_ref_del(), qqi_getref(), qqi_putref(), qsd_qtype_info::qqi_reference, RETURN, and unlock_res_and_lock().
Referenced by qsd_glb_blocking_ast(), and qsd_glb_glimpse_ast().
static int qsd_glb_blocking_ast (struct ldlm_lock * lock, struct ldlm_lock_desc * desc, void * data, int flag) [static]
Definition at line 176 of file qsd_lock.c.
References CDEBUG, lustre_handle::cookie, D_QUOTA, ENTRY, portals_handle::h_cookie, ldlm_lock::l_handle, LASSERTF, LCF_ASYNC, LDLM_CB_BLOCKING, LDLM_CB_CANCELING, ldlm_cli_cancel(), LDLM_DEBUG, ldlm_is_local_only, ldlm_lock2handle(), lu_ref_del(), qsd_qtype_info::qqi_glb_uptodate, qsd_qtype_info::qqi_lockh, qqi_putref(), qsd_qtype_info::qqi_qsd, qsd_qtype_info::qqi_qtype, qsd_qtype_info::qqi_reference, qsd_qtype_info::qqi_slv_uptodate, qsd_glb_ast_data_get(), qsd_instance::qsd_lock, qsd_start_reint_thread(), qsd_instance::qsd_svname, QTYPE_NAME, and RETURN.
static int qsd_glb_glimpse_ast (struct ldlm_lock * lock, void * data) [static]
Definition at line 236 of file qsd_lock.c.
References CDEBUG, CERROR, D_QUOTA, ELDLM_NO_LOCK_DATA, ENTRY, EXIT, ldlm_gl_lquota_desc::gl_hardlimit, ldlm_gl_lquota_desc::gl_id, ldlm_gl_lquota_desc::gl_softlimit, ldlm_gl_lquota_desc::gl_time, ldlm_gl_lquota_desc::gl_ver, GOTO, LPU64, lu_ref_del(), lquota_glb_rec::qbr_granted, lquota_glb_rec::qbr_hardlimit, lquota_glb_rec::qbr_softlimit, lquota_glb_rec::qbr_time, lquota_id::qid_uid, qqi_putref(), qsd_qtype_info::qqi_qsd, qsd_qtype_info::qqi_reference, qsd_common_glimpse_ast(), qsd_glb_ast_data_get(), qsd_instance::qsd_svname, qsd_upd_schedule(), and ptlrpc_request::rq_status.
static struct lquota_entry* qsd_id_ast_data_get (struct ldlm_lock * lock, bool reset) [static, read]
Definition at line 101 of file qsd_lock.c.
References ENTRY, ldlm_lock::l_ast_data, lock_res_and_lock(), lqe_getref(), lqe_putref(), RETURN, and unlock_res_and_lock().
Referenced by qsd_id_blocking_ast(), and qsd_id_glimpse_ast().
static int qsd_id_blocking_ast (struct ldlm_lock * lock, struct ldlm_lock_desc * desc, void * data, int flag) [static]
Blocking callback handler for per-ID lock.
Parameters:
lock - is the lock for which ast occurred.
desc - is the description of a conflicting lock in case of blocking ast.
data - is the value of lock->l_ast_data
flag - LDLM_CB_BLOCKING or LDLM_CB_CANCELING. Used to distinguish cancellation and blocking ast's.
Definition at line 295 of file qsd_lock.c.
References ENTRY, LASSERTF, LCF_ASYNC, LCT_DT_THREAD, LDLM_CB_BLOCKING, LDLM_CB_CANCELING, ldlm_cli_cancel(), LDLM_DEBUG, ldlm_is_local_only, ldlm_lock2handle(), lqe_putref(), lqe_write_lock(), lqe_write_unlock(), LQUOTA_DEBUG, lu_env_fini(), lu_env_init(), lustre_handle_equal(), OBD_ALLOC_PTR, OBD_FREE_PTR, qsd_adjust(), qsd_id_ast_data_get(), qsd_set_edquot(), qsd_set_qunit(), and RETURN.
static int qsd_id_glimpse_ast (struct ldlm_lock * lock, void * data) [static]
Definition at line 378 of file qsd_lock.c.
References ELDLM_NO_LOCK_DATA, ENTRY, ldlm_gl_lquota_desc::gl_flags, GOTO, LPD64, LPU64, lqe2qqi(), lquota_entry::lqe_granted, lquota_entry::lqe_id, lqe_putref(), lquota_entry::lqe_qunit, lqe_write_lock(), lqe_write_unlock(), LQUOTA_DEBUG, LQUOTA_FL_EDQUOT, qsd_qtype_info::qqi_qsd, qsd_common_glimpse_ast(), qsd_id_ast_data_get(), qsd_set_edquot(), qsd_set_qunit(), qsd_upd_schedule(), RETURN, and ptlrpc_request::rq_status.
int qsd_id_lock_cancel (const struct lu_env * env, struct lquota_entry * lqe)
Definition at line 494 of file qsd_lock.c.
References ldlm_enqueue_info::ei_mode, ENTRY, ldlm_lock_decref_and_cancel(), lquota_entry::lqe_granted, lqe_write_lock(), lqe_write_unlock(), lustre_handle_copy(), lustre_handle_is_used(), qsd_id_lock_match(), qsd_info(), qsd_set_edquot(), qsd_set_qunit(), qsd_thread_info::qti_lockh, and RETURN.
Referenced by qsd_upd_thread().
int qsd_id_lock_match (struct lustre_handle * lockh, struct lustre_handle * rlockh)
Check whether a slave already own a ldlm lock for the quota identifier .
Parameters:
lockh - is the local lock handle from lquota entry.
rlockh - is the remote lock handle of the matched lock, if any.
Return values:
0 : on successful look up and contains the lock handle.
-ENOENT,: no lock found
Definition at line 462 of file qsd_lock.c.
References D_QUOTA, ldlm_enqueue_info::ei_mode, ENTRY, ldlm_lock::l_remote_handle, LASSERT, ldlm_handle2lock(), ldlm_lock_addref_try(), ldlm_lock_dump_handle(), LDLM_LOCK_PUT, lustre_handle_copy(), lustre_handle_is_used(), and RETURN.
Referenced by qsd_acquire_remote(), qsd_adjust(), and qsd_id_lock_cancel().
Variable Documentation
enqi_bl_cb_t qsd_glb_blocking_ast [static]
Definition at line 41 of file qsd_lock.c.
struct ldlm_enqueue_info qsd_glb_einfo
Initial value:
 {
        .ei_type        = LDLM_PLAIN,
        .ei_mode        = LCK_CR,
        .ei_cb_bl       = qsd_glb_blocking_ast,
        .ei_cb_cp       = ldlm_completion_ast,
        .ei_cb_gl       = qsd_glb_glimpse_ast,
}
Definition at line 46 of file qsd_lock.c.
Referenced by qsd_intent_lock(), and qsd_reint_main().
enqi_gl_cb_t qsd_glb_glimpse_ast [static]
Definition at line 44 of file qsd_lock.c.
enqi_bl_cb_t qsd_id_blocking_ast [static]
Definition at line 41 of file qsd_lock.c.
struct ldlm_enqueue_info qsd_id_einfo
Initial value:
 {
        .ei_type        = LDLM_PLAIN,
        .ei_mode        = LCK_CR,
        .ei_cb_bl       = qsd_id_blocking_ast,
        .ei_cb_cp       = ldlm_completion_ast,
        .ei_cb_gl       = qsd_id_glimpse_ast,
}
Definition at line 54 of file qsd_lock.c.
Referenced by qsd_intent_lock(), and qsd_req_completion().
enqi_gl_cb_t qsd_id_glimpse_ast [static]
Definition at line 44 of file qsd_lock.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.