Lustre: lustre/quota/qsd_lib.c File Reference
lustre/quota/qsd_lib.c File Reference
#include <obd_class.h>
#include "qsd_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LQUOTA
Functions
LU_KEY_INIT_FINI (qsd, struct qsd_thread_info)
LU_CONTEXT_KEY_DEFINE (qsd, LCT_MD_THREAD|LCT_DT_THREAD|LCT_LOCAL)
LU_KEY_INIT_GENERIC (qsd)
static int qsd_state_seq_show (struct seq_file *m, void *data)
LPROC_SEQ_FOPS_RO (qsd_state)
static int qsd_enabled_seq_show (struct seq_file *m, void *data)
LPROC_SEQ_FOPS_RO (qsd_enabled)
static ssize_t lprocfs_force_reint_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
LPROC_SEQ_FOPS_WO_TYPE (qsd, force_reint)
static int qsd_timeout_seq_show (struct seq_file *m, void *data)
static ssize_t qsd_timeout_seq_write (struct file *file, const char __user *buffer, size_t count, loff_t *off)
LPROC_SEQ_FOPS (qsd_timeout)
static int qsd_conn_callback (void *data)
static void qsd_qtype_fini (const struct lu_env *env, struct qsd_instance *qsd, int qtype)
static int qsd_qtype_init (const struct lu_env *env, struct qsd_instance *qsd, int qtype)
void qsd_fini (const struct lu_env *env, struct qsd_instance *qsd)
struct qsd_instance * qsd_init (const struct lu_env *env, char *svname, struct dt_device *dev, struct proc_dir_entry *osd_proc)
int qsd_prepare (const struct lu_env *env, struct qsd_instance *qsd)
int qsd_start (const struct lu_env *env, struct qsd_instance *qsd)
void lustre_register_quota_process_config (int(*qpc)(struct lustre_cfg *lcfg))
int qsd_glb_init (void)
void qsd_glb_fini (void)
Variables
struct kmem_cache * upd_kmem
struct lu_kmem_descr qsd_caches []
static struct lprocfs_vars lprocfs_quota_qsd_vars []
Define Documentation
#define DEBUG_SUBSYSTEM S_LQUOTA
Definition at line 52 of file qsd_lib.c.
Function Documentation
LPROC_SEQ_FOPS (qsd_timeout)
LPROC_SEQ_FOPS_RO (qsd_enabled)
LPROC_SEQ_FOPS_RO (qsd_state)
LPROC_SEQ_FOPS_WO_TYPE (qsd , force_reint)
static ssize_t lprocfs_force_reint_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Definition at line 146 of file qsd_lib.c.
References LASSERT, qsd_qtype_info::qqi_glb_uptodate, qsd_qtype_info::qqi_slv_uptodate, qsd_instance::qsd_lock, qsd_instance::qsd_prepared, qsd_start_reint_thread(), qsd_instance::qsd_stopping, and qsd_instance::qsd_type_array.
LU_CONTEXT_KEY_DEFINE (qsd , LCT_MD_THREAD|LCT_DT_THREAD| LCT_LOCAL)
LU_KEY_INIT_FINI (qsd , struct qsd_thread_info)
LU_KEY_INIT_GENERIC (qsd)
void lustre_register_quota_process_config (int(*)(struct lustre_cfg *lcfg) qpc)
Definition at line 1132 of file obd_config.c.
References quota_process_config.
Referenced by qsd_glb_fini(), and qsd_glb_init().
static int qsd_conn_callback (void * data) [static]
Definition at line 232 of file qsd_lib.c.
References class_exp2obd(), ENTRY, LASSERT, obd_device::obd_namespace, qsd_qtype_info::qqi_reint_thread, qsd_instance::qsd_exp, qsd_instance::qsd_exp_valid, qsd_instance::qsd_lock, qsd_instance::qsd_ns, qsd_instance::qsd_type_array, RETURN, and ptlrpc_thread::t_ctl_waitq.
Referenced by qsd_prepare().
static int qsd_enabled_seq_show (struct seq_file * m, void * data) [static]
Definition at line 123 of file qsd_lib.c.
References LASSERT, and qsd_type_enabled().
void qsd_fini (const struct lu_env * env, struct qsd_instance * qsd)
Definition at line 474 of file qsd_lib.c.
References CDEBUG, D_QUOTA, dt_device::dd_lu_dev, dt_object::do_lu, ENTRY, EXIT, lu_device::ld_reference, list_del_init(), lprocfs_remove(), lu_device_put(), lu_object_put(), lu_ref_del(), lustre_deregister_lwp_item(), OBD_FREE_PTR, qsd_fsinfo::qfs_mutex, qsd_instance::qsd_dev, qsd_instance::qsd_exp, qsd_instance::qsd_exp_valid, qsd_instance::qsd_fsinfo, qsd_instance::qsd_link, qsd_instance::qsd_lock, qsd_instance::qsd_ns, qsd_instance::qsd_proc, qsd_put_fsinfo(), qsd_qtype_fini(), qsd_instance::qsd_root, qsd_stop_reint_thread(), qsd_stop_upd_thread(), qsd_instance::qsd_stopping, qsd_instance::qsd_svname, qsd_instance::qsd_type_array, RETURN_EXIT, and unlikely.
Referenced by osd_shutdown(), and qsd_init().
void qsd_glb_fini (void)
Definition at line 827 of file qsd_lib.c.
References lu_context_key_degister(), lu_kmem_fini(), lustre_register_quota_process_config(), and qsd_thread_key.
Referenced by lquota_exit().
int qsd_glb_init (void)
Definition at line 809 of file qsd_lib.c.
References lu_context_key_register(), lu_kmem_init(), lustre_register_quota_process_config(), qsd_process_config(), and qsd_thread_key.
Referenced by lquota_init().
struct qsd_instance* qsd_init (const struct lu_env * env, char * svname, struct dt_device * dev, struct proc_dir_entry * osd_proc) [read]
Definition at line 557 of file qsd_lib.c.
References CERROR, dt_device::dd_lu_dev, ENTRY, EXIT, GOTO, INIT_LIST_HEAD, lu_device::ld_reference, LDD_F_SV_TYPE_MDT, LDD_F_SV_TYPE_OST, list_add_tail(), lprocfs_register(), lu_device_get(), lu_ref_add(), OBD_ALLOC_PTR, qsd_fsinfo::qfs_mutex, qsd_fsinfo::qfs_qsd_list, qsd_instance::qsd_adjust_list, qsd_instance::qsd_adjust_lock, qsd_instance::qsd_dev, QSD_DIR, qsd_fini(), qsd_instance::qsd_fsinfo, qsd_get_fsinfo(), qsd_info(), qsd_instance::qsd_link, qsd_instance::qsd_lock, qsd_instance::qsd_pool_id, qsd_instance::qsd_prepared, qsd_instance::qsd_proc, qsd_instance::qsd_started, qsd_instance::qsd_svname, qsd_instance::qsd_upd_list, qsd_instance::qsd_upd_thread, qsd_thread_info::qti_buf, RETURN, server_name2fsname(), server_name2index(), strlcpy(), SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, and thread_set_flags().
Referenced by osd_device_init0(), and osd_mount().
int qsd_prepare (const struct lu_env * env, struct qsd_instance * qsd)
Definition at line 656 of file qsd_lib.c.
References CERROR, dt_device::dd_lu_dev, ENTRY, LCONSOLE_ERROR, lu_device::ld_site, lquota_disk_dir_find_create(), LQUOTA_LEAST_QUNIT, LQUOTA_RES_DT, LQUOTA_RES_MD, lu_site::ls_top_dev, lu_device_is_md(), lustre_register_lwp_item(), MTI_NAME_MAXLEN, qsd_instance::qsd_acct_failed, qsd_conn_callback(), qsd_instance::qsd_dev, QSD_DIR, qsd_instance::qsd_exp, qsd_info(), qsd_instance::qsd_is_md, qsd_instance::qsd_lock, qsd_instance::qsd_prepared, qsd_qtype_init(), qsd_instance::qsd_root, qsd_start_reint_thread(), qsd_start_upd_thread(), qsd_instance::qsd_svname, qsd_instance::qsd_sync_threshold, qsd_instance::qsd_type_array, qsd_type_enabled(), qsd_thread_info::qti_buf, QTYPE_NAME, RETURN, tgt_name2lwp_name(), and unlikely.
Referenced by osd_prepare().
static void qsd_qtype_fini (const struct lu_env * env, struct qsd_instance * qsd, int qtype) [static]
Definition at line 273 of file qsd_lib.c.
References CDEBUG, cfs_time_seconds(), D_QUOTA, dt_object::do_lu, ENTRY, EXIT, LASSERT, list_empty(), lquota_site_free(), lu_object_put(), lu_ref_fini(), OBD_FREE_PTR, qsd_qtype_info::qqi_acct_obj, qsd_qtype_info::qqi_deferred_glb, qsd_qtype_info::qqi_deferred_slv, qsd_qtype_info::qqi_glb_obj, qsd_qtype_info::qqi_glb_ver, qsd_qtype_info::qqi_ref, qsd_qtype_info::qqi_reference, qsd_qtype_info::qqi_site, qsd_qtype_info::qqi_slv_obj, qsd_qtype_info::qqi_slv_ver, qsd_instance::qsd_type_array, and RETURN_EXIT.
Referenced by qsd_fini(), and qsd_qtype_init().
static int qsd_qtype_init (const struct lu_env * env, struct qsd_instance * qsd, int qtype) [static]
Definition at line 360 of file qsd_lib.c.
References acct_obj_lookup(), CDEBUG, CERROR, D_QUOTA, DFID, dt_version_get(), ENTRY, EXIT, GOTO, INIT_LIST_HEAD, LASSERT, lprocfs_quota_seq_fops, lquota_disk_glb_find_create(), lquota_disk_slv_find_create(), lquota_generate_fid(), lquota_site_alloc(), lu_ref_init(), OBD_ALLOC_PTR, obd_str2uuid(), PFID, qsd_qtype_info::qqi_acct_obj, qsd_qtype_info::qqi_deferred_glb, qsd_qtype_info::qqi_deferred_slv, qsd_qtype_info::qqi_fid, qsd_qtype_info::qqi_glb_obj, qsd_qtype_info::qqi_glb_uptodate, qsd_qtype_info::qqi_glb_ver, qsd_qtype_info::qqi_qsd, qsd_qtype_info::qqi_qtype, qsd_qtype_info::qqi_ref, qsd_qtype_info::qqi_reference, qsd_qtype_info::qqi_reint, qsd_qtype_info::qqi_reint_thread, qsd_qtype_info::qqi_site, qsd_qtype_info::qqi_slv_obj, qsd_qtype_info::qqi_slv_uptodate, qsd_qtype_info::qqi_slv_ver, qsd_instance::qsd_acct_failed, qsd_instance::qsd_dev, qsd_lqe_ops, qsd_instance::qsd_pool_id, qsd_instance::qsd_proc, qsd_qtype_fini(), QSD_RES_TYPE, qsd_instance::qsd_root, qsd_instance::qsd_svname, qsd_instance::qsd_type_array, QTYPE_NAME, RETURN, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, and thread_set_flags().
Referenced by qsd_prepare().
int qsd_start (const struct lu_env * env, struct qsd_instance * qsd)
Definition at line 768 of file qsd_lib.c.
References CERROR, ENTRY, qsd_qtype_info::qqi_reint_thread, qsd_instance::qsd_lock, qsd_instance::qsd_prepared, qsd_instance::qsd_started, qsd_instance::qsd_svname, qsd_instance::qsd_type_array, RETURN, ptlrpc_thread::t_ctl_waitq, and unlikely.
Referenced by osd_recovery_complete().
static int qsd_state_seq_show (struct seq_file * m, void * data) [static]
Definition at line 76 of file qsd_lib.c.
References LASSERT, qsd_qtype_info::qqi_acct_obj, qsd_qtype_info::qqi_glb_uptodate, qsd_qtype_info::qqi_reint, qsd_qtype_info::qqi_slv_uptodate, qsd_instance::qsd_exp_valid, qsd_instance::qsd_is_md, qsd_instance::qsd_pool_id, qsd_instance::qsd_prepared, qsd_instance::qsd_svname, qsd_instance::qsd_type_array, and qsd_type_enabled().
static int qsd_timeout_seq_show (struct seq_file * m, void * data) [static]
Definition at line 183 of file qsd_lib.c.
References LASSERT, and qsd_wait_timeout().
static ssize_t qsd_timeout_seq_write (struct file * file, const char __user * buffer, size_t count, loff_t * off) [static]
Definition at line 193 of file qsd_lib.c.
References LASSERT, qsd_instance::qsd_timeout, and timeout.
Variable Documentation
struct lprocfs_vars lprocfs_quota_qsd_vars[] [static]
Initial value:
 {
        { .name =       "info",
          .fops =       &qsd_state_fops         },
        { .name =       "enabled",
          .fops =       &qsd_enabled_fops       },
        { .name =       "force_reint",
          .fops =       &qsd_force_reint_fops   },
        { .name =       "timeout",
          .fops =       &qsd_timeout_fops       },
        { NULL }
}
Definition at line 212 of file qsd_lib.c.
struct lu_kmem_descr qsd_caches[]
Initial value:
 {
        {
                .ckd_cache = &upd_kmem,
                .ckd_name  = "upd_kmem",
                .ckd_size  = sizeof(struct qsd_upd_rec)
        },
        {
                .ckd_cache = NULL
        }
}
Definition at line 59 of file qsd_lib.c.
struct kmem_cache* upd_kmem
Definition at line 57 of file qsd_lib.c.
Referenced by qsd_upd_alloc(), and qsd_upd_free().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.