Lustre: lustre/quota/qsd_reint.c File Reference
lustre/quota/qsd_reint.c File Reference
#include <linux/kthread.h>
#include <lustre_swab.h>
#include "qsd_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LQUOTA
Functions
static void qsd_reint_completion (const struct lu_env *env, struct qsd_qtype_info *qqi, struct quota_body *req_qbody, struct quota_body *rep_qbody, struct lustre_handle *lockh, struct lquota_lvb *lvb, void *arg, int rc)
static int qsd_reint_qid (const struct lu_env *env, struct qsd_qtype_info *qqi, bool global, union lquota_id *qid, void *rec)
static int qsd_reint_entries (const struct lu_env *env, struct qsd_qtype_info *qqi, struct idx_info *ii, bool global, struct page **pages, unsigned int npages, bool need_swab)
static int qsd_reint_index (const struct lu_env *env, struct qsd_qtype_info *qqi, bool global)
static int qsd_reconciliation (const struct lu_env *env, struct qsd_qtype_info *qqi)
static int qsd_connected (struct qsd_instance *qsd)
static int qsd_started (struct qsd_instance *qsd)
static int qsd_reint_main (void *args)
void qsd_stop_reint_thread (struct qsd_qtype_info *qqi)
static int qsd_entry_iter_cb (struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode, void *data)
static bool qsd_pending_updates (struct qsd_qtype_info *qqi)
int qsd_start_reint_thread (struct qsd_qtype_info *qqi)
Define Documentation
#define DEBUG_SUBSYSTEM S_LQUOTA
Definition at line 31 of file qsd_reint.c.
Function Documentation
static int qsd_connected (struct qsd_instance * qsd) [static]
Definition at line 382 of file qsd_reint.c.
References qsd_instance::qsd_exp_valid, and qsd_instance::qsd_lock.
Referenced by qsd_reint_main().
static int qsd_entry_iter_cb (struct cfs_hash * hs, struct cfs_hash_bd * bd, struct hlist_node * hnode, void * data) [static]
Definition at line 558 of file qsd_reint.c.
References hlist_entry, LASSERT, lquota_entry::lqe_hash, lqe_read_lock(), lqe_read_unlock(), and lquota_entry::lqe_ref.
Referenced by qsd_pending_updates().
static bool qsd_pending_updates (struct qsd_qtype_info * qqi) [static]
Definition at line 574 of file qsd_reint.c.
References CDEBUG, CERROR, cfs_hash_for_each_safe(), D_QUOTA, ENTRY, EXIT, GOTO, list_del_init(), list_for_each_entry, list_for_each_entry_safe, lqe2qqi(), lquota_entry::lqe_link, lqe_putref(), lquota_site::lqs_hash, qsd_qtype_info::qqi_qsd, qsd_qtype_info::qqi_qtype, qsd_qtype_info::qqi_site, qsd_instance::qsd_adjust_list, qsd_instance::qsd_adjust_lock, qsd_entry_iter_cb(), qsd_instance::qsd_lock, qsd_instance::qsd_svname, qsd_instance::qsd_upd_list, qsd_upd_rec::qur_global, and qsd_upd_rec::qur_qqi.
Referenced by qsd_start_reint_thread().
static int qsd_reconciliation (const struct lu_env * env, struct qsd_qtype_info * qqi) [static]
Definition at line 294 of file qsd_reint.c.
References __u64, CWARN, DFID, dt_index_operations::dio_it, dt_object::do_index_ops, dt_key, ENTRY, GOTO, dt_index_operations::dt_it_ops::init, LASSERT, lqe_locate(), lqe_putref(), PFID, lquota_id::qid_uid, qsd_qtype_info::qqi_fid, qsd_qtype_info::qqi_glb_obj, qsd_qtype_info::qqi_qsd, qsd_qtype_info::qqi_site, qsd_adjust(), qsd_info(), qsd_refresh_usage(), qsd_instance::qsd_svname, qsd_thread_info::qti_id, and RETURN.
Referenced by qsd_reint_main().
static void qsd_reint_completion (const struct lu_env * env, struct qsd_qtype_info * qqi, struct quota_body * req_qbody, struct quota_body * rep_qbody, struct lustre_handle * lockh, struct lquota_lvb * lvb, void * arg, int rc) [static]
Definition at line 40 of file qsd_reint.c.
References __u64, CDEBUG, CDEBUG_LIMIT, D_ERROR, D_QUOTA, DFID, ENTRY, EXIT, LPU64, lustre_handle_copy(), PFID, quota_body::qb_fid, quota_body::qb_slv_ver, qsd_qtype_info::qqi_lockh, qsd_qtype_info::qqi_qsd, qsd_qtype_info::qqi_slv_fid, qsd_instance::qsd_svname, and RETURN_EXIT.
Referenced by qsd_reint_main().
static int qsd_reint_entries (const struct lu_env * env, struct qsd_qtype_info * qqi, struct idx_info * ii, bool global, struct page ** pages, unsigned int npages, bool need_swab) [static]
Definition at line 96 of file qsd_reint.c.
References __swab64s, __u64, CDEBUG, CERROR, D_QUOTA, ENTRY, GOTO, idx_info::ii_keysize, idx_info::ii_recsize, lu_idxpage::lip_entries, LIP_MAGIC, lu_idxpage::lip_magic, lu_idxpage::lip_nr, lu_page::lp_idx, LU_PAGE_COUNT, lustre_swab_lip_header(), lquota_id::qid_uid, qsd_qtype_info::qqi_qsd, qsd_info(), qsd_reint_qid(), qsd_instance::qsd_svname, qsd_thread_info::qti_id, RETURN, and size.
Referenced by qsd_reint_index().
static int qsd_reint_index (const struct lu_env * env, struct qsd_qtype_info * qqi, bool global) [static]
Definition at line 181 of file qsd_reint.c.
References __u64, CDEBUG, CERROR, CWARN, D_QUOTA, DFID, ENTRY, GOTO, IDX_INFO_MAGIC, idx_info::ii_count, II_END_OFF, idx_info::ii_fid, II_FL_NOHASH, II_FL_NONUNQ, II_FL_VARKEY, idx_info::ii_flags, idx_info::ii_hash_end, idx_info::ii_hash_start, idx_info::ii_keysize, idx_info::ii_magic, idx_info::ii_version, LPU64, LU_PAGE_COUNT, LU_PAGE_SHIFT, min_t, OBD_ALLOC, OBD_FREE, OFD_MAX_BRW_SIZE, PFID, qsd_qtype_info::qqi_fid, qsd_qtype_info::qqi_qsd, qsd_qtype_info::qqi_slv_fid, qsd_instance::qsd_exp, qsd_fetch_index(), qsd_info(), qsd_reint_entries(), qsd_instance::qsd_svname, qsd_write_version(), qsd_thread_info::qti_ii, and RETURN.
Referenced by qsd_reint_main().
static int qsd_reint_main (void * args) [static]
Definition at line 407 of file qsd_reint.c.
References CDEBUG, CWARN, D_QUOTA, DFID, ldlm_enqueue_info::ei_mode, ENTRY, EXIT, GOTO, IT_QUOTA_CONN, l_wait_event, LASSERT, LCT_DT_THREAD, ldlm_lock_addref_try(), ldlm_lock_decref(), LPU64, lu_env_fini(), lu_env_init(), lu_ref_add(), lu_ref_del(), lustre_handle_is_used(), OBD_ALLOC_PTR, OBD_FAIL_QUOTA_DELAY_REINT, OBD_FAIL_TIMEOUT, OBD_FREE_PTR, PFID, quota_body::qb_fid, qsd_qtype_info::qqi_fid, qqi_getref(), qsd_qtype_info::qqi_glb_uptodate, qsd_qtype_info::qqi_glb_ver, qsd_qtype_info::qqi_lockh, qqi_putref(), qsd_qtype_info::qqi_qsd, qsd_qtype_info::qqi_reference, qsd_qtype_info::qqi_reint, qsd_qtype_info::qqi_reint_thread, qsd_qtype_info::qqi_slv_fid, qsd_qtype_info::qqi_slv_uptodate, qsd_qtype_info::qqi_slv_ver, qsd_bump_version(), qsd_connected(), qsd_instance::qsd_exp, qsd_glb_einfo, qsd_info(), qsd_intent_lock(), qsd_instance::qsd_lock, qsd_reconciliation(), qsd_reint_completion(), qsd_reint_index(), qsd_started(), qsd_instance::qsd_svname, qsd_thread_info::qti_body, qsd_thread_info::qti_lvb, qsd_thread_info::qti_slv_ver, SVC_RUNNING, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, thread, thread_is_running(), and thread_set_flags().
Referenced by qsd_start_reint_thread().
static int qsd_reint_qid (const struct lu_env * env, struct qsd_qtype_info * qqi, bool global, union lquota_id * qid, void * rec) [static]
Definition at line 73 of file qsd_reint.c.
References ENTRY, GOTO, lqe_locate(), lqe_putref(), LQUOTA_DEBUG, qsd_qtype_info::qqi_site, qsd_update_index(), qsd_update_lqe(), and RETURN.
Referenced by qsd_reint_entries().
int qsd_start_reint_thread (struct qsd_qtype_info * qqi)
Definition at line 624 of file qsd_reint.c.
References ENTRY, l_wait_event, MTI_NAME_MAXLEN, name, OBD_ALLOC, OBD_FREE, qsd_qtype_info::qqi_glb_uptodate, qsd_qtype_info::qqi_qsd, qsd_qtype_info::qqi_qtype, qsd_qtype_info::qqi_reint, qsd_qtype_info::qqi_reint_thread, qsd_qtype_info::qqi_slv_uptodate, qsd_instance::qsd_acct_failed, qsd_instance::qsd_lock, qsd_pending_updates(), qsd_reint_main(), qsd_instance::qsd_stopping, qsd_instance::qsd_svname, qsd_type_enabled(), RETURN, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, thread, thread_is_running(), thread_is_stopped(), and thread_set_flags().
Referenced by lprocfs_force_reint_seq_write(), qsd_glb_blocking_ast(), qsd_prepare(), qsd_process_config(), qsd_ready(), and qsd_upd_thread().
static int qsd_started (struct qsd_instance * qsd) [static]
Definition at line 393 of file qsd_reint.c.
References qsd_instance::qsd_lock, and qsd_instance::qsd_started.
Referenced by qsd_reint_main().
void qsd_stop_reint_thread (struct qsd_qtype_info * qqi)
Definition at line 544 of file qsd_reint.c.
References l_wait_event, qsd_qtype_info::qqi_reint_thread, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, thread, thread_is_stopped(), and thread_set_flags().
Referenced by qsd_fini().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.