Lustre: lustre/llite/range_lock.h File Reference
lustre/llite/range_lock.h File Reference
#include <libcfs/libcfs.h>
#include <interval_tree.h>
Data Structures
struct range_lock
struct range_lock_tree
Defines
#define RL_FMT "["LPU64", "LPU64"]"
#define RL_PARA(range)
Functions
static struct range_lock * node2rangelock (const struct interval_node *n)
void range_lock_tree_init (struct range_lock_tree *tree)
Initialize a range lock tree.
void range_lock_init (struct range_lock *lock, __u64 start, __u64 end)
Intialize a range lock node.
int range_lock (struct range_lock_tree *tree, struct range_lock *lock)
Lock a region.
void range_unlock (struct range_lock_tree *tree, struct range_lock *lock)
Unlock a range lock, wake up locks blocked by this lock.
Define Documentation
#define RL_FMT "["LPU64", "LPU64"]"
Definition at line 42 of file range_lock.h.
Referenced by ll_file_io_generic().
#define RL_PARA (range)
Value:
(range)->rl_node.in_extent.start,       \
        (range)->rl_node.in_extent.end
Definition at line 43 of file range_lock.h.
Referenced by ll_file_io_generic().
Function Documentation
static struct range_lock* node2rangelock (const struct interval_node * n) [static, read]
Definition at line 72 of file range_lock.h.
References range_lock::rl_node.
Referenced by range_lock(), range_lock_cb(), and range_unlock_cb().
int range_lock (struct range_lock_tree * tree, struct range_lock * lock)
Lock a region.
Parameters:
tree [in] range lock tree
lock [in] range lock node containing the region span
Return values:
0 get the range lock
<0 error code while not getting the range lock
If there exists overlapping range lock, the new lock will wait and retry, if later it find that it is not the chosen one to wake up, it wait again.
Definition at line 196 of file range_lock.c.
References ENTRY, GOTO, interval_node::in_extent, interval_insert(), interval_search(), list_add_tail(), node2rangelock(), range_lock_cb(), range_unlock(), RETURN, range_lock::rl_blocking_ranges, range_lock::rl_lock_count, range_lock::rl_next_lock, range_lock::rl_node, range_lock::rl_sequence, range_lock::rl_task, range_lock_tree::rlt_lock, range_lock_tree::rlt_root, and range_lock_tree::rlt_sequence.
Referenced by ll_file_io_generic().
void range_lock_init (struct range_lock * lock, __u64 start, __u64 end)
Intialize a range lock node.
Parameters:
lock [in] an empty range lock node
start [in] start of the covering region
end [in] end of the covering region
Pre: Caller should have allocated the range lock node. Post: The range lock node is meant to cover [start, end] region
Definition at line 64 of file range_lock.c.
References INIT_LIST_HEAD, interval_init(), interval_set(), LUSTRE_EOF, range_lock::rl_blocking_ranges, range_lock::rl_lock_count, range_lock::rl_next_lock, range_lock::rl_node, range_lock::rl_sequence, and range_lock::rl_task.
Referenced by ll_file_io_generic().
void range_lock_tree_init (struct range_lock_tree * tree)
Initialize a range lock tree.
Parameters:
tree [in] an empty range lock tree
Pre: Caller should have allocated the range lock tree. Post: The range lock tree is ready to function.
Definition at line 47 of file range_lock.c.
References range_lock_tree::rlt_lock, range_lock_tree::rlt_root, and range_lock_tree::rlt_sequence.
Referenced by ll_lli_init().
void range_unlock (struct range_lock_tree * tree, struct range_lock * lock)
Unlock a range lock, wake up locks blocked by this lock.
Parameters:
tree [in] range lock tree
lock [in] range lock to be deleted
If this lock has been granted, relase it; if not, just delete it from the tree or the same region lock list. Wake up those locks only blocked by this lock through range_unlock_cb().
Definition at line 124 of file range_lock.c.
References ENTRY, EXIT, interval_node::in_extent, interval_erase(), interval_insert(), interval_is_intree(), interval_search(), LASSERT, list_del_init(), list_empty(), list_for_each_entry, next_lock(), range_unlock_cb(), range_lock::rl_lock_count, range_lock::rl_next_lock, range_lock::rl_node, range_lock_tree::rlt_lock, and range_lock_tree::rlt_root.
Referenced by ll_file_io_generic(), and range_lock().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.