Lustre: lustre/ptlrpc/recover.c File Reference
lustre/ptlrpc/recover.c File Reference
#include <libcfs/libcfs.h>
#include <obd_support.h>
#include <lustre_ha.h>
#include <lustre_net.h>
#include <lustre_import.h>
#include <lustre_export.h>
#include <obd.h>
#include <obd_class.h>
#include <libcfs/list.h>
#include "ptlrpc_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_RPC
Functions
void ptlrpc_initiate_recovery (struct obd_import *imp)
Start recovery on disconnected import.
int ptlrpc_replay_next (struct obd_import *imp, int *inflight)
Identify what request from replay list needs to be replayed next (based on what we have already replayed) and send it to server.
int ptlrpc_resend (struct obd_import *imp)
Schedule resending of request on sending_list.
void ptlrpc_wake_delayed (struct obd_import *imp)
Go through all requests in delayed list and wake their threads for resending.
void ptlrpc_request_handle_notconn (struct ptlrpc_request *failed_req)
int ptlrpc_set_import_active (struct obd_import *imp, int active)
Administratively active/deactive a client.
int ptlrpc_recover_import (struct obd_import *imp, char *new_uuid, int async)
int ptlrpc_import_in_recovery (struct obd_import *imp)
Define Documentation
#define DEBUG_SUBSYSTEM S_RPC
Definition at line 41 of file recover.c.
Function Documentation
int ptlrpc_import_in_recovery (struct obd_import * imp)
Definition at line 393 of file recover.c.
References obd_import::imp_lock, obd_import::imp_obd, obd_import::imp_state, LUSTRE_IMP_CLOSED, LUSTRE_IMP_DISCON, LUSTRE_IMP_FULL, and obd_device::obd_no_recov.
Referenced by ptlrpc_disconnect_import(), ptlrpc_reconnect_import(), and ptlrpc_recover_import().
void ptlrpc_initiate_recovery (struct obd_import * imp)
Start recovery on disconnected import.
This is done by just attempting a connect
Definition at line 58 of file recover.c.
References CDEBUG, D_HA, ENTRY, EXIT, obd_import::imp_obd, obd2cli_tgt, and ptlrpc_connect_import().
Referenced by ptlrpc_pinger_process_import().
int ptlrpc_replay_next (struct obd_import * imp, int * inflight)
Identify what request from replay list needs to be replayed next (based on what we have already replayed) and send it to server.
Definition at line 72 of file recover.c.
References __u64, CDEBUG, CERROR, D_HA, ENTRY, obd_import::imp_committed_list, obd_import::imp_last_replay_transno, obd_import::imp_last_transno_checked, obd_import::imp_lock, obd_import::imp_obd, obd_import::imp_peer_committed_transno, obd_import::imp_replay_cursor, obd_import::imp_replay_list, obd_import::imp_resend_replay, LASSERT, list_empty(), list_entry, list_for_each_safe, LPU64, lustre_msg_add_flags(), MSG_RESENT, list_head::next, obd2cli_tgt, list_head::prev, ptlrpc_add_unreplied(), ptlrpc_free_committed(), ptlrpc_replay_req(), RETURN, ptlrpc_request::rq_replay_list, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_transno, and ptlrpc_request::rq_xid.
Referenced by ptlrpc_import_recovery_state_machine().
void ptlrpc_request_handle_notconn (struct ptlrpc_request * failed_req)
Definition at line 249 of file recover.c.
References ptlrpc_connection::c_remote_uuid, CDEBUG, D_HA, ENTRY, EXIT, obd_import::imp_connection, obd_import::imp_deactive, obd_import::imp_obd, obd_import::imp_replayable, lustre_msg_get_conn_cnt(), obd2cli_tgt, obd_device::obd_name, ptlrpc_connect_import(), ptlrpc_deactivate_import(), ptlrpc_set_import_discon(), ptlrpc_request::rq_import, ptlrpc_request::rq_lock, ptlrpc_request::rq_no_resend, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_resend, and obd_uuid::uuid.
Referenced by after_reply().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.