Lustre: lustre/llite/remote_perm.c File Reference
lustre/llite/remote_perm.c File Reference
#include <linux/module.h>
#include <linux/types.h>
#include <linux/version.h>
#include <linux/user_namespace.h>
#include <lustre_dlm.h>
#include <lustre_ha.h>
#include <lustre_param.h>
#include <lustre_swab.h>
#include <lprocfs_status.h>
#include <lustre_disk.h>
#include "llite_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LLITE
Functions
static struct ll_remote_perm * alloc_ll_remote_perm (void)
static void free_ll_remote_perm (struct ll_remote_perm *lrp)
static struct hlist_head * alloc_rmtperm_hash (void)
void free_rmtperm_hash (struct hlist_head *hash)
static int remote_perm_hashfunc (uid_t uid)
static int do_check_remote_perm (struct ll_inode_info *lli, int mask)
int ll_update_remote_perm (struct inode *inode, struct mdt_remote_perm *perm)
int lustre_check_remote_perm (struct inode *inode, int mask)
Variables
struct kmem_cache * ll_remote_perm_cachep
struct kmem_cache * ll_rmtperm_hash_cachep
Define Documentation
#define DEBUG_SUBSYSTEM S_LLITE
Definition at line 44 of file remote_perm.c.
Function Documentation
static struct ll_remote_perm* alloc_ll_remote_perm (void) [static, read]
Definition at line 66 of file remote_perm.c.
References INIT_HLIST_NODE, ll_remote_perm_cachep, ll_remote_perm::lrp_list, and OBD_SLAB_ALLOC_PTR_GFP.
Referenced by ll_update_remote_perm().
static struct hlist_head* alloc_rmtperm_hash (void) [static, read]
Definition at line 86 of file remote_perm.c.
References INIT_HLIST_HEAD, ll_rmtperm_hash_cachep, OBD_SLAB_ALLOC_GFP, and REMOTE_PERM_HASHSIZE.
Referenced by ll_update_remote_perm().
static int do_check_remote_perm (struct ll_inode_info * lli, int mask) [static]
Definition at line 128 of file remote_perm.c.
References CDEBUG, cfs_hlist_for_each_entry, D_SEC, ENTRY, from_kgid(), from_kuid(), GOTO, head, ll_inode_info::lli_lock, ll_inode_info::lli_remote_perms, ll_remote_perm::lrp_access_perm, ll_remote_perm::lrp_fsgid, ll_remote_perm::lrp_fsuid, ll_remote_perm::lrp_gid, ll_remote_perm::lrp_uid, remote_perm_hashfunc(), and RETURN.
Referenced by lustre_check_remote_perm().
static void free_ll_remote_perm (struct ll_remote_perm * lrp) [inline, static]
Definition at line 76 of file remote_perm.c.
References hlist_del(), hlist_unhashed(), ll_remote_perm_cachep, ll_remote_perm::lrp_list, and OBD_SLAB_FREE.
Referenced by free_rmtperm_hash(), and ll_update_remote_perm().
void free_rmtperm_hash (struct hlist_head * hash)
Definition at line 103 of file remote_perm.c.
References cfs_hlist_for_each_entry_safe, free_ll_remote_perm(), ll_rmtperm_hash_cachep, hlist_node::next, OBD_SLAB_FREE, and REMOTE_PERM_HASHSIZE.
Referenced by ll_clear_inode(), and ll_update_remote_perm().
int ll_update_remote_perm (struct inode * inode, struct mdt_remote_perm * perm)
Definition at line 169 of file remote_perm.c.
References alloc_ll_remote_perm(), alloc_rmtperm_hash(), CDEBUG, CERROR, cfs_hlist_for_each_entry, cfs_time_current(), D_SEC, ENTRY, free_ll_remote_perm(), free_rmtperm_hash(), head, hlist_add_head(), LASSERT, ll_i2info(), ll_i2sbi(), LL_SBI_RMT_CLIENT, ll_inode_info::lli_lock, ll_inode_info::lli_remote_perms, ll_inode_info::lli_rmtperm_time, ll_remote_perm::lrp_access_perm, ll_remote_perm::lrp_fsgid, ll_remote_perm::lrp_fsuid, ll_remote_perm::lrp_gid, ll_remote_perm::lrp_list, ll_remote_perm::lrp_uid, remote_perm_hashfunc(), RETURN, mdt_remote_perm::rp_access_perm, mdt_remote_perm::rp_fsgid, mdt_remote_perm::rp_fsuid, mdt_remote_perm::rp_gid, and mdt_remote_perm::rp_uid.
Referenced by ll_update_inode(), and lustre_check_remote_perm().
int lustre_check_remote_perm (struct inode * inode, int mask)
Definition at line 256 of file remote_perm.c.
References CERROR, do_check_remote_perm(), ENTRY, LBUG, ll_i2info(), ll_i2sbi(), ll_i2suppgid(), ll_inode2fid(), ll_sb_info::ll_md_exp, ll_update_remote_perm(), ll_inode_info::lli_rmtperm_mutex, ll_inode_info::lli_rmtperm_time, lustre_swab_mdt_remote_perm(), md_get_remote_perm(), ptlrpc_req_finished(), req_capsule_server_swab_get(), RETURN, RMF_ACL, ptlrpc_request::rq_pill, and unlikely.
Referenced by ll_inode_permission().
static int remote_perm_hashfunc (uid_t uid) [inline, static]
Definition at line 121 of file remote_perm.c.
References REMOTE_PERM_HASHSIZE.
Referenced by do_check_remote_perm(), and ll_update_remote_perm().
Variable Documentation
struct kmem_cache* ll_remote_perm_cachep
Definition at line 63 of file remote_perm.c.
Referenced by alloc_ll_remote_perm(), free_ll_remote_perm(), lustre_exit(), and lustre_init().
struct kmem_cache* ll_rmtperm_hash_cachep
Definition at line 64 of file remote_perm.c.
Referenced by alloc_rmtperm_hash(), free_rmtperm_hash(), lustre_exit(), and lustre_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.