Lustre: lnet/lnet/router.c File Reference
lnet/lnet/router.c File Reference
#include <lnet/lib-lnet.h>
Defines
#define DEBUG_SUBSYSTEM S_LNET
#define LNET_NRB_TINY_MIN 512
#define LNET_NRB_TINY (LNET_NRB_TINY_MIN * 4)
#define LNET_NRB_SMALL_MIN 4096
#define LNET_NRB_SMALL (LNET_NRB_SMALL_MIN * 4)
#define LNET_NRB_SMALL_PAGES 1
#define LNET_NRB_LARGE_MIN 256
#define LNET_NRB_LARGE (LNET_NRB_LARGE_MIN * 4)
#define LNET_NRB_LARGE_PAGES
Functions
module_param (forwarding, charp, 0444)
MODULE_PARM_DESC (forwarding,"Explicitly enable/disable forwarding between networks")
module_param (tiny_router_buffers, int, 0444)
MODULE_PARM_DESC (tiny_router_buffers,"# of 0 payload messages to buffer in the router")
module_param (small_router_buffers, int, 0444)
MODULE_PARM_DESC (small_router_buffers,"# of small (1 page) messages to buffer in the router")
module_param (large_router_buffers, int, 0444)
MODULE_PARM_DESC (large_router_buffers,"# of large messages to buffer in the router")
module_param (peer_buffer_credits, int, 0444)
MODULE_PARM_DESC (peer_buffer_credits,"# router buffer credits per peer")
module_param (auto_down, int, 0444)
MODULE_PARM_DESC (auto_down,"Automatically mark peers down on comms error")
int lnet_peer_buffer_credits (lnet_ni_t *ni)
static int lnet_router_checker (void *)
module_param (check_routers_before_use, int, 0444)
MODULE_PARM_DESC (check_routers_before_use,"Assume routers are down and ping them before use")
module_param (avoid_asym_router_failure, int, 0644)
MODULE_PARM_DESC (avoid_asym_router_failure,"Avoid asymmetrical router failures (0 to disable)")
module_param (dead_router_check_interval, int, 0644)
MODULE_PARM_DESC (dead_router_check_interval,"Seconds between dead router health checks (<= 0 to disable)")
module_param (live_router_check_interval, int, 0644)
MODULE_PARM_DESC (live_router_check_interval,"Seconds between live router health checks (<= 0 to disable)")
module_param (router_ping_timeout, int, 0644)
MODULE_PARM_DESC (router_ping_timeout,"Seconds to wait for the reply to a router health query")
int lnet_peers_start_down (void)
void lnet_notify_locked (lnet_peer_t *lp, int notifylnd, int alive, cfs_time_t when)
static void lnet_ni_notify_locked (lnet_ni_t *ni, lnet_peer_t *lp)
static void lnet_rtr_addref_locked (lnet_peer_t *lp)
static void lnet_rtr_decref_locked (lnet_peer_t *lp)
lnet_remotenet_t * lnet_find_net_locked (__u32 net)
static void lnet_shuffle_seed (void)
static void lnet_add_route_to_rnet (lnet_remotenet_t *rnet, lnet_route_t *route)
int lnet_add_route (__u32 net, __u32 hops, lnet_nid_t gateway, unsigned int priority)
int lnet_check_routes (void)
int lnet_del_route (__u32 net, lnet_nid_t gw_nid)
void lnet_destroy_routes (void)
int lnet_get_rtr_pool_cfg (int idx, struct lnet_ioctl_pool_cfg *pool_cfg)
int lnet_get_route (int idx, __u32 *net, __u32 *hops, lnet_nid_t *gateway, __u32 *alive, __u32 *priority)
void lnet_swap_pinginfo (lnet_ping_info_t *info)
static void lnet_parse_rc_info (lnet_rc_data_t *rcd)
parse router-checker pinginfo, record number of down NIs for remote networks on that router.
static void lnet_router_checker_event (lnet_event_t *event)
static void lnet_wait_known_routerstate (void)
void lnet_router_ni_update_locked (lnet_peer_t *gw, __u32 net)
static void lnet_update_ni_status_locked (void)
static void lnet_destroy_rc_data (lnet_rc_data_t *rcd)
static lnet_rc_data_t * lnet_create_rc_data_locked (lnet_peer_t *gateway)
static int lnet_router_check_interval (lnet_peer_t *rtr)
static void lnet_ping_router_locked (lnet_peer_t *rtr)
int lnet_router_checker_start (void)
void lnet_router_checker_stop (void)
static void lnet_prune_rc_data (int wait_unlink)
static bool lnet_router_checker_active (void)
void lnet_destroy_rtrbuf (lnet_rtrbuf_t *rb, int npages)
static lnet_rtrbuf_t * lnet_new_rtrbuf (lnet_rtrbufpool_t *rbp, int cpt)
static void lnet_rtrpool_free_bufs (lnet_rtrbufpool_t *rbp, int cpt)
static int lnet_rtrpool_adjust_bufs (lnet_rtrbufpool_t *rbp, int nbufs, int cpt)
static void lnet_rtrpool_init (lnet_rtrbufpool_t *rbp, int npages)
void lnet_rtrpools_free (int keep_pools)
static int lnet_nrb_tiny_calculate (void)
static int lnet_nrb_small_calculate (void)
static int lnet_nrb_large_calculate (void)
int lnet_rtrpools_alloc (int im_a_router)
static int lnet_rtrpools_adjust_helper (int tiny, int small, int large)
int lnet_rtrpools_adjust (int tiny, int small, int large)
int lnet_rtrpools_enable (void)
void lnet_rtrpools_disable (void)
int lnet_notify (lnet_ni_t *ni, lnet_nid_t nid, int alive, cfs_time_t when)
Variables
static char * forwarding = ""
static int tiny_router_buffers
static int small_router_buffers
static int large_router_buffers
static int peer_buffer_credits
static int auto_down = 1
static int check_routers_before_use
int avoid_asym_router_failure = 1
static int dead_router_check_interval = 60
static int live_router_check_interval = 60
static int router_ping_timeout = 50
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 23 of file router.c.
#define LNET_NRB_LARGE (LNET_NRB_LARGE_MIN * 4)
Definition at line 32 of file router.c.
Referenced by lnet_nrb_large_calculate().
#define LNET_NRB_LARGE_MIN 256
Definition at line 31 of file router.c.
Referenced by lnet_nrb_large_calculate().
#define LNET_NRB_LARGE_PAGES
Value:
((LNET_MTU + PAGE_CACHE_SIZE - 1) >> \
                                  PAGE_CACHE_SHIFT)
Definition at line 33 of file router.c.
Referenced by lnet_rtrpools_alloc().
#define LNET_NRB_SMALL (LNET_NRB_SMALL_MIN * 4)
Definition at line 29 of file router.c.
Referenced by lnet_nrb_small_calculate().
#define LNET_NRB_SMALL_MIN 4096
Definition at line 28 of file router.c.
Referenced by lnet_nrb_small_calculate().
#define LNET_NRB_SMALL_PAGES 1
Definition at line 30 of file router.c.
Referenced by lnet_rtrpools_alloc().
#define LNET_NRB_TINY (LNET_NRB_TINY_MIN * 4)
Definition at line 27 of file router.c.
Referenced by lnet_nrb_tiny_calculate().
#define LNET_NRB_TINY_MIN 512
Definition at line 26 of file router.c.
Referenced by lnet_nrb_tiny_calculate().
Function Documentation
int lnet_add_route (__u32 net, __u32 hops, lnet_nid_t gateway, unsigned int priority)
Definition at line 296 of file router.c.
References CDEBUG, CERROR, D_NET, INIT_LIST_HEAD, LASSERT, LIBCFS_ALLOC, LIBCFS_FREE, libcfs_net2str(), libcfs_nid2str(), list_add_tail(), list_entry, list_for_each, lnet_t::ln_rc_waitq, lnet_t::ln_shutdown, lnet_lnd::lnd_notify, lnet_add_route_to_rnet(), lnet_find_net_locked(), lnet_islocalnet(), LNET_LOCK_EX, lnet_net2rnethash(), lnet_net_lock(), lnet_net_unlock(), LNET_NETTYP(), lnet_nid2peer_locked(), LNET_NID_ANY, LNET_NIDNET(), lnet_peer_addref_locked(), lnet_peer_decref_locked(), LNET_UNDEFINED_HOPS, LOLND, lnet_peer::lp_ni, lnet_peer::lp_nid, lnet_route_t::lr_gateway, lnet_route_t::lr_hops, lnet_route_t::lr_net, lnet_route_t::lr_priority, lnet_remotenet_t::lrn_list, lnet_remotenet_t::lrn_net, lnet_remotenet_t::lrn_routes, lnet_ni::ni_lnd, and the_lnet.
Referenced by lnet_parse_route(), and LNetCtl().
static void lnet_add_route_to_rnet (lnet_remotenet_t * rnet, lnet_route_t * route) [static]
Definition at line 269 of file router.c.
References cfs_rand(), list_add(), list_for_each, lnet_t::ln_remote_nets_version, lnet_rtr_addref_locked(), lnet_shuffle_seed(), lnet_peer::lp_routes, lnet_route_t::lr_gateway, lnet_route_t::lr_gwlist, lnet_route_t::lr_list, lnet_remotenet_t::lrn_routes, and the_lnet.
Referenced by lnet_add_route().
int lnet_check_routes (void)
Definition at line 415 of file router.c.
References CERROR, libcfs_net2str(), libcfs_nid2str(), list_entry, list_for_each, lnet_t::ln_remote_nets_hash, lnet_net_lock_current(), lnet_net_unlock(), LNET_REMOTE_NETS_HASH_SIZE, lnet_peer::lp_ni, lnet_peer::lp_nid, lnet_route_t::lr_gateway, lnet_remotenet_t::lrn_net, lnet_remotenet_t::lrn_routes, and the_lnet.
Referenced by LNetCtl(), and LNetNIInit().
static lnet_rc_data_t* lnet_create_rc_data_locked (lnet_peer_t * gateway) [static]
Definition at line 899 of file router.c.
References CERROR, INIT_LIST_HEAD, LASSERT, LIBCFS_ALLOC, lnet_t::ln_rc_eqh, lnet_destroy_rc_data(), lnet_isrouter(), LNET_MAX_RTR_NIS, LNET_MD_THRESH_INF, LNET_MD_TRUNCATE, lnet_net_lock(), lnet_net_unlock(), LNET_NI_STATUS_INVALID, LNET_NID_ANY, lnet_peer_addref_locked(), LNET_PINGINFO_SIZE, LNET_UNLINK, LNetHandleIsInvalid(), LNetInvalidateHandle(), LNetMDBind(), LNetMDUnlink(), lnet_peer::lp_cpt, lnet_peer::lp_ping_notsent, lnet_peer::lp_rcd, lnet_rc_data_t::rcd_gateway, lnet_rc_data_t::rcd_list, lnet_rc_data_t::rcd_mdh, lnet_rc_data_t::rcd_pinginfo, and the_lnet.
Referenced by lnet_ping_router_locked().
int lnet_del_route (__u32 net, lnet_nid_t gw_nid)
Definition at line 472 of file router.c.
References CDEBUG, D_NET, LIBCFS_FREE, libcfs_net2str(), libcfs_nid2str(), list_del(), list_empty(), list_entry, list_for_each, lnet_t::ln_remote_nets_hash, lnet_t::ln_remote_nets_version, LNET_LOCK_EX, lnet_net2rnethash(), lnet_net_lock(), lnet_net_unlock(), LNET_NID_ANY, LNET_NIDNET(), lnet_peer_decref_locked(), LNET_REMOTE_NETS_HASH_SIZE, lnet_rtr_decref_locked(), lnet_peer::lp_nid, lnet_route_t::lr_gateway, lnet_route_t::lr_gwlist, lnet_route_t::lr_list, lnet_remotenet_t::lrn_list, lnet_remotenet_t::lrn_net, lnet_remotenet_t::lrn_routes, and the_lnet.
Referenced by lnet_destroy_routes(), lnet_peer_table_del_rtrs_locked(), and LNetCtl().
static void lnet_destroy_rc_data (lnet_rc_data_t * rcd) [static]
Definition at line 878 of file router.c.
References LASSERT, LIBCFS_FREE, list_empty(), lnet_net_lock(), lnet_net_unlock(), lnet_peer_decref_locked(), LNET_PINGINFO_SIZE, LNetHandleIsInvalid(), lnet_peer::lp_cpt, lnet_rc_data_t::rcd_gateway, lnet_rc_data_t::rcd_list, lnet_rc_data_t::rcd_mdh, and lnet_rc_data_t::rcd_pinginfo.
Referenced by lnet_create_rc_data_locked(), and lnet_prune_rc_data().
void lnet_destroy_routes (void)
Definition at line 547 of file router.c.
References lnet_del_route(), LNET_NID_ANY, and LNET_NIDNET().
Referenced by LNetNIFini(), and LNetNIInit().
void lnet_destroy_rtrbuf (lnet_rtrbuf_t * rb, int npages)
Definition at line 1299 of file router.c.
References lnet_kiov_t::kiov_page, LIBCFS_FREE, offsetof, and lnet_rtrbuf_t::rb_kiov.
Referenced by lnet_return_rx_credits_locked(), lnet_rtrpool_adjust_bufs(), and lnet_rtrpool_free_bufs().
lnet_remotenet_t* lnet_find_net_locked (__u32 net)
Definition at line 219 of file router.c.
References LASSERT, list_entry, list_for_each, lnet_t::ln_shutdown, lnet_net2rnethash(), lnet_remotenet_t::lrn_net, and the_lnet.
Referenced by lnet_add_route(), lnet_dyn_add_ni(), and lnet_find_route_locked().
int lnet_get_route (int idx, __u32 * net, __u32 * hops, lnet_nid_t * gateway, __u32 * alive, __u32 * priority)
Definition at line 589 of file router.c.
References list_entry, list_for_each, lnet_t::ln_remote_nets_hash, lnet_is_route_alive(), lnet_net_lock_current(), lnet_net_unlock(), LNET_REMOTE_NETS_HASH_SIZE, lnet_peer::lp_nid, lnet_route_t::lr_gateway, lnet_route_t::lr_hops, lnet_route_t::lr_priority, lnet_remotenet_t::lrn_net, lnet_remotenet_t::lrn_routes, and the_lnet.
Referenced by LNetCtl().
int lnet_get_rtr_pool_cfg (int idx, struct lnet_ioctl_pool_cfg * pool_cfg)
Definition at line 552 of file router.c.
References cfs_percpt_for_each, lnet_t::ln_routing, lnet_t::ln_rtrpools, LNET_LOCK_EX, lnet_net_lock(), lnet_net_unlock(), LNET_NRBPOOLS, lnet_ioctl_pool_cfg::pl_credits, lnet_ioctl_pool_cfg::pl_mincredits, lnet_ioctl_pool_cfg::pl_nbuffers, lnet_ioctl_pool_cfg::pl_npages, lnet_ioctl_pool_cfg::pl_pools, lnet_ioctl_pool_cfg::pl_routing, lnet_rtrbufpool_t::rbp_credits, lnet_rtrbufpool_t::rbp_mincredits, lnet_rtrbufpool_t::rbp_nbuffers, lnet_rtrbufpool_t::rbp_npages, and the_lnet.
Referenced by LNetCtl().
static lnet_rtrbuf_t* lnet_new_rtrbuf (lnet_rtrbufpool_t * rbp, int cpt) [static]
Definition at line 1310 of file router.c.
References cfs_page_cpt_alloc(), lnet_kiov_t::kiov_len, lnet_kiov_t::kiov_offset, lnet_kiov_t::kiov_page, LIBCFS_CPT_ALLOC, LIBCFS_FREE, lnet_cpt_table, offsetof, lnet_rtrbuf_t::rb_kiov, lnet_rtrbuf_t::rb_pool, and lnet_rtrbufpool_t::rbp_npages.
Referenced by lnet_rtrpool_adjust_bufs().
static void lnet_ni_notify_locked (lnet_ni_t * ni, lnet_peer_t * lp) [static]
Definition at line 130 of file router.c.
References lnet_lnd::lnd_notify, lnet_net_lock(), lnet_net_unlock(), lnet_peer::lp_alive, lnet_peer::lp_cpt, lnet_peer::lp_nid, lnet_peer::lp_notify, lnet_peer::lp_notifying, lnet_peer::lp_notifylnd, and lnet_ni::ni_lnd.
Referenced by lnet_notify(), and lnet_ping_router_locked().
int lnet_notify (lnet_ni_t * ni, lnet_nid_t nid, int alive, cfs_time_t when)
Definition at line 1721 of file router.c.
References auto_down, CDEBUG, cfs_duration_sec(), cfs_time_after(), cfs_time_current(), cfs_time_sub(), CWARN, D_NET, LASSERT, libcfs_nid2str(), lnet_t::ln_peer_tables, lnet_t::ln_shutdown, lnet_cpt_of_nid(), lnet_find_peer_locked(), lnet_net_lock(), lnet_net_unlock(), lnet_ni_notify_locked(), LNET_NIDNET(), lnet_notify_locked(), lnet_peer_decref_locked(), lnet_peer::lp_last_alive, lnet_ni::ni_nid, now(), and the_lnet.
Referenced by kgnilnd_finish_connect(), kgnilnd_peer_notify(), kiblnd_peer_notify(), ksocknal_peer_failed(), and LNetCtl().
void lnet_notify_locked (lnet_peer_t * lp, int notifylnd, int alive, cfs_time_t when)
Definition at line 101 of file router.c.
References CDEBUG, cfs_time_before(), D_NET, libcfs_nid2str(), LNET_PING_FEAT_INVAL, lnet_peer::lp_alive, lnet_peer::lp_alive_count, lnet_peer::lp_nid, lnet_peer::lp_notify, lnet_peer::lp_notifylnd, lnet_peer::lp_ping_deadline, lnet_peer::lp_ping_feats, and lnet_peer::lp_timestamp.
Referenced by lnet_notify(), lnet_peer_alive_locked(), lnet_peer_is_alive(), lnet_peer_set_alive(), lnet_ping_router_locked(), and lnet_router_checker_event().
static int lnet_nrb_large_calculate (void) [static]
Definition at line 1521 of file router.c.
References large_router_buffers, LCONSOLE_ERROR_MSG, LNET_CPT_NUMBER, LNET_NRB_LARGE, LNET_NRB_LARGE_MIN, and max.
Referenced by lnet_rtrpools_adjust_helper(), and lnet_rtrpools_alloc().
static int lnet_nrb_small_calculate (void) [static]
Definition at line 1502 of file router.c.
References LCONSOLE_ERROR_MSG, LNET_CPT_NUMBER, LNET_NRB_SMALL, LNET_NRB_SMALL_MIN, max, and small_router_buffers.
Referenced by lnet_rtrpools_adjust_helper(), and lnet_rtrpools_alloc().
static int lnet_nrb_tiny_calculate (void) [static]
Definition at line 1483 of file router.c.
References LCONSOLE_ERROR_MSG, LNET_CPT_NUMBER, LNET_NRB_TINY, LNET_NRB_TINY_MIN, max, and tiny_router_buffers.
Referenced by lnet_rtrpools_adjust_helper(), and lnet_rtrpools_alloc().
static void lnet_parse_rc_info (lnet_rc_data_t * rcd) [static]
parse router-checker pinginfo, record number of down NIs for remote networks on that router.
Definition at line 651 of file router.c.
References __swab32, CDEBUG, D_NET, libcfs_nid2str(), list_for_each_entry, LNET_MAX_RTR_NIS, LNET_NETTYP(), LNET_NI_STATUS_DOWN, LNET_NI_STATUS_UP, LNET_NID_ANY, LNET_NIDNET(), LNET_PING_FEAT_INVAL, LNET_PING_FEAT_MASK, LNET_PING_FEAT_NI_STATUS, LNET_PING_FEAT_RTE_DISABLED, LNET_PROTO_PING_MAGIC, lnet_swap_pinginfo(), LOLND, lnet_peer::lp_alive, lnet_peer::lp_nid, lnet_peer::lp_ping_feats, lnet_peer::lp_routes, lnet_route_t::lr_downis, lnet_route_t::lr_hops, lnet_route_t::lr_net, lnet_rc_data_t::rcd_gateway, and lnet_rc_data_t::rcd_pinginfo.
Referenced by lnet_router_checker_event().
int lnet_peer_buffer_credits (lnet_ni_t * ni)
Definition at line 58 of file router.c.
References lnet_ni::ni_peerrtrcredits, lnet_ni::ni_peertxcredits, and peer_buffer_credits.
Referenced by lnet_nid2peer_locked().
int lnet_peers_start_down (void)
Definition at line 95 of file router.c.
References check_routers_before_use.
Referenced by lnet_nid2peer_locked().
static void lnet_ping_router_locked (lnet_peer_t * rtr) [static]
Definition at line 981 of file router.c.
References CDEBUG, cfs_time_add(), cfs_time_after(), cfs_time_current(), cfs_time_seconds(), cfs_time_shift(), D_NET, libcfs_id2str(), libcfs_nid2str(), lnet_t::ln_rc_state, lnet_create_rc_data_locked(), lnet_isrouter(), lnet_net_lock(), lnet_net_unlock(), lnet_ni_notify_locked(), LNET_NID_ANY, lnet_notify_locked(), lnet_peer_addref_locked(), lnet_peer_decref_locked(), LNET_PID_LUSTRE, LNET_PROTO_PING_MATCHBITS, LNET_RC_STATE_RUNNING, LNET_RESERVED_PORTAL, lnet_router_check_interval(), LNetGet(), lnet_peer::lp_alive, lnet_peer::lp_alive_count, lnet_peer::lp_cpt, lnet_peer::lp_ni, lnet_peer::lp_nid, lnet_peer::lp_ping_deadline, lnet_peer::lp_ping_notsent, lnet_peer::lp_ping_timestamp, lnet_peer::lp_rcd, now(), lnet_rc_data_t::rcd_mdh, router_ping_timeout, and the_lnet.
Referenced by lnet_router_checker().
static void lnet_prune_rc_data (int wait_unlink) [static]
Definition at line 1124 of file router.c.
References CDEBUG, cfs_time_seconds(), D_NET, D_WARNING, INIT_LIST_HEAD, LASSERT, likely, list_add(), list_del_init(), list_empty(), list_entry, list_for_each_entry, list_for_each_entry_safe, list_move(), list_splice_init(), lnet_t::ln_rc_state, lnet_t::ln_rcd_deathrow, lnet_t::ln_rcd_zombie, lnet_t::ln_routers, lnet_destroy_rc_data(), LNET_LOCK_EX, lnet_net_lock(), lnet_net_unlock(), LNET_RC_STATE_RUNNING, LNetHandleIsInvalid(), LNetMDUnlink(), lnet_peer::lp_rcd, list_head::next, lnet_rc_data_t::rcd_list, lnet_rc_data_t::rcd_mdh, and the_lnet.
Referenced by lnet_router_checker().
static int lnet_router_check_interval (lnet_peer_t * rtr) [static]
Definition at line 968 of file router.c.
References dead_router_check_interval, live_router_check_interval, and lnet_peer::lp_alive.
Referenced by lnet_ping_router_locked().
static int lnet_router_checker (void * arg) [static]
Definition at line 1230 of file router.c.
References __u64, cfs_block_allsigs(), cfs_time_seconds(), list_entry, list_for_each, lnet_t::ln_rc_signal, lnet_t::ln_rc_state, lnet_t::ln_rc_waitq, lnet_t::ln_routers, lnet_t::ln_routers_version, lnet_t::ln_routing, lnet_cpt_of_nid_locked(), lnet_net_lock(), lnet_net_lock_current(), lnet_net_unlock(), lnet_ping_router_locked(), lnet_prune_rc_data(), LNET_RC_STATE_RUNNING, LNET_RC_STATE_SHUTDOWN, lnet_router_checker_active(), lnet_update_ni_status_locked(), lnet_peer::lp_nid, the_lnet, and version.
Referenced by lnet_router_checker_start().
static bool lnet_router_checker_active (void) [inline, static]
Definition at line 1214 of file router.c.
References dead_router_check_interval, list_empty(), live_router_check_interval, lnet_t::ln_rc_state, lnet_t::ln_routers, lnet_t::ln_routing, LNET_RC_STATE_RUNNING, and the_lnet.
Referenced by lnet_router_checker().
static void lnet_router_checker_event (lnet_event_t * event) [static]
Definition at line 738 of file router.c.
References avoid_asym_router_failure, cfs_time_current(), LASSERT, LNET_EVENT_REPLY, LNET_EVENT_SEND, lnet_isrouter(), lnet_net_lock(), lnet_net_unlock(), lnet_notify_locked(), lnet_parse_rc_info(), LNetInvalidateHandle(), lnet_peer::lp_cpt, lnet_peer::lp_ping_notsent, lnet_peer::lp_rcd, lnet_rc_data_t::rcd_gateway, lnet_rc_data_t::rcd_mdh, lnet_event_t::status, lnet_event_t::type, and lnet_event_t::unlinked.
Referenced by lnet_router_checker_start().
int lnet_router_checker_start (void)
Definition at line 1054 of file router.c.
References CERROR, check_routers_before_use, dead_router_check_interval, LASSERT, LCONSOLE_ERROR_MSG, lnet_t::ln_rc_eqh, lnet_t::ln_rc_signal, lnet_t::ln_rc_state, LNET_RC_STATE_RUNNING, LNET_RC_STATE_SHUTDOWN, lnet_router_checker(), lnet_router_checker_event(), lnet_wait_known_routerstate(), LNetEQAlloc(), LNetEQFree(), and the_lnet.
Referenced by LNetNIInit().
void lnet_router_checker_stop (void)
Definition at line 1102 of file router.c.
References LASSERT, lnet_t::ln_rc_eqh, lnet_t::ln_rc_signal, lnet_t::ln_rc_state, lnet_t::ln_rc_waitq, LNET_RC_STATE_RUNNING, LNET_RC_STATE_SHUTDOWN, LNET_RC_STATE_STOPPING, LNetEQFree(), and the_lnet.
Referenced by LNetNIFini().
void lnet_router_ni_update_locked (lnet_peer_t * gw, __u32 net)
Definition at line 823 of file router.c.
References list_for_each_entry, LNET_PING_FEAT_NI_STATUS, lnet_peer::lp_ping_feats, lnet_peer::lp_routes, lnet_route_t::lr_downis, and lnet_route_t::lr_net.
Referenced by lnet_parse().
static void lnet_rtr_addref_locked (lnet_peer_t * lp) [static]
Definition at line 168 of file router.c.
References LASSERT, list_add(), list_entry, list_for_each_prev, lnet_t::ln_routers, lnet_t::ln_routers_version, lnet_peer_addref_locked(), lnet_peer::lp_nid, lnet_peer::lp_refcount, lnet_peer::lp_rtr_list, lnet_peer::lp_rtr_refcount, and the_lnet.
Referenced by lnet_add_route_to_rnet().
static void lnet_rtr_decref_locked (lnet_peer_t * lp) [static]
Definition at line 195 of file router.c.
References LASSERT, list_add(), list_del(), list_empty(), lnet_t::ln_rcd_deathrow, lnet_t::ln_routers_version, lnet_peer_decref_locked(), lnet_peer::lp_rcd, lnet_peer::lp_refcount, lnet_peer::lp_routes, lnet_peer::lp_rtr_list, lnet_peer::lp_rtr_refcount, lnet_rc_data_t::rcd_list, and the_lnet.
Referenced by lnet_del_route().
static int lnet_rtrpool_adjust_bufs (lnet_rtrbufpool_t * rbp, int nbufs, int cpt) [static]
Definition at line 1372 of file router.c.
References CERROR, INIT_LIST_HEAD, list_add(), list_del(), list_empty(), list_entry, list_splice_tail(), lnet_destroy_rtrbuf(), lnet_net_lock(), lnet_net_unlock(), lnet_new_rtrbuf(), lnet_schedule_blocked_locked(), list_head::next, lnet_rtrbufpool_t::rbp_bufs, lnet_rtrbufpool_t::rbp_credits, lnet_rtrbufpool_t::rbp_mincredits, lnet_rtrbufpool_t::rbp_msgs, lnet_rtrbufpool_t::rbp_nbuffers, lnet_rtrbufpool_t::rbp_npages, and lnet_rtrbufpool_t::rbp_req_nbuffers.
Referenced by lnet_rtrpools_adjust_helper(), and lnet_rtrpools_alloc().
static void lnet_rtrpool_free_bufs (lnet_rtrbufpool_t * rbp, int cpt) [static]
Definition at line 1344 of file router.c.
References INIT_LIST_HEAD, list_del(), list_empty(), list_entry, list_splice_init(), lnet_destroy_rtrbuf(), lnet_drop_routed_msgs_locked(), lnet_net_lock(), lnet_net_unlock(), list_head::next, lnet_rtrbuf_t::rb_list, lnet_rtrbufpool_t::rbp_bufs, lnet_rtrbufpool_t::rbp_credits, lnet_rtrbufpool_t::rbp_mincredits, lnet_rtrbufpool_t::rbp_msgs, lnet_rtrbufpool_t::rbp_nbuffers, lnet_rtrbufpool_t::rbp_npages, and lnet_rtrbufpool_t::rbp_req_nbuffers.
Referenced by lnet_rtrpools_free().
static void lnet_rtrpool_init (lnet_rtrbufpool_t * rbp, int npages) [static]
Definition at line 1451 of file router.c.
References INIT_LIST_HEAD, lnet_rtrbufpool_t::rbp_bufs, lnet_rtrbufpool_t::rbp_credits, lnet_rtrbufpool_t::rbp_mincredits, lnet_rtrbufpool_t::rbp_msgs, and lnet_rtrbufpool_t::rbp_npages.
Referenced by lnet_rtrpools_alloc().
int lnet_rtrpools_adjust (int tiny, int small, int large)
Definition at line 1662 of file router.c.
References lnet_t::ln_routing, lnet_rtrpools_adjust_helper(), and the_lnet.
Referenced by LNetCtl().
static int lnet_rtrpools_adjust_helper (int tiny, int small, int large) [static]
Definition at line 1618 of file router.c.
References cfs_percpt_for_each, large_router_buffers, lnet_t::ln_rtrpools, LNET_LARGE_BUF_IDX, lnet_nrb_large_calculate(), lnet_nrb_small_calculate(), lnet_nrb_tiny_calculate(), lnet_rtrpool_adjust_bufs(), LNET_SMALL_BUF_IDX, LNET_TINY_BUF_IDX, small_router_buffers, the_lnet, and tiny_router_buffers.
Referenced by lnet_rtrpools_adjust(), and lnet_rtrpools_enable().
int lnet_rtrpools_alloc (int im_a_router)
Definition at line 1540 of file router.c.
References cfs_percpt_alloc(), cfs_percpt_for_each, forwarding, LCONSOLE_ERROR_MSG, lnet_t::ln_routing, lnet_t::ln_rtrpools, lnet_cpt_table, LNET_LARGE_BUF_IDX, LNET_LOCK_EX, lnet_net_lock(), lnet_net_unlock(), lnet_nrb_large_calculate(), LNET_NRB_LARGE_PAGES, lnet_nrb_small_calculate(), LNET_NRB_SMALL_PAGES, lnet_nrb_tiny_calculate(), LNET_NRBPOOLS, lnet_rtrpool_adjust_bufs(), lnet_rtrpool_init(), lnet_rtrpools_free(), LNET_SMALL_BUF_IDX, LNET_TINY_BUF_IDX, and the_lnet.
Referenced by lnet_rtrpools_enable(), and LNetNIInit().
void lnet_rtrpools_disable (void)
Definition at line 1704 of file router.c.
References large_router_buffers, lnet_t::ln_ping_info, lnet_t::ln_routing, LNET_LOCK_EX, lnet_net_lock(), lnet_net_unlock(), LNET_PING_FEAT_RTE_DISABLED, lnet_rtrpools_free(), small_router_buffers, the_lnet, and tiny_router_buffers.
Referenced by LNetCtl().
int lnet_rtrpools_enable (void)
Definition at line 1675 of file router.c.
References lnet_t::ln_ping_info, lnet_t::ln_routing, lnet_t::ln_rtrpools, LNET_LOCK_EX, lnet_net_lock(), lnet_net_unlock(), LNET_PING_FEAT_RTE_DISABLED, lnet_rtrpools_adjust_helper(), lnet_rtrpools_alloc(), and the_lnet.
Referenced by LNetCtl().
void lnet_rtrpools_free (int keep_pools)
Definition at line 1462 of file router.c.
References cfs_percpt_for_each, cfs_percpt_free(), lnet_t::ln_rtrpools, LNET_LARGE_BUF_IDX, lnet_rtrpool_free_bufs(), LNET_SMALL_BUF_IDX, LNET_TINY_BUF_IDX, and the_lnet.
Referenced by lnet_rtrpools_alloc(), lnet_rtrpools_disable(), and lnet_unprepare().
static void lnet_shuffle_seed (void) [static]
Definition at line 237 of file router.c.
References cfs_get_random_bytes(), cfs_srand(), list_entry, list_for_each, lnet_t::ln_nis, LNET_NETTYP(), LNET_NIDADDR(), LNET_NIDNET(), LOLND, seed, and the_lnet.
Referenced by lnet_add_route_to_rnet().
void lnet_swap_pinginfo (lnet_ping_info_t * info)
Definition at line 629 of file router.c.
References __swab32s, __swab64s, and LNET_MAX_RTR_NIS.
Referenced by lnet_parse_rc_info(), and lnet_ping().
static void lnet_update_ni_status_locked (void) [static]
Definition at line 838 of file router.c.
References CDEBUG, cfs_time_current_sec(), D_NET, dead_router_check_interval, LASSERT, libcfs_nid2str(), list_for_each_entry, live_router_check_interval, lnet_t::ln_nis, lnet_t::ln_routing, lnet_lnd::lnd_type, lnet_ni_lock, LNET_NI_STATUS_DOWN, lnet_ni_unlock, LOLND, MAX, lnet_ni::ni_lnd, lnet_ni::ni_nid, lnet_ni::ni_status, now(), router_ping_timeout, the_lnet, and timeout.
Referenced by lnet_router_checker().
static void lnet_wait_known_routerstate (void) [static]
Definition at line 791 of file router.c.
References cfs_time_seconds(), LASSERT, list_entry, list_for_each, lnet_t::ln_rc_state, lnet_t::ln_routers, lnet_net_lock_current(), lnet_net_unlock(), LNET_RC_STATE_RUNNING, lnet_peer::lp_alive_count, and the_lnet.
Referenced by lnet_router_checker_start().
module_param (router_ping_timeout , int , 0644)
module_param (live_router_check_interval , int , 0644)
module_param (dead_router_check_interval , int , 0644)
module_param (avoid_asym_router_failure , int , 0644)
module_param (check_routers_before_use , int , 0444)
module_param (auto_down , int , 0444)
module_param (peer_buffer_credits , int , 0444)
module_param (large_router_buffers , int , 0444)
module_param (small_router_buffers , int , 0444)
module_param (tiny_router_buffers , int , 0444)
module_param (forwarding , charp , 0444)
MODULE_PARM_DESC (router_ping_timeout , "Seconds to wait for the reply to a router health query")
MODULE_PARM_DESC (live_router_check_interval , "Seconds between live router health checks (<= 0 to disable)")
MODULE_PARM_DESC (dead_router_check_interval , "Seconds between dead router health checks (<= 0 to disable)")
MODULE_PARM_DESC (avoid_asym_router_failure , "Avoid asymmetrical router failures (0 to disable)")
MODULE_PARM_DESC (check_routers_before_use , "Assume routers are down and ping them before use")
MODULE_PARM_DESC (auto_down , "Automatically mark peers down on comms error")
MODULE_PARM_DESC (peer_buffer_credits , "# router buffer credits per peer")
MODULE_PARM_DESC (large_router_buffers , "# of large messages to buffer in the router")
MODULE_PARM_DESC (small_router_buffers , "# of small (1 page) messages to buffer in the router")
MODULE_PARM_DESC (tiny_router_buffers , "# of 0 payload messages to buffer in the router")
MODULE_PARM_DESC (forwarding , "Explicitly enable/disable forwarding between networks")
Variable Documentation
int auto_down = 1 [static]
Definition at line 53 of file router.c.
Referenced by lnet_notify().
int avoid_asym_router_failure = 1
Definition at line 78 of file router.c.
Referenced by lnet_parse(), and lnet_router_checker_event().
int check_routers_before_use [static]
Definition at line 74 of file router.c.
Referenced by lnet_peers_start_down(), and lnet_router_checker_start().
int dead_router_check_interval = 60 [static]
Definition at line 82 of file router.c.
Referenced by lnet_router_check_interval(), lnet_router_checker_active(), lnet_router_checker_start(), and lnet_update_ni_status_locked().
char* forwarding = "" [static]
Definition at line 36 of file router.c.
Referenced by lnet_rtrpools_alloc().
int large_router_buffers [static]
Definition at line 46 of file router.c.
Referenced by lnet_nrb_large_calculate(), lnet_rtrpools_adjust_helper(), and lnet_rtrpools_disable().
int live_router_check_interval = 60 [static]
Definition at line 86 of file router.c.
Referenced by lnet_router_check_interval(), lnet_router_checker_active(), and lnet_update_ni_status_locked().
int peer_buffer_credits [static]
Definition at line 49 of file router.c.
Referenced by lnet_peer_buffer_credits().
int router_ping_timeout = 50 [static]
Definition at line 90 of file router.c.
Referenced by lnet_ping_router_locked(), and lnet_update_ni_status_locked().
int small_router_buffers [static]
Definition at line 43 of file router.c.
Referenced by lnet_nrb_small_calculate(), lnet_rtrpools_adjust_helper(), and lnet_rtrpools_disable().
int tiny_router_buffers [static]
Definition at line 40 of file router.c.
Referenced by lnet_nrb_tiny_calculate(), lnet_rtrpools_adjust_helper(), and lnet_rtrpools_disable().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.