Lustre: lnet/lnet/router_proc.c File Reference
lnet/lnet/router_proc.c File Reference
#include <libcfs/libcfs.h>
#include <lnet/lib-lnet.h>
Data Structures
struct lnet_portal_rotors
Defines
#define DEBUG_SUBSYSTEM S_LNET
#define LNET_LOFFT_BITS (sizeof(loff_t) * 8)
#define LNET_PROC_CPT_BITS (LNET_CPT_BITS + 1)
#define LNET_PROC_VER_BITS MAX(((MIN(LNET_LOFFT_BITS, 64)) / 4), 8)
#define LNET_PROC_HASH_BITS LNET_PEER_HASH_BITS
#define LNET_PROC_HOFF_BITS
#define LNET_PROC_HPOS_BITS (LNET_PROC_HASH_BITS + LNET_PROC_HOFF_BITS)
#define LNET_PROC_VPOS_BITS (LNET_PROC_HPOS_BITS + LNET_PROC_VER_BITS)
#define LNET_PROC_CPT_MASK ((1ULL << LNET_PROC_CPT_BITS) - 1)
#define LNET_PROC_VER_MASK ((1ULL << LNET_PROC_VER_BITS) - 1)
#define LNET_PROC_HASH_MASK ((1ULL << LNET_PROC_HASH_BITS) - 1)
#define LNET_PROC_HOFF_MASK ((1ULL << LNET_PROC_HOFF_BITS) - 1)
#define LNET_PROC_CPT_GET(pos) (int)(((pos) >> LNET_PROC_VPOS_BITS) & LNET_PROC_CPT_MASK)
#define LNET_PROC_VER_GET(pos) (int)(((pos) >> LNET_PROC_HPOS_BITS) & LNET_PROC_VER_MASK)
#define LNET_PROC_HASH_GET(pos) (int)(((pos) >> LNET_PROC_HOFF_BITS) & LNET_PROC_HASH_MASK)
#define LNET_PROC_HOFF_GET(pos) (int)((pos) & LNET_PROC_HOFF_MASK)
#define LNET_PROC_POS_MAKE(cpt, ver, hash, off)
#define LNET_PROC_VERSION(v) ((unsigned int)((v) & LNET_PROC_VER_MASK))
Functions
static int __proc_lnet_stats (void *data, int write, loff_t pos, void __user *buffer, int nob)
static int proc_lnet_stats (struct ctl_table *table, int write, void __user *buffer, size_t *lenp, loff_t *ppos)
static int proc_lnet_routes (struct ctl_table *table, int write, void __user *buffer, size_t *lenp, loff_t *ppos)
static int proc_lnet_routers (struct ctl_table *table, int write, void __user *buffer, size_t *lenp, loff_t *ppos)
static int proc_lnet_peers (struct ctl_table *table, int write, void __user *buffer, size_t *lenp, loff_t *ppos)
static int __proc_lnet_buffers (void *data, int write, loff_t pos, void __user *buffer, int nob)
static int proc_lnet_buffers (struct ctl_table *table, int write, void __user *buffer, size_t *lenp, loff_t *ppos)
static int proc_lnet_nis (struct ctl_table *table, int write, void __user *buffer, size_t *lenp, loff_t *ppos)
static int __proc_lnet_portal_rotor (void *data, int write, loff_t pos, void __user *buffer, int nob)
static int proc_lnet_portal_rotor (struct ctl_table *table, int write, void __user *buffer, size_t *lenp, loff_t *ppos)
void lnet_proc_init (void)
void lnet_proc_fini (void)
Variables
static struct ctl_table_header * lnet_table_header = NULL
static struct lnet_portal_rotors portal_rotors []
static struct ctl_table lnet_table []
static struct ctl_table top_table []
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 23 of file router_proc.c.
#define LNET_LOFFT_BITS (sizeof(loff_t) * 8)
Definition at line 32 of file router_proc.c.
#define LNET_PROC_CPT_BITS (LNET_CPT_BITS + 1)
Definition at line 36 of file router_proc.c.
#define LNET_PROC_CPT_GET (pos) (int)(((pos) >> LNET_PROC_VPOS_BITS) & LNET_PROC_CPT_MASK)
Definition at line 59 of file router_proc.c.
Referenced by proc_lnet_peers().
#define LNET_PROC_CPT_MASK ((1ULL << LNET_PROC_CPT_BITS) - 1)
Definition at line 54 of file router_proc.c.
#define LNET_PROC_HASH_BITS LNET_PEER_HASH_BITS
Definition at line 40 of file router_proc.c.
Referenced by proc_lnet_peers().
#define LNET_PROC_HASH_GET (pos) (int)(((pos) >> LNET_PROC_HOFF_BITS) & LNET_PROC_HASH_MASK)
Definition at line 65 of file router_proc.c.
Referenced by proc_lnet_peers().
#define LNET_PROC_HASH_MASK ((1ULL << LNET_PROC_HASH_BITS) - 1)
Definition at line 56 of file router_proc.c.
#define LNET_PROC_HOFF_BITS
Value:
(LNET_LOFFT_BITS -       \
                                 LNET_PROC_CPT_BITS -    \
                                 LNET_PROC_VER_BITS -    \
                                 LNET_PROC_HASH_BITS - 1)
Definition at line 45 of file router_proc.c.
#define LNET_PROC_HOFF_GET (pos) (int)((pos) & LNET_PROC_HOFF_MASK)
Definition at line 68 of file router_proc.c.
Referenced by proc_lnet_peers(), proc_lnet_routers(), and proc_lnet_routes().
#define LNET_PROC_HOFF_MASK ((1ULL << LNET_PROC_HOFF_BITS) - 1)
Definition at line 57 of file router_proc.c.
#define LNET_PROC_HPOS_BITS (LNET_PROC_HASH_BITS + LNET_PROC_HOFF_BITS)
Definition at line 50 of file router_proc.c.
#define LNET_PROC_POS_MAKE (cpt, ver, hash, off)
Value:
(((((loff_t)(cpt)) & LNET_PROC_CPT_MASK) << LNET_PROC_VPOS_BITS) |   \
        ((((loff_t)(ver)) & LNET_PROC_VER_MASK) << LNET_PROC_HPOS_BITS) |   \
        ((((loff_t)(hash)) & LNET_PROC_HASH_MASK) << LNET_PROC_HOFF_BITS) | \
        ((off) & LNET_PROC_HOFF_MASK))
Definition at line 71 of file router_proc.c.
Referenced by proc_lnet_peers(), proc_lnet_routers(), and proc_lnet_routes().
#define LNET_PROC_VER_BITS MAX(((MIN(LNET_LOFFT_BITS, 64)) / 4), 8)
Definition at line 38 of file router_proc.c.
#define LNET_PROC_VER_GET (pos) (int)(((pos) >> LNET_PROC_HPOS_BITS) & LNET_PROC_VER_MASK)
Definition at line 62 of file router_proc.c.
Referenced by proc_lnet_peers(), proc_lnet_routers(), and proc_lnet_routes().
#define LNET_PROC_VER_MASK ((1ULL << LNET_PROC_VER_BITS) - 1)
Definition at line 55 of file router_proc.c.
#define LNET_PROC_VERSION (v) ((unsigned int)((v) & LNET_PROC_VER_MASK))
Definition at line 77 of file router_proc.c.
Referenced by proc_lnet_peers(), proc_lnet_routers(), and proc_lnet_routes().
#define LNET_PROC_VPOS_BITS (LNET_PROC_HPOS_BITS + LNET_PROC_VER_BITS)
Definition at line 52 of file router_proc.c.
Function Documentation
static int __proc_lnet_buffers (void * data, int write, loff_t pos, void __user * buffer, int nob) [static]
Definition at line 567 of file router_proc.c.
References cfs_percpt_for_each, cfs_trace_copyout_string(), LASSERT, LIBCFS_ALLOC, LIBCFS_FREE, lnet_t::ln_rtrpools, LNET_CPT_NUMBER, LNET_LOCK_EX, lnet_net_lock(), lnet_net_unlock(), LNET_NRBPOOLS, min_t, and the_lnet.
Referenced by proc_lnet_buffers().
static int __proc_lnet_portal_rotor (void * data, int write, loff_t pos, void __user * buffer, int nob) [static]
Definition at line 790 of file router_proc.c.
References buf, cfs_trace_copyin_string(), cfs_trace_copyout_string(), cfs_trimwhite(), LASSERT, LIBCFS_ALLOC, LIBCFS_FREE, lnet_res_lock(), lnet_res_unlock(), min_t, portal_rotor, lnet_portal_rotors::pr_desc, lnet_portal_rotors::pr_name, and lnet_portal_rotors::pr_value.
Referenced by proc_lnet_portal_rotor().
static int __proc_lnet_stats (void * data, int write, loff_t pos, void __user * buffer, int nob) [static]
Definition at line 79 of file router_proc.c.
References cfs_trace_copyout_string(), lnet_counters::drop_count, lnet_counters::drop_length, lnet_counters::errors, LIBCFS_ALLOC, LIBCFS_FREE, lnet_counters_get(), lnet_counters_reset(), LPU64, min_t, lnet_counters::msgs_alloc, lnet_counters::msgs_max, lnet_counters::recv_count, lnet_counters::recv_length, lnet_counters::route_count, lnet_counters::route_length, lnet_counters::send_count, and lnet_counters::send_length.
Referenced by proc_lnet_stats().
void lnet_proc_fini (void)
Definition at line 932 of file router_proc.c.
References lnet_table_header.
Referenced by LNetNIFini().
void lnet_proc_init (void)
Definition at line 923 of file router_proc.c.
References lnet_table_header, and top_table.
Referenced by LNetNIInit().
static int proc_lnet_buffers (struct ctl_table * table, int write, void __user * buffer, size_t * lenp, loff_t * ppos) [static]
Definition at line 626 of file router_proc.c.
References __proc_lnet_buffers(), and lprocfs_call_handler().
static int proc_lnet_nis (struct ctl_table * table, int write, void __user * buffer, size_t * lenp, loff_t * ppos) [static]
Definition at line 634 of file router_proc.c.
References cfs_percpt_for_each, cfs_time_current_sec(), LASSERT, LIBCFS_ALLOC, LIBCFS_FREE, libcfs_nid2str(), list_entry, lnet_t::ln_nis, lnet_t::ln_routing, lnet_lnd::lnd_type, LNET_CPT_NUMBER, lnet_net_lock(), lnet_net_unlock(), lnet_ni_lock, LNET_NI_STATUS_UP, lnet_ni_unlock, LOLND, list_head::next, lnet_ni::ni_cpts, lnet_ni::ni_last_alive, lnet_ni::ni_lnd, lnet_ni::ni_ncpts, lnet_ni::ni_nid, lnet_ni::ni_peerrtrcredits, lnet_ni::ni_peertxcredits, lnet_ni::ni_refs, lnet_ni::ni_status, lnet_ni::ni_tx_queues, now(), the_lnet, lnet_tx_queue::tq_credits, lnet_tx_queue::tq_credits_max, and lnet_tx_queue::tq_credits_min.
static int proc_lnet_peers (struct ctl_table * table, int write, void __user * buffer, size_t * lenp, loff_t * ppos) [static]
Definition at line 400 of file router_proc.c.
References cfs_duration_sec(), cfs_time_current(), cfs_time_sub(), CLASSERT, LASSERT, LIBCFS_ALLOC, LIBCFS_FREE, libcfs_nid2str(), list_entry, lnet_t::ln_peer_tables, LNET_CPT_NUMBER, lnet_isrouter(), lnet_net_lock(), lnet_net_unlock(), lnet_peer_aliveness_enabled, LNET_PEER_HASH_BITS, LNET_PEER_HASH_SIZE, LNET_PROC_CPT_GET, LNET_PROC_HASH_BITS, LNET_PROC_HASH_GET, LNET_PROC_HOFF_GET, LNET_PROC_POS_MAKE, LNET_PROC_VER_GET, LNET_PROC_VERSION, lnet_peer::lp_alive, lnet_peer::lp_hashlist, lnet_peer::lp_last_alive, lnet_peer::lp_minrtrcredits, lnet_peer::lp_mintxcredits, lnet_peer::lp_ni, lnet_peer::lp_nid, lnet_peer::lp_refcount, lnet_peer::lp_rtrcredits, lnet_peer::lp_txcredits, lnet_peer::lp_txqnob, list_head::next, lnet_ni::ni_peertxcredits, now(), lnet_peer_table::pt_hash, lnet_peer_table::pt_version, and the_lnet.
static int proc_lnet_portal_rotor (struct ctl_table * table, int write, void __user * buffer, size_t * lenp, loff_t * ppos) [static]
Definition at line 852 of file router_proc.c.
References __proc_lnet_portal_rotor(), and lprocfs_call_handler().
static int proc_lnet_routers (struct ctl_table * table, int write, void __user * buffer, size_t * lenp, loff_t * ppos) [static]
Definition at line 264 of file router_proc.c.
References cfs_duration_sec(), cfs_time_current(), cfs_time_sub(), LASSERT, LIBCFS_ALLOC, LIBCFS_FREE, libcfs_nid2str(), list_entry, list_for_each_entry, lnet_t::ln_routers, lnet_t::ln_routers_version, lnet_net_lock(), lnet_net_unlock(), LNET_PING_FEAT_NI_STATUS, LNET_PROC_HOFF_GET, LNET_PROC_POS_MAKE, LNET_PROC_VER_GET, LNET_PROC_VERSION, lnet_peer::lp_alive, lnet_peer::lp_alive_count, lnet_peer::lp_nid, lnet_peer::lp_ping_deadline, lnet_peer::lp_ping_feats, lnet_peer::lp_ping_notsent, lnet_peer::lp_ping_timestamp, lnet_peer::lp_refcount, lnet_peer::lp_routes, lnet_peer::lp_rtr_list, lnet_peer::lp_rtr_refcount, lnet_route_t::lr_downis, list_head::next, now(), and the_lnet.
static int proc_lnet_routes (struct ctl_table * table, int write, void __user * buffer, size_t * lenp, loff_t * ppos) [static]
Definition at line 137 of file router_proc.c.
References CLASSERT, LASSERT, LIBCFS_ALLOC, LIBCFS_FREE, libcfs_net2str(), libcfs_nid2str(), list_entry, lnet_t::ln_remote_nets_hash, lnet_t::ln_remote_nets_version, lnet_t::ln_routing, lnet_is_route_alive(), lnet_net_lock(), lnet_net_unlock(), LNET_PROC_HOFF_GET, LNET_PROC_POS_MAKE, LNET_PROC_VER_GET, LNET_PROC_VERSION, LNET_REMOTE_NETS_HASH_SIZE, lnet_remotenet_t::lrn_net, lnet_remotenet_t::lrn_routes, list_head::next, and the_lnet.
static int proc_lnet_stats (struct ctl_table * table, int write, void __user * buffer, size_t * lenp, loff_t * ppos) [static]
Definition at line 129 of file router_proc.c.
References __proc_lnet_stats(), and lprocfs_call_handler().
Variable Documentation
struct ctl_table lnet_table[] [static]
Definition at line 860 of file router_proc.c.
struct ctl_table_header* lnet_table_header = NULL [static]
Definition at line 30 of file router_proc.c.
Referenced by insert_proc(), lnet_proc_fini(), lnet_proc_init(), and remove_proc().
struct lnet_portal_rotors portal_rotors[] [static]
Initial value:
 {
        {
                .pr_value = LNET_PTL_ROTOR_OFF,
                .pr_name  = "OFF",
                .pr_desc  = "Turn off message rotor for wildcard portals"
        },
        {
                .pr_value = LNET_PTL_ROTOR_ON,
                .pr_name  = "ON",
                .pr_desc  = "round-robin dispatch all PUT messages for "
                            "wildcard portals"
        },
        {
                .pr_value = LNET_PTL_ROTOR_RR_RT,
                .pr_name  = "RR_RT",
                .pr_desc  = "round-robin dispatch routed PUT message for "
                            "wildcard portals"
        },
        {
                .pr_value = LNET_PTL_ROTOR_HASH_RT,
                .pr_name  = "HASH_RT",
                .pr_desc  = "dispatch routed PUT message by hashing source "
                            "NID for wildcard portals"
        },
        {
                .pr_value = -1,
                .pr_name  = NULL,
                .pr_desc  = NULL
        },
}
Definition at line 759 of file router_proc.c.
struct ctl_table top_table[] [static]
Initial value:
 {
        {
                INIT_CTL_NAME
                .procname       = "lnet",
                .mode           = 0555,
                .data           = NULL,
                .maxlen         = 0,
                .child          = lnet_table,
        },
        { 0 }
}
Definition at line 910 of file router_proc.c.
Referenced by lnet_proc_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.