Lustre: lnet/utils/routerstat.c File Reference
lnet/utils/routerstat.c File Reference
#include <errno.h>
#include <fcntl.h>
#include <glob.h>
#include <limits.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <sys/time.h>
#include <unistd.h>
#include <libcfs/util/param.h>
Data Structures
struct counters_t
Functions
double timenow ()
unsigned long long subull (unsigned long long a, unsigned long long b)
unsigned long long subul (unsigned long a, unsigned long b)
double rul (unsigned long a, double secs)
double rull (unsigned long long a, double secs)
void do_stat (int fd)
int main (int argc, char **argv)
Function Documentation
void do_stat (int fd)
Definition at line 100 of file routerstat.c.
References counters_t::drop_count, counters_t::drop_length, counters_t::errors, counters_t::msgs_alloc, counters_t::msgs_max, now(), counters_t::recv_count, counters_t::recv_length, counters_t::route_count, counters_t::route_length, rul(), rull(), counters_t::send_count, counters_t::send_length, subul(), subull(), and timenow().
Referenced by main().
int main (int argc, char ** argv)
Definition at line 175 of file routerstat.c.
References cfs_free_param_data(), cfs_get_param_paths(), do_stat(), and path.
double rul (unsigned long a, double secs)
Definition at line 89 of file routerstat.c.
Referenced by do_stat().
double rull (unsigned long long a, double secs)
Definition at line 94 of file routerstat.c.
Referenced by do_stat().
unsigned long long subul (unsigned long a, unsigned long b)
Definition at line 81 of file routerstat.c.
Referenced by do_stat().
unsigned long long subull (unsigned long long a, unsigned long long b)
Definition at line 73 of file routerstat.c.
Referenced by do_stat().
double timenow ()
Definition at line 51 of file routerstat.c.
Referenced by do_stat().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.