Lustre: lnet/selftest/rpc.c File Reference
lnet/selftest/rpc.c File Reference
#include "selftest.h"
Data Structures
struct smoketest_rpc
Defines
#define DEBUG_SUBSYSTEM S_LNET
Enumerations
enum srpc_state_t {
SRPC_STATE_NONE, SRPC_STATE_NI_INIT, SRPC_STATE_EQ_INIT, SRPC_STATE_RUNNING,
SRPC_STATE_STOPPING
}
Functions
static int srpc_serv_portal (int svc_id)
int srpc_handle_rpc (swi_workitem_t *wi)
void srpc_get_counters (srpc_counters_t *cnt)
void srpc_set_counters (const srpc_counters_t *cnt)
static int srpc_add_bulk_page (srpc_bulk_t *bk, struct page *pg, int i, int nob)
void srpc_free_bulk (srpc_bulk_t *bk)
srpc_bulk_t * srpc_alloc_bulk (int cpt, unsigned bulk_npg, unsigned bulk_len, int sink)
static __u64 srpc_next_id (void)
static void srpc_init_server_rpc (struct srpc_server_rpc *rpc, struct srpc_service_cd *scd, struct srpc_buffer *buffer)
static void srpc_service_fini (struct srpc_service *svc)
static int srpc_service_nrpcs (struct srpc_service *svc)
int srpc_add_buffer (struct swi_workitem *wi)
static int srpc_service_init (struct srpc_service *svc)
int srpc_add_service (struct srpc_service *sv)
int srpc_remove_service (srpc_service_t *sv)
static int srpc_post_passive_rdma (int portal, int local, __u64 matchbits, void *buf, int len, int options, lnet_process_id_t peer, lnet_handle_md_t *mdh, srpc_event_t *ev)
static int srpc_post_active_rdma (int portal, __u64 matchbits, void *buf, int len, int options, lnet_process_id_t peer, lnet_nid_t self, lnet_handle_md_t *mdh, srpc_event_t *ev)
static int srpc_post_passive_rqtbuf (int service, int local, void *buf, int len, lnet_handle_md_t *mdh, srpc_event_t *ev)
static int srpc_service_post_buffer (struct srpc_service_cd *scd, struct srpc_buffer *buf) __must_hold(&scd->scd_lock)
int srpc_service_add_buffers (struct srpc_service *sv, int nbuffer)
void srpc_service_remove_buffers (struct srpc_service *sv, int nbuffer)
int srpc_finish_service (struct srpc_service *sv)
static void srpc_service_recycle_buffer (struct srpc_service_cd *scd, srpc_buffer_t *buf) __must_hold(&scd->scd_lock)
void srpc_abort_service (struct srpc_service *sv)
void srpc_shutdown_service (srpc_service_t *sv)
static int srpc_send_request (srpc_client_rpc_t *rpc)
static int srpc_prepare_reply (srpc_client_rpc_t *rpc)
static int srpc_prepare_bulk (srpc_client_rpc_t *rpc)
static int srpc_do_bulk (srpc_server_rpc_t *rpc)
static void srpc_server_rpc_done (srpc_server_rpc_t *rpc, int status)
static void srpc_client_rpc_expired (void *data)
static void srpc_add_client_rpc_timer (srpc_client_rpc_t *rpc)
static void srpc_del_client_rpc_timer (srpc_client_rpc_t *rpc)
static void srpc_client_rpc_done (srpc_client_rpc_t *rpc, int status)
int srpc_send_rpc (swi_workitem_t *wi)
srpc_client_rpc_t * srpc_create_client_rpc (lnet_process_id_t peer, int service, int nbulkiov, int bulklen, void(*rpc_done)(srpc_client_rpc_t *), void(*rpc_fini)(srpc_client_rpc_t *), void *priv)
void srpc_abort_rpc (srpc_client_rpc_t *rpc, int why)
void srpc_post_rpc (srpc_client_rpc_t *rpc)
int srpc_send_reply (struct srpc_server_rpc *rpc)
static void srpc_lnet_ev_handler (lnet_event_t *ev)
int srpc_startup (void)
void srpc_shutdown (void)
Variables
static struct smoketest_rpc srpc_data
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 45 of file rpc.c.
Enumeration Type Documentation
enum srpc_state_t
Enumerator:
SRPC_STATE_NONE
SRPC_STATE_NI_INIT
SRPC_STATE_EQ_INIT
SRPC_STATE_RUNNING
SRPC_STATE_STOPPING
Definition at line 49 of file rpc.c.
Function Documentation
void srpc_abort_rpc (srpc_client_rpc_t * rpc, int why)
Definition at line 1311 of file rpc.c.
References CDEBUG, srpc_client_rpc::crpc_aborted, srpc_client_rpc::crpc_closed, srpc_client_rpc::crpc_dest, srpc_client_rpc::crpc_service, srpc_client_rpc::crpc_status, srpc_client_rpc::crpc_wi, D_NET, LASSERT, libcfs_id2str(), swi_schedule_workitem(), swi_workitem::swi_state, and swi_state2str().
Referenced by sfw_abort_rpc(), sfw_stop_batch(), srpc_client_rpc_expired(), and srpc_send_rpc().
void srpc_abort_service (struct srpc_service * sv)
Definition at line 723 of file rpc.c.
References CDEBUG, cfs_percpt_for_each, D_NET, list_for_each_entry, srpc_service_cd::scd_lock, srpc_service_cd::scd_rpc_active, srpc_server_rpc::srpc_aborted, srpc_server_rpc::srpc_list, srpc_server_rpc::srpc_wi, srpc_service::sv_cpt_data, srpc_service::sv_id, srpc_service::sv_name, and swi_schedule_workitem().
Referenced by sfw_deactivate_session().
int srpc_add_buffer (struct swi_workitem * wi)
Definition at line 509 of file rpc.c.
References buf, CERROR, cfs_time_current_sec(), LASSERT, LIBCFS_ALLOC, LIBCFS_FREE, MAX, srpc_service_cd::scd_buf_adjust, srpc_service_cd::scd_buf_err, srpc_service_cd::scd_buf_err_stamp, srpc_service_cd::scd_buf_low, srpc_service_cd::scd_buf_posting, srpc_service_cd::scd_buf_total, srpc_service_cd::scd_lock, srpc_service_cd::scd_svc, srpc_service_post_buffer(), srpc_service::sv_name, srpc_service::sv_shuttingdown, swi_workitem::swi_workitem, and cfs_workitem::wi_data.
Referenced by srpc_service_init().
static int srpc_add_bulk_page (srpc_bulk_t * bk, struct page * pg, int i, int nob) [static]
Definition at line 91 of file rpc.c.
References srpc_bulk_t::bk_iovs, lnet_kiov_t::kiov_len, lnet_kiov_t::kiov_offset, lnet_kiov_t::kiov_page, and LASSERT.
Referenced by srpc_alloc_bulk().
static void srpc_add_client_rpc_timer (srpc_client_rpc_t * rpc) [static]
Definition at line 1085 of file rpc.c.
References cfs_time_add(), cfs_time_current_sec(), srpc_client_rpc::crpc_timeout, srpc_client_rpc::crpc_timer, INIT_LIST_HEAD, srpc_client_rpc_expired(), stt_add_timer(), stt_timer_t::stt_data, stt_timer_t::stt_expires, stt_timer_t::stt_func, and stt_timer_t::stt_list.
Referenced by srpc_post_rpc().
int srpc_add_service (struct srpc_service * sv)
Definition at line 307 of file rpc.c.
References CDEBUG, D_NET, LASSERT, smoketest_rpc::rpc_glock, smoketest_rpc::rpc_services, smoketest_rpc::rpc_state, srpc_data, srpc_service_fini(), srpc_service_init(), SRPC_SERVICE_MAX_ID, SRPC_STATE_RUNNING, srpc_service::sv_id, and srpc_service::sv_name.
Referenced by lstcon_console_init(), and sfw_startup().
srpc_bulk_t* srpc_alloc_bulk (int cpt, unsigned bulk_npg, unsigned bulk_len, int sink)
Definition at line 124 of file rpc.c.
References srpc_bulk_t::bk_len, srpc_bulk_t::bk_niov, srpc_bulk_t::bk_sink, CERROR, cfs_page_cpt_alloc(), LASSERT, LIBCFS_CPT_ALLOC, lnet_cpt_table, LNET_MAX_IOV, offsetof, srpc_add_bulk_page(), and srpc_free_bulk().
Referenced by brw_client_init(), and sfw_alloc_pages().
static void srpc_client_rpc_done (srpc_client_rpc_t * rpc, int status) [static]
Definition at line 1128 of file rpc.c.
References CDEBUG_LIMIT, srpc_client_rpc::crpc_aborted, srpc_client_rpc::crpc_closed, srpc_client_rpc::crpc_dest, srpc_client_rpc::crpc_done, srpc_client_rpc::crpc_lock, srpc_client_rpc::crpc_service, srpc_client_rpc::crpc_status, srpc_client_rpc::crpc_wi, D_NET, D_NETERROR, LASSERT, libcfs_id2str(), srpc_del_client_rpc_timer(), srpc_event_pending, swi_exit_workitem(), swi_workitem::swi_state, swi_state2str(), and SWI_STATE_DONE.
Referenced by srpc_send_rpc().
static void srpc_client_rpc_expired (void * data) [static]
Definition at line 1064 of file rpc.c.
References srpc_client_rpc::crpc_dest, srpc_client_rpc::crpc_lock, srpc_client_rpc::crpc_service, srpc_client_rpc::crpc_timeout, CWARN, libcfs_id2str(), smoketest_rpc::rpc_counters, smoketest_rpc::rpc_glock, srpc_abort_rpc(), and srpc_data.
Referenced by srpc_add_client_rpc_timer().
srpc_client_rpc_t* srpc_create_client_rpc (lnet_process_id_t peer, int service, int nbulkiov, int bulklen, void(*)(srpc_client_rpc_t *) rpc_done, void(*)(srpc_client_rpc_t *) rpc_fini, void * priv)
Definition at line 1292 of file rpc.c.
References LIBCFS_ALLOC, offsetof, and srpc_init_client_rpc().
Referenced by sfw_create_rpc(), and sfw_create_test_rpc().
static void srpc_del_client_rpc_timer (srpc_client_rpc_t * rpc) [static]
Definition at line 1107 of file rpc.c.
References srpc_client_rpc::crpc_lock, srpc_client_rpc::crpc_timeout, srpc_client_rpc::crpc_timer, and stt_del_timer().
Referenced by srpc_client_rpc_done().
static int srpc_do_bulk (srpc_server_rpc_t * rpc) [static]
Definition at line 861 of file rpc.c.
References __u64, srpc_bulk_t::bk_iovs, srpc_bulk_t::bk_mdh, srpc_bulk_t::bk_niov, srpc_bulk_t::bk_sink, srpc_buffer::buf_msg, srpc_event_t::ev_data, srpc_event_t::ev_fired, srpc_event_t::ev_type, LASSERT, LNET_MD_KIOV, LNET_MD_OP_GET, LNET_MD_OP_PUT, srpc_msg::msg_body, opt, srpc_msg::reqst, srpc_server_rpc::srpc_bulk, SRPC_BULK_GET_RPLD, SRPC_BULK_PUT_SENT, srpc_server_rpc::srpc_ev, srpc_server_rpc::srpc_peer, srpc_post_active_rdma(), SRPC_RDMA_PORTAL, srpc_server_rpc::srpc_reqstbuf, and srpc_server_rpc::srpc_self.
Referenced by srpc_handle_rpc().
int srpc_finish_service (struct srpc_service * sv)
Definition at line 643 of file rpc.c.
References CDEBUG, cfs_percpt_for_each, CNETERR, D_NET, srpc_event_t::ev_fired, srpc_event_t::ev_lnet, srpc_event_t::ev_status, srpc_event_t::ev_type, LASSERT, libcfs_id2str(), list_empty(), list_entry, list_head::next, srpc_service_cd::scd_buf_nposted, srpc_service_cd::scd_buf_wi, srpc_service_cd::scd_lock, srpc_service_cd::scd_rpc_active, srpc_server_rpc::srpc_ev, srpc_server_rpc::srpc_list, srpc_server_rpc::srpc_peer, srpc_service_fini(), srpc_server_rpc::srpc_wi, srpc_service::sv_cpt_data, srpc_service::sv_name, srpc_service::sv_shuttingdown, swi_deschedule_workitem(), swi_workitem::swi_state, swi_state2str(), swi_workitem::swi_workitem, cfs_workitem::wi_running, and cfs_workitem::wi_scheduled.
Referenced by srpc_wait_service_shutdown().
void srpc_free_bulk (srpc_bulk_t * bk)
Definition at line 105 of file rpc.c.
References srpc_bulk_t::bk_iovs, srpc_bulk_t::bk_niov, lnet_kiov_t::kiov_page, LASSERT, LIBCFS_FREE, and offsetof.
Referenced by brw_client_fini(), sfw_free_pages(), and srpc_alloc_bulk().
void srpc_get_counters (srpc_counters_t * cnt)
Definition at line 76 of file rpc.c.
References smoketest_rpc::rpc_counters, smoketest_rpc::rpc_glock, and srpc_data.
Referenced by sfw_get_stats().
int srpc_handle_rpc (swi_workitem_t * wi)
Definition at line 952 of file rpc.c.
References srpc_bulk_t::bk_mdh, srpc_buffer::buf_msg, CERROR, CWARN, srpc_event_t::ev_fired, srpc_event_t::ev_lnet, srpc_event_t::ev_status, srpc_event_t::ev_type, LASSERT, LBUG, libcfs_id2str(), LNetMDUnlink(), msg, srpc_msg::msg_body, srpc_msg::msg_magic, srpc_msg::msg_version, srpc_msg::reply, srpc_service_cd::scd_lock, srpc_service_cd::scd_svc, srpc_server_rpc::srpc_aborted, srpc_server_rpc::srpc_bulk, srpc_do_bulk(), srpc_server_rpc::srpc_ev, SRPC_MSG_VERSION, srpc_server_rpc::srpc_peer, srpc_server_rpc::srpc_replymdh, srpc_server_rpc::srpc_replymsg, srpc_server_rpc::srpc_reqstbuf, srpc_server_rpc::srpc_scd, srpc_send_reply(), srpc_server_rpc_done(), srpc_unpack_msg_hdr(), srpc_server_rpc::srpc_wi, srpc_service::sv_bulk_ready, srpc_service::sv_handler, srpc_service::sv_id, srpc_service::sv_shuttingdown, swi_workitem::swi_state, SWI_STATE_BULK_STARTED, SWI_STATE_DONE, SWI_STATE_NEWBORN, SWI_STATE_REPLY_SUBMITTED, swi_workitem::swi_workitem, and cfs_workitem::wi_data.
Referenced by srpc_init_server_rpc().
static void srpc_init_server_rpc (struct srpc_server_rpc * rpc, struct srpc_service_cd * scd, struct srpc_buffer * buffer) [static]
Definition at line 173 of file rpc.c.
References srpc_buffer::buf_peer, srpc_buffer::buf_self, srpc_event_t::ev_fired, LNetInvalidateHandle(), lst_sched_serial, lst_sched_test, srpc_service_cd::scd_cpt, srpc_service_cd::scd_svc, srpc_server_rpc::srpc_ev, srpc_handle_rpc(), srpc_server_rpc::srpc_peer, srpc_server_rpc::srpc_replymdh, srpc_server_rpc::srpc_reqstbuf, srpc_server_rpc::srpc_scd, srpc_server_rpc::srpc_self, srpc_serv_is_framework(), srpc_server_rpc::srpc_wi, and swi_init_workitem().
Referenced by srpc_lnet_ev_handler(), and srpc_server_rpc_done().
static void srpc_lnet_ev_handler (lnet_event_t * ev) [static]
Definition at line 1392 of file rpc.c.
References __swab32, srpc_buffer::buf_list, srpc_buffer::buf_msg, srpc_buffer::buf_peer, srpc_buffer::buf_self, CERROR, cfs_time_current_sec(), CNETERR, srpc_client_rpc::crpc_bulkev, srpc_client_rpc::crpc_lock, srpc_client_rpc::crpc_replyev, srpc_client_rpc::crpc_reqstev, srpc_client_rpc::crpc_wi, errors, srpc_event_t::ev_data, srpc_event_t::ev_fired, srpc_event_t::ev_lnet, srpc_event_t::ev_status, srpc_event_t::ev_type, lnet_event_t::initiator, LASSERT, LBUG, libcfs_id2str(), list_add_tail(), list_del(), list_empty(), list_entry, LNET_EVENT_PUT, LNET_EVENT_REPLY, LNET_EVENT_SEND, LNET_EVENT_UNLINK, MAX, lnet_event_t::md, lnet_event_t::mlength, msg, srpc_msg::msg_magic, srpc_msg::msg_type, list_head::next, lnet_process_id_t::nid, smoketest_rpc::rpc_counters, smoketest_rpc::rpc_glock, srpc_service_cd::scd_buf_adjust, srpc_service_cd::scd_buf_blocked, srpc_service_cd::scd_buf_err, srpc_service_cd::scd_buf_err_stamp, srpc_service_cd::scd_buf_low, srpc_service_cd::scd_buf_nposted, srpc_service_cd::scd_buf_total, srpc_service_cd::scd_buf_wi, srpc_service_cd::scd_ev, srpc_service_cd::scd_lock, srpc_service_cd::scd_rpc_active, srpc_service_cd::scd_rpc_free, srpc_service_cd::scd_svc, SFW_TEST_WI_MIN, SRPC_BULK_GET_RPLD, SRPC_BULK_PUT_SENT, SRPC_BULK_REQ_RCVD, srpc_data, srpc_server_rpc::srpc_ev, srpc_init_server_rpc(), srpc_server_rpc::srpc_list, SRPC_MSG_MAGIC, SRPC_REPLY_RCVD, SRPC_REPLY_SENT, SRPC_REQUEST_RCVD, SRPC_REQUEST_SENT, srpc_server_rpc::srpc_scd, srpc_service2request(), srpc_server_rpc::srpc_wi, lnet_md_t::start, lnet_event_t::status, srpc_service::sv_id, srpc_service::sv_name, srpc_service::sv_shuttingdown, swi_schedule_workitem(), lnet_event_t::target, lnet_event_t::type, lnet_event_t::unlinked, and lnet_md_t::user_ptr.
Referenced by srpc_startup().
static __u64 srpc_next_id (void) [inline, static]
Definition at line 162 of file rpc.c.
References __u64, smoketest_rpc::rpc_glock, smoketest_rpc::rpc_matchbits, and srpc_data.
Referenced by srpc_prepare_bulk(), and srpc_prepare_reply().
static int srpc_post_active_rdma (int portal, __u64 matchbits, void * buf, int len, int options, lnet_process_id_t peer, lnet_nid_t self, lnet_handle_md_t * mdh, srpc_event_t * ev) [static]
Definition at line 394 of file rpc.c.
References CDEBUG, CERROR, D_NET, lnet_md_t::eq_handle, LASSERT, lnet_md_t::length, libcfs_id2str(), LNET_MD_OP_GET, LNET_MD_OP_PUT, LNET_NOACK_REQ, LNET_UNLINK, LNetGet(), LNetMDBind(), LNetMDUnlink(), LNetPut(), LPD64, LPX64, lnet_md_t::options, smoketest_rpc::rpc_lnet_eq, srpc_data, lnet_md_t::start, lnet_md_t::threshold, and lnet_md_t::user_ptr.
Referenced by srpc_do_bulk(), srpc_send_reply(), and srpc_send_request().
static int srpc_post_passive_rdma (int portal, int local, __u64 matchbits, void * buf, int len, int options, lnet_process_id_t peer, lnet_handle_md_t * mdh, srpc_event_t * ev) [static]
Definition at line 354 of file rpc.c.
References CDEBUG, CERROR, D_NET, lnet_md_t::eq_handle, LASSERT, lnet_md_t::length, libcfs_id2str(), LNET_INS_AFTER, LNET_INS_LOCAL, LNET_UNLINK, LNetMDAttach(), LNetMEAttach(), LNetMEUnlink(), LPX64, lnet_md_t::options, smoketest_rpc::rpc_lnet_eq, srpc_data, lnet_md_t::start, lnet_md_t::threshold, and lnet_md_t::user_ptr.
Referenced by srpc_post_passive_rqtbuf(), srpc_prepare_bulk(), and srpc_prepare_reply().
static int srpc_post_passive_rqtbuf (int service, int local, void * buf, int len, lnet_handle_md_t * mdh, srpc_event_t * ev) [static]
Definition at line 446 of file rpc.c.
References LNET_MD_OP_PUT, LNET_NID_ANY, LNET_PID_ANY, lnet_process_id_t::nid, lnet_process_id_t::pid, srpc_post_passive_rdma(), and srpc_serv_portal().
Referenced by srpc_service_post_buffer().
void srpc_post_rpc (srpc_client_rpc_t * rpc)
Definition at line 1332 of file rpc.c.
References CDEBUG, srpc_client_rpc::crpc_aborted, srpc_client_rpc::crpc_dest, srpc_client_rpc::crpc_service, srpc_client_rpc::crpc_timeout, srpc_client_rpc::crpc_wi, D_NET, LASSERT, libcfs_id2str(), smoketest_rpc::rpc_state, srpc_add_client_rpc_timer(), srpc_data, SRPC_STATE_RUNNING, and swi_schedule_workitem().
Referenced by sfw_post_rpc(), and sfw_run_test().
static int srpc_prepare_bulk (srpc_client_rpc_t * rpc) [static]
Definition at line 829 of file rpc.c.
References __u64, srpc_bulk_t::bk_iovs, srpc_bulk_t::bk_mdh, srpc_bulk_t::bk_niov, srpc_bulk_t::bk_sink, srpc_client_rpc::crpc_bulk, srpc_client_rpc::crpc_bulkev, srpc_client_rpc::crpc_dest, srpc_client_rpc::crpc_reqstmsg, srpc_event_t::ev_data, srpc_event_t::ev_fired, srpc_event_t::ev_type, LASSERT, LNET_MAX_IOV, LNET_MD_KIOV, LNET_MD_OP_GET, LNET_MD_OP_PUT, srpc_msg::msg_body, opt, srpc_msg::reqst, SRPC_BULK_REQ_RCVD, srpc_next_id(), srpc_post_passive_rdma(), and SRPC_RDMA_PORTAL.
Referenced by srpc_send_rpc().
static int srpc_prepare_reply (srpc_client_rpc_t * rpc) [static]
Definition at line 805 of file rpc.c.
References __u64, srpc_client_rpc::crpc_dest, srpc_client_rpc::crpc_replyev, srpc_client_rpc::crpc_replymdh, srpc_client_rpc::crpc_replymsg, srpc_client_rpc::crpc_reqstmsg, srpc_event_t::ev_data, srpc_event_t::ev_fired, srpc_event_t::ev_type, LASSERT, LNET_MD_OP_PUT, srpc_msg::msg_body, srpc_msg::reqst, srpc_next_id(), srpc_post_passive_rdma(), SRPC_RDMA_PORTAL, and SRPC_REPLY_RCVD.
Referenced by srpc_send_rpc().
int srpc_remove_service (srpc_service_t * sv)
Definition at line 337 of file rpc.c.
References smoketest_rpc::rpc_glock, smoketest_rpc::rpc_services, srpc_data, and srpc_service::sv_id.
Referenced by lstcon_console_fini(), lstcon_console_init(), and sfw_shutdown().
int srpc_send_reply (struct srpc_server_rpc * rpc)
Definition at line 1348 of file rpc.c.
References __u64, srpc_buffer::buf_msg, CWARN, srpc_event_t::ev_data, srpc_event_t::ev_fired, srpc_event_t::ev_type, LASSERT, LNET_MD_OP_PUT, msg, srpc_msg::msg_body, srpc_msg::msg_magic, srpc_msg::msg_type, srpc_msg::msg_version, srpc_msg::reqst, srpc_service_cd::scd_lock, srpc_service_cd::scd_svc, srpc_server_rpc::srpc_ev, SRPC_MSG_MAGIC, SRPC_MSG_VERSION, srpc_server_rpc::srpc_peer, srpc_post_active_rdma(), SRPC_RDMA_PORTAL, SRPC_REPLY_SENT, srpc_server_rpc::srpc_replymdh, srpc_server_rpc::srpc_replymsg, srpc_server_rpc::srpc_reqstbuf, srpc_server_rpc::srpc_scd, srpc_server_rpc::srpc_self, srpc_serv_is_framework(), srpc_service2reply(), srpc_service_post_buffer(), srpc_service::sv_id, srpc_service::sv_name, and srpc_service::sv_shuttingdown.
Referenced by srpc_handle_rpc().
static int srpc_send_request (srpc_client_rpc_t * rpc) [static]
Definition at line 783 of file rpc.c.
References srpc_client_rpc::crpc_dest, srpc_client_rpc::crpc_reqstev, srpc_client_rpc::crpc_reqstmdh, srpc_client_rpc::crpc_reqstmsg, srpc_client_rpc::crpc_service, srpc_event_t::ev_data, srpc_event_t::ev_fired, srpc_event_t::ev_type, LASSERT, LNET_MD_OP_PUT, LNET_NID_ANY, srpc_post_active_rdma(), SRPC_REQUEST_SENT, and srpc_serv_portal().
Referenced by srpc_send_rpc().
int srpc_send_rpc (swi_workitem_t * wi)
Definition at line 1166 of file rpc.c.
References __swab32, srpc_bulk_t::bk_mdh, srpc_bulk_t::bk_niov, srpc_client_rpc::crpc_aborted, srpc_client_rpc::crpc_bulk, srpc_client_rpc::crpc_bulkev, srpc_client_rpc::crpc_dest, srpc_client_rpc::crpc_lock, srpc_client_rpc::crpc_replyev, srpc_client_rpc::crpc_replymdh, srpc_client_rpc::crpc_replymsg, srpc_client_rpc::crpc_reqstev, srpc_client_rpc::crpc_reqstmdh, srpc_client_rpc::crpc_service, srpc_client_rpc::crpc_status, srpc_client_rpc::crpc_wi, CWARN, srpc_event_t::ev_fired, srpc_event_t::ev_lnet, srpc_event_t::ev_status, LASSERT, LBUG, libcfs_id2str(), LNET_EVENT_UNLINK, LNetMDUnlink(), srpc_msg::msg_body, srpc_msg::msg_magic, srpc_msg::msg_type, srpc_msg::reply, srpc_abort_rpc(), srpc_client_rpc_done(), srpc_event_pending, SRPC_MSG_MAGIC, srpc_prepare_bulk(), srpc_prepare_reply(), srpc_send_request(), srpc_service2reply(), srpc_unpack_msg_hdr(), swi_workitem::swi_state, SWI_STATE_DONE, SWI_STATE_NEWBORN, SWI_STATE_REPLY_RECEIVED, SWI_STATE_REQUEST_SENT, SWI_STATE_REQUEST_SUBMITTED, swi_workitem::swi_workitem, and cfs_workitem::wi_data.
Referenced by srpc_init_client_rpc().
static int srpc_serv_portal (int svc_id) [inline, static]
Definition at line 67 of file rpc.c.
References SRPC_FRAMEWORK_REQUEST_PORTAL, SRPC_FRAMEWORK_SERVICE_MAX_ID, and SRPC_REQUEST_PORTAL.
Referenced by srpc_post_passive_rqtbuf(), and srpc_send_request().
static void srpc_server_rpc_done (srpc_server_rpc_t * rpc, int status) [static]
Definition at line 889 of file rpc.c.
References srpc_buffer::buf_list, CDEBUG_LIMIT, D_NET, D_NETERROR, srpc_event_t::ev_fired, LASSERT, libcfs_id2str(), list_add(), list_add_tail(), list_del(), list_empty(), list_entry, list_head::next, smoketest_rpc::rpc_counters, smoketest_rpc::rpc_glock, srpc_service_cd::scd_buf_blocked, srpc_service_cd::scd_lock, srpc_service_cd::scd_rpc_active, srpc_service_cd::scd_rpc_free, srpc_service_cd::scd_svc, srpc_server_rpc::srpc_bulk, srpc_data, srpc_server_rpc::srpc_done, srpc_server_rpc::srpc_ev, srpc_init_server_rpc(), srpc_server_rpc::srpc_list, srpc_server_rpc::srpc_peer, srpc_server_rpc::srpc_reqstbuf, srpc_server_rpc::srpc_scd, srpc_service_recycle_buffer(), srpc_server_rpc::srpc_status, srpc_server_rpc::srpc_wi, srpc_service::sv_name, srpc_service::sv_shuttingdown, swi_exit_workitem(), swi_schedule_workitem(), swi_workitem::swi_state, swi_state2str(), and SWI_STATE_DONE.
Referenced by srpc_handle_rpc().
int srpc_service_add_buffers (struct srpc_service * sv, int nbuffer)
Definition at line 569 of file rpc.c.
References cfs_percpt_for_each, LASSERTF, lst_wait_until, srpc_service_cd::scd_buf_adjust, srpc_service_cd::scd_buf_err, srpc_service_cd::scd_buf_err_stamp, srpc_service_cd::scd_buf_posting, srpc_service_cd::scd_buf_wi, srpc_service_cd::scd_lock, srpc_serv_is_framework(), srpc_service::sv_cpt_data, and swi_schedule_workitem().
Referenced by lstcon_console_init(), sfw_load_test(), and sfw_startup().
static void srpc_service_fini (struct srpc_service * svc) [static]
Definition at line 192 of file rpc.c.
References buf, srpc_buffer::buf_list, cfs_percpt_for_each, cfs_percpt_free(), LASSERT, LIBCFS_FREE, list_del(), list_empty(), list_entry, list_head::next, srpc_service_cd::scd_buf_blocked, srpc_service_cd::scd_buf_posted, srpc_service_cd::scd_rpc_active, srpc_service_cd::scd_rpc_free, srpc_server_rpc::srpc_list, and srpc_service::sv_cpt_data.
Referenced by srpc_add_service(), srpc_finish_service(), and srpc_service_init().
static int srpc_service_init (struct srpc_service * svc) [static]
Definition at line 248 of file rpc.c.
References cfs_cpt_number(), cfs_percpt_alloc(), cfs_percpt_for_each, srpc_event_t::ev_data, srpc_event_t::ev_type, INIT_LIST_HEAD, LIBCFS_CPT_ALLOC, list_add(), lnet_cpt_table, lst_sched_test, srpc_service_cd::scd_buf_blocked, srpc_service_cd::scd_buf_posted, srpc_service_cd::scd_buf_wi, srpc_service_cd::scd_cpt, srpc_service_cd::scd_ev, srpc_service_cd::scd_lock, srpc_service_cd::scd_rpc_active, srpc_service_cd::scd_rpc_free, srpc_service_cd::scd_svc, srpc_add_buffer(), srpc_server_rpc::srpc_list, SRPC_REQUEST_RCVD, srpc_serv_is_framework(), srpc_service_fini(), srpc_service_nrpcs(), srpc_service::sv_cpt_data, srpc_service::sv_ncpts, srpc_service::sv_shuttingdown, and swi_init_workitem().
Referenced by srpc_add_service().
static int srpc_service_nrpcs (struct srpc_service * svc) [static]
Definition at line 237 of file rpc.c.
References max, SFW_FRWK_WI_MIN, SFW_TEST_WI_MIN, srpc_serv_is_framework(), srpc_service::sv_ncpts, and srpc_service::sv_wi_total.
Referenced by srpc_service_init().
static int srpc_service_post_buffer (struct srpc_service_cd * scd, struct srpc_buffer * buf) [static]
Definition at line 460 of file rpc.c.
References buf, LIBCFS_FREE, list_add(), list_del(), LNetInvalidateHandle(), LNetMDUnlink(), msg, srpc_post_passive_rqtbuf(), srpc_serv_is_framework(), srpc_service::sv_id, and srpc_service::sv_shuttingdown.
Referenced by srpc_add_buffer(), srpc_send_reply(), and srpc_service_recycle_buffer().
static void srpc_service_recycle_buffer (struct srpc_service_cd * scd, srpc_buffer_t * buf) [static]
Definition at line 692 of file rpc.c.
References buf, CDEBUG, CWARN, D_INFO, LIBCFS_FREE, and srpc_service_post_buffer().
Referenced by srpc_server_rpc_done().
void srpc_service_remove_buffers (struct srpc_service * sv, int nbuffer)
Definition at line 623 of file rpc.c.
References cfs_percpt_for_each, LASSERT, srpc_service_cd::scd_buf_adjust, srpc_service_cd::scd_buf_posting, srpc_service_cd::scd_buf_total, srpc_service_cd::scd_lock, srpc_service::sv_cpt_data, and srpc_service::sv_shuttingdown.
Referenced by sfw_load_test(), and sfw_unload_test().
void srpc_set_counters (const srpc_counters_t * cnt)
Definition at line 83 of file rpc.c.
References smoketest_rpc::rpc_counters, smoketest_rpc::rpc_glock, and srpc_data.
void srpc_shutdown (void)
Definition at line 1630 of file rpc.c.
References LASSERT, LASSERTF, LBUG, LNetClearLazyPortal(), LNetEQFree(), LNetNIFini(), smoketest_rpc::rpc_glock, smoketest_rpc::rpc_lnet_eq, smoketest_rpc::rpc_services, smoketest_rpc::rpc_state, srpc_data, SRPC_FRAMEWORK_REQUEST_PORTAL, SRPC_REQUEST_PORTAL, SRPC_SERVICE_MAX_ID, SRPC_STATE_EQ_INIT, SRPC_STATE_NI_INIT, SRPC_STATE_RUNNING, SRPC_STATE_STOPPING, state, stt_shutdown(), and srpc_service::sv_name.
Referenced by lnet_selftest_exit(), and srpc_startup().
void srpc_shutdown_service (srpc_service_t * sv)
Definition at line 748 of file rpc.c.
References buf, srpc_buffer::buf_mdh, CDEBUG, cfs_percpt_for_each, D_NET, list_for_each_entry, LNetMDUnlink(), srpc_service_cd::scd_buf_posted, srpc_service_cd::scd_lock, srpc_service_cd::scd_rpc_active, srpc_server_rpc::srpc_list, srpc_server_rpc::srpc_wi, srpc_service::sv_cpt_data, srpc_service::sv_id, srpc_service::sv_name, srpc_service::sv_shuttingdown, and swi_schedule_workitem().
Referenced by lstcon_console_fini(), lstcon_console_init(), and sfw_shutdown().
int srpc_startup (void)
Definition at line 1582 of file rpc.c.
References __u64, CERROR, cfs_time_current_sec(), cfs_time_seconds(), LASSERT, LNET_PID_LUSTRE, LNetEQAlloc(), LNetInvalidateHandle(), LNetNIInit(), LNetSetLazyPortal(), smoketest_rpc::rpc_glock, smoketest_rpc::rpc_lnet_eq, smoketest_rpc::rpc_matchbits, smoketest_rpc::rpc_state, srpc_data, SRPC_FRAMEWORK_REQUEST_PORTAL, srpc_lnet_ev_handler(), SRPC_REQUEST_PORTAL, srpc_shutdown(), SRPC_STATE_EQ_INIT, SRPC_STATE_NI_INIT, SRPC_STATE_NONE, SRPC_STATE_RUNNING, and stt_startup().
Referenced by lnet_selftest_init().
Variable Documentation
struct smoketest_rpc srpc_data [static]
Referenced by srpc_add_service(), srpc_client_rpc_expired(), srpc_get_counters(), srpc_lnet_ev_handler(), srpc_next_id(), srpc_post_active_rdma(), srpc_post_passive_rdma(), srpc_post_rpc(), srpc_remove_service(), srpc_server_rpc_done(), srpc_set_counters(), srpc_shutdown(), and srpc_startup().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.