Lustre: lustre/llite/rw26.c File Reference
lustre/llite/rw26.c File Reference
#include <linux/kernel.h>
#include <linux/mm.h>
#include <linux/string.h>
#include <linux/stat.h>
#include <linux/errno.h>
#include <linux/unistd.h>
#include <asm/uaccess.h>
#include <linux/fs.h>
#include <linux/buffer_head.h>
#include <linux/mpage.h>
#include <linux/writeback.h>
#include <linux/pagemap.h>
#include "llite_internal.h"
#include <lustre_compat.h>
Defines
#define DEBUG_SUBSYSTEM S_LLITE
#define RELEASEPAGE_ARG_TYPE gfp_t
#define MAX_DIRECTIO_SIZE 2*1024*1024*1024UL
#define MAX_MALLOC (128 * 1024)
#define MAX_DIO_SIZE
#define iov_iter_rw(iter) rw
Functions
static void ll_invalidatepage (struct page *vmpage, unsigned long offset)
Implements Linux VM address_space::invalidatepage() method.
static int ll_releasepage (struct page *vmpage, RELEASEPAGE_ARG_TYPE gfp_mask)
ssize_t ll_direct_rw_pages (const struct lu_env *env, struct cl_io *io, int rw, struct inode *inode, struct ll_dio_pages *pv)
static ssize_t ll_direct_IO_seg (const struct lu_env *env, struct cl_io *io, int rw, struct inode *inode, size_t size, loff_t file_offset, struct page **pages, int page_count)
static void ll_free_user_pages (struct page **pages, int npages, int do_dirty)
static int ll_get_user_pages (int rw, unsigned long user_addr, size_t size, struct page ***pages, int *max_pages)
static ssize_t ll_direct_IO (int rw, struct kiocb *iocb, const struct iovec *iov, loff_t file_offset, unsigned long nr_segs)
static int ll_prepare_partial_page (const struct lu_env *env, struct cl_io *io, struct cl_page *pg)
Prepare partially written-to page for a write.
static int ll_write_begin (struct file *file, struct address_space *mapping, loff_t pos, unsigned len, unsigned flags, struct page **pagep, void **fsdata)
static int ll_write_end (struct file *file, struct address_space *mapping, loff_t pos, unsigned len, unsigned copied, struct page *vmpage, void *fsdata)
Variables
struct address_space_operations ll_aops
Define Documentation
#define DEBUG_SUBSYSTEM S_LLITE
Definition at line 63 of file rw26.c.
#define iov_iter_rw (iter) rw
Definition at line 346 of file rw26.c.
#define MAX_DIO_SIZE
Value:
((MAX_MALLOC / sizeof(struct brw_page) * PAGE_CACHE_SIZE) & \
                      ~(DT_MAX_BRW_SIZE - 1))
Definition at line 342 of file rw26.c.
Referenced by ll_direct_IO().
#define MAX_DIRECTIO_SIZE 2*1024*1024*1024UL
Definition at line 187 of file rw26.c.
Referenced by ll_get_user_pages().
#define MAX_MALLOC (128 * 1024)
Definition at line 334 of file rw26.c.
#define RELEASEPAGE_ARG_TYPE gfp_t
Definition at line 126 of file rw26.c.
Function Documentation
static ssize_t ll_direct_IO (int rw, struct kiocb * iocb, const struct iovec * iov, loff_t file_offset, unsigned long nr_segs) [static]
Definition at line 487 of file rw26.c.
References CDEBUG, cl_io_slice::cis_io, cl_env_get(), cl_env_put(), D_VFSTRACE, DFID, ENTRY, GOTO, LASSERT, likely, ll_direct_IO_seg(), ll_free_user_pages(), ll_get_user_pages(), ll_inode2fid(), MAX_DIO_SIZE, PFID, READ, RETURN, size, vvp_io::u, unlikely, vvp_io::vui_cl, vvp_env_io(), and vvp_io::write.
static ssize_t ll_direct_IO_seg (const struct lu_env * env, struct cl_io * io, int rw, struct inode * inode, size_t size, loff_t file_offset, struct page ** pages, int page_count) [static]
Definition at line 296 of file rw26.c.
References ll_dio_pages::ldp_pages, and ll_direct_rw_pages().
Referenced by ll_direct_IO().
ssize_t ll_direct_rw_pages (const struct lu_env * env, struct cl_io * io, int rw, struct inode * inode, struct ll_dio_pages * pv)
Definition at line 189 of file rw26.c.
References cl_io::ci_obj, cl_io::ci_queue, cl_2queue_add(), cl_2queue_discard(), cl_2queue_disown(), cl_2queue_fini(), cl_2queue_init(), cl_index(), cl_io_submit_sync(), cl_page_clip(), cl_page_disown(), cl_page_find(), cl_page_own(), cl_page_put(), cl_page_size(), cl_page_vmpage(), cl_page::cp_state, cl_page::cp_type, CPS_FREEING, CPT_CACHEABLE, CPT_TRANSIENT, CRT_READ, CRT_WRITE, ENTRY, LASSERT, ll_dio_pages::ldp_nr, ll_dio_pages::ldp_offsets, ll_dio_pages::ldp_pages, ll_dio_pages::ldp_size, ll_dio_pages::ldp_start_offset, likely, ll_kmap_atomic, ll_kunmap_atomic, page_size, READ, RETURN, size, and WRITE.
Referenced by do_bio_lustrebacked(), and ll_direct_IO_seg().
static void ll_free_user_pages (struct page ** pages, int npages, int do_dirty) [static]
Definition at line 312 of file rw26.c.
References OBD_FREE_LARGE.
Referenced by ll_direct_IO().
static int ll_get_user_pages (int rw, unsigned long user_addr, size_t size, struct page *** pages, int * max_pages) [inline, static]
Definition at line 456 of file rw26.c.
References MAX_DIRECTIO_SIZE, OBD_ALLOC_LARGE, OBD_FREE_LARGE, READ, and unlikely.
Referenced by ll_direct_IO().
static void ll_invalidatepage (struct page * vmpage, unsigned long offset) [static]
Implements Linux VM address_space::invalidatepage() method.
This method is called when the page is truncate from a file, either as a result of explicit truncate, or when inode is removed from memory (as a result of final iput(), umount, or memory pressure induced icache shrinking).
[0, offset] bytes of the page remain valid (this is for a case of not-page aligned truncate). Lustre leaves partially truncated page in the cache, relying on struct inode::i_size to limit further accesses.
Definition at line 78 of file rw26.c.
References cl_env_get(), cl_env_put(), cl_page_delete(), cl_page_put(), cl_vmpage_page(), LASSERT, ll_i2info(), and ll_inode_info::lli_clob.
static int ll_prepare_partial_page (const struct lu_env * env, struct cl_io * io, struct cl_page * pg) [static]
Prepare partially written-to page for a write.
Definition at line 596 of file rw26.c.
References cl_attr::cat_kms, cl_io::ci_obj, cl_object_attr_get(), cl_object_attr_lock(), cl_object_attr_unlock(), cl_object_page_slice(), cl_offset(), cl_page_size(), CRT_READ, ll_kmap_atomic, ll_kunmap_atomic, ll_page_sync_io(), vvp_page::vpg_defer_uptodate, vvp_page::vpg_page, vvp_page::vpg_ra_used, vvp_env_thread_attr(), and vvp_index().
Referenced by ll_write_begin().
static int ll_releasepage (struct page * vmpage, RELEASEPAGE_ARG_TYPE gfp_mask) [static]
Definition at line 128 of file rw26.c.
References cl_env_percpu_get(), cl_env_percpu_put(), cl_env_reenter(), cl_env_reexit(), cl_object_refc(), cl_page_delete(), cl_page_in_use, cl_page_put(), cl_vmpage_page(), LASSERT, ll_i2info(), ll_inode_info::lli_clob, and mapping.
static int ll_write_begin (struct file * file, struct address_space * mapping, loff_t pos, unsigned len, unsigned flags, struct page ** pagep, void ** fsdata) [static]
Definition at line 627 of file rw26.c.
References CDEBUG, cl_io::ci_result, cl_page_assume(), cl_page_find(), CL_PAGE_HEADER, cl_page_unassume(), cl_page::cp_reference, CPT_CACHEABLE, D_PAGE, D_VFSTRACE, ENTRY, EXIT, GOTO, ll_cl_context::lcc_env, ll_cl_context::lcc_io, ll_cl_context::lcc_page, ll_cl_find(), ll_i2info(), ll_prepare_partial_page(), ll_inode_info::lli_clob, lu_ref_add(), cl_page_list::pl_nr, POISON_PAGE, RETURN, vvp_io::u, unlikely, vvp_env_io(), vvp_io_write_commit(), and vvp_io::write.
static int ll_write_end (struct file * file, struct address_space * mapping, loff_t pos, unsigned len, unsigned copied, struct page * vmpage, void * fsdata) [static]
Definition at line 730 of file rw26.c.
References cl_io::ci_result, CL_PAGE_DEBUG, cl_page_disown(), cl_page_is_owned(), cl_page_list_add(), cl_page_put(), cl_page::cp_reference, D_VFSTRACE, ENTRY, LASSERT, ll_cl_context::lcc_env, ll_cl_context::lcc_io, ll_cl_context::lcc_page, lu_ref_del(), cl_page_list::pl_nr, PTLRPC_MAX_BRW_PAGES, RETURN, vvp_io::u, vvp_env_io(), vvp_io_write_commit(), and vvp_io::write.
Variable Documentation
struct address_space_operations ll_aops
Initial value:
 {
        .readpage       = ll_readpage,
        .direct_IO      = ll_direct_IO,
        .writepage      = ll_writepage,
        .writepages     = ll_writepages,
        .set_page_dirty = __set_page_dirty_nobuffers,
        .write_begin    = ll_write_begin,
        .write_end      = ll_write_end,
        .invalidatepage = ll_invalidatepage,
        .releasepage    = (void *)ll_releasepage,
}
Definition at line 809 of file rw26.c.
Referenced by ll_read_inode2().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.