Lustre: lustre/llite/rw.c File Reference
lustre/llite/rw.c File Reference
#include <linux/kernel.h>
#include <linux/mm.h>
#include <linux/string.h>
#include <linux/stat.h>
#include <linux/errno.h>
#include <linux/unistd.h>
#include <linux/writeback.h>
#include <asm/uaccess.h>
#include <linux/fs.h>
#include <linux/pagemap.h>
#include <linux/swap.h>
#include <obd_cksum.h>
#include "llite_internal.h"
#include <lustre_compat.h>
Defines
#define DEBUG_SUBSYSTEM S_LLITE
#define RAS_CDEBUG(ras)
#define RIA_DEBUG(ria)
Functions
static void ll_ra_stats_inc_sbi (struct ll_sb_info *sbi, enum ra_stat which)
static unsigned long ll_ra_count_get (struct ll_sb_info *sbi, struct ra_io_arg *ria, unsigned long pages, unsigned long min)
Get readahead pages from the filesystem readahead pool of the client for a thread.
void ll_ra_count_put (struct ll_sb_info *sbi, unsigned long len)
void ll_ra_stats_inc (struct inode *inode, enum ra_stat which)
static int index_in_window (unsigned long index, unsigned long point, unsigned long before, unsigned long after)
void ll_ras_enter (struct file *f)
static int ll_read_ahead_page (const struct lu_env *env, struct cl_io *io, struct cl_page_list *queue, pgoff_t index)
Initiates read-ahead of a page with given index.
static int stride_io_mode (struct ll_readahead_state *ras)
static unsigned long stride_pg_count (pgoff_t st_off, unsigned long st_len, unsigned long st_pgs, unsigned long off, unsigned long length)
static int ria_page_count (struct ra_io_arg *ria)
static unsigned long ras_align (struct ll_readahead_state *ras, unsigned long index, unsigned long *remainder)
static int ras_inside_ra_window (unsigned long idx, struct ra_io_arg *ria)
static unsigned long ll_read_ahead_pages (const struct lu_env *env, struct cl_io *io, struct cl_page_list *queue, struct ll_readahead_state *ras, struct ra_io_arg *ria)
static int ll_readahead (const struct lu_env *env, struct cl_io *io, struct cl_page_list *queue, struct ll_readahead_state *ras, bool hit)
static void ras_set_start (struct inode *inode, struct ll_readahead_state *ras, unsigned long index)
static void ras_reset (struct inode *inode, struct ll_readahead_state *ras, unsigned long index)
static void ras_stride_reset (struct ll_readahead_state *ras)
void ll_readahead_init (struct inode *inode, struct ll_readahead_state *ras)
static int index_in_stride_window (struct ll_readahead_state *ras, unsigned long index)
static void ras_update_stride_detector (struct ll_readahead_state *ras, unsigned long index)
static unsigned long stride_page_count (struct ll_readahead_state *ras, unsigned long len)
static void ras_stride_increase_window (struct ll_readahead_state *ras, struct ll_ra_info *ra, unsigned long inc_len)
static void ras_increase_window (struct inode *inode, struct ll_readahead_state *ras, struct ll_ra_info *ra)
static void ras_update (struct ll_sb_info *sbi, struct inode *inode, struct ll_readahead_state *ras, unsigned long index, enum ras_update_flags flags)
int ll_writepage (struct page *vmpage, struct writeback_control *wbc)
int ll_writepages (struct address_space *mapping, struct writeback_control *wbc)
struct ll_cl_context * ll_cl_find (struct file *file)
void ll_cl_add (struct file *file, const struct lu_env *env, struct cl_io *io)
void ll_cl_remove (struct file *file, const struct lu_env *env)
static int ll_io_read_page (const struct lu_env *env, struct cl_io *io, struct cl_page *page)
int ll_readpage (struct file *file, struct page *vmpage)
int ll_page_sync_io (const struct lu_env *env, struct cl_io *io, struct cl_page *page, enum cl_req_type crt)
Define Documentation
#define DEBUG_SUBSYSTEM S_LLITE
Definition at line 58 of file rw.c.
#define RAS_CDEBUG (ras)
Value:
CDEBUG(D_READA,                                                      \
               "lrp %lu cr %lu cp %lu ws %lu wl %lu nra %lu rpc %lu "        \
               "r %lu ri %lu csr %lu sf %lu sp %lu sl %lu\n",                \
               ras->ras_last_readpage, ras->ras_consecutive_requests,        \
               ras->ras_consecutive_pages, ras->ras_window_start,            \
               ras->ras_window_len, ras->ras_next_readahead,                 \
               ras->ras_rpc_size,                                            \
               ras->ras_requests, ras->ras_request_index,                    \
               ras->ras_consecutive_stride_requests, ras->ras_stride_offset, \
               ras->ras_stride_pages, ras->ras_stride_length)
Definition at line 133 of file rw.c.
Referenced by ll_readahead(), ras_reset(), ras_stride_increase_window(), ras_stride_reset(), ras_update(), and ras_update_stride_detector().
#define RIA_DEBUG (ria)
Value:
CDEBUG(D_READA, "rs %lu re %lu ro %lu rl %lu rp %lu\n",       \
        ria->ria_start, ria->ria_end, ria->ria_stoff, ria->ria_length,\
        ria->ria_pages)
Definition at line 245 of file rw.c.
Referenced by ll_read_ahead_pages().
Function Documentation
static int index_in_stride_window (struct ll_readahead_state * ras, unsigned long index) [static]
Definition at line 617 of file rw.c.
References ll_readahead_state::ras_consecutive_pages, ll_readahead_state::ras_last_readpage, ll_readahead_state::ras_stride_length, and ll_readahead_state::ras_stride_pages.
Referenced by ras_update().
static int index_in_window (unsigned long index, unsigned long point, unsigned long before, unsigned long after) [static]
Definition at line 145 of file rw.c.
References end, and start.
Referenced by ll_readahead(), and ras_update().
void ll_cl_add (struct file * file, const struct lu_env * env, struct cl_io * io)
Definition at line 1051 of file rw.c.
References ll_file_data::fd_lccs, ll_file_data::fd_lock, INIT_LIST_HEAD, ll_cl_context::lcc_cookie, ll_cl_context::lcc_env, ll_cl_context::lcc_io, ll_cl_context::lcc_list, list_add(), ll_env_info(), ll_thread_info::lti_io_ctx, and LUSTRE_FPRIVATE.
Referenced by ll_fault0(), and ll_file_io_generic().
struct ll_cl_context* ll_cl_find (struct file * file) [read]
Definition at line 1033 of file rw.c.
References ll_file_data::fd_lccs, ll_file_data::fd_lock, ll_cl_context::lcc_cookie, ll_cl_context::lcc_list, list_for_each_entry, and LUSTRE_FPRIVATE.
Referenced by ll_readpage(), and ll_write_begin().
void ll_cl_remove (struct file * file, const struct lu_env * env)
Definition at line 1067 of file rw.c.
References ll_file_data::fd_lock, ll_cl_context::lcc_list, list_del_init(), ll_env_info(), ll_thread_info::lti_io_ctx, and LUSTRE_FPRIVATE.
Referenced by ll_fault0(), and ll_file_io_generic().
static int ll_io_read_page (const struct lu_env * env, struct cl_io * io, struct cl_page * page) [static]
Definition at line 1077 of file rw.c.
References cl_2queue::c2_qin, CDEBUG, cl_io::ci_queue, cl2vvp_page(), cl_2queue_add(), cl_2queue_fini(), cl_2queue_init(), cl_io_submit_rw(), cl_object_page_slice(), cl_page_disown(), cl_page_export(), cl_page_list_disown(), cl_page::cp_obj, CRT_READ, D_READA, DFID, ENTRY, ll_file_data::fd_ras, ll_i2sbi(), ll_inode2fid(), ll_sb_info::ll_ra_info, LL_RAS_HIT, LL_RAS_MMAP, ll_readahead(), PFID, cl_page_list::pl_nr, ll_ra_info::ra_max_pages, ll_ra_info::ra_max_pages_per_file, ras_update(), RETURN, vvp_page::vpg_defer_uptodate, vvp_page::vpg_ra_used, vvp_io::vui_fd, vvp_io::vui_ra_valid, vvp_env_io(), vvp_index(), and vvp_object_inode().
Referenced by ll_readpage().
int ll_page_sync_io (const struct lu_env * env, struct cl_io * io, struct cl_page * page, enum cl_req_type crt)
Definition at line 1176 of file rw.c.
References cl_2queue::c2_qin, cl_io::ci_queue, cl_io::ci_type, CIT_READ, CIT_WRITE, cl_2queue_fini(), cl_2queue_init_page(), cl_io_submit_sync(), cl_page_is_owned(), cl_page_list_disown(), CRT_READ, and LASSERT.
Referenced by ll_prepare_partial_page().
static unsigned long ll_ra_count_get (struct ll_sb_info * sbi, struct ra_io_arg * ria, unsigned long pages, unsigned long min) [static]
Get readahead pages from the filesystem readahead pool of the client for a thread.
/param sbi superblock for filesystem readahead state ll_ra_info /param ria per-thread readahead state /param pages number of pages requested for readahead for the thread.
WARNING: This algorithm is used to reduce contention on sbi->ll_lock. It should work well if the ra_max_pages is much greater than the single file's read-ahead window, and not too many threads contending for these readahead pages.
TODO: There may be a 'global sync problem' if many threads are trying to get an ra budget that is larger than the remaining readahead pages and reach here at exactly the same time. They will compute /a ret to consume the remaining pages, but will fail at atomic_add_return() and get a zero ra window, although there is still ra space remaining. - Jay
Definition at line 85 of file rw.c.
References ENTRY, GOTO, ll_sb_info::ll_ra_info, min_t, PTLRPC_MAX_BRW_PAGES, ll_ra_info::ra_cur_pages, ll_ra_info::ra_max_pages, ret, and RETURN.
Referenced by ll_readahead().
void ll_ra_count_put (struct ll_sb_info * sbi, unsigned long len)
Definition at line 115 of file rw.c.
References ll_sb_info::ll_ra_info, and ll_ra_info::ra_cur_pages.
Referenced by ll_readahead(), and vvp_page_completion_read().
void ll_ra_stats_inc (struct inode * inode, enum ra_stat which)
Definition at line 127 of file rw.c.
References ll_i2sbi(), and ll_ra_stats_inc_sbi().
Referenced by ll_read_ahead_page(), ll_readahead(), and vvp_page_discard().
static void ll_ra_stats_inc_sbi (struct ll_sb_info * sbi, enum ra_stat which) [static]
Definition at line 121 of file rw.c.
References _NR_RA_STAT, LASSERTF, ll_sb_info::ll_ra_stats, and lprocfs_counter_incr().
Referenced by ll_ra_stats_inc(), and ras_update().
void ll_ras_enter (struct file * f)
Definition at line 158 of file rw.c.
References ll_file_data::fd_ras, LUSTRE_FPRIVATE, ll_readahead_state::ras_consecutive_requests, ll_readahead_state::ras_lock, ll_readahead_state::ras_request_index, and ll_readahead_state::ras_requests.
Referenced by vvp_io_read_start().
static int ll_read_ahead_page (const struct lu_env * env, struct cl_io * io, struct cl_page_list * queue, pgoff_t index) [static]
Initiates read-ahead of a page with given index.
Return values:
+ve,: page was already uptodate so it will be skipped from being added;
-ve,: page wasn't added to queue for error;
0,: page was added into queue for read ahead.
Definition at line 178 of file rw.c.
References _NR_RA_STAT, CDEBUG, cl_io::ci_obj, cl2vvp_page(), cl_object_page_slice(), cl_page_assume(), cl_page_find(), cl_page_list_add(), cl_page_put(), cl_page_unassume(), cl_page::cp_reference, CPT_CACHEABLE, D_READA, ENTRY, GOTO, ll_ra_stats_inc(), lu_ref_add(), lu_ref_del(), msg, RA_STAT_FAILED_GRAB_PAGE, RA_STAT_WRONG_GRAB_PAGE, RETURN, vvp_page::vpg_defer_uptodate, vvp_page::vpg_ra_used, and vvp_object_inode().
Referenced by ll_read_ahead_pages().
static unsigned long ll_read_ahead_pages (const struct lu_env * env, struct cl_io * io, struct cl_page_list * queue, struct ll_readahead_state * ras, struct ra_io_arg * ria) [static]
Definition at line 343 of file rw.c.
References CDEBUG, cl_io::ci_obj, cl_io_read_ahead(), cl_read_ahead_release(), cl_read_ahead::cra_end, cl_read_ahead::cra_rpc_size, D_READA, end, LASSERT, LASSERTF, ll_read_ahead_page(), ras_align(), ras_inside_ra_window(), ll_readahead_state::ras_rpc_size, RIA_DEBUG, ra_io_arg::ria_end, ra_io_arg::ria_end_min, ra_io_arg::ria_eof, ra_io_arg::ria_length, ra_io_arg::ria_pages, ra_io_arg::ria_reserved, ra_io_arg::ria_start, and ra_io_arg::ria_stoff.
Referenced by ll_readahead().
static int ll_readahead (const struct lu_env * env, struct cl_io * io, struct cl_page_list * queue, struct ll_readahead_state * ras, bool hit) [static]
Note: other thread might rollback the ras_next_readahead, if it can not get the full size of prepared pages, see the end of this function. For stride read ahead, it needs to make sure the offset is no less than ras_stride_offset, so that stride read ahead can work correctly.
Definition at line 428 of file rw.c.
References __u64, cl_attr::cat_kms, CDEBUG, cl_io::ci_obj, cl_object_attr_get(), cl_object_attr_lock(), cl_object_attr_unlock(), cl_object::co_lu, D_READA, DFID, end, ENTRY, index_in_window(), ll_env_info(), ll_i2sbi(), ll_ra_count_get(), ll_ra_count_put(), ll_ra_stats_inc(), ll_read_ahead_pages(), ll_thread_info::lti_ria, lu_object_fid(), max, PFID, RA_STAT_EOF, RA_STAT_FAILED_REACH_END, RA_STAT_MAX_IN_FLIGHT, RA_STAT_ZERO_LEN, RA_STAT_ZERO_WINDOW, ras_align(), RAS_CDEBUG, ll_readahead_state::ras_lock, ll_readahead_state::ras_next_readahead, ll_readahead_state::ras_rpc_size, ll_readahead_state::ras_stride_length, ll_readahead_state::ras_stride_offset, ll_readahead_state::ras_stride_pages, ll_readahead_state::ras_window_len, ll_readahead_state::ras_window_start, ret, RETURN, ra_io_arg::ria_end, ra_io_arg::ria_end_min, ra_io_arg::ria_eof, ra_io_arg::ria_length, ria_page_count(), ra_io_arg::ria_pages, ra_io_arg::ria_reserved, ra_io_arg::ria_start, ra_io_arg::ria_stoff, start, stride_io_mode(), vvp_io::vui_ra_count, vvp_io::vui_ra_start, vvp_io::vui_ra_valid, vvp_env_io(), vvp_env_thread_attr(), and vvp_object_inode().
Referenced by ll_io_read_page().
void ll_readahead_init (struct inode * inode, struct ll_readahead_state * ras)
Definition at line 605 of file rw.c.
References PTLRPC_MAX_BRW_PAGES, ll_readahead_state::ras_lock, ll_readahead_state::ras_requests, ras_reset(), and ll_readahead_state::ras_rpc_size.
Referenced by ll_local_open().
int ll_readpage (struct file * file, struct page * vmpage)
Definition at line 1136 of file rw.c.
References cl_io::ci_state, CIS_IO_GOING, cl_page_assume(), cl_page_find(), cl_page_put(), cl_page::cp_type, CPT_CACHEABLE, ENTRY, LASSERT, ll_cl_context::lcc_env, ll_cl_context::lcc_io, likely, ll_cl_find(), ll_i2info(), ll_io_read_page(), ll_inode_info::lli_clob, and RETURN.
int ll_writepage (struct page * vmpage, struct writeback_control * wbc)
Definition at line 887 of file rw.c.
References cl_io::ci_ignore_layout, cl_io::ci_obj, CIT_MISC, cl_env_nested_get(), cl_env_nested_put(), CL_FSYNC_LOCAL, cl_io_fini(), cl_io_init(), cl_offset(), cl_page_assume(), cl_page_disown(), cl_page_find(), cl_page_flush(), cl_page_put(), cl_sync_file_range(), cl_page::cp_reference, CPT_CACHEABLE, ENTRY, GOTO, LASSERT, ll_i2dtexp(), ll_i2info(), ll_inode_info::lli_async_rc, ll_inode_info::lli_clob, lu_ref_add(), lu_ref_del(), and vvp_env_thread_io().
int ll_writepages (struct address_space * mapping, struct writeback_control * wbc)
Definition at line 981 of file rw.c.
References CL_FSYNC_LOCAL, CL_FSYNC_NONE, cl_sync_file_range(), end, ENTRY, ll_i2info(), ll_i2sbi(), ll_sb_info::ll_umounting, mode, OBD_OBJECT_EOF, RETURN, and start.
static unsigned long ras_align (struct ll_readahead_state * ras, unsigned long index, unsigned long * remainder) [static]
Definition at line 320 of file rw.c.
References ll_readahead_state::ras_rpc_size.
Referenced by ll_read_ahead_pages(), ll_readahead(), ras_increase_window(), and ras_set_start().
static void ras_increase_window (struct inode * inode, struct ll_readahead_state * ras, struct ll_ra_info * ra) [static]
Definition at line 710 of file rw.c.
References ll_ra_info::ra_max_pages_per_file, ras_align(), ll_readahead_state::ras_rpc_size, ras_stride_increase_window(), ll_readahead_state::ras_window_len, and stride_io_mode().
Referenced by ras_update().
static int ras_inside_ra_window (unsigned long idx, struct ra_io_arg * ria) [static]
Definition at line 331 of file rw.c.
References ra_io_arg::ria_length, ra_io_arg::ria_pages, and ra_io_arg::ria_stoff.
Referenced by ll_read_ahead_pages().
static void ras_reset (struct inode * inode, struct ll_readahead_state * ras, unsigned long index) [static]
Definition at line 583 of file rw.c.
References max, RAS_CDEBUG, ll_readahead_state::ras_consecutive_pages, ll_readahead_state::ras_consecutive_requests, ll_readahead_state::ras_last_readpage, ll_readahead_state::ras_next_readahead, ras_set_start(), ll_readahead_state::ras_window_len, and ll_readahead_state::ras_window_start.
Referenced by ll_readahead_init(), and ras_update().
static void ras_set_start (struct inode * inode, struct ll_readahead_state * ras, unsigned long index) [static]
Definition at line 576 of file rw.c.
References ras_align(), and ll_readahead_state::ras_window_start.
Referenced by ras_reset(), and ras_update().
static void ras_stride_increase_window (struct ll_readahead_state * ras, struct ll_ra_info * ra, unsigned long inc_len) [static]
Definition at line 673 of file rw.c.
References LASSERT, LASSERTF, ll_ra_info::ra_max_pages_per_file, RAS_CDEBUG, ll_readahead_state::ras_stride_length, ll_readahead_state::ras_stride_offset, ll_readahead_state::ras_stride_pages, ll_readahead_state::ras_window_len, ll_readahead_state::ras_window_start, and stride_page_count().
Referenced by ras_increase_window().
static void ras_stride_reset (struct ll_readahead_state * ras) [static]
Definition at line 597 of file rw.c.
References RAS_CDEBUG, ll_readahead_state::ras_consecutive_stride_requests, ll_readahead_state::ras_stride_length, and ll_readahead_state::ras_stride_pages.
Referenced by ras_update(), and ras_update_stride_detector().
static void ras_update (struct ll_sb_info * sbi, struct inode * inode, struct ll_readahead_state * ras, unsigned long index, enum ras_update_flags flags) [static]
Once stride IO mode is detected, next_readahead should be reset to make sure next_readahead > stride offset
Definition at line 729 of file rw.c.
References __u64, CDEBUG, D_READA, ENTRY, EXIT, GOTO, index_in_stride_window(), index_in_window(), ll_sb_info::ll_ra_info, ll_ra_stats_inc_sbi(), LL_RAS_HIT, LL_RAS_MMAP, LPU64, max, ll_ra_info::ra_max_pages_per_file, ll_ra_info::ra_max_read_ahead_whole_pages, RA_STAT_DISTANT_READPAGE, RA_STAT_HIT, RA_STAT_MISS, RA_STAT_MISS_IN_WINDOW, RAS_CDEBUG, ll_readahead_state::ras_consecutive_pages, ll_readahead_state::ras_consecutive_requests, ll_readahead_state::ras_consecutive_stride_requests, ras_increase_window(), ll_readahead_state::ras_last_readpage, ll_readahead_state::ras_lock, ll_readahead_state::ras_next_readahead, ll_readahead_state::ras_request_index, ll_readahead_state::ras_requests, ras_reset(), ras_set_start(), ll_readahead_state::ras_stride_offset, ras_stride_reset(), ras_update_stride_detector(), ll_readahead_state::ras_window_len, ll_readahead_state::ras_window_start, and stride_io_mode().
Referenced by ll_io_read_page().
static void ras_update_stride_detector (struct ll_readahead_state * ras, unsigned long index) [static]
Definition at line 637 of file rw.c.
References LASSERT, RAS_CDEBUG, ll_readahead_state::ras_consecutive_pages, ll_readahead_state::ras_consecutive_stride_requests, ll_readahead_state::ras_last_readpage, ll_readahead_state::ras_request_index, ll_readahead_state::ras_stride_length, ll_readahead_state::ras_stride_pages, ras_stride_reset(), and stride_io_mode().
Referenced by ras_update().
static int ria_page_count (struct ra_io_arg * ria) [static]
Definition at line 310 of file rw.c.
References __u64, ra_io_arg::ria_end, ra_io_arg::ria_length, ra_io_arg::ria_pages, ra_io_arg::ria_start, ra_io_arg::ria_stoff, and stride_pg_count().
Referenced by ll_readahead().
static int stride_io_mode (struct ll_readahead_state * ras) [inline, static]
Definition at line 250 of file rw.c.
References ll_readahead_state::ras_consecutive_stride_requests.
Referenced by ll_readahead(), ras_increase_window(), ras_update(), and ras_update_stride_detector().
static unsigned long stride_page_count (struct ll_readahead_state * ras, unsigned long len) [static]
Definition at line 664 of file rw.c.
References ll_readahead_state::ras_stride_length, ll_readahead_state::ras_stride_offset, ll_readahead_state::ras_stride_pages, and stride_pg_count().
Referenced by ras_stride_increase_window().
static unsigned long stride_pg_count (pgoff_t st_off, unsigned long st_len, unsigned long st_pgs, unsigned long off, unsigned long length) [static]
Definition at line 274 of file rw.c.
References __u64, CDEBUG, D_READA, end, LPU64, and start.
Referenced by ria_page_count(), and stride_page_count().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.