Lustre: lustre/ptlrpc/sec_null.c File Reference
lustre/ptlrpc/sec_null.c File Reference
#include <obd_support.h>
#include <obd_cksum.h>
#include <obd_class.h>
#include <lustre_net.h>
#include <lustre_sec.h>
#include "ptlrpc_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_SEC
Functions
static void null_encode_sec_part (struct lustre_msg *msg, enum lustre_sec_part sp)
static enum lustre_sec_part null_decode_sec_part (struct lustre_msg *msg)
static int null_ctx_refresh (struct ptlrpc_cli_ctx *ctx)
static int null_ctx_sign (struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req)
static int null_ctx_verify (struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req)
static struct ptlrpc_sec * null_create_sec (struct obd_import *imp, struct ptlrpc_svc_ctx *svc_ctx, struct sptlrpc_flavor *sf)
static void null_destroy_sec (struct ptlrpc_sec *sec)
static struct ptlrpc_cli_ctx * null_lookup_ctx (struct ptlrpc_sec *sec, struct vfs_cred *vcred, int create, int remove_dead)
static int null_flush_ctx_cache (struct ptlrpc_sec *sec, uid_t uid, int grace, int force)
static int null_alloc_reqbuf (struct ptlrpc_sec *sec, struct ptlrpc_request *req, int msgsize)
static void null_free_reqbuf (struct ptlrpc_sec *sec, struct ptlrpc_request *req)
static int null_alloc_repbuf (struct ptlrpc_sec *sec, struct ptlrpc_request *req, int msgsize)
static void null_free_repbuf (struct ptlrpc_sec *sec, struct ptlrpc_request *req)
static int null_enlarge_reqbuf (struct ptlrpc_sec *sec, struct ptlrpc_request *req, int segment, int newsize)
static int null_accept (struct ptlrpc_request *req)
static int null_alloc_rs (struct ptlrpc_request *req, int msgsize)
static void null_free_rs (struct ptlrpc_reply_state *rs)
static int null_authorize (struct ptlrpc_request *req)
static void null_init_internal (void)
int sptlrpc_null_init (void)
void sptlrpc_null_fini (void)
Variables
static struct ptlrpc_sec_policy null_policy
static struct ptlrpc_sec null_sec
static struct ptlrpc_cli_ctx null_cli_ctx
static struct ptlrpc_svc_ctx null_svc_ctx
static struct ptlrpc_ctx_ops null_ctx_ops
static struct ptlrpc_sec_cops null_sec_cops
static struct ptlrpc_sec_sops null_sec_sops
Define Documentation
#define DEBUG_SUBSYSTEM S_SEC
Definition at line 41 of file sec_null.c.
Function Documentation
static int null_accept (struct ptlrpc_request * req) [static]
Definition at line 287 of file sec_null.c.
References CERROR, LASSERT, null_decode_sec_part(), ptlrpc_request::rq_flvr, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqdata_len, ptlrpc_request::rq_reqlen, ptlrpc_request::rq_reqmsg, SECSVC_DROP, SECSVC_OK, sptlrpc_flavor::sf_rpc, SPTLRPC_FLVR_NULL, SPTLRPC_FLVR_POLICY, and SPTLRPC_POLICY_NULL.
static int null_alloc_repbuf (struct ptlrpc_sec * sec, struct ptlrpc_request * req, int msgsize) [static]
Definition at line 199 of file sec_null.c.
References lustre_msg_early_size(), OBD_ALLOC_LARGE, ptlrpc_request::rq_repbuf, ptlrpc_request::rq_repbuf_len, and size_roundup_power2().
static int null_alloc_reqbuf (struct ptlrpc_sec * sec, struct ptlrpc_request * req, int msgsize) [static]
Definition at line 157 of file sec_null.c.
References LASSERT, OBD_ALLOC_LARGE, ptlrpc_request::rq_pool, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqbuf_len, ptlrpc_request::rq_reqmsg, and size_roundup_power2().
static int null_alloc_rs (struct ptlrpc_request * req, int msgsize) [static]
Definition at line 309 of file sec_null.c.
References LASSERT, lustre_msg, OBD_ALLOC_LARGE, ptlrpc_reply_state::rs_repbuf, ptlrpc_reply_state::rs_repbuf_len, ptlrpc_reply_state::rs_size, and ptlrpc_reply_state::rs_svc_ctx.
static int null_authorize (struct ptlrpc_request * req) [static]
Definition at line 351 of file sec_null.c.
References cksum, LASSERT, likely, lustre_msg_calc_cksum(), lustre_msg_early_size(), lustre_msg_set_cksum(), lustre_msghdr_get_flags(), MSGHDR_AT_SUPPORT, ptlrpc_request::rq_packed_final, ptlrpc_request::rq_replen, ptlrpc_request::rq_reply_off, ptlrpc_request::rq_reqmsg, ptlrpc_reply_state::rs_repbuf, ptlrpc_reply_state::rs_repdata_len, and SPTLRPC_FLVR_NULL.
static struct ptlrpc_sec* null_create_sec (struct obd_import * imp, struct ptlrpc_svc_ctx * svc_ctx, struct sptlrpc_flavor * sf) [static, read]
Definition at line 120 of file sec_null.c.
References LASSERT, null_policy, null_sec, sptlrpc_flavor::sf_rpc, SPTLRPC_FLVR_POLICY, SPTLRPC_POLICY_NULL, and sptlrpc_policy_put().
static int null_ctx_refresh (struct ptlrpc_cli_ctx * ctx) [static]
Definition at line 73 of file sec_null.c.
References LBUG.
static int null_ctx_sign (struct ptlrpc_cli_ctx * ctx, struct ptlrpc_request * req) [static]
Definition at line 81 of file sec_null.c.
References client_obd::cl_sp_me, obd_device::cli, obd_import::imp_dlm_fake, obd_import::imp_obd, null_encode_sec_part(), ptlrpc_request::rq_import, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqdata_len, ptlrpc_request::rq_reqlen, SPTLRPC_FLVR_NULL, and obd_device::u.
static int null_ctx_verify (struct ptlrpc_cli_ctx * ctx, struct ptlrpc_request * req) [static]
Definition at line 95 of file sec_null.c.
References CDEBUG, D_SEC, LASSERT, lustre_msg_calc_cksum(), lustre_msg_get_cksum(), ptlrpc_request::rq_early, ptlrpc_request::rq_repdata, ptlrpc_request::rq_repdata_len, ptlrpc_request::rq_replen, and ptlrpc_request::rq_repmsg.
static enum lustre_sec_part null_decode_sec_part (struct lustre_msg * msg) [inline, static]
Definition at line 68 of file sec_null.c.
Referenced by null_accept().
static void null_destroy_sec (struct ptlrpc_sec * sec) [static]
Definition at line 134 of file sec_null.c.
References LASSERT, and null_sec.
static void null_encode_sec_part (struct lustre_msg * msg, enum lustre_sec_part sp) [inline, static]
Definition at line 62 of file sec_null.c.
Referenced by null_ctx_sign().
static int null_enlarge_reqbuf (struct ptlrpc_sec * sec, struct ptlrpc_request * req, int segment, int newsize) [static]
Definition at line 228 of file sec_null.c.
References _sptlrpc_enlarge_msg_inplace(), obd_import::imp_lock, LASSERT, lustre_msg, lustre_packed_msg_size(), OBD_ALLOC_LARGE, OBD_FREE_LARGE, ptlrpc_request::rq_import, ptlrpc_request::rq_pool, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqbuf_len, ptlrpc_request::rq_reqlen, ptlrpc_request::rq_reqmsg, and size_roundup_power2().
static int null_flush_ctx_cache (struct ptlrpc_sec * sec, uid_t uid, int grace, int force) [static]
Definition at line 149 of file sec_null.c.
static void null_free_repbuf (struct ptlrpc_sec * sec, struct ptlrpc_request * req) [static]
Definition at line 217 of file sec_null.c.
References LASSERT, OBD_FREE_LARGE, ptlrpc_request::rq_repbuf, and ptlrpc_request::rq_repbuf_len.
static void null_free_reqbuf (struct ptlrpc_sec * sec, struct ptlrpc_request * req) [static]
Definition at line 181 of file sec_null.c.
References LASSERTF, OBD_FREE_LARGE, ptlrpc_request::rq_pool, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqbuf_len, ptlrpc_request::rq_reqlen, and ptlrpc_request::rq_reqmsg.
static void null_free_rs (struct ptlrpc_reply_state * rs) [static]
Definition at line 341 of file sec_null.c.
References LASSERT_ATOMIC_GT, OBD_FREE_LARGE, ptlrpc_reply_state::rs_prealloc, ptlrpc_reply_state::rs_size, ptlrpc_reply_state::rs_svc_ctx, and ptlrpc_svc_ctx::sc_refcount.
static void null_init_internal (void) [static]
Definition at line 409 of file sec_null.c.
References ptlrpc_cli_ctx::cc_cache, ptlrpc_cli_ctx::cc_expire, ptlrpc_cli_ctx::cc_flags, ptlrpc_cli_ctx::cc_gc_chain, ptlrpc_cli_ctx::cc_lock, ptlrpc_cli_ctx::cc_ops, ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_req_list, ptlrpc_cli_ctx::cc_sec, ptlrpc_cli_ctx::cc_vcred, hlist_add_head(), HLIST_HEAD, INIT_LIST_HEAD, LUSTRE_SP_ANY, null_cli_ctx, null_sec, ptlrpc_sec::ps_dying, ptlrpc_sec::ps_flvr, ptlrpc_sec::ps_gc_interval, ptlrpc_sec::ps_gc_list, ptlrpc_sec::ps_gc_next, ptlrpc_sec::ps_id, ptlrpc_sec::ps_import, ptlrpc_sec::ps_lock, ptlrpc_sec::ps_nctx, ptlrpc_sec::ps_part, ptlrpc_sec::ps_policy, ptlrpc_sec::ps_refcount, PTLRPC_CTX_CACHED, PTLRPC_CTX_ETERNAL, PTLRPC_CTX_UPTODATE, sptlrpc_flavor::sf_flags, sptlrpc_flavor::sf_rpc, SPTLRPC_FLVR_NULL, and vfs_cred::vc_uid.
Referenced by sptlrpc_null_init().
static struct ptlrpc_cli_ctx* null_lookup_ctx (struct ptlrpc_sec * sec, struct vfs_cred * vcred, int create, int remove_dead) [static, read]
Definition at line 140 of file sec_null.c.
References ptlrpc_cli_ctx::cc_refcount, and null_cli_ctx.
void sptlrpc_null_fini (void)
Definition at line 453 of file sec_null.c.
References CERROR, ptlrpc_sec_policy::sp_name, and sptlrpc_unregister_policy().
Referenced by sptlrpc_fini(), and sptlrpc_init().
int sptlrpc_null_init (void)
Definition at line 440 of file sec_null.c.
References CERROR, null_init_internal(), ptlrpc_sec_policy::sp_name, and sptlrpc_register_policy().
Referenced by sptlrpc_init().
Variable Documentation
struct ptlrpc_cli_ctx null_cli_ctx [static]
Definition at line 54 of file sec_null.c.
Referenced by null_init_internal(), and null_lookup_ctx().
struct ptlrpc_ctx_ops null_ctx_ops [static]
Initial value:
 {
        .refresh                = null_ctx_refresh,
        .sign                   = null_ctx_sign,
        .verify                 = null_ctx_verify,
}
Definition at line 376 of file sec_null.c.
static struct ptlrpc_sec_policy null_policy [static, read]
Initial value:
 {
        .sp_owner               = THIS_MODULE,
        .sp_name                = "sec.null",
        .sp_policy              = SPTLRPC_POLICY_NULL,
        .sp_cops                = &null_sec_cops,
        .sp_sops                = &null_sec_sops,
}
Definition at line 52 of file sec_null.c.
Referenced by null_create_sec().
struct ptlrpc_sec null_sec [static]
Definition at line 53 of file sec_null.c.
Referenced by null_create_sec(), null_destroy_sec(), and null_init_internal().
struct ptlrpc_sec_cops null_sec_cops [static]
Initial value:
 {
        .create_sec             = null_create_sec,
        .destroy_sec            = null_destroy_sec,
        .lookup_ctx             = null_lookup_ctx,
        .flush_ctx_cache        = null_flush_ctx_cache,
        .alloc_reqbuf           = null_alloc_reqbuf,
        .alloc_repbuf           = null_alloc_repbuf,
        .free_reqbuf            = null_free_reqbuf,
        .free_repbuf            = null_free_repbuf,
        .enlarge_reqbuf         = null_enlarge_reqbuf,
}
Definition at line 382 of file sec_null.c.
struct ptlrpc_sec_sops null_sec_sops [static]
Initial value:
 {
        .accept                 = null_accept,
        .alloc_rs               = null_alloc_rs,
        .authorize              = null_authorize,
        .free_rs                = null_free_rs,
}
Definition at line 394 of file sec_null.c.
static struct ptlrpc_svc_ctx null_svc_ctx [static, read]
Initial value:
 {
        .sc_refcount    = ATOMIC_INIT(1),
        .sc_policy      = &null_policy,
}
Definition at line 55 of file sec_null.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.