Lustre: lustre/ptlrpc/sec_plain.c File Reference
lustre/ptlrpc/sec_plain.c File Reference
#include <obd_support.h>
#include <obd_cksum.h>
#include <obd_class.h>
#include <lustre_net.h>
#include <lustre_sec.h>
#include "ptlrpc_internal.h"
Data Structures
struct plain_sec
struct plain_header
struct plain_bulk_token
Defines
#define DEBUG_SUBSYSTEM S_SEC
#define PLAIN_PACK_SEGMENTS (4)
#define PLAIN_PACK_HDR_OFF (0)
#define PLAIN_PACK_MSG_OFF (1)
#define PLAIN_PACK_USER_OFF (2)
#define PLAIN_PACK_BULK_OFF (3)
#define PLAIN_FL_USER (0x01)
#define PLAIN_FL_BULK (0x02)
#define PLAIN_BSD_SIZE (sizeof(struct ptlrpc_bulk_sec_desc) + sizeof(struct plain_bulk_token))
Functions
static struct plain_sec * sec2plsec (struct ptlrpc_sec *sec)
static int plain_unpack_bsd (struct lustre_msg *msg, int swabbed)
static int plain_generate_bulk_csum (struct ptlrpc_bulk_desc *desc, __u8 hash_alg, struct plain_bulk_token *token)
static int plain_verify_bulk_csum (struct ptlrpc_bulk_desc *desc, __u8 hash_alg, struct plain_bulk_token *tokenr)
static void corrupt_bulk_data (struct ptlrpc_bulk_desc *desc)
static int plain_ctx_refresh (struct ptlrpc_cli_ctx *ctx)
static int plain_ctx_validate (struct ptlrpc_cli_ctx *ctx)
static int plain_ctx_sign (struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req)
static int plain_ctx_verify (struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req)
static int plain_cli_wrap_bulk (struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
static int plain_cli_unwrap_bulk (struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
static struct ptlrpc_cli_ctx * plain_sec_install_ctx (struct plain_sec *plsec)
static void plain_destroy_sec (struct ptlrpc_sec *sec)
static void plain_kill_sec (struct ptlrpc_sec *sec)
static struct ptlrpc_sec * plain_create_sec (struct obd_import *imp, struct ptlrpc_svc_ctx *svc_ctx, struct sptlrpc_flavor *sf)
static struct ptlrpc_cli_ctx * plain_lookup_ctx (struct ptlrpc_sec *sec, struct vfs_cred *vcred, int create, int remove_dead)
static void plain_release_ctx (struct ptlrpc_sec *sec, struct ptlrpc_cli_ctx *ctx, int sync)
static int plain_flush_ctx_cache (struct ptlrpc_sec *sec, uid_t uid, int grace, int force)
static int plain_alloc_reqbuf (struct ptlrpc_sec *sec, struct ptlrpc_request *req, int msgsize)
static void plain_free_reqbuf (struct ptlrpc_sec *sec, struct ptlrpc_request *req)
static int plain_alloc_repbuf (struct ptlrpc_sec *sec, struct ptlrpc_request *req, int msgsize)
static void plain_free_repbuf (struct ptlrpc_sec *sec, struct ptlrpc_request *req)
static int plain_enlarge_reqbuf (struct ptlrpc_sec *sec, struct ptlrpc_request *req, int segment, int newsize)
static int plain_accept (struct ptlrpc_request *req)
static int plain_alloc_rs (struct ptlrpc_request *req, int msgsize)
static void plain_free_rs (struct ptlrpc_reply_state *rs)
static int plain_authorize (struct ptlrpc_request *req)
static int plain_svc_unwrap_bulk (struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
static int plain_svc_wrap_bulk (struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
int sptlrpc_plain_init (void)
void sptlrpc_plain_fini (void)
Variables
static struct ptlrpc_sec_policy plain_policy
static struct ptlrpc_ctx_ops plain_ctx_ops
static struct ptlrpc_svc_ctx plain_svc_ctx
static unsigned int plain_at_offset
static struct ptlrpc_sec_cops plain_sec_cops
static struct ptlrpc_sec_sops plain_sec_sops
Define Documentation
#define DEBUG_SUBSYSTEM S_SEC
Definition at line 41 of file sec_plain.c.
#define PLAIN_BSD_SIZE (sizeof(struct ptlrpc_bulk_sec_desc) + sizeof(struct plain_bulk_token))
Definition at line 94 of file sec_plain.c.
Referenced by plain_alloc_repbuf(), plain_alloc_reqbuf(), plain_alloc_rs(), and plain_unpack_bsd().
#define PLAIN_FL_BULK (0x02)
Definition at line 80 of file sec_plain.c.
Referenced by plain_accept(), plain_authorize(), plain_ctx_sign(), and plain_ctx_verify().
#define PLAIN_FL_USER (0x01)
Definition at line 79 of file sec_plain.c.
Referenced by plain_accept(), plain_ctx_sign(), and plain_ctx_verify().
#define PLAIN_PACK_BULK_OFF (3)
Definition at line 77 of file sec_plain.c.
Referenced by plain_alloc_repbuf(), plain_alloc_reqbuf(), plain_alloc_rs(), plain_cli_unwrap_bulk(), plain_cli_wrap_bulk(), plain_svc_unwrap_bulk(), plain_svc_wrap_bulk(), and plain_unpack_bsd().
#define PLAIN_PACK_HDR_OFF (0)
Definition at line 74 of file sec_plain.c.
Referenced by plain_accept(), plain_alloc_repbuf(), plain_alloc_reqbuf(), plain_alloc_rs(), plain_authorize(), plain_ctx_sign(), and plain_ctx_verify().
#define PLAIN_PACK_MSG_OFF (1)
Definition at line 75 of file sec_plain.c.
Referenced by plain_accept(), plain_alloc_repbuf(), plain_alloc_reqbuf(), plain_alloc_rs(), plain_authorize(), plain_ctx_verify(), plain_enlarge_reqbuf(), and sptlrpc_plain_init().
#define PLAIN_PACK_SEGMENTS (4)
Definition at line 72 of file sec_plain.c.
Referenced by plain_accept(), plain_alloc_repbuf(), plain_alloc_reqbuf(), plain_alloc_rs(), plain_cli_unwrap_bulk(), plain_cli_wrap_bulk(), plain_ctx_verify(), and sptlrpc_plain_init().
#define PLAIN_PACK_USER_OFF (2)
Definition at line 76 of file sec_plain.c.
Referenced by plain_accept(), and plain_alloc_reqbuf().
Function Documentation
static void corrupt_bulk_data (struct ptlrpc_bulk_desc * desc) [static]
Definition at line 157 of file sec_plain.c.
References BD_GET_KIOV, ptlrpc_bulk_desc::bd_iov_count, ptlrpc_bulk_desc::bd_type, LASSERT, and ptlrpc_is_bulk_desc_kiov().
Referenced by plain_svc_wrap_bulk().
static int plain_accept (struct ptlrpc_request * req) [static]
Definition at line 731 of file sec_plain.c.
References BULK_HASH_ALG_MAX, CERROR, ENTRY, sptlrpc_flavor::hash, bulk_spec_hash::hash_alg, LASSERT, lustre_msg, lustre_msg_buf(), msg, plain_header::ph_bulk_hash_alg, plain_header::ph_flags, plain_header::ph_sp, plain_header::ph_ver, PLAIN_FL_BULK, PLAIN_FL_USER, PLAIN_PACK_HDR_OFF, PLAIN_PACK_MSG_OFF, PLAIN_PACK_SEGMENTS, PLAIN_PACK_USER_OFF, plain_unpack_bsd(), ptlrpc_req_need_swab(), RETURN, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_pack_udesc, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqlen, ptlrpc_request::rq_reqmsg, SECSVC_DROP, SECSVC_OK, sptlrpc_flavor::sf_rpc, SPTLRPC_FLVR_BASE, SPTLRPC_FLVR_BULK_TYPE, SPTLRPC_FLVR_PLAIN, SPTLRPC_FLVR_POLICY, SPTLRPC_POLICY_PLAIN, sptlrpc_unpack_user_desc(), and sptlrpc_flavor::u_bulk.
static int plain_alloc_repbuf (struct ptlrpc_sec * sec, struct ptlrpc_request * req, int msgsize) [static]
Definition at line 611 of file sec_plain.c.
References ENTRY, LASSERT, lustre_msg_size_v2(), OBD_ALLOC_LARGE, plain_at_offset, PLAIN_BSD_SIZE, PLAIN_PACK_BULK_OFF, PLAIN_PACK_HDR_OFF, PLAIN_PACK_MSG_OFF, PLAIN_PACK_SEGMENTS, RETURN, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_repbuf, ptlrpc_request::rq_repbuf_len, and size_roundup_power2().
static int plain_alloc_reqbuf (struct ptlrpc_sec * sec, struct ptlrpc_request * req, int msgsize) [static]
Definition at line 552 of file sec_plain.c.
References ENTRY, LASSERT, lustre_init_msg_v2(), lustre_msg_buf(), lustre_msg_size_v2(), OBD_ALLOC_LARGE, PLAIN_BSD_SIZE, PLAIN_PACK_BULK_OFF, PLAIN_PACK_HDR_OFF, PLAIN_PACK_MSG_OFF, PLAIN_PACK_SEGMENTS, PLAIN_PACK_USER_OFF, RETURN, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_pack_udesc, ptlrpc_request::rq_pool, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqbuf_len, ptlrpc_request::rq_reqmsg, size_roundup_power2(), sptlrpc_current_user_desc_size(), and sptlrpc_pack_user_desc().
static int plain_alloc_rs (struct ptlrpc_request * req, int msgsize) [static]
Definition at line 803 of file sec_plain.c.
References ENTRY, LASSERT, lustre_init_msg_v2(), lustre_msg, lustre_msg_buf_v2(), lustre_msg_size_v2(), OBD_ALLOC_LARGE, PLAIN_BSD_SIZE, PLAIN_PACK_BULK_OFF, PLAIN_PACK_HDR_OFF, PLAIN_PACK_MSG_OFF, PLAIN_PACK_SEGMENTS, RETURN, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_pack_bulk, ptlrpc_reply_state::rs_repbuf, ptlrpc_reply_state::rs_repbuf_len, ptlrpc_reply_state::rs_size, and ptlrpc_reply_state::rs_svc_ctx.
static int plain_authorize (struct ptlrpc_request * req) [static]
Definition at line 859 of file sec_plain.c.
References cfs_crypto_hash_digest(), CFS_HASH_ALG_CRC32, ENTRY, sptlrpc_flavor::hash, bulk_spec_hash::hash_alg, LASSERT, likely, lustre_msg_v2::lm_bufcount, lustre_msg_v2::lm_buflens, lustre_msg_v2::lm_cksum, lustre_msg_v2::lm_secflvr, lustre_msg_buf(), lustre_msg_buflen(), lustre_msg_size_v2(), lustre_msghdr_get_flags(), lustre_shrink_msg(), msg, MSGHDR_AT_SUPPORT, plain_header::ph_bulk_hash_alg, plain_header::ph_flags, plain_header::ph_ver, plain_at_offset, PLAIN_FL_BULK, PLAIN_PACK_HDR_OFF, PLAIN_PACK_MSG_OFF, RETURN, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_packed_final, ptlrpc_request::rq_replen, ptlrpc_request::rq_reply_off, ptlrpc_request::rq_reqmsg, ptlrpc_reply_state::rs_repbuf, ptlrpc_reply_state::rs_repdata_len, sptlrpc_flavor::sf_rpc, and sptlrpc_flavor::u_bulk.
static int plain_cli_unwrap_bulk (struct ptlrpc_cli_ctx * ctx, struct ptlrpc_request * req, struct ptlrpc_bulk_desc * desc) [static]
Definition at line 337 of file sec_plain.c.
References BD_GET_KIOV, ptlrpc_bulk_desc::bd_iov_count, ptlrpc_bulk_desc::bd_nob_transferred, ptlrpc_bulk_desc::bd_type, ptlrpc_bulk_sec_desc::bsd_data, BSD_FL_ERR, ptlrpc_bulk_sec_desc::bsd_flags, CERROR, sptlrpc_flavor::hash, bulk_spec_hash::hash_alg, LASSERT, lustre_msg_buf(), PLAIN_PACK_BULK_OFF, PLAIN_PACK_SEGMENTS, plain_verify_bulk_csum(), ptlrpc_is_bulk_desc_kiov(), ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_repdata, ptlrpc_request::rq_reqbuf, and sptlrpc_flavor::u_bulk.
static int plain_cli_wrap_bulk (struct ptlrpc_cli_ctx * ctx, struct ptlrpc_request * req, struct ptlrpc_bulk_desc * desc) [static]
Definition at line 294 of file sec_plain.c.
References ptlrpc_bulk_sec_desc::bsd_data, ptlrpc_bulk_sec_desc::bsd_flags, ptlrpc_bulk_sec_desc::bsd_svc, ptlrpc_bulk_sec_desc::bsd_type, ptlrpc_bulk_sec_desc::bsd_version, BULK_HASH_ALG_NULL, CERROR, sptlrpc_flavor::hash, bulk_spec_hash::hash_alg, LASSERT, lustre_msg_buf(), OBD_FAIL_CHECK, OBD_FAIL_OSC_CHECKSUM_SEND, plain_bulk_token::pbt_hash, plain_generate_bulk_csum(), PLAIN_PACK_BULK_OFF, PLAIN_PACK_SEGMENTS, RETURN, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_reqbuf, sptlrpc_flavor::sf_rpc, SPTLRPC_BULK_DEFAULT, SPTLRPC_BULK_SVC_NULL, SPTLRPC_FLVR_BULK_SVC, and sptlrpc_flavor::u_bulk.
static struct ptlrpc_sec* plain_create_sec (struct obd_import * imp, struct ptlrpc_svc_ctx * svc_ctx, struct sptlrpc_flavor * sf) [static, read]
Definition at line 447 of file sec_plain.c.
References class_import_get(), ENTRY, INIT_LIST_HEAD, LASSERT, OBD_ALLOC_PTR, plain_destroy_sec(), plain_policy, plain_sec_install_ctx(), plain_sec::pls_base, plain_sec::pls_ctx, plain_sec::pls_lock, ptlrpc_sec::ps_flvr, ptlrpc_sec::ps_gc_interval, ptlrpc_sec::ps_gc_list, ptlrpc_sec::ps_gc_next, ptlrpc_sec::ps_id, ptlrpc_sec::ps_import, ptlrpc_sec::ps_lock, ptlrpc_sec::ps_nctx, ptlrpc_sec::ps_policy, ptlrpc_sec::ps_refcount, RETURN, sptlrpc_flavor::sf_rpc, sptlrpc_cli_ctx_put(), SPTLRPC_FLVR_POLICY, sptlrpc_get_next_secid(), and SPTLRPC_POLICY_PLAIN.
static int plain_ctx_refresh (struct ptlrpc_cli_ctx * ctx) [static]
Definition at line 181 of file sec_plain.c.
References LBUG.
static int plain_ctx_sign (struct ptlrpc_cli_ctx * ctx, struct ptlrpc_request * req) [static]
Definition at line 195 of file sec_plain.c.
References ptlrpc_cli_ctx::cc_sec, ENTRY, sptlrpc_flavor::hash, bulk_spec_hash::hash_alg, lustre_msg, lustre_msg_buf(), lustre_msg_size_v2(), msg, plain_header::ph_bulk_hash_alg, plain_header::ph_flags, plain_header::ph_sp, plain_header::ph_ver, PLAIN_FL_BULK, PLAIN_FL_USER, PLAIN_PACK_HDR_OFF, ptlrpc_sec::ps_part, RETURN, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_pack_udesc, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqdata_len, sptlrpc_flavor::sf_rpc, and sptlrpc_flavor::u_bulk.
static int plain_ctx_validate (struct ptlrpc_cli_ctx * ctx) [static]
Definition at line 189 of file sec_plain.c.
static int plain_ctx_verify (struct ptlrpc_cli_ctx * ctx, struct ptlrpc_request * req) [static]
Definition at line 220 of file sec_plain.c.
References CDEBUG, CERROR, cfs_crypto_hash_digest(), CFS_HASH_ALG_CRC32, cksum, cpu_to_le32, D_SEC, ENTRY, equi, sptlrpc_flavor::hash, bulk_spec_hash::hash_alg, lustre_msg, lustre_msg_buf(), lustre_msg_buflen(), msg, plain_header::ph_bulk_hash_alg, plain_header::ph_flags, plain_header::ph_ver, PLAIN_FL_BULK, PLAIN_FL_USER, PLAIN_PACK_HDR_OFF, PLAIN_PACK_MSG_OFF, PLAIN_PACK_SEGMENTS, plain_unpack_bsd(), ptlrpc_rep_need_swab(), RETURN, ptlrpc_request::rq_early, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_repdata, ptlrpc_request::rq_replen, ptlrpc_request::rq_repmsg, sptlrpc_flavor::u_bulk, and unlikely.
static void plain_destroy_sec (struct ptlrpc_sec * sec) [static]
Definition at line 423 of file sec_plain.c.
References class_import_put(), ENTRY, EXIT, LASSERT, OBD_FREE_PTR, plain_policy, plain_sec::pls_ctx, ptlrpc_sec::ps_import, ptlrpc_sec::ps_nctx, ptlrpc_sec::ps_policy, ptlrpc_sec::ps_refcount, and sec2plsec().
Referenced by plain_create_sec().
static int plain_enlarge_reqbuf (struct ptlrpc_sec * sec, struct ptlrpc_request * req, int segment, int newsize) [static]
Definition at line 654 of file sec_plain.c.
References _sptlrpc_enlarge_msg_inplace(), ENTRY, obd_import::imp_lock, LASSERT, lustre_msg, lustre_msg_buf(), lustre_msg_size_v2(), OBD_ALLOC_LARGE, OBD_FREE_LARGE, PLAIN_PACK_MSG_OFF, RETURN, ptlrpc_request::rq_import, ptlrpc_request::rq_pool, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqbuf_len, ptlrpc_request::rq_reqlen, ptlrpc_request::rq_reqmsg, and size_roundup_power2().
static int plain_flush_ctx_cache (struct ptlrpc_sec * sec, uid_t uid, int grace, int force) [static]
Definition at line 530 of file sec_plain.c.
References ENTRY, plain_sec::pls_ctx, plain_sec::pls_lock, RETURN, sec2plsec(), and sptlrpc_cli_ctx_put().
static void plain_free_repbuf (struct ptlrpc_sec * sec, struct ptlrpc_request * req) [static]
Definition at line 643 of file sec_plain.c.
References ENTRY, EXIT, OBD_FREE_LARGE, ptlrpc_request::rq_repbuf, and ptlrpc_request::rq_repbuf_len.
static void plain_free_reqbuf (struct ptlrpc_sec * sec, struct ptlrpc_request * req) [static]
Definition at line 598 of file sec_plain.c.
References ENTRY, EXIT, OBD_FREE_LARGE, ptlrpc_request::rq_pool, ptlrpc_request::rq_reqbuf, and ptlrpc_request::rq_reqbuf_len.
static void plain_free_rs (struct ptlrpc_reply_state * rs) [static]
Definition at line 846 of file sec_plain.c.
References ENTRY, EXIT, LASSERT, OBD_FREE_LARGE, ptlrpc_reply_state::rs_prealloc, ptlrpc_reply_state::rs_size, ptlrpc_reply_state::rs_svc_ctx, and ptlrpc_svc_ctx::sc_refcount.
static int plain_generate_bulk_csum (struct ptlrpc_bulk_desc * desc, __u8 hash_alg, struct plain_bulk_token * token) [static]
Definition at line 124 of file sec_plain.c.
References BULK_HASH_ALG_NULL, plain_bulk_token::pbt_hash, and sptlrpc_get_bulk_checksum().
Referenced by plain_cli_wrap_bulk(), and plain_svc_wrap_bulk().
static void plain_kill_sec (struct ptlrpc_sec * sec) [static]
Definition at line 441 of file sec_plain.c.
References ptlrpc_sec::ps_dying.
static struct ptlrpc_cli_ctx* plain_lookup_ctx (struct ptlrpc_sec * sec, struct vfs_cred * vcred, int create, int remove_dead) [static, read]
Definition at line 494 of file sec_plain.c.
References ptlrpc_cli_ctx::cc_refcount, ENTRY, plain_sec_install_ctx(), plain_sec::pls_ctx, plain_sec::pls_lock, RETURN, sec2plsec(), and unlikely.
static void plain_release_ctx (struct ptlrpc_sec * sec, struct ptlrpc_cli_ctx * ctx, int sync) [static]
Definition at line 515 of file sec_plain.c.
References ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_sec, LASSERT, OBD_FREE_PTR, ptlrpc_sec::ps_nctx, ptlrpc_sec::ps_refcount, and sptlrpc_sec_put().
static struct ptlrpc_cli_ctx* plain_sec_install_ctx (struct plain_sec * plsec) [static, read]
Definition at line 383 of file sec_plain.c.
References ptlrpc_cli_ctx::cc_expire, ptlrpc_cli_ctx::cc_flags, ptlrpc_cli_ctx::cc_gc_chain, ptlrpc_cli_ctx::cc_lock, ptlrpc_cli_ctx::cc_ops, ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_req_list, ptlrpc_cli_ctx::cc_sec, ptlrpc_cli_ctx::cc_vcred, INIT_LIST_HEAD, OBD_ALLOC_PTR, OBD_FREE_PTR, plain_ctx_ops, plain_sec::pls_base, plain_sec::pls_ctx, plain_sec::pls_lock, ptlrpc_sec::ps_nctx, ptlrpc_sec::ps_refcount, PTLRPC_CTX_CACHED, PTLRPC_CTX_UPTODATE, and vfs_cred::vc_uid.
Referenced by plain_create_sec(), and plain_lookup_ctx().
static int plain_svc_unwrap_bulk (struct ptlrpc_request * req, struct ptlrpc_bulk_desc * desc) [static]
Definition at line 907 of file sec_plain.c.
References ptlrpc_bulk_sec_desc::bsd_data, BSD_FL_ERR, ptlrpc_bulk_sec_desc::bsd_flags, ptlrpc_bulk_sec_desc::bsd_svc, ptlrpc_bulk_sec_desc::bsd_type, ptlrpc_bulk_sec_desc::bsd_version, CERROR, sptlrpc_flavor::hash, bulk_spec_hash::hash_alg, LASSERT, lustre_msg_buf(), PLAIN_PACK_BULK_OFF, plain_verify_bulk_csum(), ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_reqbuf, ptlrpc_reply_state::rs_repbuf, SPTLRPC_BULK_DEFAULT, SPTLRPC_BULK_SVC_NULL, and sptlrpc_flavor::u_bulk.
static int plain_svc_wrap_bulk (struct ptlrpc_request * req, struct ptlrpc_bulk_desc * desc) [static]
Definition at line 941 of file sec_plain.c.
References ptlrpc_bulk_sec_desc::bsd_data, ptlrpc_bulk_sec_desc::bsd_flags, ptlrpc_bulk_sec_desc::bsd_svc, ptlrpc_bulk_sec_desc::bsd_type, ptlrpc_bulk_sec_desc::bsd_version, CERROR, corrupt_bulk_data(), sptlrpc_flavor::hash, bulk_spec_hash::hash_alg, LASSERT, lustre_msg_buf(), OBD_FAIL_CHECK, OBD_FAIL_OSC_CHECKSUM_RECEIVE, plain_generate_bulk_csum(), PLAIN_PACK_BULK_OFF, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_reqbuf, ptlrpc_reply_state::rs_repbuf, SPTLRPC_BULK_DEFAULT, SPTLRPC_BULK_SVC_NULL, and sptlrpc_flavor::u_bulk.
static int plain_unpack_bsd (struct lustre_msg * msg, int swabbed) [static]
Definition at line 101 of file sec_plain.c.
References ptlrpc_bulk_sec_desc::bsd_svc, bulk_sec_desc_unpack(), CERROR, lustre_msg_buf(), lustre_msg_buflen(), PLAIN_BSD_SIZE, PLAIN_PACK_BULK_OFF, SPTLRPC_BULK_SVC_INTG, and SPTLRPC_BULK_SVC_NULL.
Referenced by plain_accept(), and plain_ctx_verify().
static int plain_verify_bulk_csum (struct ptlrpc_bulk_desc * desc, __u8 hash_alg, struct plain_bulk_token * tokenr) [static]
Definition at line 136 of file sec_plain.c.
References BULK_HASH_ALG_NULL, plain_bulk_token::pbt_hash, and sptlrpc_get_bulk_checksum().
Referenced by plain_cli_unwrap_bulk(), and plain_svc_unwrap_bulk().
static struct plain_sec* sec2plsec (struct ptlrpc_sec * sec) [static, read]
Definition at line 58 of file sec_plain.c.
References plain_sec::pls_base.
Referenced by plain_destroy_sec(), plain_flush_ctx_cache(), and plain_lookup_ctx().
void sptlrpc_plain_fini (void)
Definition at line 1032 of file sec_plain.c.
References CERROR, and sptlrpc_unregister_policy().
Referenced by sptlrpc_fini(), and sptlrpc_init().
int sptlrpc_plain_init (void)
Definition at line 1017 of file sec_plain.c.
References CERROR, lustre_msg_early_size(), lustre_msg_size_v2(), plain_at_offset, PLAIN_PACK_MSG_OFF, PLAIN_PACK_SEGMENTS, and sptlrpc_register_policy().
Referenced by sptlrpc_init().
Variable Documentation
unsigned int plain_at_offset [static]
Definition at line 67 of file sec_plain.c.
Referenced by plain_alloc_repbuf(), plain_authorize(), and sptlrpc_plain_init().
static struct ptlrpc_ctx_ops plain_ctx_ops [static, read]
Initial value:
 {
        .refresh                = plain_ctx_refresh,
        .validate               = plain_ctx_validate,
        .sign                   = plain_ctx_sign,
        .verify                 = plain_ctx_verify,
        .wrap_bulk              = plain_cli_wrap_bulk,
        .unwrap_bulk            = plain_cli_unwrap_bulk,
}
Definition at line 64 of file sec_plain.c.
Referenced by plain_sec_install_ctx().
static struct ptlrpc_sec_policy plain_policy [static, read]
Initial value:
 {
        .sp_owner               = THIS_MODULE,
        .sp_name                = "plain",
        .sp_policy              = SPTLRPC_POLICY_PLAIN,
        .sp_cops                = &plain_sec_cops,
        .sp_sops                = &plain_sec_sops,
}
Definition at line 63 of file sec_plain.c.
Referenced by plain_create_sec(), and plain_destroy_sec().
struct ptlrpc_sec_cops plain_sec_cops [static]
Initial value:
 {
        .create_sec             = plain_create_sec,
        .destroy_sec            = plain_destroy_sec,
        .kill_sec               = plain_kill_sec,
        .lookup_ctx             = plain_lookup_ctx,
        .release_ctx            = plain_release_ctx,
        .flush_ctx_cache        = plain_flush_ctx_cache,
        .alloc_reqbuf           = plain_alloc_reqbuf,
        .free_reqbuf            = plain_free_reqbuf,
        .alloc_repbuf           = plain_alloc_repbuf,
        .free_repbuf            = plain_free_repbuf,
        .enlarge_reqbuf         = plain_enlarge_reqbuf,
}
Definition at line 986 of file sec_plain.c.
struct ptlrpc_sec_sops plain_sec_sops [static]
Initial value:
 {
        .accept                 = plain_accept,
        .alloc_rs               = plain_alloc_rs,
        .authorize              = plain_authorize,
        .free_rs                = plain_free_rs,
        .unwrap_bulk            = plain_svc_unwrap_bulk,
        .wrap_bulk              = plain_svc_wrap_bulk,
}
Definition at line 1000 of file sec_plain.c.
static struct ptlrpc_svc_ctx plain_svc_ctx [static, read]
Initial value:
 {
        .sc_refcount    = ATOMIC_INIT(1),
        .sc_policy      = &plain_policy,
}
Definition at line 65 of file sec_plain.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.