Lustre: lustre/ptlrpc/sec_gc.c File Reference
lustre/ptlrpc/sec_gc.c File Reference
#include <linux/kthread.h>
#include <libcfs/libcfs.h>
#include <obd_support.h>
#include <obd_class.h>
#include <lustre_net.h>
#include <lustre_sec.h>
#include "ptlrpc_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_SEC
#define SEC_GC_INTERVAL (30 * 60)
Functions
void sptlrpc_gc_add_sec (struct ptlrpc_sec *sec)
void sptlrpc_gc_del_sec (struct ptlrpc_sec *sec)
void sptlrpc_gc_add_ctx (struct ptlrpc_cli_ctx *ctx)
static void sec_process_ctx_list (void)
static void sec_do_gc (struct ptlrpc_sec *sec)
static int sec_gc_main (void *arg)
int sptlrpc_gc_init (void)
void sptlrpc_gc_fini (void)
Variables
static struct mutex sec_gc_mutex
static spinlock_t sec_gc_list_lock
static struct list_head sec_gc_list
static spinlock_t sec_gc_ctx_list_lock
static struct list_head sec_gc_ctx_list
static struct ptlrpc_thread sec_gc_thread
static atomic_t sec_gc_wait_del = ATOMIC_INIT(0)
Define Documentation
#define DEBUG_SUBSYSTEM S_SEC
Definition at line 41 of file sec_gc.c.
#define SEC_GC_INTERVAL (30 * 60)
Definition at line 53 of file sec_gc.c.
Referenced by sec_gc_main().
Function Documentation
static void sec_do_gc (struct ptlrpc_sec * sec) [static]
Definition at line 144 of file sec_gc.c.
References CDEBUG, cfs_time_after(), cfs_time_current_sec(), D_SEC, ptlrpc_sec_cops::gc_ctx, LASSERT, ptlrpc_sec::ps_gc_interval, ptlrpc_sec::ps_gc_next, ptlrpc_sec::ps_policy, ptlrpc_sec_policy::sp_cops, ptlrpc_sec_policy::sp_name, and unlikely.
Referenced by sec_gc_main().
static int sec_gc_main (void * arg) [static]
Definition at line 163 of file sec_gc.c.
References CDEBUG, D_SEC, l_wait_event, list_for_each_entry, LWI_TIMEOUT, ptlrpc_sec::ps_gc_list, sec_do_gc(), SEC_GC_INTERVAL, sec_gc_list, sec_gc_mutex, sec_gc_wait_del, sec_process_ctx_list(), SVC_RUNNING, SVC_SIGNAL, SVC_STOPPED, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, thread, thread_clear_flags(), thread_is_signal(), thread_is_stopping(), thread_set_flags(), and thread_test_and_clear_flags().
Referenced by sptlrpc_gc_init().
static void sec_process_ctx_list (void) [static]
Definition at line 120 of file sec_gc.c.
References ptlrpc_cli_ctx::cc_gc_chain, ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_sec, ptlrpc_cli_ctx::cc_vcred, CDEBUG, D_SEC, LASSERT, list_del_init(), list_empty(), list_entry, list_head::next, sec2target_str(), sec_gc_ctx_list, sec_gc_ctx_list_lock, sptlrpc_cli_ctx_put(), and vfs_cred::vc_uid.
Referenced by sec_gc_main().
void sptlrpc_gc_fini (void)
Definition at line 247 of file sec_gc.c.
References l_wait_event, sec_gc_thread, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, thread_is_stopped(), and thread_set_flags().
Referenced by sptlrpc_fini(), and sptlrpc_init().
int sptlrpc_gc_init (void)
Definition at line 220 of file sec_gc.c.
References CERROR, INIT_LIST_HEAD, l_wait_event, sec_gc_ctx_list, sec_gc_ctx_list_lock, sec_gc_list, sec_gc_list_lock, sec_gc_main(), sec_gc_mutex, sec_gc_thread, ptlrpc_thread::t_ctl_waitq, and thread_is_running().
Referenced by sptlrpc_init().
Variable Documentation
struct list_head sec_gc_ctx_list [static]
Definition at line 61 of file sec_gc.c.
Referenced by sec_process_ctx_list(), sptlrpc_gc_add_ctx(), and sptlrpc_gc_init().
spinlock_t sec_gc_ctx_list_lock [static]
Definition at line 60 of file sec_gc.c.
Referenced by sec_process_ctx_list(), sptlrpc_gc_add_ctx(), and sptlrpc_gc_init().
struct list_head sec_gc_list [static]
Definition at line 58 of file sec_gc.c.
Referenced by sec_gc_main(), sptlrpc_gc_add_sec(), and sptlrpc_gc_init().
spinlock_t sec_gc_list_lock [static]
Definition at line 57 of file sec_gc.c.
Referenced by sptlrpc_gc_add_sec(), sptlrpc_gc_del_sec(), and sptlrpc_gc_init().
struct mutex sec_gc_mutex [static]
Definition at line 56 of file sec_gc.c.
Referenced by sec_gc_main(), sptlrpc_gc_del_sec(), and sptlrpc_gc_init().
struct ptlrpc_thread sec_gc_thread [static]
Definition at line 63 of file sec_gc.c.
Referenced by sptlrpc_gc_add_ctx(), sptlrpc_gc_fini(), and sptlrpc_gc_init().
atomic_t sec_gc_wait_del = ATOMIC_INIT(0) [static]
Definition at line 64 of file sec_gc.c.
Referenced by sec_gc_main(), and sptlrpc_gc_del_sec().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.