Lustre: lustre/ptlrpc/sec.c File Reference
lustre/ptlrpc/sec.c File Reference
#include <linux/user_namespace.h>
#include <linux/crypto.h>
#include <linux/key.h>
#include <libcfs/libcfs.h>
#include <obd.h>
#include <obd_class.h>
#include <obd_support.h>
#include <lustre_net.h>
#include <lustre_import.h>
#include <lustre_dlm.h>
#include <lustre_sec.h>
#include "ptlrpc_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_SEC
#define EXP_FLVR_UPDATE_EXPIRE (OBD_TIMEOUT_DEFAULT + 10)
Functions
int sptlrpc_register_policy (struct ptlrpc_sec_policy *policy)
int sptlrpc_unregister_policy (struct ptlrpc_sec_policy *policy)
static struct ptlrpc_sec_policy * sptlrpc_wireflavor2policy (__u32 flavor)
__u32 sptlrpc_name2flavor_base (const char *name)
const char * sptlrpc_flavor2name_base (__u32 flvr)
char * sptlrpc_flavor2name_bulk (struct sptlrpc_flavor *sf, char *buf, int bufsize)
char * sptlrpc_flavor2name (struct sptlrpc_flavor *sf, char *buf, int bufsize)
char * sptlrpc_secflags2str (__u32 flags, char *buf, int bufsize)
static struct ptlrpc_cli_ctx * get_my_ctx (struct ptlrpc_sec *sec)
struct ptlrpc_cli_ctx * sptlrpc_cli_ctx_get (struct ptlrpc_cli_ctx *ctx)
void sptlrpc_cli_ctx_put (struct ptlrpc_cli_ctx *ctx, int sync)
void sptlrpc_cli_ctx_expire (struct ptlrpc_cli_ctx *ctx)
Expire the client context immediately.
void sptlrpc_cli_ctx_wakeup (struct ptlrpc_cli_ctx *ctx)
To wake up the threads who are waiting for this client context.
int sptlrpc_cli_ctx_display (struct ptlrpc_cli_ctx *ctx, char *buf, int bufsize)
static int import_sec_check_expire (struct obd_import *imp)
static int import_sec_validate_get (struct obd_import *imp, struct ptlrpc_sec **sec)
Get and validate the client side ptlrpc security facilities from imp.
int sptlrpc_req_get_ctx (struct ptlrpc_request *req)
Given a req, find or allocate an appropriate context for it.
void sptlrpc_req_put_ctx (struct ptlrpc_request *req, int sync)
Drop the context for req.
static int sptlrpc_req_ctx_switch (struct ptlrpc_request *req, struct ptlrpc_cli_ctx *oldctx, struct ptlrpc_cli_ctx *newctx)
int sptlrpc_req_replace_dead_ctx (struct ptlrpc_request *req)
If current context of req is dead somehow, e.g.
static int ctx_check_refresh (struct ptlrpc_cli_ctx *ctx)
static int ctx_refresh_timeout (void *data)
static void ctx_refresh_interrupt (void *data)
static void req_off_ctx_list (struct ptlrpc_request *req, struct ptlrpc_cli_ctx *ctx)
int sptlrpc_req_refresh_ctx (struct ptlrpc_request *req, long timeout)
To refresh the context of , if it's not up-to-date.
void sptlrpc_req_set_flavor (struct ptlrpc_request *req, int opcode)
Initialize flavor settings for req, according to opcode.
void sptlrpc_request_out_callback (struct ptlrpc_request *req)
int sptlrpc_import_check_ctx (struct obd_import *imp)
Given an import imp, check whether current user has a valid context or not.
int sptlrpc_cli_wrap_request (struct ptlrpc_request *req)
Used by ptlrpc client, to perform the pre-defined security transformation upon the request message of req.
static int do_cli_unwrap_reply (struct ptlrpc_request *req)
int sptlrpc_cli_unwrap_reply (struct ptlrpc_request *req)
Used by ptlrpc client, to perform security transformation upon the reply message of req.
int sptlrpc_cli_unwrap_early_reply (struct ptlrpc_request *req, struct ptlrpc_request **req_ret)
Used by ptlrpc client, to perform security transformation upon the early reply message of req.
void sptlrpc_cli_finish_early_reply (struct ptlrpc_request *early_req)
Used by ptlrpc client, to release a processed early reply early_req.
int sptlrpc_get_next_secid (void)
static int sec_cop_flush_ctx_cache (struct ptlrpc_sec *sec, uid_t uid, int grace, int force)
static void sec_cop_destroy_sec (struct ptlrpc_sec *sec)
void sptlrpc_sec_destroy (struct ptlrpc_sec *sec)
static void sptlrpc_sec_kill (struct ptlrpc_sec *sec)
struct ptlrpc_sec * sptlrpc_sec_get (struct ptlrpc_sec *sec)
void sptlrpc_sec_put (struct ptlrpc_sec *sec)
static struct ptlrpc_sec * sptlrpc_sec_create (struct obd_import *imp, struct ptlrpc_svc_ctx *svc_ctx, struct sptlrpc_flavor *sf, enum lustre_sec_part sp)
struct ptlrpc_sec * sptlrpc_import_sec_ref (struct obd_import *imp)
static void sptlrpc_import_sec_install (struct obd_import *imp, struct ptlrpc_sec *sec)
static int flavor_equal (struct sptlrpc_flavor *sf1, struct sptlrpc_flavor *sf2)
static void flavor_copy (struct sptlrpc_flavor *dst, struct sptlrpc_flavor *src)
static void sptlrpc_import_sec_adapt_inplace (struct obd_import *imp, struct ptlrpc_sec *sec, struct sptlrpc_flavor *sf)
int sptlrpc_import_sec_adapt (struct obd_import *imp, struct ptlrpc_svc_ctx *svc_ctx, struct sptlrpc_flavor *flvr)
To get an appropriate ptlrpc_sec for the imp, according to the current configuration.
void sptlrpc_import_sec_put (struct obd_import *imp)
static void import_flush_ctx_common (struct obd_import *imp, uid_t uid, int grace, int force)
void sptlrpc_import_flush_root_ctx (struct obd_import *imp)
void sptlrpc_import_flush_my_ctx (struct obd_import *imp)
void sptlrpc_import_flush_all_ctx (struct obd_import *imp)
int sptlrpc_cli_alloc_reqbuf (struct ptlrpc_request *req, int msgsize)
Used by ptlrpc client to allocate request buffer of req.
void sptlrpc_cli_free_reqbuf (struct ptlrpc_request *req)
Used by ptlrpc client to free request buffer of req.
void _sptlrpc_enlarge_msg_inplace (struct lustre_msg *msg, int segment, int newsize)
int sptlrpc_cli_enlarge_reqbuf (struct ptlrpc_request *req, int segment, int newsize)
Used by ptlrpc client to enlarge the segment of request message pointed by req->rq_reqmsg to size newsize, all previously filled-in data will be preserved after the enlargement.
int sptlrpc_cli_alloc_repbuf (struct ptlrpc_request *req, int msgsize)
Used by ptlrpc client to allocate reply buffer of req.
void sptlrpc_cli_free_repbuf (struct ptlrpc_request *req)
Used by ptlrpc client to free reply buffer of req.
int sptlrpc_cli_install_rvs_ctx (struct obd_import *imp, struct ptlrpc_cli_ctx *ctx)
int sptlrpc_svc_install_rvs_ctx (struct obd_import *imp, struct ptlrpc_svc_ctx *ctx)
static int flavor_allowed (struct sptlrpc_flavor *exp, struct ptlrpc_request *req)
int sptlrpc_target_export_check (struct obd_export *exp, struct ptlrpc_request *req)
Given an export exp, check whether the flavor of incoming req is allowed by the export exp.
void sptlrpc_target_update_exp_flavor (struct obd_device *obd, struct sptlrpc_rule_set *rset)
static int sptlrpc_svc_check_from (struct ptlrpc_request *req, int svc_rc)
int sptlrpc_svc_unwrap_request (struct ptlrpc_request *req)
Used by ptlrpc server, to perform transformation upon request message of incoming req.
int sptlrpc_svc_alloc_rs (struct ptlrpc_request *req, int msglen)
Used by ptlrpc server, to allocate reply buffer for req.
int sptlrpc_svc_wrap_reply (struct ptlrpc_request *req)
Used by ptlrpc server, to perform transformation upon reply message.
void sptlrpc_svc_free_rs (struct ptlrpc_reply_state *rs)
Used by ptlrpc server, to free reply_state.
void sptlrpc_svc_ctx_addref (struct ptlrpc_request *req)
void sptlrpc_svc_ctx_decref (struct ptlrpc_request *req)
void sptlrpc_svc_ctx_invalidate (struct ptlrpc_request *req)
int sptlrpc_cli_wrap_bulk (struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
Perform transformation upon bulk data pointed by desc.
int sptlrpc_cli_unwrap_bulk_read (struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc, int nob)
This is called after unwrap the reply message.
int sptlrpc_cli_unwrap_bulk_write (struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
This is called after unwrap the reply message.
int sptlrpc_current_user_desc_size (void)
int sptlrpc_pack_user_desc (struct lustre_msg *msg, int offset)
int sptlrpc_unpack_user_desc (struct lustre_msg *msg, int offset, int swabbed)
const char * sec2target_str (struct ptlrpc_sec *sec)
int sptlrpc_flavor_has_bulk (struct sptlrpc_flavor *flvr)
int sptlrpc_init (void)
void sptlrpc_fini (void)
Variables
static rwlock_t policy_lock
static struct ptlrpc_sec_policy * policies [SPTLRPC_POLICY_MAX]
static atomic_t sptlrpc_sec_id = ATOMIC_INIT(1)
Define Documentation
#define DEBUG_SUBSYSTEM S_SEC
Definition at line 41 of file sec.c.
#define EXP_FLVR_UPDATE_EXPIRE (OBD_TIMEOUT_DEFAULT + 10)
Definition at line 1790 of file sec.c.
Referenced by sptlrpc_target_export_check().
Function Documentation
static int ctx_check_refresh (struct ptlrpc_cli_ctx * ctx) [static]
Definition at line 614 of file sec.c.
References cli_ctx_is_refreshed().
Referenced by sptlrpc_req_refresh_ctx().
static void ctx_refresh_interrupt (void * data) [static]
Definition at line 643 of file sec.c.
References ptlrpc_request::rq_intr, and ptlrpc_request::rq_lock.
Referenced by sptlrpc_req_refresh_ctx().
static int ctx_refresh_timeout (void * data) [static]
Definition at line 622 of file sec.c.
References obd_import::imp_conn_cnt, lustre_msg_set_conn_cnt(), ptlrpc_expire_one_request(), ptlrpc_request::rq_import, and ptlrpc_request::rq_reqmsg.
Referenced by sptlrpc_req_refresh_ctx().
static int do_cli_unwrap_reply (struct ptlrpc_request * req) [static]
Definition at line 1021 of file sec.c.
References __lustre_unpack_msg(), ptlrpc_cli_ctx::cc_ops, ptlrpc_cli_ctx::cc_sec, CERROR, ENTRY, LASSERT, LBUG, LPU64, lustre_msg, lustre_set_rep_swabbed(), MSG_PTLRPC_HEADER_OFF, RETURN, ptlrpc_request::rq_ctx_init, ptlrpc_request::rq_flvr, ptlrpc_request::rq_rep_swab_mask, ptlrpc_request::rq_repbuf, ptlrpc_request::rq_repdata, ptlrpc_request::rq_repdata_len, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_resend, ptlrpc_request::rq_xid, sptlrpc_flavor::sf_rpc, SPTLRPC_FLVR_POLICY, SPTLRPC_FLVR_SVC, SPTLRPC_POLICY_NULL, SPTLRPC_SVC_AUTH, SPTLRPC_SVC_INTG, SPTLRPC_SVC_NULL, SPTLRPC_SVC_PRIV, ptlrpc_ctx_ops::unseal, and ptlrpc_ctx_ops::verify.
Referenced by sptlrpc_cli_unwrap_early_reply(), and sptlrpc_cli_unwrap_reply().
static int flavor_allowed (struct sptlrpc_flavor * exp, struct ptlrpc_request * req) [static]
Definition at line 1773 of file sec.c.
References ptlrpc_request::rq_ctx_fini, ptlrpc_request::rq_ctx_init, ptlrpc_request::rq_flvr, sptlrpc_flavor::sf_rpc, SPTLRPC_FLVR_ANY, SPTLRPC_FLVR_MECH, and SPTLRPC_FLVR_POLICY.
Referenced by sptlrpc_target_export_check().
static void flavor_copy (struct sptlrpc_flavor * dst, struct sptlrpc_flavor * src) [inline, static]
Definition at line 1408 of file sec.c.
Referenced by sptlrpc_import_sec_adapt_inplace().
static int flavor_equal (struct sptlrpc_flavor * sf1, struct sptlrpc_flavor * sf2) [inline, static]
Definition at line 1402 of file sec.c.
Referenced by sptlrpc_import_sec_adapt(), and sptlrpc_target_update_exp_flavor().
static struct ptlrpc_cli_ctx* get_my_ctx (struct ptlrpc_sec * sec) [static, read]
Definition at line 271 of file sec.c.
References from_kgid(), from_kuid(), LASSERT, ptlrpc_sec_cops::lookup_ctx, ptlrpc_sec::ps_flvr, ptlrpc_sec::ps_policy, PTLRPC_SEC_FL_REVERSE, PTLRPC_SEC_FL_ROOTONLY, sptlrpc_flavor::sf_flags, ptlrpc_sec_policy::sp_cops, vfs_cred::vc_gid, and vfs_cred::vc_uid.
Referenced by sptlrpc_import_check_ctx(), and sptlrpc_req_get_ctx().
static void import_flush_ctx_common (struct obd_import * imp, uid_t uid, int grace, int force) [static]
Definition at line 1540 of file sec.c.
References sec_cop_flush_ctx_cache(), sptlrpc_import_sec_ref(), and sptlrpc_sec_put().
Referenced by sptlrpc_import_flush_all_ctx(), sptlrpc_import_flush_my_ctx(), and sptlrpc_import_flush_root_ctx().
static int import_sec_check_expire (struct obd_import * imp) [static]
Definition at line 357 of file sec.c.
References CDEBUG, cfs_time_current_sec(), D_SEC, obd_import::imp_lock, obd_import::imp_sec_expire, and sptlrpc_import_sec_adapt().
Referenced by import_sec_validate_get().
static int import_sec_validate_get (struct obd_import * imp, struct ptlrpc_sec ** sec) [static]
Get and validate the client side ptlrpc security facilities from imp.
There is a race condition on client reconnect when the import is being destroyed while there are outstanding client bound requests. In this case do not output any error messages if import secuity is not found.
Parameters:
[in] imp obd import associated with client
[out] sec client side ptlrpc security
Return values:
0 if security retrieved successfully
-ve errno if there was a problem
Definition at line 389 of file sec.c.
References CERROR, obd_import::imp_sec_expire, obd_import::imp_state, obd_import::imp_zombie_chain, import_sec_check_expire(), list_empty(), ptlrpc_import_state_name(), sptlrpc_import_sec_ref(), sptlrpc_sec_put(), and unlikely.
Referenced by sptlrpc_req_get_ctx(), and sptlrpc_req_refresh_ctx().
static void req_off_ctx_list (struct ptlrpc_request * req, struct ptlrpc_cli_ctx * ctx) [static]
Definition at line 653 of file sec.c.
References ptlrpc_cli_ctx::cc_lock, list_del_init(), and list_empty().
Referenced by sptlrpc_req_refresh_ctx().
static void sec_cop_destroy_sec (struct ptlrpc_sec * sec) [static]
Definition at line 1262 of file sec.c.
References CDEBUG, D_SEC, ptlrpc_sec_cops::destroy_sec, LASSERT, LASSERT_ATOMIC_ZERO, ptlrpc_sec::ps_nctx, ptlrpc_sec::ps_policy, ptlrpc_sec::ps_refcount, ptlrpc_sec_policy::sp_cops, ptlrpc_sec_policy::sp_name, and sptlrpc_policy_put().
Referenced by sptlrpc_sec_destroy(), and sptlrpc_sec_put().
static int sec_cop_flush_ctx_cache (struct ptlrpc_sec * sec, uid_t uid, int grace, int force) [static]
Definition at line 1251 of file sec.c.
References ptlrpc_sec_cops::flush_ctx_cache, LASSERT, ptlrpc_sec::ps_policy, and ptlrpc_sec_policy::sp_cops.
Referenced by import_flush_ctx_common(), and sptlrpc_sec_kill().
void sptlrpc_fini (void)
Definition at line 2590 of file sec.c.
References sptlrpc_conf_fini(), sptlrpc_enc_pool_fini(), sptlrpc_gc_fini(), sptlrpc_lproc_fini(), sptlrpc_null_fini(), and sptlrpc_plain_fini().
Referenced by ptlrpc_exit(), and ptlrpc_init().
static void sptlrpc_import_sec_adapt_inplace (struct obd_import * imp, struct ptlrpc_sec * sec, struct sptlrpc_flavor * sf) [static]
Definition at line 1413 of file sec.c.
References CDEBUG, D_SEC, flavor_copy(), ptlrpc_sec::ps_flvr, ptlrpc_sec::ps_lock, sptlrpc_flavor::sf_flags, and sptlrpc_secflags2str().
Referenced by sptlrpc_import_sec_adapt().
static void sptlrpc_import_sec_install (struct obd_import * imp, struct ptlrpc_sec * sec) [static]
Definition at line 1381 of file sec.c.
References obd_import::imp_lock, obd_import::imp_sec, LASSERT_ATOMIC_POS, ptlrpc_sec::ps_refcount, sptlrpc_sec_kill(), and sptlrpc_sec_put().
Referenced by sptlrpc_import_sec_adapt().
int sptlrpc_init (void)
Definition at line 2544 of file sec.c.
References policy_lock, sptlrpc_conf_fini(), sptlrpc_conf_init(), sptlrpc_enc_pool_fini(), sptlrpc_enc_pool_init(), sptlrpc_gc_fini(), sptlrpc_gc_init(), sptlrpc_lproc_init(), sptlrpc_null_fini(), sptlrpc_null_init(), sptlrpc_plain_fini(), and sptlrpc_plain_init().
Referenced by ptlrpc_init().
static int sptlrpc_req_ctx_switch (struct ptlrpc_request * req, struct ptlrpc_cli_ctx * oldctx, struct ptlrpc_cli_ctx * newctx) [static]
Definition at line 482 of file sec.c.
References ptlrpc_cli_ctx::cc_sec, ptlrpc_cli_ctx::cc_vcred, CDEBUG, CWARN, D_SEC, LASSERT, OBD_ALLOC_LARGE, OBD_FREE_LARGE, ptlrpc_sec::ps_policy, ptlrpc_request::rq_flvr, ptlrpc_request::rq_replen, ptlrpc_request::rq_reqlen, ptlrpc_request::rq_reqmsg, sec2target_str(), ptlrpc_sec_policy::sp_name, sptlrpc_cli_alloc_reqbuf(), sptlrpc_cli_free_repbuf(), sptlrpc_cli_free_reqbuf(), sptlrpc_req_set_flavor(), and vfs_cred::vc_uid.
Referenced by sptlrpc_req_replace_dead_ctx().
static struct ptlrpc_sec* sptlrpc_sec_create (struct obd_import * imp, struct ptlrpc_svc_ctx * svc_ctx, struct sptlrpc_flavor * sf, enum lustre_sec_part sp) [static, read]
Definition at line 1319 of file sec.c.
References CDEBUG, CERROR, ptlrpc_sec_cops::create_sec, D_SEC, ENTRY, ptlrpc_sec_cops::gc_ctx, obd_import::imp_dlm_fake, obd_import::imp_obd, LASSERT, obd_device::obd_name, obd_device::obd_type, ptlrpc_sec::ps_gc_interval, ptlrpc_sec::ps_part, ptlrpc_sec::ps_refcount, PTLRPC_SEC_FL_REVERSE, PTLRPC_SEC_FL_ROOTONLY, RETURN, ptlrpc_svc_ctx::sc_policy, sptlrpc_flavor::sf_flags, sptlrpc_flavor::sf_rpc, ptlrpc_sec_policy::sp_cops, sptlrpc_flavor2name(), sptlrpc_gc_add_sec(), sptlrpc_policy_get(), sptlrpc_policy_put(), sptlrpc_wireflavor2policy(), and obd_type::typ_name.
Referenced by sptlrpc_import_sec_adapt().
static void sptlrpc_sec_kill (struct ptlrpc_sec * sec) [static]
Definition at line 1282 of file sec.c.
References ptlrpc_sec_cops::kill_sec, LASSERT_ATOMIC_POS, ptlrpc_sec::ps_policy, ptlrpc_sec::ps_refcount, sec_cop_flush_ctx_cache(), and ptlrpc_sec_policy::sp_cops.
Referenced by sptlrpc_import_sec_install(), and sptlrpc_import_sec_put().
static int sptlrpc_svc_check_from (struct ptlrpc_request * req, int svc_rc) [static]
Definition at line 2017 of file sec.c.
References D_ERROR, DEBUG_REQ, LUSTRE_SP_ANY, LUSTRE_SP_CLI, LUSTRE_SP_MDT, LUSTRE_SP_MGC, LUSTRE_SP_MGS, LUSTRE_SP_OST, ptlrpc_request::rq_auth_gss, ptlrpc_request::rq_auth_usr_mdt, ptlrpc_request::rq_auth_usr_ost, ptlrpc_request::rq_auth_usr_root, and SECSVC_DROP.
Referenced by sptlrpc_svc_unwrap_request().
static struct ptlrpc_sec_policy* sptlrpc_wireflavor2policy (__u32 flavor) [static, read]
Definition at line 117 of file sec.c.
References CDEBUG, CERROR, D_SEC, DEFINE_MUTEX(), policy_lock, ptlrpc_sec_policy::sp_owner, SPTLRPC_FLVR_POLICY, SPTLRPC_POLICY_GSS, and SPTLRPC_POLICY_MAX.
Referenced by sptlrpc_sec_create(), and sptlrpc_svc_unwrap_request().
Variable Documentation
struct ptlrpc_sec_policy* policies[SPTLRPC_POLICY_MAX] [static]
Initial value:
 {
        NULL,
}
Definition at line 66 of file sec.c.
rwlock_t policy_lock [static]
Definition at line 65 of file sec.c.
Referenced by sptlrpc_init(), sptlrpc_register_policy(), sptlrpc_unregister_policy(), and sptlrpc_wireflavor2policy().
atomic_t sptlrpc_sec_id = ATOMIC_INIT(1) [static]
Definition at line 1239 of file sec.c.
Referenced by sptlrpc_get_next_secid().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.