Lustre: lustre/ptlrpc/sec_bulk.c File Reference
lustre/ptlrpc/sec_bulk.c File Reference
#include <libcfs/libcfs.h>
#include <obd.h>
#include <obd_cksum.h>
#include <obd_class.h>
#include <obd_support.h>
#include <lustre_net.h>
#include <lustre_import.h>
#include <lustre_dlm.h>
#include <lustre_sec.h>
#include "ptlrpc_internal.h"
Data Structures
struct ptlrpc_enc_page_pool
Defines
#define DEBUG_SUBSYSTEM S_SEC
#define PTRS_PER_PAGE (PAGE_CACHE_SIZE / sizeof(void *))
#define PAGES_PER_POOL (PTRS_PER_PAGE)
#define IDLE_IDX_MAX (100)
#define IDLE_IDX_WEIGHT (3)
#define CACHE_QUIESCENT_PERIOD (20)
Functions
module_param (enc_pool_max_memory_mb, int, 0644)
MODULE_PARM_DESC (enc_pool_max_memory_mb,"Encoding pool max memory (MB), 1/8 of total physical memory by default")
int sptlrpc_proc_enc_pool_seq_show (struct seq_file *m, void *v)
static void enc_pools_release_free_pages (long npages)
static unsigned long enc_pools_shrink_count (struct shrinker *s, struct shrink_control *sc)
static unsigned long enc_pools_shrink_scan (struct shrinker *s, struct shrink_control *sc)
static int enc_pools_shrink (SHRINKER_ARGS(sc, nr_to_scan, gfp_mask))
static int npages_to_npools (unsigned long npages)
static unsigned long enc_pools_cleanup (struct page ***pools, int npools)
static void enc_pools_insert (struct page ***pools, int npools, int npages)
static int enc_pools_add_pages (int npages)
static void enc_pools_wakeup (void)
static int enc_pools_should_grow (int page_needed, long now)
int get_free_pages_in_pool (void)
int pool_is_at_full_capacity (void)
int sptlrpc_enc_pool_get_pages (struct ptlrpc_bulk_desc *desc)
void sptlrpc_enc_pool_put_pages (struct ptlrpc_bulk_desc *desc)
int sptlrpc_enc_pool_add_user (void)
int sptlrpc_enc_pool_del_user (void)
static void enc_pools_alloc (void)
static void enc_pools_free (void)
int sptlrpc_enc_pool_init (void)
void sptlrpc_enc_pool_fini (void)
const char * sptlrpc_get_hash_name (__u8 hash_alg)
__u8 sptlrpc_get_hash_alg (const char *algname)
int bulk_sec_desc_unpack (struct lustre_msg *msg, int offset, int swabbed)
int sptlrpc_get_bulk_checksum (struct ptlrpc_bulk_desc *desc, __u8 alg, void *buf, int buflen)
Variables
static int mult = 20 - PAGE_CACHE_SHIFT
static int enc_pool_max_memory_mb
static struct ptlrpc_enc_page_pool page_pools
static const int pools_shrinker_seeks = DEFAULT_SEEKS
static struct shrinker * pools_shrinker
static int cfs_hash_alg_id []
Define Documentation
#define CACHE_QUIESCENT_PERIOD (20)
Definition at line 73 of file sec_bulk.c.
Referenced by enc_pools_shrink_count(), and enc_pools_shrink_scan().
#define DEBUG_SUBSYSTEM S_SEC
Definition at line 41 of file sec_bulk.c.
#define IDLE_IDX_MAX (100)
Definition at line 70 of file sec_bulk.c.
Referenced by enc_pools_shrink_count(), enc_pools_shrink_scan(), and sptlrpc_enc_pool_get_pages().
#define IDLE_IDX_WEIGHT (3)
Definition at line 71 of file sec_bulk.c.
Referenced by sptlrpc_enc_pool_get_pages().
#define PAGES_PER_POOL (PTRS_PER_PAGE)
Definition at line 68 of file sec_bulk.c.
Referenced by enc_pools_add_pages(), enc_pools_cleanup(), enc_pools_insert(), enc_pools_release_free_pages(), npages_to_npools(), sptlrpc_enc_pool_get_pages(), sptlrpc_enc_pool_put_pages(), and sptlrpc_proc_enc_pool_seq_show().
#define PTRS_PER_PAGE (PAGE_CACHE_SIZE / sizeof(void *))
Definition at line 67 of file sec_bulk.c.
Function Documentation
static int enc_pools_add_pages (int npages) [static]
Definition at line 427 of file sec_bulk.c.
References CDEBUG, CERROR, D_SEC, DEFINE_MUTEX(), enc_pools_cleanup(), enc_pools_insert(), ptlrpc_enc_page_pool::epp_max_pages, ptlrpc_enc_page_pool::epp_st_grow_fails, ptlrpc_enc_page_pool::epp_st_grows, ptlrpc_enc_page_pool::epp_total_pages, LASSERT, npages_to_npools(), OBD_ALLOC, OBD_FREE, page_pools, PAGES_PER_POOL, and PTLRPC_MAX_BRW_PAGES.
Referenced by sptlrpc_enc_pool_add_user(), and sptlrpc_enc_pool_get_pages().
static void enc_pools_alloc (void) [inline, static]
Definition at line 759 of file sec_bulk.c.
References ptlrpc_enc_page_pool::epp_max_pools, ptlrpc_enc_page_pool::epp_pools, LASSERT, OBD_ALLOC_LARGE, and page_pools.
Referenced by sptlrpc_enc_pool_init().
static unsigned long enc_pools_cleanup (struct page *** pools, int npools) [static]
Definition at line 318 of file sec_bulk.c.
References OBD_FREE, and PAGES_PER_POOL.
Referenced by enc_pools_add_pages(), and sptlrpc_enc_pool_fini().
static void enc_pools_free (void) [inline, static]
Definition at line 767 of file sec_bulk.c.
References ptlrpc_enc_page_pool::epp_max_pools, ptlrpc_enc_page_pool::epp_pools, LASSERT, OBD_FREE_LARGE, and page_pools.
Referenced by sptlrpc_enc_pool_fini(), and sptlrpc_enc_pool_init().
static void enc_pools_insert (struct page *** pools, int npools, int npages) [static]
Definition at line 346 of file sec_bulk.c.
References CDEBUG, D_SEC, ptlrpc_enc_page_pool::epp_free_pages, ptlrpc_enc_page_pool::epp_growing, ptlrpc_enc_page_pool::epp_lock, ptlrpc_enc_page_pool::epp_max_pages, ptlrpc_enc_page_pool::epp_max_pools, ptlrpc_enc_page_pool::epp_pools, ptlrpc_enc_page_pool::epp_st_lowfree, ptlrpc_enc_page_pool::epp_st_max_pages, ptlrpc_enc_page_pool::epp_total_pages, LASSERT, npages_to_npools(), page_pools, and PAGES_PER_POOL.
Referenced by enc_pools_add_pages().
static void enc_pools_release_free_pages (long npages) [static]
Definition at line 186 of file sec_bulk.c.
References ptlrpc_enc_page_pool::epp_free_pages, ptlrpc_enc_page_pool::epp_pools, ptlrpc_enc_page_pool::epp_total_pages, LASSERT, OBD_FREE, page_pools, and PAGES_PER_POOL.
Referenced by enc_pools_shrink_scan().
static int enc_pools_should_grow (int page_needed, long now) [static]
Definition at line 493 of file sec_bulk.c.
References ptlrpc_enc_page_pool::epp_growing, ptlrpc_enc_page_pool::epp_last_shrink, ptlrpc_enc_page_pool::epp_max_pages, ptlrpc_enc_page_pool::epp_total_pages, and page_pools.
Referenced by sptlrpc_enc_pool_get_pages().
static int enc_pools_shrink (SHRINKER_ARGS(sc, nr_to_scan, gfp_mask)) [static]
Definition at line 292 of file sec_bulk.c.
References enc_pools_shrink_count(), enc_pools_shrink_scan(), shrink_control::gfp_mask, shrink_control::nr_to_scan, and shrink_param.
Referenced by sptlrpc_enc_pool_init().
static unsigned long enc_pools_shrink_count (struct shrinker * s, struct shrink_control * sc) [static]
Definition at line 234 of file sec_bulk.c.
References CACHE_QUIESCENT_PERIOD, cfs_time_current_sec(), ptlrpc_enc_page_pool::epp_free_pages, ptlrpc_enc_page_pool::epp_idle_idx, ptlrpc_enc_page_pool::epp_last_access, ptlrpc_enc_page_pool::epp_lock, IDLE_IDX_MAX, LASSERT, max, page_pools, PTLRPC_MAX_BRW_PAGES, and unlikely.
Referenced by enc_pools_shrink(), and sptlrpc_enc_pool_init().
static unsigned long enc_pools_shrink_scan (struct shrinker * s, struct shrink_control * sc) [static]
Definition at line 256 of file sec_bulk.c.
References CACHE_QUIESCENT_PERIOD, CDEBUG, cfs_time_current_sec(), D_SEC, enc_pools_release_free_pages(), ptlrpc_enc_page_pool::epp_free_pages, ptlrpc_enc_page_pool::epp_idle_idx, ptlrpc_enc_page_pool::epp_last_access, ptlrpc_enc_page_pool::epp_last_shrink, ptlrpc_enc_page_pool::epp_lock, ptlrpc_enc_page_pool::epp_st_shrinks, IDLE_IDX_MAX, LASSERT, min_t, shrink_control::nr_to_scan, page_pools, PTLRPC_MAX_BRW_PAGES, and unlikely.
Referenced by enc_pools_shrink(), and sptlrpc_enc_pool_init().
static void enc_pools_wakeup (void) [inline, static]
Definition at line 483 of file sec_bulk.c.
References ptlrpc_enc_page_pool::epp_lock, ptlrpc_enc_page_pool::epp_waitq, ptlrpc_enc_page_pool::epp_waitqlen, LASSERT, page_pools, and unlikely.
Referenced by sptlrpc_enc_pool_add_user(), sptlrpc_enc_pool_get_pages(), and sptlrpc_enc_pool_put_pages().
module_param (enc_pool_max_memory_mb , int , 0644)
MODULE_PARM_DESC (enc_pool_max_memory_mb , "Encoding pool max memory MB, 1/8 of total physical memory by default")
static int npages_to_npools (unsigned long npages) [inline, static]
Definition at line 310 of file sec_bulk.c.
References PAGES_PER_POOL.
Referenced by enc_pools_add_pages(), enc_pools_insert(), sptlrpc_enc_pool_fini(), and sptlrpc_enc_pool_init().
void sptlrpc_enc_pool_fini (void)
Definition at line 827 of file sec_bulk.c.
References CDEBUG, CFS_TIME_T, D_SEC, enc_pools_cleanup(), enc_pools_free(), ptlrpc_enc_page_pool::epp_free_pages, ptlrpc_enc_page_pool::epp_pools, ptlrpc_enc_page_pool::epp_st_access, ptlrpc_enc_page_pool::epp_st_grow_fails, ptlrpc_enc_page_pool::epp_st_grows, ptlrpc_enc_page_pool::epp_st_max_pages, ptlrpc_enc_page_pool::epp_st_max_wait, ptlrpc_enc_page_pool::epp_st_max_wqlen, ptlrpc_enc_page_pool::epp_st_missings, ptlrpc_enc_page_pool::epp_st_outofmem, ptlrpc_enc_page_pool::epp_st_shrinks, ptlrpc_enc_page_pool::epp_total_pages, LASSERT, npages_to_npools(), page_pools, pools_shrinker, and remove_shrinker().
Referenced by sptlrpc_fini(), and sptlrpc_init().
int sptlrpc_enc_pool_init (void)
Definition at line 777 of file sec_bulk.c.
References cfs_time_current_sec(), DEF_SHRINKER_VAR, enc_pool_max_memory_mb, enc_pools_alloc(), enc_pools_free(), enc_pools_shrink(), enc_pools_shrink_count(), enc_pools_shrink_scan(), ptlrpc_enc_page_pool::epp_free_pages, ptlrpc_enc_page_pool::epp_growing, ptlrpc_enc_page_pool::epp_idle_idx, ptlrpc_enc_page_pool::epp_last_access, ptlrpc_enc_page_pool::epp_last_shrink, ptlrpc_enc_page_pool::epp_lock, ptlrpc_enc_page_pool::epp_max_pages, ptlrpc_enc_page_pool::epp_max_pools, ptlrpc_enc_page_pool::epp_pages_short, ptlrpc_enc_page_pool::epp_pools, ptlrpc_enc_page_pool::epp_st_access, ptlrpc_enc_page_pool::epp_st_grow_fails, ptlrpc_enc_page_pool::epp_st_grows, ptlrpc_enc_page_pool::epp_st_lowfree, ptlrpc_enc_page_pool::epp_st_max_pages, ptlrpc_enc_page_pool::epp_st_max_wait, ptlrpc_enc_page_pool::epp_st_max_wqlen, ptlrpc_enc_page_pool::epp_st_missings, ptlrpc_enc_page_pool::epp_st_outofmem, ptlrpc_enc_page_pool::epp_st_shrinks, ptlrpc_enc_page_pool::epp_total_pages, ptlrpc_enc_page_pool::epp_waitq, ptlrpc_enc_page_pool::epp_waitqlen, mult, npages_to_npools(), page_pools, pools_shrinker, pools_shrinker_seeks, and set_shrinker().
Referenced by sptlrpc_init().
int sptlrpc_proc_enc_pool_seq_show (struct seq_file * m, void * v)
Definition at line 139 of file sec_bulk.c.
References cfs_time_current_sec(), CFS_TIME_T, ptlrpc_enc_page_pool::epp_free_pages, ptlrpc_enc_page_pool::epp_idle_idx, ptlrpc_enc_page_pool::epp_last_access, ptlrpc_enc_page_pool::epp_last_shrink, ptlrpc_enc_page_pool::epp_lock, ptlrpc_enc_page_pool::epp_max_pages, ptlrpc_enc_page_pool::epp_max_pools, ptlrpc_enc_page_pool::epp_st_access, ptlrpc_enc_page_pool::epp_st_grow_fails, ptlrpc_enc_page_pool::epp_st_grows, ptlrpc_enc_page_pool::epp_st_lowfree, ptlrpc_enc_page_pool::epp_st_max_pages, ptlrpc_enc_page_pool::epp_st_max_wait, ptlrpc_enc_page_pool::epp_st_max_wqlen, ptlrpc_enc_page_pool::epp_st_missings, ptlrpc_enc_page_pool::epp_st_outofmem, ptlrpc_enc_page_pool::epp_st_shrinks, ptlrpc_enc_page_pool::epp_total_pages, page_pools, and PAGES_PER_POOL.
Variable Documentation
int cfs_hash_alg_id[] [static]
Initial value:
 {
        [BULK_HASH_ALG_NULL]    = CFS_HASH_ALG_NULL,
        [BULK_HASH_ALG_ADLER32] = CFS_HASH_ALG_ADLER32,
        [BULK_HASH_ALG_CRC32]   = CFS_HASH_ALG_CRC32,
        [BULK_HASH_ALG_MD5]     = CFS_HASH_ALG_MD5,
        [BULK_HASH_ALG_SHA1]    = CFS_HASH_ALG_SHA1,
        [BULK_HASH_ALG_SHA256]  = CFS_HASH_ALG_SHA256,
        [BULK_HASH_ALG_SHA384]  = CFS_HASH_ALG_SHA384,
        [BULK_HASH_ALG_SHA512]  = CFS_HASH_ALG_SHA512,
}
Definition at line 859 of file sec_bulk.c.
int enc_pool_max_memory_mb [static]
Definition at line 57 of file sec_bulk.c.
Referenced by sptlrpc_enc_pool_init().
int mult = 20 - PAGE_CACHE_SHIFT [static]
Definition at line 56 of file sec_bulk.c.
Referenced by sptlrpc_enc_pool_init().
struct ptlrpc_enc_page_pool page_pools [static]
Referenced by enc_pools_add_pages(), enc_pools_alloc(), enc_pools_free(), enc_pools_insert(), enc_pools_release_free_pages(), enc_pools_should_grow(), enc_pools_shrink_count(), enc_pools_shrink_scan(), enc_pools_wakeup(), get_free_pages_in_pool(), pool_is_at_full_capacity(), sptlrpc_enc_pool_add_user(), sptlrpc_enc_pool_fini(), sptlrpc_enc_pool_get_pages(), sptlrpc_enc_pool_init(), sptlrpc_enc_pool_put_pages(), and sptlrpc_proc_enc_pool_seq_show().
struct shrinker* pools_shrinker [static]
Definition at line 133 of file sec_bulk.c.
Referenced by sptlrpc_enc_pool_fini(), and sptlrpc_enc_pool_init().
const int pools_shrinker_seeks = DEFAULT_SEEKS [static]
Definition at line 132 of file sec_bulk.c.
Referenced by sptlrpc_enc_pool_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.