Lustre: lustre/ptlrpc/gss/sec_gss.c File Reference
lustre/ptlrpc/gss/sec_gss.c File Reference
#include <linux/init.h>
#include <linux/module.h>
#include <linux/slab.h>
#include <linux/dcache.h>
#include <linux/fs.h>
#include <linux/mutex.h>
#include <asm/atomic.h>
#include <obd.h>
#include <obd_class.h>
#include <obd_support.h>
#include <obd_cksum.h>
#include <lustre/lustre_idl.h>
#include <lustre_net.h>
#include <lustre_import.h>
#include <lustre_sec.h>
#include "gss_err.h"
#include "gss_internal.h"
#include "gss_api.h"
#include <linux/crypto.h>
#include <linux/crc32.h>
Defines
#define DEBUG_SUBSYSTEM S_SEC
#define GSS_KRB5_INTEG_MAX_PAYLOAD (40)
Functions
static int msg_last_segidx (struct lustre_msg *msg)
static int msg_last_seglen (struct lustre_msg *msg)
static void gss_header_swabber (struct gss_header *ghdr)
struct gss_header * gss_swab_header (struct lustre_msg *msg, int segment, int swabbed)
static int gss_mech_payload (struct gss_ctx *mechctx, int msgsize, int privacy)
static int gss_sign_msg (struct lustre_msg *msg, struct gss_ctx *mechctx, enum lustre_sec_part sp, __u32 flags, __u32 proc, __u32 seq, __u32 svc, rawobj_t *handle)
static __u32 gss_verify_msg (struct lustre_msg *msg, struct gss_ctx *mechctx, __u32 svc)
static __u32 gss_unseal_msg (struct gss_ctx *mechctx, struct lustre_msg *msgbuf, int *msg_len, int msgbuf_len)
int cli_ctx_expire (struct ptlrpc_cli_ctx *ctx)
int cli_ctx_check_death (struct ptlrpc_cli_ctx *ctx)
void gss_cli_ctx_uptodate (struct gss_cli_ctx *gctx)
static void gss_cli_ctx_finalize (struct gss_cli_ctx *gctx)
static int gss_do_check_seq (unsigned long *window, __u32 win_size, __u32 *max_seq, __u32 seq_num, int phase)
Based on sequence number algorithm as specified in RFC 2203.
int gss_check_seq_num (struct gss_svc_seq_data *ssd, __u32 seq_num, int set)
static int gss_cli_payload (struct ptlrpc_cli_ctx *ctx, int msgsize, int privacy)
static int gss_cli_bulk_payload (struct ptlrpc_cli_ctx *ctx, struct sptlrpc_flavor *flvr, int reply, int read)
int gss_cli_ctx_match (struct ptlrpc_cli_ctx *ctx, struct vfs_cred *vcred)
void gss_cli_ctx_flags2str (unsigned long flags, char *buf, int bufsize)
int gss_cli_ctx_sign (struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req)
static int gss_cli_ctx_handle_err_notify (struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req, struct gss_header *ghdr)
int gss_cli_ctx_verify (struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req)
int gss_cli_ctx_seal (struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req)
int gss_cli_ctx_unseal (struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req)
static int gss_install_rvs_svc_ctx (struct obd_import *imp, struct gss_sec *gsec, struct gss_cli_ctx *gctx)
int gss_sec_create_common (struct gss_sec *gsec, struct ptlrpc_sec_policy *policy, struct obd_import *imp, struct ptlrpc_svc_ctx *svcctx, struct sptlrpc_flavor *sf)
void gss_sec_destroy_common (struct gss_sec *gsec)
void gss_sec_kill (struct ptlrpc_sec *sec)
int gss_cli_ctx_init_common (struct ptlrpc_sec *sec, struct ptlrpc_cli_ctx *ctx, struct ptlrpc_ctx_ops *ctxops, struct vfs_cred *vcred)
int gss_cli_ctx_fini_common (struct ptlrpc_sec *sec, struct ptlrpc_cli_ctx *ctx)
static int gss_alloc_reqbuf_intg (struct ptlrpc_sec *sec, struct ptlrpc_request *req, int svc, int msgsize)
static int gss_alloc_reqbuf_priv (struct ptlrpc_sec *sec, struct ptlrpc_request *req, int msgsize)
int gss_alloc_reqbuf (struct ptlrpc_sec *sec, struct ptlrpc_request *req, int msgsize)
void gss_free_reqbuf (struct ptlrpc_sec *sec, struct ptlrpc_request *req)
static int do_alloc_repbuf (struct ptlrpc_request *req, int bufsize)
static int gss_alloc_repbuf_intg (struct ptlrpc_sec *sec, struct ptlrpc_request *req, int svc, int msgsize)
static int gss_alloc_repbuf_priv (struct ptlrpc_sec *sec, struct ptlrpc_request *req, int msgsize)
int gss_alloc_repbuf (struct ptlrpc_sec *sec, struct ptlrpc_request *req, int msgsize)
void gss_free_repbuf (struct ptlrpc_sec *sec, struct ptlrpc_request *req)
static int get_enlarged_msgsize (struct lustre_msg *msg, int segment, int newsize)
static int get_enlarged_msgsize2 (struct lustre_msg *msg, int segment1, int newsize1, int segment2, int newsize2)
static int gss_enlarge_reqbuf_intg (struct ptlrpc_sec *sec, struct ptlrpc_request *req, int svc, int segment, int newsize)
static int gss_enlarge_reqbuf_priv (struct ptlrpc_sec *sec, struct ptlrpc_request *req, int segment, int newsize)
int gss_enlarge_reqbuf (struct ptlrpc_sec *sec, struct ptlrpc_request *req, int segment, int newsize)
int gss_sec_install_rctx (struct obd_import *imp, struct ptlrpc_sec *sec, struct ptlrpc_cli_ctx *ctx)
static int gss_svc_reqctx_is_special (struct gss_svc_reqctx *grctx)
static void gss_svc_reqctx_free (struct gss_svc_reqctx *grctx)
static void gss_svc_reqctx_addref (struct gss_svc_reqctx *grctx)
static void gss_svc_reqctx_decref (struct gss_svc_reqctx *grctx)
static int gss_svc_sign (struct ptlrpc_request *req, struct ptlrpc_reply_state *rs, struct gss_svc_reqctx *grctx, __u32 svc)
int gss_pack_err_notify (struct ptlrpc_request *req, __u32 major, __u32 minor)
static int gss_svc_handle_init (struct ptlrpc_request *req, struct gss_wire_ctx *gw)
static int gss_svc_verify_request (struct ptlrpc_request *req, struct gss_svc_reqctx *grctx, struct gss_wire_ctx *gw, __u32 *major)
static int gss_svc_unseal_request (struct ptlrpc_request *req, struct gss_svc_reqctx *grctx, struct gss_wire_ctx *gw, __u32 *major)
static int gss_svc_handle_data (struct ptlrpc_request *req, struct gss_wire_ctx *gw)
static int gss_svc_handle_destroy (struct ptlrpc_request *req, struct gss_wire_ctx *gw)
int gss_svc_accept (struct ptlrpc_sec_policy *policy, struct ptlrpc_request *req)
void gss_svc_invalidate_ctx (struct ptlrpc_svc_ctx *svc_ctx)
static int gss_svc_payload (struct gss_svc_reqctx *grctx, int early, int msgsize, int privacy)
static int gss_svc_bulk_payload (struct gss_svc_ctx *gctx, struct sptlrpc_flavor *flvr, int read)
int gss_svc_alloc_rs (struct ptlrpc_request *req, int msglen)
static int gss_svc_seal (struct ptlrpc_request *req, struct ptlrpc_reply_state *rs, struct gss_svc_reqctx *grctx)
int gss_svc_authorize (struct ptlrpc_request *req)
void gss_svc_free_rs (struct ptlrpc_reply_state *rs)
void gss_svc_free_ctx (struct ptlrpc_svc_ctx *ctx)
int gss_copy_rvc_cli_ctx (struct ptlrpc_cli_ctx *cli_ctx, struct ptlrpc_svc_ctx *svc_ctx)
static void gss_init_at_reply_offset (void)
static int __init sptlrpc_gss_init (void)
static void __exit sptlrpc_gss_exit (void)
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre GSS security policy")
MODULE_VERSION (LUSTRE_VERSION_STRING)
MODULE_LICENSE ("GPL")
module_init (sptlrpc_gss_init)
module_exit (sptlrpc_gss_exit)
Variables
static int gss_at_reply_off_integ
static int gss_at_reply_off_priv
Define Documentation
#define DEBUG_SUBSYSTEM S_SEC
Definition at line 49 of file sec_gss.c.
#define GSS_KRB5_INTEG_MAX_PAYLOAD (40)
Definition at line 163 of file sec_gss.c.
Referenced by gss_mech_payload().
Function Documentation
int cli_ctx_check_death (struct ptlrpc_cli_ctx * ctx)
Definition at line 351 of file sec_gss.c.
References ptlrpc_cli_ctx::cc_expire, cfs_time_after(), cfs_time_current_sec(), cli_ctx_expire(), cli_ctx_is_dead(), and unlikely.
Referenced by ctx_check_death_pf(), gss_cli_ctx_validate_kr(), and gss_sec_gc_ctx_kr().
int cli_ctx_expire (struct ptlrpc_cli_ctx * ctx)
Definition at line 327 of file sec_gss.c.
References ptlrpc_cli_ctx::cc_early_expire, ptlrpc_cli_ctx::cc_expire, ptlrpc_cli_ctx::cc_flags, ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_sec, ptlrpc_cli_ctx::cc_vcred, cfs_time_current_sec(), cfs_time_sub(), CWARN, LASSERT, PTLRPC_CTX_DEAD_BIT, PTLRPC_CTX_UPTODATE_BIT, sec2target_str(), sptlrpc_cli_ctx_wakeup(), and vfs_cred::vc_uid.
Referenced by cli_ctx_check_death(), ctx_upcall_timeout_kr(), gss_cli_ctx_die_kr(), gss_cli_ctx_die_pf(), gss_kt_update(), and gss_sec_ctx_replace_pf().
static int do_alloc_repbuf (struct ptlrpc_request * req, int bufsize) [static]
Definition at line 1475 of file sec_gss.c.
References OBD_ALLOC_LARGE, ptlrpc_request::rq_repbuf, ptlrpc_request::rq_repbuf_len, and size_roundup_power2().
Referenced by gss_alloc_repbuf_intg(), and gss_alloc_repbuf_priv().
static int get_enlarged_msgsize (struct lustre_msg * msg, int segment, int newsize) [static]
Definition at line 1606 of file sec_gss.c.
References LASSERT, and lustre_msg_size_v2().
Referenced by gss_enlarge_reqbuf_intg(), and gss_enlarge_reqbuf_priv().
static int get_enlarged_msgsize2 (struct lustre_msg * msg, int segment1, int newsize1, int segment2, int newsize2) [static]
Definition at line 1621 of file sec_gss.c.
References LASSERT, and lustre_msg_size_v2().
Referenced by gss_enlarge_reqbuf_intg().
int gss_alloc_repbuf (struct ptlrpc_sec * sec, struct ptlrpc_request * req, int msgsize)
Definition at line 1573 of file sec_gss.c.
References ENTRY, gss_alloc_repbuf_intg(), gss_alloc_repbuf_priv(), LASSERT, LASSERTF, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pack_bulk, sptlrpc_flavor::sf_rpc, SPTLRPC_FLVR_SVC, SPTLRPC_SVC_AUTH, SPTLRPC_SVC_INTG, SPTLRPC_SVC_NULL, and SPTLRPC_SVC_PRIV.
static int gss_alloc_repbuf_intg (struct ptlrpc_sec * sec, struct ptlrpc_request * req, int svc, int msgsize) [static]
Definition at line 1488 of file sec_gss.c.
References do_alloc_repbuf(), gss_at_reply_off_integ, gss_cli_bulk_payload(), gss_cli_payload(), GSS_CTX_INIT_MAX_LEN, lustre_msg_size_v2(), PTLRPC_GSS_HEADER_SIZE, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_ctx_init, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pack_bulk, SPTLRPC_SVC_INTG, and SPTLRPC_SVC_NULL.
Referenced by gss_alloc_repbuf().
static int gss_alloc_repbuf_priv (struct ptlrpc_sec * sec, struct ptlrpc_request * req, int msgsize) [static]
Definition at line 1541 of file sec_gss.c.
References do_alloc_repbuf(), gss_at_reply_off_priv, gss_cli_bulk_payload(), gss_cli_payload(), GSS_MAX_CIPHER_BLOCK, lustre_msg_size_v2(), PTLRPC_GSS_HEADER_SIZE, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_flvr, and ptlrpc_request::rq_pack_bulk.
Referenced by gss_alloc_repbuf().
int gss_alloc_reqbuf (struct ptlrpc_sec * sec, struct ptlrpc_request * req, int msgsize)
Definition at line 1416 of file sec_gss.c.
References gss_alloc_reqbuf_intg(), gss_alloc_reqbuf_priv(), LASSERT, LASSERTF, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pack_bulk, sptlrpc_flavor::sf_rpc, SPTLRPC_FLVR_SVC, SPTLRPC_SVC_AUTH, SPTLRPC_SVC_INTG, SPTLRPC_SVC_NULL, and SPTLRPC_SVC_PRIV.
static int gss_alloc_reqbuf_intg (struct ptlrpc_sec * sec, struct ptlrpc_request * req, int svc, int msgsize) [static]
Definition at line 1253 of file sec_gss.c.
References bufsize, ENTRY, gss_cli_bulk_payload(), gss_cli_payload(), GSS_CTX_INIT_MAX_LEN, LASSERT, lustre_init_msg_v2(), lustre_msg_buf(), lustre_msg_size_v2(), OBD_ALLOC_LARGE, PTLRPC_GSS_HEADER_SIZE, RETURN, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_ctx_init, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_pack_udesc, ptlrpc_request::rq_pool, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqbuf_len, ptlrpc_request::rq_reqmsg, sptlrpc_flavor::sf_rpc, size_roundup_power2(), sptlrpc_current_user_desc_size(), sptlrpc_pack_user_desc(), SPTLRPC_SVC_INTG, and SPTLRPC_SVC_NULL.
Referenced by gss_alloc_reqbuf().
static int gss_alloc_reqbuf_priv (struct ptlrpc_sec * sec, struct ptlrpc_request * req, int msgsize) [static]
Definition at line 1335 of file sec_gss.c.
References CWARN, ENTRY, gss_cli_bulk_payload(), gss_cli_payload(), GSS_MAX_CIPHER_BLOCK, LASSERT, lustre_init_msg_v2(), lustre_msg_buf(), lustre_msg_size_v2(), OBD_ALLOC_LARGE, PTLRPC_GSS_HEADER_SIZE, RETURN, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_clrbuf, ptlrpc_request::rq_clrbuf_len, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_pack_udesc, ptlrpc_request::rq_pool, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqbuf_len, ptlrpc_request::rq_reqmsg, size_roundup_power2(), sptlrpc_current_user_desc_size(), and sptlrpc_pack_user_desc().
Referenced by gss_alloc_reqbuf().
int gss_check_seq_num (struct gss_svc_seq_data * ssd, __u32 seq_num, int set)
Definition at line 536 of file sec_gss.c.
References gss_do_check_seq(), GSS_SEQ_WIN_BACK, GSS_SEQ_WIN_MAIN, gss_stat_oos_record_svc(), gss_svc_seq_data::ssd_lock, gss_svc_seq_data::ssd_max_back, gss_svc_seq_data::ssd_max_main, gss_svc_seq_data::ssd_win_back, gss_svc_seq_data::ssd_win_main, and unlikely.
Referenced by gss_svc_unseal_request(), and gss_svc_verify_request().
static int gss_cli_bulk_payload (struct ptlrpc_cli_ctx * ctx, struct sptlrpc_flavor * flvr, int reply, int read) [static]
Definition at line 588 of file sec_gss.c.
References gss_cli_payload(), LASSERT, LBUG, sptlrpc_flavor::sf_rpc, SPTLRPC_BULK_DEFAULT, SPTLRPC_BULK_SVC_AUTH, SPTLRPC_BULK_SVC_INTG, SPTLRPC_BULK_SVC_NULL, SPTLRPC_BULK_SVC_PRIV, SPTLRPC_FLVR_BULK_SVC, and SPTLRPC_FLVR_BULK_TYPE.
Referenced by gss_alloc_repbuf_intg(), gss_alloc_repbuf_priv(), gss_alloc_reqbuf_intg(), and gss_alloc_reqbuf_priv().
static void gss_cli_ctx_finalize (struct gss_cli_ctx * gctx) [static]
Definition at line 410 of file sec_gss.c.
References ptlrpc_cli_ctx::cc_sec, gss_cli_ctx::gc_base, gss_cli_ctx::gc_handle, gss_cli_ctx::gc_mechctx, gss_cli_ctx::gc_svc_handle, gss_svc_upcall_expire_rvs_ctx(), LASSERT, lgss_delete_sec_context(), rawobj_empty(), rawobj_free(), and sec_is_reverse().
Referenced by gss_cli_ctx_fini_common().
int gss_cli_ctx_fini_common (struct ptlrpc_sec * sec, struct ptlrpc_cli_ctx * ctx)
Definition at line 1209 of file sec_gss.c.
References ptlrpc_cli_ctx::cc_flags, ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_sec, ptlrpc_cli_ctx::cc_vcred, ctx2gctx(), CWARN, gss_cli_ctx::gc_mechctx, gss_cli_ctx_finalize(), gss_do_ctx_fini_rpc(), LASSERT, ptlrpc_sec::ps_nctx, ptlrpc_sec::ps_policy, PTLRPC_CTX_UPTODATE, sec2target_str(), sec_is_reverse(), ptlrpc_sec_policy::sp_name, and vfs_cred::vc_uid.
Referenced by ctx_destroy_kr(), and ctx_destroy_pf().
void gss_cli_ctx_flags2str (unsigned long flags, char * buf, int bufsize)
Definition at line 620 of file sec_gss.c.
References PTLRPC_CTX_CACHED, PTLRPC_CTX_DEAD, PTLRPC_CTX_ERROR, PTLRPC_CTX_ETERNAL, PTLRPC_CTX_NEW, PTLRPC_CTX_UPTODATE, and strlcat().
Referenced by gss_sec_display_kr().
static int gss_cli_ctx_handle_err_notify (struct ptlrpc_cli_ctx * ctx, struct ptlrpc_request * req, struct gss_header * ghdr) [static]
Definition at line 693 of file sec_gss.c.
References ptlrpc_cli_ctx::cc_sec, ptlrpc_cli_ctx::cc_vcred, ctx2gctx(), CWARN, gss_err_header::gh_major, gss_err_header::gh_minor, gss_header::gh_proc, gss_handle_to_u64(), GSS_S_BAD_SIG, GSS_S_NO_CONTEXT, LASSERT, LPU64, LPX64, PTLRPC_GSS_PROC_ERR, ptlrpc_request::rq_ctx_fini, ptlrpc_request::rq_resend, ptlrpc_request::rq_transno, ptlrpc_request::rq_xid, sec2target_str(), sec_is_reverse(), sptlrpc_cli_ctx_expire(), sptlrpc_req_replace_dead_ctx(), and vfs_cred::vc_uid.
Referenced by gss_cli_ctx_unseal(), and gss_cli_ctx_verify().
int gss_cli_ctx_init_common (struct ptlrpc_sec * sec, struct ptlrpc_cli_ctx * ctx, struct ptlrpc_ctx_ops * ctxops, struct vfs_cred * vcred)
Definition at line 1172 of file sec_gss.c.
References ptlrpc_cli_ctx::cc_cache, ptlrpc_cli_ctx::cc_expire, ptlrpc_cli_ctx::cc_flags, ptlrpc_cli_ctx::cc_gc_chain, ptlrpc_cli_ctx::cc_lock, ptlrpc_cli_ctx::cc_ops, ptlrpc_cli_ctx::cc_refcount, ptlrpc_cli_ctx::cc_req_list, ptlrpc_cli_ctx::cc_sec, ptlrpc_cli_ctx::cc_vcred, CDEBUG, ctx2gctx(), D_SEC, gss_cli_ctx::gc_seq, gss_cli_ctx::gc_win, INIT_HLIST_NODE, INIT_LIST_HEAD, ptlrpc_sec::ps_nctx, ptlrpc_sec::ps_policy, ptlrpc_sec::ps_refcount, PTLRPC_CTX_NEW, sec2target_str(), ptlrpc_sec_policy::sp_name, and vfs_cred::vc_uid.
Referenced by ctx_create_kr(), and ctx_create_pf().
int gss_cli_ctx_match (struct ptlrpc_cli_ctx * ctx, struct vfs_cred * vcred)
Definition at line 615 of file sec_gss.c.
References ptlrpc_cli_ctx::cc_vcred, and vfs_cred::vc_uid.
int gss_cli_ctx_seal (struct ptlrpc_cli_ctx * ctx, struct ptlrpc_request * req)
Definition at line 881 of file sec_gss.c.
References ptlrpc_cli_ctx::cc_sec, CERROR, CWARN, rawobj_s::data, netobj_s::data, ENTRY, gss_cli_ctx::gc_base, gss_cli_ctx::gc_handle, gss_cli_ctx::gc_mechctx, gss_cli_ctx::gc_proc, gss_cli_ctx::gc_seq, gss_header::gh_flags, gss_header::gh_handle, gss_header::gh_proc, gss_header::gh_seq, gss_header::gh_sp, gss_header::gh_svc, gss_header::gh_version, GOTO, gss_cli_payload(), GSS_S_COMPLETE, GSS_SEQ_REPACK_THRESHOLD, gss_stat_oos_record_cli(), LASSERT, rawobj_s::len, netobj_s::len, lgss_wrap(), LUSTRE_GSS_PACK_BULK, LUSTRE_GSS_PACK_USER, lustre_init_msg_v2(), lustre_msg_buf(), lustre_msg_buflen(), lustre_msg_size_v2(), lustre_shrink_msg(), OBD_ALLOC_LARGE, OBD_FREE_LARGE, ptlrpc_sec::ps_part, PTLRPC_GSS_HEADER_SIZE, PTLRPC_GSS_VERSION, RETURN, ptlrpc_request::rq_clrbuf, ptlrpc_request::rq_clrbuf_len, ptlrpc_request::rq_clrdata_len, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_pack_udesc, ptlrpc_request::rq_pool, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqbuf_len, ptlrpc_request::rq_reqdata_len, ptlrpc_request::rq_reqlen, sptlrpc_flavor::sf_rpc, SPTLRPC_SVC_PRIV, and unlikely.
int gss_cli_ctx_sign (struct ptlrpc_cli_ctx * ctx, struct ptlrpc_request * req)
Definition at line 640 of file sec_gss.c.
References ptlrpc_cli_ctx::cc_sec, ctx2gctx(), CWARN, ENTRY, gss_cli_ctx::gc_handle, gss_cli_ctx::gc_mechctx, gss_cli_ctx::gc_proc, gss_cli_ctx::gc_seq, GSS_SEQ_REPACK_THRESHOLD, gss_sign_msg(), gss_stat_oos_record_cli(), LASSERT, LUSTRE_GSS_PACK_BULK, LUSTRE_GSS_PACK_USER, ptlrpc_sec::ps_part, RETURN, ptlrpc_request::rq_ctx_init, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_pack_udesc, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqdata_len, sptlrpc_flavor::sf_rpc, SPTLRPC_FLVR_SVC, and SPTLRPC_SVC_NULL.
int gss_cli_ctx_unseal (struct ptlrpc_cli_ctx * ctx, struct ptlrpc_request * req)
Definition at line 980 of file sec_gss.c.
References __lustre_unpack_msg(), bulk_sec_desc_unpack(), CERROR, ENTRY, equi, gss_cli_ctx::gc_mechctx, gss_header::gh_flags, gss_header::gh_proc, gss_header::gh_version, gss_cli_ctx_handle_err_notify(), gss_header_swabber(), GSS_S_COMPLETE, gss_swab_header(), gss_unseal_msg(), LASSERT, LUSTRE_GSS_PACK_BULK, lustre_msg, lustre_msg_buf(), PTLRPC_GSS_PROC_DATA, PTLRPC_GSS_PROC_ERR, PTLRPC_GSS_VERSION, ptlrpc_rep_need_swab(), RETURN, ptlrpc_request::rq_ctx_init, ptlrpc_request::rq_early, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_repdata, ptlrpc_request::rq_repdata_len, ptlrpc_request::rq_replen, and ptlrpc_request::rq_repmsg.
void gss_cli_ctx_uptodate (struct gss_cli_ctx * gctx)
Definition at line 369 of file sec_gss.c.
References ptlrpc_cli_ctx::cc_expire, ptlrpc_cli_ctx::cc_flags, ptlrpc_cli_ctx::cc_sec, ptlrpc_cli_ctx::cc_vcred, CERROR, cfs_time_current_sec(), CWARN, gss_cli_ctx::gc_base, gss_cli_ctx::gc_handle, gss_cli_ctx::gc_mechctx, gss_handle_to_u64(), gss_round_ctx_expiry(), gss_sec_install_rctx(), lgss_inquire_context(), LPX64, ptlrpc_sec::ps_flvr, ptlrpc_sec::ps_import, PTLRPC_CTX_UPTODATE_BIT, sec2target_str(), sec_is_reverse(), sptlrpc_flavor::sf_flags, sptlrpc_cli_ctx_wakeup(), and vfs_cred::vc_uid.
Referenced by gss_copy_rvc_cli_ctx(), gss_kt_update(), and gss_pipe_downcall().
int gss_cli_ctx_verify (struct ptlrpc_cli_ctx * ctx, struct ptlrpc_request * req)
Definition at line 757 of file sec_gss.c.
References bulk_sec_desc_unpack(), CERROR, cksum, CWARN, ENTRY, equi, gss_cli_ctx::gc_mechctx, gss_header::gh_flags, gss_header::gh_proc, gss_header::gh_seq, gss_header::gh_svc, gss_header::gh_version, gss_cli_ctx_handle_err_notify(), gss_header_swabber(), GSS_S_COMPLETE, gss_swab_header(), gss_verify_msg(), LASSERT, LUSTRE_GSS_PACK_BULK, lustre_msg, lustre_msg_buf(), lustre_msg_buflen(), PTLRPC_GSS_PROC_DATA, PTLRPC_GSS_PROC_ERR, ptlrpc_rep_need_swab(), RETURN, ptlrpc_request::rq_ctx_init, ptlrpc_request::rq_early, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_repdata, ptlrpc_request::rq_replen, ptlrpc_request::rq_repmsg, and SPTLRPC_SVC_NULL.
static int gss_cli_payload (struct ptlrpc_cli_ctx * ctx, int msgsize, int privacy) [inline, static]
Definition at line 582 of file sec_gss.c.
References gss_mech_payload().
Referenced by gss_alloc_repbuf_intg(), gss_alloc_repbuf_priv(), gss_alloc_reqbuf_intg(), gss_alloc_reqbuf_priv(), gss_cli_bulk_payload(), gss_cli_ctx_seal(), gss_enlarge_reqbuf_intg(), gss_enlarge_reqbuf_priv(), and gss_init_at_reply_offset().
int gss_copy_rvc_cli_ctx (struct ptlrpc_cli_ctx * cli_ctx, struct ptlrpc_svc_ctx * svc_ctx)
Definition at line 2801 of file sec_gss.c.
References CERROR, ctx2gctx(), gss_cli_ctx::gc_handle, gss_cli_ctx::gc_mechctx, gss_cli_ctx::gc_proc, gss_cli_ctx::gc_seq, gss_cli_ctx::gc_svc_handle, gss_cli_ctx::gc_win, gss_svc_ctx::gsc_mechctx, gss_svc_ctx::gsc_rvs_hdl, gss_svc_ctx::gsc_rvs_seq, gss_cli_ctx_uptodate(), GSS_S_COMPLETE, GSS_SEQ_WIN, gss_svc_ctx2gssctx(), gss_svc_upcall_dup_handle(), LASSERT, lgss_copy_reverse_context(), lgss_delete_sec_context(), PTLRPC_GSS_PROC_DATA, rawobj_dup(), and rawobj_free().
Referenced by gss_install_rvs_cli_ctx_pf(), and sec_install_rctx_kr().
static int gss_do_check_seq (unsigned long * window, __u32 win_size, __u32 * max_seq, __u32 seq_num, int phase) [static]
Based on sequence number algorithm as specified in RFC 2203.
Modified for our own problem: arriving request has valid sequence number, but unwrapping request might cost a long time, after that its sequence are not valid anymore (fall behind the window). It rarely happen, mostly under extreme load.
Note we should not check sequence before verifying the integrity of incoming request, because just one attacking request with high sequence number might cause all following requests be dropped.
So here we use a multi-phase approach: prepare 2 sequence windows, "main window" for normal sequence and "back window" for fall behind sequence. and 3-phase checking mechanism: 0 - before integrity verification, perform an initial sequence checking in main window, which only tries and doesn't actually set any bits. if the sequence is high above the window or fits in the window and the bit is 0, then accept and proceed to integrity verification. otherwise reject this sequence. 1 - after integrity verification, check in main window again. if this sequence is high above the window or fits in the window and the bit is 0, then set the bit and accept; if it fits in the window but bit already set, then reject; if it falls behind the window, then proceed to phase 2. 2 - check in back window. if it is high above the window or fits in the window and the bit is 0, then set the bit and accept. otherwise reject.
Returns:
1: looks like a replay
0: is ok
-1: is a replay
Note phase 0 is necessary, because otherwise replay attacking request of sequence which between the 2 windows can't be detected.
This mechanism can't totally solve the problem, but could help reduce the number of valid requests be dropped.
Definition at line 470 of file sec_gss.c.
References CERROR, CWARN, and LASSERT.
Referenced by gss_check_seq_num().
int gss_enlarge_reqbuf (struct ptlrpc_sec * sec, struct ptlrpc_request * req, int segment, int newsize)
Definition at line 1838 of file sec_gss.c.
References gss_enlarge_reqbuf_intg(), gss_enlarge_reqbuf_priv(), LASSERT, LASSERTF, ptlrpc_request::rq_ctx_fini, ptlrpc_request::rq_ctx_init, ptlrpc_request::rq_flvr, sptlrpc_flavor::sf_rpc, SPTLRPC_FLVR_SVC, SPTLRPC_SVC_AUTH, SPTLRPC_SVC_INTG, SPTLRPC_SVC_NULL, and SPTLRPC_SVC_PRIV.
static int gss_enlarge_reqbuf_intg (struct ptlrpc_sec * sec, struct ptlrpc_request * req, int svc, int segment, int newsize) [static]
Definition at line 1642 of file sec_gss.c.
References _sptlrpc_enlarge_msg_inplace(), get_enlarged_msgsize(), get_enlarged_msgsize2(), gss_cli_payload(), obd_import::imp_lock, LASSERT, lustre_msg, lustre_msg_buf(), msg_last_segidx(), msg_last_seglen(), OBD_ALLOC_LARGE, OBD_FREE_LARGE, RETURN, ptlrpc_request::rq_import, ptlrpc_request::rq_pool, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqbuf_len, ptlrpc_request::rq_reqlen, ptlrpc_request::rq_reqmsg, size_roundup_power2(), SPTLRPC_SVC_INTG, and SPTLRPC_SVC_NULL.
Referenced by gss_enlarge_reqbuf().
static int gss_enlarge_reqbuf_priv (struct ptlrpc_sec * sec, struct ptlrpc_request * req, int segment, int newsize) [static]
Definition at line 1733 of file sec_gss.c.
References _sptlrpc_enlarge_msg_inplace(), get_enlarged_msgsize(), gss_cli_payload(), GSS_MAX_CIPHER_BLOCK, obd_import::imp_lock, LASSERT, lustre_msg, lustre_msg_buf(), lustre_msg_size_v2(), OBD_ALLOC_LARGE, OBD_FREE_LARGE, PTLRPC_GSS_HEADER_SIZE, RETURN, ptlrpc_request::rq_clrbuf, ptlrpc_request::rq_clrbuf_len, ptlrpc_request::rq_import, ptlrpc_request::rq_pool, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqbuf_len, ptlrpc_request::rq_reqlen, ptlrpc_request::rq_reqmsg, size_roundup_power2(), and unlikely.
Referenced by gss_enlarge_reqbuf().
void gss_free_repbuf (struct ptlrpc_sec * sec, struct ptlrpc_request * req)
Definition at line 1596 of file sec_gss.c.
References OBD_FREE_LARGE, ptlrpc_request::rq_repbuf, ptlrpc_request::rq_repbuf_len, ptlrpc_request::rq_repdata, and ptlrpc_request::rq_repdata_len.
void gss_free_reqbuf (struct ptlrpc_sec * sec, struct ptlrpc_request * req)
Definition at line 1438 of file sec_gss.c.
References ENTRY, EXIT, LASSERT, OBD_FREE_LARGE, ptlrpc_request::rq_clrbuf, ptlrpc_request::rq_clrbuf_len, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pool, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqbuf_len, sptlrpc_flavor::sf_rpc, SPTLRPC_FLVR_SVC, and SPTLRPC_SVC_PRIV.
static void gss_header_swabber (struct gss_header * ghdr) [static]
Definition at line 97 of file sec_gss.c.
References __swab32s, gss_header::gh_flags, gss_header::gh_handle, gss_header::gh_pad1, gss_header::gh_proc, gss_header::gh_seq, gss_header::gh_svc, and netobj_s::len.
Referenced by gss_cli_ctx_unseal(), gss_cli_ctx_verify(), gss_svc_accept(), and gss_swab_header().
static void gss_init_at_reply_offset (void) [static]
Definition at line 2854 of file sec_gss.c.
References gss_at_reply_off_integ, gss_at_reply_off_priv, gss_cli_payload(), lustre_msg_early_size(), lustre_msg_size_v2(), and PTLRPC_GSS_HEADER_SIZE.
Referenced by sptlrpc_gss_init().
static int gss_install_rvs_svc_ctx (struct obd_import * imp, struct gss_sec * gsec, struct gss_cli_ctx * gctx) [inline, static]
Definition at line 1085 of file sec_gss.c.
References gss_svc_upcall_install_rvs_ctx().
Referenced by gss_sec_install_rctx().
static int gss_mech_payload (struct gss_ctx * mechctx, int msgsize, int privacy) [inline, static]
Definition at line 166 of file sec_gss.c.
References GSS_KRB5_INTEG_MAX_PAYLOAD.
Referenced by gss_cli_payload(), gss_svc_bulk_payload(), gss_svc_payload(), and gss_svc_seal().
int gss_pack_err_notify (struct ptlrpc_request * req, __u32 major, __u32 minor)
Definition at line 1955 of file sec_gss.c.
References CDEBUG, CERROR, D_SEC, ENTRY, gss_err_header::gh_flags, gss_err_header::gh_handle, gss_err_header::gh_major, gss_err_header::gh_minor, gss_err_header::gh_proc, gss_err_header::gh_version, gss_svc_ctx2reqctx(), LASSERT, netobj_s::len, libcfs_nid2str(), lustre_msg_buf(), lustre_msg_size_v2(), lustre_pack_reply_v2(), lnet_process_id_t::nid, ptlrpc_body, PTLRPC_GSS_PROC_ERR, PTLRPC_GSS_VERSION, RETURN, ptlrpc_request::rq_peer, ptlrpc_reply_state::rs_repbuf, ptlrpc_reply_state::rs_repdata_len, gss_svc_reqctx::src_err_notify, and gss_svc_reqctx::src_reserve_len.
Referenced by gss_svc_handle_data(), and gss_svc_upcall_handle_init().
int gss_sec_create_common (struct gss_sec * gsec, struct ptlrpc_sec_policy * policy, struct obd_import * imp, struct ptlrpc_svc_ctx * svcctx, struct sptlrpc_flavor * sf)
Definition at line 1095 of file sec_gss.c.
References CDEBUG, CERROR, class_import_get(), D_SEC, gss_sec::gs_base, gss_sec::gs_lock, gss_sec::gs_mech, gss_sec::gs_rvs_hdl, GSS_GC_INTERVAL, INIT_LIST_HEAD, LASSERT, lgss_subflavor_to_mech(), ptlrpc_sec::ps_flvr, ptlrpc_sec::ps_gc_interval, ptlrpc_sec::ps_gc_list, ptlrpc_sec::ps_id, ptlrpc_sec::ps_import, ptlrpc_sec::ps_lock, ptlrpc_sec::ps_nctx, ptlrpc_sec::ps_policy, ptlrpc_sec::ps_refcount, sec_is_reverse(), sptlrpc_flavor::sf_rpc, ptlrpc_sec_policy::sp_name, SPTLRPC_BULK_SVC_PRIV, sptlrpc_enc_pool_add_user(), SPTLRPC_FLVR_BASE_SUB, SPTLRPC_FLVR_BULK_SVC, SPTLRPC_FLVR_POLICY, sptlrpc_get_next_secid(), and SPTLRPC_POLICY_GSS.
Referenced by gss_sec_create_kr(), and gss_sec_create_pf().
void gss_sec_destroy_common (struct gss_sec * gsec)
Definition at line 1145 of file sec_gss.c.
References class_import_put(), ENTRY, EXIT, gss_sec::gs_base, gss_sec::gs_mech, LASSERT, lgss_mech_put(), ptlrpc_sec::ps_flvr, ptlrpc_sec::ps_import, ptlrpc_sec::ps_nctx, ptlrpc_sec::ps_refcount, sptlrpc_flavor::sf_rpc, SPTLRPC_BULK_SVC_PRIV, sptlrpc_enc_pool_del_user(), and SPTLRPC_FLVR_BULK_SVC.
Referenced by gss_sec_create_kr(), gss_sec_create_pf(), gss_sec_destroy_kr(), and gss_sec_destroy_pf().
int gss_sec_install_rctx (struct obd_import * imp, struct ptlrpc_sec * sec, struct ptlrpc_cli_ctx * ctx)
Definition at line 1859 of file sec_gss.c.
References gss_cli_ctx::gc_base, and gss_install_rvs_svc_ctx().
Referenced by gss_cli_ctx_uptodate().
void gss_sec_kill (struct ptlrpc_sec * sec)
Definition at line 1167 of file sec_gss.c.
References ptlrpc_sec::ps_dying.
static int gss_sign_msg (struct lustre_msg * msg, struct gss_ctx * mechctx, enum lustre_sec_part sp, __u32 flags, __u32 proc, __u32 seq, __u32 svc, rawobj_t * handle) [static]
Definition at line 177 of file sec_gss.c.
References CERROR, rawobj_s::data, netobj_s::data, gss_header::gh_flags, gss_header::gh_handle, gss_header::gh_proc, gss_header::gh_seq, gss_header::gh_sp, gss_header::gh_svc, gss_header::gh_version, GSS_S_COMPLETE, LASSERT, netobj_s::len, rawobj_s::len, lgss_get_mic(), lustre_msg_buf(), lustre_msg_size_v2(), lustre_shrink_msg(), msg_last_segidx(), PTLRPC_GSS_VERSION, SPTLRPC_SVC_AUTH, and SPTLRPC_SVC_NULL.
Referenced by gss_cli_ctx_sign(), and gss_svc_sign().
int gss_svc_accept (struct ptlrpc_sec_policy * policy, struct ptlrpc_request * req)
Definition at line 2366 of file sec_gss.c.
References CERROR, ENTRY, gss_header::gh_flags, gss_header::gh_handle, gss_header::gh_proc, gss_header::gh_seq, gss_header::gh_sp, gss_header::gh_svc, gss_header::gh_version, gss_svc_ctx::gsc_mapped_uid, gss_svc_ctx::gsc_remote, gss_svc_ctx::gsc_uid, gss_svc_ctx::gsc_usr_mds, gss_svc_ctx::gsc_usr_oss, gss_svc_ctx::gsc_usr_root, gss_header_swabber(), gss_svc_handle_data(), gss_svc_handle_destroy(), gss_svc_handle_init(), gss_svc_reqctx_free(), gss_swab_header(), gss_wire_ctx::gw_flags, gss_wire_ctx::gw_handle, gss_wire_ctx::gw_proc, gss_wire_ctx::gw_seq, gss_wire_ctx::gw_svc, LASSERT, OBD_ALLOC_PTR, PTLRPC_GSS_PROC_CONTINUE_INIT, PTLRPC_GSS_PROC_DATA, PTLRPC_GSS_PROC_DESTROY, PTLRPC_GSS_PROC_INIT, PTLRPC_GSS_VERSION, ptlrpc_req_need_swab(), rawobj_from_netobj(), RETURN, ptlrpc_request::rq_auth_gss, ptlrpc_request::rq_auth_remote, ptlrpc_request::rq_auth_usr_mdt, ptlrpc_request::rq_auth_usr_ost, ptlrpc_request::rq_auth_usr_root, ptlrpc_request::rq_reqbuf, ptlrpc_svc_ctx::sc_policy, ptlrpc_svc_ctx::sc_refcount, SECSVC_COMPLETE, SECSVC_DROP, SECSVC_OK, sptlrpc_policy_get(), gss_svc_reqctx::src_base, gss_svc_reqctx::src_ctx, and gss_svc_reqctx::src_wirectx.
Referenced by gss_svc_accept_kr(), and gss_svc_accept_pf().
int gss_svc_alloc_rs (struct ptlrpc_request * req, int msglen)
Definition at line 2517 of file sec_gss.c.
References CERROR, ENTRY, GSS_MAX_CIPHER_BLOCK, gss_svc_bulk_payload(), gss_svc_ctx2reqctx(), gss_svc_payload(), gss_svc_reqctx_addref(), gss_svc_reqctx_is_special(), LASSERT, lustre_init_msg_v2(), lustre_msg, lustre_msg_buf(), lustre_msg_buflen(), lustre_msg_size_v2(), OBD_ALLOC_LARGE, PTLRPC_GSS_HEADER_SIZE, RETURN, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_packed_final, ptlrpc_reply_state::rs_msg, ptlrpc_reply_state::rs_repbuf, ptlrpc_reply_state::rs_repbuf_len, ptlrpc_reply_state::rs_size, ptlrpc_reply_state::rs_svc_ctx, sptlrpc_flavor::sf_rpc, SPTLRPC_FLVR_SVC, SPTLRPC_SVC_INTG, SPTLRPC_SVC_NULL, SPTLRPC_SVC_PRIV, gss_svc_reqctx::src_ctx, gss_svc_reqctx::src_repbsd, gss_svc_reqctx::src_repbsd_size, and gss_svc_reqctx::src_reqbsd.
int gss_svc_authorize (struct ptlrpc_request * req)
Definition at line 2735 of file sec_gss.c.
References CERROR, ENTRY, GOTO, gss_at_reply_off_integ, gss_svc_ctx2reqctx(), gss_svc_reqctx_is_special(), gss_svc_seal(), gss_svc_sign(), gss_wire_ctx::gw_proc, gss_wire_ctx::gw_svc, LASSERT, PTLRPC_GSS_PROC_DATA, PTLRPC_GSS_PROC_DESTROY, RETURN, ptlrpc_request::rq_packed_final, ptlrpc_request::rq_reply_off, ptlrpc_reply_state::rs_repdata_len, SPTLRPC_SVC_AUTH, SPTLRPC_SVC_INTG, SPTLRPC_SVC_NULL, SPTLRPC_SVC_PRIV, gss_svc_reqctx::src_ctx, and gss_svc_reqctx::src_wirectx.
static int gss_svc_bulk_payload (struct gss_svc_ctx * gctx, struct sptlrpc_flavor * flvr, int read) [static]
Definition at line 2492 of file sec_gss.c.
References gss_mech_payload(), LBUG, sptlrpc_flavor::sf_rpc, SPTLRPC_BULK_SVC_AUTH, SPTLRPC_BULK_SVC_INTG, SPTLRPC_BULK_SVC_NULL, SPTLRPC_BULK_SVC_PRIV, and SPTLRPC_FLVR_BULK_SVC.
Referenced by gss_svc_alloc_rs().
void gss_svc_free_ctx (struct ptlrpc_svc_ctx * ctx)
Definition at line 2795 of file sec_gss.c.
References gss_svc_ctx2reqctx(), gss_svc_reqctx_free(), LASSERT, and ptlrpc_svc_ctx::sc_refcount.
void gss_svc_free_rs (struct ptlrpc_reply_state * rs)
Definition at line 2781 of file sec_gss.c.
References gss_svc_reqctx_decref(), LASSERT, OBD_FREE_LARGE, ptlrpc_reply_state::rs_prealloc, ptlrpc_reply_state::rs_size, ptlrpc_reply_state::rs_svc_ctx, and gss_svc_reqctx::src_base.
static int gss_svc_handle_data (struct ptlrpc_request * req, struct gss_wire_ctx * gw) [static]
Definition at line 2272 of file sec_gss.c.
References CERROR, ENTRY, error, gss_svc_ctx::gsc_uid, gss_handle_to_u64(), gss_pack_err_notify(), GSS_S_BAD_SIG, GSS_S_NO_CONTEXT, gss_svc_ctx2reqctx(), gss_svc_unseal_request(), gss_svc_upcall_get_ctx(), gss_svc_verify_request(), gss_wire_ctx::gw_handle, gss_wire_ctx::gw_svc, libcfs_nid2str(), LPU64, LPX64, lnet_process_id_t::nid, RETURN, ptlrpc_request::rq_peer, ptlrpc_request::rq_xid, SECSVC_COMPLETE, SECSVC_DROP, SECSVC_OK, SPTLRPC_SVC_AUTH, SPTLRPC_SVC_INTG, SPTLRPC_SVC_NULL, SPTLRPC_SVC_PRIV, and gss_svc_reqctx::src_ctx.
Referenced by gss_svc_accept().
static int gss_svc_handle_destroy (struct ptlrpc_request * req, struct gss_wire_ctx * gw) [static]
Definition at line 2318 of file sec_gss.c.
References CDEBUG, CERROR, CWARN, D_SEC, ENTRY, gss_svc_ctx::gsc_uid, gss_handle_to_u64(), gss_svc_ctx2reqctx(), gss_svc_upcall_destroy_ctx(), gss_svc_upcall_get_ctx(), gss_svc_verify_request(), gss_wire_ctx::gw_flags, gss_wire_ctx::gw_handle, gss_wire_ctx::gw_svc, libcfs_nid2str(), LPX64, LUSTRE_GSS_PACK_USER, lustre_msg_buf(), lnet_process_id_t::nid, ptlrpc_req_need_swab(), RETURN, ptlrpc_request::rq_ctx_fini, ptlrpc_request::rq_no_reply, ptlrpc_request::rq_pack_udesc, ptlrpc_request::rq_peer, ptlrpc_request::rq_reqbuf, SECSVC_DROP, SECSVC_OK, SPTLRPC_SVC_INTG, sptlrpc_unpack_user_desc(), and gss_svc_reqctx::src_ctx.
Referenced by gss_svc_accept().
static int gss_svc_handle_init (struct ptlrpc_request * req, struct gss_wire_ctx * gw) [static]
Definition at line 1996 of file sec_gss.c.
References CDEBUG, CERROR, class_uuid2obd(), CWARN, D_SEC, rawobj_s::data, ENTRY, gss_svc_ctx::gsc_uid, gss_svc_ctx::gsc_usr_mds, gss_svc_ctx::gsc_usr_oss, gss_svc_ctx::gsc_usr_root, gss_svc_ctx2reqctx(), gss_svc_upcall_handle_init(), gss_wire_ctx::gw_flags, gss_wire_ctx::gw_handle, gss_wire_ctx::gw_proc, le32_to_cpu, rawobj_s::len, libcfs_nid2str(), LUSTRE_GSS_PACK_BULK, LUSTRE_GSS_PACK_USER, lustre_msg, lustre_msg_buf(), lustre_msg_buflen(), lnet_process_id_t::nid, obd_device::obd_set_up, obd_device::obd_stopping, PTLRPC_GSS_PROC_INIT, ptlrpc_req_need_swab(), rawobj_extract(), RETURN, ptlrpc_request::rq_ctx_init, ptlrpc_request::rq_pack_udesc, ptlrpc_request::rq_peer, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqlen, ptlrpc_request::rq_reqmsg, SECSVC_DROP, SECSVC_OK, sptlrpc_unpack_user_desc(), gss_svc_reqctx::src_ctx, obd_uuid::uuid, and uuid.
Referenced by gss_svc_accept().
void gss_svc_invalidate_ctx (struct ptlrpc_svc_ctx * svc_ctx)
Definition at line 2460 of file sec_gss.c.
References CWARN, ENTRY, EXIT, gss_svc_ctx::gsc_uid, gss_svc_ctx2reqctx(), gss_svc_upcall_destroy_ctx(), and gss_svc_reqctx::src_ctx.
static int gss_svc_payload (struct gss_svc_reqctx * grctx, int early, int msgsize, int privacy) [inline, static]
Definition at line 2480 of file sec_gss.c.
References gss_mech_payload(), gss_svc_reqctx_is_special(), and gss_svc_reqctx::src_reserve_len.
Referenced by gss_svc_alloc_rs().
static void gss_svc_reqctx_addref (struct gss_svc_reqctx * grctx) [inline, static]
Definition at line 1897 of file sec_gss.c.
References LASSERT, ptlrpc_svc_ctx::sc_refcount, and gss_svc_reqctx::src_base.
Referenced by gss_svc_alloc_rs().
static void gss_svc_reqctx_decref (struct gss_svc_reqctx * grctx) [inline, static]
Definition at line 1904 of file sec_gss.c.
References gss_svc_reqctx_free(), LASSERT, ptlrpc_svc_ctx::sc_refcount, and gss_svc_reqctx::src_base.
Referenced by gss_svc_free_rs().
static void gss_svc_reqctx_free (struct gss_svc_reqctx * grctx) [static]
Definition at line 1887 of file sec_gss.c.
References gss_svc_upcall_put_ctx(), OBD_FREE_PTR, ptlrpc_svc_ctx::sc_policy, sptlrpc_policy_put(), gss_svc_reqctx::src_base, and gss_svc_reqctx::src_ctx.
Referenced by gss_svc_accept(), gss_svc_free_ctx(), and gss_svc_reqctx_decref().
static int gss_svc_reqctx_is_special (struct gss_svc_reqctx * grctx) [inline, static]
Definition at line 1879 of file sec_gss.c.
References LASSERT, gss_svc_reqctx::src_err_notify, gss_svc_reqctx::src_init, and gss_svc_reqctx::src_init_continue.
Referenced by gss_svc_alloc_rs(), gss_svc_authorize(), and gss_svc_payload().
static int gss_svc_seal (struct ptlrpc_request * req, struct ptlrpc_reply_state * rs, struct gss_svc_reqctx * grctx) [static]
Definition at line 2637 of file sec_gss.c.
References CERROR, rawobj_s::data, ENTRY, gss_header::gh_flags, gss_header::gh_handle, gss_header::gh_proc, gss_header::gh_seq, gss_header::gh_sp, gss_header::gh_svc, gss_header::gh_version, GOTO, gss_svc_ctx::gsc_mechctx, gss_at_reply_off_priv, gss_mech_payload(), GSS_S_COMPLETE, gss_wire_ctx::gw_seq, LASSERT, rawobj_s::len, netobj_s::len, lgss_wrap(), LUSTRE_GSS_PACK_BULK, lustre_init_msg_v2(), lustre_msg_buf(), lustre_msg_buflen(), lustre_msg_size_v2(), lustre_msghdr_get_flags(), lustre_shrink_msg(), LUSTRE_SP_ANY, MSGHDR_AT_SUPPORT, OBD_ALLOC_LARGE, OBD_FREE_LARGE, PTLRPC_GSS_HEADER_SIZE, PTLRPC_GSS_PROC_DATA, PTLRPC_GSS_VERSION, RETURN, ptlrpc_request::rq_flvr, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_packed_final, ptlrpc_request::rq_replen, ptlrpc_request::rq_reply_off, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_reqmsg, ptlrpc_reply_state::rs_msg, ptlrpc_reply_state::rs_repbuf, ptlrpc_reply_state::rs_repbuf_len, ptlrpc_reply_state::rs_repdata_len, sptlrpc_flavor::sf_rpc, SPTLRPC_SVC_PRIV, gss_svc_reqctx::src_ctx, gss_svc_reqctx::src_repbsd, gss_svc_reqctx::src_repbsd_size, and gss_svc_reqctx::src_wirectx.
Referenced by gss_svc_authorize().
static int gss_svc_sign (struct ptlrpc_request * req, struct ptlrpc_reply_state * rs, struct gss_svc_reqctx * grctx, __u32 svc) [static]
Definition at line 1913 of file sec_gss.c.
References ENTRY, gss_svc_ctx::gsc_mechctx, gss_at_reply_off_integ, gss_sign_msg(), gss_wire_ctx::gw_seq, LASSERT, likely, LUSTRE_GSS_PACK_BULK, lustre_msg_buf(), lustre_msg_buflen(), lustre_msghdr_get_flags(), lustre_shrink_msg(), LUSTRE_SP_ANY, MSGHDR_AT_SUPPORT, PTLRPC_GSS_PROC_DATA, RETURN, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_packed_final, ptlrpc_request::rq_replen, ptlrpc_request::rq_reply_off, ptlrpc_request::rq_reqmsg, ptlrpc_reply_state::rs_msg, ptlrpc_reply_state::rs_repbuf, ptlrpc_reply_state::rs_repdata_len, SPTLRPC_SVC_NULL, gss_svc_reqctx::src_ctx, and gss_svc_reqctx::src_wirectx.
Referenced by gss_svc_authorize().
static int gss_svc_unseal_request (struct ptlrpc_request * req, struct gss_svc_reqctx * grctx, struct gss_wire_ctx * gw, __u32 * major) [static]
Definition at line 2195 of file sec_gss.c.
References __lustre_unpack_msg(), bulk_sec_desc_unpack(), CERROR, ENTRY, gss_svc_ctx::gsc_mechctx, gss_svc_ctx::gsc_seqdata, gss_check_seq_num(), GSS_S_COMPLETE, GSS_S_DUPLICATE_TOKEN, gss_unseal_msg(), gss_wire_ctx::gw_flags, gss_wire_ctx::gw_seq, LUSTRE_GSS_PACK_BULK, LUSTRE_GSS_PACK_USER, lustre_msg, lustre_msg_buf(), lustre_msg_buflen(), RETURN, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_pack_udesc, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqdata_len, ptlrpc_request::rq_reqlen, ptlrpc_request::rq_reqmsg, sptlrpc_unpack_user_desc(), gss_svc_reqctx::src_ctx, gss_svc_reqctx::src_reqbsd, and gss_svc_reqctx::src_reqbsd_size.
Referenced by gss_svc_handle_data().
static int gss_svc_verify_request (struct ptlrpc_request * req, struct gss_svc_reqctx * grctx, struct gss_wire_ctx * gw, __u32 * major) [static]
Definition at line 2114 of file sec_gss.c.
References bulk_sec_desc_unpack(), CERROR, ENTRY, gss_svc_ctx::gsc_mechctx, gss_svc_ctx::gsc_reverse, gss_svc_ctx::gsc_seqdata, gss_check_seq_num(), GSS_S_COMPLETE, GSS_S_DUPLICATE_TOKEN, gss_verify_msg(), gss_wire_ctx::gw_flags, gss_wire_ctx::gw_seq, gss_wire_ctx::gw_svc, LUSTRE_GSS_PACK_BULK, LUSTRE_GSS_PACK_USER, lustre_msg, lustre_msg_buf(), lustre_msg_buflen(), ptlrpc_req_need_swab(), RETURN, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_pack_udesc, ptlrpc_request::rq_reqbuf, ptlrpc_request::rq_reqlen, ptlrpc_request::rq_reqmsg, SPTLRPC_SVC_NULL, sptlrpc_unpack_user_desc(), gss_svc_reqctx::src_ctx, gss_svc_reqctx::src_reqbsd, and gss_svc_reqctx::src_reqbsd_size.
Referenced by gss_svc_handle_data(), and gss_svc_handle_destroy().
struct gss_header* gss_swab_header (struct lustre_msg * msg, int segment, int swabbed) [read]
Definition at line 107 of file sec_gss.c.
References CERROR, gss_header::gh_handle, gss_header_swabber(), netobj_s::len, and lustre_msg_buf().
Referenced by ctx_init_parse_reply(), gss_cli_ctx_unseal(), gss_cli_ctx_verify(), and gss_svc_accept().
static __u32 gss_unseal_msg (struct gss_ctx * mechctx, struct lustre_msg * msgbuf, int * msg_len, int msgbuf_len) [static]
Definition at line 275 of file sec_gss.c.
References CERROR, rawobj_s::data, ENTRY, GOTO, GSS_S_COMPLETE, GSS_S_FAILURE, LASSERT, rawobj_s::len, lgss_unwrap(), lustre_msg_buf(), lustre_msg_buflen(), OBD_ALLOC_LARGE, OBD_FREE_LARGE, and RETURN.
Referenced by gss_cli_ctx_unseal(), and gss_svc_unseal_request().
static __u32 gss_verify_msg (struct lustre_msg * msg, struct gss_ctx * mechctx, __u32 svc) [static]
Definition at line 239 of file sec_gss.c.
References CERROR, rawobj_s::data, GSS_S_COMPLETE, LASSERT, rawobj_s::len, lgss_verify_mic(), lustre_msg_buf(), msg_last_segidx(), SPTLRPC_SVC_AUTH, and SPTLRPC_SVC_NULL.
Referenced by gss_cli_ctx_verify(), and gss_svc_verify_request().
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre GSS security policy")
module_exit (sptlrpc_gss_exit)
module_init (sptlrpc_gss_init)
MODULE_LICENSE ("GPL")
MODULE_VERSION (LUSTRE_VERSION_STRING)
static int msg_last_segidx (struct lustre_msg * msg) [inline, static]
Definition at line 82 of file sec_gss.c.
References LASSERT.
Referenced by gss_enlarge_reqbuf_intg(), gss_sign_msg(), gss_verify_msg(), and msg_last_seglen().
static int msg_last_seglen (struct lustre_msg * msg) [inline, static]
Definition at line 87 of file sec_gss.c.
References msg_last_segidx().
Referenced by gss_enlarge_reqbuf_intg().
static void __exit sptlrpc_gss_exit (void) [static]
Definition at line 2932 of file sec_gss.c.
References cleanup_kerberos_module(), gss_exit_cli_upcall(), gss_exit_keyring(), gss_exit_lproc(), gss_exit_pipefs(), and gss_exit_svc_upcall().
static int __init sptlrpc_gss_init (void) [static]
Definition at line 2872 of file sec_gss.c.
References cleanup_kerberos_module(), cleanup_null_module(), cleanup_sk_module(), gss_exit_cli_upcall(), gss_exit_keyring(), gss_exit_lproc(), gss_exit_svc_upcall(), gss_init_at_reply_offset(), gss_init_cli_upcall(), gss_init_keyring(), gss_init_lproc(), gss_init_pipefs(), gss_init_svc_upcall(), init_kerberos_module(), init_null_module(), and init_sk_module().
Variable Documentation
int gss_at_reply_off_integ [static]
Definition at line 78 of file sec_gss.c.
Referenced by gss_alloc_repbuf_intg(), gss_init_at_reply_offset(), gss_svc_authorize(), and gss_svc_sign().
int gss_at_reply_off_priv [static]
Definition at line 79 of file sec_gss.c.
Referenced by gss_alloc_repbuf_priv(), gss_init_at_reply_offset(), and gss_svc_seal().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.