Lustre: lustre/ptlrpc/sec_ctx.c File Reference
lustre/ptlrpc/sec_ctx.c File Reference
#include <linux/fs.h>
#include <libcfs/libcfs.h>
#include <lvfs.h>
#include <obd_class.h>
#include "ptlrpc_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_FILTER
#define ASSERT_CTXT_MAGIC(magic) LASSERT((magic) == OBD_RUN_CTXT_MAGIC)
#define ASSERT_NOT_KERNEL_CTXT(msg)
#define ASSERT_KERNEL_CTXT(msg) LASSERTF(segment_eq(get_fs(), get_ds()), msg)
Functions
void push_ctxt (struct lvfs_run_ctxt *save, struct lvfs_run_ctxt *new_ctx)
void pop_ctxt (struct lvfs_run_ctxt *saved, struct lvfs_run_ctxt *new_ctx)
int lustre_rename (struct dentry *dir, struct vfsmount *mnt, char *oldname, char *newname)
Define Documentation
#define ASSERT_CTXT_MAGIC (magic) LASSERT((magic) == OBD_RUN_CTXT_MAGIC)
Definition at line 39 of file sec_ctx.c.
Referenced by pop_ctxt(), and push_ctxt().
#define ASSERT_KERNEL_CTXT (msg) LASSERTF(segment_eq(get_fs(), get_ds()), msg)
Definition at line 42 of file sec_ctx.c.
Referenced by lustre_rename(), and pop_ctxt().
#define ASSERT_NOT_KERNEL_CTXT (msg)
Value:
LASSERTF(!segment_eq(get_fs(), get_ds()),\
                                              msg)
Definition at line 40 of file sec_ctx.c.
#define DEBUG_SUBSYSTEM S_FILTER
Definition at line 27 of file sec_ctx.c.
Function Documentation
int lustre_rename (struct dentry * dir, struct vfsmount * mnt, char * oldname, char * newname)
Definition at line 102 of file sec_ctx.c.
References ASSERT_KERNEL_CTXT, CDEBUG, D_INODE, ENTRY, GOTO, ll_lookup_one_len(), ll_vfs_rename, and RETURN.
Referenced by sptlrpc_target_local_copy_conf().
void pop_ctxt (struct lvfs_run_ctxt * saved, struct lvfs_run_ctxt * new_ctx)
Definition at line 78 of file sec_ctx.c.
References ASSERT_CTXT_MAGIC, ASSERT_KERNEL_CTXT, lvfs_run_ctxt::dt, lvfs_run_ctxt::fs, LASSERTF, ll_set_fs_pwd(), lvfs_run_ctxt::magic, lvfs_run_ctxt::pwd, lvfs_run_ctxt::pwdmnt, and lvfs_run_ctxt::umask.
Referenced by osd_mdt_init(), osd_ost_init(), osd_scrub_setup(), sptlrpc_target_local_copy_conf(), and sptlrpc_target_local_read_conf().
void push_ctxt (struct lvfs_run_ctxt * save, struct lvfs_run_ctxt * new_ctx)
Definition at line 50 of file sec_ctx.c.
References ASSERT_CTXT_MAGIC, lvfs_run_ctxt::dt, lvfs_run_ctxt::fs, LASSERT, ll_d_count, ll_set_fs_pwd(), lvfs_run_ctxt::magic, OBD_SET_CTXT_MAGIC(), lvfs_run_ctxt::pwd, lvfs_run_ctxt::pwdmnt, and lvfs_run_ctxt::umask.
Referenced by osd_push_ctxt(), osd_scrub_setup(), sptlrpc_target_local_copy_conf(), and sptlrpc_target_local_read_conf().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.