Lustre: lustre/ptlrpc/sec_config.c File Reference
lustre/ptlrpc/sec_config.c File Reference
#include <libcfs/libcfs.h>
#include <linux/crypto.h>
#include <linux/key.h>
#include <obd.h>
#include <obd_class.h>
#include <obd_support.h>
#include <lustre_net.h>
#include <lustre_import.h>
#include <lustre_log.h>
#include <lustre_disk.h>
#include <lustre_dlm.h>
#include <lustre_param.h>
#include <lustre_sec.h>
#include "ptlrpc_internal.h"
Data Structures
struct sptlrpc_conf_tgt
struct sptlrpc_conf
Defines
#define DEBUG_SUBSYSTEM S_SEC
#define SEC_ADAPT_DELAY (10)
#define LOG_SPTLRPC_TMP "sptlrpc.tmp"
#define LOG_SPTLRPC "sptlrpc"
Functions
const char * sptlrpc_part2name (enum lustre_sec_part part)
enum lustre_sec_part sptlrpc_target_sec_part (struct obd_device *obd)
int sptlrpc_parse_flavor (const char *str, struct sptlrpc_flavor *flvr)
static void get_default_flavor (struct sptlrpc_flavor *sf)
static void sptlrpc_rule_init (struct sptlrpc_rule *rule)
int sptlrpc_parse_rule (char *param, struct sptlrpc_rule *rule)
void sptlrpc_rule_set_free (struct sptlrpc_rule_set *rset)
int sptlrpc_rule_set_expand (struct sptlrpc_rule_set *rset)
static int rule_spec_dir (struct sptlrpc_rule *rule)
static int rule_spec_net (struct sptlrpc_rule *rule)
static int rule_match_dir (struct sptlrpc_rule *r1, struct sptlrpc_rule *r2)
static int rule_match_net (struct sptlrpc_rule *r1, struct sptlrpc_rule *r2)
int sptlrpc_rule_set_merge (struct sptlrpc_rule_set *rset, struct sptlrpc_rule *rule)
int sptlrpc_rule_set_choose (struct sptlrpc_rule_set *rset, enum lustre_sec_part from, enum lustre_sec_part to, lnet_nid_t nid, struct sptlrpc_flavor *sf)
given from/to/nid, determine a matching flavor in ruleset.
void sptlrpc_rule_set_dump (struct sptlrpc_rule_set *rset)
static int sptlrpc_rule_set_extract (struct sptlrpc_rule_set *gen, struct sptlrpc_rule_set *tgt, enum lustre_sec_part from, enum lustre_sec_part to, struct sptlrpc_rule_set *rset)
static int is_hex (char c)
static void target2fsname (const char *tgt, char *fsname, int buflen)
static void sptlrpc_conf_free_rsets (struct sptlrpc_conf *conf)
static void sptlrpc_conf_free (struct sptlrpc_conf *conf)
static struct sptlrpc_conf_tgt * sptlrpc_conf_get_tgt (struct sptlrpc_conf *conf, const char *name, int create)
static struct sptlrpc_conf * sptlrpc_conf_get (const char *fsname, int create)
static int sptlrpc_conf_merge_rule (struct sptlrpc_conf *conf, const char *target, struct sptlrpc_rule *rule)
caller must hold conf_lock already.
static int __sptlrpc_process_config (struct lustre_cfg *lcfg, struct sptlrpc_conf *conf)
process one LCFG_SPTLRPC_CONF record.
int sptlrpc_process_config (struct lustre_cfg *lcfg)
static int logname2fsname (const char *logname, char *buf, int buflen)
void sptlrpc_conf_log_update_begin (const char *logname)
void sptlrpc_conf_log_update_end (const char *logname)
mark a config log has been updated
void sptlrpc_conf_log_start (const char *logname)
void sptlrpc_conf_log_stop (const char *logname)
static void flavor_set_flags (struct sptlrpc_flavor *sf, enum lustre_sec_part from, enum lustre_sec_part to, unsigned int fl_udesc)
void sptlrpc_conf_choose_flavor (enum lustre_sec_part from, enum lustre_sec_part to, struct obd_uuid *target, lnet_nid_t nid, struct sptlrpc_flavor *sf)
void sptlrpc_target_choose_flavor (struct sptlrpc_rule_set *rset, enum lustre_sec_part from, lnet_nid_t nid, struct sptlrpc_flavor *sf)
called by target devices, determine the expected flavor from certain peer (from, nid).
void sptlrpc_conf_client_adapt (struct obd_device *obd)
called by client devices, notify the sptlrpc config has changed and do import_sec_adapt later.
static void rule2string (struct sptlrpc_rule *r, char *buf, int buflen)
static int sptlrpc_record_rule_set (struct llog_handle *llh, char *target, struct sptlrpc_rule_set *rset)
static int sptlrpc_record_rules (struct llog_handle *llh, struct sptlrpc_conf *conf)
static int sptlrpc_target_local_copy_conf (struct obd_device *obd, struct sptlrpc_conf *conf)
static int local_read_handler (const struct lu_env *env, struct llog_handle *llh, struct llog_rec_hdr *rec, void *data)
static int sptlrpc_target_local_read_conf (struct obd_device *obd, struct sptlrpc_conf *conf)
int sptlrpc_conf_target_get_rules (struct obd_device *obd, struct sptlrpc_rule_set *rset, int initial)
called by target devices, extract sptlrpc rules which applies to this target, to be used for future rpc flavor checking.
int sptlrpc_conf_init (void)
void sptlrpc_conf_fini (void)
Variables
static struct mutex sptlrpc_conf_lock
static struct list_head sptlrpc_confs
Define Documentation
#define DEBUG_SUBSYSTEM S_SEC
Definition at line 37 of file sec_config.c.
#define LOG_SPTLRPC "sptlrpc"
Definition at line 997 of file sec_config.c.
Referenced by sptlrpc_target_local_copy_conf(), and sptlrpc_target_local_read_conf().
#define LOG_SPTLRPC_TMP "sptlrpc.tmp"
Definition at line 996 of file sec_config.c.
Referenced by sptlrpc_target_local_copy_conf().
#define SEC_ADAPT_DELAY (10)
Definition at line 899 of file sec_config.c.
Referenced by sptlrpc_conf_client_adapt().
Function Documentation
static int __sptlrpc_process_config (struct lustre_cfg * lcfg, struct sptlrpc_conf * conf) [static]
process one LCFG_SPTLRPC_CONF record.
if conf is NULL, we find one through the target name in the record inside conf_lock; otherwise means caller already hold conf_lock.
Definition at line 656 of file sec_config.c.
References CDEBUG, CERROR, D_SEC, ENTRY, LASSERT, lustre_cfg_string(), MTI_NAME_MAXLEN, PARAM_SRPC_FLVR, RETURN, sptlrpc_conf::sc_modified, sptlrpc_conf_get(), sptlrpc_conf_lock, sptlrpc_conf_merge_rule(), sptlrpc_parse_rule(), and target2fsname().
Referenced by local_read_handler(), and sptlrpc_process_config().
static void flavor_set_flags (struct sptlrpc_flavor * sf, enum lustre_sec_part from, enum lustre_sec_part to, unsigned int fl_udesc) [inline, static]
Definition at line 818 of file sec_config.c.
References LUSTRE_SP_CLI, LUSTRE_SP_MDT, LUSTRE_SP_OST, PTLRPC_SEC_FL_BULK, PTLRPC_SEC_FL_ROOTONLY, PTLRPC_SEC_FL_UDESC, sptlrpc_flavor::sf_flags, sptlrpc_flavor::sf_rpc, and SPTLRPC_FLVR_NULL.
Referenced by sptlrpc_conf_choose_flavor().
static void get_default_flavor (struct sptlrpc_flavor * sf) [static]
Definition at line 165 of file sec_config.c.
References sptlrpc_flavor::sf_flags, sptlrpc_flavor::sf_rpc, and SPTLRPC_FLVR_NULL.
Referenced by sptlrpc_conf_choose_flavor(), sptlrpc_rule_init(), and sptlrpc_target_choose_flavor().
static int is_hex (char c) [inline, static]
Definition at line 511 of file sec_config.c.
Referenced by target2fsname().
static int local_read_handler (const struct lu_env * env, struct llog_handle * llh, struct llog_rec_hdr * rec, void * data) [static]
Definition at line 1058 of file sec_config.c.
References __sptlrpc_process_config(), CERROR, ENTRY, lustre_cfg::lcfg_command, LCFG_SPTLRPC_CONF, llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, lustre_cfg_sanity_check(), OBD_CFG_REC, and RETURN.
Referenced by sptlrpc_target_local_read_conf().
static int logname2fsname (const char * logname, char * buf, int buflen) [static]
Definition at line 719 of file sec_config.c.
References CERROR.
Referenced by sptlrpc_conf_log_start(), sptlrpc_conf_log_stop(), sptlrpc_conf_log_update_begin(), and sptlrpc_conf_log_update_end().
static void rule2string (struct sptlrpc_rule * r, char * buf, int buflen) [static]
Definition at line 934 of file sec_config.c.
References libcfs_net2str_r(), LNET_NID_ANY, LNET_NIDNET(), LNET_NIDSTR_SIZE, LUSTRE_SP_ANY, sptlrpc_flavor2name(), sptlrpc_part2name(), sptlrpc_rule::sr_flvr, sptlrpc_rule::sr_from, sptlrpc_rule::sr_netid, and sptlrpc_rule::sr_to.
Referenced by sptlrpc_record_rule_set().
static int rule_match_dir (struct sptlrpc_rule * r1, struct sptlrpc_rule * r2) [inline, static]
Definition at line 298 of file sec_config.c.
References sptlrpc_rule::sr_from, and sptlrpc_rule::sr_to.
Referenced by sptlrpc_rule_set_merge().
static int rule_match_net (struct sptlrpc_rule * r1, struct sptlrpc_rule * r2) [inline, static]
Definition at line 303 of file sec_config.c.
References sptlrpc_rule::sr_netid.
Referenced by sptlrpc_rule_set_merge().
static int rule_spec_dir (struct sptlrpc_rule * rule) [inline, static]
Definition at line 289 of file sec_config.c.
References LUSTRE_SP_ANY, sptlrpc_rule::sr_from, and sptlrpc_rule::sr_to.
Referenced by sptlrpc_rule_set_merge().
static int rule_spec_net (struct sptlrpc_rule * rule) [inline, static]
Definition at line 294 of file sec_config.c.
References LNET_NID_ANY, LNET_NIDNET(), and sptlrpc_rule::sr_netid.
Referenced by sptlrpc_rule_set_merge().
void sptlrpc_conf_choose_flavor (enum lustre_sec_part from, enum lustre_sec_part to, struct obd_uuid * target, lnet_nid_t nid, struct sptlrpc_flavor * sf)
Definition at line 843 of file sec_config.c.
References flavor_set_flags(), get_default_flavor(), LASSERT, MTI_NAME_MAXLEN, name, sptlrpc_conf::sc_rset, sptlrpc_conf_tgt::sct_rset, sptlrpc_conf_get(), sptlrpc_conf_get_tgt(), sptlrpc_conf_lock, sptlrpc_rule_set_choose(), target2fsname(), and obd_uuid::uuid.
Referenced by sptlrpc_import_sec_adapt().
void sptlrpc_conf_fini (void)
Definition at line 1217 of file sec_config.c.
References LASSERT, list_empty(), list_for_each_entry_safe, sptlrpc_conf::sc_list, sptlrpc_conf_free(), sptlrpc_conf_lock, and sptlrpc_confs.
Referenced by sptlrpc_fini(), and sptlrpc_init().
static void sptlrpc_conf_free (struct sptlrpc_conf * conf) [static]
Definition at line 560 of file sec_config.c.
References CDEBUG, D_SEC, list_del(), OBD_FREE_PTR, sptlrpc_conf::sc_fsname, sptlrpc_conf::sc_list, and sptlrpc_conf_free_rsets().
Referenced by sptlrpc_conf_fini(), and sptlrpc_conf_log_stop().
static void sptlrpc_conf_free_rsets (struct sptlrpc_conf * conf) [static]
Definition at line 542 of file sec_config.c.
References LASSERT, list_del(), list_empty(), list_for_each_entry_safe, OBD_FREE_PTR, sptlrpc_conf::sc_local, sptlrpc_conf::sc_rset, sptlrpc_conf::sc_tgts, sptlrpc_conf::sc_updated, sptlrpc_conf_tgt::sct_list, sptlrpc_conf_tgt::sct_rset, and sptlrpc_rule_set_free().
Referenced by sptlrpc_conf_free(), sptlrpc_conf_log_update_begin(), sptlrpc_conf_target_get_rules(), and sptlrpc_target_local_read_conf().
static struct sptlrpc_conf* sptlrpc_conf_get (const char * fsname, int create) [static, read]
Definition at line 595 of file sec_config.c.
References CDEBUG, D_SEC, INIT_LIST_HEAD, list_add(), list_for_each_entry, OBD_ALLOC_PTR, OBD_FREE_PTR, sptlrpc_conf::sc_fsname, sptlrpc_conf::sc_list, sptlrpc_conf::sc_rset, sptlrpc_conf::sc_tgts, sptlrpc_confs, sptlrpc_rule_set_init(), and strlcpy().
Referenced by __sptlrpc_process_config(), sptlrpc_conf_choose_flavor(), sptlrpc_conf_log_start(), sptlrpc_conf_log_stop(), sptlrpc_conf_log_update_begin(), sptlrpc_conf_log_update_end(), and sptlrpc_conf_target_get_rules().
static struct sptlrpc_conf_tgt* sptlrpc_conf_get_tgt (struct sptlrpc_conf * conf, const char * name, int create) [static, read]
Definition at line 570 of file sec_config.c.
References list_add(), list_for_each_entry, OBD_ALLOC_PTR, sptlrpc_conf::sc_tgts, sptlrpc_conf_tgt::sct_list, sptlrpc_conf_tgt::sct_name, sptlrpc_conf_tgt::sct_rset, sptlrpc_rule_set_init(), and strlcpy().
Referenced by sptlrpc_conf_choose_flavor(), sptlrpc_conf_merge_rule(), and sptlrpc_conf_target_get_rules().
int sptlrpc_conf_init (void)
Definition at line 1210 of file sec_config.c.
References INIT_LIST_HEAD, sptlrpc_conf_lock, and sptlrpc_confs.
Referenced by sptlrpc_init().
static int sptlrpc_conf_merge_rule (struct sptlrpc_conf * conf, const char * target, struct sptlrpc_rule * rule) [static]
caller must hold conf_lock already.
Definition at line 628 of file sec_config.c.
References CERROR, sptlrpc_conf::sc_fsname, sptlrpc_conf::sc_rset, sptlrpc_conf_tgt::sct_rset, sptlrpc_conf_get_tgt(), and sptlrpc_rule_set_merge().
Referenced by __sptlrpc_process_config().
static int sptlrpc_record_rule_set (struct llog_handle * llh, char * target, struct sptlrpc_rule_set * rset) [static]
Definition at line 956 of file sec_config.c.
References LCFG_SPTLRPC_CONF, lcr, llog_cfg_rec::lcr_hdr, LLOG_NEXT_IDX, llog_write(), lustre_cfg_bufs_reset(), lustre_cfg_bufs_set_string(), lustre_cfg_rec_free(), lustre_cfg_rec_new(), rule2string(), sptlrpc_rule_set::srs_nrule, and sptlrpc_rule_set::srs_rules.
Referenced by sptlrpc_record_rules().
static int sptlrpc_record_rules (struct llog_handle * llh, struct sptlrpc_conf * conf) [static]
Definition at line 982 of file sec_config.c.
References list_for_each_entry, sptlrpc_conf::sc_fsname, sptlrpc_conf::sc_rset, sptlrpc_conf::sc_tgts, sptlrpc_conf_tgt::sct_list, sptlrpc_conf_tgt::sct_name, sptlrpc_conf_tgt::sct_rset, and sptlrpc_record_rule_set().
Referenced by sptlrpc_target_local_copy_conf().
static void sptlrpc_rule_init (struct sptlrpc_rule * rule) [static]
Definition at line 173 of file sec_config.c.
References get_default_flavor(), LNET_NID_ANY, LNET_NIDNET(), LUSTRE_SP_ANY, sptlrpc_rule::sr_flvr, sptlrpc_rule::sr_from, sptlrpc_rule::sr_netid, sptlrpc_rule::sr_padding, and sptlrpc_rule::sr_to.
Referenced by sptlrpc_parse_rule().
static int sptlrpc_rule_set_extract (struct sptlrpc_rule_set * gen, struct sptlrpc_rule_set * tgt, enum lustre_sec_part from, enum lustre_sec_part to, struct sptlrpc_rule_set * rset) [static]
Definition at line 448 of file sec_config.c.
References CERROR, LUSTRE_SP_ANY, sptlrpc_rule_set_merge(), sptlrpc_rule::sr_from, sptlrpc_rule::sr_to, sptlrpc_rule_set::srs_nrule, and sptlrpc_rule_set::srs_rules.
Referenced by sptlrpc_conf_target_get_rules().
static int sptlrpc_target_local_copy_conf (struct obd_device * obd, struct sptlrpc_conf * conf) [static]
Definition at line 1000 of file sec_config.c.
References CDEBUG, CERROR, D_SEC, ENTRY, GOTO, ll_lookup_one_len(), llog_close(), LLOG_CONFIG_ORIG_CTXT, llog_ctxt_put(), llog_erase(), LLOG_F_IS_PLAIN, llog_get_context(), llog_init_handle(), llog_open_create(), LOG_SPTLRPC, LOG_SPTLRPC_TMP, lustre_rename(), MOUNT_CONFIGS_DIR, obd_device::obd_lvfs_ctxt, obd_device::obd_name, pop_ctxt(), push_ctxt(), lvfs_run_ctxt::pwdmnt, RETURN, and sptlrpc_record_rules().
Referenced by sptlrpc_conf_target_get_rules().
static int sptlrpc_target_local_read_conf (struct obd_device * obd, struct sptlrpc_conf * conf) [static]
Definition at line 1090 of file sec_config.c.
References CDEBUG, CERROR, D_SEC, ENTRY, GOTO, LASSERT, llog_close(), LLOG_CONFIG_ORIG_CTXT, llog_ctxt_put(), LLOG_F_IS_PLAIN, llog_get_context(), llog_get_size(), llog_init_handle(), llog_open(), LLOG_OPEN_EXISTS, llog_process(), local_read_handler(), LOG_SPTLRPC, obd_device::obd_lvfs_ctxt, obd_device::obd_name, pop_ctxt(), push_ctxt(), RETURN, sptlrpc_conf::sc_local, sptlrpc_conf::sc_updated, and sptlrpc_conf_free_rsets().
Referenced by sptlrpc_conf_target_get_rules().
static void target2fsname (const char * tgt, char * fsname, int buflen) [static]
Definition at line 517 of file sec_config.c.
References is_hex().
Referenced by __sptlrpc_process_config(), sptlrpc_conf_choose_flavor(), and sptlrpc_conf_target_get_rules().
Variable Documentation
struct mutex sptlrpc_conf_lock [static]
Definition at line 508 of file sec_config.c.
Referenced by __sptlrpc_process_config(), sptlrpc_conf_choose_flavor(), sptlrpc_conf_fini(), sptlrpc_conf_init(), sptlrpc_conf_log_start(), sptlrpc_conf_log_stop(), sptlrpc_conf_log_update_begin(), sptlrpc_conf_log_update_end(), and sptlrpc_conf_target_get_rules().
struct list_head sptlrpc_confs [static]
Definition at line 509 of file sec_config.c.
Referenced by sptlrpc_conf_fini(), sptlrpc_conf_get(), and sptlrpc_conf_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.