Lustre: lustre/ptlrpc/sec_lproc.c File Reference
lustre/ptlrpc/sec_lproc.c File Reference
#include <libcfs/libcfs.h>
#include <linux/crypto.h>
#include <obd.h>
#include <obd_class.h>
#include <obd_support.h>
#include <lustre_net.h>
#include <lustre_import.h>
#include <lustre_dlm.h>
#include <lustre_sec.h>
#include "ptlrpc_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_SEC
Functions
static char * sec_flags2str (unsigned long flags, char *buf, int bufsize)
static int sptlrpc_info_lprocfs_seq_show (struct seq_file *seq, void *v)
LPROC_SEQ_FOPS_RO (sptlrpc_info_lprocfs)
static int sptlrpc_ctxs_lprocfs_seq_show (struct seq_file *seq, void *v)
LPROC_SEQ_FOPS_RO (sptlrpc_ctxs_lprocfs)
int sptlrpc_lprocfs_cliobd_attach (struct obd_device *dev)
LPROC_SEQ_FOPS_RO (sptlrpc_proc_enc_pool)
int sptlrpc_lproc_init (void)
void sptlrpc_lproc_fini (void)
Variables
struct proc_dir_entry * sptlrpc_proc_root = NULL
static struct lprocfs_vars sptlrpc_lprocfs_vars []
Define Documentation
#define DEBUG_SUBSYSTEM S_SEC
Definition at line 41 of file sec_lproc.c.
Function Documentation
LPROC_SEQ_FOPS_RO (sptlrpc_proc_enc_pool)
LPROC_SEQ_FOPS_RO (sptlrpc_ctxs_lprocfs)
LPROC_SEQ_FOPS_RO (sptlrpc_info_lprocfs)
static char* sec_flags2str (unsigned long flags, char * buf, int bufsize) [static]
Definition at line 60 of file sec_lproc.c.
References PTLRPC_SEC_FL_BULK, PTLRPC_SEC_FL_REVERSE, PTLRPC_SEC_FL_ROOTONLY, PTLRPC_SEC_FL_UDESC, and strlcat().
Referenced by sptlrpc_info_lprocfs_seq_show().
static int sptlrpc_ctxs_lprocfs_seq_show (struct seq_file * seq, void * v) [static]
Definition at line 119 of file sec_lproc.c.
References client_obd::cl_import, obd_device::cli, ptlrpc_sec_cops::display, LASSERT, LUSTRE_LWP_NAME, LUSTRE_MDC_NAME, LUSTRE_MGC_NAME, LUSTRE_OSC_NAME, LUSTRE_OSP_NAME, obd_device::obd_type, ptlrpc_sec::ps_policy, ptlrpc_sec_policy::sp_cops, sptlrpc_import_sec_ref(), sptlrpc_sec_put(), obd_type::typ_name, and obd_device::u.
static int sptlrpc_info_lprocfs_seq_show (struct seq_file * seq, void * v) [static]
Definition at line 78 of file sec_lproc.c.
References cfs_time_current_sec(), client_obd::cl_import, obd_device::cli, LASSERT, LUSTRE_LWP_NAME, LUSTRE_MDC_NAME, LUSTRE_MGC_NAME, LUSTRE_OSC_NAME, LUSTRE_OSP_NAME, obd_device::obd_type, ptlrpc_sec::ps_flvr, ptlrpc_sec::ps_gc_interval, ptlrpc_sec::ps_gc_next, ptlrpc_sec::ps_id, ptlrpc_sec::ps_nctx, ptlrpc_sec::ps_refcount, sec_flags2str(), sptlrpc_flavor::sf_flags, sptlrpc_flavor::sf_rpc, sptlrpc_flavor2name_base(), sptlrpc_flavor2name_bulk(), sptlrpc_import_sec_ref(), sptlrpc_sec_put(), obd_type::typ_name, and obd_device::u.
void sptlrpc_lproc_fini (void)
Definition at line 202 of file sec_lproc.c.
References lprocfs_remove(), and sptlrpc_proc_root.
Referenced by sptlrpc_fini().
int sptlrpc_lproc_init (void)
Definition at line 186 of file sec_lproc.c.
References LASSERT, lprocfs_register(), proc_lustre_root, and sptlrpc_proc_root.
Referenced by sptlrpc_init().
Variable Documentation
struct lprocfs_vars sptlrpc_lprocfs_vars[] [static]
Initial value:
 {
        { .name =       "encrypt_page_pools",
          .fops =       &sptlrpc_proc_enc_pool_fops     },
        { NULL }
}
Definition at line 180 of file sec_lproc.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.