Lustre: lnet/selftest/selftest.h File Reference
lnet/selftest/selftest.h File Reference
#include <libcfs/libcfs.h>
#include <lnet/api.h>
#include <lnet/lib-lnet.h>
#include <lnet/lib-types.h>
#include <lnet/lnetst.h>
#include "rpc.h"
#include "timer.h"
Data Structures
struct srpc_event_t
struct srpc_bulk_t
struct srpc_buffer
struct swi_workitem
struct srpc_server_rpc
struct srpc_client_rpc
struct srpc_service_cd
struct srpc_service
struct sfw_session_t
struct sfw_batch_t
struct sfw_test_client_ops_t
struct sfw_test_instance
struct sfw_test_unit
struct sfw_test_case
Defines
#define LNET_ONLY
#define SWI_STATE_NEWBORN 0
#define SWI_STATE_REPLY_SUBMITTED 1
#define SWI_STATE_REPLY_SENT 2
#define SWI_STATE_REQUEST_SUBMITTED 3
#define SWI_STATE_REQUEST_SENT 4
#define SWI_STATE_REPLY_RECEIVED 5
#define SWI_STATE_BULK_STARTED 6
#define SWI_STATE_DONE 10
#define SRPC_SERVICE_DEBUG 0
#define SRPC_SERVICE_MAKE_SESSION 1
#define SRPC_SERVICE_REMOVE_SESSION 2
#define SRPC_SERVICE_BATCH 3
#define SRPC_SERVICE_TEST 4
#define SRPC_SERVICE_QUERY_STAT 5
#define SRPC_SERVICE_JOIN 6
#define SRPC_FRAMEWORK_SERVICE_MAX_ID 10
#define SRPC_SERVICE_BRW 11
#define SRPC_SERVICE_PING 12
#define SRPC_SERVICE_MAX_ID 12
#define SRPC_REQUEST_PORTAL 50
#define SRPC_FRAMEWORK_REQUEST_PORTAL 51
#define SRPC_RDMA_PORTAL 52
#define srpc_client_rpc_size(rpc) offsetof(srpc_client_rpc_t, crpc_bulk.bk_iovs[(rpc)->crpc_bulk.bk_niov])
#define srpc_client_rpc_addref(rpc)
#define srpc_client_rpc_decref(rpc)
#define srpc_event_pending(rpc)
#define SFW_TEST_WI_MIN 256
#define SFW_TEST_WI_MAX 2048
#define SFW_TEST_WI_EXTRA 64
#define SFW_FRWK_WI_MIN 16
#define SFW_FRWK_WI_MAX 256
#define sfw_sid_equal(sid0, sid1)
#define SFW_MAX_CONCUR LST_MAX_CONCUR
#define SFW_ID_PER_PAGE (PAGE_CACHE_SIZE / sizeof(lnet_process_id_packed_t))
#define SFW_MAX_NDESTS (LNET_MAX_IOV * SFW_ID_PER_PAGE)
#define sfw_id_pages(n) (((n) + SFW_ID_PER_PAGE - 1) / SFW_ID_PER_PAGE)
#define STATE2STR(x) case x: return #x
#define lst_wait_until(cond, lock, fmt,...)
Typedefs
typedef struct srpc_buffer srpc_buffer_t
typedef int(* swi_action_t)(struct swi_workitem *)
typedef struct swi_workitem swi_workitem_t
typedef struct srpc_server_rpc srpc_server_rpc_t
typedef struct srpc_client_rpc srpc_client_rpc_t
typedef struct srpc_service srpc_service_t
typedef struct sfw_test_instance sfw_test_instance_t
typedef struct sfw_test_unit sfw_test_unit_t
typedef struct sfw_test_case sfw_test_case_t
Enumerations
enum srpc_event_type_t {
SRPC_BULK_REQ_RCVD = 1, SRPC_BULK_PUT_SENT = 2, SRPC_BULK_GET_RPLD = 3, SRPC_REPLY_RCVD = 4,
SRPC_REPLY_SENT = 5, SRPC_REQUEST_RCVD = 6, SRPC_REQUEST_SENT = 7
}
Functions
static srpc_msg_type_t srpc_service2request (int service)
static srpc_msg_type_t srpc_service2reply (int service)
srpc_client_rpc_t * sfw_create_rpc (lnet_process_id_t peer, int service, unsigned features, int nbulkiov, int bulklen, void(*done)(srpc_client_rpc_t *), void *priv)
int sfw_create_test_rpc (sfw_test_unit_t *tsu, lnet_process_id_t peer, unsigned features, int nblk, int blklen, srpc_client_rpc_t **rpc)
void sfw_abort_rpc (srpc_client_rpc_t *rpc)
void sfw_post_rpc (srpc_client_rpc_t *rpc)
void sfw_client_rpc_done (srpc_client_rpc_t *rpc)
void sfw_unpack_message (srpc_msg_t *msg)
void sfw_free_pages (srpc_server_rpc_t *rpc)
void sfw_add_bulk_page (srpc_bulk_t *bk, struct page *pg, int i)
int sfw_alloc_pages (srpc_server_rpc_t *rpc, int cpt, int npages, int len, int sink)
int sfw_make_session (srpc_mksn_reqst_t *request, srpc_mksn_reply_t *reply)
srpc_client_rpc_t * srpc_create_client_rpc (lnet_process_id_t peer, int service, int nbulkiov, int bulklen, void(*rpc_done)(srpc_client_rpc_t *), void(*rpc_fini)(srpc_client_rpc_t *), void *priv)
void srpc_post_rpc (srpc_client_rpc_t *rpc)
void srpc_abort_rpc (srpc_client_rpc_t *rpc, int why)
void srpc_free_bulk (srpc_bulk_t *bk)
srpc_bulk_t * srpc_alloc_bulk (int cpt, unsigned bulk_npg, unsigned bulk_len, int sink)
int srpc_send_rpc (swi_workitem_t *wi)
int srpc_send_reply (srpc_server_rpc_t *rpc)
int srpc_add_service (srpc_service_t *sv)
int srpc_remove_service (srpc_service_t *sv)
void srpc_shutdown_service (srpc_service_t *sv)
void srpc_abort_service (srpc_service_t *sv)
int srpc_finish_service (srpc_service_t *sv)
int srpc_service_add_buffers (srpc_service_t *sv, int nbuffer)
void srpc_service_remove_buffers (srpc_service_t *sv, int nbuffer)
void srpc_get_counters (srpc_counters_t *cnt)
void srpc_set_counters (const srpc_counters_t *cnt)
static int srpc_serv_is_framework (struct srpc_service *svc)
static int swi_wi_action (struct cfs_workitem *wi)
static void swi_init_workitem (swi_workitem_t *swi, void *data, swi_action_t action, struct cfs_wi_sched *sched)
static void swi_schedule_workitem (swi_workitem_t *wi)
static void swi_exit_workitem (swi_workitem_t *swi)
static int swi_deschedule_workitem (swi_workitem_t *swi)
int sfw_startup (void)
int srpc_startup (void)
void sfw_shutdown (void)
void srpc_shutdown (void)
static void srpc_destroy_client_rpc (srpc_client_rpc_t *rpc)
static void srpc_init_client_rpc (srpc_client_rpc_t *rpc, lnet_process_id_t peer, int service, int nbulkiov, int bulklen, void(*rpc_done)(srpc_client_rpc_t *), void(*rpc_fini)(srpc_client_rpc_t *), void *priv)
static const char * swi_state2str (int state)
static void srpc_wait_service_shutdown (srpc_service_t *sv)
void ping_init_test_client (void)
void ping_init_test_service (void)
void brw_init_test_client (void)
void brw_init_test_service (void)
Variables
struct cfs_wi_sched * lst_sched_serial
struct cfs_wi_sched ** lst_sched_test
sfw_test_client_ops_t ping_test_client
srpc_service_t ping_test_service
sfw_test_client_ops_t brw_test_client
srpc_service_t brw_test_service
Define Documentation
#define LNET_ONLY
Definition at line 44 of file selftest.h.
#define lst_wait_until (cond, lock, fmt, ...)
Value:
do {                                                                    \
        int __I = 2;                                                    \
        while (!(cond)) {                                               \
                CDEBUG(IS_PO2(++__I) ? D_WARNING : D_NET,               \
                       fmt, ## __VA_ARGS__);                            \
                spin_unlock(&(lock));                                   \
                                                                        \
                set_current_state(TASK_UNINTERRUPTIBLE);                \
                schedule_timeout(cfs_time_seconds(1) / 10);             \
                                                                        \
                spin_lock(&(lock));                                     \
        }                                                               \
} while (0)
Definition at line 577 of file selftest.h.
Referenced by lstcon_rpc_cleanup_wait(), sfw_shutdown(), srpc_service_add_buffers(), and stt_shutdown().
#define SFW_FRWK_WI_MAX 256
Definition at line 308 of file selftest.h.
Referenced by lstcon_init_acceptor_service(), and sfw_startup().
#define SFW_FRWK_WI_MIN 16
Definition at line 307 of file selftest.h.
Referenced by srpc_service_nrpcs().
#define sfw_id_pages (n) (((n) + SFW_ID_PER_PAGE - 1) / SFW_ID_PER_PAGE)
Definition at line 397 of file selftest.h.
Referenced by lstcon_testrpc_prep(), and sfw_add_test().
#define SFW_ID_PER_PAGE (PAGE_CACHE_SIZE / sizeof(lnet_process_id_packed_t))
Definition at line 395 of file selftest.h.
Referenced by lstcon_next_id(), and sfw_add_test_instance().
#define SFW_MAX_CONCUR LST_MAX_CONCUR
Definition at line 394 of file selftest.h.
Referenced by sfw_add_test().
#define SFW_MAX_NDESTS (LNET_MAX_IOV * SFW_ID_PER_PAGE)
Definition at line 396 of file selftest.h.
Referenced by sfw_add_test().
#define sfw_sid_equal (sid0, sid1)
Value:
((sid0).ses_nid == (sid1).ses_nid && \
                                       (sid0).ses_stamp == (sid1).ses_stamp)
Definition at line 343 of file selftest.h.
Referenced by sfw_add_test(), sfw_control_batch(), sfw_get_stats(), sfw_make_session(), and sfw_remove_session().
#define SFW_TEST_WI_EXTRA 64
Definition at line 304 of file selftest.h.
Referenced by sfw_test_buffers().
#define SFW_TEST_WI_MAX 2048
Definition at line 301 of file selftest.h.
#define SFW_TEST_WI_MIN 256
Definition at line 300 of file selftest.h.
Referenced by sfw_test_buffers(), srpc_lnet_ev_handler(), and srpc_service_nrpcs().
#define srpc_client_rpc_addref (rpc)
Value:
do {                                                                    \
        CDEBUG(D_NET, "RPC[%p] -> %s (%d)++\n",                         \
               (rpc), libcfs_id2str((rpc)->crpc_dest),                  \
               atomic_read(&(rpc)->crpc_refcount));                 \
        LASSERT(atomic_read(&(rpc)->crpc_refcount) > 0);            \
        atomic_inc(&(rpc)->crpc_refcount);                          \
} while (0)
Definition at line 240 of file selftest.h.
#define srpc_client_rpc_decref (rpc)
Value:
do {                                                                    \
        CDEBUG(D_NET, "RPC[%p] -> %s (%d)--\n",                         \
               (rpc), libcfs_id2str((rpc)->crpc_dest),                  \
               atomic_read(&(rpc)->crpc_refcount));                 \
        LASSERT(atomic_read(&(rpc)->crpc_refcount) > 0);            \
        if (atomic_dec_and_test(&(rpc)->crpc_refcount))             \
                srpc_destroy_client_rpc(rpc);                           \
} while (0)
Definition at line 249 of file selftest.h.
Referenced by lstcon_rpc_put(), and sfw_test_rpc_done().
#define srpc_client_rpc_size (rpc) offsetof(srpc_client_rpc_t, crpc_bulk.bk_iovs[(rpc)->crpc_bulk.bk_niov])
Definition at line 237 of file selftest.h.
Referenced by sfw_destroy_test_instance(), sfw_shutdown(), and srpc_destroy_client_rpc().
#define srpc_event_pending (rpc)
Value:
((rpc)->crpc_bulkev.ev_fired == 0 ||  \
                                   (rpc)->crpc_reqstev.ev_fired == 0 || \
                                   (rpc)->crpc_replyev.ev_fired == 0)
Definition at line 259 of file selftest.h.
Referenced by srpc_client_rpc_done(), srpc_destroy_client_rpc(), and srpc_send_rpc().
#define SRPC_FRAMEWORK_REQUEST_PORTAL 51
Definition at line 93 of file selftest.h.
Referenced by srpc_serv_portal(), srpc_shutdown(), and srpc_startup().
#define SRPC_FRAMEWORK_SERVICE_MAX_ID 10
Definition at line 85 of file selftest.h.
Referenced by sfw_abort_rpc(), sfw_add_test(), sfw_create_rpc(), sfw_find_test_case(), sfw_handle_server_rpc(), srpc_serv_is_framework(), and srpc_serv_portal().
#define SRPC_RDMA_PORTAL 52
Definition at line 95 of file selftest.h.
Referenced by srpc_do_bulk(), srpc_prepare_bulk(), srpc_prepare_reply(), and srpc_send_reply().
#define SRPC_REQUEST_PORTAL 50
Definition at line 91 of file selftest.h.
Referenced by srpc_serv_portal(), srpc_shutdown(), and srpc_startup().
#define SRPC_SERVICE_BATCH 3
Definition at line 81 of file selftest.h.
Referenced by lstcon_batrpc_prep(), sfw_handle_server_rpc(), and srpc_service2request().
#define SRPC_SERVICE_BRW 11
Definition at line 87 of file selftest.h.
Referenced by brw_init_test_service(), brw_server_handle(), lstcon_testrpc_prep(), sfw_unpack_addtest_req(), and srpc_service2request().
#define SRPC_SERVICE_DEBUG 0
Definition at line 78 of file selftest.h.
Referenced by lstcon_dbgrpc_prep(), lstcon_rpc_pinger(), sfw_handle_server_rpc(), and srpc_service2request().
#define SRPC_SERVICE_JOIN 6
Definition at line 84 of file selftest.h.
Referenced by lstcon_init_acceptor_service(), and srpc_service2request().
#define SRPC_SERVICE_MAKE_SESSION 1
Definition at line 79 of file selftest.h.
Referenced by lstcon_sesrpc_prep(), sfw_handle_server_rpc(), and srpc_service2request().
#define SRPC_SERVICE_MAX_ID 12
Definition at line 89 of file selftest.h.
Referenced by sfw_add_test(), sfw_find_test_case(), srpc_add_service(), and srpc_shutdown().
#define SRPC_SERVICE_PING 12
Definition at line 88 of file selftest.h.
Referenced by lstcon_testrpc_prep(), ping_init_test_service(), ping_server_handle(), sfw_unpack_addtest_req(), and srpc_service2request().
#define SRPC_SERVICE_QUERY_STAT 5
Definition at line 83 of file selftest.h.
Referenced by lstcon_statrpc_prep(), sfw_handle_server_rpc(), and srpc_service2request().
#define SRPC_SERVICE_REMOVE_SESSION 2
Definition at line 80 of file selftest.h.
Referenced by lstcon_sesrpc_prep(), sfw_handle_server_rpc(), and srpc_service2request().
#define SRPC_SERVICE_TEST 4
Definition at line 82 of file selftest.h.
Referenced by lstcon_testrpc_prep(), sfw_bulk_ready(), sfw_handle_server_rpc(), sfw_startup(), and srpc_service2request().
#define STATE2STR (x) case x: return #x
Referenced by swi_state2str().
#define SWI_STATE_BULK_STARTED 6
Definition at line 66 of file selftest.h.
Referenced by srpc_handle_rpc(), and swi_state2str().
#define SWI_STATE_DONE 10
Definition at line 67 of file selftest.h.
Referenced by srpc_client_rpc_done(), srpc_handle_rpc(), srpc_send_rpc(), srpc_server_rpc_done(), and swi_state2str().
#define SWI_STATE_NEWBORN 0
Definition at line 60 of file selftest.h.
Referenced by srpc_handle_rpc(), srpc_send_rpc(), swi_init_workitem(), and swi_state2str().
#define SWI_STATE_REPLY_RECEIVED 5
Definition at line 65 of file selftest.h.
Referenced by srpc_send_rpc(), and swi_state2str().
#define SWI_STATE_REPLY_SENT 2
Definition at line 62 of file selftest.h.
Referenced by swi_state2str().
#define SWI_STATE_REPLY_SUBMITTED 1
Definition at line 61 of file selftest.h.
Referenced by srpc_handle_rpc(), and swi_state2str().
#define SWI_STATE_REQUEST_SENT 4
Definition at line 64 of file selftest.h.
Referenced by srpc_send_rpc(), and swi_state2str().
#define SWI_STATE_REQUEST_SUBMITTED 3
Definition at line 63 of file selftest.h.
Referenced by srpc_send_rpc(), and swi_state2str().
Typedef Documentation
typedef struct sfw_test_case sfw_test_case_t
typedef struct sfw_test_instance sfw_test_instance_t
typedef struct sfw_test_unit sfw_test_unit_t
typedef struct srpc_buffer srpc_buffer_t
typedef struct srpc_client_rpc srpc_client_rpc_t
typedef struct srpc_server_rpc srpc_server_rpc_t
typedef struct srpc_service srpc_service_t
typedef int(* swi_action_t)(struct swi_workitem *)
Definition at line 175 of file selftest.h.
typedef struct swi_workitem swi_workitem_t
Enumeration Type Documentation
enum srpc_event_type_t
Enumerator:
SRPC_BULK_REQ_RCVD
SRPC_BULK_PUT_SENT
SRPC_BULK_GET_RPLD
SRPC_REPLY_RCVD
SRPC_REPLY_SENT
SRPC_REQUEST_RCVD
SRPC_REQUEST_SENT
Definition at line 138 of file selftest.h.
Function Documentation
void brw_init_test_client (void)
Definition at line 484 of file brw_test.c.
References brw_client_done_rpc(), brw_client_fini(), brw_client_init(), brw_client_prep_rpc(), sfw_test_client_ops_t::tso_done_rpc, sfw_test_client_ops_t::tso_fini, sfw_test_client_ops_t::tso_init, and sfw_test_client_ops_t::tso_prep_rpc.
Referenced by sfw_startup().
void brw_init_test_service (void)
Definition at line 493 of file brw_test.c.
References brw_bulk_ready(), brw_server_handle(), brw_srv_workitems, SRPC_SERVICE_BRW, srpc_service::sv_bulk_ready, srpc_service::sv_handler, srpc_service::sv_id, srpc_service::sv_name, and srpc_service::sv_wi_total.
Referenced by sfw_startup().
void ping_init_test_client (void)
Definition at line 215 of file ping_test.c.
References ping_client_done_rpc(), ping_client_fini(), ping_client_init(), ping_client_prep_rpc(), sfw_test_client_ops_t::tso_done_rpc, sfw_test_client_ops_t::tso_fini, sfw_test_client_ops_t::tso_init, and sfw_test_client_ops_t::tso_prep_rpc.
Referenced by sfw_startup().
void ping_init_test_service (void)
Definition at line 224 of file ping_test.c.
References ping_server_handle(), ping_srv_workitems, SRPC_SERVICE_PING, srpc_service::sv_handler, srpc_service::sv_id, srpc_service::sv_name, and srpc_service::sv_wi_total.
Referenced by sfw_startup().
void sfw_abort_rpc (srpc_client_rpc_t * rpc)
Definition at line 1582 of file framework.c.
References srpc_client_rpc::crpc_lock, srpc_client_rpc::crpc_refcount, srpc_client_rpc::crpc_service, LASSERT, srpc_abort_rpc(), and SRPC_FRAMEWORK_SERVICE_MAX_ID.
Referenced by lstcon_rpc_trans_abort().
void sfw_add_bulk_page (srpc_bulk_t * bk, struct page * pg, int i)
int sfw_alloc_pages (srpc_server_rpc_t * rpc, int cpt, int npages, int len, int sink)
Definition at line 1122 of file framework.c.
References LASSERT, LNET_MAX_IOV, srpc_alloc_bulk(), and srpc_server_rpc::srpc_bulk.
Referenced by brw_server_handle(), and sfw_add_test().
void sfw_client_rpc_done (srpc_client_rpc_t * rpc)
srpc_client_rpc_t* sfw_create_rpc (lnet_process_id_t peer, int service, unsigned features, int nbulkiov, int bulklen, void(*)(srpc_client_rpc_t *) done, void * priv)
Definition at line 1401 of file framework.c.
References srpc_client_rpc::crpc_list, srpc_client_rpc::crpc_reqstmsg, done, smoketest_framework::fw_lock, smoketest_framework::fw_shuttingdown, smoketest_framework::fw_zombie_rpcs, LASSERT, list_del(), list_empty(), list_entry, srpc_msg::msg_ses_feats, list_head::next, sfw_client_rpc_fini(), sfw_data, srpc_create_client_rpc(), SRPC_FRAMEWORK_SERVICE_MAX_ID, and srpc_init_client_rpc().
Referenced by lstcon_rpc_init().
int sfw_create_test_rpc (sfw_test_unit_t * tsu, lnet_process_id_t peer, unsigned features, int nblk, int blklen, srpc_client_rpc_t ** rpc)
Definition at line 921 of file framework.c.
References srpc_bulk_t::bk_niov, CERROR, srpc_client_rpc::crpc_bulk, srpc_client_rpc::crpc_list, srpc_client_rpc::crpc_reqstmsg, LASSERT, list_del_init(), list_empty(), list_entry, srpc_msg::msg_ses_feats, list_head::next, sfw_test_active, sfw_test_rpc_done(), sfw_test_rpc_fini(), srpc_create_client_rpc(), srpc_init_client_rpc(), sfw_test_instance::tsi_free_rpcs, sfw_test_instance::tsi_lock, sfw_test_instance::tsi_service, and sfw_test_unit::tsu_instance.
Referenced by brw_client_prep_rpc(), and ping_client_prep_rpc().
void sfw_free_pages (srpc_server_rpc_t * rpc)
Definition at line 1115 of file framework.c.
References srpc_server_rpc::srpc_bulk, and srpc_free_bulk().
Referenced by brw_server_rpc_done(), and sfw_server_rpc_done().
int sfw_make_session (srpc_mksn_reqst_t * request, srpc_mksn_reply_t * reply)
Definition at line 422 of file framework.c.
References CERROR, smoketest_framework::fw_lock, smoketest_framework::fw_session, LASSERT, LIBCFS_ALLOC, LNET_NID_ANY, LST_FEATS_MASK, msg, srpc_msg::msg_ses_feats, sfw_data, sfw_deactivate_session(), sfw_init_session(), sfw_sid_equal, sfw_session_t::sn_id, sfw_session_t::sn_name, sfw_session_t::sn_refcount, sfw_session_t::sn_timeout, and strlcpy().
Referenced by sfw_handle_server_rpc().
void sfw_post_rpc (srpc_client_rpc_t * rpc)
Definition at line 1594 of file framework.c.
References srpc_client_rpc::crpc_aborted, srpc_client_rpc::crpc_closed, srpc_client_rpc::crpc_list, srpc_client_rpc::crpc_lock, srpc_client_rpc::crpc_timeout, smoketest_framework::fw_shuttingdown, LASSERT, list_empty(), rpc_timeout, sfw_data, and srpc_post_rpc().
Referenced by lstcon_rpc_post().
void sfw_shutdown (void)
Definition at line 1748 of file framework.c.
References srpc_client_rpc::crpc_list, smoketest_framework::fw_active_srpc, smoketest_framework::fw_lock, smoketest_framework::fw_nzombies, smoketest_framework::fw_session, smoketest_framework::fw_shuttingdown, smoketest_framework::fw_tests, smoketest_framework::fw_zombie_rpcs, LIBCFS_FREE, list_del(), list_empty(), list_entry, list_for_each_entry, lst_wait_until, list_head::next, sfw_data, sfw_deactivate_session(), sfw_del_session_timer(), srpc_client_rpc_size, srpc_remove_service(), srpc_shutdown_service(), srpc_wait_service_shutdown(), srpc_service::sv_name, sfw_test_case::tsc_list, and sfw_test_case::tsc_srv_service.
Referenced by lnet_selftest_exit(), and sfw_startup().
int sfw_startup (void)
Definition at line 1650 of file framework.c.
References brw_init_test_client(), brw_init_test_service(), brw_test_client, brw_test_service, CERROR, CWARN, error, smoketest_framework::fw_active_srpc, smoketest_framework::fw_lock, smoketest_framework::fw_nzombies, smoketest_framework::fw_session, smoketest_framework::fw_tests, smoketest_framework::fw_zombie_rpcs, smoketest_framework::fw_zombie_sessions, INIT_LIST_HEAD, LASSERT, list_for_each_entry, ping_init_test_client(), ping_init_test_service(), ping_test_client, ping_test_service, rpc_timeout, session_timeout, sfw_bulk_ready(), sfw_data, SFW_FRWK_WI_MAX, sfw_handle_server_rpc(), sfw_register_test(), sfw_shutdown(), srpc_add_service(), srpc_service_add_buffers(), SRPC_SERVICE_TEST, srpc_service::sv_bulk_ready, srpc_service::sv_handler, srpc_service::sv_id, srpc_service::sv_name, srpc_service::sv_wi_total, and sfw_test_case::tsc_srv_service.
Referenced by lnet_selftest_init().
void sfw_unpack_message (srpc_msg_t * msg)
Definition at line 1438 of file framework.c.
References __swab32, __swab32s, __swab64s, srpc_msg::bat_reply, srpc_msg::bat_reqst, srpc_msg::dbg_reply, srpc_msg::dbg_reqst, srpc_msg::join_reply, srpc_msg::join_reqst, LASSERT, LBUG, srpc_msg::mksn_reply, srpc_msg::mksn_reqst, srpc_msg::msg_body, srpc_msg::msg_magic, srpc_msg::msg_type, srpc_msg::rmsn_reply, srpc_msg::rmsn_reqst, sfw_unpack_fw_counters, sfw_unpack_lnet_counters, sfw_unpack_rpc_counters, sfw_unpack_sid, SRPC_MSG_BATCH_REPLY, SRPC_MSG_BATCH_REQST, SRPC_MSG_DEBUG_REPLY, SRPC_MSG_DEBUG_REQST, SRPC_MSG_JOIN_REPLY, SRPC_MSG_JOIN_REQST, SRPC_MSG_MAGIC, SRPC_MSG_MKSN_REPLY, SRPC_MSG_MKSN_REQST, SRPC_MSG_RMSN_REPLY, SRPC_MSG_RMSN_REQST, SRPC_MSG_STAT_REPLY, SRPC_MSG_STAT_REQST, SRPC_MSG_TEST_REPLY, SRPC_MSG_TEST_REQST, srpc_msg::stat_reply, srpc_msg::stat_reqst, srpc_msg::tes_reply, and srpc_msg::tes_reqst.
Referenced by lstcon_acceptor_handle(), lstcon_rpc_get_reply(), and sfw_handle_server_rpc().
void srpc_abort_rpc (srpc_client_rpc_t * rpc, int why)
Definition at line 1311 of file rpc.c.
References CDEBUG, srpc_client_rpc::crpc_aborted, srpc_client_rpc::crpc_closed, srpc_client_rpc::crpc_dest, srpc_client_rpc::crpc_service, srpc_client_rpc::crpc_status, srpc_client_rpc::crpc_wi, D_NET, LASSERT, libcfs_id2str(), swi_schedule_workitem(), swi_workitem::swi_state, and swi_state2str().
Referenced by sfw_abort_rpc(), sfw_stop_batch(), srpc_client_rpc_expired(), and srpc_send_rpc().
void srpc_abort_service (srpc_service_t * sv)
Definition at line 723 of file rpc.c.
References CDEBUG, cfs_percpt_for_each, D_NET, list_for_each_entry, srpc_service_cd::scd_lock, srpc_service_cd::scd_rpc_active, srpc_server_rpc::srpc_aborted, srpc_server_rpc::srpc_list, srpc_server_rpc::srpc_wi, srpc_service::sv_cpt_data, srpc_service::sv_id, srpc_service::sv_name, and swi_schedule_workitem().
Referenced by sfw_deactivate_session().
int srpc_add_service (srpc_service_t * sv)
Definition at line 307 of file rpc.c.
References CDEBUG, D_NET, LASSERT, smoketest_rpc::rpc_glock, smoketest_rpc::rpc_services, smoketest_rpc::rpc_state, srpc_data, srpc_service_fini(), srpc_service_init(), SRPC_SERVICE_MAX_ID, SRPC_STATE_RUNNING, srpc_service::sv_id, and srpc_service::sv_name.
Referenced by lstcon_console_init(), and sfw_startup().
srpc_bulk_t* srpc_alloc_bulk (int cpt, unsigned bulk_npg, unsigned bulk_len, int sink)
Definition at line 124 of file rpc.c.
References srpc_bulk_t::bk_len, srpc_bulk_t::bk_niov, srpc_bulk_t::bk_sink, CERROR, cfs_page_cpt_alloc(), LASSERT, LIBCFS_CPT_ALLOC, lnet_cpt_table, LNET_MAX_IOV, offsetof, srpc_add_bulk_page(), and srpc_free_bulk().
Referenced by brw_client_init(), and sfw_alloc_pages().
srpc_client_rpc_t* srpc_create_client_rpc (lnet_process_id_t peer, int service, int nbulkiov, int bulklen, void(*)(srpc_client_rpc_t *) rpc_done, void(*)(srpc_client_rpc_t *) rpc_fini, void * priv)
Definition at line 1292 of file rpc.c.
References LIBCFS_ALLOC, offsetof, and srpc_init_client_rpc().
Referenced by sfw_create_rpc(), and sfw_create_test_rpc().
static void srpc_destroy_client_rpc (srpc_client_rpc_t * rpc) [inline, static]
Definition at line 504 of file selftest.h.
References srpc_client_rpc::crpc_fini, srpc_client_rpc::crpc_refcount, LASSERT, LIBCFS_FREE, srpc_client_rpc_size, and srpc_event_pending.
int srpc_finish_service (srpc_service_t * sv)
Definition at line 643 of file rpc.c.
References CDEBUG, cfs_percpt_for_each, CNETERR, D_NET, srpc_event_t::ev_fired, srpc_event_t::ev_lnet, srpc_event_t::ev_status, srpc_event_t::ev_type, LASSERT, libcfs_id2str(), list_empty(), list_entry, list_head::next, srpc_service_cd::scd_buf_nposted, srpc_service_cd::scd_buf_wi, srpc_service_cd::scd_lock, srpc_service_cd::scd_rpc_active, srpc_server_rpc::srpc_ev, srpc_server_rpc::srpc_list, srpc_server_rpc::srpc_peer, srpc_service_fini(), srpc_server_rpc::srpc_wi, srpc_service::sv_cpt_data, srpc_service::sv_name, srpc_service::sv_shuttingdown, swi_deschedule_workitem(), swi_workitem::swi_state, swi_state2str(), swi_workitem::swi_workitem, cfs_workitem::wi_running, and cfs_workitem::wi_scheduled.
Referenced by srpc_wait_service_shutdown().
void srpc_free_bulk (srpc_bulk_t * bk)
Definition at line 105 of file rpc.c.
References srpc_bulk_t::bk_iovs, srpc_bulk_t::bk_niov, lnet_kiov_t::kiov_page, LASSERT, LIBCFS_FREE, and offsetof.
Referenced by brw_client_fini(), sfw_free_pages(), and srpc_alloc_bulk().
void srpc_get_counters (srpc_counters_t * cnt)
Definition at line 76 of file rpc.c.
References smoketest_rpc::rpc_counters, smoketest_rpc::rpc_glock, and srpc_data.
Referenced by sfw_get_stats().
static void srpc_init_client_rpc (srpc_client_rpc_t * rpc, lnet_process_id_t peer, int service, int nbulkiov, int bulklen, void(*)(srpc_client_rpc_t *) rpc_done, void(*)(srpc_client_rpc_t *) rpc_fini, void * priv) [inline, static]
Definition at line 520 of file selftest.h.
References srpc_bulk_t::bk_len, srpc_bulk_t::bk_mdh, srpc_bulk_t::bk_niov, srpc_client_rpc::crpc_bulk, srpc_client_rpc::crpc_bulkev, srpc_client_rpc::crpc_dest, srpc_client_rpc::crpc_done, srpc_client_rpc::crpc_fini, srpc_client_rpc::crpc_list, srpc_client_rpc::crpc_lock, srpc_client_rpc::crpc_priv, srpc_client_rpc::crpc_refcount, srpc_client_rpc::crpc_replyev, srpc_client_rpc::crpc_replymdh, srpc_client_rpc::crpc_reqstev, srpc_client_rpc::crpc_reqstmdh, srpc_client_rpc::crpc_reqstmsg, srpc_client_rpc::crpc_service, srpc_client_rpc::crpc_wi, srpc_event_t::ev_fired, INIT_LIST_HEAD, LASSERT, lnet_cpt_of_nid(), LNET_MAX_IOV, LNetInvalidateHandle(), srpc_msg::msg_magic, srpc_msg::msg_type, srpc_msg::msg_version, lnet_process_id_t::nid, offsetof, SRPC_MSG_MAGIC, SRPC_MSG_VERSION, srpc_send_rpc(), srpc_service2request(), and swi_init_workitem().
Referenced by sfw_create_rpc(), sfw_create_test_rpc(), and srpc_create_client_rpc().
void srpc_post_rpc (srpc_client_rpc_t * rpc)
Definition at line 1332 of file rpc.c.
References CDEBUG, srpc_client_rpc::crpc_aborted, srpc_client_rpc::crpc_dest, srpc_client_rpc::crpc_service, srpc_client_rpc::crpc_timeout, srpc_client_rpc::crpc_wi, D_NET, LASSERT, libcfs_id2str(), smoketest_rpc::rpc_state, srpc_add_client_rpc_timer(), srpc_data, SRPC_STATE_RUNNING, and swi_schedule_workitem().
Referenced by sfw_post_rpc(), and sfw_run_test().
int srpc_remove_service (srpc_service_t * sv)
Definition at line 337 of file rpc.c.
References smoketest_rpc::rpc_glock, smoketest_rpc::rpc_services, srpc_data, and srpc_service::sv_id.
Referenced by lstcon_console_fini(), lstcon_console_init(), and sfw_shutdown().
int srpc_send_reply (srpc_server_rpc_t * rpc)
Definition at line 1348 of file rpc.c.
References __u64, srpc_buffer::buf_msg, CWARN, srpc_event_t::ev_data, srpc_event_t::ev_fired, srpc_event_t::ev_type, LASSERT, LNET_MD_OP_PUT, msg, srpc_msg::msg_body, srpc_msg::msg_magic, srpc_msg::msg_type, srpc_msg::msg_version, srpc_msg::reqst, srpc_service_cd::scd_lock, srpc_service_cd::scd_svc, srpc_server_rpc::srpc_ev, SRPC_MSG_MAGIC, SRPC_MSG_VERSION, srpc_server_rpc::srpc_peer, srpc_post_active_rdma(), SRPC_RDMA_PORTAL, SRPC_REPLY_SENT, srpc_server_rpc::srpc_replymdh, srpc_server_rpc::srpc_replymsg, srpc_server_rpc::srpc_reqstbuf, srpc_server_rpc::srpc_scd, srpc_server_rpc::srpc_self, srpc_serv_is_framework(), srpc_service2reply(), srpc_service_post_buffer(), srpc_service::sv_id, srpc_service::sv_name, and srpc_service::sv_shuttingdown.
Referenced by srpc_handle_rpc().
int srpc_send_rpc (swi_workitem_t * wi)
Definition at line 1166 of file rpc.c.
References __swab32, srpc_bulk_t::bk_mdh, srpc_bulk_t::bk_niov, srpc_client_rpc::crpc_aborted, srpc_client_rpc::crpc_bulk, srpc_client_rpc::crpc_bulkev, srpc_client_rpc::crpc_dest, srpc_client_rpc::crpc_lock, srpc_client_rpc::crpc_replyev, srpc_client_rpc::crpc_replymdh, srpc_client_rpc::crpc_replymsg, srpc_client_rpc::crpc_reqstev, srpc_client_rpc::crpc_reqstmdh, srpc_client_rpc::crpc_service, srpc_client_rpc::crpc_status, srpc_client_rpc::crpc_wi, CWARN, srpc_event_t::ev_fired, srpc_event_t::ev_lnet, srpc_event_t::ev_status, LASSERT, LBUG, libcfs_id2str(), LNET_EVENT_UNLINK, LNetMDUnlink(), srpc_msg::msg_body, srpc_msg::msg_magic, srpc_msg::msg_type, srpc_msg::reply, srpc_abort_rpc(), srpc_client_rpc_done(), srpc_event_pending, SRPC_MSG_MAGIC, srpc_prepare_bulk(), srpc_prepare_reply(), srpc_send_request(), srpc_service2reply(), srpc_unpack_msg_hdr(), swi_workitem::swi_state, SWI_STATE_DONE, SWI_STATE_NEWBORN, SWI_STATE_REPLY_RECEIVED, SWI_STATE_REQUEST_SENT, SWI_STATE_REQUEST_SUBMITTED, swi_workitem::swi_workitem, and cfs_workitem::wi_data.
Referenced by srpc_init_client_rpc().
static int srpc_serv_is_framework (struct srpc_service * svc) [inline, static]
Definition at line 457 of file selftest.h.
References SRPC_FRAMEWORK_SERVICE_MAX_ID, and srpc_service::sv_id.
Referenced by sfw_load_test(), srpc_init_server_rpc(), srpc_send_reply(), srpc_service_add_buffers(), srpc_service_init(), srpc_service_nrpcs(), and srpc_service_post_buffer().
static srpc_msg_type_t srpc_service2reply (int service) [inline, static]
Definition at line 133 of file selftest.h.
References srpc_service2request().
Referenced by srpc_send_reply(), and srpc_send_rpc().
static srpc_msg_type_t srpc_service2request (int service) [inline, static]
Definition at line 98 of file selftest.h.
References LBUG, SRPC_MSG_BATCH_REQST, SRPC_MSG_BRW_REQST, SRPC_MSG_DEBUG_REQST, SRPC_MSG_JOIN_REQST, SRPC_MSG_MKSN_REQST, SRPC_MSG_PING_REQST, SRPC_MSG_RMSN_REQST, SRPC_MSG_STAT_REQST, SRPC_MSG_TEST_REQST, SRPC_SERVICE_BATCH, SRPC_SERVICE_BRW, SRPC_SERVICE_DEBUG, SRPC_SERVICE_JOIN, SRPC_SERVICE_MAKE_SESSION, SRPC_SERVICE_PING, SRPC_SERVICE_QUERY_STAT, SRPC_SERVICE_REMOVE_SESSION, and SRPC_SERVICE_TEST.
Referenced by brw_server_handle(), ping_server_handle(), sfw_handle_server_rpc(), srpc_init_client_rpc(), srpc_lnet_ev_handler(), and srpc_service2reply().
int srpc_service_add_buffers (srpc_service_t * sv, int nbuffer)
Definition at line 569 of file rpc.c.
References cfs_percpt_for_each, LASSERTF, lst_wait_until, srpc_service_cd::scd_buf_adjust, srpc_service_cd::scd_buf_err, srpc_service_cd::scd_buf_err_stamp, srpc_service_cd::scd_buf_posting, srpc_service_cd::scd_buf_wi, srpc_service_cd::scd_lock, srpc_serv_is_framework(), srpc_service::sv_cpt_data, and swi_schedule_workitem().
Referenced by lstcon_console_init(), sfw_load_test(), and sfw_startup().
void srpc_service_remove_buffers (srpc_service_t * sv, int nbuffer)
Definition at line 623 of file rpc.c.
References cfs_percpt_for_each, LASSERT, srpc_service_cd::scd_buf_adjust, srpc_service_cd::scd_buf_posting, srpc_service_cd::scd_buf_total, srpc_service_cd::scd_lock, srpc_service::sv_cpt_data, and srpc_service::sv_shuttingdown.
Referenced by sfw_load_test(), and sfw_unload_test().
void srpc_set_counters (const srpc_counters_t * cnt)
Definition at line 83 of file rpc.c.
References smoketest_rpc::rpc_counters, smoketest_rpc::rpc_glock, and srpc_data.
void srpc_shutdown (void)
Definition at line 1630 of file rpc.c.
References LASSERT, LASSERTF, LBUG, LNetClearLazyPortal(), LNetEQFree(), LNetNIFini(), smoketest_rpc::rpc_glock, smoketest_rpc::rpc_lnet_eq, smoketest_rpc::rpc_services, smoketest_rpc::rpc_state, srpc_data, SRPC_FRAMEWORK_REQUEST_PORTAL, SRPC_REQUEST_PORTAL, SRPC_SERVICE_MAX_ID, SRPC_STATE_EQ_INIT, SRPC_STATE_NI_INIT, SRPC_STATE_RUNNING, SRPC_STATE_STOPPING, state, stt_shutdown(), and srpc_service::sv_name.
Referenced by lnet_selftest_exit(), and srpc_startup().
void srpc_shutdown_service (srpc_service_t * sv)
Definition at line 748 of file rpc.c.
References buf, srpc_buffer::buf_mdh, CDEBUG, cfs_percpt_for_each, D_NET, list_for_each_entry, LNetMDUnlink(), srpc_service_cd::scd_buf_posted, srpc_service_cd::scd_lock, srpc_service_cd::scd_rpc_active, srpc_server_rpc::srpc_list, srpc_server_rpc::srpc_wi, srpc_service::sv_cpt_data, srpc_service::sv_id, srpc_service::sv_name, srpc_service::sv_shuttingdown, and swi_schedule_workitem().
Referenced by lstcon_console_fini(), lstcon_console_init(), and sfw_shutdown().
int srpc_startup (void)
Definition at line 1582 of file rpc.c.
References __u64, CERROR, cfs_time_current_sec(), cfs_time_seconds(), LASSERT, LNET_PID_LUSTRE, LNetEQAlloc(), LNetInvalidateHandle(), LNetNIInit(), LNetSetLazyPortal(), smoketest_rpc::rpc_glock, smoketest_rpc::rpc_lnet_eq, smoketest_rpc::rpc_matchbits, smoketest_rpc::rpc_state, srpc_data, SRPC_FRAMEWORK_REQUEST_PORTAL, srpc_lnet_ev_handler(), SRPC_REQUEST_PORTAL, srpc_shutdown(), SRPC_STATE_EQ_INIT, SRPC_STATE_NI_INIT, SRPC_STATE_NONE, SRPC_STATE_RUNNING, and stt_startup().
Referenced by lnet_selftest_init().
static void srpc_wait_service_shutdown (srpc_service_t * sv) [inline, static]
Definition at line 593 of file selftest.h.
References CDEBUG, cfs_time_seconds(), D_NET, D_WARNING, LASSERT, srpc_finish_service(), srpc_service::sv_name, and srpc_service::sv_shuttingdown.
Referenced by lstcon_console_fini(), lstcon_console_init(), and sfw_shutdown().
static int swi_deschedule_workitem (swi_workitem_t * swi) [inline, static]
Definition at line 493 of file selftest.h.
References cfs_wi_deschedule(), swi_workitem::swi_sched, and swi_workitem::swi_workitem.
Referenced by srpc_finish_service().
static void swi_exit_workitem (swi_workitem_t * swi) [inline, static]
Definition at line 487 of file selftest.h.
References cfs_wi_exit(), swi_workitem::swi_sched, and swi_workitem::swi_workitem.
Referenced by sfw_run_test(), srpc_client_rpc_done(), and srpc_server_rpc_done().
static void swi_init_workitem (swi_workitem_t * swi, void * data, swi_action_t action, struct cfs_wi_sched * sched) [inline, static]
Definition at line 471 of file selftest.h.
References cfs_wi_init(), swi_workitem::swi_action, swi_workitem::swi_sched, swi_workitem::swi_state, SWI_STATE_NEWBORN, swi_wi_action(), and swi_workitem::swi_workitem.
Referenced by sfw_run_batch(), srpc_init_client_rpc(), srpc_init_server_rpc(), and srpc_service_init().
static void swi_schedule_workitem (swi_workitem_t * wi) [inline, static]
Definition at line 481 of file selftest.h.
References cfs_wi_schedule(), swi_workitem::swi_sched, and swi_workitem::swi_workitem.
Referenced by sfw_run_batch(), sfw_test_rpc_done(), srpc_abort_rpc(), srpc_abort_service(), srpc_lnet_ev_handler(), srpc_post_rpc(), srpc_server_rpc_done(), srpc_service_add_buffers(), and srpc_shutdown_service().
static const char* swi_state2str (int state) [inline, static]
Definition at line 559 of file selftest.h.
References LBUG, STATE2STR, SWI_STATE_BULK_STARTED, SWI_STATE_DONE, SWI_STATE_NEWBORN, SWI_STATE_REPLY_RECEIVED, SWI_STATE_REPLY_SENT, SWI_STATE_REPLY_SUBMITTED, SWI_STATE_REQUEST_SENT, and SWI_STATE_REQUEST_SUBMITTED.
Referenced by sfw_client_rpc_fini(), sfw_server_rpc_done(), srpc_abort_rpc(), srpc_client_rpc_done(), srpc_finish_service(), and srpc_server_rpc_done().
static int swi_wi_action (struct cfs_workitem * wi) [inline, static]
Definition at line 463 of file selftest.h.
References swi_workitem::swi_action.
Referenced by swi_init_workitem().
Variable Documentation
sfw_test_client_ops_t brw_test_client
Definition at line 483 of file brw_test.c.
Referenced by sfw_startup().
srpc_service_t brw_test_service
Definition at line 490 of file brw_test.c.
Referenced by sfw_startup().
struct cfs_wi_sched* lst_sched_serial
Definition at line 53 of file module.c.
Referenced by srpc_init_server_rpc().
struct cfs_wi_sched** lst_sched_test
Definition at line 54 of file module.c.
Referenced by sfw_run_batch(), srpc_init_server_rpc(), and srpc_service_init().
sfw_test_client_ops_t ping_test_client
Definition at line 214 of file ping_test.c.
Referenced by sfw_startup().
srpc_service_t ping_test_service
Definition at line 223 of file ping_test.c.
Referenced by sfw_startup().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.