Lustre: lustre/tests/sendfile_grouplock.c File Reference
lustre/tests/sendfile_grouplock.c File Reference
#include <stdlib.h>
#include <errno.h>
#include <getopt.h>
#include <fcntl.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>
#include <poll.h>
#include <sys/sendfile.h>
#include <lustre/lustreapi.h>
#include <lustre/lustre_idl.h>
Defines
#define ERROR(fmt,...)
#define DIE(fmt,...)
#define ASSERTF(cond, fmt,...)
#define PERFORM(testfn)
Functions
static void make_crc_table (void)
static unsigned long update_crc (unsigned long crc, unsigned char *buf, int len)
static void cleanup (void)
static unsigned long compute_crc (const char *fname)
static int sendfile_copy (const char *source, int source_gid, const char *dest, int dest_gid)
static void test10 (void)
static void test11 (void)
static void test12 (void)
static void test13 (void)
static void test14 (void)
static void test15 (void)
static void test16 (void)
int main (int argc, char *argv[])
Variables
static const char * source_file
static char * dest_file
static unsigned long source_crc
static unsigned long crc_table [256]
static int crc_table_computed
Define Documentation
#define ASSERTF (cond, fmt, ...)
Value:
do {                                                            \
                if (!(cond))                                            \
                        DIE("assertion '%s' failed: "fmt,               \
                            #cond, ## __VA_ARGS__);                     \
        } while (0)
Definition at line 82 of file sendfile_grouplock.c.
#define DIE (fmt, ...)
Value:
do {                                    \
                ERROR(fmt, ## __VA_ARGS__);     \
                exit(EXIT_FAILURE);             \
        } while (0)
Definition at line 76 of file sendfile_grouplock.c.
#define ERROR (fmt, ...)
Value:
fprintf(stderr, "%s: %s:%d: %s: " fmt "\n",                     \
                program_invocation_short_name, __FILE__, __LINE__,      \
                __func__, ## __VA_ARGS__);
Definition at line 71 of file sendfile_grouplock.c.
#define PERFORM (testfn)
Value:
do {                                                            \
                fprintf(stderr, "Starting test " #testfn " at %lld\n",  \
                        (unsigned long long)time(NULL));                \
                testfn();                                               \
                fprintf(stderr, "Finishing test " #testfn " at %lld\n", \
                        (unsigned long long)time(NULL));                \
        } while (0)
Definition at line 89 of file sendfile_grouplock.c.
Function Documentation
static void cleanup (void) [static]
Definition at line 160 of file sendfile_grouplock.c.
References dest_file.
static unsigned long compute_crc (const char * fname) [static]
Definition at line 166 of file sendfile_grouplock.c.
References ASSERTF, buf, and update_crc().
Referenced by main(), test10(), test11(), test12(), test13(), and test14().
int main (int argc, char * argv[])
Definition at line 356 of file sendfile_grouplock.c.
References cleanup(), compute_crc(), dest_file, PERFORM, source_crc, source_file, test10(), test11(), test12(), test13(), test14(), test15(), and test16().
static void make_crc_table (void) [static]
Definition at line 114 of file sendfile_grouplock.c.
References crc_table, and crc_table_computed.
Referenced by update_crc().
static int sendfile_copy (const char * source, int source_gid, const char * dest, int dest_gid) [static]
Definition at line 207 of file sendfile_grouplock.c.
References ASSERTF, and llapi_group_lock().
Referenced by test10(), test11(), test12(), test13(), test14(), test15(), and test16().
static void test10 (void) [static]
Definition at line 277 of file sendfile_grouplock.c.
References ASSERTF, cleanup(), compute_crc(), dest_file, sendfile_copy(), source_crc, and source_file.
static void test11 (void) [static]
Definition at line 290 of file sendfile_grouplock.c.
References ASSERTF, cleanup(), compute_crc(), dest_file, sendfile_copy(), source_crc, and source_file.
static void test12 (void) [static]
Definition at line 303 of file sendfile_grouplock.c.
References ASSERTF, cleanup(), compute_crc(), dest_file, sendfile_copy(), source_crc, and source_file.
static void test13 (void) [static]
Definition at line 316 of file sendfile_grouplock.c.
References ASSERTF, cleanup(), compute_crc(), dest_file, sendfile_copy(), source_crc, and source_file.
static void test14 (void) [static]
Definition at line 330 of file sendfile_grouplock.c.
References ASSERTF, cleanup(), compute_crc(), dest_file, sendfile_copy(), source_crc, and source_file.
static void test15 (void) [static]
Definition at line 343 of file sendfile_grouplock.c.
References sendfile_copy(), and source_file.
static void test16 (void) [static]
Definition at line 350 of file sendfile_grouplock.c.
References sendfile_copy(), and source_file.
static unsigned long update_crc (unsigned long crc, unsigned char * buf, int len) [static]
Definition at line 145 of file sendfile_grouplock.c.
References crc_table, crc_table_computed, and make_crc_table().
Referenced by compute_crc().
Variable Documentation
unsigned long crc_table[256] [static]
Definition at line 108 of file sendfile_grouplock.c.
Referenced by make_crc_table(), and update_crc().
int crc_table_computed [static]
Definition at line 111 of file sendfile_grouplock.c.
Referenced by make_crc_table(), and update_crc().
char* dest_file [static]
Definition at line 100 of file sendfile_grouplock.c.
Referenced by cleanup(), main(), test10(), test11(), test12(), test13(), and test14().
unsigned long source_crc [static]
Definition at line 101 of file sendfile_grouplock.c.
Referenced by main(), test10(), test11(), test12(), test13(), and test14().
const char* source_file [static]
Definition at line 99 of file sendfile_grouplock.c.
Referenced by main(), test10(), test11(), test12(), test13(), test14(), test15(), and test16().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.