Lustre: lustre/include/seq_range.h File Reference
lustre/include/seq_range.h File Reference
#include <lustre/lustre_idl.h>
Defines
#define DRANGE "[%#16.16llx-%#16.16llx]:%x:%s"
printf string and argument list for sequence range
#define PRANGE(range)
Functions
static unsigned fld_range_type (const struct lu_seq_range *range)
computes the sequence range type range
static bool fld_range_is_ost (const struct lu_seq_range *range)
Is this sequence range an OST? range.
static bool fld_range_is_mdt (const struct lu_seq_range *range)
Is this sequence range an MDT? range.
static unsigned fld_range_is_any (const struct lu_seq_range *range)
ANY range is only used when the fld client sends a fld query request, but it does not know whether the seq is an MDT or OST, so it will send the request with ANY type, which means any seq type from the lookup can be expected.
static void fld_range_set_type (struct lu_seq_range *range, unsigned flags)
Apply flags to range range flags.
static void fld_range_set_mdt (struct lu_seq_range *range)
Add MDT to range type range.
static void fld_range_set_ost (struct lu_seq_range *range)
Add OST to range type range.
static void fld_range_set_any (struct lu_seq_range *range)
Add ANY to range type range.
static __u64 lu_seq_range_space (const struct lu_seq_range *range)
computes width of given sequence range range
static void lu_seq_range_init (struct lu_seq_range *range)
initialize range to zero range
static bool lu_seq_range_within (const struct lu_seq_range *range, __u64 seq)
check if given seq id s is within given range range
static bool lu_seq_range_is_sane (const struct lu_seq_range *range)
Is the range sane? Is the end after the beginning? range.
static bool lu_seq_range_is_zero (const struct lu_seq_range *range)
Is the range 0? range.
static bool lu_seq_range_is_exhausted (const struct lu_seq_range *range)
Is the range out of space? range.
static int lu_seq_range_compare_loc (const struct lu_seq_range *r1, const struct lu_seq_range *r2)
return 0 if two ranges have the same location, nonzero if they are different r1 r2
Define Documentation
#define DRANGE "[%#16.16llx-%#16.16llx]:%x:%s"
printf string and argument list for sequence range
Definition at line 184 of file seq_range.h.
Referenced by __seq_server_alloc_meta(), __seq_server_alloc_super(), fld_cache_insert_nolock(), fld_cache_overlap_handle(), fld_declare_index_create(), fld_fix_new_list(), fld_handle_lookup(), fld_index_create(), fld_index_lookup(), fld_local_lookup(), range_alloc_set(), seq_client_alloc_seq(), seq_client_rpc(), seq_server_alloc_spec(), and seq_store_read().
#define PRANGE (range)
Value:
(unsigned long long)(range)->lsr_start, \
        (unsigned long long)(range)->lsr_end,   \
        (range)->lsr_index,                     \
        fld_range_is_mdt(range) ? "mdt" : "ost"
Definition at line 186 of file seq_range.h.
Referenced by __seq_server_alloc_meta(), __seq_server_alloc_super(), fld_cache_insert_nolock(), fld_cache_overlap_handle(), fld_declare_index_create(), fld_fix_new_list(), fld_handle_lookup(), fld_index_create(), fld_index_lookup(), fld_local_lookup(), range_alloc_set(), seq_client_alloc_seq(), seq_client_rpc(), seq_server_alloc_spec(), and seq_store_read().
Function Documentation
static unsigned fld_range_is_any (const struct lu_seq_range * range) [inline, static]
ANY range is only used when the fld client sends a fld query request, but it does not know whether the seq is an MDT or OST, so it will send the request with ANY type, which means any seq type from the lookup can be expected.
/a range
Definition at line 72 of file seq_range.h.
References fld_range_type(), and LU_SEQ_RANGE_ANY.
Referenced by fld_local_lookup().
static bool fld_range_is_mdt (const struct lu_seq_range * range) [inline, static]
Is this sequence range an MDT? range.
Definition at line 61 of file seq_range.h.
References fld_range_type(), and LU_SEQ_RANGE_MDT.
Referenced by lfsck_fid_match_idx(), and lfsck_layout_slave_check_pairs().
static bool fld_range_is_ost (const struct lu_seq_range * range) [inline, static]
Is this sequence range an OST? range.
Definition at line 52 of file seq_range.h.
References fld_range_type(), and LU_SEQ_RANGE_OST.
Referenced by fid_is_for_ostobj(), and fid_is_on_ost().
static void fld_range_set_any (struct lu_seq_range * range) [inline, static]
Add ANY to range type range.
Definition at line 109 of file seq_range.h.
References fld_range_set_type(), and LU_SEQ_RANGE_ANY.
Referenced by fid_is_for_ostobj(), lfsck_fid_match_idx(), lfsck_layout_slave_check_pairs(), llog_osd_get_regular_fid_dir(), and osd_fld_lookup().
static void fld_range_set_mdt (struct lu_seq_range * range) [inline, static]
Add MDT to range type range.
Definition at line 91 of file seq_range.h.
References fld_range_set_type(), and LU_SEQ_RANGE_MDT.
Referenced by fld_update_from_controller(), lfsck_find_mdt_idx_by_fid(), lfsck_master_oit_engine(), lfsck_namespace_exec_oit(), lfsck_namespace_scan_local_lpf(), lfsck_namespace_set_lmv_master(), lfsck_namespace_striped_dir_rescan(), lfsck_needs_scan_dir(), osd_fld_lookup(), and seq_client_rpc().
static void fld_range_set_ost (struct lu_seq_range * range) [inline, static]
Add OST to range type range.
Definition at line 100 of file seq_range.h.
References fld_range_set_type(), and LU_SEQ_RANGE_OST.
Referenced by lfsck_master_oit_engine(), osd_fld_lookup(), and seq_client_rpc().
static void fld_range_set_type (struct lu_seq_range * range, unsigned flags) [inline, static]
Apply flags to range range flags.
Definition at line 81 of file seq_range.h.
References lu_seq_range::lsr_flags.
Referenced by fld_client_lookup(), fld_range_set_any(), fld_range_set_mdt(), fld_range_set_ost(), lod_fld_lookup(), and update_is_committed().
static unsigned fld_range_type (const struct lu_seq_range * range) [inline, static]
computes the sequence range type range
Definition at line 43 of file seq_range.h.
References lu_seq_range::lsr_flags, and LU_SEQ_RANGE_MASK.
Referenced by fld_local_lookup(), fld_range_is_any(), fld_range_is_mdt(), and fld_range_is_ost().
static int lu_seq_range_compare_loc (const struct lu_seq_range * r1, const struct lu_seq_range * r2) [inline, static]
return 0 if two ranges have the same location, nonzero if they are different r1 r2
Definition at line 174 of file seq_range.h.
References lu_seq_range::lsr_flags, and lu_seq_range::lsr_index.
Referenced by fld_declare_index_create(), and fld_index_create().
static void lu_seq_range_init (struct lu_seq_range * range) [inline, static]
initialize range to zero range
Definition at line 127 of file seq_range.h.
Referenced by seq_client_flush(), seq_client_rpc(), and seq_server_init().
static bool lu_seq_range_is_exhausted (const struct lu_seq_range * range) [inline, static]
Is the range out of space? range.
Definition at line 164 of file seq_range.h.
References lu_seq_range_space().
Referenced by __seq_server_alloc_super(), range_alloc_set(), seq_client_alloc_seq(), seq_client_rpc(), and seq_server_check_and_alloc_super().
static bool lu_seq_range_is_sane (const struct lu_seq_range * range) [inline, static]
Is the range sane? Is the end after the beginning? range.
Definition at line 146 of file seq_range.h.
References lu_seq_range::lsr_end, and lu_seq_range::lsr_start.
Referenced by __seq_server_alloc_meta(), __seq_server_alloc_super(), fld_cache_entry_create(), fld_fix_new_list(), range_alloc_set(), seq_client_alloc_seq(), seq_client_rpc(), seq_server_check_and_alloc_super(), and seq_server_init().
static bool lu_seq_range_is_zero (const struct lu_seq_range * range) [inline, static]
Is the range 0? range.
Definition at line 155 of file seq_range.h.
References lu_seq_range::lsr_end, and lu_seq_range::lsr_start.
Referenced by range_alloc_set(), seq_server_check_and_alloc_super(), and seq_server_init().
static __u64 lu_seq_range_space (const struct lu_seq_range * range) [inline, static]
computes width of given sequence range range
Definition at line 118 of file seq_range.h.
References lu_seq_range::lsr_end, and lu_seq_range::lsr_start.
Referenced by lu_seq_range_is_exhausted(), range_alloc(), and range_alloc_set().
static bool lu_seq_range_within (const struct lu_seq_range * range, __u64 seq) [inline, static]
check if given seq id s is within given range range
Definition at line 136 of file seq_range.h.
References lu_seq_range::lsr_end, and lu_seq_range::lsr_start.
Referenced by fld_cache_lookup(), and fld_index_lookup().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.