Lustre: lustre/ptlrpc/service.c File Reference
lustre/ptlrpc/service.c File Reference
#include <linux/kthread.h>
#include <obd_support.h>
#include <obd_class.h>
#include <lustre_net.h>
#include <lu_object.h>
#include <lnet/types.h>
#include "ptlrpc_internal.h"
Data Structures
struct ptlrpc_hr_thread
struct ptlrpc_hr_partition
struct ptlrpc_hr_service
struct rs_batch
Defines
#define DEBUG_SUBSYSTEM S_RPC
#define HRT_RUNNING 0
#define HRT_STOPPING 1
#define MAX_SCHEDULED 256
maximum mumber of replies scheduled in one batch
#define DECLARE_RS_BATCH(b) struct rs_batch b
Functions
module_param (test_req_buffer_pressure, int, 0444)
MODULE_PARM_DESC (test_req_buffer_pressure,"set non-zero to put pressure on request buffer pools")
module_param (at_min, int, 0644)
MODULE_PARM_DESC (at_min,"Adaptive timeout minimum (sec)")
module_param (at_max, int, 0644)
MODULE_PARM_DESC (at_max,"Adaptive timeout maximum (sec)")
module_param (at_history, int, 0644)
MODULE_PARM_DESC (at_history,"Adaptive timeouts remember the slowest event that took place within this period (sec)")
module_param (at_early_margin, int, 0644)
MODULE_PARM_DESC (at_early_margin,"How soon before an RPC deadline to send an early reply")
module_param (at_extra, int, 0644)
MODULE_PARM_DESC (at_extra,"How much extra time to give with each early reply")
static int ptlrpc_server_post_idle_rqbds (struct ptlrpc_service_part *svcpt)
static void ptlrpc_server_hpreq_fini (struct ptlrpc_request *req)
Remove the request from the export list.
static void ptlrpc_at_remove_timed (struct ptlrpc_request *req)
static struct
ptlrpc_request_buffer_desc * ptlrpc_alloc_rqbd (struct ptlrpc_service_part *svcpt)
static void ptlrpc_free_rqbd (struct ptlrpc_request_buffer_desc *rqbd)
static int ptlrpc_grow_req_bufs (struct ptlrpc_service_part *svcpt, int post)
void ptlrpc_save_lock (struct ptlrpc_request *req, struct lustre_handle *lock, int mode, int no_ack)
Part of Rep-Ack logic.
static void rs_batch_init (struct rs_batch *b)
Initialize a reply batch.
static struct ptlrpc_hr_thread * ptlrpc_hr_select (struct ptlrpc_service_part *svcpt)
Choose an hr thread to dispatch requests to.
static void rs_batch_dispatch (struct rs_batch *b)
Dispatch all replies accumulated in the batch to one from dedicated reply handling threads.
static void rs_batch_add (struct rs_batch *b, struct ptlrpc_reply_state *rs)
Add a reply to a batch.
static void rs_batch_fini (struct rs_batch *b)
Reply batch finalization.
void ptlrpc_dispatch_difficult_reply (struct ptlrpc_reply_state *rs)
Put reply state into a queue for processing because we received ACK from the client.
void ptlrpc_schedule_difficult_reply (struct ptlrpc_reply_state *rs)
void ptlrpc_commit_replies (struct obd_export *exp)
static void ptlrpc_at_timer (unsigned long castmeharder)
static void ptlrpc_server_nthreads_check (struct ptlrpc_service *svc, struct ptlrpc_service_conf *conf)
static int ptlrpc_service_part_init (struct ptlrpc_service *svc, struct ptlrpc_service_part *svcpt, int cpt)
Initialize percpt data for a service.
struct ptlrpc_service * ptlrpc_register_service (struct ptlrpc_service_conf *conf, struct proc_dir_entry *proc_entry)
Initialize service on a given portal.
static void ptlrpc_server_free_request (struct ptlrpc_request *req)
to actually free the request, must be called without holding svc_lock.
void ptlrpc_server_drop_request (struct ptlrpc_request *req)
drop a reference count of the request.
void ptlrpc_request_change_export (struct ptlrpc_request *req, struct obd_export *export)
Change request export and move hp request from old export to new.
static void ptlrpc_server_finish_request (struct ptlrpc_service_part *svcpt, struct ptlrpc_request *req)
to finish a request: stop sending more early replies, and release the request.
static void ptlrpc_server_finish_active_request (struct ptlrpc_service_part *svcpt, struct ptlrpc_request *req)
to finish an active request: stop sending more early replies, and release the request.
void ptlrpc_update_export_timer (struct obd_export *exp, long extra_delay)
This function makes sure dead exports are evicted in a timely manner.
static int ptlrpc_check_req (struct ptlrpc_request *req)
Sanity check request req.
static void ptlrpc_at_set_timer (struct ptlrpc_service_part *svcpt)
static int ptlrpc_at_add_timed (struct ptlrpc_request *req)
static int ptlrpc_at_send_early_reply (struct ptlrpc_request *req)
static int ptlrpc_at_check_timed (struct ptlrpc_service_part *svcpt)
static int ptlrpc_server_check_resend_in_progress (struct ptlrpc_request *req)
static int ptlrpc_server_hpreq_init (struct ptlrpc_service_part *svcpt, struct ptlrpc_request *req)
Check if a request should be assigned with a high priority.
static int ptlrpc_hpreq_check (struct ptlrpc_request *req)
int ptlrpc_hpreq_handler (struct ptlrpc_request *req)
static int ptlrpc_server_request_add (struct ptlrpc_service_part *svcpt, struct ptlrpc_request *req)
static bool ptlrpc_server_allow_high (struct ptlrpc_service_part *svcpt, bool force)
Allow to handle high priority request User can call it w/o any lock but need to hold ptlrpc_service_part::scp_req_lock to get reliable result.
static bool ptlrpc_server_high_pending (struct ptlrpc_service_part *svcpt, bool force)
static bool ptlrpc_server_allow_normal (struct ptlrpc_service_part *svcpt, bool force)
Only allow normal priority requests on a service that has a high-priority queue if forced (i.e.
static bool ptlrpc_server_normal_pending (struct ptlrpc_service_part *svcpt, bool force)
static bool ptlrpc_server_request_pending (struct ptlrpc_service_part *svcpt, bool force)
Returns true if there are requests available in incoming request queue for processing and it is allowed to fetch them.
static struct ptlrpc_request * ptlrpc_server_request_get (struct ptlrpc_service_part *svcpt, bool force)
Fetch a request for processing from queue of unprocessed requests.
static int ptlrpc_server_handle_req_in (struct ptlrpc_service_part *svcpt, struct ptlrpc_thread *thread)
Handle freshly incoming reqs, add to timed early reply list, pass on to regular request queue.
static int ptlrpc_server_handle_request (struct ptlrpc_service_part *svcpt, struct ptlrpc_thread *thread)
Main incoming request handling logic.
static int ptlrpc_handle_rs (struct ptlrpc_reply_state *rs)
An internal function to process a single reply state object.
static void ptlrpc_check_rqbd_pool (struct ptlrpc_service_part *svcpt)
static int ptlrpc_retry_rqbds (void *arg)
static int ptlrpc_threads_enough (struct ptlrpc_service_part *svcpt)
static int ptlrpc_threads_increasable (struct ptlrpc_service_part *svcpt)
allowed to create more threads user can call it w/o any lock but need to hold ptlrpc_service_part::scp_lock to get reliable result
static int ptlrpc_threads_need_create (struct ptlrpc_service_part *svcpt)
too many requests and allowed to create more threads
static int ptlrpc_thread_stopping (struct ptlrpc_thread *thread)
static int ptlrpc_rqbd_pending (struct ptlrpc_service_part *svcpt)
static int ptlrpc_at_check (struct ptlrpc_service_part *svcpt)
static int ptlrpc_server_request_incoming (struct ptlrpc_service_part *svcpt)
requests wait on preprocessing user can call it w/o any lock but need to hold ptlrpc_service_part::scp_lock to get reliable result
static __attribute__ ((__noinline__))
static int ptlrpc_main (void *arg)
Main thread body for service threads.
static int hrt_dont_sleep (struct ptlrpc_hr_thread *hrt, struct list_head *replies)
static int ptlrpc_hr_main (void *arg)
Main body of "handle reply" function.
static void ptlrpc_stop_hr_threads (void)
static int ptlrpc_start_hr_threads (void)
static void ptlrpc_svcpt_stop_threads (struct ptlrpc_service_part *svcpt)
void ptlrpc_stop_all_threads (struct ptlrpc_service *svc)
Stops all threads of a particular service svc.
int ptlrpc_start_threads (struct ptlrpc_service *svc)
int ptlrpc_start_thread (struct ptlrpc_service_part *svcpt, int wait)
int ptlrpc_hr_init (void)
void ptlrpc_hr_fini (void)
static void ptlrpc_wait_replies (struct ptlrpc_service_part *svcpt)
Wait until all already scheduled replies are processed.
static void ptlrpc_service_del_atimer (struct ptlrpc_service *svc)
static void ptlrpc_service_unlink_rqbd (struct ptlrpc_service *svc)
static void ptlrpc_service_purge_all (struct ptlrpc_service *svc)
static void ptlrpc_service_free (struct ptlrpc_service *svc)
int ptlrpc_unregister_service (struct ptlrpc_service *service)
static int ptlrpc_svcpt_health_check (struct ptlrpc_service_part *svcpt)
Returns 0 if the service is healthy.
int ptlrpc_service_health_check (struct ptlrpc_service *svc)
Variables
int test_req_buffer_pressure = 0
struct list_head ptlrpc_all_services
Holds a list of all PTLRPC services.
struct mutex ptlrpc_all_services_mutex
Used to protect the ptlrpc_all_services list.
static struct ptlrpc_hr_service ptlrpc_hr
reply handling service.
static struct ptlrpc_hpreq_ops ptlrpc_hpreq_common
Define Documentation
#define DEBUG_SUBSYSTEM S_RPC
Definition at line 37 of file service.c.
#define DECLARE_RS_BATCH (b) struct rs_batch b
Definition at line 362 of file service.c.
Referenced by ptlrpc_commit_replies().
#define HRT_RUNNING 0
Definition at line 230 of file service.c.
#define HRT_STOPPING 1
Definition at line 231 of file service.c.
#define MAX_SCHEDULED 256
maximum mumber of replies scheduled in one batch
Definition at line 257 of file service.c.
Referenced by rs_batch_add().
Function Documentation
static __attribute__ ((__noinline__)) [static]
Definition at line 2345 of file service.c.
References l_wait_event_exclusive_head, lc_watchdog_disable(), lc_watchdog_touch(), LWI_TIMEOUT, ptlrpc_at_check(), ptlrpc_retry_rqbds(), ptlrpc_rqbd_pending(), ptlrpc_server_get_timeout(), ptlrpc_server_request_incoming(), ptlrpc_server_request_pending(), and ptlrpc_thread_stopping().
static int hrt_dont_sleep (struct ptlrpc_hr_thread * hrt, struct list_head * replies) [static]
Definition at line 2560 of file service.c.
References ptlrpc_hr_service::hr_stopping, ptlrpc_hr_thread::hrt_lock, ptlrpc_hr_thread::hrt_queue, list_empty(), list_splice_init(), and ptlrpc_hr.
Referenced by ptlrpc_hr_main().
module_param (at_extra , int , 0644)
module_param (at_early_margin , int , 0644)
module_param (at_history , int , 0644)
module_param (at_max , int , 0644)
module_param (at_min , int , 0644)
module_param (test_req_buffer_pressure , int , 0444)
MODULE_PARM_DESC (at_extra , "How much extra time to give with each early reply")
MODULE_PARM_DESC (at_early_margin , "How soon before an RPC deadline to send an early reply")
MODULE_PARM_DESC (at_history , "Adaptive timeouts remember the slowest event that took place within this period (sec)")
MODULE_PARM_DESC (at_max , "Adaptive timeout maximum (sec)")
MODULE_PARM_DESC (at_min , "Adaptive timeout minimum (sec)")
MODULE_PARM_DESC (test_req_buffer_pressure , "set non-zero to put pressure on request buffer pools")
static struct ptlrpc_request_buffer_desc* ptlrpc_alloc_rqbd (struct ptlrpc_service_part * svcpt) [static, read]
Definition at line 73 of file service.c.
References ptlrpc_cb_id::cbid_arg, ptlrpc_cb_id::cbid_fn, INIT_LIST_HEAD, list_add(), OBD_CPT_ALLOC_LARGE, OBD_CPT_ALLOC_PTR, OBD_FREE_PTR, request_in_callback(), ptlrpc_request_buffer_desc::rqbd_buffer, ptlrpc_request_buffer_desc::rqbd_cbid, ptlrpc_request_buffer_desc::rqbd_list, ptlrpc_request_buffer_desc::rqbd_refcount, ptlrpc_request_buffer_desc::rqbd_reqs, ptlrpc_request_buffer_desc::rqbd_svcpt, ptlrpc_service_part::scp_cpt, ptlrpc_service_part::scp_nrqbds_total, ptlrpc_service_part::scp_rqbd_idle, ptlrpc_service::srv_buf_size, and ptlrpc_service::srv_cptable.
Referenced by ptlrpc_grow_req_bufs().
static int ptlrpc_at_add_timed (struct ptlrpc_request * req) [static]
Definition at line 1182 of file service.c.
References AT_OFF, LASSERT, list_add(), list_empty(), list_for_each_entry_reverse, lustre_msghdr_get_flags(), MSGHDR_AT_SUPPORT, ptlrpc_at_array::paa_count, ptlrpc_at_array::paa_deadline, ptlrpc_at_array::paa_reqs_array, ptlrpc_at_array::paa_reqs_count, ptlrpc_at_array::paa_size, ptlrpc_at_set_timer(), ptlrpc_request::rq_at_linked, ptlrpc_request::rq_deadline, ptlrpc_request::rq_lock, ptlrpc_request::rq_no_reply, ptlrpc_request::rq_reqmsg, rq_timed_list, and ptlrpc_service_part::scp_at_array.
Referenced by ptlrpc_at_check_timed(), and ptlrpc_server_handle_req_in().
static int ptlrpc_at_check (struct ptlrpc_service_part * svcpt) [inline, static]
Definition at line 2329 of file service.c.
References ptlrpc_service_part::scp_at_check.
Referenced by __attribute__(), and ptlrpc_main().
static int ptlrpc_at_check_timed (struct ptlrpc_service_part * svcpt) [static]
ptlrpc_server_drop_request() may drop refcount to 0 already. Let's check this and don't add entry to work_list
Definition at line 1416 of file service.c.
References at_early_margin, at_extra, at_get(), CDEBUG, CFS_DURATION_T, cfs_time_current(), cfs_time_current_sec(), cfs_time_sub(), CWARN, D_ADAPTTO, ENTRY, INIT_LIST_HEAD, LCONSOLE_WARN, likely, list_add(), list_del_init(), list_empty(), list_entry, list_for_each_entry_safe, list_head::next, now(), ptlrpc_at_array::paa_count, ptlrpc_at_array::paa_deadline, ptlrpc_at_array::paa_reqs_array, ptlrpc_at_array::paa_reqs_count, ptlrpc_at_array::paa_size, ptlrpc_at_add_timed(), ptlrpc_at_remove_timed(), ptlrpc_at_send_early_reply(), ptlrpc_at_set_timer(), ptlrpc_server_drop_request(), RETURN, ptlrpc_request::rq_deadline, ptlrpc_request::rq_refcount, rq_timed_list, ptlrpc_service_part::scp_at_array, ptlrpc_service_part::scp_at_check, ptlrpc_service_part::scp_at_checktime, ptlrpc_service_part::scp_at_estimate, ptlrpc_service_part::scp_nreqs_active, and ptlrpc_service_part::scp_nreqs_incoming.
Referenced by ptlrpc_main().
static void ptlrpc_at_remove_timed (struct ptlrpc_request * req) [static]
Definition at line 1237 of file service.c.
References LASSERT, list_del_init(), list_empty(), ptlrpc_at_array::paa_count, ptlrpc_at_array::paa_reqs_count, ptlrpc_request::rq_at_linked, and ptlrpc_request::rq_lock.
Referenced by ptlrpc_at_check_timed(), and ptlrpc_server_drop_request().
static int ptlrpc_at_send_early_reply (struct ptlrpc_request * req) [static]
if it is last refcount then early reply isn't needed
Definition at line 1259 of file service.c.
References at_early_margin, at_extra, at_get(), at_measured(), AT_OFF, CFS_FAIL_CHECK, cfs_time_current_sec(), class_conn2export(), class_export_put(), class_export_rpc_dec, class_export_rpc_inc, D_ADAPTTO, D_ERROR, D_INFO, D_WARNING, DEBUG_REQ, ENTRY, obd_export::exp_obd, GOTO, LASSERT, LPRFL_EARLY_REPLY, lustre_msg, lustre_msg_get_flags(), lustre_msg_get_handle(), lustre_msghdr_get_flags(), lustre_pack_reply_flags(), MSG_LOCK_REPLAY_DONE, MSG_REPLAY, MSG_REQ_REPLAY_DONE, MSGHDR_AT_SUPPORT, OBD_ALLOC_LARGE, obd_device::obd_fail, OBD_FAIL_TGT_REPLAY_RECONNECT, OBD_FREE_LARGE, obd_device::obd_recovery_timeout, PTLRPC_REPLY_EARLY, ptlrpc_req_drop_rs(), ptlrpc_request_cache_alloc(), ptlrpc_request_cache_free(), ptlrpc_send_reply(), RETURN, ptlrpc_request::rq_deadline, ptlrpc_request::rq_early_count, ptlrpc_request::rq_export, ptlrpc_request::rq_no_reply, ptlrpc_request::rq_pack_bulk, ptlrpc_request::rq_pack_udesc, ptlrpc_request::rq_packed_final, ptlrpc_request::rq_refcount, ptlrpc_request::rq_rep_swab_mask, ptlrpc_request::rq_reqlen, ptlrpc_request::rq_reqmsg, ptlrpc_service_part::scp_at_estimate, sptlrpc_svc_ctx_addref(), and sptlrpc_svc_ctx_decref().
Referenced by ptlrpc_at_check_timed().
static void ptlrpc_at_set_timer (struct ptlrpc_service_part * svcpt) [static]
Definition at line 1159 of file service.c.
References at_early_margin, CDEBUG, cfs_time_current_sec(), cfs_time_shift(), cfs_timer_arm(), cfs_timer_disarm(), D_INFO, ptlrpc_at_array::paa_count, ptlrpc_at_array::paa_deadline, ptlrpc_at_timer(), ptlrpc_service_part::scp_at_array, and ptlrpc_service_part::scp_at_timer.
Referenced by ptlrpc_at_add_timed(), and ptlrpc_at_check_timed().
static void ptlrpc_at_timer (unsigned long castmeharder) [static]
Definition at line 482 of file service.c.
References cfs_time_current(), ptlrpc_service_part::scp_at_check, ptlrpc_service_part::scp_at_checktime, and ptlrpc_service_part::scp_waitq.
Referenced by ptlrpc_at_set_timer(), and ptlrpc_service_part_init().
static int ptlrpc_check_req (struct ptlrpc_request * req) [static]
Sanity check request req.
Return 0 if all is ok, error code otherwise.
Definition at line 1117 of file service.c.
References CDEBUG, class_fail_export(), D_ERROR, D_RPCTRACE, DEBUG_REQ, obd_export::exp_conn_cnt, obd_export::exp_obd, LPU64, lustre_msg_get_conn_cnt(), lustre_msg_get_flags(), lustre_msg_get_transno(), MSG_REPLAY, MSG_REQ_REPLAY_DONE, obd_device::obd_fail, obd_device::obd_name, obd_device::obd_recovering, ptlrpc_error(), ptlrpc_request::rq_export, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_status, and unlikely.
Referenced by ptlrpc_server_handle_req_in(), and ptlrpc_server_handle_request().
static void ptlrpc_check_rqbd_pool (struct ptlrpc_service_part * svcpt) [static]
Definition at line 2252 of file service.c.
References lprocfs_counter_add(), ptlrpc_grow_req_bufs(), PTLRPC_REQBUF_AVAIL_CNTR, ptlrpc_service_part::scp_nrqbds_posted, and test_req_buffer_pressure.
Referenced by ptlrpc_main().
static void ptlrpc_free_rqbd (struct ptlrpc_request_buffer_desc * rqbd) [static]
Definition at line 103 of file service.c.
References LASSERT, list_del(), list_empty(), OBD_FREE_LARGE, OBD_FREE_PTR, ptlrpc_request_buffer_desc::rqbd_buffer, ptlrpc_request_buffer_desc::rqbd_list, ptlrpc_request_buffer_desc::rqbd_refcount, ptlrpc_request_buffer_desc::rqbd_reqs, ptlrpc_request_buffer_desc::rqbd_svcpt, and ptlrpc_service_part::scp_nrqbds_total.
Referenced by ptlrpc_service_purge_all().
static int ptlrpc_grow_req_bufs (struct ptlrpc_service_part * svcpt, int post) [static]
Definition at line 120 of file service.c.
References CDEBUG, CERROR, D_RPCTRACE, LASSERT, ptlrpc_alloc_rqbd(), ptlrpc_server_post_idle_rqbds(), ptlrpc_service_part::scp_nrqbds_posted, ptlrpc_service_part::scp_nrqbds_total, ptlrpc_service_part::scp_rqbd_allocating, ptlrpc_service::srv_buf_size, ptlrpc_service::srv_name, and ptlrpc_service::srv_nbuf_per_group.
Referenced by ptlrpc_check_rqbd_pool(), and ptlrpc_service_part_init().
static int ptlrpc_handle_rs (struct ptlrpc_reply_state * rs) [static]
An internal function to process a single reply state object.
Definition at line 2149 of file service.c.
References ptlrpc_connection::c_peer, CDEBUG, class_export_put(), D_HA, ENTRY, obd_export::exp_connection, obd_export::exp_lock, obd_export::exp_uncommitted_replies_lock, LASSERT, ldlm_lock_decref(), libcfs_nid2str(), list_del_init(), list_empty(), LNetMDUnlink(), LPD64, lnet_process_id_t::nid, ptlrpc_rs_decref(), RETURN, ptlrpc_reply_state::rs_committed, ptlrpc_reply_state::rs_difficult, ptlrpc_reply_state::rs_exp_list, ptlrpc_reply_state::rs_export, ptlrpc_reply_state::rs_handled, ptlrpc_reply_state::rs_list, ptlrpc_reply_state::rs_lock, ptlrpc_reply_state::rs_locks, ptlrpc_reply_state::rs_md_h, ptlrpc_reply_state::rs_modes, ptlrpc_reply_state::rs_nlocks, ptlrpc_reply_state::rs_obd_list, ptlrpc_reply_state::rs_on_net, ptlrpc_reply_state::rs_opc, ptlrpc_reply_state::rs_scheduled, ptlrpc_reply_state::rs_svcpt, ptlrpc_reply_state::rs_transno, ptlrpc_reply_state::rs_xid, ptlrpc_service_part::scp_nreps_difficult, ptlrpc_service_part::scp_waitq, and ptlrpc_service::srv_is_stopping.
Referenced by ptlrpc_hr_main().
static int ptlrpc_hpreq_check (struct ptlrpc_request * req) [static]
Definition at line 1610 of file service.c.
static int ptlrpc_hr_main (void * arg) [static]
Main body of "handle reply" function.
It processes acked reply states
Definition at line 2578 of file service.c.
References cfs_cpt_bind(), CWARN, ptlrpc_hr_service::hr_cpt_table, ptlrpc_hr_service::hr_stopping, ptlrpc_hr_service::hr_waitq, ptlrpc_hr_partition::hrp_cpt, ptlrpc_hr_partition::hrp_nstarted, ptlrpc_hr_partition::hrp_nstopped, hrt_dont_sleep(), ptlrpc_hr_thread::hrt_id, ptlrpc_hr_thread::hrt_partition, ptlrpc_hr_thread::hrt_waitq, INIT_LIST_HEAD, l_wait_condition, list_del_init(), list_empty(), list_entry, list_head::prev, ptlrpc_handle_rs(), ptlrpc_hr, and ptlrpc_reply_state::rs_list.
Referenced by ptlrpc_start_hr_threads().
static struct ptlrpc_hr_thread* ptlrpc_hr_select (struct ptlrpc_service_part * svcpt) [static, read]
Choose an hr thread to dispatch requests to.
Definition at line 274 of file service.c.
References cfs_cpt_number(), ptlrpc_hr_service::hr_cpt_table, ptlrpc_hr_service::hr_partitions, ptlrpc_hr_service::hr_rotor, ptlrpc_hr_partition::hrp_nthrs, ptlrpc_hr_partition::hrp_rotor, ptlrpc_hr_partition::hrp_thrs, ptlrpc_hr, and ptlrpc_service_part::scp_cpt.
Referenced by ptlrpc_dispatch_difficult_reply(), and rs_batch_dispatch().
static int ptlrpc_main (void * arg) [static]
Main thread body for service threads.
Waits in a loop waiting for new requests to process to appear. Every time an incoming requests is added to its queue, a waitq is woken up and one of the threads will handle it.
Definition at line 2378 of file service.c.
References CDEBUG, CERROR, cfs_cpt_bind(), cfs_time_seconds(), current_pid, CWARN, D_NET, D_RPCTRACE, ENTRY, LASSERT, lu_context::lc_cookie, lu_context::lc_thread, lc_watchdog_add(), lc_watchdog_delete(), LCT_NOREF, LCT_REMEMBER, lu_env::le_ctx, lu_env::le_ses, list_add(), list_empty(), lu_context_enter(), lu_context_exit(), lu_context_fini(), lu_context_init(), OBD_ALLOC_LARGE, OBD_ALLOC_PTR, OBD_FREE_PTR, ptlrpc_at_check(), ptlrpc_at_check_timed(), ptlrpc_check_rqbd_pool(), ptlrpc_rqbd_pending(), ptlrpc_server_get_timeout(), ptlrpc_server_handle_req_in(), ptlrpc_server_handle_request(), ptlrpc_server_post_idle_rqbds(), ptlrpc_server_request_incoming(), ptlrpc_server_request_pending(), ptlrpc_start_thread(), ptlrpc_thread_stopping(), ptlrpc_threads_need_create(), ptlrpc_reply_state::rs_list, ptlrpc_service_part::scp_cpt, ptlrpc_service_part::scp_nrqbds_posted, ptlrpc_service_part::scp_nthrs_running, ptlrpc_service_part::scp_nthrs_starting, ptlrpc_service_part::scp_rep_idle, ptlrpc_service_part::scp_rep_waitq, ptlrpc_service_part::scp_rqbd_idle, ptlrpc_service_part::scp_rqbd_timeout, ptlrpc_service_ops::so_thr_done, ptlrpc_service_ops::so_thr_init, ptlrpc_service::srv_cptable, ptlrpc_service::srv_ctx_tags, ptlrpc_service::srv_max_reply_size, ptlrpc_service::srv_name, ptlrpc_service::srv_ops, SVC_RUNNING, SVC_STARTING, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, ptlrpc_thread::t_env, ptlrpc_thread::t_id, ptlrpc_thread::t_name, ptlrpc_thread::t_pid, ptlrpc_thread::t_svcpt, ptlrpc_thread::t_watchdog, thread, thread_add_flags(), thread_clear_flags(), thread_is_starting(), and thread_test_and_clear_flags().
Referenced by ptlrpc_start_thread().
static int ptlrpc_retry_rqbds (void * arg) [static]
Definition at line 2275 of file service.c.
References ptlrpc_service_part::scp_rqbd_timeout.
Referenced by __attribute__().
static int ptlrpc_rqbd_pending (struct ptlrpc_service_part * svcpt) [inline, static]
Definition at line 2322 of file service.c.
References list_empty(), ptlrpc_service_part::scp_rqbd_idle, and ptlrpc_service_part::scp_rqbd_timeout.
Referenced by __attribute__(), and ptlrpc_main().
static bool ptlrpc_server_allow_high (struct ptlrpc_service_part * svcpt, bool force) [static]
Allow to handle high priority request User can call it w/o any lock but need to hold ptlrpc_service_part::scp_req_lock to get reliable result.
Definition at line 1686 of file service.c.
References CFS_FAIL_PRECHECK(), MDS_REQUEST_PORTAL, nrs_svcpt_has_hp(), OBD_FAIL_PTLRPC_CANCEL_RESEND, ptlrpc_nrs_req_pending_nolock(), ptlrpc_nrs_req_throttling_nolock(), PTLRPC_NTHRS_INIT, ptlrpc_service_part::scp_hreq_count, ptlrpc_service_part::scp_nhreqs_active, ptlrpc_service_part::scp_nreqs_active, ptlrpc_service_part::scp_nthrs_running, and unlikely.
Referenced by ptlrpc_server_high_pending().
static bool ptlrpc_server_allow_normal (struct ptlrpc_service_part * svcpt, bool force) [static]
Only allow normal priority requests on a service that has a high-priority queue if forced (i.e.
cleanup), if there are other high priority requests already being processed (i.e. those threads can service more high-priority requests), or if there are enough idle threads that a later thread can do a high priority request. User can call it w/o any lock but need to hold ptlrpc_service_part::scp_req_lock to get reliable result
Definition at line 1734 of file service.c.
References CFS_FAIL_PRECHECK(), MDS_REQUEST_PORTAL, nrs_svcpt_has_hp(), OBD_FAIL_PTLRPC_CANCEL_RESEND, ptlrpc_nrs_req_throttling_nolock(), PTLRPC_NTHRS_INIT, ptlrpc_service_part::scp_nhreqs_active, ptlrpc_service_part::scp_nreqs_active, ptlrpc_service_part::scp_nthrs_running, and unlikely.
Referenced by ptlrpc_server_normal_pending().
static int ptlrpc_server_check_resend_in_progress (struct ptlrpc_request * req) [static]
Definition at line 1522 of file service.c.
References D_HA, DEBUG_REQ, obd_export::exp_hp_rpcs, obd_export::exp_reg_rpcs, obd_export::exp_rpc_count, list_for_each_entry, lustre_msg_get_flags(), MSG_RESENT, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_bulk_write, rq_exp_list, ptlrpc_request::rq_export, ptlrpc_request::rq_reqmsg, and ptlrpc_request::rq_xid.
Referenced by ptlrpc_server_request_add().
static void ptlrpc_server_finish_active_request (struct ptlrpc_service_part * svcpt, struct ptlrpc_request * req) [static]
to finish an active request: stop sending more early replies, and release the request.
should be called after we finished handling the request.
Definition at line 1013 of file service.c.
References class_export_rpc_dec, ptlrpc_nrs_req_finalize(), ptlrpc_nrs_req_stop_nolock(), ptlrpc_server_finish_request(), ptlrpc_request::rq_export, ptlrpc_request::rq_hp, ptlrpc_service_part::scp_nhreqs_active, and ptlrpc_service_part::scp_nreqs_active.
Referenced by ptlrpc_server_handle_request(), and ptlrpc_service_purge_all().
static void ptlrpc_server_finish_request (struct ptlrpc_service_part * svcpt, struct ptlrpc_request * req) [static]
to finish a request: stop sending more early replies, and release the request.
Definition at line 1001 of file service.c.
References ptlrpc_server_drop_request(), and ptlrpc_server_hpreq_fini().
Referenced by ptlrpc_server_finish_active_request(), ptlrpc_server_handle_req_in(), and ptlrpc_service_purge_all().
static void ptlrpc_server_free_request (struct ptlrpc_request * req) [static]
to actually free the request, must be called without holding svc_lock.
note it's caller's responsibility to unlink req->rq_list.
Definition at line 836 of file service.c.
References LASSERT, list_empty(), ptlrpc_req_drop_rs(), ptlrpc_request_cache_free(), ptlrpc_request::rq_refcount, and sptlrpc_svc_ctx_decref().
Referenced by ptlrpc_server_drop_request().
static int ptlrpc_server_handle_req_in (struct ptlrpc_service_part * svcpt, struct ptlrpc_thread * thread) [static]
Handle freshly incoming reqs, add to timed early reply list, pass on to regular request queue.
All incoming requests pass through here before getting into ptlrpc_server_handle_req later on.
Definition at line 1835 of file service.c.
References CDEBUG, CERROR, CFS_DURATION_T, cfs_fail_val, cfs_time_current_sec(), cfs_time_sub(), class_conn2export(), D_ERROR, D_RPCTRACE, D_WARNING, DEBUG_REQ, ENTRY, GOTO, LBUG, LCT_NOREF, LCT_SERVER_SESSION, lu_env::le_ses, libcfs_id2str(), list_del_init(), list_empty(), list_entry, LPU64, lu_context_enter(), lu_context_init(), lustre_msg_get_handle(), lustre_msg_get_opc(), lustre_msg_get_timeout(), lustre_msg_get_type(), lustre_msghdr_get_flags(), lustre_unpack_req_ptlrpc_body(), MDS_READPAGE, MDS_WRITEPAGE, MGS_CONFIG_READ, MSG_PTLRPC_BODY_OFF, MSGHDR_AT_SUPPORT, list_head::next, OBD_FAIL_CHECK, OBD_FAIL_MDS_ALL_REPLY_NET, OBD_FAIL_MDS_RESEND, OBD_FAIL_PRECHECK, OBD_FAIL_PTLRPC_DROP_REQ_OPC, obd_timeout, OST_READ, OST_WRITE, OUT_UPDATE, PTL_RPC_MSG_REQUEST, ptlrpc_at_add_timed(), ptlrpc_check_req(), ptlrpc_server_finish_request(), ptlrpc_server_request_add(), ptlrpc_unpack_req_msg(), ptlrpc_update_export_timer(), RETURN, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_deadline, ptlrpc_request::rq_export, ptlrpc_request::rq_flvr, ptlrpc_request::rq_list, ptlrpc_request::rq_peer, ptlrpc_request::rq_reqlen, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_xid, ptlrpc_service_part::scp_nreqs_incoming, ptlrpc_service_part::scp_req_incoming, ptlrpc_service_part::scp_waitq, SECSVC_COMPLETE, SECSVC_DROP, SECSVC_OK, sptlrpc_flavor::sf_rpc, SPTLRPC_FLVR_POLICY, SPTLRPC_POLICY_NULL, sptlrpc_svc_unwrap_request(), sptlrpc_target_export_check(), ptlrpc_service::srv_req_portal, ptlrpc_thread::t_env, ptlrpc_thread::t_name, target_send_reply(), and unlikely.
Referenced by ptlrpc_main().
static int ptlrpc_server_handle_request (struct ptlrpc_service_part * svcpt, struct ptlrpc_thread * thread) [static]
Main incoming request handling logic.
Calls handler function from service to do actual processing.
Definition at line 1999 of file service.c.
References at_get(), CDEBUG, CFS_DURATION_T, CFS_FAIL_TIMEOUT_MS, cfs_fail_val, cfs_time_current_sec(), cfs_time_sub(), cfs_timeval_sub(), current_comm, D_ADAPTTO, D_ERROR, D_NET, D_RPCTRACE, D_WARNING, DEBUG_REQ, ENTRY, obd_export::exp_client_uuid, obd_export::exp_refcount, EXTRA_MAX_OPCODES, LASSERT, LDLM_ENQUEUE, lu_env::le_ses, libcfs_debug_dumplog(), libcfs_id2str(), likely, lprocfs_counter_add(), LPU64, LUSTRE_MAX_OPCODES, lustre_msg_get_opc(), lustre_msg_get_status(), lustre_msg_get_transno(), MDS_REINT, OBD_FAIL_CHECK, OBD_FAIL_PTLRPC_DUMP_LOG, OBD_FAIL_PTLRPC_HPREQ_NOTIMEOUT, OBD_FAIL_PTLRPC_HPREQ_TIMEOUT, OBD_FAIL_PTLRPC_PAUSE_REQ, OBD_FAIL_TIMEOUT, OBD_PING, opcode_offset(), ptlrpc_check_req(), PTLRPC_REQACTIVE_CNTR, PTLRPC_REQQDEPTH_CNTR, PTLRPC_REQWAIT_CNTR, ptlrpc_rqphase_move(), ptlrpc_server_finish_active_request(), ptlrpc_server_request_get(), PTLRPC_TIMEOUT, ptlrpc_update_export_timer(), RETURN, ptlrpc_request::rq_deadline, ptlrpc_request::rq_early_count, ptlrpc_request::rq_export, ptlrpc_request::rq_peer, RQ_PHASE_COMPLETE, RQ_PHASE_INTERPRET, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_status, ptlrpc_request::rq_transno, ptlrpc_request::rq_xid, ptlrpc_service_part::scp_at_estimate, ptlrpc_service_part::scp_nreqs_active, ptlrpc_service_part::scp_nreqs_incoming, ptlrpc_service_ops::so_req_handler, ptlrpc_service::srv_ops, ptlrpc_service::srv_stats, ptlrpc_thread::t_env, unlikely, and obd_uuid::uuid.
Referenced by ptlrpc_main().
static bool ptlrpc_server_high_pending (struct ptlrpc_service_part * svcpt, bool force) [static]
Definition at line 1718 of file service.c.
References ptlrpc_nrs_req_pending_nolock(), and ptlrpc_server_allow_high().
Referenced by ptlrpc_server_request_get(), ptlrpc_server_request_pending(), and ptlrpc_svcpt_health_check().
static void ptlrpc_server_hpreq_fini (struct ptlrpc_request * req) [static]
Remove the request from the export list.
Definition at line 1594 of file service.c.
References ENTRY, EXIT, obd_export::exp_rpc_lock, list_del_init(), and ptlrpc_request::rq_export.
Referenced by ptlrpc_server_finish_request().
static int ptlrpc_server_hpreq_init (struct ptlrpc_service_part * svcpt, struct ptlrpc_request * req) [static]
Check if a request should be assigned with a high priority.
Return values:
< 0: error occurred 0: normal RPC request +1: high priority request
Definition at line 1566 of file service.c.
References ENTRY, LASSERT, RETURN, and ptlrpc_request::rq_export.
Referenced by ptlrpc_server_request_add().
static bool ptlrpc_server_normal_pending (struct ptlrpc_service_part * svcpt, bool force) [static]
Definition at line 1761 of file service.c.
References ptlrpc_nrs_req_pending_nolock(), and ptlrpc_server_allow_normal().
Referenced by ptlrpc_server_request_get(), ptlrpc_server_request_pending(), and ptlrpc_svcpt_health_check().
static void ptlrpc_server_nthreads_check (struct ptlrpc_service * svc, struct ptlrpc_service_conf * conf) [static]
Definition at line 494 of file service.c.
References CDEBUG, CFS_CPT_ANY, cfs_cpt_weight(), cfs_cpu_ht_nsiblings(), D_OTHER, LASSERT, max, ptlrpc_service_conf::psc_thr, PTLRPC_NTHRS_INIT, ptlrpc_service_ops::so_hpreq_handler, ptlrpc_service::srv_cptable, ptlrpc_service::srv_name, ptlrpc_service::srv_ncpts, ptlrpc_service::srv_nthrs_cpt_init, ptlrpc_service::srv_nthrs_cpt_limit, ptlrpc_service::srv_ops, ptlrpc_service_thr_conf::tc_nthrs_base, ptlrpc_service_thr_conf::tc_nthrs_init, ptlrpc_service_thr_conf::tc_nthrs_max, ptlrpc_service_thr_conf::tc_nthrs_user, and ptlrpc_service_thr_conf::tc_thr_factor.
Referenced by ptlrpc_register_service().
static int ptlrpc_server_post_idle_rqbds (struct ptlrpc_service_part * svcpt) [static]
Definition at line 436 of file service.c.
References list_add(), list_add_tail(), list_del(), list_empty(), list_entry, list_head::next, ptlrpc_register_rqbd(), ptlrpc_request_buffer_desc::rqbd_list, ptlrpc_service_part::scp_nrqbds_posted, ptlrpc_service_part::scp_rqbd_idle, and ptlrpc_service_part::scp_rqbd_posted.
Referenced by ptlrpc_grow_req_bufs(), and ptlrpc_main().
static int ptlrpc_server_request_add (struct ptlrpc_service_part * svcpt, struct ptlrpc_request * req) [static]
Definition at line 1634 of file service.c.
References ENTRY, obd_export::exp_hp_rpcs, obd_export::exp_reg_rpcs, obd_export::exp_rpc_lock, list_add(), ptlrpc_nrs_req_add(), ptlrpc_nrs_req_finalize(), ptlrpc_nrs_req_initialize(), ptlrpc_server_check_resend_in_progress(), ptlrpc_server_hpreq_init(), RETURN, and ptlrpc_request::rq_export.
Referenced by ptlrpc_server_handle_req_in().
static struct ptlrpc_request* ptlrpc_server_request_get (struct ptlrpc_service_part * svcpt, bool force) [static, read]
Fetch a request for processing from queue of unprocessed requests.
Favors high-priority requests. Returns a pointer to fetched request.
Definition at line 1789 of file service.c.
References class_export_rpc_inc, ENTRY, likely, ptlrpc_nrs_req_get_nolock(), ptlrpc_server_high_pending(), ptlrpc_server_normal_pending(), RETURN, ptlrpc_request::rq_export, ptlrpc_request::rq_hp, ptlrpc_service_part::scp_hreq_count, ptlrpc_service_part::scp_nhreqs_active, and ptlrpc_service_part::scp_nreqs_active.
Referenced by ptlrpc_server_handle_request(), and ptlrpc_service_purge_all().
static int ptlrpc_server_request_incoming (struct ptlrpc_service_part * svcpt) [inline, static]
requests wait on preprocessing user can call it w/o any lock but need to hold ptlrpc_service_part::scp_lock to get reliable result
Definition at line 2340 of file service.c.
References list_empty(), and ptlrpc_service_part::scp_req_incoming.
Referenced by __attribute__(), and ptlrpc_main().
static bool ptlrpc_server_request_pending (struct ptlrpc_service_part * svcpt, bool force) [inline, static]
Returns true if there are requests available in incoming request queue for processing and it is allowed to fetch them.
User can call it w/o any lock but need to hold ptlrpc_service::scp_req_lock to get reliable result
See also:
ptlrpc_server_allow_normal
ptlrpc_server_allow high
Definition at line 1777 of file service.c.
References ptlrpc_server_high_pending(), and ptlrpc_server_normal_pending().
Referenced by __attribute__(), ptlrpc_main(), and ptlrpc_service_purge_all().
static void ptlrpc_service_del_atimer (struct ptlrpc_service * svc) [static]
Definition at line 2985 of file service.c.
References cfs_timer_disarm(), ptlrpc_service_for_each_part, and ptlrpc_service_part::scp_at_timer.
Referenced by ptlrpc_unregister_service().
static void ptlrpc_service_free (struct ptlrpc_service * svc) [static]
Definition at line 3123 of file service.c.
References cfs_expr_list_values_free(), cfs_timer_disarm(), OBD_FREE, OBD_FREE_PTR, offsetof, ptlrpc_at_array::paa_reqs_array, ptlrpc_at_array::paa_reqs_count, ptlrpc_at_array::paa_size, ptlrpc_service_for_each_part, ptlrpc_service_part::scp_at_array, ptlrpc_service_part::scp_at_timer, ptlrpc_service::srv_cpts, and ptlrpc_service::srv_ncpts.
Referenced by ptlrpc_unregister_service().
static int ptlrpc_service_part_init (struct ptlrpc_service * svc, struct ptlrpc_service_part * svcpt, int cpt) [static]
Initialize percpt data for a service.
Definition at line 599 of file service.c.
References at_est2timeout(), at_init(), at_max, cfs_timer_init(), INIT_LIST_HEAD, OBD_CPT_ALLOC, OBD_FREE, ptlrpc_at_array::paa_count, ptlrpc_at_array::paa_deadline, ptlrpc_at_array::paa_reqs_array, ptlrpc_at_array::paa_reqs_count, ptlrpc_at_array::paa_size, ptlrpc_at_timer(), ptlrpc_grow_req_bufs(), ptlrpc_service_part::scp_at_array, ptlrpc_service_part::scp_at_estimate, ptlrpc_service_part::scp_at_timer, ptlrpc_service_part::scp_cpt, ptlrpc_service_part::scp_hist_reqs, ptlrpc_service_part::scp_hist_rqbds, ptlrpc_service_part::scp_nreps_difficult, ptlrpc_service_part::scp_rep_active, ptlrpc_service_part::scp_rep_idle, ptlrpc_service_part::scp_rep_waitq, ptlrpc_service_part::scp_req_incoming, ptlrpc_service_part::scp_rqbd_idle, ptlrpc_service_part::scp_rqbd_posted, ptlrpc_service_part::scp_threads, ptlrpc_service_part::scp_waitq, size, and ptlrpc_service::srv_cptable.
Referenced by ptlrpc_register_service().
static void ptlrpc_service_purge_all (struct ptlrpc_service * svc) [static]
Definition at line 3055 of file service.c.
References LASSERT, list_del(), list_empty(), list_entry, list_head::next, OBD_FREE_LARGE, ptlrpc_free_rqbd(), ptlrpc_schedule_difficult_reply(), ptlrpc_server_finish_active_request(), ptlrpc_server_finish_request(), ptlrpc_server_request_get(), ptlrpc_server_request_pending(), ptlrpc_service_for_each_part, ptlrpc_wait_replies(), ptlrpc_request::rq_list, ptlrpc_reply_state::rs_list, ptlrpc_reply_state::rs_lock, ptlrpc_service_part::scp_hist_nrqbds, ptlrpc_service_part::scp_nreqs_active, ptlrpc_service_part::scp_nreqs_incoming, ptlrpc_service_part::scp_rep_active, ptlrpc_service_part::scp_rep_idle, ptlrpc_service_part::scp_req_incoming, ptlrpc_service_part::scp_rqbd_idle, ptlrpc_service_part::scp_rqbd_posted, and ptlrpc_service::srv_max_reply_size.
Referenced by ptlrpc_unregister_service().
static void ptlrpc_service_unlink_rqbd (struct ptlrpc_service * svc) [static]
Definition at line 2998 of file service.c.
References cfs_time_seconds(), CWARN, l_wait_event, LASSERT, list_for_each_entry, LNetClearLazyPortal(), LNetMDUnlink(), LONG_UNLINK, LWI_TIMEOUT_INTERVAL, ptlrpc_service_for_each_part, ptlrpc_request_buffer_desc::rqbd_md_h, ptlrpc_service_part::scp_nrqbds_posted, ptlrpc_service_part::scp_rqbd_posted, ptlrpc_service_part::scp_waitq, ptlrpc_service::srv_hist_nrqbds_cpt_max, and ptlrpc_service::srv_req_portal.
Referenced by ptlrpc_unregister_service().
static int ptlrpc_start_hr_threads (void) [static]
Definition at line 2644 of file service.c.
References CERROR, cfs_percpt_for_each, ENTRY, ptlrpc_hr_service::hr_partitions, ptlrpc_hr_service::hr_waitq, ptlrpc_hr_partition::hrp_cpt, ptlrpc_hr_partition::hrp_nstarted, ptlrpc_hr_partition::hrp_nthrs, ptlrpc_hr_partition::hrp_thrs, ptlrpc_hr_thread::hrt_id, ptlrpc_hr, ptlrpc_hr_main(), ptlrpc_stop_hr_threads(), and RETURN.
Referenced by ptlrpc_hr_init().
int ptlrpc_start_thread (struct ptlrpc_service_part * svcpt, int wait)
Definition at line 2782 of file service.c.
References CDEBUG, CERROR, D_INFO, D_RPCTRACE, ENTRY, l_wait_event, LASSERT, list_add(), list_del(), OBD_CPT_ALLOC_PTR, OBD_FAIL_CHECK, OBD_FAIL_TGT_TOOMANY_THREADS, OBD_FREE_PTR, ptlrpc_main(), PTLRPC_THR_NAME_LEN, ptlrpc_threads_increasable(), RETURN, ptlrpc_service_part::scp_cpt, ptlrpc_service_part::scp_nthrs_running, ptlrpc_service_part::scp_nthrs_starting, ptlrpc_service_part::scp_thr_nextid, ptlrpc_service_part::scp_threads, ptlrpc_service::srv_cptable, ptlrpc_service::srv_is_stopping, ptlrpc_service::srv_name, ptlrpc_service::srv_nthrs_cpt_init, ptlrpc_service::srv_nthrs_cpt_limit, ptlrpc_service::srv_thread_name, SVC_STARTING, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, ptlrpc_thread::t_id, ptlrpc_thread::t_link, ptlrpc_thread::t_name, ptlrpc_thread::t_svcpt, thread, thread_add_flags(), thread_is_running(), thread_is_stopped(), thread_is_stopping(), and unlikely.
Referenced by ptlrpc_main(), and ptlrpc_start_threads().
static void ptlrpc_stop_hr_threads (void) [static]
Definition at line 2620 of file service.c.
References cfs_percpt_for_each, ptlrpc_hr_service::hr_partitions, ptlrpc_hr_service::hr_stopping, ptlrpc_hr_service::hr_waitq, ptlrpc_hr_partition::hrp_nstarted, ptlrpc_hr_partition::hrp_nstopped, ptlrpc_hr_partition::hrp_nthrs, ptlrpc_hr_partition::hrp_thrs, ptlrpc_hr_thread::hrt_waitq, and ptlrpc_hr.
Referenced by ptlrpc_hr_fini(), and ptlrpc_start_hr_threads().
static int ptlrpc_svcpt_health_check (struct ptlrpc_service_part * svcpt) [static]
Returns 0 if the service is healthy.
Right now, it just checks to make sure that requests aren't languishing in the queue. We'll use this health check to govern whether a node needs to be shot, so it's intentionally non-aggressive.
Definition at line 3193 of file service.c.
References at_max, AT_OFF, CERROR, cfs_timeval_sub(), obd_timeout, ONE_MILLION, ptlrpc_nrs_req_peek_nolock(), ptlrpc_server_high_pending(), and ptlrpc_server_normal_pending().
Referenced by ptlrpc_service_health_check().
static void ptlrpc_svcpt_stop_threads (struct ptlrpc_service_part * svcpt) [static]
Definition at line 2683 of file service.c.
References CDEBUG, D_INFO, ENTRY, EXIT, INIT_LIST_HEAD, l_wait_event, list_add(), list_del(), list_empty(), list_entry, list_for_each_entry, list_head::next, OBD_FREE_PTR, ptlrpc_service_part::scp_threads, ptlrpc_service_part::scp_waitq, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, ptlrpc_thread::t_id, ptlrpc_thread::t_link, thread, thread_add_flags(), and thread_is_stopped().
Referenced by ptlrpc_stop_all_threads().
static int ptlrpc_thread_stopping (struct ptlrpc_thread * thread) [inline, static]
Definition at line 2315 of file service.c.
References ptlrpc_thread::t_svcpt, and thread_is_stopping().
Referenced by __attribute__(), and ptlrpc_main().
static int ptlrpc_threads_enough (struct ptlrpc_service_part * svcpt) [inline, static]
Definition at line 2284 of file service.c.
References ptlrpc_service_part::scp_nreqs_active, and ptlrpc_service_part::scp_nthrs_running.
Referenced by ptlrpc_threads_need_create().
static int ptlrpc_threads_increasable (struct ptlrpc_service_part * svcpt) [inline, static]
allowed to create more threads user can call it w/o any lock but need to hold ptlrpc_service_part::scp_lock to get reliable result
Definition at line 2297 of file service.c.
References ptlrpc_service_part::scp_nthrs_running, and ptlrpc_service_part::scp_nthrs_starting.
Referenced by ptlrpc_start_thread(), and ptlrpc_threads_need_create().
static int ptlrpc_threads_need_create (struct ptlrpc_service_part * svcpt) [inline, static]
too many requests and allowed to create more threads
Definition at line 2308 of file service.c.
References ptlrpc_threads_enough(), and ptlrpc_threads_increasable().
Referenced by ptlrpc_main().
static void ptlrpc_wait_replies (struct ptlrpc_service_part * svcpt) [static]
Wait until all already scheduled replies are processed.
Definition at line 2968 of file service.c.
References cfs_time_seconds(), CWARN, l_wait_event, LWI_TIMEOUT, ptlrpc_service_part::scp_nreps_difficult, and ptlrpc_service_part::scp_waitq.
Referenced by ptlrpc_service_purge_all().
static void rs_batch_add (struct rs_batch * b, struct ptlrpc_reply_state * rs) [static]
Add a reply to a batch.
Add one reply object to a batch, schedule batched replies if overload.
Parameters:
b batch
rs reply
Definition at line 324 of file service.c.
References list_move(), MAX_SCHEDULED, rs_batch_dispatch(), ptlrpc_reply_state::rs_committed, ptlrpc_reply_state::rs_list, ptlrpc_reply_state::rs_lock, ptlrpc_reply_state::rs_scheduled, ptlrpc_reply_state::rs_scheduled_ever, ptlrpc_reply_state::rs_svcpt, rs_batch::rsb_n_replies, rs_batch::rsb_replies, and rs_batch::rsb_svcpt.
Referenced by ptlrpc_commit_replies().
static void rs_batch_dispatch (struct rs_batch * b) [static]
Dispatch all replies accumulated in the batch to one from dedicated reply handling threads.
Parameters:
b batch
Definition at line 301 of file service.c.
References ptlrpc_hr_thread::hrt_lock, ptlrpc_hr_thread::hrt_queue, ptlrpc_hr_thread::hrt_waitq, list_splice_init(), ptlrpc_hr_select(), rs_batch::rsb_n_replies, rs_batch::rsb_replies, and rs_batch::rsb_svcpt.
Referenced by rs_batch_add(), and rs_batch_fini().
static void rs_batch_fini (struct rs_batch * b) [static]
Reply batch finalization.
Dispatch remaining replies from the batch and release remaining spinlock.
Parameters:
b batch
Definition at line 354 of file service.c.
References rs_batch_dispatch(), and rs_batch::rsb_svcpt.
Referenced by ptlrpc_commit_replies().
static void rs_batch_init (struct rs_batch * b) [static]
Initialize a reply batch.
Parameters:
b batch
Definition at line 264 of file service.c.
References INIT_LIST_HEAD, and rs_batch::rsb_replies.
Referenced by ptlrpc_commit_replies().
Variable Documentation
struct list_head ptlrpc_all_services
Holds a list of all PTLRPC services.
Definition at line 68 of file service.c.
Referenced by nrs_policy_unregister_locked(), ptlrpc_init(), ptlrpc_nrs_policy_register(), and ptlrpc_register_service().
struct mutex ptlrpc_all_services_mutex
Used to protect the ptlrpc_all_services list.
Definition at line 70 of file service.c.
Referenced by nrs_policy_unregister_locked(), ptlrpc_init(), ptlrpc_nrs_policy_register(), ptlrpc_nrs_policy_unregister(), ptlrpc_register_service(), and ptlrpc_unregister_service().
struct ptlrpc_hpreq_ops ptlrpc_hpreq_common [static]
Initial value:
 {
        .hpreq_check       = ptlrpc_hpreq_check,
}
Definition at line 1615 of file service.c.
struct ptlrpc_hr_service ptlrpc_hr [static]
reply handling service.
Definition at line 252 of file service.c.
Referenced by hrt_dont_sleep(), ptlrpc_hr_fini(), ptlrpc_hr_init(), ptlrpc_hr_main(), ptlrpc_hr_select(), ptlrpc_start_hr_threads(), and ptlrpc_stop_hr_threads().
int test_req_buffer_pressure = 0
Definition at line 47 of file service.c.
Referenced by ptlrpc_check_rqbd_pool(), ptlrpc_register_service(), and request_in_callback().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.