Lustre: lnet/klnds/socklnd/socklnd_proto.c File Reference
lnet/klnds/socklnd/socklnd_proto.c File Reference
#include "socklnd.h"
Functions
static ksock_tx_t * ksocknal_queue_tx_msg_v1 (ksock_conn_t *conn, ksock_tx_t *tx_msg)
void ksocknal_next_tx_carrier (ksock_conn_t *conn)
static int ksocknal_queue_tx_zcack_v2 (ksock_conn_t *conn, ksock_tx_t *tx_ack, __u64 cookie)
static ksock_tx_t * ksocknal_queue_tx_msg_v2 (ksock_conn_t *conn, ksock_tx_t *tx_msg)
static int ksocknal_queue_tx_zcack_v3 (ksock_conn_t *conn, ksock_tx_t *tx_ack, __u64 cookie)
static int ksocknal_match_tx (ksock_conn_t *conn, ksock_tx_t *tx, int nonblk)
static int ksocknal_match_tx_v3 (ksock_conn_t *conn, ksock_tx_t *tx, int nonblk)
static int ksocknal_handle_zcreq (ksock_conn_t *c, __u64 cookie, int remote)
static int ksocknal_handle_zcack (ksock_conn_t *conn, __u64 cookie1, __u64 cookie2)
static int ksocknal_send_hello_v1 (ksock_conn_t *conn, ksock_hello_msg_t *hello)
static int ksocknal_send_hello_v2 (ksock_conn_t *conn, ksock_hello_msg_t *hello)
static int ksocknal_recv_hello_v1 (ksock_conn_t *conn, ksock_hello_msg_t *hello, int timeout)
static int ksocknal_recv_hello_v2 (ksock_conn_t *conn, ksock_hello_msg_t *hello, int timeout)
static void ksocknal_pack_msg_v1 (ksock_tx_t *tx)
static void ksocknal_pack_msg_v2 (ksock_tx_t *tx)
static void ksocknal_unpack_msg_v1 (ksock_msg_t *msg)
static void ksocknal_unpack_msg_v2 (ksock_msg_t *msg)
Variables
ksock_proto_t ksocknal_protocol_v1x
ksock_proto_t ksocknal_protocol_v2x
ksock_proto_t ksocknal_protocol_v3x
Function Documentation
static int ksocknal_handle_zcack (ksock_conn_t * conn, __u64 cookie1, __u64 cookie2) [static]
Definition at line 405 of file socklnd_proto.c.
References __u64, ksock_conn::ksnc_peer, ksock_conn::ksnc_proto, ksock_peer::ksnp_lock, ksock_peer::ksnp_zc_req_list, ksocknal_protocol_v3x, ksocknal_tx_decref(), list_add(), list_del(), list_empty(), list_entry, list_for_each_entry_safe, LIST_HEAD_INIT, list_head::next, SOCKNAL_KEEPALIVE_PING, ksock_tx_t::tx_msg, and ksock_tx_t::tx_zc_list.
static int ksocknal_handle_zcreq (ksock_conn_t * c, __u64 cookie, int remote) [static]
Definition at line 362 of file socklnd_proto.c.
References ksock_conn::ksnc_peer, ksock_conn::ksnc_proto, ksock_conn::ksnc_scheduler, ksock_nal_data_t::ksnd_global_lock, ksock_peer::ksnp_id, ksock_peer::ksnp_ni, ksocknal_alloc_tx_noop(), ksocknal_data, ksocknal_find_conn_locked(), ksocknal_free_tx(), ksocknal_launch_packet(), ksock_sched_t::kss_lock, LASSERT, and ksock_proto::pro_queue_tx_zcack.
static int ksocknal_match_tx (ksock_conn_t * conn, ksock_tx_t * tx, int nonblk) [static]
Definition at line 274 of file socklnd_proto.c.
References CERROR, ksock_conn::ksnc_proto, ksock_conn::ksnc_type, ksock_tunables_t::ksnd_min_bulk, ksock_tunables_t::ksnd_typed_conns, ksocknal_protocol_v1x, ksocknal_tunables, LBUG, lnet_msg::msg_len, offsetof, SOCKLND_CONN_ANY, SOCKLND_CONN_BULK_IN, SOCKLND_CONN_BULK_OUT, SOCKLND_CONN_CONTROL, SOCKNAL_MATCH_MAY, SOCKNAL_MATCH_YES, and ksock_tx_t::tx_lnetmsg.
static int ksocknal_match_tx_v3 (ksock_conn_t * conn, ksock_tx_t * tx, int nonblk) [static]
Definition at line 318 of file socklnd_proto.c.
References CERROR, ksock_conn::ksnc_type, ksock_tunables_t::ksnd_min_bulk, ksocknal_tunables, LBUG, lnet_msg::msg_len, offsetof, SOCKLND_CONN_ACK, SOCKLND_CONN_ANY, SOCKLND_CONN_BULK_OUT, SOCKLND_CONN_CONTROL, SOCKNAL_MATCH_MAY, SOCKNAL_MATCH_NO, SOCKNAL_MATCH_YES, and ksock_tx_t::tx_lnetmsg.
void ksocknal_next_tx_carrier (ksock_conn_t * conn)
Definition at line 53 of file socklnd_proto.c.
References ksock_conn::ksnc_tx_carrier, ksock_conn::ksnc_tx_queue, LASSERT, list_empty(), list_entry, list_head::next, ksock_tx_t::tx_list, and ksock_tx_t::tx_msg.
Referenced by ksocknal_queue_tx_msg_v2(), ksocknal_queue_tx_zcack_v2(), ksocknal_queue_tx_zcack_v3(), and ksocknal_scheduler().
static void ksocknal_pack_msg_v1 (ksock_tx_t * tx) [static]
Definition at line 712 of file socklnd_proto.c.
References KSOCK_MSG_NOOP, LASSERT, lnet_msg::msg_hdr, lnet_msg::msg_len, ksock_tx_t::tx_iov, ksock_tx_t::tx_lnetmsg, ksock_tx_t::tx_msg, ksock_tx_t::tx_nob, and ksock_tx_t::tx_resid.
static void ksocknal_pack_msg_v2 (ksock_tx_t * tx) [static]
Definition at line 725 of file socklnd_proto.c.
References KSOCK_MSG_NOOP, LASSERT, lnet_msg::msg_hdr, lnet_msg::msg_len, offsetof, ksock_tx_t::tx_iov, ksock_tx_t::tx_lnetmsg, ksock_tx_t::tx_msg, ksock_tx_t::tx_nob, and ksock_tx_t::tx_resid.
static ksock_tx_t* ksocknal_queue_tx_msg_v1 (ksock_conn_t * conn, ksock_tx_t * tx_msg) [static]
Definition at line 45 of file socklnd_proto.c.
References ksock_conn::ksnc_tx_queue, list_add_tail(), and ksock_tx_t::tx_list.
static ksock_tx_t* ksocknal_queue_tx_msg_v2 (ksock_conn_t * conn, ksock_tx_t * tx_msg) [static]
Definition at line 121 of file socklnd_proto.c.
References ksock_conn::ksnc_tx_carrier, ksock_conn::ksnc_tx_queue, KSOCK_MSG_LNET, KSOCK_MSG_NOOP, ksocknal_next_tx_carrier(), LASSERT, list_add(), list_add_tail(), list_del(), ksock_tx_t::tx_list, and ksock_tx_t::tx_msg.
static int ksocknal_queue_tx_zcack_v2 (ksock_conn_t * conn, ksock_tx_t * tx_ack, __u64 cookie) [static]
Definition at line 74 of file socklnd_proto.c.
References ksock_conn::ksnc_tx_carrier, ksock_conn::ksnc_tx_queue, KSOCK_MSG_LNET, KSOCK_MSG_NOOP, ksocknal_next_tx_carrier(), LASSERT, list_add_tail(), ksock_tx_t::tx_list, and ksock_tx_t::tx_msg.
Referenced by ksocknal_queue_tx_zcack_v3().
static int ksocknal_queue_tx_zcack_v3 (ksock_conn_t * conn, ksock_tx_t * tx_ack, __u64 cookie) [static]
Definition at line 157 of file socklnd_proto.c.
References __u64, CWARN, ksock_conn::ksnc_peer, ksock_conn::ksnc_tx_carrier, ksock_conn::ksnc_tx_queue, ksock_conn::ksnc_type, ksock_peer::ksnp_id, KSOCK_MSG_NOOP, ksocknal_next_tx_carrier(), ksocknal_queue_tx_zcack_v2(), LASSERT, libcfs_id2str(), list_add_tail(), LPU64, SOCKLND_CONN_ACK, SOCKNAL_KEEPALIVE_PING, ksock_tx_t::tx_list, and ksock_tx_t::tx_msg.
static int ksocknal_recv_hello_v1 (ksock_conn_t * conn, ksock_hello_msg_t * hello, int timeout) [static]
Definition at line 569 of file socklnd_proto.c.
References CERROR, cpu_to_le32, ksock_conn::ksnc_ipaddr, ksock_conn::ksnc_sock, LASSERT, le32_to_cpu, le64_to_cpu, LIBCFS_ALLOC, LIBCFS_FREE, LNET_MAX_INTERFACES, LNET_MSG_HELLO, lnet_sock_read(), and offsetof.
static int ksocknal_recv_hello_v2 (ksock_conn_t * conn, ksock_hello_msg_t * hello, int timeout) [static]
Definition at line 645 of file socklnd_proto.c.
References __swab32s, __swab64s, CERROR, ksock_conn::ksnc_flip, ksock_conn::ksnc_ipaddr, ksock_conn::ksnc_sock, LASSERT, LNET_MAX_INTERFACES, LNET_PROTO_MAGIC, lnet_sock_read(), and offsetof.
static int ksocknal_send_hello_v1 (ksock_conn_t * conn, ksock_hello_msg_t * hello) [static]
Definition at line 452 of file socklnd_proto.c.
References CERROR, CLASSERT, CNETERR, cpu_to_le16, cpu_to_le32, cpu_to_le64, ksock_conn::ksnc_ipaddr, ksock_conn::ksnc_port, ksock_conn::ksnc_sock, KSOCK_PROTO_V1_MAJOR, KSOCK_PROTO_V1_MINOR, LIBCFS_ALLOC, LIBCFS_FREE, lnet_t::ln_testprotocompat, lnet_acceptor_timeout(), LNET_LOCK, LNET_MSG_HELLO, LNET_PROTO_MAGIC, LNET_PROTO_TCP_MAGIC, lnet_sock_write(), LNET_UNLOCK, offsetof, and the_lnet.
static int ksocknal_send_hello_v2 (ksock_conn_t * conn, ksock_hello_msg_t * hello) [static]
Definition at line 526 of file socklnd_proto.c.
References CNETERR, ksock_conn::ksnc_ipaddr, ksock_conn::ksnc_port, ksock_conn::ksnc_proto, ksock_conn::ksnc_sock, lnet_t::ln_testprotocompat, lnet_acceptor_timeout(), LNET_LOCK, LNET_PROTO_MAGIC, lnet_sock_write(), LNET_UNLOCK, offsetof, ksock_proto::pro_version, and the_lnet.
static void ksocknal_unpack_msg_v1 (ksock_msg_t * msg) [static]
Definition at line 745 of file socklnd_proto.c.
References KSOCK_MSG_LNET.
static void ksocknal_unpack_msg_v2 (ksock_msg_t * msg) [static]
Definition at line 753 of file socklnd_proto.c.
Variable Documentation
ksock_proto_t ksocknal_protocol_v1x
Initial value:
{
        .pro_version            = KSOCK_PROTO_V1,
        .pro_send_hello         = ksocknal_send_hello_v1,
        .pro_recv_hello         = ksocknal_recv_hello_v1,
        .pro_pack               = ksocknal_pack_msg_v1,
        .pro_unpack             = ksocknal_unpack_msg_v1,
        .pro_queue_tx_msg       = ksocknal_queue_tx_msg_v1,
        .pro_handle_zcreq       = NULL,
        .pro_handle_zcack       = NULL,
        .pro_queue_tx_zcack     = NULL,
        .pro_match_tx           = ksocknal_match_tx
}
Definition at line 758 of file socklnd_proto.c.
Referenced by ksocknal_check_zc_req(), ksocknal_create_conn(), ksocknal_lib_zc_capable(), ksocknal_match_tx(), ksocknal_parse_proto_version(), ksocknal_process_receive(), and ksocknal_recv_hello().
ksock_proto_t ksocknal_protocol_v2x
Initial value:
{
        .pro_version            = KSOCK_PROTO_V2,
        .pro_send_hello         = ksocknal_send_hello_v2,
        .pro_recv_hello         = ksocknal_recv_hello_v2,
        .pro_pack               = ksocknal_pack_msg_v2,
        .pro_unpack             = ksocknal_unpack_msg_v2,
        .pro_queue_tx_msg       = ksocknal_queue_tx_msg_v2,
        .pro_queue_tx_zcack     = ksocknal_queue_tx_zcack_v2,
        .pro_handle_zcreq       = ksocknal_handle_zcreq,
        .pro_handle_zcack       = ksocknal_handle_zcack,
        .pro_match_tx           = ksocknal_match_tx
}
Definition at line 772 of file socklnd_proto.c.
Referenced by ksocknal_create_conn(), ksocknal_lib_csum_tx(), ksocknal_lib_recv_iov(), ksocknal_lib_send_iov(), ksocknal_parse_proto_version(), and ksocknal_recv_hello().
ksock_proto_t ksocknal_protocol_v3x
Initial value:
{
        .pro_version            = KSOCK_PROTO_V3,
        .pro_send_hello         = ksocknal_send_hello_v2,
        .pro_recv_hello         = ksocknal_recv_hello_v2,
        .pro_pack               = ksocknal_pack_msg_v2,
        .pro_unpack             = ksocknal_unpack_msg_v2,
        .pro_queue_tx_msg       = ksocknal_queue_tx_msg_v2,
        .pro_queue_tx_zcack     = ksocknal_queue_tx_zcack_v3,
        .pro_handle_zcreq       = ksocknal_handle_zcreq,
        .pro_handle_zcack       = ksocknal_handle_zcack,
        .pro_match_tx           = ksocknal_match_tx_v3
}
Definition at line 786 of file socklnd_proto.c.
Referenced by ksocknal_close_conn_locked(), ksocknal_connect(), ksocknal_create_conn(), ksocknal_handle_zcack(), ksocknal_parse_proto_version(), ksocknal_recv_hello(), and ksocknal_send_keepalive_locked().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.