Lustre: lnet/klnds/socklnd/socklnd_lib.c File Reference
lnet/klnds/socklnd/socklnd_lib.c File Reference
#include "socklnd.h"
Functions
int ksocknal_lib_get_conn_addrs (ksock_conn_t *conn)
int ksocknal_lib_zc_capable (ksock_conn_t *conn)
int ksocknal_lib_send_iov (ksock_conn_t *conn, ksock_tx_t *tx)
int ksocknal_lib_send_kiov (ksock_conn_t *conn, ksock_tx_t *tx)
void ksocknal_lib_eager_ack (ksock_conn_t *conn)
int ksocknal_lib_recv_iov (ksock_conn_t *conn)
static void ksocknal_lib_kiov_vunmap (void *addr)
static void * ksocknal_lib_kiov_vmap (lnet_kiov_t *kiov, int niov, struct kvec *iov, struct page **pages)
int ksocknal_lib_recv_kiov (ksock_conn_t *conn)
void ksocknal_lib_csum_tx (ksock_tx_t *tx)
int ksocknal_lib_get_conn_tunables (ksock_conn_t *conn, int *txmem, int *rxmem, int *nagle)
int ksocknal_lib_setup_sock (struct socket *sock)
void ksocknal_lib_push_conn (ksock_conn_t *conn)
void ksocknal_read_callback (ksock_conn_t *conn)
void ksocknal_write_callback (ksock_conn_t *conn)
static void ksocknal_data_ready (struct sock *sk, int n)
static void ksocknal_write_space (struct sock *sk)
void ksocknal_lib_save_callback (struct socket *sock, ksock_conn_t *conn)
void ksocknal_lib_set_callback (struct socket *sock, ksock_conn_t *conn)
void ksocknal_lib_reset_callback (struct socket *sock, ksock_conn_t *conn)
int ksocknal_lib_memory_pressure (ksock_conn_t *conn)
Function Documentation
static void ksocknal_data_ready (struct sock * sk, int n) [static]
Definition at line 627 of file socklnd_lib.c.
References ENTRY, EXIT, ksock_nal_data_t::ksnd_global_lock, ksocknal_data, ksocknal_read_callback(), and LASSERT.
Referenced by ksocknal_lib_set_callback().
void ksocknal_lib_csum_tx (ksock_tx_t * tx)
Definition at line 387 of file socklnd_lib.c.
References lnet_kiov_t::kiov_len, lnet_kiov_t::kiov_offset, lnet_kiov_t::kiov_page, ksock_conn::ksnc_proto, ksock_tunables_t::ksnd_inject_csum_error, ksocknal_csum(), ksocknal_protocol_v2x, ksocknal_tunables, LASSERT, ksock_tx_t::tx_conn, ksock_tx_t::tx_iov, ksock_tx_t::tx_kiov, ksock_tx_t::tx_msg, ksock_tx_t::tx_niov, and ksock_tx_t::tx_nkiov.
Referenced by ksocknal_lib_send_iov().
void ksocknal_lib_eager_ack (ksock_conn_t * conn)
Definition at line 188 of file socklnd_lib.c.
References ksock_conn::ksnc_sock, and opt.
Referenced by ksocknal_new_packet().
int ksocknal_lib_get_conn_addrs (ksock_conn_t * conn)
Definition at line 40 of file socklnd_lib.c.
References CERROR, ksock_conn::ksnc_closing, ksock_conn::ksnc_ipaddr, ksock_conn::ksnc_myipaddr, ksock_conn::ksnc_port, ksock_conn::ksnc_sock, LASSERT, and lnet_sock_getaddr().
Referenced by ksocknal_create_conn().
int ksocknal_lib_get_conn_tunables (ksock_conn_t * conn, int * txmem, int * rxmem, int * nagle)
Definition at line 426 of file socklnd_lib.c.
References ksock_conn::ksnc_closing, ksock_conn::ksnc_sock, ksocknal_connsock_addref(), ksocknal_connsock_decref(), LASSERT, and lnet_sock_getbuf().
Referenced by ksocknal_ctl().
static void* ksocknal_lib_kiov_vmap (lnet_kiov_t * kiov, int niov, struct kvec * iov, struct page ** pages) [static]
Definition at line 271 of file socklnd_lib.c.
References lnet_kiov_t::kiov_len, lnet_kiov_t::kiov_offset, lnet_kiov_t::kiov_page, ksock_tunables_t::ksnd_zc_recv, ksock_tunables_t::ksnd_zc_recv_min_nfrags, ksocknal_tunables, LASSERT, and LNET_MAX_IOV.
Referenced by ksocknal_lib_recv_kiov().
static void ksocknal_lib_kiov_vunmap (void * addr) [static]
Definition at line 262 of file socklnd_lib.c.
Referenced by ksocknal_lib_recv_kiov().
int ksocknal_lib_memory_pressure (ksock_conn_t * conn)
Definition at line 732 of file socklnd_lib.c.
References ksock_conn::ksnc_scheduler, ksock_conn::ksnc_sock, ksock_conn::ksnc_tx_ready, and ksock_sched_t::kss_lock.
Referenced by ksocknal_transmit().
void ksocknal_lib_push_conn (ksock_conn_t * conn)
Definition at line 587 of file socklnd_lib.c.
References ksock_conn::ksnc_sock, ksocknal_connsock_addref(), ksocknal_connsock_decref(), and LASSERT.
Referenced by ksocknal_push_peer().
int ksocknal_lib_recv_iov (ksock_conn_t * conn)
Definition at line 203 of file socklnd_lib.c.
References ksock_conn::ksnc_msg, ksock_conn::ksnc_proto, ksock_conn::ksnc_rx_csum, ksock_conn::ksnc_rx_iov, ksock_conn::ksnc_rx_niov, ksock_conn::ksnc_scheduler, ksock_conn::ksnc_sock, ksocknal_csum(), ksocknal_protocol_v2x, ksock_sched_t::kss_scratch_iov, and LASSERT.
Referenced by ksocknal_recv_iov().
int ksocknal_lib_recv_kiov (ksock_conn_t * conn)
Definition at line 308 of file socklnd_lib.c.
References lnet_kiov_t::kiov_len, lnet_kiov_t::kiov_offset, ksock_conn::ksnc_msg, ksock_conn::ksnc_rx_csum, ksock_conn::ksnc_rx_kiov, ksock_conn::ksnc_rx_nkiov, ksock_conn::ksnc_scheduler, ksock_conn::ksnc_sock, ksocknal_csum(), ksocknal_lib_kiov_vmap(), ksocknal_lib_kiov_vunmap(), ksock_sched_t::kss_rx_scratch_pgs, ksock_sched_t::kss_scratch_iov, and LASSERT.
Referenced by ksocknal_recv_kiov().
void ksocknal_lib_reset_callback (struct socket * sock, ksock_conn_t * conn)
Definition at line 715 of file socklnd_lib.c.
References ksock_conn::ksnc_saved_data_ready, and ksock_conn::ksnc_saved_write_space.
Referenced by ksocknal_terminate_conn().
void ksocknal_lib_save_callback (struct socket * sock, ksock_conn_t * conn)
Definition at line 699 of file socklnd_lib.c.
References ksock_conn::ksnc_saved_data_ready, and ksock_conn::ksnc_saved_write_space.
Referenced by ksocknal_create_conn().
int ksocknal_lib_send_iov (ksock_conn_t * conn, ksock_tx_t * tx)
Definition at line 78 of file socklnd_lib.c.
References ksock_conn::ksnc_proto, ksock_conn::ksnc_scheduler, ksock_conn::ksnc_sock, ksock_conn::ksnc_tx_queue, ksock_tunables_t::ksnd_enable_csum, ksocknal_lib_csum_tx(), ksocknal_protocol_v2x, ksocknal_tunables, ksock_sched_t::kss_scratch_iov, list_empty(), ksock_tx_t::tx_iov, ksock_tx_t::tx_msg, ksock_tx_t::tx_niov, ksock_tx_t::tx_nob, and ksock_tx_t::tx_resid.
Referenced by ksocknal_send_iov().
int ksocknal_lib_send_kiov (ksock_conn_t * conn, ksock_tx_t * tx)
Definition at line 120 of file socklnd_lib.c.
References CDEBUG, cfs_tcp_sendpage, D_NET, lnet_kiov_t::kiov_len, lnet_kiov_t::kiov_offset, lnet_kiov_t::kiov_page, ksock_conn::ksnc_scheduler, ksock_conn::ksnc_sock, ksock_conn::ksnc_tx_queue, ksock_sched_t::kss_scratch_iov, LASSERT, list_empty(), ksock_tx_t::tx_kiov, ksock_tx_t::tx_lnetmsg, ksock_tx_t::tx_msg, and ksock_tx_t::tx_nkiov.
Referenced by ksocknal_send_kiov().
void ksocknal_lib_set_callback (struct socket * sock, ksock_conn_t * conn)
Definition at line 706 of file socklnd_lib.c.
References ksocknal_data_ready(), and ksocknal_write_space().
Referenced by ksocknal_create_conn().
int ksocknal_lib_setup_sock (struct socket * sock)
Definition at line 457 of file socklnd_lib.c.
References CERROR, ksock_tunables_t::ksnd_keepalive_count, ksock_tunables_t::ksnd_keepalive_idle, ksock_tunables_t::ksnd_keepalive_intvl, ksock_tunables_t::ksnd_nagle, ksock_tunables_t::ksnd_rx_buffer_size, ksock_tunables_t::ksnd_tx_buffer_size, ksocknal_tunables, and lnet_sock_setbuf().
Referenced by ksocknal_create_conn().
int ksocknal_lib_zc_capable (ksock_conn_t * conn)
Definition at line 65 of file socklnd_lib.c.
References ksock_conn::ksnc_proto, ksock_conn::ksnc_sock, and ksocknal_protocol_v1x.
Referenced by ksocknal_create_conn().
void ksocknal_read_callback (ksock_conn_t * conn)
Definition at line 1559 of file socklnd_cb.c.
References ENTRY, EXIT, ksock_conn::ksnc_rx_list, ksock_conn::ksnc_rx_ready, ksock_conn::ksnc_rx_scheduled, ksock_conn::ksnc_scheduler, ksocknal_conn_addref(), ksock_sched_t::kss_lock, ksock_sched_t::kss_rx_conns, ksock_sched_t::kss_waitq, and list_add_tail().
void ksocknal_write_callback (ksock_conn_t * conn)
Definition at line 1588 of file socklnd_cb.c.
References ENTRY, EXIT, ksock_conn::ksnc_scheduler, ksock_conn::ksnc_tx_list, ksock_conn::ksnc_tx_queue, ksock_conn::ksnc_tx_ready, ksock_conn::ksnc_tx_scheduled, ksocknal_conn_addref(), ksock_sched_t::kss_lock, ksock_sched_t::kss_tx_conns, ksock_sched_t::kss_waitq, list_add_tail(), and list_empty().
static void ksocknal_write_space (struct sock * sk) [static]
Definition at line 654 of file socklnd_lib.c.
References CDEBUG, D_NET, ksock_conn::ksnc_tx_queue, ksock_conn::ksnc_tx_ready, ksock_conn::ksnc_tx_scheduled, ksock_nal_data_t::ksnd_global_lock, ksocknal_data, ksocknal_write_callback(), LASSERT, and list_empty().
Referenced by ksocknal_lib_set_callback().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.