Lustre: lnet/klnds/socklnd/socklnd.c File Reference
lnet/klnds/socklnd/socklnd.c File Reference
#include "socklnd.h"
Functions
static ksock_interface_t * ksocknal_ip2iface (lnet_ni_t *ni, __u32 ip)
static ksock_route_t * ksocknal_create_route (__u32 ipaddr, int port)
void ksocknal_destroy_route (ksock_route_t *route)
static int ksocknal_create_peer (ksock_peer_t **peerp, lnet_ni_t *ni, lnet_process_id_t id)
void ksocknal_destroy_peer (ksock_peer_t *peer)
ksock_peer_t * ksocknal_find_peer_locked (lnet_ni_t *ni, lnet_process_id_t id)
ksock_peer_t * ksocknal_find_peer (lnet_ni_t *ni, lnet_process_id_t id)
static void ksocknal_unlink_peer_locked (ksock_peer_t *peer)
static int ksocknal_get_peer_info (lnet_ni_t *ni, int index, lnet_process_id_t *id, __u32 *myip, __u32 *peer_ip, int *port, int *conn_count, int *share_count)
static void ksocknal_associate_route_conn_locked (ksock_route_t *route, ksock_conn_t *conn)
static void ksocknal_add_route_locked (ksock_peer_t *peer, ksock_route_t *route)
static void ksocknal_del_route_locked (ksock_route_t *route)
int ksocknal_add_peer (lnet_ni_t *ni, lnet_process_id_t id, __u32 ipaddr, int port)
static void ksocknal_del_peer_locked (ksock_peer_t *peer, __u32 ip)
static int ksocknal_del_peer (lnet_ni_t *ni, lnet_process_id_t id, __u32 ip)
static ksock_conn_t * ksocknal_get_conn_by_idx (lnet_ni_t *ni, int index)
static ksock_sched_t * ksocknal_choose_scheduler_locked (unsigned int cpt)
static int ksocknal_local_ipvec (lnet_ni_t *ni, __u32 *ipaddrs)
static int ksocknal_match_peerip (ksock_interface_t *iface, __u32 *ips, int nips)
static int ksocknal_select_ips (ksock_peer_t *peer, __u32 *peerips, int n_peerips)
static void ksocknal_create_routes (ksock_peer_t *peer, int port, __u32 *peer_ipaddrs, int npeer_ipaddrs)
int ksocknal_accept (lnet_ni_t *ni, struct socket *sock)
static int ksocknal_connecting (ksock_peer_t *peer, __u32 ipaddr)
int ksocknal_create_conn (lnet_ni_t *ni, ksock_route_t *route, struct socket *sock, int type)
void ksocknal_close_conn_locked (ksock_conn_t *conn, int error)
void ksocknal_peer_failed (ksock_peer_t *peer)
void ksocknal_finalize_zcreq (ksock_conn_t *conn)
void ksocknal_terminate_conn (ksock_conn_t *conn)
void ksocknal_queue_zombie_conn (ksock_conn_t *conn)
void ksocknal_destroy_conn (ksock_conn_t *conn)
int ksocknal_close_peer_conns_locked (ksock_peer_t *peer, __u32 ipaddr, int why)
int ksocknal_close_conn_and_siblings (ksock_conn_t *conn, int why)
int ksocknal_close_matching_conns (lnet_process_id_t id, __u32 ipaddr)
void ksocknal_notify (lnet_ni_t *ni, lnet_nid_t gw_nid, int alive)
void ksocknal_query (lnet_ni_t *ni, lnet_nid_t nid, cfs_time_t *when)
static void ksocknal_push_peer (ksock_peer_t *peer)
static int ksocknal_push (lnet_ni_t *ni, lnet_process_id_t id)
static int ksocknal_add_interface (lnet_ni_t *ni, __u32 ipaddress, __u32 netmask)
static void ksocknal_peer_del_interface_locked (ksock_peer_t *peer, __u32 ipaddr)
static int ksocknal_del_interface (lnet_ni_t *ni, __u32 ipaddress)
int ksocknal_ctl (lnet_ni_t *ni, unsigned int cmd, void *arg)
static void ksocknal_free_buffers (void)
static void ksocknal_base_shutdown (void)
static __u64 ksocknal_new_incarnation (void)
static int ksocknal_base_startup (void)
static void ksocknal_debug_peerhash (lnet_ni_t *ni)
void ksocknal_shutdown (lnet_ni_t *ni)
static int ksocknal_enumerate_interfaces (ksock_net_t *net)
static int ksocknal_search_new_ipif (ksock_net_t *net)
static int ksocknal_start_schedulers (struct ksock_sched_info *info)
static int ksocknal_net_start_threads (ksock_net_t *net, __u32 *cpts, int ncpts)
int ksocknal_startup (lnet_ni_t *ni)
static void __exit ksocklnd_exit (void)
static int __init ksocklnd_init (void)
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("TCP Socket LNet Network Driver")
MODULE_VERSION ("2.8.0")
MODULE_LICENSE ("GPL")
module_init (ksocklnd_init)
module_exit (ksocklnd_exit)
Variables
static lnd_t the_ksocklnd
ksock_nal_data_t ksocknal_data
Function Documentation
static void __exit ksocklnd_exit (void) [static]
Definition at line 2866 of file socklnd.c.
References lnet_unregister_lnd().
static int __init ksocklnd_init (void) [static]
Definition at line 2871 of file socklnd.c.
References CLASSERT, ksocknal_accept(), ksocknal_ctl(), ksocknal_notify(), ksocknal_query(), ksocknal_recv(), ksocknal_send(), ksocknal_shutdown(), ksocknal_startup(), ksocknal_tunables_init(), lnet_lnd::lnd_accept, lnet_lnd::lnd_ctl, lnet_lnd::lnd_notify, lnet_lnd::lnd_query, lnet_lnd::lnd_recv, lnet_lnd::lnd_send, lnet_lnd::lnd_shutdown, lnet_lnd::lnd_startup, lnet_lnd::lnd_type, lnet_register_lnd(), SOCKLND, SOCKLND_CONN_ACK, SOCKLND_CONN_BULK_IN, and SOCKLND_CONN_NTYPES.
int ksocknal_accept (lnet_ni_t * ni, struct socket * sock)
Definition at line 973 of file socklnd.c.
References ksock_connreq::ksncr_list, ksock_connreq::ksncr_ni, ksock_connreq::ksncr_sock, ksock_nal_data_t::ksnd_connd_connreqs, ksock_nal_data_t::ksnd_connd_lock, ksock_nal_data_t::ksnd_connd_waitq, LASSERT, LCONSOLE_ERROR_MSG, LIBCFS_ALLOC, list_add_tail(), lnet_ni_addref(), and lnet_sock_getaddr().
Referenced by ksocklnd_init().
static int ksocknal_add_interface (lnet_ni_t * ni, __u32 ipaddress, __u32 netmask) [static]
Definition at line 1943 of file socklnd.c.
References ksock_nal_data_t::ksnd_global_lock, ksock_nal_data_t::ksnd_peer_hash_size, ksock_nal_data_t::ksnd_peers, ksock_interface_t::ksni_ipaddr, ksock_interface_t::ksni_netmask, ksock_interface_t::ksni_npeers, ksock_interface_t::ksni_nroutes, ksock_net_t::ksnn_interfaces, ksock_net_t::ksnn_ninterfaces, ksock_peer::ksnp_n_passive_ips, ksock_peer::ksnp_passive_ips, ksock_peer::ksnp_routes, ksock_route::ksnr_myipaddr, ksocknal_ip2iface(), list_entry, list_for_each, LNET_MAX_INTERFACES, and lnet_ni::ni_data.
Referenced by ksocknal_ctl().
int ksocknal_add_peer (lnet_ni_t * ni, lnet_process_id_t id, __u32 ipaddr, int port)
Definition at line 448 of file socklnd.c.
References ksock_nal_data_t::ksnd_global_lock, ksock_peer::ksnp_list, ksock_peer::ksnp_routes, ksock_route::ksnr_ipaddr, ksock_route::ksnr_share_count, ksocknal_add_route_locked(), ksocknal_create_peer(), ksocknal_create_route(), ksocknal_find_peer_locked(), ksocknal_nid2peerlist(), ksocknal_peer_decref(), ksocknal_route_decref(), LASSERT, list_add_tail(), list_entry, list_for_each, LNET_NID_ANY, LNET_PID_ANY, and lnet_ni::ni_data.
Referenced by ksocknal_ctl(), ksocknal_launch_packet(), and ksocknal_query().
static void ksocknal_add_route_locked (ksock_peer_t * peer, ksock_route_t * route) [static]
Definition at line 367 of file socklnd.c.
References CERROR, ksock_conn::ksnc_ipaddr, ksock_peer::ksnp_closing, ksock_peer::ksnp_conns, ksock_peer::ksnp_id, ksock_peer::ksnp_routes, ksock_route::ksnr_connected, ksock_route::ksnr_connecting, ksock_route::ksnr_ipaddr, ksock_route::ksnr_list, ksock_route::ksnr_peer, ksock_route::ksnr_scheduled, ksocknal_associate_route_conn_locked(), ksocknal_peer_addref(), LASSERT, LBUG, libcfs_id2str(), list_add_tail(), list_entry, and list_for_each.
Referenced by ksocknal_add_peer(), and ksocknal_create_routes().
static void ksocknal_associate_route_conn_locked (ksock_route_t * route, ksock_conn_t * conn) [static]
Definition at line 323 of file socklnd.c.
References CDEBUG, D_NET, ksock_conn::ksnc_myipaddr, ksock_conn::ksnc_route, ksock_conn::ksnc_type, ksock_interface_t::ksni_nroutes, ksock_peer::ksnp_id, ksock_peer::ksnp_ni, ksock_route::ksnr_conn_count, ksock_route::ksnr_connected, ksock_route::ksnr_ipaddr, ksock_route::ksnr_myipaddr, ksock_route::ksnr_peer, ksock_route::ksnr_retry_interval, ksocknal_ip2iface(), ksocknal_route_addref(), and libcfs_id2str().
Referenced by ksocknal_add_route_locked(), and ksocknal_create_conn().
static void ksocknal_base_shutdown (void) [static]
Definition at line 2264 of file socklnd.c.
References CDEBUG, cfs_percpt_for_each, cfs_time_seconds(), D_MALLOC, D_NET, D_WARNING, ksock_sched_info::ksi_nthreads_max, ksock_sched_info::ksi_scheds, ksock_nal_data_t::ksnd_connd_connreqs, ksock_nal_data_t::ksnd_connd_routes, ksock_nal_data_t::ksnd_connd_waitq, ksock_nal_data_t::ksnd_enomem_conns, ksock_nal_data_t::ksnd_global_lock, ksock_nal_data_t::ksnd_init, ksock_nal_data_t::ksnd_nets, ksock_nal_data_t::ksnd_nnets, ksock_nal_data_t::ksnd_nthreads, ksock_nal_data_t::ksnd_peer_hash_size, ksock_nal_data_t::ksnd_peers, ksock_nal_data_t::ksnd_reaper_waitq, ksock_nal_data_t::ksnd_sched_info, ksock_nal_data_t::ksnd_shuttingdown, ksock_nal_data_t::ksnd_zombie_conns, ksocknal_free_buffers(), ksock_sched_t::kss_nconns, ksock_sched_t::kss_waitq, LASSERT, libcfs_kmemory, list_empty(), SOCKNAL_INIT_ALL, SOCKNAL_INIT_DATA, and SOCKNAL_INIT_NOTHING.
Referenced by ksocknal_base_startup(), ksocknal_shutdown(), and ksocknal_startup().
static int ksocknal_base_startup (void) [static]
Definition at line 2372 of file socklnd.c.
References CERROR, cfs_cpt_weight(), cfs_percpt_alloc(), cfs_percpt_for_each, cfs_time_current_sec(), INIT_LIST_HEAD, ksock_sched_info::ksi_cpt, ksock_sched_info::ksi_nthreads_max, ksock_sched_info::ksi_scheds, ksock_nal_data_t::ksnd_connd_connreqs, ksock_nal_data_t::ksnd_connd_failed_stamp, ksock_nal_data_t::ksnd_connd_lock, ksock_nal_data_t::ksnd_connd_routes, ksock_nal_data_t::ksnd_connd_starting, ksock_nal_data_t::ksnd_connd_starting_stamp, ksock_nal_data_t::ksnd_connd_waitq, ksock_nal_data_t::ksnd_deathrow_conns, ksock_nal_data_t::ksnd_enomem_conns, ksock_nal_data_t::ksnd_global_lock, ksock_nal_data_t::ksnd_idle_noop_txs, ksock_nal_data_t::ksnd_init, ksock_tunables_t::ksnd_nconnds, ksock_tunables_t::ksnd_nconnds_max, ksock_nal_data_t::ksnd_nets, ksock_nal_data_t::ksnd_nnets, ksock_tunables_t::ksnd_nscheds, ksock_nal_data_t::ksnd_peer_hash_size, ksock_nal_data_t::ksnd_peers, ksock_nal_data_t::ksnd_reaper_lock, ksock_nal_data_t::ksnd_reaper_waitq, ksock_nal_data_t::ksnd_sched_info, ksock_nal_data_t::ksnd_tx_lock, ksock_nal_data_t::ksnd_zombie_conns, ksocknal_base_shutdown(), ksocknal_connd(), ksocknal_reaper(), ksocknal_thread_start(), ksocknal_tunables, ksock_sched_t::kss_info, ksock_sched_t::kss_lock, ksock_sched_t::kss_rx_conns, ksock_sched_t::kss_tx_conns, ksock_sched_t::kss_waitq, ksock_sched_t::kss_zombie_noop_txs, LASSERT, LIBCFS_ALLOC, LIBCFS_CPT_ALLOC, lnet_cpt_table, max, name, SOCKNAL_CONND_RESV, SOCKNAL_INIT_ALL, SOCKNAL_INIT_DATA, SOCKNAL_INIT_NOTHING, SOCKNAL_NSCHEDS, and SOCKNAL_PEER_HASH_SIZE.
Referenced by ksocknal_startup().
static ksock_sched_t* ksocknal_choose_scheduler_locked (unsigned int cpt) [static]
Definition at line 666 of file socklnd.c.
References ksock_sched_info::ksi_nthreads, ksock_sched_info::ksi_scheds, ksock_nal_data_t::ksnd_sched_info, ksock_sched_t::kss_nconns, and LASSERT.
Referenced by ksocknal_create_conn().
int ksocknal_close_conn_and_siblings (ksock_conn_t * conn, int why)
Definition at line 1716 of file socklnd.c.
References ksock_conn::ksnc_ipaddr, ksock_conn::ksnc_peer, ksock_nal_data_t::ksnd_global_lock, and ksocknal_close_peer_conns_locked().
Referenced by ksocknal_check_peer_timeouts(), ksocknal_process_receive(), and ksocknal_process_transmit().
void ksocknal_close_conn_locked (ksock_conn_t * conn, int error)
Definition at line 1404 of file socklnd.c.
References ksock_conn::ksnc_closing, ksock_conn::ksnc_list, ksock_conn::ksnc_peer, ksock_conn::ksnc_proto, ksock_conn::ksnc_route, ksock_conn::ksnc_scheduler, ksock_conn::ksnc_tx_queue, ksock_conn::ksnc_type, ksock_nal_data_t::ksnd_deathrow_conns, ksock_nal_data_t::ksnd_reaper_lock, ksock_nal_data_t::ksnd_reaper_waitq, ksock_peer::ksnp_conns, ksock_peer::ksnp_error, ksock_peer::ksnp_proto, ksock_peer::ksnp_routes, ksock_peer::ksnp_tx_queue, ksock_route::ksnr_connected, ksock_route::ksnr_deleted, ksock_route::ksnr_list, ksocknal_protocol_v3x, ksocknal_route_decref(), ksocknal_tx_prep(), ksocknal_unlink_peer_locked(), ksock_sched_t::kss_lock, LASSERT, list_add_tail(), list_del(), list_empty(), list_entry, list_for_each, list_for_each_entry, and list_splice_init().
Referenced by ksocknal_close_peer_conns_locked(), ksocknal_create_conn(), ksocknal_del_peer_locked(), ksocknal_del_route_locked(), and ksocknal_peer_del_interface_locked().
int ksocknal_close_matching_conns (lnet_process_id_t id, __u32 ipaddr)
Definition at line 1732 of file socklnd.c.
References ksock_nal_data_t::ksnd_global_lock, ksock_nal_data_t::ksnd_peer_hash_size, ksock_nal_data_t::ksnd_peers, ksock_peer::ksnp_id, ksocknal_close_peer_conns_locked(), ksocknal_nid2peerlist(), list_entry, list_for_each_safe, LNET_NID_ANY, LNET_PID_ANY, lnet_process_id_t::nid, and lnet_process_id_t::pid.
Referenced by ksocknal_ctl(), and ksocknal_notify().
int ksocknal_close_peer_conns_locked (ksock_peer_t * peer, __u32 ipaddr, int why)
Definition at line 1695 of file socklnd.c.
References ksock_conn::ksnc_ipaddr, ksock_peer::ksnp_conns, ksocknal_close_conn_locked(), list_entry, and list_for_each_safe.
Referenced by ksocknal_close_conn_and_siblings(), ksocknal_close_matching_conns(), and ksocknal_create_conn().
static int ksocknal_connecting (ksock_peer_t * peer, __u32 ipaddr) [static]
Definition at line 1004 of file socklnd.c.
References ksock_peer::ksnp_routes, ksock_route::ksnr_connecting, ksock_route::ksnr_ipaddr, and list_for_each_entry.
Referenced by ksocknal_create_conn().
int ksocknal_create_conn (lnet_ni_t * ni, ksock_route_t * route, struct socket * sock, int type)
Definition at line 1016 of file socklnd.c.
References __u64, CDEBUG, CERROR, cfs_time_current(), cfs_time_shift(), D_NET, INIT_LIST_HEAD, ksock_sched_info::ksi_scheds, ksock_conn::ksnc_closing, ksock_conn::ksnc_conn_refcount, ksock_conn::ksnc_ipaddr, ksock_conn::ksnc_list, ksock_conn::ksnc_myipaddr, ksock_conn::ksnc_peer, ksock_conn::ksnc_port, ksock_conn::ksnc_proto, ksock_conn::ksnc_route, ksock_conn::ksnc_rx_ready, ksock_conn::ksnc_rx_scheduled, ksock_conn::ksnc_scheduler, ksock_conn::ksnc_sock, ksock_conn::ksnc_sock_refcount, ksock_conn::ksnc_tx_bufnob, ksock_conn::ksnc_tx_carrier, ksock_conn::ksnc_tx_deadline, ksock_conn::ksnc_tx_last_post, ksock_conn::ksnc_tx_nob, ksock_conn::ksnc_tx_queue, ksock_conn::ksnc_tx_ready, ksock_conn::ksnc_tx_scheduled, ksock_conn::ksnc_type, ksock_conn::ksnc_zc_capable, ksock_nal_data_t::ksnd_global_lock, ksock_tunables_t::ksnd_timeout, ksock_peer::ksnp_accepting, ksock_peer::ksnp_closing, ksock_peer::ksnp_conns, ksock_peer::ksnp_error, ksock_peer::ksnp_id, ksock_peer::ksnp_incarnation, ksock_peer::ksnp_last_alive, ksock_peer::ksnp_list, ksock_peer::ksnp_ni, ksock_peer::ksnp_proto, ksock_peer::ksnp_routes, ksock_peer::ksnp_send_keepalive, ksock_peer::ksnp_tx_queue, ksock_route::ksnr_deleted, ksock_route::ksnr_ipaddr, ksock_route::ksnr_peer, ksocknal_associate_route_conn_locked(), ksocknal_choose_scheduler_locked(), ksocknal_close_conn_locked(), ksocknal_close_peer_conns_locked(), ksocknal_conn_addref(), ksocknal_conn_decref(), ksocknal_connecting(), ksocknal_connsock_addref(), ksocknal_connsock_decref(), ksocknal_create_peer(), ksocknal_create_routes(), ksocknal_find_peer_locked(), ksocknal_lib_get_conn_addrs(), ksocknal_lib_save_callback(), ksocknal_lib_set_callback(), ksocknal_lib_setup_sock(), ksocknal_lib_zc_capable(), ksocknal_local_ipvec(), ksocknal_new_packet(), ksocknal_nid2peerlist(), ksocknal_peer_addref(), ksocknal_peer_decref(), ksocknal_protocol_v1x, ksocknal_protocol_v2x, ksocknal_protocol_v3x, ksocknal_queue_tx_locked(), ksocknal_read_callback(), ksocknal_recv_hello(), ksocknal_select_ips(), ksocknal_send_hello(), ksocknal_tunables, ksocknal_txlist_done(), ksocknal_unlink_peer_locked(), ksocknal_write_callback(), ksock_sched_t::kss_info, ksock_sched_t::kss_nconns, LASSERT, LBUG, LIBCFS_ALLOC, LIBCFS_FREE, libcfs_id2str(), list_add(), list_add_tail(), list_del(), list_del_init(), list_empty(), list_entry, list_for_each, list_for_each_entry_safe, LIST_HEAD_INIT, lnet_cpt_of_nid(), LNET_MAX_INTERFACES, LNET_NID_ANY, LNET_PID_ANY, lnet_ni::ni_data, lnet_ni::ni_nid, lnet_process_id_t::nid, offsetof, lnet_process_id_t::pid, ksock_proto::pro_match_tx, ksock_proto::pro_version, SOCKLND_CONN_NONE, SOCKNAL_MATCH_NO, ksock_tx_t::tx_list, ksock_tx_t::tx_nonblk, and warn().
Referenced by ksocknal_connd(), and ksocknal_connect().
static int ksocknal_create_peer (ksock_peer_t ** peerp, lnet_ni_t * ni, lnet_process_id_t id) [static]
Definition at line 103 of file socklnd.c.
References CERROR, INIT_LIST_HEAD, ksock_net_t::ksnn_lock, ksock_net_t::ksnn_npeers, ksock_net_t::ksnn_shutdown, ksock_peer::ksnp_accepting, ksock_peer::ksnp_closing, ksock_peer::ksnp_conns, ksock_peer::ksnp_id, ksock_peer::ksnp_last_alive, ksock_peer::ksnp_lock, ksock_peer::ksnp_ni, ksock_peer::ksnp_proto, ksock_peer::ksnp_refcount, ksock_peer::ksnp_routes, ksock_peer::ksnp_tx_queue, ksock_peer::ksnp_zc_next_cookie, ksock_peer::ksnp_zc_req_list, LASSERT, LIBCFS_CPT_ALLOC, LIBCFS_FREE, lnet_cpt_of_nid(), lnet_cpt_table, LNET_NID_ANY, LNET_PID_ANY, lnet_ni::ni_data, and SOCKNAL_KEEPALIVE_PING.
Referenced by ksocknal_add_peer(), and ksocknal_create_conn().
static ksock_route_t* ksocknal_create_route (__u32 ipaddr, int port) [static]
Definition at line 68 of file socklnd.c.
References ksock_route::ksnr_conn_count, ksock_route::ksnr_connected, ksock_route::ksnr_connecting, ksock_route::ksnr_deleted, ksock_route::ksnr_ipaddr, ksock_route::ksnr_peer, ksock_route::ksnr_port, ksock_route::ksnr_refcount, ksock_route::ksnr_retry_interval, ksock_route::ksnr_scheduled, ksock_route::ksnr_share_count, and LIBCFS_ALLOC.
Referenced by ksocknal_add_peer(), and ksocknal_create_routes().
static void ksocknal_create_routes (ksock_peer_t * peer, int port, __u32 * peer_ipaddrs, int npeer_ipaddrs) [static]
Definition at line 855 of file socklnd.c.
References ksock_nal_data_t::ksnd_global_lock, ksock_interface_t::ksni_ipaddr, ksock_interface_t::ksni_netmask, ksock_interface_t::ksni_nroutes, ksock_net_t::ksnn_interfaces, ksock_net_t::ksnn_ninterfaces, ksock_peer::ksnp_closing, ksock_peer::ksnp_ni, ksock_peer::ksnp_routes, ksock_route::ksnr_ipaddr, ksock_route::ksnr_myipaddr, ksocknal_add_route_locked(), ksocknal_create_route(), ksocknal_route_decref(), LASSERT, list_entry, list_for_each, LNET_MAX_INTERFACES, and lnet_ni::ni_data.
Referenced by ksocknal_create_conn().
int ksocknal_ctl (lnet_ni_t * ni, unsigned int cmd, void * arg)
Definition at line 2094 of file socklnd.c.
References CERROR, libcfs_ioctl_data::ioc_count, libcfs_ioctl_data::ioc_flags, IOC_LIBCFS_ADD_INTERFACE, IOC_LIBCFS_ADD_PEER, IOC_LIBCFS_CLOSE_CONNECTION, IOC_LIBCFS_DEL_INTERFACE, IOC_LIBCFS_DEL_PEER, IOC_LIBCFS_GET_CONN, IOC_LIBCFS_GET_INTERFACE, IOC_LIBCFS_GET_PEER, IOC_LIBCFS_PUSH_CONNECTION, IOC_LIBCFS_REGISTER_MYNID, libcfs_ioctl_data::ioc_nid, libcfs_ioctl_data::ioc_u32, ksock_sched_info::ksi_cpt, ksock_conn::ksnc_ipaddr, ksock_conn::ksnc_myipaddr, ksock_conn::ksnc_peer, ksock_conn::ksnc_port, ksock_conn::ksnc_scheduler, ksock_conn::ksnc_type, ksock_nal_data_t::ksnd_global_lock, ksock_interface_t::ksni_ipaddr, ksock_interface_t::ksni_netmask, ksock_interface_t::ksni_npeers, ksock_interface_t::ksni_nroutes, ksock_net_t::ksnn_interfaces, ksock_net_t::ksnn_ninterfaces, ksock_peer::ksnp_id, ksocknal_add_interface(), ksocknal_add_peer(), ksocknal_close_matching_conns(), ksocknal_conn_decref(), ksocknal_del_interface(), ksocknal_del_peer(), ksocknal_get_conn_by_idx(), ksocknal_get_peer_info(), ksocknal_lib_get_conn_tunables(), ksocknal_push(), ksock_sched_t::kss_info, libcfs_nid2str(), LNET_PID_ANY, LNET_PID_LUSTRE, nagle, lnet_ni::ni_data, lnet_ni::ni_nid, lnet_process_id_t::nid, and lnet_process_id_t::pid.
Referenced by ksocklnd_init().
static void ksocknal_debug_peerhash (lnet_ni_t * ni) [static]
Definition at line 2504 of file socklnd.c.
References CWARN, ksock_conn::ksnc_closing, ksock_conn::ksnc_conn_refcount, ksock_conn::ksnc_sock_refcount, ksock_conn::ksnc_type, ksock_nal_data_t::ksnd_global_lock, ksock_nal_data_t::ksnd_peer_hash_size, ksock_nal_data_t::ksnd_peers, ksock_peer::ksnp_accepting, ksock_peer::ksnp_closing, ksock_peer::ksnp_conns, ksock_peer::ksnp_error, ksock_peer::ksnp_id, ksock_peer::ksnp_ni, ksock_peer::ksnp_refcount, ksock_peer::ksnp_routes, ksock_peer::ksnp_sharecount, ksock_peer::ksnp_tx_queue, ksock_peer::ksnp_zc_next_cookie, ksock_peer::ksnp_zc_req_list, ksock_route::ksnr_connected, ksock_route::ksnr_connecting, ksock_route::ksnr_deleted, ksock_route::ksnr_refcount, ksock_route::ksnr_scheduled, libcfs_id2str(), list_empty(), list_entry, list_for_each, and LPU64.
Referenced by ksocknal_shutdown().
static int ksocknal_del_interface (lnet_ni_t * ni, __u32 ipaddress) [static]
Definition at line 2046 of file socklnd.c.
References ksock_nal_data_t::ksnd_global_lock, ksock_nal_data_t::ksnd_peer_hash_size, ksock_nal_data_t::ksnd_peers, ksock_interface_t::ksni_ipaddr, ksock_net_t::ksnn_interfaces, ksock_net_t::ksnn_ninterfaces, ksock_peer::ksnp_ni, ksocknal_peer_del_interface_locked(), list_entry, list_for_each_safe, and lnet_ni::ni_data.
Referenced by ksocknal_ctl().
static int ksocknal_del_peer (lnet_ni_t * ni, lnet_process_id_t id, __u32 ip) [static]
Definition at line 565 of file socklnd.c.
References ksock_nal_data_t::ksnd_global_lock, ksock_nal_data_t::ksnd_peer_hash_size, ksock_nal_data_t::ksnd_peers, ksock_peer::ksnp_closing, ksock_peer::ksnp_conns, ksock_peer::ksnp_id, ksock_peer::ksnp_ni, ksock_peer::ksnp_routes, ksock_peer::ksnp_tx_queue, ksocknal_del_peer_locked(), ksocknal_nid2peerlist(), ksocknal_peer_addref(), ksocknal_peer_decref(), ksocknal_txlist_done(), LASSERT, list_empty(), list_entry, list_for_each_safe, LIST_HEAD_INIT, list_splice_init(), LNET_NID_ANY, LNET_PID_ANY, lnet_process_id_t::nid, and lnet_process_id_t::pid.
Referenced by ksocknal_ctl(), and ksocknal_shutdown().
static void ksocknal_del_peer_locked (ksock_peer_t * peer, __u32 ip) [static]
Definition at line 510 of file socklnd.c.
References ksock_peer::ksnp_closing, ksock_peer::ksnp_conns, ksock_peer::ksnp_routes, ksock_route::ksnr_ipaddr, ksock_route::ksnr_share_count, ksocknal_close_conn_locked(), ksocknal_del_route_locked(), ksocknal_peer_addref(), ksocknal_peer_decref(), LASSERT, list_entry, and list_for_each_safe.
Referenced by ksocknal_del_peer().
static void ksocknal_del_route_locked (ksock_route_t * route) [static]
Definition at line 408 of file socklnd.c.
References ksock_conn::ksnc_route, ksock_interface_t::ksni_nroutes, ksock_peer::ksnp_conns, ksock_peer::ksnp_ni, ksock_peer::ksnp_routes, ksock_route::ksnr_deleted, ksock_route::ksnr_list, ksock_route::ksnr_myipaddr, ksock_route::ksnr_peer, ksocknal_close_conn_locked(), ksocknal_ip2iface(), ksocknal_route_decref(), ksocknal_unlink_peer_locked(), LASSERT, list_del(), list_empty(), list_entry, and list_for_each_safe.
Referenced by ksocknal_del_peer_locked(), and ksocknal_peer_del_interface_locked().
void ksocknal_destroy_conn (ksock_conn_t * conn)
Definition at line 1630 of file socklnd.c.
References CDEBUG, CERROR, cfs_duration_sec(), cfs_time_current(), cfs_time_seconds(), cfs_time_sub(), D_NET, ksock_conn::ksnc_conn_refcount, ksock_conn::ksnc_cookie, ksock_conn::ksnc_ipaddr, ksock_conn::ksnc_peer, ksock_conn::ksnc_port, ksock_conn::ksnc_proto, ksock_conn::ksnc_route, ksock_conn::ksnc_rx_deadline, ksock_conn::ksnc_rx_nob_left, ksock_conn::ksnc_rx_nob_wanted, ksock_conn::ksnc_rx_scheduled, ksock_conn::ksnc_rx_started, ksock_conn::ksnc_rx_state, ksock_conn::ksnc_sock, ksock_conn::ksnc_sock_refcount, ksock_conn::ksnc_tx_queue, ksock_conn::ksnc_tx_scheduled, ksock_conn::ksnc_type, ksock_tunables_t::ksnd_timeout, ksock_peer::ksnp_id, ksock_peer::ksnp_ni, ksocknal_peer_decref(), ksocknal_tunables, LASSERT, LBUG, LIBCFS_FREE, libcfs_id2str(), list_empty(), lnet_finalize(), ksock_proto::pro_version, SOCKNAL_RX_KSM_HEADER, SOCKNAL_RX_LNET_HEADER, SOCKNAL_RX_LNET_PAYLOAD, and SOCKNAL_RX_SLOP.
Referenced by ksocknal_reaper().
void ksocknal_destroy_peer (ksock_peer_t * peer)
Definition at line 151 of file socklnd.c.
References CDEBUG, D_NET, ksock_net_t::ksnn_lock, ksock_net_t::ksnn_npeers, ksock_peer::ksnp_accepting, ksock_peer::ksnp_conns, ksock_peer::ksnp_id, ksock_peer::ksnp_ni, ksock_peer::ksnp_refcount, ksock_peer::ksnp_routes, ksock_peer::ksnp_tx_queue, ksock_peer::ksnp_zc_req_list, LASSERT, LIBCFS_FREE, libcfs_id2str(), list_empty(), and lnet_ni::ni_data.
Referenced by ksocknal_peer_decref().
void ksocknal_destroy_route (ksock_route_t * route)
Definition at line 92 of file socklnd.c.
References ksock_route::ksnr_peer, ksock_route::ksnr_refcount, ksocknal_peer_decref(), LASSERT, and LIBCFS_FREE.
Referenced by ksocknal_route_decref().
static int ksocknal_enumerate_interfaces (ksock_net_t * net) [static]
Definition at line 2610 of file socklnd.c.
References CERROR, CWARN, ksock_interface_t::ksni_ipaddr, ksock_interface_t::ksni_name, ksock_interface_t::ksni_netmask, ksock_net_t::ksnn_interfaces, lnet_ipif_enumerate(), lnet_ipif_free_enumeration(), lnet_ipif_query(), LNET_MAX_INTERFACES, and strlcpy().
Referenced by ksocknal_startup().
void ksocknal_finalize_zcreq (ksock_conn_t * conn)
Definition at line 1519 of file socklnd.c.
References ksock_conn::ksnc_peer, ksock_conn::ksnc_sock, ksock_peer::ksnp_lock, ksock_peer::ksnp_zc_req_list, ksocknal_tx_decref(), LASSERT, list_add(), list_del(), list_empty(), list_entry, list_for_each_entry_safe, LIST_HEAD_INIT, list_head::next, ksock_tx_t::tx_conn, ksock_tx_t::tx_msg, ksock_tx_t::tx_zc_aborted, and ksock_tx_t::tx_zc_list.
Referenced by ksocknal_connsock_decref().
ksock_peer_t* ksocknal_find_peer (lnet_ni_t * ni, lnet_process_id_t id)
Definition at line 205 of file socklnd.c.
References ksock_nal_data_t::ksnd_global_lock, ksocknal_find_peer_locked(), and ksocknal_peer_addref().
ksock_peer_t* ksocknal_find_peer_locked (lnet_ni_t * ni, lnet_process_id_t id)
Definition at line 177 of file socklnd.c.
References CDEBUG, D_NET, ksock_peer::ksnp_closing, ksock_peer::ksnp_id, ksock_peer::ksnp_ni, ksock_peer::ksnp_refcount, ksocknal_nid2peerlist(), LASSERT, libcfs_id2str(), list_entry, list_for_each, lnet_process_id_t::nid, and lnet_process_id_t::pid.
Referenced by ksocknal_add_peer(), ksocknal_create_conn(), ksocknal_find_peer(), ksocknal_launch_packet(), and ksocknal_query().
static void ksocknal_free_buffers (void) [static]
Definition at line 2221 of file socklnd.c.
References cfs_percpt_for_each, cfs_percpt_free(), ksock_sched_info::ksi_nthreads_max, ksock_sched_info::ksi_scheds, ksock_nal_data_t::ksnd_idle_noop_txs, ksock_nal_data_t::ksnd_nactive_txs, ksock_nal_data_t::ksnd_peer_hash_size, ksock_nal_data_t::ksnd_peers, ksock_nal_data_t::ksnd_sched_info, ksock_nal_data_t::ksnd_tx_lock, LASSERT, LIBCFS_FREE, list_add(), list_del(), list_del_init(), list_empty(), list_entry, and list_head::next.
Referenced by ksocknal_base_shutdown().
static ksock_conn_t* ksocknal_get_conn_by_idx (lnet_ni_t * ni, int index) [static]
Definition at line 628 of file socklnd.c.
References ksock_nal_data_t::ksnd_global_lock, ksock_nal_data_t::ksnd_peer_hash_size, ksock_nal_data_t::ksnd_peers, ksock_peer::ksnp_closing, ksock_peer::ksnp_conns, ksock_peer::ksnp_ni, ksocknal_conn_addref(), LASSERT, list_entry, and list_for_each.
Referenced by ksocknal_ctl().
static int ksocknal_get_peer_info (lnet_ni_t * ni, int index, lnet_process_id_t * id, __u32 * myip, __u32 * peer_ip, int * port, int * conn_count, int * share_count) [static]
Definition at line 249 of file socklnd.c.
References ksock_nal_data_t::ksnd_global_lock, ksock_nal_data_t::ksnd_peer_hash_size, ksock_nal_data_t::ksnd_peers, ksock_peer::ksnp_id, ksock_peer::ksnp_n_passive_ips, ksock_peer::ksnp_ni, ksock_peer::ksnp_passive_ips, ksock_peer::ksnp_routes, ksock_route::ksnr_conn_count, ksock_route::ksnr_ipaddr, ksock_route::ksnr_myipaddr, ksock_route::ksnr_port, ksock_route::ksnr_share_count, list_empty(), list_entry, and list_for_each.
Referenced by ksocknal_ctl().
static ksock_interface_t* ksocknal_ip2iface (lnet_ni_t * ni, __u32 ip) [static]
Definition at line 50 of file socklnd.c.
References ksock_interface_t::ksni_ipaddr, ksock_net_t::ksnn_interfaces, ksock_net_t::ksnn_ninterfaces, LASSERT, LNET_MAX_INTERFACES, and lnet_ni::ni_data.
Referenced by ksocknal_add_interface(), ksocknal_associate_route_conn_locked(), ksocknal_del_route_locked(), ksocknal_select_ips(), and ksocknal_unlink_peer_locked().
static int ksocknal_local_ipvec (lnet_ni_t * ni, __u32 * ipaddrs) [static]
Definition at line 689 of file socklnd.c.
References ksock_nal_data_t::ksnd_global_lock, ksock_interface_t::ksni_ipaddr, ksock_net_t::ksnn_interfaces, ksock_net_t::ksnn_ninterfaces, LASSERT, LNET_MAX_INTERFACES, and lnet_ni::ni_data.
Referenced by ksocknal_create_conn().
static int ksocknal_match_peerip (ksock_interface_t * iface, __u32 * ips, int nips) [static]
Definition at line 717 of file socklnd.c.
References ksock_interface_t::ksni_ipaddr, ksock_interface_t::ksni_netmask, and LASSERT.
Referenced by ksocknal_select_ips().
static int ksocknal_net_start_threads (ksock_net_t * net, __u32 * cpts, int ncpts) [static]
Definition at line 2755 of file socklnd.c.
References cfs_cpt_number(), ksock_sched_info::ksi_nthreads, ksock_nal_data_t::ksnd_sched_info, ksocknal_search_new_ipif(), ksocknal_start_schedulers(), LASSERT, and lnet_cpt_table.
Referenced by ksocknal_startup().
static __u64 ksocknal_new_incarnation (void) [static]
Definition at line 2357 of file socklnd.c.
References __u64.
Referenced by ksocknal_startup().
void ksocknal_notify (lnet_ni_t * ni, lnet_nid_t gw_nid, int alive)
Definition at line 1774 of file socklnd.c.
References CDEBUG, D_NET, ksocknal_close_matching_conns(), libcfs_nid2str(), and LNET_PID_ANY.
Referenced by ksocklnd_init().
static void ksocknal_peer_del_interface_locked (ksock_peer_t * peer, __u32 ipaddr) [static]
Definition at line 2005 of file socklnd.c.
References ksock_conn::ksnc_myipaddr, ksock_peer::ksnp_conns, ksock_peer::ksnp_n_passive_ips, ksock_peer::ksnp_passive_ips, ksock_peer::ksnp_routes, ksock_route::ksnr_myipaddr, ksock_route::ksnr_share_count, ksocknal_close_conn_locked(), ksocknal_del_route_locked(), list_entry, and list_for_each_safe.
Referenced by ksocknal_del_interface().
void ksocknal_peer_failed (ksock_peer_t * peer)
Definition at line 1492 of file socklnd.c.
References ksock_nal_data_t::ksnd_global_lock, ksock_peer::ksnp_accepting, ksock_peer::ksnp_conns, ksock_peer::ksnp_id, ksock_peer::ksnp_last_alive, ksock_peer::ksnp_ni, ksocknal_find_connecting_route_locked(), list_empty(), lnet_notify(), LNET_PID_USERFLAG, lnet_process_id_t::nid, and lnet_process_id_t::pid.
Referenced by ksocknal_connect(), and ksocknal_terminate_conn().
static int ksocknal_push (lnet_ni_t * ni, lnet_process_id_t id) [static]
Definition at line 1894 of file socklnd.c.
References end, ksock_nal_data_t::ksnd_global_lock, ksock_nal_data_t::ksnd_peer_hash_size, ksock_nal_data_t::ksnd_peers, ksock_peer::ksnp_id, ksocknal_nid2peerlist(), ksocknal_peer_addref(), ksocknal_peer_decref(), ksocknal_push_peer(), list_for_each_entry, LNET_NID_ANY, LNET_PID_ANY, lnet_process_id_t::nid, lnet_process_id_t::pid, and start.
Referenced by ksocknal_ctl().
static void ksocknal_push_peer (ksock_peer_t * peer) [static]
Definition at line 1861 of file socklnd.c.
References ksock_nal_data_t::ksnd_global_lock, ksock_peer::ksnp_conns, ksocknal_conn_addref(), ksocknal_conn_decref(), ksocknal_lib_push_conn(), list_entry, and list_for_each.
Referenced by ksocknal_push().
void ksocknal_query (lnet_ni_t * ni, lnet_nid_t nid, cfs_time_t * when)
Definition at line 1797 of file socklnd.c.
References CDEBUG, cfs_duration_sec(), cfs_time_current(), cfs_time_shift(), D_NET, ksock_conn::ksnc_sock, ksock_conn::ksnc_tx_bufnob, ksock_conn::ksnc_tx_deadline, ksock_nal_data_t::ksnd_global_lock, ksock_tunables_t::ksnd_timeout, ksock_peer::ksnp_conns, ksock_peer::ksnp_last_alive, ksocknal_add_peer(), ksocknal_find_connectable_route_locked(), ksocknal_find_peer_locked(), ksocknal_launch_all_connections_locked(), ksocknal_tunables, libcfs_nid2str(), list_entry, list_for_each, lnet_acceptor_port(), LNET_NIDADDR(), LNET_PID_LUSTRE, and now().
Referenced by ksocklnd_init().
void ksocknal_queue_zombie_conn (ksock_conn_t * conn)
Definition at line 1616 of file socklnd.c.
References ksock_conn::ksnc_conn_refcount, ksock_conn::ksnc_list, ksock_nal_data_t::ksnd_reaper_lock, ksock_nal_data_t::ksnd_reaper_waitq, ksock_nal_data_t::ksnd_zombie_conns, LASSERT, and list_add_tail().
Referenced by ksocknal_conn_decref().
static int ksocknal_search_new_ipif (ksock_net_t * net) [static]
Definition at line 2667 of file socklnd.c.
References ksock_nal_data_t::ksnd_nets, ksock_interface_t::ksni_name, ksock_net_t::ksnn_interfaces, ksock_net_t::ksnn_ninterfaces, and list_for_each_entry.
Referenced by ksocknal_net_start_threads().
static int ksocknal_select_ips (ksock_peer_t * peer, __u32 * peerips, int n_peerips) [static]
Definition at line 749 of file socklnd.c.
References ksock_nal_data_t::ksnd_global_lock, ksock_interface_t::ksni_ipaddr, ksock_interface_t::ksni_netmask, ksock_interface_t::ksni_npeers, ksock_net_t::ksnn_interfaces, ksock_net_t::ksnn_ninterfaces, ksock_peer::ksnp_n_passive_ips, ksock_peer::ksnp_ni, ksock_peer::ksnp_passive_ips, ksocknal_ip2iface(), ksocknal_match_peerip(), LASSERT, LNET_MAX_INTERFACES, MIN, and lnet_ni::ni_data.
Referenced by ksocknal_create_conn().
void ksocknal_shutdown (lnet_ni_t * ni)
Definition at line 2558 of file socklnd.c.
References CDEBUG, cfs_time_seconds(), D_NET, D_WARNING, ksock_nal_data_t::ksnd_init, ksock_nal_data_t::ksnd_nnets, ksock_interface_t::ksni_npeers, ksock_interface_t::ksni_nroutes, ksock_net_t::ksnn_interfaces, ksock_net_t::ksnn_list, ksock_net_t::ksnn_lock, ksock_net_t::ksnn_ninterfaces, ksock_net_t::ksnn_npeers, ksock_net_t::ksnn_shutdown, ksocknal_base_shutdown(), ksocknal_debug_peerhash(), ksocknal_del_peer(), LASSERT, LIBCFS_FREE, list_del(), LNET_NID_ANY, LNET_PID_ANY, lnet_ni::ni_data, lnet_process_id_t::nid, lnet_process_id_t::pid, and SOCKNAL_INIT_ALL.
Referenced by ksocklnd_init().
static int ksocknal_start_schedulers (struct ksock_sched_info * info) [static]
Definition at line 2709 of file socklnd.c.
References CERROR, cfs_cpt_weight(), ksock_sched_info::ksi_cpt, ksock_sched_info::ksi_nthreads, ksock_sched_info::ksi_nthreads_max, ksock_sched_info::ksi_scheds, ksock_tunables_t::ksnd_nscheds, KSOCK_THREAD_ID, KSOCK_THREAD_SID, ksocknal_scheduler(), ksocknal_thread_start(), ksocknal_tunables, LASSERT, lnet_cpt_table, max, name, SOCKNAL_NSCHEDS, and SOCKNAL_NSCHEDS_HIGH.
Referenced by ksocknal_net_start_threads().
int ksocknal_startup (lnet_ni_t * ni)
Definition at line 2781 of file socklnd.c.
References CERROR, ksock_tunables_t::ksnd_credits, ksock_nal_data_t::ksnd_init, ksock_nal_data_t::ksnd_nets, ksock_nal_data_t::ksnd_nnets, ksock_tunables_t::ksnd_peerrtrcredits, ksock_tunables_t::ksnd_peertimeout, ksock_tunables_t::ksnd_peertxcredits, ksock_interface_t::ksni_ipaddr, ksock_interface_t::ksni_name, ksock_interface_t::ksni_netmask, ksock_net_t::ksnn_incarnation, ksock_net_t::ksnn_interfaces, ksock_net_t::ksnn_list, ksock_net_t::ksnn_lock, ksock_net_t::ksnn_ninterfaces, ksocknal_base_shutdown(), ksocknal_base_startup(), ksocknal_enumerate_interfaces(), ksocknal_net_start_threads(), ksocknal_new_incarnation(), ksocknal_tunables, LASSERT, LIBCFS_ALLOC, LIBCFS_FREE, list_add(), lnet_ipif_query(), LNET_MAX_INTERFACES, LNET_MKNID(), LNET_NIDNET(), lnet_ni::ni_cpts, lnet_ni::ni_data, lnet_ni::ni_interfaces, lnet_ni::ni_lnd, lnet_ni::ni_maxtxcredits, lnet_ni::ni_ncpts, lnet_ni::ni_nid, lnet_ni::ni_peerrtrcredits, lnet_ni::ni_peertimeout, lnet_ni::ni_peertxcredits, SOCKNAL_INIT_NOTHING, and strlcpy().
Referenced by ksocklnd_init().
void ksocknal_terminate_conn (ksock_conn_t * conn)
Definition at line 1555 of file socklnd.c.
References ksock_conn::ksnc_closing, ksock_conn::ksnc_peer, ksock_conn::ksnc_scheduler, ksock_conn::ksnc_sock, ksock_conn::ksnc_tx_list, ksock_conn::ksnc_tx_queue, ksock_conn::ksnc_tx_ready, ksock_conn::ksnc_tx_scheduled, ksock_nal_data_t::ksnd_global_lock, ksock_peer::ksnp_conns, ksock_peer::ksnp_error, ksocknal_conn_addref(), ksocknal_connsock_decref(), ksocknal_lib_reset_callback(), ksocknal_peer_failed(), ksock_sched_t::kss_lock, ksock_sched_t::kss_nconns, ksock_sched_t::kss_tx_conns, ksock_sched_t::kss_waitq, LASSERT, list_add_tail(), and list_empty().
Referenced by ksocknal_reaper().
static void ksocknal_unlink_peer_locked (ksock_peer_t * peer) [static]
Definition at line 219 of file socklnd.c.
References CDEBUG, D_NET, ksock_interface_t::ksni_npeers, ksock_interface_t::ksni_nroutes, ksock_peer::ksnp_closing, ksock_peer::ksnp_conns, ksock_peer::ksnp_list, ksock_peer::ksnp_n_passive_ips, ksock_peer::ksnp_ni, ksock_peer::ksnp_passive_ips, ksock_peer::ksnp_routes, ksocknal_ip2iface(), ksocknal_peer_decref(), LASSERT, list_del(), list_empty(), and LNET_MAX_INTERFACES.
Referenced by ksocknal_close_conn_locked(), ksocknal_create_conn(), and ksocknal_del_route_locked().
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("TCP Socket LNet Network Driver")
module_exit (ksocklnd_exit)
module_init (ksocklnd_init)
MODULE_LICENSE ("GPL")
MODULE_VERSION ("2.8.0")
Variable Documentation
ksock_nal_data_t ksocknal_data
Definition at line 47 of file socklnd.c.
Referenced by ksocknal_alloc_tx(), ksocknal_check_peer_timeouts(), ksocknal_connd(), ksocknal_connd_check_start(), ksocknal_connd_check_stop(), ksocknal_connd_get_route_locked(), ksocknal_connect(), ksocknal_data_ready(), ksocknal_flush_stale_txs(), ksocknal_free_tx(), ksocknal_handle_zcreq(), ksocknal_launch_connection_locked(), ksocknal_launch_packet(), ksocknal_process_transmit(), ksocknal_reaper(), ksocknal_receive(), ksocknal_sched_cansleep(), ksocknal_scheduler(), ksocknal_send_keepalive_locked(), ksocknal_thread_fini(), ksocknal_thread_start(), ksocknal_transmit(), and ksocknal_write_space().
lnd_t the_ksocklnd [static]
Definition at line 46 of file socklnd.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.