Lustre: lnet/klnds/socklnd/socklnd_cb.c File Reference
lnet/klnds/socklnd/socklnd_cb.c File Reference
#include "socklnd.h"
Functions
ksock_tx_t * ksocknal_alloc_tx (int type, int size)
ksock_tx_t * ksocknal_alloc_tx_noop (__u64 cookie, int nonblk)
void ksocknal_free_tx (ksock_tx_t *tx)
static int ksocknal_send_iov (ksock_conn_t *conn, ksock_tx_t *tx)
static int ksocknal_send_kiov (ksock_conn_t *conn, ksock_tx_t *tx)
static int ksocknal_transmit (ksock_conn_t *conn, ksock_tx_t *tx)
static int ksocknal_recv_iov (ksock_conn_t *conn)
static int ksocknal_recv_kiov (ksock_conn_t *conn)
static int ksocknal_receive (ksock_conn_t *conn)
void ksocknal_tx_done (lnet_ni_t *ni, ksock_tx_t *tx)
void ksocknal_txlist_done (lnet_ni_t *ni, struct list_head *txlist, int error)
static void ksocknal_check_zc_req (ksock_tx_t *tx)
static void ksocknal_uncheck_zc_req (ksock_tx_t *tx)
static int ksocknal_process_transmit (ksock_conn_t *conn, ksock_tx_t *tx)
static void ksocknal_launch_connection_locked (ksock_route_t *route)
void ksocknal_launch_all_connections_locked (ksock_peer_t *peer)
ksock_conn_t * ksocknal_find_conn_locked (ksock_peer_t *peer, ksock_tx_t *tx, int nonblk)
void ksocknal_tx_prep (ksock_conn_t *conn, ksock_tx_t *tx)
void ksocknal_queue_tx_locked (ksock_tx_t *tx, ksock_conn_t *conn)
ksock_route_t * ksocknal_find_connectable_route_locked (ksock_peer_t *peer)
ksock_route_t * ksocknal_find_connecting_route_locked (ksock_peer_t *peer)
int ksocknal_launch_packet (lnet_ni_t *ni, ksock_tx_t *tx, lnet_process_id_t id)
int ksocknal_send (lnet_ni_t *ni, void *private, lnet_msg_t *lntmsg)
int ksocknal_thread_start (int(*fn)(void *arg), void *arg, char *name)
void ksocknal_thread_fini (void)
int ksocknal_new_packet (ksock_conn_t *conn, int nob_to_skip)
static int ksocknal_process_receive (ksock_conn_t *conn)
int ksocknal_recv (lnet_ni_t *ni, void *private, lnet_msg_t *msg, int delayed, unsigned int niov, struct kvec *iov, lnet_kiov_t *kiov, unsigned int offset, unsigned int mlen, unsigned int rlen)
static int ksocknal_sched_cansleep (ksock_sched_t *sched)
int ksocknal_scheduler (void *arg)
void ksocknal_read_callback (ksock_conn_t *conn)
void ksocknal_write_callback (ksock_conn_t *conn)
static ksock_proto_t * ksocknal_parse_proto_version (ksock_hello_msg_t *hello)
int ksocknal_send_hello (lnet_ni_t *ni, ksock_conn_t *conn, lnet_nid_t peer_nid, ksock_hello_msg_t *hello)
static int ksocknal_invert_type (int type)
int ksocknal_recv_hello (lnet_ni_t *ni, ksock_conn_t *conn, ksock_hello_msg_t *hello, lnet_process_id_t *peerid, __u64 *incarnation)
static int ksocknal_connect (ksock_route_t *route)
static int ksocknal_connd_check_start (long sec, long *timeout)
static int ksocknal_connd_check_stop (long sec, long *timeout)
static ksock_route_t * ksocknal_connd_get_route_locked (signed long *timeout_p)
int ksocknal_connd (void *arg)
static ksock_conn_t * ksocknal_find_timed_out_conn (ksock_peer_t *peer)
static void ksocknal_flush_stale_txs (ksock_peer_t *peer)
static int ksocknal_send_keepalive_locked (ksock_peer_t *peer) __must_hold(&ksocknal_data.ksnd_global_lock)
static void ksocknal_check_peer_timeouts (int idx)
int ksocknal_reaper (void *arg)
Function Documentation
ksock_tx_t* ksocknal_alloc_tx (int type, int size)
Definition at line 30 of file socklnd_cb.c.
References ksock_nal_data_t::ksnd_idle_noop_txs, ksock_nal_data_t::ksnd_nactive_txs, ksock_nal_data_t::ksnd_tx_lock, KSOCK_MSG_NOOP, KSOCK_NOOP_TX_SIZE, ksocknal_data, LASSERT, LIBCFS_ALLOC, list_del(), list_empty(), list_entry, ksock_tx_t::tx_desc_size, ksock_tx_t::tx_list, ksock_tx_t::tx_refcount, ksock_tx_t::tx_zc_aborted, ksock_tx_t::tx_zc_capable, and ksock_tx_t::tx_zc_checked.
Referenced by ksocknal_alloc_tx_noop(), and ksocknal_send().
ksock_tx_t* ksocknal_alloc_tx_noop (__u64 cookie, int nonblk)
Definition at line 68 of file socklnd_cb.c.
References CERROR, KSOCK_MSG_NOOP, KSOCK_NOOP_TX_SIZE, ksocknal_alloc_tx(), socklnd_init_msg(), ksock_tx_t::tx_conn, ksock_tx_t::tx_frags, ksock_tx_t::tx_iov, ksock_tx_t::tx_kiov, ksock_tx_t::tx_lnetmsg, ksock_tx_t::tx_msg, ksock_tx_t::tx_niov, ksock_tx_t::tx_nkiov, ksock_tx_t::tx_nonblk, and ksock_tx_t::virt.
Referenced by ksocknal_handle_zcreq(), and ksocknal_send_keepalive_locked().
static void ksocknal_check_peer_timeouts (int idx) [static]
Definition at line 2418 of file socklnd_cb.c.
References CERROR, cfs_duration_sec(), cfs_time_aftereq(), cfs_time_current(), ksock_conn::ksnc_closing, ksock_conn::ksnc_sock, ksock_nal_data_t::ksnd_global_lock, ksock_nal_data_t::ksnd_peers, ksock_peer::ksnp_id, ksock_peer::ksnp_lock, ksock_peer::ksnp_tx_queue, ksock_peer::ksnp_zc_req_list, ksocknal_close_conn_and_siblings(), ksocknal_conn_addref(), ksocknal_conn_decref(), ksocknal_data, ksocknal_find_timed_out_conn(), ksocknal_flush_stale_txs(), ksocknal_peer_addref(), ksocknal_peer_decref(), ksocknal_send_keepalive_locked(), libcfs_nid2str(), list_empty(), list_entry, list_for_each_entry, list_head::next, lnet_process_id_t::nid, ksock_tx_t::tx_conn, ksock_tx_t::tx_deadline, and ksock_tx_t::tx_resid.
Referenced by ksocknal_reaper().
static void ksocknal_check_zc_req (ksock_tx_t * tx) [static]
Definition at line 437 of file socklnd_cb.c.
References cfs_time_shift(), ksock_conn::ksnc_peer, ksock_conn::ksnc_proto, ksock_conn::ksnc_zc_capable, ksock_tunables_t::ksnd_timeout, ksock_peer::ksnp_lock, ksock_peer::ksnp_zc_next_cookie, ksock_peer::ksnp_zc_req_list, KSOCK_MSG_NOOP, ksocknal_protocol_v1x, ksocknal_tunables, ksocknal_tx_addref(), LASSERT, list_add_tail(), SOCKNAL_KEEPALIVE_PING, ksock_tx_t::tx_conn, ksock_tx_t::tx_deadline, ksock_tx_t::tx_msg, ksock_tx_t::tx_zc_capable, ksock_tx_t::tx_zc_checked, and ksock_tx_t::tx_zc_list.
Referenced by ksocknal_process_transmit().
int ksocknal_connd (void * arg)
Definition at line 2134 of file socklnd_cb.c.
References cfs_block_allsigs(), cfs_time_current_sec(), CWARN, ksock_connreq::ksncr_list, ksock_connreq::ksncr_ni, ksock_connreq::ksncr_sock, ksock_nal_data_t::ksnd_connd_connecting, ksock_nal_data_t::ksnd_connd_connreqs, ksock_nal_data_t::ksnd_connd_lock, ksock_nal_data_t::ksnd_connd_running, ksock_nal_data_t::ksnd_connd_starting, ksock_nal_data_t::ksnd_connd_waitq, ksock_nal_data_t::ksnd_shuttingdown, ksock_route::ksnr_connd_list, ksock_route::ksnr_ipaddr, ksocknal_connd_check_start(), ksocknal_connd_check_stop(), ksocknal_connd_get_route_locked(), ksocknal_connect(), ksocknal_create_conn(), ksocknal_data, ksocknal_route_decref(), ksocknal_thread_fini(), LASSERT, LIBCFS_FREE, list_del(), list_empty(), list_entry, lnet_ni_decref(), SOCKLND_CONN_NONE, SOCKNAL_CONND_RESV, SOCKNAL_INSANITY_RECONN, SOCKNAL_RESCHED, and timeout.
Referenced by ksocknal_base_startup(), and ksocknal_connd_check_start().
static int ksocknal_connd_check_start (long sec, long * timeout) [static]
Definition at line 2011 of file socklnd_cb.c.
References cfs_time_current_sec(), cfs_time_seconds(), ksock_nal_data_t::ksnd_connd_connecting, ksock_nal_data_t::ksnd_connd_failed_stamp, ksock_nal_data_t::ksnd_connd_lock, ksock_nal_data_t::ksnd_connd_routes, ksock_nal_data_t::ksnd_connd_running, ksock_nal_data_t::ksnd_connd_starting, ksock_nal_data_t::ksnd_connd_starting_stamp, ksock_nal_data_t::ksnd_init, ksock_tunables_t::ksnd_nconnds_max, ksocknal_connd(), ksocknal_data, ksocknal_thread_start(), ksocknal_tunables, LASSERT, list_empty(), name, SOCKNAL_CONND_RESV, SOCKNAL_INIT_ALL, and unlikely.
Referenced by ksocknal_connd().
static int ksocknal_connd_check_stop (long sec, long * timeout) [static]
Definition at line 2073 of file socklnd_cb.c.
References cfs_time_seconds(), ksock_nal_data_t::ksnd_connd_connecting, ksock_nal_data_t::ksnd_connd_running, ksock_nal_data_t::ksnd_connd_starting, ksock_nal_data_t::ksnd_connd_starting_stamp, ksock_nal_data_t::ksnd_init, ksock_tunables_t::ksnd_nconnds, ksocknal_data, ksocknal_tunables, SOCKNAL_CONND_RESV, SOCKNAL_CONND_TIMEOUT, SOCKNAL_INIT_ALL, and unlikely.
Referenced by ksocknal_connd().
static ksock_route_t* ksocknal_connd_get_route_locked (signed long * timeout_p) [static]
Definition at line 2110 of file socklnd_cb.c.
References cfs_time_aftereq(), cfs_time_current(), ksock_nal_data_t::ksnd_connd_routes, ksock_route::ksnr_retry_interval, ksock_route::ksnr_timeout, ksocknal_data, list_for_each_entry, and now().
Referenced by ksocknal_connd().
static int ksocknal_connect (ksock_route_t * route) [static]
Definition at line 1840 of file socklnd_cb.c.
References CDEBUG, cfs_time_add(), cfs_time_aftereq(), cfs_time_current(), cfs_time_seconds(), D_NET, ksock_conn::ksnc_proto, ksock_nal_data_t::ksnd_global_lock, ksock_tunables_t::ksnd_max_reconnectms, ksock_tunables_t::ksnd_min_reconnectms, ksock_tunables_t::ksnd_timeout, ksock_peer::ksnp_accepting, ksock_peer::ksnp_closing, ksock_peer::ksnp_conns, ksock_peer::ksnp_id, ksock_peer::ksnp_ni, ksock_peer::ksnp_routes, ksock_peer::ksnp_tx_queue, ksock_route::ksnr_connected, ksock_route::ksnr_connecting, ksock_route::ksnr_deleted, ksock_route::ksnr_ipaddr, ksock_route::ksnr_list, ksock_route::ksnr_myipaddr, ksock_route::ksnr_peer, ksock_route::ksnr_port, ksock_route::ksnr_retry_interval, ksock_route::ksnr_scheduled, ksock_route::ksnr_timeout, ksocknal_create_conn(), ksocknal_data, ksocknal_find_connecting_route_locked(), ksocknal_launch_connection_locked(), ksocknal_peer_failed(), ksocknal_protocol_v3x, ksocknal_route_mask(), ksocknal_tunables, ksocknal_txlist_done(), LASSERT, libcfs_nid2str(), list_add_tail(), list_del(), list_empty(), list_entry, LIST_HEAD_INIT, list_splice_init(), lnet_connect(), lnet_connect_console_error(), MAX, MIN, list_head::next, lnet_process_id_t::nid, SOCKLND_CONN_ANY, SOCKLND_CONN_BULK_IN, SOCKLND_CONN_BULK_OUT, and SOCKLND_CONN_CONTROL.
Referenced by ksocknal_connd().
ksock_conn_t* ksocknal_find_conn_locked (ksock_peer_t * peer, ksock_tx_t * tx, int nonblk)
Definition at line 623 of file socklnd_cb.c.
References cfs_time_after(), cfs_time_current(), ksock_conn::ksnc_closing, ksock_conn::ksnc_proto, ksock_conn::ksnc_sock, ksock_conn::ksnc_tx_last_post, ksock_conn::ksnc_tx_nob, ksock_tunables_t::ksnd_round_robin, ksock_peer::ksnp_conns, ksocknal_tunables, LASSERT, LBUG, list_entry, list_for_each, ksock_proto::pro_match_tx, SOCKNAL_MATCH_MAY, SOCKNAL_MATCH_NO, and SOCKNAL_MATCH_YES.
Referenced by ksocknal_handle_zcreq(), ksocknal_launch_packet(), and ksocknal_send_keepalive_locked().
ksock_route_t* ksocknal_find_connectable_route_locked (ksock_peer_t * peer)
Definition at line 778 of file socklnd_cb.c.
References CDEBUG, cfs_duration_sec(), cfs_time_aftereq(), cfs_time_current(), D_NET, ksock_peer::ksnp_routes, ksock_route::ksnr_connected, ksock_route::ksnr_connecting, ksock_route::ksnr_ipaddr, ksock_route::ksnr_retry_interval, ksock_route::ksnr_scheduled, ksock_route::ksnr_timeout, ksocknal_route_mask(), LASSERT, list_entry, list_for_each, and now().
Referenced by ksocknal_launch_all_connections_locked(), ksocknal_launch_packet(), and ksocknal_query().
ksock_route_t* ksocknal_find_connecting_route_locked (ksock_peer_t * peer)
Definition at line 815 of file socklnd_cb.c.
References ksock_peer::ksnp_routes, ksock_route::ksnr_connecting, ksock_route::ksnr_scheduled, LASSERT, list_entry, and list_for_each.
Referenced by ksocknal_connect(), ksocknal_launch_packet(), and ksocknal_peer_failed().
static ksock_conn_t* ksocknal_find_timed_out_conn (ksock_peer_t * peer) [static]
Definition at line 2247 of file socklnd_cb.c.
References cfs_time_aftereq(), cfs_time_current(), CNETERR, error, ksock_conn::ksnc_closing, ksock_conn::ksnc_ipaddr, ksock_conn::ksnc_port, ksock_conn::ksnc_rx_deadline, ksock_conn::ksnc_rx_nob_left, ksock_conn::ksnc_rx_nob_wanted, ksock_conn::ksnc_rx_started, ksock_conn::ksnc_rx_state, ksock_conn::ksnc_sock, ksock_conn::ksnc_tx_deadline, ksock_conn::ksnc_tx_queue, ksock_peer::ksnp_conns, ksock_peer::ksnp_id, ksocknal_conn_addref(), LASSERT, libcfs_id2str(), list_empty(), list_entry, and list_for_each.
Referenced by ksocknal_check_peer_timeouts().
static void ksocknal_flush_stale_txs (ksock_peer_t * peer) [inline, static]
Definition at line 2329 of file socklnd_cb.c.
References cfs_time_aftereq(), cfs_time_current(), ksock_nal_data_t::ksnd_global_lock, ksock_peer::ksnp_ni, ksock_peer::ksnp_tx_queue, ksocknal_data, ksocknal_txlist_done(), list_add_tail(), list_del(), list_empty(), list_entry, LIST_HEAD_INIT, list_head::next, ksock_tx_t::tx_deadline, and ksock_tx_t::tx_list.
Referenced by ksocknal_check_peer_timeouts().
void ksocknal_free_tx (ksock_tx_t * tx)
Definition at line 94 of file socklnd_cb.c.
References ksock_nal_data_t::ksnd_idle_noop_txs, ksock_nal_data_t::ksnd_nactive_txs, ksock_nal_data_t::ksnd_tx_lock, KSOCK_NOOP_TX_SIZE, ksocknal_data, LIBCFS_FREE, list_add(), ksock_tx_t::tx_desc_size, ksock_tx_t::tx_list, and ksock_tx_t::tx_lnetmsg.
Referenced by ksocknal_handle_zcreq(), ksocknal_send(), ksocknal_send_keepalive_locked(), and ksocknal_tx_done().
static int ksocknal_invert_type (int type) [static]
Definition at line 1679 of file socklnd_cb.c.
References SOCKLND_CONN_ANY, SOCKLND_CONN_BULK_IN, SOCKLND_CONN_BULK_OUT, SOCKLND_CONN_CONTROL, and SOCKLND_CONN_NONE.
Referenced by ksocknal_recv_hello().
void ksocknal_launch_all_connections_locked (ksock_peer_t * peer)
Definition at line 607 of file socklnd_cb.c.
References ksocknal_find_connectable_route_locked(), and ksocknal_launch_connection_locked().
Referenced by ksocknal_launch_packet(), and ksocknal_query().
static void ksocknal_launch_connection_locked (ksock_route_t * route) [static]
Definition at line 585 of file socklnd_cb.c.
References ksock_nal_data_t::ksnd_connd_lock, ksock_nal_data_t::ksnd_connd_routes, ksock_nal_data_t::ksnd_connd_waitq, ksock_route::ksnr_connd_list, ksock_route::ksnr_connected, ksock_route::ksnr_connecting, ksock_route::ksnr_scheduled, ksocknal_data, ksocknal_route_addref(), ksocknal_route_mask(), LASSERT, and list_add_tail().
Referenced by ksocknal_connect(), and ksocknal_launch_all_connections_locked().
int ksocknal_launch_packet (lnet_ni_t * ni, ksock_tx_t * tx, lnet_process_id_t id)
Definition at line 833 of file socklnd_cb.c.
References CERROR, cfs_time_shift(), CNETERR, ksock_nal_data_t::ksnd_global_lock, ksock_tunables_t::ksnd_timeout, ksock_peer::ksnp_accepting, ksock_peer::ksnp_tx_queue, ksocknal_add_peer(), ksocknal_data, ksocknal_find_conn_locked(), ksocknal_find_connectable_route_locked(), ksocknal_find_connecting_route_locked(), ksocknal_find_peer_locked(), ksocknal_launch_all_connections_locked(), ksocknal_queue_tx_locked(), ksocknal_tunables, LASSERT, libcfs_id2str(), list_add_tail(), lnet_acceptor_port(), LNET_NIDADDR(), LNET_PID_USERFLAG, ksock_tx_t::tx_conn, ksock_tx_t::tx_deadline, ksock_tx_t::tx_list, and ksock_tx_t::tx_nonblk.
Referenced by ksocknal_handle_zcreq(), ksocknal_send(), and ksocknal_send_keepalive_locked().
int ksocknal_new_packet (ksock_conn_t * conn, int nob_to_skip)
Definition at line 1028 of file socklnd_cb.c.
References ksock_conn::ksnc_msg, ksock_conn::ksnc_proto, ksock_conn::ksnc_rx_csum, ksock_conn::ksnc_rx_iov, ksock_conn::ksnc_rx_iov_space, ksock_conn::ksnc_rx_kiov, ksock_conn::ksnc_rx_niov, ksock_conn::ksnc_rx_nkiov, ksock_conn::ksnc_rx_nob_left, ksock_conn::ksnc_rx_nob_wanted, ksock_conn::ksnc_rx_started, ksock_conn::ksnc_rx_state, ksock_conn::ksnc_type, ksock_tunables_t::ksnd_eager_ack, KSOCK_PROTO_V1, KSOCK_PROTO_V2, KSOCK_PROTO_V3, ksocknal_lib_eager_ack(), ksocknal_tunables, LASSERT, LBUG, MIN, offsetof, ksock_proto::pro_version, SOCKNAL_RX_KSM_HEADER, SOCKNAL_RX_LNET_HEADER, and SOCKNAL_RX_SLOP.
Referenced by ksocknal_create_conn(), and ksocknal_process_receive().
static ksock_proto_t* ksocknal_parse_proto_version (ksock_hello_msg_t * hello) [static]
Definition at line 1615 of file socklnd_cb.c.
References __swab32, CLASSERT, cpu_to_le16, KSOCK_PROTO_V1_MAJOR, KSOCK_PROTO_V1_MINOR, KSOCK_PROTO_V2, KSOCK_PROTO_V3, ksocknal_protocol_v1x, ksocknal_protocol_v2x, ksocknal_protocol_v3x, ksocknal_tunables, le32_to_cpu, LNET_PROTO_MAGIC, LNET_PROTO_TCP_MAGIC, offsetof, and version.
Referenced by ksocknal_recv_hello().
static int ksocknal_process_receive (ksock_conn_t * conn) [static]
Definition at line 1110 of file socklnd_cb.c.
References __swab32s, __swab64s, __u64, CDEBUG, CERROR, cpu_to_le32, cpu_to_le64, D_NET, ksock_conn::ksnc_closing, ksock_conn::ksnc_conn_refcount, ksock_conn::ksnc_cookie, ksock_conn::ksnc_flip, ksock_conn::ksnc_ipaddr, ksock_conn::ksnc_msg, ksock_conn::ksnc_peer, ksock_conn::ksnc_port, ksock_conn::ksnc_proto, ksock_conn::ksnc_rx_csum, ksock_conn::ksnc_rx_iov, ksock_conn::ksnc_rx_iov_space, ksock_conn::ksnc_rx_kiov, ksock_conn::ksnc_rx_niov, ksock_conn::ksnc_rx_nkiov, ksock_conn::ksnc_rx_nob_left, ksock_conn::ksnc_rx_nob_wanted, ksock_conn::ksnc_rx_state, ksock_tunables_t::ksnd_nonblk_zcack, ksock_peer::ksnp_id, ksock_peer::ksnp_ni, KSOCK_MSG_LNET, KSOCK_MSG_NOOP, ksocknal_close_conn_and_siblings(), ksocknal_conn_addref(), ksocknal_conn_decref(), ksocknal_new_packet(), ksocknal_protocol_v1x, ksocknal_receive(), ksocknal_tunables, LASSERT, LBUG, le64_to_cpu, libcfs_id2str(), lnet_finalize(), lnet_parse(), LNET_PID_USERFLAG, LPU64, lnet_process_id_t::nid, lnet_process_id_t::pid, ksock_proto::pro_handle_zcack, ksock_proto::pro_handle_zcreq, ksock_proto::pro_unpack, SOCKNAL_RX_KSM_HEADER, SOCKNAL_RX_LNET_HEADER, SOCKNAL_RX_LNET_PAYLOAD, SOCKNAL_RX_PARSE, and SOCKNAL_RX_SLOP.
Referenced by ksocknal_scheduler().
static int ksocknal_process_transmit (ksock_conn_t * conn, ksock_tx_t * tx) [static]
Definition at line 507 of file socklnd_cb.c.
References CDEBUG, cfs_time_add(), cfs_time_aftereq(), cfs_time_current(), CWARN, D_NET, ksock_conn::ksnc_closing, ksock_conn::ksnc_ipaddr, ksock_conn::ksnc_peer, ksock_conn::ksnc_port, ksock_conn::ksnc_tx_list, ksock_conn::ksnc_tx_scheduled, ksock_nal_data_t::ksnd_enomem_conns, ksock_nal_data_t::ksnd_reaper_lock, ksock_nal_data_t::ksnd_reaper_waitq, ksock_nal_data_t::ksnd_reaper_waketime, ksock_peer::ksnp_id, ksocknal_check_zc_req(), ksocknal_close_conn_and_siblings(), ksocknal_data, ksocknal_transmit(), ksocknal_uncheck_zc_req(), LASSERT, LCONSOLE_WARN, libcfs_id2str(), libcfs_kmemory, list_add_tail(), SOCKNAL_ENOMEM_RETRY, ksock_tx_t::tx_resid, ksock_tx_t::tx_zc_capable, and ksock_tx_t::tx_zc_checked.
Referenced by ksocknal_scheduler().
void ksocknal_queue_tx_locked (ksock_tx_t * tx, ksock_conn_t * conn)
Definition at line 690 of file socklnd_cb.c.
References CDEBUG, cfs_time_current(), cfs_time_shift(), D_NET, ksock_conn::ksnc_closing, ksock_conn::ksnc_ipaddr, ksock_conn::ksnc_peer, ksock_conn::ksnc_port, ksock_conn::ksnc_proto, ksock_conn::ksnc_scheduler, ksock_conn::ksnc_sock, ksock_conn::ksnc_tx_bufnob, ksock_conn::ksnc_tx_deadline, ksock_conn::ksnc_tx_list, ksock_conn::ksnc_tx_nob, ksock_conn::ksnc_tx_queue, ksock_conn::ksnc_tx_ready, ksock_conn::ksnc_tx_scheduled, ksock_tunables_t::ksnd_timeout, ksock_peer::ksnp_id, ksock_peer::ksnp_last_alive, KSOCK_MSG_NOOP, ksocknal_conn_addref(), ksocknal_tunables, ksocknal_tx_prep(), ksock_sched_t::kss_lock, ksock_sched_t::kss_tx_conns, ksock_sched_t::kss_waitq, ksock_sched_t::kss_zombie_noop_txs, LASSERT, libcfs_id2str(), list_add_tail(), list_empty(), lnet_iov_nob(), lnet_kiov_nob(), msg, lnet_msg::msg_hdr, ksock_proto::pro_queue_tx_msg, ksock_proto::pro_queue_tx_zcack, ksock_tx_t::tx_iov, ksock_tx_t::tx_kiov, ksock_tx_t::tx_list, ksock_tx_t::tx_lnetmsg, ksock_tx_t::tx_msg, ksock_tx_t::tx_niov, ksock_tx_t::tx_nkiov, ksock_tx_t::tx_nob, and ksock_tx_t::tx_resid.
Referenced by ksocknal_create_conn(), and ksocknal_launch_packet().
void ksocknal_read_callback (ksock_conn_t * conn)
Definition at line 1559 of file socklnd_cb.c.
References ENTRY, EXIT, ksock_conn::ksnc_rx_list, ksock_conn::ksnc_rx_ready, ksock_conn::ksnc_rx_scheduled, ksock_conn::ksnc_scheduler, ksocknal_conn_addref(), ksock_sched_t::kss_lock, ksock_sched_t::kss_rx_conns, ksock_sched_t::kss_waitq, and list_add_tail().
Referenced by ksocknal_create_conn(), and ksocknal_data_ready().
int ksocknal_reaper (void * arg)
Definition at line 2519 of file socklnd_cb.c.
References cfs_block_allsigs(), cfs_time_add(), cfs_time_current(), cfs_time_seconds(), cfs_time_sub(), INIT_LIST_HEAD, ksock_conn::ksnc_list, ksock_conn::ksnc_scheduler, ksock_conn::ksnc_tx_list, ksock_conn::ksnc_tx_ready, ksock_conn::ksnc_tx_scheduled, ksock_nal_data_t::ksnd_deathrow_conns, ksock_nal_data_t::ksnd_enomem_conns, ksock_nal_data_t::ksnd_peer_hash_size, ksock_nal_data_t::ksnd_reaper_lock, ksock_nal_data_t::ksnd_reaper_waitq, ksock_nal_data_t::ksnd_reaper_waketime, ksock_nal_data_t::ksnd_shuttingdown, ksock_tunables_t::ksnd_timeout, ksock_nal_data_t::ksnd_zombie_conns, ksocknal_check_peer_timeouts(), ksocknal_conn_decref(), ksocknal_data, ksocknal_destroy_conn(), ksocknal_terminate_conn(), ksocknal_thread_fini(), ksocknal_tunables, ksock_sched_t::kss_lock, ksock_sched_t::kss_tx_conns, ksock_sched_t::kss_waitq, LASSERT, list_add(), list_add_tail(), list_del(), list_del_init(), list_empty(), list_entry, list_head::next, SOCKNAL_ENOMEM_RETRY, and timeout.
Referenced by ksocknal_base_startup().
static int ksocknal_receive (ksock_conn_t * conn) [static]
Definition at line 341 of file socklnd_cb.c.
References cfs_time_seconds(), ENTRY, ksock_conn::ksnc_closing, ksock_conn::ksnc_rx_niov, ksock_conn::ksnc_rx_nob_wanted, ksock_conn::ksnc_rx_started, ksock_nal_data_t::ksnd_stall_rx, ksocknal_connsock_addref(), ksocknal_connsock_decref(), ksocknal_data, ksocknal_recv_iov(), ksocknal_recv_kiov(), LASSERT, and RETURN.
Referenced by ksocknal_process_receive().
int ksocknal_recv (lnet_ni_t * ni, void * private, lnet_msg_t * msg, int delayed, unsigned int niov, struct kvec * iov, lnet_kiov_t * kiov, unsigned int offset, unsigned int mlen, unsigned int rlen)
Definition at line 1316 of file socklnd_cb.c.
References ksock_rxiovspace_t::iov, ksock_rxiovspace_t::kiov, ksock_conn::ksnc_cookie, ksock_conn::ksnc_rx_iov, ksock_conn::ksnc_rx_iov_space, ksock_conn::ksnc_rx_kiov, ksock_conn::ksnc_rx_list, ksock_conn::ksnc_rx_niov, ksock_conn::ksnc_rx_nkiov, ksock_conn::ksnc_rx_nob_left, ksock_conn::ksnc_rx_nob_wanted, ksock_conn::ksnc_rx_ready, ksock_conn::ksnc_rx_scheduled, ksock_conn::ksnc_rx_state, ksock_conn::ksnc_scheduler, ksocknal_conn_decref(), ksock_sched_t::kss_lock, ksock_sched_t::kss_rx_conns, ksock_sched_t::kss_waitq, LASSERT, list_add_tail(), lnet_extract_iov(), lnet_extract_kiov(), lnet_iov_nob(), lnet_kiov_nob(), LNET_MAX_IOV, SOCKNAL_RX_LNET_PAYLOAD, SOCKNAL_RX_PARSE, and SOCKNAL_RX_PARSE_WAIT.
Referenced by ksocklnd_init().
int ksocknal_recv_hello (lnet_ni_t * ni, ksock_conn_t * conn, ksock_hello_msg_t * hello, lnet_process_id_t * peerid, __u64 * incarnation)
Definition at line 1696 of file socklnd_cb.c.
References __swab32, CERROR, ksock_conn::ksnc_ipaddr, ksock_conn::ksnc_port, ksock_conn::ksnc_proto, ksock_conn::ksnc_sock, ksock_conn::ksnc_type, ksock_tunables_t::ksnd_timeout, ksocknal_invert_type(), ksocknal_parse_proto_version(), ksocknal_protocol_v1x, ksocknal_protocol_v2x, ksocknal_protocol_v3x, ksocknal_send_hello(), ksocknal_tunables, LASSERT, LCONSOLE_ERROR_MSG, le32_to_cpu, libcfs_id2str(), lnet_acceptor_timeout(), LNET_MKNID(), LNET_NID_ANY, LNET_NIDNET(), LNET_PID_USERFLAG, LNET_PROTO_MAGIC, LNET_PROTO_TCP_MAGIC, lnet_sock_read(), lnet_ni::ni_nid, lnet_process_id_t::nid, lnet_process_id_t::pid, ksock_proto::pro_recv_hello, ksock_proto::pro_version, SOCKLND_CONN_NONE, and timeout.
Referenced by ksocknal_create_conn().
static int ksocknal_recv_iov (ksock_conn_t * conn) [static]
Definition at line 252 of file socklnd_cb.c.
References cfs_time_current(), cfs_time_shift(), ksock_conn::ksnc_peer, ksock_conn::ksnc_rx_deadline, ksock_conn::ksnc_rx_iov, ksock_conn::ksnc_rx_niov, ksock_conn::ksnc_rx_nob_left, ksock_conn::ksnc_rx_nob_wanted, ksock_conn::ksnc_rx_started, ksock_tunables_t::ksnd_timeout, ksock_peer::ksnp_last_alive, ksocknal_lib_recv_iov(), ksocknal_tunables, and LASSERT.
Referenced by ksocknal_receive().
static int ksocknal_recv_kiov (ksock_conn_t * conn) [static]
Definition at line 297 of file socklnd_cb.c.
References cfs_time_current(), cfs_time_shift(), lnet_kiov_t::kiov_len, lnet_kiov_t::kiov_offset, ksock_conn::ksnc_peer, ksock_conn::ksnc_rx_deadline, ksock_conn::ksnc_rx_kiov, ksock_conn::ksnc_rx_nkiov, ksock_conn::ksnc_rx_nob_left, ksock_conn::ksnc_rx_nob_wanted, ksock_conn::ksnc_rx_started, ksock_tunables_t::ksnd_timeout, ksock_peer::ksnp_last_alive, ksocknal_lib_recv_kiov(), ksocknal_tunables, and LASSERT.
Referenced by ksocknal_receive().
static int ksocknal_sched_cansleep (ksock_sched_t * sched) [inline, static]
Definition at line 1374 of file socklnd_cb.c.
References ksock_nal_data_t::ksnd_shuttingdown, ksocknal_data, ksock_sched_t::kss_lock, ksock_sched_t::kss_rx_conns, ksock_sched_t::kss_tx_conns, and list_empty().
Referenced by ksocknal_scheduler().
int ksocknal_scheduler (void * arg)
Definition at line 1388 of file socklnd_cb.c.
References CERROR, cfs_block_allsigs(), cfs_cpt_bind(), ksock_sched_info::ksi_cpt, ksock_sched_info::ksi_scheds, ksock_conn::ksnc_rx_list, ksock_conn::ksnc_rx_ready, ksock_conn::ksnc_rx_scheduled, ksock_conn::ksnc_rx_state, ksock_conn::ksnc_tx_carrier, ksock_conn::ksnc_tx_list, ksock_conn::ksnc_tx_queue, ksock_conn::ksnc_tx_ready, ksock_conn::ksnc_tx_scheduled, ksock_nal_data_t::ksnd_sched_info, ksock_nal_data_t::ksnd_shuttingdown, KSOCK_THREAD_CPT, KSOCK_THREAD_SID, ksocknal_conn_decref(), ksocknal_data, ksocknal_next_tx_carrier(), ksocknal_process_receive(), ksocknal_process_transmit(), ksocknal_sched_cansleep(), ksocknal_thread_fini(), ksocknal_tx_decref(), ksocknal_txlist_done(), ksock_sched_t::kss_lock, ksock_sched_t::kss_rx_conns, ksock_sched_t::kss_tx_conns, ksock_sched_t::kss_waitq, ksock_sched_t::kss_zombie_noop_txs, LASSERT, list_add(), list_add_tail(), list_del(), list_del_init(), list_empty(), list_entry, LIST_HEAD_INIT, lnet_cpt_table, list_head::next, SOCKNAL_RESCHED, SOCKNAL_RX_PARSE, SOCKNAL_RX_PARSE_WAIT, and ksock_tx_t::tx_list.
Referenced by ksocknal_start_schedulers().
int ksocknal_send (lnet_ni_t * ni, void * private, lnet_msg_t * lntmsg)
Definition at line 924 of file socklnd_cb.c.
References CDEBUG, CERROR, cfs_memory_pressure_get_and_set(), cfs_memory_pressure_restore(), D_NET, ksock_tunables_t::ksnd_zc_min_payload, KSOCK_MSG_LNET, ksocknal_alloc_tx(), ksocknal_free_tx(), ksocknal_launch_packet(), ksocknal_tunables, LASSERT, libcfs_id2str(), lnet_extract_iov(), lnet_extract_kiov(), LNET_MAX_IOV, lnet_msg::msg_iov, lnet_msg::msg_kiov, lnet_msg::msg_len, lnet_msg::msg_niov, lnet_msg::msg_offset, lnet_msg::msg_target, lnet_msg::msg_type, lnet_msg::msg_vmflush, offsetof, ksock_tx_t::paged, socklnd_init_msg(), ksock_tx_t::tx_conn, ksock_tx_t::tx_frags, ksock_tx_t::tx_iov, ksock_tx_t::tx_kiov, ksock_tx_t::tx_lnetmsg, ksock_tx_t::tx_msg, ksock_tx_t::tx_niov, ksock_tx_t::tx_nkiov, ksock_tx_t::tx_zc_capable, and ksock_tx_t::virt.
Referenced by ksocklnd_init().
int ksocknal_send_hello (lnet_ni_t * ni, ksock_conn_t * conn, lnet_nid_t peer_nid, ksock_hello_msg_t * hello)
Definition at line 1657 of file socklnd_cb.c.
References ksock_conn::ksnc_proto, ksock_conn::ksnc_type, ksock_net_t::ksnn_incarnation, LASSERT, lnet_t::ln_pid, LNET_MAX_INTERFACES, lnet_ni::ni_data, lnet_ni::ni_nid, ksock_proto::pro_send_hello, and the_lnet.
Referenced by ksocknal_create_conn(), and ksocknal_recv_hello().
static int ksocknal_send_iov (ksock_conn_t * conn, ksock_tx_t * tx) [static]
Definition at line 111 of file socklnd_cb.c.
References ksocknal_lib_send_iov(), LASSERT, ksock_tx_t::tx_iov, ksock_tx_t::tx_niov, and ksock_tx_t::tx_resid.
Referenced by ksocknal_transmit().
static int ksocknal_send_keepalive_locked (ksock_peer_t * peer) [static]
Definition at line 2354 of file socklnd_cb.c.
References cfs_time_add(), cfs_time_before(), cfs_time_current(), cfs_time_seconds(), cfs_time_shift(), ksock_conn::ksnc_scheduler, ksock_conn::ksnc_tx_queue, ksock_nal_data_t::ksnd_global_lock, ksock_tunables_t::ksnd_keepalive, ksocknal_alloc_tx_noop(), ksocknal_data, ksocknal_find_conn_locked(), ksocknal_free_tx(), ksocknal_launch_packet(), ksocknal_protocol_v3x, ksocknal_tunables, ksock_sched_t::kss_lock, and list_empty().
Referenced by ksocknal_check_peer_timeouts().
static int ksocknal_send_kiov (ksock_conn_t * conn, ksock_tx_t * tx) [static]
Definition at line 148 of file socklnd_cb.c.
References lnet_kiov_t::kiov_len, lnet_kiov_t::kiov_offset, ksocknal_lib_send_kiov(), LASSERT, ksock_tx_t::tx_kiov, ksock_tx_t::tx_niov, ksock_tx_t::tx_nkiov, and ksock_tx_t::tx_resid.
Referenced by ksocknal_transmit().
void ksocknal_thread_fini (void)
Definition at line 1020 of file socklnd_cb.c.
References ksock_nal_data_t::ksnd_global_lock, ksock_nal_data_t::ksnd_nthreads, and ksocknal_data.
Referenced by ksocknal_connd(), ksocknal_reaper(), and ksocknal_scheduler().
int ksocknal_thread_start (int(*)(void *arg) fn, void * arg, char * name)
Definition at line 1006 of file socklnd_cb.c.
References ksock_nal_data_t::ksnd_global_lock, ksock_nal_data_t::ksnd_nthreads, and ksocknal_data.
Referenced by ksocknal_base_startup(), ksocknal_connd_check_start(), and ksocknal_start_schedulers().
static int ksocknal_transmit (ksock_conn_t * conn, ksock_tx_t * tx) [static]
Definition at line 186 of file socklnd_cb.c.
References cfs_time_current(), cfs_time_seconds(), cfs_time_shift(), ksock_conn::ksnc_closing, ksock_conn::ksnc_peer, ksock_conn::ksnc_sock, ksock_conn::ksnc_tx_bufnob, ksock_conn::ksnc_tx_deadline, ksock_conn::ksnc_tx_nob, ksock_nal_data_t::ksnd_enomem_tx, ksock_nal_data_t::ksnd_stall_tx, ksock_tunables_t::ksnd_timeout, ksock_peer::ksnp_last_alive, ksocknal_connsock_addref(), ksocknal_connsock_decref(), ksocknal_data, ksocknal_lib_memory_pressure(), ksocknal_send_iov(), ksocknal_send_kiov(), ksocknal_tunables, LASSERT, ksock_tx_t::tx_niov, and ksock_tx_t::tx_resid.
Referenced by ksocknal_process_transmit().
void ksocknal_tx_done (lnet_ni_t * ni, ksock_tx_t * tx)
Definition at line 390 of file socklnd_cb.c.
References ENTRY, EXIT, ksock_conn::ksnc_peer, ksock_peer::ksnp_ni, ksocknal_conn_decref(), ksocknal_free_tx(), LASSERT, lnet_finalize(), ksock_tx_t::tx_conn, ksock_tx_t::tx_lnetmsg, ksock_tx_t::tx_resid, and ksock_tx_t::tx_zc_aborted.
Referenced by ksocknal_tx_decref(), and ksocknal_txlist_done().
void ksocknal_tx_prep (ksock_conn_t * conn, ksock_tx_t * tx)
Definition at line 680 of file socklnd_cb.c.
References ksock_conn::ksnc_proto, ksock_conn::ksnc_tx_nob, ksocknal_conn_addref(), ksock_proto::pro_pack, ksock_tx_t::tx_conn, and ksock_tx_t::tx_nob.
Referenced by ksocknal_close_conn_locked(), and ksocknal_queue_tx_locked().
void ksocknal_txlist_done (lnet_ni_t * ni, struct list_head * txlist, int error)
Definition at line 412 of file socklnd_cb.c.
References CNETERR, ksocknal_tx_done(), LASSERT, le32_to_cpu, le64_to_cpu, libcfs_nid2str(), list_del(), list_empty(), list_entry, lnet_msg::msg_hdr, list_head::next, ksock_tx_t::tx_list, ksock_tx_t::tx_lnetmsg, and ksock_tx_t::tx_refcount.
Referenced by ksocknal_connect(), ksocknal_create_conn(), ksocknal_del_peer(), ksocknal_flush_stale_txs(), and ksocknal_scheduler().
static void ksocknal_uncheck_zc_req (ksock_tx_t * tx) [static]
Definition at line 481 of file socklnd_cb.c.
References ksock_conn::ksnc_peer, ksock_peer::ksnp_lock, KSOCK_MSG_NOOP, ksocknal_tx_decref(), LASSERT, list_del(), ksock_tx_t::tx_conn, ksock_tx_t::tx_msg, ksock_tx_t::tx_zc_capable, ksock_tx_t::tx_zc_checked, and ksock_tx_t::tx_zc_list.
Referenced by ksocknal_process_transmit().
void ksocknal_write_callback (ksock_conn_t * conn)
Definition at line 1588 of file socklnd_cb.c.
References ENTRY, EXIT, ksock_conn::ksnc_scheduler, ksock_conn::ksnc_tx_list, ksock_conn::ksnc_tx_queue, ksock_conn::ksnc_tx_ready, ksock_conn::ksnc_tx_scheduled, ksocknal_conn_addref(), ksock_sched_t::kss_lock, ksock_sched_t::kss_tx_conns, ksock_sched_t::kss_waitq, list_add_tail(), and list_empty().
Referenced by ksocknal_create_conn(), and ksocknal_write_space().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.