Lustre: lustre/llite/statahead.c File Reference
lustre/llite/statahead.c File Reference
#include <linux/fs.h>
#include <linux/sched.h>
#include <linux/kthread.h>
#include <linux/mm.h>
#include <linux/highmem.h>
#include <linux/pagemap.h>
#include <obd_support.h>
#include <lustre_dlm.h>
#include "llite_internal.h"
Data Structures
struct sa_entry
Defines
#define DEBUG_SUBSYSTEM S_LLITE
#define SA_OMITTED_ENTRY_MAX 8ULL
Enumerations
enum se_state_t { SA_ENTRY_INIT = 0, SA_ENTRY_SUCC = 1, SA_ENTRY_INVA = 2 }
enum { LS_NOT_FIRST_DE = 0, LS_FIRST_DE, LS_FIRST_DOT_DE }
Functions
static DEFINE_SPINLOCK (sai_generation_lock)
static int sa_unhashed (struct sa_entry *entry)
static int sa_ready (struct sa_entry *entry)
static int sa_hash (int val)
static void sa_rehash (struct ll_statahead_info *sai, struct sa_entry *entry)
static void sa_unhash (struct ll_statahead_info *sai, struct sa_entry *entry)
static int agl_should_run (struct ll_statahead_info *sai, struct inode *inode)
static struct ll_inode_info * agl_first_entry (struct ll_statahead_info *sai)
static int sa_sent_full (struct ll_statahead_info *sai)
static int sa_has_callback (struct ll_statahead_info *sai)
static int agl_list_empty (struct ll_statahead_info *sai)
static int sa_low_hit (struct ll_statahead_info *sai)
(1) hit ratio less than 80% or (2) consecutive miss more than 8 then means low hit.
static int is_omitted_entry (struct ll_statahead_info *sai, __u64 index)
static struct sa_entry * sa_alloc (struct ll_statahead_info *sai, __u64 index, const char *name, int len, const struct lu_fid *fid)
static void sa_free (struct ll_statahead_info *sai, struct sa_entry *entry)
static struct sa_entry * sa_get (struct ll_statahead_info *sai, const struct qstr *qstr)
static void sa_kill (struct ll_statahead_info *sai, struct sa_entry *entry)
static void sa_put (struct ll_statahead_info *sai, struct sa_entry *entry)
static bool __sa_make_ready (struct ll_statahead_info *sai, struct sa_entry *entry, int ret)
static void sa_make_ready (struct ll_statahead_info *sai, struct sa_entry *entry, int ret)
static void ll_agl_add (struct ll_statahead_info *sai, struct inode *inode, int index)
static struct ll_statahead_info * ll_sai_alloc (struct dentry *dentry)
static void ll_sai_free (struct ll_statahead_info *sai)
static struct ll_statahead_info * ll_sai_get (struct inode *dir)
static void ll_sai_put (struct ll_statahead_info *sai)
static void ll_agl_trigger (struct inode *inode, struct ll_statahead_info *sai)
static void sa_instantiate (struct ll_statahead_info *sai, struct sa_entry *entry)
static void sa_handle_callback (struct ll_statahead_info *sai)
static int ll_statahead_interpret (struct ptlrpc_request *req, struct md_enqueue_info *minfo, int rc)
static void sa_fini_data (struct md_enqueue_info *minfo)
static struct md_enqueue_info * sa_prep_data (struct inode *dir, struct inode *child, struct sa_entry *entry)
static int sa_lookup (struct inode *dir, struct sa_entry *entry)
static int sa_revalidate (struct inode *dir, struct sa_entry *entry, struct dentry *dentry)
async stat for file found in dcache, similar to .revalidate
static void sa_statahead (struct dentry *parent, const char *name, int len, const struct lu_fid *fid)
static int ll_agl_thread (void *arg)
static void ll_start_agl (struct dentry *parent, struct ll_statahead_info *sai)
static int ll_statahead_thread (void *arg)
void ll_authorize_statahead (struct inode *dir, void *key)
void ll_deauthorize_statahead (struct inode *dir, void *key)
static int is_first_dirent (struct inode *dir, struct dentry *dentry)
static int revalidate_statahead_dentry (struct inode *dir, struct ll_statahead_info *sai, struct dentry **dentryp, bool unplug)
revalidate from statahead cache
static int start_statahead_thread (struct inode *dir, struct dentry *dentry)
int ll_statahead (struct inode *dir, struct dentry **dentryp, bool unplug)
statahead entry function, this is called when client getattr on a file, it will start statahead thread if this is the first dir entry, else revalidate dentry from statahead cache.
Variables
static unsigned int sai_generation = 0
Define Documentation
#define DEBUG_SUBSYSTEM S_LLITE
Definition at line 44 of file statahead.c.
#define SA_OMITTED_ENTRY_MAX 8ULL
Definition at line 50 of file statahead.c.
Referenced by is_omitted_entry().
Enumeration Type Documentation
anonymous enum
Enumerator:
LS_NOT_FIRST_DE
not first dirent, or is "."
LS_FIRST_DE
the first non-hidden dirent
LS_FIRST_DOT_DE
the first hidden dirent, that is "."
Definition at line 1247 of file statahead.c.
enum se_state_t
Enumerator:
SA_ENTRY_INIT
negative values are for error cases
SA_ENTRY_SUCC
init entry
SA_ENTRY_INVA
stat succeed
Definition at line 52 of file statahead.c.
Function Documentation
static bool __sa_make_ready (struct ll_statahead_info * sai, struct sa_entry * entry, int ret) [static]
Definition at line 316 of file statahead.c.
References __u64, LASSERT, list_add(), list_empty(), list_for_each_entry_reverse, SA_ENTRY_INVA, SA_ENTRY_SUCC, sa_ready(), ll_statahead_info::sai_entries, ll_statahead_info::sai_index_wait, sa_entry::se_index, sa_entry::se_list, and sa_entry::se_state.
Referenced by ll_statahead_interpret(), and sa_make_ready().
static struct ll_inode_info* agl_first_entry (struct ll_statahead_info * sai) [static, read]
Definition at line 139 of file statahead.c.
References list_entry, ll_inode_info::lli_agl_list, list_head::next, and ll_statahead_info::sai_agls.
Referenced by ll_agl_thread(), and ll_statahead_thread().
static int agl_list_empty (struct ll_statahead_info * sai) [inline, static]
Definition at line 157 of file statahead.c.
References list_empty(), and ll_statahead_info::sai_agls.
Referenced by ll_agl_add(), ll_agl_thread(), ll_sai_put(), and ll_statahead_thread().
static int agl_should_run (struct ll_statahead_info * sai, struct inode * inode) [inline, static]
Definition at line 132 of file statahead.c.
References ll_statahead_info::sai_agl_valid.
Referenced by sa_instantiate(), and sa_statahead().
static DEFINE_SPINLOCK (sai_generation_lock) [static]
static int is_first_dirent (struct inode * dir, struct dentry * dentry) [static]
FIXME choose the start offset of the readdir
Definition at line 1263 of file statahead.c.
References __u64, CDEBUG, CERROR, D_READA, DFID, ENTRY, EXIT, GOTO, lu_dirent::lde_hash, lu_dirent::lde_name, lu_dirent::lde_namelen, LDF_COLLIDE, lu_dirpage::ldp_flags, lu_dirpage::ldp_hash_end, le16_to_cpu, le32_to_cpu, le64_to_cpu, ll_dir_chain_fini(), ll_dir_chain_init(), ll_finish_md_op_data(), ll_get_dir_page(), ll_get_fsname(), ll_i2info(), ll_i2sbi(), ll_inode2fid(), ll_sb_info::ll_md_brw_pages, ll_prep_md_op_data(), ll_release_page(), ll_inode_info::lli_opendir_pid, LPU64, LS_FIRST_DE, LS_FIRST_DOT_DE, LS_NOT_FIRST_DE, lu_dirent_next(), lu_dirent_start(), LUSTRE_OPC_ANY, MDS_DIR_END_OFF, name, md_op_data::op_data, md_op_data::op_max_pages, PFID, RETURN, and unlikely.
Referenced by start_statahead_thread().
static int is_omitted_entry (struct ll_statahead_info * sai, __u64 index) [inline, static]
Definition at line 178 of file statahead.c.
References __u64, SA_OMITTED_ENTRY_MAX, ll_statahead_info::sai_index, and ll_statahead_info::sai_max.
Referenced by ll_agl_trigger(), and sa_put().
static void ll_agl_add (struct ll_statahead_info * sai, struct inode * inode, int index) [static]
Definition at line 371 of file statahead.c.
References agl_list_empty(), LASSERT, list_add_tail(), list_empty(), ll_i2info(), ll_inode_info::lli_agl_index, ll_inode_info::lli_agl_list, ll_inode_info::lli_agl_lock, ll_statahead_info::sai_agl_thread, ll_statahead_info::sai_agls, ll_statahead_info::sai_dentry, and ptlrpc_thread::t_ctl_waitq.
Referenced by sa_instantiate(), and sa_statahead().
static int ll_agl_thread (void * arg) [static]
Definition at line 868 of file statahead.c.
References agl_first_entry(), agl_list_empty(), CDEBUG, current_pid, D_READA, dir, ENTRY, l_wait_event, list_del_init(), ll_sb_info::ll_agl_total, ll_agl_trigger(), ll_i2info(), ll_i2sbi(), ll_sai_get(), ll_sai_put(), ll_inode_info::lli_agl_index, ll_inode_info::lli_agl_list, ll_inode_info::lli_agl_lock, ll_inode_info::lli_vfs_inode, RETURN, ll_statahead_info::sai_agl_thread, ll_statahead_info::sai_agl_valid, SVC_RUNNING, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, ptlrpc_thread::t_pid, thread, thread_is_init(), thread_is_running(), and thread_set_flags().
Referenced by ll_start_agl().
static void ll_agl_trigger (struct inode * inode, struct ll_statahead_info * sai) [static]
Definition at line 497 of file statahead.c.
References __u64, CDEBUG, cfs_time_before(), cfs_time_current(), cfs_time_shift(), cl_agl(), D_READA, DFID, ENTRY, EXIT, is_omitted_entry(), LASSERT, list_empty(), ll_i2info(), ll_inode_info::lli_agl_index, ll_inode_info::lli_agl_list, ll_inode_info::lli_fid, ll_inode_info::lli_glimpse_sem, ll_inode_info::lli_glimpse_time, LPU64, PFID, and RETURN_EXIT.
Referenced by ll_agl_thread(), and ll_statahead_thread().
void ll_authorize_statahead (struct inode * dir, void * key)
Definition at line 1198 of file statahead.c.
References current_pid, LASSERT, ll_i2info(), ll_inode_info::lli_opendir_key, ll_inode_info::lli_opendir_pid, ll_inode_info::lli_sa_enabled, ll_inode_info::lli_sa_lock, and ll_inode_info::lli_sai.
Referenced by ll_file_open().
void ll_deauthorize_statahead (struct inode * dir, void * key)
Definition at line 1220 of file statahead.c.
References CDEBUG, D_READA, DFID, LASSERT, ll_i2info(), ll_inode_info::lli_fid, ll_inode_info::lli_opendir_key, ll_inode_info::lli_opendir_pid, ll_inode_info::lli_sa_enabled, ll_inode_info::lli_sa_lock, ll_inode_info::lli_sai, PFID, ll_statahead_info::sai_thread, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, thread_is_running(), and thread_set_flags().
Referenced by ll_file_open(), and ll_file_release().
static struct ll_statahead_info* ll_sai_alloc (struct dentry * dentry) [static, read]
Definition at line 400 of file statahead.c.
References ENTRY, INIT_LIST_HEAD, ll_i2info(), LL_SA_CACHE_SIZE, LL_SA_RPC_MIN, ll_inode_info::lli_sa_generation, OBD_ALLOC_PTR, RETURN, ll_statahead_info::sai_agl_thread, ll_statahead_info::sai_agls, ll_statahead_info::sai_cache, ll_statahead_info::sai_cache_count, ll_statahead_info::sai_cache_lock, ll_statahead_info::sai_dentry, ll_statahead_info::sai_entries, sai_generation, ll_statahead_info::sai_index, ll_statahead_info::sai_interim_entries, ll_statahead_info::sai_max, ll_statahead_info::sai_refcount, ll_statahead_info::sai_thread, ll_statahead_info::sai_waitq, ptlrpc_thread::t_ctl_waitq, and unlikely.
Referenced by start_statahead_thread().
static void ll_sai_free (struct ll_statahead_info * sai) [inline, static]
Definition at line 439 of file statahead.c.
References LASSERT, OBD_FREE_PTR, and ll_statahead_info::sai_dentry.
Referenced by ll_sai_put(), and start_statahead_thread().
static struct ll_statahead_info* ll_sai_get (struct inode * dir) [static, read]
Definition at line 450 of file statahead.c.
References ll_i2info(), ll_inode_info::lli_sa_lock, ll_inode_info::lli_sai, and ll_statahead_info::sai_refcount.
Referenced by ll_agl_thread(), ll_statahead(), and ll_statahead_thread().
static void ll_sai_put (struct ll_statahead_info * sai) [static]
Definition at line 468 of file statahead.c.
References agl_list_empty(), LASSERT, list_for_each_entry_safe, ll_i2info(), ll_i2sbi(), ll_sb_info::ll_sa_running, ll_sai_free(), ll_inode_info::lli_sa_lock, ll_inode_info::lli_sai, sa_has_callback(), sa_kill(), ll_statahead_info::sai_agl_thread, ll_statahead_info::sai_cache_count, ll_statahead_info::sai_dentry, ll_statahead_info::sai_entries, ll_statahead_info::sai_refcount, ll_statahead_info::sai_replied, ll_statahead_info::sai_sent, ll_statahead_info::sai_thread, and thread_is_stopped().
Referenced by ll_agl_thread(), ll_statahead(), ll_statahead_thread(), and start_statahead_thread().
static void ll_start_agl (struct dentry * parent, struct ll_statahead_info * sai) [static]
Definition at line 940 of file statahead.c.
References CDEBUG, CERROR, D_READA, ENTRY, EXIT, l_wait_event, ll_agl_thread(), ll_i2info(), ll_inode_info::lli_opendir_pid, RETURN_EXIT, ll_statahead_info::sai_agl_thread, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, thread, thread_is_running(), thread_is_stopped(), and thread_set_flags().
Referenced by ll_statahead_thread().
int ll_statahead (struct inode * dir, struct dentry ** dentryp, bool unplug)
statahead entry function, this is called when client getattr on a file, it will start statahead thread if this is the first dir entry, else revalidate dentry from statahead cache.
Parameters:
[in] dir parent directory
[out] dentryp dentry to getattr
[in] unplug unplug statahead window only (normally for negative dentry)
Return values:
1 on success
0 revalidation from statahead cache failed, caller needs to getattr from server directly
negative number on error, caller often ignores this and then getattr from server
Definition at line 1624 of file statahead.c.
References CDEBUG, D_READA, ll_sai_get(), ll_sai_put(), revalidate_statahead_dentry(), and start_statahead_thread().
Referenced by ll_lookup_it(), and ll_revalidate_dentry().
static int ll_statahead_interpret (struct ptlrpc_request * req, struct md_enqueue_info * minfo, int rc) [static]
Definition at line 653 of file statahead.c.
References __sa_make_ready(), __u64, CDEBUG, D_READA, dir, DISP_LOOKUP_NEG, ENTRY, it_disposition(), lookup_intent::it_lock_handle, LASSERT, list_add_tail(), ll_i2info(), ll_intent_drop_lock(), ll_intent_release(), ll_inode_info::lli_sa_lock, ll_inode_info::lli_sai, md_enqueue_info::mi_cbdata, md_enqueue_info::mi_dir, md_enqueue_info::mi_it, OBD_FREE_PTR, ptlrpc_request_addref(), RETURN, sa_has_callback(), ll_statahead_info::sai_interim_entries, ll_statahead_info::sai_replied, ll_statahead_info::sai_thread, ll_statahead_info::sai_waitq, sa_entry::se_handle, sa_entry::se_list, sa_entry::se_minfo, sa_entry::se_qstr, sa_entry::se_req, ptlrpc_thread::t_ctl_waitq, and thread_is_stopped().
Referenced by sa_prep_data().
static int ll_statahead_thread (void * arg) [static]
Definition at line 967 of file statahead.c.
References __u64, agl_first_entry(), agl_list_empty(), CDEBUG, current_pid, D_READA, DFID, dir, ENTRY, EXIT, fid_le_to_cpu(), GOTO, l_wait_event, lu_dirent::lde_fid, lu_dirent::lde_hash, lu_dirent::lde_name, lu_dirent::lde_namelen, LDF_COLLIDE, lu_dirpage::ldp_flags, lu_dirpage::ldp_hash_end, le16_to_cpu, le32_to_cpu, le64_to_cpu, list_del_init(), ll_agl_trigger(), ll_dir_chain_fini(), ll_dir_chain_init(), ll_finish_md_op_data(), ll_sb_info::ll_flags, ll_get_dir_page(), ll_i2info(), ll_i2sbi(), ll_inode2fid(), ll_sb_info::ll_md_brw_pages, ll_prep_md_op_data(), ll_release_page(), ll_sb_info::ll_sa_total, ll_sb_info::ll_sa_wrong, ll_sai_get(), ll_sai_put(), LL_SBI_AGL_ENABLED, ll_start_agl(), ll_inode_info::lli_agl_list, ll_inode_info::lli_agl_lock, ll_inode_info::lli_fid, ll_inode_info::lli_opendir_pid, ll_inode_info::lli_sa_enabled, ll_inode_info::lli_sa_lock, ll_inode_info::lli_vfs_inode, LPU64, lu_dirent_next(), lu_dirent_start(), LUSTRE_OPC_ANY, LWI_TIMEOUT, MDS_DIR_END_OFF, name, md_op_data::op_data, md_op_data::op_max_pages, PFID, sa_handle_callback(), sa_has_callback(), sa_low_hit(), sa_sent_full(), sa_statahead(), ll_statahead_info::sai_agl_thread, ll_statahead_info::sai_agl_valid, ll_statahead_info::sai_hit, ll_statahead_info::sai_in_readpage, ll_statahead_info::sai_index, ll_statahead_info::sai_ls_all, ll_statahead_info::sai_miss, ll_statahead_info::sai_replied, ll_statahead_info::sai_sent, ll_statahead_info::sai_skip_hidden, ll_statahead_info::sai_thread, ll_statahead_info::sai_waitq, SVC_RUNNING, SVC_STOPPED, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, ptlrpc_thread::t_pid, thread_is_init(), thread_is_running(), thread_is_stopped(), thread_set_flags(), and unlikely.
Referenced by start_statahead_thread().
static int revalidate_statahead_dentry (struct inode * dir, struct ll_statahead_info * sai, struct dentry ** dentryp, bool unplug) [static]
revalidate from statahead cache
Parameters:
[in] dir parent directory
[in] sai sai structure
[out] dentryp pointer to dentry which will be revalidated
[in] unplug unplug statahead window only (normally for negative dentry)
Return values:
1 on success, dentry is saved in
0 if revalidation failed (no proper lock on client)
negative number upon error
Definition at line 1394 of file statahead.c.
References __u64, CDEBUG, cfs_time_seconds(), d_lustre_invalid(), d_lustre_revalidate(), D_READA, DFID, ENTRY, GOTO, IT_GETATTR, lookup_intent::it_op, l_wait_event, ll_d2d, ll_get_fsname(), ll_i2info(), ll_i2mdexp(), ll_inode2fid(), ll_intent_release(), ll_splice_alias(), ll_dentry_data::lld_sa_generation, ll_inode_info::lli_sa_generation, ll_inode_info::lli_sa_lock, LWI_ON_SIGNAL_NOOP, LWI_TIMEOUT_INTR, md_revalidate_lock(), MDS_INODELOCK_LOOKUP, PFID, RETURN, SA_ENTRY_SUCC, sa_get(), sa_handle_callback(), sa_put(), sa_ready(), ll_statahead_info::sai_in_readpage, ll_statahead_info::sai_index_wait, ll_statahead_info::sai_ls_all, ll_statahead_info::sai_miss_hidden, ll_statahead_info::sai_skip_hidden, ll_statahead_info::sai_waitq, sa_entry::se_handle, sa_entry::se_index, sa_entry::se_inode, and sa_entry::se_state.
Referenced by ll_statahead().
static struct sa_entry* sa_alloc (struct ll_statahead_info * sai, __u64 index, const char * name, int len, const struct lu_fid * fid) [static, read]
Definition at line 186 of file statahead.c.
References CDEBUG, D_READA, ENTRY, INIT_LIST_HEAD, ll_i2info(), ll_inode_info::lli_sa_lock, LPU64, OBD_ALLOC, RETURN, SA_ENTRY_INIT, sa_rehash(), ll_statahead_info::sai_cache_count, ll_statahead_info::sai_dentry, sa_entry::se_fid, sa_entry::se_index, sa_entry::se_list, sa_entry::se_qstr, sa_entry::se_size, sa_entry::se_state, and unlikely.
Referenced by sa_statahead().
static void sa_fini_data (struct md_enqueue_info * minfo) [static]
Definition at line 716 of file statahead.c.
References md_enqueue_info::mi_dir, and OBD_FREE_PTR.
Referenced by sa_lookup(), and sa_revalidate().
static void sa_free (struct ll_statahead_info * sai, struct sa_entry * entry) [static]
Definition at line 228 of file statahead.c.
References CDEBUG, D_READA, LASSERT, list_empty(), LPU64, OBD_FREE, sa_unhashed(), ll_statahead_info::sai_cache_count, sa_entry::se_index, sa_entry::se_list, sa_entry::se_qstr, and sa_entry::se_size.
Referenced by sa_kill().
static struct sa_entry* sa_get (struct ll_statahead_info * sai, const struct qstr * qstr) [static, read]
Definition at line 246 of file statahead.c.
References list_for_each_entry, sa_hash(), ll_statahead_info::sai_cache, sa_entry::se_hash, and sa_entry::se_qstr.
Referenced by revalidate_statahead_dentry().
static void sa_handle_callback (struct ll_statahead_info * sai) [static]
Definition at line 625 of file statahead.c.
References list_del_init(), list_entry, ll_i2info(), ll_inode_info::lli_sa_lock, list_head::next, sa_has_callback(), sa_instantiate(), ll_statahead_info::sai_dentry, ll_statahead_info::sai_interim_entries, sa_entry::se_list, and unlikely.
Referenced by ll_statahead_thread(), and revalidate_statahead_dentry().
static int sa_has_callback (struct ll_statahead_info * sai) [inline, static]
Definition at line 152 of file statahead.c.
References list_empty(), and ll_statahead_info::sai_interim_entries.
Referenced by ll_sai_put(), ll_statahead_interpret(), ll_statahead_thread(), and sa_handle_callback().
static int sa_hash (int val) [inline, static]
Definition at line 105 of file statahead.c.
References LL_SA_CACHE_MASK.
Referenced by sa_get(), sa_rehash(), and sa_unhash().
static void sa_instantiate (struct ll_statahead_info * sai, struct sa_entry * entry) [static]
Definition at line 563 of file statahead.c.
References agl_should_run(), CDEBUG, D_READA, DFID, dir, ENTRY, EXIT, GOTO, lookup_intent::it_lock_handle, LASSERT, ll_agl_add(), ll_get_fsname(), ll_i2mdexp(), ll_i2sbi(), ll_inode2fid(), ll_prep_inode(), ll_set_lock_data(), lu_fid_eq(), mdt_body::mbo_fid1, md_revalidate_lock(), md_enqueue_info::mi_data, md_enqueue_info::mi_it, md_op_data::op_fid2, PFID, req_capsule_server_get(), RMF_MDT_BODY, ptlrpc_request::rq_pill, sa_make_ready(), ll_statahead_info::sai_dentry, sa_entry::se_handle, sa_entry::se_index, sa_entry::se_inode, sa_entry::se_minfo, sa_entry::se_qstr, sa_entry::se_req, and unlikely.
Referenced by sa_handle_callback().
static void sa_kill (struct ll_statahead_info * sai, struct sa_entry * entry) [inline, static]
Definition at line 262 of file statahead.c.
References LASSERT, list_del_init(), list_empty(), ll_i2info(), ll_inode_info::lli_sa_lock, sa_free(), sa_ready(), sa_unhash(), sa_unhashed(), ll_statahead_info::sai_dentry, sa_entry::se_inode, and sa_entry::se_list.
Referenced by ll_sai_put(), and sa_put().
static int sa_lookup (struct inode * dir, struct sa_entry * entry) [static]
Definition at line 763 of file statahead.c.
References ENTRY, ll_i2mdexp(), md_intent_getattr_async(), RETURN, sa_fini_data(), and sa_prep_data().
Referenced by __osd_object_attr_get(), __osd_xattr_get_large(), __osd_xattr_load(), __osd_xattr_set(), osd_find_parent_by_dnode(), osd_get_fid_by_oid(), osd_object_sa_init(), and sa_statahead().
static int sa_low_hit (struct ll_statahead_info * sai) [inline, static]
(1) hit ratio less than 80% or (2) consecutive miss more than 8 then means low hit.
Definition at line 168 of file statahead.c.
References ll_statahead_info::sai_consecutive_miss, ll_statahead_info::sai_hit, and ll_statahead_info::sai_miss.
Referenced by ll_statahead_thread().
static void sa_make_ready (struct ll_statahead_info * sai, struct sa_entry * entry, int ret) [static]
Definition at line 342 of file statahead.c.
References __sa_make_ready(), ll_i2info(), ll_intent_release(), ll_inode_info::lli_sa_lock, md_enqueue_info::mi_dir, md_enqueue_info::mi_it, OBD_FREE_PTR, ptlrpc_req_finished(), ll_statahead_info::sai_dentry, ll_statahead_info::sai_waitq, sa_entry::se_minfo, and sa_entry::se_req.
Referenced by sa_instantiate(), and sa_statahead().
static struct md_enqueue_info* sa_prep_data (struct inode * dir, struct inode * child, struct sa_entry * entry) [static, read]
Definition at line 726 of file statahead.c.
References ldlm_enqueue_info::ei_cb_bl, ldlm_enqueue_info::ei_cb_cp, ldlm_enqueue_info::ei_cb_gl, ldlm_enqueue_info::ei_cbdata, ldlm_enqueue_info::ei_mode, ldlm_enqueue_info::ei_type, IT_GETATTR, lookup_intent::it_op, it_to_lock_mode(), ldlm_completion_ast(), LDLM_IBITS, ll_md_blocking_ast(), ll_prep_md_op_data(), ll_statahead_interpret(), LUSTRE_OPC_ANY, md_enqueue_info::mi_cb, md_enqueue_info::mi_cbdata, md_enqueue_info::mi_data, md_enqueue_info::mi_dir, md_enqueue_info::mi_einfo, md_enqueue_info::mi_it, OBD_ALLOC_PTR, OBD_FREE_PTR, md_op_data::op_data, md_op_data::op_fid2, and sa_entry::se_fid.
Referenced by sa_lookup(), and sa_revalidate().
static void sa_put (struct ll_statahead_info * sai, struct sa_entry * entry) [static]
Definition at line 284 of file statahead.c.
References is_omitted_entry(), list_for_each_entry_safe, ll_i2sbi(), ll_sb_info::ll_sa_max, SA_ENTRY_SUCC, sa_kill(), ll_statahead_info::sai_consecutive_miss, ll_statahead_info::sai_dentry, ll_statahead_info::sai_entries, ll_statahead_info::sai_hit, ll_statahead_info::sai_max, ll_statahead_info::sai_miss, ll_statahead_info::sai_thread, sa_entry::se_index, sa_entry::se_state, and ptlrpc_thread::t_ctl_waitq.
Referenced by revalidate_statahead_dentry().
static int sa_ready (struct sa_entry * entry) [inline, static]
Definition at line 98 of file statahead.c.
References SA_ENTRY_INIT, and sa_entry::se_state.
Referenced by __sa_make_ready(), revalidate_statahead_dentry(), and sa_kill().
static void sa_rehash (struct ll_statahead_info * sai, struct sa_entry * entry) [inline, static]
Definition at line 112 of file statahead.c.
References list_add_tail(), sa_hash(), ll_statahead_info::sai_cache, ll_statahead_info::sai_cache_lock, sa_entry::se_hash, and sa_entry::se_qstr.
Referenced by sa_alloc().
static int sa_revalidate (struct inode * dir, struct sa_entry * entry, struct dentry * dentry) [static]
async stat for file found in dcache, similar to .revalidate
Return values:
1 dentry valid, no RPC sent
0 dentry invalid, will send async stat RPC
negative number upon error
Definition at line 787 of file statahead.c.
References ENTRY, IT_GETATTR, lookup_intent::it_lock_handle, lookup_intent::it_op, ll_i2mdexp(), ll_inode2fid(), ll_intent_release(), md_intent_getattr_async(), md_revalidate_lock(), RETURN, sa_fini_data(), sa_prep_data(), sa_entry::se_handle, sa_entry::se_inode, and unlikely.
Referenced by sa_statahead().
static int sa_sent_full (struct ll_statahead_info * sai) [inline, static]
Definition at line 146 of file statahead.c.
References ll_statahead_info::sai_cache_count, and ll_statahead_info::sai_max.
Referenced by ll_statahead_thread().
static void sa_statahead (struct dentry * parent, const char * name, int len, const struct lu_fid * fid) [static]
Definition at line 830 of file statahead.c.
References agl_should_run(), dir, ENTRY, EXIT, ll_agl_add(), ll_i2info(), ll_inode_info::lli_sai, RETURN_EXIT, sa_alloc(), sa_lookup(), sa_make_ready(), sa_revalidate(), ll_statahead_info::sai_index, ll_statahead_info::sai_sent, sa_entry::se_index, and sa_entry::se_qstr.
Referenced by ll_statahead_thread().
static void sa_unhash (struct ll_statahead_info * sai, struct sa_entry * entry) [inline, static]
Definition at line 123 of file statahead.c.
References list_del_init(), sa_hash(), ll_statahead_info::sai_cache_lock, sa_entry::se_hash, and sa_entry::se_qstr.
Referenced by sa_kill().
static int sa_unhashed (struct sa_entry * entry) [inline, static]
Definition at line 92 of file statahead.c.
References list_empty(), and sa_entry::se_hash.
Referenced by sa_free(), and sa_kill().
static int start_statahead_thread (struct inode * dir, struct dentry * dentry) [static]
Definition at line 1534 of file statahead.c.
References CDEBUG, CERROR, current_pid, D_READA, ENTRY, GOTO, is_first_dirent(), l_wait_event, ll_i2info(), ll_i2sbi(), ll_sb_info::ll_sa_running, ll_sai_alloc(), ll_sai_free(), ll_sai_put(), ll_statahead_thread(), ll_inode_info::lli_opendir_key, ll_inode_info::lli_opendir_pid, ll_inode_info::lli_sa_enabled, ll_inode_info::lli_sa_lock, ll_inode_info::lli_sai, LS_FIRST_DOT_DE, LS_NOT_FIRST_DE, RETURN, ll_statahead_info::sai_ls_all, ll_statahead_info::sai_thread, ptlrpc_thread::t_ctl_waitq, thread, thread_is_running(), thread_is_stopped(), and unlikely.
Referenced by ll_statahead().
Variable Documentation
unsigned int sai_generation = 0 [static]
Definition at line 89 of file statahead.c.
Referenced by ll_sai_alloc().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.