Lustre: lustre/obdclass/statfs_pack.c File Reference
lustre/obdclass/statfs_pack.c File Reference
#include <linux/statfs.h>
#include <lustre_export.h>
#include <lustre_net.h>
#include <obd_support.h>
#include <obd_class.h>
Defines
#define DEBUG_SUBSYSTEM S_CLASS
Functions
void statfs_pack (struct obd_statfs *osfs, struct kstatfs *sfs)
void statfs_unpack (struct kstatfs *sfs, struct obd_statfs *osfs)
Define Documentation
#define DEBUG_SUBSYSTEM S_CLASS
Definition at line 43 of file statfs_pack.c.
Function Documentation
void statfs_pack (struct obd_statfs * osfs, struct kstatfs * sfs)
Definition at line 51 of file statfs_pack.c.
References obd_statfs::os_bavail, obd_statfs::os_bfree, obd_statfs::os_blocks, obd_statfs::os_bsize, obd_statfs::os_ffree, obd_statfs::os_files, obd_statfs::os_namelen, and obd_statfs::os_type.
Referenced by osd_statfs().
void statfs_unpack (struct kstatfs * sfs, struct obd_statfs * osfs)
Definition at line 65 of file statfs_pack.c.
References obd_statfs::os_bavail, obd_statfs::os_bfree, obd_statfs::os_blocks, obd_statfs::os_bsize, obd_statfs::os_ffree, obd_statfs::os_files, obd_statfs::os_namelen, and obd_statfs::os_type.
Referenced by ll_statfs(), and server_statfs().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.