Lustre: libcfs/libcfs/util/string.c File Reference
libcfs/libcfs/util/string.c File Reference
#include <ctype.h>
#include <errno.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
Functions
size_t strlcpy (char *dst, const char *src, size_t size)
size_t strlcat (char *dst, const char *src, size_t size)
int cfs_gettok (struct cfs_lstr *next, char delim, struct cfs_lstr *res)
Extracts tokens from strings.
int cfs_str2num_check (char *str, int nob, unsigned *num, unsigned min, unsigned max)
Converts string to integer.
static int cfs_range_expr_parse (struct cfs_lstr *src, unsigned min, unsigned max, int bracketed, struct cfs_range_expr **expr)
Parses <range_expr> token of the syntax.
static int cfs_range_expr_print (char *buffer, int count, struct cfs_range_expr *expr, bool bracketed)
Print the range expression re into specified buffer.
int cfs_expr_list_print (char *buffer, int count, struct cfs_expr_list *expr_list)
Print a list of range expressions (expr_list) into specified buffer.
int cfs_expr_list_match (__u32 value, struct cfs_expr_list *expr_list)
Matches value (value) against ranges expression list expr_list.
static void cfs_expr_list_free (struct cfs_expr_list *expr_list)
Frees cfs_range_expr structures of expr_list.
int cfs_expr_list_parse (char *str, int len, unsigned min, unsigned max, struct cfs_expr_list **elpp)
Parses <cfs_expr_list> token of the syntax.
void cfs_expr_list_free_list (struct list_head *list)
Frees cfs_expr_list structures of list.
Function Documentation
static void cfs_expr_list_free (struct cfs_expr_list * expr_list) [static]
Frees cfs_range_expr structures of expr_list.
Return values:
none
Definition at line 339 of file string.c.
References cfs_expr_list::el_exprs, list_del(), list_empty(), list_entry, list_head::next, and cfs_range_expr::re_link.
void cfs_expr_list_free_list (struct list_head * list)
Frees cfs_expr_list structures of list.
For each struct cfs_expr_list structure found on list it frees range_expr list attached to it and frees the cfs_expr_list itself.
Return values:
none
Definition at line 423 of file string.c.
References cfs_expr_list_free(), cfs_expr_list::el_link, list_del(), list_empty(), list_entry, and list_head::next.
Referenced by cfs_ip_addr_parse(), free_addrranges(), and lnet_match_network_token().
int cfs_expr_list_match (__u32 value, struct cfs_expr_list * expr_list)
Matches value (value) against ranges expression list expr_list.
Return values:
1 if value matches
0 otherwise
Definition at line 320 of file string.c.
References cfs_expr_list::el_exprs, list_for_each_entry, cfs_range_expr::re_hi, cfs_range_expr::re_link, cfs_range_expr::re_lo, and cfs_range_expr::re_stride.
Referenced by cfs_ip_addr_match(), and libcfs_num_match().
int cfs_expr_list_parse (char * str, int len, unsigned min, unsigned max, struct cfs_expr_list ** elpp)
Parses <cfs_expr_list> token of the syntax.
Return values:
0 if str parses to <number> | <expr_list>
-errno otherwise
Definition at line 360 of file string.c.
References cfs_expr_list_free(), cfs_gettok(), cfs_range_expr_parse(), cfs_expr_list::el_exprs, INIT_LIST_HEAD, list_add_tail(), cfs_lstr::ls_len, cfs_lstr::ls_str, and cfs_range_expr::re_link.
Referenced by cfs_ip_addr_parse(), libcfs_num_parse(), lnet_parse_networks(), ptlrpc_register_service(), and ptlrpcd_init().
int cfs_expr_list_print (char * buffer, int count, struct cfs_expr_list * expr_list)
Print a list of range expressions (expr_list) into specified buffer.
If the list contains several expressions, separate them with comma and surround the list with brackets.
Return values:
number of characters written
Definition at line 285 of file string.c.
References cfs_range_expr_print(), cfs_expr_list::el_exprs, list_for_each_entry, and cfs_range_expr::re_link.
Referenced by libcfs_ip_addr_range_print(), and libcfs_num_addr_range_print().
int cfs_gettok (struct cfs_lstr * next, char delim, struct cfs_lstr * res)
Extracts tokens from strings.
Looks for delim in string next, sets res to point to substring before the delimiter, sets next right after the found delimiter.
Return values:
1 if res points to a string of non-whitespace characters
0 otherwise
Definition at line 99 of file string.c.
References end, cfs_lstr::ls_len, and cfs_lstr::ls_str.
Referenced by cfs_expr_list_parse(), cfs_ip_addr_parse(), cfs_parse_nidlist(), cfs_range_expr_parse(), and parse_nidrange().
static int cfs_range_expr_parse (struct cfs_lstr * src, unsigned min, unsigned max, int bracketed, struct cfs_range_expr ** expr) [static]
Parses <range_expr> token of the syntax.
If bracketed is false, src should only have a single token which can be <number> or \*
Return values:
pointer to allocated range_expr and initialized range_expr::re_lo, range_expr::re_hi and range_expr:re_stride if src parses to <number> | <number> '-' <number> | <number> '-' <number> '/' <number>
0 will be returned if it can be parsed, otherwise -EINVAL or -ENOMEM will be returned.
Definition at line 184 of file string.c.
References cfs_gettok(), cfs_str2num_check(), cfs_lstr::ls_len, and cfs_lstr::ls_str.
Referenced by cfs_expr_list_parse().
static int cfs_range_expr_print (char * buffer, int count, struct cfs_range_expr * expr, bool bracketed) [static]
Print the range expression re into specified buffer.
If bracketed is true, expression does not need additional brackets.
Return values:
number of characters written
Definition at line 255 of file string.c.
References cfs_range_expr::re_hi, cfs_range_expr::re_lo, and cfs_range_expr::re_stride.
Referenced by cfs_expr_list_print().
int cfs_str2num_check (char * str, int nob, unsigned * num, unsigned min, unsigned max)
Converts string to integer.
Accepts decimal and hexadecimal number recordings.
Return values:
1 if first nob chars of str convert to decimal or hexadecimal integer in the range [min, max]
0 otherwise
Definition at line 153 of file string.c.
Referenced by add_nidrange(), and cfs_range_expr_parse().
size_t strlcat (char * dst, const char * src, size_t size)
Definition at line 72 of file string.c.
References ret.
Referenced by cfs_get_param_paths(), ct_archive(), ct_rebind_one(), ct_remove(), gss_cli_ctx_flags2str(), ll_init_security(), llapi_search_fsname(), lmd_parse(), lwp_setup(), osd_mount(), sec_flags2str(), and sptlrpc_secflags2str().
size_t strlcpy (char * dst, const char * src, size_t size)
Definition at line 58 of file string.c.
References ret.
Referenced by cb_getstripe(), cfs_hash_create(), cfs_wi_sched_create(), class_set_global(), ct_max_sequence(), dt_store_resolve(), extract_fsname_poolname(), fld_cache_init(), get_groups_local(), get_lmd_info(), gss_ctx_refresh_pf(), iam_convert(), kiblnd_init_poolset(), ksocknal_enumerate_interfaces(), ksocknal_startup(), libcfs_debug_init(), ll_init_security(), ll_send_mgc_param(), llapi_get_poolmembers(), llapi_json_add_item(), llapi_lov_dump_user_lmm(), lmv_unpack_md_v1(), lod_dir_striping_create_internal(), lod_generate_and_set_lovea(), lod_pool_new(), lov_lsm_pack(), lov_pool_new(), lr_add_pc(), lr_clear_cl(), lr_get_symlink(), lr_link(), lr_parse_line(), lr_read_log(), lr_replicate(), lsi_prepare(), lsm_unpackmd_v3(), lstcon_acceptor_handle(), lstcon_sesrpc_prep(), lstcon_session_new(), main(), mdc_pack_name(), mdd_changelog_rec_ext_jobid(), mdd_changelog_rec_ext_rename(), mdt_coordinator_cb(), mgc_process_recover_log(), mgs_modify(), mgs_replace_nids_log(), mgs_setparam(), mgs_steal_client_llog_handler(), ofd_grant_commit_cb_add(), ofd_soft_sync_cb_add(), osd_device_init(), osd_device_init0(), osd_mount(), osd_oi_lookup(), param_callback(), parse_callout_info(), ptl_ipaddr_2_str(), ptlrpc_nrs_policy_register(), qmt_device_init0(), qsd_init(), record_marker(), sattr_cache_get_defaults(), seq_update_cb_add(), server_lsi2mti(), server_name2svname(), sfw_debug_session(), sfw_init_session(), sfw_make_session(), sptlrpc_conf_get(), sptlrpc_conf_get_tgt(), sptlrpc_parse_flavor(), tgt_last_commit_cb_add(), tgt_new_client_cb_add(), ucred_set_jobid(), and upcall_cache_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.