Lustre: lgss_mech_type Struct Reference
lgss_mech_type Struct Reference
#include <lgss_utils.h>
Data Fields
char * lmt_name
lgss_mech_t lmt_mech_n
int(* lmt_init)(void)
void(* lmt_fini)(void)
int(* lmt_prepare_cred)(struct lgss_cred *cred)
void(* lmt_release_cred)(struct lgss_cred *cred)
int(* lmt_using_cred)(struct lgss_cred *cred)
Detailed Description
Definition at line 152 of file lgss_utils.h.
Field Documentation
void(* lgss_mech_type::lmt_fini)(void)
Referenced by lgss_mech_finalize().
int(* lgss_mech_type::lmt_init)(void)
Referenced by lgss_mech_initialize().
lgss_mech_t lgss_mech_type::lmt_mech_n
Definition at line 154 of file lgss_utils.h.
Referenced by lgssc_kr_negotiate().
char* lgss_mech_type::lmt_name
Definition at line 153 of file lgss_utils.h.
Referenced by lgss_create_cred(), lgss_destroy_cred(), lgss_mech_finalize(), lgss_mech_initialize(), lgss_prepare_cred(), lgss_release_cred(), lgss_using_cred(), and main().
int(* lgss_mech_type::lmt_prepare_cred)(struct lgss_cred *cred)
Referenced by lgss_prepare_cred().
void(* lgss_mech_type::lmt_release_cred)(struct lgss_cred *cred)
Referenced by lgss_release_cred().
int(* lgss_mech_type::lmt_using_cred)(struct lgss_cred *cred)
Referenced by lgss_using_cred().
The documentation for this struct was generated from the following file:
lustre/utils/gss/lgss_utils.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.