Lustre: cl_lock_operations Struct Reference
cl_lock_operations Struct Reference
[cl_lock]
#include <cl_object.h>
Data Fields
void(* clo_fini)(const struct lu_env *env, struct cl_lock_slice *slice)
Destructor.
int(* clo_print)(const struct lu_env *env, void *cookie, lu_printer_t p, const struct cl_lock_slice *slice)
Optional debugging helper.
int(* clo_enqueue)(const struct lu_env *env, const struct cl_lock_slice *slice, struct cl_io *io, struct cl_sync_io *anchor)
Attempts to enqueue the lock.
void(* clo_cancel)(const struct lu_env *env, const struct cl_lock_slice *slice)
Cancel a lock, release its DLM lock ref, while does not cancel the DLM lock.
Detailed Description
See also:
vvp_lock_ops, lov_lock_ops, lovsub_lock_ops, osc_lock_ops
Definition at line 1215 of file cl_object.h.
Field Documentation
void(* cl_lock_operations::clo_cancel)(const struct lu_env *env, const struct cl_lock_slice *slice)
Cancel a lock, release its DLM lock ref, while does not cancel the DLM lock.
Referenced by cl_lock_cancel().
int(* cl_lock_operations::clo_enqueue)(const struct lu_env *env, const struct cl_lock_slice *slice, struct cl_io *io, struct cl_sync_io *anchor)
Attempts to enqueue the lock.
Called top-to-bottom.
Return values:
0 this layer has enqueued the lock successfully
>0 this layer has enqueued the lock, but need to wait on resources
-ve failure
See also:
vvp_lock_enqueue(), lov_lock_enqueue(), lovsub_lock_enqueue(),
osc_lock_enqueue()
Referenced by cl_lock_enqueue().
void(* cl_lock_operations::clo_fini)(const struct lu_env *env, struct cl_lock_slice *slice)
Destructor.
Frees resources and the slice.
See also:
vvp_lock_fini(), lov_lock_fini(), lovsub_lock_fini(),
osc_lock_fini()
Referenced by cl_lock_fini().
int(* cl_lock_operations::clo_print)(const struct lu_env *env, void *cookie, lu_printer_t p, const struct cl_lock_slice *slice)
Optional debugging helper.
Prints given lock slice.
Referenced by cl_lock_print().
The documentation for this struct was generated from the following file:
lustre/include/cl_object.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.