Lustre: ptlrpc_sec_sops Struct Reference
ptlrpc_sec_sops Struct Reference
[sptlrpc]
server side policy operation vector.
#include <lustre_sec.h>
Data Fields
int(* accept)(struct ptlrpc_request *req)
verify an incoming request.
int(* authorize)(struct ptlrpc_request *req)
Perform security transformation upon reply message.
void(* invalidate_ctx)(struct ptlrpc_svc_ctx *ctx)
Invalidate server context ctx.
int(* alloc_rs)(struct ptlrpc_request *req, int msgsize)
Allocate a ptlrpc_reply_state.
void(* free_rs)(struct ptlrpc_reply_state *rs)
Free a ptlrpc_reply_state.
void(* free_ctx)(struct ptlrpc_svc_ctx *ctx)
Release the server context ctx.
int(* install_rctx)(struct obd_import *imp, struct ptlrpc_svc_ctx *ctx)
Install a reverse context based on the server context ctx.
int(* prep_bulk)(struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
Prepare buffer for incoming bulk write.
int(* unwrap_bulk)(struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
Unwrap the bulk write data.
int(* wrap_bulk)(struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
Wrap the bulk read data.
Detailed Description
server side policy operation vector.
Definition at line 721 of file lustre_sec.h.
Field Documentation
int(* ptlrpc_sec_sops::accept)(struct ptlrpc_request *req)
verify an incoming request.
Precondition:
request message is pointed by req->rq_reqbuf, size is req->rq_reqdata_len; and the message has been unpacked to host byte order.
Return values:
SECSVC_OK success, req->rq_reqmsg point to request message in clear text, size is req->rq_reqlen; req->rq_svc_ctx is set; req->rq_sp_from is decoded from request.
SECSVC_COMPLETE success, the request has been fully processed, and reply message has been prepared; req->rq_sp_from is decoded from request.
SECSVC_DROP failed, this request should be dropped.
See also:
null_accept(), plain_accept(), gss_svc_accept_kr().
Referenced by sptlrpc_svc_unwrap_request().
int(* ptlrpc_sec_sops::alloc_rs)(struct ptlrpc_request *req, int msgsize)
Allocate a ptlrpc_reply_state.
Parameters:
msgsize size of the reply message in clear text.
Precondition:
if req->rq_reply_state != NULL, then it's pre-allocated, we should simply use it; otherwise we'll responsible for allocating a new one.
Postcondition:
req->rq_reply_state != NULL;
req->rq_reply_state->rs_msg != NULL;
See also:
null_alloc_rs(), plain_alloc_rs(), gss_svc_alloc_rs().
Referenced by sptlrpc_svc_alloc_rs().
int(* ptlrpc_sec_sops::authorize)(struct ptlrpc_request *req)
Perform security transformation upon reply message.
Precondition:
reply message is pointed by req->rq_reply_state->rs_msg, size is req->rq_replen.
Postcondition:
req->rs_repdata_len is the final message size.
req->rq_reply_off is set.
See also:
null_authorize(), plain_authorize(), gss_svc_authorize().
Referenced by sptlrpc_svc_wrap_reply().
void(* ptlrpc_sec_sops::free_ctx)(struct ptlrpc_svc_ctx *ctx)
Release the server context ctx.
See also:
gss_svc_free_ctx().
Referenced by sptlrpc_svc_ctx_decref().
void(* ptlrpc_sec_sops::free_rs)(struct ptlrpc_reply_state *rs)
Free a ptlrpc_reply_state.
Referenced by sptlrpc_svc_free_rs().
int(* ptlrpc_sec_sops::install_rctx)(struct obd_import *imp, struct ptlrpc_svc_ctx *ctx)
Install a reverse context based on the server context ctx.
See also:
gss_svc_install_rctx_kr().
Referenced by sptlrpc_svc_install_rvs_ctx().
void(* ptlrpc_sec_sops::invalidate_ctx)(struct ptlrpc_svc_ctx *ctx)
Invalidate server context ctx.
See also:
gss_svc_invalidate_ctx().
Referenced by sptlrpc_svc_ctx_invalidate().
int(* ptlrpc_sec_sops::prep_bulk)(struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
Prepare buffer for incoming bulk write.
Precondition:
desc->bd_iov and desc->bd_iov_count describes the buffer intended to receive the write.
See also:
gss_svc_prep_bulk().
int(* ptlrpc_sec_sops::unwrap_bulk)(struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
Unwrap the bulk write data.
See also:
plain_svc_unwrap_bulk(), gss_svc_unwrap_bulk().
int(* ptlrpc_sec_sops::wrap_bulk)(struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
Wrap the bulk read data.
See also:
plain_svc_wrap_bulk(), gss_svc_wrap_bulk().
The documentation for this struct was generated from the following file:
lustre/include/lustre_sec.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.