Lustre: ptlrpc_sec_cops Struct Reference
ptlrpc_sec_cops Struct Reference
[sptlrpc]
client side policy operation vector.
#include <lustre_sec.h>
Data Fields
struct ptlrpc_sec *(* create_sec)(struct obd_import *imp, struct ptlrpc_svc_ctx *ctx, struct sptlrpc_flavor *flavor)
Given an imp, create and initialize a ptlrpc_sec structure.
void(* destroy_sec)(struct ptlrpc_sec *sec)
Destructor of ptlrpc_sec.
void(* kill_sec)(struct ptlrpc_sec *sec)
Notify that this ptlrpc_sec is going to die.
struct ptlrpc_cli_ctx *(* lookup_ctx)(struct ptlrpc_sec *sec, struct vfs_cred *vcred, int create, int remove_dead)
Given vcred, lookup and/or create its context.
void(* release_ctx)(struct ptlrpc_sec *sec, struct ptlrpc_cli_ctx *ctx, int sync)
Called then the reference of ctx dropped to 0.
int(* flush_ctx_cache)(struct ptlrpc_sec *sec, uid_t uid, int grace, int force)
Flush the context cache.
void(* gc_ctx)(struct ptlrpc_sec *sec)
Called periodically by garbage collector to remove dead contexts from cache.
int(* install_rctx)(struct obd_import *imp, struct ptlrpc_sec *sec, struct ptlrpc_cli_ctx *ctx)
Given an context ctx, install a corresponding reverse service context on client side.
int(* alloc_reqbuf)(struct ptlrpc_sec *sec, struct ptlrpc_request *req, int lustre_msg_size)
To allocate request buffer for req.
void(* free_reqbuf)(struct ptlrpc_sec *sec, struct ptlrpc_request *req)
To free request buffer for req.
int(* alloc_repbuf)(struct ptlrpc_sec *sec, struct ptlrpc_request *req, int lustre_msg_size)
To allocate reply buffer for req.
void(* free_repbuf)(struct ptlrpc_sec *sec, struct ptlrpc_request *req)
To free reply buffer for req.
int(* enlarge_reqbuf)(struct ptlrpc_sec *sec, struct ptlrpc_request *req, int segment, int newsize)
To expand the request buffer of req, thus the segment in the request message pointed by req->rq_reqmsg can accommodate at least newsize of data.
int(* display)(struct ptlrpc_sec *sec, struct seq_file *seq)
Detailed Description
client side policy operation vector.
Definition at line 551 of file lustre_sec.h.
Field Documentation
int(* ptlrpc_sec_cops::alloc_repbuf)(struct ptlrpc_sec *sec, struct ptlrpc_request *req, int lustre_msg_size)
To allocate reply buffer for req.
Precondition:
req->rq_repbuf == NULL.
Postcondition:
if success, req->rq_repbuf point to a buffer with size req->rq_repbuf_len, the size should be large enough to receive reply which be transformed from lustre_msg_size of clear text.
See also:
null_alloc_repbuf(), plain_alloc_repbuf(), gss_alloc_repbuf().
Referenced by sptlrpc_cli_alloc_repbuf().
int(* ptlrpc_sec_cops::alloc_reqbuf)(struct ptlrpc_sec *sec, struct ptlrpc_request *req, int lustre_msg_size)
To allocate request buffer for req.
Precondition:
req->rq_reqmsg == NULL.
req->rq_reqbuf == NULL, otherwise it must be pre-allocated, we are not supposed to free it.
Postcondition:
if success, req->rq_reqmsg point to a buffer with size at least lustre_msg_size.
See also:
null_alloc_reqbuf(), plain_alloc_reqbuf(), gss_alloc_reqbuf().
Referenced by sptlrpc_cli_alloc_reqbuf().
struct ptlrpc_sec*(* ptlrpc_sec_cops::create_sec)(struct obd_import *imp, struct ptlrpc_svc_ctx *ctx, struct sptlrpc_flavor *flavor) [read]
Given an imp, create and initialize a ptlrpc_sec structure.
Parameters:
ctx service context:
regular import: ctx should be NULL;
reverse import: ctx is obtained from incoming request.
flavor specify what flavor to use.
When necessary, policy module is responsible for taking reference on the import.
See also:
null_create_sec(), plain_create_sec(), gss_sec_create_kr().
Referenced by sptlrpc_sec_create().
void(* ptlrpc_sec_cops::destroy_sec)(struct ptlrpc_sec *sec)
Destructor of ptlrpc_sec.
When called, refcount has been dropped to 0 and all contexts has been destroyed.
See also:
null_destroy_sec(), plain_destroy_sec(), gss_sec_destroy_kr().
Referenced by sec_cop_destroy_sec().
int(* ptlrpc_sec_cops::display)(struct ptlrpc_sec *sec, struct seq_file *seq)
Referenced by sptlrpc_ctxs_lprocfs_seq_show().
int(* ptlrpc_sec_cops::enlarge_reqbuf)(struct ptlrpc_sec *sec, struct ptlrpc_request *req, int segment, int newsize)
To expand the request buffer of req, thus the segment in the request message pointed by req->rq_reqmsg can accommodate at least newsize of data.
Precondition:
req->rq_reqmsg->lm_buflens[segment] < newsize.
See also:
null_enlarge_reqbuf(), plain_enlarge_reqbuf(), gss_enlarge_reqbuf().
Referenced by sptlrpc_cli_enlarge_reqbuf().
int(* ptlrpc_sec_cops::flush_ctx_cache)(struct ptlrpc_sec *sec, uid_t uid, int grace, int force)
Flush the context cache.
Parameters:
uid context of which user, -1 means all contexts.
grace if zero, the PTLRPC_CTX_UPTODATE_BIT of affected contexts should be cleared immediately.
force if zero, only idle contexts will be flushed.
See also:
plain_flush_ctx_cache(), gss_sec_flush_ctx_cache_kr().
Referenced by sec_cop_flush_ctx_cache().
void(* ptlrpc_sec_cops::free_repbuf)(struct ptlrpc_sec *sec, struct ptlrpc_request *req)
To free reply buffer for req.
Precondition:
req->rq_repbuf != NULL.
Postcondition:
req->rq_repbuf == NULL.
req->rq_repbuf_len == 0.
See also:
null_free_repbuf(), plain_free_repbuf(), gss_free_repbuf().
Referenced by sptlrpc_cli_free_repbuf().
void(* ptlrpc_sec_cops::free_reqbuf)(struct ptlrpc_sec *sec, struct ptlrpc_request *req)
To free request buffer for req.
Precondition:
req->rq_reqbuf != NULL.
See also:
null_free_reqbuf(), plain_free_reqbuf(), gss_free_reqbuf().
Referenced by sptlrpc_cli_free_reqbuf().
void(* ptlrpc_sec_cops::gc_ctx)(struct ptlrpc_sec *sec)
Called periodically by garbage collector to remove dead contexts from cache.
See also:
gss_sec_gc_ctx_kr().
Referenced by sec_do_gc(), sptlrpc_gc_add_sec(), and sptlrpc_sec_create().
int(* ptlrpc_sec_cops::install_rctx)(struct obd_import *imp, struct ptlrpc_sec *sec, struct ptlrpc_cli_ctx *ctx)
Given an context ctx, install a corresponding reverse service context on client side.
XXX currently it's only used by GSS module, maybe we should remove this from general API.
Referenced by sptlrpc_cli_install_rvs_ctx().
void(* ptlrpc_sec_cops::kill_sec)(struct ptlrpc_sec *sec)
Notify that this ptlrpc_sec is going to die.
Optionally, policy module is supposed to set sec->ps_dying and whatever necessary actions.
See also:
plain_kill_sec(), gss_sec_kill().
Referenced by sptlrpc_sec_kill().
struct ptlrpc_cli_ctx*(* ptlrpc_sec_cops::lookup_ctx)(struct ptlrpc_sec *sec, struct vfs_cred *vcred, int create, int remove_dead) [read]
Given vcred, lookup and/or create its context.
The policy module is supposed to maintain its own context cache. XXX currently create and remove_dead is always 1, perhaps should be removed completely.
See also:
null_lookup_ctx(), plain_lookup_ctx(), gss_sec_lookup_ctx_kr().
Referenced by get_my_ctx().
void(* ptlrpc_sec_cops::release_ctx)(struct ptlrpc_sec *sec, struct ptlrpc_cli_ctx *ctx, int sync)
Called then the reference of ctx dropped to 0.
The policy module is supposed to destroy this context or whatever else according to its cache maintainance mechamism.
Parameters:
sync if zero, we shouldn't wait for the context being destroyed completely.
See also:
plain_release_ctx(), gss_sec_release_ctx_kr().
Referenced by sptlrpc_cli_ctx_put().
The documentation for this struct was generated from the following file:
lustre/include/lustre_sec.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.