Lustre: iam_leaf_operations Struct Reference
iam_leaf_operations Struct Reference
#include <osd_iam.h>
Data Fields
int(* init)(struct iam_leaf *p)
void(* init_new)(struct iam_container *c, struct buffer_head *bh)
void(* fini)(struct iam_leaf *l)
int(* at_end)(const struct iam_leaf *l)
void(* start)(struct iam_leaf *l)
void(* next)(struct iam_leaf *l)
struct iam_ikey *(* ikey)(const struct iam_leaf *l, struct iam_ikey *k)
struct iam_key *(* key)(const struct iam_leaf *l)
struct iam_rec *(* rec)(const struct iam_leaf *l)
void(* key_set)(struct iam_leaf *l, const struct iam_key *k)
void(* rec_set)(struct iam_leaf *l, const struct iam_rec *r)
void(* rec_get)(const struct iam_leaf *l, struct iam_rec *r)
int(* key_cmp)(const struct iam_leaf *l, const struct iam_key *k)
int(* key_eq)(const struct iam_leaf *l, const struct iam_key *k)
int(* rec_eq)(const struct iam_leaf *l, const struct iam_rec *r)
int(* key_size)(const struct iam_leaf *l)
int(* lookup)(struct iam_leaf *l, const struct iam_key *k)
int(* ilookup)(struct iam_leaf *l, const struct iam_ikey *ik)
int(* can_add)(const struct iam_leaf *l, const struct iam_key *k, const struct iam_rec *r)
void(* rec_add)(struct iam_leaf *l, const struct iam_key *k, const struct iam_rec *r)
void(* rec_del)(struct iam_leaf *l, int shift)
void(* split)(struct iam_leaf *l, struct buffer_head **bh, iam_ptr_t newblknr)
int(* leaf_empty)(struct iam_leaf *l)
Detailed Description
Definition at line 331 of file osd_iam.h.
Field Documentation
int(* iam_leaf_operations::at_end)(const struct iam_leaf *l)
Referenced by iam_leaf_at_end().
int(* iam_leaf_operations::can_add)(const struct iam_leaf *l, const struct iam_key *k, const struct iam_rec *r)
Referenced by iam_leaf_can_add().
void(* iam_leaf_operations::fini)(struct iam_leaf *l)
Referenced by iam_leaf_fini().
struct iam_ikey*(* iam_leaf_operations::ikey)(const struct iam_leaf *l, struct iam_ikey *k) [read]
Referenced by iam_leaf_ikey().
int(* iam_leaf_operations::ilookup)(struct iam_leaf *l, const struct iam_ikey *ik)
int(* iam_leaf_operations::init)(struct iam_leaf *p)
Referenced by iam_leaf_load().
void(* iam_leaf_operations::init_new)(struct iam_container *c, struct buffer_head *bh)
Referenced by iam_new_leaf().
struct iam_key*(* iam_leaf_operations::key)(const struct iam_leaf *l) [read]
Referenced by iam_leaf_key().
int(* iam_leaf_operations::key_cmp)(const struct iam_leaf *l, const struct iam_key *k)
Referenced by iam_leaf_keycmp().
int(* iam_leaf_operations::key_eq)(const struct iam_leaf *l, const struct iam_key *k)
Referenced by iam_leaf_keyeq().
void(* iam_leaf_operations::key_set)(struct iam_leaf *l, const struct iam_key *k)
int(* iam_leaf_operations::key_size)(const struct iam_leaf *l)
Referenced by iam_leaf_key_size().
int(* iam_leaf_operations::leaf_empty)(struct iam_leaf *l)
Referenced by iam_leaf_empty().
int(* iam_leaf_operations::lookup)(struct iam_leaf *l, const struct iam_key *k)
void(* iam_leaf_operations::next)(struct iam_leaf *l)
Referenced by iam_leaf_next().
struct iam_rec*(* iam_leaf_operations::rec)(const struct iam_leaf *l) [read]
Referenced by iam_leaf_rec().
void(* iam_leaf_operations::rec_add)(struct iam_leaf *l, const struct iam_key *k, const struct iam_rec *r)
Referenced by iam_leaf_rec_add().
void(* iam_leaf_operations::rec_del)(struct iam_leaf *l, int shift)
Referenced by iam_rec_del().
int(* iam_leaf_operations::rec_eq)(const struct iam_leaf *l, const struct iam_rec *r)
Referenced by iam_update().
void(* iam_leaf_operations::rec_get)(const struct iam_leaf *l, struct iam_rec *r)
Referenced by iam_reccpy().
void(* iam_leaf_operations::rec_set)(struct iam_leaf *l, const struct iam_rec *r)
Referenced by iam_it_reccpy().
void(* iam_leaf_operations::split)(struct iam_leaf *l, struct buffer_head **bh, iam_ptr_t newblknr)
Referenced by iam_leaf_split().
void(* iam_leaf_operations::start)(struct iam_leaf *l)
Referenced by iam_leaf_start().
The documentation for this struct was generated from the following file:
lustre/osd-ldiskfs/osd_iam.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.