Lustre: module_backfs_ops Struct Reference
module_backfs_ops Struct Reference
#include <mount_utils.h>
Data Fields
int(* init)(void)
void(* fini)(void)
int(* read_ldd)(char *ds, struct lustre_disk_data *ldd)
int(* write_ldd)(struct mkfs_opts *mop)
int(* is_lustre)(char *dev, enum ldd_mount_type *mount_type)
int(* make_lustre)(struct mkfs_opts *mop)
int(* prepare_lustre)(struct mkfs_opts *mop, char *wanted_mountopts, size_t len)
int(* fix_mountopts)(struct mkfs_opts *mop, char *mountopts, size_t len)
int(* tune_lustre)(char *dev, struct mount_opts *mop)
int(* label_lustre)(struct mount_opts *mop)
int(* enable_quota)(struct mkfs_opts *mop)
void * dl_handle
Detailed Description
Definition at line 159 of file mount_utils.h.
Field Documentation
void* module_backfs_ops::dl_handle
Definition at line 173 of file mount_utils.h.
Referenced by load_backfs_module(), and unload_backfs_module().
int(* module_backfs_ops::enable_quota)(struct mkfs_opts *mop)
Referenced by load_backfs_module(), and osd_enable_quota().
void(* module_backfs_ops::fini)(void)
Referenced by load_backfs_module(), osd_fini(), and osd_init().
int(* module_backfs_ops::fix_mountopts)(struct mkfs_opts *mop, char *mountopts, size_t len)
Referenced by load_backfs_module(), and osd_fix_mountopts().
int(* module_backfs_ops::init)(void)
Referenced by load_backfs_module(), and osd_init().
int(* module_backfs_ops::is_lustre)(char *dev, enum ldd_mount_type *mount_type)
Referenced by load_backfs_module().
int(* module_backfs_ops::label_lustre)(struct mount_opts *mop)
Referenced by load_backfs_module(), and osd_label_lustre().
int(* module_backfs_ops::make_lustre)(struct mkfs_opts *mop)
Referenced by load_backfs_module(), and osd_make_lustre().
int(* module_backfs_ops::prepare_lustre)(struct mkfs_opts *mop, char *wanted_mountopts, size_t len)
Referenced by load_backfs_module(), and osd_prepare_lustre().
int(* module_backfs_ops::read_ldd)(char *ds, struct lustre_disk_data *ldd)
Referenced by load_backfs_module(), and osd_read_ldd().
int(* module_backfs_ops::tune_lustre)(char *dev, struct mount_opts *mop)
Referenced by load_backfs_module(), and osd_tune_lustre().
int(* module_backfs_ops::write_ldd)(struct mkfs_opts *mop)
Referenced by load_backfs_module(), and osd_write_ldd().
The documentation for this struct was generated from the following file:
lustre/utils/mount_utils.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.