Lustre: cfs_hash_hlist_ops Struct Reference
cfs_hash_hlist_ops Struct Reference
#include <libcfs_hash.h>
Data Fields
struct hlist_head *(* hop_hhead)(struct cfs_hash *hs, struct cfs_hash_bd *bd)
return hlist_head of hash-head of
int(* hop_hhead_size)(struct cfs_hash *hs)
return hash-head size
int(* hop_hnode_add)(struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode)
add to hash-head of
int(* hop_hnode_del)(struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode)
remove from hash-head of
Detailed Description
Definition at line 282 of file libcfs_hash.h.
Field Documentation
struct hlist_head*(* cfs_hash_hlist_ops::hop_hhead)(struct cfs_hash *hs, struct cfs_hash_bd *bd) [read]
return hlist_head of hash-head of
Referenced by cfs_hash_bd_hhead().
int(* cfs_hash_hlist_ops::hop_hhead_size)(struct cfs_hash *hs)
return hash-head size
Referenced by cfs_hash_bkt_size().
int(* cfs_hash_hlist_ops::hop_hnode_add)(struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode)
add to hash-head of
Referenced by cfs_hash_bd_add_locked(), and cfs_hash_bd_move_locked().
int(* cfs_hash_hlist_ops::hop_hnode_del)(struct cfs_hash *hs, struct cfs_hash_bd *bd, struct hlist_node *hnode)
remove from hash-head of
Referenced by cfs_hash_bd_del_locked(), and cfs_hash_bd_move_locked().
The documentation for this struct was generated from the following file:
libcfs/include/libcfs/libcfs_hash.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.