Lustre: lnet_lnd Struct Reference
lnet_lnd Struct Reference
#include <lib-types.h>
Data Fields
struct list_head lnd_list
int lnd_refcount
__u32 lnd_type
int(* lnd_startup)(struct lnet_ni *ni)
void(* lnd_shutdown)(struct lnet_ni *ni)
int(* lnd_ctl)(struct lnet_ni *ni, unsigned int cmd, void *arg)
int(* lnd_send)(struct lnet_ni *ni, void *private, lnet_msg_t *msg)
int(* lnd_recv)(struct lnet_ni *ni, void *private, lnet_msg_t *msg, int delayed, unsigned int niov, struct kvec *iov, lnet_kiov_t *kiov, unsigned int offset, unsigned int mlen, unsigned int rlen)
int(* lnd_eager_recv)(struct lnet_ni *ni, void *private, lnet_msg_t *msg, void **new_privatep)
void(* lnd_notify)(struct lnet_ni *ni, lnet_nid_t peer, int alive)
void(* lnd_query)(struct lnet_ni *ni, lnet_nid_t peer, cfs_time_t *when)
int(* lnd_accept)(struct lnet_ni *ni, struct socket *sock)
Detailed Description
Definition at line 197 of file lib-types.h.
Field Documentation
int(* lnet_lnd::lnd_accept)(struct lnet_ni *ni, struct socket *sock)
Referenced by ksocklnd_init(), lnet_accept(), lnet_count_acceptor_nis(), and lnet_dyn_add_ni().
int(* lnet_lnd::lnd_ctl)(struct lnet_ni *ni, unsigned int cmd, void *arg)
Referenced by ksocklnd_init(), and LNetCtl().
int(* lnet_lnd::lnd_eager_recv)(struct lnet_ni *ni, void *private, lnet_msg_t *msg, void **new_privatep)
Referenced by lnet_ni_eager_recv(), lnet_parse_forward_locked(), and lnet_parse_put().
struct list_head lnet_lnd::lnd_list [read]
Definition at line 200 of file lib-types.h.
Referenced by lnet_register_lnd(), and lnet_unregister_lnd().
void(* lnet_lnd::lnd_notify)(struct lnet_ni *ni, lnet_nid_t peer, int alive)
Referenced by ksocklnd_init(), lnet_add_route(), and lnet_ni_notify_locked().
void(* lnet_lnd::lnd_query)(struct lnet_ni *ni, lnet_nid_t peer, cfs_time_t *when)
Referenced by ksocklnd_init(), lnet_ni_query_locked(), and lnet_startup_lndni().
int(* lnet_lnd::lnd_recv)(struct lnet_ni *ni, void *private, lnet_msg_t *msg, int delayed, unsigned int niov, struct kvec *iov, lnet_kiov_t *kiov, unsigned int offset, unsigned int mlen, unsigned int rlen)
Referenced by ksocklnd_init(), and lnet_ni_recv().
int lnet_lnd::lnd_refcount
Definition at line 201 of file lib-types.h.
Referenced by lnet_clear_zombies_nis_locked(), lnet_register_lnd(), lnet_startup_lndni(), and lnet_unregister_lnd().
int(* lnet_lnd::lnd_send)(struct lnet_ni *ni, void *private, lnet_msg_t *msg)
Referenced by ksocklnd_init(), and lnet_ni_send().
void(* lnet_lnd::lnd_shutdown)(struct lnet_ni *ni)
Referenced by ksocklnd_init(), and lnet_clear_zombies_nis_locked().
int(* lnet_lnd::lnd_startup)(struct lnet_ni *ni)
Referenced by ksocklnd_init(), and lnet_startup_lndni().
__u32 lnet_lnd::lnd_type
Definition at line 204 of file lib-types.h.
Referenced by ksocklnd_init(), lnet_clear_zombies_nis_locked(), lnet_find_lnd_by_type(), lnet_register_lnd(), lnet_startup_lndni(), lnet_unregister_lnd(), lnet_update_ni_status_locked(), and proc_lnet_nis().
The documentation for this struct was generated from the following file:
lnet/include/lnet/lib-types.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.