Lustre: lquota_entry_operations Struct Reference
lquota_entry_operations Struct Reference
#include <lquota_internal.h>
Data Fields
void(* lqe_init)(struct lquota_entry *, void *arg)
int(* lqe_read)(const struct lu_env *, struct lquota_entry *, void *arg)
void(* lqe_debug)(struct lquota_entry *, void *, struct libcfs_debug_msg_data *, const char *, va_list)
Detailed Description
Definition at line 58 of file lquota_internal.h.
Field Documentation
void(* lquota_entry_operations::lqe_debug)(struct lquota_entry *, void *, struct libcfs_debug_msg_data *, const char *, va_list)
Referenced by lquota_lqe_debug0().
void(* lquota_entry_operations::lqe_init)(struct lquota_entry *, void *arg)
Referenced by lqe_init().
int(* lquota_entry_operations::lqe_read)(const struct lu_env *, struct lquota_entry *, void *arg)
Referenced by lqe_read().
The documentation for this struct was generated from the following file:
lustre/quota/lquota_internal.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.