Lustre: lfsck_assistant_operations Struct Reference
lfsck_assistant_operations Struct Reference
#include <lfsck_internal.h>
Data Fields
int(* la_handler_p1)(const struct lu_env *env, struct lfsck_component *com, struct lfsck_assistant_req *lar)
int(* la_handler_p2)(const struct lu_env *env, struct lfsck_component *com)
void(* la_fill_pos)(const struct lu_env *env, struct lfsck_component *com, struct lfsck_position *pos)
int(* la_double_scan_result)(const struct lu_env *env, struct lfsck_component *com, int rc)
void(* la_req_fini)(const struct lu_env *env, struct lfsck_assistant_req *lar)
void(* la_sync_failures)(const struct lu_env *env, struct lfsck_component *com, struct lfsck_request *lr)
Detailed Description
Definition at line 779 of file lfsck_internal.h.
Field Documentation
int(* lfsck_assistant_operations::la_double_scan_result)(const struct lu_env *env, struct lfsck_component *com, int rc)
Referenced by lfsck_assistant_engine().
void(* lfsck_assistant_operations::la_fill_pos)(const struct lu_env *env, struct lfsck_component *com, struct lfsck_position *pos)
Referenced by lfsck_assistant_engine().
int(* lfsck_assistant_operations::la_handler_p1)(const struct lu_env *env, struct lfsck_component *com, struct lfsck_assistant_req *lar)
Referenced by lfsck_assistant_engine().
int(* lfsck_assistant_operations::la_handler_p2)(const struct lu_env *env, struct lfsck_component *com)
Referenced by lfsck_assistant_engine().
void(* lfsck_assistant_operations::la_req_fini)(const struct lu_env *env, struct lfsck_assistant_req *lar)
Referenced by lfsck_assistant_engine().
void(* lfsck_assistant_operations::la_sync_failures)(const struct lu_env *env, struct lfsck_component *com, struct lfsck_request *lr)
Referenced by lfsck_assistant_notify_others().
The documentation for this struct was generated from the following file:
lustre/lfsck/lfsck_internal.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.