Lustre: lu_device_type_operations Struct Reference
lu_device_type_operations Struct Reference
[lu]
Operations on a device type.
#include <lu_object.h>
Data Fields
struct lu_device *(* ldto_device_alloc)(const struct lu_env *env, struct lu_device_type *t, struct lustre_cfg *lcfg)
Allocate new device.
struct lu_device *(* ldto_device_free)(const struct lu_env *, struct lu_device *)
Free device.
int(* ldto_device_init)(const struct lu_env *env, struct lu_device *, const char *, struct lu_device *)
Initialize the devices after allocation.
struct lu_device *(* ldto_device_fini)(const struct lu_env *env, struct lu_device *)
Finalize device.
int(* ldto_init)(struct lu_device_type *t)
Initialize device type.
void(* ldto_fini)(struct lu_device_type *t)
Finalize device type.
void(* ldto_start)(struct lu_device_type *t)
Called when the first device is created.
void(* ldto_stop)(struct lu_device_type *t)
Called when number of devices drops to 0.
Detailed Description
Operations on a device type.
Definition at line 352 of file lu_object.h.
Field Documentation
struct lu_device*(* lu_device_type_operations::ldto_device_alloc)(const struct lu_env *env, struct lu_device_type *t, struct lustre_cfg *lcfg) [read]
Allocate new device.
Referenced by cl_type_setup().
struct lu_device*(* lu_device_type_operations::ldto_device_fini)(const struct lu_env *env, struct lu_device *) [read]
Finalize device.
Dual to lu_device_type_operations::ldto_device_init(). Returns pointer to the next device in the stack.
Referenced by echo_device_fini(), and lu_stack_fini().
struct lu_device*(* lu_device_type_operations::ldto_device_free)(const struct lu_env *, struct lu_device *) [read]
Free device.
Dual to lu_device_type_operations::ldto_device_alloc(). Returns pointer to the next device in the stack.
Referenced by cl_type_setup(), echo_device_free(), and lu_stack_fini().
int(* lu_device_type_operations::ldto_device_init)(const struct lu_env *env, struct lu_device *, const char *, struct lu_device *)
Initialize the devices after allocation.
Referenced by cl_type_setup(), echo_device_alloc(), lovsub_device_init(), and vvp_device_init().
void(* lu_device_type_operations::ldto_fini)(struct lu_device_type *t)
Finalize device type.
Dual to lu_device_type_operations::ldto_init(). Called on module unload.
Referenced by lu_device_type_fini().
int(* lu_device_type_operations::ldto_init)(struct lu_device_type *t)
Initialize device type.
This is called on module load.
Referenced by lu_device_type_init().
void(* lu_device_type_operations::ldto_start)(struct lu_device_type *t)
Called when the first device is created.
Referenced by lu_device_init().
void(* lu_device_type_operations::ldto_stop)(struct lu_device_type *t)
Called when number of devices drops to 0.
Referenced by lu_device_fini().
The documentation for this struct was generated from the following file:
lustre/include/lu_object.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.