Lustre: lfsck_operations Struct Reference
lfsck_operations Struct Reference
#include <lfsck_internal.h>
Data Fields
int(* lfsck_reset)(const struct lu_env *env, struct lfsck_component *com, bool init)
void(* lfsck_fail)(const struct lu_env *env, struct lfsck_component *com, bool new_checked)
void(* lfsck_close_dir)(const struct lu_env *env, struct lfsck_component *com)
int(* lfsck_open_dir)(const struct lu_env *env, struct lfsck_component *com)
int(* lfsck_checkpoint)(const struct lu_env *env, struct lfsck_component *com, bool init)
int(* lfsck_prep)(const struct lu_env *env, struct lfsck_component *com, struct lfsck_start_param *lsp)
int(* lfsck_exec_oit)(const struct lu_env *env, struct lfsck_component *com, struct dt_object *obj)
int(* lfsck_exec_dir)(const struct lu_env *env, struct lfsck_component *com, struct lfsck_assistant_object *lso, struct lu_dirent *ent, __u16 type)
int(* lfsck_post)(const struct lu_env *env, struct lfsck_component *com, int result, bool init)
void(* lfsck_dump)(const struct lu_env *env, struct lfsck_component *com, struct seq_file *m)
int(* lfsck_double_scan)(const struct lu_env *env, struct lfsck_component *com)
void(* lfsck_data_release)(const struct lu_env *env, struct lfsck_component *com)
void(* lfsck_quit)(const struct lu_env *env, struct lfsck_component *com)
int(* lfsck_in_notify)(const struct lu_env *env, struct lfsck_component *com, struct lfsck_request *lr, struct thandle *th)
int(* lfsck_query)(const struct lu_env *env, struct lfsck_component *com, struct lfsck_request *req, struct lfsck_reply *rep, struct lfsck_query *que, int idx)
int(* lfsck_join)(const struct lu_env *env, struct lfsck_component *com, struct lfsck_start_param *lsp)
Detailed Description
Definition at line 376 of file lfsck_internal.h.
Field Documentation
int(* lfsck_operations::lfsck_checkpoint)(const struct lu_env *env, struct lfsck_component *com, bool init)
Referenced by lfsck_checkpoint(), and lfsck_prep().
void(* lfsck_operations::lfsck_close_dir)(const struct lu_env *env, struct lfsck_component *com)
Referenced by lfsck_close_dir().
void(* lfsck_operations::lfsck_data_release)(const struct lu_env *env, struct lfsck_component *com)
Referenced by lfsck_component_put().
int(* lfsck_operations::lfsck_double_scan)(const struct lu_env *env, struct lfsck_component *com)
Referenced by lfsck_double_scan().
void(* lfsck_operations::lfsck_dump)(const struct lu_env *env, struct lfsck_component *com, struct seq_file *m)
Referenced by lfsck_dump().
int(* lfsck_operations::lfsck_exec_dir)(const struct lu_env *env, struct lfsck_component *com, struct lfsck_assistant_object *lso, struct lu_dirent *ent, __u16 type)
Referenced by lfsck_exec_dir().
int(* lfsck_operations::lfsck_exec_oit)(const struct lu_env *env, struct lfsck_component *com, struct dt_object *obj)
Referenced by lfsck_exec_oit().
void(* lfsck_operations::lfsck_fail)(const struct lu_env *env, struct lfsck_component *com, bool new_checked)
Referenced by lfsck_fail().
int(* lfsck_operations::lfsck_in_notify)(const struct lu_env *env, struct lfsck_component *com, struct lfsck_request *lr, struct thandle *th)
Referenced by lfsck_in_notify().
int(* lfsck_operations::lfsck_join)(const struct lu_env *env, struct lfsck_component *com, struct lfsck_start_param *lsp)
Referenced by lfsck_start().
int(* lfsck_operations::lfsck_open_dir)(const struct lu_env *env, struct lfsck_component *com)
Referenced by lfsck_open_dir().
int(* lfsck_operations::lfsck_post)(const struct lu_env *env, struct lfsck_component *com, int result, bool init)
Referenced by lfsck_post(), lfsck_prep(), and lfsck_start().
int(* lfsck_operations::lfsck_prep)(const struct lu_env *env, struct lfsck_component *com, struct lfsck_start_param *lsp)
Referenced by lfsck_prep().
int(* lfsck_operations::lfsck_query)(const struct lu_env *env, struct lfsck_component *com, struct lfsck_request *req, struct lfsck_reply *rep, struct lfsck_query *que, int idx)
Referenced by lfsck_query().
void(* lfsck_operations::lfsck_quit)(const struct lu_env *env, struct lfsck_component *com)
Referenced by lfsck_quit().
int(* lfsck_operations::lfsck_reset)(const struct lu_env *env, struct lfsck_component *com, bool init)
Referenced by lfsck_start().
The documentation for this struct was generated from the following file:
lustre/lfsck/lfsck_internal.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.