Lustre: netstrfns Struct Reference
netstrfns Struct Reference
#include <nidstr.h>
Data Fields
__u32 nf_type
char * nf_name
char * nf_modname
void(* nf_addr2str)(__u32 addr, char *str, size_t size)
int(* nf_str2addr)(const char *str, int nob, __u32 *addr)
int(* nf_parse_addrlist)(char *str, int len, struct list_head *list)
int(* nf_print_addrlist)(char *buffer, int count, struct list_head *list)
int(* nf_match_addr)(__u32 addr, struct list_head *list)
bool(* nf_is_contiguous)(struct list_head *nidlist)
void(* nf_min_max)(struct list_head *nidlist, __u32 *min_nid, __u32 *max_nid)
Detailed Description
Definition at line 97 of file nidstr.h.
Field Documentation
void(* netstrfns::nf_addr2str)(__u32 addr, char *str, size_t size)
Referenced by cfs_nidrange_find_min_max(), and libcfs_nid2str_r().
bool(* netstrfns::nf_is_contiguous)(struct list_head *nidlist)
Referenced by cfs_nidrange_is_contiguous().
int(* netstrfns::nf_match_addr)(__u32 addr, struct list_head *list)
Referenced by cfs_match_nid().
void(* netstrfns::nf_min_max)(struct list_head *nidlist, __u32 *min_nid, __u32 *max_nid)
Referenced by cfs_nidrange_find_min_max().
char* netstrfns::nf_modname
Definition at line 100 of file nidstr.h.
Referenced by libcfs_lnd2modname().
char* netstrfns::nf_name
Definition at line 99 of file nidstr.h.
Referenced by add_nidrange(), cfs_nidrange_find_min_max(), cfs_nidrange_is_contiguous(), cfs_print_network(), libcfs_lnd2str_r(), libcfs_name2netstrfns(), libcfs_namenum2netstrfns(), libcfs_net2str_r(), libcfs_nid2str_r(), and libcfs_str2net_internal().
int(* netstrfns::nf_parse_addrlist)(char *str, int len, struct list_head *list)
Referenced by parse_addrange().
int(* netstrfns::nf_print_addrlist)(char *buffer, int count, struct list_head *list)
Referenced by cfs_print_addrranges().
int(* netstrfns::nf_str2addr)(const char *str, int nob, __u32 *addr)
Referenced by libcfs_str2nid().
__u32 netstrfns::nf_type
Definition at line 98 of file nidstr.h.
Referenced by cfs_match_nid(), libcfs_lnd2netstrfns(), libcfs_str2lnd(), and libcfs_str2net_internal().
The documentation for this struct was generated from the following file:
lnet/include/lnet/nidstr.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.