Lustre: lu_device_operations Struct Reference
lu_device_operations Struct Reference
[lu]
Operations common for data and meta-data devices.
#include <lu_object.h>
Data Fields
struct lu_object *(* ldo_object_alloc)(const struct lu_env *env, const struct lu_object_header *h, struct lu_device *d)
Allocate object for the given device (without lower-layer parts).
int(* ldo_process_config)(const struct lu_env *env, struct lu_device *, struct lustre_cfg *)
process config specific for device.
int(* ldo_recovery_complete)(const struct lu_env *, struct lu_device *)
int(* ldo_prepare)(const struct lu_env *, struct lu_device *parent, struct lu_device *dev)
initialize local objects for device.
Detailed Description
Operations common for data and meta-data devices.
Definition at line 109 of file lu_object.h.
Field Documentation
struct lu_object*(* lu_device_operations::ldo_object_alloc)(const struct lu_env *env, const struct lu_object_header *h, struct lu_device *d) [read]
Allocate object for the given device (without lower-layer parts).
This is called by lu_object_operations::loo_object_init() from the parent layer, and should setup at least lu_object::lo_dev and lu_object::lo_ops fields of resulting lu_object.
Object creation protocol.
Due to design goal of avoiding recursion, object creation (see lu_object_alloc()) is somewhat involved:
first, lu_device_operations::ldo_object_alloc() method of the top-level device in the stack is called. It should allocate top level object (including lu_object_header), but without any lower-layer sub-object(s).
then lu_object_alloc() sets fid in the header of newly created object.
then lu_object_operations::loo_object_init() is called. It has to allocate lower-layer object(s). To do this, lu_object_operations::loo_object_init() calls ldo_object_alloc() of the lower-layer device(s).
for all new objects allocated by lu_object_operations::loo_object_init() (and inserted into object stack), lu_object_operations::loo_object_init() is called again repeatedly, until no new objects are created.
Postcondition:
ergo(!IS_ERR(result), result->lo_dev == d && result->lo_ops != NULL);
Referenced by echo_object_init(), lod_object_init(), lovsub_object_init(), ls_object_init(), lu_object_alloc(), mdd_object_init(), mdt_object_init(), mgs_object_init(), ofd_object_init(), and vvp_object_init().
int(* lu_device_operations::ldo_prepare)(const struct lu_env *, struct lu_device *parent, struct lu_device *dev)
initialize local objects for device.
this method called after layer has been initialized (after LCFG_SETUP stage) and before it starts serving user requests.
Referenced by lod_prepare(), mdd_prepare(), mdt_prepare(), mdt_quota_init(), ofd_prepare(), and server_start_targets().
int(* lu_device_operations::ldo_process_config)(const struct lu_env *env, struct lu_device *, struct lustre_cfg *)
process config specific for device.
Referenced by lod_add_device(), lod_process_config(), lod_sub_process_config(), lustre_disconnect_lwp(), mdd_process_config(), mdt_process_config(), mdt_stack_fini(), mdt_stack_pre_fini(), ofd_process_config(), and ofd_stack_fini().
int(* lu_device_operations::ldo_recovery_complete)(const struct lu_env *, struct lu_device *)
Referenced by lod_add_device(), lod_recovery_complete(), mdd_recovery_complete(), mdt_postrecov(), ofd_postrecov(), and ofd_recovery_complete().
The documentation for this struct was generated from the following file:
lustre/include/lu_object.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.