Lustre: ptlrpc_service_ops Struct Reference
ptlrpc_service_ops Struct Reference
[net]
#include <lustre_net.h>
Data Fields
int(* so_thr_init)(struct ptlrpc_thread *thr)
if non-NULL called during thread creation (ptlrpc_start_thread()) to initialize service specific per-thread state.
void(* so_thr_done)(struct ptlrpc_thread *thr)
if non-NULL called during thread shutdown (ptlrpc_main()) to destruct state created by ->srv_init().
int(* so_req_handler)(struct ptlrpc_request *req)
Handler function for incoming requests for this service.
int(* so_hpreq_handler)(struct ptlrpc_request *)
function to determine priority of the request, it's called on every new request
void(* so_req_printer)(void *, struct ptlrpc_request *)
service-specific print fn
Detailed Description
Definition at line 1626 of file lustre_net.h.
Field Documentation
int(* ptlrpc_service_ops::so_hpreq_handler)(struct ptlrpc_request *)
function to determine priority of the request, it's called on every new request
Referenced by ptlrpc_server_nthreads_check().
int(* ptlrpc_service_ops::so_req_handler)(struct ptlrpc_request *req)
Handler function for incoming requests for this service.
Referenced by ptlrpc_server_handle_request().
void(* ptlrpc_service_ops::so_req_printer)(void *, struct ptlrpc_request *)
service-specific print fn
void(* ptlrpc_service_ops::so_thr_done)(struct ptlrpc_thread *thr)
if non-NULL called during thread shutdown (ptlrpc_main()) to destruct state created by ->srv_init().
Referenced by ptlrpc_main().
int(* ptlrpc_service_ops::so_thr_init)(struct ptlrpc_thread *thr)
if non-NULL called during thread creation (ptlrpc_start_thread()) to initialize service specific per-thread state.
Referenced by ptlrpc_main().
The documentation for this struct was generated from the following file:
lustre/include/lustre_net.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.