Lustre: ldlm_valblock_ops Struct Reference
ldlm_valblock_ops Struct Reference
[Lustre Distributed Lock Manager]
LVB operations.
#include <lustre_dlm.h>
Data Fields
int(* lvbo_init)(struct ldlm_resource *res)
int(* lvbo_update)(struct ldlm_resource *res, struct ptlrpc_request *r, int increase)
int(* lvbo_free)(struct ldlm_resource *res)
int(* lvbo_size)(struct ldlm_lock *lock)
int(* lvbo_fill)(struct ldlm_lock *lock, void *buf, int buflen)
Detailed Description
LVB operations.
LVB is Lock Value Block. This is a special opaque (to LDLM) value that could be associated with an LDLM lock and transferred from client to server and back.
Currently LVBs are used by:
OSC-OST code to maintain current object size/times
layout lock code to return the layout when the layout lock is granted
To ensure delayed LVB initialization, it is highly recommended to use the set of ldlm_[res_]lvbo_[init,update,fill]() functions.
Definition at line 288 of file lustre_dlm.h.
Field Documentation
int(* ldlm_valblock_ops::lvbo_fill)(struct ldlm_lock *lock, void *buf, int buflen)
Referenced by ldlm_lvbo_fill().
int(* ldlm_valblock_ops::lvbo_free)(struct ldlm_resource *res)
Referenced by ldlm_resource_putref().
int(* ldlm_valblock_ops::lvbo_init)(struct ldlm_resource *res)
Referenced by ldlm_lvbo_init().
int(* ldlm_valblock_ops::lvbo_size)(struct ldlm_lock *lock)
Referenced by ldlm_lvbo_size().
int(* ldlm_valblock_ops::lvbo_update)(struct ldlm_resource *res, struct ptlrpc_request *r, int increase)
Referenced by ldlm_res_lvbo_update(), and ofd_commitrw().
The documentation for this struct was generated from the following file:
lustre/include/lustre_dlm.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.