Lustre: lsm_operations Struct Reference
lsm_operations Struct Reference
#include <lov_internal.h>
Data Fields
void(* lsm_free)(struct lov_stripe_md *)
void(* lsm_stripe_by_index)(struct lov_stripe_md *, int *, loff_t *, loff_t *)
void(* lsm_stripe_by_offset)(struct lov_stripe_md *, int *, loff_t *, loff_t *)
int(* lsm_lmm_verify)(struct lov_mds_md *lmm, int lmm_bytes, u16 *stripe_count)
int(* lsm_unpackmd)(struct lov_obd *lov, struct lov_stripe_md *lsm, struct lov_mds_md *lmm)
Detailed Description
Definition at line 82 of file lov_internal.h.
Field Documentation
void(* lsm_operations::lsm_free)(struct lov_stripe_md *)
Referenced by lov_free_memmd().
int(* lsm_operations::lsm_lmm_verify)(struct lov_mds_md *lmm, int lmm_bytes, u16 *stripe_count)
Referenced by lov_verify_lmm().
void(* lsm_operations::lsm_stripe_by_index)(struct lov_stripe_md *, int *, loff_t *, loff_t *)
Referenced by lov_size_to_stripe(), lov_stripe_offset(), and lov_stripe_size().
void(* lsm_operations::lsm_stripe_by_offset)(struct lov_stripe_md *, int *, loff_t *, loff_t *)
Referenced by lov_stripe_number().
int(* lsm_operations::lsm_unpackmd)(struct lov_obd *lov, struct lov_stripe_md *lsm, struct lov_mds_md *lmm)
Referenced by lov_unpackmd().
The documentation for this struct was generated from the following file:
lustre/lov/lov_internal.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.