Lustre: qmt_handlers Struct Reference
qmt_handlers Struct Reference
#include <lustre_quota.h>
Data Fields
int(* qmth_quotactl)(const struct lu_env *, struct lu_device *, struct obd_quotactl *)
int(* qmth_dqacq)(const struct lu_env *, struct lu_device *, struct ptlrpc_request *)
int(* qmth_intent_policy)(const struct lu_env *, struct lu_device *, struct ptlrpc_request *, struct ldlm_lock **, int)
int(* qmth_lvbo_init)(struct lu_device *, struct ldlm_resource *)
int(* qmth_lvbo_update)(struct lu_device *, struct ldlm_resource *, struct ptlrpc_request *, int)
int(* qmth_lvbo_size)(struct lu_device *, struct ldlm_lock *)
int(* qmth_lvbo_fill)(struct lu_device *, struct ldlm_lock *, void *, int)
int(* qmth_lvbo_free)(struct lu_device *, struct ldlm_resource *)
Detailed Description
Definition at line 84 of file lustre_quota.h.
Field Documentation
int(* qmt_handlers::qmth_dqacq)(const struct lu_env *, struct lu_device *, struct ptlrpc_request *)
Referenced by mdt_quota_dqacq().
int(* qmt_handlers::qmth_intent_policy)(const struct lu_env *, struct lu_device *, struct ptlrpc_request *, struct ldlm_lock **, int)
Referenced by mdt_intent_opc().
int(* qmt_handlers::qmth_lvbo_fill)(struct lu_device *, struct ldlm_lock *, void *, int)
Referenced by mdt_lvbo_fill().
int(* qmt_handlers::qmth_lvbo_free)(struct lu_device *, struct ldlm_resource *)
Referenced by mdt_lvbo_free().
int(* qmt_handlers::qmth_lvbo_init)(struct lu_device *, struct ldlm_resource *)
Referenced by mdt_lvbo_init().
int(* qmt_handlers::qmth_lvbo_size)(struct lu_device *, struct ldlm_lock *)
Referenced by mdt_lvbo_size().
int(* qmt_handlers::qmth_lvbo_update)(struct lu_device *, struct ldlm_resource *, struct ptlrpc_request *, int)
Referenced by mdt_lvbo_update().
int(* qmt_handlers::qmth_quotactl)(const struct lu_env *, struct lu_device *, struct obd_quotactl *)
Referenced by mdt_quotactl().
The documentation for this struct was generated from the following file:
lustre/include/lustre_quota.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.