Lustre: dt_object_operations Struct Reference
dt_object_operations Struct Reference
[dt]
A dt_object provides common operations to create and destroy objects and to manage regular and extended attributes.
#include <dt_object.h>
Data Fields
void(* do_read_lock)(const struct lu_env *env, struct dt_object *dt, unsigned role)
Get read lock on object.
void(* do_write_lock)(const struct lu_env *env, struct dt_object *dt, unsigned role)
void(* do_read_unlock)(const struct lu_env *env, struct dt_object *dt)
Release read lock.
void(* do_write_unlock)(const struct lu_env *env, struct dt_object *dt)
Release write lock.
int(* do_write_locked)(const struct lu_env *env, struct dt_object *dt)
Check whether write lock is held.
int(* do_declare_attr_get)(const struct lu_env *env, struct dt_object *dt)
Declare intention to request reqular attributes.
int(* do_attr_get)(const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr)
Return regular attributes.
int(* do_declare_attr_set)(const struct lu_env *env, struct dt_object *dt, const struct lu_attr *attr, struct thandle *th)
Declare intention to change regular object's attributes.
int(* do_attr_set)(const struct lu_env *env, struct dt_object *dt, const struct lu_attr *attr, struct thandle *th)
Change regular attributes.
int(* do_declare_xattr_get)(const struct lu_env *env, struct dt_object *dt, struct lu_buf *buf, const char *name)
Declare intention to request extented attribute.
int(* do_xattr_get)(const struct lu_env *env, struct dt_object *dt, struct lu_buf *buf, const char *name)
Return a value of an extended attribute.
int(* do_declare_xattr_set)(const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, const char *name, int fl, struct thandle *th)
Declare intention to change an extended attribute.
int(* do_xattr_set)(const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, const char *name, int fl, struct thandle *th)
Set an extended attribute.
int(* do_declare_xattr_del)(const struct lu_env *env, struct dt_object *dt, const char *name, struct thandle *th)
Declare intention to delete an extended attribute.
int(* do_xattr_del)(const struct lu_env *env, struct dt_object *dt, const char *name, struct thandle *th)
Delete an extended attribute.
int(* do_xattr_list)(const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf)
Return a list of the extended attributes.
void(* do_ah_init)(const struct lu_env *env, struct dt_allocation_hint *ah, struct dt_object *parent, struct dt_object *child, umode_t mode)
Prepare allocation hint for a new object.
int(* do_declare_create)(const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *th)
Declare intention to create a new object.
int(* do_create)(const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *th)
Create new object.
int(* do_declare_destroy)(const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Declare intention to destroy an object.
int(* do_destroy)(const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Destroy an object.
int(* do_index_try)(const struct lu_env *env, struct dt_object *dt, const struct dt_index_features *feat)
Try object as an index.
int(* do_declare_ref_add)(const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Declare intention to increment nlink count.
int(* do_ref_add)(const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Increment nlink.
int(* do_declare_ref_del)(const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Declare intention to decrement nlink count.
int(* do_ref_del)(const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Decrement nlink.
int(* do_object_sync)(const struct lu_env *env, struct dt_object *obj, __u64 start, __u64 end)
Sync obect.
int(* do_object_lock)(const struct lu_env *env, struct dt_object *dt, struct lustre_handle *lh, struct ldlm_enqueue_info *einfo, union ldlm_policy_data *policy)
Lock object.
int(* do_object_unlock)(const struct lu_env *env, struct dt_object *dt, struct ldlm_enqueue_info *einfo, union ldlm_policy_data *policy)
Unlock object.
Detailed Description
A dt_object provides common operations to create and destroy objects and to manage regular and extended attributes.
Definition at line 425 of file dt_object.h.
Field Documentation
void(* dt_object_operations::do_ah_init)(const struct lu_env *env, struct dt_allocation_hint *ah, struct dt_object *parent, struct dt_object *child, umode_t mode)
Prepare allocation hint for a new object.
This method is used by the caller to inform OSD of the parent-child relationship between two objects and enable efficient object allocation. Filled allocation hint will be passed to ->do_create() later.
Parameters:
[in] env execution environment for this thread
[out] ah allocation hint
[in] parent parent object (can be NULL)
[in] child child object
[in] _mode type of the child object
Referenced by lfsck_namespace_create_orphan_dir(), lfsck_namespace_repair_dangling(), lod_ah_init(), and mdd_object_make_hint().
int(* dt_object_operations::do_attr_get)(const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr)
Return regular attributes.
The object must exist. Currently all the attributes should be returned, but in the future this can be improved so that only a selected set is returned. This can improve performance as in some cases attributes are stored in different places and getting them all can be an iterative and expensive process.
Parameters:
[in] env execution environment for this thread
[in] dt object
[out] attr attributes to fill
Return values:
0 on success
negative negated errno on error
Referenced by dt_attr_get(), llog_size(), and osp_object_init().
int(* dt_object_operations::do_attr_set)(const struct lu_env *env, struct dt_object *dt, const struct lu_attr *attr, struct thandle *th)
Change regular attributes.
Change regular attributes in the given transaction. Note only attributes flagged by attr.la_valid change. The object must exist. If the layer implementing this method is responsible for quota, then the method should maintain object accounting for the given credentials when la_uid/la_gid changes.
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] attr new attributes to apply
[in] th transaction handle
Return values:
0 on success
negative negated errno on error
Referenced by dt_attr_set().
int(* dt_object_operations::do_create)(const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *th)
Create new object.
The method creates the object passed with the specified attributes and object format. Object allocation procedure can use information stored in the allocation hint. Different object formats are supported (see enum dt_format_type and struct dt_object_format) depending on the device. If creation succeeds, then LOHA_EXISTS flag must be set in the LU-object header attributes.
If the layer implementing this method is responsible for quota, then the method should maintain object accounting for the given credentials.
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] attr attributes of the new object
[in] hint allocation hint
[in] dof object format
[in] th transaction handle
Return values:
0 on success
negative negated errno on error
Referenced by dt_create().
int(* dt_object_operations::do_declare_attr_get)(const struct lu_env *env, struct dt_object *dt)
Declare intention to request reqular attributes.
Notity the underlying filesystem that the caller may request regular attributes with ->do_attr_get() soon. This allows OSD to implement prefetching logic in an object-oriented manner. The implementation can be noop. This method should avoid expensive delays such as waiting on disk I/O, otherwise the goal of enabling a performance optimization would be defeated.
Parameters:
[in] env execution environment for this thread
[in] dt object
Return values:
0 on success
negative negated errno on error
Referenced by dt_declare_attr_get().
int(* dt_object_operations::do_declare_attr_set)(const struct lu_env *env, struct dt_object *dt, const struct lu_attr *attr, struct thandle *th)
Declare intention to change regular object's attributes.
Notify the underlying filesystem that the regular attributes may change in this transaction. This enables the layer below to prepare resources (e.g. journal credits in ext4). This method should be called between creating the transaction and starting it. Note that the la_valid field of attr specifies which attributes will change. The object need not exist.
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] attr attributes to change specified in attr.la_valid
[in] th transaction handle
Return values:
0 on success
negative negated errno on error
Referenced by dt_declare_attr_set().
int(* dt_object_operations::do_declare_create)(const struct lu_env *env, struct dt_object *dt, struct lu_attr *attr, struct dt_allocation_hint *hint, struct dt_object_format *dof, struct thandle *th)
Declare intention to create a new object.
Notify the underlying filesystem that the object may be created in this transaction. This enables the layer below to prepare resources (e.g. journal credits in ext4). This method should be called between creating the transaction and starting it.
If the layer implementing this method is responsible for quota, then the method should reserve an object for the given credentials and return an error if quota is over. If object creation later fails for some reason, then the reservation should be released properly (usually in ->dt_trans_stop()).
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] attr attributes of the new object
[in] hint allocation hint
[in] dof object format
[in] th transaction handle
Return values:
0 on success
negative negated errno on error
Referenced by dt_declare_create().
int(* dt_object_operations::do_declare_destroy)(const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Declare intention to destroy an object.
Notify the underlying filesystem that the object may be destroyed in this transaction. This enables the layer below to prepare resources (e.g. journal credits in ext4). This method should be called between creating the transaction and starting it. The object need not exist.
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] th transaction handle
Return values:
0 on success
negative negated errno on error
Referenced by dt_declare_destroy().
int(* dt_object_operations::do_declare_ref_add)(const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Declare intention to increment nlink count.
Notify the underlying filesystem that the nlink regular attribute be changed in this transaction. This enables the layer below to prepare resources (e.g. journal credits in ext4). This method should be called between creating the transaction and starting it. The object need not exist.
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] th transaction handle
Return values:
0 on success
negative negated errno on error
Referenced by dt_declare_ref_add().
int(* dt_object_operations::do_declare_ref_del)(const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Declare intention to decrement nlink count.
Notify the underlying filesystem that the nlink regular attribute be changed in this transaction. This enables the layer below to prepare resources (e.g. journal credits in ext4). This method should be called between creating the transaction and starting it. The object need not exist.
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] th transaction handle
Return values:
0 on success
negative negated errno on error
Referenced by dt_declare_ref_del().
int(* dt_object_operations::do_declare_xattr_del)(const struct lu_env *env, struct dt_object *dt, const char *name, struct thandle *th)
Declare intention to delete an extended attribute.
Notify the underlying filesystem that the extended attribute may be deleted in this transaction. This enables the layer below to prepare resources (e.g. journal credits in ext4). This method should be called between creating the transaction and starting it. The object need not exist.
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] name name of the attribute
[in] th transaction handle
Return values:
0 on success
negative negated errno on error
Referenced by dt_declare_xattr_del().
int(* dt_object_operations::do_declare_xattr_get)(const struct lu_env *env, struct dt_object *dt, struct lu_buf *buf, const char *name)
Declare intention to request extented attribute.
Notify the underlying filesystem that the caller may request extended attribute with ->do_xattr_get() soon. This allows OSD to implement prefetching logic in an object-oriented manner. The implementation can be noop. This method should avoid expensive delays such as waiting on disk I/O, otherwise the goal of enabling a performance optimization would be defeated.
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] buf unused, may be removed in the future
[in] name name of the extended attribute
Return values:
0 on success
negative negated errno on error
Referenced by dt_declare_xattr_get().
int(* dt_object_operations::do_declare_xattr_set)(const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, const char *name, int fl, struct thandle *th)
Declare intention to change an extended attribute.
Notify the underlying filesystem that the extended attribute may change in this transaction. This enables the layer below to prepare resources (e.g. journal credits in ext4). This method should be called between creating the transaction and starting it. The object need not exist.
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] buf buffer storing new value of the attribute
[in] name name of the attribute
[in] fl LU_XATTR_CREATE - fail if EA exists LU_XATTR_REPLACE - fail if EA doesn't exist
[in] th transaction handle
Return values:
0 on success
negative negated errno on error
Referenced by dt_declare_xattr_set().
int(* dt_object_operations::do_destroy)(const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Destroy an object.
This method destroys the object and all the resources associated with the object (data, key/value pairs, extended attributes, etc). The object must exist. If destroy is successful, then flag LU_OBJECT_HEARD_BANSHEE should be set to forbid access to this instance of in-core object. Any subsequent access to the same FID should get another instance with no LOHA_EXIST flag set.
If the layer implementing this method is responsible for quota, then the method should maintain object accounting for the given credentials.
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] th transaction handle
Return values:
0 on success
negative negated errno on error
Referenced by dt_destroy().
int(* dt_object_operations::do_index_try)(const struct lu_env *env, struct dt_object *dt, const struct dt_index_features *feat)
Try object as an index.
Announce that this object is going to be used as an index. This operation checks that object supports indexing operations and installs appropriate dt_index_operations vector on success. Also probes for features. Operation is successful if all required features are supported. It's not possible to access the object with index methods before ->do_index_try() returns success.
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] feat index features
Return values:
0 on success
negative negated errno on error
Referenced by acct_obj_lookup(), dt_index_read(), dt_try_as_dir(), fld_index_init(), lfsck_layout_scan_orphan(), lfsck_namespace_load_sub_trace_files(), lfsck_register(), lod_declare_object_destroy(), lod_index_try(), lod_object_destroy(), lod_striped_it_next(), lquota_disk_glb_find_create(), lquota_disk_slv_find(), lquota_disk_slv_find_create(), mgs_fs_setup(), and quota_obj_lookup().
int(* dt_object_operations::do_object_lock)(const struct lu_env *env, struct dt_object *dt, struct lustre_handle *lh, struct ldlm_enqueue_info *einfo, union ldlm_policy_data *policy)
Lock object.
Lock object(s) using Distributed Lock Manager (LDLM).
Get LDLM locks for the object. Currently used to lock "remote" objects in DNE configuration - a service running on MDTx needs to lock an object on MDTy.
Parameters:
[in] env execution environment for this thread
[in] dt object
[out] lh lock handle, sometimes used, sometimes not
[in] einfo ldlm callbacks, locking type and mode
[out] einfo private data to be passed to unlock later
[in] policy inodebits data
Return values:
0 on success
negative negated errno on error
Referenced by dt_object_lock().
int(* dt_object_operations::do_object_sync)(const struct lu_env *env, struct dt_object *obj, __u64 start, __u64 end)
Sync obect.
The method is called to sync specified range of the object to a persistent storage. The control is returned once the operation is complete. The difference from ->do_sync() is that the object can be in-sync with the persistent storage (nothing to flush), then the method returns quickly with no I/O overhead. So, this method should be preferred over ->do_sync() where possible. Also note that if the object isn't clean, then some disk filesystems will call ->do_sync() to maintain overall consistency, in which case it's still very expensive.
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] start start of the range to sync
[in] end end of the range to sync
Return values:
0 on success
negative negated errno on error
Referenced by dt_object_sync().
int(* dt_object_operations::do_object_unlock)(const struct lu_env *env, struct dt_object *dt, struct ldlm_enqueue_info *einfo, union ldlm_policy_data *policy)
Unlock object.
Release LDLM lock(s) granted with ->do_object_lock().
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] einfo lock handles, from ->do_object_lock()
[in] policy inodebits data
Return values:
0 on success
negative negated errno on error
Referenced by dt_object_unlock().
void(* dt_object_operations::do_read_lock)(const struct lu_env *env, struct dt_object *dt, unsigned role)
Get read lock on object.
Read lock is compatible with other read locks, so it's shared. Read lock is not compatible with write lock which is exclusive. The lock is blocking and can't be used from an interrupt context.
Parameters:
[in] env execution environment for this thread
[in] dt object to lock for reading
[in] role a hint to debug locks (see kernel's mutexes)
Referenced by dt_read_lock(), and ofd_read_lock().
void(* dt_object_operations::do_read_unlock)(const struct lu_env *env, struct dt_object *dt)
Release read lock.
Parameters:
[in] env execution environment for this thread
[in] dt object
Referenced by dt_read_unlock(), and ofd_read_unlock().
int(* dt_object_operations::do_ref_add)(const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Increment nlink.
Increment nlink (from the regular attributes set) in the given transaction. Note the absolute limit for nlink should be learnt from struct dt_device_param::ddp_max_nlink. The object must exist.
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] th transaction handle
Return values:
0 on success
negative negated errno on error
Referenced by dt_ref_add().
int(* dt_object_operations::do_ref_del)(const struct lu_env *env, struct dt_object *dt, struct thandle *th)
Decrement nlink.
Decrement nlink (from the regular attributes set) in the given transaction. The object must exist.
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] th transaction handle
Return values:
0 on success
negative negated errno on error
Referenced by dt_ref_del().
void(* dt_object_operations::do_write_lock)(const struct lu_env *env, struct dt_object *dt, unsigned role)
Referenced by dt_write_lock(), and ofd_write_lock().
int(* dt_object_operations::do_write_locked)(const struct lu_env *env, struct dt_object *dt)
Check whether write lock is held.
The caller can learn whether write lock is held on the object
Parameters:
[in] env execution environment for this thread
[in] dt object
Return values:
0 no write lock
1 write lock is held
Referenced by dt_write_locked().
void(* dt_object_operations::do_write_unlock)(const struct lu_env *env, struct dt_object *dt)
Release write lock.
Parameters:
[in] env execution environment for this thread
[in] dt object
Referenced by dt_write_unlock(), and ofd_write_unlock().
int(* dt_object_operations::do_xattr_del)(const struct lu_env *env, struct dt_object *dt, const char *name, struct thandle *th)
Delete an extended attribute.
This method deletes the specified extended attribute. The object must exist.
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] name name of the attribute
[in] th transaction handle
Return values:
0 on success
negative negated errno on error
Referenced by dt_xattr_del().
int(* dt_object_operations::do_xattr_get)(const struct lu_env *env, struct dt_object *dt, struct lu_buf *buf, const char *name)
Return a value of an extended attribute.
The object must exist. If the buffer is NULL, then the method must return the size of the value.
Parameters:
[in] env execution environment for this thread
[in] dt object
[out] buf buffer in which to store the value
[in] name name of the extended attribute
Return values:
0 on success
-ERANGE if buf is too small
negative negated errno on error
positive value's size if buf is NULL or has zero size
Referenced by dt_xattr_get().
int(* dt_object_operations::do_xattr_list)(const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf)
Return a list of the extended attributes.
Fills the passed buffer with a list of the extended attributes found in the object. The names are separated with ''. The object must exist.
Parameters:
[in] env execution environment for this thread
[in] dt object
[out] buf buffer to put the list in
Return values:
positive bytes used/required in the buffer
negative negated errno on error
Referenced by dt_xattr_list().
int(* dt_object_operations::do_xattr_set)(const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, const char *name, int fl, struct thandle *th)
Set an extended attribute.
Change or replace the specified extended attribute (EA). The flags passed in fl dictate whether the EA is to be created or replaced, as follows. LU_XATTR_CREATE - fail if EA exists LU_XATTR_REPLACE - fail if EA doesn't exist The object must exist.
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] buf buffer storing new value of the attribute
[in] name name of the attribute
[in] fl flags indicating EA creation or replacement
[in] th transaction handle
Return values:
0 on success
negative negated errno on error
Referenced by dt_xattr_set().
The documentation for this struct was generated from the following file:
lustre/include/dt_object.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.