Lustre: ptlrpc_nrs_pol_ops Struct Reference
ptlrpc_nrs_pol_ops Struct Reference
[Network Request Scheduler]
NRS policy operations.
#include <lustre_nrs.h>
Data Fields
int(* op_policy_init)(struct ptlrpc_nrs_policy *policy)
Called during policy registration; this operation is optional.
void(* op_policy_fini)(struct ptlrpc_nrs_policy *policy)
Called during policy unregistration; this operation is optional.
int(* op_policy_start)(struct ptlrpc_nrs_policy *policy, char *arg)
Called when activating a policy via lprocfs; policies allocate and initialize their resources here; this operation is optional.
void(* op_policy_stop)(struct ptlrpc_nrs_policy *policy)
Called when deactivating a policy via lprocfs; policies deallocate their resources here; this operation is optional.
int(* op_policy_ctl)(struct ptlrpc_nrs_policy *policy, enum ptlrpc_nrs_ctl opc, void *arg)
Used for policy-specific operations; i.e.
int(* op_res_get)(struct ptlrpc_nrs_policy *policy, struct ptlrpc_nrs_request *nrq, const struct ptlrpc_nrs_resource *parent, struct ptlrpc_nrs_resource **resp, bool moving_req)
Called when obtaining references to the resources of the resource hierarchy for a request that has arrived for handling at the PTLRPC service.
void(* op_res_put)(struct ptlrpc_nrs_policy *policy, const struct ptlrpc_nrs_resource *res)
Called when releasing references taken for resources in the resource hierarchy for the request; this operation is optional.
struct ptlrpc_nrs_request *(* op_req_get)(struct ptlrpc_nrs_policy *policy, bool peek, bool force)
Obtains a request for handling from the policy, and optionally removes the request from the policy; this operation is mandatory.
int(* op_req_enqueue)(struct ptlrpc_nrs_policy *policy, struct ptlrpc_nrs_request *nrq)
Called when attempting to add a request to a policy for later handling; this operation is mandatory.
void(* op_req_dequeue)(struct ptlrpc_nrs_policy *policy, struct ptlrpc_nrs_request *nrq)
Removes a request from the policy's set of pending requests.
void(* op_req_stop)(struct ptlrpc_nrs_policy *policy, struct ptlrpc_nrs_request *nrq)
Called after the request being carried out.
int(* op_lprocfs_init)(struct ptlrpc_service *svc)
Registers the policy's lprocfs interface with a PTLRPC service.
void(* op_lprocfs_fini)(struct ptlrpc_service *svc)
Unegisters the policy's lprocfs interface with a PTLRPC service.
Detailed Description
NRS policy operations.
These determine the behaviour of a policy, and are called in response to NRS core events.
Definition at line 75 of file lustre_nrs.h.
Field Documentation
void(* ptlrpc_nrs_pol_ops::op_lprocfs_fini)(struct ptlrpc_service *svc)
Unegisters the policy's lprocfs interface with a PTLRPC service.
In cases of failed policy registration in ptlrpc_nrs_policy_register(), this function may be called for a service which has not registered the policy successfully, so implementations of this method should make sure their operations are safe in such cases.
Parameters:
[in] svc The service
Referenced by nrs_policy_unregister_locked(), and ptlrpc_service_nrs_cleanup().
int(* ptlrpc_nrs_pol_ops::op_lprocfs_init)(struct ptlrpc_service *svc)
Registers the policy's lprocfs interface with a PTLRPC service.
Parameters:
[in] svc The service
Return values:
0 success
!= 0 error
Referenced by ptlrpc_nrs_policy_register(), and ptlrpc_service_nrs_setup().
int(* ptlrpc_nrs_pol_ops::op_policy_ctl)(struct ptlrpc_nrs_policy *policy, enum ptlrpc_nrs_ctl opc, void *arg)
Used for policy-specific operations; i.e.
not generic ones like PTLRPC_NRS_CTL_START and PTLRPC_NRS_CTL_GET_INFO; analogous to an ioctl; this operation is optional.
Parameters:
[in,out] policy The policy carrying out operation opc
[in] opc The command operation being carried out
[in,out] arg An generic buffer for communication between the user and the control operation
Return values:
-ve error
0 success
See also:
ptlrpc_nrs_policy_control()
Referenced by nrs_policy_ctl_locked().
void(* ptlrpc_nrs_pol_ops::op_policy_fini)(struct ptlrpc_nrs_policy *policy)
Called during policy unregistration; this operation is optional.
Parameters:
[in,out] policy The policy being unregistered/finalized
Referenced by nrs_policy_fini().
int(* ptlrpc_nrs_pol_ops::op_policy_init)(struct ptlrpc_nrs_policy *policy)
Called during policy registration; this operation is optional.
Parameters:
[in,out] policy The policy being initialized
Referenced by nrs_policy_init().
int(* ptlrpc_nrs_pol_ops::op_policy_start)(struct ptlrpc_nrs_policy *policy, char *arg)
Called when activating a policy via lprocfs; policies allocate and initialize their resources here; this operation is optional.
Parameters:
[in,out] policy The policy being started
[in,out] arg A generic char buffer
See also:
nrs_policy_start_locked()
Referenced by nrs_policy_start_locked().
void(* ptlrpc_nrs_pol_ops::op_policy_stop)(struct ptlrpc_nrs_policy *policy)
Called when deactivating a policy via lprocfs; policies deallocate their resources here; this operation is optional.
Parameters:
[in,out] policy The policy being stopped
See also:
nrs_policy_stop0()
Referenced by nrs_policy_stop0().
void(* ptlrpc_nrs_pol_ops::op_req_dequeue)(struct ptlrpc_nrs_policy *policy, struct ptlrpc_nrs_request *nrq)
Removes a request from the policy's set of pending requests.
Normally called after a request has been polled successfully from the policy for handling; this operation is mandatory.
Parameters:
[in,out] policy The policy the request nrq belongs to
[in,out] nrq The request to dequeue
See also:
ptlrpc_nrs_req_del_nolock()
Referenced by nrs_policy_register(), and ptlrpc_nrs_req_del_nolock().
int(* ptlrpc_nrs_pol_ops::op_req_enqueue)(struct ptlrpc_nrs_policy *policy, struct ptlrpc_nrs_request *nrq)
Called when attempting to add a request to a policy for later handling; this operation is mandatory.
Parameters:
[in,out] policy The policy on which to enqueue nrq
[in,out] nrq The request to enqueue
Return values:
0 success
!= 0 error
See also:
ptlrpc_nrs_req_add_nolock()
Referenced by nrs_policy_register(), and nrs_request_enqueue().
struct ptlrpc_nrs_request*(* ptlrpc_nrs_pol_ops::op_req_get)(struct ptlrpc_nrs_policy *policy, bool peek, bool force) [read]
Obtains a request for handling from the policy, and optionally removes the request from the policy; this operation is mandatory.
Parameters:
[in,out] policy The policy to poll
[in] peek When set, signifies that we just want to examine the request, and not handle it, so the request is not removed from the policy.
[in] force When set, it will force a policy to return a request if it has one queued.
Return values:
NULL No request available for handling
valid-pointer The request polled for handling
See also:
ptlrpc_nrs_req_get_nolock()
Referenced by nrs_policy_register(), and nrs_request_get().
void(* ptlrpc_nrs_pol_ops::op_req_stop)(struct ptlrpc_nrs_policy *policy, struct ptlrpc_nrs_request *nrq)
Called after the request being carried out.
Could be used for job/resource control; this operation is optional.
Parameters:
[in,out] policy The policy which is stopping to handle request nrq
[in,out] nrq The request
Precondition:
assert_spin_locked(&svcpt->scp_req_lock)
See also:
ptlrpc_nrs_req_stop_nolock()
Referenced by nrs_request_stop().
int(* ptlrpc_nrs_pol_ops::op_res_get)(struct ptlrpc_nrs_policy *policy, struct ptlrpc_nrs_request *nrq, const struct ptlrpc_nrs_resource *parent, struct ptlrpc_nrs_resource **resp, bool moving_req)
Called when obtaining references to the resources of the resource hierarchy for a request that has arrived for handling at the PTLRPC service.
Policies should return -ve for requests they do not wish to handle. This operation is mandatory.
Parameters:
[in,out] policy The policy we're getting resources for.
[in,out] nrq The request we are getting resources for.
[in] parent The parent resource of the resource being requested; set to NULL if none.
[out] resp The resource is to be returned here; the fallback policy in an NRS head should always return a non-NULL pointer value.
[in] moving_req When set, signifies that this is an attempt to obtain resources for a request being moved to the high-priority NRS head by ldlm_lock_reorder_req(). This implies two things: 1. We are under obd_export::exp_rpc_lock and so should not sleep. 2. We should not perform non-idempotent or can skip performing idempotent operations that were carried out when resources were first taken for the request when it was initialized in ptlrpc_nrs_req_initialize().
Return values:
0,+ve The level of the returned resource in the resource hierarchy; currently only 0 (for a non-leaf resource) and 1 (for a leaf resource) are supported by the framework.
-ve error
See also:
ptlrpc_nrs_req_initialize()
ptlrpc_nrs_hpreq_add_nolock()
ptlrpc_nrs_req_hp_move()
Referenced by nrs_policy_register(), and nrs_resource_get().
void(* ptlrpc_nrs_pol_ops::op_res_put)(struct ptlrpc_nrs_policy *policy, const struct ptlrpc_nrs_resource *res)
Called when releasing references taken for resources in the resource hierarchy for the request; this operation is optional.
Parameters:
[in,out] policy The policy the resource belongs to
[in] res The resource to be freed
See also:
ptlrpc_nrs_req_finalize()
ptlrpc_nrs_hpreq_add_nolock()
ptlrpc_nrs_req_hp_move()
Referenced by nrs_resource_put().
The documentation for this struct was generated from the following file:
lustre/include/lustre_nrs.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.