Lustre: md_object_operations Struct Reference
md_object_operations Struct Reference
[md]
Operations implemented for each md object (both directory and leaf).
#include <md_object.h>
Data Fields
int(* moo_permission)(const struct lu_env *env, struct md_object *pobj, struct md_object *cobj, struct md_attr *attr, int mask)
int(* moo_attr_get)(const struct lu_env *env, struct md_object *obj, struct md_attr *attr)
int(* moo_attr_set)(const struct lu_env *env, struct md_object *obj, const struct md_attr *attr)
int(* moo_xattr_get)(const struct lu_env *env, struct md_object *obj, struct lu_buf *buf, const char *name)
int(* moo_xattr_list)(const struct lu_env *env, struct md_object *obj, struct lu_buf *buf)
int(* moo_xattr_set)(const struct lu_env *env, struct md_object *obj, const struct lu_buf *buf, const char *name, int fl)
int(* moo_xattr_del)(const struct lu_env *env, struct md_object *obj, const char *name)
int(* moo_swap_layouts)(const struct lu_env *env, struct md_object *obj1, struct md_object *obj2, __u64 flags)
This method is used to swap the layouts between 2 objects.
int(* moo_readpage)(const struct lu_env *env, struct md_object *obj, const struct lu_rdpg *rdpg)
int(* moo_readlink)(const struct lu_env *env, struct md_object *obj, struct lu_buf *buf)
int(* moo_changelog)(const struct lu_env *env, enum changelog_rec_type type, int flags, struct md_object *obj)
int(* moo_open)(const struct lu_env *env, struct md_object *obj, int flag)
int(* moo_close)(const struct lu_env *env, struct md_object *obj, struct md_attr *ma, int mode)
int(* moo_object_sync)(const struct lu_env *, struct md_object *)
int(* moo_object_lock)(const struct lu_env *env, struct md_object *obj, struct lustre_handle *lh, struct ldlm_enqueue_info *einfo, union ldlm_policy_data *policy)
int(* moo_object_unlock)(const struct lu_env *env, struct md_object *obj, struct ldlm_enqueue_info *einfo, union ldlm_policy_data *policy)
Detailed Description
Operations implemented for each md object (both directory and leaf).
Definition at line 162 of file md_object.h.
Field Documentation
int(* md_object_operations::moo_attr_get)(const struct lu_env *env, struct md_object *obj, struct md_attr *attr)
Referenced by mo_attr_get().
int(* md_object_operations::moo_attr_set)(const struct lu_env *env, struct md_object *obj, const struct md_attr *attr)
Referenced by mo_attr_set().
int(* md_object_operations::moo_changelog)(const struct lu_env *env, enum changelog_rec_type type, int flags, struct md_object *obj)
Referenced by mo_changelog().
int(* md_object_operations::moo_close)(const struct lu_env *env, struct md_object *obj, struct md_attr *ma, int mode)
Referenced by mo_close().
int(* md_object_operations::moo_object_lock)(const struct lu_env *env, struct md_object *obj, struct lustre_handle *lh, struct ldlm_enqueue_info *einfo, union ldlm_policy_data *policy)
Referenced by mo_object_lock().
int(* md_object_operations::moo_object_sync)(const struct lu_env *, struct md_object *)
Referenced by mo_object_sync().
int(* md_object_operations::moo_object_unlock)(const struct lu_env *env, struct md_object *obj, struct ldlm_enqueue_info *einfo, union ldlm_policy_data *policy)
Referenced by mo_object_unlock().
int(* md_object_operations::moo_open)(const struct lu_env *env, struct md_object *obj, int flag)
Referenced by mo_open().
int(* md_object_operations::moo_permission)(const struct lu_env *env, struct md_object *pobj, struct md_object *cobj, struct md_attr *attr, int mask)
Referenced by mo_permission().
int(* md_object_operations::moo_readlink)(const struct lu_env *env, struct md_object *obj, struct lu_buf *buf)
Referenced by mo_readlink().
int(* md_object_operations::moo_readpage)(const struct lu_env *env, struct md_object *obj, const struct lu_rdpg *rdpg)
Return values:
number of bytes actually read upon success
Referenced by mo_readpage().
int(* md_object_operations::moo_swap_layouts)(const struct lu_env *env, struct md_object *obj1, struct md_object *obj2, __u64 flags)
This method is used to swap the layouts between 2 objects.
Referenced by mo_swap_layouts().
int(* md_object_operations::moo_xattr_del)(const struct lu_env *env, struct md_object *obj, const char *name)
Referenced by mo_xattr_del().
int(* md_object_operations::moo_xattr_get)(const struct lu_env *env, struct md_object *obj, struct lu_buf *buf, const char *name)
Referenced by mo_xattr_get().
int(* md_object_operations::moo_xattr_list)(const struct lu_env *env, struct md_object *obj, struct lu_buf *buf)
Referenced by mo_xattr_list().
int(* md_object_operations::moo_xattr_set)(const struct lu_env *env, struct md_object *obj, const struct lu_buf *buf, const char *name, int fl)
Referenced by mo_xattr_set().
The documentation for this struct was generated from the following file:
lustre/include/md_object.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.