Lustre: ksock_proto Struct Reference
ksock_proto Struct Reference
#include <socklnd.h>
Data Fields
int pro_version
int(* pro_send_hello)(ksock_conn_t *, ksock_hello_msg_t *)
int(* pro_recv_hello)(ksock_conn_t *, ksock_hello_msg_t *, int)
void(* pro_pack)(ksock_tx_t *)
void(* pro_unpack)(ksock_msg_t *)
ksock_tx_t *(* pro_queue_tx_msg)(ksock_conn_t *, ksock_tx_t *)
int(* pro_queue_tx_zcack)(ksock_conn_t *, ksock_tx_t *, __u64)
int(* pro_handle_zcreq)(ksock_conn_t *, __u64, int)
int(* pro_handle_zcack)(ksock_conn_t *, __u64, __u64)
int(* pro_match_tx)(ksock_conn_t *, ksock_tx_t *, int)
Detailed Description
Definition at line 451 of file socklnd.h.
Field Documentation
int(* ksock_proto::pro_handle_zcack)(ksock_conn_t *, __u64, __u64)
Referenced by ksocknal_process_receive().
int(* ksock_proto::pro_handle_zcreq)(ksock_conn_t *, __u64, int)
Referenced by ksocknal_process_receive().
int(* ksock_proto::pro_match_tx)(ksock_conn_t *, ksock_tx_t *, int)
Referenced by ksocknal_create_conn(), and ksocknal_find_conn_locked().
void(* ksock_proto::pro_pack)(ksock_tx_t *)
Referenced by ksocknal_tx_prep().
ksock_tx_t*(* ksock_proto::pro_queue_tx_msg)(ksock_conn_t *, ksock_tx_t *)
Referenced by ksocknal_queue_tx_locked().
int(* ksock_proto::pro_queue_tx_zcack)(ksock_conn_t *, ksock_tx_t *, __u64)
Referenced by ksocknal_handle_zcreq(), and ksocknal_queue_tx_locked().
int(* ksock_proto::pro_recv_hello)(ksock_conn_t *, ksock_hello_msg_t *, int)
Referenced by ksocknal_recv_hello().
int(* ksock_proto::pro_send_hello)(ksock_conn_t *, ksock_hello_msg_t *)
Referenced by ksocknal_send_hello().
void(* ksock_proto::pro_unpack)(ksock_msg_t *)
Referenced by ksocknal_process_receive().
int ksock_proto::pro_version
Definition at line 453 of file socklnd.h.
Referenced by ksocknal_create_conn(), ksocknal_destroy_conn(), ksocknal_new_packet(), ksocknal_recv_hello(), and ksocknal_send_hello_v2().
The documentation for this struct was generated from the following file:
lnet/klnds/socklnd/socklnd.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.