Lustre: llog_operations Struct Reference
llog_operations Struct Reference
[log]
#include <lustre_log.h>
Data Fields
int(* lop_declare_destroy)(const struct lu_env *env, struct llog_handle *handle, struct thandle *th)
int(* lop_destroy)(const struct lu_env *env, struct llog_handle *handle, struct thandle *th)
int(* lop_next_block)(const struct lu_env *env, struct llog_handle *h, int *curr_idx, int next_idx, __u64 *offset, void *buf, int len)
int(* lop_prev_block)(const struct lu_env *env, struct llog_handle *h, int prev_idx, void *buf, int len)
int(* lop_read_header)(const struct lu_env *env, struct llog_handle *handle)
int(* lop_setup)(const struct lu_env *env, struct obd_device *obd, struct obd_llog_group *olg, int ctxt_idx, struct obd_device *disk_obd)
int(* lop_sync)(struct llog_ctxt *ctxt, struct obd_export *exp, int flags)
int(* lop_cleanup)(const struct lu_env *env, struct llog_ctxt *ctxt)
int(* lop_cancel)(const struct lu_env *env, struct llog_ctxt *ctxt, struct llog_cookie *cookies, int flags)
int(* lop_connect)(struct llog_ctxt *ctxt, struct llog_logid *logid, struct llog_gen *gen, struct obd_uuid *uuid)
int(* lop_open)(const struct lu_env *env, struct llog_handle *lgh, struct llog_logid *logid, char *name, enum llog_open_param)
Any llog file must be opened first using llog_open().
int(* lop_exist)(struct llog_handle *lgh)
Opened llog may not exist and this must be checked where needed using the llog_exist() call.
int(* lop_close)(const struct lu_env *env, struct llog_handle *handle)
Close llog file and calls llog_free_handle() implicitly.
int(* lop_declare_create)(const struct lu_env *env, struct llog_handle *handle, struct thandle *th)
Create new llog file.
int(* lop_create)(const struct lu_env *env, struct llog_handle *handle, struct thandle *th)
int(* lop_declare_write_rec)(const struct lu_env *env, struct llog_handle *lgh, struct llog_rec_hdr *rec, int idx, struct thandle *th)
write new record in llog.
int(* lop_write_rec)(const struct lu_env *env, struct llog_handle *loghandle, struct llog_rec_hdr *rec, struct llog_cookie *cookie, int idx, struct thandle *th)
int(* lop_declare_add)(const struct lu_env *env, struct llog_handle *lgh, struct llog_rec_hdr *rec, struct thandle *th)
Add new record in llog catalog.
int(* lop_add)(const struct lu_env *env, struct llog_handle *lgh, struct llog_rec_hdr *rec, struct llog_cookie *cookie, struct thandle *th)
Detailed Description
Definition at line 187 of file lustre_log.h.
Field Documentation
int(* llog_operations::lop_add)(const struct lu_env *env, struct llog_handle *lgh, struct llog_rec_hdr *rec, struct llog_cookie *cookie, struct thandle *th)
Referenced by llog_add(), mdd_init(), and osp_init().
int(* llog_operations::lop_cancel)(const struct lu_env *env, struct llog_ctxt *ctxt, struct llog_cookie *cookies, int flags)
Referenced by mdd_init().
int(* llog_operations::lop_cleanup)(const struct lu_env *env, struct llog_ctxt *ctxt)
int(* llog_operations::lop_close)(const struct lu_env *env, struct llog_handle *handle)
Close llog file and calls llog_free_handle() implicitly.
Any opened llog must be closed by llog_close() call.
Referenced by llog_close().
int(* llog_operations::lop_connect)(struct llog_ctxt *ctxt, struct llog_logid *logid, struct llog_gen *gen, struct obd_uuid *uuid)
Referenced by llog_connect().
int(* llog_operations::lop_create)(const struct lu_env *env, struct llog_handle *handle, struct thandle *th)
Referenced by llog_create().
int(* llog_operations::lop_declare_add)(const struct lu_env *env, struct llog_handle *lgh, struct llog_rec_hdr *rec, struct thandle *th)
Add new record in llog catalog.
Does the same as llog_write_rec() but using llog catalog.
Referenced by llog_declare_add(), mdd_init(), and osp_init().
int(* llog_operations::lop_declare_create)(const struct lu_env *env, struct llog_handle *handle, struct thandle *th)
Create new llog file.
The llog must be opened. Must be used only for local llog operations.
Referenced by llog_declare_create().
int(* llog_operations::lop_declare_destroy)(const struct lu_env *env, struct llog_handle *handle, struct thandle *th)
Referenced by llog_declare_destroy().
int(* llog_operations::lop_declare_write_rec)(const struct lu_env *env, struct llog_handle *lgh, struct llog_rec_hdr *rec, int idx, struct thandle *th)
write new record in llog.
It appends records usually but can edit existing records too.
Referenced by llog_declare_write_rec().
int(* llog_operations::lop_destroy)(const struct lu_env *env, struct llog_handle *handle, struct thandle *th)
Referenced by llog_destroy(), and llog_trans_destroy().
int(* llog_operations::lop_exist)(struct llog_handle *lgh)
Opened llog may not exist and this must be checked where needed using the llog_exist() call.
Referenced by llog_exist().
int(* llog_operations::lop_next_block)(const struct lu_env *env, struct llog_handle *h, int *curr_idx, int next_idx, __u64 *offset, void *buf, int len)
Referenced by llog_next_block().
int(* llog_operations::lop_open)(const struct lu_env *env, struct llog_handle *lgh, struct llog_logid *logid, char *name, enum llog_open_param)
Any llog file must be opened first using llog_open().
Llog can be opened by name, logid or without both, in last case the new logid will be generated.
Referenced by llog_open().
int(* llog_operations::lop_prev_block)(const struct lu_env *env, struct llog_handle *h, int prev_idx, void *buf, int len)
Referenced by llog_prev_block().
int(* llog_operations::lop_read_header)(const struct lu_env *env, struct llog_handle *handle)
Referenced by llog_read_header().
int(* llog_operations::lop_setup)(const struct lu_env *env, struct obd_device *obd, struct obd_llog_group *olg, int ctxt_idx, struct obd_device *disk_obd)
Referenced by llog_setup().
int(* llog_operations::lop_sync)(struct llog_ctxt *ctxt, struct obd_export *exp, int flags)
int(* llog_operations::lop_write_rec)(const struct lu_env *env, struct llog_handle *loghandle, struct llog_rec_hdr *rec, struct llog_cookie *cookie, int idx, struct thandle *th)
Referenced by llog_write_rec().
The documentation for this struct was generated from the following file:
lustre/include/lustre_log.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.