Lustre: sfw_test_client_ops_t Struct Reference
sfw_test_client_ops_t Struct Reference
#include <selftest.h>
Data Fields
int(* tso_init)(struct sfw_test_instance *tsi)
void(* tso_fini)(struct sfw_test_instance *tsi)
int(* tso_prep_rpc)(struct sfw_test_unit *tsu, lnet_process_id_t dest, srpc_client_rpc_t **rpc)
void(* tso_done_rpc)(struct sfw_test_unit *tsu, srpc_client_rpc_t *rpc)
Detailed Description
Definition at line 355 of file selftest.h.
Field Documentation
void(* sfw_test_client_ops_t::tso_done_rpc)(struct sfw_test_unit *tsu, srpc_client_rpc_t *rpc)
Referenced by brw_init_test_client(), ping_init_test_client(), and sfw_test_rpc_done().
void(* sfw_test_client_ops_t::tso_fini)(struct sfw_test_instance *tsi)
Referenced by brw_init_test_client(), ping_init_test_client(), and sfw_destroy_test_instance().
int(* sfw_test_client_ops_t::tso_init)(struct sfw_test_instance *tsi)
Referenced by brw_init_test_client(), ping_init_test_client(), and sfw_add_test_instance().
int(* sfw_test_client_ops_t::tso_prep_rpc)(struct sfw_test_unit *tsu, lnet_process_id_t dest, srpc_client_rpc_t **rpc)
Referenced by brw_init_test_client(), ping_init_test_client(), and sfw_run_test().
The documentation for this struct was generated from the following file:
lnet/selftest/selftest.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.