Lustre: lu_object_operations Struct Reference
lu_object_operations Struct Reference
[lu]
Operations specific for particular lu_object.
#include <lu_object.h>
Data Fields
int(* loo_object_init)(const struct lu_env *env, struct lu_object *o, const struct lu_object_conf *conf)
Allocate lower-layer parts of the object by calling lu_device_operations::ldo_object_alloc() of the corresponding underlying device.
int(* loo_object_start)(const struct lu_env *env, struct lu_object *o)
Called (in top-to-bottom order) during object allocation after all layers were allocated and initialized.
void(* loo_object_delete)(const struct lu_env *env, struct lu_object *o)
Called before lu_object_operations::loo_object_free() to signal that object is being destroyed.
void(* loo_object_free)(const struct lu_env *env, struct lu_object *o)
Dual to lu_device_operations::ldo_object_alloc().
void(* loo_object_release)(const struct lu_env *env, struct lu_object *o)
Called when last active reference to the object is released (and object returns to the cache).
int(* loo_object_print)(const struct lu_env *env, void *cookie, lu_printer_t p, const struct lu_object *o)
Optional debugging helper.
int(* loo_object_invariant)(const struct lu_object *o)
Optional debugging method.
Detailed Description
Operations specific for particular lu_object.
Definition at line 204 of file lu_object.h.
Field Documentation
void(* lu_object_operations::loo_object_delete)(const struct lu_env *env, struct lu_object *o)
Called before lu_object_operations::loo_object_free() to signal that object is being destroyed.
Dual to lu_object_operations::loo_object_init().
Referenced by lu_object_free().
void(* lu_object_operations::loo_object_free)(const struct lu_env *env, struct lu_object *o)
Dual to lu_device_operations::ldo_object_alloc().
Called when object is removed from memory.
Referenced by lu_object_free().
int(* lu_object_operations::loo_object_init)(const struct lu_env *env, struct lu_object *o, const struct lu_object_conf *conf)
Allocate lower-layer parts of the object by calling lu_device_operations::ldo_object_alloc() of the corresponding underlying device.
This method is called once for each object inserted into object stack. It's responsibility of this method to insert lower-layer object(s) it create into appropriate places of object stack.
Referenced by lu_object_alloc().
int(* lu_object_operations::loo_object_invariant)(const struct lu_object *o)
Optional debugging method.
Returns true iff method is internally consistent.
Referenced by lu_object_invariant().
int(* lu_object_operations::loo_object_print)(const struct lu_env *env, void *cookie, lu_printer_t p, const struct lu_object *o)
Optional debugging helper.
Print given object.
Referenced by lu_object_print().
void(* lu_object_operations::loo_object_release)(const struct lu_env *env, struct lu_object *o)
Called when last active reference to the object is released (and object returns to the cache).
This method is optional.
Referenced by lu_object_put().
int(* lu_object_operations::loo_object_start)(const struct lu_env *env, struct lu_object *o)
Called (in top-to-bottom order) during object allocation after all layers were allocated and initialized.
Can be used to perform initialization depending on lower layers.
Referenced by lu_object_alloc().
The documentation for this struct was generated from the following file:
lustre/include/lu_object.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.