Lustre: lov_layout_operations Struct Reference
lov_layout_operations Struct Reference
[lov]
Data Fields
int(* llo_init)(const struct lu_env *env, struct lov_device *dev, struct lov_object *lov, struct lov_stripe_md *lsm, const struct cl_object_conf *conf, union lov_layout_state *state)
int(* llo_delete)(const struct lu_env *env, struct lov_object *lov, union lov_layout_state *state)
void(* llo_fini)(const struct lu_env *env, struct lov_object *lov, union lov_layout_state *state)
void(* llo_install)(const struct lu_env *env, struct lov_object *lov, union lov_layout_state *state)
int(* llo_print)(const struct lu_env *env, void *cookie, lu_printer_t p, const struct lu_object *o)
int(* llo_page_init)(const struct lu_env *env, struct cl_object *obj, struct cl_page *page, pgoff_t index)
int(* llo_lock_init)(const struct lu_env *env, struct cl_object *obj, struct cl_lock *lock, const struct cl_io *io)
int(* llo_io_init)(const struct lu_env *env, struct cl_object *obj, struct cl_io *io)
int(* llo_getattr)(const struct lu_env *env, struct cl_object *obj, struct cl_attr *attr)
Detailed Description
Definition at line 61 of file lov_object.c.
Field Documentation
int(* lov_layout_operations::llo_delete)(const struct lu_env *env, struct lov_object *lov, union lov_layout_state *state)
Referenced by lov_layout_change().
void(* lov_layout_operations::llo_fini)(const struct lu_env *env, struct lov_object *lov, union lov_layout_state *state)
Referenced by lov_layout_change().
int(* lov_layout_operations::llo_getattr)(const struct lu_env *env, struct cl_object *obj, struct cl_attr *attr)
int(* lov_layout_operations::llo_init)(const struct lu_env *env, struct lov_device *dev, struct lov_object *lov, struct lov_stripe_md *lsm, const struct cl_object_conf *conf, union lov_layout_state *state)
Referenced by lov_layout_change(), and lov_object_init().
void(* lov_layout_operations::llo_install)(const struct lu_env *env, struct lov_object *lov, union lov_layout_state *state)
Referenced by lov_layout_change(), and lov_object_init().
int(* lov_layout_operations::llo_io_init)(const struct lu_env *env, struct cl_object *obj, struct cl_io *io)
int(* lov_layout_operations::llo_lock_init)(const struct lu_env *env, struct cl_object *obj, struct cl_lock *lock, const struct cl_io *io)
int(* lov_layout_operations::llo_page_init)(const struct lu_env *env, struct cl_object *obj, struct cl_page *page, pgoff_t index)
int(* lov_layout_operations::llo_print)(const struct lu_env *env, void *cookie, lu_printer_t p, const struct lu_object *o)
The documentation for this struct was generated from the following file:
lustre/lov/lov_object.c
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.