Lustre: dt_txn_callback Struct Reference
dt_txn_callback Struct Reference
[dt]
Transaction call-backs.
#include <dt_object.h>
Data Fields
int(* dtc_txn_start)(const struct lu_env *env, struct thandle *txn, void *cookie)
int(* dtc_txn_stop)(const struct lu_env *env, struct thandle *txn, void *cookie)
void(* dtc_txn_commit)(struct thandle *txn, void *cookie)
void * dtc_cookie
__u32 dtc_tag
struct list_head dtc_linkage
Detailed Description
Transaction call-backs.
These are invoked by osd (or underlying transaction engine) when transaction changes state.
Call-backs are used by upper layers to modify transaction parameters and to perform some actions on for each transaction state transition. Typical example is mdt registering call-back to write into last-received file before each transaction commit.
Definition at line 1868 of file dt_object.h.
Field Documentation
void* dt_txn_callback::dtc_cookie
Definition at line 1874 of file dt_object.h.
Referenced by dt_txn_hook_commit(), dt_txn_hook_start(), dt_txn_hook_stop(), mdt_fs_setup(), osp_sync_id_traction_init(), and tgt_init().
struct list_head dt_txn_callback::dtc_linkage [read]
Definition at line 1876 of file dt_object.h.
Referenced by dt_txn_callback_add(), dt_txn_callback_del(), dt_txn_hook_commit(), dt_txn_hook_start(), dt_txn_hook_stop(), mdt_fs_setup(), and tgt_init().
__u32 dt_txn_callback::dtc_tag
Definition at line 1875 of file dt_object.h.
Referenced by dt_txn_hook_start(), dt_txn_hook_stop(), mdt_fs_setup(), osp_sync_id_traction_init(), and tgt_init().
void(* dt_txn_callback::dtc_txn_commit)(struct thandle *txn, void *cookie)
Referenced by dt_txn_hook_commit(), mdt_fs_setup(), osp_sync_id_traction_init(), and tgt_init().
int(* dt_txn_callback::dtc_txn_start)(const struct lu_env *env, struct thandle *txn, void *cookie)
Referenced by dt_txn_hook_start(), mdt_fs_setup(), and tgt_init().
int(* dt_txn_callback::dtc_txn_stop)(const struct lu_env *env, struct thandle *txn, void *cookie)
Referenced by dt_txn_hook_stop(), mdt_fs_setup(), and tgt_init().
The documentation for this struct was generated from the following file:
lustre/include/dt_object.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.