Lustre: gss_api_ops Struct Reference
gss_api_ops Struct Reference
#include <gss_api.h>
Data Fields
__u32(* gss_import_sec_context)(rawobj_t *input_token, struct gss_ctx *ctx)
__u32(* gss_copy_reverse_context)(struct gss_ctx *ctx, struct gss_ctx *ctx_new)
__u32(* gss_inquire_context)(struct gss_ctx *ctx, unsigned long *endtime)
__u32(* gss_get_mic)(struct gss_ctx *ctx, int msgcnt, rawobj_t *msgs, int iovcnt, lnet_kiov_t *iovs, rawobj_t *mic_token)
__u32(* gss_verify_mic)(struct gss_ctx *ctx, int msgcnt, rawobj_t *msgs, int iovcnt, lnet_kiov_t *iovs, rawobj_t *mic_token)
__u32(* gss_wrap)(struct gss_ctx *ctx, rawobj_t *gsshdr, rawobj_t *msg, int msg_buflen, rawobj_t *out_token)
__u32(* gss_unwrap)(struct gss_ctx *ctx, rawobj_t *gsshdr, rawobj_t *token, rawobj_t *out_msg)
__u32(* gss_prep_bulk)(struct gss_ctx *gctx, struct ptlrpc_bulk_desc *desc)
__u32(* gss_wrap_bulk)(struct gss_ctx *gctx, struct ptlrpc_bulk_desc *desc, rawobj_t *token, int adj_nob)
__u32(* gss_unwrap_bulk)(struct gss_ctx *gctx, struct ptlrpc_bulk_desc *desc, rawobj_t *token, int adj_nob)
void(* gss_delete_sec_context)(void *ctx)
int(* gss_display)(struct gss_ctx *ctx, char *buf, int bufsize)
Detailed Description
Definition at line 113 of file gss_api.h.
Field Documentation
__u32(* gss_api_ops::gss_copy_reverse_context)(struct gss_ctx *ctx, struct gss_ctx *ctx_new)
Referenced by lgss_copy_reverse_context().
void(* gss_api_ops::gss_delete_sec_context)(void *ctx)
Referenced by lgss_delete_sec_context().
int(* gss_api_ops::gss_display)(struct gss_ctx *ctx, char *buf, int bufsize)
Referenced by lgss_display().
__u32(* gss_api_ops::gss_get_mic)(struct gss_ctx *ctx, int msgcnt, rawobj_t *msgs, int iovcnt, lnet_kiov_t *iovs, rawobj_t *mic_token)
Referenced by lgss_get_mic().
__u32(* gss_api_ops::gss_import_sec_context)(rawobj_t *input_token, struct gss_ctx *ctx)
Referenced by lgss_import_sec_context().
__u32(* gss_api_ops::gss_inquire_context)(struct gss_ctx *ctx, unsigned long *endtime)
Referenced by lgss_inquire_context().
__u32(* gss_api_ops::gss_prep_bulk)(struct gss_ctx *gctx, struct ptlrpc_bulk_desc *desc)
Referenced by lgss_prep_bulk().
__u32(* gss_api_ops::gss_unwrap)(struct gss_ctx *ctx, rawobj_t *gsshdr, rawobj_t *token, rawobj_t *out_msg)
Referenced by lgss_unwrap().
__u32(* gss_api_ops::gss_unwrap_bulk)(struct gss_ctx *gctx, struct ptlrpc_bulk_desc *desc, rawobj_t *token, int adj_nob)
Referenced by lgss_unwrap_bulk().
__u32(* gss_api_ops::gss_verify_mic)(struct gss_ctx *ctx, int msgcnt, rawobj_t *msgs, int iovcnt, lnet_kiov_t *iovs, rawobj_t *mic_token)
Referenced by lgss_verify_mic().
__u32(* gss_api_ops::gss_wrap)(struct gss_ctx *ctx, rawobj_t *gsshdr, rawobj_t *msg, int msg_buflen, rawobj_t *out_token)
Referenced by lgss_wrap().
__u32(* gss_api_ops::gss_wrap_bulk)(struct gss_ctx *gctx, struct ptlrpc_bulk_desc *desc, rawobj_t *token, int adj_nob)
Referenced by lgss_wrap_bulk().
The documentation for this struct was generated from the following file:
lustre/ptlrpc/gss/gss_api.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.