Lustre: cfs_hash_ops Struct Reference
cfs_hash_ops Struct Reference
#include <libcfs_hash.h>
Data Fields
unsigned(* hs_hash)(struct cfs_hash *hs, const void *key, unsigned mask)
return hashed value from
void *(* hs_key)(struct hlist_node *hnode)
return key address of
void(* hs_keycpy)(struct hlist_node *hnode, void *key)
copy key from to
int(* hs_keycmp)(const void *key, struct hlist_node *hnode)
compare with key of returns 1 on a match
void *(* hs_object)(struct hlist_node *hnode)
return object address of , i.e: container_of(...hnode)
void(* hs_get)(struct cfs_hash *hs, struct hlist_node *hnode)
get refcount of item, always called with holding bucket-lock
void(* hs_put)(struct cfs_hash *hs, struct hlist_node *hnode)
release refcount of item
void(* hs_put_locked)(struct cfs_hash *hs, struct hlist_node *hnode)
release refcount of item, always called with holding bucket-lock
void(* hs_exit)(struct cfs_hash *hs, struct hlist_node *hnode)
it's called before removing of
Detailed Description
Definition at line 295 of file libcfs_hash.h.
Field Documentation
void(* cfs_hash_ops::hs_exit)(struct cfs_hash *hs, struct hlist_node *hnode)
it's called before removing of
Referenced by cfs_hash_exit().
void(* cfs_hash_ops::hs_get)(struct cfs_hash *hs, struct hlist_node *hnode)
get refcount of item, always called with holding bucket-lock
Referenced by cfs_hash_create(), cfs_hash_for_each_empty(), cfs_hash_for_each_nolock(), and cfs_hash_get().
unsigned(* cfs_hash_ops::hs_hash)(struct cfs_hash *hs, const void *key, unsigned mask)
return hashed value from
Referenced by cfs_hash_create(), and cfs_hash_id().
void*(* cfs_hash_ops::hs_key)(struct hlist_node *hnode)
return key address of
Referenced by cfs_hash_create(), and cfs_hash_key().
int(* cfs_hash_ops::hs_keycmp)(const void *key, struct hlist_node *hnode)
compare with key of returns 1 on a match
Referenced by cfs_hash_create(), and cfs_hash_keycmp().
void(* cfs_hash_ops::hs_keycpy)(struct hlist_node *hnode, void *key)
copy key from to
Referenced by cfs_hash_create(), and cfs_hash_keycpy().
void*(* cfs_hash_ops::hs_object)(struct hlist_node *hnode)
return object address of , i.e: container_of(...hnode)
Referenced by cfs_hash_create(), and cfs_hash_object().
void(* cfs_hash_ops::hs_put)(struct cfs_hash *hs, struct hlist_node *hnode)
release refcount of item
Referenced by cfs_hash_create(), cfs_hash_for_each_empty(), cfs_hash_for_each_nolock(), and cfs_hash_put().
void(* cfs_hash_ops::hs_put_locked)(struct cfs_hash *hs, struct hlist_node *hnode)
release refcount of item, always called with holding bucket-lock
Referenced by cfs_hash_create(), cfs_hash_for_each_empty(), cfs_hash_for_each_nolock(), cfs_hash_for_each_relax(), and cfs_hash_put_locked().
The documentation for this struct was generated from the following file:
libcfs/include/libcfs/libcfs_hash.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.