Lustre: dt_body_operations Struct Reference
dt_body_operations Struct Reference
[dt]
Per-dt-object operations on "file body" - unstructure raw data.
#include <dt_object.h>
Data Fields
ssize_t(* dbo_read)(const struct lu_env *env, struct dt_object *dt, struct lu_buf *buf, loff_t *pos)
Read data.
ssize_t(* dbo_declare_write)(const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, loff_t pos, struct thandle *th)
Declare intention to write data to object.
ssize_t(* dbo_write)(const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, loff_t *pos, struct thandle *th, int ignore)
Write unstructured data to regular existing object.
int(* dbo_bufs_get)(const struct lu_env *env, struct dt_object *dt, loff_t pos, ssize_t len, struct niobuf_local *lb, int rw)
Return buffers for data.
int(* dbo_bufs_put)(const struct lu_env *env, struct dt_object *dt, struct niobuf_local *lb, int nr)
Release reference granted by ->dbo_bufs_get().
int(* dbo_read_prep)(const struct lu_env *env, struct dt_object *dt, struct niobuf_local *lnb, int nr)
Prepare buffers for reading.
int(* dbo_write_prep)(const struct lu_env *env, struct dt_object *dt, struct niobuf_local *lb, int nr)
Prepare buffers for write.
int(* dbo_declare_write_commit)(const struct lu_env *env, struct dt_object *dt, struct niobuf_local *lb, int nr, struct thandle *th)
Declare intention to write data stored in the buffers.
int(* dbo_write_commit)(const struct lu_env *env, struct dt_object *dt, struct niobuf_local *lb, int nr, struct thandle *th)
Write to existing object.
int(* dbo_fiemap_get)(const struct lu_env *env, struct dt_object *dt, struct fiemap *fm)
Return logical to physical block mapping for a given extent.
int(* dbo_declare_punch)(const struct lu_env *env, struct dt_object *dt, __u64 start, __u64 end, struct thandle *th)
Declare intention to deallocate space from an object.
int(* dbo_punch)(const struct lu_env *env, struct dt_object *dt, __u64 start, __u64 end, struct thandle *th)
Deallocate specified region in an object.
int(* dbo_ladvise)(const struct lu_env *env, struct dt_object *dt, __u64 start, __u64 end, enum lu_ladvise_type advice)
Give advices on specified region in an object.
Detailed Description
Per-dt-object operations on "file body" - unstructure raw data.
Definition at line 1023 of file dt_object.h.
Field Documentation
int(* dt_body_operations::dbo_bufs_get)(const struct lu_env *env, struct dt_object *dt, loff_t pos, ssize_t len, struct niobuf_local *lb, int rw)
Return buffers for data.
This method is used to access data with no copying. It's so-called zero-copy I/O. The method returns the descriptors for the internal buffers where data are managed by the disk filesystem. For example, pagecache in case of ext4 or ARC with ZFS. Then other components (e.g. networking) can transfer data from or to the buffers with no additional copying.
The method should fill an array of struct niobuf_local, where each element describes a full or partial page for data at specific offset. The caller should use page/lnb_page_offset/len to find data at object's offset lnb_file_offset.
The memory referenced by the descriptors can't change its purpose until the complementary ->dbo_bufs_put() is called. The caller should specify if the buffers are used to read or modify data so that OSD can decide how to initialize the buffers: bring all the data for reads or just bring partial buffers for write. Note: the method does not check whether output array is large enough.
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] pos position in the object to start
[in] len size of region in bytes
[out] lb array of descriptors to fill
[in] rw 0 if used to read, 1 if used for write
Return values:
positive number of descriptors on success
negative negated errno on error
Referenced by dt_bufs_get().
int(* dt_body_operations::dbo_bufs_put)(const struct lu_env *env, struct dt_object *dt, struct niobuf_local *lb, int nr)
Release reference granted by ->dbo_bufs_get().
Release the reference granted by the previous ->dbo_bufs_get(). Note the references are counted.
Parameters:
[in] env execution environment for this thread
[in] dt object
[out] lb array of descriptors to fill
[in] nr size of the array
Return values:
0 on success
negative negated errno on error
Referenced by dt_bufs_put().
int(* dt_body_operations::dbo_declare_punch)(const struct lu_env *env, struct dt_object *dt, __u64 start, __u64 end, struct thandle *th)
Declare intention to deallocate space from an object.
Notify the underlying filesystem that space may be deallocated in this transactions. This enables the layer below to prepare resources (e.g. journal credits in ext4). This method should be called between creating the transaction and starting it. The object need not exist.
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] start the start of the region to deallocate
[in] end the end of the region to deallocate
[in] th transaction handle
Return values:
0 on success
negative negated errno on error
Referenced by dt_declare_punch().
ssize_t(* dt_body_operations::dbo_declare_write)(const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, loff_t pos, struct thandle *th)
Declare intention to write data to object.
Notify the underlying filesystem that data may be written in this transaction. This enables the layer below to prepare resources (e.g. journal credits in ext4). This method should be called between creating the transaction and starting it. The object need not exist. If the layer implementing this method is responsible for quota, then the method should reserve space for the given credentials and return an error if quota is over. If the write later fails for some reason, then the reserve should be released properly (usually in ->dt_trans_stop()).
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] buf buffer (including size) to copy data from
[in] pos position in the object to start
[in] th transaction handle
Return values:
0 on success
negative negated errno on error
Referenced by dt_declare_record_write(), and dt_declare_write().
int(* dt_body_operations::dbo_declare_write_commit)(const struct lu_env *env, struct dt_object *dt, struct niobuf_local *lb, int nr, struct thandle *th)
Declare intention to write data stored in the buffers.
Notify the underlying filesystem that data may be written in this transaction. This enables the layer below to prepare resources (e.g. journal credits in ext4). This method should be called between creating the transaction and starting it.
If the layer implementing this method is responsible for quota, then the method should be reserving a space for the given credentials and return an error if quota is exceeded. If the write later fails for some reason, then the reserve should be released properly (usually in ->dt_trans_stop()).
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] lb array of descriptors
[in] nr size of the array
[in] th transaction handle
Return values:
0 on success
negative negated errno on error
Referenced by dt_declare_write_commit().
int(* dt_body_operations::dbo_fiemap_get)(const struct lu_env *env, struct dt_object *dt, struct fiemap *fm)
Return logical to physical block mapping for a given extent.
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] fm describe the region to map and the output buffer see the details in include/linux/fiemap.h
Return values:
0 on success
negative negated errno on error
Referenced by dt_fiemap_get().
int(* dt_body_operations::dbo_ladvise)(const struct lu_env *env, struct dt_object *dt, __u64 start, __u64 end, enum lu_ladvise_type advice)
Give advices on specified region in an object.
This method is used to give advices about access pattern on an given region of the object. The disk filesystem understands the advices and tunes cache/read-ahead policies.
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] start the start of the region affected
[in] end the end of the region affected
[in] advice advice type
Return values:
0 on success
negative negated errno on error
Referenced by dt_ladvise().
int(* dt_body_operations::dbo_punch)(const struct lu_env *env, struct dt_object *dt, __u64 start, __u64 end, struct thandle *th)
Deallocate specified region in an object.
This method is used to deallocate (release) space possibly consumed by the given region of the object. If the layer implementing this method is responsible for quota, then the method should maintain space accounting for the given credentials.
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] start the start of the region to deallocate
[in] end the end of the region to deallocate
[in] th transaction handle
Return values:
0 on success
negative negated errno on error
Referenced by dt_punch().
ssize_t(* dt_body_operations::dbo_read)(const struct lu_env *env, struct dt_object *dt, struct lu_buf *buf, loff_t *pos)
Read data.
Read unstructured data from an existing regular object. Only data before attr.la_size is returned.
Parameters:
[in] env execution environment for this thread
[in] dt object
[out] buf buffer (including size) to copy data in
[in] pos position in the object to start
[out] pos original value of pos + bytes returned
Return values:
positive bytes read on success
negative negated errno on error
Referenced by dt_read(), dt_record_read(), lod_read(), and mdd_readlink().
int(* dt_body_operations::dbo_read_prep)(const struct lu_env *env, struct dt_object *dt, struct niobuf_local *lnb, int nr)
Prepare buffers for reading.
The method is called on the given buffers to fill them with data if that wasn't done in ->dbo_bufs_get(). The idea is that the caller should be able to get few buffers for discontiguous regions using few calls to ->dbo_bufs_get() and then request them all for the preparation with a single call, so that OSD can fire many I/Os to run concurrently. It's up to the specific OSD whether to implement this logic in ->dbo_read_prep() or just use ->dbo_bufs_get() to prepare data for every requested region individually.
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] lnb array of buffer descriptors
[in] nr size of the array
Return values:
0 on success
negative negated errno on error
Referenced by dt_read_prep().
ssize_t(* dt_body_operations::dbo_write)(const struct lu_env *env, struct dt_object *dt, const struct lu_buf *buf, loff_t *pos, struct thandle *th, int ignore)
Write unstructured data to regular existing object.
The method allocates space and puts data in. Also, the method should maintain attr.la_size properly. Partial writes are possible.
If the layer implementing this method is responsible for quota, then the method should maintain space accounting for the given credentials.
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] buf buffer (including size) to copy data from
[in] pos position in the object to start
[out] pos pos + bytes written
[in] th transaction handle
[in] ignore unused (was used to request quota ignorance)
Return values:
positive bytes written on success
negative negated errno on error
Referenced by dt_record_write(), dt_write(), and mdd_object_create().
int(* dt_body_operations::dbo_write_commit)(const struct lu_env *env, struct dt_object *dt, struct niobuf_local *lb, int nr, struct thandle *th)
Write to existing object.
This method is used to write data to a persistent storage using the buffers returned by ->dbo_bufs_get(). The caller puts new data into the buffers using own mechanisms (e.g. direct transfer from a NIC). The method should maintain attr.la_size. Also, attr.la_blocks should be maintained but this can be done in lazy manner, when actual allocation happens.
If the layer implementing this method is responsible for quota, then the method should maintain space accounting for the given credentials.
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] lb array of descriptors for the buffers
[in] nr size of the array
[in] th transaction handle
Return values:
0 on success
negative negated errno on error
Referenced by dt_write_commit().
int(* dt_body_operations::dbo_write_prep)(const struct lu_env *env, struct dt_object *dt, struct niobuf_local *lb, int nr)
Prepare buffers for write.
This method is called on the given buffers to ensure the partial buffers contain correct data. The underlying idea is the same as in ->db_read_prep().
Parameters:
[in] env execution environment for this thread
[in] dt object
[in] lb array of buffer descriptors
[in] nr size of the array
Return values:
0 on success
negative negated errno on error
Referenced by dt_write_prep().
The documentation for this struct was generated from the following file:
lustre/include/dt_object.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.