Lustre: osd_fid_pack Struct Reference
osd_fid_pack Struct Reference
Storage representation for fids.
#include <osd_internal.h>
Data Fields
unsigned char fp_len
char fp_area [sizeof(struct lu_fid)]
Detailed Description
Storage representation for fids.
Variable size, first byte contains the length of the whole record.
Definition at line 418 of file osd_internal.h.
Field Documentation
char osd_fid_pack::fp_area[sizeof(struct lu_fid)]
Definition at line 420 of file osd_internal.h.
Referenced by osd_dirent_reinsert(), osd_fid_pack(), and osd_fid_unpack().
unsigned char osd_fid_pack::fp_len
Definition at line 419 of file osd_internal.h.
Referenced by osd_dirent_reinsert(), osd_fid_pack(), and osd_fid_unpack().
The documentation for this struct was generated from the following file:
lustre/osd-ldiskfs/osd_internal.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.