Lustre: link_ea_entry Struct Reference
link_ea_entry Struct Reference
[lustreidl]
Hardlink data is name and parent fid.
#include <lustre_idl.h>
Data Fields
unsigned char lee_reclen [2]
__u16 stored big-endian, unaligned
unsigned char lee_parent_fid [sizeof(struct lu_fid)]
char lee_name [0]
Detailed Description
Hardlink data is name and parent fid.
Stored in this crazy struct for maximum packing and endian-neutrality
Definition at line 3684 of file lustre_idl.h.
Field Documentation
char link_ea_entry::lee_name[0]
Definition at line 3688 of file lustre_idl.h.
Referenced by linkea_entry_pack(), and linkea_entry_unpack().
unsigned char link_ea_entry::lee_parent_fid[sizeof(struct lu_fid)]
Definition at line 3687 of file lustre_idl.h.
Referenced by linkea_entry_pack(), linkea_entry_unpack(), mdt_attr_get_pfid(), and osd_find_parent_fid().
unsigned char link_ea_entry::lee_reclen[2]
__u16 stored big-endian, unaligned
Definition at line 3686 of file lustre_idl.h.
Referenced by lfsck_namespace_filter_linkea_entry(), linkea_entry_pack(), and linkea_entry_unpack().
The documentation for this struct was generated from the following file:
lustre/include/lustre/lustre_idl.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.