Lustre: md_device_operations Struct Reference
md_device_operations Struct Reference
[md]
#include <md_object.h>
Data Fields
int(* mdo_root_get)(const struct lu_env *env, struct md_device *m, struct lu_fid *f)
meta-data device related handlers.
int(* mdo_maxeasize_get)(const struct lu_env *env, struct md_device *m, int *easize)
int(* mdo_statfs)(const struct lu_env *env, struct md_device *m, struct obd_statfs *sfs)
int(* mdo_llog_ctxt_get)(const struct lu_env *env, struct md_device *m, int idx, void **h)
int(* mdo_iocontrol)(const struct lu_env *env, struct md_device *m, unsigned int cmd, int len, void *data)
Detailed Description
Definition at line 263 of file md_object.h.
Field Documentation
int(* md_device_operations::mdo_iocontrol)(const struct lu_env *env, struct md_device *m, unsigned int cmd, int len, void *data)
Referenced by mdt_fini(), mdt_init0(), mdt_ioc_child(), mdt_iocontrol(), and mdt_postrecov().
int(* md_device_operations::mdo_llog_ctxt_get)(const struct lu_env *env, struct md_device *m, int idx, void **h)
Referenced by mdt_llog_ctxt_clone().
int(* md_device_operations::mdo_maxeasize_get)(const struct lu_env *env, struct md_device *m, int *easize)
Referenced by mdt_init0().
int(* md_device_operations::mdo_root_get)(const struct lu_env *env, struct md_device *m, struct lu_fid *f)
meta-data device related handlers.
Referenced by mdt_prepare().
int(* md_device_operations::mdo_statfs)(const struct lu_env *env, struct md_device *m, struct obd_statfs *sfs)
Referenced by mdt_statfs().
The documentation for this struct was generated from the following file:
lustre/include/md_object.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.