Lustre: dt_device_operations Struct Reference
dt_device_operations Struct Reference
[dt]
Operations on dt device.
#include <dt_object.h>
Data Fields
int(* dt_statfs)(const struct lu_env *env, struct dt_device *dev, struct obd_statfs *osfs)
Return device-wide statistics.
struct thandle *(* dt_trans_create)(const struct lu_env *env, struct dt_device *dev)
Create transaction.
int(* dt_trans_start)(const struct lu_env *env, struct dt_device *dev, struct thandle *th)
Start transaction.
int(* dt_trans_stop)(const struct lu_env *env, struct dt_device *dev, struct thandle *th)
Stop transaction.
int(* dt_trans_cb_add)(struct thandle *th, struct dt_txn_commit_cb *dcb)
Add commit callback to the transaction.
int(* dt_root_get)(const struct lu_env *env, struct dt_device *dev, struct lu_fid *f)
Return FID of root index object.
void(* dt_conf_get)(const struct lu_env *env, const struct dt_device *dev, struct dt_device_param *param)
Return device configuration data.
int(* dt_sync)(const struct lu_env *env, struct dt_device *dev)
Sync the device.
int(* dt_ro)(const struct lu_env *env, struct dt_device *dev)
Make device read-only.
int(* dt_commit_async)(const struct lu_env *env, struct dt_device *dev)
Start transaction commit asynchronously.
Detailed Description
Operations on dt device.
Definition at line 120 of file dt_object.h.
Field Documentation
int(* dt_device_operations::dt_commit_async)(const struct lu_env *env, struct dt_device *dev)
Start transaction commit asynchronously.
Provide a hint to the underlying filesystem that it should start committing soon. The control returns immediately. It's up to the layer implementing the method how soon to start committing. Usually this should be throttled to some extent, otherwise the number of aggregated transaction goes too high causing performance drop.
Parameters:
[in] env execution environment for this thread
[in] dev dt device
Return values:
0 on success
negative negated errno on error
Referenced by dt_commit_async(), and mdt_device_commit_async().
void(* dt_device_operations::dt_conf_get)(const struct lu_env *env, const struct dt_device *dev, struct dt_device_param *param)
Return device configuration data.
Return device (disk fs, actually) specific configuration. The configuration isn't subject to change at runtime. See struct dt_device_param for the details.
Parameters:
[in] env execution environment for this thread
[in] dev dt device
[out] param configuration parameters
Referenced by dt_conf_get().
int(* dt_device_operations::dt_ro)(const struct lu_env *env, struct dt_device *dev)
Make device read-only.
Prevent new modifications to the device. This is a very specific state where all the changes are accepted successfully and the commit callbacks are called, but persistent state never changes. Used only in the tests to simulate power-off scenario.
Parameters:
[in] env execution environment for this thread
[in] dev dt device
Return values:
0 on success
negative negated errno on error
Referenced by dt_ro(), mdt_fail_write(), and mdt_iocontrol().
int(* dt_device_operations::dt_root_get)(const struct lu_env *env, struct dt_device *dev, struct lu_fid *f)
Return FID of root index object.
Return the FID of the root object in the filesystem. This object is usually provided as a bootstrap point by a disk filesystem. This is up to the implementation which FID to use, though [FID_SEQ_ROOT:1:0] is reserved for this purpose.
Parameters:
[in] env execution environment for this thread
[in] dev dt device
[out] fid FID of the root object
Return values:
0 on success
negative negated errno on error
Referenced by dt_root_get(), and dt_store_resolve().
int(* dt_device_operations::dt_statfs)(const struct lu_env *env, struct dt_device *dev, struct obd_statfs *osfs)
Return device-wide statistics.
Return device-wide stats including block size, total and free blocks, total and free objects, etc. See struct obd_statfs for the details.
Parameters:
[in] env execution environment for this thread
[in] dev dt device
[out] osfs stats information
Return values:
0 on success
negative negated errno on error
Referenced by dt_statfs(), and mdd_statfs().
int(* dt_device_operations::dt_sync)(const struct lu_env *env, struct dt_device *dev)
Sync the device.
Sync all the cached state (dirty buffers, pages, etc) to the persistent storage. The method returns control once the sync is complete. This operation may incur significant I/O to disk and should be reserved for cases where a global sync is strictly necessary.
Parameters:
[in] env execution environment for this thread
[in] dev dt device
Return values:
0 on success
negative negated errno on error
Referenced by dt_sync(), and mdt_device_sync().
int(* dt_device_operations::dt_trans_cb_add)(struct thandle *th, struct dt_txn_commit_cb *dcb)
Add commit callback to the transaction.
Add a commit callback to the given transaction handle. The callback will be called when the associated transaction is stored. I.e. the transaction will survive an event like power off if the callback did run. The number of callbacks isn't limited, but you should note that some disk filesystems do handle the commit callbacks in the thread handling commit/flush of all the transactions, meaning that new transactions are blocked from commit and flush until all the callbacks are done. Also, note multiple callbacks can be running concurrently using multiple CPU cores. The callbacks will be running in a special environment which can not be used to pass data around.
Parameters:
[in] th transaction handle
[in] dcb commit callback description
Return values:
0 on success
negative negated errno on error
Referenced by dt_trans_cb_add().
struct thandle*(* dt_device_operations::dt_trans_create)(const struct lu_env *env, struct dt_device *dev) [read]
Create transaction.
Create in-memory structure representing the transaction for the caller. The structure returned will be used by the calling thread to specify the transaction the updates belong to. Once created successfully ->dt_trans_stop() must be called in any case (with ->dt_trans_start() and updates or not) so that the transaction handle and other resources can be released by the layers below.
Parameters:
[in] env execution environment for this thread
[in] dev dt device
Return values:
pointer to handle if creation succeeds
ERR_PTR(errno) if creation fails
Referenced by dt_trans_create(), and mdd_trans_create().
int(* dt_device_operations::dt_trans_start)(const struct lu_env *env, struct dt_device *dev, struct thandle *th)
Start transaction.
Start the transaction. The transaction described by th can be started only once. Another start is considered as an error. A thread is not supposed to start a transaction while another transaction isn't closed by the thread (though multiple handles can be created). The caller should start the transaction once all possible updates are declared (see the ->do_declare_* methods below) and all the needed resources are reserved.
Parameters:
[in] env execution environment for this thread
[in] dev dt device
[in] th transaction handle
Return values:
0 on success
negative negated errno on error
Referenced by dt_trans_start(), dt_trans_start_local(), and mdd_trans_start().
int(* dt_device_operations::dt_trans_stop)(const struct lu_env *env, struct dt_device *dev, struct thandle *th)
Stop transaction.
Once stopped the transaction described by th is complete (all the needed updates are applied) and further processing such as flushing to disk, sending to another target, etc, is handled by lower layers. The caller can't access this transaction by the handle anymore (except from the commit callbacks, see below).
Parameters:
[in] env execution environment for this thread
[in] dev dt device
[in] th transaction handle
Return values:
0 on success
negative negated errno on error
Referenced by dt_trans_stop(), and mdd_trans_stop().
The documentation for this struct was generated from the following file:
lustre/include/dt_object.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.