Lustre: upcall_cache_ops Struct Reference
upcall_cache_ops Struct Reference
[ucache]
#include <upcall_cache.h>
Data Fields
void(* init_entry)(struct upcall_cache_entry *, void *args)
void(* free_entry)(struct upcall_cache *, struct upcall_cache_entry *)
int(* upcall_compare)(struct upcall_cache *, struct upcall_cache_entry *, __u64 key, void *args)
int(* downcall_compare)(struct upcall_cache *, struct upcall_cache_entry *, __u64 key, void *args)
int(* do_upcall)(struct upcall_cache *, struct upcall_cache_entry *)
int(* parse_downcall)(struct upcall_cache *, struct upcall_cache_entry *, void *)
Detailed Description
Definition at line 105 of file upcall_cache.h.
Field Documentation
int(* upcall_cache_ops::do_upcall)(struct upcall_cache *, struct upcall_cache_entry *)
Referenced by refresh_entry().
int(* upcall_cache_ops::downcall_compare)(struct upcall_cache *, struct upcall_cache_entry *, __u64 key, void *args)
Referenced by downcall_compare().
void(* upcall_cache_ops::free_entry)(struct upcall_cache *, struct upcall_cache_entry *)
Referenced by free_entry().
void(* upcall_cache_ops::init_entry)(struct upcall_cache_entry *, void *args)
Referenced by alloc_entry().
int(* upcall_cache_ops::parse_downcall)(struct upcall_cache *, struct upcall_cache_entry *, void *)
Referenced by upcall_cache_downcall().
int(* upcall_cache_ops::upcall_compare)(struct upcall_cache *, struct upcall_cache_entry *, __u64 key, void *args)
Referenced by upcall_compare().
The documentation for this struct was generated from the following file:
lustre/include/upcall_cache.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.