Lustre: cfs_binheap_ops Struct Reference
cfs_binheap_ops Struct Reference
[Binary heap]
Binary heap operations.
#include <libcfs_heap.h>
Data Fields
int(* hop_enter)(struct cfs_binheap *h, struct cfs_binheap_node *e)
Called right before inserting a node into the binary heap.
void(* hop_exit)(struct cfs_binheap *h, struct cfs_binheap_node *e)
Called right after removing a node from the binary heap.
int(* hop_compare)(struct cfs_binheap_node *a, struct cfs_binheap_node *b)
A binary predicate which is called during internal heap sorting operations, and used in order to determine the relevant ordering of two heap nodes.
Detailed Description
Binary heap operations.
Definition at line 90 of file libcfs_heap.h.
Field Documentation
int(* cfs_binheap_ops::hop_compare)(struct cfs_binheap_node *a, struct cfs_binheap_node *b)
A binary predicate which is called during internal heap sorting operations, and used in order to determine the relevant ordering of two heap nodes.
Implementing this operation is mandatory.
Parameters:
[in] a The first heap node
[in] b The second heap node
Return values:
0 Node a > node b
1 Node a < node b
See also:
cfs_binheap_bubble()
cfs_biheap_sink()
Referenced by cfs_binheap_bubble(), cfs_binheap_create(), and cfs_binheap_sink().
int(* cfs_binheap_ops::hop_enter)(struct cfs_binheap *h, struct cfs_binheap_node *e)
Called right before inserting a node into the binary heap.
Implementing this operation is optional.
Parameters:
[in] h The heap
[in] e The node
Return values:
0 success
!= 0 error
Referenced by cfs_binheap_insert().
void(* cfs_binheap_ops::hop_exit)(struct cfs_binheap *h, struct cfs_binheap_node *e)
Called right after removing a node from the binary heap.
Implementing this operation is optional.
Parameters:
[in] h The heap
[in] e The node
Referenced by cfs_binheap_remove().
The documentation for this struct was generated from the following file:
libcfs/include/libcfs/libcfs_heap.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.