Lustre: md_dir_operations Struct Reference
md_dir_operations Struct Reference
[md]
Operations implemented for each directory object.
#include <md_object.h>
Data Fields
int(* mdo_is_subdir)(const struct lu_env *env, struct md_object *obj, const struct lu_fid *fid, struct lu_fid *sfid)
int(* mdo_lookup)(const struct lu_env *env, struct md_object *obj, const struct lu_name *lname, struct lu_fid *fid, struct md_op_spec *spec)
mdl_mode_t(* mdo_lock_mode)(const struct lu_env *env, struct md_object *obj, mdl_mode_t mode)
int(* mdo_create)(const struct lu_env *env, struct md_object *pobj, const struct lu_name *lname, struct md_object *child, struct md_op_spec *spec, struct md_attr *ma)
int(* mdo_create_data)(const struct lu_env *env, struct md_object *p, struct md_object *o, const struct md_op_spec *spec, struct md_attr *ma)
This method is used for creating data object for this meta object.
int(* mdo_rename)(const struct lu_env *env, struct md_object *spobj, struct md_object *tpobj, const struct lu_fid *lf, const struct lu_name *lsname, struct md_object *tobj, const struct lu_name *ltname, struct md_attr *ma)
int(* mdo_link)(const struct lu_env *env, struct md_object *tgt_obj, struct md_object *src_obj, const struct lu_name *lname, struct md_attr *ma)
int(* mdo_unlink)(const struct lu_env *env, struct md_object *pobj, struct md_object *cobj, const struct lu_name *lname, struct md_attr *ma, int no_name)
int(* mdo_migrate)(const struct lu_env *env, struct md_object *pobj, struct md_object *sobj, const struct lu_name *lname, struct md_object *tobj, struct md_attr *ma)
Detailed Description
Operations implemented for each directory object.
Definition at line 222 of file md_object.h.
Field Documentation
int(* md_dir_operations::mdo_create)(const struct lu_env *env, struct md_object *pobj, const struct lu_name *lname, struct md_object *child, struct md_op_spec *spec, struct md_attr *ma)
Referenced by mdo_create().
int(* md_dir_operations::mdo_create_data)(const struct lu_env *env, struct md_object *p, struct md_object *o, const struct md_op_spec *spec, struct md_attr *ma)
This method is used for creating data object for this meta object.
Referenced by mdo_create_data().
int(* md_dir_operations::mdo_is_subdir)(const struct lu_env *env, struct md_object *obj, const struct lu_fid *fid, struct lu_fid *sfid)
Referenced by mdo_is_subdir().
int(* md_dir_operations::mdo_link)(const struct lu_env *env, struct md_object *tgt_obj, struct md_object *src_obj, const struct lu_name *lname, struct md_attr *ma)
Referenced by mdo_link().
mdl_mode_t(* md_dir_operations::mdo_lock_mode)(const struct lu_env *env, struct md_object *obj, mdl_mode_t mode)
Referenced by mdo_lock_mode().
int(* md_dir_operations::mdo_lookup)(const struct lu_env *env, struct md_object *obj, const struct lu_name *lname, struct lu_fid *fid, struct md_op_spec *spec)
Referenced by mdo_lookup().
int(* md_dir_operations::mdo_migrate)(const struct lu_env *env, struct md_object *pobj, struct md_object *sobj, const struct lu_name *lname, struct md_object *tobj, struct md_attr *ma)
Referenced by mdo_migrate().
int(* md_dir_operations::mdo_rename)(const struct lu_env *env, struct md_object *spobj, struct md_object *tpobj, const struct lu_fid *lf, const struct lu_name *lsname, struct md_object *tobj, const struct lu_name *ltname, struct md_attr *ma)
Referenced by mdo_rename().
int(* md_dir_operations::mdo_unlink)(const struct lu_env *env, struct md_object *pobj, struct md_object *cobj, const struct lu_name *lname, struct md_attr *ma, int no_name)
Referenced by mdo_unlink().
The documentation for this struct was generated from the following file:
lustre/include/md_object.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.