Lustre: iam_operations Struct Reference
iam_operations Struct Reference
#include <osd_iam.h>
Data Fields
__u32(* id_root_ptr)(struct iam_container *c)
int(* id_node_check)(struct iam_path *path, struct iam_frame *frame)
int(* id_node_load)(struct iam_path *path, struct iam_frame *frame)
int(* id_node_init)(struct iam_container *c, struct buffer_head *bh, int root)
int(* id_node_read)(struct iam_container *c, iam_ptr_t ptr, handle_t *h, struct buffer_head **bh)
int(* id_ikeycmp)(const struct iam_container *c, const struct iam_ikey *k1, const struct iam_ikey *k2)
struct iam_entry *(* id_root_inc)(struct iam_container *c, struct iam_path *path, struct iam_frame *frame)
struct iam_path_descr *(* id_ipd_alloc)(const struct iam_container *c, void *area)
void(* id_ipd_free)(struct iam_path_descr *ipd)
char id_name [DX_FMT_NAME_LEN]
Detailed Description
Definition at line 279 of file osd_iam.h.
Field Documentation
int(* iam_operations::id_ikeycmp)(const struct iam_container *c, const struct iam_ikey *k1, const struct iam_ikey *k2)
Referenced by iam_ikeycmp().
struct iam_path_descr*(* iam_operations::id_ipd_alloc)(const struct iam_container *c, void *area) [read]
Referenced by osd_idx_ipd_get(), and osd_it_ipd_get().
void(* iam_operations::id_ipd_free)(struct iam_path_descr *ipd)
Referenced by osd_ipd_put().
char iam_operations::id_name[DX_FMT_NAME_LEN]
Definition at line 322 of file osd_iam.h.
Referenced by osd_object_print().
int(* iam_operations::id_node_check)(struct iam_path *path, struct iam_frame *frame)
Referenced by iam_lookup_try().
int(* iam_operations::id_node_init)(struct iam_container *c, struct buffer_head *bh, int root)
Referenced by split_index_node().
int(* iam_operations::id_node_load)(struct iam_path *path, struct iam_frame *frame)
Referenced by iam_lookup_try().
int(* iam_operations::id_node_read)(struct iam_container *c, iam_ptr_t ptr, handle_t *h, struct buffer_head **bh)
Referenced by iam_leaf_load(), and iam_lookup_try().
struct iam_entry*(* iam_operations::id_root_inc)(struct iam_container *c, struct iam_path *path, struct iam_frame *frame) [read]
Referenced by split_index_node().
__u32(* iam_operations::id_root_ptr)(struct iam_container *c)
Referenced by iam_lookup_try(), and iam_node_read().
The documentation for this struct was generated from the following file:
lustre/osd-ldiskfs/osd_iam.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.