Lustre: ptlrpc_bulk_frag_ops Struct Reference
ptlrpc_bulk_frag_ops Struct Reference
[net]
#include <lustre_net.h>
Data Fields
void(* add_kiov_frag)(struct ptlrpc_bulk_desc *desc, struct page *page, int pageoffset, int len)
Add a page page to the bulk descriptor desc Data to transfer in the page starts at offset pageoffset and amount of data to transfer from the page is len.
int(* add_iov_frag)(struct ptlrpc_bulk_desc *desc, void *frag, int len)
void(* release_frags)(struct ptlrpc_bulk_desc *desc)
Uninitialize and free bulk descriptor desc.
Detailed Description
Definition at line 1395 of file lustre_net.h.
Field Documentation
int(* ptlrpc_bulk_frag_ops::add_iov_frag)(struct ptlrpc_bulk_desc *desc, void *frag, int len)
Referenced by osp_md_read(), osp_prep_update_req(), out_handle(), ptlrpc_new_bulk(), and tgt_send_buffer().
void(* ptlrpc_bulk_frag_ops::add_kiov_frag)(struct ptlrpc_bulk_desc *desc, struct page *page, int pageoffset, int len)
Add a page page to the bulk descriptor desc Data to transfer in the page starts at offset pageoffset and amount of data to transfer from the page is len.
Referenced by mdc_getpage(), mgc_process_recover_log(), mgs_get_ir_logs(), osc_brw_prep_request(), osp_it_fetch(), ptlrpc_new_bulk(), qsd_fetch_index(), tgt_brw_read(), tgt_brw_write(), and tgt_sendpage().
void(* ptlrpc_bulk_frag_ops::release_frags)(struct ptlrpc_bulk_desc *desc)
Uninitialize and free bulk descriptor desc.
Works on bulk descriptors both from server and client side.
Referenced by ptlrpc_free_bulk().
The documentation for this struct was generated from the following file:
lustre/include/lustre_net.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.