Lustre: ptlrpc_ctx_ops Struct Reference
ptlrpc_ctx_ops Struct Reference
[sptlrpc]
#include <lustre_sec.h>
Data Fields
int(* match)(struct ptlrpc_cli_ctx *ctx, struct vfs_cred *vcred)
To determine whether it's suitable to use the ctx for vcred.
int(* refresh)(struct ptlrpc_cli_ctx *ctx)
To bring the ctx uptodate.
int(* validate)(struct ptlrpc_cli_ctx *ctx)
Validate the ctx.
void(* die)(struct ptlrpc_cli_ctx *ctx, int grace)
Force the ctx to die.
int(* display)(struct ptlrpc_cli_ctx *ctx, char *buf, int bufsize)
int(* sign)(struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req)
Sign the request message using ctx.
int(* verify)(struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req)
Verify the reply message using ctx.
int(* seal)(struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req)
Encrypt the request message using ctx.
int(* unseal)(struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req)
Decrypt the reply message using ctx.
int(* wrap_bulk)(struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
Wrap bulk request data.
int(* unwrap_bulk)(struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
Unwrap bulk reply data.
Detailed Description
Definition at line 396 of file lustre_sec.h.
Field Documentation
void(* ptlrpc_ctx_ops::die)(struct ptlrpc_cli_ctx *ctx, int grace)
Force the ctx to die.
Referenced by sptlrpc_cli_ctx_expire().
int(* ptlrpc_ctx_ops::display)(struct ptlrpc_cli_ctx *ctx, char *buf, int bufsize)
Referenced by sptlrpc_cli_ctx_display().
int(* ptlrpc_ctx_ops::match)(struct ptlrpc_cli_ctx *ctx, struct vfs_cred *vcred)
To determine whether it's suitable to use the ctx for vcred.
Referenced by ctx_match_pf().
int(* ptlrpc_ctx_ops::refresh)(struct ptlrpc_cli_ctx *ctx)
To bring the ctx uptodate.
Referenced by sptlrpc_req_refresh_ctx().
int(* ptlrpc_ctx_ops::seal)(struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req)
Encrypt the request message using ctx.
Precondition:
req->rq_reqmsg point to request message in clear text.
req->rq_reqlen is the request message length.
Postcondition:
req->rq_reqbuf point to request message.
req->rq_reqdata_len is set to the final request message size.
See also:
gss_cli_ctx_seal().
Referenced by sptlrpc_cli_wrap_request().
int(* ptlrpc_ctx_ops::sign)(struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req)
Sign the request message using ctx.
Precondition:
req->rq_reqmsg point to request message.
req->rq_reqlen is the request message length.
Postcondition:
req->rq_reqbuf point to request message with signature.
req->rq_reqdata_len is set to the final request message size.
See also:
null_ctx_sign(), plain_ctx_sign(), gss_cli_ctx_sign().
Referenced by sptlrpc_cli_wrap_request().
int(* ptlrpc_ctx_ops::unseal)(struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req)
Decrypt the reply message using ctx.
Precondition:
req->rq_repdata point to encrypted reply message.
req->rq_repdata_len is the total cipher text length.
Postcondition:
req->rq_repmsg point to reply message in clear text.
req->rq_replen is the reply message length in clear text.
See also:
gss_cli_ctx_unseal().
Referenced by do_cli_unwrap_reply().
int(* ptlrpc_ctx_ops::unwrap_bulk)(struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
Unwrap bulk reply data.
This is called after wrapping RPC reply message.
Precondition:
bulk buffer is descripted by desc->bd_iov/desc->bd_enc_iov and desc->bd_iov_count, according to wrap_bulk().
Postcondition:
final bulk data in clear text is placed in buffer described by desc->bd_iov and desc->bd_iov_count.
Returns:
+ve nob of actual bulk data in clear text.
-ve error code.
See also:
plain_cli_unwrap_bulk(), gss_cli_ctx_unwrap_bulk().
Referenced by sptlrpc_cli_unwrap_bulk_read(), and sptlrpc_cli_unwrap_bulk_write().
int(* ptlrpc_ctx_ops::validate)(struct ptlrpc_cli_ctx *ctx)
Validate the ctx.
Referenced by sptlrpc_import_check_ctx(), and sptlrpc_req_refresh_ctx().
int(* ptlrpc_ctx_ops::verify)(struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req)
Verify the reply message using ctx.
Precondition:
req->rq_repdata point to reply message with signature.
req->rq_repdata_len is the total reply message length.
Postcondition:
req->rq_repmsg point to reply message without signature.
req->rq_replen is the reply message length.
See also:
null_ctx_verify(), plain_ctx_verify(), gss_cli_ctx_verify().
Referenced by do_cli_unwrap_reply().
int(* ptlrpc_ctx_ops::wrap_bulk)(struct ptlrpc_cli_ctx *ctx, struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc)
Wrap bulk request data.
This is called before wrapping RPC request message.
Precondition:
bulk buffer is descripted by desc->bd_iov and desc->bd_iov_count. note for read it's just buffer, no data need to be sent; for write it contains data in clear text.
Postcondition:
when necessary, ptlrpc_bulk_sec_desc was properly prepared (usually inside of RPC request message).
encryption: cipher text bulk buffer is descripted by desc->bd_enc_iov and desc->bd_iov_count (currently assume iov count remains the same).
otherwise: bulk buffer is still desc->bd_iov and desc->bd_iov_count.
Returns:
0: success.
-ev: error code.
See also:
plain_cli_wrap_bulk(), gss_cli_ctx_wrap_bulk().
Referenced by sptlrpc_cli_wrap_bulk().
The documentation for this struct was generated from the following file:
lustre/include/lustre_sec.h
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.