Lustre: lustre/llite/super25.c File Reference
lustre/llite/super25.c File Reference
#include <linux/module.h>
#include <linux/types.h>
#include <linux/version.h>
#include <lustre_ha.h>
#include <lustre_dlm.h>
#include <linux/init.h>
#include <linux/fs.h>
#include <lprocfs_status.h>
#include "llite_internal.h"
#include "vvp_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LLITE
Functions
static struct inode * ll_alloc_inode (struct super_block *sb)
static void ll_destroy_inode (struct inode *inode)
void lustre_register_client_process_config (int(*cpc)(struct lustre_cfg *lcfg))
static int __init lustre_init (void)
static void __exit lustre_exit (void)
MODULE_AUTHOR ("OpenSFS, Inc. <http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Client File System")
MODULE_VERSION (LUSTRE_VERSION_STRING)
MODULE_LICENSE ("GPL")
module_init (lustre_init)
module_exit (lustre_exit)
Variables
static struct kmem_cache * ll_inode_cachep
struct super_operations lustre_super_operations
Define Documentation
#define DEBUG_SUBSYSTEM S_LLITE
Definition at line 37 of file super25.c.
Function Documentation
static struct inode* ll_alloc_inode (struct super_block * sb) [static, read]
Definition at line 52 of file super25.c.
References ll_inode_cachep, ll_s2sbi, ll_stats_ops_tally(), ll_inode_info::lli_vfs_inode, LPROC_LL_ALLOC_INODE, and OBD_SLAB_ALLOC_PTR_GFP.
static void ll_destroy_inode (struct inode * inode) [static]
Definition at line 77 of file super25.c.
References ll_i2info(), ll_inode_cachep, and OBD_SLAB_FREE_PTR.
static void __exit lustre_exit (void) [static]
Definition at line 213 of file super25.c.
References cl_env_put(), cl_inode_fini_env, cl_inode_fini_refcheck, ll_file_data_slab, ll_inode_cachep, ll_remote_perm_cachep, ll_rmtperm_hash_cachep, ll_xattr_fini(), lprocfs_remove(), lustre_register_client_fill_super(), lustre_register_client_process_config(), lustre_register_kill_super_cb(), proc_lustre_fs_root, and vvp_global_fini().
static int __init lustre_init (void) [static]
Definition at line 105 of file super25.c.
References CDEBUG, CERROR, cfs_get_random_bytes(), cfs_srand(), cl_env_alloc(), cl_env_put(), cl_inode_fini_env, cl_inode_fini_refcheck, CLASSERT, D_INFO, GOTO, lu_context::lc_cookie, LCT_NOREF, LCT_REMEMBER, lu_env::le_ctx, ll_file_data_slab, ll_fill_super(), ll_inode_cachep, ll_kill_super(), ll_process_config(), ll_remote_perm_cachep, ll_rmtperm_hash_cachep, ll_xattr_init(), LNET_NETTYP(), LNET_NIDADDR(), LNET_NIDNET(), LNetGetId(), LOLND, lprocfs_register(), lprocfs_remove(), lustre_register_client_fill_super(), lustre_register_client_process_config(), lustre_register_kill_super_cb(), lustre_super_operations, LUSTRE_VOLATILE_HDR, LUSTRE_VOLATILE_HDR_LEN, lnet_process_id_t::nid, proc_lustre_fs_root, proc_lustre_root, REMOTE_PERM_HASHSIZE, RETURN, seed, vvp_global_fini(), and vvp_global_init().
void lustre_register_client_process_config (int(*)(struct lustre_cfg *lcfg) cpc)
Definition at line 1015 of file obd_config.c.
References client_process_config.
Referenced by lustre_exit(), and lustre_init().
MODULE_AUTHOR (" OpenSFS, Inc.< http://www.lustre.org/>")
MODULE_DESCRIPTION ("Lustre Client File System")
module_exit (lustre_exit)
module_init (lustre_init)
MODULE_LICENSE ("GPL")
MODULE_VERSION (LUSTRE_VERSION_STRING)
Variable Documentation
struct kmem_cache* ll_inode_cachep [static]
Definition at line 50 of file super25.c.
Referenced by ll_alloc_inode(), ll_destroy_inode(), lustre_exit(), and lustre_init().
struct super_operations lustre_super_operations
Initial value:
{
        .alloc_inode   = ll_alloc_inode,
        .destroy_inode = ll_destroy_inode,
        .clear_inode   = ll_clear_inode,
        .delete_inode  = ll_delete_inode,
        .put_super     = ll_put_super,
        .statfs        = ll_statfs,
        .umount_begin  = ll_umount_begin,
        .remount_fs    = ll_remount_fs,
        .show_options  = ll_show_options,
}
Definition at line 85 of file super25.c.
Referenced by client_common_fill_super(), and lustre_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.