Lustre: lustre/utils/gss/svcgssd.h File Reference
lustre/utils/gss/svcgssd.h File Reference
#include <sys/types.h>
#include <sys/queue.h>
#include <gssapi/gssapi.h>
Defines
#define GSSD_SERVICE_NAME "lustre"
#define GSSD_SERVICE_MGS "lustre_mgs"
#define GSSD_SERVICE_MDS "lustre_mds"
#define GSSD_SERVICE_OSS "lustre_oss"
#define LUSTRE_ROOT_NAME "lustre_root"
#define LUSTRE_ROOT_NAMELEN 11
Functions
int handle_nullreq (FILE *f)
void svcgssd_run (void)
int gssd_prepare_creds (int must_srv_mgs, int must_srv_mds, int must_srv_oss)
gss_cred_id_t gssd_select_svc_cred (int lustre_svc)
Variables
char * mds_local_realm
char * oss_local_realm
Define Documentation
#define GSSD_SERVICE_MDS "lustre_mds"
Definition at line 50 of file svcgssd.h.
#define GSSD_SERVICE_MGS "lustre_mgs"
Definition at line 49 of file svcgssd.h.
#define GSSD_SERVICE_NAME "lustre"
Definition at line 46 of file svcgssd.h.
#define GSSD_SERVICE_OSS "lustre_oss"
Definition at line 51 of file svcgssd.h.
#define LUSTRE_ROOT_NAME "lustre_root"
Definition at line 52 of file svcgssd.h.
#define LUSTRE_ROOT_NAMELEN 11
Definition at line 53 of file svcgssd.h.
Function Documentation
int gssd_prepare_creds (int must_srv_mgs, int must_srv_mds, int must_srv_oss)
Definition at line 281 of file gss_util.c.
References gssd_acquire_cred(), gssd_cred_mds, gssd_cred_mds_valid, gssd_cred_mgs, gssd_cred_mgs_valid, gssd_cred_oss, gssd_cred_oss_valid, GSSD_SERVICE_MDS, GSSD_SERVICE_MGS, GSSD_SERVICE_OSS, mds_local_realm, mgs_local_realm, oss_local_realm, and printerr.
Referenced by main().
gss_cred_id_t gssd_select_svc_cred (int lustre_svc)
Definition at line 321 of file gss_util.c.
References gssd_cred_mds, gssd_cred_mds_valid, gssd_cred_mgs, gssd_cred_mgs_valid, gssd_cred_oss, gssd_cred_oss_valid, LUSTRE_GSS_SVC_MDS, LUSTRE_GSS_SVC_MGS, LUSTRE_GSS_SVC_OSS, and printerr.
Referenced by handle_nullreq().
int handle_nullreq (FILE * f)
Definition at line 474 of file svcgssd_proc.c.
References do_svc_downcall(), get_ids(), GSS_C_NO_CONTEXT, GSS_S_BAD_NAME, GSS_S_COMPLETE, GSS_S_CONTINUE_NEEDED, GSS_S_FAILURE, gssd_select_svc_cred(), out_handle(), pgsserr, print_hexl(), printerr, qword_get(), readline(), send_response(), serialize_context_for_kernel(), and TOKEN_BUF_SIZE.
Referenced by svcgssd_run().
void svcgssd_run (void)
Definition at line 61 of file svcgssd_main_loop.c.
References handle_nullreq(), NULLRPC_FILE, printerr, and ret.
Referenced by main().
Variable Documentation
char* mds_local_realm
Definition at line 92 of file gss_util.c.
Referenced by get_ids(), and gssd_prepare_creds().
char* oss_local_realm
Definition at line 93 of file gss_util.c.
Referenced by gssd_prepare_creds().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.