Lustre: lustre/utils/gss/svcgssd_proc.c File Reference
lustre/utils/gss/svcgssd_proc.c File Reference
#include <sys/param.h>
#include <sys/stat.h>
#include <inttypes.h>
#include <pwd.h>
#include <stdio.h>
#include <unistd.h>
#include <ctype.h>
#include <string.h>
#include <fcntl.h>
#include <errno.h>
#include "svcgssd.h"
#include "gss_util.h"
#include "err_util.h"
#include "context.h"
#include "cacheio.h"
#include "lsupport.h"
Data Structures
struct svc_cred
struct gss_verifier
struct gss_union_ctx_id_t
Defines
#define SVCGSSD_CONTEXT_CHANNEL "/proc/net/rpc/auth.sptlrpc.context/channel"
#define SVCGSSD_INIT_CHANNEL "/proc/net/rpc/auth.sptlrpc.init/channel"
#define TOKEN_BUF_SIZE 8192
#define RPCSEC_GSS_SEQ_WIN 5
#define rpc_auth_ok 0
#define rpc_autherr_badcred 1
#define rpc_autherr_rejectedcred 2
#define rpc_autherr_badverf 3
#define rpc_autherr_rejectedverf 4
#define rpc_autherr_tooweak 5
#define rpcsec_gsserr_credproblem 13
#define rpcsec_gsserr_ctxproblem 14
Typedefs
typedef struct gss_union_ctx_id_t gss_union_ctx_id_desc
Functions
char * mech2file (gss_OID mech)
static int do_svc_downcall (gss_buffer_desc *out_handle, struct svc_cred *cred, gss_OID mech, gss_buffer_desc *context_token)
static int send_response (FILE *f, gss_buffer_desc *in_handle, gss_buffer_desc *in_token, u_int32_t maj_stat, u_int32_t min_stat, gss_buffer_desc *out_handle, gss_buffer_desc *out_token)
static int get_ids (gss_name_t client_name, gss_OID mech, struct svc_cred *cred, lnet_nid_t nid, uint32_t lustre_svc)
int handle_nullreq (FILE *f)
Define Documentation
#define rpc_auth_ok 0
Definition at line 163 of file svcgssd_proc.c.
#define rpc_autherr_badcred 1
Definition at line 164 of file svcgssd_proc.c.
#define rpc_autherr_badverf 3
Definition at line 166 of file svcgssd_proc.c.
#define rpc_autherr_rejectedcred 2
Definition at line 165 of file svcgssd_proc.c.
#define rpc_autherr_rejectedverf 4
Definition at line 167 of file svcgssd_proc.c.
#define rpc_autherr_tooweak 5
Definition at line 168 of file svcgssd_proc.c.
#define RPCSEC_GSS_SEQ_WIN 5
Definition at line 119 of file svcgssd_proc.c.
#define rpcsec_gsserr_credproblem 13
Definition at line 169 of file svcgssd_proc.c.
#define rpcsec_gsserr_ctxproblem 14
Definition at line 170 of file svcgssd_proc.c.
#define SVCGSSD_CONTEXT_CHANNEL "/proc/net/rpc/auth.sptlrpc.context/channel"
Definition at line 61 of file svcgssd_proc.c.
Referenced by do_svc_downcall().
#define SVCGSSD_INIT_CHANNEL "/proc/net/rpc/auth.sptlrpc.init/channel"
Definition at line 62 of file svcgssd_proc.c.
Referenced by send_response().
#define TOKEN_BUF_SIZE 8192
Definition at line 64 of file svcgssd_proc.c.
Referenced by handle_nullreq(), and send_response().
Typedef Documentation
typedef struct gss_union_ctx_id_t gss_union_ctx_id_desc
Function Documentation
static int do_svc_downcall (gss_buffer_desc * out_handle, struct svc_cred * cred, gss_OID mech, gss_buffer_desc * context_token) [static]
Definition at line 77 of file svcgssd_proc.c.
References svc_cred::cr_gid, svc_cred::cr_mapped_uid, svc_cred::cr_remote, svc_cred::cr_uid, svc_cred::cr_usr_mds, svc_cred::cr_usr_oss, svc_cred::cr_usr_root, fname, mech2file(), printerr, qword_eol(), qword_print(), qword_printhex(), qword_printint(), and SVCGSSD_CONTEXT_CHANNEL.
Referenced by handle_nullreq().
static int get_ids (gss_name_t client_name, gss_OID mech, struct svc_cred * cred, lnet_nid_t nid, uint32_t lustre_svc) [static]
Definition at line 306 of file svcgssd_proc.c.
References assert, svc_cred::cr_gid, svc_cred::cr_mapped_uid, svc_cred::cr_remote, svc_cred::cr_uid, svc_cred::cr_usr_mds, svc_cred::cr_usr_oss, svc_cred::cr_usr_root, GSS_S_COMPLETE, GSSD_SERVICE_MDS, GSSD_SERVICE_MGS, GSSD_SERVICE_OSS, lnet_nid2hostname(), lookup_mapping(), LUSTRE_GSS_SVC_MDS, LUSTRE_GSS_SVC_MGS, LUSTRE_GSS_SVC_OSS, LUSTRE_ROOT_NAME, lustre_svc_name, mds_local_realm, pgsserr, and printerr.
Referenced by handle_nullreq().
int handle_nullreq (FILE * f)
Definition at line 474 of file svcgssd_proc.c.
References do_svc_downcall(), get_ids(), GSS_C_NO_CONTEXT, GSS_S_BAD_NAME, GSS_S_COMPLETE, GSS_S_CONTINUE_NEEDED, GSS_S_FAILURE, gssd_select_svc_cred(), out_handle(), pgsserr, print_hexl(), printerr, qword_get(), readline(), send_response(), serialize_context_for_kernel(), and TOKEN_BUF_SIZE.
Referenced by svcgssd_run().
char* mech2file (gss_OID mech)
Definition at line 63 of file svcgssd_mech2file.c.
References mech2file::filename, g_OID_equal, and mech2file::mech.
Referenced by do_svc_downcall().
static int send_response (FILE * f, gss_buffer_desc * in_handle, gss_buffer_desc * in_token, u_int32_t maj_stat, u_int32_t min_stat, gss_buffer_desc * out_handle, gss_buffer_desc * out_token) [static]
Definition at line 122 of file svcgssd_proc.c.
References buf, printerr, qword_addeol(), qword_addhex(), qword_addint(), qword_adduint(), SVCGSSD_INIT_CHANNEL, and TOKEN_BUF_SIZE.
Referenced by handle_nullreq().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.