Lustre: lustre/utils/gss/svcgssd.c File Reference
lustre/utils/gss/svcgssd.c File Reference
#include "config.h"
#include <sys/param.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <sys/socket.h>
#include <fcntl.h>
#include <errno.h>
#include <unistd.h>
#include <err.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <signal.h>
#include <dirent.h>
#include "svcgssd.h"
#include "gss_util.h"
#include "err_util.h"
#include "lsupport.h"
Functions
void closeall (int min)
static void mydaemon (int nochdir, int noclose)
static void release_parent ()
void sig_die (int signal)
void sig_hup (int signal)
static void usage (char *progname)
int main (int argc, char *argv[])
Variables
int pipefds [2] = { -1, -1}
Function Documentation
void closeall (int min)
Definition at line 63 of file svcgssd.c.
References dir.
Referenced by mydaemon().
int main (int argc, char * argv[])
Definition at line 187 of file svcgssd.c.
References cleanup_mapping(), fg, gssd_check_mechs(), gssd_get_local_realm(), gssd_init_unique(), gssd_prepare_creds(), GSSD_SVC, initerr(), mydaemon(), opt, optarg, printerr, progname, release_parent(), sig_die(), sig_hup(), svcgssd_run(), usage, and verbosity.
static void mydaemon (int nochdir, int noclose) [static]
Definition at line 93 of file svcgssd.c.
References closeall(), pipefds, printerr, and status.
Referenced by main().
static void release_parent () [static]
Definition at line 149 of file svcgssd.c.
References __attribute__(), pipefds, and status.
Referenced by main().
void sig_die (int signal)
Definition at line 162 of file svcgssd.c.
References cleanup_mapping(), and printerr.
void sig_hup (int signal)
Definition at line 171 of file svcgssd.c.
References printerr.
static void usage (char * progname) [static]
Definition at line 179 of file svcgssd.c.
Variable Documentation
int pipefds[2] = { -1, -1}
Definition at line 90 of file svcgssd.c.
Referenced by mydaemon(), and release_parent().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.