Lustre: lustre/llite/symlink.c File Reference
lustre/llite/symlink.c File Reference
#include <linux/fs.h>
#include <linux/mm.h>
#include <linux/stat.h>
#include <linux/version.h>
#include "llite_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_LLITE
Functions
static int ll_readlink_internal (struct inode *inode, struct ptlrpc_request **request, char **symname)
static const char * ll_follow_link (struct dentry *dentry, void **cookie)
static void ll_put_link (struct inode *unused, void *cookie)
Variables
struct inode_operations ll_fast_symlink_inode_operations
Define Documentation
#define DEBUG_SUBSYSTEM S_LLITE
Definition at line 41 of file symlink.c.
Function Documentation
static const char* ll_follow_link (struct dentry * dentry, void ** cookie) [static]
Definition at line 159 of file symlink.c.
References CDEBUG, D_VFSTRACE, ENTRY, ll_inode_size_lock(), ll_inode_size_unlock(), ll_readlink_internal(), ptlrpc_req_finished(), and RETURN.
static void ll_put_link (struct inode * unused, void * cookie) [static]
Definition at line 187 of file symlink.c.
References ptlrpc_req_finished().
static int ll_readlink_internal (struct inode * inode, struct ptlrpc_request ** request, char ** symname) [static]
Definition at line 45 of file symlink.c.
References CDEBUG, CERROR, D_INODE, DFID, ENTRY, GOTO, LASSERT, ll_finish_md_op_data(), ll_get_fsname(), ll_i2info(), ll_i2sbi(), ll_inode2fid(), ll_sb_info::ll_md_exp, ll_prep_md_op_data(), ll_inode_info::lli_symlink_name, LUSTRE_OPC_ANY, mdt_body::mbo_eadatasize, mdt_body::mbo_valid, md_getattr(), min_t, OBD_ALLOC, OBD_MD_LINKNAME, md_op_data::op_data, md_op_data::op_valid, PFID, req_capsule_server_get(), RETURN, RMF_MDT_BODY, RMF_MDT_MD, and strnlen.
Referenced by ll_follow_link().
Variable Documentation
struct inode_operations ll_fast_symlink_inode_operations
Initial value:
 {
        .readlink       = generic_readlink,
        .setattr        = ll_setattr,
        .follow_link    = ll_follow_link,
        .put_link       = ll_put_link,
        .getattr        = ll_getattr,
        .permission     = ll_inode_permission,
        .setxattr       = ll_setxattr,
        .getxattr       = ll_getxattr,
        .listxattr      = ll_listxattr,
        .removexattr    = ll_removexattr,
}
Definition at line 193 of file symlink.c.
Referenced by ll_read_inode2().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.