Lustre: lustre/target/tgt_handler.c File Reference
lustre/target/tgt_handler.c File Reference
#include <linux/user_namespace.h>
#include <obd.h>
#include <obd_class.h>
#include <obd_cksum.h>
#include <md_object.h>
#include <lustre_lfsck.h>
#include <lustre_nodemap.h>
#include "tgt_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_CLASS
Functions
char * tgt_name (struct lu_target *tgt)
static int tgt_mdt_body_unpack (struct tgt_session_info *tsi, __u32 flags)
int tgt_validate_obdo (struct tgt_session_info *tsi, struct obdo *oa)
Validate oa from client.
static int tgt_io_data_unpack (struct tgt_session_info *tsi, struct ost_id *oi)
static int tgt_ost_body_unpack (struct tgt_session_info *tsi, __u32 flags)
static int tgt_request_preprocess (struct tgt_session_info *tsi, struct tgt_handler *h, struct ptlrpc_request *req)
static int tgt_handle_request0 (struct tgt_session_info *tsi, struct tgt_handler *h, struct ptlrpc_request *req)
static int tgt_filter_recovery_request (struct ptlrpc_request *req, struct obd_device *obd, int *process)
static int tgt_handle_recovery (struct ptlrpc_request *req, int reply_fail_id)
static struct tgt_handler * tgt_handler_find_check (struct ptlrpc_request *req)
static int process_req_last_xid (struct ptlrpc_request *req)
int tgt_request_handle (struct ptlrpc_request *req)
int tgt_hpreq_handler (struct ptlrpc_request *req)
Assign high priority operations to the request if needed.
void tgt_counter_incr (struct obd_export *exp, int opcode)
static void tgt_init_sec_none (struct obd_connect_data *reply)
static int tgt_init_sec_level (struct ptlrpc_request *req)
int tgt_connect_check_sptlrpc (struct ptlrpc_request *req, struct obd_export *exp)
int tgt_adapt_sptlrpc_conf (struct lu_target *tgt, int initial)
int tgt_connect (struct tgt_session_info *tsi)
int tgt_disconnect (struct tgt_session_info *tsi)
int tgt_obd_ping (struct tgt_session_info *tsi)
int tgt_obd_log_cancel (struct tgt_session_info *tsi)
int tgt_send_buffer (struct tgt_session_info *tsi, struct lu_rdbuf *rdbuf)
int tgt_sendpage (struct tgt_session_info *tsi, struct lu_rdpg *rdpg, int nob)
static int tgt_obd_idx_read (struct tgt_session_info *tsi)
int tgt_sync (const struct lu_env *env, struct lu_target *tgt, struct dt_object *obj, __u64 start, __u64 end)
static int tgt_blocking_ast (struct ldlm_lock *lock, struct ldlm_lock_desc *desc, void *data, int flag)
Unified target BAST.
int tgt_enqueue (struct tgt_session_info *tsi)
int tgt_convert (struct tgt_session_info *tsi)
int tgt_bl_callback (struct tgt_session_info *tsi)
int tgt_cp_callback (struct tgt_session_info *tsi)
int tgt_llog_open (struct tgt_session_info *tsi)
int tgt_llog_close (struct tgt_session_info *tsi)
int tgt_llog_destroy (struct tgt_session_info *tsi)
int tgt_llog_read_header (struct tgt_session_info *tsi)
int tgt_llog_next_block (struct tgt_session_info *tsi)
int tgt_llog_prev_block (struct tgt_session_info *tsi)
static int tgt_sec_ctx_handle (struct tgt_session_info *tsi)
void tgt_register_lfsck_in_notify (int(*notify)(const struct lu_env *, struct dt_device *, struct lfsck_request *, struct thandle *))
void tgt_register_lfsck_query (int(*query)(const struct lu_env *, struct dt_device *, struct lfsck_request *, struct lfsck_reply *, struct lfsck_query *))
static int tgt_handle_lfsck_notify (struct tgt_session_info *tsi)
static int tgt_handle_lfsck_query (struct tgt_session_info *tsi)
int tgt_io_thread_init (struct ptlrpc_thread *thread)
void tgt_io_thread_done (struct ptlrpc_thread *thread)
int tgt_extent_lock (struct ldlm_namespace *ns, struct ldlm_res_id *res_id, __u64 start, __u64 end, struct lustre_handle *lh, int mode, __u64 *flags)
Helper function for getting server side [start, start+count] DLM lock if asked by client.
void tgt_extent_unlock (struct lustre_handle *lh, enum ldlm_mode mode)
int tgt_brw_lock (struct ldlm_namespace *ns, struct ldlm_res_id *res_id, struct obd_ioobj *obj, struct niobuf_remote *nb, struct lustre_handle *lh, enum ldlm_mode mode)
void tgt_brw_unlock (struct obd_ioobj *obj, struct niobuf_remote *niob, struct lustre_handle *lh, enum ldlm_mode mode)
static __u32 tgt_checksum_bulk (struct lu_target *tgt, struct ptlrpc_bulk_desc *desc, int opc, cksum_type_t cksum_type)
int tgt_brw_read (struct tgt_session_info *tsi)
static void tgt_warn_on_cksum (struct ptlrpc_request *req, struct ptlrpc_bulk_desc *desc, struct niobuf_local *local_nb, int npages, u32 client_cksum, u32 server_cksum, bool mmap)
int tgt_brw_write (struct tgt_session_info *tsi)
bool req_can_reconstruct (struct ptlrpc_request *req, struct tg_reply_data *trd)
Variables
struct tgt_handler tgt_obd_handlers []
static struct ldlm_callback_suite tgt_dlm_cbs
struct tgt_handler tgt_dlm_handlers []
struct tgt_handler tgt_llog_handlers []
struct tgt_handler tgt_sec_ctx_handlers []
int(* tgt_lfsck_in_notify)(const struct lu_env *env, struct dt_device *key, struct lfsck_request *lr, struct thandle *th) = NULL
static int(* tgt_lfsck_query)(const struct lu_env *env, struct dt_device *key, struct lfsck_request *req, struct lfsck_reply *rep, struct lfsck_query *que) = NULL
struct tgt_handler tgt_lfsck_handlers []
Define Documentation
#define DEBUG_SUBSYSTEM S_CLASS
Definition at line 35 of file tgt_handler.c.
Function Documentation
static int process_req_last_xid (struct ptlrpc_request * req) [static]
Definition at line 607 of file tgt_handler.c.
References __u64, D_ERROR, DEBUG_REQ, ENTRY, obd_export::exp_last_xid, lustre_msg_get_flags(), lustre_msg_get_last_xid(), lustre_msg_get_tag(), MSG_REPLAY, MSG_RESENT, RETURN, ptlrpc_request::rq_export, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_xid, tgt_handle_received_xid(), tgt_handle_tag(), and tgt_is_multimodrpcs_client().
Referenced by tgt_request_handle().
bool req_can_reconstruct (struct ptlrpc_request * req, struct tg_reply_data * trd)
Definition at line 2310 of file tgt_handler.c.
References lsd_client_data::lcd_last_close_result, lsd_client_data::lcd_last_close_transno, lsd_client_data::lcd_last_close_xid, lsd_client_data::lcd_last_data, lsd_client_data::lcd_last_result, lsd_client_data::lcd_last_transno, lsd_client_data::lcd_last_xid, lsd_client_data::lcd_pre_versions, lsd_reply_data::lrd_data, lsd_reply_data::lrd_result, lsd_reply_data::lrd_transno, lsd_reply_data::lrd_xid, lustre_msg_get_opc(), MDS_CLOSE, ptlrpc_request::rq_export, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_xid, tg_export_data::ted_lcd, tg_export_data::ted_lcd_lock, tgt_is_multimodrpcs_client(), tgt_lookup_reply(), tg_reply_data::trd_pre_versions, and tg_reply_data::trd_reply.
Referenced by mdt_check_resent(), mdt_intent_fixup_resent(), and tgt_handle_recovery().
int tgt_adapt_sptlrpc_conf (struct lu_target * tgt, int initial)
Definition at line 1010 of file tgt_handler.c.
References CERROR, lu_target::lut_obd, lu_target::lut_sptlrpc_lock, lu_target::lut_sptlrpc_rset, sptlrpc_conf_target_get_rules(), sptlrpc_rule_set_free(), sptlrpc_rule_set_init(), sptlrpc_target_update_exp_flavor(), tgt_name(), and unlikely.
Referenced by mdt_init0(), mdt_obd_set_info_async(), ofd_init0(), ofd_set_info_async(), and ofd_set_info_hdl().
int tgt_bl_callback (struct tgt_session_info * tsi)
Definition at line 1433 of file tgt_handler.c.
References err_serious().
static int tgt_blocking_ast (struct ldlm_lock * lock, struct ldlm_lock_desc * desc, void * data, int flag) [static]
Unified target BAST.
Ensure data and metadata are synced to disk when lock is canceled if Sync on Cancel (SOC) is enabled. If it's extent lock, normally sync obj is enough, but if it's cross-MDT lock, because remote object version is not set, a filesystem sync is needed.
Parameters:
lock server side lock
desc lock desc
data ldlm_cb_set_arg
flag indicates whether this cancelling or blocking callback
Return values:
0 on success
negative number on error
Definition at line 1312 of file tgt_handler.c.
References __u64, ALWAYS_SYNC_ON_CANCEL, BLOCKING_SYNC_ON_CANCEL, CDEBUG, CERROR, class_exp2obd(), D_ERROR, DFID, dt_object::do_lu, dt_locate(), dt_object_exists(), ldlm_extent::end, end, ENTRY, exp_connect_flags(), GOTO, ldlm_lock::l_export, ldlm_policy_data::l_extent, ldlm_lock::l_granted_mode, ldlm_lock::l_policy_data, ldlm_lock::l_resource, LCK_EX, LCK_GROUP, LCK_PW, LCT_DT_THREAD, LDLM_CB_CANCELING, LDLM_EXTENT, ldlm_is_cbpending, LPU64, ldlm_resource::lr_name, ldlm_resource::lr_type, lr_server_data::lsd_osd_index, lu_env_fini(), lu_env_init(), lu_object_put(), lu_target::lut_bottom, lu_target::lut_lsd, lu_target::lut_sync_lock_cancel, OBD_CONNECT_MDS_MDS, obd_device::obd_name, OBD_OBJECT_EOF, ost_fid_from_resid(), PFID, RETURN, ldlm_extent::start, start, tgt_name(), tgt_sync(), and unlikely.
int tgt_brw_lock (struct ldlm_namespace * ns, struct ldlm_res_id * res_id, struct obd_ioobj * obj, struct niobuf_remote * nb, struct lustre_handle * lh, enum ldlm_mode mode)
Definition at line 1716 of file tgt_handler.c.
References __u64, ENTRY, obd_ioobj::ioo_bufcnt, LASSERT, LCK_PR, LCK_PW, lustre_handle_is_used(), OBD_BRW_SRVLOCK, RETURN, and tgt_extent_lock().
Referenced by tgt_brw_read(), and tgt_brw_write().
int tgt_brw_read (struct tgt_session_info * tsi)
Definition at line 1837 of file tgt_handler.c.
References ptlrpc_bulk_frag_ops::add_kiov_frag, ptlrpc_bulk_desc::bd_frag_ops, CDEBUG, CERROR, CFS_FAIL_PRECHECK(), cfs_fail_val, cfs_time_current_sec(), cfs_time_seconds(), cksum_type_pack(), cksum_type_unpack(), D_INFO, D_PAGE, DOSTID, ENTRY, obd_export::exp_client_uuid, obd_export::exp_obd, GOTO, obd_ioobj::ioo_oid, ioobj_max_brw_get, l_wait_event, LASSERT, LCK_PR, LCONSOLE_WARN, libcfs_id2str(), likely, niobuf_local::lnb_rc, tgt_thread_big_cache::local, LWI_INTR, LWI_TIMEOUT_INTR, obdo::o_flags, obdo::o_valid, ost_body::oa, OBD_BRW_READ, obd_commitrw(), obd_device::obd_evict_inprogress, obd_device::obd_evict_inprogress_waitq, obd_export_nid2str(), OBD_FAIL_CHECK, OBD_FAIL_OST_BRW_PAUSE_BULK, OBD_FAIL_OST_BRW_READ_BULK, OBD_FAIL_OST_DROP_REQ, OBD_FAIL_OST_READ_SIZE, OBD_FAIL_PTLRPC_CLIENT_BULK_CB2, OBD_FAIL_TIMEOUT, OBD_MD_FLCKSUM, OBD_MD_FLFLAGS, obd_device::obd_name, obd_device::obd_namespace, obd_preprw(), obd_timeout, obd_uuid2str(), OST_BULK_PORTAL, OST_IO_PORTAL, OST_READ, POSTID, PTLRPC_BULK_BUF_KIOV, ptlrpc_bulk_kiov_nopin_ops, PTLRPC_BULK_PUT_SOURCE, ptlrpc_free_bulk(), ptlrpc_lprocfs_brw(), PTLRPC_MAX_BRW_PAGES, ptlrpc_req2svc(), ptlrpc_req_drop_rs(), req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_NIOBUF_REMOTE, RMF_OBD_IOOBJ, RMF_OST_BODY, ptlrpc_request::rq_bulk_read, ptlrpc_request::rq_deadline, ptlrpc_request::rq_export, ptlrpc_request::rq_no_reply, ptlrpc_request::rq_peer, ptlrpc_request::rq_pill, tgt_brw_lock(), tgt_brw_unlock(), tgt_checksum_bulk(), tgt_drop_id(), tgt_name(), tgt_ses_req(), tgt_session_info::tsi_env, tgt_session_info::tsi_exp, tgt_session_info::tsi_ost_body, tgt_session_info::tsi_pill, tgt_session_info::tsi_resid, tgt_session_info::tsi_tgt, and unlikely.
void tgt_brw_unlock (struct obd_ioobj * obj, struct niobuf_remote * niob, struct lustre_handle * lh, enum ldlm_mode mode)
Definition at line 1742 of file tgt_handler.c.
References ENTRY, EXIT, obd_ioobj::ioo_bufcnt, LASSERT, LCK_PR, LCK_PW, lustre_handle_is_used(), OBD_BRW_SRVLOCK, niobuf_remote::rnb_flags, and tgt_extent_unlock().
Referenced by tgt_brw_read(), and tgt_brw_write().
int tgt_brw_write (struct tgt_session_info * tsi)
Definition at line 2073 of file tgt_handler.c.
References ptlrpc_bulk_frag_ops::add_kiov_frag, ptlrpc_bulk_desc::bd_frag_ops, ptlrpc_connection::c_peer, ptlrpc_connection::c_self, CDEBUG, CERROR, CFS_FAIL_TIMEOUT, cfs_fail_val, cfs_time_current_sec(), cksum_type_pack(), cksum_type_unpack(), D_CACHE, D_INFO, DEBUG_REQ, DOSTID, ENTRY, err_serious(), obd_export::exp_client_uuid, obd_export::exp_connection, obd_export::exp_obd, GOTO, obd_ioobj::ioo_oid, ioobj_max_brw_get, LASSERT, LCK_PW, LCONSOLE_WARN, libcfs_id2str(), niobuf_local::lnb_len, niobuf_local::lnb_page, niobuf_local::lnb_page_offset, niobuf_local::lnb_rc, tgt_thread_big_cache::local, lustre_msg_get_flags(), memory_pressure_clr(), memory_pressure_set(), MSG_REPLAY, MSG_RESENT, lnet_process_id_t::nid, obdo::o_flags, obdo::o_valid, ost_body::oa, OBD_BRW_MEMALLOC, OBD_BRW_WRITE, OBD_CKSUM_CRC32, obd_commitrw(), obd_export_nid2str(), OBD_FAIL_CHECK, OBD_FAIL_OST_BRW_PAUSE_BULK, OBD_FAIL_OST_BRW_PAUSE_PACK, OBD_FAIL_OST_BRW_WRITE_BULK, OBD_FAIL_OST_BRW_WRITE_BULK2, OBD_FAIL_OST_DROP_REQ, OBD_FAIL_OST_ENOSPC, OBD_FAIL_OST_EROFS, OBD_FAIL_TIMEOUT, OBD_FL_CKSUM_ALL, OBD_FL_MMAP, OBD_MD_FLATIME, OBD_MD_FLCKSUM, OBD_MD_FLFLAGS, OBD_MD_FLGRANT, OBD_MD_FLMTIME, obd_device::obd_name, obd_device::obd_namespace, obd_preprw(), obd_timeout, obd_uuid2str(), OST_BULK_PORTAL, OST_IO_PORTAL, OST_WRITE, POSTID, PTLRPC_BULK_BUF_KIOV, PTLRPC_BULK_GET_SINK, ptlrpc_bulk_kiov_nopin_ops, ptlrpc_free_bulk(), ptlrpc_lprocfs_brw(), PTLRPC_MAX_BRW_PAGES, ptlrpc_req2svc(), ptlrpc_req_drop_rs(), RCL_CLIENT, RCL_SERVER, req_capsule_client_get(), req_capsule_get_size(), req_capsule_server_get(), req_capsule_server_pack(), req_capsule_set_size(), RETURN, RMF_NIOBUF_REMOTE, RMF_OBD_IOOBJ, RMF_OST_BODY, RMF_RCS, niobuf_remote::rnb_len, ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_deadline, ptlrpc_request::rq_export, ptlrpc_request::rq_no_reply, ptlrpc_request::rq_peer, ptlrpc_request::rq_pill, ptlrpc_request::rq_reqmsg, tgt_brw_lock(), tgt_brw_unlock(), tgt_checksum_bulk(), tgt_drop_id(), tgt_name(), tgt_ses_req(), tgt_warn_on_cksum(), tgt_session_info::tsi_env, tgt_session_info::tsi_ost_body, tgt_session_info::tsi_resid, tgt_session_info::tsi_tgt, and unlikely.
static __u32 tgt_checksum_bulk (struct lu_target * tgt, struct ptlrpc_bulk_desc * desc, int opc, cksum_type_t cksum_type) [static]
Definition at line 1757 of file tgt_handler.c.
References BD_GET_KIOV, ptlrpc_bulk_desc::bd_iov_count, ptlrpc_bulk_desc::bd_type, bufsize, CDEBUG, CERROR, cfs_crypto_hash_final(), cfs_crypto_hash_init(), cfs_crypto_hash_name(), cfs_crypto_hash_update_page(), cksum, cksum_obd2cfs(), D_INFO, LASSERT, OBD_FAIL_CHECK, OBD_FAIL_OST_CHECKSUM_RECEIVE, OBD_FAIL_OST_CHECKSUM_SEND, OST_READ, OST_WRITE, ptlrpc_is_bulk_desc_kiov(), tgt_name(), and tgt_page_to_corrupt.
Referenced by tgt_brw_read(), and tgt_brw_write().
int tgt_connect (struct tgt_session_info * tsi)
Definition at line 1039 of file tgt_handler.c.
References class_export_get(), ENTRY, obd_export::exp_connect_data, exp_connect_flags_ptr(), obd_export::exp_lock, GOTO, obd_disconnect(), obd_connect_data::ocd_brw_size, obd_connect_data::ocd_connect_flags, req_capsule_server_get(), RETURN, RMF_CONNECT_DATA, tgt_connect_check_sptlrpc(), tgt_init_sec_level(), tgt_ses_req(), tgt_session_info::tsi_exp, and tgt_session_info::tsi_pill.
Referenced by mdt_tgt_connect(), and mgs_connect().
int tgt_connect_check_sptlrpc (struct ptlrpc_request * req, struct obd_export * exp)
Definition at line 947 of file tgt_handler.c.
References ptlrpc_connection::c_peer, CERROR, obd_export::exp_connection, obd_export::exp_flvr, obd_export::exp_lock, obd_export::exp_obd, obd_export::exp_sp_peer, LASSERT, libcfs_nid2str(), LNET_NETTYP(), LNET_NIDNET(), LOLND, LUSTRE_ECHO_NAME, LUSTRE_MGS_NAME, lu_target::lut_obd, lu_target::lut_slice, lu_target::lut_sptlrpc_lock, lu_target::lut_sptlrpc_rset, lnet_process_id_t::nid, obd_device::obd_type, ptlrpc_request::rq_flvr, ptlrpc_request::rq_peer, sptlrpc_flavor::sf_rpc, SPTLRPC_FLVR_ANY, SPTLRPC_FLVR_INVALID, SPTLRPC_FLVR_NULL, sptlrpc_part2name(), sptlrpc_target_choose_flavor(), sptlrpc_target_export_check(), tgt_name(), obd_type::typ_name, and unlikely.
Referenced by tgt_connect().
int tgt_convert (struct tgt_session_info * tsi)
Definition at line 1419 of file tgt_handler.c.
References ENTRY, err_serious(), LASSERT, RETURN, ptlrpc_request::rq_status, tgt_ses_req(), and tgt_session_info::tsi_dlm_req.
void tgt_counter_incr (struct obd_export * exp, int opcode)
Definition at line 818 of file tgt_handler.c.
References obd_export::exp_nid_stats, obd_export::exp_obd, lprocfs_counter_incr(), nid_stat::nid_stats, and obd_device::obd_stats.
Referenced by mgs_exception(), mgs_obd_connect(), mgs_obd_disconnect(), mgs_obd_reconnect(), mgs_target_del(), and mgs_target_reg().
int tgt_cp_callback (struct tgt_session_info * tsi)
Definition at line 1438 of file tgt_handler.c.
References err_serious().
int tgt_disconnect (struct tgt_session_info * tsi)
Definition at line 1076 of file tgt_handler.c.
References ENTRY, err_serious(), RETURN, and tgt_ses_req().
Referenced by mgs_disconnect().
int tgt_enqueue (struct tgt_session_info * tsi)
Definition at line 1385 of file tgt_handler.c.
References ENTRY, err_serious(), obd_export::exp_obd, LASSERT, ldlm_handle_enqueue0(), LUT_FAIL_CLASS, LUT_FAIL_MDT, LUT_FAIL_MGT, LUT_FAIL_OST, OBD_FAIL_LDLM_REPLY, OBD_FAIL_MDS_LDLM_REPLY_NET, OBD_FAIL_MGS_LDLM_REPLY_NET, OBD_FAIL_OST_LDLM_REPLY_NET, obd_device::obd_namespace, RETURN, ptlrpc_request::rq_status, tgt_ses_req(), tgt_session_info::tsi_dlm_req, tgt_session_info::tsi_exp, and tgt_session_info::tsi_reply_fail_id.
int tgt_extent_lock (struct ldlm_namespace * ns, struct ldlm_res_id * res_id, __u64 start, __u64 end, struct lustre_handle * lh, int mode, __u64 * flags)
Helper function for getting server side [start, start+count] DLM lock if asked by client.
Definition at line 1676 of file tgt_handler.c.
References ELDLM_OK, ldlm_extent::end, ENTRY, ldlm_extent::gid, ldlm_policy_data::l_extent, LASSERT, ldlm_blocking_ast(), ldlm_cli_enqueue_local(), ldlm_completion_ast(), LDLM_EXTENT, ldlm_glimpse_ast(), lustre_handle_is_used(), LVB_T_NONE, OBD_OBJECT_EOF, RETURN, and ldlm_extent::start.
Referenced by lock_region(), ofd_getattr_hdl(), ofd_punch_hdl(), and tgt_brw_lock().
void tgt_extent_unlock (struct lustre_handle * lh, enum ldlm_mode mode)
Definition at line 1709 of file tgt_handler.c.
References LASSERT, ldlm_lock_decref(), and lustre_handle_is_used().
Referenced by ofd_getattr_hdl(), ofd_punch_hdl(), tgt_brw_unlock(), and unlock_zero_regions().
static int tgt_filter_recovery_request (struct ptlrpc_request * req, struct obd_device * obd, int * process) [static]
Definition at line 471 of file tgt_handler.c.
References D_ERROR, DEBUG_REQ, FLD_QUERY, FLD_READ, LDLM_ENQUEUE, lustre_msg_get_opc(), MDS_CLOSE, MDS_DISCONNECT, MDS_HSM_PROGRESS, MDS_HSM_REQUEST, MDS_HSM_STATE_SET, MDS_REINT, MDS_SYNC, OBD_IDX_READ, OBD_PING, OST_CREATE, OST_DESTROY, OST_DISCONNECT, OST_PUNCH, OST_SETATTR, OST_SYNC, OST_WRITE, OUT_UPDATE, RETURN, ptlrpc_request::rq_reqmsg, and SEQ_QUERY.
Referenced by tgt_handle_recovery().
static int tgt_handle_lfsck_notify (struct tgt_session_info * tsi) [static]
Definition at line 1585 of file tgt_handler.c.
References ENTRY, lu_target::lut_bottom, req_capsule_client_get(), RETURN, RMF_LFSCK_REQUEST, tgt_lfsck_in_notify, tgt_session_info::tsi_env, tgt_session_info::tsi_pill, and tgt_session_info::tsi_tgt.
static int tgt_handle_lfsck_query (struct tgt_session_info * tsi) [static]
Definition at line 1602 of file tgt_handler.c.
References ENTRY, lu_target::lut_bottom, req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_LFSCK_REPLY, RMF_LFSCK_REQUEST, tgt_lfsck_query, tgt_session_info::tsi_env, tgt_session_info::tsi_pill, and tgt_session_info::tsi_tgt.
static int tgt_handle_recovery (struct ptlrpc_request * req, int reply_fail_id) [static]
Definition at line 514 of file tgt_handler.c.
References D_INFO, D_WARNING, DEBUG_REQ, ENTRY, obd_export::exp_obd, LPU64, lustre_msg_get_flags(), lustre_msg_get_opc(), MDS_CONNECT, MGS_CONNECT, MSG_REPLAY, MSG_RESENT, obd_device::obd_recovering, obd_device::obd_replayable, OST_CONNECT, ptlrpc_error(), req_can_reconstruct(), RETURN, ptlrpc_request::rq_export, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_status, ptlrpc_request::rq_xid, SEC_CTX_FINI, SEC_CTX_INIT, SEC_CTX_INIT_CONT, tgt_filter_recovery_request(), and unlikely.
Referenced by tgt_request_handle().
static int tgt_handle_request0 (struct tgt_session_info * tsi, struct tgt_handler * h, struct ptlrpc_request * req) [static]
Definition at line 371 of file tgt_handler.c.
References CFS_FAIL_TIMEOUT, cfs_fail_val, clear_serious(), D_ERROR, DEBUG_REQ, ENTRY, GOTO, HABEO_REFERO, is_serious(), LASSERT, LBUG, likely, lustre_msg_get_opc(), mdt_body::mbo_eadatasize, MDS_REINT, OBD_FAIL_CHECK, OBD_FAIL_CHECK_ORSET, OBD_FAIL_MDS_REINT_MULTI_NET, OBD_FAIL_ONCE, OBD_FAIL_SEC_CTX_HDL_PAUSE, RCL_SERVER, req_capsule_has_field(), req_capsule_server_pack(), req_capsule_set_size(), RETURN, RMF_LOGCOOKIES, RMF_MDT_MD, ptlrpc_request::rq_export, ptlrpc_request::rq_no_reply, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_status, SEC_CTX_FINI, SEC_CTX_INIT, SEC_CTX_INIT_CONT, target_send_reply(), tgt_name(), tgt_request_preprocess(), tgt_handler::th_act, tgt_handler::th_fail_id, tgt_handler::th_flags, tgt_handler::th_name, tgt_session_info::tsi_mdt_body, tgt_session_info::tsi_pill, tgt_session_info::tsi_reply_fail_id, tgt_session_info::tsi_tgt, and unlikely.
Referenced by tgt_request_handle().
static struct tgt_handler* tgt_handler_find_check (struct ptlrpc_request * req) [static, read]
Definition at line 570 of file tgt_handler.c.
References CERROR, class_exp2obd(), D_ERROR, DEBUG_REQ, ENTRY, LASSERT, lustre_msg_get_opc(), lu_target::lut_slice, obd_device::obd_name, RETURN, ptlrpc_request::rq_export, ptlrpc_request::rq_reqmsg, tgt_name(), tgt_handler::th_opc, tgt_opc_slice::tos_hs, tgt_opc_slice::tos_opc_start, and unlikely.
Referenced by tgt_hpreq_handler(), and tgt_request_handle().
int tgt_hpreq_handler (struct ptlrpc_request * req)
Assign high priority operations to the request if needed.
Definition at line 785 of file tgt_handler.c.
References ENTRY, RCL_SERVER, req_capsule_init(), RETURN, ptlrpc_request::rq_export, ptlrpc_request::rq_pill, tgt_handler_find_check(), tgt_request_preprocess(), tgt_ses_info(), tgt_handler::th_hp, tgt_session_info::tsi_env, tgt_session_info::tsi_exp, tgt_session_info::tsi_pill, tgt_session_info::tsi_tgt, and unlikely.
Referenced by ost_setup().
static int tgt_init_sec_level (struct ptlrpc_request * req) [static]
Definition at line 839 of file tgt_handler.c.
References CDEBUG, class_exp2obd(), CWARN, D_ERROR, D_SEC, DEBUG_REQ, ENTRY, libcfs_nid2str(), LUSTRE_SEC_ALL, LUSTRE_SEC_NONE, LUSTRE_SEC_REMOTE, lu_target::lut_sec_level, make_kuid(), lnet_process_id_t::nid, OBD_CONNECT_MDS_CAPA, OBD_CONNECT_OSS_CAPA, OBD_CONNECT_RMT_CLIENT, OBD_CONNECT_RMT_CLIENT_FORCE, obd_device::obd_name, obd_connect_data::ocd_connect_flags, req_capsule_client_get(), req_capsule_server_get(), RETURN, RMF_CONNECT_DATA, ptlrpc_request::rq_auth_gss, ptlrpc_request::rq_auth_remote, ptlrpc_request::rq_auth_usr_mdt, ptlrpc_request::rq_export, ptlrpc_request::rq_peer, ptlrpc_request::rq_pill, tgt_init_sec_none(), tgt_name(), uid_valid(), and unlikely.
Referenced by tgt_connect().
static void tgt_init_sec_none (struct obd_connect_data * reply) [inline, static]
Definition at line 833 of file tgt_handler.c.
References OBD_CONNECT_RMT_CLIENT, OBD_CONNECT_RMT_CLIENT_FORCE, and obd_connect_data::ocd_connect_flags.
Referenced by tgt_init_sec_level().
static int tgt_io_data_unpack (struct tgt_session_info * tsi, struct ost_id * oi) [static]
Definition at line 188 of file tgt_handler.c.
References CERROR, D_RPCTRACE, DEBUG_REQ, DOSTID, ENTRY, obd_ioobj::ioo_bufcnt, obd_ioobj::ioo_oid, ioobj_max_brw_get, obd_export_nid2str(), POSTID, PTLRPC_MAX_BRW_PAGES, RCL_CLIENT, req_capsule_client_get(), req_capsule_get_size(), RETURN, RMF_NIOBUF_REMOTE, RMF_OBD_IOOBJ, tgt_name(), tgt_ses_req(), tgt_session_info::tsi_exp, tgt_session_info::tsi_pill, tgt_session_info::tsi_tgt, and unlikely.
Referenced by tgt_ost_body_unpack().
void tgt_io_thread_done (struct ptlrpc_thread * thread)
Definition at line 1652 of file tgt_handler.c.
References ENTRY, EXIT, LASSERT, OBD_FREE_LARGE, and ptlrpc_thread::t_data.
Referenced by ost_setup().
int tgt_io_thread_init (struct ptlrpc_thread * thread)
Definition at line 1632 of file tgt_handler.c.
References ENTRY, LASSERT, OBD_ALLOC_LARGE, RETURN, and ptlrpc_thread::t_data.
Referenced by ost_setup().
int tgt_llog_close (struct tgt_session_info * tsi)
Definition at line 1467 of file tgt_handler.c.
References ENTRY, llog_origin_handle_close(), RETURN, and tgt_ses_req().
int tgt_llog_destroy (struct tgt_session_info * tsi)
Definition at line 1480 of file tgt_handler.c.
References ENTRY, llog_origin_handle_destroy(), RETURN, and tgt_ses_req().
int tgt_llog_next_block (struct tgt_session_info * tsi)
Definition at line 1503 of file tgt_handler.c.
References ENTRY, llog_origin_handle_next_block(), RETURN, and tgt_ses_req().
int tgt_llog_open (struct tgt_session_info * tsi)
Definition at line 1455 of file tgt_handler.c.
References ENTRY, llog_origin_handle_open(), RETURN, and tgt_ses_req().
Referenced by mgs_llog_open().
int tgt_llog_prev_block (struct tgt_session_info * tsi)
Definition at line 1515 of file tgt_handler.c.
References ENTRY, llog_origin_handle_prev_block(), RETURN, and tgt_ses_req().
int tgt_llog_read_header (struct tgt_session_info * tsi)
Definition at line 1491 of file tgt_handler.c.
References ENTRY, llog_origin_handle_read_header(), RETURN, and tgt_ses_req().
static int tgt_mdt_body_unpack (struct tgt_session_info * tsi, __u32 flags) [static]
Definition at line 70 of file tgt_handler.c.
References CERROR, dt_device::dd_lu_dev, DFID, ENTRY, fid_is_sane(), fid_is_zero(), HABEO_CORPUS, lu_object_exists, lu_object_find(), lu_object_put(), lu_target::lut_bottom, mdt_body::mbo_fid1, mdt_body::mbo_valid, OBD_MD_FLID, PFID, req_capsule_client_get(), RETURN, RMF_MDT_BODY, tgt_name(), tgt_session_info::tsi_corpus, tgt_session_info::tsi_env, tgt_session_info::tsi_fid, tgt_session_info::tsi_mdt_body, tgt_session_info::tsi_pill, tgt_session_info::tsi_tgt, and unlikely.
Referenced by tgt_request_preprocess().
char* tgt_name (struct lu_target * tgt)
Definition at line 51 of file tgt_handler.c.
References LASSERT, lu_target::lut_obd, and obd_device::obd_name.
Referenced by ll_rename(), mdt_get_info(), mdt_init_idmap(), mdt_set_info(), mgs_llog_open(), mgs_set_info(), ofd_get_info_hdl(), ofd_punch_hpreq_check(), ofd_rw_hpreq_check(), ofd_set_info_hdl(), ofd_statfs_hdl(), out_attr_get(), out_attr_set(), out_create(), out_destroy(), out_handle(), out_index_delete(), out_index_insert(), out_index_lookup(), out_read(), out_write(), out_xattr_del(), out_xattr_get(), out_xattr_set(), tgt_adapt_sptlrpc_conf(), tgt_add_reply_data(), tgt_blocking_ast(), tgt_brw_read(), tgt_brw_write(), tgt_checksum_bulk(), tgt_clear_reply_slot(), tgt_clients_data_init(), tgt_connect_check_sptlrpc(), tgt_free_reply_data(), tgt_handle_request0(), tgt_handler_find_check(), tgt_init(), tgt_init_sec_level(), tgt_io_data_unpack(), tgt_last_rcvd_update(), tgt_lookup_reply(), tgt_mdt_body_unpack(), tgt_ost_body_unpack(), tgt_release_reply_data(), tgt_reply_data_init(), tgt_request_handle(), tgt_server_data_init(), tgt_set_reply_slot(), and tgt_validate_obdo().
static int tgt_obd_idx_read (struct tgt_session_info * tsi) [static]
Definition at line 1185 of file tgt_handler.c.
References dt_index_read(), ENTRY, err_serious(), EXIT, exp_max_brw_size(), fid_is_sane(), GOTO, IDX_INFO_MAGIC, idx_info::ii_attrs, idx_info::ii_count, idx_info::ii_fid, idx_info::ii_flags, idx_info::ii_hash_start, idx_info::ii_magic, LASSERTF, LU_PAGE_SHIFT, lu_target::lut_bottom, min_t, OBD_ALLOC, OBD_FREE, tgt_thread_info::rdpg, req_capsule_client_get(), req_capsule_server_get(), req_capsule_server_pack(), req_capsule_set(), RETURN, RMF_IDX_INFO, lu_rdpg::rp_attrs, lu_rdpg::rp_count, lu_rdpg::rp_hash, lu_rdpg::rp_npages, lu_rdpg::rp_pages, RQF_OBD_IDX_READ, tgt_sendpage(), tgt_th_info(), tgt_session_info::tsi_env, tgt_session_info::tsi_exp, tgt_session_info::tsi_pill, tgt_session_info::tsi_tgt, and tgt_thread_info::tti_u.
int tgt_obd_log_cancel (struct tgt_session_info * tsi)
Definition at line 1107 of file tgt_handler.c.
References err_serious().
int tgt_obd_ping (struct tgt_session_info * tsi)
Definition at line 1093 of file tgt_handler.c.
References ENTRY, err_serious(), RETURN, and tgt_ses_req().
static int tgt_ost_body_unpack (struct tgt_session_info * tsi, __u32 flags) [static]
Definition at line 241 of file tgt_handler.c.
References CERROR, ENTRY, HABEO_CORPUS, NODEMAP_CLIENT_TO_FS, NODEMAP_GID, nodemap_map_id(), NODEMAP_UID, obdo::o_gid, obdo::o_oi, obdo::o_uid, obdo::o_valid, ost_body::oa, OBD_MD_FLID, ost_id::oi_fid, ost_fid_build_resid(), RCL_CLIENT, req_capsule_client_get(), req_capsule_has_field(), RETURN, RMF_OBD_IOOBJ, RMF_OST_BODY, tgt_io_data_unpack(), tgt_name(), tgt_validate_obdo(), tgt_session_info::tsi_corpus, tgt_session_info::tsi_exp, tgt_session_info::tsi_fid, tgt_session_info::tsi_ost_body, tgt_session_info::tsi_pill, tgt_session_info::tsi_resid, and tgt_session_info::tsi_tgt.
Referenced by tgt_request_preprocess().
void tgt_register_lfsck_in_notify (int(*)(const struct lu_env *, struct dt_device *, struct lfsck_request *, struct thandle *) notify)
Definition at line 1559 of file tgt_handler.c.
References tgt_lfsck_in_notify.
Referenced by lfsck_init().
void tgt_register_lfsck_query (int(*)(const struct lu_env *, struct dt_device *, struct lfsck_request *, struct lfsck_reply *, struct lfsck_query *) query)
Definition at line 1574 of file tgt_handler.c.
References tgt_lfsck_query.
Referenced by lfsck_init().
int tgt_request_handle (struct ptlrpc_request * req)
Definition at line 653 of file tgt_handler.c.
References CDEBUG, CFS_FAIL_CHECK_ORSET, CFS_FAIL_ONCE, class_connected_export(), class_exp2obd(), current_pid, D_ERROR, D_HA, DEBUG_REQ, ENTRY, EXIT, exp_connect_flags(), obd_export::exp_last_xid, GOTO, LASSERTF, libcfs_id2str(), likely, lu_env_refill(), lu_object_put(), lustre_msg, lustre_msg_check_version(), lustre_msg_get_jobid(), lustre_msg_get_opc(), lustre_msg_get_version(), lu_target::lut_reply_fail_id, lu_target::lut_request_fail_id, MDS_CONNECT, MGS_CONNECT, msg, OBD_CONNECT_JOBSTATS, OBD_FAIL_CHECK, OBD_FAIL_OST_CONNECT_NET2, OBD_FAIL_SEC_CTX_INIT_NET, obd_device::obd_name, obd_device::obd_recovery_data, OST_CONNECT, process_req_last_xid(), ptlrpc_error(), RCL_SERVER, req_capsule_fini(), req_capsule_init(), req_capsule_set(), ptlrpc_request::rq_export, ptlrpc_request::rq_peer, ptlrpc_request::rq_pill, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_status, RQF_CONNECT, SEC_CTX_FINI, SEC_CTX_INIT, SEC_CTX_INIT_CONT, tgt_handle_recovery(), tgt_handle_request0(), tgt_handler_find_check(), tgt_name(), tgt_ses_info(), tgt_handler::th_opc, tgt_handler::th_version, target_recovery_data::trd_processing_task, tgt_session_info::tsi_corpus, tgt_session_info::tsi_env, tgt_session_info::tsi_exp, tgt_session_info::tsi_jobid, tgt_session_info::tsi_pill, tgt_session_info::tsi_reply_fail_id, tgt_session_info::tsi_tgt, and unlikely.
Referenced by mds_start_ptlrpc_service(), mdt_prepare(), mgs_init0(), ofd_prepare(), and ost_setup().
static int tgt_request_preprocess (struct tgt_session_info * tsi, struct tgt_handler * h, struct ptlrpc_request * req) [static]
Definition at line 300 of file tgt_handler.c.
References ENTRY, ergo, HABEO_CLAVIS, HABEO_CORPUS, HABEO_REFERO, ldlm_lock_desc::l_policy_data, ldlm_lock_desc::l_resource, LASSERT, LDLM_IBITS, ldlm_request::lock_desc, ldlm_resource_desc::lr_type, lustre_msg_get_opc(), MUTABOR, OBD_CONNECT_RDONLY, RCL_CLIENT, req_capsule_client_get(), req_capsule_has_field(), req_capsule_set(), RETURN, RMF_DLM_REQ, RMF_MDT_BODY, RMF_OST_BODY, ptlrpc_request::rq_reqmsg, tgt_conn_flags(), tgt_mdt_body_unpack(), tgt_ost_body_unpack(), tgt_handler::th_act, tgt_handler::th_flags, tgt_handler::th_fmt, tgt_handler::th_opc, tgt_session_info::tsi_dlm_req, tgt_session_info::tsi_pill, tgt_session_info::tsi_preprocessed, and unlikely.
Referenced by tgt_handle_request0(), and tgt_hpreq_handler().
static int tgt_sec_ctx_handle (struct tgt_session_info * tsi) [static]
Definition at line 1542 of file tgt_handler.c.
int tgt_send_buffer (struct tgt_session_info * tsi, struct lu_rdbuf * rdbuf)
Definition at line 1112 of file tgt_handler.c.
References ptlrpc_bulk_frag_ops::add_iov_frag, ptlrpc_bulk_desc::bd_frag_ops, ENTRY, lu_buf::lb_buf, lu_buf::lb_len, MDS_BULK_PORTAL, PTLRPC_BULK_BUF_KVEC, ptlrpc_bulk_kvec_ops, PTLRPC_BULK_PUT_SOURCE, ptlrpc_free_bulk(), lu_rdbuf::rb_bufs, lu_rdbuf::rb_nbufs, RETURN, ptlrpc_request::rq_export, tgt_ses_req(), tgt_th_info(), tgt_session_info::tsi_env, tgt_thread_info::tti_u, and tgt_thread_info::update.
Referenced by out_read().
int tgt_sendpage (struct tgt_session_info * tsi, struct lu_rdpg * rdpg, int nob)
Definition at line 1141 of file tgt_handler.c.
References ptlrpc_bulk_frag_ops::add_kiov_frag, ptlrpc_bulk_desc::bd_frag_ops, ptlrpc_bulk_desc::bd_nob, ENTRY, exp_connect_flags(), LASSERT, MDS_BULK_PORTAL, min_t, OBD_CONNECT_BRW_SIZE, PTLRPC_BULK_BUF_KIOV, ptlrpc_bulk_kiov_pin_ops, PTLRPC_BULK_PUT_SOURCE, ptlrpc_free_bulk(), tgt_thread_info::rdpg, RETURN, lu_rdpg::rp_count, lu_rdpg::rp_npages, lu_rdpg::rp_pages, ptlrpc_request::rq_export, tgt_ses_req(), tgt_th_info(), tgt_session_info::tsi_env, and tgt_thread_info::tti_u.
Referenced by mdt_readpage(), and tgt_obd_idx_read().
int tgt_sync (const struct lu_env * env, struct lu_target * tgt, struct dt_object * obj, __u64 start, __u64 end)
Definition at line 1274 of file tgt_handler.c.
References dt_object_sync(), dt_sync(), dt_version_get(), ENTRY, lu_target::lut_bottom, lu_target::lut_obd, lu_target::lut_sync_count, obd_device::obd_last_committed, and RETURN.
Referenced by ofd_sync_hdl(), and tgt_blocking_ast().
int tgt_validate_obdo (struct tgt_session_info * tsi, struct obdo * oa)
Validate oa from client.
If the request comes from 2.0 clients, currently only RSVD seq and IDIF req are valid. a. objects in Single MDT FS seq = FID_SEQ_OST_MDT0, oi_id != 0 b. Echo objects(seq = 2), old echo client still use oi_id/oi_seq to pack ost_id. Because non-zero oi_seq will make it diffcult to tell whether this is oi_fid or real ostid. So it will check OBD_CONNECT_FID, then convert the ostid to FID for old client. c. Old FID-disable osc will send IDIF. d. new FID-enable osc/osp will send normal FID.
And also oi_id/f_oid should always start from 1. oi_id/f_oid = 0 will be used for LAST_ID file, and only being accessed inside OST now.
Definition at line 134 of file tgt_handler.c.
References CERROR, DOSTID, ENTRY, exp_connect_flags(), lu_fid::f_oid, lu_fid::f_seq, lu_fid::f_ver, FID_SEQ_ECHO, fid_seq_is_echo(), fid_seq_is_idif(), fid_seq_is_mdt0(), fid_seq_is_norm(), GOTO, lr_server_data::lsd_osd_index, lu_target::lut_lsd, obdo::o_oi, obdo::o_valid, OBD_CONNECT_FID, obd_export_nid2str(), OBD_MD_FLGROUP, OBD_MD_FLID, ost_id::oi, ost_id::oi_fid, ostid_id(), ostid_seq(), ostid_set_seq_mdt0(), ostid_to_fid(), RETURN, tgt_name(), tgt_th_info(), tgt_session_info::tsi_env, tgt_session_info::tsi_exp, tgt_session_info::tsi_tgt, tgt_thread_info::tti_fid1, and unlikely.
Referenced by ofd_get_info_hdl(), and tgt_ost_body_unpack().
static void tgt_warn_on_cksum (struct ptlrpc_request * req, struct ptlrpc_bulk_desc * desc, struct niobuf_local * local_nb, int npages, u32 client_cksum, u32 server_cksum, bool mmap) [static]
Definition at line 2030 of file tgt_handler.c.
References __u64, ptlrpc_bulk_desc::bd_sender, CDEBUG_LIMIT, D_INFO, DFID, DOSTID, obd_export::exp_obd, LASSERT, LCONSOLE_ERROR_MSG, libcfs_id2str(), libcfs_nid2str(), niobuf_local::lnb_file_offset, niobuf_local::lnb_len, LPU64, lnet_process_id_t::nid, obdo::o_oi, obdo::o_parent_oid, obdo::o_parent_seq, obdo::o_parent_ver, obdo::o_valid, ost_body::oa, OBD_MD_FLFID, obd_device::obd_name, POSTID, req_capsule_client_get(), RMF_OST_BODY, ptlrpc_request::rq_export, ptlrpc_request::rq_peer, and ptlrpc_request::rq_pill.
Referenced by tgt_brw_write().
Variable Documentation
struct ldlm_callback_suite tgt_dlm_cbs [static]
Initial value:
 {
        .lcs_completion = ldlm_server_completion_ast,
        .lcs_blocking   = tgt_blocking_ast,
        .lcs_glimpse    = ldlm_server_glimpse_ast
}
Definition at line 1379 of file tgt_handler.c.
struct tgt_handler tgt_dlm_handlers[]
Initial value:
 {
TGT_DLM_HDL    (HABEO_CLAVIS,   LDLM_ENQUEUE,           tgt_enqueue),
TGT_DLM_HDL_VAR(HABEO_CLAVIS,   LDLM_CONVERT,           tgt_convert),
TGT_DLM_HDL_VAR(0,              LDLM_BL_CALLBACK,       tgt_bl_callback),
}
Definition at line 1444 of file tgt_handler.c.
struct tgt_handler tgt_lfsck_handlers[]
Initial value:
 {
TGT_LFSCK_HDL(HABEO_REFERO,     LFSCK_NOTIFY,   tgt_handle_lfsck_notify),
TGT_LFSCK_HDL(HABEO_REFERO,     LFSCK_QUERY,    tgt_handle_lfsck_query),
}
Definition at line 1623 of file tgt_handler.c.
int(* tgt_lfsck_in_notify)(const struct lu_env *env, struct dt_device *key, struct lfsck_request *lr, struct thandle *th) = NULL
Referenced by out_handle(), out_tx_xattr_set_exec(), out_xattr_set_add_exec(), tgt_handle_lfsck_notify(), and tgt_register_lfsck_in_notify().
int(* tgt_lfsck_query)(const struct lu_env *env, struct dt_device *key, struct lfsck_request *req, struct lfsck_reply *rep, struct lfsck_query *que) = NULL [static]
Referenced by tgt_handle_lfsck_query(), and tgt_register_lfsck_query().
struct tgt_handler tgt_llog_handlers[]
Initial value:
 {
TGT_LLOG_HDL    (0,     LLOG_ORIGIN_HANDLE_CREATE,      tgt_llog_open),
TGT_LLOG_HDL    (0,     LLOG_ORIGIN_HANDLE_NEXT_BLOCK,  tgt_llog_next_block),
TGT_LLOG_HDL    (0,     LLOG_ORIGIN_HANDLE_READ_HEADER, tgt_llog_read_header),
TGT_LLOG_HDL    (0,     LLOG_ORIGIN_HANDLE_PREV_BLOCK,  tgt_llog_prev_block),
TGT_LLOG_HDL    (0,     LLOG_ORIGIN_HANDLE_DESTROY,     tgt_llog_destroy),
TGT_LLOG_HDL_VAR(0,     LLOG_ORIGIN_HANDLE_CLOSE,       tgt_llog_close),
}
Definition at line 1528 of file tgt_handler.c.
struct tgt_handler tgt_obd_handlers[]
Initial value:
 {
TGT_OBD_HDL    (0,      OBD_PING,               tgt_obd_ping),
TGT_OBD_HDL_VAR(0,      OBD_LOG_CANCEL,         tgt_obd_log_cancel),
}
Definition at line 1267 of file tgt_handler.c.
struct tgt_handler tgt_sec_ctx_handlers[]
Initial value:
 {
TGT_SEC_HDL_VAR(0,      SEC_CTX_INIT,           tgt_sec_ctx_handle),
TGT_SEC_HDL_VAR(0,      SEC_CTX_INIT_CONT,      tgt_sec_ctx_handle),
TGT_SEC_HDL_VAR(0,      SEC_CTX_FINI,           tgt_sec_ctx_handle),
}
Definition at line 1547 of file tgt_handler.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.