Lustre: lustre/target/tgt_main.c File Reference
lustre/target/tgt_main.c File Reference
#include <obd.h>
#include "tgt_internal.h"
#include "../ptlrpc/ptlrpc_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_CLASS
Functions
void tgt_save_slc_lock (struct ldlm_lock *lock, __u64 transno)
void tgt_discard_slc_lock (struct ldlm_lock *lock)
void tgt_cancel_slc_locks (__u64 transno)
int tgt_init (const struct lu_env *env, struct lu_target *lut, struct obd_device *obd, struct dt_device *dt, struct tgt_opc_slice *slice, int request_fail_id, int reply_fail_id)
void tgt_fini (const struct lu_env *env, struct lu_target *lut)
LU_KEY_INIT (tgt, struct tgt_thread_info)
static void tgt_key_fini (const struct lu_context *ctx, struct lu_context_key *key, void *data)
static void tgt_key_exit (const struct lu_context *ctx, struct lu_context_key *key, void *data)
LU_KEY_INIT_GENERIC (tgt)
LU_KEY_INIT_FINI (tgt_ses, struct tgt_session_info)
LU_KEY_INIT_GENERIC (tgt_ses)
int tgt_mod_init (void)
void tgt_mod_exit (void)
Variables
static spinlock_t uncommitted_slc_locks_guard
static struct list_head uncommitted_slc_locks
struct lu_context_key tgt_thread_key
struct lu_context_key tgt_session_key
struct page * tgt_page_to_corrupt
Define Documentation
#define DEBUG_SUBSYSTEM S_CLASS
Definition at line 34 of file tgt_main.c.
Function Documentation
LU_KEY_INIT (tgt , struct tgt_thread_info)
LU_KEY_INIT_FINI (tgt_ses , struct tgt_session_info)
LU_KEY_INIT_GENERIC (tgt_ses)
LU_KEY_INIT_GENERIC (tgt)
void tgt_cancel_slc_locks (__u64 transno)
Definition at line 111 of file tgt_main.c.
References ldlm_lock::l_readers, l_slc_link, ldlm_lock::l_writers, LASSERT, LCF_ASYNC, ldlm_cli_cancel(), ldlm_lock2handle(), LDLM_LOCK_PUT, ldlm_set_cbpending, list, list_del_init(), list_for_each_entry_safe, LIST_HEAD(), list_move(), lock_res_and_lock(), uncommitted_slc_locks, uncommitted_slc_locks_guard, and unlock_res_and_lock().
Referenced by tgt_cb_last_committed().
void tgt_discard_slc_lock (struct ldlm_lock * lock)
Definition at line 86 of file tgt_main.c.
References LASSERT, ldlm_is_cbpending, LDLM_LOCK_PUT, list_del_init(), list_empty(), lock_res_and_lock(), uncommitted_slc_locks_guard, and unlock_res_and_lock().
Referenced by mdt_remote_blocking_ast().
void tgt_fini (const struct lu_env * env, struct lu_target * lut)
Definition at line 283 of file tgt_main.c.
References CERROR, dt_object::do_lu, dt_txn_callback_del(), ENTRY, EXIT, LR_MAX_CLIENTS, lr_server_data::lsd_feature_incompat, lu_object_put(), lu_target::lut_bottom, lu_target::lut_client_bitmap, lu_target::lut_last_rcvd, lu_target::lut_lsd, lu_target::lut_num_clients, lu_target::lut_obd, lu_target::lut_reply_bitmap, lu_target::lut_reply_data, LUT_REPLY_SLOTS_MAX_CHUNKS, LUT_REPLY_SLOTS_PER_CHUNK, lu_target::lut_sptlrpc_rset, lu_target::lut_txn_cb, OBD_FREE, OBD_INCOMPAT_MULTI_RPCS, obd_device::obd_name, sptlrpc_rule_set_free(), and tgt_server_data_update().
Referenced by mdt_fini(), mdt_init0(), mgs_device_fini(), mgs_init0(), ofd_fini(), and ofd_init0().
int tgt_init (const struct lu_env * env, struct lu_target * lut, struct obd_device * obd, struct dt_device * dt, struct tgt_opc_slice * slice, int request_fail_id, int reply_fail_id)
Definition at line 147 of file tgt_main.c.
References CERROR, dt_device::dd_lu_dev, dt_object::do_lu, dt_object_format::dof_type, dt_find_or_create(), dt_mode_to_dft(), dt_txn_callback_add(), dt_txn_callback_del(), dt_txn_callback::dtc_cookie, dt_txn_callback::dtc_linkage, dt_txn_callback::dtc_tag, dt_txn_callback::dtc_txn_commit, dt_txn_callback::dtc_txn_start, dt_txn_callback::dtc_txn_stop, ENTRY, GOTO, INIT_LIST_HEAD, lu_attr::la_mode, LA_MODE, lu_attr::la_valid, LASSERT, LAST_RECV_OID, LCT_DT_THREAD, LCT_MD_THREAD, lu_device::ld_site, LR_MAX_CLIENTS, lu_site::ls_tgt, lu_local_obj_fid(), lu_object_put(), LUSTRE_MDT_NAME, lu_target::lut_bottom, lu_target::lut_client_bitmap, lu_target::lut_client_bitmap_lock, lu_target::lut_client_generation, lu_target::lut_flags_lock, lu_target::lut_last_rcvd, lu_target::lut_num_clients, lu_target::lut_obd, lu_target::lut_reply_bitmap, lu_target::lut_reply_data, lu_target::lut_reply_fail_id, LUT_REPLY_SLOTS_MAX_CHUNKS, lu_target::lut_request_fail_id, lu_target::lut_slice, lu_target::lut_sptlrpc_lock, lu_target::lut_sptlrpc_rset, lu_target::lut_sync_count, lu_target::lut_sync_lock_cancel, lu_target::lut_translock, lu_target::lut_txn_cb, NEVER_SYNC_ON_CANCEL, OBD_ALLOC, OBD_FREE, obd_device::obd_replayable, obd_device::obd_type, OBT_MAGIC, REPLY_DATA_OID, RETURN, sptlrpc_rule_set_init(), tgt_name(), tgt_reply_data_init(), tgt_server_data_init(), tgt_txn_start_cb(), tgt_txn_stop_cb(), obd_type::typ_name, and obd_device::u.
Referenced by mdt_init0(), mgs_init0(), and ofd_init0().
static void tgt_key_exit (const struct lu_context * ctx, struct lu_context_key * key, void * data) [static]
Definition at line 352 of file tgt_main.c.
References tgt_thread_info::tti_has_trans, and tgt_thread_info::tti_mult_trans.
static void tgt_key_fini (const struct lu_context * ctx, struct lu_context_key * key, void * data) [static]
Definition at line 334 of file tgt_main.c.
References OBD_FREE, OBD_FREE_PTR, thandle_exec_args::ta_alloc_args, thandle_exec_args::ta_args, and tgt_thread_info::tti_tea.
void tgt_mod_exit (void)
Definition at line 413 of file tgt_main.c.
References lu_context_key_degister(), tgt_page_to_corrupt, and update_info_fini().
Referenced by ptlrpc_exit(), and ptlrpc_init().
int tgt_mod_init (void)
Definition at line 393 of file tgt_main.c.
References ENTRY, INIT_LIST_HEAD, lu_context_key_register_many(), RETURN, tgt_page_to_corrupt, uncommitted_slc_locks, uncommitted_slc_locks_guard, and update_info_init().
Referenced by ptlrpc_init().
void tgt_save_slc_lock (struct ldlm_lock * lock, __u64 transno)
Definition at line 54 of file tgt_main.c.
References ldlm_is_cbpending, LDLM_LOCK_PUT, list_add_tail(), list_empty(), lock_res_and_lock(), uncommitted_slc_locks, uncommitted_slc_locks_guard, and unlock_res_and_lock().
Referenced by mdt_save_remote_lock().
Variable Documentation
struct page* tgt_page_to_corrupt
Definition at line 391 of file tgt_main.c.
Referenced by tgt_checksum_bulk(), tgt_mod_exit(), and tgt_mod_init().
struct lu_context_key tgt_session_key
Initial value:
 {
        .lct_tags = LCT_SERVER_SESSION,
        .lct_init = tgt_ses_key_init,
        .lct_fini = tgt_ses_key_fini,
}
Definition at line 375 of file tgt_main.c.
Referenced by ofd_punch_hpreq_check(), ofd_punch_hpreq_lock_match(), ofd_rw_hpreq_check(), and tgt_ses_info().
struct lu_context_key tgt_thread_key
Initial value:
 {
        .lct_tags = LCT_MD_THREAD | LCT_DT_THREAD,
        .lct_init = tgt_key_init,
        .lct_fini = tgt_key_fini,
        .lct_exit = tgt_key_exit,
}
Definition at line 362 of file tgt_main.c.
Referenced by tgt_th_info().
struct list_head uncommitted_slc_locks [static]
Definition at line 41 of file tgt_main.c.
Referenced by tgt_cancel_slc_locks(), tgt_mod_init(), and tgt_save_slc_lock().
spinlock_t uncommitted_slc_locks_guard [static]
Definition at line 40 of file tgt_main.c.
Referenced by tgt_cancel_slc_locks(), tgt_discard_slc_lock(), tgt_mod_init(), and tgt_save_slc_lock().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.