Lustre: lustre/target/tgt_lastrcvd.c File Reference
lustre/target/tgt_lastrcvd.c File Reference
#include <obd.h>
#include <obd_class.h>
#include <lustre_fid.h>
#include "tgt_internal.h"
Data Structures
struct tgt_last_committed_callback
commit callback, need to update last_committed value
struct tgt_new_client_callback
struct server_compat_data
Functions
static int tgt_bitmap_chunk_alloc (struct lu_target *lut, int chunk)
static int tgt_find_free_reply_slot (struct lu_target *lut)
static int tgt_set_reply_slot (struct lu_target *lut, int idx)
static int tgt_clear_reply_slot (struct lu_target *lut, int idx)
static int tgt_reply_header_read (const struct lu_env *env, struct lu_target *tgt, struct lsd_reply_header *lrh)
static int tgt_reply_header_write (const struct lu_env *env, struct lu_target *tgt, struct lsd_reply_header *lrh)
static int tgt_reply_data_write (const struct lu_env *env, struct lu_target *tgt, struct lsd_reply_data *lrd, loff_t off, struct thandle *th)
static int tgt_reply_data_read (const struct lu_env *env, struct lu_target *tgt, struct lsd_reply_data *lrd, loff_t off)
static void tgt_free_reply_data (struct lu_target *lut, struct tg_export_data *ted, struct tg_reply_data *trd)
static void tgt_release_reply_data (struct lu_target *lut, struct tg_export_data *ted, struct tg_reply_data *trd)
static struct lu_buf * tti_buf_lsd (struct tgt_thread_info *tti)
static struct lu_buf * tti_buf_lcd (struct tgt_thread_info *tti)
int tgt_client_alloc (struct obd_export *exp)
Allocate in-memory data for client slot related to export.
void tgt_client_free (struct obd_export *exp)
Free in-memory data for client slot related to export.
int tgt_client_data_read (const struct lu_env *env, struct lu_target *tgt, struct lsd_client_data *lcd, loff_t *off, int index)
int tgt_client_data_write (const struct lu_env *env, struct lu_target *tgt, struct lsd_client_data *lcd, loff_t *off, struct thandle *th)
static int tgt_client_data_update (const struct lu_env *env, struct obd_export *exp)
Update client data in last_rcvd.
int tgt_server_data_read (const struct lu_env *env, struct lu_target *tgt)
int tgt_server_data_write (const struct lu_env *env, struct lu_target *tgt, struct thandle *th)
int tgt_server_data_update (const struct lu_env *env, struct lu_target *tgt, int sync)
Update server data in last_rcvd.
int tgt_truncate_last_rcvd (const struct lu_env *env, struct lu_target *tgt, loff_t size)
static void tgt_client_epoch_update (const struct lu_env *env, struct obd_export *exp)
void tgt_boot_epoch_update (struct lu_target *tgt)
Update boot epoch when recovery ends.
static void tgt_cb_last_committed (struct lu_env *env, struct thandle *th, struct dt_txn_commit_cb *cb, int err)
int tgt_last_commit_cb_add (struct thandle *th, struct lu_target *tgt, struct obd_export *exp, __u64 transno)
static void tgt_cb_new_client (struct lu_env *env, struct thandle *th, struct dt_txn_commit_cb *cb, int err)
int tgt_new_client_cb_add (struct thandle *th, struct obd_export *exp)
int tgt_client_new (const struct lu_env *env, struct obd_export *exp)
Add new client to the last_rcvd upon new connection.
int tgt_client_add (const struct lu_env *env, struct obd_export *exp, int idx)
int tgt_client_del (const struct lu_env *env, struct obd_export *exp)
int tgt_add_reply_data (const struct lu_env *env, struct lu_target *tgt, struct tg_export_data *ted, struct tg_reply_data *trd, struct thandle *th, bool update_lrd_file)
static int tgt_last_rcvd_update (const struct lu_env *env, struct lu_target *tgt, struct dt_object *obj, __u64 opdata, struct thandle *th, struct ptlrpc_request *req)
static int tgt_last_rcvd_update_echo (const struct lu_env *env, struct lu_target *tgt, struct dt_object *obj, struct thandle *th, struct obd_export *exp)
static int tgt_clients_data_init (const struct lu_env *env, struct lu_target *tgt, unsigned long last_size)
int tgt_server_data_init (const struct lu_env *env, struct lu_target *tgt)
int tgt_txn_start_cb (const struct lu_env *env, struct thandle *th, void *cookie)
int tgt_txn_stop_cb (const struct lu_env *env, struct thandle *th, void *cookie)
int tgt_reply_data_init (const struct lu_env *env, struct lu_target *tgt)
struct tg_reply_data * tgt_lookup_reply_by_xid (struct tg_export_data *ted, __u64 xid)
bool tgt_lookup_reply (struct ptlrpc_request *req, struct tg_reply_data *trd)
int tgt_handle_received_xid (struct obd_export *exp, __u64 rcvd_xid)
int tgt_handle_tag (struct obd_export *exp, __u16 tag)
Variables
static struct server_compat_data tgt_scd []
Function Documentation
int tgt_add_reply_data (const struct lu_env * env, struct lu_target * tgt, struct tg_export_data * ted, struct tg_reply_data * trd, struct thandle * th, bool update_lrd_file)
Definition at line 1075 of file tgt_lastrcvd.c.
References CDEBUG, CERROR, D_TRACE, lsd_client_data::lcd_last_transno, list_add(), lsd_reply_data::lrd_client_gen, lsd_reply_data::lrd_transno, lsd_reply_data::lrd_xid, REPLY_DATA, RETURN, tg_export_data::ted_lcd, tg_export_data::ted_lcd_lock, tg_export_data::ted_reply_cnt, tg_export_data::ted_reply_list, tg_export_data::ted_reply_max, tgt_find_free_reply_slot(), tgt_name(), tgt_reply_data_write(), tg_reply_data::trd_index, tg_reply_data::trd_list, tg_reply_data::trd_reply, tg_reply_data::trd_tag, and unlikely.
Referenced by tgt_last_rcvd_update().
static int tgt_bitmap_chunk_alloc (struct lu_target * lut, int chunk) [static]
Definition at line 49 of file tgt_lastrcvd.c.
References lu_target::lut_client_bitmap_lock, lu_target::lut_reply_bitmap, LUT_REPLY_SLOTS_PER_CHUNK, OBD_ALLOC, and OBD_FREE.
Referenced by tgt_find_free_reply_slot(), and tgt_set_reply_slot().
void tgt_boot_epoch_update (struct lu_target * tgt)
Update boot epoch when recovery ends.
The recovery is not yet finished and final queue can still be updated with resend requests. Move final list to separate one for processing
go through list of exports participated in recovery and set new epoch for them
return list back at once
Clear MULTI RPCS incompatibility flag if
target is MDT and
there is no client to recover or the recovery was aborted
update server epoch
Definition at line 690 of file tgt_lastrcvd.c.
References __u64, CERROR, obd_export::exp_delayed, obd_export::exp_vbr_failed, INIT_LIST_HEAD, LASSERT, LCT_DT_THREAD, list_for_each_entry, list_splice_init(), lr_epoch, LR_EPOCH_BITS, lr_server_data::lsd_feature_incompat, lr_server_data::lsd_start_epoch, lu_env_fini(), lu_env_init(), LUSTRE_MDT_NAME, lu_target::lut_last_transno, lu_target::lut_lsd, lu_target::lut_obd, lu_target::lut_translock, obd_device::obd_abort_recovery, obd_device::obd_final_req_queue, OBD_INCOMPAT_MULTI_RPCS, obd_device::obd_max_recoverable_clients, obd_device::obd_name, obd_device::obd_recovery_task_lock, obd_device::obd_stopping, obd_device::obd_type, ptlrpc_request::rq_export, tgt_client_epoch_update(), tgt_server_data_update(), and obd_type::typ_name.
static void tgt_cb_last_committed (struct lu_env * env, struct thandle * th, struct dt_txn_commit_cb * cb, int err) [static]
Definition at line 761 of file tgt_lastrcvd.c.
References CDEBUG, class_export_cb_put, D_HA, obd_export::exp_last_committed, obd_export::exp_obd, LASSERT, tgt_last_committed_callback::llcc_cb, tgt_last_committed_callback::llcc_exp, tgt_last_committed_callback::llcc_tgt, tgt_last_committed_callback::llcc_transno, LPD64, lu_target::lut_obd, lu_target::lut_translock, OBD_FREE_PTR, obd_device::obd_last_committed, obd_device::obd_name, ptlrpc_commit_replies(), and tgt_cancel_slc_locks().
Referenced by tgt_last_commit_cb_add().
static void tgt_cb_new_client (struct lu_env * env, struct thandle * th, struct dt_txn_commit_cb * cb, int err) [static]
Definition at line 836 of file tgt_lastrcvd.c.
References CDEBUG, class_export_cb_put, D_RPCTRACE, obd_export::exp_client_uuid, obd_export::exp_lock, obd_export::exp_need_sync, obd_export::exp_obd, LASSERT, tgt_new_client_callback::lncc_cb, tgt_new_client_callback::lncc_exp, OBD_FREE_PTR, obd_device::obd_name, and obd_uuid::uuid.
Referenced by tgt_new_client_cb_add().
static int tgt_clear_reply_slot (struct lu_target * lut, int idx) [static]
Definition at line 147 of file tgt_lastrcvd.c.
References CERROR, LASSERT, lu_target::lut_reply_bitmap, LUT_REPLY_SLOTS_MAX_CHUNKS, LUT_REPLY_SLOTS_PER_CHUNK, and tgt_name().
Referenced by tgt_free_reply_data().
int tgt_client_add (const struct lu_env * env, struct obd_export * exp, int idx)
Definition at line 976 of file tgt_lastrcvd.c.
References CDEBUG, CERROR, D_INFO, ENTRY, exp_connect_flags(), LASSERT, LASSERTF, LBUG, lsd_client_data::lcd_generation, lsd_client_data::lcd_uuid, lr_server_data::lsd_client_size, lr_server_data::lsd_client_start, lu_target::lut_client_bitmap, lu_target::lut_lsd, lu_target::lut_num_clients, lu_target::lut_obd, OBD_CONNECT_LIGHTWEIGHT, obd_device::obd_name, obd_device::obd_uuid, RETURN, tg_export_data::ted_lcd, tg_export_data::ted_lcd_lock, tg_export_data::ted_lr_idx, tg_export_data::ted_lr_off, and obd_uuid::uuid.
Referenced by tgt_clients_data_init().
int tgt_client_alloc (struct obd_export * exp)
Allocate in-memory data for client slot related to export.
Definition at line 376 of file tgt_lastrcvd.c.
References ENTRY, obd_export::exp_obd, INIT_LIST_HEAD, LASSERT, OBD_ALLOC_PTR, obd_device::obd_self_export, and RETURN.
Referenced by mdt_init_export(), and ofd_init_export().
int tgt_client_data_read (const struct lu_env * env, struct lu_target * tgt, struct lsd_client_data * lcd, loff_t * off, int index)
Definition at line 441 of file tgt_lastrcvd.c.
References CDEBUG, check_lcd(), D_INFO, dt_record_read(), lsd_client_data::lcd_last_close_result, lsd_client_data::lcd_last_close_transno, lsd_client_data::lcd_last_close_xid, lsd_client_data::lcd_last_data, lsd_client_data::lcd_last_result, lsd_client_data::lcd_last_transno, lsd_client_data::lcd_last_xid, lcd_le_to_cpu(), lsd_client_data::lcd_uuid, LPU64, lu_target::lut_last_rcvd, lu_target::lut_obd, obd_device::obd_name, ptlrpc_status_ntoh(), tgt_th_info(), tgt_thread_info::tti_buf, tti_buf_lcd(), and tgt_thread_info::tti_lcd.
Referenced by tgt_clients_data_init().
static int tgt_client_data_update (const struct lu_env * env, struct obd_export * exp) [static]
Update client data in last_rcvd.
Definition at line 488 of file tgt_lastrcvd.c.
References CDEBUG, class_exp2obd(), D_ERROR, D_INFO, dt_declare_record_write(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), ENTRY, EXIT, obd_export::exp_lock, obd_export::exp_need_sync, GOTO, LPU64, lr_server_data::lsd_last_transno, lr_server_data::lsd_uuid, lu_target::lut_bottom, lu_target::lut_last_rcvd, lu_target::lut_lsd, lu_target::lut_obd, obd_device::obd_name, RETURN, tg_export_data::ted_lcd, tg_export_data::ted_lr_off, tgt_client_data_write(), tgt_new_client_cb_add(), tgt_th_info(), thandle::th_sync, tgt_thread_info::tti_buf, tti_buf_lcd(), tgt_thread_info::tti_off, and unlikely.
Referenced by tgt_client_del(), tgt_client_epoch_update(), and tgt_client_new().
int tgt_client_data_write (const struct lu_env * env, struct lu_target * tgt, struct lsd_client_data * lcd, loff_t * off, struct thandle * th)
Definition at line 468 of file tgt_lastrcvd.c.
References dt_object_locate(), dt_record_write(), lcd_cpu_to_le(), lsd_client_data::lcd_last_close_result, lsd_client_data::lcd_last_result, lu_target::lut_last_rcvd, ptlrpc_status_hton(), tgt_th_info(), thandle::th_dev, tgt_thread_info::tti_buf, tti_buf_lcd(), and tgt_thread_info::tti_lcd.
Referenced by tgt_client_data_update(), tgt_last_rcvd_update(), and tgt_last_rcvd_update_echo().
int tgt_client_del (const struct lu_env * env, struct obd_export * exp)
Definition at line 1013 of file tgt_lastrcvd.c.
References CDEBUG, CERROR, class_exp2obd(), D_ERROR, D_INFO, ENTRY, exp_connect_flags(), obd_export::exp_flags, LASSERT, LBUG, lsd_client_data::lcd_uuid, lu_target::lut_client_bitmap, lu_target::lut_obd, OBD_CONNECT_LIGHTWEIGHT, obd_device::obd_name, OBD_OPT_FAILOVER, obd_device::obd_uuid, RETURN, tg_export_data::ted_lcd, tg_export_data::ted_lcd_lock, tg_export_data::ted_lr_idx, tg_export_data::ted_lr_off, tgt_client_data_update(), tgt_server_data_update(), unlikely, and obd_uuid::uuid.
Referenced by mdt_export_cleanup(), and ofd_obd_disconnect().
static void tgt_client_epoch_update (const struct lu_env * env, struct obd_export * exp) [static]
VBR: set client last_epoch to current epoch
Definition at line 673 of file tgt_lastrcvd.c.
References LASSERT, lsd_client_data::lcd_last_epoch, lr_server_data::lsd_start_epoch, lu_target::lut_bottom, lu_target::lut_lsd, and tgt_client_data_update().
Referenced by tgt_boot_epoch_update().
void tgt_client_free (struct obd_export * exp)
Free in-memory data for client slot related to export.
Definition at line 395 of file tgt_lastrcvd.c.
References CERROR, cfs_hash_del(), obd_export::exp_gen_hash, obd_export::exp_obd, hlist_unhashed(), LASSERT, LBUG, lsd_client_data::lcd_generation, list_for_each_entry_safe, lu_target::lut_client_bitmap, lu_target::lut_num_clients, OBD_FREE_PTR, obd_device::obd_gen_hash, obd_device::obd_name, obd_device::obd_self_export, obd_device::obd_stopping, OBT_MAGIC, tg_export_data::ted_lcd, tg_export_data::ted_lcd_lock, tg_export_data::ted_lr_idx, tg_export_data::ted_reply_last, tg_export_data::ted_reply_list, tgt_free_reply_data(), tgt_is_multimodrpcs_client(), tgt_release_reply_data(), tg_reply_data::trd_list, and obd_device::u.
Referenced by mdt_destroy_export(), mdt_init_export(), and ofd_destroy_export().
int tgt_client_new (const struct lu_env * env, struct obd_export * exp)
Add new client to the last_rcvd upon new connection.
We use a bitmap to locate a free space in the last_rcvd file and initialize tg_export_data.
Definition at line 890 of file tgt_lastrcvd.c.
References CDEBUG, CERROR, D_INFO, ENTRY, exp_connect_flags(), obd_export::exp_obd, LASSERT, LASSERTF, lsd_client_data::lcd_generation, lsd_client_data::lcd_uuid, LR_MAX_CLIENTS, lr_server_data::lsd_client_size, lr_server_data::lsd_client_start, lr_server_data::lsd_feature_incompat, lu_target::lut_client_bitmap, lu_target::lut_client_generation, lu_target::lut_lsd, lu_target::lut_num_clients, lu_target::lut_obd, OBD_CONNECT_LIGHTWEIGHT, OBD_FAIL_CHECK, OBD_FAIL_MDS_CLIENT_ADD, OBD_FAIL_TGT_CLIENT_ADD, OBD_INCOMPAT_MULTI_RPCS, obd_device::obd_name, obd_device::obd_uuid, RETURN, tg_export_data::ted_lcd, tg_export_data::ted_lr_idx, tg_export_data::ted_lr_off, tgt_client_data_update(), tgt_is_multimodrpcs_client(), tgt_server_data_update(), and obd_uuid::uuid.
Referenced by mdt_obd_connect(), and ofd_obd_connect().
static int tgt_clients_data_init (const struct lu_env * env, struct lu_target * tgt, unsigned long last_size) [static]
Definition at line 1369 of file tgt_lastrcvd.c.
References __u64, CDEBUG, CERROR, cfs_hash_add_unique(), cfs_hash_getref(), cfs_hash_putref(), class_export_put(), class_new_export(), class_unlink_export(), CLASSERT, D_HA, D_INFO, D_OTHER, ENTRY, obd_export::exp_connecting, obd_export::exp_gen_hash, obd_export::exp_in_recovery, obd_export::exp_last_committed, obd_export::exp_lock, GOTO, LASSERTF, LAST_RCVD, lsd_client_data::lcd_generation, lcd_last_transno(), lcd_last_xid(), lsd_client_data::lcd_padding, lsd_client_data::lcd_uuid, LPU64, LR_CLIENT_SIZE, lr_server_data::lsd_client_size, lr_server_data::lsd_client_start, lr_server_data::lsd_feature_incompat, lr_server_data::lsd_last_transno, lu_target::lut_client_generation, lu_target::lut_last_transno, lu_target::lut_lsd, lu_target::lut_obd, lu_target::lut_translock, max, OBD_ALLOC_PTR, OBD_FREE_PTR, obd_device::obd_gen_hash, OBD_INCOMPAT_MULTI_RPCS, obd_device::obd_max_recoverable_clients, offsetof, RETURN, tg_export_data::ted_lcd, tgt_client_add(), tgt_client_data_read(), and tgt_name().
Referenced by tgt_server_data_init().
static int tgt_find_free_reply_slot (struct lu_target * lut) [static]
Definition at line 79 of file tgt_lastrcvd.c.
References lu_target::lut_reply_bitmap, LUT_REPLY_SLOTS_MAX_CHUNKS, LUT_REPLY_SLOTS_PER_CHUNK, tgt_bitmap_chunk_alloc(), and unlikely.
Referenced by tgt_add_reply_data().
static void tgt_free_reply_data (struct lu_target * lut, struct tg_export_data * ted, struct tg_reply_data * trd) [static]
Definition at line 305 of file tgt_lastrcvd.c.
References CDEBUG, D_TRACE, LASSERT, list_del(), lsd_reply_data::lrd_client_gen, lsd_reply_data::lrd_transno, lsd_reply_data::lrd_xid, OBD_FREE_PTR, tg_export_data::ted_lcd_lock, tg_export_data::ted_reply_cnt, tgt_clear_reply_slot(), tgt_name(), tg_reply_data::trd_index, tg_reply_data::trd_list, and tg_reply_data::trd_reply.
Referenced by tgt_client_free(), and tgt_release_reply_data().
int tgt_handle_received_xid (struct obd_export * exp, __u64 rcvd_xid)
Definition at line 1995 of file tgt_lastrcvd.c.
References list_for_each_entry_safe, lsd_reply_data::lrd_xid, tg_export_data::ted_lcd_lock, tg_export_data::ted_release_xid, tg_export_data::ted_reply_list, tgt_release_reply_data(), tg_reply_data::trd_list, and tg_reply_data::trd_reply.
Referenced by process_req_last_xid().
int tgt_handle_tag (struct obd_export * exp, __u16 tag)
Definition at line 2013 of file tgt_lastrcvd.c.
References list_for_each_entry_safe, tg_export_data::ted_lcd_lock, tg_export_data::ted_release_tag, tg_export_data::ted_reply_list, tgt_release_reply_data(), tg_reply_data::trd_list, and tg_reply_data::trd_tag.
Referenced by process_req_last_xid().
int tgt_last_commit_cb_add (struct thandle * th, struct lu_target * tgt, struct obd_export * exp, __u64 transno)
Definition at line 798 of file tgt_lastrcvd.c.
References class_export_cb_get, class_export_cb_put, dt_txn_commit_cb::dcb_func, dt_txn_commit_cb::dcb_linkage, dt_txn_commit_cb::dcb_name, dt_trans_cb_add(), exp_connect_flags(), INIT_LIST_HEAD, tgt_last_committed_callback::llcc_cb, tgt_last_committed_callback::llcc_exp, tgt_last_committed_callback::llcc_tgt, tgt_last_committed_callback::llcc_transno, OBD_ALLOC_PTR, OBD_CONNECT_LIGHTWEIGHT, OBD_FREE_PTR, strlcpy(), and tgt_cb_last_committed().
Referenced by tgt_last_rcvd_update(), and tgt_last_rcvd_update_echo().
static int tgt_last_rcvd_update (const struct lu_env * env, struct lu_target * tgt, struct dt_object * obj, __u64 opdata, struct thandle * th, struct ptlrpc_request * req) [static]
VBR: set new versions
Definition at line 1130 of file tgt_lastrcvd.c.
References __u64, CDEBUG, CERROR, D_INODE, dt_object_locate(), dt_version_set(), ENTRY, ergo, exp_connect_flags(), obd_export::exp_lock, obd_export::exp_vbr_failed, LASSERT, lsd_client_data::lcd_generation, lsd_client_data::lcd_last_close_result, lsd_client_data::lcd_last_close_transno, lsd_client_data::lcd_last_close_xid, lsd_client_data::lcd_last_data, lsd_client_data::lcd_last_result, lsd_client_data::lcd_last_transno, lsd_client_data::lcd_last_xid, lsd_client_data::lcd_pre_versions, likely, LPU64, lsd_reply_data::lrd_client_gen, lsd_reply_data::lrd_data, lsd_reply_data::lrd_result, lsd_reply_data::lrd_transno, lsd_reply_data::lrd_xid, lr_server_data::lsd_last_transno, lustre_msg_get_opc(), lustre_msg_get_tag(), lustre_msg_get_transno(), lustre_msg_get_versions(), lustre_msg_set_transno(), lu_target::lut_last_transno, lu_target::lut_lsd, lu_target::lut_no_reconstruct, lu_target::lut_obd, lu_target::lut_translock, MDS_CLOSE, OBD_ALLOC_PTR, OBD_CONNECT_LIGHTWEIGHT, OBD_FREE_PTR, obd_device::obd_last_committed, req_is_replay(), RETURN, ptlrpc_request::rq_export, ptlrpc_request::rq_repmsg, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_transno, ptlrpc_request::rq_xid, tg_export_data::ted_lcd, tg_export_data::ted_lcd_lock, tg_export_data::ted_lr_idx, tg_export_data::ted_lr_off, tgt_add_reply_data(), tgt_client_data_write(), tgt_is_multimodrpcs_client(), tgt_last_commit_cb_add(), tgt_name(), tgt_server_data_write(), tgt_ses_info(), tgt_th_info(), thandle::th_dev, thandle::th_result, thandle::th_sync, tg_reply_data::trd_pre_versions, tg_reply_data::trd_reply, tg_reply_data::trd_tag, tgt_session_info::tsi_client_gen, tgt_session_info::tsi_exp, tgt_session_info::tsi_result, tgt_session_info::tsi_xid, tgt_thread_info::tti_off, tgt_thread_info::tti_transno, and unlikely.
Referenced by tgt_txn_stop_cb().
static int tgt_last_rcvd_update_echo (const struct lu_env * env, struct lu_target * tgt, struct dt_object * obj, struct thandle * th, struct obd_export * exp) [static]
VBR: set new versions
Definition at line 1329 of file tgt_lastrcvd.c.
References dt_version_set(), ENTRY, ergo, LASSERT, lsd_client_data::lcd_last_result, lsd_client_data::lcd_last_transno, lu_target::lut_last_transno, lu_target::lut_translock, RETURN, tg_export_data::ted_lcd, tg_export_data::ted_lcd_lock, tg_export_data::ted_lr_off, tgt_client_data_write(), tgt_last_commit_cb_add(), tgt_th_info(), thandle::th_result, thandle::th_sync, tgt_thread_info::tti_off, and tgt_thread_info::tti_transno.
Referenced by tgt_txn_stop_cb().
bool tgt_lookup_reply (struct ptlrpc_request * req, struct tg_reply_data * trd)
Definition at line 1974 of file tgt_lastrcvd.c.
References CDEBUG, D_TRACE, ptlrpc_request::rq_export, ptlrpc_request::rq_xid, tgt_lookup_reply_by_xid(), and tgt_name().
Referenced by req_can_reconstruct().
struct tg_reply_data* tgt_lookup_reply_by_xid (struct tg_export_data * ted, __u64 xid) [read]
Definition at line 1953 of file tgt_lastrcvd.c.
References list_for_each_entry, lsd_reply_data::lrd_xid, tg_export_data::ted_lcd_lock, tg_export_data::ted_reply_list, tg_reply_data::trd_list, and tg_reply_data::trd_reply.
Referenced by tgt_lookup_reply().
int tgt_new_client_cb_add (struct thandle * th, struct obd_export * exp)
Definition at line 859 of file tgt_lastrcvd.c.
References class_export_cb_get, class_export_cb_put, dt_txn_commit_cb::dcb_func, dt_txn_commit_cb::dcb_linkage, dt_txn_commit_cb::dcb_name, dt_trans_cb_add(), INIT_LIST_HEAD, tgt_new_client_callback::lncc_cb, tgt_new_client_callback::lncc_exp, OBD_ALLOC_PTR, OBD_FREE_PTR, strlcpy(), and tgt_cb_new_client().
Referenced by tgt_client_data_update().
static void tgt_release_reply_data (struct lu_target * lut, struct tg_export_data * ted, struct tg_reply_data * trd) [static]
Definition at line 329 of file tgt_lastrcvd.c.
References CDEBUG, D_TRACE, LASSERT, lsd_client_data::lcd_last_transno, list_del_init(), lsd_reply_data::lrd_client_gen, lsd_reply_data::lrd_transno, lsd_reply_data::lrd_xid, tg_export_data::ted_lcd, tg_export_data::ted_lcd_lock, tg_export_data::ted_reply_last, tgt_free_reply_data(), tgt_name(), tg_reply_data::trd_index, tg_reply_data::trd_list, and tg_reply_data::trd_reply.
Referenced by tgt_client_free(), tgt_handle_received_xid(), and tgt_handle_tag().
int tgt_reply_data_init (const struct lu_env * env, struct lu_target * tgt)
Definition at line 1806 of file tgt_lastrcvd.c.
References CDEBUG, CERROR, cfs_hash_getref(), cfs_hash_lookup(), cfs_hash_putref(), class_export_put(), D_HA, D_INFO, dt_attr_get(), obd_export::exp_last_committed, GOTO, lu_attr::la_size, list_add(), lsd_reply_data::lrd_client_gen, lsd_reply_data::lrd_transno, lsd_reply_data::lrd_xid, lrh, lsd_reply_header::lrh_header_size, LRH_MAGIC, lsd_reply_header::lrh_magic, lsd_reply_header::lrh_reply_size, lu_target::lut_last_transno, lu_target::lut_obd, lu_target::lut_reply_data, lu_target::lut_translock, max, OBD_ALLOC_PTR, OBD_FREE_PTR, obd_device::obd_gen_hash, obd_device::obd_last_committed, REPLY_DATA, tg_export_data::ted_lcd_lock, tg_export_data::ted_reply_cnt, tg_export_data::ted_reply_list, tg_export_data::ted_reply_max, tgt_name(), tgt_reply_data_read(), tgt_reply_header_read(), tgt_reply_header_write(), tgt_set_reply_slot(), tgt_th_info(), tg_reply_data::trd_index, tg_reply_data::trd_list, tg_reply_data::trd_pre_versions, tg_reply_data::trd_reply, tg_reply_data::trd_tag, tgt_thread_info::tti_attr, and tgt_thread_info::tti_lrd.
Referenced by tgt_init().
static int tgt_reply_data_read (const struct lu_env * env, struct lu_target * tgt, struct lsd_reply_data * lrd, loff_t off) [static]
Definition at line 275 of file tgt_lastrcvd.c.
References buf, dt_record_read(), lu_buf::lb_buf, lu_buf::lb_len, le32_to_cpu, le64_to_cpu, lsd_reply_data::lrd_client_gen, lsd_reply_data::lrd_data, lsd_reply_data::lrd_result, lsd_reply_data::lrd_transno, lsd_reply_data::lrd_xid, lu_target::lut_reply_data, tgt_th_info(), tgt_thread_info::tti_buf, tgt_thread_info::tti_lrd, and tgt_thread_info::tti_off.
Referenced by tgt_reply_data_init().
static int tgt_reply_data_write (const struct lu_env * env, struct lu_target * tgt, struct lsd_reply_data * lrd, loff_t off, struct thandle * th) [static]
Definition at line 246 of file tgt_lastrcvd.c.
References buf, cpu_to_le32, cpu_to_le64, dt_object_locate(), dt_record_write(), lu_buf::lb_buf, lu_buf::lb_len, lsd_reply_data::lrd_client_gen, lsd_reply_data::lrd_data, lsd_reply_data::lrd_result, lsd_reply_data::lrd_transno, lsd_reply_data::lrd_xid, lu_target::lut_reply_data, ptlrpc_status_hton(), ptlrpc_status_ntoh(), tgt_th_info(), thandle::th_dev, tgt_thread_info::tti_buf, tgt_thread_info::tti_lrd, and tgt_thread_info::tti_off.
Referenced by tgt_add_reply_data().
static int tgt_reply_header_read (const struct lu_env * env, struct lu_target * tgt, struct lsd_reply_header * lrh) [static]
Definition at line 169 of file tgt_lastrcvd.c.
References CDEBUG, D_HA, dt_record_read(), lu_buf::lb_buf, lu_buf::lb_len, le32_to_cpu, lsd_reply_header::lrh_header_size, lsd_reply_header::lrh_magic, lsd_reply_header::lrh_reply_size, lu_target::lut_obd, lu_target::lut_reply_data, obd_device::obd_name, REPLY_DATA, tgt_th_info(), tgt_thread_info::tti_buf, and tgt_thread_info::tti_off.
Referenced by tgt_reply_data_init().
static int tgt_reply_header_write (const struct lu_env * env, struct lu_target * tgt, struct lsd_reply_header * lrh) [static]
Definition at line 199 of file tgt_lastrcvd.c.
References CDEBUG, cpu_to_le32, D_HA, dt_declare_record_write(), dt_object_locate(), dt_record_write(), dt_trans_create(), dt_trans_start(), dt_trans_stop(), GOTO, lu_buf::lb_buf, lu_buf::lb_len, lsd_reply_header::lrh_header_size, lsd_reply_header::lrh_magic, lsd_reply_header::lrh_reply_size, lu_target::lut_bottom, lu_target::lut_obd, lu_target::lut_reply_data, obd_device::obd_name, REPLY_DATA, tgt_th_info(), thandle::th_dev, thandle::th_sync, tgt_thread_info::tti_buf, and tgt_thread_info::tti_off.
Referenced by tgt_reply_data_init().
int tgt_server_data_init (const struct lu_env * env, struct lu_target * tgt)
Interop: evict all clients at first boot with 1.8 last_rcvd
set 2.0 flag to upgrade/downgrade between 1.8 and 2.0
Definition at line 1525 of file tgt_lastrcvd.c.
References CDEBUG, CERROR, class_disconnect_exports(), CLASSERT, CWARN, D_INODE, dt_attr_get(), GOTO, server_compat_data::incinit, server_compat_data::incompat, lu_attr::la_size, LCONSOLE_ERROR_MSG, LCONSOLE_WARN, LDD_F_SV_TYPE_MDT, LDD_F_SV_TYPE_OST, LPU64, LR_CLIENT_SIZE, LR_CLIENT_START, LR_SERVER_SIZE, lr_server_data::lsd_client_size, lr_server_data::lsd_client_start, lr_server_data::lsd_feature_compat, lr_server_data::lsd_feature_incompat, lr_server_data::lsd_feature_rocompat, lr_server_data::lsd_last_transno, lr_server_data::lsd_mount_count, lr_server_data::lsd_osd_index, lr_server_data::lsd_padding, lr_server_data::lsd_server_size, lr_server_data::lsd_subdir_count, lr_server_data::lsd_uuid, lu_target::lut_last_rcvd, lu_target::lut_last_transno, lu_target::lut_lsd, lu_target::lut_no_reconstruct, lu_target::lut_obd, lu_target::lut_translock, OBD_COMPAT_20, OBD_INCOMPAT_FID, obd_device::obd_last_committed, obd_device::obd_replayable, obd_device::obd_uuid, OBJ_SUBDIR_COUNT, offsetof, RETURN, server_compat_data::rocinit, server_compat_data::rocompat, server_name2index(), tgt_clients_data_init(), tgt_name(), tgt_server_data_read(), tgt_server_data_update(), tgt_th_info(), tgt_truncate_last_rcvd(), tgt_thread_info::tti_attr, obd_device::u, and obd_uuid::uuid.
Referenced by tgt_init().
int tgt_server_data_read (const struct lu_env * env, struct lu_target * tgt)
Definition at line 547 of file tgt_lastrcvd.c.
References CDEBUG, D_INFO, dt_record_read(), LPU64, lr_server_data::lsd_last_transno, lsd_le_to_cpu(), lr_server_data::lsd_uuid, lu_target::lut_last_rcvd, lu_target::lut_lsd, lu_target::lut_obd, obd_device::obd_name, tgt_th_info(), tgt_thread_info::tti_buf, tti_buf_lsd(), tgt_thread_info::tti_lsd, and tgt_thread_info::tti_off.
Referenced by tgt_server_data_init().
int tgt_server_data_update (const struct lu_env * env, struct lu_target * tgt, int sync)
Update server data in last_rcvd.
Definition at line 591 of file tgt_lastrcvd.c.
References CDEBUG, D_INFO, D_SUPER, dt_declare_record_write(), dt_trans_create(), dt_trans_start(), dt_trans_stop(), ENTRY, GOTO, LPU64, lr_server_data::lsd_last_transno, lr_server_data::lsd_uuid, lu_target::lut_bottom, lu_target::lut_last_rcvd, lu_target::lut_last_transno, lu_target::lut_lsd, lu_target::lut_obd, lu_target::lut_translock, obd_device::obd_name, RETURN, tgt_server_data_write(), tgt_th_info(), thandle::th_sync, tgt_thread_info::tti_buf, tti_buf_lsd(), tgt_thread_info::tti_off, and obd_device::u.
Referenced by ofd_parse_connect_data(), tgt_boot_epoch_update(), tgt_client_del(), tgt_client_new(), tgt_fini(), and tgt_server_data_init().
int tgt_server_data_write (const struct lu_env * env, struct lu_target * tgt, struct thandle * th)
Definition at line 565 of file tgt_lastrcvd.c.
References CDEBUG, D_INFO, dt_object_locate(), dt_record_write(), ENTRY, LPU64, lsd_cpu_to_le(), lr_server_data::lsd_last_transno, lr_server_data::lsd_uuid, lu_target::lut_last_rcvd, lu_target::lut_lsd, lu_target::lut_obd, obd_device::obd_name, RETURN, tgt_th_info(), thandle::th_dev, tgt_thread_info::tti_buf, tti_buf_lsd(), tgt_thread_info::tti_lsd, and tgt_thread_info::tti_off.
Referenced by tgt_last_rcvd_update(), and tgt_server_data_update().
static int tgt_set_reply_slot (struct lu_target * lut, int idx) [static]
Definition at line 114 of file tgt_lastrcvd.c.
References CERROR, LASSERT, lu_target::lut_reply_bitmap, LUT_REPLY_SLOTS_MAX_CHUNKS, LUT_REPLY_SLOTS_PER_CHUNK, tgt_bitmap_chunk_alloc(), tgt_name(), and unlikely.
Referenced by tgt_reply_data_init().
int tgt_truncate_last_rcvd (const struct lu_env * env, struct lu_target * tgt, loff_t size)
Definition at line 637 of file tgt_lastrcvd.c.
References cleanup(), dt_attr_set(), dt_declare_attr_set(), dt_declare_punch(), dt_punch(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), ENTRY, GOTO, LA_SIZE, lu_attr::la_size, lu_attr::la_valid, lu_target::lut_bottom, lu_target::lut_last_rcvd, OBD_OBJECT_EOF, and RETURN.
Referenced by tgt_server_data_init().
int tgt_txn_start_cb (const struct lu_env * env, struct thandle * th, void * cookie)
Definition at line 1697 of file tgt_lastrcvd.c.
References dt_object::do_lu, dt_declare_record_write(), dt_declare_version_set(), dt_object_locate(), LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lu_env::le_ses, lu_object_remote, lu_target::lut_last_rcvd, lu_target::lut_num_clients, lu_target::lut_reply_data, tgt_is_multimodrpcs_client(), tgt_ses_info(), tgt_th_info(), thandle::th_dev, tgt_session_info::tsi_exp, tgt_session_info::tsi_vbr_obj, tgt_thread_info::tti_buf, tti_buf_lcd(), tti_buf_lsd(), and tgt_thread_info::tti_off.
Referenced by tgt_init().
int tgt_txn_stop_cb (const struct lu_env * env, struct thandle * th, void * cookie)
Definition at line 1760 of file tgt_lastrcvd.c.
References CDEBUG, D_HA, dt_object::do_lu, lu_env::le_ses, LPU64, lu_object_remote, RETURN, tgt_last_rcvd_update(), tgt_last_rcvd_update_echo(), tgt_ses_info(), tgt_ses_req(), tgt_th_info(), thandle::th_result, tgt_session_info::tsi_exp, tgt_session_info::tsi_opdata, tgt_session_info::tsi_vbr_obj, tgt_session_info::tsi_xid, tgt_thread_info::tti_has_trans, tgt_thread_info::tti_mult_trans, tgt_thread_info::tti_transno, and unlikely.
Referenced by tgt_init().
static struct lu_buf* tti_buf_lcd (struct tgt_thread_info * tti) [static, read]
Definition at line 366 of file tgt_lastrcvd.c.
References lu_buf::lb_buf, lu_buf::lb_len, tgt_thread_info::tti_buf, and tgt_thread_info::tti_lcd.
Referenced by tgt_client_data_read(), tgt_client_data_update(), tgt_client_data_write(), and tgt_txn_start_cb().
static struct lu_buf* tti_buf_lsd (struct tgt_thread_info * tti) [static, read]
Definition at line 359 of file tgt_lastrcvd.c.
References lu_buf::lb_buf, lu_buf::lb_len, tgt_thread_info::tti_buf, and tgt_thread_info::tti_lsd.
Referenced by tgt_server_data_read(), tgt_server_data_update(), tgt_server_data_write(), and tgt_txn_start_cb().
Variable Documentation
struct server_compat_data tgt_scd[] [static]
Initial value:
 {
        [LDD_F_SV_TYPE_MDT] = {
                .rocompat = OBD_ROCOMPAT_LOVOBJID,
                .incompat = OBD_INCOMPAT_MDT | OBD_INCOMPAT_COMMON_LR |
                            OBD_INCOMPAT_FID | OBD_INCOMPAT_IAM_DIR |
                            OBD_INCOMPAT_LMM_VER | OBD_INCOMPAT_MULTI_OI |
                            OBD_INCOMPAT_MULTI_RPCS,
                .rocinit = OBD_ROCOMPAT_LOVOBJID,
                .incinit = OBD_INCOMPAT_MDT | OBD_INCOMPAT_COMMON_LR |
                           OBD_INCOMPAT_MULTI_OI,
        },
        [LDD_F_SV_TYPE_OST] = {
                .rocompat = OBD_ROCOMPAT_IDX_IN_IDIF,
                .incompat = OBD_INCOMPAT_OST | OBD_INCOMPAT_COMMON_LR |
                            OBD_INCOMPAT_FID,
                .rocinit = OBD_ROCOMPAT_IDX_IN_IDIF,
                .incinit = OBD_INCOMPAT_OST | OBD_INCOMPAT_COMMON_LR,
        }
}
Definition at line 1505 of file tgt_lastrcvd.c.
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.