Lustre: lustre/target/tgt_internal.h File Reference
lustre/target/tgt_internal.h File Reference
#include <lustre_net.h>
#include <lustre/lustre_idl.h>
#include <lu_target.h>
#include <lustre_export.h>
#include <lustre_fid.h>
#include <lustre_fld.h>
#include <lustre_req_layout.h>
#include <lustre_sec.h>
Data Structures
struct tgt_thread_info
Common data shared by tg-level handlers.
struct tgt_thread_big_cache
struct update_thread_info
Defines
#define MGS_SERVICE_WATCHDOG_FACTOR (2)
#define out_tx_create(env, obj, attr, fid, dof, ta, th, reply, idx)
#define out_tx_attr_set(env, obj, attr, ta, th, reply, idx)
#define out_tx_xattr_set(env, obj, buf, name, fl, ta, th, reply, idx)
#define out_tx_xattr_del(env, obj, name, ta, th, reply, idx)
#define out_tx_ref_add(env, obj, ta, th, reply, idx)
#define out_tx_ref_del(env, obj, ta, th, reply, idx)
#define out_tx_index_insert(env, obj, rec, key, ta, th, reply, idx)
#define out_tx_index_delete(env, obj, key, ta, th, reply, idx)
#define out_tx_destroy(env, obj, ta, th, reply, idx)
#define out_tx_write(env, obj, buf, pos, ta, th, reply, idx)
Functions
static struct tgt_thread_info * tgt_th_info (const struct lu_env *env)
int tgt_request_handle (struct ptlrpc_request *req)
static int req_xid_is_last (struct ptlrpc_request *req)
static char * dt_obd_name (struct dt_device *dt)
int out_tx_create_exec (const struct lu_env *env, struct thandle *th, struct tx_arg *arg)
struct tx_arg * tx_add_exec (struct thandle_exec_args *ta, tx_exec_func_t func, tx_exec_func_t undo, const char *file, int line)
int out_create_add_exec (const struct lu_env *env, struct dt_object *obj, struct lu_attr *attr, struct lu_fid *parent_fid, struct dt_object_format *dof, struct thandle_exec_args *ta, struct thandle *th, struct object_update_reply *reply, int index, const char *file, int line)
Add create update to thandle.
int out_attr_set_add_exec (const struct lu_env *env, struct dt_object *dt_obj, const struct lu_attr *attr, struct thandle_exec_args *ta, struct thandle *th, struct object_update_reply *reply, int index, const char *file, int line)
int out_write_add_exec (const struct lu_env *env, struct dt_object *dt_obj, const struct lu_buf *buf, loff_t pos, struct thandle_exec_args *ta, struct thandle *th, struct object_update_reply *reply, int index, const char *file, int line)
int out_xattr_set_add_exec (const struct lu_env *env, struct dt_object *dt_obj, const struct lu_buf *buf, const char *name, int flags, struct thandle_exec_args *ta, struct thandle *th, struct object_update_reply *reply, int index, const char *file, int line)
int out_xattr_del_add_exec (const struct lu_env *env, struct dt_object *dt_obj, const char *name, struct thandle_exec_args *ta, struct thandle *th, struct object_update_reply *reply, int index, const char *file, int line)
int out_ref_add_add_exec (const struct lu_env *env, struct dt_object *dt_obj, struct thandle_exec_args *ta, struct thandle *th, struct object_update_reply *reply, int index, const char *file, int line)
int out_ref_del_add_exec (const struct lu_env *env, struct dt_object *dt_obj, struct thandle_exec_args *ta, struct thandle *th, struct object_update_reply *reply, int index, const char *file, int line)
int out_index_insert_add_exec (const struct lu_env *env, struct dt_object *dt_obj, const struct dt_rec *rec, const struct dt_key *key, struct thandle_exec_args *ta, struct thandle *th, struct object_update_reply *reply, int index, const char *file, int line)
int out_index_delete_add_exec (const struct lu_env *env, struct dt_object *dt_obj, const struct dt_key *key, struct thandle_exec_args *ta, struct thandle *th, struct object_update_reply *reply, int index, const char *file, int line)
int out_destroy_add_exec (const struct lu_env *env, struct dt_object *dt_obj, struct thandle_exec_args *ta, struct thandle *th, struct object_update_reply *reply, int index, const char *file, int line)
int out_handle (struct tgt_session_info *tsi)
Object updates between Targets.
const char * update_op_str (__u16 opcode)
int tgt_server_data_init (const struct lu_env *env, struct lu_target *tgt)
int tgt_txn_start_cb (const struct lu_env *env, struct thandle *th, void *cookie)
int tgt_txn_stop_cb (const struct lu_env *env, struct thandle *th, void *cookie)
int tgt_handle_received_xid (struct obd_export *exp, __u64 rcvd_xid)
int tgt_handle_tag (struct obd_export *exp, __u16 tag)
void update_records_dump (const struct update_records *records, unsigned int mask, bool dump_updates)
Dump update record.
int check_and_prepare_update_record (const struct lu_env *env, struct thandle_update_records *tur)
Check and prepare whether it needs to record update.
static struct update_thread_info * update_env_info (const struct lu_env *env)
void update_info_init (void)
void update_info_fini (void)
struct sub_thandle * create_sub_thandle (struct top_multiple_thandle *tmt, struct dt_device *dt_dev)
int sub_thandle_trans_create (const struct lu_env *env, struct top_thandle *top_th, struct sub_thandle *st)
Create sub thandle.
void distribute_txn_insert_by_batchid (struct top_multiple_thandle *new)
Insert distribute transaction to the distribute txn list.
int top_trans_create_tmt (const struct lu_env *env, struct top_thandle *top_th)
Create top_multiple_thandle for top_thandle.
void tgt_cancel_slc_locks (__u64 transno)
Variables
int(* tgt_lfsck_in_notify)(const struct lu_env *env, struct dt_device *key, struct lfsck_request *lr, struct thandle *th)
struct lu_context_key tgt_thread_key
struct page * tgt_page_to_corrupt
struct lu_context_key update_thread_key
Define Documentation
#define MGS_SERVICE_WATCHDOG_FACTOR (2)
Definition at line 104 of file tgt_internal.h.
#define out_tx_attr_set (env, obj, attr, ta, th, reply, idx)
Value:
out_attr_set_add_exec(env, obj, attr, ta, th, reply, idx, \
                              __FILE__, __LINE__)
Definition at line 201 of file tgt_internal.h.
Referenced by out_attr_set(), and update_recovery_attr_set().
#define out_tx_create (env, obj, attr, fid, dof, ta, th, reply, idx)
Value:
out_create_add_exec(env, obj, attr, fid, dof, ta, th, reply, idx, \
                            __FILE__, __LINE__)
Definition at line 197 of file tgt_internal.h.
Referenced by out_create(), and update_recovery_create().
#define out_tx_destroy (env, obj, ta, th, reply, idx)
Value:
out_destroy_add_exec(env, obj, ta, th, reply, idx,      \
                             __FILE__, __LINE__)
Definition at line 229 of file tgt_internal.h.
Referenced by out_destroy(), and update_recovery_destroy().
#define out_tx_index_delete (env, obj, key, ta, th, reply, idx)
Value:
out_index_delete_add_exec(env, obj, key, ta, th, reply, idx, \
                                  __FILE__, __LINE__)
Definition at line 225 of file tgt_internal.h.
Referenced by out_index_delete(), and update_recovery_index_delete().
#define out_tx_index_insert (env, obj, rec, key, ta, th, reply, idx)
Value:
out_index_insert_add_exec(env, obj, rec, key, ta, th, reply, idx, \
                                  __FILE__, __LINE__)
Definition at line 221 of file tgt_internal.h.
Referenced by out_index_insert(), and update_recovery_index_insert().
#define out_tx_ref_add (env, obj, ta, th, reply, idx)
Value:
out_ref_add_add_exec(env, obj, ta, th, reply, idx,      \
                             __FILE__, __LINE__)
Definition at line 213 of file tgt_internal.h.
Referenced by out_ref_add(), and update_recovery_ref_add().
#define out_tx_ref_del (env, obj, ta, th, reply, idx)
Value:
out_ref_del_add_exec(env, obj, ta, th, reply, idx,      \
                             __FILE__, __LINE__)
Definition at line 217 of file tgt_internal.h.
Referenced by out_ref_del(), and update_recovery_ref_del().
#define out_tx_write (env, obj, buf, pos, ta, th, reply, idx)
Value:
out_write_add_exec(env, obj, buf, pos, ta, th, reply, idx,\
                           __FILE__, __LINE__)
Definition at line 233 of file tgt_internal.h.
Referenced by out_write(), and update_recovery_write().
#define out_tx_xattr_del (env, obj, name, ta, th, reply, idx)
Value:
out_xattr_del_add_exec(env, obj, name, ta, th, reply, idx,      \
                               __FILE__, __LINE__)
Definition at line 209 of file tgt_internal.h.
Referenced by out_xattr_del(), and update_recovery_xattr_del().
#define out_tx_xattr_set (env, obj, buf, name, fl, ta, th, reply, idx)
Value:
out_xattr_set_add_exec(env, obj, buf, name, fl, ta, th, reply, idx, \
                               __FILE__, __LINE__)
Definition at line 205 of file tgt_internal.h.
Referenced by out_xattr_set(), and update_recovery_xattr_set().
Function Documentation
int check_and_prepare_update_record (const struct lu_env * env, struct thandle_update_records * tur)
Check and prepare whether it needs to record update.
Checks if the transaction needs to record updates, and if it does, then initialize the update record buffer in the transaction.
Parameters:
[in] env execution environment
[in] th transaction handle
Return values:
0 if updates recording succeeds.
negative errno if updates recording fails.
Definition at line 1161 of file update_records.c.
References LLOG_MIN_CHUNK_SIZE, llog_rec_hdr::lrh_len, lur, llog_update_record::lur_hdr, llog_update_record::lur_update_rec, RETURN, thandle_update_records::tur_update_param_count, thandle_update_records::tur_update_params, tur_update_params_create(), thandle_update_records::tur_update_records, tur_update_records_create(), update_records::ur_batchid, update_records::ur_flags, update_records::ur_master_transno, update_records::ur_param_count, and update_records::ur_update_count.
Referenced by prepare_multiple_node_trans().
struct sub_thandle* create_sub_thandle (struct top_multiple_thandle * tmt, struct dt_device * dt_dev) [read]
Definition at line 436 of file update_trans.c.
References INIT_LIST_HEAD, list_add(), OBD_ALLOC_PTR, RETURN, sub_thandle::st_cookie_list, sub_thandle::st_dt, sub_thandle::st_sub_list, and top_multiple_thandle::tmt_sub_thandle_list.
Referenced by create_sub_thandle_with_thandle(), and update_recovery_exec().
void distribute_txn_insert_by_batchid (struct top_multiple_thandle * new)
Insert distribute transaction to the distribute txn list.
Insert distribute transaction to the distribute txn list.
Parameters:
[in] new the distribute txn to be inserted.
Definition at line 694 of file update_trans.c.
References D_INFO, dt2lu_dev(), LASSERT, lu_device::ld_site, list_add(), list_empty(), list_for_each_entry, list_for_each_entry_reverse, lu_site::ls_tgt, lu_target::lut_tdtd, sub_thandle::st_sub_list, sub_thandle::st_sub_th, sub_thandle_register_commit_cb(), target_distribute_txn_data::tdtd_batchid_lock, target_distribute_txn_data::tdtd_commit_thread_waitq, target_distribute_txn_data::tdtd_list, top_multiple_thandle::tmt_batchid, top_multiple_thandle::tmt_commit_list, top_multiple_thandle_dump(), and top_multiple_thandle_get().
Referenced by distribute_txn_replay_handle().
static char* dt_obd_name (struct dt_device * dt) [inline, static]
Definition at line 118 of file tgt_internal.h.
References dt_device::dd_lu_dev, lu_device::ld_obd, and obd_device::obd_name.
Referenced by distribute_txn_replay_handle(), out_obj_destroy(), out_obj_index_delete(), out_obj_index_insert(), out_reconstruct(), out_tx_attr_set_exec(), out_tx_attr_set_undo(), out_tx_create_exec(), out_tx_create_undo(), out_tx_destroy_exec(), out_tx_destroy_undo(), out_tx_end(), out_tx_index_delete_exec(), out_tx_index_delete_undo(), out_tx_index_insert_exec(), out_tx_ref_add_exec(), out_tx_ref_del_exec(), out_tx_start(), out_tx_xattr_del_exec(), and out_tx_xattr_set_exec().
int out_attr_set_add_exec (const struct lu_env * env, struct dt_object * dt_obj, const struct lu_attr * attr, struct thandle_exec_args * ta, struct thandle * th, struct object_update_reply * reply, int index, const char * file, int line)
Definition at line 649 of file out_lib.c.
References tx_arg::attr_set, dt_object::do_lu, dt_declare_attr_set(), tx_arg::index, lu_object_get(), tx_arg::object, out_tx_attr_set_exec(), out_tx_attr_set_undo(), tx_arg::reply, tx_add_exec(), and tx_arg::u.
int out_create_add_exec (const struct lu_env * env, struct dt_object * obj, struct lu_attr * attr, struct lu_fid * parent_fid, struct dt_object_format * dof, struct thandle_exec_args * ta, struct thandle * th, struct object_update_reply * reply, int index, const char * file, int line)
Add create update to thandle.
Declare create updates and add the update to the thandle updates exec array.
Parameters:
[in] env execution environment
[in] obj object to be created
[in] attr attributes of the creation
[in] parent_fid the fid of the parent
[in] dof dt object format of the creation
[in] ta thandle execuation args where all of updates of the transaction are stored
[in] th thandle for this update
[in] reply reply of the updates
[in] index index of the reply
[in] file the file name where the function is called, which is only for debugging purpose.
[in] line the line number where the funtion is called, which is only for debugging purpose.
Return values:
0 if updates is added successfully.
negative errno if update adding fails.
Definition at line 582 of file out_lib.c.
References tx_arg::create, dt_object::do_lu, dt_declare_create(), tx_arg::index, lu_object_get(), tx_arg::object, out_tx_create_exec(), out_tx_create_undo(), tx_arg::reply, tx_add_exec(), and tx_arg::u.
int out_destroy_add_exec (const struct lu_env * env, struct dt_object * dt_obj, struct thandle_exec_args * ta, struct thandle * th, struct object_update_reply * reply, int index, const char * file, int line)
Definition at line 1201 of file out_lib.c.
References dt_object::do_lu, dt_declare_destroy(), tx_arg::index, lu_object_get(), tx_arg::object, out_tx_destroy_exec(), out_tx_destroy_undo(), tx_arg::reply, and tx_add_exec().
int out_handle (struct tgt_session_info * tsi)
Object updates between Targets.
Because all the updates has been dis-assemblied into object updates at sender side, so OUT will call OSD API directly to execute these updates.
In DNE phase I all of the updates in the request need to be executed in one transaction, and the transaction has to be synchronously.
Please refer to lustre/include/lustre/lustre_idl.h for req/reply format.
Definition at line 894 of file out_handler.c.
References ptlrpc_bulk_frag_ops::add_iov_frag, ptlrpc_bulk_desc::bd_frag_ops, CERROR, dt_device::dd_record_fid_accessed, DFID, dt_object::do_lu, dt_locate(), ENTRY, err_serious(), fid_is_sane(), GOTO, LE_FID_ACCESSED, lfsck_pack_rfa(), LFSCK_TYPE_LAYOUT, lu_object_fid(), lu_object_put(), lustre_swab_object_update, lustre_swab_object_update_request, lu_target::lut_bottom, MDS_BULK_PORTAL, MUTABOR, OBD_ALLOC, OBD_FREE, object_update_request_get(), object_update::ou_batchid, object_update::ou_fid, object_update::ou_flags, object_update::ou_result_size, object_update::ou_type, out_update_buffer::oub_size, out_update_header::ouh_count, out_update_header::ouh_inline_data, out_update_header::ouh_inline_length, out_update_header::ouh_magic, out_update_header::ouh_reply_size, object_update_reply::ourp_count, object_update_reply::ourp_lens, object_update_reply::ourp_magic, object_update_request::ourq_count, object_update_request::ourq_magic, out_check_resent(), out_handler_find(), OUT_MAXREQSIZE, out_reconstruct(), out_tx_end(), out_tx_start(), OUT_UPDATE_HEADER_MAGIC, PFID, PTLRPC_BULK_BUF_KVEC, PTLRPC_BULK_GET_SINK, ptlrpc_bulk_kvec_ops, PTLRPC_BULK_OPS_COUNT, ptlrpc_free_bulk(), ptlrpc_req_need_swab(), req_capsule::rc_req, RCL_CLIENT, RCL_SERVER, req_capsule_client_get(), req_capsule_get_size(), req_capsule_server_get(), req_capsule_server_pack(), req_capsule_set(), req_capsule_set_size(), req_is_replay(), RETURN, RMF_OUT_UPDATE_BUF, RMF_OUT_UPDATE_HEADER, RMF_OUT_UPDATE_REPLY, ptlrpc_request::rq_bulk_write, ptlrpc_request::rq_export, RQF_OUT_UPDATE, thandle_exec_args::ta_handle, tgt_lfsck_in_notify, tgt_name(), tgt_ses_req(), tgt_th_info(), tgt_handler::th_act, tgt_handler::th_flags, thandle::th_sync, tgt_session_info::tsi_env, tgt_session_info::tsi_exp, tgt_session_info::tsi_pill, tgt_session_info::tsi_tgt, tgt_thread_info::tti_lr, tgt_thread_info::tti_mult_trans, tgt_thread_info::tti_tea, tgt_thread_info::tti_u, unlikely, tgt_thread_info::update, UPDATE_FL_SYNC, UPDATE_REPLY_MAGIC, and UPDATE_REQUEST_MAGIC.
Referenced by handle_nullreq().
int out_index_delete_add_exec (const struct lu_env * env, struct dt_object * dt_obj, const struct dt_key * key, struct thandle_exec_args * ta, struct thandle * th, struct object_update_reply * reply, int index, const char * file, int line)
Definition at line 1141 of file out_lib.c.
References dt_object::do_lu, dt_declare_delete(), dt_try_as_dir(), tx_arg::index, tx_arg::insert, LASSERT, lu_object_get(), tx_arg::object, out_tx_index_delete_exec(), out_tx_index_delete_undo(), tx_arg::reply, thandle_exec_args::ta_handle, tx_add_exec(), and tx_arg::u.
int out_index_insert_add_exec (const struct lu_env * env, struct dt_object * dt_obj, const struct dt_rec * rec, const struct dt_key * key, struct thandle_exec_args * ta, struct thandle * th, struct object_update_reply * reply, int index, const char * file, int line)
Definition at line 1078 of file out_lib.c.
References dt_object::do_lu, dt_declare_insert(), dt_try_as_dir(), tx_arg::index, tx_arg::insert, lu_object_get(), tx_arg::object, out_tx_index_insert_exec(), out_tx_index_insert_undo(), tx_arg::reply, tx_add_exec(), and tx_arg::u.
int out_ref_add_add_exec (const struct lu_env * env, struct dt_object * dt_obj, struct thandle_exec_args * ta, struct thandle * th, struct object_update_reply * reply, int index, const char * file, int line)
Definition at line 932 of file out_lib.c.
References dt_object::do_lu, dt_declare_ref_add(), tx_arg::index, lu_object_get(), tx_arg::object, out_tx_ref_add_exec(), out_tx_ref_add_undo(), tx_arg::reply, and tx_add_exec().
int out_ref_del_add_exec (const struct lu_env * env, struct dt_object * dt_obj, struct thandle_exec_args * ta, struct thandle * th, struct object_update_reply * reply, int index, const char * file, int line)
Definition at line 981 of file out_lib.c.
References dt_object::do_lu, dt_declare_ref_del(), tx_arg::index, lu_object_get(), tx_arg::object, out_tx_ref_del_exec(), out_tx_ref_del_undo(), tx_arg::reply, and tx_add_exec().
int out_tx_create_exec (const struct lu_env * env, struct thandle * th, struct tx_arg * arg)
Definition at line 530 of file out_lib.c.
References CDEBUG, tx_arg::create, D_INFO, D_OTHER, DFID, dt_object::do_lu, dt_create(), dt_obd_name(), dt_write_lock(), dt_write_unlock(), tx_arg::index, lu_object_fid(), MOR_TGT_CHILD, tx_arg::object, object_update_result_insert(), PFID, tx_arg::reply, thandle::th_dev, and tx_arg::u.
Referenced by out_create_add_exec(), and out_trans_stop().
int out_write_add_exec (const struct lu_env * env, struct dt_object * dt_obj, const struct lu_buf * buf, loff_t pos, struct thandle_exec_args * ta, struct thandle * th, struct object_update_reply * reply, int index, const char * file, int line)
Definition at line 704 of file out_lib.c.
References dt_object::do_lu, dt_declare_record_write(), tx_arg::index, lu_object_get(), tx_arg::object, out_tx_write_exec(), tx_arg::reply, tx_add_exec(), tx_arg::u, and tx_arg::write.
int out_xattr_del_add_exec (const struct lu_env * env, struct dt_object * dt_obj, const char * name, struct thandle_exec_args * ta, struct thandle * th, struct object_update_reply * reply, int index, const char * file, int line)
Definition at line 858 of file out_lib.c.
References dt_object::do_lu, dt_declare_xattr_del(), tx_arg::index, lu_object_get(), tx_arg::object, out_tx_xattr_del_exec(), tx_arg::reply, tx_add_exec(), tx_arg::u, and tx_arg::xattr_set.
int out_xattr_set_add_exec (const struct lu_env * env, struct dt_object * dt_obj, const struct lu_buf * buf, const char * name, int flags, struct thandle_exec_args * ta, struct thandle * th, struct object_update_reply * reply, int index, const char * file, int line)
Definition at line 783 of file out_lib.c.
References dt_object::do_lu, dt_declare_xattr_set(), tx_arg::index, LE_SKIP_NLINK_DECLARE, lfsck_pack_rfa(), LFSCK_TYPE_NAMESPACE, lu_object_fid(), lu_object_get(), tx_arg::object, out_tx_xattr_set_exec(), tx_arg::reply, thandle_exec_args::ta_handle, tgt_lfsck_in_notify, tgt_ses_info(), tgt_th_info(), tgt_thread_info::tti_lr, tx_add_exec(), tx_arg::u, XATTR_NAME_LINK, and tx_arg::xattr_set.
static int req_xid_is_last (struct ptlrpc_request * req) [inline, static]
Definition at line 109 of file tgt_internal.h.
References LASSERT, lsd_client_data::lcd_last_close_xid, lsd_client_data::lcd_last_xid, ptlrpc_request::rq_export, and ptlrpc_request::rq_xid.
Referenced by out_check_resent().
int sub_thandle_trans_create (const struct lu_env * env, struct top_thandle * top_th, struct sub_thandle * st)
Create sub thandle.
Create transaction handle for sub_thandle
Parameters:
[in] env execution environment
[in] th top thandle
[in] st sub_thandle
Return values:
0 if creation succeeds.
negative errno if creation fails.
Definition at line 567 of file update_trans.c.
References dt_trans_create(), sub_thandle::st_dt, sub_thandle::st_sub_th, sub_thandle_register_stop_cb(), thandle::th_top, thandle::th_wait_submit, top_thandle::tt_multiple_thandle, and top_thandle::tt_super.
void tgt_cancel_slc_locks (__u64 transno)
Definition at line 111 of file tgt_main.c.
References ldlm_lock::l_readers, l_slc_link, ldlm_lock::l_writers, LASSERT, LCF_ASYNC, ldlm_cli_cancel(), ldlm_lock2handle(), LDLM_LOCK_PUT, ldlm_set_cbpending, list, list_del_init(), list_for_each_entry_safe, LIST_HEAD(), list_move(), lock_res_and_lock(), uncommitted_slc_locks, uncommitted_slc_locks_guard, and unlock_res_and_lock().
Referenced by tgt_cb_last_committed().
int tgt_handle_received_xid (struct obd_export * exp, __u64 rcvd_xid)
Definition at line 1995 of file tgt_lastrcvd.c.
References list_for_each_entry_safe, lsd_reply_data::lrd_xid, tg_export_data::ted_lcd_lock, tg_export_data::ted_release_xid, tg_export_data::ted_reply_list, tgt_release_reply_data(), tg_reply_data::trd_list, and tg_reply_data::trd_reply.
Referenced by process_req_last_xid().
int tgt_handle_tag (struct obd_export * exp, __u16 tag)
Definition at line 2013 of file tgt_lastrcvd.c.
References list_for_each_entry_safe, tg_export_data::ted_lcd_lock, tg_export_data::ted_release_tag, tg_export_data::ted_reply_list, tgt_release_reply_data(), tg_reply_data::trd_list, and tg_reply_data::trd_tag.
Referenced by process_req_last_xid().
int tgt_request_handle (struct ptlrpc_request * req)
Definition at line 653 of file tgt_handler.c.
References CDEBUG, CFS_FAIL_CHECK_ORSET, CFS_FAIL_ONCE, class_connected_export(), class_exp2obd(), current_pid, D_ERROR, D_HA, DEBUG_REQ, ENTRY, EXIT, exp_connect_flags(), obd_export::exp_last_xid, GOTO, LASSERTF, libcfs_id2str(), likely, lu_env_refill(), lu_object_put(), lustre_msg, lustre_msg_check_version(), lustre_msg_get_jobid(), lustre_msg_get_opc(), lustre_msg_get_version(), lu_target::lut_reply_fail_id, lu_target::lut_request_fail_id, MDS_CONNECT, MGS_CONNECT, msg, OBD_CONNECT_JOBSTATS, OBD_FAIL_CHECK, OBD_FAIL_OST_CONNECT_NET2, OBD_FAIL_SEC_CTX_INIT_NET, obd_device::obd_name, obd_device::obd_recovery_data, OST_CONNECT, process_req_last_xid(), ptlrpc_error(), RCL_SERVER, req_capsule_fini(), req_capsule_init(), req_capsule_set(), ptlrpc_request::rq_export, ptlrpc_request::rq_peer, ptlrpc_request::rq_pill, ptlrpc_request::rq_reqmsg, ptlrpc_request::rq_status, RQF_CONNECT, SEC_CTX_FINI, SEC_CTX_INIT, SEC_CTX_INIT_CONT, tgt_handle_recovery(), tgt_handle_request0(), tgt_handler_find_check(), tgt_name(), tgt_ses_info(), tgt_handler::th_opc, tgt_handler::th_version, target_recovery_data::trd_processing_task, tgt_session_info::tsi_corpus, tgt_session_info::tsi_env, tgt_session_info::tsi_exp, tgt_session_info::tsi_jobid, tgt_session_info::tsi_pill, tgt_session_info::tsi_reply_fail_id, tgt_session_info::tsi_tgt, and unlikely.
int tgt_server_data_init (const struct lu_env * env, struct lu_target * tgt)
Interop: evict all clients at first boot with 1.8 last_rcvd
set 2.0 flag to upgrade/downgrade between 1.8 and 2.0
Definition at line 1525 of file tgt_lastrcvd.c.
References CDEBUG, CERROR, class_disconnect_exports(), CLASSERT, CWARN, D_INODE, dt_attr_get(), GOTO, server_compat_data::incinit, server_compat_data::incompat, lu_attr::la_size, LCONSOLE_ERROR_MSG, LCONSOLE_WARN, LDD_F_SV_TYPE_MDT, LDD_F_SV_TYPE_OST, LPU64, LR_CLIENT_SIZE, LR_CLIENT_START, LR_SERVER_SIZE, lr_server_data::lsd_client_size, lr_server_data::lsd_client_start, lr_server_data::lsd_feature_compat, lr_server_data::lsd_feature_incompat, lr_server_data::lsd_feature_rocompat, lr_server_data::lsd_last_transno, lr_server_data::lsd_mount_count, lr_server_data::lsd_osd_index, lr_server_data::lsd_padding, lr_server_data::lsd_server_size, lr_server_data::lsd_subdir_count, lr_server_data::lsd_uuid, lu_target::lut_last_rcvd, lu_target::lut_last_transno, lu_target::lut_lsd, lu_target::lut_no_reconstruct, lu_target::lut_obd, lu_target::lut_translock, OBD_COMPAT_20, OBD_INCOMPAT_FID, obd_device::obd_last_committed, obd_device::obd_replayable, obd_device::obd_uuid, OBJ_SUBDIR_COUNT, offsetof, RETURN, server_compat_data::rocinit, server_compat_data::rocompat, server_name2index(), tgt_clients_data_init(), tgt_name(), tgt_server_data_read(), tgt_server_data_update(), tgt_th_info(), tgt_truncate_last_rcvd(), tgt_thread_info::tti_attr, obd_device::u, and obd_uuid::uuid.
Referenced by tgt_init().
static struct tgt_thread_info* tgt_th_info (const struct lu_env * env) [static, read]
Definition at line 95 of file tgt_internal.h.
References LASSERT, lu_env::le_ctx, lu_context_key_get(), and tgt_thread_key.
Referenced by distribute_txn_commit_batchid_init(), distribute_txn_replay_handle(), out_attr_get(), out_attr_set(), out_create(), out_destroy(), out_handle(), out_index_delete(), out_index_insert(), out_index_lookup(), out_read(), out_ref_add(), out_ref_del(), out_tx_xattr_set_exec(), out_write(), out_xattr_del(), out_xattr_get(), out_xattr_set(), out_xattr_set_add_exec(), tgt_client_data_read(), tgt_client_data_update(), tgt_client_data_write(), tgt_last_rcvd_update(), tgt_last_rcvd_update_echo(), tgt_obd_idx_read(), tgt_reply_data_init(), tgt_reply_data_read(), tgt_reply_data_write(), tgt_reply_header_read(), tgt_reply_header_write(), tgt_send_buffer(), tgt_sendpage(), tgt_server_data_init(), tgt_server_data_read(), tgt_server_data_update(), tgt_server_data_write(), tgt_txn_start_cb(), tgt_txn_stop_cb(), tgt_validate_obdo(), top_trans_stop(), and update_recovery_update_ses().
int tgt_txn_start_cb (const struct lu_env * env, struct thandle * th, void * cookie)
Definition at line 1697 of file tgt_lastrcvd.c.
References dt_object::do_lu, dt_declare_record_write(), dt_declare_version_set(), dt_object_locate(), LASSERT, lu_buf::lb_buf, lu_buf::lb_len, lu_env::le_ses, lu_object_remote, lu_target::lut_last_rcvd, lu_target::lut_num_clients, lu_target::lut_reply_data, tgt_is_multimodrpcs_client(), tgt_ses_info(), tgt_th_info(), thandle::th_dev, tgt_session_info::tsi_exp, tgt_session_info::tsi_vbr_obj, tgt_thread_info::tti_buf, tti_buf_lcd(), tti_buf_lsd(), and tgt_thread_info::tti_off.
Referenced by tgt_init().
int tgt_txn_stop_cb (const struct lu_env * env, struct thandle * th, void * cookie)
Definition at line 1760 of file tgt_lastrcvd.c.
References CDEBUG, D_HA, dt_object::do_lu, lu_env::le_ses, LPU64, lu_object_remote, RETURN, tgt_last_rcvd_update(), tgt_last_rcvd_update_echo(), tgt_ses_info(), tgt_ses_req(), tgt_th_info(), thandle::th_result, tgt_session_info::tsi_exp, tgt_session_info::tsi_opdata, tgt_session_info::tsi_vbr_obj, tgt_session_info::tsi_xid, tgt_thread_info::tti_has_trans, tgt_thread_info::tti_mult_trans, tgt_thread_info::tti_transno, and unlikely.
Referenced by tgt_init().
int top_trans_create_tmt (const struct lu_env * env, struct top_thandle * top_th)
Create top_multiple_thandle for top_thandle.
Create top_mutilple_thandle to manage the mutiple node transaction for top_thandle, and it also needs to add master sub thandle to the sub trans list now.
Parameters:
[in] env execution environment
[in] top_th the top thandle
Return values:
0 if creation succeeds
negative errno if creation fails
Definition at line 1112 of file update_trans.c.
References INIT_LIST_HEAD, OBD_ALLOC_PTR, top_multiple_thandle::tmt_commit_list, top_multiple_thandle::tmt_magic, top_multiple_thandle::tmt_refcount, top_multiple_thandle::tmt_stop_waitq, top_multiple_thandle::tmt_sub_lock, top_multiple_thandle::tmt_sub_thandle_list, TOP_THANDLE_MAGIC, and top_thandle::tt_multiple_thandle.
Referenced by distribute_txn_replay_handle(), and thandle_get_sub_by_dt().
struct tx_arg* tx_add_exec (struct thandle_exec_args * ta, tx_exec_func_t func, tx_exec_func_t undo, const char * file, int line) [read]
Definition at line 468 of file out_lib.c.
References tx_arg::exec_fn, tx_arg::file, LASSERT, tx_arg::line, thandle_exec_args::ta_alloc_args, thandle_exec_args::ta_argno, thandle_exec_args::ta_args, TX_ALLOC_STEP, tx_extend_args(), and tx_arg::undo_fn.
Referenced by out_attr_set_add_exec(), out_create_add_exec(), out_destroy_add_exec(), out_index_delete_add_exec(), out_index_insert_add_exec(), out_ref_add_add_exec(), out_ref_del_add_exec(), out_write_add_exec(), out_xattr_del_add_exec(), and out_xattr_set_add_exec().
static struct update_thread_info* update_env_info (const struct lu_env * env) [static, read]
Definition at line 271 of file tgt_internal.h.
References LASSERT, lu_env::le_ctx, lu_context_key_get(), and update_thread_key.
Referenced by distribute_txn_replay_handle(), prepare_multiple_node_trans(), update_records_attr_set_pack(), update_records_create_pack(), update_recovery_attr_set(), update_recovery_create(), update_recovery_index_delete(), update_recovery_index_insert(), update_recovery_write(), update_recovery_xattr_del(), and update_recovery_xattr_set().
void update_info_fini (void)
Definition at line 1232 of file update_records.c.
References lu_context_key_degister(), and update_thread_key.
Referenced by tgt_mod_exit().
void update_info_init (void)
Definition at line 1226 of file update_records.c.
References lu_context_key_register(), and update_thread_key.
Referenced by tgt_mod_init().
const char* update_op_str (__u16 opcode)
Definition at line 43 of file out_lib.c.
References ARRAY_SIZE, OUT_ATTR_GET, OUT_ATTR_SET, OUT_CREATE, OUT_DESTROY, OUT_INDEX_DELETE, OUT_INDEX_INSERT, OUT_INDEX_LOOKUP, OUT_NOOP, OUT_PUNCH, OUT_READ, OUT_REF_ADD, OUT_REF_DEL, OUT_START, OUT_WRITE, OUT_XATTR_DEL, OUT_XATTR_GET, and OUT_XATTR_SET.
void update_records_dump (const struct update_records * records, unsigned int mask, bool dump_updates)
Dump update record.
Dump all of updates in the update_records, mostly for debugging purpose.
Parameters:
[in] records update records to be dumpped
[in] mask debug level mask
[in] dump_params if dump all of updates the updates.
Definition at line 63 of file update_records.c.
References CDEBUG, DFID, LPU64, object_update_param::oup_len, PFID, update_ops::uops_op, update_op_next_op(), update_op_str(), update_params_get_param(), update_records_get_params(), update_records::ur_batchid, update_records::ur_flags, update_records::ur_master_transno, update_records::ur_ops, update_records::ur_param_count, and update_records::ur_update_count.
Referenced by distribute_txn_replay_handle(), dtrq_append_updates(), dtrq_list_dump(), prepare_writing_updates(), and sub_updates_write().
Variable Documentation
int(* tgt_lfsck_in_notify)(const struct lu_env *env, struct dt_device *key, struct lfsck_request *lr, struct thandle *th)
Referenced by out_handle(), out_tx_xattr_set_exec(), out_xattr_set_add_exec(), tgt_handle_lfsck_notify(), and tgt_register_lfsck_in_notify().
struct page* tgt_page_to_corrupt
Definition at line 391 of file tgt_main.c.
Referenced by tgt_checksum_bulk(), tgt_mod_exit(), and tgt_mod_init().
struct lu_context_key tgt_thread_key
Definition at line 362 of file tgt_main.c.
Referenced by tgt_th_info().
struct lu_context_key update_thread_key
Referenced by update_env_info(), update_info_fini(), and update_info_init().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.