Lustre: lnet/selftest/timer.c File Reference
lnet/selftest/timer.c File Reference
#include "selftest.h"
Data Structures
struct st_timer_data
Defines
#define DEBUG_SUBSYSTEM S_LNET
#define STTIMER_MINPOLL 3
#define STTIMER_SLOTTIME (1 << STTIMER_MINPOLL)
#define STTIMER_SLOTTIMEMASK (~(STTIMER_SLOTTIME - 1))
#define STTIMER_NSLOTS (1 << 7)
#define STTIMER_SLOT(t)
Functions
void stt_add_timer (stt_timer_t *timer)
int stt_del_timer (stt_timer_t *timer)
static int stt_expire_list (struct list_head *slot, cfs_time_t now)
static int stt_check_timers (cfs_time_t *last)
static int stt_timer_main (void *arg)
static int stt_start_timer_thread (void)
int stt_startup (void)
void stt_shutdown (void)
Variables
static struct st_timer_data stt_data
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 41 of file timer.c.
#define STTIMER_MINPOLL 3
Definition at line 53 of file timer.c.
#define STTIMER_NSLOTS (1 << 7)
Definition at line 56 of file timer.c.
Referenced by stt_shutdown(), and stt_startup().
#define STTIMER_SLOT (t)
Value:
(&stt_data.stt_hash[(((t) >> STTIMER_MINPOLL) & \
                                                    (STTIMER_NSLOTS - 1))])
Definition at line 57 of file timer.c.
Referenced by stt_add_timer(), and stt_check_timers().
#define STTIMER_SLOTTIME (1 << STTIMER_MINPOLL)
Definition at line 54 of file timer.c.
Referenced by stt_check_timers(), and stt_timer_main().
#define STTIMER_SLOTTIMEMASK (~(STTIMER_SLOTTIME - 1))
Definition at line 55 of file timer.c.
Referenced by stt_check_timers(), and stt_startup().
Function Documentation
void stt_add_timer (stt_timer_t * timer)
Definition at line 71 of file timer.c.
References cfs_time_after(), cfs_time_aftereq(), cfs_time_current_sec(), LASSERT, list_add(), list_empty(), list_entry, list_for_each_prev, stt_data, stt_timer_t::stt_expires, stt_timer_t::stt_func, stt_timer_t::stt_list, st_timer_data::stt_lock, st_timer_data::stt_nthreads, st_timer_data::stt_shuttingdown, and STTIMER_SLOT.
Referenced by lstcon_rpc_pinger(), lstcon_rpc_pinger_start(), sfw_add_session_timer(), and srpc_add_client_rpc_timer().
static int stt_check_timers (cfs_time_t * last) [static]
Definition at line 149 of file timer.c.
References cfs_time_aftereq(), cfs_time_current_sec(), cfs_time_sub(), now(), stt_data, stt_expire_list(), st_timer_data::stt_lock, STTIMER_SLOT, STTIMER_SLOTTIME, and STTIMER_SLOTTIMEMASK.
Referenced by stt_timer_main().
int stt_del_timer (stt_timer_t * timer)
Definition at line 105 of file timer.c.
References LASSERT, list_del_init(), list_empty(), ret, stt_data, stt_timer_t::stt_list, st_timer_data::stt_lock, st_timer_data::stt_nthreads, and st_timer_data::stt_shuttingdown.
Referenced by lstcon_rpc_pinger_stop(), sfw_del_session_timer(), and srpc_del_client_rpc_timer().
static int stt_expire_list (struct list_head * slot, cfs_time_t now) [static]
Definition at line 125 of file timer.c.
References cfs_time_after(), list_del_init(), list_empty(), list_entry, list_head::next, stt_timer_t::stt_data, stt_data, stt_timer_t::stt_expires, stt_timer_t::stt_func, stt_timer_t::stt_list, and st_timer_data::stt_lock.
Referenced by stt_check_timers().
void stt_shutdown (void)
Definition at line 233 of file timer.c.
References LASSERT, list_empty(), lst_wait_until, stt_data, st_timer_data::stt_hash, st_timer_data::stt_lock, st_timer_data::stt_nthreads, st_timer_data::stt_shuttingdown, st_timer_data::stt_waitq, and STTIMER_NSLOTS.
Referenced by srpc_shutdown().
static int stt_start_timer_thread (void) [static]
Definition at line 193 of file timer.c.
References LASSERT, stt_data, st_timer_data::stt_lock, st_timer_data::stt_nthreads, st_timer_data::stt_shuttingdown, and stt_timer_main().
Referenced by stt_startup().
int stt_startup (void)
Definition at line 211 of file timer.c.
References CERROR, cfs_time_current_sec(), INIT_LIST_HEAD, stt_data, st_timer_data::stt_hash, st_timer_data::stt_lock, st_timer_data::stt_nthreads, st_timer_data::stt_prev_slot, st_timer_data::stt_shuttingdown, stt_start_timer_thread(), st_timer_data::stt_waitq, STTIMER_NSLOTS, and STTIMER_SLOTTIMEMASK.
Referenced by srpc_startup().
static int stt_timer_main (void * arg) [static]
Definition at line 172 of file timer.c.
References cfs_block_allsigs(), cfs_time_seconds(), stt_check_timers(), stt_data, st_timer_data::stt_lock, st_timer_data::stt_nthreads, st_timer_data::stt_prev_slot, st_timer_data::stt_shuttingdown, st_timer_data::stt_waitq, and STTIMER_SLOTTIME.
Referenced by stt_start_timer_thread().
Variable Documentation
struct st_timer_data stt_data [static]
Referenced by stt_add_timer(), stt_check_timers(), stt_del_timer(), stt_expire_list(), stt_shutdown(), stt_start_timer_thread(), stt_startup(), and stt_timer_main().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.