Lustre: lnet/selftest/timer.h File Reference
lnet/selftest/timer.h File Reference
Data Structures
struct stt_timer_t
Functions
void stt_add_timer (stt_timer_t *timer)
int stt_del_timer (stt_timer_t *timer)
int stt_startup (void)
void stt_shutdown (void)
Function Documentation
void stt_add_timer (stt_timer_t * timer)
Definition at line 71 of file timer.c.
References cfs_time_after(), cfs_time_aftereq(), cfs_time_current_sec(), LASSERT, list_add(), list_empty(), list_entry, list_for_each_prev, stt_data, stt_timer_t::stt_expires, stt_timer_t::stt_func, stt_timer_t::stt_list, st_timer_data::stt_lock, st_timer_data::stt_nthreads, st_timer_data::stt_shuttingdown, and STTIMER_SLOT.
Referenced by lstcon_rpc_pinger(), lstcon_rpc_pinger_start(), sfw_add_session_timer(), and srpc_add_client_rpc_timer().
int stt_del_timer (stt_timer_t * timer)
Definition at line 105 of file timer.c.
References LASSERT, list_del_init(), list_empty(), ret, stt_data, stt_timer_t::stt_list, st_timer_data::stt_lock, st_timer_data::stt_nthreads, and st_timer_data::stt_shuttingdown.
Referenced by lstcon_rpc_pinger_stop(), sfw_del_session_timer(), and srpc_del_client_rpc_timer().
void stt_shutdown (void)
Definition at line 233 of file timer.c.
References LASSERT, list_empty(), lst_wait_until, stt_data, st_timer_data::stt_hash, st_timer_data::stt_lock, st_timer_data::stt_nthreads, st_timer_data::stt_shuttingdown, st_timer_data::stt_waitq, and STTIMER_NSLOTS.
Referenced by srpc_shutdown().
int stt_startup (void)
Definition at line 211 of file timer.c.
References CERROR, cfs_time_current_sec(), INIT_LIST_HEAD, stt_data, st_timer_data::stt_hash, st_timer_data::stt_lock, st_timer_data::stt_nthreads, st_timer_data::stt_prev_slot, st_timer_data::stt_shuttingdown, stt_start_timer_thread(), st_timer_data::stt_waitq, STTIMER_NSLOTS, and STTIMER_SLOTTIMEMASK.
Referenced by srpc_startup().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.