Lustre: libcfs/libcfs/tracefile.h File Reference
libcfs/libcfs/tracefile.h File Reference
#include <libcfs/libcfs.h>
Data Structures
union cfs_trace_data_union
struct cfs_trace_data_union::cfs_trace_cpu_data
struct page_collection
struct tracefiled_ctl
struct cfs_trace_page
Defines
#define TRACEFILE_NAME_SIZE 1024
#define TCD_MAX_PAGES (5 << (20 - PAGE_CACHE_SHIFT))
#define TCD_STOCK_PAGES (TCD_MAX_PAGES)
#define CFS_TRACEFILE_SIZE (500 << 20)
#define TCD_MAX_PAGES (5 << (20 - PAGE_CACHE_SHIFT))
#define TCD_STOCK_PAGES (TCD_MAX_PAGES)
#define CFS_TRACEFILE_SIZE (500 << 20)
#define CFS_TRACE_CONSOLE_BUFFER_SIZE 1024
#define TCD_MAX_TYPES 8
#define cfs_tcd_for_each(tcd, i, j)
#define cfs_tcd_for_each_type_lock(tcd, i, cpu)
#define __LASSERT(cond)
#define __LASSERT_TAGE_INVARIANT(tage)
Enumerations
enum cfs_trace_buf_type { CFS_TCD_TYPE_PROC = 0, CFS_TCD_TYPE_SOFTIRQ, CFS_TCD_TYPE_IRQ, CFS_TCD_TYPE_MAX }
Functions
void libcfs_run_debug_log_upcall (char *file)
Upcall function once a Lustre log has been dumped.
int cfs_tracefile_init_arch (void)
void cfs_tracefile_fini_arch (void)
void cfs_tracefile_read_lock (void)
void cfs_tracefile_read_unlock (void)
void cfs_tracefile_write_lock (void)
void cfs_tracefile_write_unlock (void)
int cfs_tracefile_dump_all_pages (char *filename)
void cfs_trace_debug_print (void)
void cfs_trace_flush_pages (void)
int cfs_trace_start_thread (void)
void cfs_trace_stop_thread (void)
int cfs_tracefile_init (int max_pages)
void cfs_tracefile_exit (void)
int cfs_trace_copyin_string (char *knl_buffer, int knl_buffer_nob, const char __user *usr_buffer, int usr_buffer_nob)
int cfs_trace_copyout_string (char __user *usr_buffer, int usr_buffer_nob, const char *knl_str, char *append)
int cfs_trace_allocate_string_buffer (char **str, int nob)
int cfs_trace_dump_debug_buffer_usrstr (void __user *usr_str, int usr_str_nob)
int cfs_trace_daemon_command (char *str)
int cfs_trace_daemon_command_usrstr (void __user *usr_str, int usr_str_nob)
int cfs_trace_set_debug_mb (int mb)
int cfs_trace_set_debug_mb_usrstr (void __user *usr_str, int usr_str_nob)
int cfs_trace_get_debug_mb (void)
void libcfs_debug_dumplog_internal (void *arg)
Dump Lustre log to debug_file_path by calling tracefile_dump_all_pages().
void libcfs_register_panic_notifier (void)
void libcfs_unregister_panic_notifier (void)
int cfs_trace_max_debug_mb (void)
void cfs_set_ptldebug_header (struct ptldebug_header *header, struct libcfs_debug_msg_data *m, unsigned long stack)
void cfs_print_to_console (struct ptldebug_header *hdr, int mask, const char *buf, int len, const char *file, const char *fn)
int cfs_trace_lock_tcd (struct cfs_trace_cpu_data *tcd, int walking)
void cfs_trace_unlock_tcd (struct cfs_trace_cpu_data *tcd, int walking)
enum cfs_trace_buf_type cfs_trace_buf_idx_get (void)
static char * cfs_trace_get_console_buffer (void)
static struct cfs_trace_cpu_data * cfs_trace_get_tcd (void)
static void cfs_trace_put_tcd (struct cfs_trace_cpu_data *tcd)
int cfs_trace_refill_stock (struct cfs_trace_cpu_data *tcd, gfp_t gfp, struct list_head *stock)
int cfs_tcd_owns_tage (struct cfs_trace_cpu_data *tcd, struct cfs_trace_page *tage)
void cfs_trace_assertion_failed (const char *str, struct libcfs_debug_msg_data *m)
Variables
char cfs_tracefile [TRACEFILE_NAME_SIZE]
long long cfs_tracefile_size
char lnet_upcall [1024]
char lnet_debug_log_upcall [1024]
The path of debug log dump upcall script.
int libcfs_panic_in_progress
union cfs_trace_data_union(*[TCD_MAX_TYPES] cfs_trace_data)[NR_CPUS]
char * cfs_trace_console_buffers [NR_CPUS][CFS_TCD_TYPE_MAX]
Define Documentation
#define __LASSERT (cond)
Value:
do {                                                                    \
        if (unlikely(!(cond))) {                                        \
                LIBCFS_DEBUG_MSG_DATA_DECL(msgdata, D_EMERG, NULL);     \
                cfs_trace_assertion_failed("ASSERTION("#cond") failed", \
                                           &msgdata);                   \
        }                                                               \
} while (0)
Definition at line 306 of file tracefile.h.
Referenced by cfs_tage_free(), cfs_tage_to_tail(), cfs_trace_get_tage_try(), cfs_trace_lock_tcd(), cfs_trace_unlock_tcd(), cfs_tracefile_dump_all_pages(), libcfs_debug_vmsg2(), put_pages_on_tcd_daemon_list(), and tracefiled().
#define __LASSERT_TAGE_INVARIANT (tage)
Value:
do {                                                                    \
        __LASSERT(tage != NULL);                                        \
        __LASSERT(tage->page != NULL);                                  \
        __LASSERT(tage->used <= PAGE_CACHE_SIZE);                         \
        __LASSERT(page_count(tage->page) > 0);                      \
} while (0)
Definition at line 315 of file tracefile.h.
Referenced by cfs_trace_debug_print(), cfs_trace_flush_pages(), cfs_tracefile_dump_all_pages(), put_pages_back_on_all_cpus(), put_pages_on_tcd_daemon_list(), trace_cleanup_on_all_cpus(), and tracefiled().
#define cfs_tcd_for_each (tcd, i, j)
Value:
for (i = 0; cfs_trace_data[i] != NULL; i++)                               \
        for (j = 0, ((tcd) = &(*cfs_trace_data[i])[j].tcd);               \
             j < num_possible_cpus();                                     \
             j++, (tcd) = &(*cfs_trace_data[i])[j].tcd)
Definition at line 196 of file tracefile.h.
Referenced by cfs_trace_get_debug_mb(), cfs_trace_set_debug_mb(), cfs_tracefile_init(), cfs_tracefile_init_arch(), and panic_collect_pages().
#define cfs_tcd_for_each_type_lock (tcd, i, cpu)
Value:
for (i = 0; cfs_trace_data[i] &&                                      \
         (tcd = &(*cfs_trace_data[i])[cpu].tcd) &&                        \
         cfs_trace_lock_tcd(tcd, 1); cfs_trace_unlock_tcd(tcd, 1), i++)
Definition at line 202 of file tracefile.h.
Referenced by collect_pages_on_all_cpus(), put_pages_back_on_all_cpus(), put_pages_on_daemon_list(), and trace_cleanup_on_all_cpus().
#define CFS_TRACE_CONSOLE_BUFFER_SIZE 1024
Definition at line 115 of file tracefile.h.
Referenced by cfs_tracefile_init_arch(), and libcfs_debug_vmsg2().
#define CFS_TRACEFILE_SIZE (500 << 20)
Definition at line 111 of file tracefile.h.
#define CFS_TRACEFILE_SIZE (500 << 20)
Definition at line 111 of file tracefile.h.
Referenced by cfs_trace_daemon_command().
#define TCD_MAX_PAGES (5 << (20 - PAGE_CACHE_SHIFT))
Definition at line 108 of file tracefile.h.
#define TCD_MAX_PAGES (5 << (20 - PAGE_CACHE_SHIFT))
Definition at line 108 of file tracefile.h.
Referenced by libcfs_debug_init().
#define TCD_MAX_TYPES 8
Definition at line 193 of file tracefile.h.
#define TCD_STOCK_PAGES (TCD_MAX_PAGES)
Definition at line 109 of file tracefile.h.
#define TCD_STOCK_PAGES (TCD_MAX_PAGES)
Definition at line 109 of file tracefile.h.
Referenced by cfs_trace_refill_stock().
#define TRACEFILE_NAME_SIZE 1024
Definition at line 51 of file tracefile.h.
Enumeration Type Documentation
enum cfs_trace_buf_type
Enumerator:
CFS_TCD_TYPE_PROC
CFS_TCD_TYPE_SOFTIRQ
CFS_TCD_TYPE_IRQ
CFS_TCD_TYPE_MAX
Definition at line 42 of file tracefile.h.
Function Documentation
void cfs_print_to_console (struct ptldebug_header * hdr, int mask, const char * buf, int len, const char * file, const char * fn)
Definition at line 238 of file linux-tracefile.c.
References D_CONSOLE, D_EMERG, D_ERROR, D_WARNING, dbghdr_to_err_string(), dbghdr_to_info_string(), libcfs_printk, ptldebug_header::ph_extern_pid, ptldebug_header::ph_line_num, ptldebug_header::ph_pid, and printk.
Referenced by cfs_trace_assertion_failed(), cfs_trace_debug_print(), and libcfs_debug_vmsg2().
void cfs_set_ptldebug_header (struct ptldebug_header * header, struct libcfs_debug_msg_data * m, unsigned long stack)
Definition at line 191 of file linux-tracefile.c.
References cfs_trace_buf_idx_get(), libcfs_debug_msg_data::msg_line, libcfs_debug_msg_data::msg_mask, libcfs_debug_msg_data::msg_subsys, ptldebug_header::ph_cpu_id, ptldebug_header::ph_extern_pid, ptldebug_header::ph_line_num, ptldebug_header::ph_mask, ptldebug_header::ph_pid, ptldebug_header::ph_sec, ptldebug_header::ph_stack, ptldebug_header::ph_subsys, ptldebug_header::ph_type, and ptldebug_header::ph_usec.
Referenced by cfs_trace_assertion_failed(), and libcfs_debug_vmsg2().
int cfs_tcd_owns_tage (struct cfs_trace_cpu_data * tcd, struct cfs_trace_page * tage)
Definition at line 180 of file linux-tracefile.c.
References cfs_trace_page::cpu.
int cfs_trace_allocate_string_buffer (char ** str, int nob)
Definition at line 791 of file tracefile.c.
Referenced by __proc_dobitmasks(), cfs_trace_daemon_command_usrstr(), and cfs_trace_dump_debug_buffer_usrstr().
void cfs_trace_assertion_failed (const char * str, struct libcfs_debug_msg_data * m)
Definition at line 475 of file tracefile.c.
References CDEBUG_STACK, cfs_print_to_console(), cfs_set_ptldebug_header(), D_EMERG, libcfs_catastrophe, libcfs_panic_in_progress, libcfs_debug_msg_data::msg_file, and libcfs_debug_msg_data::msg_fn.
enum cfs_trace_buf_type cfs_trace_buf_idx_get (void)
Definition at line 135 of file linux-tracefile.c.
References CFS_TCD_TYPE_IRQ, CFS_TCD_TYPE_PROC, and CFS_TCD_TYPE_SOFTIRQ.
Referenced by cfs_set_ptldebug_header(), cfs_trace_get_console_buffer(), and cfs_trace_get_tcd().
int cfs_trace_copyin_string (char * knl_buffer, int knl_buffer_nob, const char __user * usr_buffer, int usr_buffer_nob)
Definition at line 739 of file tracefile.c.
References strnlen.
Referenced by __proc_dobitmasks(), __proc_lnet_portal_rotor(), cfs_trace_daemon_command_usrstr(), cfs_trace_dump_debug_buffer_usrstr(), and cfs_trace_set_debug_mb_usrstr().
int cfs_trace_copyout_string (char __user * usr_buffer, int usr_buffer_nob, const char * knl_str, char * append)
Definition at line 766 of file tracefile.c.
Referenced by __proc_cpt_table(), __proc_daemon_file(), __proc_debug_mb(), __proc_dobitmasks(), __proc_lnet_buffers(), __proc_lnet_portal_rotor(), and __proc_lnet_stats().
int cfs_trace_daemon_command (char * str)
Definition at line 827 of file tracefile.c.
References cfs_trace_start_thread(), cfs_trace_stop_thread(), cfs_tracefile, CFS_TRACEFILE_SIZE, cfs_tracefile_size, cfs_tracefile_write_lock(), cfs_tracefile_write_unlock(), and printk.
Referenced by cfs_trace_daemon_command_usrstr().
int cfs_trace_daemon_command_usrstr (void __user * usr_str, int usr_str_nob)
Definition at line 865 of file tracefile.c.
References cfs_trace_allocate_string_buffer(), cfs_trace_copyin_string(), and cfs_trace_daemon_command().
Referenced by __proc_daemon_file().
void cfs_trace_debug_print (void)
Definition at line 624 of file tracefile.c.
References __LASSERT_TAGE_INVARIANT, cfs_print_to_console(), cfs_tage_free(), collect_pages(), D_EMERG, cfs_trace_page::linkage, list_del(), list_for_each_entry_safe, cfs_trace_page::page, page_collection::pc_pages, page_collection::pc_want_daemon_pages, ptldebug_header::ph_len, and cfs_trace_page::used.
Referenced by panic_notifier().
int cfs_trace_dump_debug_buffer_usrstr (void __user * usr_str, int usr_str_nob)
Definition at line 803 of file tracefile.c.
References cfs_trace_allocate_string_buffer(), cfs_trace_copyin_string(), and cfs_tracefile_dump_all_pages().
Referenced by __proc_dump_kernel().
void cfs_trace_flush_pages (void)
Definition at line 722 of file tracefile.c.
References __LASSERT_TAGE_INVARIANT, cfs_tage_free(), collect_pages(), cfs_trace_page::linkage, list_del(), list_for_each_entry_safe, page_collection::pc_pages, and page_collection::pc_want_daemon_pages.
Referenced by libcfs_debug_clear_buffer().
static char* cfs_trace_get_console_buffer (void) [inline, static]
Definition at line 271 of file tracefile.h.
References cfs_trace_buf_idx_get().
Referenced by libcfs_debug_vmsg2().
int cfs_trace_get_debug_mb (void)
Definition at line 930 of file tracefile.c.
References cfs_tcd_for_each, cfs_tracefile_read_lock(), and cfs_tracefile_read_unlock().
Referenced by __proc_debug_mb().
static struct cfs_trace_cpu_data* cfs_trace_get_tcd (void) [static, read]
Definition at line 279 of file tracefile.h.
References cfs_trace_buf_idx_get(), cfs_trace_data, and cfs_trace_lock_tcd().
Referenced by libcfs_debug_vmsg2().
int cfs_trace_lock_tcd (struct cfs_trace_cpu_data * tcd, int walking)
Definition at line 151 of file linux-tracefile.c.
References __LASSERT, CFS_TCD_TYPE_IRQ, CFS_TCD_TYPE_MAX, CFS_TCD_TYPE_SOFTIRQ, and unlikely.
Referenced by cfs_trace_get_tcd().
int cfs_trace_max_debug_mb (void)
Definition at line 268 of file linux-tracefile.c.
References MAX.
Referenced by cfs_trace_set_debug_mb(), and libcfs_debug_init().
static void cfs_trace_put_tcd (struct cfs_trace_cpu_data * tcd) [inline, static]
Definition at line 289 of file tracefile.h.
References cfs_trace_unlock_tcd().
Referenced by libcfs_debug_vmsg2().
int cfs_trace_refill_stock (struct cfs_trace_cpu_data * tcd, gfp_t gfp, struct list_head * stock)
Definition at line 118 of file tracefile.c.
References cfs_tage_alloc(), cfs_trace_page::linkage, list_add_tail(), and TCD_STOCK_PAGES.
int cfs_trace_set_debug_mb (int mb)
Definition at line 883 of file tracefile.c.
References cfs_tcd_for_each, cfs_trace_max_debug_mb(), cfs_tracefile_write_lock(), cfs_tracefile_write_unlock(), and printk.
Referenced by cfs_trace_set_debug_mb_usrstr().
int cfs_trace_set_debug_mb_usrstr (void __user * usr_str, int usr_str_nob)
Definition at line 918 of file tracefile.c.
References cfs_trace_copyin_string(), and cfs_trace_set_debug_mb().
Referenced by __proc_debug_mb().
int cfs_trace_start_thread (void)
Definition at line 1063 of file tracefile.c.
References tracefiled_ctl::tctl_shutdown, tracefiled_ctl::tctl_start, tracefiled_ctl::tctl_stop, tracefiled_ctl::tctl_waitq, thread_running, trace_tctl, and tracefiled().
Referenced by cfs_trace_daemon_command().
void cfs_trace_stop_thread (void)
Definition at line 1089 of file tracefile.c.
References printk, tracefiled_ctl::tctl_shutdown, tracefiled_ctl::tctl_stop, thread_running, and trace_tctl.
Referenced by cfs_trace_daemon_command(), and cfs_tracefile_exit().
void cfs_trace_unlock_tcd (struct cfs_trace_cpu_data * tcd, int walking)
Definition at line 166 of file linux-tracefile.c.
References __LASSERT, CFS_TCD_TYPE_IRQ, CFS_TCD_TYPE_MAX, CFS_TCD_TYPE_SOFTIRQ, and unlikely.
Referenced by cfs_trace_put_tcd().
int cfs_tracefile_dump_all_pages (char * filename)
Definition at line 661 of file tracefile.c.
References __LASSERT, __LASSERT_TAGE_INVARIANT, __user, buf, cfs_tage_free(), cfs_tracefile_write_lock(), cfs_tracefile_write_unlock(), collect_pages(), cfs_trace_page::linkage, list_del(), list_empty(), list_for_each_entry_safe, ll_vfs_fsync_range, cfs_trace_page::page, page_collection::pc_pages, page_collection::pc_want_daemon_pages, printk, put_pages_back(), and cfs_trace_page::used.
Referenced by cfs_trace_dump_debug_buffer_usrstr(), and libcfs_debug_dumplog_internal().
void cfs_tracefile_exit (void)
Definition at line 1165 of file tracefile.c.
References cfs_trace_cleanup(), and cfs_trace_stop_thread().
Referenced by libcfs_debug_cleanup().
void cfs_tracefile_fini_arch (void)
Definition at line 97 of file linux-tracefile.c.
References cfs_trace_console_buffers, and cfs_trace_data.
Referenced by cfs_trace_cleanup(), and cfs_tracefile_init_arch().
int cfs_tracefile_init (int max_pages)
Definition at line 1104 of file tracefile.c.
References cfs_tcd_for_each, cfs_tracefile_init_arch(), INIT_LIST_HEAD, and LASSERT.
Referenced by libcfs_debug_init().
int cfs_tracefile_init_arch (void)
Definition at line 54 of file linux-tracefile.c.
References cfs_tcd_for_each, CFS_TCD_TYPE_MAX, CFS_TRACE_CONSOLE_BUFFER_SIZE, cfs_trace_console_buffers, cfs_trace_data, cfs_tracefile_fini_arch(), pages_factor, and printk.
Referenced by cfs_tracefile_init().
void cfs_tracefile_read_lock (void)
Definition at line 115 of file linux-tracefile.c.
Referenced by cfs_trace_get_debug_mb(), and tracefiled().
void cfs_tracefile_read_unlock (void)
Definition at line 120 of file linux-tracefile.c.
Referenced by cfs_trace_get_debug_mb(), and tracefiled().
void cfs_tracefile_write_lock (void)
Definition at line 125 of file linux-tracefile.c.
Referenced by cfs_trace_daemon_command(), cfs_trace_set_debug_mb(), and cfs_tracefile_dump_all_pages().
void cfs_tracefile_write_unlock (void)
Definition at line 130 of file linux-tracefile.c.
Referenced by cfs_trace_daemon_command(), cfs_trace_set_debug_mb(), and cfs_tracefile_dump_all_pages().
void libcfs_debug_dumplog_internal (void * arg)
Dump Lustre log to debug_file_path by calling tracefile_dump_all_pages().
Definition at line 219 of file debug.c.
References cfs_time_current_sec(), cfs_tracefile_dump_all_pages(), debug_file_name, libcfs_debug_file_path_arr, libcfs_run_debug_log_upcall(), LPLD, and printk.
Referenced by libcfs_debug_dumplog_thread(), and panic_notifier().
void libcfs_register_panic_notifier (void)
Definition at line 305 of file linux-debug.c.
Referenced by libcfs_debug_init().
void libcfs_run_debug_log_upcall (char * file)
Upcall function once a Lustre log has been dumped.
Parameters:
file path of the dumped log
Definition at line 79 of file linux-debug.c.
References CDEBUG, CERROR, D_HA, ENTRY, EXIT, LASSERTF, and lnet_debug_log_upcall.
Referenced by libcfs_debug_dumplog_internal().
void libcfs_unregister_panic_notifier (void)
Definition at line 310 of file linux-debug.c.
Referenced by libcfs_debug_cleanup().
Variable Documentation
char* cfs_trace_console_buffers[NR_CPUS][CFS_TCD_TYPE_MAX]
Definition at line 50 of file linux-tracefile.c.
Referenced by cfs_tracefile_fini_arch(), and cfs_tracefile_init_arch().
union cfs_trace_data_union(*[TCD_MAX_TYPES] cfs_trace_data)[NR_CPUS]
Referenced by cfs_trace_get_tcd(), cfs_tracefile_fini_arch(), and cfs_tracefile_init_arch().
char cfs_tracefile[TRACEFILE_NAME_SIZE]
Definition at line 53 of file tracefile.c.
Referenced by __proc_daemon_file(), cfs_trace_daemon_command(), and tracefiled().
long long cfs_tracefile_size
Definition at line 54 of file tracefile.c.
Referenced by cfs_trace_daemon_command(), and tracefiled().
int libcfs_panic_in_progress
Definition at line 112 of file debug.c.
Referenced by cfs_trace_assertion_failed(), collect_pages(), panic_notifier(), and put_pages_back().
char lnet_debug_log_upcall[1024]
The path of debug log dump upcall script.
Definition at line 72 of file linux-debug.c.
Referenced by libcfs_run_debug_log_upcall().
char lnet_upcall[1024]
Definition at line 71 of file linux-debug.c.
Referenced by libcfs_run_upcall().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.