Lustre: libcfs/libcfs/tracefile.c File Reference
libcfs/libcfs/tracefile.c File Reference
#include "tracefile.h"
#include <linux/kthread.h>
#include <libcfs/libcfs.h>
Defines
#define DEBUG_SUBSYSTEM S_LNET
#define LUSTRE_TRACEFILE_PRIVATE
Functions
static DEFINE_MUTEX (cfs_trace_thread_mutex)
static void put_pages_on_tcd_daemon_list (struct page_collection *pc, struct cfs_trace_cpu_data *tcd)
static struct cfs_trace_page * cfs_tage_from_list (struct list_head *list)
static struct cfs_trace_page * cfs_tage_alloc (gfp_t gfp)
static void cfs_tage_free (struct cfs_trace_page *tage)
static void cfs_tage_to_tail (struct cfs_trace_page *tage, struct list_head *queue)
int cfs_trace_refill_stock (struct cfs_trace_cpu_data *tcd, gfp_t gfp, struct list_head *stock)
static struct cfs_trace_page * cfs_trace_get_tage_try (struct cfs_trace_cpu_data *tcd, unsigned long len)
static void cfs_tcd_shrink (struct cfs_trace_cpu_data *tcd)
static struct cfs_trace_page * cfs_trace_get_tage (struct cfs_trace_cpu_data *tcd, unsigned long len)
int libcfs_debug_msg (struct libcfs_debug_msg_data *msgdata, const char *format,...)
int libcfs_debug_vmsg2 (struct libcfs_debug_msg_data *msgdata, const char *format1, va_list args, const char *format2,...)
void cfs_trace_assertion_failed (const char *str, struct libcfs_debug_msg_data *msgdata)
static void panic_collect_pages (struct page_collection *pc)
static void collect_pages_on_all_cpus (struct page_collection *pc)
static void collect_pages (struct page_collection *pc)
static void put_pages_back_on_all_cpus (struct page_collection *pc)
static void put_pages_back (struct page_collection *pc)
static void put_pages_on_daemon_list (struct page_collection *pc)
void cfs_trace_debug_print (void)
int cfs_tracefile_dump_all_pages (char *filename)
void cfs_trace_flush_pages (void)
int cfs_trace_copyin_string (char *knl_buffer, int knl_buffer_nob, const char __user *usr_buffer, int usr_buffer_nob)
int cfs_trace_copyout_string (char __user *usr_buffer, int usr_buffer_nob, const char *knl_buffer, char *append)
int cfs_trace_allocate_string_buffer (char **str, int nob)
int cfs_trace_dump_debug_buffer_usrstr (void __user *usr_str, int usr_str_nob)
int cfs_trace_daemon_command (char *str)
int cfs_trace_daemon_command_usrstr (void __user *usr_str, int usr_str_nob)
int cfs_trace_set_debug_mb (int mb)
int cfs_trace_set_debug_mb_usrstr (void __user *usr_str, int usr_str_nob)
int cfs_trace_get_debug_mb (void)
static int tracefiled (void *arg)
int cfs_trace_start_thread (void)
void cfs_trace_stop_thread (void)
int cfs_tracefile_init (int max_pages)
static void trace_cleanup_on_all_cpus (void)
static void cfs_trace_cleanup (void)
void cfs_tracefile_exit (void)
Variables
union cfs_trace_data_union(* __cacheline_aligned [TCD_MAX_TYPES] cfs_trace_data)[NR_CPUS]
char cfs_tracefile [TRACEFILE_NAME_SIZE]
long long cfs_tracefile_size = CFS_TRACEFILE_SIZE
static struct tracefiled_ctl trace_tctl
static int thread_running = 0
static atomic_t cfs_tage_allocated = ATOMIC_INIT(0)
Define Documentation
#define DEBUG_SUBSYSTEM S_LNET
Definition at line 43 of file tracefile.c.
#define LUSTRE_TRACEFILE_PRIVATE
Definition at line 44 of file tracefile.c.
Function Documentation
static struct cfs_trace_page* cfs_tage_alloc (gfp_t gfp) [static, read]
Definition at line 70 of file tracefile.c.
References cfs_tage_allocated, memory_pressure_get(), and cfs_trace_page::page.
Referenced by cfs_trace_get_tage_try(), and cfs_trace_refill_stock().
static void cfs_tage_free (struct cfs_trace_page * tage) [static]
Definition at line 99 of file tracefile.c.
References __LASSERT, cfs_tage_allocated, and cfs_trace_page::page.
Referenced by cfs_trace_debug_print(), cfs_trace_flush_pages(), cfs_tracefile_dump_all_pages(), put_pages_on_tcd_daemon_list(), and trace_cleanup_on_all_cpus().
static struct cfs_trace_page* cfs_tage_from_list (struct list_head * list) [static, read]
Definition at line 65 of file tracefile.c.
References cfs_trace_page::linkage, and list_entry.
Referenced by cfs_trace_get_tage(), cfs_trace_get_tage_try(), and put_pages_on_tcd_daemon_list().
static void cfs_tage_to_tail (struct cfs_trace_page * tage, struct list_head * queue) [static]
Definition at line 109 of file tracefile.c.
References __LASSERT, cfs_trace_page::linkage, and list_move_tail().
Referenced by cfs_trace_get_tage(), put_pages_back_on_all_cpus(), and put_pages_on_tcd_daemon_list().
static void cfs_tcd_shrink (struct cfs_trace_cpu_data * tcd) [static]
Definition at line 187 of file tracefile.c.
References INIT_LIST_HEAD, cfs_trace_page::linkage, list_for_each_entry_safe, list_move_tail(), page_collection::pc_pages, printk, and put_pages_on_tcd_daemon_list().
Referenced by cfs_trace_get_tage().
int cfs_trace_allocate_string_buffer (char ** str, int nob)
Definition at line 791 of file tracefile.c.
Referenced by __proc_dobitmasks(), cfs_trace_daemon_command_usrstr(), and cfs_trace_dump_debug_buffer_usrstr().
void cfs_trace_assertion_failed (const char * str, struct libcfs_debug_msg_data * msgdata)
Definition at line 475 of file tracefile.c.
References CDEBUG_STACK, cfs_print_to_console(), cfs_set_ptldebug_header(), D_EMERG, libcfs_catastrophe, libcfs_panic_in_progress, libcfs_debug_msg_data::msg_file, and libcfs_debug_msg_data::msg_fn.
static void cfs_trace_cleanup (void) [static]
Definition at line 1154 of file tracefile.c.
References cfs_tracefile_fini_arch(), INIT_LIST_HEAD, page_collection::pc_pages, and trace_cleanup_on_all_cpus().
Referenced by cfs_tracefile_exit().
int cfs_trace_copyin_string (char * knl_buffer, int knl_buffer_nob, const char __user * usr_buffer, int usr_buffer_nob)
Definition at line 739 of file tracefile.c.
References strnlen.
Referenced by __proc_dobitmasks(), __proc_lnet_portal_rotor(), cfs_trace_daemon_command_usrstr(), cfs_trace_dump_debug_buffer_usrstr(), and cfs_trace_set_debug_mb_usrstr().
int cfs_trace_copyout_string (char __user * usr_buffer, int usr_buffer_nob, const char * knl_buffer, char * append)
Definition at line 766 of file tracefile.c.
Referenced by __proc_cpt_table(), __proc_daemon_file(), __proc_debug_mb(), __proc_dobitmasks(), __proc_lnet_buffers(), __proc_lnet_portal_rotor(), and __proc_lnet_stats().
int cfs_trace_daemon_command (char * str)
Definition at line 827 of file tracefile.c.
References cfs_trace_start_thread(), cfs_trace_stop_thread(), cfs_tracefile, CFS_TRACEFILE_SIZE, cfs_tracefile_size, cfs_tracefile_write_lock(), cfs_tracefile_write_unlock(), and printk.
Referenced by cfs_trace_daemon_command_usrstr().
int cfs_trace_daemon_command_usrstr (void __user * usr_str, int usr_str_nob)
Definition at line 865 of file tracefile.c.
References cfs_trace_allocate_string_buffer(), cfs_trace_copyin_string(), and cfs_trace_daemon_command().
Referenced by __proc_daemon_file().
void cfs_trace_debug_print (void)
Definition at line 624 of file tracefile.c.
References __LASSERT_TAGE_INVARIANT, cfs_print_to_console(), cfs_tage_free(), collect_pages(), D_EMERG, cfs_trace_page::linkage, list_del(), list_for_each_entry_safe, cfs_trace_page::page, page_collection::pc_pages, page_collection::pc_want_daemon_pages, ptldebug_header::ph_len, and cfs_trace_page::used.
Referenced by panic_notifier().
int cfs_trace_dump_debug_buffer_usrstr (void __user * usr_str, int usr_str_nob)
Definition at line 803 of file tracefile.c.
References cfs_trace_allocate_string_buffer(), cfs_trace_copyin_string(), and cfs_tracefile_dump_all_pages().
Referenced by __proc_dump_kernel().
void cfs_trace_flush_pages (void)
Definition at line 722 of file tracefile.c.
References __LASSERT_TAGE_INVARIANT, cfs_tage_free(), collect_pages(), cfs_trace_page::linkage, list_del(), list_for_each_entry_safe, page_collection::pc_pages, and page_collection::pc_want_daemon_pages.
Referenced by libcfs_debug_clear_buffer().
int cfs_trace_get_debug_mb (void)
Definition at line 930 of file tracefile.c.
References cfs_tcd_for_each, cfs_tracefile_read_lock(), and cfs_tracefile_read_unlock().
Referenced by __proc_debug_mb().
static struct cfs_trace_page* cfs_trace_get_tage (struct cfs_trace_cpu_data * tcd, unsigned long len) [static, read]
Definition at line 217 of file tracefile.c.
References cfs_tage_from_list(), cfs_tage_to_tail(), cfs_tcd_shrink(), cfs_trace_get_tage_try(), printk, thread_running, and cfs_trace_page::used.
Referenced by libcfs_debug_vmsg2().
static struct cfs_trace_page* cfs_trace_get_tage_try (struct cfs_trace_cpu_data * tcd, unsigned long len) [static, read]
Definition at line 141 of file tracefile.c.
References __LASSERT, cfs_tage_alloc(), cfs_tage_from_list(), cfs_trace_page::cpu, cfs_trace_page::linkage, list_add_tail(), list_del_init(), list_empty(), memory_pressure_get(), printk, tracefiled_ctl::tctl_waitq, thread_running, trace_tctl, cfs_trace_page::type, unlikely, and cfs_trace_page::used.
Referenced by cfs_trace_get_tage().
int cfs_trace_refill_stock (struct cfs_trace_cpu_data * tcd, gfp_t gfp, struct list_head * stock)
Definition at line 118 of file tracefile.c.
References cfs_tage_alloc(), cfs_trace_page::linkage, list_add_tail(), and TCD_STOCK_PAGES.
int cfs_trace_set_debug_mb (int mb)
Definition at line 883 of file tracefile.c.
References cfs_tcd_for_each, cfs_trace_max_debug_mb(), cfs_tracefile_write_lock(), cfs_tracefile_write_unlock(), and printk.
Referenced by cfs_trace_set_debug_mb_usrstr().
int cfs_trace_set_debug_mb_usrstr (void __user * usr_str, int usr_str_nob)
Definition at line 918 of file tracefile.c.
References cfs_trace_copyin_string(), and cfs_trace_set_debug_mb().
Referenced by __proc_debug_mb().
int cfs_trace_start_thread (void)
Definition at line 1063 of file tracefile.c.
References tracefiled_ctl::tctl_shutdown, tracefiled_ctl::tctl_start, tracefiled_ctl::tctl_stop, tracefiled_ctl::tctl_waitq, thread_running, trace_tctl, and tracefiled().
Referenced by cfs_trace_daemon_command().
void cfs_trace_stop_thread (void)
Definition at line 1089 of file tracefile.c.
References printk, tracefiled_ctl::tctl_shutdown, tracefiled_ctl::tctl_stop, thread_running, and trace_tctl.
Referenced by cfs_trace_daemon_command(), and cfs_tracefile_exit().
int cfs_tracefile_dump_all_pages (char * filename)
Definition at line 661 of file tracefile.c.
References __LASSERT, __LASSERT_TAGE_INVARIANT, __user, buf, cfs_tage_free(), cfs_tracefile_write_lock(), cfs_tracefile_write_unlock(), collect_pages(), cfs_trace_page::linkage, list_del(), list_empty(), list_for_each_entry_safe, ll_vfs_fsync_range, cfs_trace_page::page, page_collection::pc_pages, page_collection::pc_want_daemon_pages, printk, put_pages_back(), and cfs_trace_page::used.
Referenced by cfs_trace_dump_debug_buffer_usrstr(), and libcfs_debug_dumplog_internal().
void cfs_tracefile_exit (void)
Definition at line 1165 of file tracefile.c.
References cfs_trace_cleanup(), and cfs_trace_stop_thread().
Referenced by libcfs_debug_cleanup().
int cfs_tracefile_init (int max_pages)
Definition at line 1104 of file tracefile.c.
References cfs_tcd_for_each, cfs_tracefile_init_arch(), INIT_LIST_HEAD, and LASSERT.
Referenced by libcfs_debug_init().
static void collect_pages (struct page_collection * pc) [static]
Definition at line 536 of file tracefile.c.
References collect_pages_on_all_cpus(), INIT_LIST_HEAD, libcfs_panic_in_progress, panic_collect_pages(), and page_collection::pc_pages.
Referenced by cfs_trace_debug_print(), cfs_trace_flush_pages(), cfs_tracefile_dump_all_pages(), and tracefiled().
static void collect_pages_on_all_cpus (struct page_collection * pc) [static]
Definition at line 518 of file tracefile.c.
References cfs_tcd_for_each_type_lock, list_splice_init(), page_collection::pc_pages, and page_collection::pc_want_daemon_pages.
Referenced by collect_pages().
static DEFINE_MUTEX (cfs_trace_thread_mutex) [static]
int libcfs_debug_msg (struct libcfs_debug_msg_data * msgdata, const char * format, ...)
Definition at line 246 of file tracefile.c.
References libcfs_debug_vmsg2().
int libcfs_debug_vmsg2 (struct libcfs_debug_msg_data * msgdata, const char * format1, va_list args, const char * format2, ...)
Definition at line 260 of file tracefile.c.
References __LASSERT, CDEBUG_STACK, cfs_print_to_console(), cfs_set_ptldebug_header(), cfs_time_after(), cfs_time_current(), cfs_time_seconds(), CFS_TRACE_CONSOLE_BUFFER_SIZE, cfs_trace_get_console_buffer(), cfs_trace_get_tage(), cfs_trace_get_tcd(), cfs_trace_put_tcd(), D_ERROR, libcfs_console_backoff, libcfs_console_max_delay, libcfs_console_min_delay, libcfs_console_ratelimit, libcfs_debug_binary, libcfs_printk, libcfs_debug_msg_data::msg_cdls, libcfs_debug_msg_data::msg_file, libcfs_debug_msg_data::msg_fn, libcfs_debug_msg_data::msg_line, libcfs_debug_msg_data::msg_mask, cfs_trace_page::page, PH_FLAG_FIRST_RECORD, ptldebug_header::ph_flags, ptldebug_header::ph_len, printk, and cfs_trace_page::used.
static void panic_collect_pages (struct page_collection * pc) [static]
Definition at line 495 of file tracefile.c.
References cfs_tcd_for_each, INIT_LIST_HEAD, list_splice_init(), page_collection::pc_pages, and page_collection::pc_want_daemon_pages.
Referenced by collect_pages().
static void put_pages_back (struct page_collection * pc) [static]
Definition at line 573 of file tracefile.c.
References libcfs_panic_in_progress, and put_pages_back_on_all_cpus().
Referenced by cfs_tracefile_dump_all_pages(), and tracefiled().
static void put_pages_back_on_all_cpus (struct page_collection * pc) [static]
Definition at line 546 of file tracefile.c.
References __LASSERT_TAGE_INVARIANT, cfs_tage_to_tail(), cfs_tcd_for_each_type_lock, cfs_trace_page::cpu, cfs_trace_page::linkage, list_for_each_entry_safe, list_head::next, page_collection::pc_pages, and cfs_trace_page::type.
Referenced by put_pages_back().
static void put_pages_on_daemon_list (struct page_collection * pc) [static]
Definition at line 613 of file tracefile.c.
References cfs_tcd_for_each_type_lock, and put_pages_on_tcd_daemon_list().
Referenced by tracefiled().
static void put_pages_on_tcd_daemon_list (struct page_collection * pc, struct cfs_trace_cpu_data * tcd) [static]
Definition at line 583 of file tracefile.c.
References __LASSERT, __LASSERT_TAGE_INVARIANT, cfs_tage_free(), cfs_tage_from_list(), cfs_tage_to_tail(), cfs_trace_page::cpu, cfs_trace_page::linkage, list_del(), list_empty(), list_for_each_entry_safe, page_collection::pc_pages, and cfs_trace_page::type.
Referenced by cfs_tcd_shrink(), and put_pages_on_daemon_list().
static void trace_cleanup_on_all_cpus (void) [static]
Definition at line 1132 of file tracefile.c.
References __LASSERT_TAGE_INVARIANT, cfs_tage_free(), cfs_tcd_for_each_type_lock, cfs_trace_page::cpu, cfs_trace_page::linkage, list_del(), and list_for_each_entry_safe.
Referenced by cfs_trace_cleanup().
static int tracefiled (void * arg) [static]
Definition at line 947 of file tracefile.c.
References __LASSERT, __LASSERT_TAGE_INVARIANT, __user, buf, cfs_time_seconds(), cfs_tracefile, cfs_tracefile_read_lock(), cfs_tracefile_read_unlock(), cfs_tracefile_size, collect_pages(), cfs_trace_page::cpu, list_empty(), list_for_each_entry_safe, cfs_trace_page::page, page_collection::pc_pages, page_collection::pc_want_daemon_pages, printk, put_pages_back(), put_pages_on_daemon_list(), tracefiled_ctl::tctl_shutdown, tracefiled_ctl::tctl_start, tracefiled_ctl::tctl_stop, tracefiled_ctl::tctl_waitq, and cfs_trace_page::used.
Referenced by cfs_trace_start_thread().
Variable Documentation
union cfs_trace_data_union(* __cacheline_aligned[TCD_MAX_TYPES] cfs_trace_data)[NR_CPUS]
Definition at line 51 of file tracefile.c.
atomic_t cfs_tage_allocated = ATOMIC_INIT(0) [static]
Definition at line 59 of file tracefile.c.
Referenced by cfs_tage_alloc(), and cfs_tage_free().
char cfs_tracefile[TRACEFILE_NAME_SIZE]
Definition at line 53 of file tracefile.c.
Referenced by __proc_daemon_file(), cfs_trace_daemon_command(), and tracefiled().
long long cfs_tracefile_size = CFS_TRACEFILE_SIZE
Definition at line 54 of file tracefile.c.
Referenced by cfs_trace_daemon_command(), and tracefiled().
int thread_running = 0 [static]
Definition at line 57 of file tracefile.c.
Referenced by cfs_trace_get_tage(), cfs_trace_get_tage_try(), cfs_trace_start_thread(), and cfs_trace_stop_thread().
struct tracefiled_ctl trace_tctl [static]
Definition at line 55 of file tracefile.c.
Referenced by cfs_trace_get_tage_try(), cfs_trace_start_thread(), and cfs_trace_stop_thread().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.