Lustre: lustre/obdclass/upcall_cache.c File Reference
lustre/obdclass/upcall_cache.c File Reference
#include <libcfs/libcfs.h>
#include <lnet/types.h>
#include <upcall_cache.h>
Defines
#define DEBUG_SUBSYSTEM S_SEC
Functions
static struct upcall_cache_entry * alloc_entry (struct upcall_cache *cache, __u64 key, void *args)
static void free_entry (struct upcall_cache *cache, struct upcall_cache_entry *entry)
static int upcall_compare (struct upcall_cache *cache, struct upcall_cache_entry *entry, __u64 key, void *args)
static int downcall_compare (struct upcall_cache *cache, struct upcall_cache_entry *entry, __u64 key, void *args)
static void get_entry (struct upcall_cache_entry *entry)
static void put_entry (struct upcall_cache *cache, struct upcall_cache_entry *entry)
static int check_unlink_entry (struct upcall_cache *cache, struct upcall_cache_entry *entry)
static int refresh_entry (struct upcall_cache *cache, struct upcall_cache_entry *entry)
struct upcall_cache_entry * upcall_cache_get_entry (struct upcall_cache *cache, __u64 key, void *args)
void upcall_cache_put_entry (struct upcall_cache *cache, struct upcall_cache_entry *entry)
int upcall_cache_downcall (struct upcall_cache *cache, __u32 err, __u64 key, void *args)
void upcall_cache_flush (struct upcall_cache *cache, int force)
void upcall_cache_flush_one (struct upcall_cache *cache, __u64 key, void *args)
struct upcall_cache * upcall_cache_init (const char *name, const char *upcall, struct upcall_cache_ops *ops)
void upcall_cache_cleanup (struct upcall_cache *cache)
Define Documentation
#define DEBUG_SUBSYSTEM S_SEC
Definition at line 40 of file upcall_cache.c.
Function Documentation
static struct upcall_cache_entry* alloc_entry (struct upcall_cache * cache, __u64 key, void * args) [static, read]
Definition at line 46 of file upcall_cache.c.
References upcall_cache_ops::init_entry, INIT_LIST_HEAD, LIBCFS_ALLOC, UC_CACHE_SET_NEW, upcall_cache::uc_ops, upcall_cache_entry::ue_hash, upcall_cache_entry::ue_key, upcall_cache_entry::ue_refcount, and upcall_cache_entry::ue_waitq.
Referenced by upcall_cache_get_entry().
static int check_unlink_entry (struct upcall_cache * cache, struct upcall_cache_entry * entry) [static]
Definition at line 118 of file upcall_cache.c.
References cfs_time_before(), cfs_time_current(), free_entry(), list_del_init(), UC_CACHE_IS_ACQUIRING, UC_CACHE_IS_INVALID, UC_CACHE_IS_VALID, UC_CACHE_SET_EXPIRED, upcall_cache_entry::ue_acquire_expire, upcall_cache_entry::ue_expire, upcall_cache_entry::ue_hash, upcall_cache_entry::ue_refcount, and upcall_cache_entry::ue_waitq.
Referenced by upcall_cache_get_entry().
static int downcall_compare (struct upcall_cache * cache, struct upcall_cache_entry * entry, __u64 key, void * args) [inline, static]
Definition at line 91 of file upcall_cache.c.
References upcall_cache_ops::downcall_compare, upcall_cache::uc_ops, and upcall_cache_entry::ue_key.
Referenced by upcall_cache_downcall().
static void free_entry (struct upcall_cache * cache, struct upcall_cache_entry * entry) [static]
Definition at line 66 of file upcall_cache.c.
References CDEBUG, D_OTHER, upcall_cache_ops::free_entry, LIBCFS_FREE, list_del(), LPU64, upcall_cache::uc_ops, upcall_cache_entry::ue_hash, and upcall_cache_entry::ue_key.
Referenced by check_unlink_entry(), put_entry(), upcall_cache_flush(), upcall_cache_flush_one(), and upcall_cache_get_entry().
static void get_entry (struct upcall_cache_entry * entry) [inline, static]
Definition at line 104 of file upcall_cache.c.
References upcall_cache_entry::ue_refcount.
Referenced by upcall_cache_downcall(), and upcall_cache_get_entry().
static void put_entry (struct upcall_cache * cache, struct upcall_cache_entry * entry) [inline, static]
Definition at line 109 of file upcall_cache.c.
References free_entry(), UC_CACHE_IS_EXPIRED, UC_CACHE_IS_INVALID, and upcall_cache_entry::ue_refcount.
Referenced by upcall_cache_downcall(), upcall_cache_get_entry(), and upcall_cache_put_entry().
static int refresh_entry (struct upcall_cache * cache, struct upcall_cache_entry * entry) [inline, static]
Definition at line 143 of file upcall_cache.c.
References upcall_cache_ops::do_upcall, LASSERT, and upcall_cache::uc_ops.
Referenced by upcall_cache_get_entry().
static int upcall_compare (struct upcall_cache * cache, struct upcall_cache_entry * entry, __u64 key, void * args) [inline, static]
Definition at line 78 of file upcall_cache.c.
References upcall_cache::uc_ops, upcall_cache_entry::ue_key, and upcall_cache_ops::upcall_compare.
Referenced by upcall_cache_flush_one(), and upcall_cache_get_entry().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.