Lustre: lustre/target/update_trans.c File Reference
lustre/target/update_trans.c File Reference
#include <linux/kthread.h>
#include <lu_target.h>
#include <lustre_log.h>
#include <lustre_update.h>
#include <obd.h>
#include <obd_class.h>
#include <tgt_internal.h>
Data Structures
struct distribute_txn_bid_data
Defines
#define DEBUG_SUBSYSTEM S_CLASS
Functions
static void top_multiple_thandle_dump (struct top_multiple_thandle *tmt, __u32 mask)
Dump top mulitple thandle.
static int sub_declare_updates_write (const struct lu_env *env, struct llog_update_record *record, struct thandle *sub_th, size_t record_size)
Declare write update to sub device.
static int sub_updates_write (const struct lu_env *env, struct llog_update_record *record, struct sub_thandle *sub_th)
write update to sub device
static int prepare_writing_updates (const struct lu_env *env, struct top_multiple_thandle *tmt)
Prepare the update records.
static int distribute_txn_commit_thread_running (struct lu_target *lut)
static int distribute_txn_commit_thread_stopped (struct lu_target *lut)
static void top_trans_committed_cb (struct top_multiple_thandle *tmt)
Top thandle commit callback.
struct sub_thandle * lookup_sub_thandle (struct top_multiple_thandle *tmt, struct dt_device *dt_dev)
struct sub_thandle * create_sub_thandle (struct top_multiple_thandle *tmt, struct dt_device *dt_dev)
static void sub_trans_commit_cb_internal (struct top_multiple_thandle *tmt, struct thandle *sub_th, int err)
static void sub_trans_commit_cb (struct lu_env *env, struct thandle *sub_th, struct dt_txn_commit_cb *cb, int err)
sub thandle commit callback
static void sub_thandle_register_commit_cb (struct sub_thandle *st, struct top_multiple_thandle *tmt)
static void sub_trans_stop_cb (struct lu_env *env, struct thandle *sub_th, struct dt_txn_commit_cb *cb, int err)
Sub thandle stop call back.
static void sub_thandle_register_stop_cb (struct sub_thandle *st, struct top_multiple_thandle *tmt)
int sub_thandle_trans_create (const struct lu_env *env, struct top_thandle *top_th, struct sub_thandle *st)
Create sub thandle.
struct thandle * top_trans_create (const struct lu_env *env, struct dt_device *master_dev)
Create the top transaction.
static int declare_updates_write (const struct lu_env *env, struct top_multiple_thandle *tmt)
Declare write update transaction.
static void distribute_txn_assign_batchid (struct top_multiple_thandle *new)
Assign batchid to the distribute transaction.
void distribute_txn_insert_by_batchid (struct top_multiple_thandle *new)
Insert distribute transaction to the distribute txn list.
static int prepare_multiple_node_trans (const struct lu_env *env, struct top_multiple_thandle *tmt)
Prepare cross-MDT operation.
int top_trans_start (const struct lu_env *env, struct dt_device *master_dev, struct thandle *th)
start the top transaction.
static bool top_check_write_updates (struct top_thandle *top_th)
Check whether we need write updates record.
static bool top_trans_is_stopped (struct top_thandle *top_th)
Check if top transaction is stopped.
static int top_trans_wait_result (struct top_thandle *top_th)
Wait result of top transaction.
int top_trans_stop (const struct lu_env *env, struct dt_device *master_dev, struct thandle *th)
Stop the top transaction.
int top_trans_create_tmt (const struct lu_env *env, struct top_thandle *top_th)
Create top_multiple_thandle for top_thandle.
static struct sub_thandle * create_sub_thandle_with_thandle (struct top_thandle *top_th, struct thandle *sub_th)
struct thandle * thandle_get_sub_by_dt (const struct lu_env *env, struct thandle *th, struct dt_device *sub_dt)
Get sub thandle.
void top_multiple_thandle_destroy (struct top_multiple_thandle *tmt)
Top multiple thandle destroy.
static int distribute_txn_cancel_records (const struct lu_env *env, struct top_multiple_thandle *tmt)
Cancel the update log on MDTs.
static bool tdtd_ready_for_cancel_log (struct target_distribute_txn_data *tdtd)
Check if there are committed transaction.
static void distribute_txn_batchid_cb (struct lu_env *env, struct thandle *th, struct dt_txn_commit_cb *cb, int err)
callback of updating commit batchid
static int distribute_txn_commit_batchid_update (const struct lu_env *env, struct target_distribute_txn_data *tdtd, __u64 batchid)
Update the commit batchid in disk.
static int distribute_txn_commit_batchid_init (const struct lu_env *env, struct target_distribute_txn_data *tdtd)
Init commit batchid for distribute transaction.
static int distribute_txn_commit_thread (void *_arg)
manage the distribute transaction thread
int distribute_txn_init (const struct lu_env *env, struct lu_target *lut, struct target_distribute_txn_data *tdtd, __u32 index)
Start llog cancel thread.
void distribute_txn_fini (const struct lu_env *env, struct target_distribute_txn_data *tdtd)
Stop llog cancel thread.
Define Documentation
#define DEBUG_SUBSYSTEM S_CLASS
Definition at line 50 of file update_trans.c.
Function Documentation
struct sub_thandle* create_sub_thandle (struct top_multiple_thandle * tmt, struct dt_device * dt_dev) [read]
Definition at line 436 of file update_trans.c.
References INIT_LIST_HEAD, list_add(), OBD_ALLOC_PTR, RETURN, sub_thandle::st_cookie_list, sub_thandle::st_dt, sub_thandle::st_sub_list, and top_multiple_thandle::tmt_sub_thandle_list.
Referenced by create_sub_thandle_with_thandle(), and update_recovery_exec().
static struct sub_thandle* create_sub_thandle_with_thandle (struct top_thandle * top_th, struct thandle * sub_th) [static, read]
Definition at line 1134 of file update_trans.c.
References create_sub_thandle(), sub_thandle::st_sub_th, sub_thandle_register_stop_cb(), thandle::th_dev, thandle::th_top, top_thandle::tt_multiple_thandle, and top_thandle::tt_super.
Referenced by thandle_get_sub_by_dt().
static int declare_updates_write (const struct lu_env * env, struct top_multiple_thandle * tmt) [static]
Declare write update transaction.
Check if there are updates being recorded in this transaction, it will write the record into the disk.
Parameters:
[in] env execution environment
[in] tmt top multiple transaction handle
Return values:
0 if writing succeeds
negative errno if writing fails
Definition at line 638 of file update_trans.c.
References list_for_each_entry, sub_thandle::st_sub_list, sub_thandle::st_sub_th, sub_declare_updates_write(), top_multiple_thandle::tmt_record_size, top_multiple_thandle::tmt_sub_thandle_list, top_multiple_thandle::tmt_update_records, and thandle_update_records::tur_update_records.
Referenced by prepare_multiple_node_trans().
static void distribute_txn_assign_batchid (struct top_multiple_thandle * new) [static]
Assign batchid to the distribute transaction.
Assign batchid to the distribute transaction
Parameters:
[in] tmt distribute transaction
Definition at line 667 of file update_trans.c.
References D_INFO, dt2lu_dev(), LASSERT, lu_device::ld_site, list_add_tail(), list_for_each_entry, lu_site::ls_tgt, lu_target::lut_tdtd, sub_thandle::st_sub_list, sub_thandle::st_sub_th, sub_thandle_register_commit_cb(), target_distribute_txn_data::tdtd_batchid, target_distribute_txn_data::tdtd_batchid_lock, target_distribute_txn_data::tdtd_list, top_multiple_thandle_dump(), and top_multiple_thandle_get().
Referenced by prepare_multiple_node_trans().
static void distribute_txn_batchid_cb (struct lu_env * env, struct thandle * th, struct dt_txn_commit_cb * cb, int err) [static]
callback of updating commit batchid
Updating commit batchid then wake up the commit thread to cancel the records.
Parameters:
[in] execution environment
[in] thandle to updating commit batchid
[in] commit callback
[in] result of thandle
Definition at line 1367 of file update_trans.c.
References CDEBUG, D_HA, distribute_txn_bid_data::dtbd_batchid, distribute_txn_bid_data::dtbd_tdtd, lu_target::lut_obd, OBD_FREE_PTR, obd_device::obd_name, obd_device::obd_no_transno, target_distribute_txn_data::tdtd_batchid_lock, target_distribute_txn_data::tdtd_commit_thread_waitq, target_distribute_txn_data::tdtd_committed_batchid, target_distribute_txn_data::tdtd_lut, and target_distribute_txn_data::tdtd_refcount.
Referenced by distribute_txn_commit_batchid_update().
static int distribute_txn_cancel_records (const struct lu_env * env, struct top_multiple_thandle * tmt) [static]
Cancel the update log on MDTs.
Cancel the update log on MDTs then destroy the thandle.
Parameters:
[in] env execution environment
[in] tmt the top multiple thandle whose updates records will be cancelled.
Return values:
0 if cancellation succeeds.
negative errno if cancellation fails.
Definition at line 1277 of file update_trans.c.
References CDEBUG, D_HA, D_INFO, dt_device::dd_lu_dev, DOSTID, ENTRY, fid_is_zero(), lu_device::ld_obd, llog_cookie::lgc_index, llog_cookie::lgc_lgl, llog_logid::lgl_oi, list_for_each_entry, llog_cat_cancel_records(), llog_ctxt_put(), llog_get_context(), LLOG_UPDATELOG_ORIG_CTXT, llog_ctxt::loc_handle, obd_device::obd_name, ost_id::oi_fid, POSTID, RETURN, sub_thandle::st_cookie_list, sub_thandle::st_dt, sub_thandle::st_sub_list, sub_thandle_cookie::stc_cookie, sub_thandle_cookie::stc_list, top_multiple_thandle::tmt_batchid, top_multiple_thandle::tmt_sub_thandle_list, and top_multiple_thandle_dump().
Referenced by distribute_txn_commit_thread().
static int distribute_txn_commit_batchid_init (const struct lu_env * env, struct target_distribute_txn_data * tdtd) [static]
Init commit batchid for distribute transaction.
Initialize the batchid object and get commit batchid from the object.
Parameters:
[in] env execution environment
[in] tdtd distribute transaction whose batchid is initialized.
Return values:
0 if initialization succeeds.
negative errno if initialization fails.
Definition at line 1474 of file update_trans.c.
References __u64, BATCHID_COMMITTED_OID, CDEBUG, CERROR, D_HA, dt_object::do_lu, dt_object_format::dof_type, dt_find_or_create(), dt_mode_to_dft(), dt_read(), ENTRY, GOTO, lu_attr::la_mode, LA_MODE, lu_attr::la_valid, lu_buf::lb_buf, lu_buf::lb_len, le64_to_cpu, lu_local_obj_fid(), lu_object_put(), lu_target::lut_bottom, lu_target::lut_obd, obd_device::obd_name, target_distribute_txn_data::tdtd_batchid_obj, target_distribute_txn_data::tdtd_committed_batchid, target_distribute_txn_data::tdtd_lut, tgt_th_info(), tgt_thread_info::tti_attr, tgt_thread_info::tti_fid1, tgt_thread_info::tti_u, and tgt_thread_info::update.
Referenced by distribute_txn_init().
static int distribute_txn_commit_batchid_update (const struct lu_env * env, struct target_distribute_txn_data * tdtd, __u64 batchid) [static]
Update the commit batchid in disk.
Update commit batchid in the disk, after this is committed, it can start to cancel the update records.
Parameters:
[in] env execution environment
[in] tdtd distribute transaction structure
[in] batchid commit batchid to be updated
Return values:
0 if update succeeds.
negative errno if update fails.
Definition at line 1405 of file update_trans.c.
References __u64, CDEBUG, cpu_to_le64, D_INFO, dt_txn_commit_cb::dcb_func, distribute_txn_batchid_cb(), dt_declare_record_write(), dt_record_write(), dt_trans_cb_add(), dt_trans_create(), dt_trans_start_local(), dt_trans_stop(), distribute_txn_bid_data::dtbd_batchid, distribute_txn_bid_data::dtbd_cb, distribute_txn_bid_data::dtbd_tdtd, ENTRY, GOTO, lu_buf::lb_buf, lu_buf::lb_len, LPU64, lu_target::lut_bottom, lu_target::lut_obd, OBD_ALLOC_PTR, OBD_FREE_PTR, obd_device::obd_name, RETURN, stop, target_distribute_txn_data::tdtd_batchid_obj, target_distribute_txn_data::tdtd_lut, and target_distribute_txn_data::tdtd_refcount.
Referenced by distribute_txn_commit_thread().
static int distribute_txn_commit_thread (void * _arg) [static]
manage the distribute transaction thread
Distribute transaction are linked to the list, and once the distribute transaction is committed, it will update the last committed batchid first, after it is committed, it will cancel the records.
Parameters:
[in] _arg argument for commit thread
Return values:
0 if thread is running successfully
negative errno if the thread can not be run.
Definition at line 1544 of file update_trans.c.
References __u64, CDEBUG, D_HA, D_INFO, distribute_txn_cancel_records(), distribute_txn_commit_batchid_update(), distribute_txn_commit_thread_running(), ENTRY, INIT_LIST_HEAD, l_wait_event, LASSERTF, LCT_LOCAL, LCT_MD_THREAD, list_del_init(), list_for_each_entry_safe, list_move_tail(), LPU64, lu_env_fini(), lu_env_init(), lu_target::lut_obd, lu_target::lut_tdtd_commit_thread, obd_device::obd_name, obd_device::obd_recovering, RETURN, SVC_RUNNING, SVC_STOPPED, ptlrpc_thread::t_ctl_waitq, ptlrpc_thread::t_flags, target_distribute_txn_data::tdtd_batchid_lock, target_distribute_txn_data::tdtd_commit_thread_waitq, target_distribute_txn_data::tdtd_committed_batchid, target_distribute_txn_data::tdtd_list, target_distribute_txn_data::tdtd_lut, tdtd_ready_for_cancel_log(), target_distribute_txn_data::tdtd_refcount, thread, top_multiple_thandle::tmt_batchid, top_multiple_thandle::tmt_commit_list, top_multiple_thandle::tmt_committed, top_multiple_thandle::tmt_result, top_multiple_thandle_dump(), and top_multiple_thandle_put().
Referenced by distribute_txn_init().
static int distribute_txn_commit_thread_running (struct lu_target * lut) [inline, static]
Definition at line 390 of file update_trans.c.
References lu_target::lut_tdtd_commit_thread, SVC_RUNNING, and ptlrpc_thread::t_flags.
Referenced by distribute_txn_commit_thread(), distribute_txn_fini(), distribute_txn_init(), and top_trans_committed_cb().
static int distribute_txn_commit_thread_stopped (struct lu_target * lut) [inline, static]
Definition at line 396 of file update_trans.c.
References lu_target::lut_tdtd_commit_thread, SVC_STOPPED, and ptlrpc_thread::t_flags.
Referenced by distribute_txn_init().
void distribute_txn_fini (const struct lu_env * env, struct target_distribute_txn_data * tdtd)
Stop llog cancel thread.
Stop llog cancel(master/slave) thread on LOD and also destory all of transaction in the list.
Parameters:
[in] cancel log thread to be stopped.
Definition at line 1732 of file update_trans.c.
References distribute_txn_commit_thread_running(), dt_object::do_lu, dtrq_list_destroy(), lu_object_put(), lu_target::lut_tdtd_commit_thread, SVC_STOPPED, SVC_STOPPING, ptlrpc_thread::t_ctl_waitq, ptlrpc_thread::t_flags, target_distribute_txn_data::tdtd_batchid_lock, target_distribute_txn_data::tdtd_batchid_obj, target_distribute_txn_data::tdtd_commit_thread_waitq, and target_distribute_txn_data::tdtd_lut.
Referenced by lod_fini_distribute_txn().
int distribute_txn_init (const struct lu_env * env, struct lu_target * lut, struct target_distribute_txn_data * tdtd, __u32 index)
Start llog cancel thread.
Start llog cancel(master/slave) thread on LOD
Parameters:
[in] cancel log thread to be started.
Return values:
0 if the thread is started successfully.
negative errno if the thread is not being started.
Definition at line 1681 of file update_trans.c.
References distribute_txn_commit_batchid_init(), distribute_txn_commit_thread(), distribute_txn_commit_thread_running(), distribute_txn_commit_thread_stopped(), distribute_txn_replay_handle(), ENTRY, INIT_LIST_HEAD, l_wait_event, lu_target::lut_last_transno, lu_target::lut_tdtd_commit_thread, RETURN, ptlrpc_thread::t_ctl_waitq, target_distribute_txn_data::tdtd_batchid, target_distribute_txn_data::tdtd_batchid_lock, target_distribute_txn_data::tdtd_commit_thread_waitq, target_distribute_txn_data::tdtd_list, target_distribute_txn_data::tdtd_lut, target_distribute_txn_data::tdtd_recovery_threads_count, target_distribute_txn_data::tdtd_recovery_threads_waitq, target_distribute_txn_data::tdtd_refcount, target_distribute_txn_data::tdtd_replay_finish_list, target_distribute_txn_data::tdtd_replay_handler, target_distribute_txn_data::tdtd_replay_list, target_distribute_txn_data::tdtd_replay_list_lock, and target_distribute_txn_data::tdtd_replay_ready.
Referenced by lod_prepare_distribute_txn().
void distribute_txn_insert_by_batchid (struct top_multiple_thandle * new)
Insert distribute transaction to the distribute txn list.
Insert distribute transaction to the distribute txn list.
Parameters:
[in] new the distribute txn to be inserted.
Definition at line 694 of file update_trans.c.
References D_INFO, dt2lu_dev(), LASSERT, lu_device::ld_site, list_add(), list_empty(), list_for_each_entry, list_for_each_entry_reverse, lu_site::ls_tgt, lu_target::lut_tdtd, sub_thandle::st_sub_list, sub_thandle::st_sub_th, sub_thandle_register_commit_cb(), target_distribute_txn_data::tdtd_batchid_lock, target_distribute_txn_data::tdtd_commit_thread_waitq, target_distribute_txn_data::tdtd_list, top_multiple_thandle::tmt_batchid, top_multiple_thandle::tmt_commit_list, top_multiple_thandle_dump(), and top_multiple_thandle_get().
Referenced by distribute_txn_replay_handle().
struct sub_thandle* lookup_sub_thandle (struct top_multiple_thandle * tmt, struct dt_device * dt_dev) [read]
Definition at line 423 of file update_trans.c.
References list_for_each_entry, sub_thandle::st_dt, sub_thandle::st_sub_list, and top_multiple_thandle::tmt_sub_thandle_list.
Referenced by distribute_txn_replay_handle(), thandle_get_sub_by_dt(), top_trans_stop(), and update_recovery_exec().
static int prepare_multiple_node_trans (const struct lu_env * env, struct top_multiple_thandle * tmt) [static]
Prepare cross-MDT operation.
Create the update record buffer to record updates for cross-MDT operation, add master sub transaction to tt_sub_trans_list, and declare the update writes.
During updates packing, all of parameters will be packed in tur_update_params, and updates will be packed in tur_update_records. Then in transaction stop, parameters and updates will be merged into one updates buffer.
And also master thandle will be added to the sub_th list, so it will be easy to track the commit status.
Parameters:
[in] env execution environment
[in] th top transaction handle
Return values:
0 if preparation succeeds.
negative errno if preparation fails.
Definition at line 750 of file update_trans.c.
References check_and_prepare_update_record(), declare_updates_write(), distribute_txn_assign_batchid(), ENTRY, RETURN, top_multiple_thandle::tmt_update_records, update_env_info(), and update_thread_info::uti_tur.
Referenced by top_trans_start().
static int prepare_writing_updates (const struct lu_env * env, struct top_multiple_thandle * tmt) [static]
Prepare the update records.
Merge params and ops into the update records, then initializing the update buffer.
During transaction execution phase, parameters and update ops are collected in two different buffers (see lod_updates_pack()), during transaction stop, it needs to be merged in one buffer, so it will be written in the update log.
Parameters:
[in] env execution environment
[in] tmt top_multiple_thandle for distribute txn
Return values:
0 if merging succeeds.
negaitive errno if merging fails.
Definition at line 343 of file update_trans.c.
References cfs_size_round(), D_INFO, LASSERT, llog_update_record_size(), llog_rec_hdr::lrh_len, llog_rec_hdr::lrh_type, lur, llog_update_record::lur_hdr, llog_update_record::lur_update_rec, top_multiple_thandle::tmt_batchid, top_multiple_thandle::tmt_update_records, thandle_update_records::tur_update_param_count, thandle_update_records::tur_update_params, thandle_update_records::tur_update_records, thandle_update_records::tur_update_records_buf_size, tur_update_records_extend(), update_params_size(), UPDATE_REC, update_records_dump(), update_records_get_params(), update_records::ur_batchid, and update_records::ur_param_count.
Referenced by top_trans_stop().
static int sub_declare_updates_write (const struct lu_env * env, struct llog_update_record * record, struct thandle * sub_th, size_t record_size) [static]
Declare write update to sub device.
Declare Write updates llog records to the sub device during distribute transaction.
Parameters:
[in] env execution environment
[in] record update records being written
[in] sub_th sub transaction handle
[in] record_size total update record size
Return values:
0 if writing succeeds
negative errno if writing fails
Definition at line 112 of file update_trans.c.
References dt_device::dd_lu_dev, GOTO, lu_device::ld_obd, llog_ctxt_put(), llog_declare_add(), llog_get_context(), LLOG_UPDATELOG_ORIG_CTXT, llog_ctxt::loc_chunk_size, llog_ctxt::loc_handle, llog_update_record::lur_hdr, and thandle::th_dev.
Referenced by declare_updates_write().
static void sub_thandle_register_commit_cb (struct sub_thandle * st, struct top_multiple_thandle * tmt) [static]
Definition at line 502 of file update_trans.c.
References dt_txn_commit_cb::dcb_data, dt_txn_commit_cb::dcb_func, dt_txn_commit_cb::dcb_linkage, dt_trans_cb_add(), INIT_LIST_HEAD, LASSERT, sub_thandle::st_commit_dcb, sub_thandle::st_sub_th, sub_trans_commit_cb(), and top_multiple_thandle_get().
Referenced by distribute_txn_assign_batchid(), and distribute_txn_insert_by_batchid().
static void sub_thandle_register_stop_cb (struct sub_thandle * st, struct top_multiple_thandle * tmt) [static]
Definition at line 545 of file update_trans.c.
References dt_txn_commit_cb::dcb_data, dt_txn_commit_cb::dcb_flags, dt_txn_commit_cb::dcb_func, dt_txn_commit_cb::dcb_linkage, DCB_TRANS_STOP, dt_trans_cb_add(), INIT_LIST_HEAD, sub_thandle::st_stop_dcb, sub_thandle::st_sub_th, and sub_trans_stop_cb().
Referenced by create_sub_thandle_with_thandle(), and sub_thandle_trans_create().
int sub_thandle_trans_create (const struct lu_env * env, struct top_thandle * top_th, struct sub_thandle * st)
Create sub thandle.
Create transaction handle for sub_thandle
Parameters:
[in] env execution environment
[in] th top thandle
[in] st sub_thandle
Return values:
0 if creation succeeds.
negative errno if creation fails.
Definition at line 567 of file update_trans.c.
References dt_trans_create(), sub_thandle::st_dt, sub_thandle::st_sub_th, sub_thandle_register_stop_cb(), thandle::th_top, thandle::th_wait_submit, top_thandle::tt_multiple_thandle, and top_thandle::tt_super.
Referenced by update_recovery_exec().
static void sub_trans_commit_cb (struct lu_env * env, struct thandle * sub_th, struct dt_txn_commit_cb * cb, int err) [static]
sub thandle commit callback
Mark the sub thandle to be committed and if all sub thandle are committed notify the top thandle.
Parameters:
[in] env execution environment
[in] sub_th sub thandle being committed
[in] cb commit callback
[in] err trans result
Definition at line 493 of file update_trans.c.
References dt_txn_commit_cb::dcb_data, and sub_trans_commit_cb_internal().
Referenced by sub_thandle_register_commit_cb().
static void sub_trans_commit_cb_internal (struct top_multiple_thandle * tmt, struct thandle * sub_th, int err) [static]
Definition at line 453 of file update_trans.c.
References D_INFO, list_for_each_entry, RETURN_EXIT, sub_thandle::st_committed, sub_thandle::st_result, sub_thandle::st_sub_list, sub_thandle::st_sub_th, top_multiple_thandle::tmt_result, top_multiple_thandle::tmt_sub_lock, top_multiple_thandle::tmt_sub_thandle_list, top_multiple_thandle_dump(), top_multiple_thandle_put(), and top_trans_committed_cb().
Referenced by sub_trans_commit_cb(), and top_trans_stop().
static void sub_trans_stop_cb (struct lu_env * env, struct thandle * sub_th, struct dt_txn_commit_cb * cb, int err) [static]
Sub thandle stop call back.
After sub thandle is stopped, it will call this callback to notify the top thandle.
Parameters:
[in] th sub thandle to be stopped
[in] rc result of sub trans
Definition at line 522 of file update_trans.c.
References dt_txn_commit_cb::dcb_data, ENTRY, list_for_each_entry, RETURN_EXIT, sub_thandle::st_dt, sub_thandle::st_result, sub_thandle::st_stopped, thandle::th_dev, top_multiple_thandle::tmt_stop_waitq, and top_multiple_thandle::tmt_sub_thandle_list.
Referenced by sub_thandle_register_stop_cb().
static int sub_updates_write (const struct lu_env * env, struct llog_update_record * record, struct sub_thandle * sub_th) [static]
write update to sub device
Write llog update record to the sub device during distribute transaction. If it succeeds, llog cookie of the record will be returned by .
Parameters:
[in] env execution environment
[in] record update records being written
[in] sub_th sub transaction handle
[out] cookie llog cookie of the update record.
Return values:
1 if writing succeeds
negative errno if writing fails
Definition at line 167 of file update_trans.c.
References CDEBUG, cfs_size_round(), D_INFO, dt_device::dd_lu_dev, DOSTID, ENTRY, GOTO, INIT_LIST_HEAD, LASSERT, LASSERTF, lu_device::ld_obd, llog_cookie::lgc_index, llog_cookie::lgc_lgl, llog_logid::lgl_oi, likely, list_add(), llog_add(), llog_ctxt_put(), llog_get_context(), LLOG_MIN_REC_SIZE, llog_update_record_size(), LLOG_UPDATELOG_ORIG_CTXT, llog_ctxt::loc_chunk_size, llog_ctxt::loc_handle, llog_rec_hdr::lrh_len, lur, llog_update_record::lur_hdr, llog_update_record::lur_update_rec, OBD_ALLOC_LARGE, OBD_ALLOC_PTR, OBD_FREE_LARGE, OBD_FREE_PTR, obd_device::obd_name, object_update_param_size(), POSTID, RETURN, sub_thandle::st_cookie_list, sub_thandle::st_dt, sub_thandle::st_sub_th, start, sub_thandle_cookie::stc_cookie, sub_thandle_cookie::stc_list, update_op_next_op(), UPDATE_RECORD_CONTINUE, update_records_dump(), update_records_get_params(), update_records::ur_flags, update_records::ur_ops, update_records::ur_param_count, and update_records::ur_update_count.
Referenced by top_trans_stop().
static bool tdtd_ready_for_cancel_log (struct target_distribute_txn_data * tdtd) [static]
Check if there are committed transaction.
Check if there are committed transaction in the distribute transaction list, then cancel the update records for those committed transaction. Because the distribute transaction in the list are sorted by batchid, and cancellation will be done by batchid order, so we only check the first the transaction(with lowest batchid) in the list.
Parameters:
[in] lod lod device where cancel thread is
Return values:
true if it is ready
false if it is not ready
Definition at line 1330 of file update_trans.c.
References list_empty(), list_entry, lu_target::lut_obd, list_head::next, obd_device::obd_recovering, target_distribute_txn_data::tdtd_batchid_lock, target_distribute_txn_data::tdtd_committed_batchid, target_distribute_txn_data::tdtd_list, target_distribute_txn_data::tdtd_lut, top_multiple_thandle::tmt_batchid, and top_multiple_thandle::tmt_committed.
Referenced by distribute_txn_commit_thread().
struct thandle* thandle_get_sub_by_dt (const struct lu_env * env, struct thandle * th, struct dt_device * sub_dt) [read]
Get sub thandle.
Get sub thandle from the top thandle according to the sub dt_device.
Parameters:
[in] env execution environment
[in] th thandle on the top layer.
[in] sub_dt sub dt_device used to get sub transaction
Return values:
thandle of sub transaction if succeed
PTR_ERR(errno) if failed
Definition at line 1164 of file update_trans.c.
References create_sub_thandle_with_thandle(), dt_trans_create(), dt_trans_stop(), ENTRY, GOTO, likely, list_del(), lookup_sub_thandle(), OBD_FREE_PTR, RETURN, sub_thandle::st_sub_list, sub_thandle::st_sub_th, thandle::th_dev, thandle::th_result, thandle::th_wait_submit, top_multiple_thandle::tmt_master_sub_dt, top_trans_create_tmt(), top_thandle::tt_master_sub_thandle, and top_thandle::tt_multiple_thandle.
Referenced by mdd_declare_links_add(), mdd_links_write(), osp_get_storage_thandle(), osp_sync_add_rec(), osp_sync_declare_add(), and thandle_get_sub().
static bool top_check_write_updates (struct top_thandle * top_th) [static]
Check whether we need write updates record.
Check if the updates for the top_thandle needs to be writen to all targets. Only if the transaction succeeds and the updates number > 2, it will write the updates,
[in] top_th top thandle.
Return values:
true if it needs to write updates
false if it does not need to write updates
Definition at line 844 of file update_trans.c.
References llog_update_record::lur_update_rec, thandle::th_result, top_multiple_thandle::tmt_update_records, top_thandle::tt_multiple_thandle, top_thandle::tt_super, thandle_update_records::tur_update_records, and update_records::ur_update_count.
Referenced by top_trans_stop().
void top_multiple_thandle_destroy (struct top_multiple_thandle * tmt)
Top multiple thandle destroy.
Destroy multiple thandle and all its sub thandle.
Parameters:
[in] tmt top_multiple_thandle to be destroyed.
Definition at line 1242 of file update_trans.c.
References LASSERT, list_del(), list_for_each_entry_safe, OBD_FREE_PTR, sub_thandle::st_cookie_list, sub_thandle::st_sub_list, sub_thandle_cookie::stc_list, top_multiple_thandle::tmt_magic, top_multiple_thandle::tmt_sub_thandle_list, and TOP_THANDLE_MAGIC.
Referenced by top_multiple_thandle_put().
static void top_multiple_thandle_dump (struct top_multiple_thandle * tmt, __u32 mask) [static]
Dump top mulitple thandle.
Dump top multiple thandle and all of its sub thandle to the debug log.
Parameters:
[in] debug mask
[in] top_thandle to be dumped
Definition at line 69 of file update_trans.c.
References CDEBUG, dt_device::dd_lu_dev, DOSTID, LASSERT, lu_device::ld_obd, llog_cookie::lgc_index, llog_cookie::lgc_lgl, llog_logid::lgl_oi, list_for_each_entry, LPU64, obd_device::obd_name, POSTID, sub_thandle::st_committed, sub_thandle::st_cookie_list, sub_thandle::st_dt, sub_thandle::st_stopped, sub_thandle::st_sub_list, sub_thandle::st_sub_th, sub_thandle_cookie::stc_cookie, sub_thandle_cookie::stc_list, top_multiple_thandle::tmt_batchid, top_multiple_thandle::tmt_committed, top_multiple_thandle::tmt_magic, top_multiple_thandle::tmt_master_sub_dt, top_multiple_thandle::tmt_refcount, top_multiple_thandle::tmt_result, top_multiple_thandle::tmt_sub_thandle_list, and TOP_THANDLE_MAGIC.
Referenced by distribute_txn_assign_batchid(), distribute_txn_cancel_records(), distribute_txn_commit_thread(), distribute_txn_insert_by_batchid(), sub_trans_commit_cb_internal(), and top_trans_committed_cb().
static void top_trans_committed_cb (struct top_multiple_thandle * tmt) [static]
Top thandle commit callback.
This callback will be called when all of sub transactions are committed.
Parameters:
[in] th top thandle to be committed.
Definition at line 408 of file update_trans.c.
References D_HA, distribute_txn_commit_thread_running(), dt2lu_dev(), ENTRY, LASSERT, lu_device::ld_site, lu_site::ls_tgt, lu_target::lut_tdtd, RETURN_EXIT, target_distribute_txn_data::tdtd_commit_thread_waitq, top_multiple_thandle::tmt_committed, top_multiple_thandle::tmt_master_sub_dt, top_multiple_thandle::tmt_refcount, and top_multiple_thandle_dump().
Referenced by sub_trans_commit_cb_internal().
struct thandle* top_trans_create (const struct lu_env * env, struct dt_device * master_dev) [read]
Create the top transaction.
Create the top transaction on the master device. It will create a top thandle and a sub thandle on the master device.
Parameters:
[in] env execution environment
[in] master_dev master_dev the top thandle will be created
Return values:
pointer to the created thandle.
ERR_PTR(errno) if creation failed.
Definition at line 598 of file update_trans.c.
References dt_trans_create(), OBD_ALLOC_GFP, OBD_FREE_PTR, thandle::th_tags, thandle::th_top, thandle::th_wait_submit, top_thandle::tt_master_sub_thandle, and top_thandle::tt_super.
Referenced by distribute_txn_replay_handle(), and lod_trans_create().
int top_trans_create_tmt (const struct lu_env * env, struct top_thandle * top_th)
Create top_multiple_thandle for top_thandle.
Create top_mutilple_thandle to manage the mutiple node transaction for top_thandle, and it also needs to add master sub thandle to the sub trans list now.
Parameters:
[in] env execution environment
[in] top_th the top thandle
Return values:
0 if creation succeeds
negative errno if creation fails
Definition at line 1112 of file update_trans.c.
References INIT_LIST_HEAD, OBD_ALLOC_PTR, top_multiple_thandle::tmt_commit_list, top_multiple_thandle::tmt_magic, top_multiple_thandle::tmt_refcount, top_multiple_thandle::tmt_stop_waitq, top_multiple_thandle::tmt_sub_lock, top_multiple_thandle::tmt_sub_thandle_list, TOP_THANDLE_MAGIC, and top_thandle::tt_multiple_thandle.
Referenced by distribute_txn_replay_handle(), and thandle_get_sub_by_dt().
static bool top_trans_is_stopped (struct top_thandle * top_th) [static]
Check if top transaction is stopped.
Check if top transaction is stopped, only if all sub transaction is stopped, then the top transaction is stopped.
Parameters:
[in] top_th top thandle
Return values:
true if the top transaction is stopped.
false if the top transaction is not stopped.
Definition at line 882 of file update_trans.c.
References list_for_each_entry, sub_thandle::st_result, sub_thandle::st_stopped, sub_thandle::st_sub_list, sub_thandle::st_sub_th, thandle::th_result, top_multiple_thandle::tmt_sub_thandle_list, top_thandle::tt_multiple_thandle, and top_thandle::tt_super.
Referenced by top_trans_wait_result().
int top_trans_start (const struct lu_env * env, struct dt_device * master_dev, struct thandle * th)
start the top transaction.
Start all of its sub transactions, then start master sub transaction.
Parameters:
[in] env execution environment
[in] master_dev master_dev the top thandle will be start
[in] th top thandle
Return values:
0 if transaction start succeeds.
negative errno if start fails.
Definition at line 784 of file update_trans.c.
References dt_trans_start(), ENTRY, GOTO, LASSERT, list_for_each_entry, prepare_multiple_node_trans(), RETURN, sub_thandle::st_started, sub_thandle::st_sub_th, thandle::th_dev, thandle::th_local, thandle::th_result, thandle::th_sync, thandle::th_tags, top_multiple_thandle::tmt_sub_thandle_list, top_thandle::tt_master_sub_thandle, top_thandle::tt_multiple_thandle, and top_thandle::tt_super.
Referenced by distribute_txn_replay_handle(), and lod_trans_start().
int top_trans_stop (const struct lu_env * env, struct dt_device * master_dev, struct thandle * th)
Stop the top transaction.
Stop the transaction on the master device first, then stop transactions on other sub devices.
Parameters:
[in] env execution environment
[in] master_dev master_dev the top thandle will be created
[in] th top thandle
Return values:
0 if stop transaction succeeds.
negative errno if stop transaction fails.
Definition at line 935 of file update_trans.c.
References CERROR, dt_device::dd_lu_dev, dt_trans_stop(), ENTRY, GOTO, LASSERT, lu_device::ld_obd, likely, list_empty(), list_for_each_entry, lookup_sub_thandle(), lur, llog_update_record::lur_update_rec, OBD_FREE_PTR, obd_device::obd_name, prepare_writing_updates(), RETURN, sub_thandle::st_dt, sub_thandle::st_started, sub_thandle::st_sub_th, sub_trans_commit_cb_internal(), sub_updates_write(), tgt_th_info(), thandle::th_dev, thandle::th_local, thandle::th_result, thandle::th_sync, thandle::th_tags, top_multiple_thandle::tmt_commit_list, top_multiple_thandle::tmt_master_sub_dt, top_multiple_thandle::tmt_result, top_multiple_thandle::tmt_sub_thandle_list, top_multiple_thandle::tmt_update_records, top_check_write_updates(), top_multiple_thandle_put(), top_trans_wait_result(), top_thandle::tt_master_sub_thandle, top_thandle::tt_multiple_thandle, top_thandle::tt_super, tgt_thread_info::tti_transno, thandle_update_records::tur_update_params, thandle_update_records::tur_update_records, unlikely, update_records::ur_master_transno, and update_records::ur_param_count.
Referenced by distribute_txn_replay_handle(), and lod_trans_stop().
static int top_trans_wait_result (struct top_thandle * top_th) [static]
Wait result of top transaction.
Wait until all sub transaction get its result.
Parameters:
[in] top_th top thandle.
Return values:
the result of top thandle.
Definition at line 912 of file update_trans.c.
References l_wait_event, RETURN, thandle::th_result, top_multiple_thandle::tmt_stop_waitq, top_trans_is_stopped(), top_thandle::tt_multiple_thandle, and top_thandle::tt_super.
Referenced by top_trans_stop().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.