Lustre: lustre/target/update_recovery.c File Reference
lustre/target/update_recovery.c File Reference
#include <lu_target.h>
#include <lustre_obdo.h>
#include <lustre_update.h>
#include <lustre_swab.h>
#include <md_object.h>
#include <obd.h>
#include <obd_class.h>
#include "tgt_internal.h"
Defines
#define DEBUG_SUBSYSTEM S_CLASS
Functions
static struct
distribute_txn_replay_req * dtrq_lookup (struct target_distribute_txn_data *tdtd, __u64 batchid)
Lookup distribute_txn_replay req.
static int dtrq_insert (struct target_distribute_txn_data *tdtd, struct distribute_txn_replay_req *new)
insert distribute txn replay req
static struct
distribute_txn_replay_req * dtrq_create (struct target_distribute_txn_data *tdtd, struct llog_update_record *lur)
create distribute txn replay req
struct
distribute_txn_replay_req_sub * dtrq_sub_lookup (struct distribute_txn_replay_req *dtrq, __u32 mdt_index)
Lookup distribute sub replay.
static int dtrq_sub_add_cookie (struct distribute_txn_replay_req_sub *dtrqs, struct llog_cookie *cookie)
Try to add cookie to sub distribute txn request.
static int dtrq_sub_create_and_insert (struct distribute_txn_replay_req *dtrq, struct llog_cookie *cookie, __u32 mdt_index)
Insert distribute txn sub req replay.
static int dtrq_append_updates (struct distribute_txn_replay_req *dtrq, struct update_records *record)
append updates to the current replay updates
int insert_update_records_to_replay_list (struct target_distribute_txn_data *tdtd, struct llog_update_record *lur, struct llog_cookie *cookie, __u32 mdt_index)
Insert update records to the replay list.
void dtrq_list_dump (struct target_distribute_txn_data *tdtd, unsigned int mask)
Dump updates of distribute txns.
void dtrq_destroy (struct distribute_txn_replay_req *dtrq)
Destroy distribute txn replay req.
void dtrq_list_destroy (struct target_distribute_txn_data *tdtd)
Destroy all of replay req.
struct distribute_txn_replay_req * distribute_txn_get_next_req (struct target_distribute_txn_data *tdtd)
Get next req in the replay list.
__u64 distribute_txn_get_next_transno (struct target_distribute_txn_data *tdtd)
Get next transno in the replay list, because this is the sorted list, so it will return the transno of next req in the list.
struct distribute_txn_replay_req * distribute_txn_lookup_finish_list (struct target_distribute_txn_data *tdtd, __u64 xid)
bool is_req_replayed_by_update (struct ptlrpc_request *req)
static int update_is_committed (const struct lu_env *env, struct distribute_txn_replay_req *dtrq, struct dt_object *dt_obj, struct top_thandle *top_th, struct sub_thandle *st)
Check if the update of one object is committed.
static int update_recovery_create (const struct lu_env *env, struct dt_object *dt_obj, const struct update_op *op, const struct update_params *params, struct thandle_exec_args *ta, struct thandle *th)
Implementation of different update methods for update recovery.
static int update_recovery_destroy (const struct lu_env *env, struct dt_object *dt_obj, const struct update_op *op, const struct update_params *params, struct thandle_exec_args *ta, struct thandle *th)
static int update_recovery_ref_add (const struct lu_env *env, struct dt_object *dt_obj, const struct update_op *op, const struct update_params *params, struct thandle_exec_args *ta, struct thandle *th)
static int update_recovery_ref_del (const struct lu_env *env, struct dt_object *dt_obj, const struct update_op *op, const struct update_params *params, struct thandle_exec_args *ta, struct thandle *th)
static int update_recovery_attr_set (const struct lu_env *env, struct dt_object *dt_obj, const struct update_op *op, const struct update_params *params, struct thandle_exec_args *ta, struct thandle *th)
static int update_recovery_xattr_set (const struct lu_env *env, struct dt_object *dt_obj, const struct update_op *op, const struct update_params *params, struct thandle_exec_args *ta, struct thandle *th)
static int update_recovery_index_insert (const struct lu_env *env, struct dt_object *dt_obj, const struct update_op *op, const struct update_params *params, struct thandle_exec_args *ta, struct thandle *th)
static int update_recovery_index_delete (const struct lu_env *env, struct dt_object *dt_obj, const struct update_op *op, const struct update_params *params, struct thandle_exec_args *ta, struct thandle *th)
static int update_recovery_write (const struct lu_env *env, struct dt_object *dt_obj, const struct update_op *op, const struct update_params *params, struct thandle_exec_args *ta, struct thandle *th)
static int update_recovery_xattr_del (const struct lu_env *env, struct dt_object *dt_obj, const struct update_op *op, const struct update_params *params, struct thandle_exec_args *ta, struct thandle *th)
static void update_recovery_update_ses (struct lu_env *env, struct target_distribute_txn_data *tdtd, struct thandle *th, struct thandle *master_th, struct distribute_txn_replay_req *dtrq, struct tx_arg *ta_arg)
Update session information.
static int update_recovery_exec (const struct lu_env *env, struct target_distribute_txn_data *tdtd, struct distribute_txn_replay_req *dtrq, struct thandle_exec_args *ta)
Execute updates in the update replay records.
int distribute_txn_replay_handle (struct lu_env *env, struct target_distribute_txn_data *tdtd, struct distribute_txn_replay_req *dtrq)
redo updates on MDT if needed.
Define Documentation
#define DEBUG_SUBSYSTEM S_CLASS
Definition at line 44 of file update_recovery.c.
Function Documentation
struct distribute_txn_replay_req* distribute_txn_get_next_req (struct target_distribute_txn_data * tdtd) [read]
Get next req in the replay list.
Get next req needs to be replayed, since it is a sorted list (by master MDT transno)
Parameters:
[in] tdtd distribute txn data where the replay list is
Return values:
the pointer of update recovery header
Definition at line 565 of file update_recovery.c.
References distribute_txn_replay_req::dtrq_list, list_del_init(), list_empty(), list_entry, list_head::next, target_distribute_txn_data::tdtd_replay_list, and target_distribute_txn_data::tdtd_replay_list_lock.
__u64 distribute_txn_get_next_transno (struct target_distribute_txn_data * tdtd)
Get next transno in the replay list, because this is the sorted list, so it will return the transno of next req in the list.
Parameters:
[in] tdtd distribute txn data where the replay list is
Return values:
the transno of next update in the list
Definition at line 589 of file update_recovery.c.
References __u64, CDEBUG, D_HA, distribute_txn_replay_req::dtrq_list, distribute_txn_replay_req::dtrq_master_transno, list_empty(), list_entry, LPU64, lu_target::lut_obd, list_head::next, obd_device::obd_name, target_distribute_txn_data::tdtd_lut, target_distribute_txn_data::tdtd_replay_list, and target_distribute_txn_data::tdtd_replay_list_lock.
struct distribute_txn_replay_req* distribute_txn_lookup_finish_list (struct target_distribute_txn_data * tdtd, __u64 xid) [read]
Definition at line 609 of file update_recovery.c.
References distribute_txn_replay_req::dtrq_list, distribute_txn_replay_req::dtrq_xid, list_for_each_entry, target_distribute_txn_data::tdtd_replay_finish_list, and target_distribute_txn_data::tdtd_replay_list_lock.
Referenced by is_req_replayed_by_update().
int distribute_txn_replay_handle (struct lu_env * env, struct target_distribute_txn_data * tdtd, struct distribute_txn_replay_req * dtrq)
redo updates on MDT if needed.
During DNE recovery, the recovery thread (target_recovery_thread) will call this function to replay distribute txn updates on all MDTs. It only replay updates on the MDT where the update record is missing.
If the update already exists on the MDT, then it does not need replay the updates on that MDT, and only mark the sub transaction has been committed there.
Parameters:
[in] env execution environment
[in] tdtd target distribute txn data, which holds the replay list and all parameters needed by replay process.
[in] dtrq distribute txn replay req.
Return values:
0 if replay succeeds.
negative errno if replay failes.
Definition at line 1285 of file update_recovery.c.
References CDEBUG, CERROR, class_export_put(), D_HA, distribute_txn_insert_by_batchid(), dt_object::do_lu, dt_obd_name(), distribute_txn_replay_req::dtrq_batchid, distribute_txn_replay_req::dtrq_lur, distribute_txn_replay_req::dtrq_lur_size, distribute_txn_replay_req::dtrq_master_transno, ENTRY, tx_arg::exec_fn, tx_arg::file, GOTO, LASSERT, LCT_NOREF, LCT_SERVER_SESSION, lu_env::le_ses, tx_arg::line, lu_object::lo_dev, lookup_sub_thandle(), lu2dt_dev(), lu_context_enter(), lu_context_exit(), lu_context_fini(), lu_context_init(), lu_env_refill(), lu_object_put(), llog_update_record::lur_update_rec, lu_target::lut_bottom, lu_target::lut_obd, lu_target::lut_reply_data, obd_device::obd_name, tx_arg::object, RETURN, sub_thandle::st_sub_th, thandle_exec_args::ta_argno, thandle_exec_args::ta_args, thandle_exec_args::ta_handle, target_distribute_txn_data::tdtd_committed_batchid, target_distribute_txn_data::tdtd_dt, target_distribute_txn_data::tdtd_lut, tgt_ses_info(), tgt_th_info(), thandle::th_dev, thandle::th_result, top_multiple_thandle::tmt_batchid, top_multiple_thandle::tmt_committed, top_multiple_thandle::tmt_master_sub_dt, top_multiple_thandle::tmt_update_records, top_trans_create(), top_trans_create_tmt(), top_trans_start(), top_trans_stop(), tgt_session_info::tsi_exp, top_thandle::tt_multiple_thandle, tgt_thread_info::tti_transno, thandle_update_records::tur_update_param_count, thandle_update_records::tur_update_params, thandle_update_records::tur_update_records, thandle_update_records::tur_update_records_buf_size, tx_arg::undo_fn, unlikely, update_env_info(), update_records_dump(), update_recovery_exec(), update_recovery_update_ses(), update_thread_info::uti_dtrq, update_thread_info::uti_tea, and update_thread_info::uti_tur.
Referenced by distribute_txn_init().
static int dtrq_append_updates (struct distribute_txn_replay_req * dtrq, struct update_records * record) [static]
append updates to the current replay updates
Append more updates to the existent replay update. And this is only used when combining mulitple updates into one large updates during replay.
Parameters:
[in] dtrq the update replay request where the new update records will be added.
[in] lur the new update record.
Return values:
0 if appending succeeds.
negative errno if appending fails.
Definition at line 307 of file update_recovery.c.
References D_INFO, distribute_txn_replay_req::dtrq_lur, distribute_txn_replay_req::dtrq_lur_size, distribute_txn_replay_req::dtrq_sub_list_lock, ENTRY, llog_update_record_size(), llog_rec_hdr::lrh_len, llog_update_record::lur_hdr, llog_update_record::lur_update_rec, OBD_ALLOC_LARGE, OBD_FREE_LARGE, offsetof, RETURN, update_records_dump(), update_records_size(), update_records::ur_flags, update_records::ur_index, update_records::ur_ops, update_records::ur_param_count, and update_records::ur_update_count.
Referenced by insert_update_records_to_replay_list().
static struct distribute_txn_replay_req* dtrq_create (struct target_distribute_txn_data * tdtd, struct llog_update_record * lur) [static, read]
create distribute txn replay req
Allocate distribute txn replay req according to the update records.
Parameters:
[in] tdtd target distribute txn data where replay list is.
[in] record update records from the update log.
Return values:
the pointer of distribute txn replay req if the creation succeeds.
NULL if the creation fails.
Definition at line 141 of file update_recovery.c.
References INIT_LIST_HEAD, llog_update_record_size(), llog_update_record::lur_update_rec, lu_target::lut_obd, OBD_ALLOC_LARGE, OBD_ALLOC_PTR, OBD_FREE_PTR, obd_device::obd_last_committed, RETURN, target_distribute_txn_data::tdtd_lut, update_records::ur_batchid, and update_records::ur_master_transno.
Referenced by insert_update_records_to_replay_list().
void dtrq_destroy (struct distribute_txn_replay_req * dtrq)
Destroy distribute txn replay req.
Destroy distribute txn replay req and all of subs.
Parameters:
[in] dtrq distribute txn replqy req to be destroyed.
Definition at line 499 of file update_recovery.c.
References distribute_txn_replay_req::dtrq_list, distribute_txn_replay_req::dtrq_lur, distribute_txn_replay_req::dtrq_lur_size, distribute_txn_replay_req::dtrq_sub_list, distribute_txn_replay_req::dtrq_sub_list_lock, distribute_txn_replay_req_sub::dtrqs_cookie_list, distribute_txn_replay_req_sub::dtrqs_list, LASSERT, list_del(), list_empty(), list_for_each_entry_safe, OBD_FREE_LARGE, OBD_FREE_PTR, and sub_thandle_cookie::stc_list.
Referenced by dtrq_list_destroy(), and insert_update_records_to_replay_list().
static int dtrq_insert (struct target_distribute_txn_data * tdtd, struct distribute_txn_replay_req * new) [static]
insert distribute txn replay req
Insert distribute txn replay to the replay list, and it assumes the list has been looked. Note: the replay list is a sorted list, which is sorted by master transno. It is assumed the replay list has been locked before calling this function.
Parameters:
[in] tdtd target distribute txn data where replay list is
[in] new distribute txn replay to be inserted
Return values:
0 if insertion succeeds
EEXIST if the dtrq already exists
Definition at line 98 of file update_recovery.c.
References distribute_txn_replay_req::dtrq_batchid, distribute_txn_replay_req::dtrq_list, dtrq_lookup(), distribute_txn_replay_req::dtrq_master_transno, list_add(), list_empty(), list_for_each_entry_reverse, and target_distribute_txn_data::tdtd_replay_list.
Referenced by insert_update_records_to_replay_list().
void dtrq_list_destroy (struct target_distribute_txn_data * tdtd)
Destroy all of replay req.
Destroy all of replay req in the replay list.
Parameters:
[in] tdtd target distribute txn data where the replay list is.
Definition at line 534 of file update_recovery.c.
References dtrq_destroy(), distribute_txn_replay_req::dtrq_list, list_del_init(), list_for_each_entry_safe, target_distribute_txn_data::tdtd_replay_finish_list, target_distribute_txn_data::tdtd_replay_list, and target_distribute_txn_data::tdtd_replay_list_lock.
Referenced by distribute_txn_fini().
void dtrq_list_dump (struct target_distribute_txn_data * tdtd, unsigned int mask)
Dump updates of distribute txns.
Output all of recovery updates in the distribute txn list to the debug log.
Parameters:
[in] tdtd distribute txn data where all of distribute txn are listed.
[in] mask debug mask
Definition at line 480 of file update_recovery.c.
References distribute_txn_replay_req::dtrq_list, distribute_txn_replay_req::dtrq_lur, list_for_each_entry, llog_update_record::lur_update_rec, target_distribute_txn_data::tdtd_replay_list, target_distribute_txn_data::tdtd_replay_list_lock, and update_records_dump().
static struct distribute_txn_replay_req* dtrq_lookup (struct target_distribute_txn_data * tdtd, __u64 batchid) [static, read]
Lookup distribute_txn_replay req.
Lookup distribute_txn_replay in the replay list by batchid. It is assumed the list has been locked before calling this function.
Parameters:
[in] tdtd distribute_txn_data, which holds the replay list.
[in] batchid batchid used by lookup.
Return values:
pointer of the replay if succeeds.
NULL if can not find it.
Definition at line 70 of file update_recovery.c.
References distribute_txn_replay_req::dtrq_batchid, distribute_txn_replay_req::dtrq_list, list_for_each_entry, and target_distribute_txn_data::tdtd_replay_list.
Referenced by dtrq_insert(), and insert_update_records_to_replay_list().
static int dtrq_sub_add_cookie (struct distribute_txn_replay_req_sub * dtrqs, struct llog_cookie * cookie) [static]
Try to add cookie to sub distribute txn request.
Check if the update log cookie has been added to the request, if not, add it to the dtrqs_cookie_list.
Parameters:
[in] dtrqs sub replay req where cookies to be added.
[in] cookie cookie to be added.
Return values:
0 if the cookie is adding succeeds.
negative errno if adding fails.
Definition at line 223 of file update_recovery.c.
References distribute_txn_replay_req_sub::dtrqs_cookie_list, INIT_LIST_HEAD, list_add(), and OBD_ALLOC_PTR.
Referenced by dtrq_sub_create_and_insert().
static int dtrq_sub_create_and_insert (struct distribute_txn_replay_req * dtrq, struct llog_cookie * cookie, __u32 mdt_index) [static]
Insert distribute txn sub req replay.
Allocate sub replay req and insert distribute txn replay list.
Parameters:
[in] dtrq d to be added
[in] cookie the cookie of the update record
[in] mdt_index the mdt_index of the update record
Return values:
0 if the adding succeeds.
negative errno if the adding fails.
Definition at line 254 of file update_recovery.c.
References dtrq_sub_add_cookie(), distribute_txn_replay_req::dtrq_sub_list, distribute_txn_replay_req::dtrq_sub_list_lock, dtrq_sub_lookup(), ENTRY, INIT_LIST_HEAD, list_add(), OBD_ALLOC_PTR, OBD_FREE_PTR, and RETURN.
Referenced by insert_update_records_to_replay_list().
struct distribute_txn_replay_req_sub* dtrq_sub_lookup (struct distribute_txn_replay_req * dtrq, __u32 mdt_index) [read]
Lookup distribute sub replay.
Lookup distribute sub replay in the sub list of distribute_txn_replay by mdt_index.
Parameters:
[in] distribute_txn_replay_req the distribute txn replay req to lookup
[in] mdt_index the mdt_index as the key of lookup
Return values:
the pointer of sub replay if it can be found.
NULL if it can not find.
Definition at line 197 of file update_recovery.c.
References distribute_txn_replay_req::dtrq_sub_list, distribute_txn_replay_req_sub::dtrqs_list, distribute_txn_replay_req_sub::dtrqs_mdt_index, and list_for_each_entry.
Referenced by dtrq_sub_create_and_insert(), and update_is_committed().
int insert_update_records_to_replay_list (struct target_distribute_txn_data * tdtd, struct llog_update_record * lur, struct llog_cookie * cookie, __u32 mdt_index)
Insert update records to the replay list.
Allocate distribute txn replay req and insert it into the replay list, then insert the update records into the replay req.
Parameters:
[in] tdtd distribute txn replay data where the replay list is.
[in] record the update record
[in] cookie cookie of the record
[in] index mdt index of the record
Return values:
0 if the adding succeeds.
negative errno if the adding fails.
Definition at line 373 of file update_recovery.c.
References CDEBUG, D_HA, dtrq_append_updates(), dtrq_create(), dtrq_destroy(), dtrq_insert(), distribute_txn_replay_req::dtrq_list, dtrq_lookup(), distribute_txn_replay_req::dtrq_lur, distribute_txn_replay_req::dtrq_lur_size, distribute_txn_replay_req::dtrq_master_transno, dtrq_sub_create_and_insert(), ENTRY, list_del_init(), llog_update_record_size(), LPU64, llog_update_record::lur_update_rec, lu_target::lut_obd, OBD_ALLOC_LARGE, OBD_FREE_LARGE, obd_device::obd_name, RETURN, target_distribute_txn_data::tdtd_batchid, target_distribute_txn_data::tdtd_batchid_lock, target_distribute_txn_data::tdtd_lut, target_distribute_txn_data::tdtd_replay_list_lock, UPDATE_RECORD_CONTINUE, update_records::ur_batchid, update_records::ur_flags, and update_records::ur_master_transno.
Referenced by lod_process_recovery_updates().
bool is_req_replayed_by_update (struct ptlrpc_request * req)
Definition at line 626 of file update_recovery.c.
References distribute_txn_lookup_finish_list(), lu_target::lut_tdtd, ptlrpc_request::rq_export, and ptlrpc_request::rq_xid.
static int update_is_committed (const struct lu_env * env, struct distribute_txn_replay_req * dtrq, struct dt_object * dt_obj, struct top_thandle * top_th, struct sub_thandle * st) [static]
Check if the update of one object is committed.
Check whether the update for the object is committed by checking whether the correspondent sub exists in the replay req. If it is committed, mark the committed flag in correspondent the sub thandle.
Parameters:
[in] env execution environment
[in] dtrq replay request
[in] dt_obj object for the update
[in] top_th top thandle
[in] sub_th sub thandle which the update belongs to
Return values:
1 if the update is not committed.
0 if the update is committed.
negative errno if some other failures happen.
Definition at line 659 of file update_recovery.c.
References CDEBUG, D_HA, DFID, dt_object::do_lu, dtrq_sub_lookup(), distribute_txn_replay_req_sub::dtrqs_cookie_list, ENTRY, fid_is_update_log(), fid_is_update_log_dir(), fid_oid(), fid_seq_in_fldb(), fld_range_set_type(), LASSERT, lu_device::ld_site, list_for_each_entry_safe, list_move(), lu_object::lo_dev, lu_server_fld::lsf_seq_lookup, lu_seq_range::lsr_index, lu_object_fid(), LU_SEQ_RANGE_MDT, lu_site2seq(), PFID, RETURN, seq_server_site::ss_node_id, seq_server_site::ss_server_fld, sub_thandle::st_committed, sub_thandle::st_cookie_list, sub_thandle::st_sub_th, sub_thandle_cookie::stc_list, top_multiple_thandle::tmt_committed, and top_thandle::tt_multiple_thandle.
Referenced by update_recovery_exec().
static int update_recovery_attr_set (const struct lu_env * env, struct dt_object * dt_obj, const struct update_op * op, const struct update_params * params, struct thandle_exec_args * ta, struct thandle * th) [static]
Definition at line 825 of file update_recovery.c.
References distribute_txn_replay_req::dtrq_lur, ENTRY, la_from_obdo(), LLOG_REC_HDR_NEEDS_SWABBING, lur, llog_update_record::lur_hdr, llog_update_record::lur_update_rec, lustre_get_wire_obdo(), lustre_swab_obdo(), obdo::o_valid, out_tx_attr_set, RETURN, size, update_op::uop_params_off, update_env_info(), update_params_get_param_buf(), update_records::ur_param_count, update_thread_info::uti_attr, update_thread_info::uti_dtrq, and update_thread_info::uti_obdo.
Referenced by update_recovery_exec().
static int update_recovery_create (const struct lu_env * env, struct dt_object * dt_obj, const struct update_op * op, const struct update_params * params, struct thandle_exec_args * ta, struct thandle * th) [static]
Implementation of different update methods for update recovery.
These following functions update_recovery_ implement different updates recovery methods. They will extract the parameters from the common parameters area and call correspondent dt API to redo the update.
Parameters:
[in] env execution environment
[in] op update operation to be replayed
[in] params common update parameters which holds all parameters of the operation
[in] th transaction handle
[in] declare indicate it will do declare or real execution, true means declare, false means real execution
Return values:
0 if it succeeds.
negative errno if it fails.
Definition at line 737 of file update_recovery.c.
References dt_object_format::dof_type, dt_mode_to_dft(), dt_object_exists(), distribute_txn_replay_req::dtrq_lur, ENTRY, la_from_obdo(), lu_attr::la_mode, LLOG_REC_HDR_NEEDS_SWABBING, lur, llog_update_record::lur_hdr, llog_update_record::lur_update_rec, lustre_get_wire_obdo(), lustre_swab_obdo(), obdo::o_valid, out_tx_create, RETURN, size, update_op::uop_params_off, update_env_info(), update_params_get_param_buf(), update_records::ur_param_count, update_thread_info::uti_attr, update_thread_info::uti_dtrq, and update_thread_info::uti_obdo.
Referenced by update_recovery_exec().
static int update_recovery_destroy (const struct lu_env * env, struct dt_object * dt_obj, const struct update_op * op, const struct update_params * params, struct thandle_exec_args * ta, struct thandle * th) [static]
Definition at line 780 of file update_recovery.c.
References ENTRY, out_tx_destroy, and RETURN.
Referenced by update_recovery_exec().
static int update_recovery_exec (const struct lu_env * env, struct target_distribute_txn_data * tdtd, struct distribute_txn_replay_req * dtrq, struct thandle_exec_args * ta) [static]
Execute updates in the update replay records.
Declare distribute txn replay by update records and add the updates to the execution list. Note: it will check if the update has been committed, and only execute the updates if it is not committed to disk.
Parameters:
[in] env execution environment
[in] tdtd distribute txn replay data which hold all of replay reqs and all replay parameters.
[in] dtrq distribute transaction replay req.
[in] ta thandle execute args.
Return values:
0 if declare succeeds.
negative errno if declare fails.
Definition at line 1137 of file update_recovery.c.
References CDEBUG, CERROR, create_sub_thandle(), D_HA, dt_object::do_lu, dt_locate(), dt_object_child(), distribute_txn_replay_req::dtrq_lur, ENTRY, GOTO, lu_object::lo_dev, lookup_sub_thandle(), lu2dt_dev(), lu_object_put(), lur, llog_update_record::lur_update_rec, OUT_ATTR_SET, OUT_CREATE, OUT_DESTROY, OUT_INDEX_DELETE, OUT_INDEX_INSERT, OUT_NOOP, OUT_REF_ADD, OUT_REF_DEL, OUT_WRITE, OUT_XATTR_DEL, OUT_XATTR_SET, RETURN, sub_thandle::st_sub_th, sub_thandle_trans_create(), thandle_exec_args::ta_handle, target_distribute_txn_data::tdtd_dt, thandle::th_result, top_thandle::tt_multiple_thandle, top_thandle::tt_super, update_op::uop_fid, update_op::uop_type, update_ops::uops_op, update_is_committed(), update_op_next_op(), update_records_get_params(), update_recovery_attr_set(), update_recovery_create(), update_recovery_destroy(), update_recovery_index_delete(), update_recovery_index_insert(), update_recovery_ref_add(), update_recovery_ref_del(), update_recovery_write(), update_recovery_xattr_del(), update_recovery_xattr_set(), and update_records::ur_ops.
Referenced by distribute_txn_replay_handle().
static int update_recovery_index_delete (const struct lu_env * env, struct dt_object * dt_obj, const struct update_op * op, const struct update_params * params, struct thandle_exec_args * ta, struct thandle * th) [static]
Definition at line 962 of file update_recovery.c.
References dt_key, dt_try_as_dir(), distribute_txn_replay_req::dtrq_lur, ENTRY, llog_update_record::lur_update_rec, name, out_tx_index_delete, RETURN, size, update_op::uop_params_off, update_env_info(), update_params_get_param_buf(), update_records::ur_param_count, and update_thread_info::uti_dtrq.
Referenced by update_recovery_exec().
static int update_recovery_index_insert (const struct lu_env * env, struct dt_object * dt_obj, const struct update_op * op, const struct update_params * params, struct thandle_exec_args * ta, struct thandle * th) [static]
Definition at line 908 of file update_recovery.c.
References dt_key, dt_try_as_dir(), distribute_txn_replay_req::dtrq_lur, ENTRY, fid_le_to_cpu(), le32_to_cpu, llog_update_record::lur_update_rec, name, out_tx_index_insert, dt_insert_rec::rec_fid, dt_insert_rec::rec_type, RETURN, size, update_op::uop_params_off, update_env_info(), update_params_get_param_buf(), update_records::ur_param_count, update_thread_info::uti_dtrq, and update_thread_info::uti_rec.
Referenced by update_recovery_exec().
static int update_recovery_ref_add (const struct lu_env * env, struct dt_object * dt_obj, const struct update_op * op, const struct update_params * params, struct thandle_exec_args * ta, struct thandle * th) [static]
Definition at line 795 of file update_recovery.c.
References ENTRY, out_tx_ref_add, and RETURN.
Referenced by update_recovery_exec().
static int update_recovery_ref_del (const struct lu_env * env, struct dt_object * dt_obj, const struct update_op * op, const struct update_params * params, struct thandle_exec_args * ta, struct thandle * th) [static]
Definition at line 810 of file update_recovery.c.
References ENTRY, out_tx_ref_del, and RETURN.
Referenced by update_recovery_exec().
static void update_recovery_update_ses (struct lu_env * env, struct target_distribute_txn_data * tdtd, struct thandle * th, struct thandle * master_th, struct distribute_txn_replay_req * dtrq, struct tx_arg * ta_arg) [static]
Update session information.
Update session information so tgt_txn_stop_cb()->tgt_last_rcvd_update() can be called correctly during update replay.
Parameters:
[in] env execution environment.
[in] tdtd distribute data structure of the recovering tgt.
[in] th thandle of this update replay.
[in] master_th master sub thandle.
[in] ta_arg the tx arg structure to hold the update for updating reply data.
Definition at line 1066 of file update_recovery.c.
References cfs_hash_getref(), cfs_hash_lookup(), cfs_hash_putref(), distribute_txn_replay_req::dtrq_xid, le32_to_cpu, le64_to_cpu, lsd_reply_data::lrd_client_gen, lsd_reply_data::lrd_data, lsd_reply_data::lrd_result, lsd_reply_data::lrd_transno, lsd_reply_data::lrd_xid, lu_target::lut_obd, obd_device::obd_gen_hash, size, target_distribute_txn_data::tdtd_lut, tgt_ses_info(), tgt_th_info(), tgt_session_info::tsi_client_gen, tgt_session_info::tsi_exp, tgt_session_info::tsi_opdata, tgt_session_info::tsi_result, tgt_session_info::tsi_xid, top_thandle::tt_master_sub_thandle, tx_arg::u, and tx_arg::write.
Referenced by distribute_txn_replay_handle().
static int update_recovery_write (const struct lu_env * env, struct dt_object * dt_obj, const struct update_op * op, const struct update_params * params, struct thandle_exec_args * ta, struct thandle * th) [static]
Definition at line 991 of file update_recovery.c.
References __u64, buf, distribute_txn_replay_req::dtrq_lur, ENTRY, lu_buf::lb_buf, lu_buf::lb_len, le64_to_cpu, llog_update_record::lur_update_rec, out_tx_write, RETURN, size, update_op::uop_params_off, update_env_info(), update_params_get_param_buf(), update_records::ur_param_count, update_thread_info::uti_buf, and update_thread_info::uti_dtrq.
Referenced by update_recovery_exec().
static int update_recovery_xattr_del (const struct lu_env * env, struct dt_object * dt_obj, const struct update_op * op, const struct update_params * params, struct thandle_exec_args * ta, struct thandle * th) [static]
Definition at line 1028 of file update_recovery.c.
References distribute_txn_replay_req::dtrq_lur, ENTRY, llog_update_record::lur_update_rec, name, out_tx_xattr_del, RETURN, size, update_op::uop_params_off, update_env_info(), update_params_get_param_buf(), update_records::ur_param_count, and update_thread_info::uti_dtrq.
Referenced by update_recovery_exec().
static int update_recovery_xattr_set (const struct lu_env * env, struct dt_object * dt_obj, const struct update_op * op, const struct update_params * params, struct thandle_exec_args * ta, struct thandle * th) [static]
Definition at line 861 of file update_recovery.c.
References buf, distribute_txn_replay_req::dtrq_lur, ENTRY, lu_buf::lb_buf, lu_buf::lb_len, le32_to_cpu, llog_update_record::lur_update_rec, name, out_tx_xattr_set, RETURN, size, update_op::uop_params_off, update_env_info(), update_params_get_param_buf(), update_records::ur_param_count, update_thread_info::uti_buf, and update_thread_info::uti_dtrq.
Referenced by update_recovery_exec().
Contact | About Sun | News | Employment | Privacy | Terms of Use | Trademarks | (C) 2008 Sun Microsystems, Inc.